Blender: BLI_ghash.c File Reference
BLI_ghash.c File Reference
blenlib
#include <string.h>
#include <stdlib.h>
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_mempool.h"
#include "BLI_ghash.h"
#include "BLO_sys_types.h"
Functions
GHash * BLI_ghash_new (GHashHashFP hashfp, GHashCmpFP cmpfp, const char *info)
int BLI_ghash_size (GHash *gh)
void BLI_ghash_insert (GHash *gh, void *key, void *val)
void * BLI_ghash_lookup (GHash *gh, const void *key)
int BLI_ghash_remove (GHash *gh, void *key, GHashKeyFreeFP keyfreefp, GHashValFreeFP valfreefp)
int BLI_ghash_haskey (GHash *gh, void *key)
void BLI_ghash_free (GHash *gh, GHashKeyFreeFP keyfreefp, GHashValFreeFP valfreefp)
GHashIterator * BLI_ghashIterator_new (GHash *gh)
void BLI_ghashIterator_init (GHashIterator *ghi, GHash *gh)
void BLI_ghashIterator_free (GHashIterator *ghi)
void * BLI_ghashIterator_getKey (GHashIterator *ghi)
void * BLI_ghashIterator_getValue (GHashIterator *ghi)
void BLI_ghashIterator_step (GHashIterator *ghi)
int BLI_ghashIterator_isDone (GHashIterator *ghi)
unsigned int BLI_ghashutil_ptrhash (const void *key)
int BLI_ghashutil_ptrcmp (const void *a, const void *b)
unsigned int BLI_ghashutil_inthash (const void *ptr)
int BLI_ghashutil_intcmp (const void *a, const void *b)
unsigned int BLI_ghashutil_strhash (const void *ptr)
int BLI_ghashutil_strcmp (const void *a, const void *b)
GHashPair * BLI_ghashutil_pairalloc (const void *first, int second)
unsigned int BLI_ghashutil_pairhash (const void *ptr)
int BLI_ghashutil_paircmp (const void *a, const void *b)
void BLI_ghashutil_pairfree (void *ptr)
Variables
unsigned int hashsizes []
Detailed Description
Definition in file BLI_ghash.c.
Function Documentation
void BLI_ghash_free (GHash * gh, GHashKeyFreeFP keyfreefp, GHashValFreeFP valfreefp)
Definition at line 169 of file BLI_ghash.c.
References BLI_mempool_destroy(), GHash::buckets, GHash::entrypool, i, MEM_freeN(), GHash::nbuckets, GHash::nentries, Entry::next, and NULL.
Referenced by animdata_filter_remove_duplis(), applyModifier(), BIF_freeTemplates(), BIF_makeListTemplates(), BKE_icons_free(), BKE_nlastrip_validate_name(), BLI_argsFree(), BLI_pbvh_get_grid_updates(), BLO_blendhandle_get_linkable_groups(), BM_mesh_remap(), BME_free_transdata(), bmesh_vert_separate(), BMO_op_finish(), bmw_EdgeringWalker_begin(), BMW_end(), bmw_FaceLoopWalker_begin(), bmw_LoopWalker_begin(), BMW_reset(), build_mesh_leaf_node(), cloneRigGraph(), cloth_bvh_objcollisions_nearcheck(), codegen_set_unique_ids(), ConvertCSGDescriptorsToDerivedMesh(), copy_mesh(), DNA_sdna_free(), edbm_knife_cut_exec(), edge_find_shortest_path(), free_curve_editNurb_keyIndex(), free_forest(), free_mesh_orco_hash(), free_pose_channels_hash(), free_scratch(), free_sss(), free_undoCurve(), game_copy_pose(), GPU_codegen_exit(), IMB_moviecache_free(), imb_thread_cache_exit(), imb_tile_cache_exit(), knifetool_exit(), make_object_duplilist_real(), mesh_get_x_mirror_faces(), REEB_freeArc(), RIG_freeRigGraph(), RNA_exit(), stitch_init(), strand_shade_cache_free(), tracks_map_free(), undoCurve_to_editCurve(), uv_sculpt_stroke_init(), WM_menutype_free(), wm_operatortype_free(), and wpaint_make_validmap().
int BLI_ghash_haskey (GHash * gh, void * key)
Definition at line 157 of file BLI_ghash.c.
References GHash::buckets, GHash::cmpfp, hash, GHash::hashfp, Entry::key, GHash::nbuckets, and Entry::next.
Referenced by animdata_filter_remove_duplis(), applyModifier(), BLO_blendhandle_get_linkable_groups(), bmesh_vert_separate(), BMO_slot_map_contains(), bmw_ConnectedVertexWalker_step(), bmw_ConnectedVertexWalker_visitVertex(), bmw_EdgeringWalker_step(), bmw_FaceLoopWalker_include_face(), bmw_IslandboundWalker_step(), bmw_IslandWalker_step(), bmw_LoopWalker_step(), bmw_ShellWalker_visitEdge(), bmw_UVEdgeWalker_begin(), bmw_UVEdgeWalker_step(), codegen_set_unique_ids(), ConvertCSGDescriptorsToDerivedMesh(), edge_find_shortest_path(), map_insert_vert(), nla_editbone_name_check(), RIG_reconnectControlBones(), stitch_init(), uv_sculpt_stroke_init(), and wpaint_make_validmap().
void BLI_ghash_insert (GHash * gh, void * key, void * val)
Definition at line 78 of file BLI_ghash.c.
References BLI_mempool_alloc(), GHash::buckets, GHash::cursize, GHash::entrypool, hash, GHash::hashfp, hashsizes, i, Entry::key, MEM_freeN(), MEM_mallocN(), GHash::nbuckets, GHash::nentries, Entry::next, and Entry::val.
Referenced by animdata_filter_remove_duplis(), applyModifier(), BIF_makeListTemplates(), BKE_icon_getid(), BKE_icon_set(), BKE_nlastrip_validate_name(), BLI_pbvh_get_grid_updates(), BLO_blendhandle_get_linkable_groups(), BM_mesh_remap(), BME_assign_transdata(), bmesh_vert_separate(), BMO_slot_copy(), BMO_slot_map_insert(), bmw_ConnectedVertexWalker_visitVertex(), bmw_EdgeringWalker_begin(), bmw_EdgeringWalker_step(), bmw_FaceLoopWalker_begin(), bmw_FaceLoopWalker_step(), bmw_IslandboundWalker_begin(), bmw_IslandboundWalker_step(), bmw_IslandWalker_begin(), bmw_IslandWalker_step(), bmw_LoopWalker_begin(), bmw_LoopWalker_step(), bmw_ShellWalker_visitEdge(), bmw_UVEdgeWalker_begin(), bmw_UVEdgeWalker_step(), ccd_build_deflector_hash(), cloneArc(), cloneControl(), cloneRigGraph(), codegen_set_unique_ids(), ConvertCSGDescriptorsToDerivedMesh(), copy_edge(), copy_vertex(), dag_add_node(), dupli_keyIndexHash(), ED_armature_bone_rename(), edbm_knife_cut_exec(), edge_find_shortest_path(), game_copy_pose(), get_bm_knife_edge(), get_bm_knife_vert(), get_object_orco(), gpu_parse_functions_string(), imb_global_cache_get_tile(), IMB_moviecache_put(), imb_thread_cache_get_tile(), init_editNurb_keyIndex(), init_structDNA(), internalAdd(), keyIndex_swap(), keyIndex_updateCV(), knife_get_face_kedges(), make_object_duplilist_real(), make_pose_channels_hash(), map_insert_vert(), mesh_get_x_mirror_faces(), RIG_addControlBone(), RIG_arcFromBoneChain(), RNA_def_property(), RNA_init(), set_object_orco(), sss_create_tree_mat(), stitch_init(), strand_shade_get(), strand_shade_refcount(), tracks_map_insert(), tracks_map_merge(), uv_sculpt_stroke_init(), WM_menutype_add(), WM_operatortype_append(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), WM_operatortype_append_ptr(), and wpaint_make_validmap().
void* BLI_ghash_lookup (GHash * gh, const void * key)
Definition at line 112 of file BLI_ghash.c.
References GHash::buckets, GHash::cmpfp, hash, GHash::hashfp, Entry::key, GHash::nbuckets, Entry::next, NULL, and Entry::val.
Referenced by applyModifier(), BIF_setTemplate(), BKE_icon_changed(), BKE_icon_get(), BKE_icon_set(), BLI_pbvh_get_grid_updates(), bm_edge_seg_isect(), BM_mesh_remap(), BME_assign_transdata(), BME_get_transdata(), bmesh_vert_separate(), BMO_slot_map_data_get(), ccd_build_deflector_hash(), ccd_update_deflector_hash(), cloneArc(), cloneRigGraph(), codegen_set_unique_ids(), ConvertCSGDescriptorsToDerivedMesh(), copy_edge(), copy_face(), dag_find_node(), DNA_struct_find_nr(), freeSlideVerts(), game_copy_pose(), get_bm_knife_edge(), get_bm_knife_vert(), get_next_free_id(), get_object_orco(), get_pose_channel(), getCVKeyIndex(), GPU_lookup_function(), imb_global_cache_get_tile(), IMB_moviecache_get(), imb_thread_cache_get_tile(), imb_tile_cache_tile_free(), knife_get_face_kedges(), lookUp(), make_object_duplilist_real(), map_insert_vert(), mesh_get_x_mirror_faces(), RIG_reconnectControlBones(), sample_sss(), sss_pass_done(), stitch_init(), strand_shade_get(), strand_shade_refcount(), strand_shade_unref(), tracks_map_merge(), uv_sculpt_stroke_init(), WM_menutype_find(), WM_operatortype_find(), and wpaint_make_validmap().
GHash* BLI_ghash_new (GHashHashFP hashfp, GHashCmpFP cmpfp, const char * info)
Definition at line 56 of file BLI_ghash.c.
References BLI_mempool_create(), GHash::buckets, GHash::cmpfp, GHash::cursize, GHash::entrypool, GHash::hashfp, hashsizes, MEM_mallocN(), GHash::nbuckets, and GHash::nentries.
Referenced by animdata_filter_remove_duplis(), applyModifier(), BIF_makeListTemplates(), BKE_icons_init(), BKE_nlastrip_validate_name(), BLI_argsInit(), BLI_pbvh_get_grid_updates(), BLO_blendhandle_get_linkable_groups(), BM_mesh_remap(), BME_init_transdata(), bmesh_vert_separate(), BMO_slot_copy(), BMO_slot_map_insert(), bmw_EdgeringWalker_begin(), bmw_FaceLoopWalker_begin(), BMW_init(), bmw_LoopWalker_begin(), BMW_reset(), build_mesh_leaf_node(), cloneRigGraph(), cloth_bvh_objcollisions_nearcheck(), codegen_set_unique_ids(), ConvertCSGDescriptorsToDerivedMesh(), copy_mesh(), dag_add_node(), dupli_keyIndexHash(), edbm_knife_cut_exec(), edge_find_shortest_path(), game_copy_pose(), get_object_orco(), GPU_lookup_function(), IMB_moviecache_create(), imb_thread_cache_init(), IMB_tile_cache_params(), init_editNurb_keyIndex(), init_structDNA(), knifetool_init(), make_object_duplilist_real(), make_pose_channels_hash(), make_sss_tree(), mesh_get_x_mirror_faces(), newRigGraph(), RNA_init(), sb_new_scratch(), set_object_orco(), stitch_init(), strand_shade_cache_create(), tracks_map_new(), uv_sculpt_stroke_init(), WM_menutype_init(), wm_operatortype_init(), and wpaint_make_validmap().
int BLI_ghash_remove (GHash * gh, void * key, GHashKeyFreeFP keyfreefp, GHashValFreeFP valfreefp)
Definition at line 125 of file BLI_ghash.c.
References BLI_mempool_free(), GHash::buckets, GHash::cmpfp, GHash::entrypool, hash, GHash::hashfp, Entry::key, GHash::nbuckets, GHash::nentries, Entry::next, NULL, p, and Entry::val.
Referenced by BKE_icon_delete(), check_unused_keys(), ED_armature_bone_rename(), edge_find_shortest_path(), imb_global_cache_get_tile(), IMB_moviecache_put(), imb_thread_cache_get_tile(), imb_tile_cache_tile_free(), keyIndex_delCV(), keyIndex_delNurb(), keyIndex_swap(), keyIndex_updateCV(), strand_shade_get(), strand_shade_unref(), tracks_map_merge(), WM_menutype_freelink(), WM_operatortype_remove(), and wpaint_make_validmap().
int BLI_ghash_size (GHash * gh)
Definition at line 73 of file BLI_ghash.c.
References GHash::nentries.
Referenced by applyModifier(), BIF_listTemplates(), BLI_pbvh_get_grid_updates(), BMO_slot_map_count(), IMB_moviecache_get_cache_segments(), uv_sculpt_stroke_init(), and wpaint_make_validmap().
void BLI_ghashIterator_free (GHashIterator * ghi)
Free a GHashIterator.
Parameters:
ghi The iterator to free.
Definition at line 224 of file BLI_ghash.c.
References MEM_freeN().
Referenced by applyModifier(), BLI_pbvh_get_grid_updates(), build_mesh_leaf_node(), check_unused_keys(), dupli_keyIndexHash(), free_sss(), IMB_moviecache_get_cache_segments(), operator_search_cb(), pyop_dir(), sb_detect_aabb_collisionCached(), sb_detect_edge_collisionCached(), sb_detect_face_collisionCached(), sb_detect_face_pointCached(), sb_detect_vertex_collisionCached(), stitch_init(), uv_sculpt_stroke_init(), and WM_menutype_free().
void* BLI_ghashIterator_getKey (GHashIterator * ghi)
Retrieve the key from an iterator.
Parameters:
ghi The iterator.
Returns:
The key at the current index, or NULL if the iterator is done.
Definition at line 229 of file BLI_ghash.c.
References GHashIterator::curEntry, Entry::key, and NULL.
Referenced by applyModifier(), BIF_currentTemplate(), BIF_listTemplates(), BLI_pbvh_get_grid_updates(), BMO_iter_step(), BMO_slot_map_to_flag(), build_mesh_leaf_node(), check_unused_keys(), dupli_keyIndexHash(), IMB_moviecache_get_cache_segments(), sb_detect_aabb_collisionCached(), sb_detect_edge_collisionCached(), sb_detect_face_collisionCached(), sb_detect_face_pointCached(), sb_detect_vertex_collisionCached(), stitch_init(), and uv_sculpt_stroke_init().
void* BLI_ghashIterator_getValue (GHashIterator * ghi)
Retrieve the value from an iterator.
Parameters:
ghi The iterator.
Returns:
The value at the current index, or NULL if the iterator is done.
Definition at line 233 of file BLI_ghash.c.
References GHashIterator::curEntry, NULL, and Entry::val.
Referenced by applyModifier(), BIF_currentTemplate(), BIF_listTemplates(), BMO_iter_step(), BMO_slot_copy(), build_mesh_leaf_node(), check_unused_keys(), dupli_keyIndexHash(), free_sss(), IMB_moviecache_get_cache_segments(), operator_search_cb(), pyop_dir(), RIG_reconnectControlBones(), sb_detect_aabb_collisionCached(), sb_detect_edge_collisionCached(), sb_detect_face_collisionCached(), sb_detect_face_pointCached(), sb_detect_vertex_collisionCached(), and WM_menutype_free().
void BLI_ghashIterator_init (GHashIterator * ghi, GHash * gh)
Init an already allocated GHashIterator. The hash table must not be mutated while the iterator is in use, and the iterator will step exactly BLI_ghash_size(gh) times before becoming done.
Parameters:
ghi The GHashIterator to initialize.
gh The GHash to iterate over.
Definition at line 212 of file BLI_ghash.c.
References GHash::buckets, GHashIterator::curBucket, GHashIterator::curEntry, GHashIterator::gh, GHash::nbuckets, and NULL.
Referenced by BIF_currentTemplate(), BIF_listTemplates(), BMO_iter_new(), BMO_slot_copy(), BMO_slot_map_to_flag(), RIG_reconnectControlBones(), and stitch_init().
int BLI_ghashIterator_isDone (GHashIterator * ghi)
Determine if an iterator is done (has reached the end of the hash table).
Parameters:
ghi The iterator.
Returns:
True if done, False otherwise.
Definition at line 250 of file BLI_ghash.c.
References GHashIterator::curEntry.
Referenced by applyModifier(), BIF_currentTemplate(), BIF_listTemplates(), BLI_pbvh_get_grid_updates(), build_mesh_leaf_node(), check_unused_keys(), dupli_keyIndexHash(), free_sss(), IMB_moviecache_get_cache_segments(), operator_search_cb(), pyop_dir(), RIG_reconnectControlBones(), sb_detect_aabb_collisionCached(), sb_detect_edge_collisionCached(), sb_detect_face_collisionCached(), sb_detect_face_pointCached(), sb_detect_vertex_collisionCached(), stitch_init(), uv_sculpt_stroke_init(), and WM_menutype_free().
GHashIterator* BLI_ghashIterator_new (GHash * gh)
Create a new GHashIterator. The hash table must not be mutated while the iterator is in use, and the iterator will step exactly BLI_ghash_size(gh) times before becoming done.
Parameters:
gh The GHash to iterate over.
Returns:
Pointer to a new DynStr.
Definition at line 198 of file BLI_ghash.c.
References GHash::buckets, GHashIterator::curBucket, GHashIterator::curEntry, GHashIterator::gh, MEM_mallocN(), GHash::nbuckets, and NULL.
Referenced by applyModifier(), BLI_pbvh_get_grid_updates(), build_mesh_leaf_node(), check_unused_keys(), dupli_keyIndexHash(), free_sss(), IMB_moviecache_get_cache_segments(), sb_detect_aabb_collisionCached(), sb_detect_edge_collisionCached(), sb_detect_face_collisionCached(), sb_detect_face_pointCached(), sb_detect_vertex_collisionCached(), stitch_init(), uv_sculpt_stroke_init(), WM_menutype_free(), and WM_operatortype_iter().
void BLI_ghashIterator_step (GHashIterator * ghi)
Steps the iterator to the next index.
Parameters:
ghi The iterator.
Definition at line 238 of file BLI_ghash.c.
References GHash::buckets, GHashIterator::curBucket, GHashIterator::curEntry, GHashIterator::gh, GHash::nbuckets, and Entry::next.
Referenced by applyModifier(), BIF_currentTemplate(), BIF_listTemplates(), BLI_pbvh_get_grid_updates(), BMO_iter_step(), BMO_slot_copy(), BMO_slot_map_to_flag(), build_mesh_leaf_node(), check_unused_keys(), dupli_keyIndexHash(), free_sss(), IMB_moviecache_get_cache_segments(), operator_search_cb(), pyop_dir(), RIG_reconnectControlBones(), sb_detect_aabb_collisionCached(), sb_detect_edge_collisionCached(), sb_detect_face_collisionCached(), sb_detect_face_pointCached(), sb_detect_vertex_collisionCached(), stitch_init(), uv_sculpt_stroke_init(), and WM_menutype_free().
int BLI_ghashutil_intcmp (const void * a, const void * b)
Definition at line 283 of file BLI_ghash.c.
Referenced by applyModifier(), BIF_makeListTemplates(), BKE_icons_init(), BLI_ghashutil_paircmp(), build_mesh_leaf_node(), and keycmp().
unsigned int BLI_ghashutil_inthash (const void * ptr)
Definition at line 269 of file BLI_ghash.c.
Referenced by applyModifier(), BIF_makeListTemplates(), BKE_icons_init(), BLI_ghashutil_pairhash(), build_mesh_leaf_node(), and uv_edge_hash().
GHashPair* BLI_ghashutil_pairalloc (const void * first, int second)
Definition at line 308 of file BLI_ghash.c.
References GHashPair::first, MEM_mallocN(), and GHashPair::second.
Referenced by make_object_duplilist_real().
int BLI_ghashutil_paircmp (const void * a, const void * b)
Definition at line 323 of file BLI_ghash.c.
References A, B, BLI_ghashutil_intcmp(), BLI_ghashutil_ptrcmp(), GHashPair::first, GHashPair::second, and SET_INT_IN_POINTER.
Referenced by make_object_duplilist_real().
void BLI_ghashutil_pairfree (void * ptr)
Definition at line 334 of file BLI_ghash.c.
References MEM_freeN().
Referenced by make_object_duplilist_real().
unsigned int BLI_ghashutil_pairhash (const void * ptr)
Definition at line 316 of file BLI_ghash.c.
References BLI_ghashutil_inthash(), BLI_ghashutil_ptrhash(), GHashPair::first, hash, GHashPair::second, and SET_INT_IN_POINTER.
Referenced by make_object_duplilist_real().
int BLI_ghashutil_ptrcmp (const void * a, const void * b)
Definition at line 261 of file BLI_ghash.c.
Referenced by animdata_filter_remove_duplis(), BLI_ghashutil_paircmp(), BLI_pbvh_get_grid_updates(), BLO_blendhandle_get_linkable_groups(), BM_mesh_remap(), BME_init_transdata(), bmesh_vert_separate(), BMO_slot_copy(), BMO_slot_map_insert(), bmw_EdgeringWalker_begin(), bmw_FaceLoopWalker_begin(), BMW_init(), bmw_LoopWalker_begin(), BMW_reset(), cloneRigGraph(), codegen_set_unique_ids(), ConvertCSGDescriptorsToDerivedMesh(), copy_mesh(), dag_add_node(), dupli_keyIndexHash(), edbm_knife_cut_exec(), edge_find_shortest_path(), game_copy_pose(), get_object_orco(), init_editNurb_keyIndex(), knifetool_init(), make_object_duplilist_real(), make_sss_tree(), sb_new_scratch(), set_object_orco(), strand_shade_cache_create(), and tracks_map_new().
unsigned int BLI_ghashutil_ptrhash (const void * key)
Definition at line 257 of file BLI_ghash.c.
Referenced by animdata_filter_remove_duplis(), BLI_ghashutil_pairhash(), BLI_pbvh_get_grid_updates(), BLO_blendhandle_get_linkable_groups(), BM_mesh_remap(), BME_init_transdata(), bmesh_vert_separate(), BMO_slot_copy(), BMO_slot_map_insert(), bmw_EdgeringWalker_begin(), bmw_FaceLoopWalker_begin(), BMW_init(), bmw_LoopWalker_begin(), BMW_reset(), cloneRigGraph(), codegen_set_unique_ids(), ConvertCSGDescriptorsToDerivedMesh(), copy_mesh(), dag_add_node(), dupli_keyIndexHash(), edbm_knife_cut_exec(), edge_find_shortest_path(), game_copy_pose(), get_object_orco(), init_editNurb_keyIndex(), knifetool_init(), make_object_duplilist_real(), make_sss_tree(), sb_new_scratch(), set_object_orco(), strand_shade_cache_create(), and tracks_map_new().
int BLI_ghashutil_strcmp (const void * a, const void * b)
Definition at line 303 of file BLI_ghash.c.
Referenced by applyModifier(), BKE_nlastrip_validate_name(), GPU_lookup_function(), init_structDNA(), make_pose_channels_hash(), newRigGraph(), RNA_init(), WM_menutype_init(), wm_operatortype_init(), and wpaint_make_validmap().
unsigned int BLI_ghashutil_strhash (const void * ptr)
Definition at line 291 of file BLI_ghash.c.
References i.
Referenced by applyModifier(), BKE_nlastrip_validate_name(), GPU_lookup_function(), init_structDNA(), make_pose_channels_hash(), newRigGraph(), RNA_init(), ui_popup_menu_hash(), ui_popup_string_hash(), WM_menutype_init(), wm_operatortype_init(), and wpaint_make_validmap().
Variable Documentation
unsigned int hashsizes[]
Initial value:
 {
    5, 11, 17, 37, 67, 131, 257, 521, 1031, 2053, 4099, 8209,
    16411, 32771, 65537, 131101, 262147, 524309, 1048583, 2097169,
    4194319, 8388617, 16777259, 33554467, 67108879, 134217757,
    268435459
}
Definition at line 47 of file BLI_ghash.c.
Referenced by BLI_ghash_insert(), BLI_ghash_new(), BLI_smallhash_init(), and BLI_smallhash_insert().