Blender: btContactArray Class Reference
btContactArray Class Reference
#include <btContactProcessing.h>
Public Member Functions
btContactArray ()
SIMD_FORCE_INLINE void push_contact (const btVector3 &point, const btVector3 &normal, btScalar depth, int feature1, int feature2)
SIMD_FORCE_INLINE void push_triangle_contacts (const GIM_TRIANGLE_CONTACT &tricontact, int feature1, int feature2)
void merge_contacts (const btContactArray &contacts, bool normal_contact_average=true)
void merge_contacts_unique (const btContactArray &contacts)
Detailed Description
Definition at line 111 of file btContactProcessing.h.
Constructor & Destructor Documentation
btContactArray::btContactArray () [inline]
Definition at line 114 of file btContactProcessing.h.
References btAlignedObjectArray< GIM_CONTACT >::reserve().
Member Function Documentation
void btContactArray::merge_contacts (const btContactArray & contacts, bool normal_contact_average = true)
Definition at line 68 of file btContactProcessing.cpp.
References btFabs(), btAlignedObjectArray< GIM_CONTACT >::clear(), CONTACT_DIFF_EPSILON, i, GIM_CONTACT::interpolate_normals(), GIM_CONTACT::m_depth, GIM_CONTACT::m_normal, MAX_COINCIDENT, btAlignedObjectArray< T >::push_back(), btAlignedObjectArray< GIM_CONTACT >::push_back(), btAlignedObjectArray< T >::quickSort(), btAlignedObjectArray< T >::reserve(), btAlignedObjectArray< T >::size(), and btAlignedObjectArray< GIM_CONTACT >::size().
void btContactArray::merge_contacts_unique (const btContactArray & contacts)
Definition at line 149 of file btContactProcessing.cpp.
References btAlignedObjectArray< GIM_CONTACT >::clear(), i, GIM_CONTACT::m_depth, GIM_CONTACT::m_normal, GIM_CONTACT::m_point, btAlignedObjectArray< GIM_CONTACT >::push_back(), and btAlignedObjectArray< T >::size().
SIMD_FORCE_INLINE void btContactArray::push_contact (const btVector3 & point, const btVector3 & normal, btScalar depth, int feature1, int feature2) [inline]
Definition at line 119 of file btContactProcessing.h.
References btAlignedObjectArray< GIM_CONTACT >::push_back().
Referenced by push_triangle_contacts().
SIMD_FORCE_INLINE void btContactArray::push_triangle_contacts (const GIM_TRIANGLE_CONTACT & tricontact, int feature1, int feature2) [inline]
Definition at line 126 of file btContactProcessing.h.
References i, GIM_TRIANGLE_CONTACT::m_penetration_depth, GIM_TRIANGLE_CONTACT::m_point_count, GIM_TRIANGLE_CONTACT::m_points, GIM_TRIANGLE_CONTACT::m_separating_normal, and push_contact().
The documentation for this class was generated from the following files:
btContactProcessing.h
btContactProcessing.cpp