Blender: rna_sculpt_paint.c File Reference
rna_sculpt_paint.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_ID.h"
#include "DNA_scene_types.h"
#include "DNA_brush_types.h"
#include "BKE_paint.h"
#include "WM_api.h"
#include "WM_types.h"
Functions
static void rna_def_paint (BlenderRNA *brna)
static void rna_def_sculpt (BlenderRNA *brna)
static void rna_def_uv_sculpt (BlenderRNA *brna)
static void rna_def_vertex_paint (BlenderRNA *brna)
static void rna_def_image_paint (BlenderRNA *brna)
static void rna_def_particle_edit (BlenderRNA *brna)
void RNA_def_sculpt_paint (BlenderRNA *brna)
Variables
static EnumPropertyItem particle_edit_hair_brush_items []
Detailed Description
Definition in file rna_sculpt_paint.c.
Function Documentation
static void rna_def_image_paint (BlenderRNA * brna) [static]
Definition at line 333 of file rna_sculpt_paint.c.
References IMAGEPAINT_PROJECT_BACKFACE, IMAGEPAINT_PROJECT_DISABLE, IMAGEPAINT_PROJECT_FLAT, IMAGEPAINT_PROJECT_LAYER_CLONE, IMAGEPAINT_PROJECT_LAYER_STENCIL, IMAGEPAINT_PROJECT_LAYER_STENCIL_INV, IMAGEPAINT_PROJECT_XRAY, NULL, PROP_BOOLEAN, PROP_INT, PROP_NONE, PROP_UNSIGNED, RNA_def_int_array(), RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sculpt_paint().
static void rna_def_paint (BlenderRNA * brna) [static]
Definition at line 208 of file rna_sculpt_paint.c.
References NA_EDITED, NC_BRUSH, NULL, PAINT_FAST_NAVIGATE, PAINT_SHOW_BRUSH, PAINT_SHOW_BRUSH_ON_SURFACE, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sculpt_paint().
static void rna_def_particle_edit (BlenderRNA * brna) [static]
Definition at line 388 of file rna_sculpt_paint.c.
References NC_OBJECT, ND_DRAW, NULL, PE_AUTO_VELOCITY, PE_BRUSH_DATA_PUFF_VOLUME, PE_DEFLECT_EMITTER, PE_DRAW_PART, PE_FADE_TIME, PE_INTERPOLATE_ADDED, PE_KEEP_LENGTHS, PE_LOCK_FIRST, PE_TYPE_CLOTH, PE_TYPE_PARTICLES, PE_TYPE_SOFTBODY, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SCE_SELECT_END, SCE_SELECT_PATH, and SCE_SELECT_POINT.
Referenced by RNA_def_sculpt_paint().
static void rna_def_sculpt (BlenderRNA * brna) [static]
Definition at line 236 of file rna_sculpt_paint.c.
References NC_OBJECT, ND_DRAW, NULL, PROP_BOOLEAN, PROP_INT, PROP_NONE, PROP_XYZ, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_int_default(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_text(), SCULPT_LOCK_X, SCULPT_LOCK_Y, SCULPT_LOCK_Z, SCULPT_ONLY_DEFORM, SCULPT_SYMM_X, SCULPT_SYMM_Y, SCULPT_SYMM_Z, SCULPT_SYMMETRY_FEATHER, and SCULPT_USE_OPENMP.
Referenced by RNA_def_sculpt_paint().
void RNA_def_sculpt_paint (BlenderRNA * brna)
Definition at line 560 of file rna_sculpt_paint.c.
References rna_def_image_paint(), rna_def_paint(), rna_def_particle_edit(), rna_def_sculpt(), rna_def_uv_sculpt(), and rna_def_vertex_paint().
static void rna_def_uv_sculpt (BlenderRNA * brna) [static]
Definition at line 295 of file rna_sculpt_paint.c.
References RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sculpt_paint().
static void rna_def_vertex_paint (BlenderRNA * brna) [static]
Definition at line 305 of file rna_sculpt_paint.c.
References NULL, PROP_BOOLEAN, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), VP_AREA, VP_NORMALS, VP_ONLYVGROUP, and VP_SPRAY.
Referenced by RNA_def_sculpt_paint().
Variable Documentation
EnumPropertyItem particle_edit_hair_brush_items[] [static]
Initial value:
 {
    {PE_BRUSH_NONE, "NONE", 0, "None", "Don't use any brush"},
    {PE_BRUSH_COMB, "COMB", 0, "Comb", "Comb hairs"},
    {PE_BRUSH_SMOOTH, "SMOOTH", 0, "Smooth", "Smooth hairs"},
    {PE_BRUSH_ADD, "ADD", 0, "Add", "Add hairs"},
    {PE_BRUSH_LENGTH, "LENGTH", 0, "Length", "Make hairs longer or shorter"},
    {PE_BRUSH_PUFF, "PUFF", 0, "Puff", "Make hairs stand up"},
    {PE_BRUSH_CUT, "CUT", 0, "Cut", "Cut hairs"},
    {PE_BRUSH_WEIGHT, "WEIGHT", 0, "Weight", "Weight hair particles"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 43 of file rna_sculpt_paint.c.