Blender: cycles_test.cpp File Reference
cycles_test.cpp File Reference
#include <stdio.h>
#include "buffers.h"
#include "camera.h"
#include "device.h"
#include "scene.h"
#include "session.h"
#include "util_args.h"
#include "util_foreach.h"
#include "util_function.h"
#include "util_path.h"
#include "util_progress.h"
#include "util_string.h"
#include "util_time.h"
#include "util_view.h"
#include "cycles_xml.h"
Classes
struct Options
Functions
static void session_print (const string &str)
static void session_print_status ()
static BufferParams & session_buffer_params ()
static void session_init ()
static void scene_init (int width, int height)
static void session_exit ()
static void display_info (Progress &progress)
static void display ()
static void resize (int width, int height)
void keyboard (unsigned char key)
static int files_parse (int argc, const char *argv[])
static void options_parse (int argc, const char **argv)
int main (int argc, const char **argv)
Variables
CCL_NAMESPACE_BEGIN struct Options options
Function Documentation
static void display () [static]
Definition at line 166 of file cycles_test.cpp.
References display_info(), Session::draw(), options, Session::progress, Options::session, and session_buffer_params().
Referenced by GHOST_DisplayManager::findMatch(), GHOST_DisplayManagerCarbon::getCurrentDisplaySetting(), GHOST_DisplayManagerCarbon::getDisplaySetting(), GHOST_DisplayManager::getDisplaySetting(), GHOST_DisplayManagerCarbon::getNumDisplaySettings(), GHOST_DisplayManager::getNumDisplaySettings(), GHOST_DisplayManager::initializeSettings(), main(), GHOST_DisplayManagerCarbon::setCurrentDisplaySetting(), view_main_loop(), and zbufshade_sss_tile().
static void display_info (Progress & progress) [static]
Definition at line 140 of file cycles_test.cpp.
References Progress::get_sample(), Progress::get_status(), str, string_printf(), time_dt(), and view_display_info().
Referenced by display().
static int files_parse (int argc, const char * argv[]) [static]
Definition at line 190 of file cycles_test.cpp.
References Options::filepath, and options.
Referenced by options_parse().
void keyboard (unsigned char key)
Definition at line 182 of file cycles_test.cpp.
References options, Session::progress, Session::reset(), SessionParams::samples, Options::session, session_buffer_params(), Options::session_params, and Progress::set_cancel().
Referenced by main(), and view_main_loop().
int main (int argc, const char ** argv)
Definition at line 322 of file cycles_test.cpp.
References SessionParams::background, display(), Options::filepath, Options::height, keyboard(), options, options_parse(), path_filename(), path_init(), resize(), Options::session, session_exit(), session_init(), Options::session_params, view_main_loop(), Session::wait(), and Options::width.
static void options_parse (int argc, const char ** argv) [static]
Definition at line 198 of file cycles_test.cpp.
References Device::available_devices(), Device::available_types(), SessionParams::background, CCL_NAMESPACE_END, DeviceInfo::description, SessionParams::device, DEVICE_CPU, DEVICE_NONE, DeviceInfo::display_device, Options::filepath, files_parse(), Options::height, NULL, options, SceneParams::OSL, SessionParams::output_path, Options::quiet, SessionParams::samples, scene_init(), Options::scene_params, Options::session, Options::session_params, SceneParams::shadingsystem, Device::string_from_type(), SceneParams::SVM, SessionParams::threads, DeviceInfo::type, Device::type_from_string(), types, and Options::width.
Referenced by main().
static void resize (int width, int height) [static]
Definition at line 173 of file cycles_test.cpp.
References Options::height, options, Session::reset(), SessionParams::samples, Options::session, session_buffer_params(), Options::session_params, and Options::width.
Referenced by GregoryAccStencil::GregoryAccStencil(), main(), repositionBone(), and view_main_loop().
static void scene_init (int width, int height) [static]
Definition at line 112 of file cycles_test.cpp.
References Scene::camera, Options::filepath, Options::height, options, Options::scene, Options::scene_params, Options::width, and xml_read_file().
Referenced by options_parse().
static BufferParams& session_buffer_params () [static]
Definition at line 85 of file cycles_test.cpp.
References BufferParams::full_height, BufferParams::full_width, BufferParams::height, Options::height, options, Options::width, and BufferParams::width.
Referenced by display(), keyboard(), resize(), and session_init().
static void session_exit () [static]
Definition at line 123 of file cycles_test.cpp.
References SessionParams::background, NULL, options, Options::quiet, Options::scene, Options::session, Options::session_params, and session_print().
Referenced by main().
static void session_init () [static]
Definition at line 96 of file cycles_test.cpp.
References SessionParams::background, function_bind, NULL, options, Session::progress, Options::quiet, Session::reset(), SessionParams::samples, Options::scene, Session::scene, Options::session, session_buffer_params(), Options::session_params, session_print_status(), Progress::set_update_callback(), Session::start(), and view_redraw().
Referenced by main().
static void session_print (const string & str) [static]
Definition at line 50 of file cycles_test.cpp.
References i, len(), and max.
Referenced by session_exit(), and session_print_status().
static void session_print_status () [static]
Definition at line 67 of file cycles_test.cpp.
References Progress::get_sample(), Progress::get_status(), options, Session::progress, Options::session, session_print(), and string_printf().
Referenced by session_init().
Variable Documentation
CCL_NAMESPACE_BEGIN struct Options options
Referenced by __nlFactorize_SUPERLU(), applyModifier(), AUD_JackDevice::AUD_JackDevice(), display(), files_parse(), initTransform(), keyboard(), main(), options_parse(), resize(), scene_init(), session_buffer_params(), session_exit(), session_init(), and session_print_status().