Blender: svm_noise.h File Reference
svm_noise.h File Reference
Defines
#define rot(x, k) (((x)<<(k)) | ((x)>>(32-(k))))
#define final(a, b, c)
Functions
CCL_NAMESPACE_BEGIN __device int quick_floor (float x)
__device float bits_to_01 (uint bits)
__device uint hash (uint kx, uint ky, uint kz)
__device int imod (int a, int b)
__device uint phash (int kx, int ky, int kz, int3 p)
__device float floorfrac (float x, int *i)
__device float fade (float t)
__device float nerp (float t, float a, float b)
__device float grad (int hash, float x, float y, float z)
__device float scale3 (float result)
__device_noinline float perlin (float x, float y, float z)
__device_noinline float perlin_periodic (float x, float y, float z, float3 pperiod)
__device float noise (float3 p)
__device float snoise (float3 p)
__device_noinline float cellnoise (float3 p)
__device float3 cellnoise_color (float3 p)
__device float pnoise (float3 p, float3 pperiod)
__device float psnoise (float3 p, float3 pperiod)
Define Documentation
#define final (a, b, c)
Value:
{ \
    c ^= b; c -= rot(b,14); \
    a ^= c; a -= rot(c,11); \
    b ^= a; b -= rot(a,25); \
    c ^= b; c -= rot(b,16); \
    a ^= c; a -= rot(c,4);  \
    b ^= a; b -= rot(a,14); \
    c ^= b; c -= rot(b,24); \
}
#define rot (x, k) (((x)<<(k)) | ((x)>>(32-(k))))
Referenced by TransformWriter::add_node_transform(), TransformWriter::add_node_transform_identity(), add_primitive_circle_exec(), add_primitive_cone_exec(), add_primitive_cube_exec(), add_primitive_cylinder_exec(), add_primitive_grid_exec(), add_primitive_icosphere_exec(), add_primitive_monkey_exec(), add_primitive_plane_exec(), add_primitive_uvsphere_exec(), ntlGeometryObject::applyTransformation(), IK_QOrientationTask::ComputeJacobian(), convert_pose(), convert_tree(), createRepresentation(), curvesurf_prim_add(), dblur(), do_rotate_brush(), effector_add_type(), explodeMesh(), KDL::FrameAcc::FrameAcc(), KDL::FrameVel::FrameVel(), CcdGraphicController::getAabb(), ntlGeometryObject::getInitialVelocity(), KDL::TwistVel::GetTwistDot(), group_instance_add_exec(), hash_int_2d(), IK_CreateSegment(), IK_SolverAddGoalOrientation(), ntlMatrix4x4< Scalar >::initRotationXYZ(), Matrix_decompose(), Matrix_to_scale(), ndof_orbit_invoke(), object_add_exec(), object_add_text_exec(), object_apply_mat4(), object_armature_add_exec(), object_camera_add_exec(), object_lamp_add_exec(), object_metaball_add_exec(), object_speaker_add_exec(), object_tfm_protected_backup(), object_transform_apply_exec(), KDL::Twist::operator()(), pchan_apply_mat4(), pivotcon_evaluate(), psys_cache_edit_paths(), psys_get_birth_coordinates(), psys_thread_create_path(), ptcache_particle_interpolate(), radial_control_paint_tex(), KDL::TwistVel::RefPoint(), rest_pose(), set_plane_exec(), btSliderConstraint::testAngLimits(), and txt_add_object().
Function Documentation
__device float bits_to_01 (uint bits)
Definition at line 40 of file svm_noise.h.
Referenced by cellnoise().
__device_noinline float cellnoise (float3 p)
Definition at line 182 of file svm_noise.h.
References bits_to_01(), hash, quick_floor(), float3::x, float3::y, and float3::z.
Referenced by cellnoise_color(), and noise_basis().
__device float3 cellnoise_color (float3 p)
Definition at line 191 of file svm_noise.h.
References cellnoise(), g, make_float3(), float3::x, float3::y, and float3::z.
__device float fade (float t)
Definition at line 92 of file svm_noise.h.
Referenced by do_clay_brush(), do_clay_strips_brush(), do_crease_brush(), do_draw_brush(), do_fill_brush(), do_flatten_brush(), do_grab_brush(), do_inflate_brush(), do_layer_brush(), do_mesh_smooth_brush(), do_multires_smooth_brush(), do_nudge_brush(), do_pinch_brush(), do_rotate_brush(), do_scrape_brush(), do_snake_hook_brush(), do_thumb_brush(), perlin(), and perlin_periodic().
__device float floorfrac (float x, int * i)
Definition at line 85 of file svm_noise.h.
References floorf.
Referenced by perlin(), and perlin_periodic().
__device float grad (int hash, float x, float y, float z)
Definition at line 102 of file svm_noise.h.
Referenced by btConeTwistConstraint::adjustSwingAxisToUseEllipseNormal(), fresnel_fac(), perlin(), and perlin_periodic().
__device uint hash (uint kx, uint ky, uint kz)
Definition at line 45 of file svm_noise.h.
References len().
__device int imod (int a, int b)
Definition at line 74 of file svm_noise.h.
Referenced by phash().
__device float nerp (float t, float a, float b)
Definition at line 97 of file svm_noise.h.
Referenced by perlin(), and perlin_periodic().
__device float noise (float3 p)
Definition at line 169 of file svm_noise.h.
References perlin(), float3::x, float3::y, and float3::z.
Referenced by add_node(), fcm_noise_evaluate(), and noise_basis().
__device_noinline float perlin (float x, float y, float z)
Definition at line 116 of file svm_noise.h.
References fade(), floorfrac(), grad(), hash, nerp(), scale3(), and X.
Referenced by noise(), and snoise().
__device_noinline float perlin_periodic (float x, float y, float z, float3 pperiod)
Definition at line 139 of file svm_noise.h.
References fade(), floorfrac(), grad(), max, nerp(), p, phash(), quick_floor(), scale3(), float3::x, int3::x, X, float3::y, int3::y, float3::z, and int3::z.
Referenced by pnoise(), and psnoise().
__device uint phash (int kx, int ky, int kz, int3 p)
Definition at line 80 of file svm_noise.h.
References hash, imod(), int3::x, int3::y, and int3::z.
Referenced by perlin_periodic().
__device float pnoise (float3 p, float3 pperiod)
Definition at line 201 of file svm_noise.h.
References perlin_periodic(), float3::x, float3::y, and float3::z.
__device float psnoise (float3 p, float3 pperiod)
Definition at line 208 of file svm_noise.h.
References perlin_periodic(), float3::x, float3::y, and float3::z.
CCL_NAMESPACE_BEGIN __device int quick_floor (float x)
Definition at line 35 of file svm_noise.h.
Referenced by cellnoise(), and perlin_periodic().
__device float scale3 (float result)
Definition at line 111 of file svm_noise.h.
Referenced by perlin(), and perlin_periodic().
__device float snoise (float3 p)
Definition at line 176 of file svm_noise.h.
References perlin(), float3::x, float3::y, and float3::z.
Referenced by noise_musgrave_fBm(), noise_musgrave_hetero_terrain(), noise_musgrave_hybrid_multi_fractal(), noise_musgrave_multi_fractal(), and noise_musgrave_ridged_multi_fractal().