Blender: ED_markers.h File Reference
ED_markers.h File Reference
Editors
Enumerations
enum { DRAW_MARKERS_LINES = (1<<0), DRAW_MARKERS_LOCAL = (1<<1) }
Functions
void draw_markers_time (const struct bContext *C, int flag)
ListBase * ED_context_get_markers (const struct bContext *C)
ListBase * ED_animcontext_get_markers (const struct bAnimContext *ac)
int ED_markers_post_apply_transform (ListBase *markers, struct Scene *scene, int mode, float value, char side)
struct TimeMarker * ED_markers_find_nearest_marker (ListBase *markers, float x)
int ED_markers_find_nearest_marker_time (ListBase *markers, float x)
void ED_markers_get_minmax (ListBase *markers, short sel, float *first, float *last)
void ED_markers_make_cfra_list (ListBase *markers, ListBase *lb, short sel)
struct TimeMarker * ED_markers_get_first_selected (ListBase *markers)
void ED_operatortypes_marker (void)
void ED_marker_keymap (struct wmKeyConfig *keyconf)
void ED_marker_keymap_animedit_conflictfree (struct wmKeyMap *keymap)
void debug_markers_print_list (struct ListBase *markers)
Detailed Description
Definition in file ED_markers.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
DRAW_MARKERS_LINES
DRAW_MARKERS_LOCAL
Definition at line 44 of file ED_markers.h.
Function Documentation
void debug_markers_print_list (struct ListBase * markers)
Definition at line 328 of file anim_markers.c.
References ListBase::first, TimeMarker::flag, TimeMarker::frame, TimeMarker::name, TimeMarker::next, and NULL.
void draw_markers_time (const struct bContext * C, int flag)
ListBase* ED_animcontext_get_markers (const struct bAnimContext * ac)
ListBase* ED_context_get_markers (const struct bContext * C)
void ED_marker_keymap (struct wmKeyConfig * keyconf)
Definition at line 1487 of file anim_markers.c.
References AKEY, BKEY, DELKEY, DKEY, EVT_TWEAK_S, FALSE, GKEY, KM_ANY, KM_CTRL, KM_PRESS, KM_SHIFT, MKEY, wmKeyMapItem::ptr, RNA_boolean_set(), SELECTMOUSE, TRUE, WM_keymap_add_item(), WM_keymap_find(), WM_keymap_verify_item(), and XKEY.
Referenced by ED_spacetypes_keymap().
void ED_marker_keymap_animedit_conflictfree (struct wmKeyMap * keymap)
Definition at line 1524 of file anim_markers.c.
References KM_CTRL, KM_PRESS, MKEY, and WM_keymap_add_item().
Referenced by action_keymap_keyframes(), graphedit_keymap_keyframes(), nla_keymap_main(), and sequencer_keymap().
struct TimeMarker* ED_markers_find_nearest_marker (ListBase * markers, float x) [read]
Definition at line 170 of file anim_markers.c.
References ABS, ListBase::first, TimeMarker::frame, TimeMarker::next, and NULL.
Referenced by ED_markers_find_nearest_marker_time().
int ED_markers_find_nearest_marker_time (ListBase * markers, float x)
Definition at line 190 of file anim_markers.c.
References ED_markers_find_nearest_marker(), and TimeMarker::frame.
Referenced by doAnimEdit_SnapFrame(), ed_marker_select(), flushTransGraphData(), nlaedit_snap_exec(), recalcData_nla(), and snap_bezier_nearmarker().
struct TimeMarker* ED_markers_get_first_selected (ListBase * markers) [read]
Definition at line 309 of file anim_markers.c.
References ListBase::first, TimeMarker::flag, TimeMarker::next, NULL, and SELECT.
Referenced by act_markers_make_local_poll(), ed_marker_rename_exec(), ed_marker_rename_invoke_wrapper(), ed_marker_select_all_exec(), ed_markers_poll_selected_markers(), mirror_action_keys(), and mirror_graph_keys().
void ED_markers_get_minmax (ListBase * markers, short sel, float * first, float * last)
Definition at line 197 of file anim_markers.c.
References BLI_countlist(), ListBase::first, TimeMarker::flag, TimeMarker::frame, if(), ListBase::last, max, min, TimeMarker::next, NULL, and SELECT.
Referenced by markers_selectkeys_between().
void ED_markers_make_cfra_list (ListBase * markers, ListBase * lb, short sel)
Definition at line 295 of file anim_markers.c.
References add_marker_to_cfra_elem(), ListBase::first, TimeMarker::next, and NULL.
Referenced by columnselect_action_keys(), and columnselect_graph_keys().
int ED_markers_post_apply_transform (ListBase * markers, struct Scene * scene, int mode, float value, char side)
Definition at line 124 of file anim_markers.c.
References CFRA, ListBase::first, TimeMarker::flag, floorf, TimeMarker::frame, TimeMarker::next, NULL, SELECT, TFM_TIME_EXTEND, TFM_TIME_SCALE, and TFM_TIME_TRANSLATE.
Referenced by special_aftertrans_update().
void ED_operatortypes_marker (void)
Definition at line 1470 of file anim_markers.c.
References MARKER_OT_add(), MARKER_OT_delete(), MARKER_OT_duplicate(), MARKER_OT_make_links_scene(), MARKER_OT_move(), MARKER_OT_rename(), MARKER_OT_select(), MARKER_OT_select_all(), MARKER_OT_select_border(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().