Blender: ED_screen.h File Reference
ED_screen.h File Reference
Editors
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "DNA_view2d_types.h"
#include "DNA_view3d_types.h"
Defines
#define ED_KEYMAP_UI 1
#define ED_KEYMAP_VIEW2D 2
#define ED_KEYMAP_MARKERS 4
#define ED_KEYMAP_ANIMATION 8
#define ED_KEYMAP_FRAMES 16
#define ED_KEYMAP_GPENCIL 32
#define ED_KEYMAP_HEADER 64
Functions
void ED_region_do_listen (struct ARegion *ar, struct wmNotifier *note)
void ED_region_do_draw (struct bContext *C, struct ARegion *ar)
void ED_region_exit (struct bContext *C, struct ARegion *ar)
void ED_region_pixelspace (struct ARegion *ar)
void ED_region_set (const struct bContext *C, struct ARegion *ar)
void ED_region_init (struct bContext *C, struct ARegion *ar)
void ED_region_tag_redraw (struct ARegion *ar)
void ED_region_tag_redraw_partial (struct ARegion *ar, struct rcti *rct)
void ED_region_tag_redraw_overlay (struct ARegion *ar)
void ED_region_panels_init (struct wmWindowManager *wm, struct ARegion *ar)
void ED_region_panels (const struct bContext *C, struct ARegion *ar, int vertical, const char *context, int contextnr)
void ED_region_header_init (struct ARegion *ar)
void ED_region_header (const struct bContext *C, struct ARegion *ar)
void ED_region_toggle_hidden (struct bContext *C, struct ARegion *ar)
void region_scissor_winrct (struct ARegion *ar, struct rcti *winrct)
void ED_region_info_draw (struct ARegion *ar, const char *text, int block, float alpha)
void ED_spacetypes_init (void)
void ED_spacetypes_keymap (struct wmKeyConfig *keyconf)
int ED_area_header_switchbutton (const struct bContext *C, struct uiBlock *block, int yco)
int ED_area_header_standardbuttons (const struct bContext *C, struct uiBlock *block, int yco)
void ED_area_overdraw (struct bContext *C)
void ED_area_overdraw_flush (struct ScrArea *sa, struct ARegion *ar)
void ED_area_initialize (struct wmWindowManager *wm, struct wmWindow *win, struct ScrArea *sa)
void ED_area_exit (struct bContext *C, struct ScrArea *sa)
int ED_screen_area_active (const struct bContext *C)
void ED_area_do_listen (ScrArea *sa, struct wmNotifier *note)
void ED_area_tag_redraw (ScrArea *sa)
void ED_area_tag_redraw_regiontype (ScrArea *sa, int type)
void ED_area_tag_refresh (ScrArea *sa)
void ED_area_do_refresh (struct bContext *C, ScrArea *sa)
void ED_area_headerprint (ScrArea *sa, const char *str)
void ED_area_newspace (struct bContext *C, ScrArea *sa, int type)
void ED_area_prevspace (struct bContext *C, ScrArea *sa)
void ED_area_swapspace (struct bContext *C, ScrArea *sa1, ScrArea *sa2)
int ED_area_headersize (void)
void ED_screens_initialize (struct wmWindowManager *wm)
void ED_screen_draw (struct wmWindow *win)
void ED_screen_refresh (struct wmWindowManager *wm, struct wmWindow *win)
void ED_screen_do_listen (struct bContext *C, struct wmNotifier *note)
bScreen * ED_screen_duplicate (struct wmWindow *win, struct bScreen *sc)
bScreen * ED_screen_add (struct wmWindow *win, struct Scene *scene, const char *name)
void ED_screen_set (struct bContext *C, struct bScreen *sc)
void ED_screen_delete (struct bContext *C, struct bScreen *sc)
void ED_screen_set_scene (struct bContext *C, struct bScreen *screen, struct Scene *scene)
void ED_screen_delete_scene (struct bContext *C, struct Scene *scene)
void ED_screen_set_subwinactive (struct bContext *C, struct wmEvent *event)
void ED_screen_exit (struct bContext *C, struct wmWindow *window, struct bScreen *screen)
void ED_screen_animation_timer (struct bContext *C, int redraws, int refresh, int sync, int enable)
void ED_screen_animation_timer_update (struct bScreen *screen, int redraws, int refresh)
ScrArea * ED_screen_full_newspace (struct bContext *C, ScrArea *sa, int type)
void ED_screen_full_prevspace (struct bContext *C, ScrArea *sa)
void ED_screen_full_restore (struct bContext *C, ScrArea *sa)
struct ScrArea * ED_screen_full_toggle (struct bContext *C, struct wmWindow *win, struct ScrArea *sa)
void ED_update_for_newframe (struct Main *bmain, struct Scene *scene, struct bScreen *screen, int mute)
void ED_refresh_viewport_fps (struct bContext *C)
int ED_screen_animation_play (struct bContext *C, int sync, int mode)
void ED_operatortypes_screen (void)
void ED_keymap_screen (struct wmKeyConfig *keyconf)
int ED_operator_screenactive (struct bContext *C)
int ED_operator_screen_mainwinactive (struct bContext *C)
int ED_operator_areaactive (struct bContext *C)
int ED_operator_regionactive (struct bContext *C)
int ED_operator_scene_editable (struct bContext *C)
int ED_operator_objectmode (struct bContext *C)
int ED_operator_view3d_active (struct bContext *C)
int ED_operator_region_view3d_active (struct bContext *C)
int ED_operator_animview_active (struct bContext *C)
int ED_operator_timeline_active (struct bContext *C)
int ED_operator_outliner_active (struct bContext *C)
int ED_operator_outliner_active_no_editobject (struct bContext *C)
int ED_operator_file_active (struct bContext *C)
int ED_operator_action_active (struct bContext *C)
int ED_operator_buttons_active (struct bContext *C)
int ED_operator_node_active (struct bContext *C)
int ED_operator_graphedit_active (struct bContext *C)
int ED_operator_sequencer_active (struct bContext *C)
int ED_operator_image_active (struct bContext *C)
int ED_operator_nla_active (struct bContext *C)
int ED_operator_logic_active (struct bContext *C)
int ED_operator_info_active (struct bContext *C)
int ED_operator_console_active (struct bContext *C)
int ED_operator_object_active (struct bContext *C)
int ED_operator_object_active_editable (struct bContext *C)
int ED_operator_object_active_editable_mesh (struct bContext *C)
int ED_operator_object_active_editable_font (struct bContext *C)
int ED_operator_editmesh (struct bContext *C)
int ED_operator_editmesh_view3d (struct bContext *C)
int ED_operator_editmesh_region_view3d (struct bContext *C)
int ED_operator_editarmature (struct bContext *C)
int ED_operator_editcurve (struct bContext *C)
int ED_operator_editcurve_3d (struct bContext *C)
int ED_operator_editsurf (struct bContext *C)
int ED_operator_editsurfcurve (struct bContext *C)
int ED_operator_editsurfcurve_region_view3d (struct bContext *C)
int ED_operator_editfont (struct bContext *C)
int ED_operator_editlattice (struct bContext *C)
int ED_operator_editmball (struct bContext *C)
int ED_operator_uvedit (struct bContext *C)
int ED_operator_uvmap (struct bContext *C)
int ED_operator_posemode (struct bContext *C)
Detailed Description
Definition in file ED_screen.h.
Define Documentation
#define ED_KEYMAP_ANIMATION 8
Definition at line 177 of file ED_screen.h.
Referenced by ed_default_handlers(), ED_spacetype_action(), ED_spacetype_ipo(), ED_spacetype_nla(), ED_spacetype_sequencer(), and ED_spacetype_time().
#define ED_KEYMAP_FRAMES 16
Definition at line 178 of file ED_screen.h.
Referenced by ed_default_handlers(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_time(), and ED_spacetype_view3d().
#define ED_KEYMAP_GPENCIL 32
Definition at line 179 of file ED_screen.h.
Referenced by ed_default_handlers(), ED_spacetype_clip(), ED_spacetype_image(), ED_spacetype_node(), and ED_spacetype_view3d().
#define ED_KEYMAP_HEADER 64
Definition at line 180 of file ED_screen.h.
Referenced by ed_default_handlers(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), and ED_spacetype_view3d().
#define ED_KEYMAP_MARKERS 4
Definition at line 176 of file ED_screen.h.
Referenced by ed_default_handlers(), ED_spacetype_action(), ED_spacetype_ipo(), ED_spacetype_nla(), ED_spacetype_sequencer(), and ED_spacetype_time().
#define ED_KEYMAP_UI 1
Definition at line 174 of file ED_screen.h.
Referenced by ed_default_handlers(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), and ED_spacetype_view3d().
#define ED_KEYMAP_VIEW2D 2
Definition at line 175 of file ED_screen.h.
Referenced by ed_default_handlers(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), and ED_spacetype_view3d().
Function Documentation
void ED_area_do_listen (ScrArea * sa, struct wmNotifier * note)
Definition at line 133 of file area.c.
References SpaceType::listener, and ScrArea::type.
Referenced by wm_event_do_notifiers().
void ED_area_do_refresh (struct bContext * C, ScrArea * sa)
Definition at line 142 of file area.c.
References ScrArea::do_refresh, SpaceType::refresh, and ScrArea::type.
Referenced by wm_event_do_notifiers().
void ED_area_exit (struct bContext * C, struct ScrArea * sa)
Definition at line 1146 of file screen_edit.c.
References CTX_wm_area(), CTX_wm_area_set(), ED_fileselect_exit(), ED_region_exit(), ED_render_engine_area_exit(), ListBase::first, ScrArea::handlers, ARegion::next, ScrArea::regionbase, SPACE_FILE, SPACE_VIEW3D, ScrArea::spacedata, SpaceLink::spacetype, ScrArea::spacetype, and WM_event_remove_handlers().
Referenced by ED_area_newspace(), ED_area_swapspace(), ED_screen_exit(), and screen_delarea().
int ED_area_header_standardbuttons (const struct bContext * C, struct uiBlock * block, int yco)
Referenced by uiTemplateHeader().
int ED_area_header_switchbutton (const struct bContext * C, struct uiBlock * block, int yco)
Referenced by buttons_header_buttons(), ED_area_header_standardbuttons(), and uiTemplateHeader().
void ED_area_headerprint (ScrArea * sa, const char * str)
Definition at line 568 of file area.c.
References BLI_strncpy(), ED_region_tag_redraw(), ListBase::first, ARegion::headerstr, MEM_freeN(), MEM_mallocN(), ARegion::next, NULL, ScrArea::regionbase, ARegion::regiontype, and RGN_TYPE_HEADER.
Referenced by Align(), BakeTime(), Bevel(), BevelWeight(), BoneEnvelope(), BoneRoll(), BoneSize(), Crease(), CurveShrinkFatten(), ed_marker_move_exit(), ed_marker_move_modal(), ED_screen_full_toggle(), edbm_vertex_slide_modal(), EdgeSlide(), gpencil_draw_status_indicators(), knife_update_header(), knifetool_modal(), loopcut_modal(), minimize_stretch_exit(), minimize_stretch_iteration(), Mirror(), pose_slide_draw_status(), pose_slide_modal(), poselib_preview_apply(), poselib_preview_cleanup(), PushPull(), Resize(), ringcut_invoke(), Rotation(), SeqSlide(), Shear(), ShrinkFatten(), stitch_exit(), stitch_update_header(), Tilt(), TimeScale(), TimeSlide(), TimeTranslate(), ToSphere(), Trackball(), Translation(), viewRedrawPost(), vtx_slide_exit(), vtx_slide_init(), and Warp().
int ED_area_headersize (void)
Definition at line 1777 of file area.c.
References UI_UNIT_Y.
Referenced by area_move_apply_do(), area_move_set_limits(), area_split_init(), ED_region_header(), screen_refresh_headersizes(), and screen_test_scale().
void ED_area_initialize (struct wmWindowManager * wm, struct wmWindow * win, struct ScrArea * sa)
Definition at line 1202 of file area.c.
References area_azone_initialize(), area_calc_totrct(), BKE_regiontype_from_id(), BKE_spacetype_from_id(), ScrArea::butspacetype, ed_default_handlers(), ListBase::first, View2D::flag, ARegion::handlers, ScrArea::handlers, ARegionType::init, SpaceType::init, SpaceType::keymapflag, ARegionType::keymapflag, ARegion::next, NULL, region_rect_recursive(), region_subwindow(), ScrArea::regionbase, ARegion::regiontype, RGN_TYPE_HEADER, wmWindow::sizex, wmWindow::sizey, SPACE_VIEW3D, ScrArea::spacetype, ARegion::swinid, ScrArea::totrct, ScrArea::type, ARegion::type, ARegion::uiblocks, uiFreeBlocks(), ARegion::v2d, and V2D_IS_INITIALISED.
Referenced by clip_refresh(), ED_area_newspace(), ED_area_swapspace(), ED_region_toggle_hidden(), ED_screen_refresh(), and sequencer_refresh().
void ED_area_newspace (struct bContext * C, ScrArea * sa, int type)
Definition at line 1360 of file area.c.
References BKE_spacetype_from_id(), BLI_addhead(), BLI_freelinkN(), BLI_remlink(), ScrArea::butspacetype, CTX_wm_manager(), CTX_wm_window(), ED_area_exit(), ED_area_initialize(), ED_area_tag_redraw(), ED_area_tag_refresh(), ListBase::first, SpaceType::free, ListBase::last, NC_SPACE, ND_SPACE_CHANGED, SpaceType::new, SpaceLink::next, NULL, ScrArea::regionbase, SpaceLink::regionbase, ScrArea::spacedata, SpaceLink::spacetype, ScrArea::spacetype, ScrArea::type, WM_event_add_mousemove(), and WM_event_add_notifier().
Referenced by ED_area_prevspace(), ED_screen_full_newspace(), ED_screen_full_toggle(), render_view_open(), render_view_show_invoke(), spacefunc(), wm_handler_fileselect_call(), and WM_window_open_temp().
void ED_area_overdraw (struct bContext * C)
Definition at line 351 of file area.c.
References ScrArea::actionzones, AZone::ar, area_draw_azone(), bScreen::areabase, AZONE_AREA, AZONE_REGION, CTX_wm_screen(), CTX_wm_window(), AZone::do_draw, ListBase::first, ARegion::flag, G, bScreen::mainwin, ScrArea::next, AZone::next, region_draw_azone_icon(), region_draw_azone_tab(), region_draw_azone_tab_plus(), region_draw_azone_tria(), RGN_FLAG_HIDDEN, RGN_FLAG_TOO_SMALL, AZone::type, wmSubWindowSet(), AZone::x1, AZone::x2, AZone::y1, and AZone::y2.
Referenced by wm_method_draw_full(), wm_method_draw_overlap_all(), and wm_method_draw_triple().
void ED_area_overdraw_flush (struct ScrArea * sa, struct ARegion * ar)
Definition at line 153 of file area.c.
References ScrArea::actionzones, BLI_in_rcti(), AZone::do_draw, ListBase::first, AZone::next, ARegion::winrct, AZone::x1, AZone::x2, AZone::y1, and AZone::y2.
Referenced by wm_method_draw_full(), wm_method_draw_overlap_all(), and wm_method_draw_triple().
void ED_area_prevspace (struct bContext * C, ScrArea * sa)
Definition at line 1431 of file area.c.
References CTX_wm_space_data(), ED_area_newspace(), ED_area_tag_redraw(), ListBase::first, NC_SPACE, ND_SPACE_CHANGED, SpaceLink::next, SPACE_FILE, SPACE_INFO, ScrArea::spacedata, SpaceLink::spacetype, and WM_event_add_notifier().
Referenced by ED_screen_full_prevspace(), render_view_cancel_exec(), and wm_handler_fileselect_call().
void ED_area_swapspace (struct bContext * C, ScrArea * sa1, ScrArea * sa2)
Definition at line 1335 of file area.c.
References area_copy_data(), BKE_screen_area_free(), CTX_wm_manager(), CTX_wm_window(), ED_area_exit(), ED_area_initialize(), ED_area_tag_redraw(), ED_area_tag_refresh(), MEM_callocN(), MEM_freeN(), and WM_event_add_mousemove().
Referenced by area_swap_modal().
void ED_area_tag_redraw (ScrArea * sa)
Definition at line 537 of file area.c.
References ED_region_tag_redraw(), ListBase::first, ARegion::next, and ScrArea::regionbase.
Referenced by action_listener(), action_refresh(), actkeys_viewall(), area_dupli_invoke(), area_join_modal(), area_move_apply_do(), area_split_apply(), area_split_exit(), area_split_modal(), area_swap_modal(), BIF_sk_selectStroke(), bookmark_add_exec(), bookmark_delete_exec(), borderselect_exec(), buttons_area_listener(), buttons_area_redraw(), clip_listener(), clip_rebuild_proxy_exec(), clip_refresh(), console_clear_exec(), console_delete_exec(), console_history_append_exec(), console_history_cycle_exec(), console_insert_exec(), console_modal_select_apply(), console_move_exec(), console_paste_exec(), console_scrollback_append_exec(), do_buttons_buttons(), do_view3d_header_buttons(), do_view3d_region_buttons(), ED_area_newspace(), ED_area_prevspace(), ED_area_swapspace(), ED_region_toggle_hidden(), ED_view3d_quadview_update(), file_draw_check_cb(), file_filenum_exec(), file_highlight_invoke(), file_listener(), file_rename_exec(), file_select_all_exec(), game_engine_exec(), graph_listener(), graphkeys_clear_ghostcurves_exec(), graphkeys_create_ghostcurves_exec(), graphkeys_viewall(), header_flip_exec(), image_listener(), image_record_composite_apply(), image_sample_apply(), image_sample_exit(), image_sample_line_exec(), localview_exec(), nla_listener(), nlaedit_viewall(), node_area_listener(), pin_cb(), previewrange_clear_exec(), redraw_timer_window_swap(), region_flip_exec(), region_quadview_exec(), region_scale_modal(), render_view_show_invoke(), report_delete_exec(), report_replay_exec(), report_select_all_toggle_exec(), sample_apply(), sample_exit(), select_report_pick_exec(), seq_proxy_build_job(), sequencer_refresh(), sequencer_view_all_exec(), sequencer_view_all_preview_exec(), sequencer_view_selected_exec(), set_clone_cursor_exec(), sketch_cancel(), sketch_convert(), sketch_draw_modal(), sketch_draw_preview(), sketch_finish(), sketch_select(), spacefunc(), template_texture_show(), text_listener(), text_scroll_apply(), text_scroll_exec(), text_scroll_modal(), time_listener(), view3d_layers_exec(), viewRedrawForce(), and wm_gesture_end().
void ED_area_tag_redraw_regiontype (ScrArea * sa, int type)
Definition at line 546 of file area.c.
References ED_region_tag_redraw(), ListBase::first, ARegion::next, ScrArea::regionbase, and ARegion::regiontype.
Referenced by space_view3d_listener().
void ED_area_tag_refresh (ScrArea * sa)
Definition at line 559 of file area.c.
References ScrArea::do_refresh.
Referenced by action_listener(), ED_area_newspace(), ED_area_swapspace(), file_listener(), graph_init(), graph_listener(), image_listener(), nla_init(), nla_listener(), node_area_listener(), screen_animation_step(), sequencer_view_toggle_exec(), and time_listener().
void ED_keymap_screen (struct wmKeyConfig * keyconf)
Definition at line 3497 of file screen_ops.c.
References AKEY, COMMAKEY, DOWNARROWKEY, ESCKEY, EVT_ACTIONZONE_AREA, EVT_ACTIONZONE_REGION, F11KEY, F12KEY, F3KEY, F5KEY, F6KEY, F8KEY, FALSE, keymap_modal_set(), KM_ALT, KM_ANY, KM_CTRL, KM_OSKEY, KM_PRESS, KM_SHIFT, LEFTARROWKEY, LEFTMOUSE, MEDIAFIRST, MEDIALAST, MEDIAPLAY, MEDIASTOP, open_file_drop_copy(), open_file_drop_poll(), PADENTER, wmKeyMapItem::ptr, QKEY, RETKEY, RIGHTARROWKEY, RIGHTMOUSE, RKEY, RNA_boolean_set(), RNA_int_set(), SPACEKEY, TIMER0, TRUE, UKEY, UPARROWKEY, WHEELDOWNMOUSE, WHEELUPMOUSE, WM_dropbox_add(), WM_dropboxmap_find(), WM_keymap_add_item(), WM_keymap_find(), WM_keymap_verify_item(), and ZKEY.
Referenced by ED_spacetypes_keymap().
int ED_operator_action_active (struct bContext * C)
Definition at line 233 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_ACTION.
Referenced by ACTION_OT_clean(), ACTION_OT_clickselect(), ACTION_OT_copy(), ACTION_OT_delete(), ACTION_OT_duplicate(), ACTION_OT_extrapolation_type(), ACTION_OT_frame_jump(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_mirror(), ACTION_OT_paste(), ACTION_OT_previewrange_set(), ACTION_OT_sample(), ACTION_OT_select_all_toggle(), ACTION_OT_select_border(), ACTION_OT_select_column(), ACTION_OT_select_leftright(), ACTION_OT_select_less(), ACTION_OT_select_linked(), ACTION_OT_select_more(), ACTION_OT_snap(), ACTION_OT_view_all(), and ACTION_OT_view_selected().
int ED_operator_animview_active (struct bContext * C)
Definition at line 193 of file screen_ops.c.
References CTX_wm_operator_poll_msg_set(), CTX_wm_space_data(), ED_operator_areaactive(), ELEM5, SPACE_ACTION, SPACE_IPO, SPACE_NLA, SPACE_SEQ, SPACE_TIME, SpaceLink::spacetype, and TRUE.
Referenced by ANIM_OT_previewrange_clear(), ANIM_OT_previewrange_set(), ed_markers_poll_markers_exist(), ed_markers_poll_selected_markers(), and MARKER_OT_add().
int ED_operator_areaactive (struct bContext * C)
Definition at line 98 of file screen_ops.c.
References CTX_wm_area(), CTX_wm_screen(), CTX_wm_window(), and NULL.
Referenced by ANIM_OT_keyframe_delete_v3d(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_active_set(), delete_orientation_poll(), ED_operator_animview_active(), ed_spacetype_test(), SCREEN_OT_area_dupli(), SCREEN_OT_area_swap(), SCREEN_OT_header_flip(), SCREEN_OT_region_flip(), SCREEN_OT_region_scale(), SCREEN_OT_screen_full_area(), SCRIPT_OT_python_file_run(), TRANSFORM_OT_create_orientation(), and TRANSFORM_OT_snap_type().
int ED_operator_buttons_active (struct bContext * C)
Definition at line 238 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_BUTS.
Referenced by BUTTONS_OT_toolbox().
int ED_operator_console_active (struct bContext * C)
Definition at line 285 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_CONSOLE.
Referenced by CONSOLE_OT_clear(), CONSOLE_OT_copy(), CONSOLE_OT_delete(), CONSOLE_OT_history_append(), CONSOLE_OT_history_cycle(), CONSOLE_OT_insert(), CONSOLE_OT_move(), CONSOLE_OT_paste(), CONSOLE_OT_scrollback_append(), and CONSOLE_OT_select_set().
int ED_operator_editarmature (struct bContext * C)
Definition at line 336 of file screen_ops.c.
References CTX_data_edit_object(), Object::data, NULL, OB_ARMATURE, and Object::type.
Referenced by ARMATURE_OT_align(), ARMATURE_OT_armature_layers(), ARMATURE_OT_autoside_names(), ARMATURE_OT_bone_layers(), ARMATURE_OT_bone_primitive_add(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_click_extrude(), ARMATURE_OT_delete(), ARMATURE_OT_duplicate(), ARMATURE_OT_extrude(), ARMATURE_OT_fill(), ARMATURE_OT_flip_names(), ARMATURE_OT_hide(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), ARMATURE_OT_parent_set(), ARMATURE_OT_reveal(), ARMATURE_OT_select_all(), ARMATURE_OT_select_hierarchy(), ARMATURE_OT_select_inverse(), ARMATURE_OT_separate(), ARMATURE_OT_subdivide(), ARMATURE_OT_switch_direction(), armature_select_linked_poll(), ED_keymap_armature(), and pose_armature_layers_showall_poll().
int ED_operator_editcurve (struct bContext * C)
Definition at line 401 of file screen_ops.c.
References CTX_data_edit_object(), Object::data, NULL, OB_CURVE, and Object::type.
Referenced by CURVE_OT_de_select_first(), CURVE_OT_de_select_last(), CURVE_OT_handle_type_set(), CURVE_OT_select_next(), CURVE_OT_select_previous(), CURVE_OT_spline_type_set(), CURVE_OT_tilt_clear(), and CURVE_OT_vertex_add().
int ED_operator_editcurve_3d (struct bContext * C)
Definition at line 409 of file screen_ops.c.
References CTX_data_edit_object(), CU_3D, Object::data, Curve::editnurb, Curve::flag, NULL, OB_CURVE, and Object::type.
Referenced by TRANSFORM_OT_tilt().
int ED_operator_editfont (struct bContext * C)
Definition at line 428 of file screen_ops.c.
References CTX_data_edit_object(), Object::data, NULL, OB_FONT, and Object::type.
Referenced by ED_keymap_curve(), FONT_OT_case_set(), FONT_OT_case_toggle(), FONT_OT_change_character(), FONT_OT_change_spacing(), FONT_OT_delete(), FONT_OT_file_paste(), FONT_OT_insert_lorem(), FONT_OT_line_break(), FONT_OT_move(), FONT_OT_move_select(), FONT_OT_style_set(), FONT_OT_style_toggle(), FONT_OT_text_copy(), FONT_OT_text_cut(), FONT_OT_text_insert(), and FONT_OT_text_paste().
int ED_operator_editlattice (struct bContext * C)
Definition at line 436 of file screen_ops.c.
References CTX_data_edit_object(), Object::data, NULL, OB_LATTICE, and Object::type.
Referenced by ED_keymap_object(), hook_op_edit_poll(), LATTICE_OT_select_all(), make_regular_poll(), and vertex_parent_set_poll().
int ED_operator_editmball (struct bContext * C)
Definition at line 444 of file screen_ops.c.
References CTX_data_edit_object(), Object::data, NULL, OB_MBALL, and Object::type.
Referenced by ED_keymap_metaball(), MBALL_OT_delete_metaelems(), MBALL_OT_duplicate_metaelems(), MBALL_OT_hide_metaelems(), MBALL_OT_reveal_metaelems(), MBALL_OT_select_all(), and MBALL_OT_select_random_metaelems().
int ED_operator_editmesh (struct bContext * C)
Definition at line 314 of file screen_ops.c.
References BMEdit_FromObject(), CTX_data_edit_object(), NULL, OB_MESH, and Object::type.
Referenced by ED_keymap_mesh(), ED_operator_editmesh_region_view3d(), ED_operator_editmesh_view3d(), EM_view3d_poll(), hook_op_edit_poll(), MESH_OT_beautify_fill(), MESH_OT_bevel(), MESH_OT_blend_from_shape(), MESH_OT_bridge_edge_loops(), MESH_OT_colors_reverse(), MESH_OT_colors_rotate(), MESH_OT_delete(), MESH_OT_dissolve(), MESH_OT_dissolve_limited(), MESH_OT_dupli_extrude_cursor(), MESH_OT_duplicate(), MESH_OT_edge_collapse(), MESH_OT_edge_collapse_loop(), MESH_OT_edge_face_add(), MESH_OT_edge_rotate(), MESH_OT_edge_split(), MESH_OT_edges_select_sharp(), MESH_OT_extrude_edges_indiv(), MESH_OT_extrude_faces_indiv(), MESH_OT_extrude_region(), MESH_OT_extrude_verts_indiv(), MESH_OT_faces_select_linked_flat(), MESH_OT_faces_shade_flat(), MESH_OT_faces_shade_smooth(), MESH_OT_fill(), MESH_OT_flip_normals(), MESH_OT_hide(), MESH_OT_inset(), MESH_OT_loop_multi_select(), MESH_OT_loop_to_region(), MESH_OT_mark_seam(), MESH_OT_mark_sharp(), MESH_OT_merge(), MESH_OT_navmesh_face_add(), MESH_OT_navmesh_face_copy(), MESH_OT_noise(), MESH_OT_normals_make_consistent(), MESH_OT_quads_convert_to_tris(), MESH_OT_region_to_loop(), MESH_OT_remove_doubles(), MESH_OT_reveal(), MESH_OT_select_all(), MESH_OT_select_axis(), MESH_OT_select_by_number_vertices(), MESH_OT_select_interior_faces(), MESH_OT_select_less(), MESH_OT_select_linked(), MESH_OT_select_linked_pick(), MESH_OT_select_loose_verts(), MESH_OT_select_mirror(), MESH_OT_select_more(), MESH_OT_select_next_loop(), MESH_OT_select_non_manifold(), MESH_OT_select_nth(), MESH_OT_select_random(), MESH_OT_select_similar(), MESH_OT_select_vertex_path(), MESH_OT_separate(), MESH_OT_shape_propagate_to_all(), MESH_OT_solidify(), MESH_OT_sort_faces(), MESH_OT_split(), MESH_OT_subdivide(), MESH_OT_tris_convert_to_quads(), MESH_OT_uvs_reverse(), MESH_OT_uvs_rotate(), MESH_OT_vert_connect(), MESH_OT_vertices_randomize(), MESH_OT_vertices_smooth(), shade_poll(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_shrink_fatten(), and vertex_parent_set_poll().
int ED_operator_editmesh_region_view3d (struct bContext * C)
Definition at line 327 of file screen_ops.c.
References CTX_wm_operator_poll_msg_set(), CTX_wm_region_view3d(), and ED_operator_editmesh().
Referenced by edbm_shortest_path_select_poll(), MESH_OT_edgering_select(), MESH_OT_loop_select(), MESH_OT_loopcut(), and MESH_OT_vert_slide().
int ED_operator_editmesh_view3d (struct bContext * C)
Definition at line 322 of file screen_ops.c.
References ED_operator_editmesh(), and ED_operator_view3d_active().
Referenced by MESH_OT_extrude_repeat(), and MESH_OT_knife_tool().
int ED_operator_editsurf (struct bContext * C)
Definition at line 420 of file screen_ops.c.
References CTX_data_edit_object(), Object::data, NULL, OB_SURF, and Object::type.
Referenced by CURVE_OT_select_row(), and CURVE_OT_spin().
int ED_operator_editsurfcurve (struct bContext * C)
Definition at line 384 of file screen_ops.c.
References CTX_data_edit_object(), Object::data, ELEM, NULL, OB_CURVE, OB_SURF, and Object::type.
Referenced by CURVE_OT_cyclic_toggle(), CURVE_OT_delete(), CURVE_OT_duplicate(), CURVE_OT_extrude(), CURVE_OT_hide(), CURVE_OT_make_segment(), CURVE_OT_radius_set(), CURVE_OT_reveal(), CURVE_OT_select_all(), CURVE_OT_select_less(), CURVE_OT_select_linked(), CURVE_OT_select_more(), CURVE_OT_select_nth(), CURVE_OT_select_random(), CURVE_OT_separate(), CURVE_OT_shade_flat(), CURVE_OT_shade_smooth(), CURVE_OT_smooth(), CURVE_OT_smooth_radius(), CURVE_OT_spline_weight_set(), CURVE_OT_subdivide(), CURVE_OT_switch_direction(), ED_keymap_curve(), ED_operator_editsurfcurve_region_view3d(), hook_op_edit_poll(), and vertex_parent_set_poll().
int ED_operator_editsurfcurve_region_view3d (struct bContext * C)
Definition at line 392 of file screen_ops.c.
References CTX_wm_operator_poll_msg_set(), CTX_wm_region_view3d(), and ED_operator_editsurfcurve().
Referenced by CURVE_OT_select_linked_pick().
int ED_operator_file_active (struct bContext * C)
Definition at line 228 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_FILE.
Referenced by file_delete_poll(), file_directory_poll(), file_operator_poll(), FILE_OT_bookmark_add(), FILE_OT_bookmark_toggle(), FILE_OT_delete_bookmark(), FILE_OT_directory_new(), FILE_OT_filenum(), FILE_OT_hidedot(), FILE_OT_highlight(), FILE_OT_next(), FILE_OT_parent(), FILE_OT_previous(), FILE_OT_refresh(), FILE_OT_select(), FILE_OT_select_all_toggle(), FILE_OT_select_bookmark(), FILE_OT_select_border(), FILE_OT_smoothscroll(), and file_rename_poll().
int ED_operator_graphedit_active (struct bContext * C)
Definition at line 254 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_IPO.
Referenced by ANIM_OT_channels_visibility_set(), ANIM_OT_channels_visibility_toggle(), GRAPH_OT_cursor_set(), GRAPH_OT_ghost_curves_clear(), GRAPH_OT_previewrange_set(), GRAPH_OT_properties(), GRAPH_OT_view_all(), and GRAPH_OT_view_selected().
int ED_operator_image_active (struct bContext * C)
Definition at line 264 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_IMAGE.
Referenced by IMAGE_OT_properties(), IMAGE_OT_scopes(), RENDER_OT_view_cancel(), UV_OT_align(), UV_OT_circle_select(), UV_OT_cursor_set(), UV_OT_select(), UV_OT_select_border(), UV_OT_select_linked(), UV_OT_select_linked_pick(), UV_OT_select_loop(), UV_OT_snap_cursor(), UV_OT_snap_selected(), and UV_OT_tile_set().
int ED_operator_info_active (struct bContext * C)
Definition at line 279 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_INFO.
Referenced by INFO_OT_report_copy(), INFO_OT_report_delete(), INFO_OT_report_replay(), INFO_OT_select_all_toggle(), INFO_OT_select_border(), and INFO_OT_select_pick().
int ED_operator_logic_active (struct bContext * C)
Definition at line 274 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_LOGIC.
Referenced by LOGIC_OT_links_cut(), and LOGIC_OT_properties().
int ED_operator_nla_active (struct bContext * C)
Definition at line 269 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_NLA.
Referenced by NLA_OT_action_sync_length(), NLA_OT_channels_click(), NLA_OT_click_select(), NLA_OT_properties(), NLA_OT_select_leftright(), NLA_OT_view_all(), NLA_OT_view_selected(), nlaop_poll_tweakmode_off(), and nlaop_poll_tweakmode_on().
int ED_operator_node_active (struct bContext * C)
Definition at line 243 of file screen_ops.c.
References CTX_wm_space_node(), and SpaceNode::edittree.
Referenced by composite_node_active(), NODE_OT_add_file(), NODE_OT_backimage_sample(), NODE_OT_delete(), NODE_OT_delete_reconnect(), NODE_OT_duplicate(), NODE_OT_group_edit(), NODE_OT_group_make(), NODE_OT_group_socket_add(), NODE_OT_group_socket_move_down(), NODE_OT_group_socket_move_up(), NODE_OT_group_socket_remove(), NODE_OT_group_ungroup(), NODE_OT_hide_socket_toggle(), NODE_OT_hide_toggle(), NODE_OT_link(), NODE_OT_link_make(), NODE_OT_links_cut(), NODE_OT_links_detach(), NODE_OT_mute_toggle(), NODE_OT_new_node_tree(), NODE_OT_options_toggle(), NODE_OT_preview_toggle(), NODE_OT_resize(), NODE_OT_select(), NODE_OT_select_all(), NODE_OT_select_border(), NODE_OT_select_linked_from(), NODE_OT_select_linked_to(), NODE_OT_select_same_type(), NODE_OT_select_same_type_next(), NODE_OT_select_same_type_prev(), NODE_OT_show_cyclic_dependencies(), and NODE_OT_view_all().
int ED_operator_object_active (struct bContext * C)
Definition at line 290 of file screen_ops.c.
References ED_object_active_context(), NULL, OB_RESTRICT_VIEW, and Object::restrictflag.
Referenced by OBJECT_OT_make_links_data(), OBJECT_OT_parent_set(), and OBJECT_OT_proxy_make().
int ED_operator_object_active_editable (struct bContext * C)
Definition at line 296 of file screen_ops.c.
References ED_object_active_context(), Object::id, ID::lib, NULL, OB_RESTRICT_VIEW, and Object::restrictflag.
Referenced by DPAINT_OT_bake(), DPAINT_OT_output_toggle(), DPAINT_OT_surface_slot_add(), DPAINT_OT_surface_slot_remove(), DPAINT_OT_type_toggle(), LOGIC_OT_actuator_add(), LOGIC_OT_controller_add(), LOGIC_OT_sensor_add(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_constraints_clear(), OBJECT_OT_constraints_copy(), OBJECT_OT_forcefield_toggle(), OBJECT_OT_game_physics_copy(), OBJECT_OT_game_property_clear(), OBJECT_OT_game_property_copy(), OBJECT_OT_game_property_new(), OBJECT_OT_game_property_remove(), OBJECT_OT_logic_bricks_copy(), OBJECT_OT_material_slot_add(), OBJECT_OT_material_slot_assign(), OBJECT_OT_material_slot_remove(), OBJECT_OT_mode_set(), OBJECT_OT_modifier_add(), OBJECT_OT_parent_clear(), OBJECT_OT_parent_no_inverse_set(), OBJECT_OT_particle_system_add(), OBJECT_OT_particle_system_remove(), OBJECT_OT_paths_calculate(), OBJECT_OT_paths_clear(), OBJECT_OT_posemode_toggle(), and shade_poll().
int ED_operator_object_active_editable_font (struct bContext * C)
Definition at line 308 of file screen_ops.c.
References ED_object_active_context(), Object::id, ID::lib, NULL, OB_FONT, OB_RESTRICT_VIEW, Object::restrictflag, and Object::type.
Referenced by FONT_OT_textbox_add(), and FONT_OT_textbox_remove().
int ED_operator_object_active_editable_mesh (struct bContext * C)
Definition at line 302 of file screen_ops.c.
References Object::data, ED_object_active_context(), Object::id, ID::lib, NULL, OB_MESH, OB_RESTRICT_VIEW, Object::restrictflag, and Object::type.
Referenced by SCULPT_OT_sculptmode_toggle().
int ED_operator_objectmode (struct bContext * C)
Definition at line 151 of file screen_ops.c.
References CTX_data_active_object(), CTX_data_edit_object(), CTX_data_scene(), Scene::id, ID::lib, Object::mode, and NULL.
Referenced by GROUP_OT_create(), GROUP_OT_objects_add_active(), GROUP_OT_objects_remove(), GROUP_OT_objects_remove_active(), OBJECT_OT_add(), OBJECT_OT_add_named(), OBJECT_OT_armature_add(), OBJECT_OT_camera_add(), OBJECT_OT_delete(), OBJECT_OT_drop_named_material(), OBJECT_OT_duplicate(), OBJECT_OT_duplicates_make_real(), OBJECT_OT_effector_add(), OBJECT_OT_group_instance_add(), OBJECT_OT_lamp_add(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_move_to_layer(), OBJECT_OT_speaker_add(), OBJECT_OT_text_add(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), and OBJECT_OT_transform_apply().
int ED_operator_outliner_active (struct bContext * C)
Definition at line 210 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_OUTLINER.
Referenced by OUTLINER_OT_action_set(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_expanded_toggle(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_item_activate(), OUTLINER_OT_item_openclose(), OUTLINER_OT_item_rename(), OUTLINER_OT_object_operation(), OUTLINER_OT_operation(), OUTLINER_OT_parent_clear(), OUTLINER_OT_parent_drop(), OUTLINER_OT_renderability_toggle(), OUTLINER_OT_scroll_page(), OUTLINER_OT_select_border(), OUTLINER_OT_selected_toggle(), OUTLINER_OT_show_active(), OUTLINER_OT_show_hierarchy(), and OUTLINER_OT_show_one_level().
int ED_operator_outliner_active_no_editobject (struct bContext * C)
Definition at line 215 of file screen_ops.c.
References CTX_data_edit_object(), ED_object_active_context(), ed_spacetype_test(), and SPACE_OUTLINER.
Referenced by OUTLINER_OT_selectability_toggle(), and OUTLINER_OT_visibility_toggle().
int ED_operator_posemode (struct bContext * C)
Definition at line 344 of file screen_ops.c.
References CTX_data_active_object(), Object::mode, OB_MODE_EDIT, OB_MODE_WEIGHT_PAINT, and object_pose_armature_get().
Referenced by ED_keymap_armature(), pose_armature_layers_showall_poll(), POSE_OT_armature_apply(), POSE_OT_armature_layers(), POSE_OT_autoside_names(), POSE_OT_bone_layers(), POSE_OT_breakdown(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_constraints_clear(), POSE_OT_constraints_copy(), POSE_OT_copy(), POSE_OT_flip_names(), POSE_OT_group_add(), POSE_OT_group_assign(), POSE_OT_group_deselect(), POSE_OT_group_move(), POSE_OT_group_remove(), POSE_OT_group_select(), POSE_OT_group_sort(), POSE_OT_group_unassign(), POSE_OT_hide(), POSE_OT_ik_add(), POSE_OT_ik_clear(), POSE_OT_loc_clear(), POSE_OT_paste(), POSE_OT_paths_calculate(), POSE_OT_paths_clear(), POSE_OT_propagate(), POSE_OT_push(), POSE_OT_quaternions_flip(), POSE_OT_relax(), POSE_OT_reveal(), POSE_OT_rot_clear(), POSE_OT_rotation_mode_set(), POSE_OT_scale_clear(), POSE_OT_select_all(), POSE_OT_select_constraint_target(), POSE_OT_select_flip_active(), POSE_OT_select_grouped(), POSE_OT_select_hierarchy(), POSE_OT_select_parent(), POSE_OT_transforms_clear(), POSE_OT_user_transforms_clear(), POSE_OT_visual_transform_apply(), pose_select_linked_poll(), POSELIB_OT_new(), and POSELIB_OT_pose_add().
int ED_operator_region_view3d_active (struct bContext * C)
Definition at line 183 of file screen_ops.c.
References CTX_wm_operator_poll_msg_set(), CTX_wm_region_view3d(), FALSE, and TRUE.
Referenced by PAINT_OT_image_from_view(), SCREEN_OT_region_quadview(), VIEW3D_OT_clip_border(), VIEW3D_OT_rotate(), VIEW3D_OT_snap_cursor_to_grid(), VIEW3D_OT_snap_selected_to_grid(), VIEW3D_OT_view_all(), VIEW3D_OT_view_pan(), VIEW3D_OT_view_selected(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), and view3d_selectable_data().
int ED_operator_regionactive (struct bContext * C)
Definition at line 90 of file screen_ops.c.
References CTX_wm_region(), CTX_wm_screen(), CTX_wm_window(), and NULL.
Referenced by gpencil_draw_poll().
int ED_operator_scene_editable (struct bContext * C)
Definition at line 143 of file screen_ops.c.
References CTX_data_scene(), Scene::id, ID::lib, and NULL.
Referenced by CURVE_OT_primitive_bezier_circle_add(), CURVE_OT_primitive_bezier_curve_add(), CURVE_OT_primitive_nurbs_circle_add(), CURVE_OT_primitive_nurbs_curve_add(), CURVE_OT_primitive_nurbs_path_add(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cube_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_monkey_add(), MESH_OT_primitive_plane_add(), MESH_OT_primitive_uv_sphere_add(), OBJECT_OT_location_clear(), OBJECT_OT_metaball_add(), OBJECT_OT_origin_clear(), OBJECT_OT_origin_set(), OBJECT_OT_rotation_clear(), OBJECT_OT_scale_clear(), OBJECT_OT_visual_transform_apply(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_scene_strip_add(), SEQUENCER_OT_sound_strip_add(), SURFACE_OT_primitive_nurbs_surface_circle_add(), SURFACE_OT_primitive_nurbs_surface_curve_add(), SURFACE_OT_primitive_nurbs_surface_cylinder_add(), SURFACE_OT_primitive_nurbs_surface_sphere_add(), SURFACE_OT_primitive_nurbs_surface_surface_add(), and SURFACE_OT_primitive_nurbs_surface_torus_add().
int ED_operator_screen_mainwinactive (struct bContext * C)
Definition at line 135 of file screen_ops.c.
References CTX_wm_screen(), CTX_wm_window(), and NULL.
Referenced by SCREEN_OT_area_move(), and SCREEN_OT_area_options().
int ED_operator_screenactive (struct bContext * C)
Definition at line 106 of file screen_ops.c.
References CTX_wm_screen(), CTX_wm_window(), and NULL.
Referenced by ED_OT_redo(), ED_OT_undo(), ED_OT_undo_history(), join_poll(), join_shapes_poll(), RENDER_OT_opengl(), RENDER_OT_view_show(), screen_active_editable(), SCREEN_OT_animation_cancel(), SCREEN_OT_back_to_previous(), SCREEN_OT_redo_last(), SCREEN_OT_repeat_history(), SCREEN_OT_repeat_last(), SCREEN_OT_screen_set(), SCREEN_OT_userpref_show(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_shear(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), and TRANSFORM_OT_warp().
int ED_operator_sequencer_active (struct bContext * C)
Definition at line 259 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_SEQ.
Referenced by sequencer_add_effect_strip_invoke(), sequencer_add_image_strip_invoke(), sequencer_add_movie_strip_invoke(), sequencer_add_movieclip_strip_invoke(), sequencer_add_scene_strip_invoke(), sequencer_add_sound_strip_invoke(), sequencer_cut_invoke(), SEQUENCER_OT_duplicate(), SEQUENCER_OT_paste(), SEQUENCER_OT_properties(), SEQUENCER_OT_rebuild_proxy(), SEQUENCER_OT_select(), SEQUENCER_OT_select_border(), SEQUENCER_OT_select_linked_pick(), SEQUENCER_OT_swap_data(), SEQUENCER_OT_view_all(), SEQUENCER_OT_view_all_preview(), SEQUENCER_OT_view_selected(), SEQUENCER_OT_view_toggle(), SEQUENCER_OT_view_zoom_ratio(), and TRANSFORM_OT_seq_slide().
int ED_operator_timeline_active (struct bContext * C)
Definition at line 205 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_TIME.
Referenced by TIME_OT_end_frame_set(), TIME_OT_start_frame_set(), and TIME_OT_view_all().
int ED_operator_uvedit (struct bContext * C)
Definition at line 361 of file screen_ops.c.
References CTX_data_edit_object(), CTX_wm_space_image(), and ED_space_image_show_uvedit().
Referenced by image_view_selected_poll(), UV_OT_average_islands_scale(), UV_OT_hide(), UV_OT_mark_seam(), UV_OT_minimize_stretch(), UV_OT_pack_islands(), UV_OT_pin(), UV_OT_reveal(), UV_OT_seams_from_islands(), UV_OT_select_all(), UV_OT_select_pinned(), UV_OT_stitch(), UV_OT_unlink_selected(), and UV_OT_weld().
int ED_operator_uvmap (struct bContext * C)
Definition at line 368 of file screen_ops.c.
References BMEditMesh::bm, BMEdit_FromObject(), CTX_data_edit_object(), FALSE, NULL, OB_MESH, BMesh::totface, TRUE, and Object::type.
Referenced by uv_from_view_poll(), UV_OT_cube_project(), UV_OT_cylinder_project(), UV_OT_reset(), UV_OT_sphere_project(), and UV_OT_unwrap().
int ED_operator_view3d_active (struct bContext * C)
Definition at line 178 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_VIEW3D.
Referenced by armature_select_linked_poll(), ED_operator_editmesh_view3d(), EM_view3d_poll(), OBJECT_OT_hide_render_clear(), OBJECT_OT_hide_render_set(), OBJECT_OT_hide_view_clear(), OBJECT_OT_hide_view_set(), OBJECT_OT_slow_parent_clear(), OBJECT_OT_slow_parent_set(), pose_select_linked_poll(), TRANSFORM_OT_select_orientation(), view3d_camera_active_poll(), view3d_layers_poll(), VIEW3D_OT_background_image_add(), VIEW3D_OT_background_image_remove(), VIEW3D_OT_cursor3d(), VIEW3D_OT_enable_manipulator(), VIEW3D_OT_fly(), VIEW3D_OT_localview(), VIEW3D_OT_manipulator(), VIEW3D_OT_move(), VIEW3D_OT_ndof_orbit(), VIEW3D_OT_ndof_pan(), VIEW3D_OT_properties(), VIEW3D_OT_select(), VIEW3D_OT_smoothview(), VIEW3D_OT_snap_cursor_to_active(), VIEW3D_OT_snap_cursor_to_center(), VIEW3D_OT_snap_cursor_to_selected(), VIEW3D_OT_snap_selected_to_cursor(), VIEW3D_OT_toolshelf(), and VIEW3D_OT_view_center_cursor().
void ED_operatortypes_screen (void)
Definition at line 3403 of file screen_ops.c.
References ED_OT_redo(), ED_OT_undo(), ED_OT_undo_history(), ED_OT_undo_push(), SCENE_OT_delete(), SCENE_OT_new(), SCREEN_OT_actionzone(), SCREEN_OT_animation_cancel(), SCREEN_OT_animation_play(), SCREEN_OT_animation_step(), SCREEN_OT_area_dupli(), SCREEN_OT_area_join(), SCREEN_OT_area_move(), SCREEN_OT_area_options(), SCREEN_OT_area_split(), SCREEN_OT_area_swap(), SCREEN_OT_back_to_previous(), SCREEN_OT_delete(), SCREEN_OT_frame_jump(), SCREEN_OT_frame_offset(), SCREEN_OT_header_flip(), SCREEN_OT_header_toolbox(), SCREEN_OT_keyframe_jump(), SCREEN_OT_new(), SCREEN_OT_redo_last(), SCREEN_OT_region_flip(), SCREEN_OT_region_quadview(), SCREEN_OT_region_scale(), SCREEN_OT_repeat_history(), SCREEN_OT_repeat_last(), SCREEN_OT_screen_full_area(), SCREEN_OT_screen_set(), SCREEN_OT_screencast(), SCREEN_OT_screenshot(), SCREEN_OT_spacedata_cleanup(), SCREEN_OT_userpref_show(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
void ED_refresh_viewport_fps (struct bContext * C)
Definition at line 1711 of file screen_edit.c.
References bScreen::animtimer, CTX_data_scene(), CTX_wm_screen(), Scene::fps_info, ScreenFrameRateInfo::lredrawtime, wmTimer::ltime, MEM_callocN(), MEM_freeN(), NULL, ScreenFrameRateInfo::redrawtime, and USER_SHOW_FPS.
Referenced by screen_animation_step().
void ED_region_do_draw (struct bContext * C, struct ARegion * ar)
Definition at line 443 of file area.c.
References BLF_draw_default(), BLF_DRAW_STR_DUMMY_MAX, CTX_wm_area(), CTX_wm_window(), ARegion::do_draw, ARegionType::do_lock, ARegionType::draw, ARegion::drawrct, ED_region_draw_cb_draw(), ED_region_pixelspace(), ARegion::headerstr, MAX2, MIN2, region_draw_emboss(), REGION_DRAW_POST_PIXEL, region_scissor_winrct(), ARegionType::regionid, ScrArea::spacetype, ARegion::swinid, TH_HEADER, TH_TEXT, ARegion::type, UI_SetTheme(), UI_ThemeClearColor(), UI_ThemeColor(), ARegion::uiblocks, uiFreeInactiveBlocks(), wmSubWindowScissorSet(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by redraw_timer_exec(), wm_method_draw_full(), wm_method_draw_overlap_all(), and wm_method_draw_triple().
void ED_region_do_listen (struct ARegion * ar, struct wmNotifier * note)
Definition at line 115 of file area.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), ARegionType::listener, NC_WINDOW, NC_WM, ND_FILEREAD, and ARegion::type.
Referenced by wm_event_do_notifiers().
void ED_region_exit (struct bContext * C, struct ARegion * ar)
Definition at line 1129 of file screen_edit.c.
References CTX_wm_region(), CTX_wm_region_set(), CTX_wm_window(), ARegion::handlers, ARegion::headerstr, MEM_freeN(), NULL, ARegion::swinid, WM_event_remove_handlers(), and wm_subwindow_close().
Referenced by ED_area_exit(), ED_screen_exit(), region_quadview_exec(), and ui_remove_temporary_region().
void ED_region_header (const struct bContext * C, struct ARegion * ar)
Referenced by action_header_area_draw(), clip_header_area_draw(), console_header_area_draw(), file_header_area_draw(), graph_header_area_draw(), image_header_area_draw(), info_header_area_draw(), logic_header_area_draw(), nla_header_area_draw(), node_header_area_draw(), outliner_header_area_draw(), script_header_area_draw(), sequencer_header_area_draw(), text_header_area_draw(), time_header_area_draw(), userpref_header_area_draw(), and view3d_header_area_draw().
void ED_region_header_init (struct ARegion * ar)
Definition at line 1771 of file area.c.
References UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_HEADER, ARegion::winx, and ARegion::winy.
Referenced by action_header_area_init(), clip_header_area_init(), console_header_area_init(), file_header_area_init(), graph_header_area_init(), image_header_area_init(), info_header_area_init(), logic_header_area_init(), nla_header_area_init(), node_header_area_init(), outliner_header_area_init(), script_header_area_init(), sequencer_header_area_init(), text_header_area_init(), time_header_area_init(), userpref_header_area_init(), and view3d_header_area_init().
void ED_region_info_draw (struct ARegion * ar, const char * text, int block, float alpha)
Definition at line 1782 of file area.c.
References BLF_draw(), BLF_DRAW_STR_DUMMY_MAX, BLF_position(), BLF_size(), BLF_width(), TH_TEXT_HI, UI_GetStyle(), UI_ThemeColor(), uiFontStyle::uifont_id, uiStyle::widget, ARegion::winrct, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by draw_movieclip_notes(), draw_render_info(), and view3d_main_area_draw_engine_info().
void ED_region_init (struct bContext * C, struct ARegion * ar)
Definition at line 1257 of file area.c.
References CTX_wm_window(), region_subwindow(), ARegion::winrct, ARegion::winx, ARegion::winy, wmOrtho2(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_popup_block_create(), ui_searchbox_create(), and ui_tooltip_create().
void ED_region_panels (const struct bContext * C, struct ARegion * ar, int vertical, const char * context, int contextnr)
Referenced by buttons_main_area_draw(), clip_properties_area_draw(), clip_tools_area_draw(), file_channel_area_draw(), graph_buttons_area_draw(), image_buttons_area_draw(), image_scope_area_draw(), logic_buttons_area_draw(), nla_buttons_area_draw(), node_buttons_area_draw(), sequencer_buttons_area_draw(), text_properties_area_draw(), userpref_main_area_draw(), view3d_buttons_area_draw(), and view3d_tools_area_draw().
void ED_region_panels_init (struct wmWindowManager * wm, struct ARegion * ar)
Definition at line 1697 of file area.c.
References View2D::align, wmWindowManager::defaultconf, View2D::flag, ARegion::handlers, View2D::keepzoom, View2D::scroll, UI_view2d_region_reinit(), ARegion::v2d, V2D_ALIGN_NO_POS_Y, V2D_COMMONVIEW_PANELS_UI, V2D_IS_INITIALISED, V2D_KEEPZOOM, V2D_SCROLL_BOTTOM, V2D_SCROLL_HORIZONTAL_HIDE, V2D_SCROLL_RIGHT, V2D_SCROLL_VERTICAL_HIDE, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler(), and WM_keymap_find().
Referenced by buttons_main_area_init(), clip_properties_area_init(), clip_tools_area_init(), file_channel_area_init(), graph_buttons_area_init(), image_buttons_area_init(), image_scope_area_init(), logic_buttons_area_init(), nla_buttons_area_init(), node_buttons_area_init(), sequencer_buttons_area_init(), text_properties_area_init(), userpref_main_area_init(), view3d_buttons_area_init(), and view3d_tools_area_init().
void ED_region_pixelspace (struct ARegion * ar)
Definition at line 105 of file area.c.
References ARegion::winrct, wmOrtho2(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by draw_bgpic(), ED_region_do_draw(), ED_region_set(), ED_view3d_draw_offscreen(), EDBM_backbuf_border_mask_init(), UI_view2d_text_cache_draw(), view3d_cached_text_draw_end(), view3d_main_area_draw(), view3d_main_area_draw_engine(), and view3d_main_area_draw_objects().
void ED_region_set (const struct bContext * C, struct ARegion * ar)
Referenced by wm_method_draw_triple().
void ED_region_tag_redraw (struct ARegion * ar)
Definition at line 504 of file area.c.
References ARegion::do_draw, ARegion::drawrct, and RGN_DRAW.
Referenced by action_channel_area_listener(), action_header_area_listener(), action_main_area_listener(), axis_set_view(), backimage_zoom(), button_activate_exit(), button_activate_state(), center_current_frame_exec(), clip_main_area_listener(), clip_properties_area_listener(), clip_props_area_listener(), console_main_area_listener(), curvemap_buttons_redraw(), curvemap_buttons_zoom_in(), curvemap_buttons_zoom_out(), curvemap_tools_dofunc(), do_item_rename(), do_outliner_operation_event(), ED_area_headerprint(), ED_area_tag_redraw(), ED_area_tag_redraw_regiontype(), ED_region_do_listen(), ED_screen_set_subwinactive(), edbm_vertex_slide_modal(), face_select_all_exec(), face_select_hide_exec(), face_select_inverse_exec(), face_select_reveal_exec(), file_main_area_listener(), file_smoothscroll_invoke(), file_ui_area_listener(), fly_modal(), gpencil_draw_apply_event(), grab_clone_apply(), graph_region_listener(), hide_show_exec(), image_buttons_area_listener(), image_header_area_listener(), image_main_area_listener(), image_scope_area_listener(), image_view_all_exec(), image_view_ndof_invoke(), image_view_pan_exec(), image_view_pan_exit(), image_view_selected_exec(), image_view_zoom_exec(), image_view_zoom_exit(), image_view_zoom_in_exec(), image_view_zoom_invoke(), image_view_zoom_modal(), image_view_zoom_out_exec(), image_view_zoom_ratio_exec(), info_header_listener(), info_main_area_listener(), keymap_type_cb(), knifetool_exit(), knifetool_init(), knifetool_modal(), knifetool_update_mval(), logic_listener(), loopcut_modal(), ndof_orbit_invoke(), ndof_pan_invoke(), nla_channel_area_listener(), nla_main_area_listener(), nla_region_listener(), node_link_modal(), node_region_listener(), node_resize_modal(), node_view_all_exec(), outliner_border_select_exec(), outliner_header_area_listener(), outliner_item_activate(), outliner_item_openclose(), outliner_main_area_listener(), outliner_one_level_exec(), outliner_scroll_page_exec(), outliner_show_active_exec(), outliner_show_hierarchy_exec(), outliner_toggle_expanded_exec(), outliner_toggle_selectability_exec(), outliner_toggle_selected_exec(), outliner_toggle_visibility_exec(), paint_redraw(), paint_select_linked_exec(), paint_select_linked_pick_invoke(), paintface_mouse_select(), panel_activate_state(), radial_control_modal(), redraw_timer_exec(), rename_anim_channels(), renamebutton_cb(), reset_exec(), ringsel_exit(), ringsel_init(), run_pyfile_exec(), sclip_zoom_set_factor_exec(), screen_animation_step(), scroller_activate_apply(), scroller_activate_exit(), scroller_activate_init(), sculpt_flush_update(), sequencer_buttons_area_listener(), sequencer_main_area_listener(), sequencer_preview_area_listener(), sequencer_view_zoom_ratio_exec(), smooth_view(), snode_bg_viewmove_modal(), stitch_modal(), time_header_area_listener(), time_main_area_listener(), time_view_all_exec(), ui_do_animate(), ui_do_but_HOTKEYEVT(), ui_do_but_textedit(), ui_do_but_textedit_select(), ui_do_button(), ui_do_drag(), ui_handle_button_event(), ui_handle_list_event(), ui_handle_panel_header(), ui_handler_panel_region(), ui_menu_scroll(), ui_numedit_apply(), ui_popup_block_create(), ui_searchbox_create(), ui_searchbox_select(), ui_searchbox_update(), ui_tooltip_create(), UI_view2d_sync(), uiContextAnimUpdate(), uiEndPanels(), uv_sculpt_stroke_modal(), vert_select_all_exec(), vert_select_inverse_exec(), vertex_color_set_exec(), view3d_all_exec(), view3d_boxview_copy(), view3d_boxview_sync(), view3d_buttons_area_listener(), view3d_clipping_invoke(), view3d_header_area_listener(), view3d_main_area_draw_objects(), view3d_main_area_listener(), view3d_props_area_listener(), view_all_exec(), view_borderzoom_exec(), view_pan_apply(), view_pan_exec(), view_pan_exit(), view_selected_exec(), view_zoom_exec(), view_zoom_exit(), view_zoom_in_exec(), view_zoom_modal(), view_zoom_out_exec(), view_zoom_ratio_exec(), view_zoomdrag_apply(), view_zoomstep_apply(), viewdolly_apply(), viewdolly_exec(), viewmove_apply(), viewops_data_free(), viewpan_exec(), viewpersportho_exec(), viewrotate_apply(), viewrotate_invoke(), viewzoom_apply(), viewzoom_exec(), vpaint_stroke_update_step(), vtx_slide_confirm(), vtx_slide_init(), weight_paint_set_exec(), wm_method_draw_overlap_all(), wm_tag_redraw_overlay(), and wpaint_stroke_update_step().
void ED_region_tag_redraw_overlay (struct ARegion * ar)
Definition at line 513 of file area.c.
References ARegion::do_draw_overlay, and RGN_DRAW.
Referenced by view3d_main_area_listener().
void ED_region_tag_redraw_partial (struct ARegion * ar, struct rcti * rct)
Definition at line 519 of file area.c.
References ARegion::do_draw, ARegion::drawrct, MAX2, MIN2, RGN_DRAW_PARTIAL, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by sculpt_flush_update().
void ED_region_toggle_hidden (struct bContext * C, struct ARegion * ar)
Definition at line 1272 of file area.c.
References CTX_wm_area(), CTX_wm_manager(), CTX_wm_window(), ED_area_initialize(), ED_area_tag_redraw(), ARegion::flag, ARegion::handlers, RGN_FLAG_HIDDEN, and WM_event_remove_handlers().
Referenced by file_bookmark_toggle_exec(), graph_properties(), image_properties(), image_scopes(), logic_properties(), nla_properties(), node_properties(), properties_exec(), region_scale_toggle_hidden(), sequencer_properties(), text_properties_exec(), tools_exec(), view3d_properties(), view3d_toolshelf(), and WM_init_game().
bScreen* ED_screen_add (struct wmWindow * win, struct Scene * scene, const char * name)
Definition at line 417 of file screen_edit.c.
References alloc_libblock(), bScreen::do_refresh, G, HEADERDOWN, ID_SCR, bScreen::redraws_flag, bScreen::scene, screen_addarea(), screen_addedge(), screen_addvert(), wmWindow::sizex, wmWindow::sizey, SPACE_EMPTY, TIME_ALL_3D_WIN, TIME_ALL_ANIM_WIN, wmWindow::winid, and bScreen::winid.
Referenced by area_dupli_invoke(), ED_screen_duplicate(), ED_screen_full_toggle(), and WM_window_open_temp().
int ED_screen_animation_play (struct bContext * C, int sync, int mode)
Definition at line 3033 of file screen_ops.c.
References bScreen::animtimer, ScreenAnimData::ar, CTX_data_scene(), CTX_wm_region(), CTX_wm_screen(), wmTimer::customdata, ED_screen_animation_timer(), OPERATOR_FINISHED, bScreen::redraws_flag, sound_play_scene(), sound_stop_scene(), and SPACE_TIME.
Referenced by screen_animation_cancel_exec(), screen_animation_play_exec(), screen_render_invoke(), and wm_event_do_handlers().
void ED_screen_animation_timer (struct bContext * C, int redraws, int refresh, int sync, int enable)
Definition at line 1739 of file screen_edit.c.
References ANIMPLAY_FLAG_NO_SYNC, ANIMPLAY_FLAG_REVERSE, ANIMPLAY_FLAG_SYNC, bScreen::animtimer, ScreenAnimData::ar, RenderData::cfra, CTX_data_scene(), CTX_wm_manager(), CTX_wm_region(), CTX_wm_screen(), CTX_wm_window(), wmTimer::customdata, ScreenAnimData::flag, FPS, MEM_callocN(), NC_SCREEN, ND_ANIMPLAY, NULL, Scene::r, ScreenAnimData::redraws, ScreenAnimData::refresh, RenderData::sfra, ScreenAnimData::sfra, TIMER0, WM_event_add_notifier(), WM_event_add_timer(), and WM_event_remove_timer().
Referenced by ED_screen_animation_play().
void ED_screen_animation_timer_update (struct bScreen * screen, int redraws, int refresh)
Definition at line 1800 of file screen_edit.c.
References bScreen::animtimer, ScreenAnimData::ar, wmTimer::customdata, NULL, ScreenAnimData::redraws, ScreenAnimData::refresh, TIME_REGION, and time_top_left_3dwindow().
int ED_screen_area_active (const struct bContext * C)
Referenced by buttons_header_area_draw(), and ED_region_header().
void ED_screen_delete (struct bContext * C, struct bScreen * sc)
Definition at line 1395 of file screen_edit.c.
References CTX_data_main(), CTX_wm_manager(), CTX_wm_window(), ED_screen_set(), ed_screen_used(), free_libblock(), bScreen::full, bScreen::id, ID::next, ID::prev, Main::screen, wmWindow::screen, and SCREENFULL.
Referenced by wm_event_do_notifiers().
void ED_screen_delete_scene (struct bContext * C, struct Scene * scene)
Definition at line 1509 of file screen_edit.c.
References CTX_data_main(), CTX_wm_screen(), ED_screen_set_scene(), Scene::id, ID::next, ID::prev, and unlink_scene().
Referenced by scene_delete_exec().
void ED_screen_do_listen (struct bContext * C, struct wmNotifier * note)
Definition at line 961 of file screen_edit.c.
References wmNotifier::action, wmNotifier::category, CTX_wm_window(), wmNotifier::data, bScreen::do_draw, bScreen::do_refresh, NA_EDITED, NC_SCENE, NC_SCREEN, NC_WINDOW, NC_WM, ND_FILEREAD, ND_MODE, ND_SUBWINACTIVE, region_cursor_set(), wmWindow::screen, wmNotifier::swinid, and uiFreeActiveButtons().
Referenced by wm_event_do_notifiers().
void ED_screen_draw (struct wmWindow * win)
Definition at line 988 of file screen_edit.c.
References AREA_FLAG_DRAWJOINFROM, AREA_FLAG_DRAWJOINTO, AREA_FLAG_DRAWSPLIT_H, AREA_FLAG_DRAWSPLIT_V, area_getorientation(), bScreen::areabase, bScreen::do_draw, drawscredge_area(), wmWindow::eventstate, ListBase::first, ScrArea::flag, bScreen::mainwin, ScrArea::next, NULL, scrarea_draw_shape_dark(), scrarea_draw_shape_light(), wmWindow::screen, sdrawline(), wmWindow::sizex, wmWindow::sizey, ScrArea::totrct, wmSubWindowSet(), wmEvent::x, rcti::xmax, rcti::xmin, wmEvent::y, rcti::ymax, and rcti::ymin.
Referenced by wm_method_draw_full(), wm_method_draw_overlap_all(), and wm_method_draw_triple().
bScreen* ED_screen_duplicate (struct wmWindow * win, struct bScreen * sc)
Definition at line 928 of file screen_edit.c.
References ED_screen_add(), bScreen::full, bScreen::id, ID::name, NULL, bScreen::scene, screen_copy(), and SCREENNORMAL.
Referenced by screen_new_exec(), wm_window_copy(), and wm_window_match_do().
void ED_screen_exit (struct bContext * C, struct wmWindow * window, struct bScreen * screen)
Definition at line 1169 of file screen_edit.c.
References bScreen::animtimer, bScreen::areabase, CTX_wm_manager(), CTX_wm_window(), CTX_wm_window_set(), ED_area_exit(), ED_region_exit(), ListBase::first, bScreen::mainwin, ScrArea::next, ARegion::next, NULL, bScreen::regionbase, wmWindow::screen, bScreen::subwinactive, bScreen::temp, bScreen::winid, WM_event_remove_timer(), and wm_subwindow_close().
Referenced by ED_screen_set(), WM_exit_ext(), wm_window_close(), and wm_window_match_init().
ScrArea* ED_screen_full_newspace (struct bContext * C, ScrArea * sa, int type)
Definition at line 1526 of file screen_edit.c.
References AREA_TEMP_INFO, bScreen::areabase, CTX_wm_screen(), CTX_wm_window(), ED_area_newspace(), ED_screen_full_toggle(), ListBase::first, ScrArea::flag, ScrArea::full, ScrArea::next, and NULL.
Referenced by render_view_open(), and wm_handler_fileselect_call().
void ED_screen_full_prevspace (struct bContext * C, ScrArea * sa)
Definition at line 1556 of file screen_edit.c.
References CTX_wm_window(), ED_area_prevspace(), ED_screen_full_toggle(), and ScrArea::full.
Referenced by ED_screen_full_restore(), render_view_cancel_exec(), render_view_show_invoke(), and wm_handler_fileselect_call().
void ED_screen_full_restore (struct bContext * C, ScrArea * sa)
Definition at line 1567 of file screen_edit.c.
References CTX_wm_window(), ED_screen_full_prevspace(), ED_screen_full_toggle(), ListBase::first, SpaceImage::flag, SpaceLink::next, SI_FULLWINDOW, SI_PREVSPACE, SPACE_FILE, SPACE_IMAGE, ScrArea::spacedata, and SpaceLink::spacetype.
Referenced by fullscreen_back_exec(), and screen_set_exec().
struct ScrArea* ED_screen_full_toggle (struct bContext * C, struct wmWindow * win, struct ScrArea * sa) [read]
Definition at line 1610 of file screen_edit.c.
References bScreen::animtimer, area_copy_data(), area_split(), AREA_TEMP_INFO, bScreen::areabase, BLI_snprintf(), CTX_data_main(), CTX_wm_area_set(), ED_area_headerprint(), ED_area_newspace(), ED_screen_add(), ED_screen_set(), ListBase::first, ScrArea::flag, free_libblock(), free_screen(), bScreen::full, ScrArea::full, G, G_DEBUG, bScreen::id, ListBase::last, MAX_ID_NAME, ID::name, ScrArea::next, ARegion::next, NULL, ScrArea::prev, ScrArea::regionbase, bScreen::scene, wmWindow::screen, SCREENFULL, SPACE_INFO, ARegion::uiblocks, and uiFreeBlocks().
Referenced by ED_screen_full_newspace(), ED_screen_full_prevspace(), ED_screen_full_restore(), render_view_cancel_exec(), screen_full_area_exec(), and WM_init_game().
void ED_screen_refresh (struct wmWindowManager * wm, struct wmWindow * win)
Definition at line 1071 of file screen_edit.c.
References bScreen::animtimer, bScreen::areabase, bScreen::context, bScreen::do_refresh, ED_area_initialize(), ed_screen_context(), ListBase::first, G, G_DEBUG_EVENTS, bScreen::mainwin, ScrArea::next, wmWindow::screen, screen_refresh_headersizes(), screen_test_scale(), wmWindow::sizex, wmWindow::sizey, WM_event_timer_sleep(), wm_subwindow_open(), wm_subwindow_position(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ED_screen_set(), ED_screens_initialize(), wm_debug_menu_exec(), and wm_draw_update().
void ED_screen_set (struct bContext * C, struct bScreen * sc)
Definition at line 1322 of file screen_edit.c.
References bScreen::animtimer, bScreen::areabase, CTX_data_main(), CTX_wm_manager(), CTX_wm_screen(), CTX_wm_window(), CTX_wm_window_set(), ED_screen_exit(), ED_screen_refresh(), ListBase::first, ScrArea::full, bScreen::full, bScreen::id, wmWindow::modalhandlers, NC_SCREEN, NC_WINDOW, ND_SCREENSET, ScrArea::next, ID::next, NULL, wmWindow::screen, wmWindow::winid, bScreen::winid, WM_event_add_mousemove(), WM_event_add_notifier(), WM_event_remove_area_handler(), and WM_event_timer_sleep().
Referenced by ED_screen_delete(), ED_screen_full_toggle(), screen_set_exec(), wm_event_do_notifiers(), and WM_window_open_temp().
void ED_screen_set_scene (struct bContext * C, struct bScreen * screen, struct Scene * scene)
Definition at line 1433 of file screen_edit.c.
References bScreen::areabase, BKE_screen_view3d_sync(), View3D::camera, CTX_data_main(), CTX_data_scene_set(), CTX_wm_manager(), ED_object_exit_editmode(), ED_render_engine_changed(), ed_screen_used(), ED_update_for_newframe(), EM_DO_UNDO, EM_FREEDATA, ListBase::first, bScreen::id, NC_WINDOW, ScrArea::next, SpaceLink::next, ARegion::next, ID::next, NULL, object_in_scene(), RegionView3D::persp, View3D::regionbase, ARegion::regiondata, ARegion::regiontype, RGN_TYPE_WINDOW, RV3D_CAMOB, RV3D_PERSP, bScreen::scene, scene_find_camera(), set_scene_bg(), SPACE_VIEW3D, ScrArea::spacedata, SpaceLink::spacetype, USER_SCENEGLOBAL, and WM_event_add_notifier().
Referenced by do_outliner_item_activate(), ED_screen_delete_scene(), outliner_do_object_operation(), outliner_object_operation_exec(), scene_new_exec(), and tree_element_active_world().
void ED_screen_set_subwinactive (struct bContext * C, struct wmEvent * event)
Definition at line 1246 of file screen_edit.c.
References bScreen::areabase, BLI_in_rcti(), CTX_wm_window(), ED_region_tag_redraw(), ListBase::first, is_in_area_actionzone(), bScreen::mainwin, NC_SCREEN, ND_SUBWINACTIVE, ARegion::next, ScrArea::next, NULL, region_cursor_set(), ScrArea::regionbase, ARegion::regiontype, RGN_TYPE_HEADER, wmWindow::screen, screen_cursor_set(), bScreen::subwinactive, ARegion::swinid, ScrArea::totrct, ARegion::winrct, WM_event_add_notifier(), wmEvent::x, rcti::xmax, rcti::xmin, wmEvent::y, rcti::ymax, and rcti::ymin.
Referenced by wm_event_do_handlers().
void ED_screens_initialize (struct wmWindowManager * wm)
Definition at line 1113 of file screen_edit.c.
References ED_screen_refresh(), ListBase::first, G, wmWindow::next, NULL, wmWindow::screen, and wmWindowManager::windows.
Referenced by WM_check(), and wm_window_match_do().
void ED_spacetypes_init (void)
Definition at line 67 of file spacetypes.c.
References BKE_spacetypes_list(), SpaceType::dropboxes, ED_operatormacros_action(), ED_operatormacros_armature(), ED_operatormacros_clip(), ED_operatormacros_curve(), ED_operatormacros_file(), ED_operatormacros_graph(), ED_operatormacros_mesh(), ED_operatormacros_node(), ED_operatormacros_object(), ED_operatortypes_anim(), ED_operatortypes_animchannels(), ED_operatortypes_armature(), ED_operatortypes_curve(), ED_operatortypes_gpencil(), ED_operatortypes_logic(), ED_operatortypes_marker(), ED_operatortypes_mesh(), ED_operatortypes_metaball(), ED_operatortypes_object(), ED_operatortypes_paint(), ED_operatortypes_physics(), ED_operatortypes_render(), ED_operatortypes_screen(), ED_operatortypes_sculpt(), ED_operatortypes_sound(), ED_operatortypes_uvedit(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), ListBase::first, SpaceType::next, SpaceType::operatortypes, spacetypes, UI_buttons_operatortypes(), and UI_view2d_operatortypes().
void ED_spacetypes_keymap (struct wmKeyConfig * keyconf)
Definition at line 149 of file spacetypes.c.
References BKE_spacetypes_list(), ED_keymap_anim(), ED_keymap_animchannels(), ED_keymap_armature(), ED_keymap_curve(), ED_keymap_gpencil(), ED_keymap_mesh(), ED_keymap_metaball(), ED_keymap_object(), ED_keymap_paint(), ED_keymap_physics(), ED_keymap_screen(), ED_keymap_uvedit(), ED_marker_keymap(), ListBase::first, ARegionType::keymap, SpaceType::keymap, ARegionType::next, SpaceType::next, SpaceType::regiontypes, spacetypes, and UI_view2d_keymap().
Referenced by WM_keymap_init().
void ED_update_for_newframe (struct Main * bmain, struct Scene * scene, struct bScreen * screen, int mute)
Referenced by dynamicPaint_bakeImageSequence(), ED_screen_set_scene(), render_endjob(), screen_animation_step(), screen_render_exec(), track_markers_freejob(), wm_event_do_handlers(), and wm_event_do_notifiers().
void region_scissor_winrct (struct ARegion * ar, struct rcti * winrct)
Definition at line 396 of file area.c.
References ARegion::alignment, BLI_isect_rcti(), ELEM, ARegion::flag, NULL, ARegion::prev, RGN_FLAG_HIDDEN, RGN_OVERLAP_LEFT, RGN_OVERLAP_RIGHT, RGN_SPLIT_PREV, ARegion::winrct, rcti::xmax, and rcti::xmin.
Referenced by backdrawview3d(), ED_region_do_draw(), and ED_region_set().