Blender: btGImpactBvh.cpp File Reference
btGImpactBvh.cpp File Reference
#include "btGImpactBvh.h"
#include "LinearMath/btQuickprof.h"
Functions
SIMD_FORCE_INLINE bool _node_collision (btGImpactBvh *boxset0, btGImpactBvh *boxset1, const BT_BOX_BOX_TRANSFORM_CACHE &trans_cache_1to0, int node0, int node1, bool complete_primitive_tests)
static void _find_collision_pairs_recursive (btGImpactBvh *boxset0, btGImpactBvh *boxset1, btPairSet *collision_pairs, const BT_BOX_BOX_TRANSFORM_CACHE &trans_cache_1to0, int node0, int node1, bool complete_primitive_tests)
Function Documentation
static void _find_collision_pairs_recursive (btGImpactBvh * boxset0, btGImpactBvh * boxset1, btPairSet * collision_pairs, const BT_BOX_BOX_TRANSFORM_CACHE & trans_cache_1to0, int node0, int node1, bool complete_primitive_tests) [static]
Definition at line 375 of file btGImpactBvh.cpp.
References _node_collision(), btGImpactBvh::getLeftNode(), btGImpactBvh::getNodeData(), btGImpactBvh::getRightNode(), btGImpactBvh::isLeafNode(), and btPairSet::push_pair().
Referenced by btGImpactBvh::find_collision().
SIMD_FORCE_INLINE bool _node_collision (btGImpactBvh * boxset0, btGImpactBvh * boxset1, const BT_BOX_BOX_TRANSFORM_CACHE & trans_cache_1to0, int node0, int node1, bool complete_primitive_tests)
Definition at line 357 of file btGImpactBvh.cpp.
References btGImpactBvh::getNodeBound().
Referenced by _find_collision_pairs_recursive().