Blender: MT_Matrix4x4.inl File Reference
MT_Matrix4x4.inl File Reference
#include "MT_Optimize.h"
Functions
GEN_INLINE MT_Vector4 operator* (const MT_Matrix4x4 &m, const MT_Vector4 &v)
GEN_INLINE MT_Vector4 operator* (const MT_Vector4 &v, const MT_Matrix4x4 &m)
GEN_INLINE MT_Matrix4x4 operator* (const MT_Matrix4x4 &m1, const MT_Matrix4x4 &m2)
Function Documentation
GEN_INLINE MT_Vector4 operator* (const MT_Matrix4x4 & m, const MT_Vector4 & v)
Definition at line 74 of file MT_Matrix4x4.inl.
References MT_dot().
GEN_INLINE MT_Matrix4x4 operator* (const MT_Matrix4x4 & m1, const MT_Matrix4x4 & m2)
Definition at line 82 of file MT_Matrix4x4.inl.
References MT_Matrix4x4::tdot().
GEN_INLINE MT_Vector4 operator* (const MT_Vector4 & v, const MT_Matrix4x4 & m)
Definition at line 78 of file MT_Matrix4x4.inl.
References MT_Matrix4x4::tdot().