Blender: node_shader_attribute.c File Reference
node_shader_attribute.c File Reference
#include "../node_shader_util.h"
Functions
static void node_shader_init_attribute (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_sh_attribute (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_attribute_out []
Function Documentation
static void node_shader_init_attribute (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 39 of file node_shader_attribute.c.
References MEM_callocN(), and bNode::storage.
Referenced by register_node_type_sh_attribute().
void register_node_type_sh_attribute (bNodeTreeType * ttype)
Definition at line 46 of file node_shader_attribute.c.
References NODE_CLASS_INPUT, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OPTIONS, node_shader_init_attribute(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_ATTRIBUTE.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_attribute_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Color"},
    {   SOCK_VECTOR, 0, "Vector", 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_FLOAT, 0, "Fac", 0.0f, 0.0f, 0.0f, 0.0f, -FLT_MAX, FLT_MAX},
    {   -1, 0, ""   }
}
Definition at line 32 of file node_shader_attribute.c.