Blender: svm_wave.h File Reference
svm_wave.h File Reference
Functions
CCL_NAMESPACE_BEGIN
__device_noinline float svm_wave (NodeWoodType type, float3 p, float scale, float detail, float distortion, float dscale)
__device void svm_node_tex_wave (KernelGlobals *kg, ShaderData *sd, float *stack, uint4 node, int *offset)
Function Documentation
__device void svm_node_tex_wave (KernelGlobals * kg, ShaderData * sd, float * stack, uint4 node, int * offset)
Definition at line 42 of file svm_wave.h.
References co, decode_node_uchar4(), make_float3(), read_node(), stack_load_float3(), stack_load_float_default(), stack_store_float(), stack_store_float3(), stack_valid(), svm_wave(), uint4::w, uint4::x, uint4::y, and uint4::z.
Referenced by svm_eval_nodes().
CCL_NAMESPACE_BEGIN __device_noinline float svm_wave (NodeWoodType type, float3 p, float scale, float detail, float distortion, float dscale)
Definition at line 23 of file svm_wave.h.
References len(), NODE_NOISE_PERLIN, NODE_WAVE_BANDS, NODE_WAVE_SINE, noise_turbulence(), noise_wave(), float3::x, and float3::z.
Referenced by svm_node_tex_wave().