Blender: bpy_util.h File Reference
bpy_util.h File Reference
Python RNA and Operators
#include "RNA_types.h"
Defines
#define BLANK_PYTHON_TYPE {PyVarObject_HEAD_INIT(NULL, 0) NULL}
Functions
char * BPy_enum_as_string (struct EnumPropertyItem *item)
short BPy_reports_to_error (struct ReportList *reports, PyObject *exception, const short clear)
short BPy_errors_to_report (struct ReportList *reports)
struct bContext * BPy_GetContext (void)
void BPy_SetContext (struct bContext *C)
void bpy_context_update (struct bContext *C)
void bpy_context_set (struct bContext *C, PyGILState_STATE *gilstate)
void bpy_context_clear (struct bContext *C, PyGILState_STATE *gilstate)
Detailed Description
Definition in file bpy_util.h.
Define Documentation
#define BLANK_PYTHON_TYPE {PyVarObject_HEAD_INIT(NULL, 0) NULL}
Definition at line 42 of file bpy_util.h.
Function Documentation
void bpy_context_clear (struct bContext * C, PyGILState_STATE * gilstate)
void bpy_context_set (struct bContext * C, PyGILState_STATE * gilstate)
Definition at line 112 of file bpy_interface.c.
References bpy_context_update(), PIL_check_seconds_timer(), and py_call_level.
Referenced by BPY_button_exec(), bpy_class_call(), BPY_modules_load_user(), bpy_prop_update_cb(), bpy_props_enum_itemf(), BPY_string_exec(), cb_region_draw(), and python_script_exec().
void bpy_context_update (struct bContext * C)
Definition at line 99 of file bpy_interface.c.
References BLI_thread_is_main(), bpy_import_main_set(), BPY_modules_update(), BPy_SetContext(), and CTX_data_main().
Referenced by bpy_context_set(), and BPY_modules_load_user().
char* BPy_enum_as_string (struct EnumPropertyItem * item)
Definition at line 44 of file bpy_util.c.
References BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), and EnumPropertyItem::identifier.
Referenced by pyop_call(), pyop_poll(), pyrna_enum_as_string(), and pyrna_enum_value_from_id().
short BPy_errors_to_report (struct ReportList * reports)
Definition at line 79 of file bpy_util.c.
References BKE_report(), BKE_reportf(), NULL, PyC_ExceptionBuffer(), PyC_FileAndNum(), and RPT_ERROR.
Referenced by BPY_button_exec(), bpy_class_call(), BPY_string_exec(), and python_script_exec().
struct bContext* BPy_GetContext (void) [read]
Definition at line 41 of file bpy_util.c.
References __py_context.
Referenced by bpy_atexit(), bpy_class_call(), BPy_init_modules(), bpy_lib_exit(), mathutils_rna_matrix_set(), mathutils_rna_vector_set(), mathutils_rna_vector_set_index(), pyop_as_string(), pyop_call(), pyop_poll(), pyrna_enum_as_string(), pyrna_enum_to_py(), pyrna_func_call(), pyrna_prop_array_ass_subscript(), pyrna_prop_to_enum_bitfield(), pyrna_py_to_prop(), pyrna_py_to_prop_array_index(), pyrna_register_class(), pyrna_string_to_enum(), pyrna_struct_driver_add(), pyrna_struct_driver_remove(), pyrna_struct_keyframe_parse(), and pyrna_unregister_class().
short BPy_reports_to_error (struct ReportList * reports, PyObject * exception, const short clear)
Definition at line 60 of file bpy_util.c.
References BKE_reports_clear(), BKE_reports_string(), MEM_freeN(), NULL, and RPT_ERROR.
Referenced by bpy_lib_enter(), pyop_call(), pyrna_func_call(), pyrna_register_class(), pyrna_struct_driver_add(), pyrna_struct_driver_remove(), pyrna_struct_keyframe_delete(), and pyrna_struct_keyframe_insert().
void BPy_SetContext (struct bContext * C)
Definition at line 42 of file bpy_util.c.
References C.
Referenced by bpy_context_clear(), BPY_context_set(), and bpy_context_update().