Blender: svm_math.h File Reference
svm_math.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device float safe_asinf (float a)
__device float safe_acosf (float a)
__device float safe_powf (float a, float b)
__device float safe_logf (float a, float b)
__device float safe_divide (float a, float b)
__device float svm_math (NodeMath type, float Fac1, float Fac2)
__device float average_fac (float3 v)
__device void svm_vector_math (float *Fac, float3 *Vector, NodeVectorMath type, float3 Vector1, float3 Vector2)
__device void svm_node_math (KernelGlobals *kg, ShaderData *sd, float *stack, uint itype, uint f1_offset, uint f2_offset, int *offset)
__device void svm_node_vector_math (KernelGlobals *kg, ShaderData *sd, float *stack, uint itype, uint v1_offset, uint v2_offset, int *offset)
Function Documentation
__device float average_fac (float3 v)
Definition at line 117 of file svm_math.h.
References fabsf, float3::x, float3::y, and float3::z.
Referenced by svm_vector_math().
__device float safe_acosf (float a)
Definition at line 31 of file svm_math.h.
References acosf, and M_PI_F.
Referenced by sky_angle_between(), and svm_math().
CCL_NAMESPACE_BEGIN __device float safe_asinf (float a)
Definition at line 21 of file svm_math.h.
References asinf, and M_PI_2_F.
Referenced by svm_math().
__device float safe_divide (float a, float b)
Definition at line 61 of file svm_math.h.
Referenced by svm_math().
__device float safe_logf (float a, float b)
Definition at line 53 of file svm_math.h.
References logf.
Referenced by svm_math().
__device float safe_powf (float a, float b)
Definition at line 41 of file svm_math.h.
References powf.
Referenced by svm_math().
__device float svm_math (NodeMath type, float Fac1, float Fac2)
Definition at line 73 of file svm_math.h.
References atanf, cosf, floorf, fmaxf, fminf, NODE_MATH_ADD, NODE_MATH_ARCCOSINE, NODE_MATH_ARCSINE, NODE_MATH_ARCTANGENT, NODE_MATH_COSINE, NODE_MATH_DIVIDE, NODE_MATH_GREATER_THAN, NODE_MATH_LESS_THAN, NODE_MATH_LOGARITHM, NODE_MATH_MAXIMUM, NODE_MATH_MINIMUM, NODE_MATH_MULTIPLY, NODE_MATH_POWER, NODE_MATH_ROUND, NODE_MATH_SINE, NODE_MATH_SUBTRACT, NODE_MATH_TANGENT, safe_acosf(), safe_asinf(), safe_divide(), safe_logf(), safe_powf(), sinf, and tanf.
Referenced by svm_node_math().
__device void svm_node_math (KernelGlobals * kg, ShaderData * sd, float * stack, uint itype, uint f1_offset, uint f2_offset, int * offset)
Definition at line 157 of file svm_math.h.
References read_node(), stack_load_float(), stack_store_float(), svm_math(), and uint4::y.
Referenced by svm_eval_nodes().
__device void svm_node_vector_math (KernelGlobals * kg, ShaderData * sd, float * stack, uint itype, uint v1_offset, uint v2_offset, int * offset)
Definition at line 169 of file svm_math.h.
References read_node(), stack_load_float3(), stack_store_float(), stack_store_float3(), stack_valid(), svm_vector_math(), uint4::y, and uint4::z.
Referenced by svm_eval_nodes().
__device void svm_vector_math (float * Fac, float3 * Vector, NodeVectorMath type, float3 Vector1, float3 Vector2)
Definition at line 122 of file svm_math.h.
References average_fac(), cross(), dot(), len(), make_float3(), NODE_VECTOR_MATH_ADD, NODE_VECTOR_MATH_AVERAGE, NODE_VECTOR_MATH_CROSS_PRODUCT, NODE_VECTOR_MATH_DOT_PRODUCT, NODE_VECTOR_MATH_NORMALIZE, NODE_VECTOR_MATH_SUBTRACT, and normalize().
Referenced by svm_node_vector_math().