Blender: gpencil_ops.c File Reference
gpencil_ops.c File Reference
gpencil
#include <stdlib.h>
#include <stddef.h>
#include <stdio.h>
#include "BLO_sys_types.h"
#include "BLI_blenlib.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "ED_gpencil.h"
#include "gpencil_intern.h"
Functions
void ED_keymap_gpencil (wmKeyConfig *keyconf)
void ED_operatortypes_gpencil (void)
Detailed Description
Definition in file gpencil_ops.c.
Function Documentation
void ED_keymap_gpencil (wmKeyConfig * keyconf)
Definition at line 51 of file gpencil_ops.c.
References DKEY, GP_PAINTMODE_DRAW, GP_PAINTMODE_DRAW_POLY, GP_PAINTMODE_DRAW_STRAIGHT, GP_PAINTMODE_ERASER, KM_CTRL, KM_PRESS, LEFTMOUSE, wmKeyMapItem::ptr, RIGHTMOUSE, RNA_enum_set(), WM_keymap_add_item(), and WM_keymap_find().
Referenced by ED_spacetypes_keymap().
void ED_operatortypes_gpencil (void)
Definition at line 73 of file gpencil_ops.c.
References GPENCIL_OT_active_frame_delete(), GPENCIL_OT_convert(), GPENCIL_OT_data_add(), GPENCIL_OT_data_unlink(), GPENCIL_OT_draw(), GPENCIL_OT_layer_add(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().