Blender: CFloatValue Class Reference
CFloatValue Class Reference
#include <FloatValue.h>
Public Member Functions
CFloatValue ()
CFloatValue (float fl)
CFloatValue (float fl, const char *name, AllocationTYPE alloctype=CValue::HEAPVALUE)
virtual const STR_String & GetText ()
void Configure (CValue *menuvalue)
virtual double GetNumber ()
virtual void SetValue (CValue *newval)
float GetFloat ()
void SetFloat (float fl)
virtual ~CFloatValue ()
virtual CValue * GetReplica ()
virtual CValue * Calc (VALUE_OPERATOR op, CValue *val)
virtual CValue * CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue *val)
Protected Attributes
float m_float
STR_String * m_pstrRep
Detailed Description
Definition at line 24 of file FloatValue.h.
Constructor & Destructor Documentation
CFloatValue::CFloatValue ()
Definition at line 29 of file FloatValue.cpp.
References m_pstrRep, and NULL.
Referenced by Calc(), CalcFinal(), and GetReplica().
CFloatValue::CFloatValue (float fl)
Definition at line 40 of file FloatValue.cpp.
References m_float, m_pstrRep, and NULL.
CFloatValue::CFloatValue (float fl, const char * name, AllocationTYPE alloctype = CValue::HEAPVALUE)
Definition at line 52 of file FloatValue.cpp.
References CValue::DisableRefCount(), m_float, m_pstrRep, NULL, CPropValue::SetName(), and CValue::STACKVALUE.
CFloatValue::~CFloatValue () [virtual]
Definition at line 71 of file FloatValue.cpp.
References m_pstrRep.
Member Function Documentation
CValue * CFloatValue::Calc (VALUE_OPERATOR op, CValue * val) [virtual]
Implements CValue.
Definition at line 83 of file FloatValue.cpp.
References CValue::CalcFinal(), CFloatValue(), CValue::GetText(), m_float, CValue::op2str(), VALUE_AND_OPERATOR, VALUE_FLOAT_TYPE, VALUE_NEG_OPERATOR, VALUE_NOT_OPERATOR, VALUE_OR_OPERATOR, and VALUE_POS_OPERATOR.
CValue * CFloatValue::CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue * val) [virtual]
Implements CValue.
Definition at line 114 of file FloatValue.cpp.
References CFloatValue(), GetFloat(), GetText(), CValue::GetText(), m_float, CValue::op2str(), VALUE_ADD_OPERATOR, VALUE_BOOL_TYPE, VALUE_DIV_OPERATOR, VALUE_EMPTY_TYPE, VALUE_EQL_OPERATOR, VALUE_ERROR_TYPE, VALUE_FLOAT_TYPE, VALUE_GEQ_OPERATOR, VALUE_GRE_OPERATOR, VALUE_INT_TYPE, VALUE_LEQ_OPERATOR, VALUE_LES_OPERATOR, VALUE_MOD_OPERATOR, VALUE_MUL_OPERATOR, VALUE_NEG_OPERATOR, VALUE_NEQ_OPERATOR, VALUE_POS_OPERATOR, VALUE_STRING_TYPE, and VALUE_SUB_OPERATOR.
void CFloatValue::Configure (CValue * menuvalue)
float CFloatValue::GetFloat ()
Definition at line 269 of file FloatValue.cpp.
References m_float.
Referenced by CalcFinal().
double CFloatValue::GetNumber () [virtual]
Implements CValue.
Definition at line 280 of file FloatValue.cpp.
References m_float.
Referenced by KX_Scene::LogicBeginFrame().
CValue * CFloatValue::GetReplica (void) [virtual]
Implements CValue.
Definition at line 306 of file FloatValue.cpp.
References CFloatValue(), m_pstrRep, NULL, and CValue::ProcessReplica().
const STR_String & CFloatValue::GetText () [virtual]
Implements CValue.
Definition at line 295 of file FloatValue.cpp.
References STR_String::Format(), m_float, and m_pstrRep.
Referenced by CalcFinal().
void CFloatValue::SetFloat (float fl)
Definition at line 261 of file FloatValue.cpp.
References m_float, and CValue::SetModified().
Referenced by KX_Scene::LogicBeginFrame(), and SCA_TimeEventManager::NextFrame().
void CFloatValue::SetValue (CValue * newval) [virtual]
Sets the value to this cvalue.
Attention:
this particular function should never be called. Why not abstract?
Reimplemented from CValue.
Definition at line 287 of file FloatValue.cpp.
References CValue::GetNumber(), m_float, and CValue::SetModified().
Member Data Documentation
float CFloatValue::m_float [protected]
Definition at line 48 of file FloatValue.h.
Referenced by Calc(), CalcFinal(), CFloatValue(), GetFloat(), GetNumber(), GetText(), SetFloat(), and SetValue().
STR_String* CFloatValue::m_pstrRep [protected]
Definition at line 49 of file FloatValue.h.
Referenced by CFloatValue(), GetReplica(), GetText(), and ~CFloatValue().
The documentation for this class was generated from the following files:
FloatValue.h
FloatValue.cpp