Blender: bmo_create.c File Reference
bmo_create.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "BLI_heap.h"
#include "BLI_listbase.h"
#include "BLI_math.h"
#include "BLI_array.h"
#include "BLI_smallhash.h"
#include "BLI_rand.h"
#include "bmesh.h"
#include "intern/bmesh_operators_private.h"
Classes
struct EPathNode
struct EPath
struct PathBase
struct EdgeData
struct VertData
Defines
#define EDGE_MARK 1
#define EDGE_VIS 2
#define FACE_NEW 1
#define ELE_NEW 1
#define ELE_OUT 2
#define ELE_ORIG 4
#define FACE_IGNORE 16
#define SIGN(n) ((n)<0.0f)
#define STRAIGHT(vec11, vec22) (fabsf(dot_v3v3((vec11), (vec22))) > 1.0f - ((float)FLT_EPSILON * 1000.0f))
Typedefs
typedef struct EPathNode EPathNode
typedef struct EPath EPath
typedef struct PathBase PathBase
typedef struct EdgeData EdgeData
typedef struct VertData VertData
Functions
static int count_edge_faces (BMesh *bm, BMEdge *e)
BLI_INLINE BMDiskLink * rs_edge_link_get (BMEdge *e, BMVert *v, EdgeData *e_data)
static int rotsys_append_edge (BMEdge *e, BMVert *v, EdgeData *edata, VertData *vdata)
static void UNUSED_FUNCTION() rotsys_remove_edge (BMEdge *e, BMVert *v, EdgeData *edata, VertData *vdata)
static BMEdge * rotsys_nextedge (BMEdge *e, BMVert *v, EdgeData *edata, VertData *UNUSED(vdata))
static BMEdge * rotsys_prevedge (BMEdge *e, BMVert *v, EdgeData *edata, VertData *UNUSED(vdata))
static void rotsys_reverse (BMEdge *UNUSED(e), BMVert *v, EdgeData *edata, VertData *vdata)
static int UNUSED_FUNCTION() rotsys_count (BMVert *v, EdgeData *edata, VertData *vdata)
static int UNUSED_FUNCTION() rotsys_fill_faces (BMesh *bm, EdgeData *edata, VertData *vdata)
static void rotsys_make_consistent (BMesh *bm, EdgeData *edata, VertData *vdata)
static void init_rotsys (BMesh *bm, EdgeData *edata, VertData *vdata)
static PathBase * edge_pathbase_new (void)
static void edge_pathbase_free (PathBase *pathbase)
static EPath * edge_copy_add_path (PathBase *pb, EPath *path, BMVert *appendv, BMEdge *e)
static EPath * edge_path_new (PathBase *pb, BMVert *start, BMEdge *starte)
static float edge_weight_path (EPath *path, EdgeData *edata, VertData *UNUSED(vdata))
static void edge_free_path (PathBase *pathbase, EPath *path)
static EPath * edge_find_shortest_path (BMesh *bm, BMOperator *op, BMEdge *edge, EdgeData *edata, VertData *vdata, PathBase *pathbase, int group)
BLI_INLINE void vote_on_winding (BMEdge *edge, EPathNode *node, unsigned int winding[2])
void bmo_edgenet_fill_exec (BMesh *bm, BMOperator *op)
static BMEdge * edge_next (BMesh *bm, BMEdge *e)
void bmo_edgenet_prepare (BMesh *bm, BMOperator *op)
void bmo_contextual_create_exec (BMesh *bm, BMOperator *op)
Detailed Description
Definition in file bmo_create.c.
Define Documentation
#define EDGE_MARK 1
Definition at line 40 of file bmo_create.c.
Referenced by bmo_edgenet_fill_exec(), bmo_edgenet_prepare(), edge_find_shortest_path(), edge_next(), and init_rotsys().
#define EDGE_VIS 2
Definition at line 41 of file bmo_create.c.
Referenced by bmo_edgenet_prepare(), and edge_next().
#define ELE_NEW 1
Definition at line 45 of file bmo_create.c.
Referenced by bmo_contextual_create_exec(), and bmo_edgenet_prepare().
#define ELE_ORIG 4
Definition at line 47 of file bmo_create.c.
Referenced by bmo_edgenet_fill_exec().
#define ELE_OUT 2
Definition at line 46 of file bmo_create.c.
Referenced by bmo_contextual_create_exec().
#define FACE_IGNORE 16
Definition at line 49 of file bmo_create.c.
Referenced by bmo_edgenet_fill_exec(), count_edge_faces(), and edge_find_shortest_path().
#define FACE_NEW 1
Definition at line 43 of file bmo_create.c.
Referenced by bmo_edgenet_fill_exec().
#define SIGN (n) ((n)<0.0f)
#define STRAIGHT (vec11, vec22) (fabsf(dot_v3v3((vec11), (vec22))) > 1.0f - ((float)FLT_EPSILON * 1000.0f))
Referenced by init_rotsys(), and TransparentClosure::TransparentClosure().
Typedef Documentation
typedef struct EdgeData EdgeData
typedef struct EPath EPath
typedef struct EPathNode EPathNode
typedef struct PathBase PathBase
typedef struct VertData VertData
Function Documentation
void bmo_contextual_create_exec (BMesh * bm, BMOperator * op)
Definition at line 1274 of file bmo_create.c.
References BM_EDGE, BM_edge_create(), BM_EDGES_OF_VERT, BM_elem_flag_enable, BM_ELEM_SMOOTH, BM_FACE, BM_face_create_ngon_vcloud(), BM_ITER_ELEM, BM_ITER_MESH, BM_VERT, BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_bool_get(), BMO_slot_buffer_count(), BMO_slot_buffer_flag_enable(), BMO_slot_copy(), BMO_slot_int_get(), BMEditSelection::ele, ELE_NEW, ELE_OUT, FALSE, ListBase::first, BMHeader::htype, BMEditSelection::htype, i, if(), BMFace::mat_nr, MEM_freeN(), MEM_mallocN(), BMEditSelection::next, NULL, BMesh::selected, and TRUE.
void bmo_edgenet_fill_exec (BMesh * bm, BMOperator * op)
Definition at line 884 of file bmo_create.c.
References BLI_array_append, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growone, BM_EDGE, BM_edge_exists(), BM_EDGES_OF_MESH, BM_elem_flag_enable, BM_elem_index_get, BM_elem_index_set, BM_ELEM_SMOOTH, BM_FACE, BM_face_create_ngon(), BM_face_exists_multi_edge(), BM_FACES_OF_MESH, BM_ITER_MESH, BM_mesh_elem_index_ensure(), BM_VERT, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_int_get(), BMO_slot_map_contains(), BMO_slot_map_int_get(), BMO_slot_map_int_insert(), count_edge_faces(), edge_find_shortest_path(), edge_free_path(), EDGE_MARK, edge_pathbase_free(), edge_pathbase_new(), ELE_ORIG, BMesh::elem_index_dirty, FACE_IGNORE, FACE_NEW, FALSE, ListBase::first, EdgeData::ftag, EPath::group, i, init_rotsys(), BMEdge::l, ListBase::last, BMFace::mat_nr, MEM_callocN(), MEM_freeN(), EPathNode::next, EPath::nodes, NULL, EdgeData::tag, BMesh::totedge, BMesh::totvert, TRUE, EPathNode::v, and vote_on_winding().
void bmo_edgenet_prepare (BMesh * bm, BMOperator * op)
Definition at line 1096 of file bmo_create.c.
References BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growone, BLI_array_set_length, BM_EDGE, BM_edge_create(), BM_edge_share_vert_count(), BM_vert_in_edge(), BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_vert_edge_flags_count(), BMVert::co, cross_v3_v3v3(), dot_v3v3(), EDGE_MARK, edge_next(), EDGE_VIS, ELE_NEW, i, normal_tri_v3(), NULL, sub_v3_v3v3(), SWAP, TRUE, BMEdge::v1, and BMEdge::v2.
static int count_edge_faces (BMesh * bm, BMEdge * e) [static]
Definition at line 854 of file bmo_create.c.
References BMO_elem_flag_test, BMLoop::f, FACE_IGNORE, i, BMEdge::l, and BMLoop::radial_next.
Referenced by bmo_edgenet_fill_exec(), and rotsys_fill_faces().
static EPath* edge_copy_add_path (PathBase * pb, EPath * path, BMVert * appendv, BMEdge * e) [static]
Definition at line 651 of file bmo_create.c.
References BLI_addtail(), BLI_mempool_alloc(), EPathNode::cure, EPathNode::e, ListBase::first, EPath::group, ListBase::last, EPathNode::next, PathBase::nodepool, EPath::nodes, NULL, PathBase::pathpool, EPathNode::v, and EPath::weight.
Referenced by edge_find_shortest_path().
static EPath* edge_find_shortest_path (BMesh * bm, BMOperator * op, BMEdge * edge, EdgeData * edata, VertData * vdata, PathBase * pathbase, int group) [static]
Definition at line 732 of file bmo_create.c.
References BLI_array_empty, BLI_array_free, BLI_array_growone, BLI_array_staticdeclare, BLI_ghash_free(), BLI_ghash_haskey(), BLI_ghash_insert(), BLI_ghash_new(), BLI_ghash_remove(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BLI_heap_free(), BLI_heap_insert(), BLI_heap_new(), BLI_heap_popmin(), BLI_heap_size(), BM_edge_other_vert(), BM_elem_index_get, BM_face_exists(), BMO_elem_flag_test, BMO_slot_bool_get(), BMO_slot_map_contains(), BMO_slot_map_int_get(), EPathNode::cure, VertData::e, edge_copy_add_path(), edge_free_path(), EDGE_MARK, edge_path_new(), edge_weight_path(), FACE_IGNORE, ListBase::first, EdgeData::ftag, EPath::group, i, ListBase::last, EPathNode::next, EPath::nodes, NULL, rotsys_nextedge(), EPathNode::v, BMEdge::v1, BMEdge::v2, and EPath::weight.
Referenced by bmo_edgenet_fill_exec().
static void edge_free_path (PathBase * pathbase, EPath * path) [static]
Definition at line 720 of file bmo_create.c.
References BLI_mempool_free(), ListBase::first, EPathNode::next, next, PathBase::nodepool, EPath::nodes, and PathBase::pathpool.
Referenced by bmo_edgenet_fill_exec(), and edge_find_shortest_path().
static BMEdge* edge_next (BMesh * bm, BMEdge * e) [static]
Definition at line 1076 of file bmo_create.c.
References BM_EDGES_OF_VERT, BM_ITER_ELEM, BMO_elem_flag_test, EDGE_MARK, EDGE_VIS, i, NULL, BMEdge::v1, and BMEdge::v2.
Referenced by bmo_edgenet_prepare().
static EPath* edge_path_new (PathBase * pb, BMVert * start, BMEdge * starte) [static]
Definition at line 677 of file bmo_create.c.
References BLI_addtail(), BLI_mempool_alloc(), EPathNode::cure, EPathNode::e, ListBase::first, ListBase::last, PathBase::nodepool, EPath::nodes, NULL, PathBase::pathpool, EPathNode::v, and EPath::weight.
Referenced by edge_find_shortest_path().
static void edge_pathbase_free (PathBase * pathbase) [static]
Definition at line 644 of file bmo_create.c.
References BLI_mempool_destroy(), MEM_freeN(), PathBase::nodepool, and PathBase::pathpool.
Referenced by bmo_edgenet_fill_exec().
static PathBase* edge_pathbase_new (void) [static]
Definition at line 634 of file bmo_create.c.
References BLI_mempool_create(), BLI_MEMPOOL_SYSMALLOC, MEM_callocN(), PathBase::nodepool, and PathBase::pathpool.
Referenced by bmo_edgenet_fill_exec().
static float edge_weight_path (EPath * path, EdgeData * edata, VertData * UNUSEDvdata) [static]
Definition at line 697 of file bmo_create.c.
References BM_elem_index_get, EPathNode::e, ListBase::first, EdgeData::ftag, EPathNode::next, EPath::nodes, and EPathNode::prev.
Referenced by edge_find_shortest_path().
static void init_rotsys (BMesh * bm, EdgeData * edata, VertData * vdata) [static]
Definition at line 356 of file bmo_create.c.
References add_v3_v3(), BLI_array_append, BLI_array_empty, BLI_array_free, BLI_array_staticdeclare, BLI_frand(), BLI_srandom(), BM_edge_create(), BM_edge_other_vert(), BM_edge_select_set(), BM_EDGES_OF_VERT, BM_elem_index_get, BM_elem_index_set, BM_ITER_ELEM, BM_ITER_MESH, BM_NGON_STACK_SIZE, BM_vert_create(), BM_vert_edge_count(), BM_vert_select_set(), BM_VERTS_OF_MESH, BMO_elem_flag_test, co, BMVert::co, copy_v3_v3(), cross_v3_v3v3(), dot_v3v3(), VertData::e, EDGE_MARK, FALSE, i, len_v3(), len_v3v3(), mul_v3_fl(), normal_tri_v3(), normalize_v3(), NULL, rotsys_append_edge(), rotsys_make_consistent(), rotsys_nextedge(), VertData::sco, size(), STRAIGHT, sub_v3_v3v3(), SWAP, TRUE, and zero_v3().
Referenced by bmo_edgenet_fill_exec().
static int rotsys_append_edge (BMEdge * e, BMVert * v, EdgeData * edata, VertData * vdata) [static]
Definition at line 90 of file bmo_create.c.
References BM_elem_index_get, VertData::e, BMDiskLink::next, Link::next, NULL, BMDiskLink::prev, Link::prev, rs_edge_link_get(), and TRUE.
Referenced by init_rotsys(), and rotsys_reverse().
static int UNUSED_FUNCTION() rotsys_count (BMVert * v, EdgeData * edata, VertData * vdata) [static]
Definition at line 193 of file bmo_create.c.
References BM_elem_index_get, i, and rotsys_nextedge().
static int UNUSED_FUNCTION() rotsys_fill_faces (BMesh * bm, EdgeData * edata, VertData * vdata) [static]
Definition at line 217 of file bmo_create.c.
References BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_smallhash_haskey(), BLI_smallhash_init(), BLI_smallhash_insert(), BLI_smallhash_release(), BM_edge_other_vert(), BM_EDGES_OF_MESH, BM_face_create_ngon(), BM_ITER_MESH, count_edge_faces(), hash, i, NULL, rotsys_nextedge(), rotsys_prevedge(), TRUE, and BMEdge::v1.
static void rotsys_make_consistent (BMesh * bm, EdgeData * edata, VertData * vdata) [static]
Definition at line 286 of file bmo_create.c.
References BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_pop, BM_edge_other_vert(), BM_elem_index_get, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, dot_v3v3(), VertData::e, i, mul_v3_fl(), VertData::no, NULL, VertData::offco, rotsys_nextedge(), rotsys_reverse(), stack, VertData::tag, and BMesh::totvert.
Referenced by init_rotsys().
static BMEdge* rotsys_nextedge (BMEdge * e, BMVert * v, EdgeData * edata, VertData * UNUSEDvdata) [static]
Definition at line 146 of file bmo_create.c.
References BM_elem_index_get, BMDiskLink::next, NULL, BMEdge::v1, EdgeData::v1_disk_link, BMEdge::v2, and EdgeData::v2_disk_link.
Referenced by edge_find_shortest_path(), init_rotsys(), rotsys_count(), rotsys_fill_faces(), rotsys_make_consistent(), and rotsys_reverse().
static BMEdge* rotsys_prevedge (BMEdge * e, BMVert * v, EdgeData * edata, VertData * UNUSEDvdata) [static]
Definition at line 156 of file bmo_create.c.
References BM_elem_index_get, NULL, BMDiskLink::prev, BMEdge::v1, EdgeData::v1_disk_link, BMEdge::v2, and EdgeData::v2_disk_link.
Referenced by rotsys_fill_faces().
static void UNUSED_FUNCTION() rotsys_remove_edge (BMEdge * e, BMVert * v, EdgeData * edata, VertData * vdata) [static]
Definition at line 122 of file bmo_create.c.
References BM_elem_index_get, VertData::e, BMDiskLink::next, NULL, BMDiskLink::prev, and rs_edge_link_get().
static void rotsys_reverse (BMEdge * UNUSEDe, BMVert * v, EdgeData * edata, VertData * vdata) [static]
Definition at line 166 of file bmo_create.c.
References BLI_array_append, BLI_array_count, BLI_array_free, BLI_array_staticdeclare, BM_elem_index_get, BM_NGON_STACK_SIZE, VertData::e, i, NULL, rotsys_append_edge(), rotsys_nextedge(), and SWAP.
Referenced by rotsys_make_consistent().
BLI_INLINE BMDiskLink* rs_edge_link_get (BMEdge * e, BMVert * v, EdgeData * e_data)
Definition at line 84 of file bmo_create.c.
Referenced by rotsys_append_edge(), and rotsys_remove_edge().
BLI_INLINE void vote_on_winding (BMEdge * edge, EPathNode * node, unsigned int winding[2])
Definition at line 874 of file bmo_create.c.
References BM_edge_ordered_verts(), and EPathNode::v.
Referenced by bmo_edgenet_fill_exec().