Blender: rna_armature.c File Reference
rna_armature.c File Reference
RNA
#include <stdlib.h>
#include "BLI_math.h"
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_armature_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "WM_api.h"
#include "WM_types.h"
Functions
static void rna_def_bone_common (StructRNA *srna, int editbone)
static void rna_def_bone (BlenderRNA *brna)
static void rna_def_edit_bone (BlenderRNA *brna)
static void rna_def_armature_bones (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_armature_edit_bones (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_armature (BlenderRNA *brna)
void RNA_def_armature (BlenderRNA *brna)
Variables
static int rna_matrix_dimsize_4x4 [] = {4, 4}
static int rna_matrix_dimsize_3x3 [] = {3, 3}
Detailed Description
Definition in file rna_armature.c.
Function Documentation
static void rna_def_armature (BlenderRNA * brna) [static]
Definition at line 828 of file rna_armature.c.
References ARM_AUTO_IK, ARM_B_BONE, ARM_COL_CUSTOM, ARM_DEF_ENVELOPE, ARM_DEF_INVERT_VGROUP, ARM_DEF_QUATERNION, ARM_DEF_VGROUP, ARM_DELAYDEFORM, ARM_DRAWAXES, ARM_DRAWNAMES, ARM_ENVELOPE, ARM_GHOST_CUR, ARM_GHOST_KEYS, ARM_GHOST_ONLYSEL, ARM_GHOST_RANGE, ARM_LINE, ARM_MIRROR_EDIT, ARM_NO_CUSTOM, ARM_OCTA, ARM_RESTPOS, ARM_VDEF_BGE_CPU, ARM_VDEF_BLENDER, ARM_WIRE, NC_OBJECT, ND_POSE, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_INT, PROP_LAYER, PROP_LAYER_MEMBER, PROP_LIB_EXCEPTION, PROP_NONE, PROP_TIME, rna_def_animdata_common(), rna_def_armature_bones(), rna_def_armature_edit_bones(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_armature().
void RNA_def_armature (BlenderRNA * brna)
Definition at line 1041 of file rna_armature.c.
References rna_def_armature(), rna_def_bone(), and rna_def_edit_bone().
static void rna_def_armature_bones (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 758 of file rna_armature.c.
References NULL, PROP_EDITABLE, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_armature().
static void rna_def_armature_edit_bones (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 784 of file rna_armature.c.
References FUNC_USE_REPORTS, NULL, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_armature().
static void rna_def_bone (BlenderRNA * brna) [static]
Definition at line 571 of file rna_armature.c.
References BONE_HIDDEN_P, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, FLT_MAX, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_FLOAT, PROP_MATRIX, PROP_NONE, PROP_POINTER, PROP_TRANSLATION, RNA_api_bone(), rna_def_bone_common(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_float_sdna(), RNA_def_property_multi_array(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_idprops_func(), RNA_def_struct_path_func(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and RNA_TRANSLATION_PREC_DEFAULT.
Referenced by RNA_def_armature().
static void rna_def_bone_common (StructRNA * srna, int editbone) [static]
Definition at line 433 of file rna_armature.c.
References BONE_CONNECTED, BONE_DRAWWIRE, BONE_HINGE, BONE_MULT_VG_ENV, BONE_NO_CYCLICOFFSET, BONE_NO_DEFORM, BONE_NO_LOCAL_LOCATION, BONE_NO_SCALE, BONE_UNSELECTABLE, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_LAYER_MEMBER, PROP_NONE, PROP_STRING, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_name_property().
Referenced by rna_def_bone(), and rna_def_edit_bone().
static void rna_def_edit_bone (BlenderRNA * brna) [static]
Definition at line 668 of file rna_armature.c.
References BONE_EDITMODE_LOCKED, BONE_HIDDEN_A, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, M_PI, NULL, PROP_ANGLE, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_EDITABLE, PROP_FLOAT, PROP_MATRIX, PROP_NONE, PROP_POINTER, PROP_THICK_WRAP, PROP_TRANSLATION, RNA_api_armature_edit_bone(), rna_def_bone_common(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_multi_array(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_idprops_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and RNA_define_verify_sdna().
Referenced by RNA_def_armature().
Variable Documentation
int rna_matrix_dimsize_3x3[] = {3, 3} [static]
Definition at line 431 of file rna_armature.c.
int rna_matrix_dimsize_4x4[] = {4, 4} [static]
Definition at line 430 of file rna_armature.c.
Referenced by rna_def_constraint_childof().