Blender: bAnimChannelType Struct Reference
bAnimChannelType Struct Reference
#include <ED_anim_api.h>
Public Attributes
const char * channel_type_name
void(* get_backdrop_color)(bAnimContext *ac, bAnimListElem *ale, float *color)
void(* draw_backdrop)(bAnimContext *ac, bAnimListElem *ale, float yminc, float ymaxc)
short(* get_indent_level)(bAnimContext *ac, bAnimListElem *ale)
short(* get_offset)(bAnimContext *ac, bAnimListElem *ale)
void(* name)(bAnimListElem *ale, char *name)
short(* name_prop)(bAnimListElem *ale, struct PointerRNA *ptr, struct PropertyRNA **prop)
int(* icon)(bAnimListElem *ale)
short(* has_setting)(bAnimContext *ac, bAnimListElem *ale, int setting)
int(* setting_flag)(bAnimContext *ac, int setting, short *neg)
void *(* setting_ptr)(bAnimListElem *ale, int setting, short *type)
Detailed Description
Definition at line 362 of file ED_anim_api.h.
Member Data Documentation
const char* bAnimChannelType::channel_type_name
Definition at line 365 of file ED_anim_api.h.
Referenced by ANIM_channel_debug_print_info().
void(* bAnimChannelType::draw_backdrop)(bAnimContext *ac, bAnimListElem *ale, float yminc, float ymaxc)
Definition at line 371 of file ED_anim_api.h.
Referenced by ANIM_channel_draw().
void(* bAnimChannelType::get_backdrop_color)(bAnimContext *ac, bAnimListElem *ale, float *color)
Definition at line 369 of file ED_anim_api.h.
Referenced by acf_generic_channel_backdrop(), acf_generic_dataexpand_backdrop(), acf_generic_root_backdrop(), acf_group_backdrop(), acf_summary_backdrop(), and ANIM_channel_draw().
short(* bAnimChannelType::get_indent_level)(bAnimContext *ac, bAnimListElem *ale)
Definition at line 373 of file ED_anim_api.h.
Referenced by acf_generic_basic_offset(), and acf_generic_channel_color().
short(* bAnimChannelType::get_offset)(bAnimContext *ac, bAnimListElem *ale)
Definition at line 375 of file ED_anim_api.h.
Referenced by acf_generic_channel_backdrop(), acf_generic_dataexpand_backdrop(), acf_generic_root_backdrop(), acf_group_backdrop(), ANIM_channel_draw(), ANIM_channel_draw_widgets(), and ANIM_flush_setting_anim_channels().
short(* bAnimChannelType::has_setting)(bAnimContext *ac, bAnimListElem *ale, int setting)
Definition at line 386 of file ED_anim_api.h.
Referenced by ANIM_channel_draw(), ANIM_channel_draw_widgets(), ANIM_channel_setting_get(), ANIM_channel_setting_set(), and draw_channel_strips().
int(* bAnimChannelType::icon)(bAnimListElem *ale)
Definition at line 382 of file ED_anim_api.h.
Referenced by ANIM_channel_draw(), and ANIM_channel_draw_widgets().
void(* bAnimChannelType::name)(bAnimListElem *ale, char *name)
Definition at line 378 of file ED_anim_api.h.
Referenced by ANIM_channel_debug_print_info(), ANIM_channel_draw(), and skip_fcurve_with_name().
short(* bAnimChannelType::name_prop)(bAnimListElem *ale, struct PointerRNA *ptr, struct PropertyRNA **prop)
Definition at line 380 of file ED_anim_api.h.
Referenced by ANIM_channel_draw_widgets(), and rename_anim_channels().
int(* bAnimChannelType::setting_flag)(bAnimContext *ac, int setting, short *neg)
Definition at line 388 of file ED_anim_api.h.
Referenced by ANIM_channel_setting_get(), ANIM_channel_setting_set(), and draw_setting_widget().
void*(* bAnimChannelType::setting_ptr)(bAnimListElem *ale, int setting, short *type)
Definition at line 393 of file ED_anim_api.h.
Referenced by ANIM_channel_setting_get(), ANIM_channel_setting_set(), and draw_setting_widget().
The documentation for this struct was generated from the following file:
ED_anim_api.h