Blender: MEM_CacheLimiterHandle< T > Class Template Reference
MEM_CacheLimiterHandle< T > Class Template Reference
#include <MEM_CacheLimiter.h>
Public Member Functions
MEM_CacheLimiterHandle (T *data_, MEM_CacheLimiter< T > *parent_)
void ref ()
void unref ()
T * get ()
const T * get () const
int get_refcount () const
bool can_destroy () const
bool destroy_if_possible ()
void unmanage ()
void touch ()
Friends
class MEM_CacheLimiter< T >
Detailed Description
template<class T>
class MEM_CacheLimiterHandle< T >
Definition at line 74 of file MEM_CacheLimiter.h.
Constructor & Destructor Documentation
template<class T> MEM_CacheLimiterHandle< T >::MEM_CacheLimiterHandle (T * data_, MEM_CacheLimiter< T > * parent_) [inline, explicit]
Definition at line 76 of file MEM_CacheLimiter.h.
Member Function Documentation
template<class T> bool MEM_CacheLimiterHandle< T >::can_destroy () const [inline]
Definition at line 95 of file MEM_CacheLimiter.h.
Referenced by MEM_CacheLimiterHandle< T >::destroy_if_possible().
template<class T> bool MEM_CacheLimiterHandle< T >::destroy_if_possible () [inline]
Definition at line 98 of file MEM_CacheLimiter.h.
References MEM_CacheLimiterHandle< T >::can_destroy(), and MEM_CacheLimiterHandle< T >::unmanage().
template<class T> const T* MEM_CacheLimiterHandle< T >::get () const [inline]
Definition at line 89 of file MEM_CacheLimiter.h.
template<class T> T* MEM_CacheLimiterHandle< T >::get () [inline]
Definition at line 86 of file MEM_CacheLimiter.h.
template<class T> int MEM_CacheLimiterHandle< T >::get_refcount () const [inline]
Definition at line 92 of file MEM_CacheLimiter.h.
template<class T> void MEM_CacheLimiterHandle< T >::ref () [inline]
Definition at line 80 of file MEM_CacheLimiter.h.
template<class T> void MEM_CacheLimiterHandle< T >::touch () [inline]
Definition at line 110 of file MEM_CacheLimiter.h.
template<class T> void MEM_CacheLimiterHandle< T >::unmanage () [inline]
Definition at line 107 of file MEM_CacheLimiter.h.
Referenced by MEM_CacheLimiterHandle< T >::destroy_if_possible().
template<class T> void MEM_CacheLimiterHandle< T >::unref () [inline]
Definition at line 83 of file MEM_CacheLimiter.h.
Friends And Related Function Documentation
template<class T> friend class MEM_CacheLimiter< T > [friend]
Definition at line 114 of file MEM_CacheLimiter.h.
The documentation for this class was generated from the following file:
MEM_CacheLimiter.h