Blender: SMikkTSpaceInterface Struct Reference
SMikkTSpaceInterface Struct Reference
#include <mikktspace.h>
Public Attributes
int(* m_getNumFaces)(const SMikkTSpaceContext *pContext)
int(* m_getNumVerticesOfFace)(const SMikkTSpaceContext *pContext, const int iFace)
void(* m_getPosition)(const SMikkTSpaceContext *pContext, float fvPosOut[], const int iFace, const int iVert)
void(* m_getNormal)(const SMikkTSpaceContext *pContext, float fvNormOut[], const int iFace, const int iVert)
void(* m_getTexCoord)(const SMikkTSpaceContext *pContext, float fvTexcOut[], const int iFace, const int iVert)
void(* m_setTSpaceBasic)(const SMikkTSpaceContext *pContext, const float fvTangent[], const float fSign, const int iFace, const int iVert)
void(* m_setTSpace)(const SMikkTSpaceContext *pContext, const float fvTangent[], const float fvBiTangent[], const float fMagS, const float fMagT, const tbool bIsOrientationPreserving, const int iFace, const int iVert)
Detailed Description
Definition at line 65 of file mikktspace.h.
Member Data Documentation
void(* SMikkTSpaceInterface::m_getNormal)(const SMikkTSpaceContext *pContext, float fvNormOut[], const int iFace, const int iVert)
Definition at line 77 of file mikktspace.h.
Referenced by calc_vertexnormals(), DM_add_tangent_layer(), genTangSpace(), and GetNormal().
int(* SMikkTSpaceInterface::m_getNumFaces)(const SMikkTSpaceContext *pContext)
Definition at line 68 of file mikktspace.h.
Referenced by calc_vertexnormals(), DM_add_tangent_layer(), GenerateInitialVerticesIndexList(), and genTangSpace().
int(* SMikkTSpaceInterface::m_getNumVerticesOfFace)(const SMikkTSpaceContext *pContext, const int iFace)
Definition at line 72 of file mikktspace.h.
Referenced by calc_vertexnormals(), DM_add_tangent_layer(), GenerateInitialVerticesIndexList(), and genTangSpace().
void(* SMikkTSpaceInterface::m_getPosition)(const SMikkTSpaceContext *pContext, float fvPosOut[], const int iFace, const int iVert)
Definition at line 76 of file mikktspace.h.
Referenced by calc_vertexnormals(), DM_add_tangent_layer(), genTangSpace(), and GetPosition().
void(* SMikkTSpaceInterface::m_getTexCoord)(const SMikkTSpaceContext *pContext, float fvTexcOut[], const int iFace, const int iVert)
Definition at line 78 of file mikktspace.h.
Referenced by calc_vertexnormals(), DM_add_tangent_layer(), genTangSpace(), and GetTexCoord().
void(* SMikkTSpaceInterface::m_setTSpace)(const SMikkTSpaceContext *pContext, const float fvTangent[], const float fvBiTangent[], const float fMagS, const float fMagT, const tbool bIsOrientationPreserving, const int iFace, const int iVert)
Definition at line 103 of file mikktspace.h.
Referenced by genTangSpace().
void(* SMikkTSpaceInterface::m_setTSpaceBasic)(const SMikkTSpaceContext *pContext, const float fvTangent[], const float fSign, const int iFace, const int iVert)
Definition at line 90 of file mikktspace.h.
Referenced by calc_vertexnormals(), DM_add_tangent_layer(), and genTangSpace().
The documentation for this struct was generated from the following file:
mikktspace.h