Blender: LOD_GhostTestApp Class Reference
LOD_GhostTestApp Class Reference
#include <LOD_GhostTestApp.h>
Public Member Functions
LOD_GhostTestApp ()
bool InitApp ()
void Run ()
~LOD_GhostTestApp ()
Detailed Description
Definition at line 39 of file LOD_GhostTestApp.h.
Constructor & Destructor Documentation
LOD_GhostTestApp::LOD_GhostTestApp ()
Definition at line 42 of file LOD_GhostTestApp.cpp.
LOD_GhostTestApp::~LOD_GhostTestApp ()
Definition at line 102 of file LOD_GhostTestApp.cpp.
References GHOST_ISystem::disposeSystem(), GHOST_ISystem::disposeWindow(), and NULL.
Member Function Documentation
bool LOD_GhostTestApp::InitApp ()
Definition at line 54 of file LOD_GhostTestApp.cpp.
References GHOST_ISystem::addEventConsumer(), GHOST_ISystem::createSystem(), GHOST_ISystem::createWindow(), GHOST_ISystem::disposeSystem(), FALSE, GHOST_ISystem::getSystem(), GHOST_kDrawingContextTypeOpenGL, GHOST_kFailure, GHOST_kWindowStateNormal, and NULL.
Referenced by main().
void LOD_GhostTestApp::Run ()
Definition at line 89 of file LOD_GhostTestApp.cpp.
References GHOST_ISystem::dispatchEvents(), NULL, GHOST_ISystem::processEvents(), and TRUE.
Referenced by main().
The documentation for this class was generated from the following files:
LOD_GhostTestApp.h
LOD_GhostTestApp.cpp