Blender: svm_fresnel.h File Reference
svm_fresnel.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void svm_node_fresnel (ShaderData *sd, float *stack, uint ior_offset, uint ior_value, uint out_offset)
__device void svm_node_layer_weight (ShaderData *sd, float *stack, uint4 node)
Function Documentation
CCL_NAMESPACE_BEGIN __device void svm_node_fresnel (ShaderData * sd, float * stack, uint ior_offset, uint ior_value, uint out_offset)
Definition at line 23 of file svm_fresnel.h.
References __int_as_float(), dot(), ShaderData::flag, fmaxf, fresnel_dielectric_cos(), ShaderData::I, ShaderData::N, SD_BACKFACING, stack_load_float(), stack_store_float(), and stack_valid().
Referenced by svm_eval_nodes().
__device void svm_node_layer_weight (ShaderData * sd, float * stack, uint4 node)
Definition at line 36 of file svm_fresnel.h.
References __int_as_float(), blend(), clamp, decode_node_uchar4(), dot(), fabsf, ShaderData::flag, fmaxf, fresnel_dielectric_cos(), ShaderData::I, ShaderData::N, NODE_LAYER_WEIGHT_FRESNEL, NULL, powf, SD_BACKFACING, stack_load_float(), stack_store_float(), stack_valid(), uint4::w, uint4::y, and uint4::z.
Referenced by svm_eval_nodes().