Blender: svm_magic.h File Reference
svm_magic.h File Reference
Functions
CCL_NAMESPACE_BEGIN
__device_noinline float3 svm_magic (float3 p, int n, float distortion)
__device void svm_node_tex_magic (KernelGlobals *kg, ShaderData *sd, float *stack, uint4 node, int *offset)
Function Documentation
CCL_NAMESPACE_BEGIN __device_noinline float3 svm_magic (float3 p, int n, float distortion)
Definition at line 23 of file svm_magic.h.
References cosf, make_float3(), sinf, float3::x, float3::y, and float3::z.
Referenced by svm_node_tex_magic().
__device void svm_node_tex_magic (KernelGlobals * kg, ShaderData * sd, float * stack, uint4 node, int * offset)
Definition at line 92 of file svm_magic.h.
References average(), co, decode_node_uchar4(), NULL, read_node(), stack_load_float3(), stack_load_float_default(), stack_store_float(), stack_store_float3(), stack_valid(), svm_magic(), uint4::x, uint4::y, and uint4::z.
Referenced by svm_eval_nodes().