Blender: btSphereTriangleCollisionAlgorithm Class Reference
btSphereTriangleCollisionAlgorithm Class Reference
#include <btSphereTriangleCollisionAlgorithm.h>
Classes
struct CreateFunc
Public Member Functions
btSphereTriangleCollisionAlgorithm (btPersistentManifold *mf, const btCollisionAlgorithmConstructionInfo &ci, btCollisionObject *body0, btCollisionObject *body1, bool swapped)
btSphereTriangleCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo &ci)
virtual void processCollision (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
virtual btScalar calculateTimeOfImpact (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
virtual void getAllContactManifolds (btManifoldArray &manifoldArray)
virtual ~btSphereTriangleCollisionAlgorithm ()
Detailed Description
btSphereSphereCollisionAlgorithm provides sphere-sphere collision detection. Other features are frame-coherency (persistent data) and collision response. Also provides the most basic sample for custom/user btCollisionAlgorithm
Definition at line 28 of file btSphereTriangleCollisionAlgorithm.h.
Constructor & Destructor Documentation
btSphereTriangleCollisionAlgorithm::btSphereTriangleCollisionAlgorithm (btPersistentManifold * mf, const btCollisionAlgorithmConstructionInfo & ci, btCollisionObject * body0, btCollisionObject * body1, bool swapped)
Definition at line 24 of file btSphereTriangleCollisionAlgorithm.cpp.
References btDispatcher::getNewManifold(), and btCollisionAlgorithm::m_dispatcher.
Referenced by btSphereTriangleCollisionAlgorithm::CreateFunc::CreateCollisionAlgorithm().
btSphereTriangleCollisionAlgorithm::btSphereTriangleCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo & ci) [inline]
Definition at line 37 of file btSphereTriangleCollisionAlgorithm.h.
btSphereTriangleCollisionAlgorithm::~btSphereTriangleCollisionAlgorithm () [virtual]
Definition at line 37 of file btSphereTriangleCollisionAlgorithm.cpp.
References btCollisionAlgorithm::m_dispatcher, and btDispatcher::releaseManifold().
Member Function Documentation
btScalar btSphereTriangleCollisionAlgorithm::calculateTimeOfImpact (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Implements btCollisionAlgorithm.
Definition at line 75 of file btSphereTriangleCollisionAlgorithm.cpp.
virtual void btSphereTriangleCollisionAlgorithm::getAllContactManifolds (btManifoldArray & manifoldArray) [inline, virtual]
Implements btCollisionAlgorithm.
Definition at line 44 of file btSphereTriangleCollisionAlgorithm.h.
References btAlignedObjectArray< T >::push_back().
void btSphereTriangleCollisionAlgorithm::processCollision (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
report a contact. internally this will be kept persistent, and contact reduction is done
Todo:
: tighter bounds
Implements btCollisionAlgorithm.
Definition at line 46 of file btSphereTriangleCollisionAlgorithm.cpp.
References BT_LARGE_FLOAT, btDispatcherInfo::m_debugDraw, btDiscreteCollisionDetectorInterface::ClosestPointInput::m_maximumDistanceSquared, btManifoldResult::refreshContactPoints(), and btManifoldResult::setPersistentManifold().
The documentation for this class was generated from the following files:
btSphereTriangleCollisionAlgorithm.h
btSphereTriangleCollisionAlgorithm.cpp