Blender: rna_packedfile.c File Reference
rna_packedfile.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_packedFile_types.h"
Functions
void RNA_def_packedfile (BlenderRNA *brna)
Variables
EnumPropertyItem unpack_method_items []
Detailed Description
Definition in file rna_packedfile.c.
Function Documentation
void RNA_def_packedfile (BlenderRNA * brna)
Definition at line 46 of file rna_packedfile.c.
References NULL, PROP_EDITABLE, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_ui_text(), RNA_def_struct(), and RNA_def_struct_ui_text().
Variable Documentation
EnumPropertyItem unpack_method_items[]
Initial value:
 {
    {PF_USE_LOCAL, "USE_LOCAL", 0, "Use Local File", ""},
    {PF_WRITE_LOCAL, "WRITE_LOCAL", 0, "Write Local File (overwrite existing)", ""},
    {PF_USE_ORIGINAL, "USE_ORIGINAL", 0, "Use Original File", ""},
    {PF_WRITE_ORIGINAL, "WRITE_ORIGINAL", 0, "Write Original File (overwrite existing)", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 36 of file rna_packedfile.c.
Referenced by IMAGE_OT_unpack(), RNA_api_image(), and SOUND_OT_unpack().