Blender: outliner_select.c File Reference
outliner_select.c File Reference
outliner space
#include <stdlib.h>
#include "MEM_guardedalloc.h"
#include "DNA_armature_types.h"
#include "DNA_group_types.h"
#include "DNA_lamp_types.h"
#include "DNA_material_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_sequence_types.h"
#include "DNA_world_types.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_scene.h"
#include "BKE_sequencer.h"
#include "ED_armature.h"
#include "ED_object.h"
#include "ED_screen.h"
#include "ED_util.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_view2d.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "outliner_intern.h"
Functions
static int outliner_select (SpaceOops *soops, ListBase *lb, int *index, short *selecting)
static int tree_element_active_renderlayer (bContext *C, TreeElement *te, TreeStoreElem *tselem, int set)
static int tree_element_set_active_object (bContext *C, Scene *scene, SpaceOops *soops, TreeElement *te, int set)
static int tree_element_active_material (bContext *C, Scene *scene, SpaceOops *soops, TreeElement *te, int set)
static int tree_element_active_texture (bContext *C, Scene *scene, SpaceOops *soops, TreeElement *te, int set)
static int tree_element_active_lamp (bContext *UNUSED(C), Scene *scene, SpaceOops *soops, TreeElement *te, int set)
static int tree_element_active_camera (bContext *UNUSED(C), Scene *scene, SpaceOops *soops, TreeElement *te, int set)
static int tree_element_active_world (bContext *C, Scene *scene, SpaceOops *soops, TreeElement *te, int set)
static int tree_element_active_defgroup (bContext *C, Scene *scene, TreeElement *te, TreeStoreElem *tselem, int set)
static int tree_element_active_posegroup (bContext *C, Scene *scene, TreeElement *te, TreeStoreElem *tselem, int set)
static int tree_element_active_posechannel (bContext *C, Scene *scene, TreeElement *te, TreeStoreElem *tselem, int set)
static int tree_element_active_bone (bContext *C, Scene *scene, TreeElement *te, TreeStoreElem *tselem, int set)
static void tree_element_active_ebone__sel (bContext *C, Scene *scene, bArmature *arm, EditBone *ebone, short sel)
static int tree_element_active_ebone (bContext *C, Scene *scene, TreeElement *te, TreeStoreElem *UNUSED(tselem), int set)
static int tree_element_active_modifier (bContext *C, TreeElement *UNUSED(te), TreeStoreElem *tselem, int set)
static int tree_element_active_psys (bContext *C, Scene *UNUSED(scene), TreeElement *UNUSED(te), TreeStoreElem *tselem, int set)
static int tree_element_active_constraint (bContext *C, TreeElement *UNUSED(te), TreeStoreElem *tselem, int set)
static int tree_element_active_text (bContext *UNUSED(C), Scene *UNUSED(scene), SpaceOops *UNUSED(soops), TreeElement *UNUSED(te), int UNUSED(set))
static int tree_element_active_pose (bContext *C, Scene *scene, TreeElement *UNUSED(te), TreeStoreElem *tselem, int set)
static int tree_element_active_sequence (TreeElement *te, TreeStoreElem *UNUSED(tselem), int set)
static int tree_element_active_sequence_dup (Scene *scene, TreeElement *te, TreeStoreElem *UNUSED(tselem), int set)
static int tree_element_active_keymap_item (bContext *UNUSED(C), TreeElement *te, TreeStoreElem *UNUSED(tselem), int set)
int tree_element_active (bContext *C, Scene *scene, SpaceOops *soops, TreeElement *te, int set)
int tree_element_type_active (bContext *C, Scene *scene, SpaceOops *soops, TreeElement *te, TreeStoreElem *tselem, int set)
static int do_outliner_item_activate (bContext *C, Scene *scene, ARegion *ar, SpaceOops *soops, TreeElement *te, int extend, const float mval[2])
static int outliner_item_activate (bContext *C, wmOperator *op, wmEvent *event)
void OUTLINER_OT_item_activate (wmOperatorType *ot)
static void outliner_item_border_select (Scene *scene, SpaceOops *soops, rctf *rectf, TreeElement *te, int gesture_mode)
static int outliner_border_select_exec (bContext *C, wmOperator *op)
void OUTLINER_OT_select_border (wmOperatorType *ot)
Detailed Description
Definition in file outliner_select.c.
Function Documentation
static int do_outliner_item_activate (bContext * C, Scene * scene, ARegion * ar, SpaceOops * soops, TreeElement * te, int extend, const float mval[2]) [static]
Definition at line 693 of file outliner_select.c.
References BA_DESELECT, BA_SELECT, CTX_wm_screen(), ED_base_object_select(), ED_screen_set_scene(), ELEM5, ListBase::first, TreeStoreElem::flag, TreeElement::flag, Group::gobject, TreeStoreElem::id, ID_AR, ID_CU, ID_GR, ID_LT, ID_MB, ID_ME, ID_SCE, TreeElement::idcode, if(), NC_SCENE, ND_OB_SELECT, TreeElement::next, NULL, object_in_scene(), outliner_has_one_flag(), outliner_set_flag(), scene_deselect_all(), SELECT, TreeElement::subtree, TE_ICONROW, tree_element_active(), tree_element_set_active_object(), tree_element_type_active(), TREESTORE, TSE_CLOSED, TSE_SEQ_STRIP, TSE_SEQUENCE, TSE_SEQUENCE_DUP, TreeStoreElem::type, UI_UNIT_X, UI_UNIT_Y, WM_event_add_notifier(), WM_OP_INVOKE_REGION_WIN, WM_operator_name_call(), TreeElement::xend, TreeElement::xs, and TreeElement::ys.
Referenced by outliner_item_activate().
static int outliner_border_select_exec (bContext * C, wmOperator * op) [static]
Definition at line 870 of file outliner_select.c.
References CTX_data_scene(), CTX_wm_region(), CTX_wm_space_outliner(), ED_region_tag_redraw(), ListBase::first, NC_SCENE, ND_OB_SELECT, TreeElement::next, OPERATOR_FINISHED, outliner_item_border_select(), wmOperator::ptr, RNA_int_get(), SpaceOops::tree, UI_view2d_region_to_view(), ARegion::v2d, WM_event_add_notifier(), rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, rctf::ymax, rcti::ymax, rctf::ymin, and rcti::ymin.
Referenced by OUTLINER_OT_select_border().
static int outliner_item_activate (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 783 of file outliner_select.c.
References CTX_data_scene(), CTX_wm_region(), CTX_wm_space_outliner(), View2D::cur, do_outliner_item_activate(), ED_region_tag_redraw(), ED_undo_push(), ELEM3, ListBase::first, SpaceOops::flag, wmEvent::mval, TreeElement::next, NULL, OL_TOG_RESTRICT_VIEWX, OL_Y_OFFSET, OPERATOR_CANCELLED, OPERATOR_FINISHED, outliner_select(), SpaceOops::outlinevis, wmOperator::ptr, RNA_boolean_get(), SO_DATABLOCKS, SO_HIDE_RESTRICTCOLS, SO_KEYMAP, SO_TREESTORE_REDRAW, SO_USERDEF, SpaceOops::storeflag, SpaceOops::tree, UI_UNIT_Y, UI_view2d_listview_view_to_cell(), UI_view2d_region_to_view(), ARegion::v2d, and rctf::xmax.
Referenced by OUTLINER_OT_item_activate().
static void outliner_item_border_select (Scene * scene, SpaceOops * soops, rctf * rectf, TreeElement * te, int gesture_mode) [static]
Definition at line 848 of file outliner_select.c.
References ListBase::first, TreeStoreElem::flag, GESTURE_MODAL_SELECT, TreeElement::next, TreeElement::subtree, TREESTORE, TSE_CLOSED, TSE_SELECTED, UI_UNIT_Y, rctf::ymax, rctf::ymin, and TreeElement::ys.
Referenced by outliner_border_select_exec().
void OUTLINER_OT_item_activate (wmOperatorType * ot)
Definition at line 832 of file outliner_select.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_item_activate(), wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by outliner_operatortypes().
void OUTLINER_OT_select_border (wmOperatorType * ot)
Definition at line 898 of file outliner_select.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_border_select_exec(), wmOperatorType::poll, WM_border_select_cancel(), WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by outliner_operatortypes().
static int outliner_select (SpaceOops * soops, ListBase * lb, int * index, short * selecting) [static]
Definition at line 72 of file outliner_select.c.
References ListBase::first, TreeStoreElem::flag, TreeElement::flag, TreeElement::next, TreeElement::subtree, TE_ICONROW, TREESTORE, TSE_SELECTED, and TSELEM_OPEN.
Referenced by outliner_item_activate().
int tree_element_active (bContext * C, Scene * scene, SpaceOops * soops, TreeElement * te, int set)
Definition at line 629 of file outliner_select.c.
References ID_CA, ID_LA, ID_MA, ID_TE, ID_TXT, ID_WO, TreeElement::idcode, tree_element_active_camera(), tree_element_active_lamp(), tree_element_active_material(), tree_element_active_text(), tree_element_active_texture(), and tree_element_active_world().
Referenced by do_outliner_item_activate(), namebutton_cb(), outliner_draw_iconrow(), and outliner_draw_tree_element().
static int tree_element_active_bone (bContext * C, Scene * scene, TreeElement * te, TreeStoreElem * tselem, int set) [static]
Definition at line 427 of file outliner_select.c.
References bArmature::act_bone, BONE_HIDDEN_P, BONE_SELECTED, Object::data, TreeElement::directdata, ED_pose_deselectall(), TreeStoreElem::id, if(), NC_OBJECT, ND_BONE_ACTIVE, OBACT, and WM_event_add_notifier().
Referenced by tree_element_type_active().
static int tree_element_active_camera (bContext * UNUSEDC, Scene * scene, SpaceOops * soops, TreeElement * te, int set) [static]
Definition at line 318 of file outliner_select.c.
References Scene::camera, ID_OB, and outliner_search_back().
Referenced by tree_element_active().
static int tree_element_active_constraint (bContext * C, TreeElement * UNUSEDte, TreeStoreElem * tselem, int set) [static]
Definition at line 533 of file outliner_select.c.
References TreeStoreElem::id, NC_OBJECT, ND_CONSTRAINT, and WM_event_add_notifier().
Referenced by tree_element_type_active().
static int tree_element_active_defgroup (bContext * C, Scene * scene, TreeElement * te, TreeStoreElem * tselem, int set) [static]
Definition at line 357 of file outliner_select.c.
References Object::actdef, BLI_assert, DAG_id_tag_update(), Object::id, TreeStoreElem::id, if(), TreeElement::index, NC_OBJECT, ND_TRANSFORM, OB_RECALC_DATA, OBACT, and WM_event_add_notifier().
Referenced by tree_element_type_active().
static int tree_element_active_ebone (bContext * C, Scene * scene, TreeElement * te, TreeStoreElem * UNUSEDtselem, int set) [static]
Definition at line 476 of file outliner_select.c.
References BONE_HIDDEN_A, BONE_SELECTED, Object::data, TreeElement::directdata, ED_armature_deselect_all(), FALSE, EditBone::flag, Scene::obedit, tree_element_active_ebone__sel(), and TRUE.
Referenced by tree_element_type_active().
static void tree_element_active_ebone__sel (bContext * C, Scene * scene, bArmature * arm, EditBone * ebone, short sel) [static]
Definition at line 460 of file outliner_select.c.
References bArmature::act_edbone, BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, EditBone::flag, NC_OBJECT, ND_BONE_ACTIVE, Scene::obedit, EditBone::parent, and WM_event_add_notifier().
Referenced by tree_element_active_ebone().
static int tree_element_active_keymap_item (bContext * UNUSEDC, TreeElement * te, TreeStoreElem * UNUSEDtselem, int set) [static]
Definition at line 612 of file outliner_select.c.
References TreeElement::directdata, wmKeyMapItem::flag, and KMI_INACTIVE.
Referenced by tree_element_type_active().
static int tree_element_active_lamp (bContext * UNUSEDC, Scene * scene, SpaceOops * soops, TreeElement * te, int set) [static]
Definition at line 302 of file outliner_select.c.
References ID_OB, NULL, OBACT, and outliner_search_back().
Referenced by tree_element_active().
static int tree_element_active_material (bContext * C, Scene * scene, SpaceOops * soops, TreeElement * te, int set) [static]
Definition at line 189 of file outliner_select.c.
References Object::actcol, ID_OB, TreeElement::idcode, TreeElement::index, Object::matbits, NC_MATERIAL, ND_SHADING, NULL, OBACT, outliner_search_back(), TreeElement::parent, and WM_event_add_notifier().
Referenced by tree_element_active().
static int tree_element_active_modifier (bContext * C, TreeElement * UNUSEDte, TreeStoreElem * tselem, int set) [static]
Definition at line 507 of file outliner_select.c.
References TreeStoreElem::id, NC_OBJECT, ND_MODIFIER, and WM_event_add_notifier().
Referenced by tree_element_type_active().
static int tree_element_active_pose (bContext * C, Scene * scene, TreeElement * UNUSEDte, TreeStoreElem * tselem, int set) [static]
Definition at line 551 of file outliner_select.c.
References ED_armature_enter_posemode(), ED_armature_exit_posemode(), ED_object_exit_editmode(), EM_DO_UNDO, EM_FREEDATA, EM_FREEUNDO, EM_WAITCURSOR, TreeStoreElem::id, Object::mode, OB_MODE_POSE, Scene::obedit, and object_in_scene().
Referenced by tree_element_type_active().
static int tree_element_active_posechannel (bContext * C, Scene * scene, TreeElement * te, TreeStoreElem * tselem, int set) [static]
Definition at line 395 of file outliner_select.c.
References BONE_HIDDEN_P, BONE_SELECTED, Object::data, TreeElement::directdata, ED_pose_deselectall(), TreeStoreElem::id, if(), NC_OBJECT, ND_BONE_ACTIVE, OBACT, Object::pose, and WM_event_add_notifier().
Referenced by tree_element_type_active().
static int tree_element_active_posegroup (bContext * C, Scene * scene, TreeElement * te, TreeStoreElem * tselem, int set) [static]
Definition at line 377 of file outliner_select.c.
References bPose::active_group, TreeStoreElem::id, if(), TreeElement::index, NC_OBJECT, ND_DRAW, OBACT, Object::pose, and WM_event_add_notifier().
Referenced by tree_element_type_active().
static int tree_element_active_psys (bContext * C, Scene * UNUSEDscene, TreeElement * UNUSEDte, TreeStoreElem * tselem, int set) [static]
Definition at line 520 of file outliner_select.c.
References TreeStoreElem::id, NA_EDITED, NC_OBJECT, ND_PARTICLE, and WM_event_add_notifier().
Referenced by tree_element_type_active().
static int tree_element_active_renderlayer (bContext * C, TreeElement * te, TreeStoreElem * tselem, int set) [static]
Definition at line 122 of file outliner_select.c.
References RenderData::actlay, TreeStoreElem::id, ID_SCE, TreeElement::idcode, if(), NC_SCENE, ND_RENDER_OPTIONS, TreeStoreElem::nr, Scene::r, and WM_event_add_notifier().
Referenced by tree_element_type_active().
static int tree_element_active_sequence (TreeElement * te, TreeStoreElem * UNUSEDtselem, int set) [static]
Definition at line 571 of file outliner_select.c.
References TreeElement::directdata, Sequence::flag, if(), and SELECT.
Referenced by tree_element_type_active().
static int tree_element_active_sequence_dup (Scene * scene, TreeElement * te, TreeStoreElem * UNUSEDtselem, int set) [static]
Definition at line 585 of file outliner_select.c.
References TreeElement::directdata, FALSE, ListBase::first, Sequence::flag, if(), StripElem::name, Sequence::next, p, SELECT, seq_give_editing(), Editing::seqbasep, Sequence::strip, and Strip::stripdata.
Referenced by tree_element_type_active().
static int tree_element_active_text (bContext * UNUSEDC, Scene * UNUSEDscene, SpaceOops * UNUSEDsoops, TreeElement * UNUSEDte, int UNUSEDset) [static]
Definition at line 545 of file outliner_select.c.
Referenced by tree_element_active().
static int tree_element_active_texture (bContext * C, Scene * scene, SpaceOops * soops, TreeElement * te, int set) [static]
Definition at line 228 of file outliner_select.c.
References Object::actcol, Object::data, TreeElement::flag, TreeStoreElem::id, ID_LA, ID_MA, ID_WO, TreeElement::idcode, if(), TreeElement::index, NC_TEXTURE, NULL, OBACT, TreeElement::parent, TE_ACTIVE, World::texact, Lamp::texact, Material::texact, TREESTORE, WM_event_add_notifier(), and Scene::world.
Referenced by tree_element_active().
static int tree_element_active_world (bContext * C, Scene * scene, SpaceOops * soops, TreeElement * te, int set) [static]
Definition at line 328 of file outliner_select.c.
References CTX_wm_screen(), ED_screen_set_scene(), TreeStoreElem::id, NULL, TreeElement::parent, and TREESTORE.
Referenced by tree_element_active().
static int tree_element_set_active_object (bContext * C, Scene * scene, SpaceOops * soops, TreeElement * te, int set) [static]
Definition at line 141 of file outliner_select.c.
References TreeStoreElem::id, ID_OB, TreeElement::idcode, NULL, OBACT, outliner_search_back(), and TREESTORE.
Referenced by do_outliner_item_activate(), and tree_element_type_active().
int tree_element_type_active (bContext * C, Scene * scene, SpaceOops * soops, TreeElement * te, TreeStoreElem * tselem, int set)
Definition at line 653 of file outliner_select.c.
References TreeStoreElem::id, OBACT, tree_element_active_bone(), tree_element_active_constraint(), tree_element_active_defgroup(), tree_element_active_ebone(), tree_element_active_keymap_item(), tree_element_active_modifier(), tree_element_active_pose(), tree_element_active_posechannel(), tree_element_active_posegroup(), tree_element_active_psys(), tree_element_active_renderlayer(), tree_element_active_sequence(), tree_element_active_sequence_dup(), tree_element_set_active_object(), TSE_BONE, TSE_CONSTRAINT, TSE_DEFGROUP, TSE_EBONE, TSE_KEYMAP_ITEM, TSE_LINKED_OB, TSE_LINKED_PSYS, TSE_MODIFIER, TSE_POSE_BASE, TSE_POSE_CHANNEL, TSE_POSEGRP, TSE_R_LAYER, TSE_SEQUENCE, TSE_SEQUENCE_DUP, and TreeStoreElem::type.
Referenced by do_outliner_item_activate(), outliner_draw_iconrow(), and outliner_draw_tree_element().