Blender: sequencer_ops.c File Reference
sequencer_ops.c File Reference
sequencer
#include <stdlib.h>
#include <math.h>
#include "DNA_space_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_markers.h"
#include "ED_transform.h"
#include "sequencer_intern.h"
Functions
void sequencer_operatortypes (void)
void sequencer_keymap (wmKeyConfig *keyconf)
Detailed Description
Definition in file sequencer_ops.c.
Function Documentation
void sequencer_keymap (wmKeyConfig * keyconf)
Definition at line 119 of file sequencer_ops.c.
References AKEY, BKEY, CKEY, DELKEY, DKEY, ED_marker_keymap_animedit_conflictfree(), EIGHTKEY, FALSE, FIVEKEY, FOURKEY, GKEY, HKEY, HOMEKEY, i, IKEY, KKEY, KM_ALT, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTARROWKEY, LKEY, NINEKEY, NKEY, OKEY, ONEKEY, PAD1, PAD2, PAD4, PAD8, PADMINUS, PADPERIOD, PADPLUSKEY, PAGEDOWNKEY, PAGEUPKEY, wmKeyMapItem::ptr, RIGHTARROWKEY, RKEY, RNA_boolean_set(), RNA_enum_set(), RNA_float_set(), RNA_int_set(), RNA_string_set(), SEL_INVERT, SEL_TOGGLE, SELECTMOUSE, SEQ_CUT_HARD, SEQ_CUT_SOFT, SEQ_SIDE_LEFT, SEQ_SIDE_RIGHT, SEVENKEY, SIXKEY, SKEY, SPACE_SEQ, TABKEY, THREEKEY, transform_keymap_for_space(), TRUE, TWOKEY, VKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), XKEY, YKEY, and ZEROKEY.
Referenced by ED_spacetype_sequencer().
void sequencer_operatortypes (void)
Definition at line 55 of file sequencer_ops.c.
References SEQUENCER_OT_change_effect_input(), SEQUENCER_OT_change_effect_type(), SEQUENCER_OT_change_path(), SEQUENCER_OT_copy(), SEQUENCER_OT_cut(), SEQUENCER_OT_delete(), SEQUENCER_OT_duplicate(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_images_separate(), SEQUENCER_OT_lock(), SEQUENCER_OT_meta_make(), SEQUENCER_OT_meta_separate(), SEQUENCER_OT_meta_toggle(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_mute(), SEQUENCER_OT_next_edit(), SEQUENCER_OT_offset_clear(), SEQUENCER_OT_paste(), SEQUENCER_OT_previous_edit(), SEQUENCER_OT_properties(), SEQUENCER_OT_reassign_inputs(), SEQUENCER_OT_rebuild_proxy(), SEQUENCER_OT_refresh_all(), SEQUENCER_OT_reload(), SEQUENCER_OT_rendersize(), SEQUENCER_OT_scene_strip_add(), SEQUENCER_OT_select(), SEQUENCER_OT_select_active_side(), SEQUENCER_OT_select_all(), SEQUENCER_OT_select_border(), SEQUENCER_OT_select_grouped(), SEQUENCER_OT_select_handles(), SEQUENCER_OT_select_less(), SEQUENCER_OT_select_linked(), SEQUENCER_OT_select_linked_pick(), SEQUENCER_OT_select_more(), SEQUENCER_OT_snap(), SEQUENCER_OT_sound_strip_add(), SEQUENCER_OT_swap(), SEQUENCER_OT_swap_data(), SEQUENCER_OT_swap_inputs(), SEQUENCER_OT_unlock(), SEQUENCER_OT_unmute(), SEQUENCER_OT_view_all(), SEQUENCER_OT_view_all_preview(), SEQUENCER_OT_view_ghost_border(), SEQUENCER_OT_view_selected(), SEQUENCER_OT_view_toggle(), SEQUENCER_OT_view_zoom_ratio(), and WM_operatortype_append().
Referenced by ED_spacetype_sequencer().