Blender: btSoftBody::AJoint Struct Reference
btSoftBody::AJoint Struct Reference
#include <btSoftBody.h>
Classes
struct IControl
struct Specs
Public Member Functions
void Prepare (btScalar dt, int iterations)
void Solve (btScalar dt, btScalar sor)
void Terminate (btScalar dt)
eType::_ Type () const
Public Attributes
btVector3 m_axis [2]
IControl * m_icontrol
Detailed Description
Definition at line 521 of file btSoftBody.h.
Member Function Documentation
void btSoftBody::AJoint::Prepare (btScalar dt, int iterations) [virtual]
Reimplemented from btSoftBody::Joint.
Definition at line 2502 of file btSoftBody.cpp.
References AngularImpulseMatrix(), btAcos(), btCross(), btDot(), btMin(), NormalizeAny(), btSoftBody::Joint::Prepare(), and SIMD_PI.
void btSoftBody::AJoint::Solve (btScalar dt, btScalar sor) [virtual]
Implements btSoftBody::Joint.
Definition at line 2522 of file btSoftBody.cpp.
References btDot(), btSoftBody::Impulse::m_asVelocity, and btSoftBody::Impulse::m_velocity.
void btSoftBody::AJoint::Terminate (btScalar dt) [virtual]
Implements btSoftBody::Joint.
Definition at line 2537 of file btSoftBody.cpp.
eType::_ btSoftBody::AJoint::Type () const [inline, virtual]
Implements btSoftBody::Joint.
Definition at line 540 of file btSoftBody.h.
References btSoftBody::Joint::eType::Angular.
Member Data Documentation
btVector3 btSoftBody::AJoint::m_axis[2]
Definition at line 535 of file btSoftBody.h.
IControl* btSoftBody::AJoint::m_icontrol
Definition at line 536 of file btSoftBody.h.
Referenced by btSoftBody::appendAngularJoint().
The documentation for this struct was generated from the following files:
btSoftBody.h
btSoftBody.cpp