Blender: BLI_heap.h File Reference
BLI_heap.h File Reference
blenlib
A heap / priority queue ADT.
Typedefs
typedef struct Heap Heap
typedef struct HeapNode HeapNode
typedef void(* HeapFreeFP)(void *ptr)
Functions
Heap * BLI_heap_new (void)
void BLI_heap_free (Heap *heap, HeapFreeFP ptrfreefp)
HeapNode * BLI_heap_insert (Heap *heap, float value, void *ptr)
void BLI_heap_remove (Heap *heap, HeapNode *node)
int BLI_heap_empty (Heap *heap)
int BLI_heap_size (Heap *heap)
HeapNode * BLI_heap_top (Heap *heap)
void * BLI_heap_popmin (Heap *heap)
float BLI_heap_node_value (HeapNode *heap)
void * BLI_heap_node_ptr (HeapNode *heap)
Detailed Description
A heap / priority queue ADT.
Definition in file BLI_heap.h.
Typedef Documentation
typedef struct Heap Heap
Definition at line 38 of file BLI_heap.h.
typedef void(* HeapFreeFP)(void *ptr)
Definition at line 41 of file BLI_heap.h.
typedef struct HeapNode HeapNode
Definition at line 39 of file BLI_heap.h.
Function Documentation
int BLI_heap_empty (Heap * heap)
Definition at line 162 of file BLI_heap.c.
References Heap::size.
Referenced by bmo_vertexshortestpath_exec(), and edgetag_shortest_path().
void BLI_heap_free (Heap * heap, HeapFreeFP ptrfreefp)
Definition at line 80 of file BLI_heap.c.
References Heap::arena, BLI_memarena_free(), i, MEM_freeN(), HeapNode::ptr, Heap::size, and Heap::tree.
Referenced by bmo_vertexshortestpath_exec(), edge_find_shortest_path(), edgetag_shortest_path(), and p_chart_fill_boundary().
HeapNode* BLI_heap_insert (Heap * heap, float value, void * ptr)
Definition at line 126 of file BLI_heap.c.
References Heap::arena, BLI_heap_up(), BLI_memarena_alloc(), Heap::bufsize, Heap::freenodes, HeapNode::index, MEM_freeN(), MEM_mallocN(), HeapNode::ptr, Heap::size, Heap::tree, and HeapNode::value.
Referenced by bmo_vertexshortestpath_exec(), edge_find_shortest_path(), edgetag_add_adjacent(), edgetag_shortest_path(), and p_chart_fill_boundary().
Heap* BLI_heap_new (void)
Definition at line 70 of file BLI_heap.c.
References Heap::arena, BLI_memarena_new(), Heap::bufsize, MEM_callocN(), MEM_mallocN(), and Heap::tree.
Referenced by bmo_vertexshortestpath_exec(), edge_find_shortest_path(), edgetag_shortest_path(), and p_chart_fill_boundary().
void* BLI_heap_node_ptr (HeapNode * heap)
Definition at line 215 of file BLI_heap.c.
References HeapNode::ptr.
float BLI_heap_node_value (HeapNode * heap)
Definition at line 210 of file BLI_heap.c.
References HeapNode::value.
void* BLI_heap_popmin (Heap * heap)
Definition at line 177 of file BLI_heap.c.
References BLI_heap_down(), Heap::freenodes, HEAP_SWAP, HeapNode::ptr, Heap::size, and Heap::tree.
Referenced by BLI_heap_remove(), bmo_vertexshortestpath_exec(), edge_find_shortest_path(), edgetag_shortest_path(), and p_chart_fill_boundary().
void BLI_heap_remove (Heap * heap, HeapNode * node)
Definition at line 196 of file BLI_heap.c.
References BLI_heap_popmin(), HEAP_PARENT, HEAP_SWAP, i, HeapNode::index, and p.
Referenced by bmo_vertexshortestpath_exec(), and p_chart_fill_boundary().
int BLI_heap_size (Heap * heap)
Definition at line 167 of file BLI_heap.c.
References Heap::size.
Referenced by edge_find_shortest_path().
HeapNode* BLI_heap_top (Heap * heap)
Definition at line 172 of file BLI_heap.c.
References Heap::tree.