Blender: rna_texture.c File Reference
rna_texture.c File Reference
RNA
#include <float.h>
#include <stdio.h>
#include <stdlib.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_brush_types.h"
#include "DNA_lamp_types.h"
#include "DNA_material_types.h"
#include "DNA_object_types.h"
#include "DNA_texture_types.h"
#include "DNA_world_types.h"
#include "DNA_node_types.h"
#include "DNA_particle_types.h"
#include "DNA_scene_types.h"
#include "BKE_node.h"
Functions
static void rna_def_texmapping (BlenderRNA *brna)
static void rna_def_colormapping (BlenderRNA *brna)
static void rna_def_mtex (BlenderRNA *brna)
static void rna_def_filter_common (StructRNA *srna)
static void rna_def_environment_map (BlenderRNA *brna)
static void rna_def_texture_clouds (BlenderRNA *brna)
static void rna_def_texture_wood (BlenderRNA *brna)
static void rna_def_texture_marble (BlenderRNA *brna)
static void rna_def_texture_magic (BlenderRNA *brna)
static void rna_def_texture_blend (BlenderRNA *brna)
static void rna_def_texture_stucci (BlenderRNA *brna)
static void rna_def_texture_noise (BlenderRNA *brna)
static void rna_def_texture_image (BlenderRNA *brna)
static void rna_def_texture_plugin (BlenderRNA *brna)
static void rna_def_texture_environment_map (BlenderRNA *brna)
static void rna_def_texture_musgrave (BlenderRNA *brna)
static void rna_def_texture_voronoi (BlenderRNA *brna)
static void rna_def_texture_distorted_noise (BlenderRNA *brna)
static void rna_def_texture_pointdensity (BlenderRNA *brna)
static void rna_def_texture_voxeldata (BlenderRNA *brna)
static void rna_def_texture_ocean (BlenderRNA *brna)
static void rna_def_texture (BlenderRNA *brna)
void RNA_def_texture (BlenderRNA *brna)
Variables
EnumPropertyItem texture_filter_items []
EnumPropertyItem texture_type_items []
EnumPropertyItem blend_type_items []
static EnumPropertyItem prop_noise_basis_items []
static EnumPropertyItem prop_noise_type []
Detailed Description
Definition in file rna_texture.c.
Function Documentation
static void rna_def_colormapping (BlenderRNA * brna) [static]
Definition at line 532 of file rna_texture.c.
References COLORMAP_USE_RAMP, NULL, PROP_BOOLEAN, PROP_COLOR, PROP_ENUM, PROP_FLOAT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_texture().
static void rna_def_environment_map (BlenderRNA * brna) [static]
Definition at line 717 of file rna_texture.c.
References ENV_ANIM, ENV_CUBE, ENV_LOAD, ENV_PLANE, ENV_STATIC, FLT_MAX, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_LAYER_MEMBER, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, RNA_api_environment_map(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_texture().
static void rna_def_filter_common (StructRNA * srna) [static]
Definition at line 667 of file rna_texture.c.
References NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), TEX_FILTER_MIN, TEX_GAUSS_MIP, and TEX_MIPMAP.
Referenced by rna_def_texture_environment_map(), and rna_def_texture_image().
static void rna_def_mtex (BlenderRNA * brna) [static]
Definition at line 582 of file rna_texture.c.
References MTEX_NEGATIVE, MTEX_RGBTOINT, MTEX_STENCIL, NULL, PROP_BOOLEAN, PROP_COLOR, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_TRANSLATION, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and RNA_TRANSLATION_PREC_DEFAULT.
Referenced by RNA_def_texture().
static void rna_def_texmapping (BlenderRNA * brna) [static]
Definition at line 449 of file rna_texture.c.
References FLT_MAX, MTEX_CUBE, MTEX_FLAT, MTEX_SPHERE, MTEX_TUBE, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_EULER, PROP_FLOAT, PROP_NONE, PROP_TRANSLATION, PROP_XYZ, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_text(), RNA_TRANSLATION_PREC_DEFAULT, TEXMAP_CLIP_MAX, and TEXMAP_CLIP_MIN.
Referenced by RNA_def_texture().
void RNA_def_texture (BlenderRNA * brna)
Definition at line 2029 of file rna_texture.c.
References rna_def_colormapping(), rna_def_environment_map(), rna_def_mtex(), rna_def_texmapping(), and rna_def_texture().
static void rna_def_texture (BlenderRNA * brna) [static]
Definition at line 1921 of file rna_texture.c.
References NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_api_texture(), rna_def_animdata_common(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), rna_def_texture_blend(), rna_def_texture_clouds(), rna_def_texture_distorted_noise(), rna_def_texture_environment_map(), rna_def_texture_image(), rna_def_texture_magic(), rna_def_texture_marble(), rna_def_texture_musgrave(), rna_def_texture_noise(), rna_def_texture_ocean(), rna_def_texture_plugin(), rna_def_texture_pointdensity(), rna_def_texture_stucci(), rna_def_texture_voronoi(), rna_def_texture_voxeldata(), rna_def_texture_wood(), TEX_COLORBAND, and TEX_PRV_ALPHA.
Referenced by RNA_def_texture().
static void rna_def_texture_blend (BlenderRNA * brna) [static]
Definition at line 1050 of file rna_texture.c.
References NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TEX_DIAG, TEX_EASE, TEX_FLIPBLEND, TEX_HALO, TEX_LIN, TEX_QUAD, TEX_RAD, and TEX_SPHERE.
Referenced by rna_def_texture().
static void rna_def_texture_clouds (BlenderRNA * brna) [static]
Definition at line 831 of file rna_texture.c.
References FLT_MAX, NULL, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TEX_COLOR, and TEX_DEFAULT.
Referenced by rna_def_texture().
static void rna_def_texture_distorted_noise (BlenderRNA * brna) [static]
Definition at line 1525 of file rna_texture.c.
References FLT_MAX, NULL, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_texture().
static void rna_def_texture_environment_map (BlenderRNA * brna) [static]
Definition at line 1316 of file rna_texture.c.
References NULL, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, rna_def_filter_common(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_texture().
static void rna_def_texture_image (BlenderRNA * brna) [static]
Definition at line 1146 of file rna_texture.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, rna_def_filter_common(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TEX_CALCALPHA, TEX_CHECKER, TEX_CHECKER_EVEN, TEX_CHECKER_ODD, TEX_CLIP, TEX_CLIPCUBE, TEX_DERIVATIVEMAP, TEX_EXTEND, TEX_IMAROT, TEX_INTERPOL, TEX_NEGALPHA, TEX_NORMALMAP, TEX_REPEAT, TEX_REPEAT_XMIR, TEX_REPEAT_YMIR, and TEX_USEALPHA.
Referenced by rna_def_texture().
static void rna_def_texture_magic (BlenderRNA * brna) [static]
Definition at line 1026 of file rna_texture.c.
References FLT_MAX, NULL, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_texture().
static void rna_def_texture_marble (BlenderRNA * brna) [static]
Definition at line 952 of file rna_texture.c.
References FLT_MAX, NULL, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TEX_SAW, TEX_SHARP, TEX_SHARPER, TEX_SIN, TEX_SOFT, and TEX_TRI.
Referenced by rna_def_texture().
static void rna_def_texture_musgrave (BlenderRNA * brna) [static]
Definition at line 1347 of file rna_texture.c.
References FLT_MAX, NULL, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TEX_FBM, TEX_HTERRAIN, TEX_HYBRIDMF, TEX_MFRACTAL, and TEX_RIDGEDMF.
Referenced by rna_def_texture().
static void rna_def_texture_noise (BlenderRNA * brna) [static]
Definition at line 1137 of file rna_texture.c.
References RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_texture().
static void rna_def_texture_ocean (BlenderRNA * brna) [static]
Definition at line 1878 of file rna_texture.c.
References NULL, PROP_ANIMATABLE, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TEX_OCN_DISPLACEMENT, TEX_OCN_EMINUS, TEX_OCN_EPLUS, TEX_OCN_FOAM, and TEX_OCN_JPLUS.
Referenced by rna_def_texture().
static void rna_def_texture_plugin (BlenderRNA * brna) [static]
Definition at line 1305 of file rna_texture.c.
References RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_texture().
static void rna_def_texture_pointdensity (BlenderRNA * brna) [static]
Definition at line 1566 of file rna_texture.c.
References FLT_MAX, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TEX_PD_COLOR_CONSTANT, TEX_PD_COLOR_PARTAGE, TEX_PD_COLOR_PARTSPEED, TEX_PD_COLOR_PARTVEL, TEX_PD_FALLOFF_CONSTANT, TEX_PD_FALLOFF_CURVE, TEX_PD_FALLOFF_PARTICLE_AGE, TEX_PD_FALLOFF_PARTICLE_VEL, TEX_PD_FALLOFF_ROOT, TEX_PD_FALLOFF_SMOOTH, TEX_PD_FALLOFF_SOFT, TEX_PD_FALLOFF_STD, TEX_PD_NOISE_AGE, TEX_PD_NOISE_STATIC, TEX_PD_NOISE_TIME, TEX_PD_NOISE_VEL, TEX_PD_OBJECT, TEX_PD_OBJECTLOC, TEX_PD_OBJECTSPACE, TEX_PD_PSYS, TEX_PD_TURBULENCE, and TEX_PD_WORLDSPACE.
Referenced by rna_def_texture().
static void rna_def_texture_stucci (BlenderRNA * brna) [static]
Definition at line 1089 of file rna_texture.c.
References FLT_MAX, NULL, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TEX_PLASTIC, TEX_WALLIN, and TEX_WALLOUT.
Referenced by rna_def_texture().
static void rna_def_texture_voronoi (BlenderRNA * brna) [static]
Definition at line 1428 of file rna_texture.c.
References FLT_MAX, NULL, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TEX_CHEBYCHEV, TEX_COL1, TEX_COL2, TEX_COL3, TEX_DISTANCE, TEX_DISTANCE_SQUARED, TEX_INTENSITY, TEX_MANHATTAN, TEX_MINKOVSKY, TEX_MINKOVSKY_FOUR, and TEX_MINKOVSKY_HALF.
Referenced by rna_def_texture().
static void rna_def_texture_voxeldata (BlenderRNA * brna) [static]
Definition at line 1754 of file rna_texture.c.
References FLT_MAX, MAXFRAME, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FILEPATH, PROP_FLOAT, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TEX_CLIP, TEX_EXTEND, TEX_REPEAT, TEX_VD_BLENDERVOXEL, TEX_VD_IMAGE_SEQUENCE, TEX_VD_LINEAR, TEX_VD_NEARESTNEIGHBOR, TEX_VD_QUADRATIC, TEX_VD_RAW_8BIT, TEX_VD_SMOKE, TEX_VD_SMOKEDENSITY, TEX_VD_SMOKEHEAT, TEX_VD_SMOKEVEL, TEX_VD_STILL, TEX_VD_TRICUBIC_BSPLINE, and TEX_VD_TRICUBIC_CATROM.
Referenced by rna_def_texture().
static void rna_def_texture_wood (BlenderRNA * brna) [static]
Definition at line 884 of file rna_texture.c.
References FLT_MAX, NULL, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TEX_BAND, TEX_BANDNOISE, TEX_RING, TEX_RINGNOISE, TEX_SAW, TEX_SIN, and TEX_TRI.
Referenced by rna_def_texture().
Variable Documentation
EnumPropertyItem blend_type_items[]
Initial value:
 {
    {MTEX_BLEND, "MIX", 0, "Mix", ""},
    {MTEX_ADD, "ADD", 0, "Add", ""},
    {MTEX_SUB, "SUBTRACT", 0, "Subtract", ""},
    {MTEX_MUL, "MULTIPLY", 0, "Multiply", ""},
    {MTEX_SCREEN, "SCREEN", 0, "Screen", ""},
    {MTEX_OVERLAY, "OVERLAY", 0, "Overlay", ""},
    {MTEX_DIFF, "DIFFERENCE", 0, "Difference", ""},
    {MTEX_DIV, "DIVIDE", 0, "Divide", ""},
    {MTEX_DARK, "DARKEN", 0, "Darken", ""},
    {MTEX_LIGHT, "LIGHTEN", 0, "Lighten", ""},
    {MTEX_BLEND_HUE, "HUE", 0, "Hue", ""},
    {MTEX_BLEND_SAT, "SATURATION", 0, "Saturation", ""},
    {MTEX_BLEND_VAL, "VALUE", 0, "Value", ""},
    {MTEX_BLEND_COLOR, "COLOR", 0, "Color", ""},
    {MTEX_SOFT_LIGHT, "SOFT_LIGHT", 0, "Soft Light", ""},
    {MTEX_LIN_LIGHT    , "LINEAR_LIGHT", 0, "Linear Light", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 79 of file rna_texture.c.
EnumPropertyItem prop_noise_basis_items[] [static]
Initial value:
 {
    {TEX_BLENDER, "BLENDER_ORIGINAL", 0, "Blender Original",
                  "Noise algorithm - Blender original: Smooth interpolated noise"},
    {TEX_STDPERLIN, "ORIGINAL_PERLIN", 0, "Original Perlin",
                    "Noise algorithm - Original Perlin: Smooth interpolated noise"},
    {TEX_NEWPERLIN, "IMPROVED_PERLIN", 0, "Improved Perlin",
                    "Noise algorithm - Improved Perlin: Smooth interpolated noise"},
    {TEX_VORONOI_F1, "VORONOI_F1", 0, "Voronoi F1",
                     "Noise algorithm - Voronoi F1: Returns distance to the closest feature point"},
    {TEX_VORONOI_F2, "VORONOI_F2", 0, "Voronoi F2",
                     "Noise algorithm - Voronoi F2: Returns distance to the 2nd closest feature point"},
    {TEX_VORONOI_F3, "VORONOI_F3", 0, "Voronoi F3",
                     "Noise algorithm - Voronoi F3: Returns distance to the 3rd closest feature point"},
    {TEX_VORONOI_F4, "VORONOI_F4", 0, "Voronoi F4",
                     "Noise algorithm - Voronoi F4: Returns distance to the 4th closest feature point"},
    {TEX_VORONOI_F2F1, "VORONOI_F2_F1", 0, "Voronoi F2-F1", "Noise algorithm - Voronoi F1-F2"},
    {TEX_VORONOI_CRACKLE, "VORONOI_CRACKLE", 0, "Voronoi Crackle",
                          "Noise algorithm - Voronoi Crackle: Voronoi tessellation with sharp edges"},
    {TEX_CELLNOISE, "CELL_NOISE", 0, "Cell Noise",
                    "Noise algorithm - Cell Noise: Square cell tessellation"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 803 of file rna_texture.c.
EnumPropertyItem prop_noise_type[] [static]
Initial value:
 {
    {TEX_NOISESOFT, "SOFT_NOISE", 0, "Soft", "Generate soft noise (smooth transitions)"},
    {TEX_NOISEPERL, "HARD_NOISE", 0, "Hard", "Generate hard noise (sharp transitions)"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 825 of file rna_texture.c.
EnumPropertyItem texture_filter_items[]
Initial value:
 {
    {TXF_BOX, "BOX", 0, "Box", ""},
    {TXF_EWA, "EWA", 0, "EWA", ""},
    {TXF_FELINE, "FELINE", 0, "FELINE", ""},
    {TXF_AREA, "AREA", 0, "Area", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 49 of file rna_texture.c.
EnumPropertyItem texture_type_items[]
Initial value:
 {
    {0, "NONE", 0, "None", ""},
    {TEX_BLEND, "BLEND", ICON_TEXTURE, "Blend", "Procedural - create a ramp texture"},
    {TEX_CLOUDS, "CLOUDS", ICON_TEXTURE, "Clouds", "Procedural - create a cloud-like fractal noise texture"},
    {TEX_DISTNOISE, "DISTORTED_NOISE", ICON_TEXTURE,
                    "Distorted Noise", "Procedural - noise texture distorted by two noise algorithms"},
    {TEX_ENVMAP, "ENVIRONMENT_MAP", ICON_IMAGE_DATA,
                 "Environment Map", "Create a render of the environment mapped to a texture"},
    {TEX_IMAGE, "IMAGE", ICON_IMAGE_DATA, "Image or Movie", "Allow for images or movies to be used as textures"},
    {TEX_MAGIC, "MAGIC", ICON_TEXTURE, "Magic", "Procedural - color texture based on trigonometric functions"},
    {TEX_MARBLE, "MARBLE", ICON_TEXTURE, "Marble", "Procedural - marble-like noise texture with wave generated bands"},
    {TEX_MUSGRAVE, "MUSGRAVE", ICON_TEXTURE, "Musgrave", "Procedural - highly flexible fractal noise texture"},
    {TEX_NOISE, "NOISE", ICON_TEXTURE, "Noise",
                "Procedural - random noise, gives a different result every time, for every frame, for every pixel"},
    {TEX_POINTDENSITY, "POINT_DENSITY", ICON_TEXTURE, "Point Density", ""},
    {TEX_STUCCI, "STUCCI", ICON_TEXTURE, "Stucci", "Procedural - create a fractal noise texture"},
    {TEX_VORONOI, "VORONOI", ICON_TEXTURE, "Voronoi", "Procedural - create cell-like patterns based on Worley noise"},
    {TEX_VOXELDATA, "VOXEL_DATA", ICON_TEXTURE, "Voxel Data", "Create a 3d texture based on volumetric data"},
    {TEX_WOOD, "WOOD", ICON_TEXTURE, "Wood", "Procedural - wave generated bands or rings, with optional noise"},
    {TEX_OCEAN, "OCEAN", ICON_TEXTURE, "Ocean", "Use a texture generated by an Ocean modifier"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 56 of file rna_texture.c.
Referenced by RNA_def_main_textures(), and rna_def_space_node().