Blender: CocoaAppDelegate Class Reference
CocoaAppDelegate Class Reference
Public Member Functions
(void) - setSystemCocoa:
(BOOL) - application:openFile:
(NSApplicationTerminateReply) - applicationShouldTerminate:
(void) - applicationWillTerminate:
(void) - applicationWillBecomeActive:
Protected Attributes
GHOST_SystemCocoa * systemCocoa
Detailed Description
CocoaAppDelegate ObjC object to capture applicationShouldTerminate, and send quit event
Definition at line 494 of file GHOST_SystemCocoa.mm.
Member Function Documentation
- (BOOL) application: (NSApplication *) theApplication openFile: (NSString *) filename
Definition at line 510 of file GHOST_SystemCocoa.mm.
References GHOST_SystemCocoa::handleOpenDocumentRequest(), and systemCocoa.
- (NSApplicationTerminateReply) applicationShouldTerminate: (NSApplication *) sender
Definition at line 515 of file GHOST_SystemCocoa.mm.
References GHOST_kExitNow, GHOST_SystemCocoa::handleQuitRequest(), and systemCocoa.
- (void) applicationWillBecomeActive: (NSNotification *) aNotification
Definition at line 534 of file GHOST_SystemCocoa.mm.
References GHOST_SystemCocoa::handleApplicationBecomeActiveEvent(), and systemCocoa.
- (void) applicationWillTerminate: (NSNotification *) aNotification
Definition at line 528 of file GHOST_SystemCocoa.mm.
- (void) setSystemCocoa: (GHOST_SystemCocoa *) sysCocoa
Referenced by GHOST_SystemCocoa::init().
Member Data Documentation
- (GHOST_SystemCocoa*) systemCocoa [protected]
Definition at line 495 of file GHOST_SystemCocoa.mm.
Referenced by application:openFile:, applicationShouldTerminate:, and applicationWillBecomeActive:.
The documentation for this class was generated from the following file:
GHOST_SystemCocoa.mm