Blender: mathutils_Matrix.h File Reference
mathutils_Matrix.h File Reference
Python Mathutils
Classes
struct MatrixObject
Defines
#define MatrixObject_Check(_v) PyObject_TypeCheck((_v), &matrix_Type)
#define MATRIX_MAX_DIM 4
#define MATRIX_ITEM_ASSERT(_mat, _row, _col) (void)0
#define MATRIX_ITEM_INDEX(_mat, _row, _col) (MATRIX_ITEM_ASSERT(_mat, _row, _col),(((_mat)->num_row * (_col)) + (_row)))
#define MATRIX_ITEM_PTR(_mat, _row, _col) ((_mat)->matrix + MATRIX_ITEM_INDEX(_mat, _row, _col))
#define MATRIX_ITEM(_mat, _row, _col) ((_mat)->matrix [MATRIX_ITEM_INDEX(_mat, _row, _col)])
#define MATRIX_COL_INDEX(_mat, _col) (MATRIX_ITEM_INDEX(_mat, 0, _col))
#define MATRIX_COL_PTR(_mat, _col) ((_mat)->matrix + MATRIX_COL_INDEX(_mat, _col))
Functions
PyObject * Matrix_CreatePyObject (float *mat, const unsigned short num_col, const unsigned short num_row, int type, PyTypeObject *base_type)
PyObject * Matrix_CreatePyObject_cb (PyObject *user, const unsigned short num_col, const unsigned short num_row, unsigned char cb_type, unsigned char cb_subtype)
void matrix_as_3x3 (float mat[3][3], MatrixObject *self)
Variables
PyTypeObject matrix_Type
PyTypeObject matrix_access_Type
unsigned char mathutils_matrix_row_cb_index
unsigned char mathutils_matrix_col_cb_index
unsigned char mathutils_matrix_translation_cb_index
struct Mathutils_Callback mathutils_matrix_row_cb
struct Mathutils_Callback mathutils_matrix_col_cb
struct Mathutils_Callback mathutils_matrix_translation_cb
Detailed Description
Definition in file mathutils_Matrix.h.
Define Documentation
#define MATRIX_COL_INDEX (_mat, _col) (MATRIX_ITEM_INDEX(_mat, 0, _col))
Definition at line 54 of file mathutils_Matrix.h.
#define MATRIX_COL_PTR (_mat, _col) ((_mat)->matrix + MATRIX_COL_INDEX(_mat, _col))
Definition at line 55 of file mathutils_Matrix.h.
Referenced by matrix_as_3x3(), Matrix_resize_4x4(), and Matrix_to_translation().
#define MATRIX_ITEM (_mat, _row, _col) ((_mat)->matrix [MATRIX_ITEM_INDEX(_mat, _row, _col)])
Definition at line 52 of file mathutils_Matrix.h.
Referenced by column_vector_multiplication(), mathutils_matrix_col_get(), mathutils_matrix_col_get_index(), mathutils_matrix_col_set(), mathutils_matrix_col_set_index(), mathutils_matrix_row_get(), mathutils_matrix_row_get_index(), mathutils_matrix_row_set(), mathutils_matrix_row_set_index(), mathutils_matrix_translation_get(), mathutils_matrix_translation_get_index(), mathutils_matrix_translation_set(), mathutils_matrix_translation_set_index(), Matrix_ass_item_col(), Matrix_ass_item_row(), matrix_determinant_internal(), Matrix_identity(), Matrix_invert(), Matrix_mul(), Matrix_repr(), Matrix_str(), Matrix_transpose(), and row_vector_multiplication().
#define MATRIX_ITEM_ASSERT (_mat, _row, _col) (void)0
Definition at line 47 of file mathutils_Matrix.h.
#define MATRIX_ITEM_INDEX (_mat, _row, _col) (MATRIX_ITEM_ASSERT(_mat, _row, _col),(((_mat)->num_row * (_col)) + (_row)))
Definition at line 50 of file mathutils_Matrix.h.
#define MATRIX_ITEM_PTR (_mat, _row, _col) ((_mat)->matrix + MATRIX_ITEM_INDEX(_mat, _row, _col))
Definition at line 51 of file mathutils_Matrix.h.
#define MATRIX_MAX_DIM 4
Definition at line 40 of file mathutils_Matrix.h.
Referenced by Matrix_lerp(), Matrix_repr(), Matrix_str(), and MatrixAccess_iter().
#define MatrixObject_Check (_v) PyObject_TypeCheck((_v), &matrix_Type)
Definition at line 39 of file mathutils_Matrix.h.
Referenced by copy_values(), mathutils_any_to_rotmat(), Matrix_add(), Matrix_mul(), Matrix_richcmpr(), Matrix_sub(), validate_array(), Vector_imul(), and Vector_mul().
Function Documentation
void matrix_as_3x3 (float mat[3][3], MatrixObject * self)
Definition at line 877 of file mathutils_Matrix.c.
References copy_v3_v3(), and MATRIX_COL_PTR.
Referenced by mathutils_any_to_rotmat(), Matrix_median_scale_get(), Matrix_rotate(), Matrix_to_3x3(), and Matrix_to_scale().
PyObject* Matrix_CreatePyObject (float * mat, const unsigned short num_col, const unsigned short num_row, int type, PyTypeObject * base_type)
Definition at line 2370 of file mathutils_Matrix.c.
References Matrix_identity(), NULL, Py_NEW, and Py_WRAP.
Referenced by C_Matrix_Identity(), C_Matrix_OrthoProjection(), C_Matrix_Rotation(), C_Matrix_Scale(), C_Matrix_Shear(), C_Matrix_Translation(), Euler_to_matrix(), Matrix_add(), Matrix_copy(), Matrix_CreatePyObject_cb(), Matrix_lerp(), Matrix_mul(), matrix_mul_float(), Matrix_new(), Matrix_sub(), Matrix_to_3x3(), Matrix_to_4x4(), pyrna_math_object_from_array(), pyrna_param_to_py(), and Quaternion_to_matrix().
PyObject* Matrix_CreatePyObject_cb (PyObject * user, const unsigned short num_col, const unsigned short num_row, unsigned char cb_type, unsigned char cb_subtype)
Definition at line 2430 of file mathutils_Matrix.c.
References Matrix_CreatePyObject(), and Py_NEW.
Referenced by pyrna_math_object_from_array().
Variable Documentation
struct Mathutils_Callback mathutils_matrix_col_cb
Definition at line 245 of file mathutils_Matrix.c.
Referenced by PyInit_mathutils().
unsigned char mathutils_matrix_col_cb_index
Definition at line 166 of file mathutils_Matrix.c.
Referenced by Matrix_item_col(), and PyInit_mathutils().
struct Mathutils_Callback mathutils_matrix_row_cb
Definition at line 153 of file mathutils_Matrix.c.
Referenced by PyInit_mathutils().
unsigned char mathutils_matrix_row_cb_index
Definition at line 82 of file mathutils_Matrix.c.
Referenced by Matrix_item_row(), Matrix_slice(), and PyInit_mathutils().
struct Mathutils_Callback mathutils_matrix_translation_cb
Definition at line 322 of file mathutils_Matrix.c.
Referenced by PyInit_mathutils().
unsigned char mathutils_matrix_translation_cb_index
Definition at line 259 of file mathutils_Matrix.c.
Referenced by Matrix_translation_get(), and PyInit_mathutils().
PyTypeObject matrix_access_Type
Definition at line 2617 of file mathutils_Matrix.c.
Referenced by PyInit_mathutils().
PyTypeObject matrix_Type
Definition at line 2317 of file mathutils_Matrix.c.
Referenced by bpy_bmesh_transform(), Matrix_lerp(), and PyInit_mathutils().