Blender: mathutils_Euler.h File Reference
mathutils_Euler.h File Reference
Python Mathutils
Classes
struct EulerObject
Defines
#define EulerObject_Check(_v) PyObject_TypeCheck((_v), &euler_Type)
Functions
PyObject * Euler_CreatePyObject (float *eul, short order, int type, PyTypeObject *base_type)
PyObject * Euler_CreatePyObject_cb (PyObject *cb_user, short order, unsigned char cb_type, unsigned char cb_subtype)
short euler_order_from_string (const char *str, const char *error_prefix)
Variables
PyTypeObject euler_Type
Detailed Description
Definition in file mathutils_Euler.h.
Define Documentation
#define EulerObject_Check (_v) PyObject_TypeCheck((_v), &euler_Type)
Definition at line 39 of file mathutils_Euler.h.
Referenced by Euler_richcmpr(), mathutils_any_to_rotmat(), mathutils_array_parse(), and mathutils_array_parse_alloc().
Function Documentation
PyObject* Euler_CreatePyObject (float * eul, short order, int type, PyTypeObject * base_type)
Definition at line 705 of file mathutils_Euler.c.
References copy_v3_v3(), EULER_SIZE, NULL, Py_NEW, Py_WRAP, and zero_v3().
Referenced by Euler_copy(), Euler_CreatePyObject_cb(), Euler_new(), Matrix_to_euler(), pyrna_math_object_from_array(), and Quaternion_to_euler().
PyObject* Euler_CreatePyObject_cb (PyObject * cb_user, short order, unsigned char cb_type, unsigned char cb_subtype)
Definition at line 742 of file mathutils_Euler.c.
References Euler_CreatePyObject(), and Py_NEW.
Referenced by pyrna_math_object_from_array().
short euler_order_from_string (const char * str, const char * error_prefix)
Definition at line 85 of file mathutils_Euler.c.
References EULER_ORDER_XYZ, EULER_ORDER_XZY, EULER_ORDER_YXZ, EULER_ORDER_YZX, EULER_ORDER_ZXY, and EULER_ORDER_ZYX.
Referenced by Euler_new(), Euler_order_set(), Matrix_to_euler(), and Quaternion_to_euler().
Variable Documentation
PyTypeObject euler_Type
Definition at line 651 of file mathutils_Euler.c.
Referenced by Matrix_to_euler(), PyInit_mathutils(), and Quaternion_to_euler().