Blender: wm_operators.c File Reference
wm_operators.c File Reference
windowmanager
#include <float.h>
#include <string.h>
#include <ctype.h>
#include <stdio.h>
#include <stddef.h>
#include <assert.h>
#include "GHOST_C-api.h"
#include "MEM_guardedalloc.h"
#include "DNA_ID.h"
#include "DNA_object_types.h"
#include "DNA_screen_types.h"
#include "DNA_scene_types.h"
#include "DNA_userdef_types.h"
#include "DNA_windowmanager_types.h"
#include "DNA_mesh_types.h"
#include "BLF_translation.h"
#include "PIL_time.h"
#include "BLI_blenlib.h"
#include "BLI_dynstr.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BLI_ghash.h"
#include "BLO_readfile.h"
#include "BKE_blender.h"
#include "BKE_brush.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_idprop.h"
#include "BKE_image.h"
#include "BKE_library.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "BKE_screen.h"
#include "BKE_idcode.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "BLF_api.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "ED_screen.h"
#include "ED_util.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "WM_api.h"
#include "WM_types.h"
#include "wm.h"
#include "wm_draw.h"
#include "wm_event_system.h"
#include "wm_event_types.h"
#include "wm_subwindow.h"
#include "wm_window.h"
Classes
struct MacroData
struct wmOpPopUp
struct RadialControl
Typedefs
typedef struct wmOpPopUp wmOpPopUp
Enumerations
enum RCPropFlags { RC_PROP_ALLOW_MISSING = 1, RC_PROP_REQUIRE_FLOAT = 2, RC_PROP_REQUIRE_BOOL = 4 }
Functions
wmOperatorType * WM_operatortype_find (const char *idname, int quiet)
GHashIterator * WM_operatortype_iter (void)
void WM_operatortype_append (void(*opfunc)(wmOperatorType *))
void WM_operatortype_append_ptr (void(*opfunc)(wmOperatorType *, void *), void *userdata)
static void wm_macro_start (wmOperator *op)
static int wm_macro_end (wmOperator *op, int retval)
static int wm_macro_exec (bContext *C, wmOperator *op)
static int wm_macro_invoke_internal (bContext *C, wmOperator *op, wmEvent *event, wmOperator *opm)
static int wm_macro_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int wm_macro_modal (bContext *C, wmOperator *op, wmEvent *event)
static int wm_macro_cancel (bContext *C, wmOperator *op)
wmOperatorType * WM_operatortype_append_macro (const char *idname, const char *name, int flag)
void WM_operatortype_append_macro_ptr (void(*opfunc)(wmOperatorType *, void *), void *userdata)
wmOperatorTypeMacro * WM_operatortype_macro_define (wmOperatorType *ot, const char *idname)
static void wm_operatortype_free_macro (wmOperatorType *ot)
int WM_operatortype_remove (const char *idname)
void WM_operator_py_idname (char *to, const char *from)
void WM_operator_bl_idname (char *to, const char *from)
char * WM_operator_pystring (bContext *C, wmOperatorType *ot, PointerRNA *opptr, int all_args)
void WM_operator_properties_create_ptr (PointerRNA *ptr, wmOperatorType *ot)
void WM_operator_properties_create (PointerRNA *ptr, const char *opstring)
void WM_operator_properties_alloc (PointerRNA **ptr, IDProperty **properties, const char *opstring)
void WM_operator_properties_sanitize (PointerRNA *ptr, const short no_context)
void WM_operator_properties_reset (wmOperator *op)
void WM_operator_properties_free (PointerRNA *ptr)
int WM_menu_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static void operator_enum_search_cb (const struct bContext *C, void *arg_ot, const char *str, uiSearchItems *items)
static void operator_enum_call_cb (struct bContext *C, void *arg1, void *arg2)
static uiBlock * wm_enum_search_menu (bContext *C, ARegion *ar, void *arg_op)
int WM_enum_search_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
int WM_operator_confirm_message (bContext *C, wmOperator *op, const char *message)
int WM_operator_confirm (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
int WM_operator_filesel (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
int WM_operator_filesel_ensure_ext_imtype (wmOperator *op, const char imtype)
void WM_operator_properties_filesel (wmOperatorType *ot, int filter, short type, short action, short flag, short display)
void WM_operator_properties_select_all (wmOperatorType *ot)
void WM_operator_properties_gesture_border (wmOperatorType *ot, int extend)
void WM_operator_properties_gesture_straightline (wmOperatorType *ot, int cursor)
int WM_operator_winactive (bContext *C)
int WM_operator_check_ui_enabled (const bContext *C, const char *idname)
wmOperator * WM_operator_last_redo (const bContext *C)
static uiBlock * wm_block_create_redo (bContext *C, ARegion *ar, void *arg_op)
static void dialog_exec_cb (bContext *C, void *arg1, void *arg2)
static void dialog_check_cb (bContext *C, void *op_ptr, void *UNUSED(arg))
static uiBlock * wm_block_dialog_create (bContext *C, ARegion *ar, void *userData)
static uiBlock * wm_operator_ui_create (bContext *C, ARegion *ar, void *userData)
static void wm_operator_ui_popup_cancel (void *userData)
static void wm_operator_ui_popup_ok (struct bContext *C, void *arg, int retval)
int WM_operator_ui_popup (bContext *C, wmOperator *op, int width, int height)
int WM_operator_props_popup (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
int WM_operator_props_dialog_popup (bContext *C, wmOperator *op, int width, int height)
int WM_operator_redo_popup (bContext *C, wmOperator *op)
static int wm_debug_menu_exec (bContext *C, wmOperator *op)
static int wm_debug_menu_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static void WM_OT_debug_menu (wmOperatorType *ot)
static void wm_block_splash_close (bContext *C, void *arg_block, void *UNUSED(arg))
static uiBlock * wm_block_create_splash (bContext *C, ARegion *ar, void *arg_unused)
static void wm_block_splash_refreshmenu (bContext *UNUSED(C), void *UNUSED(arg_block), void *UNUSED(arg))
static int wm_resource_check_prev (void)
static uiBlock * wm_block_create_splash (bContext *C, ARegion *ar, void *UNUSED(arg))
static int wm_splash_invoke (bContext *C, wmOperator *UNUSED(op), wmEvent *UNUSED(event))
static void WM_OT_splash (wmOperatorType *ot)
static void operator_call_cb (struct bContext *C, void *UNUSED(arg1), void *arg2)
static void operator_search_cb (const struct bContext *C, void *UNUSED(arg), const char *str, uiSearchItems *items)
static uiBlock * wm_block_search_menu (bContext *C, ARegion *ar, void *UNUSED(arg_op))
static int wm_search_menu_exec (bContext *UNUSED(C), wmOperator *UNUSED(op))
static int wm_search_menu_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int wm_search_menu_poll (bContext *C)
static void WM_OT_search_menu (wmOperatorType *ot)
static int wm_call_menu_exec (bContext *C, wmOperator *op)
static void WM_OT_call_menu (wmOperatorType *ot)
static int wm_operator_winactive_normal (bContext *C)
static void WM_OT_window_duplicate (wmOperatorType *ot)
static void WM_OT_save_homefile (wmOperatorType *ot)
static void WM_OT_read_homefile (wmOperatorType *ot)
static void WM_OT_read_factory_settings (wmOperatorType *ot)
static void open_set_load_ui (wmOperator *op)
static void open_set_use_scripts (wmOperator *op)
static int wm_open_mainfile_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int wm_open_mainfile_exec (bContext *C, wmOperator *op)
static void WM_OT_open_mainfile (wmOperatorType *ot)
int wm_link_append_poll (bContext *C)
static int wm_link_append_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static short wm_link_append_flag (wmOperator *op)
static int wm_link_append_exec (bContext *C, wmOperator *op)
static void WM_OT_link_append (wmOperatorType *ot)
static int wm_recover_last_session_exec (bContext *C, wmOperator *op)
static void WM_OT_recover_last_session (wmOperatorType *ot)
static int wm_recover_auto_save_exec (bContext *C, wmOperator *op)
static int wm_recover_auto_save_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static void WM_OT_recover_auto_save (wmOperatorType *ot)
static void untitled (char *name)
static void save_set_compress (wmOperator *op)
static int wm_save_as_mainfile_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int wm_save_as_mainfile_exec (bContext *C, wmOperator *op)
static int blend_save_check (bContext *UNUSED(C), wmOperator *op)
static void WM_OT_save_as_mainfile (wmOperatorType *ot)
static int wm_save_mainfile_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static void WM_OT_save_mainfile (wmOperatorType *ot)
static void WM_OT_window_fullscreen_toggle (wmOperatorType *ot)
static int wm_exit_blender_op (bContext *C, wmOperator *op)
static void WM_OT_quit_blender (wmOperatorType *ot)
void * WM_paint_cursor_activate (wmWindowManager *wm, int(*poll)(bContext *C), wmPaintCursorDraw draw, void *customdata)
void WM_paint_cursor_end (wmWindowManager *wm, void *handle)
static int border_apply_rect (wmOperator *op)
static int border_apply (bContext *C, wmOperator *op, int gesture_mode)
static void wm_gesture_end (bContext *C, wmOperator *op)
int WM_border_select_invoke (bContext *C, wmOperator *op, wmEvent *event)
int WM_border_select_modal (bContext *C, wmOperator *op, wmEvent *event)
int WM_border_select_cancel (bContext *C, wmOperator *op)
int WM_gesture_circle_invoke (bContext *C, wmOperator *op, wmEvent *event)
static void gesture_circle_apply (bContext *C, wmOperator *op)
int WM_gesture_circle_modal (bContext *C, wmOperator *op, wmEvent *event)
int WM_gesture_circle_cancel (bContext *C, wmOperator *op)
static void tweak_gesture_modal (bContext *C, wmEvent *event)
void wm_tweakevent_test (bContext *C, wmEvent *event, int action)
int WM_gesture_lasso_invoke (bContext *C, wmOperator *op, wmEvent *event)
int WM_gesture_lines_invoke (bContext *C, wmOperator *op, wmEvent *event)
static void gesture_lasso_apply (bContext *C, wmOperator *op)
int WM_gesture_lasso_modal (bContext *C, wmOperator *op, wmEvent *event)
int WM_gesture_lines_modal (bContext *C, wmOperator *op, wmEvent *event)
int WM_gesture_lasso_cancel (bContext *C, wmOperator *op)
int WM_gesture_lines_cancel (bContext *C, wmOperator *op)
static int straightline_apply (bContext *C, wmOperator *op)
int WM_gesture_straightline_invoke (bContext *C, wmOperator *op, wmEvent *event)
int WM_gesture_straightline_modal (bContext *C, wmOperator *op, wmEvent *event)
int WM_gesture_straightline_cancel (bContext *C, wmOperator *op)
static void radial_control_set_initial_mouse (RadialControl *rc, wmEvent *event)
static void radial_control_set_tex (RadialControl *rc)
static void radial_control_paint_tex (RadialControl *rc, float radius, float alpha)
static void radial_control_paint_cursor (bContext *C, int x, int y, void *customdata)
static int radial_control_get_path (PointerRNA *ctx_ptr, wmOperator *op, const char *name, PointerRNA *r_ptr, PropertyRNA **r_prop, int req_length, RCPropFlags flags)
static int radial_control_get_properties (bContext *C, wmOperator *op)
static int radial_control_invoke (bContext *C, wmOperator *op, wmEvent *event)
static void radial_control_set_value (RadialControl *rc, float val)
static int radial_control_cancel (bContext *C, wmOperator *op)
static int radial_control_modal (bContext *C, wmOperator *op, wmEvent *event)
static void WM_OT_radial_control (wmOperatorType *ot)
static void redraw_timer_window_swap (bContext *C)
static int redraw_timer_exec (bContext *C, wmOperator *op)
static void WM_OT_redraw_timer (wmOperatorType *ot)
static int memory_statistics_exec (bContext *UNUSED(C), wmOperator *UNUSED(op))
static void WM_OT_memory_statistics (wmOperatorType *ot)
static int dependency_relations_exec (bContext *C, wmOperator *UNUSED(op))
static void WM_OT_dependency_relations (wmOperatorType *ot)
static int wm_ndof_sensitivity_exec (bContext *UNUSED(C), wmOperator *op)
static void WM_OT_ndof_sensitivity_change (wmOperatorType *ot)
static void operatortype_ghash_free_cb (wmOperatorType *ot)
void wm_operatortype_free (void)
void wm_operatortype_init (void)
static void gesture_circle_modal_keymap (wmKeyConfig *keyconf)
static void gesture_straightline_modal_keymap (wmKeyConfig *keyconf)
static void gesture_border_modal_keymap (wmKeyConfig *keyconf)
static void gesture_zoom_border_modal_keymap (wmKeyConfig *keyconf)
void wm_window_keymap (wmKeyConfig *keyconf)
static EnumPropertyItem * rna_id_itemf (bContext *UNUSED(C), PointerRNA *UNUSED(ptr), int *do_free, ID *id, int local)
EnumPropertyItem * RNA_action_itemf (bContext *C, PointerRNA *ptr, PropertyRNA *UNUSED(prop), int *do_free)
EnumPropertyItem * RNA_group_itemf (bContext *C, PointerRNA *ptr, PropertyRNA *UNUSED(prop), int *do_free)
EnumPropertyItem * RNA_group_local_itemf (bContext *C, PointerRNA *ptr, PropertyRNA *UNUSED(prop), int *do_free)
EnumPropertyItem * RNA_image_itemf (bContext *C, PointerRNA *ptr, PropertyRNA *UNUSED(prop), int *do_free)
EnumPropertyItem * RNA_image_local_itemf (bContext *C, PointerRNA *ptr, PropertyRNA *UNUSED(prop), int *do_free)
EnumPropertyItem * RNA_scene_itemf (bContext *C, PointerRNA *ptr, PropertyRNA *UNUSED(prop), int *do_free)
EnumPropertyItem * RNA_scene_local_itemf (bContext *C, PointerRNA *ptr, PropertyRNA *UNUSED(prop), int *do_free)
EnumPropertyItem * RNA_movieclip_itemf (bContext *C, PointerRNA *ptr, PropertyRNA *UNUSED(prop), int *do_free)
EnumPropertyItem * RNA_movieclip_local_itemf (bContext *C, PointerRNA *ptr, PropertyRNA *UNUSED(prop), int *do_free)
Variables
static GHash * global_ops_hash = NULL
static const int WM_RADIAL_CONTROL_DISPLAY_SIZE = 200
static EnumPropertyItem redraw_timer_type_items []
Detailed Description
Definition in file wm_operators.c.
Typedef Documentation
typedef struct wmOpPopUp wmOpPopUp
Enumeration Type Documentation
enum RCPropFlags
Enumerator:
RC_PROP_ALLOW_MISSING
RC_PROP_REQUIRE_FLOAT
RC_PROP_REQUIRE_BOOL
Definition at line 3108 of file wm_operators.c.
Function Documentation
static int blend_save_check (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 2026 of file wm_operators.c.
References BLI_ensure_extension(), BLO_has_bfile_extension(), FALSE, FILE_MAX, RecentFile::filepath, wmOperator::ptr, RNA_string_get(), RNA_string_set(), and TRUE.
Referenced by WM_OT_save_as_mainfile(), and WM_OT_save_mainfile().
static int border_apply (bContext * C, wmOperator * op, int gesture_mode) [static]
Definition at line 2337 of file wm_operators.c.
References border_apply_rect(), wmOperatorType::exec, wmOperator::ptr, RNA_int_set(), RNA_struct_find_property(), and wmOperator::type.
Referenced by WM_border_select_modal().
static int border_apply_rect (wmOperator * op) [static]
Definition at line 2319 of file wm_operators.c.
References wmGesture::customdata, wmOperator::customdata, MAX2, MIN2, wmOperator::ptr, RNA_int_set(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by border_apply(), and WM_border_select_modal().
static int dependency_relations_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3588 of file wm_operators.c.
References CTX_data_active_object(), CTX_data_main(), CTX_data_scene(), DAG_print_dependencies(), and OPERATOR_FINISHED.
Referenced by WM_OT_dependency_relations().
static void dialog_check_cb (bContext * C, void * op_ptr, void * UNUSEDarg) [static]
Definition at line 1023 of file wm_operators.c.
References wmOperatorType::check, and wmOperator::type.
Referenced by wm_block_dialog_create().
static void dialog_exec_cb (bContext * C, void * arg1, void * arg2) [static]
Definition at line 1006 of file wm_operators.c.
References data, MEM_freeN(), wmOpPopUp::op, uiPupBlockClose(), and WM_operator_call().
Referenced by wm_block_dialog_create().
static void gesture_border_modal_keymap (wmKeyConfig * keyconf) [static]
Definition at line 3795 of file wm_operators.c.
References ESCKEY, GESTURE_MODAL_BEGIN, GESTURE_MODAL_CANCEL, GESTURE_MODAL_DESELECT, GESTURE_MODAL_SELECT, KM_ANY, KM_PRESS, KM_RELEASE, KM_SHIFT, LEFTMOUSE, MIDDLEMOUSE, wmKeyMap::modal_items, NULL, RIGHTMOUSE, WM_modalkeymap_add(), WM_modalkeymap_add_item(), WM_modalkeymap_assign(), and WM_modalkeymap_get().
Referenced by wm_window_keymap().
static void gesture_circle_apply (bContext * C, wmOperator * op) [static]
Definition at line 2459 of file wm_operators.c.
References wmGesture::customdata, wmOperator::customdata, wmOperatorType::exec, GESTURE_MODAL_NOP, wmOperator::ptr, RNA_int_get(), RNA_int_set(), wmOperator::type, rcti::xmax, rcti::xmin, and rcti::ymin.
Referenced by WM_gesture_circle_modal().
static void gesture_circle_modal_keymap (wmKeyConfig * keyconf) [static]
Definition at line 3714 of file wm_operators.c.
References ESCKEY, GESTURE_MODAL_CANCEL, GESTURE_MODAL_CIRCLE_ADD, GESTURE_MODAL_CIRCLE_SUB, GESTURE_MODAL_CONFIRM, GESTURE_MODAL_DESELECT, GESTURE_MODAL_NOP, GESTURE_MODAL_SELECT, KM_ANY, KM_PRESS, KM_RELEASE, KM_SHIFT, LEFTMOUSE, MIDDLEMOUSE, wmKeyMap::modal_items, NULL, PADENTER, PADMINUS, PADPLUSKEY, RETKEY, RIGHTMOUSE, WHEELDOWNMOUSE, WHEELUPMOUSE, WM_modalkeymap_add(), WM_modalkeymap_add_item(), WM_modalkeymap_assign(), and WM_modalkeymap_get().
Referenced by wm_window_keymap().
static void gesture_lasso_apply (bContext * C, wmOperator * op) [static]
Definition at line 2673 of file wm_operators.c.
References wmGesture::customdata, wmOperator::customdata, wmOperatorType::exec, i, wmGesture::points, wmOperator::ptr, RNA_collection_add(), RNA_collection_clear(), RNA_float_set_array(), wmOperator::type, and wm_gesture_end().
Referenced by WM_gesture_lasso_modal().
static void gesture_straightline_modal_keymap (wmKeyConfig * keyconf) [static]
Definition at line 3767 of file wm_operators.c.
References ESCKEY, GESTURE_MODAL_BEGIN, GESTURE_MODAL_CANCEL, GESTURE_MODAL_SELECT, KM_ANY, KM_PRESS, KM_RELEASE, LEFTMOUSE, wmKeyMap::modal_items, NULL, RIGHTMOUSE, WM_modalkeymap_add(), WM_modalkeymap_add_item(), WM_modalkeymap_assign(), and WM_modalkeymap_get().
Referenced by wm_window_keymap().
static void gesture_zoom_border_modal_keymap (wmKeyConfig * keyconf) [static]
Definition at line 3854 of file wm_operators.c.
References ESCKEY, GESTURE_MODAL_BEGIN, GESTURE_MODAL_CANCEL, GESTURE_MODAL_IN, GESTURE_MODAL_OUT, KM_ANY, KM_PRESS, KM_RELEASE, LEFTMOUSE, MIDDLEMOUSE, wmKeyMap::modal_items, NULL, RIGHTMOUSE, WM_modalkeymap_add(), WM_modalkeymap_add_item(), WM_modalkeymap_assign(), and WM_modalkeymap_get().
Referenced by wm_window_keymap().
static int memory_statistics_exec (bContext * UNUSEDC, wmOperator * UNUSEDop) [static]
Definition at line 3571 of file wm_operators.c.
References MEM_printmemlist_stats(), and OPERATOR_FINISHED.
Referenced by WM_OT_memory_statistics().
static void open_set_load_ui (wmOperator * op) [static]
Definition at line 1575 of file wm_operators.c.
References wmOperator::ptr, RNA_boolean_set(), RNA_struct_property_is_set(), and USER_FILENOUI.
Referenced by wm_open_mainfile_exec(), and wm_open_mainfile_invoke().
static void open_set_use_scripts (wmOperator * op) [static]
Definition at line 1581 of file wm_operators.c.
References G, G_SCRIPT_AUTOEXEC, wmOperator::ptr, RNA_boolean_set(), and RNA_struct_property_is_set().
Referenced by wm_open_mainfile_exec(), and wm_open_mainfile_invoke().
static void operator_call_cb (struct bContext * C, void * UNUSEDarg1, void * arg2) [static]
Definition at line 1378 of file wm_operators.c.
References wmOperatorType::idname, NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by wm_block_search_menu().
static void operator_enum_call_cb (struct bContext * C, void * arg1, void * arg2) [static]
Definition at line 715 of file wm_operators.c.
References GET_INT_FROM_POINTER, wmOperatorType::idname, wmOperatorType::prop, RNA_property_enum_set(), WM_OP_EXEC_DEFAULT, WM_operator_name_call(), WM_operator_properties_create_ptr(), and WM_operator_properties_free().
Referenced by wm_enum_search_menu().
static void operator_enum_search_cb (const struct bContext * C, void * arg_ot, const char * str, uiSearchItems * items) [static]
Definition at line 681 of file wm_operators.c.
References BLI_strcasestr(), EnumPropertyItem::identifier, wmOperatorType::idname, MEM_freeN(), EnumPropertyItem::name, NULL, wmOperatorType::prop, PROP_ENUM, RNA_pointer_create(), RNA_property_enum_items(), RNA_property_identifier(), RNA_property_type(), SET_INT_IN_POINTER, wmOperatorType::srna, uiSearchItemAdd(), and EnumPropertyItem::value.
Referenced by wm_enum_search_menu().
static void operator_search_cb (const struct bContext * C, void * UNUSEDarg, const char * str, uiSearchItems * items) [static]
Definition at line 1386 of file wm_operators.c.
References BLI_ghashIterator_free(), BLI_ghashIterator_getValue(), BLI_ghashIterator_isDone(), BLI_ghashIterator_step(), BLI_strcasestr(), BLI_strncpy(), wmOperatorType::flag, G, G_DEBUG_WM, wmOperatorType::idname, len(), wmOperatorType::name, NULL, OPTYPE_INTERNAL, strlen(), TRUE, uiSearchItemAdd(), WM_key_event_operator_string(), WM_OP_EXEC_DEFAULT, WM_operator_poll(), and WM_operatortype_iter().
Referenced by wm_block_search_menu().
static void operatortype_ghash_free_cb (wmOperatorType * ot) [static]
Definition at line 3652 of file wm_operators.c.
References wmOperatorType::ext, ListBase::first, wmOperatorType::idname, IDP_FreeProperty(), wmOperatorType::last_properties, wmOperatorType::macro, MEM_freeN(), ExtensionRNA::srna, and wm_operatortype_free_macro().
Referenced by wm_operatortype_free().
static int radial_control_cancel (bContext * C, wmOperator * op) [static]
Definition at line 3319 of file wm_operators.c.
References CTX_wm_manager(), RadialControl::cursor, wmOperator::customdata, RadialControl::gltex, MEM_freeN(), NC_WINDOW, NULL, OPERATOR_CANCELLED, RadialControl::orig_paintcursors, wmWindowManager::paintcursors, WM_event_add_notifier(), and WM_paint_cursor_end().
Referenced by radial_control_modal(), and WM_OT_radial_control().
static int radial_control_get_path (PointerRNA * ctx_ptr, wmOperator * op, const char * name, PointerRNA * r_ptr, PropertyRNA ** r_prop, int req_length, RCPropFlags flags) [static]
Definition at line 3117 of file wm_operators.c.
References BKE_reportf(), len(), MEM_freeN(), NULL, PROP_BOOLEAN, PROP_FLOAT, wmOperator::ptr, RC_PROP_ALLOW_MISSING, RC_PROP_REQUIRE_BOOL, RC_PROP_REQUIRE_FLOAT, wmOperator::reports, RNA_path_resolve(), RNA_property_array_length(), RNA_property_type(), RNA_string_get_alloc(), RPT_ERROR, and str.
Referenced by radial_control_get_properties().
static int radial_control_get_properties (bContext * C, wmOperator * op) [static]
Definition at line 3183 of file wm_operators.c.
References BKE_report(), RadialControl::col_prop, RadialControl::col_ptr, wmOperator::customdata, PointerRNA::data, RadialControl::fill_col_prop, RadialControl::fill_col_ptr, RadialControl::image_id_ptr, NULL, RadialControl::prop, RadialControl::ptr, radial_control_get_path(), RC_PROP_ALLOW_MISSING, RC_PROP_REQUIRE_BOOL, RC_PROP_REQUIRE_FLOAT, wmOperator::reports, RNA_Context, RNA_pointer_create(), RNA_property_boolean_get(), RNA_struct_is_ID(), RadialControl::rot_prop, RadialControl::rot_ptr, RPT_ERROR, PointerRNA::type, RadialControl::zoom_prop, and RadialControl::zoom_ptr.
Referenced by radial_control_invoke().
static int radial_control_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 3244 of file wm_operators.c.
References BKE_report(), CTX_wm_manager(), RadialControl::current_value, RadialControl::cursor, wmOperator::customdata, ELEM3, ListBase::first, RadialControl::initial_value, ListBase::last, RadialControl::max_value, MEM_callocN(), MEM_freeN(), RadialControl::min_value, NULL, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, RadialControl::orig_paintcursors, wmWindowManager::paintcursors, wmOperatorType::poll, RadialControl::prop, PROP_ANGLE, PROP_DISTANCE, PROP_FACTOR, PROP_FLOAT, PROP_INT, RadialControl::ptr, radial_control_get_properties(), radial_control_paint_cursor(), radial_control_set_initial_mouse(), radial_control_set_tex(), wmOperator::reports, RNA_property_float_get(), RNA_property_float_ui_range(), RNA_property_int_get(), RNA_property_int_ui_range(), RNA_property_subtype(), RNA_property_type(), RPT_ERROR, RadialControl::subtype, wmOperator::type, RadialControl::type, WM_event_add_modal_handler(), and WM_paint_cursor_activate().
Referenced by WM_OT_radial_control().
static int radial_control_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 3341 of file wm_operators.c.
References KDL::atan2(), CLAMP(), CTX_wm_region(), RadialControl::current_value, wmOperator::customdata, DEG2RADF, ED_region_tag_redraw(), ESCKEY, RadialControl::initial_mouse, RadialControl::initial_value, LEFTMOUSE, M_PI, RadialControl::max_value, RadialControl::min_value, MOUSEMOVE, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, PADENTER, PROP_ANGLE, PROP_DISTANCE, PROP_FACTOR, RAD2DEGF, radial_control_cancel(), radial_control_set_value(), RIGHTMOUSE, RNA_property_float_get_array(), sqrt(), RadialControl::subtype, wmEvent::type, WM_RADIAL_CONTROL_DISPLAY_SIZE, RadialControl::zoom_prop, and RadialControl::zoom_ptr.
Referenced by WM_OT_radial_control().
static void radial_control_paint_cursor (bContext * C, int x, int y, void * customdata) [static]
Definition at line 3038 of file wm_operators.c.
References RadialControl::col_prop, RadialControl::col_ptr, CTX_wm_region(), RadialControl::current_value, fdrawline(), glutil_draw_lined_arc(), RadialControl::initial_mouse, RadialControl::initial_value, M_PI, PROP_ANGLE, PROP_DISTANCE, PROP_FACTOR, RAD2DEGF, radial_control_paint_tex(), RNA_property_float_get_array(), RadialControl::subtype, ARegion::winrct, WM_RADIAL_CONTROL_DISPLAY_SIZE, rcti::xmin, rcti::ymin, RadialControl::zoom_prop, and RadialControl::zoom_ptr.
Referenced by radial_control_invoke().
static void radial_control_paint_tex (RadialControl * rc, float radius, float alpha) [static]
Definition at line 2991 of file wm_operators.c.
References RadialControl::fill_col_prop, RadialControl::fill_col_ptr, RadialControl::gltex, glutil_draw_filled_arc(), M_PI, RAD2DEGF, RNA_property_float_get(), RNA_property_float_get_array(), rot, RadialControl::rot_prop, and RadialControl::rot_ptr.
Referenced by radial_control_paint_cursor().
static void radial_control_set_initial_mouse (RadialControl * rc, wmEvent * event) [static]
Definition at line 2938 of file wm_operators.c.
References cos(), RadialControl::initial_mouse, RadialControl::initial_value, PROP_ANGLE, PROP_DISTANCE, PROP_FACTOR, RNA_property_float_get_array(), sin(), RadialControl::subtype, RadialControl::zoom_prop, and RadialControl::zoom_ptr.
Referenced by radial_control_invoke().
static void radial_control_set_tex (RadialControl * rc) [static]
Definition at line 2971 of file wm_operators.c.
References brush_gen_radial_control_imbuf(), PointerRNA::data, RadialControl::gltex, ID_BR, RadialControl::image_id_ptr, MEM_freeN(), ImBuf::rect_float, RNA_type_to_ID_code(), PointerRNA::type, ImBuf::x, and ImBuf::y.
Referenced by radial_control_invoke().
static void radial_control_set_value (RadialControl * rc, float val) [static]
Definition at line 3305 of file wm_operators.c.
References RadialControl::prop, PROP_FLOAT, PROP_INT, RadialControl::ptr, RNA_property_float_set(), RNA_property_int_set(), and RadialControl::type.
Referenced by radial_control_modal().
static int redraw_timer_exec (bContext * C, wmOperator * op) [static]
Definition at line 3460 of file wm_operators.c.
References BKE_reportf(), RenderData::cfra, CTX_data_main(), CTX_data_scene(), CTX_wm_area(), CTX_wm_area_set(), CTX_wm_region(), CTX_wm_region_set(), CTX_wm_screen(), CTX_wm_window(), CTX_wm_window_set(), ED_region_do_draw(), ED_region_tag_redraw(), ED_undo_pop(), ED_undo_redo(), RenderData::efra, ListBase::first, Scene::lay, ARegion::next, ScrArea::next, OPERATOR_FINISHED, PIL_check_seconds_timer(), wmOperator::ptr, Scene::r, redraw_timer_window_swap(), ScrArea::regionbase, wmOperator::reports, RNA_enum_description(), RNA_enum_get(), RNA_int_get(), RPT_WARNING, scene_update_for_newframe(), RenderData::sfra, ARegion::swinid, WM_cursor_wait(), and wm_draw_update().
Referenced by WM_OT_redraw_timer().
static void redraw_timer_window_swap (bContext * C) [static]
Definition at line 3437 of file wm_operators.c.
References CTX_wm_screen(), CTX_wm_window(), CTX_wm_window_set(), ED_area_tag_redraw(), ScrArea::next, and wm_draw_update().
Referenced by redraw_timer_exec().
EnumPropertyItem* RNA_action_itemf (bContext * C, PointerRNA * ptr, PropertyRNA * UNUSEDprop, int * do_free)
Definition at line 4019 of file wm_operators.c.
References CTX_data_main(), FALSE, NULL, and rna_id_itemf().
EnumPropertyItem* RNA_group_itemf (bContext * C, PointerRNA * ptr, PropertyRNA * UNUSEDprop, int * do_free)
Definition at line 4030 of file wm_operators.c.
References CTX_data_main(), FALSE, NULL, and rna_id_itemf().
EnumPropertyItem* RNA_group_local_itemf (bContext * C, PointerRNA * ptr, PropertyRNA * UNUSEDprop, int * do_free)
Definition at line 4034 of file wm_operators.c.
References CTX_data_main(), NULL, rna_id_itemf(), and TRUE.
static EnumPropertyItem* rna_id_itemf (bContext * UNUSEDC, PointerRNA * UNUSEDptr, int * do_free, ID * id, int local) [static]
Definition at line 3998 of file wm_operators.c.
References FALSE, i, EnumPropertyItem::identifier, ID::lib, EnumPropertyItem::name, ID::next, NULL, RNA_enum_item_add(), RNA_enum_item_end(), and EnumPropertyItem::value.
Referenced by RNA_action_itemf(), RNA_group_itemf(), RNA_group_local_itemf(), RNA_image_itemf(), RNA_image_local_itemf(), RNA_movieclip_itemf(), RNA_movieclip_local_itemf(), RNA_scene_itemf(), and RNA_scene_local_itemf().
EnumPropertyItem* RNA_image_itemf (bContext * C, PointerRNA * ptr, PropertyRNA * UNUSEDprop, int * do_free)
Definition at line 4039 of file wm_operators.c.
References CTX_data_main(), FALSE, NULL, and rna_id_itemf().
EnumPropertyItem* RNA_image_local_itemf (bContext * C, PointerRNA * ptr, PropertyRNA * UNUSEDprop, int * do_free)
Definition at line 4043 of file wm_operators.c.
References CTX_data_main(), NULL, rna_id_itemf(), and TRUE.
EnumPropertyItem* RNA_movieclip_itemf (bContext * C, PointerRNA * ptr, PropertyRNA * UNUSEDprop, int * do_free)
Definition at line 4057 of file wm_operators.c.
References CTX_data_main(), FALSE, NULL, and rna_id_itemf().
EnumPropertyItem* RNA_movieclip_local_itemf (bContext * C, PointerRNA * ptr, PropertyRNA * UNUSEDprop, int * do_free)
Definition at line 4061 of file wm_operators.c.
References CTX_data_main(), NULL, rna_id_itemf(), and TRUE.
EnumPropertyItem* RNA_scene_itemf (bContext * C, PointerRNA * ptr, PropertyRNA * UNUSEDprop, int * do_free)
Definition at line 4048 of file wm_operators.c.
References CTX_data_main(), FALSE, NULL, and rna_id_itemf().
EnumPropertyItem* RNA_scene_local_itemf (bContext * C, PointerRNA * ptr, PropertyRNA * UNUSEDprop, int * do_free)
Definition at line 4052 of file wm_operators.c.
References CTX_data_main(), NULL, rna_id_itemf(), and TRUE.
static void save_set_compress (wmOperator * op) [static]
Definition at line 1948 of file wm_operators.c.
References G, G_FILE_COMPRESS, wmOperator::ptr, RNA_boolean_set(), RNA_struct_property_is_set(), and USER_FILECOMPRESS.
Referenced by wm_save_as_mainfile_exec(), wm_save_as_mainfile_invoke(), and wm_save_mainfile_invoke().
static int straightline_apply (bContext * C, wmOperator * op) [static]
Definition at line 2810 of file wm_operators.c.
References wmGesture::customdata, wmOperator::customdata, wmOperatorType::exec, wmOperator::ptr, RNA_int_set(), wmOperator::type, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by WM_gesture_straightline_modal().
static void tweak_gesture_modal (bContext * C, wmEvent * event) [static]
Definition at line 2564 of file wm_operators.c.
References CTX_wm_window(), wmGesture::customdata, wmGesture::event_type, wmWindow::eventstate, EVT_TWEAK_L, EVT_TWEAK_M, EVT_TWEAK_R, INBETWEEN_MOUSEMOVE, ISTIMER, KM_RELEASE, LEFTMOUSE, MIDDLEMOUSE, MOUSEMOVE, RIGHTMOUSE, wmGesture::swinid, wmWindow::tweak, wmEvent::type, wmEvent::val, wm_event_add(), WM_gesture_end(), wm_gesture_evaluate(), wm_subwindow_getorigin(), rcti::xmax, and rcti::ymax.
Referenced by wm_tweakevent_test().
static void untitled (char * name) [static]
Definition at line 1936 of file wm_operators.c.
References BLI_last_slash(), FILE_MAX, G, and strlen().
Referenced by wm_save_as_mainfile_exec(), wm_save_as_mainfile_invoke(), and wm_save_mainfile_invoke().
static uiBlock* wm_block_create_redo (bContext * C, ARegion * ar, void * arg_op) [static]
Definition at line 958 of file wm_operators.c.
References assert, ED_undo_operator_repeat_cb_evt(), ListBase::first, wmOperatorType::flag, wmOperator::macro, wmOperatorType::name, wmOperator::next, NULL, OPTYPE_MACRO, OPTYPE_REGISTER, RNA_struct_ui_name(), wmOperatorType::srna, wmOperator::type, UI_BLOCK_KEEP_OPEN, UI_BLOCK_LOOP, UI_BLOCK_MOVEMOUSE_QUIT, UI_BLOCK_RET_1, UI_EMBOSS, UI_GetStyle(), UI_LAYOUT_OP_SHOW_TITLE, UI_LAYOUT_PANEL, UI_LAYOUT_VERTICAL, UI_UNIT_Y, uiBeginBlock(), uiBlockClearFlag(), uiBlockLayout(), uiBlockSetFlag(), uiBlockSetHandleFunc(), uiEndBlock(), uiItemL(), uiLayoutOperatorButs(), uiLayoutSetEnabled(), uiPopupBoundsBlock(), and WM_operator_check_ui_enabled().
Referenced by WM_operator_props_popup(), and WM_operator_redo_popup().
static uiBlock* wm_block_create_splash (bContext * C, ARegion * ar, void * arg_unused) [static]
Referenced by wm_block_splash_refreshmenu(), and wm_splash_invoke().
static uiBlock* wm_block_create_splash (bContext * C, ARegion * ar, void * UNUSEDarg) [static]
Definition at line 1254 of file wm_operators.c.
References BLENDER_SUBVERSION, BLENDER_VERSION, BLENDER_VERSION_CHAR, BLENDER_VERSION_CYCLE, BLF_size(), BLF_width(), BLI_path_basename(), BLI_snprintf(), build_rev, BUT_IMAGE, datatoc_splash_png, datatoc_splash_png_size, MenuType::draw, RecentFile::filepath, G, i, IB_rect, IFACE_, IMB_ibImageFromMemory(), LABEL, Menu::layout, mt, RecentFile::next, NULL, uiFontStyle::points, split(), STRINGIFY, TRUE, Menu::type, UI_BLOCK_KEEP_OPEN, UI_EMBOSS, UI_EMBOSSP, UI_GetStyle(), UI_LAYOUT_PANEL, UI_LAYOUT_VERTICAL, UI_UNIT_Y, uiBeginBlock(), uiBlockLayout(), uiBlockSetEmboss(), uiBlockSetFlag(), uiBlockSetFunc(), uiButSetFunc(), uiCenteredBoundsBlock(), uiDefBut(), uiEndBlock(), uiFontStyle::uifont_id, uiItemL(), uiItemO(), uiItemS(), uiItemStringO(), uiLayoutColumn(), uiLayoutSetOperatorContext(), uiLayoutSplit(), uiStyle::widgetlabel, wm_block_splash_close(), wm_block_splash_refreshmenu(), WM_menutype_find(), WM_OP_EXEC_REGION_WIN, and wm_resource_check_prev().
static uiBlock* wm_block_dialog_create (bContext * C, ARegion * ar, void * userData) [static]
Definition at line 1034 of file wm_operators.c.
References BUT, data, dialog_check_cb(), dialog_exec_cb(), FALSE, wmOpPopUp::height, IFACE_, NULL, wmOpPopUp::op, UI_BLOCK_KEEP_OPEN, UI_BLOCK_LOOP, UI_BLOCK_MOVEMOUSE_QUIT, UI_BLOCK_RET_1, UI_EMBOSS, UI_GetStyle(), UI_LAYOUT_OP_SHOW_TITLE, UI_LAYOUT_PANEL, UI_LAYOUT_VERTICAL, UI_UNIT_Y, uiBeginBlock(), uiBlockClearFlag(), uiBlockLayout(), uiBlockSetFlag(), uiBlockSetFunc(), uiButSetFunc(), uiDefBut(), uiEndBlock(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutOperatorButs(), uiPopupBoundsBlock(), and wmOpPopUp::width.
Referenced by WM_operator_props_dialog_popup().
static uiBlock* wm_block_search_menu (bContext * C, ARegion * ar, void * UNUSEDarg_op) [static]
Definition at line 1421 of file wm_operators.c.
References CTX_wm_window(), wmWindow::eventstate, EVT_BUT_OPEN, FALSE, KM_PRESS, LABEL, NULL, operator_call_cb(), operator_search_cb(), UI_BLOCK_LOOP, UI_BLOCK_MOVEMOUSE_QUIT, UI_BLOCK_RET_1, UI_EMBOSS, UI_UNIT_X, UI_UNIT_Y, uiBeginBlock(), uiBlockSetFlag(), uiButSetSearchFunc(), uiDefBut(), uiDefSearchBut(), uiEndBlock(), uiPopupBoundsBlock(), uiSearchBoxhHeight(), and wm_event_add().
Referenced by wm_search_menu_invoke().
static void wm_block_splash_close (bContext * C, void * arg_block, void * UNUSEDarg) [static]
Definition at line 1212 of file wm_operators.c.
References uiPupBlockClose().
Referenced by wm_block_create_splash().
static void wm_block_splash_refreshmenu (bContext * UNUSEDC, void * UNUSEDarg_block, void * UNUSEDarg) [static]
Definition at line 1221 of file wm_operators.c.
References NULL, uiPupBlock(), uiPupBlockClose(), and wm_block_create_splash().
Referenced by wm_block_create_splash().
int WM_border_select_cancel (bContext * C, wmOperator * op)
Definition at line 2433 of file wm_operators.c.
References OPERATOR_CANCELLED, and wm_gesture_end().
Referenced by ACTION_OT_select_border(), ANIM_OT_channels_select_border(), ANIM_OT_previewrange_set(), FILE_OT_select_border(), GRAPH_OT_select_border(), INFO_OT_select_border(), MARKER_OT_select_border(), NLA_OT_select_border(), NODE_OT_select_border(), OUTLINER_OT_select_border(), SEQUENCER_OT_select_border(), SEQUENCER_OT_view_ghost_border(), UV_OT_select_border(), VIEW2D_OT_zoom_border(), VIEW3D_OT_clip_border(), VIEW3D_OT_render_border(), VIEW3D_OT_select_border(), and VIEW3D_OT_zoom_border().
int WM_border_select_invoke (bContext * C, wmOperator * op, wmEvent * event)
Definition at line 2363 of file wm_operators.c.
References wmOperator::customdata, ISTWEAK, OPERATOR_RUNNING_MODAL, wmEvent::type, WM_event_add_modal_handler(), WM_GESTURE_CROSS_RECT, WM_gesture_new(), WM_GESTURE_RECT, and wm_gesture_tag_redraw().
Referenced by ACTION_OT_select_border(), ANIM_OT_channels_select_border(), ANIM_OT_previewrange_set(), CLIP_OT_graph_select_border(), CLIP_OT_select_border(), ed_marker_select_border_invoke_wrapper(), FILE_OT_select_border(), GRAPH_OT_select_border(), hide_show_invoke(), INFO_OT_select_border(), NLA_OT_select_border(), node_border_select_invoke(), OUTLINER_OT_select_border(), SEQUENCER_OT_select_border(), SEQUENCER_OT_view_ghost_border(), UV_OT_select_border(), VIEW2D_OT_zoom_border(), view3d_clipping_invoke(), VIEW3D_OT_render_border(), VIEW3D_OT_select_border(), and view3d_zoom_border_invoke().
int WM_border_select_modal (bContext * C, wmOperator * op, wmEvent * event)
Definition at line 2378 of file wm_operators.c.
References border_apply(), border_apply_rect(), CTX_wm_window(), wmGesture::customdata, wmOperator::customdata, EVT_MODAL_MAP, GESTURE_MODAL_BEGIN, GESTURE_MODAL_CANCEL, GESTURE_MODAL_DESELECT, GESTURE_MODAL_IN, GESTURE_MODAL_OUT, GESTURE_MODAL_SELECT, wmGesture::mode, MOUSEMOVE, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmGesture::swinid, wmGesture::type, wmEvent::type, wmEvent::val, WM_GESTURE_CROSS_RECT, wm_gesture_end(), wm_gesture_tag_redraw(), wm_subwindow_getorigin(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ACTION_OT_select_border(), ANIM_OT_channels_select_border(), ANIM_OT_previewrange_set(), CLIP_OT_graph_select_border(), CLIP_OT_select_border(), file_border_select_modal(), GRAPH_OT_select_border(), INFO_OT_select_border(), MARKER_OT_select_border(), NLA_OT_select_border(), NODE_OT_select_border(), OUTLINER_OT_select_border(), PAINT_OT_hide_show(), SEQUENCER_OT_select_border(), SEQUENCER_OT_view_ghost_border(), UV_OT_select_border(), VIEW2D_OT_zoom_border(), VIEW3D_OT_clip_border(), VIEW3D_OT_render_border(), VIEW3D_OT_select_border(), and VIEW3D_OT_zoom_border().
static int wm_call_menu_exec (bContext * C, wmOperator * op) [static]
Definition at line 1493 of file wm_operators.c.
References BKE_ST_MAXNAME, OPERATOR_CANCELLED, wmOperator::ptr, RNA_string_get(), and uiPupMenuInvoke().
Referenced by WM_OT_call_menu().
static int wm_debug_menu_exec (bContext * C, wmOperator * op) [static]
Definition at line 1181 of file wm_operators.c.
References CTX_wm_manager(), CTX_wm_window(), ED_screen_refresh(), G, NC_WINDOW, NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_int_get(), and WM_event_add_notifier().
Referenced by WM_OT_debug_menu().
static int wm_debug_menu_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1190 of file wm_operators.c.
References G, wmOperator::ptr, RNA_int_set(), UI_UNIT_X, UI_UNIT_Y, and WM_operator_props_dialog_popup().
Referenced by WM_OT_debug_menu().
int WM_enum_search_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent)
Definition at line 768 of file wm_operators.c.
References OPERATOR_CANCELLED, uiPupBlock(), and wm_enum_search_menu().
Referenced by make_proxy_invoke(), NLA_OT_actionclip_add(), OBJECT_OT_group_instance_add(), OBJECT_OT_group_link(), OBJECT_OT_make_links_scene(), OUTLINER_OT_action_set(), PAINT_OT_project_image(), sequencer_add_movieclip_strip_invoke(), and sequencer_add_scene_strip_invoke().
static uiBlock* wm_enum_search_menu (bContext * C, ARegion * ar, void * arg_op) [static]
Definition at line 733 of file wm_operators.c.
References CTX_wm_window(), wmWindow::eventstate, EVT_BUT_OPEN, FALSE, KM_PRESS, LABEL, NULL, operator_enum_call_cb(), operator_enum_search_cb(), RNA_struct_ui_name(), wmOperatorType::srna, wmOperator::type, UI_BLOCK_LOOP, UI_BLOCK_MOVEMOUSE_QUIT, UI_BLOCK_RET_1, UI_EMBOSS, UI_UNIT_X, UI_UNIT_Y, uiBeginBlock(), uiBlockSetFlag(), uiButSetSearchFunc(), uiDefBut(), uiDefSearchBut(), uiEndBlock(), uiPopupBoundsBlock(), uiSearchBoxhHeight(), and wm_event_add().
Referenced by WM_enum_search_invoke().
static int wm_exit_blender_op (bContext * C, wmOperator * op) [static]
Definition at line 2227 of file wm_operators.c.
References OPERATOR_FINISHED, WM_exit(), and WM_operator_free().
Referenced by WM_OT_quit_blender().
int WM_gesture_circle_cancel (bContext * C, wmOperator * op)
Definition at line 2535 of file wm_operators.c.
References OPERATOR_CANCELLED, and wm_gesture_end().
Referenced by UV_OT_circle_select(), and VIEW3D_OT_select_circle().
int WM_gesture_circle_invoke (bContext * C, wmOperator * op, wmEvent * event)
Definition at line 2447 of file wm_operators.c.
References wmOperator::customdata, OPERATOR_RUNNING_MODAL, WM_event_add_modal_handler(), WM_GESTURE_CIRCLE, WM_gesture_new(), and wm_gesture_tag_redraw().
Referenced by CLIP_OT_select_circle(), UV_OT_circle_select(), and VIEW3D_OT_select_circle().
int WM_gesture_circle_modal (bContext * C, wmOperator * op, wmEvent * event)
Definition at line 2479 of file wm_operators.c.
References CTX_wm_window(), wmGesture::customdata, wmOperator::customdata, EVT_MODAL_MAP, gesture_circle_apply(), GESTURE_MODAL_CANCEL, GESTURE_MODAL_CIRCLE_ADD, GESTURE_MODAL_CIRCLE_SUB, GESTURE_MODAL_CONFIRM, GESTURE_MODAL_DESELECT, GESTURE_MODAL_NOP, GESTURE_MODAL_SELECT, wmGesture::mode, MOUSEMOVE, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_int_set(), RNA_struct_find_property(), wmGesture::swinid, wmEvent::type, wmEvent::val, wm_gesture_end(), wm_gesture_tag_redraw(), wm_subwindow_getorigin(), rcti::xmax, rcti::xmin, and rcti::ymin.
Referenced by CLIP_OT_select_circle(), UV_OT_circle_select(), and VIEW3D_OT_select_circle().
static void wm_gesture_end (bContext * C, wmOperator * op) [static]
Definition at line 2350 of file wm_operators.c.
References CTX_wm_area(), CTX_wm_window(), wmOperator::customdata, ED_area_tag_redraw(), NULL, wmOperator::ptr, RNA_struct_find_property(), WM_cursor_restore(), and WM_gesture_end().
Referenced by gesture_lasso_apply(), WM_border_select_cancel(), WM_border_select_modal(), WM_gesture_circle_cancel(), WM_gesture_circle_modal(), WM_gesture_lasso_cancel(), WM_gesture_lasso_modal(), WM_gesture_lines_cancel(), WM_gesture_straightline_cancel(), and WM_gesture_straightline_modal().
int WM_gesture_lasso_cancel (bContext * C, wmOperator * op)
Definition at line 2758 of file wm_operators.c.
References OPERATOR_CANCELLED, and wm_gesture_end().
Referenced by VIEW3D_OT_select_lasso().
int WM_gesture_lasso_invoke (bContext * C, wmOperator * op, wmEvent * event)
Definition at line 2642 of file wm_operators.c.
References CTX_wm_window(), wmOperator::customdata, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_int_get(), RNA_struct_find_property(), WM_cursor_modal(), WM_event_add_modal_handler(), WM_GESTURE_LASSO, WM_gesture_new(), and wm_gesture_tag_redraw().
Referenced by VIEW3D_OT_select_lasso().
int WM_gesture_lasso_modal (bContext * C, wmOperator * op, wmEvent * event)
Definition at line 2697 of file wm_operators.c.
References CTX_wm_window(), wmGesture::customdata, wmOperator::customdata, ESCKEY, gesture_lasso_apply(), INBETWEEN_MOUSEMOVE, KM_RELEASE, LEFTMOUSE, MEM_callocN(), MEM_freeN(), MIDDLEMOUSE, MOUSEMOVE, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmGesture::points, RIGHTMOUSE, wmGesture::size, wmGesture::swinid, wmEvent::type, wmEvent::val, wm_gesture_end(), wm_gesture_tag_redraw(), WM_LASSO_MIN_POINTS, and wm_subwindow_getorigin().
Referenced by VIEW3D_OT_select_lasso(), and WM_gesture_lines_modal().
int WM_gesture_lines_cancel (bContext * C, wmOperator * op)
Definition at line 2765 of file wm_operators.c.
References OPERATOR_CANCELLED, and wm_gesture_end().
Referenced by LOGIC_OT_links_cut(), and NODE_OT_links_cut().
int WM_gesture_lines_invoke (bContext * C, wmOperator * op, wmEvent * event)
Definition at line 2657 of file wm_operators.c.
References CTX_wm_window(), wmOperator::customdata, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_int_get(), RNA_struct_find_property(), WM_cursor_modal(), WM_event_add_modal_handler(), WM_GESTURE_LINES, WM_gesture_new(), and wm_gesture_tag_redraw().
Referenced by LOGIC_OT_links_cut(), MESH_OT_knife_cut(), and NODE_OT_links_cut().
int WM_gesture_lines_modal (bContext * C, wmOperator * op, wmEvent * event)
Definition at line 2753 of file wm_operators.c.
References WM_gesture_lasso_modal().
Referenced by LOGIC_OT_links_cut(), MESH_OT_knife_cut(), and NODE_OT_links_cut().
int WM_gesture_straightline_cancel (bContext * C, wmOperator * op)
Definition at line 2894 of file wm_operators.c.
References OPERATOR_CANCELLED, and wm_gesture_end().
Referenced by IMAGE_OT_sample_line().
int WM_gesture_straightline_invoke (bContext * C, wmOperator * op, wmEvent * event)
Definition at line 2831 of file wm_operators.c.
References CTX_wm_window(), wmOperator::customdata, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_int_get(), RNA_struct_find_property(), WM_cursor_modal(), WM_event_add_modal_handler(), WM_gesture_new(), WM_GESTURE_STRAIGHTLINE, and wm_gesture_tag_redraw().
Referenced by image_sample_line_invoke().
int WM_gesture_straightline_modal (bContext * C, wmOperator * op, wmEvent * event)
Definition at line 2846 of file wm_operators.c.
References CTX_wm_window(), wmGesture::customdata, wmOperator::customdata, EVT_MODAL_MAP, GESTURE_MODAL_BEGIN, GESTURE_MODAL_CANCEL, GESTURE_MODAL_SELECT, wmGesture::mode, MOUSEMOVE, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, straightline_apply(), wmGesture::swinid, wmEvent::type, wmEvent::val, wm_gesture_end(), wm_gesture_tag_redraw(), wm_subwindow_getorigin(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by IMAGE_OT_sample_line().
static int wm_link_append_exec (bContext * C, wmOperator * op) [static]
Definition at line 1715 of file wm_operators.c.
References BKE_idcode_from_name(), BKE_library_make_local(), BKE_report(), BKE_reportf(), BLI_assert, BLI_findstring(), BLI_path_cmp, BLI_strncpy(), BLO_blendhandle_close(), BLO_blendhandle_from_file(), BLO_is_a_library(), BLO_library_append_begin(), BLO_library_append_end(), BLO_library_append_named_part_ex(), CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), DAG_scene_sort(), FILE_GROUP_INSTANCE, FILE_LINK, FILE_MAX, RecentFile::filepath, flag_all_listbases_ids(), G, GROUP_MAX, Scene::id, ID::lib, LIB_PRE_EXISTING, Main::library, ID::name, Main::name, NC_WINDOW, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, recalc_all_library_objects(), wmOperator::reports, RNA_BEGIN, RNA_boolean_get(), RNA_END, RNA_property_collection_length(), RNA_string_get(), RNA_struct_find_property(), RPT_ERROR, RPT_WARNING, scene_deselect_all(), WM_event_add_notifier(), and wm_link_append_flag().
Referenced by WM_OT_link_append().
static short wm_link_append_flag (wmOperator * op) [static]
Definition at line 1702 of file wm_operators.c.
References FILE_ACTIVELAY, FILE_AUTOSELECT, FILE_GROUP_INSTANCE, FILE_LINK, FILE_RELPATH, wmOperator::ptr, and RNA_boolean_get().
Referenced by wm_link_append_exec().
static int wm_link_append_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1681 of file wm_operators.c.
References BLI_parent_dir(), BLI_strncpy(), FILE_MAX, G, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_string_set(), RNA_struct_property_is_set(), WM_event_add_fileselect(), and WM_operator_call_notest().
Referenced by WM_OT_link_append().
int wm_link_append_poll (bContext * C)
Definition at line 1665 of file wm_operators.c.
References CTX_data_edit_object(), and WM_operator_winactive().
Referenced by WM_OT_link_append().
static int wm_macro_cancel (bContext * C, wmOperator * op) [static]
Definition at line 337 of file wm_operators.c.
References wmOperatorType::cancel, OPERATOR_CANCELLED, wmOperator::opm, wmOperator::type, and wm_macro_end().
Referenced by WM_operatortype_append_macro(), and WM_operatortype_append_macro_ptr().
static int wm_macro_end (wmOperator * op, int retval) [static]
Definition at line 194 of file wm_operators.c.
References wmOperator::customdata, MEM_freeN(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, and MacroData::retval.
Referenced by wm_macro_cancel(), wm_macro_exec(), wm_macro_invoke_internal(), and wm_macro_modal().
static int wm_macro_exec (bContext * C, wmOperator * op) [static]
Definition at line 217 of file wm_operators.c.
References wmOperator::customdata, wmOperatorType::exec, ListBase::first, wmOperator::macro, wmOperator::next, OPERATOR_FINISHED, OPERATOR_RETVAL_CHECK, MacroData::retval, wmOperator::type, wm_macro_end(), and wm_macro_start().
Referenced by WM_operatortype_append_macro(), and WM_operatortype_append_macro_ptr().
static int wm_macro_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 270 of file wm_operators.c.
References ListBase::first, wmOperator::macro, wm_macro_invoke_internal(), and wm_macro_start().
Referenced by WM_operatortype_append_macro(), and WM_operatortype_append_macro_ptr().
static int wm_macro_invoke_internal (bContext * C, wmOperator * op, wmEvent * event, wmOperator * opm) [static]
Definition at line 243 of file wm_operators.c.
References BLI_movelisttolist(), wmOperator::customdata, wmOperatorType::exec, wmOperatorType::invoke, ReportList::list, wmOperator::next, OPERATOR_FINISHED, OPERATOR_RETVAL_CHECK, wmOperator::reports, MacroData::retval, wmOperator::type, and wm_macro_end().
Referenced by wm_macro_invoke(), and wm_macro_modal().
static int wm_macro_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 276 of file wm_operators.c.
References BLI_remlink(), bounds(), CTX_wm_region(), CTX_wm_window(), wmOperator::customdata, FALSE, ListBase::first, wmOperator::flag, wmOperatorType::flag, wmOperatorType::modal, wmWindow::modalhandlers, wmEventHandler::next, wmOperator::next, NULL, wmEventHandler::op, OP_GRAB_POINTER, OPERATOR_FINISHED, OPERATOR_RETVAL_CHECK, OPERATOR_RUNNING_MODAL, wmOperator::opm, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, MacroData::retval, wmOperator::type, USER_CONTINUOUS_MOUSE, ARegion::winrct, WM_cursor_grab(), wm_event_free_handler(), wm_macro_end(), wm_macro_invoke_internal(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by WM_operatortype_append_macro(), and WM_operatortype_append_macro_ptr().
static void wm_macro_start (wmOperator * op) [static]
Definition at line 187 of file wm_operators.c.
References wmOperator::customdata, MEM_callocN(), and NULL.
Referenced by wm_macro_exec(), and wm_macro_invoke().
int WM_menu_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent)
Definition at line 651 of file wm_operators.c.
References PointerRNA::data, wmOperatorType::exec, wmOperatorType::idname, NULL, OPERATOR_CANCELLED, OPERATOR_RETVAL_CHECK, wmOperatorType::prop, PROP_ENUM, wmOperator::ptr, RNA_property_identifier(), RNA_property_is_set(), RNA_property_type(), RNA_struct_ui_name(), wmOperatorType::srna, wmOperator::type, uiItemsFullEnumO(), uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), and WM_OP_EXEC_REGION_WIN.
Referenced by ACTION_OT_extrapolation_type(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_mirror(), ACTION_OT_snap(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), ANIM_OT_channels_setting_toggle(), ARMATURE_OT_autoside_names(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), BOID_OT_rule_add(), CURVE_OT_handle_type_set(), CURVE_OT_spline_type_set(), GPENCIL_OT_convert(), GRAPH_OT_extrapolation_type(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_snap(), LOGIC_OT_actuator_add(), LOGIC_OT_controller_add(), LOGIC_OT_sensor_add(), MESH_OT_delete(), MESH_OT_merge(), MESH_OT_select_similar(), MESH_OT_separate(), MESH_OT_sort_faces(), NLA_OT_snap(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_convert(), OBJECT_OT_effector_add(), OBJECT_OT_hook_remove(), OBJECT_OT_lamp_add(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_modifier_add(), OBJECT_OT_origin_set(), OBJECT_OT_parent_clear(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), OBJECT_OT_vertex_group_set_active(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_object_operation(), PAINT_OT_weight_from_bones(), PAINT_OT_weight_sample_group(), PARTICLE_OT_delete(), POSE_OT_autoside_names(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_rotation_mode_set(), POSE_OT_select_grouped(), POSELIB_OT_pose_remove(), SCENE_OT_new(), SEQUENCER_OT_select_grouped(), TRANSFORM_OT_snap_type(), VIEW3D_OT_select_menu(), and WM_OT_redraw_timer().
static int wm_ndof_sensitivity_exec (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 3610 of file wm_operators.c.
References max, min, OPERATOR_FINISHED, wmOperator::ptr, and RNA_boolean_get().
Referenced by WM_OT_ndof_sensitivity_change().
static int wm_open_mainfile_exec (bContext * C, wmOperator * op) [static]
Definition at line 1618 of file wm_operators.c.
References FILE_MAX, G, G_FILE_NO_UI, G_SCRIPT_AUTOEXEC, NC_WINDOW, NULL, open_set_load_ui(), open_set_use_scripts(), OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_string_get(), WM_event_add_notifier(), and WM_read_file().
Referenced by WM_OT_open_mainfile().
static int wm_open_mainfile_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1591 of file wm_operators.c.
References BKE_report(), CTX_wm_window(), RecentFile::filepath, G, NULL, open_set_load_ui(), open_set_use_scripts(), OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, wmOperator::reports, RNA_string_set(), RPT_ERROR, and WM_event_add_fileselect().
Referenced by WM_OT_open_mainfile().
void WM_operator_bl_idname (char * to, const char * from)
Definition at line 492 of file wm_operators.c.
References BLI_ascii_strtoupper(), BLI_strncpy(), and OP_MAX_TYPENAME.
Referenced by WM_operatortype_find().
int WM_operator_check_ui_enabled (const bContext * C, const char * idname)
Definition at line 937 of file wm_operators.c.
References CTX_data_scene(), CTX_wm_manager(), ED_undo_valid(), and WM_jobs_test().
Referenced by clip_panel_operator_redo(), view3d_panel_operator_redo(), and wm_block_create_redo().
int WM_operator_confirm (bContext * C, wmOperator * op, wmEvent * UNUSEDevent)
Definition at line 795 of file wm_operators.c.
References NULL, and WM_operator_confirm_message().
Referenced by ACTION_OT_delete(), ANIM_OT_keyframe_delete_v3d(), ARMATURE_OT_align(), ARMATURE_OT_delete(), ARMATURE_OT_separate(), CLIP_OT_delete_marker(), CLIP_OT_delete_track(), CLIP_OT_graph_delete_curve(), ed_marker_delete_invoke_wrapper(), FILE_OT_delete(), FILE_OT_directory_new(), GRAPH_OT_bake(), GRAPH_OT_delete(), OBJECT_OT_delete(), OBJECT_OT_parent_no_inverse_set(), OBJECT_OT_slow_parent_clear(), OBJECT_OT_slow_parent_set(), OBJECT_OT_vertex_parent_set(), SCREEN_OT_screencast(), SEQUENCER_OT_delete(), SEQUENCER_OT_meta_make(), SEQUENCER_OT_meta_separate(), TEXT_OT_reload(), TEXT_OT_unlink(), WM_OT_quit_blender(), WM_OT_read_factory_settings(), WM_OT_read_homefile(), and WM_OT_save_homefile().
int WM_operator_confirm_message (bContext * C, wmOperator * op, const char * message)
Definition at line 775 of file wm_operators.c.
References PointerRNA::data, IDP_CopyProperty(), IFACE_, IDProperty::len, NULL, OPERATOR_CANCELLED, wmOperator::ptr, wmOperator::type, uiItemFullO_ptr(), uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), and WM_OP_EXEC_REGION_WIN.
Referenced by file_directory_invoke(), move_to_layer_invoke(), and WM_operator_confirm().
int WM_operator_filesel (bContext * C, wmOperator * op, wmEvent * UNUSEDevent)
Definition at line 801 of file wm_operators.c.
References OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_struct_property_is_set(), WM_event_add_fileselect(), and WM_operator_call_notest().
Referenced by graphkeys_sound_bake_invoke(), node_add_file_invoke(), sound_mixdown_invoke(), and sound_open_invoke().
int WM_operator_filesel_ensure_ext_imtype (wmOperator * op, const char imtype)
Definition at line 812 of file wm_operators.c.
References BKE_add_image_extension(), FALSE, FILE_MAX, wmOperator::ptr, RNA_property_string_get(), RNA_property_string_set(), RNA_struct_find_property(), and TRUE.
Referenced by image_save_as_check(), and screenshot_check().
wmOperator* WM_operator_last_redo (const bContext * C)
Definition at line 945 of file wm_operators.c.
References CTX_wm_manager(), wmOperatorType::flag, ListBase::last, wmWindowManager::operators, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperator::prev, and wmOperator::type.
Referenced by clip_panel_operator_redo(), clip_panel_operator_redo_header(), ed_screen_context(), file_browse_exec(), redo_last_invoke(), view3d_panel_operator_redo(), and view3d_panel_operator_redo_header().
void WM_operator_properties_alloc (PointerRNA ** ptr, IDProperty ** properties, const char * opstring)
Definition at line 574 of file wm_operators.c.
References IDP_GROUP, IDP_New(), MEM_callocN(), NULL, and WM_operator_properties_create().
Referenced by WM_dropbox_add(), wm_keymap_item_properties_set(), and WM_operatortype_macro_define().
void WM_operator_properties_create (PointerRNA * ptr, const char * opstring)
Definition at line 562 of file wm_operators.c.
References NULL, RNA_OperatorProperties, RNA_pointer_create(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
Referenced by do_view3d_header_buttons(), file_browse_invoke(), file_panel_cb(), ghost_event_proc(), node_render_changed_exec(), object_mouse_select_menu(), parent_drop_invoke(), screen_area_options_invoke(), ui_but_menu(), ui_set_but_default(), uiLayoutOperatorButs(), wm_keymap_item_copy(), and WM_operator_properties_alloc().
void WM_operator_properties_create_ptr (PointerRNA * ptr, wmOperatorType * ot)
Definition at line 557 of file wm_operators.c.
References NULL, RNA_pointer_create(), and wmOperatorType::srna.
Referenced by node_composit_buts_renderlayers(), operator_enum_call_cb(), pyop_call(), pyop_getrna(), uiButGetOperatorPtrRNA(), uiItemBooleanO(), uiItemEnumO_ptr(), uiItemEnumO_ptr__internal(), uiItemEnumO_string(), uiItemEnumO_value(), uiItemFloatO(), uiItemIntO(), uiItemsFullEnumO(), uiItemStringO(), WM_operator_properties_create(), and WM_operator_pystring().
void WM_operator_properties_filesel (wmOperatorType * ot, int filter, short type, short action, short flag, short display)
Definition at line 829 of file wm_operators.c.
References BLENDERFILE, BTXFILE, COLLADAFILE, FILE_DEFAULTDISPLAY, FILE_IMGDISPLAY, FILE_LOADLIB, FILE_LONGDISPLAY, FILE_MAX, FILE_SAVE, FILE_SHORTDISPLAY, FILE_SPECIAL, FOLDERFILE, FTFONTFILE, IMAGEFILE, MOVIEFILE, NULL, PROP_HIDDEN, PROP_SKIP_SAVE, PYSCRIPTFILE, RNA_def_boolean(), RNA_def_collection_runtime(), RNA_def_enum(), RNA_def_int(), RNA_def_property_flag(), RNA_def_string_dir_path(), RNA_def_string_file_name(), RNA_def_string_file_path(), RNA_OperatorFileListElement, SOUNDFILE, wmOperatorType::srna, TEXTFILE, TRUE, WM_FILESEL_DIRECTORY, WM_FILESEL_FILENAME, WM_FILESEL_FILEPATH, WM_FILESEL_FILES, and WM_FILESEL_RELPATH.
Referenced by BUTTONS_OT_directory_browse(), BUTTONS_OT_file_browse(), CLIP_OT_open(), FILE_OT_find_missing_files(), FONT_OT_file_paste(), FONT_OT_open(), GRAPH_OT_sound_bake(), IMAGE_OT_open(), IMAGE_OT_replace(), IMAGE_OT_save_as(), NODE_OT_add_file(), OBJECT_OT_multires_external_save(), SCREEN_OT_screenshot(), SEQUENCER_OT_change_path(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_sound_strip_add(), SOUND_OT_mixdown(), SOUND_OT_open(), SOUND_OT_open_mono(), TEXT_OT_open(), TEXT_OT_save_as(), TEXTURE_OT_envmap_save(), WM_OT_link_append(), WM_OT_open_mainfile(), WM_OT_recover_auto_save(), WM_OT_save_as_mainfile(), and WM_OT_save_mainfile().
void WM_operator_properties_free (PointerRNA * ptr)
Definition at line 637 of file wm_operators.c.
References PointerRNA::data, IDP_FreeProperty(), MEM_freeN(), and NULL.
Referenced by do_view3d_header_buttons(), file_browse_invoke(), file_panel_cb(), ghost_event_proc(), node_render_changed_exec(), object_mouse_select_menu(), operator_enum_call_cb(), pyop_as_string(), pyop_call(), ui_apply_but_funcs_after(), ui_free_but(), ui_set_but_default(), wm_dropbox_free(), wm_keymap_item_free(), WM_keymap_properties_reset(), WM_keymap_remove_item(), WM_operator_pystring(), and wm_operatortype_free_macro().
void WM_operator_properties_gesture_border (wmOperatorType * ot, int extend)
Definition at line 905 of file wm_operators.c.
References RNA_def_boolean(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ACTION_OT_select_border(), ANIM_OT_channels_select_border(), CLIP_OT_graph_select_border(), CLIP_OT_select_border(), FILE_OT_select_border(), GRAPH_OT_select_border(), INFO_OT_select_border(), MARKER_OT_select_border(), NLA_OT_select_border(), NODE_OT_select_border(), OUTLINER_OT_select_border(), SEQUENCER_OT_select_border(), SEQUENCER_OT_view_ghost_border(), UV_OT_select_border(), and VIEW3D_OT_select_border().
void WM_operator_properties_gesture_straightline (wmOperatorType * ot, int cursor)
Definition at line 917 of file wm_operators.c.
References RNA_def_int(), and wmOperatorType::srna.
Referenced by IMAGE_OT_sample_line().
void WM_operator_properties_reset (wmOperator * op)
Definition at line 619 of file wm_operators.c.
References PointerRNA::data, PROP_SKIP_SAVE, wmOperator::ptr, RNA_PROP_BEGIN, RNA_PROP_END, RNA_property_flag(), RNA_property_identifier(), RNA_struct_idprops_unset(), RNA_struct_iterator_property(), wmOperatorType::srna, and wmOperator::type.
Referenced by ui_layout_operator_buts__reset_cb().
void WM_operator_properties_sanitize (PointerRNA * ptr, const short no_context)
Definition at line 590 of file wm_operators.c.
References PROP_ENUM, PROP_ENUM_NO_CONTEXT, PROP_POINTER, RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_OperatorProperties, RNA_property_pointer_get(), RNA_property_pointer_type(), RNA_property_type(), RNA_STRUCT_BEGIN, RNA_STRUCT_END, RNA_struct_is_a(), and WM_operator_properties_sanitize().
Referenced by pyop_call(), pyop_getrna(), wm_keymap_item_properties_set(), wm_operator_create(), WM_operator_properties_sanitize(), and WM_operatortype_macro_define().
void WM_operator_properties_select_all (wmOperatorType * ot)
Definition at line 892 of file wm_operators.c.
References NULL, RNA_def_enum(), SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, and wmOperatorType::srna.
Referenced by ARMATURE_OT_select_all(), CLIP_OT_graph_select_all_markers(), CLIP_OT_select_all(), CURVE_OT_select_all(), LATTICE_OT_select_all(), MARKER_OT_select_all(), MBALL_OT_select_all(), MESH_OT_select_all(), OBJECT_OT_select_all(), OBJECT_OT_vertex_group_lock(), PAINT_OT_face_select_all(), PAINT_OT_vert_select_all(), PARTICLE_OT_select_all(), POSE_OT_select_all(), SEQUENCER_OT_select_all(), and UV_OT_select_all().
int WM_operator_props_dialog_popup (bContext * C, wmOperator * op, int width, int height)
Definition at line 1147 of file wm_operators.c.
References data, wmOpPopUp::free_op, wmOpPopUp::height, MEM_callocN(), wmOpPopUp::op, OPERATOR_RUNNING_MODAL, TRUE, uiPupBlockEx(), wmOpPopUp::width, wm_block_dialog_create(), wm_operator_ui_popup_cancel(), and wm_operator_ui_popup_ok().
Referenced by image_new_invoke(), text_jump_invoke(), and wm_debug_menu_invoke().
int WM_operator_props_popup (bContext * C, wmOperator * op, wmEvent * UNUSEDevent)
Definition at line 1130 of file wm_operators.c.
References BKE_reportf(), ED_undo_push_op(), wmOperatorType::flag, wmOperatorType::idname, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, OPTYPE_REGISTER, wmOperator::reports, RPT_ERROR, wmOperator::type, uiPupBlock(), wm_block_create_redo(), and wm_operator_register().
Referenced by armature_bone_layers_invoke(), CURVE_OT_radius_set(), CURVE_OT_spline_weight_set(), ed_marker_rename_invoke_wrapper(), MBALL_OT_select_random_metaelems(), MESH_OT_blend_from_shape(), move_to_layer_invoke(), PARTICLE_OT_rekey(), pose_armature_layers_invoke(), pose_bone_layers_invoke(), and poselib_rename_invoke().
void WM_operator_py_idname (char * to, const char * from)
Definition at line 471 of file wm_operators.c.
References BLI_ascii_strtolower(), BLI_strncpy(), and OP_MAX_TYPENAME.
Referenced by operator_search_cb(), ui_but_menu(), and WM_operator_pystring().
char* WM_operator_pystring (bContext * C, wmOperatorType * ot, PointerRNA * opptr, int all_args)
Definition at line 521 of file wm_operators.c.
References BLI_dynstr_append(), BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), FALSE, wmOperatorType::idname, MEM_freeN(), NULL, OP_MAX_TYPENAME, RNA_pointer_as_string_keywords(), WM_operator_properties_create_ptr(), WM_operator_properties_free(), and WM_operator_py_idname().
Referenced by pyop_as_string(), ui_but_copy_paste(), ui_intro_button(), ui_tooltip_create(), wm_operator_finished(), wm_operator_print(), and wm_operator_reports().
int WM_operator_redo_popup (bContext * C, wmOperator * op)
Definition at line 1162 of file wm_operators.c.
References BKE_reportf(), CTX_wm_reports(), wmOperatorType::flag, wmOperatorType::idname, OPERATOR_CANCELLED, OPTYPE_REGISTER, wmOperatorType::poll, RPT_ERROR, wmOperator::type, uiPupBlock(), and wm_block_create_redo().
Referenced by redo_last_invoke().
static uiBlock* wm_operator_ui_create (bContext * C, ARegion * ar, void * userData) [static]
Definition at line 1075 of file wm_operators.c.
References data, wmOpPopUp::height, NULL, wmOpPopUp::op, UI_BLOCK_KEEP_OPEN, UI_BLOCK_LOOP, UI_BLOCK_MOVEMOUSE_QUIT, UI_BLOCK_RET_1, UI_EMBOSS, UI_GetStyle(), UI_LAYOUT_PANEL, UI_LAYOUT_VERTICAL, uiBeginBlock(), uiBlockClearFlag(), uiBlockLayout(), uiBlockSetFlag(), uiEndBlock(), uiLayoutOperatorButs(), uiPopupBoundsBlock(), and wmOpPopUp::width.
Referenced by WM_operator_ui_popup().
int WM_operator_ui_popup (bContext * C, wmOperator * op, int width, int height)
Definition at line 1118 of file wm_operators.c.
References data, wmOpPopUp::free_op, wmOpPopUp::height, MEM_callocN(), NULL, wmOpPopUp::op, OPERATOR_RUNNING_MODAL, TRUE, uiPupBlockEx(), wmOpPopUp::width, wm_operator_ui_create(), and wm_operator_ui_popup_cancel().
static void wm_operator_ui_popup_cancel (void * userData) [static]
Definition at line 1098 of file wm_operators.c.
References data, wmOpPopUp::free_op, MEM_freeN(), wmOpPopUp::op, and WM_operator_free().
Referenced by WM_operator_props_dialog_popup(), and WM_operator_ui_popup().
static void wm_operator_ui_popup_ok (struct bContext * C, void * arg, int retval) [static]
Definition at line 1109 of file wm_operators.c.
References data, wmOpPopUp::op, and WM_operator_call().
Referenced by WM_operator_props_dialog_popup().
int WM_operator_winactive (bContext * C)
Definition at line 930 of file wm_operators.c.
References CTX_wm_window(), and NULL.
Referenced by SCREEN_OT_new(), SCREEN_OT_screencast(), SCREEN_OT_screenshot(), SCREEN_OT_spacedata_cleanup(), wm_link_append_poll(), WM_OT_call_menu(), WM_OT_debug_menu(), WM_OT_quit_blender(), WM_OT_recover_auto_save(), WM_OT_recover_last_session(), WM_OT_redraw_timer(), WM_OT_save_homefile(), WM_OT_splash(), and WM_OT_window_fullscreen_toggle().
static int wm_operator_winactive_normal (bContext * C) [static]
Definition at line 1520 of file wm_operators.c.
References CTX_wm_window(), bScreen::full, NULL, wmWindow::screen, and SCREENNORMAL.
Referenced by WM_OT_window_duplicate().
void WM_operatortype_append (void(*)(wmOperatorType *) opfunc)
Definition at line 144 of file wm_operators.c.
References BLENDER_RNA, BLF_I18NCONTEXT_OPERATOR_DEFAULT, BLI_ghash_insert(), wmOperatorType::description, wmOperatorType::idname, MEM_callocN(), N_, wmOperatorType::name, NULL, RNA_def_struct(), RNA_def_struct_identifier(), RNA_def_struct_translation_context(), RNA_def_struct_ui_text(), and wmOperatorType::srna.
Referenced by action_operatortypes(), buttons_operatortypes(), clip_operatortypes(), console_operatortypes(), ED_operatortypes_anim(), ED_operatortypes_animchannels(), ED_operatortypes_armature(), ED_operatortypes_curve(), ED_operatortypes_gpencil(), ED_operatortypes_logic(), ED_operatortypes_marker(), ED_operatortypes_mesh(), ED_operatortypes_metaball(), ED_operatortypes_object(), ED_operatortypes_paint(), ED_operatortypes_render(), ED_operatortypes_screen(), ED_operatortypes_sculpt(), ED_operatortypes_sound(), ED_operatortypes_uvedit(), file_operatortypes(), graphedit_operatortypes(), image_operatortypes(), info_operatortypes(), logic_operatortypes(), nla_operatortypes(), node_operatortypes(), operatortypes_boids(), operatortypes_dynamicpaint(), operatortypes_fluid(), operatortypes_particle(), operatortypes_pointcache(), outliner_operatortypes(), script_operatortypes(), sequencer_operatortypes(), text_operatortypes(), time_operatortypes(), transform_operatortypes(), UI_buttons_operatortypes(), UI_view2d_operatortypes(), view3d_operatortypes(), and wm_operatortype_init().
wmOperatorType* WM_operatortype_append_macro (const char * idname, const char * name, int flag) [read]
Definition at line 348 of file wm_operators.c.
References BLENDER_RNA, BLF_I18NCONTEXT_OPERATOR_DEFAULT, BLI_ghash_insert(), wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MEM_callocN(), wmOperatorType::modal, N_, wmOperatorType::name, NULL, OPTYPE_MACRO, wmOperatorType::poll, RNA_def_struct(), RNA_def_struct_identifier(), RNA_def_struct_translation_context(), RNA_def_struct_ui_text(), wmOperatorType::srna, TRUE, wm_macro_cancel(), wm_macro_exec(), wm_macro_invoke(), wm_macro_modal(), and WM_operatortype_find().
Referenced by ED_operatormacros_action(), ED_operatormacros_armature(), ED_operatormacros_clip(), ED_operatormacros_curve(), ED_operatormacros_graph(), ED_operatormacros_mesh(), ED_operatormacros_node(), and ED_operatormacros_object().
void WM_operatortype_append_macro_ptr (void(*)(wmOperatorType *, void *) opfunc, void * userdata)
Definition at line 382 of file wm_operators.c.
References BLENDER_RNA, BLF_I18NCONTEXT_OPERATOR_DEFAULT, BLI_ghash_insert(), wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MEM_callocN(), wmOperatorType::modal, N_, wmOperatorType::name, NULL, OPTYPE_MACRO, wmOperatorType::poll, RNA_def_struct(), RNA_def_struct_identifier(), RNA_def_struct_translation_context(), RNA_def_struct_ui_text(), wmOperatorType::srna, wm_macro_cancel(), wm_macro_exec(), wm_macro_invoke(), and wm_macro_modal().
void WM_operatortype_append_ptr (void(*)(wmOperatorType *, void *) opfunc, void * userdata)
Definition at line 166 of file wm_operators.c.
References BLENDER_RNA, BLF_I18NCONTEXT_OPERATOR_DEFAULT, BLI_ghash_insert(), wmOperatorType::description, wmOperatorType::idname, MEM_callocN(), N_, wmOperatorType::name, RNA_def_struct(), RNA_def_struct_identifier(), RNA_def_struct_translation_context(), RNA_def_struct_ui_text(), and wmOperatorType::srna.
wmOperatorType* WM_operatortype_find (const char * idname, int quiet) [read]
Definition at line 110 of file wm_operators.c.
References BLI_ghash_lookup(), NULL, OP_MAX_TYPENAME, and WM_operator_bl_idname().
Referenced by graph_fmodifier_add_invoke(), node_composit_buts_renderlayers(), operator_search_menu(), poselib_add_menu_invoke__replacemenu(), pyop_as_string(), pyop_call(), pyop_getinstance(), pyop_getrna(), pyop_poll(), PYOP_wrap_macro_define(), ui_def_but_operator_text(), uiDefButO(), uiDefIconButO(), uiDefIconTextButO(), uiItemBooleanO(), uiItemEnumO(), uiItemEnumO_string(), uiItemEnumO_value(), uiItemFloatO(), uiItemFullO(), uiItemIntO(), uiItemMenuEnumO(), uiItemsFullEnumO(), uiItemStringO(), uiPupBlockO(), unpack_menu(), WM_dropbox_add(), wm_handler_operator_call(), WM_modalkeymap_assign(), wm_operator_create(), WM_operator_name_call(), WM_operator_poll(), WM_operator_properties_create(), WM_operatortype_append_macro(), WM_operatortype_macro_define(), and WM_operatortype_remove().
void wm_operatortype_free (void)
Definition at line 3670 of file wm_operators.c.
References BLI_ghash_free(), NULL, and operatortype_ghash_free_cb().
Referenced by WM_exit_ext().
static void wm_operatortype_free_macro (wmOperatorType * ot) [static]
Definition at line 433 of file wm_operators.c.
References BLI_freelistN(), ListBase::first, wmOperatorType::macro, MEM_freeN(), wmOperatorTypeMacro::next, wmOperatorTypeMacro::ptr, and WM_operator_properties_free().
Referenced by operatortype_ghash_free_cb(), and WM_operatortype_remove().
void wm_operatortype_init (void)
Definition at line 3677 of file wm_operators.c.
References BLI_ghash_new(), BLI_ghashutil_strcmp(), BLI_ghashutil_strhash(), WM_operatortype_append(), WM_OT_call_menu(), WM_OT_debug_menu(), WM_OT_dependency_relations(), WM_OT_link_append(), WM_OT_memory_statistics(), WM_OT_ndof_sensitivity_change(), WM_OT_open_mainfile(), WM_OT_quit_blender(), WM_OT_radial_control(), WM_OT_read_factory_settings(), WM_OT_read_homefile(), WM_OT_recover_auto_save(), WM_OT_recover_last_session(), WM_OT_redraw_timer(), WM_OT_save_as_mainfile(), WM_OT_save_homefile(), WM_OT_save_mainfile(), WM_OT_search_menu(), WM_OT_splash(), WM_OT_window_duplicate(), and WM_OT_window_fullscreen_toggle().
Referenced by WM_init().
GHashIterator* WM_operatortype_iter (void) [read]
Definition at line 138 of file wm_operators.c.
References BLI_ghashIterator_new().
Referenced by operator_search_cb(), and pyop_dir().
wmOperatorTypeMacro* WM_operatortype_macro_define (wmOperatorType * ot, const char * idname) [read]
Definition at line 409 of file wm_operators.c.
References BLI_addtail(), BLI_strncpy(), wmOperatorType::description, wmOperatorType::idname, wmOperatorTypeMacro::idname, wmOperatorType::macro, MEM_callocN(), wmOperatorType::name, OP_MAX_TYPENAME, wmOperatorTypeMacro::properties, wmOperatorTypeMacro::ptr, RNA_def_pointer_runtime(), wmOperatorType::srna, WM_operator_properties_alloc(), WM_operator_properties_sanitize(), and WM_operatortype_find().
Referenced by ED_operatormacros_action(), ED_operatormacros_armature(), ED_operatormacros_clip(), ED_operatormacros_curve(), ED_operatormacros_graph(), ED_operatormacros_mesh(), ED_operatormacros_node(), ED_operatormacros_object(), and PYOP_wrap_macro_define().
int WM_operatortype_remove (const char * idname)
Definition at line 447 of file wm_operators.c.
References BLENDER_RNA, BLI_ghash_remove(), ListBase::first, wmOperatorType::idname, IDP_FreeProperty(), wmOperatorType::last_properties, wmOperatorType::macro, MEM_freeN(), NULL, RNA_struct_free(), wmOperatorType::srna, WM_operatortype_find(), and wm_operatortype_free_macro().
static void WM_OT_call_menu (wmOperatorType * ot) [static]
Definition at line 1503 of file wm_operators.c.
References BKE_ST_MAXNAME, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_INTERNAL, wmOperatorType::poll, RNA_def_string(), wmOperatorType::srna, wm_call_menu_exec(), and WM_operator_winactive().
Referenced by wm_operatortype_init().
static void WM_OT_debug_menu (wmOperatorType * ot) [static]
Definition at line 1196 of file wm_operators.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, wm_debug_menu_exec(), wm_debug_menu_invoke(), and WM_operator_winactive().
Referenced by wm_operatortype_init().
static void WM_OT_dependency_relations (wmOperatorType * ot) [static]
Definition at line 3599 of file wm_operators.c.
References dependency_relations_exec(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, and wmOperatorType::name.
Referenced by wm_operatortype_init().
static void WM_OT_link_append (wmOperatorType * ot) [static]
Definition at line 1835 of file wm_operators.c.
References BLENDERFILE, wmOperatorType::description, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_LOADLIB, FILE_OPENFILE, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, WM_FILESEL_DIRECTORY, WM_FILESEL_FILENAME, WM_FILESEL_FILEPATH, WM_FILESEL_FILES, WM_FILESEL_RELPATH, wm_link_append_exec(), wm_link_append_invoke(), wm_link_append_poll(), and WM_operator_properties_filesel().
Referenced by wm_operatortype_init().
static void WM_OT_memory_statistics (wmOperatorType * ot) [static]
Definition at line 3577 of file wm_operators.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, memory_statistics_exec(), and wmOperatorType::name.
Referenced by wm_operatortype_init().
static void WM_OT_ndof_sensitivity_change (wmOperatorType * ot) [static]
Definition at line 3639 of file wm_operators.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, RNA_def_boolean(), wmOperatorType::srna, and wm_ndof_sensitivity_exec().
Referenced by wm_operatortype_init().
static void WM_OT_open_mainfile (wmOperatorType * ot) [static]
Definition at line 1645 of file wm_operators.c.
References BLENDERFILE, wmOperatorType::description, wmOperatorType::exec, FILE_BLENDER, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FOLDERFILE, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, RNA_def_boolean(), wmOperatorType::srna, WM_FILESEL_FILEPATH, wm_open_mainfile_exec(), wm_open_mainfile_invoke(), and WM_operator_properties_filesel().
Referenced by wm_operatortype_init().
static void WM_OT_quit_blender (wmOperatorType * ot) [static]
Definition at line 2236 of file wm_operators.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, wm_exit_blender_op(), WM_operator_confirm(), and WM_operator_winactive().
Referenced by wm_operatortype_init().
static void WM_OT_radial_control (wmOperatorType * ot) [static]
Definition at line 3411 of file wm_operators.c.
References wmOperatorType::cancel, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, radial_control_cancel(), radial_control_invoke(), radial_control_modal(), RNA_def_string(), and wmOperatorType::srna.
Referenced by wm_operatortype_init().
static void WM_OT_read_factory_settings (wmOperatorType * ot) [static]
Definition at line 1562 of file wm_operators.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, WM_operator_confirm(), and WM_read_homefile_exec().
Referenced by wm_operatortype_init().
static void WM_OT_read_homefile (wmOperatorType * ot) [static]
Definition at line 1551 of file wm_operators.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, WM_operator_confirm(), and WM_read_homefile_exec().
Referenced by wm_operatortype_init().
static void WM_OT_recover_auto_save (wmOperatorType * ot) [static]
Definition at line 1921 of file wm_operators.c.
References BLENDERFILE, wmOperatorType::description, wmOperatorType::exec, FILE_BLENDER, FILE_LONGDISPLAY, FILE_OPENFILE, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, WM_FILESEL_FILEPATH, WM_operator_properties_filesel(), WM_operator_winactive(), wm_recover_auto_save_exec(), and wm_recover_auto_save_invoke().
Referenced by wm_operatortype_init().
static void WM_OT_recover_last_session (wmOperatorType * ot) [static]
Definition at line 1878 of file wm_operators.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, WM_operator_winactive(), and wm_recover_last_session_exec().
Referenced by wm_operatortype_init().
static void WM_OT_redraw_timer (wmOperatorType * ot) [static]
Definition at line 3554 of file wm_operators.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, wmOperatorType::prop, redraw_timer_exec(), RNA_def_enum(), RNA_def_int(), wmOperatorType::srna, WM_menu_invoke(), and WM_operator_winactive().
Referenced by wm_operatortype_init().
static void WM_OT_save_as_mainfile (wmOperatorType * ot) [static]
Definition at line 2040 of file wm_operators.c.
References blend_save_check(), BLENDERFILE, wmOperatorType::check, wmOperatorType::description, wmOperatorType::exec, FILE_BLENDER, FILE_DEFAULTDISPLAY, FILE_SAVE, FOLDERFILE, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, RNA_def_boolean(), wmOperatorType::srna, WM_FILESEL_FILEPATH, WM_operator_properties_filesel(), wm_save_as_mainfile_exec(), and wm_save_as_mainfile_invoke().
Referenced by wm_operatortype_init().
static void WM_OT_save_homefile (wmOperatorType * ot) [static]
Definition at line 1540 of file wm_operators.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, WM_operator_confirm(), WM_operator_winactive(), and WM_write_homefile().
Referenced by wm_operatortype_init().
static void WM_OT_save_mainfile (wmOperatorType * ot) [static]
Definition at line 2107 of file wm_operators.c.
References blend_save_check(), BLENDERFILE, wmOperatorType::check, wmOperatorType::description, wmOperatorType::exec, FILE_BLENDER, FILE_DEFAULTDISPLAY, FILE_SAVE, FOLDERFILE, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, RNA_def_boolean(), wmOperatorType::srna, WM_FILESEL_FILEPATH, WM_operator_properties_filesel(), wm_save_as_mainfile_exec(), and wm_save_mainfile_invoke().
Referenced by wm_operatortype_init().
static void WM_OT_search_menu (wmOperatorType * ot) [static]
Definition at line 1483 of file wm_operators.c.
References wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, wm_search_menu_exec(), wm_search_menu_invoke(), and wm_search_menu_poll().
Referenced by wm_operatortype_init().
static void WM_OT_splash (wmOperatorType * ot) [static]
Definition at line 1366 of file wm_operators.c.
References wmOperatorType::description, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, WM_operator_winactive(), and wm_splash_invoke().
Referenced by wm_operatortype_init().
static void WM_OT_window_duplicate (wmOperatorType * ot) [static]
Definition at line 1530 of file wm_operators.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, wm_operator_winactive_normal(), and wm_window_duplicate_exec().
Referenced by wm_operatortype_init().
static void WM_OT_window_fullscreen_toggle (wmOperatorType * ot) [static]
Definition at line 2217 of file wm_operators.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, WM_operator_winactive(), and wm_window_fullscreen_toggle_exec().
Referenced by wm_operatortype_init().
void* WM_paint_cursor_activate (wmWindowManager * wm, int(*)(bContext *C) poll, wmPaintCursorDraw draw, void * customdata)
Definition at line 2278 of file wm_operators.c.
References BLI_addtail(), wmPaintCursor::customdata, wmPaintCursor::draw, MEM_callocN(), wmWindowManager::paintcursors, and wmPaintCursor::poll.
Referenced by ED_space_image_paint_update(), ED_space_image_uv_sculpt_update(), initTransform(), paint_cursor_start(), paint_stroke_modal(), radial_control_invoke(), toggle_paint_cursor(), and toggle_particle_cursor().
void WM_paint_cursor_end (wmWindowManager * wm, void * handle)
Definition at line 2292 of file wm_operators.c.
References BLI_remlink(), ListBase::first, MEM_freeN(), wmPaintCursor::next, and wmWindowManager::paintcursors.
Referenced by paint_stroke_modal(), postTrans(), radial_control_cancel(), toggle_paint_cursor(), and toggle_particle_cursor().
static int wm_recover_auto_save_exec (bContext * C, wmOperator * op) [static]
Definition at line 1890 of file wm_operators.c.
References FILE_MAX, G, G_FILE_RECOVER, NC_WINDOW, NULL, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_string_get(), WM_event_add_notifier(), and WM_read_file().
Referenced by WM_OT_recover_auto_save().
static int wm_recover_auto_save_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1910 of file wm_operators.c.
References FILE_MAX, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_string_set(), wm_autosave_location(), and WM_event_add_fileselect().
Referenced by WM_OT_recover_auto_save().
static int wm_recover_last_session_exec (bContext * C, wmOperator * op) [static]
Definition at line 1860 of file wm_operators.c.
References BLI_make_file_string(), BLI_temporary_dir(), FILE_MAX, G, G_FILE_RECOVER, NC_WINDOW, NULL, OPERATOR_FINISHED, wmOperator::reports, WM_event_add_notifier(), and WM_read_file().
Referenced by WM_OT_recover_last_session().
static int wm_resource_check_prev (void) [static]
Definition at line 1231 of file wm_operators.c.
References BLENDER_RESOURCE_PATH_LOCAL, BLENDER_RESOURCE_PATH_USER, BLENDER_VERSION, BLI_get_folder_version(), FALSE, NULL, and TRUE.
Referenced by wm_block_create_splash().
static int wm_save_as_mainfile_exec (bContext * C, wmOperator * op) [static]
Definition at line 1981 of file wm_operators.c.
References BLI_strncpy(), copy(), FILE_MAX, G, G_FILE_COMPRESS, G_FILE_MESH_COMPAT, G_FILE_RELATIVE_REMAP, NC_WM, ND_FILESAVE, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_string_get(), RNA_struct_find_property(), RNA_struct_property_is_set(), save_set_compress(), untitled(), WM_event_add_notifier(), and WM_write_file().
Referenced by WM_OT_save_as_mainfile(), WM_OT_save_mainfile(), and wm_save_mainfile_invoke().
static int wm_save_as_mainfile_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1958 of file wm_operators.c.
References BLI_strncpy(), FILE_MAX, RecentFile::filepath, G, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_string_set(), save_set_compress(), untitled(), and WM_event_add_fileselect().
Referenced by WM_OT_save_as_mainfile().
static int wm_save_mainfile_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 2062 of file wm_operators.c.
References BLI_exists(), BLI_strncpy(), CTX_wm_window(), FILE_MAX, RecentFile::filepath, G, NULL, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_boolean_get(), RNA_string_set(), RNA_struct_find_property(), save_set_compress(), uiPupMenuSaveOver(), untitled(), WM_event_add_fileselect(), and wm_save_as_mainfile_exec().
Referenced by WM_OT_save_mainfile().
static int wm_search_menu_exec (bContext * UNUSEDC, wmOperator * UNUSEDop) [static]
Definition at line 1451 of file wm_operators.c.
References OPERATOR_FINISHED.
Referenced by WM_OT_search_menu().
static int wm_search_menu_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1456 of file wm_operators.c.
References OPERATOR_CANCELLED, uiPupBlock(), and wm_block_search_menu().
Referenced by WM_OT_search_menu().
static int wm_search_menu_poll (bContext * C) [static]
Definition at line 1464 of file wm_operators.c.
References CTX_data_edit_object(), CTX_wm_area(), CTX_wm_window(), NULL, OB_FONT, SPACE_CONSOLE, SPACE_TEXT, ScrArea::spacetype, and Object::type.
Referenced by WM_OT_search_menu().
static int wm_splash_invoke (bContext * C, wmOperator * UNUSEDop, wmEvent * UNUSEDevent) [static]
Definition at line 1359 of file wm_operators.c.
References NULL, OPERATOR_FINISHED, uiPupBlock(), and wm_block_create_splash().
Referenced by WM_OT_splash().
void wm_tweakevent_test (bContext * C, wmEvent * event, int action)
Definition at line 2618 of file wm_operators.c.
References CTX_wm_region(), CTX_wm_window(), ELEM3, KM_PRESS, LEFTMOUSE, MIDDLEMOUSE, NULL, RIGHTMOUSE, wmWindow::tweak, tweak_gesture_modal(), wmEvent::type, wmEvent::val, WM_gesture_end(), WM_gesture_new(), WM_GESTURE_TWEAK, and WM_HANDLER_BREAK.
Referenced by wm_event_do_handlers().
void wm_window_keymap (wmKeyConfig * keyconf)
Definition at line 3886 of file wm_operators.c.
References DKEY, F10KEY, F11KEY, F12KEY, F1KEY, F2KEY, F3KEY, F4KEY, F5KEY, F6KEY, F7KEY, F8KEY, F9KEY, FALSE, gesture_border_modal_keymap(), gesture_circle_modal_keymap(), gesture_straightline_modal_keymap(), gesture_zoom_border_modal_keymap(), KM_ALT, KM_CTRL, KM_OSKEY, KM_PRESS, KM_SHIFT, NDOF_BUTTON_MENU, NDOF_BUTTON_MINUS, NDOF_BUTTON_PLUS, NKEY, OKEY, wmKeyMapItem::ptr, QKEY, RNA_boolean_set(), RNA_string_set(), SKEY, SPACEKEY, TKEY, TRUE, UKEY, WKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), and WM_keymap_verify_item().
Referenced by WM_keymap_init().
Variable Documentation
GHash* global_ops_hash = NULL [static]
Definition at line 105 of file wm_operators.c.
EnumPropertyItem redraw_timer_type_items[] [static]
Initial value:
 {
    {0, "DRAW", 0, "Draw Region", "Draw Region"},
    {1, "DRAW_SWAP", 0, "Draw Region + Swap", "Draw Region and Swap"},
    {2, "DRAW_WIN", 0, "Draw Window", "Draw Window"},
    {3, "DRAW_WIN_SWAP", 0, "Draw Window + Swap", "Draw Window and Swap"},
    {4, "ANIM_STEP", 0, "Anim Step", "Animation Steps"},
    {5, "ANIM_PLAY", 0, "Anim Play", "Animation Playback"},
    {6, "UNDO", 0, "Undo/Redo", "Undo/Redo"},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 3449 of file wm_operators.c.
const int WM_RADIAL_CONTROL_DISPLAY_SIZE = 200 [static]
Definition at line 2923 of file wm_operators.c.
Referenced by radial_control_modal(), and radial_control_paint_cursor().