Blender: btBoxBoxCollisionAlgorithm Class Reference
btBoxBoxCollisionAlgorithm Class Reference
box-box collision detection
#include <btBoxBoxCollisionAlgorithm.h>
Classes
struct CreateFunc
Public Member Functions
btBoxBoxCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo &ci)
virtual void processCollision (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
virtual btScalar calculateTimeOfImpact (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
btBoxBoxCollisionAlgorithm (btPersistentManifold *mf, const btCollisionAlgorithmConstructionInfo &ci, btCollisionObject *body0, btCollisionObject *body1)
virtual ~btBoxBoxCollisionAlgorithm ()
virtual void getAllContactManifolds (btManifoldArray &manifoldArray)
Detailed Description
box-box collision detection
Definition at line 27 of file btBoxBoxCollisionAlgorithm.h.
Constructor & Destructor Documentation
btBoxBoxCollisionAlgorithm::btBoxBoxCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo & ci) [inline]
Definition at line 33 of file btBoxBoxCollisionAlgorithm.h.
Referenced by btBoxBoxCollisionAlgorithm::CreateFunc::CreateCollisionAlgorithm().
btBoxBoxCollisionAlgorithm::btBoxBoxCollisionAlgorithm (btPersistentManifold * mf, const btCollisionAlgorithmConstructionInfo & ci, btCollisionObject * body0, btCollisionObject * body1)
Definition at line 24 of file btBoxBoxCollisionAlgorithm.cpp.
References btDispatcher::getNewManifold(), btCollisionAlgorithm::m_dispatcher, and btDispatcher::needsCollision().
btBoxBoxCollisionAlgorithm::~btBoxBoxCollisionAlgorithm () [virtual]
Definition at line 36 of file btBoxBoxCollisionAlgorithm.cpp.
References btCollisionAlgorithm::m_dispatcher, and btDispatcher::releaseManifold().
Member Function Documentation
btScalar btBoxBoxCollisionAlgorithm::calculateTimeOfImpact (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Implements btCollisionAlgorithm.
Definition at line 81 of file btBoxBoxCollisionAlgorithm.cpp.
virtual void btBoxBoxCollisionAlgorithm::getAllContactManifolds (btManifoldArray & manifoldArray) [inline, virtual]
Implements btCollisionAlgorithm.
Definition at line 44 of file btBoxBoxCollisionAlgorithm.h.
References btAlignedObjectArray< T >::push_back().
void btBoxBoxCollisionAlgorithm::processCollision (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
report a contact. internally this will be kept persistent, and contact reduction is done
Implements btCollisionAlgorithm.
Definition at line 45 of file btBoxBoxCollisionAlgorithm.cpp.
References BT_LARGE_FLOAT, btBoxBoxDetector::getClosestPoints(), btDispatcherInfo::m_debugDraw, btDiscreteCollisionDetectorInterface::ClosestPointInput::m_maximumDistanceSquared, btDiscreteCollisionDetectorInterface::ClosestPointInput::m_transformA, btDiscreteCollisionDetectorInterface::ClosestPointInput::m_transformB, btManifoldResult::refreshContactPoints(), and btManifoldResult::setPersistentManifold().
The documentation for this class was generated from the following files:
btBoxBoxCollisionAlgorithm.h
btBoxBoxCollisionAlgorithm.cpp