Blender: seqcache.c File Reference
seqcache.c File Reference
blenkernel
#include <stddef.h>
#include "BLO_sys_types.h"
#include "MEM_guardedalloc.h"
#include "DNA_sequence_types.h"
#include "BKE_sequencer.h"
#include "IMB_moviecache.h"
Classes
struct seqCacheKey
Typedefs
typedef struct seqCacheKey seqCacheKey
Functions
static unsigned int seqcache_hashhash (const void *key_)
static int seqcache_hashcmp (const void *a_, const void *b_)
void seq_stripelem_cache_destruct (void)
void seq_stripelem_cache_cleanup (void)
struct ImBuf * seq_stripelem_cache_get (SeqRenderData context, struct Sequence *seq, float cfra, seq_stripelem_ibuf_t type)
void seq_stripelem_cache_put (SeqRenderData context, struct Sequence *seq, float cfra, seq_stripelem_ibuf_t type, struct ImBuf *i)
Variables
static struct MovieCache * moviecache = NULL
Detailed Description
Definition in file seqcache.c.
Typedef Documentation
typedef struct seqCacheKey seqCacheKey
Function Documentation
void seq_stripelem_cache_cleanup (void)
Definition at line 98 of file seqcache.c.
References IMB_moviecache_create(), IMB_moviecache_free(), NULL, seqcache_hashcmp(), and seqcache_hashhash().
Referenced by free_imbuf_seq(), screen_render_exec(), and screen_render_invoke().
void seq_stripelem_cache_destruct (void)
Definition at line 92 of file seqcache.c.
References IMB_moviecache_free().
Referenced by free_blender().
struct ImBuf* seq_stripelem_cache_get (SeqRenderData context, struct Sequence * seq, float cfra, seq_stripelem_ibuf_t type) [read]
Definition at line 107 of file seqcache.c.
References seqCacheKey::cfra, seqCacheKey::context, IMB_moviecache_get(), NULL, seqCacheKey::seq, Sequence::start, and seqCacheKey::type.
Referenced by copy_from_ibuf_still(), seq_render_strip(), and seq_render_strip_stack().
void seq_stripelem_cache_put (SeqRenderData context, struct Sequence * seq, float cfra, seq_stripelem_ibuf_t type, struct ImBuf * i)
Definition at line 126 of file seqcache.c.
References seqCacheKey::cfra, seqCacheKey::context, IMB_moviecache_create(), IMB_moviecache_put(), NULL, seqCacheKey::seq, seqcache_hashcmp(), seqcache_hashhash(), Sequence::start, and seqCacheKey::type.
Referenced by copy_to_ibuf_still(), seq_render_strip(), and seq_render_strip_stack().
static int seqcache_hashcmp (const void * a_, const void * b_) [static]
Definition at line 63 of file seqcache.c.
References seqCacheKey::cfra, seqCacheKey::context, seqCacheKey::seq, seq_cmp_render_data(), and seqCacheKey::type.
Referenced by seq_stripelem_cache_cleanup(), and seq_stripelem_cache_put().
static unsigned int seqcache_hashhash (const void * key_) [static]
Definition at line 51 of file seqcache.c.
References seqCacheKey::cfra, seqCacheKey::context, seqCacheKey::seq, seq_hash_render_data(), and seqCacheKey::type.
Referenced by seq_stripelem_cache_cleanup(), and seq_stripelem_cache_put().
Variable Documentation
struct MovieCache* moviecache = NULL [static]
Definition at line 49 of file seqcache.c.