Blender: DerivedMesh.c File Reference
DerivedMesh.c File Reference
blenkernel
#include <string.h>
#include <limits.h>
#include "MEM_guardedalloc.h"
#include "DNA_cloth_types.h"
#include "DNA_key_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_armature_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_memarena.h"
#include "BLI_array.h"
#include "BLI_pbvh.h"
#include "BLI_utildefines.h"
#include "BLI_linklist.h"
#include "BLF_translation.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_displist.h"
#include "BKE_key.h"
#include "BKE_modifier.h"
#include "BKE_mesh.h"
#include "BKE_object.h"
#include "BKE_paint.h"
#include "BKE_texture.h"
#include "BKE_multires.h"
#include "BKE_armature.h"
#include "BKE_particle.h"
#include "BKE_tessmesh.h"
#include "BKE_bvhutils.h"
#include "BKE_deform.h"
#include "BKE_global.h"
#include "BLO_sys_types.h"
#include "GL/glew.h"
#include "GPU_buffers.h"
#include "GPU_draw.h"
#include "GPU_extensions.h"
#include "GPU_material.h"
#include "mikktspace.h"
#include "BLI_dynstr.h"
Classes
struct SGLSLMeshToTangent
Enumerations
enum { CALC_WP_MULTIPAINT = (1<<0), CALC_WP_AUTO_NORMALIZE = (1<<1) }
Functions
static void add_shapekey_layers (DerivedMesh *dm, Mesh *me, Object *ob)
static void shapekey_layers_to_keyblocks (DerivedMesh *dm, Mesh *me, int actshape_uid)
static MVert * dm_getVertArray (DerivedMesh *dm)
static MEdge * dm_getEdgeArray (DerivedMesh *dm)
static MFace * dm_getTessFaceArray (DerivedMesh *dm)
static MLoop * dm_getLoopArray (DerivedMesh *dm)
static MPoly * dm_getPolyArray (DerivedMesh *dm)
static MVert * dm_dupVertArray (DerivedMesh *dm)
static MEdge * dm_dupEdgeArray (DerivedMesh *dm)
static MFace * dm_dupFaceArray (DerivedMesh *dm)
static MLoop * dm_dupLoopArray (DerivedMesh *dm)
static MPoly * dm_dupPolyArray (DerivedMesh *dm)
static CustomData * dm_getVertCData (DerivedMesh *dm)
static CustomData * dm_getEdgeCData (DerivedMesh *dm)
static CustomData * dm_getTessFaceCData (DerivedMesh *dm)
static CustomData * dm_getLoopCData (DerivedMesh *dm)
static CustomData * dm_getPolyCData (DerivedMesh *dm)
void DM_init_funcs (DerivedMesh *dm)
void DM_init (DerivedMesh *dm, DerivedMeshType type, int numVerts, int numEdges, int numTessFaces, int numLoops, int numPolys)
void DM_from_template (DerivedMesh *dm, DerivedMesh *source, DerivedMeshType type, int numVerts, int numEdges, int numTessFaces, int numLoops, int numPolys)
int DM_release (DerivedMesh *dm)
void DM_DupPolys (DerivedMesh *source, DerivedMesh *target)
void DM_ensure_tessface (DerivedMesh *dm)
void DM_update_tessface_data (DerivedMesh *dm)
void DM_to_mesh (DerivedMesh *dm, Mesh *me, Object *ob)
void DM_to_meshkey (DerivedMesh *dm, Mesh *me, KeyBlock *kb)
void DM_set_only_copy (DerivedMesh *dm, CustomDataMask mask)
void DM_add_vert_layer (DerivedMesh *dm, int type, int alloctype, void *layer)
void DM_add_edge_layer (DerivedMesh *dm, int type, int alloctype, void *layer)
void DM_add_tessface_layer (DerivedMesh *dm, int type, int alloctype, void *layer)
void DM_add_loop_layer (DerivedMesh *dm, int type, int alloctype, void *layer)
void DM_add_poly_layer (DerivedMesh *dm, int type, int alloctype, void *layer)
void * DM_get_vert_data (DerivedMesh *dm, int index, int type)
void * DM_get_edge_data (DerivedMesh *dm, int index, int type)
void * DM_get_tessface_data (DerivedMesh *dm, int index, int type)
void * DM_get_vert_data_layer (DerivedMesh *dm, int type)
void * DM_get_edge_data_layer (DerivedMesh *dm, int type)
void * DM_get_tessface_data_layer (DerivedMesh *dm, int type)
void * DM_get_poly_data_layer (DerivedMesh *dm, int type)
void * DM_get_loop_data_layer (DerivedMesh *dm, int type)
void DM_set_vert_data (DerivedMesh *dm, int index, int type, void *data)
void DM_set_edge_data (DerivedMesh *dm, int index, int type, void *data)
void DM_set_tessface_data (DerivedMesh *dm, int index, int type, void *data)
void DM_copy_vert_data (DerivedMesh *source, DerivedMesh *dest, int source_index, int dest_index, int count)
void DM_copy_edge_data (DerivedMesh *source, DerivedMesh *dest, int source_index, int dest_index, int count)
void DM_copy_tessface_data (DerivedMesh *source, DerivedMesh *dest, int source_index, int dest_index, int count)
void DM_copy_loop_data (DerivedMesh *source, DerivedMesh *dest, int source_index, int dest_index, int count)
void DM_copy_poly_data (DerivedMesh *source, DerivedMesh *dest, int source_index, int dest_index, int count)
void DM_free_vert_data (struct DerivedMesh *dm, int index, int count)
void DM_free_edge_data (struct DerivedMesh *dm, int index, int count)
void DM_free_tessface_data (struct DerivedMesh *dm, int index, int count)
void DM_free_loop_data (struct DerivedMesh *dm, int index, int count)
void DM_free_poly_data (struct DerivedMesh *dm, int index, int count)
void DM_interp_vert_data (DerivedMesh *source, DerivedMesh *dest, int *src_indices, float *weights, int count, int dest_index)
void DM_interp_edge_data (DerivedMesh *source, DerivedMesh *dest, int *src_indices, float *weights, EdgeVertWeight *vert_weights, int count, int dest_index)
void DM_interp_tessface_data (DerivedMesh *source, DerivedMesh *dest, int *src_indices, float *weights, FaceVertWeight *vert_weights, int count, int dest_index)
void DM_swap_tessface_data (DerivedMesh *dm, int index, const int *corner_indices)
void DM_interp_loop_data (DerivedMesh *source, DerivedMesh *dest, int *src_indices, float *weights, int count, int dest_index)
void DM_interp_poly_data (DerivedMesh *source, DerivedMesh *dest, int *src_indices, float *weights, int count, int dest_index)
DerivedMesh * mesh_create_derived (Mesh *me, Object *ob, float(*vertCos)[3])
DerivedMesh * mesh_create_derived_for_modifier (Scene *scene, Object *ob, ModifierData *md, int build_shapekey_layers)
static float * get_editbmesh_orco_verts (BMEditMesh *em)
static void * get_orco_coords_dm (Object *ob, BMEditMesh *em, int layer, int *free)
static DerivedMesh * create_orco_dm (Object *ob, Mesh *me, BMEditMesh *em, int layer)
static void add_orco_dm (Object *ob, BMEditMesh *em, DerivedMesh *dm, DerivedMesh *orcodm, int layer)
void weight_to_rgb (float r_rgb[3], const float weight)
static void weightpaint_color (unsigned char r_col[4], ColorBand *coba, const float input)
static void calc_weightpaint_vert_color (unsigned char r_col[4], MDeformVert *dv, ColorBand *coba, const int defbase_tot, const int defbase_act, const char *dg_flags, const int selected, const int draw_flag)
void vDM_ColorBand_store (ColorBand *coba)
static unsigned char * calc_weightpaint_vert_array (Object *ob, DerivedMesh *dm, int const draw_flag, ColorBand *coba)
static unsigned char * calc_colors_from_weights_array (const int num, float *weights)
void DM_update_weight_mcol (Object *ob, DerivedMesh *dm, int const draw_flag, float *weights, int num, const int *indices)
static void add_shapekey_layers (DerivedMesh *dm, Mesh *me, Object *UNUSED(ob))
static void mesh_calc_modifiers (Scene *scene, Object *ob, float(*inputVertexCos)[3], DerivedMesh **deform_r, DerivedMesh **final_r, int useRenderParams, int useDeform, int needMapping, CustomDataMask dataMask, int index, int useCache, int build_shapekey_layers)
float(* editbmesh_get_vertex_cos (BMEditMesh *em, int *numVerts_r))[3]
int editbmesh_modifier_is_enabled (Scene *scene, ModifierData *md, DerivedMesh *dm)
static void editbmesh_calc_modifiers (Scene *scene, Object *ob, BMEditMesh *em, DerivedMesh **cage_r, DerivedMesh **final_r, CustomDataMask dataMask)
static void clear_mesh_caches (Object *ob)
static void mesh_build_data (Scene *scene, Object *ob, CustomDataMask dataMask, int build_shapekey_layers)
static void editbmesh_build_data (Scene *scene, Object *obedit, BMEditMesh *em, CustomDataMask dataMask)
void makeDerivedMesh (Scene *scene, Object *ob, BMEditMesh *em, CustomDataMask dataMask, int build_shapekey_layers)
DerivedMesh * mesh_get_derived_final (Scene *scene, Object *ob, CustomDataMask dataMask)
DerivedMesh * mesh_get_derived_deform (Scene *scene, Object *ob, CustomDataMask dataMask)
DerivedMesh * mesh_create_derived_render (Scene *scene, Object *ob, CustomDataMask dataMask)
DerivedMesh * mesh_create_derived_index_render (Scene *scene, Object *ob, CustomDataMask dataMask, int index)
DerivedMesh * mesh_create_derived_view (Scene *scene, Object *ob, CustomDataMask dataMask)
DerivedMesh * mesh_create_derived_no_deform (Scene *scene, Object *ob, float(*vertCos)[3], CustomDataMask dataMask)
DerivedMesh * mesh_create_derived_no_virtual (Scene *scene, Object *ob, float(*vertCos)[3], CustomDataMask dataMask)
DerivedMesh * mesh_create_derived_physics (Scene *scene, Object *ob, float(*vertCos)[3], CustomDataMask dataMask)
DerivedMesh * mesh_create_derived_no_deform_render (Scene *scene, Object *ob, float(*vertCos)[3], CustomDataMask dataMask)
DerivedMesh * editbmesh_get_derived_cage_and_final (Scene *scene, Object *obedit, BMEditMesh *em, DerivedMesh **final_r, CustomDataMask dataMask)
DerivedMesh * editbmesh_get_derived_cage (Scene *scene, Object *obedit, BMEditMesh *em, CustomDataMask dataMask)
DerivedMesh * editbmesh_get_derived_base (Object *obedit, BMEditMesh *em)
static void make_vertexcosnos__mapFunc (void *userData, int index, const float co[3], const float no_f[3], const short no_s[3])
float * mesh_get_mapped_verts_nors (Scene *scene, Object *ob)
static int GetNumFaces (const SMikkTSpaceContext *pContext)
static int GetNumVertsOfFace (const SMikkTSpaceContext *pContext, const int face_num)
static void GetPosition (const SMikkTSpaceContext *pContext, float fPos[], const int face_num, const int vert_index)
static void GetTextureCoordinate (const SMikkTSpaceContext *pContext, float fUV[], const int face_num, const int vert_index)
static void GetNormal (const SMikkTSpaceContext *pContext, float fNorm[], const int face_num, const int vert_index)
static void SetTSpace (const SMikkTSpaceContext *pContext, const float fvTangent[], const float fSign, const int face_num, const int iVert)
void DM_add_tangent_layer (DerivedMesh *dm)
void DM_calc_auto_bump_scale (DerivedMesh *dm)
void DM_vertex_attributes_from_gpu (DerivedMesh *dm, GPUVertexAttribs *gattribs, DMVertexAttribs *attribs)
void DM_set_object_boundbox (Object *ob, DerivedMesh *dm)
void DM_init_origspace (DerivedMesh *dm)
static void dm_debug_info_layers (DynStr *dynstr, DerivedMesh *dm, void *(*getElemDataArray)(DerivedMesh *, int))
char * DM_debug_info (DerivedMesh *dm)
void DM_debug_print (DerivedMesh *dm)
Variables
static ColorBand * stored_cb = NULL
Detailed Description
Definition in file DerivedMesh.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
CALC_WP_MULTIPAINT
CALC_WP_AUTO_NORMALIZE
Definition at line 989 of file DerivedMesh.c.
Function Documentation
static void add_orco_dm (Object * ob, BMEditMesh * em, DerivedMesh * dm, DerivedMesh * orcodm, int layer) [static]
Definition at line 913 of file DerivedMesh.c.
References CD_CALLOC, CD_ORCO, Object::data, DM_add_vert_layer(), DM_get_vert_data_layer(), get_orco_coords_dm(), DerivedMesh::getNumVerts, DerivedMesh::getVertCos, MEM_callocN(), MEM_freeN(), NULL, and transform_mesh_orco_verts().
Referenced by editbmesh_calc_modifiers(), and mesh_calc_modifiers().
static void add_shapekey_layers (DerivedMesh * dm, Mesh * me, Object * ob) [static]
Referenced by mesh_calc_modifiers(), and mesh_create_derived_for_modifier().
static void add_shapekey_layers (DerivedMesh * dm, Mesh * me, Object * UNUSEDob) [static]
Definition at line 1308 of file DerivedMesh.c.
References Key::block, CD_ASSIGN, CD_SHAPEKEY, CustomData_add_layer_named(), CustomData_get_layer_index_n(), KeyBlock::data, ListBase::first, DerivedMesh::getNumVerts, i, Mesh::id, if(), Mesh::key, CustomData::layers, MEM_callocN(), MEM_mallocN(), KeyBlock::name, ID::name, KeyBlock::next, DerivedMesh::numVertData, KeyBlock::totelem, Mesh::totvert, KeyBlock::uid, CustomDataLayer::uid, and DerivedMesh::vertData.
static unsigned char* calc_colors_from_weights_array (const int num, float * weights) [static]
Definition at line 1116 of file DerivedMesh.c.
References i, MEM_mallocN(), NULL, and weightpaint_color().
Referenced by DM_update_weight_mcol().
static unsigned char* calc_weightpaint_vert_array (Object * ob, DerivedMesh * dm, int const draw_flag, ColorBand * coba) [static]
Definition at line 1080 of file DerivedMesh.c.
References Object::actdef, BLI_countlist(), calc_weightpaint_vert_color(), CD_MDEFORMVERT, Object::defbase, DM_get_vert_data_layer(), fill_vn_i(), get_selected_defgroups(), DerivedMesh::getNumVerts, i, MEM_freeN(), MEM_mallocN(), and weightpaint_color().
Referenced by DM_update_weight_mcol().
static void calc_weightpaint_vert_color (unsigned char r_col[4], MDeformVert * dv, ColorBand * coba, const int defbase_tot, const int defbase_act, const char * dg_flags, const int selected, const int draw_flag) [static]
Definition at line 1014 of file DerivedMesh.c.
References CALC_WP_AUTO_NORMALIZE, CALC_WP_MULTIPAINT, CLAMP(), MDeformWeight::def_nr, defvert_find_weight(), MDeformVert::dw, FALSE, i, MDeformVert::totweight, TRUE, MDeformWeight::weight, and weightpaint_color().
Referenced by calc_weightpaint_vert_array().
static void clear_mesh_caches (Object * ob) [static]
Definition at line 2086 of file DerivedMesh.c.
References Object::bb, Mesh::bb, Object::data, Object::derivedDeform, Object::derivedFinal, Object::disp, freedisplist(), MEM_freeN(), DerivedMesh::needsFree, NULL, object_sculpt_modifiers_changed(), DerivedMesh::release, and Object::sculpt.
Referenced by editbmesh_build_data(), and mesh_build_data().
static DerivedMesh* create_orco_dm (Object * ob, Mesh * me, BMEditMesh * em, int layer) [static]
Definition at line 892 of file DerivedMesh.c.
References CDDM_apply_vert_coords(), CDDM_calc_normals(), CDDM_from_BMEditMesh(), CDDM_from_mesh(), FALSE, get_orco_coords_dm(), and MEM_freeN().
Referenced by editbmesh_calc_modifiers(), and mesh_calc_modifiers().
void DM_add_edge_layer (DerivedMesh * dm, int type, int alloctype, void * layer)
Definition at line 587 of file DerivedMesh.c.
References CustomData_add_layer(), DerivedMesh::edgeData, and DerivedMesh::numEdgeData.
Referenced by ccgDM_get_edge_data_layer(), and mesh_calc_modifiers().
void DM_add_loop_layer (DerivedMesh * dm, int type, int alloctype, void * layer)
Definition at line 597 of file DerivedMesh.c.
References CustomData_add_layer(), DerivedMesh::loopData, and DerivedMesh::numLoopData.
Referenced by editbmesh_calc_modifiers(), and mesh_calc_modifiers().
void DM_add_poly_layer (DerivedMesh * dm, int type, int alloctype, void * layer)
Definition at line 602 of file DerivedMesh.c.
References CustomData_add_layer(), DerivedMesh::numPolyData, and DerivedMesh::polyData.
Referenced by mesh_calc_modifiers().
void DM_add_tangent_layer (DerivedMesh * dm)
Definition at line 2456 of file DerivedMesh.c.
References BLI_memarena_free(), BLI_memarena_new(), BLI_MEMARENA_STD_BUFSIZE, BLI_memarena_use_calloc(), CD_CALLOC, CD_MTFACE, CD_NORMAL, CD_ORCO, CD_TANGENT, MVert::co, CustomData_get_layer_index(), DM_add_tessface_layer(), DM_get_tessface_data_layer(), DerivedMesh::faceData, find_vertex_tangent(), genTangSpaceDefault(), GetNormal(), GetNumFaces(), DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, GetNumVertsOfFace(), GetPosition(), DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceDataArray, GetTextureCoordinate(), DerivedMesh::getVertArray, DerivedMesh::getVertDataArray, i, len(), SMikkTSpaceInterface::m_getNormal, SMikkTSpaceInterface::m_getNumFaces, SMikkTSpaceInterface::m_getNumVerticesOfFace, SMikkTSpaceInterface::m_getPosition, SMikkTSpaceInterface::m_getTexCoord, SMikkTSpaceContext::m_pInterface, SMikkTSpaceContext::m_pUserData, SMikkTSpaceInterface::m_setTSpaceBasic, map_to_sphere(), MEM_callocN(), MEM_freeN(), SGLSLMeshToTangent::mface, SGLSLMeshToTangent::mtface, SGLSLMeshToTangent::mvert, normal_quad_v3(), normal_tri_v3(), normalize_v3_v3(), NULL, SGLSLMeshToTangent::numTessFaces, SGLSLMeshToTangent::orco, SGLSLMeshToTangent::precomputedFaceNormals, SetTSpace(), sum_or_add_vertex_tangent(), SGLSLMeshToTangent::tangent, tangent_from_uv(), MTFace::uv, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by BL_ConvertMesh(), DM_vertex_attributes_from_gpu(), do_multires_bake(), and init_render_mesh().
void DM_add_tessface_layer (DerivedMesh * dm, int type, int alloctype, void * layer)
Definition at line 592 of file DerivedMesh.c.
References CustomData_add_layer(), DerivedMesh::faceData, and DerivedMesh::numTessFaceData.
Referenced by ccgDM_get_tessface_data_layer(), DM_add_tangent_layer(), emDM_getTessFaceDataArray(), and getCCGDerivedMesh().
void DM_add_vert_layer (DerivedMesh * dm, int type, int alloctype, void * layer)
Definition at line 582 of file DerivedMesh.c.
References CustomData_add_layer(), DerivedMesh::numVertData, and DerivedMesh::vertData.
Referenced by add_orco_dm(), ccgDM_get_vert_data_layer(), distribute_threads_init_data(), do_hair_dynamics(), get_dm(), getEditDerivedBMesh(), and mesh_calc_modifiers().
void DM_calc_auto_bump_scale (DerivedMesh * dm)
Definition at line 2601 of file DerivedMesh.c.
References DerivedMesh::auto_bump_scale, CD_MTFACE, MVert::co, copy_v2_v2(), cross_v3_v3v3(), dot_v2v2(), dot_v3v3(), equals_v2v2(), equals_v3v3(), fabsf, DerivedMesh::getNumTessFaces, DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVertArray, i, len_v3(), norm(), offs, sqrtf, sub_v2_v2v2(), sub_v3_v3v3(), MTFace::uv, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by DM_vertex_attributes_from_gpu().
void DM_copy_edge_data (DerivedMesh * source, DerivedMesh * dest, int source_index, int dest_index, int count)
Definition at line 678 of file DerivedMesh.c.
References CustomData_copy_data(), and DerivedMesh::edgeData.
Referenced by applyModifier(), and doMirrorOnAxis().
void DM_copy_loop_data (DerivedMesh * source, DerivedMesh * dest, int source_index, int dest_index, int count)
Definition at line 692 of file DerivedMesh.c.
References CustomData_copy_data(), and DerivedMesh::loopData.
Referenced by applyModifier(), and doMirrorOnAxis().
void DM_copy_poly_data (DerivedMesh * source, DerivedMesh * dest, int source_index, int dest_index, int count)
Definition at line 699 of file DerivedMesh.c.
References CustomData_copy_data(), and DerivedMesh::polyData.
Referenced by applyModifier(), and doMirrorOnAxis().
void DM_copy_tessface_data (DerivedMesh * source, DerivedMesh * dest, int source_index, int dest_index, int count)
Definition at line 685 of file DerivedMesh.c.
References CustomData_copy_data(), and DerivedMesh::faceData.
Referenced by explodeMesh(), and get_dface().
void DM_copy_vert_data (DerivedMesh * source, DerivedMesh * dest, int source_index, int dest_index, int count)
Definition at line 671 of file DerivedMesh.c.
References CustomData_copy_data(), and DerivedMesh::vertData.
Referenced by applyModifier(), cutEdges(), doMirrorOnAxis(), explodeMesh(), and getCCGDerivedMesh().
char* DM_debug_info (DerivedMesh * dm)
Definition at line 3122 of file DerivedMesh.c.
References BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), dm_debug_info_layers(), DM_get_loop_data_layer(), DM_get_poly_data_layer(), DM_TYPE_CCGDM, DM_TYPE_CDDM, and DM_TYPE_EDITBMESH.
Referenced by DM_debug_print().
static void dm_debug_info_layers (DynStr * dynstr, DerivedMesh * dm, void *(*)(DerivedMesh *, int) getElemDataArray) [static]
Definition at line 3102 of file DerivedMesh.c.
References BLI_dynstr_appendf(), CD_NUMTYPES, CustomData_file_write_info(), CustomData_layertype_name(), CustomData_sizeof(), MEM_allocN_len(), and size().
Referenced by DM_debug_info().
void DM_debug_print (DerivedMesh * dm)
Definition at line 3170 of file DerivedMesh.c.
References DM_debug_info(), MEM_freeN(), and str.
Referenced by ConvertCSGDescriptorsToDerivedMesh().
static MEdge* dm_dupEdgeArray (DerivedMesh * dm) [static]
Definition at line 181 of file DerivedMesh.c.
References DerivedMesh::copyEdgeArray, DerivedMesh::getNumEdges, and MEM_callocN().
Referenced by DM_init_funcs().
static MFace* dm_dupFaceArray (DerivedMesh * dm) [static]
Definition at line 191 of file DerivedMesh.c.
References DerivedMesh::copyTessFaceArray, DerivedMesh::getNumTessFaces, and MEM_callocN().
Referenced by DM_init_funcs().
static MLoop* dm_dupLoopArray (DerivedMesh * dm) [static]
Definition at line 201 of file DerivedMesh.c.
References DerivedMesh::copyLoopArray, DerivedMesh::getNumLoops, and MEM_callocN().
Referenced by DM_init_funcs().
static MPoly* dm_dupPolyArray (DerivedMesh * dm) [static]
Definition at line 211 of file DerivedMesh.c.
References DerivedMesh::copyPolyArray, DerivedMesh::getNumPolys, and MEM_callocN().
Referenced by DM_init_funcs().
void DM_DupPolys (DerivedMesh * source, DerivedMesh * target)
Definition at line 345 of file DerivedMesh.c.
References CD_ASSIGN, CD_DUPLICATE, CD_MASK_DERIVEDMESH, CD_MLOOP, CD_MPOLY, CustomData_add_layer(), CustomData_copy(), CustomData_free(), CustomData_has_layer(), DerivedMesh::dupLoopArray, DerivedMesh::dupPolyArray, DerivedMesh::loopData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, and DerivedMesh::polyData.
Referenced by cddm_copy_ex().
static MVert* dm_dupVertArray (DerivedMesh * dm) [static]
Definition at line 171 of file DerivedMesh.c.
References DerivedMesh::copyVertArray, DerivedMesh::getNumVerts, and MEM_callocN().
Referenced by DM_init_funcs().
void DM_ensure_tessface (DerivedMesh * dm)
Definition at line 369 of file DerivedMesh.c.
References BLI_assert, CD_POLYINDEX, CustomData_has_layer(), DerivedMesh::dirty, DM_DIRTY_TESS_CDLAYERS, DM_update_tessface_data(), DerivedMesh::faceData, DerivedMesh::getNumPolys, DerivedMesh::getNumTessFaces, DerivedMesh::recalcTessellation, and DerivedMesh::type.
Referenced by applyModifier(), BL_ConvertMesh(), connect_hair(), ConvertCSGDescriptorsToDerivedMesh(), curve_calc_modifiers_post(), deformVerts(), distribute_threads_init_data(), dynamicPaint_Modifier_do(), editbmesh_calc_modifiers(), particle_intersect_dm(), particle_system_update(), and CcdShapeConstructionInfo::SetMesh().
void DM_free_edge_data (struct DerivedMesh * dm, int index, int count)
Definition at line 711 of file DerivedMesh.c.
References CustomData_free_elem(), and DerivedMesh::edgeData.
void DM_free_loop_data (struct DerivedMesh * dm, int index, int count)
Definition at line 721 of file DerivedMesh.c.
References CustomData_free_elem(), and DerivedMesh::loopData.
void DM_free_poly_data (struct DerivedMesh * dm, int index, int count)
Definition at line 726 of file DerivedMesh.c.
References CustomData_free_elem(), and DerivedMesh::polyData.
void DM_free_tessface_data (struct DerivedMesh * dm, int index, int count)
Definition at line 716 of file DerivedMesh.c.
References CustomData_free_elem(), and DerivedMesh::faceData.
void DM_free_vert_data (struct DerivedMesh * dm, int index, int count)
Definition at line 706 of file DerivedMesh.c.
References CustomData_free_elem(), and DerivedMesh::vertData.
void DM_from_template (DerivedMesh * dm, DerivedMesh * source, DerivedMeshType type, int numVerts, int numEdges, int numTessFaces, int numLoops, int numPolys)
Definition at line 293 of file DerivedMesh.c.
References CD_CALLOC, CD_MASK_DERIVEDMESH, CustomData_copy(), DerivedMesh::dirty, DM_init_funcs(), DerivedMesh::edgeData, DerivedMesh::faceData, DerivedMesh::loopData, DerivedMesh::needsFree, DerivedMesh::numEdgeData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, DerivedMesh::numVertData, DerivedMesh::polyData, DerivedMesh::type, and DerivedMesh::vertData.
Referenced by cddm_copy_ex(), CDDM_from_template(), and getCCGDerivedMesh().
void* DM_get_edge_data (DerivedMesh * dm, int index, int type)
Definition at line 612 of file DerivedMesh.c.
References CustomData_get(), and DerivedMesh::edgeData.
Referenced by ccgDM_get_edge_data(), cdDM_create(), DM_init_funcs(), and getCCGDerivedMesh().
void* DM_get_edge_data_layer (DerivedMesh * dm, int type)
Definition at line 630 of file DerivedMesh.c.
References CD_MEDGE, CustomData_get_layer(), DerivedMesh::edgeData, and DerivedMesh::getEdgeArray.
Referenced by ccgDM_get_edge_data_layer(), CDDM_calc_edges(), cdDM_create(), cdDM_drawMappedEdges(), cdDM_foreachMappedEdge(), DM_init_funcs(), and mesh_calc_modifiers().
void* DM_get_loop_data_layer (DerivedMesh * dm, int type)
Definition at line 651 of file DerivedMesh.c.
References CustomData_get_layer(), and DerivedMesh::loopData.
Referenced by DM_debug_info().
void* DM_get_poly_data_layer (DerivedMesh * dm, int type)
Definition at line 646 of file DerivedMesh.c.
References CustomData_get_layer(), and DerivedMesh::polyData.
Referenced by applyModifier(), DM_debug_info(), getCCGDerivedMesh(), mesh_calc_modifiers(), and ss_sync_from_derivedmesh().
void* DM_get_tessface_data (DerivedMesh * dm, int index, int type)
Definition at line 617 of file DerivedMesh.c.
References CustomData_get(), and DerivedMesh::faceData.
Referenced by ccgDM_get_tessface_data(), cdDM_create(), and DM_init_funcs().
void* DM_get_tessface_data_layer (DerivedMesh * dm, int type)
Definition at line 638 of file DerivedMesh.c.
References CD_MFACE, CustomData_get_layer(), DerivedMesh::faceData, and DerivedMesh::getTessFaceArray.
Referenced by add_tface_color_layer(), ccgDM_drawFacesTex_common(), ccgDM_drawUVEdges(), ccgDM_get_tessface_data_layer(), cdDM_create(), cdDM_drawFacesTex_common(), cdDM_drawMappedFaces(), cdDM_drawUVEdges(), DM_add_tangent_layer(), DM_init_funcs(), do_multires_bake(), draw_dm_faces_sel(), draw_mesh_fancy(), draw_mesh_textured_old(), emDM_getTessFaceDataArray(), getCCGDerivedMesh(), gpu_buffer_color_type(), GPU_buffer_copy_uv(), GPU_buffer_copy_uvedge(), and gpu_buffer_setup_type().
void* DM_get_vert_data (DerivedMesh * dm, int index, int type)
Definition at line 607 of file DerivedMesh.c.
References CustomData_get(), and DerivedMesh::vertData.
Referenced by ccgDM_get_vert_data(), cdDM_create(), and DM_init_funcs().
void* DM_get_vert_data_layer (DerivedMesh * dm, int type)
Definition at line 622 of file DerivedMesh.c.
References CD_MVERT, CustomData_get_layer(), DerivedMesh::getVertArray, and DerivedMesh::vertData.
Referenced by add_orco_dm(), calc_weightpaint_vert_array(), ccgDM_get_vert_data_layer(), cdDM_create(), cdDM_foreachMappedVert(), DM_init_funcs(), do_hair_dynamics(), getCCGDerivedMesh(), mesh_calc_modifiers(), psys_face_mat(), and psys_mat_hair_to_orco().
static MEdge* dm_getEdgeArray (DerivedMesh * dm) [static]
Definition at line 106 of file DerivedMesh.c.
References CD_CALLOC, CD_FLAG_TEMPORARY, CD_MEDGE, DerivedMesh::copyEdgeArray, CustomData_add_layer(), CustomData_get_layer(), CustomData_set_layer_flag(), DerivedMesh::edgeData, DerivedMesh::getNumEdges, and NULL.
Referenced by DM_init_funcs().
static CustomData* dm_getEdgeCData (DerivedMesh * dm) [static]
Definition at line 226 of file DerivedMesh.c.
References DerivedMesh::edgeData.
Referenced by DM_init_funcs().
static MLoop* dm_getLoopArray (DerivedMesh * dm) [static]
Definition at line 143 of file DerivedMesh.c.
References CD_CALLOC, CD_FLAG_TEMPORARY, CD_MLOOP, DerivedMesh::copyLoopArray, CustomData_add_layer(), CustomData_get_layer(), CustomData_set_layer_flag(), DerivedMesh::getNumLoops, DerivedMesh::loopData, and NULL.
Referenced by DM_init_funcs().
static CustomData* dm_getLoopCData (DerivedMesh * dm) [static]
Definition at line 236 of file DerivedMesh.c.
References DerivedMesh::loopData.
Referenced by DM_init_funcs().
static MPoly* dm_getPolyArray (DerivedMesh * dm) [static]
Definition at line 157 of file DerivedMesh.c.
References CD_CALLOC, CD_FLAG_TEMPORARY, CD_MPOLY, DerivedMesh::copyPolyArray, CustomData_add_layer(), CustomData_get_layer(), CustomData_set_layer_flag(), DerivedMesh::getNumPolys, NULL, and DerivedMesh::polyData.
Referenced by DM_init_funcs().
static CustomData* dm_getPolyCData (DerivedMesh * dm) [static]
Definition at line 241 of file DerivedMesh.c.
References DerivedMesh::polyData.
Referenced by DM_init_funcs().
static MFace* dm_getTessFaceArray (DerivedMesh * dm) [static]
Definition at line 120 of file DerivedMesh.c.
References CD_CALLOC, CD_FLAG_TEMPORARY, CD_MFACE, DerivedMesh::copyTessFaceArray, CustomData_add_layer(), CustomData_get_layer(), CustomData_set_layer_flag(), DerivedMesh::faceData, DerivedMesh::getNumTessFaces, and NULL.
Referenced by DM_init_funcs().
static CustomData* dm_getTessFaceCData (DerivedMesh * dm) [static]
Definition at line 231 of file DerivedMesh.c.
References DerivedMesh::faceData.
Referenced by DM_init_funcs().
static MVert* dm_getVertArray (DerivedMesh * dm) [static]
Definition at line 92 of file DerivedMesh.c.
References CD_CALLOC, CD_FLAG_TEMPORARY, CD_MVERT, DerivedMesh::copyVertArray, CustomData_add_layer(), CustomData_get_layer(), CustomData_set_layer_flag(), DerivedMesh::getNumVerts, NULL, and DerivedMesh::vertData.
Referenced by DM_init_funcs().
static CustomData* dm_getVertCData (DerivedMesh * dm) [static]
Definition at line 221 of file DerivedMesh.c.
References DerivedMesh::vertData.
Referenced by DM_init_funcs().
void DM_init (DerivedMesh * dm, DerivedMeshType type, int numVerts, int numEdges, int numTessFaces, int numLoops, int numPolys)
Definition at line 276 of file DerivedMesh.c.
References DerivedMesh::auto_bump_scale, DerivedMesh::dirty, DM_init_funcs(), DerivedMesh::needsFree, DerivedMesh::numEdgeData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, DerivedMesh::numVertData, and DerivedMesh::type.
Referenced by CDDM_from_mesh(), CDDM_new(), and getEditDerivedBMesh().
void DM_init_funcs (DerivedMesh * dm)
Definition at line 246 of file DerivedMesh.c.
References DerivedMesh::bvhCache, bvhcache_init(), dm_dupEdgeArray(), dm_dupFaceArray(), dm_dupLoopArray(), dm_dupPolyArray(), dm_dupVertArray(), DM_get_edge_data(), DM_get_edge_data_layer(), DM_get_tessface_data(), DM_get_tessface_data_layer(), DM_get_vert_data(), DM_get_vert_data_layer(), dm_getEdgeArray(), dm_getEdgeCData(), dm_getLoopArray(), dm_getLoopCData(), dm_getPolyArray(), dm_getPolyCData(), dm_getTessFaceArray(), dm_getTessFaceCData(), dm_getVertArray(), dm_getVertCData(), DerivedMesh::dupEdgeArray, DerivedMesh::dupLoopArray, DerivedMesh::dupPolyArray, DerivedMesh::dupTessFaceArray, DerivedMesh::dupVertArray, DerivedMesh::getEdgeArray, DerivedMesh::getEdgeData, DerivedMesh::getEdgeDataArray, DerivedMesh::getEdgeDataLayout, DerivedMesh::getLoopArray, DerivedMesh::getLoopDataLayout, DerivedMesh::getPolyArray, DerivedMesh::getPolyDataLayout, DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceData, DerivedMesh::getTessFaceDataArray, DerivedMesh::getTessFaceDataLayout, DerivedMesh::getVertArray, DerivedMesh::getVertData, DerivedMesh::getVertDataArray, and DerivedMesh::getVertDataLayout.
Referenced by DM_from_template(), and DM_init().
void DM_init_origspace (DerivedMesh * dm)
Definition at line 3070 of file DerivedMesh.c.
References CD_ORIGSPACE_MLOOP, copy_v2_v2(), CustomData_get_layer(), DerivedMesh::dirty, DM_DIRTY_TESS_CDLAYERS, DerivedMesh::getNumPolys, DerivedMesh::getPolyArray, i, DerivedMesh::loopData, MPoly::loopstart, MPoly::totloop, and OrigSpaceLoop::uv.
Referenced by editbmesh_calc_modifiers(), and mesh_calc_modifiers().
void DM_interp_edge_data (DerivedMesh * source, DerivedMesh * dest, int * src_indices, float * weights, EdgeVertWeight * vert_weights, int count, int dest_index)
Definition at line 739 of file DerivedMesh.c.
References CustomData_interp(), and DerivedMesh::edgeData.
void DM_interp_loop_data (DerivedMesh * source, DerivedMesh * dest, int * src_indices, float * weights, int count, int dest_index)
Definition at line 762 of file DerivedMesh.c.
References CustomData_interp(), DerivedMesh::loopData, and NULL.
void DM_interp_poly_data (DerivedMesh * source, DerivedMesh * dest, int * src_indices, float * weights, int count, int dest_index)
Definition at line 770 of file DerivedMesh.c.
References CustomData_interp(), NULL, and DerivedMesh::polyData.
void DM_interp_tessface_data (DerivedMesh * source, DerivedMesh * dest, int * src_indices, float * weights, FaceVertWeight * vert_weights, int count, int dest_index)
Definition at line 748 of file DerivedMesh.c.
References CustomData_interp(), and DerivedMesh::faceData.
void DM_interp_vert_data (DerivedMesh * source, DerivedMesh * dest, int * src_indices, float * weights, int count, int dest_index)
Definition at line 731 of file DerivedMesh.c.
References CustomData_interp(), NULL, and DerivedMesh::vertData.
Referenced by getCCGDerivedMesh().
int DM_release (DerivedMesh * dm)
Definition at line 321 of file DerivedMesh.c.
References DerivedMesh::bvhCache, bvhcache_free(), CustomData_free(), CustomData_free_temporary(), DerivedMesh::edgeData, DerivedMesh::faceData, GPU_drawobject_free(), DerivedMesh::loopData, DerivedMesh::needsFree, DerivedMesh::numEdgeData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, DerivedMesh::numVertData, DerivedMesh::polyData, and DerivedMesh::vertData.
Referenced by ccgDM_release(), cdDM_release(), and emDM_release().
void DM_set_edge_data (DerivedMesh * dm, int index, int type, void * data)
Definition at line 661 of file DerivedMesh.c.
References CustomData_set(), and DerivedMesh::edgeData.
void DM_set_object_boundbox (Object * ob, DerivedMesh * dm)
Definition at line 2873 of file DerivedMesh.c.
References Object::bb, boundbox_set_from_min_max(), DerivedMesh::getMinMax, INIT_MINMAX, max, MEM_callocN(), and min.
Referenced by editbmesh_build_data(), makeDispListCurveTypes(), and mesh_build_data().
void DM_set_only_copy (DerivedMesh * dm, CustomDataMask mask)
Definition at line 575 of file DerivedMesh.c.
References CustomData_set_only_copy(), DerivedMesh::edgeData, DerivedMesh::faceData, and DerivedMesh::vertData.
Referenced by editbmesh_calc_modifiers(), mesh_calc_modifiers(), multires_modifier_update_mdisps(), multires_subdivide(), and multiresModifier_base_apply().
void DM_set_tessface_data (DerivedMesh * dm, int index, int type, void * data)
Definition at line 666 of file DerivedMesh.c.
References CustomData_set(), and DerivedMesh::faceData.
void DM_set_vert_data (DerivedMesh * dm, int index, int type, void * data)
Definition at line 656 of file DerivedMesh.c.
References CustomData_set(), and DerivedMesh::vertData.
Referenced by getEditDerivedBMesh().
void DM_swap_tessface_data (DerivedMesh * dm, int index, const int * corner_indices)
Definition at line 757 of file DerivedMesh.c.
References CustomData_swap(), and DerivedMesh::faceData.
void DM_to_mesh (DerivedMesh * dm, Mesh * me, Object * ob)
Definition at line 461 of file DerivedMesh.c.
References BKE_mesh_tessface_calc(), BLI_findlink(), Key::block, CD_ASSIGN, CD_DUPLICATE, CD_MASK_MESH, CD_MDISPS, CD_MEDGE, CD_MLOOP, CD_MPOLY, CD_MVERT, CD_SHAPEKEY, CustomData_add_layer(), CustomData_copy(), CustomData_free(), CustomData_get_layer(), CustomData_has_layer(), DerivedMesh::dupEdgeArray, DerivedMesh::dupLoopArray, DerivedMesh::dupPolyArray, DerivedMesh::dupVertArray, DerivedMesh::edgeData, Mesh::fdata, DerivedMesh::getNumEdges, DerivedMesh::getNumLoops, DerivedMesh::getNumPolys, DerivedMesh::getNumVerts, Key::id, Mesh::id, Mesh::key, Mesh::ldata, DerivedMesh::loopData, mesh_update_customdata_pointers(), Mesh::mloop, Mesh::mpoly, ID::name, NULL, DerivedMesh::polyData, shapekey_layers_to_keyblocks(), Object::shapenr, Mesh::totedge, Mesh::totface, Mesh::totloop, Mesh::totpoly, Mesh::totvert, TRUE, KeyBlock::uid, ID::us, and DerivedMesh::vertData.
Referenced by convert_exec(), modifier_apply_obdata(), NewBooleanMesh(), and nurbs_to_mesh().
void DM_to_meshkey (DerivedMesh * dm, Mesh * me, KeyBlock * kb)
Definition at line 555 of file DerivedMesh.c.
References CD_MVERT, MVert::co, copy_v3_v3(), KeyBlock::data, Key::elemsize, DerivedMesh::getNumVerts, DerivedMesh::getVertDataArray, Mesh::key, MEM_callocN(), MEM_freeN(), KeyBlock::totelem, and Mesh::totvert.
Referenced by join_mesh_shapes_exec(), and modifier_apply_shape().
void DM_update_tessface_data (DerivedMesh * dm)
Definition at line 396 of file DerivedMesh.c.
References CD_MLOOPCOL, CD_MTEXPOLY, CD_ORIGSPACE_MLOOP, CD_POLYINDEX, CD_PREVIEW_MLOOPCOL, CustomData_from_bmeshpoly(), CustomData_get_layer(), CustomData_has_layer(), CustomData_number_of_layers(), DerivedMesh::dirty, DM_DIRTY_TESS_CDLAYERS, G, G_DEBUG, DerivedMesh::getLoopArray, DerivedMesh::getLoopDataLayout, DerivedMesh::getNumTessFaces, DerivedMesh::getPolyArray, DerivedMesh::getPolyDataLayout, DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceDataLayout, i, mesh_loops_to_mface_corners(), MLoop::v, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by DM_ensure_tessface(), and mesh_calc_modifiers().
void DM_update_weight_mcol (Object * ob, DerivedMesh * dm, int const draw_flag, float * weights, int num, const int * indices)
Definition at line 1128 of file DerivedMesh.c.
References BLI_array_declare, BLI_array_growitems, calc_colors_from_weights_array(), calc_weightpaint_vert_array(), CD_ASSIGN, CD_CALLOC, CD_PREVIEW_MCOL, CD_PREVIEW_MLOOPCOL, copy_v4_v4_char(), CustomData_add_layer(), CustomData_get_layer(), DerivedMesh::dirty, DM_DIRTY_TESS_CDLAYERS, DerivedMesh::faceData, DerivedMesh::getLoopArray, DerivedMesh::getLoopDataLayout, DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, DerivedMesh::getPolyArray, DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceDataArray, i, DerivedMesh::loopData, MPoly::loopstart, MEM_callocN(), MEM_freeN(), NULL, DerivedMesh::numPolyData, stored_cb, and MPoly::totloop.
Referenced by applyModifier(), dynamicPaint_Modifier_apply(), and mesh_calc_modifiers().
void DM_vertex_attributes_from_gpu (DerivedMesh * dm, GPUVertexAttribs * gattribs, DMVertexAttribs * attribs)
Definition at line 2746 of file DerivedMesh.c.
References DMVertexAttribs::array, DerivedMesh::auto_bump_scale, CD_MCOL, CD_MLOOPCOL, CD_MLOOPUV, CD_MTFACE, CD_ORCO, CD_TANGENT, CustomData_get_active_layer_index(), CustomData_get_layer_index(), CustomData_get_named_layer_index(), CustomDataLayer::data, DM_add_tangent_layer(), DM_calc_auto_bump_scale(), DM_TYPE_EDITBMESH, DMVertexAttribs::emOffset, DerivedMesh::getLoopDataLayout, DerivedMesh::getTessFaceDataLayout, GPUVertexAttribs::glindex, DMVertexAttribs::glIndex, GPUVertexAttribs::gltexco, DMVertexAttribs::glTexco, GPUVertexAttribs::layer, CustomData::layers, DMVertexAttribs::mcol, GPUVertexAttribs::name, NULL, CustomDataLayer::offset, DMVertexAttribs::orco, DMVertexAttribs::tang, DMVertexAttribs::tface, GPUVertexAttribs::totlayer, DMVertexAttribs::totmcol, DMVertexAttribs::totorco, DMVertexAttribs::tottang, DMVertexAttribs::tottface, DerivedMesh::type, GPUVertexAttribs::type, and DerivedMesh::vertData.
Referenced by ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), cdDM_drawMappedFacesGLSL(), cdDM_drawMappedFacesMat(), emDM_drawMappedFacesGLSL(), and emDM_drawMappedFacesMat().
static void editbmesh_build_data (Scene * scene, Object * obedit, BMEditMesh * em, CustomDataMask dataMask) [static]
Definition at line 2145 of file DerivedMesh.c.
References clear_mesh_caches(), BMEditMesh::derivedCage, BMEditMesh::derivedFinal, DM_set_object_boundbox(), editbmesh_calc_modifiers(), BMEditMesh::lastDataMask, DerivedMesh::needsFree, NULL, and DerivedMesh::release.
Referenced by editbmesh_get_derived_cage(), editbmesh_get_derived_cage_and_final(), and makeDerivedMesh().
static void editbmesh_calc_modifiers (Scene * scene, Object * ob, BMEditMesh * em, DerivedMesh ** cage_r, DerivedMesh ** final_r, CustomDataMask dataMask) [static]
Definition at line 1867 of file DerivedMesh.c.
References add_orco_dm(), ModifierTypeInfo::applyModifier, ModifierTypeInfo::applyModifierEM, BLI_linklist_free(), DerivedMesh::calcNormals, CD_CALLOC, CD_MASK_ORCO, CD_MASK_ORIGINDEX, CD_MASK_ORIGSPACE_MLOOP, CD_ORCO, CD_ORIGSPACE_MLOOP, CDDM_apply_vert_coords(), CDDM_calc_normals(), CDDM_copy(), CDDM_from_BMEditMesh(), create_orco_dm(), CustomData_has_layer(), Object::data, ModifierTypeInfo::deformVerts, ModifierTypeInfo::deformVertsEM, DM_add_loop_layer(), DM_ensure_tessface(), DM_init_origspace(), DM_set_only_copy(), DM_TYPE_EDITBMESH, editbmesh_get_vertex_cos(), editbmesh_modifier_is_enabled(), eModifierMode_Editmode, eModifierMode_Realtime, eModifierTypeType_OnlyDeform, FALSE, getEditDerivedBMesh(), DerivedMesh::getNumVerts, DerivedMesh::getVertCos, i, DerivedMesh::loopData, CDMaskLink::mask, MEM_dupallocN(), MEM_freeN(), MEM_mallocN(), modifiers_calcDataMasks(), modifiers_clearErrors(), modifiers_getCageIndex(), modifiers_getVirtualModifierList(), modifierType_getInfo(), mti, ModifierData::next, CDMaskLink::next, NULL, DerivedMesh::release, ModifierTypeInfo::requiredDataMask, and ModifierTypeInfo::type.
Referenced by editbmesh_build_data().
DerivedMesh* editbmesh_get_derived_base (Object * obedit, BMEditMesh * em)
Definition at line 2301 of file DerivedMesh.c.
References getEditDerivedBMesh(), and NULL.
Referenced by draw_mesh_object(), draw_object_mesh_instance(), and snapObject().
DerivedMesh* editbmesh_get_derived_cage (Scene * scene, Object * obedit, BMEditMesh * em, CustomDataMask dataMask)
Definition at line 2289 of file DerivedMesh.c.
References BMEditMesh::derivedCage, editbmesh_build_data(), and BMEditMesh::lastDataMask.
Referenced by crazyspace_get_mapped_editverts(), draw_object_backbufsel(), face_duplilist(), mesh_foreachScreenEdge(), mesh_foreachScreenFace(), mesh_foreachScreenVert(), peelObjects(), and vertex_duplilist().
DerivedMesh* editbmesh_get_derived_cage_and_final (Scene * scene, Object * obedit, BMEditMesh * em, DerivedMesh ** final_r, CustomDataMask dataMask)
Definition at line 2275 of file DerivedMesh.c.
References BMEditMesh::derivedCage, BMEditMesh::derivedFinal, editbmesh_build_data(), and BMEditMesh::lastDataMask.
Referenced by BMBVH_NewBVH(), draw_mesh_object(), draw_uvs(), knifetool_init(), and meshdeformModifier_do().
float(* editbmesh_get_vertex_cos (BMEditMesh * em, int * numVerts_r))[3]
Definition at line 1836 of file DerivedMesh.c.
References BMIter::bm, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, BMVert::co, copy_v3_v3(), cos(), i, MEM_mallocN(), and NULL.
Referenced by editbmesh_calc_modifiers(), and editbmesh_get_first_deform_matrices().
int editbmesh_modifier_is_enabled (Scene * scene, ModifierData * md, DerivedMesh * dm)
Definition at line 1853 of file DerivedMesh.c.
References eModifierMode_Editmode, eModifierMode_Realtime, eModifierTypeFlag_RequiresOriginalData, ModifierTypeInfo::flags, modifier_isEnabled(), modifier_setError(), modifierType_getInfo(), mti, TIP_, and ModifierData::type.
Referenced by editbmesh_calc_modifiers(), and editbmesh_get_first_deform_matrices().
static float* get_editbmesh_orco_verts (BMEditMesh * em) [static]
Definition at line 839 of file DerivedMesh.c.
References BMEditMesh::bm, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, BMVert::co, copy_v3_v3(), MEM_mallocN(), NULL, and BMesh::totvert.
Referenced by get_orco_coords_dm().
static void* get_orco_coords_dm (Object * ob, BMEditMesh * em, int layer, int * free) [static]
Definition at line 862 of file DerivedMesh.c.
References CD_CLOTH_ORCO, CD_ORCO, KeyBlock::data, eModifierType_Cloth, get_editbmesh_orco_verts(), get_mesh_orco_verts(), key_get_keyblock(), modifiers_findByType(), NULL, ob_get_key(), ClothSimSettings::shapekey_rest, and ClothModifierData::sim_parms.
Referenced by add_orco_dm(), and create_orco_dm().
static void GetNormal (const SMikkTSpaceContext * pContext, float fNorm[], const int face_num, const int vert_index) [static]
Definition at line 2416 of file DerivedMesh.c.
References MVert::co, copy_v3_v3(), MFace::flag, SMikkTSpaceContext::m_pUserData, ME_SMOOTH, SGLSLMeshToTangent::mface, SGLSLMeshToTangent::mvert, normal_quad_v3(), normal_short_to_float_v3(), normal_tri_v3(), SGLSLMeshToTangent::precomputedFaceNormals, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by DM_add_tangent_layer().
static int GetNumFaces (const SMikkTSpaceContext * pContext) [static]
Definition at line 2381 of file DerivedMesh.c.
References SMikkTSpaceContext::m_pUserData, and SGLSLMeshToTangent::numTessFaces.
Referenced by DM_add_tangent_layer().
static int GetNumVertsOfFace (const SMikkTSpaceContext * pContext, const int face_num) [static]
Definition at line 2387 of file DerivedMesh.c.
References SMikkTSpaceContext::m_pUserData, SGLSLMeshToTangent::mface, and MFace::v4.
Referenced by DM_add_tangent_layer().
static void GetPosition (const SMikkTSpaceContext * pContext, float fPos[], const int face_num, const int vert_index) [static]
Definition at line 2393 of file DerivedMesh.c.
References MVert::co, co, copy_v3_v3(), SMikkTSpaceContext::m_pUserData, SGLSLMeshToTangent::mface, SGLSLMeshToTangent::mvert, and MFace::v1.
Referenced by DM_add_tangent_layer().
static void GetTextureCoordinate (const SMikkTSpaceContext * pContext, float fUV[], const int face_num, const int vert_index) [static]
Definition at line 2401 of file DerivedMesh.c.
References if(), SMikkTSpaceContext::m_pUserData, map_to_sphere(), SGLSLMeshToTangent::mface, SGLSLMeshToTangent::mtface, NULL, SGLSLMeshToTangent::orco, MTFace::uv, and MFace::v1.
Referenced by DM_add_tangent_layer().
static void make_vertexcosnos__mapFunc (void * userData, int index, const float co[3], const float no_f[3], const short no_s[3]) [static]
Definition at line 2309 of file DerivedMesh.c.
References copy_v3_v3(), and normal_short_to_float_v3().
Referenced by mesh_get_mapped_verts_nors().
void makeDerivedMesh (Scene * scene, Object * ob, BMEditMesh * em, CustomDataMask dataMask, int build_shapekey_layers)
Definition at line 2170 of file DerivedMesh.c.
References editbmesh_build_data(), and mesh_build_data().
Referenced by crazyspace_get_mapped_editverts(), facesel_face_pick(), object_handle_update(), and vertex_parent_set_exec().
static void mesh_build_data (Scene * scene, Object * ob, CustomDataMask dataMask, int build_shapekey_layers) [static]
Definition at line 2118 of file DerivedMesh.c.
References Scene::basact, clear_mesh_caches(), Object::derivedDeform, Object::derivedFinal, DM_set_object_boundbox(), DerivedMesh::getPBVH, Object::lastDataMask, mesh_calc_modifiers(), Object::mode, DerivedMesh::needsFree, NULL, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, Base::object, paint_facesel_test(), SculptSession::pbvh, and Object::sculpt.
Referenced by makeDerivedMesh(), mesh_get_derived_deform(), and mesh_get_derived_final().
static void mesh_calc_modifiers (Scene * scene, Object * ob, float(*) inputVertexCos[3], DerivedMesh ** deform_r, DerivedMesh ** final_r, int useRenderParams, int useDeform, int needMapping, CustomDataMask dataMask, int index, int useCache, int build_shapekey_layers) [static]
Definition at line 1353 of file DerivedMesh.c.
References add_orco_dm(), add_shapekey_layers(), ModifierTypeInfo::applyModifier, ToolSettings::auto_normalize, BLI_assert, BLI_linklist_free(), CALC_WP_AUTO_NORMALIZE, CALC_WP_MULTIPAINT, CD_CALLOC, CD_CLOTH_ORCO, CD_MASK_CLOTH_ORCO, CD_MASK_ORCO, CD_MASK_ORIGINDEX, CD_MASK_ORIGSPACE_MLOOP, CD_MASK_POLYINDEX, CD_MASK_PREVIEW_MCOL, CD_MASK_PREVIEW_MLOOPCOL, CD_NORMAL, CD_ORCO, CD_ORIGINDEX, CD_ORIGSPACE_MLOOP, CD_POLYINDEX, CDDM_apply_vert_coords(), CDDM_calc_normals(), CDDM_calc_normals_mapping_ex(), CDDM_copy(), CDDM_from_mesh(), create_orco_dm(), CustomData_has_layer(), Object::data, ModifierTypeInfo::deformVerts, ModifierTypeInfo::dependsOnNormals, dependsOnTime(), ModifierTypeInfo::dependsOnTime, DM_add_edge_layer(), DM_add_loop_layer(), DM_add_poly_layer(), DM_add_vert_layer(), DM_DIRTY_TESS_CDLAYERS, DM_get_edge_data_layer(), DM_get_poly_data_layer(), DM_get_vert_data_layer(), DM_init_origspace(), DM_set_only_copy(), DM_TYPE_CDDM, DM_update_tessface_data(), DM_update_weight_mcol(), eModifierMode_Realtime, eModifierMode_Render, eModifierType_Armature, eModifierType_DynamicPaint, eModifierType_Multires, eModifierTypeFlag_RequiresOriginalData, eModifierTypeType_OnlyDeform, FALSE, ListBase::first, ModifierTypeInfo::flags, Sculpt::flags, Object::gameflag, get_multires_modifier(), DerivedMesh::getNumVerts, DerivedMesh::getVertCos, DerivedMesh::loopData, CDMaskLink::mask, MEM_freeN(), MEM_mallocN(), mesh_getVertexCos(), Object::mode, modifier_freeTemporaryData(), modifier_isEnabled(), modifier_setError(), modifier_supportsMapping(), Object::modifiers, modifiers_calcDataMasks(), modifiers_clearErrors(), modifiers_getLastPreview(), modifiers_getVirtualModifierList(), modifiers_indexInObject(), modifierType_getInfo(), mti, ToolSettings::multipaint, ModifierData::next, CDMaskLink::next, NULL, DerivedMesh::numEdgeData, DerivedMesh::numPolyData, DerivedMesh::numVertData, OB_MODE_OBJECT, OB_MODE_SCULPT, OB_MODE_WEIGHT_PAINT, OB_NAVMESH, range_vn_i(), DerivedMesh::release, ModifierTypeInfo::requiredDataMask, ModifierData::scene, Object::sculpt, ToolSettings::sculpt, SCULPT_ONLY_DEFORM, MultiresModifierData::sculptlvl, TIP_, Scene::toolsettings, Mesh::totvert, TRUE, DerivedMesh::type, ModifierData::type, and ModifierTypeInfo::type.
Referenced by mesh_build_data(), mesh_create_derived_index_render(), mesh_create_derived_no_deform(), mesh_create_derived_no_deform_render(), mesh_create_derived_no_virtual(), mesh_create_derived_physics(), mesh_create_derived_render(), and mesh_create_derived_view().
DerivedMesh* mesh_create_derived (Mesh * me, Object * ob, float(*) vertCos[3])
Definition at line 779 of file DerivedMesh.c.
References CDDM_apply_vert_coords(), CDDM_calc_normals(), CDDM_from_mesh(), and NULL.
Referenced by mesh_create_derived_for_modifier(), and sculpt_get_first_deform_matrices().
DerivedMesh* mesh_create_derived_for_modifier (Scene * scene, Object * ob, ModifierData * md, int build_shapekey_layers)
Definition at line 796 of file DerivedMesh.c.
References add_shapekey_layers(), ModifierTypeInfo::applyModifier, BLI_findlink(), Key::block, Object::data, ModifierTypeInfo::deformVerts, eModifierMode_Realtime, eModifierTypeType_OnlyDeform, ModifierTypeInfo::isDisabled, Mesh::key, key_to_mesh(), MEM_freeN(), mesh_create_derived(), mesh_getVertexCos(), ModifierData::mode, modifierType_getInfo(), mti, NULL, DerivedMesh::release, ModifierData::scene, Object::shapenr, ModifierTypeInfo::type, and ModifierData::type.
Referenced by modifier_apply_obdata(), and modifier_apply_shape().
DerivedMesh* mesh_create_derived_index_render (Scene * scene, Object * ob, CustomDataMask dataMask, int index)
Definition at line 2214 of file DerivedMesh.c.
References mesh_calc_modifiers(), and NULL.
Referenced by initElbeemMesh().
DerivedMesh* mesh_create_derived_no_deform (Scene * scene, Object * ob, float(*) vertCos[3], CustomDataMask dataMask)
Definition at line 2232 of file DerivedMesh.c.
References mesh_calc_modifiers(), and NULL.
Referenced by mesh_deform_bind().
DerivedMesh* mesh_create_derived_no_deform_render (Scene * scene, Object * ob, float(*) vertCos[3], CustomDataMask dataMask)
Definition at line 2262 of file DerivedMesh.c.
References mesh_calc_modifiers(), and NULL.
DerivedMesh* mesh_create_derived_no_virtual (Scene * scene, Object * ob, float(*) vertCos[3], CustomDataMask dataMask)
Definition at line 2242 of file DerivedMesh.c.
References mesh_calc_modifiers(), and NULL.
Referenced by KX_NavMeshObject::BuildVertIndArrays(), createVertsTrisData(), and BL_ModifierDeformer::Update().
DerivedMesh* mesh_create_derived_physics (Scene * scene, Object * ob, float(*) vertCos[3], CustomDataMask dataMask)
Definition at line 2252 of file DerivedMesh.c.
References mesh_calc_modifiers(), and NULL.
Referenced by BL_ModifierDeformer::GetPhysicsMesh().
DerivedMesh* mesh_create_derived_render (Scene * scene, Object * ob, CustomDataMask dataMask)
Definition at line 2205 of file DerivedMesh.c.
References mesh_calc_modifiers(), and NULL.
Referenced by dupli_render_particle_set(), init_render_mesh(), init_render_object_data(), object_handle_update(), pointdensity_cache_object(), pointdensity_cache_psys(), and project_paint_begin().
DerivedMesh* mesh_create_derived_view (Scene * scene, Object * ob, CustomDataMask dataMask)
Definition at line 2223 of file DerivedMesh.c.
References mesh_calc_modifiers(), and NULL.
Referenced by meshdeform_bind_exec(), and NewBooleanMesh().
DerivedMesh* mesh_get_derived_deform (Scene * scene, Object * ob, CustomDataMask dataMask)
Definition at line 2194 of file DerivedMesh.c.
References Object::derivedDeform, Object::lastDataMask, and mesh_build_data().
Referenced by brush_add(), connect_hair(), dm_deform_recalc(), draw_mesh_text(), face_duplilist(), get_multires_dm(), join_mesh_shapes_exec(), multires_apply_smat(), particle_intersect_dm(), vertex_duplilist(), and vgroup_fix().
DerivedMesh* mesh_get_derived_final (Scene * scene, Object * ob, CustomDataMask dataMask)
Definition at line 2183 of file DerivedMesh.c.
References Object::derivedFinal, Object::lastDataMask, and mesh_build_data().
Referenced by add_verts_to_dgroups(), arrayModifier_doArray(), bbs_mesh_solid(), convert_exec(), draw_mesh_fancy(), draw_object_backbufsel(), draw_object_mesh_instance(), hide_show_exec(), imapaint_pick_uv(), mesh_get_mapped_verts_nors(), mesh_to_curve(), multiresModifier_reshape(), NewBooleanMesh(), GeometryExporter::operator()(), particle_intersect_dm(), peelObjects(), project_paint_begin(), sculpt_undo_restore(), sculpt_update_mesh_elements(), snapObject(), texture_paint_init(), and weight_sample_invoke().
float* mesh_get_mapped_verts_nors (Scene * scene, Object * ob)
Definition at line 2334 of file DerivedMesh.c.
References CD_MASK_BAREMESH, CD_MASK_ORIGINDEX, Object::data, DerivedMesh::foreachMappedVert, DerivedMesh::getVertCo, DerivedMesh::getVertNo, make_vertexcosnos__mapFunc(), MEM_callocN(), mesh_get_derived_final(), NULL, OB_MESH, DerivedMesh::release, Mesh::totvert, and Object::type.
Referenced by vpaint_stroke_test_start(), and wpaint_stroke_test_start().
static void SetTSpace (const SMikkTSpaceContext * pContext, const float fvTangent[], const float fSign, const int face_num, const int iVert) [static]
Definition at line 2446 of file DerivedMesh.c.
References copy_v3_v3(), SMikkTSpaceContext::m_pUserData, and SGLSLMeshToTangent::tangent.
Referenced by DM_add_tangent_layer().
static void shapekey_layers_to_keyblocks (DerivedMesh * dm, Mesh * me, int actshape_uid) [static]
Definition at line 1252 of file DerivedMesh.c.
References add_keyblock(), Key::block, CD_SHAPEKEY, MVert::co, copy_v3_v3(), cos(), CustomData_get_layer_index_n(), CustomData_get_layer_n(), CustomData_number_of_layers(), KeyBlock::data, ListBase::first, DerivedMesh::getVertArray, i, Mesh::key, CustomData::layers, MEM_callocN(), MEM_freeN(), MEM_mallocN(), KeyBlock::name, CustomDataLayer::name, KeyBlock::next, DerivedMesh::numVertData, KeyBlock::totelem, KeyBlock::uid, CustomDataLayer::uid, and DerivedMesh::vertData.
Referenced by DM_to_mesh().
void vDM_ColorBand_store (ColorBand * coba)
Definition at line 1070 of file DerivedMesh.c.
Referenced by init_userdef_do_versions().
void weight_to_rgb (float r_rgb[3], const float weight)
Definition at line 955 of file DerivedMesh.c.
References blend().
Referenced by draw_new_particle_system(), draw_uvs_stretch(), drawlattice__point(), psys_cache_edit_paths(), and weightpaint_color().
static void weightpaint_color (unsigned char r_col[4], ColorBand * coba, const float input) [static]
Definition at line 994 of file DerivedMesh.c.
References do_colorband(), and weight_to_rgb().
Referenced by calc_colors_from_weights_array(), calc_weightpaint_vert_array(), and calc_weightpaint_vert_color().
Variable Documentation
ColorBand* stored_cb = NULL [static]
Definition at line 1068 of file DerivedMesh.c.
Referenced by DM_update_weight_mcol().