Blender: view3d_buttons.c File Reference
view3d_buttons.c File Reference
3D view
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <float.h>
#include "DNA_armature_types.h"
#include "DNA_curve_types.h"
#include "DNA_lattice_types.h"
#include "DNA_meta_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLF_translation.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BKE_action.h"
#include "BKE_context.h"
#include "BKE_curve.h"
#include "BKE_customdata.h"
#include "BKE_depsgraph.h"
#include "BKE_main.h"
#include "BKE_mesh.h"
#include "BKE_screen.h"
#include "BKE_tessmesh.h"
#include "BKE_deform.h"
#include "BKE_object.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "ED_armature.h"
#include "ED_gpencil.h"
#include "ED_mesh.h"
#include "ED_screen.h"
#include "ED_transform.h"
#include "ED_curve.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "view3d_intern.h"
Classes
struct TransformProperties
Defines
#define B_NOP 1
#define B_REDR 2
#define B_OBJECTPANELMEDIAN 1008
#define B_VGRP_PNL_COPY 1
#define B_VGRP_PNL_NORMALIZE 2
#define B_VGRP_PNL_EDIT_SINGLE 8
#define B_VGRP_PNL_COPY_SINGLE 16384
Functions
static float compute_scale_factor (const float ve_median, const float median)
static void v3d_editvertex_buts (uiLayout *layout, View3D *v3d, Object *ob, float lim)
static void act_vert_def (Object *ob, BMVert **eve, MDeformVert **dvert)
static void editvert_mirror_update (Object *ob, BMVert *eve, int def_nr, int index)
static void vgroup_adjust_active (Object *ob, int def_nr)
static void vgroup_copy_active_to_sel (Object *ob)
static void vgroup_copy_active_to_sel_single (Object *ob, const int def_nr)
static void vgroup_normalize_active (Object *ob)
static void do_view3d_vgroup_buttons (bContext *C, void *UNUSED(arg), int event)
static int view3d_panel_vgroup_poll (const bContext *C, PanelType *UNUSED(pt))
static void view3d_panel_vgroup (const bContext *C, Panel *pa)
static void v3d_transform_butsR (uiLayout *layout, PointerRNA *ptr)
static void v3d_posearmature_buts (uiLayout *layout, Object *ob)
static void v3d_editarmature_buts (uiLayout *layout, Object *ob)
static void v3d_editmetaball_buts (uiLayout *layout, Object *ob)
static void do_view3d_region_buttons (bContext *C, void *UNUSED(index), int event)
static void view3d_panel_object (const bContext *C, Panel *pa)
void view3d_buttons_register (ARegionType *art)
static int view3d_properties (bContext *C, wmOperator *UNUSED(op))
void VIEW3D_OT_properties (wmOperatorType *ot)
Detailed Description
Definition in file view3d_buttons.c.
Define Documentation
#define B_NOP 1
Definition at line 86 of file view3d_buttons.c.
#define B_OBJECTPANELMEDIAN 1008
Definition at line 88 of file view3d_buttons.c.
Referenced by do_view3d_region_buttons(), and v3d_editvertex_buts().
#define B_REDR 2
Definition at line 87 of file view3d_buttons.c.
#define B_VGRP_PNL_COPY 1
Definition at line 610 of file view3d_buttons.c.
Referenced by do_view3d_vgroup_buttons(), and view3d_panel_vgroup().
#define B_VGRP_PNL_COPY_SINGLE 16384
Definition at line 613 of file view3d_buttons.c.
Referenced by do_view3d_vgroup_buttons(), and view3d_panel_vgroup().
#define B_VGRP_PNL_EDIT_SINGLE 8
Definition at line 612 of file view3d_buttons.c.
Referenced by do_view3d_vgroup_buttons(), and view3d_panel_vgroup().
#define B_VGRP_PNL_NORMALIZE 2
Definition at line 611 of file view3d_buttons.c.
Referenced by do_view3d_vgroup_buttons(), and view3d_panel_vgroup().
Function Documentation
static void act_vert_def (Object * ob, BMVert ** eve, MDeformVert ** dvert) [static]
Definition at line 615 of file view3d_buttons.c.
References BMEditMesh::bm, BM_VERT, CD_MDEFORMVERT, CustomData_bmesh_get(), Object::data, Object::defbase, Mesh::edit_btmesh, BMEditSelection::ele, ListBase::first, BMEditSelection::htype, if(), ListBase::last, Object::mode, NULL, OB_MESH, OB_MODE_EDIT, BMesh::selected, Object::type, and BMesh::vdata.
Referenced by vgroup_adjust_active(), vgroup_copy_active_to_sel(), vgroup_copy_active_to_sel_single(), vgroup_normalize_active(), view3d_panel_vgroup(), and view3d_panel_vgroup_poll().
static float compute_scale_factor (const float ve_median, const float median) [static]
Definition at line 106 of file view3d_buttons.c.
References CLAMP().
Referenced by v3d_editvertex_buts().
static void do_view3d_region_buttons (bContext * C, void * UNUSEDindex, int event) [static]
Definition at line 1041 of file view3d_buttons.c.
References B_OBJECTPANELMEDIAN, B_REDR, CTX_data_scene(), CTX_wm_area(), CTX_wm_view3d(), DAG_id_tag_update(), ED_area_tag_redraw(), Object::id, NC_SPACE, ND_SPACE_VIEW3D, NULL, OB_RECALC_DATA, OBACT, v3d_editvertex_buts(), and WM_event_add_notifier().
Referenced by view3d_panel_object().
static void do_view3d_vgroup_buttons (bContext * C, void * UNUSEDarg, int event) [static]
Definition at line 775 of file view3d_buttons.c.
References B_VGRP_PNL_COPY, B_VGRP_PNL_COPY_SINGLE, B_VGRP_PNL_EDIT_SINGLE, B_VGRP_PNL_NORMALIZE, CTX_data_scene(), DAG_id_tag_update(), Object::data, ED_vgroup_mirror(), Object::id, ME_EDIT_MIRROR_X, NC_GEOM, ND_DATA, OB_RECALC_DATA, OBACT, vgroup_adjust_active(), vgroup_copy_active_to_sel(), vgroup_copy_active_to_sel_single(), vgroup_normalize_active(), and WM_event_add_notifier().
Referenced by view3d_panel_vgroup().
static void editvert_mirror_update (Object * ob, BMVert * eve, int def_nr, int index) [static]
Definition at line 633 of file view3d_buttons.c.
References BMEditMesh::bm, CD_MDEFORMVERT, BMVert::co, CustomData_bmesh_get(), BMHeader::data, Object::data, defgroup_flip_index(), defgroup_flip_map(), defvert_find_weight(), defvert_sync_mapped(), defvert_verify_index(), Mesh::edit_btmesh, editbmesh_get_x_mirror_vert(), BMVert::head, MEM_freeN(), TRUE, BMesh::vdata, and MDeformWeight::weight.
Referenced by vgroup_adjust_active(), vgroup_copy_active_to_sel(), vgroup_copy_active_to_sel_single(), and vgroup_normalize_active().
static void v3d_editarmature_buts (uiLayout * layout, Object * ob) [static]
Definition at line 959 of file view3d_buttons.c.
References bArmature::act_edbone, BONE_CONNECTED, Object::data, EditBone::flag, bArmature::id, IFACE_, bArmature::layer, EditBone::layer, NULL, EditBone::parent, RNA_EditBone, RNA_pointer_create(), RNA_pointer_get(), uiItemL(), uiItemR(), and uiLayoutColumn().
Referenced by view3d_panel_object().
static void v3d_editmetaball_buts (uiLayout * layout, Object * ob) [static]
Definition at line 992 of file view3d_buttons.c.
References Object::data, MetaBall::id, IFACE_, MetaBall::lastelem, MB_BALL, MB_CUBE, MB_ELIPSOID, MB_PLANE, MB_TUBE, NULL, RNA_enum_get(), RNA_MetaBall, RNA_MetaElement, RNA_pointer_create(), uiItemL(), uiItemR(), and uiLayoutColumn().
Referenced by view3d_panel_object().
static void v3d_editvertex_buts (uiLayout * layout, View3D * v3d, Object * ob, float lim) [static]
Definition at line 133 of file view3d_buttons.c.
References add_v3_v3(), B_OBJECTPANELMEDIAN, B_REDR, Nurb::bezt, BLI_findlink(), BLI_snprintf(), BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, Nurb::bp, CD_BWEIGHT, CD_CREASE, CD_MDEFORMVERT, CLAMP(), BMVert::co, compute_scale_factor(), CU_BEZIER, TransformProperties::curdef, curve_editnurbs(), CustomData_bmesh_get(), BMHeader::data, Object::data, Lattice::def, MDeformWeight::def_nr, Object::defbase, TransformProperties::defweightp, MDeformVert::dw, BMesh::edata, EDBM_mesh_normals_update(), Mesh::edit_btmesh, Lattice::editlatt, ELEM, BPoint::f1, BezTriple::f1, BezTriple::f2, BezTriple::f3, ListBase::first, View3D::flag, BMVert::head, BMEdge::head, i, Curve::id, IFACE_, Object::imat, init(), invert_m4_m4(), LABEL, EditLatt::latt, len_v3(), max, MEM_callocN(), mul_m4_v3(), bDeformGroup::name, Nurb::next, NULL, NUM, OB_CURVE, OB_LATTICE, OB_MESH, OB_SURF, Object::obmat, Lattice::pntsu, Nurb::pntsu, Lattice::pntsv, Nurb::pntsv, Lattice::pntsw, PROP_UNIT_LENGTH, View3D::properties_storage, BPoint::radius, BezTriple::radius, RNA_BezierSplinePoint, RNA_pointer_create(), RNA_SplinePoint, RNA_TRANSLATION_PREC_DEFAULT, SELECT, str, sub_v3_v3v3(), test2DNurb(), testhandlesNurb(), TIP_, TOG, TOGN, MDeformVert::totweight, Nurb::type, Object::type, UI_DPI_ICON_FAC, uiBlockBeginAlign(), uiBlockEndAlign(), uiButSetUnitType(), uiDefBut(), uiDefButBitS(), uiDefButF(), uiLayoutAbsoluteBlock(), V3D_GLOBAL_STATS, BMesh::vdata, TransformProperties::ve_median, BPoint::vec, BezTriple::vec, BPoint::weight, BezTriple::weight, and MDeformWeight::weight.
Referenced by do_view3d_region_buttons(), and view3d_panel_object().
static void v3d_posearmature_buts (uiLayout * layout, Object * ob) [static]
Definition at line 936 of file view3d_buttons.c.
References get_active_posechannel(), Object::id, IFACE_, RNA_pointer_create(), RNA_PoseBone, uiItemL(), uiLayoutColumn(), and v3d_transform_butsR().
Referenced by view3d_panel_object().
static void v3d_transform_butsR (uiLayout * layout, PointerRNA * ptr) [static]
Definition at line 864 of file view3d_buttons.c.
References BONE_CONNECTED, PointerRNA::data, Bone::flag, IFACE_, NULL, OB_TYPE_SUPPORT_MATERIAL, Bone::parent, RNA_boolean_get(), RNA_enum_get(), RNA_Object, RNA_pointer_get(), RNA_PoseBone, ROT_MODE_AXISANGLE, ROT_MODE_QUAT, split(), Object::type, PointerRNA::type, UI_ITEM_R_ICON_ONLY, UI_ITEM_R_TOGGLE, uiItemL(), uiItemR(), uiLayoutColumn(), uiLayoutSetActive(), and uiLayoutSplit().
Referenced by v3d_posearmature_buts(), and view3d_panel_object().
static void vgroup_adjust_active (Object * ob, int def_nr) [static]
Definition at line 663 of file view3d_buttons.c.
References act_vert_def(), Object::data, editvert_mirror_update(), and ME_EDIT_MIRROR_X.
Referenced by do_view3d_vgroup_buttons().
static void vgroup_copy_active_to_sel (Object * ob) [static]
Definition at line 676 of file view3d_buttons.c.
References act_vert_def(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, CD_MDEFORMVERT, CustomData_bmesh_get(), BMHeader::data, Object::data, defvert_copy(), Mesh::edit_btmesh, Mesh::editflag, editvert_mirror_update(), BMVert::head, ME_EDIT_MIRROR_X, NULL, and BMesh::vdata.
Referenced by do_view3d_vgroup_buttons().
static void vgroup_copy_active_to_sel_single (Object * ob, const int def_nr) [static]
Definition at line 711 of file view3d_buttons.c.
References act_vert_def(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, CD_MDEFORMVERT, CustomData_bmesh_get(), BMHeader::data, Object::data, defvert_find_index(), Mesh::edit_btmesh, Mesh::editflag, editvert_mirror_update(), BMVert::head, ME_EDIT_MIRROR_X, NULL, BMesh::vdata, and MDeformWeight::weight.
Referenced by do_view3d_vgroup_buttons().
static void vgroup_normalize_active (Object * ob) [static]
Definition at line 759 of file view3d_buttons.c.
References act_vert_def(), Object::data, defvert_normalize(), editvert_mirror_update(), ME_EDIT_MIRROR_X, and NULL.
Referenced by do_view3d_vgroup_buttons().
void view3d_buttons_register (ARegionType * art)
Definition at line 1104 of file view3d_buttons.c.
References BLI_addtail(), PanelType::draw, gpencil_panel_standard(), PanelType::idname, PanelType::label, MEM_callocN(), ARegionType::paneltypes, PanelType::poll, view3d_panel_object(), view3d_panel_vgroup(), and view3d_panel_vgroup_poll().
Referenced by ED_spacetype_view3d().
void VIEW3D_OT_properties (wmOperatorType * ot)
Definition at line 1139 of file view3d_buttons.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and view3d_properties().
Referenced by view3d_operatortypes().
static void view3d_panel_object (const bContext * C, Panel * pa) [static]
Definition at line 1065 of file view3d_buttons.c.
References CTX_data_edit_object(), CTX_data_scene(), CTX_wm_view3d(), do_view3d_region_buttons(), View3D::grid, Object::id, Panel::layout, MAX2, Object::mode, NULL, OB_ARMATURE, OB_MBALL, OB_MODE_POSE, OBACT, RNA_id_pointer_create(), Object::type, uiBlockSetHandleFunc(), uiLayoutColumn(), uiLayoutGetBlock(), v3d_editarmature_buts(), v3d_editmetaball_buts(), v3d_editvertex_buts(), v3d_posearmature_buts(), and v3d_transform_butsR().
Referenced by view3d_buttons_register().
static void view3d_panel_vgroup (const bContext * C, Panel * pa) [static]
Definition at line 817 of file view3d_buttons.c.
References act_vert_def(), B_VGRP_PNL_COPY, B_VGRP_PNL_COPY_SINGLE, B_VGRP_PNL_EDIT_SINGLE, B_VGRP_PNL_NORMALIZE, BLI_findlink(), BUT, CTX_data_scene(), MDeformWeight::def_nr, Object::defbase, do_view3d_vgroup_buttons(), MDeformVert::dw, i, IFACE_, Panel::layout, bDeformGroup::name, NULL, NUM, OBACT, TIP_, MDeformVert::totweight, uiBlockBeginAlign(), uiBlockEndAlign(), uiBlockSetHandleFunc(), uiDefBut(), uiDefButF(), uiLayoutAbsoluteBlock(), uiLayoutColumn(), and MDeformWeight::weight.
Referenced by view3d_buttons_register().
static int view3d_panel_vgroup_poll (const bContext * C, PanelType * UNUSEDpt) [static]
Definition at line 804 of file view3d_buttons.c.
References act_vert_def(), CTX_data_scene(), OBACT, and MDeformVert::totweight.
Referenced by view3d_buttons_register().
static int view3d_properties (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1128 of file view3d_buttons.c.
References CTX_wm_area(), ED_region_toggle_hidden(), OPERATOR_FINISHED, and view3d_has_buttons_region().
Referenced by VIEW3D_OT_properties().