Blender: BSP_PlyLoader Class Reference
BSP_PlyLoader Class Reference
#include <BSP_PlyLoader.h>
Static Public Member Functions
static MEM_SmartPtr< BSP_TMesh > NewMeshFromFile (char *file_name, MT_Vector3 &min, MT_Vector3 &max)
Detailed Description
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) 2001-2002 by NaN Holding BV. All rights reserved.
The Original Code is: all of this file.
Contributor(s): none yet.
***** END GPL LICENSE BLOCK *****
Definition at line 34 of file BSP_PlyLoader.h.
Member Function Documentation
MEM_SmartPtr< BSP_TMesh > BSP_PlyLoader::NewMeshFromFile (char * file_name, MT_Vector3 & min, MT_Vector3 & max) [static]
Definition at line 46 of file BSP_PlyLoader.cpp.
References equal_strings(), i, BSP_TVertex::m_pos, BSP_TFace::m_verts, MT_INFINITY(), NULL, ply_close(), PLY_FLOAT, ply_get_element(), ply_get_element_description(), ply_get_property(), PLY_INT, ply_open_for_reading(), PLY_UCHAR, MT_Tuple3::x(), MT_Tuple3::y(), and MT_Tuple3::z().
Referenced by main().
The documentation for this class was generated from the following files:
BSP_PlyLoader.h
BSP_PlyLoader.cpp