Blender: view3d_toolbar.c File Reference
view3d_toolbar.c File Reference
3D view
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <float.h>
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BLI_ghash.h"
#include "BLF_translation.h"
#include "BKE_context.h"
#include "BKE_idprop.h"
#include "BKE_global.h"
#include "BKE_screen.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "ED_screen.h"
#include "ED_util.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "view3d_intern.h"
Classes
struct CustomTool
Typedefs
typedef struct CustomTool CustomTool
Functions
static void view3d_panel_operator_redo_buts (const bContext *C, Panel *pa, wmOperator *op)
static void view3d_panel_operator_redo_header (const bContext *C, Panel *pa)
static void view3d_panel_operator_redo_operator (const bContext *C, Panel *pa, wmOperator *op)
static void view3d_panel_operator_redo (const bContext *C, Panel *pa)
static void operator_call_cb (struct bContext *C, void *arg_listbase, void *arg2)
static void operator_search_cb (const struct bContext *C, void *UNUSED(arg), const char *str, uiSearchItems *items)
static uiBlock * tool_search_menu (bContext *C, ARegion *ar, void *arg_listbase)
static void view3d_panel_tool_shelf (const bContext *C, Panel *pa)
void view3d_toolshelf_register (ARegionType *art)
void view3d_tool_props_register (ARegionType *art)
static int view3d_toolshelf (bContext *C, wmOperator *UNUSED(op))
void VIEW3D_OT_toolshelf (wmOperatorType *ot)
Detailed Description
Definition in file view3d_toolbar.c.
Typedef Documentation
typedef struct CustomTool CustomTool
Function Documentation
static void operator_call_cb (struct bContext * C, void * arg_listbase, void * arg2) [static]
Definition at line 128 of file view3d_toolbar.c.
References BLI_addtail(), BLI_strncpy(), CustomTool::context, CTX_data_mode_string(), wmOperatorType::idname, MEM_callocN(), OP_MAX_TYPENAME, and CustomTool::opname.
Referenced by tool_search_menu().
static void operator_search_cb (const struct bContext * C, void * UNUSEDarg, const char * str, uiSearchItems * items) [static]
Definition at line 142 of file view3d_toolbar.c.
References BLI_ghashIterator_free(), BLI_ghashIterator_getValue(), BLI_ghashIterator_isDone(), BLI_ghashIterator_step(), BLI_strcasestr(), wmOperatorType::name, uiSearchItemAdd(), WM_operator_poll(), and WM_operatortype_iter().
Referenced by tool_search_menu().
static uiBlock* tool_search_menu (bContext * C, ARegion * ar, void * arg_listbase) [static]
Definition at line 162 of file view3d_toolbar.c.
References CTX_wm_window(), wmWindow::eventstate, EVT_BUT_OPEN, FALSE, KM_PRESS, LABEL, NULL, OP_MAX_TYPENAME, operator_call_cb(), operator_search_cb(), UI_BLOCK_LOOP, UI_BLOCK_REDRAW, UI_BLOCK_RET_1, UI_DOWN, UI_EMBOSS, uiBeginBlock(), uiBlockSetDirection(), uiBlockSetFlag(), uiBoundsBlock(), uiButSetSearchFunc(), uiDefBut(), uiDefSearchBut(), uiEndBlock(), uiSearchBoxhHeight(), and wm_event_add().
Referenced by view3d_panel_tool_shelf().
void VIEW3D_OT_toolshelf (wmOperatorType * ot)
Definition at line 258 of file view3d_toolbar.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and view3d_toolshelf().
Referenced by view3d_operatortypes().
static void view3d_panel_operator_redo (const bContext * C, Panel * pa) [static]
Definition at line 99 of file view3d_toolbar.c.
References ED_undo_operator_repeat_cb_evt(), Panel::layout, wmOperatorType::name, NULL, wmOperator::type, uiBlockSetHandleFunc(), uiLayoutGetBlock(), uiLayoutSetEnabled(), view3d_panel_operator_redo_operator(), WM_operator_check_ui_enabled(), WM_operator_last_redo(), and WM_operator_poll().
Referenced by view3d_tool_props_register().
static void view3d_panel_operator_redo_buts (const bContext * C, Panel * pa, wmOperator * op) [static]
Definition at line 72 of file view3d_toolbar.c.
References Panel::layout, NULL, and uiLayoutOperatorButs().
Referenced by view3d_panel_operator_redo_operator().
static void view3d_panel_operator_redo_header (const bContext * C, Panel * pa) [static]
Definition at line 77 of file view3d_toolbar.c.
References BLI_strncpy(), Panel::drawname, IFACE_, wmOperatorType::name, wmOperator::type, and WM_operator_last_redo().
Referenced by view3d_tool_props_register().
static void view3d_panel_operator_redo_operator (const bContext * C, Panel * pa, wmOperator * op) [static]
Definition at line 85 of file view3d_toolbar.c.
References ListBase::first, wmOperatorType::flag, Panel::layout, wmOperator::macro, wmOperatorType::name, wmOperator::next, OPTYPE_MACRO, wmOperator::type, uiItemL(), and view3d_panel_operator_redo_buts().
Referenced by view3d_panel_operator_redo().
static void view3d_panel_tool_shelf (const bContext * C, Panel * pa) [static]
Definition at line 197 of file view3d_toolbar.c.
References BKE_spacetype_from_id(), CustomTool::context, CTX_data_mode_string(), CTX_wm_space_data(), ListBase::first, Panel::layout, CustomTool::next, NULL, OP_MAX_TYPENAME, CustomTool::opname, SpaceLink::spacetype, tool_search_menu(), SpaceType::toolshelf, UI_UNIT_X, UI_UNIT_Y, uiDefBlockBut(), uiItemFullO(), uiLayoutColumn(), uiLayoutGetBlock(), and WM_OP_INVOKE_REGION_WIN.
Referenced by view3d_toolshelf_register().
void view3d_tool_props_register (ARegionType * art)
Definition at line 233 of file view3d_toolbar.c.
References BLI_addtail(), PanelType::draw, PanelType::draw_header, PanelType::idname, PanelType::label, MEM_callocN(), ARegionType::paneltypes, view3d_panel_operator_redo(), and view3d_panel_operator_redo_header().
Referenced by ED_spacetype_view3d().
static int view3d_toolshelf (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 247 of file view3d_toolbar.c.
References CTX_wm_area(), ED_region_toggle_hidden(), OPERATOR_FINISHED, and view3d_has_tools_region().
Referenced by VIEW3D_OT_toolshelf().
void view3d_toolshelf_register (ARegionType * art)
Definition at line 222 of file view3d_toolbar.c.
References BLI_addtail(), PanelType::draw, PanelType::idname, PanelType::label, MEM_callocN(), ARegionType::paneltypes, and view3d_panel_tool_shelf().
Referenced by ED_spacetype_view3d().