Blender: bgl.h File Reference
bgl.h File Reference
Python Generic
Classes
struct _Buffer
Defines
#define void_str ""
#define void_var(num)
#define void_ref(num) &bgl_var##num
#define void_def(num) char bgl_var##num
#define buffer_str "O!"
#define buffer_var(number) (bgl_buffer##number)->buf.asvoid
#define buffer_ref(number) &BGL_bufferType, &bgl_buffer##number
#define buffer_def(number) Buffer *bgl_buffer##number
#define GLbooleanP_str "O!"
#define GLbooleanP_var(number) (bgl_buffer##number)->buf.asvoid
#define GLbooleanP_ref(number) &BGL_bufferType, &bgl_buffer##number
#define GLbooleanP_def(number) Buffer *bgl_buffer##number
#define GLbyteP_str "O!"
#define GLbyteP_var(number) (bgl_buffer##number)->buf.asvoid
#define GLbyteP_ref(number) &BGL_bufferType, &bgl_buffer##number
#define GLbyteP_def(number) Buffer *bgl_buffer##number
#define GLubyteP_str "O!"
#define GLubyteP_var(number) (bgl_buffer##number)->buf.asvoid
#define GLubyteP_ref(number) &BGL_bufferType, &bgl_buffer##number
#define GLubyteP_def(number) Buffer *bgl_buffer##number
#define GLintP_str "O!"
#define GLintP_var(number) (bgl_buffer##number)->buf.asvoid
#define GLintP_ref(number) &BGL_bufferType, &bgl_buffer##number
#define GLintP_def(number) Buffer *bgl_buffer##number
#define GLuintP_str "O!"
#define GLuintP_var(number) (bgl_buffer##number)->buf.asvoid
#define GLuintP_ref(number) &BGL_bufferType, &bgl_buffer##number
#define GLuintP_def(number) Buffer *bgl_buffer##number
#define GLshortP_str "O!"
#define GLshortP_var(number) (bgl_buffer##number)->buf.asvoid
#define GLshortP_ref(number) &BGL_bufferType, &bgl_buffer##number
#define GLshortP_def(number) Buffer *bgl_buffer##number
#define GLushortP_str "O!"
#define GLushortP_var(number) (bgl_buffer##number)->buf.asvoid
#define GLushortP_ref(number) &BGL_bufferType, &bgl_buffer##number
#define GLushortP_def(number) Buffer *bgl_buffer##number
#define GLfloatP_str "O!"
#define GLfloatP_var(number) (bgl_buffer##number)->buf.asvoid
#define GLfloatP_ref(number) &BGL_bufferType, &bgl_buffer##number
#define GLfloatP_def(number) Buffer *bgl_buffer##number
#define GLdoubleP_str "O!"
#define GLdoubleP_var(number) (bgl_buffer##number)->buf.asvoid
#define GLdoubleP_ref(number) &BGL_bufferType, &bgl_buffer##number
#define GLdoubleP_def(number) Buffer *bgl_buffer##number
#define GLclampfP_str "O!"
#define GLclampfP_var(number) (bgl_buffer##number)->buf.asvoid
#define GLclampfP_ref(number) &BGL_bufferType, &bgl_buffer##number
#define GLclampfP_def(number) Buffer *bgl_buffer##number
#define GLvoidP_str "O!"
#define GLvoidP_var(number) (bgl_buffer##number)->buf.asvoid
#define GLvoidP_ref(number) &BGL_bufferType, &bgl_buffer##number
#define GLvoidP_def(number) Buffer *bgl_buffer##number
#define buffer_str "O!"
#define buffer_var(number) (bgl_buffer##number)->buf.asvoid
#define buffer_ref(number) &BGL_bufferType, &bgl_buffer##number
#define buffer_def(number) Buffer *bgl_buffer##number
#define GLenum_str "i"
#define GLenum_var(num) bgl_var##num
#define GLenum_ref(num) &bgl_var##num
#define GLenum_def(num) /* unsigned */ int GLenum_var(num)
#define GLboolean_str "b"
#define GLboolean_var(num) bgl_var##num
#define GLboolean_ref(num) &bgl_var##num
#define GLboolean_def(num) /* unsigned */ char GLboolean_var(num)
#define GLbitfield_str "i"
#define GLbitfield_var(num) bgl_var##num
#define GLbitfield_ref(num) &bgl_var##num
#define GLbitfield_def(num) /* unsigned */ int GLbitfield_var(num)
#define GLbyte_str "b"
#define GLbyte_var(num) bgl_var##num
#define GLbyte_ref(num) &bgl_var##num
#define GLbyte_def(num) signed char GLbyte_var(num)
#define GLshort_str "h"
#define GLshort_var(num) bgl_var##num
#define GLshort_ref(num) &bgl_var##num
#define GLshort_def(num) short GLshort_var(num)
#define GLint_str "i"
#define GLint_var(num) bgl_var##num
#define GLint_ref(num) &bgl_var##num
#define GLint_def(num) int GLint_var(num)
#define GLsizei_str "i"
#define GLsizei_var(num) bgl_var##num
#define GLsizei_ref(num) &bgl_var##num
#define GLsizei_def(num) int GLsizei_var(num)
#define GLubyte_str "B"
#define GLubyte_var(num) bgl_var##num
#define GLubyte_ref(num) &bgl_var##num
#define GLubyte_def(num) /* unsigned */ char GLubyte_var(num)
#define GLushort_str "H"
#define GLushort_var(num) bgl_var##num
#define GLushort_ref(num) &bgl_var##num
#define GLushort_def(num) /* unsigned */ short GLushort_var(num)
#define GLuint_str "I"
#define GLuint_var(num) bgl_var##num
#define GLuint_ref(num) &bgl_var##num
#define GLuint_def(num) /* unsigned */ int GLuint_var(num)
#define GLfloat_str "f"
#define GLfloat_var(num) bgl_var##num
#define GLfloat_ref(num) &bgl_var##num
#define GLfloat_def(num) float GLfloat_var(num)
#define GLclampf_str "f"
#define GLclampf_var(num) bgl_var##num
#define GLclampf_ref(num) &bgl_var##num
#define GLclampf_def(num) float GLclampf_var(num)
#define GLdouble_str "d"
#define GLdouble_var(num) bgl_var##num
#define GLdouble_ref(num) &bgl_var##num
#define GLdouble_def(num) double GLdouble_var(num)
#define GLclampd_str "d"
#define GLclampd_var(num) bgl_var##num
#define GLclampd_ref(num) &bgl_var##num
#define GLclampd_def(num) double GLclampd_var(num)
#define arg_def1(a1) a1##_def(1)
#define arg_def2(a1, a2) arg_def1(a1); a2##_def(2)
#define arg_def3(a1, a2, a3) arg_def2(a1, a2); a3##_def(3)
#define arg_def4(a1, a2, a3, a4) arg_def3(a1, a2, a3); a4##_def(4)
#define arg_def5(a1, a2, a3, a4, a5) arg_def4(a1, a2, a3, a4); a5##_def(5)
#define arg_def6(a1, a2, a3, a4, a5, a6) arg_def5(a1, a2, a3, a4, a5); a6##_def(6)
#define arg_def7(a1, a2, a3, a4, a5, a6, a7) arg_def6(a1, a2, a3, a4, a5, a6); a7##_def(7)
#define arg_def8(a1, a2, a3, a4, a5, a6, a7, a8) arg_def7(a1, a2, a3, a4, a5, a6, a7); a8##_def(8)
#define arg_def9(a1, a2, a3, a4, a5, a6, a7, a8, a9) arg_def8(a1, a2, a3, a4, a5, a6, a7, a8); a9##_def(9)
#define arg_def10(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) arg_def9(a1, a2, a3, a4, a5, a6, a7, a8, a9); a10##_def(10)
#define arg_var1(a1) a1##_var(1)
#define arg_var2(a1, a2) arg_var1(a1), a2##_var(2)
#define arg_var3(a1, a2, a3) arg_var2(a1, a2), a3##_var(3)
#define arg_var4(a1, a2, a3, a4) arg_var3(a1, a2, a3), a4##_var(4)
#define arg_var5(a1, a2, a3, a4, a5) arg_var4(a1, a2, a3, a4), a5##_var(5)
#define arg_var6(a1, a2, a3, a4, a5, a6) arg_var5(a1, a2, a3, a4, a5), a6##_var(6)
#define arg_var7(a1, a2, a3, a4, a5, a6, a7) arg_var6(a1, a2, a3, a4, a5, a6), a7##_var(7)
#define arg_var8(a1, a2, a3, a4, a5, a6, a7, a8) arg_var7(a1, a2, a3, a4, a5, a6, a7), a8##_var(8)
#define arg_var9(a1, a2, a3, a4, a5, a6, a7, a8, a9) arg_var8(a1, a2, a3, a4, a5, a6, a7, a8), a9##_var(9)
#define arg_var10(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) arg_var9(a1, a2, a3, a4, a5, a6, a7, a8, a9), a10##_var(10)
#define arg_ref1(a1) a1##_ref(1)
#define arg_ref2(a1, a2) arg_ref1(a1), a2##_ref(2)
#define arg_ref3(a1, a2, a3) arg_ref2(a1, a2), a3##_ref(3)
#define arg_ref4(a1, a2, a3, a4) arg_ref3(a1, a2, a3), a4##_ref(4)
#define arg_ref5(a1, a2, a3, a4, a5) arg_ref4(a1, a2, a3, a4), a5##_ref(5)
#define arg_ref6(a1, a2, a3, a4, a5, a6) arg_ref5(a1, a2, a3, a4, a5), a6##_ref(6)
#define arg_ref7(a1, a2, a3, a4, a5, a6, a7) arg_ref6(a1, a2, a3, a4, a5, a6), a7##_ref(7)
#define arg_ref8(a1, a2, a3, a4, a5, a6, a7, a8) arg_ref7(a1, a2, a3, a4, a5, a6, a7), a8##_ref(8)
#define arg_ref9(a1, a2, a3, a4, a5, a6, a7, a8, a9) arg_ref8(a1, a2, a3, a4, a5, a6, a7, a8), a9##_ref(9)
#define arg_ref10(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) arg_ref9(a1, a2, a3, a4, a5, a6, a7, a8, a9), a10##_ref(10)
#define arg_str1(a1) a1##_str
#define arg_str2(a1, a2) arg_str1(a1) a2##_str
#define arg_str3(a1, a2, a3) arg_str2(a1, a2) a3##_str
#define arg_str4(a1, a2, a3, a4) arg_str3(a1, a2, a3) a4##_str
#define arg_str5(a1, a2, a3, a4, a5) arg_str4(a1, a2, a3, a4) a5##_str
#define arg_str6(a1, a2, a3, a4, a5, a6) arg_str5(a1, a2, a3, a4, a5) a6##_str
#define arg_str7(a1, a2, a3, a4, a5, a6, a7) arg_str6(a1, a2, a3, a4, a5, a6) a7##_str
#define arg_str8(a1, a2, a3, a4, a5, a6, a7, a8) arg_str7(a1, a2, a3, a4, a5, a6, a7) a8##_str
#define arg_str9(a1, a2, a3, a4, a5, a6, a7, a8, a9) arg_str8(a1, a2, a3, a4, a5, a6, a7, a8) a9##_str
#define arg_str10(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) arg_str9(a1, a2, a3, a4, a5, a6, a7, a8, a9) a10##_str
#define ret_def_void
#define ret_set_void
#define ret_ret_void return Py_INCREF(Py_None), Py_None
#define ret_def_GLint int ret_int
#define ret_set_GLint ret_int =
#define ret_ret_GLint return PyLong_FromLong(ret_int)
#define ret_def_GLuint unsigned int ret_uint
#define ret_set_GLuint ret_uint =
#define ret_ret_GLuint return PyLong_FromLong((long) ret_uint)
#define ret_def_GLenum unsigned int ret_uint
#define ret_set_GLenum ret_uint =
#define ret_ret_GLenum return PyLong_FromLong((long) ret_uint)
#define ret_def_GLboolean unsigned char ret_bool
#define ret_set_GLboolean ret_bool =
#define ret_ret_GLboolean return PyLong_FromLong((long) ret_bool)
#define ret_def_GLstring const unsigned char *ret_str
#define ret_set_GLstring ret_str =
#define ret_ret_GLstring
Typedefs
typedef struct _Buffer Buffer
Functions
PyObject * BPyInit_bgl (void)
struct _Buffer * BGL_MakeBuffer (int type, int ndimensions, int *dimensions, void *initbuffer)
int BGL_typeSize (int type)
Variables
PyTypeObject BGL_bufferType
Detailed Description
Definition in file bgl.h.
Define Documentation
#define arg_def1 (a1) a1##_def(1)
Definition at line 266 of file bgl.h.
#define arg_def10 (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) arg_def9(a1, a2, a3, a4, a5, a6, a7, a8, a9); a10##_def(10)
Definition at line 275 of file bgl.h.
#define arg_def2 (a1, a2) arg_def1(a1); a2##_def(2)
Definition at line 267 of file bgl.h.
#define arg_def3 (a1, a2, a3) arg_def2(a1, a2); a3##_def(3)
Definition at line 268 of file bgl.h.
#define arg_def4 (a1, a2, a3, a4) arg_def3(a1, a2, a3); a4##_def(4)
Definition at line 269 of file bgl.h.
#define arg_def5 (a1, a2, a3, a4, a5) arg_def4(a1, a2, a3, a4); a5##_def(5)
Definition at line 270 of file bgl.h.
#define arg_def6 (a1, a2, a3, a4, a5, a6) arg_def5(a1, a2, a3, a4, a5); a6##_def(6)
Definition at line 271 of file bgl.h.
#define arg_def7 (a1, a2, a3, a4, a5, a6, a7) arg_def6(a1, a2, a3, a4, a5, a6); a7##_def(7)
Definition at line 272 of file bgl.h.
#define arg_def8 (a1, a2, a3, a4, a5, a6, a7, a8) arg_def7(a1, a2, a3, a4, a5, a6, a7); a8##_def(8)
Definition at line 273 of file bgl.h.
#define arg_def9 (a1, a2, a3, a4, a5, a6, a7, a8, a9) arg_def8(a1, a2, a3, a4, a5, a6, a7, a8); a9##_def(9)
Definition at line 274 of file bgl.h.
#define arg_ref1 (a1) a1##_ref(1)
Definition at line 288 of file bgl.h.
#define arg_ref10 (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) arg_ref9(a1, a2, a3, a4, a5, a6, a7, a8, a9), a10##_ref(10)
Definition at line 297 of file bgl.h.
#define arg_ref2 (a1, a2) arg_ref1(a1), a2##_ref(2)
Definition at line 289 of file bgl.h.
#define arg_ref3 (a1, a2, a3) arg_ref2(a1, a2), a3##_ref(3)
Definition at line 290 of file bgl.h.
#define arg_ref4 (a1, a2, a3, a4) arg_ref3(a1, a2, a3), a4##_ref(4)
Definition at line 291 of file bgl.h.
#define arg_ref5 (a1, a2, a3, a4, a5) arg_ref4(a1, a2, a3, a4), a5##_ref(5)
Definition at line 292 of file bgl.h.
#define arg_ref6 (a1, a2, a3, a4, a5, a6) arg_ref5(a1, a2, a3, a4, a5), a6##_ref(6)
Definition at line 293 of file bgl.h.
#define arg_ref7 (a1, a2, a3, a4, a5, a6, a7) arg_ref6(a1, a2, a3, a4, a5, a6), a7##_ref(7)
Definition at line 294 of file bgl.h.
#define arg_ref8 (a1, a2, a3, a4, a5, a6, a7, a8) arg_ref7(a1, a2, a3, a4, a5, a6, a7), a8##_ref(8)
Definition at line 295 of file bgl.h.
#define arg_ref9 (a1, a2, a3, a4, a5, a6, a7, a8, a9) arg_ref8(a1, a2, a3, a4, a5, a6, a7, a8), a9##_ref(9)
Definition at line 296 of file bgl.h.
#define arg_str1 (a1) a1##_str
Definition at line 299 of file bgl.h.
#define arg_str10 (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) arg_str9(a1, a2, a3, a4, a5, a6, a7, a8, a9) a10##_str
Definition at line 308 of file bgl.h.
#define arg_str2 (a1, a2) arg_str1(a1) a2##_str
Definition at line 300 of file bgl.h.
#define arg_str3 (a1, a2, a3) arg_str2(a1, a2) a3##_str
Definition at line 301 of file bgl.h.
#define arg_str4 (a1, a2, a3, a4) arg_str3(a1, a2, a3) a4##_str
Definition at line 302 of file bgl.h.
#define arg_str5 (a1, a2, a3, a4, a5) arg_str4(a1, a2, a3, a4) a5##_str
Definition at line 303 of file bgl.h.
#define arg_str6 (a1, a2, a3, a4, a5, a6) arg_str5(a1, a2, a3, a4, a5) a6##_str
Definition at line 304 of file bgl.h.
#define arg_str7 (a1, a2, a3, a4, a5, a6, a7) arg_str6(a1, a2, a3, a4, a5, a6) a7##_str
Definition at line 305 of file bgl.h.
#define arg_str8 (a1, a2, a3, a4, a5, a6, a7, a8) arg_str7(a1, a2, a3, a4, a5, a6, a7) a8##_str
Definition at line 306 of file bgl.h.
#define arg_str9 (a1, a2, a3, a4, a5, a6, a7, a8, a9) arg_str8(a1, a2, a3, a4, a5, a6, a7, a8) a9##_str
Definition at line 307 of file bgl.h.
#define arg_var1 (a1) a1##_var(1)
Definition at line 277 of file bgl.h.
#define arg_var10 (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) arg_var9(a1, a2, a3, a4, a5, a6, a7, a8, a9), a10##_var(10)
Definition at line 286 of file bgl.h.
#define arg_var2 (a1, a2) arg_var1(a1), a2##_var(2)
Definition at line 278 of file bgl.h.
#define arg_var3 (a1, a2, a3) arg_var2(a1, a2), a3##_var(3)
Definition at line 279 of file bgl.h.
#define arg_var4 (a1, a2, a3, a4) arg_var3(a1, a2, a3), a4##_var(4)
Definition at line 280 of file bgl.h.
#define arg_var5 (a1, a2, a3, a4, a5) arg_var4(a1, a2, a3, a4), a5##_var(5)
Definition at line 281 of file bgl.h.
#define arg_var6 (a1, a2, a3, a4, a5, a6) arg_var5(a1, a2, a3, a4, a5), a6##_var(6)
Definition at line 282 of file bgl.h.
#define arg_var7 (a1, a2, a3, a4, a5, a6, a7) arg_var6(a1, a2, a3, a4, a5, a6), a7##_var(7)
Definition at line 283 of file bgl.h.
#define arg_var8 (a1, a2, a3, a4, a5, a6, a7, a8) arg_var7(a1, a2, a3, a4, a5, a6, a7), a8##_var(8)
Definition at line 284 of file bgl.h.
#define arg_var9 (a1, a2, a3, a4, a5, a6, a7, a8, a9) arg_var8(a1, a2, a3, a4, a5, a6, a7, a8), a9##_var(9)
Definition at line 285 of file bgl.h.
#define buffer_def (number) Buffer *bgl_buffer##number
Definition at line 166 of file bgl.h.
#define buffer_def (number) Buffer *bgl_buffer##number
Definition at line 166 of file bgl.h.
#define buffer_ref (number) &BGL_bufferType, &bgl_buffer##number
Definition at line 165 of file bgl.h.
#define buffer_ref (number) &BGL_bufferType, &bgl_buffer##number
Definition at line 165 of file bgl.h.
#define buffer_str "O!"
Definition at line 163 of file bgl.h.
#define buffer_str "O!"
Definition at line 163 of file bgl.h.
#define buffer_var (number) (bgl_buffer##number)->buf.asvoid
Definition at line 164 of file bgl.h.
#define buffer_var (number) (bgl_buffer##number)->buf.asvoid
Definition at line 164 of file bgl.h.
#define GLbitfield_def (num) /* unsigned */ int GLbitfield_var(num)
Definition at line 192 of file bgl.h.
#define GLbitfield_ref (num) &bgl_var##num
Definition at line 191 of file bgl.h.
#define GLbitfield_str "i"
Definition at line 189 of file bgl.h.
#define GLbitfield_var (num) bgl_var##num
Definition at line 190 of file bgl.h.
#define GLboolean_def (num) /* unsigned */ char GLboolean_var(num)
Definition at line 186 of file bgl.h.
#define GLboolean_ref (num) &bgl_var##num
Definition at line 185 of file bgl.h.
#define GLboolean_str "b"
Definition at line 183 of file bgl.h.
#define GLboolean_var (num) bgl_var##num
Definition at line 184 of file bgl.h.
#define GLbooleanP_def (number) Buffer *bgl_buffer##number
Definition at line 111 of file bgl.h.
#define GLbooleanP_ref (number) &BGL_bufferType, &bgl_buffer##number
Definition at line 110 of file bgl.h.
#define GLbooleanP_str "O!"
Definition at line 108 of file bgl.h.
#define GLbooleanP_var (number) (bgl_buffer##number)->buf.asvoid
Definition at line 109 of file bgl.h.
#define GLbyte_def (num) signed char GLbyte_var(num)
Definition at line 198 of file bgl.h.
#define GLbyte_ref (num) &bgl_var##num
Definition at line 197 of file bgl.h.
#define GLbyte_str "b"
Definition at line 195 of file bgl.h.
#define GLbyte_var (num) bgl_var##num
Definition at line 196 of file bgl.h.
#define GLbyteP_def (number) Buffer *bgl_buffer##number
Definition at line 116 of file bgl.h.
#define GLbyteP_ref (number) &BGL_bufferType, &bgl_buffer##number
Definition at line 115 of file bgl.h.
#define GLbyteP_str "O!"
Definition at line 113 of file bgl.h.
#define GLbyteP_var (number) (bgl_buffer##number)->buf.asvoid
Definition at line 114 of file bgl.h.
#define GLclampd_def (num) double GLclampd_var(num)
Definition at line 258 of file bgl.h.
#define GLclampd_ref (num) &bgl_var##num
Definition at line 257 of file bgl.h.
#define GLclampd_str "d"
Definition at line 255 of file bgl.h.
#define GLclampd_var (num) bgl_var##num
Definition at line 256 of file bgl.h.
#define GLclampf_def (num) float GLclampf_var(num)
Definition at line 246 of file bgl.h.
#define GLclampf_ref (num) &bgl_var##num
Definition at line 245 of file bgl.h.
#define GLclampf_str "f"
Definition at line 243 of file bgl.h.
#define GLclampf_var (num) bgl_var##num
Definition at line 244 of file bgl.h.
#define GLclampfP_def (number) Buffer *bgl_buffer##number
Definition at line 156 of file bgl.h.
#define GLclampfP_ref (number) &BGL_bufferType, &bgl_buffer##number
Definition at line 155 of file bgl.h.
#define GLclampfP_str "O!"
Definition at line 153 of file bgl.h.
#define GLclampfP_var (number) (bgl_buffer##number)->buf.asvoid
Definition at line 154 of file bgl.h.
#define GLdouble_def (num) double GLdouble_var(num)
Definition at line 252 of file bgl.h.
#define GLdouble_ref (num) &bgl_var##num
Definition at line 251 of file bgl.h.
#define GLdouble_str "d"
Definition at line 249 of file bgl.h.
#define GLdouble_var (num) bgl_var##num
Definition at line 250 of file bgl.h.
#define GLdoubleP_def (number) Buffer *bgl_buffer##number
Definition at line 151 of file bgl.h.
#define GLdoubleP_ref (number) &BGL_bufferType, &bgl_buffer##number
Definition at line 150 of file bgl.h.
#define GLdoubleP_str "O!"
Definition at line 148 of file bgl.h.
#define GLdoubleP_var (number) (bgl_buffer##number)->buf.asvoid
Definition at line 149 of file bgl.h.
#define GLenum_def (num) /* unsigned */ int GLenum_var(num)
Definition at line 180 of file bgl.h.
#define GLenum_ref (num) &bgl_var##num
Definition at line 179 of file bgl.h.
#define GLenum_str "i"
Definition at line 177 of file bgl.h.
#define GLenum_var (num) bgl_var##num
Definition at line 178 of file bgl.h.
#define GLfloat_def (num) float GLfloat_var(num)
Definition at line 240 of file bgl.h.
#define GLfloat_ref (num) &bgl_var##num
Definition at line 239 of file bgl.h.
#define GLfloat_str "f"
Definition at line 237 of file bgl.h.
#define GLfloat_var (num) bgl_var##num
Definition at line 238 of file bgl.h.
#define GLfloatP_def (number) Buffer *bgl_buffer##number
Definition at line 146 of file bgl.h.
#define GLfloatP_ref (number) &BGL_bufferType, &bgl_buffer##number
Definition at line 145 of file bgl.h.
#define GLfloatP_str "O!"
Definition at line 143 of file bgl.h.
#define GLfloatP_var (number) (bgl_buffer##number)->buf.asvoid
Definition at line 144 of file bgl.h.
#define GLint_def (num) int GLint_var(num)
Definition at line 210 of file bgl.h.
#define GLint_ref (num) &bgl_var##num
Definition at line 209 of file bgl.h.
#define GLint_str "i"
Definition at line 207 of file bgl.h.
#define GLint_var (num) bgl_var##num
Definition at line 208 of file bgl.h.
#define GLintP_def (number) Buffer *bgl_buffer##number
Definition at line 126 of file bgl.h.
#define GLintP_ref (number) &BGL_bufferType, &bgl_buffer##number
Definition at line 125 of file bgl.h.
#define GLintP_str "O!"
Definition at line 123 of file bgl.h.
#define GLintP_var (number) (bgl_buffer##number)->buf.asvoid
Definition at line 124 of file bgl.h.
#define GLshort_def (num) short GLshort_var(num)
Definition at line 204 of file bgl.h.
#define GLshort_ref (num) &bgl_var##num
Definition at line 203 of file bgl.h.
#define GLshort_str "h"
Definition at line 201 of file bgl.h.
#define GLshort_var (num) bgl_var##num
Definition at line 202 of file bgl.h.
#define GLshortP_def (number) Buffer *bgl_buffer##number
Definition at line 136 of file bgl.h.
#define GLshortP_ref (number) &BGL_bufferType, &bgl_buffer##number
Definition at line 135 of file bgl.h.
#define GLshortP_str "O!"
Definition at line 133 of file bgl.h.
#define GLshortP_var (number) (bgl_buffer##number)->buf.asvoid
Definition at line 134 of file bgl.h.
#define GLsizei_def (num) int GLsizei_var(num)
Definition at line 216 of file bgl.h.
#define GLsizei_ref (num) &bgl_var##num
Definition at line 215 of file bgl.h.
#define GLsizei_str "i"
Definition at line 213 of file bgl.h.
#define GLsizei_var (num) bgl_var##num
Definition at line 214 of file bgl.h.
#define GLubyte_def (num) /* unsigned */ char GLubyte_var(num)
Definition at line 222 of file bgl.h.
#define GLubyte_ref (num) &bgl_var##num
Definition at line 221 of file bgl.h.
#define GLubyte_str "B"
Definition at line 219 of file bgl.h.
#define GLubyte_var (num) bgl_var##num
Definition at line 220 of file bgl.h.
#define GLubyteP_def (number) Buffer *bgl_buffer##number
Definition at line 121 of file bgl.h.
#define GLubyteP_ref (number) &BGL_bufferType, &bgl_buffer##number
Definition at line 120 of file bgl.h.
#define GLubyteP_str "O!"
Definition at line 118 of file bgl.h.
#define GLubyteP_var (number) (bgl_buffer##number)->buf.asvoid
Definition at line 119 of file bgl.h.
#define GLuint_def (num) /* unsigned */ int GLuint_var(num)
Definition at line 234 of file bgl.h.
#define GLuint_ref (num) &bgl_var##num
Definition at line 233 of file bgl.h.
#define GLuint_str "I"
Definition at line 231 of file bgl.h.
#define GLuint_var (num) bgl_var##num
Definition at line 232 of file bgl.h.
#define GLuintP_def (number) Buffer *bgl_buffer##number
Definition at line 131 of file bgl.h.
#define GLuintP_ref (number) &BGL_bufferType, &bgl_buffer##number
Definition at line 130 of file bgl.h.
#define GLuintP_str "O!"
Definition at line 128 of file bgl.h.
#define GLuintP_var (number) (bgl_buffer##number)->buf.asvoid
Definition at line 129 of file bgl.h.
#define GLushort_def (num) /* unsigned */ short GLushort_var(num)
Definition at line 228 of file bgl.h.
#define GLushort_ref (num) &bgl_var##num
Definition at line 227 of file bgl.h.
#define GLushort_str "H"
Definition at line 225 of file bgl.h.
#define GLushort_var (num) bgl_var##num
Definition at line 226 of file bgl.h.
#define GLushortP_def (number) Buffer *bgl_buffer##number
Definition at line 141 of file bgl.h.
#define GLushortP_ref (number) &BGL_bufferType, &bgl_buffer##number
Definition at line 140 of file bgl.h.
#define GLushortP_str "O!"
Definition at line 138 of file bgl.h.
#define GLushortP_var (number) (bgl_buffer##number)->buf.asvoid
Definition at line 139 of file bgl.h.
#define GLvoidP_def (number) Buffer *bgl_buffer##number
Definition at line 161 of file bgl.h.
#define GLvoidP_ref (number) &BGL_bufferType, &bgl_buffer##number
Definition at line 160 of file bgl.h.
#define GLvoidP_str "O!"
Definition at line 158 of file bgl.h.
#define GLvoidP_var (number) (bgl_buffer##number)->buf.asvoid
Definition at line 159 of file bgl.h.
#define ret_def_GLboolean unsigned char ret_bool
Definition at line 326 of file bgl.h.
#define ret_def_GLenum unsigned int ret_uint
Definition at line 322 of file bgl.h.
#define ret_def_GLint int ret_int
Definition at line 314 of file bgl.h.
#define ret_def_GLstring const unsigned char *ret_str
Definition at line 330 of file bgl.h.
#define ret_def_GLuint unsigned int ret_uint
Definition at line 318 of file bgl.h.
#define ret_def_void
Definition at line 310 of file bgl.h.
#define ret_ret_GLboolean return PyLong_FromLong((long) ret_bool)
Definition at line 328 of file bgl.h.
#define ret_ret_GLenum return PyLong_FromLong((long) ret_uint)
Definition at line 324 of file bgl.h.
#define ret_ret_GLint return PyLong_FromLong(ret_int)
Definition at line 316 of file bgl.h.
#define ret_ret_GLstring
Value:
if (ret_str) {                                                            \
        return PyUnicode_FromString((const char *)ret_str);                   \
    }                                                                         \
    else {                                                                    \
        PyErr_SetString(PyExc_AttributeError, "could not get opengl string"); \
        return NULL;                                                          \
    }                                                                         \
Definition at line 333 of file bgl.h.
#define ret_ret_GLuint return PyLong_FromLong((long) ret_uint)
Definition at line 320 of file bgl.h.
#define ret_ret_void return Py_INCREF(Py_None), Py_None
Definition at line 312 of file bgl.h.
#define ret_set_GLboolean ret_bool =
Definition at line 327 of file bgl.h.
#define ret_set_GLenum ret_uint =
Definition at line 323 of file bgl.h.
#define ret_set_GLint ret_int =
Definition at line 315 of file bgl.h.
#define ret_set_GLstring ret_str =
Definition at line 331 of file bgl.h.
#define ret_set_GLuint ret_uint =
Definition at line 319 of file bgl.h.
#define ret_set_void
Definition at line 311 of file bgl.h.
#define void_def (num) char bgl_var##num
Definition at line 98 of file bgl.h.
#define void_ref (num) &bgl_var##num
Definition at line 97 of file bgl.h.
#define void_str ""
Definition at line 95 of file bgl.h.
#define void_var (num)
Definition at line 96 of file bgl.h.
Typedef Documentation
typedef struct _Buffer Buffer
Function Documentation
struct _Buffer* BGL_MakeBuffer (int type, int ndimensions, int * dimensions, void * initbuffer) [read]
Definition at line 256 of file bgl.c.
References _Buffer::asvoid, BGL_typeSize(), _Buffer::buf, _Buffer::dimensions, i, length(), MEM_mallocN(), _Buffer::ndimensions, NULL, _Buffer::parent, size(), and _Buffer::type.
Referenced by Buffer_new(), and Image_getImage().
int BGL_typeSize (int type)
Definition at line 239 of file bgl.c.
Referenced by BGL_MakeBuffer(), Buffer_item(), and testBGLBuffer().
PyObject* BPyInit_bgl (void)
Definition at line 1298 of file bgl.c.
References EXPP_ADDCONST, and NULL.
Variable Documentation
PyTypeObject BGL_bufferType
Definition at line 138 of file bgl.c.
Referenced by load(), and plot().