Blender: OVBVHNode Struct Reference
OVBVHNode Struct Reference
#include <reorganize.h>
Public Member Functions
float get_cost (int cutsize)
int get_cut_size (int parent_cut_size)
void set_cut (int cutsize, OVBVHNode ***cut)
void optimize ()
Public Attributes
float bb [6]
OVBVHNode * child
OVBVHNode * sibling
float cut_cost [MAX_CUT_SIZE]
int cut_size [MAX_CUT_SIZE]
int best_cutsize
Detailed Description
Definition at line 317 of file reorganize.h.
Member Function Documentation
float OVBVHNode::get_cost (int cutsize) [inline]
Definition at line 329 of file reorganize.h.
References cut_cost.
int OVBVHNode::get_cut_size (int parent_cut_size) [inline]
Definition at line 339 of file reorganize.h.
References cut_size.
Referenced by set_cut().
void OVBVHNode::optimize () [inline]
Definition at line 372 of file reorganize.h.
References best_cutsize, child, NULL, optimize(), RE_rayobject_isAligned, set_cut(), and sibling.
Referenced by optimize().
void OVBVHNode::set_cut (int cutsize, OVBVHNode *** cut) [inline]
Definition at line 348 of file reorganize.h.
References assert, child, get_cut_size(), MAX_CUT_SIZE, RE_rayobject_isAligned, set_cut(), and sibling.
Referenced by optimize(), and set_cut().
Member Data Documentation
float OVBVHNode::bb[6]
Definition at line 319 of file reorganize.h.
int OVBVHNode::best_cutsize
Definition at line 347 of file reorganize.h.
Referenced by optimize().
OVBVHNode* OVBVHNode::child
Definition at line 321 of file reorganize.h.
Referenced by optimize(), and set_cut().
float OVBVHNode::cut_cost[MAX_CUT_SIZE]
Definition at line 328 of file reorganize.h.
Referenced by get_cost().
int OVBVHNode::cut_size[MAX_CUT_SIZE]
Definition at line 338 of file reorganize.h.
Referenced by get_cut_size().
OVBVHNode* OVBVHNode::sibling
Definition at line 322 of file reorganize.h.
Referenced by optimize(), and set_cut().
The documentation for this struct was generated from the following file:
reorganize.h