Blender: node_composite_viewer.c File Reference
node_composite_viewer.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void node_composit_exec_viewer (void *data, bNode *node, bNodeStack **in, bNodeStack **UNUSED(out))
static void node_composit_init_viewer (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_viewer (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_viewer_in []
Detailed Description
Definition in file node_composite_viewer.c.
Function Documentation
static void node_composit_exec_viewer (void * data, bNode * node, bNodeStack ** in, bNodeStack ** UNUSEDout) [static]
Definition at line 45 of file node_composite_viewer.c.
References alloc_compbuf(), BKE_image_acquire_ibuf(), BKE_image_release_ibuf(), BKE_image_user_calc_frame(), CB_RGBA, CB_VAL, RenderData::cfra, composit1_pixel_processor(), composit2_pixel_processor(), bNodeStack::data, data, do_copy_a_rgba(), do_copy_rgba(), do_copy_value(), bNode::flag, free_compbuf(), generate_preview(), IB_zbuffloat, bNode::id, IMA_OK_LOADED, imb_addrectfloatImBuf(), imb_freerectfloatImBuf(), imb_freerectImBuf(), IMB_freezbuffloatImBuf(), CompBuf::malloc, NODE_DO_OUTPUT, NULL, Image::ok, CompBuf::rect, and bNode::storage.
Referenced by register_node_type_cmp_viewer().
static void node_composit_init_viewer (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 125 of file node_composite_viewer.c.
References ImageUser::fie_ima, MEM_callocN(), ImageUser::ok, ImageUser::sfra, and bNode::storage.
Referenced by register_node_type_cmp_viewer().
void register_node_type_cmp_viewer (bNodeTreeType * ttype)
Definition at line 134 of file node_composite_viewer.c.
References CMP_NODE_VIEWER, NODE_CLASS_OUTPUT, node_composit_exec_viewer(), node_composit_init_viewer(), node_copy_standard_storage(), node_free_standard_storage(), NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_viewer_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",      0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_FLOAT, 1, "Alpha",     1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_NONE},
    {   SOCK_FLOAT, 1, "Z",         1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_NONE},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_composite_viewer.c.