Blender: wm_window.h File Reference
wm_window.h File Reference
windowmanager
Functions
void wm_ghost_init (bContext *C)
void wm_ghost_exit (void)
void wm_get_screensize (int *width_r, int *height_r)
wmWindow * wm_window_new (bContext *C)
void wm_window_free (bContext *C, wmWindowManager *wm, wmWindow *win)
void wm_window_close (bContext *C, wmWindowManager *wm, wmWindow *win)
void wm_window_title (wmWindowManager *wm, wmWindow *win)
void wm_window_add_ghostwindows (wmWindowManager *wm)
void wm_window_process_events (const bContext *C)
void wm_window_process_events_nosleep (void)
void wm_window_make_drawable (bContext *C, wmWindow *win)
void wm_window_raise (wmWindow *win)
void wm_window_lower (wmWindow *win)
void wm_window_set_size (wmWindow *win, int width, int height)
void wm_window_get_size (wmWindow *win, int *width_r, int *height_r)
void wm_window_get_size_ghost (wmWindow *win, int *width_r, int *height_r)
void wm_window_get_position (wmWindow *win, int *posx_r, int *posy_r)
void wm_window_swap_buffers (wmWindow *win)
void wm_get_cursor_position (wmWindow *win, int *x, int *y)
wmWindow * wm_window_copy (bContext *C, wmWindow *winorig)
void wm_window_testbreak (void)
int wm_window_duplicate_exec (bContext *C, struct wmOperator *op)
int wm_window_fullscreen_toggle_exec (bContext *C, struct wmOperator *op)
Detailed Description
Definition in file wm_window.h.
Function Documentation
void wm_get_cursor_position (wmWindow * win, int * x, int * y)
Definition at line 1177 of file wm_window.c.
References g_system, GHOST_GetCursorPosition(), GHOST_ScreenToClient(), wmWindow::ghostwin, and wmWindow::sizey.
Referenced by wm_event_add_ghostevent(), and wm_paintcursor_draw().
void wm_get_screensize (int * width_r, int * height_r)
Definition at line 100 of file wm_window.c.
References g_system, and GHOST_GetMainDisplayDimensions().
Referenced by ghost_event_proc(), WM_init_game(), wm_window_add_ghostwindow(), wm_window_add_ghostwindows(), and wm_window_check_position().
void wm_ghost_exit (void)
Definition at line 995 of file wm_window.c.
References g_system, GHOST_DisposeSystem(), and NULL.
Referenced by WM_exit_ext().
void wm_ghost_init (bContext * C)
Definition at line 985 of file wm_window.c.
References g_system, GHOST_AddEventConsumer(), GHOST_CreateEventConsumer(), GHOST_CreateSystem(), and ghost_event_proc().
Referenced by WM_init().
void wm_window_add_ghostwindows (wmWindowManager * wm)
Definition at line 392 of file wm_window.c.
References wmWindowManager::defaultconf, wmWindow::eventstate, ListBase::first, wmWindow::ghostwin, wmWindow::handlers, MEM_callocN(), wmWindow::modalhandlers, wmWindow::next, NULL, WMInitStruct::override_flag, wmWindow::posx, wmWindow::posy, WMInitStruct::size_x, WMInitStruct::size_y, wmWindow::sizex, wmWindow::sizey, WMInitStruct::start_x, WMInitStruct::start_y, WIN_OVERRIDE_GEOM, WIN_OVERRIDE_WINSTATE, wmWindowManager::windows, WMInitStruct::windowstate, wmWindow::windowstate, WM_dropboxmap_find(), WM_event_add_dropbox_handler(), WM_event_add_keymap_handler(), wm_get_screensize(), wm_init_state, WM_keymap_find(), wm_set_apple_prefsize(), wm_window_add_ghostwindow(), and wm_window_title().
Referenced by WM_check().
void wm_window_close (bContext * C, wmWindowManager * wm, wmWindow * win)
Definition at line 251 of file wm_window.c.
References BLI_remlink(), CTX_data_main(), CTX_wm_window_set(), ED_screen_exit(), wmWindowManager::file_saved, ListBase::first, free_libblock(), GHOST_confirmQuit(), wmWindow::ghostwin, wmWindow::handlers, wmWindow::modalhandlers, wmWindow::next, NULL, Main::screen, wmWindow::screen, bScreen::temp, USER_QUIT_PROMPT, wmWindowManager::windows, wm_draw_window_clear(), WM_event_remove_handlers(), WM_exit(), and wm_window_free().
Referenced by ghost_event_proc(), and WM_write_homefile().
wmWindow* wm_window_copy (bContext * C, wmWindow * winorig)
Definition at line 227 of file wm_window.c.
References BLI_strncpy(), bScreen::do_draw, bScreen::do_refresh, wmWindow::drawdata, wmWindow::drawmethod, ED_screen_duplicate(), bScreen::id, ID::name, NULL, wmWindow::posx, wmWindow::posy, wmWindow::screen, wmWindow::screenname, wmWindow::sizex, wmWindow::sizey, wmWindow::winid, bScreen::winid, and wm_window_new().
Referenced by wm_window_duplicate_exec().
int wm_window_duplicate_exec (bContext * C, struct wmOperator * op)
void wm_window_free (bContext * C, wmWindowManager * wm, wmWindow * win)
Definition at line 156 of file wm_window.c.
References CTX_wm_window(), CTX_wm_window_set(), wmWindow::drawdata, wmTimer::event_type, wmWindow::eventstate, ListBase::first, wmWindow::handlers, MEM_freeN(), wmWindow::modalhandlers, wmTimer::next, NULL, TIMERJOBS, wmWindowManager::timers, wmTimer::win, wmWindowManager::winactive, wmWindowManager::windrawable, wm_event_free_all(), WM_event_remove_handlers(), WM_event_remove_timer(), wm_ghostwindow_destroy(), wm_jobs_timer_ended(), and wm_subwindows_free().
Referenced by wm_close_and_free(), and wm_window_close().
int wm_window_fullscreen_toggle_exec (bContext * C, struct wmOperator * op)
void wm_window_get_position (wmWindow * win, int * posx_r, int * posy_r)
Definition at line 1127 of file wm_window.c.
References wmWindow::posx, and wmWindow::posy.
void wm_window_get_size (wmWindow * win, int * width_r, int * height_r)
Definition at line 1133 of file wm_window.c.
References wmWindow::sizex, and wmWindow::sizey.
Referenced by ui_block_position(), ui_popup_block_clip(), ui_popup_bounds_block(), ui_searchbox_create(), and ui_tooltip_create().
void wm_window_get_size_ghost (wmWindow * win, int * width_r, int * height_r)
Definition at line 1141 of file wm_window.c.
References bounds(), GHOST_DisposeRectangle(), GHOST_GetClientBounds(), GHOST_GetHeightRectangle(), GHOST_GetWidthRectangle(), and wmWindow::ghostwin.
Referenced by ui_centered_bounds_block().
void wm_window_lower (wmWindow * win)
Definition at line 1155 of file wm_window.c.
References GHOST_kWindowOrderBottom, GHOST_SetWindowOrder(), and wmWindow::ghostwin.
Referenced by render_view_cancel_exec(), and render_view_show_invoke().
void wm_window_make_drawable (bContext * C, wmWindow * win)
Definition at line 620 of file wm_window.c.
References CTX_wm_manager(), G, G_DEBUG_EVENTS, GHOST_ActivateWindowDrawingContext(), wmWindow::ghostwin, wmWindowManager::windrawable, and wmWindow::winid.
Referenced by ghost_event_proc(), wm_add_default(), wm_draw_update(), and wm_event_do_handlers().
wmWindow* wm_window_new (bContext * C)
Definition at line 214 of file wm_window.c.
References BLI_addtail(), CTX_wm_manager(), find_free_winid(), MEM_callocN(), wmWindowManager::windows, and wmWindow::winid.
Referenced by wm_add_default(), wm_window_copy(), WM_window_open(), and WM_window_open_temp().
void wm_window_process_events (const bContext * C)
Definition at line 944 of file wm_window.c.
References g_system, GHOST_DispatchEvents(), GHOST_ProcessEvents(), PIL_sleep_ms(), and wm_window_timer().
Referenced by WM_main().
void wm_window_process_events_nosleep (void)
Definition at line 958 of file wm_window.c.
References g_system, GHOST_DispatchEvents(), and GHOST_ProcessEvents().
Referenced by StartKetsjiShell().
void wm_window_raise (wmWindow * win)
Definition at line 1160 of file wm_window.c.
References GHOST_kWindowOrderTop, GHOST_SetWindowOrder(), and wmWindow::ghostwin.
Referenced by render_view_open(), render_view_show_invoke(), and WM_window_open_temp().
void wm_window_set_size (wmWindow * win, int width, int height)
Definition at line 1150 of file wm_window.c.
References GHOST_SetClientSize(), and wmWindow::ghostwin.
Referenced by WM_window_open_temp().
void wm_window_swap_buffers (wmWindow * win)
Definition at line 1165 of file wm_window.c.
References GHOST_SwapWindowBuffers(), and wmWindow::ghostwin.
Referenced by BL_SwapBuffers(), wm_draw_update(), and wm_window_add_ghostwindow().
void wm_window_testbreak (void)
Definition at line 965 of file wm_window.c.
References g_system, GHOST_DispatchEvents(), GHOST_ProcessEvents(), and PIL_check_seconds_timer().
Referenced by WM_init().
void wm_window_title (wmWindowManager * wm, wmWindow * win)
Definition at line 301 of file wm_window.c.
References BLI_snprintf(), wmWindowManager::file_saved, G, GHOST_GetTitle(), GHOST_kWindowStateModified, GHOST_kWindowStateUnModified, GHOST_SetTitle(), GHOST_SetWindowModifiedState(), GHOST_SetWindowState(), wmWindow::ghostwin, NULL, wmWindow::screen, str, and bScreen::temp.
Referenced by wm_event_do_notifiers(), and wm_window_add_ghostwindows().