Blender: LassoSelectUserData Struct Reference
LassoSelectUserData Struct Reference
Public Attributes
ViewContext * vc
rcti * rect
int(* mcords)[2]
int(moves
int(select
int(pass
int(done
Detailed Description
Definition at line 252 of file view3d_select.c.
Member Data Documentation
int(LassoSelectUserData::done
Definition at line 255 of file view3d_select.c.
Referenced by do_lasso_select_mesh(), and do_lasso_select_mesh__doSelectEdge().
int(* LassoSelectUserData::mcords)[2]
Definition at line 255 of file view3d_select.c.
Referenced by do_lasso_select_curve(), do_lasso_select_curve__doSelect(), do_lasso_select_lattice(), do_lasso_select_lattice__doSelect(), do_lasso_select_mesh(), do_lasso_select_mesh__doSelectEdge(), do_lasso_select_mesh__doSelectFace(), and do_lasso_select_mesh__doSelectVert().
int(LassoSelectUserData::moves
Definition at line 255 of file view3d_select.c.
Referenced by do_lasso_select_curve(), do_lasso_select_curve__doSelect(), do_lasso_select_lattice(), do_lasso_select_lattice__doSelect(), do_lasso_select_mesh(), do_lasso_select_mesh__doSelectEdge(), do_lasso_select_mesh__doSelectFace(), and do_lasso_select_mesh__doSelectVert().
int(LassoSelectUserData::pass
Definition at line 255 of file view3d_select.c.
Referenced by do_lasso_select_mesh(), and do_lasso_select_mesh__doSelectEdge().
rcti* LassoSelectUserData::rect
Definition at line 254 of file view3d_select.c.
Referenced by do_lasso_select_mesh(), do_lasso_select_mesh__doSelectEdge(), do_lasso_select_mesh__doSelectFace(), and do_lasso_select_mesh__doSelectVert().
int(LassoSelectUserData::select
Definition at line 255 of file view3d_select.c.
Referenced by do_lasso_select_curve(), do_lasso_select_curve__doSelect(), do_lasso_select_lattice(), do_lasso_select_lattice__doSelect(), do_lasso_select_mesh(), do_lasso_select_mesh__doSelectEdge(), do_lasso_select_mesh__doSelectFace(), and do_lasso_select_mesh__doSelectVert().
ViewContext* LassoSelectUserData::vc
Definition at line 253 of file view3d_select.c.
Referenced by do_lasso_select_curve(), do_lasso_select_curve__doSelect(), do_lasso_select_mesh(), do_lasso_select_mesh__doSelectEdge(), do_lasso_select_mesh__doSelectFace(), and do_lasso_select_mesh__doSelectVert().
The documentation for this struct was generated from the following file:
view3d_select.c