Blender: node_composite_valToRgb.c File Reference
node_composite_valToRgb.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_colorband_composit (bNode *node, float *out, float *in)
static void node_composit_exec_valtorgb (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_valtorgb (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_valtorgb (bNodeTreeType *ttype)
static void do_rgbtobw (bNode *UNUSED(node), float *out, float *in)
static void node_composit_exec_rgbtobw (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_rgbtobw (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_valtorgb_in []
static bNodeSocketTemplate cmp_node_valtorgb_out []
static bNodeSocketTemplate cmp_node_rgbtobw_in []
static bNodeSocketTemplate cmp_node_rgbtobw_out []
Detailed Description
Definition in file node_composite_valToRgb.c.
Function Documentation
static void do_colorband_composit (bNode * node, float * out, float * in) [static]
Definition at line 47 of file node_composite_valToRgb.c.
References do_colorband(), and bNode::storage.
Referenced by node_composit_exec_valtorgb().
static void do_rgbtobw (bNode * UNUSEDnode, float * out, float * in) [static]
Definition at line 112 of file node_composite_valToRgb.c.
Referenced by node_composit_exec_rgbtobw().
static void node_composit_exec_rgbtobw (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 117 of file node_composite_valToRgb.c.
References alloc_compbuf(), CB_RGBA, CB_VAL, composit1_pixel_processor(), bNodeStack::data, data, do_rgbtobw(), NULL, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_rgbtobw().
static void node_composit_exec_valtorgb (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 52 of file node_composite_valToRgb.c.
References alloc_compbuf(), CB_RGBA, CB_VAL, CHAN_A, composit1_pixel_processor(), bNodeStack::data, data, do_colorband(), do_colorband_composit(), NULL, bNode::storage, valbuf_from_rgbabuf(), bNodeStack::vec, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_valtorgb().
static void node_composit_init_valtorgb (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 81 of file node_composite_valToRgb.c.
References add_colorband(), and bNode::storage.
Referenced by register_node_type_cmp_valtorgb().
void register_node_type_cmp_rgbtobw (bNodeTreeType * ttype)
Definition at line 140 of file node_composite_valToRgb.c.
References CMP_NODE_RGBTOBW, NODE_CLASS_CONVERTOR, node_composit_exec_rgbtobw(), node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_valtorgb (bNodeTreeType * ttype)
Definition at line 86 of file node_composite_valToRgb.c.
References CMP_NODE_VALTORGB, NODE_CLASS_CONVERTOR, node_composit_exec_valtorgb(), node_composit_init_valtorgb(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_rgbtobw_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          0.8f, 0.8f, 0.8f, 1.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 103 of file node_composite_valToRgb.c.
bNodeSocketTemplate cmp_node_rgbtobw_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "Val",           0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 107 of file node_composite_valToRgb.c.
bNodeSocketTemplate cmp_node_valtorgb_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Fac",           0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_FACTOR},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_composite_valToRgb.c.
bNodeSocketTemplate cmp_node_valtorgb_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   SOCK_FLOAT, 0, "Alpha"},
    {   -1, 0, ""   }
}
Definition at line 41 of file node_composite_valToRgb.c.