Blender: CParser Class Reference
CParser Class Reference
#include <InputParser.h>
Public Member Functions
CParser ()
virtual ~CParser ()
float GetFloat (STR_String &txt)
CValue * GetValue (STR_String &txt, bool bFallbackToText=false)
CExpression * ProcessText (const char *intext)
void SetContext (CValue *context)
Detailed Description
Definition at line 28 of file InputParser.h.
Constructor & Destructor Documentation
CParser::CParser ()
Definition at line 54 of file InputParser.cpp.
CParser::~CParser () [virtual]
Definition at line 60 of file InputParser.cpp.
References CValue::Release().
Member Function Documentation
float CParser::GetFloat (STR_String & txt)
Definition at line 604 of file InputParser.cpp.
References CExpression::Calculate(), CValue::GetNumber(), NULL, ProcessText(), CExpression::Release(), and CValue::Release().
CValue * CParser::GetValue (STR_String & txt, bool bFallbackToText = false)
Definition at line 629 of file InputParser.cpp.
References CExpression::Calculate(), CValue::IsError(), STR_String::Length(), NULL, ProcessText(), CExpression::Release(), and CValue::Release().
CExpression * CParser::ProcessText (const char * intext)
Definition at line 567 of file InputParser.cpp.
References NULL, and VALUE_ADD_OPERATOR.
Referenced by EXP_ParseInput(), GetFloat(), GetValue(), SCA_PropertySensor::PrecalculateRangeExpression(), SCA_ExpressionController::Trigger(), and SCA_PropertyActuator::Update().
void CParser::SetContext (CValue * context)
Definition at line 658 of file InputParser.cpp.
References CValue::Release().
Referenced by SCA_PropertySensor::PrecalculateRangeExpression(), SCA_ExpressionController::Trigger(), and SCA_PropertyActuator::Update().
The documentation for this class was generated from the following files:
InputParser.h
InputParser.cpp