Blender: rna_access.c File Reference
rna_access.c File Reference
RNA
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <ctype.h>
#include "MEM_guardedalloc.h"
#include "DNA_ID.h"
#include "DNA_scene_types.h"
#include "DNA_windowmanager_types.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BLI_dynstr.h"
#include "BLI_ghash.h"
#include "BLF_api.h"
#include "BLF_translation.h"
#include "BKE_animsys.h"
#include "BKE_context.h"
#include "BKE_idprop.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "WM_api.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "DNA_object_types.h"
#include "BKE_depsgraph.h"
#include "WM_types.h"
#include "rna_internal.h"
Classes
struct tRnaUpdateCacheElem
struct IDP_Chain
Defines
#define RAW_GET(dtype, var, raw, a)
#define RAW_SET(dtype, raw, a, var)
Typedefs
typedef struct tRnaUpdateCacheElem tRnaUpdateCacheElem
typedef struct IDP_Chain IDP_Chain
Functions
void RNA_init (void)
void RNA_exit (void)
void RNA_main_pointer_create (struct Main *main, PointerRNA *r_ptr)
void RNA_id_pointer_create (ID *id, PointerRNA *r_ptr)
void RNA_pointer_create (ID *id, StructRNA *type, void *data, PointerRNA *r_ptr)
static void rna_pointer_inherit_id (StructRNA *type, PointerRNA *parent, PointerRNA *ptr)
void RNA_blender_rna_pointer_create (PointerRNA *r_ptr)
PointerRNA rna_pointer_inherit_refine (PointerRNA *ptr, StructRNA *type, void *data)
void RNA_pointer_recast (PointerRNA *ptr, PointerRNA *r_ptr)
static void rna_idproperty_touch (IDProperty *idprop)
IDProperty * rna_idproperty_ui (PropertyRNA *prop)
IDProperty * RNA_struct_idprops (PointerRNA *ptr, int create)
int RNA_struct_idprops_check (StructRNA *srna)
static IDProperty * rna_idproperty_find (PointerRNA *ptr, const char *name)
static int rna_ensure_property_array_length (PointerRNA *ptr, PropertyRNA *prop)
static int rna_ensure_property_array_check (PropertyRNA *prop)
static void rna_ensure_property_multi_array_length (PointerRNA *ptr, PropertyRNA *prop, int length[])
static int rna_idproperty_verify_valid (PointerRNA *ptr, PropertyRNA *prop, IDProperty *idprop)
IDProperty * rna_idproperty_check (PropertyRNA **prop, PointerRNA *ptr)
static PropertyRNA * rna_ensure_property (PropertyRNA *prop)
static const char * rna_ensure_property_identifier (PropertyRNA *prop)
static const char * rna_ensure_property_description (PropertyRNA *prop)
static const char * rna_ensure_property_name (PropertyRNA *prop)
StructRNA * RNA_struct_find (const char *identifier)
const char * RNA_struct_identifier (StructRNA *type)
const char * RNA_struct_ui_name (StructRNA *type)
int RNA_struct_ui_icon (StructRNA *type)
const char * RNA_struct_ui_description (StructRNA *type)
PropertyRNA * RNA_struct_name_property (StructRNA *type)
PropertyRNA * RNA_struct_iterator_property (StructRNA *type)
StructRNA * RNA_struct_base (StructRNA *type)
int RNA_struct_is_ID (StructRNA *type)
int RNA_struct_undo_check (StructRNA *type)
int RNA_struct_idprops_register_check (StructRNA *type)
int RNA_struct_idprops_unset (PointerRNA *ptr, const char *identifier)
int RNA_struct_is_a (StructRNA *type, StructRNA *srna)
PropertyRNA * RNA_struct_find_property (PointerRNA *ptr, const char *identifier)
PropertyRNA * RNA_struct_find_nested (PointerRNA *ptr, StructRNA *srna)
int RNA_struct_contains_property (PointerRNA *ptr, PropertyRNA *prop_test)
struct ListBase * RNA_struct_type_properties (StructRNA *srna)
PropertyRNA * RNA_struct_type_find_property (StructRNA *srna, const char *identifier)
FunctionRNA * RNA_struct_find_function (PointerRNA *ptr, const char *identifier)
struct ListBase * RNA_struct_type_functions (StructRNA *srna)
StructRegisterFunc RNA_struct_register (StructRNA *type)
StructUnregisterFunc RNA_struct_unregister (StructRNA *type)
void ** RNA_struct_instance (PointerRNA *ptr)
void * RNA_struct_py_type_get (StructRNA *srna)
void RNA_struct_py_type_set (StructRNA *srna, void *py_type)
void * RNA_struct_blender_type_get (StructRNA *srna)
void RNA_struct_blender_type_set (StructRNA *srna, void *blender_type)
char * RNA_struct_name_get_alloc (PointerRNA *ptr, char *fixedbuf, int fixedlen, int *r_len)
const char * RNA_property_identifier (PropertyRNA *prop)
const char * RNA_property_description (PropertyRNA *prop)
PropertyType RNA_property_type (PropertyRNA *prop)
PropertySubType RNA_property_subtype (PropertyRNA *prop)
PropertyUnit RNA_property_unit (PropertyRNA *prop)
int RNA_property_flag (PropertyRNA *prop)
void * RNA_property_py_data_get (PropertyRNA *prop)
int RNA_property_array_length (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_array_check (PropertyRNA *prop)
int RNA_property_array_dimension (PointerRNA *ptr, PropertyRNA *prop, int length[])
int RNA_property_multi_array_length (PointerRNA *ptr, PropertyRNA *prop, int dim)
char RNA_property_array_item_char (PropertyRNA *prop, int index)
int RNA_property_array_item_index (PropertyRNA *prop, char name)
void RNA_property_int_range (PointerRNA *ptr, PropertyRNA *prop, int *hardmin, int *hardmax)
void RNA_property_int_ui_range (PointerRNA *ptr, PropertyRNA *prop, int *softmin, int *softmax, int *step)
void RNA_property_float_range (PointerRNA *ptr, PropertyRNA *prop, float *hardmin, float *hardmax)
void RNA_property_float_ui_range (PointerRNA *ptr, PropertyRNA *prop, float *softmin, float *softmax, float *step, float *precision)
int RNA_property_float_clamp (PointerRNA *ptr, PropertyRNA *prop, float *value)
int RNA_property_int_clamp (PointerRNA *ptr, PropertyRNA *prop, int *value)
int RNA_property_string_maxlength (PropertyRNA *prop)
StructRNA * RNA_property_pointer_type (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_pointer_poll (PointerRNA *ptr, PropertyRNA *prop, PointerRNA *value)
void RNA_property_enum_items (bContext *C, PointerRNA *ptr, PropertyRNA *prop, EnumPropertyItem **item, int *totitem, int *free)
void RNA_property_enum_items_gettexted (bContext *C, PointerRNA *ptr, PropertyRNA *prop, EnumPropertyItem **item, int *totitem, int *free)
int RNA_property_enum_value (bContext *C, PointerRNA *ptr, PropertyRNA *prop, const char *identifier, int *value)
int RNA_enum_identifier (EnumPropertyItem *item, const int value, const char **identifier)
int RNA_enum_bitflag_identifiers (EnumPropertyItem *item, const int value, const char **identifier)
int RNA_enum_name (EnumPropertyItem *item, const int value, const char **name)
int RNA_enum_description (EnumPropertyItem *item, const int value, const char **description)
int RNA_property_enum_identifier (bContext *C, PointerRNA *ptr, PropertyRNA *prop, const int value, const char **identifier)
int RNA_property_enum_name (bContext *C, PointerRNA *ptr, PropertyRNA *prop, const int value, const char **name)
int RNA_property_enum_bitflag_identifiers (bContext *C, PointerRNA *ptr, PropertyRNA *prop, const int value, const char **identifier)
const char * RNA_property_ui_name (PropertyRNA *prop)
const char * RNA_property_ui_description (PropertyRNA *prop)
int RNA_property_ui_icon (PropertyRNA *prop)
int RNA_property_editable (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_editable_flag (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_editable_index (PointerRNA *ptr, PropertyRNA *prop, int index)
int RNA_property_animateable (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_animated (PointerRNA *UNUSED(ptr), PropertyRNA *UNUSED(prop))
int RNA_property_path_from_ID_check (PointerRNA *ptr, PropertyRNA *prop)
static void rna_property_update (bContext *C, Main *bmain, Scene *scene, PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_update_check (PropertyRNA *prop)
void RNA_property_update (bContext *C, PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_update_main (Main *bmain, Scene *scene, PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_update_cache_add (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_update_cache_flush (Main *bmain, Scene *scene)
void RNA_property_update_cache_free (void)
int RNA_property_boolean_get (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_boolean_set (PointerRNA *ptr, PropertyRNA *prop, int value)
void RNA_property_boolean_get_array (PointerRNA *ptr, PropertyRNA *prop, int *values)
int RNA_property_boolean_get_index (PointerRNA *ptr, PropertyRNA *prop, int index)
void RNA_property_boolean_set_array (PointerRNA *ptr, PropertyRNA *prop, const int *values)
void RNA_property_boolean_set_index (PointerRNA *ptr, PropertyRNA *prop, int index, int value)
int RNA_property_boolean_get_default (PointerRNA *UNUSED(ptr), PropertyRNA *prop)
void RNA_property_boolean_get_default_array (PointerRNA *UNUSED(ptr), PropertyRNA *prop, int *values)
int RNA_property_boolean_get_default_index (PointerRNA *ptr, PropertyRNA *prop, int index)
int RNA_property_int_get (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_int_set (PointerRNA *ptr, PropertyRNA *prop, int value)
void RNA_property_int_get_array (PointerRNA *ptr, PropertyRNA *prop, int *values)
void RNA_property_int_get_array_range (PointerRNA *ptr, PropertyRNA *prop, int values[2])
int RNA_property_int_get_index (PointerRNA *ptr, PropertyRNA *prop, int index)
void RNA_property_int_set_array (PointerRNA *ptr, PropertyRNA *prop, const int *values)
void RNA_property_int_set_index (PointerRNA *ptr, PropertyRNA *prop, int index, int value)
int RNA_property_int_get_default (PointerRNA *UNUSED(ptr), PropertyRNA *prop)
void RNA_property_int_get_default_array (PointerRNA *UNUSED(ptr), PropertyRNA *prop, int *values)
int RNA_property_int_get_default_index (PointerRNA *ptr, PropertyRNA *prop, int index)
float RNA_property_float_get (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_float_set (PointerRNA *ptr, PropertyRNA *prop, float value)
void RNA_property_float_get_array (PointerRNA *ptr, PropertyRNA *prop, float *values)
void RNA_property_float_get_array_range (PointerRNA *ptr, PropertyRNA *prop, float values[2])
float RNA_property_float_get_index (PointerRNA *ptr, PropertyRNA *prop, int index)
void RNA_property_float_set_array (PointerRNA *ptr, PropertyRNA *prop, const float *values)
void RNA_property_float_set_index (PointerRNA *ptr, PropertyRNA *prop, int index, float value)
float RNA_property_float_get_default (PointerRNA *UNUSED(ptr), PropertyRNA *prop)
void RNA_property_float_get_default_array (PointerRNA *UNUSED(ptr), PropertyRNA *prop, float *values)
float RNA_property_float_get_default_index (PointerRNA *ptr, PropertyRNA *prop, int index)
void RNA_property_string_get (PointerRNA *ptr, PropertyRNA *prop, char *value)
char * RNA_property_string_get_alloc (PointerRNA *ptr, PropertyRNA *prop, char *fixedbuf, int fixedlen, int *r_len)
int RNA_property_string_length (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_string_set (PointerRNA *ptr, PropertyRNA *prop, const char *value)
void RNA_property_string_get_default (PointerRNA *UNUSED(ptr), PropertyRNA *prop, char *value)
char * RNA_property_string_get_default_alloc (PointerRNA *ptr, PropertyRNA *prop, char *fixedbuf, int fixedlen)
int RNA_property_string_default_length (PointerRNA *UNUSED(ptr), PropertyRNA *prop)
int RNA_property_enum_get (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_enum_set (PointerRNA *ptr, PropertyRNA *prop, int value)
int RNA_property_enum_get_default (PointerRNA *UNUSED(ptr), PropertyRNA *prop)
void * RNA_property_enum_py_data_get (PropertyRNA *prop)
PointerRNA RNA_property_pointer_get (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_pointer_set (PointerRNA *ptr, PropertyRNA *prop, PointerRNA ptr_value)
PointerRNA RNA_property_pointer_get_default (PointerRNA *UNUSED(ptr), PropertyRNA *UNUSED(prop))
void RNA_property_pointer_add (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_pointer_remove (PointerRNA *ptr, PropertyRNA *prop)
static void rna_property_collection_get_idp (CollectionPropertyIterator *iter)
void RNA_property_collection_begin (PointerRNA *ptr, PropertyRNA *prop, CollectionPropertyIterator *iter)
void RNA_property_collection_next (CollectionPropertyIterator *iter)
void RNA_property_collection_end (CollectionPropertyIterator *iter)
int RNA_property_collection_length (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_collection_add (PointerRNA *ptr, PropertyRNA *prop, PointerRNA *r_ptr)
int RNA_property_collection_remove (PointerRNA *ptr, PropertyRNA *prop, int key)
int RNA_property_collection_move (PointerRNA *ptr, PropertyRNA *prop, int key, int pos)
void RNA_property_collection_clear (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_collection_lookup_index (PointerRNA *ptr, PropertyRNA *prop, PointerRNA *t_ptr)
int RNA_property_collection_lookup_int (PointerRNA *ptr, PropertyRNA *prop, int key, PointerRNA *r_ptr)
int RNA_property_collection_lookup_string (PointerRNA *ptr, PropertyRNA *prop, const char *key, PointerRNA *r_ptr)
int RNA_property_collection_assign_int (PointerRNA *ptr, PropertyRNA *prop, const int key, const PointerRNA *assign_ptr)
int RNA_property_collection_type_get (PointerRNA *ptr, PropertyRNA *prop, PointerRNA *r_ptr)
int RNA_property_collection_raw_array (PointerRNA *ptr, PropertyRNA *prop, PropertyRNA *itemprop, RawArray *array)
int RNA_raw_type_sizeof (RawPropertyType type)
static int rna_raw_access (ReportList *reports, PointerRNA *ptr, PropertyRNA *prop, const char *propname, void *inarray, RawPropertyType intype, int inlen, int set)
RawPropertyType RNA_property_raw_type (PropertyRNA *prop)
int RNA_property_collection_raw_get (ReportList *reports, PointerRNA *ptr, PropertyRNA *prop, const char *propname, void *array, RawPropertyType type, int len)
int RNA_property_collection_raw_set (ReportList *reports, PointerRNA *ptr, PropertyRNA *prop, const char *propname, void *array, RawPropertyType type, int len)
void rna_iterator_listbase_begin (CollectionPropertyIterator *iter, ListBase *lb, IteratorSkipFunc skip)
void rna_iterator_listbase_next (CollectionPropertyIterator *iter)
void * rna_iterator_listbase_get (CollectionPropertyIterator *iter)
void rna_iterator_listbase_end (CollectionPropertyIterator *iter)
PointerRNA rna_listbase_lookup_int (PointerRNA *ptr, StructRNA *type, struct ListBase *lb, int index)
void rna_iterator_array_begin (CollectionPropertyIterator *iter, void *ptr, int itemsize, int length, int free_ptr, IteratorSkipFunc skip)
void rna_iterator_array_next (CollectionPropertyIterator *iter)
void * rna_iterator_array_get (CollectionPropertyIterator *iter)
void * rna_iterator_array_dereference_get (CollectionPropertyIterator *iter)
void rna_iterator_array_end (CollectionPropertyIterator *iter)
PointerRNA rna_array_lookup_int (PointerRNA *ptr, StructRNA *type, void *data, int itemsize, int length, int index)
static char * rna_path_token (const char **path, char *fixedbuf, int fixedlen, int bracket)
static int rna_token_strip_quotes (char *token)
int RNA_path_resolve (PointerRNA *ptr, const char *path, PointerRNA *r_ptr, PropertyRNA **r_prop)
int RNA_path_resolve_full (PointerRNA *ptr, const char *path, PointerRNA *r_ptr, PropertyRNA **r_prop, int *index)
char * RNA_path_append (const char *path, PointerRNA *UNUSED(ptr), PropertyRNA *prop, int intkey, const char *strkey)
char * RNA_path_back (const char *path)
static char * rna_idp_path_create (IDP_Chain *child_link)
static char * rna_idp_path (PointerRNA *ptr, IDProperty *haystack, IDProperty *needle, IDP_Chain *parent_link)
static char * rna_path_from_ID_to_idpgroup (PointerRNA *ptr)
char * RNA_path_from_ID_to_struct (PointerRNA *ptr)
char * RNA_path_from_ID_to_property (PointerRNA *ptr, PropertyRNA *prop)
int RNA_boolean_get (PointerRNA *ptr, const char *name)
void RNA_boolean_set (PointerRNA *ptr, const char *name, int value)
void RNA_boolean_get_array (PointerRNA *ptr, const char *name, int *values)
void RNA_boolean_set_array (PointerRNA *ptr, const char *name, const int *values)
int RNA_int_get (PointerRNA *ptr, const char *name)
void RNA_int_set (PointerRNA *ptr, const char *name, int value)
void RNA_int_get_array (PointerRNA *ptr, const char *name, int *values)
void RNA_int_set_array (PointerRNA *ptr, const char *name, const int *values)
float RNA_float_get (PointerRNA *ptr, const char *name)
void RNA_float_set (PointerRNA *ptr, const char *name, float value)
void RNA_float_get_array (PointerRNA *ptr, const char *name, float *values)
void RNA_float_set_array (PointerRNA *ptr, const char *name, const float *values)
int RNA_enum_get (PointerRNA *ptr, const char *name)
void RNA_enum_set (PointerRNA *ptr, const char *name, int value)
void RNA_enum_set_identifier (PointerRNA *ptr, const char *name, const char *id)
int RNA_enum_is_equal (bContext *C, PointerRNA *ptr, const char *name, const char *enumname)
int RNA_enum_value_from_id (EnumPropertyItem *item, const char *identifier, int *value)
int RNA_enum_id_from_value (EnumPropertyItem *item, int value, const char **identifier)
int RNA_enum_icon_from_value (EnumPropertyItem *item, int value, int *icon)
void RNA_string_get (PointerRNA *ptr, const char *name, char *value)
char * RNA_string_get_alloc (PointerRNA *ptr, const char *name, char *fixedbuf, int fixedlen)
int RNA_string_length (PointerRNA *ptr, const char *name)
void RNA_string_set (PointerRNA *ptr, const char *name, const char *value)
PointerRNA RNA_pointer_get (PointerRNA *ptr, const char *name)
void RNA_pointer_set (PointerRNA *ptr, const char *name, PointerRNA ptr_value)
void RNA_pointer_add (PointerRNA *ptr, const char *name)
void RNA_collection_begin (PointerRNA *ptr, const char *name, CollectionPropertyIterator *iter)
void RNA_collection_add (PointerRNA *ptr, const char *name, PointerRNA *r_value)
void RNA_collection_clear (PointerRNA *ptr, const char *name)
int RNA_collection_length (PointerRNA *ptr, const char *name)
int RNA_property_is_set (PointerRNA *ptr, PropertyRNA *prop)
int RNA_struct_property_is_set (PointerRNA *ptr, const char *identifier)
int RNA_property_is_idprop (PropertyRNA *prop)
char * RNA_pointer_as_string (bContext *C, PointerRNA *ptr)
char * RNA_pointer_as_string_keywords_ex (bContext *C, PointerRNA *ptr, PointerRNA *ptr_default, const short as_function, const short all_args, PropertyRNA *iterprop)
char * RNA_pointer_as_string_keywords (bContext *C, PointerRNA *ptr, PointerRNA *ptr_default, const short as_function, const short all_args)
char * RNA_function_as_string_keywords (bContext *C, FunctionRNA *func, PointerRNA *ptr_default, const short as_function, const short all_args)
char * RNA_property_as_string (bContext *C, PointerRNA *ptr, PropertyRNA *prop)
const char * RNA_function_identifier (FunctionRNA *func)
const char * RNA_function_ui_description (FunctionRNA *func)
int RNA_function_flag (FunctionRNA *func)
int RNA_function_defined (FunctionRNA *func)
PropertyRNA * RNA_function_get_parameter (PointerRNA *UNUSED(ptr), FunctionRNA *func, int index)
PropertyRNA * RNA_function_find_parameter (PointerRNA *UNUSED(ptr), FunctionRNA *func, const char *identifier)
struct ListBase * RNA_function_defined_parameters (FunctionRNA *func)
ParameterList * RNA_parameter_list_create (ParameterList *parms, PointerRNA *UNUSED(ptr), FunctionRNA *func)
void RNA_parameter_list_free (ParameterList *parms)
int RNA_parameter_list_size (ParameterList *parms)
int RNA_parameter_list_arg_count (ParameterList *parms)
int RNA_parameter_list_ret_count (ParameterList *parms)
void RNA_parameter_list_begin (ParameterList *parms, ParameterIterator *iter)
void RNA_parameter_list_next (ParameterIterator *iter)
void RNA_parameter_list_end (ParameterIterator *UNUSED(iter))
void RNA_parameter_get (ParameterList *parms, PropertyRNA *parm, void **value)
void RNA_parameter_get_lookup (ParameterList *parms, const char *identifier, void **value)
void RNA_parameter_set (ParameterList *parms, PropertyRNA *parm, const void *value)
void RNA_parameter_set_lookup (ParameterList *parms, const char *identifier, const void *value)
int RNA_parameter_length_get (ParameterList *parms, PropertyRNA *parm)
void RNA_parameter_length_set (ParameterList *parms, PropertyRNA *parm, int length)
int RNA_parameter_length_get_data (ParameterList *UNUSED(parms), PropertyRNA *UNUSED(parm), void *data)
void RNA_parameter_length_set_data (ParameterList *UNUSED(parms), PropertyRNA *UNUSED(parm), void *data, int length)
int RNA_function_call (bContext *C, ReportList *reports, PointerRNA *ptr, FunctionRNA *func, ParameterList *parms)
int RNA_function_call_lookup (bContext *C, ReportList *reports, PointerRNA *ptr, const char *identifier, ParameterList *parms)
int RNA_function_call_direct (bContext *C, ReportList *reports, PointerRNA *ptr, FunctionRNA *func, const char *format,...)
int RNA_function_call_direct_lookup (bContext *C, ReportList *reports, PointerRNA *ptr, const char *identifier, const char *format,...)
static int rna_function_format_array_length (const char *format, int ofs, int flen)
static int rna_function_parameter_parse (PointerRNA *ptr, PropertyRNA *prop, PropertyType type, char ftype, int len, void *dest, void *src, StructRNA *srna, const char *tid, const char *fid, const char *pid)
int RNA_function_call_direct_va (bContext *C, ReportList *reports, PointerRNA *ptr, FunctionRNA *func, const char *format, va_list args)
int RNA_function_call_direct_va_lookup (bContext *C, ReportList *reports, PointerRNA *ptr, const char *identifier, const char *format, va_list args)
int RNA_property_reset (PointerRNA *ptr, PropertyRNA *prop, int index)
int RNA_property_copy (PointerRNA *ptr, PointerRNA *fromptr, PropertyRNA *prop, int index)
void _RNA_warning (const char *format,...)
Variables
const PointerRNA PointerRNA_NULL = {{NULL}}
static PropertyRNA * typemap [IDP_NUMTYPES]
static PropertyRNA * arraytypemap [IDP_NUMTYPES]
EnumPropertyItem DummyRNA_NULL_items []
EnumPropertyItem DummyRNA_DEFAULT_items []
static ListBase rna_updates_cache = {NULL, NULL}
Detailed Description
Definition in file rna_access.c.
Define Documentation
#define RAW_GET (dtype, var, raw, a)
Value:
{                                                                             \
    switch (raw.type) {                                                       \
        case PROP_RAW_CHAR: var = (dtype)((char*)raw.array)[a]; break;        \
        case PROP_RAW_SHORT: var = (dtype)((short*)raw.array)[a]; break;      \
        case PROP_RAW_INT: var = (dtype)((int*)raw.array)[a]; break;          \
        case PROP_RAW_FLOAT: var = (dtype)((float*)raw.array)[a]; break;      \
        case PROP_RAW_DOUBLE: var = (dtype)((double*)raw.array)[a]; break;    \
        default: var = (dtype)0;                                              \
    }                                                                         \
}
Definition at line 3011 of file rna_access.c.
Referenced by rna_raw_access().
#define RAW_SET (dtype, raw, a, var)
Value:
{                                                                             \
    switch (raw.type) {                                                       \
        case PROP_RAW_CHAR: ((char*)raw.array)[a] = (char)var; break;         \
        case PROP_RAW_SHORT: ((short*)raw.array)[a] = (short)var; break;      \
        case PROP_RAW_INT: ((int*)raw.array)[a] = (int)var; break;            \
        case PROP_RAW_FLOAT: ((float*)raw.array)[a] = (float)var; break;      \
        case PROP_RAW_DOUBLE: ((double*)raw.array)[a] = (double)var; break;   \
        default: break;                                                       \
    }                                                                         \
}
Definition at line 3023 of file rna_access.c.
Referenced by rna_raw_access().
Typedef Documentation
typedef struct IDP_Chain IDP_Chain
typedef struct tRnaUpdateCacheElem tRnaUpdateCacheElem
Function Documentation
void _RNA_warning (const char * format, ...)
Definition at line 5713 of file rna_access.c.
References PyC_LineSpit().
PointerRNA rna_array_lookup_int (PointerRNA * ptr, StructRNA * type, void * data, int itemsize, int length, int index)
Definition at line 3485 of file rna_access.c.
References PointerRNA_NULL, and rna_pointer_inherit_refine().
void RNA_blender_rna_pointer_create (PointerRNA * r_ptr)
Definition at line 173 of file rna_access.c.
References BLENDER_RNA, PointerRNA::data, PointerRNA::id, NULL, RNA_BlenderRNA, and PointerRNA::type.
Referenced by BPY_rna_types(), pyrna_alloc_types(), pyrna_free_types(), and pyrna_unregister_class().
int RNA_boolean_get (PointerRNA * ptr, const char * name)
Definition at line 4101 of file rna_access.c.
References StructRNA::identifier, RNA_property_boolean_get(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by actkeys_borderselect_exec(), actkeys_clickselect_invoke(), actkeys_deselectall_exec(), actkeys_select_leftright_exec(), add_driver_button_exec(), add_keyingset_button_exec(), add_named_exec(), animchannels_borderselect_exec(), animchannels_collapse_exec(), animchannels_deselectall_exec(), animchannels_expand_exec(), animchannels_mouseclick_invoke(), armature_calc_roll_exec(), armature_extrude_exec(), armature_hide_exec(), armature_select_hierarchy_exec(), armature_select_linked_invoke(), border_select_exec(), border_select_graph_exec(), borderselect_exec(), brush_edit_apply(), clear_track_path_exec(), connect_hair_exec(), console_clear_exec(), console_history_append_exec(), console_history_cycle_exec(), convert_exec(), copy_to_selected_button_exec(), create_orientation_exec(), delete_key_button_exec(), delete_key_exec(), disconnect_hair_exec(), draw_actuator_action(), draw_actuator_constraint(), draw_actuator_filter_2d(), draw_actuator_header(), draw_actuator_motion(), draw_actuator_parent(), draw_actuator_sound(), draw_actuator_steering(), draw_brick_actuator(), draw_brick_controller(), draw_brick_sensor(), draw_controller_header(), draw_modifier__stepped(), draw_sensor_collision(), draw_sensor_header(), draw_sensor_internal_header(), draw_sensor_joystick(), draw_sensor_keyboard(), duplicate_exec(), ED_fileselect_set_params(), ed_marker_border_select_exec(), ed_marker_select_invoke(), ED_object_add_generic_get_opts(), edbm_bevel_exec(), edbm_blend_from_shape_exec(), edbm_dissolve_exec(), edbm_dupli_extrude_cursor_invoke(), edbm_hide_exec(), edbm_inset_exec(), edbm_loop_multiselect_exec(), edbm_loop_to_region_exec(), edbm_mark_seam(), edbm_mark_sharp(), edbm_merge_exec(), edbm_normals_make_consistent_exec(), edbm_quads_convert_to_tris_exec(), edbm_select_linked_exec(), edbm_select_linked_pick_invoke(), edbm_select_loop_invoke(), edbm_select_mirror_exec(), edbm_select_random_exec(), edbm_spin_exec(), edbm_subdivide_exec(), edbm_tris_convert_to_quads_exec(), enable_manipulator_invoke(), face_select_hide_exec(), file_border_select_exec(), file_draw_check_exists(), file_exec(), file_select_invoke(), file_sfile_to_operator(), frame_jump_exec(), get_boolean(), BlenderSync::get_scene_params(), gpencil_draw_exec(), graph_fmodifier_add_exec(), graph_fmodifier_add_invoke(), graph_panel_view(), graphkeys_borderselect_exec(), graphkeys_clickselect_invoke(), graphkeys_deselectall_exec(), graphkeys_select_leftright_exec(), hide_exec(), hide_metaelems_exec(), hide_tracks_exec(), image_cycle_render_slot_exec(), image_invert_exec(), image_new_exec(), image_pack_exec(), image_pack_invoke(), image_pack_test(), image_save_as_draw_check_prop(), initSnapping(), initTransInfo(), insert_key_button_exec(), insert_key_exec(), insert_key_menu_invoke(), keyframe_jump_exec(), knifetool_init(), line_break_exec(), logic_buttons_new(), make_single_user_exec(), minimize_stretch_init(), mode_set_exec(), multires_external_save_exec(), nla_fmodifier_add_exec(), nla_panel_actclip(), nla_panel_evaluation(), nla_panel_properties(), nlachannels_mouseclick_invoke(), nlaedit_add_tracks_exec(), nlaedit_borderselect_exec(), nlaedit_clickselect_invoke(), nlaedit_deselectall_exec(), nlaedit_select_leftright_exec(), nlaedit_sync_actlen_exec(), node_border_select_invoke(), node_borderselect_exec(), node_composit_buts_blur(), node_composit_buts_color_spill(), node_composit_buts_crop(), node_composit_buts_defocus(), node_composit_buts_file_output_details(), node_composit_buts_lensdist(), node_composit_buts_map_value(), node_duplicate_exec(), node_make_link_exec(), node_select_exec(), node_socket_button_output_file(), object_delete_exec(), object_duplicates_make_real_exec(), object_hide_render_set_exec(), object_hide_view_set_exec(), object_mode_set_exec(), object_select_by_layer_exec(), object_select_by_type_exec(), object_select_grouped_exec(), object_select_linked_exec(), object_select_menu_exec(), object_select_mirror_exec(), object_select_random_exec(), object_transform_apply_exec(), ocean_bake_exec(), outliner_item_activate(), outliner_item_openclose(), outliner_one_level_exec(), outliner_scroll_page_exec(), paint_select_linked_pick_invoke(), pin_exec(), pose_armature_layers_showall_exec(), pose_hide_exec(), pose_ik_add_exec(), pose_paste_exec(), pose_select_connected_invoke(), pose_select_grouped_exec(), pose_select_hierarchy_exec(), ptcache_bake_all_exec(), ptcache_bake_exec(), remove_driver_button_exec(), reset_default_button_exec(), ringsel_init(), save_image_doit(), screen_animation_cancel_exec(), screen_animation_play_exec(), screen_opengl_render_exec(), screen_opengl_render_init(), screen_opengl_render_invoke(), screen_opengl_render_modal(), screen_render_exec(), screen_render_invoke(), screencast_exec(), screenshot_exec(), sculpt_brush_stroke_invoke(), sculpt_update_cache_variants(), select_exec(), select_invoke(), select_linked_exec(), select_linked_internal(), select_linked_pick_invoke(), select_loop_exec(), select_random_exec(), seq_load_operator_info(), sequencer_add_effect_strip_exec(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_borderselect_exec(), sequencer_change_path_exec(), sequencer_mute_exec(), sequencer_reload_exec(), sequencer_select_grouped_exec(), sequencer_select_invoke(), sequencer_select_linked_pick_invoke(), sequencer_unmute_exec(), set_style_exec(), shape_key_add_exec(), sketch_draw_gesture(), sketch_draw_modal(), sketch_draw_preview(), sketch_draw_stroke(), stitch_init(), text_open_exec(), text_paste_exec(), text_set_selection_invoke(), text_to_3d_object_exec(), track_markers_exec(), track_markers_invoke(), uiTemplateImage(), unwrap_exec(), uv_from_view_exec(), uv_map_clip_correct(), v3d_transform_butsR(), vertex_group_assign_exec(), vertex_group_clean_exec(), vertex_group_invert_exec(), vertex_group_mirror_exec(), vertex_group_normalize_all_exec(), vertex_group_remove_exec(), vertex_group_remove_from_exec(), view3d_all_exec(), view3d_borderselect_exec(), view3d_lasso_select_exec(), view3d_layers_exec(), view3d_select_invoke(), view_all_exec(), view_scrolldown_exec(), view_scrollup_exec(), viewnumpad_exec(), wm_handler_fileselect_call(), wm_link_append_exec(), wm_link_append_flag(), wm_ndof_sensitivity_exec(), wm_open_mainfile_exec(), wm_save_as_mainfile_exec(), wm_save_mainfile_invoke(), and wpaint_stroke_update_step().
void RNA_boolean_get_array (PointerRNA * ptr, const char * name, int * values)
Definition at line 4124 of file rna_access.c.
References StructRNA::identifier, RNA_property_boolean_get_array(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by armature_bone_layers_exec(), ED_object_add_generic_get_opts(), move_to_layer_init(), pose_armature_layers_exec(), pose_armature_layers_invoke(), and pose_bone_layers_exec().
void RNA_boolean_set (PointerRNA * ptr, const char * name, int value)
Definition at line 4114 of file rna_access.c.
References StructRNA::identifier, RNA_property_boolean_set(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by action_keymap_keyframes(), brush_edit_apply_event(), clip_keymap(), console_keymap(), ED_fileselect_set_params(), ED_keymap_animchannels(), ED_keymap_armature(), ED_keymap_curve(), ED_keymap_mesh(), ED_keymap_metaball(), ED_keymap_object(), ED_keymap_paint(), ED_keymap_screen(), ED_keymap_uvedit(), ED_marker_keymap(), ED_object_add_generic_get_opts(), ED_operatormacros_armature(), ED_operatormacros_clip(), ED_operatormacros_curve(), ED_operatormacros_mesh(), ED_operatormacros_node(), ED_operatormacros_object(), file_browse_invoke(), file_keymap(), gpencil_draw_apply_event(), graph_fmodifier_add_invoke(), graphedit_keymap_keyframes(), image_keymap(), image_replace_invoke(), image_save_as_invoke(), initTransInfo(), insert_key_menu_invoke(), keymap_particle(), linked_limit_default(), nla_keymap_channels(), nla_keymap_main(), node_keymap(), object_add_generic_invoke_options(), object_camera_add_exec(), object_mouse_select_menu(), open_invoke(), open_set_load_ui(), open_set_use_scripts(), outliner_keymap(), paint_brush_stroke_add_step(), save_set_compress(), screen_opengl_render_init(), sequencer_change_path_invoke(), sequencer_keymap(), sketch_draw_modal(), stitch_exit(), text_keymap(), transform_keymap_for_space(), ui_keymap_but_cb(), ui_set_but_default(), UI_view2d_keymap(), uiItemBooleanO(), uiLayoutOperatorButs(), view3d_keymap(), view3d_layers_invoke(), and wm_window_keymap().
void RNA_boolean_set_array (PointerRNA * ptr, const char * name, const int * values)
Definition at line 4134 of file rna_access.c.
References StructRNA::identifier, RNA_property_boolean_set_array(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by armature_bone_layers_exec(), armature_bone_layers_invoke(), BIF_do_manipulator(), move_to_layer_init(), object_add_generic_invoke_options(), pose_armature_layers_exec(), pose_armature_layers_invoke(), pose_armature_layers_showall_exec(), pose_bone_layers_exec(), and pose_bone_layers_invoke().
void RNA_collection_add (PointerRNA * ptr, const char * name, PointerRNA * r_value)
Definition at line 4425 of file rna_access.c.
References StructRNA::identifier, RNA_property_collection_add(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by brush_edit_apply_event(), gesture_lasso_apply(), gpencil_draw_apply_event(), paint_apply_event(), paint_brush_stroke_add_step(), sequencer_drop_copy(), and stitch_exit().
void RNA_collection_begin (PointerRNA * ptr, const char * name, CollectionPropertyIterator * iter)
Definition at line 4415 of file rna_access.c.
References StructRNA::identifier, RNA_property_collection_begin(), RNA_struct_find_property(), and PointerRNA::type.
void RNA_collection_clear (PointerRNA * ptr, const char * name)
Definition at line 4435 of file rna_access.c.
References StructRNA::identifier, RNA_property_collection_clear(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by gesture_lasso_apply(), sequencer_drop_copy(), and stitch_init().
int RNA_collection_length (PointerRNA * ptr, const char * name)
Definition at line 4445 of file rna_access.c.
References StructRNA::identifier, RNA_property_collection_length(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by sequencer_add_image_strip_invoke(), sequencer_add_movie_strip_invoke(), and sequencer_add_sound_strip_invoke().
static PropertyRNA* rna_ensure_property (PropertyRNA * prop) [static]
Definition at line 432 of file rna_access.c.
References IDP_ARRAY, PropertyRNA::magic, RNA_MAGIC, IDProperty::subtype, and IDProperty::type.
Referenced by RNA_property_animateable(), RNA_property_array_dimension(), RNA_property_array_item_char(), RNA_property_array_item_index(), RNA_property_collection_assign_int(), RNA_property_collection_end(), RNA_property_collection_lookup_int(), RNA_property_collection_lookup_string(), RNA_property_collection_next(), RNA_property_collection_type_get(), RNA_property_editable(), RNA_property_editable_flag(), RNA_property_editable_index(), RNA_property_enum_items(), RNA_property_flag(), RNA_property_float_range(), RNA_property_float_ui_range(), RNA_property_int_range(), RNA_property_int_ui_range(), RNA_property_pointer_poll(), RNA_property_pointer_type(), RNA_property_string_maxlength(), RNA_property_subtype(), RNA_property_type(), RNA_property_ui_icon(), RNA_property_unit(), rna_property_update(), and RNA_property_update_cache_add().
static int rna_ensure_property_array_check (PropertyRNA * prop) [static]
Definition at line 300 of file rna_access.c.
References PropertyRNA::getlength, IDP_ARRAY, PropertyRNA::magic, RNA_MAGIC, PropertyRNA::totarraylength, and IDProperty::type.
Referenced by RNA_property_array_check().
static int rna_ensure_property_array_length (PointerRNA * ptr, PropertyRNA * prop) [static]
Definition at line 284 of file rna_access.c.
References PointerRNA::data, PropertyRNA::getlength, IDP_ARRAY, IDProperty::len, PropertyRNA::magic, RNA_MAGIC, RNA_MAX_ARRAY_DIMENSION, PropertyRNA::totarraylength, and IDProperty::type.
Referenced by rna_idproperty_verify_valid(), RNA_property_array_length(), RNA_property_boolean_get_default_index(), RNA_property_boolean_get_index(), RNA_property_boolean_set_index(), RNA_property_float_get_default_index(), RNA_property_float_get_index(), RNA_property_float_set_index(), RNA_property_int_get_default_index(), RNA_property_int_get_index(), and RNA_property_int_set_index().
static const char* rna_ensure_property_description (PropertyRNA * prop) [static]
Definition at line 457 of file rna_access.c.
References PropertyRNA::description, IDP_GetPropertyTypeFromGroup(), IDP_String, IDP_STRING, uiWidgetColors::item, PropertyRNA::magic, NULL, rna_idproperty_ui(), RNA_MAGIC, and TIP_.
Referenced by RNA_property_description(), and RNA_property_ui_description().
static const char* rna_ensure_property_identifier (PropertyRNA * prop) [static]
Definition at line 449 of file rna_access.c.
References PropertyRNA::identifier, PropertyRNA::magic, and RNA_MAGIC.
Referenced by RNA_property_identifier().
static void rna_ensure_property_multi_array_length (PointerRNA * ptr, PropertyRNA * prop, int length[]) [static]
Definition at line 312 of file rna_access.c.
References PropertyRNA::arraydimension, PropertyRNA::arraylength, PropertyRNA::getlength, IDP_ARRAY, IDProperty::len, PropertyRNA::magic, RNA_MAGIC, and IDProperty::type.
Referenced by RNA_property_array_dimension(), and RNA_property_multi_array_length().
static const char* rna_ensure_property_name (PropertyRNA * prop) [static]
Definition at line 480 of file rna_access.c.
References CTX_IFACE_, PropertyRNA::magic, PropertyRNA::name, RNA_MAGIC, and PropertyRNA::translation_context.
Referenced by RNA_property_ui_name().
int RNA_enum_bitflag_identifiers (EnumPropertyItem * item, const int value, const char ** identifier)
Definition at line 1267 of file rna_access.c.
References EnumPropertyItem::identifier, NULL, and EnumPropertyItem::value.
Referenced by pyrna_enum_bitfield_to_py(), and RNA_property_enum_bitflag_identifiers().
int RNA_enum_description (EnumPropertyItem * item, const int value, const char ** description)
Definition at line 1290 of file rna_access.c.
References EnumPropertyItem::description, EnumPropertyItem::identifier, and EnumPropertyItem::value.
Referenced by redraw_timer_exec().
int RNA_enum_get (PointerRNA * ptr, const char * name)
Definition at line 4230 of file rna_access.c.
References StructRNA::identifier, RNA_property_enum_get(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by actkeys_columnselect_exec(), actkeys_expo_exec(), actkeys_handletype_exec(), actkeys_insertkey_exec(), actkeys_ipo_exec(), actkeys_keytype_exec(), actkeys_mirror_exec(), actkeys_paste_exec(), actkeys_select_leftright_exec(), actkeys_select_leftright_invoke(), actkeys_snap_exec(), actuator_add_exec(), add_primitive_circle_exec(), add_primitive_cone_exec(), add_primitive_cylinder_exec(), align_exec(), animchannels_rearrange_exec(), animchannels_setflag_exec(), area_split_apply(), area_split_init(), area_split_menu_init(), area_split_modal(), armature_autoside_names_exec(), armature_calc_roll_exec(), armature_de_select_all_exec(), armature_merge_exec(), armature_parent_clear_exec(), armature_parent_set_exec(), armature_select_hierarchy_exec(), BL_ConvertActuators(), blender_camera_from_object(), brush_curve_preset_exec(), brush_select_exec(), brush_uv_sculpt_tool_set_exec(), clean_tracks_exec(), clear_track_path_exec(), console_delete_exec(), console_move_exec(), console_scrollback_append_exec(), controller_add_exec(), convert_exec(), de_select_all_exec(), delete_exec(), delete_key_exec(), detect_features_exec(), disable_markers_exec(), draw_actuator_action(), draw_actuator_armature(), draw_actuator_constraint(), draw_actuator_edit_object(), draw_actuator_filter_2d(), draw_actuator_game(), draw_actuator_message(), draw_actuator_motion(), draw_actuator_parent(), draw_actuator_property(), draw_actuator_random(), draw_actuator_scene(), draw_actuator_shape_action(), draw_actuator_steering(), draw_brick_actuator(), draw_brick_controller(), draw_brick_sensor(), draw_controller_python(), draw_sensor_armature(), draw_sensor_joystick(), draw_sensor_property(), draw_sensor_ray(), ED_fileselect_set_params(), ed_marker_make_links_scene_exec(), ed_marker_select_all_exec(), edbm_blend_from_shape_exec(), edbm_delete_exec(), edbm_edge_rotate_selected_exec(), edbm_merge_exec(), edbm_rotate_colors_exec(), edbm_rotate_uvs_exec(), edbm_select_all_exec(), edbm_select_axis_exec(), edbm_select_by_number_vertices_exec(), edbm_select_similar_exec(), edbm_select_vertex_path_exec(), edbm_separate_exec(), edbm_sort_faces_exec(), edbm_subdivide_exec(), edit_constraint_property_get(), effector_add_exec(), face_select_all_exec(), frame_jump_exec(), game_property_copy_exec(), game_property_new(), get_enum(), BlenderSync::get_scene_params(), BlenderSync::get_session_params(), gp_convert_layer_exec(), gpencil_draw_init(), graph_disable_markers_exec(), graph_fmodifier_add_exec(), graph_select_all_markers_exec(), graphkeys_columnselect_exec(), graphkeys_expo_exec(), graphkeys_handletype_exec(), graphkeys_insertkey_exec(), graphkeys_ipo_exec(), graphkeys_mirror_exec(), graphkeys_paste_exec(), graphkeys_select_leftright_exec(), graphkeys_select_leftright_invoke(), graphkeys_snap_exec(), group_instance_add_exec(), group_link_exec(), group_move_exec(), hide_exec(), hide_show_exec(), hide_show_invoke(), image_sample_apply(), image_unpack_exec(), initSnapping(), initTransInfo(), insert_key_exec(), keyingset_active_menu_exec(), lattice_select_all_exec(), lock_tracks_exec(), logicbricks_move_property_get(), make_links_data_exec(), make_links_scene_exec(), make_local_exec(), make_proxy_exec(), make_single_user_exec(), mball_select_all_exec(), mode_set_exec(), modifier_add_exec(), modifier_apply_exec(), move_exec(), move_select_exec(), new_node_tree_exec(), nla_fmodifier_add_exec(), nla_panel_properties(), nlaedit_add_actionclip_exec(), nlaedit_select_leftright_exec(), nlaedit_select_leftright_invoke(), nlaedit_snap_exec(), node_composit_buts_blur(), node_composit_buts_channel_matte(), node_composit_buts_color_spill(), node_composit_buts_colorbalance(), node_composit_buts_colorbalance_but(), node_composit_buts_file_output(), node_composit_buts_file_output_details(), node_composit_buts_glare(), node_composit_buts_image(), node_composit_buts_tonemap(), node_group_socket_add_exec(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_socket_remove_exec(), node_shader_buts_geometry(), node_socket_button_output_file(), node_texture_buts_proc(), object_add_exec(), object_constraint_add_exec(), object_hook_assign_exec(), object_hook_recenter_exec(), object_hook_remove_exec(), object_hook_reset_exec(), object_hook_select_exec(), object_lamp_add_exec(), object_metaball_add_exec(), object_mode_set_compat(), object_mode_set_exec(), object_origin_set_exec(), object_select_all_exec(), object_select_by_type_exec(), object_select_grouped_exec(), object_select_linked_exec(), object_select_menu_exec(), object_track_clear_exec(), outliner_action_set_exec(), outliner_animdata_operation_exec(), outliner_data_operation_exec(), outliner_group_operation_exec(), outliner_id_operation_exec(), outliner_object_operation_exec(), output_toggle_exec(), parent_clear_exec(), parent_clear_invoke(), parent_drop_exec(), parent_set_exec(), pe_select_all_exec(), pose_autoside_names_exec(), pose_bone_rotmode_exec(), pose_constraint_add_exec(), pose_de_select_all_exec(), pose_propagate_fcurve(), pose_select_grouped_exec(), pose_select_hierarchy_exec(), redraw_timer_exec(), rule_add_exec(), scene_new_exec(), sculpt_brush_stroke_init(), sculpt_update_cache_invariants(), select_all_exec(), select_groped_exec(), select_orientation_exec(), sensor_add_exec(), sequencer_add_effect_strip_exec(), sequencer_add_effect_strip_invoke(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_change_effect_input_exec(), sequencer_change_effect_type_exec(), sequencer_cut_exec(), sequencer_de_select_all_exec(), sequencer_select_active_side_exec(), sequencer_select_grouped_exec(), sequencer_select_handles_exec(), sequencer_swap_exec(), set_active_group_exec(), set_axis_exec(), set_case_exec(), set_handle_type_exec(), set_plane_exec(), set_spline_type_exec(), set_style_exec(), shape_key_move_exec(), similar_edge_select_exec(), similar_face_select_exec(), similar_vert_select_exec(), snap_cursor_exec(), snap_selection_exec(), snap_type_exec(), sound_mixdown_exec(), sound_unpack_exec(), text_convert_whitespace_exec(), text_delete_exec(), text_move_exec(), text_move_select_exec(), text_resolve_conflict_exec(), texture_paint_camera_project_exec(), texture_slot_move(), toggle_cyclic_exec(), toggle_style_exec(), track_set_exec(), transformops_data(), type_toggle_exec(), unpack_all_exec(), unwrap_exec(), uv_map_transform(), uv_sculpt_stroke_init(), v3d_editmetaball_buts(), v3d_transform_butsR(), vert_select_all_exec(), vertex_group_lock_exec(), vgroup_move_exec(), viewnumpad_exec(), vieworbit_exec(), viewpan_exec(), weight_from_bones_exec(), and weight_sample_group_exec().
int RNA_enum_icon_from_value (EnumPropertyItem * item, int value, int * icon)
Definition at line 4318 of file rna_access.c.
References EnumPropertyItem::icon, EnumPropertyItem::identifier, and EnumPropertyItem::value.
Referenced by list_item_row(), and ui_id_brush_get_icon().
int RNA_enum_id_from_value (EnumPropertyItem * item, int value, const char ** identifier)
Definition at line 4306 of file rna_access.c.
References EnumPropertyItem::identifier, and EnumPropertyItem::value.
Referenced by pyrna_prop_str().
int RNA_enum_identifier (EnumPropertyItem * item, const int value, const char ** identifier)
Definition at line 1256 of file rna_access.c.
References EnumPropertyItem::identifier, and EnumPropertyItem::value.
Referenced by RNA_property_enum_identifier(), and WM_event_print().
int RNA_enum_is_equal (bContext * C, PointerRNA * ptr, const char * name, const char * enumname)
Definition at line 4269 of file rna_access.c.
References StructRNA::identifier, EnumPropertyItem::identifier, MEM_freeN(), NULL, RNA_property_enum_get(), RNA_property_enum_items(), RNA_struct_find_property(), PointerRNA::type, and EnumPropertyItem::value.
int RNA_enum_name (EnumPropertyItem * item, const int value, const char ** name)
Definition at line 1279 of file rna_access.c.
References EnumPropertyItem::identifier, EnumPropertyItem::name, and EnumPropertyItem::value.
Referenced by node_blend_label(), node_filter_label(), node_math_label(), node_vect_math_label(), RNA_property_enum_name(), ui_menu_enumpropname(), and WM_key_event_string().
void RNA_enum_set (PointerRNA * ptr, const char * name, int value)
Definition at line 4243 of file rna_access.c.
References StructRNA::identifier, RNA_property_enum_set(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by action_keymap_keyframes(), actkeys_select_leftright_invoke(), area_split_invoke(), area_split_modal(), BIF_do_manipulator(), clean_tracks_invoke(), clip_keymap(), console_keymap(), do_view3d_header_buttons(), draw_group_socket(), duplicate_metaelems_invoke(), ED_keymap_animchannels(), ED_keymap_armature(), ED_keymap_curve(), ED_keymap_gpencil(), ED_keymap_mesh(), ED_keymap_metaball(), ED_keymap_object(), ED_keymap_paint(), ED_keymap_uvedit(), ED_operatormacros_action(), ED_operatormacros_armature(), ED_operatormacros_curve(), ED_operatormacros_graph(), ED_operatormacros_mesh(), ED_operatormacros_object(), edbm_subdivide_exec(), edit_constraint_invoke_properties(), graph_fmodifier_add_invoke(), graphedit_keymap_keyframes(), graphkeys_select_leftright_invoke(), image_keymap(), insert_key_menu_invoke(), keymap_brush_select(), keymap_particle(), nla_keymap_main(), nlaedit_duplicate_invoke(), outliner_parent_clear_copy(), paint_partial_visibility_keys(), parent_drop_invoke(), poselib_rename_invoke(), saveTransform(), sequencer_add_duplicate_invoke(), sequencer_cut_invoke(), sequencer_keymap(), text_keymap(), transform_keymap_for_space(), unpack_menu(), and view3d_keymap().
void RNA_enum_set_identifier (PointerRNA * ptr, const char * name, const char * id)
Definition at line 4253 of file rna_access.c.
References StructRNA::identifier, NULL, RNA_property_enum_set(), RNA_property_enum_value(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by ED_keymap_object().
int RNA_enum_value_from_id (EnumPropertyItem * item, const char * identifier, int * value)
Definition at line 4294 of file rna_access.c.
References EnumPropertyItem::identifier, and EnumPropertyItem::value.
Referenced by BPy_FloatProperty(), BPy_FloatVectorProperty(), pyop_call(), pyop_poll(), pyrna_enum_value_from_id(), uiItemEnumO_string(), uiItemEnumR_string(), and wm_user_modal_keymap_set_items().
void RNA_exit (void)
Definition at line 86 of file rna_access.c.
References BLENDER_RNA, BLI_ghash_free(), StructRNA::cont, ListBase::first, ContainerRNA::next, NULL, ContainerRNA::prophash, RNA_free(), RNA_property_update_cache_free(), and BlenderRNA::structs.
Referenced by main(), and WM_exit_ext().
float RNA_float_get (PointerRNA * ptr, const char * name)
Definition at line 4187 of file rna_access.c.
References StructRNA::identifier, RNA_property_float_get(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by actkeys_clean_exec(), add_primitive_circle_exec(), add_primitive_cone_exec(), add_primitive_cylinder_exec(), add_primitive_grid_exec(), add_primitive_icosphere_exec(), add_primitive_uvsphere_exec(), area_split_apply(), backimage_zoom(), blender_camera_from_object(), brush_scale_size_exec(), clean_tracks_exec(), create_subd_mesh(), cube_project_exec(), do_set_scale(), edbm_bevel_exec(), edbm_blend_from_shape_exec(), edbm_dissolve_limited_exec(), edbm_extrude_repeat_exec(), edbm_inset_exec(), edbm_noise_exec(), edbm_remove_doubles_exec(), edbm_select_linked_flat_faces_exec(), edbm_select_random_exec(), edbm_select_sharp_edges_exec(), edbm_solidify_exec(), edbm_spin_exec(), edbm_subdivide_exec(), edbm_tris_convert_to_quads_exec(), edbm_vertex_slide_exec(), DocumentExporter::exportCurrentScene(), get_float(), gpencil_draw_exec(), graphkeys_clean_exec(), graphkeys_click_insert_exec(), graphview_cursor_apply(), image_view_zoom_exec(), image_view_zoom_ratio_exec(), initTransform(), initTransInfo(), minimize_stretch_init(), object_select_random_exec(), pack_islands_exec(), paint_apply(), pose_slide_init(), remove_doubles_exec(), sculpt_update_cache_variants(), select_random_exec(), select_random_metaelems_exec(), sequencer_view_zoom_ratio_exec(), set_goal_weight_exec(), set_radius_exec(), similar_edge_select_exec(), similar_face_select_exec(), similar_vert_select_exec(), stitch_init(), uv_map_transform(), vertex_group_blend_exec(), vertex_group_clean_exec(), vertex_group_fix_exec(), vertex_group_levels_exec(), view_zoom_exec(), view_zoom_ratio_exec(), view_zoomdrag_apply(), view_zoomstep_apply(), vpaint_stroke_update_step(), weight_set_exec(), and wpaint_stroke_update_step().
void RNA_float_get_array (PointerRNA * ptr, const char * name, float * values)
Definition at line 4210 of file rna_access.c.
References StructRNA::identifier, RNA_property_float_get_array(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by add_marker_exec(), add_vertex_exec(), brush_edit_apply(), cut_links_exec(), ED_object_add_generic_get_opts(), edbm_knife_cut_exec(), edbm_screw_exec(), edbm_spin_exec(), gpencil_draw_exec(), grab_clone_apply(), image_new_exec(), image_view_pan_exec(), image_view_zoom_in_exec(), image_view_zoom_out_exec(), initSnapping(), initTransform(), paint_apply(), save_envmap(), sculpt_update_cache_variants(), select_exec(), select_linked_internal(), select_loop_exec(), sequencer_add_effect_strip_exec(), set_2d_cursor_exec(), set_clone_cursor_exec(), spin_exec(), view3d_lasso_select_exec(), view_pan_exec(), view_zoom_in_exec(), view_zoom_out_exec(), vpaint_stroke_update_step(), and wpaint_stroke_update_step().
void RNA_float_set (PointerRNA * ptr, const char * name, float value)
Definition at line 4200 of file rna_access.c.
References StructRNA::identifier, RNA_property_float_set(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by area_split_invoke(), area_split_modal(), BKE_nlameta_flush_transforms(), clean_tracks_invoke(), clip_keymap(), ed_keymap_paint_brush_size(), edbm_vertex_slide_exec(), gpencil_draw_apply_event(), graphkeys_click_insert_invoke(), graphview_cursor_setprops(), image_keymap(), image_view_zoom_invoke(), image_view_zoom_modal(), minimize_stretch_modal(), nlaedit_clear_scale_exec(), node_keymap(), pack_islands_exec(), paint_apply_event(), paint_brush_stroke_add_step(), pose_slide_modal(), recalcData_nla(), saveTransform(), sequencer_keymap(), set_scale_invoke(), set_solution_scale_invoke(), stitch_exit(), uiItemFloatO(), view_zoom_invoke(), view_zoom_modal(), view_zoomdrag_invoke(), view_zoomdrag_modal(), view_zoomin_exec(), and view_zoomout_exec().
void RNA_float_set_array (PointerRNA * ptr, const char * name, const float * values)
Definition at line 4220 of file rna_access.c.
References StructRNA::identifier, RNA_property_float_set_array(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by add_marker_invoke(), add_vertex_invoke(), brush_edit_apply_event(), ED_object_add_generic_get_opts(), edbm_screw_invoke(), edbm_spin_invoke(), gesture_lasso_apply(), gpencil_draw_apply_event(), grab_clone_modal(), image_view_pan_invoke(), image_view_pan_modal(), image_view_zoom_in_invoke(), image_view_zoom_out_invoke(), object_add_generic_invoke_options(), paint_apply_event(), paint_brush_stroke_add_step(), select_invoke(), select_linked_internal(), select_loop_invoke(), set_2d_cursor_invoke(), set_clone_cursor_invoke(), spin_invoke(), view_pan_invoke(), view_pan_modal(), view_zoom_in_invoke(), and view_zoom_out_invoke().
char* RNA_function_as_string_keywords (bContext * C, FunctionRNA * func, PointerRNA * ptr_default, const short as_function, const short all_args)
Definition at line 4621 of file rna_access.c.
References NULL, RNA_Function, RNA_pointer_as_string_keywords_ex(), RNA_pointer_create(), RNA_struct_find_property(), RNA_struct_iterator_property(), and PointerRNA::type.
Referenced by pyrna_func_doc_get().
int RNA_function_call (bContext * C, ReportList * reports, PointerRNA * ptr, FunctionRNA * func, ParameterList * parms)
Definition at line 5089 of file rna_access.c.
References FunctionRNA::call.
Referenced by pyrna_func_call(), RNA_function_call_direct_va(), RNA_function_call_lookup(), RNA_property_collection_add(), and RNA_property_collection_remove().
int RNA_function_call_direct (bContext * C, ReportList * reports, PointerRNA * ptr, FunctionRNA * func, const char * format, ...)
Definition at line 5113 of file rna_access.c.
References RNA_function_call_direct_va().
int RNA_function_call_direct_lookup (bContext * C, ReportList * reports, PointerRNA * ptr, const char * identifier, const char * format, ...)
Definition at line 5128 of file rna_access.c.
References RNA_function_call_direct_va(), and RNA_struct_find_function().
int RNA_function_call_direct_va (bContext * C, ReportList * reports, PointerRNA * ptr, FunctionRNA * func, const char * format, va_list args)
Definition at line 5313 of file rna_access.c.
References FunctionRNA::c_ret, ParameterIterator::data, err, i, len(), NULL, ParameterIterator::parm, PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_OUTPUT, PROP_POINTER, PROP_REQUIRED, PROP_STRING, RNA_Function, RNA_function_call(), rna_function_format_array_length(), RNA_function_identifier(), rna_function_parameter_parse(), RNA_parameter_list_begin(), RNA_parameter_list_create(), RNA_parameter_list_end(), RNA_parameter_list_free(), RNA_parameter_list_next(), RNA_pointer_create(), RNA_property_array_length(), RNA_property_flag(), RNA_property_identifier(), RNA_property_type(), RNA_struct_identifier(), strlen(), PointerRNA::type, and ParameterIterator::valid.
Referenced by RNA_function_call_direct(), RNA_function_call_direct_lookup(), and RNA_function_call_direct_va_lookup().
int RNA_function_call_direct_va_lookup (bContext * C, ReportList * reports, PointerRNA * ptr, const char * identifier, const char * format, va_list args)
Definition at line 5503 of file rna_access.c.
References RNA_function_call_direct_va(), and RNA_struct_find_function().
int RNA_function_call_lookup (bContext * C, ReportList * reports, PointerRNA * ptr, const char * identifier, ParameterList * parms)
Definition at line 5100 of file rna_access.c.
References RNA_function_call(), and RNA_struct_find_function().
int RNA_function_defined (FunctionRNA * func)
Definition at line 4811 of file rna_access.c.
References FunctionRNA::call, and NULL.
Referenced by pyrna_struct_getattro().
struct ListBase* RNA_function_defined_parameters (FunctionRNA * func) [read]
Definition at line 4826 of file rna_access.c.
References FunctionRNA::cont, and ContainerRNA::properties.
Referenced by rna_function_arg_count().
PropertyRNA* RNA_function_find_parameter (PointerRNA * UNUSEDptr, FunctionRNA * func, const char * identifier)
Definition at line 4821 of file rna_access.c.
References BLI_findstring(), FunctionRNA::cont, and ContainerRNA::properties.
int RNA_function_flag (FunctionRNA * func)
Definition at line 4806 of file rna_access.c.
References FunctionRNA::flag.
Referenced by bpy_class_call(), bpy_class_validate(), and rna_function_arg_count().
static int rna_function_format_array_length (const char * format, int ofs, int flen) [static]
Definition at line 5151 of file rna_access.c.
Referenced by RNA_function_call_direct_va().
PropertyRNA* RNA_function_get_parameter (PointerRNA * UNUSEDptr, FunctionRNA * func, int index)
Definition at line 4816 of file rna_access.c.
References BLI_findlink(), FunctionRNA::cont, and ContainerRNA::properties.
const char* RNA_function_identifier (FunctionRNA * func)
Definition at line 4796 of file rna_access.c.
References FunctionRNA::identifier.
Referenced by bpy_class_call(), bpy_class_validate(), pyrna_dir_members_rna(), pyrna_func_call(), pyrna_func_doc_get(), pyrna_func_repr(), RNA_function_call_direct_va(), and RNA_struct_find_function().
static int rna_function_parameter_parse (PointerRNA * ptr, PropertyRNA * prop, PropertyType type, char ftype, int len, void * dest, void * src, StructRNA * srna, const char * tid, const char * fid, const char * pid) [static]
Definition at line 5169 of file rna_access.c.
References BLI_addtail(), ListBase::first, PropertyRNA::flag, link(), MEM_callocN(), Link::next, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_POINTER, PROP_RNAPTR, PROP_STRING, CollectionPointerLink::ptr, RNA_pointer_create(), RNA_property_pointer_type(), RNA_struct_identifier(), and RNA_struct_is_a().
Referenced by RNA_function_call_direct_va().
const char* RNA_function_ui_description (FunctionRNA * func)
Definition at line 4801 of file rna_access.c.
References FunctionRNA::description.
Referenced by pyrna_func_doc_get().
void RNA_id_pointer_create (ID * id, PointerRNA * r_ptr)
Definition at line 111 of file rna_access.c.
References PointerRNA::data, PointerRNA::id, NULL, StructRNA::refine, rna_ID_refine(), and PointerRNA::type.
Referenced by acf_generic_idblock_nameprop(), acf_generic_idfill_nameprop(), achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), act_new_exec(), action_get_item_transforms(), ANIM_add_driver(), ANIM_apply_keyingset(), ANIM_channel_draw_widgets(), ANIM_copy_driver(), ANIM_list_elem_update(), ANIM_paste_driver(), ANIM_relative_keyingset_add_source(), ANIM_unit_mapping_get_factor(), BKE_animsys_evaluate_animdata(), BL_Action::BL_Action(), BL_ShapeActionActuator::BL_ShapeActionActuator(), bpy_app_generic_callback(), bpy_lib_exit(), buttons_context_path(), buttons_context_path_brush(), buttons_context_path_data(), buttons_context_path_material(), buttons_context_path_object(), buttons_context_path_texture(), buttons_context_path_world(), check_rna_path_is_valid(), copy_to_selected_button_exec(), copy_to_selected_button_poll(), create_func(), CTX_data_id_list_add(), CTX_data_id_pointer_set(), delete_keyframe(), draw_gpencil_panel(), dtar_get_prop_val(), DocumentExporter::exportCurrentScene(), DocumentImporter::finish(), font_open_exec(), font_unlink_exec(), getname_anim_fcurve(), gpencil_data_get_pointers(), graph_panel_driverVar__singleProp(), graph_panel_key_properties(), graph_panel_view(), id_search_call_cb(), id_search_cb(), id_single_user(), image_new_exec(), image_open_exec(), insert_keyframe(), new_material_exec(), new_node_tree_exec(), new_texture_exec(), new_world_exec(), object_to_mesh(), open_exec(), pastebuf_match_path_property(), pose_armature_layers_exec(), pose_armature_layers_invoke(), pose_armature_layers_showall_exec(), pose_propagate_get_refVal(), poselib_preview_init_data(), pyrna_param_to_py(), pyrna_struct_get_id_data(), rna_path_from_ID_to_idpgroup(), RNA_path_from_ID_to_struct(), RNA_pointer_recast(), RNA_property_path_from_ID_check(), text_new_exec(), text_open_exec(), uiIconFromID(), view3d_panel_object(), and what_does_obaction().
static char* rna_idp_path (PointerRNA * ptr, IDProperty * haystack, IDProperty * needle, IDP_Chain * parent_link) [static]
Definition at line 3946 of file rna_access.c.
References BLI_assert, IDProperty::data, ListBase::first, IDPropertyData::group, i, IDP_GROUP, IDP_IDPArray, IDP_IDPARRAY, IDP_Chain::index, IDProperty::len, link(), IDProperty::name, IDP_Chain::name, IDProperty::next, NULL, PROP_COLLECTION, rna_idp_path_create(), RNA_pointer_get(), RNA_property_collection_lookup_int(), RNA_struct_find_property(), PropertyRNA::type, PointerRNA::type, IDProperty::type, and IDP_Chain::up.
Referenced by rna_path_from_ID_to_idpgroup().
static char* rna_idp_path_create (IDP_Chain * child_link) [static]
Definition at line 3903 of file rna_access.c.
References BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), FALSE, IDP_Chain::index, link(), MEM_freeN(), IDP_Chain::name, NULL, TRUE, and IDP_Chain::up.
Referenced by rna_idp_path().
IDProperty* rna_idproperty_check (PropertyRNA ** prop, PointerRNA * ptr) [read]
Definition at line 392 of file rna_access.c.
References IDP_ARRAY, IDP_FreeProperty(), IDP_RemFromGroup(), MEM_freeN(), NULL, PROP_IDPROPERTY, rna_idproperty_find(), rna_idproperty_verify_valid(), RNA_MAGIC, RNA_struct_idprops(), IDProperty::subtype, and IDProperty::type.
Referenced by RNA_property_boolean_get(), RNA_property_boolean_get_array(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_collection_add(), RNA_property_collection_begin(), RNA_property_collection_clear(), RNA_property_collection_length(), RNA_property_collection_move(), RNA_property_collection_remove(), RNA_property_enum_get(), RNA_property_enum_set(), RNA_property_float_get(), RNA_property_float_get_array(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_int_get(), RNA_property_int_get_array(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_pointer_add(), RNA_property_pointer_get(), RNA_property_pointer_remove(), RNA_property_pointer_set(), RNA_property_string_get(), RNA_property_string_length(), and RNA_property_string_set().
static IDProperty* rna_idproperty_find (PointerRNA * ptr, const char * name) [static]
Definition at line 274 of file rna_access.c.
References IDP_GetPropertyFromGroup(), NULL, and RNA_struct_idprops().
Referenced by rna_idproperty_check(), and RNA_property_is_set().
static void rna_idproperty_touch (IDProperty * idprop) [static]
Definition at line 229 of file rna_access.c.
References IDProperty::flag, and IDP_FLAG_GHOST.
Referenced by RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_enum_set(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_int_set(), RNA_property_int_set_array(), and RNA_property_string_set().
IDProperty* rna_idproperty_ui (PropertyRNA * prop)
Definition at line 236 of file rna_access.c.
References IDP_GetPropertyTypeFromGroup(), IDP_GROUP, IDProperty::name, IDProperty::next, next, NULL, IDProperty::prev, and RNA_IDP_UI.
Referenced by rna_ensure_property_description(), RNA_property_float_range(), RNA_property_float_ui_range(), RNA_property_int_range(), and RNA_property_int_ui_range().
static int rna_idproperty_verify_valid (PointerRNA * ptr, PropertyRNA * prop, IDProperty * idprop) [static]
Definition at line 330 of file rna_access.c.
References ELEM3, IDP_ARRAY, IDP_DOUBLE, IDP_FLOAT, IDP_GROUP, IDP_IDPARRAY, IDP_INT, IDP_STRING, IDProperty::len, PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_POINTER, PROP_STRING, rna_ensure_property_array_length(), IDProperty::subtype, PropertyRNA::type, and IDProperty::type.
Referenced by rna_idproperty_check().
void RNA_init (void)
Definition at line 70 of file rna_access.c.
References BLENDER_RNA, BLI_ghash_insert(), BLI_ghash_new(), BLI_ghashutil_strcmp(), BLI_ghashutil_strhash(), StructRNA::cont, ListBase::first, PropertyRNA::flag, PropertyRNA::identifier, PropertyRNA::next, ContainerRNA::next, PROP_BUILTIN, ContainerRNA::properties, ContainerRNA::prophash, and BlenderRNA::structs.
Referenced by main().
int RNA_int_get (PointerRNA * ptr, const char * name)
Definition at line 4144 of file rna_access.c.
References StructRNA::identifier, RNA_property_int_get(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by actionzone_apply(), actkeys_borderselect_exec(), add_primitive_circle_exec(), add_primitive_cone_exec(), add_primitive_cylinder_exec(), add_primitive_grid_exec(), add_primitive_icosphere_exec(), add_primitive_uvsphere_exec(), animchannels_borderselect_exec(), area_join_init(), area_move_apply(), area_move_init(), area_move_modal(), area_split_invoke(), armature_subdivide_exec(), background_image_remove_exec(), blender_camera_from_object(), bookmark_delete_exec(), border_select_exec(), border_select_graph_exec(), borderselect_exec(), change_character_exec(), change_frame_apply(), change_spacing_exec(), circle_select_exec(), clean_tracks_exec(), console_history_append_exec(), detect_features_exec(), draw_controller_header(), ED_fileselect_set_params(), ed_marker_border_select_exec(), ed_marker_move_apply(), edbm_do_smooth_vertex_exec(), edbm_extrude_repeat_exec(), edbm_knife_cut_exec(), edbm_screw_exec(), edbm_select_by_number_vertices_exec(), edbm_select_nth_exec(), edbm_spin_exec(), edbm_subdivide_exec(), edbm_vertices_randomize_exec(), file_border_select_exec(), file_border_select_modal(), file_filenum_exec(), frame_offset_exec(), game_property_remove(), gesture_circle_apply(), get_int(), graphkeys_borderselect_exec(), graphview_cursor_apply(), image_new_exec(), image_sample_line_exec(), loopcut_modal(), minimize_stretch_exec(), minimize_stretch_init(), nlaedit_borderselect_exec(), node_borderselect_exec(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_socket_remove_exec(), node_select_exec(), object_select_by_layer_exec(), outliner_border_select_exec(), pose_group_assign_exec(), pose_slide_init(), poselib_add_exec(), poselib_preview_init_data(), poselib_rename_exec(), previewrange_define_exec(), rect_from_props(), redraw_timer_exec(), rekey_exec(), render_border_exec(), repeat_history_exec(), ringsel_finish(), screen_set_exec(), select_nth_exec(), select_report_pick_exec(), seq_load_operator_info(), sequencer_add_effect_strip_exec(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_borderselect_exec(), sequencer_cut_exec(), sequencer_separate_images_exec(), sequencer_snap_exec(), sound_mixdown_exec(), stitch_init(), subdivide_exec(), text_cursor_set_exec(), text_jump_exec(), text_scroll_exec(), textbox_remove_exec(), undo_history_exec(), unwrap_exec(), view3d_borderselect_exec(), view3d_circle_select_exec(), view3d_clipping_exec(), view3d_layers_exec(), view3d_layers_invoke(), view3d_zoom_border_exec(), view_borderzoom_exec(), view_ghost_border_exec(), view_pan_apply(), viewdolly_exec(), viewzoom_exec(), wm_debug_menu_exec(), WM_gesture_lasso_invoke(), WM_gesture_lines_invoke(), and WM_gesture_straightline_invoke().
void RNA_int_get_array (PointerRNA * ptr, const char * name, int * values)
Definition at line 4167 of file rna_access.c.
References StructRNA::identifier, RNA_property_int_get_array(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by sample_color_exec(), select_linked_exec(), and set_tile_exec().
void RNA_int_set (PointerRNA * ptr, const char * name, int value)
Definition at line 4157 of file rna_access.c.
References StructRNA::identifier, RNA_property_int_set(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by area_join_invoke(), area_move_cancel(), area_move_invoke(), area_move_modal(), border_apply(), border_apply_rect(), change_frame_invoke(), change_frame_modal(), clean_tracks_invoke(), draw_group_socket(), ED_keymap_curve(), ED_keymap_mesh(), ED_keymap_object(), ED_keymap_paint(), ed_keymap_paint_brush_switch(), ED_keymap_screen(), ed_marker_move_cancel(), ed_marker_move_invoke(), ed_marker_move_modal(), file_draw_buttons(), file_keymap(), gesture_circle_apply(), graphview_cursor_setprops(), image_keymap(), loopcut_modal(), minimize_stretch_iteration(), nlaedit_select_leftright_invoke(), node_select_invoke(), pose_groups_menu_invoke(), pose_slide_invoke_common(), poselib_add_menu_invoke__replacemenu(), poselib_preview_apply(), screen_area_options_invoke(), select_report_pick_invoke(), sequencer_cut_invoke(), sequencer_generic_invoke_xy__internal(), sequencer_keymap(), sequencer_snap_invoke(), stitch_exit(), straightline_apply(), text_cursor_set_invoke(), text_keymap(), uiItemIntO(), view3d_keymap(), view3d_layers_invoke(), view_pan_invoke(), view_pan_modal(), view_scrolldown_exec(), view_scrollleft_exec(), view_scrollright_exec(), view_scrollup_exec(), viewdolly_invoke(), viewzoom_invoke(), wm_debug_menu_invoke(), and WM_gesture_circle_modal().
void RNA_int_set_array (PointerRNA * ptr, const char * name, const int * values)
Definition at line 4177 of file rna_access.c.
References StructRNA::identifier, RNA_property_int_set_array(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by sample_color_invoke(), sample_color_modal(), select_linked_invoke(), and set_tile_invoke().
void rna_iterator_array_begin (CollectionPropertyIterator * iter, void * ptr, int itemsize, int length, int free_ptr, IteratorSkipFunc skip)
Definition at line 3415 of file rna_access.c.
References CollectionPropertyIterator::internal, length(), MEM_callocN(), NULL, tRnaUpdateCacheElem::ptr, CollectionPropertyIterator::ptr, rna_iterator_array_next(), and CollectionPropertyIterator::valid.
Referenced by RNA_property_collection_begin().
void* rna_iterator_array_dereference_get (CollectionPropertyIterator * iter)
Definition at line 3465 of file rna_access.c.
References CollectionPropertyIterator::internal.
void rna_iterator_array_end (CollectionPropertyIterator * iter)
Definition at line 3473 of file rna_access.c.
References CollectionPropertyIterator::internal, MEM_freeN(), and NULL.
Referenced by RNA_property_collection_end().
void* rna_iterator_array_get (CollectionPropertyIterator * iter)
Definition at line 3458 of file rna_access.c.
References CollectionPropertyIterator::internal.
Referenced by rna_property_collection_get_idp().
void rna_iterator_array_next (CollectionPropertyIterator * iter)
Definition at line 3442 of file rna_access.c.
References CollectionPropertyIterator::internal, CollectionPropertyIterator::ptr, and CollectionPropertyIterator::valid.
Referenced by rna_iterator_array_begin(), and RNA_property_collection_next().
void rna_iterator_listbase_begin (CollectionPropertyIterator * iter, ListBase * lb, IteratorSkipFunc skip)
Definition at line 3365 of file rna_access.c.
References ListBase::first, CollectionPropertyIterator::internal, MEM_callocN(), NULL, rna_iterator_listbase_next(), and CollectionPropertyIterator::valid.
void rna_iterator_listbase_end (CollectionPropertyIterator * iter)
Definition at line 3403 of file rna_access.c.
References CollectionPropertyIterator::internal, MEM_freeN(), and NULL.
void* rna_iterator_listbase_get (CollectionPropertyIterator * iter)
Definition at line 3396 of file rna_access.c.
References CollectionPropertyIterator::internal.
void rna_iterator_listbase_next (CollectionPropertyIterator * iter)
Definition at line 3380 of file rna_access.c.
References CollectionPropertyIterator::internal, NULL, and CollectionPropertyIterator::valid.
Referenced by rna_iterator_listbase_begin().
PointerRNA rna_listbase_lookup_int (PointerRNA * ptr, StructRNA * type, struct ListBase * lb, int index)
Definition at line 3409 of file rna_access.c.
References BLI_findlink(), data, and rna_pointer_inherit_refine().
void RNA_main_pointer_create (struct Main * main, PointerRNA * r_ptr)
Definition at line 104 of file rna_access.c.
References PointerRNA::data, PointerRNA::id, main(), NULL, RNA_BlendData, and PointerRNA::type.
Referenced by BPY_rna_module(), BPY_update_rna_module(), draw_actuator_constraint(), draw_actuator_message(), draw_sensor_collision(), draw_sensor_ray(), outliner_build_tree(), and search_id_collection().
void RNA_parameter_get (ParameterList * parms, PropertyRNA * parm, void ** value)
Definition at line 4984 of file rna_access.c.
References ParameterIterator::data, NULL, ParameterIterator::parm, RNA_parameter_list_begin(), RNA_parameter_list_end(), RNA_parameter_list_next(), and ParameterIterator::valid.
Referenced by RNA_parameter_get_lookup().
void RNA_parameter_get_lookup (ParameterList * parms, const char * identifier, void ** value)
Definition at line 5002 of file rna_access.c.
References FunctionRNA::cont, ListBase::first, ParameterList::func, PropertyRNA::next, ContainerRNA::properties, RNA_parameter_get(), and RNA_property_identifier().
int RNA_parameter_length_get (ParameterList * parms, PropertyRNA * parm)
Definition at line 5044 of file rna_access.c.
References ParameterIterator::data, len(), ParameterIterator::parm, RNA_parameter_length_get_data(), RNA_parameter_list_begin(), RNA_parameter_list_end(), RNA_parameter_list_next(), and ParameterIterator::valid.
int RNA_parameter_length_get_data (ParameterList * UNUSEDparms, PropertyRNA * UNUSEDparm, void * data)
Definition at line 5079 of file rna_access.c.
References data.
Referenced by RNA_parameter_length_get().
void RNA_parameter_length_set (ParameterList * parms, PropertyRNA * parm, int length)
Definition at line 5063 of file rna_access.c.
References ParameterIterator::data, ParameterIterator::parm, RNA_parameter_length_set_data(), RNA_parameter_list_begin(), RNA_parameter_list_end(), RNA_parameter_list_next(), and ParameterIterator::valid.
void RNA_parameter_length_set_data (ParameterList * UNUSEDparms, PropertyRNA * UNUSEDparm, void * data, int length)
Definition at line 5084 of file rna_access.c.
References length().
Referenced by RNA_parameter_length_set().
int RNA_parameter_list_arg_count (ParameterList * parms)
Definition at line 4941 of file rna_access.c.
References ParameterList::arg_count.
Referenced by pyrna_func_call().
void RNA_parameter_list_begin (ParameterList * parms, ParameterIterator * iter)
Definition at line 4951 of file rna_access.c.
References FunctionRNA::cont, ParameterList::data, ParameterIterator::data, ListBase::first, ParameterList::func, NULL, ParameterIterator::offset, ParameterIterator::parm, ParameterIterator::parms, ContainerRNA::properties, rna_parameter_size_alloc(), ParameterIterator::size, and ParameterIterator::valid.
Referenced by bpy_class_call(), pyrna_func_call(), RNA_function_call_direct_va(), RNA_parameter_get(), RNA_parameter_length_get(), RNA_parameter_length_set(), and RNA_parameter_set().
ParameterList* RNA_parameter_list_create (ParameterList * parms, PointerRNA * UNUSEDptr, FunctionRNA * func)
Definition at line 4833 of file rna_access.c.
References ParameterList::alloc_size, ParameterList::arg_count, ParameterDynAlloc::array, ParameterDynAlloc::array_tot, PropertyRNA::arraydimension, BLI_strncpy(), FunctionRNA::cont, ParameterList::data, data, ListBase::first, PropertyRNA::flag, ParameterList::func, MEM_callocN(), PropertyRNA::next, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_DYNAMIC, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_OUTPUT, PROP_POINTER, PROP_REQUIRED, PROP_STRING, ContainerRNA::properties, ParameterList::ret_count, rna_parameter_size(), rna_parameter_size_alloc(), size(), and PropertyRNA::type.
Referenced by pyrna_func_call(), RNA_function_call_direct_va(), RNA_property_collection_add(), and RNA_property_collection_remove().
void RNA_parameter_list_end (ParameterIterator * UNUSEDiter)
Definition at line 4979 of file rna_access.c.
Referenced by bpy_class_call(), pyrna_func_call(), RNA_function_call_direct_va(), RNA_parameter_get(), RNA_parameter_length_get(), RNA_parameter_length_set(), and RNA_parameter_set().
void RNA_parameter_list_free (ParameterList * parms)
Definition at line 4911 of file rna_access.c.
References ParameterDynAlloc::array, BLI_freelistN(), FunctionRNA::cont, ParameterList::data, ListBase::first, PropertyRNA::flag, ParameterList::func, MEM_freeN(), PropertyRNA::next, NULL, PROP_COLLECTION, PROP_DYNAMIC, ContainerRNA::properties, rna_parameter_size_alloc(), and PropertyRNA::type.
Referenced by pyrna_func_call(), RNA_function_call_direct_va(), RNA_property_collection_add(), and RNA_property_collection_remove().
void RNA_parameter_list_next (ParameterIterator * iter)
Definition at line 4967 of file rna_access.c.
References ParameterList::data, ParameterIterator::data, PropertyRNA::next, NULL, ParameterIterator::offset, ParameterIterator::parm, ParameterIterator::parms, rna_parameter_size_alloc(), ParameterIterator::size, and ParameterIterator::valid.
Referenced by bpy_class_call(), pyrna_func_call(), RNA_function_call_direct_va(), RNA_parameter_get(), RNA_parameter_length_get(), RNA_parameter_length_set(), and RNA_parameter_set().
int RNA_parameter_list_ret_count (ParameterList * parms)
Definition at line 4946 of file rna_access.c.
References ParameterList::ret_count.
int RNA_parameter_list_size (ParameterList * parms)
Definition at line 4936 of file rna_access.c.
References ParameterList::alloc_size.
void RNA_parameter_set (ParameterList * parms, PropertyRNA * parm, const void * value)
Definition at line 5015 of file rna_access.c.
References ParameterIterator::data, ParameterIterator::parm, RNA_parameter_list_begin(), RNA_parameter_list_end(), RNA_parameter_list_next(), ParameterIterator::size, and ParameterIterator::valid.
Referenced by RNA_parameter_set_lookup().
void RNA_parameter_set_lookup (ParameterList * parms, const char * identifier, const void * value)
Definition at line 5031 of file rna_access.c.
References FunctionRNA::cont, ListBase::first, ParameterList::func, PropertyRNA::next, ContainerRNA::properties, RNA_parameter_set(), and RNA_property_identifier().
char* RNA_path_append (const char * path, PointerRNA * UNUSEDptr, PropertyRNA * prop, int intkey, const char * strkey)
Definition at line 3795 of file rna_access.c.
References BLI_dynstr_append(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), BLI_snprintf(), PROP_COLLECTION, RNA_property_identifier(), and RNA_property_type().
Referenced by tree_element_to_path().
char* RNA_path_back (const char * path)
Definition at line 3846 of file rna_access.c.
References BLI_strdup(), i, MEM_freeN(), NULL, and rna_path_token().
static char* rna_path_from_ID_to_idpgroup (PointerRNA * ptr) [static]
Definition at line 4010 of file rna_access.c.
References BLI_assert, PointerRNA::data, FALSE, PointerRNA::id, NULL, RNA_id_pointer_create(), rna_idp_path(), and RNA_struct_idprops().
Referenced by RNA_path_from_ID_to_struct().
char* RNA_path_from_ID_to_property (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 4071 of file rna_access.c.
References BLI_sprintfN(), BLI_strdup(), PointerRNA::data, PointerRNA::id, PropertyRNA::magic, MEM_freeN(), NULL, RNA_MAGIC, RNA_path_from_ID_to_struct(), and RNA_property_identifier().
Referenced by add_keyingset_button_exec(), copy_data_path_button_exec(), copy_to_selected_button_exec(), copy_to_selected_button_poll(), delete_key_button_exec(), get_driver_path_hack(), id_data_find_fcurve(), insert_key_button_exec(), key_get_curValue_rnaPath(), pyrna_prop_path_from_id(), pyrna_prop_repr(), pyrna_struct_anim_args_parse(), pyrna_struct_path_from_id(), remove_keyingset_button_exec(), rna_get_fcurve(), RNA_property_path_from_ID_check(), and ui_but_anim_expression_create().
char* RNA_path_from_ID_to_struct (PointerRNA * ptr)
Definition at line 4033 of file rna_access.c.
References BLI_strdup(), PointerRNA::data, PointerRNA::id, StructRNA::nested, NULL, StructRNA::path, RNA_id_pointer_create(), rna_path_from_ID_to_idpgroup(), RNA_property_identifier(), RNA_PropertyGroup, RNA_struct_find_nested(), RNA_struct_is_a(), RNA_struct_is_ID(), and PointerRNA::type.
Referenced by action_get_item_transforms(), fcurves_to_pchan_links_get(), node_group_make_from_selected(), node_group_ungroup(), pyrna_struct_path_from_id(), pyrna_struct_repr(), and RNA_path_from_ID_to_property().
int RNA_path_resolve (PointerRNA * ptr, const char * path, PointerRNA * r_ptr, PropertyRNA ** r_prop)
Definition at line 3597 of file rna_access.c.
References NULL, and RNA_path_resolve_full().
Referenced by achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), ANIM_add_driver(), ANIM_apply_keyingset(), ANIM_channel_draw_widgets(), ANIM_copy_driver(), ANIM_list_elem_update(), ANIM_paste_driver(), ANIM_unit_mapping_get_factor(), animsys_write_rna_setting(), check_rna_path_is_valid(), copy_to_selected_button_exec(), copy_to_selected_button_poll(), delete_keyframe(), getname_anim_fcurve(), graph_panel_key_properties(), insert_keyframe(), insert_keyframe_direct(), nlaevalchan_verify(), pastebuf_match_path_property(), pose_propagate_get_refVal(), radial_control_get_path(), RNA_property_path_from_ID_check(), and RNA_struct_find_property().
int RNA_path_resolve_full (PointerRNA * ptr, const char * path, PointerRNA * r_ptr, PropertyRNA ** r_prop, int * index)
Definition at line 3602 of file rna_access.c.
References PointerRNA::data, i, IDP_GetPropertyFromGroup(), len(), MEM_freeN(), NULL, PROP_COLLECTION, PROP_POINTER, tRnaUpdateCacheElem::ptr, RNA_MAX_ARRAY_DIMENSION, rna_path_token(), RNA_property_array_dimension(), RNA_property_array_item_index(), RNA_property_collection_lookup_int(), RNA_property_collection_lookup_string(), RNA_property_collection_type_get(), RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_idprops(), and rna_token_strip_quotes().
Referenced by dtar_get_prop_val(), pyrna_struct_anim_args_parse(), pyrna_struct_path_resolve(), and RNA_path_resolve().
static char* rna_path_token (const char ** path, char * fixedbuf, int fixedlen, int bracket) [static]
Definition at line 3495 of file rna_access.c.
References i, len(), MEM_callocN(), NULL, and p.
Referenced by RNA_path_back(), and RNA_path_resolve_full().
void RNA_pointer_add (PointerRNA * ptr, const char * name)
Definition at line 4405 of file rna_access.c.
References StructRNA::identifier, RNA_property_pointer_add(), RNA_struct_find_property(), and PointerRNA::type.
char* RNA_pointer_as_string (bContext * C, PointerRNA * ptr)
Definition at line 4491 of file rna_access.c.
References BLI_dynstr_append(), BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), MEM_freeN(), RNA_property_as_string(), RNA_property_identifier(), RNA_STRUCT_BEGIN, and RNA_STRUCT_END.
Referenced by RNA_property_as_string().
char* RNA_pointer_as_string_keywords (bContext * C, PointerRNA * ptr, PointerRNA * ptr_default, const short as_function, const short all_args)
Definition at line 4610 of file rna_access.c.
References RNA_pointer_as_string_keywords_ex(), RNA_struct_iterator_property(), and PointerRNA::type.
Referenced by WM_operator_pystring().
char* RNA_pointer_as_string_keywords_ex (bContext * C, PointerRNA * ptr, PointerRNA * ptr_default, const short as_function, const short all_args, PropertyRNA * iterprop)
Definition at line 4527 of file rna_access.c.
References BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), BLI_strdup(), FALSE, MEM_freeN(), NULL, PROP_NEVER_NULL, PROP_OUTPUT, PROP_POINTER, PROP_REQUIRED, RNA_PROP_BEGIN, RNA_PROP_END, RNA_property_as_string(), RNA_property_flag(), RNA_property_identifier(), RNA_property_type(), RNA_struct_find_property(), and TRUE.
Referenced by RNA_function_as_string_keywords(), and RNA_pointer_as_string_keywords().
void RNA_pointer_create (ID * id, StructRNA * type, void * data, PointerRNA * r_ptr)
Definition at line 135 of file rna_access.c.
References data, PointerRNA::data, PointerRNA::id, NULL, StructRNA::refine, rna_ID_refine(), and PointerRNA::type.
Referenced by acf_gpl_name_prop(), acf_group_name_prop(), acf_shapekey_nameprop(), action_get_item_transforms(), active_node_panel(), actuator_add_exec(), ANIM_relative_keyingset_add_source(), ANIM_uiTemplate_fmodifier_draw(), armature_bone_layers_exec(), BKE_nlameta_flush_transforms(), BL_ConvertActuators(), bpy_class_call(), BPy_init_modules(), buttons_context_path_bone(), buttons_context_path_particle(), buttons_context_path_pose_bone(), buttons_texture_modifier_foreach(), buttons_texture_users_find_nodetree(), buttons_texture_users_from_context(), colorband_buttons_large(), colorband_buttons_small(), controller_add_exec(), create_func(), CTX_data_list_add(), CTX_data_pointer_set(), draw_actuator_action(), draw_actuator_armature(), draw_actuator_message(), draw_actuator_motion(), draw_actuator_property(), draw_actuator_random(), draw_actuator_shape_action(), draw_actuator_state(), draw_constraint(), draw_modifier(), draw_modifier__cycles(), draw_modifier__envelope(), draw_modifier__fn_generator(), draw_modifier__generator(), draw_modifier__limits(), draw_modifier__noise(), draw_modifier__stepped(), draw_sensor_actuator(), draw_sensor_armature(), draw_sensor_keyboard(), draw_sensor_property(), fcurves_to_pchan_links_get(), get_driver_path_hack(), gp_drawui_layer(), gpencil_data_get_pointers(), graph_panel_drivers(), graph_panel_driverVar__locDiff(), graph_panel_driverVar__rotDiff(), graph_panel_driverVar__singleProp(), graph_panel_driverVar__transChan(), graph_panel_key_properties(), graph_panel_properties(), graph_panel_view(), id_data_find_fcurve(), image_panel_curves(), image_save_as_draw(), key_get_curValue_rnaPath(), logic_buttons(), logic_buttons_new(), menu_add_shortcut(), menu_change_shortcut(), nla_panel_context(), nlaedit_clear_scale_exec(), nlastrip_evaluate_controls(), node_animation_properties(), node_draw_basis(), node_draw_group(), node_group_make_from_selected(), node_group_ungroup(), node_socket_button_color(), node_socket_button_components(), node_socket_button_default(), node_socket_button_output_file(), node_texture_buts_proc(), node_update_basis(), operator_enum_search_cb(), operator_wrapper(), outliner_build_tree(), outliner_draw_restrictbuts(), pose_bone_layers_exec(), pose_slide_apply_props(), pyop_as_string(), pyop_getinstance(), PYOP_wrap_macro_define(), pyrna_dir_members_rna(), pyrna_func_call(), pyrna_param_to_py(), pyrna_py_to_prop(), pyrna_srna_contains_pointer_prop_srna(), pyrna_struct_driver_add(), pyrna_struct_get_rna_type(), pyrna_subtype_set_rna(), radial_control_get_properties(), recalcData_nla(), BlenderSession::render(), RNA_function_as_string_keywords(), RNA_function_call_direct_va(), rna_function_parameter_parse(), RNA_property_update_cache_add(), rna_raw_access(), RNA_struct_find_function(), screenshot_draw(), sensor_add_exec(), sequencer_change_path_exec(), toolbox_invoke(), ui_node_draw_input(), ui_node_draw_node(), uiItemsFullEnumO(), uiLayoutOperatorButs(), uiTemplateHeader3D(), uiTemplatePreview(), v3d_editarmature_buts(), v3d_editmetaball_buts(), v3d_editvertex_buts(), v3d_posearmature_buts(), wm_operator_create(), WM_operator_properties_create(), and WM_operator_properties_create_ptr().
PointerRNA RNA_pointer_get (PointerRNA * ptr, const char * name)
Retrieve the named property from PointerRNA.
Definition at line 4379 of file rna_access.c.
References StructRNA::identifier, PointerRNA_NULL, RNA_property_pointer_get(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by blender_camera_from_object(), draw_actuator_sound(), draw_actuator_steering(), DocumentExporter::exportCurrentScene(), DocumentImporter::finish(), BlenderSync::get_scene_params(), BlenderSync::get_session_params(), BlenderSync::get_session_pause(), list_item_icon_get(), node_composit_buts_file_output(), node_composit_buts_file_output_details(), node_composit_buts_renderlayers(), node_shader_buts_geometry(), node_socket_button_output_file(), object_ray_visibility(), rna_idp_path(), uiTemplateKeymapItemProperties(), v3d_editarmature_buts(), v3d_transform_butsR(), and view3d_ob_drop_copy().
static void rna_pointer_inherit_id (StructRNA * type, PointerRNA * parent, PointerRNA * ptr) [static]
Definition at line 163 of file rna_access.c.
References PointerRNA::data, StructRNA::flag, PointerRNA::id, and STRUCT_ID.
Referenced by rna_pointer_inherit_refine(), RNA_property_collection_add(), and rna_property_collection_get_idp().
PointerRNA rna_pointer_inherit_refine (PointerRNA * ptr, StructRNA * type, void * data)
Definition at line 180 of file rna_access.c.
References data, PointerRNA::data, PointerRNA_NULL, StructRNA::refine, rna_pointer_inherit_id(), and PointerRNA::type.
Referenced by rna_array_lookup_int(), rna_listbase_lookup_int(), RNA_pointer_recast(), and RNA_property_pointer_get().
void RNA_pointer_recast (PointerRNA * ptr, PointerRNA * r_ptr)
Definition at line 204 of file rna_access.c.
References StructRNA::base, PointerRNA::data, PointerRNA::id, RNA_id_pointer_create(), rna_pointer_inherit_refine(), RNA_struct_is_ID(), and PointerRNA::type.
Referenced by pyrna_struct_type_recast().
void RNA_pointer_set (PointerRNA * ptr, const char * name, PointerRNA ptr_value)
Definition at line 4393 of file rna_access.c.
References StructRNA::identifier, RNA_property_pointer_set(), RNA_struct_find_property(), and PointerRNA::type.
int RNA_property_animateable (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1406 of file rna_access.c.
References PointerRNA::data, PropertyRNA::flag, PointerRNA::id, id_type_can_have_animdata(), PROP_ANIMATABLE, PROP_EDITABLE, and rna_ensure_property().
Referenced by add_driver_button_exec(), add_keyingset_button_exec(), animsys_write_rna_setting(), copy_driver_button_exec(), do_outliner_drivers_editop(), do_outliner_keyingset_editop(), insert_key_button_exec(), nlaevalchan_verify(), paste_driver_button_exec(), pyrna_struct_anim_args_parse(), rna_get_fcurve(), and ui_but_menu().
int RNA_property_animated (PointerRNA * UNUSEDptr, PropertyRNA * UNUSEDprop)
Definition at line 1420 of file rna_access.c.
int RNA_property_array_check (PropertyRNA * prop)
Definition at line 803 of file rna_access.c.
References rna_ensure_property_array_check().
Referenced by dtar_get_prop_val(), initTransform(), node_animation_properties(), pose_propagate_get_refVal(), pyrna_param_to_py(), pyrna_prop_CreatePyObject(), pyrna_prop_str(), pyrna_prop_to_py(), pyrna_py_to_prop(), pyrna_struct_anim_args_parse(), RNA_property_boolean_get(), RNA_property_boolean_get_array(), RNA_property_boolean_get_default(), RNA_property_boolean_get_default_array(), RNA_property_boolean_get_default_index(), RNA_property_boolean_get_index(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_boolean_set_index(), RNA_property_float_get(), RNA_property_float_get_array(), RNA_property_float_get_default(), RNA_property_float_get_default_array(), RNA_property_float_get_default_index(), RNA_property_float_get_index(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_float_set_index(), RNA_property_int_get(), RNA_property_int_get_array(), RNA_property_int_get_default_array(), RNA_property_int_get_index(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_int_set_index(), saveTransform(), ui_get_but_val(), ui_tooltip_create(), uiDefAutoButsRNA(), and uiItemFullR().
int RNA_property_array_dimension (PointerRNA * ptr, PropertyRNA * prop, int length[])
Definition at line 809 of file rna_access.c.
References PropertyRNA::arraydimension, rna_ensure_property(), and rna_ensure_property_multi_array_length().
Referenced by copy_values(), py_to_array_index(), pyrna_array_contains_py(), pyrna_math_object_from_array(), pyrna_prop_array_length(), pyrna_prop_array_subscript_slice(), pyrna_py_from_array_index(), pyrna_py_to_prop_array_index(), RNA_path_resolve_full(), ui_item_array(), validate_array(), and validate_array_length().
char RNA_property_array_item_char (PropertyRNA * prop, int index)
Definition at line 829 of file rna_access.c.
References ELEM, ELEM8, PROP_ACCELERATION, PROP_AXISANGLE, PROP_COLOR, PROP_COLOR_GAMMA, PROP_COORDS, PROP_DIRECTION, PROP_EULER, PROP_QUATERNION, PROP_TRANSLATION, PROP_VELOCITY, PROP_XYZ, PROP_XYZ_LENGTH, rna_ensure_property(), and PropertyRNA::subtype.
Referenced by getname_anim_fcurve(), and ui_item_array().
int RNA_property_array_item_index (PropertyRNA * prop, char name)
Definition at line 852 of file rna_access.c.
References ELEM, ELEM6, PROP_ACCELERATION, PROP_AXISANGLE, PROP_COLOR, PROP_COLOR_GAMMA, PROP_DIRECTION, PROP_EULER, PROP_QUATERNION, PROP_TRANSLATION, PROP_VELOCITY, PROP_XYZ, rna_ensure_property(), and PropertyRNA::subtype.
Referenced by RNA_path_resolve_full().
int RNA_property_array_length (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 798 of file rna_access.c.
References rna_ensure_property_array_length().
Referenced by ANIM_add_driver(), ANIM_apply_keyingset(), animsys_write_rna_setting(), delete_key_button_exec(), delete_keyframe(), do_outliner_drivers_editop(), dtar_get_prop_val(), eyedropper_sample(), foreach_attr_type(), foreach_parse_args(), getname_anim_fcurve(), handle_layer_buttons(), insert_key_button_exec(), insert_keyframe(), mathutils_rna_vector_set(), nladata_flush_channels(), node_animation_properties(), pose_propagate_get_refVal(), pyrna_array_contains_py(), pyrna_math_object_from_array(), pyrna_param_to_py(), pyrna_prop_array_ass_subscript(), pyrna_prop_array_bool(), pyrna_prop_array_length(), pyrna_struct_anim_args_parse(), pyrna_struct_path_resolve(), radial_control_get_path(), RNA_function_call_direct_va(), RNA_property_as_string(), RNA_property_copy(), RNA_property_float_get_array_range(), RNA_property_int_get_array_range(), RNA_property_reset(), rna_raw_access(), setting_get_rna_value(), tree_element_to_path(), ui_but_menu(), ui_def_but_rna(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_get_but_vectorf(), ui_item_rna_size(), ui_layer_but_cb(), ui_set_but_soft_range(), ui_set_but_val(), ui_set_but_vectorf(), uiDefAutoButR(), uiItemFullR(), uiTemplateLayers(), validate_array_length(), and widget_swatch().
char* RNA_property_as_string (bContext * C, PointerRNA * ptr, PropertyRNA * prop)
Definition at line 4637 of file rna_access.c.
References BLI_dynstr_append(), BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), BLI_strescape(), FALSE, i, EnumPropertyItem::identifier, len(), length(), MEM_freeN(), MEM_mallocN(), NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_ENUM_FLAG, PROP_FLOAT, PROP_INT, PROP_POINTER, PROP_STRING, CollectionPropertyIterator::ptr, RNA_pointer_as_string(), RNA_property_array_length(), RNA_property_boolean_get(), RNA_property_boolean_get_index(), RNA_property_collection_begin(), RNA_property_collection_end(), RNA_property_collection_next(), RNA_property_enum_get(), RNA_property_enum_identifier(), RNA_property_enum_items(), RNA_property_flag(), RNA_property_float_get(), RNA_property_float_get_index(), RNA_property_int_get(), RNA_property_int_get_index(), RNA_property_pointer_get(), RNA_property_string_get(), RNA_property_string_length(), RNA_property_type(), TRUE, CollectionPropertyIterator::valid, and EnumPropertyItem::value.
Referenced by RNA_pointer_as_string(), and RNA_pointer_as_string_keywords_ex().
int RNA_property_boolean_get (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1615 of file rna_access.c.
References BLI_assert, BoolPropertyRNA::defaultvalue, BoolPropertyRNA::get, IDP_Int, PROP_BOOLEAN, rna_idproperty_check(), RNA_property_array_check(), and RNA_property_type().
Referenced by ANIM_add_driver(), dtar_get_prop_val(), initTransform(), pose_propagate_get_refVal(), pyrna_prop_to_py(), radial_control_get_properties(), RNA_boolean_get(), RNA_property_as_string(), RNA_property_boolean_get_array(), RNA_property_copy(), rna_raw_access(), setting_get_rna_value(), ui_get_but_val(), and uiItemFullR().
void RNA_property_boolean_get_array (PointerRNA * ptr, PropertyRNA * prop, int * values)
Definition at line 1660 of file rna_access.c.
References PropertyRNA::arraydimension, BLI_assert, BoolPropertyRNA::defaultarray, BoolPropertyRNA::getarray, IDP_Array, IDProperty::len, PROP_BOOLEAN, rna_idproperty_check(), RNA_property_array_check(), RNA_property_boolean_get(), RNA_property_type(), and PropertyRNA::totarraylength.
Referenced by initTransform(), prop_subscript_ass_array_slice(), pyrna_array_contains_py(), pyrna_prop_array_subscript_slice(), RNA_boolean_get_array(), RNA_property_boolean_get_index(), RNA_property_boolean_set_index(), RNA_property_copy(), rna_raw_access(), and ui_item_array().
int RNA_property_boolean_get_default (PointerRNA * UNUSEDptr, PropertyRNA * prop)
Definition at line 1768 of file rna_access.c.
References BLI_assert, BoolPropertyRNA::defaultvalue, PROP_BOOLEAN, RNA_property_array_check(), and RNA_property_type().
Referenced by RNA_property_reset().
void RNA_property_boolean_get_default_array (PointerRNA * UNUSEDptr, PropertyRNA * prop, int * values)
Definition at line 1778 of file rna_access.c.
References PropertyRNA::arraydimension, BLI_assert, BoolPropertyRNA::defaultarray, BoolPropertyRNA::defaultvalue, PROP_BOOLEAN, RNA_property_array_check(), RNA_property_type(), and PropertyRNA::totarraylength.
Referenced by RNA_property_boolean_get_default_index(), and RNA_property_reset().
int RNA_property_boolean_get_default_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 1793 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_BOOLEAN, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_boolean_get_default_array(), and RNA_property_type().
Referenced by RNA_property_reset().
int RNA_property_boolean_get_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 1684 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_BOOLEAN, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_boolean_get_array(), and RNA_property_type().
Referenced by ANIM_add_driver(), dtar_get_prop_val(), pose_propagate_get_refVal(), pyrna_array_index(), RNA_property_as_string(), RNA_property_copy(), setting_get_rna_value(), ui_get_but_val(), uiItemFullR(), and uiTemplateLayers().
void RNA_property_boolean_set (PointerRNA * ptr, PropertyRNA * prop, int value)
Definition at line 1631 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, IDPropertyTemplate::i, PropertyRNA::identifier, IDP_AddToGroup(), IDP_INT, IDP_Int, IDP_New(), PROP_BOOLEAN, PROP_EDITABLE, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_array_check(), RNA_property_type(), RNA_struct_idprops(), and BoolPropertyRNA::set.
Referenced by animsys_write_rna_setting(), nladata_flush_channels(), pyrna_py_to_prop(), RNA_boolean_set(), RNA_property_boolean_set_array(), RNA_property_copy(), RNA_property_reset(), rna_raw_access(), saveTransform(), and ui_set_but_val().
void RNA_property_boolean_set_array (PointerRNA * ptr, PropertyRNA * prop, const int * values)
Definition at line 1708 of file rna_access.c.
References IDPropertyTemplate::array, PropertyRNA::arraydimension, BLI_assert, PropertyRNA::flag, PropertyRNA::identifier, IDP_AddToGroup(), IDP_ARRAY, IDP_Array, IDP_INT, IDP_Int, IDP_New(), IDPropertyTemplate::len, IDProperty::len, PROP_BOOLEAN, PROP_EDITABLE, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_array_check(), RNA_property_boolean_set(), RNA_property_type(), RNA_struct_idprops(), BoolPropertyRNA::setarray, PropertyRNA::totarraylength, and IDPropertyTemplate::type.
Referenced by prop_subscript_ass_array_slice(), pyrna_py_to_array(), RNA_boolean_set_array(), RNA_property_boolean_set_index(), RNA_property_copy(), RNA_property_reset(), rna_raw_access(), and saveTransform().
void RNA_property_boolean_set_index (PointerRNA * ptr, PropertyRNA * prop, int index, int value)
Definition at line 1744 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_BOOLEAN, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_boolean_get_array(), RNA_property_boolean_set_array(), and RNA_property_type().
Referenced by animsys_write_rna_setting(), bool_set_index(), handle_layer_buttons(), nladata_flush_channels(), pyrna_py_to_prop_array_index(), RNA_property_copy(), RNA_property_reset(), ui_layer_but_cb(), and ui_set_but_val().
void RNA_property_collection_add (PointerRNA * ptr, PropertyRNA * prop, PointerRNA * r_ptr)
Definition at line 2705 of file rna_access.c.
References BLI_assert, PointerRNA::data, PropertyRNA::flag, FUNC_USE_CONTEXT, PropertyRNA::identifier, IDP_AddToGroup(), IDP_AppendArray(), IDP_GetIndexArray(), IDP_GROUP, IDP_New(), IDP_NewIDPArray(), CollectionPropertyRNA::item_type, IDProperty::len, MEM_freeN(), NULL, PROP_COLLECTION, PROP_IDPROPERTY, RNA_function_call(), rna_idproperty_check(), RNA_parameter_list_create(), RNA_parameter_list_free(), rna_pointer_inherit_id(), RNA_property_type(), RNA_struct_idprops(), and PointerRNA::type.
Referenced by file_sfile_to_operator(), pyrna_prop_collection_idprop_add(), pyrna_py_to_prop(), and RNA_collection_add().
int RNA_property_collection_assign_int (PointerRNA * ptr, PropertyRNA * prop, const int key, const PointerRNA * assign_ptr)
Definition at line 2952 of file rna_access.c.
References CollectionPropertyRNA::assignint, BLI_assert, PROP_COLLECTION, rna_ensure_property(), and RNA_property_type().
Referenced by pyrna_prop_collection_ass_subscript_int().
void RNA_property_collection_begin (PointerRNA * ptr, PropertyRNA * prop, CollectionPropertyIterator * iter)
Definition at line 2627 of file rna_access.c.
References CollectionPropertyRNA::begin, BLI_assert, PropertyRNA::flag, IDP_IDPArray, CollectionPropertyIterator::idprop, IDProperty::len, NULL, CollectionPropertyIterator::parent, CollectionPropertyIterator::prop, PROP_COLLECTION, PROP_IDPROPERTY, tRnaUpdateCacheElem::ptr, rna_idproperty_check(), rna_iterator_array_begin(), rna_property_collection_get_idp(), RNA_property_type(), and CollectionPropertyIterator::valid.
Referenced by pyrna_prop_collection_bool(), pyrna_prop_collection_iter_CreatePyObject(), pyrna_prop_collection_subscript_slice(), RNA_collection_begin(), RNA_property_as_string(), RNA_property_collection_length(), RNA_property_collection_lookup_index(), RNA_property_collection_lookup_int(), RNA_property_collection_lookup_string(), and RNA_property_collection_raw_array().
void RNA_property_collection_clear (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2842 of file rna_access.c.
References BLI_assert, IDP_ResizeIDPArray(), PROP_COLLECTION, rna_idproperty_check(), and RNA_property_type().
Referenced by file_sfile_to_operator(), pyrna_prop_collection_idprop_clear(), and RNA_collection_clear().
void RNA_property_collection_end (CollectionPropertyIterator * iter)
Definition at line 2669 of file rna_access.c.
References CollectionPropertyRNA::end, CollectionPropertyIterator::idprop, CollectionPropertyIterator::prop, rna_ensure_property(), and rna_iterator_array_end().
Referenced by pyrna_prop_collection_bool(), pyrna_prop_collection_iter_dealloc(), pyrna_prop_collection_subscript_slice(), RNA_property_as_string(), RNA_property_collection_length(), RNA_property_collection_lookup_index(), RNA_property_collection_lookup_int(), RNA_property_collection_lookup_string(), and RNA_property_collection_raw_array().
static void rna_property_collection_get_idp (CollectionPropertyIterator * iter) [static]
Definition at line 2618 of file rna_access.c.
References PointerRNA::data, CollectionPropertyRNA::item_type, CollectionPropertyIterator::parent, CollectionPropertyIterator::prop, CollectionPropertyIterator::ptr, rna_iterator_array_get(), rna_pointer_inherit_id(), and PointerRNA::type.
Referenced by RNA_property_collection_begin(), and RNA_property_collection_next().
int RNA_property_collection_length (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2679 of file rna_access.c.
References BLI_assert, IDProperty::len, length(), CollectionPropertyRNA::length, PROP_COLLECTION, rna_idproperty_check(), RNA_property_collection_begin(), RNA_property_collection_end(), RNA_property_collection_next(), RNA_property_type(), and CollectionPropertyIterator::valid.
Referenced by foreach_parse_args(), pyrna_prop_collection_ass_subscript(), pyrna_prop_collection_ass_subscript_int(), pyrna_prop_collection_length(), pyrna_prop_collection_subscript(), pyrna_prop_collection_subscript_int(), RNA_collection_length(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_change_path_exec(), uiDefAutoButR(), uiTemplateList(), and wm_link_append_exec().
int RNA_property_collection_lookup_index (PointerRNA * ptr, PropertyRNA * prop, PointerRNA * t_ptr)
Definition at line 2852 of file rna_access.c.
References BLI_assert, PointerRNA::data, PROP_COLLECTION, CollectionPropertyIterator::ptr, RNA_property_collection_begin(), RNA_property_collection_end(), RNA_property_collection_next(), RNA_property_type(), and CollectionPropertyIterator::valid.
int RNA_property_collection_lookup_int (PointerRNA * ptr, PropertyRNA * prop, int key, PointerRNA * r_ptr)
Definition at line 2873 of file rna_access.c.
References BLI_assert, i, CollectionPropertyRNA::lookupint, PROP_COLLECTION, CollectionPropertyIterator::ptr, rna_ensure_property(), RNA_property_collection_begin(), RNA_property_collection_end(), RNA_property_collection_next(), RNA_property_type(), and CollectionPropertyIterator::valid.
Referenced by node_buts_rgb(), node_buts_value(), pyrna_prop_collection_subscript_int(), rna_idp_path(), and RNA_path_resolve_full().
int RNA_property_collection_lookup_string (PointerRNA * ptr, PropertyRNA * prop, const char * key, PointerRNA * r_ptr)
Definition at line 2904 of file rna_access.c.
References BLI_assert, PointerRNA::data, CollectionPropertyRNA::lookupstring, MEM_freeN(), StructRNA::nameproperty, PROP_COLLECTION, CollectionPropertyIterator::ptr, rna_ensure_property(), RNA_property_collection_begin(), RNA_property_collection_end(), RNA_property_collection_next(), RNA_property_string_get_alloc(), RNA_property_type(), strlen(), PointerRNA::type, and CollectionPropertyIterator::valid.
Referenced by draw_actuator_armature(), draw_sensor_armature(), pyrna_basetype_getattro(), pyrna_prop_collection_contains(), pyrna_prop_collection_get(), pyrna_prop_collection_subscript_str(), RNA_path_resolve_full(), RNA_struct_find_property(), and ui_set_but_string().
int RNA_property_collection_move (PointerRNA * ptr, PropertyRNA * prop, int key, int pos)
Definition at line 2812 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, IDP_IDPArray, IDProperty::len, len(), PROP_COLLECTION, PROP_IDPROPERTY, rna_idproperty_check(), and RNA_property_type().
Referenced by pyrna_prop_collection_idprop_move().
void RNA_property_collection_next (CollectionPropertyIterator * iter)
Definition at line 2655 of file rna_access.c.
References CollectionPropertyIterator::idprop, CollectionPropertyRNA::next, CollectionPropertyIterator::prop, rna_ensure_property(), rna_iterator_array_next(), rna_property_collection_get_idp(), and CollectionPropertyIterator::valid.
Referenced by pyrna_prop_collection_iter_next(), pyrna_prop_collection_subscript_slice(), RNA_property_as_string(), RNA_property_collection_length(), RNA_property_collection_lookup_index(), RNA_property_collection_lookup_int(), and RNA_property_collection_lookup_string().
int RNA_property_collection_raw_array (PointerRNA * ptr, PropertyRNA * prop, PropertyRNA * itemprop, RawArray * array)
Definition at line 2974 of file rna_access.c.
References RawArray::array, BLI_assert, PointerRNA::data, PropertyRNA::flag, if(), CollectionPropertyIterator::internal, RawArray::len, NULL, PROP_COLLECTION, PROP_RAW_ACCESS, PROP_RAW_ARRAY, CollectionPropertyIterator::ptr, PropertyRNA::rawoffset, PropertyRNA::rawtype, RNA_property_collection_begin(), RNA_property_collection_end(), RNA_property_editable(), RNA_property_type(), RawArray::stride, RawArray::type, and CollectionPropertyIterator::valid.
Referenced by rna_raw_access().
int RNA_property_collection_raw_get (ReportList * reports, PointerRNA * ptr, PropertyRNA * prop, const char * propname, void * array, RawPropertyType type, int len)
Definition at line 3351 of file rna_access.c.
References rna_raw_access().
Referenced by foreach_getset().
int RNA_property_collection_raw_set (ReportList * reports, PointerRNA * ptr, PropertyRNA * prop, const char * propname, void * array, RawPropertyType type, int len)
Definition at line 3357 of file rna_access.c.
References rna_raw_access().
Referenced by foreach_getset().
int RNA_property_collection_remove (PointerRNA * ptr, PropertyRNA * prop, int key)
Definition at line 2764 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, FUNC_USE_CONTEXT, IDP_IDPArray, IDP_ResizeIDPArray(), IDProperty::len, len(), NULL, PROP_COLLECTION, PROP_IDPROPERTY, RNA_function_call(), rna_idproperty_check(), RNA_parameter_list_create(), RNA_parameter_list_free(), and RNA_property_type().
Referenced by pyrna_prop_collection_idprop_remove().
int RNA_property_collection_type_get (PointerRNA * ptr, PropertyRNA * prop, PointerRNA * r_ptr)
Definition at line 2966 of file rna_access.c.
References BLI_assert, PROP_COLLECTION, tRnaUpdateCacheElem::ptr, rna_ensure_property(), RNA_property_type(), and PointerRNA::type.
Referenced by pyrna_dir_members_py(), pyrna_prop_collection_getattro(), pyrna_prop_collection_setattro(), pyrna_prop_dir(), pyrna_prop_str(), pyrna_py_to_prop(), and RNA_path_resolve_full().
int RNA_property_copy (PointerRNA * ptr, PointerRNA * fromptr, PropertyRNA * prop, int index)
Definition at line 5613 of file rna_access.c.
References len(), MEM_callocN(), MEM_freeN(), NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_POINTER, PROP_STRING, RNA_property_array_length(), RNA_property_boolean_get(), RNA_property_boolean_get_array(), RNA_property_boolean_get_index(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_boolean_set_index(), RNA_property_enum_get(), RNA_property_enum_set(), RNA_property_float_get(), RNA_property_float_get_array(), RNA_property_float_get_index(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_float_set_index(), RNA_property_int_get(), RNA_property_int_get_array(), RNA_property_int_get_index(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_int_set_index(), RNA_property_pointer_get(), RNA_property_pointer_set(), RNA_property_string_get_alloc(), RNA_property_string_set(), and RNA_property_type().
Referenced by copy_to_selected_button_exec().
const char* RNA_property_description (PropertyRNA * prop)
Definition at line 768 of file rna_access.c.
References rna_ensure_property_description().
Referenced by ui_but_menu(), ui_tooltip_create(), and uiItemMenuEnumR().
int RNA_property_editable (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1366 of file rna_access.c.
References PointerRNA::data, PropertyRNA::editable, PropertyRNA::flag, PointerRNA::id, PROP_EDITABLE, PROP_LIB_EXCEPTION, and rna_ensure_property().
Referenced by copy_to_selected_button_exec(), copy_to_selected_button_poll(), eyedropper_init(), id_single_user(), reset_default_button_exec(), reset_default_button_poll(), RNA_property_collection_raw_array(), rna_raw_access(), template_ID(), ui_def_but_rna(), ui_set_but_string(), and ui_set_but_val().
int RNA_property_editable_flag (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1376 of file rna_access.c.
References PropertyRNA::editable, PropertyRNA::flag, PROP_EDITABLE, and rna_ensure_property().
Referenced by mathutils_rna_matrix_set(), mathutils_rna_vector_set(), mathutils_rna_vector_set_index(), pyrna_prop_array_ass_subscript(), and pyrna_struct_setattro().
int RNA_property_editable_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 1386 of file rna_access.c.
References PointerRNA::data, PropertyRNA::editable, PropertyRNA::flag, PointerRNA::id, PropertyRNA::itemeditable, PROP_EDITABLE, PROP_LIB_EXCEPTION, and rna_ensure_property().
int RNA_property_enum_bitflag_identifiers (bContext * C, PointerRNA * ptr, PropertyRNA * prop, const int value, const char ** identifier)
Definition at line 1334 of file rna_access.c.
References MEM_freeN(), NULL, RNA_enum_bitflag_identifiers(), and RNA_property_enum_items().
Referenced by pyrna_enum_to_py().
int RNA_property_enum_get (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2459 of file rna_access.c.
References BLI_assert, EnumPropertyRNA::defaultvalue, EnumPropertyRNA::get, IDP_Int, PROP_ENUM, rna_idproperty_check(), and RNA_property_type().
Referenced by actuator_add_exec(), controller_add_exec(), dtar_get_prop_val(), DocumentExporter::exportCurrentScene(), get_enum_identifier(), list_item_row(), node_composit_buts_renderlayers(), node_socket_button_output_file(), pose_propagate_get_refVal(), poselib_remove_exec(), pyrna_prop_to_py(), pyrna_rotation_euler_order_get(), RNA_enum_get(), RNA_enum_is_equal(), RNA_property_as_string(), RNA_property_copy(), sensor_add_exec(), setting_get_rna_value(), ui_def_but_rna(), ui_get_but_val(), ui_set_but_val(), and uiItemFullR().
int RNA_property_enum_get_default (PointerRNA * UNUSEDptr, PropertyRNA * prop)
Definition at line 2500 of file rna_access.c.
References BLI_assert, EnumPropertyRNA::defaultvalue, PROP_ENUM, and RNA_property_type().
Referenced by RNA_property_reset().
int RNA_property_enum_identifier (bContext * C, PointerRNA * ptr, PropertyRNA * prop, const int value, const char ** identifier)
Definition at line 1301 of file rna_access.c.
References MEM_freeN(), NULL, RNA_enum_identifier(), and RNA_property_enum_items().
Referenced by get_enum_identifier(), BlenderSync::get_session_params(), node_composit_buts_renderlayers(), pyrna_enum_to_py(), and RNA_property_as_string().
void RNA_property_enum_items (bContext * C, PointerRNA * ptr, PropertyRNA * prop, EnumPropertyItem ** item, int * totitem, int * free)
Definition at line 1152 of file rna_access.c.
References PropertyRNA::flag, EnumPropertyRNA::item, EnumPropertyRNA::itemf, NULL, PROP_ENUM_NO_CONTEXT, rna_ensure_property(), and EnumPropertyRNA::totitem.
Referenced by operator_enum_search_cb(), pyrna_enum_as_string(), pyrna_enum_to_py(), pyrna_prop_to_enum_bitfield(), RNA_enum_is_equal(), RNA_property_as_string(), RNA_property_enum_bitflag_identifiers(), RNA_property_enum_identifier(), RNA_property_enum_items_gettexted(), RNA_property_enum_name(), and RNA_property_enum_value().
void RNA_property_enum_items_gettexted (bContext * C, PointerRNA * ptr, PropertyRNA * prop, EnumPropertyItem ** item, int * totitem, int * free)
Definition at line 1183 of file rna_access.c.
References BLF_gettext(), BLF_pgettext(), BLF_translate_iface(), EnumPropertyItem::description, i, EnumPropertyItem::identifier, MEM_callocN(), EnumPropertyItem::name, RNA_property_enum_items(), and PropertyRNA::translation_context.
Referenced by ui_def_but_rna(), ui_item_enum_expand(), ui_menu_enumpropname(), ui_tooltip_create(), uiItemEnumO_string(), uiItemEnumR_string(), uiItemsEnumR(), and uiItemsFullEnumO().
int RNA_property_enum_name (bContext * C, PointerRNA * ptr, PropertyRNA * prop, const int value, const char ** name)
Definition at line 1318 of file rna_access.c.
References MEM_freeN(), NULL, RNA_enum_name(), and RNA_property_enum_items().
Referenced by actuator_add_exec(), controller_add_exec(), list_item_row(), node_socket_button_output_file(), and sensor_add_exec().
void* RNA_property_enum_py_data_get (PropertyRNA * prop)
Definition at line 2509 of file rna_access.c.
References BLI_assert, PROP_ENUM, EnumPropertyRNA::py_data, and RNA_property_type().
Referenced by bpy_props_enum_itemf().
void RNA_property_enum_set (PointerRNA * ptr, PropertyRNA * prop, int value)
Definition at line 2474 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, IDPropertyTemplate::i, PropertyRNA::identifier, IDP_AddToGroup(), IDP_INT, IDP_Int, IDP_New(), PROP_EDITABLE, PROP_ENUM, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_type(), RNA_struct_idprops(), and EnumPropertyRNA::set.
Referenced by animsys_write_rna_setting(), DocumentImporter::finish(), mathutils_rna_vector_set(), nladata_flush_channels(), operator_enum_call_cb(), pyrna_py_to_prop(), RNA_enum_set(), RNA_enum_set_identifier(), RNA_property_copy(), RNA_property_reset(), saveTransform(), ui_set_but_val(), uiItemEnumO_ptr(), uiItemEnumO_ptr__internal(), uiItemEnumO_string(), uiItemEnumO_value(), and uiItemsFullEnumO().
int RNA_property_enum_value (bContext * C, PointerRNA * ptr, PropertyRNA * prop, const char * identifier, int * value)
Definition at line 1229 of file rna_access.c.
References EnumPropertyItem::identifier, MEM_freeN(), NULL, RNA_property_enum_items(), and EnumPropertyItem::value.
Referenced by pyrna_string_to_enum(), and RNA_enum_set_identifier().
int RNA_property_flag (PropertyRNA * prop)
Definition at line 788 of file rna_access.c.
References PropertyRNA::flag, and rna_ensure_property().
Referenced by bpy_class_call(), bpy_class_validate(), bpy_props_enum_itemf(), id_search_cb(), py_to_array(), pyrna_enum_to_py(), pyrna_func_call(), pyrna_math_object_from_array(), pyrna_param_to_py(), pyrna_prop_collection_type_check(), pyrna_prop_CreatePyObject(), pyrna_py_to_prop(), pyrna_srna_contains_pointer_prop_srna(), pyrna_struct_is_property_hidden(), rna_function_arg_count(), RNA_function_call_direct_va(), RNA_pointer_as_string_keywords_ex(), RNA_property_as_string(), rna_search_cb(), template_ID(), template_keymap_item_properties(), ui_check_but(), ui_is_but_sel(), ui_set_but_val(), uiDefAutoButsRNA(), uiItemFullR(), validate_array_length(), and WM_operator_properties_reset().
int RNA_property_float_clamp (PointerRNA * ptr, PropertyRNA * prop, float * value)
Definition at line 1056 of file rna_access.c.
References max, min, and RNA_property_float_range().
Referenced by mathutils_rna_vector_set_index(), pyrna_py_to_prop(), and pyrna_py_to_prop_array_index().
float RNA_property_float_get (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2048 of file rna_access.c.
References BLI_assert, FloatPropertyRNA::defaultvalue, FloatPropertyRNA::get, IDP_Double, IDP_Float, IDP_FLOAT, PROP_FLOAT, rna_idproperty_check(), RNA_property_array_check(), RNA_property_type(), and IDProperty::type.
Referenced by ANIM_add_driver(), dtar_get_prop_val(), edbm_select_similar_exec(), pose_propagate_get_refVal(), pose_slide_apply_props(), pyrna_prop_to_py(), radial_control_invoke(), radial_control_paint_tex(), RNA_float_get(), RNA_property_as_string(), RNA_property_copy(), RNA_property_float_get_array(), rna_raw_access(), setting_get_rna_value(), ui_get_but_val(), and ui_tooltip_create().
void RNA_property_float_get_array (PointerRNA * ptr, PropertyRNA * prop, float * values)
Definition at line 2101 of file rna_access.c.
References PropertyRNA::arraydimension, BLI_assert, FloatPropertyRNA::defaultarray, FloatPropertyRNA::getarray, i, IDP_Array, IDP_FLOAT, IDProperty::len, PROP_FLOAT, rna_idproperty_check(), RNA_property_array_check(), RNA_property_float_get(), RNA_property_type(), IDProperty::subtype, and PropertyRNA::totarraylength.
Referenced by do_picker_rna_cb(), eyedropper_sample(), initTransform(), mathutils_rna_matrix_get(), mathutils_rna_vector_get(), prop_subscript_ass_array_slice(), pyrna_array_contains_py(), pyrna_math_object_from_array(), pyrna_prop_array_subscript_slice(), radial_control_modal(), radial_control_paint_cursor(), radial_control_paint_tex(), radial_control_set_initial_mouse(), RNA_float_get_array(), RNA_property_copy(), RNA_property_float_get_array_range(), RNA_property_float_get_index(), RNA_property_float_set_index(), rna_raw_access(), uiBlockPicker(), and uiTemplateColorWheel().
void RNA_property_float_get_array_range (PointerRNA * ptr, PropertyRNA * prop, float values[2])
Definition at line 2131 of file rna_access.c.
References i, MAX2, MEM_freeN(), MEM_mallocN(), MIN2, RNA_property_array_length(), and RNA_property_float_get_array().
Referenced by ui_set_but_soft_range().
float RNA_property_float_get_default (PointerRNA * UNUSEDptr, PropertyRNA * prop)
Definition at line 2264 of file rna_access.c.
References BLI_assert, FloatPropertyRNA::defaultvalue, PROP_FLOAT, RNA_property_array_check(), and RNA_property_type().
Referenced by RNA_property_reset().
void RNA_property_float_get_default_array (PointerRNA * UNUSEDptr, PropertyRNA * prop, float * values)
Definition at line 2274 of file rna_access.c.
References PropertyRNA::arraydimension, BLI_assert, FloatPropertyRNA::defaultarray, FloatPropertyRNA::defaultvalue, PROP_FLOAT, RNA_property_array_check(), RNA_property_type(), and PropertyRNA::totarraylength.
Referenced by RNA_property_float_get_default_index(), RNA_property_reset(), ui_do_but_HSVCIRCLE(), and ui_do_but_HSVCUBE().
float RNA_property_float_get_default_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 2289 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_FLOAT, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_float_get_default_array(), and RNA_property_type().
Referenced by RNA_property_reset().
float RNA_property_float_get_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 2168 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_FLOAT, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_float_get_array(), and RNA_property_type().
Referenced by ANIM_add_driver(), dtar_get_prop_val(), mathutils_rna_vector_get_index(), pose_propagate_get_refVal(), pyrna_array_index(), RNA_property_as_string(), RNA_property_copy(), setting_get_rna_value(), ui_get_but_val(), ui_get_but_vectorf(), ui_tooltip_create(), and widget_swatch().
void RNA_property_float_range (PointerRNA * ptr, PropertyRNA * prop, float * hardmin, float * hardmax)
Definition at line 976 of file rna_access.c.
References FLT_MAX, FloatPropertyRNA::hardmax, FloatPropertyRNA::hardmin, IDP_Double, IDP_DOUBLE, IDP_GetPropertyTypeFromGroup(), PropertyRNA::magic, FloatPropertyRNA::range, rna_ensure_property(), rna_idproperty_ui(), and RNA_MAGIC.
Referenced by mathutils_rna_vector_set(), prop_subscript_ass_array_slice(), RNA_property_float_clamp(), and ui_def_but_rna().
void RNA_property_float_set (PointerRNA * ptr, PropertyRNA * prop, float value)
Definition at line 2068 of file rna_access.c.
References BLI_assert, IDPropertyTemplate::f, PropertyRNA::flag, PropertyRNA::identifier, IDP_AddToGroup(), IDP_Double, IDP_Float, IDP_FLOAT, IDP_New(), PROP_EDITABLE, PROP_FLOAT, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_array_check(), RNA_property_type(), RNA_struct_idprops(), FloatPropertyRNA::set, and IDProperty::type.
Referenced by animsys_write_rna_setting(), edbm_select_similar_exec(), DocumentImporter::finish(), nladata_flush_channels(), pose_slide_apply_props(), pyrna_py_to_prop(), radial_control_set_value(), RNA_float_set(), RNA_property_copy(), RNA_property_float_set_array(), RNA_property_reset(), rna_raw_access(), saveTransform(), and ui_set_but_val().
void RNA_property_float_set_array (PointerRNA * ptr, PropertyRNA * prop, const float * values)
Definition at line 2193 of file rna_access.c.
References IDPropertyTemplate::array, PropertyRNA::arraydimension, BLI_assert, PropertyRNA::flag, i, PropertyRNA::identifier, IDP_AddToGroup(), IDP_ARRAY, IDP_Array, IDP_Double, IDP_Float, IDP_FLOAT, IDP_New(), IDPropertyTemplate::len, IDProperty::len, PROP_EDITABLE, PROP_FLOAT, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_array_check(), RNA_property_float_set(), RNA_property_type(), RNA_struct_idprops(), FloatPropertyRNA::setarray, IDProperty::subtype, PropertyRNA::totarraylength, IDPropertyTemplate::type, and IDProperty::type.
Referenced by eyedropper_sample(), mathutils_rna_matrix_set(), mathutils_rna_vector_set(), prop_subscript_ass_array_slice(), pyrna_py_to_array(), RNA_float_set_array(), RNA_property_copy(), RNA_property_float_set_index(), RNA_property_reset(), rna_raw_access(), and saveTransform().
void RNA_property_float_set_index (PointerRNA * ptr, PropertyRNA * prop, int index, float value)
Definition at line 2240 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_FLOAT, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_float_get_array(), RNA_property_float_set_array(), and RNA_property_type().
Referenced by animsys_write_rna_setting(), float_set_index(), mathutils_rna_vector_set_index(), nladata_flush_channels(), pyrna_py_to_prop_array_index(), RNA_property_copy(), RNA_property_reset(), ui_set_but_val(), and ui_set_but_vectorf().
void RNA_property_float_ui_range (PointerRNA * ptr, PropertyRNA * prop, float * softmin, float * softmax, float * step, float * precision)
Definition at line 1010 of file rna_access.c.
References FLT_MAX, IDP_Double, IDP_DOUBLE, IDP_GetPropertyTypeFromGroup(), PropertyRNA::magic, MAX2, MIN2, FloatPropertyRNA::precision, FloatPropertyRNA::range, rna_ensure_property(), rna_idproperty_ui(), RNA_MAGIC, FloatPropertyRNA::softmax, FloatPropertyRNA::softmin, and FloatPropertyRNA::step.
Referenced by radial_control_invoke(), ui_def_but_rna(), ui_set_but_soft_range(), uiBlockPicker(), and uiTemplateColorWheel().
const char* RNA_property_identifier (PropertyRNA * prop)
Definition at line 763 of file rna_access.c.
References rna_ensure_property_identifier().
Referenced by ANIM_channel_draw_widgets(), bpy_class_validate(), file_panel_check_prop(), image_save_as_draw_check_prop(), insert_key_button_exec(), mathutils_rna_matrix_set(), mathutils_rna_vector_set(), mathutils_rna_vector_set_index(), operator_enum_search_cb(), pastebuf_match_path_property(), py_to_array_index(), pyrna_enum_to_py(), pyrna_func_call(), pyrna_prop_array_ass_subscript(), pyrna_prop_path_from_id(), pyrna_prop_repr(), pyrna_prop_str(), pyrna_prop_to_enum_bitfield(), pyrna_prop_validity_check(), pyrna_py_to_prop(), pyrna_pydict_to_props(), pyrna_srna_contains_pointer_prop_srna(), pyrna_struct_setattro(), RNA_function_call_direct_va(), RNA_parameter_get_lookup(), RNA_parameter_set_lookup(), RNA_path_append(), RNA_path_from_ID_to_property(), RNA_path_from_ID_to_struct(), RNA_pointer_as_string(), RNA_pointer_as_string_keywords_ex(), screenshot_draw_check_prop(), template_keymap_item_properties(), ui_but_menu(), ui_intro_button(), ui_tooltip_create(), validate_array(), validate_array_length(), visualkey_can_use(), visualkey_get_value(), WM_menu_invoke(), wm_operator_create(), and WM_operator_properties_reset().
int RNA_property_int_clamp (PointerRNA * ptr, PropertyRNA * prop, int * value)
Definition at line 1075 of file rna_access.c.
References max, min, and RNA_property_int_range().
Referenced by pyrna_py_to_prop(), and pyrna_py_to_prop_array_index().
int RNA_property_int_get (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1817 of file rna_access.c.
References BLI_assert, IntPropertyRNA::defaultvalue, IntPropertyRNA::get, IDP_Int, PROP_INT, rna_idproperty_check(), RNA_property_array_check(), and RNA_property_type().
Referenced by ANIM_add_driver(), dtar_get_prop_val(), pose_propagate_get_refVal(), pose_slide_apply_props(), pyrna_prop_to_py(), radial_control_invoke(), RNA_int_get(), RNA_property_as_string(), RNA_property_copy(), RNA_property_int_get_array(), rna_raw_access(), setting_get_rna_value(), ui_get_but_val(), ui_handle_list_event(), and uiTemplateList().
void RNA_property_int_get_array (PointerRNA * ptr, PropertyRNA * prop, int * values)
Definition at line 1861 of file rna_access.c.
References PropertyRNA::arraydimension, BLI_assert, IntPropertyRNA::defaultarray, IntPropertyRNA::getarray, IDP_Array, IDProperty::len, PROP_INT, rna_idproperty_check(), RNA_property_array_check(), RNA_property_int_get(), RNA_property_type(), and PropertyRNA::totarraylength.
Referenced by prop_subscript_ass_array_slice(), pyrna_array_contains_py(), pyrna_prop_array_subscript_slice(), RNA_int_get_array(), RNA_property_copy(), RNA_property_int_get_array_range(), RNA_property_int_get_index(), RNA_property_int_set_index(), and rna_raw_access().
void RNA_property_int_get_array_range (PointerRNA * ptr, PropertyRNA * prop, int values[2])
Definition at line 1885 of file rna_access.c.
References i, MAX2, MEM_freeN(), MEM_mallocN(), MIN2, RNA_property_array_length(), and RNA_property_int_get_array().
Referenced by ui_set_but_soft_range().
int RNA_property_int_get_default (PointerRNA * UNUSEDptr, PropertyRNA * prop)
Definition at line 2006 of file rna_access.c.
References IntPropertyRNA::defaultvalue.
Referenced by RNA_property_reset().
void RNA_property_int_get_default_array (PointerRNA * UNUSEDptr, PropertyRNA * prop, int * values)
Definition at line 2012 of file rna_access.c.
References PropertyRNA::arraydimension, BLI_assert, IntPropertyRNA::defaultarray, IntPropertyRNA::defaultvalue, PROP_INT, RNA_property_array_check(), RNA_property_type(), and PropertyRNA::totarraylength.
Referenced by RNA_property_int_get_default_index(), and RNA_property_reset().
int RNA_property_int_get_default_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 2027 of file rna_access.c.
References len(), MEM_callocN(), MEM_freeN(), rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, and RNA_property_int_get_default_array().
Referenced by RNA_property_reset().
int RNA_property_int_get_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 1922 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_INT, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_int_get_array(), and RNA_property_type().
Referenced by ANIM_add_driver(), dtar_get_prop_val(), pose_propagate_get_refVal(), pyrna_array_index(), RNA_property_as_string(), RNA_property_copy(), setting_get_rna_value(), and ui_get_but_val().
void RNA_property_int_range (PointerRNA * ptr, PropertyRNA * prop, int * hardmin, int * hardmax)
Definition at line 901 of file rna_access.c.
References IntPropertyRNA::hardmax, IntPropertyRNA::hardmin, IDP_GetPropertyTypeFromGroup(), IDP_Int, IDP_INT, PropertyRNA::magic, IntPropertyRNA::range, rna_ensure_property(), rna_idproperty_ui(), and RNA_MAGIC.
Referenced by prop_subscript_ass_array_slice(), RNA_property_int_clamp(), ui_def_but_rna(), ui_handle_list_event(), and uiTemplateList().
void RNA_property_int_set (PointerRNA * ptr, PropertyRNA * prop, int value)
Definition at line 1833 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, IDPropertyTemplate::i, PropertyRNA::identifier, IDP_AddToGroup(), IDP_INT, IDP_Int, IDP_New(), PROP_EDITABLE, PROP_INT, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_array_check(), RNA_property_type(), RNA_struct_idprops(), and IntPropertyRNA::set.
Referenced by animsys_write_rna_setting(), nladata_flush_channels(), pose_slide_apply_props(), pyrna_py_to_prop(), radial_control_set_value(), RNA_int_set(), RNA_property_copy(), RNA_property_int_set_array(), RNA_property_reset(), rna_raw_access(), ui_handle_list_event(), and ui_set_but_val().
void RNA_property_int_set_array (PointerRNA * ptr, PropertyRNA * prop, const int * values)
Definition at line 1946 of file rna_access.c.
References IDPropertyTemplate::array, PropertyRNA::arraydimension, BLI_assert, PropertyRNA::flag, PropertyRNA::identifier, IDP_AddToGroup(), IDP_ARRAY, IDP_Array, IDP_INT, IDP_Int, IDP_New(), IDPropertyTemplate::len, IDProperty::len, PROP_EDITABLE, PROP_INT, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_array_check(), RNA_property_int_set(), RNA_property_type(), RNA_struct_idprops(), IntPropertyRNA::setarray, PropertyRNA::totarraylength, and IDPropertyTemplate::type.
Referenced by prop_subscript_ass_array_slice(), pyrna_py_to_array(), RNA_int_set_array(), RNA_property_copy(), RNA_property_int_set_index(), RNA_property_reset(), and rna_raw_access().
void RNA_property_int_set_index (PointerRNA * ptr, PropertyRNA * prop, int index, int value)
Definition at line 1982 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_INT, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_int_get_array(), RNA_property_int_set_array(), and RNA_property_type().
Referenced by animsys_write_rna_setting(), int_set_index(), nladata_flush_channels(), pyrna_py_to_prop_array_index(), RNA_property_copy(), RNA_property_reset(), and ui_set_but_val().
void RNA_property_int_ui_range (PointerRNA * ptr, PropertyRNA * prop, int * softmin, int * softmax, int * step)
Definition at line 935 of file rna_access.c.
References IDP_GetPropertyTypeFromGroup(), IDP_Int, IDP_INT, PropertyRNA::magic, MAX2, MIN2, IntPropertyRNA::range, rna_ensure_property(), rna_idproperty_ui(), RNA_MAGIC, IntPropertyRNA::softmax, IntPropertyRNA::softmin, and IntPropertyRNA::step.
Referenced by radial_control_invoke(), ui_def_but_rna(), and ui_set_but_soft_range().
int RNA_property_is_idprop (PropertyRNA * prop)
Definition at line 4483 of file rna_access.c.
References PropertyRNA::magic, and RNA_MAGIC.
int RNA_property_is_set (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 4458 of file rna_access.c.
References IDProperty::flag, PropertyRNA::flag, PropertyRNA::identifier, IDP_FLAG_GHOST, NULL, PROP_IDPROPERTY, and rna_idproperty_find().
Referenced by edbm_select_similar_exec(), initTransform(), poselib_remove_exec(), pyrna_struct_is_property_set(), RNA_struct_property_is_set(), saveTransform(), and WM_menu_invoke().
int RNA_property_multi_array_length (PointerRNA * ptr, PropertyRNA * prop, int dim)
Definition at line 820 of file rna_access.c.
References len(), rna_ensure_property_multi_array_length(), and RNA_MAX_ARRAY_DIMENSION.
Referenced by pyrna_prop_array_length(), and pyrna_py_from_array_index().
int RNA_property_path_from_ID_check (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1430 of file rna_access.c.
References PointerRNA::data, FALSE, PointerRNA::id, MEM_freeN(), RNA_id_pointer_create(), RNA_path_from_ID_to_property(), RNA_path_resolve(), and TRUE.
Referenced by ui_but_menu().
void RNA_property_pointer_add (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2576 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, IDPropertyTemplate::i, PropertyRNA::identifier, StructRNA::identifier, IDP_AddToGroup(), IDP_GROUP, IDP_New(), PROP_IDPROPERTY, PROP_POINTER, rna_idproperty_check(), RNA_property_type(), RNA_struct_idprops(), and PointerRNA::type.
Referenced by RNA_pointer_add(), and RNA_property_pointer_get().
PointerRNA RNA_property_pointer_get (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2518 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, PointerPropertyRNA::get, PointerRNA_NULL, PROP_IDPROPERTY, PROP_POINTER, rna_idproperty_check(), rna_pointer_inherit_refine(), RNA_property_pointer_add(), RNA_property_pointer_get(), RNA_property_type(), and PointerPropertyRNA::type.
Referenced by act_new_exec(), buttons_texture_context_compute(), id_search_menu(), node_composit_buts_image(), open_invoke(), pyrna_prop_str(), pyrna_prop_to_py(), pyrna_py_to_prop(), RNA_path_resolve_full(), RNA_pointer_get(), RNA_property_as_string(), RNA_property_copy(), RNA_property_pointer_get(), template_ID(), template_id_cb(), template_keymap_item_properties(), template_texture_select(), ui_get_but_string(), uiDefAutoButR(), uiTemplateColorRamp(), uiTemplateCurveMapping(), uiTemplateHistogram(), uiTemplateImage(), uiTemplateMarker(), uiTemplateMovieClip(), uiTemplateTrack(), uiTemplateVectorscope(), uiTemplateWaveform(), wm_operator_create(), and WM_operator_properties_sanitize().
PointerRNA RNA_property_pointer_get_default (PointerRNA * UNUSEDptr, PropertyRNA * UNUSEDprop)
Definition at line 2567 of file rna_access.c.
References PointerRNA_NULL.
Referenced by RNA_property_reset().
int RNA_property_pointer_poll (PointerRNA * ptr, PropertyRNA * prop, PointerRNA * value)
Definition at line 1125 of file rna_access.c.
References PropertyRNA::identifier, PointerPropertyRNA::poll, PROP_POINTER, rna_ensure_property(), and PropertyRNA::type.
Referenced by id_search_cb(), and rna_search_cb().
void RNA_property_pointer_remove (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2599 of file rna_access.c.
References BLI_assert, StructRNA::identifier, PropertyRNA::identifier, IDP_FreeProperty(), IDP_RemFromGroup(), MEM_freeN(), PROP_POINTER, rna_idproperty_check(), RNA_property_type(), RNA_struct_idprops(), and PointerRNA::type.
void RNA_property_pointer_set (PointerRNA * ptr, PropertyRNA * prop, PointerRNA ptr_value)
Definition at line 2545 of file rna_access.c.
References BLI_assert, PointerRNA::data, PropertyRNA::flag, PointerRNA::id, NULL, PROP_ID_SELF_CHECK, PROP_NEVER_NULL, PROP_POINTER, rna_idproperty_check(), RNA_property_type(), and PointerPropertyRNA::set.
Referenced by act_new_exec(), font_open_exec(), font_unlink_exec(), id_search_call_cb(), id_single_user(), image_new_exec(), image_open_exec(), new_material_exec(), new_node_tree_exec(), new_texture_exec(), new_world_exec(), open_exec(), pyrna_py_to_prop(), RNA_pointer_set(), RNA_property_copy(), RNA_property_reset(), template_id_cb(), text_new_exec(), text_open_exec(), and ui_set_but_string().
StructRNA* RNA_property_pointer_type (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1102 of file rna_access.c.
References CollectionPropertyRNA::item_type, PROP_COLLECTION, PROP_POINTER, rna_ensure_property(), RNA_UnknownType, PointerPropertyRNA::type, PropertyRNA::type, and PointerPropertyRNA::typef.
Referenced by pyrna_param_to_py(), pyrna_prop_collection_type_check(), pyrna_py_to_prop(), pyrna_srna_contains_pointer_prop_srna(), rna_function_parameter_parse(), rna_raw_access(), RNA_struct_find_nested(), search_id_collection(), ui_but_add_search(), ui_template_id(), uiDefAutoButR(), uiItemPointerR(), uiTemplateList(), and WM_operator_properties_sanitize().
void* RNA_property_py_data_get (PropertyRNA * prop)
Definition at line 793 of file rna_access.c.
References PropertyRNA::py_data.
Referenced by bpy_prop_update_cb().
RawPropertyType RNA_property_raw_type (PropertyRNA * prop)
Definition at line 3331 of file rna_access.c.
References PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_RAW_FLOAT, PROP_RAW_INT, PROP_RAW_UNSET, PropertyRNA::rawtype, and PropertyRNA::type.
Referenced by foreach_attr_type().
int RNA_property_reset (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 5516 of file rna_access.c.
References len(), MEM_callocN(), MEM_freeN(), NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_POINTER, PROP_STRING, RNA_property_array_length(), RNA_property_boolean_get_default(), RNA_property_boolean_get_default_array(), RNA_property_boolean_get_default_index(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_boolean_set_index(), RNA_property_enum_get_default(), RNA_property_enum_set(), RNA_property_float_get_default(), RNA_property_float_get_default_array(), RNA_property_float_get_default_index(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_float_set_index(), RNA_property_int_get_default(), RNA_property_int_get_default_array(), RNA_property_int_get_default_index(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_int_set_index(), RNA_property_pointer_get_default(), RNA_property_pointer_set(), RNA_property_string_get_default_alloc(), RNA_property_string_set(), and RNA_property_type().
Referenced by reset_default_button_exec().
int RNA_property_string_default_length (PointerRNA * UNUSEDptr, PropertyRNA * prop)
Definition at line 2450 of file rna_access.c.
References BLI_assert, StringPropertyRNA::defaultvalue, PROP_STRING, RNA_property_type(), and strlen().
Referenced by RNA_property_string_get_default_alloc().
void RNA_property_string_get (PointerRNA * ptr, PropertyRNA * prop, char * value)
Definition at line 2313 of file rna_access.c.
References BLI_assert, StringPropertyRNA::defaultvalue, StringPropertyRNA::get, IDP_String, IDP_STRING_SUB_BYTE, IDProperty::len, PROP_STRING, rna_idproperty_check(), RNA_property_type(), and IDProperty::subtype.
Referenced by file_operator_to_sfile(), RNA_property_as_string(), RNA_property_string_get_alloc(), RNA_string_get(), and WM_operator_filesel_ensure_ext_imtype().
char* RNA_property_string_get_alloc (PointerRNA * ptr, PropertyRNA * prop, char * fixedbuf, int fixedlen, int * r_len)
Definition at line 2339 of file rna_access.c.
References BLI_assert, length(), MEM_mallocN(), PROP_STRING, RNA_property_string_get(), RNA_property_string_length(), and RNA_property_type().
Referenced by file_browse_invoke(), getname_anim_fcurve(), list_item_row(), pyrna_prop_to_py(), RNA_property_collection_lookup_string(), RNA_property_copy(), RNA_string_get_alloc(), RNA_struct_name_get_alloc(), and ui_get_but_string().
void RNA_property_string_get_default (PointerRNA * UNUSEDptr, PropertyRNA * prop, char * value)
Definition at line 2421 of file rna_access.c.
References BLI_assert, StringPropertyRNA::defaultvalue, PROP_STRING, and RNA_property_type().
Referenced by RNA_property_string_get_default_alloc().
char* RNA_property_string_get_default_alloc (PointerRNA * ptr, PropertyRNA * prop, char * fixedbuf, int fixedlen)
Definition at line 2430 of file rna_access.c.
References BLI_assert, length(), MEM_callocN(), PROP_STRING, RNA_property_string_default_length(), RNA_property_string_get_default(), and RNA_property_type().
Referenced by RNA_property_reset().
int RNA_property_string_length (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2373 of file rna_access.c.
References BLI_assert, StringPropertyRNA::defaultvalue, IDP_String, IDP_STRING_SUB_BYTE, IDProperty::len, StringPropertyRNA::length, PROP_STRING, rna_idproperty_check(), RNA_property_type(), strlen(), and IDProperty::subtype.
Referenced by RNA_property_as_string(), RNA_property_string_get_alloc(), and RNA_string_length().
int RNA_property_string_maxlength (PropertyRNA * prop)
Definition at line 1096 of file rna_access.c.
References StringPropertyRNA::maxlength, and rna_ensure_property().
Referenced by RNA_property_string_set(), and ui_def_but_rna().
void RNA_property_string_set (PointerRNA * ptr, PropertyRNA * prop, const char * value)
Definition at line 2398 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, PropertyRNA::identifier, IDP_AddToGroup(), IDP_AssignString(), IDP_NewString(), PROP_EDITABLE, PROP_STRING, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_string_maxlength(), RNA_property_type(), RNA_struct_idprops(), and StringPropertyRNA::set.
Referenced by file_browse_exec(), pyrna_py_to_prop(), RNA_property_copy(), RNA_property_reset(), RNA_string_set(), sequencer_change_path_exec(), ui_set_but_string(), and WM_operator_filesel_ensure_ext_imtype().
PropertySubType RNA_property_subtype (PropertyRNA * prop)
Definition at line 778 of file rna_access.c.
References rna_ensure_property(), and PropertyRNA::subtype.
Referenced by ANIM_unit_mapping_get_factor(), eyedropper_sample(), file_browse_exec(), foreach_attr_type(), graph_panel_key_properties(), insert_keyframe(), pyrna_math_object_from_array(), pyrna_param_to_py(), pyrna_prop_to_py(), pyrna_py_to_prop(), radial_control_invoke(), ui_block_func_COL(), ui_check_but(), ui_draw_but_HSV_v(), ui_draw_but_HSVCIRCLE(), ui_handle_menu_event(), ui_is_but_utf8(), ui_item_array(), ui_item_rna_size(), ui_item_with_label(), ui_ndofedit_but_HSVCUBE(), ui_numedit_but_HSVCUBE(), uiButGetUnitType(), uiDefAutoButR(), and widget_swatch().
PropertyType RNA_property_type (PropertyRNA * prop)
Definition at line 773 of file rna_access.c.
References rna_ensure_property(), and PropertyRNA::type.
Referenced by ANIM_add_driver(), animsys_write_rna_setting(), dtar_get_prop_val(), eyedropper_sample(), foreach_parse_args(), id_search_cb(), insert_keyframe_direct(), list_item_row(), nladata_flush_channels(), node_composit_buts_image(), operator_enum_search_cb(), outliner_draw_rnabuts(), pose_propagate_get_refVal(), pose_slide_apply_props(), prop_subscript_ass_array_slice(), pyrna_array_contains_py(), pyrna_array_index(), pyrna_dir_members_py(), pyrna_math_object_from_array(), pyrna_param_to_py(), pyrna_prop_array_subscript_slice(), pyrna_prop_CreatePyObject(), pyrna_prop_dir(), pyrna_prop_str(), pyrna_prop_to_py(), pyrna_py_to_array(), pyrna_py_to_array_index(), pyrna_py_to_prop(), pyrna_py_to_prop_array_index(), pyrna_srna_contains_pointer_prop_srna(), radial_control_get_path(), radial_control_invoke(), RNA_function_call_direct_va(), RNA_path_append(), RNA_path_resolve_full(), RNA_pointer_as_string_keywords_ex(), RNA_property_as_string(), RNA_property_boolean_get(), RNA_property_boolean_get_array(), RNA_property_boolean_get_default(), RNA_property_boolean_get_default_array(), RNA_property_boolean_get_default_index(), RNA_property_boolean_get_index(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_boolean_set_index(), RNA_property_collection_add(), RNA_property_collection_assign_int(), RNA_property_collection_begin(), RNA_property_collection_clear(), RNA_property_collection_length(), RNA_property_collection_lookup_index(), RNA_property_collection_lookup_int(), RNA_property_collection_lookup_string(), RNA_property_collection_move(), RNA_property_collection_raw_array(), RNA_property_collection_remove(), RNA_property_collection_type_get(), RNA_property_copy(), RNA_property_enum_get(), RNA_property_enum_get_default(), RNA_property_enum_py_data_get(), RNA_property_enum_set(), RNA_property_float_get(), RNA_property_float_get_array(), RNA_property_float_get_default(), RNA_property_float_get_default_array(), RNA_property_float_get_default_index(), RNA_property_float_get_index(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_float_set_index(), RNA_property_int_get(), RNA_property_int_get_array(), RNA_property_int_get_default_array(), RNA_property_int_get_index(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_int_set_index(), RNA_property_pointer_add(), RNA_property_pointer_get(), RNA_property_pointer_remove(), RNA_property_pointer_set(), RNA_property_reset(), RNA_property_string_default_length(), RNA_property_string_get(), RNA_property_string_get_alloc(), RNA_property_string_get_default(), RNA_property_string_get_default_alloc(), RNA_property_string_length(), RNA_property_string_set(), rna_raw_access(), rna_search_cb(), search_id_collection(), setting_get_rna_value(), template_keymap_item_properties(), tree_element_to_path(), ui_but_add_search(), ui_but_search_test(), ui_def_but_rna(), ui_get_but_string(), ui_get_but_val(), ui_get_but_vectorf(), ui_is_but_float(), ui_item_array(), ui_item_rna_size(), ui_item_with_label(), ui_popup_menu_create(), ui_set_but_soft_range(), ui_set_but_string(), ui_set_but_val(), ui_set_but_vectorf(), ui_template_id(), ui_tooltip_create(), uiDefAutoButR(), uiDefAutoButsRNA(), uiFileBrowseContextProperty(), uiItemEnumR(), uiItemEnumR_string(), uiItemFullR(), uiItemPointerR(), uiItemsEnumR(), uiItemsFullEnumO(), uiTemplateAnyID(), uiTemplateColorRamp(), uiTemplateCurveMapping(), uiTemplateHistogram(), uiTemplateImage(), uiTemplateList(), uiTemplateMarker(), uiTemplateMovieClip(), uiTemplatePathBuilder(), uiTemplateTrack(), uiTemplateVectorscope(), uiTemplateWaveform(), validate_array(), WM_menu_invoke(), and WM_operator_properties_sanitize().
const char* RNA_property_ui_description (PropertyRNA * prop)
Definition at line 1356 of file rna_access.c.
References rna_ensure_property_description().
Referenced by ui_def_but_rna().
int RNA_property_ui_icon (PropertyRNA * prop)
Definition at line 1361 of file rna_access.c.
References PropertyRNA::icon, and rna_ensure_property().
Referenced by ui_def_but_rna(), and uiItemFullR().
const char* RNA_property_ui_name (PropertyRNA * prop)
Definition at line 1351 of file rna_access.c.
References rna_ensure_property_name().
Referenced by getname_anim_fcurve(), template_keymap_item_properties(), ui_but_menu(), ui_def_but_rna(), uiDefAutoButsRNA(), uiItemFullR(), uiItemMenuEnumR(), and uiItemPointerR().
PropertyUnit RNA_property_unit (PropertyRNA * prop)
Definition at line 783 of file rna_access.c.
References rna_ensure_property(), and RNA_SUBTYPE_UNIT.
static void rna_property_update (bContext * C, Main * bmain, Scene * scene, PointerRNA * ptr, PropertyRNA * prop) [static]
Definition at line 1454 of file rna_access.c.
References C, DAG_id_tag_update(), PointerRNA::data, PropertyRNA::flag, PointerRNA::id, PropertyRNA::magic, NC_WINDOW, PropertyRNA::noteflag, NULL, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, PROP_CONTEXT_PROPERTY_UPDATE, PROP_CONTEXT_UPDATE, PROP_IDPROPERTY, rna_ensure_property(), RNA_MAGIC, PropertyRNA::update, and WM_main_add_notifier().
Referenced by RNA_property_update(), and RNA_property_update_main().
void RNA_property_update (bContext * C, PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1496 of file rna_access.c.
References CTX_data_main(), CTX_data_scene(), and rna_property_update().
Referenced by act_new_exec(), copy_to_selected_button_exec(), eyedropper_sample(), file_browse_exec(), font_open_exec(), font_unlink_exec(), id_search_call_cb(), id_single_user(), image_new_exec(), image_open_exec(), mathutils_rna_matrix_set(), mathutils_rna_vector_set(), mathutils_rna_vector_set_index(), new_material_exec(), new_node_tree_exec(), new_texture_exec(), new_world_exec(), open_exec(), pyrna_prop_array_ass_subscript(), pyrna_py_to_prop(), pyrna_py_to_prop_array_index(), reset_default_button_exec(), rna_update_cb(), sequencer_change_path_exec(), template_id_cb(), text_new_exec(), text_open_exec(), ui_apply_but_funcs_after(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_handle_list_event(), and ui_layer_but_cb().
void RNA_property_update_cache_add (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1534 of file rna_access.c.
References BLI_addtail(), BLI_genericNodeN(), LinkData::data, PointerRNA::data, ELEM, ListBase::first, PropertyRNA::flag, PointerRNA::id, tRnaUpdateCacheElem::L2Funcs, PropertyRNA::magic, MEM_callocN(), LinkData::next, tRnaUpdateCacheElem::next, NULL, PROP_CONTEXT_UPDATE, tRnaUpdateCacheElem::ptr, rna_ensure_property(), RNA_MAGIC, RNA_pointer_create(), PointerRNA::type, and PropertyRNA::update.
Referenced by animsys_write_rna_setting().
void RNA_property_update_cache_flush (Main * bmain, Scene * scene)
Definition at line 1579 of file rna_access.c.
References LinkData::data, ListBase::first, tRnaUpdateCacheElem::L2Funcs, LinkData::next, tRnaUpdateCacheElem::next, and tRnaUpdateCacheElem::ptr.
Referenced by BKE_animsys_evaluate_animdata().
void RNA_property_update_cache_free (void)
Definition at line 1596 of file rna_access.c.
References BLI_freelinkN(), BLI_freelistN(), ListBase::first, tRnaUpdateCacheElem::L2Funcs, and tRnaUpdateCacheElem::next.
Referenced by BKE_animsys_evaluate_animdata(), RNA_exit(), and setup_app_data().
int RNA_property_update_check (PropertyRNA * prop)
Definition at line 1491 of file rna_access.c.
References PropertyRNA::magic, PropertyRNA::noteflag, RNA_MAGIC, and PropertyRNA::update.
Referenced by animsys_write_rna_setting(), mathutils_rna_matrix_set(), mathutils_rna_vector_set(), mathutils_rna_vector_set_index(), pyrna_prop_array_ass_subscript(), pyrna_py_to_prop(), and pyrna_py_to_prop_array_index().
void RNA_property_update_main (Main * bmain, Scene * scene, PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1501 of file rna_access.c.
References NULL, and rna_property_update().
Referenced by ANIM_list_elem_update().
static int rna_raw_access (ReportList * reports, PointerRNA * ptr, PropertyRNA * prop, const char * propname, void * inarray, RawPropertyType intype, int inlen, int set) [static]
Definition at line 3047 of file rna_access.c.
References RawArray::array, BKE_report(), BKE_reportf(), PointerRNA::data, ELEM3, err, i, RawArray::len, MEM_callocN(), MEM_freeN(), NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, PROP_RAW_FLOAT, PROP_RAW_INT, RAW_GET, RAW_SET, RNA_pointer_create(), RNA_PROP_BEGIN, RNA_PROP_END, RNA_property_array_length(), RNA_property_boolean_get(), RNA_property_boolean_get_array(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_collection_raw_array(), RNA_property_editable(), RNA_property_float_get(), RNA_property_float_get_array(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_int_get(), RNA_property_int_get_array(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_pointer_type(), RNA_property_type(), RNA_raw_type_sizeof(), RNA_struct_find_property(), RPT_ERROR, size(), RawArray::stride, and RawArray::type.
Referenced by RNA_property_collection_raw_get(), and RNA_property_collection_raw_set().
int RNA_raw_type_sizeof (RawPropertyType type)
Definition at line 3035 of file rna_access.c.
References PROP_RAW_CHAR, PROP_RAW_DOUBLE, PROP_RAW_FLOAT, PROP_RAW_INT, and PROP_RAW_SHORT.
Referenced by foreach_parse_args(), and rna_raw_access().
void RNA_string_get (PointerRNA * ptr, const char * name, char * value)
Definition at line 4330 of file rna_access.c.
References StructRNA::identifier, RNA_property_string_get(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by actuator_add_exec(), add_named_exec(), armature_bone_primitive_add_exec(), background_image_add_invoke(), blend_save_check(), bookmark_select_exec(), controller_add_exec(), create_orientation_exec(), drop_named_image_invoke(), drop_named_material_invoke(), ED_fileselect_set_params(), ed_marker_rename_exec(), ed_undo_push_exec(), edit_actuator_property_get(), edit_constraint_property_get(), edit_controller_property_get(), edit_modifier_property_get(), edit_object_property_get(), edit_sensor_property_get(), envmap_save_exec(), file_directory_new_exec(), font_open_exec(), game_property_new(), group_create_exec(), image_new_exec(), image_open_exec(), image_replace_exec(), image_unpack_exec(), multires_external_save_exec(), new_node_tree_exec(), node_add_file_exec(), node_composit_buts_renderlayers(), node_group_socket_add_exec(), node_output_file_add_socket_exec(), object_select_same_group_exec(), open_exec(), parent_clear_invoke(), parent_drop_exec(), parent_drop_invoke(), poselib_add_exec(), poselib_rename_exec(), run_pyfile_exec(), save_image_options_from_op(), screen_render_scene_layer_set(), screenshot_exec(), sensor_add_exec(), seq_load_operator_info(), sequencer_add_effect_strip_exec(), sequencer_add_generic_strip_exec(), sequencer_change_path_exec(), sound_mixdown_exec(), sound_unpack_exec(), text_open_exec(), text_save_as_exec(), texture_paint_image_from_view_exec(), wm_call_menu_exec(), wm_link_append_exec(), wm_open_mainfile_exec(), wm_recover_auto_save_exec(), and wm_save_as_mainfile_exec().
char* RNA_string_get_alloc (PointerRNA * ptr, const char * name, char * fixedbuf, int fixedlen)
Definition at line 4343 of file rna_access.c.
References StructRNA::identifier, NULL, RNA_property_string_get_alloc(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by console_history_append_exec(), console_insert_exec(), console_scrollback_append_exec(), file_browse_exec(), find_missing_files_exec(), insert_text_exec(), paste_file_exec(), radial_control_get_path(), seq_load_operator_info(), sequencer_add_image_strip_exec(), sequencer_change_path_exec(), text_insert_exec(), and wm_handler_fileselect_call().
int RNA_string_length (PointerRNA * ptr, const char * name)
Definition at line 4356 of file rna_access.c.
References StructRNA::identifier, RNA_property_string_length(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by console_insert_invoke(), and text_insert_invoke().
void RNA_string_set (PointerRNA * ptr, const char * name, const char * value)
Definition at line 4369 of file rna_access.c.
References StructRNA::identifier, RNA_property_string_set(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by blend_save_check(), clip_filesel(), clip_keymap(), console_insert_invoke(), console_keymap(), ED_keymap_anim(), ED_keymap_paint(), ed_keymap_paint_brush_switch(), ED_keymap_uvedit(), ed_marker_rename_invoke_wrapper(), ED_object_generic_keymap(), edit_actuator_invoke_properties(), edit_constraint_invoke_properties(), edit_controller_invoke_properties(), edit_modifier_invoke_properties(), edit_sensor_invoke_properties(), envmap_save_invoke(), file_browse_invoke(), file_panel_cb(), file_sfile_to_operator(), ghost_event_proc(), graphedit_keymap_keyframes(), id_drop_copy(), image_drop_copy(), image_filesel(), image_keymap(), insert_text_invoke(), keymap_particle(), multires_external_save_invoke(), node_composit_buts_renderlayers(), node_id_path_drop_copy(), node_render_changed_exec(), open_file_drop_copy(), open_invoke(), outliner_parent_clear_copy(), outliner_parent_drop_copy(), parent_drop_invoke(), path_drop_copy(), poselib_add_menu_invoke__replacemenu(), poselib_rename_invoke(), save_image_options_to_op(), screenshot_invoke(), script_keymap(), sequencer_change_path_invoke(), sequencer_drop_copy(), sequencer_generic_invoke_path__internal(), sequencer_keymap(), set_brush_rc_path(), set_brush_rc_props(), text_drop_copy(), text_insert_invoke(), text_keymap(), text_open_invoke(), text_save_as_invoke(), transform_keymap_for_space(), ui_but_menu(), uiItemStringO(), uiLayoutOperatorButs(), unpack_menu(), view3d_id_drop_copy(), view3d_id_path_drop_copy(), view3d_keymap(), view3d_ob_drop_copy(), WM_keymap_add_menu(), wm_link_append_invoke(), wm_open_mainfile_invoke(), wm_recover_auto_save_invoke(), wm_save_as_mainfile_invoke(), wm_save_mainfile_invoke(), and wm_window_keymap().
StructRNA* RNA_struct_base (StructRNA * type)
Definition at line 538 of file rna_access.c.
References StructRNA::base.
Referenced by pyrna_basetype_dir(), and pyrna_srna_PyBase().
void* RNA_struct_blender_type_get (StructRNA * srna)
Definition at line 741 of file rna_access.c.
References StructRNA::blender_type.
void RNA_struct_blender_type_set (StructRNA * srna, void * blender_type)
Definition at line 746 of file rna_access.c.
References StructRNA::blender_type.
Referenced by operator_properties_init(), and RNA_struct_free_extension().
int RNA_struct_contains_property (PointerRNA * ptr, PropertyRNA * prop_test)
Definition at line 630 of file rna_access.c.
References FALSE, RNA_PROP_BEGIN, RNA_PROP_END, RNA_struct_iterator_property(), TRUE, and PointerRNA::type.
Referenced by ui_is_but_rna_valid().
StructRNA* RNA_struct_find (const char * identifier)
Definition at line 494 of file rna_access.c.
References BLENDER_RNA, StructRNA::cont, ListBase::first, StructRNA::identifier, ContainerRNA::next, NULL, and BlenderRNA::structs.
FunctionRNA* RNA_struct_find_function (PointerRNA * ptr, const char * identifier)
Definition at line 663 of file rna_access.c.
References StructRNA::base, BLI_findstring_ptr(), StructRNA::functions, NULL, RNA_function_identifier(), RNA_pointer_create(), RNA_PROP_BEGIN, RNA_PROP_END, RNA_Struct, RNA_struct_find_property(), and PointerRNA::type.
Referenced by pyrna_prop_collection_getattro(), pyrna_struct_getattro(), RNA_function_call_direct_lookup(), RNA_function_call_direct_va_lookup(), and RNA_function_call_lookup().
PropertyRNA* RNA_struct_find_nested (PointerRNA * ptr, StructRNA * srna)
Definition at line 614 of file rna_access.c.
References NULL, RNA_PROP_END, RNA_property_pointer_type(), and RNA_STRUCT_BEGIN.
Referenced by RNA_path_from_ID_to_struct().
PropertyRNA* RNA_struct_find_property (PointerRNA * ptr, const char * identifier)
Definition at line 591 of file rna_access.c.
References PointerRNA::data, NULL, RNA_path_resolve(), RNA_property_collection_lookup_string(), RNA_struct_iterator_property(), and PointerRNA::type.
Referenced by actuator_add_exec(), bookmark_delete_exec(), bookmark_select_exec(), border_apply(), BPY_rna_types(), buttons_texture_modifier_foreach(), buttons_texture_users_from_context(), controller_add_exec(), draw_actuator_armature(), draw_sensor_armature(), ED_fileselect_set_params(), ED_object_add_generic_get_opts(), edbm_select_similar_exec(), DocumentExporter::exportCurrentScene(), file_browse_exec(), file_browse_invoke(), file_directory_new_exec(), file_draw_check_exists(), file_operator_to_sfile(), file_sfile_to_operator(), DocumentImporter::finish(), foreach_attr_type(), get_enum_identifier(), BlenderSync::get_session_params(), id_data_find_fcurve(), image_sample_apply(), initSnapping(), initTransform(), initTransInfo(), key_get_curValue_rnaPath(), list_item_row(), node_animation_properties(), node_buts_rgb(), node_buts_value(), node_composit_buts_image(), node_composit_buts_renderlayers(), node_socket_button_output_file(), object_add_generic_invoke_options(), operator_wrapper(), pose_slide_apply_props(), poselib_remove_exec(), pyrna_alloc_types(), pyrna_dir_members_rna(), pyrna_free_types(), pyrna_prop_collection_getattro(), pyrna_prop_collection_setattro(), pyrna_pydict_to_props(), pyrna_rotation_euler_order_get(), pyrna_struct_anim_args_parse(), pyrna_struct_getattro(), pyrna_struct_is_property_hidden(), pyrna_struct_is_property_set(), pyrna_struct_path_from_id(), pyrna_struct_setattro(), pyrna_unregister_class(), RNA_boolean_get(), RNA_boolean_get_array(), RNA_boolean_set(), RNA_boolean_set_array(), RNA_collection_add(), RNA_collection_begin(), RNA_collection_clear(), RNA_collection_length(), RNA_enum_get(), RNA_enum_is_equal(), RNA_enum_set(), RNA_enum_set_identifier(), RNA_float_get(), RNA_float_get_array(), RNA_float_set(), RNA_float_set_array(), RNA_function_as_string_keywords(), rna_idp_path(), RNA_int_get(), RNA_int_get_array(), RNA_int_set(), RNA_int_set_array(), RNA_path_resolve_full(), RNA_pointer_add(), RNA_pointer_as_string_keywords_ex(), RNA_pointer_get(), RNA_pointer_set(), rna_raw_access(), RNA_string_get(), RNA_string_get_alloc(), RNA_string_length(), RNA_string_set(), RNA_struct_find_function(), RNA_struct_property_is_set(), save_envmap(), save_image_doit(), saveTransform(), sensor_add_exec(), seq_load_operator_info(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_change_path_exec(), sequencer_drop_copy(), sequencer_generic_invoke_path__internal(), ui_def_but_rna_propname(), ui_template_id(), uiItemEnumO_ptr(), uiItemEnumO_string(), uiItemEnumO_value(), uiItemEnumR(), uiItemEnumR_string(), uiItemMenuEnumR(), uiItemPointerR(), uiItemR(), uiItemsEnumR(), uiItemsFullEnumO(), uiTemplateAnyID(), uiTemplateColorRamp(), uiTemplateColorWheel(), uiTemplateCurveMapping(), uiTemplateHistogram(), uiTemplateImage(), uiTemplateLayers(), uiTemplateList(), uiTemplateMarker(), uiTemplateMovieClip(), uiTemplatePathBuilder(), uiTemplateTrack(), uiTemplateVectorscope(), uiTemplateWaveform(), uv_map_transform(), WM_gesture_circle_modal(), wm_gesture_end(), WM_gesture_lasso_invoke(), WM_gesture_lines_invoke(), WM_gesture_straightline_invoke(), wm_handler_fileselect_call(), wm_link_append_exec(), WM_operator_filesel_ensure_ext_imtype(), wm_save_as_mainfile_exec(), and wm_save_mainfile_invoke().
const char* RNA_struct_identifier (StructRNA * type)
Definition at line 505 of file rna_access.c.
References StructRNA::identifier.
Referenced by bpy_class_call(), bpy_class_validate(), deferred_register_prop(), mathutils_rna_matrix_set(), mathutils_rna_vector_set(), mathutils_rna_vector_set_index(), py_to_array_index(), PYOP_wrap_macro_define(), pyrna_basetype_dir(), pyrna_enum_to_py(), pyrna_func_call(), pyrna_func_doc_get(), pyrna_func_repr(), pyrna_prop_array_ass_subscript(), pyrna_prop_collection_subscript_str_lib_pair_ptr(), pyrna_prop_collection_type_check(), pyrna_prop_path_from_id(), pyrna_prop_str(), pyrna_prop_to_enum_bitfield(), pyrna_py_to_prop(), pyrna_register_class(), pyrna_srna_ExternalType(), pyrna_srna_Subtype(), pyrna_struct_is_property_hidden(), pyrna_struct_is_property_set(), pyrna_struct_path_from_id(), pyrna_struct_path_resolve(), pyrna_struct_repr(), pyrna_struct_setattro(), pyrna_struct_str(), pyrna_unregister_class(), RNA_function_call_direct_va(), rna_function_parameter_parse(), rna_id_write_error(), ui_but_menu(), ui_intro_button(), ui_template_id(), ui_tooltip_create(), uiItemEnumO_ptr(), uiItemEnumO_string(), uiItemEnumO_value(), uiItemEnumR(), uiItemEnumR_string(), uiItemMenuEnumR(), uiItemPointerR(), uiItemR(), uiItemsEnumR(), uiTemplateAnyID(), uiTemplateColorWheel(), uiTemplateCurveMapping(), uiTemplateImage(), uiTemplateLayers(), uiTemplateList(), uiTemplateMarker(), uiTemplateMovieClip(), uiTemplatePathBuilder(), uiTemplateTrack(), validate_array(), and validate_array_length().
IDProperty* RNA_struct_idprops (PointerRNA * ptr, int create) [read]
Definition at line 259 of file rna_access.c.
References StructRNA::idproperties, NULL, and PointerRNA::type.
Referenced by pyrna_struct_ass_subscript(), pyrna_struct_contains(), pyrna_struct_get(), pyrna_struct_items(), pyrna_struct_keys(), pyrna_struct_subscript(), pyrna_struct_values(), rna_idproperty_check(), rna_idproperty_find(), rna_path_from_ID_to_idpgroup(), RNA_path_resolve_full(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_collection_add(), RNA_property_enum_set(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_pointer_add(), RNA_property_pointer_remove(), RNA_property_string_set(), and RNA_struct_idprops_unset().
int RNA_struct_idprops_check (StructRNA * srna)
Definition at line 269 of file rna_access.c.
References StructRNA::idproperties.
Referenced by pyrna_srna_Subtype(), pyrna_struct_contains(), pyrna_struct_get(), pyrna_struct_getattro(), pyrna_struct_items(), pyrna_struct_keys(), pyrna_struct_subscript(), and pyrna_struct_values().
int RNA_struct_idprops_register_check (StructRNA * type)
Definition at line 553 of file rna_access.c.
References StructRNA::flag, and STRUCT_NO_IDPROPERTIES.
Referenced by pyrna_deferred_register_class().
int RNA_struct_idprops_unset (PointerRNA * ptr, const char * identifier)
Definition at line 559 of file rna_access.c.
References IDP_FreeProperty(), IDP_GetPropertyFromGroup(), IDP_RemFromGroup(), MEM_freeN(), and RNA_struct_idprops().
Referenced by ED_operatormacros_clip(), ED_operatormacros_mesh(), view_align_update(), and WM_operator_properties_reset().
void** RNA_struct_instance (PointerRNA * ptr)
Definition at line 719 of file rna_access.c.
References StructRNA::base, StructRNA::instance, NULL, and PointerRNA::type.
Referenced by bpy_class_call(), and pyrna_struct_as_instance().
int RNA_struct_is_a (StructRNA * type, StructRNA * srna)
Definition at line 576 of file rna_access.c.
References StructRNA::base.
Referenced by bpy_class_call(), buttons_context_path_brush(), buttons_context_path_data(), buttons_context_path_material(), buttons_context_path_object(), buttons_context_path_particle(), buttons_context_path_pose_bone(), buttons_context_path_scene(), buttons_context_path_texture(), buttons_context_path_world(), buttons_texture_context_compute(), copy_to_selected_list(), CTX_data_pointer_get_type(), get_pointer_type(), list_item_icon_get(), list_item_row(), pointer_type_from_py(), pyrna_callback_add(), pyrna_callback_remove(), pyrna_prop_collection_type_check(), pyrna_py_to_prop(), rna_function_parameter_parse(), RNA_path_from_ID_to_struct(), set_pointer_type(), template_keymap_item_properties(), template_texture_select(), ui_item_with_label(), uiTemplateColorRamp(), uiTemplateConstraint(), uiTemplateCurveMapping(), uiTemplateHistogram(), uiTemplateModifier(), uiTemplateVectorscope(), uiTemplateWaveform(), and WM_operator_properties_sanitize().
int RNA_struct_is_ID (StructRNA * type)
Definition at line 543 of file rna_access.c.
References StructRNA::flag, and STRUCT_ID.
Referenced by list_item_icon_get(), pyrna_param_to_py(), pyrna_struct_anim_args_parse(), pyrna_struct_repr(), radial_control_get_properties(), RNA_path_from_ID_to_struct(), RNA_pointer_recast(), rna_search_cb(), tree_element_to_path(), tselem_draw_icon(), and uiItemLDrag().
PropertyRNA* RNA_struct_iterator_property (StructRNA * type)
Definition at line 533 of file rna_access.c.
References StructRNA::iteratorproperty.
Referenced by pyrna_dir_members_rna(), RNA_function_as_string_keywords(), RNA_pointer_as_string_keywords(), RNA_struct_contains_property(), RNA_struct_find_property(), and WM_operator_properties_reset().
char* RNA_struct_name_get_alloc (PointerRNA * ptr, char * fixedbuf, int fixedlen, int * r_len)
Definition at line 751 of file rna_access.c.
References PointerRNA::data, NULL, RNA_property_string_get_alloc(), RNA_struct_name_property(), and PointerRNA::type.
Referenced by buttons_context_draw(), list_item_row(), pyrna_dir_members_rna(), pyrna_enum_to_py(), pyrna_prop_collection_find(), pyrna_prop_collection_items(), pyrna_prop_collection_keys(), pyrna_prop_str(), pyrna_struct_str(), rna_search_cb(), tree_element_to_path(), ui_get_but_string(), and uiTemplateList().
PropertyRNA* RNA_struct_name_property (StructRNA * type)
Definition at line 528 of file rna_access.c.
References StructRNA::nameproperty.
Referenced by acf_generic_idblock_nameprop(), acf_generic_idfill_nameprop(), acf_gpl_name_prop(), acf_group_name_prop(), acf_shapekey_nameprop(), getname_anim_fcurve(), and RNA_struct_name_get_alloc().
int RNA_struct_property_is_set (PointerRNA * ptr, const char * identifier)
Definition at line 4469 of file rna_access.c.
References RNA_property_is_set(), and RNA_struct_find_property().
Referenced by add_vertex_invoke(), area_split_invoke(), background_image_add_invoke(), clean_tracks_invoke(), drop_named_image_invoke(), ED_fileselect_set_params(), ED_object_add_generic_get_opts(), edit_actuator_invoke_properties(), edit_constraint_invoke_properties(), edit_controller_invoke_properties(), edit_modifier_invoke_properties(), edit_sensor_invoke_properties(), envmap_save_invoke(), file_browse_exec(), file_browse_invoke(), image_open_invoke(), image_replace_invoke(), image_save_as_invoke(), image_unpack_exec(), image_unpack_invoke(), initSnapping(), initTransInfo(), insert_text_exec(), insert_text_invoke(), linked_limit_default(), move_to_layer_init(), multires_external_save_invoke(), new_node_tree_exec(), node_add_file_exec(), node_add_file_invoke(), node_group_socket_add_exec(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_socket_remove_exec(), object_add_generic_invoke_options(), object_origin_set_exec(), open_invoke(), open_set_load_ui(), open_set_use_scripts(), pack_islands_exec(), paste_file_invoke(), save_image_options_from_op(), save_set_compress(), screen_animation_play_exec(), screen_render_invoke(), screen_render_scene_layer_set(), screenshot_invoke(), sequencer_add_effect_strip_exec(), sequencer_add_effect_strip_invoke(), sequencer_add_image_strip_invoke(), sequencer_add_movie_strip_invoke(), sequencer_add_movieclip_strip_invoke(), sequencer_add_scene_strip_invoke(), sequencer_add_sound_strip_invoke(), sequencer_generic_invoke_xy__internal(), set_scale_invoke(), set_solution_scale_invoke(), sound_mixdown_invoke(), sound_open_invoke(), sound_unpack_exec(), sound_unpack_invoke(), stitch_init(), text_open_invoke(), text_save_as_invoke(), text_scroll_bar_invoke(), text_scroll_invoke(), transform_invoke(), undo_history_exec(), viewdolly_invoke(), viewzoom_exec(), viewzoom_invoke(), wm_link_append_invoke(), WM_operator_filesel(), and wm_save_as_mainfile_exec().
void* RNA_struct_py_type_get (StructRNA * srna)
Definition at line 731 of file rna_access.c.
References StructRNA::py_type.
Referenced by bpy_class_call(), bpy_class_validate(), pyrna_free_types(), pyrna_register_class(), pyrna_srna_Subtype(), and pyrna_subtype_set_rna().
void RNA_struct_py_type_set (StructRNA * srna, void * py_type)
Definition at line 736 of file rna_access.c.
References StructRNA::py_type.
Referenced by pyrna_free_types(), pyrna_register_class(), pyrna_subtype_set_rna(), and RNA_struct_free_extension().
StructRegisterFunc RNA_struct_register (StructRNA * type)
Definition at line 704 of file rna_access.c.
References StructRNA::reg.
Referenced by pyrna_register_class().
PropertyRNA* RNA_struct_type_find_property (StructRNA * srna, const char * identifier)
Definition at line 658 of file rna_access.c.
References BLI_findstring_ptr(), StructRNA::cont, and ContainerRNA::properties.
Referenced by OBJECT_OT_camera_add(), and pyrna_struct_meta_idprop_setattro().
struct ListBase* RNA_struct_type_functions (StructRNA * srna) [read]
Definition at line 699 of file rna_access.c.
References StructRNA::functions.
Referenced by bpy_class_validate().
struct ListBase* RNA_struct_type_properties (StructRNA * srna) [read]
Definition at line 653 of file rna_access.c.
References StructRNA::cont, and ContainerRNA::properties.
Referenced by bpy_class_validate(), node_animation_properties(), and pyrna_srna_contains_pointer_prop_srna().
const char* RNA_struct_ui_description (StructRNA * type)
Definition at line 523 of file rna_access.c.
References StructRNA::description, and TIP_.
Referenced by ui_def_but_operator_ptr(), and uiItemMenuEnumO().
int RNA_struct_ui_icon (StructRNA * type)
Definition at line 515 of file rna_access.c.
References StructRNA::icon.
Referenced by buttons_context_compute(), buttons_context_draw(), buttons_texture_modifier_foreach(), buttons_texture_users_find_nodetree(), buttons_texture_users_from_context(), draw_modifier(), getname_anim_fcurve(), template_ID(), tselem_draw_icon(), uiDefAutoButR(), uiIconFromID(), uiItemPointerR(), and uiTemplateList().
const char* RNA_struct_ui_name (StructRNA * type)
Definition at line 510 of file rna_access.c.
References CTX_IFACE_, StructRNA::name, and StructRNA::translation_context.
Referenced by dropbox_active(), ED_fileselect_set_params(), getname_anim_fcurve(), ui_def_but_operator_ptr(), uiItemFullO_ptr(), uiItemMenuEnumO(), uiLayoutOperatorButs(), undo_history_invoke(), wm_block_create_redo(), wm_enum_search_menu(), and WM_menu_invoke().
int RNA_struct_undo_check (StructRNA * type)
Definition at line 548 of file rna_access.c.
References StructRNA::flag, and STRUCT_UNDO.
Referenced by ui_but_is_rna_undo().
StructUnregisterFunc RNA_struct_unregister (StructRNA * type)
Definition at line 709 of file rna_access.c.
References StructRNA::base, NULL, and StructRNA::unreg.
Referenced by pyrna_unregister_class().
static int rna_token_strip_quotes (char * token) [static]
Definition at line 3583 of file rna_access.c.
References len(), and strlen().
Referenced by RNA_path_resolve_full().
Variable Documentation
PropertyRNA* arraytypemap[IDP_NUMTYPES] [static]
Initial value:
    {NULL, (PropertyRNA*)&rna_PropertyGroupItem_int_array,
     (PropertyRNA*)&rna_PropertyGroupItem_float_array,
     NULL, NULL, NULL,
     (PropertyRNA*)&rna_PropertyGroupItem_collection, NULL,
     (PropertyRNA*)&rna_PropertyGroupItem_double_array}
Definition at line 385 of file rna_access.c.
EnumPropertyItem DummyRNA_DEFAULT_items[]
Initial value:
 {
    {0, "DEFAULT", 0, "Default", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 1147 of file rna_access.c.
Referenced by ANIM_keying_sets_enum_itemf(), ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_active_set(), OBJECT_OT_proxy_make(), PAINT_OT_weight_sample_group(), and proxy_group_object_itemf().
EnumPropertyItem DummyRNA_NULL_items[]
Initial value:
 {
    {0, NULL, 0, NULL, NULL}
}
Definition at line 1142 of file rna_access.c.
Referenced by BPy_EnumProperty(), bpy_props_enum_itemf(), hook_mod_itemf(), LOGIC_OT_actuator_add(), LOGIC_OT_sensor_add(), MARKER_OT_make_links_scene(), NLA_OT_actionclip_add(), OBJECT_OT_group_instance_add(), OBJECT_OT_group_link(), OBJECT_OT_hook_assign(), OBJECT_OT_hook_recenter(), OBJECT_OT_hook_remove(), OBJECT_OT_hook_reset(), OBJECT_OT_hook_select(), OBJECT_OT_make_links_scene(), object_select_menu_enum_itemf(), OUTLINER_OT_action_set(), PAINT_OT_project_image(), POSELIB_OT_pose_remove(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_scene_strip_add(), VIEW3D_OT_select_menu(), and weight_paint_sample_enum_itemf().
const PointerRNA PointerRNA_NULL = {{NULL}}
Definition at line 66 of file rna_access.c.
Referenced by CTX_data_pointer_get(), CTX_data_pointer_get_type(), pyrna_prop_collection_ass_subscript_int(), rna_array_lookup_int(), RNA_pointer_get(), rna_pointer_inherit_refine(), RNA_property_pointer_get(), RNA_property_pointer_get_default(), ui_set_but_string(), uiItemFullO(), and uiItemFullO_ptr().
ListBase rna_updates_cache = {NULL, NULL} [static]
Definition at line 1530 of file rna_access.c.
PropertyRNA* typemap[IDP_NUMTYPES] [static]
Initial value:
    {(PropertyRNA*)&rna_PropertyGroupItem_string,
     (PropertyRNA*)&rna_PropertyGroupItem_int,
     (PropertyRNA*)&rna_PropertyGroupItem_float,
     NULL, NULL, NULL,
     (PropertyRNA*)&rna_PropertyGroupItem_group, NULL,
     (PropertyRNA*)&rna_PropertyGroupItem_double,
     (PropertyRNA*)&rna_PropertyGroupItem_idp_array}
Definition at line 376 of file rna_access.c.