Blender: space_graph.c File Reference
space_graph.c File Reference
graph editor
#include <string.h>
#include <stdio.h>
#include "DNA_anim_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_fcurve.h"
#include "BKE_screen.h"
#include "ED_space_api.h"
#include "ED_screen.h"
#include "ED_anim_api.h"
#include "ED_markers.h"
#include "BIF_gl.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "graph_intern.h"
Functions
ARegion * graph_has_buttons_region (ScrArea *sa)
static SpaceLink * graph_new (const bContext *C)
static void graph_free (SpaceLink *sl)
static void graph_init (struct wmWindowManager *UNUSED(wm), ScrArea *sa)
static SpaceLink * graph_duplicate (SpaceLink *sl)
static void graph_main_area_init (wmWindowManager *wm, ARegion *ar)
static void graph_main_area_draw (const bContext *C, ARegion *ar)
static void graph_channel_area_init (wmWindowManager *wm, ARegion *ar)
static void graph_channel_area_draw (const bContext *C, ARegion *ar)
static void graph_header_area_init (wmWindowManager *UNUSED(wm), ARegion *ar)
static void graph_header_area_draw (const bContext *C, ARegion *ar)
static void graph_buttons_area_init (wmWindowManager *wm, ARegion *ar)
static void graph_buttons_area_draw (const bContext *C, ARegion *ar)
static void graph_region_listener (ARegion *ar, wmNotifier *wmn)
static void graph_listener (ScrArea *sa, wmNotifier *wmn)
static void graph_refresh (const bContext *C, ScrArea *sa)
void ED_spacetype_ipo (void)
Detailed Description
Definition in file space_graph.c.
Function Documentation
void ED_spacetype_ipo (void)
Definition at line 591 of file space_graph.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_ANIMATION, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_MARKERS, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, graph_buttons_area_draw(), graph_buttons_area_init(), graph_buttons_register(), graph_channel_area_draw(), graph_channel_area_init(), graph_duplicate(), graph_free(), graph_header_area_draw(), graph_header_area_init(), graph_init(), graph_listener(), graph_main_area_draw(), graph_main_area_init(), graph_new(), graph_refresh(), graph_region_listener(), graphedit_keymap(), graphedit_operatortypes(), HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_CHANNELS, RGN_TYPE_HEADER, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_IPO, SpaceType::spaceid, and V2D_SCROLL_WIDTH.
Referenced by ED_spacetypes_init().
static void graph_buttons_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 369 of file space_graph.c.
References ED_region_panels(), and NULL.
Referenced by ED_spacetype_ipo().
static void graph_buttons_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 359 of file space_graph.c.
References wmWindowManager::defaultconf, ED_region_panels_init(), ARegion::handlers, View2D::mask, SPACE_IPO, ARegion::v2d, ARegion::winrct, WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_ipo().
static void graph_channel_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 319 of file space_graph.c.
References ANIM_animdata_get_context(), graph_draw_channel_names(), TH_BACK, UI_GetThemeColor3fv(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_view_ortho(), UI_view2d_view_restore(), ARegion::v2d, and V2D_ARG_DUMMY.
Referenced by ED_spacetype_ipo().
static void graph_channel_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 306 of file space_graph.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, SPACE_IPO, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_LIST, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler(), WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_ipo().
static SpaceLink* graph_duplicate (SpaceLink * sl) [static]
Definition at line 195 of file space_graph.c.
References SpaceIpo::ads, BLI_duplicatelist(), SpaceIpo::ghostCurves, and MEM_dupallocN().
Referenced by ED_spacetype_ipo().
static void graph_free (SpaceLink * sl) [static]
Definition at line 167 of file space_graph.c.
References SpaceIpo::ads, BLI_freelistN(), bDopeSheet::chanbase, ListBase::first, free_fcurves(), SpaceIpo::ghostCurves, MEM_freeN(), and si.
Referenced by ED_spacetype_ipo().
ARegion* graph_has_buttons_region (ScrArea * sa) [read]
Definition at line 68 of file space_graph.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_RIGHT, RGN_FLAG_HIDDEN, RGN_TYPE_UI, and RGN_TYPE_WINDOW.
Referenced by graph_properties().
static void graph_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 353 of file space_graph.c.
References ED_region_header().
Referenced by ED_spacetype_ipo().
static void graph_header_area_init (wmWindowManager * UNUSEDwm, ARegion * ar) [static]
Definition at line 348 of file space_graph.c.
References ED_region_header_init().
Referenced by ED_spacetype_ipo().
static void graph_init (struct wmWindowManager * UNUSEDwm, ScrArea * sa) [static]
Definition at line 182 of file space_graph.c.
References SpaceIpo::ads, ED_area_tag_refresh(), ListBase::first, G, if(), MEM_callocN(), NULL, bDopeSheet::source, and ScrArea::spacedata.
Referenced by ED_spacetype_ipo().
static void graph_listener (ScrArea * sa, wmNotifier * wmn) [static]
Definition at line 428 of file space_graph.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_area_tag_redraw(), ED_area_tag_refresh(), ELEM, ListBase::first, SpaceIpo::flag, NA_SELECTED, NC_ANIMATION, NC_NODE, NC_OBJECT, NC_SCENE, NC_SPACE, ND_ANIMCHAN, ND_BONE_ACTIVE, ND_BONE_SELECT, ND_KEYFRAME, ND_OB_ACTIVE, ND_OB_SELECT, ND_SPACE_GRAPH, ND_TRANSFORM, SIPO_TEMP_NEEDCHANSYNC, and ScrArea::spacedata.
Referenced by ED_spacetype_ipo().
static void graph_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 220 of file space_graph.c.
References ANIM_animdata_get_context(), ANIM_draw_cfra(), ANIM_draw_previewrange(), CTX_data_scene(), CTX_wm_space_graph(), View2D::cur, SpaceIpo::cursorVal, draw_markers_time(), DRAWCFRA_SHOW_NUMBOX, DRAWCFRA_UNIT_SECONDS, FALSE, SpaceIpo::flag, get_graph_keyframe_extents(), graph_draw_curves(), graph_draw_ghost_curves(), SIPO_DRAWTIME, SIPO_NODRAWCFRANUM, SIPO_NODRAWCURSOR, TH_BACK, TH_CFRAME, View2D::tot, UI_GetThemeColor3fv(), UI_ThemeColorShadeAlpha(), UI_view2d_grid_calc(), UI_view2d_grid_draw(), UI_view2d_grid_free(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_view_ortho(), UI_view2d_view_orthoSpecial(), UI_view2d_view_restore(), ARegion::v2d, V2D_GRID_NOCLAMP, V2D_GRIDLINES_ALL, V2D_UNIT_FRAMESCALE, V2D_UNIT_SECONDS, V2D_UNIT_VALUES, ARegion::winx, ARegion::winy, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by ED_spacetype_ipo().
static void graph_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 207 of file space_graph.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, SPACE_IPO, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_CUSTOM, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler(), WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_ipo().
static SpaceLink* graph_new (const bContext * C) [static]
Definition at line 95 of file space_graph.c.
References SpaceIpo::ads, ADS_FILTER_ONLYSEL, ARegion::alignment, SpaceIpo::autosnap, BLI_addtail(), CTX_data_scene(), View2D::cur, RenderData::efra, bDopeSheet::filterflag, ARegion::flag, SpaceIpo::flag, FLT_MAX, View2D::keeptot, View2D::max, MAXFRAMEF, MEM_callocN(), View2D::min, Scene::r, SpaceIpo::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_ALIGN_LEFT, RGN_ALIGN_RIGHT, RGN_FLAG_HIDDEN, RGN_TYPE_CHANNELS, RGN_TYPE_HEADER, RGN_TYPE_UI, RGN_TYPE_WINDOW, SACTSNAP_FRAME, View2D::scroll, RenderData::sfra, SIPO_SELVHANDLESONLY, bDopeSheet::source, SPACE_IPO, SpaceIpo::spacetype, View2D::tot, ARegion::v2d, V2D_SCROLL_BOTTOM, V2D_SCROLL_LEFT, V2D_SCROLL_RIGHT, V2D_SCROLL_SCALE_HORIZONTAL, V2D_SCROLL_SCALE_VERTICAL, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by ED_spacetype_ipo().
static void graph_refresh (const bContext * C, ScrArea * sa) [static]
Definition at line 490 of file space_graph.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIM_sync_animchannels_to_data(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_NODUPLIS, FCurve::array_index, BLI_freelistN(), FCurve::color, FCurve::color_mode, bAnimListElem::data, FCURVE_COLOR_AUTO_RAINBOW, FCURVE_COLOR_AUTO_RGB, FCURVE_COLOR_CUSTOM, filter(), ListBase::first, SpaceIpo::flag, getcolor_fcurve_rainbow(), i, SpaceIpo::mode, bAnimListElem::next, NULL, SIPO_MODE_ANIMATION, SIPO_MODE_DRIVERS, SIPO_TEMP_NEEDCHANSYNC, and ScrArea::spacedata.
Referenced by ED_spacetype_ipo().
static void graph_region_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 374 of file space_graph.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NA_EDITED, NA_RENAME, NA_SELECTED, NC_ANIMATION, NC_ID, NC_NODE, NC_OBJECT, NC_SCENE, ND_BONE_ACTIVE, ND_BONE_SELECT, ND_FRAME, ND_KEYS, ND_MARKERS, ND_MODIFIER, ND_OB_ACTIVE, ND_RENDER_OPTIONS, and ND_SEQUENCER.
Referenced by ED_spacetype_ipo().