Blender: main.cpp File Reference
main.cpp File Reference
#include "MEM_SmartPtr.h"
#include "IK_solver.h"
#include <GL/glut.h>
#include "MT_Vector3.h"
#include "MT_Quaternion.h"
#include "MT_Matrix3x3.h"
#include "MyGlutMouseHandler.h"
#include "MyGlutKeyHandler.h"
#include "ChainDrawer.h"
Functions
void init (MT_Vector3 min, MT_Vector3 max)
int main (int argc, char **argv)
Function Documentation
void init (MT_Vector3 min, MT_Vector3 max)
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) 2001-2002 by NaN Holding BV. All rights reserved.
The Original Code is: all of this file.
Contributor(s): none yet.
***** END GPL LICENSE BLOCK *****
Definition at line 45 of file iksolver/test/ik_glut_test/intern/main.cpp.
References distance(), MT_Vector3::length(), max, min, MT_Tuple3::x(), MT_Tuple3::y(), and MT_Tuple3::z().
int main (int argc, char ** argv)
Definition at line 98 of file iksolver/test/ik_glut_test/intern/main.cpp.
References GlutDrawManager::Draw(), MT_Matrix3x3::getValue(), GlutKeyboardManager::HandleKeyboard(), i, init(), GlutDrawManager::InstallDrawer(), GlutKeyboardManager::InstallHandler(), GlutMouseManager::InstallHandler(), GlutDrawManager::Instance(), GlutKeyboardManager::Instance(), GlutMouseManager::Instance(), GlutMouseManager::Motion(), GlutMouseManager::Mouse(), ChainDrawer::New(), MyGlutKeyHandler::New(), MyGlutMouseHandler::New(), and MT_Quaternion::setEuler().