Blender: ExtraTags Class Reference
ExtraTags Class Reference
Class for saving <extra> tags for a specific UniqueId.
#include <ExtraTags.h>
Public Member Functions
ExtraTags (const std::string profile)
virtual ~ExtraTags ()
bool addTag (std::string tag, std::string data)
void setData (std::string tag, short *data)
void setData (std::string tag, int *data)
void setData (std::string tag, float *data)
void setData (std::string tag, char *data)
bool isProfile (std::string profile)
Detailed Description
Class for saving <extra> tags for a specific UniqueId.
Definition at line 33 of file ExtraTags.h.
Constructor & Destructor Documentation
ExtraTags::ExtraTags (const std::string profile)
Constructor.
Definition at line 35 of file ExtraTags.cpp.
ExtraTags::~ExtraTags () [virtual]
Destructor.
Definition at line 41 of file ExtraTags.cpp.
Member Function Documentation
bool ExtraTags::addTag (std::string tag, std::string data)
Handle the beginning of an element.
Definition at line 50 of file ExtraTags.cpp.
References data.
Referenced by ExtraHandler::textData().
bool ExtraTags::isProfile (std::string profile)
Return true if the extra tags is for specified profile.
Definition at line 45 of file ExtraTags.cpp.
Referenced by DocumentImporter::writeLight().
void ExtraTags::setData (std::string tag, char * data)
Set given char pointer to value of tag, if it exists.
Definition at line 109 of file ExtraTags.cpp.
void ExtraTags::setData (std::string tag, float * data)
Set given float pointer to value of tag, if it exists.
Definition at line 102 of file ExtraTags.cpp.
void ExtraTags::setData (std::string tag, int * data)
Set given int pointer to value of tag, if it exists.
Definition at line 95 of file ExtraTags.cpp.
void ExtraTags::setData (std::string tag, short * data)
Set given short pointer to value of tag, if it exists.
Definition at line 88 of file ExtraTags.cpp.
Referenced by DocumentImporter::writeLight().
The documentation for this class was generated from the following files:
ExtraTags.h
ExtraTags.cpp