Blender: rna_animviz.c File Reference
rna_animviz.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_anim_types.h"
#include "DNA_action_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "WM_types.h"
Functions
void rna_def_motionpath_common (StructRNA *srna)
static void rna_def_animviz_motionpath_vert (BlenderRNA *brna)
static void rna_def_animviz_motion_path (BlenderRNA *brna)
static void rna_def_animviz_ghosts (BlenderRNA *brna)
static void rna_def_animviz_paths (BlenderRNA *brna)
void rna_def_animviz_common (StructRNA *srna)
static void rna_def_animviz (BlenderRNA *brna)
void RNA_def_animviz (BlenderRNA *brna)
Detailed Description
Definition in file rna_animviz.c.
Function Documentation
static void rna_def_animviz (BlenderRNA * brna) [static]
Definition at line 345 of file rna_animviz.c.
References NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_animviz().
void RNA_def_animviz (BlenderRNA * brna)
Definition at line 371 of file rna_animviz.c.
References rna_def_animviz(), rna_def_animviz_ghosts(), rna_def_animviz_motion_path(), rna_def_animviz_motionpath_vert(), and rna_def_animviz_paths().
void rna_def_animviz_common (StructRNA * srna)
Definition at line 335 of file rna_animviz.c.
References NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), and RNA_def_property_ui_text().
Referenced by rna_def_object(), and rna_def_pose().
static void rna_def_animviz_ghosts (BlenderRNA * brna) [static]
Definition at line 160 of file rna_animviz.c.
References GHOST_FLAG_ONLYSEL, GHOST_TYPE_ACFRA, GHOST_TYPE_KEYS, GHOST_TYPE_NONE, GHOST_TYPE_RANGE, NC_SPACE, ND_SPACE_VIEW3D, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_INT, PROP_NONE, PROP_TIME, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_animviz().
static void rna_def_animviz_motion_path (BlenderRNA * brna) [static]
Definition at line 116 of file rna_animviz.c.
References MOTIONPATH_FLAG_BHEAD, MOTIONPATH_FLAG_EDIT, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_TIME, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_int_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_animviz().
static void rna_def_animviz_motionpath_vert (BlenderRNA * brna) [static]
Definition at line 98 of file rna_animviz.c.
References MOTIONPATH_VERT_SEL, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_animviz().
static void rna_def_animviz_paths (BlenderRNA * brna) [static]
Definition at line 234 of file rna_animviz.c.
References MAXFRAMEF, MOTIONPATH_BAKE_HEADS, MOTIONPATH_TYPE_ACFRA, MOTIONPATH_TYPE_RANGE, MOTIONPATH_VIEW_FNUMS, MOTIONPATH_VIEW_KFACT, MOTIONPATH_VIEW_KFNOS, MOTIONPATH_VIEW_KFRAS, NC_SPACE, ND_SPACE_VIEW3D, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_INT, PROP_NONE, PROP_TIME, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_animviz().
void rna_def_motionpath_common (StructRNA * srna)
Definition at line 89 of file rna_animviz.c.
References NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_pointer_sdna(), and RNA_def_property_ui_text().
Referenced by rna_def_object(), and rna_def_pose_channel().