Blender: PixelFormat Namespace Reference
PixelFormat Namespace Reference
Functions
uint convert (uint c, uint inbits, uint outbits)
void maskShiftAndSize (uint mask, uint *shift, uint *size)
float quantizeCeil (float f, int inbits, int outbits)
Function Documentation
uint PixelFormat::convert (uint c, uint inbits, uint outbits) [inline]
Definition at line 67 of file PixelFormat.h.
Referenced by ShaderGraph::connect(), do_versions(), quantizeCeil(), and translate_id().
void PixelFormat::maskShiftAndSize (uint mask, uint * shift, uint * size) [inline]
Definition at line 86 of file PixelFormat.h.
float PixelFormat::quantizeCeil (float f, int inbits, int outbits) [inline]
Definition at line 108 of file PixelFormat.h.
References convert(), i, and uint.