Blender: BKE_anim.h File Reference
BKE_anim.h File Reference
blenkernel
Functions
void animviz_settings_init (struct bAnimVizSettings *avs)
void animviz_free_motionpath_cache (struct bMotionPath *mpath)
void animviz_free_motionpath (struct bMotionPath *mpath)
struct bMotionPath * animviz_verify_motionpaths (struct ReportList *reports, struct Scene *scene, struct Object *ob, struct bPoseChannel *pchan)
void animviz_get_object_motionpaths (struct Object *ob, ListBase *targets)
void animviz_calc_motionpaths (struct Scene *scene, ListBase *targets)
void free_path (struct Path *path)
void calc_curvepath (struct Object *ob)
int interval_test (int min, int max, int p1, int cycl)
int where_on_path (struct Object *ob, float ctime, float vec[4], float dir[3], float quat[4], float *radius, float *weight)
struct ListBase * object_duplilist (struct Scene *sce, struct Object *ob)
void free_object_duplilist (struct ListBase *lb)
int count_duplilist (struct Object *ob)
Detailed Description
Author:
nzc
Since:
March 2001
Definition in file BKE_anim.h.
Function Documentation
void animviz_calc_motionpaths (struct Scene * scene, ListBase * targets)
Definition at line 394 of file anim.c.
References ANIMVIZ_RECALC_PATHS, bPose::avs, Object::avs, CFRA, ELEM, bMotionPath::end_frame, ListBase::first, MAX2, MIN2, motionpaths_calc_bake_targets(), motionpaths_calc_optimise_depsgraph(), motionpaths_calc_update_scene(), MPathTarget::mpath, MPathTarget::next, NULL, MPathTarget::ob, MPathTarget::pchan, Object::pose, bAnimVizSettings::recalc, and bMotionPath::start_frame.
Referenced by ED_objects_recalculate_paths(), and ED_pose_recalculate_paths().
void animviz_free_motionpath (struct bMotionPath * mpath)
Definition at line 131 of file anim.c.
References animviz_free_motionpath_cache(), MEM_freeN(), and NULL.
Referenced by ED_objects_clear_paths(), ED_pose_clear_paths(), free_object(), and free_pose_channel().
void animviz_free_motionpath_cache (struct bMotionPath * mpath)
Definition at line 113 of file anim.c.
References bMotionPath::length, MEM_freeN(), NULL, and bMotionPath::points.
Referenced by animviz_free_motionpath().
void animviz_get_object_motionpaths (struct Object * ob, ListBase * targets)
Definition at line 237 of file anim.c.
References ANIMVIZ_RECALC_PATHS, Object::avs, bPose::avs, BLI_addtail(), bPoseChannel::bone, bPose::chanbase, Object::data, ListBase::first, Bone::layer, bArmature::layer, MEM_callocN(), Object::mpath, bPoseChannel::mpath, MPathTarget::mpath, bPoseChannel::next, MPathTarget::ob, MPathTarget::pchan, Object::pose, and bAnimVizSettings::recalc.
Referenced by ED_objects_recalculate_paths(), and ED_pose_recalculate_paths().
void animviz_settings_init (struct bAnimVizSettings * avs)
Definition at line 84 of file anim.c.
References bAnimVizSettings::ghost_ac, bAnimVizSettings::ghost_bc, bAnimVizSettings::ghost_ef, bAnimVizSettings::ghost_sf, bAnimVizSettings::ghost_step, MOTIONPATH_VIEW_KFNOS, MOTIONPATH_VIEW_KFRAS, NULL, bAnimVizSettings::path_ac, bAnimVizSettings::path_bc, bAnimVizSettings::path_ef, bAnimVizSettings::path_sf, bAnimVizSettings::path_step, and bAnimVizSettings::path_viewflag.
Referenced by add_only_object(), armature_rebuild_pose(), and do_versions().
struct bMotionPath* animviz_verify_motionpaths (struct ReportList * reports, struct Scene * scene, struct Object * ob, struct bPoseChannel * pchan) [read]
Definition at line 151 of file anim.c.
References bPose::avs, Object::avs, BKE_reportf(), ELEM, bMotionPath::end_frame, bMotionPath::flag, Object::id, bMotionPath::length, MEM_callocN(), MOTIONPATH_BAKE_HAS_PATHS, MOTIONPATH_BAKE_HEADS, MOTIONPATH_FLAG_BHEAD, Object::mpath, bPoseChannel::mpath, bPoseChannel::name, ID::name, NULL, bAnimVizSettings::path_bakeflag, bAnimVizSettings::path_ef, bAnimVizSettings::path_sf, bMotionPath::points, Object::pose, RPT_ERROR, and bMotionPath::start_frame.
Referenced by object_calculate_paths_exec(), and pose_calculate_paths_exec().
void calc_curvepath (struct Object * ob)
Definition at line 466 of file anim.c.
References BevPoint::alfa, Curve::bev, BKE_curve_nurbs(), Object::data, Path::data, ListBase::first, free_path(), interp_qt_qtqt(), interp_v3_v3v3(), Path::len, len_v3(), MEM_callocN(), MEM_freeN(), MEM_mallocN(), normalize_qt(), BevList::nr, NULL, OB_CURVE, Curve::path, BevList::poly, pp, PathPoint::quat, BevPoint::quat, BevPoint::radius, PathPoint::radius, Nurb::resolu, SEGMENTSU, sub_v3_v3v3(), Path::totdist, Object::type, PathPoint::vec, BevPoint::vec, PathPoint::weight, and BevPoint::weight.
Referenced by do_makeDispListCurveTypes().
int count_duplilist (struct Object * ob)
Definition at line 1646 of file anim.c.
References Object::data, Object::dupend, Object::dupoff, Object::dupon, Object::dupsta, ListBase::first, if(), ParticleSystem::next, OB_DUPLI, OB_DUPLIFRAMES, OB_DUPLIVERTS, OB_MESH, Object::particlesystem, ParticleSystem::totpart, Mesh::totvert, Object::transflag, and Object::type.
Referenced by stats_dupli_object().
void free_object_duplilist (struct ListBase * lb)
Definition at line 1630 of file anim.c.
References BLI_freelistN(), copy_m4_m4(), ListBase::last, Object::lay, MEM_freeN(), DupliObject::ob, Object::obmat, DupliObject::omat, DupliObject::origlay, and DupliObject::prev.
Referenced by BKE_ptcache_ids_from_object(), BKE_scene_foreach_display_point(), database_init_objects(), draw_dupli_objects_color(), gpu_update_lamps_shadows(), make_object_duplilist_real(), material_lights(), minmax_object_duplis(), next_object(), peelObjects(), snapObjects(), and view3d_opengl_select().
void free_path (struct Path * path)
Definition at line 457 of file anim.c.
References Path::data, and MEM_freeN().
Referenced by ANIM_channel_draw_widgets(), animsys_execute_fcurve(), calc_curvepath(), do_makeDispListCurveTypes(), and free_curve().
int interval_test (int min, int max, int p1, int cycl)
Definition at line 572 of file anim.c.
References max, and min.
Referenced by where_on_path().
struct ListBase* object_duplilist (struct Scene * sce, struct Object * ob) [read]
Definition at line 1622 of file anim.c.
References ListBase::first, ListBase::last, MEM_mallocN(), NULL, and object_duplilist_recursive().
Referenced by BKE_ptcache_ids_from_object(), BKE_scene_foreach_display_point(), database_init_objects(), draw_dupli_objects_color(), gpu_update_lamps_shadows(), make_object_duplilist_real(), material_lights(), minmax_object_duplis(), next_object(), peelObjects(), snapObjects(), and view3d_opengl_select().
int where_on_path (struct Object * ob, float ctime, float vec[4], float dir[3], float quat[4], float * radius, float * weight)
Definition at line 595 of file anim.c.
References Curve::bev, copy_qt_qt(), CU_BEZIER, CU_POLY, Path::data, Object::data, data, ListBase::first, interp_qt_qtqt(), interp_v3_v3v3v3v3(), interval_test(), KEY_BSPLINE, KEY_CARDINAL, key_curve_position_weights(), key_curve_tangent_weights(), KEY_LINEAR, Path::len, negate_v3(), BevList::nr, NULL, Curve::nurb, OB_CURVE, Curve::path, BevList::poly, pp, PathPoint::quat, PathPoint::radius, Nurb::type, Object::type, PathPoint::vec, and PathPoint::weight.
Referenced by BKE_text_to_curve(), clampto_evaluate(), do_guides(), draw_forcefield(), followpath_get_tarmat(), ob_parcurve(), precalculate_effector(), splineik_evaluate_bone(), and where_on_path_deform().