Blender: nodes.cpp File Reference
nodes.cpp File Reference
#include "image.h"
#include "nodes.h"
#include "svm.h"
#include "osl.h"
#include "util_transform.h"
Functions
static ShaderEnum color_space_init ()
static ShaderEnum projection_init ()
static float2 sky_spherical_coordinates (float3 dir)
static float sky_perez_function (float lam[6], float theta, float gamma)
static void sky_texture_precompute (KernelSunSky *ksunsky, float3 dir, float turbidity)
static ShaderEnum gradient_type_init ()
static ShaderEnum voronoi_coloring_init ()
static ShaderEnum musgrave_type_init ()
static ShaderEnum wave_type_init ()
static ShaderEnum glossy_distribution_init ()
static ShaderEnum glass_distribution_init ()
static ShaderEnum mix_type_init ()
static ShaderEnum math_type_init ()
static ShaderEnum vector_math_type_init ()
Function Documentation
static ShaderEnum color_space_init () [static]
Definition at line 92 of file nodes.cpp.
References ShaderEnum::insert().
static ShaderEnum glass_distribution_init () [static]
Definition at line 1143 of file nodes.cpp.
References CLOSURE_BSDF_MICROFACET_BECKMANN_REFRACTION_ID, CLOSURE_BSDF_MICROFACET_GGX_REFRACTION_ID, CLOSURE_BSDF_REFRACTION_ID, and ShaderEnum::insert().
static ShaderEnum glossy_distribution_init () [static]
Definition at line 1105 of file nodes.cpp.
References CLOSURE_BSDF_MICROFACET_BECKMANN_ID, CLOSURE_BSDF_MICROFACET_GGX_ID, CLOSURE_BSDF_REFLECTION_ID, and ShaderEnum::insert().
static ShaderEnum gradient_type_init () [static]
Definition at line 404 of file nodes.cpp.
References ShaderEnum::insert(), NODE_BLEND_DIAGONAL, NODE_BLEND_EASING, NODE_BLEND_LINEAR, NODE_BLEND_QUADRATIC, NODE_BLEND_QUADRATIC_SPHERE, NODE_BLEND_RADIAL, and NODE_BLEND_SPHERICAL.
static ShaderEnum math_type_init () [static]
Definition at line 2227 of file nodes.cpp.
References ShaderEnum::insert(), NODE_MATH_ADD, NODE_MATH_ARCCOSINE, NODE_MATH_ARCSINE, NODE_MATH_ARCTANGENT, NODE_MATH_COSINE, NODE_MATH_DIVIDE, NODE_MATH_GREATER_THAN, NODE_MATH_LESS_THAN, NODE_MATH_LOGARITHM, NODE_MATH_MAXIMUM, NODE_MATH_MINIMUM, NODE_MATH_MULTIPLY, NODE_MATH_POWER, NODE_MATH_ROUND, NODE_MATH_SINE, NODE_MATH_SUBTRACT, and NODE_MATH_TANGENT.
static ShaderEnum mix_type_init () [static]
Definition at line 1808 of file nodes.cpp.
References ShaderEnum::insert(), NODE_MIX_ADD, NODE_MIX_BLEND, NODE_MIX_BURN, NODE_MIX_COLOR, NODE_MIX_DARK, NODE_MIX_DIFF, NODE_MIX_DIV, NODE_MIX_DODGE, NODE_MIX_HUE, NODE_MIX_LIGHT, NODE_MIX_LINEAR, NODE_MIX_MUL, NODE_MIX_OVERLAY, NODE_MIX_SAT, NODE_MIX_SCREEN, NODE_MIX_SOFT, NODE_MIX_SUB, and NODE_MIX_VAL.
static ShaderEnum musgrave_type_init () [static]
Definition at line 584 of file nodes.cpp.
References ShaderEnum::insert(), NODE_MUSGRAVE_FBM, NODE_MUSGRAVE_HETERO_TERRAIN, NODE_MUSGRAVE_HYBRID_MULTIFRACTAL, NODE_MUSGRAVE_MULTIFRACTAL, and NODE_MUSGRAVE_RIDGED_MULTIFRACTAL.
static ShaderEnum projection_init () [static]
Definition at line 193 of file nodes.cpp.
References ShaderEnum::insert().
static float sky_perez_function (float lam[6], float theta, float gamma) [static]
Definition at line 302 of file nodes.cpp.
References cosf, and expf.
static float2 sky_spherical_coordinates (float3 dir) [static]
Definition at line 297 of file nodes.cpp.
References acosf, atan2f, make_float2(), float3::x, float3::y, and float3::z.
Referenced by sky_texture_precompute().
static void sky_texture_precompute (KernelSunSky * ksunsky, float3 dir, float turbidity) [static]
Definition at line 307 of file nodes.cpp.
References M_PI_F, KernelSunSky::perez_x, KernelSunSky::perez_y, KernelSunSky::perez_Y, KernelSunSky::phi, sky_perez_function(), sky_spherical_coordinates(), T, T2, KDL::tan(), KernelSunSky::theta, float2::x, float2::y, KernelSunSky::zenith_x, KernelSunSky::zenith_y, and KernelSunSky::zenith_Y.
static ShaderEnum vector_math_type_init () [static]
Definition at line 2287 of file nodes.cpp.
References ShaderEnum::insert(), NODE_VECTOR_MATH_ADD, NODE_VECTOR_MATH_AVERAGE, NODE_VECTOR_MATH_CROSS_PRODUCT, NODE_VECTOR_MATH_DOT_PRODUCT, NODE_VECTOR_MATH_NORMALIZE, and NODE_VECTOR_MATH_SUBTRACT.
static ShaderEnum voronoi_coloring_init () [static]
Definition at line 523 of file nodes.cpp.
References ShaderEnum::insert(), NODE_VORONOI_CELLS, and NODE_VORONOI_INTENSITY.
static ShaderEnum wave_type_init () [static]
Definition at line 672 of file nodes.cpp.
References ShaderEnum::insert(), NODE_WAVE_BANDS, and NODE_WAVE_RINGS.