Blender: KX_IPOTransform Class Reference
KX_IPOTransform Class Reference
#include <KX_IPOTransform.h>
Public Member Functions
KX_IPOTransform ()
MT_Transform GetTransform () const
MT_Point3 & GetPosition ()
MT_Vector3 & GetEulerAngles ()
MT_Vector3 & GetScaling ()
const MT_Point3 & GetPosition () const
const MT_Vector3 & GetEulerAngles () const
const MT_Vector3 & GetScaling () const
MT_Vector3 & GetDeltaPosition ()
MT_Vector3 & GetDeltaEulerAngles ()
MT_Vector3 & GetDeltaScaling ()
void SetPosition (const MT_Point3 &pos)
void SetEulerAngles (const MT_Vector3 &eul)
void SetScaling (const MT_Vector3 &scaling)
void ClearDeltaStuff ()
Protected Attributes
MT_Point3 m_position
MT_Vector3 m_eulerAngles
MT_Vector3 m_scaling
MT_Vector3 m_deltaPosition
MT_Vector3 m_deltaEulerAngles
MT_Vector3 m_deltaScaling
Detailed Description
Definition at line 38 of file KX_IPOTransform.h.
Constructor & Destructor Documentation
KX_IPOTransform::KX_IPOTransform () [inline]
Definition at line 40 of file KX_IPOTransform.h.
Member Function Documentation
void KX_IPOTransform::ClearDeltaStuff () [inline]
Definition at line 71 of file KX_IPOTransform.h.
References m_deltaEulerAngles, m_deltaPosition, m_deltaScaling, and MT_Tuple3::setValue().
MT_Vector3& KX_IPOTransform::GetDeltaEulerAngles () [inline]
Definition at line 64 of file KX_IPOTransform.h.
References m_deltaEulerAngles.
Referenced by BL_CreateIPO(), and KX_IpoSGController::Update().
MT_Vector3& KX_IPOTransform::GetDeltaPosition () [inline]
Definition at line 63 of file KX_IPOTransform.h.
References m_deltaPosition.
Referenced by BL_CreateIPO(), and KX_IpoSGController::Update().
MT_Vector3& KX_IPOTransform::GetDeltaScaling () [inline]
Definition at line 65 of file KX_IPOTransform.h.
References m_deltaScaling.
Referenced by BL_CreateIPO(), and KX_IpoSGController::Update().
MT_Vector3& KX_IPOTransform::GetEulerAngles () [inline]
Definition at line 56 of file KX_IPOTransform.h.
References m_eulerAngles.
Referenced by BL_CreateIPO(), and KX_IpoSGController::Update().
const MT_Vector3& KX_IPOTransform::GetEulerAngles () const [inline]
Definition at line 60 of file KX_IPOTransform.h.
References m_eulerAngles.
const MT_Point3& KX_IPOTransform::GetPosition () const [inline]
Definition at line 59 of file KX_IPOTransform.h.
References m_position.
MT_Point3& KX_IPOTransform::GetPosition () [inline]
Definition at line 55 of file KX_IPOTransform.h.
References m_position.
Referenced by BL_CreateIPO(), and KX_IpoSGController::Update().
MT_Vector3& KX_IPOTransform::GetScaling () [inline]
Definition at line 57 of file KX_IPOTransform.h.
References m_scaling.
Referenced by BL_CreateIPO(), and KX_IpoSGController::Update().
const MT_Vector3& KX_IPOTransform::GetScaling () const [inline]
Definition at line 61 of file KX_IPOTransform.h.
References m_scaling.
MT_Transform KX_IPOTransform::GetTransform () const [inline]
Definition at line 49 of file KX_IPOTransform.h.
References m_deltaEulerAngles, m_deltaPosition, m_deltaScaling, m_eulerAngles, m_position, and m_scaling.
void KX_IPOTransform::SetEulerAngles (const MT_Vector3 & eul) [inline]
Definition at line 68 of file KX_IPOTransform.h.
References m_eulerAngles.
Referenced by BL_CreateIPO().
void KX_IPOTransform::SetPosition (const MT_Point3 & pos) [inline]
Definition at line 67 of file KX_IPOTransform.h.
References m_position.
Referenced by BL_CreateIPO().
void KX_IPOTransform::SetScaling (const MT_Vector3 & scaling) [inline]
Definition at line 69 of file KX_IPOTransform.h.
References m_scaling.
Referenced by BL_CreateIPO().
Member Data Documentation
MT_Vector3 KX_IPOTransform::m_deltaEulerAngles [protected]
Definition at line 82 of file KX_IPOTransform.h.
Referenced by ClearDeltaStuff(), GetDeltaEulerAngles(), and GetTransform().
MT_Vector3 KX_IPOTransform::m_deltaPosition [protected]
Definition at line 81 of file KX_IPOTransform.h.
Referenced by ClearDeltaStuff(), GetDeltaPosition(), and GetTransform().
MT_Vector3 KX_IPOTransform::m_deltaScaling [protected]
Definition at line 83 of file KX_IPOTransform.h.
Referenced by ClearDeltaStuff(), GetDeltaScaling(), and GetTransform().
MT_Vector3 KX_IPOTransform::m_eulerAngles [protected]
Definition at line 79 of file KX_IPOTransform.h.
Referenced by GetEulerAngles(), GetTransform(), and SetEulerAngles().
MT_Point3 KX_IPOTransform::m_position [protected]
Definition at line 78 of file KX_IPOTransform.h.
Referenced by GetPosition(), GetTransform(), and SetPosition().
MT_Vector3 KX_IPOTransform::m_scaling [protected]
Definition at line 80 of file KX_IPOTransform.h.
Referenced by GetScaling(), GetTransform(), and SetScaling().
The documentation for this class was generated from the following file:
KX_IPOTransform.h