Blender: PTCacheID Struct Reference
PTCacheID Struct Reference
#include <BKE_pointcache.h>
Public Attributes
struct PTCacheID * next
struct PTCacheID * prev
struct Scene * scene
struct Object * ob
void * calldata
unsigned int type
unsigned int stack_index
unsigned int flag
unsigned int default_step
unsigned int max_step
unsigned int data_types
unsigned int info_types
int(* write_point)(int index, void *calldata, void **data, int cfra)
void(* read_point)(int index, void *calldata, void **data, float cfra, float *old_data)
void(* interpolate_point)(int index, void *calldata, void **data, float cfra, float cfra1, float cfra2, float *old_data)
int(* write_stream)(PTCacheFile *pf, void *calldata)
int(* read_stream)(PTCacheFile *pf, void *calldata)
void(* write_extra_data)(void *calldata, struct PTCacheMem *pm, int cfra)
void(* read_extra_data)(void *calldata, struct PTCacheMem *pm, float cfra)
void(* interpolate_extra_data)(void *calldata, struct PTCacheMem *pm, float cfra, float cfra1, float cfra2)
int(* totpoint)(void *calldata, int cfra)
int(* totwrite)(void *calldata, int cfra)
int(* write_header)(PTCacheFile *pf)
int(* read_header)(PTCacheFile *pf)
struct PointCache * cache
struct PointCache ** cache_ptr
struct ListBase * ptcaches
Detailed Description
Definition at line 120 of file BKE_pointcache.h.
Member Data Documentation
struct PointCache* PTCacheID::cache
Definition at line 163 of file BKE_pointcache.h.
Referenced by BKE_ptcache_bake(), BKE_ptcache_disk_cache_rename(), BKE_ptcache_disk_to_mem(), BKE_ptcache_id_clear(), BKE_ptcache_id_exist(), BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_id_reset(), BKE_ptcache_id_time(), BKE_ptcache_load_external(), BKE_ptcache_mem_to_disk(), BKE_ptcache_object_reset(), BKE_ptcache_read(), BKE_ptcache_toggle_disk_cache(), BKE_ptcache_update_info(), BKE_ptcache_write(), cloth_clear_cache(), dynamicPaint_frameUpdate(), ED_object_exit_editmode(), get_PTCacheUndo(), make_PTCacheUndo(), object_cacheIgnoreClear(), pe_get_current(), ptcache_add_new_exec(), ptcache_bake_exec(), ptcache_file_open(), ptcache_filename(), ptcache_find_frames_around(), ptcache_free_bake_all_exec(), ptcache_interpolate(), ptcache_mem_frame_to_disk(), ptcache_path(), ptcache_read(), ptcache_remove_exec(), ptcache_write(), ptcache_write_needed(), special_aftertrans_update(), time_draw_cache(), and tot_particles().
struct PointCache** PTCacheID::cache_ptr
Definition at line 165 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), ptcache_add_new_exec(), and ptcache_remove_exec().
void* PTCacheID::calldata
Definition at line 125 of file BKE_pointcache.h.
Referenced by BKE_ptcache_bake(), BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_id_reset(), BKE_ptcache_read(), BKE_ptcache_update_info(), BKE_ptcache_write(), pe_get_current(), ptcache_interpolate(), ptcache_read(), ptcache_read_stream(), ptcache_write(), and ptcache_write_stream().
unsigned int PTCacheID::data_types
Definition at line 134 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_write(), ptcache_interpolate(), ptcache_read(), ptcache_write(), and ptcache_write_stream().
unsigned int PTCacheID::default_step
Definition at line 130 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), and ptcache_add_new_exec().
unsigned int PTCacheID::flag
Definition at line 128 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_particles(), and update_velocities().
unsigned int PTCacheID::info_types
Definition at line 134 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_write(), and ptcache_write().
void(* PTCacheID::interpolate_extra_data)(void *calldata, struct PTCacheMem *pm, float cfra, float cfra1, float cfra2)
Definition at line 153 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), and ptcache_interpolate().
void(* PTCacheID::interpolate_point)(int index, void *calldata, void **data, float cfra, float cfra1, float cfra2, float *old_data)
Definition at line 141 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_read(), and ptcache_interpolate().
unsigned int PTCacheID::max_step
Definition at line 131 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), and BKE_ptcache_id_from_softbody().
struct PTCacheID* PTCacheID::next
Definition at line 121 of file BKE_pointcache.h.
Referenced by BKE_ptcache_bake(), ED_object_exit_editmode(), object_cacheIgnoreClear(), pe_get_current(), ptcache_add_new_exec(), ptcache_bake_exec(), ptcache_free_bake_all_exec(), ptcache_remove_exec(), special_aftertrans_update(), and time_draw_cache().
struct Object* PTCacheID::ob
Definition at line 124 of file BKE_pointcache.h.
Referenced by BKE_ptcache_bake(), BKE_ptcache_id_clear(), BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), ptcache_file_open(), ptcache_filename(), and ptcache_path().
struct PTCacheID * PTCacheID::prev
Definition at line 121 of file BKE_pointcache.h.
struct ListBase* PTCacheID::ptcaches
Definition at line 166 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), ptcache_add_new_exec(), and ptcache_remove_exec().
void(* PTCacheID::read_extra_data)(void *calldata, struct PTCacheMem *pm, float cfra)
Definition at line 151 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), and ptcache_read().
int(* PTCacheID::read_header)(PTCacheFile *pf)
Definition at line 161 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_load_external(), ptcache_disk_frame_to_mem(), and ptcache_read_stream().
void(* PTCacheID::read_point)(int index, void *calldata, void **data, float cfra, float *old_data)
Definition at line 139 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_read(), and ptcache_read().
int(* PTCacheID::read_stream)(PTCacheFile *pf, void *calldata)
Definition at line 146 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_read(), and ptcache_read_stream().
struct Scene* PTCacheID::scene
Definition at line 123 of file BKE_pointcache.h.
unsigned int PTCacheID::stack_index
Definition at line 127 of file BKE_pointcache.h.
Referenced by BKE_ptcache_disk_cache_rename(), BKE_ptcache_id_clear(), BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_id_time(), and ptcache_filename().
int(* PTCacheID::totpoint)(void *calldata, int cfra)
Definition at line 156 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_read(), BKE_ptcache_update_info(), BKE_ptcache_write(), ptcache_interpolate(), ptcache_read(), ptcache_read_stream(), and ptcache_write().
int(* PTCacheID::totwrite)(void *calldata, int cfra)
Definition at line 158 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), and ptcache_write().
unsigned int PTCacheID::type
Definition at line 126 of file BKE_pointcache.h.
Referenced by BKE_ptcache_bake(), BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_id_reset(), BKE_ptcache_load_external(), BKE_ptcache_update_info(), ED_object_exit_editmode(), pe_get_current(), ptcache_disk_frame_to_mem(), ptcache_mem_frame_to_disk(), ptcache_old_elemsize(), ptcache_read_stream(), ptcache_write_stream(), special_aftertrans_update(), and time_draw_cache().
void(* PTCacheID::write_extra_data)(void *calldata, struct PTCacheMem *pm, int cfra)
Definition at line 149 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), and ptcache_write().
int(* PTCacheID::write_header)(PTCacheFile *pf)
Definition at line 160 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), ptcache_mem_frame_to_disk(), and ptcache_write_stream().
int(* PTCacheID::write_point)(int index, void *calldata, void **data, int cfra)
Definition at line 137 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_write(), and ptcache_write().
int(* PTCacheID::write_stream)(PTCacheFile *pf, void *calldata)
Definition at line 144 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_write(), and ptcache_write_stream().
The documentation for this struct was generated from the following file:
BKE_pointcache.h