Blender: script_ops.c File Reference
script_ops.c File Reference
script space
#include <stdlib.h>
#include <math.h>
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BKE_context.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
#include "script_intern.h"
Functions
void script_operatortypes (void)
void script_keymap (wmKeyConfig *keyconf)
Detailed Description
Definition in file script_ops.c.
Function Documentation
void script_keymap (wmKeyConfig * keyconf)
Definition at line 61 of file script_ops.c.
References KM_ALT, KM_CTRL, KM_PRESS, KM_SHIFT, PKEY, RNA_string_set(), SPACE_SCRIPT, WM_keymap_add_item(), and WM_keymap_find().
Referenced by ED_spacetype_script().
void script_operatortypes (void)
Definition at line 55 of file script_ops.c.
References SCRIPT_OT_python_file_run(), SCRIPT_OT_reload(), and WM_operatortype_append().
Referenced by ED_spacetype_script().