Blender: node_intern.h File Reference
node_intern.h File Reference
node editor
#include <stddef.h>
#include "UI_interface.h"
Classes
struct bNodeLinkDrag
Defines
#define HIDDEN_RAD 15.0f
#define BASIS_RAD 8.0f
#define NODE_DYS (U.widget_unit/2)
#define NODE_DY U.widget_unit
#define NODE_SOCKSIZE 5
Typedefs
typedef struct bNodeLinkDrag bNodeLinkDrag
Enumerations
enum {
B_NOP = 0, B_REDR = 1, B_NODE_USEMAT, B_NODE_USESCENE,
B_NODE_USETEX, B_TEXBROWSE, B_TEXALONE, B_TEXLOCAL,
B_TEXDELETE, B_TEXPRV, B_AUTOTEXNAME, B_KEEPDATA,
B_NODE_EXEC, B_MATPRV, B_NODE_LOADIMAGE, B_NODE_SETIMAGE
}
Functions
ARegion * node_has_buttons_region (ScrArea *sa)
void node_menus_register (void)
void node_socket_circle_draw (struct bNodeTree *ntree, struct bNodeSocket *sock, float size)
void node_draw_default (const struct bContext *C, struct ARegion *ar, struct SpaceNode *snode, struct bNodeTree *ntree, struct bNode *node)
void node_update_default (const struct bContext *C, struct bNodeTree *ntree, struct bNode *node)
void node_update_nodetree (const struct bContext *C, struct bNodeTree *ntree, float offsetx, float offsety)
void node_draw_nodetree (const struct bContext *C, struct ARegion *ar, struct SpaceNode *snode, struct bNodeTree *ntree)
void drawnodespace (const bContext *C, ARegion *ar, View2D *v2d)
void node_buttons_register (struct ARegionType *art)
void NODE_OT_properties (struct wmOperatorType *ot)
void node_operatortypes (void)
void node_keymap (wmKeyConfig *keyconf)
void node_select (struct bNode *node)
void node_deselect (struct bNode *node)
void node_deselect_all (struct SpaceNode *snode)
void node_socket_select (struct bNode *node, struct bNodeSocket *sock)
void node_socket_deselect (struct bNode *node, struct bNodeSocket *sock, int deselect_node)
void node_deselect_all_input_sockets (struct SpaceNode *snode, int deselect_nodes)
void node_deselect_all_output_sockets (struct SpaceNode *snode, int deselect_nodes)
int node_select_same_type (struct SpaceNode *snode)
int node_select_same_type_np (struct SpaceNode *snode, int dir)
void node_select_single (struct bContext *C, struct bNode *node)
void NODE_OT_select (struct wmOperatorType *ot)
void NODE_OT_select_all (wmOperatorType *ot)
void NODE_OT_select_linked_to (wmOperatorType *ot)
void NODE_OT_select_linked_from (wmOperatorType *ot)
void NODE_OT_select_border (struct wmOperatorType *ot)
void NODE_OT_select_same_type (struct wmOperatorType *ot)
void NODE_OT_select_same_type_next (wmOperatorType *ot)
void NODE_OT_select_same_type_prev (wmOperatorType *ot)
void NODE_OT_view_all (struct wmOperatorType *ot)
void node_draw_link (View2D *v2d, SpaceNode *snode, bNodeLink *link)
void node_draw_link_bezier (View2D *v2d, SpaceNode *snode, bNodeLink *link, int th_col1, int do_shaded, int th_col2, int do_triple, int th_col3)
int node_link_bezier_points (View2D *v2d, SpaceNode *snode, bNodeLink *link, float coord_array[][2], int resol)
void node_draw_link_straight (View2D *v2d, SpaceNode *snode, bNodeLink *link, int th_col1, int do_shaded, int th_col2, int do_triple, int th_col3)
void draw_nodespace_back_pix (ARegion *ar, SpaceNode *snode, int color_manage)
void node_tree_from_ID (ID *id, bNodeTree **ntree, bNodeTree **edittree, int *treetype)
void snode_notify (bContext *C, SpaceNode *snode)
void snode_dag_update (bContext *C, SpaceNode *snode)
bNode * node_add_node (struct SpaceNode *snode, struct Main *bmain, struct Scene *scene, struct bNodeTemplate *ntemp, float locx, float locy)
void snode_set_context (SpaceNode *snode, Scene *scene)
void snode_make_group_editable (SpaceNode *snode, bNode *gnode)
void snode_composite_job (const struct bContext *C, ScrArea *sa)
bNode * node_tree_get_editgroup (bNodeTree *ntree)
void snode_autoconnect (SpaceNode *snode, int allow_multiple, int replace)
int node_has_hidden_sockets (bNode *node)
void node_set_hidden_sockets (SpaceNode *snode, bNode *node, int set)
int node_render_changed_exec (bContext *, wmOperator *)
int node_find_indicated_socket (struct SpaceNode *snode, struct bNode **nodep, struct bNodeSocket **sockp, int in_out)
void NODE_OT_duplicate (struct wmOperatorType *ot)
void NODE_OT_delete (struct wmOperatorType *ot)
void NODE_OT_delete_reconnect (struct wmOperatorType *ot)
void NODE_OT_resize (struct wmOperatorType *ot)
void NODE_OT_link (struct wmOperatorType *ot)
void NODE_OT_link_make (struct wmOperatorType *ot)
void NODE_OT_links_cut (struct wmOperatorType *ot)
void NODE_OT_links_detach (struct wmOperatorType *ot)
void NODE_OT_group_make (struct wmOperatorType *ot)
void NODE_OT_group_ungroup (struct wmOperatorType *ot)
void NODE_OT_group_edit (struct wmOperatorType *ot)
void NODE_OT_group_socket_add (struct wmOperatorType *ot)
void NODE_OT_group_socket_remove (struct wmOperatorType *ot)
void NODE_OT_group_socket_move_up (struct wmOperatorType *ot)
void NODE_OT_group_socket_move_down (struct wmOperatorType *ot)
void NODE_OT_mute_toggle (struct wmOperatorType *ot)
void NODE_OT_hide_toggle (struct wmOperatorType *ot)
void NODE_OT_hide_socket_toggle (struct wmOperatorType *ot)
void NODE_OT_preview_toggle (struct wmOperatorType *ot)
void NODE_OT_options_toggle (struct wmOperatorType *ot)
void NODE_OT_show_cyclic_dependencies (struct wmOperatorType *ot)
void NODE_OT_link_viewer (struct wmOperatorType *ot)
void NODE_OT_read_fullsamplelayers (struct wmOperatorType *ot)
void NODE_OT_read_renderlayers (struct wmOperatorType *ot)
void NODE_OT_render_changed (struct wmOperatorType *ot)
void NODE_OT_backimage_move (struct wmOperatorType *ot)
void NODE_OT_backimage_zoom (struct wmOperatorType *ot)
void NODE_OT_backimage_sample (wmOperatorType *ot)
void NODE_OT_add_file (struct wmOperatorType *ot)
void NODE_OT_new_node_tree (struct wmOperatorType *ot)
void NODE_OT_output_file_add_socket (struct wmOperatorType *ot)
void NODE_OT_output_file_remove_active_socket (struct wmOperatorType *ot)
Variables
const char * node_context_dir []
enum { ... } eNodeSpace_ButEvents
Detailed Description
Definition in file node_intern.h.
Define Documentation
#define BASIS_RAD 8.0f
Definition at line 176 of file node_intern.h.
Referenced by node_draw_basis(), and node_draw_group().
#define HIDDEN_RAD 15.0f
Definition at line 175 of file node_intern.h.
Referenced by node_update_hidden().
#define NODE_DY U.widget_unit
Definition at line 178 of file node_intern.h.
Referenced by draw_group_socket(), draw_group_socket_name(), node_draw_basis(), node_draw_hidden(), node_mouse_groupheader(), node_socket_button_color(), node_socket_button_components(), node_socket_button_default(), node_socket_button_label(), node_socket_button_output_file(), node_update_basis(), node_update_group(), node_update_hidden(), and socket_component_menu().
#define NODE_DYS (U.widget_unit/2)
Definition at line 177 of file node_intern.h.
Referenced by draw_group_socket(), node_draw_basis(), node_update_basis(), node_update_frame(), and node_update_group().
#define NODE_SOCKSIZE 5
Definition at line 179 of file node_intern.h.
Referenced by draw_group_socket(), node_draw_basis(), node_draw_hidden(), node_find_indicated_socket(), node_update_basis(), and node_update_hidden().
Typedef Documentation
typedef struct bNodeLinkDrag bNodeLinkDrag
Enumeration Type Documentation
anonymous enum
Enumerator:
B_NOP
B_REDR
B_NODE_USEMAT
B_NODE_USESCENE
B_NODE_USETEX
B_TEXBROWSE
B_TEXALONE
B_TEXLOCAL
B_TEXDELETE
B_TEXPRV
B_AUTOTEXNAME
B_KEEPDATA
B_NODE_EXEC
B_MATPRV
B_NODE_LOADIMAGE
B_NODE_SETIMAGE
Definition at line 182 of file node_intern.h.
Function Documentation
void draw_nodespace_back_pix (ARegion * ar, SpaceNode * snode, int color_manage)
Definition at line 2332 of file drawnode.c.
References B_ENDIAN, BKE_image_acquire_ibuf(), BKE_image_release_ibuf(), BKE_image_verify_viewer(), ENDIAN_ORDER, SpaceNode::flag, glaDefine2DArea(), glaDrawPixelsSafe(), IB_PROFILE_LINEAR_RGB, IB_PROFILE_NONE, IMA_TYPE_COMPOSITE, IMB_rect_from_float(), NTREE_COMPOSIT, NULL, ImBuf::profile, ImBuf::rect, SNODE_BACKDRAW, SNODE_SHOW_ALPHA, SNODE_USE_ALPHA, SpaceNode::treetype, ARegion::winrct, ARegion::winx, ARegion::winy, wmOrtho2(), ImBuf::x, SpaceNode::xof, ImBuf::y, SpaceNode::yof, and SpaceNode::zoom.
Referenced by drawnodespace().
void drawnodespace (const bContext * C, ARegion * ar, View2D * v2d)
Definition at line 926 of file node_draw.c.
References SpaceNode::aspect, RenderData::color_mgt_flag, CTX_data_scene(), CTX_wm_space_node(), View2D::cur, draw_gpencil_view2d(), draw_nodespace_back_pix(), ListBase::first, bNode::flag, bNode::id, bNodeLinkDrag::link, SpaceNode::linkdrag, bNodeLinkDrag::next, bNode::next, node_draw_group(), node_draw_link(), node_draw_nodetree(), NODE_GROUP_EDIT, node_uiblocks_init(), node_update_nodetree(), bNodeTree::nodes, SpaceNode::nodetree, Scene::r, R_COLOR_MANAGEMENT, snode_set_context(), TH_BACK, UI_ThemeClearColor(), UI_view2d_constant_grid_draw(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_view_ortho(), UI_view2d_view_restore(), ARegion::v2d, V2D_ARG_DUMMY, V2D_GRID_CLAMP, ARegion::winx, rctf::xmax, and rctf::xmin.
Referenced by node_main_area_draw().
bNode* node_add_node (struct SpaceNode * snode, struct Main * bmain, struct Scene * scene, struct bNodeTemplate * ntemp, float locx, float locy)
Definition at line 2113 of file node_edit.c.
References Scene::clip, CMP_NODE_COMPOSITE, CMP_NODE_DEFOCUS, CMP_NODE_MOVIECLIP, CMP_NODE_MOVIEDISTORTION, CMP_NODE_OUTPUT_FILE, CMP_NODE_R_LAYERS, CMP_NODE_STABILIZE2D, ED_node_set_active(), SpaceNode::edittree, ELEM3, ELEM4, Scene::id, bNode::id, id_us_plus(), bNode::locx, bNode::locy, node_deselect_all(), node_select(), node_tree_get_editgroup(), nodeAddNode(), SpaceNode::nodetree, NTREE_COMPOSIT, NTREE_TEXTURE, ntreeCompositForceHidden(), ntreeTexCheckCyclics(), ntreeUpdateTree(), NULL, snode_update(), bNodeTree::type, and bNode::type.
Referenced by do_node_add(), node_add_file_exec(), and node_link_viewer().
void node_buttons_register (struct ARegionType * art)
Definition at line 149 of file node_buttons.c.
References active_node_panel(), active_node_poll(), active_nodetree_poll(), BLI_addtail(), PanelType::draw, PanelType::flag, gpencil_panel_standard(), PanelType::idname, IFACE_, PanelType::label, MEM_callocN(), node_sockets_panel(), node_sockets_poll(), ARegionType::paneltypes, PNL_DEFAULT_CLOSED, and PanelType::poll.
Referenced by ED_spacetype_node().
void node_deselect (struct bNode * node)
Definition at line 181 of file node_select.c.
References ListBase::first, bNode::flag, bNodeSocket::flag, bNode::inputs, bNodeSocket::next, bNode::outputs, and SELECT.
Referenced by node_borderselect_exec(), node_deselect_all(), node_duplicate_exec(), node_mouse_select(), node_select_all_exec(), node_select_same_type(), node_select_same_type_np(), node_select_single(), node_toggle(), and snode_make_group_editable().
void node_deselect_all (struct SpaceNode * snode)
Definition at line 246 of file node_select.c.
References SpaceNode::edittree, ListBase::first, bNode::next, node_deselect(), and bNodeTree::nodes.
Referenced by node_add_file_exec(), and node_add_node().
void node_deselect_all_input_sockets (struct SpaceNode * snode, int deselect_nodes)
Definition at line 254 of file node_select.c.
References SpaceNode::edittree, ListBase::first, bNode::flag, bNodeSocket::flag, bNode::inputs, bNodeSocket::next, bNode::next, bNodeTree::nodes, bNode::outputs, bNodeTree::outputs, and SELECT.
Referenced by node_link_init(), node_link_modal(), and node_make_link_exec().
void node_deselect_all_output_sockets (struct SpaceNode * snode, int deselect_nodes)
Definition at line 288 of file node_select.c.
References SpaceNode::edittree, ListBase::first, bNode::flag, bNodeSocket::flag, bNodeTree::inputs, bNode::inputs, bNodeSocket::next, bNode::next, bNodeTree::nodes, bNode::outputs, and SELECT.
Referenced by node_link_init(), node_link_modal(), and node_make_link_exec().
void node_draw_default (const struct bContext * C, struct ARegion * ar, struct SpaceNode * snode, struct bNodeTree * ntree, struct bNode * node)
void node_draw_link (View2D * v2d, SpaceNode * snode, bNodeLink * link)
Definition at line 2649 of file drawnode.c.
References bNodeLink::flag, bNode::flag, bNodeSocket::flag, bNodeLink::fromnode, bNodeLink::fromsock, bNode::level, node_draw_link_bezier(), NODE_LINK_VALID, NODE_LINKFLAG_HILITE, NULL, SELECT, SOCK_UNAVAIL, TH_ACTIVE, TH_BACK, TH_EDGE_SELECT, TH_HEADER, TH_REDALERT, TH_WIRE, bNodeLink::tonode, bNodeLink::tosock, and UI_ThemeColorBlend().
Referenced by drawnodespace(), and node_draw_nodetree().
void node_draw_link_bezier (View2D * v2d, SpaceNode * snode, bNodeLink * link, int th_col1, int do_shaded, int th_col2, int do_triple, int th_col3)
Definition at line 2506 of file drawnode.c.
References i, LINK_RESOL, node_link_bezier_points(), UI_ThemeColor(), UI_ThemeColorBlend(), and UI_ThemeColorShadeAlpha().
Referenced by node_draw_link(), and node_draw_mute_line().
void node_draw_link_straight (View2D * v2d, SpaceNode * snode, bNodeLink * link, int th_col1, int do_shaded, int th_col2, int do_triple, int th_col3)
Definition at line 2590 of file drawnode.c.
References i, LINK_RESOL, node_link_straight_points(), UI_ThemeColor(), UI_ThemeColorBlend(), and UI_ThemeColorShadeAlpha().
void node_draw_nodetree (const struct bContext * C, struct ARegion * ar, struct SpaceNode * snode, struct bNodeTree * ntree)
int node_find_indicated_socket (struct SpaceNode * snode, struct bNode ** nodep, struct bNodeSocket ** sockp, int in_out)
Definition at line 1808 of file node_edit.c.
References BLI_in_rctf(), SpaceNode::edittree, ListBase::first, bNode::flag, bNodeTree::inputs, bNode::inputs, bNodeSocket::locx, bNodeSocket::locy, SpaceNode::mx, SpaceNode::my, bNodeSocket::next, bNode::next, NODE_HIDDEN, NODE_SOCKSIZE, bNodeTree::nodes, nodeSocketIsHidden(), NULL, bNode::outputs, bNodeTree::outputs, SOCK_IN, SOCK_OUT, visible_node(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by node_link_init(), node_link_modal(), and node_mouse_select().
ARegion* node_has_buttons_region (ScrArea * sa)
Definition at line 70 of file space_node.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_RIGHT, RGN_FLAG_HIDDEN, RGN_TYPE_HEADER, and RGN_TYPE_UI.
Referenced by node_properties().
int node_has_hidden_sockets (bNode * node)
Definition at line 1610 of file node_edit.c.
References ListBase::first, bNodeSocket::flag, bNode::inputs, bNodeSocket::next, bNode::outputs, and SOCK_HIDDEN.
Referenced by node_socket_toggle_exec().
void node_keymap (wmKeyConfig * keyconf)
Definition at line 137 of file node_ops.c.
References ACTIONMOUSE, AKEY, BKEY, CKEY, DELKEY, DKEY, EVT_TWEAK_S, FALSE, FKEY, GKEY, HKEY, HOMEKEY, KM_ALT, KM_ANY, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTBRACKETKEY, LEFTMOUSE, LKEY, MIDDLEMOUSE, MKEY, NKEY, wmKeyMapItem::ptr, RIGHTBRACKETKEY, RKEY, RNA_boolean_set(), RNA_float_set(), SELECTMOUSE, SPACE_NODE, TABKEY, transform_keymap_for_space(), TRUE, VKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), XKEY, and ZKEY.
Referenced by ED_spacetype_node().
int node_link_bezier_points (View2D * v2d, SpaceNode * snode, bNodeLink * link, float coord_array[][2], int resol)
Definition at line 2459 of file drawnode.c.
References ABS, View2D::cur, forward_diff_bezier(), bNodeLink::fromsock, bNodeSocket::locx, bNodeSocket::locy, MAX4, MIN4, SpaceNode::mx, SpaceNode::my, NULL, TH_NODE_CURVING, bNodeLink::tosock, UI_GetThemeValue(), rctf::xmax, and rctf::xmin.
Referenced by cut_links_intersect(), and node_draw_link_bezier().
void node_menus_register (void)
Definition at line 267 of file node_header.c.
References MenuType::draw, MenuType::idname, MenuType::label, MEM_callocN(), mt, node_menu_add(), and WM_menutype_add().
Referenced by ED_spacetype_node().
void node_operatortypes (void)
Definition at line 50 of file node_ops.c.
References NODE_OT_add_file(), NODE_OT_backimage_move(), NODE_OT_backimage_sample(), NODE_OT_backimage_zoom(), NODE_OT_delete(), NODE_OT_delete_reconnect(), NODE_OT_duplicate(), NODE_OT_group_edit(), NODE_OT_group_make(), NODE_OT_group_socket_add(), NODE_OT_group_socket_move_down(), NODE_OT_group_socket_move_up(), NODE_OT_group_socket_remove(), NODE_OT_group_ungroup(), NODE_OT_hide_socket_toggle(), NODE_OT_hide_toggle(), NODE_OT_link(), NODE_OT_link_make(), NODE_OT_link_viewer(), NODE_OT_links_cut(), NODE_OT_links_detach(), NODE_OT_mute_toggle(), NODE_OT_new_node_tree(), NODE_OT_options_toggle(), NODE_OT_output_file_add_socket(), NODE_OT_output_file_remove_active_socket(), NODE_OT_preview_toggle(), NODE_OT_properties(), NODE_OT_read_fullsamplelayers(), NODE_OT_read_renderlayers(), NODE_OT_render_changed(), NODE_OT_resize(), NODE_OT_select(), NODE_OT_select_all(), NODE_OT_select_border(), NODE_OT_select_linked_from(), NODE_OT_select_linked_to(), NODE_OT_select_same_type(), NODE_OT_select_same_type_next(), NODE_OT_select_same_type_prev(), NODE_OT_show_cyclic_dependencies(), NODE_OT_view_all(), and WM_operatortype_append().
Referenced by ED_spacetype_node().
void NODE_OT_add_file (struct wmOperatorType * ot)
Definition at line 3503 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, IMAGEFILE, wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::name, node_add_file_exec(), node_add_file_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string(), wmOperatorType::srna, WM_FILESEL_FILEPATH, and WM_operator_properties_filesel().
Referenced by node_operatortypes().
void NODE_OT_backimage_move (struct wmOperatorType * ot)
Definition at line 1283 of file node_edit.c.
References wmOperatorType::cancel, composite_node_active(), wmOperatorType::description, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, wmOperatorType::poll, snode_bg_viewmove_cancel(), snode_bg_viewmove_invoke(), and snode_bg_viewmove_modal().
Referenced by node_operatortypes().
void NODE_OT_backimage_sample (wmOperatorType * ot)
Definition at line 1480 of file node_edit.c.
References wmOperatorType::cancel, ED_operator_node_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, sample_cancel(), sample_invoke(), and sample_modal().
Referenced by node_operatortypes().
void NODE_OT_backimage_zoom (struct wmOperatorType * ot)
Definition at line 1313 of file node_edit.c.
References backimage_zoom(), composite_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, RNA_def_float(), and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_delete (struct wmOperatorType * ot)
Definition at line 3333 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_delete_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_delete_reconnect (struct wmOperatorType * ot)
Definition at line 3376 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_delete_reconnect_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_duplicate (struct wmOperatorType * ot)
Definition at line 2248 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_duplicate_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_group_edit (struct wmOperatorType * ot)
Definition at line 874 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, node_group_edit_exec(), node_group_edit_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_group_make (struct wmOperatorType * ot)
Definition at line 3069 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_group_make_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_group_socket_add (struct wmOperatorType * ot)
Definition at line 924 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAX_NAME, wmOperatorType::name, node_group_socket_add_exec(), node_socket_type_items, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_string(), SOCK_FLOAT, SOCK_IN, and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_group_socket_move_down (struct wmOperatorType * ot)
Definition at line 1116 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_group_socket_move_down_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_int(), SOCK_IN, and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_group_socket_move_up (struct wmOperatorType * ot)
Definition at line 1046 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_group_socket_move_up_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_int(), SOCK_IN, and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_group_socket_remove (struct wmOperatorType * ot)
Definition at line 976 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_group_socket_remove_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_int(), SOCK_IN, and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_group_ungroup (struct wmOperatorType * ot)
Definition at line 1167 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_group_ungroup_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_hide_socket_toggle (struct wmOperatorType * ot)
Definition at line 3253 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_socket_toggle_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_hide_toggle (struct wmOperatorType * ot)
Definition at line 3140 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_hide_toggle_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_link (struct wmOperatorType * ot)
Definition at line 2572 of file node_edit.c.
References wmOperatorType::cancel, ED_operator_node_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, node_link_cancel(), node_link_invoke(), node_link_modal(), OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_link_make (struct wmOperatorType * ot)
Definition at line 2612 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_make_link_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_link_viewer (struct wmOperatorType * ot)
Definition at line 1761 of file node_edit.c.
References composite_node_active(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_active_link_viewer(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_links_cut (struct wmOperatorType * ot)
Definition at line 2689 of file node_edit.c.
References BC_KNIFECURSOR, wmOperatorType::cancel, cut_links_exec(), ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_COLLECTION, PROP_NONE, RNA_def_int(), RNA_def_property(), RNA_def_property_struct_runtime(), RNA_OperatorMousePath, wmOperatorType::srna, WM_gesture_lines_cancel(), WM_gesture_lines_invoke(), and WM_gesture_lines_modal().
Referenced by node_operatortypes().
void NODE_OT_links_detach (struct wmOperatorType * ot)
Definition at line 2736 of file node_edit.c.
References detach_links_exec(), ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_mute_toggle (struct wmOperatorType * ot)
Definition at line 3291 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_mute_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_new_node_tree (struct wmOperatorType * ot)
Definition at line 3570 of file node_edit.c.
References ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAX_ID_NAME, wmOperatorType::name, new_node_tree_exec(), nodetree_type_items, NTREE_COMPOSIT, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_string(), and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_options_toggle (struct wmOperatorType * ot)
Definition at line 3202 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_options_toggle_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_output_file_add_socket (struct wmOperatorType * ot)
Definition at line 3608 of file node_edit.c.
References composite_node_active(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAX_NAME, wmOperatorType::name, node_output_file_add_socket_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string(), and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_output_file_remove_active_socket (struct wmOperatorType * ot)
Definition at line 3644 of file node_edit.c.
References composite_node_active(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_output_file_remove_active_socket_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_preview_toggle (struct wmOperatorType * ot)
Definition at line 3172 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_preview_toggle_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_properties (struct wmOperatorType * ot)
Definition at line 194 of file node_buttons.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_properties(), node_properties_poll(), and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_read_fullsamplelayers (struct wmOperatorType * ot)
Definition at line 2962 of file node_edit.c.
References composite_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_read_fullsamplelayers_exec(), and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_read_renderlayers (struct wmOperatorType * ot)
Definition at line 2929 of file node_edit.c.
References composite_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_read_renderlayers_exec(), and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_render_changed (struct wmOperatorType * ot)
Definition at line 3010 of file node_edit.c.
References composite_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_render_changed_exec(), and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_resize (struct wmOperatorType * ot)
Definition at line 1591 of file node_edit.c.
References wmOperatorType::cancel, ED_operator_node_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, node_resize_cancel(), node_resize_invoke(), node_resize_modal(), OPTYPE_BLOCKING, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_select (struct wmOperatorType * ot)
Definition at line 524 of file node_select.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, node_select_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_int(), and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_select_all (wmOperatorType * ot)
Definition at line 654 of file node_select.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_select_all_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_select_border (struct wmOperatorType * ot)
Definition at line 603 of file node_select.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, node_border_select_invoke(), node_borderselect_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, TRUE, WM_border_select_cancel(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by node_operatortypes().
void NODE_OT_select_linked_from (wmOperatorType * ot)
Definition at line 738 of file node_select.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_select_linked_from_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_select_linked_to (wmOperatorType * ot)
Definition at line 696 of file node_select.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_select_linked_to_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_select_same_type (struct wmOperatorType * ot)
Definition at line 767 of file node_select.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_select_same_type_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_select_same_type_next (wmOperatorType * ot)
Definition at line 797 of file node_select.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_select_same_type_next_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_select_same_type_prev (wmOperatorType * ot)
Definition at line 824 of file node_select.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_select_same_type_prev_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_show_cyclic_dependencies (struct wmOperatorType * ot)
Definition at line 3404 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_show_cycles_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_view_all (struct wmOperatorType * ot)
Definition at line 120 of file node_state.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_view_all_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
int node_render_changed_exec (bContext * , wmOperator *)
void node_select (struct bNode * node)
Definition at line 176 of file node_select.c.
References bNode::flag, and SELECT.
Referenced by node_add_node(), node_borderselect_exec(), node_duplicate_exec(), node_mouse_select(), node_select_all_exec(), node_select_linked_from_exec(), node_select_linked_to_exec(), node_select_same_type(), node_select_same_type_np(), node_select_single(), node_toggle(), and snode_make_group_editable().
int node_select_same_type (struct SpaceNode * snode)
Definition at line 323 of file node_select.c.
References SpaceNode::edittree, ListBase::first, bNode::flag, bNode::next, node_deselect(), node_select(), bNodeTree::nodes, p, SELECT, and bNode::type.
Referenced by node_select_same_type_exec().
int node_select_same_type_np (struct SpaceNode * snode, int dir)
Definition at line 357 of file node_select.c.
References SpaceNode::edittree, ListBase::first, bNode::flag, bNode::next, node_deselect(), node_select(), bNodeTree::nodes, p, bNode::prev, SELECT, and bNode::type.
Referenced by node_select_same_type_next_exec(), and node_select_same_type_prev_exec().
void node_select_single (struct bContext * C, struct bNode * node)
Definition at line 397 of file node_select.c.
References CTX_data_main(), CTX_wm_space_node(), ED_node_set_active(), SpaceNode::edittree, ListBase::first, NA_SELECTED, NC_NODE, bNode::next, node_deselect(), node_select(), node_sort(), bNodeTree::nodes, NULL, and WM_event_add_notifier().
Referenced by node_toggle_button_cb().
void node_set_hidden_sockets (SpaceNode * snode, bNode * node, int set)
Definition at line 1623 of file node_edit.c.
References SpaceNode::edittree, ListBase::first, bNodeSocket::flag, bNode::inputs, bNodeSocket::link, bNodeSocket::next, nodeCountSocketLinks(), NULL, bNode::outputs, and SOCK_HIDDEN.
Referenced by node_socket_toggle_exec().
void node_socket_circle_draw (struct bNodeTree * ntree, struct bNodeSocket * sock, float size)
void node_socket_deselect (struct bNode * node, struct bNodeSocket * sock, int deselect_node)
Definition at line 211 of file node_select.c.
References ListBase::first, bNode::flag, bNodeSocket::flag, bNode::inputs, bNodeSocket::next, bNode::outputs, and SELECT.
Referenced by node_mouse_select(), and node_socket_toggle().
void node_socket_select (struct bNode * node, struct bNodeSocket * sock)
Definition at line 202 of file node_select.c.
References bNode::flag, bNodeSocket::flag, and SELECT.
Referenced by node_link_init(), node_link_modal(), node_mouse_select(), and node_socket_toggle().
void node_tree_from_ID (ID * id, bNodeTree ** ntree, bNodeTree ** edittree, int * treetype)
Definition at line 437 of file node_edit.c.
References GS, bNode::id, ID_LA, ID_MA, ID_NT, ID_SCE, ID_TE, ID_WO, ID::name, bNode::next, nodeGroupEditGet(), NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, NULL, and bNodeTree::type.
Referenced by ED_node_changed_update(), and snode_set_context().
bNode* node_tree_get_editgroup (bNodeTree * ntree)
Definition at line 263 of file node_edit.c.
References ListBase::first, bNode::next, nodeGroupEditGet(), and bNodeTree::nodes.
Referenced by ED_node_changed_update(), node_add_node(), node_group_ungroup_exec(), node_mouse_groupheader(), outside_group_rect(), and snode_update().
void node_update_default (const struct bContext * C, struct bNodeTree * ntree, struct bNode * node)
void node_update_nodetree (const struct bContext * C, struct bNodeTree * ntree, float offsetx, float offsety)
void snode_autoconnect (SpaceNode * snode, int allow_multiple, int replace)
Definition at line 2033 of file node_edit.c.
References best_socket_input(), best_socket_output(), BLI_addtail(), BLI_countlist(), BLI_freelistN(), BLI_sortlist(), SpaceNode::edittree, ListBase::first, bNode::flag, bNodeSocket::flag, i, bNode::inputs, MEM_callocN(), MEM_freeN(), MEM_mallocN(), bNodeSocket::next, bNode::next, bNodeListItem::next, bNodeListItem::node, NODE_SELECT, bNodeTree::nodes, ntreeUpdateTree(), NULL, SELECT, snode_autoconnect_input(), socket_is_available(), and sort_nodes_locx().
Referenced by node_make_link_exec().
void snode_composite_job (const struct bContext * C, ScrArea * sa)
void snode_dag_update (bContext * C, SpaceNode * snode)
void snode_make_group_editable (SpaceNode * snode, bNode * gnode)
Definition at line 813 of file node_edit.c.
References SpaceNode::edittree, ListBase::first, bNode::next, node_deselect(), node_select(), nodeGetActive(), nodeGroupEditClear(), nodeGroupEditSet(), bNodeTree::nodes, SpaceNode::nodetree, and NULL.
Referenced by node_group_edit_exec(), node_group_ungroup_exec(), and node_mouse_groupheader().
void snode_notify (bContext * C, SpaceNode * snode)
Definition at line 251 of file node_edit.c.
References SpaceNode::id, NA_EDITED, NC_MATERIAL, NC_NODE, NC_SCENE, NC_TEXTURE, ND_NODES, NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, NULL, SpaceNode::treetype, and WM_event_add_notifier().
Referenced by cut_links_exec(), detach_links_exec(), do_node_add(), node_active_link_viewer(), node_add_file_exec(), node_delete_exec(), node_delete_reconnect_exec(), node_duplicate_exec(), node_group_make_exec(), node_group_socket_add_exec(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_socket_remove_exec(), node_group_ungroup_exec(), node_hide_toggle_exec(), node_link_modal(), node_make_link_exec(), node_mute_exec(), node_options_toggle_exec(), node_output_file_add_socket_exec(), node_output_file_remove_active_socket_exec(), node_preview_toggle_exec(), node_read_renderlayers_exec(), node_show_cycles_exec(), and node_socket_toggle_exec().
void snode_set_context (SpaceNode * snode, Scene * scene)
Definition at line 493 of file node_edit.c.
References Object::actcol, Object::data, SpaceNode::edittree, SpaceNode::from, give_current_brush_texture(), give_current_material(), give_current_object_texture(), give_current_world_texture(), bNodeTree::id, Tex::id, Scene::id, World::id, Material::id, Object::id, SpaceNode::id, ToolSettings::imapaint, Object::mode, node_tree_from_ID(), SpaceNode::nodetree, Scene::nodetree, NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, ntreeCompositForceHidden(), NULL, OB_LAMP, OB_MODE_SCULPT, OBACT, ImagePaintSettings::paint, Sculpt::paint, paint_brush(), ToolSettings::sculpt, SpaceNode::shaderfrom, SNODE_SHADER_OBJECT, SNODE_TEX_OBJECT, SNODE_TEX_WORLD, SpaceNode::texfrom, Scene::toolsettings, SpaceNode::treetype, bNodeTree::type, Object::type, and Scene::world.
Referenced by drawnodespace(), ED_node_tree_update(), node_area_refresh(), and node_header_area_draw().
Variable Documentation
enum { ... } eNodeSpace_ButEvents
const char* node_context_dir[]
Definition at line 458 of file space_node.c.