Blender: UnitConverter Class Reference
UnitConverter Class Reference
#include <collada_internal.h>
Public Types
enum UnitSystem { None, Metric, Imperial }
Public Member Functions
UnitConverter ()
void read_asset (const COLLADAFW::FileInfo *asset)
void convertVector3 (COLLADABU::Math::Vector3 &vec, float *v)
UnitConverter::UnitSystem isMetricSystem (void)
float getLinearMeter (void)
void dae_matrix_to_mat4_ (float out[][4], const COLLADABU::Math::Matrix4 &in)
void mat4_to_dae (float out[][4], float in[][4])
void mat4_to_dae_double (double out[][4], float in[][4])
Detailed Description
Definition at line 43 of file collada_internal.h.
Member Enumeration Documentation
enum UnitConverter::UnitSystem
Enumerator:
None
Metric
Imperial
Definition at line 51 of file collada_internal.h.
Constructor & Destructor Documentation
UnitConverter::UnitConverter ()
Definition at line 33 of file collada_internal.cpp.
Member Function Documentation
void UnitConverter::convertVector3 (COLLADABU::Math::Vector3 & vec, float * v)
Definition at line 64 of file collada_internal.cpp.
void UnitConverter::dae_matrix_to_mat4_ (float out[][4], const COLLADABU::Math::Matrix4 & in)
Definition at line 73 of file collada_internal.cpp.
References i.
Referenced by SkinInfo::add_joint(), SkinInfo::borrow_skin_controller_data(), and TransformReader::dae_matrix_to_mat4().
float UnitConverter::getLinearMeter (void)
Definition at line 59 of file collada_internal.cpp.
References Scene::unit.
Referenced by DocumentImporter::finish(), and DocumentImporter::writeLight().
UnitConverter::UnitSystem UnitConverter::isMetricSystem (void)
Definition at line 41 of file collada_internal.cpp.
References Imperial, Metric, None, and Scene::unit.
Referenced by DocumentImporter::finish().
void UnitConverter::mat4_to_dae (float out[][4], float in[][4])
Definition at line 84 of file collada_internal.cpp.
References copy_m4_m4(), and transpose_m4().
Referenced by AnimationExporter::create_4x4_source(), and mat4_to_dae_double().
void UnitConverter::mat4_to_dae_double (double out[][4], float in[][4])
Definition at line 90 of file collada_internal.cpp.
References i, and mat4_to_dae().
Referenced by TransformWriter::add_node_transform(), and TransformWriter::add_node_transform_ob().
void UnitConverter::read_asset (const COLLADAFW::FileInfo * asset)
Definition at line 35 of file collada_internal.cpp.
References Scene::unit.
Referenced by DocumentImporter::writeGlobalAsset().
The documentation for this class was generated from the following files:
collada_internal.h
collada_internal.cpp