Blender: btAabbUtil2.h File Reference
btAabbUtil2.h File Reference
#include "btTransform.h"
#include "btVector3.h"
#include "btMinMax.h"
Defines
#define USE_BANCHLESS 1
Functions
SIMD_FORCE_INLINE void AabbExpand (btVector3 &aabbMin, btVector3 &aabbMax, const btVector3 &expansionMin, const btVector3 &expansionMax)
SIMD_FORCE_INLINE bool TestPointAgainstAabb2 (const btVector3 &aabbMin1, const btVector3 &aabbMax1, const btVector3 &point)
conservative test for overlap between two aabbs
SIMD_FORCE_INLINE bool TestAabbAgainstAabb2 (const btVector3 &aabbMin1, const btVector3 &aabbMax1, const btVector3 &aabbMin2, const btVector3 &aabbMax2)
conservative test for overlap between two aabbs
SIMD_FORCE_INLINE bool TestTriangleAgainstAabb2 (const btVector3 *vertices, const btVector3 &aabbMin, const btVector3 &aabbMax)
conservative test for overlap between triangle and aabb
SIMD_FORCE_INLINE int btOutcode (const btVector3 &p, const btVector3 &halfExtent)
SIMD_FORCE_INLINE bool btRayAabb2 (const btVector3 &rayFrom, const btVector3 &rayInvDirection, const unsigned int raySign[3], const btVector3 bounds[2], btScalar &tmin, btScalar lambda_min, btScalar lambda_max)
SIMD_FORCE_INLINE bool btRayAabb (const btVector3 &rayFrom, const btVector3 &rayTo, const btVector3 &aabbMin, const btVector3 &aabbMax, btScalar &param, btVector3 &normal)
SIMD_FORCE_INLINE void btTransformAabb (const btVector3 &halfExtents, btScalar margin, const btTransform &t, btVector3 &aabbMinOut, btVector3 &aabbMaxOut)
SIMD_FORCE_INLINE void btTransformAabb (const btVector3 &localAabbMin, const btVector3 &localAabbMax, btScalar margin, const btTransform &trans, btVector3 &aabbMinOut, btVector3 &aabbMaxOut)
SIMD_FORCE_INLINE unsigned testQuantizedAabbAgainstQuantizedAabb (const unsigned short int *aabbMin1, const unsigned short int *aabbMax1, const unsigned short int *aabbMin2, const unsigned short int *aabbMax2)
Define Documentation
#define USE_BANCHLESS 1
Definition at line 213 of file btAabbUtil2.h.
Function Documentation
SIMD_FORCE_INLINE void AabbExpand (btVector3 & aabbMin, btVector3 & aabbMax, const btVector3 & expansionMin, const btVector3 & expansionMax)
Definition at line 26 of file btAabbUtil2.h.
Referenced by btCollisionWorld::convexSweepTest().
SIMD_FORCE_INLINE int btOutcode (const btVector3 & p, const btVector3 & halfExtent)
Definition at line 78 of file btAabbUtil2.h.
Referenced by btRayAabb().
SIMD_FORCE_INLINE bool btRayAabb (const btVector3 & rayFrom, const btVector3 & rayTo, const btVector3 & aabbMin, const btVector3 & aabbMax, btScalar & param, btVector3 & normal)
Definition at line 125 of file btAabbUtil2.h.
References btOutcode(), btSetMin(), and i.
Referenced by btCollisionWorld::convexSweepTest(), and btDbvt::rayTest().
SIMD_FORCE_INLINE bool btRayAabb2 (const btVector3 & rayFrom, const btVector3 & rayInvDirection, const unsigned int raySign[3], const btVector3 bounds[2], btScalar & tmin, btScalar lambda_min, btScalar lambda_max)
Definition at line 90 of file btAabbUtil2.h.
Referenced by btDbvt::rayTest(), and btDbvt::rayTestInternal().
SIMD_FORCE_INLINE void btTransformAabb (const btVector3 & halfExtents, btScalar margin, const btTransform & t, btVector3 & aabbMinOut, btVector3 & aabbMaxOut)
Definition at line 182 of file btAabbUtil2.h.
References btMatrix3x3::absolute(), dot(), btTransform::getBasis(), and btTransform::getOrigin().
Referenced by btCylinderShape::getAabb(), btBox2dShape::getAabb(), btBoxShape::getAabb(), btConvexInternalAabbCachingShape::getNonvirtualAabb(), btPolyhedralConvexAabbCachingShape::getNonvirtualAabb(), btCompoundLeafCallback::Process(), and btSoftBodyTriangleCallback::setTimeStepAndCounters().
SIMD_FORCE_INLINE void btTransformAabb (const btVector3 & localAabbMin, const btVector3 & localAabbMax, btScalar margin, const btTransform & trans, btVector3 & aabbMinOut, btVector3 & aabbMaxOut)
Definition at line 195 of file btAabbUtil2.h.
References btMatrix3x3::absolute(), btAssert, dot(), and btTransform::getBasis().
SIMD_FORCE_INLINE bool TestAabbAgainstAabb2 (const btVector3 & aabbMin1, const btVector3 & aabbMax1, const btVector3 & aabbMin2, const btVector3 & aabbMax2)
conservative test for overlap between two aabbs
Definition at line 48 of file btAabbUtil2.h.
Referenced by btSimpleBroadphase::aabbTest(), btAxisSweep3Internal< BP_FP_INT_TYPE >::aabbTest(), btCompoundLeafCallback::ProcessChildShape(), btCompoundCollisionAlgorithm::processCollision(), btMultiSapBroadphase::setAabb(), and btMultiSapBroadphase::testAabbOverlap().
SIMD_FORCE_INLINE bool TestPointAgainstAabb2 (const btVector3 & aabbMin1, const btVector3 & aabbMax1, const btVector3 & point)
conservative test for overlap between two aabbs
Definition at line 36 of file btAabbUtil2.h.
SIMD_FORCE_INLINE unsigned testQuantizedAabbAgainstQuantizedAabb (const unsigned short int * aabbMin1, const unsigned short int * aabbMax1, const unsigned short int * aabbMin2, const unsigned short int * aabbMax2)
Definition at line 216 of file btAabbUtil2.h.
References btSelect().
SIMD_FORCE_INLINE bool TestTriangleAgainstAabb2 (const btVector3 * vertices, const btVector3 & aabbMin, const btVector3 & aabbMax)
conservative test for overlap between triangle and aabb
Definition at line 59 of file btAabbUtil2.h.
References btMax(), and btMin().
Referenced by btTriangleMeshShape::processAllTriangles().