Blender: texture_ocean.c File Reference
texture_ocean.c File Reference
#include <stddef.h>
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "DNA_modifier_types.h"
#include "DNA_object_types.h"
#include "DNA_texture_types.h"
#include "BKE_global.h"
#include "BKE_modifier.h"
#include "BKE_ocean.h"
#include "BKE_utildefines.h"
#include "render_types.h"
#include "RE_shader_ext.h"
#include "texture.h"
Functions
int ocean_texture (Tex *tex, float *texvec, TexResult *texres)
Variables
struct Render R
Function Documentation
int ocean_texture (Tex * tex, float * texvec, TexResult * texres)
Definition at line 57 of file texture_ocean.c.
References OceanModifierData::bakeend, OceanModifierData::bakestart, BKE_ocean_cache_eval_uv(), BKE_ocean_eval_uv(), BKE_ocean_eval_uv_catrom(), BKE_ocean_jminus_to_foam(), BRICONT, BRICONTRGB, OceanModifierData::cached, Render::cfra, CLAMP(), OceanResult::disp, OceanResult::Eminus, eModifierType_Ocean, OceanResult::Eplus, OceanModifierData::flag, OceanResult::foam, OceanModifierData::foam_coverage, G, OceanResult::Jminus, OceanResult::Jplus, MAX2, MOD_OCEAN_GENERATE_NORMALS, modifiers_findByType(), TexResult::nor, OceanResult::normal, normalize_v3_v3(), OceanTex::object, OceanModifierData::ocean, OceanModifierData::oceancache, Tex::ot, OceanTex::output, R, TexResult::ta, TexResult::tb, TEX_INT, TEX_NOR, TEX_OCN_DISPLACEMENT, TEX_OCN_EMINUS, TEX_OCN_EPLUS, TEX_OCN_FOAM, TEX_OCN_JPLUS, TEX_RGB, TexResult::tg, TexResult::tin, TexResult::tr, and TRUE.
Referenced by multitex().
Variable Documentation
struct Render R
Definition at line 126 of file pipeline.c.