Blender: btSubSimplexClosestResult Struct Reference
btSubSimplexClosestResult Struct Reference
#include <btVoronoiSimplexSolver.h>
Public Member Functions
void reset ()
bool isValid ()
void setBarycentricCoordinates (btScalar a=btScalar(0.), btScalar b=btScalar(0.), btScalar c=btScalar(0.), btScalar d=btScalar(0.))
Public Attributes
btVector3 m_closestPointOnSimplex
btUsageBitfield m_usedVertices
btScalar m_barycentricCoords [4]
bool m_degenerate
Detailed Description
Definition at line 56 of file btVoronoiSimplexSolver.h.
Member Function Documentation
bool btSubSimplexClosestResult::isValid () [inline]
Definition at line 72 of file btVoronoiSimplexSolver.h.
References m_barycentricCoords.
Referenced by btVoronoiSimplexSolver::updateClosestVectorAndPoints().
void btSubSimplexClosestResult::reset () [inline]
Definition at line 66 of file btVoronoiSimplexSolver.h.
References m_degenerate, m_usedVertices, btUsageBitfield::reset(), and setBarycentricCoordinates().
Referenced by btVoronoiSimplexSolver::reset(), and btVoronoiSimplexSolver::updateClosestVectorAndPoints().
void btSubSimplexClosestResult::setBarycentricCoordinates (btScalar a = btScalar(0.), btScalar b = btScalar(0.), btScalar c = btScalar(0.), btScalar d = btScalar(0.)) [inline]
Definition at line 82 of file btVoronoiSimplexSolver.h.
References m_barycentricCoords.
Referenced by btVoronoiSimplexSolver::closestPtPointTetrahedron(), btVoronoiSimplexSolver::closestPtPointTriangle(), reset(), and btVoronoiSimplexSolver::updateClosestVectorAndPoints().
Member Data Documentation
btScalar btSubSimplexClosestResult::m_barycentricCoords[4]
Definition at line 63 of file btVoronoiSimplexSolver.h.
Referenced by btVoronoiSimplexSolver::closestPtPointTetrahedron(), isValid(), setBarycentricCoordinates(), and btVoronoiSimplexSolver::updateClosestVectorAndPoints().
btVector3 btSubSimplexClosestResult::m_closestPointOnSimplex
Definition at line 58 of file btVoronoiSimplexSolver.h.
Referenced by btVoronoiSimplexSolver::closestPtPointTetrahedron(), and btVoronoiSimplexSolver::closestPtPointTriangle().
bool btSubSimplexClosestResult::m_degenerate
Definition at line 64 of file btVoronoiSimplexSolver.h.
Referenced by btVoronoiSimplexSolver::closestPtPointTetrahedron(), reset(), and btVoronoiSimplexSolver::updateClosestVectorAndPoints().
btUsageBitfield btSubSimplexClosestResult::m_usedVertices
Definition at line 62 of file btVoronoiSimplexSolver.h.
Referenced by btVoronoiSimplexSolver::closestPtPointTetrahedron(), btVoronoiSimplexSolver::closestPtPointTriangle(), reset(), and btVoronoiSimplexSolver::updateClosestVectorAndPoints().
The documentation for this struct was generated from the following file:
btVoronoiSimplexSolver.h