Blender: graph_intern.h File Reference
graph_intern.h File Reference
graph editor
Enumerations
enum { GRAPHKEYS_LRSEL_TEST = 0, GRAPHKEYS_LRSEL_LEFT, GRAPHKEYS_LRSEL_RIGHT }
enum { GRAPHKEYS_COLUMNSEL_KEYS = 0, GRAPHKEYS_COLUMNSEL_CFRA, GRAPHKEYS_COLUMNSEL_MARKERS_COLUMN, GRAPHKEYS_COLUMNSEL_MARKERS_BETWEEN }
enum {
GRAPHKEYS_SNAP_CFRA = 1, GRAPHKEYS_SNAP_NEAREST_FRAME, GRAPHKEYS_SNAP_NEAREST_SECOND, GRAPHKEYS_SNAP_NEAREST_MARKER,
GRAPHKEYS_SNAP_HORIZONTAL, GRAPHKEYS_SNAP_VALUE
}
enum {
GRAPHKEYS_MIRROR_CFRA = 1, GRAPHKEYS_MIRROR_YAXIS, GRAPHKEYS_MIRROR_XAXIS, GRAPHKEYS_MIRROR_MARKER,
GRAPHKEYS_MIRROR_VALUE
}
Functions
struct ARegion * graph_has_buttons_region (struct ScrArea *sa)
void graph_draw_channel_names (struct bContext *C, struct bAnimContext *ac, struct ARegion *ar)
void graph_draw_curves (struct bAnimContext *ac, struct SpaceIpo *sipo, struct ARegion *ar, struct View2DGrid *grid, short sel)
void graph_draw_ghost_curves (struct bAnimContext *ac, struct SpaceIpo *sipo, struct ARegion *ar)
void GRAPH_OT_select_all_toggle (struct wmOperatorType *ot)
void GRAPH_OT_select_border (struct wmOperatorType *ot)
void GRAPH_OT_select_column (struct wmOperatorType *ot)
void GRAPH_OT_select_linked (struct wmOperatorType *ot)
void GRAPH_OT_select_more (struct wmOperatorType *ot)
void GRAPH_OT_select_less (struct wmOperatorType *ot)
void GRAPH_OT_select_leftright (struct wmOperatorType *ot)
void GRAPH_OT_clickselect (struct wmOperatorType *ot)
void get_graph_keyframe_extents (struct bAnimContext *ac, float *xmin, float *xmax, float *ymin, float *ymax, const short do_selected)
void GRAPH_OT_previewrange_set (struct wmOperatorType *ot)
void GRAPH_OT_view_all (struct wmOperatorType *ot)
void GRAPH_OT_view_selected (struct wmOperatorType *ot)
void GRAPH_OT_click_insert (struct wmOperatorType *ot)
void GRAPH_OT_keyframe_insert (struct wmOperatorType *ot)
void GRAPH_OT_copy (struct wmOperatorType *ot)
void GRAPH_OT_paste (struct wmOperatorType *ot)
void GRAPH_OT_duplicate (struct wmOperatorType *ot)
void GRAPH_OT_delete (struct wmOperatorType *ot)
void GRAPH_OT_clean (struct wmOperatorType *ot)
void GRAPH_OT_sample (struct wmOperatorType *ot)
void GRAPH_OT_bake (struct wmOperatorType *ot)
void GRAPH_OT_sound_bake (struct wmOperatorType *ot)
void GRAPH_OT_smooth (struct wmOperatorType *ot)
void GRAPH_OT_euler_filter (struct wmOperatorType *ot)
void GRAPH_OT_handle_type (struct wmOperatorType *ot)
void GRAPH_OT_interpolation_type (struct wmOperatorType *ot)
void GRAPH_OT_extrapolation_type (struct wmOperatorType *ot)
void GRAPH_OT_frame_jump (struct wmOperatorType *ot)
void GRAPH_OT_snap (struct wmOperatorType *ot)
void GRAPH_OT_mirror (struct wmOperatorType *ot)
void GRAPH_OT_fmodifier_add (struct wmOperatorType *ot)
void GRAPH_OT_fmodifier_copy (struct wmOperatorType *ot)
void GRAPH_OT_fmodifier_paste (struct wmOperatorType *ot)
void GRAPH_OT_ghost_curves_create (struct wmOperatorType *ot)
void GRAPH_OT_ghost_curves_clear (struct wmOperatorType *ot)
void GRAPH_OT_properties (struct wmOperatorType *ot)
void graph_buttons_register (struct ARegionType *art)
struct bAnimListElem * get_active_fcurve_channel (struct bAnimContext *ac)
int graphop_visible_keyframes_poll (struct bContext *C)
int graphop_editable_keyframes_poll (struct bContext *C)
int graphop_active_fcurve_poll (struct bContext *C)
int graphop_selected_fcurve_poll (struct bContext *C)
void graphedit_keymap (struct wmKeyConfig *keyconf)
void graphedit_operatortypes (void)
Variables
enum { ... } eGraphKeys_LeftRightSelect_Mode
enum { ... } eGraphKeys_ColumnSelect_Mode
enum { ... } eGraphKeys_Snap_Mode
enum { ... } eGraphKeys_Mirror_Mode
Detailed Description
Definition in file graph_intern.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
GRAPHKEYS_LRSEL_TEST
GRAPHKEYS_LRSEL_LEFT
GRAPHKEYS_LRSEL_RIGHT
Definition at line 72 of file graph_intern.h.
anonymous enum
Enumerator:
GRAPHKEYS_COLUMNSEL_KEYS
GRAPHKEYS_COLUMNSEL_CFRA
GRAPHKEYS_COLUMNSEL_MARKERS_COLUMN
GRAPHKEYS_COLUMNSEL_MARKERS_BETWEEN
Definition at line 79 of file graph_intern.h.
anonymous enum
Enumerator:
GRAPHKEYS_SNAP_CFRA
GRAPHKEYS_SNAP_NEAREST_FRAME
GRAPHKEYS_SNAP_NEAREST_SECOND
GRAPHKEYS_SNAP_NEAREST_MARKER
GRAPHKEYS_SNAP_HORIZONTAL
GRAPHKEYS_SNAP_VALUE
Definition at line 121 of file graph_intern.h.
anonymous enum
Enumerator:
GRAPHKEYS_MIRROR_CFRA
GRAPHKEYS_MIRROR_YAXIS
GRAPHKEYS_MIRROR_XAXIS
GRAPHKEYS_MIRROR_MARKER
GRAPHKEYS_MIRROR_VALUE
Definition at line 133 of file graph_intern.h.
Function Documentation
struct bAnimListElem* get_active_fcurve_channel (struct bAnimContext * ac) [read]
Definition at line 68 of file graph_utils.c.
References ANIM_animdata_filter(), ANIMFILTER_ACTIVE, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, BLI_freelistN(), BLI_remlink(), bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, and NULL.
Referenced by graph_fmodifier_copy_exec(), graph_panel_context(), graphkeys_click_insert_exec(), and graphop_active_fcurve_poll().
void get_graph_keyframe_extents (struct bAnimContext * ac, float * xmin, float * xmax, float * ymin, float * ymax, const short do_selected)
Definition at line 86 of file graph_edit.c.
References ANIM_animdata_filter(), ANIM_nla_mapping_get(), ANIM_unit_mapping_get_factor(), ANIMFILTER_CURVE_VISIBLE, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_NODUPLIS, BKE_nla_tweakedit_remap(), BLI_freelistN(), calc_fcurve_bounds(), bAnimContext::data, bAnimContext::datatype, RenderData::efra, fabsf, filter(), ListBase::first, bAnimListElem::id, if(), bAnimListElem::key_data, bAnimListElem::next, NLATIME_CONVERT_MAP, NULL, Scene::r, bAnimContext::scene, and RenderData::sfra.
Referenced by graph_main_area_draw(), graphkeys_previewrange_exec(), and graphkeys_viewall().
void graph_buttons_register (struct ARegionType * art)
Definition at line 788 of file graph_buttons.c.
References BLI_addtail(), PanelType::draw, PanelType::flag, graph_panel_drivers(), graph_panel_drivers_poll(), graph_panel_key_properties(), graph_panel_modifiers(), graph_panel_poll(), graph_panel_properties(), graph_panel_view(), PanelType::idname, PanelType::label, MEM_callocN(), N_, ARegionType::paneltypes, PNL_DEFAULT_CLOSED, and PanelType::poll.
Referenced by ED_spacetype_ipo().
void graph_draw_channel_names (struct bContext * C, struct bAnimContext * ac, struct ARegion * ar)
Definition at line 950 of file graph_draw.c.
References ACHANNEL_FIRST, ACHANNEL_HEIGHT, ACHANNEL_HEIGHT_HALF, ACHANNEL_STEP, ANIM_animdata_filter(), ANIM_channel_draw(), ANIM_channel_draw_widgets(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, BLI_freelistN(), View2D::cur, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, i, IN_RANGE, bAnimListElem::next, NULL, UI_EMBOSS, UI_view2d_totRect_set(), uiBeginBlock(), uiDrawBlock(), uiEndBlock(), ARegion::v2d, ARegion::winx, rctf::ymax, and rctf::ymin.
Referenced by graph_channel_area_draw().
void graph_draw_curves (struct bAnimContext * ac, struct SpaceIpo * sipo, struct ARegion * ar, struct View2DGrid * grid, short sel)
Definition at line 815 of file graph_draw.c.
References AGRP_MUTED, AGRP_PROTECTED, ANIM_animdata_filter(), ANIM_nla_mapping_apply_fcurve(), ANIM_nla_mapping_get(), ANIM_unit_mapping_apply_fcurve(), ANIM_UNITCONV_RESTORE, ANIMFILTER_CURVE_VISIBLE, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_SEL, ANIMFILTER_UNSEL, FCurve::bezt, BLI_freelistN(), FCurve::color, bAnimContext::data, bAnimContext::datatype, draw_fcurve_curve(), draw_fcurve_curve_bezts(), draw_fcurve_curve_samples(), draw_fcurve_handles(), draw_fcurve_handles_check(), draw_fcurve_modifier_controls_envelope(), draw_fcurve_samples(), draw_fcurve_vertices(), FCURVE_ACTIVE, fcurve_are_keyframes_usable(), fcurve_display_alpha(), FCURVE_INT_VALUES, FCURVE_MUTED, FCURVE_PROTECTED, FCURVE_SELECTED, filter(), find_active_fmodifier(), ListBase::first, SpaceIpo::flag, FCurve::flag, bActionGroup::flag, FMODIFIER_TYPE_ENVELOPE, FCurve::fpt, FCurve::grp, bAnimListElem::id, bAnimListElem::key_data, FCurve::modifiers, bAnimListElem::next, NULL, bAnimContext::scene, setlinestyle(), SIPO_BEAUTYDRAW_OFF, SIPO_SELCUVERTSONLY, SIPO_SELVHANDLESONLY, TH_HEADER, FCurve::totvert, UI_ThemeColorShade(), and ARegion::v2d.
Referenced by graph_main_area_draw().
void graph_draw_ghost_curves (struct bAnimContext * ac, struct SpaceIpo * sipo, struct ARegion * ar)
Definition at line 780 of file graph_draw.c.
References FCurve::color, draw_fcurve_curve_samples(), ListBase::first, SpaceIpo::flag, SpaceIpo::ghostCurves, FCurve::next, NULL, setlinestyle(), SIPO_BEAUTYDRAW_OFF, and ARegion::v2d.
Referenced by graph_main_area_draw().
struct ARegion* graph_has_buttons_region (struct ScrArea * sa) [read]
Definition at line 68 of file space_graph.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_RIGHT, RGN_FLAG_HIDDEN, RGN_TYPE_UI, and RGN_TYPE_WINDOW.
Referenced by graph_properties().
void GRAPH_OT_bake (struct wmOperatorType * ot)
Definition at line 1033 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_bake_exec(), graphop_selected_fcurve_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by graphedit_operatortypes().
void GRAPH_OT_clean (struct wmOperatorType * ot)
Definition at line 950 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, graphkeys_clean_exec(), graphop_editable_keyframes_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_float(), and wmOperatorType::srna.
Referenced by graphedit_operatortypes().
void GRAPH_OT_click_insert (struct wmOperatorType * ot)
Definition at line 621 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, graphkeys_click_insert_exec(), graphkeys_click_insert_invoke(), graphop_active_fcurve_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), and wmOperatorType::srna.
Referenced by graphedit_operatortypes().
void GRAPH_OT_clickselect (struct wmOperatorType * ot)
Definition at line 1334 of file graph_select.c.
References wmOperatorType::description, graphkeys_clickselect_invoke(), graphop_visible_keyframes_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by graphedit_operatortypes().
void GRAPH_OT_copy (struct wmOperatorType * ot)
Definition at line 704 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_copy_exec(), graphop_editable_keyframes_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_delete (struct wmOperatorType * ot)
Definition at line 888 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_delete_exec(), graphop_editable_keyframes_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by graphedit_operatortypes().
void GRAPH_OT_duplicate (struct wmOperatorType * ot)
Definition at line 818 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_duplicate_exec(), graphkeys_duplicate_invoke(), graphop_editable_keyframes_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, TFM_TRANSLATION, and transform_mode_types.
Referenced by graphedit_operatortypes().
void GRAPH_OT_euler_filter (struct wmOperatorType * ot)
Definition at line 1700 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_euler_filter_exec(), graphop_editable_keyframes_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_extrapolation_type (struct wmOperatorType * ot)
Definition at line 1360 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_expo_exec(), graphop_editable_keyframes_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by graphedit_operatortypes().
void GRAPH_OT_fmodifier_add (struct wmOperatorType * ot)
Definition at line 2155 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, fmodifier_type_items, graph_fmodifier_add_exec(), graph_fmodifier_add_invoke(), graphop_selected_fcurve_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), and wmOperatorType::srna.
Referenced by graphedit_operatortypes().
void GRAPH_OT_fmodifier_copy (struct wmOperatorType * ot)
Definition at line 2213 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graph_fmodifier_copy_exec(), graphop_active_fcurve_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_fmodifier_paste (struct wmOperatorType * ot)
Definition at line 2275 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graph_fmodifier_paste_exec(), graphop_active_fcurve_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_frame_jump (struct wmOperatorType * ot)
Definition at line 1774 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_framejump_exec(), graphop_visible_keyframes_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_ghost_curves_clear (struct wmOperatorType * ot)
Definition at line 419 of file graph_edit.c.
References wmOperatorType::description, ED_operator_graphedit_active(), wmOperatorType::exec, wmOperatorType::flag, graphkeys_clear_ghostcurves_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_ghost_curves_create (struct wmOperatorType * ot)
Definition at line 376 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_create_ghostcurves_exec(), graphop_visible_keyframes_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_handle_type (struct wmOperatorType * ot)
Definition at line 1506 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_handletype_exec(), graphop_editable_keyframes_poll(), wmOperatorType::idname, wmOperatorType::invoke, keyframe_handle_type_items, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by graphedit_operatortypes().
void GRAPH_OT_interpolation_type (struct wmOperatorType * ot)
Definition at line 1429 of file graph_edit.c.
References beztriple_interpolation_mode_items, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_ipo_exec(), graphop_editable_keyframes_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by graphedit_operatortypes().
void GRAPH_OT_keyframe_insert (struct wmOperatorType * ot)
Definition at line 514 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_insertkey_exec(), graphop_editable_keyframes_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by graphedit_operatortypes().
void GRAPH_OT_mirror (struct wmOperatorType * ot)
Definition at line 1996 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_mirror_exec(), graphop_editable_keyframes_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by graphedit_operatortypes().
void GRAPH_OT_paste (struct wmOperatorType * ot)
Definition at line 749 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_paste_exec(), graphop_editable_keyframes_poll(), wmOperatorType::idname, keyframe_paste_merge_items, KEYFRAME_PASTE_MERGE_MIX, KEYFRAME_PASTE_OFFSET_CFRA_START, keyframe_paste_offset_items, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by graphedit_operatortypes().
void GRAPH_OT_previewrange_set (struct wmOperatorType * ot)
Definition at line 184 of file graph_edit.c.
References wmOperatorType::description, ED_operator_graphedit_active(), wmOperatorType::exec, wmOperatorType::flag, graphkeys_previewrange_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_properties (struct wmOperatorType * ot)
Definition at line 840 of file graph_buttons.c.
References wmOperatorType::description, ED_operator_graphedit_active(), wmOperatorType::exec, wmOperatorType::flag, graph_properties(), wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_sample (struct wmOperatorType * ot)
Definition at line 1251 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_sample_exec(), graphop_editable_keyframes_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_select_all_toggle (struct wmOperatorType * ot)
Definition at line 169 of file graph_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_deselectall_exec(), graphop_visible_keyframes_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by graphedit_operatortypes().
void GRAPH_OT_select_border (struct wmOperatorType * ot)
Definition at line 348 of file graph_select.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_borderselect_exec(), graphop_visible_keyframes_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), wmOperatorType::srna, TRUE, WM_border_select_cancel(), WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by graphedit_operatortypes().
void GRAPH_OT_select_column (struct wmOperatorType * ot)
Definition at line 538 of file graph_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_columnselect_exec(), graphop_visible_keyframes_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), and wmOperatorType::srna.
Referenced by graphedit_operatortypes().
void GRAPH_OT_select_leftright (struct wmOperatorType * ot)
Definition at line 849 of file graph_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, GRAPHKEYS_LRSEL_TEST, graphkeys_select_leftright_exec(), graphkeys_select_leftright_invoke(), graphop_visible_keyframes_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), and wmOperatorType::srna.
Referenced by graphedit_operatortypes().
void GRAPH_OT_select_less (struct wmOperatorType * ot)
Definition at line 708 of file graph_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_select_less_exec(), graphop_visible_keyframes_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_select_linked (struct wmOperatorType * ot)
Definition at line 596 of file graph_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_select_linked_exec(), graphop_visible_keyframes_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_select_more (struct wmOperatorType * ot)
Definition at line 674 of file graph_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_select_more_exec(), graphop_visible_keyframes_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_smooth (struct wmOperatorType * ot)
Definition at line 2051 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_smooth_exec(), graphop_editable_keyframes_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_snap (struct wmOperatorType * ot)
Definition at line 1878 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, graphkeys_snap_exec(), graphop_editable_keyframes_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by graphedit_operatortypes().
void GRAPH_OT_sound_bake (struct wmOperatorType * ot)
Definition at line 1177 of file graph_edit.c.
References wmOperatorType::description, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, graphkeys_sound_bake_exec(), graphkeys_sound_bake_invoke(), graphop_selected_fcurve_poll(), wmOperatorType::idname, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float(), SOUNDFILE, wmOperatorType::srna, WM_FILESEL_FILEPATH, and WM_operator_properties_filesel().
Referenced by graphedit_operatortypes().
void GRAPH_OT_view_all (struct wmOperatorType * ot)
Definition at line 246 of file graph_edit.c.
References wmOperatorType::description, ED_operator_graphedit_active(), wmOperatorType::exec, wmOperatorType::flag, graphkeys_viewall_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void GRAPH_OT_view_selected (struct wmOperatorType * ot)
Definition at line 261 of file graph_edit.c.
References wmOperatorType::description, ED_operator_graphedit_active(), wmOperatorType::exec, wmOperatorType::flag, graphkeys_view_selected_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by graphedit_operatortypes().
void graphedit_keymap (struct wmKeyConfig * keyconf)
Definition at line 404 of file graph_ops.c.
References EKEY, graphedit_keymap_keyframes(), KM_PRESS, KM_SHIFT, NKEY, SPACE_IPO, WM_keymap_add_item(), and WM_keymap_find().
Referenced by ED_spacetype_ipo().
void graphedit_operatortypes (void)
Definition at line 187 of file graph_ops.c.
References GRAPH_OT_bake(), GRAPH_OT_clean(), GRAPH_OT_click_insert(), GRAPH_OT_clickselect(), GRAPH_OT_copy(), GRAPH_OT_cursor_set(), GRAPH_OT_delete(), GRAPH_OT_duplicate(), GRAPH_OT_euler_filter(), GRAPH_OT_extrapolation_type(), GRAPH_OT_fmodifier_add(), GRAPH_OT_fmodifier_copy(), GRAPH_OT_fmodifier_paste(), GRAPH_OT_frame_jump(), GRAPH_OT_ghost_curves_clear(), GRAPH_OT_ghost_curves_create(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_paste(), GRAPH_OT_previewrange_set(), GRAPH_OT_properties(), GRAPH_OT_sample(), GRAPH_OT_select_all_toggle(), GRAPH_OT_select_border(), GRAPH_OT_select_column(), GRAPH_OT_select_leftright(), GRAPH_OT_select_less(), GRAPH_OT_select_linked(), GRAPH_OT_select_more(), GRAPH_OT_smooth(), GRAPH_OT_snap(), GRAPH_OT_sound_bake(), GRAPH_OT_view_all(), GRAPH_OT_view_selected(), and WM_operatortype_append().
Referenced by ED_spacetype_ipo().
int graphop_active_fcurve_poll (struct bContext * C)
Definition at line 194 of file graph_utils.c.
References ANIM_animdata_get_context(), ANIMTYPE_FCURVE, CTX_wm_area(), bAnimListElem::data, tNearestVertInfo::fcu, FCURVE_VISIBLE, FCurve::flag, get_active_fcurve_channel(), MEM_freeN(), NULL, SPACE_IPO, ScrArea::spacetype, and bAnimListElem::type.
Referenced by GRAPH_OT_click_insert(), GRAPH_OT_fmodifier_copy(), and GRAPH_OT_fmodifier_paste().
int graphop_editable_keyframes_poll (struct bContext * C)
Definition at line 144 of file graph_utils.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_CURVE_VISIBLE, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, FCurve::bezt, BLI_freelistN(), CTX_wm_area(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, tNearestVertInfo::fcu, fcurve_is_keyframable(), filter(), ListBase::first, if(), bAnimListElem::next, NULL, SPACE_IPO, and ScrArea::spacetype.
Referenced by GRAPH_OT_clean(), GRAPH_OT_copy(), GRAPH_OT_delete(), GRAPH_OT_duplicate(), GRAPH_OT_euler_filter(), GRAPH_OT_extrapolation_type(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_paste(), GRAPH_OT_sample(), GRAPH_OT_smooth(), and GRAPH_OT_snap().
int graphop_selected_fcurve_poll (struct bContext * C)
Definition at line 229 of file graph_utils.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_SEL, BLI_freelistN(), CTX_wm_area(), bAnimContext::data, bAnimContext::datatype, filter(), NULL, SPACE_IPO, and ScrArea::spacetype.
Referenced by GRAPH_OT_bake(), GRAPH_OT_fmodifier_add(), and GRAPH_OT_sound_bake().
int graphop_visible_keyframes_poll (struct bContext * C)
Definition at line 95 of file graph_utils.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_CURVE_VISIBLE, ANIMFILTER_DATA_VISIBLE, FCurve::bezt, BLI_freelistN(), CTX_wm_area(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, tNearestVertInfo::fcu, fcurve_are_keyframes_usable(), filter(), ListBase::first, if(), bAnimListElem::next, NULL, SPACE_IPO, and ScrArea::spacetype.
Referenced by GRAPH_OT_clickselect(), GRAPH_OT_frame_jump(), GRAPH_OT_ghost_curves_create(), GRAPH_OT_select_all_toggle(), GRAPH_OT_select_border(), GRAPH_OT_select_column(), GRAPH_OT_select_leftright(), GRAPH_OT_select_less(), GRAPH_OT_select_linked(), and GRAPH_OT_select_more().
Variable Documentation
enum { ... } eGraphKeys_ColumnSelect_Mode
enum { ... } eGraphKeys_LeftRightSelect_Mode
enum { ... } eGraphKeys_Mirror_Mode
enum { ... } eGraphKeys_Snap_Mode