Blender: text_header.c File Reference
text_header.c File Reference
text editor
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include "DNA_windowmanager_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "ED_screen.h"
#include "WM_types.h"
#include "text_intern.h"
Defines
#define HEADER_PATH_MAX 260
Functions
static ARegion * text_has_properties_region (ScrArea *sa)
static int text_properties_poll (bContext *C)
static int text_properties_exec (bContext *C, wmOperator *UNUSED(op))
void TEXT_OT_properties (wmOperatorType *ot)
Detailed Description
Definition in file text_header.c.
Define Documentation
#define HEADER_PATH_MAX 260
Definition at line 71 of file text_header.c.
Function Documentation
static ARegion* text_has_properties_region (ScrArea * sa) [static]
Definition at line 77 of file text_header.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_LEFT, RGN_FLAG_HIDDEN, RGN_TYPE_HEADER, and RGN_TYPE_UI.
Referenced by text_properties_exec().
void TEXT_OT_properties (wmOperatorType * ot)
Definition at line 117 of file text_header.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_properties_exec(), and text_properties_poll().
Referenced by text_operatortypes().
static int text_properties_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 106 of file text_header.c.
References CTX_wm_area(), ED_region_toggle_hidden(), OPERATOR_FINISHED, and text_has_properties_region().
Referenced by TEXT_OT_properties().
static int text_properties_poll (bContext * C) [static]
Definition at line 101 of file text_header.c.
References CTX_wm_space_text(), and NULL.
Referenced by TEXT_OT_properties().