Blender: TNT::Fortran_Array2D< T > Class Template Reference
TNT::Fortran_Array2D< T > Class Template Reference
#include <tnt_fortran_array2d.h>
Public Types
typedef T value_type
Public Member Functions
Fortran_Array2D ()
Fortran_Array2D (int m, int n)
Fortran_Array2D (int m, int n, T *a)
Fortran_Array2D (int m, int n, const T &a)
Fortran_Array2D (const Fortran_Array2D &A)
Fortran_Array2D & operator= (const T &a)
Fortran_Array2D & operator= (const Fortran_Array2D &A)
Fortran_Array2D & ref (const Fortran_Array2D &A)
Fortran_Array2D copy () const
Fortran_Array2D & inject (const Fortran_Array2D &A)
T & operator() (int i, int j)
const T & operator() (int i, int j) const
int dim1 () const
int dim2 () const
~Fortran_Array2D ()
int ref_count () const
Detailed Description
template<class T>
class TNT::Fortran_Array2D< T >
Definition at line 41 of file tnt_fortran_array2d.h.
Member Typedef Documentation
template<class T> typedef T TNT::Fortran_Array2D< T >::value_type
Definition at line 58 of file tnt_fortran_array2d.h.
Constructor & Destructor Documentation
template<class T > TNT::Fortran_Array2D< T >::Fortran_Array2D ()
Definition at line 83 of file tnt_fortran_array2d.h.
template<class T > TNT::Fortran_Array2D< T >::Fortran_Array2D (int m, int n)
Definition at line 93 of file tnt_fortran_array2d.h.
template<class T > TNT::Fortran_Array2D< T >::Fortran_Array2D (int m, int n, T * a)
Definition at line 105 of file tnt_fortran_array2d.h.
template<class T > TNT::Fortran_Array2D< T >::Fortran_Array2D (int m, int n, const T & a)
Definition at line 97 of file tnt_fortran_array2d.h.
template<class T > TNT::Fortran_Array2D< T >::Fortran_Array2D (const Fortran_Array2D< T > & A) [inline]
Definition at line 87 of file tnt_fortran_array2d.h.
template<class T > TNT::Fortran_Array2D< T >::~Fortran_Array2D ()
Definition at line 196 of file tnt_fortran_array2d.h.
Member Function Documentation
template<class T > Fortran_Array2D< T > TNT::Fortran_Array2D< T >::copy () const
Definition at line 148 of file tnt_fortran_array2d.h.
References B, and TNT::Fortran_Array2D< T >::inject().
template<class T > int TNT::Fortran_Array2D< T >::dim1 () const [inline]
Definition at line 189 of file tnt_fortran_array2d.h.
Referenced by TNT::operator*(), TNT::operator*=(), TNT::operator+(), TNT::operator+=(), TNT::operator-(), TNT::operator-=(), TNT::operator/(), and TNT::operator/=().
template<class T > int TNT::Fortran_Array2D< T >::dim2 () const [inline]
Definition at line 192 of file tnt_fortran_array2d.h.
Referenced by TNT::operator*(), TNT::operator*=(), TNT::operator+(), TNT::operator+=(), TNT::operator-(), TNT::operator-=(), TNT::operator/(), and TNT::operator/=().
template<class T > Fortran_Array2D< T > & TNT::Fortran_Array2D< T >::inject (const Fortran_Array2D< T > & A)
Definition at line 159 of file tnt_fortran_array2d.h.
Referenced by TNT::Fortran_Array2D< T >::copy().
template<class T > const T & TNT::Fortran_Array2D< T >::operator() (int i, int j) const [inline]
Definition at line 126 of file tnt_fortran_array2d.h.
References assert.
template<class T > T & TNT::Fortran_Array2D< T >::operator() (int i, int j) [inline]
Definition at line 112 of file tnt_fortran_array2d.h.
References assert.
template<class T > Fortran_Array2D< T > & TNT::Fortran_Array2D< T >::operator= (const T & a) [inline]
Definition at line 141 of file tnt_fortran_array2d.h.
template<class T > Fortran_Array2D< T > & TNT::Fortran_Array2D< T >::operator= (const Fortran_Array2D< T > & A) [inline]
Definition at line 183 of file tnt_fortran_array2d.h.
template<class T > Fortran_Array2D< T > & TNT::Fortran_Array2D< T >::ref (const Fortran_Array2D< T > & A) [inline]
Definition at line 170 of file tnt_fortran_array2d.h.
template<class T > int TNT::Fortran_Array2D< T >::ref_count () const [inline]
Definition at line 201 of file tnt_fortran_array2d.h.
The documentation for this class was generated from the following file:
tnt_fortran_array2d.h