Blender: rna_pose_api.c File Reference
rna_pose_api.c File Reference
RNA
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include "RNA_define.h"
#include "DNA_object_types.h"
Functions
void RNA_api_pose (StructRNA *srna)
void RNA_api_pose_channel (StructRNA *srna)
Detailed Description
Definition in file rna_pose_api.c.
Function Documentation
void RNA_api_pose (StructRNA * srna)
Definition at line 61 of file rna_pose_api.c.
void RNA_api_pose_channel (StructRNA * srna)
Definition at line 67 of file rna_pose_api.c.
References FLT_MAX, NULL, PROP_REQUIRED, RNA_def_float(), RNA_def_float_vector_xyz(), RNA_def_function(), RNA_def_function_return(), RNA_def_function_ui_description(), and RNA_def_property_flag().
Referenced by rna_def_pose_channel().