Blender: iTaSC Namespace Reference
iTaSC Namespace Reference
Classes
class Armature
struct Timestamp
class Cache
struct CacheEntry
struct CacheChannel
struct CacheBlock
struct CacheItem
struct CacheBufferHeader
struct CacheBuffer
struct ConstraintSingleValue
struct ConstraintValues
class ConstraintSet
class ControlledObject
class CopyPose
class Distance
class Range
class FixedObject
class MovingFrame
class Object
class SceneLock
class Scene
class Solver
class UncontrolledObject
class WDLSSolver
class WorldObject
class WSDLSSolver
Typedefs
typedef unsigned int CacheTS
typedef bool(* ConstraintCallback)(const Timestamp &timestamp, struct ConstraintValues *const _values, unsigned int _nvalues, void *_param)
typedef bool(* MovingFrameCallback)(const Timestamp &timestamp, const Frame &_current, Frame &_next, void *param)
Enumerations
enum ConstraintAction {
ACT_NONE = 0, ACT_VALUE = 1, ACT_VELOCITY = 2, ACT_TOLERANCE = 4,
ACT_FEEDBACK = 8, ACT_ALPHA = 16
}
Functions
void setCacheTimestamp (Timestamp &timestamp)
template<typename MatrixType >
Eigen::Block< MatrixType > project (MatrixType &m, Range r)
template<typename MatrixType >
Eigen::Block< MatrixType > project (MatrixType &m, Range r, Range c)
template<typename Derived >
static int changeBase (Eigen::MatrixBase< Derived > &J, const Frame &T)
static int changeBase (const u_matrix &J_in, const Frame &T, u_matrix &J_out)
static int changeBase (const ublas::matrix_range< u_matrix > &J_in, const Frame &T, ublas::matrix_range< u_matrix > &J_out)
Variables
static const unsigned int constraintCacheSize = 5
const unsigned int maxPoseCacheSize = (2*(3+3*2))
static const unsigned int distanceCacheSize = sizeof(double)*5 + sizeof(e_scalar)*6
const Frame F_identity
static const unsigned int frameCacheSize = (sizeof(((Frame*)0)->p.data)+sizeof(((Frame*)0)->M.data))/sizeof(double)
Typedef Documentation
typedef unsigned int iTaSC::CacheTS
Definition at line 32 of file Cache.hpp.
typedef bool(* iTaSC::ConstraintCallback)(const Timestamp &timestamp, struct ConstraintValues *const _values, unsigned int _nvalues, void *_param)
Definition at line 49 of file ConstraintSet.hpp.
typedef bool(* iTaSC::MovingFrameCallback)(const Timestamp &timestamp, const Frame &_current, Frame &_next, void *param)
Definition at line 17 of file MovingFrame.hpp.
Enumeration Type Documentation
enum iTaSC::ConstraintAction
Enumerator:
ACT_NONE
ACT_VALUE
ACT_VELOCITY
ACT_TOLERANCE
ACT_FEEDBACK
ACT_ALPHA
Definition at line 18 of file ConstraintSet.hpp.
Function Documentation
template<typename Derived > static int iTaSC::changeBase (Eigen::MatrixBase< Derived > & J, const Frame & T) [inline, static]
Definition at line 67 of file eigen_types.hpp.
References e_scalar, and i.
Referenced by iTaSC::Scene::update().
static int iTaSC::changeBase (const u_matrix & J_in, const Frame & T, u_matrix & J_out) [inline, static]
Definition at line 48 of file ublas_types.hpp.
References i.
static int iTaSC::changeBase (const ublas::matrix_range< u_matrix > & J_in, const Frame & T, ublas::matrix_range< u_matrix > & J_out) [inline, static]
Definition at line 64 of file ublas_types.hpp.
References i.
template<typename MatrixType > Eigen::Block<MatrixType> iTaSC::project (MatrixType & m, Range r, Range c) [inline]
Definition at line 62 of file eigen_types.hpp.
References iTaSC::Range::count, and iTaSC::Range::start.
template<typename MatrixType > Eigen::Block<MatrixType> iTaSC::project (MatrixType & m, Range r) [inline]
Definition at line 57 of file eigen_types.hpp.
References iTaSC::Range::count, and iTaSC::Range::start.
Referenced by iTaSC::Scene::initialize(), iTaSC::SceneLock::lockJoint(), iTaSC::Scene::update(), and btWheelInfo::updateWheel().
void iTaSC::setCacheTimestamp (Timestamp & timestamp) [inline]
Definition at line 51 of file Cache.hpp.
References iTaSC::Timestamp::cacheTimestamp, and iTaSC::Timestamp::realTimestamp.
Referenced by iTaSC::Scene::update().
Variable Documentation
const unsigned int iTaSC::constraintCacheSize = 5 [static]
Definition at line 19 of file Armature.cpp.
Referenced by iTaSC::Armature::initCache().
const unsigned int iTaSC::distanceCacheSize = sizeof(double)*5 + sizeof(e_scalar)*6 [static]
Definition at line 19 of file Distance.cpp.
Referenced by iTaSC::Distance::initCache().
const KDL::Frame iTaSC::F_identity
Referenced by base_callback(), iTaSC::ConstraintSet::closeLoop(), iTaSC::Distance::closeLoop(), convert_tree(), iTaSC::Armature::Effector_struct::Effector_struct(), iTaSC::CopyPose::getControlParameters(), iTaSC::FixedObject::getPose(), iTaSC::Armature::getPose(), and iTaSC::CopyPose::updateControlOutput().
const unsigned int iTaSC::frameCacheSize = (sizeof(((Frame*)0)->p.data)+sizeof(((Frame*)0)->M.data))/sizeof(double) [static]
Definition at line 15 of file MovingFrame.cpp.
Referenced by iTaSC::MovingFrame::initCache().
const unsigned int iTaSC::maxPoseCacheSize = (2*(3+3*2))
Definition at line 19 of file CopyPose.cpp.