Blender: node_composite_tonemap.c File Reference
node_composite_tonemap.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static float avgLogLum (CompBuf *src, float *auto_key, float *Lav, float *Cav)
static void tonemap (NodeTonemap *ntm, CompBuf *dst, CompBuf *src)
static void node_composit_exec_tonemap (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_tonemap (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_tonemap (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_tonemap_in []
static bNodeSocketTemplate cmp_node_tonemap_out []
Detailed Description
Definition in file node_composite_tonemap.c.
Function Documentation
static float avgLogLum (CompBuf * src, float * auto_key, float * Lav, float * Cav) [static]
Definition at line 45 of file node_composite_tonemap.c.
References KDL::exp(), fRGB_add, fRGB_mult, L, log(), MAX2, p, CompBuf::rect, CompBuf::x, and CompBuf::y.
Referenced by tonemap().
static void node_composit_exec_tonemap (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 130 of file node_composite_tonemap.c.
References CB_RGBA, data, bNodeStack::data, dupalloc_compbuf(), free_compbuf(), NULL, bNode::storage, tonemap(), CompBuf::type, and typecheck_compbuf().
Referenced by register_node_type_cmp_tonemap().
static void node_composit_init_tonemap (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 149 of file node_composite_tonemap.c.
References NodeTonemap::a, NodeTonemap::c, NodeTonemap::f, NodeTonemap::gamma, NodeTonemap::key, NodeTonemap::m, MEM_callocN(), NodeTonemap::offset, bNode::storage, and NodeTonemap::type.
Referenced by register_node_type_cmp_tonemap().
void register_node_type_cmp_tonemap (bNodeTreeType * ttype)
Definition at line 165 of file node_composite_tonemap.c.
References CMP_NODE_TONEMAP, NODE_CLASS_OP_COLOR, node_composit_exec_tonemap(), node_composit_init_tonemap(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
static void tonemap (NodeTonemap * ntm, CompBuf * dst, CompBuf * src) [static]
Definition at line 70 of file node_composite_tonemap.c.
References NodeTonemap::a, avgLogLum(), NodeTonemap::c, KDL::exp(), NodeTonemap::f, fRGB_copy, fRGB_mult, NodeTonemap::gamma, NodeTonemap::key, L, NodeTonemap::m, MAX2, NodeTonemap::offset, pow(), CompBuf::rect, CompBuf::type, NodeTonemap::type, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_tonemap().
Variable Documentation
bNodeSocketTemplate cmp_node_tonemap_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 35 of file node_composite_tonemap.c.
bNodeSocketTemplate cmp_node_tonemap_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 39 of file node_composite_tonemap.c.