Blender: gjkepa2_impl Namespace Reference
gjkepa2_impl Namespace Reference
Classes
struct MinkowskiDiff
struct GJK
struct EPA
Typedefs
typedef unsigned int U
typedef unsigned char U1
typedef MinkowskiDiff tShape
Functions
static void Initialize (const btConvexShape *shape0, const btTransform &wtrs0, const btConvexShape *shape1, const btTransform &wtrs1, btGjkEpaSolver2::sResults &results, tShape &shape, bool withmargins)
Typedef Documentation
typedef MinkowskiDiff gjkepa2_impl::tShape
Definition at line 138 of file btGjkEpa2.cpp.
typedef unsigned int gjkepa2_impl::U
Definition at line 62 of file btGjkEpa2.cpp.
typedef unsigned char gjkepa2_impl::U1
Definition at line 63 of file btGjkEpa2.cpp.
Function Documentation
static void gjkepa2_impl::Initialize (const btConvexShape * shape0, const btTransform & wtrs0, const btConvexShape * shape1, const btTransform & wtrs1, btGjkEpaSolver2::sResults & results, tShape & shape, bool withmargins) [static]
Definition at line 790 of file btGjkEpa2.cpp.
References gjkepa2_impl::MinkowskiDiff::EnableMargin(), btTransform::getBasis(), btTransform::inverseTimes(), gjkepa2_impl::MinkowskiDiff::m_shapes, gjkepa2_impl::MinkowskiDiff::m_toshape0, gjkepa2_impl::MinkowskiDiff::m_toshape1, btGjkEpaSolver2::sResults::Separated, btGjkEpaSolver2::sResults::status, btMatrix3x3::transposeTimes(), and btGjkEpaSolver2::sResults::witnesses.
Referenced by btGjkEpaSolver2::Distance(), btGjkEpaSolver2::Penetration(), and btGjkEpaSolver2::SignedDistance().