Blender: interface_layout.c File Reference
interface_layout.c File Reference
interface
#include <limits.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "MEM_guardedalloc.h"
#include "DNA_screen_types.h"
#include "DNA_armature_types.h"
#include "DNA_userdef_types.h"
#include "BLI_listbase.h"
#include "BLI_string.h"
#include "BLI_utildefines.h"
#include "BLF_translation.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_idprop.h"
#include "BKE_screen.h"
#include "RNA_access.h"
#include "UI_interface.h"
#include "WM_api.h"
#include "WM_types.h"
#include "interface_intern.h"
#include "BLI_dynstr.h"
Classes
struct uiLayoutRoot
struct uiItem
struct uiButtonItem
struct uiLayout
struct uiLayoutItemFlow
struct uiLayoutItemBx
struct uiLayoutItemSplit
struct uiLayoutItemRoot
struct CollItemSearch
struct MenuItemLevel
Defines
#define RNA_NO_INDEX -1
#define RNA_ENUM_VALUE -2
#define EM_SEPR_X 6
#define EM_SEPR_Y 6
#define UI_OPERATOR_ERROR_RET(_ot, _opname, return_statement)
#define UI_ITEM_VARY_X 1
#define UI_ITEM_VARY_Y 2
Typedefs
typedef struct uiLayoutRoot uiLayoutRoot
typedef enum uiItemType uiItemType
typedef struct uiItem uiItem
typedef struct uiButtonItem uiButtonItem
typedef struct uiLayoutItemFlow uiLayoutItemFlow
typedef struct uiLayoutItemBx uiLayoutItemBx
typedef struct uiLayoutItemSplit uiLayoutItemSplit
typedef struct uiLayoutItemRoot uiLayoutItemRoot
typedef struct CollItemSearch CollItemSearch
typedef struct MenuItemLevel MenuItemLevel
Enumerations
enum uiItemType {
ITEM_BUTTON, ITEM_LAYOUT_ROW, ITEM_LAYOUT_COLUMN, ITEM_LAYOUT_COLUMN_FLOW,
ITEM_LAYOUT_ROW_FLOW, ITEM_LAYOUT_BOX, ITEM_LAYOUT_ABSOLUTE, ITEM_LAYOUT_SPLIT,
ITEM_LAYOUT_OVERLAP, ITEM_LAYOUT_ROOT
}
Functions
static const char * ui_item_name_add_colon (const char *name, char namestr[UI_MAX_NAME_STR])
static int ui_item_fit (int item, int pos, int all, int available, int last, int alignment, int *offset)
static int ui_layout_vary_direction (uiLayout *layout)
static int ui_text_icon_width (uiLayout *layout, const char *name, int icon, int compact)
static void ui_item_size (uiItem *item, int *r_w, int *r_h)
static void ui_item_offset (uiItem *item, int *r_x, int *r_y)
static void ui_item_position (uiItem *item, int x, int y, int w, int h)
static int ui_layout_local_dir (uiLayout *layout)
static uiLayout * ui_item_local_sublayout (uiLayout *test, uiLayout *layout, int align)
static void ui_layer_but_cb (bContext *C, void *arg_but, void *arg_index)
static void ui_item_array (uiLayout *layout, uiBlock *block, const char *name, int icon, PointerRNA *ptr, PropertyRNA *prop, int len, int x, int y, int w, int UNUSED(h), int expand, int slider, int toggle, int icon_only)
static void ui_item_enum_expand (uiLayout *layout, uiBlock *block, PointerRNA *ptr, PropertyRNA *prop, const char *uiname, int h, int icon_only)
static void ui_keymap_but_cb (bContext *UNUSED(C), void *but_v, void *UNUSED(key_v))
static uiBut * ui_item_with_label (uiLayout *layout, uiBlock *block, const char *name, int icon, PointerRNA *ptr, PropertyRNA *prop, int index, int x, int y, int w, int h, int flag)
void uiFileBrowseContextProperty (const bContext *C, PointerRNA *ptr, PropertyRNA **prop)
static void ui_item_disabled (uiLayout *layout, const char *name)
PointerRNA uiItemFullO_ptr (uiLayout *layout, wmOperatorType *ot, const char *name, int icon, IDProperty *properties, int context, int flag)
PointerRNA uiItemFullO (uiLayout *layout, const char *opname, const char *name, int icon, IDProperty *properties, int context, int flag)
static const char * ui_menu_enumpropname (uiLayout *layout, PointerRNA *ptr, PropertyRNA *prop, int retval)
static void uiItemEnumO_ptr__internal (uiLayout *layout, wmOperatorType *ot, const char *name, int icon, PropertyRNA *prop, int value)
void uiItemEnumO_ptr (uiLayout *layout, wmOperatorType *ot, const char *name, int icon, const char *propname, int value)
void uiItemEnumO (uiLayout *layout, const char *opname, const char *name, int icon, const char *propname, int value)
void uiItemsFullEnumO (uiLayout *layout, const char *opname, const char *propname, IDProperty *properties, int context, int flag)
void uiItemsEnumO (uiLayout *layout, const char *opname, const char *propname)
void uiItemEnumO_value (uiLayout *layout, const char *name, int icon, const char *opname, const char *propname, int value)
void uiItemEnumO_string (uiLayout *layout, const char *name, int icon, const char *opname, const char *propname, const char *value_str)
void uiItemBooleanO (uiLayout *layout, const char *name, int icon, const char *opname, const char *propname, int value)
void uiItemIntO (uiLayout *layout, const char *name, int icon, const char *opname, const char *propname, int value)
void uiItemFloatO (uiLayout *layout, const char *name, int icon, const char *opname, const char *propname, float value)
void uiItemStringO (uiLayout *layout, const char *name, int icon, const char *opname, const char *propname, const char *value)
void uiItemO (uiLayout *layout, const char *name, int icon, const char *opname)
static void ui_item_rna_size (uiLayout *layout, const char *name, int icon, PointerRNA *ptr, PropertyRNA *prop, int index, int icon_only, int *r_w, int *r_h)
void uiItemFullR (uiLayout *layout, PointerRNA *ptr, PropertyRNA *prop, int index, int value, int flag, const char *name, int icon)
void uiItemR (uiLayout *layout, PointerRNA *ptr, const char *propname, int flag, const char *name, int icon)
void uiItemEnumR (uiLayout *layout, const char *name, int icon, struct PointerRNA *ptr, const char *propname, int value)
void uiItemEnumR_string (uiLayout *layout, struct PointerRNA *ptr, const char *propname, const char *value, const char *name, int icon)
void uiItemsEnumR (uiLayout *layout, struct PointerRNA *ptr, const char *propname)
static int sort_search_items_list (void *a, void *b)
static void rna_search_cb (const struct bContext *C, void *arg_but, const char *str, uiSearchItems *items)
static void search_id_collection (StructRNA *ptype, PointerRNA *ptr, PropertyRNA **prop)
void ui_but_add_search (uiBut *but, PointerRNA *ptr, PropertyRNA *prop, PointerRNA *searchptr, PropertyRNA *searchprop)
void uiItemPointerR (uiLayout *layout, struct PointerRNA *ptr, const char *propname, struct PointerRNA *searchptr, const char *searchpropname, const char *name, int icon)
static void ui_item_menutype_func (bContext *C, uiLayout *layout, void *arg_mt)
static void ui_item_menu (uiLayout *layout, const char *name, int icon, uiMenuCreateFunc func, void *arg, void *argN, const char *tip)
void uiItemM (uiLayout *layout, bContext *UNUSED(C), const char *menuname, const char *name, int icon)
static uiBut * uiItemL_ (uiLayout *layout, const char *name, int icon)
void uiItemL (uiLayout *layout, const char *name, int icon)
void uiItemLDrag (uiLayout *layout, PointerRNA *ptr, const char *name, int icon)
void uiItemV (uiLayout *layout, const char *name, int icon, int argval)
void uiItemS (uiLayout *layout)
void uiItemMenuF (uiLayout *layout, const char *name, int icon, uiMenuCreateFunc func, void *arg)
static void menu_item_enum_opname_menu (bContext *UNUSED(C), uiLayout *layout, void *arg)
void uiItemMenuEnumO (uiLayout *layout, const char *opname, const char *propname, const char *name, int icon)
static void menu_item_enum_rna_menu (bContext *UNUSED(C), uiLayout *layout, void *arg)
void uiItemMenuEnumR (uiLayout *layout, struct PointerRNA *ptr, const char *propname, const char *name, int icon)
static void ui_litem_estimate_row (uiLayout *litem)
static int ui_litem_min_width (int itemw)
static void ui_litem_layout_row (uiLayout *litem)
static void ui_litem_estimate_column (uiLayout *litem)
static void ui_litem_layout_column (uiLayout *litem)
static void ui_litem_estimate_root (uiLayout *UNUSED(litem))
static void ui_litem_layout_root (uiLayout *litem)
static void ui_litem_estimate_box (uiLayout *litem)
static void ui_litem_layout_box (uiLayout *litem)
static void ui_litem_estimate_column_flow (uiLayout *litem)
static void ui_litem_layout_column_flow (uiLayout *litem)
static void ui_litem_estimate_absolute (uiLayout *litem)
static void ui_litem_layout_absolute (uiLayout *litem)
static void ui_litem_estimate_split (uiLayout *litem)
static void ui_litem_layout_split (uiLayout *litem)
static void ui_litem_estimate_overlap (uiLayout *litem)
static void ui_litem_layout_overlap (uiLayout *litem)
uiLayout * uiLayoutRow (uiLayout *layout, int align)
uiLayout * uiLayoutColumn (uiLayout *layout, int align)
uiLayout * uiLayoutColumnFlow (uiLayout *layout, int number, int align)
static uiLayoutItemBx * ui_layout_box (uiLayout *layout, int type)
uiLayout * uiLayoutBox (uiLayout *layout)
uiLayout * uiLayoutListBox (uiLayout *layout, PointerRNA *ptr, PropertyRNA *prop, PointerRNA *actptr, PropertyRNA *actprop)
uiLayout * uiLayoutAbsolute (uiLayout *layout, int align)
uiBlock * uiLayoutAbsoluteBlock (uiLayout *layout)
uiLayout * uiLayoutOverlap (uiLayout *layout)
uiLayout * uiLayoutSplit (uiLayout *layout, float percentage, int align)
void uiLayoutSetActive (uiLayout *layout, int active)
void uiLayoutSetEnabled (uiLayout *layout, int enabled)
void uiLayoutSetRedAlert (uiLayout *layout, int redalert)
void uiLayoutSetKeepAspect (uiLayout *layout, int keepaspect)
void uiLayoutSetAlignment (uiLayout *layout, int alignment)
void uiLayoutSetScaleX (uiLayout *layout, float scale)
void uiLayoutSetScaleY (uiLayout *layout, float scale)
int uiLayoutGetActive (uiLayout *layout)
int uiLayoutGetEnabled (uiLayout *layout)
int uiLayoutGetRedAlert (uiLayout *layout)
int uiLayoutGetKeepAspect (uiLayout *layout)
int uiLayoutGetAlignment (uiLayout *layout)
int uiLayoutGetWidth (uiLayout *layout)
float uiLayoutGetScaleX (uiLayout *layout)
float uiLayoutGetScaleY (uiLayout *layout)
static void ui_item_scale (uiLayout *litem, float scale[2])
static void ui_item_estimate (uiItem *item)
static void ui_item_align (uiLayout *litem, short nr)
static void ui_item_flag (uiLayout *litem, int flag)
static void ui_item_layout (uiItem *item)
static void ui_layout_end (uiBlock *block, uiLayout *layout, int *x, int *y)
static void ui_layout_free (uiLayout *layout)
uiLayout * uiBlockLayout (uiBlock *block, int dir, int type, int x, int y, int size, int em, uiStyle *style)
uiBlock * uiLayoutGetBlock (uiLayout *layout)
int uiLayoutGetOperatorContext (uiLayout *layout)
void uiBlockSetCurLayout (uiBlock *block, uiLayout *layout)
void ui_layout_add_but (uiLayout *layout, uiBut *but)
void uiLayoutSetOperatorContext (uiLayout *layout, int opcontext)
void uiLayoutSetFunc (uiLayout *layout, uiMenuHandleFunc handlefunc, void *argv)
void uiBlockLayoutResolve (uiBlock *block, int *x, int *y)
void uiLayoutSetContextPointer (uiLayout *layout, const char *name, PointerRNA *ptr)
void uiLayoutContextCopy (uiLayout *layout, bContextStore *context)
static void ui_intro_button (DynStr *ds, uiButtonItem *bitem)
static void ui_intro_items (DynStr *ds, ListBase *lb)
static void ui_intro_uiLayout (DynStr *ds, uiLayout *layout)
const char * uiLayoutIntrospect (uiLayout *layout)
static void ui_layout_operator_buts__reset_cb (bContext *UNUSED(C), void *op_pt, void *UNUSED(arg_dummy2))
void uiLayoutOperatorButs (const bContext *C, uiLayout *layout, wmOperator *op, int(*check_prop)(struct PointerRNA *, struct PropertyRNA *), const char label_align, const short flag)
MenuType * uiButGetMenuType (uiBut *but)
Variables
static char * str = NULL
Detailed Description
Definition in file interface_layout.c.
Define Documentation
#define EM_SEPR_X 6
Definition at line 66 of file interface_layout.c.
Referenced by uiItemS().
#define EM_SEPR_Y 6
Definition at line 67 of file interface_layout.c.
Referenced by uiItemS().
#define RNA_ENUM_VALUE -2
Definition at line 64 of file interface_layout.c.
Referenced by uiItemEnumR(), uiItemEnumR_string(), and uiItemFullR().
#define RNA_NO_INDEX -1
Definition at line 63 of file interface_layout.c.
Referenced by ui_item_rna_size(), uiItemFullR(), and uiItemR().
#define UI_ITEM_VARY_X 1
Definition at line 215 of file interface_layout.c.
Referenced by ui_item_rna_size(), ui_layout_vary_direction(), and ui_text_icon_width().
#define UI_ITEM_VARY_Y 2
Definition at line 216 of file interface_layout.c.
Referenced by ui_layout_vary_direction().
#define UI_OPERATOR_ERROR_RET (_ot, _opname, return_statement)
Value:
if (ot == NULL) {                                                         \
        ui_item_disabled(layout, _opname);                                    \
        RNA_warning("'%s' unknown operator", _opname);                        \
        return_statement;                                                     \
    } (void)0                                                                 \
Definition at line 69 of file interface_layout.c.
Referenced by uiItemBooleanO(), uiItemEnumO_string(), uiItemEnumO_value(), uiItemFloatO(), uiItemFullO(), uiItemIntO(), uiItemMenuEnumO(), and uiItemStringO().
Typedef Documentation
typedef struct CollItemSearch CollItemSearch
typedef struct MenuItemLevel MenuItemLevel
typedef struct uiButtonItem uiButtonItem
typedef struct uiItem uiItem
typedef enum uiItemType uiItemType
typedef struct uiLayoutItemBx uiLayoutItemBx
typedef struct uiLayoutItemFlow uiLayoutItemFlow
typedef struct uiLayoutItemRoot uiLayoutItemRoot
typedef struct uiLayoutItemSplit uiLayoutItemSplit
typedef struct uiLayoutRoot uiLayoutRoot
Enumeration Type Documentation
enum uiItemType
Enumerator:
ITEM_BUTTON
ITEM_LAYOUT_ROW
ITEM_LAYOUT_COLUMN
ITEM_LAYOUT_COLUMN_FLOW
ITEM_LAYOUT_ROW_FLOW
ITEM_LAYOUT_BOX
ITEM_LAYOUT_ABSOLUTE
ITEM_LAYOUT_SPLIT
ITEM_LAYOUT_OVERLAP
ITEM_LAYOUT_ROOT
Definition at line 97 of file interface_layout.c.
Function Documentation
static void menu_item_enum_opname_menu (bContext * UNUSEDC, uiLayout * layout, void * arg) [static]
Definition at line 1599 of file interface_layout.c.
References MenuItemLevel::opcontext, MenuItemLevel::opname, MenuItemLevel::propname, uiItemsEnumO(), and uiLayoutSetOperatorContext().
Referenced by uiItemMenuEnumO().
static void menu_item_enum_rna_menu (bContext * UNUSEDC, uiLayout * layout, void * arg) [static]
Definition at line 1633 of file interface_layout.c.
References MenuItemLevel::opcontext, MenuItemLevel::propname, MenuItemLevel::rnapoin, uiItemsEnumR(), and uiLayoutSetOperatorContext().
Referenced by uiItemMenuEnumR().
static void rna_search_cb (const struct bContext * C, void * arg_but, const char * str, uiSearchItems * items) [static]
Definition at line 1258 of file interface_layout.c.
References BLI_addtail(), BLI_freelistN(), BLI_sortlist(), BLI_strcasestr(), BLI_strdup(), BLI_strncpy(), uiBut::changed, PointerRNA::data, ListBase::first, i, CollItemSearch::iconid, PointerRNA::id, CollItemSearch::index, MAX_ID_NAME, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), CollItemSearch::name, ID::name, name_uiprefix_id(), CollItemSearch::next, NULL, PROP_ID_SELF_CHECK, PROP_POINTER, RNA_PROP_BEGIN, RNA_PROP_END, RNA_property_flag(), RNA_property_pointer_poll(), RNA_property_type(), RNA_struct_is_ID(), RNA_struct_name_get_alloc(), uiBut::rnapoin, uiBut::rnaprop, uiBut::rnasearchpoin, uiBut::rnasearchprop, SET_INT_IN_POINTER, sort_search_items_list(), ui_id_icon_get(), and uiSearchItemAdd().
Referenced by ui_but_add_search().
static void search_id_collection (StructRNA * ptype, PointerRNA * ptr, PropertyRNA ** prop) [static]
Definition at line 1327 of file interface_layout.c.
References G, NULL, PROP_COLLECTION, RNA_main_pointer_create(), RNA_property_pointer_type(), RNA_property_type(), RNA_STRUCT_BEGIN, and RNA_STRUCT_END.
Referenced by ui_but_add_search().
static int sort_search_items_list (void * a, void * b) [static]
Definition at line 1247 of file interface_layout.c.
References BLI_strcasecmp(), and CollItemSearch::name.
Referenced by rna_search_cb().
void ui_but_add_search (uiBut * but, PointerRNA * ptr, PropertyRNA * prop, PointerRNA * searchptr, PropertyRNA * searchprop)
Definition at line 1350 of file interface_layout.c.
References uiBut::flag, uiBut::hardmax, MAX2, NULL, PROP_POINTER, RNA_property_pointer_type(), RNA_property_type(), rna_search_cb(), uiBut::rnasearchpoin, uiBut::rnasearchprop, search_id_collection(), SEARCH_MENU, uiBut::type, UI_ICON_LEFT, UI_TEXT_LEFT, and uiButSetSearchFunc().
Referenced by uiItemFullR(), and uiItemPointerR().
static void ui_intro_button (DynStr * ds, uiButtonItem * bitem) [static]
Definition at line 2735 of file interface_layout.c.
References BLI_dynstr_appendf(), uiBut::block, uiButtonItem::but, uiBut::drawstr, uiBlock::evil_C, MEM_freeN(), uiBut::opptr, uiBut::optype, RNA_property_identifier(), RNA_struct_identifier(), uiBut::rnaindex, uiBut::rnapoin, uiBut::rnaprop, uiBut::tip, PointerRNA::type, uiBut::type, and WM_operator_pystring().
Referenced by ui_intro_items().
static void ui_intro_items (DynStr * ds, ListBase * lb) [static]
Definition at line 2754 of file interface_layout.c.
References BLI_dynstr_append(), ListBase::first, ITEM_BUTTON, ITEM_LAYOUT_ABSOLUTE, ITEM_LAYOUT_BOX, ITEM_LAYOUT_COLUMN, ITEM_LAYOUT_COLUMN_FLOW, ITEM_LAYOUT_OVERLAP, ITEM_LAYOUT_ROOT, ITEM_LAYOUT_ROW, ITEM_LAYOUT_ROW_FLOW, ITEM_LAYOUT_SPLIT, ListBase::last, uiItem::next, uiItem::type, and ui_intro_button().
Referenced by ui_intro_uiLayout().
static void ui_intro_uiLayout (DynStr * ds, uiLayout * layout) [static]
Definition at line 2797 of file interface_layout.c.
References uiLayout::items, and ui_intro_items().
Referenced by uiLayoutIntrospect().
static void ui_item_align (uiLayout * litem, short nr) [static]
Definition at line 2492 of file interface_layout.c.
References uiBut::alignnr, BLI_addhead(), BLI_remlink(), uiLayoutRoot::block, uiButtonItem::but, uiBlock::buttons, ITEM_BUTTON, ITEM_LAYOUT_ABSOLUTE, ITEM_LAYOUT_BOX, ITEM_LAYOUT_OVERLAP, uiLayout::items, ListBase::last, uiItem::prev, uiLayout::root, uiLayoutItemBx::roundbox, uiItem::type, and ui_but_can_align().
Referenced by ui_item_layout().
static void ui_item_array (uiLayout * layout, uiBlock * block, const char * name, int icon, PointerRNA * ptr, PropertyRNA * prop, int len, int x, int y, int w, int UNUSEDh, int expand, int slider, int toggle, int icon_only) [static]
Definition at line 345 of file interface_layout.c.
References uiLayoutRoot::block, BUT_NORMAL, uiStyle::buttonspacex, PointerRNA::data, uiBlock::dt, ELEM, LABEL, bArmature::layer_used, len(), MEM_callocN(), MEM_freeN(), NULL, NUM, NUMSLI, OPTION, PROP_BOOLEAN, PROP_COLOR, PROP_COLOR_GAMMA, PROP_DIRECTION, PROP_LAYER, PROP_LAYER_MEMBER, PROP_MATRIX, RNA_Armature, RNA_property_array_dimension(), RNA_property_array_item_char(), RNA_property_boolean_get_array(), RNA_property_subtype(), RNA_property_type(), uiLayout::root, SET_INT_IN_POINTER, str, uiLayoutRoot::style, TOG, PointerRNA::type, uiBut::type, UI_EMBOSSN, UI_EMBOSSP, ui_item_local_sublayout(), ui_layer_but_cb(), UI_UNIT_X, UI_UNIT_Y, uiBlockBeginAlign(), uiBlockEndAlign(), uiBlockSetCurLayout(), uiButSetFunc(), uiDefAutoButR(), uiDefBut(), uiDefButR_prop(), and uiLayoutAbsolute().
Referenced by uiItemFullR().
static void ui_item_disabled (uiLayout * layout, const char * name) [static]
Definition at line 615 of file interface_layout.c.
References uiLayoutRoot::block, uiBut::flag, LABEL, uiBut::lock, uiBut::lockstr, NULL, uiLayout::root, UI_BUT_DISABLED, ui_text_icon_width(), UI_UNIT_Y, uiBlockSetCurLayout(), and uiDefBut().
Referenced by uiItemEnumO(), uiItemEnumR(), uiItemEnumR_string(), uiItemMenuEnumO(), uiItemMenuEnumR(), uiItemR(), uiItemsEnumR(), and uiItemsFullEnumO().
static void ui_item_enum_expand (uiLayout * layout, uiBlock * block, PointerRNA * ptr, PropertyRNA * prop, const char * uiname, int h, int icon_only) [static]
Definition at line 479 of file interface_layout.c.
References uiBlock::curlayout, uiBlock::evil_C, uiBut::flag, EnumPropertyItem::icon, MEM_freeN(), NULL, RNA_property_enum_items_gettexted(), ROW, ui_item_local_sublayout(), UI_LAYOUT_HORIZONTAL, ui_layout_local_dir(), ui_text_icon_width(), UI_TEXT_LEFT, uiBlockSetCurLayout(), uiDefButR_prop(), uiDefIconButR_prop(), uiDefIconTextButR_prop(), and EnumPropertyItem::value.
Referenced by uiItemFullR().
static void ui_item_estimate (uiItem * item) [static]
Definition at line 2445 of file interface_layout.c.
References ListBase::first, uiLayout::item, ITEM_BUTTON, ITEM_LAYOUT_ABSOLUTE, ITEM_LAYOUT_BOX, ITEM_LAYOUT_COLUMN, ITEM_LAYOUT_COLUMN_FLOW, ITEM_LAYOUT_OVERLAP, ITEM_LAYOUT_ROOT, ITEM_LAYOUT_ROW, ITEM_LAYOUT_SPLIT, uiLayout::items, uiItem::next, NULL, uiLayout::scale, uiItem::type, ui_item_scale(), ui_litem_estimate_absolute(), ui_litem_estimate_box(), ui_litem_estimate_column(), ui_litem_estimate_column_flow(), ui_litem_estimate_overlap(), ui_litem_estimate_root(), ui_litem_estimate_row(), and ui_litem_estimate_split().
Referenced by ui_layout_end().
static int ui_item_fit (int item, int pos, int all, int available, int last, int alignment, int * offset) [static]
Definition at line 185 of file interface_layout.c.
References UI_LAYOUT_ALIGN_EXPAND.
Referenced by ui_litem_layout_column_flow(), and ui_litem_layout_row().
static void ui_item_flag (uiLayout * litem, int flag) [static]
Definition at line 2518 of file interface_layout.c.
References uiButtonItem::but, uiBut::flag, ITEM_BUTTON, uiLayout::items, ListBase::last, uiItem::prev, and uiItem::type.
Referenced by ui_item_layout().
static void ui_item_layout (uiItem * item) [static]
Definition at line 2533 of file interface_layout.c.
References uiLayout::active, uiLayout::align, uiBlock::alignnr, uiLayoutRoot::block, uiLayout::enabled, ListBase::first, uiLayout::item, ITEM_BUTTON, ITEM_LAYOUT_ABSOLUTE, ITEM_LAYOUT_BOX, ITEM_LAYOUT_COLUMN, ITEM_LAYOUT_COLUMN_FLOW, ITEM_LAYOUT_OVERLAP, ITEM_LAYOUT_ROOT, ITEM_LAYOUT_ROW, ITEM_LAYOUT_SPLIT, uiLayout::items, uiItem::next, NULL, uiLayout::root, uiItem::type, UI_BUT_DISABLED, UI_BUT_INACTIVE, ui_item_align(), ui_item_flag(), ui_litem_layout_absolute(), ui_litem_layout_box(), ui_litem_layout_column(), ui_litem_layout_column_flow(), ui_litem_layout_overlap(), ui_litem_layout_root(), ui_litem_layout_row(), and ui_litem_layout_split().
Referenced by ui_layout_end().
static uiLayout* ui_item_local_sublayout (uiLayout * test, uiLayout * layout, int align) [static]
Definition at line 307 of file interface_layout.c.
References uiLayout::space, UI_LAYOUT_HORIZONTAL, ui_layout_local_dir(), uiLayoutColumn(), and uiLayoutRow().
Referenced by ui_item_array(), and ui_item_enum_expand().
static void ui_item_menu (uiLayout * layout, const char * name, int icon, uiMenuCreateFunc func, void * arg, void * argN, const char * tip) [static]
Definition at line 1443 of file interface_layout.c.
References uiLayoutRoot::block, ELEM, uiBut::flag, uiBut::func_argN, MENU, uiBut::poin, uiLayout::root, uiBut::type, uiLayoutRoot::type, UI_EMBOSS, UI_LAYOUT_HEADER, UI_LAYOUT_MENU, UI_LAYOUT_PANEL, UI_LAYOUT_TOOLBAR, ui_text_icon_width(), UI_TEXT_LEFT, UI_UNIT_Y, uiBlockSetCurLayout(), uiBlockSetEmboss(), uiDefIconMenuBut(), uiDefIconTextMenuBut(), and uiDefMenuBut().
Referenced by uiItemM(), uiItemMenuEnumO(), uiItemMenuEnumR(), and uiItemMenuF().
static void ui_item_menutype_func (bContext * C, uiLayout * layout, void * arg_mt) [static]
Definition at line 1433 of file interface_layout.c.
References MenuType::draw, Menu::layout, mt, NULL, and Menu::type.
Referenced by uiButGetMenuType(), and uiItemM().
static const char* ui_item_name_add_colon (const char * name, char namestr[UI_MAX_NAME_STR]) [static]
Definition at line 171 of file interface_layout.c.
References BLI_strncpy(), len(), and strlen().
Referenced by uiItemFullR().
static void ui_item_offset (uiItem * item, int * r_x, int * r_y) [static]
Definition at line 252 of file interface_layout.c.
References uiButtonItem::but, ITEM_BUTTON, uiItem::type, uiBut::x1, and uiBut::y1.
Referenced by ui_item_scale(), ui_litem_estimate_absolute(), and ui_litem_layout_absolute().
static void ui_item_position (uiItem * item, int x, int y, int w, int h) [static]
Definition at line 266 of file interface_layout.c.
References uiButtonItem::but, uiLayout::h, ITEM_BUTTON, uiItem::type, ui_check_but(), uiLayout::w, uiLayout::x, uiBut::x1, uiBut::x2, uiLayout::y, uiBut::y1, and uiBut::y2.
Referenced by ui_item_scale(), ui_litem_layout_absolute(), ui_litem_layout_column(), ui_litem_layout_column_flow(), ui_litem_layout_overlap(), and ui_litem_layout_split().
static void ui_item_rna_size (uiLayout * layout, const char * name, int icon, PointerRNA * ptr, PropertyRNA * prop, int index, int icon_only, int * r_w, int * r_h) [static]
Definition at line 983 of file interface_layout.c.
References ELEM, ELEM3, len(), PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_LAYER, PROP_LAYER_MEMBER, PROP_MATRIX, PROP_POINTER, PROP_STRING, RNA_NO_INDEX, RNA_property_array_length(), RNA_property_subtype(), RNA_property_type(), sqrt(), UI_ITEM_VARY_X, ui_layout_vary_direction(), ui_text_icon_width(), UI_UNIT_X, and UI_UNIT_Y.
Referenced by uiItemFullR(), and uiItemPointerR().
static void ui_item_scale (uiLayout * litem, float scale[2]) [static]
Definition at line 2422 of file interface_layout.c.
References uiLayout::items, ListBase::last, uiItem::prev, ui_item_offset(), ui_item_position(), and ui_item_size().
Referenced by ui_item_estimate().
static void ui_item_size (uiItem * item, int * r_w, int * r_h) [static]
Definition at line 236 of file interface_layout.c.
References uiButtonItem::but, uiLayout::h, ITEM_BUTTON, uiItem::type, uiLayout::w, uiBut::x1, uiBut::x2, uiBut::y1, and uiBut::y2.
Referenced by ui_item_scale(), ui_litem_estimate_absolute(), ui_litem_estimate_column(), ui_litem_estimate_column_flow(), ui_litem_estimate_overlap(), ui_litem_estimate_row(), ui_litem_layout_absolute(), ui_litem_layout_column(), ui_litem_layout_column_flow(), ui_litem_layout_overlap(), ui_litem_layout_row(), and ui_litem_layout_split().
static uiBut* ui_item_with_label (uiLayout * layout, uiBlock * block, const char * name, int icon, PointerRNA * ptr, PropertyRNA * prop, int index, int x, int y, int w, int h, int flag) [static]
Definition at line 527 of file interface_layout.c.
References BUT, CLAMP(), PointerRNA::data, HOTKEYEVT, KEYEVT, LABEL, NULL, PROP_DIRPATH, PROP_ENUM, PROP_FILEPATH, RNA_KeyMapItem, RNA_property_subtype(), RNA_property_type(), RNA_struct_is_a(), PointerRNA::type, UI_BUT_IMMEDIATE, UI_GetStringWidth(), UI_ITEM_R_EVENT, UI_ITEM_R_FULL_EVENT, UI_ITEM_R_ICON_ONLY, UI_ITEM_R_IMMEDIATE, ui_keymap_but_cb(), UI_UNIT_X, uiBlockSetCurLayout(), uiButSetFlag(), uiButSetFunc(), uiDefAutoButR(), uiDefBut(), uiDefButR_prop(), uiDefIconButO(), uiLayoutRow(), WM_keymap_item_to_string(), and WM_OP_INVOKE_DEFAULT.
Referenced by uiItemFullR(), and uiItemPointerR().
static void ui_keymap_but_cb (bContext * UNUSEDC, void * but_v, void * UNUSEDkey_v) [static]
Definition at line 516 of file interface_layout.c.
References KM_ALT, KM_CTRL, KM_OSKEY, KM_SHIFT, uiBut::modifier_key, RNA_boolean_set(), and uiBut::rnapoin.
Referenced by ui_item_with_label().
static void ui_layer_but_cb (bContext * C, void * arg_but, void * arg_index) [static]
Definition at line 320 of file interface_layout.c.
References uiBut::block, uiBlock::buttons, CTX_wm_window(), wmWindow::eventstate, ListBase::first, GET_INT_FROM_POINTER, i, len(), RNA_property_array_length(), RNA_property_boolean_set_index(), RNA_property_update(), uiBut::rnapoin, uiBut::rnaprop, wmEvent::shift, TRUE, and ui_check_but().
Referenced by ui_item_array().
void ui_layout_add_but (uiLayout * layout, uiBut * but)
Definition at line 2669 of file interface_layout.c.
References BLI_addtail(), uiButtonItem::but, uiBut::context, uiLayout::context, uiButtonItem::item, ITEM_BUTTON, uiLayout::items, MEM_callocN(), uiItem::type, and bContextStore::used.
Referenced by ui_def_but().
static uiLayoutItemBx* ui_layout_box (uiLayout * layout, int type) [static]
Definition at line 2240 of file interface_layout.c.
References uiLayout::active, BLI_addtail(), uiLayoutRoot::block, uiStyle::columnspace, uiLayout::context, uiLayout::enabled, uiLayout::item, ITEM_LAYOUT_BOX, uiLayout::items, uiLayoutItemBx::litem, MEM_callocN(), NULL, uiLayout::root, uiLayoutItemBx::roundbox, uiLayout::space, uiLayoutRoot::style, uiItem::type, uiBlockSetCurLayout(), uiDefBut(), and uiLayout::w.
Referenced by uiLayoutBox(), and uiLayoutListBox().
static void ui_layout_end (uiBlock * block, uiLayout * layout, int * x, int * y) [static]
Definition at line 2584 of file interface_layout.c.
References uiLayoutRoot::argv, uiLayoutRoot::handlefunc, uiLayout::item, uiLayout::root, ui_item_estimate(), ui_item_layout(), uiBlockSetHandleFunc(), uiLayout::x, and uiLayout::y.
Referenced by uiBlockLayoutResolve().
static void ui_layout_free (uiLayout * layout) [static]
Definition at line 2596 of file interface_layout.c.
References ListBase::first, ITEM_BUTTON, uiLayout::items, MEM_freeN(), next, uiItem::next, and uiItem::type.
Referenced by uiBlockLayoutResolve().
static int ui_layout_local_dir (uiLayout * layout) [static]
Definition at line 290 of file interface_layout.c.
References uiLayout::item, ITEM_LAYOUT_ABSOLUTE, ITEM_LAYOUT_BOX, ITEM_LAYOUT_COLUMN, ITEM_LAYOUT_COLUMN_FLOW, ITEM_LAYOUT_OVERLAP, ITEM_LAYOUT_ROOT, ITEM_LAYOUT_ROW, ITEM_LAYOUT_SPLIT, uiItem::type, UI_LAYOUT_HORIZONTAL, and UI_LAYOUT_VERTICAL.
Referenced by ui_item_enum_expand(), and ui_item_local_sublayout().
static void ui_layout_operator_buts__reset_cb (bContext * UNUSEDC, void * op_pt, void * UNUSEDarg_dummy2) [static]
Definition at line 2819 of file interface_layout.c.
References WM_operator_properties_reset().
Referenced by uiLayoutOperatorButs().
static int ui_layout_vary_direction (uiLayout * layout) [static]
Definition at line 218 of file interface_layout.c.
References uiLayout::alignment, uiLayout::root, uiLayoutRoot::type, UI_ITEM_VARY_X, UI_ITEM_VARY_Y, UI_LAYOUT_ALIGN_EXPAND, and UI_LAYOUT_HEADER.
Referenced by ui_item_rna_size(), and ui_text_icon_width().
static void ui_litem_estimate_absolute (uiLayout * litem) [static]
Definition at line 2013 of file interface_layout.c.
References ListBase::first, uiLayout::h, uiLayout::items, MAX2, MIN2, uiItem::next, ui_item_offset(), ui_item_size(), and uiLayout::w.
Referenced by ui_item_estimate().
static void ui_litem_estimate_box (uiLayout * litem) [static]
Definition at line 1857 of file interface_layout.c.
References uiStyle::boxspace, uiLayout::h, uiLayout::root, uiLayoutRoot::style, ui_litem_estimate_column(), and uiLayout::w.
Referenced by ui_item_estimate().
static void ui_litem_estimate_column (uiLayout * litem) [static]
Definition at line 1800 of file interface_layout.c.
References ListBase::first, uiLayout::h, uiLayout::items, MAX2, uiItem::next, uiLayout::space, ui_item_size(), and uiLayout::w.
Referenced by ui_item_estimate(), and ui_litem_estimate_box().
static void ui_litem_estimate_column_flow (uiLayout * litem) [static]
Definition at line 1898 of file interface_layout.c.
References uiStyle::buttonspacey, uiLayoutRoot::emw, ListBase::first, uiLayout::h, uiLayout::items, MAX2, MIN2, uiItem::next, uiLayoutItemFlow::number, uiLayout::root, uiLayout::space, uiLayoutRoot::style, uiLayoutItemFlow::totcol, ui_item_size(), uiLayout::w, and uiLayout::y.
Referenced by ui_item_estimate().
static void ui_litem_estimate_overlap (uiLayout * litem) [static]
Definition at line 2143 of file interface_layout.c.
References ListBase::first, uiLayout::h, uiLayout::items, MAX2, uiItem::next, ui_item_size(), and uiLayout::w.
Referenced by ui_item_estimate().
static void ui_litem_estimate_root (uiLayout * UNUSEDlitem) [static]
Definition at line 1843 of file interface_layout.c.
Referenced by ui_item_estimate().
static void ui_litem_estimate_row (uiLayout * litem) [static]
Definition at line 1669 of file interface_layout.c.
References ListBase::first, uiLayout::h, uiLayout::items, MAX2, uiItem::next, uiLayout::space, ui_item_size(), and uiLayout::w.
Referenced by ui_item_estimate(), and ui_litem_estimate_split().
static void ui_litem_estimate_split (uiLayout * litem) [static]
Definition at line 2097 of file interface_layout.c.
References ui_litem_estimate_row().
Referenced by ui_item_estimate().
static void ui_litem_layout_absolute (uiLayout * litem) [static]
Definition at line 2038 of file interface_layout.c.
References ListBase::first, uiLayout::h, uiLayout::items, MAX2, MIN2, uiItem::next, ui_item_offset(), ui_item_position(), ui_item_size(), uiLayout::w, uiLayout::x, and uiLayout::y.
Referenced by ui_item_layout().
static void ui_litem_layout_box (uiLayout * litem) [static]
Definition at line 1866 of file interface_layout.c.
References uiStyle::boxspace, uiLayout::h, uiLayout::root, uiLayoutItemBx::roundbox, uiLayoutRoot::style, ui_litem_layout_column(), uiLayout::w, uiLayout::x, uiBut::x1, uiBut::x2, uiLayout::y, uiBut::y1, and uiBut::y2.
Referenced by ui_item_layout().
static void ui_litem_layout_column (uiLayout * litem) [static]
Definition at line 1819 of file interface_layout.c.
References ListBase::first, uiLayout::h, uiLayout::items, uiItem::next, NULL, uiLayout::space, ui_item_position(), ui_item_size(), uiLayout::w, uiLayout::x, and uiLayout::y.
Referenced by ui_item_layout(), ui_litem_layout_box(), and ui_litem_layout_root().
static void ui_litem_layout_column_flow (uiLayout * litem) [static]
Definition at line 1961 of file interface_layout.c.
References uiLayout::alignment, uiStyle::buttonspacey, uiStyle::columnspace, ListBase::first, uiLayout::h, uiLayout::items, MIN2, uiItem::next, NULL, uiLayout::root, uiLayoutRoot::style, uiLayoutItemFlow::totcol, ui_item_fit(), ui_item_position(), ui_item_size(), uiLayout::w, uiLayout::x, and uiLayout::y.
Referenced by ui_item_layout().
static void ui_litem_layout_overlap (uiLayout * litem) [static]
Definition at line 2159 of file interface_layout.c.
References ListBase::first, uiLayout::h, uiLayout::items, MAX2, uiItem::next, ui_item_position(), ui_item_size(), uiLayout::w, uiLayout::x, and uiLayout::y.
Referenced by ui_item_layout().
static void ui_litem_layout_root (uiLayout * litem) [static]
Definition at line 1848 of file interface_layout.c.
References uiLayout::root, uiLayoutRoot::type, UI_LAYOUT_HEADER, ui_litem_layout_column(), and ui_litem_layout_row().
Referenced by ui_item_layout().
static void ui_litem_layout_row (uiLayout * litem) [static]
Definition at line 1693 of file interface_layout.c.
References uiLayout::alignment, ListBase::first, uiItem::flag, uiLayout::items, uiItem::next, NULL, uiLayout::space, ui_item_fit(), ui_item_size(), ui_litem_min_width(), uiLayout::w, and uiLayout::y.
Referenced by ui_item_layout(), and ui_litem_layout_root().
static void ui_litem_layout_split (uiLayout * litem) [static]
Definition at line 2102 of file interface_layout.c.
References BLI_countlist(), ListBase::first, uiLayout::h, uiLayout::items, MAX2, uiItem::next, NULL, uiLayoutItemSplit::percentage, uiLayout::space, split(), ui_item_position(), ui_item_size(), uiLayout::w, uiLayout::x, and uiLayout::y.
Referenced by ui_item_layout().
static int ui_litem_min_width (int itemw) [static]
Definition at line 1688 of file interface_layout.c.
References MIN2, and UI_UNIT_X.
Referenced by ui_litem_layout_row().
static const char* ui_menu_enumpropname (uiLayout * layout, PointerRNA * ptr, PropertyRNA * prop, int retval) [static]
Definition at line 711 of file interface_layout.c.
References uiLayoutRoot::block, uiBlock::evil_C, MEM_freeN(), RNA_enum_name(), RNA_property_enum_items_gettexted(), and uiLayout::root.
Referenced by uiItemEnumO_ptr(), uiItemEnumO_ptr__internal(), uiItemEnumO_string(), and uiItemEnumO_value().
static int ui_text_icon_width (uiLayout * layout, const char * name, int icon, int compact) [static]
Definition at line 224 of file interface_layout.c.
References UI_GetStringWidth(), UI_ITEM_VARY_X, ui_layout_vary_direction(), and UI_UNIT_X.
Referenced by ui_item_disabled(), ui_item_enum_expand(), ui_item_menu(), ui_item_rna_size(), uiItemFullO_ptr(), uiItemL_(), and uiItemV().
uiLayout* uiBlockLayout (uiBlock * block, int dir, int type, int x, int y, int size, int em, uiStyle * style)
Definition at line 2612 of file interface_layout.c.
References uiLayout::active, BLI_addtail(), uiLayoutRoot::block, uiLayout::context, uiBlock::curlayout, uiLayoutRoot::emh, uiLayoutRoot::emw, uiLayout::enabled, uiLayout::h, uiLayout::item, ITEM_LAYOUT_ROOT, uiLayoutRoot::layout, uiBlock::layouts, MEM_callocN(), NULL, uiLayoutRoot::opcontext, uiLayout::root, size(), uiLayout::space, uiLayoutRoot::style, uiStyle::templatespace, uiItem::type, uiLayoutRoot::type, UI_LAYOUT_HORIZONTAL, UI_LAYOUT_MENU, UI_UNIT_X, UI_UNIT_Y, uiLayout::w, WM_OP_INVOKE_REGION_WIN, uiLayout::x, and uiLayout::y.
Referenced by ED_region_header(), ED_region_panels(), logic_buttons_new(), menu_add_shortcut(), menu_change_shortcut(), node_draw_group(), node_socket_button_output_file(), node_update_basis(), socket_component_menu(), ui_popup_menu_create(), uiPupMenuBegin(), wm_block_create_redo(), wm_block_create_splash(), wm_block_dialog_create(), and wm_operator_ui_create().
void uiBlockLayoutResolve (uiBlock * block, int * x, int * y)
Definition at line 2695 of file interface_layout.c.
References BLI_freelistN(), uiBlock::curlayout, ListBase::first, uiLayoutRoot::layout, uiBlock::layouts, uiLayoutRoot::next, NULL, ui_layout_end(), ui_layout_free(), and UI_template_fix_linking().
Referenced by ED_region_header(), ED_region_panels(), logic_buttons_new(), node_draw_group(), node_socket_button_output_file(), node_update_basis(), ui_block_func_POPUP(), and uiEndBlock().
void uiBlockSetCurLayout (uiBlock * block, uiLayout * layout)
Definition at line 2664 of file interface_layout.c.
References uiBlock::curlayout.
Referenced by ui_item_array(), ui_item_disabled(), ui_item_enum_expand(), ui_item_menu(), ui_item_with_label(), ui_layout_box(), ui_node_menu_column(), ui_template_node_link_menu(), uiItemFullO_ptr(), uiItemFullR(), uiItemL_(), uiItemS(), uiItemV(), uiLayoutAbsolute(), uiLayoutColumn(), uiLayoutColumnFlow(), uiLayoutOverlap(), uiLayoutRow(), uiLayoutSplit(), uiTemplateNodeLink(), uiTemplateOperatorSearch(), and uiTemplateRunningJobs().
MenuType* uiButGetMenuType (uiBut * but) [read]
Definition at line 2920 of file interface_layout.c.
References uiBut::menu_create_func, NULL, uiBut::poin, and ui_item_menutype_func().
Referenced by ui_menu_block_set_keymaps(), and ui_tooltip_create().
void uiFileBrowseContextProperty (const bContext * C, PointerRNA * ptr, PropertyRNA ** prop)
Definition at line 584 of file interface_layout.c.
References uiBlock::buttons, CTX_wm_region(), PointerRNA::data, ListBase::first, uiBut::flag, uiBut::next, uiBlock::next, NULL, uiBut::prev, PROP_STRING, RNA_property_type(), uiBut::rnapoin, uiBut::rnaprop, UI_BUT_LAST_ACTIVE, and ARegion::uiblocks.
void uiItemBooleanO (uiLayout * layout, const char * name, int icon, const char * opname, const char * propname, int value)
Definition at line 924 of file interface_layout.c.
References PointerRNA::data, uiLayoutRoot::opcontext, RNA_boolean_set(), uiLayout::root, UI_OPERATOR_ERROR_RET, uiItemFullO_ptr(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
Referenced by image_pack_invoke(), pose_ik_add_invoke(), and ui_but_menu().
void uiItemEnumO (uiLayout * layout, const char * opname, const char * name, int icon, const char * propname, int value)
Definition at line 763 of file interface_layout.c.
References RNA_warning, ui_item_disabled(), uiItemEnumO_ptr(), and WM_operatortype_find().
Referenced by armature_parent_set_invoke(), draw_actuator_header(), draw_controller_header(), draw_modifier(), draw_sensor_header(), graph_panel_view(), nla_fmodifier_add_invoke(), and parent_set_invoke().
void uiItemEnumO_ptr (uiLayout * layout, wmOperatorType * ot, const char * name, int icon, const char * propname, int value)
Definition at line 741 of file interface_layout.c.
References PointerRNA::data, uiLayoutRoot::opcontext, RNA_property_enum_set(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, uiLayout::root, PointerRNA::type, ui_menu_enumpropname(), uiItemFullO_ptr(), and WM_operator_properties_create_ptr().
Referenced by delete_invoke(), text_resolve_conflict_invoke(), and uiItemEnumO().
static void uiItemEnumO_ptr__internal (uiLayout * layout, wmOperatorType * ot, const char * name, int icon, PropertyRNA * prop, int value) [static]
Definition at line 730 of file interface_layout.c.
References PointerRNA::data, uiLayoutRoot::opcontext, RNA_property_enum_set(), uiLayout::root, ui_menu_enumpropname(), uiItemFullO_ptr(), and WM_operator_properties_create_ptr().
Referenced by uiItemsFullEnumO().
void uiItemEnumO_string (uiLayout * layout, const char * name, int icon, const char * opname, const char * propname, const char * value_str)
Definition at line 882 of file interface_layout.c.
References uiLayoutRoot::block, PointerRNA::data, uiBlock::evil_C, MEM_freeN(), NULL, uiLayoutRoot::opcontext, RNA_enum_value_from_id(), RNA_property_enum_items_gettexted(), RNA_property_enum_set(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, uiLayout::root, PointerRNA::type, ui_menu_enumpropname(), UI_OPERATOR_ERROR_RET, uiItemFullO_ptr(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
void uiItemEnumO_value (uiLayout * layout, const char * name, int icon, const char * opname, const char * propname, int value)
Definition at line 854 of file interface_layout.c.
References PointerRNA::data, uiLayoutRoot::opcontext, RNA_property_enum_set(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, uiLayout::root, PointerRNA::type, ui_menu_enumpropname(), UI_OPERATOR_ERROR_RET, uiItemFullO_ptr(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
void uiItemEnumR (uiLayout * layout, const char * name, int icon, struct PointerRNA * ptr, const char * propname, int value)
Definition at line 1137 of file interface_layout.c.
References PROP_ENUM, RNA_ENUM_VALUE, RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, PointerRNA::type, ui_item_disabled(), and uiItemFullR().
Referenced by uiItemsEnumR().
void uiItemEnumR_string (uiLayout * layout, struct PointerRNA * ptr, const char * propname, const char * value, const char * name, int icon)
Definition at line 1150 of file interface_layout.c.
References uiLayoutRoot::block, uiBlock::evil_C, EnumPropertyItem::identifier, MEM_freeN(), NULL, PROP_ENUM, RNA_ENUM_VALUE, RNA_enum_value_from_id(), RNA_property_enum_items_gettexted(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, uiLayout::root, PointerRNA::type, ui_item_disabled(), and uiItemFullR().
Referenced by draw_gpencil_panel().
void uiItemFloatO (uiLayout * layout, const char * name, int icon, const char * opname, const char * propname, float value)
Definition at line 950 of file interface_layout.c.
References PointerRNA::data, uiLayoutRoot::opcontext, RNA_float_set(), uiLayout::root, UI_OPERATOR_ERROR_RET, uiItemFullO_ptr(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
PointerRNA uiItemFullO (uiLayout * layout, const char * opname, const char * name, int icon, IDProperty * properties, int context, int flag)
Definition at line 702 of file interface_layout.c.
References PointerRNA_NULL, UI_OPERATOR_ERROR_RET, uiItemFullO_ptr(), and WM_operatortype_find().
Referenced by node_composit_buts_file_output_details(), parent_drop_invoke(), screen_area_options_invoke(), ui_but_menu(), uiItemO(), uiLayoutOperatorButs(), and view3d_panel_tool_shelf().
PointerRNA uiItemFullO_ptr (uiLayout * layout, wmOperatorType * ot, const char * name, int icon, IDProperty * properties, int context, int flag)
Definition at line 635 of file interface_layout.c.
References assert, uiLayoutRoot::block, BUT, PointerRNA::data, uiBut::flag, IDP_GROUP, IDP_New(), NULL, uiBut::optype, PointerRNA_NULL, uiLayout::redalert, RNA_struct_ui_name(), uiLayout::root, wmOperatorType::srna, uiLayoutRoot::type, UI_BUT_REDALERT, UI_EMBOSS, UI_EMBOSSN, UI_ITEM_O_RETURN_PROPS, UI_ITEM_R_NO_BG, UI_LAYOUT_MENU, UI_LAYOUT_TOOLBAR, ui_text_icon_width(), UI_TEXT_LEFT, UI_UNIT_Y, uiBlockSetCurLayout(), uiBlockSetEmboss(), uiButGetOperatorPtrRNA(), uiButSetFlag(), uiDefButO_ptr(), uiDefIconButO_ptr(), and uiDefIconTextButO_ptr().
Referenced by graph_fmodifier_add_invoke(), make_proxy_invoke(), node_composit_buts_renderlayers(), poselib_add_menu_invoke__replacemenu(), uiItemBooleanO(), uiItemEnumO_ptr(), uiItemEnumO_ptr__internal(), uiItemEnumO_string(), uiItemEnumO_value(), uiItemFloatO(), uiItemFullO(), uiItemIntO(), uiItemsFullEnumO(), uiItemStringO(), unpack_menu(), and WM_operator_confirm_message().
void uiItemFullR (uiLayout * layout, PointerRNA * ptr, PropertyRNA * prop, int index, int value, int flag, const char * name, int icon)
Definition at line 1027 of file interface_layout.c.
References uiLayoutRoot::block, ELEM4, FALSE, len(), NULL, NUM, NUMSLI, OPTION, PROP_BOOLEAN, PROP_ENUM, PROP_ENUM_FLAG, PROP_FLOAT, PROP_INT, PROP_POINTER, PROP_STRING, uiLayout::redalert, RNA_ENUM_VALUE, RNA_NO_INDEX, RNA_property_array_check(), RNA_property_array_length(), RNA_property_boolean_get(), RNA_property_boolean_get_index(), RNA_property_enum_get(), RNA_property_flag(), RNA_property_type(), RNA_property_ui_icon(), RNA_property_ui_name(), uiLayout::root, ROW, TOG, uiBut::type, uiLayoutRoot::type, ui_but_add_search(), UI_BUT_REDALERT, UI_EMBOSS, UI_EMBOSSN, ui_item_array(), ui_item_enum_expand(), ui_item_name_add_colon(), UI_ITEM_R_EXPAND, UI_ITEM_R_ICON_ONLY, UI_ITEM_R_NO_BG, UI_ITEM_R_SLIDER, UI_ITEM_R_TOGGLE, ui_item_rna_size(), ui_item_with_label(), UI_LAYOUT_MENU, UI_MAX_NAME_STR, uiBlockSetCurLayout(), uiBlockSetEmboss(), uiButSetFlag(), uiDefAutoButR(), uiDefButR_prop(), uiDefIconButR_prop(), and uiDefIconTextButR_prop().
Referenced by uiDefAutoButsRNA(), uiItemEnumR(), uiItemEnumR_string(), uiItemR(), and uiTemplateAnyID().
void uiItemIntO (uiLayout * layout, const char * name, int icon, const char * opname, const char * propname, int value)
Definition at line 937 of file interface_layout.c.
References PointerRNA::data, uiLayoutRoot::opcontext, RNA_int_set(), uiLayout::root, UI_OPERATOR_ERROR_RET, uiItemFullO_ptr(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
Referenced by file_panel_category(), pose_groups_menu_invoke(), poselib_add_menu_invoke(), repeat_history_invoke(), and undo_history_invoke().
void uiItemL (uiLayout * layout, const char * name, int icon)
Definition at line 1532 of file interface_layout.c.
References uiItemL_().
Referenced by ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), clip_panel_operator_redo_operator(), draw_actuator_armature(), draw_actuator_constraint(), draw_actuator_edit_object(), draw_actuator_header(), draw_actuator_motion(), draw_actuator_random(), draw_actuator_shape_action(), draw_actuator_sound(), draw_constraint(), draw_controller_header(), draw_gpencil_panel(), draw_modifier(), draw_modifier__cycles(), draw_modifier__envelope(), draw_sensor_armature(), draw_sensor_header(), draw_sensor_keyboard(), file_panel_bookmarks(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_key_properties(), graph_panel_properties(), list_item_row(), logic_buttons_new(), nla_panel_actclip(), nla_panel_properties(), node_composit_buts_blur(), node_composit_buts_channel_matte(), node_composit_buts_color_spill(), node_composit_buts_dblur(), node_composit_buts_defocus(), node_composit_buts_double_edge_mask(), node_composit_buts_file_output(), node_composit_buts_file_output_details(), node_composit_buts_image(), node_composit_buts_vecblur(), node_shader_buts_mapping(), node_socket_button_output_file(), node_sockets_panel(), recent_files_menu_draw(), template_keymap_item_properties(), template_texture_user_menu(), ui_block_func_MENUSTR(), ui_node_draw_input(), ui_node_menu_column(), ui_template_node_link_menu(), uiblock_layer_pass_arrow_buttons(), uiDefAutoButsRNA(), uiItemsEnumR(), uiItemsFullEnumO(), uiLayoutOperatorButs(), uiTemplateAnyID(), uiTemplateImage(), uiTemplateImageSettings(), uiTemplateList(), uiTemplateTextureUser(), v3d_editarmature_buts(), v3d_editmetaball_buts(), v3d_posearmature_buts(), v3d_transform_butsR(), view3d_panel_operator_redo_operator(), wm_block_create_redo(), and wm_block_create_splash().
static uiBut* uiItemL_ (uiLayout * layout, const char * name, int icon) [static]
Definition at line 1507 of file interface_layout.c.
References uiLayoutRoot::block, LABEL, NULL, uiLayout::root, uiLayoutRoot::type, UI_LAYOUT_MENU, ui_text_icon_width(), UI_UNIT_Y, uiBlockSetCurLayout(), uiDefBut(), uiDefIconBut(), and uiDefIconTextBut().
Referenced by uiItemL(), and uiItemLDrag().
void uiItemLDrag (uiLayout * layout, PointerRNA * ptr, const char * name, int icon)
Definition at line 1537 of file interface_layout.c.
References PointerRNA::data, PointerRNA::id, RNA_struct_is_ID(), PointerRNA::type, uiButSetDragID(), and uiItemL_().
Referenced by buttons_context_draw().
void uiItemM (uiLayout * layout, bContext * UNUSEDC, const char * menuname, const char * name, int icon)
Definition at line 1485 of file interface_layout.c.
References MenuType::description, FALSE, IFACE_, MenuType::label, mt, NULL, RNA_warning, uiLayout::root, TIP_, uiLayoutRoot::type, ui_item_menu(), ui_item_menutype_func(), UI_LAYOUT_MENU, and WM_menutype_find().
void uiItemMenuEnumO (uiLayout * layout, const char * opname, const char * propname, const char * name, int icon)
Definition at line 1607 of file interface_layout.c.
References BLI_strncpy(), MEM_callocN(), menu_item_enum_opname_menu(), NULL, uiLayoutRoot::opcontext, MenuItemLevel::opcontext, MenuItemLevel::opname, MenuItemLevel::propname, RNA_struct_ui_description(), RNA_struct_ui_name(), RNA_warning, uiLayout::root, wmOperatorType::srna, uiLayoutRoot::type, ui_item_disabled(), ui_item_menu(), UI_LAYOUT_MENU, UI_OPERATOR_ERROR_RET, and WM_operatortype_find().
Referenced by logic_buttons_new().
void uiItemMenuEnumR (uiLayout * layout, struct PointerRNA * ptr, const char * propname, const char * name, int icon)
Definition at line 1641 of file interface_layout.c.
References BLI_strncpy(), MEM_callocN(), menu_item_enum_rna_menu(), NULL, uiLayoutRoot::opcontext, MenuItemLevel::opcontext, MenuItemLevel::propname, RNA_property_description(), RNA_property_ui_name(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, MenuItemLevel::rnapoin, uiLayout::root, uiLayoutRoot::type, PointerRNA::type, ui_item_disabled(), ui_item_menu(), and UI_LAYOUT_MENU.
void uiItemMenuF (uiLayout * layout, const char * name, int icon, uiMenuCreateFunc func, void * arg)
Definition at line 1582 of file interface_layout.c.
References NULL, and ui_item_menu().
Referenced by node_menu_add_foreach_cb(), and poselib_add_menu_invoke().
void uiItemO (uiLayout * layout, const char * name, int icon, const char * opname)
Definition at line 976 of file interface_layout.c.
References NULL, uiLayoutRoot::opcontext, uiLayout::root, and uiItemFullO().
Referenced by active_node_panel(), draw_actuator_header(), draw_constraint(), draw_controller_header(), draw_gpencil_panel(), draw_modifier(), draw_sensor_header(), file_panel_bookmarks(), graph_panel_modifiers(), graph_panel_view(), header_toolbox_invoke(), nla_panel_actclip(), nla_panel_modifiers(), node_composit_buts_file_output_details(), ui_but_menu(), uiTemplateImage(), uiTemplateMovieClip(), and wm_block_create_splash().
void uiItemPointerR (uiLayout * layout, struct PointerRNA * ptr, const char * propname, struct PointerRNA * searchptr, const char * searchpropname, const char * name, int icon)
Definition at line 1376 of file interface_layout.c.
References ELEM, PROP_COLLECTION, PROP_POINTER, PROP_STRING, RNA_property_pointer_type(), RNA_property_type(), RNA_property_ui_name(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_struct_ui_icon(), RNA_warning, PointerRNA::type, ui_but_add_search(), ui_item_rna_size(), ui_item_with_label(), and uiLayoutGetBlock().
Referenced by draw_actuator_action(), draw_actuator_armature(), draw_actuator_constraint(), draw_actuator_message(), draw_actuator_property(), draw_actuator_random(), draw_actuator_shape_action(), draw_sensor_actuator(), draw_sensor_armature(), draw_sensor_collision(), draw_sensor_keyboard(), draw_sensor_property(), draw_sensor_ray(), graph_panel_driverVar__locDiff(), graph_panel_driverVar__rotDiff(), graph_panel_driverVar__transChan(), and node_shader_buts_geometry().
void uiItemR (uiLayout * layout, PointerRNA * ptr, const char * propname, int flag, const char * name, int icon)
Definition at line 1124 of file interface_layout.c.
References RNA_NO_INDEX, RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, PointerRNA::type, ui_item_disabled(), and uiItemFullR().
Referenced by active_node_panel(), ANIM_uiTemplate_fmodifier_draw(), colorband_buttons_large(), colorband_buttons_small(), curvemap_buttons_layout(), draw_actuator_action(), draw_actuator_armature(), draw_actuator_camera(), draw_actuator_constraint(), draw_actuator_edit_object(), draw_actuator_filter_2d(), draw_actuator_game(), draw_actuator_header(), draw_actuator_message(), draw_actuator_motion(), draw_actuator_parent(), draw_actuator_property(), draw_actuator_random(), draw_actuator_scene(), draw_actuator_shape_action(), draw_actuator_sound(), draw_actuator_state(), draw_actuator_steering(), draw_actuator_visibility(), draw_constraint(), draw_controller_expression(), draw_controller_header(), draw_controller_python(), draw_gpencil_panel(), draw_modifier(), draw_modifier__cycles(), draw_modifier__envelope(), draw_modifier__fn_generator(), draw_modifier__limits(), draw_modifier__noise(), draw_modifier__stepped(), draw_sensor_armature(), draw_sensor_collision(), draw_sensor_delay(), draw_sensor_header(), draw_sensor_internal_header(), draw_sensor_joystick(), draw_sensor_keyboard(), draw_sensor_message(), draw_sensor_mouse(), draw_sensor_near(), draw_sensor_property(), draw_sensor_radar(), draw_sensor_random(), draw_sensor_ray(), draw_sensor_touch(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_driverVar__locDiff(), graph_panel_driverVar__transChan(), graph_panel_key_properties(), graph_panel_properties(), graph_panel_view(), list_item_row(), logic_buttons_new(), menu_add_shortcut(), menu_change_shortcut(), nla_panel_actclip(), nla_panel_animdata(), nla_panel_evaluation(), nla_panel_properties(), nla_panel_track(), node_buts_math(), node_buts_mix_rgb(), node_buts_rgb(), node_buts_texture(), node_buts_time(), node_buts_value(), node_common_buts_whileloop(), node_composit_buts_alphaover(), node_composit_buts_bilateralblur(), node_composit_buts_blur(), node_composit_buts_channel_matte(), node_composit_buts_chroma_matte(), node_composit_buts_color_matte(), node_composit_buts_color_spill(), node_composit_buts_colorbalance(), node_composit_buts_colorbalance_but(), node_composit_buts_crop(), node_composit_buts_dblur(), node_composit_buts_defocus(), node_composit_buts_diff_matte(), node_composit_buts_dilateerode(), node_composit_buts_distance_matte(), node_composit_buts_double_edge_mask(), node_composit_buts_file_output(), node_composit_buts_file_output_details(), node_composit_buts_filter(), node_composit_buts_flip(), node_composit_buts_glare(), node_composit_buts_hue_sat(), node_composit_buts_id_mask(), node_composit_buts_image(), node_composit_buts_invert(), node_composit_buts_lensdist(), node_composit_buts_luma_matte(), node_composit_buts_map_uv(), node_composit_buts_map_value(), node_composit_buts_moviedistortion(), node_composit_buts_premulkey(), node_composit_buts_renderlayers(), node_composit_buts_rotate(), node_composit_buts_scale(), node_composit_buts_splitviewer(), node_composit_buts_stabilize2d(), node_composit_buts_tonemap(), node_composit_buts_transform(), node_composit_buts_vecblur(), node_composit_buts_view_levels(), node_composit_buts_ycc(), node_composit_buts_zcombine(), node_shader_buts_attribute(), node_shader_buts_geometry(), node_shader_buts_glossy(), node_shader_buts_mapping(), node_shader_buts_material(), node_shader_buts_tex_environment(), node_shader_buts_tex_gradient(), node_shader_buts_tex_image(), node_shader_buts_tex_magic(), node_shader_buts_tex_musgrave(), node_shader_buts_tex_sky(), node_shader_buts_tex_voronoi(), node_shader_buts_tex_wave(), node_shader_buts_vect_math(), node_texture_buts_bricks(), node_texture_buts_output(), node_texture_buts_proc(), socket_component_menu(), template_keymap_item_properties(), ui_node_draw_input(), uiTemplateHeader3D(), uiTemplateImage(), uiTemplateImageSettings(), uiTemplateMovieClip(), uiTemplatePathBuilder(), uiTemplatePreview(), v3d_editarmature_buts(), v3d_editmetaball_buts(), and v3d_transform_butsR().
void uiItemS (uiLayout * layout)
Definition at line 1573 of file interface_layout.c.
References uiLayoutRoot::block, EM_SEPR_X, EM_SEPR_Y, NULL, uiLayout::root, SEPR, uiBlockSetCurLayout(), and uiDefBut().
Referenced by active_node_panel(), graph_fmodifier_add_invoke(), header_toolbox_invoke(), logic_buttons_new(), nla_fmodifier_add_invoke(), node_add_menu(), node_composit_buts_dblur(), node_composit_buts_file_output_details(), pose_groups_menu_invoke(), template_keymap_item_properties(), ui_block_func_ICONTEXTROW(), ui_but_menu(), ui_node_draw_input(), uiItemsEnumR(), uiItemsFullEnumO(), uiTemplateColorWheel(), uiTemplateImage(), and wm_block_create_splash().
void uiItemsEnumO (uiLayout * layout, const char * opname, const char * propname)
Definition at line 848 of file interface_layout.c.
References NULL, uiLayoutRoot::opcontext, uiLayout::root, and uiItemsFullEnumO().
Referenced by delete_invoke(), insert_key_menu_invoke(), keyingset_active_menu_invoke(), menu_item_enum_opname_menu(), object_metaball_add_invoke(), select_orientation_invoke(), toggle_cyclic_invoke(), and unpack_all_invoke().
void uiItemsEnumR (uiLayout * layout, struct PointerRNA * ptr, const char * propname)
Definition at line 1185 of file interface_layout.c.
References uiLayoutRoot::block, uiBlock::buttons, uiBlock::evil_C, uiBut::flag, uiBlock::flag, i, ListBase::last, MEM_freeN(), PROP_ENUM, RNA_property_enum_items_gettexted(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, uiLayout::root, split(), PointerRNA::type, UI_BLOCK_NO_FLIP, ui_item_disabled(), UI_TEXT_LEFT, uiItemEnumR(), uiItemL(), uiItemS(), uiLayoutColumn(), and uiLayoutSplit().
Referenced by menu_item_enum_rna_menu(), and toolbox_invoke().
void uiItemsFullEnumO (uiLayout * layout, const char * opname, const char * propname, IDProperty * properties, int context, int flag)
Definition at line 777 of file interface_layout.c.
References BLI_assert, uiLayoutRoot::block, uiBlock::buttons, PointerRNA::data, uiBlock::evil_C, uiBut::flag, uiBlock::flag, i, IDP_CopyProperty(), IDP_FreeProperty(), ListBase::last, MEM_freeN(), NULL, PROP_ENUM, RNA_pointer_create(), RNA_property_enum_items_gettexted(), RNA_property_enum_set(), RNA_property_type(), RNA_struct_find_property(), RNA_warning, uiLayout::root, split(), wmOperatorType::srna, UI_BLOCK_NO_FLIP, ui_item_disabled(), UI_TEXT_LEFT, uiItemEnumO_ptr__internal(), uiItemFullO_ptr(), uiItemL(), uiItemS(), uiLayoutColumn(), uiLayoutSplit(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
Referenced by uiItemsEnumO(), and WM_menu_invoke().
void uiItemStringO (uiLayout * layout, const char * name, int icon, const char * opname, const char * propname, const char * value)
Definition at line 963 of file interface_layout.c.
References PointerRNA::data, uiLayoutRoot::opcontext, RNA_string_set(), uiLayout::root, UI_OPERATOR_ERROR_RET, uiItemFullO_ptr(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
Referenced by draw_modifier(), recent_files_menu_draw(), select_grouped_group(), and wm_block_create_splash().
void uiItemV (uiLayout * layout, const char * name, int icon, int argval)
Definition at line 1548 of file interface_layout.c.
References uiLayoutRoot::block, BUT, uiBlock::handle, NULL, uiPopupBlockHandle::retvalue, uiLayout::root, uiLayoutRoot::type, UI_LAYOUT_MENU, ui_text_icon_width(), UI_UNIT_Y, uiBlockSetCurLayout(), uiDefButF(), uiDefIconButF(), and uiDefIconTextButF().
Referenced by node_add_menu().
uiLayout* uiLayoutAbsolute (uiLayout * layout, int align)
Definition at line 2279 of file interface_layout.c.
References uiLayout::active, uiLayout::align, BLI_addtail(), uiLayoutRoot::block, uiLayout::context, uiLayout::enabled, uiLayout::item, ITEM_LAYOUT_ABSOLUTE, uiLayout::items, MEM_callocN(), uiLayout::root, uiItem::type, and uiBlockSetCurLayout().
Referenced by ui_item_array(), uiLayoutAbsoluteBlock(), uiTemplateReportsBanner(), and uiTemplateRunningJobs().
uiBlock* uiLayoutAbsoluteBlock (uiLayout * layout)
Definition at line 2297 of file interface_layout.c.
References uiLayoutAbsolute(), and uiLayoutGetBlock().
Referenced by draw_constraint(), draw_modifier(), image_panel_uv(), node_buts_normal(), node_shader_buts_dynamic(), uiTemplateColorRamp(), uiTemplateHeader(), uiTemplateHistogram(), uiTemplateMarker(), uiTemplateTrack(), uiTemplateVectorscope(), uiTemplateWaveform(), v3d_editvertex_buts(), and view3d_panel_vgroup().
uiLayout* uiLayoutBox (uiLayout * layout)
Definition at line 2261 of file interface_layout.c.
References ROUNDBOX, and ui_layout_box().
Referenced by ANIM_uiTemplate_fmodifier_draw(), draw_actuator_header(), draw_brick_actuator(), draw_brick_controller(), draw_brick_sensor(), draw_constraint(), draw_controller_header(), draw_modifier(), draw_sensor_header(), draw_sensor_internal_header(), file_panel_category(), gp_drawui_layer(), graph_panel_drivers(), and logic_buttons_new().
uiLayout* uiLayoutColumn (uiLayout * layout, int align)
Definition at line 2199 of file interface_layout.c.
References uiLayout::active, uiLayout::align, BLI_addtail(), uiLayoutRoot::block, uiStyle::buttonspacey, uiLayout::context, uiLayout::enabled, uiLayout::item, ITEM_LAYOUT_COLUMN, uiLayout::items, MEM_callocN(), uiLayout::root, uiLayout::space, uiLayoutRoot::style, uiItem::type, uiBlockSetCurLayout(), and uiLayout::w.
Referenced by ANIM_uiTemplate_fmodifier_draw(), curvemap_buttons_layout(), draw_actuator_action(), draw_actuator_constraint(), draw_actuator_motion(), draw_actuator_sound(), draw_actuator_steering(), draw_constraint(), draw_gpencil_panel(), draw_modifier(), draw_modifier__cycles(), draw_modifier__envelope(), draw_modifier__fn_generator(), draw_modifier__limits(), draw_modifier__noise(), draw_modifier__stepped(), draw_sensor_joystick(), draw_sensor_keyboard(), file_panel_category(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_driverVar__locDiff(), graph_panel_driverVar__rotDiff(), graph_panel_driverVar__singleProp(), graph_panel_driverVar__transChan(), graph_panel_key_properties(), graph_panel_modifiers(), graph_panel_properties(), graph_panel_view(), logic_buttons_new(), nla_panel_actclip(), nla_panel_evaluation(), nla_panel_modifiers(), nla_panel_properties(), node_buts_rgb(), node_composit_buts_alphaover(), node_composit_buts_bilateralblur(), node_composit_buts_blur(), node_composit_buts_channel_matte(), node_composit_buts_chroma_matte(), node_composit_buts_color_matte(), node_composit_buts_color_spill(), node_composit_buts_colorbalance(), node_composit_buts_crop(), node_composit_buts_dblur(), node_composit_buts_defocus(), node_composit_buts_diff_matte(), node_composit_buts_distance_matte(), node_composit_buts_double_edge_mask(), node_composit_buts_file_output_details(), node_composit_buts_hue_sat(), node_composit_buts_image(), node_composit_buts_invert(), node_composit_buts_lensdist(), node_composit_buts_luma_matte(), node_composit_buts_map_value(), node_composit_buts_renderlayers(), node_composit_buts_splitviewer(), node_composit_buts_tonemap(), node_composit_buts_vecblur(), node_composit_buts_zcombine(), node_shader_buts_geometry(), node_shader_buts_material(), node_texture_buts_bricks(), node_texture_buts_proc(), socket_component_menu(), ui_block_func_MENUSTR(), ui_item_local_sublayout(), ui_node_draw_input(), ui_node_draw_node(), ui_node_menu_column(), ui_template_node_link_menu(), uiDefAutoButsRNA(), uiItemsEnumR(), uiItemsFullEnumO(), uiLayoutOperatorButs(), uiTemplateColorWheel(), uiTemplateImage(), uiTemplateImageSettings(), uiTemplateLayers(), uiTemplateList(), uiTemplateMarker(), uiTemplatePreview(), undo_history_invoke(), v3d_editarmature_buts(), v3d_editmetaball_buts(), v3d_posearmature_buts(), v3d_transform_butsR(), view3d_panel_object(), view3d_panel_tool_shelf(), view3d_panel_vgroup(), wm_block_create_splash(), and wm_block_dialog_create().
uiLayout* uiLayoutColumnFlow (uiLayout * layout, int number, int align)
Definition at line 2219 of file interface_layout.c.
References uiLayout::active, uiLayout::align, BLI_addtail(), uiLayoutRoot::block, uiStyle::columnspace, uiLayout::context, uiLayout::enabled, uiLayout::item, ITEM_LAYOUT_COLUMN_FLOW, uiLayout::items, uiLayoutItemFlow::litem, MEM_callocN(), uiLayoutItemFlow::number, uiLayout::root, uiLayout::space, uiLayoutRoot::style, uiItem::type, uiBlockSetCurLayout(), and uiLayout::w.
Referenced by template_keymap_item_properties().
void uiLayoutContextCopy (uiLayout * layout, bContextStore * context)
Definition at line 2725 of file interface_layout.c.
References uiLayoutRoot::block, uiLayout::context, uiBlock::contexts, CTX_store_add_all(), and uiLayout::root.
Referenced by ui_popup_menu_create().
int uiLayoutGetActive (uiLayout * layout)
Definition at line 2380 of file interface_layout.c.
References uiLayout::active.
int uiLayoutGetAlignment (uiLayout * layout)
Definition at line 2400 of file interface_layout.c.
References uiLayout::alignment.
uiBlock* uiLayoutGetBlock (uiLayout * layout)
Definition at line 2653 of file interface_layout.c.
References uiLayoutRoot::block, and uiLayout::root.
Referenced by ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), clip_panel_operator_redo(), curvemap_buttons_layout(), draw_constraint(), draw_controller_header(), draw_modifier(), draw_modifier__envelope(), draw_modifier__generator(), file_panel_category(), file_panel_operator(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_key_properties(), graph_panel_modifiers(), graph_panel_properties(), list_item_row(), nla_panel_actclip(), nla_panel_animdata(), nla_panel_evaluation(), nla_panel_modifiers(), nla_panel_properties(), nla_panel_track(), template_ID(), template_texture_user_menu(), ui_block_func_ICONROW(), ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), ui_but_menu(), ui_node_draw_input(), ui_node_menu_column(), ui_template_node_link_menu(), uiblock_layer_pass_arrow_buttons(), uiblock_layer_pass_buttons(), uiItemPointerR(), uiLayoutAbsoluteBlock(), uiLayoutOperatorButs(), uiTemplateColorWheel(), uiTemplateConstraint(), uiTemplateEditModeSelection(), uiTemplateHeader3D(), uiTemplateImage(), uiTemplateKeymapItemProperties(), uiTemplateLayers(), uiTemplateList(), uiTemplateMarker(), uiTemplateModifier(), uiTemplateMovieClip(), uiTemplateNodeLink(), uiTemplateOperatorSearch(), uiTemplatePreview(), uiTemplateReportsBanner(), uiTemplateRunningJobs(), uiTemplateTextureShow(), uiTemplateTextureUser(), view3d_panel_object(), view3d_panel_operator_redo(), view3d_panel_tool_shelf(), and wm_block_dialog_create().
int uiLayoutGetEnabled (uiLayout * layout)
Definition at line 2385 of file interface_layout.c.
References uiLayout::enabled.
int uiLayoutGetKeepAspect (uiLayout * layout)
Definition at line 2395 of file interface_layout.c.
References uiLayout::keepaspect.
int uiLayoutGetOperatorContext (uiLayout * layout)
Definition at line 2658 of file interface_layout.c.
References uiLayoutRoot::opcontext, and uiLayout::root.
int uiLayoutGetRedAlert (uiLayout * layout)
Definition at line 2390 of file interface_layout.c.
References uiLayout::redalert.
float uiLayoutGetScaleX (uiLayout * layout)
Definition at line 2410 of file interface_layout.c.
References uiLayout::scale.
float uiLayoutGetScaleY (uiLayout * layout)
Definition at line 2415 of file interface_layout.c.
References uiLayout::scale.
int uiLayoutGetWidth (uiLayout * layout)
Definition at line 2405 of file interface_layout.c.
References uiLayout::w.
Referenced by curvemap_buttons_layout(), ED_region_header(), and ui_but_menu().
const char* uiLayoutIntrospect (uiLayout * layout)
Definition at line 2803 of file interface_layout.c.
References BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), MEM_freeN(), str, and ui_intro_uiLayout().
uiLayout* uiLayoutListBox (uiLayout * layout, PointerRNA * ptr, PropertyRNA * prop, PointerRNA * actptr, PropertyRNA * actprop)
Definition at line 2266 of file interface_layout.c.
References LISTBOX, uiBut::rnapoin, uiBut::rnaprop, uiBut::rnasearchpoin, uiBut::rnasearchprop, uiLayoutItemBx::roundbox, and ui_layout_box().
Referenced by uiTemplateList().
void uiLayoutOperatorButs (const bContext * C, uiLayout * layout, wmOperator * op, int(*)(struct PointerRNA *, struct PropertyRNA *) check_prop, const char label_align, const short flag)
Definition at line 2825 of file interface_layout.c.
References BUT, CTX_wm_manager(), CTX_wm_window(), PointerRNA::data, wmOperatorType::flag, wmWindowManager::id, wmOperatorType::idname, IDP_GROUP, IDP_New(), IFACE_, wmOperator::layout, IDProperty::len, uiBut::next, NULL, OPTYPE_PRESET, wmOperatorType::prop, wmOperator::properties, RNA_boolean_set(), RNA_pointer_create(), RNA_string_set(), RNA_struct_ui_name(), uiBut::rnaprop, wmOperatorType::srna, TEX, TIP_, TRUE, wmOperator::type, uiBut::type, wmOperatorType::ui, UI_BUT_UNDO, UI_LAYOUT_OP_SHOW_EMPTY, UI_LAYOUT_OP_SHOW_TITLE, ui_layout_operator_buts__reset_cb(), uiBlock::ui_operator, uiBlockSetButLock(), uiButClearFlag(), uiButSetFocusOnEnter(), uiButSetFunc(), uiDefAutoButsRNA(), uiDefIconTextBut(), uiItemFullO(), uiItemL(), uiItemM(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), WM_OP_INVOKE_DEFAULT, WM_operator_properties_create(), and WM_operator_repeat_check().
uiLayout* uiLayoutOverlap (uiLayout * layout)
Definition at line 2307 of file interface_layout.c.
References uiLayout::active, BLI_addtail(), uiLayoutRoot::block, uiLayout::context, uiLayout::enabled, uiLayout::item, ITEM_LAYOUT_OVERLAP, uiLayout::items, MEM_callocN(), uiLayout::root, uiItem::type, and uiBlockSetCurLayout().
Referenced by list_item_row().
uiLayout* uiLayoutRow (uiLayout * layout, int align)
Definition at line 2179 of file interface_layout.c.
References uiLayout::active, uiLayout::align, BLI_addtail(), uiLayoutRoot::block, uiStyle::buttonspacex, uiLayout::context, uiLayout::enabled, uiLayout::item, ITEM_LAYOUT_ROW, uiLayout::items, MEM_callocN(), uiLayout::root, uiLayout::space, uiLayoutRoot::style, uiItem::type, uiBlockSetCurLayout(), and uiLayout::w.
Referenced by ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), colorband_buttons_large(), curvemap_buttons_layout(), draw_actuator_action(), draw_actuator_camera(), draw_actuator_constraint(), draw_actuator_edit_object(), draw_actuator_filter_2d(), draw_actuator_header(), draw_actuator_message(), draw_actuator_motion(), draw_actuator_parent(), draw_actuator_property(), draw_actuator_random(), draw_actuator_shape_action(), draw_actuator_sound(), draw_actuator_steering(), draw_actuator_visibility(), draw_constraint(), draw_controller_header(), draw_gpencil_panel(), draw_modifier(), draw_modifier__envelope(), draw_modifier__generator(), draw_sensor_armature(), draw_sensor_collision(), draw_sensor_delay(), draw_sensor_header(), draw_sensor_internal_header(), draw_sensor_joystick(), draw_sensor_keyboard(), draw_sensor_near(), draw_sensor_property(), draw_sensor_radar(), draw_sensor_ray(), file_panel_bookmarks(), file_panel_category(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_driverVar__singleProp(), graph_panel_modifiers(), graph_panel_properties(), list_item_row(), logic_buttons_new(), nla_panel_actclip(), nla_panel_animdata(), nla_panel_evaluation(), nla_panel_modifiers(), nla_panel_properties(), nla_panel_track(), node_buts_mix_rgb(), node_buts_time(), node_composit_buts_blur(), node_composit_buts_channel_matte(), node_composit_buts_color_spill(), node_composit_buts_colorbalance(), node_composit_buts_file_output_details(), node_composit_buts_renderlayers(), node_composit_buts_splitviewer(), node_shader_buts_mapping(), node_socket_button_output_file(), node_texture_buts_proc(), template_ID(), ui_item_local_sublayout(), ui_item_with_label(), ui_node_draw_input(), ui_template_id(), uiblock_layer_pass_arrow_buttons(), uiblock_layer_pass_buttons(), uiLayoutOperatorButs(), uiTemplateAnyID(), uiTemplateColorWheel(), uiTemplateEditModeSelection(), uiTemplateHeader3D(), uiTemplateImage(), uiTemplateImageSettings(), uiTemplateLayers(), uiTemplateList(), uiTemplateMovieClip(), uiTemplatePathBuilder(), uiTemplatePreview(), and uiTemplateRunningJobs().
void uiLayoutSetActive (uiLayout * layout, int active)
Definition at line 2345 of file interface_layout.c.
References uiLayout::active.
Referenced by draw_actuator_action(), draw_actuator_constraint(), draw_actuator_filter_2d(), draw_actuator_header(), draw_actuator_motion(), draw_actuator_parent(), draw_actuator_property(), draw_actuator_sound(), draw_actuator_steering(), draw_gpencil_panel(), draw_modifier__stepped(), draw_sensor_header(), draw_sensor_internal_header(), draw_sensor_joystick(), draw_sensor_keyboard(), graph_panel_view(), list_item_row(), logic_buttons_new(), nla_panel_actclip(), nla_panel_properties(), node_composit_buts_defocus(), node_composit_buts_file_output_details(), node_composit_buts_lensdist(), node_composit_buts_map_value(), node_menu_add(), node_texture_buts_proc(), uiTemplateImage(), uiTemplateMarker(), and v3d_transform_butsR().
void uiLayoutSetAlignment (uiLayout * layout, int alignment)
Definition at line 2365 of file interface_layout.c.
References uiLayout::alignment.
Referenced by ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), curvemap_buttons_layout(), draw_modifier(), file_panel_category(), gp_drawui_layer(), and logic_buttons_new().
void uiLayoutSetContextPointer (uiLayout * layout, const char * name, PointerRNA * ptr)
Definition at line 2719 of file interface_layout.c.
References uiLayoutRoot::block, uiLayout::context, uiBlock::contexts, CTX_store_add(), and uiLayout::root.
Referenced by draw_constraint(), draw_modifier(), logic_buttons_new(), uiTemplateImage(), and uiTemplateMovieClip().
void uiLayoutSetEnabled (uiLayout * layout, int enabled)
Definition at line 2350 of file interface_layout.c.
References uiLayout::enabled.
Referenced by clip_panel_operator_redo(), graph_panel_properties(), nla_panel_evaluation(), uiTemplateImage(), view3d_panel_operator_redo(), and wm_block_create_redo().
void uiLayoutSetFunc (uiLayout * layout, uiMenuHandleFunc handlefunc, void * argv)
Definition at line 2689 of file interface_layout.c.
References uiLayoutRoot::argv, uiLayoutRoot::handlefunc, and uiLayout::root.
Referenced by node_add_menu().
void uiLayoutSetKeepAspect (uiLayout * layout, int keepaspect)
Definition at line 2360 of file interface_layout.c.
References uiLayout::keepaspect.
Referenced by uiTemplatePreview().
void uiLayoutSetOperatorContext (uiLayout * layout, int opcontext)
Definition at line 2684 of file interface_layout.c.
References uiLayoutRoot::opcontext, and uiLayout::root.
Referenced by draw_constraint(), draw_modifier(), menu_item_enum_opname_menu(), menu_item_enum_rna_menu(), parent_set_invoke(), poselib_add_menu_invoke(), poselib_add_menu_invoke__replacemenu(), recent_files_menu_draw(), ui_but_menu(), ui_popup_menu_create(), uiPupMenuBegin(), unpack_all_invoke(), and wm_block_create_splash().
void uiLayoutSetRedAlert (uiLayout * layout, int redalert)
Definition at line 2355 of file interface_layout.c.
References uiLayout::redalert.
Referenced by draw_constraint().
void uiLayoutSetScaleX (uiLayout * layout, float scale)
Definition at line 2370 of file interface_layout.c.
References uiLayout::scale.
Referenced by uiTemplatePreview().
void uiLayoutSetScaleY (uiLayout * layout, float scale)
Definition at line 2375 of file interface_layout.c.
References uiLayout::scale.
uiLayout* uiLayoutSplit (uiLayout * layout, float percentage, int align)
Definition at line 2324 of file interface_layout.c.
References uiLayout::active, uiLayout::align, BLI_addtail(), uiLayoutRoot::block, uiStyle::columnspace, uiLayout::context, uiLayout::enabled, uiLayout::item, ITEM_LAYOUT_SPLIT, uiLayout::items, uiLayoutItemSplit::litem, MEM_callocN(), uiLayoutItemSplit::percentage, uiLayout::root, uiLayout::space, split(), uiLayoutRoot::style, uiItem::type, uiBlockSetCurLayout(), and uiLayout::w.
Referenced by curvemap_buttons_layout(), draw_actuator_constraint(), draw_actuator_edit_object(), draw_actuator_filter_2d(), draw_actuator_motion(), draw_actuator_state(), draw_controller_python(), draw_modifier__cycles(), draw_modifier__limits(), draw_modifier__noise(), draw_sensor_collision(), draw_sensor_internal_header(), draw_sensor_ray(), gp_drawui_layer(), graph_panel_view(), list_item_row(), logic_buttons_new(), node_composit_buts_colorbalance(), node_sockets_panel(), ui_block_func_MENUSTR(), ui_node_draw_input(), ui_node_draw_node(), ui_template_node_link_menu(), uiDefAutoButsRNA(), uiItemsEnumR(), uiItemsFullEnumO(), uiTemplateImage(), uiTemplateImageSettings(), uiTemplateMovieClip(), undo_history_invoke(), v3d_transform_butsR(), and wm_block_create_splash().
Variable Documentation
char* str = NULL [static]
Definition at line 2802 of file interface_layout.c.
Referenced by add_name(), add_text(), arraysize(), BakeTime(), Bevel(), BevelWeight(), BKE_add_image_file(), BKE_add_movieclip_file(), BKE_undo_save_quit(), BL_ConvertTextProperty(), BLI_str_find_prev_char_utf8(), BLI_utf8_invalid_byte(), BLO_blendhandle_get_linkable_groups(), BoneEnvelope(), BoneRoll(), BoneSize(), bpy_lib_enter(), bUnit_ReplaceString(), change_plugin_seq(), check_destination(), console_draw_string(), console_history_append_exec(), console_insert_exec(), console_insert_invoke(), console_lb_add_str__internal(), console_scrollback_append_exec(), copy_attr_menu(), copymenu_properties(), cp_property(), Crease(), CurveShrinkFatten(), display_info(), DM_debug_print(), DNA_elem_array_size(), do_versions(), draw_actuatorbuttons(), draw_marker_texts(), draw_modifier(), draw_movieclip_notes(), draw_sensorbuttons(), draw_seq_text(), draw_suggestion_list(), dynamicPaint_paintParticles(), ED_image_draw_info(), ed_marker_move_modal(), ed_undo_push_exec(), EdgeSlide(), editFont_to_undoFont(), exr_rgba_channelname(), file_browse_exec(), file_browse_invoke(), file_delete_exec(), get_words(), gpu_str_skip_token(), STR_HashedString::hash(), headerResize(), headerTranslation(), ibJpegImageFromCinfo(), image_load_image_file(), image_load_movie_file(), image_open_exec(), image_replace_exec(), init_structDNA(), layer_menu(), list_item_row(), make_memhead_header(), make_renderinfo_string(), make_structDNA(), make_unique_prop_names_cb(), menudata_add_item(), minimize_stretch_iteration(), Mirror(), movieclip_open_anim_file(), multiple_scattering_diffusion(), nla_draw_strip_text(), ntreeCompositExecTree(), open_exec(), outliner_add_object_contents(), outliner_draw_keymapbuts(), outliner_group_operation_exec(), outliner_object_operation_exec(), pass_menu(), path_read_text(), print_part_stats(), GHOST_EventPrinter::processEvent(), PushPull(), radial_control_get_path(), RE_is_rendering_allowed(), reload_sequence_new_file(), render_composit_stats(), render_result_exr_file_begin(), render_result_exr_file_read(), reopen_text(), report_textview_init__internal(), reports_to_text_exec(), Resize(), Rotation(), seq_free_animdata(), seq_offset_animdata(), SeqSlide(), set_addons(), set_case(), Shear(), ShrinkFatten(), slot_menu(), sound_new_file(), stitch_update_header(), STR_String::STR_String(), string_printf(), text_draw_wrapped(), text_font_draw_character(), text_font_draw_character_utf8(), text_insert_exec(), text_insert_invoke(), text_open_exec(), text_save_as_exec(), text_save_as_invoke(), Tilt(), TimeScale(), TimeSlide(), TimeTranslate(), toggle_case_exec(), ToSphere(), touch_seq_files(), Trackball(), Translation(), txt_format_line(), u_alloc_getenv(), ui_apply_autokey_undo(), ui_but_copy_paste(), ui_item_array(), ui_popup_menu_create(), ui_textedit_autocomplete(), ui_textedit_copypaste(), ui_textedit_delete(), ui_textedit_delete_selection(), ui_textedit_move(), ui_textedit_type_buf(), ui_tooltip_create(), UI_view2d_text_cache_draw(), uiLayoutIntrospect(), uiPupMenuReports(), uiTemplateImage(), undoFont_to_editFont(), uput_getenv(), v3d_editvertex_buts(), view3d_cached_text_draw_end(), view3d_modeselect_pup(), vol_precache_objectinstance_threads(), Warp(), widget_draw_text(), wm_autosave_delete(), WM_key_event_operator_string(), WM_keymap_item_to_string(), and wm_window_title().