Blender: clip_utils.c File Reference
clip_utils.c File Reference
#include "DNA_object_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "BLI_listbase.h"
#include "BKE_context.h"
#include "BKE_movieclip.h"
#include "BKE_tracking.h"
#include "BKE_depsgraph.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_screen.h"
#include "ED_clip.h"
#include "UI_interface.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "UI_view2d.h"
#include "clip_intern.h"
Functions
void clip_graph_tracking_values_iterate_track (SpaceClip *sc, MovieTrackingTrack *track, void *userdata, void(*func)(void *userdata, MovieTrackingTrack *track, MovieTrackingMarker *marker, int coord, float val), void(*segment_start)(void *userdata, MovieTrackingTrack *track, int coord), void(*segment_end)(void *userdata))
void clip_graph_tracking_values_iterate (SpaceClip *sc, void *userdata, void(*func)(void *userdata, MovieTrackingTrack *track, MovieTrackingMarker *marker, int coord, float val), void(*segment_start)(void *userdata, MovieTrackingTrack *track, int coord), void(*segment_end)(void *userdata))
void clip_graph_tracking_iterate (SpaceClip *sc, void *userdata, void(*func)(void *userdata, MovieTrackingMarker *marker))
void clip_delete_track (bContext *C, MovieClip *clip, ListBase *tracksbase, MovieTrackingTrack *track)
void clip_delete_marker (bContext *C, MovieClip *clip, ListBase *tracksbase, MovieTrackingTrack *track, MovieTrackingMarker *marker)
void clip_view_center_to_point (SpaceClip *sc, float x, float y)
Detailed Description
Definition in file clip_utils.c.
Function Documentation
void clip_delete_marker (bContext * C, MovieClip * clip, ListBase * tracksbase, MovieTrackingTrack * track, MovieTrackingMarker * marker)
Definition at line 200 of file clip_utils.c.
References BKE_tracking_delete_marker(), clip_delete_track(), MovieTrackingMarker::framenr, MovieTrackingTrack::markersnr, NA_EDITED, NC_MOVIECLIP, and WM_event_add_notifier().
Referenced by delete_knot_exec(), and delete_marker_exec().
void clip_delete_track (bContext * C, MovieClip * clip, ListBase * tracksbase, MovieTrackingTrack * track)
Definition at line 163 of file clip_utils.c.
References MovieTracking::act_track, BKE_tracking_active_track(), BKE_tracking_free_track(), BLI_freelinkN(), DAG_id_tag_update(), FALSE, MovieTrackingTrack::flag, MovieClip::id, NA_EDITED, NC_MOVIECLIP, NC_SPACE, ND_DISPLAY, ND_SPACE_VIEW3D, NULL, MovieTrackingStabilization::ok, MovieTrackingStabilization::rot_track, MovieTracking::stabilization, TRACK_HAS_BUNDLE, MovieClip::tracking, TRUE, and WM_event_add_notifier().
Referenced by clip_delete_marker(), delete_curve_exec(), and delete_track_exec().
void clip_graph_tracking_iterate (SpaceClip * sc, void * userdata, void(*)(void *userdata, MovieTrackingMarker *marker) func)
Definition at line 135 of file clip_utils.c.
References BKE_tracking_get_tracks(), ED_space_clip(), ListBase::first, MovieTrackingMarker::flag, i, MARKER_DISABLED, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, MovieTrackingTrack::next, TRACK_VIEW_SELECTED, and MovieClip::tracking.
void clip_graph_tracking_values_iterate (SpaceClip * sc, void * userdata, void(*)(void *userdata, MovieTrackingTrack *track, MovieTrackingMarker *marker, int coord, float val) func, void(*)(void *userdata, MovieTrackingTrack *track, int coord) segment_start, void(*)(void *userdata) segment_end)
Definition at line 115 of file clip_utils.c.
References BKE_tracking_get_tracks(), clip_graph_tracking_values_iterate_track(), ED_space_clip(), ListBase::first, MovieTrackingTrack::next, TRACK_VIEW_SELECTED, and MovieClip::tracking.
void clip_graph_tracking_values_iterate_track (SpaceClip * sc, MovieTrackingTrack * track, void * userdata, void(*)(void *userdata, MovieTrackingTrack *track, MovieTrackingMarker *marker, int coord, float val) func, void(*)(void *userdata, MovieTrackingTrack *track, int coord) segment_start, void(*)(void *userdata) segment_end)
Definition at line 60 of file clip_utils.c.
References BKE_movieclip_get_size(), ED_space_clip(), FALSE, MovieTrackingMarker::flag, MovieTrackingMarker::framenr, i, MARKER_DISABLED, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, MovieTrackingMarker::pos, TRUE, and SpaceClip::user.
void clip_view_center_to_point (SpaceClip * sc, float x, float y)
Definition at line 212 of file clip_utils.c.
References ED_space_clip_aspect(), ED_space_clip_size(), SpaceClip::xof, and SpaceClip::yof.
Referenced by ED_clip_view_selection(), and mouse_select_curve().