Blender: MOD_mask.c File Reference
MOD_mask.c File Reference
modifiers
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_listbase.h"
#include "BLI_string.h"
#include "BLI_ghash.h"
#include "DNA_armature_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_modifier_types.h"
#include "DNA_object_types.h"
#include "BKE_action.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_mesh.h"
#include "BKE_modifier.h"
#include "BKE_deform.h"
#include "depsgraph_private.h"
#include "MOD_util.h"
Functions
static void copyData (ModifierData *md, ModifierData *target)
static CustomDataMask requiredDataMask (Object *UNUSED(ob), ModifierData *UNUSED(md))
static void foreachObjectLink (ModifierData *md, Object *ob, void(*walk)(void *userData, Object *ob, Object **obpoin), void *userData)
static void updateDepgraph (ModifierData *md, DagForest *forest, struct Scene *UNUSED(scene), Object *UNUSED(ob), DagNode *obNode)
static DerivedMesh * applyModifier (ModifierData *md, Object *ob, DerivedMesh *derivedData, int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
Variables
ModifierTypeInfo modifierType_Mask
Detailed Description
Definition in file MOD_mask.c.
Function Documentation
static DerivedMesh* applyModifier (ModifierData * md, Object * ob, DerivedMesh * derivedData, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 95 of file MOD_mask.c.
References BLI_countlist(), BLI_ghash_free(), BLI_ghash_haskey(), BLI_ghash_insert(), BLI_ghash_lookup(), BLI_ghash_new(), BLI_ghashIterator_free(), BLI_ghashIterator_getKey(), BLI_ghashIterator_getValue(), BLI_ghashIterator_isDone(), BLI_ghashIterator_new(), BLI_ghashIterator_step(), BLI_ghashutil_intcmp(), BLI_ghashutil_inthash(), BLI_ghashutil_strcmp(), BLI_ghashutil_strhash(), bPoseChannel::bone, BONE_SELECTED, CD_MDEFORMVERT, CDDM_calc_normals(), CDDM_from_template(), CDDM_get_edges(), CDDM_get_loops(), CDDM_get_polys(), CDDM_get_verts(), MDeformWeight::def_nr, Object::defbase, defgroup_name_index(), defvert_find_weight(), DM_copy_edge_data(), DM_copy_loop_data(), DM_copy_poly_data(), DM_copy_vert_data(), MLoop::e, ELEM, ELEM3, FALSE, ListBase::first, MaskModifierData::flag, Bone::flag, GET_INT_FROM_POINTER, get_pose_channel(), DerivedMesh::getEdge, DerivedMesh::getLoopArray, DerivedMesh::getNumEdges, DerivedMesh::getNumPolys, DerivedMesh::getNumVerts, DerivedMesh::getPolyArray, DerivedMesh::getVert, DerivedMesh::getVertDataArray, i, MPoly::loopstart, MEM_callocN(), MEM_freeN(), MEM_mallocN(), MOD_MASK_INV, MOD_MASK_MODE_ARM, MOD_MASK_MODE_VGROUP, MaskModifierData::mode, bDeformGroup::name, bDeformGroup::next, NULL, MaskModifierData::ob_arm, Object::pose, SET_INT_IN_POINTER, MPoly::totloop, TRUE, MLoop::v, MEdge::v1, MEdge::v2, MaskModifierData::vgroup, and MDeformWeight::weight.
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 58 of file MOD_mask.c.
References BLI_strncpy(), MaskModifierData::flag, and MaskModifierData::vgroup.
static void foreachObjectLink (ModifierData * md, Object * ob, void(*)(void *userData, Object *ob, Object **obpoin) walk, void * userData) [static]
Definition at line 72 of file MOD_mask.c.
References MaskModifierData::ob_arm.
static CustomDataMask requiredDataMask (Object * UNUSEDob, ModifierData * UNUSEDmd) [static]
Definition at line 67 of file MOD_mask.c.
References CD_MASK_MDEFORMVERT.
static void updateDepgraph (ModifierData * md, DagForest * forest, struct Scene * UNUSEDscene, Object * UNUSEDob, DagNode * obNode) [static]
Definition at line 81 of file MOD_mask.c.
References dag_add_relation(), dag_get_node(), DAG_RL_DATA_DATA, DAG_RL_OB_DATA, and MaskModifierData::ob_arm.
Variable Documentation
ModifierTypeInfo modifierType_Mask
Initial value:
 {
                  "Mask",
            "MaskModifierData",
            sizeof(MaskModifierData),
                  eModifierTypeType_Nonconstructive,
                 eModifierTypeFlag_AcceptsMesh|eModifierTypeFlag_SupportsMapping|eModifierTypeFlag_SupportsEditmode,
              copyData,
           NULL,
        NULL,
         NULL,
      NULL,
         applyModifier,
       NULL,
              NULL,
      requiredDataMask,
              NULL,
            NULL,
        updateDepgraph,
         NULL,
        NULL,
     foreachObjectLink,
         NULL,
        NULL,
}
Definition at line 410 of file MOD_mask.c.