Blender: ED_curve.h File Reference
ED_curve.h File Reference
Editors
Functions
void ED_operatortypes_curve (void)
void ED_operatormacros_curve (void)
void ED_keymap_curve (struct wmKeyConfig *keyconf)
void CU_deselect_all (struct Object *obedit)
void CU_select_all (struct Object *obedit)
void CU_select_swap (struct Object *obedit)
void undo_push_curve (struct bContext *C, const char *name)
ListBase * object_editcurve_get (struct Object *ob)
void load_editNurb (struct Object *obedit)
void make_editNurb (struct Object *obedit)
void free_editNurb (struct Object *obedit)
void free_curve_editNurb (struct Curve *cu)
int mouse_nurb (struct bContext *C, const int mval[2], int extend)
struct Nurb * add_nurbs_primitive (struct bContext *C, float mat[4][4], int type, int newob)
int isNurbsel (struct Nurb *nu)
void ED_nurb_set_spline_type (struct Nurb *nu, int type)
int join_curve_exec (struct bContext *C, struct wmOperator *op)
void undo_push_font (struct bContext *C, const char *name)
void make_editText (struct Object *obedit)
void load_editText (struct Object *obedit)
void free_editText (struct Object *obedit)
void ED_text_to_object (struct bContext *C, struct Text *text, int split_lines)
int CU_select_nth (struct Object *obedit, int nth)
void ED_curve_beztcpy (struct EditNurb *editnurb, struct BezTriple *dst, struct BezTriple *src, int count)
void ED_curve_bpcpy (struct EditNurb *editnurb, struct BPoint *dst, struct BPoint *src, int count)
int ED_curve_updateAnimPaths (struct Curve *cu)
int ED_curve_actSelection (struct Curve *cu, float center[3])
void printknots (struct Object *obedit)
Detailed Description
Definition in file ED_curve.h.
Function Documentation
struct Nurb* add_nurbs_primitive (struct bContext * C, float mat[4][4], int type, int newob) [read]
Definition at line 6175 of file editcurve.c.
References CTX_data_edit_object(), CTX_wm_view3d(), Object::data, ED_view3d_context_rv3d(), NurbSort::nu, NULL, object_editcurve_get(), and NurbSort::vec.
Referenced by curvesurf_prim_add(), and effector_add_type().
void CU_deselect_all (struct Object * obedit)
Definition at line 1291 of file editcurve.c.
References DESELECT, FIRST, object_editcurve_get(), select_adjacent_cp(), and selectend_nurb().
Referenced by de_select_all_exec(), do_lasso_select_curve(), do_nurbs_box_select(), and select_random_exec().
void CU_select_all (struct Object * obedit)
Definition at line 1301 of file editcurve.c.
References FIRST, object_editcurve_get(), SELECT, select_adjacent_cp(), and selectend_nurb().
Referenced by de_select_all_exec().
int CU_select_nth (struct Object * obedit, int nth)
Definition at line 5537 of file editcurve.c.
References Nurb::bezt, Object::data, get_lastsel_nurb(), Curve::lastsel, NurbSort::nu, select_nth_bezt(), and select_nth_bp().
Referenced by select_nth_exec().
void CU_select_swap (struct Object * obedit)
Definition at line 1311 of file editcurve.c.
References Nurb::bezt, Nurb::bp, CU_BEZIER, CU_HIDE_HANDLES, Object::data, Curve::drawflag, BezTriple::f1, BezTriple::f2, BezTriple::f3, ListBase::first, BezTriple::hide, Curve::lastsel, Nurb::next, NULL, object_editcurve_get(), Nurb::pntsu, Nurb::pntsv, SELECT, swap_selection_bpoint(), and Nurb::type.
Referenced by de_select_all_exec().
int ED_curve_actSelection (struct Curve * cu, float center[3])
Definition at line 7077 of file editcurve.c.
References Nurb::bezt, copy_v3_v3(), get_lastsel_nurb(), Curve::lastsel, NurbSort::nu, BezTriple::vec, and BPoint::vec.
Referenced by calc_manipulator_stats(), and calculateCenter().
void ED_curve_beztcpy (struct EditNurb * editnurb, struct BezTriple * dst, struct BezTriple * src, int count)
Definition at line 7065 of file editcurve.c.
References keyIndex_updateBezt().
Referenced by delete_exec(), and make_segment_exec().
void ED_curve_bpcpy (struct EditNurb * editnurb, struct BPoint * dst, struct BPoint * src, int count)
Definition at line 7071 of file editcurve.c.
References keyIndex_updateBP().
Referenced by delete_exec(), extrudeflagNurb(), and make_segment_exec().
int ED_curve_updateAnimPaths (struct Curve * cu)
Definition at line 1179 of file editcurve.c.
References AnimData::action, BKE_animdata_from_id(), curve_is_animated(), curve_rename_fcurves(), bAction::curves, AnimData::drivers, and Curve::id.
Referenced by delete_exec(), deleteflagNurb(), extrude_exec(), load_editNurb(), make_segment_exec(), set_spline_type_exec(), spin_exec(), subdivide_exec(), switch_direction_exec(), and undoCurve_to_editCurve().
void ED_keymap_curve (struct wmKeyConfig * keyconf)
Definition at line 158 of file curve_ops.c.
References AKEY, BACKSPACEKEY, BKEY, CKEY, CU_CHINFO_BOLD, CU_CHINFO_ITALIC, CU_CHINFO_SMALLCAPS, CU_CHINFO_UNDERLINE, DEL_ALL, DEL_NEXT_SEL, DEL_PREV_SEL, DELKEY, DKEY, DOWNARROWKEY, ED_object_generic_keymap(), ED_operator_editfont(), ED_operator_editsurfcurve(), EKEY, ENDKEY, FALSE, FKEY, HKEY, HOMEKEY, IKEY, KM_ALT, KM_ANY, KM_CLICK, KM_CTRL, KM_OSKEY, KM_PRESS, KM_SHIFT, KM_TEXTINPUT, LEFTARROWKEY, LEFTMOUSE, LINE_BEGIN, LINE_END, LKEY, NEXT_CHAR, NEXT_LINE, NEXT_PAGE, NEXT_WORD, PADMINUS, PADPLUSKEY, PAGEDOWNKEY, PAGEUPKEY, PKEY, wmKeyMap::poll, PREV_CHAR, PREV_LINE, PREV_PAGE, PREV_WORD, wmKeyMapItem::ptr, RETKEY, RIGHTARROWKEY, RKEY, RNA_boolean_set(), RNA_enum_set(), RNA_int_set(), SEL_INVERT, SEL_TOGGLE, SKEY, TFM_CURVE_SHRINKFATTEN, TKEY, TRUE, UKEY, UPARROWKEY, VKEY, WKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), and XKEY.
Referenced by ED_spacetypes_keymap().
void ED_nurb_set_spline_type (struct Nurb * nu, int type)
Definition at line 3488 of file editcurve.c.
References convertspline().
void ED_operatormacros_curve (void)
Definition at line 138 of file curve_ops.c.
References wmOperatorType::description, FALSE, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorTypeMacro::ptr, RNA_boolean_set(), RNA_enum_set(), WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().
void ED_operatortypes_curve (void)
Definition at line 56 of file curve_ops.c.
References CURVE_OT_cyclic_toggle(), CURVE_OT_de_select_first(), CURVE_OT_de_select_last(), CURVE_OT_delete(), CURVE_OT_duplicate(), CURVE_OT_extrude(), CURVE_OT_handle_type_set(), CURVE_OT_hide(), CURVE_OT_make_segment(), CURVE_OT_primitive_bezier_circle_add(), CURVE_OT_primitive_bezier_curve_add(), CURVE_OT_primitive_nurbs_circle_add(), CURVE_OT_primitive_nurbs_curve_add(), CURVE_OT_primitive_nurbs_path_add(), CURVE_OT_radius_set(), CURVE_OT_reveal(), CURVE_OT_select_all(), CURVE_OT_select_less(), CURVE_OT_select_linked(), CURVE_OT_select_linked_pick(), CURVE_OT_select_more(), CURVE_OT_select_next(), CURVE_OT_select_nth(), CURVE_OT_select_previous(), CURVE_OT_select_random(), CURVE_OT_select_row(), CURVE_OT_separate(), CURVE_OT_shade_flat(), CURVE_OT_shade_smooth(), CURVE_OT_smooth(), CURVE_OT_smooth_radius(), CURVE_OT_spin(), CURVE_OT_spline_type_set(), CURVE_OT_spline_weight_set(), CURVE_OT_subdivide(), CURVE_OT_switch_direction(), CURVE_OT_tilt_clear(), CURVE_OT_vertex_add(), FONT_OT_case_set(), FONT_OT_case_toggle(), FONT_OT_change_character(), FONT_OT_change_spacing(), FONT_OT_delete(), FONT_OT_file_paste(), FONT_OT_insert_lorem(), FONT_OT_line_break(), FONT_OT_move(), FONT_OT_move_select(), FONT_OT_open(), FONT_OT_style_set(), FONT_OT_style_toggle(), FONT_OT_text_copy(), FONT_OT_text_cut(), FONT_OT_text_insert(), FONT_OT_text_paste(), FONT_OT_textbox_add(), FONT_OT_textbox_remove(), FONT_OT_unlink(), SURFACE_OT_primitive_nurbs_surface_circle_add(), SURFACE_OT_primitive_nurbs_surface_curve_add(), SURFACE_OT_primitive_nurbs_surface_cylinder_add(), SURFACE_OT_primitive_nurbs_surface_sphere_add(), SURFACE_OT_primitive_nurbs_surface_surface_add(), SURFACE_OT_primitive_nurbs_surface_torus_add(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
void ED_text_to_object (struct bContext * C, struct Text * text, int split_lines)
Definition at line 483 of file editfont.c.
References BLI_countlist(), CTX_wm_region_view3d(), ListBase::first, TextLine::line, Text::lines, mul_mat3_m4_v3(), TextLine::next, txt_add_object(), and RegionView3D::viewinv.
Referenced by text_to_3d_object_exec().
void free_curve_editNurb (struct Curve * cu)
Definition at line 124 of file curve.c.
References Curve::editnurb, free_curve_editNurb_keyIndex(), freeNurblist(), MEM_freeN(), NULL, and EditNurb::nurbs.
void free_editNurb (struct Object * obedit)
Definition at line 1284 of file editcurve.c.
References Object::data, and free_curve_editNurb().
Referenced by ED_object_exit_editmode(), and separate_exec().
void free_editText (struct Object * obedit)
Definition at line 1492 of file editfont.c.
References BKE_free_editfont(), and Object::data.
Referenced by ED_object_exit_editmode().
int isNurbsel (struct Nurb * nu)
Definition at line 215 of file editcurve.c.
References Nurb::bezt, Nurb::bp, CU_BEZIER, BezTriple::f1, BPoint::f1, BezTriple::f2, BezTriple::f3, Nurb::pntsu, Nurb::pntsv, SELECT, and Nurb::type.
Referenced by adduplicateflagNurb(), make_editNurb(), make_segment_exec(), make_selection_list_nurb(), material_slot_assign_exec(), printknots(), separate_exec(), set_spline_type_exec(), shade_smooth_exec(), spin_nurb(), and switch_direction_exec().
int join_curve_exec (struct bContext * C, struct wmOperator * op)
void load_editNurb (struct Object * obedit)
Definition at line 1196 of file editcurve.c.
References BLI_addtail(), calc_shapeKeys(), clamp_nurb_order_u(), CU_NURBS, Object::data, duplicateNurb(), ED_curve_updateAnimPaths(), ELEM, ListBase::first, freeNurblist(), Nurb::next, NULL, Curve::nurb, OB_CURVE, OB_SURF, object_editcurve_get(), set_actNurb(), Nurb::type, and Object::type.
Referenced by ED_object_exit_editmode(), and separate_exec().
void load_editText (struct Object * obedit)
Definition at line 1465 of file editfont.c.
References Object::data, Curve::editfont, Curve::len, MEM_callocN(), MEM_freeN(), NULL, EditFont::oldstr, EditFont::oldstrinfo, Curve::selboxes, Curve::str, Curve::strinfo, strlen(), EditFont::textbufinfo, and update_string().
Referenced by ED_object_exit_editmode().
void make_editNurb (struct Object * obedit)
Definition at line 1230 of file editcurve.c.
References BLI_addtail(), Object::data, duplicateNurb(), Curve::editnurb, ELEM, ListBase::first, free_curve_editNurb_keyIndex(), freeNurblist(), init_editNurb_keyIndex(), isNurbsel(), key_to_curve(), Curve::lastsel, MEM_callocN(), Nurb::next, NULL, Curve::nurb, OB_CURVE, ob_get_keyblock(), OB_SURF, set_actNurb(), Object::shapenr, test2DNurb(), Object::type, and undo_editmode_clear().
Referenced by ED_object_enter_editmode(), and separate_exec().
void make_editText (struct Object * obedit)
Definition at line 1429 of file editfont.c.
References BLI_strncpy_wchar_from_utf8(), EditFont::copybuf, EditFont::copybufinfo, Curve::curinfo, Object::data, Curve::editfont, Curve::len, MAXTEXT, MEM_callocN(), NULL, EditFont::oldstr, EditFont::oldstrinfo, Curve::pos, Curve::str, Curve::strinfo, EditFont::textbuf, EditFont::textbufinfo, and update_string().
Referenced by ED_object_enter_editmode().
int mouse_nurb (struct bContext * C, const int mval[2], int extend)
Definition at line 4132 of file editcurve.c.
References CTX_data_edit_object(), Object::data, DESELECT, BezTriple::f1, BPoint::f1, BezTriple::f2, BezTriple::f3, findnearestNurbvert(), get_actNurb(), HIDDEN, Curve::lastsel, NC_GEOM, ND_SELECT, NurbSort::nu, NULL, object_editcurve_get(), SELECT, select_beztriple(), select_bpoint(), set_actNurb(), setflagsNurb(), view3d_operator_needs_opengl(), view3d_set_viewcontext(), and WM_event_add_notifier().
Referenced by view3d_select_invoke().
ListBase* object_editcurve_get (struct Object * ob)
Definition at line 118 of file editcurve.c.
References Object::data, Curve::editnurb, ELEM, NULL, EditNurb::nurbs, OB_CURVE, OB_SURF, and Object::type.
Referenced by add_nurbs_primitive(), adduplicateflagNurb(), clear_tilt_exec(), CU_deselect_all(), CU_select_all(), CU_select_swap(), curvesurf_prim_add(), de_select_all_exec(), deleteflagNurb(), effector_add_type(), hide_exec(), load_editNurb(), make_segment_exec(), merge_nurb(), mouse_nurb(), printknots(), return_editcurve_indexar(), reveal_exec(), select_editcurve_hook(), select_less_exec(), select_more_exec(), select_next_exec(), select_previous_exec(), select_random_exec(), select_row_exec(), selectend_nurb(), set_goal_weight_exec(), set_handle_type_exec(), set_radius_exec(), set_spline_type_exec(), shade_smooth_exec(), smooth_exec(), smooth_radius_exec(), spin_nurb(), toggle_cyclic_exec(), toggle_cyclic_invoke(), and vertex_parent_set_exec().
void printknots (struct Object * obedit)
Definition at line 267 of file editcurve.c.
References CU_NURBS, ListBase::first, isNurbsel(), Nurb::knotsu, KNOTSU, Nurb::knotsv, KNOTSV, Nurb::next, object_editcurve_get(), and Nurb::type.
void undo_push_curve (struct bContext * C, const char * name)
Definition at line 7060 of file editcurve.c.
References editCurve_to_undoCurve(), free_undoCurve(), get_data(), NULL, undo_editmode_push(), and undoCurve_to_editCurve().
Referenced by ED_undo_push().
void undo_push_font (struct bContext * C, const char * name)
Definition at line 1793 of file editfont.c.
References editFont_to_undoFont(), free_undoFont(), get_undoFont(), NULL, undo_editmode_push(), and undoFont_to_editFont().
Referenced by ED_undo_push().