Blender: keyframes_edit.c File Reference
keyframes_edit.c File Reference
animation
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "DNA_anim_types.h"
#include "DNA_armature_types.h"
#include "DNA_camera_types.h"
#include "DNA_key_types.h"
#include "DNA_lamp_types.h"
#include "DNA_lattice_types.h"
#include "DNA_mesh_types.h"
#include "DNA_material_types.h"
#include "DNA_object_types.h"
#include "DNA_meta_types.h"
#include "DNA_node_types.h"
#include "DNA_particle_types.h"
#include "DNA_scene_types.h"
#include "DNA_space_types.h"
#include "DNA_world_types.h"
#include "BKE_fcurve.h"
#include "BKE_key.h"
#include "BKE_material.h"
#include "ED_anim_api.h"
#include "ED_keyframes_edit.h"
#include "ED_markers.h"
Defines
#define KEYFRAME_OK_CHECKS(check)
#define KEY_CHECK_OK(_index) IS_EQF(bezt->vec[_index][0], ked->f1)
#define KEY_CHECK_OK(_index) ((bezt->vec[_index][0] > ked->f1) && (bezt->vec[_index][0] < ked->f2))
#define KEY_CHECK_OK(_index) IS_EQF(bezt->vec[_index][1], ked->f1)
#define KEY_CHECK_OK(_index) ((bezt->vec[_index][1] > ked->f1) && (bezt->vec[_index][1] < ked->f2))
#define KEY_CHECK_OK(_index) BLI_in_rctf(ked->data, bezt->vec[_index][0], bezt->vec[_index][1])
#define ENSURE_HANDLES_MATCH(bezt)
Functions
short ANIM_fcurve_keyframes_loop (KeyframeEditData *ked, FCurve *fcu, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
static short agrp_keyframes_loop (KeyframeEditData *ked, bActionGroup *agrp, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
static short act_keyframes_loop (KeyframeEditData *ked, bAction *act, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
static short ob_keyframes_loop (KeyframeEditData *ked, bDopeSheet *ads, Object *ob, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
static short scene_keyframes_loop (KeyframeEditData *ked, bDopeSheet *ads, Scene *sce, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
static short summary_keyframes_loop (KeyframeEditData *ked, bAnimContext *ac, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
short ANIM_animchannel_keyframes_loop (KeyframeEditData *ked, bDopeSheet *ads, bAnimListElem *ale, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
short ANIM_animchanneldata_keyframes_loop (KeyframeEditData *ked, bDopeSheet *ads, void *data, int keytype, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
void ANIM_editkeyframes_refresh (bAnimContext *ac)
static short ok_bezier_frame (KeyframeEditData *ked, BezTriple *bezt)
static short ok_bezier_framerange (KeyframeEditData *ked, BezTriple *bezt)
static short ok_bezier_selected (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short ok_bezier_value (KeyframeEditData *ked, BezTriple *bezt)
static short ok_bezier_valuerange (KeyframeEditData *ked, BezTriple *bezt)
static short ok_bezier_region (KeyframeEditData *ked, BezTriple *bezt)
KeyframeEditFunc ANIM_editkeyframes_ok (short mode)
short bezt_calc_average (KeyframeEditData *ked, BezTriple *bezt)
short bezt_to_cfraelem (KeyframeEditData *ked, BezTriple *bezt)
void bezt_remap_times (KeyframeEditData *ked, BezTriple *bezt)
static short snap_bezier_nearest (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short snap_bezier_nearestsec (KeyframeEditData *ked, BezTriple *bezt)
static short snap_bezier_cframe (KeyframeEditData *ked, BezTriple *bezt)
static short snap_bezier_nearmarker (KeyframeEditData *ked, BezTriple *bezt)
static short snap_bezier_horizontal (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short snap_bezier_value (KeyframeEditData *ked, BezTriple *bezt)
KeyframeEditFunc ANIM_editkeyframes_snap (short type)
static short mirror_bezier_cframe (KeyframeEditData *ked, BezTriple *bezt)
static short mirror_bezier_yaxis (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short mirror_bezier_xaxis (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short mirror_bezier_marker (KeyframeEditData *ked, BezTriple *bezt)
static short mirror_bezier_value (KeyframeEditData *ked, BezTriple *bezt)
KeyframeEditFunc ANIM_editkeyframes_mirror (short type)
static short set_bezier_auto (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short set_bezier_auto_clamped (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short set_bezier_vector (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short bezier_isfree (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short set_bezier_align (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short set_bezier_free (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
KeyframeEditFunc ANIM_editkeyframes_handles (short code)
static short set_bezt_constant (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short set_bezt_linear (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short set_bezt_bezier (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
KeyframeEditFunc ANIM_editkeyframes_ipo (short code)
static short set_keytype_keyframe (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short set_keytype_breakdown (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short set_keytype_extreme (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
static short set_keytype_jitter (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
KeyframeEditFunc ANIM_editkeyframes_keytype (short code)
static short select_bezier_add (KeyframeEditData *ked, BezTriple *bezt)
static short select_bezier_subtract (KeyframeEditData *ked, BezTriple *bezt)
static short select_bezier_invert (KeyframeEditData *UNUSED(ked), BezTriple *bezt)
KeyframeEditFunc ANIM_editkeyframes_select (short selectmode)
static short selmap_build_bezier_more (KeyframeEditData *ked, BezTriple *bezt)
static short selmap_build_bezier_less (KeyframeEditData *ked, BezTriple *bezt)
KeyframeEditFunc ANIM_editkeyframes_buildselmap (short mode)
short bezt_selmap_flush (KeyframeEditData *ked, BezTriple *bezt)
Detailed Description
Definition in file keyframes_edit.c.
Define Documentation
#define ENSURE_HANDLES_MATCH (bezt)
Value:
if (bezt->h1 != bezt->h2) {                                               \
        if (ELEM3(bezt->h1, HD_ALIGN, HD_AUTO, HD_AUTO_ANIM))                 \
            bezt->h1= HD_FREE;                                                \
        if (ELEM3(bezt->h2, HD_ALIGN, HD_AUTO, HD_AUTO_ANIM))                 \
        bezt->h2= HD_FREE;                                                    \
    }
Definition at line 763 of file keyframes_edit.c.
Referenced by set_bezier_auto(), and set_bezier_auto_clamped().
#define KEY_CHECK_OK (_index) ((bezt->vec[_index][0] > ked->f1) && (bezt->vec[_index][0] < ked->f2))
#define KEY_CHECK_OK (_index) BLI_in_rctf(ked->data, bezt->vec[_index][0], bezt->vec[_index][1])
#define KEY_CHECK_OK (_index) ((bezt->vec[_index][1] > ked->f1) && (bezt->vec[_index][1] < ked->f2))
#define KEY_CHECK_OK (_index) IS_EQF(bezt->vec[_index][1], ked->f1)
#define KEY_CHECK_OK (_index) IS_EQF(bezt->vec[_index][0], ked->f1)
Referenced by ok_bezier_frame(), ok_bezier_framerange(), ok_bezier_region(), ok_bezier_value(), and ok_bezier_valuerange().
#define KEYFRAME_OK_CHECKS (check)
Value:
{ \
        if (check(1)) \
            ok |= KEYFRAME_OK_KEY; \
         \
        if (ked && (ked->iterflags & KEYFRAME_ITER_INCL_HANDLES)) { \
            if (check(0)) \
                ok |= KEYFRAME_OK_H1; \
            if (check(2)) \
                ok |= KEYFRAME_OK_H2; \
        } \
    }
Definition at line 421 of file keyframes_edit.c.
Referenced by ok_bezier_frame(), ok_bezier_framerange(), ok_bezier_region(), ok_bezier_value(), and ok_bezier_valuerange().
Function Documentation
static short act_keyframes_loop (KeyframeEditData * ked, bAction * act, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb) [static]
Definition at line 182 of file keyframes_edit.c.
References ANIM_fcurve_keyframes_loop(), bAction::curves, ListBase::first, FCurve::next, and NULL.
Referenced by ANIM_animchannel_keyframes_loop(), and ANIM_animchanneldata_keyframes_loop().
static short agrp_keyframes_loop (KeyframeEditData * ked, bActionGroup * agrp, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb) [static]
Definition at line 164 of file keyframes_edit.c.
References ANIM_fcurve_keyframes_loop(), bActionGroup::channels, ListBase::first, FCurve::grp, FCurve::next, and NULL.
Referenced by ANIM_animchannel_keyframes_loop(), and ANIM_animchanneldata_keyframes_loop().
short ANIM_animchannel_keyframes_loop (KeyframeEditData * ked, bDopeSheet * ads, bAnimListElem * ale, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
Definition at line 317 of file keyframes_edit.c.
References act_keyframes_loop(), agrp_keyframes_loop(), ALE_ACT, ALE_ALL, ALE_FCURVE, ALE_GROUP, ALE_OB, ALE_SCE, ANIM_fcurve_keyframes_loop(), bAnimListElem::data, bAnimListElem::datatype, bAnimListElem::key_data, NULL, ob_keyframes_loop(), scene_keyframes_loop(), and summary_keyframes_loop().
Referenced by actkeys_mselect_single(), and borderselect_action().
short ANIM_animchanneldata_keyframes_loop (KeyframeEditData * ked, bDopeSheet * ads, void * data, int keytype, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
Definition at line 349 of file keyframes_edit.c.
References act_keyframes_loop(), agrp_keyframes_loop(), ALE_ACT, ALE_ALL, ALE_FCURVE, ALE_GROUP, ALE_OB, ALE_SCE, ANIM_fcurve_keyframes_loop(), NULL, ob_keyframes_loop(), scene_keyframes_loop(), and summary_keyframes_loop().
Referenced by nlaedit_apply_scale_exec(), and poselib_apply_pose().
KeyframeEditFunc ANIM_editkeyframes_buildselmap (short mode)
Definition at line 1095 of file keyframes_edit.c.
References selmap_build_bezier_less(), selmap_build_bezier_more(), SELMAP_LESS, and SELMAP_MORE.
Referenced by select_moreless_action_keys(), and select_moreless_graph_keys().
KeyframeEditFunc ANIM_editkeyframes_handles (short code)
Definition at line 833 of file keyframes_edit.c.
References bezier_isfree(), HD_ALIGN, HD_AUTO, HD_AUTO_ANIM, HD_FREE, HD_VECT, set_bezier_align(), set_bezier_auto(), set_bezier_auto_clamped(), set_bezier_free(), and set_bezier_vector().
Referenced by sethandles_action_keys(), and sethandles_graph_keys().
KeyframeEditFunc ANIM_editkeyframes_ipo (short code)
Definition at line 878 of file keyframes_edit.c.
References BEZT_IPO_CONST, BEZT_IPO_LIN, set_bezt_bezier(), set_bezt_constant(), and set_bezt_linear().
Referenced by setipo_action_keys(), and setipo_graph_keys().
KeyframeEditFunc ANIM_editkeyframes_keytype (short code)
Definition at line 921 of file keyframes_edit.c.
References BEZT_KEYTYPE_BREAKDOWN, BEZT_KEYTYPE_EXTREME, BEZT_KEYTYPE_JITTER, BEZT_KEYTYPE_KEYFRAME, set_keytype_breakdown(), set_keytype_extreme(), set_keytype_jitter(), and set_keytype_keyframe().
Referenced by setkeytype_action_keys().
KeyframeEditFunc ANIM_editkeyframes_mirror (short type)
Definition at line 739 of file keyframes_edit.c.
References mirror_bezier_cframe(), mirror_bezier_marker(), mirror_bezier_value(), mirror_bezier_xaxis(), mirror_bezier_yaxis(), MIRROR_KEYS_CURFRAME, MIRROR_KEYS_MARKER, MIRROR_KEYS_VALUE, MIRROR_KEYS_XAXIS, and MIRROR_KEYS_YAXIS.
Referenced by mirror_action_keys(), and mirror_graph_keys().
KeyframeEditFunc ANIM_editkeyframes_ok (short mode)
Definition at line 520 of file keyframes_edit.c.
References BEZT_OK_FRAME, BEZT_OK_FRAMERANGE, BEZT_OK_REGION, BEZT_OK_SELECTED, BEZT_OK_VALUE, BEZT_OK_VALUERANGE, NULL, ok_bezier_frame(), ok_bezier_framerange(), ok_bezier_region(), ok_bezier_selected(), ok_bezier_value(), and ok_bezier_valuerange().
Referenced by actkeys_mselect_column(), actkeys_mselect_single(), actkeys_select_leftright(), actkeys_select_linked_exec(), ANIM_unit_mapping_apply_fcurve(), borderselect_action(), borderselect_graphkeys(), columnselect_action_keys(), columnselect_graph_keys(), copy_animedit_keys(), deselect_action_keys(), graphkeys_mselect_column(), graphkeys_select_leftright(), graphkeys_select_linked_exec(), markers_selectkeys_between(), poselib_apply_pose(), sethandles_action_keys(), and sethandles_graph_keys().
void ANIM_editkeyframes_refresh (bAnimContext * ac)
Definition at line 385 of file keyframes_edit.c.
References ANIM_animdata_filter(), ANIMFILTER_DATA_VISIBLE, BLI_freelistN(), bAnimContext::data, bAnimContext::datatype, FALSE, filter(), ListBase::first, SpaceIpo::flag, bAnimListElem::key_data, bAnimListElem::next, NULL, SIPO_NOHANDLES, bAnimContext::sl, sort_time_fcurve(), SPACE_IPO, bAnimContext::spacetype, and testhandles_fcurve().
Referenced by actkeys_clean_exec(), actkeys_delete_exec(), actkeys_duplicate_exec(), actkeys_expo_exec(), actkeys_handletype_exec(), actkeys_insertkey_exec(), actkeys_ipo_exec(), actkeys_keytype_exec(), actkeys_mirror_exec(), actkeys_paste_exec(), actkeys_sample_exec(), actkeys_snap_exec(), graph_fmodifier_add_exec(), graph_fmodifier_paste_exec(), graphkeys_bake_exec(), graphkeys_clean_exec(), graphkeys_delete_exec(), graphkeys_duplicate_exec(), graphkeys_euler_filter_exec(), graphkeys_expo_exec(), graphkeys_handletype_exec(), graphkeys_insertkey_exec(), graphkeys_ipo_exec(), graphkeys_mirror_exec(), graphkeys_paste_exec(), graphkeys_sample_exec(), graphkeys_smooth_exec(), graphkeys_snap_exec(), and special_aftertrans_update().
KeyframeEditFunc ANIM_editkeyframes_select (short selectmode)
Definition at line 993 of file keyframes_edit.c.
References SELECT_ADD, select_bezier_add(), select_bezier_invert(), select_bezier_subtract(), SELECT_INVERT, and SELECT_SUBTRACT.
Referenced by actkeys_mselect_column(), actkeys_mselect_single(), actkeys_select_leftright(), actkeys_select_linked_exec(), borderselect_action(), borderselect_graphkeys(), columnselect_action_keys(), columnselect_graph_keys(), deselect_action_keys(), graphkeys_mselect_column(), graphkeys_select_leftright(), graphkeys_select_linked_exec(), markers_selectkeys_between(), and mouse_graph_keys().
KeyframeEditFunc ANIM_editkeyframes_snap (short type)
Definition at line 653 of file keyframes_edit.c.
References snap_bezier_cframe(), snap_bezier_horizontal(), snap_bezier_nearest(), snap_bezier_nearestsec(), snap_bezier_nearmarker(), snap_bezier_value(), SNAP_KEYS_CURFRAME, SNAP_KEYS_HORIZONTAL, SNAP_KEYS_NEARFRAME, SNAP_KEYS_NEARMARKER, SNAP_KEYS_NEARSEC, and SNAP_KEYS_VALUE.
Referenced by snap_action_keys(), and snap_graph_keys().
short ANIM_fcurve_keyframes_loop (KeyframeEditData * ked, FCurve * fcu, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
Definition at line 93 of file keyframes_edit.c.
References FCurve::bezt, KeyframeEditData::curflags, KeyframeEditData::curIndex, ELEM, KeyframeEditData::fcu, i, and NULL.
Referenced by act_keyframes_loop(), actkeys_framejump_exec(), actkeys_mselect_column(), actkeys_select_leftright(), actkeys_select_linked_exec(), agrp_keyframes_loop(), ANIM_animchannel_keyframes_loop(), ANIM_animchanneldata_keyframes_loop(), ANIM_nla_mapping_apply_fcurve(), ANIM_unit_mapping_apply_fcurve(), borderselect_graphkeys(), columnselect_action_keys(), columnselect_graph_keys(), copy_animedit_keys(), deselect_action_keys(), graphkeys_framejump_exec(), graphkeys_mselect_column(), graphkeys_select_leftright(), graphkeys_select_linked_exec(), markers_selectkeys_between(), mirror_action_keys(), mirror_graph_keys(), mouse_graph_keys(), ob_keyframes_loop(), scene_keyframes_loop(), select_moreless_action_keys(), select_moreless_graph_keys(), sethandles_action_keys(), sethandles_graph_keys(), setipo_action_keys(), setipo_graph_keys(), setkeytype_action_keys(), snap_action_keys(), snap_graph_keys(), and summary_keyframes_loop().
static short bezier_isfree (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 808 of file keyframes_edit.c.
References BezTriple::f1, BezTriple::f3, BezTriple::h1, BezTriple::h2, and SELECT.
Referenced by ANIM_editkeyframes_handles().
short bezt_calc_average (KeyframeEditData * ked, BezTriple * bezt)
Definition at line 545 of file keyframes_edit.c.
References KeyframeEditData::f1, BezTriple::f2, KeyframeEditData::f2, KeyframeEditData::i1, SELECT, and BezTriple::vec.
Referenced by actkeys_framejump_exec(), and graphkeys_framejump_exec().
void bezt_remap_times (KeyframeEditData * ked, BezTriple * bezt)
Definition at line 581 of file keyframes_edit.c.
References KeyframeEditData::data, KeyframeEditCD_Remap::newMax, KeyframeEditCD_Remap::newMin, KeyframeEditCD_Remap::oldMax, KeyframeEditCD_Remap::oldMin, and BezTriple::vec.
short bezt_selmap_flush (KeyframeEditData * ked, BezTriple * bezt)
Definition at line 1110 of file keyframes_edit.c.
References BEZ_DESEL, BEZ_SEL, KeyframeEditData::curIndex, and KeyframeEditData::data.
Referenced by select_moreless_action_keys(), and select_moreless_graph_keys().
short bezt_to_cfraelem (KeyframeEditData * ked, BezTriple * bezt)
Definition at line 565 of file keyframes_edit.c.
References BLI_addtail(), CfraElem::cfra, BezTriple::f2, KeyframeEditData::list, MEM_callocN(), SELECT, and BezTriple::vec.
Referenced by columnselect_action_keys(), and columnselect_graph_keys().
static short mirror_bezier_cframe (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 676 of file keyframes_edit.c.
References CFRA, KDL::diff(), BezTriple::f2, KeyframeEditData::scene, SELECT, and BezTriple::vec.
Referenced by ANIM_editkeyframes_mirror().
static short mirror_bezier_marker (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 713 of file keyframes_edit.c.
References KDL::diff(), KeyframeEditData::f1, BezTriple::f2, SELECT, and BezTriple::vec.
Referenced by ANIM_editkeyframes_mirror().
static short mirror_bezier_value (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 724 of file keyframes_edit.c.
References KDL::diff(), KeyframeEditData::f1, BezTriple::f2, SELECT, and BezTriple::vec.
Referenced by ANIM_editkeyframes_mirror().
static short mirror_bezier_xaxis (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 701 of file keyframes_edit.c.
References KDL::diff(), BezTriple::f2, SELECT, and BezTriple::vec.
Referenced by ANIM_editkeyframes_mirror().
static short mirror_bezier_yaxis (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 689 of file keyframes_edit.c.
References KDL::diff(), BezTriple::f2, SELECT, and BezTriple::vec.
Referenced by ANIM_editkeyframes_mirror().
static short ob_keyframes_loop (KeyframeEditData * ked, bDopeSheet * ads, Object * ob, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb) [static]
Definition at line 200 of file keyframes_edit.c.
References bAnimContext::ads, bAnimListElem::adt, Object::adt, ANIM_animdata_filter(), ANIM_fcurve_keyframes_loop(), ANIMCONT_CHANNEL, ANIMFILTER_DATA_VISIBLE, ANIMTYPE_OBJECT, BLI_freelistN(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, filter(), ListBase::first, Object::id, bAnimListElem::id, bAnimListElem::next, NULL, Base::object, and bAnimListElem::type.
Referenced by ANIM_animchannel_keyframes_loop(), and ANIM_animchanneldata_keyframes_loop().
static short ok_bezier_frame (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 436 of file keyframes_edit.c.
References KEY_CHECK_OK, and KEYFRAME_OK_CHECKS.
Referenced by ANIM_editkeyframes_ok().
static short ok_bezier_framerange (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 449 of file keyframes_edit.c.
References KEY_CHECK_OK, and KEYFRAME_OK_CHECKS.
Referenced by ANIM_editkeyframes_ok().
static short ok_bezier_region (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 502 of file keyframes_edit.c.
References KeyframeEditData::data, KEY_CHECK_OK, and KEYFRAME_OK_CHECKS.
Referenced by ANIM_editkeyframes_ok().
static short ok_bezier_selected (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 462 of file keyframes_edit.c.
References BEZSELECTED, and KEYFRAME_OK_ALL.
Referenced by ANIM_editkeyframes_ok().
static short ok_bezier_value (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 473 of file keyframes_edit.c.
References KEY_CHECK_OK, and KEYFRAME_OK_CHECKS.
Referenced by ANIM_editkeyframes_ok().
static short ok_bezier_valuerange (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 489 of file keyframes_edit.c.
References KEY_CHECK_OK, and KEYFRAME_OK_CHECKS.
Referenced by ANIM_editkeyframes_ok().
static short scene_keyframes_loop (KeyframeEditData * ked, bDopeSheet * ads, Scene * sce, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb) [static]
Definition at line 245 of file keyframes_edit.c.
References bAnimContext::ads, bAnimListElem::adt, Scene::adt, ANIM_animdata_filter(), ANIM_fcurve_keyframes_loop(), ANIMCONT_CHANNEL, ANIMFILTER_DATA_VISIBLE, ANIMTYPE_SCENE, BLI_freelistN(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, filter(), ListBase::first, Scene::id, bAnimListElem::id, bAnimListElem::next, NULL, and bAnimListElem::type.
Referenced by ANIM_animchannel_keyframes_loop(), and ANIM_animchanneldata_keyframes_loop().
static short select_bezier_add (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 942 of file keyframes_edit.c.
References BEZ_SEL, KeyframeEditData::curflags, BezTriple::f1, BezTriple::f2, BezTriple::f3, KeyframeEditData::iterflags, KEYFRAME_ITER_INCL_HANDLES, KEYFRAME_OK_H1, KEYFRAME_OK_H2, KEYFRAME_OK_KEY, and SELECT.
Referenced by ANIM_editkeyframes_select().
static short select_bezier_invert (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 978 of file keyframes_edit.c.
References BezTriple::f1, BezTriple::f2, BezTriple::f3, and SELECT.
Referenced by ANIM_editkeyframes_select().
static short select_bezier_subtract (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 960 of file keyframes_edit.c.
References BEZ_DESEL, KeyframeEditData::curflags, BezTriple::f1, BezTriple::f2, BezTriple::f3, KeyframeEditData::iterflags, KEYFRAME_ITER_INCL_HANDLES, KEYFRAME_OK_H1, KEYFRAME_OK_H2, KEYFRAME_OK_KEY, and SELECT.
Referenced by ANIM_editkeyframes_select().
static short selmap_build_bezier_less (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 1053 of file keyframes_edit.c.
References BEZSELECTED, KeyframeEditData::curIndex, KeyframeEditData::data, KeyframeEditData::fcu, i, next, ActBeztColumn::prev, and FCurve::totvert.
Referenced by ANIM_editkeyframes_buildselmap().
static short selmap_build_bezier_more (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 1018 of file keyframes_edit.c.
References BEZSELECTED, KeyframeEditData::curIndex, KeyframeEditData::data, KeyframeEditData::fcu, i, next, ActBeztColumn::prev, and FCurve::totvert.
Referenced by ANIM_editkeyframes_buildselmap().
static short set_bezier_align (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 816 of file keyframes_edit.c.
References BezTriple::f1, BezTriple::f3, BezTriple::h1, BezTriple::h2, HD_ALIGN, and SELECT.
Referenced by ANIM_editkeyframes_handles().
static short set_bezier_auto (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 772 of file keyframes_edit.c.
References ENSURE_HANDLES_MATCH, BezTriple::f1, BezTriple::f3, BezTriple::h1, BezTriple::h2, HD_AUTO, and SELECT.
Referenced by ANIM_editkeyframes_handles().
static short set_bezier_auto_clamped (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 786 of file keyframes_edit.c.
References ENSURE_HANDLES_MATCH, BezTriple::f1, BezTriple::f3, BezTriple::h1, BezTriple::h2, HD_AUTO_ANIM, and SELECT.
Referenced by ANIM_editkeyframes_handles().
static short set_bezier_free (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 824 of file keyframes_edit.c.
References BezTriple::f1, BezTriple::f3, BezTriple::h1, BezTriple::h2, HD_FREE, and SELECT.
Referenced by ANIM_editkeyframes_handles().
static short set_bezier_vector (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 798 of file keyframes_edit.c.
References BezTriple::f1, BezTriple::f3, BezTriple::h1, BezTriple::h2, HD_VECT, and SELECT.
Referenced by ANIM_editkeyframes_handles().
static short set_bezt_bezier (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 869 of file keyframes_edit.c.
References BEZT_IPO_BEZ, BezTriple::f2, BezTriple::ipo, and SELECT.
Referenced by ANIM_editkeyframes_ipo().
static short set_bezt_constant (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 855 of file keyframes_edit.c.
References BEZT_IPO_CONST, BezTriple::f2, BezTriple::ipo, and SELECT.
Referenced by ANIM_editkeyframes_ipo().
static short set_bezt_linear (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 862 of file keyframes_edit.c.
References BEZT_IPO_LIN, BezTriple::f2, BezTriple::ipo, and SELECT.
Referenced by ANIM_editkeyframes_ipo().
static short set_keytype_breakdown (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 899 of file keyframes_edit.c.
References BEZKEYTYPE, BEZT_KEYTYPE_BREAKDOWN, BezTriple::f2, and SELECT.
Referenced by ANIM_editkeyframes_keytype().
static short set_keytype_extreme (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 906 of file keyframes_edit.c.
References BEZKEYTYPE, BEZT_KEYTYPE_EXTREME, BezTriple::f2, and SELECT.
Referenced by ANIM_editkeyframes_keytype().
static short set_keytype_jitter (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 913 of file keyframes_edit.c.
References BEZKEYTYPE, BEZT_KEYTYPE_JITTER, BezTriple::f2, and SELECT.
Referenced by ANIM_editkeyframes_keytype().
static short set_keytype_keyframe (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 892 of file keyframes_edit.c.
References BEZKEYTYPE, BEZT_KEYTYPE_KEYFRAME, BezTriple::f2, and SELECT.
Referenced by ANIM_editkeyframes_keytype().
static short snap_bezier_cframe (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 617 of file keyframes_edit.c.
References CFRA, BezTriple::f2, KeyframeEditData::scene, SELECT, and BezTriple::vec.
Referenced by ANIM_editkeyframes_snap().
static short snap_bezier_horizontal (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 634 of file keyframes_edit.c.
References ELEM3, BezTriple::f2, BezTriple::h1, BezTriple::h2, HD_ALIGN, HD_AUTO, HD_AUTO_ANIM, HD_VECT, SELECT, and BezTriple::vec.
Referenced by ANIM_editkeyframes_snap().
static short snap_bezier_nearest (KeyframeEditData * UNUSEDked, BezTriple * bezt) [static]
Definition at line 598 of file keyframes_edit.c.
References BezTriple::f2, floorf, SELECT, and BezTriple::vec.
Referenced by ANIM_editkeyframes_snap().
static short snap_bezier_nearestsec (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 606 of file keyframes_edit.c.
References BezTriple::f2, FPS, KeyframeEditData::scene, SELECT, and BezTriple::vec.
Referenced by ANIM_editkeyframes_snap().
static short snap_bezier_nearmarker (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 626 of file keyframes_edit.c.
References ED_markers_find_nearest_marker_time(), BezTriple::f2, KeyframeEditData::list, SELECT, and BezTriple::vec.
Referenced by ANIM_editkeyframes_snap().
static short snap_bezier_value (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 646 of file keyframes_edit.c.
References KeyframeEditData::f1, BezTriple::f2, SELECT, and BezTriple::vec.
Referenced by ANIM_editkeyframes_snap().
static short summary_keyframes_loop (KeyframeEditData * ked, bAnimContext * ac, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb) [static]
Definition at line 287 of file keyframes_edit.c.
References ANIM_animdata_filter(), ANIM_fcurve_keyframes_loop(), ANIMFILTER_DATA_VISIBLE, BLI_freelistN(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, filter(), ListBase::first, bAnimListElem::next, and NULL.
Referenced by ANIM_animchannel_keyframes_loop(), and ANIM_animchanneldata_keyframes_loop().