Blender: HalfArray< T > Class Template Reference
HalfArray< T > Class Template Reference
Public Member Functions
HalfArray ()
~HalfArray ()
void resize (unsigned int size)
T & operator() (unsigned int x, unsigned int y)
void erase_column (unsigned int x)
void delete_column (unsigned int x)
void erase_row (unsigned int y)
Detailed Description
template<typename T>
class HalfArray< T >
A Half array is a square 2d array where cell(x, y) is undefined if x < y.
Definition at line 175 of file SG_Tree.cpp.
Constructor & Destructor Documentation
template<typename T> HalfArray< T >::HalfArray () [inline]
Definition at line 179 of file SG_Tree.cpp.
template<typename T> HalfArray< T >::~HalfArray () [inline]
Definition at line 180 of file SG_Tree.cpp.
Member Function Documentation
template<typename T> void HalfArray< T >::delete_column (unsigned int x) [inline]
Definition at line 203 of file SG_Tree.cpp.
Referenced by SG_TreeFactory::MakeTreeUp().
template<typename T> void HalfArray< T >::erase_column (unsigned int x) [inline]
Definition at line 197 of file SG_Tree.cpp.
template<typename T> void HalfArray< T >::erase_row (unsigned int y) [inline]
Definition at line 212 of file SG_Tree.cpp.
Referenced by SG_TreeFactory::MakeTreeUp().
template<typename T> T& HalfArray< T >::operator() (unsigned int x, unsigned int y) [inline]
Definition at line 191 of file SG_Tree.cpp.
References assert.
template<typename T> void HalfArray< T >::resize (unsigned int size) [inline]
Definition at line 182 of file SG_Tree.cpp.
References i, and size().
Referenced by SG_TreeFactory::MakeTreeUp().
The documentation for this class was generated from the following file:
SG_Tree.cpp