Blender: rna_camera.c File Reference
rna_camera.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_camera_types.h"
#include "BLI_math.h"
#include "WM_types.h"
Functions
void RNA_def_camera (BlenderRNA *brna)
Detailed Description
Definition in file rna_camera.c.
Function Documentation
void RNA_def_camera (BlenderRNA * brna)
Definition at line 93 of file rna_camera.c.
References CAM_ANGLETOGGLE, CAM_DTX_CENTER, CAM_DTX_CENTER_DIAG, CAM_DTX_GOLDEN, CAM_DTX_GOLDEN_TRI_A, CAM_DTX_GOLDEN_TRI_B, CAM_DTX_HARMONY_TRI_A, CAM_DTX_HARMONY_TRI_B, CAM_DTX_THIRDS, CAM_ORTHO, CAM_PANORAMA, CAM_PERSP, CAM_SHOWLIMITS, CAM_SHOWMIST, CAM_SHOWNAME, CAM_SHOWPASSEPARTOUT, CAM_SHOWSENSOR, CAM_SHOWTITLESAFE, CAMERA_SENSOR_FIT_AUTO, CAMERA_SENSOR_FIT_HOR, CAMERA_SENSOR_FIT_VERT, FLT_MAX, M_PI, NC_OBJECT, ND_DRAW, NULL, PROP_ANGLE, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_ENUM_FLAG, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_api_camera(), rna_def_animdata_common(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().