Blender: AttributeRequestSet Class Reference
AttributeRequestSet Class Reference
#include <attribute.h>
Public Member Functions
AttributeRequestSet ()
~AttributeRequestSet ()
void add (ustring name)
void add (Attribute::Standard std)
void add (AttributeRequestSet &reqs)
bool find (ustring name)
bool find (Attribute::Standard std)
size_t size ()
void clear ()
bool modified (const AttributeRequestSet &other)
Public Attributes
vector< AttributeRequest > requests
Detailed Description
Definition at line 138 of file attribute.h.
Constructor & Destructor Documentation
AttributeRequestSet::AttributeRequestSet ()
Definition at line 262 of file attribute.cpp.
AttributeRequestSet::~AttributeRequestSet ()
Definition at line 266 of file attribute.cpp.
Member Function Documentation
void AttributeRequestSet::add (ustring name)
Definition at line 290 of file attribute.cpp.
References AttributeRequest::name, and requests.
Referenced by add(), AttributeNode::attributes(), TextureCoordinateNode::attributes(), and ShaderNode::attributes().
void AttributeRequestSet::add (Attribute::Standard std)
Definition at line 299 of file attribute.cpp.
References requests, and AttributeRequest::std.
void AttributeRequestSet::add (AttributeRequestSet & reqs)
Definition at line 308 of file attribute.cpp.
References add(), AttributeRequest::name, requests, AttributeRequest::std, and Attribute::STD_NONE.
void AttributeRequestSet::clear ()
Definition at line 341 of file attribute.cpp.
References requests.
Referenced by Shader::tag_update().
bool AttributeRequestSet::find (Attribute::Standard std)
Definition at line 327 of file attribute.cpp.
References requests, and AttributeRequest::std.
bool AttributeRequestSet::find (ustring name)
Definition at line 318 of file attribute.cpp.
References AttributeRequest::name, and requests.
bool AttributeRequestSet::modified (const AttributeRequestSet & other)
Definition at line 270 of file attribute.cpp.
References i, and requests.
Referenced by Shader::tag_update().
size_t AttributeRequestSet::size ()
Definition at line 336 of file attribute.cpp.
References requests.
Member Data Documentation
vector<AttributeRequest> AttributeRequestSet::requests
Definition at line 140 of file attribute.h.
Referenced by add(), clear(), MeshManager::device_update_attributes(), find(), modified(), size(), MeshManager::update_osl_attributes(), and MeshManager::update_svm_attributes().
The documentation for this class was generated from the following files:
attribute.h
attribute.cpp