Blender: btDiscreteDynamicsWorld.cpp File Reference
btDiscreteDynamicsWorld.cpp File Reference
#include "btDiscreteDynamicsWorld.h"
#include "BulletCollision/CollisionDispatch/btCollisionDispatcher.h"
#include "BulletCollision/BroadphaseCollision/btSimpleBroadphase.h"
#include "BulletCollision/BroadphaseCollision/btCollisionAlgorithm.h"
#include "BulletCollision/CollisionShapes/btCollisionShape.h"
#include "BulletCollision/CollisionDispatch/btSimulationIslandManager.h"
#include "LinearMath/btTransformUtil.h"
#include "LinearMath/btQuickprof.h"
#include "BulletDynamics/Dynamics/btRigidBody.h"
#include "BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.h"
#include "BulletDynamics/ConstraintSolver/btContactSolverInfo.h"
#include "BulletDynamics/ConstraintSolver/btTypedConstraint.h"
#include "BulletDynamics/ConstraintSolver/btPoint2PointConstraint.h"
#include "BulletDynamics/ConstraintSolver/btHingeConstraint.h"
#include "BulletDynamics/ConstraintSolver/btConeTwistConstraint.h"
#include "BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.h"
#include "BulletDynamics/ConstraintSolver/btSliderConstraint.h"
#include "LinearMath/btIDebugDraw.h"
#include "BulletCollision/CollisionShapes/btSphereShape.h"
#include "BulletDynamics/Dynamics/btActionInterface.h"
#include "LinearMath/btMotionState.h"
#include "LinearMath/btSerializer.h"
Classes
class btSortConstraintOnIslandPredicate
class btClosestNotMeConvexResultCallback
Functions
SIMD_FORCE_INLINE int btGetConstraintIslandId (const btTypedConstraint *lhs)
Variables
int gNumClampedCcdMotions = 0
internal debugging variable. this value shouldn't be too high
Function Documentation
SIMD_FORCE_INLINE int btGetConstraintIslandId (const btTypedConstraint * lhs)
Definition at line 527 of file btDiscreteDynamicsWorld.cpp.
References btTypedConstraint::getRigidBodyA(), and btTypedConstraint::getRigidBodyB().
Referenced by btSortConstraintOnIslandPredicate::operator()(), and btDiscreteDynamicsWorld::solveConstraints().
Variable Documentation
int gNumClampedCcdMotions = 0
internal debugging variable. this value shouldn't be too high
Definition at line 825 of file btDiscreteDynamicsWorld.cpp.
Referenced by btDiscreteDynamicsWorld::integrateTransforms().