Blender: node_shader_fresnel.c File Reference
node_shader_fresnel.c File Reference
#include "../node_shader_util.h"
Functions
static int node_shader_gpu_fresnel (GPUMaterial *mat, bNode *UNUSED(node), GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_fresnel (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_fresnel_in []
static bNodeSocketTemplate sh_node_fresnel_out []
Function Documentation
static int node_shader_gpu_fresnel (GPUMaterial * mat, bNode * UNUSEDnode, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 41 of file node_shader_fresnel.c.
References GPU_builtin(), GPU_stack_link(), GPU_VIEW_NORMAL, and GPU_VIEW_POSITION.
Referenced by register_node_type_sh_fresnel().
void register_node_type_sh_fresnel (bNodeTreeType * ttype)
Definition at line 48 of file node_shader_fresnel.c.
References NODE_CLASS_INPUT, NODE_NEW_SHADING, node_shader_gpu_fresnel(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_FRESNEL.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_fresnel_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "IOR",   1.45f, 0.0f, 0.0f, 0.0f, 1.0f, 1000.0f},
    {   -1, 0, ""   }
}
Definition at line 31 of file node_shader_fresnel.c.
bNodeSocketTemplate sh_node_fresnel_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "Fac",   0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_shader_fresnel.c.