Blender: KX_VertexParentRelation Class Reference
KX_VertexParentRelation Class Reference
#include <KX_SG_NodeRelationships.h>
Public Member Functions
bool UpdateChildCoordinates (SG_Spatial *child, const SG_Spatial *parent, bool &parentUpdated)
SG_ParentRelation * NewCopy ()
~KX_VertexParentRelation ()
bool IsVertexRelation ()
Static Public Member Functions
static KX_VertexParentRelation * New ()
Detailed Description
Definition at line 98 of file KX_SG_NodeRelationships.h.
Constructor & Destructor Documentation
KX_VertexParentRelation::~KX_VertexParentRelation ()
Definition at line 156 of file KX_SG_NodeRelationships.cpp.
Member Function Documentation
bool KX_VertexParentRelation::IsVertexRelation () [inline, virtual]
Vertex Parent Relation are special: they don't propagate rotation
Reimplemented from SG_ParentRelation.
Definition at line 136 of file KX_SG_NodeRelationships.h.
KX_VertexParentRelation * KX_VertexParentRelation::New () [static]
Allocate and construct a new KX_VertexParentRelation on the heap.
Next KX_VertexParentRelation
Definition at line 110 of file KX_SG_NodeRelationships.cpp.
Referenced by BL_ConvertBlenderObjects().
SG_ParentRelation * KX_VertexParentRelation::NewCopy () [virtual]
Method inherited from KX_ParentRelation
Implements SG_ParentRelation.
Definition at line 150 of file KX_SG_NodeRelationships.cpp.
bool KX_VertexParentRelation::UpdateChildCoordinates (SG_Spatial * child, const SG_Spatial * parent, bool & parentUpdated) [virtual]
Method inherited from KX_ParentRelation
Implements SG_ParentRelation.
Definition at line 121 of file KX_SG_NodeRelationships.cpp.
References SG_Spatial::ClearModified(), SG_Spatial::GetLocalOrientation(), SG_Spatial::GetLocalPosition(), SG_Spatial::GetLocalScale(), SG_Spatial::GetWorldPosition(), SG_Spatial::IsModified(), MT_assert, NULL, SG_Spatial::SetWorldOrientation(), SG_Spatial::SetWorldPosition(), and SG_Spatial::SetWorldScale().
The documentation for this class was generated from the following files:
KX_SG_NodeRelationships.h
KX_SG_NodeRelationships.cpp