Blender: KX_SCA_EndObjectActuator Class Reference
KX_SCA_EndObjectActuator Class Reference
#include <KX_SCA_EndObjectActuator.h>
Public Member Functions
KX_SCA_EndObjectActuator (SCA_IObject *gameobj, SCA_IScene *scene)
~KX_SCA_EndObjectActuator ()
CValue * GetReplica ()
virtual bool Update ()
virtual void Replace_IScene (SCA_IScene *val)
Detailed Description
Definition at line 42 of file KX_SCA_EndObjectActuator.h.
Constructor & Destructor Documentation
KX_SCA_EndObjectActuator::KX_SCA_EndObjectActuator (SCA_IObject * gameobj, SCA_IScene * scene)
Definition at line 45 of file KX_SCA_EndObjectActuator.cpp.
Referenced by GetReplica().
KX_SCA_EndObjectActuator::~KX_SCA_EndObjectActuator ()
Definition at line 55 of file KX_SCA_EndObjectActuator.cpp.
Member Function Documentation
CValue * KX_SCA_EndObjectActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 77 of file KX_SCA_EndObjectActuator.cpp.
References KX_SCA_EndObjectActuator(), NULL, and SCA_IActuator::ProcessReplica().
virtual void KX_SCA_EndObjectActuator::Replace_IScene (SCA_IScene * val) [inline, virtual]
Reimplemented from SCA_ILogicBrick.
Definition at line 62 of file KX_SCA_EndObjectActuator.h.
bool KX_SCA_EndObjectActuator::Update (void) [virtual]
Reimplemented from SCA_IActuator.
Definition at line 62 of file KX_SCA_EndObjectActuator.cpp.
References SCA_IScene::DelayedRemoveObject(), SCA_ILogicBrick::GetParent(), SCA_IActuator::IsNegativeEvent(), and SCA_IActuator::RemoveAllEvents().
The documentation for this class was generated from the following files:
KX_SCA_EndObjectActuator.h
KX_SCA_EndObjectActuator.cpp