Blender: BL_System.cpp File Reference
BL_System.cpp File Reference
Blender Routines
#include "CTR_Map.h"
#include "STR_HashedString.h"
#include "BL_System.h"
Classes
struct SingletonSystem
Functions
SYS_SystemHandle SYS_GetSystem ()
void SYS_DeleteSystem (SYS_SystemHandle sys)
int SYS_GetCommandLineInt (SYS_SystemHandle sys, const char *paramname, int defaultvalue)
float SYS_GetCommandLineFloat (SYS_SystemHandle sys, const char *paramname, float defaultvalue)
const char * SYS_GetCommandLineString (SYS_SystemHandle sys, const char *paramname, const char *defaultvalue)
void SYS_WriteCommandLineInt (SYS_SystemHandle sys, const char *paramname, int value)
void SYS_WriteCommandLineFloat (SYS_SystemHandle sys, const char *paramname, float value)
void SYS_WriteCommandLineString (SYS_SystemHandle sys, const char *paramname, const char *value)
Variables
static SingletonSystem * _system_instance = NULL
Detailed Description
Definition in file BL_System.cpp.
Function Documentation
void SYS_DeleteSystem (SYS_SystemHandle sys)
Definition at line 53 of file BL_System.cpp.
References _system_instance, and NULL.
Referenced by main(), and WM_exit_ext().
float SYS_GetCommandLineFloat (SYS_SystemHandle sys, const char * paramname, float defaultvalue)
Definition at line 70 of file BL_System.cpp.
int SYS_GetCommandLineInt (SYS_SystemHandle sys, const char * paramname, int defaultvalue)
Definition at line 61 of file BL_System.cpp.
Referenced by KX_BlenderSceneConverter::ConvertScene(), GPG_Application::initEngine(), KX_Scene::KX_Scene(), main(), and StartKetsjiShell().
const char* SYS_GetCommandLineString (SYS_SystemHandle sys, const char * paramname, const char * defaultvalue)
Definition at line 79 of file BL_System.cpp.
SYS_SystemHandle SYS_GetSystem (void)
Definition at line 45 of file BL_System.cpp.
References _system_instance.
Referenced by KX_BlenderSceneConverter::ConvertScene(), GPG_Application::initEngine(), KX_Scene::KX_Scene(), main(), StartKetsjiShell(), and WM_exit_ext().
void SYS_WriteCommandLineFloat (SYS_SystemHandle sys, const char * paramname, float value)
Definition at line 93 of file BL_System.cpp.
Referenced by main().
void SYS_WriteCommandLineInt (SYS_SystemHandle sys, const char * paramname, int value)
Definition at line 88 of file BL_System.cpp.
Referenced by GPG_Application::initEngine(), main(), no_joystick(), and set_ge_parameters().
void SYS_WriteCommandLineString (SYS_SystemHandle sys, const char * paramname, const char * value)
Definition at line 98 of file BL_System.cpp.
Referenced by main(), and set_ge_parameters().
Variable Documentation
SingletonSystem* _system_instance = NULL [static]
Definition at line 43 of file BL_System.cpp.
Referenced by SYS_DeleteSystem(), and SYS_GetSystem().