Blender: BL_DeformableGameObject Class Reference
BL_DeformableGameObject Class Reference
#include <BL_DeformableGameObject.h>
Public Member Functions
CValue * GetReplica ()
double GetLastFrame ()
Object * GetBlendObject ()
virtual void Relink (CTR_Map< CTR_HashedPtr, void * > *map)
void ProcessReplica ()
BL_DeformableGameObject (Object *blendobj, void *sgReplicationInfo, SG_Callbacks callbacks)
virtual ~BL_DeformableGameObject ()
bool SetActiveAction (class BL_ShapeActionActuator *act, short priority, double curtime)
bool GetShape (vector< float > &shape)
virtual void SetDeformer (class RAS_Deformer *deformer)
virtual class RAS_Deformer * GetDeformer ()
Protected Attributes
RAS_Deformer * m_pDeformer
class BL_ShapeActionActuator * m_activeAct
double m_lastframe
Object * m_blendobj
short m_activePriority
Detailed Description
Definition at line 48 of file BL_DeformableGameObject.h.
Constructor & Destructor Documentation
BL_DeformableGameObject::BL_DeformableGameObject (Object * blendobj, void * sgReplicationInfo, SG_Callbacks callbacks) [inline]
Definition at line 69 of file BL_DeformableGameObject.h.
References KX_GameObject::m_isDeformable.
Referenced by GetReplica().
BL_DeformableGameObject::~BL_DeformableGameObject () [virtual]
Definition at line 39 of file BL_DeformableGameObject.cpp.
References m_pDeformer.
Member Function Documentation
Object* BL_DeformableGameObject::GetBlendObject () [inline]
Definition at line 57 of file BL_DeformableGameObject.h.
References m_blendobj.
Referenced by BL_ModifierDeformer::GetPhysicsMesh(), BL_ModifierDeformer::Update(), and BL_ShapeDeformer::Update().
virtual class RAS_Deformer* BL_DeformableGameObject::GetDeformer () [inline, virtual]
Reimplemented from KX_GameObject.
Definition at line 85 of file BL_DeformableGameObject.h.
References m_pDeformer.
Referenced by BL_Action::BL_Action(), BL_ConvertBlenderObjects(), BL_ShapeActionActuator::BL_ShapeActionActuator(), BL_Action::Play(), KX_Scene::ReplaceMesh(), BL_Action::Update(), and BL_ShapeActionActuator::Update().
double BL_DeformableGameObject::GetLastFrame () [inline]
Definition at line 53 of file BL_DeformableGameObject.h.
References m_lastframe.
Referenced by BL_MeshDeformer::Apply(), BL_ModifierDeformer::Update(), and BL_ShapeDeformer::Update().
CValue * BL_DeformableGameObject::GetReplica (void) [virtual]
Inherited from CValue -- return a new copy of this instance allocated on the heap. Ownership of the new object belongs with the caller.
Reimplemented from KX_GameObject.
Definition at line 53 of file BL_DeformableGameObject.cpp.
References BL_DeformableGameObject(), and ProcessReplica().
bool BL_DeformableGameObject::GetShape (vector< float > & shape)
Definition at line 85 of file BL_DeformableGameObject.cpp.
References Key::block, KeyBlock::curval, ListBase::first, BL_ShapeDeformer::GetKey(), KEY_RELATIVE, m_pDeformer, KeyBlock::next, and Key::type.
Referenced by BL_Action::Play(), BL_Action::Update(), and BL_ShapeActionActuator::Update().
void BL_DeformableGameObject::ProcessReplica () [virtual]
Inherited from CValue -- Makes sure any internal data owned by this class is deep copied. Called internally
Reimplemented from KX_GameObject.
Definition at line 45 of file BL_DeformableGameObject.cpp.
References RAS_Deformer::GetReplica(), and m_pDeformer.
Referenced by GetReplica().
virtual void BL_DeformableGameObject::Relink (CTR_Map< CTR_HashedPtr, void * > * map) [inline, virtual]
Reimplemented from KX_GameObject.
Definition at line 61 of file BL_DeformableGameObject.h.
References m_pDeformer, and RAS_Deformer::Relink().
bool BL_DeformableGameObject::SetActiveAction (class BL_ShapeActionActuator * act, short priority, double curtime)
Definition at line 61 of file BL_DeformableGameObject.cpp.
References m_activeAct, m_activePriority, m_lastframe, NULL, and BL_ShapeActionActuator::SetBlendTime().
Referenced by BL_Action::Update(), and BL_ShapeActionActuator::Update().
void BL_DeformableGameObject::SetDeformer (class RAS_Deformer * deformer) [virtual]
Reimplemented from KX_GameObject.
Definition at line 106 of file BL_DeformableGameObject.cpp.
References SG_QList::iterator< T >::begin(), SG_QList::iterator< T >::end(), KX_GameObject::m_meshSlots, and m_pDeformer.
Referenced by KX_Scene::ReplaceMesh().
Member Data Documentation
class BL_ShapeActionActuator* BL_DeformableGameObject::m_activeAct [protected]
Definition at line 96 of file BL_DeformableGameObject.h.
Referenced by SetActiveAction().
short BL_DeformableGameObject::m_activePriority [protected]
Definition at line 99 of file BL_DeformableGameObject.h.
Referenced by SetActiveAction().
Object* BL_DeformableGameObject::m_blendobj [protected]
Definition at line 98 of file BL_DeformableGameObject.h.
Referenced by GetBlendObject().
double BL_DeformableGameObject::m_lastframe [protected]
Definition at line 97 of file BL_DeformableGameObject.h.
Referenced by GetLastFrame(), and SetActiveAction().
RAS_Deformer* BL_DeformableGameObject::m_pDeformer [protected]
Definition at line 94 of file BL_DeformableGameObject.h.
Referenced by GetDeformer(), GetShape(), ProcessReplica(), Relink(), SetDeformer(), and ~BL_DeformableGameObject().
The documentation for this class was generated from the following files:
BL_DeformableGameObject.h
BL_DeformableGameObject.cpp