Blender: KX_ObColorIpoSGController Class Reference
KX_ObColorIpoSGController Class Reference
#include <KX_ObColorIpoSGController.h>
Public Member Functions
KX_ObColorIpoSGController ()
virtual ~KX_ObColorIpoSGController ()
virtual SG_Controller * GetReplica (class SG_Node *destnode)
virtual bool Update (double time)
virtual void SetSimulatedTime (double time)
void SetOption (int option, int value)
void AddInterpolator (KX_IInterpolator *interp)
Public Attributes
MT_Vector4 m_rgba
Detailed Description
Definition at line 39 of file KX_ObColorIpoSGController.h.
Constructor & Destructor Documentation
KX_ObColorIpoSGController::KX_ObColorIpoSGController () [inline]
Definition at line 51 of file KX_ObColorIpoSGController.h.
Referenced by GetReplica().
KX_ObColorIpoSGController::~KX_ObColorIpoSGController () [virtual]
Definition at line 105 of file KX_ObColorIpoSGController.cpp.
References i.
Member Function Documentation
void KX_ObColorIpoSGController::AddInterpolator (KX_IInterpolator * interp)
Definition at line 71 of file KX_ObColorIpoSGController.cpp.
Referenced by BL_CreateIPO(), and GetReplica().
SG_Controller * KX_ObColorIpoSGController::GetReplica (class SG_Node * destnode) [virtual]
Implements SG_Controller.
Definition at line 76 of file KX_ObColorIpoSGController.cpp.
References AddInterpolator(), SG_Controller::ClearObject(), i, KX_ObColorIpoSGController(), and KX_ScalarInterpolator::SetNewTarget().
void KX_ObColorIpoSGController::SetOption (int option, int value) [inline, virtual]
Hacky way of passing options to specific controllers
Parameters:
option An integer identifying the option.
value The value of this option.
Attention:
This has been placed here to give sca-elements
some control over the controllers. This is
necessary because the identity of the controller
is lost on the way here.
Implements SG_Controller.
Definition at line 64 of file KX_ObColorIpoSGController.h.
virtual void KX_ObColorIpoSGController::SetSimulatedTime (double time) [inline, virtual]
Implements SG_Controller.
Definition at line 58 of file KX_ObColorIpoSGController.h.
bool KX_ObColorIpoSGController::Update (double time) [virtual]
Implements SG_Controller.
Definition at line 44 of file KX_ObColorIpoSGController.cpp.
References SG_IObject::GetSGClientObject(), i, SG_Controller::m_pObject, m_rgba, and KX_GameObject::SetObjectColor().
Member Data Documentation
MT_Vector4 KX_ObColorIpoSGController::m_rgba
Definition at line 42 of file KX_ObColorIpoSGController.h.
Referenced by BL_CreateIPO(), and Update().
The documentation for this class was generated from the following files:
KX_ObColorIpoSGController.h
KX_ObColorIpoSGController.cpp