Blender: MT_Vector3.h File Reference
MT_Vector3.h File Reference
moto
#include <MT_assert.h>
#include "MT_Tuple3.h"
Classes
class MT_Vector3
Functions
MT_Vector3 operator+ (const MT_Vector3 &v1, const MT_Vector3 &v2)
MT_Vector3 operator- (const MT_Vector3 &v1, const MT_Vector3 &v2)
MT_Vector3 operator- (const MT_Vector3 &v)
MT_Vector3 operator* (const MT_Vector3 &v, MT_Scalar s)
MT_Vector3 operator* (MT_Scalar s, const MT_Vector3 &v)
MT_Vector3 operator/ (const MT_Vector3 &v, MT_Scalar s)
MT_Vector3 operator* (const MT_Vector3 &v1, const MT_Vector3 &v2)
MT_Scalar MT_dot (const MT_Vector3 &v1, const MT_Vector3 &v2)
MT_Scalar MT_length2 (const MT_Vector3 &v)
MT_Scalar MT_length (const MT_Vector3 &v)
bool MT_fuzzyZero (const MT_Vector3 &v)
bool MT_fuzzyEqual (const MT_Vector3 &v1, const MT_Vector3 &v2)
MT_Scalar MT_angle (const MT_Vector3 &v1, const MT_Vector3 &v2)
MT_Vector3 MT_cross (const MT_Vector3 &v1, const MT_Vector3 &v2)
MT_Scalar MT_triple (const MT_Vector3 &v1, const MT_Vector3 &v2, const MT_Vector3 &v3)
Detailed Description
Definition in file MT_Vector3.h.
Function Documentation
MT_Scalar MT_angle (const MT_Vector3 & v1, const MT_Vector3 & v2)
Definition at line 130 of file MT_Vector3.inl.
References MT_Vector3::angle().
MT_Vector3 MT_cross (const MT_Vector3 & v1, const MT_Vector3 & v2)
Definition at line 131 of file MT_Vector3.inl.
References MT_Vector3::cross().
MT_Scalar MT_dot (const MT_Vector3 & v1, const MT_Vector3 & v2)
Definition at line 118 of file MT_Vector3.inl.
References MT_Vector3::dot().
bool MT_fuzzyEqual (const MT_Vector3 & v1, const MT_Vector3 & v2)
Definition at line 126 of file MT_Vector3.inl.
References MT_fuzzyZero().
bool MT_fuzzyZero (const MT_Vector3 & v)
Definition at line 125 of file MT_Vector3.inl.
References MT_Vector3::fuzzyZero().
MT_Scalar MT_length (const MT_Vector3 & v)
Definition at line 123 of file MT_Vector3.inl.
References MT_Vector3::length().
MT_Scalar MT_length2 (const MT_Vector3 & v)
Definition at line 122 of file MT_Vector3.inl.
References MT_Vector3::length2().
MT_Scalar MT_triple (const MT_Vector3 & v1, const MT_Vector3 & v2, const MT_Vector3 & v3)
Definition at line 132 of file MT_Vector3.inl.
References MT_Vector3::triple().
MT_Vector3 operator* (const MT_Vector3 & v, MT_Scalar s)
Definition at line 35 of file MT_Vector3.inl.
MT_Vector3 operator* (MT_Scalar s, const MT_Vector3 & v)
Definition at line 39 of file MT_Vector3.inl.
MT_Vector3 operator* (const MT_Vector3 & v1, const MT_Vector3 & v2)
Definition at line 46 of file MT_Vector3.inl.
MT_Vector3 operator+ (const MT_Vector3 & v1, const MT_Vector3 & v2)
Definition at line 23 of file MT_Vector3.inl.
MT_Vector3 operator- (const MT_Vector3 & v1, const MT_Vector3 & v2)
Definition at line 27 of file MT_Vector3.inl.
MT_Vector3 operator- (const MT_Vector3 & v)
Definition at line 31 of file MT_Vector3.inl.
MT_Vector3 operator/ (const MT_Vector3 & v, MT_Scalar s)
Definition at line 41 of file MT_Vector3.inl.
References MT_assert, and MT_fuzzyZero().