Blender: btBoxBoxDetector Struct Reference
btBoxBoxDetector Struct Reference
#include <btBoxBoxDetector.h>
Public Member Functions
btBoxBoxDetector (btBoxShape *box1, btBoxShape *box2)
ODE box-box collision detection is adapted to work with Bullet.
virtual ~btBoxBoxDetector ()
virtual void getClosestPoints (const ClosestPointInput &input, Result &output, class btIDebugDraw *debugDraw, bool swapResults=false)
Public Attributes
btBoxShape * m_box1
btBoxShape * m_box2
Detailed Description
btBoxBoxDetector wraps the ODE box-box collision detector re-distributed under the Zlib license with permission from Russell L. Smith
Definition at line 29 of file btBoxBoxDetector.h.
Constructor & Destructor Documentation
btBoxBoxDetector::btBoxBoxDetector (btBoxShape * box1, btBoxShape * box2)
ODE box-box collision detection is adapted to work with Bullet.
Definition at line 27 of file btBoxBoxDetector.cpp.
virtual btBoxBoxDetector::~btBoxBoxDetector () [inline, virtual]
Definition at line 38 of file btBoxBoxDetector.h.
Member Function Documentation
void btBoxBoxDetector::getClosestPoints (const ClosestPointInput & input, Result & output, class btIDebugDraw * debugDraw, bool swapResults = false) [virtual]
Implements btDiscreteCollisionDetectorInterface.
Definition at line 673 of file btBoxBoxDetector.cpp.
References dBoxBox2(), btTransform::getBasis(), btBoxShape::getHalfExtentsWithMargin(), btTransform::getOrigin(), m_box1, m_box2, btDiscreteCollisionDetectorInterface::ClosestPointInput::m_transformA, and btDiscreteCollisionDetectorInterface::ClosestPointInput::m_transformB.
Referenced by btBoxBoxCollisionAlgorithm::processCollision().
Member Data Documentation
btBoxShape* btBoxBoxDetector::m_box1
Definition at line 31 of file btBoxBoxDetector.h.
Referenced by getClosestPoints().
btBoxShape* btBoxBoxDetector::m_box2
Definition at line 32 of file btBoxBoxDetector.h.
Referenced by getClosestPoints().
The documentation for this struct was generated from the following files:
btBoxBoxDetector.h
btBoxBoxDetector.cpp