Blender: btConvexPlaneCollisionAlgorithm Class Reference
btConvexPlaneCollisionAlgorithm Class Reference
#include <btConvexPlaneCollisionAlgorithm.h>
Classes
struct CreateFunc
Public Member Functions
btConvexPlaneCollisionAlgorithm (btPersistentManifold *mf, const btCollisionAlgorithmConstructionInfo &ci, btCollisionObject *col0, btCollisionObject *col1, bool isSwapped, int numPerturbationIterations, int minimumPointsPerturbationThreshold)
virtual ~btConvexPlaneCollisionAlgorithm ()
virtual void processCollision (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
void collideSingleContact (const btQuaternion &perturbeRot, btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
virtual btScalar calculateTimeOfImpact (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
virtual void getAllContactManifolds (btManifoldArray &manifoldArray)
Detailed Description
btSphereBoxCollisionAlgorithm provides sphere-box collision detection. Other features are frame-coherency (persistent data) and collision response.
Definition at line 29 of file btConvexPlaneCollisionAlgorithm.h.
Constructor & Destructor Documentation
btConvexPlaneCollisionAlgorithm::btConvexPlaneCollisionAlgorithm (btPersistentManifold * mf, const btCollisionAlgorithmConstructionInfo & ci, btCollisionObject * col0, btCollisionObject * col1, bool isSwapped, int numPerturbationIterations, int minimumPointsPerturbationThreshold)
Definition at line 25 of file btConvexPlaneCollisionAlgorithm.cpp.
References btDispatcher::getNewManifold(), btCollisionAlgorithm::m_dispatcher, and btDispatcher::needsCollision().
Referenced by btConvexPlaneCollisionAlgorithm::CreateFunc::CreateCollisionAlgorithm().
btConvexPlaneCollisionAlgorithm::~btConvexPlaneCollisionAlgorithm () [virtual]
Definition at line 44 of file btConvexPlaneCollisionAlgorithm.cpp.
References btCollisionAlgorithm::m_dispatcher, and btDispatcher::releaseManifold().
Member Function Documentation
btScalar btConvexPlaneCollisionAlgorithm::calculateTimeOfImpact (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Implements btCollisionAlgorithm.
Definition at line 146 of file btConvexPlaneCollisionAlgorithm.cpp.
void btConvexPlaneCollisionAlgorithm::collideSingleContact (const btQuaternion & perturbeRot, btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut)
report a contact. internally this will be kept persistent, and contact reduction is done
Definition at line 53 of file btConvexPlaneCollisionAlgorithm.cpp.
References btManifoldResult::addContactPoint(), distance(), btTransform::getBasis(), btTransform::inverse(), and btManifoldResult::setPersistentManifold().
Referenced by processCollision().
virtual void btConvexPlaneCollisionAlgorithm::getAllContactManifolds (btManifoldArray & manifoldArray) [inline, virtual]
Implements btCollisionAlgorithm.
Definition at line 49 of file btConvexPlaneCollisionAlgorithm.h.
References btAlignedObjectArray< T >::push_back().
void btConvexPlaneCollisionAlgorithm::processCollision (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Implements btCollisionAlgorithm.
Definition at line 93 of file btConvexPlaneCollisionAlgorithm.cpp.
References btPlaneSpace1(), collideSingleContact(), gContactBreakingThreshold, btManifoldResult::getPersistentManifold(), i, btManifoldResult::refreshContactPoints(), SIMD_2_PI, and SIMD_PI.
The documentation for this class was generated from the following files:
btConvexPlaneCollisionAlgorithm.h
btConvexPlaneCollisionAlgorithm.cpp