Blender: rotate.c File Reference
rotate.c File Reference
IMage Buffer
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "MEM_guardedalloc.h"
#include "imbuf.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_allocimbuf.h"
Functions
void IMB_flipy (struct ImBuf *ibuf)
void IMB_flipx (struct ImBuf *ibuf)
Detailed Description
Definition in file rotate.c.
Function Documentation
void IMB_flipx (struct ImBuf * ibuf)
Attention:
Defined in rotate.c
Definition at line 100 of file rotate.c.
References NULL, ImBuf::rect, ImBuf::rect_float, SWAP, ImBuf::x, and ImBuf::y.
Referenced by input_preprocess().
void IMB_flipy (struct ImBuf * ibuf)
Definition at line 47 of file rotate.c.
References MEM_freeN(), MEM_mallocN(), NULL, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by imb_load_dds(), imb_loadhdr(), imb_loadtarga(), index_rebuild_fallback(), and input_preprocess().