Blender: KX_ISystem Class Reference
KX_ISystem Class Reference
#include <KX_ISystem.h>
Public Member Functions
KX_ISystem ()
virtual ~KX_ISystem ()
virtual double GetTimeInSeconds ()=0
Detailed Description
System Abstraction, needed only for getting some timing stuff from the host.
Definition at line 48 of file KX_ISystem.h.
Constructor & Destructor Documentation
KX_ISystem::KX_ISystem () [inline]
Definition at line 51 of file KX_ISystem.h.
virtual KX_ISystem::~KX_ISystem () [inline, virtual]
Definition at line 52 of file KX_ISystem.h.
Member Function Documentation
virtual double KX_ISystem::GetTimeInSeconds () [pure virtual]
Implemented in KX_BlenderSystem, GPC_System, and GPG_System.
Referenced by KX_KetsjiEngine::BeginFrame(), KX_KetsjiEngine::EndFrame(), KX_KetsjiEngine::GetRealTime(), KX_KetsjiEngine::NextFrame(), KX_KetsjiEngine::Render(), KX_KetsjiEngine::RenderDome(), and KX_KetsjiEngine::StartEngine().
The documentation for this class was generated from the following file:
KX_ISystem.h