Blender: btTriangleRaycastCallback Class Reference
btTriangleRaycastCallback Class Reference
#include <btRaycastCallback.h>
Public Types
enum EFlags { kF_None = 0, kF_FilterBackfaces = 1 << 0, kF_KeepUnflippedNormal = 1 << 1, kF_Terminator = 0xFFFFFFFF }
Public Member Functions
btTriangleRaycastCallback (const btVector3 &from, const btVector3 &to, unsigned int flags=0)
virtual void processTriangle (btVector3 *triangle, int partId, int triangleIndex)
virtual btScalar reportHit (const btVector3 &hitNormalLocal, btScalar hitFraction, int partId, int triangleIndex)=0
Public Attributes
btVector3 m_from
btVector3 m_to
unsigned int m_flags
btScalar m_hitFraction
Detailed Description
Definition at line 24 of file btRaycastCallback.h.
Member Enumeration Documentation
enum btTriangleRaycastCallback::EFlags
Enumerator:
kF_None
kF_FilterBackfaces
kF_KeepUnflippedNormal
kF_Terminator
Definition at line 33 of file btRaycastCallback.h.
Constructor & Destructor Documentation
btTriangleRaycastCallback::btTriangleRaycastCallback (const btVector3 & from, const btVector3 & to, unsigned int flags = 0)
Definition at line 26 of file btRaycastCallback.cpp.
Member Function Documentation
void btTriangleRaycastCallback::processTriangle (btVector3 * triangle, int partId, int triangleIndex) [virtual]
Implements btTriangleCallback.
Definition at line 39 of file btRaycastCallback.cpp.
References distance(), kF_FilterBackfaces, kF_KeepUnflippedNormal, m_flags, m_from, m_hitFraction, m_to, and reportHit().
virtual btScalar btTriangleRaycastCallback::reportHit (const btVector3 & hitNormalLocal, btScalar hitFraction, int partId, int triangleIndex) [pure virtual]
Referenced by processTriangle().
Member Data Documentation
unsigned int btTriangleRaycastCallback::m_flags
Definition at line 41 of file btRaycastCallback.h.
Referenced by processTriangle().
btVector3 btTriangleRaycastCallback::m_from
Definition at line 29 of file btRaycastCallback.h.
Referenced by processTriangle().
btScalar btTriangleRaycastCallback::m_hitFraction
Definition at line 43 of file btRaycastCallback.h.
Referenced by processTriangle().
btVector3 btTriangleRaycastCallback::m_to
Definition at line 30 of file btRaycastCallback.h.
Referenced by processTriangle().
The documentation for this class was generated from the following files:
btRaycastCallback.h
btRaycastCallback.cpp