Blender: WM_api.h File Reference
WM_api.h File Reference
windowmanager
#include "DNA_windowmanager_types.h"
#include "WM_keymap.h"
Defines
#define WM_WINDOW_RENDER 0
#define WM_WINDOW_USERPREFS 1
#define WM_WINDOW_FILESEL 2
#define SEL_TOGGLE 0
#define SEL_SELECT 1
#define SEL_DESELECT 2
#define SEL_INVERT 3
#define WM_FILESEL_RELPATH (1 << 0)
#define WM_FILESEL_DIRECTORY (1 << 1)
#define WM_FILESEL_FILENAME (1 << 2)
#define WM_FILESEL_FILEPATH (1 << 3)
#define WM_FILESEL_FILES (1 << 4)
#define WM_JOB_PRIORITY 1
#define WM_JOB_EXCL_RENDER 2
#define WM_JOB_PROGRESS 4
#define WM_JOB_SUSPEND 8
Typedefs
typedef struct wmJob wmJob
Functions
void WM_setprefsize (int stax, int stay, int sizx, int sizy)
void WM_setinitialstate_fullscreen (void)
void WM_setinitialstate_normal (void)
void WM_init (struct bContext *C, int argc, const char **argv)
void WM_exit_ext (struct bContext *C, const short do_python)
void WM_exit (struct bContext *C)
void WM_main (struct bContext *C)
int WM_init_game (struct bContext *C)
void WM_init_splash (struct bContext *C)
void WM_check (struct bContext *C)
struct wmWindow * WM_window_open (struct bContext *C, struct rcti *rect)
void WM_window_open_temp (struct bContext *C, struct rcti *position, int type)
int WM_read_homefile_exec (struct bContext *C, struct wmOperator *op)
int WM_read_homefile (struct bContext *C, struct ReportList *reports, short from_memory)
int WM_write_homefile (struct bContext *C, struct wmOperator *op)
void WM_read_file (struct bContext *C, const char *filepath, struct ReportList *reports)
int WM_write_file (struct bContext *C, const char *target, int fileflags, struct ReportList *reports, int copy)
void WM_autosave_init (struct wmWindowManager *wm)
void WM_cursor_set (struct wmWindow *win, int curs)
void WM_cursor_modal (struct wmWindow *win, int curs)
void WM_cursor_restore (struct wmWindow *win)
void WM_cursor_wait (int val)
void WM_cursor_grab (struct wmWindow *win, int wrap, int hide, int *bounds)
void WM_cursor_ungrab (struct wmWindow *win)
void WM_timecursor (struct wmWindow *win, int nr)
void * WM_paint_cursor_activate (struct wmWindowManager *wm, int(*poll)(struct bContext *C), void(*draw)(struct bContext *C, int, int, void *customdata), void *customdata)
void WM_paint_cursor_end (struct wmWindowManager *wm, void *handle)
void WM_cursor_warp (struct wmWindow *win, int x, int y)
int WM_userdef_event_map (int kmitype)
struct wmEventHandler * WM_event_add_keymap_handler (ListBase *handlers, wmKeyMap *keymap)
struct wmEventHandler * WM_event_add_keymap_handler_bb (ListBase *handlers, wmKeyMap *keymap, rcti *bb, rcti *swinbb)
struct wmEventHandler * WM_event_add_keymap_handler_priority (ListBase *handlers, wmKeyMap *keymap, int priority)
void WM_event_remove_keymap_handler (ListBase *handlers, wmKeyMap *keymap)
struct wmEventHandler * WM_event_add_ui_handler (const struct bContext *C, ListBase *handlers, int(*func)(struct bContext *C, struct wmEvent *event, void *userdata), void(*remove)(struct bContext *C, void *userdata), void *userdata)
void WM_event_remove_ui_handler (ListBase *handlers, int(*func)(struct bContext *C, struct wmEvent *event, void *userdata), void(*remove)(struct bContext *C, void *userdata), void *userdata, int postpone)
void WM_event_remove_area_handler (struct ListBase *handlers, void *area)
struct wmEventHandler * WM_event_add_modal_handler (struct bContext *C, struct wmOperator *op)
void WM_event_remove_handlers (struct bContext *C, ListBase *handlers)
struct wmEventHandler * WM_event_add_dropbox_handler (ListBase *handlers, ListBase *dropboxes)
void WM_event_add_mousemove (struct bContext *C)
int WM_modal_tweak_exit (struct wmEvent *evt, int tweak_event)
void WM_event_add_notifier (const struct bContext *C, unsigned int type, void *reference)
void WM_main_add_notifier (unsigned int type, void *reference)
void wm_event_add (struct wmWindow *win, struct wmEvent *event_to_add)
struct wmTimer * WM_event_add_timer (struct wmWindowManager *wm, struct wmWindow *win, int event_type, double timestep)
void WM_event_remove_timer (struct wmWindowManager *wm, struct wmWindow *win, struct wmTimer *timer)
void WM_event_timer_sleep (struct wmWindowManager *wm, struct wmWindow *win, struct wmTimer *timer, int dosleep)
int WM_menu_invoke (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_enum_search_invoke (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_operator_confirm (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_operator_filesel (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_operator_filesel_ensure_ext_imtype (wmOperator *op, const char imtype)
int WM_operator_winactive (struct bContext *C)
int WM_operator_props_popup (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_operator_props_dialog_popup (struct bContext *C, struct wmOperator *op, int width, int height)
int WM_operator_redo_popup (struct bContext *C, struct wmOperator *op)
int WM_operator_ui_popup (struct bContext *C, struct wmOperator *op, int width, int height)
int WM_operator_confirm_message (struct bContext *C, struct wmOperator *op, const char *message)
void WM_operator_free (struct wmOperator *op)
void WM_operator_stack_clear (struct wmWindowManager *wm)
struct wmOperatorType * WM_operatortype_find (const char *idnamem, int quiet)
struct GHashIterator * WM_operatortype_iter (void)
void WM_operatortype_append (void(*opfunc)(struct wmOperatorType *))
void WM_operatortype_append_ptr (void(*opfunc)(struct wmOperatorType *, void *), void *userdata)
void WM_operatortype_append_macro_ptr (void(*opfunc)(struct wmOperatorType *, void *), void *userdata)
int WM_operatortype_remove (const char *idname)
struct wmOperatorType * WM_operatortype_append_macro (const char *idname, const char *name, int flag)
struct wmOperatorTypeMacro * WM_operatortype_macro_define (struct wmOperatorType *ot, const char *idname)
int WM_operator_poll (struct bContext *C, struct wmOperatorType *ot)
int WM_operator_poll_context (struct bContext *C, struct wmOperatorType *ot, int context)
int WM_operator_call (struct bContext *C, struct wmOperator *op)
int WM_operator_call_notest (struct bContext *C, struct wmOperator *op)
int WM_operator_repeat (struct bContext *C, struct wmOperator *op)
int WM_operator_repeat_check (const struct bContext *C, struct wmOperator *op)
int WM_operator_name_call (struct bContext *C, const char *opstring, int context, struct PointerRNA *properties)
int WM_operator_call_py (struct bContext *C, struct wmOperatorType *ot, int context, struct PointerRNA *properties, struct ReportList *reports)
void WM_operator_properties_alloc (struct PointerRNA **ptr, struct IDProperty **properties, const char *opstring)
void WM_operator_properties_sanitize (struct PointerRNA *ptr, const short no_context)
void WM_operator_properties_reset (struct wmOperator *op)
void WM_operator_properties_create (struct PointerRNA *ptr, const char *opstring)
void WM_operator_properties_create_ptr (struct PointerRNA *ptr, struct wmOperatorType *ot)
void WM_operator_properties_free (struct PointerRNA *ptr)
void WM_operator_properties_filesel (struct wmOperatorType *ot, int filter, short type, short action, short flag, short display)
void WM_operator_properties_gesture_border (struct wmOperatorType *ot, int extend)
void WM_operator_properties_gesture_straightline (struct wmOperatorType *ot, int cursor)
void WM_operator_properties_select_all (struct wmOperatorType *ot)
int WM_operator_check_ui_enabled (const struct bContext *C, const char *idname)
wmOperator * WM_operator_last_redo (const struct bContext *C)
int WM_operator_last_properties_init (struct wmOperator *op)
int WM_operator_last_properties_store (struct wmOperator *op)
char * WM_operator_pystring (struct bContext *C, struct wmOperatorType *ot, struct PointerRNA *opptr, int all_args)
void WM_operator_bl_idname (char *to, const char *from)
void WM_operator_py_idname (char *to, const char *from)
void WM_menutype_init (void)
struct MenuType * WM_menutype_find (const char *idname, int quiet)
int WM_menutype_add (struct MenuType *mt)
void WM_menutype_freelink (struct MenuType *mt)
void WM_menutype_free (void)
int WM_border_select_invoke (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_border_select_modal (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_border_select_cancel (struct bContext *C, struct wmOperator *op)
int WM_gesture_circle_invoke (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_gesture_circle_modal (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_gesture_circle_cancel (struct bContext *C, struct wmOperator *op)
int WM_gesture_lines_invoke (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_gesture_lines_modal (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_gesture_lines_cancel (struct bContext *C, struct wmOperator *op)
int WM_gesture_lasso_invoke (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_gesture_lasso_modal (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_gesture_lasso_cancel (struct bContext *C, struct wmOperator *op)
int WM_gesture_straightline_invoke (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_gesture_straightline_modal (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int WM_gesture_straightline_cancel (struct bContext *C, struct wmOperator *op)
struct wmGesture * WM_gesture_new (struct bContext *C, struct wmEvent *event, int type)
void WM_gesture_end (struct bContext *C, struct wmGesture *gesture)
void WM_gestures_remove (struct bContext *C)
void WM_event_add_fileselect (struct bContext *C, struct wmOperator *op)
void WM_event_fileselect_event (struct bContext *C, void *ophandle, int eventval)
void WM_event_print (struct wmEvent *event)
struct wmDrag * WM_event_start_drag (struct bContext *C, int icon, int type, void *poin, double value)
void WM_event_drag_image (struct wmDrag *, struct ImBuf *, float scale, int sx, int sy)
struct wmDropBox * WM_dropbox_add (ListBase *lb, const char *idname, int(*poll)(struct bContext *, struct wmDrag *, struct wmEvent *event), void(*copy)(struct wmDrag *, struct wmDropBox *))
ListBase * WM_dropboxmap_find (const char *idname, int spaceid, int regionid)
void wmSubWindowSet (struct wmWindow *win, int swinid)
void wmSubWindowScissorSet (struct wmWindow *win, int swinid, struct rcti *srct)
void wmFrustum (float x1, float x2, float y1, float y2, float n, float f)
void wmOrtho (float x1, float x2, float y1, float y2, float n, float f)
void wmOrtho2 (float x1, float x2, float y1, float y2)
void WM_set_framebuffer_index_color (int index)
int WM_framebuffer_to_index (unsigned int col)
struct wmJob * WM_jobs_get (struct wmWindowManager *wm, struct wmWindow *win, void *owner, const char *name, int flag)
int WM_jobs_test (struct wmWindowManager *wm, void *owner)
float WM_jobs_progress (struct wmWindowManager *wm, void *owner)
char * WM_jobs_name (struct wmWindowManager *wm, void *owner)
int WM_jobs_is_running (struct wmJob *)
void * WM_jobs_get_customdata (struct wmJob *)
void WM_jobs_customdata (struct wmJob *, void *customdata, void(*free)(void *))
void WM_jobs_timer (struct wmJob *, double timestep, unsigned int note, unsigned int endnote)
void WM_jobs_callbacks (struct wmJob *, void(*startjob)(void *, short *, short *, float *), void(*initjob)(void *), void(*update)(void *), void(*endjob)(void *))
void WM_jobs_start (struct wmWindowManager *wm, struct wmJob *)
void WM_jobs_stop (struct wmWindowManager *wm, void *owner, void *startjob)
void WM_jobs_kill (struct wmWindowManager *wm, void *owner, void(*)(void *, short int *, short int *, float *))
void WM_jobs_stop_all (struct wmWindowManager *wm)
int WM_jobs_has_running (struct wmWindowManager *wm)
char * WM_clipboard_text_get (int selection)
void WM_clipboard_text_set (char *buf, int selection)
void WM_progress_set (struct wmWindow *win, float progress)
void WM_progress_clear (struct wmWindow *win)
void WM_redraw_windows (struct bContext *C)
int write_crash_blend (void)
Detailed Description
Definition in file WM_api.h.
Define Documentation
#define SEL_DESELECT 2
Definition at line 224 of file WM_api.h.
Referenced by armature_de_select_all_exec(), border_select_exec(), de_select_all_exec(), do_lasso_select_paintface(), do_lasso_select_paintvert(), do_paintface_box_select(), do_paintvert_box_select(), ed_marker_select_all_exec(), edbm_select_all_exec(), graph_select_all_markers_exec(), lattice_select_all_exec(), mball_select_all_exec(), mouse_select(), mouse_select_curve(), mouse_select_knot(), mouse_weight_paint_vertex_select(), object_select_all_exec(), paintface_deselect_all_visible(), paintvert_deselect_all_visible(), pe_select_all_exec(), pose_de_select_all_exec(), select_all_exec(), select_all_perform(), select_edgeloop(), sequencer_de_select_all_exec(), toggle_selection_cb(), vgroup_lock_all(), and WM_operator_properties_select_all().
#define SEL_INVERT 3
Definition at line 225 of file WM_api.h.
Referenced by armature_de_select_all_exec(), clip_keymap(), de_select_all_exec(), ED_keymap_armature(), ED_keymap_curve(), ED_keymap_mesh(), ED_keymap_metaball(), ED_keymap_object(), ED_keymap_uvedit(), ed_marker_select_all_exec(), edbm_select_all_exec(), face_select_inverse_exec(), graph_select_all_markers_exec(), keymap_particle(), lattice_select_all_exec(), mball_select_all_exec(), object_select_all_exec(), paintface_deselect_all_visible(), paintvert_deselect_all_visible(), pe_select_all_exec(), pose_de_select_all_exec(), select_all_exec(), select_all_perform(), sequencer_de_select_all_exec(), sequencer_keymap(), toggle_selection_cb(), vert_select_inverse_exec(), vgroup_lock_all(), and WM_operator_properties_select_all().
#define SEL_SELECT 1
Definition at line 223 of file WM_api.h.
Referenced by armature_de_select_all_exec(), de_select_all_exec(), ed_marker_select_all_exec(), edbm_select_all_exec(), graph_select_all_markers_exec(), lattice_select_all_exec(), mball_select_all_exec(), object_select_all_exec(), paintface_deselect_all_visible(), paintvert_deselect_all_visible(), pe_select_all_exec(), pose_de_select_all_exec(), select_all_exec(), select_all_perform(), sequencer_de_select_all_exec(), toggle_selection_cb(), vgroup_lock_all(), and WM_operator_properties_select_all().
#define SEL_TOGGLE 0
Definition at line 222 of file WM_api.h.
Referenced by armature_de_select_all_exec(), clip_keymap(), de_select_all_exec(), ED_keymap_armature(), ED_keymap_curve(), ED_keymap_mesh(), ED_keymap_metaball(), ED_keymap_object(), ED_keymap_uvedit(), ed_marker_select_all_exec(), edbm_select_all_exec(), graph_select_all_markers_exec(), keymap_particle(), lattice_select_all_exec(), mball_select_all_exec(), object_select_all_exec(), paintface_deselect_all_visible(), paintvert_deselect_all_visible(), pe_select_all_exec(), pose_de_select_all_exec(), select_all_exec(), select_all_perform(), sequencer_de_select_all_exec(), sequencer_keymap(), vgroup_lock_all(), and WM_operator_properties_select_all().
#define WM_FILESEL_DIRECTORY (1 << 1)
Definition at line 231 of file WM_api.h.
Referenced by BUTTONS_OT_directory_browse(), SEQUENCER_OT_change_path(), SEQUENCER_OT_image_strip_add(), WM_operator_properties_filesel(), and WM_OT_link_append().
#define WM_FILESEL_FILENAME (1 << 2)
Definition at line 232 of file WM_api.h.
Referenced by WM_operator_properties_filesel(), and WM_OT_link_append().
#define WM_FILESEL_FILEPATH (1 << 3)
Definition at line 233 of file WM_api.h.
Referenced by BUTTONS_OT_file_browse(), CLIP_OT_open(), FILE_OT_find_missing_files(), FONT_OT_file_paste(), FONT_OT_open(), GRAPH_OT_sound_bake(), IMAGE_OT_open(), IMAGE_OT_replace(), IMAGE_OT_save_as(), NODE_OT_add_file(), OBJECT_OT_multires_external_save(), SCREEN_OT_screenshot(), SEQUENCER_OT_change_path(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_sound_strip_add(), SOUND_OT_mixdown(), SOUND_OT_open(), SOUND_OT_open_mono(), TEXT_OT_open(), TEXT_OT_save_as(), TEXTURE_OT_envmap_save(), WM_operator_properties_filesel(), WM_OT_link_append(), WM_OT_open_mainfile(), WM_OT_recover_auto_save(), WM_OT_save_as_mainfile(), and WM_OT_save_mainfile().
#define WM_FILESEL_FILES (1 << 4)
Definition at line 234 of file WM_api.h.
Referenced by SEQUENCER_OT_change_path(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_sound_strip_add(), WM_operator_properties_filesel(), and WM_OT_link_append().
#define WM_FILESEL_RELPATH (1 << 0)
Definition at line 229 of file WM_api.h.
Referenced by BUTTONS_OT_directory_browse(), BUTTONS_OT_file_browse(), CLIP_OT_open(), FONT_OT_open(), IMAGE_OT_open(), IMAGE_OT_replace(), IMAGE_OT_save_as(), OBJECT_OT_multires_external_save(), SEQUENCER_OT_change_path(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_sound_strip_add(), SOUND_OT_open(), SOUND_OT_open_mono(), WM_operator_properties_filesel(), and WM_OT_link_append().
#define WM_JOB_EXCL_RENDER 2
Definition at line 301 of file WM_api.h.
Referenced by ED_preview_icon_job(), ED_preview_shader_job(), multiresbake_image_exec(), objects_bake_render_invoke(), screen_render_invoke(), snode_composite_job(), and wm_jobs_test_suspend_stop().
#define WM_JOB_PRIORITY 1
Definition at line 300 of file WM_api.h.
Referenced by multiresbake_image_exec(), objects_bake_render_invoke(), screen_render_invoke(), and wm_jobs_test_suspend_stop().
#define WM_JOB_PROGRESS 4
Definition at line 302 of file WM_api.h.
Referenced by clip_rebuild_proxy_exec(), multiresbake_image_exec(), objects_bake_render_invoke(), ocean_bake_exec(), screen_render_invoke(), seq_proxy_build_job(), snode_composite_job(), solve_camera_invoke(), track_markers_invoke(), WM_jobs_progress(), and wm_jobs_timer().
#define WM_JOB_SUSPEND 8
Definition at line 303 of file WM_api.h.
Referenced by ED_preview_icon_job(), screen_render_invoke(), and wm_jobs_test_suspend_stop().
#define WM_WINDOW_FILESEL 2
Definition at line 88 of file WM_api.h.
#define WM_WINDOW_RENDER 0
Definition at line 86 of file WM_api.h.
Referenced by render_view_open(), and WM_window_open_temp().
#define WM_WINDOW_USERPREFS 1
Definition at line 87 of file WM_api.h.
Referenced by userpref_show_invoke().
Typedef Documentation
typedef struct wmJob wmJob
Definition at line 65 of file WM_api.h.
Function Documentation
void WM_autosave_init (struct wmWindowManager * wm)
Definition at line 916 of file wm_files.c.
References wmWindowManager::autosavetimer, NULL, TIMERAUTOSAVE, USER_AUTOSAVE, wm_autosave_timer_ended(), and WM_event_add_timer().
Referenced by WM_check().
int WM_border_select_cancel (struct bContext * C, struct wmOperator * op)
Definition at line 2433 of file wm_operators.c.
References OPERATOR_CANCELLED, and wm_gesture_end().
Referenced by ACTION_OT_select_border(), ANIM_OT_channels_select_border(), ANIM_OT_previewrange_set(), FILE_OT_select_border(), GRAPH_OT_select_border(), INFO_OT_select_border(), MARKER_OT_select_border(), NLA_OT_select_border(), NODE_OT_select_border(), OUTLINER_OT_select_border(), SEQUENCER_OT_select_border(), SEQUENCER_OT_view_ghost_border(), UV_OT_select_border(), VIEW2D_OT_zoom_border(), VIEW3D_OT_clip_border(), VIEW3D_OT_render_border(), VIEW3D_OT_select_border(), and VIEW3D_OT_zoom_border().
int WM_border_select_invoke (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
Definition at line 2363 of file wm_operators.c.
References wmOperator::customdata, ISTWEAK, OPERATOR_RUNNING_MODAL, wmEvent::type, WM_event_add_modal_handler(), WM_GESTURE_CROSS_RECT, WM_gesture_new(), WM_GESTURE_RECT, and wm_gesture_tag_redraw().
Referenced by ACTION_OT_select_border(), ANIM_OT_channels_select_border(), ANIM_OT_previewrange_set(), CLIP_OT_graph_select_border(), CLIP_OT_select_border(), ed_marker_select_border_invoke_wrapper(), FILE_OT_select_border(), GRAPH_OT_select_border(), hide_show_invoke(), INFO_OT_select_border(), NLA_OT_select_border(), node_border_select_invoke(), OUTLINER_OT_select_border(), SEQUENCER_OT_select_border(), SEQUENCER_OT_view_ghost_border(), UV_OT_select_border(), VIEW2D_OT_zoom_border(), view3d_clipping_invoke(), VIEW3D_OT_render_border(), VIEW3D_OT_select_border(), and view3d_zoom_border_invoke().
int WM_border_select_modal (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
Definition at line 2378 of file wm_operators.c.
References border_apply(), border_apply_rect(), CTX_wm_window(), wmGesture::customdata, wmOperator::customdata, EVT_MODAL_MAP, GESTURE_MODAL_BEGIN, GESTURE_MODAL_CANCEL, GESTURE_MODAL_DESELECT, GESTURE_MODAL_IN, GESTURE_MODAL_OUT, GESTURE_MODAL_SELECT, wmGesture::mode, MOUSEMOVE, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmGesture::swinid, wmGesture::type, wmEvent::type, wmEvent::val, WM_GESTURE_CROSS_RECT, wm_gesture_end(), wm_gesture_tag_redraw(), wm_subwindow_getorigin(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ACTION_OT_select_border(), ANIM_OT_channels_select_border(), ANIM_OT_previewrange_set(), CLIP_OT_graph_select_border(), CLIP_OT_select_border(), file_border_select_modal(), GRAPH_OT_select_border(), INFO_OT_select_border(), MARKER_OT_select_border(), NLA_OT_select_border(), NODE_OT_select_border(), OUTLINER_OT_select_border(), PAINT_OT_hide_show(), SEQUENCER_OT_select_border(), SEQUENCER_OT_view_ghost_border(), UV_OT_select_border(), VIEW2D_OT_zoom_border(), VIEW3D_OT_clip_border(), VIEW3D_OT_render_border(), VIEW3D_OT_select_border(), and VIEW3D_OT_zoom_border().
void WM_check (struct bContext * C)
Definition at line 238 of file wm.c.
References CTX_data_main(), CTX_wm_manager(), CTX_wm_manager_set(), ED_screens_initialize(), ListBase::first, G, wmWindowManager::initialized, NULL, wmWindowManager::windows, Main::wm, WM_autosave_init(), WM_INIT_WINDOW, WM_keymap_init(), and wm_window_add_ghostwindows().
Referenced by load_file(), WM_read_file(), WM_read_homefile(), wm_window_duplicate_exec(), WM_window_open(), and WM_window_open_temp().
char* WM_clipboard_text_get (int selection)
Definition at line 1055 of file wm_window.c.
References G, GHOST_getClipboard(), MEM_callocN(), NULL, p, and strlen().
Referenced by console_paste_exec(), text_paste_exec(), ui_but_copy_paste(), and ui_textedit_copypaste().
void WM_clipboard_text_set (char * buf, int selection)
Definition at line 1080 of file wm_window.c.
References G, GHOST_putClipboard(), MEM_callocN(), MEM_freeN(), and p.
Referenced by console_copy_exec(), console_cursor_set_exit(), copy_data_path_button_exec(), report_copy_exec(), text_cursor_set_exit(), txt_copy_clipboard(), ui_but_copy_paste(), and ui_textedit_copypaste().
void WM_cursor_grab (struct wmWindow * win, int wrap, int hide, int * bounds)
Definition at line 182 of file wm_cursors.c.
References GHOST_TabletData::Active, G, G_DEBUG, GHOST_GetTabletData(), GHOST_kGrabHide, GHOST_kGrabNormal, GHOST_kGrabWrap, GHOST_kTabletModeNone, GHOST_SetCursorGrab(), wmWindow::ghostwin, and wmWindow::grabcursor.
Referenced by button_activate_state(), wm_macro_modal(), and wm_operator_invoke().
void WM_cursor_modal (struct wmWindow * win, int curs)
Definition at line 148 of file wm_cursors.c.
References wmWindow::cursor, wmWindow::lastcursor, wmWindow::modalcursor, and WM_cursor_set().
Referenced by area_swap_invoke(), eyedropper_invoke(), gpencil_draw_invoke(), image_view_pan_init(), image_view_zoom_init(), knifetool_invoke(), pose_slide_invoke_common(), ui_textedit_begin(), view_pan_init(), view_pan_invoke(), view_zoom_init(), view_zoomdrag_invoke(), WM_cursor_wait(), WM_gesture_lasso_invoke(), WM_gesture_lines_invoke(), and WM_gesture_straightline_invoke().
void WM_cursor_restore (struct wmWindow * win)
Definition at line 156 of file wm_cursors.c.
References wmWindow::lastcursor, wmWindow::modalcursor, and WM_cursor_set().
Referenced by area_split_exit(), area_swap_exit(), dynamicPaint_initBake(), eyedropper_exit(), gpencil_draw_exit(), image_record_composite_exit(), image_view_pan_exit(), image_view_zoom_exit(), knifetool_exit(), pose_slide_modal(), ptcache_bake_all_exec(), ptcache_bake_exec(), ui_textedit_end(), view_pan_exit(), view_pan_modal(), view_zoom_exit(), view_zoomdrag_modal(), WM_cursor_wait(), and wm_gesture_end().
void WM_cursor_set (struct wmWindow * win, int curs)
Definition at line 105 of file wm_cursors.c.
References BC_CROSSCURSOR, BC_GHOST_CURSORS, BC_NUMCURSORS, BCursor::big_bm, convert_cursor(), wmWindow::cursor, CURSOR_EDIT, CURSOR_NONE, CURSOR_STD, GHOST_SetCursorShape(), GHOST_SetCursorVisibility(), wmWindow::ghostwin, wmWindow::modalcursor, NULL, SYSCURSOR, and window_set_custom_cursor_ex().
Referenced by area_split_modal(), BL_HideMouse(), BL_NormalMouse(), BL_WaitMouse(), hide_cursor(), region_cursor_set(), screen_cursor_set(), show_cursor(), text_cursor(), view3d_main_area_cursor(), WM_cursor_modal(), and WM_cursor_restore().
void WM_cursor_ungrab (struct wmWindow * win)
Definition at line 205 of file wm_cursors.c.
References G, G_DEBUG, GHOST_kGrabDisable, GHOST_SetCursorGrab(), wmWindow::ghostwin, wmWindow::grabcursor, and NULL.
Referenced by button_activate_state(), WM_event_remove_handlers(), and wm_handler_operator_call().
void WM_cursor_wait (int val)
Definition at line 165 of file wm_cursors.c.
References BC_WAITCURSOR, ListBase::first, G, wmWindow::next, NULL, wmJob::win, wmWindowManager::windows, WM_cursor_modal(), and WM_cursor_restore().
Referenced by BKE_ptcache_bake(), ED_object_parent_set(), edbm_duplicate_invoke(), envmap_save_exec(), multiresbake_image_exec(), node_read_fullsamplelayers_exec(), objects_bake_render_invoke(), redraw_timer_exec(), save_image_doit(), screen_opengl_render_end(), screen_opengl_render_init(), screen_render_invoke(), script_reload_exec(), separate_armature_exec(), separate_exec(), solve_camera_invoke(), touch_seq_files(), track_markers_invoke(), WM_read_file(), and WM_write_file().
void WM_cursor_warp (struct wmWindow * win, int x, int y)
Definition at line 1211 of file wm_window.c.
References wmWindow::eventstate, g_system, GHOST_ClientToScreen(), GHOST_SetCursorPosition(), wmWindow::ghostwin, wmEvent::prevx, wmEvent::prevy, and wmWindow::sizey.
Referenced by BL_warp_pointer(), initFlyInfo(), and wm_cursor_arrow_move().
struct wmDropBox* WM_dropbox_add (ListBase * lb, const char * idname, int(*)(struct bContext *, struct wmDrag *, struct wmEvent *event) poll, void(*)(struct wmDrag *, struct wmDropBox *) copy) [read]
ListBase* WM_dropboxmap_find (const char * idname, int spaceid, int regionid)
Definition at line 86 of file wm_dragdrop.c.
References BLI_addtail(), BLI_strncpy(), wmDropBoxMap::dropboxes, ListBase::first, wmDropBoxMap::idname, KMAP_MAX_NAME, MEM_callocN(), wmDropBoxMap::next, wmDropBoxMap::regionid, and wmDropBoxMap::spaceid.
Referenced by console_dropboxes(), console_main_area_init(), ED_keymap_screen(), image_dropboxes(), image_init(), node_dropboxes(), node_main_area_init(), outliner_dropboxes(), outliner_main_area_init(), sequencer_dropboxes(), sequencer_main_area_init(), text_dropboxes(), text_main_area_init(), view3d_dropboxes(), view3d_main_area_init(), and wm_window_add_ghostwindows().
int WM_enum_search_invoke (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
void wm_event_add (struct wmWindow * win, struct wmEvent * event_to_add)
Definition at line 90 of file wm_event_system.c.
References BLI_addtail(), MEM_callocN(), and wmWindow::queue.
Referenced by actionzone_apply(), ghost_event_proc(), operator_search_menu(), tool_search_menu(), tweak_gesture_modal(), uiButSetFocusOnEnter(), wm_block_search_menu(), wm_enum_search_menu(), wm_event_add_ghostevent(), wm_event_do_handlers(), WM_event_fileselect_event(), and wm_window_timer().
struct wmEventHandler* WM_event_add_dropbox_handler (ListBase * handlers, ListBase * dropboxes) [read]
Definition at line 2352 of file wm_event_system.c.
References BLI_addhead(), dropboxes, wmEventHandler::dropboxes, ListBase::first, MEM_callocN(), and wmEventHandler::next.
Referenced by console_main_area_init(), image_init(), node_main_area_init(), outliner_main_area_init(), sequencer_main_area_init(), text_main_area_init(), view3d_main_area_init(), and wm_window_add_ghostwindows().
void WM_event_add_fileselect (struct bContext * C, struct wmOperator * op)
Definition at line 2188 of file wm_event_system.c.
References BLI_addhead(), BLI_remlink(), wmOperatorType::check, CTX_wm_area(), CTX_wm_region(), CTX_wm_screen(), CTX_wm_window(), EVT_FILESELECT_FULL_OPEN, EVT_FILESELECT_OPEN, wmEventHandler::filescreen, ListBase::first, MEM_callocN(), wmWindow::modalhandlers, wmEventHandler::next, wmEventHandler::op, wmEventHandler::op_area, wmEventHandler::op_region, wmOperator::type, wmEventHandler::type, WM_event_fileselect_event(), wm_event_free_handler(), WM_HANDLER_FILESELECT, and WM_operator_free().
Referenced by clip_filesel(), envmap_save_invoke(), file_browse_invoke(), find_missing_files_invoke(), image_filesel(), multires_external_save_invoke(), open_invoke(), paste_file_invoke(), screenshot_invoke(), sequencer_add_effect_strip_invoke(), sequencer_add_image_strip_invoke(), sequencer_add_movie_strip_invoke(), sequencer_add_sound_strip_invoke(), sequencer_change_path_invoke(), text_open_invoke(), text_save_as_invoke(), wm_link_append_invoke(), wm_open_mainfile_invoke(), WM_operator_filesel(), wm_recover_auto_save_invoke(), wm_save_as_mainfile_invoke(), and wm_save_mainfile_invoke().
struct wmEventHandler* WM_event_add_keymap_handler (ListBase * handlers, wmKeyMap * keymap) [read]
Definition at line 2256 of file wm_event_system.c.
References BLI_addtail(), ListBase::first, wmEventHandler::keymap, MEM_callocN(), wmEventHandler::next, and NULL.
Referenced by buttons_main_area_init(), clip_properties_area_init(), ed_default_handlers(), ED_region_panels_init(), graph_channel_area_init(), graph_main_area_init(), image_buttons_area_init(), image_main_area_init(), image_scope_area_init(), info_main_area_init(), logic_buttons_area_init(), logic_main_area_init(), nla_main_area_init(), node_buttons_area_init(), node_main_area_init(), view3d_buttons_area_init(), view3d_header_area_init(), view3d_main_area_init(), view3d_tools_area_init(), WM_event_add_keymap_handler_bb(), and wm_window_add_ghostwindows().
struct wmEventHandler* WM_event_add_keymap_handler_bb (ListBase * handlers, wmKeyMap * keymap, rcti * bb, rcti * swinbb) [read]
Definition at line 2291 of file wm_event_system.c.
References wmEventHandler::bblocal, wmEventHandler::bbwin, and WM_event_add_keymap_handler().
Referenced by action_channel_area_init(), action_main_area_init(), clip_main_area_init(), clip_preview_area_init(), console_main_area_init(), ed_default_handlers(), file_channel_area_init(), file_header_area_init(), file_main_area_init(), file_ui_area_init(), graph_buttons_area_init(), graph_channel_area_init(), graph_main_area_init(), image_main_area_init(), nla_buttons_area_init(), nla_channel_area_init(), nla_main_area_init(), node_main_area_init(), outliner_main_area_init(), script_main_area_init(), sequencer_main_area_init(), sequencer_preview_area_init(), text_main_area_init(), and time_main_area_init().
struct wmEventHandler* WM_event_add_keymap_handler_priority (ListBase * handlers, wmKeyMap * keymap, int priority) [read]
struct wmEventHandler* WM_event_add_modal_handler (struct bContext * C, struct wmOperator * op) [read]
Definition at line 2233 of file wm_event_system.c.
References BLI_addhead(), CTX_wm_area(), CTX_wm_region(), CTX_wm_window(), MEM_callocN(), wmWindow::modalhandlers, wmEventHandler::op, wmEventHandler::op_area, wmEventHandler::op_region, and wmOperator::opm.
Referenced by actionzone_invoke(), area_join_invoke(), area_move_invoke(), area_split_invoke(), area_swap_invoke(), brush_edit_invoke(), change_frame_invoke(), console_modal_select_invoke(), ed_marker_move_invoke(), eyedropper_invoke(), fly_invoke(), gpencil_draw_invoke(), grab_clone_invoke(), graphview_cursor_invoke(), image_record_composite_invoke(), image_sample_invoke(), image_view_pan_init(), image_view_zoom_init(), knifetool_invoke(), minimize_stretch_invoke(), multiresbake_image_exec(), node_link_invoke(), node_resize_invoke(), objects_bake_render_invoke(), paint_invoke(), pose_slide_invoke_common(), poselib_preview_invoke(), radial_control_invoke(), region_scale_invoke(), ringcut_invoke(), sample_color_invoke(), sample_invoke(), screen_opengl_render_invoke(), screen_render_invoke(), scroller_activate_invoke(), sculpt_brush_stroke_invoke(), sketch_draw_gesture(), sketch_draw_stroke(), slide_marker_invoke(), snode_bg_viewmove_invoke(), solve_camera_invoke(), stitch_invoke(), text_scroll_bar_invoke(), text_scroll_invoke(), text_set_selection_invoke(), track_markers_invoke(), transform_invoke(), uv_sculpt_stroke_invoke(), view_pan_init(), view_pan_invoke(), view_zoom_init(), view_zoomdrag_invoke(), viewdolly_invoke(), viewmove_invoke(), viewrotate_invoke(), viewzoom_invoke(), vpaint_invoke(), vtx_slide_init(), WM_border_select_invoke(), WM_gesture_circle_invoke(), WM_gesture_lasso_invoke(), WM_gesture_lines_invoke(), WM_gesture_straightline_invoke(), and wpaint_invoke().
void WM_event_add_mousemove (struct bContext * C)
Definition at line 2394 of file wm_event_system.c.
References wmWindow::addmousemove, and CTX_wm_window().
Referenced by button_activate_exit(), ED_area_newspace(), ED_area_swapspace(), ED_screen_set(), file_select_invoke(), ui_popup_menu_create(), uiPupBlockEx(), uiPupBlockO(), and uiPupMenuEnd().
void WM_event_add_notifier (const struct bContext * C, unsigned int type, void * reference)
struct wmTimer* WM_event_add_timer (struct wmWindowManager * wm, struct wmWindow * win, int event_type, double timestep) [read]
Definition at line 1018 of file wm_window.c.
References BLI_addtail(), wmTimer::event_type, wmTimer::ltime, MEM_callocN(), wmTimer::ntime, PIL_check_seconds_timer(), wmTimer::stime, wmWindowManager::timers, wmTimer::timestep, and wmTimer::win.
Referenced by button_activate_state(), button_tooltip_timer_reset(), ED_screen_animation_timer(), file_directory_new_exec(), image_record_composite_invoke(), initFlyInfo(), minimize_stretch_invoke(), paint_invoke(), paint_stroke_modal(), panel_activate_state(), screen_opengl_render_invoke(), smooth_view(), ui_handle_menu_event(), uv_sculpt_stroke_invoke(), view_zoomdrag_invoke(), viewzoom_invoke(), WM_autosave_init(), wm_autosave_timer(), WM_init_game(), WM_jobs_start(), and wm_operator_reports().
struct wmEventHandler* WM_event_add_ui_handler (const struct bContext * C, ListBase * handlers, int(*)(struct bContext *C, struct wmEvent *event, void *userdata) func, void(*)(struct bContext *C, void *userdata) remove, void * userdata) [read]
void WM_event_drag_image (struct wmDrag * , struct ImBuf * , float scale, int sx, int sy)
Definition at line 170 of file wm_dragdrop.c.
References wmDrag::imb, wmDrag::scale, wmDrag::sx, and wmDrag::sy.
Referenced by ui_but_start_drag().
void WM_event_fileselect_event (struct bContext * C, void * ophandle, int eventval)
Definition at line 2164 of file wm_event_system.c.
References CTX_wm_manager(), wmWindow::eventstate, EVT_FILESELECT, wmWindow::next, wmEvent::type, and wm_event_add().
Referenced by ED_fileselect_exit(), file_cancel_exec(), file_exec(), and WM_event_add_fileselect().
void WM_event_print (struct wmEvent * event)
Definition at line 436 of file wm_event_system.c.
References wmEvent::alt, wmEvent::ascii, BLI_str_utf8_size(), wmEvent::ctrl, event_type_items, event_value_items, wmEvent::keymap_idname, wmEvent::keymodifier, wmEvent::oskey, RNA_enum_identifier(), wmEvent::shift, wmEvent::type, wmEvent::utf8_buf, wmEvent::val, wmEvent::x, and wmEvent::y.
void WM_event_remove_area_handler (struct ListBase * handlers, void * area)
Definition at line 2371 of file wm_event_system.c.
References BLI_remlink(), ListBase::first, wmEventHandler::next, wmEventHandler::type, wmEventHandler::ui_area, wm_event_free_handler(), and WM_HANDLER_FILESELECT.
Referenced by ED_screen_set().
void WM_event_remove_handlers (struct bContext * C, ListBase * handlers)
Definition at line 1169 of file wm_event_system.c.
References BLI_remlink(), wmOperatorType::cancel, CTX_wm_area(), CTX_wm_area_set(), CTX_wm_manager(), CTX_wm_menu(), CTX_wm_menu_set(), CTX_wm_region(), CTX_wm_region_set(), CTX_wm_window(), ListBase::first, wmOperatorType::flag, wmEventHandler::op, wmWindowManager::op_undo_depth, OPTYPE_UNDO, wmOperator::type, wmEventHandler::ui_area, wmEventHandler::ui_menu, wmEventHandler::ui_region, wmEventHandler::ui_remove, wmEventHandler::ui_userdata, WM_cursor_ungrab(), wm_event_free_handler(), wm_handler_op_context(), and WM_operator_free().
Referenced by clip_refresh(), ED_area_exit(), ED_region_exit(), ED_region_toggle_hidden(), sequencer_refresh(), WM_exit_ext(), wm_window_close(), wm_window_free(), and wm_window_match_init().
void WM_event_remove_keymap_handler (ListBase * handlers, wmKeyMap * keymap)
Definition at line 2302 of file wm_event_system.c.
References BLI_remlink(), ListBase::first, wmEventHandler::keymap, wmEventHandler::next, and wm_event_free_handler().
Referenced by WM_event_add_keymap_handler_priority().
void WM_event_remove_timer (struct wmWindowManager * wm, struct wmWindow * win, struct wmTimer * timer)
void WM_event_remove_ui_handler (ListBase * handlers, int(*)(struct bContext *C, struct wmEvent *event, void *userdata) func, void(*)(struct bContext *C, void *userdata) remove, void * userdata, int postpone)
Definition at line 2332 of file wm_event_system.c.
References BLI_remlink(), ListBase::first, wmEventHandler::flag, wmEventHandler::next, wmEventHandler::ui_handle, wmEventHandler::ui_remove, wmEventHandler::ui_userdata, wm_event_free_handler(), and WM_HANDLER_DO_FREE.
Referenced by button_activate_state(), panel_activate_state(), UI_add_region_handlers(), and UI_remove_popup_handlers().
struct wmDrag* WM_event_start_drag (struct bContext * C, int icon, int type, void * poin, double value) [read]
Definition at line 150 of file wm_dragdrop.c.
References BLI_addtail(), BLI_strncpy(), CTX_wm_manager(), wmWindowManager::drags, FILE_MAX, wmDrag::icon, MEM_callocN(), wmDrag::path, wmDrag::poin, wmDrag::type, wmDrag::value, and WM_DRAG_PATH.
Referenced by ghost_event_proc(), and ui_but_start_drag().
void WM_event_timer_sleep (struct wmWindowManager * wm, struct wmWindow * win, struct wmTimer * timer, int dosleep)
void WM_exit (struct bContext * C)
Definition at line 456 of file wm_init_exit.c.
References G, and WM_exit_ext().
Referenced by ghost_event_proc(), main(), wm_exit_blender_op(), and wm_window_close().
void WM_exit_ext (struct bContext * C, const short do_python)
Definition at line 328 of file wm_init_exit.c.
References ANIM_keyingset_infos_exit(), BIF_freeTemplates(), BKE_freecubetable(), BKE_reset_undo(), BKE_tracking_free_clipboard(), BKE_undo_save_quit(), BKE_userdef_free(), BLF_exit(), BPY_python_end(), CTX_free(), CTX_wm_manager(), CTX_wm_window_set(), ED_editors_exit(), ED_file_exit(), ED_preview_free_dbase(), ED_screen_exit(), free_anim_copybuf(), free_anim_drivers_copybuf(), free_blender(), free_fmodifiers_copybuf(), free_openrecent(), free_posebuf(), free_ttfont(), G, G_DEBUG, GHOST_DisposeSystemPaths(), GPU_extensions_exit(), GPU_free_unused_buffers(), GPU_global_buffer_pool_free(), wmWindow::handlers, MEM_get_memory_blocks_in_use(), MEM_printmemlist(), wmWindow::modalhandlers, wmWindow::next, RE_engines_exit(), RE_FreeAllRender(), RNA_exit(), wmWindow::screen, seq_free_clipboard(), sound_exit(), SYS_DeleteSystem(), SYS_GetSystem(), UI_exit(), wm_autosave_delete(), wm_dropbox_free(), WM_event_remove_handlers(), wm_free_reports(), wm_ghost_exit(), WM_jobs_stop_all(), WM_menutype_free(), and wm_operatortype_free().
Referenced by bpy_atexit(), and WM_exit().
int WM_framebuffer_to_index (unsigned int col)
Definition at line 386 of file wm_subwindow.c.
References GPU_color_depth().
Referenced by do_paintface_box_select(), do_paintvert_box_select(), sample_backbuf_area(), view3d_read_backbuf(), and view3d_sample_backbuf().
int WM_gesture_circle_cancel (struct bContext * C, struct wmOperator * op)
Definition at line 2535 of file wm_operators.c.
References OPERATOR_CANCELLED, and wm_gesture_end().
Referenced by UV_OT_circle_select(), and VIEW3D_OT_select_circle().
int WM_gesture_circle_invoke (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
Definition at line 2447 of file wm_operators.c.
References wmOperator::customdata, OPERATOR_RUNNING_MODAL, WM_event_add_modal_handler(), WM_GESTURE_CIRCLE, WM_gesture_new(), and wm_gesture_tag_redraw().
Referenced by CLIP_OT_select_circle(), UV_OT_circle_select(), and VIEW3D_OT_select_circle().
int WM_gesture_circle_modal (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
Definition at line 2479 of file wm_operators.c.
References CTX_wm_window(), wmGesture::customdata, wmOperator::customdata, EVT_MODAL_MAP, gesture_circle_apply(), GESTURE_MODAL_CANCEL, GESTURE_MODAL_CIRCLE_ADD, GESTURE_MODAL_CIRCLE_SUB, GESTURE_MODAL_CONFIRM, GESTURE_MODAL_DESELECT, GESTURE_MODAL_NOP, GESTURE_MODAL_SELECT, wmGesture::mode, MOUSEMOVE, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_int_set(), RNA_struct_find_property(), wmGesture::swinid, wmEvent::type, wmEvent::val, wm_gesture_end(), wm_gesture_tag_redraw(), wm_subwindow_getorigin(), rcti::xmax, rcti::xmin, and rcti::ymin.
Referenced by CLIP_OT_select_circle(), UV_OT_circle_select(), and VIEW3D_OT_select_circle().
void WM_gesture_end (struct bContext * C, struct wmGesture * gesture)
Definition at line 108 of file wm_gesture.c.
References BLI_remlink(), CTX_wm_window(), wmGesture::customdata, wmWindow::gesture, MEM_freeN(), NULL, and wmWindow::tweak.
Referenced by tweak_gesture_modal(), wm_gesture_end(), WM_gestures_remove(), and wm_tweakevent_test().
int WM_gesture_lasso_cancel (struct bContext * C, struct wmOperator * op)
Definition at line 2758 of file wm_operators.c.
References OPERATOR_CANCELLED, and wm_gesture_end().
Referenced by VIEW3D_OT_select_lasso().
int WM_gesture_lasso_invoke (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
Definition at line 2642 of file wm_operators.c.
References CTX_wm_window(), wmOperator::customdata, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_int_get(), RNA_struct_find_property(), WM_cursor_modal(), WM_event_add_modal_handler(), WM_GESTURE_LASSO, WM_gesture_new(), and wm_gesture_tag_redraw().
Referenced by VIEW3D_OT_select_lasso().
int WM_gesture_lasso_modal (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
Definition at line 2697 of file wm_operators.c.
References CTX_wm_window(), wmGesture::customdata, wmOperator::customdata, ESCKEY, gesture_lasso_apply(), INBETWEEN_MOUSEMOVE, KM_RELEASE, LEFTMOUSE, MEM_callocN(), MEM_freeN(), MIDDLEMOUSE, MOUSEMOVE, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmGesture::points, RIGHTMOUSE, wmGesture::size, wmGesture::swinid, wmEvent::type, wmEvent::val, wm_gesture_end(), wm_gesture_tag_redraw(), WM_LASSO_MIN_POINTS, and wm_subwindow_getorigin().
Referenced by VIEW3D_OT_select_lasso(), and WM_gesture_lines_modal().
int WM_gesture_lines_cancel (struct bContext * C, struct wmOperator * op)
Definition at line 2765 of file wm_operators.c.
References OPERATOR_CANCELLED, and wm_gesture_end().
Referenced by LOGIC_OT_links_cut(), and NODE_OT_links_cut().
int WM_gesture_lines_invoke (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
Definition at line 2657 of file wm_operators.c.
References CTX_wm_window(), wmOperator::customdata, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_int_get(), RNA_struct_find_property(), WM_cursor_modal(), WM_event_add_modal_handler(), WM_GESTURE_LINES, WM_gesture_new(), and wm_gesture_tag_redraw().
Referenced by LOGIC_OT_links_cut(), MESH_OT_knife_cut(), and NODE_OT_links_cut().
int WM_gesture_lines_modal (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
Definition at line 2753 of file wm_operators.c.
References WM_gesture_lasso_modal().
Referenced by LOGIC_OT_links_cut(), MESH_OT_knife_cut(), and NODE_OT_links_cut().
struct wmGesture* WM_gesture_new (struct bContext * C, struct wmEvent * event, int type) [read]
Definition at line 61 of file wm_gesture.c.
References BLI_addtail(), circle_select_size, CTX_wm_region(), CTX_wm_window(), wmGesture::customdata, ELEM, ELEM5, wmGesture::event_type, wmWindow::gesture, MEM_callocN(), wmGesture::points, wmGesture::size, ARegion::swinid, wmGesture::swinid, wmGesture::type, WM_GESTURE_CIRCLE, WM_GESTURE_CROSS_RECT, WM_GESTURE_LASSO, WM_GESTURE_LINES, WM_GESTURE_RECT, WM_GESTURE_STRAIGHTLINE, WM_GESTURE_TWEAK, WM_LASSO_MIN_POINTS, wm_subwindow_getorigin(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by WM_border_select_invoke(), WM_gesture_circle_invoke(), WM_gesture_lasso_invoke(), WM_gesture_lines_invoke(), WM_gesture_straightline_invoke(), and wm_tweakevent_test().
int WM_gesture_straightline_cancel (struct bContext * C, struct wmOperator * op)
Definition at line 2894 of file wm_operators.c.
References OPERATOR_CANCELLED, and wm_gesture_end().
Referenced by IMAGE_OT_sample_line().
int WM_gesture_straightline_invoke (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
Definition at line 2831 of file wm_operators.c.
References CTX_wm_window(), wmOperator::customdata, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_int_get(), RNA_struct_find_property(), WM_cursor_modal(), WM_event_add_modal_handler(), WM_gesture_new(), WM_GESTURE_STRAIGHTLINE, and wm_gesture_tag_redraw().
Referenced by image_sample_line_invoke().
int WM_gesture_straightline_modal (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
Definition at line 2846 of file wm_operators.c.
References CTX_wm_window(), wmGesture::customdata, wmOperator::customdata, EVT_MODAL_MAP, GESTURE_MODAL_BEGIN, GESTURE_MODAL_CANCEL, GESTURE_MODAL_SELECT, wmGesture::mode, MOUSEMOVE, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, straightline_apply(), wmGesture::swinid, wmEvent::type, wmEvent::val, wm_gesture_end(), wm_gesture_tag_redraw(), wm_subwindow_getorigin(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by IMAGE_OT_sample_line().
void WM_gestures_remove (struct bContext * C)
Definition at line 119 of file wm_gesture.c.
References CTX_wm_window(), ListBase::first, wmWindow::gesture, and WM_gesture_end().
Referenced by ui_but_start_drag().
void WM_init (struct bContext * C, int argc, const char ** argv)
Definition at line 125 of file wm_init_exit.c.
References BLF_init(), BLF_lang_init(), BLF_lang_set(), BLI_getDefaultDocumentFolder(), BLI_make_file_string(), BLI_strncpy(), BPY_app_handlers_reset(), BPY_context_set(), BPY_driver_reset(), BPY_modules_load_user(), BPY_python_start(), clear_matcopybuf(), DAG_editors_update_cb(), ED_file_init(), ED_init_node_butfuncs(), ED_preview_init_dbase(), ED_render_clear_mtex_copybuf(), ED_render_id_flush_update(), ED_render_scene_update(), ED_spacetypes_init(), FALSE, FILE_MAX, G, GHOST_CreateSystemPaths(), GHOST_toggleConsole(), GPU_extensions_init(), GPU_set_anisotropic(), GPU_set_mipmap(), NULL, set_blender_test_break_cb(), set_free_windowmanager_cb(), UI_init(), USER_DISABLE_MIPMAP, wm_close_and_free(), wm_ghost_init(), wm_init_cursor_data(), wm_init_reports(), WM_menutype_init(), wm_operatortype_init(), WM_read_history(), WM_read_homefile(), wm_start_with_console, and wm_window_testbreak().
Referenced by main().
int WM_init_game (struct bContext * C)
Definition at line 217 of file wm_init_exit.c.
References ARegion::alignment, BKE_area_find_region_type(), BKE_report(), BKE_screen_find_big_area(), CTX_data_main(), CTX_data_scene(), CTX_wm_area_set(), CTX_wm_manager(), CTX_wm_region_set(), CTX_wm_screen(), CTX_wm_window(), CTX_wm_window_set(), wmTimer::customdata, ED_region_toggle_hidden(), ED_screen_full_toggle(), ListBase::first, ARegion::flag, ScrArea::full, GAME_PLAYER_FULLSCREEN, GHOST_DisposeRectangle(), GHOST_GetClientBounds(), GHOST_GetHeightRectangle(), GHOST_GetWidthRectangle(), wmWindow::ghostwin, Scene::gm, MEM_callocN(), ARegion::next, NULL, GameData::playerflag, ScrArea::regionbase, ARegion::regiontype, wmWindowManager::reports, ReportList::reporttimer, RGN_ALIGN_QSPLIT, RGN_FLAG_HIDDEN, RGN_TYPE_WINDOW, RPT_ERROR, Main::scene, sound_exit(), SPACE_VIEW3D, TIMER, wmWindowManager::windows, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_timer(), WM_event_remove_timer(), wm_get_screensize(), WM_OP_EXEC_DEFAULT, WM_operator_name_call(), rcti::xmax, and rcti::ymax.
Referenced by main().
void WM_init_splash (struct bContext * C)
Definition at line 203 of file wm_init_exit.c.
References CTX_wm_manager(), CTX_wm_window(), CTX_wm_window_set(), ListBase::first, NULL, USER_SPLASH_DISABLE, wmWindowManager::windows, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by main().
void WM_jobs_callbacks (struct wmJob * , void(*)(void *, short *, short *, float *) startjob, void(*)(void *) initjob, void(*)(void *) update, void(*)(void *) endjob)
Definition at line 242 of file wm_jobs.c.
References wmJob::endjob, wmJob::initjob, wmJob::startjob, update(), and wmJob::update.
Referenced by clip_rebuild_proxy_exec(), ED_preview_icon_job(), ED_preview_shader_job(), multiresbake_image_exec(), objects_bake_render_invoke(), ocean_bake_exec(), screen_render_invoke(), screencast_exec(), seq_proxy_build_job(), snode_composite_job(), solve_camera_invoke(), thumbnails_start(), and track_markers_invoke().
void WM_jobs_customdata (struct wmJob * , void * customdata, void(*)(void *) free)
Definition at line 220 of file wm_jobs.c.
References wmJob::customdata, wmJob::free, wmJob::running, and wmJob::stop.
Referenced by clip_rebuild_proxy_exec(), ED_preview_icon_job(), ED_preview_shader_job(), multiresbake_image_exec(), objects_bake_render_invoke(), ocean_bake_exec(), screen_render_invoke(), screencast_exec(), seq_proxy_build_job(), snode_composite_job(), solve_camera_invoke(), thumbnails_start(), and track_markers_invoke().
struct wmJob* WM_jobs_get (struct wmWindowManager * wm, struct wmWindow * win, void * owner, const char * name, int flag) [read]
Definition at line 154 of file wm_jobs.c.
References BLI_addtail(), BLI_strncpy(), wmJob::flag, wmWindowManager::jobs, MEM_callocN(), wmJob::name, NULL, wmJob::owner, wmJob::win, and wm_job_find().
Referenced by clip_rebuild_proxy_exec(), ED_preview_icon_job(), ED_preview_shader_job(), multiresbake_image_exec(), objects_bake_render_invoke(), ocean_bake_exec(), screen_render_invoke(), screencast_exec(), seq_proxy_build_job(), snode_composite_job(), solve_camera_invoke(), thumbnails_start(), and track_markers_invoke().
void* WM_jobs_get_customdata (struct wmJob *)
Definition at line 210 of file wm_jobs.c.
References wmJob::customdata, and wmJob::run_customdata.
Referenced by ED_preview_icon_job(), and seq_proxy_build_job().
int WM_jobs_has_running (struct wmWindowManager * wm)
Definition at line 521 of file wm_jobs.c.
References ListBase::first, wmWindowManager::jobs, wmJob::next, and wmJob::running.
int WM_jobs_is_running (struct wmJob *)
Definition at line 205 of file wm_jobs.c.
References wmJob::running.
Referenced by seq_proxy_build_job().
void WM_jobs_kill (struct wmWindowManager * wm, void * owner, void(*)(void *, short int *, short int *, float *))
Definition at line 396 of file wm_jobs.c.
References ListBase::first, wmWindowManager::jobs, wmJob::next, wmJob::owner, wmJob::startjob, and wm_jobs_kill_job().
Referenced by ED_preview_kill_jobs(), and thumbnails_stop().
char* WM_jobs_name (struct wmWindowManager * wm, void * owner)
Definition at line 195 of file wm_jobs.c.
References wmJob::name, NULL, and wm_job_find().
Referenced by uiTemplateRunningJobs().
float WM_jobs_progress (struct wmWindowManager * wm, void * owner)
Definition at line 185 of file wm_jobs.c.
References wmJob::flag, NULL, wmJob::progress, wm_job_find(), and WM_JOB_PROGRESS.
Referenced by uiTemplateRunningJobs().
void WM_jobs_start (struct wmWindowManager * wm, struct wmJob *)
Definition at line 308 of file wm_jobs.c.
References BLI_init_threads(), BLI_insert_thread(), wmJob::customdata, do_job_thread(), wmJob::free, wmJob::initjob, NULL, wmJob::progress, wmJob::ready, wmJob::run_customdata, wmJob::run_free, wmJob::running, wmJob::startjob, wmJob::stop, wmJob::suspended, wmJob::threads, TIMERJOBS, wmJob::timestep, wmJob::win, WM_event_add_timer(), wm_jobs_test_suspend_stop(), and wmJob::wt.
Referenced by clip_rebuild_proxy_exec(), ED_preview_icon_job(), ED_preview_shader_job(), multiresbake_image_exec(), objects_bake_render_invoke(), ocean_bake_exec(), screen_render_invoke(), screencast_exec(), seq_proxy_build_job(), snode_composite_job(), solve_camera_invoke(), thumbnails_start(), track_markers_invoke(), and wm_jobs_timer().
void WM_jobs_stop (struct wmWindowManager * wm, void * owner, void * startjob)
Definition at line 385 of file wm_jobs.c.
References ListBase::first, wmWindowManager::jobs, wmJob::next, wmJob::owner, wmJob::running, wmJob::startjob, and wmJob::stop.
Referenced by do_running_jobs().
void WM_jobs_stop_all (struct wmWindowManager * wm)
Definition at line 375 of file wm_jobs.c.
References ListBase::first, wmWindowManager::jobs, and wm_jobs_kill_job().
Referenced by read_undosave(), screen_opengl_render_init(), screen_render_invoke(), WM_exit_ext(), and wm_window_match_init().
int WM_jobs_test (struct wmWindowManager * wm, void * owner)
Definition at line 172 of file wm_jobs.c.
References ListBase::first, wmWindowManager::jobs, wmJob::next, wmJob::owner, wmJob::running, and wmJob::suspended.
Referenced by ED_undo_operator_repeat(), ed_undo_step(), objects_bake_render_invoke(), objects_bake_render_modal(), screen_opengl_render_init(), screen_render_invoke(), screen_render_modal(), solve_camera_invoke(), solve_camera_modal(), thumbnails_running(), track_markers_invoke(), track_markers_modal(), uiTemplateRunningJobs(), and WM_operator_check_ui_enabled().
void WM_jobs_timer (struct wmJob * , double timestep, unsigned int note, unsigned int endnote)
Definition at line 235 of file wm_jobs.c.
References wmJob::endnote, wmJob::note, and wmJob::timestep.
Referenced by clip_rebuild_proxy_exec(), ED_preview_icon_job(), ED_preview_shader_job(), multiresbake_image_exec(), objects_bake_render_invoke(), ocean_bake_exec(), screen_render_invoke(), screencast_exec(), seq_proxy_build_job(), snode_composite_job(), solve_camera_invoke(), thumbnails_start(), and track_markers_invoke().
void WM_main (struct bContext * C)
Definition at line 358 of file wm.c.
References wm_draw_update(), wm_event_do_handlers(), wm_event_do_notifiers(), and wm_window_process_events().
Referenced by main().
void WM_main_add_notifier (unsigned int type, void * reference)
Definition at line 156 of file wm_event_system.c.
References wmNotifier::action, BLI_addtail(), wmNotifier::category, wmNotifier::data, ListBase::first, G, MEM_callocN(), NOTE_ACTION, NOTE_CATEGORY, NOTE_DATA, NOTE_SUBTYPE, wmWindowManager::queue, wmNotifier::reference, wmNotifier::subtype, wmNotifier::wm, Main::wm, and wm_test_duplicate_notifier().
Referenced by ANIM_apply_keyingset(), armature_circle_select(), brush_generic_tool_set(), do_lasso_select_armature(), ED_node_changed_update(), ED_node_set_active(), ED_space_image_set(), ED_view3d_camera_lock_sync(), icon_preview_endjob(), make_paths_absolute_exec(), make_paths_relative_exec(), object_duplicates_make_real_exec(), pose_circle_select(), proxy_endjob(), render_endjob(), rna_property_update(), solve_camera_freejob(), track_markers_freejob(), viewRedrawPost(), weight_sample_invoke(), and WM_operator_stack_clear().
int WM_menu_invoke (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
int WM_menutype_add (struct MenuType * mt)
Definition at line 172 of file wm.c.
References BLI_ghash_insert(), and MenuType::idname.
Referenced by node_menus_register(), and recent_files_menu_register().
struct MenuType* WM_menutype_find (const char * idname, int quiet) [read]
Definition at line 156 of file wm.c.
References BLI_ghash_lookup(), mt, and NULL.
Referenced by uiItemM(), uiPupMenuInvoke(), and wm_block_create_splash().
void WM_menutype_free (void)
Definition at line 189 of file wm.c.
References BLI_ghash_free(), BLI_ghashIterator_free(), BLI_ghashIterator_getValue(), BLI_ghashIterator_isDone(), BLI_ghashIterator_new(), BLI_ghashIterator_step(), ExtensionRNA::data, MenuType::ext, ExtensionRNA::free, MEM_freeN(), mt, and NULL.
Referenced by WM_exit_ext().
void WM_menutype_freelink (struct MenuType * mt)
Definition at line 178 of file wm.c.
References BLI_ghash_remove(), MenuType::idname, MEM_freeN(), and NULL.
void WM_menutype_init (void)
Definition at line 184 of file wm.c.
References BLI_ghash_new(), BLI_ghashutil_strcmp(), and BLI_ghashutil_strhash().
Referenced by WM_init().
int WM_modal_tweak_exit (struct wmEvent * evt, int tweak_event)
Definition at line 2402 of file wm_event_system.c.
References ELEM3, EVT_TWEAK_L, EVT_TWEAK_M, EVT_TWEAK_R, KM_RELEASE, USER_RELEASECONFIRM, and wmEvent::val.
Referenced by ed_marker_move_modal().
void WM_operator_bl_idname (char * to, const char * from)
Definition at line 492 of file wm_operators.c.
References BLI_ascii_strtoupper(), BLI_strncpy(), and OP_MAX_TYPENAME.
Referenced by WM_operatortype_find().
int WM_operator_call (struct bContext * C, struct wmOperator * op)
Definition at line 621 of file wm_event_system.c.
References wm_operator_exec().
Referenced by dialog_exec_cb(), operator_cb(), and wm_operator_ui_popup_ok().
int WM_operator_call_notest (struct bContext * C, struct wmOperator * op)
Definition at line 629 of file wm_event_system.c.
References wm_operator_exec_notest().
Referenced by wm_link_append_invoke(), and WM_operator_filesel().
int WM_operator_call_py (struct bContext * C, struct wmOperatorType * ot, int context, struct PointerRNA * properties, struct ReportList * reports)
Definition at line 1081 of file wm_event_system.c.
References CTX_wm_manager(), wmOperatorType::exec, FALSE, wmOperatorType::flag, ReportList::flag, wmOperatorType::name, wmWindowManager::op_undo_depth, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RETVAL_CHECK, OPERATOR_RUNNING_MODAL, OPTYPE_UNDO, RPT_FREE, wmOperator::type, wm_operator_call_internal(), wm_operator_create(), and wm_operator_register_check().
int WM_operator_check_ui_enabled (const struct bContext * C, const char * idname)
int WM_operator_confirm (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
int WM_operator_confirm_message (struct bContext * C, struct wmOperator * op, const char * message)
Definition at line 775 of file wm_operators.c.
References PointerRNA::data, IDP_CopyProperty(), IFACE_, IDProperty::len, NULL, OPERATOR_CANCELLED, wmOperator::ptr, wmOperator::type, uiItemFullO_ptr(), uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), and WM_OP_EXEC_REGION_WIN.
Referenced by file_directory_invoke(), move_to_layer_invoke(), and WM_operator_confirm().
int WM_operator_filesel (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
int WM_operator_filesel_ensure_ext_imtype (wmOperator * op, const char imtype)
Definition at line 812 of file wm_operators.c.
References BKE_add_image_extension(), FALSE, FILE_MAX, wmOperator::ptr, RNA_property_string_get(), RNA_property_string_set(), RNA_struct_find_property(), and TRUE.
Referenced by image_save_as_check(), and screenshot_check().
void WM_operator_free (struct wmOperator * op)
Definition at line 74 of file wm.c.
References BKE_reports_clear(), BPY_DECREF(), PointerRNA::data, ListBase::first, ReportList::flag, IDP_FreeProperty(), wmOperator::macro, MEM_freeN(), wmOperator::next, wmOperator::properties, wmOperator::ptr, wmOperator::py_instance, wmOperator::reports, RPT_FREE, and WM_operator_free().
Referenced by confirm_cancel_operator(), operator_cb(), wm_close_and_free(), WM_event_add_fileselect(), WM_event_remove_handlers(), wm_exit_blender_op(), wm_handler_fileselect_call(), wm_handler_operator_call(), wm_operator_exec(), wm_operator_finished(), WM_operator_free(), wm_operator_invoke(), wm_operator_register(), WM_operator_stack_clear(), and wm_operator_ui_popup_cancel().
int WM_operator_last_properties_init (struct wmOperator * op)
int WM_operator_last_properties_store (struct wmOperator * op)
wmOperator* WM_operator_last_redo (const struct bContext * C)
int WM_operator_name_call (struct bContext * C, const char * opstring, int context, struct PointerRNA * properties)
Definition at line 1067 of file wm_event_system.c.
References FALSE, NULL, wm_operator_call_internal(), and WM_operatortype_find().
Referenced by BIF_do_manipulator(), console_main_area_draw(), console_paste_exec(), do_outliner_item_activate(), do_outliner_operation_event(), do_running_jobs(), do_view3d_header_buttons(), duplicate_metaelems_invoke(), ED_object_toggle_modes(), file_browse_invoke(), file_panel_cb(), file_smoothscroll_invoke(), ghost_event_proc(), mouse_nla_strips(), nlaedit_duplicate_invoke(), nlaedit_select_leftright(), node_render_changed_exec(), node_toggle_button_cb(), object_mode_set_exec(), object_mouse_select_menu(), operator_call_cb(), operator_enum_call_cb(), operator_name_cb(), outliner_animdata_operation_exec(), pyop_call(), report_replay_exec(), sequencer_add_duplicate_invoke(), ui_add_smart_controller(), ui_apply_but_funcs_after(), ui_but_anim_add_driver(), ui_but_anim_add_keyingset(), ui_but_anim_copy_driver(), ui_but_anim_delete_keyframe(), ui_but_anim_insert_keyframe(), ui_but_anim_paste_driver(), ui_but_anim_remove_driver(), ui_but_anim_remove_keyingset(), ui_handler_popup(), ui_set_but_default(), view_pan_modal(), viewdolly_modal(), viewmove_modal(), viewrotate_modal(), viewzoom_modal(), wm_handlers_do(), WM_init_game(), and WM_init_splash().
int WM_operator_poll (struct bContext * C, struct wmOperatorType * ot)
Definition at line 399 of file wm_event_system.c.
References ListBase::first, wmOperatorTypeMacro::idname, wmOperatorType::macro, wmOperatorTypeMacro::next, wmOperatorType::poll, wmOperatorType::pyop_poll, WM_operator_poll(), and WM_operatortype_find().
Referenced by clip_panel_operator_redo(), ED_undo_operator_repeat(), operator_search_cb(), view3d_panel_operator_redo(), wm_operator_exec(), wm_operator_invoke(), and WM_operator_poll().
int WM_operator_poll_context (struct bContext * C, struct wmOperatorType * ot, int context)
Definition at line 420 of file wm_event_system.c.
References NULL, TRUE, and wm_operator_call_internal().
Referenced by pyop_call(), pyop_poll(), ui_tooltip_create(), and uiEndBlock().
void WM_operator_properties_alloc (struct PointerRNA ** ptr, struct IDProperty ** properties, const char * opstring)
Definition at line 574 of file wm_operators.c.
References IDP_GROUP, IDP_New(), MEM_callocN(), NULL, and WM_operator_properties_create().
Referenced by WM_dropbox_add(), wm_keymap_item_properties_set(), and WM_operatortype_macro_define().
void WM_operator_properties_create (struct PointerRNA * ptr, const char * opstring)
Definition at line 562 of file wm_operators.c.
References NULL, RNA_OperatorProperties, RNA_pointer_create(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
Referenced by do_view3d_header_buttons(), file_browse_invoke(), file_panel_cb(), ghost_event_proc(), node_render_changed_exec(), object_mouse_select_menu(), parent_drop_invoke(), screen_area_options_invoke(), ui_but_menu(), ui_set_but_default(), uiLayoutOperatorButs(), wm_keymap_item_copy(), and WM_operator_properties_alloc().
void WM_operator_properties_create_ptr (struct PointerRNA * ptr, struct wmOperatorType * ot)
Definition at line 557 of file wm_operators.c.
References NULL, RNA_pointer_create(), and wmOperatorType::srna.
Referenced by node_composit_buts_renderlayers(), operator_enum_call_cb(), pyop_call(), pyop_getrna(), uiButGetOperatorPtrRNA(), uiItemBooleanO(), uiItemEnumO_ptr(), uiItemEnumO_ptr__internal(), uiItemEnumO_string(), uiItemEnumO_value(), uiItemFloatO(), uiItemIntO(), uiItemsFullEnumO(), uiItemStringO(), WM_operator_properties_create(), and WM_operator_pystring().
void WM_operator_properties_filesel (struct wmOperatorType * ot, int filter, short type, short action, short flag, short display)
Definition at line 829 of file wm_operators.c.
References BLENDERFILE, BTXFILE, COLLADAFILE, FILE_DEFAULTDISPLAY, FILE_IMGDISPLAY, FILE_LOADLIB, FILE_LONGDISPLAY, FILE_MAX, FILE_SAVE, FILE_SHORTDISPLAY, FILE_SPECIAL, FOLDERFILE, FTFONTFILE, IMAGEFILE, MOVIEFILE, NULL, PROP_HIDDEN, PROP_SKIP_SAVE, PYSCRIPTFILE, RNA_def_boolean(), RNA_def_collection_runtime(), RNA_def_enum(), RNA_def_int(), RNA_def_property_flag(), RNA_def_string_dir_path(), RNA_def_string_file_name(), RNA_def_string_file_path(), RNA_OperatorFileListElement, SOUNDFILE, wmOperatorType::srna, TEXTFILE, TRUE, WM_FILESEL_DIRECTORY, WM_FILESEL_FILENAME, WM_FILESEL_FILEPATH, WM_FILESEL_FILES, and WM_FILESEL_RELPATH.
Referenced by BUTTONS_OT_directory_browse(), BUTTONS_OT_file_browse(), CLIP_OT_open(), FILE_OT_find_missing_files(), FONT_OT_file_paste(), FONT_OT_open(), GRAPH_OT_sound_bake(), IMAGE_OT_open(), IMAGE_OT_replace(), IMAGE_OT_save_as(), NODE_OT_add_file(), OBJECT_OT_multires_external_save(), SCREEN_OT_screenshot(), SEQUENCER_OT_change_path(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_sound_strip_add(), SOUND_OT_mixdown(), SOUND_OT_open(), SOUND_OT_open_mono(), TEXT_OT_open(), TEXT_OT_save_as(), TEXTURE_OT_envmap_save(), WM_OT_link_append(), WM_OT_open_mainfile(), WM_OT_recover_auto_save(), WM_OT_save_as_mainfile(), and WM_OT_save_mainfile().
void WM_operator_properties_free (struct PointerRNA * ptr)
Definition at line 637 of file wm_operators.c.
References PointerRNA::data, IDP_FreeProperty(), MEM_freeN(), and NULL.
Referenced by do_view3d_header_buttons(), file_browse_invoke(), file_panel_cb(), ghost_event_proc(), node_render_changed_exec(), object_mouse_select_menu(), operator_enum_call_cb(), pyop_as_string(), pyop_call(), ui_apply_but_funcs_after(), ui_free_but(), ui_set_but_default(), wm_dropbox_free(), wm_keymap_item_free(), WM_keymap_properties_reset(), WM_keymap_remove_item(), WM_operator_pystring(), and wm_operatortype_free_macro().
void WM_operator_properties_gesture_border (struct wmOperatorType * ot, int extend)
Definition at line 905 of file wm_operators.c.
References RNA_def_boolean(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ACTION_OT_select_border(), ANIM_OT_channels_select_border(), CLIP_OT_graph_select_border(), CLIP_OT_select_border(), FILE_OT_select_border(), GRAPH_OT_select_border(), INFO_OT_select_border(), MARKER_OT_select_border(), NLA_OT_select_border(), NODE_OT_select_border(), OUTLINER_OT_select_border(), SEQUENCER_OT_select_border(), SEQUENCER_OT_view_ghost_border(), UV_OT_select_border(), and VIEW3D_OT_select_border().
void WM_operator_properties_gesture_straightline (struct wmOperatorType * ot, int cursor)
Definition at line 917 of file wm_operators.c.
References RNA_def_int(), and wmOperatorType::srna.
Referenced by IMAGE_OT_sample_line().
void WM_operator_properties_reset (struct wmOperator * op)
Definition at line 619 of file wm_operators.c.
References PointerRNA::data, PROP_SKIP_SAVE, wmOperator::ptr, RNA_PROP_BEGIN, RNA_PROP_END, RNA_property_flag(), RNA_property_identifier(), RNA_struct_idprops_unset(), RNA_struct_iterator_property(), wmOperatorType::srna, and wmOperator::type.
Referenced by ui_layout_operator_buts__reset_cb().
void WM_operator_properties_sanitize (struct PointerRNA * ptr, const short no_context)
Definition at line 590 of file wm_operators.c.
References PROP_ENUM, PROP_ENUM_NO_CONTEXT, PROP_POINTER, RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_OperatorProperties, RNA_property_pointer_get(), RNA_property_pointer_type(), RNA_property_type(), RNA_STRUCT_BEGIN, RNA_STRUCT_END, RNA_struct_is_a(), and WM_operator_properties_sanitize().
Referenced by pyop_call(), pyop_getrna(), wm_keymap_item_properties_set(), wm_operator_create(), WM_operator_properties_sanitize(), and WM_operatortype_macro_define().
void WM_operator_properties_select_all (struct wmOperatorType * ot)
Definition at line 892 of file wm_operators.c.
References NULL, RNA_def_enum(), SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, and wmOperatorType::srna.
Referenced by ARMATURE_OT_select_all(), CLIP_OT_graph_select_all_markers(), CLIP_OT_select_all(), CURVE_OT_select_all(), LATTICE_OT_select_all(), MARKER_OT_select_all(), MBALL_OT_select_all(), MESH_OT_select_all(), OBJECT_OT_select_all(), OBJECT_OT_vertex_group_lock(), PAINT_OT_face_select_all(), PAINT_OT_vert_select_all(), PARTICLE_OT_select_all(), POSE_OT_select_all(), SEQUENCER_OT_select_all(), and UV_OT_select_all().
int WM_operator_props_dialog_popup (struct bContext * C, struct wmOperator * op, int width, int height)
Definition at line 1147 of file wm_operators.c.
References data, wmOpPopUp::free_op, wmOpPopUp::height, MEM_callocN(), wmOpPopUp::op, OPERATOR_RUNNING_MODAL, TRUE, uiPupBlockEx(), wmOpPopUp::width, wm_block_dialog_create(), wm_operator_ui_popup_cancel(), and wm_operator_ui_popup_ok().
Referenced by image_new_invoke(), text_jump_invoke(), and wm_debug_menu_invoke().
int WM_operator_props_popup (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
void WM_operator_py_idname (char * to, const char * from)
Definition at line 471 of file wm_operators.c.
References BLI_ascii_strtolower(), BLI_strncpy(), and OP_MAX_TYPENAME.
Referenced by operator_search_cb(), ui_but_menu(), and WM_operator_pystring().
char* WM_operator_pystring (struct bContext * C, struct wmOperatorType * ot, struct PointerRNA * opptr, int all_args)
Definition at line 521 of file wm_operators.c.
References BLI_dynstr_append(), BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), FALSE, wmOperatorType::idname, MEM_freeN(), NULL, OP_MAX_TYPENAME, RNA_pointer_as_string_keywords(), WM_operator_properties_create_ptr(), WM_operator_properties_free(), and WM_operator_py_idname().
Referenced by pyop_as_string(), ui_but_copy_paste(), ui_intro_button(), ui_tooltip_create(), wm_operator_finished(), wm_operator_print(), and wm_operator_reports().
int WM_operator_redo_popup (struct bContext * C, struct wmOperator * op)
Definition at line 1162 of file wm_operators.c.
References BKE_reportf(), CTX_wm_reports(), wmOperatorType::flag, wmOperatorType::idname, OPERATOR_CANCELLED, OPTYPE_REGISTER, wmOperatorType::poll, RPT_ERROR, wmOperator::type, uiPupBlock(), and wm_block_create_redo().
Referenced by redo_last_invoke().
int WM_operator_repeat (struct bContext * C, struct wmOperator * op)
Definition at line 635 of file wm_event_system.c.
References wm_operator_exec().
Referenced by ED_undo_operator_repeat(), repeat_history_exec(), and repeat_last_exec().
int WM_operator_repeat_check (const struct bContext * C, struct wmOperator * op)
void WM_operator_stack_clear (struct wmWindowManager * wm)
Definition at line 140 of file wm.c.
References BLI_remlink(), ListBase::first, NC_WM, ND_HISTORY, NULL, wmWindowManager::operators, WM_main_add_notifier(), and WM_operator_free().
Referenced by ed_undo_exec().
int WM_operator_ui_popup (struct bContext * C, struct wmOperator * op, int width, int height)
Definition at line 1118 of file wm_operators.c.
References data, wmOpPopUp::free_op, wmOpPopUp::height, MEM_callocN(), NULL, wmOpPopUp::op, OPERATOR_RUNNING_MODAL, TRUE, uiPupBlockEx(), wmOpPopUp::width, wm_operator_ui_create(), and wm_operator_ui_popup_cancel().
int WM_operator_winactive (struct bContext * C)
Definition at line 930 of file wm_operators.c.
References CTX_wm_window(), and NULL.
Referenced by SCREEN_OT_new(), SCREEN_OT_screencast(), SCREEN_OT_screenshot(), SCREEN_OT_spacedata_cleanup(), wm_link_append_poll(), WM_OT_call_menu(), WM_OT_debug_menu(), WM_OT_quit_blender(), WM_OT_recover_auto_save(), WM_OT_recover_last_session(), WM_OT_redraw_timer(), WM_OT_save_homefile(), WM_OT_splash(), and WM_OT_window_fullscreen_toggle().
void WM_operatortype_append (void(*)(struct wmOperatorType *) opfunc)
struct wmOperatorType* WM_operatortype_append_macro (const char * idname, const char * name, int flag) [read]
Definition at line 348 of file wm_operators.c.
References BLENDER_RNA, BLF_I18NCONTEXT_OPERATOR_DEFAULT, BLI_ghash_insert(), wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MEM_callocN(), wmOperatorType::modal, N_, wmOperatorType::name, NULL, OPTYPE_MACRO, wmOperatorType::poll, RNA_def_struct(), RNA_def_struct_identifier(), RNA_def_struct_translation_context(), RNA_def_struct_ui_text(), wmOperatorType::srna, TRUE, wm_macro_cancel(), wm_macro_exec(), wm_macro_invoke(), wm_macro_modal(), and WM_operatortype_find().
Referenced by ED_operatormacros_action(), ED_operatormacros_armature(), ED_operatormacros_clip(), ED_operatormacros_curve(), ED_operatormacros_graph(), ED_operatormacros_mesh(), ED_operatormacros_node(), and ED_operatormacros_object().
void WM_operatortype_append_macro_ptr (void(*)(struct wmOperatorType *, void *) opfunc, void * userdata)
void WM_operatortype_append_ptr (void(*)(struct wmOperatorType *, void *) opfunc, void * userdata)
struct wmOperatorType* WM_operatortype_find (const char * idnamem, int quiet) [read]
Definition at line 110 of file wm_operators.c.
References BLI_ghash_lookup(), NULL, OP_MAX_TYPENAME, and WM_operator_bl_idname().
Referenced by graph_fmodifier_add_invoke(), node_composit_buts_renderlayers(), operator_search_menu(), poselib_add_menu_invoke__replacemenu(), pyop_as_string(), pyop_call(), pyop_getinstance(), pyop_getrna(), pyop_poll(), PYOP_wrap_macro_define(), ui_def_but_operator_text(), uiDefButO(), uiDefIconButO(), uiDefIconTextButO(), uiItemBooleanO(), uiItemEnumO(), uiItemEnumO_string(), uiItemEnumO_value(), uiItemFloatO(), uiItemFullO(), uiItemIntO(), uiItemMenuEnumO(), uiItemsFullEnumO(), uiItemStringO(), uiPupBlockO(), unpack_menu(), WM_dropbox_add(), wm_handler_operator_call(), WM_modalkeymap_assign(), wm_operator_create(), WM_operator_name_call(), WM_operator_poll(), WM_operator_properties_create(), WM_operatortype_append_macro(), WM_operatortype_macro_define(), and WM_operatortype_remove().
struct GHashIterator* WM_operatortype_iter (void) [read]
Definition at line 138 of file wm_operators.c.
References BLI_ghashIterator_new().
Referenced by operator_search_cb(), and pyop_dir().
struct wmOperatorTypeMacro* WM_operatortype_macro_define (struct wmOperatorType * ot, const char * idname) [read]
Definition at line 409 of file wm_operators.c.
References BLI_addtail(), BLI_strncpy(), wmOperatorType::description, wmOperatorType::idname, wmOperatorTypeMacro::idname, wmOperatorType::macro, MEM_callocN(), wmOperatorType::name, OP_MAX_TYPENAME, wmOperatorTypeMacro::properties, wmOperatorTypeMacro::ptr, RNA_def_pointer_runtime(), wmOperatorType::srna, WM_operator_properties_alloc(), WM_operator_properties_sanitize(), and WM_operatortype_find().
Referenced by ED_operatormacros_action(), ED_operatormacros_armature(), ED_operatormacros_clip(), ED_operatormacros_curve(), ED_operatormacros_graph(), ED_operatormacros_mesh(), ED_operatormacros_node(), ED_operatormacros_object(), and PYOP_wrap_macro_define().
int WM_operatortype_remove (const char * idname)
Definition at line 447 of file wm_operators.c.
References BLENDER_RNA, BLI_ghash_remove(), ListBase::first, wmOperatorType::idname, IDP_FreeProperty(), wmOperatorType::last_properties, wmOperatorType::macro, MEM_freeN(), NULL, RNA_struct_free(), wmOperatorType::srna, WM_operatortype_find(), and wm_operatortype_free_macro().
void* WM_paint_cursor_activate (struct wmWindowManager * wm, int(*)(struct bContext *C) poll, void(*)(struct bContext *C, int, int, void *customdata) draw, void * customdata)
void WM_paint_cursor_end (struct wmWindowManager * wm, void * handle)
Definition at line 2292 of file wm_operators.c.
References BLI_remlink(), ListBase::first, MEM_freeN(), wmPaintCursor::next, and wmWindowManager::paintcursors.
Referenced by paint_stroke_modal(), postTrans(), radial_control_cancel(), toggle_paint_cursor(), and toggle_particle_cursor().
void WM_progress_clear (struct wmWindow * win)
Definition at line 1120 of file wm_window.c.
References GHOST_EndProgressBar(), and wmWindow::ghostwin.
Referenced by wm_jobs_timer().
void WM_progress_set (struct wmWindow * win, float progress)
Definition at line 1115 of file wm_window.c.
References GHOST_SetProgressBar(), and wmWindow::ghostwin.
Referenced by wm_jobs_timer().
void WM_read_file (struct bContext * C, const char * filepath, struct ReportList * reports)
Definition at line 355 of file wm_files.c.
References BKE_READ_EXOTIC_FAIL_FORMAT, BKE_READ_EXOTIC_FAIL_OPEN, BKE_READ_EXOTIC_FAIL_PATH, BKE_READ_EXOTIC_OK_BLEND, BKE_READ_EXOTIC_OK_OTHER, BKE_read_file(), BKE_READ_FILE_FAIL, BKE_READ_FILE_OK_USERPREFS, BKE_reportf(), BKE_reset_undo(), BKE_write_undo(), BLI_assert, BLI_CB_EVT_LOAD_POST, BLI_CB_EVT_LOAD_PRE, BLI_exec_cb(), BLI_findstring(), BPY_app_handlers_reset(), BPY_driver_reset(), BPY_modules_load_user(), CTX_data_main(), CTX_data_scene(), CTX_wm_manager(), CTX_wm_window_set(), DAG_on_visible_update(), ED_editors_init(), RenderData::engine, FALSE, G, G_SCRIPT_AUTOEXEC, G_SCRIPT_OVERRIDE_PREF, Scene::id, IFACE_, ID::name, NC_WM, ND_FILEREAD, ID::next, NULL, Scene::r, R_engines, RPT_ERROR, RPT_WARNING, TRUE, WM_check(), WM_cursor_wait(), WM_event_add_notifier(), wm_init_userdef(), wm_read_exotic(), wm_window_match_do(), wm_window_match_init(), and write_history().
Referenced by load_file(), wm_autosave_read(), wm_open_mainfile_exec(), wm_recover_auto_save_exec(), and wm_recover_last_session_exec().
int WM_read_homefile (struct bContext * C, struct ReportList * reports, short from_memory)
int WM_read_homefile_exec (struct bContext * C, struct wmOperator * op)
Definition at line 577 of file wm_files.c.
References wmOperatorType::idname, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, wmOperator::type, and WM_read_homefile().
Referenced by WM_OT_read_factory_settings(), and WM_OT_read_homefile().
void WM_redraw_windows (struct bContext * C)
Definition at line 822 of file wm_draw.c.
References CTX_wm_area(), CTX_wm_area_set(), CTX_wm_region(), CTX_wm_region_set(), CTX_wm_window(), CTX_wm_window_set(), and wm_draw_update().
Referenced by game_engine_exec(), and screenshot_data_create().
void WM_set_framebuffer_index_color (int index)
Definition at line 380 of file wm_subwindow.c.
References cpack, and index_to_framebuffer().
Referenced by bbs_mesh_solid__drawCenter(), bbs_mesh_solid__setDrawOpts(), bbs_mesh_solid__setSolidDrawOptions(), bbs_mesh_solid_hide__setDrawOpts(), bbs_mesh_verts__mapFunc(), bbs_mesh_wire__setDrawOptions(), and bbs_obmode_mesh_verts__mapFunc().
void WM_setinitialstate_fullscreen (void)
Definition at line 1198 of file wm_window.c.
References GHOST_kWindowStateFullScreen, WMInitStruct::override_flag, WIN_OVERRIDE_WINSTATE, WMInitStruct::windowstate, and wm_init_state.
Referenced by without_borders().
void WM_setinitialstate_normal (void)
Definition at line 1204 of file wm_window.c.
References GHOST_kWindowStateNormal, WMInitStruct::override_flag, WIN_OVERRIDE_WINSTATE, WMInitStruct::windowstate, and wm_init_state.
Referenced by with_borders().
void WM_setprefsize (int stax, int stay, int sizx, int sizy)
Definition at line 1188 of file wm_window.c.
References WMInitStruct::override_flag, WMInitStruct::size_x, WMInitStruct::size_y, WMInitStruct::start_x, WMInitStruct::start_y, WIN_OVERRIDE_GEOM, and wm_init_state.
Referenced by prefsize(), and wm_set_apple_prefsize().
void WM_timecursor (struct wmWindow * win, int nr)
Definition at line 242 of file wm_cursors.c.
References wmWindow::cursor, i, wmWindow::lastcursor, and window_set_custom_cursor().
Referenced by dynamicPaint_bakeImageSequence(), image_record_composite_apply(), ptcache_bake_all_exec(), and ptcache_bake_exec().
int WM_userdef_event_map (int kmitype)
Definition at line 1221 of file wm_event_system.c.
References ACTIONMOUSE, EVT_TWEAK_A, EVT_TWEAK_L, EVT_TWEAK_R, EVT_TWEAK_S, LEFTMOUSE, RIGHTMOUSE, SELECTMOUSE, USER_LMOUSESELECT, USER_WHEELZOOMDIR, WHEELDOWNMOUSE, WHEELINMOUSE, WHEELOUTMOUSE, and WHEELUPMOUSE.
Referenced by wm_eventmatch(), and WM_keymap_item_compare().
struct wmWindow* WM_window_open (struct bContext * C, struct rcti * rect) [read]
Definition at line 461 of file wm_window.c.
References wmWindow::drawdata, wmWindow::drawmethod, NULL, wmWindow::posx, wmWindow::posy, wmWindow::sizex, wmWindow::sizey, WM_check(), wm_window_new(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by area_dupli_invoke().
void WM_window_open_temp (struct bContext * C, struct rcti * position, int type)
Definition at line 482 of file wm_window.c.
References bScreen::areabase, CTX_data_scene(), CTX_wm_area_set(), CTX_wm_manager(), CTX_wm_window_set(), ED_area_newspace(), ED_screen_add(), ED_screen_set(), ELEM, ListBase::first, GHOST_SetTitle(), wmWindow::ghostwin, IFACE_, wmWindow::next, NULL, wmWindow::posx, wmWindow::posy, wmWindow::screen, wmWindow::sizex, wmWindow::sizey, SPACE_FILE, SPACE_IMAGE, SPACE_OUTLINER, SPACE_USERPREF, ScrArea::spacetype, bScreen::temp, WM_check(), wm_window_check_position(), wm_window_new(), wm_window_raise(), WM_WINDOW_RENDER, wm_window_set_size(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by render_view_open(), and userpref_show_invoke().
int WM_write_file (struct bContext * C, const char * target, int fileflags, struct ReportList * reports, int copy)
Definition at line 755 of file wm_files.c.
References BKE_report(), BKE_reportf(), blend_file_thumb(), BLI_CB_EVT_SAVE_POST, BLI_CB_EVT_SAVE_PRE, BLI_exec_cb(), BLI_path_cmp, BLI_replace_extension(), BLI_strncpy(), BLO_write_file(), CTX_data_main(), CTX_data_scene(), CTX_wm_screen(), ED_object_exit_editmode(), ED_sculpt_force_update(), EM_DO_UNDO, FILE_MAX, Library::filepath, RecentFile::filepath, G, G_AUTOPACK, G_FILE_AUTOPLAY, G_FILE_COMPRESS, G_FILE_HISTORY, Library::id, IMB_freeImBuf(), IMB_thumb_create(), IMB_thumb_delete(), len(), MEM_freeN(), ID::next, NULL, packAll(), RPT_ERROR, strlen(), THB_FAIL, THB_NORMAL, THB_SOURCE_BLEND, USER_SAVE_PREVIEWS, WM_cursor_wait(), and write_history().
Referenced by wm_save_as_mainfile_exec().
int WM_write_homefile (struct bContext * C, struct wmOperator * op)
Definition at line 854 of file wm_files.c.
References BLENDER_STARTUP_FILE, BLENDER_USER_CONFIG, BLI_get_folder_create(), BLI_make_file_string(), BLO_write_file(), CTX_data_main(), CTX_wm_manager(), CTX_wm_window(), FILE_MAX, RecentFile::filepath, G, G_FILE_AUTOPLAY, G_FILE_COMPRESS, G_FILE_HISTORY, G_FILE_LOCK, G_FILE_SIGN, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, wmWindow::screen, bScreen::temp, WM_keyconfig_update(), and wm_window_close().
Referenced by WM_OT_save_homefile().
void wmFrustum (float x1, float x2, float y1, float y2, float n, float f)
Definition at line 285 of file wm_subwindow.c.
Referenced by setwinmatrixview3d().
void wmOrtho (float x1, float x2, float y1, float y2, float n, float f)
Definition at line 293 of file wm_subwindow.c.
Referenced by setwinmatrixview3d(), and wmOrtho2().
void wmOrtho2 (float x1, float x2, float y1, float y2)
Definition at line 303 of file wm_subwindow.c.
References wmOrtho().
Referenced by draw_gpencil_2dimage(), draw_nodespace_back_pix(), ED_region_init(), ED_region_pixelspace(), ui_searchbox_region_draw_cb(), UI_view2d_view_ortho(), UI_view2d_view_orthoSpecial(), UI_view2d_view_restore(), uiDrawBlock(), wm_subwindow_open(), wm_subwindow_position(), and wmSubWindowScissorSet().
void wmSubWindowScissorSet (struct wmWindow * win, int swinid, struct rcti * srct)
Definition at line 247 of file wm_subwindow.c.
References _curswin, wmWindow::curswin, NULL, swin_from_swinid(), wmSubWindow::winrct, wmOrtho2(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ED_region_do_draw(), ED_region_set(), and wmSubWindowSet().
void wmSubWindowSet (struct wmWindow * win, int swinid)
Definition at line 280 of file wm_subwindow.c.
References NULL, and wmSubWindowScissorSet().
Referenced by ED_area_overdraw(), ED_screen_draw(), select_report_pick_invoke(), ui_popup_block_create(), view3d_region_operator_needs_opengl(), wm_gesture_draw(), wm_method_draw_triple(), wm_subwindow_open(), and wm_subwindow_position().
int write_crash_blend (void)
Definition at line 738 of file wm_files.c.
References BLI_replace_extension(), BLI_strncpy(), BLO_write_file(), FILE_MAX, G, G_FILE_HISTORY, and NULL.