Blender: node_buttons.c File Reference
node_buttons.c File Reference
node editor
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <float.h>
#include "MEM_guardedalloc.h"
#include "DNA_node_types.h"
#include "DNA_scene_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BLF_translation.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_node.h"
#include "BKE_screen.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "ED_gpencil.h"
#include "ED_screen.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "node_intern.h"
Functions
static int active_nodetree_poll (const bContext *C, PanelType *UNUSED(pt))
static int active_node_poll (const bContext *C, PanelType *UNUSED(pt))
static void active_node_panel (const bContext *C, Panel *pa)
static int node_sockets_poll (const bContext *C, PanelType *UNUSED(pt))
static void node_sockets_panel (const bContext *C, Panel *pa)
void node_buttons_register (ARegionType *art)
static int node_properties (bContext *C, wmOperator *UNUSED(op))
static int node_properties_poll (bContext *C)
void NODE_OT_properties (wmOperatorType *ot)
Detailed Description
Definition in file node_buttons.c.
Function Documentation
static void active_node_panel (const bContext * C, Panel * pa) [static]
Definition at line 87 of file node_buttons.c.
References CTX_wm_space_node(), SpaceNode::edittree, ELEM, bNodeTree::id, Panel::layout, nodeGetActive(), NULL, RNA_Node, RNA_pointer_create(), uiItemO(), uiItemR(), and uiItemS().
Referenced by node_buttons_register().
static int active_node_poll (const bContext * C, PanelType * UNUSEDpt) [static]
Definition at line 79 of file node_buttons.c.
References CTX_wm_space_node(), SpaceNode::edittree, and nodeGetActive().
Referenced by node_buttons_register().
static int active_nodetree_poll (const bContext * C, PanelType * UNUSEDpt) [static]
Definition at line 71 of file node_buttons.c.
References CTX_wm_space_node(), and SpaceNode::nodetree.
Referenced by node_buttons_register().
void node_buttons_register (ARegionType * art)
Definition at line 149 of file node_buttons.c.
References active_node_panel(), active_node_poll(), active_nodetree_poll(), BLI_addtail(), PanelType::draw, PanelType::flag, gpencil_panel_standard(), PanelType::idname, IFACE_, PanelType::label, MEM_callocN(), node_sockets_panel(), node_sockets_poll(), ARegionType::paneltypes, PNL_DEFAULT_CLOSED, and PanelType::poll.
Referenced by ED_spacetype_node().
void NODE_OT_properties (wmOperatorType * ot)
Definition at line 194 of file node_buttons.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_properties(), node_properties_poll(), and wmOperatorType::poll.
Referenced by node_operatortypes().
static int node_properties (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 176 of file node_buttons.c.
References CTX_wm_area(), ED_region_toggle_hidden(), node_has_buttons_region(), and OPERATOR_FINISHED.
Referenced by NODE_OT_properties().
static int node_properties_poll (bContext * C) [static]
Definition at line 188 of file node_buttons.c.
References CTX_wm_area(), SPACE_NODE, and ScrArea::spacetype.
Referenced by NODE_OT_properties().
static void node_sockets_panel (const bContext * C, Panel * pa) [static]
Definition at line 126 of file node_buttons.c.
References BLI_snprintf(), CTX_wm_space_node(), SpaceNode::edittree, ELEM, Panel::layout, bNodeSocket::name, bNodeSocket::next, nodeGetActive(), NULL, split(), UI_MAX_NAME_STR, uiItemL(), uiLayoutSplit(), and uiTemplateNodeLink().
Referenced by node_buttons_register().
static int node_sockets_poll (const bContext * C, PanelType * UNUSEDpt) [static]
Definition at line 119 of file node_buttons.c.
References CTX_wm_space_node(), G, and SpaceNode::nodetree.
Referenced by node_buttons_register().