Blender: object_select.c File Reference
object_select.c File Reference
object
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_anim_types.h"
#include "DNA_group_types.h"
#include "DNA_material_types.h"
#include "DNA_modifier_types.h"
#include "DNA_property_types.h"
#include "DNA_scene_types.h"
#include "DNA_armature_types.h"
#include "BLI_math.h"
#include "BLI_listbase.h"
#include "BLI_rand.h"
#include "BLI_string.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_group.h"
#include "BKE_main.h"
#include "BKE_material.h"
#include "BKE_particle.h"
#include "BKE_property.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "BKE_library.h"
#include "BKE_deform.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_object.h"
#include "ED_screen.h"
#include "ED_keyframing.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "object_intern.h"
Defines
#define GROUP_MENU_MAX 24
Functions
void ED_base_object_select (Base *base, short mode)
void ED_base_object_activate (bContext *C, Base *base)
static int objects_selectable_poll (bContext *C)
static int object_select_by_type_exec (bContext *C, wmOperator *op)
void OBJECT_OT_select_by_type (wmOperatorType *ot)
static int object_select_linked_exec (bContext *C, wmOperator *op)
void OBJECT_OT_select_linked (wmOperatorType *ot)
static short select_grouped_children (bContext *C, Object *ob, int recursive)
static short select_grouped_parent (bContext *C)
static short select_grouped_group (bContext *C, Object *ob)
static short select_grouped_object_hooks (bContext *C, Object *ob)
static short select_grouped_siblings (bContext *C, Object *ob)
static short select_grouped_type (bContext *C, Object *ob)
static short select_grouped_layer (bContext *C, Object *ob)
static short select_grouped_index_object (bContext *C, Object *ob)
static short select_grouped_color (bContext *C, Object *ob)
static short objects_share_gameprop (Object *a, Object *b)
static short select_grouped_gameprops (bContext *C, Object *ob)
static short select_grouped_keyingset (bContext *C, Object *UNUSED(ob))
static int object_select_grouped_exec (bContext *C, wmOperator *op)
void OBJECT_OT_select_grouped (wmOperatorType *ot)
static int object_select_by_layer_exec (bContext *C, wmOperator *op)
void OBJECT_OT_select_by_layer (wmOperatorType *ot)
static int object_select_all_exec (bContext *C, wmOperator *op)
void OBJECT_OT_select_all (wmOperatorType *ot)
static int object_select_same_group_exec (bContext *C, wmOperator *op)
void OBJECT_OT_select_same_group (wmOperatorType *ot)
static int object_select_mirror_exec (bContext *C, wmOperator *op)
void OBJECT_OT_select_mirror (wmOperatorType *ot)
static int object_select_random_exec (bContext *C, wmOperator *op)
void OBJECT_OT_select_random (wmOperatorType *ot)
Variables
static EnumPropertyItem prop_select_linked_types []
static EnumPropertyItem prop_select_grouped_types []
Detailed Description
Definition in file object_select.c.
Define Documentation
#define GROUP_MENU_MAX 24
Definition at line 427 of file object_select.c.
Referenced by select_grouped_group().
Function Documentation
void ED_base_object_activate (bContext * C, Base * base)
Definition at line 103 of file object_select.c.
References BASACT, CTX_data_scene(), NC_SCENE, ND_OB_ACTIVE, NULL, and WM_event_add_notifier().
Referenced by add_named_exec(), convert_exec(), duplicate_exec(), ed_marker_select(), ED_object_add_type(), mouse_select(), object_hide_view_set_exec(), object_select_menu_exec(), and select_grouped_parent().
void ED_base_object_select (Base * base, short mode)
Definition at line 88 of file object_select.c.
References BA_DESELECT, BA_SELECT, Object::flag, Base::flag, OB_RESTRICT_SELECT, Base::object, Object::restrictflag, and SELECT.
Referenced by deselectall_except(), do_lasso_select_objects(), do_object_pose_box_select(), do_outliner_item_activate(), duplicate_exec(), ed_marker_select(), mesh_separate_selected(), mouse_select(), object_deselect_all_visible(), object_select_all_exec(), object_select_by_layer_exec(), object_select_by_type_exec(), object_select_grouped_exec(), object_select_linked_exec(), object_select_menu_exec(), object_select_mirror_exec(), object_select_random_exec(), object_select_same_group_exec(), object_toggle_visibility_cb(), parent_clear_invoke(), parent_drop_invoke(), restrictbutton_gr_restrict_flag(), restrictbutton_sel_cb(), restrictbutton_view_cb(), select_grouped_children(), select_grouped_color(), select_grouped_gameprops(), select_grouped_group(), select_grouped_index_object(), select_grouped_keyingset(), select_grouped_layer(), select_grouped_object_hooks(), select_grouped_parent(), select_grouped_siblings(), select_grouped_type(), separate_exec(), and view3d_circle_select_exec().
void OBJECT_OT_select_all (wmOperatorType * ot)
Definition at line 787 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_select_all_exec(), objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_properties_select_all().
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_by_layer (wmOperatorType * ot)
Definition at line 722 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_select_by_layer_exec(), objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_by_type (wmOperatorType * ot)
Definition at line 165 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_select_by_type_exec(), object_type_items, objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_grouped (wmOperatorType * ot)
Definition at line 673 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_select_grouped_exec(), objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_linked (wmOperatorType * ot)
Definition at line 347 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_select_linked_exec(), objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_mirror (wmOperatorType * ot)
Definition at line 889 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_select_mirror_exec(), objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_random (wmOperatorType * ot)
Definition at line 937 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_select_random_exec(), objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_percentage(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_same_group (wmOperatorType * ot)
Definition at line 836 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAX_ID_NAME, wmOperatorType::name, object_select_same_group_exec(), objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
static int object_select_all_exec (bContext * C, wmOperator * op) [static]
Definition at line 744 of file object_select.c.
References BA_DESELECT, BA_SELECT, CTX_DATA_BEGIN, CTX_DATA_COUNT, CTX_DATA_END, CTX_data_scene(), ED_base_object_select(), NC_SCENE, ND_OB_SELECT, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_enum_get(), SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, SELECT, and WM_event_add_notifier().
Referenced by OBJECT_OT_select_all().
static int object_select_by_layer_exec (bContext * C, wmOperator * op) [static]
Definition at line 695 of file object_select.c.
References BA_DESELECT, BA_SELECT, CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_scene(), ED_base_object_select(), NC_SCENE, ND_OB_SELECT, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_int_get(), and WM_event_add_notifier().
Referenced by OBJECT_OT_select_by_layer().
static int object_select_by_type_exec (bContext * C, wmOperator * op) [static]
Definition at line 139 of file object_select.c.
References BA_DESELECT, BA_SELECT, CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_scene(), ED_base_object_select(), NC_SCENE, ND_OB_SELECT, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_enum_get(), and WM_event_add_notifier().
Referenced by OBJECT_OT_select_by_type().
static int object_select_grouped_exec (bContext * C, wmOperator * op) [static]
Definition at line 629 of file object_select.c.
References BA_DESELECT, BKE_report(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_scene(), ED_base_object_select(), NC_SCENE, ND_OB_SELECT, NULL, OBACT, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_enum_get(), RPT_ERROR, select_grouped_children(), select_grouped_color(), select_grouped_gameprops(), select_grouped_group(), select_grouped_index_object(), select_grouped_keyingset(), select_grouped_layer(), select_grouped_object_hooks(), select_grouped_parent(), select_grouped_siblings(), select_grouped_type(), and WM_event_add_notifier().
Referenced by OBJECT_OT_select_grouped().
static int object_select_linked_exec (bContext * C, wmOperator * op) [static]
Definition at line 199 of file object_select.c.
References Object::actcol, BA_DESELECT, BKE_report(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_scene(), Object::data, Object::dup_group, ED_base_object_select(), ListBase::first, ParticleSystem::flag, give_current_material(), Library::id, Object::id, if(), ID::lib, MAX_MTEX, Material::mtex, NC_SCENE, ND_OB_SELECT, ParticleSystem::next, NULL, OBACT, OPERATOR_CANCELLED, OPERATOR_FINISHED, ParticleSystem::part, Object::particlesystem, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_enum_get(), RPT_ERROR, SELECT, MTex::tex, Material::texact, Object::totcol, and WM_event_add_notifier().
Referenced by OBJECT_OT_select_linked().
static int object_select_mirror_exec (bContext * C, wmOperator * op) [static]
Definition at line 855 of file object_select.c.
References BA_DESELECT, BA_SELECT, CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_scene(), ED_base_object_select(), find_id(), flip_side_name(), MAXBONENAME, NC_SCENE, ND_OB_SELECT, object_in_scene(), OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), TRUE, and WM_event_add_notifier().
Referenced by OBJECT_OT_select_mirror().
static int object_select_random_exec (bContext * C, wmOperator * op) [static]
Definition at line 910 of file object_select.c.
References BA_DESELECT, BA_SELECT, BLI_frand(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_scene(), ED_base_object_select(), NC_SCENE, ND_OB_SELECT, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_float_get(), and WM_event_add_notifier().
Referenced by OBJECT_OT_select_random().
static int object_select_same_group_exec (bContext * C, wmOperator * op) [static]
Definition at line 807 of file object_select.c.
References BA_SELECT, CTX_DATA_BEGIN, CTX_DATA_COUNT, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), ED_base_object_select(), Group::id, MAX_ID_NAME, ID::name, NC_SCENE, ND_OB_SELECT, ID::next, object_in_group(), OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_string_get(), SELECT, and WM_event_add_notifier().
Referenced by OBJECT_OT_select_same_group().
static int objects_selectable_poll (bContext * C) [static]
Definition at line 123 of file object_select.c.
References CTX_data_active_object(), CTX_data_edit_object(), and Object::mode.
Referenced by OBJECT_OT_select_all(), OBJECT_OT_select_by_layer(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_select_mirror(), OBJECT_OT_select_random(), and OBJECT_OT_select_same_group().
static short objects_share_gameprop (Object * a, Object * b) [static]
Definition at line 567 of file object_select.c.
References ListBase::first, get_ob_property(), bProperty::name, bProperty::next, and Object::prop.
Referenced by select_grouped_gameprops().
static short select_grouped_children (bContext * C, Object * ob, int recursive) [static]
Definition at line 385 of file object_select.c.
References BA_SELECT, CTX_DATA_BEGIN, CTX_DATA_END, ED_base_object_select(), Object::parent, and SELECT.
Referenced by object_select_grouped_exec().
static short select_grouped_color (bContext * C, Object * ob) [static]
Definition at line 553 of file object_select.c.
References BA_SELECT, Object::col, compare_v3v3(), CTX_DATA_BEGIN, CTX_DATA_END, ED_base_object_select(), and SELECT.
Referenced by object_select_grouped_exec().
static short select_grouped_gameprops (bContext * C, Object * ob) [static]
Definition at line 579 of file object_select.c.
References BA_SELECT, CTX_DATA_BEGIN, CTX_DATA_END, ED_base_object_select(), objects_share_gameprop(), and SELECT.
Referenced by object_select_grouped_exec().
static short select_grouped_group (bContext * C, Object * ob) [static]
Definition at line 428 of file object_select.c.
References BA_SELECT, CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), ED_base_object_select(), GROUP_MENU_MAX, i, Group::id, ID::name, object_in_group(), SELECT, uiItemStringO(), uiPupMenuBegin(), uiPupMenuEnd(), and uiPupMenuLayout().
Referenced by object_select_grouped_exec().
static short select_grouped_index_object (bContext * C, Object * ob) [static]
Definition at line 539 of file object_select.c.
References BA_SELECT, CTX_DATA_BEGIN, CTX_DATA_END, ED_base_object_select(), Object::index, and SELECT.
Referenced by object_select_grouped_exec().
static short select_grouped_keyingset (bContext * C, Object * UNUSEDob) [static]
Definition at line 593 of file object_select.c.
References ANIM_scene_get_active_keyingset(), ANIM_validate_keyingset(), BA_SELECT, CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_scene(), ED_base_object_select(), ListBase::first, KS_Path::id, KS_Path::next, NULL, KeyingSet::paths, and SELECT.
Referenced by object_select_grouped_exec().
static short select_grouped_layer (bContext * C, Object * ob) [static]
Definition at line 525 of file object_select.c.
References BA_SELECT, CTX_DATA_BEGIN, CTX_DATA_END, ED_base_object_select(), Object::lay, and SELECT.
Referenced by object_select_grouped_exec().
static short select_grouped_object_hooks (bContext * C, Object * ob) [static]
Definition at line 470 of file object_select.c.
References BA_SELECT, BASE_SELECTABLE, CTX_data_scene(), CTX_wm_view3d(), ED_base_object_select(), eModifierType_Hook, ListBase::first, Object::flag, Object::modifiers, ModifierData::next, HookModifierData::object, object_in_scene(), SELECT, and ModifierData::type.
Referenced by object_select_grouped_exec().
static short select_grouped_parent (bContext * C) [static]
Definition at line 404 of file object_select.c.
References BA_DESELECT, BA_SELECT, BASE_SELECTABLE, CTX_data_active_base(), CTX_data_scene(), CTX_wm_view3d(), ED_base_object_activate(), ED_base_object_select(), Base::object, object_in_scene(), and Object::parent.
Referenced by object_select_grouped_exec().
static short select_grouped_siblings (bContext * C, Object * ob) [static]
Definition at line 497 of file object_select.c.
References BA_SELECT, CTX_DATA_BEGIN, CTX_DATA_END, ED_base_object_select(), Object::parent, and SELECT.
Referenced by object_select_grouped_exec().
static short select_grouped_type (bContext * C, Object * ob) [static]
Definition at line 511 of file object_select.c.
References BA_SELECT, CTX_DATA_BEGIN, CTX_DATA_END, ED_base_object_select(), SELECT, and Object::type.
Referenced by object_select_grouped_exec().
Variable Documentation
EnumPropertyItem prop_select_grouped_types[] [static]
Initial value:
 {
    {1, "CHILDREN_RECURSIVE", 0, "Children", ""},
    {2, "CHILDREN", 0, "Immediate Children", ""},
    {3, "PARENT", 0, "Parent", ""},
    {4, "SIBLINGS", 0, "Siblings", "Shared Parent"},
    {5, "TYPE", 0, "Type", "Shared object type"},
    {6, "LAYER", 0, "Layer", "Shared layers"},
    {7, "GROUP", 0, "Group", "Shared group"},
    {8, "HOOK", 0, "Hook", ""},
    {9, "PASS", 0, "Pass", "Render pass Index"},
    {10, "COLOR", 0, "Color", "Object Color"},
    {11, "PROPERTIES", 0, "Properties", "Game Properties"},
    {12, "KEYINGSET", 0, "Keying Set", "Objects included in active Keying Set"},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 369 of file object_select.c.
Referenced by POSE_OT_select_grouped().
EnumPropertyItem prop_select_linked_types[] [static]
Initial value:
 {
    {2, "OBDATA", 0, "Object Data", ""},
    {3, "MATERIAL", 0, "Material", ""},
    {4, "TEXTURE", 0, "Texture", ""},
    {5, "DUPGROUP", 0, "Dupligroup", ""},
    {6, "PARTICLE", 0, "Particle System", ""},
    {7, "LIBRARY", 0, "Library", ""},
    {8, "LIBRARY_OBDATA", 0, "Library (Object Data)", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 187 of file object_select.c.