Blender: kernel_path.h File Reference
kernel_path.h File Reference
#include "kernel_differential.h"
#include "kernel_montecarlo.h"
#include "kernel_triangle.h"
#include "kernel_object.h"
#include "kernel_bvh.h"
#include "kernel_accumulate.h"
#include "kernel_camera.h"
#include "kernel_shader.h"
#include "kernel_light.h"
#include "kernel_emission.h"
#include "kernel_random.h"
#include "kernel_passes.h"
Classes
struct PathState
Typedefs
typedef CCL_NAMESPACE_BEGIN
struct PathState PathState
Functions
__device_inline void path_state_init (PathState *state)
__device_inline void path_state_next (KernelGlobals *kg, PathState *state, int label)
__device_inline uint path_state_ray_visibility (KernelGlobals *kg, PathState *state)
__device_inline float path_state_terminate_probability (KernelGlobals *kg, PathState *state, const float3 throughput)
__device_inline bool shadow_blocked (KernelGlobals *kg, PathState *state, Ray *ray, float3 *shadow)
__device float4 kernel_path_integrate (KernelGlobals *kg, RNG *rng, int sample, Ray ray, __global float *buffer)
__device void kernel_path_trace (KernelGlobals *kg, __global float *buffer, __global uint *rng_state, int sample, int x, int y, int offset, int stride)
Typedef Documentation
typedef CCL_NAMESPACE_BEGIN struct PathState PathState
Function Documentation
__device float4 kernel_path_integrate (KernelGlobals * kg, RNG * rng, int sample, Ray ray, __global float * buffer)
Definition at line 217 of file kernel_path.h.
References average(), PathState::bounce, bsdf_eval_is_zero(), Ray::D, Ray::dD, direct_emission(), dot(), ShaderData::dP, Ray::dP, emission(), PathState::flag, ShaderData::flag, FLT_MAX, i, indirect_background(), indirect_emission(), kernel_data, kernel_write_data_passes(), kernel_write_light_passes(), L, label(), LABEL_TRANSMIT, LABEL_TRANSPARENT, make_float3(), make_float4(), ShaderData::N, ShaderData::Ng, Ray::P, ShaderData::P, path_radiance_accum_ao(), path_radiance_accum_background(), path_radiance_accum_emission(), path_radiance_accum_light(), path_radiance_bsdf_bounce(), path_radiance_clamp(), path_radiance_init(), path_radiance_sum(), PATH_RAY_CAMERA, path_rng(), path_state_init(), path_state_next(), path_state_ray_visibility(), path_state_terminate_probability(), PRNG_BASE_NUM, PRNG_BOUNCE_NUM, PRNG_BSDF, PRNG_BSDF_U, PRNG_BSDF_V, PRNG_LIGHT, PRNG_LIGHT_F, PRNG_LIGHT_U, PRNG_LIGHT_V, PRNG_TERMINATE, ray_offset(), sample_cos_hemisphere(), scene_intersect(), SD_BSDF, SD_BSDF_HAS_EVAL, SD_EMISSION, SD_HOLDOUT, shader_bsdf_diffuse(), shader_bsdf_sample(), shader_eval_surface(), shader_holdout_eval(), shader_release(), shader_setup_from_ray(), shadow_blocked(), state, Intersection::t, Ray::t, float3::x, float3::y, and float3::z.
Referenced by kernel_path_trace().
__device void kernel_path_trace (KernelGlobals * kg, __global float * buffer, __global uint * rng_state, int sample, int x, int y, int offset, int stride)
Definition at line 408 of file kernel_path.h.
References camera_sample(), kernel_data, kernel_path_integrate(), kernel_write_pass_float4(), L, path_rng(), path_rng_end(), path_rng_init(), PRNG_LENS_U, and PRNG_LENS_V.
Referenced by kernel_cpu_path_trace().
__device_inline void path_state_init (PathState * state)
Definition at line 48 of file kernel_path.h.
References PathState::bounce, PathState::diffuse_bounce, PathState::flag, PathState::glossy_bounce, PATH_RAY_CAMERA, PATH_RAY_MIS_SKIP, PATH_RAY_SINGULAR, PathState::transmission_bounce, and PathState::transparent_bounce.
Referenced by kernel_path_integrate().
__device_inline void path_state_next (KernelGlobals * kg, PathState * state, int label)
Definition at line 58 of file kernel_path.h.
References PathState::bounce, PathState::diffuse_bounce, PathState::flag, PathState::glossy_bounce, kernel_assert, kernel_data, LABEL_DIFFUSE, LABEL_GLOSSY, LABEL_REFLECT, LABEL_SINGULAR, LABEL_TRANSMIT, LABEL_TRANSPARENT, PATH_RAY_CAMERA, PATH_RAY_DIFFUSE, PATH_RAY_GLOSSY, PATH_RAY_MIS_SKIP, PATH_RAY_REFLECT, PATH_RAY_SINGULAR, PATH_RAY_TRANSMIT, PATH_RAY_TRANSPARENT, PathState::transmission_bounce, and PathState::transparent_bounce.
Referenced by kernel_path_integrate().
__device_inline uint path_state_ray_visibility (KernelGlobals * kg, PathState * state)
Definition at line 110 of file kernel_path.h.
References PathState::flag, kernel_data, PATH_RAY_CAMERA, PATH_RAY_DIFFUSE, PATH_RAY_GLOSSY, and PATH_RAY_TRANSMIT.
Referenced by kernel_path_integrate().
__device_inline float path_state_terminate_probability (KernelGlobals * kg, PathState * state, const float3 throughput)
Definition at line 124 of file kernel_path.h.
References average(), PathState::bounce, PathState::diffuse_bounce, PathState::flag, PathState::glossy_bounce, kernel_data, PATH_RAY_TRANSPARENT, PathState::transmission_bounce, and PathState::transparent_bounce.
Referenced by kernel_path_integrate().
__device_inline bool shadow_blocked (KernelGlobals * kg, PathState * state, Ray * ray, float3 * shadow)
Definition at line 148 of file kernel_path.h.
References average(), Ray::D, FLT_MAX, kernel_data, make_float3(), ShaderData::Ng, normalize_len(), Ray::P, ShaderData::P, PATH_RAY_SHADOW, PATH_RAY_SHADOW_OPAQUE, PATH_RAY_SHADOW_TRANSPARENT, ray_offset(), scene_intersect(), shader_bsdf_transparency(), shader_eval_surface(), shader_setup_from_ray(), Ray::t, and PathState::transparent_bounce.
Referenced by kernel_path_integrate().