Blender: ED_space_api.h File Reference
ED_space_api.h File Reference
Editors
Defines
#define REGION_DRAW_POST_VIEW 0
#define REGION_DRAW_POST_PIXEL 1
#define REGION_DRAW_PRE_VIEW 2
Functions
void ED_spacetype_outliner (void)
void ED_spacetype_time (void)
void ED_spacetype_view3d (void)
void ED_spacetype_ipo (void)
void ED_spacetype_image (void)
void ED_spacetype_node (void)
void ED_spacetype_buttons (void)
void ED_spacetype_info (void)
void ED_spacetype_file (void)
void ED_spacetype_action (void)
void ED_spacetype_nla (void)
void ED_spacetype_script (void)
void ED_spacetype_text (void)
void ED_spacetype_sequencer (void)
void ED_spacetype_logic (void)
void ED_spacetype_console (void)
void ED_spacetype_userpref (void)
void ED_spacetype_clip (void)
void ED_file_init (void)
void ED_file_exit (void)
void * ED_region_draw_cb_activate (struct ARegionType *, void(*draw)(const struct bContext *, struct ARegion *, void *), void *custumdata, int type)
void ED_region_draw_cb_draw (const struct bContext *, struct ARegion *, int)
void ED_region_draw_cb_exit (struct ARegionType *, void *)
void * ED_region_draw_cb_customdata (void *handle)
Detailed Description
Definition in file ED_space_api.h.
Define Documentation
#define REGION_DRAW_POST_PIXEL 1
Definition at line 66 of file ED_space_api.h.
Referenced by ED_region_do_draw(), image_sample_invoke(), initFlyInfo(), pyrna_callback_add(), and sample_invoke().
#define REGION_DRAW_POST_VIEW 0
Definition at line 65 of file ED_space_api.h.
Referenced by image_main_area_draw(), initTransform(), knifetool_init(), pyrna_callback_add(), ringsel_init(), view3d_main_area_draw_objects(), and vtx_slide_init().
#define REGION_DRAW_PRE_VIEW 2
Definition at line 67 of file ED_space_api.h.
Referenced by initTransform(), pyrna_callback_add(), and view3d_main_area_draw_objects().
Function Documentation
void ED_file_exit (void)
Definition at line 628 of file space_file.c.
References filelist_free_icons(), fsmenu_free(), and fsmenu_get().
Referenced by WM_exit_ext().
void ED_file_init (void)
Definition at line 612 of file space_file.c.
References BLENDER_BOOKMARK_FILE, BLENDER_USER_CONFIG, BLI_get_folder(), BLI_make_file_string(), FILE_MAX, filelist_init_icons(), fsmenu_get(), fsmenu_read_bookmarks(), fsmenu_read_system(), IMB_thumb_makedirs(), and NULL.
Referenced by WM_init().
void* ED_region_draw_cb_activate (struct ARegionType * , void(*)(const struct bContext *, struct ARegion *, void *) draw, void * custumdata, int type)
Definition at line 194 of file spacetypes.c.
References BLI_addtail(), RegionDrawCB::customdata, RegionDrawCB::draw, ARegionType::drawcalls, MEM_callocN(), ARegion::type, and RegionDrawCB::type.
Referenced by image_sample_invoke(), initFlyInfo(), initTransform(), knifetool_init(), pyrna_callback_add(), ringsel_init(), sample_invoke(), and vtx_slide_init().
void* ED_region_draw_cb_customdata (void * handle)
Definition at line 221 of file spacetypes.c.
Referenced by pyrna_callback_remove().
void ED_region_draw_cb_draw (const struct bContext * , struct ARegion * , int)
Referenced by ED_region_do_draw(), image_main_area_draw(), and view3d_main_area_draw_objects().
void ED_region_draw_cb_exit (struct ARegionType * , void *)
Definition at line 208 of file spacetypes.c.
References BLI_remlink(), ARegionType::drawcalls, ListBase::first, MEM_freeN(), and RegionDrawCB::next.
Referenced by flyEnd(), image_sample_exit(), knifetool_exit(), postTrans(), pyrna_callback_remove(), ringsel_exit(), sample_exit(), and vtx_slide_exit().
void ED_spacetype_action (void)
Definition at line 465 of file space_action.c.
References action_channel_area_draw(), action_channel_area_init(), action_channel_area_listener(), action_duplicate(), action_free(), action_header_area_draw(), action_header_area_init(), action_header_area_listener(), action_init(), action_keymap(), action_listener(), action_main_area_draw(), action_main_area_init(), action_main_area_listener(), action_new(), action_operatortypes(), action_refresh(), BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_ANIMATION, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_MARKERS, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_CHANNELS, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_ACTION, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
void ED_spacetype_buttons (void)
Definition at line 380 of file space_buttons.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), buttons_area_listener(), buttons_context(), buttons_context_register(), buttons_duplicate(), buttons_free(), buttons_header_area_draw(), buttons_header_area_init(), buttons_init(), buttons_keymap(), buttons_main_area_draw(), buttons_main_area_init(), buttons_new(), buttons_operatortypes(), SpaceType::context, ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizey, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_BUTS, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
void ED_spacetype_clip (void)
Definition at line 959 of file space_clip.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), clip_context(), clip_duplicate(), clip_free(), clip_header_area_draw(), clip_header_area_init(), clip_init(), clip_keymap(), clip_listener(), clip_main_area_draw(), clip_main_area_init(), clip_main_area_listener(), clip_new(), clip_operatortypes(), clip_preview_area_draw(), clip_preview_area_init(), clip_preview_area_listener(), clip_properties_area_draw(), clip_properties_area_init(), clip_properties_area_listener(), clip_props_area_listener(), clip_refresh(), clip_tools_area_draw(), clip_tools_area_init(), SpaceType::context, ARegionType::draw, SpaceType::duplicate, ED_clip_buttons_register(), ED_clip_tool_props_register(), ED_KEYMAP_FRAMES, ED_KEYMAP_GPENCIL, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_PREVIEW, RGN_TYPE_TOOL_PROPS, RGN_TYPE_TOOLS, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_CLIP, SpaceType::spaceid, and UI_COMPACT_PANEL_WIDTH.
Referenced by ED_spacetypes_init().
void ED_spacetype_console (void)
Definition at line 364 of file space_console.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), console_dropboxes(), console_duplicate(), console_free(), console_header_area_draw(), console_header_area_init(), console_init(), console_keymap(), console_main_area_draw(), console_main_area_init(), console_main_area_listener(), console_new(), console_operatortypes(), ARegionType::draw, SpaceType::dropboxes, SpaceType::duplicate, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizey, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_CONSOLE, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
void ED_spacetype_file (void)
Definition at line 551 of file space_file.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, file_channel_area_draw(), file_channel_area_init(), file_channel_area_listener(), file_duplicate(), file_free(), file_header_area_draw(), file_header_area_init(), file_init(), file_keymap(), file_listener(), file_main_area_draw(), file_main_area_init(), file_main_area_listener(), file_new(), file_operatortypes(), file_panels_register(), file_refresh(), file_ui_area_draw(), file_ui_area_init(), file_ui_area_listener(), SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_CHANNELS, RGN_TYPE_HEADER, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_FILE, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
void ED_spacetype_image (void)
Definition at line 981 of file space_image.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), SpaceType::context, ARegionType::draw, SpaceType::dropboxes, SpaceType::duplicate, ED_KEYMAP_FRAMES, ED_KEYMAP_GPENCIL, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, ED_uvedit_buttons_register(), SpaceType::free, HEADERY, image_buttons_area_draw(), image_buttons_area_init(), image_buttons_area_listener(), image_buttons_register(), image_context(), image_dropboxes(), image_duplicate(), image_free(), image_header_area_draw(), image_header_area_init(), image_header_area_listener(), image_init(), image_keymap(), image_listener(), image_main_area_draw(), image_main_area_init(), image_main_area_listener(), image_new(), image_operatortypes(), image_refresh(), image_scope_area_draw(), image_scope_area_init(), image_scope_area_listener(), ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_PREVIEW, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_IMAGE, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
void ED_spacetype_info (void)
Definition at line 298 of file space_info.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, info_duplicate(), info_free(), info_header_area_draw(), info_header_area_init(), info_header_listener(), info_init(), info_keymap(), info_main_area_draw(), info_main_area_init(), info_main_area_listener(), info_new(), info_operatortypes(), ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizey, recent_files_menu_register(), ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_INFO, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
void ED_spacetype_ipo (void)
Definition at line 591 of file space_graph.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_ANIMATION, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_MARKERS, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, graph_buttons_area_draw(), graph_buttons_area_init(), graph_buttons_register(), graph_channel_area_draw(), graph_channel_area_init(), graph_duplicate(), graph_free(), graph_header_area_draw(), graph_header_area_init(), graph_init(), graph_listener(), graph_main_area_draw(), graph_main_area_init(), graph_new(), graph_refresh(), graph_region_listener(), graphedit_keymap(), graphedit_operatortypes(), HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_CHANNELS, RGN_TYPE_HEADER, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_IPO, SpaceType::spaceid, and V2D_SCROLL_WIDTH.
Referenced by ED_spacetypes_init().
void ED_spacetype_logic (void)
Definition at line 303 of file space_logic.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), SpaceType::context, ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, logic_buttons_area_draw(), logic_buttons_area_init(), logic_context(), logic_duplicate(), logic_free(), logic_header_area_draw(), logic_header_area_init(), logic_init(), logic_keymap(), logic_listener(), logic_main_area_draw(), logic_main_area_init(), logic_new(), logic_operatortypes(), logic_refresh(), MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_LOGIC, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
void ED_spacetype_nla (void)
Definition at line 497 of file space_nla.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_ANIMATION, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_MARKERS, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, nla_buttons_area_draw(), nla_buttons_area_init(), nla_buttons_register(), nla_channel_area_draw(), nla_channel_area_init(), nla_channel_area_listener(), nla_duplicate(), nla_free(), nla_header_area_draw(), nla_header_area_init(), nla_init(), nla_keymap(), nla_listener(), nla_main_area_draw(), nla_main_area_init(), nla_main_area_listener(), nla_new(), nla_operatortypes(), nla_region_listener(), SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_CHANNELS, RGN_TYPE_HEADER, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_NLA, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
void ED_spacetype_node (void)
Definition at line 500 of file space_node.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), SpaceType::context, ARegionType::draw, SpaceType::dropboxes, SpaceType::duplicate, ED_KEYMAP_FRAMES, ED_KEYMAP_GPENCIL, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, node_area_listener(), node_area_refresh(), node_buttons_area_draw(), node_buttons_area_init(), node_buttons_register(), node_context(), node_dropboxes(), node_duplicate(), node_free(), node_header_area_draw(), node_header_area_init(), node_init(), node_keymap(), node_main_area_draw(), node_main_area_init(), node_menus_register(), node_new(), node_operatortypes(), node_region_listener(), SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_NODE, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
void ED_spacetype_outliner (void)
Definition at line 377 of file space_outliner.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::dropboxes, SpaceType::duplicate, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, ARegionType::free, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, outliner_dropboxes(), outliner_duplicate(), outliner_free(), outliner_header_area_draw(), outliner_header_area_free(), outliner_header_area_init(), outliner_header_area_listener(), outliner_init(), outliner_keymap(), outliner_main_area_draw(), outliner_main_area_free(), outliner_main_area_init(), outliner_main_area_listener(), outliner_new(), outliner_operatortypes(), ARegionType::prefsizey, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_OUTLINER, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
void ED_spacetype_script (void)
Definition at line 190 of file space_script.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizey, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, script_duplicate(), script_free(), script_header_area_draw(), script_header_area_init(), script_init(), script_keymap(), script_main_area_draw(), script_main_area_init(), script_main_area_listener(), script_new(), script_operatortypes(), SPACE_SCRIPT, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
void ED_spacetype_sequencer (void)
Definition at line 527 of file space_sequencer.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::dropboxes, SpaceType::duplicate, ED_KEYMAP_ANIMATION, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_MARKERS, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, ED_view3d_draw_offscreen_imbuf_simple(), SpaceType::free, G, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_PREVIEW, RGN_TYPE_UI, RGN_TYPE_WINDOW, sequencer_buttons_area_draw(), sequencer_buttons_area_init(), sequencer_buttons_area_listener(), sequencer_dropboxes(), sequencer_duplicate(), sequencer_free(), sequencer_header_area_draw(), sequencer_header_area_init(), sequencer_init(), sequencer_keymap(), sequencer_main_area_draw(), sequencer_main_area_init(), sequencer_main_area_listener(), sequencer_new(), sequencer_operatortypes(), sequencer_preview_area_draw(), sequencer_preview_area_init(), sequencer_preview_area_listener(), sequencer_refresh(), sequencer_view3d_cb, SPACE_SEQ, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
void ED_spacetype_text (void)
Definition at line 508 of file space_text.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), SpaceType::context, ARegionType::cursor, ARegionType::draw, SpaceType::dropboxes, SpaceType::duplicate, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_TEXT, SpaceType::spaceid, text_context(), text_cursor(), text_dropboxes(), text_duplicate(), text_free(), text_header_area_draw(), text_header_area_init(), text_init(), text_keymap(), text_listener(), text_main_area_draw(), text_main_area_init(), text_new(), text_operatortypes(), text_properties_area_draw(), text_properties_area_init(), and UI_COMPACT_PANEL_WIDTH.
Referenced by ED_spacetypes_init().
void ED_spacetype_time (void)
Definition at line 661 of file space_time.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_ANIMATION, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_MARKERS, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, ARegionType::keymap, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, NULL, SpaceType::operatortypes, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_TIME, SpaceType::spaceid, time_duplicate(), time_free(), time_header_area_draw(), time_header_area_init(), time_header_area_listener(), time_init(), time_keymap(), time_listener(), time_main_area_draw(), time_main_area_init(), time_main_area_listener(), time_new(), time_operatortypes(), and time_refresh().
Referenced by ED_spacetypes_init().
void ED_spacetype_userpref (void)
Definition at line 156 of file space_userpref.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizey, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_USERPREF, SpaceType::spaceid, userpref_duplicate(), userpref_free(), userpref_header_area_draw(), userpref_header_area_init(), userpref_header_listener(), userpref_init(), userpref_keymap(), userpref_main_area_draw(), userpref_main_area_init(), userpref_main_area_listener(), userpref_new(), and userpref_operatortypes().
Referenced by ED_spacetypes_init().
void ED_spacetype_view3d (void)
Definition at line 1141 of file space_view3d.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), SpaceType::context, ARegionType::cursor, ARegionType::draw, SpaceType::dropboxes, ARegionType::duplicate, SpaceType::duplicate, ED_KEYMAP_FRAMES, ED_KEYMAP_GPENCIL, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, ARegionType::free, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, ARegionType::lock, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_TOOL_PROPS, RGN_TYPE_TOOLS, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_VIEW3D, space_view3d_listener(), SpaceType::spaceid, view3d_buttons_area_draw(), view3d_buttons_area_init(), view3d_buttons_area_listener(), view3d_buttons_register(), view3d_context(), view3d_dropboxes(), view3d_duplicate(), view3d_free(), view3d_header_area_draw(), view3d_header_area_init(), view3d_header_area_listener(), view3d_init(), view3d_keymap(), view3d_main_area_cursor(), view3d_main_area_draw(), view3d_main_area_duplicate(), view3d_main_area_free(), view3d_main_area_init(), view3d_main_area_listener(), view3d_new(), view3d_operatortypes(), view3d_props_area_listener(), view3d_tool_props_register(), view3d_tools_area_draw(), view3d_tools_area_init(), and view3d_toolshelf_register().
Referenced by ED_spacetypes_init().