Blender: outliner_tools.c File Reference
outliner_tools.c File Reference
outliner space
#include "MEM_guardedalloc.h"
#include "DNA_anim_types.h"
#include "DNA_armature_types.h"
#include "DNA_group_types.h"
#include "DNA_lamp_types.h"
#include "DNA_material_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meta_types.h"
#include "DNA_scene_types.h"
#include "DNA_world_types.h"
#include "DNA_object_types.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_animsys.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_fcurve.h"
#include "BKE_group.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "ED_armature.h"
#include "ED_object.h"
#include "ED_screen.h"
#include "ED_util.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_view2d.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "outliner_intern.h"
Typedefs
typedef enum eOutlinerIdOpTypes eOutlinerIdOpTypes
typedef enum eOutliner_AnimDataOps eOutliner_AnimDataOps
Enumerations
enum eOutlinerIdOpTypes {
OUTLINER_IDOP_INVALID = 0, OUTLINER_IDOP_UNLINK, OUTLINER_IDOP_LOCAL, OUTLINER_IDOP_SINGLE,
OUTLINER_IDOP_FAKE_ADD, OUTLINER_IDOP_FAKE_CLEAR, OUTLINER_IDOP_RENAME
}
enum eOutliner_AnimDataOps {
OUTLINER_ANIMOP_INVALID = 0, OUTLINER_ANIMOP_SET_ACT, OUTLINER_ANIMOP_CLEAR_ACT, OUTLINER_ANIMOP_REFRESH_DRV,
OUTLINER_ANIMOP_CLEAR_DRV
}
Functions
static void set_operation_types (SpaceOops *soops, ListBase *lb, int *scenelevel, int *objectlevel, int *idlevel, int *datalevel)
static void unlink_action_cb (bContext *C, Scene *UNUSED(scene), TreeElement *UNUSED(te), TreeStoreElem *tsep, TreeStoreElem *UNUSED(tselem))
static void unlink_material_cb (bContext *UNUSED(C), Scene *UNUSED(scene), TreeElement *te, TreeStoreElem *tsep, TreeStoreElem *UNUSED(tselem))
static void unlink_texture_cb (bContext *UNUSED(C), Scene *UNUSED(scene), TreeElement *te, TreeStoreElem *tsep, TreeStoreElem *UNUSED(tselem))
static void unlink_group_cb (bContext *UNUSED(C), Scene *UNUSED(scene), TreeElement *UNUSED(te), TreeStoreElem *tsep, TreeStoreElem *tselem)
static void unlink_world_cb (bContext *UNUSED(C), Scene *UNUSED(scene), TreeElement *UNUSED(te), TreeStoreElem *tsep, TreeStoreElem *tselem)
static void outliner_do_libdata_operation (bContext *C, Scene *scene, SpaceOops *soops, ListBase *lb, void(*operation_cb)(bContext *C, Scene *scene, TreeElement *, TreeStoreElem *, TreeStoreElem *))
static void object_select_cb (bContext *UNUSED(C), Scene *scene, TreeElement *te, TreeStoreElem *UNUSED(tsep), TreeStoreElem *tselem)
static void object_deselect_cb (bContext *UNUSED(C), Scene *scene, TreeElement *te, TreeStoreElem *UNUSED(tsep), TreeStoreElem *tselem)
static void object_delete_cb (bContext *C, Scene *scene, TreeElement *te, TreeStoreElem *UNUSED(tsep), TreeStoreElem *tselem)
static void id_local_cb (bContext *C, Scene *UNUSED(scene), TreeElement *UNUSED(te), TreeStoreElem *UNUSED(tsep), TreeStoreElem *tselem)
static void id_fake_user_set_cb (bContext *UNUSED(C), Scene *UNUSED(scene), TreeElement *UNUSED(te), TreeStoreElem *UNUSED(tsep), TreeStoreElem *tselem)
static void id_fake_user_clear_cb (bContext *UNUSED(C), Scene *UNUSED(scene), TreeElement *UNUSED(te), TreeStoreElem *UNUSED(tsep), TreeStoreElem *tselem)
static void singleuser_action_cb (bContext *C, Scene *UNUSED(scene), TreeElement *UNUSED(te), TreeStoreElem *tsep, TreeStoreElem *tselem)
static void singleuser_world_cb (bContext *C, Scene *UNUSED(scene), TreeElement *UNUSED(te), TreeStoreElem *tsep, TreeStoreElem *tselem)
static void group_linkobs2scene_cb (bContext *UNUSED(C), Scene *scene, TreeElement *UNUSED(te), TreeStoreElem *UNUSED(tsep), TreeStoreElem *tselem)
void outliner_do_object_operation (bContext *C, Scene *scene_act, SpaceOops *soops, ListBase *lb, void(*operation_cb)(bContext *C, Scene *scene, TreeElement *, TreeStoreElem *, TreeStoreElem *))
static void unlinkact_animdata_cb (int UNUSED(event), TreeElement *UNUSED(te), TreeStoreElem *tselem)
static void cleardrivers_animdata_cb (int UNUSED(event), TreeElement *UNUSED(te), TreeStoreElem *tselem)
static void refreshdrivers_animdata_cb (int UNUSED(event), TreeElement *UNUSED(te), TreeStoreElem *tselem)
static void pchan_cb (int event, TreeElement *te, TreeStoreElem *UNUSED(tselem))
static void bone_cb (int event, TreeElement *te, TreeStoreElem *UNUSED(tselem))
static void ebone_cb (int event, TreeElement *te, TreeStoreElem *UNUSED(tselem))
static void sequence_cb (int event, TreeElement *UNUSED(te), TreeStoreElem *UNUSED(tselem))
static void outliner_do_data_operation (SpaceOops *soops, int type, int event, ListBase *lb, void(*operation_cb)(int, TreeElement *, TreeStoreElem *))
static int outliner_object_operation_exec (bContext *C, wmOperator *op)
void OUTLINER_OT_object_operation (wmOperatorType *ot)
static int outliner_group_operation_exec (bContext *C, wmOperator *op)
void OUTLINER_OT_group_operation (wmOperatorType *ot)
static int outliner_id_operation_exec (bContext *C, wmOperator *op)
void OUTLINER_OT_id_operation (wmOperatorType *ot)
static void outliner_do_id_set_operation (SpaceOops *soops, int type, ListBase *lb, ID *newid, void(*operation_cb)(TreeElement *, TreeStoreElem *, TreeStoreElem *, ID *))
static void actionset_id_cb (TreeElement *UNUSED(te), TreeStoreElem *tselem, TreeStoreElem *tsep, ID *actId)
static int outliner_action_set_exec (bContext *C, wmOperator *op)
void OUTLINER_OT_action_set (wmOperatorType *ot)
static int outliner_animdata_operation_exec (bContext *C, wmOperator *op)
void OUTLINER_OT_animdata_operation (wmOperatorType *ot)
static int outliner_data_operation_exec (bContext *C, wmOperator *op)
void OUTLINER_OT_data_operation (wmOperatorType *ot)
static int do_outliner_operation_event (bContext *C, Scene *scene, ARegion *ar, SpaceOops *soops, TreeElement *te, wmEvent *event, const float mval[2])
static int outliner_operation (bContext *C, wmOperator *UNUSED(op), wmEvent *event)
void OUTLINER_OT_operation (wmOperatorType *ot)
Variables
static EnumPropertyItem prop_object_op_types []
static EnumPropertyItem prop_group_op_types []
static EnumPropertyItem prop_id_op_types []
static EnumPropertyItem prop_animdata_op_types []
static EnumPropertyItem prop_data_op_types []
Detailed Description
Definition in file outliner_tools.c.
Typedef Documentation
typedef enum eOutliner_AnimDataOps eOutliner_AnimDataOps
typedef enum eOutlinerIdOpTypes eOutlinerIdOpTypes
Enumeration Type Documentation
enum eOutliner_AnimDataOps
Enumerator:
OUTLINER_ANIMOP_INVALID
OUTLINER_ANIMOP_SET_ACT
OUTLINER_ANIMOP_CLEAR_ACT
OUTLINER_ANIMOP_REFRESH_DRV
OUTLINER_ANIMOP_CLEAR_DRV
Definition at line 967 of file outliner_tools.c.
enum eOutlinerIdOpTypes
Enumerator:
OUTLINER_IDOP_INVALID
OUTLINER_IDOP_UNLINK
OUTLINER_IDOP_LOCAL
OUTLINER_IDOP_SINGLE
OUTLINER_IDOP_FAKE_ADD
OUTLINER_IDOP_FAKE_CLEAR
OUTLINER_IDOP_RENAME
Definition at line 689 of file outliner_tools.c.
Function Documentation
static void actionset_id_cb (TreeElement * UNUSEDte, TreeStoreElem * tselem, TreeStoreElem * tsep, ID * actId) [static]
Definition at line 881 of file outliner_tools.c.
References BKE_animdata_set_action(), TreeStoreElem::id, NULL, TSE_ANIM_DATA, and TreeStoreElem::type.
Referenced by outliner_action_set_exec().
static void bone_cb (int event, TreeElement * te, TreeStoreElem * UNUSEDtselem) [static]
Definition at line 445 of file outliner_tools.c.
References BONE_HIDDEN_P, BONE_SELECTED, TreeElement::directdata, Bone::flag, and if().
Referenced by outliner_data_operation_exec().
static void cleardrivers_animdata_cb (int UNUSEDevent, TreeElement * UNUSEDte, TreeStoreElem * tselem) [static]
Definition at line 405 of file outliner_tools.c.
References IdAdtTemplate::adt, AnimData::drivers, free_fcurves(), and TreeStoreElem::id.
Referenced by outliner_animdata_operation_exec().
static int do_outliner_operation_event (bContext * C, Scene * scene, ARegion * ar, SpaceOops * soops, TreeElement * te, wmEvent * event, const float mval[2]) [static]
Definition at line 1150 of file outliner_tools.c.
References BKE_report(), CTX_wm_reports(), ED_region_tag_redraw(), ELEM3, ListBase::first, TreeStoreElem::flag, ID_GR, TreeElement::next, NULL, outliner_has_one_flag(), outliner_set_flag(), RPT_WARNING, set_operation_types(), SO_TREESTORE_REDRAW, SpaceOops::storeflag, TreeElement::subtree, SpaceOops::tree, TREESTORE, TSE_ANIM_DATA, TSE_DRIVER_BASE, TSE_R_LAYER, TSE_R_LAYER_BASE, TSE_R_PASS, TSE_SELECTED, UI_UNIT_Y, WM_OP_INVOKE_REGION_WIN, WM_operator_name_call(), and TreeElement::ys.
Referenced by outliner_operation().
static void ebone_cb (int event, TreeElement * te, TreeStoreElem * UNUSEDtselem) [static]
Definition at line 461 of file outliner_tools.c.
References BONE_HIDDEN_A, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, TreeElement::directdata, EditBone::flag, and if().
Referenced by outliner_data_operation_exec().
static void group_linkobs2scene_cb (bContext * UNUSEDC, Scene * scene, TreeElement * UNUSEDte, TreeStoreElem * UNUSEDtsep, TreeStoreElem * tselem) [static]
Definition at line 345 of file outliner_tools.c.
References Scene::base, BLI_addhead(), ListBase::first, Group::gobject, TreeStoreElem::id, id_lib_extern(), MEM_callocN(), object_in_scene(), and SELECT.
Referenced by outliner_group_operation_exec().
static void id_fake_user_clear_cb (bContext * UNUSEDC, Scene * UNUSEDscene, TreeElement * UNUSEDte, TreeStoreElem * UNUSEDtsep, TreeStoreElem * tselem) [static]
Definition at line 302 of file outliner_tools.c.
References ID::flag, TreeStoreElem::id, id_us_min(), and LIB_FAKEUSER.
Referenced by outliner_id_operation_exec().
static void id_fake_user_set_cb (bContext * UNUSEDC, Scene * UNUSEDscene, TreeElement * UNUSEDte, TreeStoreElem * UNUSEDtsep, TreeStoreElem * tselem) [static]
Definition at line 292 of file outliner_tools.c.
References ID::flag, TreeStoreElem::id, id_us_plus(), and LIB_FAKEUSER.
Referenced by outliner_id_operation_exec().
static void id_local_cb (bContext * C, Scene * UNUSEDscene, TreeElement * UNUSEDte, TreeStoreElem * UNUSEDtsep, TreeStoreElem * tselem) [static]
Definition at line 280 of file outliner_tools.c.
References CTX_data_main(), FALSE, ID::flag, TreeStoreElem::id, id_clear_lib_data(), id_make_local(), ID::lib, and LIB_EXTERN.
Referenced by outliner_group_operation_exec(), outliner_id_operation_exec(), and outliner_object_operation_exec().
static void object_delete_cb (bContext * C, Scene * scene, TreeElement * te, TreeStoreElem * UNUSEDtsep, TreeStoreElem * tselem) [static]
Definition at line 263 of file outliner_tools.c.
References CTX_data_main(), TreeElement::directdata, ED_base_object_free_and_unlink(), ED_object_exit_editmode(), EM_DO_UNDO, EM_FREEDATA, EM_FREEUNDO, EM_WAITCURSOR, TreeStoreElem::id, if(), NULL, Scene::obedit, Base::object, and object_in_scene().
Referenced by outliner_object_operation_exec().
static void object_deselect_cb (bContext * UNUSEDC, Scene * scene, TreeElement * te, TreeStoreElem * UNUSEDtsep, TreeStoreElem * tselem) [static]
Definition at line 252 of file outliner_tools.c.
References TreeElement::directdata, Object::flag, Base::flag, TreeStoreElem::id, if(), NULL, Base::object, object_in_scene(), and SELECT.
Referenced by outliner_object_operation_exec().
static void object_select_cb (bContext * UNUSEDC, Scene * scene, TreeElement * te, TreeStoreElem * UNUSEDtsep, TreeStoreElem * tselem) [static]
Definition at line 241 of file outliner_tools.c.
References TreeElement::directdata, Object::flag, Base::flag, TreeStoreElem::id, if(), NULL, OB_RESTRICT_VIEW, Base::object, object_in_scene(), Object::restrictflag, and SELECT.
Referenced by outliner_object_operation_exec().
static int outliner_action_set_exec (bContext * C, wmOperator * op) [static]
Definition at line 899 of file outliner_tools.c.
References actionset_id_cb(), BKE_report(), BKE_reportf(), BLI_findlink(), CTX_data_main(), CTX_wm_space_outliner(), ED_undo_push(), bAction::id, ID_AC, bAction::idroot, ID::name, NC_ANIMATION, ND_NLA_ACTCHANGE, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, outliner_do_id_set_operation(), wmOperator::ptr, wmOperator::reports, RNA_enum_get(), RPT_ERROR, RPT_WARNING, set_operation_types(), SpaceOops::tree, TSE_ANIM_DATA, and WM_event_add_notifier().
Referenced by OUTLINER_OT_action_set().
static int outliner_animdata_operation_exec (bContext * C, wmOperator * op) [static]
Definition at line 990 of file outliner_tools.c.
References cleardrivers_animdata_cb(), CTX_data_main(), CTX_data_scene(), CTX_wm_space_outliner(), DAG_ids_flush_update(), DAG_scene_sort(), ED_undo_push(), NC_ANIMATION, ND_ANIMCHAN, ND_NLA_ACTCHANGE, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OUTLINER_ANIMOP_CLEAR_ACT, OUTLINER_ANIMOP_CLEAR_DRV, OUTLINER_ANIMOP_REFRESH_DRV, OUTLINER_ANIMOP_SET_ACT, outliner_do_data_operation(), wmOperator::ptr, refreshdrivers_animdata_cb(), RNA_enum_get(), set_operation_types(), SpaceOops::tree, TSE_ANIM_DATA, unlinkact_animdata_cb(), WM_event_add_notifier(), WM_OP_INVOKE_REGION_WIN, and WM_operator_name_call().
Referenced by OUTLINER_OT_animdata_operation().
static int outliner_data_operation_exec (bContext * C, wmOperator * op) [static]
Definition at line 1085 of file outliner_tools.c.
References bone_cb(), CTX_wm_space_outliner(), ebone_cb(), ED_undo_push(), NC_OBJECT, ND_POSE, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, outliner_do_data_operation(), pchan_cb(), wmOperator::ptr, RNA_enum_get(), sequence_cb(), set_operation_types(), SpaceOops::tree, TSE_BONE, TSE_EBONE, TSE_POSE_CHANNEL, TSE_SEQUENCE, and WM_event_add_notifier().
Referenced by OUTLINER_OT_data_operation().
static void outliner_do_data_operation (SpaceOops * soops, int type, int event, ListBase * lb, void(*)(int, TreeElement *, TreeStoreElem *) operation_cb) [static]
Definition at line 485 of file outliner_tools.c.
References ListBase::first, TreeStoreElem::flag, TreeElement::next, TreeElement::subtree, TREESTORE, TSE_SELECTED, TSELEM_OPEN, and TreeStoreElem::type.
Referenced by outliner_animdata_operation_exec(), and outliner_data_operation_exec().
static void outliner_do_id_set_operation (SpaceOops * soops, int type, ListBase * lb, ID * newid, void(*)(TreeElement *, TreeStoreElem *, TreeStoreElem *, ID *) operation_cb) [static]
Definition at line 859 of file outliner_tools.c.
References ListBase::first, TreeStoreElem::flag, TreeElement::next, TreeElement::parent, TreeElement::subtree, TREESTORE, TSE_SELECTED, TSELEM_OPEN, and TreeStoreElem::type.
Referenced by outliner_action_set_exec().
static void outliner_do_libdata_operation (bContext * C, Scene * scene, SpaceOops * soops, ListBase * lb, void(*)(bContext *C, Scene *scene, TreeElement *, TreeStoreElem *, TreeStoreElem *) operation_cb) [static]
Definition at line 219 of file outliner_tools.c.
References ListBase::first, TreeStoreElem::flag, TreeElement::next, TreeElement::parent, TreeElement::subtree, TREESTORE, TSE_SELECTED, TSELEM_OPEN, and TreeStoreElem::type.
Referenced by outliner_group_operation_exec(), and outliner_id_operation_exec().
void outliner_do_object_operation (bContext * C, Scene * scene_act, SpaceOops * soops, ListBase * lb, void(*)(bContext *C, Scene *scene, TreeElement *, TreeStoreElem *, TreeStoreElem *) operation_cb)
Definition at line 370 of file outliner_tools.c.
References CTX_wm_screen(), ED_screen_set_scene(), ListBase::first, TreeStoreElem::flag, ID_OB, ID_SCE, TreeElement::idcode, TreeElement::next, NULL, outliner_do_object_operation(), outliner_search_back(), TreeElement::subtree, TREESTORE, TSE_SELECTED, TSELEM_OPEN, and TreeStoreElem::type.
static int outliner_group_operation_exec (bContext * C, wmOperator * op) [static]
Definition at line 620 of file outliner_tools.c.
References CTX_data_scene(), CTX_wm_space_outliner(), ED_undo_push(), group_linkobs2scene_cb(), group_toggle_renderability_cb(), group_toggle_selectability_cb(), group_toggle_visibility_cb(), id_local_cb(), item_rename_cb(), NC_GROUP, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, outliner_do_libdata_operation(), wmOperator::ptr, RNA_enum_get(), str, SpaceOops::tree, unlink_group_cb(), and WM_event_add_notifier().
Referenced by OUTLINER_OT_group_operation().
static int outliner_id_operation_exec (bContext * C, wmOperator * op) [static]
Definition at line 712 of file outliner_tools.c.
References BKE_report(), CTX_data_scene(), CTX_wm_space_outliner(), ED_undo_push(), ID_AC, id_fake_user_clear_cb(), id_fake_user_set_cb(), id_local_cb(), ID_MA, ID_TE, ID_WO, item_rename_cb(), NA_EDITED, NC_ANIMATION, NC_ID, NC_OBJECT, NC_SCENE, NC_SPACE, ND_NLA_ACTCHANGE, ND_OB_SHADING, ND_SPACE_OUTLINER, ND_WORLD, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, outliner_do_libdata_operation(), OUTLINER_IDOP_FAKE_ADD, OUTLINER_IDOP_FAKE_CLEAR, OUTLINER_IDOP_LOCAL, OUTLINER_IDOP_RENAME, OUTLINER_IDOP_SINGLE, OUTLINER_IDOP_UNLINK, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), RPT_WARNING, set_operation_types(), singleuser_action_cb(), singleuser_world_cb(), SpaceOops::tree, unlink_action_cb(), unlink_material_cb(), unlink_texture_cb(), unlink_world_cb(), and WM_event_add_notifier().
Referenced by OUTLINER_OT_id_operation().
static int outliner_object_operation_exec (bContext * C, wmOperator * op) [static]
Definition at line 517 of file outliner_tools.c.
References CTX_data_main(), CTX_data_scene(), CTX_wm_screen(), CTX_wm_space_outliner(), DAG_scene_sort(), ED_screen_set_scene(), ED_undo_push(), id_local_cb(), item_rename_cb(), NC_SCENE, ND_OB_ACTIVE, ND_OB_RENDER, ND_OB_SELECT, ND_OB_VISIBLE, NULL, object_delete_cb(), object_deselect_cb(), object_select_cb(), object_toggle_renderability_cb(), object_toggle_selectability_cb(), object_toggle_visibility_cb(), OPERATOR_CANCELLED, OPERATOR_FINISHED, outliner_cleanup_tree(), outliner_do_object_operation(), wmOperator::ptr, RNA_enum_get(), str, SpaceOops::tree, and WM_event_add_notifier().
Referenced by OUTLINER_OT_object_operation().
static int outliner_operation (bContext * C, wmOperator * UNUSEDop, wmEvent * event) [static]
Definition at line 1213 of file outliner_tools.c.
References CTX_data_scene(), CTX_wm_region(), CTX_wm_space_outliner(), do_outliner_operation_event(), ListBase::first, wmEvent::mval, TreeElement::next, OPERATOR_FINISHED, SpaceOops::tree, UI_view2d_region_to_view(), and ARegion::v2d.
Referenced by OUTLINER_OT_operation().
void OUTLINER_OT_action_set (wmOperatorType * ot)
Definition at line 941 of file outliner_tools.c.
References wmOperatorType::description, DummyRNA_NULL_items, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_action_set_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_action_itemf(), RNA_def_enum(), RNA_def_enum_funcs(), wmOperatorType::srna, and WM_enum_search_invoke().
Referenced by outliner_operatortypes().
void OUTLINER_OT_animdata_operation (wmOperatorType * ot)
Definition at line 1058 of file outliner_tools.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_animdata_operation_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by outliner_operatortypes().
void OUTLINER_OT_data_operation (wmOperatorType * ot)
Definition at line 1129 of file outliner_tools.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_data_operation_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by outliner_operatortypes().
void OUTLINER_OT_group_operation (wmOperatorType * ot)
Definition at line 670 of file outliner_tools.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_group_operation_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by outliner_operatortypes().
void OUTLINER_OT_id_operation (wmOperatorType * ot)
Definition at line 840 of file outliner_tools.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_id_operation_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by outliner_operatortypes().
void OUTLINER_OT_object_operation (wmOperatorType * ot)
Definition at line 590 of file outliner_tools.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_object_operation_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by outliner_operatortypes().
void OUTLINER_OT_operation (wmOperatorType * ot)
Definition at line 1231 of file outliner_tools.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_operation(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
static void pchan_cb (int event, TreeElement * te, TreeStoreElem * UNUSEDtselem) [static]
Definition at line 429 of file outliner_tools.c.
References bPoseChannel::bone, BONE_HIDDEN_P, BONE_SELECTED, TreeElement::directdata, Bone::flag, and if().
Referenced by outliner_data_operation_exec().
static void refreshdrivers_animdata_cb (int UNUSEDevent, TreeElement * UNUSEDte, TreeStoreElem * tselem) [static]
Definition at line 413 of file outliner_tools.c.
References IdAdtTemplate::adt, DRIVER_FLAG_INVALID, AnimData::drivers, FCURVE_DISABLED, ListBase::first, FCurve::flag, and TreeStoreElem::id.
Referenced by outliner_animdata_operation_exec().
static void sequence_cb (int event, TreeElement * UNUSEDte, TreeStoreElem * UNUSEDtselem) [static]
Definition at line 477 of file outliner_tools.c.
Referenced by outliner_data_operation_exec().
static void set_operation_types (SpaceOops * soops, ListBase * lb, int * scenelevel, int * objectlevel, int * idlevel, int * datalevel) [static]
Definition at line 79 of file outliner_tools.c.
References ListBase::first, TreeStoreElem::flag, GS, TreeStoreElem::id, ID_AC, ID_AR, ID_CA, ID_CU, ID_GR, ID_IM, ID_IP, ID_KE, ID_LA, ID_LT, ID_MA, ID_MB, ID_ME, ID_NLA, ID_OB, ID_SCE, ID_SO, ID_SPK, ID_TE, ID_TXT, ID_WO, ID::name, TreeElement::next, TreeElement::subtree, TREESTORE, TSE_SELECTED, TSELEM_OPEN, and TreeStoreElem::type.
Referenced by do_outliner_operation_event(), outliner_action_set_exec(), outliner_animdata_operation_exec(), outliner_data_operation_exec(), and outliner_id_operation_exec().
static void singleuser_action_cb (bContext * C, Scene * UNUSEDscene, TreeElement * UNUSEDte, TreeStoreElem * tsep, TreeStoreElem * tselem) [static]
Definition at line 312 of file outliner_tools.c.
References TreeStoreElem::id, and NULL.
Referenced by outliner_id_operation_exec().
static void singleuser_world_cb (bContext * C, Scene * UNUSEDscene, TreeElement * UNUSEDte, TreeStoreElem * tsep, TreeStoreElem * tselem) [static]
Definition at line 328 of file outliner_tools.c.
References TreeStoreElem::id, and NULL.
Referenced by outliner_id_operation_exec().
static void unlink_action_cb (bContext * C, Scene * UNUSEDscene, TreeElement * UNUSEDte, TreeStoreElem * tsep, TreeStoreElem * UNUSEDtselem) [static]
Definition at line 125 of file outliner_tools.c.
References BKE_animdata_set_action(), CTX_wm_reports(), TreeStoreElem::id, and NULL.
Referenced by outliner_id_operation_exec().
static void unlink_group_cb (bContext * UNUSEDC, Scene * UNUSEDscene, TreeElement * UNUSEDte, TreeStoreElem * tsep, TreeStoreElem * tselem) [static]
Definition at line 194 of file outliner_tools.c.
References Object::dup_group, GS, TreeStoreElem::id, ID_OB, if(), ID::name, NULL, and unlink_group().
Referenced by outliner_group_operation_exec().
static void unlink_material_cb (bContext * UNUSEDC, Scene * UNUSEDscene, TreeElement * te, TreeStoreElem * tsep, TreeStoreElem * UNUSEDtselem) [static]
Definition at line 131 of file outliner_tools.c.
References GS, Material::id, TreeStoreElem::id, ID_CU, ID_MB, ID_ME, ID_OB, TreeElement::index, Object::mat, Mesh::mat, Curve::mat, MetaBall::mat, ID::name, NULL, Curve::totcol, Object::totcol, Mesh::totcol, MetaBall::totcol, and ID::us.
Referenced by outliner_id_operation_exec().
static void unlink_texture_cb (bContext * UNUSEDC, Scene * UNUSEDscene, TreeElement * te, TreeStoreElem * tsep, TreeStoreElem * UNUSEDtselem) [static]
Definition at line 165 of file outliner_tools.c.
References GS, TreeStoreElem::id, Tex::id, ID_LA, ID_MA, ID_WO, TreeElement::index, MAX_MTEX, Lamp::mtex, World::mtex, Material::mtex, ID::name, NULL, MTex::tex, and ID::us.
Referenced by outliner_id_operation_exec().
static void unlink_world_cb (bContext * UNUSEDC, Scene * UNUSEDscene, TreeElement * UNUSEDte, TreeStoreElem * tsep, TreeStoreElem * tselem) [static]
Definition at line 209 of file outliner_tools.c.
References TreeStoreElem::id, id_us_min(), NULL, and Scene::world.
Referenced by outliner_id_operation_exec().
static void unlinkact_animdata_cb (int UNUSEDevent, TreeElement * UNUSEDte, TreeStoreElem * tselem) [static]
Definition at line 399 of file outliner_tools.c.
References BKE_animdata_set_action(), TreeStoreElem::id, and NULL.
Referenced by outliner_animdata_operation_exec().
Variable Documentation
EnumPropertyItem prop_animdata_op_types[] [static]
Initial value:
 {
    {OUTLINER_ANIMOP_SET_ACT, "SET_ACT", 0, "Set Action", ""},
    {OUTLINER_ANIMOP_CLEAR_ACT, "CLEAR_ACT", 0, "Unlink Action", ""},
    {OUTLINER_ANIMOP_REFRESH_DRV, "REFRESH_DRIVERS", 0, "Refresh Drivers", ""},
    {OUTLINER_ANIMOP_CLEAR_DRV, "CLEAR_DRIVERS", 0, "Clear Drivers", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 980 of file outliner_tools.c.
EnumPropertyItem prop_data_op_types[] [static]
Initial value:
 {
    {1, "SELECT", 0, "Select", ""},
    {2, "DESELECT", 0, "Deselect", ""},
    {3, "HIDE", 0, "Hide", ""},
    {4, "UNHIDE", 0, "Unhide", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 1077 of file outliner_tools.c.
EnumPropertyItem prop_group_op_types[] [static]
Initial value:
 {
    {1, "UNLINK", 0, "Unlink", ""},
    {2, "LOCAL", 0, "Make Local", ""},
    {3, "LINK", 0, "Link Group Objects to Scene", ""},
    {4, "TOGVIS", 0, "Toggle Visible", ""},
    {5, "TOGSEL", 0, "Toggle Selectable", ""},
    {6, "TOGREN", 0, "Toggle Renderable", ""},
    {7, "RENAME", 0, "Rename", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 609 of file outliner_tools.c.
EnumPropertyItem prop_id_op_types[] [static]
Initial value:
 {
    {OUTLINER_IDOP_UNLINK, "UNLINK", 0, "Unlink", ""},
    {OUTLINER_IDOP_LOCAL, "LOCAL", 0, "Make Local", ""},
    {OUTLINER_IDOP_SINGLE, "SINGLE", 0, "Make Single User", ""},
    {OUTLINER_IDOP_FAKE_ADD, "ADD_FAKE", 0, "Add Fake User", "Ensure datablock gets saved even if it isn't in use (e.g. for motion and material libraries)"},
    {OUTLINER_IDOP_FAKE_CLEAR, "CLEAR_FAKE", 0, "Clear Fake User", ""},
    {OUTLINER_IDOP_RENAME, "RENAME", 0, "Rename", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 702 of file outliner_tools.c.
EnumPropertyItem prop_object_op_types[] [static]
Initial value:
 {
    {1, "SELECT", 0, "Select", ""},
    {2, "DESELECT", 0, "Deselect", ""},
    {4, "DELETE", 0, "Delete", ""},
    {6, "TOGVIS", 0, "Toggle Visible", ""},
    {7, "TOGSEL", 0, "Toggle Selectable", ""},
    {8, "TOGREN", 0, "Toggle Renderable", ""},
    {9, "RENAME", 0, "Rename", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 506 of file outliner_tools.c.