Blender: bmesh_py_types_select.c File Reference
bmesh_py_types_select.c File Reference
#include <Python.h>
#include "BLI_utildefines.h"
#include "BLI_listbase.h"
#include "bmesh.h"
#include "bmesh_py_types.h"
#include "bmesh_py_types_select.h"
#include "BKE_tessmesh.h"
#include "DNA_mesh_types.h"
#include "../generic/py_capi_utils.h"
#include "bmesh_py_api.h"
Functions
PyDoc_STRVAR (bpy_bmeditselseq_active_doc,"The last selected element or None (read-only).\n\n:type: :class:`BMVert`, :class:`BMEdge` or :class:`BMFace`")
static PyObject * bpy_bmeditselseq_active_get (BPy_BMEditSelSeq *self, void *UNUSED(closure))
PyDoc_STRVAR (bpy_bmeditselseq_validate_doc,".. method:: validate()\n""\n"" Ensures all elements in the selection history are selected.\n")
static PyObject * bpy_bmeditselseq_validate (BPy_BMEditSelSeq *self)
PyDoc_STRVAR (bpy_bmeditselseq_clear_doc,".. method:: clear()\n""\n"" Empties the selection history.\n")
static PyObject * bpy_bmeditselseq_clear (BPy_BMEditSelSeq *self)
PyDoc_STRVAR (bpy_bmeditselseq_add_doc,".. method:: add(element)\n""\n"" Add an element to the selection history (no action taken if its already added).\n")
static PyObject * bpy_bmeditselseq_add (BPy_BMEditSelSeq *self, BPy_BMElem *value)
PyDoc_STRVAR (bpy_bmeditselseq_remove_doc,".. method:: remove(element)\n""\n"" Remove an element from the selection history.\n")
static PyObject * bpy_bmeditselseq_remove (BPy_BMEditSelSeq *self, BPy_BMElem *value)
static Py_ssize_t bpy_bmeditselseq_length (BPy_BMEditSelSeq *self)
static PyObject * bpy_bmeditselseq_subscript_int (BPy_BMEditSelSeq *self, int keynum)
static PyObject * bpy_bmeditselseq_subscript_slice (BPy_BMEditSelSeq *self, Py_ssize_t start, Py_ssize_t stop)
static PyObject * bpy_bmeditselseq_subscript (BPy_BMEditSelSeq *self, PyObject *key)
static int bpy_bmeditselseq_contains (BPy_BMEditSelSeq *self, PyObject *value)
static PyObject * bpy_bmeditselseq_iter (BPy_BMEditSelSeq *self)
static PyObject * bpy_bmeditseliter_next (BPy_BMEditSelIter *self)
PyObject * BPy_BMEditSel_CreatePyObject (BMesh *bm)
PyObject * BPy_BMEditSelIter_CreatePyObject (BMesh *bm)
void BPy_BM_init_types_select (void)
int BPy_BMEditSel_Assign (BPy_BMesh *self, PyObject *value)
Variables
static PyGetSetDef bpy_bmeditselseq_getseters []
static struct PyMethodDef bpy_bmeditselseq_methods []
static PySequenceMethods bpy_bmeditselseq_as_sequence
static PyMappingMethods bpy_bmeditselseq_as_mapping
PyTypeObject BPy_BMEditSelSeq_Type = {{{0}}}
PyTypeObject BPy_BMEditSelIter_Type = {{{0}}}
Detailed Description
This file defines the types for 'BMesh.select_history' sequence and iterator.
select_history is very loosely based on pytons set() type, since items can only exist once. however they do have an order.
Definition in file bmesh_py_types_select.c.
Function Documentation
void BPy_BM_init_types_select (void)
Definition at line 382 of file bmesh_py_types_select.c.
References bpy_bmeditseliter_next(), bpy_bmeditselseq_as_mapping, bpy_bmeditselseq_as_sequence, bpy_bmeditselseq_getseters, bpy_bmeditselseq_iter(), bpy_bmeditselseq_methods, and NULL.
Referenced by BPyInit_bmesh().
int BPy_BMEditSel_Assign (BPy_BMesh * self, PyObject * value)
Note:
doesn't actually check selection.
Definition at line 427 of file bmesh_py_types_select.c.
References BM_EDGE, BM_FACE, BM_select_history_clear(), BM_select_history_store_notest, BM_VERT, BPY_BM_CHECK_INT, BPy_BMElem_PySeq_As_Array(), i, NULL, and TRUE.
Referenced by bpy_bmesh_select_history_set().
PyObject* BPy_BMEditSel_CreatePyObject (BMesh * bm)
Definition at line 366 of file bmesh_py_types_select.c.
Referenced by bpy_bmesh_select_history_get().
PyObject* BPy_BMEditSelIter_CreatePyObject (BMesh * bm)
Definition at line 374 of file bmesh_py_types_select.c.
Referenced by bpy_bmeditselseq_iter().
static PyObject* bpy_bmeditseliter_next (BPy_BMEditSelIter * self) [static]
Definition at line 348 of file bmesh_py_types_select.c.
References BPy_BMElem_CreatePyObject(), BMEditSelection::ele, BMElem::head, BMEditSelection::next, and NULL.
Referenced by BPy_BM_init_types_select().
static PyObject* bpy_bmeditselseq_active_get (BPy_BMEditSelSeq * self, void * UNUSEDclosure) [static]
Definition at line 57 of file bmesh_py_types_select.c.
References BPY_BM_CHECK_OBJ, BPy_BMElem_CreatePyObject(), BMEditSelection::ele, and BMElem::head.
static PyObject* bpy_bmeditselseq_add (BPy_BMEditSelSeq * self, BPy_BMElem * value) [static]
Definition at line 104 of file bmesh_py_types_select.c.
References BPy_BMElem::bm, BM_select_history_store, BPY_BM_CHECK_OBJ, BPy_BMEdge_Check, BPy_BMFace_Check, BPy_BMVert_Check, BPy_BMElem::ele, FALSE, and NULL.
static PyObject* bpy_bmeditselseq_clear (BPy_BMEditSelSeq * self) [static]
Definition at line 92 of file bmesh_py_types_select.c.
References BM_select_history_clear(), and BPY_BM_CHECK_OBJ.
static int bpy_bmeditselseq_contains (BPy_BMEditSelSeq * self, PyObject * value) [static]
Definition at line 301 of file bmesh_py_types_select.c.
References BPy_BMElem::bm, BM_select_history_check, BPY_BM_CHECK_INT, and BPy_BMElem::ele.
static PyObject* bpy_bmeditselseq_iter (BPy_BMEditSelSeq * self) [static]
Definition at line 338 of file bmesh_py_types_select.c.
References BPY_BM_CHECK_OBJ, BPy_BMEditSelIter_CreatePyObject(), and BPy_BMEditSelIter::ese.
Referenced by BPy_BM_init_types_select().
static Py_ssize_t bpy_bmeditselseq_length (BPy_BMEditSelSeq * self) [static]
Definition at line 174 of file bmesh_py_types_select.c.
References BLI_countlist(), and BPY_BM_CHECK_INT.
Referenced by bpy_bmeditselseq_subscript().
static PyObject* bpy_bmeditselseq_remove (BPy_BMEditSelSeq * self, BPy_BMElem * value) [static]
Definition at line 135 of file bmesh_py_types_select.c.
References BPy_BMElem::bm, BM_select_history_remove, BPY_BM_CHECK_OBJ, BPy_BMEdge_Check, BPy_BMFace_Check, BPy_BMVert_Check, BPy_BMElem::ele, FALSE, and NULL.
static PyObject* bpy_bmeditselseq_subscript (BPy_BMEditSelSeq * self, PyObject * key) [static]
Definition at line 248 of file bmesh_py_types_select.c.
References bpy_bmeditselseq_length(), bpy_bmeditselseq_subscript_int(), bpy_bmeditselseq_subscript_slice(), i, len(), NULL, and step().
static PyObject* bpy_bmeditselseq_subscript_int (BPy_BMEditSelSeq * self, int keynum) [static]
Definition at line 181 of file bmesh_py_types_select.c.
References BLI_findlink(), BLI_rfindlink(), BPY_BM_CHECK_OBJ, BPy_BMElem_CreatePyObject(), BMEditSelection::ele, BMElem::head, and NULL.
Referenced by bpy_bmeditselseq_subscript().
static PyObject* bpy_bmeditselseq_subscript_slice (BPy_BMEditSelSeq * self, Py_ssize_t start, Py_ssize_t stop) [static]
Definition at line 204 of file bmesh_py_types_select.c.
References BPY_BM_CHECK_OBJ, BPy_BMElem_CreatePyObject(), BMEditSelection::ele, FALSE, BMElem::head, BMEditSelection::next, NULL, TRUE, and UNLIKELY.
Referenced by bpy_bmeditselseq_subscript().
static PyObject* bpy_bmeditselseq_validate (BPy_BMEditSelSeq * self) [static]
Definition at line 80 of file bmesh_py_types_select.c.
References BM_select_history_validate(), and BPY_BM_CHECK_OBJ.
PyDoc_STRVAR (bpy_bmeditselseq_clear_doc , ".. method:: clear()\n""\n"" Empties the selection history.\n")
PyDoc_STRVAR (bpy_bmeditselseq_validate_doc , ".. method:: validate()\n""\n"" Ensures all elements in the selection history are selected.\n")
PyDoc_STRVAR (bpy_bmeditselseq_active_doc , "The last selected element or None (read-only).\n\n:type: :class:`BMVert` , :class:`BMEdge`or:class:`BMFace`")
PyDoc_STRVAR (bpy_bmeditselseq_remove_doc , ".. method:: remove(element)\n""\n"" Remove an element from the selection history.\n")
PyDoc_STRVAR (bpy_bmeditselseq_add_doc , ".. method:: add(element)\n""\n"" Add an element to the selection history (no action taken if its already added).\n")
Variable Documentation
PyTypeObject BPy_BMEditSelIter_Type = {{{0}}}
Definition at line 363 of file bmesh_py_types_select.c.
Referenced by BPyInit_bmesh_types().
PyMappingMethods bpy_bmeditselseq_as_mapping [static]
Initial value:
 {
    (lenfunc)bpy_bmeditselseq_length,
    (binaryfunc)bpy_bmeditselseq_subscript,
    (objobjargproc)NULL,
}
Definition at line 328 of file bmesh_py_types_select.c.
Referenced by BPy_BM_init_types_select().
PySequenceMethods bpy_bmeditselseq_as_sequence [static]
Initial value:
 {
    (lenfunc)bpy_bmeditselseq_length,
    NULL,
    NULL,
    (ssizeargfunc)bpy_bmeditselseq_subscript_int,
    NULL,
    (ssizeobjargproc)NULL,
    NULL,
    (objobjproc)bpy_bmeditselseq_contains,
    (binaryfunc) NULL,
    (ssizeargfunc) NULL,
}
Definition at line 315 of file bmesh_py_types_select.c.
Referenced by BPy_BM_init_types_select().
PyGetSetDef bpy_bmeditselseq_getseters[] [static]
Initial value:
 {
    {(char *)"active", (getter)bpy_bmeditselseq_active_get, (setter)NULL, (char *)bpy_bmeditselseq_active_doc, NULL},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 70 of file bmesh_py_types_select.c.
Referenced by BPy_BM_init_types_select().
struct PyMethodDef bpy_bmeditselseq_methods[] [static]
Initial value:
 {
    {"validate", (PyCFunction)bpy_bmeditselseq_validate, METH_NOARGS, bpy_bmeditselseq_validate_doc},
    {"clear",    (PyCFunction)bpy_bmeditselseq_clear,    METH_NOARGS, bpy_bmeditselseq_clear_doc},
    {"add",      (PyCFunction)bpy_bmeditselseq_add,      METH_O,      bpy_bmeditselseq_add_doc},
    {"remove",   (PyCFunction)bpy_bmeditselseq_remove,   METH_O,      bpy_bmeditselseq_remove_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 161 of file bmesh_py_types_select.c.
Referenced by BPy_BM_init_types_select().
PyTypeObject BPy_BMEditSelSeq_Type = {{{0}}}
Definition at line 362 of file bmesh_py_types_select.c.
Referenced by BPyInit_bmesh_types().