Blender: bsdf_westin.h File Reference
bsdf_westin.h File Reference
Classes
struct BsdfWestinBackscatterClosure
struct BsdfWestinSheenClosure
Typedefs
typedef CCL_NAMESPACE_BEGIN
struct
BsdfWestinBackscatterClosure BsdfWestinBackscatterClosure
typedef struct
BsdfWestinSheenClosure BsdfWestinSheenClosure
Functions
__device void bsdf_westin_backscatter_setup (ShaderData *sd, ShaderClosure *sc, float roughness)
__device void bsdf_westin_backscatter_blur (ShaderClosure *sc, float roughness)
__device float3 bsdf_westin_backscatter_eval_reflect (const ShaderData *sd, const ShaderClosure *sc, const float3 I, const float3 omega_in, float *pdf)
__device float3 bsdf_westin_backscatter_eval_transmit (const ShaderData *sd, const ShaderClosure *sc, const float3 I, const float3 omega_in, float *pdf)
__device float bsdf_westin_backscatter_albedo (const ShaderData *sd, const ShaderClosure *sc, const float3 I)
__device int bsdf_westin_backscatter_sample (const ShaderData *sd, const ShaderClosure *sc, float randu, float randv, float3 *eval, float3 *omega_in, float3 *domega_in_dx, float3 *domega_in_dy, float *pdf)
__device void bsdf_westin_sheen_setup (ShaderData *sd, ShaderClosure *sc, float edginess)
__device void bsdf_westin_sheen_blur (ShaderClosure *sc, float roughness)
__device float3 bsdf_westin_sheen_eval_reflect (const ShaderData *sd, const ShaderClosure *sc, const float3 I, const float3 omega_in, float *pdf)
__device float3 bsdf_westin_sheen_eval_transmit (const ShaderData *sd, const ShaderClosure *sc, const float3 I, const float3 omega_in, float *pdf)
__device float bsdf_westin_sheen_albedo (const ShaderData *sd, const ShaderClosure *sc, const float3 I)
__device int bsdf_westin_sheen_sample (const ShaderData *sd, const ShaderClosure *sc, float randu, float randv, float3 *eval, float3 *omega_in, float3 *domega_in_dx, float3 *domega_in_dy, float *pdf)
Typedef Documentation
typedef CCL_NAMESPACE_BEGIN struct BsdfWestinBackscatterClosure BsdfWestinBackscatterClosure
typedef struct BsdfWestinSheenClosure BsdfWestinSheenClosure
Function Documentation
__device float bsdf_westin_backscatter_albedo (const ShaderData * sd, const ShaderClosure * sc, const float3 I)
Definition at line 84 of file bsdf_westin.h.
__device void bsdf_westin_backscatter_blur (ShaderClosure * sc, float roughness)
Definition at line 55 of file bsdf_westin.h.
References ShaderClosure::data0, and min.
Referenced by svm_bsdf_blur().
__device float3 bsdf_westin_backscatter_eval_reflect (const ShaderData * sd, const ShaderClosure * sc, const float3 I, const float3 omega_in, float * pdf)
Definition at line 62 of file bsdf_westin.h.
References ShaderClosure::data0, dot(), M_1_PI_F, make_float3(), ShaderData::N, and powf.
Referenced by svm_bsdf_eval().
__device float3 bsdf_westin_backscatter_eval_transmit (const ShaderData * sd, const ShaderClosure * sc, const float3 I, const float3 omega_in, float * pdf)
Definition at line 79 of file bsdf_westin.h.
References make_float3().
Referenced by svm_bsdf_eval().
__device int bsdf_westin_backscatter_sample (const ShaderData * sd, const ShaderClosure * sc, float randu, float randv, float3 * eval, float3 * omega_in, float3 * domega_in_dx, float3 * domega_in_dy, float * pdf)
Definition at line 89 of file bsdf_westin.h.
References B, cosf, ShaderClosure::data0, ShaderData::dI, dot(), differential3::dx, differential3::dy, ShaderData::I, LABEL_GLOSSY, LABEL_REFLECT, M_1_PI_F, M_PI_F, make_float3(), make_orthonormals(), ShaderData::N, ShaderData::Ng, powf, sinf, sqrtf, and T.
Referenced by svm_bsdf_sample().
__device void bsdf_westin_backscatter_setup (ShaderData * sd, ShaderClosure * sc, float roughness)
Definition at line 45 of file bsdf_westin.h.
References clamp, CLOSURE_BSDF_WESTIN_BACKSCATTER_ID, ShaderClosure::data0, ShaderData::flag, SD_BSDF, SD_BSDF_GLOSSY, SD_BSDF_HAS_EVAL, and ShaderClosure::type.
__device float bsdf_westin_sheen_albedo (const ShaderData * sd, const ShaderClosure * sc, const float3 I)
Definition at line 173 of file bsdf_westin.h.
__device void bsdf_westin_sheen_blur (ShaderClosure * sc, float roughness)
Definition at line 147 of file bsdf_westin.h.
Referenced by svm_bsdf_blur().
__device float3 bsdf_westin_sheen_eval_reflect (const ShaderData * sd, const ShaderClosure * sc, const float3 I, const float3 omega_in, float * pdf)
Definition at line 151 of file bsdf_westin.h.
References ShaderClosure::data0, dot(), M_1_PI_F, make_float3(), ShaderData::N, and powf.
Referenced by svm_bsdf_eval().
__device float3 bsdf_westin_sheen_eval_transmit (const ShaderData * sd, const ShaderClosure * sc, const float3 I, const float3 omega_in, float * pdf)
Definition at line 168 of file bsdf_westin.h.
References make_float3().
Referenced by svm_bsdf_eval().
__device int bsdf_westin_sheen_sample (const ShaderData * sd, const ShaderClosure * sc, float randu, float randv, float3 * eval, float3 * omega_in, float3 * domega_in_dx, float3 * domega_in_dy, float * pdf)
Definition at line 178 of file bsdf_westin.h.
References ShaderClosure::data0, ShaderData::dI, dot(), differential3::dx, differential3::dy, ShaderData::I, LABEL_DIFFUSE, LABEL_REFLECT, make_float3(), ShaderData::N, ShaderData::Ng, powf, and sample_cos_hemisphere().
Referenced by svm_bsdf_sample().
__device void bsdf_westin_sheen_setup (ShaderData * sd, ShaderClosure * sc, float edginess)
Definition at line 140 of file bsdf_westin.h.
References CLOSURE_BSDF_WESTIN_SHEEN_ID, ShaderClosure::data0, ShaderData::flag, SD_BSDF, SD_BSDF_GLOSSY, SD_BSDF_HAS_EVAL, and ShaderClosure::type.