Blender: property.c File Reference
property.c File Reference
blenkernel
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <ctype.h>
#include "MEM_guardedalloc.h"
#include "DNA_property_types.h"
#include "DNA_object_types.h"
#include "BLI_blenlib.h"
#include "BKE_property.h"
Functions
void free_property (bProperty *prop)
void free_properties (ListBase *lb)
bProperty * copy_property (bProperty *prop)
void copy_properties (ListBase *lbn, ListBase *lbo)
void init_property (bProperty *prop)
bProperty * new_property (int type)
static bProperty * get_property__internal (bProperty *first, bProperty *self, const char *name)
void unique_property (bProperty *first, bProperty *prop, int force)
bProperty * get_ob_property (Object *ob, const char *name)
void set_ob_property (Object *ob, bProperty *propc)
int compare_property (bProperty *prop, const char *str)
void set_property (bProperty *prop, const char *str)
void add_property (bProperty *prop, const char *str)
void set_property_valstr (bProperty *prop, char *str)
void cp_property (bProperty *prop1, bProperty *prop2)
Detailed Description
Definition in file property.c.
Function Documentation
void add_property (bProperty * prop, const char * str)
Definition at line 265 of file property.c.
References bProperty::data, GPROP_BOOL, GPROP_FLOAT, GPROP_INT, GPROP_STRING, GPROP_TIME, and bProperty::type.
Referenced by ply_read().
int compare_property (bProperty * prop, const char * str)
Definition at line 204 of file property.c.
References BLI_strcasecmp(), bProperty::data, GPROP_BOOL, GPROP_FLOAT, GPROP_INT, GPROP_STRING, GPROP_TIME, bProperty::poin, and bProperty::type.
void copy_properties (ListBase * lbn, ListBase * lbo)
Definition at line 79 of file property.c.
References BLI_addtail(), copy_property(), ListBase::first, free_properties(), and bProperty::next.
Referenced by copy_object(), copymenu_properties(), and game_property_copy_exec().
bProperty* copy_property (bProperty * prop) [read]
Definition at line 66 of file property.c.
References bProperty::data, MEM_dupallocN(), and bProperty::poin.
Referenced by copy_properties(), ply_describe_element(), ply_describe_other_properties(), ply_describe_property(), ply_get_element_description(), ply_get_other_properties(), and set_ob_property().
void cp_property (bProperty * prop1, bProperty * prop2)
Definition at line 306 of file property.c.
References set_property(), set_property_valstr(), and str.
void free_properties (ListBase * lb)
Definition at line 56 of file property.c.
References BLI_remlink(), ListBase::first, and free_property().
Referenced by copy_properties(), free_object(), and game_property_clear_exec().
void free_property (bProperty * prop)
Definition at line 48 of file property.c.
References bProperty::data, MEM_freeN(), and bProperty::poin.
Referenced by free_properties(), game_property_remove(), and set_ob_property().
bProperty* get_ob_property (Object * ob, const char * name) [read]
Definition at line 185 of file property.c.
References BLI_findstring(), and Object::prop.
Referenced by BL_ConvertTextProperty(), do_versions(), draw_mesh_text(), draw_mesh_textured_old(), objects_share_gameprop(), and set_ob_property().
static bProperty* get_property__internal (bProperty * first, bProperty * self, const char * name) [static]
Definition at line 131 of file property.c.
References bProperty::name, bProperty::next, NULL, and p.
Referenced by unique_property().
void init_property (bProperty * prop)
Definition at line 93 of file property.c.
References bProperty::data, GPROP_BOOL, GPROP_FLOAT, GPROP_INT, GPROP_STRING, GPROP_TIME, MAX_PROPSTRING, MEM_callocN(), MEM_freeN(), NULL, bProperty::poin, and bProperty::type.
Referenced by new_property().
bProperty* new_property (int type) [read]
Definition at line 116 of file property.c.
References init_property(), MEM_callocN(), bProperty::name, and bProperty::type.
Referenced by game_property_new().
void set_ob_property (Object * ob, bProperty * propc)
Definition at line 190 of file property.c.
References BLI_addtail(), BLI_remlink(), copy_property(), free_property(), get_ob_property(), bProperty::name, and Object::prop.
Referenced by copymenu_properties(), and game_property_copy_exec().
void set_property (bProperty * prop, const char * str)
Definition at line 241 of file property.c.
References BLI_strcasecmp(), bProperty::data, GPROP_BOOL, GPROP_FLOAT, GPROP_INT, GPROP_STRING, GPROP_TIME, bProperty::poin, and bProperty::type.
Referenced by cp_property().
void set_property_valstr (bProperty * prop, char * str)
Definition at line 285 of file property.c.
References BLI_strncpy(), bProperty::data, GPROP_BOOL, GPROP_FLOAT, GPROP_INT, GPROP_STRING, GPROP_TIME, MAX_PROPSTRING, NULL, bProperty::poin, and bProperty::type.
Referenced by cp_property(), and draw_mesh_text().
void unique_property (bProperty * first, bProperty * prop, int force)
Definition at line 140 of file property.c.
References BLI_snprintf(), BLI_strncpy(), get_property__internal(), i, bProperty::name, NULL, p, bProperty::prev, strlen(), and unique_property().
Referenced by game_property_new(), and unique_property().