Blender: RenderBuffers Class Reference
RenderBuffers Class Reference
#include <buffers.h>
Public Member Functions
RenderBuffers (Device *device)
~RenderBuffers ()
void reset (Device *device, BufferParams &params)
bool copy_from_device ()
bool get_pass (PassType type, float exposure, int sample, int components, float *pixels)
Public Attributes
BufferParams params
device_vector< float > buffer
device_vector< uint > rng_state
thread_mutex mutex
Protected Member Functions
void device_free ()
Protected Attributes
Device * device
Detailed Description
Definition at line 66 of file buffers.h.
Constructor & Destructor Documentation
RenderBuffers::RenderBuffers (Device * device)
Definition at line 79 of file buffers.cpp.
References device.
RenderBuffers::~RenderBuffers ()
Definition at line 84 of file buffers.cpp.
References device_free().
Member Function Documentation
bool RenderBuffers::copy_from_device ()
Definition at line 128 of file buffers.cpp.
References buffer, device, device_memory::device_pointer, BufferParams::get_passes_size(), BufferParams::height, Device::mem_copy_from(), params, and BufferParams::width.
Referenced by BlenderSession::write_render_result().
void RenderBuffers::device_free () [protected]
Definition at line 89 of file buffers.cpp.
References buffer, device_vector< T >::clear(), device, device_memory::device_pointer, Device::mem_free(), and rng_state.
Referenced by reset(), and ~RenderBuffers().
bool RenderBuffers::get_pass (PassType type, float exposure, int sample, int components, float * pixels)
Definition at line 138 of file buffers.cpp.
References assert, buffer, clamp, Pass::components, device_memory::data_pointer, Pass::divide_type, Pass::exposure, Pass::filter, BufferParams::get_passes_size(), BufferParams::height, i, make_float3(), make_float4(), params, PASS_DEPTH, PASS_NONE, PASS_SHADOW, BufferParams::passes, safe_divide_color(), size(), Pass::type, float4::w, BufferParams::width, float3::x, float4::x, float3::y, float4::y, float3::z, and float4::z.
Referenced by BlenderSession::write_render_result().
void RenderBuffers::reset (Device * device, BufferParams & params)
Definition at line 102 of file buffers.cpp.
References buffer, device_free(), BufferParams::full_x, BufferParams::full_y, BufferParams::get_passes_size(), hash_int_2d(), BufferParams::height, Device::mem_alloc(), Device::mem_copy_to(), MEM_READ_WRITE, Device::mem_zero(), params, device_vector< T >::resize(), rng_state, and BufferParams::width.
Referenced by Session::reset_().
Member Data Documentation
device_vector<float> RenderBuffers::buffer
Definition at line 71 of file buffers.h.
Referenced by copy_from_device(), device_free(), get_pass(), Session::path_trace(), reset(), and Session::tonemap().
Device* RenderBuffers::device [protected]
Definition at line 88 of file buffers.h.
Referenced by copy_from_device(), device_free(), and RenderBuffers().
thread_mutex RenderBuffers::mutex
Definition at line 75 of file buffers.h.
Referenced by Session::draw_gpu(), Session::reset_gpu(), Session::run_cpu(), and Session::run_gpu().
BufferParams RenderBuffers::params
Definition at line 69 of file buffers.h.
Referenced by copy_from_device(), get_pass(), reset(), Session::reset_(), and BlenderSession::write_render_result().
device_vector<uint> RenderBuffers::rng_state
Definition at line 73 of file buffers.h.
Referenced by device_free(), Session::path_trace(), and reset().
The documentation for this class was generated from the following files:
buffers.h
buffers.cpp