Blender: bmo_subdivide.c File Reference
bmo_subdivide.c File Reference
BMesh | BMesh | BMesh
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_array.h"
#include "BLI_noise.h"
#include "BKE_customdata.h"
#include "DNA_object_types.h"
#include "bmesh.h"
#include "intern/bmesh_private.h"
#include "intern/bmesh_operators_private.h"
#include "bmo_subdivide.h"
Classes
struct SubDFaceData
Defines
#define SUBD_SPLIT 1
#define EDGE_PERCENT 2
#define FACE_CUSTOMFILL 4
#define ELE_INNER 8
#define ELE_SPLIT 16
#define PLEN (sizeof(patterns) / sizeof(void *))
Typedefs
typedef struct SubDFaceData SubDFaceData
Functions
static BMEdge * connect_smallest_face (BMesh *bm, BMVert *v1, BMVert *v2, BMFace **r_nf)
static void alter_co (BMesh *bm, BMVert *v, BMEdge *UNUSED(origed), const SubDParams *params, float perc, BMVert *vsta, BMVert *vend)
static BMVert * bm_subdivide_edge_addvert (BMesh *bm, BMEdge *edge, BMEdge *oedge, const SubDParams *params, float percent, float percent2, BMEdge **out, BMVert *vsta, BMVert *vend)
static BMVert * subdivideedgenum (BMesh *bm, BMEdge *edge, BMEdge *oedge, int curpoint, int totpoint, const SubDParams *params, BMEdge **newe, BMVert *vsta, BMVert *vend)
static void bm_subdivide_multicut (BMesh *bm, BMEdge *edge, const SubDParams *params, BMVert *vsta, BMVert *vend)
static void quad_1edge_split (BMesh *bm, BMFace *UNUSED(face), BMVert **verts, const SubDParams *params)
static void quad_2edge_split_path (BMesh *bm, BMFace *UNUSED(face), BMVert **verts, const SubDParams *params)
static void quad_2edge_split_innervert (BMesh *bm, BMFace *UNUSED(face), BMVert **verts, const SubDParams *params)
static void quad_2edge_split_fan (BMesh *bm, BMFace *UNUSED(face), BMVert **verts, const SubDParams *params)
static void quad_3edge_split (BMesh *bm, BMFace *UNUSED(face), BMVert **verts, const SubDParams *params)
static void quad_4edge_subdivide (BMesh *bm, BMFace *UNUSED(face), BMVert **verts, const SubDParams *params)
static void tri_1edge_split (BMesh *bm, BMFace *UNUSED(face), BMVert **verts, const SubDParams *params)
static void tri_3edge_subdivide (BMesh *bm, BMFace *UNUSED(face), BMVert **verts, const SubDParams *params)
void bmo_esubd_exec (BMesh *bm, BMOperator *op)
void BM_mesh_esubdivide (BMesh *bm, const char edge_hflag, float smooth, float fractal, int numcuts, int seltype, int cornertype, const short use_singleedge, const short use_gridfill, int seed)
void bmo_edgebisect_exec (BMesh *bm, BMOperator *op)
Variables
static SubDPattern quad_1edge
static SubDPattern quad_2edge_path
static SubDPattern quad_2edge_innervert
static SubDPattern quad_2edge_fan
static SubDPattern quad_3edge
static SubDPattern tri_1edge
static SubDPattern tri_3edge
static SubDPattern quad_4edge
static SubDPattern * patterns []
Detailed Description
utility bmesh operators, e.g. transform, translate, rotate, scale, etc.
Definition in file bmo_subdivide.c.
Define Documentation
#define EDGE_PERCENT 2
Definition at line 48 of file bmo_subdivide.c.
Referenced by bmo_esubd_exec(), and subdivideedgenum().
#define ELE_INNER 8
Definition at line 53 of file bmo_subdivide.c.
Referenced by bm_subdivide_edge_addvert(), bmo_esubd_exec(), quad_4edge_subdivide(), and tri_3edge_subdivide().
#define ELE_SPLIT 16
Definition at line 54 of file bmo_subdivide.c.
Referenced by bm_subdivide_multicut(), bmo_edgebisect_exec(), and bmo_esubd_exec().
#define FACE_CUSTOMFILL 4
Definition at line 52 of file bmo_subdivide.c.
Referenced by bmo_esubd_exec().
#define PLEN (sizeof(patterns) / sizeof(void *))
Definition at line 666 of file bmo_subdivide.c.
Referenced by bmo_esubd_exec().
#define SUBD_SPLIT 1
Definition at line 46 of file bmo_subdivide.c.
Referenced by bm_subdivide_multicut(), and bmo_esubd_exec().
Typedef Documentation
typedef struct SubDFaceData SubDFaceData
Function Documentation
static void alter_co (BMesh * bm, BMVert * v, BMEdge * UNUSEDoriged, const SubDParams * params, float perc, BMVert * vsta, BMVert * vend) [static]
Definition at line 99 of file bmo_subdivide.c.
References add_v3_v3(), add_v3_v3v3(), BLI_gTurbulence(), BM_vert_normal_update_all(), CD_SHAPEKEY, co, BMVert::co, copy_v3_v3(), CustomData_bmesh_get_n(), CustomData_number_of_layers(), BMHeader::data, dot_v3v3(), fabsf, SubDParams::fractal, BMVert::head, i, len(), len_v3v3(), madd_v3_v3fl(), mul_v3_fl(), mul_v3_v3(), mul_v3_v3fl(), BMVert::no, normalize_v3(), NULL, SubDParams::off, SubDParams::origkey, smooth(), SubDParams::smooth, sqrtf, sub_v3_v3(), sub_v3_v3v3(), UNLIKELY, SubDParams::use_fractal, SubDParams::use_smooth, SubDParams::use_sphere, and BMesh::vdata.
Referenced by bm_subdivide_edge_addvert(), and bm_subdivide_multicut().
void BM_mesh_esubdivide (BMesh * bm, const char edge_hflag, float smooth, float fractal, int numcuts, int seltype, int cornertype, const short use_singleedge, const short use_gridfill, int seed)
Definition at line 1027 of file bmo_subdivide.c.
References BM_EDGE, BM_edge_select_set(), BM_EDGES_OF_VERT, BM_elem_flag_test, BM_ELEM_SELECT, BM_elem_select_set(), BM_FACE, BM_ITER_ELEM, BM_mesh_elem_hflag_disable_all(), BM_VERT, BMO_iter_new(), BMO_iter_step(), BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), FALSE, BMElem::head, BMHeader::htype, SUBDIV_SELECT_INNER, SUBDIV_SELECT_LOOPCUT, TRUE, BMEdge::v1, and BMEdge::v2.
Referenced by edbm_subdivide_exec(), and ringsel_finish().
static BMVert* bm_subdivide_edge_addvert (BMesh * bm, BMEdge * edge, BMEdge * oedge, const SubDParams * params, float percent, float percent2, BMEdge ** out, BMVert * vsta, BMVert * vend) [static]
Definition at line 182 of file bmo_subdivide.c.
References alter_co(), BM_edge_split(), BMO_elem_flag_enable, co, ELE_INNER, interp_v3_v3v3(), BMVert::no, normalize_v3(), BMEdge::v1, and BMEdge::v2.
Referenced by quad_2edge_split_innervert(), and subdivideedgenum().
static void bm_subdivide_multicut (BMesh * bm, BMEdge * edge, const SubDParams * params, BMVert * vsta, BMVert * vend) [static]
Definition at line 237 of file bmo_subdivide.c.
References alter_co(), BM_CHECK_ELEMENT, BMO_elem_flag_enable, BMVert::e, ELE_SPLIT, BMLoop::f, i, BMEdge::l, SubDParams::numcuts, SUBD_SPLIT, subdivideedgenum(), BMEdge::v1, and BMEdge::v2.
Referenced by bmo_edgebisect_exec(), and bmo_esubd_exec().
void bmo_edgebisect_exec (BMesh * bm, BMOperator * op)
Definition at line 1096 of file bmo_subdivide.c.
References BM_ALL, BM_data_layer_add(), BM_data_layer_free_n(), BM_EDGE, bm_subdivide_multicut(), BMO_ITER, BMO_slot_buffer_from_enabled_flag(), BMO_slot_int_get(), CD_SHAPEKEY, CustomData_number_of_layers(), ELE_SPLIT, SubDParams::numcuts, SubDParams::op, SubDParams::origkey, BMEdge::v1, BMEdge::v2, and BMesh::vdata.
void bmo_esubd_exec (BMesh * bm, BMOperator * op)
Definition at line 674 of file bmo_subdivide.c.
References angle(), BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BLI_array_growone, BLI_drand(), BLI_srandom(), BM_ALL, BM_CHECK_ELEMENT, BM_data_layer_add(), BM_data_layer_free_n(), BM_EDGE, BM_edge_share_vert_count(), BM_FACE, BM_face_split(), BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_ELEM_INDEX, BM_ITER_MESH, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, bm_subdivide_multicut(), BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_get(), BMO_slot_int_get(), BMO_slot_map_data_get(), BMO_slot_map_to_flag(), CD_SHAPEKEY, co, BMVert::co, SubDPattern::connectexec, copy_v3_v3(), CustomData_bmesh_get_n(), CustomData_number_of_layers(), BMHeader::data, BMOpSlot::data, dot_v3v3(), BMLoop::e, EDGE_PERCENT, ELE_INNER, ELE_SPLIT, fabsf, SubDFaceData::face, FACE_CUSTOMFILL, FALSE, SubDParams::fractal, BMVert::head, i, if(), BMOpSlot::len, SubDPattern::len, BMFace::len, normalize_v3(), NULL, SubDParams::numcuts, SubDParams::off, SubDParams::op, SubDParams::origkey, BMOpSlot::p, SubDFaceData::pat, PLEN, quad_1edge, quad_2edge_fan, quad_2edge_innervert, quad_2edge_path, quad_4edge, SubDParams::seed, SubDPattern::seledges, smooth(), SubDParams::smooth, SubDFaceData::start, sub_v3_v3v3(), SUBD_FAN, SUBD_INNERVERT, SUBD_PATH, SUBD_SPLIT, SubDFaceData::totedgesel, tri_1edge, tri_3edge, SubDParams::use_fractal, SubDParams::use_smooth, SubDParams::use_sphere, BMLoop::v, BMEdge::v1, BMEdge::v2, and BMesh::vdata.
static BMEdge* connect_smallest_face (BMesh * bm, BMVert * v1, BMVert * v2, BMFace ** r_nf) [static]
Definition at line 71 of file bmo_subdivide.c.
References BM_face_split(), BM_FACES_OF_VERT, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_FACE, BMLoop::e, FALSE, BMFace::len, and NULL.
Referenced by quad_1edge_split(), quad_2edge_split_fan(), quad_2edge_split_innervert(), quad_2edge_split_path(), quad_3edge_split(), quad_4edge_subdivide(), tri_1edge_split(), and tri_3edge_subdivide().
static void quad_1edge_split (BMesh * bm, BMFace * UNUSEDface, BMVert ** verts, const SubDParams * params) [static]
Definition at line 279 of file bmo_subdivide.c.
References add(), connect_smallest_face(), i, and SubDParams::numcuts.
static void quad_2edge_split_fan (BMesh * bm, BMFace * UNUSEDface, BMVert ** verts, const SubDParams * params) [static]
Definition at line 390 of file bmo_subdivide.c.
References connect_smallest_face(), i, and SubDParams::numcuts.
static void quad_2edge_split_innervert (BMesh * bm, BMFace * UNUSEDface, BMVert ** verts, const SubDParams * params) [static]
Definition at line 349 of file bmo_subdivide.c.
References bm_subdivide_edge_addvert(), connect_smallest_face(), i, SubDParams::numcuts, BMEdge::v1, and BMEdge::v2.
static void quad_2edge_split_path (BMesh * bm, BMFace * UNUSEDface, BMVert ** verts, const SubDParams * params) [static]
Definition at line 323 of file bmo_subdivide.c.
References connect_smallest_face(), i, and SubDParams::numcuts.
static void quad_3edge_split (BMesh * bm, BMFace * UNUSEDface, BMVert ** verts, const SubDParams * params) [static]
Definition at line 421 of file bmo_subdivide.c.
References add(), connect_smallest_face(), i, and SubDParams::numcuts.
static void quad_4edge_subdivide (BMesh * bm, BMFace * UNUSEDface, BMVert ** verts, const SubDParams * params) [static]
Definition at line 458 of file bmo_subdivide.c.
References BMESH_ASSERT, BMO_elem_flag_enable, connect_smallest_face(), ELE_INNER, i, MEM_callocN(), MEM_freeN(), NULL, SubDParams::numcuts, and subdivideedgenum().
static BMVert* subdivideedgenum (BMesh * bm, BMEdge * edge, BMEdge * oedge, int curpoint, int totpoint, const SubDParams * params, BMEdge ** newe, BMVert * vsta, BMVert * vend) [static]
Definition at line 217 of file bmo_subdivide.c.
References bm_subdivide_edge_addvert(), BMO_elem_flag_test, BMO_slot_map_float_get(), EDGE_PERCENT, and SubDParams::op.
Referenced by bm_subdivide_multicut(), quad_4edge_subdivide(), and tri_3edge_subdivide().
static void tri_1edge_split (BMesh * bm, BMFace * UNUSEDface, BMVert ** verts, const SubDParams * params) [static]
Definition at line 537 of file bmo_subdivide.c.
References connect_smallest_face(), i, and SubDParams::numcuts.
static void tri_3edge_subdivide (BMesh * bm, BMFace * UNUSEDface, BMVert ** verts, const SubDParams * params) [static]
Definition at line 563 of file bmo_subdivide.c.
References BMO_elem_flag_enable, connect_smallest_face(), ELE_INNER, i, MEM_callocN(), MEM_freeN(), SubDParams::numcuts, subdivideedgenum(), BMEdge::v1, and BMEdge::v2.
Variable Documentation
SubDPattern* patterns[] [static]
Initial value:
 {
    NULL,
    NULL,
    NULL,
    NULL,
    &quad_3edge,
    NULL,
}
Definition at line 657 of file bmo_subdivide.c.
SubDPattern quad_1edge [static]
Initial value:
 {
    {1, 0, 0, 0},
    quad_1edge_split,
    4,
}
Definition at line 308 of file bmo_subdivide.c.
Referenced by bmo_esubd_exec().
SubDPattern quad_2edge_fan [static]
Initial value:
 {
    {1, 1, 0, 0},
    quad_2edge_split_fan,
    4,
}
Definition at line 405 of file bmo_subdivide.c.
Referenced by bmo_esubd_exec().
SubDPattern quad_2edge_innervert [static]
Initial value:
 {
    {1, 1, 0, 0},
    quad_2edge_split_innervert,
    4,
}
Definition at line 375 of file bmo_subdivide.c.
Referenced by bmo_esubd_exec().
SubDPattern quad_2edge_path [static]
Initial value:
 {
    {1, 1, 0, 0},
    quad_2edge_split_path,
    4,
}
Definition at line 335 of file bmo_subdivide.c.
Referenced by bmo_esubd_exec().
SubDPattern quad_3edge [static]
Initial value:
 {
    {1, 1, 1, 0},
    quad_3edge_split,
    4,
}
Definition at line 442 of file bmo_subdivide.c.
SubDPattern quad_4edge [static]
Initial value:
 {
    {1, 1, 1, 1},
    quad_4edge_subdivide,
    4,
}
Definition at line 651 of file bmo_subdivide.c.
Referenced by bmo_esubd_exec().
SubDPattern tri_1edge [static]
Initial value:
 {
    {1, 0, 0},
    tri_1edge_split,
    3,
}
Definition at line 548 of file bmo_subdivide.c.
Referenced by bmo_esubd_exec().
SubDPattern tri_3edge [static]
Initial value:
 {
    {1, 1, 1},
    tri_3edge_subdivide,
    3,
}
Definition at line 644 of file bmo_subdivide.c.
Referenced by bmo_esubd_exec().