Blender: bmesh_iterators.c File Reference
bmesh_iterators.c File Reference
BMesh
#include "BLI_utildefines.h"
#include "bmesh.h"
#include "intern/bmesh_private.h"
Functions
void * BM_iter_at_index (BMesh *bm, const char itype, void *data, int index)
int BM_iter_as_array (BMesh *bm, const char itype, void *data, void **array, const int len)
Iterator as Array.
static void init_iterator (BMIter *iter)
Init Iterator.
void bmiter__vert_of_mesh_begin (BMIter *iter)
void * bmiter__vert_of_mesh_step (BMIter *iter)
void bmiter__edge_of_mesh_begin (BMIter *iter)
void * bmiter__edge_of_mesh_step (BMIter *iter)
void bmiter__face_of_mesh_begin (BMIter *iter)
void * bmiter__face_of_mesh_step (BMIter *iter)
void bmiter__edge_of_vert_begin (BMIter *iter)
void * bmiter__edge_of_vert_step (BMIter *iter)
void bmiter__face_of_vert_begin (BMIter *iter)
void * bmiter__face_of_vert_step (BMIter *iter)
void bmiter__loop_of_vert_begin (BMIter *iter)
void * bmiter__loop_of_vert_step (BMIter *iter)
void bmiter__loops_of_edge_begin (BMIter *iter)
void * bmiter__loops_of_edge_step (BMIter *iter)
void bmiter__loops_of_loop_begin (BMIter *iter)
void * bmiter__loops_of_loop_step (BMIter *iter)
void bmiter__face_of_edge_begin (BMIter *iter)
void * bmiter__face_of_edge_step (BMIter *iter)
void bmiter__vert_of_edge_begin (BMIter *iter)
void * bmiter__vert_of_edge_step (BMIter *iter)
void bmiter__vert_of_face_begin (BMIter *iter)
void * bmiter__vert_of_face_step (BMIter *iter)
void bmiter__edge_of_face_begin (BMIter *iter)
void * bmiter__edge_of_face_step (BMIter *iter)
void bmiter__loop_of_face_begin (BMIter *iter)
void * bmiter__loop_of_face_step (BMIter *iter)
Variables
const char bm_iter_itype_htype_map [BM_ITYPE_MAX]
Detailed Description
Functions to abstract looping over bmesh data structures.
See: bmesh_iterators_inlin.c too, some functions are here for speed reasons.
Definition in file bmesh_iterators.c.
Function Documentation
int BM_iter_as_array (BMesh * bm, const char itype, void * data, void ** array, const int len)
Iterator as Array.
Sometimes its convenient to get the iterator as an array to avoid multiple calls to BM_iter_at_index.
Definition at line 86 of file bmesh_iterators.c.
References BM_iter_new(), BM_iter_step(), i, and len().
Referenced by BM_mesh_remap().
void* BM_iter_at_index (BMesh * bm, const char itype, void * data, int index)
Note:
Use BM_vert_at_index / BM_edge_at_index / BM_face_at_index for mesh arrays.
Definition at line 57 of file bmesh_iterators.c.
References BM_iter_new(), BM_iter_step(), i, and NULL.
Referenced by bm_vert_loop_pair(), bpy_bmelemseq_subscript_int(), EDBM_uv_vert_map_create(), mesh_separate_material(), select_edgeloop_uv_vertex_map_get(), stitch_init(), and uv_faces_do_sticky().
void bmiter__edge_of_face_begin (BMIter * iter)
Definition at line 418 of file bmesh_iterators.c.
References BM_FACE_FIRST_LOOP, BMIter::firstloop, init_iterator(), BMIter::nextloop, and BMIter::pdata.
Referenced by BM_iter_init().
void* bmiter__edge_of_face_step (BMIter * iter)
Definition at line 424 of file bmesh_iterators.c.
References BMLoop::e, BMIter::firstloop, BMLoop::next, BMIter::nextloop, and NULL.
Referenced by BM_iter_init().
void bmiter__edge_of_mesh_begin (BMIter * iter)
Definition at line 151 of file bmesh_iterators.c.
References BLI_mempool_iternew(), BMIter::bm, BMesh::epool, and BMIter::pooliter.
Referenced by BM_iter_init().
void* bmiter__edge_of_mesh_step (BMIter * iter)
Definition at line 156 of file bmesh_iterators.c.
References BLI_mempool_iterstep(), and BMIter::pooliter.
Referenced by BM_iter_init().
void bmiter__edge_of_vert_begin (BMIter * iter)
Definition at line 177 of file bmesh_iterators.c.
References BMVert::e, BMIter::firstedge, init_iterator(), BMIter::nextedge, and BMIter::vdata.
Referenced by BM_iter_init().
void* bmiter__edge_of_vert_step (BMIter * iter)
Definition at line 186 of file bmesh_iterators.c.
References bmesh_disk_edge_next(), BMIter::firstedge, BMIter::nextedge, NULL, and BMIter::vdata.
Referenced by BM_iter_init().
void bmiter__face_of_edge_begin (BMIter * iter)
Definition at line 348 of file bmesh_iterators.c.
References BMIter::edata, BMIter::firstloop, init_iterator(), BMEdge::l, and BMIter::nextloop.
Referenced by BM_iter_init().
void* bmiter__face_of_edge_step (BMIter * iter)
Definition at line 358 of file bmesh_iterators.c.
References BMLoop::f, BMIter::firstloop, BMIter::nextloop, NULL, and BMLoop::radial_next.
Referenced by BM_iter_init().
void bmiter__face_of_mesh_begin (BMIter * iter)
Definition at line 162 of file bmesh_iterators.c.
References BLI_mempool_iternew(), BMIter::bm, BMesh::fpool, and BMIter::pooliter.
Referenced by BM_iter_init().
void* bmiter__face_of_mesh_step (BMIter * iter)
Definition at line 167 of file bmesh_iterators.c.
References BLI_mempool_iterstep(), and BMIter::pooliter.
Referenced by BM_iter_init().
void bmiter__face_of_vert_begin (BMIter * iter)
Definition at line 202 of file bmesh_iterators.c.
References bmesh_disk_faceedge_find_first(), bmesh_disk_facevert_count(), bmesh_radial_faceloop_find_first(), BMIter::count, BMVert::e, BMIter::firstedge, BMIter::firstloop, init_iterator(), BMEdge::l, BMIter::nextedge, BMIter::nextloop, and BMIter::vdata.
Referenced by BM_iter_init().
void* bmiter__face_of_vert_step (BMIter * iter)
Definition at line 215 of file bmesh_iterators.c.
References bmesh_disk_faceedge_find_next(), bmesh_radial_faceloop_find_first(), bmesh_radial_faceloop_find_next(), BMIter::count, BMLoop::f, BMIter::firstloop, BMEdge::l, BMIter::nextedge, BMIter::nextloop, NULL, and BMIter::vdata.
Referenced by BM_iter_init().
void bmiter__loop_of_face_begin (BMIter * iter)
Definition at line 438 of file bmesh_iterators.c.
References BM_FACE_FIRST_LOOP, BMIter::firstloop, init_iterator(), BMIter::nextloop, and BMIter::pdata.
Referenced by BM_iter_init().
void* bmiter__loop_of_face_step (BMIter * iter)
Definition at line 444 of file bmesh_iterators.c.
References BMIter::firstloop, BMLoop::next, BMIter::nextloop, and NULL.
Referenced by BM_iter_init().
void bmiter__loop_of_vert_begin (BMIter * iter)
Definition at line 240 of file bmesh_iterators.c.
References bmesh_disk_faceedge_find_first(), bmesh_disk_facevert_count(), bmesh_radial_faceloop_find_first(), BMIter::count, BMVert::e, BMIter::firstedge, BMIter::firstloop, init_iterator(), BMEdge::l, BMIter::nextedge, BMIter::nextloop, and BMIter::vdata.
Referenced by BM_iter_init().
void* bmiter__loop_of_vert_step (BMIter * iter)
Definition at line 253 of file bmesh_iterators.c.
References bmesh_disk_faceedge_find_next(), bmesh_radial_faceloop_find_first(), bmesh_radial_faceloop_find_next(), BMIter::count, BMIter::firstloop, BMEdge::l, BMIter::nextedge, BMIter::nextloop, NULL, and BMIter::vdata.
Referenced by BM_iter_init().
void bmiter__loops_of_edge_begin (BMIter * iter)
Definition at line 278 of file bmesh_iterators.c.
References BMIter::edata, BMIter::firstloop, init_iterator(), BMEdge::l, and BMIter::nextloop.
Referenced by BM_iter_init().
void* bmiter__loops_of_edge_step (BMIter * iter)
Definition at line 290 of file bmesh_iterators.c.
References BMIter::firstloop, BMIter::nextloop, NULL, and BMLoop::radial_next.
Referenced by BM_iter_init().
void bmiter__loops_of_loop_begin (BMIter * iter)
Definition at line 309 of file bmesh_iterators.c.
References BMIter::firstloop, init_iterator(), BMIter::ldata, BMIter::nextloop, NULL, and BMLoop::radial_next.
Referenced by BM_iter_init().
void* bmiter__loops_of_loop_step (BMIter * iter)
Definition at line 325 of file bmesh_iterators.c.
References BMIter::firstloop, BMIter::nextloop, NULL, and BMLoop::radial_next.
Referenced by BM_iter_init().
void bmiter__vert_of_edge_begin (BMIter * iter)
Definition at line 375 of file bmesh_iterators.c.
References BMIter::count, and init_iterator().
Referenced by BM_iter_init().
void* bmiter__vert_of_edge_step (BMIter * iter)
Definition at line 381 of file bmesh_iterators.c.
References BMIter::count, BMIter::edata, NULL, BMEdge::v1, and BMEdge::v2.
Referenced by BM_iter_init().
void bmiter__vert_of_face_begin (BMIter * iter)
Definition at line 398 of file bmesh_iterators.c.
References BM_FACE_FIRST_LOOP, BMIter::firstloop, init_iterator(), BMIter::nextloop, and BMIter::pdata.
Referenced by BM_iter_init().
void* bmiter__vert_of_face_step (BMIter * iter)
Definition at line 404 of file bmesh_iterators.c.
References BMIter::firstloop, BMLoop::next, BMIter::nextloop, NULL, and BMLoop::v.
Referenced by BM_iter_init().
void bmiter__vert_of_mesh_begin (BMIter * iter)
Notes on iterator implementation:
Iterators keep track of the next element in a sequence. When a step() callback is invoked the current value of 'next' is stored to be returned later and the next variable is incremented.
When the end of a sequence is reached, next should always equal NULL
The 'bmiter__' prefix is used because these are used in bmesh_iterators_inine.c but should otherwise be seen as private.
Definition at line 140 of file bmesh_iterators.c.
References BLI_mempool_iternew(), BMIter::bm, BMIter::pooliter, and BMesh::vpool.
Referenced by BM_iter_init().
void* bmiter__vert_of_mesh_step (BMIter * iter)
Definition at line 145 of file bmesh_iterators.c.
References BLI_mempool_iterstep(), and BMIter::pooliter.
Referenced by BM_iter_init().
static void init_iterator (BMIter * iter) [static]
Init Iterator.
Clears the internal state of an iterator for begin() callbacks.
Definition at line 113 of file bmesh_iterators.c.
References BMIter::firstedge, BMIter::firstloop, BMIter::firstpoly, BMIter::firstvert, BMIter::ldata, BMIter::nextedge, BMIter::nextloop, BMIter::nextpoly, BMIter::nextvert, and NULL.
Referenced by bmiter__edge_of_face_begin(), bmiter__edge_of_vert_begin(), bmiter__face_of_edge_begin(), bmiter__face_of_vert_begin(), bmiter__loop_of_face_begin(), bmiter__loop_of_vert_begin(), bmiter__loops_of_edge_begin(), bmiter__loops_of_loop_begin(), bmiter__vert_of_edge_begin(), and bmiter__vert_of_face_begin().
Variable Documentation
const char bm_iter_itype_htype_map[BM_ITYPE_MAX]
Initial value:
 {
    '\0',
    BM_VERT,
    BM_EDGE,
    BM_FACE,
    BM_EDGE,
    BM_FACE,
    BM_LOOP,
    BM_VERT,
    BM_FACE,
    BM_VERT,
    BM_EDGE,
    BM_LOOP,
    BM_LOOP,
    BM_LOOP,
    BM_LOOP
}
Definition at line 36 of file bmesh_iterators.c.
Referenced by bpy_bmelemseq_index_update().