Blender: uvedit_draw.c File Reference
uvedit_draw.c File Reference
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_DerivedMesh.h"
#include "BKE_mesh.h"
#include "BKE_tessmesh.h"
#include "BLI_array.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "ED_util.h"
#include "ED_image.h"
#include "ED_mesh.h"
#include "ED_uvedit.h"
#include "UI_resources.h"
#include "uvedit_intern.h"
Functions
static void drawcursor_sima (SpaceImage *sima, ARegion *ar)
static int draw_uvs_face_check (Scene *scene)
static void draw_uvs_shadow (Object *obedit)
static int draw_uvs_dm_shadow (DerivedMesh *dm)
static void draw_uvs_stretch (SpaceImage *sima, Scene *scene, BMEditMesh *em, MTexPoly *activetf)
static void draw_uvs_other (Scene *scene, Object *obedit, Image *curimage)
static void draw_uvs_texpaint (SpaceImage *sima, Scene *scene, Object *ob)
static void draw_uvs (SpaceImage *sima, Scene *scene, Object *obedit)
void draw_uvedit_main (SpaceImage *sima, ARegion *ar, Scene *scene, Object *obedit, Object *obact)
Detailed Description
Definition in file uvedit_draw.c.
Function Documentation
void draw_uvedit_main (SpaceImage * sima, ARegion * ar, Scene * scene, Object * obedit, Object * obact)
Definition at line 874 of file uvedit_draw.c.
References draw_uvs(), draw_uvs_shadow(), draw_uvs_texpaint(), drawcursor_sima(), ED_space_image_show_uvedit(), ED_space_image_show_uvshadow(), Object::mode, OB_MESH, OB_MODE_TEXTURE_PAINT, Scene::toolsettings, Object::type, and ToolSettings::use_uv_sculpt.
Referenced by image_main_area_draw().
static void draw_uvs (SpaceImage * sima, Scene * scene, Object * obedit) [static]
Definition at line 439 of file uvedit_draw.c.
References bglBegin(), bglEnd(), bglVertex2fv(), BMEditMesh::bm, BM_active_face_get(), BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_TAG, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, CD_MASK_BAREMESH, CD_MASK_MTFACE, CD_MLOOPUV, CD_MTEXPOLY, cpack, CustomData_bmesh_get(), BMHeader::data, Object::data, BMEditMesh::derivedFinal, draw_uvs_dm_shadow(), draw_uvs_face_check(), draw_uvs_other(), draw_uvs_stretch(), Mesh::drawflag, SpaceImage::dt_uv, EDBM_mtexpoly_active_get(), Mesh::edit_btmesh, editbmesh_get_derived_cage_and_final(), FALSE, MLoopUV::flag, SpaceImage::flag, BMLoop::head, BMFace::head, i, SpaceImage::image, BMesh::ldata, ME_DRAWEDGES, MLOOPUV_PINNED, BMLoop::next, NULL, StitchPreviewer::num_polys, StitchPreviewer::num_static_tris, StitchPreviewer::num_stitchable, StitchPreviewer::num_unstitchable, BMesh::pdata, poly_uv_center(), StitchPreviewer::preview_polys, StitchPreviewer::preview_stitchable, StitchPreviewer::preview_unstitchable, DerivedMesh::release, SCE_SELECT_VERTEX, ToolSettings::selectmode, setlinestyle(), SI_DRAW_OTHER, SI_DRAW_STRETCH, SI_DRAWSHADOW, SI_NO_DRAWFACES, SI_SMOOTH_UV, SI_UVDT_BLACK, SI_UVDT_DASH, SI_UVDT_OUTLINE, SI_UVDT_WHITE, StitchPreviewer::static_tris, stipple_quarttone, TH_EDITMESH_ACTIVE, TH_FACE, TH_FACE_DOT, TH_FACE_SELECT, TH_FACEDOT_SIZE, TH_STITCH_PREVIEW_ACTIVE, TH_STITCH_PREVIEW_EDGE, TH_STITCH_PREVIEW_FACE, TH_STITCH_PREVIEW_STITCHABLE, TH_STITCH_PREVIEW_UNSTITCHABLE, TH_STITCH_PREVIEW_VERT, TH_VERTEX, TH_VERTEX_SELECT, TH_VERTEX_SIZE, TH_WIRE, Scene::toolsettings, MTexPoly::tpage, UI_GetThemeColor4ubv(), UI_GetThemeValuef(), UI_ThemeColor(), UI_ThemeColor4(), MLoopUV::uv, ToolSettings::uv_flag, uv_get_stitch_previewer(), UV_SELECT_VERTEX, ToolSettings::uv_selectmode, UV_SYNC_SELECTION, uvedit_edge_select_test(), uvedit_face_select_test(), uvedit_face_visible_test(), uvedit_uv_select_test(), and StitchPreviewer::uvs_per_polygon.
Referenced by draw_uvedit_main().
static int draw_uvs_dm_shadow (DerivedMesh * dm) [static]
Definition at line 150 of file uvedit_draw.c.
References CD_MLOOPUV, CustomData_has_layer(), DerivedMesh::drawUVEdges, and DerivedMesh::loopData.
Referenced by draw_uvs().
static int draw_uvs_face_check (Scene * scene) [static]
Definition at line 110 of file uvedit_draw.c.
References SCE_SELECT_FACE, ToolSettings::selectmode, Scene::toolsettings, ToolSettings::uv_flag, UV_SELECT_FACE, ToolSettings::uv_selectmode, and UV_SYNC_SELECTION.
Referenced by draw_uvs().
static void draw_uvs_other (Scene * scene, Object * obedit, Image * curimage) [static]
Definition at line 370 of file uvedit_draw.c.
References Scene::base, Object::data, ListBase::first, Base::flag, Scene::lay, Base::lay, MPoly::loopstart, Mesh::mloopuv, Mesh::mpoly, Mesh::mtpoly, Base::next, OB_MESH, OB_RESTRICT_VIEW, Base::object, Object::restrictflag, SELECT, MPoly::totloop, Mesh::totpoly, MTexPoly::tpage, Object::type, and MLoopUV::uv.
Referenced by draw_uvs(), and draw_uvs_texpaint().
static void draw_uvs_shadow (Object * obedit) [static]
Definition at line 127 of file uvedit_draw.c.
References BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::head, BMesh::ldata, and MLoopUV::uv.
Referenced by draw_uvedit_main().
static void draw_uvs_stretch (SpaceImage * sima, Scene * scene, BMEditMesh * em, MTexPoly * activetf) [static]
Definition at line 163 of file uvedit_draw.c.
References angle_normalized_v2v2(), angle_normalized_v3v3(), angle_v2v2v2(), angle_v3v3v3(), BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BMEditMesh::bm, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_TAG, BM_face_calc_area(), BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_ELEM_INDEX, BM_ITER_MESH, BM_LOOPS_OF_FACE, CD_MLOOPUV, CD_MTEXPOLY, BMVert::co, copy_v2_v2(), CustomData_bmesh_get(), BMHeader::data, SpaceImage::dt_uvstretch, ED_space_image_uv_aspect(), fabsf, BMLoop::head, BMFace::head, i, SpaceImage::image, BMesh::ldata, BMFace::len, M_PI, normalize_v2(), normalize_v3(), NULL, BMesh::pdata, poly_copy_aspect(), poly_uv_area(), powf, BMLoop::prev, RAD2DEG, SI_UVDT_STRETCH_ANGLE, SI_UVDT_STRETCH_AREA, sub_v2_v2v2(), sub_v3_v3v3(), MLoopUV::uv, uvedit_face_visible_test(), BMLoop::v, and weight_to_rgb().
Referenced by draw_uvs().
static void draw_uvs_texpaint (SpaceImage * sima, Scene * scene, Object * ob) [static]
Definition at line 408 of file uvedit_draw.c.
References Object::data, draw_uvs_other(), ED_space_image(), SpaceImage::flag, MPoly::loopstart, Mesh::mloopuv, Mesh::mpoly, Mesh::mtface, Mesh::mtpoly, SI_DRAW_OTHER, MPoly::totloop, Mesh::totpoly, MTexPoly::tpage, and MLoopUV::uv.
Referenced by draw_uvedit_main().
static void drawcursor_sima (SpaceImage * sima, ARegion * ar) [static]
Definition at line 66 of file uvedit_draw.c.
References cpack, SpaceImage::cursor, ED_space_image_size(), ED_space_image_zoom(), fdrawline(), and setlinestyle().
Referenced by draw_uvedit_main().