Blender: space_script.c File Reference
space_script.c File Reference
script space
#include <string.h>
#include <stdio.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "ED_space_api.h"
#include "ED_screen.h"
#include "BIF_gl.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "script_intern.h"
Functions
static SpaceLink * script_new (const bContext *UNUSED(C))
static void script_free (SpaceLink *sl)
static void script_init (struct wmWindowManager *UNUSED(wm), ScrArea *UNUSED(sa))
static SpaceLink * script_duplicate (SpaceLink *sl)
static void script_main_area_init (wmWindowManager *wm, ARegion *ar)
static void script_main_area_draw (const bContext *C, ARegion *ar)
static void script_header_area_init (wmWindowManager *UNUSED(wm), ARegion *ar)
static void script_header_area_draw (const bContext *C, ARegion *ar)
static void script_main_area_listener (ARegion *UNUSED(ar), wmNotifier *UNUSED(wmn))
void ED_spacetype_script (void)
Detailed Description
Definition in file space_script.c.
Function Documentation
void ED_spacetype_script (void)
Definition at line 190 of file space_script.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizey, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, script_duplicate(), script_free(), script_header_area_draw(), script_header_area_init(), script_init(), script_keymap(), script_main_area_draw(), script_main_area_init(), script_main_area_listener(), script_new(), script_operatortypes(), SPACE_SCRIPT, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
static SpaceLink* script_duplicate (SpaceLink * sl) [static]
Definition at line 119 of file space_script.c.
References MEM_dupallocN().
Referenced by ED_spacetype_script().
static void script_free (SpaceLink * sl) [static]
Definition at line 97 of file space_script.c.
References SpaceScript::but_refs, NULL, and SpaceScript::script.
Referenced by ED_spacetype_script().
static void script_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 177 of file space_script.c.
References ED_region_header().
Referenced by ED_spacetype_script().
static void script_header_area_init (wmWindowManager * UNUSEDwm, ARegion * ar) [static]
Definition at line 172 of file space_script.c.
References ED_region_header_init().
Referenced by ED_spacetype_script().
static void script_init (struct wmWindowManager * UNUSEDwm, ScrArea * UNUSEDsa) [static]
Definition at line 114 of file space_script.c.
Referenced by ED_spacetype_script().
static void script_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 142 of file space_script.c.
References CTX_wm_space_data(), SpaceScript::script, TH_BACK, UI_ThemeClearColor(), UI_view2d_view_ortho(), UI_view2d_view_restore(), and ARegion::v2d.
Referenced by ED_spacetype_script().
static void script_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 131 of file space_script.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, SPACE_SCRIPT, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_STANDARD, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_script().
static void script_main_area_listener (ARegion * UNUSEDar, wmNotifier * UNUSEDwmn) [static]
Definition at line 182 of file space_script.c.
Referenced by ED_spacetype_script().
static SpaceLink* script_new (const bContext * UNUSEDC) [static]
Definition at line 68 of file space_script.c.
References ARegion::alignment, BLI_addtail(), MEM_callocN(), SpaceScript::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_SCRIPT, and SpaceScript::spacetype.
Referenced by ED_spacetype_script().