Blender: tracking.c File Reference
tracking.c File Reference
blenkernel
#include <stddef.h>
#include <limits.h>
#include <math.h>
#include <memory.h>
#include "MEM_guardedalloc.h"
#include "DNA_gpencil_types.h"
#include "DNA_camera_types.h"
#include "DNA_movieclip_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "BLI_math_base.h"
#include "BLI_listbase.h"
#include "BLI_ghash.h"
#include "BLI_path_util.h"
#include "BLI_string.h"
#include "BLI_threads.h"
#include "BKE_global.h"
#include "BKE_tracking.h"
#include "BKE_movieclip.h"
#include "BKE_object.h"
#include "BKE_scene.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
Classes
struct MovieDistortion
struct TracksMap
struct TrackContext
struct MovieTrackingContext
struct MovieReconstructContext
struct ReconstructProgressData
Typedefs
typedef struct MovieDistortion MovieDistortion
typedef struct TracksMap TracksMap
typedef struct TrackContext TrackContext
typedef struct MovieTrackingContext MovieTrackingContext
typedef struct
MovieReconstructContext MovieReconstructContext
typedef struct
ReconstructProgressData ReconstructProgressData
Functions
void BKE_tracking_init_settings (MovieTracking *tracking)
void BKE_tracking_clamp_track (MovieTrackingTrack *track, int event)
void BKE_tracking_track_flag (MovieTrackingTrack *track, int area, int flag, int clear)
MovieTrackingTrack * BKE_tracking_add_track (MovieTracking *tracking, ListBase *tracksbase, float x, float y, int framenr, int width, int height)
MovieTrackingMarker * BKE_tracking_insert_marker (MovieTrackingTrack *track, MovieTrackingMarker *marker)
void BKE_tracking_delete_marker (MovieTrackingTrack *track, int framenr)
MovieTrackingMarker * BKE_tracking_get_marker (MovieTrackingTrack *track, int framenr)
MovieTrackingMarker * BKE_tracking_ensure_marker (MovieTrackingTrack *track, int framenr)
MovieTrackingMarker * BKE_tracking_exact_marker (MovieTrackingTrack *track, int framenr)
int BKE_tracking_has_marker (MovieTrackingTrack *track, int framenr)
int BKE_tracking_has_enabled_marker (MovieTrackingTrack *track, int framenr)
void BKE_tracking_free_track (MovieTrackingTrack *track)
static void put_disabled_marker (MovieTrackingTrack *track, MovieTrackingMarker *ref_marker, int before, int overwrite)
void BKE_tracking_clear_path (MovieTrackingTrack *track, int ref_frame, int action)
void BKE_tracking_join_tracks (MovieTrackingTrack *dst_track, MovieTrackingTrack *src_track)
static void tracking_tracks_free (ListBase *tracks)
static void tracking_reconstruction_free (MovieTrackingReconstruction *reconstruction)
static void tracking_object_free (MovieTrackingObject *object)
static void tracking_objects_free (ListBase *objects)
void BKE_tracking_free (MovieTracking *tracking)
static MovieTrackingTrack * duplicate_track (MovieTrackingTrack *track)
void BKE_tracking_free_clipboard (void)
void BKE_tracking_clipboard_copy_tracks (MovieTracking *tracking, MovieTrackingObject *object)
int BKE_tracking_clipboard_has_tracks (void)
void BKE_tracking_clipboard_paste_tracks (MovieTracking *tracking, MovieTrackingObject *object)
static TracksMap * tracks_map_new (const char *object_name, int is_camera, int num_tracks, int customdata_size)
static int tracks_map_size (TracksMap *map)
static void tracks_map_get (TracksMap *map, int index, MovieTrackingTrack **track, void **customdata)
static void tracks_map_insert (TracksMap *map, MovieTrackingTrack *track, void *customdata)
static void tracks_map_merge (TracksMap *map, MovieTracking *tracking)
static void tracks_map_free (TracksMap *map, void(*customdata_free)(void *customdata))
MovieTrackingContext * BKE_tracking_context_new (MovieClip *clip, MovieClipUser *user, short backwards, short sequence)
static void track_context_free (void *customdata)
void BKE_tracking_context_free (MovieTrackingContext *context)
void BKE_tracking_disable_imbuf_channels (ImBuf *ibuf, int disable_red, int disable_green, int disable_blue, int grayscale)
static void disable_imbuf_channels (ImBuf *ibuf, MovieTrackingTrack *track, int grayscale)
static ImBuf * get_area_imbuf (ImBuf *ibuf, MovieTrackingTrack *track, MovieTrackingMarker *marker, float min[2], float max[2], int margin, int anchored, float pos[2], int origin[2])
ImBuf * BKE_tracking_get_pattern_imbuf (ImBuf *ibuf, MovieTrackingTrack *track, MovieTrackingMarker *marker, int margin, int anchored, float pos[2], int origin[2])
ImBuf * BKE_tracking_get_search_imbuf (ImBuf *ibuf, MovieTrackingTrack *track, MovieTrackingMarker *marker, int margin, int anchored, float pos[2], int origin[2])
void BKE_tracking_sync (MovieTrackingContext *context)
void BKE_tracking_sync_user (MovieClipUser *user, MovieTrackingContext *context)
int BKE_tracking_next (MovieTrackingContext *context)
int BKE_tracking_can_reconstruct (MovieTracking *tracking, MovieTrackingObject *object, char *error_msg, int error_size)
MovieReconstructContext * BKE_tracking_reconstruction_context_new (MovieTracking *tracking, MovieTrackingObject *object, int keyframe1, int keyframe2, int width, int height)
void BKE_tracking_reconstruction_context_free (MovieReconstructContext *context)
void BKE_tracking_solve_reconstruction (MovieReconstructContext *context, short *stop, short *do_update, float *progress, char *stats_message, int message_size)
int BKE_tracking_finish_reconstruction (MovieReconstructContext *context, MovieTracking *tracking)
void BKE_track_unique_name (ListBase *tracksbase, MovieTrackingTrack *track)
MovieTrackingTrack * BKE_tracking_named_track (MovieTracking *tracking, MovieTrackingObject *object, const char *name)
static int reconstruction_camera_index (MovieTrackingReconstruction *reconstruction, int framenr, int nearest)
static void scale_reconstructed_camera (MovieTrackingObject *object, float mat[4][4])
MovieReconstructedCamera * BKE_tracking_get_reconstructed_camera (MovieTracking *tracking, MovieTrackingObject *object, int framenr)
void BKE_tracking_get_interpolated_camera (MovieTracking *tracking, MovieTrackingObject *object, int framenr, float mat[4][4])
void BKE_get_tracking_mat (Scene *scene, Object *ob, float mat[4][4])
void BKE_tracking_camera_shift (MovieTracking *tracking, int winx, int winy, float *shiftx, float *shifty)
void BKE_tracking_camera_to_blender (MovieTracking *tracking, Scene *scene, Camera *camera, int width, int height)
void BKE_tracking_projection_matrix (MovieTracking *tracking, MovieTrackingObject *object, int framenr, int winx, int winy, float mat[4][4])
ListBase * BKE_tracking_get_tracks (MovieTracking *tracking)
MovieTrackingTrack * BKE_tracking_active_track (MovieTracking *tracking)
MovieTrackingObject * BKE_tracking_active_object (MovieTracking *tracking)
MovieTrackingObject * BKE_tracking_get_camera_object (MovieTracking *tracking)
ListBase * BKE_tracking_object_tracks (MovieTracking *tracking, MovieTrackingObject *object)
MovieTrackingReconstruction * BKE_tracking_object_reconstruction (MovieTracking *tracking, MovieTrackingObject *object)
MovieTrackingReconstruction * BKE_tracking_get_reconstruction (MovieTracking *tracking)
void BKE_tracking_apply_intrinsics (MovieTracking *tracking, float co[2], float nco[2])
void BKE_tracking_invert_intrinsics (MovieTracking *tracking, float co[2], float nco[2])
void BKE_tracking_detect_fast (MovieTracking *tracking, ListBase *tracksbase, ImBuf *ibuf, int framenr, int margin, int min_trackness, int min_distance, bGPDlayer *layer, int place_outside_layer)
MovieTrackingTrack * BKE_tracking_indexed_track (MovieTracking *tracking, int tracknr, ListBase **tracksbase_r)
static int stabilization_median_point (MovieTracking *tracking, int framenr, float median[2])
static void calculate_stabdata (MovieTracking *tracking, int framenr, float width, float height, float firstmedian[2], float median[2], float loc[2], float *scale, float *angle)
static float stabilization_auto_scale_factor (MovieTracking *tracking, int width, int height)
static ImBuf * stabilize_alloc_ibuf (ImBuf *cacheibuf, ImBuf *srcibuf, int fill)
void BKE_tracking_stabilization_data (MovieTracking *tracking, int framenr, int width, int height, float loc[2], float *scale, float *angle)
ImBuf * BKE_tracking_stabilize (MovieTracking *tracking, int framenr, ImBuf *ibuf, float loc[2], float *scale, float *angle)
void BKE_tracking_stabdata_to_mat4 (int width, int height, float aspect, float loc[2], float scale, float angle, float mat[4][4])
MovieDistortion * BKE_tracking_distortion_create (void)
MovieDistortion * BKE_tracking_distortion_copy (MovieDistortion *distortion)
void BKE_tracking_distortion_update (MovieDistortion *distortion, MovieTracking *tracking, int width, int height)
ImBuf * BKE_tracking_distortion_exec (MovieDistortion *distortion, MovieTracking *tracking, ImBuf *ibuf, int width, int height, float overscan, int undistort)
void BKE_tracking_distortion_destroy (MovieDistortion *distortion)
ImBuf * BKE_tracking_undistort (MovieTracking *tracking, ImBuf *ibuf, int width, int height, float overscan)
ImBuf * BKE_tracking_distort (MovieTracking *tracking, ImBuf *ibuf, int width, int height, float overscan)
void BKE_tracking_select_track (ListBase *tracksbase, MovieTrackingTrack *track, int area, int extend)
void BKE_tracking_deselect_track (MovieTrackingTrack *track, int area)
MovieTrackingObject * BKE_tracking_new_object (MovieTracking *tracking, const char *name)
void BKE_tracking_remove_object (MovieTracking *tracking, MovieTrackingObject *object)
void BKE_tracking_object_unique_name (MovieTracking *tracking, MovieTrackingObject *object)
MovieTrackingObject * BKE_tracking_named_object (MovieTracking *tracking, const char *name)
Variables
struct {
ListBase tracks
} tracking_clipboard
Detailed Description
Definition in file tracking.c.
Typedef Documentation
typedef struct MovieDistortion MovieDistortion
typedef struct MovieReconstructContext MovieReconstructContext
typedef struct MovieTrackingContext MovieTrackingContext
typedef struct ReconstructProgressData ReconstructProgressData
typedef struct TrackContext TrackContext
typedef struct TracksMap TracksMap
Function Documentation
void BKE_get_tracking_mat (Scene * scene, Object * ob, float mat[4][4])
Definition at line 2080 of file tracking.c.
References Scene::camera, scene_find_camera(), unit_m4(), and where_is_object_mat().
Referenced by bundle_midpoint(), do_set_scale(), draw_viewport_object_reconstruction(), followtrack_evaluate(), set_axis(), set_origin_exec(), and set_plane_exec().
void BKE_track_unique_name (ListBase * tracksbase, MovieTrackingTrack * track)
Definition at line 1945 of file tracking.c.
References BLI_uniquename(), and MovieTrackingTrack::name.
Referenced by BKE_tracking_add_track(), and BKE_tracking_clipboard_paste_tracks().
MovieTrackingObject* BKE_tracking_active_object (MovieTracking * tracking) [read]
Definition at line 2191 of file tracking.c.
References BLI_findlink(), MovieTracking::objectnr, and MovieTracking::objects.
Referenced by BKE_tracking_context_new(), BKE_tracking_get_reconstruction(), BKE_tracking_get_tracks(), copy_tracks_exec(), do_set_scale(), draw_tracking_tracks(), frame_jump_exec(), get_orientation_object(), paste_tracks_exec(), set_axis_exec(), set_orientation_poll(), set_origin_exec(), set_plane_exec(), set_solution_scale_poll(), solve_camera_initjob(), and tracking_object_remove_exec().
MovieTrackingTrack* BKE_tracking_active_track (MovieTracking * tracking) [read]
Definition at line 2175 of file tracking.c.
References MovieTracking::act_track, BKE_tracking_get_tracks(), BLI_findindex(), and NULL.
Referenced by BKE_movieclip_update_scopes(), border_select_graph_exec(), clean_tracks_exec(), clear_track_path_exec(), clip_delete_track(), delete_curve_exec(), delete_knot_exec(), draw_movieclip_cache(), draw_tracking_tracks(), draw_tracks_curves(), frame_jump_exec(), graph_disable_markers_exec(), graph_select_all_markers_exec(), hide_tracks_exec(), join_tracks_exec(), mouse_select(), mouse_select_curve(), mouse_select_knot(), select_groped_exec(), set_plane_exec(), stabilize_2d_set_rotation_exec(), track_copy_color_exec(), and tracks_map_merge().
MovieTrackingTrack* BKE_tracking_add_track (MovieTracking * tracking, ListBase * tracksbase, float x, float y, int framenr, int width, int height) [read]
Definition at line 228 of file tracking.c.
References BKE_track_unique_name(), BKE_tracking_clamp_track(), BKE_tracking_insert_marker(), BLI_addtail(), CLAMP_PYRAMID_LEVELS, copy_v2_v2(), MovieTrackingSettings::default_flag, MovieTrackingSettings::default_frames_limit, MovieTrackingSettings::default_margin, MovieTrackingSettings::default_minimum_correlation, MovieTrackingSettings::default_pattern_match, MovieTrackingSettings::default_pattern_size, MovieTrackingSettings::default_pyramid_levels, MovieTrackingSettings::default_search_size, MovieTrackingSettings::default_tracker, MovieTrackingTrack::flag, MovieTrackingMarker::framenr, MovieTrackingTrack::frames_limit, MovieTrackingTrack::margin, MEM_callocN(), MovieTrackingTrack::minimum_correlation, MovieTrackingTrack::name, negate_v2_v2(), MovieTrackingTrack::pat_max, MovieTrackingTrack::pat_min, MovieTrackingTrack::pattern_match, MovieTrackingMarker::pos, MovieTrackingTrack::pyramid_levels, MovieTrackingTrack::search_max, MovieTrackingTrack::search_min, MovieTracking::settings, MovieTrackingTrack::tracker, and TRACKER_KLT.
Referenced by add_marker().
void BKE_tracking_apply_intrinsics (MovieTracking * tracking, float co[2], float nco[2])
Definition at line 2235 of file tracking.c.
References MovieTracking::camera, MovieTrackingCamera::focal, MovieTrackingCamera::k1, MovieTrackingCamera::k2, MovieTrackingCamera::k3, MovieTrackingCamera::pixel_aspect, and MovieTrackingCamera::principal.
Referenced by draw_distortion(), draw_tracking_tracks(), and ED_clip_point_stable_pos().
void BKE_tracking_camera_shift (MovieTracking * tracking, int winx, int winy, float * shiftx, float * shifty)
Definition at line 2095 of file tracking.c.
References MovieTracking::camera, and MovieTrackingCamera::principal.
Referenced by BKE_tracking_camera_to_blender(), and BKE_tracking_projection_matrix().
void BKE_tracking_camera_to_blender (MovieTracking * tracking, Scene * scene, Camera * camera, int width, int height)
Definition at line 2102 of file tracking.c.
References BKE_tracking_camera_shift(), MovieTracking::camera, CAMERA_SENSOR_FIT_AUTO, MovieTrackingCamera::focal, Camera::lens, MovieTrackingCamera::pixel_aspect, Scene::r, Camera::sensor_fit, MovieTrackingCamera::sensor_width, Camera::sensor_x, Camera::shiftx, Camera::shifty, RenderData::xasp, RenderData::xsch, RenderData::yasp, and RenderData::ysch.
Referenced by solve_camera_freejob().
int BKE_tracking_can_reconstruct (MovieTracking * tracking, MovieTrackingObject * object, char * error_msg, int error_size)
Definition at line 1750 of file tracking.c.
References BKE_tracking_object_tracks(), BLI_strncpy(), FALSE, and TRUE.
Referenced by solve_camera_initjob().
void BKE_tracking_clamp_track (MovieTrackingTrack * track, int event)
Definition at line 102 of file tracking.c.
References CLAMP_PAT_DIM, CLAMP_PAT_POS, CLAMP_PYRAMID_LEVELS, CLAMP_SEARCH_DIM, CLAMP_SEARCH_POS, MAX2, MIN2, MovieTrackingTrack::pat_max, MovieTrackingTrack::pat_min, MovieTrackingTrack::pyramid_levels, MovieTrackingTrack::search_max, MovieTrackingTrack::search_min, sub_v2_v2v2(), SWAP, MovieTrackingTrack::tracker, and TRACKER_KLT.
Referenced by BKE_tracking_add_track(), marker_block_handler(), recalcData_clip(), and slide_marker_modal().
void BKE_tracking_clear_path (MovieTrackingTrack * track, int ref_frame, int action)
Definition at line 445 of file tracking.c.
References BKE_tracking_get_marker(), BKE_tracking_insert_marker(), MovieTrackingMarker::framenr, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, MEM_freeN(), MEM_reallocN(), NULL, put_disabled_marker(), TRACK_CLEAR_ALL, TRACK_CLEAR_REMAINED, and TRACK_CLEAR_UPTO.
Referenced by clear_track_path_exec().
void BKE_tracking_clipboard_copy_tracks (MovieTracking * tracking, MovieTrackingObject * object)
Definition at line 678 of file tracking.c.
References BKE_tracking_object_tracks(), BLI_addtail(), duplicate_track(), ListBase::first, MovieTrackingTrack::flag, MovieTrackingTrack::next, TRACK_HIDDEN, TRACK_SELECTED, and tracking_clipboard.
Referenced by copy_tracks_exec().
int BKE_tracking_clipboard_has_tracks (void)
Definition at line 694 of file tracking.c.
References NULL, and tracking_clipboard.
Referenced by paste_tracks_poll().
void BKE_tracking_clipboard_paste_tracks (MovieTracking * tracking, MovieTrackingObject * object)
Definition at line 699 of file tracking.c.
References BKE_track_unique_name(), BKE_tracking_object_tracks(), BLI_addtail(), duplicate_track(), MovieTrackingTrack::next, and tracking_clipboard.
Referenced by paste_tracks_exec().
void BKE_tracking_context_free (MovieTrackingContext * context)
Definition at line 1061 of file tracking.c.
References BLI_end_threaded_malloc(), MEM_freeN(), MovieTrackingContext::sequence, track_context_free(), MovieTrackingContext::tracks_map, and tracks_map_free().
Referenced by track_markers_exec(), and track_markers_freejob().
MovieTrackingContext* BKE_tracking_context_new (MovieClip * clip, MovieClipUser * user, short backwards, short sequence) [read]
Definition at line 930 of file tracking.c.
References MovieTrackingContext::backwards, BKE_movieclip_get_size(), BKE_tracking_active_object(), BKE_tracking_get_marker(), BKE_tracking_get_tracks(), BLI_begin_threaded_malloc(), MovieTrackingContext::clip, MovieTrackingContext::clip_flag, ListBase::first, MovieTrackingContext::first_time, MovieClip::flag, MovieTrackingObject::flag, MovieTrackingMarker::flag, MovieTrackingTrack::flag, MovieClipUser::framenr, log(), M_LN2, MARKER_DISABLED, MAX2, MCLIP_PROXY_RENDER_SIZE_FULL, MCLIP_TIMECODE_FLAGS, MEM_callocN(), MIN2, MovieTrackingTrack::minimum_correlation, MovieTrackingObject::name, MovieTrackingTrack::next, MovieTrackingTrack::pat_max, MovieTrackingTrack::pat_min, MovieTrackingTrack::pyramid_levels, MovieClipUser::render_flag, MovieClipUser::render_size, MovieTrackingTrack::search_max, MovieTrackingTrack::search_min, MovieTrackingContext::sequence, MovieTrackingContext::settings, MovieTracking::settings, MovieTrackingContext::sync_frame, TRACK_HIDDEN, TRACK_LOCKED, TRACK_SELECTED, MovieTrackingTrack::tracker, TRACKER_HYBRID, TRACKER_KLT, TRACKER_SAD, MovieClip::tracking, TRACKING_OBJECT_CAMERA, MovieTrackingContext::tracks_map, tracks_map_insert(), tracks_map_new(), TRUE, and MovieTrackingContext::user.
Referenced by track_markers_exec(), and track_markers_initjob().
void BKE_tracking_delete_marker (MovieTrackingTrack * track, int framenr)
Definition at line 314 of file tracking.c.
References MovieTrackingMarker::framenr, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, MEM_freeN(), MEM_reallocN(), and NULL.
Referenced by clip_delete_marker().
void BKE_tracking_deselect_track (MovieTrackingTrack * track, int area)
Definition at line 2940 of file tracking.c.
References BKE_tracking_track_flag(), and SELECT.
Referenced by deselect_all_tracks(), and mouse_select().
void BKE_tracking_detect_fast (MovieTracking * tracking, ListBase * tracksbase, ImBuf * ibuf, int framenr, int margin, int min_trackness, int min_distance, bGPDlayer * layer, int place_outside_layer)
Definition at line 2353 of file tracking.c.
References MEM_freeN(), ImBuf::x, and ImBuf::y.
Referenced by detect_features_exec().
void BKE_tracking_disable_imbuf_channels (ImBuf * ibuf, int disable_red, int disable_green, int disable_blue, int grayscale)
Definition at line 1074 of file tracking.c.
References g, IB_RECT_INVALID, if(), ImBuf::rect, ImBuf::rect_float, ImBuf::userflags, ImBuf::x, and ImBuf::y.
Referenced by disable_imbuf_channels(), and put_postprocessed_frame_to_cache().
ImBuf* BKE_tracking_distort (MovieTracking * tracking, ImBuf * ibuf, int width, int height, float overscan) [read]
Definition at line 2905 of file tracking.c.
References BKE_tracking_distortion_create(), BKE_tracking_distortion_exec(), MovieTracking::camera, MovieTrackingCamera::intrinsics, and NULL.
MovieDistortion* BKE_tracking_distortion_copy (MovieDistortion * distortion) [read]
Definition at line 2798 of file tracking.c.
References MovieDistortion::intrinsics, and MEM_callocN().
Referenced by local_merge(), and storage_copy().
MovieDistortion* BKE_tracking_distortion_create (void) [read]
Definition at line 2789 of file tracking.c.
References MEM_callocN().
Referenced by BKE_tracking_distort(), BKE_tracking_undistort(), exec(), and proxy_startjob().
void BKE_tracking_distortion_destroy (MovieDistortion * distortion)
Definition at line 2886 of file tracking.c.
References MovieDistortion::intrinsics, and MEM_freeN().
Referenced by BKE_tracking_free(), local_merge(), proxy_startjob(), and storage_free().
ImBuf* BKE_tracking_distortion_exec (MovieDistortion * distortion, MovieTracking * tracking, ImBuf * ibuf, int width, int height, float overscan, int undistort) [read]
Definition at line 2838 of file tracking.c.
References BKE_tracking_distortion_update(), ImBuf::channels, IB_RECT_INVALID, IMB_dupImBuf(), MovieDistortion::intrinsics, ImBuf::rect, ImBuf::rect_float, ImBuf::userflags, ImBuf::x, and ImBuf::y.
Referenced by BKE_tracking_distort(), BKE_tracking_undistort(), exec(), and get_undistorted_ibuf().
void BKE_tracking_distortion_update (MovieDistortion * distortion, MovieTracking * tracking, int width, int height)
Definition at line 2813 of file tracking.c.
References MovieTracking::camera, MovieTrackingCamera::focal, MovieDistortion::intrinsics, MovieTrackingCamera::k1, MovieTrackingCamera::k2, MovieTrackingCamera::k3, MovieTrackingCamera::pixel_aspect, and MovieTrackingCamera::principal.
Referenced by BKE_tracking_distortion_exec().
MovieTrackingMarker* BKE_tracking_ensure_marker (MovieTrackingTrack * track, int framenr) [read]
Definition at line 383 of file tracking.c.
References BKE_tracking_get_marker(), BKE_tracking_insert_marker(), and MovieTrackingMarker::framenr.
Referenced by create_slide_marker_data(), disable_markers_exec(), marker_block_handler(), marker_update_cb(), track_init_markers(), trackToTransData(), and ui_numedit_but_TRACKPREVIEW().
MovieTrackingMarker* BKE_tracking_exact_marker (MovieTrackingTrack * track, int framenr) [read]
Definition at line 400 of file tracking.c.
References BKE_tracking_get_marker(), MovieTrackingMarker::framenr, and NULL.
Referenced by BKE_tracking_has_enabled_marker(), BKE_tracking_has_marker(), BKE_tracking_insert_marker(), BKE_tracking_next(), delete_marker_exec(), and frame_jump_exec().
int BKE_tracking_finish_reconstruction (MovieReconstructContext * context, MovieTracking * tracking)
Definition at line 1918 of file tracking.c.
References BKE_tracking_named_object(), MovieTrackingReconstruction::error, FALSE, MovieTrackingReconstruction::flag, MovieReconstructContext::is_camera, MovieReconstructContext::object_name, MovieTracking::reconstruction, MovieReconstructContext::reprojection_error, TRACKING_RECONSTRUCTED, MovieReconstructContext::tracks_map, tracks_map_merge(), and TRUE.
Referenced by solve_camera_freejob().
void BKE_tracking_free (MovieTracking * tracking)
Definition at line 635 of file tracking.c.
References BKE_tracking_distortion_destroy(), MovieTracking::camera, IMB_freeImBuf(), MovieTrackingCamera::intrinsics, MovieTracking::objects, MovieTracking::reconstruction, MovieTrackingStabilization::scaleibuf, MovieTracking::stabilization, tracking_objects_free(), tracking_reconstruction_free(), tracking_tracks_free(), and MovieTracking::tracks.
Referenced by free_movieclip().
void BKE_tracking_free_clipboard (void)
Definition at line 664 of file tracking.c.
References BKE_tracking_free_track(), MEM_freeN(), MovieTrackingTrack::next, and tracking_clipboard.
Referenced by WM_exit_ext().
void BKE_tracking_free_track (MovieTrackingTrack * track)
Definition at line 422 of file tracking.c.
References MovieTrackingTrack::markers, and MEM_freeN().
Referenced by BKE_tracking_free_clipboard(), clean_tracks_exec(), clip_delete_track(), join_tracks_exec(), tracking_tracks_free(), tracks_map_free(), and tracks_map_merge().
MovieTrackingObject* BKE_tracking_get_camera_object (MovieTracking * tracking) [read]
Definition at line 2196 of file tracking.c.
References ListBase::first, MovieTrackingObject::flag, MovieTrackingObject::next, NULL, MovieTracking::objects, and TRACKING_OBJECT_CAMERA.
Referenced by camerasolver_evaluate(), followtrack_evaluate(), and test_constraints().
void BKE_tracking_get_interpolated_camera (MovieTracking * tracking, MovieTrackingObject * object, int framenr, float mat[4][4])
Definition at line 2051 of file tracking.c.
References BKE_tracking_object_reconstruction(), blend_m4_m4m4(), MovieTrackingReconstruction::cameras, copy_m4_m4(), MovieReconstructedCamera::framenr, reconstruction_camera_index(), scale_reconstructed_camera(), and unit_m4().
Referenced by bundle_midpoint(), camerasolver_evaluate(), draw_viewport_object_reconstruction(), followtrack_evaluate(), and objectsolver_evaluate().
MovieTrackingMarker* BKE_tracking_get_marker (MovieTrackingTrack * track, int framenr) [read]
Definition at line 338 of file tracking.c.
References MovieTrackingMarker::framenr, MovieTrackingTrack::last_marker, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, and NULL.
Referenced by BKE_movieclip_update_scopes(), BKE_tracking_clear_path(), BKE_tracking_context_new(), BKE_tracking_ensure_marker(), BKE_tracking_exact_marker(), border_select_exec(), calculate_stabdata(), cancelTransTracking(), circle_select_exec(), createTransTrackingTracksData(), draw_track_path(), draw_tracking_tracks(), find_nearest_track(), followtrack_evaluate(), mouse_select_curve(), select_all_exec(), select_groped_exec(), selected_boundbox(), slide_marker_customdata(), stabilization_median_point(), track_count_markers(), track_mouse_area(), and uiTemplateMarker().
ImBuf* BKE_tracking_get_pattern_imbuf (ImBuf * ibuf, MovieTrackingTrack * track, MovieTrackingMarker * marker, int margin, int anchored, float pos[2], int origin[2]) [read]
Definition at line 1191 of file tracking.c.
References get_area_imbuf(), MovieTrackingTrack::pat_max, and MovieTrackingTrack::pat_min.
Referenced by BKE_movieclip_update_scopes().
MovieReconstructedCamera* BKE_tracking_get_reconstructed_camera (MovieTracking * tracking, MovieTrackingObject * object, int framenr) [read]
Definition at line 2036 of file tracking.c.
References BKE_tracking_object_reconstruction(), MovieTrackingReconstruction::cameras, FALSE, NULL, and reconstruction_camera_index().
Referenced by BKE_tracking_projection_matrix(), and frame_jump_exec().
MovieTrackingReconstruction* BKE_tracking_get_reconstruction (MovieTracking * tracking) [read]
Definition at line 2228 of file tracking.c.
References BKE_tracking_active_object(), and BKE_tracking_object_reconstruction().
Referenced by clear_solution_exec(), draw_frame_curves(), draw_movieclip_cache(), and solve_camera_invoke().
ImBuf* BKE_tracking_get_search_imbuf (ImBuf * ibuf, MovieTrackingTrack * track, MovieTrackingMarker * marker, int margin, int anchored, float pos[2], int origin[2]) [read]
Definition at line 1197 of file tracking.c.
References get_area_imbuf(), MovieTrackingTrack::search_max, and MovieTrackingTrack::search_min.
ListBase* BKE_tracking_get_tracks (MovieTracking * tracking) [read]
Definition at line 2164 of file tracking.c.
References BKE_tracking_active_object(), MovieTrackingObject::flag, TRACKING_OBJECT_CAMERA, and MovieTracking::tracks.
Referenced by add_marker(), BKE_tracking_active_track(), BKE_tracking_context_new(), border_select_exec(), cancelTransTracking(), circle_select_exec(), clean_tracks_exec(), clear_invisible_track_selection(), clear_solution_exec(), clear_track_path_exec(), clip_graph_tracking_iterate(), clip_graph_tracking_values_iterate(), count_selected_bundles(), createTransTrackingCurvesData(), createTransTrackingTracksData(), delete_curve_exec(), delete_knot_exec(), delete_marker_exec(), delete_track_exec(), detect_features_exec(), disable_markers_exec(), do_set_scale(), draw_tracking_tracks(), hide_tracks_clear_exec(), hide_tracks_exec(), join_tracks_exec(), lock_tracks_exec(), mouse_select(), recalcData_clip(), select_all_exec(), select_groped_exec(), selected_boundbox(), slide_marker_customdata(), stabilize_2d_add_exec(), stabilize_2d_remove_exec(), stabilize_2d_select_exec(), track_copy_color_exec(), track_count_markers(), and track_init_markers().
int BKE_tracking_has_enabled_marker (MovieTrackingTrack * track, int framenr)
Definition at line 415 of file tracking.c.
References BKE_tracking_exact_marker(), MovieTrackingMarker::flag, and MARKER_DISABLED.
int BKE_tracking_has_marker (MovieTrackingTrack * track, int framenr)
Definition at line 410 of file tracking.c.
References BKE_tracking_exact_marker().
Referenced by put_disabled_marker().
MovieTrackingTrack* BKE_tracking_indexed_track (MovieTracking * tracking, int tracknr, ListBase ** tracksbase_r) [read]
Definition at line 2383 of file tracking.c.
References BKE_tracking_object_tracks(), ListBase::first, MovieTrackingTrack::flag, MovieTrackingTrack::next, NULL, MovieTracking::objects, and TRACK_HAS_BUNDLE.
Referenced by mouse_select().
void BKE_tracking_init_settings (MovieTracking * tracking)
Definition at line 78 of file tracking.c.
References BKE_tracking_new_object(), MovieTracking::camera, CAMERA_UNITS_MM, MovieTrackingSettings::default_minimum_correlation, MovieTrackingSettings::default_pattern_size, MovieTrackingSettings::default_pyramid_levels, MovieTrackingSettings::default_search_size, MovieTrackingSettings::default_tracker, MovieTrackingSettings::dist, MovieTrackingSettings::keyframe1, MovieTrackingSettings::keyframe2, MovieTrackingStabilization::locinf, MovieTrackingStabilization::maxscale, MovieTrackingSettings::object_distance, MovieTrackingCamera::pixel_aspect, MovieTrackingStabilization::rotinf, MovieTrackingStabilization::scaleinf, MovieTrackingCamera::sensor_width, MovieTracking::settings, MovieTracking::stabilization, TRACKER_HYBRID, and MovieTrackingCamera::units.
Referenced by movieclip_alloc().
MovieTrackingMarker* BKE_tracking_insert_marker (MovieTrackingTrack * track, MovieTrackingMarker * marker) [read]
Definition at line 278 of file tracking.c.
References BKE_tracking_exact_marker(), MovieTrackingMarker::framenr, MovieTrackingTrack::last_marker, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, MEM_callocN(), MEM_reallocN(), and NULL.
Referenced by BKE_tracking_add_track(), BKE_tracking_clear_path(), BKE_tracking_ensure_marker(), BKE_tracking_next(), and put_disabled_marker().
void BKE_tracking_invert_intrinsics (MovieTracking * tracking, float co[2], float nco[2])
Definition at line 2260 of file tracking.c.
References MovieTracking::camera, MovieTrackingCamera::focal, MovieTrackingCamera::k1, MovieTrackingCamera::k2, MovieTrackingCamera::k3, MovieTrackingCamera::pixel_aspect, and MovieTrackingCamera::principal.
Referenced by BKE_movieclip_update_scopes(), draw_distortion(), and ED_clip_point_undistorted_pos().
void BKE_tracking_join_tracks (MovieTrackingTrack * dst_track, MovieTrackingTrack * src_track)
Definition at line 502 of file tracking.c.
References MovieTrackingMarker::flag, MovieTrackingMarker::framenr, i, interp_v2_v2v2(), inverse(), len(), MARKER_DISABLED, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, MEM_callocN(), MEM_freeN(), and MovieTrackingMarker::pos.
Referenced by join_tracks_exec().
MovieTrackingObject* BKE_tracking_named_object (MovieTracking * tracking, const char * name) [read]
Definition at line 3008 of file tracking.c.
References ListBase::first, MovieTrackingObject::name, MovieTrackingObject::next, NULL, and MovieTracking::objects.
Referenced by BKE_tracking_finish_reconstruction(), followtrack_evaluate(), objectsolver_evaluate(), test_constraints(), and tracks_map_merge().
MovieTrackingTrack* BKE_tracking_named_track (MovieTracking * tracking, MovieTrackingObject * object, const char * name) [read]
Definition at line 1950 of file tracking.c.
References BKE_tracking_object_tracks(), ListBase::first, MovieTrackingTrack::name, MovieTrackingTrack::next, and NULL.
Referenced by followtrack_evaluate(), and test_constraints().
MovieTrackingObject* BKE_tracking_new_object (MovieTracking * tracking, const char * name) [read]
Definition at line 2945 of file tracking.c.
References BKE_tracking_object_unique_name(), BLI_addtail(), BLI_countlist(), BLI_strncpy(), MEM_callocN(), MovieTrackingObject::name, MovieTracking::objectnr, MovieTracking::objects, MovieTracking::tot_object, and TRACKING_OBJECT_CAMERA.
Referenced by BKE_tracking_init_settings(), do_versions(), tracking_object_new_exec(), and tracks_map_merge().
int BKE_tracking_next (MovieTrackingContext * context)
Definition at line 1362 of file tracking.c.
References MovieTrackingContext::backwards, BKE_movieclip_get_ibuf_flag(), BKE_tracking_exact_marker(), BKE_tracking_insert_marker(), MovieTrackingContext::clip, MovieTrackingContext::clip_flag, copy_v2_v2(), FALSE, MovieTrackingContext::first_time, MovieTrackingMarker::flag, MovieTrackingMarker::framenr, MovieClipUser::framenr, MovieTrackingContext::frames, IMB_freeImBuf(), MovieTrackingTrack::margin, MARKER_DISABLED, MARKER_TRACKED, MAX2, MEM_freeN(), MOVIECLIP_CACHE_SKIP, NULL, MovieTrackingTrack::pat_max, MovieTrackingTrack::pat_min, MovieTrackingTrack::pattern_match, MovieTrackingMarker::pos, put_disabled_marker(), sub_v2_v2v2(), TRACK_MATCH_KEYFRAME, MovieTrackingContext::tracks_map, tracks_map_get(), tracks_map_size(), TRUE, MovieTrackingContext::user, ImBuf::x, and ImBuf::y.
Referenced by track_markers_exec(), and track_markers_startjob().
MovieTrackingReconstruction* BKE_tracking_object_reconstruction (MovieTracking * tracking, MovieTrackingObject * object) [read]
Definition at line 2219 of file tracking.c.
References MovieTrackingObject::flag, MovieTracking::reconstruction, and TRACKING_OBJECT_CAMERA.
Referenced by BKE_tracking_get_interpolated_camera(), BKE_tracking_get_reconstructed_camera(), BKE_tracking_get_reconstruction(), and draw_viewport_object_reconstruction().
ListBase* BKE_tracking_object_tracks (MovieTracking * tracking, MovieTrackingObject * object) [read]
Definition at line 2210 of file tracking.c.
References MovieTrackingObject::flag, TRACKING_OBJECT_CAMERA, and MovieTracking::tracks.
Referenced by BKE_tracking_can_reconstruct(), BKE_tracking_clipboard_copy_tracks(), BKE_tracking_clipboard_paste_tracks(), BKE_tracking_indexed_track(), BKE_tracking_named_track(), BKE_tracking_reconstruction_context_new(), bundle_midpoint(), deselect_all_tracks(), draw_viewport_object_reconstruction(), set_axis_exec(), set_origin_exec(), and set_plane_exec().
void BKE_tracking_object_unique_name (MovieTracking * tracking, MovieTrackingObject * object)
Definition at line 3003 of file tracking.c.
References BLI_uniquename(), MovieTrackingObject::name, ImBuf::name, and MovieTracking::objects.
Referenced by BKE_tracking_new_object().
void BKE_tracking_projection_matrix (MovieTracking * tracking, MovieTrackingObject * object, int framenr, int winx, int winy, float mat[4][4])
Definition at line 2119 of file tracking.c.
References BKE_tracking_camera_shift(), BKE_tracking_get_reconstructed_camera(), MovieTracking::camera, copy_m4_m4(), MovieTrackingCamera::focal, invert_m4_m4(), left(), MovieReconstructedCamera::mat, MAX2, mult_m4_m4m4(), perspective_m4(), MovieTrackingCamera::pixel_aspect, and MovieTrackingCamera::sensor_width.
Referenced by draw_tracking_tracks().
void BKE_tracking_reconstruction_context_free (MovieReconstructContext * context)
Definition at line 1843 of file tracking.c.
References MEM_freeN(), NULL, MovieReconstructContext::tracks_map, and tracks_map_free().
Referenced by solve_camera_freejob().
MovieReconstructContext* BKE_tracking_reconstruction_context_new (MovieTracking * tracking, MovieTrackingObject * object, int keyframe1, int keyframe2, int width, int height) [read]
Definition at line 1772 of file tracking.c.
References BKE_tracking_object_tracks(), BLI_countlist(), BLI_strncpy(), MovieTracking::camera, MovieReconstructContext::efra, ListBase::first, MovieTrackingMarker::flag, MovieTrackingCamera::focal, MovieReconstructContext::focal_length, MovieTrackingMarker::framenr, MovieReconstructContext::is_camera, MovieTrackingCamera::k1, MovieReconstructContext::k1, MovieTrackingCamera::k2, MovieReconstructContext::k2, MovieTrackingCamera::k3, MovieReconstructContext::k3, MARKER_DISABLED, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, MAX2, MEM_callocN(), MIN2, MovieTrackingObject::name, MovieTrackingTrack::next, NULL, MovieReconstructContext::object_name, MovieTrackingCamera::pixel_aspect, MovieTrackingCamera::principal, MovieReconstructContext::principal_point, MovieReconstructContext::sfra, TRACKING_OBJECT_CAMERA, MovieReconstructContext::tracks_map, tracks_map_insert(), and tracks_map_new().
Referenced by solve_camera_initjob().
void BKE_tracking_remove_object (MovieTracking * tracking, MovieTrackingObject * object)
Definition at line 2971 of file tracking.c.
References MovieTracking::act_track, BLI_findindex(), BLI_freelinkN(), MovieTrackingObject::flag, ImBuf::index, MovieTrackingTrack::next, NULL, MovieTracking::objectnr, MovieTracking::objects, MovieTracking::tot_object, TRACKING_OBJECT_CAMERA, and tracking_object_free().
Referenced by tracking_object_remove_exec().
void BKE_tracking_select_track (ListBase * tracksbase, MovieTrackingTrack * track, int area, int extend)
Definition at line 2916 of file tracking.c.
References BKE_tracking_track_flag(), ListBase::first, MovieTrackingTrack::flag, MovieTrackingTrack::next, SELECT, TRACK_AREA_ALL, and TRACK_HIDDEN.
Referenced by add_marker(), and mouse_select().
void BKE_tracking_solve_reconstruction (MovieReconstructContext * context, short * stop, short * do_update, float * progress, char * stats_message, int message_size)
Definition at line 1883 of file tracking.c.
References ReconstructProgressData::do_update, error(), MovieReconstructContext::focal_length, MovieReconstructContext::k1, MovieReconstructContext::k2, MovieReconstructContext::k3, ReconstructProgressData::message_size, MovieReconstructContext::principal_point, ReconstructProgressData::progress, MovieReconstructContext::reprojection_error, ReconstructProgressData::stats_message, and ReconstructProgressData::stop.
Referenced by solve_camera_startjob().
void BKE_tracking_stabdata_to_mat4 (int width, int height, float aspect, float loc[2], float scale, float angle, float mat[4][4])
Definition at line 2761 of file tracking.c.
References add_v2_v2(), invert_m4_m4(), mul_serie_m4(), NULL, rotate_m4(), size_to_mat4(), and unit_m4().
Referenced by BKE_tracking_stabilize(), clip_draw_main(), and stabilization_auto_scale_factor().
void BKE_tracking_stabilization_data (MovieTracking * tracking, int framenr, int width, int height, float loc[2], float * scale, float * angle)
Definition at line 2626 of file tracking.c.
References calculate_stabdata(), MovieTrackingStabilization::flag, MovieTrackingStabilization::ok, MovieTrackingStabilization::scale, MovieTracking::stabilization, stabilization_auto_scale_factor(), stabilization_median_point(), TRACKING_2D_STABILIZATION, TRACKING_AUTOSCALE, TRUE, and zero_v2().
Referenced by BKE_tracking_stabilize(), get_stable_cached_frame(), node_composit_exec_movieclip(), and node_composit_exec_stabilize2d().
ImBuf* BKE_tracking_stabilize (MovieTracking * tracking, int framenr, ImBuf * ibuf, float loc[2], float * scale, float * angle) [read]
Definition at line 2664 of file tracking.c.
References bicubic_interpolation(), bilinear_interpolation(), BKE_tracking_stabdata_to_mat4(), BKE_tracking_stabilization_data(), MovieTracking::camera, copy_v2_v2(), MovieTrackingStabilization::filter, filter(), MovieTrackingStabilization::flag, i, IB_MIPMAP_INVALID, IB_RECT_INVALID, IMB_rectcpy(), IMB_scalefastImBuf(), invert_m4(), mul_v3_m4v3(), neareast_interpolation(), NULL, MovieTrackingCamera::pixel_aspect, ImBuf::rect_float, MovieTrackingStabilization::scaleibuf, MovieTracking::stabilization, stabilization_auto_scale_factor(), stabilize_alloc_ibuf(), TRACKING_2D_STABILIZATION, TRACKING_FILTER_BICUBIC, TRACKING_FILTER_BILINEAR, TRACKING_FILTER_NEAREAST, TRUE, ImBuf::userflags, ImBuf::x, ImBuf::y, and zero_v2().
Referenced by put_stabilized_frame_to_cache().
void BKE_tracking_sync (MovieTrackingContext * context)
Definition at line 1342 of file tracking.c.
References MovieTrackingContext::backwards, MovieTrackingContext::clip, MovieClipUser::framenr, MovieTrackingContext::sync_frame, MovieClip::tracking, MovieTrackingContext::tracks_map, tracks_map_merge(), and MovieTrackingContext::user.
Referenced by track_markers_exec(), track_markers_freejob(), and track_markers_updatejob().
void BKE_tracking_sync_user (MovieClipUser * user, MovieTrackingContext * context)
Definition at line 1357 of file tracking.c.
References MovieClipUser::framenr, and MovieTrackingContext::sync_frame.
Referenced by clip_main_area_draw().
void BKE_tracking_track_flag (MovieTrackingTrack * track, int area, int flag, int clear)
Definition at line 205 of file tracking.c.
References MovieTrackingTrack::flag, MovieTrackingTrack::pat_flag, MovieTrackingTrack::search_flag, TRACK_AREA_NONE, TRACK_AREA_PAT, TRACK_AREA_POINT, and TRACK_AREA_SEARCH.
Referenced by BKE_tracking_deselect_track(), BKE_tracking_select_track(), border_select_exec(), circle_select_exec(), clean_tracks_exec(), clear_invisible_track_selection(), and stabilize_2d_select_exec().
ImBuf* BKE_tracking_undistort (MovieTracking * tracking, ImBuf * ibuf, int width, int height, float overscan) [read]
Definition at line 2895 of file tracking.c.
References BKE_tracking_distortion_create(), BKE_tracking_distortion_exec(), MovieTracking::camera, MovieTrackingCamera::intrinsics, and NULL.
Referenced by get_undistorted_ibuf().
static void calculate_stabdata (MovieTracking * tracking, int framenr, float width, float height, float firstmedian[2], float median[2], float loc[2], float * scale, float * angle) [static]
Definition at line 2441 of file tracking.c.
References KDL::atan2(), BKE_tracking_get_marker(), cosf, MovieTrackingStabilization::flag, MovieTrackingStabilization::locinf, mul_v2_fl(), MovieTrackingMarker::pos, MovieTrackingStabilization::rot_track, MovieTrackingStabilization::rotinf, MovieTrackingStabilization::scale, MovieTrackingStabilization::scaleinf, sinf, MovieTracking::stabilization, sub_v2_v2v2(), and TRACKING_STABILIZE_ROTATION.
Referenced by BKE_tracking_stabilization_data(), and stabilization_auto_scale_factor().
static void disable_imbuf_channels (ImBuf * ibuf, MovieTrackingTrack * track, int grayscale) [static]
Definition at line 1133 of file tracking.c.
References BKE_tracking_disable_imbuf_channels(), MovieTrackingTrack::flag, TRACK_DISABLE_BLUE, TRACK_DISABLE_GREEN, and TRACK_DISABLE_RED.
Referenced by get_area_imbuf().
static MovieTrackingTrack* duplicate_track (MovieTrackingTrack * track) [static]
Definition at line 648 of file tracking.c.
References MovieTrackingTrack::markers, MEM_callocN(), MEM_dupallocN(), MovieTrackingTrack::next, NULL, and MovieTrackingTrack::prev.
Referenced by BKE_tracking_clipboard_copy_tracks(), BKE_tracking_clipboard_paste_tracks(), and tracks_map_merge().
static ImBuf* get_area_imbuf (ImBuf * ibuf, MovieTrackingTrack * track, MovieTrackingMarker * marker, float min[2], float max[2], int margin, int anchored, float pos[2], int origin[2]) [static]
Definition at line 1139 of file tracking.c.
References add_v2_v2(), copy_v2_v2(), disable_imbuf_channels(), MovieTrackingTrack::flag, IB_rect, IMB_allocImBuf(), IMB_rectcpy(), NULL, MovieTrackingTrack::offset, MovieTrackingMarker::pos, TRACK_DISABLE_BLUE, TRACK_DISABLE_GREEN, TRACK_DISABLE_RED, TRACK_PREVIEW_GRAYSCALE, TRUE, ImBuf::x, ImBuf::y, and zero_v2().
Referenced by BKE_tracking_get_pattern_imbuf(), and BKE_tracking_get_search_imbuf().
static void put_disabled_marker (MovieTrackingTrack * track, MovieTrackingMarker * ref_marker, int before, int overwrite) [static]
Definition at line 428 of file tracking.c.
References BKE_tracking_has_marker(), BKE_tracking_insert_marker(), MovieTrackingMarker::flag, MovieTrackingMarker::framenr, MARKER_DISABLED, and MARKER_TRACKED.
Referenced by BKE_tracking_clear_path(), and BKE_tracking_next().
static int reconstruction_camera_index (MovieTrackingReconstruction * reconstruction, int framenr, int nearest) [static]
Definition at line 1965 of file tracking.c.
References MovieTrackingReconstruction::cameras, MovieTrackingReconstruction::camnr, MovieReconstructedCamera::framenr, and MovieTrackingReconstruction::last_camera.
Referenced by BKE_tracking_get_interpolated_camera(), and BKE_tracking_get_reconstructed_camera().
static void scale_reconstructed_camera (MovieTrackingObject * object, float mat[4][4]) [static]
Definition at line 2026 of file tracking.c.
References MovieTrackingObject::flag, mult_m4_m4m4(), MovieTrackingObject::scale, scale_m4_fl(), and TRACKING_OBJECT_CAMERA.
Referenced by BKE_tracking_get_interpolated_camera().
static float stabilization_auto_scale_factor (MovieTracking * tracking, int width, int height) [static]
Definition at line 2479 of file tracking.c.
References angle(), BKE_tracking_stabdata_to_mat4(), calculate_stabdata(), MovieTracking::camera, co, copy_v3_v3(), cos(), cross_v2v2(), F, ListBase::first, MovieTrackingStabilization::flag, MovieTrackingTrack::flag, MovieTrackingMarker::framenr, G, H, I, i, K, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, MAX2, MovieTrackingStabilization::maxscale, MIN2, mul_m4_v3(), MovieTrackingTrack::next, MovieTrackingStabilization::ok, MovieTrackingCamera::pixel_aspect, MovieTrackingStabilization::rot_track, MovieTrackingStabilization::scale, si, sin(), MovieTracking::stabilization, stabilization_median_point(), sub_v3_v3v3(), TRACK_USE_2D_STAB, TRACKING_STABILIZE_ROTATION, MovieTracking::tracks, and TRUE.
Referenced by BKE_tracking_stabilization_data(), and BKE_tracking_stabilize().
static int stabilization_median_point (MovieTracking * tracking, int framenr, float median[2]) [static]
Definition at line 2414 of file tracking.c.
References BKE_tracking_get_marker(), DO_MINMAX2, FALSE, ListBase::first, MovieTrackingTrack::flag, INIT_MINMAX2, max, min, MovieTrackingTrack::next, MovieTrackingMarker::pos, TRACK_USE_2D_STAB, MovieTracking::tracks, and TRUE.
Referenced by BKE_tracking_stabilization_data(), and stabilization_auto_scale_factor().
static ImBuf* stabilize_alloc_ibuf (ImBuf * cacheibuf, ImBuf * srcibuf, int fill) [static]
Definition at line 2597 of file tracking.c.
References IB_rect, IB_rectfloat, IMB_allocImBuf(), IMB_freeImBuf(), IMB_rectfill(), NULL, ImBuf::planes, ImBuf::profile, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by BKE_tracking_stabilize().
static void track_context_free (void * customdata) [static]
Definition at line 1045 of file tracking.c.
References MEM_freeN().
Referenced by BKE_tracking_context_free().
static void tracking_object_free (MovieTrackingObject * object) [static]
Definition at line 619 of file tracking.c.
References MovieTrackingObject::reconstruction, tracking_reconstruction_free(), tracking_tracks_free(), and MovieTrackingObject::tracks.
Referenced by BKE_tracking_remove_object(), and tracking_objects_free().
static void tracking_objects_free (ListBase * objects) [static]
Definition at line 625 of file tracking.c.
References BLI_freelistN(), ListBase::first, MovieTrackingObject::next, and tracking_object_free().
Referenced by BKE_tracking_free().
static void tracking_reconstruction_free (MovieTrackingReconstruction * reconstruction) [static]
Definition at line 613 of file tracking.c.
References MovieTrackingReconstruction::cameras, and MEM_freeN().
Referenced by BKE_tracking_free(), and tracking_object_free().
static void tracking_tracks_free (ListBase * tracks) [static]
Definition at line 602 of file tracking.c.
References BKE_tracking_free_track(), BLI_freelistN(), ListBase::first, and MovieTrackingTrack::next.
Referenced by BKE_tracking_free(), and tracking_object_free().
static void tracks_map_free (TracksMap * map, void(*)(void *customdata) customdata_free) [static]
Definition at line 883 of file tracking.c.
References BKE_tracking_free_track(), BLI_ghash_free(), TracksMap::customdata, TracksMap::customdata_size, TracksMap::hash, i, MEM_freeN(), NULL, TracksMap::num_tracks, and TracksMap::tracks.
Referenced by BKE_tracking_context_free(), and BKE_tracking_reconstruction_context_free().
static void tracks_map_get (TracksMap * map, int index, MovieTrackingTrack ** track, void ** customdata) [static]
Definition at line 756 of file tracking.c.
References TracksMap::customdata, TracksMap::customdata_size, and TracksMap::tracks.
Referenced by BKE_tracking_next().
static void tracks_map_insert (TracksMap * map, MovieTrackingTrack * track, void * customdata) [static]
Definition at line 764 of file tracking.c.
References BLI_ghash_insert(), TracksMap::customdata, TracksMap::customdata_size, TracksMap::hash, MovieTrackingTrack::markers, MEM_dupallocN(), TracksMap::ptr, and TracksMap::tracks.
Referenced by BKE_tracking_context_new(), and BKE_tracking_reconstruction_context_new().
static void tracks_map_merge (TracksMap * map, MovieTracking * tracking) [static]
Definition at line 780 of file tracking.c.
References MovieTracking::act_track, BKE_tracking_active_track(), BKE_tracking_free_track(), BKE_tracking_named_object(), BKE_tracking_new_object(), BLI_addtail(), BLI_freelinkN(), BLI_ghash_insert(), BLI_ghash_lookup(), BLI_ghash_remove(), BLI_remlink(), BLI_uniquename(), duplicate_track(), ListBase::first, MovieTrackingTrack::flag, TracksMap::hash, TracksMap::is_camera, MovieTrackingTrack::name, next, MovieTrackingTrack::next, NULL, TracksMap::num_tracks, TracksMap::object_name, MovieTrackingTrack::pat_flag, MovieTrackingTrack::prev, MovieTrackingStabilization::rot_track, MovieTrackingTrack::search_flag, MovieTracking::stabilization, TracksMap::tracks, MovieTracking::tracks, and tracks.
Referenced by BKE_tracking_finish_reconstruction(), and BKE_tracking_sync().
static TracksMap* tracks_map_new (const char * object_name, int is_camera, int num_tracks, int customdata_size) [static]
Definition at line 731 of file tracking.c.
References BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BLI_strncpy(), TracksMap::customdata, TracksMap::customdata_size, TracksMap::hash, TracksMap::is_camera, MEM_callocN(), TracksMap::num_tracks, TracksMap::object_name, and TracksMap::tracks.
Referenced by BKE_tracking_context_new(), and BKE_tracking_reconstruction_context_new().
static int tracks_map_size (TracksMap * map) [static]
Definition at line 751 of file tracking.c.
References TracksMap::num_tracks.
Referenced by BKE_tracking_next().
Variable Documentation
struct { ... } tracking_clipboard [static]
Referenced by BKE_tracking_clipboard_copy_tracks(), BKE_tracking_clipboard_has_tracks(), BKE_tracking_clipboard_paste_tracks(), and BKE_tracking_free_clipboard().
ListBase tracks
Definition at line 73 of file tracking.c.
Referenced by tracks_map_merge().