Blender: btCollisionConfiguration Class Reference
btCollisionConfiguration Class Reference
#include <btCollisionConfiguration.h>
Public Member Functions
virtual ~btCollisionConfiguration ()
virtual btPoolAllocator * getPersistentManifoldPool ()=0
memory pools
virtual btPoolAllocator * getCollisionAlgorithmPool ()=0
virtual btStackAlloc * getStackAllocator ()=0
virtual
btCollisionAlgorithmCreateFunc * getCollisionAlgorithmCreateFunc (int proxyType0, int proxyType1)=0
Detailed Description
btCollisionConfiguration allows to configure Bullet collision detection stack allocator size, default collision algorithms and persistent manifold pool size
Todo:
: describe the meaning
Definition at line 26 of file btCollisionConfiguration.h.
Constructor & Destructor Documentation
virtual btCollisionConfiguration::~btCollisionConfiguration () [inline, virtual]
Definition at line 31 of file btCollisionConfiguration.h.
Member Function Documentation
virtual btCollisionAlgorithmCreateFunc* btCollisionConfiguration::getCollisionAlgorithmCreateFunc (int proxyType0, int proxyType1) [pure virtual]
Implemented in btDefaultCollisionConfiguration, and btSoftBodyRigidBodyCollisionConfiguration.
Referenced by btCollisionDispatcher::btCollisionDispatcher().
virtual btPoolAllocator* btCollisionConfiguration::getCollisionAlgorithmPool () [pure virtual]
Implemented in btDefaultCollisionConfiguration.
Referenced by btCollisionDispatcher::btCollisionDispatcher().
virtual btPoolAllocator* btCollisionConfiguration::getPersistentManifoldPool () [pure virtual]
memory pools
Implemented in btDefaultCollisionConfiguration.
Referenced by btCollisionDispatcher::btCollisionDispatcher().
virtual btStackAlloc* btCollisionConfiguration::getStackAllocator () [pure virtual]
Implemented in btDefaultCollisionConfiguration.
Referenced by btCollisionWorld::btCollisionWorld().
The documentation for this class was generated from the following file:
btCollisionConfiguration.h