Blender: IK_QPositionTask Class Reference
IK_QPositionTask Class Reference
#include <IK_QTask.h>
Public Member Functions
IK_QPositionTask (bool primary, const IK_QSegment *segment, const MT_Vector3 &goal)
void ComputeJacobian (IK_QJacobian &jacobian)
MT_Scalar Distance () const
bool PositionTask () const
void Scale (float scale)
Detailed Description
Definition at line 92 of file IK_QTask.h.
Constructor & Destructor Documentation
IK_QPositionTask::IK_QPositionTask (bool primary, const IK_QSegment * segment, const MT_Vector3 & goal)
Definition at line 51 of file IK_QTask.cpp.
References IK_QTask::m_segment, IK_QSegment::MaxExtension(), and IK_QSegment::Parent().
Member Function Documentation
void IK_QPositionTask::ComputeJacobian (IK_QJacobian & jacobian) [virtual]
Implements IK_QTask.
Definition at line 73 of file IK_QTask.cpp.
References IK_QSegment::Axis(), MT_Vector3::cross(), IK_QSegment::DoFId(), IK_QSegment::GlobalEnd(), IK_QSegment::GlobalStart(), i, length(), MT_Vector3::length(), IK_QTask::m_id, IK_QTask::m_segment, IK_QTask::m_size, IK_QTask::m_weight, IK_QSegment::NumberOfDoF(), p, IK_QSegment::Parent(), IK_QJacobian::SetBetas(), IK_QJacobian::SetDerivatives(), and IK_QSegment::Translational().
MT_Scalar IK_QPositionTask::Distance () const [virtual]
Implements IK_QTask.
Definition at line 106 of file IK_QTask.cpp.
References IK_QSegment::GlobalEnd(), MT_Vector3::length(), and IK_QTask::m_segment.
bool IK_QPositionTask::PositionTask () const [inline, virtual]
Reimplemented from IK_QTask.
Definition at line 105 of file IK_QTask.h.
void IK_QPositionTask::Scale (float scale) [inline, virtual]
Reimplemented from IK_QTask.
Definition at line 106 of file IK_QTask.h.
The documentation for this class was generated from the following files:
IK_QTask.h
IK_QTask.cpp