Blender: GHOST_IEvent Class Reference
GHOST_IEvent Class Reference
#include <GHOST_IEvent.h>
Public Member Functions
virtual ~GHOST_IEvent ()
virtual GHOST_TEventType getType ()=0
virtual GHOST_TUns64 getTime ()=0
virtual GHOST_IWindow * getWindow ()=0
virtual GHOST_TEventDataPtr getData ()=0
Detailed Description
Interface class for events received from GHOST. You should not need to inherit this class. The system will pass these events to the GHOST_IEventConsumer::processEvent() method of event consumers.
Use the getType() method to retrieve the type of event and the getData() method to get the event data out. Using the event type you can cast the event data to the correct event dat structure.
See also:
GHOST_IEventConsumer::processEvent
GHOST_TEventType
Author:
Maarten Gribnau
Date:
May 31, 2001
Definition at line 53 of file GHOST_IEvent.h.
Constructor & Destructor Documentation
virtual GHOST_IEvent::~GHOST_IEvent () [inline, virtual]
Destructor.
Definition at line 59 of file GHOST_IEvent.h.
Member Function Documentation
virtual GHOST_TEventDataPtr GHOST_IEvent::getData () [pure virtual]
Returns the event data.
Returns:
The event data.
Implemented in GHOST_Event.
Referenced by GHOST_GetEventData(), and Application::processEvent().
virtual GHOST_TUns64 GHOST_IEvent::getTime () [pure virtual]
Returns the time this event was generated.
Returns:
The event generation time.
Implemented in GHOST_Event.
Referenced by GHOST_GetEventTime(), and GHOST_EventPrinter::processEvent().
virtual GHOST_TEventType GHOST_IEvent::getType () [pure virtual]
Returns the event type.
Returns:
The event type.
Implemented in GHOST_Event.
Referenced by GHOST_GetEventType(), GPG_Application::processEvent(), GHOST_EventPrinter::processEvent(), and Application::processEvent().
virtual GHOST_IWindow* GHOST_IEvent::getWindow () [pure virtual]
Returns the window this event was generated on, or NULL if it is a 'system' event.
Returns:
The generating window.
Implemented in GHOST_Event.
Referenced by GHOST_GetEventWindow().
The documentation for this class was generated from the following file:
GHOST_IEvent.h