Blender: BKE_tessmesh.h File Reference
BKE_tessmesh.h File Reference
#include "BKE_customdata.h"
#include "bmesh.h"
Classes
struct BMEditMesh
Typedefs
typedef struct BMEditMesh BMEditMesh
Functions
void BMEdit_RecalcTessellation (BMEditMesh *tm)
BMEditMesh * BMEdit_Create (BMesh *bm, int do_tessellate)
BMEditMesh * BMEdit_Copy (BMEditMesh *tm)
BMEditMesh * BMEdit_FromObject (struct Object *ob)
Return the BMEditMesh for a given object.
void BMEdit_Free (BMEditMesh *em)
void BMEdit_UpdateLinkedCustomData (BMEditMesh *em)
Typedef Documentation
typedef struct BMEditMesh BMEditMesh
Function Documentation
BMEditMesh* BMEdit_Copy (BMEditMesh * tm)
Definition at line 84 of file editderivedmesh.c.
References BMEditMesh::bm, BM_mesh_copy(), BMEditMesh::derivedCage, BMEditMesh::derivedFinal, BMEditMesh::edge_index, BMEditMesh::face_index, BMEditMesh::looptris, MEM_callocN(), NULL, and BMEditMesh::vert_index.
Referenced by EDBM_op_call_and_selectf(), EDBM_op_call_silentf(), EDBM_op_callf(), and EDBM_op_init().
BMEditMesh* BMEdit_Create (BMesh * bm, int do_tessellate)
Definition at line 72 of file editderivedmesh.c.
References BMEditMesh::bm, BMEdit_RecalcTessellation(), and MEM_callocN().
Referenced by bm_mdisps_space_set(), DM_to_editbmesh(), EDBM_mesh_make(), and undoMesh_to_editbtMesh().
void BMEdit_Free (BMEditMesh * em)
Definition at line 290 of file editderivedmesh.c.
References BMEditMesh::bm, BM_mesh_free(), BMEditMesh::derivedCage, BMEditMesh::derivedFinal, BMEditMesh::edge_index, BMEditMesh::face_index, BMEditMesh::looptris, MEM_freeN(), DerivedMesh::needsFree, NULL, DerivedMesh::release, and BMEditMesh::vert_index.
Referenced by applyModifier(), arrayModifier_doArray(), bm_mdisps_space_set(), doEdgeSplit(), EDBM_mesh_free(), and EDBM_op_finish().
BMEditMesh* BMEdit_FromObject (Object * ob)
Return the BMEditMesh for a given object.
Note:
this function assumes this is a mesh object, don't add NULL data check here. caller must do that
Definition at line 1744 of file editderivedmesh.c.
References BLI_assert, Object::data, OB_MESH, and Object::type.
Referenced by average_islands_scale_exec(), border_select_exec(), calc_manipulator_stats(), calculateCenter(), circle_select_exec(), createRepresentation(), createTransEdge(), createTransEditVerts(), createTransUVs(), cube_project_exec(), cylinder_project_exec(), do_lasso_select_mesh(), do_uvedit_vertex(), do_view3d_header_buttons(), draw_uvs_shadow(), ED_object_enter_editmode(), ED_operator_editmesh(), ED_operator_uvmap(), ED_space_image_show_uvedit(), ED_space_image_show_uvshadow(), ED_unwrap_lscm(), ED_uvedit_assign_image(), ED_uvedit_ensure_uvs(), ED_uvedit_live_unwrap(), ED_uvedit_live_unwrap_begin(), ED_uvedit_median(), ED_uvedit_minmax(), ED_uvedit_nearest_uv(), ED_uvedit_test(), ED_vgroup_object_is_edit_mode(), edbm_add_edge_face_exec(), EDBM_automerge(), edbm_beautify_fill_exec(), edbm_bevel_exec(), edbm_bridge_edge_loops_exec(), edbm_collapse_edge_exec(), edbm_collapse_edge_loop_exec(), edbm_delete_exec(), edbm_dissolve_exec(), edbm_dissolve_limited_exec(), edbm_do_smooth_vertex_exec(), edbm_duplicate_exec(), edbm_edge_rotate_selected_exec(), edbm_edge_split_exec(), edbm_extrude_edges_exec(), edbm_extrude_faces_exec(), edbm_extrude_region_exec(), edbm_extrude_repeat_exec(), edbm_extrude_verts_exec(), edbm_faces_select_interior_exec(), edbm_faces_shade_flat_exec(), edbm_faces_shade_smooth_exec(), edbm_fill_exec(), edbm_flip_normals_exec(), edbm_hide_exec(), edbm_inset_exec(), edbm_knife_cut_exec(), edbm_loop_multiselect_exec(), edbm_loop_to_region_exec(), edbm_mark_seam(), edbm_mark_sharp(), edbm_merge_exec(), edbm_noise_exec(), edbm_normals_make_consistent_exec(), edbm_quads_convert_to_tris_exec(), edbm_region_to_loop_exec(), edbm_remove_doubles_exec(), edbm_reveal_exec(), edbm_reverse_colors_exec(), edbm_reverse_uvs_exec(), edbm_rip_invoke(), edbm_rip_invoke__edge(), edbm_rip_invoke__vert(), edbm_rotate_colors_exec(), edbm_rotate_uvs_exec(), edbm_screw_exec(), edbm_select_all_exec(), edbm_select_axis_exec(), edbm_select_by_number_vertices_exec(), edbm_select_less_exec(), edbm_select_linked_exec(), edbm_select_linked_flat_faces_exec(), edbm_select_loose_verts_exec(), edbm_select_mirror_exec(), edbm_select_more_exec(), edbm_select_next_loop_exec(), edbm_select_non_manifold_exec(), edbm_select_nth_exec(), edbm_select_random_exec(), edbm_select_sharp_edges_exec(), edbm_select_vertex_path_exec(), EDBM_selectmode_to_scene(), edbm_separate_exec(), edbm_shortest_path_select_poll(), edbm_spin_exec(), edbm_split_exec(), edbm_subdivide_exec(), edbm_tris_convert_to_quads_exec(), edbm_vert_connect(), edbm_vertex_slide_exec(), edbm_vertices_randomize_exec(), hide_exec(), knifetool_init(), knifetool_modal(), linked_limit_default(), make_prim_finish(), material_slot_assign_exec(), material_slot_de_select(), merge_type_itemf(), mesh_circle_select(), mesh_separate_loose(), mesh_separate_material(), minimize_stretch_init(), mouse_select(), navmesh_face_add_exec(), navmesh_face_copy_exec(), object_handle_update(), pack_islands_exec(), peelObjects(), pin_exec(), recalcData_view3d(), reveal_exec(), ringsel_init(), select_all_exec(), select_linked_internal(), select_pinned_exec(), select_similar_type_itemf(), shape_itemf(), similar_edge_select_exec(), similar_face_select_exec(), similar_vert_select_exec(), snap_uvs_to_adjacent_unselected(), snap_uvs_to_cursor(), snap_uvs_to_pixels(), snapObject(), special_aftertrans_update(), sphere_project_exec(), stats_object_edit(), stitch_init(), uiTemplateEditModeSelection(), undo_push_mesh(), unlink_selection_exec(), unwrap_exec(), uv_faces_do_sticky(), uv_from_view_exec(), uv_map_transform(), uv_sculpt_brush_poll(), uv_sculpt_stroke_apply(), uv_sculpt_stroke_init(), uvedit_set_tile(), uvedit_vertex_buttons(), vgroup_blend(), vgroup_do_remap(), vgroup_object_in_edit_mode(), view3d_borderselect_exec(), vtx_slide_confirm(), vtx_slide_init(), and weld_align_uv().
void BMEdit_RecalcTessellation (BMEditMesh * tm)
Definition at line 250 of file editderivedmesh.c.
References BMEdit_RecalcTessellation_intern(), BMEditMesh::derivedCage, BMEditMesh::derivedFinal, and DerivedMesh::recalcTessellation.
Referenced by BMBVH_NewBVH(), BME_bevel(), BMEdit_Create(), DM_to_editbmesh(), ED_mesh_calc_tessface(), ED_object_enter_editmode(), EDBM_automerge(), EDBM_op_finish(), EDBM_update_generic(), and recalcData_view3d().
void BMEdit_UpdateLinkedCustomData (BMEditMesh * em)
Definition at line 269 of file editderivedmesh.c.
References BMEditMesh::bm, CD_MLOOPUV, CD_MTEXPOLY, CustomData_get_active_layer(), CustomData_get_clone_layer(), CustomData_get_render_layer(), CustomData_get_stencil_layer(), CustomData_has_layer(), CustomData_set_layer_active(), CustomData_set_layer_clone(), CustomData_set_layer_render(), CustomData_set_layer_stencil(), BMesh::ldata, and BMesh::pdata.
Referenced by mesh_update_linked_customdata().