Blender: bmo_inset.c File Reference
bmo_inset.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "bmesh.h"
#include "intern/bmesh_operators_private.h"
Classes
struct SplitEdgeInfo
Defines
#define ELE_NEW 1
Typedefs
typedef struct SplitEdgeInfo SplitEdgeInfo
Functions
static BMLoop * bm_edge_is_mixed_face_tag (BMLoop *l)
float bm_vert_avg_tag_dist (BMVert *v)
void bmo_inset_exec (BMesh *bm, BMOperator *op)
Detailed Description
Definition in file bmo_inset.c.
Define Documentation
#define ELE_NEW 1
Definition at line 35 of file bmo_inset.c.
Referenced by bmo_inset_exec().
Typedef Documentation
typedef struct SplitEdgeInfo SplitEdgeInfo
Function Documentation
static BMLoop* bm_edge_is_mixed_face_tag (BMLoop * l) [static]
return the tag loop where there is...
only 1 tagged face attached to this edge.
1 or more untagged faces.
Note:
this function looks to be expensive but in most cases it will only do 2 iterations.
Definition at line 53 of file bmo_inset.c.
References BM_elem_flag_test, BM_ELEM_TAG, BMLoop::f, LIKELY, NULL, and BMLoop::radial_next.
Referenced by bmo_inset_exec().
float bm_vert_avg_tag_dist (BMVert * v)
Definition at line 83 of file bmo_inset.c.
References BM_edge_calc_length(), BM_edge_other_vert(), BM_EDGES_OF_VERT, BM_elem_flag_test, BM_ELEM_TAG, BM_ITER_ELEM_INDEX, and length().
Referenced by bmo_inset_exec().
void bmo_inset_exec (BMesh * bm, BMOperator * op)
implementation is as follows...
set all faces as tagged/untagged based on selection.
find all edges that have 1 tagged, 1 untagged face.
separate these edges and tag vertices, set their index to point to the original edge.
build faces between old/new edges.
inset the new edges into their faces.
Definition at line 110 of file bmo_inset.c.
References add_v3_v3(), add_v3_v3v3(), angle_normalized_v3v3(), BLI_assert, BM_EDGE, BM_edge_calc_face_tangent(), BM_edge_calc_length(), BM_edge_create(), BM_edge_is_boundary(), bm_edge_is_mixed_face_tag(), BM_edge_ordered_verts_ex(), BM_edge_other_vert(), BM_EDGES_OF_MESH, BM_EDGES_OF_VERT, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_elem_index_get, BM_elem_index_set, BM_ELEM_TAG, BM_FACE, BM_face_copy_shared(), BM_face_create_quad_tri_v(), BM_FACES_OF_VERT, BM_ITER_ELEM, BM_ITER_MESH, BM_ITER_MESH_INDEX, BM_loop_other_vert_loop(), BM_mesh_elem_hflag_disable_all(), BM_mesh_elem_hflag_enable_all(), BM_VERT, bm_vert_avg_tag_dist(), BM_vert_calc_shell_factor(), BM_vert_create(), BM_vert_splice(), BM_VERTS_OF_FACE, BM_VERTS_OF_MESH, bmesh_edge_separate(), bmesh_vert_separate(), BMO_elem_flag_enable, BMO_ITER, BMO_slot_bool_get(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_buffer_hflag_disable(), BMO_slot_buffer_hflag_enable(), BMO_slot_float_get(), BMVert::co, compare_v3v3(), copy_v3_v3(), cross_v3_v3v3(), dot_v3v3(), BMLoop::e, BMVert::e, SplitEdgeInfo::e_new, SplitEdgeInfo::e_old, ELE_NEW, BMesh::elem_index_dirty, BMLoop::f, FALSE, i, if(), SplitEdgeInfo::l, BMEdge::l, len_squared_v3(), SplitEdgeInfo::length, length(), madd_v3_v3fl(), madd_v3_v3v3fl(), MEM_callocN(), MEM_freeN(), MEM_mallocN(), mid_v3_v3v3(), mul_v3_fl(), negate_v3(), BMLoop::next, SplitEdgeInfo::no, BMFace::no, BMVert::no, normalize_v3(), NULL, BMLoop::prev, shell_angle_to_dist(), sub_v3_v3v3(), BMesh::totvert, TRUE, BMLoop::v, BMEdge::v1, BMEdge::v2, and zero_v3().