Blender: node_shader_tex_environment.c File Reference
node_shader_tex_environment.c File Reference
#include "../node_shader_util.h"
Functions
static void node_shader_init_tex_environment (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static int node_shader_gpu_tex_environment (GPUMaterial *mat, bNode *node, GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_tex_environment (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_tex_environment_in []
static bNodeSocketTemplate sh_node_tex_environment_out []
Function Documentation
static int node_shader_gpu_tex_environment (GPUMaterial * mat, bNode * node, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 53 of file node_shader_tex_environment.c.
References GPU_builtin(), GPU_image(), GPU_stack_link(), GPU_uniform(), GPU_VIEW_POSITION, bNode::id, if(), link(), GPUNodeStack::link, node_shader_gpu_tex_mapping(), and NULL.
Referenced by register_node_type_sh_tex_environment().
static void node_shader_init_tex_environment (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 42 of file node_shader_tex_environment.c.
References NodeTexEnvironment::base, NodeTexBase::color_mapping, NodeTexEnvironment::color_space, default_color_mapping(), default_tex_mapping(), MEM_callocN(), NodeTexEnvironment::projection, SHD_COLORSPACE_COLOR, SHD_PROJ_EQUIRECTANGULAR, bNode::storage, and NodeTexBase::tex_mapping.
Referenced by register_node_type_sh_tex_environment().
void register_node_type_sh_tex_environment (bNodeTreeType * ttype)
Definition at line 73 of file node_shader_tex_environment.c.
References NODE_CLASS_TEXTURE, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OPTIONS, node_shader_gpu_tex_environment(), node_shader_init_tex_environment(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_ENVIRONMENT.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_tex_environment_in[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 1, "Vector",       0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_NONE, SOCK_HIDE_VALUE},
    {   -1, 0, ""   }
}
Definition at line 32 of file node_shader_tex_environment.c.
bNodeSocketTemplate sh_node_tex_environment_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Color",      0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_shader_tex_environment.c.