Blender: btSoftBodyHelpers.cpp File Reference
btSoftBodyHelpers.cpp File Reference
#include "btSoftBodyInternals.h"
#include <stdio.h>
#include <string.h>
#include "btSoftBodyHelpers.h"
#include "LinearMath/btConvexHull.h"
Defines
#define IDX(_x_, _y_) ((_y_)*rx+(_x_))
#define IDX(_x_, _y_) ((_y_)*rx+(_x_))
#define IDX(_x_, _y_) ((_y_)*maxidx+(_x_))
Functions
static void drawVertex (btIDebugDraw *idraw, const btVector3 &x, btScalar s, const btVector3 &c)
btSoftBodyHelpers.cpp by Nathanael Presson
static void drawBox (btIDebugDraw *idraw, const btVector3 &mins, const btVector3 &maxs, const btVector3 &color)
static void drawTree (btIDebugDraw *idraw, const btDbvtNode *node, int depth, const btVector3 &ncolor, const btVector3 &lcolor, int mindepth, int maxdepth)
template<typename T >
static T sum (const btAlignedObjectArray< T > &items)
template<typename T , typename Q >
static void add (btAlignedObjectArray< T > &items, const Q &value)
template<typename T , typename Q >
static void mul (btAlignedObjectArray< T > &items, const Q &value)
template<typename T >
static T average (const btAlignedObjectArray< T > &items)
static btScalar tetravolume (const btVector3 &x0, const btVector3 &x1, const btVector3 &x2, const btVector3 &x3)
static int nextLine (const char *buffer)
Define Documentation
#define IDX (_x_, _y_) ((_y_)*rx+(_x_))
#define IDX (_x_, _y_) ((_y_)*maxidx+(_x_))
#define IDX (_x_, _y_) ((_y_)*rx+(_x_))
Function Documentation
template<typename T , typename Q > static void add (btAlignedObjectArray< T > & items, const Q & value) [inline, static]
Definition at line 98 of file btSoftBodyHelpers.cpp.
References i, and btAlignedObjectArray< T >::size().
Referenced by addAlphaOverFloatMask(), alloc_utf16_from_8(), alloc_utf_8_from_16(), AUD_addSequence(), BLI_newname(), BufferParams::BufferParams(), btSoftBodyHelpers::Draw(), edbm_blend_from_shape_exec(), Film::Film(), flatten_background_closure_tree(), flatten_surface_closure_tree(), flatten_volume_closure_tree(), get_new_constraint_target(), init_brush_icons(), LbmFsgrSolver::mainLoop(), outliner_one_level_exec(), quad_1edge_split(), quad_3edge_split(), RE_inithalo_particle(), region_azone_tab(), region_azone_tab_plus(), region_azone_tria(), BlenderSession::render(), scaledownx(), scaledowny(), scaleupx(), scaleupy(), txt_comment(), txt_indent(), txt_insert_buf(), and ui_picker_small_wheel_cb().
template<typename T > static T average (const btAlignedObjectArray< T > & items) [inline, static]
Definition at line 118 of file btSoftBodyHelpers.cpp.
References btAlignedObjectArray< T >::size(), and sum().
static void drawBox (btIDebugDraw * idraw, const btVector3 & mins, const btVector3 & maxs, const btVector3 & color) [static]
Definition at line 33 of file btSoftBodyHelpers.cpp.
References btIDebugDraw::drawLine().
Referenced by drawTree().
static void drawTree (btIDebugDraw * idraw, const btDbvtNode * node, int depth, const btVector3 & ncolor, const btVector3 & lcolor, int mindepth, int maxdepth) [static]
Definition at line 55 of file btSoftBodyHelpers.cpp.
References btDbvtAabbMm::Center(), btDbvtNode::childs, drawBox(), btDbvtAabbMm::Extents(), btDbvtNode::isinternal(), btDbvtNode::isleaf(), and btDbvtNode::volume.
Referenced by btSoftBodyHelpers::DrawClusterTree(), btSoftBodyHelpers::DrawFaceTree(), and btSoftBodyHelpers::DrawNodeTree().
static void drawVertex (btIDebugDraw * idraw, const btVector3 & x, btScalar s, const btVector3 & c) [static]
btSoftBodyHelpers.cpp by Nathanael Presson
Definition at line 24 of file btSoftBodyHelpers.cpp.
References btIDebugDraw::drawLine().
Referenced by btSoftBodyHelpers::Draw(), and btSoftBodyHelpers::DrawFrame().
template<typename T , typename Q > static void mul (btAlignedObjectArray< T > & items, const Q & value) [inline, static]
Definition at line 108 of file btSoftBodyHelpers.cpp.
References i, and btAlignedObjectArray< T >::size().
Referenced by addAlphaOverFloat(), addAlphaOverFloatMask(), addAlphaUnderFloat(), arraysize(), boid_brain(), calculate_structlens(), collision_interpolate_element(), color_balance_fl(), DNA_elem_array_size(), DNA_struct_switch_endian(), do_alphaover_key(), do_alphaover_mixed(), do_alphaover_premul(), btSoftBodyHelpers::Draw(), drawlamp(), elementsize(), flatten_background_closure_tree(), flatten_surface_closure_tree(), flatten_volume_closure_tree(), icu_to_fcurves(), input_have_to_preprocess(), input_preprocess(), multibuf(), normalize_v3_d(), pe_iterate_lengths(), project_v2_v2v2(), project_v3_plane(), project_v3_v3v3(), reconstruct_elem(), reconstruct_struct(), rule_follow_leader(), rule_goal_avoid(), sk_filterStroke(), snapEdge(), and zbuffer_abuf().
static int nextLine (const char * buffer) [static]
Definition at line 900 of file btSoftBodyHelpers.cpp.
Referenced by btSoftBodyHelpers::CreateFromTetGenData().
template<typename T > static T sum (const btAlignedObjectArray< T > & items) [inline, static]
Definition at line 82 of file btSoftBodyHelpers.cpp.
References i, btAlignedObjectArray< T >::size(), and T.
Referenced by ATTRIBUTE_ALIGNED16(), average(), BLI_gTurbulence(), blur_single_image(), blur_with_reference(), brightness_mean(), brightness_standard_deviation(), btDbvtBroadphase::calculateOverlappingPairs(), btConvexTriangleMeshShape::calculatePrincipalAxisTransform(), WTURBULENCE::computeEnergy(), BSP_CSGMesh::CountTriangles(), diffuse_shv3(), do_weight_paint_normalize_all(), do_weight_paint_normalize_all_active(), TNT::dot_prod(), gjkepa2_impl::EPA::Evaluate(), btQuaternion::farthest(), freeraytree(), btSoftBody::generateBendingConstraints(), MT_Matrix4x4::invert(), TNT::LU_solve(), make_gausstab(), makeNurbcurve(), makeNurbfaces(), TNT::matmult(), md5_stream(), btQuaternion::nearest(), noise_turbulence(), occ_compute_bounces(), overlapped_curve(), p_stretch_compute_vertex(), path_radiance_accum_light(), path_radiance_bsdf_bounce(), path_radiance_clamp(), TNT::QR_factor(), TNT::QR_solve(), TNT::R_solve(), AUD_ChannelMapperReader::read(), btSequentialImpulseConstraintSolver::resolveSingleConstraintRowGeneric(), btSequentialImpulseConstraintSolver::resolveSingleConstraintRowGenericSIMD(), btSequentialImpulseConstraintSolver::resolveSingleConstraintRowLowerLimit(), btSequentialImpulseConstraintSolver::resolveSingleConstraintRowLowerLimitSIMD(), btSequentialImpulseConstraintSolver::resolveSplitPenetrationImpulseCacheFriendly(), btSequentialImpulseConstraintSolver::resolveSplitPenetrationSIMD(), sh_eval(), shader_bsdf_sample(), btRotationalLimitMotor::solveAngularLimits(), btSequentialImpulseConstraintSolver::solveGroupCacheFriendlyFinish(), btSequentialImpulseConstraintSolver::solveGroupCacheFriendlySetup(), and btTranslationalLimitMotor::solveLinearAxis().
static btScalar tetravolume (const btVector3 & x0, const btVector3 & x1, const btVector3 & x2, const btVector3 & x3) [inline, static]
Definition at line 125 of file btSoftBodyHelpers.cpp.
References btCross(), and btDot().