Blender: node_ops.c File Reference
node_ops.c File Reference
node editor
#include "DNA_node_types.h"
#include "DNA_scene_types.h"
#include "BKE_context.h"
#include "BLI_utildefines.h"
#include "ED_node.h"
#include "ED_screen.h"
#include "ED_transform.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
#include "node_intern.h"
Functions
void node_operatortypes (void)
void ED_operatormacros_node (void)
void node_keymap (struct wmKeyConfig *keyconf)
Detailed Description
Definition in file node_ops.c.
Function Documentation
void ED_operatormacros_node (void)
Definition at line 108 of file node_ops.c.
References wmOperatorType::description, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorTypeMacro::ptr, RNA_boolean_set(), TRUE, WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().
void node_keymap (struct wmKeyConfig * keyconf)
Definition at line 137 of file node_ops.c.
References ACTIONMOUSE, AKEY, BKEY, CKEY, DELKEY, DKEY, EVT_TWEAK_S, FALSE, FKEY, GKEY, HKEY, HOMEKEY, KM_ALT, KM_ANY, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTBRACKETKEY, LEFTMOUSE, LKEY, MIDDLEMOUSE, MKEY, NKEY, wmKeyMapItem::ptr, RIGHTBRACKETKEY, RKEY, RNA_boolean_set(), RNA_float_set(), SELECTMOUSE, SPACE_NODE, TABKEY, transform_keymap_for_space(), TRUE, VKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), XKEY, and ZKEY.
Referenced by ED_spacetype_node().
void node_operatortypes (void)
Definition at line 50 of file node_ops.c.
References NODE_OT_add_file(), NODE_OT_backimage_move(), NODE_OT_backimage_sample(), NODE_OT_backimage_zoom(), NODE_OT_delete(), NODE_OT_delete_reconnect(), NODE_OT_duplicate(), NODE_OT_group_edit(), NODE_OT_group_make(), NODE_OT_group_socket_add(), NODE_OT_group_socket_move_down(), NODE_OT_group_socket_move_up(), NODE_OT_group_socket_remove(), NODE_OT_group_ungroup(), NODE_OT_hide_socket_toggle(), NODE_OT_hide_toggle(), NODE_OT_link(), NODE_OT_link_make(), NODE_OT_link_viewer(), NODE_OT_links_cut(), NODE_OT_links_detach(), NODE_OT_mute_toggle(), NODE_OT_new_node_tree(), NODE_OT_options_toggle(), NODE_OT_output_file_add_socket(), NODE_OT_output_file_remove_active_socket(), NODE_OT_preview_toggle(), NODE_OT_properties(), NODE_OT_read_fullsamplelayers(), NODE_OT_read_renderlayers(), NODE_OT_render_changed(), NODE_OT_resize(), NODE_OT_select(), NODE_OT_select_all(), NODE_OT_select_border(), NODE_OT_select_linked_from(), NODE_OT_select_linked_to(), NODE_OT_select_same_type(), NODE_OT_select_same_type_next(), NODE_OT_select_same_type_prev(), NODE_OT_show_cyclic_dependencies(), NODE_OT_view_all(), and WM_operatortype_append().
Referenced by ED_spacetype_node().