Blender: btInternalEdgeUtility.h File Reference
btInternalEdgeUtility.h File Reference
#include "LinearMath/btHashMap.h"
#include "LinearMath/btVector3.h"
#include "BulletCollision/CollisionShapes/btTriangleInfoMap.h"
Enumerations
enum btInternalEdgeAdjustFlags { BT_TRIANGLE_CONVEX_BACKFACE_MODE = 1, BT_TRIANGLE_CONCAVE_DOUBLE_SIDED = 2, BT_TRIANGLE_CONVEX_DOUBLE_SIDED = 4 }
Functions
void btGenerateInternalEdgeInfo (btBvhTriangleMeshShape *trimeshShape, btTriangleInfoMap *triangleInfoMap)
Call btGenerateInternalEdgeInfo to create triangle info, store in the shape 'userInfo'.
void btAdjustInternalEdgeContacts (btManifoldPoint &cp, const btCollisionObject *trimeshColObj0, const btCollisionObject *otherColObj1, int partId0, int index0, int normalAdjustFlags=0)
Changes a btManifoldPoint collision normal to the normal from the mesh.
Enumeration Type Documentation
enum btInternalEdgeAdjustFlags
Enumerator:
BT_TRIANGLE_CONVEX_BACKFACE_MODE
BT_TRIANGLE_CONCAVE_DOUBLE_SIDED
BT_TRIANGLE_CONVEX_DOUBLE_SIDED
Definition at line 20 of file btInternalEdgeUtility.h.
Function Documentation
void btAdjustInternalEdgeContacts (btManifoldPoint & cp, const btCollisionObject * trimeshColObj0, const btCollisionObject * otherColObj1, int partId0, int index0, int normalAdjustFlags = 0)
Changes a btManifoldPoint collision normal to the normal from the mesh.
Call the btFixMeshNormal to adjust the collision normal, using the triangle info map (generated using btGenerateInternalEdgeInfo) If this info map is missing, or the triangle is not store in this map, nothing will be done
Definition at line 453 of file btInternalEdgeUtility.cpp.
References BT_TRIANGLE_CONCAVE_DOUBLE_SIDED, BT_TRIANGLE_CONVEX_BACKFACE_MODE, BT_TRIANGLE_CONVEX_DOUBLE_SIDED, btClampNormal(), btGetHash(), btNearestPointInLineSegment(), btHashMap< Key, Value >::find(), btTransform::getBasis(), btManifoldPoint::getPositionWorldOnB(), hash, len(), length(), btTriangleInfoMap::m_convexEpsilon, btManifoldPoint::m_distance1, btTriangleInfo::m_edgeV0V1Angle, btTriangleInfo::m_edgeV1V2Angle, btTriangleInfo::m_edgeV2V0Angle, btTriangleInfo::m_flags, btManifoldPoint::m_localPointB, btManifoldPoint::m_normalWorldOnB, btManifoldPoint::m_positionWorldOnA, btManifoldPoint::m_positionWorldOnB, quatRotate(), SIMD_2_PI, TRI_INFO_V0V1_CONVEX, TRI_INFO_V0V1_SWAP_NORMALB, TRI_INFO_V1V2_CONVEX, TRI_INFO_V1V2_SWAP_NORMALB, TRI_INFO_V2V0_CONVEX, TRI_INFO_V2V0_SWAP_NORMALB, and TRIANGLE_SHAPE_PROXYTYPE.
void btGenerateInternalEdgeInfo (btBvhTriangleMeshShape * trimeshShape, btTriangleInfoMap * triangleInfoMap)
Call btGenerateInternalEdgeInfo to create triangle info, store in the shape 'userInfo'.
Definition at line 315 of file btInternalEdgeUtility.cpp.
References BT_LARGE_FLOAT, btStridingMeshInterface::getLockedReadOnlyVertexIndexBase(), btStridingMeshInterface::getNumSubParts(), btStridingMeshInterface::getScaling(), btConnectivityProcessor::m_partIdA, btConnectivityProcessor::m_triangleIndexA, btConnectivityProcessor::m_triangleInfoMap, btConnectivityProcessor::m_triangleVerticesA, PHY_FLOAT, PHY_INTEGER, and PHY_SHORT.