Blender: ED_physics.h File Reference
ED_physics.h File Reference
Editors
Functions
int PE_poll (struct bContext *C)
int PE_hair_poll (struct bContext *C)
int PE_poll_view3d (struct bContext *C)
void ED_operatortypes_physics (void)
void ED_keymap_physics (struct wmKeyConfig *keyconf)
Detailed Description
Definition in file ED_physics.h.
Function Documentation
void ED_keymap_physics (struct wmKeyConfig * keyconf)
Definition at line 209 of file physics_ops.c.
References keymap_particle().
Referenced by ED_spacetypes_keymap().
void ED_operatortypes_physics (void)
Definition at line 200 of file physics_ops.c.
References operatortypes_boids(), operatortypes_dynamicpaint(), operatortypes_fluid(), operatortypes_particle(), and operatortypes_pointcache().
Referenced by ED_spacetypes_init().
int PE_hair_poll (struct bContext * C)
Definition at line 118 of file particle_edit.c.
References CTX_data_active_object(), CTX_data_scene(), Object::mode, OB_MODE_PARTICLE_EDIT, PE_get_current(), and PTCacheEdit::psys.
Referenced by PARTICLE_OT_delete(), PARTICLE_OT_mirror(), PARTICLE_OT_rekey(), PARTICLE_OT_remove_doubles(), PARTICLE_OT_subdivide(), and PARTICLE_OT_weight_set().
int PE_poll (struct bContext * C)
Definition at line 107 of file particle_edit.c.
References CTX_data_active_object(), CTX_data_scene(), Object::mode, NULL, OB_MODE_PARTICLE_EDIT, and PE_get_current().
Referenced by buttons_context(), keymap_particle(), PARTICLE_OT_hide(), PARTICLE_OT_reveal(), PARTICLE_OT_select_all(), PARTICLE_OT_select_less(), PARTICLE_OT_select_more(), PARTICLE_OT_select_roots(), PARTICLE_OT_select_tips(), and PE_poll_view3d().
int PE_poll_view3d (struct bContext * C)
Definition at line 132 of file particle_edit.c.
References CTX_wm_area(), CTX_wm_region(), PE_poll(), ARegion::regiontype, RGN_TYPE_WINDOW, SPACE_VIEW3D, and ScrArea::spacetype.
Referenced by PARTICLE_OT_brush_edit(), PARTICLE_OT_select_linked(), and toggle_particle_cursor().