Blender: rna_cloth.c File Reference
rna_cloth.c File Reference
RNA
#include <stdlib.h>
#include <limits.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "BKE_cloth.h"
#include "BKE_modifier.h"
#include "DNA_cloth_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "WM_api.h"
#include "WM_types.h"
Functions
static void rna_def_cloth_sim_settings (BlenderRNA *brna)
static void rna_def_cloth_collision_settings (BlenderRNA *brna)
void RNA_def_cloth (BlenderRNA *brna)
Detailed Description
Definition in file rna_cloth.c.
Function Documentation
void RNA_def_cloth (BlenderRNA * brna)
Definition at line 521 of file rna_cloth.c.
References rna_def_cloth_collision_settings(), and rna_def_cloth_sim_settings().
static void rna_def_cloth_collision_settings (BlenderRNA * brna) [static]
Definition at line 437 of file rna_cloth.c.
References CLOTH_COLLSETTINGS_FLAG_ENABLED, CLOTH_COLLSETTINGS_FLAG_SELF, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_float_default(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_cloth().
static void rna_def_cloth_sim_settings (BlenderRNA * brna) [static]
Definition at line 210 of file rna_cloth.c.
References CLOTH_SIMSETTINGS_FLAG_GOAL, CLOTH_SIMSETTINGS_FLAG_SCALING, NULL, PROP_ACCELERATION, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_cloth().