Blender: IK_QRevoluteSegment Class Reference
IK_QRevoluteSegment Class Reference
#include <IK_QSegment.h>
Public Member Functions
IK_QRevoluteSegment (int axis)
MT_Vector3 Axis (int dof) const
bool UpdateAngle (const IK_QJacobian &jacobian, MT_Vector3 &delta, bool *clamp)
void Lock (int dof, IK_QJacobian &jacobian, MT_Vector3 &delta)
void UpdateAngleApply ()
void SetLimit (int axis, MT_Scalar lmin, MT_Scalar lmax)
void SetWeight (int axis, MT_Scalar weight)
void SetBasis (const MT_Matrix3x3 &basis)
Detailed Description
Definition at line 251 of file IK_QSegment.h.
Constructor & Destructor Documentation
IK_QRevoluteSegment::IK_QRevoluteSegment (int axis)
Definition at line 554 of file IK_QSegment.cpp.
Member Function Documentation
MT_Vector3 IK_QRevoluteSegment::Axis (int dof) const [virtual]
Implements IK_QSegment.
Definition at line 571 of file IK_QSegment.cpp.
References MT_Transform::getBasis(), MT_Matrix3x3::getColumn(), and IK_QSegment::m_global_transform.
void IK_QRevoluteSegment::Lock (int dof, IK_QJacobian & jacobian, MT_Vector3 & delta) [virtual]
Reimplemented from IK_QSegment.
Definition at line 601 of file IK_QSegment.cpp.
References IK_QJacobian::Lock(), IK_QSegment::m_DoF_id, and IK_QSegment::m_locked.
void IK_QRevoluteSegment::SetBasis (const MT_Matrix3x3 & basis) [virtual]
Reimplemented from IK_QSegment.
Definition at line 559 of file IK_QSegment.cpp.
References ComputeTwist(), ComputeTwistMatrix(), EulerAngleFromMatrix(), IK_QSegment::m_basis, and RotationMatrix().
void IK_QRevoluteSegment::SetLimit (int axis, MT_Scalar lmin, MT_Scalar lmax) [virtual]
Reimplemented from IK_QSegment.
Definition at line 613 of file IK_QSegment.cpp.
References MT_clamp(), and MT_PI().
void IK_QRevoluteSegment::SetWeight (int axis, MT_Scalar weight) [virtual]
Reimplemented from IK_QSegment.
Definition at line 628 of file IK_QSegment.cpp.
References IK_QSegment::m_weight.
bool IK_QRevoluteSegment::UpdateAngle (const IK_QJacobian & jacobian, MT_Vector3 & delta, bool * clamp) [virtual]
Implements IK_QSegment.
Definition at line 576 of file IK_QSegment.cpp.
References IK_QJacobian::AngleUpdate(), IK_QSegment::m_DoF_id, and IK_QSegment::m_locked.
void IK_QRevoluteSegment::UpdateAngleApply () [virtual]
Implements IK_QSegment.
Definition at line 607 of file IK_QSegment.cpp.
References IK_QSegment::m_basis, and RotationMatrix().
The documentation for this class was generated from the following files:
IK_QSegment.h
IK_QSegment.cpp