Blender: btDiscreteCollisionDetectorInterface::Result Struct Reference
btDiscreteCollisionDetectorInterface::Result Struct Reference
#include <btDiscreteCollisionDetectorInterface.h>
Public Member Functions
virtual ~Result ()
virtual void setShapeIdentifiersA (int partId0, int index0)=0
setShapeIdentifiersA/B provides experimental support for per-triangle material / custom material combiner
virtual void setShapeIdentifiersB (int partId1, int index1)=0
virtual void addContactPoint (const btVector3 &normalOnBInWorld, const btVector3 &pointInWorld, btScalar depth)=0
Detailed Description
Definition at line 31 of file btDiscreteCollisionDetectorInterface.h.
Constructor & Destructor Documentation
virtual btDiscreteCollisionDetectorInterface::Result::~Result () [inline, virtual]
Definition at line 34 of file btDiscreteCollisionDetectorInterface.h.
Member Function Documentation
virtual void btDiscreteCollisionDetectorInterface::Result::addContactPoint (const btVector3 & normalOnBInWorld, const btVector3 & pointInWorld, btScalar depth) [pure virtual]
Implemented in btBridgedManifoldResult, btPerturbedContactResult, btManifoldResult, btStorageResult, and btPointCollector.
Referenced by dBoxBox2(), SphereTriangleDetector::getClosestPoints(), and btGjkPairDetector::getClosestPointsNonVirtual().
virtual void btDiscreteCollisionDetectorInterface::Result::setShapeIdentifiersA (int partId0, int index0) [pure virtual]
setShapeIdentifiersA/B provides experimental support for per-triangle material / custom material combiner
Implemented in btManifoldResult, and btPointCollector.
virtual void btDiscreteCollisionDetectorInterface::Result::setShapeIdentifiersB (int partId1, int index1) [pure virtual]
Implemented in btManifoldResult, and btPointCollector.
The documentation for this struct was generated from the following file:
btDiscreteCollisionDetectorInterface.h