Blender: SG_DList Class Reference
SG_DList Class Reference
#include <SG_DList.h>
Classes
class const_iterator
class iterator
Public Member Functions
SG_DList ()
SG_DList (const SG_DList &other)
virtual ~SG_DList ()
bool Empty ()
bool AddBack (SG_DList *item)
bool AddFront (SG_DList *item)
SG_DList * Remove ()
bool Delink ()
SG_DList * Peek ()
SG_DList * Back ()
SG_DList * Self ()
const SG_DList * Peek () const
const SG_DList * Back () const
const SG_DList * Self () const
Protected Attributes
SG_DList * m_flink
SG_DList * m_blink
Detailed Description
Double circular linked list
Definition at line 44 of file SG_DList.h.
Constructor & Destructor Documentation
SG_DList::SG_DList () [inline]
Definition at line 135 of file SG_DList.h.
References m_blink, and m_flink.
SG_DList::SG_DList (const SG_DList & other) [inline]
Definition at line 139 of file SG_DList.h.
References m_blink, and m_flink.
virtual SG_DList::~SG_DList () [inline, virtual]
Definition at line 143 of file SG_DList.h.
References Delink().
Member Function Documentation
bool SG_DList::AddBack (SG_DList * item) [inline]
Definition at line 152 of file SG_DList.h.
References Empty(), m_blink, and m_flink.
Referenced by SCA_IActuator::Activate(), SCA_IController::Activate(), BL_ArmatureObject::LoadChannels(), BL_ArmatureObject::LoadConstraints(), KX_TouchEventManager::RegisterSensor(), SCA_EventManager::RegisterSensor(), SG_Node::Schedule(), and SG_DListHead< BL_ArmatureConstraint >::SG_DListHead().
bool SG_DList::AddFront (SG_DList * item) [inline]
Definition at line 162 of file SG_DList.h.
References Empty(), m_blink, and m_flink.
Referenced by SCA_IController::Activate(), KX_StateActuator::Activate(), and SG_Node::Schedule().
const SG_DList* SG_DList::Back () const [inline]
Definition at line 209 of file SG_DList.h.
References m_blink.
SG_DList* SG_DList::Back () [inline]
Definition at line 197 of file SG_DList.h.
References m_blink.
Referenced by SG_DList::const_iterator< T >::back(), and SG_DList::iterator< T >::back().
bool SG_DList::Delink () [inline]
Definition at line 184 of file SG_DList.h.
References Empty(), m_blink, and m_flink.
Referenced by SCA_IController::Deactivate(), KX_StateActuator::Deactivate(), SCA_IActuator::Deactivate(), KX_TouchEventManager::RemoveSensor(), SCA_EventManager::RemoveSensor(), SCA_LogicManager::UpdateFrame(), SG_Node::UpdateWorldData(), and ~SG_DList().
bool SG_DList::Empty () [inline]
Definition at line 148 of file SG_DList.h.
References m_flink.
Referenced by SG_IObject::ActivateScheduleUpdateCallback(), AddBack(), AddFront(), Delink(), BL_ArmatureObject::LoadChannels(), BL_ArmatureObject::LoadConstraints(), SCA_JoystickManager::NextFrame(), KX_TouchEventManager::NextFrame(), SG_QList::QAddFront(), Remove(), KX_Scene::UpdateParents(), SCA_EventManager::~SCA_EventManager(), and SCA_LogicManager::~SCA_LogicManager().
const SG_DList* SG_DList::Peek () const [inline]
Definition at line 205 of file SG_DList.h.
References m_flink.
SG_DList* SG_DList::Peek () [inline]
Definition at line 193 of file SG_DList.h.
References m_flink.
Referenced by SG_DList::iterator< T >::begin(), and SG_DList::const_iterator< T >::begin().
SG_DList* SG_DList::Remove () [inline]
Reimplemented in SG_DListHead< T >, and SG_DListHead< BL_ArmatureConstraint >.
Definition at line 172 of file SG_DList.h.
References Empty(), m_blink, m_flink, and NULL.
Referenced by SCA_LogicManager::BeginFrame(), RAS_MaterialBucket::GetNextActiveMeshSlot(), SG_Node::GetNextScheduled(), CListValue::RemoveValue(), and BL_ArmatureObject::~BL_ArmatureObject().
SG_DList* SG_DList::Self () [inline]
Definition at line 201 of file SG_DList.h.
Referenced by SG_DList::const_iterator< T >::end(), SG_DList::iterator< T >::end(), and SG_QList::iterator< T >::end().
const SG_DList* SG_DList::Self () const [inline]
Definition at line 213 of file SG_DList.h.
Member Data Documentation
SG_DList* SG_DList::m_blink [protected]
Definition at line 48 of file SG_DList.h.
Referenced by AddBack(), AddFront(), Back(), Delink(), Remove(), and SG_DList().
SG_DList* SG_DList::m_flink [protected]
Definition at line 47 of file SG_DList.h.
Referenced by AddBack(), AddFront(), Delink(), Empty(), Peek(), Remove(), and SG_DList().
The documentation for this class was generated from the following file:
SG_DList.h