Blender: EffectsExporter Class Reference
EffectsExporter Class Reference
#include <EffectExporter.h>
Public Member Functions
EffectsExporter (COLLADASW::StreamWriter *sw, const ExportSettings *export_settings)
void exportEffects (Scene *sce)
void operator() (Material *ma, Object *ob)
COLLADASW::ColorOrTexture createTexture (Image *ima, std::string &uv_layer_name, COLLADASW::Sampler *sampler)
COLLADASW::ColorOrTexture getcol (float r, float g, float b, float a)
Detailed Description
Definition at line 46 of file EffectExporter.h.
Constructor & Destructor Documentation
EffectsExporter::EffectsExporter (COLLADASW::StreamWriter * sw, const ExportSettings * export_settings)
Definition at line 57 of file EffectExporter.cpp.
Member Function Documentation
COLLADASW::ColorOrTexture EffectsExporter::createTexture (Image * ima, std::string & uv_layer_name, COLLADASW::Sampler * sampler)
Definition at line 337 of file EffectExporter.cpp.
References id_name(), Texture, and translate_id().
Referenced by operator()().
void EffectsExporter::exportEffects (Scene * sce)
Definition at line 80 of file EffectExporter.cpp.
References MaterialFunctor::forEachMaterialInScene(), and ExportSettings::selected.
Referenced by DocumentExporter::exportCurrentScene().
COLLADASW::ColorOrTexture EffectsExporter::getcol (float r, float g, float b, float a)
Definition at line 352 of file EffectExporter.cpp.
Referenced by operator()().
void EffectsExporter::operator() (Material * ma, Object * ob)
Definition at line 120 of file EffectExporter.cpp.
References Material::alpha, Material::amb, World::ambr, Material::ang, Material::b, createTexture(), Object::data, Material::diff_shader, Material::emit, Mesh::flag, Material::g, getActiveUVLayerName(), getcol(), i, id_name(), if(), Tex::ima, MA_DIFF_LAMBERT, MA_RAYMIRROR, MA_RAYTRANSP, MA_SPEC_BLINN, MA_TRANSP, MAP_ALPHA, MAP_AMB, MAP_COL, MAP_COLSPEC, MAP_EMIT, MAP_NORM, MAP_REF, MAP_SPEC, MTex::mapto, MAX_MTEX, ME_TWOSIDED, Material::mirb, Material::mirg, Material::mirr, Material::mode, Material::mtex, OB_MESH, Material::r, Material::ray_mirror, Material::ref, Material::spec, Material::spec_shader, Material::specb, Material::specg, Material::specr, strlen(), MTex::tex, Texture, translate_id(), Object::type, MTex::uvname, and Scene::world.
The documentation for this class was generated from the following files:
EffectExporter.h
EffectExporter.cpp