Blender: node_socket.c File Reference
node_socket.c File Reference
nodes
#include <limits.h>
#include "DNA_node_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_listbase.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_DerivedMesh.h"
#include "BKE_node.h"
#include "RNA_access.h"
#include "RNA_types.h"
#include "MEM_guardedalloc.h"
#include "NOD_socket.h"
Defines
#define INIT_TYPE(name) types[node_socket_type_##name.type] = &node_socket_type_##name
Functions
void node_socket_type_init (bNodeSocketType *types[])
void * node_socket_make_default_value (int type)
void node_socket_free_default_value (int UNUSED(type), void *default_value)
void node_socket_init_default_value (int type, void *default_value)
void node_socket_set_default_value_int (void *default_value, PropertySubType subtype, int value, int min, int max)
void node_socket_set_default_value_float (void *default_value, PropertySubType subtype, float value, float min, float max)
void node_socket_set_default_value_boolean (void *default_value, char value)
void node_socket_set_default_value_vector (void *default_value, PropertySubType subtype, float x, float y, float z, float min, float max)
void node_socket_set_default_value_rgba (void *default_value, float r, float g, float b, float a)
void node_socket_set_default_value_shader (void *UNUSED(default_value))
void node_socket_set_default_value_mesh (void *UNUSED(default_value))
void node_socket_copy_default_value (int type, void *to_default_value, void *from_default_value)
void node_socket_convert_default_value (int to_type, void *to_default_value, int from_type, void *from_default_value)
struct bNodeSocket * node_add_input_from_template (struct bNodeTree *ntree, struct bNode *node, struct bNodeSocketTemplate *stemp)
struct bNodeSocket * node_add_output_from_template (struct bNodeTree *ntree, struct bNode *node, struct bNodeSocketTemplate *stemp)
static bNodeSocket * verify_socket_template (bNodeTree *ntree, bNode *node, int in_out, ListBase *socklist, bNodeSocketTemplate *stemp)
static void verify_socket_template_list (bNodeTree *ntree, bNode *node, int in_out, ListBase *socklist, bNodeSocketTemplate *stemp_first)
void node_verify_socket_templates (bNodeTree *ntree, bNode *node)
Variables
static bNodeSocketType node_socket_type_float
static bNodeSocketType node_socket_type_vector
static bNodeSocketType node_socket_type_rgba
static bNodeSocketType node_socket_type_int
static bNodeSocketType node_socket_type_boolean
static bNodeSocketType node_socket_type_shader
static bNodeSocketType node_socket_type_mesh
Detailed Description
Definition in file node_socket.c.
Define Documentation
#define INIT_TYPE (name) types[node_socket_type_##name.type] = &node_socket_type_##name
Function Documentation
struct bNodeSocket* node_add_input_from_template (struct bNodeTree * ntree, struct bNode * node, struct bNodeSocketTemplate * stemp) [read]
Definition at line 446 of file node_socket.c.
References bNodeSocket::default_value, bNodeSocketTemplate::flag, bNodeSocket::flag, bNodeSocketTemplate::max, bNodeSocketTemplate::min, bNodeSocketTemplate::name, node_socket_set_default_value_boolean(), node_socket_set_default_value_float(), node_socket_set_default_value_int(), node_socket_set_default_value_mesh(), node_socket_set_default_value_rgba(), node_socket_set_default_value_shader(), node_socket_set_default_value_vector(), nodeAddSocket(), SOCK_BOOLEAN, SOCK_FLOAT, SOCK_IN, SOCK_INT, SOCK_MESH, SOCK_RGBA, SOCK_SHADER, SOCK_VECTOR, bNodeSocketTemplate::subtype, bNodeSocketTemplate::type, bNodeSocketTemplate::val1, bNodeSocketTemplate::val2, bNodeSocketTemplate::val3, and bNodeSocketTemplate::val4.
Referenced by node_add_sockets_from_type(), and verify_socket_template().
struct bNodeSocket* node_add_output_from_template (struct bNodeTree * ntree, struct bNode * node, struct bNodeSocketTemplate * stemp) [read]
Definition at line 478 of file node_socket.c.
References bNodeSocketTemplate::name, nodeAddSocket(), SOCK_OUT, and bNodeSocketTemplate::type.
Referenced by cmp_node_image_add_render_pass_output(), node_add_sockets_from_type(), and verify_socket_template().
void node_socket_convert_default_value (int to_type, void * to_default_value, int from_type, void * from_default_value)
Definition at line 330 of file node_socket.c.
References copy_v3_v3(), copy_v4_v4(), SOCK_BOOLEAN, SOCK_FLOAT, SOCK_INT, SOCK_RGBA, SOCK_VECTOR, bNodeSocketValueBoolean::value, bNodeSocketValueFloat::value, bNodeSocketValueVector::value, bNodeSocketValueInt::value, and bNodeSocketValueRGBA::value.
Referenced by node_group_ungroup(), and nodeSocketSetType().
void node_socket_copy_default_value (int type, void * to_default_value, void * from_default_value)
Definition at line 277 of file node_socket.c.
References SOCK_BOOLEAN, SOCK_FLOAT, SOCK_INT, SOCK_RGBA, and SOCK_VECTOR.
Referenced by node_group_add_extern_socket(), node_group_expose_all_sockets(), node_group_expose_socket(), node_socket_add_replace(), nodeCopyNode(), and ntreeCopyTree().
void node_socket_free_default_value (int UNUSEDtype, void * default_value)
Definition at line 190 of file node_socket.c.
References MEM_freeN().
Referenced by node_socket_add_replace(), nodeFreeNode(), nodeRemoveAllSockets(), nodeRemoveSocket(), nodeSocketSetType(), and ntreeFreeTree().
void node_socket_init_default_value (int type, void * default_value)
Definition at line 197 of file node_socket.c.
References FALSE, FLT_MAX, node_socket_set_default_value_boolean(), node_socket_set_default_value_float(), node_socket_set_default_value_int(), node_socket_set_default_value_mesh(), node_socket_set_default_value_rgba(), node_socket_set_default_value_shader(), node_socket_set_default_value_vector(), PROP_NONE, SOCK_BOOLEAN, SOCK_FLOAT, SOCK_INT, SOCK_MESH, SOCK_RGBA, SOCK_SHADER, and SOCK_VECTOR.
Referenced by make_socket(), and nodeSocketSetType().
void* node_socket_make_default_value (int type)
Definition at line 176 of file node_socket.c.
References MEM_callocN(), ntreeGetSocketType(), NULL, and bNodeSocketType::value_structsize.
Referenced by make_socket(), node_group_add_extern_socket(), node_socket_add_replace(), nodeCopyNode(), nodeSocketSetType(), and ntreeCopyTree().
void node_socket_set_default_value_boolean (void * default_value, char value)
Definition at line 242 of file node_socket.c.
References bNodeSocketValueBoolean::value.
Referenced by node_add_input_from_template(), and node_socket_init_default_value().
void node_socket_set_default_value_float (void * default_value, PropertySubType subtype, float value, float min, float max)
Definition at line 233 of file node_socket.c.
References max, bNodeSocketValueFloat::max, bNodeSocketValueFloat::min, min, bNodeSocketValueFloat::subtype, and bNodeSocketValueFloat::value.
Referenced by node_add_input_from_template(), node_forloop_init(), node_socket_init_default_value(), and node_whileloop_init().
void node_socket_set_default_value_int (void * default_value, PropertySubType subtype, int value, int min, int max)
Definition at line 224 of file node_socket.c.
References max, bNodeSocketValueInt::max, min, bNodeSocketValueInt::min, bNodeSocketValueInt::subtype, and bNodeSocketValueInt::value.
Referenced by node_add_input_from_template(), and node_socket_init_default_value().
void node_socket_set_default_value_mesh (void * UNUSEDdefault_value)
Definition at line 272 of file node_socket.c.
Referenced by node_add_input_from_template(), and node_socket_init_default_value().
void node_socket_set_default_value_rgba (void * default_value, float r, float g, float b, float a)
Definition at line 259 of file node_socket.c.
References g, and bNodeSocketValueRGBA::value.
Referenced by node_add_input_from_template(), and node_socket_init_default_value().
void node_socket_set_default_value_shader (void * UNUSEDdefault_value)
Definition at line 268 of file node_socket.c.
Referenced by node_add_input_from_template(), and node_socket_init_default_value().
void node_socket_set_default_value_vector (void * default_value, PropertySubType subtype, float x, float y, float z, float min, float max)
Definition at line 248 of file node_socket.c.
References max, bNodeSocketValueVector::max, bNodeSocketValueVector::min, min, bNodeSocketValueVector::subtype, and bNodeSocketValueVector::value.
Referenced by node_add_input_from_template(), and node_socket_init_default_value().
void node_socket_type_init (bNodeSocketType * types[])
Definition at line 161 of file node_socket.c.
References INIT_TYPE.
Referenced by ntreeGetSocketType().
void node_verify_socket_templates (bNodeTree * ntree, bNode * node)
Definition at line 596 of file node_socket.c.
References bNodeType::inputs, bNode::inputs, bNode::outputs, bNodeType::outputs, SOCK_IN, SOCK_OUT, bNodeSocketTemplate::type, bNode::typeinfo, and verify_socket_template_list().
Referenced by lib_nodetree_init_types_cb().
static bNodeSocket* verify_socket_template (bNodeTree * ntree, bNode * node, int in_out, ListBase * socklist, bNodeSocketTemplate * stemp) [static]
Definition at line 484 of file node_socket.c.
References BLI_remlink(), bNodeSocket::default_value, ListBase::first, bNodeSocketTemplate::flag, bNodeSocket::flag, bNodeSocket::limit, bNodeSocketTemplate::limit, bNodeSocketTemplate::max, bNodeSocketValueFloat::max, bNodeSocketValueInt::max, bNodeSocketValueVector::max, bNodeSocketValueFloat::min, bNodeSocketTemplate::min, bNodeSocketValueVector::min, bNodeSocketValueInt::min, bNodeSocket::name, bNodeSocketTemplate::name, bNodeSocket::next, node_add_input_from_template(), node_add_output_from_template(), NODE_MAXSTR, SOCK_DYNAMIC, SOCK_FLOAT, SOCK_IN, SOCK_INT, SOCK_VECTOR, bNodeSocketValueVector::subtype, bNodeSocketValueFloat::subtype, bNodeSocketValueInt::subtype, bNodeSocketTemplate::subtype, bNodeSocketTemplate::type, and bNodeSocket::type.
Referenced by verify_socket_template_list().
static void verify_socket_template_list (bNodeTree * ntree, bNode * node, int in_out, ListBase * socklist, bNodeSocketTemplate * stemp_first) [static]
Definition at line 547 of file node_socket.c.
References BLI_addtail(), BLI_insertlinkbefore(), ListBase::first, bNodeSocket::flag, bNodeSocket::next, nodeRemoveSocket(), NULL, bNodeSocketTemplate::sock, SOCK_DYNAMIC, bNodeSocketTemplate::type, and verify_socket_template().
Referenced by node_verify_socket_templates().
Variable Documentation
bNodeSocketType node_socket_type_boolean [static]
Initial value:
 {
                    SOCK_BOOLEAN,
                "Boolean",
        "Boolean",
                0,
                {158,139,63,255},
        "bNodeSocketValueBoolean",
        sizeof(bNodeSocketValueBoolean),
            NULL,
}
Definition at line 117 of file node_socket.c.
bNodeSocketType node_socket_type_float [static]
Initial value:
 {
                    SOCK_FLOAT,
                "Float",
        "Floating Point",
                0,
                {160,160,160,255},
        "bNodeSocketValueFloat",
        sizeof(bNodeSocketValueFloat),
            NULL,
}
Definition at line 57 of file node_socket.c.
bNodeSocketType node_socket_type_int [static]
Initial value:
 {
                    SOCK_INT,
                "Int",
        "Integer",
                0,
                {17,133,37,255},
        "bNodeSocketValueInt",
        sizeof(bNodeSocketValueInt),
            NULL,
}
Definition at line 102 of file node_socket.c.
bNodeSocketType node_socket_type_mesh [static]
Initial value:
 {
                    SOCK_MESH,
                "Mesh",
        "Mesh geometry data",
                0,
                {255,133,7,255},
        NULL,
        0,
            NULL,
}
Definition at line 147 of file node_socket.c.
bNodeSocketType node_socket_type_rgba [static]
Initial value:
 {
                    SOCK_RGBA,
                "RGBA",
        "RGBA color",
                0,
                {200,200,40,255},
        "bNodeSocketValueRGBA",
        sizeof(bNodeSocketValueRGBA),
            NULL,
}
Definition at line 87 of file node_socket.c.
bNodeSocketType node_socket_type_shader [static]
Initial value:
 {
                    SOCK_SHADER,
                "Shader",
        "Shader",
                0,
                {100,200,100,255},
        NULL,
        0,
            NULL,
}
Definition at line 132 of file node_socket.c.
bNodeSocketType node_socket_type_vector [static]
Initial value:
 {
                    SOCK_VECTOR,
                "Vector",
        "3-dimensional floating point vector",
                0,
                {100,100,200,255},
        "bNodeSocketValueVector",
        sizeof(bNodeSocketValueVector),
            NULL,
}
Definition at line 72 of file node_socket.c.