Blender: object_ops.c File Reference
object_ops.c File Reference
object
#include <stdlib.h>
#include <math.h>
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_screen.h"
#include "ED_object.h"
#include "object_intern.h"
Functions
void ED_operatortypes_object (void)
void ED_operatormacros_object (void)
static int object_mode_poll (bContext *C)
void ED_keymap_object (wmKeyConfig *keyconf)
void ED_object_generic_keymap (struct wmKeyConfig *UNUSED(keyconf), struct wmKeyMap *keymap, int do_pet)
Detailed Description
Definition in file object_ops.c.
Function Documentation
void ED_keymap_object (wmKeyConfig * keyconf)
Definition at line 260 of file object_ops.c.
References AKEY, CKEY, DELKEY, DKEY, ED_object_generic_keymap(), ED_operator_editlattice(), FALSE, GKEY, HKEY, i, IKEY, JKEY, KM_ALT, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTBRACKETKEY, LKEY, MKEY, OB_MODE_EDIT, OB_MODE_POSE, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, object_mode_poll(), OKEY, PKEY, wmKeyMap::poll, wmKeyMapItem::ptr, RIGHTBRACKETKEY, RKEY, RNA_boolean_set(), RNA_enum_set(), RNA_enum_set_identifier(), RNA_int_set(), SEL_INVERT, SEL_TOGGLE, SKEY, TABKEY, TKEY, TRUE, UKEY, VKEY, WKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), WM_keymap_verify_item(), XKEY, and ZEROKEY.
Referenced by ED_spacetypes_keymap().
void ED_object_generic_keymap (struct wmKeyConfig * UNUSEDkeyconf, struct wmKeyMap * keymap, int do_pet)
Definition at line 420 of file object_ops.c.
References KM_ALT, KM_PRESS, KM_SHIFT, OKEY, wmKeyMapItem::ptr, RNA_string_set(), and WM_keymap_add_item().
void ED_operatormacros_object (void)
Definition at line 220 of file object_ops.c.
References wmOperatorType::description, MAX_ID_NAME, OPTYPE_REGISTER, OPTYPE_UNDO, PROP_EDIT_OFF, wmOperatorTypeMacro::ptr, RNA_boolean_set(), RNA_def_string(), RNA_enum_set(), wmOperatorType::srna, TRUE, WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().
void ED_operatortypes_object (void)
Definition at line 59 of file object_ops.c.
References CONSTRAINT_OT_childof_clear_inverse(), CONSTRAINT_OT_childof_set_inverse(), CONSTRAINT_OT_delete(), CONSTRAINT_OT_limitdistance_reset(), CONSTRAINT_OT_move_down(), CONSTRAINT_OT_move_up(), CONSTRAINT_OT_objectsolver_clear_inverse(), CONSTRAINT_OT_objectsolver_set_inverse(), CONSTRAINT_OT_stretchto_reset(), GROUP_OT_create(), GROUP_OT_objects_add_active(), GROUP_OT_objects_remove(), GROUP_OT_objects_remove_active(), LATTICE_OT_make_regular(), LATTICE_OT_select_all(), OBJECT_OT_add(), OBJECT_OT_add_named(), OBJECT_OT_armature_add(), OBJECT_OT_bake_image(), OBJECT_OT_camera_add(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_constraints_clear(), OBJECT_OT_constraints_copy(), OBJECT_OT_convert(), OBJECT_OT_delete(), OBJECT_OT_drop_named_material(), OBJECT_OT_duplicate(), OBJECT_OT_duplicates_make_real(), OBJECT_OT_editmode_toggle(), OBJECT_OT_effector_add(), OBJECT_OT_explode_refresh(), OBJECT_OT_forcefield_toggle(), OBJECT_OT_game_physics_copy(), OBJECT_OT_game_property_clear(), OBJECT_OT_game_property_copy(), OBJECT_OT_game_property_new(), OBJECT_OT_game_property_remove(), OBJECT_OT_group_add(), OBJECT_OT_group_instance_add(), OBJECT_OT_group_link(), OBJECT_OT_group_remove(), OBJECT_OT_hide_render_clear(), OBJECT_OT_hide_render_set(), OBJECT_OT_hide_view_clear(), OBJECT_OT_hide_view_set(), OBJECT_OT_hook_add_newobj(), OBJECT_OT_hook_add_selobj(), OBJECT_OT_hook_assign(), OBJECT_OT_hook_recenter(), OBJECT_OT_hook_remove(), OBJECT_OT_hook_reset(), OBJECT_OT_hook_select(), OBJECT_OT_join(), OBJECT_OT_join_shapes(), OBJECT_OT_lamp_add(), OBJECT_OT_location_clear(), OBJECT_OT_logic_bricks_copy(), OBJECT_OT_make_links_data(), OBJECT_OT_make_links_scene(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_meshdeform_bind(), OBJECT_OT_metaball_add(), OBJECT_OT_mode_set(), OBJECT_OT_modifier_add(), OBJECT_OT_modifier_apply(), OBJECT_OT_modifier_convert(), OBJECT_OT_modifier_copy(), OBJECT_OT_modifier_move_down(), OBJECT_OT_modifier_move_up(), OBJECT_OT_modifier_remove(), OBJECT_OT_move_to_layer(), OBJECT_OT_multires_base_apply(), OBJECT_OT_multires_external_pack(), OBJECT_OT_multires_external_save(), OBJECT_OT_multires_higher_levels_delete(), OBJECT_OT_multires_reshape(), OBJECT_OT_multires_subdivide(), OBJECT_OT_ocean_bake(), OBJECT_OT_origin_clear(), OBJECT_OT_origin_set(), OBJECT_OT_parent_clear(), OBJECT_OT_parent_no_inverse_set(), OBJECT_OT_parent_set(), OBJECT_OT_paths_calculate(), OBJECT_OT_paths_clear(), OBJECT_OT_posemode_toggle(), OBJECT_OT_proxy_make(), OBJECT_OT_rotation_clear(), OBJECT_OT_scale_clear(), OBJECT_OT_select_all(), OBJECT_OT_select_by_layer(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_select_mirror(), OBJECT_OT_select_random(), OBJECT_OT_select_same_group(), OBJECT_OT_shade_flat(), OBJECT_OT_shade_smooth(), OBJECT_OT_shape_key_add(), OBJECT_OT_shape_key_clear(), OBJECT_OT_shape_key_mirror(), OBJECT_OT_shape_key_move(), OBJECT_OT_shape_key_remove(), OBJECT_OT_shape_key_retime(), OBJECT_OT_slow_parent_clear(), OBJECT_OT_slow_parent_set(), OBJECT_OT_speaker_add(), OBJECT_OT_text_add(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), OBJECT_OT_transform_apply(), OBJECT_OT_vertex_group_add(), OBJECT_OT_vertex_group_assign(), OBJECT_OT_vertex_group_blend(), OBJECT_OT_vertex_group_clean(), OBJECT_OT_vertex_group_copy(), OBJECT_OT_vertex_group_copy_to_linked(), OBJECT_OT_vertex_group_copy_to_selected(), OBJECT_OT_vertex_group_deselect(), OBJECT_OT_vertex_group_fix(), OBJECT_OT_vertex_group_invert(), OBJECT_OT_vertex_group_levels(), OBJECT_OT_vertex_group_lock(), OBJECT_OT_vertex_group_mirror(), OBJECT_OT_vertex_group_move(), OBJECT_OT_vertex_group_normalize(), OBJECT_OT_vertex_group_normalize_all(), OBJECT_OT_vertex_group_remove(), OBJECT_OT_vertex_group_remove_from(), OBJECT_OT_vertex_group_select(), OBJECT_OT_vertex_group_set_active(), OBJECT_OT_vertex_group_sort(), OBJECT_OT_vertex_parent_set(), OBJECT_OT_visual_transform_apply(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_constraints_clear(), POSE_OT_constraints_copy(), POSE_OT_ik_add(), POSE_OT_ik_clear(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
static int object_mode_poll (bContext * C) [static]
Definition at line 254 of file object_ops.c.
References CTX_data_active_object(), Object::mode, and OB_MODE_OBJECT.
Referenced by ED_keymap_object().