Blender: FilterNormal.cpp File Reference
FilterNormal.cpp File Reference
BGE Video Texture
#include <PyObjectPlus.h>
#include <structmember.h>
#include "FilterNormal.h"
#include "FilterBase.h"
#include "PyTypeList.h"
Functions
FilterNormal * getFilter (PyFilter *self)
static PyObject * getColor (PyFilter *self, void *closure)
static int setColor (PyFilter *self, PyObject *value, void *closure)
static PyObject * getDepth (PyFilter *self, void *closure)
static int setDepth (PyFilter *self, PyObject *value, void *closure)
Variables
static PyGetSetDef filterNormalGetSets []
PyTypeObject FilterNormalType
Detailed Description
Definition in file FilterNormal.cpp.
Function Documentation
static PyObject* getColor (PyFilter * self, void * closure) [static]
Definition at line 69 of file FilterNormal.cpp.
References getFilter().
static PyObject* getDepth (PyFilter * self, void * closure) [static]
Definition at line 91 of file FilterNormal.cpp.
References getFilter().
FilterNormal* getFilter (PyFilter * self) [inline]
Definition at line 62 of file FilterNormal.cpp.
static int setColor (PyFilter * self, PyObject * value, void * closure) [static]
Definition at line 75 of file FilterNormal.cpp.
References getFilter(), NULL, and FilterBlueScreen::setColor().
static int setDepth (PyFilter * self, PyObject * value, void * closure) [static]
Definition at line 97 of file FilterNormal.cpp.
References getFilter().
Variable Documentation
PyGetSetDef filterNormalGetSets[] [static]
Initial value:
{
    {(char*)"colorIdx", (getter)getColor, (setter)setColor, (char*)"index of color used to calculate normal (0 - red, 1 - green, 2 - blue)", NULL},
    {(char*)"depth", (getter)getDepth, (setter)setDepth, (char*)"depth of relief", NULL},
    {(char*)"previous", (getter)Filter_getPrevious, (setter)Filter_setPrevious, (char*)"previous pixel filter", NULL},
    {NULL}
}
Definition at line 118 of file FilterNormal.cpp.
PyTypeObject FilterNormalType
Definition at line 128 of file FilterNormal.cpp.
Referenced by registerAllTypes().