Blender: STR_String.h File Reference
STR_String.h File Reference
string
#include <vector>
#include <limits.h>
#include <cstring>
#include <cstdlib>
Classes
class STR_String
Defines
#define assertd(exp) ((void)NULL)
Typedefs
typedef unsigned long dword
typedef const STR_String & rcSTR_String
typedef unsigned char byte
Functions
STR_String operator+ (rcSTR_String lhs, rcSTR_String rhs)
STR_String operator+ (rcSTR_String lhs, char rhs)
STR_String operator+ (char lhs, rcSTR_String rhs)
STR_String operator+ (rcSTR_String lhs, const char *rhs)
STR_String operator+ (const char *lhs, rcSTR_String rhs)
Detailed Description
Definition in file STR_String.h.
Define Documentation
#define assertd (exp) ((void)NULL)
Copyright (C) 2001 NaN Technologies B.V. This file was formerly known as: GEN_StdString.h.
Date:
April, 25, 2001
Definition at line 45 of file STR_String.h.
Referenced by STR_String::GetAt(), and STR_String::SetAt().
Typedef Documentation
typedef unsigned char byte
Definition at line 66 of file STR_String.h.
typedef unsigned long dword
Definition at line 62 of file STR_String.h.
typedef const STR_String& rcSTR_String
Definition at line 65 of file STR_String.h.
Function Documentation
STR_String operator+ (rcSTR_String lhs, rcSTR_String rhs) [inline]
Definition at line 213 of file STR_String.h.
References STR_String::Length(), and STR_String::ReadPtr().
STR_String operator+ (const char * lhs, rcSTR_String rhs) [inline]
Definition at line 217 of file STR_String.h.
References STR_String::Length(), STR_String::ReadPtr(), and strlen().
STR_String operator+ (rcSTR_String lhs, const char * rhs) [inline]
Definition at line 216 of file STR_String.h.
References STR_String::Length(), STR_String::ReadPtr(), and strlen().
STR_String operator+ (char lhs, rcSTR_String rhs) [inline]
Definition at line 215 of file STR_String.h.
References STR_String::Length(), and STR_String::ReadPtr().
STR_String operator+ (rcSTR_String lhs, char rhs) [inline]
Definition at line 214 of file STR_String.h.
References STR_String::Length(), and STR_String::ReadPtr().