Blender: subd_patch.cpp File Reference
subd_patch.cpp File Reference
#include "mesh.h"
#include "subd_patch.h"
#include "util_math.h"
#include "util_types.h"
Functions
static CCL_NAMESPACE_BEGIN float3 decasteljau_quadratic (float t, const float3 cp[3])
static void decasteljau_cubic (float3 *P, float3 *dt, float t, const float3 cp[4])
static void decasteljau_bicubic (float3 *P, float3 *du, float3 *dv, const float3 cp[16], float u, float v)
static float3 decasteljau_tangent (const float3 cp[12], float u, float v)
static float no_zero_div (float f)
Function Documentation
static void decasteljau_bicubic (float3 * P, float3 * du, float3 * dv, const float3 cp[16], float u, float v) [static]
Definition at line 53 of file subd_patch.cpp.
References decasteljau_cubic(), and NULL.
Referenced by GregoryQuadPatch::eval(), BicubicTangentPatch::eval(), and BicubicPatch::eval().
static void decasteljau_cubic (float3 * P, float3 * dt, float t, const float3 cp[4]) [static]
Definition at line 40 of file subd_patch.cpp.
Referenced by decasteljau_bicubic(), and decasteljau_tangent().
static CCL_NAMESPACE_BEGIN float3 decasteljau_quadratic (float t, const float3 cp[3]) [static]
Definition at line 32 of file subd_patch.cpp.
Referenced by decasteljau_tangent().
static float3 decasteljau_tangent (const float3 cp[12], float u, float v) [static]
Definition at line 68 of file subd_patch.cpp.
References decasteljau_cubic(), decasteljau_quadratic(), and NULL.
Referenced by BicubicTangentPatch::eval().
static float no_zero_div (float f) [static]
Definition at line 165 of file subd_patch.cpp.
Referenced by GregoryTrianglePatch::eval(), and GregoryQuadPatch::eval().