Blender: bsdf_ward.h File Reference
bsdf_ward.h File Reference
Classes
struct BsdfWardClosure
Typedefs
typedef CCL_NAMESPACE_BEGIN
struct BsdfWardClosure BsdfWardClosure
Functions
__device void bsdf_ward_setup (ShaderData *sd, ShaderClosure *sc, float3 T, float ax, float ay)
__device void bsdf_ward_blur (ShaderClosure *sc, float roughness)
__device float3 bsdf_ward_eval_reflect (const ShaderData *sd, const ShaderClosure *sc, const float3 I, const float3 omega_in, float *pdf)
__device float3 bsdf_ward_eval_transmit (const ShaderData *sd, const ShaderClosure *sc, const float3 I, const float3 omega_in, float *pdf)
__device float bsdf_ward_albedo (const ShaderData *sd, const ShaderClosure *sc, const float3 I)
__device int bsdf_ward_sample (const ShaderData *sd, const ShaderClosure *sc, float randu, float randv, float3 *eval, float3 *omega_in, float3 *domega_in_dx, float3 *domega_in_dy, float *pdf)
Typedef Documentation
typedef CCL_NAMESPACE_BEGIN struct BsdfWardClosure BsdfWardClosure
Function Documentation
__device float bsdf_ward_albedo (const ShaderData * sd, const ShaderClosure * sc, const float3 I)
Definition at line 101 of file bsdf_ward.h.
__device void bsdf_ward_blur (ShaderClosure * sc, float roughness)
Definition at line 59 of file bsdf_ward.h.
References ShaderClosure::data0, ShaderClosure::data1, and fmaxf.
Referenced by svm_bsdf_blur().
__device float3 bsdf_ward_eval_reflect (const ShaderData * sd, const ShaderClosure * sc, const float3 I, const float3 omega_in, float * pdf)
Definition at line 65 of file bsdf_ward.h.
References ShaderClosure::data0, ShaderClosure::data1, dot(), ShaderData::dPdu, expf, H, M_PI_F, make_float3(), make_orthonormals_tangent(), ShaderData::N, normalize(), sqrtf, and X.
Referenced by svm_bsdf_eval().
__device float3 bsdf_ward_eval_transmit (const ShaderData * sd, const ShaderClosure * sc, const float3 I, const float3 omega_in, float * pdf)
Definition at line 96 of file bsdf_ward.h.
References make_float3().
Referenced by svm_bsdf_eval().
__device int bsdf_ward_sample (const ShaderData * sd, const ShaderClosure * sc, float randu, float randv, float3 * eval, float3 * omega_in, float3 * domega_in_dx, float3 * domega_in_dy, float * pdf)
Definition at line 106 of file bsdf_ward.h.
References ShaderClosure::data0, ShaderClosure::data1, ShaderData::dI, dot(), ShaderData::dPdu, differential3::dx, differential3::dy, expf, ShaderData::I, LABEL_GLOSSY, LABEL_REFLECT, logf, M_PI_2_F, M_PI_F, make_float3(), make_orthonormals_tangent(), ShaderData::N, ShaderData::Ng, normalize(), sqrtf, tanf, float3::x, X, float3::y, and float3::z.
Referenced by svm_bsdf_sample().
__device void bsdf_ward_setup (ShaderData * sd, ShaderClosure * sc, float3 T, float ax, float ay)
Definition at line 47 of file bsdf_ward.h.
References clamp, CLOSURE_BSDF_WARD_ID, ShaderClosure::data0, ShaderClosure::data1, ShaderData::flag, SD_BSDF, SD_BSDF_GLOSSY, SD_BSDF_HAS_EVAL, and ShaderClosure::type.
Referenced by svm_node_closure_bsdf().