Blender: bmo_mirror.c File Reference
bmo_mirror.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "DNA_meshdata_types.h"
#include "BLI_math.h"
#include "BLI_array.h"
#include "BKE_customdata.h"
#include "bmesh.h"
#include "intern/bmesh_operators_private.h"
Defines
#define ELE_NEW 1
Functions
void bmo_mirror_exec (BMesh *bm, BMOperator *op)
Detailed Description
Definition in file bmo_mirror.c.
Define Documentation
#define ELE_NEW 1
Definition at line 39 of file bmo_mirror.c.
Referenced by bmo_mirror_exec().
Function Documentation
void bmo_mirror_exec (BMesh * bm, BMOperator * op)
Definition at line 41 of file bmo_mirror.c.
References ABS, BLI_array_declare, BLI_array_free, BLI_array_growone, BM_ALL, BM_FACE, BM_ITER_ELEM, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BM_VERT, BM_VERTS_OF_MESH, BMO_ITER, BMO_op_callf(), BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_op_initf(), BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), BMO_slot_map_ptr_insert(), BMO_slot_mat4_get(), CD_MLOOPUV, BMVert::co, CustomData_bmesh_get_n(), CustomData_number_of_layers(), BMHeader::data, ELE_NEW, BMesh::elem_index_dirty, BMLoop::head, i, invert_m4_m4(), BMesh::ldata, NULL, BMesh::totvert, and MLoopUV::uv.