Blender: MT_Point3 Class Reference
MT_Point3 Class Reference
#include <MT_Point3.h>
Public Member Functions
MT_Point3 ()
MT_Point3 (const float *v)
MT_Point3 (const double *v)
MT_Point3 (MT_Scalar xx, MT_Scalar yy, MT_Scalar zz)
MT_Point3 & operator+= (const MT_Vector3 &v)
MT_Point3 & operator-= (const MT_Vector3 &v)
MT_Point3 & operator= (const MT_Vector3 &v)
MT_Point3 & operator= (const MT_Point3 &v)
MT_Scalar distance (const MT_Point3 &p) const
MT_Scalar distance2 (const MT_Point3 &p) const
MT_Point3 lerp (const MT_Point3 &p, MT_Scalar t) const
Detailed Description
Definition at line 52 of file MT_Point3.h.
Constructor & Destructor Documentation
MT_Point3::MT_Point3 () [inline]
Definition at line 54 of file MT_Point3.h.
Referenced by lerp().
MT_Point3::MT_Point3 (const float * v) [inline]
Definition at line 55 of file MT_Point3.h.
MT_Point3::MT_Point3 (const double * v) [inline]
Definition at line 56 of file MT_Point3.h.
MT_Point3::MT_Point3 (MT_Scalar xx, MT_Scalar yy, MT_Scalar zz) [inline]
Definition at line 57 of file MT_Point3.h.
Member Function Documentation
GEN_INLINE MT_Scalar MT_Point3::distance (const MT_Point3 & p) const
Definition at line 23 of file MT_Point3.inl.
Referenced by BOP_between(), BOP_EpsilonDistance(), BOP_getNearestVertex(), BOP_isInsideCircle(), BOP_mergeSort(), KX_Camera::ExtractFrustumSphere(), and MT_distance().
GEN_INLINE MT_Scalar MT_Point3::distance2 (const MT_Point3 & p) const
Definition at line 27 of file MT_Point3.inl.
Referenced by SG_Spatial::inside(), MT_distance2(), and KX_Camera::SphereInsideFrustum().
GEN_INLINE MT_Point3 MT_Point3::lerp (const MT_Point3 & p, MT_Scalar t) const
Definition at line 31 of file MT_Point3.inl.
References MT_Tuple3::m_co, and MT_Point3().
Referenced by BOP_getCircleCenter(), and MT_lerp().
GEN_INLINE MT_Point3 & MT_Point3::operator+= (const MT_Vector3 & v)
Reimplemented from MT_Vector3.
Definition at line 3 of file MT_Point3.inl.
References MT_Tuple3::m_co.
GEN_INLINE MT_Point3 & MT_Point3::operator-= (const MT_Vector3 & v)
Reimplemented from MT_Vector3.
Definition at line 8 of file MT_Point3.inl.
References MT_Tuple3::m_co.
GEN_INLINE MT_Point3 & MT_Point3::operator= (const MT_Vector3 & v)
Definition at line 13 of file MT_Point3.inl.
References MT_Tuple3::m_co.
GEN_INLINE MT_Point3 & MT_Point3::operator= (const MT_Point3 & v)
Definition at line 18 of file MT_Point3.inl.
References MT_Tuple3::m_co.
The documentation for this class was generated from the following files:
MT_Point3.h
MT_Point3.inl