Blender: RAS_VAOpenGLRasterizer Class Reference
RAS_VAOpenGLRasterizer Class Reference
#include <RAS_VAOpenGLRasterizer.h>
Public Member Functions
RAS_VAOpenGLRasterizer (RAS_ICanvas *canvas, bool lock=false)
virtual ~RAS_VAOpenGLRasterizer ()
virtual bool Init ()
virtual void Exit ()
virtual void SetDrawingMode (int drawingmode)
virtual void IndexPrimitives (class RAS_MeshSlot &ms)
virtual void IndexPrimitivesMulti (class RAS_MeshSlot &ms)
Detailed Description
Definition at line 37 of file RAS_VAOpenGLRasterizer.h.
Constructor & Destructor Documentation
RAS_VAOpenGLRasterizer::RAS_VAOpenGLRasterizer (RAS_ICanvas * canvas, bool lock = false)
Definition at line 43 of file RAS_VAOpenGLRasterizer.cpp.
RAS_VAOpenGLRasterizer::~RAS_VAOpenGLRasterizer () [virtual]
Definition at line 51 of file RAS_VAOpenGLRasterizer.cpp.
Member Function Documentation
void RAS_VAOpenGLRasterizer::Exit () [virtual]
Exit cleans up the renderer.
Reimplemented from RAS_OpenGLRasterizer.
Reimplemented in RAS_ListRasterizer.
Definition at line 96 of file RAS_VAOpenGLRasterizer.cpp.
void RAS_VAOpenGLRasterizer::IndexPrimitives (class RAS_MeshSlot & ms) [virtual]
IndexPrimitives: Renders primitives from mesh slot.
Reimplemented from RAS_OpenGLRasterizer.
Reimplemented in RAS_ListRasterizer.
Definition at line 106 of file RAS_VAOpenGLRasterizer.cpp.
References RAS_MeshSlot::iterator::array, RAS_MeshSlot::begin(), RAS_MeshSlot::end(), RAS_TexVert::getNormal(), RAS_TexVert::getRGBA(), RAS_TexVert::getUV1(), RAS_TexVert::getXYZ(), RAS_MeshSlot::iterator::index, RAS_OpenGLRasterizer::IndexPrimitivesInternal(), RAS_IRasterizer::KX_WIREFRAME, RAS_MeshSlot::m_bObjectColor, RAS_OpenGLRasterizer::m_drawingmode, RAS_MeshSlot::m_pDerivedMesh, RAS_MeshSlot::m_RGBAcolor, RAS_DisplayArray::m_type, RAS_MeshSlot::next(), RAS_DisplayArray::QUAD, RAS_MeshSlot::iterator::totindex, RAS_DisplayArray::TRIANGLE, and RAS_MeshSlot::iterator::vertex.
void RAS_VAOpenGLRasterizer::IndexPrimitivesMulti (class RAS_MeshSlot & ms) [virtual]
Reimplemented from RAS_OpenGLRasterizer.
Reimplemented in RAS_ListRasterizer.
Definition at line 169 of file RAS_VAOpenGLRasterizer.cpp.
References RAS_MeshSlot::iterator::array, RAS_MeshSlot::begin(), RAS_MeshSlot::end(), RAS_TexVert::getNormal(), RAS_TexVert::getRGBA(), RAS_TexVert::getXYZ(), RAS_MeshSlot::iterator::index, RAS_OpenGLRasterizer::IndexPrimitivesInternal(), RAS_IRasterizer::KX_WIREFRAME, RAS_MeshSlot::m_bObjectColor, RAS_OpenGLRasterizer::m_drawingmode, RAS_MeshSlot::m_pDerivedMesh, RAS_MeshSlot::m_RGBAcolor, RAS_DisplayArray::m_type, RAS_MeshSlot::next(), RAS_DisplayArray::QUAD, RAS_MeshSlot::iterator::totindex, RAS_DisplayArray::TRIANGLE, and RAS_MeshSlot::iterator::vertex.
bool RAS_VAOpenGLRasterizer::Init () [virtual]
Init initializes the renderer.
Reimplemented from RAS_OpenGLRasterizer.
Reimplemented in RAS_ListRasterizer.
Definition at line 55 of file RAS_VAOpenGLRasterizer.cpp.
void RAS_VAOpenGLRasterizer::SetDrawingMode (int drawingmode) [virtual]
Parameters:
drawingmode = KX_BOUNDINGBOX, KX_WIREFRAME, KX_SOLID, KX_SHADED or KX_TEXTURED.
Reimplemented from RAS_OpenGLRasterizer.
Reimplemented in RAS_ListRasterizer.
Definition at line 73 of file RAS_VAOpenGLRasterizer.cpp.
References RAS_IRasterizer::KX_BOUNDINGBOX, RAS_IRasterizer::KX_SHADED, RAS_IRasterizer::KX_SHADOW, RAS_IRasterizer::KX_SOLID, RAS_IRasterizer::KX_TEXTURED, RAS_IRasterizer::KX_WIREFRAME, and RAS_OpenGLRasterizer::m_drawingmode.
The documentation for this class was generated from the following files:
RAS_VAOpenGLRasterizer.h
RAS_VAOpenGLRasterizer.cpp