Blender: editmesh_utils.c File Reference
editmesh_utils.c File Reference
mesh
#include "MEM_guardedalloc.h"
#include "DNA_mesh_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BKE_DerivedMesh.h"
#include "BKE_bmesh.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_key.h"
#include "BKE_library.h"
#include "BKE_mesh.h"
#include "BKE_report.h"
#include "BKE_tessmesh.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_mesh.h"
#include "ED_util.h"
#include "bmesh.h"
#include "mesh_intern.h"
Classes
struct UndoMesh
Defines
#define BM_SEARCH_MAXDIST_MIRR 0.00002f
#define BM_CD_LAYER_ID "__mirror_index"
Typedefs
typedef struct UndoMesh UndoMesh
Functions
void EDBM_mesh_normals_update (BMEditMesh *em)
void EDBM_mesh_clear (BMEditMesh *em)
void EDBM_stats_update (BMEditMesh *em)
int EDBM_op_init (BMEditMesh *em, BMOperator *bmop, wmOperator *op, const char *fmt,...)
int EDBM_op_finish (BMEditMesh *em, BMOperator *bmop, wmOperator *op, const int report)
int EDBM_op_callf (BMEditMesh *em, wmOperator *op, const char *fmt,...)
int EDBM_op_call_and_selectf (BMEditMesh *em, wmOperator *op, const char *selectslot, const char *fmt,...)
int EDBM_op_call_silentf (BMEditMesh *em, const char *fmt,...)
void EDBM_selectmode_to_scene (bContext *C)
void EDBM_mesh_make (ToolSettings *ts, Scene *UNUSED(scene), Object *ob)
void EDBM_mesh_load (Object *ob)
void EDBM_mesh_free (BMEditMesh *em)
void EDBM_index_arrays_init (BMEditMesh *tm, int forvert, int foredge, int forface)
void EDBM_index_arrays_free (BMEditMesh *tm)
BMVert * EDBM_vert_at_index (BMEditMesh *tm, int index)
BMEdge * EDBM_edge_at_index (BMEditMesh *tm, int index)
BMFace * EDBM_face_at_index (BMEditMesh *tm, int index)
void EDBM_selectmode_flush_ex (BMEditMesh *em, int selectmode)
void EDBM_selectmode_flush (BMEditMesh *em)
void EDBM_deselect_flush (BMEditMesh *em)
void EDBM_select_flush (BMEditMesh *em)
void EDBM_select_more (BMEditMesh *em)
void EDBM_select_less (BMEditMesh *em)
void EDBM_flag_disable_all (BMEditMesh *em, const char hflag)
void EDBM_flag_enable_all (BMEditMesh *em, const char hflag)
static void * getEditMesh (bContext *C)
static void * editbtMesh_to_undoMesh (void *emv, void *obdata)
static void undoMesh_to_editbtMesh (void *umv, void *em_v, void *UNUSED(obdata))
static void free_undo (void *me_v)
void undo_push_mesh (bContext *C, const char *name)
UvVertMap * EDBM_uv_vert_map_create (BMEditMesh *em, int selected, int do_face_idx_array, float *limit)
UvMapVert * EDBM_uv_vert_map_at_index (UvVertMap *vmap, unsigned int v)
UvElementMap * EDBM_uv_element_map_create (BMEditMesh *em, int selected, int do_islands)
void EDBM_uv_vert_map_free (UvVertMap *vmap)
void EDBM_uv_element_map_free (UvElementMap *element_map)
MTexPoly * EDBM_mtexpoly_active_get (BMEditMesh *em, BMFace **r_act_efa, int sloppy)
int EDBM_mtexpoly_check (BMEditMesh *em)
int EDBM_vert_color_check (BMEditMesh *em)
static BMVert * cache_mirr_intptr_as_bmvert (intptr_t *index_lookup, int index)
void EDBM_verts_mirror_cache_begin (BMEditMesh *em, const short use_select)
BMVert * EDBM_verts_mirror_get (BMEditMesh *em, BMVert *v)
void EDBM_verts_mirror_cache_clear (BMEditMesh *em, BMVert *v)
void EDBM_verts_mirror_cache_end (BMEditMesh *em)
void EDBM_verts_mirror_apply (BMEditMesh *em, const int sel_from, const int sel_to)
void EDBM_mesh_hide (BMEditMesh *em, int swap)
void EDBM_mesh_reveal (BMEditMesh *em)
void EDBM_update_generic (bContext *C, BMEditMesh *em, const short do_tessface)
Detailed Description
Definition in file editmesh_utils.c.
Define Documentation
#define BM_CD_LAYER_ID "__mirror_index"
Definition at line 1011 of file editmesh_utils.c.
Referenced by EDBM_verts_mirror_cache_begin().
#define BM_SEARCH_MAXDIST_MIRR 0.00002f
[note: I've decided to use ideasman's code for non-editmode stuff, but since it has a big "not for editmode!" disclaimer, I'm going to keep what I have here
joeedh]
x-mirror editing api. usage:
EDBM_verts_mirror_cache_begin(em); ... ... BM_ITER_MESH (v, &iter, em->bm, BM_VERTS_OF_MESH) { mirrorv = EDBM_verts_mirror_get(em, v); } ... ... EDBM_verts_mirror_cache_end(em);
Note:
why do we only allow x axis mirror editing?
Definition at line 1010 of file editmesh_utils.c.
Referenced by EDBM_verts_mirror_cache_begin().
Typedef Documentation
typedef struct UndoMesh UndoMesh
Function Documentation
static BMVert* cache_mirr_intptr_as_bmvert (intptr_t * index_lookup, int index) [static]
Definition at line 982 of file editmesh_utils.c.
References NULL.
Referenced by EDBM_verts_mirror_cache_begin().
void EDBM_deselect_flush (BMEditMesh * em)
Definition at line 421 of file editmesh_utils.c.
References BMEditMesh::bm, BM_mesh_deselect_flush(), BMEditMesh::selectmode, and BMesh::selectmode.
Referenced by border_select_exec(), mouse_select(), and vgroup_select_verts().
BMEdge* EDBM_edge_at_index (BMEditMesh * tm, int index) [read]
Definition at line 399 of file editmesh_utils.c.
References BMEditMesh::bm, BMEditMesh::edge_index, NULL, and BMesh::totedge.
Referenced by bbs_mesh_wire__setDrawOptions(), construct_param_handle_subsurfed(), draw_dm_bweights__setDrawOptions(), draw_dm_creases__setDrawOptions(), draw_dm_edges__setDrawOptions(), draw_dm_edges_seams__setDrawOptions(), draw_dm_edges_sel__setDrawOptions(), draw_dm_edges_sel_interp__setDrawInterpOptions(), draw_dm_edges_sel_interp__setDrawOptions(), draw_dm_edges_sharp__setDrawOptions(), edgetag_add_adjacent(), edgetag_shortest_path(), mesh_foreachScreenEdge__mapFunc(), and snapDerivedMesh().
BMFace* EDBM_face_at_index (BMEditMesh * tm, int index) [read]
Definition at line 404 of file editmesh_utils.c.
References BMEditMesh::face_index, and NULL.
Referenced by bbs_mesh_solid__drawCenter(), bbs_mesh_solid__setSolidDrawOptions(), construct_param_handle_subsurfed(), draw_dm_face_centers__mapFunc(), draw_dm_face_normals__mapFunc(), draw_dm_faces_sel__compareDrawOptions(), draw_dm_faces_sel__setDrawOptions(), draw_em_fancy__setFaceOpts(), draw_em_fancy__setGLSLFaceOpts(), draw_em_tf_mapped__set_draw(), EDBM_uv_vert_map_create(), mesh_foreachScreenFace__mapFunc(), select_edgeloop_uv_edge_tag_faces(), snapDerivedMesh(), stitch_init(), tex_mat_set_face_editmesh_cb(), and uv_faces_do_sticky().
void EDBM_flag_disable_all (BMEditMesh * em, const char hflag)
Definition at line 468 of file editmesh_utils.c.
References BMEditMesh::bm, BM_EDGE, BM_FACE, BM_mesh_elem_hflag_disable_all(), BM_VERT, and FALSE.
Referenced by do_lasso_select_mesh(), do_mesh_box_select(), edbm_delete_exec(), edbm_duplicate_exec(), edbm_extrude_edge(), edbm_extrude_edges_indiv(), edbm_extrude_face_indiv(), edbm_inset_exec(), edbm_loop_to_region_exec(), EDBM_mesh_reveal(), edbm_region_to_loop_exec(), edbm_screw_exec(), edbm_select_all_exec(), EDBM_select_mirrored(), edbm_select_random_exec(), EDBM_select_toggle_all(), edbm_spin_exec(), edbm_vertex_slide_exec(), edgering_sel(), knife_make_cuts(), mesh_separate_loose(), mesh_separate_material(), mouse_mesh(), mouse_mesh_loop(), select_all_perform(), similar_edge_select_exec(), similar_face_select_exec(), similar_vert_select_exec(), and vtx_slide_confirm().
void EDBM_flag_enable_all (BMEditMesh * em, const char hflag)
Definition at line 473 of file editmesh_utils.c.
References BMEditMesh::bm, BM_EDGE, BM_FACE, BM_mesh_elem_hflag_enable_all(), BM_VERT, and TRUE.
Referenced by edbm_select_all_exec(), EDBM_select_toggle_all(), and select_all_perform().
void EDBM_index_arrays_free (BMEditMesh * tm)
Definition at line 376 of file editmesh_utils.c.
References BMEditMesh::edge_index, BMEditMesh::face_index, MEM_freeN(), NULL, and BMEditMesh::vert_index.
Referenced by construct_param_handle_subsurfed(), createRepresentation(), draw_em_fancy(), draw_object_backbufsel(), ED_mesh_mirrtopo_init(), EDBM_index_arrays_init(), EDBM_uv_vert_map_create(), edgetag_shortest_path(), make_trans_verts(), mesh_foreachScreenEdge(), mesh_foreachScreenFace(), mesh_foreachScreenVert(), select_edgeloop(), select_linked(), snapDerivedMesh(), stitch_init(), and uv_faces_do_sticky().
void EDBM_index_arrays_init (BMEditMesh * tm, int forvert, int foredge, int forface)
Definition at line 332 of file editmesh_utils.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, EDBM_index_arrays_free(), BMEditMesh::edge_index, BMEditMesh::face_index, i, MEM_mallocN(), NULL, BMesh::totedge, BMesh::totface, BMesh::totvert, and BMEditMesh::vert_index.
Referenced by construct_param_handle_subsurfed(), createRepresentation(), draw_em_fancy(), draw_object_backbufsel(), ED_mesh_mirrtopo_init(), EDBM_uv_vert_map_create(), EDBM_verts_mirror_cache_begin(), edgetag_shortest_path(), make_trans_verts(), mesh_foreachScreenEdge(), mesh_foreachScreenFace(), mesh_foreachScreenVert(), select_edgeloop(), select_linked(), snapDerivedMesh(), stitch_init(), and uv_faces_do_sticky().
void EDBM_mesh_clear (BMEditMesh * em)
Definition at line 66 of file editmesh_utils.c.
References BMEditMesh::bm, BM_mesh_clear(), BMEditMesh::derivedCage, BMEditMesh::derivedFinal, BMEditMesh::looptris, MEM_freeN(), DerivedMesh::needsFree, NULL, DerivedMesh::release, and BMEditMesh::tottri.
Referenced by createRepresentation().
void EDBM_mesh_free (BMEditMesh * em)
Should only be called on the active editmesh, otherwise call BMEdit_Free
Definition at line 321 of file editmesh_utils.c.
References BMEdit_Free(), mesh_mirrtopo_table(), mesh_octree_table(), and NULL.
Referenced by drop_named_image_invoke(), ED_editors_exit(), ED_object_exit_editmode(), EDBM_mesh_make(), EDBM_op_finish(), join_mesh_exec(), and undoMesh_to_editbtMesh().
void EDBM_mesh_hide (BMEditMesh * em, int swap)
Definition at line 1153 of file editmesh_utils.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_elem_hide_set, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_MESH, BM_VERTS_OF_MESH, EDBM_selectmode_flush(), NULL, SCE_SELECT_EDGE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, and TRUE.
Referenced by edbm_hide_exec(), and hide_exec().
void EDBM_mesh_load (Object * ob)
Definition at line 306 of file editmesh_utils.c.
References BKE_mesh_tessface_calc(), BMEditMesh::bm, BM_mesh_bm_to_me(), Object::data, Mesh::edit_btmesh, and FALSE.
Referenced by drop_named_image_invoke(), ED_object_exit_editmode(), join_mesh_exec(), object_hook_index_array(), and vertex_parent_set_exec().
void EDBM_mesh_make (ToolSettings * ts, Scene * UNUSEDscene, Object * ob)
Definition at line 274 of file editmesh_utils.c.
References Object::actcol, BKE_mesh_convert_mfaces_to_mpolys(), BKE_mesh_to_bmesh(), BMEditMesh::bm, BMEdit_Create(), Object::data, EDBM_mesh_free(), Mesh::edit_btmesh, FALSE, BMEditMesh::mat_nr, BMEditMesh::me, MEM_freeN(), Mesh::mpoly, BMEditMesh::ob, ToolSettings::selectmode, BMesh::selectmode, BMEditMesh::selectmode, Mesh::totface, TRUE, and UNLIKELY.
void EDBM_mesh_normals_update (BMEditMesh * em)
Definition at line 61 of file editmesh_utils.c.
References BMEditMesh::bm, BM_mesh_normals_update(), and TRUE.
Referenced by ED_object_enter_editmode(), edbm_bevel_exec(), edbm_dupli_extrude_cursor_invoke(), edbm_extrude_region_exec(), edbm_extrude_repeat_exec(), EDBM_mesh_reveal(), edbm_noise_exec(), edbm_split_exec(), object_origin_set_exec(), recalcData_view3d(), and v3d_editvertex_buts().
void EDBM_mesh_reveal (BMEditMesh * em)
Definition at line 1185 of file editmesh_utils.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_set, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_select_set(), BM_ELEM_TAG, BM_FACES_OF_MESH, BM_ITER_MESH, BM_VERTS_OF_MESH, EDBM_flag_disable_all(), EDBM_mesh_normals_update(), EDBM_selectmode_flush(), i, SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, and TRUE.
Referenced by edbm_reveal_exec(), and reveal_exec().
MTexPoly* EDBM_mtexpoly_active_get (BMEditMesh * em, BMFace ** r_act_efa, int sloppy) [read]
Definition at line 950 of file editmesh_utils.c.
References BMEditMesh::bm, BM_active_face_get(), CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, EDBM_mtexpoly_check(), BMFace::head, NULL, and BMesh::pdata.
Referenced by draw_uvs(), and image_refresh().
int EDBM_mtexpoly_check (BMEditMesh * em)
Definition at line 969 of file editmesh_utils.c.
References BMEditMesh::bm, CD_MLOOPUV, CD_MTEXPOLY, CustomData_has_layer(), BMesh::ldata, BMesh::pdata, and BMesh::totface.
Referenced by ED_space_image_show_uvedit(), ED_space_image_show_uvshadow(), ED_uvedit_test(), EDBM_mtexpoly_active_get(), image_refresh(), and uv_sculpt_brush_poll().
int EDBM_op_call_and_selectf (BMEditMesh * em, wmOperator * op, const char * selectslot, const char * fmt, ...)
Definition at line 208 of file editmesh_utils.c.
References BKE_reportf(), BMEditMesh::bm, BM_ALL, BM_EDGE, BM_ELEM_SELECT, BM_FACE, BM_mesh_elem_hflag_disable_all(), BM_VERT, BMEdit_Copy(), BMO_op_exec(), BMO_op_vinitf(), BMO_slot_buffer_hflag_enable(), EDBM_op_finish(), BMEditMesh::emcopy, BMEditMesh::emcopyusers, FALSE, wmOperator::reports, RPT_ERROR, and TRUE.
Referenced by add_primitive_circle_exec(), add_primitive_cone_exec(), add_primitive_cube_exec(), add_primitive_cylinder_exec(), add_primitive_grid_exec(), add_primitive_icosphere_exec(), add_primitive_monkey_exec(), add_primitive_plane_exec(), and add_primitive_uvsphere_exec().
int EDBM_op_call_silentf (BMEditMesh * em, const char * fmt, ...)
Definition at line 236 of file editmesh_utils.c.
References BMEditMesh::bm, BMEdit_Copy(), BMO_op_exec(), BMO_op_vinitf(), EDBM_op_finish(), BMEditMesh::emcopy, BMEditMesh::emcopyusers, FALSE, and NULL.
int EDBM_op_callf (BMEditMesh * em, wmOperator * op, const char * fmt, ...)
Definition at line 184 of file editmesh_utils.c.
References BKE_reportf(), BMEditMesh::bm, BMEdit_Copy(), BMO_op_exec(), BMO_op_vinitf(), EDBM_op_finish(), BMEditMesh::emcopy, BMEditMesh::emcopyusers, wmOperator::reports, RPT_ERROR, and TRUE.
Referenced by edbm_beautify_fill_exec(), edbm_bridge_edge_loops_exec(), edbm_collapse_edge_exec(), edbm_collapse_edge_loop_exec(), edbm_delete_exec(), edbm_dissolve_exec(), edbm_dissolve_limited_exec(), edbm_do_smooth_vertex_exec(), edbm_dupli_extrude_cursor_invoke(), edbm_flip_normals_exec(), edbm_merge_exec(), edbm_normals_make_consistent_exec(), edbm_quads_convert_to_tris_exec(), edbm_remove_doubles_exec(), edbm_tris_convert_to_quads_exec(), merge_firstlast(), merge_target(), mesh_separate_selected(), and vtx_slide_confirm().
int EDBM_op_finish (BMEditMesh * em, BMOperator * bmop, wmOperator * op, const int report)
Definition at line 140 of file editmesh_utils.c.
References BKE_report(), BMEditMesh::bm, BMEdit_Free(), BMEdit_RecalcTessellation(), BMO_error_get(), BMO_op_finish(), EDBM_mesh_free(), BMEditMesh::emcopy, BMEditMesh::emcopyusers, FALSE, BMEditMesh::looptris, MEM_freeN(), NULL, wmOperator::reports, RPT_ERROR, and TRUE.
Referenced by edbm_add_edge_face_exec(), edbm_bevel_exec(), edbm_dupli_extrude_cursor_invoke(), edbm_duplicate_exec(), edbm_edge_rotate_selected_exec(), edbm_edge_split_exec(), edbm_extrude_edges_indiv(), edbm_extrude_face_indiv(), edbm_extrude_verts_indiv(), edbm_fill_exec(), edbm_inset_exec(), edbm_knife_cut_exec(), EDBM_op_call_and_selectf(), EDBM_op_call_silentf(), EDBM_op_callf(), edbm_remove_doubles_exec(), edbm_reverse_colors_exec(), edbm_reverse_uvs_exec(), edbm_rip_call_edgesplit(), edbm_rotate_colors_exec(), edbm_rotate_uvs_exec(), edbm_screw_exec(), edbm_select_vertex_path_exec(), edbm_solidify_exec(), edbm_spin_exec(), edbm_split_exec(), edbm_vert_connect(), edbm_vertex_slide_exec(), similar_edge_select_exec(), similar_face_select_exec(), and similar_vert_select_exec().
int EDBM_op_init (BMEditMesh * em, BMOperator * bmop, wmOperator * op, const char * fmt, ...)
Definition at line 116 of file editmesh_utils.c.
References BKE_reportf(), BMEditMesh::bm, BMEdit_Copy(), BMO_op_vinitf(), BMEditMesh::emcopy, BMEditMesh::emcopyusers, wmOperator::reports, and RPT_ERROR.
Referenced by edbm_add_edge_face_exec(), edbm_bevel_exec(), edbm_dupli_extrude_cursor_invoke(), edbm_duplicate_exec(), edbm_edge_rotate_selected_exec(), edbm_edge_split_exec(), edbm_extrude_edges_indiv(), edbm_extrude_face_indiv(), edbm_extrude_verts_indiv(), edbm_fill_exec(), edbm_inset_exec(), edbm_knife_cut_exec(), edbm_remove_doubles_exec(), edbm_reverse_colors_exec(), edbm_reverse_uvs_exec(), edbm_rip_call_edgesplit(), edbm_rotate_colors_exec(), edbm_rotate_uvs_exec(), edbm_screw_exec(), edbm_select_vertex_path_exec(), edbm_solidify_exec(), edbm_spin_exec(), edbm_split_exec(), edbm_vert_connect(), edbm_vertex_slide_exec(), similar_edge_select_exec(), similar_face_select_exec(), and similar_vert_select_exec().
void EDBM_select_flush (BMEditMesh * em)
Definition at line 429 of file editmesh_utils.c.
References BMEditMesh::bm, BM_mesh_select_flush(), BMEditMesh::selectmode, and BMesh::selectmode.
Referenced by EDBM_select_more(), EDBM_selectmode_set(), mouse_select(), select_editbmesh_hook(), and vgroup_select_verts().
void EDBM_select_less (BMEditMesh * em)
Definition at line 452 of file editmesh_utils.c.
References BMEditMesh::bm, BM_ALL, BM_ELEM_SELECT, BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_hflag_disable(), EDBM_selectmode_flush(), FALSE, SCE_SELECT_FACE, BMEditMesh::selectmode, and TRUE.
Referenced by edbm_select_less_exec().
void EDBM_select_more (BMEditMesh * em)
Definition at line 436 of file editmesh_utils.c.
References BMEditMesh::bm, BM_ALL, BM_ELEM_SELECT, BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_hflag_enable(), EDBM_select_flush(), FALSE, SCE_SELECT_FACE, BMEditMesh::selectmode, and TRUE.
Referenced by edbm_select_more_exec().
void EDBM_selectmode_flush (BMEditMesh * em)
Definition at line 416 of file editmesh_utils.c.
References EDBM_selectmode_flush_ex(), and BMEditMesh::selectmode.
Referenced by deselect_nth_active(), do_lasso_select_mesh(), do_mesh_box_select(), edbm_edge_rotate_selected_exec(), edbm_loop_multiselect_exec(), EDBM_mesh_hide(), EDBM_mesh_reveal(), edbm_rip_invoke__edge(), edbm_select_all_exec(), edbm_select_axis_exec(), edbm_select_by_number_vertices_exec(), EDBM_select_less(), edbm_select_loose_verts_exec(), edbm_select_mirror_exec(), edbm_select_random_exec(), edbm_select_vertex_path_exec(), EDBM_selectmode_set(), edbm_vertex_slide_exec(), mesh_circle_select(), mouse_mesh(), mouse_mesh_loop(), mouse_mesh_shortest_path(), mouse_select(), ringsel_finish(), select_all_perform(), similar_edge_select_exec(), similar_vert_select_exec(), vtx_slide_confirm(), and vtx_slide_init().
void EDBM_selectmode_flush_ex (BMEditMesh * em, int selectmode)
Definition at line 409 of file editmesh_utils.c.
References BMEditMesh::bm, BM_mesh_select_mode_flush(), BMEditMesh::selectmode, and BMesh::selectmode.
Referenced by edbm_select_linked_exec(), EDBM_selectmode_flush(), hide_exec(), make_prim_finish(), mesh_separate_loose(), and walker_deselect_nth().
void EDBM_selectmode_to_scene (bContext * C)
Definition at line 259 of file editmesh_utils.c.
References BMEdit_FromObject(), CTX_data_edit_object(), CTX_data_scene(), NC_SCENE, ND_TOOLSETTINGS, BMEditMesh::selectmode, ToolSettings::selectmode, Scene::toolsettings, and WM_event_add_notifier().
Referenced by edbm_region_to_loop_exec(), and undo_editmode_step().
void EDBM_stats_update (BMEditMesh * em)
Definition at line 89 of file editmesh_utils.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, i, NULL, BMesh::totedgesel, BMesh::totfacesel, and BMesh::totvertsel.
void EDBM_update_generic (bContext * C, BMEditMesh * em, const short do_tessface)
Definition at line 1231 of file editmesh_utils.c.
References BMEdit_RecalcTessellation(), DAG_id_tag_update(), Object::data, NC_GEOM, ND_DATA, BMEditMesh::ob, OB_RECALC_DATA, and WM_event_add_notifier().
Referenced by edbm_add_edge_face_exec(), edbm_beautify_fill_exec(), edbm_bevel_exec(), edbm_blend_from_shape_exec(), edbm_bridge_edge_loops_exec(), edbm_collapse_edge_exec(), edbm_collapse_edge_loop_exec(), edbm_delete_exec(), edbm_dissolve_exec(), edbm_dissolve_limited_exec(), edbm_do_smooth_vertex_exec(), edbm_dupli_extrude_cursor_invoke(), edbm_duplicate_exec(), edbm_edge_rotate_selected_exec(), edbm_edge_split_exec(), edbm_extrude_region_exec(), edbm_extrude_repeat_exec(), edbm_faces_shade_flat_exec(), edbm_faces_shade_smooth_exec(), edbm_fill_exec(), edbm_flip_normals_exec(), edbm_hide_exec(), edbm_inset_exec(), edbm_knife_cut_exec(), edbm_mark_seam(), edbm_mark_sharp(), edbm_merge_exec(), edbm_noise_exec(), edbm_normals_make_consistent_exec(), edbm_quads_convert_to_tris_exec(), edbm_remove_doubles_exec(), edbm_reveal_exec(), edbm_reverse_colors_exec(), edbm_reverse_uvs_exec(), edbm_rip_invoke(), edbm_rotate_colors_exec(), edbm_rotate_uvs_exec(), edbm_screw_exec(), edbm_select_nth_exec(), edbm_select_vertex_path_exec(), edbm_separate_exec(), edbm_shape_propagate_to_all_exec(), edbm_solidify_exec(), edbm_spin_exec(), edbm_split_exec(), edbm_subdivide_exec(), edbm_tris_convert_to_quads_exec(), edbm_vert_connect(), edbm_vertex_slide_exec(), knifetool_finish(), make_prim_finish(), mouse_mesh_shortest_path(), similar_edge_select_exec(), similar_face_select_exec(), similar_vert_select_exec(), and vtx_slide_confirm().
UvElementMap* EDBM_uv_element_map_create (BMEditMesh * em, int selected, int do_islands) [read]
Definition at line 710 of file editmesh_utils.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_index_get, BM_ELEM_SELECT, BM_FACE, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_ELEM_INDEX, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_index_ensure(), BM_VERT, BM_VERTS_OF_MESH, UvElementMap::buf, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, EDBM_uv_element_map_free(), fabsf, UvElement::face, BMLoop::head, i, INVALID_ISLAND, UvElement::island, UvElementMap::islandIndices, UvElement::l, BMesh::ldata, BMFace::len, MEM_callocN(), MEM_freeN(), MEM_mallocN(), UvElement::next, next, NULL, UvElement::separate, stack, STD_UV_CONNECT_LIMIT, sub_v2_v2v2(), UvElement::tfindex, UvElementMap::totalIslands, UvElementMap::totalUVs, BMesh::totface, BMesh::totvert, MLoopUV::uv, BMLoop::v, and UvElementMap::vert.
Referenced by stitch_init(), and uv_sculpt_stroke_init().
void EDBM_uv_element_map_free (UvElementMap * element_map)
Definition at line 938 of file editmesh_utils.c.
References UvElementMap::buf, UvElementMap::islandIndices, MEM_freeN(), and UvElementMap::vert.
Referenced by EDBM_uv_element_map_create(), stitch_state_delete(), and uv_sculpt_stroke_exit().
UvMapVert* EDBM_uv_vert_map_at_index (UvVertMap * vmap, unsigned int v) [read]
Definition at line 701 of file editmesh_utils.c.
References UvVertMap::vert.
Referenced by select_edgeloop_uv_vertex_map_get(), select_linked(), and uv_faces_do_sticky().
UvVertMap* EDBM_uv_vert_map_create (BMEditMesh * em, int selected, int do_face_idx_array, float * limit) [read]
Definition at line 570 of file editmesh_utils.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_index_get, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_iter_at_index(), BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_index_ensure(), BM_VERT, BM_VERTS_OF_MESH, UvVertMap::buf, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, EDBM_face_at_index(), EDBM_index_arrays_free(), EDBM_index_arrays_init(), UvMapVert::f, fabs(), free_uv_vert_map(), BMLoop::head, i, BMesh::ldata, BMFace::len, MEM_callocN(), UvMapVert::next, next, NULL, UvMapVert::separate, sub_v2_v2v2(), UvMapVert::tfindex, BMesh::totvert, MLoopUV::uv, BMLoop::v, and UvVertMap::vert.
Referenced by select_edgeloop(), select_linked(), and uv_faces_do_sticky().
void EDBM_uv_vert_map_free (UvVertMap * vmap)
Definition at line 929 of file editmesh_utils.c.
References UvVertMap::buf, MEM_freeN(), and UvVertMap::vert.
Referenced by select_edgeloop(), select_linked(), and uv_faces_do_sticky().
BMVert* EDBM_vert_at_index (BMEditMesh * tm, int index) [read]
Definition at line 394 of file editmesh_utils.c.
References BMEditMesh::bm, NULL, BMesh::totvert, and BMEditMesh::vert_index.
Referenced by bbs_mesh_verts__mapFunc(), createRepresentation(), draw_dm_bweights__mapFunc(), draw_dm_vert_normals__mapFunc(), draw_dm_verts__mapFunc(), ED_mesh_mirrtopo_init(), edgetag_add_adjacent(), mesh_foreachScreenVert__mapFunc(), set_mapped_co(), and snapDerivedMesh().
int EDBM_vert_color_check (BMEditMesh * em)
Definition at line 976 of file editmesh_utils.c.
References BMEditMesh::bm, CD_MLOOPCOL, CustomData_has_layer(), BMesh::ldata, and BMesh::totface.
void EDBM_verts_mirror_apply (BMEditMesh * em, const int sel_from, const int sel_to)
Definition at line 1131 of file editmesh_utils.c.
References BLI_assert, BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, BMVert::co, copy_v3_v3(), EDBM_verts_mirror_get(), NULL, and BMEditMesh::vert_index.
Referenced by edbm_do_smooth_vertex_exec().
void EDBM_verts_mirror_cache_begin (BMEditMesh * em, const short use_select)
Definition at line 1012 of file editmesh_utils.c.
References BMEditMesh::bm, BM_CD_LAYER_ID, BM_data_layer_add_named(), BM_elem_flag_test, BM_elem_index_get, BM_ELEM_SELECT, BM_ITER_MESH, BM_mesh_elem_index_ensure(), BM_SEARCH_MAXDIST_MIRR, BM_VERT, BM_VERTS_OF_MESH, BMBVH_FindClosestVert(), BMBVH_FreeBVH(), BMBVH_NewBVH(), cache_mirr_intptr_as_bmvert(), CD_FLAG_TEMPORARY, CD_PROP_INT, BMVert::co, co, CustomData_bmesh_get_layer_n(), CustomData_get_layer_named(), CustomData_get_named_layer_index(), BMHeader::data, ED_mesh_mirrtopo_free(), ED_mesh_mirrtopo_init(), EDBM_index_arrays_init(), Mesh::editflag, CustomDataLayer::flag, BMVert::head, MirrTopoStore_t::index_lookup, CustomData::layers, BMEditMesh::me, ME_EDIT_MIRROR_TOPO, mesh_topo_store, BMEditMesh::mirr_free_arrays, BMEditMesh::mirror_cdlayer, NULL, TRUE, BMesh::vdata, and BMEditMesh::vert_index.
Referenced by createTransEditVerts(), ED_vgroup_mirror(), edbm_do_smooth_vertex_exec(), and EDBM_select_mirrored().
void EDBM_verts_mirror_cache_clear (BMEditMesh * em, BMVert * v)
Definition at line 1110 of file editmesh_utils.c.
References BLI_assert, BMEditMesh::bm, CustomData_bmesh_get_layer_n(), BMHeader::data, BMVert::head, BMEditMesh::mirror_cdlayer, and BMesh::vdata.
Referenced by ED_vgroup_mirror().
void EDBM_verts_mirror_cache_end (BMEditMesh * em)
Definition at line 1121 of file editmesh_utils.c.
References MEM_freeN(), BMEditMesh::mirr_free_arrays, BMEditMesh::mirror_cdlayer, NULL, and BMEditMesh::vert_index.
Referenced by createTransEditVerts(), ED_vgroup_mirror(), edbm_do_smooth_vertex_exec(), and EDBM_select_mirrored().
BMVert* EDBM_verts_mirror_get (BMEditMesh * em, BMVert * v) [read]
Definition at line 1091 of file editmesh_utils.c.
References BLI_assert, BMEditMesh::bm, CustomData_bmesh_get_layer_n(), BMHeader::data, BMVert::head, BMEditMesh::mirror_cdlayer, NULL, BMesh::vdata, and BMEditMesh::vert_index.
Referenced by createTransEditVerts(), ED_vgroup_mirror(), EDBM_select_mirrored(), and EDBM_verts_mirror_apply().
static void* editbtMesh_to_undoMesh (void * emv, void * obdata) [static]
Definition at line 498 of file editmesh_utils.c.
References BMEditMesh::bm, BM_mesh_bm_to_me(), copy_key_nolib(), FALSE, Mesh::key, UndoMesh::me, MEM_callocN(), NULL, BMEditMesh::selectmode, and UndoMesh::selectmode.
Referenced by undo_push_mesh().
static void free_undo (void * me_v) [static]
Definition at line 544 of file editmesh_utils.c.
References FALSE, free_key(), free_mesh(), Mesh::key, and MEM_freeN().
Referenced by undo_push_mesh().
static void* getEditMesh (bContext * C) [static]
Definition at line 482 of file editmesh_utils.c.
References CTX_data_edit_object(), Object::data, Mesh::edit_btmesh, NULL, OB_MESH, and Object::type.
Referenced by undo_push_mesh().
void undo_push_mesh (bContext * C, const char * name)
Definition at line 557 of file editmesh_utils.c.
References BMEdit_FromObject(), CTX_data_edit_object(), editbtMesh_to_undoMesh(), free_undo(), getEditMesh(), NULL, BMEditMesh::ob, undo_editmode_push(), and undoMesh_to_editbtMesh().
Referenced by ED_undo_push().
static void undoMesh_to_editbtMesh (void * umv, void * em_v, void * UNUSEDobdata) [static]
Definition at line 517 of file editmesh_utils.c.
References BMEditMesh::bm, bm_mesh_allocsize_default, BM_mesh_bm_from_me(), BM_mesh_create(), BM_mesh_normals_update(), BMEdit_Create(), EDBM_mesh_free(), FALSE, UndoMesh::me, MEM_freeN(), BMEditMesh::ob, BMEditMesh::selectmode, UndoMesh::selectmode, BMesh::shapenr, Object::shapenr, and TRUE.
Referenced by undo_push_mesh().