Blender: GlutMouseManager Class Reference
GlutMouseManager Class Reference
#include <GlutMouseManager.h>
Public Member Functions
void InstallHandler (GlutMouseHandler *)
void ReleaseHandler ()
~GlutMouseManager ()
void InstallHandler (GlutMouseHandler *)
void ReleaseHandler ()
~GlutMouseManager ()
Static Public Member Functions
static GlutMouseManager * Instance ()
static void ButtonUp (GHOST_IWindow *window, GHOST_TButtonMask button_mask, int x, int y)
static void ButtonDown (GHOST_IWindow *window, GHOST_TButtonMask button_mask, int x, int y)
static void Motion (GHOST_IWindow *window, int x, int y)
static GlutMouseManager * Instance ()
static void Mouse (int button, int state, int x, int y)
static void Motion (int x, int y)
Detailed Description
Definition at line 72 of file decimation/test/decimate_glut_test/intern/common/GlutMouseManager.h.
Constructor & Destructor Documentation
GlutMouseManager::~GlutMouseManager ()
Definition at line 111 of file decimation/test/decimate_glut_test/intern/common/GlutMouseManager.cpp.
GlutMouseManager::~GlutMouseManager ()
Member Function Documentation
void GlutMouseManager::ButtonDown (GHOST_IWindow * window, GHOST_TButtonMask button_mask, int x, int y) [static]
Definition at line 64 of file decimation/test/decimate_glut_test/intern/common/GlutMouseManager.cpp.
References GlutMouseHandler::ButtonDown(), Instance(), and NULL.
void GlutMouseManager::ButtonUp (GHOST_IWindow * window, GHOST_TButtonMask button_mask, int x, int y) [static]
Definition at line 49 of file decimation/test/decimate_glut_test/intern/common/GlutMouseManager.cpp.
References GlutMouseHandler::ButtonUp(), Instance(), and NULL.
void GlutMouseManager::InstallHandler (GlutMouseHandler * handler)
Definition at line 95 of file decimation/test/decimate_glut_test/intern/common/GlutMouseManager.cpp.
References MT_assert, and NULL.
Referenced by main().
void GlutMouseManager::InstallHandler (GlutMouseHandler *)
GlutMouseManager * GlutMouseManager::Instance () [static]
Definition at line 36 of file decimation/test/decimate_glut_test/intern/common/GlutMouseManager.cpp.
References NULL.
Referenced by ButtonDown(), ButtonUp(), main(), Motion(), and Mouse().
static GlutMouseManager* GlutMouseManager::Instance () [static]
void GlutMouseManager::Motion (GHOST_IWindow * window, int x, int y) [static]
Definition at line 81 of file decimation/test/decimate_glut_test/intern/common/GlutMouseManager.cpp.
References Instance(), GlutMouseHandler::Motion(), and NULL.
Referenced by main().
void GlutMouseManager::Motion (int x, int y) [static]
Definition at line 64 of file iksolver/test/ik_glut_test/common/GlutMouseManager.cpp.
References Instance(), GlutMouseHandler::Motion(), and NULL.
void GlutMouseManager::Mouse (int button, int state, int x, int y) [static]
Definition at line 49 of file iksolver/test/ik_glut_test/common/GlutMouseManager.cpp.
References Instance(), GlutMouseHandler::Mouse(), and NULL.
Referenced by main().
void GlutMouseManager::ReleaseHandler ()
void GlutMouseManager::ReleaseHandler ()
Definition at line 105 of file decimation/test/decimate_glut_test/intern/common/GlutMouseManager.cpp.
References NULL.
The documentation for this class was generated from the following files:
decimation/test/decimate_glut_test/intern/common/GlutMouseManager.h
iksolver/test/ik_glut_test/common/GlutMouseManager.h
decimation/test/decimate_glut_test/intern/common/GlutMouseManager.cpp
iksolver/test/ik_glut_test/common/GlutMouseManager.cpp