Blender: pipeline.c File Reference
pipeline.c File Reference
Rendering
#include <math.h>
#include <limits.h>
#include <string.h>
#include <stdlib.h>
#include <stddef.h>
#include "DNA_group_types.h"
#include "DNA_image_types.h"
#include "DNA_node_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_sequence_types.h"
#include "DNA_userdef_types.h"
#include "MEM_guardedalloc.h"
#include "BKE_animsys.h"
#include "BKE_camera.h"
#include "BKE_global.h"
#include "BKE_image.h"
#include "BKE_main.h"
#include "BKE_node.h"
#include "BKE_pointcache.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "BKE_sequencer.h"
#include "BKE_utildefines.h"
#include "BKE_writeavi.h"
#include "BLI_math.h"
#include "BLI_listbase.h"
#include "BLI_string.h"
#include "BLI_path_util.h"
#include "BLI_fileops.h"
#include "BLI_rand.h"
#include "BLI_callbacks.h"
#include "PIL_time.h"
#include "IMB_imbuf.h"
#include "IMB_imbuf_types.h"
#include "RE_engine.h"
#include "RE_pipeline.h"
#include "render_result.h"
#include "render_types.h"
#include "renderpipeline.h"
#include "renderdatabase.h"
#include "rendercore.h"
#include "initrender.h"
#include "shadbuf.h"
#include "pixelblending.h"
#include "zbuf.h"
Functions
static int do_write_image_or_movie (Render *re, Main *bmain, Scene *scene, bMovieHandle *mh, const char *name_override)
static int thread_break (void *UNUSED(arg))
static void result_nothing (void *UNUSED(arg), RenderResult *UNUSED(rr))
static void result_rcti_nothing (void *UNUSED(arg), RenderResult *UNUSED(rr), volatile struct rcti *UNUSED(rect))
static void stats_nothing (void *UNUSED(arg), RenderStats *UNUSED(rs))
static void float_nothing (void *UNUSED(arg), float UNUSED(val))
static int default_break (void *UNUSED(arg))
static void stats_background (void *UNUSED(arg), RenderStats *rs)
void RE_FreeRenderResult (RenderResult *res)
float * RE_RenderLayerGetPass (RenderLayer *rl, int passtype)
RenderLayer * RE_GetRenderLayer (RenderResult *rr, const char *name)
RenderResult * RE_MultilayerConvert (void *exrhandle, int rectx, int recty)
RenderLayer * render_get_active_layer (Render *re, RenderResult *rr)
static int render_scene_needs_vector (Render *re)
Render * RE_GetRender (const char *name)
RenderResult * RE_AcquireResultRead (Render *re)
RenderResult * RE_AcquireResultWrite (Render *re)
void RE_SwapResult (Render *re, RenderResult **rr)
void RE_ReleaseResult (Render *re)
Scene * RE_GetScene (Render *re)
void RE_AcquireResultImage (Render *re, RenderResult *rr)
void RE_ReleaseResultImage (Render *re)
void RE_ResultGet32 (Render *re, unsigned int *rect)
RenderStats * RE_GetStats (Render *re)
Render * RE_NewRender (const char *name)
void RE_InitRenderCB (Render *re)
void RE_FreeRender (Render *re)
void RE_FreeAllRender (void)
void RE_FreeAllRenderResults (void)
void RE_InitState (Render *re, Render *source, RenderData *rd, SceneRenderLayer *srl, int winx, int winy, rcti *disprect)
void RE_SetWindow (Render *re, rctf *viewplane, float clipsta, float clipend)
void RE_SetOrtho (Render *re, rctf *viewplane, float clipsta, float clipend)
void RE_SetView (Render *re, float mat[][4])
void RE_display_init_cb (Render *re, void *handle, void(*f)(void *handle, RenderResult *rr))
void RE_display_clear_cb (Render *re, void *handle, void(*f)(void *handle, RenderResult *rr))
void RE_display_draw_cb (Render *re, void *handle, void(*f)(void *handle, RenderResult *rr, volatile rcti *rect))
void RE_stats_draw_cb (Render *re, void *handle, void(*f)(void *handle, RenderStats *rs))
void RE_progress_cb (Render *re, void *handle, void(*f)(void *handle, float))
void RE_draw_lock_cb (Render *re, void *handle, void(*f)(void *handle, int i))
void RE_test_break_cb (Render *re, void *handle, int(*f)(void *handle))
static int render_display_draw_enabled (Render *re)
static void * do_part_thread (void *pa_v)
float panorama_pixel_rot (Render *re)
static RenderPart * find_next_pano_slice (Render *re, int *minx, rctf *viewplane)
static RenderPart * find_next_part (Render *re, int minx)
static void print_part_stats (Render *re, RenderPart *pa)
static void threaded_tile_processor (Render *re)
void RE_TileProcessor (Render *re)
static void do_render_3d (Render *re)
static void addblur_rect_key (RenderResult *rr, float *rectf, float *rectf1, float blurfac)
static void addblur_rect (RenderResult *rr, float *rectf, float *rectf1, float blurfac, int channels)
static void merge_renderresult_blur (RenderResult *rr, RenderResult *brr, float blurfac, int key_alpha)
static void do_render_blur_3d (Render *re)
static void interleave_rect (RenderResult *rr, float *rectf, float *rectf1, float *rectf2, int channels)
static void merge_renderresult_fields (RenderResult *rr, RenderResult *rr1, RenderResult *rr2)
static void do_render_fields_3d (Render *re)
static void do_render_fields_blur_3d (Render *re)
static void render_scene (Render *re, Scene *sce, int cfra)
static int composite_needs_render (Scene *sce, int this_scene)
static void tag_scenes_for_render (Render *re)
static void ntree_render_scenes (Render *re)
static void render_composit_stats (void *UNUSED(arg), char *str)
static void do_merge_fullsample (Render *re, bNodeTree *ntree)
void RE_MergeFullSample (Render *re, Main *bmain, Scene *sce, bNodeTree *ntree)
static void do_render_composite_fields_blur_3d (Render *re)
static void renderresult_stampinfo (Render *re)
int RE_seq_render_active (Scene *scene, RenderData *rd)
static void do_render_seq (Render *re)
static void do_render_all_options (Render *re)
static int check_valid_camera (Scene *scene, Object *camera_override)
int RE_is_rendering_allowed (Scene *scene, Object *camera_override, ReportList *reports)
static void validate_render_settings (Render *re)
static void update_physics_cache (Render *re, Scene *scene, int UNUSED(anim_init))
static int render_initialize_from_main (Render *re, Main *bmain, Scene *scene, SceneRenderLayer *srl, Object *camera_override, unsigned int lay, int anim, int anim_init)
void RE_SetReports (Render *re, ReportList *reports)
void RE_BlenderFrame (Render *re, Main *bmain, Scene *scene, SceneRenderLayer *srl, Object *camera_override, unsigned int lay, int frame, const short write_still)
void RE_BlenderAnim (Render *re, Main *bmain, Scene *scene, Object *camera_override, unsigned int lay, int sfra, int efra, int tfra)
void RE_PreviewRender (Render *re, Main *bmain, Scene *sce)
int RE_ReadRenderResult (Scene *scene, Scene *scenode)
void RE_set_max_threads (int threads)
void RE_init_threadcount (Render *re)
void RE_layer_load_from_file (RenderLayer *layer, ReportList *reports, const char *filename, int x, int y)
void RE_result_load_from_file (RenderResult *result, ReportList *reports, const char *filename)
int RE_WriteEnvmapResult (struct ReportList *reports, Scene *scene, EnvMap *env, const char *relpath, const char imtype, float layout[12])
Variables
struct {
ListBase renderlist
int threads
} RenderGlobal
Render R
static volatile int g_break = 0
const float default_envmap_layout [] = { 0,0, 1,0, 2,0, 0,1, 1,1, 2,1 }
Detailed Description
Definition in file pipeline.c.
Function Documentation
static void addblur_rect (RenderResult * rr, float * rectf, float * rectf1, float blurfac, int channels) [static]
Definition at line 988 of file pipeline.c.
References len(), RenderResult::rectx, and RenderResult::recty.
Referenced by merge_renderresult_blur().
static void addblur_rect_key (RenderResult * rr, float * rectf, float * rectf1, float blurfac) [static]
Definition at line 952 of file pipeline.c.
References len(), RenderResult::rectx, and RenderResult::recty.
Referenced by merge_renderresult_blur().
static int check_valid_camera (Scene * scene, Object * camera_override) [static]
Definition at line 1747 of file pipeline.c.
References Scene::camera, CMP_NODE_R_LAYERS, Scene::ed, ListBase::first, bNode::id, if(), bNode::next, Sequence::next, bNodeTree::nodes, Scene::nodetree, NULL, Scene::r, R_DOCOMP, R_DOSEQ, RenderData::scemode, Sequence::scene, Sequence::scene_camera, scene_find_camera(), SEQ_SCENE, Editing::seqbase, bNode::type, Sequence::type, and Scene::use_nodes.
Referenced by RE_is_rendering_allowed().
static int composite_needs_render (Scene * sce, int this_scene) [static]
Definition at line 1297 of file pipeline.c.
References CMP_NODE_R_LAYERS, ListBase::first, Scene::id, bNode::id, bNode::next, bNodeTree::nodes, Scene::nodetree, NULL, Scene::r, R_DOCOMP, RenderData::scemode, bNode::type, and Scene::use_nodes.
Referenced by do_render_composite_fields_blur_3d(), RE_is_rendering_allowed(), and tag_scenes_for_render().
static int default_break (void * UNUSEDarg) [static]
Definition at line 143 of file pipeline.c.
References G.
Referenced by RE_InitRenderCB().
static void do_merge_fullsample (Render * re, bNodeTree * ntree) [static]
Definition at line 1382 of file pipeline.c.
References add_filt_fmask_coord(), BLI_rw_mutex_lock(), BLI_rw_mutex_unlock(), RenderStats::curfsa, Render::ddh, Render::display_draw, ID::flag, G, Render::i, Scene::id, LIB_DOIT, mask_array(), MEM_freeN(), MEM_mapallocN(), Render::next, ntreeCompositExecTree(), ntreeCompositTagAnimated(), ntreeCompositTagRender(), NULL, Render::osa, RenderData::osa, Render::prh, bNodeTree::prh, Render::progress, bNodeTree::progress, Render::r, R_FULL_SAMPLE, RE_AcquireResultImage(), RE_ReleaseResultImage(), RenderResult::rectf, Render::rectx, Render::recty, render_composit_stats(), render_get_active_layer(), render_result_exr_file_read(), RenderGlobal, RenderResult::renlay, Render::result, Render::resultmutex, RenderData::scemode, Render::scene, Render::sdh, bNodeTree::sdh, bNodeTree::stats_draw, tag_scenes_for_render(), Render::tbh, bNodeTree::tbh, Render::test_break, bNodeTree::test_break, and THREAD_LOCK_WRITE.
Referenced by do_render_composite_fields_blur_3d(), and RE_MergeFullSample().
static void* do_part_thread (void * pa_v) [static]
Definition at line 630 of file pipeline.c.
References RenderPart::crop, RenderPart::disprect, RenderResult::exrhandle, RenderPart::fullresult, NULL, Render::osa, Render::r, R_FULL_SAMPLE, R_PREVIEWBUTS, RenderPart::ready, render_display_draw_enabled(), render_result_exr_file_merge(), render_result_merge(), render_result_new(), render_result_new_full_sample(), Render::result, RenderPart::result, RR_USE_MEM, RenderData::scemode, Render::sss_points, Render::tbh, Render::test_break, zbufshade_sss_tile(), zbufshade_tile(), and zbufshadeDA_tile().
Referenced by threaded_tile_processor().
static void do_render_3d (Render * re) [static]
Definition at line 913 of file pipeline.c.
References add_halo_flare(), Render::dlh, Render::draw_lock, Render::field_offs, Render::flag, Render::lay, Render::main, Render::mblur_offs, Scene::r, R_HALO, RE_Database_Free(), RE_Database_FromScene(), RE_Database_FromScene_Vectors(), RE_engine_render(), render_scene_needs_vector(), Render::scene, RenderData::subframe, Render::tbh, Render::test_break, and threaded_tile_processor().
Referenced by do_render_blur_3d(), do_render_fields_3d(), do_render_fields_blur_3d(), and RE_PreviewRender().
static void do_render_all_options (Render * re) [static]
Definition at line 1712 of file pipeline.c.
References BKE_image_all_free_anim_ibufs(), RenderData::cfra, Render::ddh, Render::display_draw, do_render_composite_fields_blur_3d(), do_render_seq(), Render::i, RenderStats::lastframetime, NULL, PIL_check_seconds_timer(), Render::r, R_STAMP_ALL, R_STAMP_DRAW, RE_engine_render(), RE_seq_render_active(), renderresult_stampinfo(), Render::result, Render::scene, scene_camera_switch_update(), Render::sdh, RenderData::stamp, RenderStats::starttime, Render::stats_draw, Render::tbh, and Render::test_break.
Referenced by RE_BlenderAnim(), and RE_BlenderFrame().
static void do_render_blur_3d (Render * re) [static]
Definition at line 1037 of file pipeline.c.
References RenderData::alphamode, BLI_rw_mutex_lock(), BLI_rw_mutex_unlock(), RenderData::blurfac, RenderStats::curblur, Render::ddh, Render::display_draw, Render::disprect, do_render_3d(), Render::i, Render::mblur_offs, RenderData::mblur_samples, merge_renderresult_blur(), NULL, Render::r, R_ALPHAKEY, render_get_active_layer(), render_result_free(), render_result_new(), RenderResult::renlay, Render::result, Render::resultmutex, RR_USE_MEM, Render::tbh, Render::test_break, and THREAD_LOCK_WRITE.
Referenced by do_render_fields_3d(), and do_render_fields_blur_3d().
static void do_render_composite_fields_blur_3d (Render * re) [static]
Definition at line 1533 of file pipeline.c.
References BLI_rw_mutex_lock(), BLI_rw_mutex_unlock(), BLI_srandom(), RenderData::cfra, composite_needs_render(), Render::ddh, Render::display_draw, Render::disprect, do_merge_fullsample(), do_render_fields_blur_3d(), G, Render::lay, Render::main, Scene::nodetree, ntree_render_scenes(), ntreeCompositExecTree(), ntreeCompositTagAnimated(), ntreeCompositTagRender(), ntreeFreeCache(), NULL, Render::prh, bNodeTree::prh, Render::progress, bNodeTree::progress, Render::r, R_DOCOMP, R_FULL_SAMPLE, R_SINGLE_LAYER, render_composit_stats(), render_get_active_layer(), render_result_free(), render_result_new(), render_result_single_layer_end(), RenderResult::renlay, Render::result, Render::resultmutex, RR_USE_MEM, RenderData::scemode, Render::scene, scene_update_for_newframe(), Render::sdh, bNodeTree::sdh, Render::stats_draw, bNodeTree::stats_draw, bNodeTree::tbh, Render::tbh, bNodeTree::test_break, Render::test_break, THREAD_LOCK_WRITE, and Scene::use_nodes.
Referenced by do_render_all_options().
static void do_render_fields_3d (Render * re) [static]
Definition at line 1116 of file pipeline.c.
References BLI_rw_mutex_lock(), BLI_rw_mutex_unlock(), RenderStats::curfield, Render::ddh, Render::display_draw, Render::disprect, do_render_3d(), do_render_blur_3d(), Render::field_offs, Render::flag, Render::i, merge_renderresult_fields(), RenderData::mode, NULL, Render::r, R_FIELDSTILL, R_FULL_SAMPLE, R_MBLUR, R_ODDFIELD, R_SEC_FIELD, RE_GetCamera(), RE_SetCamera(), Render::recty, render_get_active_layer(), render_result_free(), render_result_new(), RenderResult::renlay, Render::result, Render::resultmutex, RR_USE_MEM, RenderData::scemode, Render::tbh, Render::test_break, THREAD_LOCK_WRITE, Render::winy, rcti::ymax, and rcti::ymin.
Referenced by do_render_fields_blur_3d().
static void do_render_fields_blur_3d (Render * re) [static]
Definition at line 1193 of file pipeline.c.
References BLI_rw_mutex_lock(), BLI_rw_mutex_unlock(), Render::ddh, Render::dih, Render::display_draw, Render::display_init, Render::disprect, do_render_3d(), do_render_blur_3d(), do_render_fields_3d(), G, RenderData::mode, NULL, Render::r, R_BORDER, R_CROP, R_FIELDS, R_FULL_SAMPLE, R_MBLUR, RE_GetCamera(), RE_SetCamera(), Render::rectx, Render::recty, render_get_active_layer(), render_result_free(), render_result_merge(), render_result_new(), RenderResult::renlay, Render::result, Render::resultmutex, RR_USE_MEM, RenderData::scemode, THREAD_LOCK_WRITE, RenderResult::tilerect, Render::winx, Render::winy, rcti::xmax, rcti::xmin, RenderResult::xof, rcti::ymax, rcti::ymin, and RenderResult::yof.
Referenced by do_render_composite_fields_blur_3d(), and render_scene().
static void do_render_seq (Render * re) [static]
Definition at line 1643 of file pipeline.c.
References BKE_animsys_evaluate_all_animation(), BLI_rw_mutex_lock(), BLI_rw_mutex_unlock(), RenderStats::cfra, RenderData::cfra, Scene::ed, RenderData::efra, free_imbuf_seq(), give_ibuf_seq(), Render::i, IMB_freeImBuf(), Render::main, RenderData::mode, Render::prh, Render::progress, Render::r, R_BORDER, R_CROP, R_DOSEQ, RenderResult::rectx, RenderResult::recty, render_result_rect_fill_zero(), render_result_rect_from_ibuf(), Render::result, Render::resultmutex, RenderData::scemode, Render::scene, seq_new_render_data(), Editing::seqbase, RenderData::sfra, THREAD_LOCK_WRITE, TRUE, Render::winx, and Render::winy.
Referenced by do_render_all_options().
static int do_write_image_or_movie (Render * re, Main * bmain, Scene * scene, bMovieHandle * mh, const char * name_override) [static]
Definition at line 2049 of file pipeline.c.
References bMovieHandle::append_movie, BKE_add_image_extension(), BKE_imtype_is_movie(), BKE_makepicstring(), BKE_write_ibuf_stamp(), BLI_CB_EVT_RENDER_STATS, BLI_exec_cb(), BLI_strncpy(), BLI_testextensie(), BLI_timestr(), RenderData::cfra, ImageFormatData::exr_codec, FILE_MAX, ImageFormatData::flag, G, Render::i, if(), RenderData::im_format, IMB_freeImBuf(), ImageFormatData::imtype, RenderStats::lastframetime, MEM_freeN(), MEM_mapallocN(), Main::name, ImBuf::name, NULL, RenderData::pic, ImBuf::planes, Render::r, Scene::r, R_EXTENSION, R_IMF_FLAG_PREVIEW_JPG, R_IMF_IMTYPE_JPEG90, R_IMF_IMTYPE_MULTILAYER, R_IMF_IMTYPE_OPENEXR, RE_AcquireResultImage(), RE_GetCamera(), RE_ReleaseResultImage(), RE_ResultGet32(), RE_WriteRenderResult(), RenderResult::rect32, RenderResult::rectx, RenderResult::recty, render_result_rect_to_ibuf(), Render::reports, Render::result, RenderData::scemode, RenderData::sfra, strlen(), and TRUE.
Referenced by RE_BlenderAnim(), and RE_BlenderFrame().
static RenderPart* find_next_pano_slice (Render * re, int * minx, rctf * viewplane) [static]
Definition at line 692 of file pipeline.c.
References Render::clipend, Render::clipsta, copy_m4_m4(), cos(), RenderPart::disprect, ListBase::first, RenderPart::next, RenderPart::nr, NULL, Render::panoco, Render::panodxp, Render::panodxv, panorama_pixel_rot(), Render::panosi, Render::parts, project_renderdata(), projectverto(), RE_SetWindow(), RenderPart::ready, sin(), Render::viewplane, Render::winmat, Render::winx, rctf::xmax, rcti::xmax, rctf::xmin, and rcti::xmin.
Referenced by threaded_tile_processor().
static RenderPart* find_next_part (Render * re, int minx) [static]
Definition at line 728 of file pipeline.c.
References RenderPart::disprect, ListBase::first, RenderData::mode, RenderPart::next, RenderPart::nr, NULL, Render::parts, Render::r, R_PANORAMA, RenderPart::ready, sqrt(), Render::winx, Render::winy, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by threaded_tile_processor().
static void float_nothing (void * UNUSEDarg, float UNUSEDval) [static]
Definition at line 142 of file pipeline.c.
Referenced by RE_InitRenderCB().
static void interleave_rect (RenderResult * rr, float * rectf, float * rectf1, float * rectf2, int channels) [static]
Definition at line 1076 of file pipeline.c.
References len(), RenderResult::rectx, and RenderResult::recty.
Referenced by merge_renderresult_fields().
static void merge_renderresult_blur (RenderResult * rr, RenderResult * brr, float blurfac, int key_alpha) [static]
Definition at line 1012 of file pipeline.c.
References addblur_rect(), addblur_rect_key(), RenderPass::channels, ListBase::first, RenderResult::layers, RenderPass::next, RenderLayer::next, RenderLayer::passes, RenderPass::rect, and RenderLayer::rectf.
Referenced by do_render_blur_3d().
static void merge_renderresult_fields (RenderResult * rr, RenderResult * rr1, RenderResult * rr2) [static]
Definition at line 1092 of file pipeline.c.
References RenderPass::channels, ListBase::first, interleave_rect(), RenderResult::layers, RenderPass::next, RenderLayer::next, RenderLayer::passes, RenderPass::rect, and RenderLayer::rectf.
Referenced by do_render_fields_3d().
static void ntree_render_scenes (Render * re) [static]
Definition at line 1339 of file pipeline.c.
References RenderData::cfra, CMP_NODE_R_LAYERS, ListBase::first, ID::flag, bNode::id, LIB_DOIT, Render::main, bNode::next, bNodeTree::nodes, Scene::nodetree, nodeUpdate(), NULL, Scene::r, render_scene(), Render::scene, set_scene_bg(), tag_scenes_for_render(), and bNode::type.
Referenced by do_render_composite_fields_blur_3d().
float panorama_pixel_rot (Render * re)
Definition at line 668 of file pipeline.c.
References KDL::atan(), Render::clipsta, Render::disprect, Render::partx, Render::viewplane, Render::winx, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, and Render::xparts.
Referenced by find_next_pano_slice(), and initparts().
static void print_part_stats (Render * re, RenderPart * pa) [static]
Definition at line 770 of file pipeline.c.
References BLI_snprintf(), Render::i, Scene::id, RenderStats::infostr, ID::name, RenderPart::nr, NULL, Render::scene, Render::sdh, Render::stats_draw, str, and RenderStats::totpart.
Referenced by threaded_tile_processor().
void RE_AcquireResultImage (Render * re, RenderResult * rr)
Definition at line 295 of file pipeline.c.
References BLI_rw_mutex_lock(), RenderResult::have_combined, RenderResult::layers, NULL, RE_RenderLayerGetPass(), RenderResult::rect32, RenderLayer::rectf, RenderResult::rectf, RenderResult::rectx, RenderResult::recty, RenderResult::rectz, render_get_active_layer(), Render::result, Render::resultmutex, SCE_PASS_Z, and THREAD_LOCK_READ.
Referenced by do_merge_fullsample(), do_write_image_or_movie(), ed_preview_draw_rect(), image_get_render_result(), RE_ResultGet32(), renderresult_stampinfo(), and seq_render_scene_strip().
RenderResult* RE_AcquireResultRead (Render * re) [read]
Definition at line 251 of file pipeline.c.
References BLI_rw_mutex_lock(), NULL, Render::result, Render::resultmutex, and THREAD_LOCK_READ.
Referenced by BKE_image_acquire_renderresult(), image_renderinfo_cb(), node_composit_exec_rlayers(), screen_opengl_render_apply(), uiTemplateImage(), and uiTemplateImageLayers().
RenderResult* RE_AcquireResultWrite (Render * re) [read]
Definition at line 261 of file pipeline.c.
References BLI_rw_mutex_lock(), NULL, Render::result, Render::resultmutex, and THREAD_LOCK_WRITE.
Referenced by node_composit_exec_composite(), and screen_opengl_render_init().
void RE_BlenderAnim (Render * re, Main * bmain, Scene * scene, Object * camera_override, unsigned int lay, int sfra, int efra, int tfra)
Definition at line 2130 of file pipeline.c.
References BKE_get_movie_handle(), BKE_imtype_is_movie(), BKE_makepicstring(), BKE_report(), BLI_CB_EVT_RENDER_CANCEL, BLI_CB_EVT_RENDER_COMPLETE, BLI_CB_EVT_RENDER_POST, BLI_CB_EVT_RENDER_PRE, BLI_delete(), BLI_exec_cb(), BLI_exists(), BLI_file_size(), BLI_file_touch(), BLI_make_existing_file(), RenderData::cfra, do_render_all_options(), do_write_image_or_movie(), bMovieHandle::end_movie, FILE_MAX, Render::flag, G, bMovieHandle::get_next_frame, if(), RenderData::im_format, ImageFormatData::imtype, Render::lay, Render::main, RenderData::mode, Main::name, ImBuf::name, NULL, RenderData::pic, Render::r, Scene::r, R_ANIMATION, R_EXTENSION, R_NO_OVERWRITE, R_TOUCH, Render::rectx, Render::recty, render_initialize_from_main(), Render::reports, RPT_INFO, RenderData::scemode, scene_update_for_newframe(), RenderData::sfra, bMovieHandle::start_movie, Render::tbh, Render::test_break, and TRUE.
Referenced by render_animation(), render_frame(), render_startjob(), and screen_render_exec().
void RE_BlenderFrame (Render * re, Main * bmain, Scene * scene, SceneRenderLayer * srl, Object * camera_override, unsigned int lay, int frame, const short write_still)
Definition at line 2012 of file pipeline.c.
References BKE_imtype_is_movie(), BKE_makepicstring(), BLI_CB_EVT_RENDER_CANCEL, BLI_CB_EVT_RENDER_COMPLETE, BLI_CB_EVT_RENDER_POST, BLI_CB_EVT_RENDER_PRE, BLI_exec_cb(), RenderData::cfra, do_render_all_options(), do_write_image_or_movie(), FALSE, FILE_MAX, G, Render::main, MEM_reset_peak_memory(), Main::name, ImBuf::name, NULL, Scene::r, R_EXTENSION, and render_initialize_from_main().
Referenced by render_startjob(), screen_render_exec(), and seq_render_scene_strip().
void RE_display_clear_cb (Render * re, void * handle, void(*)(void *handle, RenderResult *rr) f)
Definition at line 573 of file pipeline.c.
References Render::dch, and Render::display_clear.
void RE_display_draw_cb (Render * re, void * handle, void(*)(void *handle, RenderResult *rr, volatile rcti *rect) f)
Definition at line 578 of file pipeline.c.
References Render::ddh, and Render::display_draw.
void RE_display_init_cb (Render * re, void * handle, void(*)(void *handle, RenderResult *rr) f)
Definition at line 568 of file pipeline.c.
References Render::dih, and Render::display_init.
void RE_draw_lock_cb (Render * re, void * handle, void(*)(void *handle, int i) f)
Definition at line 594 of file pipeline.c.
References Render::draw_lock, and Render::tbh.
void RE_FreeAllRender (void)
Definition at line 406 of file pipeline.c.
References RE_FreeRender(), and RenderGlobal.
Referenced by WM_exit_ext().
void RE_FreeAllRenderResults (void)
Definition at line 414 of file pipeline.c.
References Render::next, NULL, Render::pushedresult, render_result_free(), RenderGlobal, and Render::result.
Referenced by setup_app_data().
void RE_FreeRender (Render * re)
Definition at line 391 of file pipeline.c.
References BLI_remlink(), BLI_rw_mutex_end(), free_renderdata_tables(), free_sample_tables(), MEM_freeN(), Render::pushedresult, render_result_free(), RenderGlobal, Render::result, and Render::resultmutex.
Referenced by envmap_free_render_copy(), and RE_FreeAllRender().
void RE_FreeRenderResult (RenderResult * res)
Definition at line 182 of file pipeline.c.
References render_result_free().
Referenced by BKE_image_backup_render(), free_image(), image_free_buffers(), image_load_sequence_multilayer(), render_result_exr_file_read(), render_result_single_layer_begin(), render_result_single_layer_end(), and sss_create_tree_mat().
Render* RE_GetRender (const char * name) [read]
Definition at line 238 of file pipeline.c.
References Render::name, Render::next, RE_MAXNAME, and RenderGlobal.
Referenced by BKE_image_acquire_renderresult(), BKE_image_backup_render(), BKE_image_release_renderresult(), ed_preview_draw_rect(), image_get_render_result(), node_composit_exec_composite(), node_composit_exec_rlayers(), RE_NewRender(), RE_ReadRenderResult(), seq_render_scene_strip(), shader_preview_render(), stampdata(), uiTemplateImage(), and uiTemplateImageLayers().
RenderLayer* RE_GetRenderLayer (RenderResult * rr, const char * name) [read]
Definition at line 197 of file pipeline.c.
References ListBase::first, RenderResult::layers, RenderLayer::name, RenderLayer::next, NULL, and RE_MAXNAME.
Referenced by node_composit_exec_rlayers(), and render_result_single_layer_end().
Scene* RE_GetScene (Render * re) [read]
Definition at line 287 of file pipeline.c.
References NULL, and Render::scene.
RenderStats* RE_GetStats (Render * re) [read]
Definition at line 344 of file pipeline.c.
References Render::i.
Referenced by stampdata().
void RE_init_threadcount (Render * re)
Definition at line 2346 of file pipeline.c.
References BLENDER_MAX_THREADS, BLI_system_thread_count(), MIN2, RenderData::mode, Render::r, R_FIXED_THREADS, RenderGlobal, and RenderData::threads.
Referenced by RE_Database_Baking(), and RE_InitState().
void RE_InitRenderCB (Render * re)
Definition at line 374 of file pipeline.c.
References Render::dch, Render::ddh, default_break(), Render::dih, Render::display_clear, Render::display_draw, Render::display_init, float_nothing(), G, NULL, Render::prh, Render::progress, result_nothing(), result_rcti_nothing(), Render::sdh, stats_background(), Render::stats_draw, stats_nothing(), Render::tbh, and Render::test_break.
Referenced by RE_NewRender(), and render_endjob().
void RE_InitState (Render * re, Render * source, RenderData * rd, SceneRenderLayer * srl, int winx, int winy, rcti * disprect)
Definition at line 432 of file pipeline.c.
References RenderData::actlay, BKE_imtype_is_movie(), BKE_report(), BLI_findindex(), BLI_rw_mutex_lock(), BLI_rw_mutex_unlock(), Render::clipcrop, Render::disprect, Render::field_offs, Render::i, RenderData::im_format, ImageFormatData::imtype, RenderData::layers, make_sample_tables(), Render::mblur_offs, MEM_callocN(), RenderData::mode, NULL, Render::ok, Render::osa, RenderData::osa, PIL_check_seconds_timer(), Render::r, R_BORDER, R_EXR_TILE_FILE, R_FULL_SAMPLE, R_OSA, R_PREVIEWBUTS, R_SINGLE_LAYER, RE_init_threadcount(), RenderResult::rectx, Render::rectx, RenderResult::recty, Render::recty, render_result_free(), Render::reports, Render::result, Render::resultmutex, RPT_ERROR, RenderData::scemode, RenderStats::starttime, THREAD_LOCK_WRITE, TRUE, Render::winx, Render::winy, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by envmap_render_copy(), RE_make_sticky(), RE_PreviewRender(), RE_ReadRenderResult(), render_initialize_from_main(), render_scene(), and screen_opengl_render_init().
int RE_is_rendering_allowed (Scene * scene, Object * camera_override, ReportList * reports)
Definition at line 1806 of file pipeline.c.
References RenderData::actlay, BKE_report(), BLI_file_is_writable(), BLI_findlink(), RenderData::border, Scene::camera, check_valid_camera(), CMP_NODE_COMPOSITE, composite_needs_render(), FILE_MAX, ListBase::first, RenderData::layers, SceneRenderLayer::layflag, RenderData::mode, SceneRenderLayer::next, bNode::next, bNodeTree::nodes, Scene::nodetree, NULL, object_camera_mode(), Scene::r, R_BORDER, R_DOCOMP, R_EDGE, R_EXR_TILE_FILE, R_FULL_SAMPLE, R_ORTHO, R_PANORAMA, R_SINGLE_LAYER, render_result_exr_file_path(), RPT_ERROR, SCE_LAY_DISABLE, RenderData::scemode, str, bNode::type, Scene::use_nodes, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by screen_render_invoke().
void RE_layer_load_from_file (RenderLayer * layer, ReportList * reports, const char * filename, int x, int y)
Definition at line 2358 of file pipeline.c.
References BKE_reportf(), IB_rect, IB_rectfloat, IMB_allocImBuf(), IMB_float_from_rect(), IMB_freeImBuf(), IMB_loadiffname(), IMB_rectcpy(), NULL, ImBuf::rect, ImBuf::rect_float, RenderLayer::rectf, RenderLayer::rectx, RenderLayer::recty, RPT_ERROR, ImBuf::x, and ImBuf::y.
void RE_MergeFullSample (Render * re, Main * bmain, Scene * sce, bNodeTree * ntree)
Definition at line 1489 of file pipeline.c.
References CMP_NODE_R_LAYERS, Render::dch, Render::dih, Render::display_clear, Render::display_init, do_merge_fullsample(), ListBase::first, ID::flag, G, bNode::id, Scene::id, if(), LIB_DOIT, Render::main, RenderData::mode, bNode::next, ID::next, bNodeTree::nodes, NULL, Scene::r, R_OSA, RE_ReadRenderResult(), Render::result, Main::scene, Render::scene, and bNode::type.
Referenced by node_read_fullsamplelayers_exec().
RenderResult* RE_MultilayerConvert (void * exrhandle, int rectx, int recty) [read]
Definition at line 209 of file pipeline.c.
References render_result_new_from_exr().
Referenced by image_create_multilayer().
Render* RE_NewRender (const char * name) [read]
Definition at line 349 of file pipeline.c.
References BLI_addtail(), BLI_rw_mutex_init(), BLI_strncpy(), MEM_callocN(), Render::name, NULL, RE_GetRender(), RE_InitRenderCB(), RE_MAXNAME, RenderGlobal, Render::resultmutex, and Render::ycor.
Referenced by envmap_render_copy(), init_bake_internal(), node_read_fullsamplelayers_exec(), RE_make_sticky(), RE_ReadRenderResult(), render_animation(), render_frame(), render_scene(), screen_opengl_render_init(), screen_render_exec(), screen_render_invoke(), seq_render_scene_strip(), and shader_preview_render().
void RE_PreviewRender (Render * re, Main * bmain, Scene * sce)
Definition at line 2269 of file pipeline.c.
References do_render_3d(), Scene::lay, Render::lay, Render::main, NULL, Scene::r, RE_GetCamera(), RE_InitState(), RE_SetCamera(), Render::scene, RenderData::size, RenderData::xsch, and RenderData::ysch.
Referenced by shader_preview_render().
void RE_progress_cb (Render * re, void * handle, void(*)(void *handle, float) f)
Definition at line 588 of file pipeline.c.
References Render::prh, and Render::progress.
Referenced by screen_render_invoke().
int RE_ReadRenderResult (Scene * scene, Scene * scenode)
Definition at line 2292 of file pipeline.c.
References BLI_rw_mutex_lock(), BLI_rw_mutex_unlock(), RenderData::border, Scene::id, RenderData::mode, ID::name, NULL, Scene::r, R_BORDER, RE_GetRender(), RE_InitState(), RE_NewRender(), render_result_exr_file_read(), Render::resultmutex, Render::scene, RenderData::size, THREAD_LOCK_WRITE, rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, RenderData::xsch, rctf::ymax, rcti::ymax, rctf::ymin, rcti::ymin, and RenderData::ysch.
Referenced by node_read_renderlayers_exec(), and RE_MergeFullSample().
void RE_ReleaseResult (Render * re)
Definition at line 280 of file pipeline.c.
References BLI_rw_mutex_unlock(), and Render::resultmutex.
Referenced by BKE_image_release_renderresult(), image_renderinfo_cb(), node_composit_exec_composite(), node_composit_exec_rlayers(), screen_opengl_render_apply(), screen_opengl_render_init(), uiTemplateImage(), and uiTemplateImageLayers().
void RE_ReleaseResultImage (Render * re)
Definition at line 328 of file pipeline.c.
References BLI_rw_mutex_unlock(), and Render::resultmutex.
Referenced by BKE_image_release_ibuf(), do_merge_fullsample(), do_write_image_or_movie(), ed_preview_draw_rect(), image_get_render_result(), RE_ResultGet32(), renderresult_stampinfo(), and seq_render_scene_strip().
float* RE_RenderLayerGetPass (RenderLayer * rl, int passtype)
Definition at line 187 of file pipeline.c.
References ListBase::first, RenderPass::next, NULL, RenderLayer::passes, RenderPass::passtype, and RenderPass::rect.
Referenced by atm_tile(), compbuf_from_pass(), RE_AcquireResultImage(), reset_sky_speed(), and reset_sky_speedvectors().
void RE_result_load_from_file (RenderResult * result, ReportList * reports, const char * filename)
Definition at line 2399 of file pipeline.c.
References BKE_reportf(), render_result_exr_file_read_path(), and RPT_ERROR.
void RE_ResultGet32 (Render * re, unsigned int * rect)
Definition at line 335 of file pipeline.c.
References Render::r, RE_AcquireResultImage(), RE_ReleaseResultImage(), Render::rectx, Render::recty, and render_result_rect_get_pixels().
Referenced by do_write_image_or_movie(), and shader_preview_render().
int RE_seq_render_active (Scene * scene, RenderData * rd)
Definition at line 1625 of file pipeline.c.
References Scene::ed, ListBase::first, Sequence::next, R_DOSEQ, RenderData::scemode, SEQ_SOUND, Editing::seqbase, and Sequence::type.
Referenced by do_render_all_options(), and screen_render_invoke().
void RE_set_max_threads (int threads)
Definition at line 2333 of file pipeline.c.
References BLENDER_MAX_THREADS, BLI_system_thread_count(), RenderGlobal, and threads.
Referenced by set_threads().
void RE_SetOrtho (Render * re, rctf * viewplane, float clipsta, float clipend)
Definition at line 548 of file pipeline.c.
References Render::clipend, Render::clipsta, RenderData::mode, orthographic_m4(), Render::r, R_ORTHO, Render::viewplane, Render::winmat, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
void RE_SetReports (Render * re, ReportList * reports)
Definition at line 2006 of file pipeline.c.
References Render::reports.
Referenced by render_animation(), render_frame(), render_startjob(), and screen_render_exec().
void RE_SetView (Render * re, float mat[][4])
Definition at line 560 of file pipeline.c.
References copy_m4_m4(), invert_m4_m4(), Render::viewinv, and Render::viewmat.
Referenced by database_fromscene_vectors(), RE_Database_Baking(), RE_Database_FromScene(), and RE_make_sticky().
void RE_SetWindow (Render * re, rctf * viewplane, float clipsta, float clipend)
Definition at line 535 of file pipeline.c.
References Render::clipend, Render::clipsta, RenderData::mode, perspective_m4(), Render::r, R_ORTHO, Render::viewplane, Render::winmat, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by find_next_pano_slice().
void RE_stats_draw_cb (Render * re, void * handle, void(*)(void *handle, RenderStats *rs) f)
Definition at line 583 of file pipeline.c.
References Render::sdh, and Render::stats_draw.
Referenced by screen_render_invoke().
void RE_SwapResult (Render * re, RenderResult ** rr)
Definition at line 271 of file pipeline.c.
References Render::result, and SWAP.
Referenced by BKE_image_backup_render().
void RE_test_break_cb (Render * re, void * handle, int(*)(void *handle) f)
Definition at line 600 of file pipeline.c.
References Render::tbh, and Render::test_break.
Referenced by bake_image_exec(), bake_startjob(), screen_render_exec(), screen_render_invoke(), and shader_preview_render().
void RE_TileProcessor (Render * re)
Definition at line 906 of file pipeline.c.
References threaded_tile_processor().
Referenced by render_envmap(), and sss_create_tree_mat().
int RE_WriteEnvmapResult (struct ReportList * reports, Scene * scene, EnvMap * env, const char * relpath, const char imtype, float layout[12])
Definition at line 2409 of file pipeline.c.
References BKE_report(), BKE_write_ibuf(), BLI_path_abs(), BLI_strncpy(), RenderData::color_mgt_flag, EnvMap::cube, ENV_CUBE, ENV_PLANE, FALSE, FILE_MAX, G, i, IB_PROFILE_LINEAR_RGB, IB_rectfloat, RenderData::im_format, IMB_allocImBuf(), IMB_freeImBuf(), IMB_rectcpy(), ImageFormatData::imtype, MAX2, NULL, ImBuf::profile, Scene::r, R_COLOR_MANAGEMENT, RPT_ERROR, TRUE, EnvMap::type, and ImBuf::x.
Referenced by save_envmap().
static void render_composit_stats (void * UNUSEDarg, char * str) [static]
Definition at line 1373 of file pipeline.c.
References Render::i, RenderStats::infostr, NULL, Render::sdh, Render::stats_draw, and str.
Referenced by do_merge_fullsample(), and do_render_composite_fields_blur_3d().
static int render_display_draw_enabled (Render * re) [static]
Definition at line 620 of file pipeline.c.
References Render::r, R_PREVIEWBUTS, RenderData::scemode, and Render::sss_points.
Referenced by do_part_thread(), and threaded_tile_processor().
RenderLayer* render_get_active_layer (Render * re, RenderResult * rr) [read]
Definition at line 214 of file pipeline.c.
References RenderData::actlay, BLI_findlink(), ListBase::first, RenderResult::layers, and Render::r.
Referenced by do_merge_fullsample(), do_render_blur_3d(), do_render_composite_fields_blur_3d(), do_render_fields_3d(), do_render_fields_blur_3d(), RE_AcquireResultImage(), zbufshade_sss_tile(), zbufshade_tile(), and zbufshadeDA_tile().
static int render_initialize_from_main (Render * re, Main * bmain, Scene * scene, SceneRenderLayer * srl, Object * camera_override, unsigned int lay, int anim, int anim_init) [static]
Definition at line 1935 of file pipeline.c.
References BLI_rw_mutex_lock(), BLI_rw_mutex_unlock(), RenderData::border, Render::camera_override, Render::dch, Render::dih, Render::display_clear, Render::display_init, Render::disprect, Render::lay, Render::main, RenderData::mode, ntreeCompositTagRender(), NULL, Render::ok, Scene::r, R_BORDER, R_SINGLE_LAYER, RE_InitState(), render_result_single_layer_begin(), Render::result, Render::resultmutex, RenderData::scemode, Render::scene, RenderData::size, tag_scenes_for_render(), THREAD_LOCK_WRITE, update_physics_cache(), validate_render_settings(), rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, RenderData::xsch, rctf::ymax, rcti::ymax, rctf::ymin, rcti::ymin, and RenderData::ysch.
Referenced by RE_BlenderAnim(), and RE_BlenderFrame().
static void render_scene (Render * re, Scene * sce, int cfra) [static]
Definition at line 1259 of file pipeline.c.
References RenderData::cfra, Render::ddh, Render::display_draw, Render::disprect, do_render_fields_blur_3d(), Scene::id, Scene::lay, Render::lay, Render::main, ID::name, NULL, Scene::r, RE_InitState(), RE_NewRender(), Render::scene, scene_camera_switch_update(), Render::sdh, set_scene_bg(), RenderData::size, Render::stats_draw, Render::tbh, Render::test_break, Render::winx, Render::winy, RenderData::xsch, and RenderData::ysch.
Referenced by ntree_render_scenes().
static int render_scene_needs_vector (Render * re) [static]
Definition at line 224 of file pipeline.c.
References ListBase::first, RenderData::layers, SceneRenderLayer::layflag, SceneRenderLayer::next, SceneRenderLayer::passflag, Scene::r, SCE_LAY_DISABLE, SCE_PASS_VECTOR, and Render::scene.
Referenced by do_render_3d().
static void renderresult_stampinfo (Render * re) [static]
Definition at line 1615 of file pipeline.c.
References BKE_stamp_buf(), RE_AcquireResultImage(), RE_GetCamera(), RE_ReleaseResultImage(), RenderResult::rect32, RenderResult::rectf, RenderResult::rectx, RenderResult::recty, and Render::scene.
Referenced by do_render_all_options().
static void result_nothing (void * UNUSEDarg, RenderResult * UNUSEDrr) [static]
Definition at line 139 of file pipeline.c.
Referenced by RE_InitRenderCB().
static void result_rcti_nothing (void * UNUSEDarg, RenderResult * UNUSEDrr, volatile struct rcti * UNUSEDrect) [static]
Definition at line 140 of file pipeline.c.
Referenced by RE_InitRenderCB().
static void stats_background (void * UNUSEDarg, RenderStats * rs) [static]
Definition at line 145 of file pipeline.c.
References BLI_CB_EVT_RENDER_STATS, BLI_exec_cb(), RenderStats::cfra, RenderStats::curblur, RenderStats::curfield, G, RenderStats::infostr, MEM_get_mapped_memory_in_use(), MEM_get_memory_in_use(), MEM_get_peak_memory(), mem_in_use, mmap_in_use, NULL, RenderStats::scenename, RenderStats::totface, RenderStats::tothalo, RenderStats::totlamp, and RenderStats::totvert.
Referenced by RE_InitRenderCB().
static void stats_nothing (void * UNUSEDarg, RenderStats * UNUSEDrs) [static]
Definition at line 141 of file pipeline.c.
Referenced by RE_InitRenderCB().
static void tag_scenes_for_render (Render * re) [static]
Definition at line 1314 of file pipeline.c.
References CMP_NODE_R_LAYERS, composite_needs_render(), ListBase::first, ID::flag, bNode::id, Scene::id, LIB_DOIT, Render::main, bNode::next, ID::next, bNodeTree::nodes, Scene::nodetree, NULL, RE_GetCamera(), Render::scene, Main::scene, and bNode::type.
Referenced by do_merge_fullsample(), ntree_render_scenes(), and render_initialize_from_main().
static int thread_break (void * UNUSEDarg) [static]
Definition at line 133 of file pipeline.c.
References g_break.
Referenced by threaded_tile_processor().
static void threaded_tile_processor (Render * re) [static]
Definition at line 780 of file pipeline.c.
References BLI_available_thread_index(), BLI_available_threads(), BLI_end_threads(), BLI_init_threads(), BLI_insert_thread(), BLI_remove_thread(), BLI_rw_mutex_lock(), BLI_rw_mutex_unlock(), Render::ddh, Render::display_draw, Render::disprect, do_part_thread(), RenderResult::exrhandle, find_next_pano_slice(), find_next_part(), ListBase::first, freeparts(), RenderPart::fullresult, Render::fullresult, g_break, Render::i, initparts(), RenderData::mode, RenderPart::next, RenderPart::nr, NULL, Render::parts, RenderStats::partsdone, PIL_sleep_ms(), Render::prh, print_part_stats(), Render::progress, Render::r, R_EXR_TILE_FILE, R_FULL_SAMPLE, R_PANORAMA, R_PREVIEWBUTS, RenderPart::ready, render_display_draw_enabled(), render_result_exr_file_begin(), render_result_exr_file_end(), render_result_free(), render_result_free_list(), render_result_new(), render_result_new_full_sample(), RenderResult::renrect, RenderPart::result, Render::result, Render::resultmutex, RR_USE_EXR, RR_USE_MEM, RenderData::scemode, Render::sss_points, Render::tbh, Render::test_break, RenderPart::thread, thread_break(), THREAD_LOCK_WRITE, RenderData::threads, threads, RenderStats::totpart, and Render::viewplane.
Referenced by do_render_3d(), and RE_TileProcessor().
static void update_physics_cache (Render * re, Scene * scene, int UNUSEDanim_init) [static]
Definition at line 1917 of file pipeline.c.
References PTCacheBaker::anim_init, PTCacheBaker::bake, BKE_ptcache_bake(), PTCacheBaker::break_data, PTCacheBaker::break_test, Render::main, PTCacheBaker::main, NULL, PTCacheBaker::pid, PTCacheBaker::progressbar, PTCacheBaker::quick_step, PTCacheBaker::render, PTCacheBaker::scene, Render::tbh, and Render::test_break.
Referenced by render_initialize_from_main().
static void validate_render_settings (Render * re) [static]
Definition at line 1901 of file pipeline.c.
References RenderData::mode, RenderData::osa, Render::r, R_EXR_TILE_FILE, R_FIELDS, R_FULL_SAMPLE, R_MBLUR, RE_engine_is_external(), and RenderData::scemode.
Referenced by render_initialize_from_main().
Variable Documentation
const float default_envmap_layout[] = { 0,0, 1,0, 2,0, 0,1, 1,1, 2,1 }
Definition at line 2407 of file pipeline.c.
Referenced by save_envmap(), and TEXTURE_OT_envmap_save().
volatile int g_break = 0 [static]
Definition at line 132 of file pipeline.c.
Referenced by thread_break(), and threaded_tile_processor().
Render R
Definition at line 126 of file pipeline.c.
struct { ... } RenderGlobal [static]
Referenced by do_merge_fullsample(), RE_FreeAllRender(), RE_FreeAllRenderResults(), RE_FreeRender(), RE_GetRender(), RE_init_threadcount(), RE_NewRender(), and RE_set_max_threads().
ListBase renderlist
Definition at line 119 of file pipeline.c.
int threads
Definition at line 122 of file pipeline.c.
Referenced by bake_image_exec(), BKE_ptcache_bake(), distribute_particles_on_dm(), make_occ_tree(), ntreeCompositExecTree(), occ_build_recursive(), project_paint_op(), psys_cache_child_paths(), psys_threads_create(), RE_bake_shade_all_selected(), RE_set_max_threads(), sb_cf_threads_run(), sb_sfesf_threads_run(), threaded_makeshadowbufs(), threaded_tile_processor(), and vol_precache_objectinstance_threads().