Blender: btGImpactQuantizedBvh.cpp File Reference
btGImpactQuantizedBvh.cpp File Reference
#include "btGImpactQuantizedBvh.h"
#include "LinearMath/btQuickprof.h"
Functions
SIMD_FORCE_INLINE bool _quantized_node_collision (btGImpactQuantizedBvh *boxset0, btGImpactQuantizedBvh *boxset1, const BT_BOX_BOX_TRANSFORM_CACHE &trans_cache_1to0, int node0, int node1, bool complete_primitive_tests)
static void _find_quantized_collision_pairs_recursive (btGImpactQuantizedBvh *boxset0, btGImpactQuantizedBvh *boxset1, btPairSet *collision_pairs, const BT_BOX_BOX_TRANSFORM_CACHE &trans_cache_1to0, int node0, int node1, bool complete_primitive_tests)
Function Documentation
static void _find_quantized_collision_pairs_recursive (btGImpactQuantizedBvh * boxset0, btGImpactQuantizedBvh * boxset1, btPairSet * collision_pairs, const BT_BOX_BOX_TRANSFORM_CACHE & trans_cache_1to0, int node0, int node1, bool complete_primitive_tests) [static]
Definition at line 404 of file btGImpactQuantizedBvh.cpp.
References _quantized_node_collision(), btGImpactQuantizedBvh::getLeftNode(), btGImpactQuantizedBvh::getNodeData(), btGImpactQuantizedBvh::getRightNode(), btGImpactQuantizedBvh::isLeafNode(), and btPairSet::push_pair().
Referenced by btGImpactQuantizedBvh::find_collision().
SIMD_FORCE_INLINE bool _quantized_node_collision (btGImpactQuantizedBvh * boxset0, btGImpactQuantizedBvh * boxset1, const BT_BOX_BOX_TRANSFORM_CACHE & trans_cache_1to0, int node0, int node1, bool complete_primitive_tests)
Definition at line 386 of file btGImpactQuantizedBvh.cpp.
References btGImpactQuantizedBvh::getNodeBound().
Referenced by _find_quantized_collision_pairs_recursive().