Blender: BlenderSession Class Reference
BlenderSession Class Reference
#include <blender_session.h>
Public Member Functions
BlenderSession (BL::RenderEngine b_engine, BL::UserPreferences b_userpref, BL::BlendData b_data, BL::Scene b_scene)
BlenderSession (BL::RenderEngine b_engine, BL::UserPreferences b_userpref, BL::BlendData b_data, BL::Scene b_scene, BL::SpaceView3D b_v3d, BL::RegionView3D b_rv3d, int width, int height)
~BlenderSession ()
void create_session ()
void free_session ()
void render ()
void write_render_result ()
void synchronize ()
bool draw (int w, int h)
void tag_redraw ()
void tag_update ()
void get_status (string &status, string &substatus)
void get_progress (float &progress, double &total_time)
void test_cancel ()
void update_status_progress ()
Public Attributes
bool background
Session * session
Scene * scene
BlenderSync * sync
double last_redraw_time
BL::RenderEngine b_engine
BL::UserPreferences b_userpref
BL::BlendData b_data
BL::Scene b_scene
BL::SpaceView3D b_v3d
BL::RegionView3D b_rv3d
BL::RenderResult b_rr
BL::RenderLayer b_rlay
string last_status
float last_progress
int width
int height
Detailed Description
Definition at line 33 of file blender_session.h.
Constructor & Destructor Documentation
CCL_NAMESPACE_BEGIN BlenderSession::BlenderSession (BL::RenderEngine b_engine, BL::UserPreferences b_userpref, BL::BlendData b_data, BL::Scene b_scene)
Definition at line 42 of file blender_session.cpp.
References b_scene, background, create_session(), height, last_redraw_time, and width.
BlenderSession::BlenderSession (BL::RenderEngine b_engine, BL::UserPreferences b_userpref, BL::BlendData b_data, BL::Scene b_scene, BL::SpaceView3D b_v3d, BL::RegionView3D b_rv3d, int width, int height)
Definition at line 59 of file blender_session.cpp.
References background, create_session(), height, last_redraw_time, session, Session::start(), and width.
BlenderSession::~BlenderSession ()
Definition at line 75 of file blender_session.cpp.
References free_session().
Member Function Documentation
void BlenderSession::create_session ()
Definition at line 80 of file blender_session.cpp.
References b_data, b_engine, b_rv3d, b_scene, b_userpref, b_v3d, background, function_bind, BlenderSync::get_buffer_params(), BlenderSync::get_scene_params(), BlenderSync::get_session_params(), BlenderSync::get_session_pause(), height, last_progress, last_status, Session::progress, Session::reset(), SessionParams::samples, scene, Session::scene, session, Progress::set_cancel_callback(), Session::set_pause(), Progress::set_update_callback(), sync, BlenderSync::sync_camera(), BlenderSync::sync_data(), BlenderSync::sync_view(), tag_redraw(), test_cancel(), and width.
Referenced by BlenderSession(), and synchronize().
bool BlenderSession::draw (int w, int h)
Definition at line 329 of file blender_session.cpp.
References b_rv3d, b_scene, b_userpref, b_v3d, background, Scene::camera, Session::draw(), BlenderSync::get_buffer_params(), BlenderSync::get_session_params(), height, Scene::mutex, Session::ready_to_reset(), Session::reset(), SessionParams::samples, scene, Session::scene, session, sync, BlenderSync::sync_view(), tag_update(), update_status_progress(), and width.
Referenced by draw_func().
void BlenderSession::free_session ()
Definition at line 113 of file blender_session.cpp.
References session, and sync.
Referenced by synchronize(), and ~BlenderSession().
void BlenderSession::get_progress (float & progress, double & total_time)
Definition at line 382 of file blender_session.cpp.
References Progress::get_sample(), Session::params, Session::progress, SessionParams::samples, and session.
Referenced by update_status_progress().
void BlenderSession::get_status (string & status, string & substatus)
Definition at line 377 of file blender_session.cpp.
References Progress::get_status(), Session::progress, and session.
Referenced by update_status_progress().
void BlenderSession::render ()
Definition at line 179 of file blender_session.cpp.
References add(), DeviceInfo::advanced_shading, b_engine, b_rlay, b_rr, b_rv3d, b_scene, b_userpref, b_v3d, background, SessionParams::device, Scene::film, BlenderSync::get_buffer_params(), Progress::get_cancel(), get_pass_type(), BlenderSync::get_session_params(), height, BufferParams::height, NULL, PASS_COMBINED, PASS_NONE, Film::passes, BufferParams::passes, Session::progress, RE_engine_begin_result(), RE_engine_end_result(), Session::reset(), RNA_pointer_create(), RNA_RenderResult, SessionParams::samples, scene, session, Session::start(), sync, BlenderSync::sync_data(), Film::tag_update(), Session::wait(), width, BufferParams::width, and write_render_result().
Referenced by render_func().
void BlenderSession::synchronize ()
Definition at line 283 of file blender_session.cpp.
References b_engine, b_rv3d, b_scene, b_userpref, b_v3d, background, create_session(), free_session(), BlenderSync::get_buffer_params(), BlenderSync::get_scene_params(), BlenderSync::get_session_params(), BlenderSync::get_session_pause(), height, SceneParams::modified(), SessionParams::modified(), Scene::mutex, Scene::need_reset(), Session::params, Scene::params, Session::ready_to_reset(), Session::reset(), SessionParams::samples, scene, Session::scene, session, Session::set_pause(), Session::set_samples(), Session::start(), sync, BlenderSync::sync_camera(), BlenderSync::sync_data(), BlenderSync::sync_recalc(), BlenderSync::sync_view(), tag_update(), and width.
Referenced by sync_func().
void BlenderSession::tag_redraw ()
Definition at line 423 of file blender_session.cpp.
References b_engine, background, engine_tag_redraw(), last_redraw_time, time_dt(), update_status_progress(), and write_render_result().
Referenced by create_session().
void BlenderSession::tag_update ()
Definition at line 417 of file blender_session.cpp.
References b_engine, and engine_tag_update().
Referenced by draw(), and synchronize().
void BlenderSession::test_cancel ()
Definition at line 443 of file blender_session.cpp.
References b_engine, background, Session::progress, RE_engine_test_break(), session, and Progress::set_cancel().
Referenced by create_session().
void BlenderSession::update_status_progress ()
Definition at line 391 of file blender_session.cpp.
References b_engine, BLI_timestr(), get_progress(), get_status(), last_progress, last_status, RE_engine_update_progress(), and RE_engine_update_stats().
Referenced by draw(), and tag_redraw().
void BlenderSession::write_render_result ()
Definition at line 242 of file blender_session.cpp.
References b_engine, b_rlay, b_rr, Session::buffers, RenderBuffers::copy_from_device(), Film::exposure, Scene::film, RenderBuffers::get_pass(), get_pass_type(), Progress::get_sample(), BufferParams::height, RenderBuffers::params, PASS_COMBINED, Session::progress, RE_engine_update_result(), rna_RenderLayer_rect_set(), rna_RenderPass_rect_set(), scene, session, and BufferParams::width.
Referenced by render(), and tag_redraw().
Member Data Documentation
BL::BlendData BlenderSession::b_data
Definition at line 71 of file blender_session.h.
Referenced by create_session().
BL::RenderEngine BlenderSession::b_engine
Definition at line 69 of file blender_session.h.
Referenced by create_session(), render(), synchronize(), tag_redraw(), tag_update(), test_cancel(), update_status_progress(), and write_render_result().
BL::RenderLayer BlenderSession::b_rlay
Definition at line 76 of file blender_session.h.
Referenced by render(), and write_render_result().
BL::RenderResult BlenderSession::b_rr
Definition at line 75 of file blender_session.h.
Referenced by render(), and write_render_result().
BL::RegionView3D BlenderSession::b_rv3d
Definition at line 74 of file blender_session.h.
Referenced by create_session(), draw(), render(), and synchronize().
BL::Scene BlenderSession::b_scene
Definition at line 72 of file blender_session.h.
Referenced by BlenderSession(), create_session(), draw(), render(), and synchronize().
BL::UserPreferences BlenderSession::b_userpref
Definition at line 70 of file blender_session.h.
Referenced by create_session(), draw(), render(), and synchronize().
BL::SpaceView3D BlenderSession::b_v3d
Definition at line 73 of file blender_session.h.
Referenced by create_session(), draw(), render(), and synchronize().
bool BlenderSession::background
Definition at line 63 of file blender_session.h.
Referenced by BlenderSession(), create_session(), draw(), render(), synchronize(), tag_redraw(), and test_cancel().
int BlenderSession::height
Definition at line 81 of file blender_session.h.
Referenced by BlenderSession(), create_session(), draw(), render(), and synchronize().
float BlenderSession::last_progress
Definition at line 79 of file blender_session.h.
Referenced by create_session(), and update_status_progress().
double BlenderSession::last_redraw_time
Definition at line 67 of file blender_session.h.
Referenced by BlenderSession(), and tag_redraw().
string BlenderSession::last_status
Definition at line 78 of file blender_session.h.
Referenced by create_session(), and update_status_progress().
Scene* BlenderSession::scene
Definition at line 65 of file blender_session.h.
Referenced by create_session(), draw(), render(), synchronize(), and write_render_result().
Session* BlenderSession::session
Definition at line 64 of file blender_session.h.
Referenced by BlenderSession(), create_session(), draw(), free_session(), get_progress(), get_status(), render(), synchronize(), test_cancel(), and write_render_result().
BlenderSync* BlenderSession::sync
Definition at line 66 of file blender_session.h.
Referenced by create_session(), draw(), free_session(), render(), and synchronize().
int BlenderSession::width
Definition at line 81 of file blender_session.h.
Referenced by BlenderSession(), create_func(), create_session(), draw(), render(), and synchronize().
The documentation for this class was generated from the following files:
blender_session.h
blender_session.cpp