Blender: RAS_FrameSettings Class Reference
RAS_FrameSettings Class Reference
#include <RAS_FramingManager.h>
Public Types
enum RAS_FrameType { e_frame_scale, e_frame_extend, e_frame_bars }
Public Member Functions
RAS_FrameSettings (RAS_FrameType frame_type, float bar_r, float bar_g, float bar_b, unsigned int design_aspect_width, unsigned int design_aspect_height)
RAS_FrameSettings ()
const RAS_FrameType & FrameType () const
void SetFrameType (RAS_FrameType type)
float BarRed () const
float BarGreen () const
float BarBlue () const
unsigned int DesignAspectWidth () const
unsigned int DesignAspectHeight () const
Detailed Description
RAS_FrameSettings
This is a value type describing the framing used by a particular scene in the game engine. Each KX_Scene contains a RAS_FrameSetting describing how the frustum and viewport are to be modified depending on the canvas size.
e_frame_scale means that the viewport is set to the current canvas size. If the view frustum aspect ratio is different to the canvas aspect this will lead to stretching.
e_frame_extend means that the best fit viewport will be computed based upon the design aspect ratio and the view frustum will be adjusted so that more of the scene is visible.
e_frame_bars means that the best fit viewport will be be computed based upon the design aspect ratio.
Definition at line 62 of file RAS_FramingManager.h.
Member Enumeration Documentation
enum RAS_FrameSettings::RAS_FrameType
enum defining the policy to use in each axis.
Enumerator:
e_frame_scale
e_frame_extend
e_frame_bars
Definition at line 69 of file RAS_FramingManager.h.
Constructor & Destructor Documentation
RAS_FrameSettings::RAS_FrameSettings (RAS_FrameType frame_type, float bar_r, float bar_g, float bar_b, unsigned int design_aspect_width, unsigned int design_aspect_height) [inline]
Contructor
Definition at line 79 of file RAS_FramingManager.h.
RAS_FrameSettings::RAS_FrameSettings () [inline]
Definition at line 96 of file RAS_FramingManager.h.
Member Function Documentation
float RAS_FrameSettings::BarBlue () const [inline]
Definition at line 138 of file RAS_FramingManager.h.
Referenced by KX_KetsjiEngine::Render(), and KX_KetsjiEngine::RenderDome().
float RAS_FrameSettings::BarGreen () const [inline]
Definition at line 132 of file RAS_FramingManager.h.
Referenced by KX_KetsjiEngine::Render(), and KX_KetsjiEngine::RenderDome().
float RAS_FrameSettings::BarRed () const [inline]
Definition at line 126 of file RAS_FramingManager.h.
Referenced by KX_KetsjiEngine::Render(), and KX_KetsjiEngine::RenderDome().
unsigned int RAS_FrameSettings::DesignAspectHeight () const [inline]
Definition at line 150 of file RAS_FramingManager.h.
Referenced by RAS_FramingManager::ComputeFrustum(), RAS_FramingManager::ComputeOrtho(), and RAS_FramingManager::ComputeViewport().
unsigned int RAS_FrameSettings::DesignAspectWidth () const [inline]
Definition at line 144 of file RAS_FramingManager.h.
Referenced by RAS_FramingManager::ComputeFrustum(), RAS_FramingManager::ComputeOrtho(), and RAS_FramingManager::ComputeViewport().
const RAS_FrameType& RAS_FrameSettings::FrameType () const [inline]
Accessors
Definition at line 113 of file RAS_FramingManager.h.
Referenced by RAS_FramingManager::ComputeFrustum(), RAS_FramingManager::ComputeOrtho(), RAS_FramingManager::ComputeViewport(), and KX_KetsjiEngine::GetSceneViewport().
void RAS_FrameSettings::SetFrameType (RAS_FrameType type) [inline]
Definition at line 119 of file RAS_FramingManager.h.
Referenced by KX_KetsjiEngine::GetSceneViewport().
The documentation for this class was generated from the following file:
RAS_FramingManager.h