Blender: rna_world.c File Reference
rna_world.c File Reference
RNA
#include <float.h>
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_material_types.h"
#include "DNA_texture_types.h"
#include "DNA_world_types.h"
#include "WM_types.h"
Functions
static void rna_def_world_mtex (BlenderRNA *brna)
static void rna_def_lighting (BlenderRNA *brna)
static void rna_def_world_mist (BlenderRNA *brna)
static void rna_def_world_stars (BlenderRNA *brna)
void RNA_def_world (BlenderRNA *brna)
Detailed Description
Definition in file rna_world.c.
Function Documentation
static void rna_def_lighting (BlenderRNA * brna) [static]
Definition at line 215 of file rna_world.c.
References FLT_MAX, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), WO_AMB_OCC, WO_AOADD, WO_AOCACHE, WO_AODIST, WO_AOGATHER_APPROX, WO_AOGATHER_RAYTRACE, WO_AOMUL, WO_AOPLAIN, WO_AOSAMP_CONSTANT, WO_AOSAMP_HALTON, WO_AOSAMP_HAMMERSLEY, WO_AOSKYCOL, WO_AOSKYTEX, WO_ENV_LIGHT, and WO_INDIRECT_LIGHT.
Referenced by RNA_def_world().
void RNA_def_world (BlenderRNA * brna)
Definition at line 486 of file rna_world.c.
References NC_WORLD, ND_WORLD_DRAW, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLOR, PROP_FLOAT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, rna_def_animdata_common(), rna_def_lighting(), rna_def_mtex_common(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), rna_def_world_mist(), rna_def_world_mtex(), rna_def_world_stars(), WO_SKYBLEND, WO_SKYPAPER, WO_SKYREAL, WOPHY_BULLET, and WOPHY_NONE.
static void rna_def_world_mist (BlenderRNA * brna) [static]
Definition at line 392 of file rna_world.c.
References FLT_MAX, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and WO_MIST.
Referenced by RNA_def_world().
static void rna_def_world_mtex (BlenderRNA * brna) [static]
Definition at line 136 of file rna_world.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TEXCO_ANGMAP, TEXCO_EQUIRECTMAP, TEXCO_GLOB, TEXCO_H_SPHEREMAP, TEXCO_H_TUBEMAP, TEXCO_OBJECT, TEXCO_VIEW, WOMAP_BLEND, WOMAP_HORIZ, WOMAP_ZENDOWN, and WOMAP_ZENUP.
Referenced by RNA_def_world().
static void rna_def_world_stars (BlenderRNA * brna) [static]
Definition at line 446 of file rna_world.c.
References NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and WO_STARS.
Referenced by RNA_def_world().