Blender: interface_handlers.c File Reference
interface_handlers.c File Reference
interface
#include <float.h>
#include <limits.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <assert.h>
#include "MEM_guardedalloc.h"
#include "DNA_sensor_types.h"
#include "DNA_controller_types.h"
#include "DNA_actuator_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BLI_string_cursor_utf8.h"
#include "PIL_time.h"
#include "BKE_colortools.h"
#include "BKE_context.h"
#include "BKE_idprop.h"
#include "BKE_report.h"
#include "BKE_texture.h"
#include "BKE_tracking.h"
#include "BKE_unit.h"
#include "ED_screen.h"
#include "ED_util.h"
#include "ED_keyframing.h"
#include "UI_interface.h"
#include "BLF_api.h"
#include "interface_intern.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
Classes
struct uiHandleButtonData
struct uiAfterFunc
Defines
#define BUTTON_TOOLTIP_DELAY 0.500
#define BUTTON_FLASH_DELAY 0.020
#define MENU_SCROLL_INTERVAL 0.1
#define BUTTON_AUTO_OPEN_THRESH 0.3
#define BUTTON_MOUSE_TOWARDS_THRESH 1.0
Typedefs
typedef enum uiButtonActivateType uiButtonActivateType
typedef enum uiHandleButtonState uiHandleButtonState
typedef struct uiHandleButtonData uiHandleButtonData
typedef struct uiAfterFunc uiAfterFunc
Enumerations
enum uiButtonActivateType {
BUTTON_ACTIVATE_OVER, BUTTON_ACTIVATE, BUTTON_ACTIVATE_APPLY, BUTTON_ACTIVATE_TEXT_EDITING,
BUTTON_ACTIVATE_OPEN
}
enum uiHandleButtonState {
BUTTON_STATE_INIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_WAIT_FLASH, BUTTON_STATE_WAIT_RELEASE,
BUTTON_STATE_WAIT_KEY_EVENT, BUTTON_STATE_NUM_EDITING, BUTTON_STATE_TEXT_EDITING, BUTTON_STATE_TEXT_SELECTING,
BUTTON_STATE_MENU_OPEN, BUTTON_STATE_WAIT_DRAG, BUTTON_STATE_EXIT
}
Functions
static void ui_add_smart_controller (bContext *C, uiBut *from, uiBut *to)
static void ui_add_link (bContext *C, uiBut *from, uiBut *to)
static int ui_but_contains_pt (uiBut *but, int mx, int my)
static int ui_mouse_inside_button (ARegion *ar, uiBut *but, int x, int y)
static void button_activate_state (bContext *C, uiBut *but, uiHandleButtonState state)
static int ui_handler_region_menu (bContext *C, wmEvent *event, void *userdata)
static void ui_handle_button_activate (bContext *C, ARegion *ar, uiBut *but, uiButtonActivateType type)
static void button_timers_tooltip_remove (bContext *C, uiBut *but)
static int ui_but_editable (uiBut *but)
static uiBut * ui_but_prev (uiBut *but)
static uiBut * ui_but_next (uiBut *but)
static uiBut * ui_but_first (uiBlock *block)
static uiBut * ui_but_last (uiBlock *block)
static int ui_is_a_warp_but (uiBut *but)
int ui_is_but_utf8 (uiBut *but)
static void ui_apply_but_func (bContext *C, uiBut *but)
static void ui_apply_autokey_undo (bContext *C, uiBut *but)
static void ui_apply_but_funcs_after (bContext *C)
static void ui_apply_but_BUT (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_BUTM (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_BLOCK (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_TOG (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_ROW (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_TEX (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_NUM (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_TOG3 (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_VEC (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_COLORBAND (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_CURVE (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_IDPOIN (bContext *C, uiBut *but, uiHandleButtonData *data)
static int ui_but_mouse_inside_icon (uiBut *but, ARegion *ar, wmEvent *event)
static int ui_but_start_drag (bContext *C, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static void ui_delete_active_linkline (uiBlock *block)
static uiLinkLine * ui_is_a_link (uiBut *from, uiBut *to)
static void ui_apply_but_LINK (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_IMAGE (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_HISTOGRAM (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_WAVEFORM (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_but_TRACKPREVIEW (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_apply_button (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, int interactive)
static void ui_but_drop (bContext *C, wmEvent *event, uiBut *but, uiHandleButtonData *data)
static void ui_but_copy_paste (bContext *C, uiBut *but, uiHandleButtonData *data, char mode)
static int ui_textedit_delete_selection (uiBut *but, uiHandleButtonData *data)
static void ui_textedit_set_cursor_pos (uiBut *but, uiHandleButtonData *data, short x)
static void ui_textedit_set_cursor_select (uiBut *but, uiHandleButtonData *data, short x)
static int ui_textedit_type_buf (uiBut *but, uiHandleButtonData *data, const char *utf8_buf, int utf8_buf_len)
static int ui_textedit_type_ascii (uiBut *but, uiHandleButtonData *data, char ascii)
static void ui_textedit_move (uiBut *but, uiHandleButtonData *data, strCursorJumpDirection direction, int select, strCursorJumpType jump)
static int ui_textedit_delete (uiBut *but, uiHandleButtonData *data, int direction, strCursorJumpType jump)
static int ui_textedit_autocomplete (bContext *C, uiBut *but, uiHandleButtonData *data)
static int ui_textedit_copypaste (uiBut *but, uiHandleButtonData *data, int paste, int copy, int cut)
static void ui_textedit_begin (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_textedit_end (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_textedit_next_but (uiBlock *block, uiBut *actbut, uiHandleButtonData *data)
static void ui_textedit_prev_but (uiBlock *block, uiBut *actbut, uiHandleButtonData *data)
static void ui_do_but_textedit (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static void ui_do_but_textedit_select (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static void ui_numedit_begin (uiBut *but, uiHandleButtonData *data)
static void ui_numedit_end (uiBut *but, uiHandleButtonData *data)
static void ui_numedit_apply (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data)
static void ui_blockopen_begin (bContext *C, uiBut *but, uiHandleButtonData *data)
static void ui_blockopen_end (bContext *C, uiBut *but, uiHandleButtonData *data)
static int ui_do_but_BUT (bContext *C, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_do_but_HOTKEYEVT (bContext *C, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_do_but_KEYEVT (bContext *C, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_do_but_TEX (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_do_but_TOG (bContext *C, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_do_but_EXIT (bContext *C, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static float ui_numedit_apply_snapf (uiBut *but, float tempf, float softmin, float softmax, float softrange, int snap)
static float ui_numedit_apply_snap (int temp, float softmin, float softmax, int snap)
static int ui_numedit_but_NUM (uiBut *but, uiHandleButtonData *data, float fac, int snap, int mx)
static int ui_do_but_NUM (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_numedit_but_SLI (uiBut *but, uiHandleButtonData *data, int shift, int ctrl, int mx)
static int ui_do_but_SLI (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_do_but_SCROLL (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_do_but_BLOCK (bContext *C, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_numedit_but_NORMAL (uiBut *but, uiHandleButtonData *data, int mx, int my)
static int ui_do_but_NORMAL (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_numedit_but_HSVCUBE (uiBut *but, uiHandleButtonData *data, int mx, int my)
static void ui_ndofedit_but_HSVCUBE (uiBut *but, uiHandleButtonData *data, wmNDOFMotionData *ndof, int shift)
static int ui_do_but_HSVCUBE (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_numedit_but_HSVCIRCLE (uiBut *but, uiHandleButtonData *data, int mx, int my, int shift)
static void ui_ndofedit_but_HSVCIRCLE (uiBut *but, uiHandleButtonData *data, wmNDOFMotionData *ndof, int shift)
static int ui_do_but_HSVCIRCLE (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_numedit_but_COLORBAND (uiBut *but, uiHandleButtonData *data, int mx)
static int ui_do_but_COLORBAND (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_numedit_but_CURVE (uiBut *but, uiHandleButtonData *data, int snap, int mx, int my)
static int ui_do_but_CURVE (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int in_scope_resize_zone (uiBut *but, int UNUSED(x), int y)
static int ui_numedit_but_HISTOGRAM (uiBut *but, uiHandleButtonData *data, int mx, int my)
static int ui_do_but_HISTOGRAM (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_numedit_but_WAVEFORM (uiBut *but, uiHandleButtonData *data, int mx, int my)
static int ui_do_but_WAVEFORM (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_numedit_but_VECTORSCOPE (uiBut *but, uiHandleButtonData *data, int mx, int my)
static int ui_do_but_VECTORSCOPE (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_do_but_LINK (bContext *C, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static int ui_numedit_but_TRACKPREVIEW (bContext *C, uiBut *but, uiHandleButtonData *data, int mx, int my, int shift)
static int ui_do_but_TRACKPREVIEW (bContext *C, uiBlock *block, uiBut *but, uiHandleButtonData *data, wmEvent *event)
static void but_shortcut_name_func (bContext *C, void *arg1, int UNUSED(event))
static uiBlock * menu_change_shortcut (bContext *C, ARegion *ar, void *arg)
static uiBlock * menu_add_shortcut (bContext *C, ARegion *ar, void *arg)
static void popup_change_shortcut_func (bContext *C, void *arg1, void *UNUSED(arg2))
static void remove_shortcut_func (bContext *C, void *arg1, void *UNUSED(arg2))
static void popup_add_shortcut_func (bContext *C, void *arg1, void *UNUSED(arg2))
static int ui_but_menu (bContext *C, uiBut *but)
static int ui_do_button (bContext *C, uiBlock *block, uiBut *but, wmEvent *event)
static uiBut * ui_but_find_activated (ARegion *ar)
int ui_button_is_active (ARegion *ar)
void uiFreeActiveButtons (const bContext *C, bScreen *screen)
int UI_but_active_drop_name (bContext *C)
static void ui_blocks_set_tooltips (ARegion *ar, int enable)
static int ui_mouse_inside_region (ARegion *ar, int x, int y)
static uiBut * ui_but_find_mouse_over (ARegion *ar, int x, int y)
static uiBut * ui_list_find_mouse_over (ARegion *ar, int x, int y)
static int button_modal_state (uiHandleButtonState state)
static void button_tooltip_timer_reset (bContext *C, uiBut *but)
static void button_activate_init (bContext *C, ARegion *ar, uiBut *but, uiButtonActivateType type)
static void button_activate_exit (bContext *C, uiHandleButtonData *data, uiBut *but, int mousemove, int onfree)
void ui_button_active_free (const bContext *C, uiBut *but)
static uiBut * ui_context_button_active (const bContext *C, int(*but_check_cb)(uiBut *))
static int ui_context_rna_button_active_test (uiBut *but)
static uiBut * ui_context_rna_button_active (const bContext *C)
uiBut * uiContextActiveButton (const struct bContext *C)
void uiContextActiveProperty (const bContext *C, struct PointerRNA *ptr, struct PropertyRNA **prop, int *index)
void uiContextActivePropertyHandle (bContext *C)
wmOperator * uiContextActiveOperator (const struct bContext *C)
void uiContextAnimUpdate (const bContext *C)
static uiBut * uit_but_find_open_event (ARegion *ar, wmEvent *event)
static int ui_handle_button_over (bContext *C, wmEvent *event, ARegion *ar)
void ui_button_activate_do (bContext *C, ARegion *ar, uiBut *but)
static int ui_handle_button_event (bContext *C, wmEvent *event, uiBut *but)
static int ui_handle_list_event (bContext *C, wmEvent *event, ARegion *ar)
static void ui_handle_button_return_submenu (bContext *C, wmEvent *event, uiBut *but)
static void ui_mouse_motion_towards_init (uiPopupBlockHandle *menu, int mx, int my, int force)
static int ui_mouse_motion_towards_check (uiBlock *block, uiPopupBlockHandle *menu, int mx, int my)
static char ui_menu_scroll_test (uiBlock *block, int my)
static int ui_menu_scroll (ARegion *ar, uiBlock *block, int my)
static int ui_handle_menu_event (bContext *C, wmEvent *event, uiPopupBlockHandle *menu, int UNUSED(topmenu))
static int ui_handle_menu_return_submenu (bContext *C, wmEvent *event, uiPopupBlockHandle *menu)
static int ui_handle_menus_recursive (bContext *C, wmEvent *event, uiPopupBlockHandle *menu)
static int ui_handler_region (bContext *C, wmEvent *event, void *UNUSED(userdata))
static void ui_handler_remove_region (bContext *C, void *UNUSED(userdata))
static int ui_handler_region_menu (bContext *C, wmEvent *event, void *UNUSED(userdata))
static int ui_handler_popup (bContext *C, wmEvent *event, void *userdata)
static void ui_handler_remove_popup (bContext *C, void *userdata)
void UI_add_region_handlers (ListBase *handlers)
void UI_add_popup_handlers (bContext *C, ListBase *handlers, uiPopupBlockHandle *popup)
void UI_remove_popup_handlers (ListBase *handlers, uiPopupBlockHandle *popup)
Variables
static ListBase UIAfterFuncs = {NULL, NULL}
Detailed Description
Definition in file interface_handlers.c.
Define Documentation
#define BUTTON_AUTO_OPEN_THRESH 0.3
Definition at line 87 of file interface_handlers.c.
Referenced by button_activate_init().
#define BUTTON_FLASH_DELAY 0.020
Definition at line 85 of file interface_handlers.c.
Referenced by button_activate_state().
#define BUTTON_MOUSE_TOWARDS_THRESH 1.0
Definition at line 88 of file interface_handlers.c.
Referenced by ui_mouse_motion_towards_check().
#define BUTTON_TOOLTIP_DELAY 0.500
Definition at line 84 of file interface_handlers.c.
Referenced by button_tooltip_timer_reset().
#define MENU_SCROLL_INTERVAL 0.1
Definition at line 86 of file interface_handlers.c.
Referenced by ui_handle_menu_event().
Typedef Documentation
typedef struct uiAfterFunc uiAfterFunc
typedef enum uiButtonActivateType uiButtonActivateType
typedef struct uiHandleButtonData uiHandleButtonData
typedef enum uiHandleButtonState uiHandleButtonState
Enumeration Type Documentation
enum uiButtonActivateType
Enumerator:
BUTTON_ACTIVATE_OVER
BUTTON_ACTIVATE
BUTTON_ACTIVATE_APPLY
BUTTON_ACTIVATE_TEXT_EDITING
BUTTON_ACTIVATE_OPEN
Definition at line 90 of file interface_handlers.c.
enum uiHandleButtonState
Enumerator:
BUTTON_STATE_INIT
BUTTON_STATE_HIGHLIGHT
BUTTON_STATE_WAIT_FLASH
BUTTON_STATE_WAIT_RELEASE
BUTTON_STATE_WAIT_KEY_EVENT
BUTTON_STATE_NUM_EDITING
BUTTON_STATE_TEXT_EDITING
BUTTON_STATE_TEXT_SELECTING
BUTTON_STATE_MENU_OPEN
BUTTON_STATE_WAIT_DRAG
BUTTON_STATE_EXIT
Definition at line 98 of file interface_handlers.c.
Function Documentation
static void but_shortcut_name_func (bContext * C, void * arg1, int UNUSEDevent) [static]
Definition at line 4260 of file interface_handlers.c.
References PointerRNA::data, wmOperatorType::idname, if(), NULL, uiBut::opcontext, uiBut::opptr, uiBut::optype, TRUE, ui_but_add_shortcut(), and WM_key_event_operator_string().
Referenced by menu_add_shortcut(), menu_change_shortcut(), and remove_shortcut_func().
static void button_activate_exit (bContext * C, uiHandleButtonData * data, uiBut * but, int mousemove, int onfree) [static]
Definition at line 5218 of file interface_handlers.c.
References uiBut::active, uiBut::block, uiPopupBlockHandle::butretval, button_activate_state(), BUTTON_STATE_EXIT, uiBlock::buttons, uiHandleButtonData::cancel, ED_region_tag_redraw(), uiHandleButtonData::escapecancel, ListBase::first, uiBut::flag, uiBlock::flag, uiBlock::handle, MEM_freeN(), uiPopupBlockHandle::menuretval, uiBut::next, uiBlock::next, NULL, uiHandleButtonData::origstr, uiHandleButtonData::region, uiHandleButtonData::retval, uiHandleButtonData::state, uiHandleButtonData::str, uiBlock::tooltipdisabled, UI_ACTIVE, ui_apply_autokey_undo(), ui_apply_button(), UI_BLOCK_KEEP_OPEN, UI_BLOCK_POPUP_MEMORY, ui_blocks_set_tooltips(), UI_BUT_LAST_ACTIVE, ui_check_but(), ui_popup_menu_memory(), UI_RETURN_CANCEL, UI_RETURN_OK, UI_SELECT, ARegion::uiblocks, and WM_event_add_mousemove().
Referenced by ui_button_active_free(), ui_handle_button_activate(), ui_handle_button_event(), and ui_handle_button_return_submenu().
static void button_activate_init (bContext * C, ARegion * ar, uiBut * but, uiButtonActivateType type) [static]
Definition at line 5158 of file interface_handlers.c.
References uiBut::active, uiBlock::auto_open, uiBlock::auto_open_last, uiBut::block, BUT_CURVE, BUTTON_ACTIVATE, BUTTON_ACTIVATE_APPLY, BUTTON_ACTIVATE_OPEN, BUTTON_ACTIVATE_OVER, button_activate_state(), BUTTON_ACTIVATE_TEXT_EDITING, BUTTON_AUTO_OPEN_THRESH, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_INIT, BUTTON_STATE_MENU_OPEN, BUTTON_STATE_TEXT_EDITING, BUTTON_STATE_WAIT_FLASH, BUTTON_STATE_WAIT_KEY_EVENT, CTX_wm_manager(), CTX_wm_window(), data, ELEM, FALSE, ListBase::first, uiBut::flag, HOTKEYEVT, uiHandleButtonData::interactive, MEM_callocN(), uiHandleButtonData::menu, PIL_check_seconds_timer(), uiHandleButtonData::region, uiPopupBlockHandle::region, SEARCH_MENU, uiHandleButtonData::state, TRUE, uiBut::type, UI_ACTIVE, ui_but_first(), UI_BUT_IMMEDIATE, ui_handle_button_activate(), ARegion::uiblocks, uiHandleButtonData::used_mouse, uiHandleButtonData::window, and uiHandleButtonData::wm.
Referenced by ui_button_activate_do(), ui_handle_button_activate(), ui_handle_button_event(), and ui_handle_button_over().
static void button_activate_state (bContext * C, uiBut * but, uiHandleButtonState state) [static]
Definition at line 5056 of file interface_handlers.c.
References uiBut::active, uiBlock::auto_open, uiHandleButtonData::autoopentimer, BLOCK, uiBut::block, BUTTON_FLASH_DELAY, button_modal_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_MENU_OPEN, BUTTON_STATE_NUM_EDITING, BUTTON_STATE_TEXT_EDITING, BUTTON_STATE_TEXT_SELECTING, BUTTON_STATE_WAIT_DRAG, BUTTON_STATE_WAIT_FLASH, button_timers_tooltip_remove(), button_tooltip_timer_reset(), CTX_wm_window(), data, ED_region_tag_redraw(), ELEM3, uiBut::flag, uiBlock::flag, uiHandleButtonData::flashtimer, uiBlock::handle, ICONTEXTROW, wmWindow::modalhandlers, NULL, uiPopupBlockHandle::popup, PULLDOWN, uiHandleButtonData::region, state, uiHandleButtonData::state, TIMER, TRUE, uiBut::type, UI_BLOCK_LOOP, ui_blockopen_begin(), ui_blockopen_end(), ui_check_but(), ui_handler_region_menu(), ui_is_a_warp_but(), ui_numedit_begin(), ui_numedit_end(), UI_SELECT, ui_textedit_begin(), ui_textedit_end(), uiHandleButtonData::used_mouse, USER_MENUOPENAUTO, uiHandleButtonData::window, uiHandleButtonData::wm, WM_cursor_grab(), WM_cursor_ungrab(), WM_event_add_timer(), WM_event_add_ui_handler(), WM_event_remove_timer(), and WM_event_remove_ui_handler().
Referenced by button_activate_exit(), button_activate_init(), ui_but_copy_paste(), ui_but_drop(), ui_but_start_drag(), ui_do_but_BLOCK(), ui_do_but_BUT(), ui_do_but_COLORBAND(), ui_do_but_CURVE(), ui_do_but_EXIT(), ui_do_but_HISTOGRAM(), ui_do_but_HOTKEYEVT(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_do_but_KEYEVT(), ui_do_but_LINK(), ui_do_but_NORMAL(), ui_do_but_NUM(), ui_do_but_SCROLL(), ui_do_but_SLI(), ui_do_but_TEX(), ui_do_but_textedit(), ui_do_but_textedit_select(), ui_do_but_TOG(), ui_do_but_TRACKPREVIEW(), ui_do_but_VECTORSCOPE(), ui_do_but_WAVEFORM(), ui_do_button(), ui_handle_button_event(), and ui_handle_button_return_submenu().
static int button_modal_state (uiHandleButtonState state) [static]
Definition at line 5008 of file interface_handlers.c.
References BUTTON_STATE_MENU_OPEN, BUTTON_STATE_NUM_EDITING, BUTTON_STATE_TEXT_EDITING, BUTTON_STATE_TEXT_SELECTING, BUTTON_STATE_WAIT_KEY_EVENT, BUTTON_STATE_WAIT_RELEASE, and ELEM6.
Referenced by button_activate_state(), and ui_handle_menu_event().
static void button_timers_tooltip_remove (bContext * C, uiBut * but) [static]
Definition at line 5015 of file interface_handlers.c.
References uiBut::active, uiHandleButtonData::autoopentimer, data, NULL, uiHandleButtonData::tooltip, uiHandleButtonData::tooltiptimer, ui_tooltip_free(), uiHandleButtonData::window, uiHandleButtonData::wm, and WM_event_remove_timer().
Referenced by button_activate_state(), popup_add_shortcut_func(), popup_change_shortcut_func(), and ui_but_menu().
static void button_tooltip_timer_reset (bContext * C, uiBut * but) [static]
Definition at line 5038 of file interface_handlers.c.
References uiBut::active, uiBut::block, BUTTON_TOOLTIP_DELAY, CTX_wm_manager(), data, wmWindowManager::drags, ListBase::first, NULL, TIMER, uiBlock::tooltipdisabled, uiHandleButtonData::tooltiptimer, USER_TOOLTIPS, uiHandleButtonData::window, uiHandleButtonData::wm, WM_event_add_timer(), and WM_event_remove_timer().
Referenced by button_activate_state(), and ui_handle_button_event().
static int in_scope_resize_zone (uiBut * but, int UNUSEDx, int y) [static]
Definition at line 3802 of file interface_handlers.c.
References SCOPE_RESIZE_PAD.
Referenced by ui_numedit_but_HISTOGRAM(), ui_numedit_but_TRACKPREVIEW(), ui_numedit_but_VECTORSCOPE(), and ui_numedit_but_WAVEFORM().
static uiBlock* menu_add_shortcut (bContext * C, ARegion * ar, void * arg) [static]
Definition at line 4314 of file interface_handlers.c.
References AKEY, but_shortcut_name_func(), CTX_wm_manager(), PointerRNA::data, wmWindowManager::id, wmKeyMapItem::id, wmOperatorType::idname, IDP_CopyProperty(), KM_PRESS, NULL, uiBut::opptr, uiBut::optype, RNA_KeyMapItem, RNA_pointer_create(), UI_BLOCK_RET_1, UI_CENTER, UI_EMBOSS, UI_GetStyle(), UI_ITEM_R_FULL_EVENT, UI_ITEM_R_IMMEDIATE, UI_LAYOUT_PANEL, UI_LAYOUT_VERTICAL, uiBeginBlock(), uiBlockLayout(), uiBlockSetDirection(), uiBlockSetFlag(), uiBlockSetHandleFunc(), uiEndBlock(), uiItemR(), uiPopupBoundsBlock(), WM_keyconfig_update(), WM_keymap_add_item(), WM_keymap_guess_opname(), WM_keymap_item_find_id(), and WM_keymap_properties_reset().
Referenced by popup_add_shortcut_func().
static uiBlock* menu_change_shortcut (bContext * C, ARegion * ar, void * arg) [static]
Definition at line 4282 of file interface_handlers.c.
References but_shortcut_name_func(), CTX_wm_manager(), PointerRNA::data, wmWindowManager::id, wmOperatorType::idname, NULL, uiBut::opcontext, uiBut::opptr, uiBut::optype, RNA_KeyMapItem, RNA_pointer_create(), UI_BLOCK_MOVEMOUSE_QUIT, UI_CENTER, UI_EMBOSS, UI_GetStyle(), UI_ITEM_R_FULL_EVENT, UI_ITEM_R_IMMEDIATE, UI_LAYOUT_PANEL, UI_LAYOUT_VERTICAL, uiBeginBlock(), uiBlockLayout(), uiBlockSetDirection(), uiBlockSetFlag(), uiBlockSetHandleFunc(), uiEndBlock(), uiItemR(), uiPopupBoundsBlock(), WM_key_event_operator_id(), and WM_keymap_item_find_id().
Referenced by popup_change_shortcut_func().
static void popup_add_shortcut_func (bContext * C, void * arg1, void * UNUSEDarg2) [static]
Definition at line 4381 of file interface_handlers.c.
References button_timers_tooltip_remove(), menu_add_shortcut(), and uiPupBlock().
Referenced by ui_but_menu().
static void popup_change_shortcut_func (bContext * C, void * arg1, void * UNUSEDarg2) [static]
Definition at line 4360 of file interface_handlers.c.
References button_timers_tooltip_remove(), menu_change_shortcut(), and uiPupBlock().
Referenced by ui_but_menu().
static void remove_shortcut_func (bContext * C, void * arg1, void * UNUSEDarg2) [static]
Definition at line 4367 of file interface_handlers.c.
References but_shortcut_name_func(), PointerRNA::data, wmOperatorType::idname, NULL, uiBut::opcontext, uiBut::opptr, uiBut::optype, WM_key_event_operator_id(), WM_keymap_item_find_id(), and WM_keymap_remove_item().
Referenced by ui_but_menu().
static void ui_add_link (bContext * C, uiBut * from, uiBut * to) [static]
Definition at line 828 of file interface_handlers.c.
References uiBut::block, uiLinkLine::flag, uiBut::hardmin, INLINK, link(), LINK, uiBut::link, MEM_callocN(), MEM_freeN(), uiLink::poin, uiBut::poin, uiLink::ppoin, uiLink::tocode, uiLink::totlink, uiBut::type, ui_add_smart_controller(), ui_delete_active_linkline(), ui_is_a_link(), and UI_SELECT.
Referenced by ui_add_smart_controller(), and ui_apply_but_LINK().
void UI_add_popup_handlers (bContext * C, ListBase * handlers, uiPopupBlockHandle * popup)
Definition at line 6556 of file interface_handlers.c.
References ui_handler_popup(), ui_handler_remove_popup(), and WM_event_add_ui_handler().
Referenced by ui_popup_menu_create(), uiPupBlockEx(), uiPupBlockO(), and uiPupMenuEnd().
void UI_add_region_handlers (ListBase * handlers)
Definition at line 6550 of file interface_handlers.c.
References NULL, ui_handler_region(), ui_handler_remove_region(), WM_event_add_ui_handler(), and WM_event_remove_ui_handler().
Referenced by ed_default_handlers(), and ui_popup_block_create().
static void ui_add_smart_controller (bContext * C, uiBut * from, uiBut * to) [static]
Definition at line 766 of file interface_handlers.c.
References Object::actuators, Object::controllers, CTX_DATA_BEGIN, CTX_DATA_END, ListBase::first, uiBut::hardmin, INLINK, ListBase::last, link(), LINK, uiBut::link, bSensor::links, MEM_callocN(), MEM_freeN(), bSensor::next, bActuator::next, NULL, OPERATOR_FINISHED, uiBut::poin, uiLink::ppoin, uiLink::tocode, uiBut::type, ui_add_link(), uiSetButLink(), WM_OP_EXEC_DEFAULT, and WM_operator_name_call().
Referenced by ui_add_link().
static void ui_apply_autokey_undo (bContext * C, uiBut * but) [static]
Definition at line 338 of file interface_handlers.c.
References BLI_addtail(), BLI_strncpy(), RenderData::cfra, CTX_data_scene(), uiBut::drawstr, ELEM, uiBut::flag, ICONTEXTROW, INLINK, LINK, MEM_callocN(), MENU, NULL, Scene::r, str, uiBut::tip, uiBut::type, ui_but_anim_autokey(), UI_BUT_UNDO, and uiAfterFunc::undostr.
Referenced by button_activate_exit().
static void ui_apply_but_BLOCK (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 443 of file interface_handlers.c.
References uiHandleButtonData::applied, ELEM3, ICONROW, ICONTEXTROW, MENU, uiBut::retval, uiHandleButtonData::retval, uiBut::type, ui_apply_but_func(), ui_check_but(), ui_set_but_val(), and uiHandleButtonData::value.
Referenced by ui_apply_button().
static void ui_apply_but_BUT (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 426 of file interface_handlers.c.
References uiHandleButtonData::applied, uiBut::retval, uiHandleButtonData::retval, and ui_apply_but_func().
Referenced by ui_apply_button().
static void ui_apply_but_BUTM (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 434 of file interface_handlers.c.
References uiHandleButtonData::applied, uiBut::hardmin, uiBut::retval, uiHandleButtonData::retval, ui_apply_but_func(), and ui_set_but_val().
Referenced by ui_apply_button().
static void ui_apply_but_COLORBAND (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 615 of file interface_handlers.c.
References uiHandleButtonData::applied, uiBut::retval, uiHandleButtonData::retval, and ui_apply_but_func().
Referenced by ui_apply_button().
static void ui_apply_but_CURVE (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 622 of file interface_handlers.c.
References uiHandleButtonData::applied, uiBut::retval, uiHandleButtonData::retval, and ui_apply_but_func().
Referenced by ui_apply_button().
static void ui_apply_but_func (bContext * C, uiBut * but) [static]
Definition at line 280 of file interface_handlers.c.
References uiBut::a2, uiAfterFunc::a2, BLI_addtail(), uiBut::block, BUTM, uiAfterFunc::butm_func, uiBlock::butm_func, uiBlock::butm_func_arg, uiAfterFunc::butm_func_arg, uiBut::context, uiAfterFunc::context, CTX_store_copy(), ELEM, uiBut::func, uiAfterFunc::func, uiAfterFunc::func_arg1, uiBut::func_arg1, uiAfterFunc::func_arg2, uiBut::func_arg2, uiBut::func_arg3, uiAfterFunc::func_arg3, uiAfterFunc::func_argN, uiBut::func_argN, uiAfterFunc::funcN, uiBut::funcN, uiBlock::handle_func, uiAfterFunc::handle_func, uiBlock::handle_func_arg, uiAfterFunc::handle_func_arg, MEM_callocN(), MEM_dupallocN(), NULL, uiAfterFunc::opcontext, uiBut::opcontext, uiAfterFunc::opptr, uiBut::opptr, uiAfterFunc::optype, uiBut::optype, uiAfterFunc::rename_arg1, uiBut::rename_arg1, uiBut::rename_func, uiAfterFunc::rename_func, uiBut::rename_orig, uiAfterFunc::rename_orig, uiAfterFunc::retval, uiBut::retval, uiAfterFunc::rnapoin, uiBut::rnapoin, uiAfterFunc::rnaprop, uiBut::rnaprop, and uiBut::type.
Referenced by ui_apply_but_BLOCK(), ui_apply_but_BUT(), ui_apply_but_BUTM(), ui_apply_but_COLORBAND(), ui_apply_but_CURVE(), ui_apply_but_HISTOGRAM(), ui_apply_but_IDPOIN(), ui_apply_but_IMAGE(), ui_apply_but_LINK(), ui_apply_but_NUM(), ui_apply_but_ROW(), ui_apply_but_TEX(), ui_apply_but_TOG(), ui_apply_but_TOG3(), ui_apply_but_TRACKPREVIEW(), ui_apply_but_VEC(), and ui_apply_but_WAVEFORM().
static void ui_apply_but_funcs_after (bContext * C) [static]
Definition at line 367 of file interface_handlers.c.
References uiAfterFunc::a2, BLI_freelinkN(), uiAfterFunc::butm_func, uiAfterFunc::butm_func_arg, uiAfterFunc::context, CTX_store_free(), CTX_store_set(), PointerRNA::data, ED_undo_push(), ListBase::first, uiAfterFunc::func, uiAfterFunc::func_arg1, uiAfterFunc::func_arg2, uiAfterFunc::func_argN, uiAfterFunc::funcN, uiAfterFunc::handle_func, uiAfterFunc::handle_func_arg, wmOperatorType::idname, ListBase::last, MEM_freeN(), uiAfterFunc::next, NULL, uiAfterFunc::opcontext, uiAfterFunc::opptr, uiAfterFunc::optype, uiAfterFunc::rename_arg1, uiAfterFunc::rename_func, uiAfterFunc::rename_orig, uiAfterFunc::retval, RNA_property_update(), uiAfterFunc::rnapoin, uiAfterFunc::rnaprop, UIAfterFuncs, uiAfterFunc::undostr, WM_operator_name_call(), and WM_operator_properties_free().
Referenced by ui_handler_popup(), ui_handler_region(), ui_handler_region_menu(), ui_handler_remove_popup(), and ui_handler_remove_region().
static void ui_apply_but_HISTOGRAM (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 909 of file interface_handlers.c.
References uiHandleButtonData::applied, uiBut::retval, uiHandleButtonData::retval, and ui_apply_but_func().
Referenced by ui_apply_button().
static void ui_apply_but_IDPOIN (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 629 of file interface_handlers.c.
References uiHandleButtonData::applied, uiBut::retval, uiHandleButtonData::retval, uiHandleButtonData::str, ui_apply_but_func(), ui_check_but(), and ui_set_but_string().
Referenced by ui_apply_button().
static void ui_apply_but_IMAGE (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 902 of file interface_handlers.c.
References uiHandleButtonData::applied, uiBut::retval, uiHandleButtonData::retval, and ui_apply_but_func().
Referenced by ui_apply_button().
static void ui_apply_but_LINK (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 880 of file interface_handlers.c.
References uiHandleButtonData::applied, uiBut::block, uiBlock::buttons, CTX_wm_region(), ELEM, ListBase::first, INLINK, LINK, uiBut::linkto, uiBut::next, uiBut::retval, uiHandleButtonData::retval, uiBut::type, ui_add_link(), ui_apply_but_func(), ui_mouse_inside_button(), ARegion::winrct, rcti::xmin, and rcti::ymin.
Referenced by ui_apply_button().
static void ui_apply_but_NUM (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 549 of file interface_handlers.c.
References uiHandleButtonData::applied, uiHandleButtonData::cancel, uiBut::retval, uiHandleButtonData::retval, uiHandleButtonData::str, ui_apply_but_func(), ui_check_but(), ui_get_but_val(), ui_set_but_string(), ui_set_but_val(), and uiHandleButtonData::value.
Referenced by ui_apply_button().
static void ui_apply_but_ROW (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 513 of file interface_handlers.c.
References uiHandleButtonData::applied, uiBlock::buttons, ELEM, ListBase::first, uiBut::hardmax, LISTROW, uiBut::next, uiBut::poin, uiBut::retval, uiHandleButtonData::retval, ROW, uiBut::type, ui_apply_but_func(), ui_check_but(), and ui_set_but_val().
Referenced by ui_apply_button().
static void ui_apply_but_TEX (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 530 of file interface_handlers.c.
References uiHandleButtonData::applied, NULL, uiHandleButtonData::origstr, uiBut::rename_orig, uiBut::retval, uiHandleButtonData::retval, uiHandleButtonData::str, ui_apply_but_func(), ui_check_but(), and ui_set_but_string().
Referenced by ui_apply_button().
static void ui_apply_but_TOG (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 454 of file interface_handlers.c.
References uiHandleButtonData::applied, BCLR, uiBut::bit, uiBut::bitnr, BSET, BTST, BUT_TOGDUAL, ELEM3, ICONTOG, ICONTOGN, INT, OPTIONN, uiBut::poin, uiBut::pointype, uiBut::retval, uiHandleButtonData::retval, SHO, uiHandleButtonData::togdual, TOGN, uiHandleButtonData::togonly, TOGR, uiBut::type, ui_apply_but_func(), ui_check_but(), ui_get_but_val(), and ui_set_but_val().
Referenced by ui_apply_button().
static void ui_apply_but_TOG3 (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 570 of file interface_handlers.c.
References uiHandleButtonData::applied, BCLR, uiBut::bitnr, BSET, BTST, if(), uiBut::poin, uiBut::pointype, uiBut::retval, uiHandleButtonData::retval, SHO, ui_apply_but_func(), and ui_check_but().
Referenced by ui_apply_button().
static void ui_apply_but_TRACKPREVIEW (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 923 of file interface_handlers.c.
References uiHandleButtonData::applied, uiBut::retval, uiHandleButtonData::retval, and ui_apply_but_func().
Referenced by ui_apply_button().
static void ui_apply_but_VEC (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 605 of file interface_handlers.c.
References uiHandleButtonData::applied, uiBut::retval, uiHandleButtonData::retval, ui_apply_but_func(), ui_check_but(), ui_set_but_vectorf(), and uiHandleButtonData::vec.
Referenced by ui_apply_button().
static void ui_apply_but_WAVEFORM (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 916 of file interface_handlers.c.
References uiHandleButtonData::applied, uiBut::retval, uiHandleButtonData::retval, and ui_apply_but_func().
Referenced by ui_apply_button().
static void ui_apply_button (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, int interactive) [static]
Definition at line 931 of file interface_handlers.c.
References uiHandleButtonData::applied, uiHandleButtonData::appliedinteractive, BLOCK, BUT, BUT_COLORBAND, BUT_CURVE, BUT_IMAGE, BUT_NORMAL, BUT_TOGDUAL, BUTM, uiHandleButtonData::cancel, CHARTAB, COL, copy_v3_v3(), uiBut::editcoba, uiBut::editcumap, uiBut::editstr, uiBut::editval, uiBut::editvec, HISTOGRAM, HOTKEYEVT, HSVCIRCLE, HSVCUBE, HSVSLI, ICONROW, ICONTEXTROW, ICONTOG, ICONTOGN, IDPOIN, INLINK, KEYEVT, LINK, LISTROW, MEM_freeN(), MENU, NULL, NUM, NUMABS, NUMSLI, OPTION, OPTIONN, uiHandleButtonData::origstr, uiHandleButtonData::origvalue, uiHandleButtonData::origvec, PULLDOWN, uiHandleButtonData::retval, ROW, SCROLL, SEARCH_MENU, SLI, uiHandleButtonData::str, TEX, TOG, TOG3, TOGBUT, TOGN, TOGR, TRACKPREVIEW, uiBut::type, ui_apply_but_BLOCK(), ui_apply_but_BUT(), ui_apply_but_BUTM(), ui_apply_but_COLORBAND(), ui_apply_but_CURVE(), ui_apply_but_HISTOGRAM(), ui_apply_but_IDPOIN(), ui_apply_but_IMAGE(), ui_apply_but_LINK(), ui_apply_but_NUM(), ui_apply_but_ROW(), ui_apply_but_TEX(), ui_apply_but_TOG(), ui_apply_but_TOG3(), ui_apply_but_TRACKPREVIEW(), ui_apply_but_VEC(), ui_apply_but_WAVEFORM(), uiHandleButtonData::value, uiHandleButtonData::vec, and WAVEFORM.
Referenced by button_activate_exit(), ui_do_but_BLOCK(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_do_but_textedit(), ui_handle_button_return_submenu(), and ui_numedit_apply().
static void ui_blockopen_begin (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 2002 of file interface_handlers.c.
References BLOCK, uiBut::block, uiBut::block_create_func, COL, copy_v3_v3(), uiBut::editval, uiBut::editvec, uiAfterFunc::func, uiBut::func_argN, uiBlock::handle, ICONROW, ICONTEXTROW, MENU, uiHandleButtonData::menu, uiBut::menu_create_func, NULL, uiHandleButtonData::origvalue, uiHandleButtonData::origvec, uiBut::poin, uiPopupBlockHandle::popup, PULLDOWN, uiHandleButtonData::region, uiBut::str, uiBut::type, ui_block_func_COL(), ui_block_func_ICONROW(), ui_block_func_ICONTEXTROW(), ui_get_but_val(), ui_get_but_vectorf(), ui_popup_block_create(), ui_popup_menu_create(), uiHandleButtonData::value, and uiHandleButtonData::vec.
Referenced by button_activate_state().
static void ui_blockopen_end (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 2068 of file interface_handlers.c.
References uiBlock::auto_open_last, uiBut::block, uiBut::editval, uiBut::editvec, uiHandleButtonData::menu, NULL, PIL_check_seconds_timer(), and ui_popup_block_free().
Referenced by button_activate_state().
static void ui_blocks_set_tooltips (ARegion * ar, int enable) [static]
Definition at line 4858 of file interface_handlers.c.
References ListBase::first, uiBlock::next, uiBlock::tooltipdisabled, and ARegion::uiblocks.
Referenced by button_activate_exit(), ui_handle_button_event(), ui_handler_popup(), ui_handler_region(), and ui_handler_region_menu().
int UI_but_active_drop_name (bContext * C)
Definition at line 4845 of file interface_handlers.c.
References CTX_wm_region(), ELEM3, IDPOIN, SEARCH_MENU, TEX, uiBut::type, and ui_but_find_activated().
Referenced by wm_drop_operator_options().
static int ui_but_contains_pt (uiBut * but, int mx, int my) [static]
Definition at line 4798 of file interface_handlers.c.
References uiBut::x1, uiBut::x2, uiBut::y1, and uiBut::y2.
Referenced by ui_but_find_mouse_over(), ui_do_but_textedit(), ui_list_find_mouse_over(), and ui_mouse_inside_button().
static void ui_but_copy_paste (bContext * C, uiBut * but, uiHandleButtonData * data, char mode) [static]
Definition at line 1105 of file interface_handlers.c.
References uiBut::active, BLI_snprintf(), BLI_strncpy(), BLI_strncpy_utf8(), BUT_COLORBAND, button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_NUM_EDITING, BUTTON_STATE_TEXT_EDITING, uiHandleButtonData::cancel, uiHandleButtonData::coba, COL, PointerRNA::data, ELEM3, ELEM4, HSVSLI, i, IDPOIN, uiBut::lock, uiHandleButtonData::maxlen, MEM_callocN(), MEM_freeN(), NULL, NUM, NUMABS, NUMSLI, uiAfterFunc::opptr, uiBut::optype, p, uiBut::poin, uiBut::rnapoin, SEARCH_MENU, uiHandleButtonData::searchbox, str, uiHandleButtonData::str, TEX, ColorBand::tot, uiBut::type, ui_get_but_string(), ui_get_but_vectorf(), ui_is_but_utf8(), UI_MAX_DRAW_STR, ui_searchbox_update(), ui_set_but_string(), ui_set_but_string_eval_num(), ui_set_but_vectorf(), uiButGetOperatorPtrRNA(), uiHandleButtonData::value, WM_clipboard_text_get(), WM_clipboard_text_set(), and WM_operator_pystring().
Referenced by ui_do_button().
static void ui_but_drop (bContext * C, wmEvent * event, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 1081 of file interface_handlers.c.
References BLI_strncpy(), button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_TEXT_EDITING, PointerRNA::data, ELEM3, ListBase::first, IDPOIN, if(), uiHandleButtonData::maxlen, ID::name, wmDrag::next, NULL, wmDrag::poin, uiBut::poin, uiBut::rnapoin, SEARCH_MENU, uiHandleButtonData::str, TEX, wmDrag::type, uiBut::type, and WM_DRAG_ID.
Referenced by ui_do_button().
static int ui_but_editable (uiBut * but) [static]
Definition at line 208 of file interface_handlers.c.
References ELEM5, LABEL, LISTBOX, PROGRESSBAR, ROUNDBOX, SEPR, and uiBut::type.
Referenced by ui_but_first(), ui_but_last(), ui_but_next(), and ui_but_prev().
static uiBut* ui_but_find_activated (ARegion * ar) [static]
Definition at line 4803 of file interface_handlers.c.
References uiBut::active, uiBlock::buttons, ListBase::first, uiBut::next, uiBlock::next, NULL, and ARegion::uiblocks.
Referenced by UI_but_active_drop_name(), ui_button_is_active(), ui_handle_button_activate(), ui_handle_menu_event(), ui_handle_menu_return_submenu(), ui_handle_menus_recursive(), ui_handler_region(), ui_handler_region_menu(), and uiFreeActiveButtons().
static uiBut* ui_but_find_mouse_over (ARegion * ar, int x, int y) [static]
Definition at line 4938 of file interface_handlers.c.
References uiBlock::buttons, uiBut::dragpoin, ELEM3, ListBase::first, uiBut::flag, uiBlock::flag, LABEL, LISTBOX, uiBlock::maxx, uiBlock::maxy, uiBlock::minx, uiBlock::miny, uiBut::next, uiBlock::next, NULL, ROUNDBOX, SEPR, uiBut::type, UI_BLOCK_CLIP_EVENTS, ui_but_contains_pt(), UI_HIDDEN, ui_mouse_inside_region(), UI_SCROLLED, ui_window_to_block(), and ARegion::uiblocks.
Referenced by ui_handle_button_event(), and ui_handle_button_over().
static uiBut* ui_but_first (uiBlock * block) [static]
Definition at line 231 of file interface_handlers.c.
References uiBlock::buttons, ListBase::first, uiBut::next, NULL, and ui_but_editable().
Referenced by button_activate_init(), and ui_handle_menu_event().
static uiBut* ui_but_last (uiBlock * block) [static]
Definition at line 243 of file interface_handlers.c.
References uiBlock::buttons, ListBase::last, NULL, uiBut::prev, and ui_but_editable().
Referenced by ui_handle_menu_event().
static int ui_but_menu (bContext * C, uiBut * but) [static]
Definition at line 4389 of file interface_handlers.c.
References ANIM_driver_can_paste(), BLI_snprintf(), BUT, button_timers_tooltip_remove(), PointerRNA::data, wmOperatorType::description, uiBut::flag, wmOperatorType::idname, ISKEYBOARD, length(), wmOperatorType::name, NULL, uiBut::opcontext, uiBut::opptr, uiBut::optype, popup_add_shortcut_func(), popup_change_shortcut_func(), remove_shortcut_func(), RNA_property_animateable(), RNA_property_array_length(), RNA_property_description(), RNA_property_identifier(), RNA_property_path_from_ID_check(), RNA_property_ui_name(), RNA_string_set(), RNA_struct_identifier(), uiBut::rnapoin, uiBut::rnaprop, wmKeyMapItem::type, PointerRNA::type, UI_BUT_ANIMATED, UI_BUT_ANIMATED_KEY, UI_BUT_DRIVEN, UI_UNIT_Y, uiButSetFunc(), uiDefIconTextBut(), uiItemBooleanO(), uiItemFullO(), uiItemO(), uiItemS(), uiLayoutGetBlock(), uiLayoutGetWidth(), uiLayoutSetOperatorContext(), uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), WM_key_event_operator_id(), WM_keymap_guess_opname(), WM_keymap_item_find_id(), WM_OP_EXEC_DEFAULT, WM_OP_INVOKE_DEFAULT, WM_operator_properties_create(), and WM_operator_py_idname().
Referenced by ui_do_button().
static int ui_but_mouse_inside_icon (uiBut * but, ARegion * ar, wmEvent * event) [static]
Definition at line 649 of file interface_handlers.c.
References BLI_in_rcti(), uiBut::block, uiBut::flag, uiBut::imb, UI_ICON_LEFT, ui_window_to_block(), uiBut::x1, uiBut::x2, rcti::xmax, rcti::xmin, uiBut::y1, uiBut::y2, rcti::ymax, and rcti::ymin.
Referenced by ui_do_but_BLOCK(), and ui_do_but_EXIT().
static uiBut* ui_but_next (uiBut * but) [static]
Definition at line 222 of file interface_handlers.c.
References uiBut::next, NULL, and ui_but_editable().
Referenced by ui_handle_menu_event(), and ui_menu_scroll().
static uiBut* ui_but_prev (uiBut * but) [static]
Definition at line 213 of file interface_handlers.c.
References NULL, uiBut::prev, and ui_but_editable().
Referenced by ui_handle_menu_event(), and ui_menu_scroll().
static int ui_but_start_drag (bContext * C, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 672 of file interface_handlers.c.
References ABS, button_activate_state(), BUTTON_STATE_EXIT, uiHandleButtonData::cancel, uiBut::dragpoin, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, uiBut::dragtype, uiBut::icon, uiBut::imb, uiBut::imb_scale, ui_get_but_val(), WM_event_drag_image(), WM_event_start_drag(), WM_gestures_remove(), wmEvent::x, uiBut::x1, uiBut::x2, wmEvent::y, uiBut::y1, and uiBut::y2.
Referenced by ui_do_but_BLOCK(), and ui_do_but_EXIT().
void ui_button_activate_do (bContext * C, ARegion * ar, uiBut * but)
Definition at line 5502 of file interface_handlers.c.
References uiBut::block, button_activate_init(), BUTTON_ACTIVATE_OVER, CTX_wm_window(), wmWindow::eventstate, EVT_BUT_OPEN, FALSE, KM_PRESS, and ui_do_button().
Referenced by uiButActiveOnly().
void ui_button_active_free (const bContext * C, uiBut * but)
Definition at line 5287 of file interface_handlers.c.
References uiBut::active, button_activate_exit(), uiHandleButtonData::cancel, and data.
Referenced by ui_free_but(), and uiFreeActiveButtons().
int ui_button_is_active (ARegion * ar)
Definition at line 4816 of file interface_handlers.c.
References NULL, and ui_but_find_activated().
Referenced by ui_handler_panel_region().
static uiBut* ui_context_button_active (const bContext * C, int(*)(uiBut *) but_check_cb) [static]
Definition at line 5302 of file interface_handlers.c.
References uiBut::active, uiBlock::buttons, CTX_wm_region(), data, ListBase::first, uiBut::flag, uiHandleButtonData::menu, uiBut::next, uiBlock::next, NULL, uiPopupBlockHandle::region, UI_BUT_LAST_ACTIVE, and ARegion::uiblocks.
Referenced by ui_context_rna_button_active(), and uiContextActiveButton().
static uiBut* ui_context_rna_button_active (const bContext * C) [static]
Definition at line 5348 of file interface_handlers.c.
References ui_context_button_active(), and ui_context_rna_button_active_test().
Referenced by uiContextActiveProperty(), and uiContextActivePropertyHandle().
static int ui_context_rna_button_active_test (uiBut * but) [static]
Definition at line 5344 of file interface_handlers.c.
References PointerRNA::data, NULL, and uiBut::rnapoin.
Referenced by ui_context_rna_button_active().
static void ui_delete_active_linkline (uiBlock * block) [static]
Definition at line 694 of file interface_handlers.c.
References BLI_remlink(), uiBlock::buttons, ListBase::first, uiLinkLine::flag, uiLinkLine::from, uiLink::lines, link(), LINK, uiBut::link, MEM_freeN(), uiLinkLine::next, uiBut::next, NULL, uiLink::poin, uiBut::poin, uiLink::ppoin, uiLinkLine::to, uiLink::totlink, uiBut::type, and UI_SELECT.
Referenced by ui_add_link().
static int ui_do_but_BLOCK (bContext * C, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 2896 of file interface_handlers.c.
References wmEvent::alt, uiBut::block, BUTTON_ACTIVATE_OVER, button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_MENU_OPEN, BUTTON_STATE_WAIT_DRAG, uiHandleButtonData::cancel, CLAMPIS, COL, uiBut::dragpoin, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, ELEM, ELEM3, hsv_to_rgb(), ICONROW, ICONTEXTROW, KM_PRESS, KM_RELEASE, LEFTMOUSE, MENU, PADENTER, uiHandleButtonData::postbut, uiHandleButtonData::posttype, uiHandleButtonData::region, RETKEY, rgb_to_hsv_compat(), uiHandleButtonData::state, wmEvent::type, uiBut::type, ui_apply_button(), ui_block_hsv_get(), ui_but_mouse_inside_icon(), ui_but_start_drag(), ui_get_but_vectorf(), ui_set_but_vectorf(), ui_step_name_menu(), wmEvent::val, uiHandleButtonData::value, uiHandleButtonData::vec, WHEELDOWNMOUSE, WHEELUPMOUSE, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_do_button().
static int ui_do_but_BUT (bContext * C, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 2085 of file interface_handlers.c.
References uiBut::block, button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_WAIT_FLASH, BUTTON_STATE_WAIT_RELEASE, uiHandleButtonData::cancel, ELEM, uiBut::flag, uiBlock::handle, KM_PRESS, LEFTMOUSE, PADENTER, RETKEY, uiHandleButtonData::state, wmEvent::type, UI_SELECT, wmEvent::val, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_do_button().
static int ui_do_but_COLORBAND (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 3518 of file interface_handlers.c.
References ABS, button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_NUM_EDITING, colorband_element_add(), wmEvent::ctrl, ColorBand::cur, ColorBand::data, uiHandleButtonData::dragcbd, uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, if(), KM_PRESS, LEFTMOUSE, MOUSEMOVE, uiBut::poin, CBData::pos, uiHandleButtonData::region, uiHandleButtonData::state, wmEvent::type, ui_numedit_apply(), ui_numedit_but_COLORBAND(), ui_window_to_block(), wmEvent::val, WM_UI_HANDLER_BREAK, WM_UI_HANDLER_CONTINUE, uiBut::x1, and uiBut::x2.
Referenced by ui_do_button().
static int ui_do_but_CURVE (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 3660 of file interface_handlers.c.
References button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_NUM_EDITING, uiHandleButtonData::cancel, CurveMapping::cm, CM_TABLE, wmEvent::ctrl, CurveMapping::cur, CurveMapping::curr, curvemap_insert(), curvemapping_changed(), uiHandleButtonData::dragchange, uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragsel, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, fabsf, FALSE, i, if(), KM_PRESS, LEFTMOUSE, MOUSEMOVE, uiBut::poin, uiHandleButtonData::region, SELECT, wmEvent::shift, uiHandleButtonData::state, wmEvent::type, ui_numedit_apply(), ui_numedit_but_CURVE(), ui_window_to_block(), wmEvent::val, WM_UI_HANDLER_BREAK, WM_UI_HANDLER_CONTINUE, uiBut::x1, uiBut::x2, rctf::xmax, rctf::xmin, uiBut::y1, uiBut::y2, rctf::ymax, and rctf::ymin.
Referenced by ui_do_button().
static int ui_do_but_EXIT (bContext * C, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 2235 of file interface_handlers.c.
References button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_WAIT_DRAG, uiBut::dragpoin, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, ELEM3, uiBut::imb, KM_PRESS, KM_RELEASE, LEFTMOUSE, PADENTER, uiHandleButtonData::region, RETKEY, uiHandleButtonData::state, wmEvent::type, ui_but_mouse_inside_icon(), ui_but_start_drag(), wmEvent::val, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_do_button().
static int ui_do_but_HISTOGRAM (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 3840 of file interface_handlers.c.
References BACKSPACEKEY, button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_NUM_EDITING, uiHandleButtonData::cancel, uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, uiHandleButtonData::escapecancel, ESCKEY, KM_PRESS, LEFTMOUSE, MOUSEMOVE, uiBut::poin, uiHandleButtonData::region, uiHandleButtonData::state, wmEvent::type, ui_numedit_apply(), ui_numedit_but_HISTOGRAM(), ui_window_to_block(), wmEvent::val, WM_UI_HANDLER_BREAK, WM_UI_HANDLER_CONTINUE, and Histogram::ymax.
Referenced by ui_do_button().
static int ui_do_but_HOTKEYEVT (bContext * C, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 2113 of file interface_handlers.c.
References uiBut::active, wmEvent::alt, button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_WAIT_KEY_EVENT, uiHandleButtonData::cancel, wmEvent::ctrl, uiBut::drawstr, ED_region_tag_redraw(), ELEM3, uiHandleButtonData::escapecancel, ESCKEY, uiBut::flag, ISHOTKEY, KM_ALT, KM_CTRL, KM_OSKEY, KM_PRESS, KM_SHIFT, LEFTMOUSE, uiBut::modifier_key, MOUSEMOVE, wmEvent::oskey, PADENTER, uiHandleButtonData::region, RETKEY, wmEvent::shift, uiHandleButtonData::state, wmEvent::type, UI_BUT_IMMEDIATE, ui_check_but(), ui_mouse_inside_button(), ui_set_but_val(), wmEvent::val, WM_key_event_string(), WM_UI_HANDLER_BREAK, WM_UI_HANDLER_CONTINUE, wmEvent::x, and wmEvent::y.
Referenced by ui_do_button().
static int ui_do_but_HSVCIRCLE (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 3402 of file interface_handlers.c.
References BACKSPACEKEY, uiBut::block, button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_NUM_EDITING, uiHandleButtonData::cancel, CLAMPIS, wmEvent::customdata, uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, uiHandleButtonData::escapecancel, ESCKEY, hsv_to_rgb(), KM_PRESS, LEFTMOUSE, len(), MEM_callocN(), MEM_freeN(), MOUSEMOVE, NDOF_MOTION, uiHandleButtonData::region, rgb_to_hsv(), rgb_to_hsv_compat(), RNA_property_array_length(), RNA_property_float_get_default_array(), RNA_property_update(), uiBut::rnapoin, uiBut::rnaprop, wmEvent::shift, uiHandleButtonData::state, wmEvent::type, ui_apply_button(), ui_block_hsv_get(), ui_get_but_vectorf(), ui_ndofedit_but_HSVCIRCLE(), ui_numedit_apply(), ui_numedit_but_HSVCIRCLE(), ui_set_but_hsv(), ui_set_but_vectorf(), ui_window_to_block(), wmEvent::val, WHEELDOWNMOUSE, WHEELUPMOUSE, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_do_button().
static int ui_do_but_HSVCUBE (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 3218 of file interface_handlers.c.
References uiBut::a1, BACKSPACEKEY, uiBut::block, button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_NUM_EDITING, uiHandleButtonData::cancel, wmEvent::customdata, uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, uiHandleButtonData::escapecancel, ESCKEY, hsv_to_rgb(), KM_PRESS, LEFTMOUSE, len(), MEM_callocN(), MEM_freeN(), MOUSEMOVE, NDOF_MOTION, uiHandleButtonData::region, rgb_to_hsv(), rgb_to_hsv_compat(), RNA_property_array_length(), RNA_property_float_get_default_array(), RNA_property_update(), uiBut::rnapoin, uiBut::rnaprop, wmEvent::shift, uiHandleButtonData::state, wmEvent::type, ui_apply_button(), ui_block_hsv_get(), ui_get_but_vectorf(), UI_GRAD_V_ALT, ui_ndofedit_but_HSVCUBE(), ui_numedit_apply(), ui_numedit_but_HSVCUBE(), ui_set_but_vectorf(), ui_window_to_block(), wmEvent::val, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_do_button().
static int ui_do_but_KEYEVT (bContext * C, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 2174 of file interface_handlers.c.
References button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_WAIT_KEY_EVENT, uiHandleButtonData::cancel, ELEM3, KM_PRESS, LEFTMOUSE, MOUSEMOVE, PADENTER, RETKEY, uiHandleButtonData::state, wmEvent::type, ui_set_but_val(), wmEvent::val, WM_key_event_string(), WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_do_button().
static int ui_do_but_LINK (bContext * C, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 4150 of file interface_handlers.c.
References uiBut::block, button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_WAIT_RELEASE, uiHandleButtonData::cancel, uiBut::flag, uiBlock::handle, KM_PRESS, LEFTMOUSE, uiBut::linkto, wmEvent::mval, uiHandleButtonData::state, wmEvent::type, UI_SELECT, wmEvent::val, VECCOPY2D, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_do_button().
static int ui_do_but_NORMAL (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 3052 of file interface_handlers.c.
References button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_NUM_EDITING, uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, KM_PRESS, LEFTMOUSE, MOUSEMOVE, uiHandleButtonData::region, uiHandleButtonData::state, wmEvent::type, ui_numedit_apply(), ui_numedit_but_NORMAL(), ui_window_to_block(), wmEvent::val, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_do_button().
static int ui_do_but_NUM (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 2493 of file interface_handlers.c.
References uiBut::a1, wmEvent::alt, button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_NUM_EDITING, BUTTON_STATE_TEXT_EDITING, BUTTON_STATE_TEXT_SELECTING, uiHandleButtonData::cancel, wmEvent::ctrl, uiHandleButtonData::dragchange, uiHandleButtonData::draglastx, uiHandleButtonData::dragstartx, ELEM, ELEM3, uiHandleButtonData::escapecancel, ESCKEY, if(), KM_PRESS, LEFTMOUSE, MINUSKEY, MOUSEMOVE, PADENTER, uiHandleButtonData::region, RETKEY, uiAfterFunc::retval, wmEvent::shift, uiBut::softmax, uiBut::softmin, uiHandleButtonData::state, wmEvent::type, ui_do_but_textedit(), ui_do_but_textedit_select(), ui_is_a_warp_but(), ui_is_but_float(), ui_numedit_apply(), ui_numedit_but_NUM(), ui_window_to_block(), wmEvent::val, uiHandleButtonData::value, WHEELDOWNMOUSE, WHEELUPMOUSE, WM_UI_HANDLER_BREAK, WM_UI_HANDLER_CONTINUE, uiBut::x1, and uiBut::x2.
Referenced by ui_do_button().
static int ui_do_but_SCROLL (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 2844 of file interface_handlers.c.
References button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_NUM_EDITING, uiHandleButtonData::cancel, uiHandleButtonData::draglastx, uiHandleButtonData::dragstartx, ELEM, uiHandleButtonData::escapecancel, ESCKEY, KM_PRESS, LEFTMOUSE, MOUSEMOVE, PADENTER, uiHandleButtonData::region, RETKEY, uiAfterFunc::retval, uiHandleButtonData::state, wmEvent::type, ui_numedit_apply(), ui_numedit_but_SLI(), ui_window_to_block(), wmEvent::val, WM_UI_HANDLER_BREAK, WM_UI_HANDLER_CONTINUE, uiBut::x1, uiBut::x2, uiBut::y1, and uiBut::y2.
Referenced by ui_do_button().
static int ui_do_but_SLI (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 2709 of file interface_handlers.c.
References wmEvent::alt, button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_NUM_EDITING, BUTTON_STATE_TEXT_EDITING, BUTTON_STATE_TEXT_SELECTING, uiHandleButtonData::cancel, wmEvent::ctrl, uiHandleButtonData::dragchange, uiHandleButtonData::draglastx, uiHandleButtonData::dragstartx, ELEM, ELEM3, uiHandleButtonData::escapecancel, ESCKEY, if(), KM_PRESS, LEFTMOUSE, MINUSKEY, MOUSEMOVE, PADENTER, uiHandleButtonData::region, RETKEY, uiAfterFunc::retval, wmEvent::shift, SLI, uiBut::softmax, uiBut::softmin, uiHandleButtonData::state, wmEvent::type, uiBut::type, ui_do_but_textedit(), ui_do_but_textedit_select(), ui_is_but_float(), ui_numedit_apply(), ui_numedit_but_SLI(), ui_window_to_block(), wmEvent::val, uiHandleButtonData::value, WHEELDOWNMOUSE, WHEELUPMOUSE, WM_UI_HANDLER_BREAK, WM_UI_HANDLER_CONTINUE, uiBut::x1, and uiBut::x2.
Referenced by ui_do_button().
static int ui_do_but_TEX (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 2199 of file interface_handlers.c.
References button_activate_state(), BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_TEXT_EDITING, BUTTON_STATE_TEXT_SELECTING, wmEvent::ctrl, uiBut::dt, ELEM, EVT_BUT_OPEN, KM_PRESS, LEFTMOUSE, uiHandleButtonData::state, wmEvent::type, ui_do_but_textedit(), ui_do_but_textedit_select(), UI_EMBOSSN, wmEvent::val, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_do_button().
static void ui_do_but_textedit (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 1734 of file interface_handlers.c.
References wmEvent::alt, wmEvent::ascii, uiBut::autocomplete_func, BACKSPACEKEY, BLI_str_utf8_size(), button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_TEXT_SELECTING, uiHandleButtonData::cancel, uiBut::changed, CKEY, wmEvent::ctrl, DELKEY, DOWNARROWKEY, ED_region_tag_redraw(), ELEM3, ENDKEY, uiHandleButtonData::escapecancel, ESCKEY, HOMEKEY, uiBut::icon, uiHandleButtonData::interactive, KM_PRESS, LEFTARROWKEY, LEFTMOUSE, MOUSEMOVE, NULL, NUM, NUMABS, NUMSLI, wmEvent::oskey, PADENTER, PADPERIOD, uiBut::pos, uiHandleButtonData::region, RETKEY, uiAfterFunc::retval, RIGHTARROWKEY, RIGHTMOUSE, uiHandleButtonData::searchbox, uiBut::selend, uiBut::selsta, uiHandleButtonData::selstartx, wmEvent::shift, STRCUR_DIR_NEXT, STRCUR_DIR_PREV, STRCUR_JUMP_ALL, STRCUR_JUMP_DELIM, STRCUR_JUMP_NONE, TABKEY, TRUE, wmEvent::type, uiBut::type, ui_apply_button(), ui_but_contains_pt(), ui_check_but(), ui_searchbox_event(), ui_searchbox_inside(), ui_searchbox_update(), ui_textedit_autocomplete(), ui_textedit_copypaste(), ui_textedit_delete(), ui_textedit_move(), ui_textedit_next_but(), ui_textedit_prev_but(), ui_textedit_set_cursor_pos(), ui_textedit_type_ascii(), ui_textedit_type_buf(), ui_window_to_block(), UPARROWKEY, update(), wmEvent::utf8_buf, wmEvent::val, VKEY, WHEELDOWNMOUSE, WHEELUPMOUSE, WM_UI_HANDLER_BREAK, WM_UI_HANDLER_CONTINUE, wmEvent::x, XKEY, and wmEvent::y.
Referenced by ui_do_but_NUM(), ui_do_but_SLI(), and ui_do_but_TEX().
static void ui_do_but_textedit_select (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 1915 of file interface_handlers.c.
References button_activate_state(), BUTTON_STATE_TEXT_EDITING, ED_region_tag_redraw(), KM_RELEASE, LEFTMOUSE, MOUSEMOVE, uiHandleButtonData::region, uiAfterFunc::retval, wmEvent::type, ui_check_but(), ui_textedit_set_cursor_select(), ui_window_to_block(), wmEvent::val, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_do_but_NUM(), ui_do_but_SLI(), and ui_do_but_TEX().
static int ui_do_but_TOG (bContext * C, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 2222 of file interface_handlers.c.
References button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, ELEM3, KM_PRESS, LEFTMOUSE, PADENTER, RETKEY, uiHandleButtonData::state, uiHandleButtonData::togdual, uiHandleButtonData::togonly, wmEvent::type, wmEvent::val, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_do_button().
static int ui_do_but_TRACKPREVIEW (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 4216 of file interface_handlers.c.
References button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_NUM_EDITING, uiHandleButtonData::cancel, uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, uiHandleButtonData::escapecancel, ESCKEY, KM_PRESS, LEFTMOUSE, MOUSEMOVE, uiHandleButtonData::region, wmEvent::shift, uiHandleButtonData::state, wmEvent::type, ui_numedit_apply(), ui_numedit_but_TRACKPREVIEW(), ui_window_to_block(), wmEvent::val, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_do_button().
static int ui_do_but_VECTORSCOPE (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 4000 of file interface_handlers.c.
References button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_NUM_EDITING, uiHandleButtonData::cancel, uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, uiHandleButtonData::escapecancel, ESCKEY, KM_PRESS, LEFTMOUSE, MOUSEMOVE, uiHandleButtonData::region, uiHandleButtonData::state, wmEvent::type, ui_numedit_apply(), ui_numedit_but_VECTORSCOPE(), ui_window_to_block(), wmEvent::val, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_do_button().
static int ui_do_but_WAVEFORM (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data, wmEvent * event) [static]
Definition at line 3924 of file interface_handlers.c.
References BACKSPACEKEY, button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_NUM_EDITING, uiHandleButtonData::cancel, uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, uiHandleButtonData::escapecancel, ESCKEY, KM_PRESS, LEFTMOUSE, MOUSEMOVE, uiBut::poin, uiHandleButtonData::region, uiHandleButtonData::state, wmEvent::type, ui_numedit_apply(), ui_numedit_but_WAVEFORM(), ui_window_to_block(), wmEvent::val, Scopes::wavefrm_yfac, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_do_button().
static int ui_do_button (bContext * C, uiBlock * block, uiBut * but, wmEvent * event) [static]
Definition at line 4596 of file interface_handlers.c.
References uiBut::a1, uiBut::active, wmEvent::alt, BACKSPACEKEY, BKE_report(), BKE_reportf(), BLOCK, BUT, BUT_COLORBAND, BUT_CURVE, BUT_IMAGE, BUT_NORMAL, BUT_TOGDUAL, BUTM, button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, CHARTAB, CKEY, COL, wmEvent::ctrl, CTX_wm_region(), data, DKEY, ED_region_tag_redraw(), ELEM, ELEM3, EVT_DROP, uiBut::flag, HISTOGRAM, HOTKEYEVT, HSVCIRCLE, HSVCUBE, HSVSLI, ICONROW, ICONTEXTROW, ICONTOG, ICONTOGN, IDPOIN, IKEY, INLINK, ISKEYMODIFIER, KEYEVT, KKEY, KM_MOD_FIRST, KM_PRESS, LABEL, LEFTMOUSE, LINK, LISTBOX, LISTROW, uiBut::lock, uiBut::lockstr, MENU, NULL, NUM, NUMABS, NUMSLI, OPTION, OPTIONN, wmEvent::oskey, uiBut::poin, uiBut::pointype, wmEvent::prevtype, wmEvent::prevval, PROGRESSBAR, PULLDOWN, RETKEY, uiAfterFunc::retval, RIGHTMOUSE, ROUNDBOX, ROW, RPT_WARNING, SCROLL, SEARCH_MENU, wmEvent::shift, SLI, uiHandleButtonData::state, uiBut::str, TEX, TOG, TOG3, TOGBUT, TOGN, TOGR, TRACKPREVIEW, wmEvent::type, uiBut::type, ui_but_anim_add_driver(), ui_but_anim_add_keyingset(), ui_but_anim_delete_keyframe(), ui_but_anim_insert_keyframe(), ui_but_anim_remove_driver(), ui_but_anim_remove_keyingset(), ui_but_copy_paste(), UI_BUT_DISABLED, ui_but_drop(), ui_but_menu(), ui_do_but_BLOCK(), ui_do_but_BUT(), ui_do_but_COLORBAND(), ui_do_but_CURVE(), ui_do_but_EXIT(), ui_do_but_HISTOGRAM(), ui_do_but_HOTKEYEVT(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_do_but_KEYEVT(), ui_do_but_LINK(), ui_do_but_NORMAL(), ui_do_but_NUM(), ui_do_but_SCROLL(), ui_do_but_SLI(), ui_do_but_TEX(), ui_do_but_TOG(), ui_do_but_TRACKPREVIEW(), ui_do_but_VECTORSCOPE(), ui_do_but_WAVEFORM(), UI_GRAD_V_ALT, ui_set_but_default(), wmEvent::val, VECTORSCOPE, VKEY, WAVEFORM, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_button_activate_do(), ui_handle_button_event(), and ui_handle_button_over().
static void ui_handle_button_activate (bContext * C, ARegion * ar, uiBut * but, uiButtonActivateType type) [static]
Definition at line 5518 of file interface_handlers.c.
References uiBut::active, button_activate_exit(), button_activate_init(), uiHandleButtonData::cancel, data, and ui_but_find_activated().
Referenced by button_activate_init(), and ui_handle_menu_event().
static int ui_handle_button_event (bContext * C, wmEvent * event, uiBut * but) [static]
Definition at line 5535 of file interface_handlers.c.
References uiBut::active, uiHandleButtonData::autoopentimer, uiBut::block, button_activate_exit(), button_activate_init(), button_activate_state(), BUTTON_STATE_EXIT, BUTTON_STATE_HIGHLIGHT, BUTTON_STATE_MENU_OPEN, BUTTON_STATE_WAIT_FLASH, BUTTON_STATE_WAIT_RELEASE, button_tooltip_timer_reset(), uiHandleButtonData::cancel, COL, wmEvent::customdata, data, ED_region_tag_redraw(), ELEM, EVT_BUT_CANCEL, uiBut::flag, uiHandleButtonData::flashtimer, INLINK, LINK, uiHandleButtonData::menu, MIDDLEMOUSE, MOUSEMOVE, NULL, uiHandleButtonData::postbut, uiHandleButtonData::posttype, wmEvent::prevx, wmEvent::prevy, uiHandleButtonData::region, uiPopupBlockHandle::region, uiAfterFunc::retval, uiHandleButtonData::state, TIMER, uiHandleButtonData::tooltip, uiHandleButtonData::tooltiptimer, wmEvent::type, uiBut::type, UI_ACTIVE, ui_blocks_set_tooltips(), ui_but_find_mouse_over(), ui_do_button(), ui_mouse_inside_button(), ui_mouse_inside_region(), UI_SELECT, ui_tooltip_create(), WHEELDOWNMOUSE, WHEELUPMOUSE, WINDEACTIVATE, uiHandleButtonData::window, uiHandleButtonData::wm, WM_event_remove_timer(), WM_UI_HANDLER_BREAK, WM_UI_HANDLER_CONTINUE, wmEvent::x, and wmEvent::y.
Referenced by ui_handle_menu_event(), ui_handler_region(), and ui_handler_region_menu().
static int ui_handle_button_over (bContext * C, wmEvent * event, ARegion * ar) [static]
Definition at line 5481 of file interface_handlers.c.
References uiBut::block, button_activate_init(), BUTTON_ACTIVATE_OVER, EVT_BUT_OPEN, MOUSEMOVE, wmEvent::type, ui_but_find_mouse_over(), ui_do_button(), uit_but_find_open_event(), WM_UI_HANDLER_CONTINUE, wmEvent::x, and wmEvent::y.
Referenced by ui_handle_menu_event(), and ui_handler_region().
static void ui_handle_button_return_submenu (bContext * C, wmEvent * event, uiBut * but) [static]
Definition at line 5770 of file interface_handlers.c.
References uiBut::active, uiBut::block, button_activate_exit(), button_activate_state(), BUTTON_STATE_HIGHLIGHT, uiHandleButtonData::cancel, COL, copy_v3_v3(), data, ELEM3, ICONROW, ICONTEXTROW, uiHandleButtonData::interactive, ISKEYBOARD, MENU, uiHandleButtonData::menu, uiPopupBlockHandle::menuretval, MOUSEMOVE, uiHandleButtonData::region, uiPopupBlockHandle::retvalue, uiPopupBlockHandle::retvec, wmEvent::type, uiBut::type, ui_apply_button(), ui_check_but(), ui_mouse_inside_button(), UI_RETURN_CANCEL, UI_RETURN_OK, UI_RETURN_OUT, UI_RETURN_UPDATE, uiHandleButtonData::used_mouse, uiHandleButtonData::value, uiHandleButtonData::vec, wmEvent::x, and wmEvent::y.
Referenced by ui_handle_menu_return_submenu(), and ui_handler_region_menu().
static int ui_handle_list_event (bContext * C, wmEvent * event, ARegion * ar) [static]
Definition at line 5703 of file interface_handlers.c.
References wmEvent::alt, uiBut::block, CLAMPIS, DOWNARROWKEY, ED_region_tag_redraw(), ELEM, KM_PRESS, Panel::list_grip_size, Panel::list_last_len, Panel::list_scroll, Panel::list_size, max, MAX2, min, uiBlock::panel, uiAfterFunc::retval, RNA_property_int_get(), RNA_property_int_range(), RNA_property_int_set(), RNA_property_update(), uiBut::rnapoin, uiBut::rnaprop, wmEvent::shift, wmEvent::type, ui_list_find_mouse_over(), UPARROWKEY, wmEvent::val, WHEELDOWNMOUSE, WHEELUPMOUSE, WM_UI_HANDLER_BREAK, WM_UI_HANDLER_CONTINUE, wmEvent::x, and wmEvent::y.
Referenced by ui_handler_region().
static int ui_handle_menu_event (bContext * C, wmEvent * event, uiPopupBlockHandle * menu, int UNUSEDtopmenu) [static]
Definition at line 5960 of file interface_handlers.c.
References uiBut::active, AKEY, wmEvent::alt, uiBut::bitnr, BKEY, BLI_in_rctf(), BLOCK, uiBlock::block_event_func, BUT, BUTTON_ACTIVATE, BUTTON_ACTIVATE_APPLY, BUTTON_ACTIVATE_OPEN, button_modal_state(), uiBlock::buttons, CKEY, wmEvent::ctrl, uiPopupBlockHandle::ctx_area, uiPopupBlockHandle::ctx_region, CTX_wm_area(), CTX_wm_area_set(), CTX_wm_manager(), CTX_wm_region(), CTX_wm_region_set(), CTX_wm_window(), wmEvent::customdata, PointerRNA::data, uiBlock::direction, DKEY, uiPopupBlockHandle::dotowards, DOWNARROWKEY, EIGHTKEY, EKEY, ELEM, ELEM3, ESCKEY, FALSE, ListBase::first, FIVEKEY, FKEY, uiBlock::flag, FOURKEY, GKEY, HKEY, IKEY, JKEY, KKEY, KM_PRESS, LABEL, LEFTARROWKEY, LEFTMOUSE, LKEY, uiBlock::maxx, uiBlock::maxy, MENU, uiBut::menu_key, MENU_SCROLL_INTERVAL, uiPopupBlockHandle::menuretval, MIDDLEMOUSE, uiBlock::minx, uiBlock::miny, MKEY, MOUSEMOVE, uiSafetyRct::next, uiBut::next, NINEKEY, NKEY, NULL, OKEY, ONEKEY, wmEvent::oskey, PAD0, PAD1, PAD2, PAD3, PAD4, PAD5, PAD6, PAD7, PAD8, PAD9, PADENTER, uiSafetyRct::parent, PKEY, PROP_LAYER, PROP_LAYER_MEMBER, PULLDOWN, QKEY, uiPopupBlockHandle::region, RETKEY, uiAfterFunc::retval, RIGHTARROWKEY, RIGHTMOUSE, RKEY, RNA_property_subtype(), uiBut::rnaindex, uiBut::rnapoin, uiBut::rnaprop, uiBlock::saferct, uiSafetyRct::safety, uiPopupBlockHandle::scrolltimer, SEARCH_MENU, SEPR, SEVENKEY, wmEvent::shift, SIXKEY, SKEY, uiHandleButtonData::state, THREEKEY, TIMER, TKEY, TOGR, TWOKEY, wmEvent::type, uiBut::type, UI_BLOCK_LOOP, UI_BLOCK_MOVEMOUSE_QUIT, UI_BLOCK_NUMSELECT, UI_BLOCK_OUT_1, ui_but_find_activated(), ui_but_first(), ui_but_last(), ui_but_next(), ui_but_prev(), UI_DOWN, ui_handle_button_activate(), ui_handle_button_event(), ui_handle_button_over(), ui_menu_scroll(), ui_menu_scroll_test(), ui_mouse_motion_towards_check(), ui_mouse_motion_towards_init(), UI_RETURN_CANCEL, UI_RETURN_OK, UI_RETURN_OUT, UI_RETURN_POPUP_OK, UI_RETURN_UPDATE, UI_RIGHT, UI_TOP, ui_window_to_block(), ARegion::uiblocks, UKEY, UPARROWKEY, wmEvent::val, VKEY, WHEELDOWNMOUSE, WHEELUPMOUSE, WKEY, WM_event_add_timer(), WM_UI_HANDLER_BREAK, WM_UI_HANDLER_CONTINUE, wmEvent::x, XKEY, wmEvent::y, YKEY, ZEROKEY, and ZKEY.
Referenced by ui_handle_menus_recursive().
static int ui_handle_menu_return_submenu (bContext * C, wmEvent * event, uiPopupBlockHandle * menu) [static]
Definition at line 6318 of file interface_handlers.c.
References uiBut::active, uiPopupBlockHandle::butretval, data, ListBase::first, uiBlock::flag, uiHandleButtonData::menu, uiPopupBlockHandle::menuretval, uiPopupBlockHandle::region, uiHandleButtonData::retval, UI_BLOCK_KEEP_OPEN, ui_but_find_activated(), ui_handle_button_return_submenu(), ui_mouse_motion_towards_init(), UI_RETURN_CANCEL, UI_RETURN_OK, UI_RETURN_UPDATE, ui_window_to_block(), ARegion::uiblocks, update(), WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_handle_menus_recursive().
static int ui_handle_menus_recursive (bContext * C, wmEvent * event, uiPopupBlockHandle * menu) [static]
Definition at line 6367 of file interface_handlers.c.
References uiBut::active, data, uiHandleButtonData::menu, uiPopupBlockHandle::menuretval, NULL, uiPopupBlockHandle::region, uiAfterFunc::retval, TIMER, wmEvent::type, ui_but_find_activated(), ui_handle_menu_event(), ui_handle_menu_return_submenu(), and WM_UI_HANDLER_CONTINUE.
Referenced by ui_handler_popup(), and ui_handler_region_menu().
static int ui_handler_popup (bContext * C, wmEvent * event, void * userdata) [static]
Definition at line 6503 of file interface_handlers.c.
References uiPopupBlockHandle::cancel_func, CTX_wm_window(), wmOperatorType::idname, uiPopupBlockHandle::menuretval, MOUSEMOVE, NULL, uiPopupBlockHandle::opcontext, uiPopupBlockHandle::optype, uiPopupBlockHandle::popup_arg, uiPopupBlockHandle::popup_func, wmEvent::prevx, wmEvent::prevy, uiPopupBlockHandle::region, uiPopupBlockHandle::retvalue, wmEvent::type, ui_apply_but_funcs_after(), ui_blocks_set_tooltips(), ui_handle_menus_recursive(), ui_popup_block_free(), UI_remove_popup_handlers(), UI_RETURN_OK, UI_RETURN_POPUP_OK, WM_operator_name_call(), WM_UI_HANDLER_BREAK, wmEvent::x, and wmEvent::y.
Referenced by UI_add_popup_handlers(), and UI_remove_popup_handlers().
static int ui_handler_region (bContext * C, wmEvent * event, void * UNUSEDuserdata) [static]
Definition at line 6395 of file interface_handlers.c.
References CTX_wm_region(), ListBase::first, MOUSEMOVE, NULL, wmEvent::prevx, wmEvent::prevy, uiAfterFunc::retval, wmEvent::type, ui_apply_but_funcs_after(), ui_blocks_set_tooltips(), ui_but_find_activated(), ui_handle_button_event(), ui_handle_button_over(), ui_handle_list_event(), ui_handler_panel_region(), ARegion::uiblocks, WM_UI_HANDLER_CONTINUE, wmEvent::x, and wmEvent::y.
Referenced by UI_add_region_handlers().
static int ui_handler_region_menu (bContext * C, wmEvent * event, void * userdata) [static]
Referenced by button_activate_state().
static int ui_handler_region_menu (bContext * C, wmEvent * event, void * UNUSEDuserdata) [static]
Definition at line 6453 of file interface_handlers.c.
References uiBut::active, BUTTON_STATE_MENU_OPEN, CTX_wm_menu(), CTX_wm_region(), data, uiHandleButtonData::menu, uiPopupBlockHandle::menuretval, MOUSEMOVE, wmEvent::prevx, wmEvent::prevy, uiAfterFunc::retval, uiHandleButtonData::state, TIMER, wmEvent::type, ui_apply_but_funcs_after(), ui_blocks_set_tooltips(), ui_but_find_activated(), ui_handle_button_event(), ui_handle_button_return_submenu(), ui_handle_menus_recursive(), WM_UI_HANDLER_BREAK, WM_UI_HANDLER_CONTINUE, wmEvent::x, and wmEvent::y.
static void ui_handler_remove_popup (bContext * C, void * userdata) [static]
Definition at line 6539 of file interface_handlers.c.
References ui_apply_but_funcs_after(), and ui_popup_block_free().
Referenced by UI_add_popup_handlers(), and UI_remove_popup_handlers().
static void ui_handler_remove_region (bContext * C, void * UNUSEDuserdata) [static]
Definition at line 6433 of file interface_handlers.c.
References BLI_findindex(), CTX_wm_region(), CTX_wm_screen(), NULL, bScreen::regionbase, ui_apply_but_funcs_after(), ARegion::uiblocks, and uiFreeBlocks().
Referenced by UI_add_region_handlers().
static uiLinkLine* ui_is_a_link (uiBut * from, uiBut * to) [static]
Definition at line 748 of file interface_handlers.c.
References ListBase::first, uiLinkLine::from, uiLink::lines, link(), uiBut::link, uiLinkLine::next, NULL, and uiLinkLine::to.
Referenced by ui_add_link().
static int ui_is_a_warp_but (uiBut * but) [static]
Definition at line 255 of file interface_handlers.c.
References ELEM4, FALSE, HSVCIRCLE, NUM, NUMABS, TRACKPREVIEW, TRUE, uiBut::type, and USER_CONTINUOUS_MOUSE.
Referenced by button_activate_state(), ui_do_but_NUM(), and ui_numedit_but_NUM().
int ui_is_but_utf8 (uiBut * but)
Definition at line 265 of file interface_handlers.c.
References ELEM4, uiBut::flag, PROP_BYTESTRING, PROP_DIRPATH, PROP_FILENAME, PROP_FILEPATH, RNA_property_subtype(), uiBut::rnaprop, and UI_BUT_NO_UTF8.
Referenced by ui_but_copy_paste(), ui_set_but_string(), ui_textedit_end(), and ui_textedit_type_ascii().
static uiBut* ui_list_find_mouse_over (ARegion * ar, int x, int y) [static]
Definition at line 4982 of file interface_handlers.c.
References uiBlock::buttons, ListBase::first, ListBase::last, LISTBOX, uiBlock::next, NULL, uiBut::prev, uiBut::type, ui_but_contains_pt(), ui_mouse_inside_region(), ui_window_to_block(), and ARegion::uiblocks.
Referenced by ui_handle_list_event().
static int ui_menu_scroll (ARegion * ar, uiBlock * block, int my) [static]
Definition at line 5903 of file interface_handlers.c.
References uiBlock::buttons, ED_region_tag_redraw(), ListBase::first, uiBut::flag, ListBase::last, uiBut::next, NULL, ui_but_next(), ui_but_prev(), ui_menu_scroll_test(), ui_popup_block_scrolltest(), UI_SCROLLED, uiBut::y1, and uiBut::y2.
Referenced by ui_handle_menu_event().
static char ui_menu_scroll_test (uiBlock * block, int my) [static]
Definition at line 5890 of file interface_handlers.c.
References uiBlock::flag, uiBlock::maxy, UI_BLOCK_CLIPBOTTOM, and UI_BLOCK_CLIPTOP.
Referenced by ui_handle_menu_event(), and ui_menu_scroll().
static int ui_mouse_inside_button (ARegion * ar, uiBut * but, int x, int y) [static]
Definition at line 4925 of file interface_handlers.c.
References uiBut::block, ui_but_contains_pt(), ui_mouse_inside_region(), and ui_window_to_block().
Referenced by ui_apply_but_LINK(), ui_do_but_HOTKEYEVT(), ui_handle_button_event(), and ui_handle_button_return_submenu().
static int ui_mouse_inside_region (ARegion * ar, int x, int y) [static]
Definition at line 4871 of file interface_handlers.c.
References uiBlock::auto_open, BLI_in_rcti(), FALSE, ListBase::first, View2D::hor, View2D::mask, uiBlock::next, View2D::scroll, ui_window_to_region(), ARegion::uiblocks, ARegion::v2d, V2D_SCROLL_BOTTOM, V2D_SCROLL_BOTTOM_O, V2D_SCROLL_HORIZONTAL_FULLR, V2D_SCROLL_HORIZONTAL_HIDE, V2D_SCROLL_LEFT, V2D_SCROLL_RIGHT, V2D_SCROLL_TOP, V2D_SCROLL_VERTICAL_FULLR, V2D_SCROLL_VERTICAL_HIDE, View2D::vert, ARegion::winrct, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_but_find_mouse_over(), ui_handle_button_event(), ui_list_find_mouse_over(), and ui_mouse_inside_button().
static int ui_mouse_motion_towards_check (uiBlock * block, uiPopupBlockHandle * menu, int mx, int my) [static]
Definition at line 5843 of file interface_handlers.c.
References BUTTON_MOUSE_TOWARDS_THRESH, uiPopupBlockHandle::dotowards, isect_point_tri_v2(), len_v2v2(), uiBlock::maxx, uiBlock::maxy, uiBlock::minx, uiBlock::miny, PIL_check_seconds_timer(), uiPopupBlockHandle::towardstime, uiPopupBlockHandle::towardsx, and uiPopupBlockHandle::towardsy.
Referenced by ui_handle_menu_event().
static void ui_mouse_motion_towards_init (uiPopupBlockHandle * menu, int mx, int my, int force) [static]
Definition at line 5829 of file interface_handlers.c.
References DBL_MAX, uiPopupBlockHandle::dotowards, PIL_check_seconds_timer(), uiPopupBlockHandle::towardstime, uiPopupBlockHandle::towardsx, and uiPopupBlockHandle::towardsy.
Referenced by ui_handle_menu_event(), and ui_handle_menu_return_submenu().
static void ui_ndofedit_but_HSVCIRCLE (uiBut * but, uiHandleButtonData * data, wmNDOFMotionData * ndof, int shift) [static]
Definition at line 3349 of file interface_handlers.c.
References uiBut::a2, atan2f, uiBut::block, CLAMP(), cosf, wmNDOFMotionData::dt, uiBut::flag, fmodf, hsv_to_rgb(), len_v2(), M_PI, mul_v3_fl(), normalize_v3(), rgb_to_hsv_compat(), wmNDOFMotionData::rx, wmNDOFMotionData::ry, wmNDOFMotionData::rz, sinf, ui_block_hsv_get(), UI_BUT_COLOR_LOCK, UI_BUT_VEC_SIZE_LOCK, ui_get_but_vectorf(), ui_set_but_vectorf(), and uiHandleButtonData::vec.
Referenced by ui_do_but_HSVCIRCLE().
static void ui_ndofedit_but_HSVCUBE (uiBut * but, uiHandleButtonData * data, wmNDOFMotionData * ndof, int shift) [static]
Definition at line 3161 of file interface_handlers.c.
References uiBut::a1, assert, BLI_PR_NONE, uiBut::block, CLAMP(), uiBlock::color_profile, copy_v3_v3(), wmNDOFMotionData::dt, hsv_to_rgb(), if(), PROP_COLOR_GAMMA, rgb_to_hsv_compat(), RNA_property_subtype(), uiBut::rnaprop, wmNDOFMotionData::rx, wmNDOFMotionData::ry, uiBut::softmax, uiBut::softmin, srgb_to_linearrgb(), ui_block_hsv_get(), ui_get_but_vectorf(), UI_GRAD_H, UI_GRAD_HS, UI_GRAD_HV, UI_GRAD_S, UI_GRAD_SV, UI_GRAD_V, UI_GRAD_V_ALT, ui_set_but_vectorf(), and uiHandleButtonData::vec.
Referenced by ui_do_but_HSVCUBE().
static void ui_numedit_apply (bContext * C, uiBlock * block, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 1992 of file interface_handlers.c.
References ED_region_tag_redraw(), uiHandleButtonData::interactive, uiHandleButtonData::region, ui_apply_button(), and ui_check_but().
Referenced by ui_do_but_COLORBAND(), ui_do_but_CURVE(), ui_do_but_HISTOGRAM(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_do_but_NORMAL(), ui_do_but_NUM(), ui_do_but_SCROLL(), ui_do_but_SLI(), ui_do_but_TRACKPREVIEW(), ui_do_but_VECTORSCOPE(), and ui_do_but_WAVEFORM().
static float ui_numedit_apply_snap (int temp, float softmin, float softmax, int snap) [static]
Definition at line 2333 of file interface_handlers.c.
Referenced by ui_numedit_but_NUM().
static float ui_numedit_apply_snapf (uiBut * but, float tempf, float softmin, float softmax, float softrange, int snap) [static]
Definition at line 2287 of file interface_handlers.c.
References B_UNIT_AREA, B_UNIT_LENGTH, B_UNIT_VOLUME, uiBut::block, bUnit_BaseScalar(), bUnit_IsValid(), ELEM3, floorf, RNA_SUBTYPE_UNIT_VALUE, UnitSettings::scale_length, UnitSettings::system, ui_is_but_unit(), uiButGetUnitType(), and uiBlock::unit.
Referenced by ui_numedit_but_NUM().
static void ui_numedit_begin (uiBut * but, uiHandleButtonData * data) [static]
Definition at line 1944 of file interface_handlers.c.
References BUT_COLORBAND, BUT_CURVE, BUT_NORMAL, uiHandleButtonData::coba, copy_v3_v3(), uiHandleButtonData::dragchange, uiHandleButtonData::dragf, uiHandleButtonData::dragfstart, uiHandleButtonData::draglock, uiBut::editcoba, uiBut::editcumap, uiBut::editval, uiBut::editvec, ELEM3, HSVCIRCLE, HSVCUBE, uiHandleButtonData::origvalue, uiHandleButtonData::origvec, uiBut::poin, uiBut::softmax, uiBut::softmin, uiHandleButtonData::startvalue, uiBut::type, ui_get_but_val(), ui_get_but_vectorf(), uiHandleButtonData::value, and uiHandleButtonData::vec.
Referenced by button_activate_state().
static int ui_numedit_but_COLORBAND (uiBut * but, uiHandleButtonData * data, int mx) [static]
Definition at line 3497 of file interface_handlers.c.
References CLAMP(), uiHandleButtonData::coba, colorband_update_sort(), ColorBand::cur, ColorBand::data, uiHandleButtonData::dragcbd, uiHandleButtonData::draglastx, CBData::pos, uiBut::x1, and uiBut::x2.
Referenced by ui_do_but_COLORBAND().
static int ui_numedit_but_CURVE (uiBut * but, uiHandleButtonData * data, int snap, int mx, int my) [static]
Definition at line 3578 of file interface_handlers.c.
References CurveMapping::clipr, CurveMapping::cm, CUMA_DO_CLIP, CurveMapping::cur, CurveMapping::curr, curvemapping_changed(), uiHandleButtonData::dragchange, uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragsel, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, CurveMapping::flag, floorf, len_v2(), uiBut::poin, SELECT, uiBut::x1, uiBut::x2, rctf::xmax, rctf::xmin, uiBut::y1, uiBut::y2, rctf::ymax, and rctf::ymin.
Referenced by ui_do_but_CURVE().
static int ui_numedit_but_HISTOGRAM (uiBut * but, uiHandleButtonData * data, int mx, int my) [static]
Definition at line 3808 of file interface_handlers.c.
References CLAMP(), uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, Histogram::height, if(), in_scope_resize_zone(), MIN2, uiBut::poin, powf, uiBut::y1, uiBut::y2, and Histogram::ymax.
Referenced by ui_do_but_HISTOGRAM().
static int ui_numedit_but_HSVCIRCLE (uiBut * but, uiHandleButtonData * data, int mx, int my, int shift) [static]
Definition at line 3302 of file interface_handlers.c.
References uiBut::a2, uiBut::block, copy_v3_v3(), uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, uiBut::flag, hsv_to_rgb(), mul_v3_fl(), normalize_v3(), rgb_to_hsv_compat(), sqrt3f(), ui_block_hsv_get(), UI_BUT_COLOR_CUBIC, UI_BUT_COLOR_LOCK, UI_BUT_VEC_SIZE_LOCK, ui_get_but_vectorf(), ui_hsvcircle_vals_from_pos(), ui_set_but_vectorf(), USER_CONTINUOUS_MOUSE, uiBut::x1, uiBut::x2, rcti::xmax, rcti::xmin, uiBut::y1, uiBut::y2, rcti::ymax, and rcti::ymin.
Referenced by ui_do_but_HSVCIRCLE().
static int ui_numedit_but_HSVCUBE (uiBut * but, uiHandleButtonData * data, int mx, int my) [static]
Definition at line 3091 of file interface_handlers.c.
References uiBut::a1, assert, BLI_PR_NONE, uiBut::block, CLAMP(), uiBlock::color_profile, copy_v3_v3(), uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, hsv_to_rgb(), if(), PROP_COLOR_GAMMA, rgb_to_hsv_compat(), RNA_property_subtype(), uiBut::rnaprop, uiBut::softmax, uiBut::softmin, srgb_to_linearrgb(), ui_block_hsv_get(), ui_get_but_vectorf(), UI_GRAD_H, UI_GRAD_HS, UI_GRAD_HV, UI_GRAD_S, UI_GRAD_SV, UI_GRAD_V, UI_GRAD_V_ALT, uiHandleButtonData::vec, uiBut::x1, uiBut::x2, uiBut::y1, and uiBut::y2.
Referenced by ui_do_but_HSVCUBE().
static int ui_numedit_but_NORMAL (uiBut * but, uiHandleButtonData * data, int mx, int my) [static]
Definition at line 2993 of file interface_handlers.c.
References uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, normalize_v3(), uiHandleButtonData::origvec, sqrt(), sqrtf, uiHandleButtonData::vec, uiBut::x1, and uiBut::x2.
Referenced by ui_do_but_NORMAL().
static int ui_numedit_but_NUM (uiBut * but, uiHandleButtonData * data, float fac, int snap, int mx) [static]
Definition at line 2352 of file interface_handlers.c.
References uiBut::a1, abs(), CLAMP(), uiHandleButtonData::dragchange, uiHandleButtonData::dragf, uiHandleButtonData::draglastx, uiHandleButtonData::draglock, uiHandleButtonData::dragstartx, fabsf, floorf, if(), powf, uiBut::softmax, uiBut::softmin, uiHandleButtonData::startvalue, ui_is_a_warp_but(), ui_is_but_float(), ui_numedit_apply_snap(), ui_numedit_apply_snapf(), and uiHandleButtonData::value.
Referenced by ui_do_but_NUM().
static int ui_numedit_but_SLI (uiBut * but, uiHandleButtonData * data, int shift, int ctrl, int mx) [static]
Definition at line 2636 of file interface_handlers.c.
References uiBut::a1, uiBut::aspect, CLAMP(), uiHandleButtonData::dragchange, uiHandleButtonData::dragfstart, uiHandleButtonData::dragstartx, floorf, HSVSLI, NUMSLI, SCROLL, size(), uiBut::softmax, uiBut::softmin, uiBut::type, ui_is_but_float(), uiHandleButtonData::value, uiBut::x1, uiBut::x2, uiBut::y1, and uiBut::y2.
Referenced by ui_do_but_SCROLL(), and ui_do_but_SLI().
static int ui_numedit_but_TRACKPREVIEW (bContext * C, uiBut * but, uiHandleButtonData * data, int mx, int my, int shift) [static]
Definition at line 4177 of file interface_handlers.c.
References BKE_tracking_ensure_marker(), uiBut::block, uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, MovieTrackingMarker::flag, MovieClipScopes::framenr, MovieTrackingMarker::framenr, if(), in_scope_resize_zone(), MovieClipScopes::marker, MARKER_DISABLED, MARKER_TRACKED, uiBlock::maxx, uiBlock::maxy, uiBlock::minx, uiBlock::miny, NA_EDITED, NC_MOVIECLIP, NULL, MovieClipScopes::ok, uiBut::poin, MovieTrackingMarker::pos, MovieClipScopes::slide_scale, MovieClipScopes::track, MovieClipScopes::track_preview_height, WM_event_add_notifier(), uiBut::y1, and uiBut::y2.
Referenced by ui_do_but_TRACKPREVIEW().
static int ui_numedit_but_VECTORSCOPE (uiBut * but, uiHandleButtonData * data, int mx, int my) [static]
Definition at line 3976 of file interface_handlers.c.
References uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, if(), in_scope_resize_zone(), uiBut::poin, Scopes::vecscope_height, uiBut::y1, and uiBut::y2.
Referenced by ui_do_but_VECTORSCOPE().
static int ui_numedit_but_WAVEFORM (uiBut * but, uiHandleButtonData * data, int mx, int my) [static]
Definition at line 3892 of file interface_handlers.c.
References CLAMP(), uiHandleButtonData::draglastx, uiHandleButtonData::draglasty, uiHandleButtonData::dragstartx, uiHandleButtonData::dragstarty, if(), in_scope_resize_zone(), uiBut::poin, Scopes::wavefrm_height, Scopes::wavefrm_yfac, uiBut::y1, and uiBut::y2.
Referenced by ui_do_but_WAVEFORM().
static void ui_numedit_end (uiBut * but, uiHandleButtonData * data) [static]
Definition at line 1978 of file interface_handlers.c.
References uiHandleButtonData::dragcbd, uiHandleButtonData::dragchange, uiHandleButtonData::draglastx, uiHandleButtonData::dragsel, uiHandleButtonData::dragstartx, uiBut::editcoba, uiBut::editcumap, uiBut::editval, uiBut::editvec, and NULL.
Referenced by button_activate_state().
void UI_remove_popup_handlers (ListBase * handlers, uiPopupBlockHandle * popup)
Definition at line 6561 of file interface_handlers.c.
References ui_handler_popup(), ui_handler_remove_popup(), and WM_event_remove_ui_handler().
Referenced by ui_handler_popup(), and uiPupBlockClose().
static int ui_textedit_autocomplete (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 1520 of file interface_handlers.c.
References uiBut::autocomplete_func, uiBut::autofunc_arg, uiBut::pos, uiHandleButtonData::searchbox, uiBut::selend, uiBut::selsta, str, uiHandleButtonData::str, strlen(), and ui_searchbox_autocomplete().
Referenced by ui_do_but_textedit().
static void ui_textedit_begin (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 1608 of file interface_handlers.c.
References BC_TEXTEDITCURSOR, BLI_strdupn(), CTX_wm_window(), uiBut::editstr, ELEM3, len(), uiHandleButtonData::maxlen, MEM_callocN(), MEM_freeN(), NULL, NUM, NUMABS, NUMSLI, uiHandleButtonData::origstr, uiBut::pos, uiHandleButtonData::region, SEARCH_MENU, uiHandleButtonData::searchbox, uiBut::selend, uiHandleButtonData::selextend, uiBut::selsta, uiHandleButtonData::selstartx, uiHandleButtonData::str, strlen(), uiBut::type, ui_check_but(), ui_convert_to_unit_alt_name(), ui_get_but_string(), ui_get_but_string_max_length(), ui_searchbox_create(), ui_searchbox_update(), and WM_cursor_modal().
Referenced by button_activate_state().
static int ui_textedit_copypaste (uiBut * but, uiHandleButtonData * data, int paste, int copy, int cut) [static]
Definition at line 1538 of file interface_handlers.c.
References i, len(), uiHandleButtonData::maxlen, MEM_freeN(), p, uiBut::pos, uiBut::selend, uiBut::selsta, str, uiHandleButtonData::str, strlen(), UI_MAX_DRAW_STR, ui_textedit_delete_selection(), WM_clipboard_text_get(), and WM_clipboard_text_set().
Referenced by ui_do_but_textedit().
static int ui_textedit_delete (uiBut * but, uiHandleButtonData * data, int direction, strCursorJumpType jump) [static]
Definition at line 1474 of file interface_handlers.c.
References BLI_str_cursor_step_utf8(), len(), uiBut::pos, uiBut::selend, uiBut::selsta, step(), str, uiHandleButtonData::str, STRCUR_JUMP_ALL, strlen(), and ui_textedit_delete_selection().
Referenced by ui_do_but_textedit().
static int ui_textedit_delete_selection (uiBut * but, uiHandleButtonData * data) [static]
Definition at line 1233 of file interface_handlers.c.
References len(), uiBut::pos, uiBut::selend, uiBut::selsta, str, uiHandleButtonData::str, and strlen().
Referenced by ui_textedit_copypaste(), ui_textedit_delete(), and ui_textedit_type_buf().
static void ui_textedit_end (bContext * C, uiBut * but, uiHandleButtonData * data) [static]
Definition at line 1650 of file interface_handlers.c.
References BLI_utf8_invalid_strip(), uiHandleButtonData::cancel, CTX_wm_window(), uiBut::editstr, NULL, uiBut::pos, uiHandleButtonData::searchbox, strlen(), ui_is_but_utf8(), ui_searchbox_apply(), ui_searchbox_free(), and WM_cursor_restore().
Referenced by button_activate_state().
static void ui_textedit_move (uiBut * but, uiHandleButtonData * data, strCursorJumpDirection direction, int select, strCursorJumpType jump) [static]
Definition at line 1398 of file interface_handlers.c.
References BLI_str_cursor_step_utf8(), EXTEND_LEFT, EXTEND_RIGHT, len(), uiBut::pos, uiBut::selend, uiHandleButtonData::selextend, uiBut::selsta, str, uiHandleButtonData::str, STRCUR_JUMP_ALL, strlen(), SWAP, and ui_check_but().
Referenced by ui_do_but_textedit().
static void ui_textedit_next_but (uiBlock * block, uiBut * actbut, uiHandleButtonData * data) [static]
Definition at line 1677 of file interface_handlers.c.
References BUTTON_ACTIVATE_TEXT_EDITING, uiBlock::buttons, ELEM4, ELEM7, ListBase::first, uiBut::flag, HSVSLI, IDPOIN, LABEL, LISTBOX, uiBut::next, NUM, NUMABS, NUMSLI, uiHandleButtonData::postbut, uiHandleButtonData::posttype, ROUNDBOX, SEARCH_MENU, SEPR, TEX, uiBut::type, and UI_BUT_DISABLED.
Referenced by ui_do_but_textedit().
static void ui_textedit_prev_but (uiBlock * block, uiBut * actbut, uiHandleButtonData * data) [static]
Definition at line 1705 of file interface_handlers.c.
References BUTTON_ACTIVATE_TEXT_EDITING, uiBlock::buttons, ELEM4, ELEM7, uiBut::flag, HSVSLI, IDPOIN, LABEL, ListBase::last, LISTBOX, NUM, NUMABS, NUMSLI, uiHandleButtonData::postbut, uiHandleButtonData::posttype, uiBut::prev, ROUNDBOX, SEARCH_MENU, SEPR, TEX, uiBut::type, and UI_BUT_DISABLED.
Referenced by ui_do_but_textedit().
static void ui_textedit_set_cursor_pos (uiBut * but, uiHandleButtonData * data, short x) [static]
Definition at line 1248 of file interface_handlers.c.
References uiBlock::aspect, BLF_disable(), BLF_enable(), BLF_KERNING_DEFAULT, BLF_width(), BLI_str_cursor_step_prev_utf8(), BLI_strncpy(), uiBut::block, uiBut::drawstr, ELEM, uiBut::flag, i, uiFontStyle::kerning, uiHandleButtonData::maxlen, MEM_callocN(), MEM_freeN(), NUM, NUMSLI, uiBut::ofs, uiBut::pos, SEARCH_MENU, sqrtf, strlen(), TEX, TRUE, uiBut::type, UI_DPI_ICON_SIZE, UI_GetStyle(), UI_HAS_ICON, uiFontStyle::uifont_id, uiStyleFontSet(), uiStyle::widget, uiBut::x1, uiBut::y1, and uiBut::y2.
Referenced by ui_do_but_textedit(), and ui_textedit_set_cursor_select().
static void ui_textedit_set_cursor_select (uiBut * but, uiHandleButtonData * data, short x) [static]
Definition at line 1338 of file interface_handlers.c.
References EXTEND_LEFT, EXTEND_RIGHT, uiBut::pos, uiBut::selend, uiHandleButtonData::selextend, uiBut::selsta, uiHandleButtonData::selstartx, ui_check_but(), and ui_textedit_set_cursor_pos().
Referenced by ui_do_but_textedit_select().
static int ui_textedit_type_ascii (uiBut * but, uiHandleButtonData * data, char ascii) [static]
Definition at line 1383 of file interface_handlers.c.
References BLI_str_utf8_size(), ui_is_but_utf8(), and ui_textedit_type_buf().
Referenced by ui_do_but_textedit().
static int ui_textedit_type_buf (uiBut * but, uiHandleButtonData * data, const char * utf8_buf, int utf8_buf_len) [static]
Definition at line 1354 of file interface_handlers.c.
References len(), uiHandleButtonData::maxlen, uiBut::pos, uiBut::selend, uiBut::selsta, step(), str, uiHandleButtonData::str, strlen(), and ui_textedit_delete_selection().
Referenced by ui_do_but_textedit(), and ui_textedit_type_ascii().
uiBut* uiContextActiveButton (const struct bContext * C)
Definition at line 5353 of file interface_handlers.c.
References NULL, and ui_context_button_active().
wmOperator* uiContextActiveOperator (const struct bContext * C) [read]
Definition at line 5390 of file interface_handlers.c.
References CTX_wm_region(), CTX_wm_screen(), ListBase::first, ARegion::next, uiBlock::next, NULL, bScreen::regionbase, uiBlock::ui_operator, and ARegion::uiblocks.
Referenced by ed_screen_context().
void uiContextActiveProperty (const bContext * C, struct PointerRNA * ptr, struct PropertyRNA ** prop, int * index)
Definition at line 5359 of file interface_handlers.c.
References PointerRNA::data, NULL, uiBut::rnaindex, uiBut::rnapoin, uiBut::rnaprop, and ui_context_rna_button_active().
void uiContextActivePropertyHandle (bContext * C)
Definition at line 5376 of file interface_handlers.c.
References uiBut::block, uiBlock::handle_func, uiBlock::handle_func_arg, and ui_context_rna_button_active().
Referenced by reset_default_button_exec().
void uiContextAnimUpdate (const bContext * C)
Definition at line 5428 of file interface_handlers.c.
References uiBut::active, uiBlock::buttons, RenderData::cfra, CTX_data_scene(), CTX_wm_region(), data, ED_region_tag_redraw(), ListBase::first, uiBut::flag, uiHandleButtonData::menu, uiBut::next, uiBlock::next, NULL, Scene::r, uiPopupBlockHandle::region, ui_but_anim_flag(), UI_BUT_LAST_ACTIVE, and ARegion::uiblocks.
void uiFreeActiveButtons (const bContext * C, bScreen * screen)
Definition at line 4822 of file interface_handlers.c.
References uiBut::active, bScreen::areabase, BUTTON_STATE_HIGHLIGHT, data, ListBase::first, uiHandleButtonData::menu, ARegion::next, ScrArea::next, NULL, ScrArea::regionbase, uiHandleButtonData::searchbox, uiHandleButtonData::state, ui_but_find_activated(), and ui_button_active_free().
static uiBut* uit_but_find_open_event (ARegion * ar, wmEvent * event) [static]
Definition at line 5468 of file interface_handlers.c.
References uiBlock::buttons, wmEvent::customdata, ListBase::first, uiBut::next, uiBlock::next, NULL, and ARegion::uiblocks.
Referenced by ui_handle_button_over().
Variable Documentation
ListBase UIAfterFuncs = {NULL, NULL} [static]
Definition at line 278 of file interface_handlers.c.
Referenced by ui_apply_but_funcs_after().