Blender: pointcache.c File Reference
pointcache.c File Reference
blenkernel
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include "MEM_guardedalloc.h"
#include "DNA_ID.h"
#include "DNA_cloth_types.h"
#include "DNA_dynamicpaint_types.h"
#include "DNA_modifier_types.h"
#include "DNA_object_types.h"
#include "DNA_object_force.h"
#include "DNA_particle_types.h"
#include "DNA_scene_types.h"
#include "DNA_smoke_types.h"
#include "BLI_blenlib.h"
#include "BLI_threads.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "PIL_time.h"
#include "WM_api.h"
#include "BKE_anim.h"
#include "BKE_blender.h"
#include "BKE_cloth.h"
#include "BKE_depsgraph.h"
#include "BKE_dynamicpaint.h"
#include "BKE_global.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_object.h"
#include "BKE_particle.h"
#include "BKE_pointcache.h"
#include "BKE_scene.h"
#include "BKE_smoke.h"
#include "BKE_softbody.h"
#include "BKE_utildefines.h"
#include "BIK_api.h"
#include <dirent.h>
#include <unistd.h>
Classes
struct ptcache_bake_data
Defines
#define LZO_OUT_LEN(size) ((size) + (size) / 16 + 64 + 3)
#define PTCACHE_DATA_FROM(data, type, from) if (data[type]) { memcpy(data[type], from, ptcache_data_size[type]); }
#define PTCACHE_DATA_TO(data, type, index, to) if (data[type]) { memcpy(to, (char*)data[type] + (index ? index * ptcache_data_size[type] : 0), ptcache_data_size[type]); }
#define DURIAN_POINTCACHE_LIB_OK 1
#define DPAINT_CACHE_VERSION "1.01"
#define MAX_PTCACHE_PATH FILE_MAX
#define MAX_PTCACHE_FILE ((FILE_MAX)*2)
Functions
static int ptcache_file_compressed_read (PTCacheFile *pf, unsigned char *result, unsigned int len)
static int ptcache_file_compressed_write (PTCacheFile *pf, unsigned char *in, unsigned int in_len, unsigned char *out, int mode)
static int ptcache_file_write (PTCacheFile *pf, const void *f, unsigned int tot, unsigned int size)
static int ptcache_file_read (PTCacheFile *pf, void *f, unsigned int tot, unsigned int size)
static int ptcache_basic_header_read (PTCacheFile *pf)
static int ptcache_basic_header_write (PTCacheFile *pf)
static int ptcache_softbody_write (int index, void *soft_v, void **data, int UNUSED(cfra))
static void ptcache_softbody_read (int index, void *soft_v, void **data, float UNUSED(cfra), float *old_data)
static void ptcache_softbody_interpolate (int index, void *soft_v, void **data, float cfra, float cfra1, float cfra2, float *old_data)
static int ptcache_softbody_totpoint (void *soft_v, int UNUSED(cfra))
void BKE_ptcache_make_particle_key (ParticleKey *key, int index, void **data, float time)
static int ptcache_particle_write (int index, void *psys_v, void **data, int cfra)
static void ptcache_particle_read (int index, void *psys_v, void **data, float cfra, float *old_data)
static void ptcache_particle_interpolate (int index, void *psys_v, void **data, float cfra, float cfra1, float cfra2, float *old_data)
static int ptcache_particle_totpoint (void *psys_v, int UNUSED(cfra))
static int ptcache_particle_totwrite (void *psys_v, int cfra)
static void ptcache_particle_extra_write (void *psys_v, PTCacheMem *pm, int UNUSED(cfra))
static void ptcache_particle_extra_read (void *psys_v, PTCacheMem *pm, float UNUSED(cfra))
static int ptcache_cloth_write (int index, void *cloth_v, void **data, int UNUSED(cfra))
static void ptcache_cloth_read (int index, void *cloth_v, void **data, float UNUSED(cfra), float *old_data)
static void ptcache_cloth_interpolate (int index, void *cloth_v, void **data, float cfra, float cfra1, float cfra2, float *old_data)
static int ptcache_cloth_totpoint (void *cloth_v, int UNUSED(cfra))
static int ptcache_smoke_totpoint (void *UNUSED(smoke_v), int UNUSED(cfra))
static int ptcache_smoke_read (PTCacheFile *UNUSED(pf), void *UNUSED(smoke_v))
static int ptcache_smoke_write (PTCacheFile *UNUSED(pf), void *UNUSED(smoke_v))
static int ptcache_dynamicpaint_totpoint (void *sd, int UNUSED(cfra))
static int ptcache_dynamicpaint_write (PTCacheFile *pf, void *dp_v)
static int ptcache_dynamicpaint_read (PTCacheFile *pf, void *dp_v)
void BKE_ptcache_id_from_softbody (PTCacheID *pid, Object *ob, SoftBody *sb)
void BKE_ptcache_id_from_particles (PTCacheID *pid, Object *ob, ParticleSystem *psys)
void BKE_ptcache_id_from_cloth (PTCacheID *pid, Object *ob, ClothModifierData *clmd)
void BKE_ptcache_id_from_smoke (PTCacheID *pid, struct Object *ob, struct SmokeModifierData *smd)
void BKE_ptcache_id_from_dynamicpaint (PTCacheID *pid, Object *ob, DynamicPaintSurface *surface)
void BKE_ptcache_ids_from_object (ListBase *lb, Object *ob, Scene *scene, int duplis)
static int ptcache_path (PTCacheID *pid, char *filename)
static int ptcache_filename (PTCacheID *pid, char *filename, int cfra, short do_path, short do_ext)
static PTCacheFile * ptcache_file_open (PTCacheID *pid, int mode, int cfra)
static void ptcache_file_close (PTCacheFile *pf)
static int ptcache_file_data_read (PTCacheFile *pf)
static int ptcache_file_data_write (PTCacheFile *pf)
static int ptcache_file_header_begin_read (PTCacheFile *pf)
static int ptcache_file_header_begin_write (PTCacheFile *pf)
int BKE_ptcache_data_size (int data_type)
static void ptcache_file_pointers_init (PTCacheFile *pf)
int BKE_ptcache_mem_index_find (PTCacheMem *pm, unsigned int index)
void BKE_ptcache_mem_pointers_init (PTCacheMem *pm)
void BKE_ptcache_mem_pointers_incr (PTCacheMem *pm)
int BKE_ptcache_mem_pointers_seek (int point_index, PTCacheMem *pm)
static void ptcache_data_alloc (PTCacheMem *pm)
static void ptcache_data_free (PTCacheMem *pm)
static void ptcache_data_copy (void *from[], void *to[])
static void ptcache_extra_free (PTCacheMem *pm)
static int ptcache_old_elemsize (PTCacheID *pid)
static void ptcache_find_frames_around (PTCacheID *pid, unsigned int frame, int *fra1, int *fra2)
static PTCacheMem * ptcache_disk_frame_to_mem (PTCacheID *pid, int cfra)
static int ptcache_mem_frame_to_disk (PTCacheID *pid, PTCacheMem *pm)
static int ptcache_read_stream (PTCacheID *pid, int cfra)
static int ptcache_read (PTCacheID *pid, int cfra)
static int ptcache_interpolate (PTCacheID *pid, float cfra, int cfra1, int cfra2)
int BKE_ptcache_read (PTCacheID *pid, float cfra)
static int ptcache_write_stream (PTCacheID *pid, int cfra, int totpoint)
static int ptcache_write (PTCacheID *pid, int cfra, int overwrite)
static int ptcache_write_needed (PTCacheID *pid, int cfra, int *overwrite)
int BKE_ptcache_write (PTCacheID *pid, unsigned int cfra)
void BKE_ptcache_id_clear (PTCacheID *pid, int mode, unsigned int cfra)
int BKE_ptcache_id_exist (PTCacheID *pid, int cfra)
void BKE_ptcache_id_time (PTCacheID *pid, Scene *scene, float cfra, int *startframe, int *endframe, float *timescale)
int BKE_ptcache_id_reset (Scene *scene, PTCacheID *pid, int mode)
int BKE_ptcache_object_reset (Scene *scene, Object *ob, int mode)
void BKE_ptcache_remove (void)
void BKE_ptcache_set_continue_physics (Main *bmain, Scene *scene, int enable)
int BKE_ptcache_get_continue_physics (void)
PointCache * BKE_ptcache_add (ListBase *ptcaches)
void BKE_ptcache_free_mem (ListBase *mem_cache)
void BKE_ptcache_free (PointCache *cache)
void BKE_ptcache_free_list (ListBase *ptcaches)
static PointCache * ptcache_copy (PointCache *cache)
PointCache * BKE_ptcache_copy_list (ListBase *ptcaches_new, ListBase *ptcaches_old)
void BKE_ptcache_quick_cache_all (Main *bmain, Scene *scene)
static void ptcache_dt_to_str (char *str, double dtime)
static void * ptcache_bake_thread (void *ptr)
void BKE_ptcache_bake (PTCacheBaker *baker)
void BKE_ptcache_disk_to_mem (PTCacheID *pid)
void BKE_ptcache_mem_to_disk (PTCacheID *pid)
void BKE_ptcache_toggle_disk_cache (PTCacheID *pid)
void BKE_ptcache_disk_cache_rename (PTCacheID *pid, const char *name_src, const char *name_dst)
void BKE_ptcache_load_external (PTCacheID *pid)
void BKE_ptcache_update_info (PTCacheID *pid)
void BKE_ptcache_validate (PointCache *cache, int framenr)
void BKE_ptcache_invalidate (PointCache *cache)
Variables
static int ptcache_data_size []
static int ptcache_extra_datasize []
static int CONTINUE_PHYSICS = 0
Detailed Description
Definition in file pointcache.c.
Define Documentation
#define DPAINT_CACHE_VERSION "1.01"
Definition at line 675 of file pointcache.c.
Referenced by ptcache_dynamicpaint_read(), and ptcache_dynamicpaint_write().
#define DURIAN_POINTCACHE_LIB_OK 1
Definition at line 106 of file pointcache.c.
#define LZO_OUT_LEN (size) ((size) + (size) / 16 + 64 + 3)
Definition at line 85 of file pointcache.c.
Referenced by ptcache_dynamicpaint_write(), ptcache_file_compressed_write(), and ptcache_mem_frame_to_disk().
#define MAX_PTCACHE_FILE ((FILE_MAX)*2)
Definition at line 1043 of file pointcache.c.
Referenced by BKE_ptcache_disk_cache_rename(), BKE_ptcache_id_clear(), BKE_ptcache_id_exist(), BKE_ptcache_id_time(), BKE_ptcache_load_external(), and ptcache_filename().
#define MAX_PTCACHE_PATH FILE_MAX
Definition at line 1042 of file pointcache.c.
Referenced by BKE_ptcache_disk_cache_rename(), BKE_ptcache_id_clear(), BKE_ptcache_id_time(), BKE_ptcache_load_external(), BKE_ptcache_remove(), and ptcache_path().
#define PTCACHE_DATA_FROM (data, type, from) if (data[type]) { memcpy(data[type], from, ptcache_data_size[type]); }
Definition at line 102 of file pointcache.c.
Referenced by ptcache_cloth_write(), ptcache_particle_write(), and ptcache_softbody_write().
#define PTCACHE_DATA_TO (data, type, index, to) if (data[type]) { memcpy(to, (char*)data[type] + (index ? index * ptcache_data_size[type] : 0), ptcache_data_size[type]); }
Definition at line 103 of file pointcache.c.
Referenced by BKE_ptcache_make_particle_key(), ptcache_cloth_read(), ptcache_particle_read(), and ptcache_softbody_read().
Function Documentation
PointCache* BKE_ptcache_add (ListBase * ptcaches) [read]
Definition at line 2603 of file pointcache.c.
References BLI_addtail(), PointCache::endframe, PointCache::index, MEM_callocN(), PointCache::startframe, and PointCache::step.
Referenced by do_versions(), dynamicPaint_createNewSurface(), free_hair(), initData(), object_add_particle_system(), ptcache_add_new_exec(), sbNew(), smokeModifier_createType(), and write_modifiers().
void BKE_ptcache_bake (PTCacheBaker * baker)
Definition at line 2772 of file pointcache.c.
References PTCacheBaker::anim_init, PTCacheBaker::bake, BKE_ptcache_id_clear(), BKE_ptcache_ids_from_object(), BKE_ptcache_write(), blender_test_break(), BLI_end_threads(), BLI_freelistN(), BLI_init_threads(), BLI_insert_thread(), ptcache_bake_data::break_operation, PTCacheID::cache, PTCacheID::calldata, CFRA, ptcache_bake_data::cfra_ptr, PointCache::endframe, ptcache_bake_data::endframe, FALSE, ListBase::first, PointCache::flag, RenderData::framelen, G, if(), PointCache::last_exact, Scene::lay, ptcache_bake_data::main, PTCacheBaker::main, MAX2, MAX_DUPLI_RECUR, MAXFRAME, MIN2, PTCacheID::next, NULL, PTCacheID::ob, Base::object, ParticleSystem::part, PART_EMITTER, PART_HAIR, PART_PHYS_KEYED, ParticleSettings::phystype, PTCacheBaker::pid, PIL_sleep_ms(), PTCacheBaker::progressbar, PTCacheBaker::progresscontext, PTCacheBaker::progressend, psys_get_pointcache_start_end(), ptcache_bake_thread(), PTCACHE_BAKED, PTCACHE_BAKING, PTCACHE_CLEAR_ALL, PTCACHE_DISK_CACHE, PTCACHE_OUTDATED, PTCACHE_QUICK_CACHE, PTCACHE_REDO_NEEDED, PTCACHE_SIMULATION_VALID, PTCACHE_TYPE_PARTICLES, PTCACHE_TYPE_SMOKE_DOMAIN, PTCACHE_TYPE_SMOKE_HIGHRES, PTCacheBaker::quick_step, Scene::r, PTCacheBaker::render, ptcache_bake_data::scene, PTCacheBaker::scene, scene_update_for_newframe(), SETLOOPER, RenderData::sfra, PointCache::startframe, ptcache_bake_data::step, ptcache_bake_data::thread_ended, threads, TRUE, ParticleSettings::type, PTCacheID::type, and WM_cursor_wait().
Referenced by BKE_ptcache_quick_cache_all(), ptcache_bake_all_exec(), ptcache_bake_exec(), and update_physics_cache().
PointCache* BKE_ptcache_copy_list (ListBase * ptcaches_new, ListBase * ptcaches_old) [read]
Definition at line 2669 of file pointcache.c.
References BLI_addtail(), ListBase::first, ListBase::last, PointCache::next, NULL, and ptcache_copy().
Referenced by copy_particlesystem(), copy_softbody(), and copyData().
int BKE_ptcache_data_size (int data_type)
Definition at line 1355 of file pointcache.c.
References ptcache_data_size.
Referenced by direct_link_pointcache().
void BKE_ptcache_disk_cache_rename (PTCacheID * pid, const char * name_src, const char * name_dst)
Definition at line 3066 of file pointcache.c.
References BLI_join_dirfile(), BLI_rename(), BLI_snprintf(), BLI_strncpy(), PTCacheID::cache, closedir(), dirent::d_name, len(), MAX_PTCACHE_FILE, MAX_PTCACHE_PATH, PointCache::name, NULL, opendir(), PTCACHE_EXT, ptcache_filename(), ptcache_path(), readdir(), PTCacheID::stack_index, and strlen().
void BKE_ptcache_disk_to_mem (PTCacheID * pid)
Definition at line 2984 of file pointcache.c.
References BKE_ptcache_id_clear(), BLI_addtail(), PTCacheID::cache, PointCache::endframe, PointCache::flag, PointCache::mem_cache, NULL, PTCACHE_BAKED, PTCACHE_CLEAR_ALL, ptcache_disk_frame_to_mem(), and PointCache::startframe.
Referenced by BKE_ptcache_toggle_disk_cache(), and psys_make_temp_pointcache().
void BKE_ptcache_free (PointCache * cache)
Definition at line 2631 of file pointcache.c.
References BKE_ptcache_free_mem(), PointCache::cached_frames, PointCache::edit, PointCache::free_edit, PointCache::mem_cache, and MEM_freeN().
Referenced by BKE_ptcache_free_list(), direct_link_modifiers(), and ptcache_remove_exec().
void BKE_ptcache_free_list (ListBase * ptcaches)
Definition at line 2640 of file pointcache.c.
References BKE_ptcache_free(), BLI_remlink(), and ListBase::first.
Referenced by copyData(), dynamicPaint_freeSurface(), free_hair(), freeData(), psys_free(), sbFree(), smokeModifier_freeDomain(), and write_modifiers().
void BKE_ptcache_free_mem (ListBase * mem_cache)
Definition at line 2618 of file pointcache.c.
References BLI_freelistN(), ListBase::first, PTCacheMem::next, ptcache_data_free(), and ptcache_extra_free().
Referenced by BKE_ptcache_free(), free_PTCacheUndo(), get_PTCacheUndo(), and psys_clear_temp_pointcache().
int BKE_ptcache_get_continue_physics (void)
Definition at line 2596 of file pointcache.c.
References CONTINUE_PHYSICS.
Referenced by BKE_ptcache_id_reset(), clothModifier_do(), deformVerts(), sbObjectStep(), system_step(), and transformApply().
void BKE_ptcache_id_clear (PTCacheID * pid, int mode, unsigned int cfra)
Definition at line 2122 of file pointcache.c.
References BKE_ptcache_id_exist(), BKE_ptcache_update_info(), BLI_delete(), BLI_freelinkN(), BLI_freelistN(), BLI_join_dirfile(), BLI_snprintf(), BLI_strncpy(), PTCacheID::cache, PointCache::cached_frames, closedir(), dirent::d_name, PointCache::endframe, ListBase::first, PointCache::flag, PTCacheMem::frame, Object::id, PointCache::last_exact, len(), ID::lib, link(), MAX_PTCACHE_FILE, MAX_PTCACHE_PATH, MEM_allocN_len(), PointCache::mem_cache, MIN2, PTCacheMem::next, NULL, PTCacheID::ob, opendir(), PTCACHE_BAKED, PTCACHE_CLEAR_AFTER, PTCACHE_CLEAR_ALL, PTCACHE_CLEAR_BEFORE, PTCACHE_CLEAR_FRAME, ptcache_data_free(), PTCACHE_DISK_CACHE, PTCACHE_EXT, ptcache_extra_free(), ptcache_filename(), PTCACHE_IGNORE_CLEAR, ptcache_path(), readdir(), PTCacheID::stack_index, PointCache::startframe, and strlen().
Referenced by BKE_ptcache_bake(), BKE_ptcache_disk_to_mem(), BKE_ptcache_id_reset(), BKE_ptcache_mem_to_disk(), BKE_ptcache_read(), BKE_ptcache_toggle_disk_cache(), cloth_clear_cache(), psys_changed_type(), psys_prepare_physics(), ptcache_mem_frame_to_disk(), ptcache_write_needed(), ptcache_write_stream(), and system_step().
int BKE_ptcache_id_exist (PTCacheID * pid, int cfra)
Definition at line 2264 of file pointcache.c.
References BLI_exists(), PTCacheID::cache, PointCache::cached_frames, PointCache::endframe, ListBase::first, PointCache::flag, PTCacheMem::frame, MAX_PTCACHE_FILE, PointCache::mem_cache, PTCacheMem::next, PTCACHE_DISK_CACHE, ptcache_filename(), and PointCache::startframe.
Referenced by BKE_ptcache_id_clear(), BKE_ptcache_read(), BKE_ptcache_update_info(), ptcache_find_frames_around(), ptcache_write(), and ptcache_write_needed().
void BKE_ptcache_id_from_cloth (PTCacheID * pid, Object * ob, ClothModifierData * clmd)
Definition at line 837 of file pointcache.c.
References BPHYS_DATA_LOCATION, BPHYS_DATA_VELOCITY, BPHYS_DATA_XCONST, PTCacheID::cache, PTCacheID::cache_ptr, PTCacheID::calldata, PTCacheID::data_types, PTCacheID::default_step, PointCache::index, PTCacheID::info_types, PTCacheID::interpolate_extra_data, PTCacheID::interpolate_point, PTCacheID::max_step, NULL, PTCacheID::ob, ClothModifierData::point_cache, ptcache_basic_header_read(), ptcache_basic_header_write(), ptcache_cloth_interpolate(), ptcache_cloth_read(), ptcache_cloth_totpoint(), ptcache_cloth_write(), PTCACHE_TYPE_CLOTH, ClothModifierData::ptcaches, PTCacheID::ptcaches, PTCacheID::read_extra_data, PTCacheID::read_header, PTCacheID::read_point, PTCacheID::read_stream, PTCacheID::stack_index, PTCacheID::totpoint, PTCacheID::totwrite, PTCacheID::type, PTCacheID::write_extra_data, PTCacheID::write_header, PTCacheID::write_point, and PTCacheID::write_stream.
Referenced by BKE_ptcache_ids_from_object(), BKE_ptcache_object_reset(), cloth_clear_cache(), and clothModifier_do().
void BKE_ptcache_id_from_dynamicpaint (PTCacheID * pid, Object * ob, DynamicPaintSurface * surface)
Definition at line 914 of file pointcache.c.
References BPHYS_DATA_DYNAMICPAINT, PTCacheID::cache, PTCacheID::cache_ptr, PTCacheID::calldata, PTCacheID::data_types, PTCacheID::default_step, PointCache::index, PTCacheID::info_types, PTCacheID::interpolate_extra_data, PTCacheID::interpolate_point, PTCacheID::max_step, NULL, PTCacheID::ob, DynamicPaintSurface::pointcache, ptcache_basic_header_read(), ptcache_basic_header_write(), ptcache_dynamicpaint_read(), ptcache_dynamicpaint_totpoint(), ptcache_dynamicpaint_write(), PTCACHE_TYPE_DYNAMICPAINT, DynamicPaintSurface::ptcaches, PTCacheID::ptcaches, PTCacheID::read_extra_data, PTCacheID::read_header, PTCacheID::read_point, PTCacheID::read_stream, PTCacheID::stack_index, PTCacheID::totpoint, PTCacheID::totwrite, PTCacheID::type, PTCacheID::write_extra_data, PTCacheID::write_header, PTCacheID::write_point, and PTCacheID::write_stream.
Referenced by BKE_ptcache_ids_from_object(), BKE_ptcache_object_reset(), and dynamicPaint_frameUpdate().
void BKE_ptcache_id_from_particles (PTCacheID * pid, Object * ob, ParticleSystem * psys)
Definition at line 780 of file pointcache.c.
References ParticleSettings::avefac, ParticleSettings::avemode, BPHYS_DATA_AVELOCITY, BPHYS_DATA_BOIDS, BPHYS_DATA_INDEX, BPHYS_DATA_LOCATION, BPHYS_DATA_ROTATION, BPHYS_DATA_TIMES, BPHYS_DATA_VELOCITY, PTCacheID::cache, PTCacheID::cache_ptr, PTCacheID::calldata, PTCacheID::data_types, PTCacheID::default_step, ParticleSettings::flag, SPHFluidSettings::flag, PTCacheID::flag, ParticleSettings::fluid, PointCache::index, PTCacheID::info_types, PTCacheID::interpolate_extra_data, PTCacheID::interpolate_point, PTCacheID::max_step, NULL, PTCacheID::ob, ParticleSystem::part, PART_AVE_RAND, PART_HAIR, PART_PHYS_BOIDS, PART_PHYS_FLUID, PART_ROT_VEL, PART_ROTATIONS, ParticleSettings::phystype, ParticleSystem::pointcache, ptcache_basic_header_read(), ptcache_basic_header_write(), ptcache_particle_extra_read(), ptcache_particle_extra_write(), ptcache_particle_interpolate(), ptcache_particle_read(), ptcache_particle_totpoint(), ptcache_particle_totwrite(), ptcache_particle_write(), PTCACHE_TYPE_PARTICLES, PTCACHE_VEL_PER_SEC, ParticleSystem::ptcaches, PTCacheID::ptcaches, PTCacheID::read_extra_data, PTCacheID::read_header, PTCacheID::read_point, PTCacheID::read_stream, ParticleSettings::rotmode, SPH_VISCOELASTIC_SPRINGS, PTCacheID::stack_index, PTCacheID::totpoint, PTCacheID::totwrite, ParticleSettings::type, PTCacheID::type, PTCacheID::write_extra_data, PTCacheID::write_header, PTCacheID::write_point, and PTCacheID::write_stream.
Referenced by BKE_ptcache_ids_from_object(), BKE_ptcache_object_reset(), psys_changed_type(), psys_make_temp_pointcache(), psys_prepare_physics(), and system_step().
void BKE_ptcache_id_from_smoke (PTCacheID * pid, struct Object * ob, struct SmokeModifierData * smd)
Definition at line 870 of file pointcache.c.
References BPHYS_DATA_SMOKE_HIGH, BPHYS_DATA_SMOKE_LOW, PTCacheID::cache, PTCacheID::cache_ptr, PTCacheID::calldata, PTCacheID::data_types, PTCacheID::default_step, SmokeModifierData::domain, SmokeDomainSettings::fluid, PointCache::index, PTCacheID::info_types, PTCacheID::interpolate_extra_data, PTCacheID::interpolate_point, PTCacheID::max_step, NULL, PTCacheID::ob, SmokeDomainSettings::point_cache, ptcache_basic_header_read(), ptcache_basic_header_write(), ptcache_smoke_read(), ptcache_smoke_totpoint(), ptcache_smoke_write(), PTCACHE_TYPE_SMOKE_DOMAIN, SmokeDomainSettings::ptcaches, PTCacheID::ptcaches, PTCacheID::read_extra_data, PTCacheID::read_header, PTCacheID::read_point, PTCacheID::read_stream, PTCacheID::stack_index, PTCacheID::totpoint, PTCacheID::totwrite, PTCacheID::type, PTCacheID::write_extra_data, PTCacheID::write_header, PTCacheID::write_point, PTCacheID::write_stream, and SmokeDomainSettings::wt.
Referenced by BKE_ptcache_ids_from_object(), and BKE_ptcache_object_reset().
void BKE_ptcache_id_from_softbody (PTCacheID * pid, Object * ob, SoftBody * sb)
Definition at line 746 of file pointcache.c.
References BPHYS_DATA_LOCATION, BPHYS_DATA_VELOCITY, PTCacheID::cache, PTCacheID::cache_ptr, PTCacheID::calldata, PTCacheID::data_types, PTCacheID::default_step, PointCache::index, PTCacheID::info_types, PTCacheID::interpolate_extra_data, PTCacheID::interpolate_point, PTCacheID::max_step, NULL, PTCacheID::ob, SoftBody::pointcache, ptcache_basic_header_read(), ptcache_basic_header_write(), ptcache_softbody_interpolate(), ptcache_softbody_read(), ptcache_softbody_totpoint(), ptcache_softbody_write(), PTCACHE_TYPE_SOFTBODY, SoftBody::ptcaches, PTCacheID::ptcaches, PTCacheID::read_extra_data, PTCacheID::read_header, PTCacheID::read_point, PTCacheID::read_stream, PTCacheID::stack_index, PTCacheID::totpoint, PTCacheID::totwrite, PTCacheID::type, PTCacheID::write_extra_data, PTCacheID::write_header, PTCacheID::write_point, and PTCacheID::write_stream.
Referenced by BKE_ptcache_ids_from_object(), BKE_ptcache_object_reset(), and sbObjectStep().
int BKE_ptcache_id_reset (Scene * scene, PTCacheID * pid, int mode)
Definition at line 2402 of file pointcache.c.
References BKE_ptcache_get_continue_physics(), BKE_ptcache_id_clear(), BKE_ptcache_invalidate(), PTCacheID::cache, PTCacheID::calldata, CFRA, clear(), cloth_free_modifier(), dynamicPaint_clearSurface(), PointCache::flag, psys_reset(), PSYS_RESET_DEPSGRAPH, PTCACHE_BAKED, PTCACHE_CLEAR_AFTER, PTCACHE_CLEAR_ALL, PTCACHE_OUTDATED, PTCACHE_QUICK_CACHE, PTCACHE_REDO_NEEDED, PTCACHE_RESET_BAKED, PTCACHE_RESET_DEPSGRAPH, PTCACHE_RESET_OUTDATED, PTCACHE_TYPE_CLOTH, PTCACHE_TYPE_DYNAMICPAINT, PTCACHE_TYPE_PARTICLES, PTCACHE_TYPE_SMOKE_DOMAIN, PTCACHE_TYPE_SMOKE_HIGHRES, PTCACHE_TYPE_SOFTBODY, sbFreeSimulation(), smokeModifier_reset(), smokeModifier_reset_turbulence(), and PTCacheID::type.
Referenced by BKE_ptcache_object_reset(), clothModifier_do(), dynamicPaint_frameUpdate(), sbObjectStep(), and system_step().
void BKE_ptcache_id_time (PTCacheID * pid, Scene * scene, float cfra, int * startframe, int * endframe, float * timescale)
Definition at line 2292 of file pointcache.c.
References BKE_curframe(), BKE_frame_to_ctime(), BLI_snprintf(), BLI_strncpy(), PTCacheID::cache, PointCache::cached_frames, CFRA, closedir(), dirent::d_name, PointCache::endframe, ListBase::first, PointCache::flag, PTCacheMem::frame, len(), MAX2, MAX_PTCACHE_FILE, MAX_PTCACHE_PATH, MEM_allocN_len(), PointCache::mem_cache, MEM_callocN(), MEM_freeN(), PTCacheMem::next, NULL, opendir(), PARSLOW, PTCACHE_DISK_CACHE, PTCACHE_EXT, ptcache_filename(), ptcache_path(), readdir(), PTCacheID::stack_index, PointCache::startframe, and strlen().
Referenced by BKE_ptcache_toggle_disk_cache(), clothModifier_do(), dynamicPaint_frameUpdate(), sbObjectStep(), and system_step().
void BKE_ptcache_ids_from_object (ListBase * lb, Object * ob, Scene * scene, int duplis)
Definition at line 950 of file pointcache.c.
References BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_ids_from_object(), BLI_addtail(), BLI_movelisttolist(), DynamicPaintModifierData::canvas, ELEM, eModifierType_Cloth, eModifierType_DynamicPaint, eModifierType_Smoke, ListBase::first, free_object_duplilist(), ListBase::last, MEM_callocN(), MOD_SMOKE_TYPE_DOMAIN, Object::modifiers, DupliObject::next, DynamicPaintSurface::next, ModifierData::next, ParticleSystem::next, NULL, DupliObject::ob, OB_DUPLI, object_duplilist(), ParticleSystem::part, PART_FLUID, PART_PHYS_KEYED, PART_PHYS_NO, Object::particlesystem, ParticleSettings::phystype, Object::soft, DynamicPaintCanvasSettings::surfaces, Object::transflag, SmokeModifierData::type, ModifierData::type, and ParticleSettings::type.
Referenced by BKE_ptcache_bake(), BKE_ptcache_ids_from_object(), ED_object_exit_editmode(), object_cacheIgnoreClear(), object_handle_update(), pe_get_current(), ptcache_add_new_exec(), ptcache_bake_exec(), ptcache_free_bake_all_exec(), ptcache_remove_exec(), special_aftertrans_update(), and time_draw_cache().
void BKE_ptcache_invalidate (PointCache * cache)
Definition at line 3314 of file pointcache.c.
References PointCache::flag, PointCache::last_exact, MIN2, PTCACHE_SIMULATION_VALID, PointCache::simframe, and PointCache::startframe.
Referenced by BKE_ptcache_id_reset(), clothModifier_do(), do_init_cloth(), psys_reset(), sbObjectStep(), and system_step().
void BKE_ptcache_load_external (PTCacheID * pid)
Definition at line 3122 of file pointcache.c.
References BKE_ptcache_update_info(), BLI_snprintf(), BLI_strncpy(), PTCacheID::cache, closedir(), dirent::d_name, PointCache::endframe, PointCache::flag, PointCache::index, len(), MAX2, MAX_PTCACHE_FILE, MAX_PTCACHE_PATH, MAXFRAME, MIN2, NULL, opendir(), pf, PTCACHE_BAKED, PTCACHE_DISK_CACHE, PTCACHE_EXT, ptcache_file_close(), ptcache_file_header_begin_read(), ptcache_file_open(), ptcache_file_read(), PTCACHE_FILE_READ, ptcache_filename(), PTCACHE_FRAMES_SKIPPED, ptcache_old_elemsize(), PTCACHE_OUTDATED, ptcache_path(), PTCACHE_READ_INFO, PTCACHE_SIMULATION_VALID, PTCACHE_TYPE_SMOKE_DOMAIN, PTCacheID::read_header, readdir(), PointCache::startframe, strlen(), PTCacheFile::totpoint, PointCache::totpoint, PTCacheFile::type, and PTCacheID::type.
void BKE_ptcache_make_particle_key (ParticleKey * key, int index, void ** data, float time)
Definition at line 218 of file pointcache.c.
References ParticleKey::ave, BPHYS_DATA_AVELOCITY, BPHYS_DATA_LOCATION, BPHYS_DATA_ROTATION, BPHYS_DATA_VELOCITY, ParticleKey::co, NULL, OB_NEGX, OB_POSZ, PTCACHE_DATA_TO, ParticleKey::rot, ParticleKey::time, vec_to_quat(), and ParticleKey::vel.
Referenced by get_pointcache_keys_for_time(), ptcache_cloth_interpolate(), ptcache_particle_interpolate(), ptcache_particle_read(), and ptcache_softbody_interpolate().
int BKE_ptcache_mem_index_find (PTCacheMem * pm, unsigned int index)
Definition at line 1375 of file pointcache.c.
References BPHYS_DATA_INDEX, data, PTCacheMem::data, and PTCacheMem::totpoint.
Referenced by BKE_ptcache_mem_pointers_seek(), get_pointcache_keys_for_time(), get_pointcache_times_for_particle(), and psys_get_dietime_from_cache().
void BKE_ptcache_mem_pointers_incr (PTCacheMem * pm)
Definition at line 1415 of file pointcache.c.
References BPHYS_TOT_DATA, PTCacheMem::cur, i, and ptcache_data_size.
Referenced by get_PTCacheUndo(), PE_create_particle_edit(), ptcache_disk_frame_to_mem(), ptcache_interpolate(), ptcache_mem_frame_to_disk(), ptcache_read(), and ptcache_write().
void BKE_ptcache_mem_pointers_init (PTCacheMem * pm)
Definition at line 1406 of file pointcache.c.
References BPHYS_TOT_DATA, PTCacheMem::cur, PTCacheMem::data, PTCacheMem::data_types, i, and NULL.
Referenced by get_PTCacheUndo(), ptcache_disk_frame_to_mem(), ptcache_interpolate(), ptcache_mem_frame_to_disk(), ptcache_read(), and ptcache_write().
int BKE_ptcache_mem_pointers_seek (int point_index, PTCacheMem * pm)
Definition at line 1424 of file pointcache.c.
References BKE_ptcache_mem_index_find(), BPHYS_TOT_DATA, PTCacheMem::cur, PTCacheMem::data, PTCacheMem::data_types, i, NULL, and ptcache_data_size.
Referenced by PE_create_particle_edit(), and ptcache_write().
void BKE_ptcache_mem_to_disk (PTCacheID * pid)
Definition at line 3007 of file pointcache.c.
References BKE_ptcache_id_clear(), BKE_ptcache_write(), PTCacheID::cache, ListBase::first, PointCache::flag, PointCache::mem_cache, PTCacheMem::next, PTCACHE_BAKED, PTCACHE_CLEAR_ALL, PTCACHE_DISK_CACHE, and ptcache_mem_frame_to_disk().
Referenced by BKE_ptcache_toggle_disk_cache().
int BKE_ptcache_object_reset (Scene * scene, Object * ob, int mode)
Definition at line 2466 of file pointcache.c.
References BIK_clear_cache(), BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_id_reset(), PTCacheID::cache, DynamicPaintModifierData::canvas, ParticleSystem::clmd, eModifierType_Cloth, eModifierType_DynamicPaint, eModifierType_Smoke, ListBase::first, PointCache::flag, MOD_SMOKE_TYPE_DOMAIN, Object::modifiers, DynamicPaintSurface::next, ModifierData::next, ParticleSystem::next, OB_ARMATURE, ParticleSystem::part, PART_HAIR, Object::particlesystem, Object::pose, PSYS_RECALC_CHILD, PSYS_RECALC_REDO, PSYS_RESET_ALL, PTCACHE_BAKED, ParticleSystem::recalc, Object::soft, DynamicPaintCanvasSettings::surfaces, Object::type, SmokeModifierData::type, ModifierData::type, and ParticleSettings::type.
Referenced by BKE_ptcache_set_continue_physics(), dag_id_flush_update(), DAG_scene_flush_update(), ED_object_exit_editmode(), flush_pointcache_reset(), and special_aftertrans_update().
void BKE_ptcache_quick_cache_all (Main * bmain, Scene * scene)
Definition at line 2683 of file pointcache.c.
References PTCacheBaker::anim_init, PTCacheBaker::bake, BKE_ptcache_bake(), PTCacheBaker::break_data, PTCacheBaker::break_test, PTCacheBaker::main, NULL, Scene::physics_settings, PTCacheBaker::pid, PTCacheBaker::progressbar, PTCacheBaker::progresscontext, PTCacheBaker::progressend, PhysicsSettings::quick_cache_step, PTCacheBaker::quick_step, PTCacheBaker::render, and PTCacheBaker::scene.
Referenced by scene_update_tagged().
int BKE_ptcache_read (PTCacheID * pid, float cfra)
Definition at line 1851 of file pointcache.c.
References BKE_ptcache_id_clear(), BKE_ptcache_id_exist(), PTCacheID::cache, PTCacheID::calldata, PointCache::flag, PTCacheID::interpolate_point, PointCache::last_exact, MAX2, PTCACHE_CLEAR_AFTER, ptcache_find_frames_around(), PTCACHE_FRAMES_SKIPPED, ptcache_interpolate(), PTCACHE_OUTDATED, PTCACHE_QUICK_CACHE, ptcache_read(), PTCACHE_READ_EXACT, PTCACHE_READ_INFO, PTCACHE_READ_INTERPOLATED, PTCACHE_READ_OLD, ptcache_read_stream(), PTCacheID::read_point, PTCacheID::read_stream, PointCache::simframe, and PTCacheID::totpoint.
Referenced by clothModifier_do(), dynamicPaint_frameUpdate(), sbObjectStep(), and system_step().
void BKE_ptcache_remove (void)
Definition at line 2535 of file pointcache.c.
References BLI_delete(), BLI_exists(), BLI_join_dirfile(), closedir(), dirent::d_name, MAX_PTCACHE_PATH, NULL, opendir(), PTCACHE_EXT, ptcache_path(), and readdir().
void BKE_ptcache_set_continue_physics (Main * bmain, Scene * scene, int enable)
Definition at line 2581 of file pointcache.c.
References BKE_ptcache_object_reset(), DAG_id_tag_update(), ListBase::first, Object::id, ID::next, OB_RECALC_DATA, Main::object, and PTCACHE_RESET_OUTDATED.
void BKE_ptcache_toggle_disk_cache (PTCacheID * pid)
Definition at line 3033 of file pointcache.c.
References BKE_ptcache_disk_to_mem(), BKE_ptcache_id_clear(), BKE_ptcache_id_time(), BKE_ptcache_mem_to_disk(), BKE_ptcache_update_info(), PTCacheID::cache, PointCache::cached_frames, PointCache::flag, G, G_DEBUG, PointCache::last_exact, MEM_freeN(), NULL, PTCACHE_CLEAR_ALL, and PTCACHE_DISK_CACHE.
void BKE_ptcache_update_info (PTCacheID * pid)
Definition at line 3223 of file pointcache.c.
References BKE_ptcache_id_exist(), BLI_snprintf(), BPHYS_TOT_DATA, PTCacheID::cache, PTCacheID::calldata, PTCacheExtra::data, PTCacheMem::data, PointCache::endframe, PTCacheMem::extradata, ListBase::first, PointCache::flag, i, PointCache::info, PointCache::last_exact, MEM_allocN_len(), PointCache::mem_cache, PTCacheExtra::next, PTCacheMem::next, NULL, PTCACHE_DISK_CACHE, PTCACHE_EXTERNAL, PTCACHE_FRAMES_SKIPPED, PTCACHE_OUTDATED, PTCACHE_TYPE_SMOKE_DOMAIN, PointCache::startframe, PTCacheID::totpoint, PointCache::totpoint, and PTCacheID::type.
Referenced by BKE_ptcache_id_clear(), BKE_ptcache_load_external(), BKE_ptcache_toggle_disk_cache(), and BKE_ptcache_write().
void BKE_ptcache_validate (PointCache * cache, int framenr)
Definition at line 3307 of file pointcache.c.
References PointCache::flag, PTCACHE_SIMULATION_VALID, and PointCache::simframe.
Referenced by clothModifier_do(), dynamicPaint_frameUpdate(), sbObjectStep(), and system_step().
int BKE_ptcache_write (PTCacheID * pid, unsigned int cfra)
Definition at line 2081 of file pointcache.c.
References BKE_ptcache_update_info(), PTCacheID::cache, PointCache::cached_frames, PTCacheID::calldata, PTCacheID::data_types, error(), PointCache::flag, PTCacheID::info_types, PointCache::last_exact, PTCACHE_FRAMES_SKIPPED, ptcache_write(), ptcache_write_needed(), ptcache_write_stream(), PointCache::startframe, PTCacheID::totpoint, PTCacheID::write_point, and PTCacheID::write_stream.
Referenced by BKE_ptcache_bake(), BKE_ptcache_mem_to_disk(), clothModifier_do(), dynamicPaint_frameUpdate(), sbObjectStep(), and system_step().
static void* ptcache_bake_thread (void * ptr) [static]
Definition at line 2727 of file pointcache.c.
References ptcache_bake_data::break_operation, ptcache_bake_data::cfra_ptr, ptcache_bake_data::endframe, G, Scene::lay, ptcache_bake_data::main, NULL, PIL_check_seconds_timer(), ptcache_dt_to_str(), ptcache_bake_data::scene, scene_update_for_newframe(), ptcache_bake_data::step, ptcache_bake_data::thread_ended, and TRUE.
Referenced by BKE_ptcache_bake().
static int ptcache_basic_header_read (PTCacheFile * pf) [static]
Definition at line 131 of file pointcache.c.
References PTCacheFile::data_types, error(), PTCacheFile::fp, and PTCacheFile::totpoint.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), and BKE_ptcache_id_from_softbody().
static int ptcache_basic_header_write (PTCacheFile * pf) [static]
Definition at line 144 of file pointcache.c.
References PTCacheFile::data_types, PTCacheFile::fp, and PTCacheFile::totpoint.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), and BKE_ptcache_id_from_softbody().
static void ptcache_cloth_interpolate (int index, void * cloth_v, void ** data, float cfra, float cfra1, float cfra2, float * old_data) [static]
Definition at line 480 of file pointcache.c.
References BKE_ptcache_make_particle_key(), ClothModifierData::clothObject, ParticleKey::co, co, copy_v3_v3(), ImBuf::index, mul_v3_fl(), psys_interpolate_particle(), ClothVertex::v, ParticleKey::vel, Cloth::verts, and ClothVertex::x.
Referenced by BKE_ptcache_id_from_cloth().
static void ptcache_cloth_read (int index, void * cloth_v, void ** data, float UNUSEDcfra, float * old_data) [static]
Definition at line 463 of file pointcache.c.
References BPHYS_DATA_LOCATION, BPHYS_DATA_VELOCITY, BPHYS_DATA_XCONST, ClothModifierData::clothObject, ImBuf::index, PTCACHE_DATA_TO, ClothVertex::v, Cloth::verts, ClothVertex::x, and ClothVertex::xconst.
Referenced by BKE_ptcache_id_from_cloth().
static int ptcache_cloth_totpoint (void * cloth_v, int UNUSEDcfra) [static]
Definition at line 516 of file pointcache.c.
References ClothModifierData::clothObject, and Cloth::numverts.
Referenced by BKE_ptcache_id_from_cloth().
static int ptcache_cloth_write (int index, void * cloth_v, void ** data, int UNUSEDcfra) [static]
Definition at line 451 of file pointcache.c.
References BPHYS_DATA_LOCATION, BPHYS_DATA_VELOCITY, BPHYS_DATA_XCONST, ClothModifierData::clothObject, ImBuf::index, PTCACHE_DATA_FROM, ClothVertex::v, Cloth::verts, ClothVertex::x, and ClothVertex::xconst.
Referenced by BKE_ptcache_id_from_cloth().
static PointCache* ptcache_copy (PointCache * cache) [static]
Definition at line 2651 of file pointcache.c.
References PointCache::cached_frames, PointCache::edit, ListBase::first, PointCache::flag, ListBase::last, PointCache::mem_cache, MEM_dupallocN(), NULL, and PointCache::simframe.
Referenced by BKE_ptcache_copy_list().
static void ptcache_data_alloc (PTCacheMem * pm) [static]
Definition at line 1443 of file pointcache.c.
References BPHYS_TOT_DATA, PTCacheMem::data, PTCacheMem::data_types, i, MEM_callocN(), ptcache_data_size, and PTCacheMem::totpoint.
Referenced by ptcache_disk_frame_to_mem(), and ptcache_write().
static void ptcache_data_copy (void * from[], void * to[]) [static]
Definition at line 1464 of file pointcache.c.
References BPHYS_TOT_DATA, i, and ptcache_data_size.
Referenced by ptcache_disk_frame_to_mem(), and ptcache_mem_frame_to_disk().
static void ptcache_data_free (PTCacheMem * pm) [static]
Definition at line 1454 of file pointcache.c.
References BPHYS_TOT_DATA, PTCacheMem::data, i, and MEM_freeN().
Referenced by BKE_ptcache_free_mem(), BKE_ptcache_id_clear(), ptcache_disk_frame_to_mem(), ptcache_interpolate(), ptcache_read(), and ptcache_write().
static PTCacheMem* ptcache_disk_frame_to_mem (PTCacheID * pid, int cfra) [static]
Definition at line 1553 of file pointcache.c.
References BKE_ptcache_mem_pointers_incr(), BKE_ptcache_mem_pointers_init(), BLI_addtail(), BPHYS_TOT_DATA, PTCacheMem::cur, PTCacheFile::cur, PTCacheExtra::data, PTCacheMem::data, PTCacheFile::data_types, PTCacheMem::data_types, error(), PTCacheMem::extradata, PTCacheFile::flag, PTCacheFile::frame, PTCacheMem::frame, G, G_DEBUG, i, MEM_callocN(), MEM_freeN(), NULL, ptcache_data_alloc(), ptcache_data_copy(), ptcache_data_free(), ptcache_data_size, ptcache_extra_datasize, ptcache_extra_free(), ptcache_file_close(), ptcache_file_compressed_read(), ptcache_file_data_read(), ptcache_file_header_begin_read(), ptcache_file_open(), ptcache_file_pointers_init(), ptcache_file_read(), PTCACHE_FILE_READ, PTCACHE_TYPEFLAG_COMPRESS, PTCACHE_TYPEFLAG_EXTRADATA, PTCacheID::read_header, PTCacheExtra::totdata, PTCacheFile::totpoint, PTCacheMem::totpoint, PTCacheExtra::type, PTCacheID::type, and PTCacheFile::type.
Referenced by BKE_ptcache_disk_to_mem(), ptcache_interpolate(), ptcache_read(), and ptcache_write().
static void ptcache_dt_to_str (char * str, double dtime) [static]
Definition at line 2715 of file pointcache.c.
Referenced by ptcache_bake_thread().
static int ptcache_dynamicpaint_read (PTCacheFile * pf, void * dp_v) [static]
Definition at line 710 of file pointcache.c.
References DynamicPaintSurface::data, DPAINT_CACHE_VERSION, DynamicPaintSurface::format, MOD_DPAINT_SURFACE_F_IMAGESEQ, MOD_DPAINT_SURFACE_T_DISPLACE, MOD_DPAINT_SURFACE_T_PAINT, MOD_DPAINT_SURFACE_T_WAVE, MOD_DPAINT_SURFACE_T_WEIGHT, ptcache_file_compressed_read(), ptcache_file_read(), PaintSurfaceData::total_points, DynamicPaintSurface::type, and PaintSurfaceData::type_data.
Referenced by BKE_ptcache_id_from_dynamicpaint().
static int ptcache_dynamicpaint_totpoint (void * sd, int UNUSEDcfra) [static]
Definition at line 667 of file pointcache.c.
References DynamicPaintSurface::data, and PaintSurfaceData::total_points.
Referenced by BKE_ptcache_id_from_dynamicpaint().
static int ptcache_dynamicpaint_write (PTCacheFile * pf, void * dp_v) [static]
Definition at line 677 of file pointcache.c.
References DynamicPaintSurface::data, DPAINT_CACHE_VERSION, DynamicPaintSurface::format, LZO_OUT_LEN, MEM_callocN(), MEM_freeN(), MOD_DPAINT_SURFACE_F_IMAGESEQ, MOD_DPAINT_SURFACE_T_DISPLACE, MOD_DPAINT_SURFACE_T_PAINT, MOD_DPAINT_SURFACE_T_WAVE, MOD_DPAINT_SURFACE_T_WEIGHT, ptcache_file_compressed_write(), ptcache_file_write(), PaintSurfaceData::total_points, DynamicPaintSurface::type, and PaintSurfaceData::type_data.
Referenced by BKE_ptcache_id_from_dynamicpaint().
static void ptcache_extra_free (PTCacheMem * pm) [static]
Definition at line 1475 of file pointcache.c.
References BLI_freelistN(), PTCacheExtra::data, PTCacheMem::extradata, ListBase::first, MEM_freeN(), and PTCacheExtra::next.
Referenced by BKE_ptcache_free_mem(), BKE_ptcache_id_clear(), ptcache_disk_frame_to_mem(), ptcache_interpolate(), ptcache_read(), and ptcache_write().
static void ptcache_file_close (PTCacheFile * pf) [static]
Definition at line 1173 of file pointcache.c.
References PTCacheFile::fp, and MEM_freeN().
Referenced by BKE_ptcache_load_external(), ptcache_disk_frame_to_mem(), ptcache_mem_frame_to_disk(), ptcache_read_stream(), and ptcache_write_stream().
static int ptcache_file_compressed_read (PTCacheFile * pf, unsigned char * result, unsigned int len) [static]
Definition at line 1181 of file pointcache.c.
References len(), MEM_callocN(), MEM_freeN(), NULL, ptcache_file_read(), and size().
Referenced by ptcache_disk_frame_to_mem(), and ptcache_dynamicpaint_read().
static int ptcache_file_compressed_write (PTCacheFile * pf, unsigned char * in, unsigned int in_len, unsigned char * out, int mode) [static]
Definition at line 1229 of file pointcache.c.
References LZO_OUT_LEN, MEM_callocN(), MEM_freeN(), and ptcache_file_write().
Referenced by ptcache_dynamicpaint_write(), and ptcache_mem_frame_to_disk().
static int ptcache_file_data_read (PTCacheFile * pf) [static]
Definition at line 1292 of file pointcache.c.
References BPHYS_TOT_DATA, PTCacheFile::cur, PTCacheFile::data_types, i, and ptcache_data_size.
Referenced by ptcache_disk_frame_to_mem().
static int ptcache_file_data_write (PTCacheFile * pf) [static]
Definition at line 1303 of file pointcache.c.
References BPHYS_TOT_DATA, PTCacheFile::cur, PTCacheFile::data_types, i, and ptcache_data_size.
Referenced by ptcache_mem_frame_to_disk().
static int ptcache_file_header_begin_read (PTCacheFile * pf) [static]
Definition at line 1314 of file pointcache.c.
References PTCacheFile::data_types, error(), PTCacheFile::flag, PTCacheFile::fp, fseek, PTCACHE_TYPEFLAG_FLAGMASK, PTCACHE_TYPEFLAG_TYPEMASK, and PTCacheFile::type.
Referenced by BKE_ptcache_load_external(), ptcache_disk_frame_to_mem(), and ptcache_read_stream().
static int ptcache_file_header_begin_write (PTCacheFile * pf) [static]
Definition at line 1340 of file pointcache.c.
References PTCacheFile::flag, PTCacheFile::fp, and PTCacheFile::type.
Referenced by ptcache_mem_frame_to_disk(), and ptcache_write_stream().
static PTCacheFile* ptcache_file_open (PTCacheID * pid, int mode, int cfra) [static]
Definition at line 1133 of file pointcache.c.
References BLI_exists(), BLI_fopen(), BLI_make_existing_file(), PTCacheID::cache, FILE_MAX, PointCache::flag, PTCacheFile::fp, PTCacheFile::frame, G, Object::id, ID::lib, MEM_mallocN(), NULL, PTCacheID::ob, PTCacheFile::old_format, pf, PTCACHE_EXTERNAL, PTCACHE_FILE_READ, PTCACHE_FILE_UPDATE, PTCACHE_FILE_WRITE, and ptcache_filename().
Referenced by BKE_ptcache_load_external(), ptcache_disk_frame_to_mem(), ptcache_mem_frame_to_disk(), ptcache_read_stream(), and ptcache_write_stream().
static void ptcache_file_pointers_init (PTCacheFile * pf) [static]
Definition at line 1360 of file pointcache.c.
References PTCacheData::ave, PTCacheData::boids, BPHYS_DATA_AVELOCITY, BPHYS_DATA_BOIDS, BPHYS_DATA_INDEX, BPHYS_DATA_LOCATION, BPHYS_DATA_ROTATION, BPHYS_DATA_SIZE, BPHYS_DATA_TIMES, BPHYS_DATA_VELOCITY, PTCacheFile::cur, PTCacheFile::data, PTCacheFile::data_types, PTCacheData::index, PTCacheData::loc, NULL, PTCacheData::rot, PTCacheData::size, PTCacheData::times, and PTCacheData::vel.
Referenced by ptcache_disk_frame_to_mem(), ptcache_mem_frame_to_disk(), and ptcache_read_stream().
static int ptcache_file_read (PTCacheFile * pf, void * f, unsigned int tot, unsigned int size) [static]
Definition at line 1284 of file pointcache.c.
References PTCacheFile::fp.
Referenced by BKE_ptcache_load_external(), ptcache_disk_frame_to_mem(), ptcache_dynamicpaint_read(), and ptcache_file_compressed_read().
static int ptcache_file_write (PTCacheFile * pf, const void * f, unsigned int tot, unsigned int size) [static]
Definition at line 1288 of file pointcache.c.
References PTCacheFile::fp.
Referenced by ptcache_dynamicpaint_write(), ptcache_file_compressed_write(), and ptcache_mem_frame_to_disk().
static int ptcache_filename (PTCacheID * pid, char * filename, int cfra, short do_path, short do_ext) [static]
Definition at line 1081 of file pointcache.c.
References BLI_snprintf(), PTCacheID::cache, PointCache::flag, G, Object::id, PointCache::index, len(), MAX_PTCACHE_FILE, ID::name, PointCache::name, PTCacheID::ob, object_insert_ptcache(), PTCACHE_EXT, PTCACHE_EXTERNAL, ptcache_path(), PTCacheID::stack_index, and strlen().
Referenced by BKE_ptcache_disk_cache_rename(), BKE_ptcache_id_clear(), BKE_ptcache_id_exist(), BKE_ptcache_id_time(), BKE_ptcache_load_external(), and ptcache_file_open().
static void ptcache_find_frames_around (PTCacheID * pid, unsigned int frame, int * fra1, int * fra2) [static]
Definition at line 1500 of file pointcache.c.
References BKE_ptcache_id_exist(), PTCacheID::cache, PointCache::endframe, ListBase::first, PointCache::flag, PTCacheMem::frame, ListBase::last, PointCache::mem_cache, PTCacheMem::next, NULL, PTCacheMem::prev, PTCACHE_DISK_CACHE, and PointCache::startframe.
Referenced by BKE_ptcache_read().
static int ptcache_interpolate (PTCacheID * pid, float cfra, int cfra1, int cfra2) [static]
Definition at line 1802 of file pointcache.c.
References BKE_ptcache_mem_pointers_incr(), BKE_ptcache_mem_pointers_init(), BPHYS_DATA_INDEX, PTCacheID::cache, PTCacheID::calldata, PTCacheMem::cur, PTCacheMem::data_types, PTCacheID::data_types, PTCacheMem::extradata, ListBase::first, PointCache::flag, PTCacheMem::frame, i, PTCacheID::interpolate_extra_data, PTCacheID::interpolate_point, PointCache::mem_cache, MEM_freeN(), MIN2, PTCacheMem::next, NULL, ptcache_data_free(), PTCACHE_DISK_CACHE, ptcache_disk_frame_to_mem(), ptcache_extra_free(), PTCacheID::totpoint, and PTCacheMem::totpoint.
Referenced by BKE_ptcache_read().
static int ptcache_mem_frame_to_disk (PTCacheID * pid, PTCacheMem * pm) [static]
Definition at line 1634 of file pointcache.c.
References BKE_ptcache_id_clear(), BKE_ptcache_mem_pointers_incr(), BKE_ptcache_mem_pointers_init(), BPHYS_TOT_DATA, PTCacheID::cache, PointCache::compression, PTCacheFile::cur, PTCacheMem::cur, PTCacheExtra::data, PTCacheMem::data, PTCacheMem::data_types, PTCacheFile::data_types, error(), PTCacheMem::extradata, ListBase::first, PTCacheFile::flag, PTCacheMem::frame, G, G_DEBUG, i, LZO_OUT_LEN, MEM_callocN(), MEM_freeN(), PTCacheExtra::next, NULL, PTCACHE_CLEAR_FRAME, ptcache_data_copy(), ptcache_data_size, ptcache_extra_datasize, ptcache_file_close(), ptcache_file_compressed_write(), ptcache_file_data_write(), ptcache_file_header_begin_write(), ptcache_file_open(), ptcache_file_pointers_init(), ptcache_file_write(), PTCACHE_FILE_WRITE, PTCACHE_TYPEFLAG_COMPRESS, PTCACHE_TYPEFLAG_EXTRADATA, PTCacheExtra::totdata, PTCacheMem::totpoint, PTCacheFile::totpoint, PTCacheExtra::type, PTCacheID::type, PTCacheFile::type, and PTCacheID::write_header.
Referenced by BKE_ptcache_mem_to_disk(), and ptcache_write().
static int ptcache_old_elemsize (PTCacheID * pid) [static]
Definition at line 1488 of file pointcache.c.
References PTCACHE_TYPE_CLOTH, PTCACHE_TYPE_PARTICLES, PTCACHE_TYPE_SOFTBODY, and PTCacheID::type.
Referenced by BKE_ptcache_load_external().
static void ptcache_particle_extra_read (void * psys_v, PTCacheMem * pm, float UNUSEDcfra) [static]
Definition at line 430 of file pointcache.c.
References ParticleSystem::alloc_fluidsprings, BPHYS_EXTRA_FLUID_SPRINGS, PTCacheExtra::data, PTCacheMem::extradata, ListBase::first, ParticleSystem::fluid_springs, MEM_dupallocN(), MEM_freeN(), PTCacheExtra::next, ParticleSystem::tot_fluidsprings, PTCacheExtra::totdata, and PTCacheExtra::type.
Referenced by BKE_ptcache_id_from_particles().
static void ptcache_particle_extra_write (void * psys_v, PTCacheMem * pm, int UNUSEDcfra) [static]
Definition at line 409 of file pointcache.c.
References BLI_addtail(), BPHYS_EXTRA_FLUID_SPRINGS, PTCacheExtra::data, PTCacheMem::extradata, SPHFluidSettings::flag, ParticleSettings::fluid, ParticleSystem::fluid_springs, MEM_callocN(), NULL, ParticleSystem::part, PART_PHYS_FLUID, ParticleSettings::phystype, ptcache_extra_datasize, SPH_VISCOELASTIC_SPRINGS, ParticleSystem::tot_fluidsprings, PTCacheExtra::totdata, and PTCacheExtra::type.
Referenced by BKE_ptcache_id_from_particles().
static void ptcache_particle_interpolate (int index, void * psys_v, void ** data, float cfra, float cfra1, float cfra2, float * old_data) [static]
Definition at line 326 of file pointcache.c.
References BKE_ptcache_make_particle_key(), BPHYS_DATA_LOCATION, BPHYS_DATA_ROTATION, BPHYS_DATA_VELOCITY, co, ParticleData::dietime, ImBuf::index, interp_qt_qtqt(), MAX2, MIN2, mul_v3_fl(), OB_NEGX, OB_POSZ, ParticleSystem::part, ParticleSystem::particles, ParticleSystem::pointcache, psys_interpolate_particle(), ParticleKey::rot, rot, ParticleData::state, PointCache::step, sub_v3_v3v3(), ParticleKey::time, ParticleData::time, ParticleSettings::timetweak, ParticleSystem::totpart, vec_to_quat(), and ParticleKey::vel.
Referenced by BKE_ptcache_id_from_particles().
static void ptcache_particle_read (int index, void * psys_v, void ** data, float cfra, float * old_data) [static]
Definition at line 264 of file pointcache.c.
References BKE_ptcache_make_particle_key(), ParticleData::boid, BPHYS_DATA_BOIDS, BPHYS_DATA_LOCATION, BPHYS_DATA_ROTATION, BPHYS_DATA_SIZE, BPHYS_DATA_TIMES, BPHYS_DATA_VELOCITY, ParticleKey::co, BoidParticle::data, ParticleData::dietime, if(), ImBuf::index, ParticleData::lifetime, mul_v3_fl(), NULL, ParticleSystem::part, PART_PHYS_BOIDS, ParticleSystem::particles, ParticleSettings::phystype, ParticleData::prev_state, PTCACHE_DATA_TO, ParticleKey::rot, ParticleData::size, ParticleData::state, sub_v3_v3v3(), ParticleData::time, ParticleKey::time, ParticleSettings::timetweak, ParticleSystem::totpart, and ParticleKey::vel.
Referenced by BKE_ptcache_id_from_particles().
static int ptcache_particle_totpoint (void * psys_v, int UNUSEDcfra) [static]
Definition at line 388 of file pointcache.c.
References ParticleSystem::totpart.
Referenced by BKE_ptcache_id_from_particles().
static int ptcache_particle_totwrite (void * psys_v, int cfra) [static]
Definition at line 393 of file pointcache.c.
References p, ParticleSystem::particles, ParticleSystem::pointcache, PointCache::step, step(), ParticleData::time, and ParticleSystem::totpart.
Referenced by BKE_ptcache_id_from_particles().
static int ptcache_particle_write (int index, void * psys_v, void ** data, int cfra) [static]
Definition at line 234 of file pointcache.c.
References ParticleKey::ave, ParticleData::boid, BPHYS_DATA_AVELOCITY, BPHYS_DATA_BOIDS, BPHYS_DATA_INDEX, BPHYS_DATA_LOCATION, BPHYS_DATA_ROTATION, BPHYS_DATA_SIZE, BPHYS_DATA_TIMES, BPHYS_DATA_VELOCITY, ParticleKey::co, BoidParticle::data, ParticleData::dietime, if(), ImBuf::index, ParticleData::lifetime, NULL, ParticleSystem::part, PART_PHYS_BOIDS, ParticleSystem::particles, ParticleSettings::phystype, ParticleSystem::pointcache, ParticleData::prev_state, PTCACHE_DATA_FROM, ParticleKey::rot, ParticleData::size, ParticleData::state, PointCache::step, step(), ParticleKey::time, ParticleData::time, and ParticleKey::vel.
Referenced by BKE_ptcache_id_from_particles().
static int ptcache_path (PTCacheID * pid, char * filename) [static]
Definition at line 1045 of file pointcache.c.
References abs(), BLI_add_slash(), BLI_path_abs(), BLI_snprintf(), BLI_split_file_part(), BLI_temporary_dir(), PTCacheID::cache, Library::filepath, PointCache::flag, G, i, Object::id, if(), ID::lib, MAX_PTCACHE_PATH, NULL, PTCacheID::ob, PointCache::path, PTCACHE_EXTERNAL, PTCACHE_IGNORE_LIBPATH, PTCACHE_PATH, and strlen().
Referenced by BKE_ptcache_disk_cache_rename(), BKE_ptcache_id_clear(), BKE_ptcache_id_time(), BKE_ptcache_load_external(), BKE_ptcache_remove(), and ptcache_filename().
static int ptcache_read (PTCacheID * pid, int cfra) [static]
Definition at line 1754 of file pointcache.c.
References BKE_ptcache_mem_pointers_incr(), BKE_ptcache_mem_pointers_init(), BPHYS_DATA_INDEX, PTCacheID::cache, PTCacheID::calldata, PTCacheMem::cur, PTCacheMem::data_types, PTCacheID::data_types, PTCacheMem::extradata, ListBase::first, PointCache::flag, PTCacheMem::frame, i, PointCache::mem_cache, MEM_freeN(), MIN2, PTCacheMem::next, NULL, ptcache_data_free(), PTCACHE_DISK_CACHE, ptcache_disk_frame_to_mem(), ptcache_extra_free(), PTCacheID::read_extra_data, PTCacheID::read_point, PTCacheID::totpoint, and PTCacheMem::totpoint.
Referenced by BKE_ptcache_read().
static int ptcache_read_stream (PTCacheID * pid, int cfra) [static]
Definition at line 1719 of file pointcache.c.
References PTCacheID::calldata, error(), G, G_DEBUG, NULL, ptcache_file_close(), ptcache_file_header_begin_read(), ptcache_file_open(), ptcache_file_pointers_init(), PTCACHE_FILE_READ, PTCacheID::read_header, PTCacheID::read_stream, PTCacheID::totpoint, PTCacheFile::totpoint, PTCacheID::type, and PTCacheFile::type.
Referenced by BKE_ptcache_read().
static int ptcache_smoke_read (PTCacheFile * UNUSEDpf, void * UNUSEDsmoke_v) [static]
Definition at line 663 of file pointcache.c.
Referenced by BKE_ptcache_id_from_smoke().
static int ptcache_smoke_totpoint (void * UNUSEDsmoke_v, int UNUSEDcfra) [static]
Definition at line 662 of file pointcache.c.
Referenced by BKE_ptcache_id_from_smoke().
static int ptcache_smoke_write (PTCacheFile * UNUSEDpf, void * UNUSEDsmoke_v) [static]
Definition at line 664 of file pointcache.c.
Referenced by BKE_ptcache_id_from_smoke().
static void ptcache_softbody_interpolate (int index, void * soft_v, void ** data, float cfra, float cfra1, float cfra2, float * old_data) [static]
Definition at line 180 of file pointcache.c.
References BKE_ptcache_make_particle_key(), SoftBody::bpoint, ParticleKey::co, co, copy_v3_v3(), ImBuf::index, mul_v3_fl(), BodyPoint::pos, psys_interpolate_particle(), BodyPoint::vec, and ParticleKey::vel.
Referenced by BKE_ptcache_id_from_softbody().
static void ptcache_softbody_read (int index, void * soft_v, void ** data, float UNUSEDcfra, float * old_data) [static]
Definition at line 166 of file pointcache.c.
References BPHYS_DATA_LOCATION, BPHYS_DATA_VELOCITY, SoftBody::bpoint, ImBuf::index, BodyPoint::pos, PTCACHE_DATA_TO, and BodyPoint::vec.
Referenced by BKE_ptcache_id_from_softbody().
static int ptcache_softbody_totpoint (void * soft_v, int UNUSEDcfra) [static]
Definition at line 212 of file pointcache.c.
References SoftBody::totpoint.
Referenced by BKE_ptcache_id_from_softbody().
static int ptcache_softbody_write (int index, void * soft_v, void ** data, int UNUSEDcfra) [static]
Definition at line 156 of file pointcache.c.
References BPHYS_DATA_LOCATION, BPHYS_DATA_VELOCITY, SoftBody::bpoint, ImBuf::index, BodyPoint::pos, PTCACHE_DATA_FROM, and BodyPoint::vec.
Referenced by BKE_ptcache_id_from_softbody().
static int ptcache_write (PTCacheID * pid, int cfra, int overwrite) [static]
Definition at line 1962 of file pointcache.c.
References BKE_ptcache_id_exist(), BKE_ptcache_mem_pointers_incr(), BKE_ptcache_mem_pointers_init(), BKE_ptcache_mem_pointers_seek(), BLI_addtail(), PTCacheID::cache, PTCacheID::calldata, PTCacheMem::cur, PTCacheID::data_types, PTCacheMem::data_types, error(), PointCache::flag, PTCacheMem::frame, i, PTCacheID::info_types, ListBase::last, PointCache::mem_cache, MEM_callocN(), MEM_freeN(), NULL, ptcache_data_alloc(), ptcache_data_free(), PTCACHE_DISK_CACHE, ptcache_disk_frame_to_mem(), ptcache_extra_free(), ptcache_mem_frame_to_disk(), PointCache::startframe, PTCacheMem::totpoint, PTCacheID::totpoint, PTCacheID::totwrite, PTCacheID::write_extra_data, and PTCacheID::write_point.
Referenced by BKE_ptcache_write().
static int ptcache_write_needed (PTCacheID * pid, int cfra, int * overwrite) [static]
Definition at line 2031 of file pointcache.c.
References BKE_ptcache_id_clear(), BKE_ptcache_id_exist(), PTCacheID::cache, PointCache::endframe, PointCache::flag, PTCacheMem::frame, ListBase::last, PointCache::mem_cache, NULL, PTCacheMem::prev, PTCACHE_CLEAR_ALL, PTCACHE_CLEAR_FRAME, PTCACHE_DISK_CACHE, PTCACHE_REDO_NEEDED, PointCache::startframe, step(), and PointCache::step.
Referenced by BKE_ptcache_write().
static int ptcache_write_stream (PTCacheID * pid, int cfra, int totpoint) [static]
Definition at line 1929 of file pointcache.c.
References BKE_ptcache_id_clear(), PTCacheID::calldata, PTCacheFile::data_types, PTCacheID::data_types, error(), PTCacheFile::flag, G, G_DEBUG, NULL, PTCACHE_CLEAR_FRAME, ptcache_file_close(), ptcache_file_header_begin_write(), ptcache_file_open(), PTCACHE_FILE_WRITE, PTCacheFile::totpoint, PTCacheID::type, PTCacheFile::type, PTCacheID::write_header, and PTCacheID::write_stream.
Referenced by BKE_ptcache_write().
Variable Documentation
int CONTINUE_PHYSICS = 0 [static]
Definition at line 2579 of file pointcache.c.
Referenced by BKE_ptcache_get_continue_physics().
int ptcache_data_size[] [static]
Initial value:
 {
        sizeof(unsigned int),
        3 * sizeof(float),
        3 * sizeof(float),
        4 * sizeof(float),
        3 * sizeof(float),
        sizeof(float),
        3 * sizeof(float),
        sizeof(BoidData)
}
Definition at line 108 of file pointcache.c.
Referenced by BKE_ptcache_data_size(), BKE_ptcache_mem_pointers_incr(), BKE_ptcache_mem_pointers_seek(), ptcache_data_alloc(), ptcache_data_copy(), ptcache_disk_frame_to_mem(), ptcache_file_data_read(), ptcache_file_data_write(), and ptcache_mem_frame_to_disk().
int ptcache_extra_datasize[] [static]
Initial value:
 {
    0,
    sizeof(ParticleSpring)
}
Definition at line 119 of file pointcache.c.
Referenced by ptcache_disk_frame_to_mem(), ptcache_mem_frame_to_disk(), and ptcache_particle_extra_write().