Blender: SculptUndoNode Struct Reference
SculptUndoNode Struct Reference
#include <sculpt_intern.h>
Public Attributes
struct SculptUndoNode * next
struct SculptUndoNode * prev
SculptUndoType type
char idname [MAX_ID_NAME]
void * node
float(* co)[3]
float(* orig_co)[3]
short(* no)[3]
int totvert
int maxvert
int * index
BLI_bitmap vert_hidden
int maxgrid
int gridsize
int totgrid
int * grids
BLI_bitmap * grid_hidden
float * layer_disp
char shapeName [sizeof(((KeyBlock *) 0))->name]
Detailed Description
Definition at line 75 of file sculpt_intern.h.
Member Data Documentation
float(* SculptUndoNode::co)[3]
Definition at line 83 of file sculpt_intern.h.
Referenced by calc_area_normal(), calc_area_normal_and_flatten_center(), calc_flatten_center(), do_grab_brush(), do_layer_brush(), do_rotate_brush(), do_thumb_brush(), sculpt_combine_proxies(), sculpt_raycast_cb(), sculpt_restore_mesh(), sculpt_undo_alloc_node(), sculpt_undo_free(), sculpt_undo_restore_coords(), sculpt_undo_restore_deformed(), and sculpt_undo_store_coords().
BLI_bitmap* SculptUndoNode::grid_hidden
Definition at line 98 of file sculpt_intern.h.
Referenced by sculpt_undo_alloc_and_store_hidden(), sculpt_undo_free(), and sculpt_undo_restore_hidden().
int* SculptUndoNode::grids
Definition at line 97 of file sculpt_intern.h.
Referenced by sculpt_undo_alloc_node(), sculpt_undo_free(), sculpt_undo_push_node(), sculpt_undo_restore_coords(), sculpt_undo_restore_hidden(), and sculpt_undo_store_hidden().
int SculptUndoNode::gridsize
Definition at line 95 of file sculpt_intern.h.
Referenced by sculpt_undo_alloc_node(), sculpt_undo_restore(), and sculpt_undo_restore_coords().
char SculptUndoNode::idname[MAX_ID_NAME]
Definition at line 80 of file sculpt_intern.h.
Referenced by sculpt_undo_alloc_node(), and sculpt_undo_restore().
int* SculptUndoNode::index
Definition at line 90 of file sculpt_intern.h.
Referenced by sculpt_undo_alloc_node(), sculpt_undo_free(), sculpt_undo_push_node(), sculpt_undo_restore_coords(), sculpt_undo_restore_hidden(), and sculpt_undo_store_coords().
float* SculptUndoNode::layer_disp
Definition at line 101 of file sculpt_intern.h.
Referenced by do_layer_brush(), sculpt_undo_free(), and sculpt_undo_push_end().
int SculptUndoNode::maxgrid
Definition at line 94 of file sculpt_intern.h.
Referenced by sculpt_undo_alloc_node(), sculpt_undo_restore(), sculpt_undo_restore_coords(), and sculpt_undo_restore_hidden().
int SculptUndoNode::maxvert
Definition at line 89 of file sculpt_intern.h.
Referenced by sculpt_undo_alloc_node(), sculpt_undo_restore(), sculpt_undo_restore_coords(), and sculpt_undo_restore_hidden().
struct SculptUndoNode* SculptUndoNode::next
Definition at line 76 of file sculpt_intern.h.
Referenced by sculpt_undo_free(), sculpt_undo_get_node(), sculpt_undo_push_end(), and sculpt_undo_restore().
short(* SculptUndoNode::no)[3]
Definition at line 85 of file sculpt_intern.h.
Referenced by calc_area_normal(), calc_area_normal_and_flatten_center(), do_grab_brush(), do_rotate_brush(), do_thumb_brush(), sculpt_restore_mesh(), sculpt_undo_alloc_node(), sculpt_undo_free(), sculpt_undo_push_end(), and sculpt_undo_store_coords().
void* SculptUndoNode::node
Definition at line 81 of file sculpt_intern.h.
Referenced by sculpt_undo_alloc_and_store_hidden(), sculpt_undo_alloc_node(), sculpt_undo_get_node(), sculpt_undo_store_coords(), and sculpt_undo_store_hidden().
float(* SculptUndoNode::orig_co)[3]
Definition at line 84 of file sculpt_intern.h.
Referenced by sculpt_undo_alloc_node(), sculpt_undo_free(), sculpt_undo_restore_coords(), sculpt_undo_restore_deformed(), and sculpt_undo_store_coords().
struct SculptUndoNode * SculptUndoNode::prev
Definition at line 76 of file sculpt_intern.h.
char SculptUndoNode::shapeName[sizeof(((KeyBlock *) 0))->name]
Definition at line 104 of file sculpt_intern.h.
Referenced by sculpt_undo_push_node(), and sculpt_undo_restore_coords().
int SculptUndoNode::totgrid
Definition at line 96 of file sculpt_intern.h.
Referenced by sculpt_undo_alloc_and_store_hidden(), sculpt_undo_alloc_node(), sculpt_undo_free(), sculpt_undo_push_node(), sculpt_undo_restore_coords(), and sculpt_undo_restore_hidden().
int SculptUndoNode::totvert
Definition at line 86 of file sculpt_intern.h.
Referenced by do_layer_brush(), sculpt_undo_alloc_node(), sculpt_undo_push_node(), sculpt_undo_restore_coords(), and sculpt_undo_restore_hidden().
SculptUndoType SculptUndoNode::type
Definition at line 78 of file sculpt_intern.h.
Referenced by sculpt_undo_alloc_node(), and sculpt_undo_restore().
BLI_bitmap SculptUndoNode::vert_hidden
Definition at line 91 of file sculpt_intern.h.
Referenced by sculpt_undo_alloc_node(), sculpt_undo_free(), sculpt_undo_restore_hidden(), and sculpt_undo_store_hidden().
The documentation for this struct was generated from the following file:
sculpt_intern.h