Blender: RAS_IPolygonMaterial.h File Reference
RAS_IPolygonMaterial.h File Reference
Rasterizer
#include "STR_HashedString.h"
#include "MT_Vector3.h"
Classes
class RAS_IPolyMaterial
Enumerations
enum MaterialProps {
RAS_ZSORT = 1, RAS_TRANSPARENT = 2, RAS_TRIANGLE = 4, RAS_MULTITEX = 8,
RAS_MULTILIGHT = 16, RAS_BLENDERMAT = 32, RAS_GLSHADER = 64, RAS_AUTOGEN = 128,
RAS_NORMAL = 256, RAS_DEFMULTI = 512, RAS_BLENDERGLSL = 1024, RAS_CASTSHADOW = 2048
}
Functions
bool operator== (const RAS_IPolyMaterial &rhs, const RAS_IPolyMaterial &lhs)
bool operator< (const RAS_IPolyMaterial &lhs, const RAS_IPolyMaterial &rhs)
Detailed Description
Definition in file RAS_IPolygonMaterial.h.
Enumeration Type Documentation
enum MaterialProps
Enumerator:
RAS_ZSORT
RAS_TRANSPARENT
RAS_TRIANGLE
RAS_MULTITEX
RAS_MULTILIGHT
RAS_BLENDERMAT
RAS_GLSHADER
RAS_AUTOGEN
RAS_NORMAL
RAS_DEFMULTI
RAS_BLENDERGLSL
RAS_CASTSHADOW
Definition at line 52 of file RAS_IPolygonMaterial.h.
Function Documentation
bool operator< (const RAS_IPolyMaterial & lhs, const RAS_IPolyMaterial & rhs) [inline]
Definition at line 202 of file RAS_IPolygonMaterial.h.
References RAS_IPolyMaterial::Less().
bool operator== (const RAS_IPolyMaterial & rhs, const RAS_IPolyMaterial & lhs) [inline]
Definition at line 197 of file RAS_IPolygonMaterial.h.
References RAS_IPolyMaterial::Equals().
Referenced by ATTRIBUTE_ALIGNED16().