Blender: btSoftBody::Body Struct Reference
btSoftBody::Body Struct Reference
#include <btSoftBody.h>
Public Member Functions
Body ()
Body (Cluster *p)
Body (btCollisionObject *colObj)
void activate () const
const btMatrix3x3 & invWorldInertia () const
btScalar invMass () const
const btTransform & xform () const
btVector3 linearVelocity () const
btVector3 angularVelocity (const btVector3 &rpos) const
btVector3 angularVelocity () const
btVector3 velocity (const btVector3 &rpos) const
void applyVImpulse (const btVector3 &impulse, const btVector3 &rpos) const
void applyDImpulse (const btVector3 &impulse, const btVector3 &rpos) const
void applyImpulse (const Impulse &impulse, const btVector3 &rpos) const
void applyVAImpulse (const btVector3 &impulse) const
void applyDAImpulse (const btVector3 &impulse) const
void applyAImpulse (const Impulse &impulse) const
void applyDCImpulse (const btVector3 &impulse) const
Public Attributes
Cluster * m_soft
btRigidBody * m_rigid
btCollisionObject * m_collisionObject
Detailed Description
Definition at line 369 of file btSoftBody.h.
Constructor & Destructor Documentation
btSoftBody::Body::Body () [inline]
Definition at line 375 of file btSoftBody.h.
btSoftBody::Body::Body (Cluster * p) [inline]
Definition at line 376 of file btSoftBody.h.
btSoftBody::Body::Body (btCollisionObject * colObj) [inline]
Definition at line 377 of file btSoftBody.h.
References m_collisionObject, m_rigid, and btSoftBody::upcast().
Member Function Documentation
void btSoftBody::Body::activate () const [inline]
Definition at line 382 of file btSoftBody.h.
References m_collisionObject, and m_rigid.
btVector3 btSoftBody::Body::angularVelocity (const btVector3 & rpos) const [inline]
Definition at line 416 of file btSoftBody.h.
References btCross(), btRigidBody::getAngularVelocity(), btSoftBody::Cluster::m_av, m_rigid, and m_soft.
btVector3 btSoftBody::Body::angularVelocity () const [inline]
Definition at line 422 of file btSoftBody.h.
References btRigidBody::getAngularVelocity(), btSoftBody::Cluster::m_av, m_rigid, and m_soft.
Referenced by velocity().
void btSoftBody::Body::applyAImpulse (const Impulse & impulse) const [inline]
Definition at line 465 of file btSoftBody.h.
References applyDAImpulse(), applyVAImpulse(), btSoftBody::Impulse::m_asDrift, btSoftBody::Impulse::m_asVelocity, btSoftBody::Impulse::m_drift, and btSoftBody::Impulse::m_velocity.
void btSoftBody::Body::applyDAImpulse (const btVector3 & impulse) const [inline]
Definition at line 460 of file btSoftBody.h.
References btRigidBody::applyTorqueImpulse(), btSoftBody::clusterDAImpulse(), m_rigid, and m_soft.
Referenced by applyAImpulse().
void btSoftBody::Body::applyDCImpulse (const btVector3 & impulse) const [inline]
Definition at line 470 of file btSoftBody.h.
References btRigidBody::applyCentralImpulse(), btSoftBody::clusterDCImpulse(), m_rigid, and m_soft.
void btSoftBody::Body::applyDImpulse (const btVector3 & impulse, const btVector3 & rpos) const [inline]
Definition at line 437 of file btSoftBody.h.
References btRigidBody::applyImpulse(), btSoftBody::clusterDImpulse(), m_rigid, and m_soft.
Referenced by applyImpulse().
void btSoftBody::Body::applyImpulse (const Impulse & impulse, const btVector3 & rpos) const [inline]
Definition at line 442 of file btSoftBody.h.
References applyDImpulse(), applyVImpulse(), btSoftBody::Impulse::m_asDrift, btSoftBody::Impulse::m_asVelocity, btSoftBody::Impulse::m_drift, and btSoftBody::Impulse::m_velocity.
void btSoftBody::Body::applyVAImpulse (const btVector3 & impulse) const [inline]
Definition at line 455 of file btSoftBody.h.
References btRigidBody::applyTorqueImpulse(), btSoftBody::clusterVAImpulse(), m_rigid, and m_soft.
Referenced by applyAImpulse().
void btSoftBody::Body::applyVImpulse (const btVector3 & impulse, const btVector3 & rpos) const [inline]
Definition at line 432 of file btSoftBody.h.
References btRigidBody::applyImpulse(), btSoftBody::clusterVImpulse(), m_rigid, and m_soft.
Referenced by applyImpulse().
btScalar btSoftBody::Body::invMass () const [inline]
Definition at line 397 of file btSoftBody.h.
References btRigidBody::getInvMass(), btSoftBody::Cluster::m_imass, m_rigid, and m_soft.
Referenced by btSoftColliders::ClusterBase::SolveContact().
const btMatrix3x3& btSoftBody::Body::invWorldInertia () const [inline]
Definition at line 390 of file btSoftBody.h.
References btRigidBody::getInvInertiaTensorWorld(), btSoftBody::Cluster::m_invwi, m_rigid, and m_soft.
Referenced by btSoftColliders::ClusterBase::SolveContact().
btVector3 btSoftBody::Body::linearVelocity () const [inline]
Definition at line 410 of file btSoftBody.h.
References btRigidBody::getLinearVelocity(), btSoftBody::Cluster::m_lv, m_rigid, and m_soft.
Referenced by velocity().
btVector3 btSoftBody::Body::velocity (const btVector3 & rpos) const [inline]
Definition at line 428 of file btSoftBody.h.
References angularVelocity(), and linearVelocity().
Referenced by btSoftColliders::ClusterBase::SolveContact().
const btTransform& btSoftBody::Body::xform () const [inline]
Definition at line 403 of file btSoftBody.h.
References btTransform::getIdentity(), m_collisionObject, btSoftBody::Cluster::m_framexform, and m_soft.
Referenced by btSoftBody::appendAngularJoint(), btSoftBody::appendLinearJoint(), and btSoftColliders::ClusterBase::SolveContact().
Member Data Documentation
btCollisionObject* btSoftBody::Body::m_collisionObject
Definition at line 373 of file btSoftBody.h.
Referenced by activate(), Body(), and xform().
btRigidBody* btSoftBody::Body::m_rigid
Definition at line 372 of file btSoftBody.h.
Referenced by activate(), angularVelocity(), applyDAImpulse(), applyDCImpulse(), applyDImpulse(), applyVAImpulse(), applyVImpulse(), Body(), invMass(), invWorldInertia(), and linearVelocity().
Cluster* btSoftBody::Body::m_soft
Definition at line 371 of file btSoftBody.h.
Referenced by angularVelocity(), applyDAImpulse(), applyDCImpulse(), applyDImpulse(), applyVAImpulse(), applyVImpulse(), invMass(), invWorldInertia(), linearVelocity(), and xform().
The documentation for this struct was generated from the following file:
btSoftBody.h