Blender: BLI_vfontdata.h File Reference
BLI_vfontdata.h File Reference
blenlib
A structure to represent vector fonts, and to load them from PostScript fonts.
#include "DNA_listBase.h"
Classes
struct VFontData
struct VChar
struct TmpFont
Defines
#define MAX_VF_CHARS 256
Typedefs
typedef struct VFontData VFontData
typedef struct VChar VChar
Functions
VFontData * BLI_vfontdata_from_freetypefont (struct PackedFile *pf)
int BLI_vfontchar_from_freetypefont (struct VFont *vfont, unsigned long character)
Detailed Description
A structure to represent vector fonts, and to load them from PostScript fonts.
Definition in file BLI_vfontdata.h.
Define Documentation
#define MAX_VF_CHARS 256
Definition at line 42 of file BLI_vfontdata.h.
Typedef Documentation
typedef struct VChar VChar
typedef struct VFontData VFontData
Function Documentation
int BLI_vfontchar_from_freetypefont (struct VFont * vfont, unsigned long character)
Definition at line 503 of file freetypefont.c.
References err, FALSE, library, objchr_to_ftvfontdata(), and TRUE.
Referenced by BKE_text_to_curve().
VFontData* BLI_vfontdata_from_freetypefont (struct PackedFile * pf)
Construct a new VFontData structure from Freetype font data in a PackedFile.
Parameters:
pf The font data.
Return values:
A new VFontData structure, or NULL if unable to load.
Definition at line 479 of file freetypefont.c.
References check_freetypefont(), err, library, NULL, and objfnt_to_ftvfontdata().
Referenced by load_vfont(), and vfont_get_data().