Blender: btMotionState Class Reference
btMotionState Class Reference
#include <btMotionState.h>
Public Member Functions
virtual ~btMotionState ()
virtual void getWorldTransform (btTransform &worldTrans) const =0
virtual void setWorldTransform (const btTransform &worldTrans)=0
Detailed Description
The btMotionState interface class allows the dynamics world to synchronize and interpolate the updated world transforms with graphics For optimizations, potentially only moving objects get synchronized (using setWorldPosition/setWorldOrientation)
Definition at line 23 of file btMotionState.h.
Constructor & Destructor Documentation
virtual btMotionState::~btMotionState () [inline, virtual]
Definition at line 27 of file btMotionState.h.
Member Function Documentation
virtual void btMotionState::getWorldTransform (btTransform & worldTrans) const [pure virtual]
Implemented in BlenderBulletMotionState, and btDefaultMotionState.
Referenced by btRigidBody::saveKinematicState(), btRigidBody::setMotionState(), btRigidBody::setupRigidBody(), and btRaycastVehicle::updateWheelTransformsWS().
virtual void btMotionState::setWorldTransform (const btTransform & worldTrans) [pure virtual]
Implemented in BlenderBulletMotionState, and btDefaultMotionState.
Referenced by btSimpleDynamicsWorld::synchronizeMotionStates(), and btDiscreteDynamicsWorld::synchronizeSingleMotionState().
The documentation for this class was generated from the following file:
btMotionState.h