Blender: bConstraintTypeInfo Struct Reference
bConstraintTypeInfo Struct Reference
#include <BKE_constraint.h>
Public Attributes
short type
short size
char name [32]
char structName [32]
void(* free_data)(struct bConstraint *con)
void(* relink_data)(struct bConstraint *con)
void(* id_looper)(struct bConstraint *con, ConstraintIDFunc func, void *userdata)
void(* copy_data)(struct bConstraint *con, struct bConstraint *src)
void(* new_data)(void *cdata)
int(* get_constraint_targets)(struct bConstraint *con, struct ListBase *list)
void(* flush_constraint_targets)(struct bConstraint *con, struct ListBase *list, short nocopy)
void(* get_target_matrix)(struct bConstraint *con, struct bConstraintOb *cob, struct bConstraintTarget *ct, float ctime)
void(* evaluate_constraint)(struct bConstraint *con, struct bConstraintOb *cob, struct ListBase *targets)
Detailed Description
Definition at line 80 of file BKE_constraint.h.
Member Data Documentation
void(* bConstraintTypeInfo::copy_data)(struct bConstraint *con, struct bConstraint *src)
Definition at line 95 of file BKE_constraint.h.
Referenced by copy_constraints().
void(* bConstraintTypeInfo::evaluate_constraint)(struct bConstraint *con, struct bConstraintOb *cob, struct ListBase *targets)
Definition at line 109 of file BKE_constraint.h.
Referenced by constraintRotLim(), constraintSizeLim(), constraintTransLim(), and solve_constraints().
void(* bConstraintTypeInfo::flush_constraint_targets)(struct bConstraint *con, struct ListBase *list, short nocopy)
Definition at line 103 of file BKE_constraint.h.
Referenced by armature_delete_selected_exec(), build_dag_object(), constraint_bone_name_fix(), copy_object_pose(), dag_object_time_update_flags(), DAG_pose_sort(), draw_object(), get_constraint_target_matrix(), joined_armature_fix_links(), BL_ArmatureObject::LoadConstraints(), pose_proxy_synchronize(), pose_select_constraint_target_exec(), relink_constraints(), RIG_reconnectControlBones(), separated_armature_fix_links(), set_constraint_nth_target(), solve_constraints(), subframe_updateObject(), test_constraints(), unlink_object(), and updateDuplicateSubtargetObjects().
void(* bConstraintTypeInfo::free_data)(struct bConstraint *con)
Definition at line 89 of file BKE_constraint.h.
Referenced by free_constraint_data().
int(* bConstraintTypeInfo::get_constraint_targets)(struct bConstraint *con, struct ListBase *list)
Definition at line 101 of file BKE_constraint.h.
Referenced by armature_delete_selected_exec(), build_dag_object(), constraint_bone_name_fix(), copy_object_pose(), dag_object_time_update_flags(), DAG_pose_sort(), draw_object(), get_constraint_target_matrix(), get_constraint_targets_for_solving(), joined_armature_fix_links(), BL_ArmatureObject::LoadConstraints(), pose_proxy_synchronize(), pose_select_constraint_target_exec(), relink_constraints(), RIG_reconnectControlBones(), separated_armature_fix_links(), set_constraint_nth_target(), subframe_updateObject(), test_constraints(), unlink_object(), and updateDuplicateSubtargetObjects().
void(* bConstraintTypeInfo::get_target_matrix)(struct bConstraint *con, struct bConstraintOb *cob, struct bConstraintTarget *ct, float ctime)
Definition at line 107 of file BKE_constraint.h.
Referenced by draw_object(), get_constraint_target_matrix(), and get_constraint_targets_for_solving().
void(* bConstraintTypeInfo::id_looper)(struct bConstraint *con, ConstraintIDFunc func, void *userdata)
Definition at line 93 of file BKE_constraint.h.
Referenced by copy_constraints(), and id_loop_constraints().
char bConstraintTypeInfo::name[32]
Definition at line 84 of file BKE_constraint.h.
Referenced by add_new_constraint_internal(), build_dag_object(), and draw_constraint().
void(* bConstraintTypeInfo::new_data)(void *cdata)
Definition at line 97 of file BKE_constraint.h.
Referenced by add_new_constraint_internal().
void(* bConstraintTypeInfo::relink_data)(struct bConstraint *con)
Definition at line 91 of file BKE_constraint.h.
Referenced by relink_constraints().
short bConstraintTypeInfo::size
Definition at line 83 of file BKE_constraint.h.
Referenced by add_new_constraint_internal().
char bConstraintTypeInfo::structName[32]
Definition at line 85 of file BKE_constraint.h.
Referenced by add_new_constraint_internal(), and write_constraints().
short bConstraintTypeInfo::type
Definition at line 82 of file BKE_constraint.h.
Referenced by build_dag_object(), dag_id_flush_update(), dag_object_time_update_flags(), do_versions(), draw_object(), object_solver_camera(), object_solver_inverted_matrix(), and unlink_movieclip().
The documentation for this struct was generated from the following file:
BKE_constraint.h