Blender: gpencil_intern.h File Reference
gpencil_intern.h File Reference
gpencil
Classes
struct bActListElem
Typedefs
typedef enum eGPencil_PaintModes eGPencil_PaintModes
typedef struct bActListElem bActListElem
typedef enum ACTFILTER_FLAGS ACTFILTER_FLAGS
typedef enum ACTCONT_TYPES ACTCONT_TYPES
Enumerations
enum eGPencil_PaintModes { GP_PAINTMODE_DRAW = 0, GP_PAINTMODE_ERASER, GP_PAINTMODE_DRAW_STRAIGHT, GP_PAINTMODE_DRAW_POLY }
enum ACTFILTER_FLAGS {
ACTFILTER_VISIBLE = (1<<0), ACTFILTER_SEL = (1<<1), ACTFILTER_FOREDIT = (1<<2), ACTFILTER_CHANNELS = (1<<3),
ACTFILTER_IPOKEYS = (1<<4), ACTFILTER_ONLYICU = (1<<5), ACTFILTER_FORDRAWING = (1<<6), ACTFILTER_ACTGROUPED = (1<<7)
}
enum ACTCONT_TYPES { ACTCONT_NONE = 0, ACTCONT_ACTION, ACTCONT_SHAPEKEY, ACTCONT_GPENCIL }
Functions
void GPENCIL_OT_draw (struct wmOperatorType *ot)
void GPENCIL_OT_data_add (struct wmOperatorType *ot)
void GPENCIL_OT_data_unlink (struct wmOperatorType *ot)
void GPENCIL_OT_layer_add (struct wmOperatorType *ot)
void GPENCIL_OT_active_frame_delete (struct wmOperatorType *ot)
void GPENCIL_OT_convert (struct wmOperatorType *ot)
void gpencil_undo_init (struct bGPdata *gpd)
void gpencil_undo_push (struct bGPdata *gpd)
void gpencil_undo_finish (void)
Detailed Description
Definition in file gpencil_intern.h.
Typedef Documentation
typedef enum ACTCONT_TYPES ACTCONT_TYPES
typedef enum ACTFILTER_FLAGS ACTFILTER_FLAGS
typedef struct bActListElem bActListElem
typedef enum eGPencil_PaintModes eGPencil_PaintModes
Enumeration Type Documentation
enum ACTCONT_TYPES
Enumerator:
ACTCONT_NONE
ACTCONT_ACTION
ACTCONT_SHAPEKEY
ACTCONT_GPENCIL
Definition at line 110 of file gpencil_intern.h.
enum ACTFILTER_FLAGS
Enumerator:
ACTFILTER_VISIBLE
ACTFILTER_SEL
ACTFILTER_FOREDIT
ACTFILTER_CHANNELS
ACTFILTER_IPOKEYS
ACTFILTER_ONLYICU
ACTFILTER_FORDRAWING
ACTFILTER_ACTGROUPED
Definition at line 98 of file gpencil_intern.h.
enum eGPencil_PaintModes
Enumerator:
GP_PAINTMODE_DRAW
GP_PAINTMODE_ERASER
GP_PAINTMODE_DRAW_STRAIGHT
GP_PAINTMODE_DRAW_POLY
Definition at line 48 of file gpencil_intern.h.
Function Documentation
void GPENCIL_OT_active_frame_delete (struct wmOperatorType * ot)
Definition at line 349 of file gpencil_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, gp_actframe_delete_exec(), gp_actframe_delete_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_gpencil().
void GPENCIL_OT_convert (struct wmOperatorType * ot)
Definition at line 632 of file gpencil_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, gp_convert_layer_exec(), gp_convert_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_gpencil().
void GPENCIL_OT_data_add (struct wmOperatorType * ot)
Definition at line 213 of file gpencil_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, gp_add_poll(), gp_data_add_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_gpencil().
void GPENCIL_OT_data_unlink (struct wmOperatorType * ot)
Definition at line 261 of file gpencil_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, gp_data_unlink_exec(), gp_data_unlink_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_gpencil().
void GPENCIL_OT_draw (struct wmOperatorType * ot)
Definition at line 1918 of file gpencil_paint.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, gpencil_draw_cancel(), gpencil_draw_exec(), gpencil_draw_invoke(), gpencil_draw_modal(), gpencil_draw_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_collection_runtime(), RNA_def_enum(), RNA_OperatorStrokeElement, and wmOperatorType::srna.
Referenced by ED_operatortypes_gpencil().
void GPENCIL_OT_layer_add (struct wmOperatorType * ot)
Definition at line 298 of file gpencil_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, gp_add_poll(), gp_layer_add_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_gpencil().
void gpencil_undo_finish (void)
Definition at line 152 of file gpencil_undo.c.
References BLI_freelistN(), ListBase::first, free_gpencil_data(), bGPundonode::gpd, MEM_freeN(), bGPundonode::next, and NULL.
Referenced by gpencil_draw_exit().
void gpencil_undo_init (struct bGPdata * gpd)
Definition at line 116 of file gpencil_undo.c.
References gpencil_undo_push().
Referenced by gp_session_initdata().
void gpencil_undo_push (struct bGPdata * gpd)
Definition at line 121 of file gpencil_undo.c.
References BLI_addtail(), BLI_freelinkN(), free_gpencil_data(), bGPundonode::gpd, gpencil_data_duplicate(), MEM_callocN(), MEM_freeN(), and bGPundonode::next.
Referenced by gpencil_stroke_end(), and gpencil_undo_init().