Blender: btOverlappingPairCache Class Reference
btOverlappingPairCache Class Reference
#include <btOverlappingPairCache.h>
Public Member Functions
virtual ~btOverlappingPairCache ()
virtual btBroadphasePair * getOverlappingPairArrayPtr ()=0
virtual const btBroadphasePair * getOverlappingPairArrayPtr () const =0
virtual btBroadphasePairArray & getOverlappingPairArray ()=0
virtual void cleanOverlappingPair (btBroadphasePair &pair, btDispatcher *dispatcher)=0
virtual int getNumOverlappingPairs () const =0
virtual void cleanProxyFromPairs (btBroadphaseProxy *proxy, btDispatcher *dispatcher)=0
virtual void setOverlapFilterCallback (btOverlapFilterCallback *callback)=0
virtual void processAllOverlappingPairs (btOverlapCallback *, btDispatcher *dispatcher)=0
virtual btBroadphasePair * findPair (btBroadphaseProxy *proxy0, btBroadphaseProxy *proxy1)=0
virtual bool hasDeferredRemoval ()=0
virtual void setInternalGhostPairCallback (btOverlappingPairCallback *ghostPairCallback)=0
virtual void sortOverlappingPairs (btDispatcher *dispatcher)=0
Detailed Description
The btOverlappingPairCache provides an interface for overlapping pair management (add, remove, storage), used by the btBroadphaseInterface broadphases. The btHashedOverlappingPairCache and btSortedOverlappingPairCache classes are two implementations.
Definition at line 60 of file btOverlappingPairCache.h.
Constructor & Destructor Documentation
virtual btOverlappingPairCache::~btOverlappingPairCache () [inline, virtual]
Definition at line 63 of file btOverlappingPairCache.h.
Referenced by btDbvtBroadphase::~btDbvtBroadphase(), btMultiSapBroadphase::~btMultiSapBroadphase(), and btSimpleBroadphase::~btSimpleBroadphase().
Member Function Documentation
virtual void btOverlappingPairCache::cleanOverlappingPair (btBroadphasePair & pair, btDispatcher * dispatcher) [pure virtual]
Implemented in btHashedOverlappingPairCache, btSortedOverlappingPairCache, and btNullPairCache.
Referenced by btMultiSapBroadphase::calculateOverlappingPairs(), btSimpleBroadphase::calculateOverlappingPairs(), and btDbvtBroadphase::performDeferredRemoval().
virtual void btOverlappingPairCache::cleanProxyFromPairs (btBroadphaseProxy * proxy, btDispatcher * dispatcher) [pure virtual]
Implemented in btHashedOverlappingPairCache, btSortedOverlappingPairCache, and btNullPairCache.
Referenced by CcdPhysicsEnvironment::refreshCcdPhysicsController(), btCollisionWorld::removeCollisionObject(), CcdPhysicsController::ReplaceControllerShape(), and btCollisionWorld::~btCollisionWorld().
virtual btBroadphasePair* btOverlappingPairCache::findPair (btBroadphaseProxy * proxy0, btBroadphaseProxy * proxy1) [pure virtual]
Implemented in btHashedOverlappingPairCache, btSortedOverlappingPairCache, and btNullPairCache.
Referenced by btSimpleBroadphase::calculateOverlappingPairs(), and btClosestNotMeConvexResultCallback::needsCollision().
virtual int btOverlappingPairCache::getNumOverlappingPairs () const [pure virtual]
Implemented in btHashedOverlappingPairCache, btSortedOverlappingPairCache, and btNullPairCache.
Referenced by btDbvtBroadphase::calculateOverlappingPairs(), and btSimulationIslandManager::findUnions().
virtual btBroadphasePairArray& btOverlappingPairCache::getOverlappingPairArray () [pure virtual]
Implemented in btHashedOverlappingPairCache, btSortedOverlappingPairCache, and btNullPairCache.
Referenced by btMultiSapBroadphase::calculateOverlappingPairs(), btSimpleBroadphase::calculateOverlappingPairs(), btDbvtBroadphase::collide(), and btDbvtBroadphase::performDeferredRemoval().
virtual const btBroadphasePair* btOverlappingPairCache::getOverlappingPairArrayPtr () const [pure virtual]
Implemented in btHashedOverlappingPairCache, btSortedOverlappingPairCache, and btNullPairCache.
virtual btBroadphasePair* btOverlappingPairCache::getOverlappingPairArrayPtr () [pure virtual]
Implemented in btHashedOverlappingPairCache, btSortedOverlappingPairCache, and btNullPairCache.
Referenced by btSimulationIslandManager::findUnions().
virtual bool btOverlappingPairCache::hasDeferredRemoval () [pure virtual]
Implemented in btSortedOverlappingPairCache, and btNullPairCache.
Referenced by btSimpleBroadphase::calculateOverlappingPairs(), and btDbvtBroadphase::performDeferredRemoval().
virtual void btOverlappingPairCache::processAllOverlappingPairs (btOverlapCallback * , btDispatcher * dispatcher) [pure virtual]
Implemented in btHashedOverlappingPairCache, btSortedOverlappingPairCache, and btNullPairCache.
Referenced by btCollisionDispatcher::dispatchAllCollisionPairs().
virtual void btOverlappingPairCache::setInternalGhostPairCallback (btOverlappingPairCallback * ghostPairCallback) [pure virtual]
Implemented in btSortedOverlappingPairCache, and btNullPairCache.
virtual void btOverlappingPairCache::setOverlapFilterCallback (btOverlapFilterCallback * callback) [pure virtual]
Implemented in btHashedOverlappingPairCache, btSortedOverlappingPairCache, and btNullPairCache.
Referenced by btMultiSapBroadphase::btMultiSapBroadphase(), and CcdPhysicsEnvironment::CcdPhysicsEnvironment().
virtual void btOverlappingPairCache::sortOverlappingPairs (btDispatcher * dispatcher) [pure virtual]
Implemented in btSortedOverlappingPairCache, and btNullPairCache.
The documentation for this class was generated from the following file:
btOverlappingPairCache.h