Blender: util_transform.cpp File Reference
util_transform.cpp File Reference
#include "util_math.h"
#include "util_transform.h"
Functions
static CCL_NAMESPACE_BEGIN bool transform_matrix4_gj_inverse (float R[][4], float M[][4])
Transform transform_inverse (const Transform &tfm)
Function Documentation
Transform transform_inverse (const Transform & tfm)
Definition at line 130 of file util_transform.cpp.
References M, R, T, transform_identity(), and transform_matrix4_gj_inverse().
Referenced by Object::apply_transform(), blender_camera_focal_distance(), Camera::device_update(), ObjectManager::device_update_transforms(), BVH::pack_triangle(), BlenderSync::sync_view(), and Camera::update().
static CCL_NAMESPACE_BEGIN bool transform_matrix4_gj_inverse (float R[][4], float M[][4]) [static]
Definition at line 56 of file util_transform.cpp.
References i.
Referenced by transform_inverse().