Blender: bsdf.h File Reference
bsdf.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device float fresnel_dielectric (float eta, const float3 N, const float3 I, float3 *R, float3 *T, bool *is_inside)
__device float fresnel_dielectric_cos (float cosi, float eta)
__device float fresnel_conductor (float cosi, float eta, float k)
__device float smooth_step (float edge0, float edge1, float x)
Function Documentation
__device float fresnel_conductor (float cosi, float eta, float k)
Definition at line 109 of file bsdf.h.
CCL_NAMESPACE_BEGIN __device float fresnel_dielectric (float eta, const float3 N, const float3 I, float3 * R, float3 * T, bool * is_inside)
Definition at line 38 of file bsdf.h.
References cos(), dot(), I, make_float3(), N, and sqrtf.
__device float fresnel_dielectric_cos (float cosi, float eta)
Definition at line 94 of file bsdf.h.
References A, B, fabsf, g, and sqrtf.
Referenced by svm_node_closure_bsdf(), svm_node_fresnel(), and svm_node_layer_weight().
__device float smooth_step (float edge0, float edge1, float x)
Definition at line 120 of file bsdf.h.