Blender: time_ops.c File Reference
time_ops.c File Reference
time line
#include <stdlib.h>
#include <math.h>
#include "DNA_scene_types.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "ED_screen.h"
#include "WM_api.h"
#include "WM_types.h"
#include "time_intern.h"
Functions
static int time_set_sfra_exec (bContext *C, wmOperator *UNUSED(op))
static void TIME_OT_start_frame_set (wmOperatorType *ot)
static int time_set_efra_exec (bContext *C, wmOperator *UNUSED(op))
static void TIME_OT_end_frame_set (wmOperatorType *ot)
static int time_view_all_exec (bContext *C, wmOperator *UNUSED(op))
static void TIME_OT_view_all (wmOperatorType *ot)
void time_operatortypes (void)
void time_keymap (wmKeyConfig *keyconf)
Detailed Description
Definition in file time_ops.c.
Function Documentation
void time_keymap (wmKeyConfig * keyconf)
Definition at line 188 of file time_ops.c.
References EKEY, HOMEKEY, KM_PRESS, SKEY, SPACE_TIME, WM_keymap_add_item(), and WM_keymap_find().
Referenced by ED_spacetype_time().
void time_operatortypes (void)
Definition at line 181 of file time_ops.c.
References TIME_OT_end_frame_set(), TIME_OT_start_frame_set(), TIME_OT_view_all(), and WM_operatortype_append().
Referenced by ED_spacetype_time().
static void TIME_OT_end_frame_set (wmOperatorType * ot) [static]
Definition at line 122 of file time_ops.c.
References wmOperatorType::description, ED_operator_timeline_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and time_set_efra_exec().
Referenced by time_operatortypes().
static void TIME_OT_start_frame_set (wmOperatorType * ot) [static]
Definition at line 78 of file time_ops.c.
References wmOperatorType::description, ED_operator_timeline_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and time_set_sfra_exec().
Referenced by time_operatortypes().
static void TIME_OT_view_all (wmOperatorType * ot) [static]
Definition at line 164 of file time_ops.c.
References wmOperatorType::description, ED_operator_timeline_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and time_view_all_exec().
Referenced by time_operatortypes().
static int time_set_efra_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 94 of file time_ops.c.
References CFRA, CTX_data_scene(), RenderData::efra, NC_SCENE, ND_FRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, RenderData::pefra, PRVRANGEON, RenderData::psfra, PSFRA, Scene::r, RenderData::sfra, and WM_event_add_notifier().
Referenced by TIME_OT_end_frame_set().
static int time_set_sfra_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 50 of file time_ops.c.
References CFRA, CTX_data_scene(), RenderData::efra, NC_SCENE, ND_FRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, RenderData::pefra, PEFRA, PRVRANGEON, RenderData::psfra, Scene::r, RenderData::sfra, and WM_event_add_notifier().
Referenced by TIME_OT_start_frame_set().
static int time_view_all_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 139 of file time_ops.c.
References CTX_data_scene(), CTX_wm_region(), View2D::cur, ED_region_tag_redraw(), ELEM, if(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, PEFRA, PSFRA, ARegion::v2d, rctf::xmax, and rctf::xmin.
Referenced by TIME_OT_view_all().