Blender: node_texture_util.c File Reference
node_texture_util.c File Reference
nodes
#include <assert.h>
#include "node_texture_util.h"
Defines
#define PREV_RES 128
Functions
static void tex_call_delegate (TexDelegate *dg, float *out, TexParams *params, short thread)
static void tex_input (float *out, int sz, bNodeStack *in, TexParams *params, short thread)
void tex_input_vec (float *out, bNodeStack *in, TexParams *params, short thread)
void tex_input_rgba (float *out, bNodeStack *in, TexParams *params, short thread)
float tex_input_value (bNodeStack *in, TexParams *params, short thread)
void params_from_cdata (TexParams *out, TexCallData *in)
void tex_do_preview (bNode *node, float *co, float *col)
void tex_output (bNode *node, bNodeStack **in, bNodeStack *out, TexFn texfn, TexCallData *cdata)
void ntreeTexCheckCyclics (struct bNodeTree *ntree)
Detailed Description
Definition in file node_texture_util.c.
Define Documentation
#define PREV_RES 128
Definition at line 52 of file node_texture_util.c.
Function Documentation
void ntreeTexCheckCyclics (struct bNodeTree * ntree)
Definition at line 145 of file node_texture_util.c.
References bNode::custom1, bNode::custom2, ListBase::first, bNode::id, if(), bNode::next, bNodeTree::nodes, Tex::nodetree, ntreeTexCheckCyclics(), TEX_NODE_TEXTURE, bNode::type, and Tex::use_nodes.
Referenced by ED_node_generic_update(), node_add_node(), and ntreeTexCheckCyclics().
void params_from_cdata (TexParams * out, TexCallData * in)
Definition at line 105 of file node_texture_util.c.
References TexParams::cfra, TexCallData::cfra, TexParams::co, TexCallData::co, TexParams::dxt, TexCallData::dxt, TexParams::dyt, TexCallData::dyt, TexParams::mtex, TexCallData::mtex, TexParams::osatex, TexCallData::osatex, TexParams::previewco, TexParams::shi, and TexCallData::shi.
Referenced by exec().
static void tex_call_delegate (TexDelegate * dg, float * out, TexParams * params, short thread) [static]
Definition at line 54 of file node_texture_util.c.
References TexDelegate::cdata, TexCallData::do_preview, TexDelegate::fn, TexDelegate::in, bNode::need_exec, TexDelegate::node, TexParams::previewco, and tex_do_preview().
Referenced by tex_input().
void tex_do_preview (bNode * node, float * co, float * col)
Definition at line 117 of file node_texture_util.c.
References nodeAddToPreview(), bNode::preview, bNodePreview::xsize, and bNodePreview::ysize.
Referenced by exec(), and tex_call_delegate().
static void tex_input (float * out, int sz, bNodeStack * in, TexParams * params, short thread) [static]
Definition at line 64 of file node_texture_util.c.
References bNodeStack::data, bNodeStack::hasoutput, SOCK_FLOAT, bNodeStack::sockettype, tex_call_delegate(), and bNodeStack::vec.
Referenced by tex_input_rgba(), and tex_input_vec().
void tex_input_rgba (float * out, bNodeStack * in, TexParams * params, short thread)
Definition at line 81 of file node_texture_util.c.
References bNodeStack::hasoutput, SOCK_FLOAT, SOCK_VECTOR, bNodeStack::sockettype, and tex_input().
Referenced by colorfn(), exec(), rgb_colorfn(), rgbtobw_valuefn(), texfn(), valuefn_a(), valuefn_b(), valuefn_g(), and valuefn_r().
float tex_input_value (bNodeStack * in, TexParams * params, short thread)
Definition at line 98 of file node_texture_util.c.
References tex_input_vec().
Referenced by clouds_map_inputs(), colorfn(), distnoise_map_inputs(), magic_map_inputs(), marble_map_inputs(), musgrave_map_inputs(), normalfn(), stucci_map_inputs(), valtorgb_colorfn(), valuefn(), voronoi_map_inputs(), and wood_map_inputs().
void tex_input_vec (float * out, bNodeStack * in, TexParams * params, short thread)
Definition at line 76 of file node_texture_util.c.
References tex_input().
Referenced by colorfn(), exec(), tex_input_value(), and valuefn().
void tex_output (bNode * node, bNodeStack ** in, bNodeStack * out, TexFn texfn, TexCallData * cdata)
Definition at line 129 of file node_texture_util.c.
References TexDelegate::cdata, bNodeStack::data, TexDelegate::fn, TexDelegate::in, MAX_SOCKET, MEM_mallocN(), TexDelegate::node, bNodeStack::sockettype, texfn(), and TexDelegate::type.
Referenced by exec(), rgb_exec(), rgbtobw_exec(), time_exec(), and valtorgb_exec().