Blender: rna_animation.c File Reference
rna_animation.c File Reference
RNA
#include <stdlib.h>
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_anim_types.h"
#include "DNA_action_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "ED_keyframing.h"
#include "WM_types.h"
Defines
#define KEYINGSET_IDNAME_DOC
Functions
static void rna_def_common_keying_flags (StructRNA *srna, short reg)
static void rna_def_keyingset_info (BlenderRNA *brna)
static void rna_def_keyingset_path (BlenderRNA *brna)
static void rna_def_keyingset_paths (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_keyingset (BlenderRNA *brna)
static void rna_api_animdata_nla_tracks (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_api_animdata_drivers (BlenderRNA *brna, PropertyRNA *cprop)
void rna_def_animdata_common (StructRNA *srna)
void rna_def_animdata (BlenderRNA *brna)
void RNA_def_animation (BlenderRNA *brna)
Variables
EnumPropertyItem keyingset_path_grouping_items []
Detailed Description
Definition in file rna_animation.c.
Define Documentation
#define KEYINGSET_IDNAME_DOC
Value:
"If this is set, the Keying Set gets a custom ID, otherwise it takes " \
                             "the name of the class used to define the Keying Set (for example, "   \
                             "if the class name is \"BUILTIN_KSI_location\", and bl_idname is not " \
                             "set by the script, then bl_idname = \"BUILTIN_KSI_location\")"
Definition at line 483 of file rna_animation.c.
Referenced by rna_def_keyingset(), and rna_def_keyingset_info().
Function Documentation
static void rna_api_animdata_drivers (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 789 of file rna_animation.c.
References FUNC_USE_CONTEXT, NULL, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_animdata().
static void rna_api_animdata_nla_tracks (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 753 of file rna_animation.c.
References FUNC_USE_CONTEXT, NA_SELECTED, NC_ANIMATION, ND_NLA, NULL, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_animdata().
void RNA_def_animation (BlenderRNA * brna)
Definition at line 886 of file rna_animation.c.
References rna_def_animdata(), rna_def_keyingset(), rna_def_keyingset_info(), and rna_def_keyingset_path().
void rna_def_animdata (BlenderRNA * brna)
Definition at line 821 of file rna_animation.c.
References ADT_NLA_EVAL_OFF, NC_ANIMATION, ND_NLA, nla_mode_blend_items, nla_mode_extend_items, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, rna_api_animdata_drivers(), rna_api_animdata_nla_tracks(), RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_collection_sdna(), RNA_def_property_editable_func(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_default(), RNA_def_property_float_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_animation().
void rna_def_animdata_common (StructRNA * srna)
Definition at line 811 of file rna_animation.c.
References NULL, PROP_EDITABLE, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_pointer_sdna(), and RNA_def_property_ui_text().
Referenced by rna_def_armature(), RNA_def_camera(), rna_def_curve(), rna_def_key(), rna_def_lamp(), rna_def_lattice(), RNA_def_material(), rna_def_mesh(), rna_def_metaball(), rna_def_nodetree(), rna_def_object(), rna_def_particle_settings(), RNA_def_scene(), rna_def_speaker(), rna_def_texture(), and RNA_def_world().
static void rna_def_common_keying_flags (StructRNA * srna, short reg) [static]
Definition at line 459 of file rna_animation.c.
References INSERTKEY_MATRIX, INSERTKEY_NEEDED, INSERTKEY_XYZ2RGB, NULL, PROP_ENUM, PROP_ENUM_FLAG, PROP_NONE, PROP_REGISTER_OPTIONAL, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), and RNA_def_property_ui_text().
Referenced by rna_def_keyingset(), rna_def_keyingset_info(), and rna_def_keyingset_path().
static void rna_def_keyingset (BlenderRNA * brna) [static]
Definition at line 693 of file rna_animation.c.
References KEYINGSET_ABSOLUTE, KEYINGSET_IDNAME_DOC, NA_RENAME, NC_SCENE, ND_KEYINGSET, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_NEVER_CLAMP, PROP_NONE, PROP_POINTER, PROP_REGISTER, PROP_REGISTER_OPTIONAL, PROP_STRING, PROP_TRANSLATE, RNA_api_keyingset(), rna_def_common_keying_flags(), rna_def_keyingset_paths(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and RNA_DYN_DESCR_MAX.
Referenced by RNA_def_animation().
static void rna_def_keyingset_info (BlenderRNA * brna) [static]
Definition at line 489 of file rna_animation.c.
References FUNC_REGISTER, KEYINGSET_IDNAME_DOC, NULL, PROP_NEVER_CLAMP, PROP_NEVER_NULL, PROP_NONE, PROP_REGISTER, PROP_REGISTER_OPTIONAL, PROP_REQUIRED, PROP_RNAPTR, PROP_STRING, PROP_TRANSLATE, RNA_def_boolean(), rna_def_common_keying_flags(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_string_maxlength(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_refine_func(), RNA_def_struct_register_funcs(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), RNA_define_verify_sdna(), and RNA_DYN_DESCR_MAX.
Referenced by RNA_def_animation().
static void rna_def_keyingset_path (BlenderRNA * brna) [static]
Definition at line 557 of file rna_animation.c.
References ID_OB, id_type_items, KSP_FLAG_WHOLE_ARRAY, NA_EDITED, NC_SCENE, ND_KEYINGSET, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, rna_def_common_keying_flags(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_editable_func(), RNA_def_property_enum_default(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_animation().
static void rna_def_keyingset_paths (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 624 of file rna_animation.c.
References FUNC_USE_REPORTS, KSP_GROUP_KSNAME, NULL, PROP_EDITABLE, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REQUIRED, RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_editable_func(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_keyingset().
Variable Documentation
EnumPropertyItem keyingset_path_grouping_items[]
Initial value:
 {
    {KSP_GROUP_NAMED, "NAMED", 0, "Named Group", ""},
    {KSP_GROUP_NONE, "NONE", 0, "None", ""},
    {KSP_GROUP_KSNAME, "KEYINGSET", 0, "Keying Set Name", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 47 of file rna_animation.c.