Blender: MT_Point2 Class Reference
MT_Point2 Class Reference
#include <MT_Point2.h>
Public Member Functions
MT_Point2 ()
MT_Point2 (const float *v2)
MT_Point2 (const double *v2)
MT_Point2 (MT_Scalar x2, MT_Scalar y2)
MT_Point2 & operator+= (const MT_Vector2 &v)
MT_Point2 & operator-= (const MT_Vector2 &v)
MT_Point2 & operator= (const MT_Vector2 &v)
MT_Scalar distance (const MT_Point2 &p) const
MT_Scalar distance2 (const MT_Point2 &p) const
MT_Point2 lerp (const MT_Point2 &p, MT_Scalar t) const
Detailed Description
Definition at line 52 of file MT_Point2.h.
Constructor & Destructor Documentation
MT_Point2::MT_Point2 () [inline]
Definition at line 54 of file MT_Point2.h.
Referenced by lerp().
MT_Point2::MT_Point2 (const float * v2) [inline]
Definition at line 55 of file MT_Point2.h.
MT_Point2::MT_Point2 (const double * v2) [inline]
Definition at line 56 of file MT_Point2.h.
MT_Point2::MT_Point2 (MT_Scalar x2, MT_Scalar y2) [inline]
Definition at line 57 of file MT_Point2.h.
Member Function Documentation
GEN_INLINE MT_Scalar MT_Point2::distance (const MT_Point2 & p) const
Definition at line 18 of file MT_Point2.inl.
Referenced by MT_distance().
GEN_INLINE MT_Scalar MT_Point2::distance2 (const MT_Point2 & p) const
Definition at line 22 of file MT_Point2.inl.
Referenced by MT_distance2().
GEN_INLINE MT_Point2 MT_Point2::lerp (const MT_Point2 & p, MT_Scalar t) const
Definition at line 26 of file MT_Point2.inl.
References MT_Tuple2::m_co, and MT_Point2().
Referenced by MT_lerp().
GEN_INLINE MT_Point2 & MT_Point2::operator+= (const MT_Vector2 & v)
Reimplemented from MT_Vector2.
Definition at line 3 of file MT_Point2.inl.
References MT_Tuple2::m_co.
GEN_INLINE MT_Point2 & MT_Point2::operator-= (const MT_Vector2 & v)
Reimplemented from MT_Vector2.
Definition at line 8 of file MT_Point2.inl.
References MT_Tuple2::m_co.
GEN_INLINE MT_Point2 & MT_Point2::operator= (const MT_Vector2 & v)
Definition at line 13 of file MT_Point2.inl.
References MT_Tuple2::m_co.
The documentation for this class was generated from the following files:
MT_Point2.h
MT_Point2.inl