Blender: MOD_shapekey.c File Reference
MOD_shapekey.c File Reference
modifiers
#include "BLI_math.h"
#include "DNA_key_types.h"
#include "BLI_utildefines.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_key.h"
#include "BKE_particle.h"
#include "MOD_modifiertypes.h"
#include "MEM_guardedalloc.h"
Functions
static void deformVerts (ModifierData *md, Object *ob, DerivedMesh *UNUSED(derivedData), float(*vertexCos)[3], int numVerts, int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
static void deformMatrices (ModifierData *md, Object *ob, DerivedMesh *derivedData, float(*vertexCos)[3], float(*defMats)[3][3], int numVerts)
static void deformVertsEM (ModifierData *md, Object *ob, struct BMEditMesh *UNUSED(editData), DerivedMesh *derivedData, float(*vertexCos)[3], int numVerts)
static void deformMatricesEM (ModifierData *UNUSED(md), Object *ob, struct BMEditMesh *UNUSED(editData), DerivedMesh *UNUSED(derivedData), float(*vertexCos)[3], float(*defMats)[3][3], int numVerts)
Variables
ModifierTypeInfo modifierType_ShapeKey
Detailed Description
Definition in file MOD_shapekey.c.
Function Documentation
static void deformMatrices (ModifierData * md, Object * ob, DerivedMesh * derivedData, float(*) vertexCos[3], float(*) defMats[3][3], int numVerts) [static]
Definition at line 70 of file MOD_shapekey.c.
References copy_m3_m3(), KeyBlock::curval, deformVerts(), ob_get_key(), ob_get_keyblock(), OB_SHAPE_LOCK, Key::refkey, scale_m3_fl(), Object::shapeflag, and KeyBlock::totelem.
static void deformMatricesEM (ModifierData * UNUSEDmd, Object * ob, struct BMEditMesh * UNUSEDeditData, DerivedMesh * UNUSEDderivedData, float(*) vertexCos[3], float(*) defMats[3][3], int numVerts) [static]
Definition at line 104 of file MOD_shapekey.c.
References copy_m3_m3(), KeyBlock::curval, ob_get_key(), ob_get_keyblock(), Key::refkey, scale_m3_fl(), and KeyBlock::totelem.
static void deformVerts (ModifierData * md, Object * ob, DerivedMesh * UNUSEDderivedData, float(*) vertexCos[3], int numVerts, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 51 of file MOD_shapekey.c.
References do_ob_key(), MEM_freeN(), ob_get_keyblock(), ModifierData::scene, and KeyBlock::totelem.
Referenced by deformMatrices(), and deformVertsEM().
static void deformVertsEM (ModifierData * md, Object * ob, struct BMEditMesh * UNUSEDeditData, DerivedMesh * derivedData, float(*) vertexCos[3], int numVerts) [static]
Definition at line 92 of file MOD_shapekey.c.
References deformVerts(), KEY_RELATIVE, ob_get_key(), and Key::type.
Variable Documentation
ModifierTypeInfo modifierType_ShapeKey
Initial value:
 {
                  "ShapeKey",
            "ShapeKeyModifierData",
            sizeof(ShapeKeyModifierData),
                  eModifierTypeType_OnlyDeform,
                 eModifierTypeFlag_AcceptsCVs
                            | eModifierTypeFlag_SupportsEditmode,
              NULL,
           deformVerts,
        deformMatrices,
         deformVertsEM,
      deformMatricesEM,
         NULL,
       NULL,
              NULL,
      NULL,
              NULL,
            NULL,
        NULL,
         NULL,
        NULL,
     NULL,
         NULL,
        NULL,
}
Definition at line 126 of file MOD_shapekey.c.