Blender: btDbvtAabbMm Struct Reference
btDbvtAabbMm Struct Reference
#include <btDbvt.h>
Public Member Functions
DBVT_INLINE btVector3 Center () const
DBVT_INLINE btVector3 Lengths () const
DBVT_INLINE btVector3 Extents () const
DBVT_INLINE const btVector3 & Mins () const
DBVT_INLINE const btVector3 & Maxs () const
DBVT_INLINE void Expand (const btVector3 &e)
DBVT_INLINE void SignedExpand (const btVector3 &e)
DBVT_INLINE bool Contain (const btDbvtAabbMm &a) const
DBVT_INLINE int Classify (const btVector3 &n, btScalar o, int s) const
DBVT_INLINE btScalar ProjectMinimum (const btVector3 &v, unsigned signs) const
Static Public Member Functions
static btDbvtAabbMm FromCE (const btVector3 &c, const btVector3 &e)
static btDbvtAabbMm FromCR (const btVector3 &c, btScalar r)
static btDbvtAabbMm FromMM (const btVector3 &mi, const btVector3 &mx)
static btDbvtAabbMm FromPoints (const btVector3 *pts, int n)
static btDbvtAabbMm FromPoints (const btVector3 **ppts, int n)
Friends
DBVT_INLINE friend bool Intersect (const btDbvtAabbMm &a, const btDbvtAabbMm &b)
DBVT_INLINE friend bool Intersect (const btDbvtAabbMm &a, const btVector3 &b)
DBVT_INLINE friend btScalar Proximity (const btDbvtAabbMm &a, const btDbvtAabbMm &b)
DBVT_INLINE friend int Select (const btDbvtAabbMm &o, const btDbvtAabbMm &a, const btDbvtAabbMm &b)
DBVT_INLINE friend void Merge (const btDbvtAabbMm &a, const btDbvtAabbMm &b, btDbvtAabbMm &r)
DBVT_INLINE friend bool NotEqual (const btDbvtAabbMm &a, const btDbvtAabbMm &b)
Detailed Description
Definition at line 130 of file btDbvt.h.
Member Function Documentation
DBVT_INLINE btVector3 btDbvtAabbMm::Center () const [inline]
Definition at line 132 of file btDbvt.h.
Referenced by DbvtCullingCallback::Descent(), drawTree(), and topdown().
DBVT_INLINE int btDbvtAabbMm::Classify (const btVector3 & n, btScalar o, int s) const
Definition at line 465 of file btDbvt.h.
References btDot().
Referenced by btDbvt::collideKDOP(), and btDbvt::collideOCL().
DBVT_INLINE bool btDbvtAabbMm::Contain (const btDbvtAabbMm & a) const
Definition at line 454 of file btDbvt.h.
Referenced by insertleaf(), and btDbvt::update().
DBVT_INLINE void btDbvtAabbMm::Expand (const btVector3 & e)
Definition at line 440 of file btDbvt.h.
Referenced by btDbvt::update(), and VolumeOf().
DBVT_INLINE btVector3 btDbvtAabbMm::Extents () const [inline]
Definition at line 134 of file btDbvt.h.
Referenced by DbvtCullingCallback::Descent(), and drawTree().
btDbvtAabbMm btDbvtAabbMm::FromCE (const btVector3 & c, const btVector3 & e) [inline, static]
Definition at line 392 of file btDbvt.h.
Referenced by FromCR().
btDbvtAabbMm btDbvtAabbMm::FromCR (const btVector3 & c, btScalar r) [inline, static]
Definition at line 400 of file btDbvt.h.
References FromCE().
Referenced by btSoftBody::appendNode(), btSoftBody::btSoftBody(), btDbvtBroadphase::getBroadphaseAabb(), btSoftBody::predictMotion(), btSoftBody::scale(), and btSoftBody::transform().
btDbvtAabbMm btDbvtAabbMm::FromMM (const btVector3 & mi, const btVector3 & mx) [inline, static]
Definition at line 406 of file btDbvt.h.
Referenced by btDbvtBroadphase::aabbTest(), btDbvtBroadphase::collide(), btDbvtBroadphase::createProxy(), btSoftBody::defaultCollisionHandler(), btSoftColliders::CollideCL_RS::Process(), btCompoundCollisionAlgorithm::processCollision(), btDbvtBroadphase::setAabb(), btDbvtBroadphase::setAabbForceUpdate(), and btSoftBody::updateClusters().
btDbvtAabbMm btDbvtAabbMm::FromPoints (const btVector3 * pts, int n) [inline, static]
Definition at line 414 of file btDbvt.h.
References i.
Referenced by VolumeOf().
btDbvtAabbMm btDbvtAabbMm::FromPoints (const btVector3 ** ppts, int n) [inline, static]
Definition at line 427 of file btDbvt.h.
References i.
DBVT_INLINE btVector3 btDbvtAabbMm::Lengths () const [inline]
Definition at line 133 of file btDbvt.h.
Referenced by size().
DBVT_INLINE const btVector3& btDbvtAabbMm::Maxs () const [inline]
Definition at line 136 of file btDbvt.h.
Referenced by btDbvtBroadphase::getBroadphaseAabb(), btCompoundLeafCallback::Process(), btDbvt::rayTest(), btDbvt::rayTestInternal(), and btSoftBody::updateBounds().
DBVT_INLINE const btVector3& btDbvtAabbMm::Mins () const [inline]
Definition at line 135 of file btDbvt.h.
Referenced by btDbvtBroadphase::getBroadphaseAabb(), btCompoundLeafCallback::Process(), btDbvt::rayTest(), btDbvt::rayTestInternal(), and btSoftBody::updateBounds().
DBVT_INLINE btScalar btDbvtAabbMm::ProjectMinimum (const btVector3 & v, unsigned signs) const
Definition at line 493 of file btDbvt.h.
References btDot(), and p.
Referenced by btDbvt::collideOCL().
DBVT_INLINE void btDbvtAabbMm::SignedExpand (const btVector3 & e)
Definition at line 446 of file btDbvt.h.
Referenced by btDbvt::update().
Friends And Related Function Documentation
DBVT_INLINE friend bool Intersect (const btDbvtAabbMm & a, const btDbvtAabbMm & b) [friend]
Definition at line 515 of file btDbvt.h.
DBVT_INLINE friend bool Intersect (const btDbvtAabbMm & a, const btVector3 & b) [friend]
Definition at line 536 of file btDbvt.h.
DBVT_INLINE friend void Merge (const btDbvtAabbMm & a, const btDbvtAabbMm & b, btDbvtAabbMm & r) [friend]
Definition at line 639 of file btDbvt.h.
DBVT_INLINE friend bool NotEqual (const btDbvtAabbMm & a, const btDbvtAabbMm & b) [friend]
Definition at line 662 of file btDbvt.h.
DBVT_INLINE friend btScalar Proximity (const btDbvtAabbMm & a, const btDbvtAabbMm & b) [friend]
Definition at line 555 of file btDbvt.h.
DBVT_INLINE friend int Select (const btDbvtAabbMm & o, const btDbvtAabbMm & a, const btDbvtAabbMm & b) [friend]
Definition at line 565 of file btDbvt.h.
The documentation for this struct was generated from the following file:
btDbvt.h