Blender: btSingleContactCallback Struct Reference
btSingleContactCallback Struct Reference
Public Member Functions
btSingleContactCallback (btCollisionObject *collisionObject, btCollisionWorld *world, btCollisionWorld::ContactResultCallback &resultCallback)
virtual bool process (const btBroadphaseProxy *proxy)
Public Attributes
btCollisionObject * m_collisionObject
btCollisionWorld * m_world
btCollisionWorld::ContactResultCallback & m_resultCallback
Detailed Description
Definition at line 1063 of file btCollisionWorld.cpp.
Constructor & Destructor Documentation
btSingleContactCallback::btSingleContactCallback (btCollisionObject * collisionObject, btCollisionWorld * world, btCollisionWorld::ContactResultCallback & resultCallback) [inline]
Definition at line 1071 of file btCollisionWorld.cpp.
Member Function Documentation
virtual bool btSingleContactCallback::process (const btBroadphaseProxy * proxy) [inline, virtual]
Implements btBroadphaseAabbCallback.
Definition at line 1078 of file btCollisionWorld.cpp.
References btDispatcher::findAlgorithm(), btDispatcher::freeCollisionAlgorithm(), btCollisionWorld::getDispatcher(), btCollisionWorld::getDispatchInfo(), if(), m_collisionObject, m_resultCallback, m_world, btCollisionWorld::ContactResultCallback::needsCollision(), btCollisionAlgorithm::processCollision(), and btCollisionAlgorithm::~btCollisionAlgorithm().
Member Data Documentation
btCollisionObject* btSingleContactCallback::m_collisionObject
Definition at line 1066 of file btCollisionWorld.cpp.
Referenced by process().
btCollisionWorld::ContactResultCallback& btSingleContactCallback::m_resultCallback
Definition at line 1068 of file btCollisionWorld.cpp.
Referenced by process().
btCollisionWorld* btSingleContactCallback::m_world
Definition at line 1067 of file btCollisionWorld.cpp.
Referenced by process().
The documentation for this struct was generated from the following file:
btCollisionWorld.cpp