Blender: BL_ArmatureObject Class Reference
BL_ArmatureObject Class Reference
#include <BL_ArmatureObject.h>
Public Member Functions
double GetLastFrame ()
short GetActivePriority ()
virtual void ProcessReplica ()
virtual void ReParentLogic ()
virtual void Relink (CTR_Map< CTR_HashedPtr, void * > *obj_map)
virtual bool UnlinkObject (SCA_IObject *clientobj)
class BL_ActionActuator * GetActiveAction ()
BL_ArmatureObject (void *sgReplicationInfo, SG_Callbacks callbacks, Object *armature, Scene *scene, int vert_deform_type)
virtual ~BL_ArmatureObject ()
virtual CValue * GetReplica ()
void GetMRDPose (struct bPose **pose)
void GetPose (struct bPose **pose)
void SetPose (struct bPose *pose)
struct bPose * GetOrigPose ()
void ApplyPose ()
void RestorePose ()
bool SetActiveAction (class BL_ActionActuator *act, short priority, double curtime)
struct bArmature * GetArmature ()
struct bArmature * GetArmature () const
struct Scene * GetScene () const
Object * GetArmatureObject ()
int GetVertDeformType ()
void LoadConstraints (KX_BlenderSceneConverter *converter)
size_t GetConstraintNumber () const
BL_ArmatureConstraint * GetConstraint (const char *posechannel, const char *constraint)
BL_ArmatureConstraint * GetConstraint (const char *posechannelconstraint)
BL_ArmatureConstraint * GetConstraint (int index)
void LoadChannels ()
size_t GetChannelNumber () const
BL_ArmatureChannel * GetChannel (bPoseChannel *channel)
BL_ArmatureChannel * GetChannel (const char *channel)
BL_ArmatureChannel * GetChannel (int index)
bool GetBoneMatrix (Bone *bone, MT_Matrix4x4 &matrix)
float GetBoneLength (Bone *bone) const
Returns the bone length. The end of the bone is in the local y direction.
virtual int GetGameObjectType ()
Protected Attributes
SG_DListHead
< BL_ArmatureConstraint > m_controlledConstraints
SG_DList m_poseChannels
Object * m_objArma
struct bArmature * m_armature
struct bPose * m_pose
struct bPose * m_armpose
struct bPose * m_framePose
struct Scene * m_scene
double m_lastframe
double m_timestep
class BL_ActionActuator * m_activeAct
short m_activePriority
int m_vert_deform_type
size_t m_constraintNumber
size_t m_channelNumber
float m_obmat [4][4]
double m_lastapplyframe
Detailed Description
Definition at line 52 of file BL_ArmatureObject.h.
Constructor & Destructor Documentation
BL_ArmatureObject::BL_ArmatureObject (void * sgReplicationInfo, SG_Callbacks callbacks, Object * armature, Scene * scene, int vert_deform_type)
Definition at line 216 of file BL_ArmatureObject.cpp.
References Object::data, game_copy_pose(), m_armature, m_objArma, m_obmat, m_pose, NULL, Object::obmat, and Object::pose.
Referenced by GetReplica().
BL_ArmatureObject::~BL_ArmatureObject () [virtual]
Definition at line 249 of file BL_ArmatureObject.cpp.
References game_free_pose(), m_controlledConstraints, m_framePose, m_pose, m_poseChannels, NULL, SG_DList::Remove(), and SG_DListHead< T >::Remove().
Member Function Documentation
void BL_ArmatureObject::ApplyPose ()
Definition at line 465 of file BL_ArmatureObject.cpp.
References SG_DList::iterator< T >::begin(), bPose::ctime, SG_DList::iterator< T >::end(), m_armpose, m_controlledConstraints, m_lastapplyframe, m_lastframe, m_objArma, m_obmat, m_pose, m_scene, m_timestep, Object::obmat, Object::pose, KX_GameObject::UpdateBlenderObjectMatrix(), and where_is_pose().
Referenced by BL_ShapeDeformer::ExecuteShapeDrivers(), GetBoneMatrix(), and BL_SkinDeformer::UpdateInternal().
BL_ActionActuator * BL_ArmatureObject::GetActiveAction ()
Definition at line 540 of file BL_ArmatureObject.cpp.
References m_activeAct.
short BL_ArmatureObject::GetActivePriority ()
Definition at line 578 of file BL_ArmatureObject.cpp.
References m_activePriority.
struct bArmature* BL_ArmatureObject::GetArmature () [inline, read]
Definition at line 86 of file BL_ArmatureObject.h.
References m_armature.
struct bArmature* BL_ArmatureObject::GetArmature () const [inline, read]
Definition at line 87 of file BL_ArmatureObject.h.
References m_armature.
Object* BL_ArmatureObject::GetArmatureObject () [inline]
Definition at line 90 of file BL_ArmatureObject.h.
References m_objArma.
Referenced by BL_SkinDeformer::BGEDeformVerts(), BL_Action::BL_Action(), BL_SkinDeformer::BlenderDeformVerts(), and BL_Action::Update().
float BL_ArmatureObject::GetBoneLength (Bone * bone) const
Returns the bone length. The end of the bone is in the local y direction.
Definition at line 601 of file BL_ArmatureObject.cpp.
References Bone::head, length(), and Bone::tail.
Referenced by KX_BoneParentRelation::UpdateChildCoordinates().
bool BL_ArmatureObject::GetBoneMatrix (Bone * bone, MT_Matrix4x4 & matrix)
Retrieve the pose matrix for the specified bone. Returns true on success.
Definition at line 588 of file BL_ArmatureObject.cpp.
References ApplyPose(), get_pose_channel(), m_objArma, Bone::name, NULL, Object::pose, bPoseChannel::pose_mat, RestorePose(), and MT_Matrix4x4::setValue().
Referenced by KX_BoneParentRelation::UpdateChildCoordinates().
BL_ArmatureChannel * BL_ArmatureObject::GetChannel (int index)
Definition at line 409 of file BL_ArmatureObject.cpp.
References SG_DList::iterator< T >::begin(), SG_DList::iterator< T >::end(), LoadChannels(), m_channelNumber, m_poseChannels, and NULL.
BL_ArmatureChannel * BL_ArmatureObject::GetChannel (const char * channel)
Definition at line 396 of file BL_ArmatureObject.cpp.
References SG_DList::iterator< T >::begin(), SG_DList::iterator< T >::end(), LoadChannels(), m_poseChannels, bPoseChannel::name, and NULL.
BL_ArmatureChannel * BL_ArmatureObject::GetChannel (bPoseChannel * channel)
Definition at line 383 of file BL_ArmatureObject.cpp.
References SG_DList::iterator< T >::begin(), SG_DList::iterator< T >::end(), LoadChannels(), m_poseChannels, and NULL.
size_t BL_ArmatureObject::GetChannelNumber () const [inline]
Definition at line 102 of file BL_ArmatureObject.h.
References m_channelNumber.
BL_ArmatureConstraint * BL_ArmatureObject::GetConstraint (const char * posechannel, const char * constraint)
Definition at line 337 of file BL_ArmatureObject.cpp.
References SG_DList::iterator< T >::begin(), SG_DList::iterator< T >::end(), m_controlledConstraints, BL_ArmatureConstraint::Match(), and NULL.
BL_ArmatureConstraint * BL_ArmatureObject::GetConstraint (const char * posechannelconstraint)
Definition at line 348 of file BL_ArmatureObject.cpp.
References SG_DList::iterator< T >::begin(), SG_DList::iterator< T >::end(), BL_ArmatureConstraint::GetName(), m_controlledConstraints, and NULL.
BL_ArmatureConstraint * BL_ArmatureObject::GetConstraint (int index)
Definition at line 360 of file BL_ArmatureObject.cpp.
References SG_DList::iterator< T >::begin(), SG_DList::iterator< T >::end(), m_controlledConstraints, and NULL.
size_t BL_ArmatureObject::GetConstraintNumber () const [inline]
Definition at line 96 of file BL_ArmatureObject.h.
References m_constraintNumber.
virtual int BL_ArmatureObject::GetGameObjectType () [inline, virtual]
Reimplemented from SCA_IObject.
Definition at line 114 of file BL_ArmatureObject.h.
References SCA_IObject::OBJ_ARMATURE.
double BL_ArmatureObject::GetLastFrame ()
Definition at line 583 of file BL_ArmatureObject.cpp.
References m_lastframe.
Referenced by BL_SkinDeformer::PoseUpdated(), and BL_SkinDeformer::UpdateInternal().
void BL_ArmatureObject::GetMRDPose (struct bPose ** pose)
Definition at line 567 of file BL_ArmatureObject.cpp.
References extract_pose_from_pose(), game_copy_pose(), and m_pose.
Referenced by BL_Action::Play(), and BL_Action::Update().
struct bPose* BL_ArmatureObject::GetOrigPose () [inline, read]
Definition at line 79 of file BL_ArmatureObject.h.
References m_pose.
Referenced by KX_ArmatureSensor::FindConstraint(), and BL_ArmatureConstraint::ReParent().
void BL_ArmatureObject::GetPose (struct bPose ** pose)
Definition at line 545 of file BL_ArmatureObject.cpp.
References extract_pose_from_pose(), game_copy_pose(), and m_pose.
Referenced by SetActiveAction(), and BL_Action::Update().
CValue * BL_ArmatureObject::GetReplica (void) [virtual]
Inherited from CValue -- return a new copy of this instance allocated on the heap. Ownership of the new object belongs with the caller.
Reimplemented from KX_GameObject.
Definition at line 419 of file BL_ArmatureObject.cpp.
References BL_ArmatureObject(), and ProcessReplica().
struct Scene* BL_ArmatureObject::GetScene () const [inline, read]
Definition at line 88 of file BL_ArmatureObject.h.
References m_scene.
int BL_ArmatureObject::GetVertDeformType () [inline]
Definition at line 92 of file BL_ArmatureObject.h.
References m_vert_deform_type.
Referenced by BL_SkinDeformer::UpdateInternal().
void BL_ArmatureObject::LoadChannels ()
Definition at line 368 of file BL_ArmatureObject.cpp.
References SG_DList::AddBack(), bPose::chanbase, SG_DList::Empty(), ListBase::first, m_channelNumber, m_pose, m_poseChannels, and bPoseChannel::next.
Referenced by GetChannel().
void BL_ArmatureObject::LoadConstraints (KX_BlenderSceneConverter * converter)
Definition at line 266 of file BL_ArmatureObject.cpp.
References SG_DList::AddBack(), bPose::chanbase, CONSTRAINT_DISABLE, constraint_get_typeinfo(), CONSTRAINT_TYPE_CLAMPTO, CONSTRAINT_TYPE_DAMPTRACK, CONSTRAINT_TYPE_DISTLIMIT, CONSTRAINT_TYPE_KINEMATIC, CONSTRAINT_TYPE_LOCKTRACK, CONSTRAINT_TYPE_LOCLIKE, CONSTRAINT_TYPE_MINMAX, CONSTRAINT_TYPE_ROTLIKE, CONSTRAINT_TYPE_SIZELIKE, CONSTRAINT_TYPE_STRETCHTO, CONSTRAINT_TYPE_TRACKTO, CONSTRAINT_TYPE_TRANSFORM, CONSTRAINT_TYPE_TRANSLIKE, bPoseChannel::constraints, SG_DList::Empty(), KX_BlenderSceneConverter::FindGameObject(), ListBase::first, bConstraint::flag, bConstraintTypeInfo::flush_constraint_targets, bConstraintTypeInfo::get_constraint_targets, if(), m_constraintNumber, m_controlledConstraints, m_objArma, m_pose, bPoseChannel::next, bConstraint::next, bConstraintTarget::next, NULL, SG_DListHead< T >::Remove(), bConstraintTarget::tar, and bConstraint::type.
void BL_ArmatureObject::ProcessReplica () [virtual]
Inherited from CValue -- Makes sure any internal data owned by this class is deep copied. Called internally
Reimplemented from KX_GameObject.
Definition at line 426 of file BL_ArmatureObject.cpp.
References game_copy_pose(), m_framePose, m_pose, and NULL.
Referenced by GetReplica().
void BL_ArmatureObject::Relink (CTR_Map< CTR_HashedPtr, void * > * obj_map) [virtual]
Reimplemented from KX_GameObject.
Definition at line 445 of file BL_ArmatureObject.cpp.
References SG_DList::iterator< T >::begin(), SG_DList::iterator< T >::end(), and m_controlledConstraints.
void BL_ArmatureObject::ReParentLogic () [virtual]
Reimplemented from SCA_IObject.
Definition at line 436 of file BL_ArmatureObject.cpp.
References SG_DList::iterator< T >::begin(), SG_DList::iterator< T >::end(), and m_controlledConstraints.
void BL_ArmatureObject::RestorePose ()
Definition at line 491 of file BL_ArmatureObject.cpp.
References m_armpose, m_objArma, NULL, and Object::pose.
Referenced by BL_ShapeDeformer::ExecuteShapeDrivers(), GetBoneMatrix(), and BL_SkinDeformer::UpdateInternal().
bool BL_ArmatureObject::SetActiveAction (class BL_ActionActuator * act, short priority, double curtime)
Definition at line 503 of file BL_ArmatureObject.cpp.
References GetPose(), m_activeAct, m_activePriority, m_framePose, m_lastframe, m_timestep, NULL, BL_ActionActuator::SetBlendTime(), and SetPose().
Referenced by BL_ArmatureActuator::Update(), and BL_Action::Update().
void BL_ArmatureObject::SetPose (struct bPose * pose)
Definition at line 497 of file BL_ArmatureObject.cpp.
References extract_pose_from_pose(), m_lastapplyframe, and m_pose.
Referenced by SetActiveAction(), and BL_Action::Update().
bool BL_ArmatureObject::UnlinkObject (SCA_IObject * clientobj) [virtual]
UnlinkObject(...) this object is informed that one of the object to which it holds a reference is deleted returns true if there was indeed a reference.
Reimplemented from SCA_IObject.
Definition at line 454 of file BL_ArmatureObject.cpp.
References SG_DList::iterator< T >::begin(), SG_DList::iterator< T >::end(), and m_controlledConstraints.
Member Data Documentation
class BL_ActionActuator* BL_ArmatureObject::m_activeAct [protected]
Definition at line 138 of file BL_ArmatureObject.h.
Referenced by GetActiveAction(), and SetActiveAction().
short BL_ArmatureObject::m_activePriority [protected]
Definition at line 139 of file BL_ArmatureObject.h.
Referenced by GetActivePriority(), and SetActiveAction().
struct bArmature* BL_ArmatureObject::m_armature [protected]
Definition at line 131 of file BL_ArmatureObject.h.
Referenced by BL_ArmatureObject(), and GetArmature().
struct bPose* BL_ArmatureObject::m_armpose [protected]
Definition at line 133 of file BL_ArmatureObject.h.
Referenced by ApplyPose(), and RestorePose().
size_t BL_ArmatureObject::m_channelNumber [protected]
Definition at line 142 of file BL_ArmatureObject.h.
Referenced by GetChannel(), GetChannelNumber(), and LoadChannels().
size_t BL_ArmatureObject::m_constraintNumber [protected]
Definition at line 141 of file BL_ArmatureObject.h.
Referenced by GetConstraintNumber(), and LoadConstraints().
SG_DListHead<BL_ArmatureConstraint> BL_ArmatureObject::m_controlledConstraints [protected]
Definition at line 127 of file BL_ArmatureObject.h.
Referenced by ApplyPose(), GetConstraint(), LoadConstraints(), Relink(), ReParentLogic(), UnlinkObject(), and ~BL_ArmatureObject().
struct bPose* BL_ArmatureObject::m_framePose [protected]
Definition at line 134 of file BL_ArmatureObject.h.
Referenced by ProcessReplica(), SetActiveAction(), and ~BL_ArmatureObject().
double BL_ArmatureObject::m_lastapplyframe [protected]
Definition at line 146 of file BL_ArmatureObject.h.
Referenced by ApplyPose(), and SetPose().
double BL_ArmatureObject::m_lastframe [protected]
Definition at line 136 of file BL_ArmatureObject.h.
Referenced by ApplyPose(), GetLastFrame(), and SetActiveAction().
Object* BL_ArmatureObject::m_objArma [protected]
Definition at line 130 of file BL_ArmatureObject.h.
Referenced by ApplyPose(), BL_ArmatureObject(), GetArmatureObject(), GetBoneMatrix(), LoadConstraints(), and RestorePose().
float BL_ArmatureObject::m_obmat[4][4] [protected]
Definition at line 144 of file BL_ArmatureObject.h.
Referenced by ApplyPose(), and BL_ArmatureObject().
struct bPose* BL_ArmatureObject::m_pose [protected]
Definition at line 132 of file BL_ArmatureObject.h.
Referenced by ApplyPose(), BL_ArmatureObject(), GetMRDPose(), GetOrigPose(), GetPose(), LoadChannels(), LoadConstraints(), ProcessReplica(), SetPose(), and ~BL_ArmatureObject().
SG_DList BL_ArmatureObject::m_poseChannels [protected]
Definition at line 129 of file BL_ArmatureObject.h.
Referenced by GetChannel(), LoadChannels(), and ~BL_ArmatureObject().
struct Scene* BL_ArmatureObject::m_scene [protected]
Definition at line 135 of file BL_ArmatureObject.h.
Referenced by ApplyPose(), and GetScene().
double BL_ArmatureObject::m_timestep [protected]
Definition at line 137 of file BL_ArmatureObject.h.
Referenced by ApplyPose(), and SetActiveAction().
int BL_ArmatureObject::m_vert_deform_type [protected]
Definition at line 140 of file BL_ArmatureObject.h.
Referenced by GetVertDeformType().
The documentation for this class was generated from the following files:
BL_ArmatureObject.h
BL_ArmatureObject.cpp