Blender: blf_dir.c File Reference
blf_dir.c File Reference
blenfont
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ft2build.h>
#include "MEM_guardedalloc.h"
#include "DNA_vec_types.h"
#include "BKE_utildefines.h"
#include "BLI_blenlib.h"
#include "BIF_gl.h"
#include "BLF_api.h"
#include "blf_internal_types.h"
#include "blf_internal.h"
Functions
static DirBLF * blf_dir_find (const char *path)
void BLF_dir_add (const char *path)
void BLF_dir_rem (const char *path)
char ** BLF_dir_get (int *ndir)
void BLF_dir_free (char **dirs, int count)
char * blf_dir_search (const char *file)
char * blf_dir_metrics_search (const char *filename)
Variables
static ListBase global_font_dir = { NULL, NULL }
Detailed Description
Definition in file blf_dir.c.
Function Documentation
void BLF_dir_add (const char * path)
Definition at line 69 of file blf_dir.c.
References blf_dir_find(), BLI_addhead(), BLI_strdup(), MEM_callocN(), and DirBLF::path.
static DirBLF* blf_dir_find (const char * path) [static]
Definition at line 56 of file blf_dir.c.
References BLI_path_cmp, ListBase::first, DirBLF::next, NULL, p, and DirBLF::path.
Referenced by BLF_dir_add(), and BLF_dir_rem().
void BLF_dir_free (char ** dirs, int count)
Definition at line 117 of file blf_dir.c.
References i, and MEM_freeN().
char** BLF_dir_get (int * ndir)
Definition at line 94 of file blf_dir.c.
References BLI_countlist(), BLI_strdup(), ListBase::first, i, MEM_callocN(), DirBLF::next, NULL, p, and DirBLF::path.
char* blf_dir_metrics_search (const char * filename)
Definition at line 181 of file blf_dir.c.
References BLI_exists(), BLI_strdup(), BLI_strnlen(), MEM_freeN(), and NULL.
Referenced by blf_font_new().
void BLF_dir_rem (const char * path)
Definition at line 82 of file blf_dir.c.
References blf_dir_find(), BLI_remlink(), MEM_freeN(), and DirBLF::path.
char* blf_dir_search (const char * file)
Definition at line 129 of file blf_dir.c.
References BLI_exists(), BLI_join_dirfile(), BLI_strdup(), FILE_MAX, ListBase::first, DirBLF::next, NULL, and DirBLF::path.
Referenced by BLF_load(), and BLF_load_unique().
Variable Documentation
ListBase global_font_dir = { NULL, NULL } [static]
Definition at line 54 of file blf_dir.c.