Blender: MOD_ocean.c File Reference
MOD_ocean.c File Reference
#include "MEM_guardedalloc.h"
#include "DNA_customdata_types.h"
#include "DNA_object_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_modifier_types.h"
#include "DNA_scene_types.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_global.h"
#include "BKE_modifier.h"
#include "BKE_ocean.h"
#include "BKE_utildefines.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_math_inline.h"
#include "BLI_utildefines.h"
#include "BLI_string.h"
#include "MOD_util.h"
Functions
static void initData (ModifierData *md)
static void freeData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static CustomDataMask requiredDataMask (Object *UNUSED(ob), ModifierData *md)
static DerivedMesh * doOcean (ModifierData *md, Object *UNUSED(ob), DerivedMesh *derivedData, int UNUSED(useRenderParams))
static DerivedMesh * applyModifier (ModifierData *md, Object *ob, DerivedMesh *derivedData, int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
static DerivedMesh * applyModifierEM (ModifierData *md, Object *ob, struct BMEditMesh *UNUSED(editData), DerivedMesh *derivedData)
Variables
ModifierTypeInfo modifierType_Ocean
Function Documentation
static DerivedMesh* applyModifier (ModifierData * md, Object * ob, DerivedMesh * derivedData, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 535 of file MOD_ocean.c.
References CDDM_calc_normals(), and doOcean().
Referenced by applyModifierEM().
static DerivedMesh* applyModifierEM (ModifierData * md, Object * ob, struct BMEditMesh * UNUSEDeditData, DerivedMesh * derivedData) [static]
Definition at line 550 of file MOD_ocean.c.
References applyModifier().
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 162 of file MOD_ocean.c.
References OceanModifierData::bakeend, OceanModifierData::bakestart, BKE_add_ocean(), OceanModifierData::cached, OceanModifierData::chop_amount, OceanModifierData::damp, OceanModifierData::depth, OceanModifierData::flag, OceanModifierData::foam_coverage, NULL, OceanModifierData::ocean, OceanModifierData::oceancache, OceanModifierData::refresh, OceanModifierData::repeat_x, OceanModifierData::repeat_y, OceanModifierData::resolution, OceanModifierData::seed, OceanModifierData::size, OceanModifierData::smallest_wave, OceanModifierData::spatial_size, OceanModifierData::time, OceanModifierData::wave_alignment, OceanModifierData::wave_direction, OceanModifierData::wave_scale, and OceanModifierData::wind_velocity.
static DerivedMesh* doOcean (ModifierData * md, Object * UNUSEDob, DerivedMesh * derivedData, int UNUSEDuseRenderParams) [static]
Definition at line 525 of file MOD_ocean.c.
Referenced by applyModifier().
static void freeData (ModifierData * md) [static]
Definition at line 148 of file MOD_ocean.c.
References BKE_free_ocean(), BKE_free_ocean_cache(), OceanModifierData::ocean, and OceanModifierData::oceancache.
static void initData (ModifierData * md) [static]
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) Blender Foundation All rights reserved.
The Original Code is: all of this file.
Contributor(s): Matt Ebb
***** END GPL LICENSE BLOCK *****
Definition at line 99 of file MOD_ocean.c.
References OceanModifierData::bakeend, OceanModifierData::bakestart, BKE_add_ocean(), OceanModifierData::cached, OceanModifierData::cachepath, OceanModifierData::chop_amount, OceanModifierData::damp, OceanModifierData::depth, OceanModifierData::foam_coverage, OceanModifierData::foam_fade, OceanModifierData::foamlayername, modifier_path_init(), NULL, OceanModifierData::ocean, OceanModifierData::oceancache, OceanModifierData::refresh, OceanModifierData::repeat_x, OceanModifierData::repeat_y, OceanModifierData::resolution, OceanModifierData::seed, OceanModifierData::size, OceanModifierData::smallest_wave, OceanModifierData::spatial_size, OceanModifierData::time, OceanModifierData::wave_alignment, OceanModifierData::wave_direction, OceanModifierData::wave_scale, and OceanModifierData::wind_velocity.
static CustomDataMask requiredDataMask (Object * UNUSEDob, ModifierData * md) [static]
Definition at line 223 of file MOD_ocean.c.
Variable Documentation
ModifierTypeInfo modifierType_Ocean
Initial value:
 {
                  "Ocean",
            "OceanModifierData",
            sizeof(OceanModifierData),
                  eModifierTypeType_Constructive,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_SupportsEditmode
                            | eModifierTypeFlag_EnableInEditmode,
              copyData,
        NULL,
           NULL,
         NULL,
      NULL,
         applyModifier,
       applyModifierEM,
              initData,
      requiredDataMask,
              freeData,
            NULL,
        NULL,
         NULL,
        NULL,
     NULL,
         NULL,
}
Definition at line 559 of file MOD_ocean.c.