Blender: node_shader_rgb.c File Reference
node_shader_rgb.c File Reference
shdnodes
#include "node_shader_util.h"
Functions
static void node_shader_init_rgb (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static void node_shader_exec_rgb (void *UNUSED(data), bNode *node, bNodeStack **UNUSED(in), bNodeStack **out)
static int gpu_shader_rgb (GPUMaterial *mat, bNode *node, GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_rgb (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_rgb_out []
Detailed Description
Definition in file node_shader_rgb.c.
Function Documentation
static int gpu_shader_rgb (GPUMaterial * mat, bNode * node, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 60 of file node_shader_rgb.c.
References bNodeSocket::default_value, ListBase::first, GPU_stack_link(), GPU_uniform(), and bNode::outputs.
Referenced by register_node_type_sh_rgb().
static void node_shader_exec_rgb (void * UNUSEDdata, bNode * node, bNodeStack ** UNUSEDin, bNodeStack ** out) [static]
Definition at line 52 of file node_shader_rgb.c.
References copy_v3_v3(), bNodeSocket::default_value, ListBase::first, and bNode::outputs.
Referenced by register_node_type_sh_rgb().
static void node_shader_init_rgb (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 41 of file node_shader_rgb.c.
References bNodeSocket::default_value, ListBase::first, bNode::outputs, and bNodeSocketValueRGBA::value.
Referenced by register_node_type_sh_rgb().
void register_node_type_sh_rgb (bNodeTreeType * ttype)
Definition at line 69 of file node_shader_rgb.c.
References gpu_shader_rgb(), NODE_CLASS_INPUT, NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_rgb(), node_shader_init_rgb(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), NULL, and SH_NODE_RGB.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_rgb_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Color"},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_shader_rgb.c.