Blender: rna_group.c File Reference
rna_group.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_group_types.h"
Functions
static void rna_def_group_objects (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_group (BlenderRNA *brna)
Detailed Description
Definition in file rna_group.c.
Function Documentation
void RNA_def_group (BlenderRNA * brna)
Definition at line 108 of file rna_group.c.
References NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_FLOAT, PROP_LAYER, PROP_NONE, PROP_TRANSLATION, rna_def_group_objects(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_float_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), RNA_TRANSLATION_PREC_DEFAULT, PropertyRNA::srna, and STRUCT_ID_REFCOUNT.
static void rna_def_group_objects (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 77 of file rna_group.c.
References FUNC_USE_CONTEXT, FUNC_USE_REPORTS, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_group().