Blender: btConvexSeparatingDistanceUtil Class Reference
btConvexSeparatingDistanceUtil Class Reference
#include <btTransformUtil.h>
Public Member Functions
btConvexSeparatingDistanceUtil (btScalar boundingRadiusA, btScalar boundingRadiusB)
btScalar getConservativeSeparatingDistance ()
void updateSeparatingDistance (const btTransform &transA, const btTransform &transB)
void initSeparatingDistance (const btVector3 &separatingVector, btScalar separatingDistance, const btTransform &transA, const btTransform &transB)
Detailed Description
The btConvexSeparatingDistanceUtil can help speed up convex collision detection by conservatively updating a cached separating distance/vector instead of re-calculating the closest distance
Definition at line 146 of file btTransformUtil.h.
Constructor & Destructor Documentation
btConvexSeparatingDistanceUtil::btConvexSeparatingDistanceUtil (btScalar boundingRadiusA, btScalar boundingRadiusB) [inline]
Definition at line 161 of file btTransformUtil.h.
Member Function Documentation
btScalar btConvexSeparatingDistanceUtil::getConservativeSeparatingDistance () [inline]
Definition at line 168 of file btTransformUtil.h.
void btConvexSeparatingDistanceUtil::initSeparatingDistance (const btVector3 & separatingVector, btScalar separatingDistance, const btTransform & transA, const btTransform & transB) [inline]
Definition at line 205 of file btTransformUtil.h.
References btTransform::getOrigin(), and btTransform::getRotation().
void btConvexSeparatingDistanceUtil::updateSeparatingDistance (const btTransform & transA, const btTransform & transB) [inline]
Definition at line 173 of file btTransformUtil.h.
References btTransformUtil::calculateVelocityQuaternion(), btTransform::getOrigin(), and btTransform::getRotation().
The documentation for this class was generated from the following file:
btTransformUtil.h