Blender: SCA_ExpressionController Class Reference
SCA_ExpressionController Class Reference
#include <SCA_ExpressionController.h>
Public Member Functions
SCA_ExpressionController (SCA_IObject *gameobj, const STR_String &exprtext)
virtual ~SCA_ExpressionController ()
virtual CValue * GetReplica ()
virtual void Trigger (SCA_LogicManager *logicmgr)
virtual CValue * FindIdentifier (const STR_String &identifiername)
virtual void Delete ()
Detailed Description
Definition at line 40 of file SCA_ExpressionController.h.
Constructor & Destructor Documentation
SCA_ExpressionController::SCA_ExpressionController (SCA_IObject * gameobj, const STR_String & exprtext)
Definition at line 50 of file SCA_ExpressionController.cpp.
Referenced by GetReplica().
SCA_ExpressionController::~SCA_ExpressionController () [virtual]
Definition at line 60 of file SCA_ExpressionController.cpp.
References CExpression::Release().
Member Function Documentation
void SCA_ExpressionController::Delete () [virtual]
used to release the expression cache so that self references are removed before the controller itself is released
Reimplemented from SCA_ILogicBrick.
Definition at line 82 of file SCA_ExpressionController.cpp.
References NULL, CExpression::Release(), and CValue::Release().
CValue * SCA_ExpressionController::FindIdentifier (const STR_String & identifiername) [virtual]
Reimplemented from CValue.
Definition at line 131 of file SCA_ExpressionController.cpp.
References CValue::FindIdentifier(), SCA_ILogicBrick::GetName(), SCA_ILogicBrick::GetParent(), SCA_ISensor::GetState(), SCA_IController::m_linkedsensors, and NULL.
CValue * SCA_ExpressionController::GetReplica (void) [virtual]
Implements CValue.
Definition at line 68 of file SCA_ExpressionController.cpp.
References NULL, CValue::ProcessReplica(), and SCA_ExpressionController().
void SCA_ExpressionController::Trigger (SCA_LogicManager * logicmgr) [virtual]
Implements SCA_IController.
Definition at line 93 of file SCA_ExpressionController.cpp.
References SCA_LogicManager::AddActiveActuator(), CValue::AddRef(), CExpression::Calculate(), CValue::GetNumber(), CValue::GetText(), i, CValue::IsError(), SCA_IController::m_linkedactuators, MT_fuzzyZero(), CParser::ProcessText(), STR_String::ReadPtr(), CValue::Release(), and CParser::SetContext().
The documentation for this class was generated from the following files:
SCA_ExpressionController.h
SCA_ExpressionController.cpp