Blender: time.c File Reference
time.c File Reference
blenlib
#include "PIL_time.h"
#include <unistd.h>
#include <sys/time.h>
Functions
double PIL_check_seconds_timer (void)
void PIL_sleep_ms (int ms)
Detailed Description
Definition in file time.c.
Function Documentation
double PIL_check_seconds_timer (void)
Return an indication of time, expressed as seconds since some fixed point. Successive calls are guaranteed to generate values greater than or equal to the last call.
Definition at line 83 of file time.c.
Referenced by applySnapping(), BIF_retargetArmature(), BLI_fillrand(), BLI_thread_queue_pop_timeout(), bpy_context_clear(), bpy_context_set(), BPY_python_end(), button_activate_init(), do_render_all_options(), do_versions(), draw_image_buffer_repeated(), dynamicPaint_initBake(), flyApply(), flyEvent(), free_old_images(), KX_BlenderSystem::GetTimeInSeconds(), init_render_object(), initFlyInfo(), KX_BlenderSystem::KX_BlenderSystem(), minimize_stretch_init(), minimize_stretch_iteration(), minimize_stretch_modal(), multiple_scattering_diffusion(), object_add_collision_fields(), paint_apply_event(), panel_activate_state(), ptcache_bake_thread(), RE_InitState(), redraw_timer_exec(), softbody_step(), tag_image_time(), text_line_number_invoke(), track_markers_startjob(), ui_blockopen_end(), ui_do_animate(), ui_mouse_motion_towards_check(), ui_mouse_motion_towards_init(), view_zoomdrag_apply(), view_zoomdrag_invoke(), view_zoomdrag_modal(), viewzoom_apply(), viewzoom_invoke(), vol_precache_objectinstance_threads(), WM_event_add_timer(), wm_event_do_handlers(), wm_handlers_do(), wm_window_testbreak(), and wm_window_timer().
void PIL_sleep_ms (int ms)
Platform-independent sleep function.
Parameters:
ms Number of milliseconds to sleep
Definition at line 93 of file time.c.
Referenced by bake_image_exec(), BKE_ptcache_bake(), BLI_insert_work(), ntreeCompositExecTree(), RE_bake_shade_all_selected(), screenshot_startjob(), threaded_makeshadowbufs(), threaded_tile_processor(), thumbnails_startjob(), track_markers_startjob(), and wm_window_process_events().