Blender: object_intern.h File Reference
object_intern.h File Reference
object
Enumerations
enum { OBJECT_ADDHOOK_NEWOB = 1, OBJECT_ADDHOOK_SELOB }
Functions
void OBJECT_OT_location_clear (struct wmOperatorType *ot)
void OBJECT_OT_rotation_clear (struct wmOperatorType *ot)
void OBJECT_OT_scale_clear (struct wmOperatorType *ot)
void OBJECT_OT_origin_clear (struct wmOperatorType *ot)
void OBJECT_OT_visual_transform_apply (struct wmOperatorType *ot)
void OBJECT_OT_transform_apply (struct wmOperatorType *ot)
void OBJECT_OT_origin_set (struct wmOperatorType *ot)
void OBJECT_OT_parent_set (struct wmOperatorType *ot)
void OBJECT_OT_parent_no_inverse_set (struct wmOperatorType *ot)
void OBJECT_OT_parent_clear (struct wmOperatorType *ot)
void OBJECT_OT_vertex_parent_set (struct wmOperatorType *ot)
void OBJECT_OT_track_set (struct wmOperatorType *ot)
void OBJECT_OT_track_clear (struct wmOperatorType *ot)
void OBJECT_OT_slow_parent_set (struct wmOperatorType *ot)
void OBJECT_OT_slow_parent_clear (struct wmOperatorType *ot)
void OBJECT_OT_make_local (struct wmOperatorType *ot)
void OBJECT_OT_make_single_user (struct wmOperatorType *ot)
void OBJECT_OT_make_links_scene (struct wmOperatorType *ot)
void OBJECT_OT_make_links_data (struct wmOperatorType *ot)
void OBJECT_OT_move_to_layer (struct wmOperatorType *ot)
void OBJECT_OT_drop_named_material (struct wmOperatorType *ot)
void OBJECT_OT_mode_set (struct wmOperatorType *ot)
void OBJECT_OT_editmode_toggle (struct wmOperatorType *ot)
void OBJECT_OT_posemode_toggle (struct wmOperatorType *ot)
void OBJECT_OT_hide_view_set (struct wmOperatorType *ot)
void OBJECT_OT_hide_view_clear (struct wmOperatorType *ot)
void OBJECT_OT_hide_render_set (struct wmOperatorType *ot)
void OBJECT_OT_hide_render_clear (struct wmOperatorType *ot)
void OBJECT_OT_proxy_make (struct wmOperatorType *ot)
void OBJECT_OT_shade_smooth (struct wmOperatorType *ot)
void OBJECT_OT_shade_flat (struct wmOperatorType *ot)
void OBJECT_OT_paths_calculate (struct wmOperatorType *ot)
void OBJECT_OT_paths_clear (struct wmOperatorType *ot)
void OBJECT_OT_forcefield_toggle (struct wmOperatorType *ot)
void OBJECT_OT_game_property_new (struct wmOperatorType *ot)
void OBJECT_OT_game_property_remove (struct wmOperatorType *ot)
void OBJECT_OT_game_property_copy (struct wmOperatorType *ot)
void OBJECT_OT_game_property_clear (struct wmOperatorType *ot)
void OBJECT_OT_logic_bricks_copy (struct wmOperatorType *ot)
void OBJECT_OT_game_physics_copy (struct wmOperatorType *ot)
void OBJECT_OT_select_all (struct wmOperatorType *ot)
void OBJECT_OT_select_random (struct wmOperatorType *ot)
void OBJECT_OT_select_by_type (struct wmOperatorType *ot)
void OBJECT_OT_select_by_layer (struct wmOperatorType *ot)
void OBJECT_OT_select_linked (struct wmOperatorType *ot)
void OBJECT_OT_select_grouped (struct wmOperatorType *ot)
void OBJECT_OT_select_mirror (struct wmOperatorType *ot)
void OBJECT_OT_select_same_group (struct wmOperatorType *ot)
void OBJECT_OT_add (struct wmOperatorType *ot)
void OBJECT_OT_add_named (struct wmOperatorType *ot)
void OBJECT_OT_metaball_add (struct wmOperatorType *ot)
void OBJECT_OT_text_add (struct wmOperatorType *ot)
void OBJECT_OT_armature_add (struct wmOperatorType *ot)
void OBJECT_OT_lamp_add (struct wmOperatorType *ot)
void OBJECT_OT_effector_add (struct wmOperatorType *ot)
void OBJECT_OT_camera_add (struct wmOperatorType *ot)
void OBJECT_OT_speaker_add (struct wmOperatorType *ot)
void OBJECT_OT_group_instance_add (struct wmOperatorType *ot)
void OBJECT_OT_duplicates_make_real (struct wmOperatorType *ot)
void OBJECT_OT_duplicate (struct wmOperatorType *ot)
void OBJECT_OT_delete (struct wmOperatorType *ot)
void OBJECT_OT_join (struct wmOperatorType *ot)
void OBJECT_OT_join_shapes (struct wmOperatorType *ot)
void OBJECT_OT_convert (struct wmOperatorType *ot)
void OBJECT_OT_hook_add_selobj (struct wmOperatorType *ot)
void OBJECT_OT_hook_add_newobj (struct wmOperatorType *ot)
void OBJECT_OT_hook_remove (struct wmOperatorType *ot)
void OBJECT_OT_hook_select (struct wmOperatorType *ot)
void OBJECT_OT_hook_assign (struct wmOperatorType *ot)
void OBJECT_OT_hook_reset (struct wmOperatorType *ot)
void OBJECT_OT_hook_recenter (struct wmOperatorType *ot)
void LATTICE_OT_select_all (struct wmOperatorType *ot)
void LATTICE_OT_make_regular (struct wmOperatorType *ot)
void GROUP_OT_create (struct wmOperatorType *ot)
void GROUP_OT_objects_remove (struct wmOperatorType *ot)
void GROUP_OT_objects_add_active (struct wmOperatorType *ot)
void GROUP_OT_objects_remove_active (struct wmOperatorType *ot)
void OBJECT_OT_modifier_add (struct wmOperatorType *ot)
void OBJECT_OT_modifier_remove (struct wmOperatorType *ot)
void OBJECT_OT_modifier_move_up (struct wmOperatorType *ot)
void OBJECT_OT_modifier_move_down (struct wmOperatorType *ot)
void OBJECT_OT_modifier_apply (struct wmOperatorType *ot)
void OBJECT_OT_modifier_convert (struct wmOperatorType *ot)
void OBJECT_OT_modifier_copy (struct wmOperatorType *ot)
void OBJECT_OT_multires_subdivide (struct wmOperatorType *ot)
void OBJECT_OT_multires_reshape (struct wmOperatorType *ot)
void OBJECT_OT_multires_higher_levels_delete (struct wmOperatorType *ot)
void OBJECT_OT_multires_base_apply (struct wmOperatorType *ot)
void OBJECT_OT_multires_external_save (struct wmOperatorType *ot)
void OBJECT_OT_multires_external_pack (struct wmOperatorType *ot)
void OBJECT_OT_meshdeform_bind (struct wmOperatorType *ot)
void OBJECT_OT_explode_refresh (struct wmOperatorType *ot)
void OBJECT_OT_ocean_bake (struct wmOperatorType *ot)
void OBJECT_OT_constraint_add (struct wmOperatorType *ot)
void OBJECT_OT_constraint_add_with_targets (struct wmOperatorType *ot)
void POSE_OT_constraint_add (struct wmOperatorType *ot)
void POSE_OT_constraint_add_with_targets (struct wmOperatorType *ot)
void OBJECT_OT_constraints_copy (struct wmOperatorType *ot)
void POSE_OT_constraints_copy (struct wmOperatorType *ot)
void OBJECT_OT_constraints_clear (struct wmOperatorType *ot)
void POSE_OT_constraints_clear (struct wmOperatorType *ot)
void POSE_OT_ik_add (struct wmOperatorType *ot)
void POSE_OT_ik_clear (struct wmOperatorType *ot)
void CONSTRAINT_OT_delete (struct wmOperatorType *ot)
void CONSTRAINT_OT_move_up (struct wmOperatorType *ot)
void CONSTRAINT_OT_move_down (struct wmOperatorType *ot)
void CONSTRAINT_OT_stretchto_reset (struct wmOperatorType *ot)
void CONSTRAINT_OT_limitdistance_reset (struct wmOperatorType *ot)
void CONSTRAINT_OT_childof_set_inverse (struct wmOperatorType *ot)
void CONSTRAINT_OT_childof_clear_inverse (struct wmOperatorType *ot)
void CONSTRAINT_OT_objectsolver_set_inverse (struct wmOperatorType *ot)
void CONSTRAINT_OT_objectsolver_clear_inverse (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_add (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_remove (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_assign (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_remove_from (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_select (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_deselect (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_copy_to_linked (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_copy_to_selected (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_copy (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_normalize (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_normalize_all (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_levels (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_lock (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_fix (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_invert (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_blend (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_clean (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_mirror (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_set_active (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_sort (struct wmOperatorType *ot)
void OBJECT_OT_vertex_group_move (struct wmOperatorType *ot)
void OBJECT_OT_shape_key_add (struct wmOperatorType *ot)
void OBJECT_OT_shape_key_remove (struct wmOperatorType *ot)
void OBJECT_OT_shape_key_clear (struct wmOperatorType *ot)
void OBJECT_OT_shape_key_retime (struct wmOperatorType *ot)
void OBJECT_OT_shape_key_mirror (struct wmOperatorType *ot)
void OBJECT_OT_shape_key_move (struct wmOperatorType *ot)
void OBJECT_OT_group_add (struct wmOperatorType *ot)
void OBJECT_OT_group_link (struct wmOperatorType *ot)
void OBJECT_OT_group_remove (struct wmOperatorType *ot)
void OBJECT_OT_bake_image (wmOperatorType *ot)
Variables
enum { ... } eObject_Hook_Add_Mode
Detailed Description
Definition in file object_intern.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
OBJECT_ADDHOOK_NEWOB
OBJECT_ADDHOOK_SELOB
Definition at line 43 of file object_intern.h.
Function Documentation
void CONSTRAINT_OT_childof_clear_inverse (struct wmOperatorType * ot)
Definition at line 857 of file object_constraint.c.
References childof_clear_inverse_exec(), childof_clear_inverse_invoke(), wmOperatorType::description, edit_constraint_poll(), edit_constraint_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void CONSTRAINT_OT_childof_set_inverse (struct wmOperatorType * ot)
Definition at line 813 of file object_constraint.c.
References childof_set_inverse_exec(), childof_set_inverse_invoke(), wmOperatorType::description, edit_constraint_poll(), edit_constraint_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void CONSTRAINT_OT_delete (struct wmOperatorType * ot)
Definition at line 1033 of file object_constraint.c.
References constraint_delete_exec(), constraint_poll(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void CONSTRAINT_OT_limitdistance_reset (struct wmOperatorType * ot)
Definition at line 687 of file object_constraint.c.
References wmOperatorType::description, edit_constraint_poll(), edit_constraint_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, limitdistance_reset_exec(), limitdistance_reset_invoke(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void CONSTRAINT_OT_move_down (struct wmOperatorType * ot)
Definition at line 1078 of file object_constraint.c.
References constraint_move_down_exec(), constraint_move_down_invoke(), wmOperatorType::description, edit_constraint_poll(), edit_constraint_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void CONSTRAINT_OT_move_up (struct wmOperatorType * ot)
Definition at line 1125 of file object_constraint.c.
References constraint_move_up_exec(), constraint_move_up_invoke(), wmOperatorType::description, edit_constraint_poll(), edit_constraint_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void CONSTRAINT_OT_objectsolver_clear_inverse (struct wmOperatorType * ot)
Definition at line 947 of file object_constraint.c.
References wmOperatorType::description, edit_constraint_poll(), edit_constraint_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, objectsolver_clear_inverse_exec(), objectsolver_clear_inverse_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void CONSTRAINT_OT_objectsolver_set_inverse (struct wmOperatorType * ot)
Definition at line 904 of file object_constraint.c.
References wmOperatorType::description, edit_constraint_poll(), edit_constraint_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, objectsolver_set_inverse_exec(), objectsolver_set_inverse_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void CONSTRAINT_OT_stretchto_reset (struct wmOperatorType * ot)
Definition at line 644 of file object_constraint.c.
References wmOperatorType::description, edit_constraint_poll(), edit_constraint_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, stretchto_reset_exec(), and stretchto_reset_invoke().
Referenced by ED_operatortypes_object().
void GROUP_OT_create (struct wmOperatorType * ot)
Definition at line 217 of file object_group.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, group_create_exec(), wmOperatorType::idname, MAX_ID_NAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void GROUP_OT_objects_add_active (struct wmOperatorType * ot)
Definition at line 99 of file object_group.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, objects_add_active_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void GROUP_OT_objects_remove (struct wmOperatorType * ot)
Definition at line 180 of file object_group.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, group_objects_remove_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void GROUP_OT_objects_remove_active (struct wmOperatorType * ot)
Definition at line 146 of file object_group.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, objects_remove_active_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void LATTICE_OT_make_regular (struct wmOperatorType * ot)
Definition at line 288 of file object_lattice.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, make_regular_exec(), make_regular_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void LATTICE_OT_select_all (struct wmOperatorType * ot)
Definition at line 240 of file object_lattice.c.
References wmOperatorType::description, ED_operator_editlattice(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, lattice_select_all_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_properties_select_all().
Referenced by ED_operatortypes_object().
void OBJECT_OT_add (struct wmOperatorType * ot)
Definition at line 365 of file object_add.c.
References wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_add_exec(), object_type_items, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_object().
void OBJECT_OT_add_named (struct wmOperatorType * ot)
Definition at line 1986 of file object_add.c.
References add_named_exec(), wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAX_ID_NAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_armature_add (struct wmOperatorType * ot)
Definition at line 685 of file object_add.c.
References wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_armature_add_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_object().
void OBJECT_OT_bake_image (wmOperatorType * ot)
Definition at line 1556 of file object_bake.c.
References bake_image_exec(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, objects_bake_render_invoke(), and objects_bake_render_modal().
Referenced by ED_operatortypes_object().
void OBJECT_OT_camera_add (struct wmOperatorType * ot)
Definition at line 510 of file object_add.c.
References wmOperatorType::description, ED_object_add_generic_props(), ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_camera_add_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_HIDDEN, RNA_def_property_flag(), RNA_struct_type_find_property(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_object().
void OBJECT_OT_constraint_add (struct wmOperatorType * ot)
Definition at line 1609 of file object_constraint.c.
References constraint_type_items, wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_constraint_add_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_constraint_add_with_targets (struct wmOperatorType * ot)
Definition at line 1628 of file object_constraint.c.
References constraint_type_items, wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_constraint_add_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_constraints_clear (struct wmOperatorType * ot)
Definition at line 1207 of file object_constraint.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, object_constraints_clear_exec(), and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_constraints_copy (struct wmOperatorType * ot)
Definition at line 1294 of file object_constraint.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_constraint_copy_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_convert (struct wmOperatorType * ot)
Definition at line 1585 of file object_add.c.
References convert_exec(), convert_poll(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OB_MESH, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_delete (struct wmOperatorType * ot)
Definition at line 946 of file object_add.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_delete_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, and WM_operator_confirm().
Referenced by ED_operatortypes_object().
void OBJECT_OT_drop_named_material (struct wmOperatorType * ot)
Definition at line 1912 of file object_relations.c.
References wmOperatorType::description, drop_named_material_invoke(), ED_operator_objectmode(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_duplicate (struct wmOperatorType * ot)
Definition at line 1913 of file object_add.c.
References wmOperatorType::description, duplicate_exec(), ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_HIDDEN, RNA_def_boolean(), RNA_def_enum(), RNA_def_property_flag(), wmOperatorType::srna, TFM_TRANSLATION, and transform_mode_types.
Referenced by ED_operatortypes_object().
void OBJECT_OT_duplicates_make_real (struct wmOperatorType * ot)
Definition at line 1208 of file object_add.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_duplicates_make_real_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_editmode_toggle (struct wmOperatorType * ot)
Definition at line 556 of file object_edit.c.
References wmOperatorType::description, editmode_toggle_exec(), editmode_toggle_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_effector_add (struct wmOperatorType * ot)
Definition at line 457 of file object_add.c.
References wmOperatorType::description, ED_object_add_generic_props(), ED_operator_objectmode(), effector_add_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, TRUE, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_explode_refresh (struct wmOperatorType * ot)
Definition at line 1443 of file object_modifier.c.
References wmOperatorType::description, edit_modifier_properties(), wmOperatorType::exec, explode_poll(), explode_refresh_exec(), explode_refresh_invoke(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_forcefield_toggle (struct wmOperatorType * ot)
Definition at line 1082 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, forcefield_toggle_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_game_physics_copy (struct wmOperatorType * ot)
Definition at line 1793 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, game_physics_copy_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_game_property_clear (struct wmOperatorType * ot)
Definition at line 1688 of file object_edit.c.
References ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, game_property_clear_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_game_property_copy (struct wmOperatorType * ot)
Definition at line 1658 of file object_edit.c.
References ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, game_property_copy_exec(), gameprops_itemf(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, Object::prop, RNA_def_enum(), RNA_def_enum_funcs(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_game_property_new (struct wmOperatorType * ot)
Definition at line 1527 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, game_property_new(), gameproperty_type_items, GPROP_FLOAT, wmOperatorType::idname, MAX_NAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_game_property_remove (struct wmOperatorType * ot)
Definition at line 1568 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, game_property_remove(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_group_add (struct wmOperatorType * ot)
Definition at line 253 of file object_group.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, group_add_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by ED_operatortypes_object().
void OBJECT_OT_group_instance_add (struct wmOperatorType * ot)
Definition at line 861 of file object_add.c.
References wmOperatorType::description, DummyRNA_NULL_items, ED_object_add_generic_props(), ED_operator_objectmode(), wmOperatorType::exec, FALSE, wmOperatorType::flag, group_instance_add_exec(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), RNA_group_itemf(), wmOperatorType::srna, and WM_enum_search_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_group_link (struct wmOperatorType * ot)
Definition at line 283 of file object_group.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, group_link_exec(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::prop, Object::prop, RNA_def_enum(), RNA_def_enum_funcs(), RNA_group_local_itemf(), wmOperatorType::srna, and WM_enum_search_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_group_remove (struct wmOperatorType * ot)
Definition at line 321 of file object_group.c.
References wmOperatorType::exec, wmOperatorType::flag, group_remove_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by ED_operatortypes_object().
void OBJECT_OT_hide_render_clear (struct wmOperatorType * ot)
Definition at line 253 of file object_edit.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_hide_render_clear_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_hide_render_set (struct wmOperatorType * ot)
Definition at line 290 of file object_edit.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_hide_render_set_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_hide_view_clear (struct wmOperatorType * ot)
Definition at line 160 of file object_edit.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_hide_view_clear_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_hide_view_set (struct wmOperatorType * ot)
Definition at line 215 of file object_edit.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_hide_view_set_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_hook_add_newobj (struct wmOperatorType * ot)
Definition at line 534 of file object_hook.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, hook_op_edit_poll(), wmOperatorType::idname, wmOperatorType::name, object_add_hook_newob_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_hook_add_selobj (struct wmOperatorType * ot)
Definition at line 506 of file object_hook.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, hook_op_edit_poll(), wmOperatorType::idname, wmOperatorType::name, object_add_hook_selob_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_hook_assign (struct wmOperatorType * ot)
Definition at line 791 of file object_hook.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, hook_mod_itemf(), hook_op_edit_poll(), wmOperatorType::idname, wmOperatorType::name, object_hook_assign_exec(), OPTYPE_UNDO, wmOperatorType::poll, Object::prop, RNA_def_enum(), RNA_def_enum_funcs(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_hook_recenter (struct wmOperatorType * ot)
Definition at line 727 of file object_hook.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, hook_mod_itemf(), hook_op_edit_poll(), wmOperatorType::idname, wmOperatorType::name, object_hook_recenter_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, Object::prop, RNA_def_enum(), RNA_def_enum_funcs(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_hook_remove (struct wmOperatorType * ot)
Definition at line 601 of file object_hook.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, hook_mod_itemf(), hook_op_edit_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_hook_remove_exec(), OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, Object::prop, RNA_def_enum(), RNA_def_enum_funcs(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_hook_reset (struct wmOperatorType * ot)
Definition at line 671 of file object_hook.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, hook_mod_itemf(), hook_op_edit_poll(), wmOperatorType::idname, wmOperatorType::name, object_hook_reset_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, Object::prop, RNA_def_enum(), RNA_def_enum_funcs(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_hook_select (struct wmOperatorType * ot)
Definition at line 842 of file object_hook.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, hook_mod_itemf(), hook_op_edit_poll(), wmOperatorType::idname, wmOperatorType::name, object_hook_select_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, Object::prop, RNA_def_enum(), RNA_def_enum_funcs(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_join (struct wmOperatorType * ot)
Definition at line 2044 of file object_add.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, join_exec(), join_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_join_shapes (struct wmOperatorType * ot)
Definition at line 2093 of file object_add.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, join_shapes_exec(), join_shapes_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_lamp_add (struct wmOperatorType * ot)
Definition at line 744 of file object_add.c.
References wmOperatorType::description, ED_object_add_generic_props(), ED_operator_objectmode(), wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, LA_AREA, LA_HEMI, LA_LOCAL, LA_SPOT, LA_SUN, lamp_type_items, wmOperatorType::name, NULL, object_lamp_add_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_location_clear (struct wmOperatorType * ot)
Definition at line 260 of file object_transform.c.
References wmOperatorType::description, ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_location_clear_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_logic_bricks_copy (struct wmOperatorType * ot)
Definition at line 1745 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, logicbricks_copy_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_make_links_data (struct wmOperatorType * ot)
Definition at line 1344 of file object_relations.c.
References wmOperatorType::description, ED_operator_object_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAKE_LINKS_ANIMDATA, make_links_data_exec(), MAKE_LINKS_DUPLIGROUP, MAKE_LINKS_MATERIALS, MAKE_LINKS_MODIFIERS, MAKE_LINKS_OBDATA, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_make_links_scene (struct wmOperatorType * ot)
Definition at line 1321 of file object_relations.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, make_links_scene_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), RNA_scene_local_itemf(), wmOperatorType::srna, and WM_enum_search_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_make_local (struct wmOperatorType * ot)
Definition at line 1806 of file object_relations.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, make_local_exec(), wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_make_single_user (struct wmOperatorType * ot)
Definition at line 1860 of file object_relations.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, make_single_user_exec(), wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), SELECT, wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_meshdeform_bind (struct wmOperatorType * ot)
Definition at line 1394 of file object_modifier.c.
References wmOperatorType::description, edit_modifier_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, meshdeform_bind_exec(), meshdeform_bind_invoke(), meshdeform_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_metaball_add (struct wmOperatorType * ot)
Definition at line 590 of file object_add.c.
References wmOperatorType::description, ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, metaelem_type_items, wmOperatorType::name, object_metaball_add_exec(), object_metaball_add_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_object().
void OBJECT_OT_mode_set (struct wmOperatorType * ot)
Definition at line 1460 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OB_MODE_OBJECT, object_mode_items, object_mode_set_exec(), object_mode_set_itemsf(), wmOperatorType::poll, Object::prop, RNA_def_boolean(), RNA_def_enum(), RNA_def_enum_funcs(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_modifier_add (struct wmOperatorType * ot)
Definition at line 688 of file object_modifier.c.
References wmOperatorType::description, ED_operator_object_active_editable(), eModifierType_Subsurf, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, modifier_add_exec(), modifier_add_itemf(), modifier_type_items, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_modifier_apply (struct wmOperatorType * ot)
Definition at line 923 of file object_modifier.c.
References wmOperatorType::description, edit_modifier_poll(), edit_modifier_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MODIFIER_APPLY_DATA, modifier_apply_exec(), modifier_apply_invoke(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_modifier_convert (struct wmOperatorType * ot)
Definition at line 966 of file object_modifier.c.
References wmOperatorType::description, edit_modifier_poll(), edit_modifier_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, modifier_convert_exec(), modifier_convert_invoke(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_modifier_copy (struct wmOperatorType * ot)
Definition at line 1005 of file object_modifier.c.
References wmOperatorType::description, edit_modifier_poll(), edit_modifier_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, modifier_copy_exec(), modifier_copy_invoke(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_modifier_move_down (struct wmOperatorType * ot)
Definition at line 876 of file object_modifier.c.
References wmOperatorType::description, edit_modifier_poll(), edit_modifier_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, modifier_move_down_exec(), modifier_move_down_invoke(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_modifier_move_up (struct wmOperatorType * ot)
Definition at line 837 of file object_modifier.c.
References wmOperatorType::description, edit_modifier_poll(), edit_modifier_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, modifier_move_up_exec(), modifier_move_up_invoke(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_modifier_remove (struct wmOperatorType * ot)
Definition at line 798 of file object_modifier.c.
References wmOperatorType::description, edit_modifier_poll(), edit_modifier_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, modifier_remove_exec(), modifier_remove_invoke(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_move_to_layer (struct wmOperatorType * ot)
Definition at line 1145 of file object_relations.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, move_to_layer_exec(), move_to_layer_invoke(), wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean_layer_member(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_multires_base_apply (struct wmOperatorType * ot)
Definition at line 1301 of file object_modifier.c.
References wmOperatorType::description, edit_modifier_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, multires_base_apply_exec(), multires_base_apply_invoke(), multires_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_multires_external_pack (struct wmOperatorType * ot)
Definition at line 1262 of file object_modifier.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, multires_external_pack_exec(), multires_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_multires_external_save (struct wmOperatorType * ot)
Definition at line 1228 of file object_modifier.c.
References BTXFILE, wmOperatorType::description, edit_modifier_properties(), wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_SAVE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, wmOperatorType::invoke, multires_external_save_exec(), multires_external_save_invoke(), multires_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, WM_FILESEL_FILEPATH, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by ED_operatortypes_object().
void OBJECT_OT_multires_higher_levels_delete (struct wmOperatorType * ot)
Definition at line 1050 of file object_modifier.c.
References wmOperatorType::description, edit_modifier_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, multires_higher_levels_delete_exec(), multires_higher_levels_delete_invoke(), multires_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_multires_reshape (struct wmOperatorType * ot)
Definition at line 1154 of file object_modifier.c.
References wmOperatorType::description, edit_modifier_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, multires_poll(), multires_reshape_exec(), multires_reshape_invoke(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_multires_subdivide (struct wmOperatorType * ot)
Definition at line 1091 of file object_modifier.c.
References wmOperatorType::description, edit_modifier_properties(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, multires_poll(), multires_subdivide_exec(), multires_subdivide_invoke(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_ocean_bake (struct wmOperatorType * ot)
Definition at line 1658 of file object_modifier.c.
References wmOperatorType::description, edit_modifier_properties(), wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, ocean_bake_exec(), ocean_bake_invoke(), ocean_bake_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_origin_clear (struct wmOperatorType * ot)
Definition at line 346 of file object_transform.c.
References wmOperatorType::description, ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_origin_clear_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_origin_set (struct wmOperatorType * ot)
Definition at line 945 of file object_transform.c.
References wmOperatorType::description, ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, GEOMETRY_TO_ORIGIN, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, object_origin_set_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, ORIGIN_TO_CURSOR, ORIGIN_TO_GEOMETRY, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, V3D_CENTER, V3D_CENTROID, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_parent_clear (struct wmOperatorType * ot)
Definition at line 464 of file object_relations.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, parent_clear_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_parent_no_inverse_set (struct wmOperatorType * ot)
Definition at line 787 of file object_relations.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, parent_noinv_set_exec(), wmOperatorType::poll, and WM_operator_confirm().
Referenced by ED_operatortypes_object().
void OBJECT_OT_parent_set (struct wmOperatorType * ot)
Definition at line 730 of file object_relations.c.
References wmOperatorType::description, ED_operator_object_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, parent_set_exec(), parent_set_invoke(), wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_paths_calculate (struct wmOperatorType * ot)
Definition at line 1149 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_calculate_paths_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_paths_clear (struct wmOperatorType * ot)
Definition at line 1193 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_clear_paths_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_posemode_toggle (struct wmOperatorType * ot)
Definition at line 595 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and posemode_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_proxy_make (struct wmOperatorType * ot)
Definition at line 394 of file object_relations.c.
References wmOperatorType::description, DummyRNA_DEFAULT_items, ED_operator_object_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, make_proxy_exec(), make_proxy_invoke(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, proxy_group_object_itemf(), RNA_def_enum(), RNA_def_enum_funcs(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_rotation_clear (struct wmOperatorType * ot)
Definition at line 280 of file object_transform.c.
References wmOperatorType::description, ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_rotation_clear_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_scale_clear (struct wmOperatorType * ot)
Definition at line 300 of file object_transform.c.
References wmOperatorType::description, ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_scale_clear_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_all (struct wmOperatorType * ot)
Definition at line 787 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_select_all_exec(), objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_properties_select_all().
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_by_layer (struct wmOperatorType * ot)
Definition at line 722 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_select_by_layer_exec(), objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_by_type (struct wmOperatorType * ot)
Definition at line 165 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_select_by_type_exec(), object_type_items, objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_grouped (struct wmOperatorType * ot)
Definition at line 673 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_select_grouped_exec(), objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_linked (struct wmOperatorType * ot)
Definition at line 347 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_select_linked_exec(), objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_mirror (struct wmOperatorType * ot)
Definition at line 889 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_select_mirror_exec(), objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_random (struct wmOperatorType * ot)
Definition at line 937 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_select_random_exec(), objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_percentage(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_select_same_group (struct wmOperatorType * ot)
Definition at line 836 of file object_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAX_ID_NAME, wmOperatorType::name, object_select_same_group_exec(), objects_selectable_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_shade_flat (struct wmOperatorType * ot)
Definition at line 1252 of file object_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, shade_poll(), and shade_smooth_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_shade_smooth (struct wmOperatorType * ot)
Definition at line 1267 of file object_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, shade_poll(), and shade_smooth_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_shape_key_add (struct wmOperatorType * ot)
Definition at line 280 of file object_shapekey.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), shape_key_add_exec(), shape_key_mode_poll(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_shape_key_clear (struct wmOperatorType * ot)
Definition at line 341 of file object_shapekey.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, shape_key_clear_exec(), and shape_key_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_shape_key_mirror (struct wmOperatorType * ot)
Definition at line 401 of file object_shapekey.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, shape_key_mirror_exec(), and shape_key_mode_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_shape_key_move (struct wmOperatorType * ot)
Definition at line 466 of file object_shapekey.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), shape_key_mode_poll(), shape_key_move_exec(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_shape_key_remove (struct wmOperatorType * ot)
Definition at line 308 of file object_shapekey.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, shape_key_mode_poll(), and shape_key_remove_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_shape_key_retime (struct wmOperatorType * ot)
Definition at line 376 of file object_shapekey.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, shape_key_poll(), and shape_key_retime_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_slow_parent_clear (struct wmOperatorType * ot)
Definition at line 828 of file object_relations.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_slow_parent_clear_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by ED_operatortypes_object().
void OBJECT_OT_slow_parent_set (struct wmOperatorType * ot)
Definition at line 867 of file object_relations.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_slow_parent_set_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by ED_operatortypes_object().
void OBJECT_OT_speaker_add (struct wmOperatorType * ot)
Definition at line 843 of file object_add.c.
References wmOperatorType::description, ED_object_add_generic_props(), ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_speaker_add_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_object().
void OBJECT_OT_text_add (struct wmOperatorType * ot)
Definition at line 630 of file object_add.c.
References wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_add_text_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_object().
void OBJECT_OT_track_clear (struct wmOperatorType * ot)
Definition at line 929 of file object_relations.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_track_clear_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_track_set (struct wmOperatorType * ot)
Definition at line 1034 of file object_relations.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, track_set_exec(), and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_transform_apply (struct wmOperatorType * ot)
Definition at line 620 of file object_transform.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_transform_apply_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_add (struct wmOperatorType * ot)
Definition at line 2119 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_add_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_assign (struct wmOperatorType * ot)
Definition at line 2184 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, vertex_group_assign_exec(), and vertex_group_poll_edit_or_wpaint_vert_select().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_blend (struct wmOperatorType * ot)
Definition at line 2568 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_FACTOR, PROP_FLOAT, RNA_def_property(), RNA_def_property_float_default(), RNA_def_property_range(), RNA_def_property_ui_text(), wmOperatorType::srna, vertex_group_blend_exec(), and vertex_group_blend_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_clean (struct wmOperatorType * ot)
Definition at line 2609 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float(), wmOperatorType::srna, vertex_group_clean_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_copy (struct wmOperatorType * ot)
Definition at line 2309 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_copy_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_copy_to_linked (struct wmOperatorType * ot)
Definition at line 2694 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_copy_to_linked_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_copy_to_selected (struct wmOperatorType * ot)
Definition at line 2734 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_copy_to_selected_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_deselect (struct wmOperatorType * ot)
Definition at line 2283 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_deselect_exec(), and vertex_group_poll_edit_or_wpaint_vert_select().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_fix (struct wmOperatorType * ot)
Definition at line 2444 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), wmOperatorType::srna, vertex_group_fix_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_invert (struct wmOperatorType * ot)
Definition at line 2507 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, TRUE, vertex_group_invert_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_levels (struct wmOperatorType * ot)
Definition at line 2339 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), wmOperatorType::srna, vertex_group_levels_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_lock (struct wmOperatorType * ot)
Definition at line 2477 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_lock_exec(), vertex_group_poll(), and WM_operator_properties_select_all().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_mirror (struct wmOperatorType * ot)
Definition at line 2646 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, TRUE, vertex_group_mirror_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_move (struct wmOperatorType * ot)
Definition at line 2986 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, vertex_group_poll(), and vgroup_move_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_normalize (struct wmOperatorType * ot)
Definition at line 2369 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_normalize_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_normalize_all (struct wmOperatorType * ot)
Definition at line 2397 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, TRUE, vertex_group_normalize_all_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_remove (struct wmOperatorType * ot)
Definition at line 2149 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, vertex_group_poll(), and vertex_group_remove_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_remove_from (struct wmOperatorType * ot)
Definition at line 2226 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, vertex_group_poll_edit_or_wpaint_vert_select(), and vertex_group_remove_from_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_select (struct wmOperatorType * ot)
Definition at line 2259 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_poll_edit_or_wpaint_vert_select(), and vertex_group_select_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_set_active (struct wmOperatorType * ot)
Definition at line 2791 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), set_active_group_exec(), wmOperatorType::srna, vertex_group_poll(), vgroup_itemf(), and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_sort (struct wmOperatorType * ot)
Definition at line 2933 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_poll(), and vertex_group_sort_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_parent_set (struct wmOperatorType * ot)
Definition at line 260 of file object_relations.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_parent_set_exec(), vertex_parent_set_poll(), and WM_operator_confirm().
Referenced by ED_operatortypes_object().
void OBJECT_OT_visual_transform_apply (struct wmOperatorType * ot)
Definition at line 591 of file object_transform.c.
References wmOperatorType::description, ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and visual_transform_apply_exec().
Referenced by ED_operatortypes_object().
void POSE_OT_constraint_add (struct wmOperatorType * ot)
Definition at line 1647 of file object_constraint.c.
References constraint_type_items, wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_constraint_add_exec(), wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void POSE_OT_constraint_add_with_targets (struct wmOperatorType * ot)
Definition at line 1666 of file object_constraint.c.
References constraint_type_items, wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_constraint_add_exec(), wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void POSE_OT_constraints_clear (struct wmOperatorType * ot)
Definition at line 1172 of file object_constraint.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and pose_constraints_clear_exec().
Referenced by ED_operatortypes_object().
void POSE_OT_constraints_copy (struct wmOperatorType * ot)
Definition at line 1253 of file object_constraint.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_constraint_copy_exec().
Referenced by ED_operatortypes_object().
void POSE_OT_ik_add (struct wmOperatorType * ot)
Definition at line 1752 of file object_constraint.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_ik_add_exec(), pose_ik_add_invoke(), RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void POSE_OT_ik_clear (struct wmOperatorType * ot)
Definition at line 1803 of file object_constraint.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_ik_clear_exec().
Referenced by ED_operatortypes_object().
Variable Documentation
enum { ... } eObject_Hook_Add_Mode