Blender: keyingsets.c File Reference
keyingsets.c File Reference
animation
#include <stdio.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_dynstr.h"
#include "BLI_utildefines.h"
#include "DNA_anim_types.h"
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "BKE_main.h"
#include "BKE_animsys.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_report.h"
#include "ED_keyframing.h"
#include "ED_screen.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "anim_intern.h"
Classes
struct tRKS_DSource
Typedefs
typedef struct tRKS_DSource tRKS_DSource
Functions
static int keyingset_poll_default_add (bContext *C)
static int keyingset_poll_active_edit (bContext *C)
static int keyingset_poll_activePath_edit (bContext *C)
static int add_default_keyingset_exec (bContext *C, wmOperator *UNUSED(op))
void ANIM_OT_keying_set_add (wmOperatorType *ot)
static int remove_active_keyingset_exec (bContext *C, wmOperator *op)
void ANIM_OT_keying_set_remove (wmOperatorType *ot)
static int add_empty_ks_path_exec (bContext *C, wmOperator *op)
void ANIM_OT_keying_set_path_add (wmOperatorType *ot)
static int remove_active_ks_path_exec (bContext *C, wmOperator *op)
void ANIM_OT_keying_set_path_remove (wmOperatorType *ot)
static int add_keyingset_button_exec (bContext *C, wmOperator *op)
void ANIM_OT_keyingset_button_add (wmOperatorType *ot)
static int remove_keyingset_button_exec (bContext *C, wmOperator *op)
void ANIM_OT_keyingset_button_remove (wmOperatorType *ot)
static int keyingset_active_menu_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int keyingset_active_menu_exec (bContext *C, wmOperator *op)
void ANIM_OT_keying_set_active_set (wmOperatorType *ot)
KeyingSetInfo * ANIM_keyingset_info_find_named (const char name[])
KeyingSet * ANIM_builtin_keyingset_get_named (KeyingSet *prevKS, const char name[])
void ANIM_keyingset_info_register (KeyingSetInfo *ksi)
void ANIM_keyingset_info_unregister (Main *bmain, KeyingSetInfo *ksi)
void ANIM_keyingset_infos_exit (void)
KeyingSet * ANIM_scene_get_active_keyingset (Scene *scene)
int ANIM_scene_get_keyingset_index (Scene *scene, KeyingSet *ks)
KeyingSet * ANIM_get_keyingset_for_autokeying (Scene *scene, const char *tranformKSName)
EnumPropertyItem * ANIM_keying_sets_enum_itemf (bContext *C, PointerRNA *UNUSED(ptr), PropertyRNA *UNUSED(prop), int *free)
short ANIM_keyingset_context_ok_poll (bContext *C, KeyingSet *ks)
static void RKS_ITER_overrides_list (KeyingSetInfo *ksi, bContext *C, KeyingSet *ks, ListBase *dsources)
void ANIM_relative_keyingset_add_source (ListBase *dsources, ID *id, StructRNA *srna, void *data)
short ANIM_validate_keyingset (bContext *C, ListBase *dsources, KeyingSet *ks)
int ANIM_apply_keyingset (bContext *C, ListBase *dsources, bAction *act, KeyingSet *ks, short mode, float cfra)
Variables
static ListBase keyingset_type_infos = {NULL, NULL}
ListBase builtin_keyingsets = {NULL, NULL}
Detailed Description
Definition in file keyingsets.c.
Typedef Documentation
typedef struct tRKS_DSource tRKS_DSource
Function Documentation
static int add_default_keyingset_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 116 of file keyingsets.c.
References Scene::active_keyingset, ANIM_get_keyframing_flags(), BKE_keyingset_add(), BLI_countlist(), CTX_data_scene(), KEYINGSET_ABSOLUTE, Scene::keyingsets, NC_SCENE, ND_KEYINGSET, NULL, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by ANIM_OT_keying_set_add().
static int add_empty_ks_path_exec (bContext * C, wmOperator * op) [static]
Definition at line 201 of file keyingsets.c.
References Scene::active_keyingset, KeyingSet::active_path, BKE_report(), BLI_addtail(), BLI_countlist(), BLI_findlink(), CTX_data_scene(), KS_Path::flag, KS_Path::groupmode, ID_OB, KS_Path::idtype, Scene::keyingsets, KSP_FLAG_WHOLE_ARRAY, KSP_GROUP_KSNAME, MEM_callocN(), OPERATOR_CANCELLED, OPERATOR_FINISHED, KeyingSet::paths, wmOperator::reports, and RPT_ERROR.
Referenced by ANIM_OT_keying_set_path_add().
static int add_keyingset_button_exec (bContext * C, wmOperator * op) [static]
Definition at line 290 of file keyingsets.c.
References Scene::active_keyingset, KeyingSet::active_path, ANIM_get_keyframing_flags(), BKE_keyingset_add(), BKE_keyingset_add_path(), BKE_report(), BLI_countlist(), BLI_findlink(), CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), PointerRNA::data, PointerRNA::id, INSERTKEY_XYZ2RGB, IS_AUTOKEY_FLAG, KEYINGSET_ABSOLUTE, Scene::keyingsets, KSP_FLAG_WHOLE_ARRAY, KSP_GROUP_KSNAME, MEM_freeN(), NC_SCENE, ND_KEYINGSET, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, KeyingSet::paths, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_path_from_ID_to_property(), RNA_property_animateable(), RPT_ERROR, uiContextActiveProperty(), and WM_event_add_notifier().
Referenced by ANIM_OT_keyingset_button_add().
int ANIM_apply_keyingset (bContext * C, ListBase * dsources, bAction * act, KeyingSet * ks, short mode, float cfra)
Definition at line 908 of file keyingsets.c.
References ANIM_get_keyframing_flags(), ANIM_validate_keyingset(), KS_Path::array_index, BKE_reportf(), CTX_data_scene(), CTX_wm_reports(), delete_keyframe(), ListBase::first, KS_Path::flag, KS_Path::group, KS_Path::groupmode, GS, i, KS_Path::id, ID_OB, insert_keyframe(), KS_Path::keyingflag, KeyingSet::keyingflag, KSP_FLAG_WHOLE_ARRAY, KSP_GROUP_KSNAME, KSP_GROUP_NONE, MODIFYKEY_MODE_DELETE, MODIFYKEY_MODE_INSERT, NA_EDITED, ID::name, KeyingSet::name, NC_ANIMATION, ND_KEYFRAME, KS_Path::next, NULL, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, KeyingSet::paths, tRKS_DSource::ptr, Object::recalc, RNA_id_pointer_create(), KS_Path::rna_path, RNA_path_resolve(), RNA_property_array_length(), RPT_WARNING, and WM_main_add_notifier().
Referenced by autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), delete_key_exec(), ED_autokeyframe_object(), ED_autokeyframe_pchan(), insert_key_exec(), move_camera(), pose_clear_transform_generic_exec(), poseAnim_mapping_autoKeyframe(), poselib_add_exec(), and poselib_keytag_pose().
KeyingSet* ANIM_builtin_keyingset_get_named (KeyingSet * prevKS, const char name[]) [read]
Definition at line 542 of file keyingsets.c.
References ListBase::first, KeyingSet::idname, KeyingSet::next, and NULL.
Referenced by ANIM_get_keyingset_for_autokeying(), autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), move_camera(), pose_flip_quats_exec(), and poselib_add_exec().
KeyingSet* ANIM_get_keyingset_for_autokeying (Scene * scene, const char * tranformKSName) [read]
Definition at line 695 of file keyingsets.c.
References Scene::active_keyingset, ANIM_builtin_keyingset_get_named(), ANIM_KS_AVAILABLE_ID, ANIM_scene_get_active_keyingset(), IS_AUTOKEY_FLAG, and NULL.
Referenced by object_clear_transform_generic_exec(), pose_clear_transform_generic_exec(), pose_paste_exec(), poseAnim_mapping_autoKeyframe(), poselib_keytag_pose(), snap_sel_to_curs(), and snap_sel_to_grid().
EnumPropertyItem* ANIM_keying_sets_enum_itemf (bContext * C, PointerRNA * UNUSEDptr, PropertyRNA * UNUSEDprop, int * free)
Definition at line 712 of file keyingsets.c.
References Scene::active_keyingset, ANIM_keyingset_context_ok_poll(), CTX_data_scene(), KeyingSet::description, DummyRNA_DEFAULT_items, ListBase::first, i, EnumPropertyItem::identifier, KeyingSet::idname, Scene::keyingsets, KeyingSet::name, KeyingSet::next, NULL, RNA_enum_item_add(), RNA_enum_item_add_separator(), and RNA_enum_item_end().
Referenced by ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_menu(), and ANIM_OT_keying_set_active_set().
short ANIM_keyingset_context_ok_poll (bContext * C, KeyingSet * ks)
Definition at line 783 of file keyingsets.c.
References ANIM_keyingset_info_find_named(), KeyingSet::flag, KEYINGSET_ABSOLUTE, NULL, KeyingSetInfo::poll, and KeyingSet::typeinfo.
Referenced by ANIM_keying_sets_enum_itemf().
KeyingSetInfo* ANIM_keyingset_info_find_named (const char name[])
Definition at line 531 of file keyingsets.c.
References BLI_findstring(), and NULL.
Referenced by ANIM_keyingset_context_ok_poll(), and ANIM_validate_keyingset().
void ANIM_keyingset_info_register (KeyingSetInfo * ksi)
Definition at line 574 of file keyingsets.c.
References BKE_keyingset_add(), BLI_addtail(), BLI_strncpy(), KeyingSetInfo::description, KeyingSet::description, KeyingSetInfo::idname, KeyingSetInfo::keyingflag, KeyingSetInfo::name, and KeyingSet::typeinfo.
void ANIM_keyingset_info_unregister (Main * bmain, KeyingSetInfo * ksi)
Definition at line 594 of file keyingsets.c.
References BKE_keyingset_free(), BLI_freelinkN(), BLI_remlink(), BLI_remlink_safe(), ListBase::first, Scene::id, KeyingSetInfo::idname, Scene::keyingsets, MEM_freeN(), ID::next, KeyingSet::next, Main::scene, and KeyingSet::typeinfo.
void ANIM_keyingset_infos_exit (void)
Definition at line 623 of file keyingsets.c.
References BKE_keyingsets_free(), BLI_freelinkN(), ExtensionRNA::data, KeyingSetInfo::ext, ListBase::first, ExtensionRNA::free, KeyingSetInfo::next, and next.
Referenced by WM_exit_ext().
void ANIM_OT_keying_set_active_set (wmOperatorType * ot)
Definition at line 497 of file keyingsets.c.
References ANIM_keying_sets_enum_itemf(), DummyRNA_DEFAULT_items, ED_operator_areaactive(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, keyingset_active_menu_exec(), keyingset_active_menu_invoke(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_enum_funcs(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keying_set_add (wmOperatorType * ot)
Definition at line 140 of file keyingsets.c.
References add_default_keyingset_exec(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, keyingset_poll_default_add(), wmOperatorType::name, and wmOperatorType::poll.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keying_set_path_add (wmOperatorType * ot)
Definition at line 230 of file keyingsets.c.
References add_empty_ks_path_exec(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, keyingset_poll_active_edit(), wmOperatorType::name, and wmOperatorType::poll.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keying_set_path_remove (wmOperatorType * ot)
Definition at line 273 of file keyingsets.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, keyingset_poll_activePath_edit(), wmOperatorType::name, wmOperatorType::poll, and remove_active_ks_path_exec().
Referenced by ED_operatortypes_anim().
void ANIM_OT_keying_set_remove (wmOperatorType * ot)
Definition at line 187 of file keyingsets.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, keyingset_poll_active_edit(), wmOperatorType::name, wmOperatorType::poll, and remove_active_keyingset_exec().
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyingset_button_add (wmOperatorType * ot)
Definition at line 371 of file keyingsets.c.
References add_keyingset_button_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyingset_button_remove (wmOperatorType * ot)
Definition at line 450 of file keyingsets.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and remove_keyingset_button_exec().
Referenced by ED_operatortypes_anim().
void ANIM_relative_keyingset_add_source (ListBase * dsources, ID * id, StructRNA * srna, void * data)
Definition at line 827 of file keyingsets.c.
References BLI_addtail(), ELEM, MEM_callocN(), NULL, tRKS_DSource::ptr, RNA_id_pointer_create(), and RNA_pointer_create().
Referenced by autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), ED_autokeyframe_object(), ED_autokeyframe_pchan(), move_camera(), poseAnim_mapping_autoKeyframe(), and poselib_keytag_pose().
KeyingSet* ANIM_scene_get_active_keyingset (Scene * scene) [read]
Definition at line 647 of file keyingsets.c.
References Scene::active_keyingset, BLI_findlink(), Scene::keyingsets, and NULL.
Referenced by ANIM_get_keyingset_for_autokeying(), autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), pose_select_same_keyingset(), and select_grouped_keyingset().
int ANIM_scene_get_keyingset_index (Scene * scene, KeyingSet * ks)
Definition at line 665 of file keyingsets.c.
References BLI_findindex(), Scene::keyingsets, and NULL.
short ANIM_validate_keyingset (bContext * C, ListBase * dsources, KeyingSet * ks)
Definition at line 860 of file keyingsets.c.
References ANIM_keyingset_info_find_named(), BKE_keyingset_free(), ListBase::first, KeyingSet::flag, KeyingSetInfo::iter, KEYINGSET_ABSOLUTE, MODIFYKEY_INVALID_CONTEXT, MODIFYKEY_MISSING_TYPEINFO, NULL, KeyingSet::paths, KeyingSetInfo::poll, RKS_ITER_overrides_list(), and KeyingSet::typeinfo.
Referenced by ANIM_apply_keyingset(), pose_select_same_keyingset(), and select_grouped_keyingset().
static int keyingset_active_menu_exec (bContext * C, wmOperator * op) [static]
Definition at line 483 of file keyingsets.c.
References Scene::active_keyingset, CTX_data_scene(), NC_SCENE, ND_KEYINGSET, NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), and WM_event_add_notifier().
Referenced by ANIM_OT_keying_set_active_set().
static int keyingset_active_menu_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 469 of file keyingsets.c.
References wmOperatorType::name, OPERATOR_CANCELLED, wmOperator::type, uiItemsEnumO(), uiPupMenuBegin(), uiPupMenuEnd(), and uiPupMenuLayout().
Referenced by ANIM_OT_keying_set_active_set().
static int keyingset_poll_active_edit (bContext * C) [static]
Definition at line 85 of file keyingsets.c.
References Scene::active_keyingset, CTX_data_scene(), ListBase::first, Scene::keyingsets, and NULL.
Referenced by ANIM_OT_keying_set_path_add(), and ANIM_OT_keying_set_remove().
static int keyingset_poll_activePath_edit (bContext * C) [static]
Definition at line 97 of file keyingsets.c.
References Scene::active_keyingset, KeyingSet::active_path, BLI_findlink(), CTX_data_scene(), ListBase::first, Scene::keyingsets, NULL, and KeyingSet::paths.
Referenced by ANIM_OT_keying_set_path_remove().
static int keyingset_poll_default_add (bContext * C) [static]
Definition at line 78 of file keyingsets.c.
References CTX_data_scene(), and NULL.
Referenced by ANIM_OT_keying_set_add().
static int remove_active_keyingset_exec (bContext * C, wmOperator * op) [static]
Definition at line 154 of file keyingsets.c.
References Scene::active_keyingset, BKE_keyingset_free(), BKE_report(), BLI_findlink(), BLI_freelinkN(), CTX_data_scene(), Scene::keyingsets, NC_SCENE, ND_KEYINGSET, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, and WM_event_add_notifier().
Referenced by ANIM_OT_keying_set_remove().
static int remove_active_ks_path_exec (bContext * C, wmOperator * op) [static]
Definition at line 244 of file keyingsets.c.
References Scene::active_keyingset, KeyingSet::active_path, BKE_keyingset_free_path(), BKE_report(), BLI_findlink(), CTX_data_scene(), Scene::keyingsets, OPERATOR_CANCELLED, OPERATOR_FINISHED, KeyingSet::paths, wmOperator::reports, and RPT_ERROR.
Referenced by ANIM_OT_keying_set_path_remove().
static int remove_keyingset_button_exec (bContext * C, wmOperator * op) [static]
Definition at line 390 of file keyingsets.c.
References Scene::active_keyingset, BKE_keyingset_find_path(), BKE_keyingset_free_path(), BKE_report(), BLI_findlink(), CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), PointerRNA::data, PointerRNA::id, Scene::keyingsets, KSP_GROUP_KSNAME, MEM_freeN(), KeyingSet::name, NC_SCENE, ND_KEYINGSET, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RNA_path_from_ID_to_property(), RPT_ERROR, uiContextActiveProperty(), and WM_event_add_notifier().
Referenced by ANIM_OT_keyingset_button_remove().
static void RKS_ITER_overrides_list (KeyingSetInfo * ksi, bContext * C, KeyingSet * ks, ListBase * dsources) [static]
Definition at line 816 of file keyingsets.c.
References ListBase::first, KeyingSetInfo::generate, tRKS_DSource::next, and tRKS_DSource::ptr.
Referenced by ANIM_validate_keyingset().
Variable Documentation
ListBase builtin_keyingsets = {NULL, NULL}
Definition at line 526 of file keyingsets.c.
Referenced by delete_key_exec(), and insert_key_exec().
ListBase keyingset_type_infos = {NULL, NULL} [static]
Definition at line 523 of file keyingsets.c.