Blender: RAS_TexVert Class Reference
RAS_TexVert Class Reference
#include <RAS_TexVert.h>
Public Types
enum { FLAT = 1, SECOND_UV = 2, MAX_UNIT = 8 }
Public Member Functions
short getFlag () const
unsigned int getUnit () const
RAS_TexVert ()
RAS_TexVert (const MT_Point3 &xyz, const MT_Point2 &uv, const MT_Point2 &uv2, const MT_Vector4 &tangent, const unsigned int rgba, const MT_Vector3 &normal, const bool flat, const unsigned int origindex)
~RAS_TexVert ()
const float * getUV1 () const
const float * getUV2 () const
const float * getXYZ () const
const float * getNormal () const
short int getSoftBodyIndex () const
void setSoftBodyIndex (short int sbIndex)
const float * getTangent () const
const unsigned char * getRGBA () const
unsigned int getOrigIndex () const
void SetXYZ (const MT_Point3 &xyz)
void SetXYZ (const float *xyz)
void SetUV (const MT_Point2 &uv)
void SetUV2 (const MT_Point2 &uv)
void SetRGBA (const unsigned int rgba)
void SetNormal (const MT_Vector3 &normal)
void SetTangent (const MT_Vector3 &tangent)
void SetFlag (const short flag)
void SetUnit (const unsigned u)
void SetRGBA (const MT_Vector4 &rgba)
const MT_Point3 & xyz ()
void Transform (const class MT_Matrix4x4 &mat, const class MT_Matrix4x4 &nmat)
bool closeTo (const RAS_TexVert *other)
Detailed Description
Definition at line 47 of file RAS_TexVert.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
FLAT
SECOND_UV
MAX_UNIT
Definition at line 65 of file RAS_TexVert.h.
Constructor & Destructor Documentation
RAS_TexVert::RAS_TexVert () [inline]
Definition at line 74 of file RAS_TexVert.h.
RAS_TexVert::RAS_TexVert (const MT_Point3 & xyz, const MT_Point2 & uv, const MT_Point2 & uv2, const MT_Vector4 & tangent, const unsigned int rgba, const MT_Vector3 & normal, const bool flat, const unsigned int origindex)
Definition at line 36 of file RAS_TexVert.cpp.
References FLAT, MT_Tuple4::getValue(), MT_Tuple3::getValue(), MT_Tuple2::getValue(), SetNormal(), and SetRGBA().
RAS_TexVert::~RAS_TexVert () [inline]
Definition at line 84 of file RAS_TexVert.h.
Member Function Documentation
bool RAS_TexVert::closeTo (const RAS_TexVert * other)
Definition at line 122 of file RAS_TexVert.cpp.
References MT_fuzzyEqual().
short RAS_TexVert::getFlag () const
Definition at line 136 of file RAS_TexVert.cpp.
Referenced by BL_MeshDeformer::RecalcNormals(), and RAS_OpenGLRasterizer::TexCoord().
const float* RAS_TexVert::getNormal () const [inline]
Definition at line 98 of file RAS_TexVert.h.
Referenced by RAS_VAOpenGLRasterizer::IndexPrimitives(), RAS_OpenGLRasterizer::IndexPrimitivesInternal(), RAS_VAOpenGLRasterizer::IndexPrimitivesMulti(), and RAS_OpenGLRasterizer::TexCoord().
unsigned int RAS_TexVert::getOrigIndex () const [inline]
Definition at line 120 of file RAS_TexVert.h.
Referenced by BL_SkinDeformer::Apply(), BL_MeshDeformer::Apply(), KX_NavMeshObject::BuildVertIndArrays(), BL_MeshDeformer::RecalcNormals(), and CcdShapeConstructionInfo::UpdateMesh().
const unsigned char* RAS_TexVert::getRGBA () const [inline]
Definition at line 116 of file RAS_TexVert.h.
Referenced by RAS_VAOpenGLRasterizer::IndexPrimitives(), RAS_OpenGLRasterizer::IndexPrimitivesInternal(), RAS_VAOpenGLRasterizer::IndexPrimitivesMulti(), and RAS_OpenGLRasterizer::TexCoord().
short int RAS_TexVert::getSoftBodyIndex () const [inline]
Definition at line 102 of file RAS_TexVert.h.
const float* RAS_TexVert::getTangent () const [inline]
Definition at line 112 of file RAS_TexVert.h.
Referenced by RAS_OpenGLRasterizer::TexCoord().
unsigned int RAS_TexVert::getUnit () const
Definition at line 142 of file RAS_TexVert.cpp.
Referenced by RAS_OpenGLRasterizer::TexCoord().
const float* RAS_TexVert::getUV1 () const [inline]
Definition at line 86 of file RAS_TexVert.h.
Referenced by RAS_VAOpenGLRasterizer::IndexPrimitives(), RAS_OpenGLRasterizer::IndexPrimitivesInternal(), and RAS_OpenGLRasterizer::TexCoord().
const float* RAS_TexVert::getUV2 () const [inline]
Definition at line 90 of file RAS_TexVert.h.
Referenced by RAS_OpenGLRasterizer::TexCoord().
const float* RAS_TexVert::getXYZ () const [inline]
Definition at line 94 of file RAS_TexVert.h.
Referenced by ImageRender::ImageRender(), RAS_VAOpenGLRasterizer::IndexPrimitives(), RAS_OpenGLRasterizer::IndexPrimitives_3DText(), RAS_OpenGLRasterizer::IndexPrimitivesInternal(), RAS_VAOpenGLRasterizer::IndexPrimitivesMulti(), DbvtCullingCallback::Process(), and RAS_OpenGLRasterizer::TexCoord().
void RAS_TexVert::SetFlag (const short flag)
Definition at line 100 of file RAS_TexVert.cpp.
void RAS_TexVert::SetNormal (const MT_Vector3 & normal)
Definition at line 110 of file RAS_TexVert.cpp.
References MT_Tuple3::getValue().
Referenced by BL_SkinDeformer::Apply(), RAS_TexVert(), BL_MeshDeformer::RecalcNormals(), and Transform().
void RAS_TexVert::SetRGBA (const MT_Vector4 & rgba)
Definition at line 63 of file RAS_TexVert.cpp.
void RAS_TexVert::SetRGBA (const unsigned int rgba)
Definition at line 94 of file RAS_TexVert.cpp.
Referenced by RAS_TexVert(), and RAS_MeshObject::SetVertexColor().
void RAS_TexVert::setSoftBodyIndex (short int sbIndex) [inline]
Definition at line 107 of file RAS_TexVert.h.
void RAS_TexVert::SetTangent (const MT_Vector3 & tangent)
Definition at line 115 of file RAS_TexVert.cpp.
References MT_Tuple3::getValue().
Referenced by Transform().
void RAS_TexVert::SetUnit (const unsigned u)
Definition at line 105 of file RAS_TexVert.cpp.
References MAX_UNIT.
void RAS_TexVert::SetUV (const MT_Point2 & uv)
Definition at line 83 of file RAS_TexVert.cpp.
References MT_Tuple2::getValue().
void RAS_TexVert::SetUV2 (const MT_Point2 & uv)
Definition at line 88 of file RAS_TexVert.cpp.
References MT_Tuple2::getValue().
void RAS_TexVert::SetXYZ (const MT_Point3 & xyz)
Definition at line 73 of file RAS_TexVert.cpp.
References MT_Tuple3::getValue().
Referenced by BL_SkinDeformer::Apply(), BL_MeshDeformer::Apply(), and Transform().
void RAS_TexVert::SetXYZ (const float * xyz)
Definition at line 78 of file RAS_TexVert.cpp.
void RAS_TexVert::Transform (const class MT_Matrix4x4 & mat, const class MT_Matrix4x4 & nmat)
Definition at line 147 of file RAS_TexVert.cpp.
References SetNormal(), SetTangent(), and SetXYZ().
Referenced by RAS_MeshSlot::Join(), and RAS_MeshSlot::Split().
const MT_Point3 & RAS_TexVert::xyz ()
Definition at line 57 of file RAS_TexVert.cpp.
References g_pt3, and MT_Tuple3::setValue().
Referenced by RAS_CalcTexMatrix().
The documentation for this class was generated from the following files:
RAS_TexVert.h
RAS_TexVert.cpp