Blender: physics_intern.h File Reference
physics_intern.h File Reference
physics
Functions
void PARTICLE_OT_select_all (struct wmOperatorType *ot)
void PARTICLE_OT_select_roots (struct wmOperatorType *ot)
void PARTICLE_OT_select_tips (struct wmOperatorType *ot)
void PARTICLE_OT_select_linked (struct wmOperatorType *ot)
void PARTICLE_OT_select_less (struct wmOperatorType *ot)
void PARTICLE_OT_select_more (struct wmOperatorType *ot)
void PARTICLE_OT_hide (struct wmOperatorType *ot)
void PARTICLE_OT_reveal (struct wmOperatorType *ot)
void PARTICLE_OT_rekey (struct wmOperatorType *ot)
void PARTICLE_OT_subdivide (struct wmOperatorType *ot)
void PARTICLE_OT_remove_doubles (struct wmOperatorType *ot)
void PARTICLE_OT_weight_set (struct wmOperatorType *ot)
void PARTICLE_OT_delete (struct wmOperatorType *ot)
void PARTICLE_OT_mirror (struct wmOperatorType *ot)
void PARTICLE_OT_brush_edit (struct wmOperatorType *ot)
void PARTICLE_OT_particle_edit_toggle (struct wmOperatorType *ot)
void PARTICLE_OT_edited_clear (struct wmOperatorType *ot)
void OBJECT_OT_particle_system_add (struct wmOperatorType *ot)
void OBJECT_OT_particle_system_remove (struct wmOperatorType *ot)
void PARTICLE_OT_new (struct wmOperatorType *ot)
void PARTICLE_OT_new_target (struct wmOperatorType *ot)
void PARTICLE_OT_target_remove (struct wmOperatorType *ot)
void PARTICLE_OT_target_move_up (struct wmOperatorType *ot)
void PARTICLE_OT_target_move_down (struct wmOperatorType *ot)
void PARTICLE_OT_connect_hair (struct wmOperatorType *ot)
void PARTICLE_OT_disconnect_hair (struct wmOperatorType *ot)
void PARTICLE_OT_dupliob_copy (struct wmOperatorType *ot)
void PARTICLE_OT_dupliob_remove (struct wmOperatorType *ot)
void PARTICLE_OT_dupliob_move_up (struct wmOperatorType *ot)
void PARTICLE_OT_dupliob_move_down (struct wmOperatorType *ot)
void BOID_OT_rule_add (struct wmOperatorType *ot)
void BOID_OT_rule_del (struct wmOperatorType *ot)
void BOID_OT_rule_move_up (struct wmOperatorType *ot)
void BOID_OT_rule_move_down (struct wmOperatorType *ot)
void BOID_OT_state_add (struct wmOperatorType *ot)
void BOID_OT_state_del (struct wmOperatorType *ot)
void BOID_OT_state_move_up (struct wmOperatorType *ot)
void BOID_OT_state_move_down (struct wmOperatorType *ot)
void FLUID_OT_bake (struct wmOperatorType *ot)
void DPAINT_OT_bake (struct wmOperatorType *ot)
void DPAINT_OT_surface_slot_add (struct wmOperatorType *ot)
void DPAINT_OT_surface_slot_remove (struct wmOperatorType *ot)
void DPAINT_OT_type_toggle (struct wmOperatorType *ot)
void DPAINT_OT_output_toggle (struct wmOperatorType *ot)
void PTCACHE_OT_bake_all (struct wmOperatorType *ot)
void PTCACHE_OT_free_bake_all (struct wmOperatorType *ot)
void PTCACHE_OT_bake (struct wmOperatorType *ot)
void PTCACHE_OT_free_bake (struct wmOperatorType *ot)
void PTCACHE_OT_bake_from_cache (struct wmOperatorType *ot)
void PTCACHE_OT_add (struct wmOperatorType *ot)
void PTCACHE_OT_remove (struct wmOperatorType *ot)
Detailed Description
Definition in file physics_intern.h.
Function Documentation
void BOID_OT_rule_add (struct wmOperatorType * ot)
Definition at line 90 of file particle_boids.c.
References boidrule_type_items, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::prop, RNA_def_enum(), rule_add_exec(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by operatortypes_boids().
void BOID_OT_rule_del (struct wmOperatorType * ot)
Definition at line 143 of file particle_boids.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and rule_del_exec().
Referenced by operatortypes_boids().
void BOID_OT_rule_move_down (struct wmOperatorType * ot)
Definition at line 221 of file particle_boids.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and rule_move_down_exec().
Referenced by operatortypes_boids().
void BOID_OT_rule_move_up (struct wmOperatorType * ot)
Definition at line 183 of file particle_boids.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and rule_move_up_exec().
Referenced by operatortypes_boids().
void BOID_OT_state_add (struct wmOperatorType * ot)
Definition at line 261 of file particle_boids.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and state_add_exec().
Referenced by operatortypes_boids().
void BOID_OT_state_del (struct wmOperatorType * ot)
Definition at line 316 of file particle_boids.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and state_del_exec().
Referenced by operatortypes_boids().
void BOID_OT_state_move_down (struct wmOperatorType * ot)
Definition at line 391 of file particle_boids.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and state_move_down_exec().
Referenced by operatortypes_boids().
void BOID_OT_state_move_up (struct wmOperatorType * ot)
Definition at line 355 of file particle_boids.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and state_move_up_exec().
Referenced by operatortypes_boids().
void DPAINT_OT_bake (struct wmOperatorType * ot)
Definition at line 417 of file dynamicpaint_ops.c.
References wmOperatorType::description, dynamicpaint_bake_exec(), ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by operatortypes_dynamicpaint().
void DPAINT_OT_output_toggle (struct wmOperatorType * ot)
Definition at line 243 of file dynamicpaint_ops.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, output_toggle_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), and wmOperatorType::srna.
Referenced by operatortypes_dynamicpaint().
void DPAINT_OT_surface_slot_add (struct wmOperatorType * ot)
Definition at line 85 of file dynamicpaint_ops.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and surface_slot_add_exec().
Referenced by operatortypes_dynamicpaint().
void DPAINT_OT_surface_slot_remove (struct wmOperatorType * ot)
Definition at line 133 of file dynamicpaint_ops.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and surface_slot_remove_exec().
Referenced by operatortypes_dynamicpaint().
void DPAINT_OT_type_toggle (struct wmOperatorType * ot)
Definition at line 179 of file dynamicpaint_ops.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MOD_DYNAMICPAINT_TYPE_CANVAS, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, prop_dynamicpaint_type_items, RNA_def_enum(), wmOperatorType::srna, and type_toggle_exec().
Referenced by operatortypes_dynamicpaint().
void FLUID_OT_bake (struct wmOperatorType * ot)
Referenced by operatortypes_fluid().
void OBJECT_OT_particle_system_add (struct wmOperatorType * ot)
Definition at line 84 of file particle_object.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, particle_system_add_exec(), and wmOperatorType::poll.
Referenced by operatortypes_particle().
void OBJECT_OT_particle_system_remove (struct wmOperatorType * ot)
Definition at line 123 of file particle_object.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, particle_system_remove_exec(), and wmOperatorType::poll.
Referenced by operatortypes_particle().
void PARTICLE_OT_brush_edit (struct wmOperatorType * ot)
Definition at line 3728 of file particle_edit.c.
References brush_edit_cancel(), brush_edit_exec(), brush_edit_invoke(), brush_edit_modal(), wmOperatorType::cancel, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, PE_poll_view3d(), wmOperatorType::poll, RNA_def_collection_runtime(), RNA_OperatorStrokeElement, and wmOperatorType::srna.
Referenced by operatortypes_particle().
void PARTICLE_OT_connect_hair (struct wmOperatorType * ot)
Definition at line 751 of file particle_object.c.
References connect_hair_exec(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by operatortypes_particle().
void PARTICLE_OT_delete (struct wmOperatorType * ot)
Definition at line 2535 of file particle_edit.c.
References DEL_PARTICLE, delete_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PE_hair_poll(), wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by operatortypes_particle().
void PARTICLE_OT_disconnect_hair (struct wmOperatorType * ot)
Definition at line 609 of file particle_object.c.
References wmOperatorType::description, disconnect_hair_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by operatortypes_particle().
void PARTICLE_OT_dupliob_copy (struct wmOperatorType * ot)
Definition at line 436 of file particle_object.c.
References copy_particle_dupliob_exec(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by operatortypes_particle().
void PARTICLE_OT_dupliob_move_down (struct wmOperatorType * ot)
Definition at line 519 of file particle_object.c.
References wmOperatorType::description, dupliob_move_down_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by operatortypes_particle().
void PARTICLE_OT_dupliob_move_up (struct wmOperatorType * ot)
Definition at line 397 of file particle_object.c.
References wmOperatorType::description, dupliob_move_up_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by operatortypes_particle().
void PARTICLE_OT_dupliob_remove (struct wmOperatorType * ot)
Definition at line 479 of file particle_object.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and remove_particle_dupliob_exec().
Referenced by operatortypes_particle().
void PARTICLE_OT_edited_clear (struct wmOperatorType * ot)
Definition at line 4267 of file particle_edit.c.
References clear_edited_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, particle_edit_toggle_poll(), and wmOperatorType::poll.
Referenced by operatortypes_particle().
void PARTICLE_OT_hide (struct wmOperatorType * ot)
Definition at line 1707 of file particle_edit.c.
References wmOperatorType::exec, wmOperatorType::flag, hide_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PE_poll(), wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by operatortypes_particle().
void PARTICLE_OT_mirror (struct wmOperatorType * ot)
Definition at line 2700 of file particle_edit.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, mirror_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PE_hair_poll(), and wmOperatorType::poll.
Referenced by operatortypes_particle().
void PARTICLE_OT_new (struct wmOperatorType * ot)
Definition at line 182 of file particle_object.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, new_particle_settings_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and psys_poll().
Referenced by operatortypes_particle().
void PARTICLE_OT_new_target (struct wmOperatorType * ot)
Definition at line 231 of file particle_object.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, new_particle_target_exec(), OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by operatortypes_particle().
void PARTICLE_OT_particle_edit_toggle (struct wmOperatorType * ot)
Definition at line 4218 of file particle_edit.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, particle_edit_toggle_exec(), particle_edit_toggle_poll(), and wmOperatorType::poll.
Referenced by operatortypes_particle().
void PARTICLE_OT_rekey (struct wmOperatorType * ot)
Definition at line 1964 of file particle_edit.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PE_hair_poll(), wmOperatorType::poll, rekey_exec(), RNA_def_int(), wmOperatorType::srna, and WM_operator_props_popup().
Referenced by operatortypes_particle().
void PARTICLE_OT_remove_doubles (struct wmOperatorType * ot)
Definition at line 2382 of file particle_edit.c.
References wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PE_hair_poll(), wmOperatorType::poll, remove_doubles_exec(), RNA_def_float(), and wmOperatorType::srna.
Referenced by operatortypes_particle().
void PARTICLE_OT_reveal (struct wmOperatorType * ot)
Definition at line 1749 of file particle_edit.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PE_poll(), wmOperatorType::poll, and reveal_exec().
Referenced by operatortypes_particle().
void PARTICLE_OT_select_all (struct wmOperatorType * ot)
Definition at line 1361 of file particle_edit.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PE_poll(), pe_select_all_exec(), wmOperatorType::poll, and WM_operator_properties_select_all().
Referenced by operatortypes_particle().
void PARTICLE_OT_select_less (struct wmOperatorType * ot)
Definition at line 1807 of file particle_edit.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PE_poll(), wmOperatorType::poll, and select_less_exec().
Referenced by operatortypes_particle().
void PARTICLE_OT_select_linked (struct wmOperatorType * ot)
Definition at line 1519 of file particle_edit.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, PE_poll_view3d(), wmOperatorType::poll, RNA_def_boolean(), RNA_def_int_vector(), select_linked_exec(), select_linked_invoke(), and wmOperatorType::srna.
Referenced by operatortypes_particle().
void PARTICLE_OT_select_more (struct wmOperatorType * ot)
Definition at line 1868 of file particle_edit.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PE_poll(), wmOperatorType::poll, and select_more_exec().
Referenced by operatortypes_particle().
void PARTICLE_OT_select_roots (struct wmOperatorType * ot)
Definition at line 1435 of file particle_edit.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PE_poll(), wmOperatorType::poll, and select_roots_exec().
Referenced by operatortypes_particle().
void PARTICLE_OT_select_tips (struct wmOperatorType * ot)
Definition at line 1475 of file particle_edit.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PE_poll(), wmOperatorType::poll, and select_tips_exec().
Referenced by operatortypes_particle().
void PARTICLE_OT_subdivide (struct wmOperatorType * ot)
Definition at line 2294 of file particle_edit.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PE_hair_poll(), wmOperatorType::poll, and subdivide_exec().
Referenced by operatortypes_particle().
void PARTICLE_OT_target_move_down (struct wmOperatorType * ot)
Definition at line 359 of file particle_object.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and target_move_down_exec().
Referenced by operatortypes_particle().
void PARTICLE_OT_target_move_up (struct wmOperatorType * ot)
Definition at line 321 of file particle_object.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and target_move_up_exec().
Referenced by operatortypes_particle().
void PARTICLE_OT_target_remove (struct wmOperatorType * ot)
Definition at line 280 of file particle_object.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and remove_particle_target_exec().
Referenced by operatortypes_particle().
void PARTICLE_OT_weight_set (struct wmOperatorType * ot)
Definition at line 2432 of file particle_edit.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PE_hair_poll(), wmOperatorType::poll, RNA_def_float(), wmOperatorType::srna, and weight_set_exec().
Referenced by operatortypes_particle().
void PTCACHE_OT_add (struct wmOperatorType * ot)
Definition at line 371 of file physics_pointcache.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, ptcache_add_new_exec(), and ptcache_poll().
Referenced by operatortypes_pointcache().
void PTCACHE_OT_bake (struct wmOperatorType * ot)
Definition at line 269 of file physics_pointcache.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, ptcache_bake_exec(), ptcache_poll(), RNA_def_boolean(), and wmOperatorType::srna.
Referenced by operatortypes_pointcache().
void PTCACHE_OT_bake_all (struct wmOperatorType * ot)
Definition at line 155 of file physics_pointcache.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, ptcache_bake_all_exec(), ptcache_bake_all_poll(), RNA_def_boolean(), and wmOperatorType::srna.
Referenced by operatortypes_pointcache().
void PTCACHE_OT_bake_from_cache (struct wmOperatorType * ot)
Definition at line 299 of file physics_pointcache.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, ptcache_bake_from_cache_exec(), and ptcache_poll().
Referenced by operatortypes_pointcache().
void PTCACHE_OT_free_bake (struct wmOperatorType * ot)
Definition at line 285 of file physics_pointcache.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, ptcache_free_bake_exec(), and ptcache_poll().
Referenced by operatortypes_pointcache().
void PTCACHE_OT_free_bake_all (struct wmOperatorType * ot)
Definition at line 171 of file physics_pointcache.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, ptcache_bake_all_poll(), and ptcache_free_bake_all_exec().
Referenced by operatortypes_pointcache().
void PTCACHE_OT_remove (struct wmOperatorType * ot)
Definition at line 385 of file physics_pointcache.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, ptcache_poll(), and ptcache_remove_exec().
Referenced by operatortypes_pointcache().