Blender: ED_keyframes_draw.h File Reference
ED_keyframes_draw.h File Reference
Editors
Classes
struct ActKeyColumn
struct ActKeyBlock
Typedefs
typedef struct ActKeyColumn ActKeyColumn
typedef struct ActKeyBlock ActKeyBlock
typedef enum eKeyframeShapeDrawOpts eKeyframeShapeDrawOpts
Enumerations
enum eKeyframeShapeDrawOpts { KEYFRAME_SHAPE_FRAME = 0, KEYFRAME_SHAPE_INSIDE, KEYFRAME_SHAPE_BOTH }
Functions
void draw_keyframe_shape (float x, float y, float xscale, float hsize, short sel, short key_type, short mode, float alpha)
void draw_fcurve_channel (struct View2D *v2d, struct AnimData *adt, struct FCurve *fcu, float ypos)
void draw_agroup_channel (struct View2D *v2d, struct AnimData *adt, struct bActionGroup *agrp, float ypos)
void draw_action_channel (struct View2D *v2d, struct AnimData *adt, struct bAction *act, float ypos)
void draw_object_channel (struct View2D *v2d, struct bDopeSheet *ads, struct Object *ob, float ypos)
void draw_scene_channel (struct View2D *v2d, struct bDopeSheet *ads, struct Scene *sce, float ypos)
void draw_summary_channel (struct View2D *v2d, struct bAnimContext *ac, float ypos)
void draw_gpl_channel (struct View2D *v2d, struct bDopeSheet *ads, struct bGPDlayer *gpl, float ypos)
void fcurve_to_keylist (struct AnimData *adt, struct FCurve *fcu, struct DLRBT_Tree *keys, struct DLRBT_Tree *blocks)
void agroup_to_keylist (struct AnimData *adt, struct bActionGroup *agrp, struct DLRBT_Tree *keys, struct DLRBT_Tree *blocks)
void action_to_keylist (struct AnimData *adt, struct bAction *act, struct DLRBT_Tree *keys, struct DLRBT_Tree *blocks)
void ob_to_keylist (struct bDopeSheet *ads, struct Object *ob, struct DLRBT_Tree *keys, struct DLRBT_Tree *blocks)
void scene_to_keylist (struct bDopeSheet *ads, struct Scene *sce, struct DLRBT_Tree *keys, struct DLRBT_Tree *blocks)
void summary_to_keylist (struct bAnimContext *ac, struct DLRBT_Tree *keys, struct DLRBT_Tree *blocks)
void gpl_to_keylist (struct bDopeSheet *ads, struct bGPDlayer *gpl, struct DLRBT_Tree *keys)
short compare_ak_cfraPtr (void *node, void *data)
short compare_ab_cfraPtr (void *node, void *data)
short actkeyblock_is_valid (ActKeyBlock *ab, struct DLRBT_Tree *keys)
Detailed Description
Definition in file ED_keyframes_draw.h.
Typedef Documentation
typedef struct ActKeyBlock ActKeyBlock
typedef struct ActKeyColumn ActKeyColumn
typedef enum eKeyframeShapeDrawOpts eKeyframeShapeDrawOpts
Enumeration Type Documentation
enum eKeyframeShapeDrawOpts
Enumerator:
KEYFRAME_SHAPE_FRAME
KEYFRAME_SHAPE_INSIDE
KEYFRAME_SHAPE_BOTH
Definition at line 95 of file ED_keyframes_draw.h.
Function Documentation
void action_to_keylist (struct AnimData * adt, struct bAction * act, struct DLRBT_Tree * keys, struct DLRBT_Tree * blocks)
Definition at line 917 of file keyframes_draw.c.
References bAction::curves, fcurve_to_keylist(), ListBase::first, and FCurve::next.
Referenced by draw_action_channel(), draw_ghost_poses_keys(), draw_motion_path_instance(), mouse_action_keys(), nla_action_draw_keyframes(), and poselib_sanitise_exec().
short actkeyblock_is_valid (ActKeyBlock * ab, struct DLRBT_Tree * keys)
Definition at line 462 of file keyframes_draw.c.
References BLI_dlrbTree_search_exact(), compare_ak_cfraPtr(), ActKeyBlock::end, if(), NULL, ActKeyBlock::start, ActKeyBlock::totcurve, and ActKeyColumn::totcurve.
Referenced by draw_keylist(), and pose_propagate_get_boneHoldEndFrame().
void agroup_to_keylist (struct AnimData * adt, struct bActionGroup * agrp, struct DLRBT_Tree * keys, struct DLRBT_Tree * blocks)
Definition at line 905 of file keyframes_draw.c.
References bActionGroup::channels, fcurve_to_keylist(), ListBase::first, FCurve::grp, and FCurve::next.
Referenced by draw_agroup_channel(), draw_motion_path_instance(), and mouse_action_keys().
short compare_ab_cfraPtr (void * node, void * data)
Definition at line 315 of file keyframes_draw.c.
References data, and ActKeyBlock::start.
Referenced by pose_propagate_get_boneHoldEndFrame().
short compare_ak_cfraPtr (void * node, void * data)
Definition at line 83 of file keyframes_draw.c.
References ActKeyColumn::cfra, and data.
Referenced by actkeyblock_is_valid(), draw_motion_path_instance(), keyframe_jump_exec(), pose_propagate_get_boneHoldEndFrame(), and pose_slide_invoke_common().
void draw_action_channel (struct View2D * v2d, struct AnimData * adt, struct bAction * act, float ypos)
Definition at line 732 of file keyframes_draw.c.
References action_to_keylist(), BLI_dlrbTree_free(), BLI_dlrbTree_init(), BLI_dlrbTree_linkedlist_sync(), and draw_keylist().
Referenced by draw_channel_strips().
void draw_agroup_channel (struct View2D * v2d, struct AnimData * adt, struct bActionGroup * agrp, float ypos)
Definition at line 714 of file keyframes_draw.c.
References agroup_to_keylist(), AGRP_PROTECTED, BLI_dlrbTree_free(), BLI_dlrbTree_init(), BLI_dlrbTree_linkedlist_sync(), draw_keylist(), and bActionGroup::flag.
Referenced by draw_channel_strips().
void draw_fcurve_channel (struct View2D * v2d, struct AnimData * adt, struct FCurve * fcu, float ypos)
Definition at line 696 of file keyframes_draw.c.
References BLI_dlrbTree_free(), BLI_dlrbTree_init(), BLI_dlrbTree_linkedlist_sync(), draw_keylist(), FCURVE_PROTECTED, fcurve_to_keylist(), and FCurve::flag.
Referenced by draw_channel_strips().
void draw_gpl_channel (struct View2D * v2d, struct bDopeSheet * ads, struct bGPDlayer * gpl, float ypos)
Definition at line 750 of file keyframes_draw.c.
References BLI_dlrbTree_free(), BLI_dlrbTree_init(), BLI_dlrbTree_linkedlist_sync(), draw_keylist(), bGPDlayer::flag, GP_LAYER_LOCKED, gpl_to_keylist(), and NULL.
Referenced by draw_channel_strips().
void draw_keyframe_shape (float x, float y, float xscale, float hsize, short sel, short key_type, short mode, float alpha)
Definition at line 497 of file keyframes_draw.c.
References _unit_diamond_shape, BEZT_KEYTYPE_BREAKDOWN, BEZT_KEYTYPE_EXTREME, BEZT_KEYTYPE_JITTER, BEZT_KEYTYPE_KEYFRAME, ELEM, KEYFRAME_SHAPE_BOTH, KEYFRAME_SHAPE_FRAME, KEYFRAME_SHAPE_INSIDE, TH_STRIP_SELECT, and UI_ThemeColorShadeAlpha().
Referenced by draw_keylist(), and nla_action_draw_keyframes().
void draw_object_channel (struct View2D * v2d, struct bDopeSheet * ads, struct Object * ob, float ypos)
Definition at line 678 of file keyframes_draw.c.
References BLI_dlrbTree_free(), BLI_dlrbTree_init(), BLI_dlrbTree_linkedlist_sync(), draw_keylist(), and ob_to_keylist().
Referenced by draw_channel_strips().
void draw_scene_channel (struct View2D * v2d, struct bDopeSheet * ads, struct Scene * sce, float ypos)
Definition at line 660 of file keyframes_draw.c.
References BLI_dlrbTree_free(), BLI_dlrbTree_init(), BLI_dlrbTree_linkedlist_sync(), draw_keylist(), and scene_to_keylist().
Referenced by draw_channel_strips().
void draw_summary_channel (struct View2D * v2d, struct bAnimContext * ac, float ypos)
Definition at line 642 of file keyframes_draw.c.
References BLI_dlrbTree_free(), BLI_dlrbTree_init(), BLI_dlrbTree_linkedlist_sync(), draw_keylist(), and summary_to_keylist().
Referenced by draw_channel_strips().
void fcurve_to_keylist (struct AnimData * adt, struct FCurve * fcu, struct DLRBT_Tree * keys, struct DLRBT_Tree * blocks)
Definition at line 855 of file keyframes_draw.c.
References add_bezt_to_keyblocks_list(), add_bezt_to_keycolumns_list(), ANIM_nla_mapping_apply_fcurve(), FCurve::bezt, BLI_dlrbTree_add(), BLI_dlrbTree_free(), BLI_dlrbTree_linkedlist_sync(), BLI_dlrbTree_new(), compare_abk_bezt(), MEM_freeN(), nalloc_abk_bezt(), NULL, nupdate_abk_bezt(), DLRBT_Tree::root, set_touched_actkeyblock(), set_touched_actkeycolumn(), and FCurve::totvert.
Referenced by action_to_keylist(), agroup_to_keylist(), draw_fcurve_channel(), mouse_action_keys(), ob_to_keylist(), pose_propagate_get_boneHoldEndFrame(), pose_slide_invoke_common(), scene_to_keylist(), and summary_to_keylist().
void gpl_to_keylist (struct bDopeSheet * ads, struct bGPDlayer * gpl, struct DLRBT_Tree * keys)
void ob_to_keylist (struct bDopeSheet * ads, struct Object * ob, struct DLRBT_Tree * keys, struct DLRBT_Tree * blocks)
Definition at line 819 of file keyframes_draw.c.
References bAnimContext::ads, Object::adt, bAnimListElem::adt, ANIM_animdata_filter(), ANIMCONT_CHANNEL, ANIMFILTER_DATA_VISIBLE, ANIMTYPE_OBJECT, BLI_freelistN(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, fcurve_to_keylist(), filter(), ListBase::first, Object::id, bAnimListElem::id, bAnimListElem::next, NULL, Base::object, and bAnimListElem::type.
Referenced by draw_object_channel(), keyframe_jump_exec(), mouse_action_keys(), and time_draw_idblock_keyframes().
void scene_to_keylist (struct bDopeSheet * ads, struct Scene * sce, struct DLRBT_Tree * keys, struct DLRBT_Tree * blocks)
Definition at line 786 of file keyframes_draw.c.
References bAnimContext::ads, Scene::adt, bAnimListElem::adt, ANIM_animdata_filter(), ANIMCONT_CHANNEL, ANIMFILTER_DATA_VISIBLE, ANIMTYPE_SCENE, BLI_freelistN(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, fcurve_to_keylist(), filter(), ListBase::first, Scene::id, bAnimListElem::id, bAnimListElem::next, NULL, and bAnimListElem::type.
Referenced by draw_scene_channel(), keyframe_jump_exec(), mouse_action_keys(), and time_draw_idblock_keyframes().
void summary_to_keylist (struct bAnimContext * ac, struct DLRBT_Tree * keys, struct DLRBT_Tree * blocks)
Definition at line 767 of file keyframes_draw.c.
References bAnimListElem::adt, ANIM_animdata_filter(), ANIMFILTER_DATA_VISIBLE, BLI_freelistN(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, fcurve_to_keylist(), filter(), ListBase::first, bAnimListElem::next, and NULL.
Referenced by draw_summary_channel(), and mouse_action_keys().