Blender: LocalSupportVertexCallback Class Reference
LocalSupportVertexCallback Class Reference
Public Member Functions
LocalSupportVertexCallback (const btVector3 &supportVecLocal)
virtual void internalProcessTriangleIndex (btVector3 *triangle, int partId, int triangleIndex)
btVector3 GetSupportVertexLocal ()
Public Attributes
btScalar m_maxDot
btVector3 m_supportVecLocal
Detailed Description
It's not nice to have all this virtual function overhead, so perhaps we can also gather the points once but then we are duplicating
Definition at line 36 of file btConvexTriangleMeshShape.cpp.
Constructor & Destructor Documentation
LocalSupportVertexCallback::LocalSupportVertexCallback (const btVector3 & supportVecLocal) [inline]
Definition at line 45 of file btConvexTriangleMeshShape.cpp.
Member Function Documentation
btVector3 LocalSupportVertexCallback::GetSupportVertexLocal () [inline]
Definition at line 68 of file btConvexTriangleMeshShape.cpp.
Referenced by btConvexTriangleMeshShape::batchedUnitVectorGetSupportingVertexWithoutMargin(), and btConvexTriangleMeshShape::localGetSupportingVertexWithoutMargin().
virtual void LocalSupportVertexCallback::internalProcessTriangleIndex (btVector3 * triangle, int partId, int triangleIndex) [inline, virtual]
Implements btInternalTriangleIndexCallback.
Definition at line 52 of file btConvexTriangleMeshShape.cpp.
References dot(), i, m_maxDot, and m_supportVecLocal.
Member Data Documentation
btScalar LocalSupportVertexCallback::m_maxDot
Definition at line 42 of file btConvexTriangleMeshShape.cpp.
Referenced by internalProcessTriangleIndex().
btVector3 LocalSupportVertexCallback::m_supportVecLocal
Definition at line 43 of file btConvexTriangleMeshShape.cpp.
Referenced by internalProcessTriangleIndex().
The documentation for this class was generated from the following file:
btConvexTriangleMeshShape.cpp