Blender: BLI_callbacks.h File Reference
BLI_callbacks.h File Reference
blenlib
Classes
struct bCallbackFuncStore
Enumerations
enum eCbEvent {
BLI_CB_EVT_FRAME_CHANGE_PRE, BLI_CB_EVT_FRAME_CHANGE_POST, BLI_CB_EVT_RENDER_PRE, BLI_CB_EVT_RENDER_POST,
BLI_CB_EVT_RENDER_STATS, BLI_CB_EVT_RENDER_COMPLETE, BLI_CB_EVT_RENDER_CANCEL, BLI_CB_EVT_LOAD_PRE,
BLI_CB_EVT_LOAD_POST, BLI_CB_EVT_SAVE_PRE, BLI_CB_EVT_SAVE_POST, BLI_CB_EVT_SCENE_UPDATE_PRE,
BLI_CB_EVT_SCENE_UPDATE_POST, BLI_CB_EVT_TOT
}
Functions
void BLI_exec_cb (struct Main *main, struct ID *self, eCbEvent evt)
void BLI_add_cb (bCallbackFuncStore *funcstore, eCbEvent evt)
void BLI_cb_init (void)
void BLI_cb_finalize (void)
void callLocalErrorCallBack (const char *msg)
Detailed Description
Definition in file BLI_callbacks.h.
Enumeration Type Documentation
enum eCbEvent
Enumerator:
BLI_CB_EVT_FRAME_CHANGE_PRE
BLI_CB_EVT_FRAME_CHANGE_POST
BLI_CB_EVT_RENDER_PRE
BLI_CB_EVT_RENDER_POST
BLI_CB_EVT_RENDER_STATS
BLI_CB_EVT_RENDER_COMPLETE
BLI_CB_EVT_RENDER_CANCEL
BLI_CB_EVT_LOAD_PRE
BLI_CB_EVT_LOAD_POST
BLI_CB_EVT_SAVE_PRE
BLI_CB_EVT_SAVE_POST
BLI_CB_EVT_SCENE_UPDATE_PRE
BLI_CB_EVT_SCENE_UPDATE_POST
BLI_CB_EVT_TOT
Definition at line 39 of file BLI_callbacks.h.
Function Documentation
void BLI_add_cb (bCallbackFuncStore * funcstore, eCbEvent evt)
Definition at line 41 of file callbacks.c.
References BLI_addtail().
Referenced by BPY_app_handlers_struct().
void BLI_cb_finalize (void)
Definition at line 53 of file callbacks.c.
References bCallbackFuncStore::alloc, BLI_CB_EVT_TOT, BLI_remlink(), ListBase::first, MEM_freeN(), and bCallbackFuncStore::next.
Referenced by free_blender().
void BLI_cb_init (void)
Definition at line 47 of file callbacks.c.
Referenced by main().
void BLI_exec_cb (struct Main * main, struct ID * self, eCbEvent evt)
Definition at line 31 of file callbacks.c.
References bCallbackFuncStore::arg, ListBase::first, bCallbackFuncStore::func, and bCallbackFuncStore::next.
Referenced by do_write_image_or_movie(), RE_BlenderAnim(), RE_BlenderFrame(), scene_update_for_newframe(), scene_update_tagged(), stats_background(), WM_read_file(), and WM_write_file().
void callLocalErrorCallBack (const char * msg)
Definition at line 61 of file scanfill.c.
References BLI_localErrorCallBack.
Referenced by BLI_edgefill_ex().