Blender: KX_LightIpoSGController Class Reference
KX_LightIpoSGController Class Reference
#include <KX_LightIpoSGController.h>
Public Member Functions
KX_LightIpoSGController ()
virtual ~KX_LightIpoSGController ()
virtual SG_Controller * GetReplica (class SG_Node *destnode)
virtual bool Update (double time)
virtual void SetSimulatedTime (double time)
void SetModifyEnergy (bool modify)
void SetModifyColor (bool modify)
void SetModifyDist (bool modify)
void SetOption (int option, int value)
void AddInterpolator (KX_IInterpolator *interp)
Public Attributes
MT_Scalar m_energy
MT_Scalar m_col_rgb [3]
MT_Scalar m_dist
Detailed Description
Definition at line 42 of file KX_LightIpoSGController.h.
Constructor & Destructor Documentation
KX_LightIpoSGController::KX_LightIpoSGController () [inline]
Definition at line 58 of file KX_LightIpoSGController.h.
Referenced by GetReplica().
KX_LightIpoSGController::~KX_LightIpoSGController () [virtual]
Definition at line 114 of file KX_LightIpoSGController.cpp.
References i.
Member Function Documentation
void KX_LightIpoSGController::AddInterpolator (KX_IInterpolator * interp)
Definition at line 80 of file KX_LightIpoSGController.cpp.
Referenced by BL_CreateLampIPO(), and GetReplica().
SG_Controller * KX_LightIpoSGController::GetReplica (class SG_Node * destnode) [virtual]
Implements SG_Controller.
Definition at line 85 of file KX_LightIpoSGController.cpp.
References AddInterpolator(), SG_Controller::ClearObject(), i, KX_LightIpoSGController(), and KX_ScalarInterpolator::SetNewTarget().
void KX_LightIpoSGController::SetModifyColor (bool modify) [inline]
Definition at line 81 of file KX_LightIpoSGController.h.
Referenced by BL_CreateLampIPO().
void KX_LightIpoSGController::SetModifyDist (bool modify) [inline]
Definition at line 85 of file KX_LightIpoSGController.h.
Referenced by BL_CreateLampIPO().
void KX_LightIpoSGController::SetModifyEnergy (bool modify) [inline]
Definition at line 77 of file KX_LightIpoSGController.h.
Referenced by BL_CreateLampIPO().
void KX_LightIpoSGController::SetOption (int option, int value) [inline, virtual]
Hacky way of passing options to specific controllers
Parameters:
option An integer identifying the option.
value The value of this option.
Attention:
This has been placed here to give sca-elements
some control over the controllers. This is
necessary because the identity of the controller
is lost on the way here.
Implements SG_Controller.
Definition at line 90 of file KX_LightIpoSGController.h.
virtual void KX_LightIpoSGController::SetSimulatedTime (double time) [inline, virtual]
Implements SG_Controller.
Definition at line 72 of file KX_LightIpoSGController.h.
bool KX_LightIpoSGController::Update (double time) [virtual]
Implements SG_Controller.
Definition at line 44 of file KX_LightIpoSGController.cpp.
References KX_LightObject::GetLightData(), SG_IObject::GetSGClientObject(), i, RAS_LightObject::m_blue, m_col_rgb, m_dist, RAS_LightObject::m_distance, m_energy, RAS_LightObject::m_energy, RAS_LightObject::m_green, SG_Controller::m_pObject, RAS_LightObject::m_red, and GPULamp::ob.
Member Data Documentation
MT_Scalar KX_LightIpoSGController::m_col_rgb[3]
Definition at line 46 of file KX_LightIpoSGController.h.
Referenced by BL_CreateLampIPO(), and Update().
MT_Scalar KX_LightIpoSGController::m_dist
Definition at line 47 of file KX_LightIpoSGController.h.
Referenced by BL_CreateLampIPO(), and Update().
MT_Scalar KX_LightIpoSGController::m_energy
Definition at line 45 of file KX_LightIpoSGController.h.
Referenced by BL_CreateLampIPO(), and Update().
The documentation for this class was generated from the following files:
KX_LightIpoSGController.h
KX_LightIpoSGController.cpp