Blender: rna_meta.c File Reference
rna_meta.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_mesh_types.h"
#include "DNA_meta_types.h"
Functions
static void rna_def_metaelement (BlenderRNA *brna)
static void rna_def_metaball_elements (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_metaball (BlenderRNA *brna)
void RNA_def_meta (BlenderRNA *brna)
Detailed Description
Definition in file rna_meta.c.
Function Documentation
void RNA_def_meta (BlenderRNA * brna)
Definition at line 355 of file rna_meta.c.
References rna_def_metaball(), and rna_def_metaelement().
static void rna_def_metaball (BlenderRNA * brna) [static]
Definition at line 267 of file rna_meta.c.
References MB_AUTOSPACE, MB_UPDATE_ALWAYS, MB_UPDATE_FAST, MB_UPDATE_HALFRES, MB_UPDATE_NEVER, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_DISTANCE, PROP_ENUM, PROP_EULER, PROP_FLOAT, PROP_NONE, PROP_TRANSLATION, PROP_XYZ, rna_def_animdata_common(), rna_def_metaball_elements(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_editable_func(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_meta().
static void rna_def_metaball_elements (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 234 of file rna_meta.c.
References FUNC_USE_REPORTS, MB_BALL, metaelem_type_items, NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REQUIRED, RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_srna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_metaball().
static void rna_def_metaelement (BlenderRNA * brna) [static]
Definition at line 163 of file rna_meta.c.
References FLT_MAX, MB_HIDE, MB_NEGATIVE, metaelem_type_items, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_QUATERNION, PROP_TRANSLATION, PROP_UNIT_LENGTH, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_meta().