Blender: MyGlutKeyHandler Class Reference
MyGlutKeyHandler Class Reference
#include <MyGlutKeyHandler.h>
Public Member Functions
void HandleKeyboard (GHOST_TKey key, int x, int y)
~MyGlutKeyHandler ()
void HandleKeyboard (unsigned char key, int x, int y)
~MyGlutKeyHandler ()
Static Public Member Functions
static MyGlutKeyHandler * New (LOD_Decimation_InfoPtr info)
static MyGlutKeyHandler * New ()
Detailed Description
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) 2001-2002 by NaN Holding BV. All rights reserved.
The Original Code is: all of this file.
Contributor(s): none yet.
***** END GPL LICENSE BLOCK *****
Definition at line 34 of file decimation/test/decimate_glut_test/intern/MyGlutKeyHandler.h.
Constructor & Destructor Documentation
MyGlutKeyHandler::~MyGlutKeyHandler () [inline]
Definition at line 70 of file decimation/test/decimate_glut_test/intern/MyGlutKeyHandler.h.
MyGlutKeyHandler::~MyGlutKeyHandler () [inline]
Definition at line 65 of file iksolver/test/ik_glut_test/intern/MyGlutKeyHandler.h.
Member Function Documentation
void MyGlutKeyHandler::HandleKeyboard (GHOST_TKey key, int x, int y) [inline, virtual]
Implements GlutKeyboardHandler.
Definition at line 46 of file decimation/test/decimate_glut_test/intern/MyGlutKeyHandler.h.
References GHOST_kKeyD, GHOST_kKeyEsc, and LOD_CollapseEdge().
void MyGlutKeyHandler::HandleKeyboard (unsigned char key, int x, int y) [inline, virtual]
Implements GlutKeyboardHandler.
Definition at line 51 of file iksolver/test/ik_glut_test/intern/MyGlutKeyHandler.h.
static MyGlutKeyHandler* MyGlutKeyHandler::New () [inline, static]
Definition at line 38 of file iksolver/test/ik_glut_test/intern/MyGlutKeyHandler.h.
References NULL, and MEM_SmartPtr< T >::Release().
Referenced by main().
static MyGlutKeyHandler* MyGlutKeyHandler::New (LOD_Decimation_InfoPtr info) [inline, static]
Definition at line 39 of file decimation/test/decimate_glut_test/intern/MyGlutKeyHandler.h.
The documentation for this class was generated from the following files:
decimation/test/decimate_glut_test/intern/MyGlutKeyHandler.h
iksolver/test/ik_glut_test/intern/MyGlutKeyHandler.h