Blender: bmesh_construct.h File Reference
bmesh_construct.h File Reference
BMesh
Functions
BMFace * BM_face_create_quad_tri_v (BMesh *bm, BMVert **verts, int len, const BMFace *example, const int nodouble)
BMFace * BM_face_create_quad_tri (BMesh *bm, BMVert *v1, BMVert *v2, BMVert *v3, BMVert *v4, const BMFace *example, const int nodouble)
Make Quad/Triangle.
void BM_face_copy_shared (BMesh *bm, BMFace *f)
copies face loop data from shared adjacent faces.
BMFace * BM_face_create_ngon (BMesh *bm, BMVert *v1, BMVert *v2, BMEdge **edges, int len, int nodouble)
Make NGon.
BMFace * BM_face_create_ngon_vcloud (BMesh *bm, BMVert **vert_arr, int len, int nodouble)
void BMO_remove_tagged_faces (BMesh *bm, const short oflag)
void BMO_remove_tagged_edges (BMesh *bm, const short oflag)
void BMO_remove_tagged_verts (BMesh *bm, const short oflag)
void BMO_remove_tagged_context (BMesh *bm, const short oflag, const int type)
void BM_elem_attrs_copy (BMesh *source_mesh, BMesh *target_mesh, const void *source, void *target)
BMesh * BM_mesh_copy (BMesh *bm_old)
char BM_face_flag_from_mflag (const char mflag)
char BM_edge_flag_from_mflag (const short mflag)
char BM_vert_flag_from_mflag (const char mflag)
char BM_face_flag_to_mflag (BMFace *f)
short BM_edge_flag_to_mflag (BMEdge *e)
char BM_vert_flag_to_mflag (BMVert *v)
Detailed Description
Definition in file bmesh_construct.h.
Function Documentation
char BM_edge_flag_from_mflag (const short mflag)
Definition at line 959 of file bmesh_construct.c.
References BM_ELEM_HIDDEN, BM_ELEM_SEAM, BM_ELEM_SELECT, BM_ELEM_SMOOTH, ME_HIDE, ME_SEAM, ME_SHARP, and SELECT.
Referenced by BM_mesh_bm_from_me(), and DM_to_bmesh_ex().
short BM_edge_flag_to_mflag (BMEdge * e)
Definition at line 984 of file bmesh_construct.c.
References BM_edge_is_wire(), BM_ELEM_HIDDEN, BM_ELEM_SEAM, BM_ELEM_SELECT, BM_ELEM_SMOOTH, BMEdge::head, BMHeader::hflag, ME_EDGEDRAW, ME_EDGERENDER, ME_HIDE, ME_LOOSEEDGE, ME_SEAM, ME_SHARP, and SELECT.
Referenced by BM_mesh_bm_to_me(), CDDM_from_BMEditMesh(), emDM_copyEdgeArray(), and emDM_getEdge().
void BM_elem_attrs_copy (BMesh * source_mesh, BMesh * target_mesh, const void * source, void * target)
Copies attributes, e.g. customdata, header flags, etc, from one element to another of the same type.
Definition at line 764 of file bmesh_construct.c.
References BLI_assert, BM_EDGE, bm_edge_attrs_copy(), BM_elem_flag_test, BM_ELEM_SELECT, BM_elem_select_set(), BM_FACE, bm_face_attrs_copy(), BM_LOOP, bm_loop_attrs_copy(), BM_VERT, bm_vert_attrs_copy(), BMHeader::hflag, BMHeader::htype, and TRUE.
Referenced by BM_edge_create(), BM_edge_split(), bm_extrude_copy_face_loop_attributes(), BM_face_copy(), BM_face_create_quad_tri_v(), BM_face_interp_from_face(), BM_face_split(), BM_face_split_n(), BM_faces_join(), BM_loop_interp_from_face(), BM_mesh_copy(), BM_vert_create(), bmo_bevel_exec(), bmo_bridge_loops_exec(), bmo_extrude_face_indiv_exec(), bmo_weldverts_exec(), bpy_bm_elem_copy_from(), bpy_bmedgeseq_new(), bpy_bmfaceseq_new(), bpy_bmvertseq_new(), copy_edge(), copy_face(), copy_vertex(), and projectSVData().
void BM_face_copy_shared (BMesh * bm, BMFace * f)
copies face loop data from shared adjacent faces.
Note:
when a matching edge is found, both loops of that edge are copied this is done since the face may not be completely surrounded by faces, this way: a quad with 2 connected quads on either side will still get all 4 loops updated
Definition at line 133 of file bmesh_construct.c.
References BM_FACE_FIRST_LOOP, bm_loop_attrs_copy(), BMLoop::next, BMLoop::radial_next, and BMLoop::v.
Referenced by bmo_inset_exec().
BMFace* BM_face_create_ngon (BMesh * bm, BMVert * v1, BMVert * v2, BMEdge ** edges, int len, int nodouble)
Make NGon.
Makes an ngon from an unordered list of edges. v1 and v2 must be the verts defining edges[0], and define the winding of the new face.
edges are not required to be ordered, simply to to form a single closed loop as a whole.
Note:
While this function will work fine when the edges are already sorted, if the edges are always going to be sorted, BM_face_create should be considered over this function as it avoids some unnecessary work.
Definition at line 174 of file bmesh_construct.c.
References _FLAG_MF, BLI_array_append, BLI_array_count, BLI_array_free, BLI_array_staticdeclare, BM_edge_exists(), BM_edge_other_vert(), BM_ELEM_API_FLAG_DISABLE, BM_ELEM_API_FLAG_ENABLE, BM_ELEM_API_FLAG_TEST, BM_face_create(), BM_NGON_STACK_SIZE, BM_vert_in_edge(), bmesh_disk_edge_next(), err, FALSE, i, len(), NULL, SWAP, TRUE, BMEdge::v1, and BMEdge::v2.
Referenced by BM_face_create_ngon_vcloud(), BM_faces_join(), BM_mesh_copy(), bmo_bevel_exec(), bmo_edgenet_fill_exec(), bmo_extrude_face_indiv_exec(), bmo_weldverts_exec(), DM_to_bmesh_ex(), and rotsys_fill_faces().
BMFace* BM_face_create_ngon_vcloud (BMesh * bm, BMVert ** vert_arr, int totv, int nodouble)
Makes an NGon from an un-ordered set of verts
assumes...
that verts are only once in the list.
that the verts have roughly planer bounds
that the verts are roughly circular there can be concave areas but overlapping folds from the center point will fail.
a brief explanation of the method used
find the center point
find the normal of the vcloud
order the verts around the face based on their angle to the normal vector at the center point.
Note:
Since this is a vcloud there is no direction.
Definition at line 326 of file bmesh_construct.c.
References angle(), AngleIndexPair::angle, angle_index_pair_cmp(), angle_v3v3(), BM_edge_create(), BM_edge_ordered_verts(), BM_face_create_ngon(), co, BMVert::co, cross_v3_v3v3(), dot_v3v3(), fabsf, far, i, AngleIndexPair::index, len_squared_v3v3(), len_v3(), madd_v3_v3fl(), MEM_freeN(), MEM_mallocN(), normalize_v3(), NULL, project_v3_v3v3(), sub_v3_v3(), sub_v3_v3v3(), TRUE, and zero_v3().
Referenced by bmo_contextual_create_exec().
BMFace* BM_face_create_quad_tri (BMesh * bm, BMVert * v1, BMVert * v2, BMVert * v3, BMVert * v4, const BMFace * example, const int nodouble)
Make Quad/Triangle.
Creates a new quad or triangle from a list of 3 or 4 vertices. If nodouble is TRUE, then a check is done to see if a face with these vertices already exists and returns it instead.
If a pointer to an example face is provided, it's custom data and properties will be copied to the new face.
Note:
The winding of the face is determined by the order of the vertices in the vertex array.
Definition at line 66 of file bmesh_construct.c.
References BM_face_create_quad_tri_v().
Referenced by bmo_bevel_exec(), bmo_bridge_loops_exec(), bmo_create_circle_exec(), bmo_create_cone_exec(), bmo_create_cube_exec(), bmo_create_icosphere_exec(), bmo_create_monkey_exec(), bmo_extrude_edge_only_exec(), bmo_extrude_face_indiv_exec(), bmo_triangle_fill_exec(), and createRepresentation().
BMFace* BM_face_create_quad_tri_v (BMesh * bm, BMVert ** verts, int len, const BMFace * example, const int nodouble)
Definition at line 74 of file bmesh_construct.c.
References BLI_assert, BM_edge_create(), BM_elem_attrs_copy(), BM_face_create(), BM_face_exists(), FALSE, NULL, and TRUE.
Referenced by BM_face_create_quad_tri(), bmo_extrude_face_region_exec(), and bmo_inset_exec().
char BM_face_flag_from_mflag (const char mflag)
Definition at line 967 of file bmesh_construct.c.
References BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ELEM_SMOOTH, ME_FACE_SEL, ME_HIDE, and ME_SMOOTH.
Referenced by BM_mesh_bm_from_me(), and DM_to_bmesh_ex().
char BM_face_flag_to_mflag (BMFace * f)
Definition at line 996 of file bmesh_construct.c.
References BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ELEM_SMOOTH, BMFace::head, BMHeader::hflag, ME_FACE_SEL, ME_HIDE, and ME_SMOOTH.
Referenced by BM_mesh_bm_to_me(), CDDM_from_BMEditMesh(), emDM_copyPolyArray(), emDM_copyTessFaceArray(), and emDM_getTessFace().
BMesh* BM_mesh_copy (BMesh * bm_old)
Definition at line 801 of file bmesh_construct.c.
References BMesh::act_face, BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BLI_assert, BM_EDGE, BM_edge_create(), BM_EDGES_OF_MESH, BM_elem_attrs_copy(), BM_elem_index_get, BM_elem_index_set, BM_FACE, BM_face_create_ngon(), BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_LOOP, BM_LOOPS_OF_FACE, BM_mesh_create(), BM_select_history_store, BM_VERT, BM_vert_create(), BM_VERTS_OF_MESH, bmesh_verts_in_edge(), CD_CALLOC, CD_MASK_BMESH, BMVert::co, copy_v3_v3(), CustomData_bmesh_init_pool(), CustomData_copy(), BMesh::edata, BMEditSelection::ele, BMesh::elem_index_dirty, FALSE, ListBase::first, BMEditSelection::htype, i, BMesh::ldata, BMFace::len, MEM_freeN(), MEM_mallocN(), BMEditSelection::next, BMFace::no, NULL, BMesh::pdata, BMesh::selected, BMesh::totedge, BMAllocTemplate::totedge, BMesh::totface, BMAllocTemplate::totface, BMesh::totloop, BMAllocTemplate::totloop, BMAllocTemplate::totvert, BMesh::totvert, BMEdge::v1, BMEdge::v2, and BMesh::vdata.
Referenced by BMEdit_Copy(), and bpy_bmesh_copy().
char BM_vert_flag_from_mflag (const char mflag)
Definition at line 953 of file bmesh_construct.c.
References BM_ELEM_HIDDEN, BM_ELEM_SELECT, ME_HIDE, and SELECT.
Referenced by BM_mesh_bm_from_me(), and DM_to_bmesh_ex().
char BM_vert_flag_to_mflag (BMVert * v)
Definition at line 976 of file bmesh_construct.c.
References BM_ELEM_HIDDEN, BM_ELEM_SELECT, BMVert::head, BMHeader::hflag, ME_HIDE, and SELECT.
Referenced by BM_mesh_bm_to_me(), bmvert_to_mvert(), CDDM_from_BMEditMesh(), and emDM_copyVertArray().
void BMO_remove_tagged_context (BMesh * bm, const short oflag, const int type)
Warning:
oflag applies to different types in some contexts, not just the type being removed.
take care, uses operator flag DEL_WIREVERT
Definition at line 593 of file bmesh_construct.c.
References BM_EDGES_OF_FACE, BM_EDGES_OF_MESH, BM_FACES_OF_MESH, BM_ITER_MESH, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_FACE, BM_VERTS_OF_MESH, BMO_elem_flag_disable, BMO_elem_flag_enable, BMO_elem_flag_test, bmo_remove_tagged_context_edges(), bmo_remove_tagged_context_verts(), BMO_remove_tagged_edges(), BMO_remove_tagged_faces(), BMO_remove_tagged_verts(), DEL_ALL, DEL_EDGES, DEL_EDGESFACES, DEL_FACES, DEL_ONLYFACES, DEL_ONLYTAGGED, DEL_VERTS, DEL_WIREVERT, BMVert::e, BMEdge::v1, and BMEdge::v2.
Referenced by bmo_del_exec().
void BMO_remove_tagged_edges (BMesh * bm, const short oflag)
Definition at line 505 of file bmesh_construct.c.
References BM_edge_kill(), BM_EDGES_OF_MESH, BM_ITER_MESH, and BMO_elem_flag_test.
Referenced by BMO_remove_tagged_context(), bmo_remove_tagged_context_edges(), and bmo_remove_tagged_context_verts().
void BMO_remove_tagged_faces (BMesh * bm, const short oflag)
Called by operators to remove elements that they have marked for removal.
Definition at line 493 of file bmesh_construct.c.
References BM_face_kill(), BM_FACES_OF_MESH, BM_ITER_MESH, and BMO_elem_flag_test.
Referenced by BMO_remove_tagged_context(), bmo_remove_tagged_context_edges(), and bmo_remove_tagged_context_verts().
void BMO_remove_tagged_verts (BMesh * bm, const short oflag)
Definition at line 517 of file bmesh_construct.c.
References BM_ITER_MESH, BM_vert_kill(), BM_VERTS_OF_MESH, and BMO_elem_flag_test.
Referenced by BMO_remove_tagged_context(), and bmo_remove_tagged_context_verts().