Blender: MT_Matrix3x3.h File Reference
MT_Matrix3x3.h File Reference
moto
#include <MT_assert.h>
#include "MT_Vector3.h"
#include "MT_Quaternion.h"
Classes
class MT_Matrix3x3
Functions
MT_Vector3 operator* (const MT_Matrix3x3 &m, const MT_Vector3 &v)
MT_Vector3 operator* (const MT_Vector3 &v, const MT_Matrix3x3 &m)
MT_Matrix3x3 operator* (const MT_Matrix3x3 &m1, const MT_Matrix3x3 &m2)
MT_Matrix3x3 MT_multTransposeLeft (const MT_Matrix3x3 &m1, const MT_Matrix3x3 &m2)
MT_Matrix3x3 MT_multTransposeRight (const MT_Matrix3x3 &m1, const MT_Matrix3x3 &m2)
MT_OStream & operator<< (MT_OStream &os, const MT_Matrix3x3 &m)
Detailed Description
Definition in file MT_Matrix3x3.h.
Function Documentation
MT_Matrix3x3 MT_multTransposeLeft (const MT_Matrix3x3 & m1, const MT_Matrix3x3 & m2)
Definition at line 109 of file MT_Matrix3x3.inl.
Referenced by MT_Transform::multInverseLeft().
MT_Matrix3x3 MT_multTransposeRight (const MT_Matrix3x3 & m1, const MT_Matrix3x3 & m2)
Definition at line 122 of file MT_Matrix3x3.inl.
References dot().
MT_Vector3 operator* (const MT_Matrix3x3 & m, const MT_Vector3 & v)
Definition at line 94 of file MT_Matrix3x3.inl.
References MT_dot().
MT_Vector3 operator* (const MT_Vector3 & v, const MT_Matrix3x3 & m)
Definition at line 98 of file MT_Matrix3x3.inl.
References MT_Matrix3x3::tdot().
MT_Matrix3x3 operator* (const MT_Matrix3x3 & m1, const MT_Matrix3x3 & m2)
Definition at line 102 of file MT_Matrix3x3.inl.
References MT_Matrix3x3::tdot().
MT_OStream& operator<< (MT_OStream & os, const MT_Matrix3x3 & m) [inline]
Definition at line 260 of file MT_Matrix3x3.h.
References GEN_endl().