Blender: KX_ParentActuator Class Reference
KX_ParentActuator Class Reference
#include <KX_ParentActuator.h>
Public Types
enum KX_PARENTACT_MODE { KX_PARENT_NODEF = 0, KX_PARENT_SET, KX_PARENT_REMOVE, KX_PARENT_MAX }
Public Member Functions
KX_ParentActuator (class SCA_IObject *gameobj, int mode, bool addToCompound, bool ghost, SCA_IObject *ob)
virtual ~KX_ParentActuator ()
virtual bool Update ()
virtual CValue * GetReplica ()
virtual void ProcessReplica ()
virtual void Relink (CTR_Map< CTR_HashedPtr, void * > *obj_map)
virtual bool UnlinkObject (SCA_IObject *clientobj)
Detailed Description
Definition at line 39 of file KX_ParentActuator.h.
Member Enumeration Documentation
enum KX_ParentActuator::KX_PARENTACT_MODE
Enumerator:
KX_PARENT_NODEF
KX_PARENT_SET
KX_PARENT_REMOVE
KX_PARENT_MAX
Definition at line 55 of file KX_ParentActuator.h.
Constructor & Destructor Documentation
KX_ParentActuator::KX_ParentActuator (class SCA_IObject * gameobj, int mode, bool addToCompound, bool ghost, SCA_IObject * ob)
Definition at line 46 of file KX_ParentActuator.cpp.
References SCA_IObject::RegisterActuator().
Referenced by GetReplica().
KX_ParentActuator::~KX_ParentActuator () [virtual]
Definition at line 63 of file KX_ParentActuator.cpp.
References SCA_IObject::UnregisterActuator().
Member Function Documentation
CValue * KX_ParentActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 71 of file KX_ParentActuator.cpp.
References KX_ParentActuator(), and ProcessReplica().
void KX_ParentActuator::ProcessReplica () [virtual]
Makes sure any internal data owned by this class is deep copied.
Reimplemented from SCA_IActuator.
Definition at line 79 of file KX_ParentActuator.cpp.
References SCA_IObject::RegisterActuator().
Referenced by GetReplica().
void KX_ParentActuator::Relink (CTR_Map< CTR_HashedPtr, void * > * obj_map) [virtual]
Reimplemented from SCA_ILogicBrick.
Definition at line 98 of file KX_ParentActuator.cpp.
References SCA_IObject::RegisterActuator(), and SCA_IObject::UnregisterActuator().
bool KX_ParentActuator::UnlinkObject (SCA_IObject * clientobj) [virtual]
UnlinkObject(...) Certain actuator use gameobject pointers (like TractTo actuator) This function can be called when an object is removed to make sure that the actuator will not use it anymore.
Reimplemented from SCA_IActuator.
Definition at line 87 of file KX_ParentActuator.cpp.
References NULL.
bool KX_ParentActuator::Update (void) [virtual]
Reimplemented from SCA_IActuator.
Definition at line 111 of file KX_ParentActuator.cpp.
References SCA_ILogicBrick::GetParent(), SCA_IActuator::IsNegativeEvent(), KX_GetActiveScene(), KX_PARENT_REMOVE, KX_PARENT_SET, SCA_IActuator::RemoveAllEvents(), KX_GameObject::RemoveParent(), and KX_GameObject::SetParent().
The documentation for this class was generated from the following files:
KX_ParentActuator.h
KX_ParentActuator.cpp