Blender: FilterBlueScreen Class Reference
FilterBlueScreen Class Reference
pixel filter for blue screen
#include <FilterBlueScreen.h>
Public Member Functions
FilterBlueScreen (void)
constructor
virtual ~FilterBlueScreen (void)
destructor
unsigned char * getColor (void)
get color
void setColor (unsigned char red, unsigned char green, unsigned char blue)
set color
unsigned short * getLimits (void)
get limits for color variation
void setLimits (unsigned short minLimit, unsigned short maxLimit)
set limits for color variation
Protected Member Functions
template<class SRC >
unsigned int tFilter (SRC src, short x, short y, short *size, unsigned int pixSize, unsigned int val)
filter pixel template, source int buffer
virtual unsigned int filter (unsigned char *src, short x, short y, short *size, unsigned int pixSize, unsigned int val=0)
virtual filtering function for byte source
virtual unsigned int filter (unsigned int *src, short x, short y, short *size, unsigned int pixSize, unsigned int val=0)
virtual filtering function for unsigned int source
Protected Attributes
unsigned char m_color [3]
blue screen color (red component first)
unsigned short m_limits [2]
unsigned int m_squareLimits [2]
squared limits for color variation
unsigned int m_limitDist
distance between squared limits
Detailed Description
pixel filter for blue screen
Definition at line 36 of file FilterBlueScreen.h.
Constructor & Destructor Documentation
FilterBlueScreen::FilterBlueScreen (void)
constructor
Definition at line 38 of file FilterBlueScreen.cpp.
References setColor(), and setLimits().
virtual FilterBlueScreen::~FilterBlueScreen (void) [inline, virtual]
destructor
Definition at line 42 of file FilterBlueScreen.h.
Member Function Documentation
virtual unsigned int FilterBlueScreen::filter (unsigned char * src, short x, short y, short * size, unsigned int pixSize, unsigned int val = 0) [inline, protected, virtual]
virtual filtering function for byte source
Reimplemented from FilterBase.
Definition at line 91 of file FilterBlueScreen.h.
References tFilter().
virtual unsigned int FilterBlueScreen::filter (unsigned int * src, short x, short y, short * size, unsigned int pixSize, unsigned int val = 0) [inline, protected, virtual]
virtual filtering function for unsigned int source
Reimplemented from FilterBase.
Definition at line 95 of file FilterBlueScreen.h.
References tFilter().
unsigned char* FilterBlueScreen::getColor (void) [inline]
get color
Definition at line 45 of file FilterBlueScreen.h.
References m_color.
unsigned short* FilterBlueScreen::getLimits (void) [inline]
get limits for color variation
Definition at line 50 of file FilterBlueScreen.h.
References m_limits.
void FilterBlueScreen::setColor (unsigned char red, unsigned char green, unsigned char blue)
set color
Definition at line 47 of file FilterBlueScreen.cpp.
References m_color.
Referenced by FilterBlueScreen(), and setColor().
void FilterBlueScreen::setLimits (unsigned short minLimit, unsigned short maxLimit)
set limits for color variation
Definition at line 55 of file FilterBlueScreen.cpp.
References m_limitDist, m_limits, and m_squareLimits.
Referenced by FilterBlueScreen(), and setLimits().
template<class SRC > unsigned int FilterBlueScreen::tFilter (SRC src, short x, short y, short * size, unsigned int pixSize, unsigned int val) [inline, protected]
filter pixel template, source int buffer
Definition at line 66 of file FilterBlueScreen.h.
References m_color, m_limitDist, m_squareLimits, VT_A, VT_B, VT_G, and VT_R.
Referenced by filter().
Member Data Documentation
unsigned char FilterBlueScreen::m_color[3] [protected]
blue screen color (red component first)
Definition at line 56 of file FilterBlueScreen.h.
Referenced by getColor(), setColor(), and tFilter().
unsigned int FilterBlueScreen::m_limitDist [protected]
distance between squared limits
Definition at line 63 of file FilterBlueScreen.h.
Referenced by setLimits(), and tFilter().
unsigned short FilterBlueScreen::m_limits[2] [protected]
limits for color variation - first defines, where ends fully transparent color, second defines, where begins fully opaque color
Definition at line 59 of file FilterBlueScreen.h.
Referenced by getLimits(), and setLimits().
unsigned int FilterBlueScreen::m_squareLimits[2] [protected]
squared limits for color variation
Definition at line 61 of file FilterBlueScreen.h.
Referenced by setLimits(), and tFilter().
The documentation for this class was generated from the following files:
FilterBlueScreen.h
FilterBlueScreen.cpp