Blender: BKE_fcurve.h File Reference
BKE_fcurve.h File Reference
blenkernel
#include "DNA_curve_types.h"
Classes
struct CfraElem
struct FModifierTypeInfo
Defines
#define DRIVER_TARGETS_LOOPER(dvar)
#define DRIVER_TARGETS_USED_LOOPER(dvar)
#define DRIVER_TARGETS_LOOPER_END }
Typedefs
typedef struct CfraElem CfraElem
typedef struct FModifierTypeInfo FModifierTypeInfo
typedef enum eFMI_Action_Types eFMI_Action_Types
typedef enum eFMI_Requirement_Flags eFMI_Requirement_Flags
typedef float(* FcuSampleFunc)(struct FCurve *fcu, void *data, float evaltime)
Enumerations
enum eFMI_Action_Types { FMI_TYPE_EXTRAPOLATION = 0, FMI_TYPE_INTERPOLATION, FMI_TYPE_REPLACE_VALUES, FMI_TYPE_GENERATE_CURVE }
enum eFMI_Requirement_Flags { FMI_REQUIRES_ORIGINAL_DATA = (1<<0), FMI_REQUIRES_NOTHING = (1<<1), FMI_REQUIRES_RUNTIME_CHECK = (1<<2) }
Functions
void bezt_add_to_cfra_elem (ListBase *lb, struct BezTriple *bezt)
void fcurve_free_driver (struct FCurve *fcu)
struct ChannelDriver * fcurve_copy_driver (struct ChannelDriver *driver)
void driver_free_variable (struct ChannelDriver *driver, struct DriverVar *dvar)
void driver_change_variable_type (struct DriverVar *dvar, int type)
struct DriverVar * driver_add_new_variable (struct ChannelDriver *driver)
float driver_get_variable_value (struct ChannelDriver *driver, struct DriverVar *dvar)
FModifierTypeInfo * fmodifier_get_typeinfo (struct FModifier *fcm)
FModifierTypeInfo * get_fmodifier_typeinfo (int type)
struct FModifier * add_fmodifier (ListBase *modifiers, int type)
struct FModifier * copy_fmodifier (struct FModifier *src)
void copy_fmodifiers (ListBase *dst, ListBase *src)
int remove_fmodifier (ListBase *modifiers, struct FModifier *fcm)
void free_fmodifiers (ListBase *modifiers)
struct FModifier * find_active_fmodifier (ListBase *modifiers)
void set_active_fmodifier (ListBase *modifiers, struct FModifier *fcm)
short list_has_suitable_fmodifier (ListBase *modifiers, int mtype, short acttype)
float evaluate_time_fmodifiers (ListBase *modifiers, struct FCurve *fcu, float cvalue, float evaltime)
void evaluate_value_fmodifiers (ListBase *modifiers, struct FCurve *fcu, float *cvalue, float evaltime)
void fcurve_bake_modifiers (struct FCurve *fcu, int start, int end)
void free_fcurve (struct FCurve *fcu)
struct FCurve * copy_fcurve (struct FCurve *fcu)
void free_fcurves (ListBase *list)
void copy_fcurves (ListBase *dst, ListBase *src)
struct FCurve * list_find_fcurve (ListBase *list, const char rna_path[], const int array_index)
struct FCurve * iter_step_fcurve (struct FCurve *fcu_iter, const char rna_path[])
struct FCurve * id_data_find_fcurve (ID *id, void *data, struct StructRNA *type, const char *prop_name, int index, char *driven)
int list_find_data_fcurves (ListBase *dst, ListBase *src, const char *dataPrefix, const char *dataName)
struct FCurve * rna_get_fcurve (struct PointerRNA *ptr, struct PropertyRNA *prop, int rnaindex, struct bAction **action, int *driven)
int binarysearch_bezt_index (struct BezTriple array[], float frame, int arraylen, short *replace)
void calc_fcurve_range (struct FCurve *fcu, float *min, float *max, const short do_sel_only, const short do_min_length)
void calc_fcurve_bounds (struct FCurve *fcu, float *xmin, float *xmax, float *ymin, float *ymax, const short do_sel_only)
short fcurve_are_keyframes_usable (struct FCurve *fcu)
short fcurve_is_keyframable (struct FCurve *fcu)
void calchandles_fcurve (struct FCurve *fcu)
void testhandles_fcurve (struct FCurve *fcu, const short use_handle)
void sort_time_fcurve (struct FCurve *fcu)
short test_time_fcurve (struct FCurve *fcu)
void correct_bezpart (float *v1, float *v2, float *v3, float *v4)
float evaluate_fcurve (struct FCurve *fcu, float evaltime)
void calculate_fcurve (struct FCurve *fcu, float ctime)
float fcurve_samplingcb_evalcurve (struct FCurve *fcu, void *data, float evaltime)
void fcurve_store_samples (struct FCurve *fcu, void *data, int start, int end, FcuSampleFunc sample_cb)
Detailed Description
Author:
Joshua Leung
Since:
2009
Definition in file BKE_fcurve.h.
Define Documentation
#define DRIVER_TARGETS_LOOPER (dvar)
Value:
{ \
        DriverTarget *dtar= &dvar->targets[0]; \
        int tarIndex= 0; \
        for (; tarIndex < MAX_DRIVER_TARGETS; tarIndex++, dtar++)
Definition at line 71 of file BKE_fcurve.h.
Referenced by direct_link_fcurves(), driver_free_variable(), expand_fcurves(), fcurve_copy_driver(), lib_link_fcurves(), and object_copy_proxy_drivers().
#define DRIVER_TARGETS_LOOPER_END }
Definition at line 85 of file BKE_fcurve.h.
Referenced by animdata_dtar_clear_cb(), BKE_relink_animdata(), dag_add_driver_relation(), direct_link_fcurves(), driver_change_variable_type(), driver_free_variable(), drivers_path_rename_fix(), dvar_eval_locDiff(), expand_fcurves(), fcurve_copy_driver(), lib_link_fcurves(), object_copy_proxy_drivers(), outliner_add_element(), and write_fcurves().
#define DRIVER_TARGETS_USED_LOOPER (dvar)
Value:
{ \
        DriverTarget *dtar= &dvar->targets[0]; \
        int tarIndex= 0; \
        for (; tarIndex < dvar->num_targets; tarIndex++, dtar++)
Definition at line 78 of file BKE_fcurve.h.
Referenced by animdata_dtar_clear_cb(), BKE_relink_animdata(), dag_add_driver_relation(), driver_change_variable_type(), drivers_path_rename_fix(), dvar_eval_locDiff(), outliner_add_element(), and write_fcurves().
Typedef Documentation
typedef struct CfraElem CfraElem
typedef enum eFMI_Action_Types eFMI_Action_Types
typedef enum eFMI_Requirement_Flags eFMI_Requirement_Flags
typedef float(* FcuSampleFunc)(struct FCurve *fcu, void *data, float evaltime)
Definition at line 255 of file BKE_fcurve.h.
typedef struct FModifierTypeInfo FModifierTypeInfo
Enumeration Type Documentation
enum eFMI_Action_Types
Enumerator:
FMI_TYPE_EXTRAPOLATION
FMI_TYPE_INTERPOLATION
FMI_TYPE_REPLACE_VALUES
FMI_TYPE_GENERATE_CURVE
Definition at line 139 of file BKE_fcurve.h.
enum eFMI_Requirement_Flags
Enumerator:
FMI_REQUIRES_ORIGINAL_DATA
FMI_REQUIRES_NOTHING
FMI_REQUIRES_RUNTIME_CHECK
Definition at line 151 of file BKE_fcurve.h.
Function Documentation
struct FModifier* add_fmodifier (ListBase * modifiers, int type) [read]
Definition at line 997 of file fmodifier.c.
References BLI_addtail(), FModifier::data, ELEM, ListBase::first, FModifier::flag, FMODIFIER_FLAG_ACTIVE, FMODIFIER_FLAG_EXPANDED, FMODIFIER_TYPE_CYCLES, get_fmodifier_typeinfo(), FModifier::influence, ListBase::last, MEM_callocN(), FModifierTypeInfo::new_data, NULL, FModifierTypeInfo::size, FModifierTypeInfo::structName, and FModifier::type.
Referenced by ED_object_parent_set(), graph_fmodifier_add_exec(), icu_to_fcurves(), nla_fmodifier_add_exec(), setexpo_action_keys(), setexpo_graph_keys(), and verify_driver_fcurve().
void bezt_add_to_cfra_elem (ListBase * lb, struct BezTriple * bezt)
Definition at line 691 of file fcurve.c.
References BLI_addtail(), BLI_insertlinkbefore(), CfraElem::cfra, BezTriple::f2, ListBase::first, MEM_callocN(), CfraElem::next, CfraElem::sel, SELECT, and BezTriple::vec.
int binarysearch_bezt_index (struct BezTriple array[], float frame, int arraylen, short * replace)
Definition at line 360 of file fcurve.c.
References BEZT_BINARYSEARCH_THRESH, IS_EQT, NULL, and BezTriple::vec.
Referenced by delete_keyframe(), fcurve_frame_has_keyframe(), insert_bezt_fcurve(), and pose_propagate_fcurve().
void calc_fcurve_bounds (struct FCurve * fcu, float * xmin, float * xmax, float * ymin, float * ymax, const short do_sel_only)
Definition at line 479 of file fcurve.c.
References BEZSELECTED, FCurve::bezt, BLI_assert, FALSE, FCurve::fpt, G, G_DEBUG, get_fcurve_end_keyframes(), i, MAX2, MIN2, NULL, FCurve::totvert, TRUE, BezTriple::vec, and FPoint::vec.
Referenced by get_graph_keyframe_extents().
void calc_fcurve_range (struct FCurve * fcu, float * min, float * max, const short do_sel_only, const short do_min_length)
Definition at line 561 of file fcurve.c.
References FCurve::bezt, BLI_assert, FALSE, FCurve::fpt, get_fcurve_end_keyframes(), max, MAX2, min, MIN2, NULL, FCurve::totvert, TRUE, FPoint::vec, and BezTriple::vec.
Referenced by calc_action_range(), and get_keyframe_extents().
void calchandles_fcurve (struct FCurve * fcu)
Definition at line 778 of file fcurve.c.
References FCurve::bezt, calchandleNurb(), ELEM, FCurve::extend, FCURVE_EXTRAPOLATE_CONSTANT, BezTriple::h1, BezTriple::h2, HD_AUTO, HD_AUTO_ANIM, next, NULL, FCurve::totvert, and BezTriple::vec.
Referenced by AnimationImporter::add_bezt(), delete_fcurve_key(), insert_vert_fcurve(), mirror_action_keys(), mirror_graph_keys(), nlaedit_apply_scale_exec(), paste_animedit_keys_fcurve(), sample_fcurve(), sethandles_action_keys(), sethandles_graph_keys(), setipo_action_keys(), setipo_graph_keys(), smooth_fcurve(), snap_action_keys(), snap_graph_keys(), and testhandles_fcurve().
void calculate_fcurve (struct FCurve * fcu, float ctime)
Definition at line 2120 of file fcurve.c.
References FCurve::curval, FCurve::driver, DRIVER_FLAG_INVALID, evaluate_fcurve(), ChannelDriver::flag, FMI_TYPE_GENERATE_CURVE, list_has_suitable_fmodifier(), FCurve::modifiers, and FCurve::totvert.
Referenced by animsys_evaluate_action_group(), animsys_evaluate_drivers(), and animsys_evaluate_fcurves().
struct FCurve* copy_fcurve (struct FCurve * fcu) [read]
Definition at line 122 of file fcurve.c.
References FCurve::bezt, copy_fmodifiers(), FCurve::driver, fcurve_copy_driver(), FCurve::fpt, FCurve::grp, MEM_dupallocN(), FCurve::modifiers, FCurve::next, NULL, FCurve::prev, and FCurve::rna_path.
Referenced by ANIM_copy_driver(), copy_action(), copy_fcurves(), fcurve_path_rename(), icu_to_fcurves(), and seq_dupe_animdata().
void copy_fcurves (ListBase * dst, ListBase * src)
Definition at line 154 of file fcurve.c.
References BLI_addtail(), copy_fcurve(), ELEM, ListBase::first, ListBase::last, FCurve::next, and NULL.
Referenced by BKE_copy_animdata(), copy_nlastrip(), editCurve_to_undoCurve(), object_copy_proxy_drivers(), and undoCurve_to_editCurve().
struct FModifier* copy_fmodifier (struct FModifier * src) [read]
Definition at line 1037 of file fmodifier.c.
References FModifierTypeInfo::copy_data, FModifier::data, fmodifier_get_typeinfo(), MEM_dupallocN(), FModifier::next, NULL, and FModifier::prev.
Referenced by ANIM_fmodifiers_copy_to_buf(), and ANIM_fmodifiers_paste_from_buf().
void copy_fmodifiers (ListBase * dst, ListBase * src)
Definition at line 1062 of file fmodifier.c.
References BLI_duplicatelist(), FModifierTypeInfo::copy_data, FModifier::data, ELEM, ListBase::first, fmodifier_get_typeinfo(), ListBase::last, MEM_dupallocN(), FModifier::next, and NULL.
Referenced by ANIM_fmodifiers_copy_to_buf(), ANIM_paste_driver(), copy_fcurve(), and copy_nlastrip().
void correct_bezpart (float * v1, float * v2, float * v3, float * v4)
Referenced by curvemap_make_table(), draw_fcurve_curve_bezts(), and fcurve_eval_keyframes().
struct DriverVar* driver_add_new_variable (struct ChannelDriver * driver) [read]
Definition at line 1457 of file fcurve.c.
References BLI_addtail(), BLI_uniquename(), driver_change_variable_type(), DRIVER_FLAG_RENAMEVAR, DRIVER_TYPE_PYTHON, DVAR_TYPE_SINGLE_PROP, ChannelDriver::flag, MEM_callocN(), DriverVar::name, NULL, ChannelDriver::type, and ChannelDriver::variables.
Referenced by ANIM_add_driver(), driver_add_var_cb(), and idriver_to_cdriver().
void driver_change_variable_type (struct DriverVar * dvar, int type)
Definition at line 1427 of file fcurve.c.
References DRIVER_TARGETS_LOOPER_END, DRIVER_TARGETS_USED_LOOPER, DTAR_FLAG_ID_OB_ONLY, ELEM, get_dvar_typeinfo(), ID_OB, NULL, DriverVarTypeInfo::num_targets, DriverVar::num_targets, DriverVarTypeInfo::target_flags, and DriverVar::type.
Referenced by ANIM_add_driver(), driver_add_new_variable(), and idriver_to_cdriver().
void driver_free_variable (struct ChannelDriver * driver, struct DriverVar * dvar)
Definition at line 1397 of file fcurve.c.
References BLI_freelinkN(), DRIVER_FLAG_RENAMEVAR, DRIVER_TARGETS_LOOPER, DRIVER_TARGETS_LOOPER_END, DRIVER_TYPE_PYTHON, ChannelDriver::flag, MEM_freeN(), NULL, ChannelDriver::type, and ChannelDriver::variables.
Referenced by driver_delete_var_cb(), and fcurve_free_driver().
float driver_get_variable_value (struct ChannelDriver * driver, struct DriverVar * dvar)
Definition at line 1550 of file fcurve.c.
References DriverVar::curval, ELEM, get_dvar_typeinfo(), DriverVarTypeInfo::get_value, NULL, and DriverVar::type.
Referenced by BPY_driver_exec(), and evaluate_driver().
float evaluate_fcurve (struct FCurve * fcu, float evaltime)
Definition at line 2080 of file fcurve.c.
References FCurve::bezt, FCurve::driver, evaluate_driver(), evaluate_time_fmodifiers(), evaluate_value_fmodifiers(), fcurve_eval_keyframes(), fcurve_eval_samples(), FCURVE_INT_VALUES, FCurve::flag, floorf, FCurve::fpt, and FCurve::modifiers.
Referenced by calculate_fcurve(), draw_fcurve_curve(), AnimationImporter::evaluate_animation(), fcurve_samplingcb_evalcurve(), BL_ScalarInterpolator::GetValue(), new_key_needed(), nla_draw_strip_curves(), nlastrip_evaluate_actionclip(), pose_slide_apply_quat(), pose_slide_apply_val(), sample_fcurve(), seq_render_effect_strip_impl(), and sequence_effect_speed_rebuild_map().
float evaluate_time_fmodifiers (ListBase * modifiers, struct FCurve * fcu, float cvalue, float evaltime)
Definition at line 1256 of file fmodifier.c.
References FModifier::efra, ELEM, eval_fmodifier_influence(), FModifierTypeInfo::evaluate_modifier_time, FModifier::flag, FMODIFIER_FLAG_DISABLED, FMODIFIER_FLAG_MUTED, FMODIFIER_FLAG_RANGERESTRICT, fmodifier_get_typeinfo(), interpf(), ListBase::last, NULL, FModifier::prev, and FModifier::sfra.
Referenced by evaluate_fcurve(), and nlastrip_evaluate_actionclip().
void evaluate_value_fmodifiers (ListBase * modifiers, struct FCurve * fcu, float * cvalue, float evaltime)
Definition at line 1305 of file fmodifier.c.
References FModifier::efra, ELEM, eval_fmodifier_influence(), FModifierTypeInfo::evaluate_modifier, ListBase::first, FModifier::flag, FMODIFIER_FLAG_DISABLED, FMODIFIER_FLAG_MUTED, FMODIFIER_FLAG_RANGERESTRICT, fmodifier_get_typeinfo(), interpf(), FModifier::next, NULL, and FModifier::sfra.
Referenced by evaluate_fcurve(), and nlastrip_evaluate_actionclip().
short fcurve_are_keyframes_usable (struct FCurve * fcu)
Definition at line 613 of file fcurve.c.
References FModifier::data, data, FCM_GENERATOR_ADDITIVE, ListBase::first, FMod_FunctionGenerator::flag, FMod_Generator::flag, FModifier::flag, FMODIFIER_FLAG_DISABLED, FMODIFIER_FLAG_MUTED, FMODIFIER_TYPE_CYCLES, FMODIFIER_TYPE_FN_GENERATOR, FMODIFIER_TYPE_GENERATOR, FMODIFIER_TYPE_NOISE, FMODIFIER_TYPE_STEPPED, FCurve::fpt, if(), ListBase::last, FCurve::modifiers, NULL, FModifier::prev, and FModifier::type.
Referenced by fcurve_is_keyframable(), graph_draw_curves(), and graphop_visible_keyframes_poll().
void fcurve_bake_modifiers (struct FCurve * fcu, int start, int end)
Definition at line 1342 of file fmodifier.c.
References FCurve::driver, ELEM, fcurve_samplingcb_evalcurve(), fcurve_store_samples(), ListBase::first, free_fmodifiers(), FCurve::modifiers, and NULL.
struct ChannelDriver* fcurve_copy_driver (struct ChannelDriver * driver) [read]
Definition at line 1515 of file fcurve.c.
References BLI_duplicatelist(), DRIVER_TARGETS_LOOPER, DRIVER_TARGETS_LOOPER_END, ChannelDriver::expr_comp, ListBase::first, ListBase::last, MEM_dupallocN(), DriverVar::next, NULL, and ChannelDriver::variables.
Referenced by ANIM_paste_driver(), and copy_fcurve().
void fcurve_free_driver (struct FCurve * fcu)
Definition at line 1487 of file fcurve.c.
References BPY_DECREF(), FCurve::driver, driver_free_variable(), ELEM, ChannelDriver::expr_comp, ListBase::first, MEM_freeN(), DriverVar::next, NULL, and ChannelDriver::variables.
Referenced by free_fcurve().
short fcurve_is_keyframable (struct FCurve * fcu)
Definition at line 674 of file fcurve.c.
References AGRP_PROTECTED, fcurve_are_keyframes_usable(), FCURVE_PROTECTED, FCurve::flag, bActionGroup::flag, and FCurve::grp.
Referenced by graphkeys_click_insert_exec(), graphop_editable_keyframes_poll(), and insert_keyframe_direct().
float fcurve_samplingcb_evalcurve (struct FCurve * fcu, void * data, float evaltime)
Referenced by bake_graph_curves(), and fcurve_bake_modifiers().
void fcurve_store_samples (struct FCurve * fcu, void * data, int start, int end, FcuSampleFunc sample_cb)
Definition at line 734 of file fcurve.c.
References FCurve::bezt, ELEM, FCurve::fpt, MEM_callocN(), MEM_freeN(), NULL, FCurve::totvert, and FPoint::vec.
Referenced by bake_graph_curves(), and fcurve_bake_modifiers().
struct FModifier* find_active_fmodifier (ListBase * modifiers) [read]
Definition at line 1132 of file fmodifier.c.
References ELEM, ListBase::first, FModifier::flag, FMODIFIER_FLAG_ACTIVE, FModifier::next, and NULL.
Referenced by ANIM_fmodifiers_copy_to_buf(), and graph_draw_curves().
FModifierTypeInfo* fmodifier_get_typeinfo (struct FModifier * fcm)
Definition at line 985 of file fmodifier.c.
References get_fmodifier_typeinfo(), NULL, and FModifier::type.
Referenced by ANIM_uiTemplate_fmodifier_draw(), copy_fmodifier(), copy_fmodifiers(), evaluate_time_fmodifiers(), evaluate_value_fmodifiers(), list_has_suitable_fmodifier(), remove_fmodifier(), validate_fmodifier_cb(), and write_fmodifiers().
void free_fcurve (struct FCurve * fcu)
Definition at line 74 of file fcurve.c.
References FCurve::bezt, fcurve_free_driver(), FCurve::fpt, free_fmodifiers(), MEM_freeN(), FCurve::modifiers, NULL, and FCurve::rna_path.
Referenced by ANIM_fcurve_delete_from_animdata(), ANIM_remove_driver(), animchannels_delete_exec(), fcurve_path_rename(), fcurve_remove(), free_anim_drivers_copybuf(), free_fcurves(), seq_free_animdata(), and AnimationImporter::~AnimationImporter().
void free_fcurves (ListBase * list)
Definition at line 98 of file fcurve.c.
References ListBase::first, free_fcurve(), ListBase::last, FCurve::next, and NULL.
Referenced by BKE_free_animdata(), cleardrivers_animdata_cb(), do_versions_ipos_to_animato(), free_action(), free_nlastrip(), free_undoCurve(), graph_free(), graphkeys_clear_ghostcurves_exec(), object_copy_proxy_drivers(), and undoCurve_to_editCurve().
void free_fmodifiers (ListBase * modifiers)
Definition at line 1116 of file fmodifier.c.
References ListBase::first, FModifier::next, NULL, and remove_fmodifier().
Referenced by ANIM_fmodifiers_paste_from_buf(), fcurve_bake_modifiers(), free_fcurve(), free_fmodifiers_copybuf(), and free_nlastrip().
FModifierTypeInfo* get_fmodifier_typeinfo (int type)
Definition at line 960 of file fmodifier.c.
References FMODIFIER_NUM_TYPES, FMODIFIER_TYPE_NULL, fmods_init_typeinfo(), and NULL.
Referenced by add_fmodifier(), fmodifier_get_typeinfo(), graph_fmodifier_add_invoke(), and nla_fmodifier_add_invoke().
struct FCurve* id_data_find_fcurve (ID * id, void * data, struct StructRNA * type, const char * prop_name, int index, char * driven) [read]
Definition at line 175 of file fcurve.c.
References AnimData::action, BKE_animdata_from_id(), bAction::curves, AnimData::drivers, ELEM, FALSE, ListBase::first, list_find_fcurve(), MEM_freeN(), NULL, RNA_path_from_ID_to_property(), RNA_pointer_create(), RNA_struct_find_property(), and TRUE.
Referenced by seq_render_effect_strip_impl(), sequence_effect_speed_rebuild_map(), and sound_update_animation_flags_exec().
struct FCurve* iter_step_fcurve (struct FCurve * fcu_iter, const char rna_path[]) [read]
Definition at line 244 of file fcurve.c.
References ELEM, FCurve::next, NULL, and FCurve::rna_path.
Referenced by ANIM_remove_driver().
int list_find_data_fcurves (ListBase * dst, ListBase * src, const char * dataPrefix, const char * dataName)
Definition at line 273 of file fcurve.c.
References BLI_addtail(), BLI_getQuotedStr(), LinkData::data, ELEM4, ListBase::first, MEM_callocN(), MEM_freeN(), FCurve::next, NULL, and FCurve::rna_path.
struct FCurve* list_find_fcurve (ListBase * list, const char rna_path[], const int array_index) [read]
Definition at line 221 of file fcurve.c.
References FCurve::array_index, ELEM, ListBase::first, FCurve::next, NULL, and FCurve::rna_path.
Referenced by BKE_nlastrip_validate_fcurves(), id_data_find_fcurve(), insert_key_button_exec(), make_new_animlistelem(), nla_draw_strip_curves(), pyrna_struct_driver_add(), rna_get_fcurve(), verify_driver_fcurve(), and verify_fcurve().
short list_has_suitable_fmodifier (ListBase * modifiers, int mtype, short acttype)
Definition at line 1172 of file fmodifier.c.
References FModifierTypeInfo::acttype, ELEM, ListBase::first, fmodifier_get_typeinfo(), FModifier::next, NULL, and FModifier::type.
Referenced by calculate_fcurve(), delete_action_keys(), delete_graph_keys(), delete_keyframe(), setexpo_action_keys(), and setexpo_graph_keys().
int remove_fmodifier (ListBase * modifiers, struct FModifier * fcm)
Definition at line 1085 of file fmodifier.c.
References BLI_freelinkN(), FModifier::data, fmodifier_get_typeinfo(), FModifierTypeInfo::free_data, MEM_freeN(), and NULL.
Referenced by delete_fmodifier_cb(), free_fmodifiers(), setexpo_action_keys(), and setexpo_graph_keys().
struct FCurve* rna_get_fcurve (struct PointerRNA * ptr, struct PropertyRNA * prop, int rnaindex, struct bAction ** action, int * driven) [read]
Definition at line 311 of file fcurve.c.
References AnimData::action, BKE_animdata_from_id(), bAction::curves, PointerRNA::data, AnimData::drivers, ListBase::first, PointerRNA::id, list_find_fcurve(), MEM_freeN(), NULL, RNA_path_from_ID_to_property(), and RNA_property_animateable().
Referenced by node_animation_properties(), and ui_but_get_fcurve().
void set_active_fmodifier (ListBase * modifiers, struct FModifier * fcm)
Definition at line 1151 of file fmodifier.c.
References ELEM, ListBase::first, FModifier::flag, FMODIFIER_FLAG_ACTIVE, FModifier::next, and NULL.
Referenced by graph_fmodifier_add_exec(), and nla_fmodifier_add_exec().
void sort_time_fcurve (struct FCurve * fcu)
Definition at line 887 of file fcurve.c.
References FCurve::bezt, SWAP, FCurve::totvert, and BezTriple::vec.
Referenced by ANIM_editkeyframes_refresh(), graphedit_activekey_update_cb(), and remake_graph_transdata().
short test_time_fcurve (struct FCurve * fcu)
Definition at line 930 of file fcurve.c.
References FCurve::bezt, FCurve::fpt, NULL, FCurve::totvert, BezTriple::vec, and FPoint::vec.
void testhandles_fcurve (struct FCurve * fcu, const short use_handle)
Definition at line 831 of file fcurve.c.
References FCurve::bezt, calchandles_fcurve(), ELEM, BezTriple::f1, BezTriple::f2, BezTriple::f3, FALSE, BezTriple::h1, BezTriple::h2, HD_ALIGN, HD_AUTO, HD_AUTO_ANIM, HD_VECT, if(), NULL, and SELECT.
Referenced by ANIM_editkeyframes_refresh(), graphedit_activekey_update_cb(), posttrans_fcurve_clean(), and remake_graph_transdata().