Blender: AUD_SequencerFactory Class Reference
AUD_SequencerFactory Class Reference
#include <AUD_SequencerFactory.h>
Public Member Functions
AUD_SequencerFactory (AUD_Specs specs, float fps, bool muted)
~AUD_SequencerFactory ()
void lock ()
void unlock ()
void setSpecs (AUD_Specs specs)
void setFPS (float fps)
void mute (bool muted)
bool getMute () const
float getSpeedOfSound () const
void setSpeedOfSound (float speed)
float getDopplerFactor () const
void setDopplerFactor (float factor)
AUD_DistanceModel getDistanceModel () const
void setDistanceModel (AUD_DistanceModel model)
AUD_AnimateableProperty * getAnimProperty (AUD_AnimateablePropertyType type)
AUD_Reference< AUD_SequencerEntry > add (AUD_Reference< AUD_IFactory > sound, float begin, float end, float skip)
void remove (AUD_Reference< AUD_SequencerEntry > entry)
AUD_Reference< AUD_IReader > createQualityReader ()
virtual AUD_Reference
< AUD_IReader > createReader ()
Friends
class AUD_SequencerReader
Detailed Description
This factory represents sequenced entries to play a sound scene.
Definition at line 44 of file AUD_SequencerFactory.h.
Constructor & Destructor Documentation
AUD_SequencerFactory::AUD_SequencerFactory (AUD_Specs specs, float fps, bool muted)
Creates a new sound scene.
Parameters:
specs The output audio data specification.
fps The FPS of the scene.
muted Whether the whole scene is muted.
Definition at line 34 of file AUD_SequencerFactory.cpp.
References AUD_Quaternion::get(), and AUD_AnimateableProperty::write().
AUD_SequencerFactory::~AUD_SequencerFactory ()
Definition at line 61 of file AUD_SequencerFactory.cpp.
Member Function Documentation
AUD_Reference< AUD_SequencerEntry > AUD_SequencerFactory::add (AUD_Reference< AUD_IFactory > sound, float begin, float end, float skip)
Adds a new entry to the scene.
Parameters:
sound The sound this entry should play.
begin The start time.
end The end time or a negative value if determined by the sound.
skip How much seconds should be skipped at the beginning.
Returns:
The entry added.
Definition at line 169 of file AUD_SequencerFactory.cpp.
References lock(), and unlock().
AUD_Reference< AUD_IReader > AUD_SequencerFactory::createQualityReader ()
Creates a new reader with high quality resampling.
Returns:
The new reader.
Definition at line 193 of file AUD_SequencerFactory.cpp.
References AUD_SequencerReader.
Referenced by AUD_mixdown().
AUD_Reference< AUD_IReader > AUD_SequencerFactory::createReader () [virtual]
Creates a reader for playback of the sound source.
Returns:
A pointer to an AUD_IReader object or NULL if there has been an error.
Exceptions:
AUD_Exception An exception may be thrown if there has been a more unexpected error during reader creation.
Implements AUD_IFactory.
Definition at line 198 of file AUD_SequencerFactory.cpp.
References AUD_SequencerReader.
AUD_AnimateableProperty * AUD_SequencerFactory::getAnimProperty (AUD_AnimateablePropertyType type)
Retrieves one of the animated properties of the factory.
Parameters:
type Which animated property to retrieve.
Returns:
A pointer to the animated property, valid as long as the factory is.
Definition at line 154 of file AUD_SequencerFactory.cpp.
References AUD_AP_LOCATION, AUD_AP_ORIENTATION, AUD_AP_VOLUME, and NULL.
AUD_DistanceModel AUD_SequencerFactory::getDistanceModel () const
Retrieves the distance model.
Returns:
The distance model.
Definition at line 139 of file AUD_SequencerFactory.cpp.
float AUD_SequencerFactory::getDopplerFactor () const
Retrieves the doppler factor. This value is a scaling factor for the velocity vectors of sources and listener which is used while calculating the doppler effect.
Returns:
The doppler factor.
Definition at line 124 of file AUD_SequencerFactory.cpp.
bool AUD_SequencerFactory::getMute () const
Retrieves the muting state of the scene.
Returns:
Whether the scene is muted.
Definition at line 104 of file AUD_SequencerFactory.cpp.
float AUD_SequencerFactory::getSpeedOfSound () const
Retrieves the speed of sound. This value is needed for doppler effect calculation.
Returns:
The speed of sound.
Definition at line 109 of file AUD_SequencerFactory.cpp.
void AUD_SequencerFactory::lock ()
Locks the factory.
Definition at line 66 of file AUD_SequencerFactory.cpp.
Referenced by add(), mute(), remove(), setDistanceModel(), setDopplerFactor(), setFPS(), setSpecs(), and setSpeedOfSound().
void AUD_SequencerFactory::mute (bool muted)
Sets the muting state of the scene.
Parameters:
muted Whether the scene is muted.
Definition at line 95 of file AUD_SequencerFactory.cpp.
References lock(), and unlock().
void AUD_SequencerFactory::remove (AUD_Reference< AUD_SequencerEntry > entry)
Removes an entry from the scene.
Parameters:
entry The entry to remove.
Definition at line 183 of file AUD_SequencerFactory.cpp.
References lock(), and unlock().
void AUD_SequencerFactory::setDistanceModel (AUD_DistanceModel model)
Sets the distance model.
Parameters:
model distance model.
Definition at line 144 of file AUD_SequencerFactory.cpp.
References lock(), and unlock().
Referenced by AUD_updateSequencerData().
void AUD_SequencerFactory::setDopplerFactor (float factor)
Sets the doppler factor. This value is a scaling factor for the velocity vectors of sources and listener which is used while calculating the doppler effect.
Parameters:
factor The new doppler factor.
Definition at line 129 of file AUD_SequencerFactory.cpp.
References lock(), and unlock().
Referenced by AUD_updateSequencerData().
void AUD_SequencerFactory::setFPS (float fps)
Sets the scene's FPS.
Parameters:
fps The new FPS.
Definition at line 86 of file AUD_SequencerFactory.cpp.
References lock(), and unlock().
void AUD_SequencerFactory::setSpecs (AUD_Specs specs)
Sets the audio output specification.
Parameters:
specs The new specification.
Definition at line 76 of file AUD_SequencerFactory.cpp.
References lock(), and unlock().
Referenced by AUD_mixdown().
void AUD_SequencerFactory::setSpeedOfSound (float speed)
Sets the speed of sound. This value is needed for doppler effect calculation.
Parameters:
speed The new speed of sound.
Definition at line 114 of file AUD_SequencerFactory.cpp.
References lock(), and unlock().
Referenced by AUD_updateSequencerData().
void AUD_SequencerFactory::unlock ()
Unlocks the previously locked factory.
Definition at line 71 of file AUD_SequencerFactory.cpp.
Referenced by add(), mute(), remove(), setDistanceModel(), setDopplerFactor(), setFPS(), setSpecs(), and setSpeedOfSound().
Friends And Related Function Documentation
friend class AUD_SequencerReader [friend]
Definition at line 46 of file AUD_SequencerFactory.h.
Referenced by createQualityReader(), and createReader().
The documentation for this class was generated from the following files:
AUD_SequencerFactory.h
AUD_SequencerFactory.cpp