Blender: rna_image.c File Reference
rna_image.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_image_types.h"
#include "DNA_scene_types.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_image.h"
#include "WM_types.h"
#include "WM_api.h"
Functions
static void rna_def_imageuser (BlenderRNA *brna)
static void rna_def_image (BlenderRNA *brna)
void RNA_def_image (BlenderRNA *brna)
Variables
static EnumPropertyItem image_source_items []
Detailed Description
Definition in file rna_image.c.
Function Documentation
static void rna_def_image (BlenderRNA * brna) [static]
Definition at line 416 of file rna_image.c.
References IMA_CLAMP_U, IMA_CLAMP_V, IMA_CM_PREDIVIDE, IMA_DO_PREMUL, IMA_FIELDS, IMA_GEN_FLOAT, IMA_MAX_RENDER_SLOT, IMA_REFLECT, IMA_STD_FIELD, IMA_TILES, IMA_TWINANIM, IMA_TYPE_COMPOSITE, IMA_TYPE_IMAGE, IMA_TYPE_MULTILAYER, IMA_TYPE_R_RESULT, IMA_TYPE_UV_TEST, image_type_items, NC_IMAGE, ND_DISPLAY, NULL, PROP_BOOLEAN, PROP_DYNAMIC, PROP_EDITABLE, PROP_ENUM, PROP_FILEPATH, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_UNSIGNED, PROP_XYZ, RNA_api_image(), RNA_def_float_vector(), RNA_def_int_vector(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_dynamic_array_funcs(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_multi_array(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_image().
void RNA_def_image (BlenderRNA * brna)
Definition at line 637 of file rna_image.c.
References rna_def_image(), and rna_def_imageuser().
static void rna_def_imageuser (BlenderRNA * brna) [static]
Definition at line 359 of file rna_image.c.
References IMA_ANIM_ALWAYS, MAXFRAMEF, MINAFRAMEF, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_TIME, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_image().
Variable Documentation
EnumPropertyItem image_source_items[] [static]
Initial value:
 {
    {IMA_SRC_FILE, "FILE", 0, "Single Image", "Single image file"},
    {IMA_SRC_SEQUENCE, "SEQUENCE", 0, "Image Sequence", "Multiple image files, as a sequence"},
    {IMA_SRC_MOVIE, "MOVIE", 0, "Movie", "Movie file"},
    {IMA_SRC_GENERATED, "GENERATED", 0, "Generated", "Generated image"},
    {IMA_SRC_VIEWER, "VIEWER", 0, "Viewer", "Compositing node viewer"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 45 of file rna_image.c.