Blender: font.c File Reference
font.c File Reference
blenkernel
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>
#include <wchar.h>
#include <wctype.h>
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_vfontdata.h"
#include "BLI_utildefines.h"
#include "DNA_packedFile_types.h"
#include "DNA_curve_types.h"
#include "DNA_vfont_types.h"
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "BKE_utildefines.h"
#include "BKE_packedFile.h"
#include "BKE_library.h"
#include "BKE_font.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_anim.h"
#include "BKE_curve.h"
#include "BKE_displist.h"
Functions
void free_vfont (struct VFont *vf)
void BKE_font_register_builtin (void *mem, int size)
static PackedFile * get_builtin_packedfile (void)
void free_ttfont (void)
struct TmpFont * vfont_find_tmpfont (VFont *vfont)
static VFontData * vfont_get_data (Main *bmain, VFont *vfont)
VFont * load_vfont (Main *bmain, const char *name)
static VFont * which_vfont (Curve *cu, CharInfo *info)
VFont * get_builtin_font (void)
static VChar * find_vfont_char (VFontData *vfd, intptr_t character)
static void build_underline (Curve *cu, float x1, float y1, float x2, float y2, int charidx, short mat_nr)
static void buildchar (Main *bmain, Curve *cu, unsigned long character, CharInfo *info, float ofsx, float ofsy, float rot, int charidx)
int BKE_font_getselection (Object *ob, int *start, int *end)
static float char_width (Curve *cu, VChar *che, CharInfo *info)
struct chartrans * BKE_text_to_curve (Main *bmain, Scene *scene, Object *ob, int mode)
Variables
static ListBase ttfdata = {NULL, NULL}
static void * builtin_font_data = NULL
static int builtin_font_size = 0
Detailed Description
Definition in file font.c.
Function Documentation
int BKE_font_getselection (Object * ob, int * start, int * end)
Definition at line 493 of file font.c.
References Object::data, Curve::editfont, NULL, OB_FONT, Curve::selend, Curve::selstart, and Object::type.
Referenced by BKE_text_to_curve(), copy_selection(), cut_text_exec(), delete_exec(), draw_object(), kill_selection(), material_slot_assign_exec(), set_style(), and toggle_style_exec().
void BKE_font_register_builtin (void * mem, int size)
Definition at line 97 of file font.c.
References builtin_font_data, builtin_font_size, and size().
Referenced by main().
struct chartrans* BKE_text_to_curve (Main * bmain, Scene * scene, Object * ob, int mode) [read]
Definition at line 526 of file font.c.
References KDL::atan2(), BKE_font_getselection(), BLI_strlen_utf8(), BLI_strncpy_wchar_from_utf8(), BLI_vfontchar_from_freetypefont(), build_underline(), buildchar(), ceilf, char_width(), CLAMP(), co, copy_m3_m4(), cos(), CU_CHINFO_SMALLCAPS, CU_CHINFO_SMALLCAPS_CHECK, CU_CHINFO_UNDERLINE, CU_CHINFO_WRAP, CU_FLUSH, CU_FOLLOW, CU_JUSTIFY, CU_LEFT, CU_MIDDLE, CU_PATH, CU_RIGHT, Object::data, chartrans::dobreak, Curve::editfont, ELEM3, find_vfont_char(), Curve::flag, CharInfo::flag, FO_BUILTIN_NAME, FO_CURSDOWN, FO_CURSUP, FO_DUPLI, FO_EDIT, FO_PAGEDOWN, FO_PAGEUP, FO_SELCHANGE, freeNurblist(), Curve::fsize, SelBox::h, TextBox::h, i, if(), invert_m4_m4(), CharInfo::kern, Curve::len, Curve::linedist, Curve::lines, Object::loc, M_PI, makeDispListCurveTypes(), CharInfo::mat_nr, MAX2, MAXTEXTBOX, MEM_callocN(), MEM_freeN(), MEM_mallocN(), mul_m3_m3m3(), mul_v3_fl(), mul_v3_m4v3(), VFont::name, normalize_v3(), NULL, Curve::nurb, OB_CURVE, OB_FONT, Object::obmat, Curve::path, Curve::pos, Curve::selboxes, Curve::sepchar, si, sin(), Curve::spacemode, Curve::spacing, Curve::str, Curve::strinfo, Curve::tb, EditFont::textbufinfo, EditFont::textcurs, Curve::textoncurve, Curve::totbox, Object::totcol, Path::totdist, Object::type, Curve::ulheight, Curve::ulpos, Curve::vfont, vfont_get_data(), SelBox::w, TextBox::w, where_on_path(), which_vfont(), Curve::wordspace, SelBox::x, TextBox::x, Curve::xof, chartrans::xof, SelBox::y, TextBox::y, Curve::yof, and chartrans::yof.
Referenced by copy_attr(), do_makeDispListCurveTypes(), font_duplilist(), move_cursor(), and text_update_edited().
static void build_underline (Curve * cu, float x1, float y1, float x2, float y2, int charidx, short mat_nr) [static]
Definition at line 317 of file font.c.
References Nurb::bezt, BLI_addtail(), Nurb::bp, Nurb::charidx, CU_2D, CU_NURB_CYCLIC, Nurb::flag, Nurb::flagu, Nurb::knotsu, Nurb::knotsv, Nurb::mat_nr, MEM_callocN(), MEM_freeN(), NULL, Curve::nurb, Nurb::orderu, Nurb::orderv, Nurb::pntsu, Nurb::pntsv, Nurb::resolu, Curve::resolu, and BPoint::vec.
Referenced by BKE_text_to_curve().
static void buildchar (Main * bmain, Curve * cu, unsigned long character, CharInfo * info, float ofsx, float ofsy, float rot, int charidx) [static]
Definition at line 364 of file font.c.
References Nurb::bezt, BLI_addtail(), co, cos(), CU_CHINFO_SMALLCAPS_CHECK, CU_SMOOTH, find_vfont_char(), ListBase::first, CharInfo::flag, Curve::fsize, i, CharInfo::mat_nr, MEM_freeN(), MEM_mallocN(), Nurb::next, NULL, Curve::nurb, VChar::nurbsbase, Curve::resolu, Curve::selend, Curve::selstart, Curve::shear, si, sin(), Curve::smallcaps_scale, BezTriple::vec, vfont_get_data(), and which_vfont().
Referenced by BKE_text_to_curve().
static float char_width (Curve * cu, VChar * che, CharInfo * info) [static]
Definition at line 512 of file font.c.
References CU_CHINFO_SMALLCAPS_CHECK, CharInfo::flag, NULL, Curve::smallcaps_scale, and VChar::width.
Referenced by BKE_text_to_curve().
static VChar* find_vfont_char (VFontData * vfd, intptr_t character) [static]
Definition at line 306 of file font.c.
References VFontData::characters, ListBase::first, VChar::index, VChar::next, and NULL.
Referenced by BKE_text_to_curve(), and buildchar().
void free_ttfont (void)
Definition at line 119 of file font.c.
References BLI_freelistN(), ListBase::first, freePackedFile(), TmpFont::next, NULL, TmpFont::pf, and TmpFont::vfont.
Referenced by WM_exit_ext(), and WM_read_homefile().
void free_vfont (struct VFont * vf)
Definition at line 66 of file font.c.
References Nurb::bezt, BLI_freelinkN(), VFontData::characters, VFont::data, ListBase::first, freePackedFile(), MEM_freeN(), NULL, VChar::nurbsbase, and VFont::packedfile.
Referenced by free_libblock().
VFont* get_builtin_font (void) [read]
Definition at line 295 of file font.c.
References FO_BUILTIN_NAME, G, VFont::id, load_vfont(), VFont::name, and ID::next.
Referenced by add_curve(), font_unlink_exec(), and txt_add_object().
static PackedFile* get_builtin_packedfile (void) [static]
Definition at line 103 of file font.c.
References builtin_font_data, builtin_font_size, MEM_mallocN(), newPackedFileMemory(), and NULL.
Referenced by load_vfont(), and vfont_get_data().
VFont* load_vfont (Main * bmain, const char * name) [read]
Definition at line 215 of file font.c.
References alloc_libblock(), BLI_addtail(), BLI_splitdirstring(), BLI_strncpy(), BLI_vfontdata_from_freetypefont(), VFont::data, FILE_MAXDIR, FILE_MAXFILE, FO_BUILTIN_NAME, freePackedFile(), G, G_AUTOPACK, get_builtin_packedfile(), VFont::id, ID_VF, MEM_callocN(), VFont::name, ID::name, VFontData::name, Main::name, newPackedFile(), NULL, VFont::packedfile, TmpFont::pf, pf, Main::vfont, and TmpFont::vfont.
Referenced by font_open_exec(), and get_builtin_font().
struct TmpFont* vfont_find_tmpfont (VFont * vfont) [read]
Definition at line 131 of file font.c.
References ListBase::first, TmpFont::next, NULL, and TmpFont::vfont.
Referenced by objchr_to_ftvfontdata(), and vfont_get_data().
static VFontData* vfont_get_data (Main * bmain, VFont * vfont) [static]
Definition at line 148 of file font.c.
References BLI_addtail(), BLI_vfontdata_from_freetypefont(), PackedFile::data, VFont::data, FO_BUILTIN_NAME, freePackedFile(), get_builtin_packedfile(), VFont::id, ID_BLEND_PATH, MEM_callocN(), MEM_mallocN(), VFont::name, newPackedFile(), NULL, VFont::packedfile, TmpFont::pf, pf, PackedFile::size, TmpFont::vfont, and vfont_find_tmpfont().
Referenced by BKE_text_to_curve(), and buildchar().
static VFont* which_vfont (Curve * cu, CharInfo * info) [static]
Definition at line 281 of file font.c.
References CU_CHINFO_BOLD, CU_CHINFO_ITALIC, CharInfo::flag, Curve::vfont, Curve::vfontb, Curve::vfontbi, and Curve::vfonti.
Referenced by BKE_text_to_curve(), and buildchar().
Variable Documentation
void* builtin_font_data = NULL [static]
Definition at line 94 of file font.c.
Referenced by BKE_font_register_builtin(), and get_builtin_packedfile().
int builtin_font_size = 0 [static]
Definition at line 95 of file font.c.
Referenced by BKE_font_register_builtin(), and get_builtin_packedfile().
ListBase ttfdata = {NULL, NULL} [static]
Definition at line 63 of file font.c.