Blender: MOD_array.c File Reference
MOD_array.c File Reference
modifiers
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BLI_string.h"
#include "BLI_ghash.h"
#include "BLI_edgehash.h"
#include "DNA_curve_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_displist.h"
#include "BKE_mesh.h"
#include "BKE_modifier.h"
#include "BKE_object.h"
#include "BKE_tessmesh.h"
#include "depsgraph_private.h"
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
Defines
#define _E(s, i) ((BMVert **)(s)->data.buf)[i]
Functions
static void initData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static void foreachObjectLink (ModifierData *md, Object *ob, void(*walk)(void *userData, Object *ob, Object **obpoin), void *userData)
static void updateDepgraph (ModifierData *md, DagForest *forest, struct Scene *UNUSED(scene), Object *UNUSED(ob), DagNode *obNode)
static float vertarray_size (MVert *mvert, int numVerts, int axis)
static int * find_doubles_index_map (BMesh *bm, BMOperator *dupe_op, const ArrayModifierData *amd, int *index_map_length)
static void bm_merge_dm_transform (BMesh *bm, DerivedMesh *dm, float mat[4][4], const ArrayModifierData *amd, BMOperator *dupe_op, const char *dupe_slot_name, BMOperator *weld_op)
static void merge_first_last (BMesh *bm, const ArrayModifierData *amd, BMOperator *dupe_first, BMOperator *dupe_last, BMOperator *weld_op)
static DerivedMesh * arrayModifier_doArray (ArrayModifierData *amd, Scene *scene, Object *ob, DerivedMesh *dm, int UNUSED(initFlags))
static DerivedMesh * applyModifier (ModifierData *md, Object *ob, DerivedMesh *dm, int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
static DerivedMesh * applyModifierEM (ModifierData *md, Object *ob, struct BMEditMesh *UNUSED(editData), DerivedMesh *dm)
Variables
ModifierTypeInfo modifierType_Array
Detailed Description
Definition in file MOD_array.c.
Define Documentation
#define _E (s, i) ((BMVert **)(s)->data.buf)[i]
Referenced by arrayModifier_doArray().
Function Documentation
static DerivedMesh* applyModifier (ModifierData * md, Object * ob, DerivedMesh * dm, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 544 of file MOD_array.c.
References arrayModifier_doArray(), and ModifierData::scene.
Referenced by applyModifierEM().
static DerivedMesh* applyModifierEM (ModifierData * md, Object * ob, struct BMEditMesh * UNUSEDeditData, DerivedMesh * dm) [static]
Definition at line 560 of file MOD_array.c.
References applyModifier().
static DerivedMesh* arrayModifier_doArray (ArrayModifierData * amd, Scene * scene, Object * ob, DerivedMesh * dm, int UNUSEDinitFlags) [static]
Definition at line 300 of file MOD_array.c.
References _E, add_v3_v3v3(), BLI_assert, BMEditMesh::bm, BM_ELEM_TAG, bm_merge_dm_transform(), BM_mesh_elem_hflag_enable_all(), BM_VERT, BMEdit_Free(), bmesh_edit_begin(), BMO_ITER, BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_op_initf(), BMO_pop(), BMO_push(), BMO_slot_get(), BMO_slot_map_ptr_get(), BMO_slot_map_ptr_insert(), BMOpSlot::buf, CD_MASK_MESH, CDDM_calc_normals(), CDDM_from_BMEditMesh(), BMVert::co, copy_m4_m4(), ArrayModifierData::count, CU_PATH, ArrayModifierData::curve_ob, Object::data, BMOpSlot::data, DM_to_editbmesh(), dot_v3v3(), ArrayModifierData::end_cap, FALSE, find_doubles_index_map(), ArrayModifierData::fit_type, Curve::flag, ArrayModifierData::flags, DerivedMesh::getNumVerts, DerivedMesh::getVertArray, i, invert_m4_m4(), BMOpSlot::len, ArrayModifierData::length, length(), BMEditMesh::looptris, makeDispListCurveTypes(), mat3_to_scale(), MEM_freeN(), MEM_mallocN(), merge_first_last(), mesh_get_derived_final(), MOD_ARR_FITCURVE, MOD_ARR_FITLENGTH, MOD_ARR_MERGE, MOD_ARR_MERGEFINAL, MOD_ARR_OFF_CONST, MOD_ARR_OFF_OBJ, MOD_ARR_OFF_RELATIVE, mul_m4_v3(), mul_serie_m4(), mult_m4_m4m4(), NULL, object_to_mat3(), Object::obmat, ArrayModifierData::offset, ArrayModifierData::offset_ob, ArrayModifierData::offset_type, Curve::path, ArrayModifierData::scale, sqrt(), ArrayModifierData::start_cap, Path::totdist, unit_m4(), and vertarray_size().
Referenced by applyModifier().
static void bm_merge_dm_transform (BMesh * bm, DerivedMesh * dm, float mat[4][4], const ArrayModifierData * amd, BMOperator * dupe_op, const char * dupe_slot_name, BMOperator * weld_op) [static]
Definition at line 217 of file MOD_array.c.
References BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_TAG, BM_ITER_MESH, BM_VERTS_OF_MESH, BMO_ITER, BMO_iter_map_value_p(), BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_append(), BMO_slot_map_ptr_insert(), BMVert::co, DM_to_bmesh_ex(), ArrayModifierData::flags, ArrayModifierData::merge_dist, MOD_ARR_MERGE, and mul_m4_v3().
Referenced by arrayModifier_doArray().
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 83 of file MOD_array.c.
References copy_v3_v3(), ArrayModifierData::count, ArrayModifierData::curve_ob, ArrayModifierData::end_cap, ArrayModifierData::fit_type, ArrayModifierData::flags, ArrayModifierData::length, ArrayModifierData::merge_dist, ArrayModifierData::offset, ArrayModifierData::offset_ob, ArrayModifierData::offset_type, ArrayModifierData::scale, and ArrayModifierData::start_cap.
static int* find_doubles_index_map (BMesh * bm, BMOperator * dupe_op, const ArrayModifierData * amd, int * index_map_length) [static]
Definition at line 165 of file MOD_array.c.
References BM_ALL, BM_EDGE, BM_elem_index_get, BM_elem_index_set, BM_FACE, BM_VERT, BMO_ITER, BMO_iter_map_value_p(), BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMesh::elem_index_dirty, i, MEM_callocN(), and ArrayModifierData::merge_dist.
Referenced by arrayModifier_doArray().
static void foreachObjectLink (ModifierData * md, Object * ob, void(*)(void *userData, Object *ob, Object **obpoin) walk, void * userData) [static]
Definition at line 102 of file MOD_array.c.
References ArrayModifierData::curve_ob, ArrayModifierData::end_cap, ArrayModifierData::offset_ob, and ArrayModifierData::start_cap.
static void initData (ModifierData * md) [static]
Definition at line 64 of file MOD_array.c.
References ArrayModifierData::count, ArrayModifierData::curve_ob, ArrayModifierData::end_cap, ArrayModifierData::fit_type, ArrayModifierData::flags, ArrayModifierData::length, ArrayModifierData::merge_dist, MOD_ARR_FIXEDCOUNT, MOD_ARR_OFF_RELATIVE, NULL, ArrayModifierData::offset, ArrayModifierData::offset_ob, ArrayModifierData::offset_type, ArrayModifierData::scale, ArrayModifierData::start_cap, and zero_v3().
static void merge_first_last (BMesh * bm, const ArrayModifierData * amd, BMOperator * dupe_first, BMOperator * dupe_last, BMOperator * weld_op) [static]
Definition at line 271 of file MOD_array.c.
References BMO_ITER, BMO_iter_map_value_p(), BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_append(), BMO_slot_map_ptr_insert(), and ArrayModifierData::merge_dist.
Referenced by arrayModifier_doArray().
static void updateDepgraph (ModifierData * md, DagForest * forest, struct Scene * UNUSEDscene, Object * UNUSEDob, DagNode * obNode) [static]
Definition at line 115 of file MOD_array.c.
References ArrayModifierData::curve_ob, dag_add_relation(), dag_get_node(), DAG_RL_DATA_DATA, DAG_RL_OB_DATA, ArrayModifierData::end_cap, ArrayModifierData::offset_ob, and ArrayModifierData::start_cap.
static float vertarray_size (MVert * mvert, int numVerts, int axis) [static]
Definition at line 146 of file MOD_array.c.
References MVert::co, and i.
Referenced by arrayModifier_doArray().
Variable Documentation
ModifierTypeInfo modifierType_Array
Initial value:
 {
                  "Array",
            "ArrayModifierData",
            sizeof(ArrayModifierData),
                  eModifierTypeType_Constructive,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_SupportsMapping
                            | eModifierTypeFlag_SupportsEditmode
                            | eModifierTypeFlag_EnableInEditmode
                            | eModifierTypeFlag_AcceptsCVs,
              copyData,
           NULL,
        NULL,
         NULL,
      NULL,
         applyModifier,
       applyModifierEM,
              initData,
      NULL,
              NULL,
            NULL,
        updateDepgraph,
         NULL,
        NULL,
     foreachObjectLink,
         NULL,
        NULL,
}
Definition at line 568 of file MOD_array.c.