Blender: PHY_IController Class Reference
PHY_IController Class Reference
#include <PHY_IController.h>
Public Member Functions
virtual ~PHY_IController ()
virtual void * getNewClientInfo ()=0
virtual void setNewClientInfo (void *clientinfo)=0
virtual void SetPhysicsEnvironment (class PHY_IPhysicsEnvironment *env)=0
Detailed Description
PHY_IController is the abstract simplified Interface to objects controlled by the physics engine. This includes the physics objects and the graphics object for view frustrum and occlusion culling.
Definition at line 48 of file PHY_IController.h.
Constructor & Destructor Documentation
PHY_IController::~PHY_IController () [virtual]
Definition at line 34 of file PHY_IController.cpp.
Member Function Documentation
virtual void* PHY_IController::getNewClientInfo () [pure virtual]
Implemented in CcdGraphicController, and CcdPhysicsController.
Referenced by KX_TouchSensor::BroadPhaseSensorFilterCollision(), KX_RayCast::Callback< T >::needBroadphaseRayCast(), KX_NearSensor::NewHandleCollision(), KX_TouchSensor::NewHandleCollision(), KX_TouchEventManager::NextFrame(), KX_RayCast::RayTest(), KX_TouchSensor::RegisterSumo(), and KX_TouchSensor::UnregisterSumo().
virtual void PHY_IController::setNewClientInfo (void * clientinfo) [pure virtual]
Implemented in CcdGraphicController, and CcdPhysicsController.
Referenced by KX_Scene::AddNodeReplicaObject(), KX_NearSensor::KX_NearSensor(), and KX_NearSensor::ProcessReplica().
virtual void PHY_IController::SetPhysicsEnvironment (class PHY_IPhysicsEnvironment * env) [pure virtual]
Implemented in CcdGraphicController, and CcdPhysicsController.
Referenced by MergeScene_GameObject(), and MergeScene_LogicBrick().
The documentation for this class was generated from the following files:
PHY_IController.h
PHY_IController.cpp