Blender: BKE_screen.h File Reference
BKE_screen.h File Reference
blenkernel
#include "RNA_types.h"
Classes
struct SpaceType
struct ARegionType
struct PanelType
struct HeaderType
struct Header
struct MenuType
struct Menu
Defines
#define BKE_ST_MAXNAME 64
Typedefs
typedef struct SpaceType SpaceType
typedef struct ARegionType ARegionType
typedef struct PanelType PanelType
typedef struct HeaderType HeaderType
typedef struct Header Header
typedef struct MenuType MenuType
typedef struct Menu Menu
Functions
struct SpaceType * BKE_spacetype_from_id (int spaceid)
struct ARegionType * BKE_regiontype_from_id (struct SpaceType *st, int regionid)
struct ListBase * BKE_spacetypes_list (void)
void BKE_spacetype_register (struct SpaceType *st)
void BKE_spacetypes_free (void)
void BKE_spacedata_freelist (ListBase *lb)
void BKE_spacedata_copylist (ListBase *lb1, ListBase *lb2)
void BKE_spacedata_draw_locks (int set)
struct ARegion * BKE_area_region_copy (struct SpaceType *st, struct ARegion *ar)
void BKE_area_region_free (struct SpaceType *st, struct ARegion *ar)
void BKE_screen_area_free (struct ScrArea *sa)
struct ARegion * BKE_area_find_region_type (struct ScrArea *sa, int type)
struct ScrArea * BKE_screen_find_big_area (struct bScreen *sc, const int spacetype, const short min)
void BKE_screen_view3d_sync (struct View3D *v3d, struct Scene *scene)
void BKE_screen_view3d_scene_sync (struct bScreen *sc)
void BKE_screen_view3d_main_sync (ListBase *screen_lb, struct Scene *scene)
float BKE_screen_view3d_zoom_to_fac (float camzoom)
float BKE_screen_view3d_zoom_from_fac (float zoomfac)
void free_screen (struct bScreen *sc)
unsigned int BKE_screen_visible_layers (struct bScreen *screen, struct Scene *scene)
Detailed Description
Since:
March 2001
Author:
nzc
Definition in file BKE_screen.h.
Define Documentation
#define BKE_ST_MAXNAME 64
Definition at line 61 of file BKE_screen.h.
Referenced by ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), wm_call_menu_exec(), and WM_OT_call_menu().
Typedef Documentation
typedef struct ARegionType ARegionType
typedef struct Header Header
typedef struct HeaderType HeaderType
typedef struct Menu Menu
typedef struct MenuType MenuType
typedef struct PanelType PanelType
typedef struct SpaceType SpaceType
Function Documentation
struct ARegion* BKE_area_find_region_type (struct ScrArea * sa, int type) [read]
Definition at line 343 of file screen.c.
References ListBase::first, ARegion::next, NULL, ScrArea::regionbase, and ARegion::regiontype.
Referenced by blend_file_thumb(), clip_has_preview_region(), clip_has_properties_region(), clip_has_tools_region(), clip_refresh(), ed_default_handlers(), ED_undo_operator_repeat(), ED_view3d_context_rv3d(), file_smoothscroll_invoke(), graph_has_buttons_region(), header_flip_exec(), image_has_buttons_region(), image_has_scope_region(), logic_has_buttons_region(), nla_has_buttons_region(), node_has_buttons_region(), sequencer_has_buttons_region(), text_has_properties_region(), time_refresh(), UI_view2d_fromcontext_rwin(), view3d_has_buttons_region(), view3d_main_area_draw_objects(), WM_init_game(), wm_keymap_item_find_props(), and wm_operator_call_internal().
struct ARegion* BKE_area_region_copy (struct SpaceType * st, struct ARegion * ar) [read]
Definition at line 162 of file screen.c.
References BKE_regiontype_from_id(), BLI_duplicatelist(), ARegionType::duplicate, ListBase::first, ARegion::handlers, ListBase::last, MEM_dupallocN(), Panel::next, ARegion::next, NULL, ARegion::panels, Panel::paneltab, ARegion::prev, ARegion::regiondata, ARegion::regiontype, ARegion::swinid, View2D::tab_offset, ARegion::uiblocks, and ARegion::v2d.
Referenced by area_copy_data(), region_copylist(), and region_quadview_exec().
void BKE_area_region_free (struct SpaceType * st, struct ARegion * ar)
Definition at line 262 of file screen.c.
References BKE_regiontype_from_id(), BLI_freelistN(), ARegionType::free, MEM_freeN(), NULL, ARegion::panels, ARegion::regiondata, ARegion::regiontype, View2D::tab_offset, ARegion::type, and ARegion::v2d.
Referenced by area_copy_data(), BKE_screen_area_free(), BKE_spacedata_freelist(), do_versions(), free_screen(), region_quadview_exec(), and ui_remove_temporary_region().
struct ARegionType* BKE_regiontype_from_id (struct SpaceType * st, int regionid) [read]
Definition at line 106 of file screen.c.
References ListBase::first, SpaceType::name, ARegionType::next, ARegionType::regionid, SpaceType::regiontypes, and SpaceType::spaceid.
Referenced by BKE_area_region_copy(), BKE_area_region_free(), ED_area_initialize(), and screen_refresh_headersizes().
void BKE_screen_area_free (struct ScrArea * sa)
Definition at line 285 of file screen.c.
References ScrArea::actionzones, BKE_area_region_free(), BKE_spacedata_freelist(), BKE_spacetype_from_id(), BLI_freelistN(), ListBase::first, ARegion::next, ScrArea::regionbase, ScrArea::spacedata, and ScrArea::spacetype.
Referenced by ED_area_swapspace(), free_screen(), and screen_delarea().
struct ScrArea* BKE_screen_find_big_area (struct bScreen * sc, const int spacetype, const short min) [read]
Definition at line 359 of file screen.c.
References bScreen::areabase, ListBase::first, ScrArea::next, NULL, size(), ScrArea::spacetype, ScrArea::winx, and ScrArea::winy.
Referenced by blend_file_thumb(), init_bake_internal(), render_view_open(), and WM_init_game().
void BKE_screen_view3d_main_sync (ListBase * screen_lb, struct Scene * scene)
Definition at line 425 of file screen.c.
References bScreen::areabase, BKE_screen_view3d_sync(), ListBase::first, bScreen::id, SpaceLink::next, ScrArea::next, ID::next, bScreen::scene, SPACE_VIEW3D, ScrArea::spacedata, and SpaceLink::spacetype.
Referenced by handle_view3d_lock().
void BKE_screen_view3d_scene_sync (struct bScreen * sc)
Definition at line 410 of file screen.c.
References bScreen::areabase, BKE_screen_view3d_sync(), ListBase::first, SpaceLink::next, ScrArea::next, bScreen::scene, SPACE_VIEW3D, ScrArea::spacedata, and SpaceLink::spacetype.
Referenced by ED_update_for_newframe().
void BKE_screen_view3d_sync (struct View3D * v3d, struct Scene * scene)
Definition at line 379 of file screen.c.
References Scene::camera, View3D::camera, ListBase::first, Scene::lay, View3D::lay, View3D::layact, View3D::localvd, ARegion::next, NULL, RegionView3D::persp, View3D::regionbase, ARegion::regiondata, ARegion::regiontype, RGN_TYPE_WINDOW, RV3D_CAMOB, RV3D_PERSP, and View3D::scenelock.
Referenced by BKE_screen_view3d_main_sync(), BKE_screen_view3d_scene_sync(), and ED_screen_set_scene().
float BKE_screen_view3d_zoom_from_fac (float zoomfac)
Definition at line 456 of file screen.c.
References M_SQRT2, and sqrtf.
Referenced by view3d_center_camera_exec(), and view3d_set_1_to_1_viewborder().
float BKE_screen_view3d_zoom_to_fac (float camzoom)
Definition at line 451 of file screen.c.
Referenced by camera_params_from_view3d(), StartKetsjiShell(), and viewmove_apply().
unsigned int BKE_screen_visible_layers (struct bScreen * screen, struct Scene * scene)
Definition at line 322 of file screen.c.
References bScreen::areabase, ListBase::first, Scene::lay, ScrArea::next, SPACE_VIEW3D, ScrArea::spacedata, and ScrArea::spacetype.
Referenced by dag_current_scene_layers(), and ED_update_for_newframe().
void BKE_spacedata_copylist (ListBase * lb1, ListBase * lb2)
Definition at line 222 of file screen.c.
References BKE_spacetype_from_id(), BLI_addtail(), SpaceType::duplicate, ListBase::first, ListBase::last, SpaceLink::next, NULL, region_copylist(), SpaceLink::regionbase, and SpaceLink::spacetype.
Referenced by area_copy_data().
void BKE_spacedata_draw_locks (int set)
Definition at line 244 of file screen.c.
References ARegionType::do_lock, ListBase::first, ARegionType::lock, ARegionType::next, SpaceType::next, and SpaceType::regiontypes.
Referenced by render_drawlock().
void BKE_spacedata_freelist (ListBase * lb)
Definition at line 141 of file screen.c.
References BKE_area_region_free(), BKE_spacetype_from_id(), BLI_freelistN(), ListBase::first, SpaceType::free, ARegion::next, SpaceLink::next, SpaceLink::regionbase, and SpaceLink::spacetype.
Referenced by area_copy_data(), BKE_screen_area_free(), and spacedata_cleanup().
struct SpaceType* BKE_spacetype_from_id (int spaceid) [read]
Definition at line 95 of file screen.c.
References ListBase::first, SpaceType::next, NULL, and SpaceType::spaceid.
Referenced by area_copy_data(), BKE_screen_area_free(), BKE_spacedata_copylist(), BKE_spacedata_freelist(), BKE_spacetype_register(), do_versions(), ED_area_initialize(), ED_area_newspace(), and view3d_panel_tool_shelf().
void BKE_spacetype_register (struct SpaceType * st)
Definition at line 124 of file screen.c.
References BKE_spacetype_from_id(), BLI_addtail(), MEM_freeN(), SpaceType::name, SpaceType::spaceid, and spacetype_free().
Referenced by ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), and ED_spacetype_xxx().
void BKE_spacetypes_free (void)
Definition at line 84 of file screen.c.
References BLI_freelistN(), ListBase::first, SpaceType::next, and spacetype_free().
Referenced by free_blender().
struct ListBase* BKE_spacetypes_list (void) [read]
Definition at line 119 of file screen.c.
References spacetypes.
Referenced by ED_spacetypes_init(), ED_spacetypes_keymap(), and screen_refresh_headersizes().
void free_screen (struct bScreen * sc)
Definition at line 301 of file screen.c.
References bScreen::areabase, BKE_area_region_free(), BKE_screen_area_free(), BLI_freelistN(), bScreen::edgebase, ListBase::first, ScrArea::next, ARegion::next, NULL, bScreen::regionbase, and bScreen::vertbase.
Referenced by ED_screen_full_toggle(), free_libblock(), and screen_copy().