Blender: bmesh_py_types_select.h File Reference
bmesh_py_types_select.h File Reference
Classes
struct BPy_BMEditSelSeq
struct BPy_BMEditSelIter
Defines
#define BPy_BMSelectHistory_Check(v) (Py_TYPE(v) == &BPy_BMEditSelSeq_Type)
#define BPy_BMSelectHistoryIter_Check(v) (Py_TYPE(v) == &BPy_BMEditSelIter_Type)
Typedefs
typedef struct BPy_BMEditSelSeq BPy_BMEditSelSeq
typedef struct BPy_BMEditSelIter BPy_BMEditSelIter
Functions
void BPy_BM_init_types_select (void)
PyObject * BPy_BMEditSel_CreatePyObject (BMesh *bm)
PyObject * BPy_BMEditSelIter_CreatePyObject (BMesh *bm)
int BPy_BMEditSel_Assign (struct BPy_BMesh *self, PyObject *value)
Variables
PyTypeObject BPy_BMEditSelSeq_Type
PyTypeObject BPy_BMEditSelIter_Type
Detailed Description
Definition in file bmesh_py_types_select.h.
Define Documentation
#define BPy_BMSelectHistory_Check (v) (Py_TYPE(v) == &BPy_BMEditSelSeq_Type)
Definition at line 38 of file bmesh_py_types_select.h.
#define BPy_BMSelectHistoryIter_Check (v) (Py_TYPE(v) == &BPy_BMEditSelIter_Type)
Definition at line 39 of file bmesh_py_types_select.h.
Typedef Documentation
typedef struct BPy_BMEditSelIter BPy_BMEditSelIter
typedef struct BPy_BMEditSelSeq BPy_BMEditSelSeq
Function Documentation
void BPy_BM_init_types_select (void)
Definition at line 382 of file bmesh_py_types_select.c.
References bpy_bmeditseliter_next(), bpy_bmeditselseq_as_mapping, bpy_bmeditselseq_as_sequence, bpy_bmeditselseq_getseters, bpy_bmeditselseq_iter(), bpy_bmeditselseq_methods, and NULL.
Referenced by BPyInit_bmesh().
int BPy_BMEditSel_Assign (BPy_BMesh * self, PyObject * value)
Note:
doesn't actually check selection.
Definition at line 427 of file bmesh_py_types_select.c.
References BM_EDGE, BM_FACE, BM_select_history_clear(), BM_select_history_store_notest, BM_VERT, BPY_BM_CHECK_INT, BPy_BMElem_PySeq_As_Array(), i, NULL, and TRUE.
Referenced by bpy_bmesh_select_history_set().
PyObject* BPy_BMEditSel_CreatePyObject (BMesh * bm)
Definition at line 366 of file bmesh_py_types_select.c.
Referenced by bpy_bmesh_select_history_get().
PyObject* BPy_BMEditSelIter_CreatePyObject (BMesh * bm)
Definition at line 374 of file bmesh_py_types_select.c.
Referenced by bpy_bmeditselseq_iter().
Variable Documentation
PyTypeObject BPy_BMEditSelIter_Type
Definition at line 363 of file bmesh_py_types_select.c.
Referenced by BPyInit_bmesh_types().
PyTypeObject BPy_BMEditSelSeq_Type
Definition at line 362 of file bmesh_py_types_select.c.
Referenced by BPyInit_bmesh_types().