Blender: Film Class Reference
Film Class Reference
#include <film.h>
Public Member Functions
Film ()
~Film ()
void device_update (Device *device, DeviceScene *dscene)
void device_free (Device *device, DeviceScene *dscene)
bool modified (const Film &film)
void tag_update (Scene *scene)
Public Attributes
float exposure
vector< Pass > passes
bool need_update
Detailed Description
Definition at line 45 of file film.h.
Constructor & Destructor Documentation
Film::Film ()
Definition at line 159 of file film.cpp.
References add(), exposure, need_update, PASS_COMBINED, and passes.
Film::~Film ()
Definition at line 166 of file film.cpp.
Member Function Documentation
void Film::device_free (Device * device, DeviceScene * dscene)
Definition at line 267 of file film.cpp.
Referenced by Scene::~Scene().
void Film::device_update (Device * device, DeviceScene * dscene)
Definition at line 170 of file film.cpp.
References align_up(), Pass::components, DeviceScene::data, KernelFilm::exposure, exposure, KernelData::film, need_update, PASS_AO, KernelFilm::pass_ao, PASS_BACKGROUND, KernelFilm::pass_background, KernelFilm::pass_combined, PASS_COMBINED, PASS_DEPTH, KernelFilm::pass_depth, PASS_DIFFUSE_COLOR, KernelFilm::pass_diffuse_color, PASS_DIFFUSE_DIRECT, KernelFilm::pass_diffuse_direct, KernelFilm::pass_diffuse_indirect, PASS_DIFFUSE_INDIRECT, PASS_EMISSION, KernelFilm::pass_emission, KernelFilm::pass_flag, KernelFilm::pass_glossy_color, PASS_GLOSSY_COLOR, PASS_GLOSSY_DIRECT, KernelFilm::pass_glossy_direct, KernelFilm::pass_glossy_indirect, PASS_GLOSSY_INDIRECT, KernelFilm::pass_material_id, PASS_MATERIAL_ID, PASS_NONE, KernelFilm::pass_normal, PASS_NORMAL, PASS_OBJECT_ID, KernelFilm::pass_object_id, KernelFilm::pass_shadow, PASS_SHADOW, KernelFilm::pass_stride, KernelFilm::pass_transmission_color, PASS_TRANSMISSION_COLOR, KernelFilm::pass_transmission_direct, PASS_TRANSMISSION_DIRECT, KernelFilm::pass_transmission_indirect, PASS_TRANSMISSION_INDIRECT, KernelFilm::pass_uv, PASS_UV, passes, Pass::type, and KernelFilm::use_light_pass.
Referenced by Scene::device_update().
bool Film::modified (const Film & film)
Definition at line 271 of file film.cpp.
References Pass::equals(), exposure, and passes.
void Film::tag_update (Scene * scene)
Definition at line 277 of file film.cpp.
References Scene::integrator, need_update, and Integrator::tag_update().
Referenced by BlenderSession::render().
Member Data Documentation
float Film::exposure
Definition at line 47 of file film.h.
Referenced by device_update(), Film(), modified(), and BlenderSession::write_render_result().
bool Film::need_update
Definition at line 49 of file film.h.
Referenced by device_update(), Film(), Scene::need_update(), and tag_update().
vector<Pass> Film::passes
Definition at line 48 of file film.h.
Referenced by device_update(), Film(), modified(), and BlenderSession::render().
The documentation for this class was generated from the following files:
film.h
film.cpp