Blender: sculpt_intern.h File Reference
sculpt_intern.h File Reference
sculpt and paint
#include "DNA_listBase.h"
#include "DNA_vec_types.h"
#include "DNA_key_types.h"
#include "BLI_bitmap.h"
#include "BLI_pbvh.h"
Classes
struct SculptUndoNode
Typedefs
typedef struct SculptUndoNode SculptUndoNode
Enumerations
enum SculptUndoType { SCULPT_UNDO_COORDS, SCULPT_UNDO_HIDDEN }
Functions
struct MultiresModifierData * sculpt_multires_active (struct Scene *scene, struct Object *ob)
void sculpt (Sculpt *sd)
int sculpt_mode_poll (struct bContext *C)
int sculpt_poll (struct bContext *C)
void sculpt_update_mesh_elements (struct Scene *scene, struct Sculpt *sd, struct Object *ob, int need_pmap)
void free_sculptsession_deformMats (struct SculptSession *ss)
int sculpt_stroke_get_location (bContext *C, float out[3], float mouse[2])
SculptUndoNode * sculpt_undo_push_node (Object *ob, PBVHNode *node, SculptUndoType type)
SculptUndoNode * sculpt_undo_get_node (PBVHNode *node)
void sculpt_undo_push_begin (const char *name)
void sculpt_undo_push_end (void)
void sculpt_vertcos_to_key (Object *ob, KeyBlock *kb, float(*vertCos)[3])
Detailed Description
Definition in file sculpt_intern.h.
Typedef Documentation
typedef struct SculptUndoNode SculptUndoNode
Enumeration Type Documentation
enum SculptUndoType
Enumerator:
SCULPT_UNDO_COORDS
SCULPT_UNDO_HIDDEN
Definition at line 70 of file sculpt_intern.h.
Function Documentation
void free_sculptsession_deformMats (struct SculptSession * ss)
Definition at line 267 of file object.c.
References SculptSession::deform_cos, SculptSession::deform_imats, MEM_freeN(), NULL, and SculptSession::orig_cos.
void sculpt (Sculpt * sd)
int sculpt_mode_poll (struct bContext * C)
Definition at line 2737 of file sculpt.c.
References CTX_data_active_object(), Object::mode, and OB_MODE_SCULPT.
Referenced by PAINT_OT_hide_show(), SCULPT_OT_set_persistent_base(), and sculpt_poll().
struct MultiresModifierData* sculpt_multires_active (struct Scene * scene, struct Object * ob) [read]
Definition at line 106 of file sculpt.c.
References CD_MDISPS, CustomData_get_layer(), Object::data, eModifierMode_Realtime, eModifierType_Multires, if(), Mesh::ldata, modifier_isEnabled(), modifiers_getVirtualModifierList(), ModifierData::next, NULL, and MultiresModifierData::sculptlvl.
Referenced by sculpt_modifiers_active(), sculpt_toggle_mode(), sculpt_undo_restore(), and sculpt_update_mesh_elements().
int sculpt_poll (struct bContext * C)
Definition at line 2743 of file sculpt.c.
References paint_poll(), and sculpt_mode_poll().
Referenced by ED_keymap_paint(), SCULPT_OT_brush_stroke(), and sculpt_toggle_mode().
int sculpt_stroke_get_location (bContext * C, float out[3], float mouse[2])
Definition at line 3214 of file sculpt.c.
References add_v3_v3(), ViewContext::ar, BLI_pbvh_raycast(), SculptSession::cache, copy_v3_v3(), SculptRaycastData::dist, ED_view3d_win_to_segment_clip(), SculptRaycastData::hit, invert_m4_m4(), mul_m4_v3(), mul_v3_fl(), normalize_v3(), ViewContext::obact, Object::obmat, StrokeCache::original, SculptRaycastData::original, SculptSession::pbvh, SculptRaycastData::ray_normal, SculptRaycastData::ray_start, Object::sculpt, sculpt_raycast_cb(), sculpt_stroke_modifiers_check(), SculptRaycastData::ss, sub_v3_v3v3(), ViewContext::v3d, view3d_set_viewcontext(), ARegion::winrct, rcti::xmin, and rcti::ymin.
Referenced by over_mesh(), sculpt_brush_stroke_exec(), sculpt_brush_stroke_invoke(), sculpt_get_brush_geometry(), and sculpt_update_cache_variants().
SculptUndoNode* sculpt_undo_get_node (PBVHNode * node)
Definition at line 322 of file sculpt_undo.c.
References ListBase::first, SculptUndoNode::next, SculptUndoNode::node, NULL, UNDO_PAINT_MESH, and undo_paint_push_get_list().
Referenced by sculpt_raycast_cb(), sculpt_restore_mesh(), and sculpt_undo_push_node().
void sculpt_undo_push_begin (const char * name)
Definition at line 505 of file sculpt_undo.c.
References sculpt_undo_free(), sculpt_undo_restore(), UNDO_PAINT_MESH, and undo_paint_push_begin().
Referenced by hide_show_exec(), and sculpt_stroke_test_start().
void sculpt_undo_push_end (void)
Definition at line 511 of file sculpt_undo.c.
References ListBase::first, SculptUndoNode::layer_disp, MEM_freeN(), SculptUndoNode::next, SculptUndoNode::no, NULL, UNDO_PAINT_MESH, undo_paint_push_end(), and undo_paint_push_get_list().
Referenced by hide_show_exec(), and sculpt_stroke_done().
SculptUndoNode* sculpt_undo_push_node (Object * ob, PBVHNode * node, SculptUndoType type)
Definition at line 456 of file sculpt_undo.c.
References BLI_lock_thread(), BLI_pbvh_node_get_grids(), BLI_pbvh_node_get_verts(), BLI_pbvh_node_num_verts(), BLI_strncpy(), BLI_unlock_thread(), SculptUndoNode::grids, SculptUndoNode::index, SculptSession::kb, LOCK_CUSTOM1, KeyBlock::name, NULL, SculptSession::pbvh, Object::sculpt, sculpt_undo_alloc_node(), SCULPT_UNDO_COORDS, sculpt_undo_get_node(), SCULPT_UNDO_HIDDEN, sculpt_undo_store_coords(), sculpt_undo_store_hidden(), SculptUndoNode::shapeName, SculptUndoNode::totgrid, and SculptUndoNode::totvert.
Referenced by calc_area_normal(), calc_area_normal_and_flatten_center(), calc_flatten_center(), do_brush_action(), do_grab_brush(), do_layer_brush(), do_rotate_brush(), do_thumb_brush(), partialvis_update_grids(), partialvis_update_mesh(), and sculpt_combine_proxies().
void sculpt_update_mesh_elements (struct Scene * scene, struct Sculpt * sd, struct Object * ob, int need_pmap)
Definition at line 2670 of file sculpt.c.
References BKE_mesh_tessface_ensure(), BLI_pbvh_apply_vertCos(), BLI_pbvh_isDeformed(), CD_MASK_BAREMESH, crazyspace_build_sculpt(), Object::data, SculptSession::deform_cos, SculptSession::deform_imats, SculptSession::face_normals, free_sculptsession_deformMats(), get_mesh(), DerivedMesh::getNumPolys, DerivedMesh::getNumVerts, DerivedMesh::getPBVH, DerivedMesh::getPolyMap, invert_m3(), SculptSession::kb, key_to_vertcos(), MEM_freeN(), mesh_get_derived_final(), mesh_getVertexCos(), Mesh::mloop, SculptSession::mloop, SculptSession::modifiers_active, Mesh::mpoly, SculptSession::mpoly, SculptSession::multires, Mesh::mvert, SculptSession::mvert, NULL, ob_get_keyblock(), SculptSession::orig_cos, SculptSession::pbvh, SculptSession::pmap, Object::sculpt, sculpt_modifiers_active(), sculpt_multires_active(), Mesh::totpoly, SculptSession::totpoly, Mesh::totvert, and SculptSession::totvert.
Referenced by sculpt_brush_stroke_init(), sculpt_init_session(), sculpt_stroke_modifiers_check(), sculpt_undo_restore(), and sculpt_undo_restore_coords().
void sculpt_vertcos_to_key (Object * ob, KeyBlock * kb, float(*) vertCos[3])
Definition at line 2262 of file sculpt.c.
References Key::block, MVert::co, copy_v3_v3(), Object::data, ListBase::first, Mesh::key, KEY_RELATIVE, key_to_vertcos(), MEM_freeN(), mesh_calc_normals_mapping(), Mesh::mloop, Mesh::mpoly, Mesh::mvert, KeyBlock::next, NULL, offset_to_key(), Key::refkey, KeyBlock::relative, Object::shapenr, sub_v3_v3v3(), Mesh::totloop, Mesh::totpoly, Mesh::totvert, Key::type, and vertcos_to_key().
Referenced by sculpt_flush_stroke_deform(), sculpt_undo_restore_coords(), and sculpt_update_keyblock().