Blender: node_texture.h File Reference
node_texture.h File Reference
Functions
float voronoi_distance (string distance_metric, vector d, float e)
color cellnoise_color (point p)
void voronoi (point p, string distance_metric, float e, float da[4], point pa[4])
float voronoi_Fn (point p, int n)
float voronoi_FnFn (point p, int n1, int n2)
float voronoi_F1 (point p)
float voronoi_F2 (point p)
float voronoi_F3 (point p)
float voronoi_F4 (point p)
float voronoi_F1F2 (point p)
float voronoi_Cr (point p)
float voronoi_F1S (point p)
float voronoi_F2S (point p)
float voronoi_F3S (point p)
float voronoi_F4S (point p)
float voronoi_F1F2S (point p)
float voronoi_CrS (point p)
float noise_basis (point p, string basis)
float noise_basis_hard (point p, string basis, int hard)
float noise_wave (string wave, float a)
float noise_turbulence (point p, string basis, int octaves, int hard)
float nonzero (float f, float eps)
Function Documentation
color cellnoise_color (point p)
Definition at line 43 of file node_texture.h.
References cellnoise(), and g.
Referenced by svm_voronoi(), and voronoi().
float noise_basis (point p, string basis)
Definition at line 154 of file node_texture.h.
References cellnoise(), noise(), voronoi_CrS(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2S(), voronoi_F3S(), and voronoi_F4S().
Referenced by noise_basis_hard(), noise_turbulence(), and svm_noise().
float noise_basis_hard (point p, string basis, int hard)
Definition at line 180 of file node_texture.h.
References fabs(), and noise_basis().
float noise_turbulence (point p, string basis, int octaves, int hard)
Definition at line 215 of file node_texture.h.
References fabs(), i, noise_basis(), and sum().
Referenced by svm_noise(), and svm_wave().
float noise_wave (string wave, float a)
Definition at line 188 of file node_texture.h.
References fabs(), M_PI, and sin().
Referenced by svm_wave().
float nonzero (float f, float eps)
Definition at line 240 of file node_texture.h.
References abs(), and TNT::sign().
void voronoi (point p, string distance_metric, float e, float da[4], point pa[4])
Definition at line 52 of file node_texture.h.
References cellnoise_color(), and voronoi_distance().
float voronoi_Cr (point p)
Definition at line 138 of file node_texture.h.
References voronoi_F1F2().
float voronoi_CrS (point p)
Definition at line 150 of file node_texture.h.
References voronoi_Cr().
float voronoi_distance (string distance_metric, vector d, float e)
Definition at line 19 of file node_texture.h.
References dot(), fabs(), length(), max, pow(), and sqrt().
Referenced by voronoi().
float voronoi_F1 (point p)
Definition at line 132 of file node_texture.h.
References voronoi_Fn().
float voronoi_F1F2 (point p)
Definition at line 136 of file node_texture.h.
References voronoi_FnFn().
float voronoi_F1F2S (point p)
Definition at line 149 of file node_texture.h.
References voronoi_F1F2().
float voronoi_F1S (point p)
Definition at line 145 of file node_texture.h.
References voronoi_F1().
float voronoi_F2 (point p)
Definition at line 133 of file node_texture.h.
References voronoi_Fn().
float voronoi_F2S (point p)
Definition at line 146 of file node_texture.h.
References voronoi_F2().
float voronoi_F3 (point p)
Definition at line 134 of file node_texture.h.
References voronoi_Fn().
float voronoi_F3S (point p)
Definition at line 147 of file node_texture.h.
References voronoi_F3().
float voronoi_F4 (point p)
Definition at line 135 of file node_texture.h.
References voronoi_Fn().
float voronoi_F4S (point p)
Definition at line 148 of file node_texture.h.
References voronoi_F4().
float voronoi_Fn (point p, int n)
Definition at line 112 of file node_texture.h.
References voronoi().
Referenced by voronoi_F1(), voronoi_F2(), voronoi_F3(), and voronoi_F4().
float voronoi_FnFn (point p, int n1, int n2)
Definition at line 122 of file node_texture.h.
References voronoi().
Referenced by voronoi_F1F2().