Blender: poseobject.c File Reference
poseobject.c File Reference
armature
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_dynstr.h"
#include "BLI_utildefines.h"
#include "DNA_anim_types.h"
#include "DNA_armature_types.h"
#include "DNA_constraint_types.h"
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "BKE_animsys.h"
#include "BKE_anim.h"
#include "BKE_idprop.h"
#include "BKE_action.h"
#include "BKE_armature.h"
#include "BKE_context.h"
#include "BKE_constraint.h"
#include "BKE_deform.h"
#include "BKE_depsgraph.h"
#include "BKE_fcurve.h"
#include "BKE_modifier.h"
#include "BKE_object.h"
#include "BKE_report.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_armature.h"
#include "ED_keyframing.h"
#include "ED_mesh.h"
#include "ED_screen.h"
#include "ED_object.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "armature_intern.h"
Classes
struct tSortActionGroup
Typedefs
typedef struct tSortActionGroup tSortActionGroup
Functions
void ED_armature_enter_posemode (bContext *C, Base *base)
void ED_armature_exit_posemode (bContext *C, Base *base)
static int pose_channel_in_IK_chain (Object *ob, bPoseChannel *pchan, int level)
int ED_pose_channel_in_IK_chain (Object *ob, bPoseChannel *pchan)
void ED_pose_recalculate_paths (Scene *scene, Object *ob)
static int pose_calculate_paths_exec (bContext *C, wmOperator *op)
void POSE_OT_paths_calculate (wmOperatorType *ot)
static void ED_pose_clear_paths (Object *ob)
static int pose_clear_paths_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_paths_clear (wmOperatorType *ot)
static int pose_select_constraint_target_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_select_constraint_target (wmOperatorType *ot)
static int pose_select_hierarchy_exec (bContext *C, wmOperator *op)
void POSE_OT_select_hierarchy (wmOperatorType *ot)
static short pose_select_same_group (bContext *C, Object *ob, short extend)
static short pose_select_same_layer (bContext *C, Object *ob, short extend)
static int pose_select_same_keyingset (bContext *C, Object *ob, short extend)
static int pose_select_grouped_exec (bContext *C, wmOperator *op)
void POSE_OT_select_grouped (wmOperatorType *ot)
static int pose_bone_flip_active_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_select_flip_active (wmOperatorType *ot)
void free_posebuf (void)
static void set_pose_keys (Object *ob)
static bPoseChannel * pose_bone_do_paste (Object *ob, bPoseChannel *chan, short selOnly, short flip)
static int pose_copy_exec (bContext *C, wmOperator *op)
void POSE_OT_copy (wmOperatorType *ot)
static int pose_paste_exec (bContext *C, wmOperator *op)
void POSE_OT_paste (wmOperatorType *ot)
static int pose_group_add_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_group_add (wmOperatorType *ot)
static int pose_group_remove_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_group_remove (wmOperatorType *ot)
static int pose_groups_menu_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(evt))
static int pose_group_assign_exec (bContext *C, wmOperator *op)
void POSE_OT_group_assign (wmOperatorType *ot)
static int pose_group_unassign_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_group_unassign (wmOperatorType *ot)
static int group_move_exec (bContext *C, wmOperator *op)
void POSE_OT_group_move (wmOperatorType *ot)
static int compare_agroup (const void *sgrp_a_ptr, const void *sgrp_b_ptr)
static int group_sort_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_group_sort (wmOperatorType *ot)
static void pose_group_select (bContext *C, Object *ob, int select)
static int pose_group_select_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_group_select (wmOperatorType *ot)
static int pose_group_deselect_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_group_deselect (wmOperatorType *ot)
static int pose_flip_names_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_flip_names (wmOperatorType *ot)
static int pose_autoside_names_exec (bContext *C, wmOperator *op)
void POSE_OT_autoside_names (wmOperatorType *ot)
static int pose_bone_rotmode_exec (bContext *C, wmOperator *op)
void POSE_OT_rotation_mode_set (wmOperatorType *ot)
static int pose_armature_layers_showall_poll (bContext *C)
static int pose_armature_layers_showall_exec (bContext *C, wmOperator *op)
void ARMATURE_OT_layers_show_all (wmOperatorType *ot)
static int pose_armature_layers_invoke (bContext *C, wmOperator *op, wmEvent *evt)
static int pose_armature_layers_exec (bContext *C, wmOperator *op)
void POSE_OT_armature_layers (wmOperatorType *ot)
void ARMATURE_OT_armature_layers (wmOperatorType *ot)
static int pose_bone_layers_invoke (bContext *C, wmOperator *op, wmEvent *evt)
static int pose_bone_layers_exec (bContext *C, wmOperator *op)
void POSE_OT_bone_layers (wmOperatorType *ot)
static int armature_bone_layers_invoke (bContext *C, wmOperator *op, wmEvent *evt)
static int armature_bone_layers_exec (bContext *C, wmOperator *op)
void ARMATURE_OT_bone_layers (wmOperatorType *ot)
static int pose_flip_quats_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_quaternions_flip (wmOperatorType *ot)
static int pose_clear_user_transforms_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_user_transforms_clear (wmOperatorType *ot)
Variables
static bPose * g_posebuf = NULL
Detailed Description
Definition in file poseobject.c.
Typedef Documentation
typedef struct tSortActionGroup tSortActionGroup
Function Documentation
static int armature_bone_layers_exec (bContext * C, wmOperator * op) [static]
Definition at line 2144 of file poseobject.c.
References CTX_DATA_BEGIN, CTX_data_edit_object(), CTX_DATA_END, Object::data, NC_OBJECT, ND_POSE, NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get_array(), RNA_boolean_set_array(), RNA_EditBone, RNA_pointer_create(), and WM_event_add_notifier().
Referenced by ARMATURE_OT_bone_layers().
static int armature_bone_layers_invoke (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 2119 of file poseobject.c.
References CTX_DATA_BEGIN, CTX_DATA_END, wmOperator::ptr, RNA_boolean_set_array(), and WM_operator_props_popup().
Referenced by ARMATURE_OT_bone_layers().
void ARMATURE_OT_armature_layers (wmOperatorType * ot)
Definition at line 2022 of file poseobject.c.
References wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_armature_layers_exec(), pose_armature_layers_invoke(), RNA_def_boolean_layer_member(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_bone_layers (wmOperatorType * ot)
Definition at line 2169 of file poseobject.c.
References armature_bone_layers_exec(), armature_bone_layers_invoke(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean_layer_member(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_layers_show_all (wmOperatorType * ot)
Definition at line 1937 of file poseobject.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_armature_layers_showall_exec(), pose_armature_layers_showall_poll(), wmOperatorType::prop, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
static int compare_agroup (const void * sgrp_a_ptr, const void * sgrp_b_ptr) [static]
Definition at line 1584 of file poseobject.c.
References tSortActionGroup::agrp, and bActionGroup::name.
Referenced by group_sort_exec().
void ED_armature_enter_posemode (bContext * C, Base * base)
Definition at line 84 of file poseobject.c.
References BKE_report(), CTX_wm_reports(), Object::id, ID::lib, Object::mode, NC_SCENE, ND_MODE, NS_MODE_POSE, NULL, OB_ARMATURE, OB_MODE_POSE, Base::object, Object::restore_mode, RPT_WARNING, Object::type, and WM_event_add_notifier().
Referenced by posemode_exec(), and tree_element_active_pose().
void ED_armature_exit_posemode (bContext * C, Base * base)
Definition at line 110 of file poseobject.c.
References Object::mode, NC_SCENE, ND_MODE, NS_MODE_OBJECT, NULL, OB_MODE_POSE, Base::object, Object::restore_mode, and WM_event_add_notifier().
Referenced by posemode_exec(), and tree_element_active_pose().
int ED_pose_channel_in_IK_chain (Object * ob, bPoseChannel * pchan)
Definition at line 174 of file poseobject.c.
References pose_channel_in_IK_chain().
Referenced by draw_pose_dofs().
static void ED_pose_clear_paths (Object * ob) [static]
Definition at line 254 of file poseobject.c.
References animviz_free_motionpath(), bPose::avs, bPoseChannel::bone, BONE_SELECTED, bPose::chanbase, ELEM, ListBase::first, Bone::flag, MOTIONPATH_BAKE_HAS_PATHS, bPoseChannel::mpath, bPoseChannel::next, NULL, bAnimVizSettings::path_bakeflag, tPoseLib_Backup::pchan, and Object::pose.
Referenced by pose_clear_paths_exec().
void ED_pose_recalculate_paths (Scene * scene, Object * ob)
Definition at line 187 of file poseobject.c.
References animviz_calc_motionpaths(), animviz_get_object_motionpaths(), ANIMVIZ_RECALC_PATHS, bPose::avs, BLI_freelistN(), NULL, Object::pose, and bAnimVizSettings::recalc.
Referenced by autokeyframe_pose_cb_func(), pose_calculate_paths_exec(), pose_clear_transform_generic_exec(), and poseAnim_mapping_autoKeyframe().
void free_posebuf (void)
Definition at line 965 of file poseobject.c.
References BLI_freelistN(), bPose::chanbase, ListBase::first, IDP_FreeProperty(), MEM_freeN(), bPoseChannel::next, NULL, tPoseLib_Backup::pchan, and bPoseChannel::prop.
Referenced by pose_copy_exec(), and WM_exit_ext().
static int group_move_exec (bContext * C, wmOperator * op) [static]
Definition at line 1494 of file poseobject.c.
References bPose::active_group, bPose::agroups, bPoseChannel::agrp_index, BLI_findlink(), BLI_insertlinkafter(), BLI_insertlinkbefore(), BLI_remlink(), bPose::chanbase, ED_object_context(), ELEM, ListBase::first, NC_OBJECT, ND_POSE, bPoseChannel::next, next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, tPoseLib_Backup::prev, wmOperator::ptr, RNA_enum_get(), and WM_event_add_notifier().
Referenced by POSE_OT_group_move().
static int group_sort_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1592 of file poseobject.c.
References bPose::active_group, bPose::agroups, bPoseChannel::agrp_index, BLI_addtail(), BLI_assert, BLI_countlist(), bPose::chanbase, compare_agroup(), ED_object_context(), ELEM, ListBase::first, i, if(), ListBase::last, MEM_freeN(), MEM_mallocN(), NC_OBJECT, ND_POSE, bPoseChannel::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, and WM_event_add_notifier().
Referenced by POSE_OT_group_sort().
static int pose_armature_layers_exec (bContext * C, wmOperator * op) [static]
Definition at line 1979 of file poseobject.c.
References CTX_data_active_object(), Object::data, ELEM, NC_OBJECT, ND_POSE, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get_array(), RNA_boolean_set_array(), RNA_id_pointer_create(), and WM_event_add_notifier().
Referenced by ARMATURE_OT_armature_layers(), and POSE_OT_armature_layers().
static int pose_armature_layers_invoke (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 1958 of file poseobject.c.
References CTX_data_active_object(), Object::data, if(), NULL, object_pose_armature_get(), OPERATOR_CANCELLED, wmOperator::ptr, RNA_boolean_get_array(), RNA_boolean_set_array(), RNA_id_pointer_create(), and WM_operator_props_popup().
Referenced by ARMATURE_OT_armature_layers(), and POSE_OT_armature_layers().
static int pose_armature_layers_showall_exec (bContext * C, wmOperator * op) [static]
Definition at line 1906 of file poseobject.c.
References CTX_data_active_object(), Object::data, i, bArmature::id, NC_OBJECT, ND_POSE, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_boolean_set_array(), RNA_id_pointer_create(), and WM_event_add_notifier().
Referenced by ARMATURE_OT_layers_show_all().
static int pose_armature_layers_showall_poll (bContext * C) [static]
Definition at line 1900 of file poseobject.c.
References ED_operator_editarmature(), and ED_operator_posemode().
Referenced by ARMATURE_OT_layers_show_all().
static int pose_autoside_names_exec (bContext * C, wmOperator * op) [static]
Definition at line 1802 of file poseobject.c.
References BLI_strncpy(), bPoseChannel::bone, bone_autoside_name(), CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, DAG_id_tag_update(), Object::data, ED_armature_bone_rename(), ELEM, Bone::head, Object::id, MAXBONENAME, bPoseChannel::name, NC_OBJECT, ND_POSE, NULL, OB_RECALC_DATA, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, wmOperator::ptr, RNA_enum_get(), Bone::tail, and WM_event_add_notifier().
Referenced by POSE_OT_autoside_names().
static bPoseChannel* pose_bone_do_paste (Object * ob, bPoseChannel * chan, short selOnly, short flip) [static]
Definition at line 1012 of file poseobject.c.
References axis_angle_to_eulO(), axis_angle_to_quat(), BLI_strncpy(), bPoseChannel::bone, BONE_SELECTED, copy_qt_qt(), copy_v3_v3(), bPoseChannel::eul, eul_to_quat(), EULER_ORDER_DEFAULT, eulO_to_axis_angle(), eulO_to_quat(), bPoseChannel::flag, Bone::flag, flip_side_name(), get_pose_channel(), IDP_CopyProperty(), IDP_SyncGroupValues(), bPoseChannel::loc, MAXBONENAME, bPoseChannel::name, normalize_qt(), NULL, tPoseLib_Backup::pchan, Object::pose, bPoseChannel::prop, bPoseChannel::quat, quat_to_axis_angle(), quat_to_eul(), quat_to_eulO(), ROT_MODE_AXISANGLE, bPoseChannel::rotAngle, bPoseChannel::rotAxis, bPoseChannel::rotmode, and bPoseChannel::size.
Referenced by pose_clear_user_transforms_exec(), and pose_paste_exec().
static int pose_bone_flip_active_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 707 of file poseobject.c.
References bArmature::act_bone, bPoseChannel::bone, BONE_SELECTED, CTX_data_active_object(), DAG_id_tag_update(), Object::data, ED_vgroup_select_by_name(), Bone::flag, flip_side_name(), get_pose_channel(), Object::id, MAXBONENAME, Object::mode, Bone::name, NC_OBJECT, ND_BONE_SELECT, OB_MODE_POSE, OB_MODE_WEIGHT_PAINT, OB_RECALC_DATA, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, TRUE, and WM_event_add_notifier().
Referenced by POSE_OT_select_flip_active().
static int pose_bone_layers_exec (bContext * C, wmOperator * op) [static]
Definition at line 2069 of file poseobject.c.
References bPoseChannel::bone, CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, Object::data, NC_OBJECT, ND_POSE, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_Bone, RNA_boolean_get_array(), RNA_boolean_set_array(), RNA_pointer_create(), and WM_event_add_notifier().
Referenced by POSE_OT_bone_layers().
static int pose_bone_layers_invoke (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 2044 of file poseobject.c.
References bPoseChannel::bone, CTX_DATA_BEGIN, CTX_DATA_END, Bone::layer, wmOperator::ptr, RNA_boolean_set_array(), and WM_operator_props_popup().
Referenced by POSE_OT_bone_layers().
static int pose_bone_rotmode_exec (bContext * C, wmOperator * op) [static]
Definition at line 1859 of file poseobject.c.
References CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, DAG_id_tag_update(), NC_OBJECT, ND_TRANSFORM, OB_RECALC_DATA, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), bPoseChannel::rotmode, and WM_event_add_notifier().
Referenced by POSE_OT_rotation_mode_set().
static int pose_calculate_paths_exec (bContext * C, wmOperator * op) [static]
Definition at line 203 of file poseobject.c.
References animviz_verify_motionpaths(), CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_scene(), CTX_wm_area(), ED_object_context(), ED_pose_recalculate_paths(), ELEM, NC_OBJECT, ND_POSE, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, wmOperator::reports, SPACE_BUTS, ScrArea::spacetype, and WM_event_add_notifier().
Referenced by POSE_OT_paths_calculate().
static int pose_channel_in_IK_chain (Object * ob, bPoseChannel * pchan, int level) [static]
Definition at line 150 of file poseobject.c.
References bPoseChannel::bone, Bone::childbase, CONSTRAINT_IK_AUTO, CONSTRAINT_TYPE_KINEMATIC, bPoseChannel::constraints, bConstraint::data, data, ListBase::first, bKinematicConstraint::flag, get_pose_channel(), Bone::name, Bone::next, bConstraint::next, Object::pose, bKinematicConstraint::rootbone, and bConstraint::type.
Referenced by ED_pose_channel_in_IK_chain().
static int pose_clear_paths_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 280 of file poseobject.c.
References CTX_data_active_object(), CTX_wm_area(), ED_object_context(), ED_pose_clear_paths(), ELEM, NC_OBJECT, ND_POSE, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, SPACE_BUTS, ScrArea::spacetype, and WM_event_add_notifier().
Referenced by POSE_OT_paths_clear().
static int pose_clear_user_transforms_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2235 of file poseobject.c.
References AnimData::action, Object::adt, ADT_RECALC_ANIM, BKE_animsys_evaluate_animdata(), BLI_freelistN(), BLI_strncpy(), CFRA, bPose::chanbase, copy_pose(), CTX_data_active_object(), CTX_data_scene(), DAG_id_tag_update(), Object::data, ListBase::first, Object::id, IDP_FreeProperty(), MEM_freeN(), ID::name, NC_OBJECT, ND_TRANSFORM, bPoseChannel::next, NULL, OB_ARMATURE, OB_RECALC_DATA, OPERATOR_FINISHED, Object::pose, pose_bone_do_paste(), bPoseChannel::prop, rest_pose(), Object::type, and WM_event_add_notifier().
Referenced by POSE_OT_user_transforms_clear().
static int pose_copy_exec (bContext * C, wmOperator * op) [static]
Definition at line 1130 of file poseobject.c.
References BKE_report(), copy_pose(), CTX_data_active_object(), ELEM, free_posebuf(), NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, wmOperator::reports, RPT_ERROR, and set_pose_keys().
Referenced by POSE_OT_copy().
static int pose_flip_names_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1757 of file poseobject.c.
References CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, DAG_id_tag_update(), Object::data, ED_armature_bone_rename(), ELEM, flip_side_name(), Object::id, MAXBONENAME, bPoseChannel::name, NC_OBJECT, ND_POSE, NULL, OB_RECALC_DATA, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, TRUE, and WM_event_add_notifier().
Referenced by POSE_OT_flip_names().
static int pose_flip_quats_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2191 of file poseobject.c.
References ANIM_builtin_keyingset_get_named(), ANIM_KS_LOC_ROT_SCALE_ID, CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_scene(), DAG_id_tag_update(), ED_autokeyframe_pchan(), Object::id, NC_OBJECT, ND_TRANSFORM, negate_v4(), NULL, OB_RECALC_DATA, object_pose_armature_get(), OPERATOR_FINISHED, bPoseChannel::quat, ROT_MODE_QUAT, bPoseChannel::rotmode, and WM_event_add_notifier().
Referenced by POSE_OT_quaternions_flip().
static int pose_group_add_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1244 of file poseobject.c.
References CTX_data_active_object(), CTX_wm_area(), ED_object_context(), NC_OBJECT, ND_POSE, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, pose_add_group(), SPACE_BUTS, ScrArea::spacetype, and WM_event_add_notifier().
Referenced by POSE_OT_group_add().
static int pose_group_assign_exec (bContext * C, wmOperator * op) [static]
Definition at line 1379 of file poseobject.c.
References bPose::active_group, bPoseChannel::agrp_index, CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_wm_area(), ED_object_context(), ELEM, NC_OBJECT, ND_POSE, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, pose_add_group(), wmOperator::ptr, RNA_int_get(), SPACE_BUTS, ScrArea::spacetype, and WM_event_add_notifier().
Referenced by POSE_OT_group_assign().
static int pose_group_deselect_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1717 of file poseobject.c.
References CTX_data_active_object(), CTX_wm_area(), ED_object_context(), ELEM, NC_OBJECT, ND_POSE, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, pose_group_select(), SPACE_BUTS, ScrArea::spacetype, and WM_event_add_notifier().
Referenced by POSE_OT_group_deselect().
static int pose_group_remove_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1284 of file poseobject.c.
References CTX_data_active_object(), CTX_wm_area(), ED_object_context(), NC_OBJECT, ND_POSE, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, pose_remove_group(), SPACE_BUTS, ScrArea::spacetype, and WM_event_add_notifier().
Referenced by POSE_OT_group_remove().
static void pose_group_select (bContext * C, Object * ob, int select) [static]
Definition at line 1659 of file poseobject.c.
References bPose::active_group, bPoseChannel::agrp_index, bPoseChannel::bone, BONE_SELECTED, BONE_UNSELECTABLE, CTX_DATA_BEGIN, CTX_DATA_END, Bone::flag, and Object::pose.
Referenced by pose_group_deselect_exec(), and pose_group_select_exec().
static int pose_group_select_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1679 of file poseobject.c.
References CTX_data_active_object(), CTX_wm_area(), ED_object_context(), ELEM, NC_OBJECT, ND_POSE, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, pose_group_select(), SPACE_BUTS, ScrArea::spacetype, and WM_event_add_notifier().
Referenced by POSE_OT_group_select().
static int pose_group_unassign_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1443 of file poseobject.c.
References bPoseChannel::agrp_index, CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_wm_area(), ED_object_context(), ELEM, NC_OBJECT, ND_POSE, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, SPACE_BUTS, ScrArea::spacetype, and WM_event_add_notifier().
Referenced by POSE_OT_group_unassign().
static int pose_groups_menu_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevt) [static]
Definition at line 1326 of file poseobject.c.
References bPose::active_group, bPose::agroups, CTX_data_active_object(), CTX_wm_area(), ED_object_context(), ELEM, wmOperatorType::exec, ListBase::first, i, wmOperator::idname, bActionGroup::name, wmOperatorType::name, bActionGroup::next, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, Object::pose, wmOperator::ptr, RNA_int_set(), SPACE_BUTS, ScrArea::spacetype, wmOperator::type, uiItemIntO(), uiItemS(), uiPupMenuBegin(), uiPupMenuEnd(), and uiPupMenuLayout().
Referenced by POSE_OT_group_assign().
void POSE_OT_armature_layers (wmOperatorType * ot)
Definition at line 2003 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_armature_layers_exec(), pose_armature_layers_invoke(), RNA_def_boolean_layer_member(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_autoside_names (wmOperatorType * ot)
Definition at line 1832 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_autoside_names_exec(), wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void POSE_OT_bone_layers (wmOperatorType * ot)
Definition at line 2097 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_bone_layers_exec(), pose_bone_layers_invoke(), RNA_def_boolean_layer_member(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_copy (wmOperatorType * ot)
Definition at line 1151 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, and pose_copy_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_flip_names (wmOperatorType * ot)
Definition at line 1785 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_flip_names_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_group_add (wmOperatorType * ot)
Definition at line 1268 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_group_add_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_group_assign (wmOperatorType * ot)
Definition at line 1423 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_group_assign_exec(), pose_groups_menu_invoke(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_group_deselect (wmOperatorType * ot)
Definition at line 1740 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_group_deselect_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_group_move (wmOperatorType * ot)
Definition at line 1554 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, group_move_exec(), wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_group_remove (wmOperatorType * ot)
Definition at line 1308 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_group_remove_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_group_select (wmOperatorType * ot)
Definition at line 1702 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_group_select_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_group_sort (wmOperatorType * ot)
Definition at line 1644 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, group_sort_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void POSE_OT_group_unassign (wmOperatorType * ot)
Definition at line 1479 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_group_unassign_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_paste (wmOperatorType * ot)
Definition at line 1218 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_paste_exec(), PROP_SKIP_SAVE, RNA_def_boolean(), RNA_def_property_flag(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_paths_calculate (wmOperatorType * ot)
Definition at line 236 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_calculate_paths_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_paths_clear (wmOperatorType * ot)
Definition at line 304 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_clear_paths_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_quaternions_flip (wmOperatorType * ot)
Definition at line 2217 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_flip_quats_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_rotation_mode_set (wmOperatorType * ot)
Definition at line 1878 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_bone_rotmode_exec(), posebone_rotmode_items, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void POSE_OT_select_constraint_target (wmOperatorType * ot)
Definition at line 364 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_select_constraint_target_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_select_flip_active (wmOperatorType * ot)
Definition at line 743 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_bone_flip_active_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_select_grouped (wmOperatorType * ot)
Definition at line 676 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_select_grouped_exec(), wmOperatorType::prop, prop_select_grouped_types, RNA_def_boolean(), RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void POSE_OT_select_hierarchy (wmOperatorType * ot)
Definition at line 457 of file poseobject.c.
References BONE_SELECT_CHILD, BONE_SELECT_PARENT, wmOperatorType::description, direction_items, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_select_hierarchy_exec(), wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_user_transforms_clear (wmOperatorType * ot)
Definition at line 2293 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_clear_user_transforms_exec().
Referenced by ED_operatortypes_armature().
static int pose_paste_exec (bContext * C, wmOperator * op) [static]
Definition at line 1168 of file poseobject.c.
References ANIM_get_keyingset_for_autokeying(), ANIM_KS_LOC_ROT_SCALE_ID, BKE_report(), bPose::chanbase, CTX_data_active_object(), CTX_DATA_COUNT, CTX_data_scene(), DAG_id_tag_update(), ED_autokeyframe_pchan(), ELEM, ListBase::first, bPoseChannel::flag, Object::id, NC_OBJECT, ND_POSE, bPoseChannel::next, NULL, OB_RECALC_DATA, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, pose_bone_do_paste(), POSE_KEY, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RPT_ERROR, and WM_event_add_notifier().
Referenced by POSE_OT_paste().
static int pose_select_constraint_target_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 321 of file poseobject.c.
References bPoseChannel::bone, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, BONE_UNSELECTABLE, constraint_get_typeinfo(), bPoseChannel::constraints, CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, ListBase::first, Bone::flag, bConstraintTypeInfo::flush_constraint_targets, bConstraintTypeInfo::get_constraint_targets, get_pose_channel(), NC_OBJECT, ND_BONE_SELECT, bConstraintTarget::next, bConstraint::next, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, bConstraintTarget::subtarget, bConstraintTarget::tar, and WM_event_add_notifier().
Referenced by POSE_OT_select_constraint_target().
static int pose_select_grouped_exec (bContext * C, wmOperator * op) [static]
Definition at line 641 of file poseobject.c.
References CTX_data_active_object(), ELEM, NC_OBJECT, ND_POSE, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, pose_select_same_group(), pose_select_same_keyingset(), pose_select_same_layer(), wmOperator::ptr, RNA_boolean_get(), RNA_enum_get(), and WM_event_add_notifier().
Referenced by POSE_OT_select_grouped().
static int pose_select_hierarchy_exec (bContext * C, wmOperator * op) [static]
Definition at line 381 of file poseobject.c.
References bArmature::act_bone, bPoseChannel::bone, BONE_SELECT_PARENT, BONE_SELECTED, BONE_UNSELECTABLE, bPose::chanbase, bPoseChannel::child, CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, Object::data, ListBase::first, Bone::flag, NC_OBJECT, ND_BONE_SELECT, bPoseChannel::next, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, bPoseChannel::parent, PBONE_VISIBLE, Object::pose, wmOperator::ptr, RNA_boolean_get(), RNA_enum_get(), and WM_event_add_notifier().
Referenced by POSE_OT_select_hierarchy().
static short pose_select_same_group (bContext * C, Object * ob, short extend) [static]
Definition at line 485 of file poseobject.c.
References bPoseChannel::agrp_index, BLI_countlist(), bPoseChannel::bone, BONE_SELECTED, BONE_UNSELECTABLE, CTX_DATA_BEGIN, CTX_DATA_END, Object::data, ELEM3, Bone::flag, MEM_callocN(), MEM_freeN(), NULL, and Object::pose.
Referenced by pose_select_grouped_exec().
static int pose_select_same_keyingset (bContext * C, Object * ob, short extend) [static]
Definition at line 583 of file poseobject.c.
References ANIM_scene_get_active_keyingset(), ANIM_validate_keyingset(), BLI_getQuotedStr(), bPoseChannel::bone, BONE_SELECTED, BONE_UNSELECTABLE, CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_scene(), Object::data, ELEM3, ListBase::first, Bone::flag, get_pose_channel(), Object::id, KS_Path::id, MEM_freeN(), KS_Path::next, NULL, KeyingSet::paths, PBONE_VISIBLE, Object::pose, and KS_Path::rna_path.
Referenced by pose_select_grouped_exec().
static short pose_select_same_layer (bContext * C, Object * ob, short extend) [static]
Definition at line 544 of file poseobject.c.
References bPoseChannel::bone, BONE_SELECTED, BONE_UNSELECTABLE, CTX_DATA_BEGIN, CTX_DATA_END, Object::data, ELEM3, Bone::flag, Bone::layer, NULL, and Object::pose.
Referenced by pose_select_grouped_exec().
static void set_pose_keys (Object * ob) [static]
Definition at line 988 of file poseobject.c.
References bPoseChannel::bone, BONE_SELECTED, bPose::chanbase, Object::data, ListBase::first, bPoseChannel::flag, Bone::flag, Bone::layer, bArmature::layer, bPoseChannel::next, Object::pose, and POSE_KEY.
Referenced by pose_copy_exec().
Variable Documentation
bPose* g_posebuf = NULL [static]
Definition at line 963 of file poseobject.c.