Blender: BuildBinaryVBVH< Node > Struct Template Reference
BuildBinaryVBVH< Node > Struct Template Reference
#include <vbvh.h>
Public Member Functions
void test_break ()
BuildBinaryVBVH (MemArena *a, RayObjectControl *c)
Node * create_node ()
int rtbuild_split (RTBuilder *builder)
Node * transform (RTBuilder *builder)
Node * _transform (RTBuilder *builder)
Public Attributes
MemArena * arena
RayObjectControl * control
Detailed Description
template<class Node>
struct BuildBinaryVBVH< Node >
Definition at line 114 of file vbvh.h.
Constructor & Destructor Documentation
template<class Node> BuildBinaryVBVH< Node >::BuildBinaryVBVH (MemArena * a, RayObjectControl * c) [inline]
Definition at line 125 of file vbvh.h.
References BuildBinaryVBVH< Node >::arena, and BuildBinaryVBVH< Node >::control.
Member Function Documentation
template<class Node> Node* BuildBinaryVBVH< Node >::_transform (RTBuilder * builder) [inline]
Definition at line 159 of file vbvh.h.
References assert, BuildBinaryVBVH< Node >::create_node(), DO_MAX, DO_MIN, i, INIT_MINMAX, NULL, rtbuild_get_child(), rtbuild_get_primitive(), rtbuild_merge_bb(), rtbuild_size(), BuildBinaryVBVH< Node >::rtbuild_split(), size(), and BuildBinaryVBVH< Node >::test_break().
Referenced by BuildBinaryVBVH< Node >::transform().
template<class Node> Node* BuildBinaryVBVH< Node >::create_node () [inline]
Definition at line 131 of file vbvh.h.
References BuildBinaryVBVH< Node >::arena, assert, BLI_memarena_alloc(), NULL, and RE_rayobject_isAligned.
Referenced by BuildBinaryVBVH< Node >::_transform().
template<class Node> int BuildBinaryVBVH< Node >::rtbuild_split (RTBuilder * builder) [inline]
Definition at line 142 of file vbvh.h.
References rtbuild_heuristic_object_split().
Referenced by BuildBinaryVBVH< Node >::_transform().
template<class Node> void BuildBinaryVBVH< Node >::test_break () [inline]
Definition at line 119 of file vbvh.h.
References BuildBinaryVBVH< Node >::control, and RE_rayobjectcontrol_test_break().
Referenced by BuildBinaryVBVH< Node >::_transform().
template<class Node> Node* BuildBinaryVBVH< Node >::transform (RTBuilder * builder) [inline]
Definition at line 147 of file vbvh.h.
References BuildBinaryVBVH< Node >::_transform(), and NULL.
Member Data Documentation
template<class Node> MemArena* BuildBinaryVBVH< Node >::arena
Definition at line 116 of file vbvh.h.
Referenced by BuildBinaryVBVH< Node >::BuildBinaryVBVH(), and BuildBinaryVBVH< Node >::create_node().
template<class Node> RayObjectControl* BuildBinaryVBVH< Node >::control
Definition at line 117 of file vbvh.h.
Referenced by BuildBinaryVBVH< Node >::BuildBinaryVBVH(), and BuildBinaryVBVH< Node >::test_break().
The documentation for this struct was generated from the following file:
vbvh.h