Blender: SCA_IActuator Class Reference
SCA_IActuator Class Reference
#include <SCA_IActuator.h>
Public Types
enum KX_ACTUATOR_TYPE {
KX_ACT_OBJECT, KX_ACT_IPO, KX_ACT_CAMERA, KX_ACT_SOUND,
KX_ACT_PROPERTY, KX_ACT_ADD_OBJECT, KX_ACT_END_OBJECT, KX_ACT_DYNAMIC,
KX_ACT_REPLACE_MESH, KX_ACT_TRACKTO, KX_ACT_CONSTRAINT, KX_ACT_SCENE,
KX_ACT_RANDOM, KX_ACT_MESSAGE, KX_ACT_ACTION, KX_ACT_CD,
KX_ACT_GAME, KX_ACT_VISIBILITY, KX_ACT_2DFILTER, KX_ACT_PARENT,
KX_ACT_SHAPEACTION, KX_ACT_STATE, KX_ACT_ARMATURE, KX_ACT_STEERING
}
Public Member Functions
SCA_IActuator (SCA_IObject *gameobj, KX_ACTUATOR_TYPE type)
virtual bool UnlinkObject (SCA_IObject *clientobj)
virtual bool Update (double curtime, bool frame)
virtual bool Update ()
void AddEvent (bool event)
virtual void ProcessReplica ()
bool IsNegativeEvent () const
virtual ~SCA_IActuator ()
virtual void Deactivate ()
virtual void Activate (SG_DList &head)
void LinkToController (SCA_IController *controller)
void UnlinkController (class SCA_IController *cont)
void UnlinkAllControllers ()
void ClrLink ()
void IncLink ()
void DecLink ()
bool IsNoLink () const
bool IsType (KX_ACTUATOR_TYPE type)
Protected Member Functions
void RemoveAllEvents ()
Protected Attributes
int m_type
int m_links
bool m_posevent
bool m_negevent
std::vector< class
SCA_IController * > m_linkedcontrollers
Friends
class SCA_LogicManager
Detailed Description
Use of SG_DList : None Use of SG_QList : element of activated actuator list of their owner Head: SCA_IObject::m_activeActuators
Definition at line 43 of file SCA_IActuator.h.
Member Enumeration Documentation
enum SCA_IActuator::KX_ACTUATOR_TYPE
This class also inherits the default copy constructors
Enumerator:
KX_ACT_OBJECT
KX_ACT_IPO
KX_ACT_CAMERA
KX_ACT_SOUND
KX_ACT_PROPERTY
KX_ACT_ADD_OBJECT
KX_ACT_END_OBJECT
KX_ACT_DYNAMIC
KX_ACT_REPLACE_MESH
KX_ACT_TRACKTO
KX_ACT_CONSTRAINT
KX_ACT_SCENE
KX_ACT_RANDOM
KX_ACT_MESSAGE
KX_ACT_ACTION
KX_ACT_CD
KX_ACT_GAME
KX_ACT_VISIBILITY
KX_ACT_2DFILTER
KX_ACT_PARENT
KX_ACT_SHAPEACTION
KX_ACT_STATE
KX_ACT_ARMATURE
KX_ACT_STEERING
Definition at line 67 of file SCA_IActuator.h.
Constructor & Destructor Documentation
SCA_IActuator::SCA_IActuator (SCA_IObject * gameobj, KX_ACTUATOR_TYPE type)
Definition at line 38 of file SCA_IActuator.cpp.
SCA_IActuator::~SCA_IActuator () [virtual]
Definition at line 94 of file SCA_IActuator.cpp.
References RemoveAllEvents().
Member Function Documentation
void SCA_IActuator::Activate (SG_DList & head) [virtual]
Reimplemented in KX_StateActuator.
Definition at line 62 of file SCA_IActuator.cpp.
References SG_DList::AddBack(), SCA_ILogicBrick::InsertActiveQList(), SCA_IObject::m_activeActuators, SCA_ILogicBrick::m_gameobj, and SG_QList::QEmpty().
Referenced by SCA_LogicManager::AddActiveActuator().
void SCA_IActuator::AddEvent (bool event) [inline]
Add an event to an actuator.
Definition at line 123 of file SCA_IActuator.h.
References m_negevent, and m_posevent.
Referenced by SCA_LogicManager::AddActiveActuator(), and SCA_LogicManager::UpdateFrame().
void SCA_IActuator::ClrLink () [inline]
Definition at line 156 of file SCA_IActuator.h.
References m_links.
Referenced by SCA_IObject::ReParentLogic().
void SCA_IActuator::Deactivate () [virtual]
remove this actuator from the list of active actuators
Reimplemented in KX_StateActuator.
Definition at line 73 of file SCA_IActuator.cpp.
References SG_DList::Delink(), SCA_IObject::m_activeActuators, SCA_ILogicBrick::m_gameobj, SG_QList::QDelink(), and SG_QList::QEmpty().
Referenced by SCA_LogicManager::RemoveActuator().
void SCA_IActuator::DecLink ()
Definition at line 99 of file SCA_IActuator.cpp.
References m_links, SCA_ILogicBrick::m_name, and STR_String::Ptr().
void SCA_IActuator::IncLink () [inline]
Definition at line 157 of file SCA_IActuator.h.
References m_links.
Referenced by SCA_IController::LinkToActuator().
bool SCA_IActuator::IsNegativeEvent () const [inline]
Return true iff all the current events are negative. The definition of negative event is not immediately clear. But usually refers to key-up events or events where no action is required.
Definition at line 139 of file SCA_IActuator.h.
References m_negevent, and m_posevent.
Referenced by BL_ArmatureActuator::Update(), KX_SCA_DynamicActuator::Update(), KX_GameActuator::Update(), KX_SoundActuator::Update(), SCA_ActuatorSensor::Update(), KX_ConstraintActuator::Update(), SCA_2DFilterActuator::Update(), KX_ObjectActuator::Update(), KX_SteeringActuator::Update(), KX_CameraActuator::Update(), KX_IpoActuator::Update(), KX_NetworkMessageActuator::Update(), KX_SCA_EndObjectActuator::Update(), SCA_PropertyActuator::Update(), SCA_RandomActuator::Update(), KX_VisibilityActuator::Update(), KX_TrackToActuator::Update(), KX_SCA_ReplaceMeshActuator::Update(), KX_SCA_AddObjectActuator::Update(), KX_SceneActuator::Update(), KX_ParentActuator::Update(), and KX_StateActuator::Update().
bool SCA_IActuator::IsNoLink () const [inline]
Definition at line 159 of file SCA_IActuator.h.
References m_links.
Referenced by SCA_LogicManager::UpdateFrame().
bool SCA_IActuator::IsType (KX_ACTUATOR_TYPE type) [inline]
Definition at line 160 of file SCA_IActuator.h.
References m_type.
void SCA_IActuator::LinkToController (SCA_IController * controller)
Definition at line 109 of file SCA_IActuator.cpp.
References m_linkedcontrollers.
Referenced by SCA_LogicManager::RegisterToActuator().
void SCA_IActuator::ProcessReplica () [virtual]
Makes sure any internal data owned by this class is deep copied.
Reimplemented from CValue.
Reimplemented in BL_ActionActuator, BL_ArmatureActuator, BL_ShapeActionActuator, SCA_PropertyActuator, SCA_RandomActuator, KX_CameraActuator, KX_ObjectActuator, KX_ParentActuator, KX_SCA_AddObjectActuator, KX_SceneActuator, KX_SoundActuator, KX_SteeringActuator, and KX_TrackToActuator.
Definition at line 85 of file SCA_IActuator.cpp.
References m_linkedcontrollers, and RemoveAllEvents().
Referenced by KX_IpoActuator::GetReplica(), KX_VisibilityActuator::GetReplica(), SCA_2DFilterActuator::GetReplica(), KX_NetworkMessageActuator::GetReplica(), KX_StateActuator::GetReplica(), KX_ConstraintActuator::GetReplica(), KX_SCA_DynamicActuator::GetReplica(), KX_SCA_EndObjectActuator::GetReplica(), KX_GameActuator::GetReplica(), and KX_SCA_ReplaceMeshActuator::GetReplica().
void SCA_IActuator::RemoveAllEvents () [inline, protected]
Definition at line 56 of file SCA_IActuator.h.
References m_negevent, and m_posevent.
Referenced by ProcessReplica(), BL_ArmatureActuator::Update(), KX_SCA_DynamicActuator::Update(), BL_ActionActuator::Update(), KX_GameActuator::Update(), KX_SoundActuator::Update(), KX_ConstraintActuator::Update(), SCA_2DFilterActuator::Update(), KX_ObjectActuator::Update(), BL_ShapeActionActuator::Update(), KX_SteeringActuator::Update(), KX_CameraActuator::Update(), KX_IpoActuator::Update(), KX_NetworkMessageActuator::Update(), KX_SCA_EndObjectActuator::Update(), SCA_PropertyActuator::Update(), SCA_RandomActuator::Update(), KX_VisibilityActuator::Update(), KX_TrackToActuator::Update(), KX_SCA_ReplaceMeshActuator::Update(), KX_SCA_AddObjectActuator::Update(), KX_SceneActuator::Update(), KX_ParentActuator::Update(), KX_StateActuator::Update(), SCA_LogicManager::UpdateFrame(), and ~SCA_IActuator().
void SCA_IActuator::UnlinkAllControllers ()
Definition at line 131 of file SCA_IActuator.cpp.
References m_linkedcontrollers.
Referenced by SCA_LogicManager::RemoveActuator().
void SCA_IActuator::UnlinkController (class SCA_IController * cont)
Definition at line 114 of file SCA_IActuator.cpp.
References SCA_ILogicBrick::GetName(), CValue::GetName(), SCA_ILogicBrick::GetParent(), SCA_ILogicBrick::m_gameobj, m_linkedcontrollers, and STR_String::ReadPtr().
virtual bool SCA_IActuator::UnlinkObject (SCA_IObject * clientobj) [inline, virtual]
UnlinkObject(...) Certain actuator use gameobject pointers (like TractTo actuator) This function can be called when an object is removed to make sure that the actuator will not use it anymore.
Reimplemented in BL_ArmatureActuator, SCA_PropertyActuator, KX_CameraActuator, KX_ObjectActuator, KX_ParentActuator, KX_SCA_AddObjectActuator, KX_SceneActuator, KX_SteeringActuator, and KX_TrackToActuator.
Definition at line 103 of file SCA_IActuator.h.
bool SCA_IActuator::Update (void) [virtual]
Reimplemented in SCA_2DFilterActuator, SCA_PropertyActuator, SCA_RandomActuator, KX_GameActuator, KX_ObjectActuator, KX_ParentActuator, KX_SCA_AddObjectActuator, KX_SCA_DynamicActuator, KX_SCA_EndObjectActuator, KX_SCA_ReplaceMeshActuator, KX_SceneActuator, KX_StateActuator, KX_VisibilityActuator, and KX_NetworkMessageActuator.
Definition at line 56 of file SCA_IActuator.cpp.
References assert.
Referenced by Update().
bool SCA_IActuator::Update (double curtime, bool frame) [virtual]
Update(...) Update the actuator based upon the events received since the last call to Update, the current time and deltatime the time elapsed in this frame ? It is the responsibility of concrete Actuators to clear their event's. This is usually done in the Update() method via a call to RemoveAllEvents()
Reimplemented in BL_ActionActuator, BL_ArmatureActuator, BL_ShapeActionActuator, KX_CameraActuator, KX_ConstraintActuator, KX_IpoActuator, KX_SoundActuator, KX_SteeringActuator, and KX_TrackToActuator.
Definition at line 48 of file SCA_IActuator.cpp.
References Update().
Referenced by SCA_LogicManager::UpdateFrame().
Friends And Related Function Documentation
friend class SCA_LogicManager [friend]
Definition at line 45 of file SCA_IActuator.h.
Member Data Documentation
std::vector<class SCA_IController*> SCA_IActuator::m_linkedcontrollers [protected]
Definition at line 54 of file SCA_IActuator.h.
Referenced by LinkToController(), ProcessReplica(), UnlinkAllControllers(), and UnlinkController().
int SCA_IActuator::m_links [protected]
Definition at line 48 of file SCA_IActuator.h.
Referenced by ClrLink(), DecLink(), IncLink(), and IsNoLink().
bool SCA_IActuator::m_negevent [protected]
Definition at line 52 of file SCA_IActuator.h.
Referenced by AddEvent(), IsNegativeEvent(), RemoveAllEvents(), BL_ActionActuator::Update(), BL_ShapeActionActuator::Update(), and KX_IpoActuator::Update().
bool SCA_IActuator::m_posevent [protected]
Definition at line 51 of file SCA_IActuator.h.
Referenced by AddEvent(), IsNegativeEvent(), RemoveAllEvents(), BL_ActionActuator::Update(), KX_SoundActuator::Update(), BL_ShapeActionActuator::Update(), KX_SteeringActuator::Update(), and KX_IpoActuator::Update().
int SCA_IActuator::m_type [protected]
Reimplemented in KX_IpoActuator, and KX_SoundActuator.
Definition at line 47 of file SCA_IActuator.h.
Referenced by IsType().
The documentation for this class was generated from the following files:
SCA_IActuator.h
SCA_IActuator.cpp