Blender: voxeldata.h File Reference
voxeldata.h File Reference
Rendering
Classes
struct VoxelDataHeader
Typedefs
typedef struct VoxelDataHeader VoxelDataHeader
Functions
void cache_voxeldata (Tex *tex, int scene_frame)
void make_voxeldata (struct Render *re)
int voxeldatatex (struct Tex *tex, const float texvec[3], struct TexResult *texres)
Detailed Description
Definition in file voxeldata.h.
Typedef Documentation
typedef struct VoxelDataHeader VoxelDataHeader
Function Documentation
void cache_voxeldata (Tex * tex, int scene_frame)
Definition at line 312 of file voxeldata.c.
References BLI_exists(), BLI_fopen(), BLI_path_abs(), BLI_strncpy(), VoxelData::cachedframe, VoxelData::dataset, VoxelData::file_format, VoxelData::flag, G, init_frame_smoke(), load_frame_blendervoxel(), load_frame_image_sequence(), load_frame_raw8(), MEM_freeN(), NULL, VoxelData::ok, read_voxeldata_header(), VoxelData::source_path, VoxelData::still_frame, TEX_VD_BLENDERVOXEL, TEX_VD_IMAGE_SEQUENCE, TEX_VD_RAW_8BIT, TEX_VD_SMOKE, TEX_VD_STILL, and Tex::vd.
Referenced by make_voxeldata(), and RE_init_sample_material().
void make_voxeldata (struct Render * re)
Definition at line 366 of file voxeldata.c.
References cache_voxeldata(), RenderData::cfra, ListBase::first, Render::i, Tex::id, RenderStats::infostr, Render::main, ID::next, NULL, Render::r, Render::sdh, Render::stats_draw, Main::tex, TEX_VOXELDATA, Tex::type, and ID::us.
Referenced by RE_Database_Baking(), and RE_Database_FromScene().
int voxeldatatex (struct Tex * tex, const float texvec[3], struct TexResult * texres)
Definition at line 385 of file voxeldata.c.
References add_v3_v3(), BRICONT, BRICONTRGB, CLAMP(), co, copy_v3_v3(), VoxelData::dataset, VoxelData::extend, floorf, VoxelData::int_multiplier, VoxelData::interp_type, mul_v3_fl(), NULL, VoxelData::resol, TexResult::ta, TexResult::tb, TEX_CLIP, TEX_EXTEND, TEX_INT, TEX_REPEAT, TEX_VD_LINEAR, TEX_VD_NEARESTNEIGHBOR, TEX_VD_QUADRATIC, TEX_VD_TRICUBIC_BSPLINE, TEX_VD_TRICUBIC_CATROM, TexResult::tg, TexResult::tin, TexResult::tr, Tex::vd, voxel_sample_nearest(), voxel_sample_tricubic(), voxel_sample_trilinear(), and voxel_sample_triquadratic().
Referenced by multitex().