Blender: btEigen Struct Reference
btEigen Struct Reference
#include <btSoftBodyInternals.h>
Static Public Member Functions
static int system (btMatrix3x3 &a, btMatrix3x3 *vectors, btVector3 *values=0)
Detailed Description
Definition at line 556 of file btSoftBodyInternals.h.
Member Function Documentation
static int btEigen::system (btMatrix3x3 & a, btMatrix3x3 * vectors, btVector3 * values = 0) [inline, static]
Definition at line 558 of file btSoftBodyInternals.h.
References btFabs(), btSqrt(), p, and btMatrix3x3::setIdentity().
The documentation for this struct was generated from the following file:
btSoftBodyInternals.h