Blender: space_console.c File Reference
space_console.c File Reference
console space
#include <string.h>
#include <stdio.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "BKE_idcode.h"
#include "ED_space_api.h"
#include "ED_screen.h"
#include "BIF_gl.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "console_intern.h"
Functions
static SpaceLink * console_new (const bContext *UNUSED(C))
static void console_free (SpaceLink *sl)
static void console_init (struct wmWindowManager *UNUSED(wm), ScrArea *UNUSED(sa))
static SpaceLink * console_duplicate (SpaceLink *sl)
static void console_main_area_init (wmWindowManager *wm, ARegion *ar)
static int id_drop_poll (bContext *UNUSED(C), wmDrag *drag, wmEvent *UNUSED(event))
static void id_drop_copy (wmDrag *drag, wmDropBox *drop)
static int path_drop_poll (bContext *UNUSED(C), wmDrag *drag, wmEvent *UNUSED(event))
static void path_drop_copy (wmDrag *drag, wmDropBox *drop)
static void console_dropboxes (void)
static void console_main_area_draw (const bContext *C, ARegion *ar)
static void console_operatortypes (void)
static void console_keymap (struct wmKeyConfig *keyconf)
static void console_header_area_init (wmWindowManager *UNUSED(wm), ARegion *ar)
static void console_header_area_draw (const bContext *C, ARegion *ar)
static void console_main_area_listener (ARegion *ar, wmNotifier *wmn)
void ED_spacetype_console (void)
Detailed Description
Definition in file space_console.c.
Function Documentation
static void console_dropboxes (void) [static]
Definition at line 202 of file space_console.c.
References id_drop_copy(), id_drop_poll(), path_drop_copy(), path_drop_poll(), RGN_TYPE_WINDOW, SPACE_CONSOLE, WM_dropbox_add(), and WM_dropboxmap_find().
Referenced by ED_spacetype_console().
static SpaceLink* console_duplicate (SpaceLink * sl) [static]
Definition at line 118 of file space_console.c.
References ListBase::first, SpaceConsole::history, ListBase::last, MEM_dupallocN(), NULL, and SpaceConsole::scrollback.
Referenced by ED_spacetype_console().
static void console_free (SpaceLink * sl) [static]
Definition at line 100 of file space_console.c.
References console_history_free(), console_scrollback_free(), ListBase::first, SpaceConsole::history, and SpaceConsole::scrollback.
Referenced by ED_spacetype_console().
static void console_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 344 of file space_console.c.
References ED_region_header().
Referenced by ED_spacetype_console().
static void console_header_area_init (wmWindowManager * UNUSEDwm, ARegion * ar) [static]
Definition at line 339 of file space_console.c.
References ED_region_header_init().
Referenced by ED_spacetype_console().
static void console_init (struct wmWindowManager * UNUSEDwm, ScrArea * UNUSEDsa) [static]
Definition at line 113 of file space_console.c.
Referenced by ED_spacetype_console().
static void console_keymap (struct wmKeyConfig * keyconf) [static]
Definition at line 261 of file space_console.c.
References BACKSPACEKEY, CKEY, DEL_NEXT_CHAR, DEL_NEXT_WORD, DEL_PREV_CHAR, DEL_PREV_WORD, DELKEY, DOWNARROWKEY, ENDKEY, FALSE, HOMEKEY, KM_ANY, KM_CTRL, KM_OSKEY, KM_PRESS, KM_SHIFT, KM_TEXTINPUT, LEFTARROWKEY, LEFTMOUSE, LINE_BEGIN, LINE_END, NEXT_CHAR, NEXT_LINE, NEXT_PAGE, NEXT_WORD, PADENTER, PADMINUS, PADPLUSKEY, PAGEDOWNKEY, PAGEUPKEY, PREV_CHAR, PREV_LINE, PREV_PAGE, PREV_WORD, wmKeyMapItem::ptr, RETKEY, RIGHTARROWKEY, RNA_boolean_set(), RNA_enum_set(), RNA_string_set(), SPACE_CONSOLE, SPACEKEY, TABKEY, TRUE, UPARROWKEY, VKEY, WHEELDOWNMOUSE, WHEELUPMOUSE, WM_keymap_add_item(), and WM_keymap_find().
Referenced by ED_spacetype_console().
static void console_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 212 of file space_console.c.
References console_history_verify(), console_textview_main(), CTX_wm_space_console(), ListBase::first, NULL, SpaceConsole::scrollback, TH_BACK, UI_ThemeClearColor(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_view_ortho(), UI_view2d_view_restore(), ARegion::v2d, V2D_ARG_DUMMY, V2D_GRID_CLAMP, WM_OP_EXEC_DEFAULT, and WM_operator_name_call().
Referenced by ED_spacetype_console().
static void console_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 134 of file space_console.c.
References View2D::cur, wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, RGN_TYPE_WINDOW, SPACE_CONSOLE, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_CUSTOM, ARegion::winrct, ARegion::winx, ARegion::winy, WM_dropboxmap_find(), WM_event_add_dropbox_handler(), WM_event_add_keymap_handler_bb(), WM_keymap_find(), rctf::ymax, and rctf::ymin.
Referenced by ED_spacetype_console().
static void console_main_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 349 of file space_console.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NC_SPACE, and ND_SPACE_CONSOLE.
Referenced by ED_spacetype_console().
static SpaceLink* console_new (const bContext * UNUSEDC) [static]
Definition at line 61 of file space_console.c.
References View2D::align, ARegion::alignment, BLI_addtail(), View2D::keepofs, View2D::keeptot, View2D::keepzoom, SpaceConsole::lheight, View2D::maxzoom, MEM_callocN(), View2D::minzoom, SpaceConsole::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, View2D::scroll, SPACE_CONSOLE, SpaceConsole::spacetype, ARegion::v2d, V2D_ALIGN_NO_NEG_X, V2D_ALIGN_NO_NEG_Y, V2D_KEEPASPECT, V2D_KEEPTOT_BOUNDS, V2D_LIMITZOOM, V2D_LOCKOFS_X, V2D_LOCKZOOM_X, V2D_LOCKZOOM_Y, and V2D_SCROLL_RIGHT.
Referenced by ED_spacetype_console().
static void console_operatortypes (void) [static]
Definition at line 243 of file space_console.c.
References CONSOLE_OT_clear(), CONSOLE_OT_copy(), CONSOLE_OT_delete(), CONSOLE_OT_history_append(), CONSOLE_OT_history_cycle(), CONSOLE_OT_insert(), CONSOLE_OT_move(), CONSOLE_OT_paste(), CONSOLE_OT_scrollback_append(), CONSOLE_OT_select_set(), and WM_operatortype_append().
Referenced by ED_spacetype_console().
void ED_spacetype_console (void)
Definition at line 364 of file space_console.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), console_dropboxes(), console_duplicate(), console_free(), console_header_area_draw(), console_header_area_init(), console_init(), console_keymap(), console_main_area_draw(), console_main_area_init(), console_main_area_listener(), console_new(), console_operatortypes(), ARegionType::draw, SpaceType::dropboxes, SpaceType::duplicate, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizey, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_CONSOLE, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
static void id_drop_copy (wmDrag * drag, wmDropBox * drop) [static]
Definition at line 171 of file space_console.c.
References BKE_idcode_to_name_plural(), BLI_snprintf(), BLI_strescape(), GS, ID::name, wmDrag::poin, wmDropBox::ptr, and RNA_string_set().
Referenced by console_dropboxes().
static int id_drop_poll (bContext * UNUSEDC, wmDrag * drag, wmEvent * UNUSEDevent) [static]
Definition at line 163 of file space_console.c.
References wmDrag::type, and WM_DRAG_ID.
Referenced by console_dropboxes().
static void path_drop_copy (wmDrag * drag, wmDropBox * drop) [static]
Definition at line 193 of file space_console.c.
References BLI_snprintf(), FILE_MAX, wmDrag::path, wmDropBox::ptr, and RNA_string_set().
Referenced by console_dropboxes().
static int path_drop_poll (bContext * UNUSEDC, wmDrag * drag, wmEvent * UNUSEDevent) [static]
Definition at line 185 of file space_console.c.
References wmDrag::type, and WM_DRAG_PATH.
Referenced by console_dropboxes().