Blender: bmesh_py_types_meshdata.c File Reference
bmesh_py_types_meshdata.c File Reference
#include <Python.h>
#include "../mathutils/mathutils.h"
#include "DNA_meshdata_types.h"
#include "BLI_utildefines.h"
#include "BLI_math_vector.h"
#include "BKE_deform.h"
#include "bmesh_py_types_meshdata.h"
Classes
struct BPy_BMLoopUV
struct BPy_BMDeformVert
Defines
#define BPy_BMLoopUV_Check(v) (Py_TYPE(v) == &BPy_BMLoopUV_Type)
#define MLOOPCOL_FROM_CAPSULE(color_capsule) ((MLoopCol *)PyCapsule_GetPointer(color_capsule, NULL))
#define BPy_BMDeformVert_Check(v) (Py_TYPE(v) == &BPy_BMDeformVert_Type)
Typedefs
typedef struct BPy_BMLoopUV BPy_BMLoopUV
typedef struct BPy_BMDeformVert BPy_BMDeformVert
Functions
PyDoc_STRVAR (bpy_bmloopuv_uv_doc,"Loops UV (as a 2D Vector).\n\n:type: :class:`mathutils.Vector`")
static PyObject * bpy_bmloopuv_uv_get (BPy_BMLoopUV *self, void *UNUSED(closure))
static int bpy_bmloopuv_uv_set (BPy_BMLoopUV *self, PyObject *value, void *UNUSED(closure))
PyDoc_STRVAR (bpy_bmloopuv_flag__pin_uv_doc,"UV pin state.\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmloopuv_flag__select_doc,"UV select state.\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmloopuv_flag__select_edge_doc,"UV edge select state.\n\n:type: boolean")
static PyObject * bpy_bmloopuv_flag_get (BPy_BMLoopUV *self, void *flag_p)
static int bpy_bmloopuv_flag_set (BPy_BMLoopUV *self, PyObject *value, void *flag_p)
static void bm_init_types_bmloopuv (void)
int BPy_BMLoopUV_AssignPyObject (struct MLoopUV *mloopuv, PyObject *value)
PyObject * BPy_BMLoopUV_CreatePyObject (struct MLoopUV *mloopuv)
static void mloopcol_to_float (const MLoopCol *mloopcol, float col_r[3])
static void mloopcol_from_float (MLoopCol *mloopcol, const float col[3])
static int mathutils_bmloopcol_check (BaseMathObject *UNUSED(bmo))
static int mathutils_bmloopcol_get (BaseMathObject *bmo, int UNUSED(subtype))
static int mathutils_bmloopcol_set (BaseMathObject *bmo, int UNUSED(subtype))
static int mathutils_bmloopcol_get_index (BaseMathObject *bmo, int subtype, int UNUSED(index))
static int mathutils_bmloopcol_set_index (BaseMathObject *bmo, int subtype, int index)
static void bm_init_types_bmloopcol (void)
int BPy_BMLoopColor_AssignPyObject (struct MLoopCol *mloopcol, PyObject *value)
PyObject * BPy_BMLoopColor_CreatePyObject (struct MLoopCol *data)
static int bpy_bmdeformvert_len (BPy_BMDeformVert *self)
static PyObject * bpy_bmdeformvert_subscript (BPy_BMDeformVert *self, PyObject *key)
static int bpy_bmdeformvert_ass_subscript (BPy_BMDeformVert *self, PyObject *key, PyObject *value)
static int bpy_bmdeformvert_contains (BPy_BMDeformVert *self, PyObject *value)
PyDoc_STRVAR (bpy_bmdeformvert_keys_doc,".. method:: keys()\n""\n"" Return the group indices used by this vertex\n"" (matching pythons dict.keys() functionality).\n""\n"" :return: the deform group this vertex uses\n"" :rtype: list of ints\n")
static PyObject * bpy_bmdeformvert_keys (BPy_BMDeformVert *self)
PyDoc_STRVAR (bpy_bmdeformvert_values_doc,".. method:: items()\n""\n"" Return (group, weight) pairs for this vertex\n"" (matching pythons dict.items() functionality).\n""\n"" :return: (key, value) pairs for each deform weight of this vertex.\n"" :rtype: list of tuples\n")
static PyObject * bpy_bmdeformvert_values (BPy_BMDeformVert *self)
PyDoc_STRVAR (bpy_bmdeformvert_items_doc,".. method:: values()\n""\n"" Return the weights of the deform vertex\n"" (matching pythons dict.values() functionality).\n""\n"" :return: The weights that influence this vertex\n"" :rtype: list of floats\n")
static PyObject * bpy_bmdeformvert_items (BPy_BMDeformVert *self)
PyDoc_STRVAR (bpy_bmdeformvert_get_doc,".. method:: get(key, default=None)\n""\n"" Returns the deform weight matching the key or default\n"" when not found (matches pythons dictionary function of the same name).\n""\n"" :arg key: The key associated with deform weight.\n"" :type key: int\n"" :arg default: Optional argument for the value to return if\n"" *key* is not found.\n"" :type default: Undefined\n")
static PyObject * bpy_bmdeformvert_get (BPy_BMDeformVert *self, PyObject *args)
PyDoc_STRVAR (bpy_bmdeformvert_clear_doc,".. method:: clear()\n""\n"" Clears all weights.\n")
static PyObject * bpy_bmdeformvert_clear (BPy_BMDeformVert *self)
static void bm_init_types_bmdvert (void)
int BPy_BMDeformVert_AssignPyObject (struct MDeformVert *dvert, PyObject *value)
PyObject * BPy_BMDeformVert_CreatePyObject (struct MDeformVert *dvert)
void BPy_BM_init_types_meshdata (void)
Variables
static PyGetSetDef bpy_bmloopuv_getseters []
PyTypeObject BPy_BMLoopUV_Type = {{{0}}}
static unsigned char mathutils_bmloopcol_cb_index = -1
Mathutils_Callback mathutils_bmloopcol_cb
static PySequenceMethods bpy_bmdeformvert_as_sequence
static PyMappingMethods bpy_bmdeformvert_as_mapping
static struct PyMethodDef bpy_bmdeformvert_methods []
PyTypeObject BPy_BMDeformVert_Type = {{{0}}}
Detailed Description
This file defines customdata types which can't be accessed as primitive python types such as MDeformVert, MLoopUV, MTexPoly
Definition in file bmesh_py_types_meshdata.c.
Define Documentation
#define BPy_BMDeformVert_Check (v) (Py_TYPE(v) == &BPy_BMDeformVert_Type)
This is python type wraps a deform vert as a python dictionary, hiding the MDeformWeight on access, since the mapping is very close, eg:
C: weight = defvert_find_weight(dv, group_nr); defvert_remove_group(dv, dw)
Py: weight = dv[group_nr] del dv[group_nr]
Note:
: there is nothing BMesh spesific here, its only that BMesh is the only part of blender that uses a hand written api like this. This type could eventually be used to access lattice weights.
: Many of blender-api's dict-like-wrappers act like ordered dicts, This is intentional _not_ ordered, the weights can be in any order and it wont matter, the order should not be used in the api in any meaningful way (as with a python dict) only expose as mapping, not a sequence.
Definition at line 284 of file bmesh_py_types_meshdata.c.
Referenced by BPy_BMDeformVert_AssignPyObject().
#define BPy_BMLoopUV_Check (v) (Py_TYPE(v) == &BPy_BMLoopUV_Type)
Definition at line 49 of file bmesh_py_types_meshdata.c.
Referenced by BPy_BMLoopUV_AssignPyObject().
#define MLOOPCOL_FROM_CAPSULE (color_capsule) ((MLoopCol *)PyCapsule_GetPointer(color_capsule, NULL))
Definition at line 166 of file bmesh_py_types_meshdata.c.
Referenced by mathutils_bmloopcol_get(), and mathutils_bmloopcol_set().
Typedef Documentation
typedef struct BPy_BMDeformVert BPy_BMDeformVert
typedef struct BPy_BMLoopUV BPy_BMLoopUV
Function Documentation
static void bm_init_types_bmdvert (void) [static]
Definition at line 553 of file bmesh_py_types_meshdata.c.
References bpy_bmdeformvert_as_mapping, bpy_bmdeformvert_as_sequence, bpy_bmdeformvert_methods, and NULL.
Referenced by BPy_BM_init_types_meshdata().
static void bm_init_types_bmloopcol (void) [static]
Definition at line 229 of file bmesh_py_types_meshdata.c.
References Mathutils_RegisterCallback().
Referenced by BPy_BM_init_types_meshdata().
static void bm_init_types_bmloopuv (void) [static]
Definition at line 123 of file bmesh_py_types_meshdata.c.
References bpy_bmloopuv_getseters, and NULL.
Referenced by BPy_BM_init_types_meshdata().
void BPy_BM_init_types_meshdata (void)
Definition at line 597 of file bmesh_py_types_meshdata.c.
References bm_init_types_bmdvert(), bm_init_types_bmloopcol(), and bm_init_types_bmloopuv().
Referenced by BPyInit_bmesh().
static int bpy_bmdeformvert_ass_subscript (BPy_BMDeformVert * self, PyObject * key, PyObject * value) [static]
Definition at line 329 of file bmesh_py_types_meshdata.c.
References CLAMPIS, defvert_find_index(), defvert_remove_group(), defvert_verify_index(), i, NULL, and MDeformWeight::weight.
int BPy_BMDeformVert_AssignPyObject (struct MDeformVert * dvert, PyObject * value)
Definition at line 571 of file bmesh_py_types_meshdata.c.
References BPy_BMDeformVert_Check, defvert_copy(), LIKELY, and UNLIKELY.
Referenced by BPy_BMLayerItem_SetItem().
static PyObject* bpy_bmdeformvert_clear (BPy_BMDeformVert * self) [static]
Definition at line 534 of file bmesh_py_types_meshdata.c.
References defvert_clear().
static int bpy_bmdeformvert_contains (BPy_BMDeformVert * self, PyObject * value) [static]
Definition at line 381 of file bmesh_py_types_meshdata.c.
References defvert_find_index(), and NULL.
PyObject* BPy_BMDeformVert_CreatePyObject (struct MDeformVert * dvert)
Definition at line 586 of file bmesh_py_types_meshdata.c.
Referenced by BPy_BMLayerItem_GetItem().
static PyObject* bpy_bmdeformvert_get (BPy_BMDeformVert * self, PyObject * args) [static]
Definition at line 508 of file bmesh_py_types_meshdata.c.
References defvert_find_index(), NULL, and MDeformWeight::weight.
static PyObject* bpy_bmdeformvert_items (BPy_BMDeformVert * self) [static]
Definition at line 476 of file bmesh_py_types_meshdata.c.
References MDeformWeight::def_nr, i, and MDeformWeight::weight.
static PyObject* bpy_bmdeformvert_keys (BPy_BMDeformVert * self) [static]
Definition at line 430 of file bmesh_py_types_meshdata.c.
References MDeformWeight::def_nr, and i.
static int bpy_bmdeformvert_len (BPy_BMDeformVert * self) [static]
Definition at line 295 of file bmesh_py_types_meshdata.c.
static PyObject* bpy_bmdeformvert_subscript (BPy_BMDeformVert * self, PyObject * key) [static]
Definition at line 300 of file bmesh_py_types_meshdata.c.
References defvert_find_index(), i, NULL, and MDeformWeight::weight.
static PyObject* bpy_bmdeformvert_values (BPy_BMDeformVert * self) [static]
Definition at line 453 of file bmesh_py_types_meshdata.c.
References i, and MDeformWeight::weight.
int BPy_BMLoopColor_AssignPyObject (struct MLoopCol * mloopcol, PyObject * value)
Definition at line 235 of file bmesh_py_types_meshdata.c.
References mathutils_array_parse(), and mloopcol_from_float().
Referenced by BPy_BMLayerItem_SetItem().
PyObject* BPy_BMLoopColor_CreatePyObject (struct MLoopCol * data)
Definition at line 247 of file bmesh_py_types_meshdata.c.
References Color_CreatePyObject_cb(), and NULL.
Referenced by BPy_BMLayerItem_GetItem().
int BPy_BMLoopUV_AssignPyObject (struct MLoopUV * mloopuv, PyObject * value)
Definition at line 138 of file bmesh_py_types_meshdata.c.
References BPy_BMLoopUV_Check, and UNLIKELY.
Referenced by BPy_BMLayerItem_SetItem().
PyObject* BPy_BMLoopUV_CreatePyObject (struct MLoopUV * mloopuv)
Definition at line 150 of file bmesh_py_types_meshdata.c.
Referenced by BPy_BMLayerItem_GetItem().
static PyObject* bpy_bmloopuv_flag_get (BPy_BMLoopUV * self, void * flag_p) [static]
Definition at line 87 of file bmesh_py_types_meshdata.c.
References GET_INT_FROM_POINTER.
static int bpy_bmloopuv_flag_set (BPy_BMLoopUV * self, PyObject * value, void * flag_p) [static]
Definition at line 93 of file bmesh_py_types_meshdata.c.
References FALSE, GET_INT_FROM_POINTER, and TRUE.
static PyObject* bpy_bmloopuv_uv_get (BPy_BMLoopUV * self, void * UNUSEDclosure) [static]
Definition at line 59 of file bmesh_py_types_meshdata.c.
References NULL, Py_WRAP, and Vector_CreatePyObject().
static int bpy_bmloopuv_uv_set (BPy_BMLoopUV * self, PyObject * value, void * UNUSEDclosure) [static]
Definition at line 64 of file bmesh_py_types_meshdata.c.
References copy_v2_v2(), and mathutils_array_parse().
static int mathutils_bmloopcol_check (BaseMathObject * UNUSEDbmo) [static]
Definition at line 181 of file bmesh_py_types_meshdata.c.
static int mathutils_bmloopcol_get (BaseMathObject * bmo, int UNUSEDsubtype) [static]
Definition at line 187 of file bmesh_py_types_meshdata.c.
References MLOOPCOL_FROM_CAPSULE, and mloopcol_to_float().
Referenced by mathutils_bmloopcol_get_index(), and mathutils_bmloopcol_set_index().
static int mathutils_bmloopcol_get_index (BaseMathObject * bmo, int subtype, int UNUSEDindex) [static]
Definition at line 201 of file bmesh_py_types_meshdata.c.
References mathutils_bmloopcol_get().
static int mathutils_bmloopcol_set (BaseMathObject * bmo, int UNUSEDsubtype) [static]
Definition at line 194 of file bmesh_py_types_meshdata.c.
References MLOOPCOL_FROM_CAPSULE, and mloopcol_from_float().
Referenced by mathutils_bmloopcol_set_index().
static int mathutils_bmloopcol_set_index (BaseMathObject * bmo, int subtype, int index) [static]
Definition at line 209 of file bmesh_py_types_meshdata.c.
References mathutils_bmloopcol_get(), and mathutils_bmloopcol_set().
static void mloopcol_from_float (MLoopCol * mloopcol, const float col[3]) [static]
Definition at line 174 of file bmesh_py_types_meshdata.c.
References MLoopCol::r, and rgb_float_to_uchar().
Referenced by BPy_BMLoopColor_AssignPyObject(), and mathutils_bmloopcol_set().
static void mloopcol_to_float (const MLoopCol * mloopcol, float col_r[3]) [static]
Definition at line 169 of file bmesh_py_types_meshdata.c.
References MLoopCol::r, and rgb_uchar_to_float().
Referenced by mathutils_bmloopcol_get().
PyDoc_STRVAR (bpy_bmdeformvert_items_doc , ".. method:: values()\n""\n"" Return the weights of the deform vertex\n"" (matching pythons dict.values() functionality).\n""\n"" :return: The weights that influence this vertex\n"" :rtype: list of floats\n")
PyDoc_STRVAR (bpy_bmloopuv_flag__select_edge_doc , "UV edge select state.\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmloopuv_uv_doc , "Loops UV (as a 2D Vector).\n\n:type: :class:`mathutils.Vector`")
PyDoc_STRVAR (bpy_bmdeformvert_clear_doc , ".. method:: clear()\n""\n"" Clears all weights.\n")
PyDoc_STRVAR (bpy_bmdeformvert_keys_doc , ".. method:: keys()\n""\n"" Return the group indices used by this vertex\n"" (matching pythons dict.keys() functionality).\n""\n"" :return: the deform group this vertex uses\n"" :rtype: list of ints\n")
PyDoc_STRVAR (bpy_bmdeformvert_values_doc , ".. method:: items()\n""\n"" Return (group, weight) pairs for this vertex\n"" (matching pythons dict.items() functionality).\n""\n"" :return: (key, value) pairs for each deform weight of this vertex.\n"" :rtype: list of tuples\n")
PyDoc_STRVAR (bpy_bmloopuv_flag__select_doc , "UV select state.\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmloopuv_flag__pin_uv_doc , "UV pin state.\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmdeformvert_get_doc , ".. method:: get(key, default=None)\n""\n"" Returns the deform weight matching the key or default\n"" when not found (matches pythons dictionary function of the same name).\n""\n"" :arg key: The key associated with deform weight.\n"" :type key: int\n"" :arg default: Optional argument for the value to return if\n"" *key* is not found.\n"" :type default: Undefined\n")
Variable Documentation
PyMappingMethods bpy_bmdeformvert_as_mapping [static]
Initial value:
 {
    (lenfunc)bpy_bmdeformvert_len,
    (binaryfunc)bpy_bmdeformvert_subscript,
    (objobjargproc)bpy_bmdeformvert_ass_subscript
}
Definition at line 412 of file bmesh_py_types_meshdata.c.
Referenced by bm_init_types_bmdvert().
PySequenceMethods bpy_bmdeformvert_as_sequence [static]
Initial value:
 {
    (lenfunc)bpy_bmdeformvert_len,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    (objobjproc)bpy_bmdeformvert_contains,
    (binaryfunc) NULL,
    (ssizeargfunc) NULL,
}
Definition at line 395 of file bmesh_py_types_meshdata.c.
Referenced by bm_init_types_bmdvert().
struct PyMethodDef bpy_bmdeformvert_methods[] [static]
Initial value:
 {
    {"keys",    (PyCFunction)bpy_bmdeformvert_keys,    METH_NOARGS,  bpy_bmdeformvert_keys_doc},
    {"values",  (PyCFunction)bpy_bmdeformvert_values,  METH_NOARGS,  bpy_bmdeformvert_values_doc},
    {"items",   (PyCFunction)bpy_bmdeformvert_items,   METH_NOARGS,  bpy_bmdeformvert_items_doc},
    {"get",     (PyCFunction)bpy_bmdeformvert_get,     METH_VARARGS, bpy_bmdeformvert_get_doc},
    {"clear",   (PyCFunction)bpy_bmdeformvert_clear,   METH_NOARGS,  bpy_bmdeformvert_clear_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 541 of file bmesh_py_types_meshdata.c.
Referenced by bm_init_types_bmdvert().
PyTypeObject BPy_BMDeformVert_Type = {{{0}}}
Definition at line 551 of file bmesh_py_types_meshdata.c.
Referenced by BPyInit_bmesh_types().
PyGetSetDef bpy_bmloopuv_getseters[] [static]
Initial value:
 {
    {(char *)"uv",          (getter)bpy_bmloopuv_uv_get,   (setter)bpy_bmloopuv_uv_set,   (char *)bpy_bmloopuv_uv_doc, NULL},
    {(char *)"pin_uv",      (getter)bpy_bmloopuv_flag_get, (setter)bpy_bmloopuv_flag_set, (char *)bpy_bmloopuv_flag__pin_uv_doc, (void *)MLOOPUV_PINNED},
    {(char *)"select",      (getter)bpy_bmloopuv_flag_get, (setter)bpy_bmloopuv_flag_set, (char *)bpy_bmloopuv_flag__select_doc, (void *)MLOOPUV_VERTSEL},
    {(char *)"select_edge", (getter)bpy_bmloopuv_flag_get, (setter)bpy_bmloopuv_flag_set, (char *)bpy_bmloopuv_flag__select_edge_doc, (void *)MLOOPUV_EDGESEL},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 111 of file bmesh_py_types_meshdata.c.
Referenced by bm_init_types_bmloopuv().
PyTypeObject BPy_BMLoopUV_Type = {{{0}}}
Definition at line 121 of file bmesh_py_types_meshdata.c.
Referenced by BPyInit_bmesh_types().
Mathutils_Callback mathutils_bmloopcol_cb
Initial value:
 {
    mathutils_bmloopcol_check,
    mathutils_bmloopcol_get,
    mathutils_bmloopcol_set,
    mathutils_bmloopcol_get_index,
    mathutils_bmloopcol_set_index
}
Definition at line 221 of file bmesh_py_types_meshdata.c.
unsigned char mathutils_bmloopcol_cb_index = -1 [static]
Definition at line 179 of file bmesh_py_types_meshdata.c.