Blender: ED_armature.h File Reference
ED_armature.h File Reference
Editors
Classes
struct EditBone
Defines
#define BONESEL_ROOT (1<<28)
#define BONESEL_TIP (1<<29)
#define BONESEL_BONE (1<<30)
#define BONESEL_ANY (BONESEL_TIP|BONESEL_ROOT|BONESEL_BONE)
#define BONESEL_NOSEL (1<<31)
#define EBONE_VISIBLE(arm, ebone) (((arm)->layer & (ebone)->layer) && !((ebone)->flag & BONE_HIDDEN_A))
#define EBONE_EDITABLE(ebone) (((ebone)->flag & BONE_SELECTED) && !((ebone)->flag & BONE_EDITMODE_LOCKED))
#define BONE_SELECT_PARENT 0
#define BONE_SELECT_CHILD 1
#define ARM_GROUPS_NAME 1
#define ARM_GROUPS_ENVELOPE 2
#define ARM_GROUPS_AUTO 3
Typedefs
typedef struct EditBone EditBone
Functions
void ED_operatortypes_armature (void)
void ED_operatormacros_armature (void)
void ED_keymap_armature (struct wmKeyConfig *keyconf)
void ED_armature_from_edit (struct Object *obedit)
void ED_armature_to_edit (struct Object *ob)
void ED_armature_edit_free (struct Object *ob)
void ED_armature_deselect_all (struct Object *obedit, int toggle)
void ED_armature_deselect_all_visible (struct Object *obedit)
int ED_do_pose_selectbuffer (struct Scene *scene, struct Base *base, unsigned int *buffer, short hits, short extend)
int mouse_armature (struct bContext *C, const int mval[2], int extend)
int join_armature_exec (struct bContext *C, struct wmOperator *op)
struct Bone * get_indexed_bone (struct Object *ob, int index)
float ED_rollBoneToVector (EditBone *bone, const float new_up_axis[3], const short axis_only)
EditBone * ED_armature_bone_get_mirrored (struct ListBase *edbo, EditBone *ebo)
void ED_armature_sync_selection (struct ListBase *edbo)
void ED_armature_validate_active (struct bArmature *arm)
void add_primitive_bone (struct Scene *scene, struct View3D *v3d, struct RegionView3D *rv3d)
struct EditBone * ED_armature_edit_bone_add (struct bArmature *arm, const char *name)
void ED_armature_edit_bone_remove (struct bArmature *arm, EditBone *exBone)
void transform_armature_mirror_update (struct Object *obedit)
void docenter_armature (struct Scene *scene, struct Object *ob, float cursor[3], int centermode, int around)
void ED_armature_apply_transform (struct Object *ob, float mat[4][4])
void create_vgroups_from_armature (struct ReportList *reports, struct Scene *scene, struct Object *ob, struct Object *par, int mode, int mirror)
void unique_editbone_name (struct ListBase *ebones, char *name, EditBone *bone)
void ED_armature_bone_rename (struct bArmature *arm, const char *oldnamep, const char *newnamep)
void undo_push_armature (struct bContext *C, const char *name)
void ED_armature_exit_posemode (struct bContext *C, struct Base *base)
void ED_armature_enter_posemode (struct bContext *C, struct Base *base)
int ED_pose_channel_in_IK_chain (struct Object *ob, struct bPoseChannel *pchan)
void ED_pose_deselectall (struct Object *ob, int test)
void ED_pose_recalculate_paths (struct Scene *scene, struct Object *ob)
int ED_operator_sketch_mode_active_stroke (struct bContext *C)
int ED_operator_sketch_full_mode (struct bContext *C)
int ED_operator_sketch_mode (const struct bContext *C)
void BIF_convertSketch (struct bContext *C)
void BIF_deleteSketch (struct bContext *C)
void BIF_selectAllSketch (struct bContext *C, int mode)
void BIF_makeListTemplates (const struct bContext *C)
const char * BIF_listTemplates (const struct bContext *C)
int BIF_currentTemplate (const struct bContext *C)
void BIF_freeTemplates (struct bContext *C)
void BIF_setTemplate (struct bContext *C, int index)
int BIF_nbJointsTemplate (const struct bContext *C)
const char * BIF_nameBoneTemplate (const struct bContext *C)
void BDR_drawSketch (const struct bContext *vc)
int BDR_drawSketchNames (struct ViewContext *vc)
void mesh_deform_bind (struct Scene *scene, struct MeshDeformModifierData *mmd, float *vertexcos, int totvert, float cagemat[][4])
Detailed Description
Definition in file ED_armature.h.
Define Documentation
#define ARM_GROUPS_AUTO 3
Definition at line 137 of file ED_armature.h.
Referenced by create_vgroups_from_armature(), ED_object_parent_set(), and PAINT_OT_weight_from_bones().
#define ARM_GROUPS_ENVELOPE 2
Definition at line 136 of file ED_armature.h.
Referenced by create_vgroups_from_armature(), ED_object_parent_set(), and PAINT_OT_weight_from_bones().
#define ARM_GROUPS_NAME 1
Definition at line 135 of file ED_armature.h.
Referenced by create_vgroups_from_armature(), and ED_object_parent_set().
#define BONE_SELECT_CHILD 1
Definition at line 102 of file ED_armature.h.
Referenced by ARMATURE_OT_select_hierarchy(), ED_keymap_armature(), and POSE_OT_select_hierarchy().
#define BONE_SELECT_PARENT 0
Definition at line 101 of file ED_armature.h.
Referenced by ARMATURE_OT_select_hierarchy(), armature_select_hierarchy_exec(), ED_keymap_armature(), POSE_OT_select_hierarchy(), and pose_select_hierarchy_exec().
#define BONESEL_ANY (BONESEL_TIP|BONESEL_ROOT|BONESEL_BONE)
Definition at line 92 of file ED_armature.h.
Referenced by do_armature_box_select(), do_object_pose_box_select(), get_bone_from_selectbuffer(), and get_nearest_editbonepoint().
#define BONESEL_BONE (1<<30)
Definition at line 91 of file ED_armature.h.
Referenced by do_armature_box_select(), draw_b_bone(), draw_bone(), draw_custom_bone(), draw_line_bone(), draw_sphere_bone(), draw_sphere_bone_wire(), draw_wire_bone(), and get_nearest_editbonepoint().
#define BONESEL_NOSEL (1<<31)
Definition at line 94 of file ED_armature.h.
Referenced by get_bone_from_selectbuffer(), and get_nearest_editbonepoint().
#define BONESEL_ROOT (1<<28)
Definition at line 89 of file ED_armature.h.
Referenced by do_armature_box_select(), draw_bone_points(), draw_line_bone(), draw_sphere_bone(), draw_sphere_bone_wire(), and get_nearest_editbonepoint().
#define BONESEL_TIP (1<<29)
Definition at line 90 of file ED_armature.h.
Referenced by do_armature_box_select(), draw_bone_points(), draw_line_bone(), draw_sphere_bone(), draw_sphere_bone_wire(), and get_nearest_editbonepoint().
#define EBONE_EDITABLE (ebone) (((ebone)->flag & BONE_SELECTED) && !((ebone)->flag & BONE_EDITMODE_LOCKED))
Definition at line 98 of file ED_armature.h.
Referenced by armature_calc_roll_exec(), and ed_screen_context().
#define EBONE_VISIBLE (arm, ebone) (((arm)->layer & (ebone)->layer) && !((ebone)->flag & BONE_HIDDEN_A))
Definition at line 97 of file ED_armature.h.
Referenced by armature_calc_roll_exec(), armature_click_extrude_exec(), armature_duplicate_selected_exec(), armature_extrude_exec(), armature_hide_exec(), armature_merge_exec(), armature_select_hierarchy_exec(), calc_manipulator_stats(), createTransArmatureVerts(), do_lasso_select_armature(), draw_ebones(), ED_armature_deselect_all(), ED_armature_deselect_all_visible(), and ed_screen_context().
Typedef Documentation
typedef struct EditBone EditBone
Function Documentation
void add_primitive_bone (struct Scene * scene, struct View3D * v3d, struct RegionView3D * rv3d)
Definition at line 2246 of file editarmature.c.
References bArmature::act_edbone, add_v3_v3v3(), copy_m3_m4(), copy_v3_v3(), Object::data, ED_armature_deselect_all(), ED_armature_edit_bone_add(), give_cursor(), EditBone::head, Object::imat, invert_m3_m3(), invert_m4_m4(), mul_m3_m3m3(), mul_v3_m4v3(), Scene::obedit, Object::obmat, EditBone::tail, unit_m3(), USER_ADD_VIEWALIGNED, and RegionView3D::viewmat.
Referenced by object_armature_add_exec().
void BDR_drawSketch (const struct bContext * vc)
int BDR_drawSketchNames (struct ViewContext * vc)
Definition at line 2437 of file editarmature_sketch.c.
References ViewContext::scene, sk_drawSketch(), ViewContext::v3d, ValidSketchViewContext(), and viewcontextSketch().
Referenced by view3d_opengl_select().
void BIF_convertSketch (struct bContext * C)
Definition at line 2488 of file editarmature_sketch.c.
References contextSketch(), ED_operator_sketch_full_mode(), and sk_convert().
int BIF_currentTemplate (const struct bContext * C)
void BIF_deleteSketch (struct bContext * C)
Definition at line 2503 of file editarmature_sketch.c.
References contextSketch(), ED_operator_sketch_full_mode(), and sk_deleteSelectedStrokes().
void BIF_freeTemplates (struct bContext * C)
const char* BIF_listTemplates (const struct bContext * C)
void BIF_makeListTemplates (const struct bContext * C)
const char* BIF_nameBoneTemplate (const struct bContext * C)
int BIF_nbJointsTemplate (const struct bContext * C)
void BIF_selectAllSketch (struct bContext * C, int mode)
void BIF_setTemplate (struct bContext * C, int index)
Definition at line 336 of file editarmature_sketch.c.
References BLI_ghash_lookup(), CTX_data_tool_settings(), NULL, RIG_freeRigGraph(), SET_INT_IN_POINTER, and ToolSettings::skgen_template.
void create_vgroups_from_armature (struct ReportList * reports, struct Scene * scene, struct Object * ob, struct Object * par, int mode, int mirror)
Definition at line 4736 of file editarmature.c.
References add_verts_to_dgroups(), ARM_GROUPS_AUTO, ARM_GROUPS_ENVELOPE, ARM_GROUPS_NAME, bone_looper(), bArmature::bonebase, Object::data, ED_vgroup_data_create(), ListBase::first, NULL, OB_MESH, Object::type, and vgroup_add_unique_bone_cb().
Referenced by ED_object_parent_set(), and weight_from_bones_exec().
void docenter_armature (struct Scene * scene, struct Object * ob, float cursor[3], int centermode, int around)
Definition at line 537 of file editarmature.c.
References add_v3_v3(), copy_v3_v3(), Object::data, DO_MINMAX, ED_armature_edit_free(), ED_armature_from_edit(), ED_armature_to_edit(), bArmature::edbo, ListBase::first, EditBone::head, Object::imat, INIT_MINMAX, invert_m4_m4(), Object::loc, max, mid_v3_v3v3(), min, mul_m4_v3(), mul_mat3_m4_v3(), mul_v3_fl(), EditBone::next, NULL, Scene::obedit, Object::obmat, sub_v3_v3(), EditBone::tail, V3D_CENTROID, and zero_v3().
Referenced by object_origin_set_exec().
void ED_armature_apply_transform (struct Object * ob, float mat[4][4])
Definition at line 490 of file editarmature.c.
References copy_m3_m4(), Object::data, EditBone::dist, ED_armature_edit_free(), ED_armature_from_edit(), ED_armature_to_edit(), bArmature::edbo, ListBase::first, EditBone::head, mat3_to_vec_roll(), mat4_to_scale(), mul_m3_m3m3(), mul_m4_v3(), EditBone::next, normalize_m3(), NULL, EditBone::rad_head, EditBone::rad_tail, EditBone::roll, sub_v3_v3v3(), EditBone::tail, vec_roll_to_mat3(), EditBone::xwidth, and EditBone::zwidth.
Referenced by apply_objects_internal().
EditBone* ED_armature_bone_get_mirrored (struct ListBase * edbo, EditBone * ebo)
Definition at line 161 of file editarmature.c.
References FALSE, ListBase::first, flip_side_name(), MAXBONENAME, EditBone::name, EditBone::next, and NULL.
Referenced by armature_align_bones_exec(), armature_calc_roll_exec(), armature_click_extrude_exec(), armature_duplicate_selected_exec(), armature_extrude_exec(), armature_parent_set_exec(), armature_select_mirrored(), armature_tag_select_mirrored(), ed_screen_context(), and transform_armature_mirror_update().
void ED_armature_bone_rename (struct bArmature * arm, const char * oldnamep, const char * newnamep)
Definition at line 5293 of file editarmature.c.
References bScreen::areabase, BKE_all_animdata_fix_paths_rename(), BLI_ghash_insert(), BLI_ghash_remove(), BLI_strncpy(), bPose::chanbase, bPose::chanhash, constraint_bone_name_fix(), bPoseChannel::constraints, Object::constraints, Object::data, defgroup_find_name(), bArmature::edbo, editbone_name_exists(), eModifierType_Hook, ListBase::first, G, get_named_bone(), get_pose_channel(), bScreen::id, bArmature::id, Object::id, MAXBONENAME, Object::modifiers, modifiers_usesArmature(), bDeformGroup::name, bPoseChannel::name, Bone::name, EditBone::name, SpaceLink::next, ScrArea::next, ModifierData::next, bPoseChannel::next, ID::next, NULL, View3D::ob_centre, View3D::ob_centre_bone, HookModifierData::object, PARBONE, Object::parent, Object::parsubstr, Object::partype, Object::pose, SPACE_VIEW3D, ScrArea::spacedata, SpaceLink::spacetype, HookModifierData::subtarget, ModifierData::type, unique_bone_name(), and unique_editbone_name().
Referenced by armature_autoside_names_exec(), armature_flip_names_exec(), namebutton_cb(), pose_autoside_names_exec(), and pose_flip_names_exec().
void ED_armature_deselect_all (struct Object * obedit, int toggle)
Definition at line 1766 of file editarmature.c.
References bArmature::act_edbone, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, Object::data, EBONE_VISIBLE, ED_armature_sync_selection(), bArmature::edbo, ListBase::first, EditBone::flag, EditBone::next, NULL, and EditBone::parent.
Referenced by add_primitive_bone(), armature_bone_primitive_add_exec(), armature_click_extrude_exec(), mouse_armature(), and tree_element_active_ebone().
void ED_armature_deselect_all_visible (struct Object * obedit)
Definition at line 1815 of file editarmature.c.
References BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, BONE_UNSELECTABLE, Object::data, EBONE_VISIBLE, ED_armature_sync_selection(), bArmature::edbo, ListBase::first, EditBone::flag, and EditBone::next.
Referenced by do_armature_box_select(), and do_lasso_select_armature().
struct EditBone* ED_armature_edit_bone_add (struct bArmature * arm, const char * name) [read]
Definition at line 2221 of file editarmature.c.
References BLI_addtail(), BLI_strncpy(), BONE_TIPSEL, EditBone::dist, EditBone::ease1, EditBone::ease2, bArmature::edbo, EditBone::flag, bArmature::layer, EditBone::layer, MEM_callocN(), EditBone::name, NULL, EditBone::rad_head, EditBone::rad_tail, EditBone::segments, unique_editbone_name(), EditBone::weight, EditBone::xwidth, and EditBone::zwidth.
Referenced by add_points_bone(), add_primitive_bone(), armature_bone_primitive_add_exec(), armature_click_extrude_exec(), sk_convertStroke(), and subdivideArcBy().
void ED_armature_edit_bone_remove (struct bArmature * arm, EditBone * exBone)
Definition at line 145 of file editarmature.c.
References BONE_CONNECTED, bone_free(), bArmature::edbo, ListBase::first, EditBone::flag, EditBone::next, and EditBone::parent.
Referenced by armature_delete_selected_exec().
void ED_armature_edit_free (struct Object * ob)
Definition at line 1921 of file editarmature.c.
References BLI_freelistN(), Object::data, bArmature::edbo, ListBase::first, IDP_FreeProperty(), MEM_freeN(), EditBone::next, NULL, and EditBone::prop.
Referenced by apply_armature_pose2bones_exec(), docenter_armature(), ED_armature_apply_transform(), ED_armature_to_edit(), ED_editors_exit(), ED_object_exit_editmode(), join_armature_exec(), separate_armature_bones(), and separate_armature_exec().
void ED_armature_enter_posemode (struct bContext * C, struct Base * base)
Definition at line 84 of file poseobject.c.
References BKE_report(), CTX_wm_reports(), Object::id, ID::lib, Object::mode, NC_SCENE, ND_MODE, NS_MODE_POSE, NULL, OB_ARMATURE, OB_MODE_POSE, Base::object, Object::restore_mode, RPT_WARNING, Object::type, and WM_event_add_notifier().
Referenced by posemode_exec(), and tree_element_active_pose().
void ED_armature_exit_posemode (struct bContext * C, struct Base * base)
Definition at line 110 of file poseobject.c.
References Object::mode, NC_SCENE, ND_MODE, NS_MODE_OBJECT, NULL, OB_MODE_POSE, Base::object, Object::restore_mode, and WM_event_add_notifier().
Referenced by posemode_exec(), and tree_element_active_pose().
void ED_armature_from_edit (struct Object * obedit)
Definition at line 376 of file editarmature.c.
References bArmature::act_bone, bArmature::act_edbone, Bone::arm_head, Bone::arm_roll, Bone::arm_tail, armature_rebuild_pose(), BLI_addtail(), BLI_strncpy(), bone_free(), bArmature::bonebase, Bone::childbase, copy_v3_v3(), DAG_id_tag_update(), Object::data, EditBone::dist, Bone::dist, EditBone::ease1, Bone::ease1, EditBone::ease2, Bone::ease2, bArmature::edbo, ListBase::first, fix_bonelist_roll(), EditBone::flag, Bone::flag, free_bonelist(), G, G_DEBUG, Bone::head, EditBone::head, Object::id, IDP_CopyProperty(), if(), invert_m3_m3(), EditBone::layer, Bone::layer, len(), len_v3v3(), MEM_callocN(), mul_m3_v3(), Bone::name, EditBone::name, ID::next, EditBone::next, NULL, OB_RECALC_DATA, Bone::parent, EditBone::parent, Bone::prop, EditBone::prop, EditBone::rad_head, Bone::rad_head, EditBone::rad_tail, Bone::rad_tail, Bone::roll, EditBone::roll, EditBone::segments, Bone::segments, sub_v3_v3v3(), Bone::tail, EditBone::tail, EditBone::temp, vec_roll_to_mat3(), EditBone::weight, Bone::weight, EditBone::xwidth, Bone::xwidth, EditBone::zwidth, and Bone::zwidth.
Referenced by adjustGraphs(), apply_armature_pose2bones_exec(), docenter_armature(), ED_armature_apply_transform(), ED_object_exit_editmode(), join_armature_exec(), retargetGraphs(), separate_armature_bones(), and separate_armature_exec().
void ED_armature_sync_selection (struct ListBase * edbo)
Definition at line 100 of file editarmature.c.
References BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, BONE_UNSELECTABLE, ListBase::first, EditBone::flag, EditBone::next, and EditBone::parent.
Referenced by armature_circle_select(), armature_click_extrude_exec(), armature_delete_selected_exec(), armature_duplicate_selected_exec(), armature_extrude_exec(), armature_hide_exec(), armature_merge_exec(), armature_parent_clear_exec(), armature_reveal_exec(), armature_select_hierarchy_exec(), armature_select_linked_invoke(), bones_merge(), do_armature_box_select(), do_lasso_select_armature(), ED_armature_deselect_all(), ED_armature_deselect_all_visible(), and mouse_armature().
void ED_armature_to_edit (struct Object * ob)
Definition at line 1944 of file editarmature.c.
References bArmature::act_bone, bArmature::act_edbone, bArmature::bonebase, Object::data, ED_armature_edit_free(), bArmature::edbo, make_boneList(), MEM_callocN(), and NULL.
Referenced by apply_armature_pose2bones_exec(), docenter_armature(), ED_armature_apply_transform(), ED_object_enter_editmode(), join_armature_exec(), separate_armature_bones(), and separate_armature_exec().
void ED_armature_validate_active (struct bArmature * arm)
Definition at line 122 of file editarmature.c.
References bArmature::act_edbone, BONE_HIDDEN_A, EditBone::flag, and NULL.
Referenced by armature_circle_select(), armature_duplicate_selected_exec(), armature_hide_exec(), armature_reveal_exec(), BIF_retargetArc(), and do_lasso_select_armature().
int ED_do_pose_selectbuffer (struct Scene * scene, struct Base * base, unsigned int * buffer, short hits, short extend)
Definition at line 4285 of file editarmature.c.
References bArmature::act_bone, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, BONE_UNSELECTABLE, DAG_id_tag_update(), Object::data, ED_pose_deselectall(), ED_vgroup_select_by_name(), Bone::flag, get_bone_from_selectbuffer(), Object::mode, Bone::name, NULL, OB_MODE_WEIGHT_PAINT, OB_RECALC_DATA, OBACT, Base::object, and Object::pose.
Referenced by mouse_select().
void ED_keymap_armature (struct wmKeyConfig * keyconf)
Definition at line 202 of file armature_ops.c.
References ACCENTGRAVEKEY, AKEY, BONE_SELECT_CHILD, BONE_SELECT_PARENT, CKEY, DELKEY, DKEY, ED_operator_editarmature(), ED_operator_posemode(), EKEY, ESCKEY, FALSE, FKEY, GKEY, HKEY, IKEY, KM_ALT, KM_ANY, KM_CLICK, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTBRACKETKEY, LEFTMOUSE, LKEY, MKEY, MOUSEMOVE, NKEY, PKEY, wmKeyMap::poll, wmKeyMapItem::ptr, RIGHTBRACKETKEY, RIGHTMOUSE, RKEY, RNA_boolean_set(), RNA_enum_set(), SEL_INVERT, SEL_TOGGLE, SKEY, TFM_BONE_ROLL, TFM_BONESIZE, TRUE, VKEY, WKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), WM_keymap_verify_item(), and XKEY.
Referenced by ED_spacetypes_keymap().
int ED_operator_sketch_full_mode (struct bContext * C)
Definition at line 2802 of file editarmature_sketch.c.
References ToolSettings::bone_sketching, BONE_SKETCHING, BONE_SKETCHING_QUICK, CTX_data_edit_object(), CTX_data_tool_settings(), OB_ARMATURE, and Object::type.
Referenced by BIF_convertSketch(), BIF_deleteSketch(), SKETCH_OT_convert(), SKETCH_OT_delete(), and SKETCH_OT_select().
int ED_operator_sketch_mode (const struct bContext * C)
int ED_operator_sketch_mode_active_stroke (struct bContext * C)
Definition at line 2767 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, ToolSettings::bone_sketching, BONE_SKETCHING, contextSketch(), CTX_data_tool_settings(), and NULL.
Referenced by SKETCH_OT_cancel_stroke(), SKETCH_OT_draw_preview(), and SKETCH_OT_finish_stroke().
void ED_operatormacros_armature (void)
Definition at line 168 of file armature_ops.c.
References wmOperatorType::description, FALSE, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorTypeMacro::ptr, RNA_boolean_set(), RNA_enum_set(), TRUE, WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().
void ED_operatortypes_armature (void)
Definition at line 55 of file armature_ops.c.
References ARMATURE_OT_align(), ARMATURE_OT_armature_layers(), ARMATURE_OT_autoside_names(), ARMATURE_OT_bone_layers(), ARMATURE_OT_bone_primitive_add(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_click_extrude(), ARMATURE_OT_delete(), ARMATURE_OT_duplicate(), ARMATURE_OT_extrude(), ARMATURE_OT_fill(), ARMATURE_OT_flip_names(), ARMATURE_OT_hide(), ARMATURE_OT_layers_show_all(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), ARMATURE_OT_parent_set(), ARMATURE_OT_reveal(), ARMATURE_OT_select_all(), ARMATURE_OT_select_hierarchy(), ARMATURE_OT_select_inverse(), ARMATURE_OT_select_linked(), ARMATURE_OT_separate(), ARMATURE_OT_subdivide(), ARMATURE_OT_switch_direction(), POSE_OT_armature_apply(), POSE_OT_armature_layers(), POSE_OT_autoside_names(), POSE_OT_bone_layers(), POSE_OT_breakdown(), POSE_OT_copy(), POSE_OT_flip_names(), POSE_OT_group_add(), POSE_OT_group_assign(), POSE_OT_group_deselect(), POSE_OT_group_move(), POSE_OT_group_remove(), POSE_OT_group_select(), POSE_OT_group_sort(), POSE_OT_group_unassign(), POSE_OT_hide(), POSE_OT_loc_clear(), POSE_OT_paste(), POSE_OT_paths_calculate(), POSE_OT_paths_clear(), POSE_OT_propagate(), POSE_OT_push(), POSE_OT_quaternions_flip(), POSE_OT_relax(), POSE_OT_reveal(), POSE_OT_rot_clear(), POSE_OT_rotation_mode_set(), POSE_OT_scale_clear(), POSE_OT_select_all(), POSE_OT_select_constraint_target(), POSE_OT_select_flip_active(), POSE_OT_select_grouped(), POSE_OT_select_hierarchy(), POSE_OT_select_linked(), POSE_OT_select_parent(), POSE_OT_transforms_clear(), POSE_OT_user_transforms_clear(), POSE_OT_visual_transform_apply(), POSELIB_OT_action_sanitise(), POSELIB_OT_apply_pose(), POSELIB_OT_browse_interactive(), POSELIB_OT_new(), POSELIB_OT_pose_add(), POSELIB_OT_pose_remove(), POSELIB_OT_pose_rename(), POSELIB_OT_unlink(), SKETCH_OT_cancel_stroke(), SKETCH_OT_convert(), SKETCH_OT_delete(), SKETCH_OT_draw_preview(), SKETCH_OT_draw_stroke(), SKETCH_OT_finish_stroke(), SKETCH_OT_gesture(), SKETCH_OT_select(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
int ED_pose_channel_in_IK_chain (struct Object * ob, struct bPoseChannel * pchan)
Definition at line 174 of file poseobject.c.
References pose_channel_in_IK_chain().
Referenced by draw_pose_dofs().
void ED_pose_deselectall (struct Object * ob, int test)
Definition at line 4352 of file editarmature.c.
References bPoseChannel::bone, BONE_HIDDEN_P, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, BONE_UNSELECTABLE, bPose::chanbase, Object::data, ELEM, ListBase::first, Bone::flag, bArmature::layer, Bone::layer, bPoseChannel::next, NULL, PBONE_VISIBLE, and Object::pose.
Referenced by ED_do_pose_selectbuffer(), tree_element_active_bone(), and tree_element_active_posechannel().
void ED_pose_recalculate_paths (struct Scene * scene, struct Object * ob)
Definition at line 187 of file poseobject.c.
References animviz_calc_motionpaths(), animviz_get_object_motionpaths(), ANIMVIZ_RECALC_PATHS, bPose::avs, BLI_freelistN(), NULL, Object::pose, and bAnimVizSettings::recalc.
Referenced by autokeyframe_pose_cb_func(), pose_calculate_paths_exec(), pose_clear_transform_generic_exec(), and poseAnim_mapping_autoKeyframe().
float ED_rollBoneToVector (EditBone * bone, const float new_up_axis[3], const short axis_only)
Definition at line 1961 of file editarmature.c.
References angle_v3v3(), cross_v3_v3v3(), dot_v3v3(), EditBone::head, is_zero_v3(), M_PI, negate_v3(), project_v3_v3v3(), sub_v3_v3v3(), EditBone::tail, and vec_roll_to_mat3().
Referenced by armature_calc_roll_exec(), recalcData_view3d(), rollBoneByQuat(), rollBoneByQuatAligned(), rollBoneByQuatJoint(), and setBoneRollFromNormal().
struct Bone* get_indexed_bone (struct Object * ob, int index) [read]
Definition at line 1263 of file editarmature.c.
References BLI_findlink(), bPoseChannel::bone, bPose::chanbase, NULL, and Object::pose.
Referenced by do_object_pose_box_select(), and get_bone_from_selectbuffer().
int join_armature_exec (struct bContext * C, struct wmOperator * op)
void mesh_deform_bind (struct Scene * scene, struct MeshDeformModifierData * mmd, float * vertexcos, int totvert, float cagemat[][4])
Definition at line 1953 of file meshlaplacian.c.
References MeshDeformModifierData::bindcagecos, MeshDeformModifierData::bindmat, MeshDeformBind::cagecos, MeshDeformBind::cagedm, MeshDeformBind::cagemat, CD_MASK_BAREMESH, MVert::co, copy_m4_m4(), copy_v3_v3(), end_progress_bar(), DerivedMesh::getNumVerts, DerivedMesh::getVertArray, harmonic_coordinates_bind(), MEM_callocN(), MEM_freeN(), mesh_create_derived_no_deform(), MOD_MDEF_VOLUME, MeshDeformModifierData::mode, modifier_mdef_compact_influences(), mul_m4_v3(), mul_v3_m4v3(), NULL, MeshDeformModifierData::object, Object::obmat, DerivedMesh::release, start_progress_bar(), MeshDeformModifierData::totcagevert, MeshDeformBind::totcagevert, MeshDeformModifierData::totvert, MeshDeformBind::totvert, MeshDeformBind::vertexcos, and waitcursor().
Referenced by meshdeform_bind_exec().
int mouse_armature (struct bContext * C, const int mval[2], int extend)
Definition at line 1842 of file editarmature.c.
References bArmature::act_edbone, BIF_sk_selectStroke(), BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, CTX_data_edit_object(), Object::data, ebone_select_flag(), ED_armature_deselect_all(), ED_armature_sync_selection(), bArmature::edbo, EditBone::flag, get_nearest_editbonepoint(), NC_OBJECT, ND_BONE_SELECT, NULL, ViewContext::obedit, EditBone::parent, view3d_set_viewcontext(), and WM_event_add_notifier().
Referenced by view3d_select_invoke().
void transform_armature_mirror_update (struct Object * obedit)
Definition at line 5530 of file editarmature.c.
References BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, copy_v3_v3(), Object::data, EditBone::dist, ED_armature_bone_get_mirrored(), bArmature::edbo, ListBase::first, EditBone::flag, EditBone::head, EditBone::next, EditBone::parent, EditBone::rad_head, EditBone::rad_tail, EditBone::roll, EditBone::tail, EditBone::xwidth, and EditBone::zwidth.
Referenced by recalcData_view3d(), and special_transvert_update().
void undo_push_armature (struct bContext * C, const char * name)
Definition at line 2209 of file editarmature.c.
References editBones_to_undoBones(), free_undoBones(), get_armature_edit(), NULL, undo_editmode_push(), and undoBones_to_editBones().
Referenced by ED_undo_push().
void unique_editbone_name (struct ListBase * ebones, char * name, EditBone * bone)
Definition at line 613 of file editarmature.c.
References BLI_uniquename_cb(), data, editbone_unique_check(), and EditBone::name.
Referenced by armature_extrude_exec(), armature_subdivide_exec(), duplicateEditBoneObjects(), ED_armature_bone_rename(), ED_armature_edit_bone_add(), join_armature_exec(), and renameTemplateBone().