Blender: module.c File Reference
module.c File Reference
IMage Buffer
#include <stddef.h>
#include "IMB_imbuf.h"
#include "IMB_filetype.h"
Functions
void IMB_init (void)
void IMB_exit (void)
Detailed Description
Definition in file module.c.
Function Documentation
void IMB_exit (void)
Definition at line 38 of file module.c.
References imb_filetypes_exit(), and imb_tile_cache_exit().
Referenced by free_blender(), and main().
void IMB_init (void)
Attention:
Defined in allocimbuf.c
Definition at line 32 of file module.c.
References imb_filetypes_init(), and imb_tile_cache_init().
Referenced by main().