Blender: action_edit.c File Reference
action_edit.c File Reference
action space
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "DNA_anim_types.h"
#include "DNA_gpencil_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "BKE_action.h"
#include "BKE_fcurve.h"
#include "BKE_nla.h"
#include "BKE_context.h"
#include "BKE_report.h"
#include "UI_view2d.h"
#include "ED_anim_api.h"
#include "ED_gpencil.h"
#include "ED_keyframing.h"
#include "ED_keyframes_edit.h"
#include "ED_screen.h"
#include "ED_transform.h"
#include "ED_markers.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "action_intern.h"
Defines
#define MAKE_CYCLIC_EXPO -1
#define CLEAR_CYCLIC_EXPO -2
Functions
static int act_new_exec (bContext *C, wmOperator *UNUSED(op))
void ACTION_OT_new (wmOperatorType *ot)
static int act_markers_make_local_poll (bContext *C)
static int act_markers_make_local_exec (bContext *C, wmOperator *UNUSED(op))
void ACTION_OT_markers_make_local (wmOperatorType *ot)
static void get_keyframe_extents (bAnimContext *ac, float *min, float *max, const short onlySel)
static int actkeys_previewrange_exec (bContext *C, wmOperator *UNUSED(op))
void ACTION_OT_previewrange_set (wmOperatorType *ot)
static int actkeys_viewall (bContext *C, const short onlySel)
static int actkeys_viewall_exec (bContext *C, wmOperator *UNUSED(op))
static int actkeys_viewsel_exec (bContext *C, wmOperator *UNUSED(op))
void ACTION_OT_view_all (wmOperatorType *ot)
void ACTION_OT_view_selected (wmOperatorType *ot)
static short copy_action_keys (bAnimContext *ac)
static short paste_action_keys (bAnimContext *ac, const eKeyPasteOffset offset_mode, const eKeyMergeMode merge_mode)
static int actkeys_copy_exec (bContext *C, wmOperator *op)
void ACTION_OT_copy (wmOperatorType *ot)
static int actkeys_paste_exec (bContext *C, wmOperator *op)
void ACTION_OT_paste (wmOperatorType *ot)
static void insert_action_keys (bAnimContext *ac, short mode)
static int actkeys_insertkey_exec (bContext *C, wmOperator *op)
void ACTION_OT_keyframe_insert (wmOperatorType *ot)
static void duplicate_action_keys (bAnimContext *ac)
static int actkeys_duplicate_exec (bContext *C, wmOperator *UNUSED(op))
static int actkeys_duplicate_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void ACTION_OT_duplicate (wmOperatorType *ot)
static void delete_action_keys (bAnimContext *ac)
static int actkeys_delete_exec (bContext *C, wmOperator *UNUSED(op))
void ACTION_OT_delete (wmOperatorType *ot)
static void clean_action_keys (bAnimContext *ac, float thresh)
static int actkeys_clean_exec (bContext *C, wmOperator *op)
void ACTION_OT_clean (wmOperatorType *ot)
static void sample_action_keys (bAnimContext *ac)
static int actkeys_sample_exec (bContext *C, wmOperator *UNUSED(op))
void ACTION_OT_sample (wmOperatorType *ot)
static void setexpo_action_keys (bAnimContext *ac, short mode)
static int actkeys_expo_exec (bContext *C, wmOperator *op)
void ACTION_OT_extrapolation_type (wmOperatorType *ot)
static void setipo_action_keys (bAnimContext *ac, short mode)
static int actkeys_ipo_exec (bContext *C, wmOperator *op)
void ACTION_OT_interpolation_type (wmOperatorType *ot)
static void sethandles_action_keys (bAnimContext *ac, short mode)
static int actkeys_handletype_exec (bContext *C, wmOperator *op)
void ACTION_OT_handle_type (wmOperatorType *ot)
static void setkeytype_action_keys (bAnimContext *ac, short mode)
static int actkeys_keytype_exec (bContext *C, wmOperator *op)
void ACTION_OT_keyframe_type (wmOperatorType *ot)
static int actkeys_framejump_exec (bContext *C, wmOperator *UNUSED(op))
void ACTION_OT_frame_jump (wmOperatorType *ot)
static void snap_action_keys (bAnimContext *ac, short mode)
static int actkeys_snap_exec (bContext *C, wmOperator *op)
void ACTION_OT_snap (wmOperatorType *ot)
static void mirror_action_keys (bAnimContext *ac, short mode)
static int actkeys_mirror_exec (bContext *C, wmOperator *op)
void ACTION_OT_mirror (wmOperatorType *ot)
Variables
static EnumPropertyItem prop_actkeys_insertkey_types []
static EnumPropertyItem prop_actkeys_expo_types []
static EnumPropertyItem prop_actkeys_snap_types []
static EnumPropertyItem prop_actkeys_mirror_types []
Detailed Description
Definition in file action_edit.c.
Define Documentation
#define CLEAR_CYCLIC_EXPO -2
Definition at line 940 of file action_edit.c.
Referenced by setexpo_action_keys().
#define MAKE_CYCLIC_EXPO -1
Definition at line 939 of file action_edit.c.
Referenced by setexpo_action_keys().
Function Documentation
static int act_markers_make_local_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 173 of file action_edit.c.
References SpaceAction::action, BLI_addtail(), BLI_remlink(), CTX_wm_space_action(), ED_context_get_markers(), ELEM, ListBase::first, SpaceAction::flag, if(), bAction::markers, NC_ANIMATION, NC_SCENE, ND_MARKERS, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, SACTION_POSEMARKERS_SHOW, SELECT, and WM_event_add_notifier().
Referenced by ACTION_OT_markers_make_local().
static int act_markers_make_local_poll (bContext * C) [static]
Definition at line 151 of file action_edit.c.
References SpaceAction::action, CTX_wm_space_action(), ED_context_get_markers(), ED_markers_get_first_selected(), ELEM, SpaceAction::flag, SpaceAction::mode, NULL, SACTCONT_ACTION, SACTCONT_SHAPEKEY, and SACTION_POSEMARKERS_SHOW.
Referenced by ACTION_OT_markers_make_local().
static int act_new_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 80 of file action_edit.c.
References add_empty_action(), copy_action(), PointerRNA::data, GS, PointerRNA::id, bAction::id, ID_AC, if(), NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_FINISHED, RNA_id_pointer_create(), RNA_property_pointer_get(), RNA_property_pointer_set(), RNA_property_update(), uiIDContextProperty(), ID::us, and WM_event_add_notifier().
Referenced by ACTION_OT_new().
void ACTION_OT_clean (wmOperatorType * ot)
Definition at line 854 of file action_edit.c.
References actkeys_clean_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_float(), and wmOperatorType::srna.
Referenced by action_operatortypes().
void ACTION_OT_copy (wmOperatorType * ot)
Definition at line 487 of file action_edit.c.
References actkeys_copy_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_delete (wmOperatorType * ot)
Definition at line 790 of file action_edit.c.
References actkeys_delete_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by action_operatortypes().
void ACTION_OT_duplicate (wmOperatorType * ot)
Definition at line 715 of file action_edit.c.
References actkeys_duplicate_exec(), actkeys_duplicate_invoke(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_extrapolation_type (wmOperatorType * ot)
Definition at line 1028 of file action_edit.c.
References actkeys_expo_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by action_operatortypes().
void ACTION_OT_frame_jump (wmOperatorType * ot)
Definition at line 1318 of file action_edit.c.
References actkeys_framejump_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_handle_type (wmOperatorType * ot)
Definition at line 1179 of file action_edit.c.
References actkeys_handletype_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, keyframe_handle_type_items, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by action_operatortypes().
void ACTION_OT_interpolation_type (wmOperatorType * ot)
Definition at line 1099 of file action_edit.c.
References actkeys_ipo_exec(), beztriple_interpolation_mode_items, wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by action_operatortypes().
void ACTION_OT_keyframe_insert (wmOperatorType * ot)
Definition at line 639 of file action_edit.c.
References actkeys_insertkey_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by action_operatortypes().
void ACTION_OT_keyframe_type (wmOperatorType * ot)
Definition at line 1250 of file action_edit.c.
References actkeys_keytype_exec(), beztriple_keyframe_type_items, wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by action_operatortypes().
void ACTION_OT_markers_make_local (wmOperatorType * ot)
Definition at line 207 of file action_edit.c.
References act_markers_make_local_exec(), act_markers_make_local_poll(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_mirror (wmOperatorType * ot)
Definition at line 1532 of file action_edit.c.
References actkeys_mirror_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by action_operatortypes().
void ACTION_OT_new (wmOperatorType * ot)
Definition at line 124 of file action_edit.c.
References act_new_exec(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by action_operatortypes().
void ACTION_OT_paste (wmOperatorType * ot)
Definition at line 538 of file action_edit.c.
References actkeys_paste_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, keyframe_paste_merge_items, KEYFRAME_PASTE_MERGE_MIX, KEYFRAME_PASTE_OFFSET_CFRA_START, keyframe_paste_offset_items, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by action_operatortypes().
void ACTION_OT_previewrange_set (wmOperatorType * ot)
Definition at line 322 of file action_edit.c.
References actkeys_previewrange_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_sample (wmOperatorType * ot)
Definition at line 918 of file action_edit.c.
References actkeys_sample_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_snap (wmOperatorType * ot)
Definition at line 1418 of file action_edit.c.
References actkeys_snap_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by action_operatortypes().
void ACTION_OT_view_all (wmOperatorType * ot)
Definition at line 384 of file action_edit.c.
References actkeys_viewall_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_view_selected (wmOperatorType * ot)
Definition at line 399 of file action_edit.c.
References actkeys_viewsel_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
static int actkeys_clean_exec (bContext * C, wmOperator * op) [static]
Definition at line 828 of file action_edit.c.
References ANIM_animdata_get_context(), ANIM_editkeyframes_refresh(), ANIMCONT_GPENCIL, clean_action_keys(), bAnimContext::datatype, NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_float_get(), thresh, and WM_event_add_notifier().
Referenced by ACTION_OT_clean().
static int actkeys_copy_exec (bContext * C, wmOperator * op) [static]
Definition at line 463 of file action_edit.c.
References ANIM_animdata_get_context(), ANIMCONT_GPENCIL, BKE_report(), copy_action_keys(), bAnimContext::datatype, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, and RPT_ERROR.
Referenced by ACTION_OT_copy().
static int actkeys_delete_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 769 of file action_edit.c.
References ANIM_animdata_get_context(), ANIM_editkeyframes_refresh(), ANIMCONT_GPENCIL, bAnimContext::datatype, delete_action_keys(), NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by ACTION_OT_delete().
static int actkeys_duplicate_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 687 of file action_edit.c.
References ANIM_animdata_get_context(), ANIM_editkeyframes_refresh(), ANIMCONT_GPENCIL, bAnimContext::datatype, duplicate_action_keys(), NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by ACTION_OT_duplicate(), and actkeys_duplicate_invoke().
static int actkeys_duplicate_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 708 of file action_edit.c.
References actkeys_duplicate_exec(), and OPERATOR_FINISHED.
Referenced by ACTION_OT_duplicate().
static int actkeys_expo_exec (bContext * C, wmOperator * op) [static]
Definition at line 1002 of file action_edit.c.
References ANIM_animdata_get_context(), ANIM_editkeyframes_refresh(), ANIMCONT_GPENCIL, bAnimContext::datatype, NC_ANIMATION, ND_KEYFRAME_PROP, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_enum_get(), setexpo_action_keys(), and WM_event_add_notifier().
Referenced by ACTION_OT_extrapolation_type().
static int actkeys_framejump_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1275 of file action_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIM_fcurve_keyframes_loop(), ANIM_nla_mapping_apply_fcurve(), ANIM_nla_mapping_get(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, bezt_calc_average(), BLI_freelistN(), CFRA, bAnimContext::data, bAnimContext::datatype, KeyframeEditData::f1, filter(), ListBase::first, KeyframeEditData::i1, bAnimListElem::key_data, NC_SCENE, ND_FRAME, bAnimListElem::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, bAnimContext::scene, SUBFRA, and WM_event_add_notifier().
Referenced by ACTION_OT_frame_jump().
static int actkeys_handletype_exec (bContext * C, wmOperator * op) [static]
Definition at line 1153 of file action_edit.c.
References ANIM_animdata_get_context(), ANIM_editkeyframes_refresh(), ANIMCONT_GPENCIL, bAnimContext::datatype, NC_ANIMATION, ND_KEYFRAME_PROP, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_enum_get(), sethandles_action_keys(), and WM_event_add_notifier().
Referenced by ACTION_OT_handle_type().
static int actkeys_insertkey_exec (bContext * C, wmOperator * op) [static]
Definition at line 613 of file action_edit.c.
References ANIM_animdata_get_context(), ANIM_editkeyframes_refresh(), ANIMCONT_GPENCIL, bAnimContext::datatype, insert_action_keys(), NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), and WM_event_add_notifier().
Referenced by ACTION_OT_keyframe_insert().
static int actkeys_ipo_exec (bContext * C, wmOperator * op) [static]
Definition at line 1073 of file action_edit.c.
References ANIM_animdata_get_context(), ANIM_editkeyframes_refresh(), ANIMCONT_GPENCIL, bAnimContext::datatype, NC_ANIMATION, ND_KEYFRAME_PROP, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_enum_get(), setipo_action_keys(), and WM_event_add_notifier().
Referenced by ACTION_OT_interpolation_type().
static int actkeys_keytype_exec (bContext * C, wmOperator * op) [static]
Definition at line 1224 of file action_edit.c.
References ANIM_animdata_get_context(), ANIM_editkeyframes_refresh(), ANIMCONT_GPENCIL, bAnimContext::datatype, NC_ANIMATION, ND_KEYFRAME_PROP, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_enum_get(), setkeytype_action_keys(), and WM_event_add_notifier().
Referenced by ACTION_OT_keyframe_type().
static int actkeys_mirror_exec (bContext * C, wmOperator * op) [static]
Definition at line 1504 of file action_edit.c.
References ANIM_animdata_get_context(), ANIM_editkeyframes_refresh(), ANIMCONT_GPENCIL, bAnimContext::datatype, mirror_action_keys(), NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_enum_get(), and WM_event_add_notifier().
Referenced by ACTION_OT_mirror().
static int actkeys_paste_exec (bContext * C, wmOperator * op) [static]
Definition at line 502 of file action_edit.c.
References ANIM_animdata_get_context(), ANIM_editkeyframes_refresh(), ANIMCONT_GPENCIL, BKE_report(), bAnimContext::datatype, NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, paste_action_keys(), wmOperator::ptr, wmOperator::reports, bAnimContext::reports, RNA_enum_get(), RPT_ERROR, and WM_event_add_notifier().
Referenced by ACTION_OT_paste().
static int actkeys_previewrange_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 295 of file action_edit.c.
References ANIM_animdata_get_context(), FALSE, RenderData::flag, get_keyframe_extents(), max, min, NC_SCENE, ND_FRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, RenderData::pefra, RenderData::psfra, Scene::r, bAnimContext::scene, SCER_PRV_RANGE, and WM_event_add_notifier().
Referenced by ACTION_OT_previewrange_set().
static int actkeys_sample_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 896 of file action_edit.c.
References ANIM_animdata_get_context(), ANIM_editkeyframes_refresh(), ANIMCONT_GPENCIL, bAnimContext::datatype, NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, sample_action_keys(), and WM_event_add_notifier().
Referenced by ACTION_OT_sample().
static int actkeys_snap_exec (bContext * C, wmOperator * op) [static]
Definition at line 1390 of file action_edit.c.
References ANIM_animdata_get_context(), ANIM_editkeyframes_refresh(), ANIMCONT_GPENCIL, bAnimContext::datatype, NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_enum_get(), snap_action_keys(), and WM_event_add_notifier().
Referenced by ACTION_OT_snap().
static int actkeys_viewall (bContext * C, const short onlySel) [static]
Definition at line 339 of file action_edit.c.
References ANIM_animdata_get_context(), bAnimContext::ar, CTX_wm_area(), CTX_wm_screen(), View2D::cur, ED_area_tag_redraw(), get_keyframe_extents(), View2D::mask, OPERATOR_CANCELLED, OPERATOR_FINISHED, UI_view2d_sync(), ARegion::v2d, V2D_LOCK_COPY, rctf::xmax, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by actkeys_viewall_exec(), and actkeys_viewsel_exec().
static int actkeys_viewall_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 372 of file action_edit.c.
References actkeys_viewall(), and FALSE.
Referenced by ACTION_OT_view_all().
static int actkeys_viewsel_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 378 of file action_edit.c.
References actkeys_viewall(), and TRUE.
Referenced by ACTION_OT_view_selected().
static void clean_action_keys (bAnimContext * ac, float thresh) [static]
Definition at line 808 of file action_edit.c.
References ANIM_animdata_filter(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, ANIMFILTER_SEL, BLI_freelistN(), clean_fcurve(), bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, bAnimListElem::key_data, bAnimListElem::next, and NULL.
Referenced by actkeys_clean_exec().
static short copy_action_keys (bAnimContext * ac) [static]
Definition at line 420 of file action_edit.c.
References ANIM_animdata_filter(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, BLI_freelistN(), copy_animedit_keys(), bAnimContext::data, bAnimContext::datatype, filter(), free_anim_copybuf(), and NULL.
Referenced by actkeys_copy_exec().
static void delete_action_keys (bAnimContext * ac) [static]
Definition at line 733 of file action_edit.c.
References bAnimListElem::adt, ANIM_animdata_filter(), ANIM_fcurve_delete_from_animdata(), ANIMCONT_GPENCIL, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, ANIMTYPE_GPLAYER, BLI_freelistN(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, delete_fcurve_keys(), delete_gplayer_frames(), filter(), ListBase::first, FMI_TYPE_GENERATE_CURVE, bAnimListElem::key_data, list_has_suitable_fmodifier(), FCurve::modifiers, bAnimListElem::next, NULL, FCurve::totvert, and bAnimListElem::type.
Referenced by actkeys_delete_exec().
static void duplicate_action_keys (bAnimContext * ac) [static]
Definition at line 660 of file action_edit.c.
References ANIM_animdata_filter(), ANIMCONT_GPENCIL, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, ANIMTYPE_FCURVE, BLI_freelistN(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, duplicate_fcurve_keys(), duplicate_gplayer_frames(), filter(), ListBase::first, bAnimListElem::key_data, bAnimListElem::next, NULL, and bAnimListElem::type.
Referenced by actkeys_duplicate_exec().
static void get_keyframe_extents (bAnimContext * ac, float * min, float * max, const short onlySel) [static]
Definition at line 228 of file action_edit.c.
References ALE_GPFRAME, ANIM_animdata_filter(), ANIM_nla_mapping_get(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, BKE_nla_tweakedit_remap(), BLI_freelistN(), calc_fcurve_range(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, bAnimListElem::datatype, RenderData::efra, filter(), ListBase::first, bGPDframe::framenum, bGPDlayer::frames, bAnimListElem::key_data, MAX2, MIN2, bAnimListElem::next, bGPDframe::next, NLATIME_CONVERT_MAP, NULL, Scene::r, bAnimContext::scene, RenderData::sfra, and TRUE.
Referenced by actkeys_previewrange_exec(), and actkeys_viewall().
static void insert_action_keys (bAnimContext * ac, short mode) [static]
Definition at line 569 of file action_edit.c.
References ANIM_animdata_filter(), ANIM_get_keyframing_flags(), ANIM_nla_mapping_get(), ANIMFILTER_ACTGROUPED, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, ANIMFILTER_SEL, FCurve::array_index, BKE_nla_tweakedit_remap(), BLI_freelistN(), CFRA, FCurve::curval, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, FCurve::grp, bAnimListElem::id, if(), insert_keyframe(), insert_vert_fcurve(), bAnimListElem::key_data, bActionGroup::name, bAnimListElem::next, NLATIME_CONVERT_UNMAP, NULL, bAnimContext::reports, FCurve::rna_path, and bAnimContext::scene.
Referenced by actkeys_insertkey_exec().
static void mirror_action_keys (bAnimContext * ac, short mode) [static]
Definition at line 1448 of file action_edit.c.
References ACTKEYS_MIRROR_MARKER, ANIM_animdata_filter(), ANIM_editkeyframes_mirror(), ANIM_fcurve_keyframes_loop(), ANIM_nla_mapping_apply_fcurve(), ANIM_nla_mapping_get(), ANIMCONT_GPENCIL, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, BLI_freelistN(), calchandles_fcurve(), bAnimContext::data, bAnimContext::datatype, ED_markers_get_first_selected(), KeyframeEditData::f1, filter(), ListBase::first, TimeMarker::frame, bAnimListElem::key_data, bAnimContext::markers, bAnimListElem::next, NULL, KeyframeEditData::scene, and bAnimContext::scene.
Referenced by actkeys_mirror_exec().
static short paste_action_keys (bAnimContext * ac, const eKeyPasteOffset offset_mode, const eKeyMergeMode merge_mode) [static]
Definition at line 442 of file action_edit.c.
References ANIM_animdata_filter(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, ANIMFILTER_SEL, BLI_freelistN(), bAnimContext::data, bAnimContext::datatype, filter(), NULL, and paste_animedit_keys().
Referenced by actkeys_paste_exec().
static void sample_action_keys (bAnimContext * ac) [static]
Definition at line 876 of file action_edit.c.
References ANIM_animdata_filter(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, BLI_freelistN(), bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, bAnimListElem::key_data, bAnimListElem::next, NULL, and sample_fcurve().
Referenced by actkeys_sample_exec().
static void setexpo_action_keys (bAnimContext * ac, short mode) [static]
Definition at line 953 of file action_edit.c.
References add_fmodifier(), ANIM_animdata_filter(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, ANIMFILTER_SEL, BLI_freelistN(), CLEAR_CYCLIC_EXPO, bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, FCurve::extend, filter(), ListBase::first, FMODIFIER_TYPE_CYCLES, if(), list_has_suitable_fmodifier(), MAKE_CYCLIC_EXPO, FCurve::modifiers, bAnimListElem::next, FModifier::next, NULL, remove_fmodifier(), and FModifier::type.
Referenced by actkeys_expo_exec().
static void sethandles_action_keys (bAnimContext * ac, short mode) [static]
Definition at line 1121 of file action_edit.c.
References ANIM_animdata_filter(), ANIM_editkeyframes_handles(), ANIM_editkeyframes_ok(), ANIM_fcurve_keyframes_loop(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, BEZT_OK_SELECTED, BLI_freelistN(), calchandles_fcurve(), bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, if(), bAnimListElem::key_data, bAnimListElem::next, and NULL.
Referenced by actkeys_handletype_exec().
static void setipo_action_keys (bAnimContext * ac, short mode) [static]
Definition at line 1050 of file action_edit.c.
References ANIM_animdata_filter(), ANIM_editkeyframes_ipo(), ANIM_fcurve_keyframes_loop(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, BLI_freelistN(), calchandles_fcurve(), bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, bAnimListElem::key_data, bAnimListElem::next, and NULL.
Referenced by actkeys_ipo_exec().
static void setkeytype_action_keys (bAnimContext * ac, short mode) [static]
Definition at line 1201 of file action_edit.c.
References ANIM_animdata_filter(), ANIM_editkeyframes_keytype(), ANIM_fcurve_keyframes_loop(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, BLI_freelistN(), bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, bAnimListElem::key_data, bAnimListElem::next, and NULL.
Referenced by actkeys_keytype_exec().
static void snap_action_keys (bAnimContext * ac, short mode) [static]
Definition at line 1345 of file action_edit.c.
References ACTKEYS_SNAP_NEAREST_MARKER, ANIM_animdata_filter(), ANIM_editkeyframes_snap(), ANIM_fcurve_keyframes_loop(), ANIM_nla_mapping_apply_fcurve(), ANIM_nla_mapping_get(), ANIMCONT_GPENCIL, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, BLI_freelistN(), calchandles_fcurve(), bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, bAnimListElem::key_data, ListBase::last, KeyframeEditData::list, bAnimContext::markers, bAnimListElem::next, NULL, KeyframeEditData::scene, and bAnimContext::scene.
Referenced by actkeys_snap_exec().
Variable Documentation
EnumPropertyItem prop_actkeys_expo_types[] [static]
Initial value:
 {
    {FCURVE_EXTRAPOLATE_CONSTANT, "CONSTANT", 0, "Constant Extrapolation", ""},
    {FCURVE_EXTRAPOLATE_LINEAR, "LINEAR", 0, "Linear Extrapolation", ""},
    {MAKE_CYCLIC_EXPO, "MAKE_CYCLIC", 0, "Make Cyclic (F-Modifier)", "Add Cycles F-Modifier if one doesn't exist already"},
    {CLEAR_CYCLIC_EXPO, "CLEAR_CYCLIC", 0, "Clear Cyclic (F-Modifier)", "Remove Cycles F-Modifier if not needed anymore"},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 943 of file action_edit.c.
EnumPropertyItem prop_actkeys_insertkey_types[] [static]
Initial value:
 {
    {1, "ALL", 0, "All Channels", ""},
    {2, "SEL", 0, "Only Selected Channels", ""},
    {3, "GROUP", 0, "In Active Group", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 561 of file action_edit.c.
EnumPropertyItem prop_actkeys_mirror_types[] [static]
Initial value:
 {
    {ACTKEYS_MIRROR_CFRA, "CFRA", 0, "By Times over Current frame", ""},
    {ACTKEYS_MIRROR_XAXIS, "XAXIS", 0, "By Values over Value=0", ""},
    {ACTKEYS_MIRROR_MARKER, "MARKER", 0, "By Times over First Selected Marker", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 1440 of file action_edit.c.
EnumPropertyItem prop_actkeys_snap_types[] [static]
Initial value:
 {
    {ACTKEYS_SNAP_CFRA, "CFRA", 0, "Current frame", ""},
    {ACTKEYS_SNAP_NEAREST_FRAME, "NEAREST_FRAME", 0, "Nearest Frame", ""},
    {ACTKEYS_SNAP_NEAREST_SECOND, "NEAREST_SECOND", 0, "Nearest Second", ""},
    {ACTKEYS_SNAP_NEAREST_MARKER, "NEAREST_MARKER", 0, "Nearest Marker", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 1336 of file action_edit.c.