Blender: BL_Uniform Class Reference
BL_Uniform Class Reference
#include <BL_Shader.h>
Public Types
enum UniformTypes {
UNI_NONE = 0, UNI_INT, UNI_FLOAT, UNI_INT2,
UNI_FLOAT2, UNI_INT3, UNI_FLOAT3, UNI_INT4,
UNI_FLOAT4, UNI_MAT3, UNI_MAT4, UNI_MAX
}
Public Member Functions
BL_Uniform (int data_size)
~BL_Uniform ()
void Apply (class BL_Shader *shader)
void SetData (int location, int type, bool transpose=false)
int GetLocation ()
void * getData ()
Detailed Description
BL_Uniform uniform storage
Definition at line 45 of file BL_Shader.h.
Member Enumeration Documentation
enum BL_Uniform::UniformTypes
Enumerator:
UNI_NONE
UNI_INT
UNI_FLOAT
UNI_INT2
UNI_FLOAT2
UNI_INT3
UNI_FLOAT3
UNI_INT4
UNI_FLOAT4
UNI_MAT3
UNI_MAT4
UNI_MAX
Definition at line 62 of file BL_Shader.h.
Constructor & Destructor Documentation
BL_Uniform::BL_Uniform (int data_size)
Definition at line 27 of file BL_Shader.cpp.
References MEM_mallocN(), MT_assert, and UNIFORM_MAX_LEN.
BL_Uniform::~BL_Uniform ()
Definition at line 40 of file BL_Shader.cpp.
References MEM_freeN().
Member Function Documentation
void BL_Uniform::Apply (class BL_Shader * shader)
Definition at line 50 of file BL_Shader.cpp.
References MT_assert, UNI_FLOAT, UNI_FLOAT2, UNI_FLOAT3, UNI_FLOAT4, UNI_INT, UNI_INT2, UNI_INT3, UNI_INT4, UNI_MAT3, UNI_MAT4, UNI_MAX, and UNI_NONE.
void* BL_Uniform::getData () [inline]
Definition at line 78 of file BL_Shader.h.
Referenced by BL_Shader::SetUniformfv(), and BL_Shader::SetUniformiv().
int BL_Uniform::GetLocation () [inline]
Definition at line 77 of file BL_Shader.h.
void BL_Uniform::SetData (int location, int type, bool transpose = false)
Definition at line 105 of file BL_Shader.cpp.
References DerivedMesh::type.
Referenced by BL_Shader::SetUniformfv(), and BL_Shader::SetUniformiv().
The documentation for this class was generated from the following files:
BL_Shader.h
BL_Shader.cpp