Blender: BKE_animsys.h File Reference
BKE_animsys.h File Reference
blenkernel
Typedefs
typedef void(* ID_AnimData_Edit_Callback)(struct ID *id, struct AnimData *adt, void *user_data)
Functions
short id_type_can_have_animdata (struct ID *id)
struct AnimData * BKE_animdata_from_id (struct ID *id)
struct AnimData * BKE_id_add_animdata (struct ID *id)
short BKE_animdata_set_action (struct ReportList *reports, struct ID *id, struct bAction *act)
void BKE_free_animdata (struct ID *id)
struct AnimData * BKE_copy_animdata (struct AnimData *adt, const short do_action)
int BKE_copy_animdata_id (struct ID *id_to, struct ID *id_from, const short do_action)
void BKE_copy_animdata_id_action (struct ID *id)
void BKE_animdata_make_local (struct AnimData *adt)
void BKE_relink_animdata (struct AnimData *adt)
struct KeyingSet * BKE_keyingset_add (struct ListBase *list, const char idname[], const char name[], short flag, short keyingflag)
struct KS_Path * BKE_keyingset_add_path (struct KeyingSet *ks, struct ID *id, const char group_name[], const char rna_path[], int array_index, short flag, short groupmode)
struct KS_Path * BKE_keyingset_find_path (struct KeyingSet *ks, struct ID *id, const char group_name[], const char rna_path[], int array_index, int group_mode)
void BKE_keyingsets_copy (struct ListBase *newlist, struct ListBase *list)
void BKE_keyingset_free_path (struct KeyingSet *ks, struct KS_Path *ksp)
void BKE_keyingset_free (struct KeyingSet *ks)
void BKE_keyingsets_free (struct ListBase *list)
void BKE_animdata_fix_paths_rename (struct ID *owner_id, struct AnimData *adt, struct ID *ref_id, const char *prefix, const char *oldName, const char *newName, int oldSubscript, int newSubscript, int verify_paths)
void BKE_all_animdata_fix_paths_rename (ID *ref_id, const char *prefix, const char *oldName, const char *newName)
void BKE_animdata_separate_by_basepath (struct ID *srcID, struct ID *dstID, struct ListBase *basepaths)
void action_move_fcurves_by_basepath (struct bAction *srcAct, struct bAction *dstAct, const char basepath[])
void BKE_animdata_main_cb (struct Main *main, ID_AnimData_Edit_Callback func, void *user_data)
void BKE_animsys_evaluate_animdata (struct Scene *scene, struct ID *id, struct AnimData *adt, float ctime, short recalc)
void BKE_animsys_evaluate_all_animation (struct Main *main, struct Scene *scene, float ctime)
void animsys_evaluate_action (struct PointerRNA *ptr, struct bAction *act, struct AnimMapper *remap, float ctime)
void animsys_evaluate_action_group (struct PointerRNA *ptr, struct bAction *act, struct bActionGroup *agrp, struct AnimMapper *remap, float ctime)
Detailed Description
Author:
Joshua Leung
Definition in file BKE_animsys.h.
Typedef Documentation
typedef void(* ID_AnimData_Edit_Callback)(struct ID *id, struct AnimData *adt, void *user_data)
Definition at line 127 of file BKE_animsys.h.
Function Documentation
void action_move_fcurves_by_basepath (struct bAction * srcAct, struct bAction * dstAct, const char basepath[])
Definition at line 396 of file anim_sys.c.
References action_groups_add_channel(), action_groups_add_new(), action_groups_clear_tempflags(), action_groups_find_named(), action_groups_remove_channel(), AGRP_TEMP, animpath_matches_basepath(), BLI_addtail(), BLI_freelinkN(), bActionGroup::channels, bAction::curves, ELEM3, ListBase::first, bActionGroup::flag, G, G_DEBUG, bAction::groups, FCurve::grp, bActionGroup::name, FCurve::next, bActionGroup::next, NULL, and FCurve::rna_path.
Referenced by BKE_animdata_separate_by_basepath().
void animsys_evaluate_action (struct PointerRNA * ptr, struct bAction * act, struct AnimMapper * remap, float ctime)
Definition at line 1365 of file anim_sys.c.
References action_idcode_patch_check(), animsys_evaluate_fcurves(), bAction::curves, PointerRNA::data, PointerRNA::id, NULL, and AnimMapper::target.
Referenced by animsys_evaluate_nla(), BKE_animsys_evaluate_animdata(), BL_Action::Update(), and BL_ShapeActionActuator::Update().
void animsys_evaluate_action_group (struct PointerRNA * ptr, struct bAction * act, struct bActionGroup * agrp, struct AnimMapper * remap, float ctime)
Definition at line 1339 of file anim_sys.c.
References action_idcode_patch_check(), AGRP_MUTED, animsys_execute_fcurve(), calculate_fcurve(), bActionGroup::channels, PointerRNA::data, ELEM, FCURVE_DISABLED, FCURVE_MUTED, ListBase::first, FCurve::flag, bActionGroup::flag, FCurve::grp, PointerRNA::id, FCurve::next, NULL, and AnimMapper::target.
Referenced by poselib_apply_pose(), and what_does_obaction().
void BKE_all_animdata_fix_paths_rename (ID * ref_id, const char * prefix, const char * oldName, const char * newName)
Definition at line 818 of file anim_sys.c.
References Main::armature, Main::camera, Main::curve, ListBase::first, G, Main::key, Main::lamp, Main::latt, Main::mat, Main::mball, Main::mesh, Main::movieclip, Main::nodetree, Main::object, Main::particle, RENAMEFIX_ANIM_IDS, RENAMEFIX_ANIM_NODETREE_IDS, Main::scene, Main::speaker, Main::tex, and Main::world.
Referenced by ED_armature_bone_rename().
void BKE_animdata_fix_paths_rename (struct ID * owner_id, struct AnimData * adt, struct ID * ref_id, const char * prefix, const char * oldName, const char * newName, int oldSubscript, int newSubscript, int verify_paths)
Definition at line 697 of file anim_sys.c.
References AnimData::action, BLI_sprintfN(), bAction::curves, AnimData::drivers, drivers_path_rename_fix(), ELEM, fcurves_path_rename_fix(), ListBase::first, MEM_freeN(), NlaTrack::next, AnimData::nla_tracks, nlastrips_path_rename_fix(), NULL, NlaTrack::strips, and AnimData::tmpact.
Referenced by seq_dupe_animdata(), and texture_slot_move().
struct AnimData* BKE_animdata_from_id (struct ID * id) [read]
Definition at line 108 of file anim_sys.c.
References IdAdtTemplate::adt, id_type_can_have_animdata(), and NULL.
Referenced by action_to_animdata(), ANIM_id_update(), ANIM_list_elem_update(), ANIM_remove_driver(), animfilter_block_data(), animrecord_check_state(), BKE_animdata_separate_by_basepath(), BKE_animdata_set_action(), BKE_copy_animdata_id(), BKE_copy_animdata_id_action(), build_dag_object(), ConvertMaterial(), curve_is_animated(), curve_rename_fcurves(), dag_object_time_update_flags(), delete_keyframe(), do_versions_ipos_to_animato(), draw_ghost_poses(), draw_ghost_poses_keys(), draw_ghost_poses_range(), draw_motion_path_instance(), ED_curve_updateAnimPaths(), editCurve_to_undoCurve(), id_copy_animdata(), id_data_find_fcurve(), id_frame_has_keyframe(), insert_keyframe(), ipo_to_animdata(), make_local_exec(), make_local_makelocalmaterial(), make_new_animlistelem(), mouse_nla_channels(), nlastrips_to_animdata(), ntreeLocalize(), object_handle_update(), pyrna_struct_driver_add(), rna_get_fcurve(), scene_update_drivers(), scene_update_tagged(), seq_render_strip_stack(), texture_slot_move(), undoCurve_to_editCurve(), verify_adt_action(), and verify_driver_fcurve().
void BKE_animdata_main_cb (struct Main * main, ID_AnimData_Edit_Callback func, void * user_data)
Definition at line 738 of file anim_sys.c.
References ANIMDATA_IDS_CB, ANIMDATA_NODETREE_IDS_CB, Main::armature, Main::camera, Main::curve, ListBase::first, Main::key, Main::lamp, Main::latt, Main::mat, Main::mball, Main::mesh, Main::movieclip, Main::nodetree, Main::object, Main::particle, Main::scene, Main::speaker, Main::tex, and Main::world.
Referenced by free_libblock(), and make_local_action().
void BKE_animdata_make_local (struct AnimData * adt)
Definition at line 325 of file anim_sys.c.
References AnimData::action, ListBase::first, make_local_action(), make_local_strips(), NlaTrack::next, AnimData::nla_tracks, AnimData::remap, NlaTrack::strips, AnimMapper::target, and AnimData::tmpact.
Referenced by make_local_exec(), and make_local_makelocalmaterial().
void BKE_animdata_separate_by_basepath (struct ID * srcID, struct ID * dstID, struct ListBase * basepaths)
Definition at line 476 of file anim_sys.c.
References AnimData::action, action_move_fcurves_by_basepath(), add_empty_action(), animpath_matches_basepath(), BKE_animdata_from_id(), BKE_id_add_animdata(), BLI_addtail(), BLI_remlink(), LinkData::data, AnimData::drivers, ELEM, ListBase::first, G, G_DEBUG, bAction::id, id_us_min(), if(), ID::name, FCurve::next, LinkData::next, NULL, and FCurve::rna_path.
Referenced by node_group_make_from_selected(), and node_group_ungroup().
short BKE_animdata_set_action (struct ReportList * reports, struct ID * id, struct bAction * act)
Definition at line 155 of file anim_sys.c.
References AnimData::action, AnimData::actstrip, ADT_NLA_EDIT_ON, BKE_animdata_from_id(), BKE_report(), BKE_reportf(), ELEM, AnimData::flag, GS, bAction::id, id_us_min(), id_us_plus(), bAction::idroot, ID::name, NULL, RPT_ERROR, RPT_WARNING, and AnimData::tmpact.
Referenced by actionset_id_cb(), unlink_action_cb(), and unlinkact_animdata_cb().
void BKE_animsys_evaluate_all_animation (struct Main * main, struct Scene * scene, float ctime)
Definition at line 2251 of file anim_sys.c.
References Main::action, ADT_RECALC_ANIM, Main::armature, Main::camera, Main::curve, EVAL_ANIM_IDS, EVAL_ANIM_NODETREE_IDS, ListBase::first, G, G_DEBUG, Main::key, Main::lamp, Main::latt, Main::mat, Main::mball, Main::mesh, Main::movieclip, Main::nodetree, NULL, Main::object, Main::particle, Main::scene, Main::speaker, Main::tex, and Main::world.
Referenced by do_render_seq(), scene_update_for_newframe(), and seq_render_strip().
void BKE_animsys_evaluate_animdata (struct Scene * scene, struct ID * id, struct AnimData * adt, float ctime, short recalc)
Definition at line 2183 of file anim_sys.c.
References AnimData::action, ADT_NLA_EVAL_OFF, ADT_RECALC_ANIM, ADT_RECALC_DRIVERS, animsys_calculate_nla(), animsys_evaluate_action(), animsys_evaluate_drivers(), animsys_evaluate_overrides(), ELEM, ListBase::first, AnimData::flag, G, AnimData::nla_tracks, NULL, AnimData::recalc, AnimData::remap, RNA_id_pointer_create(), RNA_property_update_cache_flush(), and RNA_property_update_cache_free().
Referenced by AnimationExporter::create_4x4_source(), do_ob_key(), draw_ghost_poses(), draw_ghost_poses_keys(), draw_ghost_poses_range(), dynamicPaint_doStep(), BL_ShapeDeformer::ExecuteShapeDrivers(), frames_duplilist(), object_handle_update(), ocean_bake_exec(), particle_system_update(), pose_clear_user_transforms_exec(), RE_init_sample_material(), reset_particle(), AnimationExporter::sample_animation(), scene_update_drivers(), scene_update_tagged(), seq_render_strip_stack(), subframe_updateObject(), what_does_obaction(), and where_is_object_time().
struct AnimData* BKE_copy_animdata (struct AnimData * adt, const short do_action) [read]
Definition at line 245 of file anim_sys.c.
References AnimData::action, copy_action(), copy_fcurves(), copy_nladata(), AnimData::drivers, ListBase::first, id_us_plus(), ListBase::last, MEM_dupallocN(), AnimData::nla_tracks, NULL, AnimData::overrides, and AnimData::tmpact.
Referenced by BKE_copy_animdata_id(), and id_copy_animdata().
int BKE_copy_animdata_id (struct ID * id_to, struct ID * id_from, const short do_action)
Definition at line 277 of file anim_sys.c.
References IdAdtTemplate::adt, BKE_animdata_from_id(), BKE_copy_animdata(), BKE_free_animdata(), GS, and ID::name.
Referenced by make_links_data_exec().
void BKE_copy_animdata_id_action (struct ID * id)
Definition at line 295 of file anim_sys.c.
References AnimData::action, BKE_animdata_from_id(), copy_action(), id_us_min(), and AnimData::tmpact.
Referenced by copy_scene(), do_single_tex_user(), id_single_user(), object_add_duplicate_internal(), single_mat_users(), single_obdata_users(), and single_object_action_users().
void BKE_free_animdata (struct ID * id)
Definition at line 208 of file anim_sys.c.
References AnimData::action, IdAdtTemplate::adt, AnimData::drivers, free_fcurves(), free_nladata(), bAction::id, id_type_can_have_animdata(), MEM_freeN(), AnimData::nla_tracks, NULL, AnimData::tmpact, and ID::us.
Referenced by BKE_copy_animdata_id(), free_armature(), free_buffers(), free_camera(), free_curve(), free_key(), free_lamp(), free_lattice(), free_material(), free_mball(), free_mesh(), free_object(), free_scene(), free_speaker(), free_texture(), free_world(), make_object_duplilist_real(), ntreeFreeTree(), and psys_free_settings().
struct AnimData* BKE_id_add_animdata (struct ID * id) [read]
Definition at line 126 of file anim_sys.c.
References AnimData::act_influence, IdAdtTemplate::adt, id_type_can_have_animdata(), MEM_callocN(), and NULL.
Referenced by BKE_animdata_separate_by_basepath(), do_versions_ipos_to_animato(), object_copy_proxy_drivers(), object_speaker_add_exec(), verify_adt_action(), verify_driver_fcurve(), and KX_BlenderSceneConverter::WritePhysicsObjectToAnimationIpo().
struct KeyingSet* BKE_keyingset_add (struct ListBase * list, const char idname[], const char name[], short flag, short keyingflag) [read]
Definition at line 947 of file anim_sys.c.
References BLI_addtail(), BLI_strncpy(), BLI_uniquename(), KeyingSet::flag, KeyingSet::idname, KeyingSet::keyingflag, MEM_callocN(), and KeyingSet::name.
Referenced by add_default_keyingset_exec(), add_keyingset_button_exec(), ANIM_keyingset_info_register(), and verify_active_keyingset().
struct KS_Path* BKE_keyingset_add_path (struct KeyingSet * ks, struct ID * id, const char group_name[], const char rna_path[], int array_index, short flag, short groupmode) [read]
Definition at line 977 of file anim_sys.c.
References KS_Path::array_index, BKE_keyingset_find_path(), BLI_addtail(), BLI_strdupn(), BLI_strncpy(), ELEM, KS_Path::flag, G, G_DEBUG, KS_Path::group, KS_Path::groupmode, GS, KS_Path::id, KS_Path::idtype, MEM_callocN(), ID::name, NULL, KeyingSet::paths, KS_Path::rna_path, and strlen().
Referenced by add_keyingset_button_exec(), and do_outliner_keyingset_editop().
struct KS_Path* BKE_keyingset_find_path (struct KeyingSet * ks, struct ID * id, const char group_name[], const char rna_path[], int array_index, int group_mode) [read]
Referenced by BKE_keyingset_add_path(), do_outliner_keyingset_editop(), and remove_keyingset_button_exec().
void BKE_keyingset_free (struct KeyingSet * ks)
Definition at line 1064 of file anim_sys.c.
References BKE_keyingset_free_path(), ListBase::first, KS_Path::next, NULL, and KeyingSet::paths.
Referenced by ANIM_keyingset_info_unregister(), ANIM_validate_keyingset(), BKE_keyingsets_free(), and remove_active_keyingset_exec().
void BKE_keyingset_free_path (struct KeyingSet * ks, struct KS_Path * ksp)
Definition at line 1031 of file anim_sys.c.
References BLI_freelinkN(), ELEM, MEM_freeN(), NULL, KeyingSet::paths, and KS_Path::rna_path.
Referenced by BKE_keyingset_free(), do_outliner_keyingset_editop(), remove_active_ks_path_exec(), and remove_keyingset_button_exec().
void BKE_keyingsets_copy (struct ListBase * newlist, struct ListBase * list)
Definition at line 1046 of file anim_sys.c.
References BLI_duplicatelist(), ListBase::first, MEM_dupallocN(), KeyingSet::next, KS_Path::next, KeyingSet::paths, and KS_Path::rna_path.
Referenced by copy_scene().
void BKE_keyingsets_free (struct ListBase * list)
Definition at line 1080 of file anim_sys.c.
References BKE_keyingset_free(), BLI_freelinkN(), ListBase::first, KeyingSet::next, and NULL.
Referenced by ANIM_keyingset_infos_exit(), and free_scene().
void BKE_relink_animdata (struct AnimData * adt)
Definition at line 347 of file anim_sys.c.
References FCurve::driver, DRIVER_TARGETS_LOOPER_END, DRIVER_TARGETS_USED_LOOPER, AnimData::drivers, ListBase::first, FCurve::next, DriverVar::next, NULL, and ChannelDriver::variables.
Referenced by object_relink().
short id_type_can_have_animdata (struct ID * id)
Definition at line 74 of file anim_sys.c.
References GS, ID_AR, ID_CA, ID_CU, ID_KE, ID_LA, ID_LT, ID_MA, ID_MB, ID_MC, ID_ME, ID_NT, ID_OB, ID_PA, ID_SCE, ID_SPK, ID_TE, ID_WO, ID::name, and NULL.
Referenced by BKE_animdata_from_id(), BKE_free_animdata(), BKE_id_add_animdata(), and RNA_property_animateable().