Blender: BPY_extern.h File Reference
BPY_extern.h File Reference
Python
Functions
void BPY_pyconstraint_exec (struct bPythonConstraint *con, struct bConstraintOb *cob, struct ListBase *targets)
void BPY_pyconstraint_target (struct bPythonConstraint *con, struct bConstraintTarget *ct)
void BPY_pyconstraint_update (struct Object *owner, struct bConstraint *con)
int BPY_is_pyconstraint (struct Text *text)
void BPY_python_start (int argc, const char **argv)
void BPY_python_end (void)
int BPY_filepath_exec (struct bContext *C, const char *filepath, struct ReportList *reports)
int BPY_text_exec (struct bContext *C, struct Text *text, struct ReportList *reports, const short do_jump)
void BPY_text_free_code (struct Text *text)
void BPY_modules_update (struct bContext *C)
void BPY_modules_load_user (struct bContext *C)
void BPY_app_handlers_reset (const short do_all)
void BPY_driver_reset (void)
float BPY_driver_exec (struct ChannelDriver *driver, const float evaltime)
int BPY_button_exec (struct bContext *C, const char *expr, double *value, const short verbose)
int BPY_string_exec (struct bContext *C, const char *expr)
void BPY_DECREF (void *pyob_ptr)
int BPY_context_member_get (struct bContext *C, const char *member, struct bContextDataResult *result)
void BPY_context_set (struct bContext *C)
void BPY_id_release (struct ID *id)
Detailed Description
Definition in file BPY_extern.h.
Function Documentation
void BPY_app_handlers_reset (const short do_all)
Definition at line 235 of file bpy_app_handlers.c.
References BLI_CB_EVT_TOT, i, NULL, and PERMINENT_CB_ID.
Referenced by load_file(), WM_init(), WM_read_file(), and WM_read_homefile().
int BPY_button_exec (struct bContext * C, const char * expr, double * value, const short verbose)
Definition at line 489 of file bpy_interface.c.
References bpy_context_clear(), bpy_context_set(), BPy_errors_to_report(), CTX_wm_reports(), i, mod(), NULL, PyC_DefaultNameSpace(), and PyC_MainModule_Backup().
Referenced by ui_set_but_string_eval_num().
int BPY_context_member_get (struct bContext * C, const char * member, struct bContextDataResult * result)
Definition at line 652 of file bpy_interface.c.
References BLI_addtail(), BPy_StructRNA_Check, CTX_data_list_add(), CTX_data_pointer_set(), CTX_py_dict_get(), PointerRNA::data, G, G_DEBUG_PYTHON, i, PointerRNA::id, len(), link(), bContextDataResult::list, MEM_callocN(), NULL, CollectionPointerLink::ptr, and PointerRNA::type.
Referenced by ctx_data_get().
void BPY_context_set (struct bContext * C)
Definition at line 184 of file bpy_interface.c.
References BPy_SetContext().
Referenced by WM_init().
void BPY_DECREF (void * pyob_ptr)
Definition at line 481 of file bpy_interface.c.
Referenced by fcurve_free_driver(), RE_engine_free(), and WM_operator_free().
float BPY_driver_exec (struct ChannelDriver * driver, const float evaltime)
Definition at line 171 of file bpy_driver.c.
Referenced by evaluate_driver().
void BPY_driver_reset (void)
Definition at line 122 of file bpy_driver.c.
Referenced by load_file(), WM_init(), WM_read_file(), and WM_read_homefile().
int BPY_filepath_exec (struct bContext * C, const char * filepath, struct ReportList * reports)
Definition at line 470 of file bpy_interface.c.
References FALSE, NULL, and python_script_exec().
Referenced by run_pyfile_exec(), and run_python().
void BPY_id_release (struct ID * id)
Definition at line 293 of file bpy_rna.c.
Referenced by free_libblock().
int BPY_is_pyconstraint (struct Text * text)
void BPY_modules_load_user (struct bContext * C)
Definition at line 613 of file bpy_interface.c.
References BLI_testextensie(), bpy_context_clear(), bpy_context_set(), bpy_context_update(), bpy_text_import(), CTX_data_main(), Text::flags, G, G_SCRIPT_AUTOEXEC, Text::id, module, Main::name, ID::name, ID::next, NULL, py_call_level, and TXT_ISSCRIPT.
Referenced by load_file(), WM_init(), WM_read_file(), and WM_read_homefile().
void BPY_modules_update (struct bContext * C)
Definition at line 171 of file bpy_interface.c.
References BPY_rna_module(), BPY_rna_types(), BPY_update_rna_module(), PointerRNA::data, mod(), NULL, and BPy_StructRNA::ptr.
Referenced by bpy_context_update(), and pyop_call().
void BPY_pyconstraint_exec (struct bPythonConstraint * con, struct bConstraintOb * cob, struct ListBase * targets)
Referenced by pycon_evaluate().
void BPY_pyconstraint_target (struct bPythonConstraint * con, struct bConstraintTarget * ct)
Referenced by pycon_get_tarmat().
void BPY_pyconstraint_update (struct Object * owner, struct bConstraint * con)
Referenced by constraint_add_exec(), and text_refresh_pyconstraints_exec().
void BPY_python_end (void)
Definition at line 294 of file bpy_interface.c.
References BPY_atexit_unregister(), bpy_intern_string_exit(), PIL_check_seconds_timer(), and pyrna_free_types().
Referenced by WM_exit_ext().
void BPY_python_start (int argc, const char ** argv)
Definition at line 221 of file bpy_interface.c.
References BLENDER_SYSTEM_PYTHON, BLI_get_folder(), BLI_program_path(), BLI_setenv(), BLI_strncpy_wchar_from_utf8(), BPY_atexit_register(), bpy_import_init(), BPy_init_modules(), bpy_intern_string_init(), FILE_MAX, i, NULL, PyC_SetHomePath(), PyC_UnicodeFromByte(), and pyrna_alloc_types().
Referenced by WM_init().
int BPY_string_exec (struct bContext * C, const char * expr)
Definition at line 569 of file bpy_interface.c.
References bpy_context_clear(), bpy_context_set(), BPy_errors_to_report(), bpy_import_main_get(), bpy_import_main_set(), CTX_data_main(), CTX_wm_reports(), NULL, PyC_DefaultNameSpace(), PyC_MainModule_Backup(), and PyC_MainModule_Restore().
Referenced by run_python_console(), script_reload_exec(), set_addons(), and WM_read_homefile().
int BPY_text_exec (struct bContext * C, struct Text * text, struct ReportList * reports, const short do_jump)
Definition at line 476 of file bpy_interface.c.
References NULL, and python_script_exec().
Referenced by text_run_script().
void BPY_text_free_code (struct Text * text)
Definition at line 163 of file bpy_interface.c.
References Text::compiled, and NULL.
Referenced by free_text(), python_script_exec(), text_reload_exec(), and txt_make_dirty().