Blender: btSolverBody.h File Reference
btSolverBody.h File Reference
#include "LinearMath/btVector3.h"
#include "LinearMath/btMatrix3x3.h"
#include "BulletDynamics/Dynamics/btRigidBody.h"
#include "LinearMath/btAlignedAllocator.h"
#include "LinearMath/btTransformUtil.h"
Defines
#define btSimdScalar btScalar
Until we get other contributions, only use SIMD on Windows, when using Visual Studio 2008 or later, and not double precision.
Functions
ATTRIBUTE_ALIGNED64 (struct) btSolverBodyObsolete
The btSolverBody is an internal datastructure for the constraint solver. Only necessary data is packed to increase cache coherence/performance.
Define Documentation
#define btSimdScalar btScalar
Until we get other contributions, only use SIMD on Windows, when using Visual Studio 2008 or later, and not double precision.
Definition at line 104 of file btSolverBody.h.
Referenced by ATTRIBUTE_ALIGNED64(), btSequentialImpulseConstraintSolver::resolveSingleConstraintRowGenericSIMD(), btSequentialImpulseConstraintSolver::resolveSingleConstraintRowLowerLimitSIMD(), btSequentialImpulseConstraintSolver::resolveSplitPenetrationSIMD(), and btSequentialImpulseConstraintSolver::setupFrictionConstraint().
Function Documentation
ATTRIBUTE_ALIGNED64 (struct)
The btSolverBody is an internal datastructure for the constraint solver. Only necessary data is packed to increase cache coherence/performance.
Definition at line 108 of file btSolverBody.h.
References BT_DECLARE_ALIGNED_ALLOCATOR, cross(), btRigidBody::getAngularVelocity(), btRigidBody::getLinearVelocity(), btTransformUtil::integrateTransform(), btRigidBody::setAngularVelocity(), btRigidBody::setLinearVelocity(), and SIMD_FORCE_INLINE.