Blender: SCA_JoystickSensor Class Reference
SCA_JoystickSensor Class Reference
#include <SCA_JoystickSensor.h>
Public Member Functions
SCA_JoystickSensor (class SCA_JoystickManager *eventmgr, SCA_IObject *gameobj, short int joyindex, short int joymode, int axis, int axisf, int prec, int button, int hat, int hatf, bool allevents)
virtual ~SCA_JoystickSensor ()
virtual CValue * GetReplica ()
virtual bool Evaluate ()
virtual bool IsPositiveTrigger ()
virtual void Init ()
short int GetJoyIndex (void)
Detailed Description
Definition at line 39 of file SCA_JoystickSensor.h.
Constructor & Destructor Documentation
SCA_JoystickSensor::SCA_JoystickSensor (class SCA_JoystickManager * eventmgr, SCA_IObject * gameobj, short int joyindex, short int joymode, int axis, int axisf, int prec, int button, int hat, int hatf, bool allevents)
Definition at line 46 of file SCA_JoystickSensor.cpp.
References Init().
Referenced by GetReplica().
SCA_JoystickSensor::~SCA_JoystickSensor () [virtual]
Definition at line 82 of file SCA_JoystickSensor.cpp.
Member Function Documentation
bool SCA_JoystickSensor::Evaluate () [virtual]
Implements SCA_ISensor.
Definition at line 106 of file SCA_JoystickSensor.cpp.
References SCA_Joystick::aAnyButtonPressIsPositive(), SCA_Joystick::aAxisIsPositive(), SCA_Joystick::aAxisPairDirectionIsPositive(), SCA_Joystick::aAxisPairIsPositive(), SCA_Joystick::aButtonPressIsPositive(), SCA_Joystick::aHatIsPositive(), SCA_Joystick::cSetPrecision(), SCA_Joystick::GetHat(), SCA_Joystick::IsTrigAxis(), SCA_Joystick::IsTrigButton(), SCA_Joystick::IsTrigHat(), SCA_ISensor::m_eventmgr, SCA_ISensor::m_level, SCA_ISensor::m_reset, and NULL.
short int SCA_JoystickSensor::GetJoyIndex (void) [inline]
Definition at line 120 of file SCA_JoystickSensor.h.
CValue * SCA_JoystickSensor::GetReplica (void) [virtual]
Implements SCA_ISensor.
Definition at line 87 of file SCA_JoystickSensor.cpp.
References Init(), SCA_ISensor::ProcessReplica(), and SCA_JoystickSensor().
void SCA_JoystickSensor::Init (void) [virtual]
Reimplemented from SCA_ISensor.
Definition at line 75 of file SCA_JoystickSensor.cpp.
References SCA_ISensor::m_invert, and SCA_ISensor::m_reset.
Referenced by GetReplica(), and SCA_JoystickSensor().
bool SCA_JoystickSensor::IsPositiveTrigger () [virtual]
Reimplemented from SCA_ISensor.
Definition at line 97 of file SCA_JoystickSensor.cpp.
References SCA_ISensor::m_invert.
The documentation for this class was generated from the following files:
SCA_JoystickSensor.h
SCA_JoystickSensor.cpp