Blender: render_ops.c File Reference
render_ops.c File Reference
render
#include <stdlib.h>
#include "WM_api.h"
#include "ED_render.h"
#include "render_intern.h"
Functions
void ED_operatortypes_render (void)
Detailed Description
Definition in file render_ops.c.
Function Documentation
void ED_operatortypes_render (void)
Definition at line 46 of file render_ops.c.
References MATERIAL_OT_copy(), MATERIAL_OT_new(), MATERIAL_OT_paste(), OBJECT_OT_material_slot_add(), OBJECT_OT_material_slot_assign(), OBJECT_OT_material_slot_copy(), OBJECT_OT_material_slot_deselect(), OBJECT_OT_material_slot_remove(), OBJECT_OT_material_slot_select(), RENDER_OT_opengl(), RENDER_OT_render(), RENDER_OT_view_cancel(), RENDER_OT_view_show(), SCENE_OT_render_layer_add(), SCENE_OT_render_layer_remove(), TEXTURE_OT_envmap_clear(), TEXTURE_OT_envmap_clear_all(), TEXTURE_OT_envmap_save(), TEXTURE_OT_new(), TEXTURE_OT_slot_copy(), TEXTURE_OT_slot_move(), TEXTURE_OT_slot_paste(), WM_operatortype_append(), and WORLD_OT_new().
Referenced by ED_spacetypes_init().