Blender: nla_edit.c File Reference
nla_edit.c File Reference
NLA editor
#include <string.h>
#include <stdio.h>
#include <math.h>
#include "DNA_anim_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BKE_action.h"
#include "BKE_fcurve.h"
#include "BKE_nla.h"
#include "BKE_context.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "BKE_screen.h"
#include "ED_anim_api.h"
#include "ED_keyframes_edit.h"
#include "ED_markers.h"
#include "ED_screen.h"
#include "ED_transform.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "nla_intern.h"
#include "nla_private.h"
Functions
void ED_nla_postop_refresh (bAnimContext *ac)
static int nlaedit_enable_tweakmode_exec (bContext *C, wmOperator *op)
void NLA_OT_tweakmode_enter (wmOperatorType *ot)
static int nlaedit_disable_tweakmode_exec (bContext *C, wmOperator *op)
void NLA_OT_tweakmode_exit (wmOperatorType *ot)
static void get_nlastrip_extents (bAnimContext *ac, float *min, float *max, const short onlySel)
static int nlaedit_viewall (bContext *C, const short onlySel)
static int nlaedit_viewall_exec (bContext *C, wmOperator *UNUSED(op))
static int nlaedit_viewsel_exec (bContext *C, wmOperator *UNUSED(op))
void NLA_OT_view_all (wmOperatorType *ot)
void NLA_OT_view_selected (wmOperatorType *ot)
static int nlaedit_add_actionclip_exec (bContext *C, wmOperator *op)
void NLA_OT_actionclip_add (wmOperatorType *ot)
static int nlaedit_add_transition_exec (bContext *C, wmOperator *op)
void NLA_OT_transition_add (wmOperatorType *ot)
static int nlaedit_add_sound_exec (bContext *C, wmOperator *UNUSED(op))
void NLA_OT_soundclip_add (wmOperatorType *ot)
static int nlaedit_add_meta_exec (bContext *C, wmOperator *UNUSED(op))
void NLA_OT_meta_add (wmOperatorType *ot)
static int nlaedit_remove_meta_exec (bContext *C, wmOperator *UNUSED(op))
void NLA_OT_meta_remove (wmOperatorType *ot)
static int nlaedit_duplicate_exec (bContext *C, wmOperator *UNUSED(op))
static int nlaedit_duplicate_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void NLA_OT_duplicate (wmOperatorType *ot)
static int nlaedit_delete_exec (bContext *C, wmOperator *UNUSED(op))
void NLA_OT_delete (wmOperatorType *ot)
static void nlaedit_split_strip_actclip (AnimData *adt, NlaTrack *nlt, NlaStrip *strip, float cfra)
static void nlaedit_split_strip_meta (NlaTrack *nlt, NlaStrip *strip)
static int nlaedit_split_exec (bContext *C, wmOperator *UNUSED(op))
void NLA_OT_split (wmOperatorType *ot)
static int nlaedit_bake_exec (bContext *C, wmOperator *UNUSED(op))
void NLA_OT_bake (wmOperatorType *ot)
static int nlaedit_toggle_mute_exec (bContext *C, wmOperator *UNUSED(op))
void NLA_OT_mute_toggle (wmOperatorType *ot)
static int nlaedit_swap_exec (bContext *C, wmOperator *op)
void NLA_OT_swap (wmOperatorType *ot)
static int nlaedit_move_up_exec (bContext *C, wmOperator *UNUSED(op))
void NLA_OT_move_up (wmOperatorType *ot)
static int nlaedit_move_down_exec (bContext *C, wmOperator *UNUSED(op))
void NLA_OT_move_down (wmOperatorType *ot)
static int nlaedit_sync_actlen_exec (bContext *C, wmOperator *op)
void NLA_OT_action_sync_length (wmOperatorType *ot)
static short bezt_apply_nlamapping (KeyframeEditData *ked, BezTriple *bezt)
static int nlaedit_apply_scale_exec (bContext *C, wmOperator *UNUSED(op))
void NLA_OT_apply_scale (wmOperatorType *ot)
static int nlaedit_clear_scale_exec (bContext *C, wmOperator *UNUSED(op))
void NLA_OT_clear_scale (wmOperatorType *ot)
static int nlaedit_snap_exec (bContext *C, wmOperator *op)
void NLA_OT_snap (wmOperatorType *ot)
static int nla_fmodifier_add_invoke (bContext *C, wmOperator *UNUSED(op), wmEvent *UNUSED(event))
static int nla_fmodifier_add_exec (bContext *C, wmOperator *op)
void NLA_OT_fmodifier_add (wmOperatorType *ot)
static int nla_fmodifier_copy_exec (bContext *C, wmOperator *op)
void NLA_OT_fmodifier_copy (wmOperatorType *ot)
static int nla_fmodifier_paste_exec (bContext *C, wmOperator *op)
void NLA_OT_fmodifier_paste (wmOperatorType *ot)
Variables
static EnumPropertyItem prop_nlaedit_snap_types []
Detailed Description
Definition in file nla_edit.c.
Function Documentation
static short bezt_apply_nlamapping (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 1638 of file nla_edit.c.
References KeyframeEditData::data, nlastrip_get_frame(), NLATIME_CONVERT_MAP, and BezTriple::vec.
Referenced by nlaedit_apply_scale_exec().
void ED_nla_postop_refresh (bAnimContext * ac)
Definition at line 79 of file nla_edit.c.
References ANIM_animdata_filter(), ANIMFILTER_ANIMDATA, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, BKE_nla_validate_state(), BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, bAnimListElem::next, and NULL.
Referenced by nlaedit_add_actionclip_exec(), nlaedit_add_sound_exec(), nlaedit_add_transition_exec(), nlaedit_bake_exec(), nlaedit_clear_scale_exec(), nlaedit_delete_exec(), nlaedit_duplicate_exec(), nlaedit_move_down_exec(), nlaedit_move_up_exec(), nlaedit_snap_exec(), nlaedit_split_exec(), nlaedit_swap_exec(), and special_aftertrans_update().
static void get_nlastrip_extents (bAnimContext * ac, float * min, float * max, const short onlySel) [static]
Definition at line 244 of file nla_edit.c.
References ANIM_animdata_filter(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, RenderData::efra, filter(), ListBase::first, MAX2, MIN2, bAnimListElem::next, NLASTRIP_FLAG_SELECT, NULL, Scene::r, bAnimContext::scene, RenderData::sfra, and NlaTrack::strips.
Referenced by nlaedit_viewall().
static int nla_fmodifier_add_exec (bContext * C, wmOperator * op) [static]
Definition at line 1974 of file nla_edit.c.
References add_fmodifier(), ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BKE_reportf(), BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, NA_EDITED, NlaTrack::name, NC_ANIMATION, ND_NLA, bAnimListElem::next, NLASTRIP_FLAG_ACTIVE, NLASTRIP_FLAG_SELECT, NLASTRIP_TYPE_SOUND, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_enum_get(), RPT_ERROR, set_active_fmodifier(), NlaTrack::strips, and WM_event_add_notifier().
Referenced by NLA_OT_fmodifier_add().
static int nla_fmodifier_add_invoke (bContext * C, wmOperator * UNUSEDop, wmEvent * UNUSEDevent) [static]
Definition at line 1945 of file nla_edit.c.
References FMODIFIER_NUM_TYPES, FMODIFIER_TYPE_CYCLES, get_fmodifier_typeinfo(), i, FModifierTypeInfo::name, NULL, OPERATOR_CANCELLED, uiItemEnumO(), uiItemS(), uiPupMenuBegin(), uiPupMenuEnd(), and uiPupMenuLayout().
Referenced by NLA_OT_fmodifier_add().
static int nla_fmodifier_copy_exec (bContext * C, wmOperator * op) [static]
Definition at line 2061 of file nla_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIM_fmodifiers_copy_to_buf(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BKE_report(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, free_fmodifiers_copybuf(), bAnimListElem::next, NLASTRIP_FLAG_ACTIVE, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, and NlaTrack::strips.
Referenced by NLA_OT_fmodifier_copy().
static int nla_fmodifier_paste_exec (bContext * C, wmOperator * op) [static]
Definition at line 2123 of file nla_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIM_fmodifiers_paste_from_buf(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_SEL, BKE_report(), BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, NA_EDITED, NC_ANIMATION, ND_NLA, bAnimListElem::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, NlaTrack::strips, and WM_event_add_notifier().
Referenced by NLA_OT_fmodifier_paste().
void NLA_OT_action_sync_length (wmOperatorType * ot)
Definition at line 1616 of file nla_edit.c.
References wmOperatorType::description, ED_operator_nla_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_sync_actlen_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by nla_operatortypes().
void NLA_OT_actionclip_add (wmOperatorType * ot)
Definition at line 471 of file nla_edit.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, nlaedit_add_actionclip_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_action_itemf(), RNA_def_enum(), RNA_def_enum_funcs(), wmOperatorType::srna, and WM_enum_search_invoke().
Referenced by nla_operatortypes().
void NLA_OT_apply_scale (wmOperatorType * ot)
Definition at line 1716 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_apply_scale_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_bake (wmOperatorType * ot)
Definition at line 1173 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_bake_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
void NLA_OT_clear_scale (wmOperatorType * ot)
Definition at line 1779 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_clear_scale_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_delete (wmOperatorType * ot)
Definition at line 975 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_delete_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_duplicate (wmOperatorType * ot)
Definition at line 900 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, nlaedit_duplicate_exec(), nlaedit_duplicate_invoke(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, TFM_TRANSLATION, and transform_mode_types.
Referenced by nla_operatortypes().
void NLA_OT_fmodifier_add (wmOperatorType * ot)
Definition at line 2039 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, fmodifier_type_items, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, nla_fmodifier_add_exec(), nla_fmodifier_add_invoke(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), and wmOperatorType::srna.
Referenced by nla_operatortypes().
void NLA_OT_fmodifier_copy (wmOperatorType * ot)
Definition at line 2103 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nla_fmodifier_copy_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_fmodifier_paste (wmOperatorType * ot)
Definition at line 2165 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nla_fmodifier_paste_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_meta_add (wmOperatorType * ot)
Definition at line 745 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_add_meta_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_meta_remove (wmOperatorType * ot)
Definition at line 797 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_remove_meta_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_move_down (wmOperatorType * ot)
Definition at line 1540 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_move_down_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_move_up (wmOperatorType * ot)
Definition at line 1466 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_move_up_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_mute_toggle (wmOperatorType * ot)
Definition at line 1235 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_toggle_mute_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_snap (wmOperatorType * ot)
Definition at line 1920 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, nlaedit_snap_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by nla_operatortypes().
void NLA_OT_soundclip_add (wmOperatorType * ot)
Definition at line 683 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_add_sound_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_split (wmOperatorType * ot)
Definition at line 1120 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_split_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_swap (wmOperatorType * ot)
Definition at line 1392 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_swap_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_transition_add (wmOperatorType * ot)
Definition at line 598 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_add_transition_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_tweakmode_enter (wmOperatorType * ot)
Definition at line 158 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_enable_tweakmode_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_tweakmode_exit (wmOperatorType * ot)
Definition at line 223 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_disable_tweakmode_exec(), nlaop_poll_tweakmode_on(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_view_all (wmOperatorType * ot)
Definition at line 338 of file nla_edit.c.
References wmOperatorType::description, ED_operator_nla_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_viewall_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_view_selected (wmOperatorType * ot)
Definition at line 353 of file nla_edit.c.
References wmOperatorType::description, ED_operator_nla_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_viewsel_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
static int nlaedit_add_actionclip_exec (bContext * C, wmOperator * op) [static]
Definition at line 376 of file nla_edit.c.
References add_nlastrip(), add_nlatrack(), bAnimListElem::adt, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_ACTIVE, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, BKE_nlastrip_validate_name(), BKE_nlatrack_add_strip(), BKE_report(), BKE_reportf(), BLI_findlink(), BLI_freelistN(), CFRA, CTX_data_main(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, ED_nla_postop_refresh(), filter(), ListBase::first, GS, bAnimListElem::id, bAction::id, bAction::idroot, if(), NA_EDITED, ID::name, NC_ANIMATION, ND_NLA, bAnimListElem::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), RPT_ERROR, RPT_WARNING, bAnimContext::scene, and WM_event_add_notifier().
Referenced by NLA_OT_actionclip_add().
static int nlaedit_add_meta_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 702 of file nla_edit.c.
References bAnimListElem::adt, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BKE_nlastrip_validate_name(), BKE_nlastrips_make_metas(), BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, NA_EDITED, NC_ANIMATION, ND_NLA, bAnimListElem::next, NLASTRIP_FLAG_SELECT, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, NlaTrack::strips, and WM_event_add_notifier().
Referenced by NLA_OT_meta_add().
static int nlaedit_add_sound_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 616 of file nla_edit.c.
References add_nla_soundstrip(), add_nlatrack(), bAnimListElem::adt, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_SEL, BKE_nlastrip_validate_name(), BKE_nlatrack_add_strip(), BLI_freelistN(), CFRA, Object::data, bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, ED_nla_postop_refresh(), NlaStrip::end, filter(), ListBase::first, GS, bAnimListElem::id, ID_OB, NA_EDITED, ID::name, NC_ANIMATION, ND_NLA, bAnimListElem::next, NULL, OB_SPEAKER, OPERATOR_CANCELLED, OPERATOR_FINISHED, bAnimContext::scene, NlaStrip::start, Object::type, and WM_event_add_notifier().
Referenced by NLA_OT_soundclip_add().
static int nlaedit_add_transition_exec (bContext * C, wmOperator * op) [static]
Definition at line 498 of file nla_edit.c.
References bAnimListElem::adt, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BKE_nlastrip_validate_name(), BKE_report(), BLI_freelistN(), BLI_insertlinkafter(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, ED_nla_postop_refresh(), ELEM, NlaStrip::end, filter(), ListBase::first, NlaStrip::flag, if(), IS_EQF, ListBase::last, MEM_callocN(), NA_EDITED, NC_ANIMATION, ND_NLA, NlaStrip::next, bAnimListElem::next, NLASTRIP_FLAG_AUTO_BLENDS, NLASTRIP_FLAG_SELECT, NLASTRIP_TYPE_SOUND, NLASTRIP_TYPE_TRANSITION, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, NlaStrip::repeat, wmOperator::reports, RPT_ERROR, NlaStrip::scale, NlaStrip::start, NlaTrack::strips, NlaStrip::type, and WM_event_add_notifier().
Referenced by NLA_OT_transition_add().
static int nlaedit_apply_scale_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1652 of file nla_edit.c.
References bAnimContext::ads, ALE_ACT, ANIM_animchanneldata_keyframes_loop(), ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, bezt_apply_nlamapping(), BLI_freelistN(), calc_action_range(), calchandles_fcurve(), copy_action(), KeyframeEditData::data, bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, NA_EDITED, NC_ANIMATION, ND_NLA, bAnimListElem::next, NLASTRIP_FLAG_SELECT, NLASTRIP_TYPE_CLIP, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, NlaTrack::strips, and WM_event_add_notifier().
Referenced by NLA_OT_apply_scale().
static int nlaedit_bake_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1138 of file nla_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_ANIMDATA, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BLI_freelistN(), bAnimContext::data, bAnimContext::datatype, ED_nla_postop_refresh(), filter(), ListBase::first, NA_EDITED, NC_ANIMATION, ND_NLA, bAnimListElem::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by NLA_OT_bake().
static int nlaedit_clear_scale_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1734 of file nla_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, ED_nla_postop_refresh(), filter(), ListBase::first, NA_EDITED, NC_ANIMATION, ND_NLA, bAnimListElem::next, NLASTRIP_FLAG_SELECT, NLASTRIP_TYPE_CLIP, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, RNA_float_set(), RNA_NlaStrip, RNA_pointer_create(), NlaTrack::strips, and WM_event_add_notifier().
Referenced by NLA_OT_clear_scale().
static int nlaedit_delete_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 922 of file nla_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, ED_nla_postop_refresh(), filter(), ListBase::first, NlaStrip::flag, free_nlastrip(), NA_EDITED, NC_ANIMATION, ND_NLA, NlaStrip::next, bAnimListElem::next, NLASTRIP_FLAG_SELECT, NLASTRIP_TYPE_TRANSITION, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, NlaStrip::prev, NlaTrack::strips, NlaStrip::type, and WM_event_add_notifier().
Referenced by NLA_OT_delete().
static int nlaedit_disable_tweakmode_exec (bContext * C, wmOperator * op) [static]
Definition at line 175 of file nla_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_ANIMDATA, ANIMFILTER_DATA_VISIBLE, BKE_nla_tweakmode_exit(), BKE_report(), BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, Scene::flag, NC_ANIMATION, ND_NLA_ACTCHANGE, bAnimListElem::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, SCE_NLA_EDIT_ON, bAnimContext::scene, and WM_event_add_notifier().
Referenced by NLA_OT_tweakmode_exit().
static int nlaedit_duplicate_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 817 of file nla_edit.c.
References add_nlatrack(), bAnimListElem::adt, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BKE_nlastrip_validate_name(), BKE_nlatrack_add_strip(), BLI_freelistN(), copy_nlastrip(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, ED_nla_postop_refresh(), filter(), ListBase::first, NlaStrip::flag, ListBase::last, NA_EDITED, NC_ANIMATION, ND_NLA, NlaTrack::next, NlaStrip::next, next, NLASTRIP_FLAG_ACTIVE, NLASTRIP_FLAG_SELECT, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, bAnimListElem::prev, NlaTrack::strips, and WM_event_add_notifier().
Referenced by NLA_OT_duplicate(), and nlaedit_duplicate_invoke().
static int nlaedit_duplicate_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 890 of file nla_edit.c.
References nlaedit_duplicate_exec(), OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_set(), TFM_TRANSLATION, WM_OP_INVOKE_REGION_WIN, and WM_operator_name_call().
Referenced by NLA_OT_duplicate().
static int nlaedit_enable_tweakmode_exec (bContext * C, wmOperator * op) [static]
Definition at line 105 of file nla_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_ANIMDATA, ANIMFILTER_DATA_VISIBLE, BKE_nla_tweakmode_enter(), BKE_report(), BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, Scene::flag, NC_ANIMATION, ND_NLA_ACTCHANGE, bAnimListElem::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, SCE_NLA_EDIT_ON, bAnimContext::scene, and WM_event_add_notifier().
Referenced by NLA_OT_tweakmode_enter().
static int nlaedit_move_down_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1484 of file nla_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BKE_nlatrack_add_strip(), BKE_nlatrack_has_space(), BLI_freelistN(), BLI_remlink(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, ED_nla_postop_refresh(), NlaStrip::end, filter(), ListBase::first, NlaStrip::flag, if(), NA_EDITED, NC_ANIMATION, ND_NLA, NlaStrip::next, bAnimListElem::next, NLASTRIP_FLAG_SELECT, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, NlaTrack::prev, NlaStrip::start, NlaTrack::strips, and WM_event_add_notifier().
Referenced by NLA_OT_move_down().
static int nlaedit_move_up_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1410 of file nla_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BKE_nlatrack_add_strip(), BKE_nlatrack_has_space(), BLI_freelistN(), BLI_remlink(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, ED_nla_postop_refresh(), NlaStrip::end, filter(), ListBase::first, NlaStrip::flag, if(), ListBase::last, NA_EDITED, NC_ANIMATION, ND_NLA, NlaStrip::next, NlaTrack::next, NLASTRIP_FLAG_SELECT, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, bAnimListElem::prev, NlaStrip::start, NlaTrack::strips, and WM_event_add_notifier().
Referenced by NLA_OT_move_up().
static int nlaedit_remove_meta_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 763 of file nla_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BKE_nlastrips_clear_metas(), BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, NA_EDITED, NC_ANIMATION, ND_NLA, bAnimListElem::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, NlaTrack::strips, and WM_event_add_notifier().
Referenced by NLA_OT_meta_remove().
static int nlaedit_snap_exec (bContext * C, wmOperator * op) [static]
Definition at line 1806 of file nla_edit.c.
References add_nlatrack(), bAnimListElem::adt, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BKE_nlameta_flush_transforms(), BKE_nlastrips_clear_metas(), BKE_nlastrips_make_metas(), BKE_nlatrack_add_strip(), BLI_addtail(), BLI_freelistN(), BLI_remlink(), CFRA, bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, ED_markers_find_nearest_marker_time(), ED_nla_postop_refresh(), NlaStrip::end, filter(), ListBase::first, NlaStrip::flag, floorf, FPS, ListBase::last, bAnimContext::markers, NA_EDITED, NC_ANIMATION, ND_NLA, NlaStrip::next, NLAEDIT_SNAP_CFRA, NLAEDIT_SNAP_NEAREST_FRAME, NLAEDIT_SNAP_NEAREST_MARKER, NLAEDIT_SNAP_NEAREST_SECOND, NLASTRIP_FLAG_TEMP_META, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, bAnimListElem::prev, wmOperator::ptr, RNA_enum_get(), bAnimContext::scene, NlaStrip::start, NlaTrack::strips, and WM_event_add_notifier().
Referenced by NLA_OT_snap().
static int nlaedit_split_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1063 of file nla_edit.c.
References bAnimListElem::adt, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BLI_freelistN(), RenderData::cfra, bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, ED_nla_postop_refresh(), filter(), ListBase::first, NlaStrip::flag, NA_EDITED, NC_ANIMATION, ND_NLA, NlaStrip::next, next, bAnimListElem::next, nlaedit_split_strip_actclip(), nlaedit_split_strip_meta(), NLASTRIP_FLAG_SELECT, NLASTRIP_TYPE_CLIP, NLASTRIP_TYPE_META, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Scene::r, bAnimContext::scene, NlaTrack::strips, NlaStrip::type, and WM_event_add_notifier().
Referenced by NLA_OT_split().
static void nlaedit_split_strip_actclip (AnimData * adt, NlaTrack * nlt, NlaStrip * strip, float cfra) [static]
Definition at line 997 of file nla_edit.c.
References NlaStrip::actend, NlaStrip::actstart, BKE_nlastrip_validate_name(), BLI_insertlinkafter(), copy_nlastrip(), NlaStrip::end, NlaStrip::flag, IS_EQF, len(), NLASTRIP_FLAG_ACTIVE, nlastrip_get_frame(), NLATIME_CONVERT_UNMAP, NlaStrip::start, and NlaTrack::strips.
Referenced by nlaedit_split_exec().
static void nlaedit_split_strip_meta (NlaTrack * nlt, NlaStrip * strip) [static]
Definition at line 1055 of file nla_edit.c.
References BKE_nlastrips_clear_metastrip(), and NlaTrack::strips.
Referenced by nlaedit_split_exec().
static int nlaedit_swap_exec (bContext * C, wmOperator * op) [static]
Definition at line 1253 of file nla_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BKE_nlameta_flush_transforms(), BKE_nlastrips_clear_metas(), BKE_nlastrips_has_space(), BKE_nlastrips_make_metas(), BKE_nlatrack_add_strip(), BKE_report(), BKE_reportf(), BLI_countlist(), BLI_freelistN(), BLI_remlink(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, ED_nla_postop_refresh(), filter(), ListBase::first, NlaStrip::flag, if(), ListBase::last, NA_EDITED, NlaTrack::name, NC_ANIMATION, ND_NLA, NlaStrip::next, bAnimListElem::next, NLASTRIP_FLAG_SELECT, NLASTRIP_FLAG_TEMP_META, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_WARNING, NlaStrip::strips, NlaTrack::strips, and WM_event_add_notifier().
Referenced by NLA_OT_swap().
static int nlaedit_sync_actlen_exec (bContext * C, wmOperator * op) [static]
Definition at line 1558 of file nla_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_ACTIVE, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BKE_nlastrip_recalculate_bounds(), BLI_freelistN(), calc_action_range(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, NA_EDITED, NC_ANIMATION, ND_NLA, bAnimListElem::next, NLASTRIP_FLAG_ACTIVE, NLASTRIP_FLAG_SELECT, NLASTRIP_TYPE_CLIP, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), NlaTrack::strips, and WM_event_add_notifier().
Referenced by NLA_OT_action_sync_length().
static int nlaedit_toggle_mute_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1194 of file nla_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, NlaStrip::flag, NA_EDITED, NC_ANIMATION, ND_NLA, bAnimListElem::next, NLASTRIP_FLAG_MUTED, NLASTRIP_FLAG_SELECT, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, NlaTrack::strips, and WM_event_add_notifier().
Referenced by NLA_OT_mute_toggle().
static int nlaedit_viewall (bContext * C, const short onlySel) [static]
Definition at line 293 of file nla_edit.c.
References ANIM_animdata_get_context(), bAnimContext::ar, CTX_wm_area(), CTX_wm_screen(), View2D::cur, ED_area_tag_redraw(), get_nlastrip_extents(), View2D::mask, OPERATOR_CANCELLED, OPERATOR_FINISHED, UI_view2d_sync(), ARegion::v2d, V2D_LOCK_COPY, rctf::xmax, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by nlaedit_viewall_exec(), and nlaedit_viewsel_exec().
static int nlaedit_viewall_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 326 of file nla_edit.c.
References FALSE, and nlaedit_viewall().
Referenced by NLA_OT_view_all().
static int nlaedit_viewsel_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 332 of file nla_edit.c.
References nlaedit_viewall(), and TRUE.
Referenced by NLA_OT_view_selected().
Variable Documentation
EnumPropertyItem prop_nlaedit_snap_types[] [static]
Initial value:
 {
    {NLAEDIT_SNAP_CFRA, "CFRA", 0, "Current frame", ""},
    {NLAEDIT_SNAP_NEAREST_FRAME, "NEAREST_FRAME", 0, "Nearest Frame", ""},
    {NLAEDIT_SNAP_NEAREST_SECOND, "NEAREST_SECOND", 0, "Nearest Second", ""},
    {NLAEDIT_SNAP_NEAREST_MARKER, "NEAREST_MARKER", 0, "Nearest Marker", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 1798 of file nla_edit.c.