Blender: interface_widgets.c File Reference
interface_widgets.c File Reference
interface
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "DNA_screen_types.h"
#include "DNA_userdef_types.h"
#include "BLI_math.h"
#include "BLI_listbase.h"
#include "BLI_rect.h"
#include "BLI_string.h"
#include "BLI_string_utf8.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_curve.h"
#include "BKE_utildefines.h"
#include "RNA_access.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "BLF_api.h"
#include "UI_interface.h"
#include "UI_interface_icons.h"
#include "interface_intern.h"
Classes
struct uiWidgetTrias
struct uiWidgetBase
struct uiWidgetType
Defines
#define WIDGET_CURVE_RESOLU 9
#define WIDGET_SIZE_MAX (WIDGET_CURVE_RESOLU * 4)
#define WIDGET_AA_JITTER 8
#define PREVIEW_PAD 4
#define LINK_RESOL 24
#define SWATCH_KEYED_BORDER 3
Typedefs
typedef struct uiWidgetTrias uiWidgetTrias
typedef struct uiWidgetBase uiWidgetBase
typedef struct uiWidgetType uiWidgetType
Functions
void ui_draw_anti_tria (float x1, float y1, float x2, float y2, float x3, float y3)
void ui_draw_anti_roundbox (int mode, float minx, float miny, float maxx, float maxy, float rad)
static void widget_init (uiWidgetBase *wtb)
static int round_box_shadow_edges (float(*vert)[2], rcti *rect, float rad, int roundboxalign, float step)
static void round_box__edges (uiWidgetBase *wt, int roundboxalign, rcti *rect, float rad, float radi)
static void round_box_edges (uiWidgetBase *wt, int roundboxalign, rcti *rect, float rad)
static void widget_num_tria (uiWidgetTrias *tria, rcti *rect, float triasize, char where)
static void widget_scroll_circle (uiWidgetTrias *tria, rcti *rect, float triasize, char where)
static void widget_trias_draw (uiWidgetTrias *tria)
static void widget_menu_trias (uiWidgetTrias *tria, rcti *rect)
static void widget_check_trias (uiWidgetTrias *tria, rcti *rect)
static void shadecolors4 (char coltop[4], char *coldown, const char *color, short shadetop, short shadedown)
static void round_box_shade_col4_r (unsigned char col_r[4], const char col1[4], const char col2[4], const float fac)
static void widget_verts_to_quad_strip (uiWidgetBase *wtb, const int totvert, float quad_strip[WIDGET_SIZE_MAX *2+2][2])
static void widget_verts_to_quad_strip_open (uiWidgetBase *wtb, const int totvert, float quad_strip[WIDGET_SIZE_MAX *2][2])
static void widgetbase_outline (uiWidgetBase *wtb)
static void widgetbase_draw (uiWidgetBase *wtb, uiWidgetColors *wcol)
static void widget_draw_preview (BIFIconID icon, float UNUSED(alpha), rcti *rect)
static int ui_but_draw_menu_icon (uiBut *but)
static void widget_draw_icon (uiBut *but, BIFIconID icon, float alpha, rcti *rect)
static void ui_text_clip_give_prev_off (uiBut *but)
static void ui_text_clip_give_next_off (uiBut *but)
static void ui_text_leftclip (uiFontStyle *fstyle, uiBut *but, rcti *rect)
static void ui_text_label_rightclip (uiFontStyle *fstyle, uiBut *but, rcti *rect)
static void widget_draw_text (uiFontStyle *fstyle, uiWidgetColors *wcol, uiBut *but, rcti *rect)
static void widget_draw_text_icon (uiFontStyle *fstyle, uiWidgetColors *wcol, uiBut *but, rcti *rect)
void ui_widget_color_init (ThemeUI *tui)
static void widget_state_blend (char cp[3], const char cpstate[3], const float fac)
static void widget_state (uiWidgetType *wt, int state)
static void widget_state_numslider (uiWidgetType *wt, int state)
static void widget_state_label (uiWidgetType *wt, int state)
static void widget_state_option_menu (uiWidgetType *wt, int state)
static void widget_state_nothing (uiWidgetType *wt, int UNUSED(state))
static void widget_state_pulldown (uiWidgetType *wt, int state)
static void widget_state_menu_item (uiWidgetType *wt, int state)
static void widget_softshadow (rcti *rect, int roundboxalign, float radin, float radout)
static void widget_menu_back (uiWidgetColors *wcol, rcti *rect, int flag, int direction)
static void ui_hsv_cursor (float x, float y)
void ui_hsvcircle_vals_from_pos (float *valrad, float *valdist, rcti *rect, float mx, float my)
static void ui_draw_but_HSVCIRCLE (uiBut *but, uiWidgetColors *wcol, rcti *rect)
void ui_draw_gradient (rcti *rect, const float hsv[3], int type, float alpha)
static void ui_draw_but_HSVCUBE (uiBut *but, rcti *rect)
static void ui_draw_but_HSV_v (uiBut *but, rcti *rect)
static void ui_draw_separator (rcti *rect, uiWidgetColors *wcol)
static void widget_numbut (uiWidgetColors *wcol, rcti *rect, int state, int roundboxalign)
int ui_link_bezier_points (rcti *rect, float coord_array[][2], int resol)
void ui_draw_link_bezier (rcti *rect)
void uiWidgetScrollDraw (uiWidgetColors *wcol, rcti *rect, rcti *slider, int state)
static void widget_scroll (uiBut *but, uiWidgetColors *wcol, rcti *rect, int state, int UNUSED(roundboxalign))
static void widget_progressbar (uiBut *but, uiWidgetColors *wcol, rcti *rect, int UNUSED(state), int UNUSED(roundboxalign))
static void widget_link (uiBut *but, uiWidgetColors *UNUSED(wcol), rcti *rect, int UNUSED(state), int UNUSED(roundboxalign))
static void widget_numslider (uiBut *but, uiWidgetColors *wcol, rcti *rect, int state, int roundboxalign)
static void widget_swatch (uiBut *but, uiWidgetColors *wcol, rcti *rect, int state, int roundboxalign)
static void widget_icon_has_anim (uiBut *UNUSED(but), uiWidgetColors *wcol, rcti *rect, int state, int UNUSED(roundboxalign))
static void widget_textbut (uiWidgetColors *wcol, rcti *rect, int state, int roundboxalign)
static void widget_menubut (uiWidgetColors *wcol, rcti *rect, int UNUSED(state), int roundboxalign)
static void widget_menuiconbut (uiWidgetColors *wcol, rcti *rect, int UNUSED(state), int roundboxalign)
static void widget_menunodebut (uiWidgetColors *wcol, rcti *rect, int UNUSED(state), int roundboxalign)
static void widget_pulldownbut (uiWidgetColors *wcol, rcti *rect, int state, int UNUSED(roundboxalign))
static void widget_menu_itembut (uiWidgetColors *wcol, rcti *rect, int UNUSED(state), int UNUSED(roundboxalign))
static void widget_list_itembut (uiWidgetColors *wcol, rcti *rect, int UNUSED(state), int UNUSED(roundboxalign))
static void widget_optionbut (uiWidgetColors *wcol, rcti *rect, int state, int UNUSED(roundboxalign))
static void widget_radiobut (uiWidgetColors *wcol, rcti *rect, int UNUSED(state), int roundboxalign)
static void widget_box (uiBut *but, uiWidgetColors *wcol, rcti *rect, int UNUSED(state), int roundboxalign)
static void widget_but (uiWidgetColors *wcol, rcti *rect, int UNUSED(state), int roundboxalign)
static void widget_roundbut (uiWidgetColors *wcol, rcti *rect, int UNUSED(state), int roundboxalign)
static void widget_draw_extra_mask (const bContext *C, uiBut *but, uiWidgetType *wt, rcti *rect)
static void widget_disabled (rcti *rect)
static uiWidgetType * widget_type (uiWidgetTypeEnum type)
static int widget_roundbox_set (uiBut *but, rcti *rect)
void ui_draw_but (const bContext *C, ARegion *ar, uiStyle *style, uiBut *but, rcti *rect)
void ui_draw_menu_back (uiStyle *UNUSED(style), uiBlock *block, rcti *rect)
uiWidgetColors * ui_tooltip_get_theme (void)
void ui_draw_tooltip_background (uiStyle *UNUSED(style), uiBlock *UNUSED(block), rcti *rect)
void ui_draw_search_back (uiStyle *UNUSED(style), uiBlock *block, rcti *rect)
void ui_draw_menu_item (uiFontStyle *fstyle, rcti *rect, const char *name, int iconid, int state)
void ui_draw_preview_item (uiFontStyle *fstyle, rcti *rect, const char *name, int iconid, int state)
Variables
static float cornervec [WIDGET_CURVE_RESOLU][2]
static float jit [WIDGET_AA_JITTER][2]
static float num_tria_vert [3][2]
static unsigned int num_tria_face [1][3]
static float scroll_circle_vert [16][2]
static unsigned int scroll_circle_face [14][3]
static float menu_tria_vert [6][2]
static unsigned int menu_tria_face [2][3] = {{2, 0, 1}, {3, 5, 4}}
static float check_tria_vert [6][2]
static unsigned int check_tria_face [4][3]
GLubyte checker_stipple_sml [32 *32/8]
static struct uiWidgetStateColors wcol_state_colors
static struct uiWidgetColors wcol_num
static struct uiWidgetColors wcol_numslider
static struct uiWidgetColors wcol_text
static struct uiWidgetColors wcol_option
static struct uiWidgetColors wcol_menu
static struct uiWidgetColors wcol_pulldown
static struct uiWidgetColors wcol_menu_item
static struct uiWidgetColors wcol_menu_back
static struct uiWidgetColors wcol_tooltip
static struct uiWidgetColors wcol_radio
static struct uiWidgetColors wcol_regular
static struct uiWidgetColors wcol_tool
static struct uiWidgetColors wcol_box
static struct uiWidgetColors wcol_toggle
static struct uiWidgetColors wcol_scroll
static struct uiWidgetColors wcol_progress
static struct uiWidgetColors wcol_list_item
static struct uiWidgetColors wcol_tmp
Detailed Description
Definition in file interface_widgets.c.
Define Documentation
#define LINK_RESOL 24
Definition at line 2242 of file interface_widgets.c.
Referenced by ui_draw_link_bezier().
#define PREVIEW_PAD 4
Definition at line 828 of file interface_widgets.c.
Referenced by ui_draw_preview_item(), and widget_draw_preview().
#define SWATCH_KEYED_BORDER 3
Definition at line 2515 of file interface_widgets.c.
Referenced by widget_swatch().
#define WIDGET_AA_JITTER 8
Definition at line 133 of file interface_widgets.c.
Referenced by ui_draw_anti_roundbox(), ui_draw_anti_tria(), and widgetbase_draw().
#define WIDGET_CURVE_RESOLU 9
Definition at line 90 of file interface_widgets.c.
Referenced by round_box__edges(), and round_box_shadow_edges().
#define WIDGET_SIZE_MAX (WIDGET_CURVE_RESOLU * 4)
Definition at line 91 of file interface_widgets.c.
Referenced by round_box__edges(), widget_softshadow(), widgetbase_draw(), and widgetbase_outline().
Typedef Documentation
typedef struct uiWidgetBase uiWidgetBase
typedef struct uiWidgetTrias uiWidgetTrias
typedef struct uiWidgetType uiWidgetType
Function Documentation
static void round_box__edges (uiWidgetBase * wt, int roundboxalign, rcti * rect, float rad, float radi) [static]
Definition at line 327 of file interface_widgets.c.
References BLI_assert, cornervec, uiWidgetBase::halfwayvert, uiWidgetBase::inner_uv, uiWidgetBase::inner_v, MIN2, uiWidgetBase::outer_v, uiWidgetBase::totvert, UI_CNR_BOTTOM_LEFT, UI_CNR_BOTTOM_RIGHT, UI_CNR_TOP_LEFT, UI_CNR_TOP_RIGHT, WIDGET_CURVE_RESOLU, WIDGET_SIZE_MAX, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by round_box_edges(), and widget_draw_extra_mask().
static void round_box_edges (uiWidgetBase * wt, int roundboxalign, rcti * rect, float rad) [static]
Definition at line 476 of file interface_widgets.c.
References round_box__edges().
Referenced by ui_draw_but_HSV_v(), uiWidgetScrollDraw(), widget_box(), widget_but(), widget_draw_extra_mask(), widget_icon_has_anim(), widget_list_itembut(), widget_menu_back(), widget_menu_itembut(), widget_menubut(), widget_menuiconbut(), widget_menunodebut(), widget_numbut(), widget_numslider(), widget_optionbut(), widget_pulldownbut(), widget_radiobut(), widget_roundbut(), widget_swatch(), and widget_textbut().
static void round_box_shade_col4_r (unsigned char col_r[4], const char col1[4], const char col2[4], const float fac) [static]
Definition at line 620 of file interface_widgets.c.
References FTOCHAR.
Referenced by widgetbase_draw().
static int round_box_shadow_edges (float(*) vert[2], rcti * rect, float rad, int roundboxalign, float step) [static]
Definition at line 249 of file interface_widgets.c.
References cornervec, step(), UI_CNR_BOTTOM_LEFT, UI_CNR_BOTTOM_RIGHT, UI_CNR_TOP_LEFT, UI_CNR_TOP_RIGHT, WIDGET_CURVE_RESOLU, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by widget_softshadow().
static void shadecolors4 (char coltop[4], char * coldown, const char * color, short shadetop, short shadedown) [static]
Definition at line 606 of file interface_widgets.c.
References CLAMPIS.
Referenced by widgetbase_draw().
static int ui_but_draw_menu_icon (uiBut * but) [static]
Definition at line 851 of file interface_widgets.c.
References uiBut::dt, uiBut::flag, UI_EMBOSSP, and UI_ICON_SUBMENU.
Referenced by widget_draw_icon(), and widget_draw_text().
void ui_draw_anti_roundbox (int mode, float minx, float miny, float maxx, float maxy, float rad)
Definition at line 216 of file interface_widgets.c.
References jit, uiDrawBox(), and WIDGET_AA_JITTER.
Referenced by uiRoundBox().
void ui_draw_anti_tria (float x1, float y1, float x2, float y2, float x3, float y3)
Definition at line 191 of file interface_widgets.c.
References jit, and WIDGET_AA_JITTER.
Referenced by region_draw_azone_tab_plus(), region_draw_azone_tria(), ui_draw_tria_rect(), and UI_DrawTriIcon().
void ui_draw_but (const bContext * C, ARegion * ar, uiStyle * style, uiBut * but, rcti * rect)
Definition at line 3032 of file interface_widgets.c.
References uiBut::a1, BLOCK, uiBut::block, BUT, BUT_COLORBAND, BUT_CURVE, BUT_EXTRA, BUT_IMAGE, BUT_NORMAL, BUTM, COL, uiWidgetType::custom, uiWidgetType::draw, uiBut::dt, uiBut::editstr, uiBut::flag, uiBlock::flag, HISTOGRAM, HSVCIRCLE, HSVCUBE, HSVSLI, uiBut::icon, ICONTEXTROW, INLINK, LABEL, LINK, LISTBOX, LISTROW, MENU, NULL, NUM, NUMSLI, OPTION, OPTIONN, PROGRESSBAR, PULLDOWN, ROUNDBOX, ROW, SCROLL, SEARCH_MENU, SEPR, uiWidgetType::state, state, uiBut::str, TEX, uiWidgetType::text, TOG, TOG3, TOGBUT, TOGN, TRACKPREVIEW, bTheme::tui, uiBut::type, UI_BLOCK_LOOP, UI_BUT_DISABLED, UI_BUT_INACTIVE, UI_BUT_NODE_LINK, ui_draw_but_COLORBAND(), ui_draw_but_CURVE(), ui_draw_but_HISTOGRAM(), ui_draw_but_HSV_v(), ui_draw_but_HSVCIRCLE(), ui_draw_but_HSVCUBE(), ui_draw_but_IMAGE(), ui_draw_but_NORMAL(), ui_draw_but_TRACKPREVIEW(), ui_draw_but_VECTORSCOPE(), ui_draw_but_WAVEFORM(), ui_draw_separator(), UI_EMBOSSN, UI_EMBOSSP, UI_GetTheme(), UI_GRAD_V_ALT, UI_HAS_ICON, UI_TEXT_LEFT, UI_TEXTINPUT, UI_WTYPE_BOX, UI_WTYPE_EXEC, UI_WTYPE_ICON, UI_WTYPE_LABEL, UI_WTYPE_LISTITEM, UI_WTYPE_MENU_ICON_RADIO, UI_WTYPE_MENU_ITEM, UI_WTYPE_MENU_NODE_LINK, UI_WTYPE_MENU_RADIO, UI_WTYPE_NAME, UI_WTYPE_NUMBER, UI_WTYPE_OPTION, UI_WTYPE_PROGRESSBAR, UI_WTYPE_PULLDOWN, UI_WTYPE_RADIO, UI_WTYPE_REGULAR, UI_WTYPE_SCROLL, UI_WTYPE_SLIDER, UI_WTYPE_SWATCH, UI_WTYPE_TOGGLE, VECTORSCOPE, WAVEFORM, uiWidgetType::wcol, ThemeUI::wcol_menu_back, ThemeUI::wcol_menu_item, ThemeUI::wcol_regular, uiWidgetType::wcol_theme, uiStyle::widget, widget_disabled(), widget_draw_extra_mask(), widget_draw_text_icon(), widget_link(), widget_roundbox_set(), widget_state_option_menu(), widget_type(), and uiStyle::widgetlabel.
static void ui_draw_but_HSV_v (uiBut * but, rcti * rect) [static]
Definition at line 2126 of file interface_widgets.c.
References BLI_PR_NONE, uiBut::block, CLAMP(), uiBlock::color_profile, uiWidgetColors::inner, linearrgb_to_srgb(), uiWidgetColors::outline, PROP_COLOR_GAMMA, rgb_to_hsv(), RNA_property_subtype(), uiBut::rnaprop, round_box_edges(), uiWidgetColors::shaded, uiWidgetColors::shadedown, uiWidgetColors::shadetop, uiBut::softmax, uiBut::softmin, UI_CNR_ALL, ui_get_but_vectorf(), ui_hsv_cursor(), widget_init(), widgetbase_draw(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_but().
static void ui_draw_but_HSVCIRCLE (uiBut * but, uiWidgetColors * wcol, rcti * rect) [static]
Definition at line 1859 of file interface_widgets.c.
References BLI_PR_NONE, uiBut::block, CLAMP(), CLAMPIS, co, uiBlock::color_profile, copy_v3_v3(), cos(), cosf, uiBut::flag, glutil_draw_lined_arc(), hsv_to_rgb(), linearrgb_to_srgb(), M_PI, uiWidgetColors::outline, powf, PROP_COLOR_GAMMA, rgb_to_hsv_compat(), RNA_property_subtype(), uiBut::rnaprop, si, sin(), sinf, ui_block_hsv_get(), UI_BUT_COLOR_CUBIC, UI_BUT_COLOR_LOCK, ui_get_but_vectorf(), ui_hsv_cursor(), ui_hsvcircle_vals_from_pos(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_but().
static void ui_draw_but_HSVCUBE (uiBut * but, rcti * rect) [static]
Definition at line 2077 of file interface_widgets.c.
References uiBut::a1, uiBut::block, CLAMP(), fdrawbox(), rgb_to_hsv_compat(), ui_block_hsv_get(), ui_draw_gradient(), ui_get_but_vectorf(), UI_GRAD_H, UI_GRAD_HS, UI_GRAD_HV, UI_GRAD_S, UI_GRAD_SV, UI_GRAD_V, ui_hsv_cursor(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_but().
void ui_draw_gradient (rcti * rect, const float hsv[3], int type, float alpha)
Definition at line 1943 of file interface_widgets.c.
References assert, copy_v3_v3(), hsv_to_rgb(), UI_GRAD_H, UI_GRAD_HS, UI_GRAD_HV, UI_GRAD_S, UI_GRAD_SV, UI_GRAD_V, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_but_CURVE(), and ui_draw_but_HSVCUBE().
void ui_draw_link_bezier (rcti * rect)
Definition at line 2243 of file interface_widgets.c.
References LINK_RESOL, and ui_link_bezier_points().
Referenced by ui_draw_linkline(), and widget_link().
void ui_draw_menu_back (uiStyle * UNUSEDstyle, uiBlock * block, rcti * rect)
Definition at line 3243 of file interface_widgets.c.
References uiBlock::direction, uiWidgetType::draw, uiBlock::flag, uiWidgetType::state, uiWidgetColors::text, UI_BLOCK_CLIPBOTTOM, UI_BLOCK_CLIPTOP, UI_DrawTriIcon(), UI_WTYPE_MENU_BACK, uiWidgetType::wcol, widget_type(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
void ui_draw_menu_item (uiFontStyle * fstyle, rcti * rect, const char * name, int iconid, int state)
Definition at line 3300 of file interface_widgets.c.
References uiFontStyle::align, BLF_width(), uiWidgetType::draw, uiWidgetType::state, uiWidgetColors::text, UI_DPI_ICON_SIZE, UI_icon_draw_aspect(), UI_STYLE_TEXT_LEFT, UI_STYLE_TEXT_RIGHT, UI_WTYPE_MENU_ITEM, uiFontStyle::uifont_id, uiStyleFontDraw(), uiStyleFontSet(), uiWidgetType::wcol, widget_type(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_searchbox_region_draw_cb().
void ui_draw_preview_item (uiFontStyle * fstyle, rcti * rect, const char * name, int iconid, int state)
Definition at line 3346 of file interface_widgets.c.
References BLF_width_and_height(), uiWidgetType::draw, uiWidgetColors::item, PREVIEW_PAD, uiWidgetType::state, uiWidgetColors::text, uiWidgetColors::text_sel, TH_BUTBACK, UI_ACTIVE, UI_GetThemeColor3ubv(), UI_WTYPE_MENU_ITEM, uiFontStyle::uifont_id, uiStyleFontDraw(), uiWidgetType::wcol, widget_draw_preview(), widget_type(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_searchbox_region_draw_cb().
void ui_draw_search_back (uiStyle * UNUSEDstyle, uiBlock * block, rcti * rect)
Definition at line 3281 of file interface_widgets.c.
References uiWidgetType::draw, uiBlock::flag, uiWidgetType::state, UI_CNR_ALL, UI_WTYPE_BOX, uiWidgetType::wcol, widget_softshadow(), and widget_type().
static void ui_draw_separator (rcti * rect, uiWidgetColors * wcol) [static]
Definition at line 2173 of file interface_widgets.c.
References sdrawline(), uiWidgetColors::text, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_but().
void ui_draw_tooltip_background (uiStyle * UNUSEDstyle, uiBlock * UNUSEDblock, rcti * rect)
Definition at line 3273 of file interface_widgets.c.
References uiWidgetType::draw, uiWidgetType::state, UI_WTYPE_TOOLTIP, uiWidgetType::wcol, and widget_type().
static void ui_hsv_cursor (float x, float y) [static]
Definition at line 1816 of file interface_widgets.c.
References glutil_draw_filled_arc(), glutil_draw_lined_arc(), and M_PI.
Referenced by ui_draw_but_HSV_v(), ui_draw_but_HSVCIRCLE(), and ui_draw_but_HSVCUBE().
void ui_hsvcircle_vals_from_pos (float * valrad, float * valdist, rcti * rect, float mx, float my)
Definition at line 1836 of file interface_widgets.c.
References atan2f, M_PI, sqrt(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_but_HSVCIRCLE(), and ui_numedit_but_HSVCIRCLE().
int ui_link_bezier_points (rcti * rect, float coord_array[][2], int resol)
Definition at line 2219 of file interface_widgets.c.
References ABS, forward_diff_bezier(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by cut_links_intersect(), and ui_draw_link_bezier().
static void ui_text_clip_give_next_off (uiBut * but) [static]
Definition at line 954 of file interface_widgets.c.
References BLI_str_find_next_char_utf8(), uiBut::drawstr, NULL, and uiBut::ofs.
Referenced by ui_text_label_rightclip(), and ui_text_leftclip().
static void ui_text_clip_give_prev_off (uiBut * but) [static]
Definition at line 946 of file interface_widgets.c.
References BLI_str_find_prev_char_utf8(), uiBut::drawstr, and uiBut::ofs.
Referenced by ui_text_leftclip().
static void ui_text_label_rightclip (uiFontStyle * fstyle, uiBut * but, rcti * rect) [static]
Definition at line 1026 of file interface_widgets.c.
References BLF_disable(), BLF_enable(), BLF_KERNING_DEFAULT, BLF_width(), BLI_str_find_prev_char_utf8(), BLI_str_utf8_size(), uiBut::drawstr, uiBut::flag, uiFontStyle::kerning, len(), NULL, uiBut::ofs, strlen(), uiBut::strwidth, UI_BUT_ALIGN_RIGHT, ui_text_clip_give_next_off(), uiFontStyle::uifont_id, uiStyleFontSet(), rcti::xmax, and rcti::xmin.
Referenced by widget_draw_text_icon().
static void ui_text_leftclip (uiFontStyle * fstyle, uiBut * but, rcti * rect) [static]
Definition at line 963 of file interface_widgets.c.
References BLF_disable(), BLF_enable(), BLF_KERNING_DEFAULT, BLF_width(), BLI_str_find_prev_char_utf8(), BLI_str_utf8_size(), BLI_strncpy_utf8(), uiBut::drawstr, uiBut::editstr, uiBut::flag, uiFontStyle::kerning, len(), uiBut::ofs, uiBut::pos, strlen(), uiBut::strwidth, UI_BUT_ALIGN_RIGHT, UI_DPI_ICON_SIZE, UI_HAS_ICON, UI_MAX_DRAW_STR, ui_text_clip_give_next_off(), ui_text_clip_give_prev_off(), uiFontStyle::uifont_id, uiStyleFontSet(), rcti::xmax, and rcti::xmin.
Referenced by widget_draw_text_icon().
uiWidgetColors* ui_tooltip_get_theme (void)
Definition at line 3267 of file interface_widgets.c.
References UI_WTYPE_TOOLTIP, uiWidgetType::wcol_theme, and widget_type().
Referenced by ui_tooltip_region_draw_cb().
void ui_widget_color_init (ThemeUI * tui)
Definition at line 1565 of file interface_widgets.c.
References wcol_box, ThemeUI::wcol_box, ThemeUI::wcol_list_item, wcol_list_item, wcol_menu, ThemeUI::wcol_menu, wcol_menu_back, ThemeUI::wcol_menu_back, ThemeUI::wcol_menu_item, wcol_menu_item, ThemeUI::wcol_num, wcol_num, wcol_numslider, ThemeUI::wcol_numslider, wcol_option, ThemeUI::wcol_option, ThemeUI::wcol_progress, wcol_progress, ThemeUI::wcol_pulldown, wcol_pulldown, ThemeUI::wcol_radio, wcol_radio, ThemeUI::wcol_regular, wcol_regular, wcol_scroll, ThemeUI::wcol_scroll, ThemeUI::wcol_state, wcol_state_colors, wcol_text, ThemeUI::wcol_text, ThemeUI::wcol_toggle, wcol_toggle, ThemeUI::wcol_tool, wcol_tool, ThemeUI::wcol_tooltip, and wcol_tooltip.
Referenced by init_userdef_do_versions(), and ui_theme_init_default().
void uiWidgetScrollDraw (uiWidgetColors * wcol, rcti * rect, rcti * slider, int state)
Definition at line 2266 of file interface_widgets.c.
References copy_v4_v4_char(), uiWidgetBase::emboss, uiWidgetColors::inner, uiWidgetColors::item, uiWidgetBase::outline, uiWidgetColors::outline, round_box_edges(), uiWidgetBase::shadedir, uiWidgetColors::shadedown, uiWidgetColors::shadetop, SWAP, uiWidgetBase::tria1, uiWidgetBase::tria2, UI_CNR_ALL, UI_SCROLL_ARROWS, UI_SCROLL_NO_OUTLINE, UI_SCROLL_PRESSED, widget_init(), widget_scroll_circle(), widgetbase_draw(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by draw_textscroll(), UI_view2d_scrollers_draw(), widget_progressbar(), and widget_scroll().
static void widget_box (uiBut * but, uiWidgetColors * wcol, rcti * rect, int UNUSEDstate, int roundboxalign) [static]
Definition at line 2739 of file interface_widgets.c.
References uiBut::col, copy_v3_v3_char(), uiWidgetColors::inner, round_box_edges(), widget_init(), and widgetbase_draw().
Referenced by widget_type().
static void widget_but (uiWidgetColors * wcol, rcti * rect, int UNUSEDstate, int roundboxalign) [static]
Definition at line 2768 of file interface_widgets.c.
References round_box_edges(), widget_init(), and widgetbase_draw().
Referenced by widget_type().
static void widget_check_trias (uiWidgetTrias * tria, rcti * rect) [static]
Definition at line 585 of file interface_widgets.c.
References check_tria_face, check_tria_vert, uiWidgetTrias::index, size(), uiWidgetTrias::tot, uiWidgetTrias::vec, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by widget_optionbut().
static void widget_disabled (rcti * rect) [static]
Definition at line 2825 of file interface_widgets.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_but().
static void widget_draw_extra_mask (const bContext * C, uiBut * but, uiWidgetType * wt, rcti * rect) [static]
Definition at line 2794 of file interface_widgets.c.
References uiBut::block, uiBlock::drawextra, uiBlock::drawextra_arg1, uiBlock::drawextra_arg2, uiWidgetBase::inner, uiWidgetBase::outline, uiBut::poin, round_box__edges(), round_box_edges(), TH_BACK, UI_CNR_ALL, UI_GetThemeColor3ubv(), uiWidgetType::wcol, uiWidgetType::wcol_theme, widget_init(), widgetbase_draw(), and widgetbase_outline().
Referenced by ui_draw_but().
static void widget_draw_icon (uiBut * but, BIFIconID icon, float alpha, rcti * rect) [static]
Definition at line 858 of file interface_widgets.c.
References uiBut::a1, uiBut::a2, uiBut::aspect, uiBlock::aspect, uiBut::block, BUT_TOGDUAL, uiBut::dragpoin, uiBut::drawstr, ELEM4, uiBut::flag, uiBlock::flag, ICONROW, ICONTEXTROW, LABEL, LISTROW, ROW, SEARCH_MENU, TOG, TOGN, uiBut::type, UI_ACTIVE, UI_BLOCK_LOOP, ui_but_draw_menu_icon(), UI_DPI_ICON_SIZE, UI_icon_draw_aspect(), UI_icon_draw_aspect_color(), UI_ICON_LEFT, UI_ICON_PREVIEW, UI_ICON_SUBMENU, UI_SELECT, widget_draw_preview(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by widget_draw_text_icon().
static void widget_draw_preview (BIFIconID icon, float UNUSEDalpha, rcti * rect) [static]
Definition at line 830 of file interface_widgets.c.
References MIN2, PREVIEW_PAD, size(), UI_icon_draw_preview_aspect_size(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_preview_item(), and widget_draw_icon().
static void widget_draw_text (uiFontStyle * fstyle, uiWidgetColors * wcol, uiBut * but, rcti * rect) [static]
Definition at line 1091 of file interface_widgets.c.
References uiFontStyle::align, uiBut::aspect, BLF_disable(), BLF_draw(), BLF_enable(), BLF_KERNING_DEFAULT, BLF_position(), BLF_width(), BLI_strncpy(), uiBut::block, uiBut::drawstr, uiBut::editstr, ELEM5, uiBut::flag, uiBlock::flag, uiWidgetColors::item, uiFontStyle::kerning, uiBut::menu_key, NULL, NUM, NUMABS, NUMSLI, uiBut::ofs, uiBut::pos, uiBut::selend, uiBut::selsta, SLI, str, TEX, uiWidgetColors::text, uiBut::type, UI_BLOCK_LOOP, ui_but_draw_menu_icon(), UI_DPI_ICON_SIZE, UI_STYLE_TEXT_CENTER, UI_STYLE_TEXT_LEFT, UI_STYLE_TEXT_RIGHT, UI_TEXT_LEFT, uiFontStyle::uifont_id, uiStyleFontDraw(), uiStyleFontDrawExt(), uiStyleFontSet(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by widget_draw_text_icon().
static void widget_draw_text_icon (uiFontStyle * fstyle, uiWidgetColors * wcol, uiBut * but, rcti * rect) [static]
Definition at line 1224 of file interface_widgets.c.
References uiBut::bitnr, uiBut::block, BTST, BUT, BUT_TOGDUAL, uiBut::editstr, ELEM, ELEM4, uiBut::flag, uiBlock::flag, uiBut::icon, uiBut::iconadd, ICONTEXTROW, INT, MENU, NULL, NUM, NUMABS, NUMSLI, uiBut::ofs, uiBut::poin, uiBut::pointype, uiBut::pos, SEARCH_MENU, SHO, SLI, TEX, uiBut::type, UI_BLOCK_LOOP, UI_BUT_NODE_LINK, UI_DPI_ICON_FAC, UI_HAS_ICON, UI_icon_get_width(), ui_text_label_rightclip(), UI_TEXT_LEFT, ui_text_leftclip(), widget_draw_icon(), widget_draw_text(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_but(), and widget_type().
static void widget_icon_has_anim (uiBut * UNUSEDbut, uiWidgetColors * wcol, rcti * rect, int state, int UNUSEDroundboxalign) [static]
Definition at line 2566 of file interface_widgets.c.
References uiWidgetBase::outline, round_box_edges(), UI_BUT_ANIMATED, UI_BUT_ANIMATED_KEY, UI_BUT_DRIVEN, UI_BUT_REDALERT, UI_CNR_ALL, widget_init(), and widgetbase_draw().
Referenced by widget_type().
static void widget_init (uiWidgetBase * wtb) [static]
Definition at line 235 of file interface_widgets.c.
References uiWidgetBase::emboss, uiWidgetBase::halfwayvert, uiWidgetBase::inner, uiWidgetBase::outline, uiWidgetBase::shadedir, uiWidgetTrias::tot, uiWidgetBase::totvert, uiWidgetBase::tria1, and uiWidgetBase::tria2.
Referenced by ui_draw_but_HSV_v(), uiWidgetScrollDraw(), widget_box(), widget_but(), widget_draw_extra_mask(), widget_icon_has_anim(), widget_list_itembut(), widget_menu_back(), widget_menu_itembut(), widget_menubut(), widget_menuiconbut(), widget_menunodebut(), widget_numbut(), widget_numslider(), widget_optionbut(), widget_pulldownbut(), widget_radiobut(), widget_roundbut(), widget_swatch(), and widget_textbut().
static void widget_link (uiBut * but, uiWidgetColors * UNUSEDwcol, rcti * rect, int UNUSEDstate, int UNUSEDroundboxalign) [static]
Definition at line 2428 of file interface_widgets.c.
References uiBut::flag, uiBut::linkto, TH_TEXT_HI, ui_draw_link_bezier(), UI_SELECT, UI_ThemeColor(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_but().
static void widget_list_itembut (uiWidgetColors * wcol, rcti * rect, int UNUSEDstate, int UNUSEDroundboxalign) [static]
Definition at line 2680 of file interface_widgets.c.
References uiWidgetBase::outline, round_box_edges(), UI_CNR_ALL, widget_init(), and widgetbase_draw().
Referenced by widget_type().
static void widget_menu_back (uiWidgetColors * wcol, rcti * rect, int flag, int direction) [static]
Definition at line 1784 of file interface_widgets.c.
References uiWidgetBase::emboss, round_box_edges(), UI_BLOCK_POPUP, UI_CNR_ALL, UI_CNR_BOTTOM_LEFT, UI_CNR_BOTTOM_RIGHT, UI_CNR_TOP_LEFT, UI_CNR_TOP_RIGHT, UI_DOWN, UI_TOP, widget_init(), widget_softshadow(), widgetbase_draw(), rcti::ymax, and rcti::ymin.
Referenced by widget_type().
static void widget_menu_itembut (uiWidgetColors * wcol, rcti * rect, int UNUSEDstate, int UNUSEDroundboxalign) [static]
Definition at line 2667 of file interface_widgets.c.
References uiWidgetBase::outline, round_box_edges(), widget_init(), and widgetbase_draw().
Referenced by widget_type().
static void widget_menu_trias (uiWidgetTrias * tria, rcti * rect) [static]
Definition at line 561 of file interface_widgets.c.
References uiWidgetTrias::index, menu_tria_face, menu_tria_vert, size(), uiWidgetTrias::tot, uiWidgetTrias::vec, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by widget_menubut().
static void widget_menubut (uiWidgetColors * wcol, rcti * rect, int UNUSEDstate, int roundboxalign) [static]
Definition at line 2598 of file interface_widgets.c.
References round_box_edges(), uiWidgetBase::tria1, widget_init(), widget_menu_trias(), widgetbase_draw(), rcti::xmax, rcti::ymax, and rcti::ymin.
Referenced by widget_type().
static void widget_menuiconbut (uiWidgetColors * wcol, rcti * rect, int UNUSEDstate, int roundboxalign) [static]
Definition at line 2616 of file interface_widgets.c.
References round_box_edges(), widget_init(), and widgetbase_draw().
Referenced by widget_type().
static void widget_menunodebut (uiWidgetColors * wcol, rcti * rect, int UNUSEDstate, int roundboxalign) [static]
Definition at line 2629 of file interface_widgets.c.
References uiWidgetColors::inner, uiWidgetColors::outline, round_box_edges(), widget_init(), and widgetbase_draw().
Referenced by widget_type().
static void widget_num_tria (uiWidgetTrias * tria, rcti * rect, float triasize, char where) [static]
Definition at line 483 of file interface_widgets.c.
References uiWidgetTrias::index, MIN2, num_tria_face, num_tria_vert, uiWidgetTrias::tot, uiWidgetTrias::vec, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by widget_numbut().
static void widget_numbut (uiWidgetColors * wcol, rcti * rect, int state, int roundboxalign) [static]
Definition at line 2191 of file interface_widgets.c.
References round_box_edges(), uiWidgetColors::shadedown, uiWidgetColors::shadetop, SWAP, uiWidgetBase::tria1, uiWidgetBase::tria2, UI_SELECT, UI_TEXTINPUT, widget_init(), widget_num_tria(), widgetbase_draw(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by widget_type().
static void widget_numslider (uiBut * but, uiWidgetColors * wcol, rcti * rect, int state, int roundboxalign) [static]
Definition at line 2445 of file interface_widgets.c.
References copy_v3_v3_char(), uiWidgetColors::inner, uiWidgetBase::inner, uiWidgetColors::item, offs, uiWidgetBase::outline, uiWidgetColors::outline, round_box_edges(), uiWidgetColors::shadedown, uiWidgetColors::shadetop, uiBut::softmax, uiBut::softmin, SWAP, UI_CNR_BOTTOM_LEFT, UI_CNR_BOTTOM_RIGHT, UI_CNR_TOP_LEFT, UI_CNR_TOP_RIGHT, ui_get_but_val(), UI_SELECT, UI_TEXTINPUT, widget_init(), widgetbase_draw(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by widget_type().
static void widget_optionbut (uiWidgetColors * wcol, rcti * rect, int state, int UNUSEDroundboxalign) [static]
Definition at line 2693 of file interface_widgets.c.
References round_box_edges(), uiWidgetBase::tria1, UI_CNR_ALL, UI_SELECT, widget_check_trias(), widget_init(), widgetbase_draw(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by widget_type().
static void widget_progressbar (uiBut * but, uiWidgetColors * wcol, rcti * rect, int UNUSEDstate, int UNUSEDroundboxalign) [static]
Definition at line 2402 of file interface_widgets.c.
References uiBut::a1, MAX2, min, UI_SCROLL_NO_OUTLINE, uiWidgetScrollDraw(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by widget_type().
static void widget_pulldownbut (uiWidgetColors * wcol, rcti * rect, int state, int UNUSEDroundboxalign) [static]
Definition at line 2652 of file interface_widgets.c.
References round_box_edges(), UI_ACTIVE, UI_CNR_ALL, widget_init(), widgetbase_draw(), rcti::ymax, and rcti::ymin.
Referenced by widget_type().
static void widget_radiobut (uiWidgetColors * wcol, rcti * rect, int UNUSEDstate, int roundboxalign) [static]
Definition at line 2726 of file interface_widgets.c.
References round_box_edges(), widget_init(), and widgetbase_draw().
Referenced by widget_type().
static int widget_roundbox_set (uiBut * but, rcti * rect) [static]
Definition at line 2996 of file interface_widgets.c.
References uiBut::flag, UI_BUT_ALIGN, UI_BUT_ALIGN_DOWN, UI_BUT_ALIGN_LEFT, UI_BUT_ALIGN_RIGHT, UI_BUT_ALIGN_TOP, UI_CNR_ALL, UI_CNR_BOTTOM_LEFT, UI_CNR_BOTTOM_RIGHT, UI_CNR_TOP_LEFT, UI_CNR_TOP_RIGHT, rcti::xmin, and rcti::ymax.
Referenced by ui_draw_but().
static void widget_roundbut (uiWidgetColors * wcol, rcti * rect, int UNUSEDstate, int roundboxalign) [static]
Definition at line 2781 of file interface_widgets.c.
References round_box_edges(), widget_init(), and widgetbase_draw().
Referenced by widget_type().
static void widget_scroll (uiBut * but, uiWidgetColors * wcol, rcti * rect, int state, int UNUSEDroundboxalign) [static]
Definition at line 2341 of file interface_widgets.c.
References uiBut::a1, ceilf, MAX2, min, size(), uiBut::softmax, uiBut::softmin, ui_get_but_val(), UI_SCROLL_PRESSED, UI_SELECT, uiWidgetScrollDraw(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by widget_type().
static void widget_scroll_circle (uiWidgetTrias * tria, rcti * rect, float triasize, char where) [static]
Definition at line 518 of file interface_widgets.c.
References uiWidgetTrias::index, MIN2, scroll_circle_face, scroll_circle_vert, uiWidgetTrias::tot, uiWidgetTrias::vec, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by uiWidgetScrollDraw().
static void widget_softshadow (rcti * rect, int roundboxalign, float radin, float radout) [static]
Definition at line 1747 of file interface_widgets.c.
References uiWidgetBase::inner_v, uiWidgetBase::outer_v, round_box_shadow_edges(), step(), UI_CNR_ALL, UI_CNR_BOTTOM_LEFT, UI_CNR_BOTTOM_RIGHT, WIDGET_SIZE_MAX, widget_verts_to_quad_strip_open(), rcti::ymax, and rcti::ymin.
Referenced by ui_draw_search_back(), and widget_menu_back().
static void widget_state (uiWidgetType * wt, int state) [static]
Definition at line 1600 of file interface_widgets.c.
References uiWidgetStateColors::blend, copy_v3_v3_char(), copy_v4_v4_char(), uiWidgetColors::inner, uiWidgetStateColors::inner_anim, uiWidgetStateColors::inner_anim_sel, uiWidgetStateColors::inner_driven, uiWidgetStateColors::inner_driven_sel, uiWidgetStateColors::inner_key, uiWidgetStateColors::inner_key_sel, uiWidgetColors::inner_sel, uiWidgetColors::shadedown, uiWidgetColors::shadetop, SWAP, uiWidgetColors::text, uiWidgetColors::text_sel, UI_ACTIVE, UI_BUT_ANIMATED, UI_BUT_ANIMATED_KEY, UI_BUT_DRIVEN, UI_BUT_NODE_ACTIVE, UI_BUT_REDALERT, UI_SELECT, uiWidgetType::wcol, uiWidgetType::wcol_state, uiWidgetType::wcol_theme, and widget_state_blend().
Referenced by widget_state_label(), widget_state_numslider(), widget_state_option_menu(), and widget_type().
static void widget_state_blend (char cp[3], const char cpstate[3], const float fac) [static]
Definition at line 1590 of file interface_widgets.c.
Referenced by widget_state(), and widget_state_numslider().
static void widget_state_label (uiWidgetType * wt, int state) [static]
Definition at line 1680 of file interface_widgets.c.
References uiWidgetColors::text, TH_TEXT, TH_TEXT_HI, UI_GetThemeColor4ubv(), UI_SELECT, uiWidgetType::wcol, and widget_state().
Referenced by widget_type().
static void widget_state_menu_item (uiWidgetType * wt, int state) [static]
Definition at line 1728 of file interface_widgets.c.
References copy_v3_v3_char(), copy_v4_v4_char(), uiWidgetColors::inner, uiWidgetColors::inner_sel, uiWidgetColors::text, uiWidgetColors::text_sel, UI_ACTIVE, UI_BUT_DISABLED, UI_BUT_INACTIVE, uiWidgetType::wcol, and uiWidgetType::wcol_theme.
Referenced by widget_type().
static void widget_state_nothing (uiWidgetType * wt, int UNUSEDstate) [static]
Definition at line 1710 of file interface_widgets.c.
References uiWidgetType::wcol, and uiWidgetType::wcol_theme.
Referenced by widget_type().
static void widget_state_numslider (uiWidgetType * wt, int state) [static]
Definition at line 1647 of file interface_widgets.c.
References blend(), uiWidgetStateColors::blend, uiWidgetStateColors::inner_anim, uiWidgetStateColors::inner_anim_sel, uiWidgetStateColors::inner_driven, uiWidgetStateColors::inner_driven_sel, uiWidgetStateColors::inner_key, uiWidgetStateColors::inner_key_sel, uiWidgetColors::item, uiWidgetColors::shadedown, uiWidgetColors::shadetop, SWAP, UI_BUT_ANIMATED, UI_BUT_ANIMATED_KEY, UI_BUT_DRIVEN, UI_SELECT, uiWidgetType::wcol, uiWidgetType::wcol_state, widget_state(), and widget_state_blend().
Referenced by widget_type().
static void widget_state_option_menu (uiWidgetType * wt, int state) [static]
Definition at line 1693 of file interface_widgets.c.
References copy_v3_v3_char(), uiWidgetColors::text, TH_TEXT_HI, bTheme::tui, UI_GetTheme(), UI_GetThemeColor4ubv(), UI_SELECT, uiWidgetType::wcol, ThemeUI::wcol_menu_back, and widget_state().
Referenced by ui_draw_but().
static void widget_state_pulldown (uiWidgetType * wt, int state) [static]
Definition at line 1716 of file interface_widgets.c.
References copy_v3_v3_char(), copy_v4_v4_char(), uiWidgetColors::inner, uiWidgetColors::inner_sel, uiWidgetColors::outline, uiWidgetColors::text, uiWidgetColors::text_sel, UI_ACTIVE, uiWidgetType::wcol, and uiWidgetType::wcol_theme.
Referenced by widget_type().
static void widget_swatch (uiBut * but, uiWidgetColors * wcol, rcti * rect, int state, int roundboxalign) [static]
Definition at line 2517 of file interface_widgets.c.
References uiWidgetColors::alpha_check, BLI_PR_NONE, uiBut::block, uiBlock::color_profile, uiWidgetColors::inner, linearrgb_to_srgb_v3_v3(), PROP_COLOR_GAMMA, rgba_float_to_uchar(), RNA_property_array_length(), RNA_property_float_get_index(), RNA_property_subtype(), uiBut::rnapoin, uiBut::rnaprop, round_box_edges(), uiWidgetColors::shaded, SWATCH_KEYED_BORDER, UI_BUT_ANIMATED, UI_BUT_ANIMATED_KEY, UI_BUT_DRIVEN, UI_BUT_REDALERT, ui_get_but_vectorf(), widget_init(), widgetbase_draw(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by widget_type().
static void widget_textbut (uiWidgetColors * wcol, rcti * rect, int state, int roundboxalign) [static]
Definition at line 2581 of file interface_widgets.c.
References round_box_edges(), uiWidgetColors::shadedown, uiWidgetColors::shadetop, SWAP, UI_SELECT, widget_init(), and widgetbase_draw().
Referenced by widget_type().
static void widget_trias_draw (uiWidgetTrias * tria) [static]
Definition at line 553 of file interface_widgets.c.
References uiWidgetTrias::index, uiWidgetTrias::tot, and uiWidgetTrias::vec.
Referenced by widgetbase_draw().
static uiWidgetType* widget_type (uiWidgetTypeEnum type) [static]
Definition at line 2842 of file interface_widgets.c.
References uiWidgetType::custom, uiWidgetType::draw, NULL, uiWidgetType::state, uiWidgetType::text, bTheme::tui, UI_GetTheme(), UI_WTYPE_BOX, UI_WTYPE_EXEC, UI_WTYPE_FILENAME, UI_WTYPE_ICON, UI_WTYPE_LABEL, UI_WTYPE_LISTITEM, UI_WTYPE_MENU_BACK, UI_WTYPE_MENU_ICON_RADIO, UI_WTYPE_MENU_ITEM, UI_WTYPE_MENU_NODE_LINK, UI_WTYPE_MENU_POINTER_LINK, UI_WTYPE_MENU_RADIO, UI_WTYPE_NAME, UI_WTYPE_NAME_LINK, UI_WTYPE_NORMAL, UI_WTYPE_NUMBER, UI_WTYPE_OPTION, UI_WTYPE_POINTER_LINK, UI_WTYPE_PROGRESSBAR, UI_WTYPE_PULLDOWN, UI_WTYPE_RADIO, UI_WTYPE_REGULAR, UI_WTYPE_RGB_PICKER, UI_WTYPE_SCROLL, UI_WTYPE_SLIDER, UI_WTYPE_SWATCH, UI_WTYPE_TOGGLE, UI_WTYPE_TOOLTIP, ThemeUI::wcol_box, ThemeUI::wcol_list_item, ThemeUI::wcol_menu, ThemeUI::wcol_menu_back, ThemeUI::wcol_menu_item, ThemeUI::wcol_num, ThemeUI::wcol_numslider, ThemeUI::wcol_option, ThemeUI::wcol_progress, ThemeUI::wcol_pulldown, ThemeUI::wcol_radio, ThemeUI::wcol_regular, ThemeUI::wcol_scroll, ThemeUI::wcol_state, uiWidgetType::wcol_state, ThemeUI::wcol_text, uiWidgetType::wcol_theme, ThemeUI::wcol_toggle, ThemeUI::wcol_tool, ThemeUI::wcol_tooltip, widget_box(), widget_but(), widget_draw_text_icon(), widget_icon_has_anim(), widget_list_itembut(), widget_menu_back(), widget_menu_itembut(), widget_menubut(), widget_menuiconbut(), widget_menunodebut(), widget_numbut(), widget_numslider(), widget_optionbut(), widget_progressbar(), widget_pulldownbut(), widget_radiobut(), widget_roundbut(), widget_scroll(), widget_state(), widget_state_label(), widget_state_menu_item(), widget_state_nothing(), widget_state_numslider(), widget_state_pulldown(), widget_swatch(), and widget_textbut().
Referenced by ui_draw_but(), ui_draw_menu_back(), ui_draw_menu_item(), ui_draw_preview_item(), ui_draw_search_back(), ui_draw_tooltip_background(), and ui_tooltip_get_theme().
static void widget_verts_to_quad_strip (uiWidgetBase * wtb, const int totvert, float quad_strip[WIDGET_SIZE_MAX *2+2][2]) [static]
Definition at line 631 of file interface_widgets.c.
References copy_v2_v2(), uiWidgetBase::inner_v, and uiWidgetBase::outer_v.
Referenced by widgetbase_draw(), and widgetbase_outline().
static void widget_verts_to_quad_strip_open (uiWidgetBase * wtb, const int totvert, float quad_strip[WIDGET_SIZE_MAX *2][2]) [static]
Definition at line 642 of file interface_widgets.c.
References uiWidgetBase::outer_v.
Referenced by widget_softshadow(), and widgetbase_draw().
static void widgetbase_draw (uiWidgetBase * wtb, uiWidgetColors * wcol) [static]
Definition at line 664 of file interface_widgets.c.
References uiWidgetColors::alpha_check, checker_stipple_sml, uiWidgetBase::emboss, uiWidgetBase::halfwayvert, uiWidgetColors::inner, uiWidgetBase::inner, uiWidgetBase::inner_uv, uiWidgetBase::inner_v, uiWidgetColors::item, jit, MIN2, uiWidgetBase::outline, uiWidgetColors::outline, round_box_shade_col4_r(), shadecolors4(), uiWidgetColors::shaded, uiWidgetBase::shadedir, uiWidgetColors::shadedown, uiWidgetColors::shadetop, uiWidgetTrias::tot, uiWidgetBase::totvert, uiWidgetBase::tria1, uiWidgetBase::tria2, UI_TRANSP_DARK, UI_TRANSP_LIGHT, WIDGET_AA_JITTER, WIDGET_SIZE_MAX, widget_trias_draw(), widget_verts_to_quad_strip(), and widget_verts_to_quad_strip_open().
Referenced by ui_draw_but_HSV_v(), uiWidgetScrollDraw(), widget_box(), widget_but(), widget_draw_extra_mask(), widget_icon_has_anim(), widget_list_itembut(), widget_menu_back(), widget_menu_itembut(), widget_menubut(), widget_menuiconbut(), widget_menunodebut(), widget_numbut(), widget_numslider(), widget_optionbut(), widget_pulldownbut(), widget_radiobut(), widget_roundbut(), widget_swatch(), and widget_textbut().
static void widgetbase_outline (uiWidgetBase * wtb) [static]
Definition at line 653 of file interface_widgets.c.
References uiWidgetBase::totvert, WIDGET_SIZE_MAX, and widget_verts_to_quad_strip().
Referenced by widget_draw_extra_mask().
Variable Documentation
unsigned int check_tria_face[4][3] [static]
Initial value:
 {
    {3, 2, 4}, {3, 4, 5}, {1, 0, 3}, {0, 2, 3}
}
Definition at line 173 of file interface_widgets.c.
Referenced by widget_check_trias().
float check_tria_vert[6][2] [static]
Initial value:
 {
    {-0.578579, 0.253369},  {-0.392773, 0.412794},  {-0.004241, -0.328551},
    {-0.003001, 0.034320},  {1.055313, 0.864744},   {0.866408, 1.026895}
}
Definition at line 168 of file interface_widgets.c.
Referenced by widget_check_trias().
GLubyte checker_stipple_sml[32 *32/8]
Initial value:
{
    255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0,
    255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0,
    0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255,
    0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255,
    255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0,
    255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0,
    0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255,
    0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255,
}
Definition at line 177 of file interface_widgets.c.
Referenced by ui_draw_but_COLORBAND(), and widgetbase_draw().
float cornervec[WIDGET_CURVE_RESOLU][2] [static]
Initial value:
 {{0.0, 0.0}, {0.195, 0.02}, {0.383, 0.067}, {0.55, 0.169},
                                                  {0.707, 0.293}, {0.831, 0.45}, {0.924, 0.617}, {0.98, 0.805}, {1.0, 1.0}}
Definition at line 130 of file interface_widgets.c.
Referenced by round_box__edges(), and round_box_shadow_edges().
float jit[WIDGET_AA_JITTER][2] [static]
Initial value:
 {
    { 0.468813, -0.481430}, {-0.155755, -0.352820},
    { 0.219306, -0.238501}, {-0.393286, -0.110949},
    {-0.024699,  0.013908}, { 0.343805,  0.147431},
    {-0.272855,  0.269918}, { 0.095909,  0.388710}
}
Definition at line 134 of file interface_widgets.c.
Referenced by distribute_threads_init_data(), give_jitter_tab(), init_render_jit(), make_jitter_weight_tab(), RE_zbuf_accumulate_vecblur(), RAS_MeshSlot::Split(), testshadowbuf(), ui_draw_anti_roundbox(), ui_draw_anti_tria(), iTaSC::Armature::updateControlOutput(), widgetbase_draw(), zbuffer_abuf(), zbuffer_abuf_shadow(), and zbuffer_strands_abuf().
unsigned int menu_tria_face[2][3] = {{2, 0, 1}, {3, 5, 4}} [static]
Definition at line 166 of file interface_widgets.c.
Referenced by widget_menu_trias().
float menu_tria_vert[6][2] [static]
Initial value:
 {
    {-0.41, 0.16}, {0.41, 0.16}, {0, 0.82},
    {0, -0.82}, {-0.41, -0.16}, {0.41, -0.16}
}
Definition at line 161 of file interface_widgets.c.
Referenced by widget_menu_trias().
unsigned int num_tria_face[1][3] [static]
Initial value:
 {
    {0, 1, 2}
}
Definition at line 145 of file interface_widgets.c.
Referenced by widget_num_tria().
float num_tria_vert[3][2] [static]
Initial value:
 {
    {-0.352077, 0.532607}, {-0.352077, -0.549313}, {0.330000, -0.008353}
}
Definition at line 141 of file interface_widgets.c.
Referenced by widget_num_tria().
unsigned int scroll_circle_face[14][3] [static]
Initial value:
 {
    {0, 1, 2}, {2, 0, 3}, {3, 0, 15}, {3, 15, 4}, {4, 15, 14}, {4, 14, 5}, {5, 14, 13}, {5, 13, 6},
    {6, 13, 12}, {6, 12, 7}, {7, 12, 11}, {7, 11, 8}, {8, 11, 10}, {8, 10, 9}
}
Definition at line 156 of file interface_widgets.c.
Referenced by widget_scroll_circle().
float scroll_circle_vert[16][2] [static]
Initial value:
 {
    {0.382684, 0.923879}, {0.000001, 1.000000}, {-0.382683, 0.923880}, {-0.707107, 0.707107},
    {-0.923879, 0.382684}, {-1.000000, 0.000000}, {-0.923880, -0.382684}, {-0.707107, -0.707107},
    {-0.382683, -0.923880}, {0.000000, -1.000000}, {0.382684, -0.923880}, {0.707107, -0.707107},
    {0.923880, -0.382684}, {1.000000, -0.000000}, {0.923880, 0.382683}, {0.707107, 0.707107}
}
Definition at line 149 of file interface_widgets.c.
Referenced by widget_scroll_circle().
struct uiWidgetColors wcol_box [static]
Initial value:
 {
    {25, 25, 25, 255},
    {128, 128, 128, 255},
    {100, 100, 100, 255},
    {25, 25, 25, 255},
    {0, 0, 0, 255},
    {255, 255, 255, 255},
    0,
    0, 0
}
Definition at line 1484 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_list_item [static]
Initial value:
 {
    {0, 0, 0, 255},
    {0, 0, 0, 0},
    {86, 128, 194, 255},
    {0, 0, 0, 255},
    {0, 0, 0, 255},
    {0, 0, 0, 255},
    0,
    0, 0
}
Definition at line 1536 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_menu [static]
Initial value:
 {
    {0, 0, 0, 255},
    {70, 70, 70, 255},
    {70, 70, 70, 255},
    {255, 255, 255, 255},
    {255, 255, 255, 255},
    {204, 204, 204, 255},
    1,
    15, -15
}
Definition at line 1376 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_menu_back [static]
Initial value:
 {
    {0, 0, 0, 255},
    {25, 25, 25, 230},
    {45, 45, 45, 230},
    {100, 100, 100, 255},
    {160, 160, 160, 255},
    {255, 255, 255, 255},
    0,
    25, -20
}
Definition at line 1418 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_menu_item [static]
Initial value:
 {
    {0, 0, 0, 255},
    {0, 0, 0, 0},
    {86, 128, 194, 255},
    {172, 172, 172, 128},
    {255, 255, 255, 255},
    {0, 0, 0, 255},
    1,
    38, 0
}
Definition at line 1404 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_num [static]
Initial value:
 {
    {25, 25, 25, 255},
    {180, 180, 180, 255},
    {153, 153, 153, 255},
    {90, 90, 90, 255},
    {0, 0, 0, 255},
    {255, 255, 255, 255},
    1,
    -20, 0
}
Definition at line 1323 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_numslider [static]
Initial value:
 {
    {25, 25, 25, 255},
    {180, 180, 180, 255},
    {153, 153, 153, 255},
    {128, 128, 128, 255},
    {0, 0, 0, 255},
    {255, 255, 255, 255},
    1,
    -20, 0
}
Definition at line 1336 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_option [static]
Initial value:
 {
    {0, 0, 0, 255},
    {70, 70, 70, 255},
    {70, 70, 70, 255},
    {255, 255, 255, 255},
    {0, 0, 0, 255},
    {255, 255, 255, 255},
    1,
    15, -15
}
Definition at line 1362 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_progress [static]
Initial value:
 {
    {0, 0, 0, 255},
    {190, 190, 190, 255},
    {100, 100, 100, 180},
    {68, 68, 68, 255},
    {0, 0, 0, 255},
    {255, 255, 255, 255},
    0,
    0, 0
}
Definition at line 1523 of file interface_widgets.c.
Referenced by init_userdef_do_versions(), and ui_widget_color_init().
struct uiWidgetColors wcol_pulldown [static]
Initial value:
 {
    {0, 0, 0, 255},
    {63, 63, 63, 255},
    {86, 128, 194, 255},
    {255, 255, 255, 255},
    {0, 0, 0, 255},
    {0, 0, 0, 255},
    0,
    25, -20
}
Definition at line 1390 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_radio [static]
Initial value:
 {
    {0, 0, 0, 255},
    {70, 70, 70, 255},
    {86, 128, 194, 255},
    {255, 255, 255, 255},
    {255, 255, 255, 255},
    {0, 0, 0, 255},
    1,
    15, -15
}
Definition at line 1445 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_regular [static]
Initial value:
 {
    {25, 25, 25, 255},
    {153, 153, 153, 255},
    {100, 100, 100, 255},
    {25, 25, 25, 255},
    {0, 0, 0, 255},
    {255, 255, 255, 255},
    0,
    0, 0
}
Definition at line 1458 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_scroll [static]
Initial value:
 {
    {50, 50, 50, 180},
    {80, 80, 80, 180},
    {100, 100, 100, 180},
    {128, 128, 128, 255},
    {0, 0, 0, 255},
    {255, 255, 255, 255},
    1,
    5, -5
}
Definition at line 1510 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetStateColors wcol_state_colors [static]
Initial value:
 {
    {115, 190, 76, 255},
    {90, 166, 51, 255},
    {240, 235, 100, 255},
    {215, 211, 75, 255},
    {180, 0, 255, 255},
    {153, 0, 230, 255},
    0.5f, 0.0f
}
Definition at line 1301 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_text [static]
Initial value:
 {
    {25, 25, 25, 255},
    {153, 153, 153, 255},
    {153, 153, 153, 255},
    {90, 90, 90, 255},
    {0, 0, 0, 255},
    {255, 255, 255, 255},
    1,
    0, 25
}
Definition at line 1349 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_tmp [static]
Initial value:
 {
    {0, 0, 0, 255},
    {128, 128, 128, 255},
    {100, 100, 100, 255},
    {25, 25, 25, 255},
    {0, 0, 0, 255},
    {255, 255, 255, 255},
    0,
    0, 0
}
Definition at line 1550 of file interface_widgets.c.
struct uiWidgetColors wcol_toggle [static]
Initial value:
 {
    {25, 25, 25, 255},
    {153, 153, 153, 255},
    {100, 100, 100, 255},
    {25, 25, 25, 255},
    {0, 0, 0, 255},
    {255, 255, 255, 255},
    0,
    0, 0
}
Definition at line 1497 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_tool [static]
Initial value:
 {
    {25, 25, 25, 255},
    {153, 153, 153, 255},
    {100, 100, 100, 255},
    {25, 25, 25, 255},
    {0, 0, 0, 255},
    {255, 255, 255, 255},
    1,
    15, -15
}
Definition at line 1471 of file interface_widgets.c.
Referenced by ui_widget_color_init().
struct uiWidgetColors wcol_tooltip [static]
Initial value:
 {
    {0, 0, 0, 255},
    {25, 25, 25, 230},
    {45, 45, 45, 230},
    {100, 100, 100, 255},
    {160, 160, 160, 255},
    {255, 255, 255, 255},
    0,
    25, -20
}
Definition at line 1432 of file interface_widgets.c.
Referenced by ui_widget_color_init().