Blender: CEmptyValue Class Reference
CEmptyValue Class Reference
#include <EmptyValue.h>
Public Member Functions
CEmptyValue ()
virtual ~CEmptyValue ()
virtual const STR_String & GetText ()
virtual double GetNumber ()
CListValue * GetPolySoup ()
virtual double * GetVector3 (bool bGetTransformedVec=false)
bool IsInside (CValue *testpoint, bool bBorderInclude=true)
CValue * Calc (VALUE_OPERATOR op, CValue *val)
CValue * CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue *val)
virtual CValue * GetReplica ()
Detailed Description
Definition at line 26 of file EmptyValue.h.
Constructor & Destructor Documentation
CEmptyValue::CEmptyValue ()
Definition at line 31 of file EmptyValue.cpp.
References CValue::SetModified().
Referenced by GetReplica().
CEmptyValue::~CEmptyValue () [virtual]
Definition at line 42 of file EmptyValue.cpp.
Member Function Documentation
CValue * CEmptyValue::Calc (VALUE_OPERATOR op, CValue * val) [virtual]
Implements CValue.
Definition at line 53 of file EmptyValue.cpp.
References CValue::CalcFinal(), and VALUE_EMPTY_TYPE.
CValue * CEmptyValue::CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue * val) [virtual]
Implements CValue.
Definition at line 66 of file EmptyValue.cpp.
References CValue::AddRef().
double CEmptyValue::GetNumber () [virtual]
Implements CValue.
Definition at line 78 of file EmptyValue.cpp.
CListValue * CEmptyValue::GetPolySoup ()
Definition at line 85 of file EmptyValue.cpp.
CValue * CEmptyValue::GetReplica (void) [virtual]
Implements CValue.
Definition at line 120 of file EmptyValue.cpp.
References CEmptyValue(), and CValue::ProcessReplica().
const STR_String & CEmptyValue::GetText () [virtual]
Implements CValue.
Definition at line 113 of file EmptyValue.cpp.
References emptyString.
double * CEmptyValue::GetVector3 (bool bGetTransformedVec = false) [virtual]
Reimplemented from CValue.
Definition at line 102 of file EmptyValue.cpp.
References assertd, and CValue::ZeroVector().
bool CEmptyValue::IsInside (CValue * testpoint, bool bBorderInclude = true)
Definition at line 94 of file EmptyValue.cpp.
The documentation for this class was generated from the following files:
EmptyValue.h
EmptyValue.cpp