Blender: wmPaintCursor Struct Reference
wmPaintCursor Struct Reference
#include <wm.h>
Public Attributes
struct wmPaintCursor * next
struct wmPaintCursor * prev
void * customdata
int(* poll)(struct bContext *C)
void(* draw)(bContext *C, int, int, void *customdata)
Detailed Description
Definition at line 37 of file wm.h.
Member Data Documentation
void* wmPaintCursor::customdata
Definition at line 40 of file wm.h.
Referenced by WM_paint_cursor_activate(), and wm_paintcursor_draw().
void(* wmPaintCursor::draw)(bContext *C, int, int, void *customdata)
Definition at line 43 of file wm.h.
Referenced by WM_paint_cursor_activate(), and wm_paintcursor_draw().
struct wmPaintCursor* wmPaintCursor::next
Definition at line 38 of file wm.h.
Referenced by WM_paint_cursor_end(), wm_paintcursor_draw(), and wm_paintcursor_tag().
int(* wmPaintCursor::poll)(struct bContext *C)
Definition at line 42 of file wm.h.
Referenced by WM_paint_cursor_activate(), wm_paintcursor_draw(), and wm_paintcursor_tag().
struct wmPaintCursor * wmPaintCursor::prev
Definition at line 38 of file wm.h.
The documentation for this struct was generated from the following file:
wm.h