Blender: node_composite_invert.c File Reference
node_composite_invert.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_invert (bNode *node, float *out, float *in)
static void do_invert_fac (bNode *node, float *out, float *in, float *fac)
static void node_composit_exec_invert (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_invert (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_invert (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_invert_in []
static bNodeSocketTemplate cmp_node_invert_out []
Detailed Description
Definition in file node_composite_invert.c.
Function Documentation
static void do_invert (bNode * node, float * out, float * in) [static]
Definition at line 46 of file node_composite_invert.c.
References CMP_CHAN_A, CMP_CHAN_RGB, copy_v3_v3(), and bNode::custom1.
Referenced by do_invert_fac(), and node_composit_exec_invert().
static void do_invert_fac (bNode * node, float * out, float * in, float * fac) [static]
Definition at line 63 of file node_composite_invert.c.
References CMP_CHAN_A, CMP_CHAN_RGB, copy_v4_v4(), bNode::custom1, and do_invert().
Referenced by node_composit_exec_invert().
static void node_composit_exec_invert (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 83 of file node_composite_invert.c.
References alloc_compbuf(), CB_RGBA, CB_VAL, composit1_pixel_processor(), composit2_pixel_processor(), bNode::custom1, bNodeStack::data, data, do_invert(), do_invert_fac(), NULL, pass_on_compbuf(), bNodeStack::vec, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_invert().
static void node_composit_init_invert (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 118 of file node_composite_invert.c.
References CMP_CHAN_RGB, and bNode::custom1.
Referenced by register_node_type_cmp_invert().
void register_node_type_cmp_invert (bNodeTreeType * ttype)
Definition at line 124 of file node_composite_invert.c.
References CMP_NODE_INVERT, NODE_CLASS_OP_COLOR, node_composit_exec_invert(), node_composit_init_invert(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_invert_in[] [static]
Initial value:
 {
    { SOCK_FLOAT, 1, "Fac", 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_FACTOR},
    { SOCK_RGBA, 1, "Color", 1.0f, 1.0f, 1.0f, 1.0f},
    { -1, 0, "" }
}
Definition at line 35 of file node_composite_invert.c.
bNodeSocketTemplate cmp_node_invert_out[] [static]
Initial value:
 {
    { SOCK_RGBA, 0, "Color"},
    { -1, 0, "" }
}
Definition at line 41 of file node_composite_invert.c.