Blender: bmp.c File Reference
bmp.c File Reference
IMage Buffer
#include "BLI_blenlib.h"
#include "imbuf.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_allocimbuf.h"
#include "IMB_filetype.h"
Classes
struct BMPINFOHEADER
struct BMPHEADER
Defines
#define BMP_FILEHEADER_SIZE 14
Typedefs
typedef struct BMPINFOHEADER BMPINFOHEADER
typedef struct BMPHEADER BMPHEADER
Functions
static int checkbmp (unsigned char *mem)
int imb_is_a_bmp (unsigned char *buf)
struct ImBuf * imb_bmp_decode (unsigned char *mem, size_t size, int flags)
static int putIntLSB (unsigned int ui, FILE *ofile)
static int putShortLSB (unsigned short us, FILE *ofile)
int imb_savebmp (struct ImBuf *ibuf, const char *name, int flags)
Detailed Description
Definition in file bmp.c.
Define Documentation
#define BMP_FILEHEADER_SIZE 14
Definition at line 69 of file bmp.c.
Referenced by checkbmp(), imb_bmp_decode(), and imb_savebmp().
Typedef Documentation
typedef struct BMPHEADER BMPHEADER
typedef struct BMPINFOHEADER BMPINFOHEADER
Function Documentation
static int checkbmp (unsigned char * mem) [static]
Definition at line 71 of file bmp.c.
References BMPINFOHEADER::biBitCount, BMPINFOHEADER::biClrUsed, BMPINFOHEADER::biCompression, BMPINFOHEADER::biSize, BMP_FILEHEADER_SIZE, LITTLE_LONG, and LITTLE_SHORT.
Referenced by imb_bmp_decode(), and imb_is_a_bmp().
struct ImBuf* imb_bmp_decode (unsigned char * mem, size_t size, int flags) [read]
Definition at line 108 of file bmp.c.
References BMPINFOHEADER::biBitCount, BMPINFOHEADER::biHeight, BMPINFOHEADER::biSize, BMPINFOHEADER::biWidth, BMP, BMP_FILEHEADER_SIZE, checkbmp(), ImBuf::depth, ImBuf::ftype, i, IB_PROFILE_SRGB, IB_rect, IB_test, if(), IMB_allocImBuf(), LITTLE_LONG, LITTLE_SHORT, NULL, ImBuf::profile, ImBuf::rect, ImBuf::x, and ImBuf::y.
int imb_is_a_bmp (unsigned char * buf)
Definition at line 103 of file bmp.c.
References checkbmp().
int imb_savebmp (struct ImBuf * ibuf, const char * name, int flags)
Definition at line 210 of file bmp.c.
References BLI_fopen(), BMP_FILEHEADER_SIZE, data, putIntLSB(), putShortLSB(), ImBuf::rect, ImBuf::x, and ImBuf::y.
static int putIntLSB (unsigned int ui, FILE * ofile) [static]
Definition at line 195 of file bmp.c.
Referenced by imb_savebmp().
static int putShortLSB (unsigned short us, FILE * ofile) [static]
Definition at line 203 of file bmp.c.
Referenced by imb_savebmp().