Blender: MeanValueMeshCoords Class Reference
MeanValueMeshCoords Class Reference
compute mvmcs
#include <mvmcoords.h>
Public Member Functions
MeanValueMeshCoords ()
~MeanValueMeshCoords ()
void clear ()
void calculateMVMCs (std::vector< ntlVec3Gfx > &reference_vertices, std::vector< ntlTriangle > &tris, std::vector< ntlVec3Gfx > &points, gfxReal numweights)
void transfer (std::vector< ntlVec3Gfx > &vertices, std::vector< ntlVec3Gfx > &displacements)
Protected Member Functions
void computeWeights (std::vector< ntlVec3Gfx > &reference_vertices, std::vector< ntlTriangle > &tris, mvmTransferPoint &tds, gfxReal numweights)
Protected Attributes
std::vector< mvmTransferPoint > mVertices
int mNumVerts
Detailed Description
compute mvmcs
Definition at line 65 of file mvmcoords.h.
Constructor & Destructor Documentation
MeanValueMeshCoords::MeanValueMeshCoords () [inline]
Definition at line 69 of file mvmcoords.h.
MeanValueMeshCoords::~MeanValueMeshCoords () [inline]
Definition at line 70 of file mvmcoords.h.
References clear().
Member Function Documentation
void MeanValueMeshCoords::calculateMVMCs (std::vector< ntlVec3Gfx > & reference_vertices, std::vector< ntlTriangle > & tris, std::vector< ntlVec3Gfx > & points, gfxReal numweights)
Definition at line 27 of file mvmcoords.cpp.
References clear(), computeWeights(), debMsgStd, DM_MSG, i, mvmTransferPoint::lastpos, mNumVerts, mVertices, mvmFloat, and mvmTransferPoint::weights.
Referenced by ControlParticles::initFromMVCMesh(), and ControlParticles::initFromObject().
void MeanValueMeshCoords::clear ()
Definition at line 21 of file mvmcoords.cpp.
References mNumVerts, and mVertices.
Referenced by calculateMVMCs(), and ~MeanValueMeshCoords().
void MeanValueMeshCoords::computeWeights (std::vector< ntlVec3Gfx > & reference_vertices, std::vector< ntlTriangle > & tris, mvmTransferPoint & tds, gfxReal numweights) [protected]
Definition at line 53 of file mvmcoords.cpp.
References KDL::asin(), errMsg, i, indices, mvmTransferPoint::lastpos, M_PI, mvmFloat, norm(), normalize(), sin(), KDL::sinh(), sort(), sqrt(), vec2D(), and mvmTransferPoint::weights.
Referenced by calculateMVMCs().
void MeanValueMeshCoords::transfer (std::vector< ntlVec3Gfx > & vertices, std::vector< ntlVec3Gfx > & displacements)
Definition at line 171 of file mvmcoords.cpp.
References errMsg, mNumVerts, mVertices, and mvmTransferPoint::weights.
Referenced by ControlParticles::initFromObject().
Member Data Documentation
int MeanValueMeshCoords::mNumVerts [protected]
Definition at line 87 of file mvmcoords.h.
Referenced by calculateMVMCs(), clear(), and transfer().
std::vector<mvmTransferPoint> MeanValueMeshCoords::mVertices [protected]
Definition at line 86 of file mvmcoords.h.
Referenced by calculateMVMCs(), clear(), and transfer().
The documentation for this class was generated from the following files:
mvmcoords.h
mvmcoords.cpp