Blender: MOD_bevel.c File Reference
MOD_bevel.c File Reference
modifiers
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "BLI_string.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_modifier.h"
#include "BKE_tessmesh.h"
#include "BKE_mesh.h"
#include "BKE_bmesh.h"
#include "DNA_object_types.h"
#include "MEM_guardedalloc.h"
Defines
#define EDGE_MARK 1
Functions
static void initData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static CustomDataMask requiredDataMask (Object *UNUSED(ob), ModifierData *md)
static DerivedMesh * applyModifier (ModifierData *md, Object *UNUSED(ob), DerivedMesh *derivedData, int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
static DerivedMesh * applyModifierEM (ModifierData *md, Object *ob, struct BMEditMesh *UNUSED(editData), DerivedMesh *derivedData)
Variables
ModifierTypeInfo modifierType_Bevel
Detailed Description
Definition in file MOD_bevel.c.
Define Documentation
#define EDGE_MARK 1
Definition at line 91 of file MOD_bevel.c.
Function Documentation
static DerivedMesh* applyModifier (ModifierData * md, Object * UNUSEDob, DerivedMesh * derivedData, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 162 of file MOD_bevel.c.
References BevelModifierData::bevel_angle, BLI_assert, BME_bevel(), BMEdit_Free(), CDDM_calc_normals(), CDDM_from_BMEditMesh(), defgroup_name_index(), BevelModifierData::defgrp_name, DEG2RADF, DM_to_editbmesh(), BevelModifierData::e_flags, FALSE, BevelModifierData::flags, BevelModifierData::lim_flags, BMEditMesh::looptris, MEM_freeN(), NULL, options, BevelModifierData::res, TRUE, BevelModifierData::val_flags, and BevelModifierData::value.
Referenced by applyModifierEM().
static DerivedMesh* applyModifierEM (ModifierData * md, Object * ob, struct BMEditMesh * UNUSEDeditData, DerivedMesh * derivedData) [static]
Definition at line 201 of file MOD_bevel.c.
References applyModifier().
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 65 of file MOD_bevel.c.
References BevelModifierData::bevel_angle, BLI_strncpy(), BevelModifierData::defgrp_name, BevelModifierData::e_flags, BevelModifierData::flags, BevelModifierData::lim_flags, BevelModifierData::res, BevelModifierData::val_flags, and BevelModifierData::value.
static void initData (ModifierData * md) [static]
Definition at line 51 of file MOD_bevel.c.
References BevelModifierData::bevel_angle, BevelModifierData::defgrp_name, BevelModifierData::e_flags, BevelModifierData::flags, BevelModifierData::lim_flags, BevelModifierData::res, BevelModifierData::val_flags, and BevelModifierData::value.
static CustomDataMask requiredDataMask (Object * UNUSEDob, ModifierData * md) [static]
Definition at line 80 of file MOD_bevel.c.
References CD_MASK_MDEFORMVERT, and BevelModifierData::defgrp_name.
Variable Documentation
ModifierTypeInfo modifierType_Bevel
Initial value:
 {
                  "Bevel",
            "BevelModifierData",
            sizeof(BevelModifierData),
                  eModifierTypeType_Constructive,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_SupportsEditmode
                            | eModifierTypeFlag_EnableInEditmode,
              copyData,
           NULL,
        NULL,
         NULL,
      NULL,
         applyModifier,
       applyModifierEM,
              initData,
      requiredDataMask,
              NULL,
            NULL,
        NULL,
         NULL,
        NULL,
     NULL,
         NULL,
        NULL,
}
Definition at line 209 of file MOD_bevel.c.