Blender: bmo_bevel.c File Reference
bmo_bevel.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "BLI_array.h"
#include "BLI_math.h"
#include "BLI_smallhash.h"
#include "BKE_customdata.h"
#include "bmesh.h"
#include "intern/bmesh_operators_private.h"
Classes
struct LoopTag
struct EdgeTag
Defines
#define BEVEL_FLAG 1
#define BEVEL_DEL 2
#define FACE_NEW 4
#define EDGE_OLD 8
#define FACE_OLD 16
#define VERT_OLD 32
#define FACE_SPAN 64
#define FACE_HOLE 128
#define ETAG_SET(e, v, nv)
#define ETAG_GET(e, v)
Typedefs
typedef struct LoopTag LoopTag
typedef struct EdgeTag EdgeTag
Functions
static void calc_corner_co (BMLoop *l, const float fac, float r_co[3], const short do_dist, const short do_even)
void bmo_bevel_exec (BMesh *bm, BMOperator *op)
Detailed Description
Definition in file bmo_bevel.c.
Define Documentation
#define BEVEL_DEL 2
Definition at line 40 of file bmo_bevel.c.
Referenced by bmo_bevel_exec().
#define BEVEL_FLAG 1
Definition at line 39 of file bmo_bevel.c.
Referenced by bmo_bevel_exec().
#define EDGE_OLD 8
Definition at line 42 of file bmo_bevel.c.
Referenced by bmo_bevel_exec().
#define ETAG_GET (e, v)
Value:
(\
    (v) == (e)->v1 ?                                                          \
        (etags[BM_elem_index_get((e))].newv1) :                               \
        (etags[BM_elem_index_get((e))].newv2)                                 \
    )
Definition at line 175 of file bmo_bevel.c.
Referenced by bmo_bevel_exec().
#define ETAG_SET (e, v, nv)
Value:
(\
    (v) == (e)->v1 ?                                                          \
        (etags[BM_elem_index_get((e))].newv1 = (nv)) :                        \
        (etags[BM_elem_index_get((e))].newv2 = (nv))                          \
    )
Definition at line 169 of file bmo_bevel.c.
Referenced by bmo_bevel_exec().
#define FACE_HOLE 128
Definition at line 46 of file bmo_bevel.c.
Referenced by bmo_bevel_exec().
#define FACE_NEW 4
Definition at line 41 of file bmo_bevel.c.
Referenced by bmo_bevel_exec().
#define FACE_OLD 16
Definition at line 43 of file bmo_bevel.c.
Referenced by bmo_bevel_exec().
#define FACE_SPAN 64
Definition at line 45 of file bmo_bevel.c.
Referenced by bmo_bevel_exec().
#define VERT_OLD 32
Definition at line 44 of file bmo_bevel.c.
Referenced by bmo_bevel_exec().
Typedef Documentation
typedef struct EdgeTag EdgeTag
typedef struct LoopTag LoopTag
Function Documentation
void bmo_bevel_exec (BMesh * bm, BMOperator * op)
Definition at line 181 of file bmo_bevel.c.
References add_v3_v3(), angle_v3v3v3(), BEVEL_DEL, BEVEL_FLAG, BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growone, BLI_smallhash_haskey(), BLI_smallhash_init(), BLI_smallhash_insert(), BLI_smallhash_lookup(), BLI_smallhash_release(), BLI_smallhash_remove(), BM_EDGE, BM_edge_create(), BM_edge_exists(), BM_edge_face_count(), BM_edge_other_vert(), BM_EDGES_OF_MESH, BM_EDGES_OF_VERT, BM_elem_attrs_copy(), BM_elem_index_get, BM_elem_index_set, BM_FACE, BM_face_create(), BM_face_create_ngon(), BM_face_create_quad_tri(), BM_face_exists(), BM_FACE_FIRST_LOOP, BM_face_kill(), BM_faces_join(), BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_loop_interp_from_face(), BM_loop_interp_multires(), BM_LOOPS_OF_EDGE, BM_LOOPS_OF_FACE, BM_LOOPS_OF_VERT, BM_vert_create(), BM_vert_in_edge(), BM_VERTS_OF_MESH, BMO_elem_flag_disable, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_op_callf(), BMO_slot_bool_get(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), calc_corner_co(), CD_MDISPS, CD_PROP_FLT, co, BMVert::co, CustomData_bmesh_get_n(), CustomData_has_layer(), BMHeader::data, DEL_EDGES, DEL_FACES, DEL_VERTS, BMLoop::e, BMesh::edata, EDGE_OLD, BMesh::elem_index_dirty, err, ETAG_GET, ETAG_SET, BMLoop::f, FACE_HOLE, FACE_NEW, FACE_OLD, FACE_SPAN, FALSE, hash, BMEdge::head, i, BMEdge::l, BMesh::ldata, mul_v3_fl(), LoopTag::newv, BMLoop::next, normalize_v3(), NULL, BMLoop::prev, BMLoop::radial_next, sub_v3_v3v3(), TRUE, BMLoop::v, BMEdge::v1, BMEdge::v2, and VERT_OLD.
static void calc_corner_co (BMLoop * l, const float fac, float r_co[3], const short do_dist, const short do_even) [static]
Definition at line 56 of file bmo_bevel.c.
References add_v3_v3v3(), angle(), angle_normalized_v3v3(), BM_edge_other_vert(), BM_ITER_ELEM, BM_LOOPS_OF_VERT, BMVert::co, copy_v3_v3(), cross_v3_v3v3(), dot_v3v3(), BMLoop::e, BMLoop::f, is_zero_v3(), BMFace::len, minf(), mul_v3_fl(), negate_v3(), BMLoop::next, BMFace::no, normalize_v3(), BMLoop::prev, shell_angle_to_dist(), sub_v3_v3v3(), UNLIKELY, and BMLoop::v.
Referenced by bmo_bevel_exec().