Blender: MT_Scalar.h File Reference
MT_Scalar.h File Reference
moto
#include <math.h>
#include <float.h>
#include "MT_random.h"
#include "NM_Scalar.h"
Typedefs
typedef double MT_Scalar
Functions
const MT_Scalar MT_DEGS_PER_RAD (57.29577951308232286465)
const MT_Scalar MT_RADS_PER_DEG (0.01745329251994329547)
const MT_Scalar MT_PI (3.14159265358979323846)
const MT_Scalar MT_2_PI (6.28318530717958623200)
const MT_Scalar MT_EPSILON (1.0e-10)
const MT_Scalar MT_EPSILON2 (1.0e-20)
const MT_Scalar MT_INFINITY (1.0e50)
int MT_sign (MT_Scalar x)
MT_Scalar MT_abs (MT_Scalar x)
bool MT_fuzzyZero (MT_Scalar x)
bool MT_fuzzyZero2 (MT_Scalar x)
MT_Scalar MT_radians (MT_Scalar x)
MT_Scalar MT_degrees (MT_Scalar x)
MT_Scalar MT_random ()
MT_Scalar MT_clamp (const MT_Scalar x, const MT_Scalar min, const MT_Scalar max)
Detailed Description
Definition in file MT_Scalar.h.
Typedef Documentation
typedef double MT_Scalar
Definition at line 56 of file MT_Scalar.h.
Function Documentation
const MT_Scalar MT_2_PI (6. 28318530717958623200)
Referenced by BL_ConvertActuators(), compatible_eulFast(), MT_Vector3::random(), and MT_Quaternion::random().
MT_Scalar MT_abs (MT_Scalar x) [inline]
Definition at line 71 of file MT_Scalar.h.
References fabs().
Referenced by MT_Vector3::absolute(), MT_Vector4::absolute(), MT_Vector2::absolute(), MT_Matrix3x3::absolute(), MT_Matrix4x4::absolute(), KX_GameObject::AlignAxisToVect(), IK_QJacobian::AngleUpdateNorm(), MT_fuzzyZero(), MT_fuzzyZero2(), KX_RayCast::RayTest(), and SphericalRangeParameters().
MT_Scalar MT_clamp (const MT_Scalar x, const MT_Scalar min, const MT_Scalar max) [inline]
Definition at line 88 of file MT_Scalar.h.
References max, and min.
Referenced by MT_Quaternion::angle(), IK_QSwingSegment::SetLimit(), IK_QElbowSegment::SetLimit(), IK_QSphericalSegment::SetLimit(), and IK_QRevoluteSegment::SetLimit().
MT_Scalar MT_degrees (MT_Scalar x) [inline]
Definition at line 80 of file MT_Scalar.h.
References MT_DEGS_PER_RAD().
const MT_Scalar MT_DEGS_PER_RAD (57. 29577951308232286465)
Referenced by MT_degrees().
const MT_Scalar MT_EPSILON (1.0e- 10)
Referenced by KX_GameObject::AlignAxisToVect(), EulerAngleFromMatrix(), MT_fuzzyZero(), KX_RayCast::RayTest(), SphericalRangeParameters(), KX_ConstraintActuator::Update(), and KX_ObjectActuator::Update().
const MT_Scalar MT_EPSILON2 (1.0e- 20)
Referenced by MT_fuzzyZero2().
bool MT_fuzzyZero (MT_Scalar x) [inline]
Definition at line 73 of file MT_Scalar.h.
References MT_abs(), and MT_EPSILON().
Referenced by KX_GameObject::AlignAxisToVect(), MT_Vector3::angle(), MT_Vector2::angle(), bl_ConvertBlenderObject_Single(), BOP_getCircleCenter(), EllipseClamp(), BSP_CSGMesh::FacePlane(), MT_Vector3::fuzzyZero(), IK_QCenterOfMassTask::IK_QCenterOfMassTask(), KX_ConstraintActuator::KX_ConstraintActuator(), MatrixToAxisAngle(), MT_fuzzyEqual(), normalize(), KX_Camera::NormalizeClipPlanes(), operator/(), MT_Vector4::operator/=(), MT_Vector3::operator/=(), MT_Vector2::operator/=(), LOD_Quadric::Optimize(), MT_Vector3::safe_normalized(), BSP_CSGMesh::SC_Face(), MT_Quaternion::setRotation(), IK_QJacobianSolver::Setup(), SCA_ExpressionController::Trigger(), KX_ConstraintActuator::Update(), IK_QSwingSegment::UpdateAngle(), IK_QSphericalSegment::UpdateAngle(), and KX_ObjectActuator::UpdateFuzzyFlags().
bool MT_fuzzyZero2 (MT_Scalar x) [inline]
Definition at line 74 of file MT_Scalar.h.
References MT_abs(), and MT_EPSILON2().
Referenced by MT_Vector2::fuzzyZero(), MT_Vector4::fuzzyZero(), MT_Matrix3x3::inverse(), MT_Matrix3x3::setRotation(), and KX_ConstraintActuator::Update().
const MT_Scalar MT_INFINITY (1. 0e50)
Referenced by BOP_BBox::BOP_BBox(), BSP_PlyLoader::NewMeshFromFile(), and NewVertsFromFile().
const MT_Scalar MT_PI (3. 14159265358979323846)
Referenced by KX_Dome::CalculateCameraOrientation(), compatible_eulFast(), KX_Dome::CreateMeshDome250(), KX_Dome::FlattenPanorama(), MT_Matrix3x3::getEuler(), NewTestMesh(), safe_acos(), IK_QSwingSegment::SetLimit(), IK_QElbowSegment::SetLimit(), IK_QSphericalSegment::SetLimit(), and IK_QRevoluteSegment::SetLimit().
MT_Scalar MT_radians (MT_Scalar x) [inline]
Definition at line 76 of file MT_Scalar.h.
References MT_RADS_PER_DEG().
Referenced by BL_ConvertSensors(), and KX_RadarSensor::SynchronizeTransform().
const MT_Scalar MT_RADS_PER_DEG (0. 01745329251994329547)
Referenced by BL_ConvertActuators(), and MT_radians().
MT_Scalar MT_random () [inline]
Definition at line 84 of file MT_Scalar.h.
References MT_rand(), and MT_RAND_MAX.
Referenced by MT_Vector3::random(), and MT_Quaternion::random().
int MT_sign (MT_Scalar x) [inline]
Definition at line 67 of file MT_Scalar.h.