Blender: GlutDrawManager Class Reference
GlutDrawManager Class Reference
#include <GlutDrawer.h>
Public Member Functions
void InstallDrawer (GlutDrawer *)
void ReleaseDrawer ()
~GlutDrawManager ()
void InstallDrawer (GlutDrawer *)
void ReleaseDrawer ()
~GlutDrawManager ()
Static Public Member Functions
static GlutDrawManager * Instance ()
static void Draw ()
static GlutDrawManager * Instance ()
static void Draw ()
Detailed Description
Definition at line 53 of file decimation/test/decimate_glut_test/intern/common/GlutDrawer.h.
Constructor & Destructor Documentation
GlutDrawManager::~GlutDrawManager ()
Definition at line 77 of file decimation/test/decimate_glut_test/intern/common/GlutDrawer.cpp.
GlutDrawManager::~GlutDrawManager ()
Member Function Documentation
void GlutDrawManager::Draw (void) [static]
Definition at line 49 of file decimation/test/decimate_glut_test/intern/common/GlutDrawer.cpp.
References GlutDrawer::Draw(), Instance(), and NULL.
Referenced by main().
static void GlutDrawManager::Draw () [static]
void GlutDrawManager::InstallDrawer (GlutDrawer *)
void GlutDrawManager::InstallDrawer (GlutDrawer * drawer)
Definition at line 60 of file decimation/test/decimate_glut_test/intern/common/GlutDrawer.cpp.
References MT_assert, and NULL.
Referenced by main().
static GlutDrawManager* GlutDrawManager::Instance () [static]
GlutDrawManager * GlutDrawManager::Instance () [static]
Definition at line 35 of file decimation/test/decimate_glut_test/intern/common/GlutDrawer.cpp.
References NULL.
Referenced by Draw(), and main().
void GlutDrawManager::ReleaseDrawer ()
void GlutDrawManager::ReleaseDrawer ()
Definition at line 70 of file decimation/test/decimate_glut_test/intern/common/GlutDrawer.cpp.
References NULL.
The documentation for this class was generated from the following files:
decimation/test/decimate_glut_test/intern/common/GlutDrawer.h
iksolver/test/ik_glut_test/common/GlutDrawer.h
decimation/test/decimate_glut_test/intern/common/GlutDrawer.cpp
iksolver/test/ik_glut_test/common/GlutDrawer.cpp