Blender: rna_main.c File Reference
rna_main.c File Reference
RNA
#include <stdlib.h>
#include <string.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "BKE_utildefines.h"
Classes
struct MainCollectionDef
Typedefs
typedef void(CollectionDefFunc)(struct BlenderRNA *brna, struct PropertyRNA *cprop)
typedef struct MainCollectionDef MainCollectionDef
Functions
void RNA_def_main (BlenderRNA *brna)
Detailed Description
Definition in file rna_main.c.
Typedef Documentation
typedef void(CollectionDefFunc)(struct BlenderRNA *brna, struct PropertyRNA *cprop)
Definition at line 271 of file rna_main.c.
typedef struct MainCollectionDef MainCollectionDef
Function Documentation
void RNA_def_main (BlenderRNA * brna)
Definition at line 282 of file rna_main.c.
References FILE_MAX, MainCollectionDef::func, i, MainCollectionDef::name, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_FILEPATH, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_api_main(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_gpencil(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_libraries(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_movieclips(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_screens(), RNA_def_main_sounds(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_window_managers(), RNA_def_main_worlds(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_pointer_funcs(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and RNA_define_verify_sdna().