Blender: rna_context.c File Reference
rna_context.c File Reference
RNA
#include <stdlib.h>
#include "DNA_ID.h"
#include "DNA_userdef_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "BKE_context.h"
#include "rna_internal.h"
Functions
void RNA_def_context (BlenderRNA *brna)
Detailed Description
Definition in file rna_context.c.
Function Documentation
void RNA_def_context (BlenderRNA * brna)
Definition at line 132 of file rna_context.c.
References CTX_MODE_EDIT_ARMATURE, CTX_MODE_EDIT_CURVE, CTX_MODE_EDIT_LATTICE, CTX_MODE_EDIT_MESH, CTX_MODE_EDIT_METABALL, CTX_MODE_EDIT_SURFACE, CTX_MODE_EDIT_TEXT, CTX_MODE_OBJECT, CTX_MODE_PAINT_TEXTURE, CTX_MODE_PAINT_VERTEX, CTX_MODE_PAINT_WEIGHT, CTX_MODE_PARTICLE, CTX_MODE_POSE, CTX_MODE_SCULPT, NULL, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().