Blender: thread Class Reference
thread Class Reference
#include <util_thread.h>
Public Member Functions
thread (boost::function< void(void)> run_cb_)
~thread ()
bool join ()
Static Public Member Functions
static void * run (void *arg)
Protected Attributes
boost::function< void(void)> run_cb
pthread_t pthread_id
bool joined
Detailed Description
Definition at line 39 of file util_thread.h.
Constructor & Destructor Documentation
thread::thread (boost::function< void(void)> run_cb_) [inline]
Definition at line 41 of file util_thread.h.
References joined, NULL, pthread_id, run(), and run_cb.
thread::~thread () [inline]
Definition at line 49 of file util_thread.h.
References join(), and joined.
Member Function Documentation
bool thread::join () [inline]
Definition at line 61 of file util_thread.h.
References NULL, and pthread_id.
Referenced by Session::wait(), CPUDevice::~CPUDevice(), and ~thread().
static void* thread::run (void * arg) [inline, static]
Definition at line 55 of file util_thread.h.
References NULL.
Referenced by thread().
Member Data Documentation
bool thread::joined [protected]
Definition at line 69 of file util_thread.h.
Referenced by thread(), and ~thread().
pthread_t thread::pthread_id [protected]
Definition at line 68 of file util_thread.h.
Referenced by join(), and thread().
boost::function<void(void)> thread::run_cb [protected]
Definition at line 67 of file util_thread.h.
Referenced by thread().
The documentation for this class was generated from the following file:
util_thread.h