Blender: mikktspace.h File Reference
mikktspace.h File Reference
mikktspace
Classes
struct SMikkTSpaceInterface
struct SMikkTSpaceContext
Typedefs
typedef int tbool
typedef struct SMikkTSpaceContext SMikkTSpaceContext
Functions
tbool genTangSpaceDefault (const SMikkTSpaceContext *pContext)
tbool genTangSpace (const SMikkTSpaceContext *pContext, const float fAngularThreshold)
Detailed Description
Definition in file mikktspace.h.
Typedef Documentation
typedef struct SMikkTSpaceContext SMikkTSpaceContext
Definition at line 63 of file mikktspace.h.
typedef int tbool
Copyright (C) 2011 by Morten S. Mikkelsen
This software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.
Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:
1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required. 2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software. 3. This notice may not be removed or altered from any source distribution.
Definition at line 62 of file mikktspace.h.
Function Documentation
tbool genTangSpace (const SMikkTSpaceContext * pContext, const float fAngularThreshold)
Definition at line 234 of file mikktspace.c.
References STSpace::bOrient, Build4RuleGroups(), cos(), DegenEpilogue(), DegenPrologue(), STSpace::fMagS, STSpace::fMagT, GenerateInitialVerticesIndexList(), GenerateSharedVerticesIndexList(), GenerateTSpaces(), GetPosition(), i, STriInfo::iFlag, InitTriInfo(), SMikkTSpaceInterface::m_getNormal, SMikkTSpaceInterface::m_getNumFaces, SMikkTSpaceInterface::m_getNumVerticesOfFace, SMikkTSpaceInterface::m_getPosition, SMikkTSpaceInterface::m_getTexCoord, M_PI, SMikkTSpaceContext::m_pInterface, SMikkTSpaceInterface::m_setTSpace, SMikkTSpaceInterface::m_setTSpaceBasic, MARK_DEGENERATE, NULL, TFALSE, TTRUE, veq(), STSpace::vOs, STSpace::vOt, SVec3::x, SVec3::y, and SVec3::z.
Referenced by genTangSpaceDefault().
tbool genTangSpaceDefault (const SMikkTSpaceContext * pContext)
Definition at line 229 of file mikktspace.c.
References genTangSpace().
Referenced by calc_vertexnormals(), and DM_add_tangent_layer().