Blender: idprop.c File Reference
idprop.c File Reference
blenkernel
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include "BKE_idprop.h"
#include "BKE_library.h"
#include "BLI_blenlib.h"
#include "MEM_guardedalloc.h"
Classes
struct IDPIter
Defines
#define GETPROP(prop, i) (((IDProperty*)(prop)->data.pointer)+(i))
#define SWITCH_LONGINT(a)
Typedefs
typedef struct IDPIter IDPIter
Functions
IDProperty * IDP_NewIDPArray (const char *name)
IDProperty * IDP_CopyIDPArray (IDProperty *array)
void IDP_FreeIDPArray (IDProperty *prop)
void IDP_SetIndexArray (IDProperty *prop, int index, IDProperty *item)
IDProperty * IDP_GetIndexArray (IDProperty *prop, int index)
IDProperty * IDP_AppendArray (IDProperty *prop, IDProperty *item)
void IDP_ResizeIDPArray (IDProperty *prop, int newlen)
static void idp_resize_group_array (IDProperty *prop, int newlen, void *newarr)
void IDP_ResizeArray (IDProperty *prop, int newlen)
void IDP_FreeArray (IDProperty *prop)
static IDProperty * idp_generic_copy (IDProperty *prop)
static IDProperty * IDP_CopyArray (IDProperty *prop)
IDProperty * IDP_NewString (const char *st, const char *name, int maxlen)
static IDProperty * IDP_CopyString (IDProperty *prop)
void IDP_AssignString (IDProperty *prop, const char *st, int maxlen)
void IDP_ConcatStringC (IDProperty *prop, const char *st)
void IDP_ConcatString (IDProperty *str1, IDProperty *append)
void IDP_FreeString (IDProperty *prop)
void IDP_LinkID (IDProperty *prop, ID *id)
void IDP_UnlinkID (IDProperty *prop)
static IDProperty * IDP_CopyGroup (IDProperty *prop)
void IDP_SyncGroupValues (IDProperty *dest, IDProperty *src)
void IDP_ReplaceGroupInGroup (IDProperty *dest, IDProperty *src)
void IDP_ReplaceInGroup (IDProperty *group, IDProperty *prop)
int IDP_AddToGroup (IDProperty *group, IDProperty *prop)
int IDP_InsertToGroup (IDProperty *group, IDProperty *previous, IDProperty *pnew)
void IDP_RemFromGroup (IDProperty *group, IDProperty *prop)
IDProperty * IDP_GetPropertyFromGroup (IDProperty *prop, const char *name)
IDProperty * IDP_GetPropertyTypeFromGroup (IDProperty *prop, const char *name, const char type)
void * IDP_GetGroupIterator (IDProperty *prop)
IDProperty * IDP_GroupIterNext (void *vself)
void IDP_FreeIterBeforeEnd (void *vself)
static void IDP_FreeGroup (IDProperty *prop)
IDProperty * IDP_CopyProperty (IDProperty *prop)
IDProperty * IDP_GetProperties (ID *id, int create_if_needed)
int IDP_EqualsProperties (IDProperty *prop1, IDProperty *prop2)
IDProperty * IDP_New (const int type, const IDPropertyTemplate *val, const char *name)
void IDP_FreeProperty (IDProperty *prop)
void IDP_UnlinkProperty (IDProperty *prop)
Variables
static char idp_size_table []
Detailed Description
Definition in file idprop.c.
Define Documentation
#define GETPROP (prop, i) (((IDProperty*)(prop)->data.pointer)+(i))
Definition at line 59 of file idprop.c.
Referenced by IDP_CopyIDPArray(), IDP_FreeIDPArray(), IDP_GetIndexArray(), IDP_ResizeIDPArray(), and IDP_SetIndexArray().
#define SWITCH_LONGINT (a)
Value:
{ \
    char s_i, *p_i; \
    p_i= (char *)&(a);  \
    s_i=p_i[0]; p_i[0]=p_i[7]; p_i[7]=s_i; \
    s_i=p_i[1]; p_i[1]=p_i[6]; p_i[6]=s_i; \
    s_i=p_i[2]; p_i[2]=p_i[5]; p_i[5]=s_i; \
    s_i=p_i[3]; p_i[3]=p_i[4]; p_i[4]=s_i; }
Definition at line 296 of file idprop.c.
Typedef Documentation
typedef struct IDPIter IDPIter
Function Documentation
int IDP_AddToGroup (struct IDProperty * group, struct IDProperty * prop)
This function has a sanity check to make sure ID properties with the same name don't get added to the group.
The sanity check just means the property is not added to the group if another property exists with the same name; the client code using ID properties then needs to detect this (the function that adds new properties to groups, IDP_AddToGroup, returns 0 if a property can't be added to the group, and 1 if it can) and free the property.
Currently the code to free ID properties is designed to leave the actual struct you pass it un-freed, this is needed for how the system works. This means to free an ID property, you first call IDP_FreeProperty then MEM_freeN the struct. In the future this will just be IDP_FreeProperty and the code will be reorganized to work properly.
Definition at line 507 of file idprop.c.
References BLI_addtail(), IDProperty::data, IDPropertyData::group, IDP_GetPropertyFromGroup(), IDProperty::len, IDProperty::name, and NULL.
Referenced by RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_collection_add(), RNA_property_enum_set(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_pointer_add(), RNA_property_string_set(), texture_paint_image_from_view_exec(), and ui_menu_block_set_keymaps().
IDProperty* IDP_AppendArray (IDProperty * prop, IDProperty * item) [read]
Definition at line 125 of file idprop.c.
References IDP_ResizeIDPArray(), IDP_SetIndexArray(), and IDProperty::len.
Referenced by BPy_IDProperty_Map_ValidateAndCreate(), and RNA_property_collection_add().
void IDP_AssignString (IDProperty * prop, const char * st, int maxlen)
Definition at line 348 of file idprop.c.
References BLI_strncpy(), IDProperty::data, IDP_ResizeArray(), IDP_STRING_SUB_BYTE, IDPropertyData::pointer, strlen(), and IDProperty::subtype.
Referenced by RNA_property_string_set(), and ui_menu_block_set_keymaps().
void IDP_ConcatString (IDProperty * str1, IDProperty * append)
Definition at line 377 of file idprop.c.
References IDProperty::data, IDP_ResizeArray(), IDProperty::len, and IDPropertyData::pointer.
void IDP_ConcatStringC (IDProperty * prop, const char * st)
Definition at line 366 of file idprop.c.
References IDProperty::data, IDP_ResizeArray(), IDProperty::len, IDPropertyData::pointer, and strlen().
static IDProperty* IDP_CopyArray (IDProperty * prop) [static]
Definition at line 273 of file idprop.c.
References IDProperty::data, IDP_CopyProperty(), idp_generic_copy(), IDP_GROUP, IDProperty::len, MEM_dupallocN(), IDPropertyData::pointer, IDProperty::subtype, IDProperty::totallen, and IDProperty::type.
Referenced by IDP_CopyProperty().
static IDProperty* IDP_CopyGroup (IDProperty * prop) [static]
Definition at line 412 of file idprop.c.
References BLI_addtail(), IDProperty::data, ListBase::first, IDPropertyData::group, IDP_CopyProperty(), idp_generic_copy(), IDProperty::len, and link().
Referenced by IDP_CopyProperty().
IDProperty* IDP_CopyIDPArray (IDProperty * array)
Definition at line 75 of file idprop.c.
References IDProperty::data, GETPROP, i, IDP_CopyProperty(), IDProperty::len, MEM_dupallocN(), MEM_freeN(), MEM_mallocN(), and IDPropertyData::pointer.
Referenced by IDP_CopyProperty().
IDProperty* IDP_CopyProperty (IDProperty * prop) [read]
Definition at line 593 of file idprop.c.
References IDP_ARRAY, IDP_CopyArray(), IDP_CopyGroup(), IDP_CopyIDPArray(), IDP_CopyString(), idp_generic_copy(), IDP_GROUP, IDP_IDPARRAY, IDP_STRING, and IDProperty::type.
Referenced by copy_bonechildren(), copy_libblock_data(), copy_pose(), copy_scene(), duplicate_pose_channel_data(), duplicateEditBoneObjects(), ED_armature_from_edit(), fcm_python_copy(), fcurves_to_pchan_links_get(), game_copy_pose(), IDP_CopyArray(), IDP_CopyGroup(), IDP_CopyIDPArray(), IDP_ReplaceGroupInGroup(), IDP_SyncGroupValues(), make_boneList(), menu_add_shortcut(), object_make_proxy(), pose_bone_do_paste(), pose_proxy_synchronize(), poselib_backup_posecopy(), pycon_copy(), uiItemsFullEnumO(), wm_keymap_item_copy(), WM_keymap_restore_item_to_default(), WM_operator_confirm_message(), and wm_operator_create().
static IDProperty* IDP_CopyString (IDProperty * prop) [static]
Definition at line 335 of file idprop.c.
References IDProperty::data, idp_generic_copy(), IDProperty::len, MEM_dupallocN(), IDPropertyData::pointer, IDProperty::subtype, and IDProperty::totallen.
Referenced by IDP_CopyProperty().
int IDP_EqualsProperties (IDProperty * prop1, IDProperty * prop2)
Definition at line 620 of file idprop.c.
References BLI_countlist(), IDProperty::data, ListBase::first, IDPropertyData::group, i, IDP_ARRAY, IDP_Array, IDP_Double, IDP_DOUBLE, IDP_EqualsProperties(), IDP_FLOAT, IDP_Float, IDP_GetPropertyFromGroup(), IDP_GROUP, IDP_IDPArray, IDP_IDPARRAY, IDP_Int, IDP_INT, idp_size_table, IDP_String, IDP_STRING, IDProperty::len, IDProperty::name, IDProperty::next, NULL, IDProperty::subtype, and IDProperty::type.
Referenced by IDP_EqualsProperties(), wm_keymap_item_equals_result(), and wm_keymap_item_find_handlers().
void IDP_FreeArray (IDProperty * prop)
Definition at line 251 of file idprop.c.
References IDProperty::data, idp_resize_group_array(), MEM_freeN(), NULL, and IDPropertyData::pointer.
Referenced by IDP_FreeProperty().
static void IDP_FreeGroup (IDProperty * prop) [static]
Definition at line 581 of file idprop.c.
References BLI_freelistN(), IDProperty::data, ListBase::first, IDPropertyData::group, IDP_FreeProperty(), and IDProperty::next.
Referenced by IDP_FreeProperty().
void IDP_FreeIDPArray (IDProperty * prop)
Definition at line 99 of file idprop.c.
References IDProperty::data, GETPROP, i, IDP_FreeProperty(), IDProperty::len, MEM_freeN(), and IDPropertyData::pointer.
Referenced by IDP_FreeProperty().
void IDP_FreeIterBeforeEnd (void * vself)
Frees the iterator pointed to at vself, only use this if iteration is stopped early; when the iterator hits the end of the list it'll automatically free itself.
Definition at line 572 of file idprop.c.
References MEM_freeN().
void IDP_FreeProperty (struct IDProperty * prop)
Note:
this will free all child properties of list arrays and groups! Also, note that this does NOT unlink anything! Plus it doesn't free the actual struct IDProperty struct either.
Definition at line 768 of file idprop.c.
References IDP_ARRAY, IDP_FreeArray(), IDP_FreeGroup(), IDP_FreeIDPArray(), IDP_FreeString(), IDP_GROUP, IDP_IDPARRAY, IDP_STRING, and IDProperty::type.
Referenced by bone_free(), BPy_IDProperty_Map_ValidateAndCreate(), BPy_Wrap_SetMapItem(), duplicate_pose_channel_data(), ED_armature_edit_free(), fcm_python_free(), free_bonelist(), free_libblock(), free_pose_channel(), free_posebuf(), free_scene(), IDP_FreeGroup(), IDP_FreeIDPArray(), IDP_ReplaceGroupInGroup(), IDP_ReplaceInGroup(), idp_resize_group_array(), IDP_ResizeIDPArray(), IDP_SetIndexArray(), IDP_SyncGroupValues(), keymap_item_free(), object_make_proxy(), operatortype_ghash_free_cb(), pose_clear_user_transforms_exec(), pose_proxy_synchronize(), poseAnim_mapping_free(), poselib_backup_free_data(), pycon_free(), pyrna_struct_dealloc(), rna_idproperty_check(), RNA_property_pointer_remove(), RNA_struct_idprops_unset(), shader_preview_free(), ui_menu_block_set_keymaps(), uiItemsFullEnumO(), WM_keymap_restore_item_to_default(), WM_operator_free(), WM_operator_properties_free(), and WM_operatortype_remove().
void IDP_FreeString (IDProperty * prop)
Definition at line 388 of file idprop.c.
References IDProperty::data, MEM_freeN(), and IDPropertyData::pointer.
Referenced by IDP_FreeProperty().
static IDProperty* idp_generic_copy (IDProperty * prop) [static]
Definition at line 260 of file idprop.c.
References BLI_strncpy(), IDProperty::data, IDProperty::flag, MAX_IDPROP_NAME, MEM_callocN(), IDProperty::name, IDProperty::type, IDPropertyData::val, and IDPropertyData::val2.
Referenced by IDP_CopyArray(), IDP_CopyGroup(), IDP_CopyProperty(), and IDP_CopyString().
void* IDP_GetGroupIterator (struct IDProperty * prop)
Get an iterator to iterate over the members of an id property group. Note that this will automatically free the iterator once iteration is complete; if you stop the iteration before hitting the end, make sure to call IDP_FreeIterBeforeEnd().
Definition at line 551 of file idprop.c.
References IDProperty::data, ListBase::first, IDPropertyData::group, MEM_callocN(), IDPIter::next, and IDPIter::parent.
IDProperty* IDP_GetIndexArray (IDProperty * prop, int index) [read]
Definition at line 120 of file idprop.c.
References GETPROP.
Referenced by RNA_property_collection_add().
IDProperty* IDP_GetProperties (struct ID * id, int create_if_needed) [read]
Get the Group property that contains the id properties for ID id. Set create_if_needed to create the Group property and attach it to id if it doesn't exist; otherwise the function will return NULL if there's no Group property attached to the ID.
Definition at line 604 of file idprop.c.
References IDP_GROUP, MEM_callocN(), and ID::properties.
Referenced by project_paint_begin(), shader_preview_free(), texture_paint_camera_project_exec(), and texture_paint_image_from_view_exec().
IDProperty* IDP_GetPropertyFromGroup (IDProperty * prop, const char * name)
Definition at line 535 of file idprop.c.
References BLI_findstring(), IDProperty::data, and IDPropertyData::group.
Referenced by BPy_IDGroup_Contains(), BPy_IDGroup_Get(), BPy_IDGroup_Map_GetItem(), BPy_IDGroup_Pop(), BPy_Wrap_SetMapItem(), IDP_AddToGroup(), IDP_EqualsProperties(), IDP_GetPropertyTypeFromGroup(), IDP_InsertToGroup(), IDP_ReplaceInGroup(), project_paint_begin(), pyrna_struct_contains(), pyrna_struct_get(), pyrna_struct_subscript(), rna_idproperty_find(), RNA_path_resolve_full(), and RNA_struct_idprops_unset().
IDProperty* IDP_GetPropertyTypeFromGroup (struct IDProperty * prop, const char * name, const char type)
same as above but ensure type match
Definition at line 540 of file idprop.c.
References IDP_GetPropertyFromGroup(), NULL, and IDProperty::type.
Referenced by rna_ensure_property_description(), rna_idproperty_ui(), RNA_property_float_range(), RNA_property_float_ui_range(), RNA_property_int_range(), RNA_property_int_ui_range(), and texture_paint_camera_project_exec().
IDProperty* IDP_GroupIterNext (void * vself)
Returns the next item in the iteration. To use, simple for a loop like the following: while (IDP_GroupIterNext(iter) != NULL) { ... }
Definition at line 559 of file idprop.c.
References if(), MEM_freeN(), next, Link::next, and NULL.
int IDP_InsertToGroup (struct IDProperty * group, struct IDProperty * previous, struct IDProperty * pnew)
this is the same as IDP_AddToGroup, only you pass an item in the group list to be inserted after.
Definition at line 518 of file idprop.c.
References BLI_insertlink(), IDProperty::data, IDPropertyData::group, IDP_GetPropertyFromGroup(), IDProperty::len, IDProperty::name, and NULL.
void IDP_LinkID (IDProperty * prop, ID * id)
Definition at line 397 of file idprop.c.
References IDProperty::data, id_us_plus(), and IDPropertyData::pointer.
IDProperty* IDP_New (const int type, const IDPropertyTemplate * val, const char * name) [read]
Allocate a new ID.
This function takes three arguments: the ID property type, a union which defines it's initial value, and a name.
The union is simple to use; see the top of this header file for its definition. An example of using this function:
IDPropertyTemplate val; IDProperty *group, *idgroup, *color; group = IDP_New(IDP_GROUP, val, "group1"); //groups don't need a template.
val.array.len = 4 val.array.type = IDP_FLOAT; color = IDP_New(IDP_ARRAY, val, "color1");
idgroup = IDP_GetProperties(some_id, 1); IDP_AddToGroup(idgroup, color); IDP_AddToGroup(idgroup, group);
Note that you MUST either attach the id property to an id property group with IDP_AddToGroup or MEM_freeN the property, doing anything else might result in a memory leak.
Definition at line 675 of file idprop.c.
References IDPropertyTemplate::array, IDPropertyTemplate::d, IDProperty::data, DEFAULT_ALLOC_FOR_NULL_STRINGS, IDPropertyTemplate::f, IDPropertyTemplate::i, IDP_ARRAY, IDP_DOUBLE, IDP_FLOAT, IDP_GROUP, IDP_INT, idp_size_table, IDP_STRING, IDP_STRING_SUB_BYTE, IDP_STRING_SUB_UTF8, if(), IDProperty::len, IDPropertyTemplate::len, MEM_callocN(), MEM_mallocN(), NULL, IDPropertyData::pointer, IDPropertyTemplate::str, IDPropertyTemplate::string, strlen(), IDPropertyTemplate::subtype, IDProperty::subtype, IDProperty::totallen, IDPropertyTemplate::type, and IDPropertyData::val.
Referenced by BPy_IDProperty_Map_ValidateAndCreate(), idp_resize_group_array(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_collection_add(), RNA_property_enum_set(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_pointer_add(), texture_paint_image_from_view_exec(), ui_menu_block_set_keymaps(), uiItemFullO_ptr(), uiLayoutOperatorButs(), wm_operator_create(), and WM_operator_properties_alloc().
IDProperty* IDP_NewIDPArray (const char * name)
Definition at line 65 of file idprop.c.
References BLI_strncpy(), IDP_IDPARRAY, IDProperty::len, MAX_IDPROP_NAME, MEM_callocN(), IDProperty::name, and IDProperty::type.
Referenced by BPy_IDProperty_Map_ValidateAndCreate(), and RNA_property_collection_add().
IDProperty* IDP_NewString (const char * st, const char * name, int maxlen)
Definition at line 307 of file idprop.c.
References BLI_strncpy(), IDProperty::data, DEFAULT_ALLOC_FOR_NULL_STRINGS, IDP_STRING, IDProperty::len, MAX_IDPROP_NAME, MEM_callocN(), IDProperty::name, NULL, IDPropertyData::pointer, strlen(), IDProperty::totallen, and IDProperty::type.
Referenced by RNA_property_string_set(), and ui_menu_block_set_keymaps().
void IDP_RemFromGroup (struct IDProperty * group, struct IDProperty * prop)
Note:
this does not free the property!!
To free the property, you have to do: IDP_FreeProperty(prop); //free all subdata MEM_freeN(prop); //free property struct itself
Definition at line 529 of file idprop.c.
References BLI_remlink(), IDProperty::data, IDPropertyData::group, and IDProperty::len.
Referenced by BPy_IDGroup_Pop(), BPy_Wrap_SetMapItem(), rna_idproperty_check(), RNA_property_pointer_remove(), and RNA_struct_idprops_unset().
void IDP_ReplaceGroupInGroup (struct IDProperty * dest, struct IDProperty * src)
replaces all properties with the same name in a destination group from a source group.
Definition at line 460 of file idprop.c.
References BLI_addtail(), BLI_insertlink(), BLI_remlink(), copy(), IDProperty::data, ListBase::first, IDPropertyData::group, IDP_CopyProperty(), IDP_FreeProperty(), IDProperty::len, MEM_freeN(), IDProperty::name, IDProperty::next, and NULL.
Referenced by wm_operator_create().
void IDP_ReplaceInGroup (struct IDProperty * group, struct IDProperty * prop)
Checks if a property with the same name as prop exists, and if so replaces it. Use this to preserve order!
Definition at line 489 of file idprop.c.
References BLI_addtail(), BLI_insertlink(), BLI_remlink(), IDProperty::data, IDPropertyData::group, IDP_FreeProperty(), IDP_GetPropertyFromGroup(), IDProperty::len, MEM_freeN(), and IDProperty::name.
Referenced by BPy_IDProperty_Map_ValidateAndCreate().
static void idp_resize_group_array (IDProperty * prop, int newlen, void * newarr) [static]
Definition at line 181 of file idprop.c.
References IDProperty::data, IDPropertyTemplate::i, IDP_FreeProperty(), IDP_GROUP, IDP_New(), IDProperty::len, MEM_freeN(), IDPropertyData::pointer, and IDProperty::subtype.
Referenced by IDP_FreeArray(), and IDP_ResizeArray().
void IDP_ResizeArray (IDProperty * prop, int newlen)
Definition at line 210 of file idprop.c.
References IDProperty::data, idp_resize_group_array(), idp_size_table, IDProperty::len, MEM_callocN(), MEM_freeN(), IDPropertyData::pointer, IDProperty::subtype, and IDProperty::totallen.
Referenced by IDP_AssignString(), IDP_ConcatString(), and IDP_ConcatStringC().
void IDP_ResizeIDPArray (IDProperty * prop, int newlen)
Definition at line 132 of file idprop.c.
References IDProperty::data, GETPROP, i, IDP_FreeProperty(), IDProperty::len, MEM_callocN(), MEM_freeN(), IDPropertyData::pointer, and IDProperty::totallen.
Referenced by IDP_AppendArray(), RNA_property_collection_clear(), and RNA_property_collection_remove().
void IDP_SetIndexArray (IDProperty * prop, int index, IDProperty * item)
Definition at line 111 of file idprop.c.
References GETPROP, IDP_FreeProperty(), and IDProperty::len.
Referenced by IDP_AppendArray().
void IDP_SyncGroupValues (struct IDProperty * dest, struct IDProperty * src)
Sync values from one group to another, only where they match
Definition at line 426 of file idprop.c.
References BLI_findstring(), BLI_insertlinkafter(), BLI_remlink(), copy(), IDProperty::data, ListBase::first, IDPropertyData::group, IDP_CopyProperty(), IDP_DOUBLE, IDP_FLOAT, IDP_FreeProperty(), IDP_GROUP, IDP_INT, IDP_SyncGroupValues(), MEM_freeN(), IDProperty::name, IDProperty::next, and IDProperty::type.
Referenced by IDP_SyncGroupValues(), pose_bone_do_paste(), pose_proxy_synchronize(), poseAnim_mapping_reset(), and poselib_backup_restore().
void IDP_UnlinkID (IDProperty * prop)
Definition at line 404 of file idprop.c.
References IDProperty::data, and IDPropertyData::pointer.
Referenced by IDP_UnlinkProperty().
void IDP_UnlinkProperty (struct IDProperty * prop)
Unlinks any struct IDProperty<->ID linkage that might be going on.
Definition at line 788 of file idprop.c.
References IDP_ID, IDP_UnlinkID(), and IDProperty::type.
Variable Documentation
char idp_size_table[] [static]
Initial value:
 {
    1,
    sizeof(int),
    sizeof(float),
    sizeof(float)*3,
    sizeof(float)*16,
    0,
    sizeof(ListBase),
    sizeof(void*),
    sizeof(double)
}
Definition at line 46 of file idprop.c.
Referenced by IDP_EqualsProperties(), IDP_New(), and IDP_ResizeArray().