Blender: node_texture_tree.c File Reference
node_texture_tree.c File Reference
nodes
#include <string.h>
#include "DNA_texture_types.h"
#include "DNA_node_types.h"
#include "BLI_listbase.h"
#include "BLI_threads.h"
#include "BLI_utildefines.h"
#include "BLF_translation.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_node.h"
#include "node_exec.h"
#include "node_util.h"
#include "NOD_texture.h"
#include "node_texture_util.h"
#include "RE_pipeline.h"
#include "RE_shader_ext.h"
Functions
static void foreach_nodetree (Main *main, void *calldata, bNodeTreeCallback func)
static void foreach_nodeclass (Scene *UNUSED(scene), void *calldata, bNodeClassCallback func)
static void localize (bNodeTree *localtree, bNodeTree *UNUSED(ntree))
static void local_sync (bNodeTree *localtree, bNodeTree *ntree)
int ntreeTexTagAnimated (bNodeTree *ntree)
bNodeTreeExec * ntreeTexBeginExecTree (bNodeTree *ntree, int use_tree_data)
static void tex_free_delegates (bNodeTreeExec *exec)
void ntreeTexEndExecTree (bNodeTreeExec *exec, int use_tree_data)
int ntreeTexExecTree (bNodeTree *nodes, TexResult *texres, float *co, float *dxt, float *dyt, int osatex, short thread, Tex *UNUSED(tex), short which_output, int cfra, int preview, ShadeInput *shi, MTex *mtex)
Variables
bNodeTreeType ntreeType_Texture
Detailed Description
Definition in file node_texture_tree.c.
Function Documentation
static void foreach_nodeclass (Scene * UNUSEDscene, void * calldata, bNodeClassCallback func) [static]
Definition at line 67 of file node_texture_tree.c.
References IFACE_, NODE_CLASS_CONVERTOR, NODE_CLASS_DISTORT, NODE_CLASS_GROUP, NODE_CLASS_INPUT, NODE_CLASS_LAYOUT, NODE_CLASS_OP_COLOR, NODE_CLASS_OUTPUT, NODE_CLASS_PATTERN, and NODE_CLASS_TEXTURE.
static void foreach_nodetree (Main * main, void * calldata, bNodeTreeCallback func) [static]
Definition at line 57 of file node_texture_tree.c.
References ListBase::first, Tex::id, ID::next, Tex::nodetree, and Main::tex.
static void local_sync (bNodeTree * localtree, bNodeTree * ntree) [static]
Definition at line 95 of file node_texture_tree.c.
References ListBase::first, bNode::new_node, bNode::next, bNodeTree::nodes, ntreeNodeExists(), bNode::preview, bNodePreview::rect, bNodePreview::xsize, and bNodePreview::ysize.
static void localize (bNodeTree * localtree, bNodeTree * UNUSEDntree) [static]
Definition at line 80 of file node_texture_tree.c.
References ListBase::first, bNode::flag, bNode::next, NODE_MUTED, nodeFreeNode(), nodeInternalRelink(), and bNodeTree::nodes.
bNodeTreeExec* ntreeTexBeginExecTree (bNodeTree * ntree, int use_tree_data) [read]
Definition at line 158 of file node_texture_tree.c.
References BLENDER_MAX_THREADS, exec(), bNodeTree::execdata, ListBase::first, MEM_callocN(), bNode::need_exec, bNode::next, bNodeTree::nodes, bNodeTreeExec::nodetree, ntree_exec_begin(), and bNodeTreeExec::threadstack.
Referenced by group_initexec(), init_render_texture(), ntree_composite_texnode(), ntreeTexExecTree(), paint_brush_init_tex(), and sculpt_brush_init_tex().
void ntreeTexEndExecTree (bNodeTreeExec * exec, int use_tree_data)
Definition at line 207 of file node_texture_tree.c.
References BLENDER_MAX_THREADS, BLI_freelistN(), bNodeTree::execdata, ListBase::first, MEM_freeN(), bNodeThreadStack::next, bNodeTreeExec::nodetree, ntree_exec_end(), NULL, bNodeThreadStack::stack, tex_free_delegates(), and bNodeTreeExec::threadstack.
Referenced by copy_texture(), end_render_texture(), group_freeexec(), ntree_composite_texnode(), ntreeFreeTree(), paint_brush_exit_tex(), and sculpt_brush_exit_tex().
int ntreeTexExecTree (bNodeTree * nodes, TexResult * texres, float * co, float * dxt, float * dyt, int osatex, short thread, Tex * UNUSEDtex, short which_output, int cfra, int preview, ShadeInput * shi, MTex * mtex)
Definition at line 236 of file node_texture_tree.c.
References BLI_lock_thread(), BLI_unlock_thread(), TexCallData::cfra, co, TexCallData::co, data, TexCallData::do_preview, TexCallData::dxt, TexCallData::dyt, exec(), bNodeTree::execdata, LOCK_NODES, TexCallData::mtex, TexResult::nor, ntreeExecThreadNodes(), ntreeGetThreadStack(), ntreeReleaseThreadStack(), ntreeTexBeginExecTree(), NULL, TexCallData::osatex, TexCallData::shi, TexCallData::target, TEX_INT, TEX_NOR, TEX_RGB, TexCallData::thread, and TexCallData::which_output.
int ntreeTexTagAnimated (bNodeTree * ntree)
Definition at line 134 of file node_texture_tree.c.
References ListBase::first, bNode::id, bNode::next, NODE_GROUP, bNodeTree::nodes, nodeUpdate(), ntreeTexTagAnimated(), NULL, TEX_NODE_CURVE_TIME, and bNode::type.
Referenced by ED_update_for_newframe(), and ntreeTexTagAnimated().
static void tex_free_delegates (bNodeTreeExec * exec) [static]
Definition at line 191 of file node_texture_tree.c.
References BLENDER_MAX_THREADS, bNodeStack::data, ListBase::first, bNodeStack::is_copy, MEM_freeN(), bNodeThreadStack::next, bNodeThreadStack::stack, and bNodeTreeExec::threadstack.
Referenced by ntreeTexEndExecTree().
Variable Documentation
bNodeTreeType ntreeType_Texture
Initial value:
 {
                    NTREE_TEXTURE,
                "NTTexture Nodetree",
            { NULL, NULL },
                NULL,
            NULL,
        foreach_nodetree,
        foreach_nodeclass,
                localize,
            local_sync,
            NULL,
                NULL,
            NULL,
            NULL,
        node_internal_connect_default
}
Definition at line 115 of file node_texture_tree.c.
Referenced by ntreeGetType().