Blender: mathutils_noise.h File Reference
mathutils_noise.h File Reference
#include "mathutils.h"
Functions
PyMODINIT_FUNC PyInit_mathutils_noise (void)
PyMODINIT_FUNC PyInit_mathutils_noise_types (void)
PyMODINIT_FUNC PyInit_mathutils_noise_metrics (void)
Detailed Description
Definition in file mathutils_noise.h.
Function Documentation
PyMODINIT_FUNC PyInit_mathutils_noise (void)
Definition at line 836 of file mathutils_noise.c.
References interp(), PyInit_mathutils_noise_metrics(), PyInit_mathutils_noise_types(), and setRndSeed().
Referenced by PyInit_mathutils().
PyMODINIT_FUNC PyInit_mathutils_noise_metrics (void)
Definition at line 898 of file mathutils_noise.c.
References TEX_CHEBYCHEV, TEX_DISTANCE, TEX_DISTANCE_SQUARED, TEX_MANHATTAN, TEX_MINKOVSKY, TEX_MINKOVSKY_FOUR, and TEX_MINKOVSKY_HALF.
Referenced by PyInit_mathutils_noise().
PyMODINIT_FUNC PyInit_mathutils_noise_types (void)
Definition at line 868 of file mathutils_noise.c.
References TEX_BLENDER, TEX_CELLNOISE, TEX_NEWPERLIN, TEX_STDPERLIN, TEX_VORONOI_CRACKLE, TEX_VORONOI_F1, TEX_VORONOI_F2, TEX_VORONOI_F2F1, TEX_VORONOI_F3, and TEX_VORONOI_F4.
Referenced by PyInit_mathutils_noise().