Blender: btBox2dBox2dCollisionAlgorithm Class Reference
btBox2dBox2dCollisionAlgorithm Class Reference
box-box collision detection
#include <btBox2dBox2dCollisionAlgorithm.h>
Classes
struct CreateFunc
Public Member Functions
btBox2dBox2dCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo &ci)
virtual void processCollision (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
virtual btScalar calculateTimeOfImpact (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
btBox2dBox2dCollisionAlgorithm (btPersistentManifold *mf, const btCollisionAlgorithmConstructionInfo &ci, btCollisionObject *body0, btCollisionObject *body1)
virtual ~btBox2dBox2dCollisionAlgorithm ()
virtual void getAllContactManifolds (btManifoldArray &manifoldArray)
Detailed Description
box-box collision detection
Definition at line 27 of file btBox2dBox2dCollisionAlgorithm.h.
Constructor & Destructor Documentation
btBox2dBox2dCollisionAlgorithm::btBox2dBox2dCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo & ci) [inline]
Definition at line 33 of file btBox2dBox2dCollisionAlgorithm.h.
Referenced by btBox2dBox2dCollisionAlgorithm::CreateFunc::CreateCollisionAlgorithm().
btBox2dBox2dCollisionAlgorithm::btBox2dBox2dCollisionAlgorithm (btPersistentManifold * mf, const btCollisionAlgorithmConstructionInfo & ci, btCollisionObject * body0, btCollisionObject * body1)
Definition at line 28 of file btBox2dBox2dCollisionAlgorithm.cpp.
References btDispatcher::getNewManifold(), btCollisionAlgorithm::m_dispatcher, and btDispatcher::needsCollision().
btBox2dBox2dCollisionAlgorithm::~btBox2dBox2dCollisionAlgorithm () [virtual]
Definition at line 40 of file btBox2dBox2dCollisionAlgorithm.cpp.
References btCollisionAlgorithm::m_dispatcher, and btDispatcher::releaseManifold().
Member Function Documentation
btScalar btBox2dBox2dCollisionAlgorithm::calculateTimeOfImpact (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Implements btCollisionAlgorithm.
Definition at line 77 of file btBox2dBox2dCollisionAlgorithm.cpp.
virtual void btBox2dBox2dCollisionAlgorithm::getAllContactManifolds (btManifoldArray & manifoldArray) [inline, virtual]
Implements btCollisionAlgorithm.
Definition at line 44 of file btBox2dBox2dCollisionAlgorithm.h.
References btAlignedObjectArray< T >::push_back().
void btBox2dBox2dCollisionAlgorithm::processCollision (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Implements btCollisionAlgorithm.
Definition at line 55 of file btBox2dBox2dCollisionAlgorithm.cpp.
References b2CollidePolygons(), btManifoldResult::refreshContactPoints(), and btManifoldResult::setPersistentManifold().
The documentation for this class was generated from the following files:
btBox2dBox2dCollisionAlgorithm.h
btBox2dBox2dCollisionAlgorithm.cpp