Blender: vbvh.h File Reference
vbvh.h File Reference
Rendering
#include <assert.h>
#include <algorithm>
#include "BLI_memarena.h"
#include "rayobject_rtbuild.h"
Classes
struct VBVHNode
struct BuildBinaryVBVH< Node >
Functions
template<class Node >
static void bvh_node_push_childs (Node *node, Isect *UNUSED(isec), Node **stack, int &stack_pos)
template<class Node >
int count_childs (Node *parent)
template<class Node >
void append_sibling (Node *node, Node *sibling)
Detailed Description
Definition in file vbvh.h.
Function Documentation
template<class Node > void append_sibling (Node * node, Node * sibling)
Definition at line 101 of file vbvh.h.
Referenced by pushup(), and pushup_simd().
template<class Node > static void bvh_node_push_childs (Node * node, Isect * UNUSEDisec, Node ** stack, int & stack_pos) [inline, static]
Definition at line 56 of file vbvh.h.
References is_leaf().
template<class Node > int count_childs (Node * parent)
Definition at line 86 of file vbvh.h.
References i, and is_leaf().
Referenced by bvh_dfs_make_hint(), pushup(), and pushup_simd().