Blender: LOD_DecimationClass Class Reference
LOD_DecimationClass Class Reference
#include <LOD_DecimationClass.h>
Public Types
enum { e_not_loaded, e_loaded, e_preprocessed }
Public Member Functions
LOD_ManMesh2 & Mesh ()
LOD_QSDecimator & Decimator ()
LOD_ExternNormalEditor & FaceEditor ()
Static Public Member Functions
static LOD_DecimationClass * New (LOD_Decimation_InfoPtr extern_info)
Public Attributes
enum LOD_DecimationClass:: { ... } m_e_decimation_state
Detailed Description
Definition at line 46 of file LOD_DecimationClass.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
e_not_loaded
e_loaded
e_preprocessed
Definition at line 50 of file LOD_DecimationClass.h.
Member Function Documentation
LOD_QSDecimator& LOD_DecimationClass::Decimator () [inline]
Definition at line 94 of file LOD_DecimationClass.h.
References MEM_SmartPtr< T >::Ref().
Referenced by LOD_CollapseEdge(), and LOD_PreprocessMesh().
LOD_ExternNormalEditor& LOD_DecimationClass::FaceEditor () [inline]
Definition at line 100 of file LOD_DecimationClass.h.
References MEM_SmartPtr< T >::Ref().
Referenced by LOD_PreprocessMesh().
LOD_ManMesh2& LOD_DecimationClass::Mesh () [inline]
Definition at line 88 of file LOD_DecimationClass.h.
References MEM_SmartPtr< T >::Ref().
static LOD_DecimationClass* LOD_DecimationClass::New (LOD_Decimation_InfoPtr extern_info) [inline, static]
Definition at line 59 of file LOD_DecimationClass.h.
References LOD_ExternNormalEditor::New(), LOD_ExternBufferEditor::New(), LOD_ManMesh2::New(), LOD_QSDecimator::New(), NULL, MEM_SmartPtr< T >::Ref(), and MEM_SmartPtr< T >::Release().
Referenced by LOD_LoadMesh().
Member Data Documentation
enum { ... } LOD_DecimationClass::m_e_decimation_state
Referenced by LOD_CollapseEdge(), and LOD_PreprocessMesh().
The documentation for this class was generated from the following file:
LOD_DecimationClass.h