Blender: btBroadphaseAabbCallback Struct Reference
btBroadphaseAabbCallback Struct Reference
#include <btBroadphaseInterface.h>
Public Member Functions
virtual ~btBroadphaseAabbCallback ()
virtual bool process (const btBroadphaseProxy *proxy)=0
Detailed Description
Definition at line 29 of file btBroadphaseInterface.h.
Constructor & Destructor Documentation
virtual btBroadphaseAabbCallback::~btBroadphaseAabbCallback () [inline, virtual]
Definition at line 31 of file btBroadphaseInterface.h.
Member Function Documentation
virtual bool btBroadphaseAabbCallback::process (const btBroadphaseProxy * proxy) [pure virtual]
Implemented in btSingleRayCallback, btSingleSweepCallback, btSingleContactCallback, and btSoftSingleRayCallback.
Referenced by btSimpleBroadphase::aabbTest(), btAxisSweep3Internal< BP_FP_INT_TYPE >::aabbTest(), BroadphaseAabbTester::Process(), BroadphaseRayTester::Process(), btMultiSapBroadphase::rayTest(), btSimpleBroadphase::rayTest(), and btAxisSweep3Internal< BP_FP_INT_TYPE >::rayTest().
The documentation for this struct was generated from the following file:
btBroadphaseInterface.h