Blender: IMB_filter.h File Reference
IMB_filter.h File Reference
IMage Buffer
Function declarations for filter.c.
Functions
void imb_filterx (struct ImBuf *ibuf)
void IMB_premultiply_rect (unsigned int *rect, char planes, int w, int h)
void IMB_premultiply_rect_float (float *rect_float, char planes, int w, int h)
void imb_onehalf_no_alloc (struct ImBuf *ibuf2, struct ImBuf *ibuf1)
Detailed Description
Function declarations for filter.c.
Definition in file IMB_filter.h.
Function Documentation
void imb_filterx (struct ImBuf * ibuf)
Definition at line 174 of file filter.c.
References filtrow(), filtrowf(), ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by IMB_double_x(), and IMB_filter().
void imb_onehalf_no_alloc (struct ImBuf * ibuf2, struct ImBuf * ibuf1)
Definition at line 296 of file scaling.c.
References imb_addrectImBuf(), NULL, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by IMB_onehalf(), and IMB_remakemipmap().
void IMB_premultiply_rect (unsigned int * rect, char planes, int w, int h)
Definition at line 537 of file filter.c.
Referenced by imb_loadtiletiff(), and IMB_premultiply_alpha().
void IMB_premultiply_rect_float (float * rect_float, char planes, int w, int h)
Definition at line 563 of file filter.c.
Referenced by IMB_premultiply_alpha().