Blender: node_composite_sepcombYUVA.c File Reference
node_composite_sepcombYUVA.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_sepyuva (bNode *UNUSED(node), float *out, float *in)
static void node_composit_exec_sepyuva (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_sepyuva (bNodeTreeType *ttype)
static void do_comb_yuva (bNode *UNUSED(node), float *out, float *in1, float *in2, float *in3, float *in4)
static void node_composit_exec_combyuva (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_combyuva (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_sepyuva_in []
static bNodeSocketTemplate cmp_node_sepyuva_out []
static bNodeSocketTemplate cmp_node_combyuva_in []
static bNodeSocketTemplate cmp_node_combyuva_out []
Detailed Description
Definition in file node_composite_sepcombYUVA.c.
Function Documentation
static void do_comb_yuva (bNode * UNUSEDnode, float * out, float * in1, float * in2, float * in3, float * in4) [static]
Definition at line 129 of file node_composite_sepcombYUVA.c.
References g, and yuv_to_rgb().
Referenced by node_composit_exec_combyuva().
static void do_sepyuva (bNode * UNUSEDnode, float * out, float * in) [static]
Definition at line 49 of file node_composite_sepcombYUVA.c.
References rgb_to_yuv().
Referenced by node_composit_exec_sepyuva().
static void node_composit_exec_combyuva (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 140 of file node_composite_sepcombYUVA.c.
References alloc_compbuf(), CB_RGBA, CB_VAL, composit4_pixel_processor(), bNodeStack::data, data, do_comb_yuva(), NULL, bNodeStack::vec, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_combyuva().
static void node_composit_exec_sepyuva (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 61 of file node_composite_sepcombYUVA.c.
References CB_RGBA, CHAN_A, CHAN_B, CHAN_G, CHAN_R, composit1_pixel_processor(), bNodeStack::data, data, do_sepyuva(), dupalloc_compbuf(), free_compbuf(), NULL, rgb_to_yuv(), typecheck_compbuf(), valbuf_from_rgbabuf(), and bNodeStack::vec.
Referenced by register_node_type_cmp_sepyuva().
void register_node_type_cmp_combyuva (bNodeTreeType * ttype)
Definition at line 173 of file node_composite_sepcombYUVA.c.
References CMP_NODE_COMBYUVA, NODE_CLASS_CONVERTOR, node_composit_exec_combyuva(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_sepyuva (bNodeTreeType * ttype)
Definition at line 102 of file node_composite_sepcombYUVA.c.
References CMP_NODE_SEPYUVA, NODE_CLASS_CONVERTOR, node_composit_exec_sepyuva(), node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_combyuva_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Y",         0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
    {   SOCK_FLOAT, 1, "U",         0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
    {   SOCK_FLOAT, 1, "V",         0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
    {   SOCK_FLOAT, 1, "A",         1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
    {   -1, 0, ""   }
}
Definition at line 117 of file node_composite_sepcombYUVA.c.
bNodeSocketTemplate cmp_node_combyuva_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 124 of file node_composite_sepcombYUVA.c.
bNodeSocketTemplate cmp_node_sepyuva_in[] [static]
Initial value:
 {
    {  SOCK_RGBA, 1, "Image",        1.0f, 1.0f, 1.0f, 1.0f},
    {  -1, 0, ""   }
}
Definition at line 37 of file node_composite_sepcombYUVA.c.
bNodeSocketTemplate cmp_node_sepyuva_out[] [static]
Initial value:
 {
    {  SOCK_FLOAT, 0, "Y"},
    {  SOCK_FLOAT, 0, "U"},
    {  SOCK_FLOAT, 0, "V"},
    {  SOCK_FLOAT, 0, "A"},
    {  -1, 0, ""   }
}
Definition at line 41 of file node_composite_sepcombYUVA.c.