Blender: KX_SoundActuator Class Reference
KX_SoundActuator Class Reference
#include <KX_SoundActuator.h>
Public Types
enum KX_SOUNDACT_TYPE {
KX_SOUNDACT_NODEF = 0, KX_SOUNDACT_PLAYSTOP, KX_SOUNDACT_PLAYEND, KX_SOUNDACT_LOOPSTOP,
KX_SOUNDACT_LOOPEND, KX_SOUNDACT_LOOPBIDIRECTIONAL, KX_SOUNDACT_LOOPBIDIRECTIONAL_STOP, KX_SOUNDACT_MAX
}
Public Member Functions
KX_SoundActuator (SCA_IObject *gameobj, AUD_Reference< AUD_IFactory > sound, float volume, float pitch, bool is3d, KX_3DSoundSettings settings, KX_SOUNDACT_TYPE type)
~KX_SoundActuator ()
virtual bool Update (double curtime, bool frame)
CValue * GetReplica ()
void ProcessReplica ()
Public Attributes
KX_SOUNDACT_TYPE m_type
Detailed Description
Definition at line 58 of file KX_SoundActuator.h.
Member Enumeration Documentation
enum KX_SoundActuator::KX_SOUNDACT_TYPE
Enumerator:
KX_SOUNDACT_NODEF
KX_SOUNDACT_PLAYSTOP
KX_SOUNDACT_PLAYEND
KX_SOUNDACT_LOOPSTOP
KX_SOUNDACT_LOOPEND
KX_SOUNDACT_LOOPBIDIRECTIONAL
KX_SOUNDACT_LOOPBIDIRECTIONAL_STOP
KX_SOUNDACT_MAX
Definition at line 73 of file KX_SoundActuator.h.
Constructor & Destructor Documentation
KX_SoundActuator::KX_SoundActuator (SCA_IObject * gameobj, AUD_Reference< AUD_IFactory > sound, float volume, float pitch, bool is3d, KX_3DSoundSettings settings, KX_SOUNDACT_TYPE type)
Definition at line 55 of file KX_SoundActuator.cpp.
References m_type.
Referenced by GetReplica().
KX_SoundActuator::~KX_SoundActuator ()
Definition at line 75 of file KX_SoundActuator.cpp.
References AUD_Reference< T >::isNull().
Member Function Documentation
CValue * KX_SoundActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 142 of file KX_SoundActuator.cpp.
References KX_SoundActuator(), and ProcessReplica().
void KX_SoundActuator::ProcessReplica () [virtual]
Makes sure any internal data owned by this class is deep copied.
Reimplemented from SCA_IActuator.
Definition at line 149 of file KX_SoundActuator.cpp.
Referenced by GetReplica().
bool KX_SoundActuator::Update (double curtime, bool frame) [virtual]
Update(...) Update the actuator based upon the events received since the last call to Update, the current time and deltatime the time elapsed in this frame ? It is the responsibility of concrete Actuators to clear their event's. This is usually done in the Update() method via a call to RemoveAllEvents()
Reimplemented from SCA_IActuator.
Definition at line 155 of file KX_SoundActuator.cpp.
References AUD_STATUS_INVALID, AUD_STATUS_PAUSED, AUD_STATUS_PLAYING, KX_3DSoundSettings::cone_inner_angle, KX_3DSoundSettings::cone_outer_angle, KX_3DSoundSettings::cone_outer_gain, AUD_Vector3::get(), KX_Scene::GetActiveCamera(), KX_GameObject::GetLinearVelocity(), SCA_ILogicBrick::GetParent(), MT_Matrix3x3::inverse(), SCA_IActuator::IsNegativeEvent(), AUD_Reference< T >::isNull(), KX_GetActiveScene(), KX_SOUNDACT_LOOPBIDIRECTIONAL, KX_SOUNDACT_LOOPBIDIRECTIONAL_STOP, KX_SOUNDACT_LOOPEND, KX_SOUNDACT_LOOPSTOP, KX_SOUNDACT_MAX, KX_SOUNDACT_NODEF, KX_SOUNDACT_PLAYEND, KX_SOUNDACT_PLAYSTOP, SCA_ILogicBrick::m_name, SCA_IActuator::m_posevent, m_type, KX_3DSoundSettings::max_distance, KX_3DSoundSettings::max_gain, KX_3DSoundSettings::min_gain, KX_GameObject::NodeGetWorldOrientation(), KX_GameObject::NodeGetWorldPosition(), NULL, p, pauseSound(), KX_3DSoundSettings::reference_distance, SCA_IActuator::RemoveAllEvents(), and KX_3DSoundSettings::rolloff_factor.
Member Data Documentation
KX_SOUNDACT_TYPE KX_SoundActuator::m_type
Reimplemented from SCA_IActuator.
Definition at line 85 of file KX_SoundActuator.h.
Referenced by KX_SoundActuator(), and Update().
The documentation for this class was generated from the following files:
KX_SoundActuator.h
KX_SoundActuator.cpp