Blender: scanfill.c File Reference
scanfill.c File Reference
blenlib
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "BLI_callbacks.h"
#include "BLI_listbase.h"
#include "BLI_math.h"
#include "BLI_scanfill.h"
#include "BLI_utildefines.h"
Classes
struct PolyFill
struct ScanFillVertLink
struct mem_elements
Defines
#define SF_EPSILON 0.00003f
#define SF_VERT_UNKNOWN 1
#define SF_VERT_ZERO_LEN 255
#define SF_EDGE_BOUNDARY 1
#define SF_EDGE_UNKNOWN 2
Typedefs
typedef struct PolyFill PolyFill
typedef struct ScanFillVertLink ScanFillVertLink
Functions
void BLI_setErrorCallBack (void(*f)(const char *))
void BLI_setInterruptCallBack (int(*f)(void))
void callLocalErrorCallBack (const char *msg)
static int vergscdata (const void *a1, const void *a2)
static int vergpoly (const void *a1, const void *a2)
static void * mem_element_new (ScanFillContext *sf_ctx, int size)
static void mem_element_reset (ScanFillContext *sf_ctx, int keep_first)
void BLI_end_edgefill (ScanFillContext *sf_ctx)
ScanFillVert * BLI_addfillvert (ScanFillContext *sf_ctx, const float vec[3])
ScanFillEdge * BLI_addfilledge (ScanFillContext *sf_ctx, ScanFillVert *v1, ScanFillVert *v2)
static void addfillface (ScanFillContext *sf_ctx, ScanFillVert *v1, ScanFillVert *v2, ScanFillVert *v3)
static int boundisect (PolyFill *pf2, PolyFill *pf1)
static void mergepolysSimp (ScanFillContext *sf_ctx, PolyFill *pf1, PolyFill *pf2)
static short testedgeside (const float v1[2], const float v2[2], const float v3[2])
static short addedgetoscanvert (ScanFillVertLink *sc, ScanFillEdge *eed)
static ScanFillVertLink * addedgetoscanlist (ScanFillContext *sf_ctx, ScanFillEdge *eed, int len)
static short boundinsideEV (ScanFillEdge *eed, ScanFillVert *eve)
static void testvertexnearedge (ScanFillContext *sf_ctx)
static void splitlist (ScanFillContext *sf_ctx, ListBase *tempve, ListBase *temped, short nr)
static int scanfill (ScanFillContext *sf_ctx, PolyFill *pf)
int BLI_begin_edgefill (ScanFillContext *sf_ctx)
int BLI_edgefill (ScanFillContext *sf_ctx, const short do_quad_tri_speedup)
int BLI_edgefill_ex (ScanFillContext *sf_ctx, const short do_quad_tri_speedup, const float nor_proj[3])
Variables
static void(* BLI_localErrorCallBack)(const char *) = NULL
static int(* BLI_localInterruptCallBack)(void) = NULL
Detailed Description
Definition in file scanfill.c.
Define Documentation
#define SF_EDGE_BOUNDARY 1
Definition at line 103 of file scanfill.c.
Referenced by scanfill().
#define SF_EDGE_UNKNOWN 2
Definition at line 104 of file scanfill.c.
Referenced by scanfill().
#define SF_EPSILON 0.00003f
Definition at line 96 of file scanfill.c.
Referenced by BLI_edgefill_ex(), and testvertexnearedge().
#define SF_VERT_UNKNOWN 1
Definition at line 98 of file scanfill.c.
Referenced by BLI_edgefill_ex(), and scanfill().
#define SF_VERT_ZERO_LEN 255
Definition at line 99 of file scanfill.c.
Referenced by scanfill().
Typedef Documentation
typedef struct PolyFill PolyFill
typedef struct ScanFillVertLink ScanFillVertLink
Function Documentation
static ScanFillVertLink* addedgetoscanlist (ScanFillContext * sf_ctx, ScanFillEdge * eed, int len) [static]
Definition at line 355 of file scanfill.c.
References ScanFillContext::_scdata, addedgetoscanvert(), ScanFillVertLink::v1, ScanFillEdge::v1, ScanFillEdge::v2, vergscdata(), and ScanFillVert::xy.
Referenced by scanfill().
static short addedgetoscanvert (ScanFillVertLink * sc, ScanFillEdge * eed) [static]
Definition at line 308 of file scanfill.c.
References BLI_addtail(), BLI_insertlinkbefore(), ScanFillVertLink::first, ScanFillVertLink::last, ScanFillEdge::next, NULL, ScanFillEdge::prev, ScanFillEdge::v1, ScanFillEdge::v2, and ScanFillVert::xy.
Referenced by addedgetoscanlist().
static void addfillface (ScanFillContext * sf_ctx, ScanFillVert * v1, ScanFillVert * v2, ScanFillVert * v3) [static]
Definition at line 230 of file scanfill.c.
References BLI_addtail(), ScanFillContext::fillfacebase, mem_element_new(), ScanFillFace::v1, ScanFillFace::v2, and ScanFillFace::v3.
Referenced by BLI_edgefill_ex(), and scanfill().
ScanFillEdge* BLI_addfilledge (ScanFillContext * sf_ctx, ScanFillVert * v1, ScanFillVert * v2) [read]
Definition at line 217 of file scanfill.c.
References BLI_addtail(), ScanFillContext::filledgebase, mem_element_new(), ScanFillEdge::v1, and ScanFillEdge::v2.
Referenced by BMEdit_RecalcTessellation_intern(), bmo_triangle_fill_exec(), construct_param_handle(), draw_filled_lasso(), filldisplist(), mesh_recalcTessellation(), scanfill(), and testvertexnearedge().
ScanFillVert* BLI_addfillvert (ScanFillContext * sf_ctx, const float vec[3]) [read]
Definition at line 205 of file scanfill.c.
References BLI_addtail(), ScanFillVert::co, copy_v3_v3(), ScanFillContext::fillvertbase, and mem_element_new().
Referenced by BMEdit_RecalcTessellation_intern(), bmo_triangle_fill_exec(), construct_param_handle(), draw_filled_lasso(), filldisplist(), and mesh_recalcTessellation().
int BLI_begin_edgefill (ScanFillContext * sf_ctx)
Definition at line 767 of file scanfill.c.
Referenced by BMEdit_RecalcTessellation_intern(), bmo_triangle_fill_exec(), construct_param_handle(), draw_filled_lasso(), filldisplist(), and mesh_recalcTessellation().
int BLI_edgefill (ScanFillContext * sf_ctx, const short do_quad_tri_speedup)
Definition at line 774 of file scanfill.c.
References BLI_edgefill_ex(), and NULL.
Referenced by bmo_triangle_fill_exec(), filldisplist(), and mesh_recalcTessellation().
int BLI_edgefill_ex (ScanFillContext * sf_ctx, const short do_quad_tri_speedup, const float nor_proj[3])
Definition at line 779 of file scanfill.c.
References add_newell_cross_v3_v3v3(), addfillface(), axis_dominant_v3(), BLI_movelisttolist(), BLI_remlink(), boundisect(), callLocalErrorCallBack(), ScanFillVert::co, compare_v3v3(), copy_v3_v3(), dot_v3v3(), PolyFill::edges, PolyFill::f, ScanFillVert::f, ScanFillContext::filledgebase, ScanFillContext::fillvertbase, ListBase::first, ScanFillVert::h, ListBase::last, LIKELY, PolyFill::max_xy, MEM_callocN(), MEM_freeN(), mergepolysSimp(), PolyFill::min_xy, ScanFillEdge::next, ScanFillVert::next, normalize_v3(), PolyFill::nr, NULL, pf, ScanFillEdge::poly_nr, ScanFillVert::poly_nr, ScanFillEdge::prev, PRINT2, scanfill(), SF_EPSILON, SF_VERT_UNKNOWN, splitlist(), sub_v3_v3v3(), testvertexnearedge(), UNLIKELY, ScanFillEdge::v1, ScanFillEdge::v2, vergpoly(), PolyFill::verts, ScanFillVert::xy, and zero_v3().
Referenced by BLI_edgefill(), BMEdit_RecalcTessellation_intern(), construct_param_handle(), and draw_filled_lasso().
void BLI_end_edgefill (ScanFillContext * sf_ctx)
Definition at line 194 of file scanfill.c.
References FALSE, ScanFillContext::filledgebase, ScanFillContext::fillfacebase, ScanFillContext::fillvertbase, ListBase::first, ListBase::last, mem_element_reset(), and NULL.
Referenced by BMEdit_RecalcTessellation_intern(), bmo_triangle_fill_exec(), construct_param_handle(), draw_filled_lasso(), filldisplist(), and mesh_recalcTessellation().
void BLI_setErrorCallBack (void(*)(const char *) f)
Set a function taking a char* as argument to flag errors. If the callback is not set, the error is discarded.
Parameters:
f The function to use as callback
Attention:
used in creator.c
Definition at line 50 of file scanfill.c.
References BLI_localErrorCallBack.
Referenced by setCallbacks().
void BLI_setInterruptCallBack (int(*)(void) f)
Set a function to be able to interrupt the execution of processing in this module. If the function returns true, the execution will terminate gracefully. If the callback is not set, interruption is not possible.
Parameters:
f The function to use as callback
Attention:
used in creator.c
Definition at line 55 of file scanfill.c.
References BLI_localInterruptCallBack.
static short boundinsideEV (ScanFillEdge * eed, ScanFillVert * eve) [static]
Definition at line 386 of file scanfill.c.
References ScanFillEdge::v1, ScanFillEdge::v2, and ScanFillVert::xy.
Referenced by testvertexnearedge().
static int boundisect (PolyFill * pf2, PolyFill * pf1) [static]
Definition at line 243 of file scanfill.c.
References PolyFill::edges, PolyFill::max_xy, and PolyFill::min_xy.
Referenced by BLI_edgefill_ex().
void callLocalErrorCallBack (const char * msg)
Definition at line 61 of file scanfill.c.
References BLI_localErrorCallBack.
Referenced by BLI_edgefill_ex().
static void* mem_element_new (ScanFillContext * sf_ctx, int size) [static]
Definition at line 143 of file scanfill.c.
References BLI_addtail(), BLI_assert, mem_elements::data, ScanFillContext::melem__cur, ScanFillContext::melem__lb, ScanFillContext::melem__offs, MEM_callocN(), MEM_ELEM_BLOCKSIZE, and size().
Referenced by addfillface(), BLI_addfilledge(), and BLI_addfillvert().
static void mem_element_reset (ScanFillContext * sf_ctx, int keep_first) [static]
Definition at line 163 of file scanfill.c.
References BLI_addtail(), BLI_freelistN(), BLI_remlink(), mem_elements::data, ListBase::first, ScanFillContext::melem__cur, ScanFillContext::melem__lb, ScanFillContext::melem__offs, MEM_ELEM_BLOCKSIZE, MEM_freeN(), mem_elements::next, and NULL.
Referenced by BLI_end_edgefill().
static void mergepolysSimp (ScanFillContext * sf_ctx, PolyFill * pf1, PolyFill * pf2) [static]
Definition at line 267 of file scanfill.c.
References PolyFill::edges, PolyFill::f, ScanFillContext::filledgebase, ScanFillContext::fillvertbase, ListBase::first, ScanFillVert::next, ScanFillEdge::next, PolyFill::nr, ScanFillEdge::poly_nr, ScanFillVert::poly_nr, and PolyFill::verts.
Referenced by BLI_edgefill_ex().
static int scanfill (ScanFillContext * sf_ctx, PolyFill * pf) [static]
Definition at line 503 of file scanfill.c.
References ScanFillContext::_scdata, addedgetoscanlist(), addfillface(), BLI_addfilledge(), BLI_addtail(), BLI_insertlinkbefore(), BLI_remlink(), equals_v2v2(), ScanFillEdge::f, PolyFill::f, ScanFillVert::f, ScanFillContext::filledgebase, ScanFillContext::fillvertbase, ScanFillVertLink::first, ListBase::first, ScanFillVert::h, ScanFillVertLink::last, MEM_callocN(), MEM_freeN(), minf(), ScanFillEdge::next, ScanFillVert::next, PolyFill::nr, NULL, ScanFillVert::poly_nr, SF_EDGE_BOUNDARY, SF_EDGE_UNKNOWN, SF_VERT_UNKNOWN, SF_VERT_ZERO_LEN, testedgeside(), ScanFillVert::tmp, ScanFillVert::v, ScanFillVertLink::v1, ScanFillEdge::v1, ScanFillEdge::v2, vergscdata(), PolyFill::verts, and ScanFillVert::xy.
Referenced by BLI_edgefill_ex().
static void splitlist (ScanFillContext * sf_ctx, ListBase * tempve, ListBase * temped, short nr) [static]
Definition at line 473 of file scanfill.c.
References BLI_addtail(), BLI_movelisttolist(), BLI_remlink(), ScanFillContext::filledgebase, ScanFillContext::fillvertbase, ListBase::first, ScanFillEdge::next, ScanFillVert::next, ScanFillEdge::poly_nr, and ScanFillVert::poly_nr.
Referenced by BLI_edgefill_ex().
static short testedgeside (const float v1[2], const float v2[2], const float v3[2]) [static]
Definition at line 290 of file scanfill.c.
Referenced by scanfill().
static void testvertexnearedge (ScanFillContext * sf_ctx) [static]
Definition at line 416 of file scanfill.c.
References BLI_addfilledge(), boundinsideEV(), ScanFillVert::co, compare_v3v3(), dist_to_line_v2(), ScanFillEdge::f, ScanFillContext::filledgebase, ScanFillContext::fillvertbase, ListBase::first, ScanFillVert::h, ScanFillEdge::next, ScanFillVert::next, ScanFillEdge::poly_nr, ScanFillVert::poly_nr, SF_EPSILON, ScanFillEdge::v1, ScanFillEdge::v2, and ScanFillVert::xy.
Referenced by BLI_edgefill_ex().
static int vergpoly (const void * a1, const void * a2) [static]
Definition at line 123 of file scanfill.c.
References PolyFill::min_xy.
Referenced by BLI_edgefill_ex().
static int vergscdata (const void * a1, const void * a2) [static]
Definition at line 111 of file scanfill.c.
References ScanFillVertLink::v1, and ScanFillVert::xy.
Referenced by addedgetoscanlist(), and scanfill().
Variable Documentation
void(* BLI_localErrorCallBack)(const char *) = NULL [static]
Definition at line 47 of file scanfill.c.
Referenced by BLI_setErrorCallBack(), and callLocalErrorCallBack().
int(* BLI_localInterruptCallBack)(void) = NULL [static]
Definition at line 48 of file scanfill.c.
Referenced by BLI_setInterruptCallBack().