Blender: suggestions.c File Reference
suggestions.c File Reference
blenkernel
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "MEM_guardedalloc.h"
#include "DNA_text_types.h"
#include "BKE_suggestions.h"
Functions
static int txttl_cmp (const char *first, const char *second, int len)
static void txttl_free_suggest (void)
static void txttl_free_docs (void)
void free_texttools (void)
void texttool_text_set_active (Text *text)
void texttool_text_clear (void)
short texttool_text_is_active (Text *text)
void texttool_suggest_add (const char *name, char type)
void texttool_suggest_prefix (const char *prefix)
void texttool_suggest_clear (void)
SuggItem * texttool_suggest_first (void)
SuggItem * texttool_suggest_last (void)
void texttool_suggest_select (SuggItem *sel)
SuggItem * texttool_suggest_selected (void)
int * texttool_suggest_top (void)
void texttool_docs_show (const char *docs)
char * texttool_docs_get (void)
void texttool_docs_clear (void)
Variables
static Text * activeToolText = NULL
static SuggList suggestions = {NULL, NULL, NULL, NULL, NULL}
static char * documentation = NULL
Detailed Description
Definition in file suggestions.c.
Function Documentation
void free_texttools (void)
Definition at line 86 of file suggestions.c.
References txttl_free_docs(), and txttl_free_suggest().
Referenced by texttool_text_clear().
void texttool_docs_clear (void)
Definition at line 274 of file suggestions.c.
References txttl_free_docs().
Referenced by do_texttools().
char* texttool_docs_get (void)
Definition at line 269 of file suggestions.c.
References documentation.
Referenced by do_texttools(), and draw_documentation().
void texttool_docs_show (const char * docs)
Definition at line 243 of file suggestions.c.
References documentation, len(), MEM_freeN(), MEM_mallocN(), NULL, and strlen().
void texttool_suggest_add (const char * name, char type)
Definition at line 114 of file suggestions.c.
References SuggList::first, SuggList::firstmatch, SuggList::last, SuggList::lastmatch, len(), MEM_mallocN(), SuggItem::name, SuggItem::next, NULL, SuggItem::prev, SuggList::selected, strlen(), SuggList::top, txttl_cmp(), DerivedMesh::type, and SuggItem::type.
void texttool_suggest_clear (void)
Definition at line 209 of file suggestions.c.
References txttl_free_suggest().
Referenced by do_texttools().
SuggItem* texttool_suggest_first (void)
Definition at line 214 of file suggestions.c.
References SuggList::firstmatch.
Referenced by do_texttools(), draw_documentation(), draw_suggestion_list(), text_do_suggest_select(), and text_pop_suggest_list().
SuggItem* texttool_suggest_last (void)
Definition at line 219 of file suggestions.c.
References SuggList::lastmatch.
Referenced by do_texttools(), draw_suggestion_list(), and text_do_suggest_select().
void texttool_suggest_prefix (const char * prefix)
Definition at line 166 of file suggestions.c.
References SuggList::first, SuggList::firstmatch, SuggList::last, SuggList::lastmatch, len(), SuggItem::name, SuggItem::next, NULL, SuggItem::prev, SuggList::selected, strlen(), SuggList::top, and txttl_cmp().
Referenced by get_suggest_prefix().
void texttool_suggest_select (SuggItem * sel)
Definition at line 224 of file suggestions.c.
References SuggList::selected.
Referenced by do_texttools(), and text_do_suggest_select().
SuggItem* texttool_suggest_selected (void)
Definition at line 229 of file suggestions.c.
References SuggList::selected.
Referenced by confirm_suggestion(), do_texttools(), draw_suggestion_list(), and text_pop_suggest_list().
int* texttool_suggest_top (void)
Definition at line 234 of file suggestions.c.
References SuggList::top.
Referenced by draw_suggestion_list(), text_do_suggest_select(), and text_pop_suggest_list().
void texttool_text_clear (void)
Definition at line 99 of file suggestions.c.
References free_texttools(), and NULL.
Referenced by confirm_suggestion(), and texttool_text_set_active().
short texttool_text_is_active (Text * text)
Definition at line 105 of file suggestions.c.
Referenced by confirm_suggestion(), do_texttools(), draw_documentation(), draw_suggestion_list(), get_suggest_prefix(), and text_do_suggest_select().
void texttool_text_set_active (Text * text)
Definition at line 92 of file suggestions.c.
References texttool_text_clear().
static int txttl_cmp (const char * first, const char * second, int len) [static]
Definition at line 50 of file suggestions.c.
References i, and len().
Referenced by texttool_suggest_add(), and texttool_suggest_prefix().
static void txttl_free_docs (void) [static]
Definition at line 74 of file suggestions.c.
References documentation, MEM_freeN(), and NULL.
Referenced by free_texttools(), and texttool_docs_clear().
static void txttl_free_suggest (void) [static]
Definition at line 61 of file suggestions.c.
References SuggList::first, SuggList::firstmatch, SuggList::last, SuggList::lastmatch, MEM_freeN(), NULL, SuggItem::prev, SuggList::selected, and SuggList::top.
Referenced by free_texttools(), and texttool_suggest_clear().
Variable Documentation
Text* activeToolText = NULL [static]
Definition at line 45 of file suggestions.c.
char* documentation = NULL [static]
Definition at line 47 of file suggestions.c.
Referenced by texttool_docs_get(), texttool_docs_show(), and txttl_free_docs().
SuggList suggestions = {NULL, NULL, NULL, NULL, NULL} [static]
Definition at line 46 of file suggestions.c.