Blender: sequencer_buttons.c File Reference
sequencer_buttons.c File Reference
sequencer
#include <string.h>
#include <stdio.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "ED_screen.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "sequencer_intern.h"
Functions
static int sequencer_properties (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_properties (wmOperatorType *ot)
Detailed Description
Definition in file sequencer_buttons.c.
Function Documentation
void SEQUENCER_OT_properties (wmOperatorType * ot)
Definition at line 64 of file sequencer_buttons.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and sequencer_properties().
Referenced by sequencer_operatortypes().
static int sequencer_properties (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 53 of file sequencer_buttons.c.
References CTX_wm_area(), ED_region_toggle_hidden(), OPERATOR_FINISHED, and sequencer_has_buttons_region().
Referenced by SEQUENCER_OT_properties().