Blender: AttributeList Class Reference
AttributeList Class Reference
The list of configuration attributes.
#include <attributes.h>
Public Member Functions
AttributeList (string name)
~AttributeList ()
void addAttr (string name, vector< string > &value, int line, bool isChannel)
bool exists (string name)
void setAllUsed ()
bool checkUnusedParams ()
void import (AttributeList *oal)
int readInt (string name, int defaultValue, string source, string target, bool needed)
bool readBool (string name, bool defaultValue, string source, string target, bool needed)
double readFloat (string name, double defaultValue, string source, string target, bool needed)
string readString (string name, string defaultValue, string source, string target, bool needed)
ntlVec3d readVec3d (string name, ntlVec3d defaultValue, string source, string target, bool needed)
void readMat4Gfx (string name, ntlMatrix4x4< gfxReal > defaultValue, string source, string target, bool needed, ntlMatrix4x4< gfxReal > *mat)
AnimChannel< int > readChannelInt (string name, int defaultValue=0, string source=string("src"), string target=string("dst"), bool needed=false)
AnimChannel< double > readChannelFloat (string name, double defaultValue=0, string source=string("src"), string target=string("dst"), bool needed=false)
AnimChannel< ntlVec3d > readChannelVec3d (string name, ntlVec3d defaultValue=ntlVec3d(0.), string source=string("src"), string target=string("dst"), bool needed=false)
AnimChannel< ntlSetVec3f > readChannelSetVec3f (string name, ntlSetVec3f defaultValue=ntlSetVec3f(0.), string source=string("src"), string target=string("dst"), bool needed=false)
AnimChannel< ntlVec3f > readChannelVec3f (string name, ntlVec3f defaultValue=ntlVec3f(0.), string source=string("src"), string target=string("dst"), bool needed=false)
AnimChannel< float > readChannelSinglePrecFloat (string name, float defaultValue=0., string source=string("src"), string target=string("dst"), bool needed=false)
bool ignoreParameter (string name, string source)
void print ()
debug function, prints all attribs
Detailed Description
The list of configuration attributes.
Definition at line 171 of file attributes.h.
Constructor & Destructor Documentation
AttributeList::AttributeList (string name) [inline]
Definition at line 174 of file attributes.h.
AttributeList::~AttributeList ()
Definition at line 142 of file attributes.cpp.
Member Function Documentation
void AttributeList::addAttr (string name, vector< string > & value, int line, bool isChannel) [inline]
Definition at line 176 of file attributes.h.
bool AttributeList::checkUnusedParams ()
Definition at line 72 of file attributes.cpp.
bool AttributeList::exists (string name) [inline]
Definition at line 179 of file attributes.h.
Referenced by ntlGeometryObject::initialize().
bool AttributeList::ignoreParameter (string name, string source)
Definition at line 108 of file attributes.cpp.
void AttributeList::import (AttributeList * oal)
Definition at line 162 of file attributes.cpp.
References NULL.
void AttributeList::print ()
debug function, prints all attribs
Definition at line 155 of file attributes.cpp.
bool AttributeList::readBool (string name, bool defaultValue, string source, string target, bool needed)
Definition at line 85 of file attributes.cpp.
Referenced by ntlGeometryObject::initialize(), LbmFsgrSolver::parseAttrList(), and LbmSolverInterface::parseStdAttrList().
AnimChannel< double > AttributeList::readChannelFloat (string name, double defaultValue = 0, string source = string("src"), string target = string("dst"), bool needed = false)
Definition at line 118 of file attributes.cpp.
Referenced by ntlGeometryObjModel::initialize(), and Parametrizer::parseAttrList().
AnimChannel< int > AttributeList::readChannelInt (string name, int defaultValue = 0, string source = string("src"), string target = string("dst"), bool needed = false)
Definition at line 114 of file attributes.cpp.
AnimChannel< ntlSetVec3f > AttributeList::readChannelSetVec3f (string name, ntlSetVec3f defaultValue = ntlSetVec3f(0.), string source = string("src"), string target = string("dst"), bool needed = false)
Definition at line 126 of file attributes.cpp.
AnimChannel< float > AttributeList::readChannelSinglePrecFloat (string name, float defaultValue = 0., string source = string("src"), string target = string("dst"), bool needed = false)
Definition at line 130 of file attributes.cpp.
Referenced by ntlGeometryObject::initialize(), and LbmControlData::parseControldataAttrList().
AnimChannel< ntlVec3d > AttributeList::readChannelVec3d (string name, ntlVec3d defaultValue = ntlVec3d(0.), string source = string("src"), string target = string("dst"), bool needed = false)
Definition at line 122 of file attributes.cpp.
Referenced by Parametrizer::parseAttrList().
AnimChannel< ntlVec3f > AttributeList::readChannelVec3f (string name, ntlVec3f defaultValue = ntlVec3f(0.), string source = string("src"), string target = string("dst"), bool needed = false)
Definition at line 134 of file attributes.cpp.
Referenced by ntlGeometryObject::initialize(), and LbmControlData::parseControldataAttrList().
double AttributeList::readFloat (string name, double defaultValue, string source, string target, bool needed)
Definition at line 89 of file attributes.cpp.
Referenced by ntlGeometryObjModel::initialize(), ntlGeometryObject::initialize(), ParticleTracer::parseAttrList(), Parametrizer::parseAttrList(), LbmFsgrSolver::parseAttrList(), LbmControlData::parseControldataAttrList(), and LbmSolverInterface::parseStdAttrList().
int AttributeList::readInt (string name, int defaultValue, string source, string target, bool needed)
Definition at line 81 of file attributes.cpp.
Referenced by ntlGeometryObject::initialize(), SimulationObject::initializeLbmSimulation(), ParticleTracer::parseAttrList(), LbmFsgrSolver::parseAttrList(), LbmControlData::parseControldataAttrList(), and LbmSolverInterface::parseStdAttrList().
void AttributeList::readMat4Gfx (string name, ntlMatrix4x4< gfxReal > defaultValue, string source, string target, bool needed, ntlMatrix4x4< gfxReal > * mat)
Definition at line 102 of file attributes.cpp.
References NULL.
Referenced by LbmSolverInterface::parseStdAttrList().
string AttributeList::readString (string name, string defaultValue, string source, string target, bool needed)
Definition at line 93 of file attributes.cpp.
Referenced by ntlGeometryObjModel::initialize(), ntlGeometryObject::initialize(), SimulationObject::initializeLbmSimulation(), ParticleTracer::parseAttrList(), Parametrizer::parseAttrList(), LbmFsgrSolver::parseAttrList(), LbmControlData::parseControldataAttrList(), LbmSolverInterface::parseStdAttrList(), and LbmSolverInterface::readBoundaryFlagInt().
ntlVec3d AttributeList::readVec3d (string name, ntlVec3d defaultValue, string source, string target, bool needed)
Definition at line 97 of file attributes.cpp.
Referenced by ntlGeometryObject::initialize(), LbmControlData::parseControldataAttrList(), and LbmSolverInterface::parseStdAttrList().
void AttributeList::setAllUsed ()
Definition at line 75 of file attributes.cpp.
Referenced by SimulationObject::initializeLbmSimulation().
The documentation for this class was generated from the following files:
attributes.h
attributes.cpp