Blender: btQuantization.h File Reference
btQuantization.h File Reference
#include "LinearMath/btTransform.h"
Functions
SIMD_FORCE_INLINE void bt_calc_quantization_parameters (btVector3 &outMinBound, btVector3 &outMaxBound, btVector3 &bvhQuantization, const btVector3 &srcMinBound, const btVector3 &srcMaxBound, btScalar quantizationMargin)
SIMD_FORCE_INLINE void bt_quantize_clamp (unsigned short *out, const btVector3 &point, const btVector3 &min_bound, const btVector3 &max_bound, const btVector3 &bvhQuantization)
SIMD_FORCE_INLINE btVector3 bt_unquantize (const unsigned short *vecIn, const btVector3 &offset, const btVector3 &bvhQuantization)
Detailed Description
Author:
Francisco Leon Najera
Definition in file btQuantization.h.
Function Documentation
SIMD_FORCE_INLINE void bt_calc_quantization_parameters (btVector3 & outMinBound, btVector3 & outMaxBound, btVector3 & bvhQuantization, const btVector3 & srcMinBound, const btVector3 & srcMaxBound, btScalar quantizationMargin)
Definition at line 35 of file btQuantization.h.
Referenced by btQuantizedBvhTree::calc_quantization().
SIMD_FORCE_INLINE void bt_quantize_clamp (unsigned short * out, const btVector3 & point, const btVector3 & min_bound, const btVector3 & max_bound, const btVector3 & bvhQuantization)
Definition at line 53 of file btQuantization.h.
Referenced by btQuantizedBvhTree::quantizePoint(), and btQuantizedBvhTree::setNodeBound().
SIMD_FORCE_INLINE btVector3 bt_unquantize (const unsigned short * vecIn, const btVector3 & offset, const btVector3 & bvhQuantization)
Definition at line 72 of file btQuantization.h.
Referenced by btQuantizedBvhTree::getNodeBound().