Blender: btTypedConstraint.h File Reference
btTypedConstraint.h File Reference
#include "LinearMath/btScalar.h"
#include "btSolverConstraint.h"
Classes
class btTypedConstraint
TypedConstraint is the baseclass for Bullet constraints and vehicles.
struct btTypedConstraint::btConstraintInfo1
struct btTypedConstraint::btConstraintInfo2
struct btTypedConstraintData
do not change those serialization structures, it requires an updated sBulletDNAstr/sBulletDNAstr64
class btAngularLimit
Defines
#define btAssertConstrParams(_par) btAssert(_par)
Enumerations
enum btTypedConstraintType {
POINT2POINT_CONSTRAINT_TYPE = 3, HINGE_CONSTRAINT_TYPE, CONETWIST_CONSTRAINT_TYPE, D6_CONSTRAINT_TYPE,
SLIDER_CONSTRAINT_TYPE, CONTACT_CONSTRAINT_TYPE, D6_SPRING_CONSTRAINT_TYPE, MAX_CONSTRAINT_TYPE
}
enum btConstraintParams { BT_CONSTRAINT_ERP = 1, BT_CONSTRAINT_STOP_ERP, BT_CONSTRAINT_CFM, BT_CONSTRAINT_STOP_CFM }
Functions
SIMD_FORCE_INLINE btScalar btAdjustAngleToLimits (btScalar angleInRadians, btScalar angleLowerLimitInRadians, btScalar angleUpperLimitInRadians)
Define Documentation
#define btAssertConstrParams (_par) btAssert(_par)
Definition at line 48 of file btTypedConstraint.h.
Referenced by btSliderConstraint::getParam(), btGeneric6DofConstraint::getParam(), btConeTwistConstraint::getParam(), btConeTwistConstraint::setParam(), btSliderConstraint::setParam(), and btGeneric6DofConstraint::setParam().
Enumeration Type Documentation
enum btConstraintParams
Enumerator:
BT_CONSTRAINT_ERP
BT_CONSTRAINT_STOP_ERP
BT_CONSTRAINT_CFM
BT_CONSTRAINT_STOP_CFM
Definition at line 39 of file btTypedConstraint.h.
enum btTypedConstraintType
Enumerator:
POINT2POINT_CONSTRAINT_TYPE
HINGE_CONSTRAINT_TYPE
CONETWIST_CONSTRAINT_TYPE
D6_CONSTRAINT_TYPE
SLIDER_CONSTRAINT_TYPE
CONTACT_CONSTRAINT_TYPE
D6_SPRING_CONSTRAINT_TYPE
MAX_CONSTRAINT_TYPE
Definition at line 26 of file btTypedConstraint.h.
Function Documentation
SIMD_FORCE_INLINE btScalar btAdjustAngleToLimits (btScalar angleInRadians, btScalar angleLowerLimitInRadians, btScalar angleUpperLimitInRadians)
Definition at line 265 of file btTypedConstraint.h.
References btFabs(), btNormalizeAngle(), and SIMD_2_PI.
Referenced by btSliderConstraint::testAngLimits(), and btGeneric6DofConstraint::testAngularLimitMotor().