Blender: IK_QOrientationTask Class Reference
IK_QOrientationTask Class Reference
#include <IK_QTask.h>
Public Member Functions
IK_QOrientationTask (bool primary, const IK_QSegment *segment, const MT_Matrix3x3 &goal)
MT_Scalar Distance () const
void ComputeJacobian (IK_QJacobian &jacobian)
Detailed Description
Definition at line 113 of file IK_QTask.h.
Constructor & Destructor Documentation
IK_QOrientationTask::IK_QOrientationTask (bool primary, const IK_QSegment * segment, const MT_Matrix3x3 & goal)
Definition at line 115 of file IK_QTask.cpp.
Member Function Documentation
void IK_QOrientationTask::ComputeJacobian (IK_QJacobian & jacobian) [virtual]
Implements IK_QTask.
Definition at line 124 of file IK_QTask.cpp.
References IK_QSegment::Axis(), IK_QSegment::DoFId(), MT_Transform::getBasis(), IK_QSegment::GlobalTransform(), i, MT_Vector3::length(), IK_QTask::m_id, IK_QTask::m_segment, IK_QTask::m_size, IK_QTask::m_weight, IK_QSegment::NumberOfDoF(), IK_QSegment::Parent(), rot, IK_QJacobian::SetBetas(), IK_QJacobian::SetDerivatives(), IK_QSegment::Translational(), MT_Matrix3x3::transpose(), and MT_Matrix3x3::transposed().
MT_Scalar IK_QOrientationTask::Distance () const [inline, virtual]
Implements IK_QTask.
Definition at line 122 of file IK_QTask.h.
The documentation for this class was generated from the following files:
IK_QTask.h
IK_QTask.cpp