Blender: MaterialFunctor Struct Reference
MaterialFunctor Struct Reference
#include <MaterialExporter.h>
Public Member Functions
template<class Functor >
void forEachMaterialInScene (Scene *sce, Functor &f, bool export_selected)
Detailed Description
Definition at line 87 of file MaterialExporter.h.
Member Function Documentation
template<class Functor > void MaterialFunctor::forEachMaterialInScene (Scene * sce, Functor & f, bool export_selected) [inline]
Definition at line 92 of file MaterialExporter.h.
References GeometryFunctor::forEachMeshObjectInScene().
Referenced by EffectsExporter::exportEffects(), ImagesExporter::exportImages(), and MaterialsExporter::exportMaterials().
The documentation for this struct was generated from the following file:
MaterialExporter.h