Blender: BL_Action Class Reference
BL_Action Class Reference
#include <BL_Action.h>
Public Types
enum { ACT_MODE_PLAY = 0, ACT_MODE_LOOP, ACT_MODE_PING_PONG, ACT_MODE_MAX }
enum { ACT_IPOFLAG_FORCE = 1, ACT_IPOFLAG_LOCAL = 2, ACT_IPOFLAG_ADD = 4, ACT_IPOFLAG_CHILD = 8 }
Public Member Functions
BL_Action (class KX_GameObject *gameobj)
~BL_Action ()
bool Play (const char *name, float start, float end, short priority, float blendin, short play_mode, float layer_weight, short ipo_flags, float playback_speed)
void Stop ()
bool IsDone ()
void Update (float curtime)
float GetFrame ()
struct bAction * GetAction ()
void SetFrame (float frame)
void SetPlayMode (short play_mode)
void SetTimes (float start, float end)
Detailed Description
Definition at line 38 of file BL_Action.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
ACT_MODE_PLAY
ACT_MODE_LOOP
ACT_MODE_PING_PONG
ACT_MODE_MAX
Definition at line 118 of file BL_Action.h.
anonymous enum
Enumerator:
ACT_IPOFLAG_FORCE
ACT_IPOFLAG_LOCAL
ACT_IPOFLAG_ADD
ACT_IPOFLAG_CHILD
Definition at line 126 of file BL_Action.h.
Constructor & Destructor Documentation
BL_Action::BL_Action (class KX_GameObject * gameobj)
Definition at line 49 of file BL_Action.cpp.
References BL_ArmatureObject::GetArmatureObject(), BL_DeformableGameObject::GetDeformer(), SCA_IObject::GetGameObjectType(), BL_ShapeDeformer::GetKey(), Key::id, Object::id, SCA_IObject::OBJ_ARMATURE, and RNA_id_pointer_create().
BL_Action::~BL_Action ()
Definition at line 91 of file BL_Action.cpp.
References game_free_pose().
Member Function Documentation
bAction * BL_Action::GetAction () [read]
Definition at line 238 of file BL_Action.cpp.
References IsDone(), and NULL.
Referenced by BL_ActionManager::GetCurrentAction().
float BL_Action::GetFrame ()
Definition at line 243 of file BL_Action.cpp.
Referenced by BL_ActionManager::GetActionFrame().
bool BL_Action::IsDone ()
Whether or not the action is still playing
Definition at line 220 of file BL_Action.cpp.
Referenced by GetAction(), BL_ActionManager::IsActionDone(), and Play().
bool BL_Action::Play (const char * name, float start, float end, short priority, float blendin, short play_mode, float layer_weight, short ipo_flags, float playback_speed)
Play an action
Definition at line 117 of file BL_Action.cpp.
References SG_IObject::AddSGController(), BL_CreateCameraIPO(), BL_CreateIPO(), BL_CreateLampIPO(), Key::block, KeyBlock::curval, ListBase::first, SCA_LogicManager::GetActionByName(), BL_DeformableGameObject::GetDeformer(), KX_KetsjiEngine::GetFrameTime(), SCA_IObject::GetGameObjectType(), BL_ShapeDeformer::GetKey(), KX_Scene::GetLogicManager(), BL_ArmatureObject::GetMRDPose(), KX_GameObject::GetSGNode(), BL_DeformableGameObject::GetShape(), IsDone(), KX_GetActiveEngine(), KX_GetActiveScene(), KeyBlock::next, SCA_IObject::OBJ_ARMATURE, SCA_IObject::OBJ_CAMERA, SCA_IObject::OBJ_LIGHT, and SG_Controller::SetObject().
Referenced by BL_ActionManager::PlayAction().
void BL_Action::SetFrame (float frame)
Definition at line 248 of file BL_Action.cpp.
References max, and min.
Referenced by BL_ActionManager::SetActionFrame().
void BL_Action::SetPlayMode (short play_mode)
Definition at line 260 of file BL_Action.cpp.
Referenced by BL_ActionManager::SetPlayMode().
void BL_Action::SetTimes (float start, float end)
Definition at line 265 of file BL_Action.cpp.
Referenced by BL_ActionManager::SetTimes().
void BL_Action::Stop ()
Stop playing the action
Definition at line 215 of file BL_Action.cpp.
Referenced by BL_ActionManager::StopAction().
void BL_Action::Update (float curtime)
Update the action's frame, etc.
Definition at line 323 of file BL_Action.cpp.
References ACT_IPOFLAG_CHILD, ACT_MODE_LOOP, ACT_MODE_PING_PONG, ACT_MODE_PLAY, animsys_evaluate_action(), Key::block, KeyBlock::curval, ListBase::first, game_blend_poses(), BL_ArmatureObject::GetArmatureObject(), BL_DeformableGameObject::GetDeformer(), SCA_IObject::GetGameObjectType(), BL_ShapeDeformer::GetKey(), BL_ArmatureObject::GetMRDPose(), BL_ArmatureObject::GetPose(), BL_DeformableGameObject::GetShape(), KX_KetsjiEngine::GetSuspendedDelta(), max, min, KeyBlock::next, NULL, SCA_IObject::OBJ_ARMATURE, Object::pose, BL_ArmatureObject::SetActiveAction(), BL_DeformableGameObject::SetActiveAction(), BL_ArmatureObject::SetPose(), and KX_GameObject::UpdateIPO().
Referenced by BL_ActionManager::Update().
The documentation for this class was generated from the following files:
BL_Action.h
BL_Action.cpp