Blender: RAS_BucketManager Class Reference
RAS_BucketManager Class Reference
#include <RAS_BucketManager.h>
Classes
struct backtofront
struct fronttoback
struct sortedmeshslot
Public Member Functions
RAS_BucketManager ()
virtual ~RAS_BucketManager ()
void Renderbuckets (const MT_Transform &cameratrans, RAS_IRasterizer *rasty, RAS_IRenderTools *rendertools)
RAS_MaterialBucket * FindBucket (RAS_IPolyMaterial *material, bool &bucketCreated)
void OptimizeBuckets (MT_Scalar distance)
void ReleaseDisplayLists (RAS_IPolyMaterial *material=NULL)
void ReleaseMaterials (RAS_IPolyMaterial *material=NULL)
void RemoveMaterial (RAS_IPolyMaterial *mat)
void MergeBucketManager (RAS_BucketManager *other, SCA_IScene *scene)
BucketList & GetSolidBuckets ()
BucketList & GetAlphaBuckets ()
Detailed Description
Definition at line 41 of file RAS_BucketManager.h.
Constructor & Destructor Documentation
RAS_BucketManager::RAS_BucketManager ()
Definition at line 90 of file RAS_BucketManager.cpp.
RAS_BucketManager::~RAS_BucketManager () [virtual]
Definition at line 95 of file RAS_BucketManager.cpp.
Member Function Documentation
RAS_MaterialBucket * RAS_BucketManager::FindBucket (RAS_IPolyMaterial * material, bool & bucketCreated)
Definition at line 241 of file RAS_BucketManager.cpp.
References RAS_MaterialBucket::IsAlpha().
Referenced by KX_Scene::FindBucket().
BucketList& RAS_BucketManager::GetAlphaBuckets () [inline]
Definition at line 69 of file RAS_BucketManager.h.
Referenced by MergeBucketManager().
BucketList& RAS_BucketManager::GetSolidBuckets () [inline]
Definition at line 68 of file RAS_BucketManager.h.
Referenced by MergeBucketManager().
void RAS_BucketManager::MergeBucketManager (RAS_BucketManager * other, SCA_IScene * scene)
Definition at line 353 of file RAS_BucketManager.cpp.
References GetAlphaBuckets(), and GetSolidBuckets().
Referenced by KX_Scene::MergeScene().
void RAS_BucketManager::OptimizeBuckets (MT_Scalar distance)
Definition at line 266 of file RAS_BucketManager.cpp.
Referenced by BL_ConvertBlenderObjects().
void RAS_BucketManager::ReleaseDisplayLists (RAS_IPolyMaterial * material = NULL)
Definition at line 278 of file RAS_BucketManager.cpp.
References NULL.
void RAS_BucketManager::ReleaseMaterials (RAS_IPolyMaterial * material = NULL)
Definition at line 306 of file RAS_BucketManager.cpp.
References NULL.
void RAS_BucketManager::RemoveMaterial (RAS_IPolyMaterial * mat)
Definition at line 325 of file RAS_BucketManager.cpp.
References RAS_MaterialBucket::GetPolyMaterial(), and i.
void RAS_BucketManager::Renderbuckets (const MT_Transform & cameratrans, RAS_IRasterizer * rasty, RAS_IRenderTools * rendertools)
Definition at line 229 of file RAS_BucketManager.cpp.
References RAS_IRasterizer::ClearCachingInfo(), NULL, and RAS_IRenderTools::SetClientObject().
Referenced by KX_Scene::RenderBuckets().
The documentation for this class was generated from the following files:
RAS_BucketManager.h
RAS_BucketManager.cpp