Blender: wm_init_exit.c File Reference
wm_init_exit.c File Reference
windowmanager
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "MEM_CacheLimiterC-Api.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_userdef_types.h"
#include "DNA_windowmanager_types.h"
#include "BKE_blender.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "BKE_curve.h"
#include "BKE_displist.h"
#include "BKE_DerivedMesh.h"
#include "BKE_font.h"
#include "BKE_global.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_mball.h"
#include "BKE_report.h"
#include "BKE_packedFile.h"
#include "BKE_sequencer.h"
#include "BKE_material.h"
#include "BKE_tracking.h"
#include "BLI_listbase.h"
#include "BLI_string.h"
#include "BLI_utildefines.h"
#include "RE_engine.h"
#include "RE_pipeline.h"
#include "GHOST_Path-api.h"
#include "GHOST_C-api.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "wm_cursors.h"
#include "wm_event_system.h"
#include "wm.h"
#include "wm_files.h"
#include "wm_window.h"
#include "ED_armature.h"
#include "ED_keyframing.h"
#include "ED_node.h"
#include "ED_render.h"
#include "ED_space_api.h"
#include "ED_screen.h"
#include "ED_util.h"
#include "UI_interface.h"
#include "BLF_api.h"
#include "BLF_translation.h"
#include "GPU_buffers.h"
#include "GPU_extensions.h"
#include "GPU_draw.h"
#include "BKE_depsgraph.h"
#include "BKE_sound.h"
Functions
static void wm_init_reports (bContext *C)
static void wm_free_reports (bContext *C)
void WM_init (bContext *C, int argc, const char **argv)
void WM_init_splash (bContext *C)
int WM_init_game (bContext *C)
static void free_openrecent (void)
void free_anim_copybuf (void)
void free_anim_drivers_copybuf (void)
void free_fmodifiers_copybuf (void)
void free_posebuf (void)
void WM_exit_ext (bContext *C, const short do_python)
void WM_exit (bContext *C)
Variables
int wm_start_with_console = 0
Detailed Description
Definition in file wm_init_exit.c.
Function Documentation
void free_anim_copybuf (void)
Definition at line 480 of file keyframes_general.c.
References animcopy_firstframe, animcopy_lastframe, tAnimCopybufItem::bezt, BLI_freelinkN(), ListBase::first, ListBase::last, MEM_freeN(), tAnimCopybufItem::next, NULL, and tAnimCopybufItem::rna_path.
Referenced by copy_action_keys(), copy_animedit_keys(), copy_graph_keys(), and WM_exit_ext().
void free_anim_drivers_copybuf (void)
Definition at line 284 of file drivers.c.
References free_fcurve(), and NULL.
Referenced by ANIM_copy_driver(), and WM_exit_ext().
void free_fmodifiers_copybuf (void)
Definition at line 772 of file fmodifier_ui.c.
References free_fmodifiers().
Referenced by graph_fmodifier_copy_exec(), nla_fmodifier_copy_exec(), and WM_exit_ext().
static void free_openrecent (void) [static]
Definition at line 307 of file wm_init_exit.c.
References BLI_freelistN(), RecentFile::filepath, G, MEM_freeN(), and RecentFile::next.
Referenced by WM_exit_ext().
void free_posebuf (void)
Definition at line 965 of file poseobject.c.
References BLI_freelistN(), bPose::chanbase, ListBase::first, IDP_FreeProperty(), MEM_freeN(), bPoseChannel::next, NULL, tPoseLib_Backup::pchan, and bPoseChannel::prop.
Referenced by pose_copy_exec(), and WM_exit_ext().
void WM_exit (bContext * C)
Definition at line 456 of file wm_init_exit.c.
References G, and WM_exit_ext().
Referenced by ghost_event_proc(), main(), wm_exit_blender_op(), and wm_window_close().
void WM_exit_ext (bContext * C, const short do_python)
Definition at line 328 of file wm_init_exit.c.
References ANIM_keyingset_infos_exit(), BIF_freeTemplates(), BKE_freecubetable(), BKE_reset_undo(), BKE_tracking_free_clipboard(), BKE_undo_save_quit(), BKE_userdef_free(), BLF_exit(), BPY_python_end(), CTX_free(), CTX_wm_manager(), CTX_wm_window_set(), ED_editors_exit(), ED_file_exit(), ED_preview_free_dbase(), ED_screen_exit(), free_anim_copybuf(), free_anim_drivers_copybuf(), free_blender(), free_fmodifiers_copybuf(), free_openrecent(), free_posebuf(), free_ttfont(), G, G_DEBUG, GHOST_DisposeSystemPaths(), GPU_extensions_exit(), GPU_free_unused_buffers(), GPU_global_buffer_pool_free(), wmWindow::handlers, MEM_get_memory_blocks_in_use(), MEM_printmemlist(), wmWindow::modalhandlers, wmWindow::next, RE_engines_exit(), RE_FreeAllRender(), RNA_exit(), wmWindow::screen, seq_free_clipboard(), sound_exit(), SYS_DeleteSystem(), SYS_GetSystem(), UI_exit(), wm_autosave_delete(), wm_dropbox_free(), WM_event_remove_handlers(), wm_free_reports(), wm_ghost_exit(), WM_jobs_stop_all(), WM_menutype_free(), and wm_operatortype_free().
Referenced by bpy_atexit(), and WM_exit().
static void wm_free_reports (bContext * C) [static]
Definition at line 117 of file wm_init_exit.c.
References BKE_reports_clear(), and CTX_wm_reports().
Referenced by WM_exit_ext().
void WM_init (bContext * C, int argc, const char ** argv)
Definition at line 125 of file wm_init_exit.c.
References BLF_init(), BLF_lang_init(), BLF_lang_set(), BLI_getDefaultDocumentFolder(), BLI_make_file_string(), BLI_strncpy(), BPY_app_handlers_reset(), BPY_context_set(), BPY_driver_reset(), BPY_modules_load_user(), BPY_python_start(), clear_matcopybuf(), DAG_editors_update_cb(), ED_file_init(), ED_init_node_butfuncs(), ED_preview_init_dbase(), ED_render_clear_mtex_copybuf(), ED_render_id_flush_update(), ED_render_scene_update(), ED_spacetypes_init(), FALSE, FILE_MAX, G, GHOST_CreateSystemPaths(), GHOST_toggleConsole(), GPU_extensions_init(), GPU_set_anisotropic(), GPU_set_mipmap(), NULL, set_blender_test_break_cb(), set_free_windowmanager_cb(), UI_init(), USER_DISABLE_MIPMAP, wm_close_and_free(), wm_ghost_init(), wm_init_cursor_data(), wm_init_reports(), WM_menutype_init(), wm_operatortype_init(), WM_read_history(), WM_read_homefile(), wm_start_with_console, and wm_window_testbreak().
Referenced by main().
int WM_init_game (bContext * C)
Definition at line 217 of file wm_init_exit.c.
References ARegion::alignment, BKE_area_find_region_type(), BKE_report(), BKE_screen_find_big_area(), CTX_data_main(), CTX_data_scene(), CTX_wm_area_set(), CTX_wm_manager(), CTX_wm_region_set(), CTX_wm_screen(), CTX_wm_window(), CTX_wm_window_set(), wmTimer::customdata, ED_region_toggle_hidden(), ED_screen_full_toggle(), ListBase::first, ARegion::flag, ScrArea::full, GAME_PLAYER_FULLSCREEN, GHOST_DisposeRectangle(), GHOST_GetClientBounds(), GHOST_GetHeightRectangle(), GHOST_GetWidthRectangle(), wmWindow::ghostwin, Scene::gm, MEM_callocN(), ARegion::next, NULL, GameData::playerflag, ScrArea::regionbase, ARegion::regiontype, wmWindowManager::reports, ReportList::reporttimer, RGN_ALIGN_QSPLIT, RGN_FLAG_HIDDEN, RGN_TYPE_WINDOW, RPT_ERROR, Main::scene, sound_exit(), SPACE_VIEW3D, TIMER, wmWindowManager::windows, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_timer(), WM_event_remove_timer(), wm_get_screensize(), WM_OP_EXEC_DEFAULT, WM_operator_name_call(), rcti::xmax, and rcti::ymax.
Referenced by main().
static void wm_init_reports (bContext * C) [static]
Definition at line 113 of file wm_init_exit.c.
References BKE_reports_init(), CTX_wm_reports(), and RPT_STORE.
Referenced by WM_init().
void WM_init_splash (bContext * C)
Definition at line 203 of file wm_init_exit.c.
References CTX_wm_manager(), CTX_wm_window(), CTX_wm_window_set(), ListBase::first, NULL, USER_SPLASH_DISABLE, wmWindowManager::windows, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by main().
Variable Documentation
int wm_start_with_console = 0
Definition at line 122 of file wm_init_exit.c.
Referenced by WM_init().