Blender: btCollisionAlgorithm Class Reference
btCollisionAlgorithm Class Reference
#include <btCollisionAlgorithm.h>
Public Member Functions
btCollisionAlgorithm ()
btCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo &ci)
virtual ~btCollisionAlgorithm ()
virtual void processCollision (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)=0
virtual btScalar calculateTimeOfImpact (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)=0
virtual void getAllContactManifolds (btManifoldArray &manifoldArray)=0
Protected Attributes
btDispatcher * m_dispatcher
Detailed Description
btCollisionAlgorithm is an collision interface that is compatible with the Broadphase and btDispatcher. It is persistent over frames
Definition at line 54 of file btCollisionAlgorithm.h.
Constructor & Destructor Documentation
btCollisionAlgorithm::btCollisionAlgorithm () [inline]
Definition at line 66 of file btCollisionAlgorithm.h.
btCollisionAlgorithm::btCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo & ci)
Definition at line 19 of file btCollisionAlgorithm.cpp.
References m_dispatcher, and btCollisionAlgorithmConstructionInfo::m_dispatcher1.
virtual btCollisionAlgorithm::~btCollisionAlgorithm () [inline, virtual]
Definition at line 70 of file btCollisionAlgorithm.h.
Referenced by btCollisionWorld::contactPairTest(), btGImpactCollisionAlgorithm::destroyConvexAlgorithm(), btSingleContactCallback::process(), btSoftBodyTriangleCallback::processTriangle(), btConvexTriangleCallback::processTriangle(), and btGImpactCollisionAlgorithm::shape_vs_shape_collision().
Member Function Documentation
virtual btScalar btCollisionAlgorithm::calculateTimeOfImpact (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [pure virtual]
Implemented in btBox2dBox2dCollisionAlgorithm, btBoxBoxCollisionAlgorithm, btCompoundCollisionAlgorithm, btConvex2dConvex2dAlgorithm, btConvexConcaveCollisionAlgorithm, btConvexConvexAlgorithm, btConvexPlaneCollisionAlgorithm, btEmptyAlgorithm, btSphereBoxCollisionAlgorithm, btSphereSphereCollisionAlgorithm, btSphereTriangleCollisionAlgorithm, btGImpactCollisionAlgorithm, btSoftBodyConcaveCollisionAlgorithm, btSoftRigidCollisionAlgorithm, and btSoftSoftCollisionAlgorithm.
virtual void btCollisionAlgorithm::getAllContactManifolds (btManifoldArray & manifoldArray) [pure virtual]
Implemented in btBox2dBox2dCollisionAlgorithm, btBoxBoxCollisionAlgorithm, btCompoundCollisionAlgorithm, btConvex2dConvex2dAlgorithm, btConvexConcaveCollisionAlgorithm, btConvexConvexAlgorithm, btConvexPlaneCollisionAlgorithm, btEmptyAlgorithm, btSphereBoxCollisionAlgorithm, btSphereSphereCollisionAlgorithm, btSphereTriangleCollisionAlgorithm, btGImpactCollisionAlgorithm, btSoftBodyConcaveCollisionAlgorithm, btSoftRigidCollisionAlgorithm, and btSoftSoftCollisionAlgorithm.
virtual void btCollisionAlgorithm::processCollision (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [pure virtual]
Implemented in btBox2dBox2dCollisionAlgorithm, btBoxBoxCollisionAlgorithm, btCompoundCollisionAlgorithm, btConvex2dConvex2dAlgorithm, btConvexConcaveCollisionAlgorithm, btConvexConvexAlgorithm, btConvexPlaneCollisionAlgorithm, btEmptyAlgorithm, btSphereBoxCollisionAlgorithm, btSphereSphereCollisionAlgorithm, btSphereTriangleCollisionAlgorithm, btGImpactCollisionAlgorithm, btSoftBodyConcaveCollisionAlgorithm, btSoftRigidCollisionAlgorithm, and btSoftSoftCollisionAlgorithm.
Referenced by btCollisionWorld::contactPairTest(), btGImpactCollisionAlgorithm::convex_vs_convex_collision(), btSingleContactCallback::process(), btCompoundLeafCallback::ProcessChildShape(), btSoftBodyTriangleCallback::processTriangle(), btConvexTriangleCallback::processTriangle(), and btGImpactCollisionAlgorithm::shape_vs_shape_collision().
Member Data Documentation
btDispatcher* btCollisionAlgorithm::m_dispatcher [protected]
Definition at line 59 of file btCollisionAlgorithm.h.
Referenced by btBox2dBox2dCollisionAlgorithm::btBox2dBox2dCollisionAlgorithm(), btBoxBoxCollisionAlgorithm::btBoxBoxCollisionAlgorithm(), btCollisionAlgorithm(), btConvexPlaneCollisionAlgorithm::btConvexPlaneCollisionAlgorithm(), btSphereBoxCollisionAlgorithm::btSphereBoxCollisionAlgorithm(), btSphereSphereCollisionAlgorithm::btSphereSphereCollisionAlgorithm(), btSphereTriangleCollisionAlgorithm::btSphereTriangleCollisionAlgorithm(), btGImpactCollisionAlgorithm::destroyContactManifolds(), btGImpactCollisionAlgorithm::destroyConvexAlgorithm(), btGImpactCollisionAlgorithm::newAlgorithm(), btGImpactCollisionAlgorithm::newContactManifold(), btConvexConvexAlgorithm::processCollision(), btConvex2dConvex2dAlgorithm::processCollision(), btCompoundCollisionAlgorithm::processCollision(), btGImpactCollisionAlgorithm::shape_vs_shape_collision(), btBox2dBox2dCollisionAlgorithm::~btBox2dBox2dCollisionAlgorithm(), btBoxBoxCollisionAlgorithm::~btBoxBoxCollisionAlgorithm(), btConvex2dConvex2dAlgorithm::~btConvex2dConvex2dAlgorithm(), btConvexConvexAlgorithm::~btConvexConvexAlgorithm(), btConvexPlaneCollisionAlgorithm::~btConvexPlaneCollisionAlgorithm(), btSphereBoxCollisionAlgorithm::~btSphereBoxCollisionAlgorithm(), btSphereSphereCollisionAlgorithm::~btSphereSphereCollisionAlgorithm(), and btSphereTriangleCollisionAlgorithm::~btSphereTriangleCollisionAlgorithm().
The documentation for this class was generated from the following files:
btCollisionAlgorithm.h
btCollisionAlgorithm.cpp