Blender: node_composite_lensdist.c File Reference
node_composite_lensdist.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void lensDistort (CompBuf *dst, CompBuf *src, float kr, float kg, float kb, int jit, int proj, int fit)
static void node_composit_exec_lensdist (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_lensdist (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_lensdist (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_lensdist_in []
static bNodeSocketTemplate cmp_node_lensdist_out []
Detailed Description
Definition in file node_composite_lensdist.c.
Function Documentation
static void lensDistort (CompBuf * dst, CompBuf * src, float kr, float kg, float kb, int jit, int proj, int fit) [static]
Definition at line 47 of file node_composite_lensdist.c.
References BLI_frand(), CB_VAL, dupalloc_compbuf(), free_compbuf(), IIR_gauss(), MAX3(), qd_getPixelLerp(), qd_getPixelLerpChan(), CompBuf::rect, sqrtf, CompBuf::type, tz, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_lensdist().
static void node_composit_exec_lensdist (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 166 of file node_composite_lensdist.c.
References alloc_compbuf(), CB_RGBA, bNodeStack::data, NodeLensDist::fit, NodeLensDist::jit, lensDistort(), MAX2, MIN2, NULL, NodeLensDist::proj, bNode::storage, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_lensdist().
static void node_composit_init_lensdist (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 185 of file node_composite_lensdist.c.
References NodeLensDist::fit, NodeLensDist::jit, MEM_callocN(), NodeLensDist::proj, and bNode::storage.
Referenced by register_node_type_cmp_lensdist().
void register_node_type_cmp_lensdist (bNodeTreeType * ttype)
Definition at line 193 of file node_composite_lensdist.c.
References CMP_NODE_LENSDIST, NODE_CLASS_DISTORT, node_composit_exec_lensdist(), node_composit_init_lensdist(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_lensdist_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   SOCK_FLOAT, 1, "Distort",   0.f, 0.f, 0.f, 0.f, -0.999f, 1.f, PROP_NONE},
    {   SOCK_FLOAT, 1, "Dispersion", 0.f, 0.f, 0.f, 0.f, 0.f, 1.f, PROP_NONE},
    {   -1, 0, ""   }
}
Definition at line 35 of file node_composite_lensdist.c.
bNodeSocketTemplate cmp_node_lensdist_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 41 of file node_composite_lensdist.c.