Blender: mball_intern.h File Reference
mball_intern.h File Reference
metaball
#include "DNA_object_types.h"
#include "DNA_windowmanager_types.h"
Functions
void MBALL_OT_hide_metaelems (struct wmOperatorType *ot)
void MBALL_OT_reveal_metaelems (struct wmOperatorType *ot)
void MBALL_OT_delete_metaelems (struct wmOperatorType *ot)
void MBALL_OT_duplicate_metaelems (struct wmOperatorType *ot)
void MBALL_OT_select_all (struct wmOperatorType *ot)
void MBALL_OT_select_random_metaelems (struct wmOperatorType *ot)
Detailed Description
Definition in file mball_intern.h.
Function Documentation
void MBALL_OT_delete_metaelems (struct wmOperatorType * ot)
Definition at line 320 of file mball_edit.c.
References delete_metaelems_exec(), wmOperatorType::description, ED_operator_editmball(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_metaball().
void MBALL_OT_duplicate_metaelems (struct wmOperatorType * ot)
Definition at line 274 of file mball_edit.c.
References wmOperatorType::description, duplicate_metaelems_exec(), duplicate_metaelems_invoke(), ED_operator_editmball(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, TFM_TRANSLATION, and transform_mode_types.
Referenced by ED_operatortypes_metaball().
void MBALL_OT_hide_metaelems (struct wmOperatorType * ot)
Definition at line 360 of file mball_edit.c.
References wmOperatorType::description, ED_operator_editmball(), wmOperatorType::exec, wmOperatorType::flag, hide_metaelems_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_metaball().
void MBALL_OT_reveal_metaelems (struct wmOperatorType * ot)
Definition at line 401 of file mball_edit.c.
References wmOperatorType::description, ED_operator_editmball(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and reveal_metaelems_exec().
Referenced by ED_operatortypes_metaball().
void MBALL_OT_select_all (struct wmOperatorType * ot)
Definition at line 167 of file mball_edit.c.
References wmOperatorType::description, ED_operator_editmball(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, mball_select_all_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_properties_select_all().
Referenced by ED_operatortypes_metaball().
void MBALL_OT_select_random_metaelems (struct wmOperatorType * ot)
Definition at line 215 of file mball_edit.c.
References wmOperatorType::description, ED_operator_editmball(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_percentage(), select_random_metaelems_exec(), wmOperatorType::srna, and WM_operator_props_popup().
Referenced by ED_operatortypes_metaball().