Blender: initrender.h File Reference
initrender.h File Reference
Rendering
Functions
void free_sample_tables (Render *re)
void make_sample_tables (Render *re)
void initparts (Render *re)
void freeparts (Render *re)
Detailed Description
Definition in file initrender.h.
Function Documentation
void free_sample_tables (Render * re)
Definition at line 250 of file initrender.c.
References SampleTables::centmask, SampleTables::fmask1, SampleTables::fmask2, MEM_freeN(), NULL, and Render::samples.
Referenced by make_sample_tables(), and RE_FreeRender().
void freeparts (Render * re)
Definition at line 530 of file initrender.c.
References BLI_freelistN(), ListBase::first, MEM_freeN(), RenderPart::next, Render::parts, RenderPart::rectp, and RenderPart::rectz.
Referenced by initparts(), and threaded_tile_processor().
void initparts (Render * re)
Definition at line 542 of file initrender.c.
References BLI_addtail(), RenderPart::crop, RenderStats::curpart, RenderPart::disprect, Render::disprect, RenderData::filtertype, freeparts(), Render::i, MEM_callocN(), RenderData::mode, Render::panophi, panorama_pixel_rot(), Render::parts, RenderStats::partsdone, Render::partx, Render::party, Render::r, R_EDGE, R_EXR_TILE_FILE, R_FULL_SAMPLE, R_PANORAMA, RenderPart::rectx, Render::rectx, Render::recty, RenderPart::recty, RenderData::scemode, RenderStats::totpart, rcti::xmax, rcti::xmin, Render::xparts, RenderData::xparts, rcti::ymax, rcti::ymin, RenderData::yparts, and Render::yparts.
Referenced by threaded_tile_processor().
void make_sample_tables (Render * re)
Definition at line 267 of file initrender.c.
References calc_weight(), SampleTables::centLut, SampleTables::centmask, CLAMP(), SampleTables::cmask, RenderData::filtertype, SampleTables::fmask1, SampleTables::fmask2, free_sample_tables(), i, init_render_jit(), Render::jit, MEM_callocN(), MEM_freeN(), MEM_mallocN(), Render::osa, Render::r, and Render::samples.
Referenced by RE_InitState().