Blender: bpy_traceback.c File Reference
bpy_traceback.c File Reference
Python RNA and Operators
#include <Python.h>
#include <frameobject.h>
#include "BLI_path_util.h"
#include "BLI_string.h"
#include "bpy_traceback.h"
Functions
static const char * traceback_filepath (PyTracebackObject *tb, PyObject **coerce)
static int parse_syntax_error (PyObject *err, PyObject **message, const char **filename, int *lineno, int *offset, const char **text)
void python_script_error_jump (const char *filepath, int *lineno, int *offset)
Detailed Description
This file contains utility functions for getting data from a python stack trace.
Definition in file bpy_traceback.c.
Function Documentation
static int parse_syntax_error (PyObject * err, PyObject ** message, const char ** filename, int * lineno, int * offset, const char ** text) [static]
Definition at line 44 of file bpy_traceback.c.
References NULL.
Referenced by python_script_error_jump().
void python_script_error_jump (const char * filepath, int * lineno, int * offset)
Definition at line 111 of file bpy_traceback.c.
References BLI_path_cmp, parse_syntax_error(), and traceback_filepath().
Referenced by python_script_error_jump_text().
static const char* traceback_filepath (PyTracebackObject * tb, PyObject ** coerce) [static]
Definition at line 37 of file bpy_traceback.c.
Referenced by python_script_error_jump().