Blender: mathutils_Quaternion.h File Reference
mathutils_Quaternion.h File Reference
Python Mathutils
Classes
struct QuaternionObject
Defines
#define QuaternionObject_Check(_v) PyObject_TypeCheck((_v), &quaternion_Type)
Functions
PyObject * Quaternion_CreatePyObject (float *quat, int type, PyTypeObject *base_type)
PyObject * Quaternion_CreatePyObject_cb (PyObject *cb_user, unsigned char cb_type, unsigned char cb_subtype)
Variables
PyTypeObject quaternion_Type
Detailed Description
Definition in file mathutils_Quaternion.h.
Define Documentation
#define QuaternionObject_Check (_v) PyObject_TypeCheck((_v), &quaternion_Type)
Definition at line 39 of file mathutils_Quaternion.h.
Referenced by mathutils_any_to_rotmat(), mathutils_array_parse(), mathutils_array_parse_alloc(), Quaternion_add(), Quaternion_mul(), Quaternion_richcmpr(), Quaternion_sub(), Vector_imul(), and Vector_mul().
Function Documentation
PyObject* Quaternion_CreatePyObject (float * quat, int type, PyTypeObject * base_type)
Definition at line 1247 of file mathutils_Quaternion.c.
References copy_qt_qt(), NULL, Py_NEW, Py_WRAP, QUAT_SIZE, and unit_qt().
Referenced by Euler_to_quaternion(), Matrix_decompose(), Matrix_to_quaternion(), pyrna_math_object_from_array(), quat_mul_float(), Quaternion_add(), Quaternion_copy(), Quaternion_CreatePyObject_cb(), Quaternion_cross(), Quaternion_mul(), Quaternion_neg(), Quaternion_new(), Quaternion_rotation_difference(), Quaternion_slerp(), Quaternion_sub(), Vector_rotation_difference(), and Vector_to_track_quat().
PyObject* Quaternion_CreatePyObject_cb (PyObject * cb_user, unsigned char cb_type, unsigned char cb_subtype)
Definition at line 1280 of file mathutils_Quaternion.c.
References Py_NEW, and Quaternion_CreatePyObject().
Referenced by pyrna_math_object_from_array().
Variable Documentation
PyTypeObject quaternion_Type
Definition at line 1193 of file mathutils_Quaternion.c.
Referenced by PyInit_mathutils().