Blender: mesh_ops.c File Reference
mesh_ops.c File Reference
mesh
#include <stdlib.h>
#include <math.h>
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BKE_context.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_object.h"
#include "ED_mesh.h"
#include "ED_screen.h"
#include "ED_view3d.h"
#include "mesh_intern.h"
Functions
void ED_operatortypes_mesh (void)
void ED_operatormacros_mesh (void)
void ED_keymap_mesh (wmKeyConfig *keyconf)
Detailed Description
Definition in file mesh_ops.c.
Function Documentation
void ED_keymap_mesh (wmKeyConfig * keyconf)
Definition at line 247 of file mesh_ops.c.
References ACTIONMOUSE, AKEY, DELKEY, DKEY, ED_object_generic_keymap(), ED_operator_editmesh(), EKEY, FALSE, FKEY, GKEY, HKEY, i, IKEY, JKEY, KKEY, KM_ALT, KM_CLICK, KM_CTRL, KM_PRESS, KM_SHIFT, knifetool_modal_keymap(), LKEY, MKEY, NKEY, PADMINUS, PADPLUSKEY, PKEY, wmKeyMap::poll, wmKeyMapItem::ptr, RKEY, RNA_boolean_set(), RNA_enum_set(), RNA_int_set(), SEL_INVERT, SEL_TOGGLE, SELECTMOUSE, SKEY, TABKEY, TKEY, TRUE, UKEY, VKEY, WKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), XKEY, YKEY, and ZEROKEY.
Referenced by ED_spacetypes_keymap().
void ED_operatormacros_mesh (void)
Definition at line 192 of file mesh_ops.c.
References wmOperatorType::description, FALSE, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorTypeMacro::ptr, RNA_boolean_set(), RNA_enum_set(), RNA_struct_idprops_unset(), WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().
void ED_operatortypes_mesh (void)
Definition at line 59 of file mesh_ops.c.
References MESH_OT_beautify_fill(), MESH_OT_bevel(), MESH_OT_blend_from_shape(), MESH_OT_bridge_edge_loops(), MESH_OT_colors_reverse(), MESH_OT_colors_rotate(), MESH_OT_delete(), MESH_OT_dissolve(), MESH_OT_dissolve_limited(), MESH_OT_drop_named_image(), MESH_OT_dupli_extrude_cursor(), MESH_OT_duplicate(), MESH_OT_edge_collapse(), MESH_OT_edge_collapse_loop(), MESH_OT_edge_face_add(), MESH_OT_edge_rotate(), MESH_OT_edge_split(), MESH_OT_edgering_select(), MESH_OT_edges_select_sharp(), MESH_OT_extrude_edges_indiv(), MESH_OT_extrude_faces_indiv(), MESH_OT_extrude_region(), MESH_OT_extrude_repeat(), MESH_OT_extrude_verts_indiv(), MESH_OT_faces_select_linked_flat(), MESH_OT_faces_shade_flat(), MESH_OT_faces_shade_smooth(), MESH_OT_fill(), MESH_OT_flip_normals(), MESH_OT_hide(), MESH_OT_inset(), MESH_OT_knife_tool(), MESH_OT_loop_multi_select(), MESH_OT_loop_select(), MESH_OT_loop_to_region(), MESH_OT_loopcut(), MESH_OT_mark_seam(), MESH_OT_mark_sharp(), MESH_OT_merge(), MESH_OT_navmesh_clear(), MESH_OT_navmesh_face_add(), MESH_OT_navmesh_face_copy(), MESH_OT_navmesh_make(), MESH_OT_navmesh_reset(), MESH_OT_noise(), MESH_OT_normals_make_consistent(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cube_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_monkey_add(), MESH_OT_primitive_plane_add(), MESH_OT_primitive_uv_sphere_add(), MESH_OT_quads_convert_to_tris(), MESH_OT_region_to_loop(), MESH_OT_remove_doubles(), MESH_OT_reveal(), MESH_OT_rip(), MESH_OT_screw(), MESH_OT_select_all(), MESH_OT_select_axis(), MESH_OT_select_by_number_vertices(), MESH_OT_select_interior_faces(), MESH_OT_select_less(), MESH_OT_select_linked(), MESH_OT_select_linked_pick(), MESH_OT_select_loose_verts(), MESH_OT_select_mirror(), MESH_OT_select_more(), MESH_OT_select_next_loop(), MESH_OT_select_non_manifold(), MESH_OT_select_nth(), MESH_OT_select_random(), MESH_OT_select_shortest_path(), MESH_OT_select_similar(), MESH_OT_select_vertex_path(), MESH_OT_separate(), MESH_OT_shape_propagate_to_all(), MESH_OT_solidify(), MESH_OT_sort_faces(), MESH_OT_spin(), MESH_OT_split(), MESH_OT_sticky_add(), MESH_OT_sticky_remove(), MESH_OT_subdivide(), MESH_OT_tris_convert_to_quads(), MESH_OT_uv_texture_add(), MESH_OT_uv_texture_remove(), MESH_OT_uvs_reverse(), MESH_OT_uvs_rotate(), MESH_OT_vert_connect(), MESH_OT_vert_slide(), MESH_OT_vertex_color_add(), MESH_OT_vertex_color_remove(), MESH_OT_vertices_randomize(), MESH_OT_vertices_smooth(), MESH_OT_vertices_sort(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().