Blender: sketch.c File Reference
sketch.c File Reference
blenkernel
#include <string.h>
#include <math.h>
#include <float.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_sketch.h"
#include "DNA_userdef_types.h"
Functions
void freeSketch (SK_Sketch *sketch)
SK_Sketch * createSketch (void)
void sk_initPoint (SK_Point *pt, SK_DrawData *dd, const float no[3])
void sk_copyPoint (SK_Point *dst, SK_Point *src)
void sk_allocStrokeBuffer (SK_Stroke *stk)
void sk_freeStroke (SK_Stroke *stk)
SK_Stroke * sk_createStroke (void)
void sk_shrinkStrokeBuffer (SK_Stroke *stk)
void sk_growStrokeBuffer (SK_Stroke *stk)
void sk_growStrokeBufferN (SK_Stroke *stk, int n)
void sk_replaceStrokePoint (SK_Stroke *stk, SK_Point *pt, int n)
void sk_insertStrokePoint (SK_Stroke *stk, SK_Point *pt, int n)
void sk_appendStrokePoint (SK_Stroke *stk, SK_Point *pt)
void sk_insertStrokePoints (SK_Stroke *stk, SK_Point *pts, int len, int start, int end)
void sk_trimStroke (SK_Stroke *stk, int start, int end)
void sk_straightenStroke (SK_Stroke *stk, int start, int end, float p_start[3], float p_end[3])
void sk_polygonizeStroke (SK_Stroke *stk, int start, int end)
void sk_flattenStroke (SK_Stroke *stk, int start, int end)
void sk_removeStroke (SK_Sketch *sketch, SK_Stroke *stk)
void sk_reverseStroke (SK_Stroke *stk)
void sk_filterStroke (SK_Stroke *stk, int start, int end)
void sk_filterLastContinuousStroke (SK_Stroke *stk)
SK_Point * sk_lastStrokePoint (SK_Stroke *stk)
void sk_endContinuousStroke (SK_Stroke *stk)
void sk_updateNextPoint (SK_Sketch *sketch, SK_Stroke *stk)
int sk_stroke_filtermval (SK_DrawData *dd)
void sk_initDrawData (SK_DrawData *dd, const int mval[2])
void sk_deleteSelectedStrokes (SK_Sketch *sketch)
void sk_selectAllSketch (SK_Sketch *sketch, int mode)
Detailed Description
Definition in file sketch.c.
Function Documentation
SK_Sketch* createSketch (void)
Definition at line 59 of file sketch.c.
References SK_Sketch::active_stroke, ListBase::first, SK_Sketch::gesture, ListBase::last, MEM_callocN(), NULL, and SK_Sketch::strokes.
Referenced by contextSketch(), and viewcontextSketch().
void freeSketch (SK_Sketch * sketch)
Definition at line 43 of file sketch.c.
References BLI_freelistN(), SK_Sketch::depth_peels, ListBase::first, MEM_freeN(), SK_Stroke::next, next, sk_freeStroke(), and SK_Sketch::strokes.
Referenced by free_armature().
void sk_allocStrokeBuffer (SK_Stroke * stk)
Definition at line 94 of file sketch.c.
References SK_Stroke::buf_size, MEM_callocN(), and SK_Stroke::points.
Referenced by sk_createStroke(), sk_filterStroke(), sk_growStrokeBuffer(), sk_growStrokeBufferN(), sk_reverseStroke(), and sk_shrinkStrokeBuffer().
void sk_appendStrokePoint (SK_Stroke * stk, SK_Point * pt)
Definition at line 190 of file sketch.c.
References SK_Stroke::nb_points, SK_Stroke::points, and sk_growStrokeBuffer().
Referenced by sk_addStrokeDrawPoint(), sk_addStrokeSnapPoint(), sk_filterStroke(), and sk_getSegments().
void sk_copyPoint (SK_Point * dst, SK_Point * src)
Definition at line 89 of file sketch.c.
Referenced by sk_reverseStroke().
SK_Stroke* sk_createStroke (void)
Definition at line 105 of file sketch.c.
References SK_Stroke::buf_size, MEM_callocN(), SK_Stroke::nb_points, SK_Stroke::selected, sk_allocStrokeBuffer(), and SK_Stroke_BUFFER_INIT_SIZE.
Referenced by sk_initGesture(), sk_start_draw_gesture(), and sk_startStroke().
void sk_deleteSelectedStrokes (SK_Sketch * sketch)
Definition at line 550 of file sketch.c.
References ListBase::first, SK_Stroke::next, next, SK_Stroke::selected, sk_removeStroke(), and SK_Sketch::strokes.
Referenced by BIF_deleteSketch(), and sketch_delete().
void sk_endContinuousStroke (SK_Stroke * stk)
Definition at line 516 of file sketch.c.
References SK_Stroke::nb_points, SK_Stroke::points, PT_EXACT, and SK_Point::type.
Referenced by sketch_draw_modal().
void sk_filterLastContinuousStroke (SK_Stroke * stk)
Definition at line 487 of file sketch.c.
References SK_Stroke::nb_points, SK_Stroke::points, PT_CONTINUOUS, sk_filterStroke(), and SK_Point::type.
Referenced by sketch_draw_modal().
void sk_filterStroke (SK_Stroke * stk, int start, int end)
Definition at line 371 of file sketch.c.
References i, max_i(), MEM_callocN(), MEM_freeN(), mul(), SK_Stroke::nb_points, NULL, SK_Point::p2d, SK_Stroke::points, sk_allocStrokeBuffer(), sk_appendStrokePoint(), and sk_shrinkStrokeBuffer().
Referenced by sk_filterLastContinuousStroke().
void sk_flattenStroke (SK_Stroke * stk, int start, int end)
Definition at line 312 of file sketch.c.
References add_v3_v3(), copy_v3_v3(), distance(), i, mul_v3_fl(), SK_Point::no, normalize_v3(), p, SK_Point::p, SK_Stroke::points, project_v3_v3v3(), sub_v3_v3(), and sub_v3_v3v3().
Referenced by sk_applyCommandGesture().
void sk_freeStroke (SK_Stroke * stk)
Definition at line 99 of file sketch.c.
References MEM_freeN(), and SK_Stroke::points.
Referenced by freeSketch(), sk_freeGesture(), sk_removeStroke(), and sketch_draw_modal().
void sk_growStrokeBuffer (SK_Stroke * stk)
Definition at line 136 of file sketch.c.
References SK_Stroke::buf_size, MEM_freeN(), SK_Stroke::nb_points, SK_Stroke::points, and sk_allocStrokeBuffer().
Referenced by sk_appendStrokePoint(), and sk_insertStrokePoint().
void sk_growStrokeBufferN (SK_Stroke * stk, int n)
Definition at line 152 of file sketch.c.
References SK_Stroke::buf_size, MEM_freeN(), SK_Stroke::nb_points, SK_Stroke::points, and sk_allocStrokeBuffer().
Referenced by sk_insertStrokePoints().
void sk_initDrawData (SK_DrawData * dd, const int mval[2])
Definition at line 540 of file sketch.c.
References SK_DrawData::mval, SK_DrawData::previous_mval, PT_EXACT, and SK_DrawData::type.
Referenced by sketch_draw_gesture(), sketch_draw_preview(), and sketch_draw_stroke().
void sk_initPoint (SK_Point * pt, SK_DrawData * dd, const float no[3])
Definition at line 74 of file sketch.c.
References SK_DrawData::mval, SK_Point::no, normalize_v3_v3(), and SK_Point::p2d.
Referenced by sk_addStrokeDrawPoint(), and sk_addStrokeSnapPoint().
void sk_insertStrokePoint (SK_Stroke * stk, SK_Point * pt, int n)
Definition at line 177 of file sketch.c.
References SK_Stroke::nb_points, SK_Stroke::points, size(), and sk_growStrokeBuffer().
Referenced by sk_applyCutGesture(), and sk_straightenStroke().
void sk_insertStrokePoints (SK_Stroke * stk, SK_Point * pts, int len, int start, int end)
Definition at line 199 of file sketch.c.
References SK_Stroke::nb_points, SK_Stroke::points, size(), and sk_growStrokeBufferN().
Referenced by sk_endOverdraw().
SK_Point* sk_lastStrokePoint (SK_Stroke * stk)
Definition at line 504 of file sketch.c.
References SK_Stroke::nb_points, NULL, and SK_Stroke::points.
Referenced by sk_detectMergeGesture(), sk_detectReverseGesture(), sk_drawSketch(), sk_endOverdraw(), sk_projectDrawPoint(), sk_strokeToArc(), and sk_updateOverdraw().
void sk_polygonizeStroke (SK_Stroke * stk, int start, int end)
Definition at line 266 of file sketch.c.
References i, SK_Stroke::nb_points, SK_Stroke::points, PT_EXACT, size(), and SK_Point::type.
Referenced by sk_applyCommandGesture().
void sk_removeStroke (SK_Sketch * sketch, SK_Stroke * stk)
Definition at line 343 of file sketch.c.
References SK_Sketch::active_stroke, BLI_remlink(), NULL, sk_freeStroke(), and SK_Sketch::strokes.
Referenced by sk_applyDeleteGesture(), sk_cancelStroke(), sk_deleteSelectedStrokes(), sk_endOverdraw(), and sk_finish_stroke().
void sk_replaceStrokePoint (SK_Stroke * stk, SK_Point * pt, int n)
Definition at line 172 of file sketch.c.
References SK_Stroke::points.
Referenced by sk_applyTrimGesture().
void sk_reverseStroke (SK_Stroke * stk)
Definition at line 354 of file sketch.c.
References i, MEM_freeN(), SK_Stroke::nb_points, SK_Stroke::points, sk_allocStrokeBuffer(), and sk_copyPoint().
Referenced by sk_applyReverseGesture(), and sk_endOverdraw().
void sk_selectAllSketch (SK_Sketch * sketch, int mode)
Definition at line 565 of file sketch.c.
References ListBase::first, SK_Stroke::next, NULL, SK_Stroke::selected, and SK_Sketch::strokes.
Referenced by sk_selectStroke(), and sk_start_draw_stroke().
void sk_shrinkStrokeBuffer (SK_Stroke * stk)
Definition at line 120 of file sketch.c.
References SK_Stroke::buf_size, MEM_freeN(), SK_Stroke::nb_points, SK_Stroke::points, and sk_allocStrokeBuffer().
Referenced by sk_endStroke(), and sk_filterStroke().
void sk_straightenStroke (SK_Stroke * stk, int start, int end, float p_start[3], float p_end[3])
Definition at line 229 of file sketch.c.
References add_v3_v3(), copy_v3_v3(), i, SK_Point::mode, mul_v3_v3fl(), next, SK_Point::no, p, SK_Point::p, SK_Stroke::points, sk_insertStrokePoint(), sub_v3_v3v3(), and SK_Point::type.
Referenced by sk_applyCommandGesture().
int sk_stroke_filtermval (SK_DrawData * dd)
Definition at line 529 of file sketch.c.
References ABS, SK_DrawData::mval, and SK_DrawData::previous_mval.
Referenced by sk_draw_stroke().
void sk_trimStroke (SK_Stroke * stk, int start, int end)
Definition at line 217 of file sketch.c.
References SK_Stroke::nb_points, SK_Stroke::points, and size().
Referenced by sk_applyTrimGesture().
void sk_updateNextPoint (SK_Sketch * sketch, SK_Stroke * stk)
Definition at line 521 of file sketch.c.
References SK_Stroke::nb_points, SK_Sketch::next_point, SK_Point::p, and SK_Stroke::points.
Referenced by sk_draw_stroke(), and sketch_draw_modal().