Blender: rna_particle.c File Reference
rna_particle.c File Reference
RNA
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_material_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_modifier_types.h"
#include "DNA_cloth_types.h"
#include "DNA_particle_types.h"
#include "DNA_object_force.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_boid_types.h"
#include "DNA_texture_types.h"
#include "WM_types.h"
#include "WM_api.h"
Functions
static void rna_def_particle_hair_key (BlenderRNA *brna)
static void rna_def_particle_key (BlenderRNA *brna)
static void rna_def_child_particle (BlenderRNA *brna)
static void rna_def_particle (BlenderRNA *brna)
static void rna_def_particle_dupliweight (BlenderRNA *brna)
static void rna_def_fluid_settings (BlenderRNA *brna)
static void rna_def_particle_settings_mtex (BlenderRNA *brna)
static void rna_def_particle_settings (BlenderRNA *brna)
static void rna_def_particle_target (BlenderRNA *brna)
static void rna_def_particle_system (BlenderRNA *brna)
void RNA_def_particle (BlenderRNA *brna)
Variables
EnumPropertyItem part_from_items []
EnumPropertyItem part_reactor_from_items []
EnumPropertyItem part_dist_items []
EnumPropertyItem part_hair_dist_items []
EnumPropertyItem part_draw_as_items []
EnumPropertyItem part_hair_draw_as_items []
EnumPropertyItem part_ren_as_items []
EnumPropertyItem part_hair_ren_as_items []
Detailed Description
Definition in file rna_particle.c.
Function Documentation
static void rna_def_child_particle (BlenderRNA * brna) [static]
Definition at line 963 of file rna_particle.c.
References NULL, RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_particle().
static void rna_def_fluid_settings (BlenderRNA * brna) [static]
Definition at line 1113 of file rna_particle.c.
References NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_ui_text(), SPH_CURRENT_REST_LENGTH, SPH_FAC_DENSITY, SPH_FAC_RADIUS, SPH_FAC_REPULSION, SPH_FAC_REST_LENGTH, SPH_FAC_VISCOSITY, and SPH_VISCOELASTIC_SPRINGS.
Referenced by RNA_def_particle().
static void rna_def_particle (BlenderRNA * brna) [static]
Definition at line 980 of file rna_particle.c.
References NULL, PARS_ALIVE, PARS_DEAD, PARS_DYING, PARS_NO_DISP, PARS_UNBORN, PARS_UNEXIST, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_QUATERNION, PROP_TIME, PROP_TRANSLATION, PROP_VELOCITY, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_particle().
void RNA_def_particle (BlenderRNA * brna)
Definition at line 2980 of file rna_particle.c.
References rna_def_child_particle(), rna_def_fluid_settings(), rna_def_particle(), rna_def_particle_dupliweight(), rna_def_particle_hair_key(), rna_def_particle_key(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_particle_system(), and rna_def_particle_target().
static void rna_def_particle_dupliweight (BlenderRNA * brna) [static]
Definition at line 1090 of file rna_particle.c.
References NULL, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_STRING, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_particle().
static void rna_def_particle_hair_key (BlenderRNA * brna) [static]
Definition at line 906 of file rna_particle.c.
References NULL, PROP_FLOAT, PROP_TRANSLATION, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_particle().
static void rna_def_particle_key (BlenderRNA * brna) [static]
Definition at line 935 of file rna_particle.c.
References NULL, PROP_FLOAT, PROP_QUATERNION, PROP_TRANSLATION, PROP_UNSIGNED, PROP_VELOCITY, RNA_def_property(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_particle().
static void rna_def_particle_settings (BlenderRNA * brna) [static]
Definition at line 1477 of file rna_particle.c.
References MAXFRAMEF, MINAFRAMEF, NULL, PART_ABS_PATH_TIME, PART_AVE_GLOBAL_X, PART_AVE_GLOBAL_Y, PART_AVE_GLOBAL_Z, PART_AVE_HORIZONTAL, PART_AVE_RAND, PART_AVE_VELOCITY, PART_AVE_VERTICAL, PART_BB_ANIM_AGE, PART_BB_ANIM_ANGLE, PART_BB_ANIM_FRAME, PART_BB_ANIM_NONE, PART_BB_OFF_LINEAR, PART_BB_OFF_NONE, PART_BB_OFF_RANDOM, PART_BB_VEL, PART_BB_VIEW, PART_BB_X, PART_BB_Y, PART_BB_Z, PART_BOIDS_2D, PART_CHILD_EFFECT, PART_CHILD_FACES, PART_CHILD_GUIDE, PART_CHILD_LONG_HAIR, PART_CHILD_PARTICLES, PART_DIE_ON_COL, PART_DIED, PART_DRAW_BB_LOCK, PART_DRAW_COL_ACC, PART_DRAW_COL_MAT, PART_DRAW_COL_NONE, PART_DRAW_COL_VEL, PART_DRAW_COUNT_GR, PART_DRAW_EMITTER, PART_DRAW_GLOBAL_OB, PART_DRAW_HEALTH, PART_DRAW_NUM, PART_DRAW_PARENT, PART_DRAW_RAND_GR, PART_DRAW_REN_ADAPT, PART_DRAW_REN_STRAND, PART_DRAW_ROTATE_OB, PART_DRAW_SIZE, PART_DRAW_VEL, PART_DRAW_VEL_LENGTH, PART_DRAW_WHOLE_GR, PART_EDISTR, PART_EMITTER, PART_EVENT_COLLIDE, PART_EVENT_DEATH, PART_EVENT_NEAR, PART_GRID_HEXAGONAL, PART_GRID_INVERT, PART_HAIR, PART_HAIR_BSPLINE, PART_HAIR_REGROW, PART_HIDE_ADVANCED_HAIR, PART_INT_EULER, PART_INT_MIDPOINT, PART_INT_RK4, PART_INT_VERLET, PART_KINK_BRAID, PART_KINK_CURL, PART_KINK_NO, PART_KINK_RADIAL, PART_KINK_WAVE, PART_PHYS_BOIDS, PART_PHYS_FLUID, PART_PHYS_KEYED, PART_PHYS_NEWTON, PART_PHYS_NO, PART_REACT_MULTIPLE, PART_REACT_STA_END, PART_ROT_DYN, PART_ROT_GLOB_X, PART_ROT_GLOB_Y, PART_ROT_GLOB_Z, PART_ROT_IINCR, PART_ROT_KEYS, PART_ROT_NOR, PART_ROT_OB_X, PART_ROT_OB_Y, PART_ROT_OB_Z, PART_ROT_VEL, PART_ROT_ZINCR, PART_ROTATIONS, PART_SELF_EFFECT, PART_SIMPLIFY_ENABLE, PART_SIMPLIFY_VIEWPORT, PART_SIZE_DEFL, PART_SIZEMASS, PART_TIME_AUTOSF, PART_TRAND, PART_UNBORN, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_TIME, PROP_TRANSLATION, PROP_UNSIGNED, PROP_VELOCITY, rna_def_animdata_common(), rna_def_mtex_common(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_default(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_particle().
static void rna_def_particle_settings_mtex (BlenderRNA * brna) [static]
Definition at line 1250 of file rna_particle.c.
References MTEX_CUBE, MTEX_FLAT, MTEX_SPHERE, MTEX_TUBE, NULL, PAMAP_CLUMP, PAMAP_DAMP, PAMAP_DENS, PAMAP_FIELD, PAMAP_GRAVITY, PAMAP_IVEL, PAMAP_KINK, PAMAP_LENGTH, PAMAP_LIFE, PAMAP_ROUGH, PAMAP_SIZE, PAMAP_TIME, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TEXCO_GLOB, TEXCO_OBJECT, TEXCO_ORCO, TEXCO_STRAND, and TEXCO_UV.
Referenced by RNA_def_particle().
static void rna_def_particle_system (BlenderRNA * brna) [static]
Definition at line 2675 of file rna_particle.c.
References NA_RENAME, NC_OBJECT, ND_MODIFIER, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_UNSIGNED, PSYS_GLOBAL_HAIR, PSYS_HAIR_DYNAMICS, PSYS_KEYED_TIMING, PSYS_VG_CLUMP, PSYS_VG_DENSITY, PSYS_VG_EFFECTOR, PSYS_VG_KINK, PSYS_VG_LENGTH, PSYS_VG_ROT, PSYS_VG_ROUGH1, PSYS_VG_ROUGH2, PSYS_VG_ROUGHE, PSYS_VG_SIZE, PSYS_VG_TAN, PSYS_VG_VEL, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_particle().
static void rna_def_particle_target (BlenderRNA * brna) [static]
Definition at line 2615 of file rna_particle.c.
References NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_TIME, PROP_UNSIGNED, PTARGET_MODE_ENEMY, PTARGET_MODE_FRIEND, PTARGET_MODE_NEUTRAL, PTARGET_VALID, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), and RNA_def_struct_ui_text().
Referenced by RNA_def_particle().
Variable Documentation
EnumPropertyItem part_dist_items[]
Initial value:
 {
    {PART_DISTR_JIT, "JIT", 0, "Jittered", ""},
    {PART_DISTR_RAND, "RAND", 0, "Random", ""},
    {PART_DISTR_GRID, "GRID", 0, "Grid", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 68 of file rna_particle.c.
EnumPropertyItem part_draw_as_items[]
Initial value:
 {
    {PART_DRAW_NOT, "NONE", 0, "None", ""},
    {PART_DRAW_REND, "RENDER", 0, "Rendered", ""},
    {PART_DRAW_DOT, "DOT", 0, "Point", ""},
    {PART_DRAW_CIRC, "CIRC", 0, "Circle", ""},
    {PART_DRAW_CROSS, "CROSS", 0, "Cross", ""},
    {PART_DRAW_AXIS, "AXIS", 0, "Axis", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 81 of file rna_particle.c.
EnumPropertyItem part_from_items[]
Initial value:
 {
    {PART_FROM_VERT, "VERT", 0, "Verts", ""},
    {PART_FROM_FACE, "FACE", 0, "Faces", ""},
    {PART_FROM_VOLUME, "VOLUME", 0, "Volume", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 54 of file rna_particle.c.
EnumPropertyItem part_hair_dist_items[]
Initial value:
 {
    {PART_DISTR_JIT, "JIT", 0, "Jittered", ""},
    {PART_DISTR_RAND, "RAND", 0, "Random", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 75 of file rna_particle.c.
EnumPropertyItem part_hair_draw_as_items[]
Initial value:
 {
    {PART_DRAW_NOT, "NONE", 0, "None", ""},
    {PART_DRAW_REND, "RENDER", 0, "Rendered", ""},
    {PART_DRAW_PATH, "PATH", 0, "Path", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 91 of file rna_particle.c.
EnumPropertyItem part_hair_ren_as_items[]
Initial value:
 {
    {PART_DRAW_NOT, "NONE", 0, "None", ""},
    {PART_DRAW_PATH, "PATH", 0, "Path", ""},
    {PART_DRAW_OB, "OBJECT", 0, "Object", ""},
    {PART_DRAW_GR, "GROUP", 0, "Group", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 109 of file rna_particle.c.
EnumPropertyItem part_reactor_from_items[]
Initial value:
 {
    {PART_FROM_VERT, "VERT", 0, "Verts", ""},
    {PART_FROM_FACE, "FACE", 0, "Faces", ""},
    {PART_FROM_VOLUME, "VOLUME", 0, "Volume", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 61 of file rna_particle.c.
EnumPropertyItem part_ren_as_items[]
Initial value:
 {
    {PART_DRAW_NOT, "NONE", 0, "None", ""},
    {PART_DRAW_HALO, "HALO", 0, "Halo", ""},
    {PART_DRAW_LINE, "LINE", 0, "Line", ""},
    {PART_DRAW_PATH, "PATH", 0, "Path", ""},
    {PART_DRAW_OB, "OBJECT", 0, "Object", ""},
    {PART_DRAW_GR, "GROUP", 0, "Group", ""},
    {PART_DRAW_BB, "BILLBOARD", 0, "Billboard", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 98 of file rna_particle.c.