Blender: node_texture_util.h File Reference
node_texture_util.h File Reference
nodes
#include <math.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_color_types.h"
#include "DNA_ipo_types.h"
#include "DNA_ID.h"
#include "DNA_image_types.h"
#include "DNA_material_types.h"
#include "DNA_node_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_texture_types.h"
#include "BKE_blender.h"
#include "BKE_colortools.h"
#include "BKE_global.h"
#include "BKE_image.h"
#include "BKE_main.h"
#include "BKE_material.h"
#include "BKE_node.h"
#include "BKE_texture.h"
#include "BKE_library.h"
#include "node_util.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_rand.h"
#include "BLI_threads.h"
#include "BLI_utildefines.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "RE_pipeline.h"
#include "RE_shader_ext.h"
Classes
struct TexCallData
struct TexParams
struct TexDelegate
Typedefs
typedef struct TexCallData TexCallData
typedef struct TexParams TexParams
typedef void(* TexFn)(float *out, TexParams *params, bNode *node, bNodeStack **in, short thread)
typedef struct TexDelegate TexDelegate
Functions
void tex_input_rgba (float *out, bNodeStack *in, TexParams *params, short thread)
void tex_input_vec (float *out, bNodeStack *in, TexParams *params, short thread)
float tex_input_value (bNodeStack *in, TexParams *params, short thread)
void tex_output (bNode *node, bNodeStack **in, bNodeStack *out, TexFn texfn, TexCallData *data)
void tex_do_preview (bNode *node, float *coord, float *col)
void params_from_cdata (TexParams *out, TexCallData *in)
Detailed Description
Definition in file node_texture_util.h.
Typedef Documentation
typedef struct TexCallData TexCallData
typedef struct TexDelegate TexDelegate
typedef void(* TexFn)(float *out, TexParams *params, bNode *node, bNodeStack **in, short thread)
Definition at line 103 of file node_texture_util.h.
typedef struct TexParams TexParams
Function Documentation
void params_from_cdata (TexParams * out, TexCallData * in)
Definition at line 105 of file node_texture_util.c.
References TexParams::cfra, TexCallData::cfra, TexParams::co, TexCallData::co, TexParams::dxt, TexCallData::dxt, TexParams::dyt, TexCallData::dyt, TexParams::mtex, TexCallData::mtex, TexParams::osatex, TexCallData::osatex, TexParams::previewco, TexParams::shi, and TexCallData::shi.
Referenced by exec().
void tex_do_preview (bNode * node, float * coord, float * col)
Definition at line 117 of file node_texture_util.c.
References nodeAddToPreview(), bNode::preview, bNodePreview::xsize, and bNodePreview::ysize.
Referenced by exec(), and tex_call_delegate().
void tex_input_rgba (float * out, bNodeStack * in, TexParams * params, short thread)
Definition at line 81 of file node_texture_util.c.
References bNodeStack::hasoutput, SOCK_FLOAT, SOCK_VECTOR, bNodeStack::sockettype, and tex_input().
Referenced by colorfn(), exec(), rgb_colorfn(), rgbtobw_valuefn(), texfn(), valuefn_a(), valuefn_b(), valuefn_g(), and valuefn_r().
float tex_input_value (bNodeStack * in, TexParams * params, short thread)
Definition at line 98 of file node_texture_util.c.
References tex_input_vec().
Referenced by clouds_map_inputs(), colorfn(), distnoise_map_inputs(), magic_map_inputs(), marble_map_inputs(), musgrave_map_inputs(), normalfn(), stucci_map_inputs(), valtorgb_colorfn(), valuefn(), voronoi_map_inputs(), and wood_map_inputs().
void tex_input_vec (float * out, bNodeStack * in, TexParams * params, short thread)
Definition at line 76 of file node_texture_util.c.
References tex_input().
Referenced by colorfn(), exec(), tex_input_value(), and valuefn().
void tex_output (bNode * node, bNodeStack ** in, bNodeStack * out, TexFn texfn, TexCallData * data)
Definition at line 129 of file node_texture_util.c.
References TexDelegate::cdata, bNodeStack::data, TexDelegate::fn, TexDelegate::in, MAX_SOCKET, MEM_mallocN(), TexDelegate::node, bNodeStack::sockettype, texfn(), and TexDelegate::type.
Referenced by exec(), rgb_exec(), rgbtobw_exec(), time_exec(), and valtorgb_exec().