Blender: GHOST_Path-api.h File Reference
GHOST_Path-api.h File Reference
GHOST API
#include "GHOST_Types.h"
Functions
GHOST_DECLARE_HANDLE (GHOST_SystemPathsHandle)
GHOST_TSuccess GHOST_CreateSystemPaths (void)
GHOST_TSuccess GHOST_DisposeSystemPaths (void)
const GHOST_TUns8 * GHOST_getSystemDir (void)
const GHOST_TUns8 * GHOST_getUserDir (void)
const GHOST_TUns8 * GHOST_getBinaryDir (void)
void GHOST_addToSystemRecentFiles (const char *filename)
Detailed Description
Definition in file GHOST_Path-api.h.
Function Documentation
void GHOST_addToSystemRecentFiles (const char * filename)
Add the file to the operating system most recently used files
Definition at line 66 of file GHOST_Path-api.cpp.
References GHOST_ISystemPaths::addToSystemRecentFiles(), and GHOST_ISystemPaths::get().
Referenced by write_history().
GHOST_TSuccess GHOST_CreateSystemPaths (void)
Creates the one and only instance of the system path access.
Returns:
An indication of success.
Definition at line 38 of file GHOST_Path-api.cpp.
References GHOST_ISystemPaths::create().
Referenced by WM_init().
GHOST_DECLARE_HANDLE (GHOST_SystemPathsHandle)
GHOST_TSuccess GHOST_DisposeSystemPaths (void)
Disposes the one and only system.
Returns:
An indication of success.
Definition at line 43 of file GHOST_Path-api.cpp.
References GHOST_ISystemPaths::dispose().
Referenced by WM_exit_ext().
const GHOST_TUns8* GHOST_getBinaryDir (void)
Determine the dir in which the binary file is found.
Returns:
Unsigned char string pointing to binary dir (eg ~/usr/local/bin/).
Definition at line 60 of file GHOST_Path-api.cpp.
References GHOST_ISystemPaths::get(), and GHOST_ISystemPaths::getBinaryDir().
const GHOST_TUns8* GHOST_getSystemDir (void)
Determine the base dir in which shared resources are located. It will first try to use "unpack and run" path, then look for properly installed path, not including versioning.
Returns:
Unsigned char string pointing to system dir (eg /usr/share/blender/).
Definition at line 48 of file GHOST_Path-api.cpp.
References GHOST_ISystemPaths::get(), and GHOST_ISystemPaths::getSystemDir().
Referenced by get_path_system().
const GHOST_TUns8* GHOST_getUserDir (void)
Determine the base dir in which user configuration is stored, not including versioning.
Returns:
Unsigned char string pointing to user dir (eg ~).
Definition at line 54 of file GHOST_Path-api.cpp.
References GHOST_ISystemPaths::get(), and GHOST_ISystemPaths::getUserDir().
Referenced by get_path_user().