Blender: transform.c File Reference
transform.c File Reference
transform
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include <unistd.h>
#include "MEM_guardedalloc.h"
#include "DNA_anim_types.h"
#include "DNA_armature_types.h"
#include "DNA_constraint_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_movieclip_types.h"
#include "DNA_scene_types.h"
#include "RNA_access.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "BKE_nla.h"
#include "BKE_bmesh.h"
#include "BKE_context.h"
#include "BKE_constraint.h"
#include "BKE_global.h"
#include "BKE_particle.h"
#include "BKE_pointcache.h"
#include "BKE_unit.h"
#include "ED_image.h"
#include "ED_keyframing.h"
#include "ED_screen.h"
#include "ED_space_api.h"
#include "ED_markers.h"
#include "ED_view3d.h"
#include "ED_mesh.h"
#include "ED_clip.h"
#include "UI_view2d.h"
#include "WM_types.h"
#include "WM_api.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BLI_ghash.h"
#include "BLI_linklist.h"
#include "BLI_smallhash.h"
#include "BLI_array.h"
#include "UI_resources.h"
#include "transform.h"
Defines
#define TFM_MODAL_CANCEL 1
#define TFM_MODAL_CONFIRM 2
#define TFM_MODAL_TRANSLATE 3
#define TFM_MODAL_ROTATE 4
#define TFM_MODAL_RESIZE 5
#define TFM_MODAL_SNAP_INV_ON 6
#define TFM_MODAL_SNAP_INV_OFF 7
#define TFM_MODAL_SNAP_TOGGLE 8
#define TFM_MODAL_AXIS_X 9
#define TFM_MODAL_AXIS_Y 10
#define TFM_MODAL_AXIS_Z 11
#define TFM_MODAL_PLANE_X 12
#define TFM_MODAL_PLANE_Y 13
#define TFM_MODAL_PLANE_Z 14
#define TFM_MODAL_CONS_OFF 15
#define TFM_MODAL_ADD_SNAP 16
#define TFM_MODAL_REMOVE_SNAP 17
#define TFM_MODAL_PROPSIZE_UP 20
#define TFM_MODAL_PROPSIZE_DOWN 21
#define TFM_MODAL_AUTOIK_LEN_INC 22
#define TFM_MODAL_AUTOIK_LEN_DEC 23
#define SIGN(a) (a<-FLT_EPSILON?1:a>FLT_EPSILON?2:3)
#define VECSIGNFLIP(a, b) ((SIGN(a[0]) & SIGN(b[0]))==0 || (SIGN(a[1]) & SIGN(b[1]))==0 || (SIGN(a[2]) & SIGN(b[2]))==0)
Enumerations
enum ArrowDirection { UP, DOWN, LEFT, RIGHT }
Functions
static void drawTransformApply (const struct bContext *C, struct ARegion *ar, void *arg)
static int doEdgeSlide (TransInfo *t, float perc)
void setTransformViewMatrices (TransInfo *t)
static void convertViewVec2D (View2D *v2d, float vec[3], int dx, int dy)
void convertViewVec (TransInfo *t, float r_vec[3], int dx, int dy)
void projectIntView (TransInfo *t, const float vec[3], int adr[2])
void projectFloatView (TransInfo *t, const float vec[3], float adr[2])
void applyAspectRatio (TransInfo *t, float *vec)
void removeAspectRatio (TransInfo *t, float *vec)
static void viewRedrawForce (const bContext *C, TransInfo *t)
static void viewRedrawPost (bContext *C, TransInfo *t)
void BIF_selectOrientation (void)
static void view_editmove (unsigned short UNUSED(event))
wmKeyMap * transform_modal_keymap (wmKeyConfig *keyconf)
int transformEvent (TransInfo *t, wmEvent *event)
int calculateTransformCenter (bContext *C, int centerMode, float *vec)
static void drawArrow (ArrowDirection d, short offset, short length, short size)
static void drawArrowHead (ArrowDirection d, short size)
static void drawArc (float size, float angle_start, float angle_end, int segments)
static int helpline_poll (bContext *C)
static void drawHelpline (bContext *UNUSED(C), int x, int y, void *customdata)
static void drawTransformView (const struct bContext *C, struct ARegion *UNUSED(ar), void *arg)
void saveTransform (bContext *C, TransInfo *t, wmOperator *op)
int initTransform (bContext *C, TransInfo *t, wmOperator *op, wmEvent *event, int mode)
void transformApply (bContext *C, TransInfo *t)
static void drawTransformApply (const bContext *C, struct ARegion *UNUSED(ar), void *arg)
int transformEnd (bContext *C, TransInfo *t)
static void protectedTransBits (short protectflag, float *vec)
static void protectedSizeBits (short protectflag, float *size)
static void protectedRotateBits (short protectflag, float *eul, float *oldeul)
static void protectedAxisAngleBits (short protectflag, float axis[3], float *angle, float oldAxis[3], float oldAngle)
static void protectedQuaternionBits (short protectflag, float *quat, float *oldquat)
static void constraintTransLim (TransInfo *t, TransData *td)
static void constraintob_from_transdata (bConstraintOb *cob, TransData *td)
static void constraintRotLim (TransInfo *UNUSED(t), TransData *td)
static void constraintSizeLim (TransInfo *t, TransData *td)
static void postInputWarp (TransInfo *t, float values[3])
void initWarp (TransInfo *t)
int handleEventWarp (TransInfo *t, wmEvent *event)
int Warp (TransInfo *t, const int UNUSED(mval[2]))
static void postInputShear (TransInfo *UNUSED(t), float values[3])
void initShear (TransInfo *t)
int handleEventShear (TransInfo *t, wmEvent *event)
int Shear (TransInfo *t, const int UNUSED(mval[2]))
void initResize (TransInfo *t)
static void headerResize (TransInfo *t, float vec[3], char *str)
static void TransMat3ToSize (float mat[][3], float smat[][3], float *size)
static void ElementResize (TransInfo *t, TransData *td, float mat[3][3])
int Resize (TransInfo *t, const int mval[2])
void initToSphere (TransInfo *t)
int ToSphere (TransInfo *t, const int UNUSED(mval[2]))
static void postInputRotation (TransInfo *t, float values[3])
void initRotation (TransInfo *t)
static void ElementRotation (TransInfo *t, TransData *td, float mat[3][3], short around)
static void applyRotation (TransInfo *t, float angle, float axis[3])
int Rotation (TransInfo *t, const int UNUSED(mval[2]))
void initTrackball (TransInfo *t)
static void applyTrackball (TransInfo *t, float axis1[3], float axis2[3], float angles[2])
int Trackball (TransInfo *t, const int UNUSED(mval[2]))
void initTranslation (TransInfo *t)
static void headerTranslation (TransInfo *t, float vec[3], char *str)
static void applyTranslation (TransInfo *t, float vec[3])
int Translation (TransInfo *t, const int UNUSED(mval[2]))
void initShrinkFatten (TransInfo *t)
int ShrinkFatten (TransInfo *t, const int UNUSED(mval[2]))
void initTilt (TransInfo *t)
int Tilt (TransInfo *t, const int UNUSED(mval[2]))
void initCurveShrinkFatten (TransInfo *t)
int CurveShrinkFatten (TransInfo *t, const int UNUSED(mval[2]))
void initPushPull (TransInfo *t)
int PushPull (TransInfo *t, const int UNUSED(mval[2]))
void initBevel (TransInfo *t)
int handleEventBevel (TransInfo *t, wmEvent *event)
int Bevel (TransInfo *t, const int UNUSED(mval[2]))
void initBevelWeight (TransInfo *t)
int BevelWeight (TransInfo *t, const int UNUSED(mval[2]))
void initCrease (TransInfo *t)
int Crease (TransInfo *t, const int UNUSED(mval[2]))
void initBoneSize (TransInfo *t)
static void headerBoneSize (TransInfo *t, float vec[3], char *str)
static void ElementBoneSize (TransInfo *t, TransData *td, float mat[3][3])
int BoneSize (TransInfo *t, const int mval[2])
void initBoneEnvelope (TransInfo *t)
int BoneEnvelope (TransInfo *t, const int UNUSED(mval[2]))
static BMEdge * get_other_edge (BMVert *v, BMEdge *e)
static BMLoop * get_next_loop (BMVert *v, BMLoop *l, BMEdge *olde, BMEdge *nexte, float vec[3])
static int createSlideVerts (TransInfo *t)
void projectSVData (TransInfo *t, int final)
void freeSlideTempFaces (SlideData *sld)
void freeSlideVerts (TransInfo *t)
void initEdgeSlide (TransInfo *t)
int EdgeSlide (TransInfo *t, const int UNUSED(mval[2]))
void initBoneRoll (TransInfo *t)
int BoneRoll (TransInfo *t, const int UNUSED(mval[2]))
void initBakeTime (TransInfo *t)
int BakeTime (TransInfo *t, const int mval[2])
void initMirror (TransInfo *t)
int Mirror (TransInfo *t, const int UNUSED(mval[2]))
void initAlign (TransInfo *t)
int Align (TransInfo *t, const int UNUSED(mval[2]))
void initSeqSlide (TransInfo *t)
static void headerSeqSlide (TransInfo *t, float val[2], char *str)
static void applySeqSlide (TransInfo *t, float val[2])
int SeqSlide (TransInfo *t, const int UNUSED(mval[2]))
static short getAnimEdit_SnapMode (TransInfo *t)
static short getAnimEdit_DrawTime (TransInfo *t)
static void doAnimEdit_SnapFrame (TransInfo *t, TransData *td, TransData2D *td2d, AnimData *adt, short autosnap)
void initTimeTranslate (TransInfo *t)
static void headerTimeTranslate (TransInfo *t, char *str)
static void applyTimeTranslate (TransInfo *t, float UNUSED(sval))
int TimeTranslate (TransInfo *t, const int mval[2])
void initTimeSlide (TransInfo *t)
static void headerTimeSlide (TransInfo *t, float sval, char *str)
static void applyTimeSlide (TransInfo *t, float sval)
int TimeSlide (TransInfo *t, const int mval[2])
void initTimeScale (TransInfo *t)
static void headerTimeScale (TransInfo *t, char *str)
static void applyTimeScale (TransInfo *t)
int TimeScale (TransInfo *t, const int UNUSED(mval[2]))
void BIF_TransformSetUndo (const char *UNUSED(str))
Detailed Description
Definition in file transform.c.
Define Documentation
#define SIGN (a) (a<-FLT_EPSILON?1:a>FLT_EPSILON?2:3)
Definition at line 2631 of file transform.c.
#define TFM_MODAL_ADD_SNAP 16
Definition at line 501 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_AUTOIK_LEN_DEC 23
Definition at line 508 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_AUTOIK_LEN_INC 22
Definition at line 507 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_AXIS_X 9
Definition at line 494 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_AXIS_Y 10
Definition at line 495 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_AXIS_Z 11
Definition at line 496 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_CANCEL 1
Definition at line 486 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_CONFIRM 2
Definition at line 487 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_CONS_OFF 15
Definition at line 500 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_PLANE_X 12
Definition at line 497 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_PLANE_Y 13
Definition at line 498 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_PLANE_Z 14
Definition at line 499 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_PROPSIZE_DOWN 21
Definition at line 506 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_PROPSIZE_UP 20
Definition at line 505 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_REMOVE_SNAP 17
Definition at line 502 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_RESIZE 5
Definition at line 490 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_ROTATE 4
Definition at line 489 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_SNAP_INV_OFF 7
Definition at line 492 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_SNAP_INV_ON 6
Definition at line 491 of file transform.c.
Referenced by initTransform(), transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_SNAP_TOGGLE 8
Definition at line 493 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define TFM_MODAL_TRANSLATE 3
Definition at line 488 of file transform.c.
Referenced by transform_modal_keymap(), and transformEvent().
#define VECSIGNFLIP (a, b) ((SIGN(a[0]) & SIGN(b[0]))==0 || (SIGN(a[1]) & SIGN(b[1]))==0 || (SIGN(a[2]) & SIGN(b[2]))==0)
Definition at line 2632 of file transform.c.
Referenced by TransMat3ToSize().
Enumeration Type Documentation
enum ArrowDirection
Enumerator:
UP
DOWN
LEFT
RIGHT
Definition at line 1151 of file transform.c.
Function Documentation
int Align (TransInfo * t, const int UNUSEDmval[2])
Definition at line 5237 of file transform.c.
References TransInfo::around, TransData::axismtx, TransData::center, TransInfo::center, copy_v3_v3(), TransInfo::data, ED_area_headerprint(), ElementRotation(), TransInfo::flag, TransData::flag, i, invert_m3_m3(), mul_m3_m3m3(), recalcData(), TransInfo::sa, SCE_SELECT_FACE, ToolSettings::selectmode, TransInfo::settings, TransInfo::spacemtx, T_OBJECT, T_POSE, TD_NOACTION, TD_SKIP, and TransInfo::total.
Referenced by initAlign().
void applyAspectRatio (TransInfo * t, float * vec)
Definition at line 259 of file transform.c.
References ED_space_image_size(), ED_space_image_uv_aspect(), ListBase::first, SpaceImage::flag, TransInfo::mode, TransInfo::sa, SI_COORDFLOATS, SPACE_IMAGE, ScrArea::spacedata, TransInfo::spacetype, and TFM_TRANSLATION.
Referenced by headerTranslation().
static void applyRotation (TransInfo * t, float angle, float axis[3]) [static]
Definition at line 3167 of file transform.c.
References TransCon::applyRot, TransInfo::around, TransInfo::con, TransInfo::data, ElementRotation(), TransData::factor, TransInfo::flag, TransData::flag, i, NULL, T_PROP_EDIT, TD_NOACTION, TD_SKIP, TransInfo::total, and vec_rot_to_mat3().
Referenced by Rotation().
static void applySeqSlide (TransInfo * t, float val[2]) [static]
Definition at line 5316 of file transform.c.
References copy_v2_v2(), TransInfo::data, TransData::factor, TransData::flag, i, TransData::iloc, TransData::loc, mul_v2_fl(), TD_NOACTION, TD_SKIP, and TransInfo::total.
Referenced by SeqSlide().
static void applyTimeScale (TransInfo * t) [static]
Definition at line 5854 of file transform.c.
References BKE_nla_tweakedit_remap(), CFRA, TransInfo::data, TransInfo::data2d, doAnimEdit_SnapFrame(), FPS, getAnimEdit_DrawTime(), getAnimEdit_SnapMode(), i, if(), NLATIME_CONVERT_UNMAP, NULL, SACTSNAP_STEP, TransInfo::scene, SPACE_NLA, TransInfo::spacetype, TransInfo::total, and TransInfo::values.
Referenced by TimeScale().
static void applyTimeSlide (TransInfo * t, float sval) [static]
Definition at line 5722 of file transform.c.
References BKE_nla_tweakedit_remap(), CLAMPIS, TransInfo::customData, TransInfo::data, TransData::extra, ListBase::first, i, if(), TransData::ival, NLATIME_CONVERT_UNMAP, NULL, TransInfo::sa, SPACE_ACTION, SPACE_NLA, ScrArea::spacedata, TransInfo::spacetype, SpaceAction::timeslide, TransInfo::total, TransData::val, and TransInfo::values.
Referenced by TimeSlide().
static void applyTimeTranslate (TransInfo * t, float UNUSEDsval) [static]
Definition at line 5581 of file transform.c.
References BKE_nla_tweakedit_remap(), TransInfo::data, TransInfo::data2d, doAnimEdit_SnapFrame(), FPS, getAnimEdit_DrawTime(), getAnimEdit_SnapMode(), i, if(), NLATIME_CONVERT_MAP, NLATIME_CONVERT_UNMAP, NULL, SACTSNAP_STEP, TransInfo::scene, SPACE_NLA, SPACE_SEQ, TransInfo::spacetype, TransInfo::total, and TransInfo::values.
Referenced by TimeTranslate().
static void applyTrackball (TransInfo * t, float axis1[3], float axis2[3], float angles[2]) [static]
Definition at line 3268 of file transform.c.
References TransInfo::around, TransInfo::data, ElementRotation(), TransData::factor, TransInfo::flag, TransData::flag, i, mul_m3_m3m3(), T_PROP_EDIT, TD_NOACTION, TD_SKIP, TransInfo::total, and vec_rot_to_mat3().
Referenced by Trackball().
static void applyTranslation (TransInfo * t, float vec[3]) [static]
Definition at line 3467 of file transform.c.
References add_v3_v3v3(), angle(), TransCon::applyVec, axis_angle_to_quat(), TransData::axismtx, TransInfo::con, constraintTransLim(), copy_v3_v3(), cross_v3_v3v3(), TransInfo::data, dot_v3v3(), ElementRotation(), TransData::factor, TransData::flag, i, TransData::iloc, TransData::loc, mul_m3_v3(), mul_v3_fl(), protectedTransBits(), TransData::protectflag, quat_to_mat3(), saacos(), TransData::smtx, TransSnap::snapNormal, TD_NOACTION, TD_SKIP, TransInfo::total, TransInfo::tsnap, unit_m3(), usingSnappingNormal(), V3D_LOCAL, and validSnappingNormal().
Referenced by Translation().
int BakeTime (TransInfo * t, const int mval[2])
Definition at line 5086 of file transform.c.
References applyNumInput(), TransInfo::center2d, TransInfo::data, ED_area_headerprint(), TransData::ext, TransData::factor, TransData::flag, hasNumInput(), i, TransData::ival, TransInfo::mouse, TransInfo::num, outputNumInput(), MouseInput::precision, MouseInput::precision_mval, TransInfo::proptext, TransDataExtension::quat, recalcData(), TransInfo::sa, TransDataExtension::size, snapGrid(), str, TD_NOACTION, TD_SKIP, TransInfo::total, and TransData::val.
Referenced by initBakeTime().
int Bevel (TransInfo * t, const int UNUSEDmval[2])
Definition at line 3933 of file transform.c.
References applyNumInput(), TransData::axismtx, BME_BEVEL_VERT, TransData::center, TransInfo::data, distance(), ED_area_headerprint(), fabs(), G, hasNumInput(), i, TransData::loc, madd_v3_v3v3fl(), TransInfo::num, outputNumInput(), recalcData(), TransInfo::sa, snapGrid(), str, TransInfo::total, TransData::val, and TransInfo::values.
Referenced by initBevel(), and modifier_type_init().
int BevelWeight (TransInfo * t, const int UNUSEDmval[2])
Definition at line 4001 of file transform.c.
References applyNumInput(), TransInfo::data, ED_area_headerprint(), TransData::factor, TransData::flag, hasNumInput(), i, TransData::ival, TransInfo::num, outputNumInput(), TransInfo::proptext, recalcData(), TransInfo::sa, snapGrid(), str, TD_NOACTION, TransInfo::total, TransData::val, and TransInfo::values.
Referenced by initBevelWeight().
void BIF_selectOrientation (void)
Definition at line 388 of file transform.c.
References BIF_menustringTransformOrientation(), G, MEM_freeN(), and pupmenu().
Referenced by transformEvent().
void BIF_TransformSetUndo (const char * UNUSEDstr)
Definition at line 5917 of file transform.c.
int BoneEnvelope (TransInfo * t, const int UNUSEDmval[2])
Definition at line 4268 of file transform.c.
References applyNumInput(), TransInfo::data, ED_area_headerprint(), TransData::flag, hasNumInput(), i, TransData::ival, TransInfo::num, outputNumInput(), recalcData(), TransInfo::sa, snapGrid(), str, TD_NOACTION, TD_SKIP, TransInfo::total, TransData::val, and TransInfo::values.
Referenced by initBoneEnvelope().
int BoneRoll (TransInfo * t, const int UNUSEDmval[2])
Definition at line 5025 of file transform.c.
References applyNumInput(), TransInfo::data, DEG2RADF, ED_area_headerprint(), TransData::flag, hasNumInput(), i, TransData::ival, TransInfo::num, outputNumInput(), RAD2DEGF, recalcData(), TransInfo::sa, snapGrid(), str, TD_NOACTION, TD_SKIP, TransInfo::total, TransData::val, and TransInfo::values.
Referenced by initBoneRoll().
int BoneSize (TransInfo * t, const int mval[2])
Definition at line 4194 of file transform.c.
References applyNumInput(), TransCon::applySize, TransInfo::con, constraintNumInput(), copy_m3_m3(), TransInfo::data, ED_area_headerprint(), ElementBoneSize(), TransData::flag, TransInfo::flag, hasNumInput(), headerBoneSize(), i, TransInfo::imval, TransInfo::mat, TransCon::mode, NULL, TransInfo::num, recalcData(), TransInfo::sa, size(), size_to_mat3(), snapGrid(), str, T_USES_MANIPULATOR, TD_NOACTION, TD_SKIP, TransInfo::total, and TransInfo::values.
Referenced by initBoneSize().
int calculateTransformCenter (bContext * C, int centerMode, float * vec)
Definition at line 1111 of file transform.c.
References TransInfo::around, calculateCenter(), TransCon::center, TransInfo::con, copy_v3_v3(), createTransData(), CTX_NONE, initTransInfo(), MEM_callocN(), MEM_freeN(), TransInfo::mode, NULL, TransInfo::options, postTrans(), special_aftertrans_update(), TransInfo::state, TFM_DUMMY, TransInfo::total, and TRANS_RUNNING.
Referenced by viewops_data_create().
static void constraintob_from_transdata (bConstraintOb * cob, TransData * td) [static]
Definition at line 2093 of file transform.c.
References axis_angle_to_mat4(), eulO_to_mat4(), TransData::ext, bConstraintOb::matrix, normalize_qt_qt(), TransDataExtension::quat, quat_to_mat4(), TransDataExtension::rot, ROT_MODE_AXISANGLE, ROT_MODE_QUAT, and TransDataExtension::rotOrder.
Referenced by constraintRotLim().
static void constraintRotLim (TransInfo * UNUSEDt, TransData * td) [static]
Definition at line 2122 of file transform.c.
References TransData::con, CONSTRAINT_DISABLE, CONSTRAINT_SPACE_LOCAL, CONSTRAINT_SPACE_WORLD, CONSTRAINT_TYPE_ROTLIMIT, constraintob_from_transdata(), copy_m4_m4(), bConstraint::data, data, ELEM, bConstraint::enforce, bConstraintTypeInfo::evaluate_constraint, TransData::ext, bConstraint::flag, bRotLimitConstraint::flag2, get_constraint_typeinfo(), LIMIT_TRANSFORM, mat4_to_axis_angle(), mat4_to_eulO(), mat4_to_quat(), bConstraintOb::matrix, TransData::mtx, mul_m4_m3m4(), bConstraint::next, NULL, bConstraint::ownspace, TransDataExtension::quat, TransDataExtension::rot, ROT_MODE_AXISANGLE, ROT_MODE_QUAT, TransDataExtension::rotOrder, TransData::smtx, and bConstraint::type.
Referenced by ElementRotation().
static void constraintSizeLim (TransInfo * t, TransData * td) [static]
Definition at line 2192 of file transform.c.
References TransData::con, TransInfo::con, CON_APPLY, CONSTRAINT_DISABLE, CONSTRAINT_SPACE_LOCAL, CONSTRAINT_SPACE_WORLD, CONSTRAINT_TYPE_SIZELIMIT, copy_m4_m4(), data, bConstraint::data, bConstraint::enforce, bConstraintTypeInfo::evaluate_constraint, TransData::ext, bConstraint::flag, TransData::flag, bSizeLimitConstraint::flag2, get_constraint_typeinfo(), LIMIT_TRANSFORM, mat4_to_size(), bConstraintOb::matrix, TransCon::mode, TransData::mtx, mul_m4_m3m4(), bConstraint::next, NULL, bConstraint::ownspace, TransDataExtension::size, size_to_mat4(), TransData::smtx, TD_SINGLESIZE, and bConstraint::type.
Referenced by ElementResize().
static void constraintTransLim (TransInfo * t, TransData * td) [static]
Definition at line 2015 of file transform.c.
References BLI_freelistN(), RenderData::cfra, TransData::con, CONSTRAINT_DISABLE, CONSTRAINT_SPACE_LOCAL, CONSTRAINT_SPACE_WORLD, CONSTRAINT_TYPE_DISTLIMIT, CONSTRAINT_TYPE_LOCLIMIT, copy_m4_m4(), copy_v3_v3(), bConstraint::data, data, bConstraint::enforce, bConstraintTypeInfo::evaluate_constraint, bDistLimitConstraint::flag, bConstraint::flag, bLocLimitConstraint::flag2, get_constraint_targets_for_solving(), get_constraint_typeinfo(), LIMIT_TRANSFORM, LIMITDIST_TRANSFORM, TransData::loc, bConstraintOb::matrix, TransData::mtx, mul_m4_m3m4(), bConstraint::next, NULL, bConstraint::ownspace, Scene::r, TransInfo::scene, TransData::smtx, bConstraint::type, and unit_m4().
Referenced by applyTranslation(), ElementResize(), and ElementRotation().
void convertViewVec (TransInfo * t, float r_vec[3], int dx, int dy)
Definition at line 139 of file transform.c.
References TransInfo::ar, convertViewVec2D(), View2D::cur, ED_space_image_uv_aspect(), ED_view3d_win_to_delta(), ELEM, ListBase::first, View2D::mask, ARegion::regiontype, RGN_TYPE_WINDOW, TransInfo::sa, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_SEQ, SPACE_VIEW3D, ScrArea::spacedata, TransInfo::spacetype, ARegion::v2d, TransInfo::view, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, rctf::ymin, and zero_v3().
Referenced by drawConstraint(), and InputVector().
static void convertViewVec2D (View2D * v2d, float vec[3], int dx, int dy) [static]
Definition at line 127 of file transform.c.
References View2D::cur, View2D::mask, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by convertViewVec().
int Crease (TransInfo * t, const int UNUSEDmval[2])
Definition at line 4074 of file transform.c.
References applyNumInput(), TransInfo::data, ED_area_headerprint(), TransData::factor, TransData::flag, hasNumInput(), i, TransData::ival, TransInfo::num, outputNumInput(), TransInfo::proptext, recalcData(), TransInfo::sa, snapGrid(), str, TD_NOACTION, TD_SKIP, TransInfo::total, TransData::val, and TransInfo::values.
Referenced by initCrease().
static int createSlideVerts (TransInfo * t) [static]
Definition at line 4388 of file transform.c.
References add_v3_v3v3(), TransInfo::ar, BLI_smallhash_haskey(), BLI_smallhash_init(), BLI_smallhash_insert(), BLI_smallhash_lookup(), BLI_smallhash_release(), BMEditMesh::bm, BM_edge_is_manifold(), BM_edge_other_vert(), BM_edge_select_set(), BM_EDGES_OF_MESH, BM_EDGES_OF_VERT, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ELEM_TAG, BM_face_copy(), BM_face_other_edge_loop(), BM_face_select_set(), BM_FACES_OF_VERT, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_vert_select_set(), BM_VERTS_OF_MESH, BMBVH_EdgeVisible(), BMBVH_FreeBVH(), BMBVH_NewBVH(), bmesh_edit_begin(), BMO_OP_FLAG_UNTAN_MULTIRES, BMVert::co, copy_v3_v3(), TransInfo::customData, Object::data, dist_to_line_segment_v2(), TransDataSlideVert::down, TransDataSlideVert::downvec, BMLoop::e, BMVert::e, ED_view3d_ob_project_mat_get(), ED_view3d_project_float_v3(), Mesh::edit_btmesh, SlideData::em, SlideData::end, BMLoop::f, FALSE, ListBase::first, GET_INT_FROM_POINTER, get_next_loop(), get_other_edge(), i, BMEdge::l, MEM_callocN(), MEM_freeN(), mul_v3_fl(), TransInfo::mval, NULL, TransInfo::obedit, SlideData::origfaces, SlideData::origfaces_init, TransDataSlideVert::origvert, SlideData::perc, BMLoop::radial_next, ARegion::regiondata, TransInfo::sa, SET_INT_IN_POINTER, ScrArea::spacedata, SlideData::start, sub_v3_v3v3(), SlideData::sv, table, SlideData::totsv, TRUE, unit_m4(), TransDataSlideVert::up, TransDataSlideVert::upvec, BMLoop::v, TransDataSlideVert::v, BMEdge::v1, BMEdge::v2, SlideData::vhash, and zero_v3().
Referenced by initEdgeSlide().
int CurveShrinkFatten (TransInfo * t, const int UNUSEDmval[2])
Definition at line 3736 of file transform.c.
References applyNumInput(), TransInfo::data, ED_area_headerprint(), TransData::flag, hasNumInput(), i, TransData::ival, TransInfo::num, outputNumInput(), recalcData(), TransInfo::sa, snapGrid(), str, TD_NOACTION, TD_SKIP, TransInfo::total, TransData::val, and TransInfo::values.
Referenced by initCurveShrinkFatten().
static void doAnimEdit_SnapFrame (TransInfo * t, TransData * td, TransData2D * td2d, AnimData * adt, short autosnap) [static]
Definition at line 5449 of file transform.c.
References BKE_nla_tweakedit_remap(), ED_markers_find_nearest_marker_time(), TransData::flag, floorf, FPS, TransData2D::h1, TransData2D::h2, TransData2D::ih1, TransData2D::ih2, TransData::ival, Scene::markers, NLATIME_CONVERT_MAP, NLATIME_CONVERT_UNMAP, SACTSNAP_FRAME, SACTSNAP_MARKER, TransInfo::scene, TD_MOVEHANDLE1, TD_MOVEHANDLE2, and TransData::val.
Referenced by applyTimeScale(), and applyTimeTranslate().
static int doEdgeSlide (TransInfo * t, float perc) [static]
Definition at line 4933 of file transform.c.
References add_v3_v3v3(), copy_v3_v3(), TransInfo::customData, i, mul_v3_fl(), SlideData::perc, projectSVData(), SlideData::sv, and SlideData::totsv.
Referenced by EdgeSlide(), and transformEnd().
static void drawArc (float size, float angle_start, float angle_end, int segments) [static]
Definition at line 1219 of file transform.c.
References angle(), cosf, and sinf.
Referenced by drawHelpline().
static void drawArrow (ArrowDirection d, short offset, short length, short size) [static]
Definition at line 1157 of file transform.c.
References DOWN, LEFT, length(), RIGHT, size(), and UP.
Referenced by drawHelpline().
static void drawArrowHead (ArrowDirection d, short size) [static]
Definition at line 1192 of file transform.c.
References DOWN, LEFT, RIGHT, size(), and UP.
Referenced by drawHelpline().
static void drawHelpline (bContext * UNUSEDC, int x, int y, void * customdata) [static]
Definition at line 1244 of file transform.c.
References angle(), atan2f, TransInfo::center, copy_v3_v3(), cosf, DOWN, drawArc(), drawArrow(), drawArrowHead(), TransInfo::flag, TransInfo::helpline, HLP_ANGLE, HLP_HARROW, HLP_NONE, HLP_SPRING, HLP_TRACKBALL, HLP_VARROW, LEFT, M_PI, MIN2, mul_m4_v3(), TransInfo::mval, TransInfo::obedit, Object::obmat, TransInfo::poseobj, projectFloatView(), RAD2DEGF, RIGHT, setlinestyle(), sinf, sqrtf, T_EDIT, T_POSE, T_USES_MANIPULATOR, TH_GRID, TH_WIRE, UI_GetThemeColor3ubv(), UI_make_axis_color(), UI_ThemeColor(), and UP.
Referenced by initTransform().
static void drawTransformApply (const struct bContext * C, struct ARegion * ar, void * arg) [static]
Referenced by initTransform().
static void drawTransformApply (const bContext * C, struct ARegion * UNUSEDar, void * arg) [static]
Definition at line 1829 of file transform.c.
References TransInfo::redraw, transformApply(), TREDRAW_HARD, and TREDRAW_SOFT.
static void drawTransformView (const struct bContext * C, struct ARegion * UNUSEDar, void * arg) [static]
Definition at line 1379 of file transform.c.
References drawConstraint(), drawPropCircle(), and drawSnapping().
Referenced by initTransform().
int EdgeSlide (TransInfo * t, const int UNUSEDmval[2])
Definition at line 4961 of file transform.c.
References applyNumInput(), CLAMP(), TransInfo::customData, doEdgeSlide(), ED_area_headerprint(), hasNumInput(), TransInfo::num, outputNumInput(), recalcData(), TransInfo::sa, snapGrid(), TransInfo::state, str, TRANS_CANCEL, and TransInfo::values.
Referenced by initEdgeSlide().
static void ElementBoneSize (TransInfo * t, TransData * td, float mat[3][3]) [static]
Definition at line 4174 of file transform.c.
References TransCon::applySize, TransInfo::con, TransData::iloc, TransData::loc, mat3_to_size(), TransData::mtx, mul_m3_m3m3(), size_to_mat3(), and TransData::smtx.
Referenced by BoneSize().
static void ElementResize (TransInfo * t, TransData * td, float mat[3][3]) [static]
Definition at line 2653 of file transform.c.
References add_v3_v3(), add_v3_v3v3(), TransCon::applySize, TransInfo::around, TransData::axismtx, TransInfo::center, TransData::center, TransInfo::con, CON_APPLY, constraintSizeLim(), constraintTransLim(), copy_m3_m3(), copy_v3_v3(), TransData::ext, TransData::factor, TransData::flag, TransInfo::flag, TransData::iloc, TransDataExtension::isize, TransData::ival, TransData::loc, mat3_to_size(), TransCon::mode, TransData::mtx, mul_m3_m3m3(), mul_m3_v3(), mul_v3_fl(), OB_ARMATURE, TransInfo::obedit, protectedSizeBits(), protectedTransBits(), TransData::protectflag, SCE_SELECT_EDGE, SCE_SELECT_FACE, ToolSettings::selectmode, TransInfo::settings, TransDataExtension::size, TransData::smtx, sub_v3_v3(), sub_v3_v3v3(), T_EDIT, T_OBJECT, T_POINTS, T_POSE, T_TEXTURE, T_V3D_ALIGN, TD_SINGLESIZE, TransMat3ToSize(), Object::type, V3D_LOCAL, and TransData::val.
Referenced by Mirror(), and Resize().
static void ElementRotation (TransInfo * t, TransData * td, float mat[3][3], short around) [static]
HACK WARNING
This is some VERY ugly special case to deal with pose mode.
The problem is that mtx and smtx include each bone orientation.
That is needed to rotate each bone properly, HOWEVER, to calculate the translation component, we only need the actual armature object's matrix (and inverse). That is not all though. Once the proper translation has been computed, it has to be converted back into the bone's space.
Definition at line 2950 of file transform.c.
References add_v3_v3(), add_v3_v3v3(), axis_angle_to_quat(), TransData::center, TransInfo::center, constraintRotLim(), constraintTransLim(), copy_m3_m4(), copy_v3_v3(), TransDataExtension::drot, eulO_to_mat3(), TransData::ext, TransData::flag, TransInfo::flag, TransData::iloc, invert_m3_m3(), TransDataExtension::iquat, TransDataExtension::irot, TransDataExtension::irotAngle, TransDataExtension::irotAxis, TransDataExtension::l_smtx, TransData::loc, mat3_to_compatible_eulO(), mat3_to_quat(), TransData::mtx, mul_m3_m3m3(), mul_m3_v3(), mul_qt_qtqt(), mul_serie_m3(), NULL, OB_ARMATURE, TransInfo::obedit, Object::obmat, TransInfo::poseobj, protectedAxisAngleBits(), protectedQuaternionBits(), protectedRotateBits(), protectedTransBits(), TransData::protectflag, TransDataExtension::quat, quat_to_axis_angle(), TransDataExtension::rot, ROT_MODE_AXISANGLE, ROT_MODE_QUAT, TransDataExtension::rotAngle, TransDataExtension::rotAxis, TransDataExtension::rotOrder, SCE_SELECT_EDGE, SCE_SELECT_FACE, ToolSettings::selectmode, TransInfo::settings, TransData::smtx, sub_v3_v3(), sub_v3_v3v3(), T_OBJECT, T_POINTS, T_POSE, T_V3D_ALIGN, TD_NO_LOC, TD_PBONE_LOCAL_MTX_C, TD_PBONE_LOCAL_MTX_P, TD_USEQUAT, Object::type, and V3D_LOCAL.
Referenced by Align(), applyRotation(), applyTrackball(), and applyTranslation().
void freeSlideTempFaces (SlideData * sld)
Definition at line 4844 of file transform.c.
References BLI_smallhash_iternew(), BLI_smallhash_iternext(), BLI_smallhash_release(), BMEditMesh::bm, BM_face_verts_kill(), SlideData::em, FALSE, NULL, SlideData::origfaces, and SlideData::origfaces_init.
Referenced by freeSlideVerts(), and special_aftertrans_update().
void freeSlideVerts (TransInfo * t)
Definition at line 4862 of file transform.c.
References BLI_ghash_lookup(), BLI_smallhash_release(), BMEditMesh::bm, bmesh_edit_end(), BMO_OP_FLAG_UNTAN_MULTIRES, TransInfo::customData, TransDataSlideVert::down, SlideData::em, freeSlideTempFaces(), LinkNode::link, ME_DRAWEXTRA_EDGELEN, MEM_freeN(), LinkNode::next, NULL, recalcData(), SELECT, SlideData::sv, TransDataSlideVert::up, and SlideData::vhash.
Referenced by initEdgeSlide().
static BMLoop* get_next_loop (BMVert * v, BMLoop * l, BMEdge * olde, BMEdge * nexte, float vec[3]) [static]
Definition at line 4329 of file transform.c.
References add_v3_v3(), add_v3_v3v3(), BM_edge_other_vert(), BM_face_other_edge_loop(), BMVert::co, co, copy_v3_v3(), cross_v3_v3v3(), BMLoop::e, BMLoop::f, i, mul_v3_fl(), BMFace::no, NULL, BMLoop::radial_next, and sub_v3_v3v3().
Referenced by createSlideVerts().
static BMEdge* get_other_edge (BMVert * v, BMEdge * e) [static]
Definition at line 4316 of file transform.c.
References BM_EDGES_OF_VERT, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_ELEM, and NULL.
Referenced by createSlideVerts().
static short getAnimEdit_DrawTime (TransInfo * t) [static]
Definition at line 5419 of file transform.c.
References ListBase::first, SpaceIpo::flag, SpaceNla::flag, SpaceAction::flag, TransInfo::sa, SACTION_DRAWTIME, SIPO_DRAWTIME, SNLA_DRAWTIME, SPACE_ACTION, SPACE_IPO, SPACE_NLA, ScrArea::spacedata, and TransInfo::spacetype.
Referenced by applyTimeScale(), applyTimeTranslate(), and headerTimeTranslate().
static short getAnimEdit_SnapMode (TransInfo * t) [static]
Definition at line 5376 of file transform.c.
References SpaceNla::autosnap, SpaceAction::autosnap, SpaceIpo::autosnap, ListBase::first, if(), MOD_SNAP_INVERT, TransInfo::modifiers, TransInfo::sa, SACTSNAP_FRAME, SACTSNAP_OFF, SPACE_ACTION, SPACE_IPO, SPACE_NLA, ScrArea::spacedata, and TransInfo::spacetype.
Referenced by applyTimeScale(), applyTimeTranslate(), and headerTimeTranslate().
int handleEventBevel (TransInfo * t, wmEvent * event)
Definition at line 3900 of file transform.c.
References BME_BEVEL_VERT, G, KM_PRESS, MIDDLEMOUSE, TransInfo::state, TRANS_CANCEL, wmEvent::type, and wmEvent::val.
Referenced by initBevel().
int handleEventShear (TransInfo * t, wmEvent * event)
Definition at line 2464 of file transform.c.
References TransInfo::customData, initMouseInputMode(), INPUT_HORIZONTAL_ABSOLUTE, INPUT_VERTICAL_ABSOLUTE, KM_PRESS, MIDDLEMOUSE, TransInfo::mouse, NULL, wmEvent::type, and wmEvent::val.
Referenced by initShear().
int handleEventWarp (TransInfo * t, wmEvent * event)
Definition at line 2323 of file transform.c.
References TransInfo::customData, KM_PRESS, MIDDLEMOUSE, NULL, wmEvent::type, and wmEvent::val.
Referenced by initWarp().
static void headerBoneSize (TransInfo * t, float vec[3], char * str) [static]
Definition at line 4150 of file transform.c.
References TransInfo::con, CON_APPLY, hasNumInput(), NumInput::idx_max, TransCon::mode, TransInfo::num, outputNumInput(), TransInfo::proptext, and TransCon::text.
Referenced by BoneSize().
static void headerResize (TransInfo * t, float vec[3], char * str) [static]
Definition at line 2592 of file transform.c.
References BLI_snprintf(), TransInfo::con, CON_APPLY, TransInfo::flag, hasNumInput(), NumInput::idx_max, TransCon::mode, TransInfo::num, outputNumInput(), TransInfo::prop_size, TransInfo::proptext, str, T_2D_EDIT, T_PROP_CONNECTED, T_PROP_EDIT, and TransCon::text.
Referenced by Resize().
static void headerSeqSlide (TransInfo * t, float val[2], char * str) [static]
Definition at line 5302 of file transform.c.
References TransInfo::con, hasNumInput(), TransInfo::num, outputNumInput(), and TransCon::text.
Referenced by SeqSlide().
static void headerTimeScale (TransInfo * t, char * str) [static]
Definition at line 5842 of file transform.c.
References hasNumInput(), TransInfo::num, outputNumInput(), and TransInfo::values.
Referenced by TimeScale().
static void headerTimeSlide (TransInfo * t, float sval, char * str) [static]
Definition at line 5700 of file transform.c.
References CLAMP(), TransInfo::customData, hasNumInput(), TransInfo::num, outputNumInput(), and TransInfo::values.
Referenced by TimeSlide().
static void headerTimeTranslate (TransInfo * t, char * str) [static]
Definition at line 5545 of file transform.c.
References floorf, FPS, getAnimEdit_DrawTime(), getAnimEdit_SnapMode(), hasNumInput(), TransInfo::num, outputNumInput(), SACTSNAP_FRAME, SACTSNAP_STEP, TransInfo::scene, and TransInfo::values.
Referenced by TimeTranslate().
static void headerTranslation (TransInfo * t, float vec[3], char * str) [static]
Definition at line 3392 of file transform.c.
References applyAspectRatio(), ToolSettings::autoik_chainlen, B_UNIT_LENGTH, bUnit_AsString(), TransInfo::con, CON_APPLY, copy_v3_v3(), UnitSettings::flag, TransInfo::flag, hasNumInput(), i, NumInput::idx_max, len_v3(), TransCon::mode, TransInfo::num, outputNumInput(), TransInfo::prop_size, TransInfo::proptext, UnitSettings::scale_length, TransInfo::scene, TransInfo::settings, str, UnitSettings::system, T_2D_EDIT, T_AUTOIK, T_PROP_CONNECTED, T_PROP_EDIT, TransCon::text, Scene::unit, USER_UNIT_OPT_SPLIT, and NumInput::val.
Referenced by Translation().
static int helpline_poll (bContext * C) [static]
Definition at line 1235 of file transform.c.
References CTX_wm_region(), ARegion::regiontype, and RGN_TYPE_WINDOW.
Referenced by initTransform().
void initAlign (TransInfo * t)
Definition at line 5228 of file transform.c.
References Align(), TransInfo::flag, initMouseInputMode(), INPUT_NONE, TransInfo::mouse, T_NO_CONSTRAINT, and TransInfo::transform.
Referenced by initTransform().
void initBakeTime (TransInfo * t)
Definition at line 5072 of file transform.c.
References BakeTime(), NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_NONE, TransInfo::mouse, TransInfo::num, TransInfo::snap, and TransInfo::transform.
Referenced by initTransform().
void initBevel (TransInfo * t)
Definition at line 3868 of file transform.c.
References Bevel(), NumInput::flag, TransInfo::flag, G, TransInfo::handleEvent, handleEventBevel(), NumInput::idx_max, TransInfo::idx_max, TransInfo::imval, NumInput::increment, initMouseInputMode(), INPUT_HORIZONTAL_ABSOLUTE, TransInfo::mode, TransInfo::mouse, TransInfo::num, NUM_NO_NEGATIVE, TransInfo::snap, T_NO_CONSTRAINT, TFM_BEVEL, and TransInfo::transform.
Referenced by initTransform().
void initBevelWeight (TransInfo * t)
Definition at line 3983 of file transform.c.
References BevelWeight(), TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_SPRING, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::snap, T_NO_CONSTRAINT, T_NO_PROJECT, TFM_BWEIGHT, and TransInfo::transform.
Referenced by initTransform().
void initBoneEnvelope (TransInfo * t)
Definition at line 4250 of file transform.c.
References BoneEnvelope(), TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_SPRING, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::snap, T_NO_CONSTRAINT, T_NO_PROJECT, TFM_BONE_ENVELOPE, and TransInfo::transform.
Referenced by initTransform().
void initBoneRoll (TransInfo * t)
Definition at line 5007 of file transform.c.
References BoneRoll(), TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_ANGLE, M_PI, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::snap, T_NO_CONSTRAINT, T_NO_PROJECT, TFM_BONE_ROLL, and TransInfo::transform.
Referenced by initTransform().
void initBoneSize (TransInfo * t)
Definition at line 4132 of file transform.c.
References BoneSize(), NumInput::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_SPRING_FLIP, TransInfo::mode, TransInfo::mouse, TransInfo::num, NUM_AFFECT_ALL, NUM_NULL_ONE, TransInfo::snap, TFM_BONESIZE, and TransInfo::transform.
Referenced by initTransform().
void initCrease (TransInfo * t)
Definition at line 4056 of file transform.c.
References Crease(), TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_SPRING, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::snap, T_NO_CONSTRAINT, T_NO_PROJECT, TFM_CREASE, and TransInfo::transform.
Referenced by initTransform().
void initCurveShrinkFatten (TransInfo * t)
Definition at line 3715 of file transform.c.
References CurveShrinkFatten(), NumInput::flag, TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_SPRING, TransInfo::mode, TransInfo::mouse, TransInfo::num, NUM_NO_ZERO, TransInfo::snap, T_NO_CONSTRAINT, T_NO_ZERO, TFM_CURVE_SHRINKFATTEN, and TransInfo::transform.
Referenced by initTransform().
void initEdgeSlide (TransInfo * t)
Definition at line 4899 of file transform.c.
References createSlideVerts(), TransInfo::customData, TransInfo::customFree, EdgeSlide(), SlideData::end, TransInfo::flag, freeSlideVerts(), NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_CUSTOM_RATIO, TransInfo::mode, TransInfo::mouse, TransInfo::num, setCustomPoints(), TransInfo::snap, SlideData::start, TransInfo::state, T_NO_CONSTRAINT, T_NO_PROJECT, TFM_EDGE_SLIDE, TRANS_CANCEL, and TransInfo::transform.
Referenced by initTransform().
void initMirror (TransInfo * t)
Definition at line 5150 of file transform.c.
References TransInfo::flag, initMouseInputMode(), INPUT_NONE, Mirror(), TransInfo::mouse, TransInfo::obedit, T_NO_ZERO, T_NULL_ONE, and TransInfo::transform.
Referenced by initTransform().
void initPushPull (TransInfo * t)
Definition at line 3783 of file transform.c.
References NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_VERTICAL_ABSOLUTE, TransInfo::mode, TransInfo::mouse, TransInfo::num, PushPull(), TransInfo::snap, TFM_PUSHPULL, and TransInfo::transform.
Referenced by initTransform().
void initResize (TransInfo * t)
Definition at line 2568 of file transform.c.
References NumInput::flag, TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_SPRING_FLIP, TransInfo::mode, TransInfo::mouse, TransInfo::num, NUM_AFFECT_ALL, NUM_NO_ZERO, NUM_NULL_ONE, TransInfo::obedit, Resize(), TransInfo::snap, T_NO_ZERO, T_NULL_ONE, TFM_RESIZE, and TransInfo::transform.
Referenced by initShrinkFatten(), initTransform(), and transformEvent().
void initRotation (TransInfo * t)
Definition at line 2925 of file transform.c.
References TransInfo::axis, TransInfo::axis_orig, copy_v3_v3(), TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_ANGLE, M_PI, TransInfo::mode, TransInfo::mouse, negate_v3_v3(), normalize_v3(), TransInfo::num, postInputRotation(), Rotation(), setInputPostFct(), TransInfo::snap, T_2D_EDIT, T_NO_CONSTRAINT, TFM_ROTATION, TransInfo::transform, and TransInfo::viewinv.
Referenced by initTransform(), and transformEvent().
void initSeqSlide (TransInfo * t)
Definition at line 5285 of file transform.c.
References NumInput::flag, RenderData::frs_sec, RenderData::frs_sec_base, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_VECTOR, TransInfo::mouse, TransInfo::num, Scene::r, TransInfo::scene, SeqSlide(), TransInfo::snap, and TransInfo::transform.
Referenced by initTransform().
void initShear (TransInfo * t)
Definition at line 2444 of file transform.c.
References TransInfo::flag, TransInfo::handleEvent, handleEventShear(), NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_HORIZONTAL_ABSOLUTE, TransInfo::mode, TransInfo::mouse, TransInfo::num, postInputShear(), setInputPostFct(), Shear(), TransInfo::snap, T_NO_CONSTRAINT, TFM_SHEAR, and TransInfo::transform.
Referenced by initTransform().
void initShrinkFatten (TransInfo * t)
Definition at line 3568 of file transform.c.
References TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), initResize(), INPUT_VERTICAL_ABSOLUTE, TransInfo::mode, TransInfo::mouse, NULL, TransInfo::num, OB_MESH, TransInfo::obedit, ShrinkFatten(), TransInfo::snap, T_NO_CONSTRAINT, TFM_SHRINKFATTEN, TransInfo::transform, and Object::type.
Referenced by initTransform().
void initTilt (TransInfo * t)
Definition at line 3646 of file transform.c.
References TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_ANGLE, M_PI, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::snap, T_NO_CONSTRAINT, T_NO_PROJECT, TFM_TILT, Tilt(), and TransInfo::transform.
Referenced by initTransform().
void initTimeScale (TransInfo * t)
Definition at line 5802 of file transform.c.
References TransInfo::center, RenderData::cfra, ELEM, NumInput::flag, TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, TransInfo::imval, NumInput::increment, initMouseInput(), initMouseInputMode(), INPUT_SPRING_FLIP, TransInfo::mode, TransInfo::mouse, TransInfo::num, NUM_NULL_ONE, projectIntView(), Scene::r, TransInfo::scene, TransInfo::snap, SPACE_ACTION, SPACE_NLA, TransInfo::spacetype, TransInfo::state, T_NULL_ONE, TFM_TIME_SCALE, TimeScale(), TRANS_CANCEL, and TransInfo::transform.
Referenced by initTransform().
void initTimeSlide (TransInfo * t)
Definition at line 5668 of file transform.c.
References ListBase::first, SpaceAction::flag, NumInput::flag, TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_NONE, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::sa, SACTION_MOVING, TransInfo::snap, SPACE_ACTION, ScrArea::spacedata, TransInfo::spacetype, TransInfo::state, T_FREE_CUSTOMDATA, TFM_TIME_SLIDE, TimeSlide(), TRANS_CANCEL, and TransInfo::transform.
Referenced by initTransform().
void initTimeTranslate (TransInfo * t)
Definition at line 5521 of file transform.c.
References ELEM, NumInput::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_NONE, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::snap, SPACE_ACTION, SPACE_SEQ, TransInfo::spacetype, TransInfo::state, TFM_TIME_TRANSLATE, TimeTranslate(), TRANS_CANCEL, and TransInfo::transform.
Referenced by initTransform().
void initToSphere (TransInfo * t)
Definition at line 2824 of file transform.c.
References TransInfo::center, TransInfo::data, NumInput::flag, TransInfo::flag, i, NumInput::idx_max, TransInfo::idx_max, TransData::iloc, NumInput::increment, initMouseInputMode(), INPUT_HORIZONTAL_RATIO, len_v3v3(), TransInfo::mode, TransInfo::mouse, TransInfo::num, NUM_NO_NEGATIVE, NUM_NULL_ONE, TransInfo::snap, T_NO_CONSTRAINT, TFM_TOSPHERE, ToSphere(), TransInfo::total, TransInfo::transform, and TransInfo::val.
Referenced by initTransform().
void initTrackball (TransInfo * t)
Definition at line 3250 of file transform.c.
References TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_TRACKBALL, M_PI, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::snap, T_NO_CONSTRAINT, TFM_TRACKBALL, Trackball(), and TransInfo::transform.
Referenced by initTransform(), and transformEvent().
int initTransform (bContext * C, TransInfo * t, wmOperator * op, wmEvent * event, int mode)
Definition at line 1519 of file transform.c.
References wmEvent::alt, TransInfo::ar, ARM_ENVELOPE, TransInfo::auto_values, TransInfo::axis, TransInfo::axis_orig, C, calculateCenter(), calculatePropRatio(), TransInfo::center2d, TransInfo::con, CON_APPLY, CON_AXIS0, CON_AXIS1, CON_AXIS2, TransInfo::context, copy_v3_v3(), copy_v4_v4(), createTransData(), wmEvent::ctrl, CTX_MOVIECLIP, CTX_TEXTURE, CTX_wm_manager(), TransInfo::current_orientation, Object::data, TransInfo::draw_handle_apply, TransInfo::draw_handle_cursor, TransInfo::draw_handle_view, drawHelpline(), drawTransformApply(), drawTransformView(), bArmature::drawtype, ED_region_draw_cb_activate(), ELEM, EVT_TWEAK_L, EVT_TWEAK_R, ListBase::first, TransInfo::flag, helpline_poll(), TransInfo::imval, initAlign(), initBakeTime(), initBevel(), initBevelWeight(), initBoneEnvelope(), initBoneRoll(), initBoneSize(), initCrease(), initCurveShrinkFatten(), initEdgeSlide(), initMirror(), initMouseInput(), initPushPull(), initResize(), initRotation(), initSeqSlide(), initShear(), initShrinkFatten(), initSnapping(), initTilt(), initTimeScale(), initTimeSlide(), initTimeTranslate(), initToSphere(), initTrackball(), initTransformOrientation(), initTransInfo(), initTranslation(), initWarp(), wmKeyMap::items, KM_PRESS, TransInfo::launch_event, LEFTALTKEY, LEFTCTRLKEY, LEFTMOUSE, LEFTSHIFTKEY, MOD_SNAP_INVERT, wmOperatorType::modalkeymap, TransCon::mode, TransInfo::mode, TransInfo::modifiers, TransInfo::mouse, wmKeyMapItem::next, normalize_v3(), NULL, options, TransInfo::options, wmEvent::oskey, OSKEY, TransInfo::poseobj, postTrans(), wmKeyMapItem::propvalue, wmOperator::ptr, REGION_DRAW_POST_VIEW, REGION_DRAW_PRE_VIEW, RIGHTALTKEY, RIGHTCTRLKEY, RIGHTMOUSE, RIGHTSHIFTKEY, RNA_float_get(), RNA_float_get_array(), RNA_property_array_check(), RNA_property_boolean_get(), RNA_property_boolean_get_array(), RNA_property_float_get_array(), RNA_property_is_set(), RNA_struct_find_property(), setUserConstraint(), wmEvent::shift, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_VIEW3D, TransInfo::spacemtx, TransInfo::spacetype, TransInfo::state, T_AUTOVALUES, TFM_ALIGN, TFM_BAKE_TIME, TFM_BEVEL, TFM_BONE_ENVELOPE, TFM_BONE_ROLL, TFM_BONESIZE, TFM_BWEIGHT, TFM_CREASE, TFM_CURVE_SHRINKFATTEN, TFM_EDGE_SLIDE, TFM_MIRROR, TFM_MODAL_SNAP_INV_ON, TFM_PUSHPULL, TFM_RESIZE, TFM_ROTATION, TFM_SEQ_SLIDE, TFM_SHEAR, TFM_SHRINKFATTEN, TFM_TILT, TFM_TIME_DUPLICATE, TFM_TIME_EXTEND, TFM_TIME_SCALE, TFM_TIME_SLIDE, TFM_TIME_TRANSLATE, TFM_TOSPHERE, TFM_TRACKBALL, TFM_TRANSLATION, TFM_WARP, TransInfo::total, TRANS_CANCEL, TRANS_STARTING, wmKeyMapItem::type, wmOperator::type, ARegion::type, unit_m3(), wmKeyMapItem::val, TransInfo::values, WM_keymap_active(), and WM_paint_cursor_activate().
Referenced by transformops_data().
void initTranslation (TransInfo * t)
Definition at line 3354 of file transform.c.
References TransInfo::ar, ELEM, NumInput::flag, TransInfo::flag, RegionView3D::gridview, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_VECTOR, TransInfo::mode, TransInfo::mouse, TransInfo::num, ARegion::regiondata, TransInfo::snap, SPACE_ACTION, SPACE_CLIP, SPACE_IMAGE, SPACE_VIEW3D, TransInfo::spacetype, TransInfo::state, T_2D_EDIT, TFM_TRANSLATION, TRANS_CANCEL, TransInfo::transform, and Translation().
Referenced by initTransform(), and transformEvent().
void initWarp (TransInfo * t)
Definition at line 2280 of file transform.c.
References TransInfo::center, TransData::center, copy_v3_v3(), TransInfo::data, TransInfo::flag, TransInfo::handleEvent, handleEventWarp(), i, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_HORIZONTAL_RATIO, M_PI, max, mid_v3_v3v3(), min, minmax_v3v3_v3(), TransInfo::mode, TransInfo::mouse, TransData::mtx, mul_m3_v3(), mul_m4_v3(), TransInfo::num, postInputWarp(), setInputPostFct(), TransInfo::snap, sub_v3_v3(), T_NO_CONSTRAINT, TFM_WARP, TransInfo::total, TransInfo::transform, TransInfo::val, TransInfo::viewmat, and Warp().
Referenced by initTransform().
int Mirror (TransInfo * t, const int UNUSEDmval[2])
Definition at line 5161 of file transform.c.
References TransCon::applySize, TransInfo::con, CON_APPLY, TransInfo::data, ED_area_headerprint(), ElementResize(), TransInfo::flag, TransData::flag, i, TransCon::mode, NULL, recalcData(), TransInfo::sa, size(), size_to_mat3(), str, T_2D_EDIT, TD_NOACTION, TD_SKIP, and TransCon::text.
Referenced by initMirror(), and modifier_type_init().
static void postInputRotation (TransInfo * t, float values[3]) [static]
Definition at line 2918 of file transform.c.
References TransCon::applyRot, TransInfo::axis, TransInfo::con, CON_APPLY, TransCon::mode, and NULL.
Referenced by initRotation().
static void postInputShear (TransInfo * UNUSEDt, float values[3]) [static]
Definition at line 2439 of file transform.c.
References mul_v3_fl().
Referenced by initShear().
static void postInputWarp (TransInfo * t, float values[3]) [static]
Definition at line 2270 of file transform.c.
References TransInfo::customData, M_PI, mul_v3_fl(), and negate_v3().
Referenced by initWarp().
void projectFloatView (TransInfo * t, const float vec[3], float adr[2])
Definition at line 232 of file transform.c.
References TransInfo::ar, project_float_noclip(), projectIntView(), ARegion::regiontype, RGN_TYPE_WINDOW, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_VIEW3D, TransInfo::spacetype, and zero_v2().
Referenced by drawHelpline().
void projectIntView (TransInfo * t, const float vec[3], int adr[2])
Definition at line 179 of file transform.c.
References TransInfo::ar, ED_space_image_uv_aspect(), ELEM, ListBase::first, SpaceAction::flag, project_int_noclip(), ARegion::regiontype, RGN_TYPE_WINDOW, TransInfo::sa, SACTION_DRAWTIME, SPACE_ACTION, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_SEQ, SPACE_VIEW3D, ScrArea::spacedata, TransInfo::spacetype, UI_view2d_to_region_no_clip(), and TransInfo::view.
Referenced by calculateCenter(), calculateCenter2D(), initTimeScale(), projectFloatView(), and setNearestAxis3d().
void projectSVData (TransInfo * t, int final)
Definition at line 4698 of file transform.c.
References BLI_assert, BLI_smallhash_haskey(), BLI_smallhash_init(), BLI_smallhash_insert(), BLI_smallhash_lookup(), BLI_smallhash_release(), BMEditMesh::bm, BM_EDGES_OF_VERT, BM_elem_attrs_copy(), BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_hide_set, BM_ELEM_SELECT, BM_face_select_set(), BM_FACES_OF_VERT, BM_ITER_ELEM, BM_loop_interp_from_face(), BM_loop_interp_multires(), BM_LOOPS_OF_FACE, BM_vert_in_face(), TransInfo::customData, TransDataSlideVert::down, BMLoop::e, SlideData::em, BMLoop::f, FALSE, i, BMEdge::l, NULL, SlideData::origfaces, SlideData::perc, BMLoop::prev, BMLoop::radial_next, TransInfo::settings, BMesh::shapenr, SlideData::sv, TransDataSlideVert::up, ToolSettings::uvcalc_flag, UVCALC_TRANSFORM_CORRECT, BMLoop::v, and TransDataSlideVert::v.
Referenced by doEdgeSlide(), and special_aftertrans_update().
static void protectedAxisAngleBits (short protectflag, float axis[3], float * angle, float oldAxis[3], float oldAngle) [static]
Definition at line 1924 of file transform.c.
References axis_angle_to_eulO(), EULER_ORDER_DEFAULT, eulO_to_axis_angle(), IS_EQF, OB_LOCK_ROT4D, OB_LOCK_ROTW, OB_LOCK_ROTX, OB_LOCK_ROTY, and OB_LOCK_ROTZ.
Referenced by ElementRotation().
static void protectedQuaternionBits (short protectflag, float * quat, float * oldquat) [static]
Definition at line 1966 of file transform.c.
References eul_to_quat(), mul_qt_fl(), normalize_qt_qt(), OB_LOCK_ROT4D, OB_LOCK_ROTW, OB_LOCK_ROTX, OB_LOCK_ROTY, OB_LOCK_ROTZ, and quat_to_eul().
Referenced by ElementRotation().
static void protectedRotateBits (short protectflag, float * eul, float * oldeul) [static]
Definition at line 1911 of file transform.c.
References OB_LOCK_ROTX, OB_LOCK_ROTY, and OB_LOCK_ROTZ.
Referenced by ElementRotation().
static void protectedSizeBits (short protectflag, float * size) [static]
Definition at line 1901 of file transform.c.
References OB_LOCK_SCALEX, OB_LOCK_SCALEY, and OB_LOCK_SCALEZ.
Referenced by ElementResize().
static void protectedTransBits (short protectflag, float * vec) [static]
Definition at line 1891 of file transform.c.
References OB_LOCK_LOCX, OB_LOCK_LOCY, and OB_LOCK_LOCZ.
Referenced by applyTranslation(), ElementResize(), and ElementRotation().
int PushPull (TransInfo * t, const int UNUSEDmval[2])
Definition at line 3800 of file transform.c.
References add_v3_v3v3(), applyNumInput(), TransCon::applyRot, TransData::center, TransInfo::center, TransInfo::con, CON_APPLY, TransInfo::data, distance(), ED_area_headerprint(), TransData::factor, TransData::flag, hasNumInput(), i, TransData::iloc, isLockConstraint(), TransData::loc, TransCon::mode, mul_v3_fl(), normalize_v3(), NULL, TransInfo::num, outputNumInput(), project_v3_v3v3(), TransInfo::proptext, recalcData(), TransInfo::sa, snapGrid(), str, sub_v3_v3(), sub_v3_v3v3(), TD_NOACTION, TD_SKIP, TransCon::text, TransInfo::total, and TransInfo::values.
Referenced by initPushPull().
void removeAspectRatio (TransInfo * t, float * vec)
Definition at line 279 of file transform.c.
References ED_space_image_size(), ED_space_image_uv_aspect(), ListBase::first, SpaceImage::flag, TransInfo::mode, TransInfo::sa, SI_COORDFLOATS, SPACE_IMAGE, ScrArea::spacedata, TransInfo::spacetype, and TFM_TRANSLATION.
Referenced by postConstraintChecks(), and Translation().
int Resize (TransInfo * t, const int mval[2])
Definition at line 2749 of file transform.c.
References applyNumInput(), TransCon::applySize, applySnapping(), TransInfo::auto_values, clipUVTransform(), TransInfo::con, constraintNumInput(), copy_m3_m3(), copy_v3_v3(), TransInfo::data, ED_area_headerprint(), ElementResize(), TransData::flag, TransInfo::flag, hasNumInput(), headerResize(), i, TransInfo::imval, TransInfo::mat, TransCon::mode, NULL, TransInfo::num, recalcData(), TransInfo::sa, size(), size_to_mat3(), snapGrid(), str, T_AUTOVALUES, T_CLIP_UV, T_USES_MANIPULATOR, TD_NOACTION, TD_SKIP, and TransInfo::values.
Referenced by initResize().
int Rotation (TransInfo * t, const int UNUSEDmval[2])
Definition at line 3195 of file transform.c.
References angle_wrap_rad(), applyNumInput(), TransCon::applyRot, applyRotation(), applySnapping(), TransInfo::axis, TransInfo::axis_orig, TransInfo::con, CON_APPLY, copy_v3_v3(), DEG2RADF, ED_area_headerprint(), TransInfo::flag, hasNumInput(), TransCon::mode, NULL, TransInfo::num, outputNumInput(), TransInfo::prop_size, TransInfo::proptext, RAD2DEGF, recalcData(), TransInfo::sa, snapGrid(), str, T_PROP_CONNECTED, T_PROP_EDIT, TransCon::text, and TransInfo::values.
Referenced by KDL::Frame::DH(), KDL::Frame::DH_Craig1989(), diff(), initRotation(), KDL::operator*(), and Rot().
void saveTransform (bContext * C, TransInfo * t, wmOperator * op)
Definition at line 1397 of file transform.c.
References TransInfo::auto_values, TransInfo::axis, TransInfo::con, CON_APPLY, CON_AXIS0, CON_AXIS1, CON_AXIS2, CTX_data_tool_settings(), TransInfo::current_orientation, TransInfo::flag, if(), MOD_SNAP, TransCon::mode, TransInfo::mode, TransInfo::modifiers, TransInfo::obedit, TransCon::orientation, PROP_EDIT_CONNECTED, PROP_EDIT_OFF, PROP_EDIT_ON, ToolSettings::prop_mode, TransInfo::prop_mode, TransInfo::prop_size, ToolSettings::proportional, ToolSettings::proportional_objects, ToolSettings::proportional_size, wmOperator::ptr, RNA_enum_set(), RNA_float_set(), RNA_property_array_check(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_enum_set(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_is_set(), RNA_struct_find_property(), SCE_SNAP, ToolSettings::snap_flag, SPACE_VIEW3D, TransInfo::spacetype, T_AUTOVALUES, T_MIRROR, T_MODAL, T_PROP_CONNECTED, T_PROP_EDIT, View3D::twmode, TransInfo::values, and TransInfo::view.
Referenced by transformops_exit().
int SeqSlide (TransInfo * t, const int UNUSEDmval[2])
Definition at line 5339 of file transform.c.
References applyNumInput(), applySeqSlide(), TransCon::applyVec, TransInfo::con, CON_APPLY, copy_v3_v3(), ED_area_headerprint(), headerSeqSlide(), TransCon::mode, NULL, TransInfo::num, recalcData(), TransInfo::sa, snapGrid(), str, and TransInfo::values.
Referenced by initSeqSlide().
void setTransformViewMatrices (TransInfo * t)
Definition at line 105 of file transform.c.
References TransInfo::ar, calculateCenter2D(), copy_m4_m4(), TransInfo::persinv, RegionView3D::persinv, RegionView3D::persmat, TransInfo::persmat, TransInfo::persp, RegionView3D::persp, ARegion::regiondata, ARegion::regiontype, RGN_TYPE_WINDOW, RV3D_ORTHO, SPACE_VIEW3D, TransInfo::spacetype, unit_m4(), RegionView3D::viewinv, TransInfo::viewinv, RegionView3D::viewmat, and TransInfo::viewmat.
Referenced by initTransInfo(), and view_editmove().
int Shear (TransInfo * t, const int UNUSEDmval[2])
Definition at line 2488 of file transform.c.
References add_v3_v3(), add_v3_v3v3(), applyNumInput(), TransInfo::center, TransData::center, copy_m3_m3(), copy_m3_m4(), TransInfo::customData, TransInfo::data, ED_area_headerprint(), TransData::factor, TransData::flag, hasNumInput(), i, TransData::iloc, invert_m3_m3(), TransData::loc, TransData::mtx, mul_m3_m3m3(), mul_m3_v3(), mul_v3_fl(), NULL, TransInfo::num, TransInfo::obedit, outputNumInput(), TransInfo::proptext, recalcData(), TransInfo::sa, TransData::smtx, snapGrid(), str, sub_v3_v3(), sub_v3_v3v3(), TD_NOACTION, TD_SKIP, TransInfo::total, unit_m3(), TransInfo::values, and TransInfo::viewmat.
Referenced by initShear().
int ShrinkFatten (TransInfo * t, const int UNUSEDmval[2])
Definition at line 3594 of file transform.c.
References add_v3_v3v3(), applyNumInput(), TransData::axismtx, copy_v3_v3(), TransInfo::data, distance(), ED_area_headerprint(), TransData::factor, TransData::flag, hasNumInput(), i, TransData::iloc, TransData::loc, mul_v3_fl(), TransInfo::num, outputNumInput(), TransInfo::proptext, recalcData(), TransInfo::sa, snapGrid(), str, TD_NOACTION, TD_SKIP, TransInfo::total, and TransInfo::values.
Referenced by initShrinkFatten().
int Tilt (TransInfo * t, const int UNUSEDmval[2])
Definition at line 3666 of file transform.c.
References applyNumInput(), TransInfo::data, DEG2RADF, ED_area_headerprint(), TransData::factor, TransData::flag, hasNumInput(), i, TransData::ival, TransInfo::num, outputNumInput(), TransInfo::proptext, RAD2DEGF, recalcData(), TransInfo::sa, snapGrid(), str, TD_NOACTION, TD_SKIP, TransInfo::total, TransData::val, and TransInfo::values.
Referenced by initTilt().
int TimeScale (TransInfo * t, const int UNUSEDmval[2])
Definition at line 5896 of file transform.c.
References applyNumInput(), applyTimeScale(), ED_area_headerprint(), headerTimeScale(), TransInfo::num, recalcData(), TransInfo::sa, str, TransInfo::values, and TransInfo::vec.
Referenced by initTimeScale().
int TimeSlide (TransInfo * t, const int mval[2])
Definition at line 5769 of file transform.c.
References applyNumInput(), applyTimeSlide(), TransInfo::customData, ED_area_headerprint(), headerTimeSlide(), TransInfo::imval, TransInfo::num, recalcData(), TransInfo::sa, str, UI_view2d_region_to_view(), TransInfo::values, TransInfo::vec, and TransInfo::view.
Referenced by initTimeSlide().
int TimeTranslate (TransInfo * t, const int mval[2])
Definition at line 5638 of file transform.c.
References applyNumInput(), applyTimeTranslate(), ED_area_headerprint(), headerTimeTranslate(), TransInfo::imval, TransInfo::num, recalcData(), TransInfo::sa, str, UI_view2d_region_to_view(), TransInfo::values, TransInfo::vec, and TransInfo::view.
Referenced by initTimeTranslate().
int ToSphere (TransInfo * t, const int UNUSEDmval[2])
Definition at line 2853 of file transform.c.
References add_v3_v3v3(), applyNumInput(), TransInfo::center, TransInfo::data, ED_area_headerprint(), TransData::factor, TransData::flag, hasNumInput(), i, TransData::iloc, TransData::loc, mul_v3_fl(), normalize_v3(), TransInfo::num, outputNumInput(), TransInfo::proptext, recalcData(), TransInfo::sa, snapGrid(), str, sub_v3_v3v3(), TD_NOACTION, TD_SKIP, TransInfo::total, TransInfo::val, and TransInfo::values.
Referenced by initToSphere().
int Trackball (TransInfo * t, const int UNUSEDmval[2])
Definition at line 3297 of file transform.c.
References applyNumInput(), applyTrackball(), copy_v3_v3(), DEG2RADF, ED_area_headerprint(), TransInfo::flag, hasNumInput(), mul_m3_m3m3(), normalize_v3(), TransInfo::num, outputNumInput(), TransInfo::persinv, TransInfo::prop_size, TransInfo::proptext, RAD2DEGF, recalcData(), TransInfo::sa, snapGrid(), str, T_PROP_CONNECTED, T_PROP_EDIT, TransInfo::values, and vec_rot_to_mat3().
Referenced by initTrackball().
wmKeyMap* transform_modal_keymap (wmKeyConfig * keyconf) [read]
Definition at line 511 of file transform.c.
References AKEY, ESCKEY, GKEY, KM_ALT, KM_ANY, KM_PRESS, KM_RELEASE, KM_SHIFT, LEFTCTRLKEY, LEFTMOUSE, wmKeyMap::modal_items, NULL, NUM_MODAL_INCREMENT_DOWN, NUM_MODAL_INCREMENT_UP, PADENTER, PAGEDOWNKEY, PAGEUPKEY, RETKEY, RIGHTCTRLKEY, RKEY, SKEY, TABKEY, TFM_MODAL_ADD_SNAP, TFM_MODAL_AUTOIK_LEN_DEC, TFM_MODAL_AUTOIK_LEN_INC, TFM_MODAL_AXIS_X, TFM_MODAL_AXIS_Y, TFM_MODAL_AXIS_Z, TFM_MODAL_CANCEL, TFM_MODAL_CONFIRM, TFM_MODAL_CONS_OFF, TFM_MODAL_PLANE_X, TFM_MODAL_PLANE_Y, TFM_MODAL_PLANE_Z, TFM_MODAL_PROPSIZE_DOWN, TFM_MODAL_PROPSIZE_UP, TFM_MODAL_REMOVE_SNAP, TFM_MODAL_RESIZE, TFM_MODAL_ROTATE, TFM_MODAL_SNAP_INV_OFF, TFM_MODAL_SNAP_INV_ON, TFM_MODAL_SNAP_TOGGLE, TFM_MODAL_TRANSLATE, WHEELDOWNMOUSE, WHEELUPMOUSE, WM_modalkeymap_add(), WM_modalkeymap_add_item(), and WM_modalkeymap_get().
Referenced by transform_keymap_for_space().
void transformApply (bContext * C, TransInfo * t)
Definition at line 1796 of file transform.c.
References BKE_ptcache_get_continue_physics(), C, TransInfo::context, CTX_AUTOCONFIRM, TransInfo::draw_handle_apply, TransInfo::mval, NULL, TransInfo::options, TransInfo::redraw, selectConstraint(), TransInfo::state, TRANS_CONFIRM, TransInfo::transform, TREDRAW_HARD, TREDRAW_NOTHING, TREDRAW_SOFT, and viewRedrawForce().
Referenced by drawTransformApply(), special_aftertrans_update(), transform_exec(), and transform_modal().
int transformEnd (bContext * C, TransInfo * t)
Definition at line 1839 of file transform.c.
References C, TransInfo::context, doEdgeSlide(), TransInfo::mode, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, postTrans(), restoreTransObjects(), special_aftertrans_update(), TransInfo::state, TFM_EDGE_SLIDE, TRANS_CANCEL, TRANS_RUNNING, TRANS_STARTING, TransInfo::undostr, viewRedrawForce(), and viewRedrawPost().
Referenced by transform_cancel(), transform_exec(), and transform_modal().
int transformEvent (TransInfo * t, wmEvent * event)
Definition at line 581 of file transform.c.
References addSnapPoint(), wmEvent::alt, applyMouseInput(), BIF_selectOrientation(), calc_manipulator_stats(), calculatePropRatio(), CKEY, TransInfo::con, CON_APPLY, CON_AXIS0, CON_AXIS1, CON_AXIS2, CON_SELECT, constraintModeToChar(), copy_m3_m4(), copy_v2_v2_int(), CTX_MOVIECLIP, CTX_TEXTURE, TransInfo::current_orientation, ELEM3, ELEM4, ESCKEY, EVT_MODAL_MAP, TransInfo::flag, G, GKEY, TransInfo::handleEvent, handleMouseInput(), handleNumInput(), handleSnapping(), initResize(), initRotation(), initSelectConstraint(), initSnapping(), initTrackball(), initTranslation(), KM_PRESS, KM_RELEASE, TransInfo::launch_event, LEFTMOUSE, LEFTSHIFTKEY, MAT3_UNITY, MIDDLEMOUSE, MIN2, MOD_CONSTRAINT_PLANE, MOD_CONSTRAINT_SELECT, MOD_SNAP, MOD_SNAP_INVERT, TransCon::mode, TransInfo::mode, TransInfo::modifiers, TransInfo::mouse, MOUSEMOVE, wmEvent::mval, TransInfo::mval, NULL, TransInfo::num, OKEY, OPERATOR_PASS_THROUGH, TransInfo::options, TransCon::orientation, PADENTER, PADMINUS, PADPLUSKEY, PAGEDOWNKEY, PAGEUPKEY, TransInfo::persp, postSelectConstraint(), TransInfo::prop_mode, PROP_MODE_MAX, TransInfo::prop_size, TransInfo::redraw, removeSnapPoint(), resetTransRestrictions(), restoreTransObjects(), RETKEY, RIGHTMOUSE, RIGHTSHIFTKEY, RKEY, RV3D_ORTHO, setLocalConstraint(), setUserConstraint(), wmEvent::shift, SKEY, sort_trans_data_dist(), SPACE_VIEW3D, SPACEKEY, TransInfo::spacemtx, TransInfo::spacename, TransInfo::spacetype, TransInfo::state, stopConstraint(), T_2D_EDIT, T_ALT_TRANSFORM, T_AUTOIK, T_CAMERA, T_NO_CONSTRAINT, T_PROP_CONNECTED, T_PROP_EDIT, T_RELEASE_CONFIRM, TFM_MODAL_ADD_SNAP, TFM_MODAL_AUTOIK_LEN_DEC, TFM_MODAL_AUTOIK_LEN_INC, TFM_MODAL_AXIS_X, TFM_MODAL_AXIS_Y, TFM_MODAL_AXIS_Z, TFM_MODAL_CANCEL, TFM_MODAL_CONFIRM, TFM_MODAL_CONS_OFF, TFM_MODAL_PLANE_X, TFM_MODAL_PLANE_Y, TFM_MODAL_PLANE_Z, TFM_MODAL_PROPSIZE_DOWN, TFM_MODAL_PROPSIZE_UP, TFM_MODAL_REMOVE_SNAP, TFM_MODAL_RESIZE, TFM_MODAL_ROTATE, TFM_MODAL_SNAP_INV_OFF, TFM_MODAL_SNAP_INV_ON, TFM_MODAL_SNAP_TOGGLE, TFM_MODAL_TRANSLATE, TFM_RESIZE, TFM_ROTATION, TFM_TRACKBALL, TFM_TRANSLATION, TRANS_CANCEL, TRANS_CONFIRM, TRANS_RUNNING, TRANS_STARTING, transform_autoik_update(), TREDRAW_HARD, wmEvent::type, V3D_MANIP_GLOBAL, V3D_MANIP_LOCAL, wmEvent::val, TransInfo::values, TransInfo::view, view_editmove(), WHEELDOWNMOUSE, WHEELUPMOUSE, XKEY, YKEY, and ZKEY.
Referenced by transform_modal().
int Translation (TransInfo * t, const int UNUSEDmval[2])
Definition at line 3528 of file transform.c.
References applyNumInput(), applySnapping(), applyTranslation(), TransCon::applyVec, clipUVTransform(), TransInfo::con, CON_APPLY, copy_v3_v3(), ED_area_headerprint(), TransInfo::flag, hasNumInput(), headerTranslation(), TransCon::mode, NULL, TransInfo::num, recalcData(), removeAspectRatio(), TransInfo::sa, snapGrid(), str, T_CLIP_UV, and TransInfo::values.
Referenced by initTranslation().
static void TransMat3ToSize (float mat[][3], float smat[][3], float * size) [static]
Definition at line 2635 of file transform.c.
References copy_v3_v3(), normalize_v3(), and VECSIGNFLIP.
Referenced by ElementResize().
static void view_editmove (unsigned short UNUSEDevent) [static]
Definition at line 402 of file transform.c.
References G, LR_ALTKEY, LR_CTRLKEY, LR_SHIFTKEY, PAD2, PAD4, PAD6, PAD8, PADMINUS, PADPLUSKEY, setTransformViewMatrices(), T_2D_EDIT, USER_WHEELZOOMDIR, WHEELDOWNMOUSE, and WHEELUPMOUSE.
Referenced by transformEvent().
static void viewRedrawForce (const bContext * C, TransInfo * t) [static]
Definition at line 299 of file transform.c.
References TransInfo::animtimer, Object::data, ED_area_tag_redraw(), ED_space_clip(), ListBase::first, TransInfo::flag, if(), IS_AUTOKEY_ON, SpaceImage::lock, NA_EDITED, NC_ANIMATION, NC_GEOM, NC_MOVIECLIP, NC_OBJECT, NC_SCENE, NC_SPACE, ND_DATA, ND_KEYFRAME, ND_KEYS, ND_NLA, ND_POSE, ND_SEQUENCER, ND_SPACE_NODE_VIEW, ND_TRANSFORM, NULL, TransInfo::obedit, TransInfo::sa, TransInfo::scene, SPACE_ACTION, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_SEQ, SPACE_VIEW3D, ScrArea::spacedata, TransInfo::spacetype, T_POSE, and WM_event_add_notifier().
Referenced by transformApply(), and transformEnd().
static void viewRedrawPost (bContext * C, TransInfo * t) [static]
Definition at line 350 of file transform.c.
References CTX_data_scene(), ED_area_headerprint(), ELEM3, IS_AUTOKEY_ON, NA_EDITED, NC_ANIMATION, NC_SCENE, ND_KEYFRAME, ND_TRANSFORM_DONE, NULL, REDRAWACTION, REDRAWBUTSOBJECT, REDRAWIPO, REDRAWNLA, TransInfo::sa, TransInfo::scene, SPACE_ACTION, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_VIEW3D, TransInfo::spacetype, WM_event_add_notifier(), and WM_main_add_notifier().
Referenced by transformEnd().
int Warp (TransInfo * t, const int UNUSEDmval[2])
Definition at line 2341 of file transform.c.
References add_v3_v3v3(), applyNumInput(), co, copy_v3_v3(), cos(), TransInfo::data, DEG2RADF, ED_area_headerprint(), TransData::factor, TransData::flag, TransInfo::flag, give_cursor(), hasNumInput(), i, TransData::iloc, TransData::loc, TransData::mtx, mul_m3_v3(), mul_m4_v3(), mul_v3_fl(), TransInfo::num, TransInfo::obedit, Object::obmat, outputNumInput(), RAD2DEGF, recalcData(), TransInfo::sa, TransInfo::scene, si, sin(), TransData::smtx, snapGrid(), str, sub_v3_v3(), T_EDIT, TD_NOACTION, TD_SKIP, TransInfo::total, TransInfo::val, TransInfo::values, TransInfo::view, TransInfo::viewinv, and TransInfo::viewmat.
Referenced by initWarp(), and modifier_type_init().