Blender: avirgb.c File Reference
avirgb.c File Reference
AVI
#include "AVI_avi.h"
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "avirgb.h"
Functions
void * avi_converter_from_avi_rgb (AviMovie *movie, int stream, unsigned char *buffer, int *size)
void * avi_converter_to_avi_rgb (AviMovie *movie, int stream, unsigned char *buffer, int *size)
Detailed Description
Definition in file avirgb.c.
Function Documentation
void* avi_converter_from_avi_rgb (AviMovie * movie, int stream, unsigned char * buffer, int * size)
Definition at line 46 of file avirgb.c.
References _AviBitmapInfoHeader::BitCount, _AviMovie::header, _AviMainHeader::Height, i, if(), MEM_freeN(), MEM_mallocN(), _AviStreamRec::sf, _AviMovie::streams, and _AviMainHeader::Width.
Referenced by avi_format_convert().
void* avi_converter_to_avi_rgb (AviMovie * movie, int stream, unsigned char * buffer, int * size)
Definition at line 120 of file avirgb.c.
References _AviMovie::header, _AviMainHeader::Height, i, MEM_freeN(), MEM_mallocN(), and _AviMainHeader::Width.
Referenced by avi_format_convert().