Blender: BKE_gpencil.h File Reference
BKE_gpencil.h File Reference
blenkernel
Functions
void free_gpencil_strokes (struct bGPDframe *gpf)
void free_gpencil_frames (struct bGPDlayer *gpl)
void free_gpencil_layers (struct ListBase *list)
void free_gpencil_data (struct bGPdata *gpd)
struct bGPDframe * gpencil_frame_addnew (struct bGPDlayer *gpl, int cframe)
struct bGPDlayer * gpencil_layer_addnew (struct bGPdata *gpd)
struct bGPdata * gpencil_data_addnew (const char name[])
struct bGPDframe * gpencil_frame_duplicate (struct bGPDframe *src)
struct bGPDlayer * gpencil_layer_duplicate (struct bGPDlayer *src)
struct bGPdata * gpencil_data_duplicate (struct bGPdata *gpd)
void gpencil_frame_delete_laststroke (struct bGPDlayer *gpl, struct bGPDframe *gpf)
struct bGPDframe * gpencil_layer_getframe (struct bGPDlayer *gpl, int cframe, short addnew)
void gpencil_layer_delframe (struct bGPDlayer *gpl, struct bGPDframe *gpf)
struct bGPDlayer * gpencil_layer_getactive (struct bGPdata *gpd)
void gpencil_layer_setactive (struct bGPdata *gpd, struct bGPDlayer *active)
void gpencil_layer_delactive (struct bGPdata *gpd)
Detailed Description
Author:
Joshua Leung
Definition in file BKE_gpencil.h.
Function Documentation
void free_gpencil_data (struct bGPdata * gpd)
Definition at line 111 of file gpencil.c.
References free_gpencil_layers(), and bGPdata::layers.
Referenced by free_libblock(), gpencil_undo_finish(), and gpencil_undo_push().
void free_gpencil_frames (struct bGPDlayer * gpl)
Definition at line 75 of file gpencil.c.
References BLI_freelinkN(), ListBase::first, bGPDlayer::frames, free_gpencil_strokes(), bGPDframe::next, and NULL.
Referenced by animchannels_delete_exec(), free_gpencil_layers(), and gpencil_layer_delactive().
void free_gpencil_layers (struct ListBase * list)
Definition at line 93 of file gpencil.c.
References BLI_freelinkN(), ListBase::first, free_gpencil_frames(), bGPDlayer::next, and NULL.
Referenced by ED_undo_gpencil_step(), and free_gpencil_data().
void free_gpencil_strokes (struct bGPDframe * gpf)
Definition at line 57 of file gpencil.c.
References BLI_freelinkN(), ListBase::first, MEM_freeN(), bGPDstroke::next, NULL, bGPDstroke::points, and bGPDframe::strokes.
Referenced by free_gpencil_frames(), and gpencil_layer_delframe().
struct bGPdata* gpencil_data_addnew (const char name[]) [read]
Definition at line 196 of file gpencil.c.
References alloc_libblock(), bGPdata::flag, G, GP_DATA_DISPINFO, GP_DATA_EXPAND, GP_DATA_VIEWALIGN, and ID_GD.
Referenced by gp_data_add_exec(), gp_layer_add_exec(), and gp_session_initdata().
struct bGPdata* gpencil_data_duplicate (struct bGPdata * gpd) [read]
Definition at line 275 of file gpencil.c.
References BLI_addtail(), ListBase::first, gpencil_layer_duplicate(), ListBase::last, bGPdata::layers, MEM_dupallocN(), bGPDlayer::next, and NULL.
Referenced by gpencil_undo_push().
struct bGPDframe* gpencil_frame_addnew (struct bGPDlayer * gpl, int cframe) [read]
Definition at line 120 of file gpencil.c.
References BLI_addtail(), BLI_insertlinkbefore(), ListBase::first, bGPDframe::framenum, bGPDlayer::frames, MEM_callocN(), MEM_freeN(), bGPDframe::next, NULL, and state.
Referenced by gpencil_layer_getframe().
void gpencil_frame_delete_laststroke (struct bGPDlayer * gpl, struct bGPDframe * gpf)
Definition at line 302 of file gpencil.c.
References BLI_freelinkN(), ELEM, ListBase::first, bGPDframe::framenum, gpencil_layer_delframe(), gpencil_layer_getframe(), ListBase::last, MEM_freeN(), NULL, bGPDstroke::points, and bGPDframe::strokes.
struct bGPDframe* gpencil_frame_duplicate (struct bGPDframe * src) [read]
Definition at line 217 of file gpencil.c.
References BLI_addtail(), ListBase::first, ListBase::last, MEM_dupallocN(), bGPDstroke::next, bGPDframe::next, NULL, bGPDstroke::points, bGPDframe::prev, and bGPDframe::strokes.
Referenced by duplicate_gplayer_frames(), and gpencil_layer_duplicate().
struct bGPDlayer* gpencil_layer_addnew (struct bGPdata * gpd) [read]
Definition at line 166 of file gpencil.c.
References BLI_addtail(), BLI_uniquename(), bGPDlayer::color, gpencil_layer_setactive(), bGPDlayer::info, bGPdata::layers, MEM_callocN(), NULL, and bGPDlayer::thickness.
Referenced by gp_layer_add_exec(), and gp_paint_initstroke().
void gpencil_layer_delactive (struct bGPdata * gpd)
Definition at line 499 of file gpencil.c.
References BLI_freelinkN(), ELEM, free_gpencil_frames(), gpencil_layer_getactive(), bGPdata::layers, and NULL.
Referenced by gp_ui_dellayer_cb().
void gpencil_layer_delframe (struct bGPDlayer * gpl, struct bGPDframe * gpf)
Definition at line 450 of file gpencil.c.
References bGPDlayer::actframe, BLI_freelinkN(), ELEM, bGPDlayer::frames, free_gpencil_strokes(), and NULL.
Referenced by delete_gplayer_frames(), gp_actframe_delete_exec(), gpencil_frame_delete_laststroke(), and posttrans_gpd_clean().
struct bGPDlayer* gpencil_layer_duplicate (struct bGPDlayer * src) [read]
Definition at line 245 of file gpencil.c.
References bGPDlayer::actframe, BLI_addtail(), ListBase::first, bGPDlayer::frames, gpencil_frame_duplicate(), ListBase::last, MEM_dupallocN(), bGPDlayer::next, bGPDframe::next, NULL, and bGPDlayer::prev.
Referenced by ED_undo_gpencil_step(), and gpencil_data_duplicate().
struct bGPDlayer* gpencil_layer_getactive (struct bGPdata * gpd) [read]
Definition at line 463 of file gpencil.c.
References ELEM, ListBase::first, bGPDlayer::flag, GP_LAYER_ACTIVE, bGPdata::layers, bGPDlayer::next, and NULL.
Referenced by gp_actframe_delete_exec(), gp_actframe_delete_poll(), gp_convert_layer_exec(), gp_convert_poll(), gp_paint_initstroke(), and gpencil_layer_delactive().
struct bGPDframe* gpencil_layer_getframe (struct bGPDlayer * gpl, int cframe, short addnew) [read]
Definition at line 328 of file gpencil.c.
References abs(), bGPDlayer::actframe, ListBase::first, bGPDframe::flag, bGPDlayer::flag, bGPDframe::framenum, bGPDlayer::frames, GP_FRAME_PAINT, GP_LAYER_FRAMELOCK, GP_LAYER_LOCKED, gpencil_frame_addnew(), ListBase::last, bGPDframe::next, NULL, and bGPDframe::prev.
Referenced by gp_actframe_delete_exec(), gp_draw_data(), gp_layer_to_curve(), gp_paint_initstroke(), and gpencil_frame_delete_laststroke().
void gpencil_layer_setactive (struct bGPdata * gpd, struct bGPDlayer * active)
Definition at line 482 of file gpencil.c.
References ELEM3, ListBase::first, bGPDlayer::flag, GP_LAYER_ACTIVE, bGPdata::layers, bGPDlayer::next, and NULL.
Referenced by gp_ui_activelayer_cb(), gp_ui_dellayer_cb(), and gpencil_layer_addnew().