Blender: AUD_DynamicIIRFilterReader Class Reference
AUD_DynamicIIRFilterReader Class Reference
#include <AUD_DynamicIIRFilterReader.h>
Public Member Functions
AUD_DynamicIIRFilterReader (AUD_Reference< AUD_IReader > reader, AUD_Reference< AUD_DynamicIIRFilterFactory > factory)
virtual void sampleRateChanged (AUD_SampleRate rate)
Detailed Description
This class is for dynamic infinite impulse response filters with simple coefficients that change depending on the sample rate.
Definition at line 39 of file AUD_DynamicIIRFilterReader.h.
Constructor & Destructor Documentation
AUD_DynamicIIRFilterReader::AUD_DynamicIIRFilterReader (AUD_Reference< AUD_IReader > reader, AUD_Reference< AUD_DynamicIIRFilterFactory > factory)
Definition at line 31 of file AUD_DynamicIIRFilterReader.cpp.
References sampleRateChanged().
Member Function Documentation
void AUD_DynamicIIRFilterReader::sampleRateChanged (AUD_SampleRate rate) [virtual]
Notifies the filter about a sample rate change.
Parameters:
rate The new sample rate.
Reimplemented from AUD_BaseIIRFilterReader.
Definition at line 39 of file AUD_DynamicIIRFilterReader.cpp.
References AUD_IIRFilterReader::setCoefficients().
Referenced by AUD_DynamicIIRFilterReader().
The documentation for this class was generated from the following files:
AUD_DynamicIIRFilterReader.h
AUD_DynamicIIRFilterReader.cpp