Blender: FilterNormal Class Reference
FilterNormal Class Reference
pixel filter for normal mapping
#include <FilterNormal.h>
Public Member Functions
FilterNormal (void)
constructor
virtual ~FilterNormal (void)
destructor
unsigned short getColor (void)
get index of color used to calculate normals
void setColor (unsigned short colIdx)
set index of color used to calculate normals
float getDepth (void)
get depth
void setDepth (float depth)
set depth
Protected Member Functions
template<class SRC >
unsigned int tFilter (SRC *src, short x, short y, short *size, unsigned int pixSize, unsigned int val=0)
filter pixel, source int buffer
virtual unsigned int filter (unsigned char *src, short x, short y, short *size, unsigned int pixSize, unsigned int val=0)
filter pixel, source byte buffer
virtual unsigned int filter (unsigned int *src, short x, short y, short *size, unsigned int pixSize, unsigned int val=0)
filter pixel, source int buffer
Protected Attributes
float m_depth
depth of normal relief
float m_depthScale
scale to calculate normals
unsigned short m_colIdx
color index, 0=red, 1=green, 2=blue, 3=alpha
Detailed Description
pixel filter for normal mapping
Definition at line 41 of file FilterNormal.h.
Constructor & Destructor Documentation
FilterNormal::FilterNormal (void)
constructor
Definition at line 38 of file FilterNormal.cpp.
References setDepth().
virtual FilterNormal::~FilterNormal (void) [inline, virtual]
destructor
Definition at line 47 of file FilterNormal.h.
Member Function Documentation
virtual unsigned int FilterNormal::filter (unsigned char * src, short x, short y, short * size, unsigned int pixSize, unsigned int val = 0) [inline, protected, virtual]
filter pixel, source byte buffer
Reimplemented from FilterBase.
Definition at line 101 of file FilterNormal.h.
References tFilter().
virtual unsigned int FilterNormal::filter (unsigned int * src, short x, short y, short * size, unsigned int pixSize, unsigned int val = 0) [inline, protected, virtual]
filter pixel, source int buffer
Reimplemented from FilterBase.
Definition at line 105 of file FilterNormal.h.
References tFilter().
unsigned short FilterNormal::getColor (void) [inline]
get index of color used to calculate normals
Definition at line 50 of file FilterNormal.h.
References m_colIdx.
float FilterNormal::getDepth (void) [inline]
get depth
Definition at line 55 of file FilterNormal.h.
References m_depth.
void FilterNormal::setColor (unsigned short colIdx)
set index of color used to calculate normals
Definition at line 45 of file FilterNormal.cpp.
References m_colIdx.
void FilterNormal::setDepth (float depth)
set depth
Definition at line 54 of file FilterNormal.cpp.
References depthScaleKoef, m_depth, and m_depthScale.
Referenced by FilterNormal().
template<class SRC > unsigned int FilterNormal::tFilter (SRC * src, short x, short y, short * size, unsigned int pixSize, unsigned int val = 0) [inline, protected]
filter pixel, source int buffer
Definition at line 69 of file FilterNormal.h.
References FilterBase::convertPrevious(), m_colIdx, m_depthScale, normScaleKoef, sqrt(), VT_C, and VT_RGBA.
Referenced by filter().
Member Data Documentation
unsigned short FilterNormal::m_colIdx [protected]
color index, 0=red, 1=green, 2=blue, 3=alpha
Definition at line 66 of file FilterNormal.h.
Referenced by getColor(), setColor(), and tFilter().
float FilterNormal::m_depth [protected]
depth of normal relief
Definition at line 61 of file FilterNormal.h.
Referenced by getDepth(), and setDepth().
float FilterNormal::m_depthScale [protected]
scale to calculate normals
Definition at line 63 of file FilterNormal.h.
Referenced by setDepth(), and tFilter().
The documentation for this class was generated from the following files:
FilterNormal.h
FilterNormal.cpp