Blender: DocumentExporter Class Reference
DocumentExporter Class Reference
#include <DocumentExporter.h>
Public Member Functions
DocumentExporter (const ExportSettings *export_settings)
void exportCurrentScene (Scene *sce)
void exportScenes (const char *filename)
Detailed Description
Definition at line 34 of file DocumentExporter.h.
Constructor & Destructor Documentation
DocumentExporter::DocumentExporter (const ExportSettings * export_settings)
Definition at line 147 of file DocumentExporter.cpp.
Member Function Documentation
void DocumentExporter::exportCurrentScene (Scene * sce)
Definition at line 153 of file DocumentExporter.cpp.
References BLENDER_SUBVERSION, BLENDER_VERSION, build_rev, clear_global_id_map(), ArmatureExporter::export_controllers(), AnimationExporter::exportAnimations(), CamerasExporter::exportCameras(), EffectsExporter::exportEffects(), GeometryExporter::exportGeom(), ImagesExporter::exportImages(), LightsExporter::exportLights(), MaterialsExporter::exportMaterials(), SceneExporter::exportScene(), ExportSettings::filepath, has_object_type(), Scene::id, id_name(), OB_ARMATURE, OB_CAMERA, OB_LAMP, OB_MESH, RNA_float_get(), RNA_id_pointer_create(), RNA_pointer_get(), RNA_property_enum_get(), RNA_struct_find_property(), translate_id(), USER_UNIT_IMPERIAL, USER_UNIT_METRIC, and USER_UNIT_NONE.
Referenced by collada_export().
void DocumentExporter::exportScenes (const char * filename)
Definition at line 284 of file DocumentExporter.cpp.
The documentation for this class was generated from the following files:
DocumentExporter.h
DocumentExporter.cpp