Blender: node_shader_tex_sky.c File Reference
node_shader_tex_sky.c File Reference
#include "../node_shader_util.h"
Functions
static void node_shader_init_tex_sky (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static int node_shader_gpu_tex_sky (GPUMaterial *mat, bNode *node, GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_tex_sky (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_tex_sky_in []
static bNodeSocketTemplate sh_node_tex_sky_out []
Function Documentation
static int node_shader_gpu_tex_sky (GPUMaterial * mat, bNode * node, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 55 of file node_shader_tex_sky.c.
References CD_ORCO, GPU_attribute(), GPU_stack_link(), link(), GPUNodeStack::link, and node_shader_gpu_tex_mapping().
Referenced by register_node_type_sh_tex_sky().
static void node_shader_init_tex_sky (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 42 of file node_shader_tex_sky.c.
References NodeTexSky::base, NodeTexBase::color_mapping, default_color_mapping(), default_tex_mapping(), MEM_callocN(), bNode::storage, NodeTexSky::sun_direction, NodeTexBase::tex_mapping, and NodeTexSky::turbidity.
Referenced by register_node_type_sh_tex_sky().
void register_node_type_sh_tex_sky (bNodeTreeType * ttype)
Definition at line 66 of file node_shader_tex_sky.c.
References NODE_CLASS_TEXTURE, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OPTIONS, node_shader_gpu_tex_sky(), node_shader_init_tex_sky(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_SKY.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_tex_sky_in[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 1, "Vector",       0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_NONE, SOCK_HIDE_VALUE},
    {   -1, 0, ""   }
}
Definition at line 32 of file node_shader_tex_sky.c.
bNodeSocketTemplate sh_node_tex_sky_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Color",      0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_shader_tex_sky.c.