Blender: space_sequencer.c File Reference
space_sequencer.c File Reference
sequencer
#include <string.h>
#include <stdio.h>
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "BKE_sequencer.h"
#include "BKE_global.h"
#include "ED_space_api.h"
#include "ED_sequencer.h"
#include "ED_screen.h"
#include "ED_view3d.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "sequencer_intern.h"
Functions
ARegion * sequencer_has_buttons_region (ScrArea *sa)
static ARegion * sequencer_find_region (ScrArea *sa, short type)
static SpaceLink * sequencer_new (const bContext *C)
static void sequencer_free (SpaceLink *UNUSED(sl))
static void sequencer_init (struct wmWindowManager *UNUSED(wm), ScrArea *UNUSED(sa))
static void sequencer_refresh (const bContext *C, ScrArea *sa)
static SpaceLink * sequencer_duplicate (SpaceLink *sl)
static void sequencer_main_area_init (wmWindowManager *wm, ARegion *ar)
static void sequencer_main_area_draw (const bContext *C, ARegion *ar)
static int image_drop_poll (bContext *UNUSED(C), wmDrag *drag, wmEvent *UNUSED(event))
static int movie_drop_poll (bContext *UNUSED(C), wmDrag *drag, wmEvent *UNUSED(event))
static int sound_drop_poll (bContext *UNUSED(C), wmDrag *drag, wmEvent *UNUSED(event))
static void sequencer_drop_copy (wmDrag *drag, wmDropBox *drop)
static void sequencer_dropboxes (void)
static void sequencer_header_area_init (wmWindowManager *UNUSED(wm), ARegion *ar)
static void sequencer_header_area_draw (const bContext *C, ARegion *ar)
static void sequencer_main_area_listener (ARegion *ar, wmNotifier *wmn)
static void sequencer_preview_area_init (wmWindowManager *wm, ARegion *ar)
static void sequencer_preview_area_draw (const bContext *C, ARegion *ar)
static void sequencer_preview_area_listener (ARegion *ar, wmNotifier *wmn)
static void sequencer_buttons_area_init (wmWindowManager *wm, ARegion *ar)
static void sequencer_buttons_area_draw (const bContext *C, ARegion *ar)
static void sequencer_buttons_area_listener (ARegion *ar, wmNotifier *wmn)
void ED_spacetype_sequencer (void)
Detailed Description
Definition in file space_sequencer.c.
Function Documentation
void ED_spacetype_sequencer (void)
Definition at line 527 of file space_sequencer.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::dropboxes, SpaceType::duplicate, ED_KEYMAP_ANIMATION, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_MARKERS, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, ED_view3d_draw_offscreen_imbuf_simple(), SpaceType::free, G, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_PREVIEW, RGN_TYPE_UI, RGN_TYPE_WINDOW, sequencer_buttons_area_draw(), sequencer_buttons_area_init(), sequencer_buttons_area_listener(), sequencer_dropboxes(), sequencer_duplicate(), sequencer_free(), sequencer_header_area_draw(), sequencer_header_area_init(), sequencer_init(), sequencer_keymap(), sequencer_main_area_draw(), sequencer_main_area_init(), sequencer_main_area_listener(), sequencer_new(), sequencer_operatortypes(), sequencer_preview_area_draw(), sequencer_preview_area_init(), sequencer_preview_area_listener(), sequencer_refresh(), sequencer_view3d_cb, SPACE_SEQ, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
static int image_drop_poll (bContext * UNUSEDC, wmDrag * drag, wmEvent * UNUSEDevent) [static]
Definition at line 327 of file space_sequencer.c.
References ELEM, wmDrag::icon, wmDrag::type, and WM_DRAG_PATH.
Referenced by sequencer_dropboxes().
static int movie_drop_poll (bContext * UNUSEDC, wmDrag * drag, wmEvent * UNUSEDevent) [static]
Definition at line 335 of file space_sequencer.c.
References ELEM3, wmDrag::icon, wmDrag::type, and WM_DRAG_PATH.
Referenced by sequencer_dropboxes().
static void sequencer_buttons_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 497 of file space_sequencer.c.
References ED_region_panels(), and NULL.
Referenced by ED_spacetype_sequencer().
static void sequencer_buttons_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 490 of file space_sequencer.c.
References ED_region_panels_init().
Referenced by ED_spacetype_sequencer().
static void sequencer_buttons_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 502 of file space_sequencer.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NA_RENAME, NC_ID, NC_SCENE, NC_SPACE, ND_FRAME, ND_SEQUENCER, and ND_SPACE_SEQUENCER.
Referenced by ED_spacetype_sequencer().
static void sequencer_drop_copy (wmDrag * drag, wmDropBox * drop) [static]
Definition at line 351 of file space_sequencer.c.
References BLI_split_dirfile(), FILE_MAX, wmDrag::path, wmDropBox::ptr, RNA_collection_add(), RNA_collection_clear(), RNA_string_set(), and RNA_struct_find_property().
Referenced by sequencer_dropboxes().
static void sequencer_dropboxes (void) [static]
Definition at line 372 of file space_sequencer.c.
References image_drop_poll(), movie_drop_poll(), RGN_TYPE_WINDOW, sequencer_drop_copy(), sound_drop_poll(), SPACE_SEQ, WM_dropbox_add(), and WM_dropboxmap_find().
Referenced by ED_spacetype_sequencer().
static SpaceLink* sequencer_duplicate (SpaceLink * sl) [static]
Definition at line 282 of file space_sequencer.c.
References MEM_dupallocN().
Referenced by ED_spacetype_sequencer().
static ARegion* sequencer_find_region (ScrArea * sa, short type) [static]
Definition at line 87 of file space_sequencer.c.
References ListBase::first, ARegion::next, NULL, ScrArea::regionbase, and ARegion::regiontype.
Referenced by sequencer_refresh().
static void sequencer_free (SpaceLink * UNUSEDsl) [static]
Definition at line 185 of file space_sequencer.c.
Referenced by ED_spacetype_sequencer().
ARegion* sequencer_has_buttons_region (ScrArea * sa) [read]
Definition at line 63 of file space_sequencer.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_RIGHT, RGN_FLAG_HIDDEN, RGN_TYPE_HEADER, and RGN_TYPE_UI.
Referenced by sequencer_properties().
static void sequencer_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 389 of file space_sequencer.c.
References ED_region_header().
Referenced by ED_spacetype_sequencer().
static void sequencer_header_area_init (wmWindowManager * UNUSEDwm, ARegion * ar) [static]
Definition at line 384 of file space_sequencer.c.
References ED_region_header_init().
Referenced by ED_spacetype_sequencer().
static void sequencer_init (struct wmWindowManager * UNUSEDwm, ScrArea * UNUSEDsa) [static]
Definition at line 195 of file space_sequencer.c.
Referenced by ED_spacetype_sequencer().
static void sequencer_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 317 of file space_sequencer.c.
References draw_timeline_seq().
Referenced by ED_spacetype_sequencer().
static void sequencer_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 296 of file space_sequencer.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, RGN_TYPE_WINDOW, SPACE_SEQ, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_CUSTOM, ARegion::winrct, ARegion::winx, ARegion::winy, WM_dropboxmap_find(), WM_event_add_dropbox_handler(), WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_sequencer().
static void sequencer_main_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 394 of file space_sequencer.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NA_RENAME, NC_ID, NC_SCENE, NC_SPACE, ND_FRAME, ND_FRAME_RANGE, ND_MARKERS, ND_RENDER_OPTIONS, ND_SEQUENCER, and ND_SPACE_SEQUENCER.
Referenced by ED_spacetype_sequencer().
static SpaceLink* sequencer_new (const bContext * C) [static]
Definition at line 100 of file space_sequencer.c.
References View2D::align, ARegion::alignment, BLI_addtail(), SpaceSeq::chanshown, CTX_data_scene(), View2D::cur, RenderData::efra, ARegion::flag, View2D::keeptot, View2D::keepzoom, SpaceSeq::mainb, View2D::max, MAXFRAMEF, MAXSEQ, View2D::maxzoom, MEM_callocN(), View2D::min, View2D::minzoom, Scene::r, SpaceSeq::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_ALIGN_RIGHT, RGN_ALIGN_TOP, RGN_FLAG_HIDDEN, RGN_TYPE_HEADER, RGN_TYPE_PREVIEW, RGN_TYPE_UI, RGN_TYPE_WINDOW, View2D::scroll, SEQ_DRAW_IMG_IMBUF, SEQ_VIEW_SEQUENCE, SPACE_SEQ, SpaceSeq::spacetype, View2D::tot, ARegion::v2d, V2D_ALIGN_FREE, V2D_ALIGN_NO_NEG_Y, V2D_KEEPASPECT, V2D_KEEPTOT_FREE, V2D_KEEPZOOM, V2D_SCROLL_BOTTOM, V2D_SCROLL_LEFT, V2D_SCROLL_SCALE_HORIZONTAL, V2D_SCROLL_SCALE_VERTICAL, SpaceSeq::view, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by ED_spacetype_sequencer().
static void sequencer_preview_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 435 of file space_sequencer.c.
References RenderData::cfra, CTX_data_scene(), CTX_wm_area(), draw_image_seq(), Scene::ed, ListBase::first, SpaceSeq::mainb, Editing::over_cfra, Editing::over_flag, Editing::over_ofs, Scene::r, SEQ_DRAW_IMG_IMBUF, SEQ_DRAW_SEQUENCE, SEQ_EDIT_OVERLAY_ABS, SEQ_EDIT_OVERLAY_SHOW, and ScrArea::spacedata.
Referenced by ED_spacetype_sequencer().
static void sequencer_preview_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 421 of file space_sequencer.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, SPACE_SEQ, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_CUSTOM, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_sequencer().
static void sequencer_preview_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 460 of file space_sequencer.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NA_RENAME, NC_ID, NC_SCENE, NC_SPACE, ND_FRAME, ND_MARKERS, ND_SEQUENCER, and ND_SPACE_SEQUENCER.
Referenced by ED_spacetype_sequencer().
static void sequencer_refresh (const bContext * C, ScrArea * sa) [static]
Definition at line 200 of file space_sequencer.c.
References ARegion::alignment, CTX_wm_manager(), CTX_wm_window(), View2D::cur, ED_area_initialize(), ED_area_tag_redraw(), ListBase::first, View2D::flag, ARegion::flag, ARegion::handlers, RGN_ALIGN_NONE, RGN_ALIGN_TOP, RGN_FLAG_HIDDEN, RGN_TYPE_PREVIEW, RGN_TYPE_WINDOW, SEQ_VIEW_PREVIEW, SEQ_VIEW_SEQUENCE, SEQ_VIEW_SEQUENCE_PREVIEW, sequencer_find_region(), ScrArea::spacedata, View2D::tot, ARegion::v2d, V2D_IS_INITIALISED, SpaceSeq::view, and WM_event_remove_handlers().
Referenced by ED_spacetype_sequencer().
static int sound_drop_poll (bContext * UNUSEDC, wmDrag * drag, wmEvent * UNUSEDevent) [static]
Definition at line 343 of file space_sequencer.c.
References ELEM, wmDrag::icon, wmDrag::type, and WM_DRAG_PATH.
Referenced by sequencer_dropboxes().