Blender: MEM_CacheLimiterCClass Class Reference
MEM_CacheLimiterCClass Class Reference
Public Member Functions
MEM_CacheLimiterCClass (MEM_CacheLimiter_Destruct_Func data_destructor_, MEM_CacheLimiter_DataSize_Func data_size)
~MEM_CacheLimiterCClass ()
handle_t * insert (void *data)
void destruct (void *data, list_t::iterator it)
cache_t * get_cache ()
Detailed Description
Definition at line 56 of file MEM_CacheLimiterC-Api.cpp.
Constructor & Destructor Documentation
MEM_CacheLimiterCClass::MEM_CacheLimiterCClass (MEM_CacheLimiter_Destruct_Func data_destructor_, MEM_CacheLimiter_DataSize_Func data_size) [inline]
Definition at line 58 of file MEM_CacheLimiterC-Api.cpp.
MEM_CacheLimiterCClass::~MEM_CacheLimiterCClass ()
Definition at line 123 of file MEM_CacheLimiterC-Api.cpp.
Member Function Documentation
void MEM_CacheLimiterCClass::destruct (void * data, list_t::iterator it)
Definition at line 110 of file MEM_CacheLimiterC-Api.cpp.
Referenced by MEM_CacheLimiterHandleCClass::~MEM_CacheLimiterHandleCClass().
cache_t* MEM_CacheLimiterCClass::get_cache () [inline]
Definition at line 68 of file MEM_CacheLimiterC-Api.cpp.
Referenced by MEM_CacheLimiter_enforce_limits().
handle_t * MEM_CacheLimiterCClass::insert (void * data)
Definition at line 100 of file MEM_CacheLimiterC-Api.cpp.
References MEM_CacheLimiter< T >::insert().
Referenced by MEM_CacheLimiter_insert().
The documentation for this class was generated from the following file:
MEM_CacheLimiterC-Api.cpp