Blender: SubdMesh Class Reference
SubdMesh Class Reference
#include <subd_mesh.h>
Classes
struct Key
Public Member Functions
SubdMesh ()
~SubdMesh ()
SubdVert * add_vert (const float3 &co)
SubdFace * add_face (int v0, int v1, int v2)
SubdFace * add_face (int v0, int v1, int v2, int v3)
SubdFace * add_face (int *index, int num)
bool link_boundary ()
void tessellate (DiagSplit *split, bool linear, Mesh *mesh, int shader, bool smooth)
Public Attributes
vector< SubdVert * > verts
vector< SubdEdge * > edges
vector< SubdFace * > faces
Protected Member Functions
bool can_add_face (int *index, int num)
bool can_add_edge (int i, int j)
SubdEdge * add_edge (int i, int j)
SubdEdge * find_edge (int i, int j)
void link_boundary_edge (SubdEdge *edge)
Protected Attributes
map< Key, SubdEdge * > edge_map
Detailed Description
Definition at line 47 of file subd_mesh.h.
Constructor & Destructor Documentation
CCL_NAMESPACE_BEGIN SubdMesh::SubdMesh ()
Definition at line 44 of file subd_mesh.cpp.
SubdMesh::~SubdMesh ()
Definition at line 48 of file subd_mesh.cpp.
References edge_map, edges, faces, and verts.
Member Function Documentation
SubdEdge * SubdMesh::add_edge (int i, int j) [protected]
Definition at line 155 of file subd_mesh.cpp.
References SubdVert::edge, edge_map, edges, find_edge(), i, SubdEdge::id, NULL, SubdEdge::pair, SubdEdge::vert, and verts.
Referenced by add_face().
SubdFace * SubdMesh::add_face (int v0, int v1, int v2)
Definition at line 74 of file subd_mesh.cpp.
Referenced by add_face(), create_subd_mesh(), and xml_read_mesh().
SubdFace * SubdMesh::add_face (int * index, int num)
Definition at line 86 of file subd_mesh.cpp.
References add_edge(), assert, can_add_face(), SubdFace::edge, SubdEdge::face, faces, i, SubdEdge::next, NULL, and SubdEdge::prev.
SubdFace * SubdMesh::add_face (int v0, int v1, int v2, int v3)
Definition at line 80 of file subd_mesh.cpp.
References add_face().
SubdVert * SubdMesh::add_vert (const float3 & co)
Definition at line 65 of file subd_mesh.cpp.
References SubdVert::co, co, and verts.
Referenced by create_subd_mesh(), and xml_read_mesh().
bool SubdMesh::can_add_edge (int i, int j) [protected]
Definition at line 145 of file subd_mesh.cpp.
References find_edge(), and NULL.
Referenced by can_add_face().
bool SubdMesh::can_add_face (int * index, int num) [protected]
Definition at line 135 of file subd_mesh.cpp.
References can_add_edge(), and i.
Referenced by add_face().
SubdEdge * SubdMesh::find_edge (int i, int j) [protected]
Definition at line 190 of file subd_mesh.cpp.
References edge_map, and NULL.
Referenced by add_edge(), and can_add_edge().
bool SubdMesh::link_boundary ()
Definition at line 197 of file subd_mesh.cpp.
References assert, edge_map, SubdVert::edges(), edges, SubdEdge::face, SubdEdge::from(), i, SubdVert::id, SubdEdge::id, SubdVert::EdgeIterator::isDone(), link_boundary_edge(), NULL, SubdEdge::pair, SubdEdge::to(), SubdEdge::vert, and verts.
Referenced by create_subd_mesh(), and xml_read_mesh().
void SubdMesh::link_boundary_edge (SubdEdge * edge) [protected]
Definition at line 260 of file subd_mesh.cpp.
References assert, SubdVert::edge, SubdEdge::face, SubdEdge::next, next, NULL, SubdEdge::pair, SubdEdge::prev, and SubdEdge::vert.
Referenced by link_boundary().
void SubdMesh::tessellate (DiagSplit * split, bool linear, Mesh * mesh, int shader, bool smooth)
Definition at line 288 of file subd_mesh.cpp.
References SubdBuilder::create(), faces, Patch::is_triangle(), SubdBuilder::run(), DiagSplit::split_quad(), and DiagSplit::split_triangle().
Referenced by create_subd_mesh(), and xml_read_mesh().
Member Data Documentation
map<Key, SubdEdge *> SubdMesh::edge_map [protected]
Definition at line 84 of file subd_mesh.h.
Referenced by add_edge(), find_edge(), link_boundary(), and ~SubdMesh().
vector<SubdEdge*> SubdMesh::edges
Definition at line 51 of file subd_mesh.h.
Referenced by add_edge(), link_boundary(), and ~SubdMesh().
vector<SubdFace*> SubdMesh::faces
Definition at line 52 of file subd_mesh.h.
Referenced by add_face(), tessellate(), and ~SubdMesh().
vector<SubdVert*> SubdMesh::verts
Definition at line 50 of file subd_mesh.h.
Referenced by add_edge(), add_vert(), link_boundary(), and ~SubdMesh().
The documentation for this class was generated from the following files:
subd_mesh.h
subd_mesh.cpp