Blender: CIdentifierExpr Class Reference
CIdentifierExpr Class Reference
#include <IdentifierExpr.h>
Public Member Functions
CIdentifierExpr (const STR_String &identifier, CValue *id_context)
virtual ~CIdentifierExpr ()
virtual CValue * Calculate ()
virtual bool MergeExpression (CExpression *otherexpr)
virtual unsigned char GetExpressionID ()
virtual bool NeedsRecalculated ()
virtual CExpression * CheckLink (std::vector< CBrokenLinkInfo * > &brokenlinks)
virtual void ClearModified ()
virtual void BroadcastOperators (VALUE_OPERATOR op)
Detailed Description
Definition at line 37 of file IdentifierExpr.h.
Constructor & Destructor Documentation
CIdentifierExpr::CIdentifierExpr (const STR_String & identifier, CValue * id_context)
Definition at line 35 of file IdentifierExpr.cpp.
References CValue::AddRef(), and NULL.
CIdentifierExpr::~CIdentifierExpr () [virtual]
Definition at line 45 of file IdentifierExpr.cpp.
References CValue::Release().
Member Function Documentation
void CIdentifierExpr::BroadcastOperators (VALUE_OPERATOR op) [virtual]
Implements CExpression.
Definition at line 100 of file IdentifierExpr.cpp.
References assertd.
CValue * CIdentifierExpr::Calculate () [virtual]
Implements CExpression.
Definition at line 53 of file IdentifierExpr.cpp.
References CValue::FindIdentifier(), and NULL.
CExpression * CIdentifierExpr::CheckLink (std::vector< CBrokenLinkInfo * > & brokenlinks) [virtual]
Implements CExpression.
Definition at line 85 of file IdentifierExpr.cpp.
References assertd, and NULL.
void CIdentifierExpr::ClearModified () [virtual]
Implements CExpression.
Definition at line 93 of file IdentifierExpr.cpp.
References assertd.
unsigned char CIdentifierExpr::GetExpressionID () [virtual]
Implements CExpression.
Definition at line 71 of file IdentifierExpr.cpp.
References CExpression::CIDENTIFIEREXPRESSIONID.
bool CIdentifierExpr::MergeExpression (CExpression * otherexpr) [virtual]
Implements CExpression.
Definition at line 64 of file IdentifierExpr.cpp.
bool CIdentifierExpr::NeedsRecalculated () [virtual]
Implements CExpression.
Definition at line 78 of file IdentifierExpr.cpp.
The documentation for this class was generated from the following files:
IdentifierExpr.h
IdentifierExpr.cpp