Blender: KX_PythonInit.h File Reference
KX_PythonInit.h File Reference
Ketsji
#include "KX_Python.h"
#include "STR_String.h"
#include "MT_Vector3.h"
Enumerations
enum TPythonSecurityLevel { psl_Lowest = 0, psl_Highest }
Functions
void KX_SetActiveScene (class KX_Scene *scene)
class KX_Scene * KX_GetActiveScene ()
class KX_KetsjiEngine * KX_GetActiveEngine ()
void KX_RasterizerDrawDebugLine (const MT_Vector3 &from, const MT_Vector3 &to, const MT_Vector3 &color)
void KX_RasterizerDrawDebugCircle (const MT_Vector3 &center, const MT_Scalar radius, const MT_Vector3 &color, const MT_Vector3 &normal, int nsector)
Variables
bool gUseVisibilityTemp
Detailed Description
Definition in file KX_PythonInit.h.
Enumeration Type Documentation
enum TPythonSecurityLevel
Enumerator:
psl_Lowest
psl_Highest
Definition at line 38 of file KX_PythonInit.h.
Function Documentation
class KX_KetsjiEngine* KX_GetActiveEngine ()
Definition at line 178 of file KX_PythonInit.cpp.
References gp_KetsjiEngine.
Referenced by ImageRender::ImageRender(), ImageViewport::ImageViewport(), BL_Action::Play(), and Texture_refresh().
class KX_Scene* KX_GetActiveScene ()
Definition at line 173 of file KX_PythonInit.cpp.
References gp_KetsjiScene.
Referenced by KX_NavMeshObject::BuildVertIndArrays(), KX_GameObject::GetActionManager(), KX_KetsjiEngine::NextFrame(), BL_Action::Play(), KX_NavMeshObject::ProcessReplica(), KX_GameObject::ProcessReplica(), KX_FontObject::ProcessReplica(), KX_SoundActuator::Update(), KX_ConstraintActuator::Update(), KX_ParentActuator::Update(), and KX_GameObject::~KX_GameObject().
void KX_RasterizerDrawDebugCircle (const MT_Vector3 & center, const MT_Scalar radius, const MT_Vector3 & color, const MT_Vector3 & normal, int nsector)
Definition at line 190 of file KX_PythonInit.cpp.
References RAS_IRasterizer::DrawDebugCircle().
Referenced by KX_ObstacleSimulation::DrawObstacles().
void KX_RasterizerDrawDebugLine (const MT_Vector3 & from, const MT_Vector3 & to, const MT_Vector3 & color)
Definition at line 184 of file KX_PythonInit.cpp.
References RAS_IRasterizer::DrawDebugLine().
Referenced by KX_NavMeshObject::DrawNavMesh(), KX_ObstacleSimulation::DrawObstacles(), KX_NavMeshObject::DrawPath(), and KX_SteeringActuator::Update().
void KX_SetActiveScene (class KX_Scene * scene)
Definition at line 168 of file KX_PythonInit.cpp.
Referenced by KX_KetsjiEngine::NextFrame().
Variable Documentation
bool gUseVisibilityTemp