Blender: GHOST_NDOFManager.cpp File Reference
GHOST_NDOFManager.cpp File Reference
#include "GHOST_Debug.h"
#include "GHOST_NDOFManager.h"
#include "GHOST_EventNDOF.h"
#include "GHOST_EventKey.h"
#include "GHOST_WindowManager.h"
#include <string.h>
#include <stdio.h>
#include <math.h>
Defines
#define HOME(foo) (ndof->foo == 0.f)
#define HOME(foo) (fabsf(ndof->foo) < threshold)
Functions
static bool atHomePosition (GHOST_TEventNDOFMotionData *ndof)
static bool nearHomePosition (GHOST_TEventNDOFMotionData *ndof, float threshold)
Variables
static const NDOF_ButtonT Modern3Dx_HID_map []
static const NDOF_ButtonT SpaceExplorer_HID_map []
static const NDOF_ButtonT SpacePilot_HID_map []
static const NDOF_ButtonT Generic_HID_map []
static const int genericButtonCount = sizeof(Generic_HID_map) / sizeof(NDOF_ButtonT)
Define Documentation
#define HOME (foo) (ndof->foo == 0.f)
Referenced by atHomePosition(), and nearHomePosition().
#define HOME (foo) (fabsf(ndof->foo) < threshold)
Function Documentation
static bool atHomePosition (GHOST_TEventNDOFMotionData * ndof) [static]
Definition at line 406 of file GHOST_NDOFManager.cpp.
References HOME, and tz.
Referenced by nearHomePosition().
static bool nearHomePosition (GHOST_TEventNDOFMotionData * ndof, float threshold) [static]
Definition at line 413 of file GHOST_NDOFManager.cpp.
References atHomePosition(), HOME, and tz.
Referenced by GHOST_NDOFManager::sendMotionEvent().
Variable Documentation
const NDOF_ButtonT Generic_HID_map[] [static]
Initial value:
 {
    NDOF_BUTTON_1,
    NDOF_BUTTON_2,
    NDOF_BUTTON_3,
    NDOF_BUTTON_4,
    NDOF_BUTTON_5,
    NDOF_BUTTON_6,
    NDOF_BUTTON_7,
    NDOF_BUTTON_8,
    NDOF_BUTTON_9,
    NDOF_BUTTON_A,
    NDOF_BUTTON_B,
    NDOF_BUTTON_C
}
Definition at line 175 of file GHOST_NDOFManager.cpp.
Referenced by GHOST_NDOFManager::setDevice().
const int genericButtonCount = sizeof(Generic_HID_map) / sizeof(NDOF_ButtonT) [static]
Definition at line 190 of file GHOST_NDOFManager.cpp.
Referenced by GHOST_NDOFManager::setDevice().
const NDOF_ButtonT Modern3Dx_HID_map[] [static]
Definition at line 97 of file GHOST_NDOFManager.cpp.
Referenced by GHOST_NDOFManager::setDevice().
const NDOF_ButtonT SpaceExplorer_HID_map[] [static]
Initial value:
 {
    NDOF_BUTTON_1,
    NDOF_BUTTON_2,
    NDOF_BUTTON_TOP,
    NDOF_BUTTON_LEFT,
    NDOF_BUTTON_RIGHT,
    NDOF_BUTTON_FRONT,
    NDOF_BUTTON_ESC,
    NDOF_BUTTON_ALT,
    NDOF_BUTTON_SHIFT,
    NDOF_BUTTON_CTRL,
    NDOF_BUTTON_FIT,
    NDOF_BUTTON_MENU,
    NDOF_BUTTON_PLUS,
    NDOF_BUTTON_MINUS,
    NDOF_BUTTON_ROTATE
}
Definition at line 131 of file GHOST_NDOFManager.cpp.
Referenced by GHOST_NDOFManager::setDevice().
const NDOF_ButtonT SpacePilot_HID_map[] [static]
Initial value:
 {
    NDOF_BUTTON_1,
    NDOF_BUTTON_2,
    NDOF_BUTTON_3,
    NDOF_BUTTON_4,
    NDOF_BUTTON_5,
    NDOF_BUTTON_6,
    NDOF_BUTTON_TOP,
    NDOF_BUTTON_LEFT,
    NDOF_BUTTON_RIGHT,
    NDOF_BUTTON_FRONT,
    NDOF_BUTTON_ESC,
    NDOF_BUTTON_ALT,
    NDOF_BUTTON_SHIFT,
    NDOF_BUTTON_CTRL,
    NDOF_BUTTON_FIT,
    NDOF_BUTTON_MENU,
    NDOF_BUTTON_PLUS,
    NDOF_BUTTON_MINUS,
    NDOF_BUTTON_DOMINANT,
    NDOF_BUTTON_ROTATE,
    NDOF_BUTTON_NONE
}
Definition at line 151 of file GHOST_NDOFManager.cpp.
Referenced by GHOST_NDOFManager::setDevice().