Blender: btGenericPoolAllocator.cpp File Reference
btGenericPoolAllocator.cpp File Reference
#include "btGenericPoolAllocator.h"
Classes
class GIM_STANDARD_ALLOCATOR
Defines
#define BT_DEFAULT_POOL_SIZE 32768
************** STANDARD ALLOCATOR ***************************///
#define BT_DEFAULT_POOL_ELEMENT_SIZE 8
Functions
void * btPoolAlloc (size_t size)
void * btPoolRealloc (void *ptr, size_t oldsize, size_t newsize)
void btPoolFree (void *ptr)
Variables
GIM_STANDARD_ALLOCATOR g_main_allocator
Detailed Description
Author:
Francisco Leon Najera. email projectileman@yahoo.com
General purpose allocator class
Definition in file btGenericPoolAllocator.cpp.
Define Documentation
#define BT_DEFAULT_POOL_ELEMENT_SIZE 8
Definition at line 251 of file btGenericPoolAllocator.cpp.
#define BT_DEFAULT_POOL_SIZE 32768
************** STANDARD ALLOCATOR ***************************///
Definition at line 250 of file btGenericPoolAllocator.cpp.
Function Documentation
void* btPoolAlloc (size_t size)
Definition at line 266 of file btGenericPoolAllocator.cpp.
References btGenericPoolAllocator::allocate().
Referenced by btPoolRealloc().
void btPoolFree (void * ptr)
Definition at line 280 of file btGenericPoolAllocator.cpp.
References btGenericPoolAllocator::freeMemory().
Referenced by btPoolRealloc().
void* btPoolRealloc (void * ptr, size_t oldsize, size_t newsize)
Definition at line 271 of file btGenericPoolAllocator.cpp.
References btPoolAlloc(), and btPoolFree().
Variable Documentation
GIM_STANDARD_ALLOCATOR g_main_allocator
Definition at line 263 of file btGenericPoolAllocator.cpp.