Blender: nla_intern.h File Reference
nla_intern.h File Reference
NLA editor
Enumerations
enum { NLAEDIT_LRSEL_TEST = -1, NLAEDIT_LRSEL_NONE, NLAEDIT_LRSEL_LEFT, NLAEDIT_LRSEL_RIGHT }
enum { NLAEDIT_SNAP_CFRA = 1, NLAEDIT_SNAP_NEAREST_FRAME, NLAEDIT_SNAP_NEAREST_SECOND, NLAEDIT_SNAP_NEAREST_MARKER }
Functions
ARegion * nla_has_buttons_region (ScrArea *sa)
void nla_buttons_register (ARegionType *art)
void NLA_OT_properties (wmOperatorType *ot)
void draw_nla_main_data (bAnimContext *ac, SpaceNla *snla, ARegion *ar)
void draw_nla_channel_list (bContext *C, bAnimContext *ac, ARegion *ar)
void NLA_OT_select_all_toggle (wmOperatorType *ot)
void NLA_OT_select_border (wmOperatorType *ot)
void NLA_OT_select_leftright (wmOperatorType *ot)
void NLA_OT_click_select (wmOperatorType *ot)
void NLA_OT_tweakmode_enter (wmOperatorType *ot)
void NLA_OT_tweakmode_exit (wmOperatorType *ot)
void NLA_OT_view_all (wmOperatorType *ot)
void NLA_OT_view_selected (wmOperatorType *ot)
void NLA_OT_actionclip_add (wmOperatorType *ot)
void NLA_OT_transition_add (wmOperatorType *ot)
void NLA_OT_soundclip_add (wmOperatorType *ot)
void NLA_OT_meta_add (wmOperatorType *ot)
void NLA_OT_meta_remove (wmOperatorType *ot)
void NLA_OT_duplicate (wmOperatorType *ot)
void NLA_OT_delete (wmOperatorType *ot)
void NLA_OT_split (wmOperatorType *ot)
void NLA_OT_mute_toggle (wmOperatorType *ot)
void NLA_OT_swap (wmOperatorType *ot)
void NLA_OT_move_up (wmOperatorType *ot)
void NLA_OT_move_down (wmOperatorType *ot)
void NLA_OT_action_sync_length (wmOperatorType *ot)
void NLA_OT_apply_scale (wmOperatorType *ot)
void NLA_OT_clear_scale (wmOperatorType *ot)
void NLA_OT_snap (wmOperatorType *ot)
void NLA_OT_fmodifier_add (wmOperatorType *ot)
void NLA_OT_fmodifier_copy (wmOperatorType *ot)
void NLA_OT_fmodifier_paste (wmOperatorType *ot)
void NLA_OT_channels_click (wmOperatorType *ot)
void NLA_OT_tracks_add (wmOperatorType *ot)
void NLA_OT_delete_tracks (wmOperatorType *ot)
int nlaop_poll_tweakmode_off (bContext *C)
int nlaop_poll_tweakmode_on (bContext *C)
short nlaedit_is_tweakmode_on (bAnimContext *ac)
void nla_operatortypes (void)
void nla_keymap (wmKeyConfig *keyconf)
Variables
enum { ... } eNlaEdit_LeftRightSelect_Mode
enum { ... } eNlaEdit_Snap_Mode
Detailed Description
Definition in file nla_intern.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
NLAEDIT_LRSEL_TEST
NLAEDIT_LRSEL_NONE
NLAEDIT_LRSEL_LEFT
NLAEDIT_LRSEL_RIGHT
Definition at line 57 of file nla_intern.h.
anonymous enum
Enumerator:
NLAEDIT_SNAP_CFRA
NLAEDIT_SNAP_NEAREST_FRAME
NLAEDIT_SNAP_NEAREST_SECOND
NLAEDIT_SNAP_NEAREST_MARKER
Definition at line 76 of file nla_intern.h.
Function Documentation
void draw_nla_channel_list (bContext * C, bAnimContext * ac, ARegion * ar)
Definition at line 923 of file nla_draw.c.
References ANIM_animdata_filter(), ANIM_channel_draw_widgets(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, BLI_freelistN(), View2D::cur, bAnimContext::data, bAnimContext::datatype, draw_nla_channel_list_gl(), filter(), ListBase::first, IN_RANGE, bAnimListElem::next, NLACHANNEL_HEIGHT, NLACHANNEL_HEIGHT_HALF, NLACHANNEL_STEP, NULL, bAnimContext::sa, bAnimContext::sl, View2D::tot, UI_EMBOSS, UI_view2d_sync(), uiBeginBlock(), uiDrawBlock(), uiEndBlock(), ARegion::v2d, V2D_LOCK_COPY, rctf::ymax, and rctf::ymin.
Referenced by nla_channel_area_draw().
void draw_nla_main_data (bAnimContext * ac, SpaceNla * snla, ARegion * ar)
Definition at line 537 of file nla_draw.c.
References bAnimListElem::adt, ANIM_animdata_filter(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, ANIMTYPE_NLAACTION, ANIMTYPE_NLATRACK, BKE_nlastrip_within_bounds(), BLI_freelistN(), View2D::cur, bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, fdrawline(), filter(), ListBase::first, NlaStrip::flag, IN_RANGE, NlaStrip::next, bAnimListElem::next, nla_action_draw_keyframes(), nla_action_get_color(), nla_draw_strip(), nla_draw_strip_frames_text(), nla_draw_strip_text(), NLACHANNEL_HEIGHT, NLACHANNEL_HEIGHT_HALF, NLACHANNEL_SKIP, NLACHANNEL_STEP, NLASTRIP_FLAG_TEMP_META, NULL, NlaTrack::strips, View2D::tot, bAnimListElem::type, ARegion::v2d, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by nla_main_area_draw().
void nla_buttons_register (ARegionType * art)
Definition at line 468 of file nla_buttons.c.
References BLI_addtail(), PanelType::draw, PanelType::flag, PanelType::idname, PanelType::label, MEM_callocN(), nla_animdata_panel_poll(), nla_panel_actclip(), nla_panel_animdata(), nla_panel_evaluation(), nla_panel_modifiers(), nla_panel_properties(), nla_panel_track(), nla_strip_actclip_panel_poll(), nla_strip_eval_panel_poll(), nla_strip_panel_poll(), nla_track_panel_poll(), ARegionType::paneltypes, PNL_DEFAULT_CLOSED, and PanelType::poll.
Referenced by ED_spacetype_nla().
ARegion* nla_has_buttons_region (ScrArea * sa)
Definition at line 67 of file space_nla.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_RIGHT, RGN_FLAG_HIDDEN, RGN_TYPE_UI, and RGN_TYPE_WINDOW.
Referenced by nla_properties().
void nla_keymap (wmKeyConfig * keyconf)
Definition at line 299 of file nla_ops.c.
References KM_PRESS, NKEY, nla_keymap_channels(), nla_keymap_main(), SPACE_NLA, WM_keymap_add_item(), and WM_keymap_find().
Referenced by ED_spacetype_nla().
void nla_operatortypes (void)
Definition at line 114 of file nla_ops.c.
References NLA_OT_action_sync_length(), NLA_OT_actionclip_add(), NLA_OT_apply_scale(), NLA_OT_channels_click(), NLA_OT_clear_scale(), NLA_OT_click_select(), NLA_OT_delete(), NLA_OT_delete_tracks(), NLA_OT_duplicate(), NLA_OT_fmodifier_add(), NLA_OT_fmodifier_copy(), NLA_OT_fmodifier_paste(), NLA_OT_meta_add(), NLA_OT_meta_remove(), NLA_OT_move_down(), NLA_OT_move_up(), NLA_OT_mute_toggle(), NLA_OT_properties(), NLA_OT_select_all_toggle(), NLA_OT_select_border(), NLA_OT_select_leftright(), NLA_OT_snap(), NLA_OT_soundclip_add(), NLA_OT_split(), NLA_OT_swap(), NLA_OT_tracks_add(), NLA_OT_transition_add(), NLA_OT_tweakmode_enter(), NLA_OT_tweakmode_exit(), NLA_OT_view_all(), NLA_OT_view_selected(), and WM_operatortype_append().
Referenced by ED_spacetype_nla().
void NLA_OT_action_sync_length (wmOperatorType * ot)
Definition at line 1616 of file nla_edit.c.
References wmOperatorType::description, ED_operator_nla_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_sync_actlen_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by nla_operatortypes().
void NLA_OT_actionclip_add (wmOperatorType * ot)
Definition at line 471 of file nla_edit.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, nlaedit_add_actionclip_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_action_itemf(), RNA_def_enum(), RNA_def_enum_funcs(), wmOperatorType::srna, and WM_enum_search_invoke().
Referenced by nla_operatortypes().
void NLA_OT_apply_scale (wmOperatorType * ot)
Definition at line 1716 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_apply_scale_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_channels_click (wmOperatorType * ot)
Definition at line 344 of file nla_channels.c.
References wmOperatorType::description, ED_operator_nla_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, nlachannels_mouseclick_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by nla_operatortypes().
void NLA_OT_clear_scale (wmOperatorType * ot)
Definition at line 1779 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_clear_scale_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_click_select (wmOperatorType * ot)
Definition at line 646 of file nla_select.c.
References wmOperatorType::description, ED_operator_nla_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, nlaedit_clickselect_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by nla_operatortypes().
void NLA_OT_delete (wmOperatorType * ot)
Definition at line 975 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_delete_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_delete_tracks (wmOperatorType * ot)
Definition at line 482 of file nla_channels.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_delete_tracks_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_duplicate (wmOperatorType * ot)
Definition at line 900 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, nlaedit_duplicate_exec(), nlaedit_duplicate_invoke(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, TFM_TRANSLATION, and transform_mode_types.
Referenced by nla_operatortypes().
void NLA_OT_fmodifier_add (wmOperatorType * ot)
Definition at line 2039 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, fmodifier_type_items, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, nla_fmodifier_add_exec(), nla_fmodifier_add_invoke(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), and wmOperatorType::srna.
Referenced by nla_operatortypes().
void NLA_OT_fmodifier_copy (wmOperatorType * ot)
Definition at line 2103 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nla_fmodifier_copy_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_fmodifier_paste (wmOperatorType * ot)
Definition at line 2165 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nla_fmodifier_paste_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_meta_add (wmOperatorType * ot)
Definition at line 745 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_add_meta_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_meta_remove (wmOperatorType * ot)
Definition at line 797 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_remove_meta_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_move_down (wmOperatorType * ot)
Definition at line 1540 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_move_down_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_move_up (wmOperatorType * ot)
Definition at line 1466 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_move_up_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_mute_toggle (wmOperatorType * ot)
Definition at line 1235 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_toggle_mute_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_properties (wmOperatorType * ot)
Definition at line 527 of file nla_buttons.c.
References wmOperatorType::description, ED_operator_nla_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nla_properties(), and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_select_all_toggle (wmOperatorType * ot)
Definition at line 186 of file nla_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_deselectall_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by nla_operatortypes().
void NLA_OT_select_border (wmOperatorType * ot)
Definition at line 331 of file nla_select.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, nlaedit_borderselect_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, WM_border_select_cancel(), WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by nla_operatortypes().
void NLA_OT_select_leftright (wmOperatorType * ot)
Definition at line 484 of file nla_select.c.
References wmOperatorType::description, ED_operator_nla_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NLAEDIT_LRSEL_TEST, nlaedit_select_leftright_exec(), nlaedit_select_leftright_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), and wmOperatorType::srna.
Referenced by nla_operatortypes().
void NLA_OT_snap (wmOperatorType * ot)
Definition at line 1920 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, nlaedit_snap_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by nla_operatortypes().
void NLA_OT_soundclip_add (wmOperatorType * ot)
Definition at line 683 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_add_sound_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_split (wmOperatorType * ot)
Definition at line 1120 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_split_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_swap (wmOperatorType * ot)
Definition at line 1392 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_swap_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_tracks_add (wmOperatorType * ot)
Definition at line 418 of file nla_channels.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_add_tracks_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by nla_operatortypes().
void NLA_OT_transition_add (wmOperatorType * ot)
Definition at line 598 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_add_transition_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_tweakmode_enter (wmOperatorType * ot)
Definition at line 158 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_enable_tweakmode_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_tweakmode_exit (wmOperatorType * ot)
Definition at line 223 of file nla_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_disable_tweakmode_exec(), nlaop_poll_tweakmode_on(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_view_all (wmOperatorType * ot)
Definition at line 338 of file nla_edit.c.
References wmOperatorType::description, ED_operator_nla_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_viewall_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_view_selected (wmOperatorType * ot)
Definition at line 353 of file nla_edit.c.
References wmOperatorType::description, ED_operator_nla_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_viewsel_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
short nlaedit_is_tweakmode_on (bAnimContext * ac)
Definition at line 105 of file nla_ops.c.
References Scene::flag, SCE_NLA_EDIT_ON, and bAnimContext::scene.
Referenced by mouse_nla_channels().
int nlaop_poll_tweakmode_off (bContext * C)
Definition at line 61 of file nla_ops.c.
References CTX_data_scene(), ED_operator_nla_active(), Scene::flag, NULL, and SCE_NLA_EDIT_ON.
Referenced by NLA_OT_actionclip_add(), NLA_OT_apply_scale(), NLA_OT_bake(), NLA_OT_clear_scale(), NLA_OT_delete(), NLA_OT_delete_tracks(), NLA_OT_duplicate(), NLA_OT_fmodifier_add(), NLA_OT_fmodifier_copy(), NLA_OT_fmodifier_paste(), NLA_OT_meta_add(), NLA_OT_meta_remove(), NLA_OT_move_down(), NLA_OT_move_up(), NLA_OT_mute_toggle(), NLA_OT_select_all_toggle(), NLA_OT_select_border(), NLA_OT_snap(), NLA_OT_soundclip_add(), NLA_OT_split(), NLA_OT_swap(), NLA_OT_tracks_add(), NLA_OT_transition_add(), and NLA_OT_tweakmode_enter().
int nlaop_poll_tweakmode_on (bContext * C)
Definition at line 83 of file nla_ops.c.
References CTX_data_scene(), ED_operator_nla_active(), Scene::flag, NULL, and SCE_NLA_EDIT_ON.
Referenced by NLA_OT_tweakmode_exit().
Variable Documentation
enum { ... } eNlaEdit_LeftRightSelect_Mode
enum { ... } eNlaEdit_Snap_Mode