Blender: node_composite_outputFile.c File Reference
node_composite_outputFile.c File Reference
cmpnodes
#include <string.h>
#include "BLI_path_util.h"
#include "BKE_utildefines.h"
#include "node_composite_util.h"
#include "IMB_imbuf.h"
#include "IMB_imbuf_types.h"
#include "intern/openexr/openexr_multi.h"
Functions
bNodeSocket * ntreeCompositOutputFileAddSocket (bNodeTree *ntree, bNode *node, const char *name, ImageFormatData *im_format)
int ntreeCompositOutputFileRemoveActiveSocket (bNodeTree *ntree, bNode *node)
static void init_output_file (bNodeTree *ntree, bNode *node, bNodeTemplate *ntemp)
static void free_output_file (bNode *node)
static void copy_output_file (struct bNode *node, struct bNode *target)
static void update_output_file (bNodeTree *UNUSED(ntree), bNode *node)
static void exec_output_file_singlelayer (RenderData *rd, bNode *node, bNodeStack **in)
static void exec_output_file_multilayer (RenderData *rd, bNode *node, bNodeStack **in)
static void exec_output_file (void *data, bNode *node, bNodeStack **in, bNodeStack **UNUSED(out))
void register_node_type_cmp_output_file (bNodeTreeType *ttype)
Detailed Description
Definition in file node_composite_outputFile.c.
Function Documentation
static void copy_output_file (struct bNode * node, struct bNode * target) [static]
Definition at line 121 of file node_composite_outputFile.c.
References ListBase::first, bNode::inputs, MEM_dupallocN(), bNodeSocket::next, bNodeSocket::storage, and bNode::storage.
Referenced by register_node_type_cmp_output_file().
static void exec_output_file (void * data, bNode * node, bNodeStack ** in, bNodeStack ** UNUSEDout) [static]
Definition at line 307 of file node_composite_outputFile.c.
References data, exec_output_file_multilayer(), exec_output_file_singlelayer(), NodeImageMultiFile::format, G, ImageFormatData::imtype, R_IMF_IMTYPE_MULTILAYER, and bNode::storage.
Referenced by register_node_type_cmp_output_file().
static void exec_output_file_multilayer (RenderData * rd, bNode * node, bNodeStack ** in) [static]
Definition at line 214 of file node_composite_outputFile.c.
References NodeImageMultiFile::base_path, BKE_makepicstring(), BLI_make_existing_file(), BLI_strncpy(), CB_RGBA, CB_VAL, CB_VEC2, CB_VEC3, RenderData::cfra, bNodeStack::data, data, ImageFormatData::exr_codec, EXR_LAY_MAXNAME, EXR_PASS_MAXNAME, FILE_MAX, ListBase::first, NodeImageMultiFile::format, G, generate_preview(), i, IMB_exr_add_channel(), IMB_exr_begin_write(), IMB_exr_close(), IMB_exr_get_handle(), IMB_exr_write_channels(), bNode::inputs, bNodeSocket::name, bNode::name, Main::name, bNodeSocket::next, R_EXTENSION, R_IMF_IMTYPE_MULTILAYER, CompBuf::rect, CompBuf::rect_procedural, RenderData::scemode, bNode::storage, strlen(), TRUE, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by exec_output_file().
static void exec_output_file_singlelayer (RenderData * rd, bNode * node, bNodeStack ** in) [static]
Definition at line 148 of file node_composite_outputFile.c.
References NodeImageMultiFile::base_path, BKE_makepicstring(), BKE_write_ibuf(), BLI_join_dirfile(), CB_RGBA, CB_VAL, CB_VEC3, RenderData::cfra, ImBuf::channels, RenderData::color_mgt_flag, data, ImBuf::dither, RenderData::dither_intensity, FILE_MAX, ListBase::first, NodeImageMultiFileSocket::format, NodeImageMultiFile::format, free_compbuf(), G, generate_preview(), i, IB_PROFILE_LINEAR_RGB, IMB_allocImBuf(), IMB_freeImBuf(), ImageFormatData::imtype, bNode::inputs, Main::name, bNodeSocket::name, bNodeSocket::next, ImageFormatData::planes, ImBuf::profile, R_COLOR_MANAGEMENT, R_EXTENSION, R_IMF_PLANES_BW, R_IMF_PLANES_RGB, R_IMF_PLANES_RGBA, CompBuf::rect, ImBuf::rect_float, RenderData::scemode, bNodeSocket::storage, bNode::storage, TRUE, typecheck_compbuf(), NodeImageMultiFileSocket::use_node_format, CompBuf::x, and CompBuf::y.
Referenced by exec_output_file().
static void free_output_file (bNode * node) [static]
Definition at line 109 of file node_composite_outputFile.c.
References ListBase::first, bNode::inputs, MEM_freeN(), bNodeSocket::next, bNodeSocket::storage, and bNode::storage.
Referenced by register_node_type_cmp_output_file().
static void init_output_file (bNodeTree * ntree, bNode * node, bNodeTemplate * ntemp) [static]
Definition at line 91 of file node_composite_outputFile.c.
References NodeImageMultiFile::base_path, BLI_strncpy(), NodeImageMultiFile::format, RenderData::im_format, MEM_callocN(), ntreeCompositOutputFileAddSocket(), NULL, RenderData::pic, Scene::r, bNodeTemplate::scene, and bNode::storage.
Referenced by register_node_type_cmp_output_file().
bNodeSocket* ntreeCompositOutputFileAddSocket (bNodeTree * ntree, bNode * node, const char * name, ImageFormatData * im_format) [read]
Definition at line 48 of file node_composite_outputFile.c.
References NodeImageMultiFile::active_input, BKE_imtype_is_movie(), BLI_findindex(), NodeImageMultiFileSocket::format, ImageFormatData::imtype, bNode::inputs, MEM_callocN(), nodeAddSocket(), R_IMF_IMTYPE_OPENEXR, SOCK_IN, SOCK_RGBA, SOCK_STRUCT_OUTPUT_FILE, bNodeSocket::storage, bNode::storage, bNodeSocket::struct_type, and NodeImageMultiFileSocket::use_node_format.
Referenced by do_versions_nodetree_multi_file_output_format_2_62_1(), init_output_file(), and node_output_file_add_socket_exec().
int ntreeCompositOutputFileRemoveActiveSocket (bNodeTree * ntree, bNode * node)
Definition at line 72 of file node_composite_outputFile.c.
References NodeImageMultiFile::active_input, BLI_countlist(), BLI_findlink(), bNode::inputs, MEM_freeN(), nodeRemoveSocket(), bNodeSocket::storage, and bNode::storage.
Referenced by node_output_file_remove_active_socket_exec().
void register_node_type_cmp_output_file (bNodeTreeType * ttype)
Definition at line 325 of file node_composite_outputFile.c.
References CMP_NODE_OUTPUT_FILE, copy_output_file(), exec_output_file(), free_output_file(), init_output_file(), NODE_CLASS_OUTPUT, NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), node_type_update(), nodeRegisterType(), NULL, and update_output_file().
Referenced by registerCompositNodes().
static void update_output_file (bNodeTree * UNUSEDntree, bNode * node) [static]
Definition at line 133 of file node_composite_outputFile.c.
References ListBase::first, bNodeLink::fromsock, bNode::inputs, bNodeSocket::link, bNodeSocket::next, nodeSocketSetType(), and bNodeSocket::type.
Referenced by register_node_type_cmp_output_file().