Blender: stdosl.h File Reference
stdosl.h File Reference
Defines
#define M_PI 3.1415926535897932
#define M_PI_2 1.5707963267948966
#define M_PI_4 0.7853981633974483
#define M_2_PI 0.6366197723675813
#define M_2_SQRTPI 1.1283791670955126
#define M_E 2.7182818284590452
#define M_LN2 0.6931471805599453
#define M_LN10 2.3025850929940457
#define M_LOG2E 1.4426950408889634
#define M_LOG10E 0.4342944819032518
#define M_SQRT2 1.4142135623730950
#define M_SQRT1_2 0.7071067811865475
#define BUILTIN [[ int builtin = 1 ]]
#define BUILTIN_DERIV [[ int builtin = 1, int deriv = 1 ]]
#define PERCOMP1(name)
#define PERCOMP2(name)
#define PERCOMP2F(name)
Functions
normal degrees (normal x)
vector degrees (vector x)
point degrees (point x)
color degrees (color x)
float degrees (float x)
normal radians (normal x)
vector radians (vector x)
point radians (point x)
color radians (color x)
float radians (float x)
point log (point a, float b)
vector log (vector a, float b)
color log (color a, float b)
float log (float a, float b)
float hypot (float a, float b)
float hypot (float a, float b, float c)
int abs (int x) BUILTIN
int fabs (int x) BUILTIN
int mod (int x, int y) BUILTIN
normal clamp (normal x, normal minval, normal maxval)
vector clamp (vector x, vector minval, vector maxval)
point clamp (point x, point minval, point maxval)
color clamp (color x, color minval, color maxval)
float clamp (float x, float minval, float maxval)
normal mix (normal x, normal y, normal a)
normal mix (normal x, normal y, float a)
vector mix (vector x, vector y, vector a)
vector mix (vector x, vector y, float a)
point mix (point x, point y, point a)
point mix (point x, point y, float a)
color mix (color x, color y, color a)
color mix (color x, color y, float a)
float mix (float x, float y, float a)
int isnan (float x) BUILTIN
int isinf (float x) BUILTIN
int isfinite (float x) BUILTIN
float erf (float x) BUILTIN
float erfc (float x) BUILTIN
vector cross (vector a, vector b) BUILTIN
float dot (vector a, vector b) BUILTIN
float length (vector v) BUILTIN
float distance (point a, point b) BUILTIN
float distance (point a, point b, point q) BUILTIN
normal normalize (normal v) BUILTIN
vector normalize (vector v) BUILTIN
vector faceforward (vector N, vector I, vector Nref) BUILTIN
vector faceforward (vector N, vector I) BUILTIN
vector reflect (vector I, vector N)
vector refract (vector I, vector N, float eta)
void fresnel (vector I, normal N, float eta, output float Kr, output float Kt, output vector R, output vector T)
void fresnel (vector I, normal N, float eta, output float Kr, output float Kt)
point rotate (point q, float angle, point a, point b) BUILTIN
normal transform (matrix Mto, normal p) BUILTIN
vector transform (matrix Mto, vector p) BUILTIN
point transform (matrix Mto, point p) BUILTIN
point transform (string tospace, point x)
point transform (string fromspace, string tospace, point x)
vector transform (string tospace, vector x)
vector transform (string fromspace, string tospace, vector x)
normal transform (string tospace, normal x)
normal transform (string fromspace, string tospace, normal x)
float transformu (string tounits, float x) BUILTIN
float transformu (string fromunits, string tounits, float x) BUILTIN
float luminance (color c)
color transformc (string to, color x)
color transformc (string from, string to, color x)
float determinant (matrix m) BUILTIN
matrix transpose (matrix m) BUILTIN
float step (float edge, float x) BUILTIN
color step (color edge, color x) BUILTIN
point step (point edge, point x) BUILTIN
vector step (vector edge, vector x) BUILTIN
normal step (normal edge, normal x) BUILTIN
float smoothstep (float edge0, float edge1, float x) BUILTIN
int strlen (string s) BUILTIN
int startswith (string s, string prefix) BUILTIN
int endswith (string s, string suffix) BUILTIN
string substr (string s, int start, int len) BUILTIN
string substr (string s, int start)
string concat (string a, string b, string c)
string concat (string a, string b, string c, string d)
string concat (string a, string b, string c, string d, string e)
string concat (string a, string b, string c, string d, string e, string f)
closure color diffuse (normal N) BUILTIN
closure color oren_nayar (normal N, float sigma) BUILTIN
closure color translucent (normal N) BUILTIN
closure color reflection (normal N, float eta) BUILTIN
closure color reflection (normal N)
closure color refraction (normal N, float eta) BUILTIN
closure color dielectric (normal N, float eta) BUILTIN
closure color transparent () BUILTIN
closure color microfacet_ggx (normal N, float ag) BUILTIN
closure color microfacet_ggx_refraction (normal N, float ag, float eta) BUILTIN
closure color microfacet_beckmann (normal N, float ab) BUILTIN
closure color microfacet_beckmann_refraction (normal N, float ab, float eta) BUILTIN
closure color ward (normal N, vector T, float ax, float ay) BUILTIN
closure color ashikhmin_velvet (normal N, float sigma) BUILTIN
closure color westin_backscatter (normal N, float roughness) BUILTIN
closure color westin_sheen (normal N, float edginess) BUILTIN
closure color bssrdf_cubic (color radius) BUILTIN
closure color emission (float inner_angle, float outer_angle) BUILTIN
closure color emission (float outer_angle) BUILTIN
closure color emission () BUILTIN
closure color debug (string tag) BUILTIN
closure color background () BUILTIN
closure color holdout () BUILTIN
closure color subsurface (float eta, float g, float mfp, float albedo) BUILTIN
int raytype (string typename) BUILTIN
Define Documentation
#define BUILTIN [[ int builtin = 1 ]]
Definition at line 51 of file stdosl.h.
#define BUILTIN_DERIV [[ int builtin = 1, int deriv = 1 ]]
Definition at line 52 of file stdosl.h.
#define M_2_PI 0.6366197723675813
Definition at line 37 of file stdosl.h.
#define M_2_SQRTPI 1.1283791670955126
Definition at line 38 of file stdosl.h.
#define M_E 2.7182818284590452
Definition at line 39 of file stdosl.h.
#define M_LN10 2.3025850929940457
Definition at line 41 of file stdosl.h.
#define M_LN2 0.6931471805599453
Definition at line 40 of file stdosl.h.
#define M_LOG10E 0.4342944819032518
Definition at line 43 of file stdosl.h.
#define M_LOG2E 1.4426950408889634
Definition at line 42 of file stdosl.h.
#define M_PI 3.1415926535897932
Definition at line 34 of file stdosl.h.
Referenced by degrees(), and radians().
#define M_PI_2 1.5707963267948966
Definition at line 35 of file stdosl.h.
#define M_PI_4 0.7853981633974483
Definition at line 36 of file stdosl.h.
#define M_SQRT1_2 0.7071067811865475
Definition at line 45 of file stdosl.h.
#define M_SQRT2 1.4142135623730950
Definition at line 44 of file stdosl.h.
#define PERCOMP1 (name)
Value:
normal name (normal x) BUILTIN;             \
    vector name (vector x) BUILTIN;             \
    point  name (point x) BUILTIN;              \
    color  name (color x) BUILTIN;              \
    float  name (float x) BUILTIN;
Definition at line 54 of file stdosl.h.
#define PERCOMP2 (name)
Value:
normal name (normal x, normal y) BUILTIN;   \
    vector name (vector x, vector y) BUILTIN;   \
    point  name (point x, point y) BUILTIN;     \
    color  name (color x, color y) BUILTIN;     \
    float  name (float x, float y) BUILTIN;
Definition at line 61 of file stdosl.h.
#define PERCOMP2F (name)
Value:
normal name (normal x, float y) BUILTIN;    \
    vector name (vector x, float y) BUILTIN;    \
    point  name (point x, float y) BUILTIN;     \
    color  name (color x, float y) BUILTIN;     \
    float  name (float x, float y) BUILTIN;
Definition at line 68 of file stdosl.h.
Function Documentation
int abs (int x)
Referenced by SCA_Joystick::aAxisIsPositive(), calcArcCorrelation(), check_zone(), computeLU(), delete_fcurve_key(), fcurve_eval_samples(), find_first_points(), find_nearest_seq(), findnearestface__doClosest(), findnearestface__getDistance(), findnearestLattvert__doClosest(), findnearestNurbvert__doClosest(), findnearestvert__doClosest(), gammaCorrect(), gp_stroke_filtermval(), gpencil_layer_getframe(), IMB_thumb_create(), initArcIterator2(), invGammaCorrect(), mouse_select(), mouse_select_knot(), nonzero(), object_mouse_select_menu(), ImagesExporter::operator()(), ptcache_path(), screen_find_active_scredge(), select_adjacent_cp(), select_nth_bezt(), select_nth_bp(), seq_tx_set_final_left(), seq_tx_set_final_right(), sequencer_select_invoke(), set_constraint_nth_target(), setNearestAxis2d(), smoke_dissolve(), snapEdge(), snapVertex(), testAxialSymmetry(), ui_numedit_but_NUM(), UI_view2d_totRect_set_resize(), and wm_autosave_location().
closure color ashikhmin_velvet (normal N, float sigma)
closure color background ()
Referenced by BlenderSync::get_scene_params(), and BlenderSync::get_session_params().
closure color bssrdf_cubic (color radius)
normal clamp (normal x, normal minval, normal maxval)
Definition at line 129 of file stdosl.h.
References max, and min.
vector clamp (vector x, vector minval, vector maxval)
Definition at line 130 of file stdosl.h.
References max, and min.
point clamp (point x, point minval, point maxval)
Definition at line 131 of file stdosl.h.
References max, and min.
color clamp (color x, color minval, color maxval)
Definition at line 132 of file stdosl.h.
References max, and min.
float clamp (float x, float minval, float maxval)
Definition at line 133 of file stdosl.h.
References max, and min.
string concat (string a, string b, string c)
Definition at line 418 of file stdosl.h.
Referenced by concat().
string concat (string a, string b, string c, string d)
Definition at line 421 of file stdosl.h.
References concat().
string concat (string a, string b, string c, string d, string e)
Definition at line 424 of file stdosl.h.
References concat().
string concat (string a, string b, string c, string d, string e, string f)
Definition at line 427 of file stdosl.h.
References concat().
vector cross (vector a, vector b)
Referenced by Mesh::add_face_normals(), EdgeDice::add_vert(), applyModifier(), area_lamp_energy(), ATTRIBUTE_ALIGNED16(), ATTRIBUTE_ALIGNED64(), bevel_list_smooth(), bt_edge_plane(), ntlScene::buildScene(), btTriangleShapeEx::buildTriPlane(), btPrimitiveTriangle::buildTriPlane(), checkValidQuad(), SphereTriangleDetector::collide(), btRigidBody::computeImpulseDenominator(), IsoSurface::computeNormals(), ntlMatrix4x4< Scalar >::decompose(), edbm_dupli_extrude_cursor_invoke(), get_strand_normal(), ParticleTracer::getTriangles(), LbmFsgrSolver::initializeSolverGrids(), ntlGeometryObject::initMovingPoints(), ntlGeometryObject::initMovingPointsAnim(), btRigidBody::internalGetVelocityInLocalPointObsolete(), ntlTree::intersect(), ntlRay::intersectTriangle(), ntlRay::intersectTriangleBack(), ntlRay::intersectTriangleFront(), ntlRay::intersectTriangleX(), ntlTree::intersectX(), isQuadPlanar(), lasso_inside(), make_orthonormals(), make_orthonormals_tangent(), mean_value_half_tan(), BVH::pack_triangle(), btVoronoiSimplexSolver::pointOutsideOfPlane(), btSoftBodyTriangleCallback::processTriangle(), btConnectivityProcessor::processTriangle(), DebugDrawcallback::processTriangle(), CcdPhysicsEnvironment::rayTest(), ntlWorld::renderScene(), btSequentialImpulseConstraintSolver::setupContactConstraint(), btSequentialImpulseConstraintSolver::setupFrictionConstraint(), shade_input_set_strand(), shade_one_light(), IsoSurface::smoothNormals(), IsoSurface::smoothSurface(), static_particle_strand(), strand_eval_point(), svm_node_set_bump(), svm_vector_math(), transform_negative_scale(), triangle_area(), triangle_normal_MT(), and triangleArea().
closure color debug (string tag)
Referenced by gp_draw_data(), and SCA_PythonController::SetDebug().
color degrees (color x)
Definition at line 80 of file stdosl.h.
References M_PI.
vector degrees (vector x)
Definition at line 78 of file stdosl.h.
References M_PI.
normal degrees (normal x)
Definition at line 77 of file stdosl.h.
References M_PI.
Referenced by KX_Dome::CalculateFrustum(), and drawcircle_size().
float degrees (float x)
Definition at line 81 of file stdosl.h.
References M_PI.
point degrees (point x)
Definition at line 79 of file stdosl.h.
References M_PI.
float determinant (matrix m)
Referenced by getLowestRoot().
closure color dielectric (normal N, float eta)
closure color diffuse (normal N)
float distance (point a, point b)
Referenced by _softbody_calc_forces_slice_in_a_thread(), ATTRIBUTE_ALIGNED16(), Bevel(), BL_ConvertBlenderObjects(), BL_ConvertSensors(), BLI_FindNodeByPosition(), BOP_between(), BOP_mergeSort(), capsuleCapsuleDistance(), ControlParticles::checkPointInside(), cloth_collision(), SphereTriangleDetector::collide(), btConvexPlaneCollisionAlgorithm::collideSingleContact(), collision_response(), do_distance_matte(), draw_forcefield(), dynamicPaint_paintSinglePoint(), EDBM_edge_find_nearest(), EDBM_vert_find_nearest(), envelope_bone_weighting(), findnearestedge__doClosest(), LbmSolverInterface::geoInitCheckPointInside(), btGjkPairDetector::getClosestPointsNonVirtual(), btGImpactCollisionAlgorithm::gimpacttrimeshpart_vs_plane_collision(), Handle_set_distance_maximum(), Handle_set_distance_reference(), init(), ControlParticles::initFromMVCMesh(), ControlParticles::initFromObject(), LbmFsgrSolver::initGeometryFlags(), InputCustomRatio(), CcdPhysicsEnvironment::processFhSprings(), btTriangleRaycastCallback::processTriangle(), PushPull(), sb_spring_force(), AUD_SoftwareDevice::AUD_SoftwareHandle::setDistanceMaximum(), AUD_SequencerEntry::setDistanceMaximum(), AUD_SoftwareDevice::AUD_SoftwareHandle::setDistanceReference(), AUD_SequencerEntry::setDistanceReference(), ShrinkFatten(), sk_addStrokeSnapPoint(), sk_distanceDepth(), sk_flattenStroke(), softbody_calc_forces(), KX_Camera::SphereInsideFrustum(), svm_node_camera(), KX_ConstraintActuator::Update(), AUD_SoftwareDevice::AUD_SoftwareHandle::update(), View(), and view3d_sample_backbuf_rect().
float distance (point a, point b, point q)
float dot (vector a, vector b)
Referenced by btPerturbedContactResult::addContactPoint(), BoundBox::area(), ATTRIBUTE_ALIGNED16(), bsdf_ashikhmin_velvet_eval_reflect(), bsdf_ashikhmin_velvet_sample(), bsdf_diffuse_eval_reflect(), bsdf_diffuse_sample(), bsdf_microfacet_beckmann_eval_reflect(), bsdf_microfacet_beckmann_eval_transmit(), bsdf_microfacet_beckmann_sample(), bsdf_microfacet_ggx_eval_reflect(), bsdf_microfacet_ggx_eval_transmit(), bsdf_microfacet_ggx_sample(), bsdf_oren_nayar_eval_reflect(), bsdf_oren_nayar_get_intensity(), bsdf_oren_nayar_sample(), bsdf_reflection_sample(), bsdf_translucent_eval_transmit(), bsdf_translucent_sample(), bsdf_ward_eval_reflect(), bsdf_ward_sample(), bsdf_westin_backscatter_eval_reflect(), bsdf_westin_backscatter_sample(), bsdf_westin_sheen_eval_reflect(), bsdf_westin_sheen_sample(), btNearestPointInLineSegment(), btTransformAabb(), btTriangleShapeEx::buildTriPlane(), btPrimitiveTriangle::buildTriPlane(), calchandleNurb_intern(), ntlMaterial::calculateFresnel(), ControlParticles::checkPointInside(), checkValidQuad(), TNT::Cholesky_upper_factorization(), btVoronoiSimplexSolver::closestPtPointTetrahedron(), cloth_calc_spring_force(), collision_response(), column_vector_multiplication(), ntlMatrix4x4< Scalar >::decompose(), differential_transfer(), IsoSurface::diffuseVertexField(), direct_emission(), do_material_tex(), dot(), dynamicPaint_paintMesh(), EdgeSeparation(), emissive_eval(), emissive_pdf(), AnimationExporter::extract_transform_name(), FindIncidentEdge(), FindMaxSeparation(), fresnel(), fresnel_dielectric(), frontface(), LbmSolverInterface::geoInitCheckPointInside(), btTriangleMeshShape::getAabb(), btHeightfieldTerrainShape::getAabb(), btCapsuleShape::getAabb(), ntlLightObject::getShadedColor(), btSphereBoxCollisionAlgorithm::getSphereDistance(), btSphereBoxCollisionAlgorithm::getSpherePenetration(), LbmFsgrSolver::handleObstacleParticle(), ntlGeometryObject::initMovingPoints(), LocalSupportVertexCallback::internalProcessTriangleIndex(), ntlRay::intersectTriangle(), ntlRay::intersectTriangleBack(), ntlRay::intersectTriangleFront(), ntlRay::intersectTriangleX(), isect_line_plane_v3(), isQuadPlanar(), kernel_path_integrate(), lasso_inside(), len(), luminance(), Matrix_mul(), mean_value_half_tan(), mirrorball_to_direction(), MT_multTransposeRight(), KDL::VectorVel::Norm(), normal_projection_project_vertex(), btTransform::operator()(), operator*(), p_vec_angle(), BVH::pack_triangle(), pe_deflect_emitter(), btVoronoiSimplexSolver::pointOutsideOfPlane(), LbmFsgrSolver::prepareVisualization(), SupportVertexCallback::processTriangle(), ntlVector3Dim< Scalar >::projectNormalTo(), btSoftBody::PSolve_SContacts(), reflect(), reflectVector(), refract(), refraction(), refractVector(), regular_light_pdf(), rotation_between_quats_to_quat(), row_vector_multiplication(), seqbase_unique_name_recursive(), set_phong_threshold(), ntlRay::shade(), shader_setup_from_ray(), shader_setup_from_sample(), IsoSurface::smoothNormals(), IsoSurface::smoothSurface(), btConeTwistConstraint::solveConstraintObsolete(), btTranslationalLimitMotor::solveLinearAxis(), strand_segment_recursive(), svm_bsdf_eval(), svm_node_closure_bsdf(), svm_node_fresnel(), svm_node_layer_weight(), svm_node_normal(), svm_node_set_bump(), svm_node_tex_coord(), svm_node_tex_coord_bump_dx(), svm_node_tex_coord_bump_dy(), svm_vector_math(), btMatrix3x3::timesTranspose(), GIM_BOX_BOX_TRANSFORM_CACHE::transform(), transform_direction(), transform_negative_scale(), transform_perspective(), transform_point(), transformc(), triangle_light_pdf(), Vector_angle(), Vector_length_set(), Vector_project(), and voronoi_distance().
closure color emission ()
closure color emission (float inner_angle, float outer_angle)
Referenced by kernel_path_integrate(), vol_get_emission(), and xml_read_shader_graph().
closure color emission (float outer_angle)
int endswith (string s, string suffix)
float erf (float x)
float erfc (float x)
int fabs (int x)
Referenced by LbmFsgrSolver::adaptTimestep(), iTaSC::Cache::addCacheVectorIfDifferent(), KX_ObstacleSimulationTOI::AdjustObstacleVelocity(), btConeTwistConstraint::adjustSwingAxisToUseEllipseNormal(), area_draw_azone(), Bevel(), BKE_image_buf_fill_checker(), BOP_abs(), buts_are_horiz(), calc_bevel_sin_cos(), check_non_flat_quads(), check_zone(), clipMirrorModifier(), colorfn(), compatible_eul(), compatible_eulFast(), compress_deepsamples(), btConeTwistConstraint::computeConeLimitInfo(), costLength(), cubemap(), cubemap_glob(), cubemap_ob(), cuboid_do(), ntlMatrix4x4< Scalar >::decompose(), defocus_blur(), detectArcRetargetMode(), DirectionToThetaPhi(), displace_render_face(), DistanceBetweenLines(), do_diff_matte(), do_kink(), do_physical_effector(), do_rough(), do_strand_fillac(), double_round(), draw_spot_cone(), drawgrid(), drawlamp(), ED_uvedit_nearest_uv(), ED_view3d_calc_clipping(), edbm_select_axis_exec(), EDBM_uv_vert_map_create(), edgetag_cut_cost(), Eigencdiv(), Eigenhqr2(), Eigenorthes(), Eigentql2(), Eigentred2(), AUD_EnvelopeFactory::envelopeFilter(), KX_Camera::ExtractFrustumSphere(), fabs(), filterObstacle(), find_nearest_uv_face(), fresnel_dielectric(), KDL::Rotation::GetEulerZYZ(), iTaSC::Armature::getMaxJointChange(), BasicVector::getNormalized(), getNormalized(), BasicVector::Vector3Dim< Scalar >::getOrthogonalntlVector3Dim(), ntlVector3Dim< Scalar >::getOrthogonalntlVector3Dim(), btConeTwistConstraint::GetPointForAngle(), KDL::Rotation::GetRPY(), graphkeys_euler_filter_exec(), halton_sample(), GHOST_SystemCocoa::handleMouseEvent(), TNT::hypot(), ImageRender::ImageRender(), imapaint_pick_uv(), initFlyInfo(), ntlRay::intersectBackAABB(), ntlRay::intersectCompleteAABB(), ntlRay::intersectFrontAABB(), invert_m4_m4(), IsectLLPt2Df(), isQuadPlanar(), lasso_inside(), TNT::LU_factor(), makeBevelList(), KX_Scene::MarkVisible(), mat3_to_compatible_eul(), mat3_to_eul(), mat3_to_eulO(), meshdeform_matrix_solve(), minDx(), minDy(), minDz(), moveCloserToDistanceFromPlane(), MT_abs(), my_get_local_bounds(), nearest_point_in_tri_surface(), node_shader_exec_camera(), node_shader_exec_vect_math(), KX_GameObject::NodeSetWorldPosition(), KX_GameObject::NodeSetWorldScale(), noise_basis_hard(), noise_turbulence(), noise_wave(), BasicVector::norm(), KDL::Norm(), norm(), KDL::Vector::Norm(), KDL::Vector2::Norm(), BasicVector::normalize(), normalize(), operator+(), NM_Scalar< T >::operator+=(), operator-(), NM_Scalar< T >::operator-=(), overlapped_curve(), p_chart_pin_positions(), panotestclip(), PE_hide_keys_time(), planeProjection(), pow(), GHOST_WindowWin32::processWin32TabletEvent(), project_float_noclip(), project_int_noclip(), project_renderdata(), psys_get_dupli_path_transform(), KDL::PYTHAG(), TNT::QR_factor(), quat_to_axis_angle(), AUD_RectifyFactory::rectifyFilter(), ImageRender::Render(), render_lighting_halo(), renderflare(), ntlWorld::renderScene(), KX_IpoActuator::ResetStartTime(), resolve_quad_uv(), BSP_CSGMesh::SC_Face(), scrollbar_start_scrolling(), sculpt_brush_test_cube(), btConeTwistConstraint::setMotorTargetInConstraintSpace(), KX_GameObject::SetParent(), shadeHaloFloat(), shadeSkyView(), KDL::SIGN(), sinc(), sinf_norm_error(), iTaSC::WSDLSSolver::solve(), iTaSC::WDLSSolver::solve(), FLUID_3D::solveHeat(), FLUID_3D::solvePressurePre(), KX_Camera::SphereInsideFrustum(), spivotL(), spothalo(), WTURBULENCE::stepTurbulenceFull(), stitch_check_uvs_stitchable(), strand_shade_segment(), surface_determineForceTargetPoints(), KDL::svd_eigen_HH(), svm_mix_diff(), switchdirection_knots(), switchdirectionNurb(), TargetSnapClosest(), test_manipulator_axis(), testshadowbuf(), ui_check_but(), ui_set_but_string(), uiBeginBlock(), KX_IpoActuator::Update(), KX_Scene::UpdateObjectActivity(), uv_find_nearest_vert(), vec_to_quat(), viewpixel_to_lampbuf(), voronoi_distance(), voronoiTex(), where_is_object_simul(), zbuffer_abuf(), zbufline(), zbufline_onlyZ(), and zbuflineAc().
vector faceforward (vector N, vector I, vector Nref)
vector faceforward (vector N, vector I)
void fresnel (vector I, normal N, float eta, output float Kr, output float Kt, output vector R, output vector T)
Definition at line 171 of file stdosl.h.
References dot(), F, g, reflect(), refract(), KDL::sqr(), and sqrt().
Referenced by fresnel(), and svm_node_closure_bsdf().
void fresnel (vector I, normal N, float eta, output float Kr, output float Kt)
Definition at line 201 of file stdosl.h.
References fresnel(), R, and T.
closure color holdout ()
float hypot (float a, float b, float c)
Definition at line 112 of file stdosl.h.
References sqrt().
float hypot (float a, float b)
Definition at line 111 of file stdosl.h.
References sqrt().
Referenced by Eigentql2().
int isfinite (float x)
Referenced by path_radiance_clamp(), and BoundBox::valid().
int isinf (float x)
int isnan (float x)
Referenced by dynamicPaint_paintParticles(), DualConInputReader::getNextTriangle(), loadTile(), nextLengthSubdivision(), old_mdisps_bilinear(), and quad_coord().
float length (vector v)
Referenced by _face_calcIFNo(), btSoftBody::appendLink(), arrayModifier_doArray(), ATTRIBUTE_ALIGNED16(), AUD_convert_double_float(), AUD_convert_double_s16(), AUD_convert_double_s24_be(), AUD_convert_double_s24_le(), AUD_convert_double_s32(), AUD_convert_double_u8(), AUD_convert_float_s16(), AUD_convert_float_s24_be(), AUD_convert_float_s24_le(), AUD_convert_float_s32(), AUD_convert_float_u8(), AUD_convert_s16_u8(), AUD_convert_s24_s16_be(), AUD_convert_s24_s16_le(), AUD_convert_s24_u8_be(), AUD_convert_s24_u8_le(), AUD_convert_s32_float(), AUD_convert_s32_s16(), AUD_convert_s32_s24_be(), AUD_convert_s32_s24_le(), AUD_convert_s32_u8(), AUD_LimiterReader::AUD_LimiterReader(), AUD_readSound(), AUD_StreamBufferFactory::AUD_StreamBufferFactory(), b_bone_spline_setup(), base_callback(), BGL_MakeBuffer(), BLI_calcGraphLength(), BLI_subtreeLength(), bm_vert_avg_tag_dist(), bmo_inset_exec(), bmo_similaredges_exec(), boid_body(), bone_align_to_bone(), brush_puff(), btAdjustInternalEdgeContacts(), Buffer_item(), btContinuousConvexCollision::calcTimeOfImpact(), ccgSubSurf__calcVertNormals(), check_path_length(), AUD_Mixer::clear(), cloth_bvh_objcollision(), cloth_calc_spring_force(), IK_QPositionTask::ComputeJacobian(), convert_tree(), MeshImporter::create_mesh_object(), AnimationExporter::create_source_from_fcurve(), btDiscreteDynamicsWorld::debugDrawConstraint(), btSoftBody::defaultCollisionHandler(), delete_key_button_exec(), dfdx_spring_type1(), distribute_simple_children(), do_kink(), do_versions(), AUD_SRCResampleReader::doCallback(), draw_b_bone(), draw_line_bone(), draw_new_particle_system(), draw_sphere_bone(), draw_wire_bone(), drawArrow(), drawseqwave(), execute_posetree(), execute_scene(), BSP_CSGMesh::FacePlane(), Factory_fadein(), Factory_fadeout(), iTaSC::Armature::finalize(), btCollisionShape::getAngularMotionDisc(), BL_ArmatureObject::GetBoneLength(), btCollisionShape::getBoundingSphere(), btGjkPairDetector::getClosestPointsNonVirtual(), GPU_shader_create(), GPU_texture_convert_pixels(), handle_app1(), GHOST_SystemCocoa::handleKeyEvent(), STR_HashedString::hash(), InputCustomRatio(), insert_key_button_exec(), RAS_MeshSlot::Join(), AUD_SoftwareDevice::mix(), nlastrip_get_frame_transition(), p_smooth(), paint_space_stroke(), PE_apply_lengths(), pe_iterate_lengths(), peekBucket(), peekPoint(), PolarDecompose(), btSoftColliders::CollideVF_SS::Process(), btConnectivityProcessor::processTriangle(), gjkepa2_impl::GJK::projectorigin(), psys_thread_create_path(), PyC_AsArray(), Quaternion_rotate(), AUD_SuperposeReader::read(), AUD_SRCResampleReader::read(), AUD_SndFileReader::read(), AUD_SinusReader::read(), AUD_SilenceReader::read(), AUD_SequencerReader::read(), AUD_ReverseReader::read(), AUD_LoopReader::read(), AUD_LinearResampleReader::read(), AUD_LimiterReader::read(), AUD_FFMPEGReader::read(), AUD_DoubleReader::read(), AUD_DelayReader::read(), AUD_ChannelMapperReader::read(), AUD_BufferReader::read(), AUD_BaseIIRFilterReader::read(), AUD_BandPassReader::read(), ReadData(), render_new_particle_system(), retargetArctoArcLength(), RNA_def_float_matrix(), RNA_def_property_array(), rna_iterator_array_begin(), RNA_parameter_length_set_data(), RNA_property_as_string(), RNA_property_collection_length(), RNA_property_string_get_alloc(), RNA_property_string_get_default_alloc(), BSP_CSGMesh::SC_Face(), AUD_FFMPEGReader::seek(), setIteratorValues(), SG_Tree::SetLeft(), SG_Tree::SetRight(), IK_QSegment::SetTransform(), SG_Tree::SG_Tree(), btGjkEpaSolver2::SignedDistance(), sk_addStrokeSnapPoint(), sk_drawEdge(), btKinematicCharacterController::stepForwardAndStrafe(), STR_gHash(), txt_copy_selected(), txt_extended_ascii_as_utf8(), txt_sel_to_buf(), txt_to_buf(), txt_undo_add_block(), ui_but_menu(), KX_ConstraintActuator::Update(), BL_ShapeActionActuator::Update(), KX_BoneParentRelation::UpdateChildCoordinates(), btSoftBody::updateConstants(), AUD_OpenALDevice::updateStreams(), voronoi_distance(), AUD_SndFileWriter::write(), AUD_FFMPEGWriter::write(), WriteData(), and AUD_FileWriter::writeReader().
vector log (vector a, float b)
Definition at line 103 of file stdosl.h.
References log().
point log (point a, float b)
Definition at line 102 of file stdosl.h.
Referenced by avgLogLum(), BKE_tracking_context_new(), do_math(), fcm_fn_generator_evaluate(), GPU_shader_create(), log(), node_shader_exec_math(), old_mdisps_convert(), power_of_2(), psys_render_simplify_distribution(), MTRand::randNorm(), ntlMaterial::setTransAttCol(), soft_range_round_down(), soft_range_round_up(), sqrt3d(), sqrt3f(), SCA_RandomActuator::Update(), valuefn(), and WTURBULENCE::WTURBULENCE().
color log (color a, float b)
Definition at line 104 of file stdosl.h.
References log().
float log (float a, float b)
Definition at line 105 of file stdosl.h.
References log().
float luminance (color c)
Definition at line 254 of file stdosl.h.
References dot().
closure color microfacet_beckmann (normal N, float ab)
closure color microfacet_beckmann_refraction (normal N, float ab, float eta)
closure color microfacet_ggx (normal N, float ag)
closure color microfacet_ggx_refraction (normal N, float ag, float eta)
color mix (color x, color y, float a)
Definition at line 146 of file stdosl.h.
float mix (float x, float y, float a)
Definition at line 147 of file stdosl.h.
normal mix (normal x, normal y, normal a)
Definition at line 139 of file stdosl.h.
Referenced by add_node(), OcclusionBuffer::draw(), dynamicPaint_mixPaintColors(), init_brush_icons(), and xml_read_shader_graph().
normal mix (normal x, normal y, float a)
Definition at line 140 of file stdosl.h.
vector mix (vector x, vector y, vector a)
Definition at line 141 of file stdosl.h.
vector mix (vector x, vector y, float a)
Definition at line 142 of file stdosl.h.
point mix (point x, point y, point a)
Definition at line 143 of file stdosl.h.
point mix (point x, point y, float a)
Definition at line 144 of file stdosl.h.
color mix (color x, color y, color a)
Definition at line 145 of file stdosl.h.
int mod (int x, int y)
Referenced by BPY_button_exec(), bpy_import_init(), bpy_import_test(), BPy_init_modules(), BPY_modules_update(), bpy_pydriver_create_dict(), BPyInit_bmesh(), BPyInit_idprop(), CCL_python_module_init(), GHOST_SystemSDL::getModifierKeys(), PyC_FileAndNum(), and PyInit_mathutils().
normal normalize (normal v)
Referenced by Mesh::add_face_normals(), EdgeDice::add_vert(), Mesh::add_vertex_normals(), ATTRIBUTE_ALIGNED16(), bsdf_ashikhmin_velvet_eval_reflect(), bsdf_ashikhmin_velvet_sample(), bsdf_microfacet_beckmann_eval_reflect(), bsdf_microfacet_beckmann_eval_transmit(), bsdf_microfacet_ggx_eval_reflect(), bsdf_microfacet_ggx_eval_transmit(), bsdf_ward_eval_reflect(), bsdf_ward_sample(), ntlScene::buildScene(), camera_sample_environment(), camera_sample_orthographic(), camera_sample_perspective(), IsoSurface::computeNormals(), MeanValueMeshCoords::computeWeights(), KX_Dome::CreateMeshDome180(), KX_Dome::CreateMeshDome250(), KX_Dome::CreateMeshPanorama(), ntlMatrix4x4< Scalar >::decompose(), LightManager::device_update_points(), distant_light_sample(), btSphereBoxCollisionAlgorithm::getSphereDistance(), btSphereBoxCollisionAlgorithm::getSpherePenetration(), ParticleTracer::getTriangles(), LbmFsgrSolver::handleObstacleParticle(), ntlLightObject::illuminatePoint(), ntlTree::intersect(), ntlTree::intersectX(), LbmFsgrSolver::mainLoop(), make_orthonormals(), mbvh_instance_push(), object_normal_transform(), btSphereBoxCollisionAlgorithm::processCollision(), regular_light_sample(), ntlWorld::renderScene(), ntlBlenderDumper::renderScene(), SimulationObject::setMousePos(), IsoSurface::smoothNormals(), IsoSurface::smoothSurface(), sphere_light_sample(), svm_node_camera(), svm_node_closure_bsdf(), svm_node_geometry(), svm_node_normal(), svm_node_set_bump(), svm_node_tex_environment(), svm_vector_math(), transform_clear_scale(), transform_rotate(), triangle_normal_MT(), triangle_smooth_normal(), IsoSurface::triangulate(), and vol_get_phasefunc().
vector normalize (vector v)
closure color oren_nayar (normal N, float sigma)
point radians (point x)
Definition at line 84 of file stdosl.h.
References M_PI.
color radians (color x)
Definition at line 85 of file stdosl.h.
References M_PI.
float radians (float x)
Definition at line 86 of file stdosl.h.
References M_PI.
normal radians (normal x)
Definition at line 82 of file stdosl.h.
References M_PI.
Referenced by KX_Dome::CalculateFrustum().
vector radians (vector x)
Definition at line 83 of file stdosl.h.
References M_PI.
int raytype (string typename)
vector reflect (vector I, vector N)
Definition at line 165 of file stdosl.h.
References dot(), and N.
Referenced by CreateMaterialFromBlenderObject(), fresnel(), reflect_v3_v3v3(), and Vector_reflect().
closure color reflection (normal N)
Definition at line 441 of file stdosl.h.
References reflection().
closure color reflection (normal N, float eta)
vector refract (vector I, vector N, float eta)
Definition at line 166 of file stdosl.h.
References dot(), and sqrt().
Referenced by fresnel(), svm_node_closure_bsdf(), and traceray().
closure color refraction (normal N, float eta)
point rotate (point q, float angle, point a, point b)
Referenced by ATTRIBUTE_ALIGNED16(), and xml_read_transform().
float smoothstep (float edge0, float edge1, float x)
int startswith (string s, string prefix)
float step (float edge, float x)
Referenced by antialias_tagbuf(), applyModifier(), background_light_sample(), BLI_strncpy_wchar_from_utf8(), bpy_bmeditselseq_subscript(), bpy_bmelemseq_subscript(), bpy_bmlayercollection_subscript(), BPy_FloatProperty(), BPy_FloatVectorProperty(), BPy_IDArray_ass_subscript(), BPy_IDArray_subscript(), BPy_IntProperty(), BPy_IntVectorProperty(), brush_edit_apply(), brush_gen_texture_cache(), brush_painter_paint(), Buffer_ass_subscript(), Buffer_subscript(), C_Vector_Linspace(), C_Vector_Range(), cache_occ_samples(), ccgDM_drawFacesSolid(), checker_board_text(), Color_ass_subscript(), Color_subscript(), cp_cu_key(), btMatrix3x3::diagonalize(), distribute_threads_init_data(), do_cu_key(), do_curve_key(), do_mesh_key(), do_rel_cu_key(), draw_rotation_guide(), btIDebugDraw::drawArc(), btIDebugDraw::drawSpherePatch(), dynamicPaint_doSmudge(), Euler_ass_subscript(), Euler_subscript(), implicit_solver(), btRigidBody::integrateVelocities(), Matrix_ass_subscript(), Matrix_subscript(), MatrixAccess_subscript(), node_composit_exec_bilateralblur(), pdDoEffectors(), poselib_preview_get_next(), ptcache_particle_totwrite(), ptcache_particle_write(), ptcache_write_needed(), pyrna_prop_array_ass_subscript(), pyrna_prop_array_subscript(), pyrna_prop_collection_ass_subscript(), pyrna_prop_collection_subscript(), Quaternion_ass_subscript(), Quaternion_subscript(), RE_Database_FromScene_Vectors(), RE_zbuf_accumulate_vecblur(), readBitmapFontVersion0(), round_box_shadow_edges(), screen_animation_step(), sequencer_separate_images_exec(), ui_def_but_rna(), ui_get_but_step_unit(), ui_searchbox_select(), ui_textedit_delete(), ui_textedit_type_buf(), UI_view2d_constant_grid_draw(), UI_view2d_grid_draw(), uiBlockPicker(), uiTemplateColorWheel(), uiTemplateMarker(), btRaycastVehicle::updateVehicle(), uvedit_vertex_buttons(), Vector_ass_subscript(), Vector_subscript(), view3d_smoothview_invoke(), and widget_softshadow().
point step (point edge, point x)
vector step (vector edge, vector x)
color step (color edge, color x)
normal step (normal edge, normal x)
int strlen (string s)
Referenced by action_get_item_transforms(), add_name(), add_text(), add_type(), amount_of_chars(), an_stringdec(), armature_extrude_exec(), MeshImporter::assign_material_to_geom(), AUD_OpenALDevice::AUD_OpenALDevice(), avi_fetchibuf(), BIF_menustringTransformOrientation(), BKE_add_image_file(), BKE_add_movieclip_file(), BKE_keyingset_add_path(), BKE_ptcache_disk_cache_rename(), BKE_ptcache_id_clear(), BKE_ptcache_id_time(), BKE_ptcache_load_external(), BKE_rebase_path(), BKE_report(), BLF_pgettext(), BLI_add_slash(), bli_builddir(), BLI_cleanup_path(), BLI_del_slash(), BLI_dir_create_recursive(), BLI_dir_free_space(), BLI_dynstr_append(), BLI_dynstr_get_cstring_ex(), BLI_ensure_extension(), BLI_getQuotedStr(), BLI_make_exist(), BLI_make_file_string(), BLI_path_cwd(), BLI_replace_extension(), BLI_replacestr(), BLI_setenv(), BLI_split_name_num(), BLI_strcasestr(), BLI_strdup(), BLI_strdupcat(), BLI_stringdec(), BLI_strncpy(), BLI_testextensie(), BLO_is_a_library(), bone_autoside_name(), bpy_text_import(), bpy_text_import_name(), bUnit_ToUnitAltName(), calculate_structlens(), cast_elem(), cast_pointer(), check_destination(), console_lb_add__internal(), console_lb_add_str__internal(), console_line_insert(), console_scrollback_prompt_begin(), console_textview_line_color(), constraint_target_to_mat4(), convert_include(), copy_text(), direct_link_text(), DNA_struct_switch_endian(), do_history(), do_versions(), do_write_image_or_movie(), draw_brackets(), draw_mesh_text(), draw_volume(), dynamicPaint_initBake(), elementsize(), AnimationExporter::enable_fcurves(), ensure_digits(), exec_output_file_multilayer(), execute_blenderplayer(), exr_rgba_channelname(), fcurve_path_rename(), file_browse_exec(), file_is_blend_backup(), file_select_do(), file_shorten_string(), find_family_object(), AnimationExporter::find_frames(), folderlist_pushdir(), font_duplilist(), fsmenu_read_bookmarks(), fsmenu_read_system(), get_filename(), get_sequence_fname(), GHOST_SystemX11::getClipboard(), GHOST_SystemWin32::getClipboard(), GHOST_SystemCocoa::GHOST_SystemCocoa(), GPU_shader_export(), IDP_AssignString(), IDP_ConcatStringC(), IDP_New(), IDP_NewString(), imb_exr_split_channel_name(), insert_lorem_exec(), is_basis_mball(), is_hidden_file(), join_dirfile_alloc(), kernel_tex_copy(), layer_menu(), load_editText(), loadTile(), make_new_line(), make_pass_name(), make_structDNA(), new_id(), EffectsExporter::operator()(), operator+(), STR_String::operator+=(), STR_String::operator=(), operator_search_cb(), pass_menu(), pastebuf_match_path_property(), ply_open_for_reading(), ply_open_for_writing(), pose_slide_apply_props(), poselib_preview_handle_event(), poselib_preview_handle_search(), processEvent(), ptcache_filename(), ptcache_path(), GHOST_SystemX11::putClipboard(), GHOST_SystemCarbon::putClipboard(), PyC_UnicodeFromByte(), python_script_exec(), reconstruct_elem(), reconstruct_struct(), replace_if_different(), rna_alloc_function_name(), rna_find_sdna_member(), RNA_function_call_direct_va(), rna_generate_property(), rna_path_rename_fix(), rna_preprocess(), RNA_property_collection_lookup_string(), RNA_property_string_default_length(), RNA_property_string_length(), rna_token_strip_quotes(), saveTile(), scolumn_bmod(), scroll_printstr(), seq_remap_paths(), set_addons(), sgstrs(), shader_print_errors(), slot_menu(), sound_new_file(), sp_strsv(), spanel_bmod(), ssnode_bmod(), STR_String::STR_String(), string_dup(), substr(), text_check_format_len(), text_convert_whitespace_exec(), texttool_docs_show(), texttool_suggest_add(), texttool_suggest_prefix(), thumbname_from_uri(), txt_add_object(), txt_extended_ascii_as_utf8(), txt_find_string(), txt_format_line(), txt_insert_buf(), txt_new_line(), txt_new_linen(), txt_undo_add_block(), ui_check_but(), ui_def_but(), ui_item_name_add_colon(), ui_text_label_rightclip(), ui_text_leftclip(), ui_textedit_autocomplete(), ui_textedit_begin(), ui_textedit_copypaste(), ui_textedit_delete(), ui_textedit_delete_selection(), ui_textedit_end(), ui_textedit_move(), ui_textedit_set_cursor_pos(), ui_textedit_type_buf(), UI_view2d_text_cache_add(), UI_view2d_text_cache_rectf(), unique_name(), unique_property(), unit_find_str(), unit_scale_str(), untitled(), uri_from_filename(), Vector_to_track_quat(), verify_driver_fcurve(), verify_fcurve(), view3d_cached_text_draw_add(), WM_clipboard_text_get(), wm_read_exotic(), WM_write_file(), write_animdata(), write_fcurves(), write_jpeg(), write_keyingsets(), and write_texts().
string substr (string s, int start, int len)
Referenced by substr().
string substr (string s, int start)
Definition at line 415 of file stdosl.h.
References strlen(), and substr().
closure color subsurface (float eta, float g, float mfp, float albedo)
vector transform (string fromspace, string tospace, vector x)
Definition at line 232 of file stdosl.h.
References transform().
point transform (string fromspace, string tospace, point x)
Definition at line 221 of file stdosl.h.
References transform().
point transform (string tospace, point x)
Definition at line 216 of file stdosl.h.
References transform().
vector transform (string tospace, vector x)
Definition at line 227 of file stdosl.h.
References transform().
normal transform (string tospace, normal x)
Definition at line 238 of file stdosl.h.
References transform().
point transform (matrix Mto, point p)
vector transform (matrix Mto, vector p)
normal transform (string fromspace, string tospace, normal x)
Definition at line 243 of file stdosl.h.
References transform().
normal transform (matrix Mto, normal p)
Referenced by ATTRIBUTE_ALIGNED16(), bvh_done< VBVHTree >(), do_transform(), btIDebugDraw::drawCapsule(), AnimationImporter::find_frames_old(), AnimationImporter::get_animation_type(), init_transform_effect(), RAS_MeshSlot::Join(), btGImpactCompoundShape::setChildTransform(), RAS_OpenGLRasterizer::SetViewMatrix(), shrinkwrap_get_tarmat(), transform(), and AnimationImporter::translate_Animations().
color transformc (string to, color x)
Definition at line 260 of file stdosl.h.
References dot(), error(), g, max, min, and rgb_to_hsv().
Referenced by transformc().
color transformc (string from, string to, color x)
Definition at line 323 of file stdosl.h.
References dot(), error(), hsv_to_rgb(), min, p, and transformc().
float transformu (string tounits, float x)
float transformu (string fromunits, string tounits, float x)
closure color translucent (normal N)
closure color transparent ()
Referenced by sdl_ghost_CreateCursor().
matrix transpose (matrix m)
Referenced by IK_QJacobian::ComputeNullProjection(), IK_QJacobian::Invert(), and PolarDecompose().
closure color ward (normal N, vector T, float ax, float ay)
closure color westin_backscatter (normal N, float roughness)
closure color westin_sheen (normal N, float edginess)