Blender: SCA_ActuatorEventManager Class Reference
SCA_ActuatorEventManager Class Reference
#include <SCA_ActuatorEventManager.h>
Public Member Functions
SCA_ActuatorEventManager (class SCA_LogicManager *logicmgr)
virtual ~SCA_ActuatorEventManager ()
virtual void NextFrame ()
virtual void UpdateFrame ()
Detailed Description
Definition at line 41 of file SCA_ActuatorEventManager.h.
Constructor & Destructor Documentation
SCA_ActuatorEventManager::SCA_ActuatorEventManager (class SCA_LogicManager * logicmgr)
Definition at line 38 of file SCA_ActuatorEventManager.cpp.
SCA_ActuatorEventManager::~SCA_ActuatorEventManager () [virtual]
Definition at line 45 of file SCA_ActuatorEventManager.cpp.
Member Function Documentation
void SCA_ActuatorEventManager::NextFrame () [virtual]
Reimplemented from SCA_EventManager.
Definition at line 50 of file SCA_ActuatorEventManager.cpp.
References SG_DList::iterator< T >::begin(), SG_DList::iterator< T >::end(), SCA_EventManager::m_logicmgr, and SCA_EventManager::m_sensors.
void SCA_ActuatorEventManager::UpdateFrame () [virtual]
Reimplemented from SCA_EventManager.
Definition at line 60 of file SCA_ActuatorEventManager.cpp.
References SG_DList::iterator< T >::begin(), SG_DList::iterator< T >::end(), and SCA_EventManager::m_sensors.
The documentation for this class was generated from the following files:
SCA_ActuatorEventManager.h
SCA_ActuatorEventManager.cpp