Blender: editmesh_loopcut.c File Reference
editmesh_loopcut.c File Reference
mesh
#include <float.h>
#include <math.h>
#include <string.h>
#include <ctype.h>
#include <stdio.h>
#include "DNA_ID.h"
#include "DNA_object_types.h"
#include "DNA_mesh_types.h"
#include "DNA_screen_types.h"
#include "DNA_scene_types.h"
#include "DNA_userdef_types.h"
#include "MEM_guardedalloc.h"
#include "PIL_time.h"
#include "BLI_array.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_dynstr.h"
#include "BLI_utildefines.h"
#include "BKE_blender.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_mesh.h"
#include "BKE_modifier.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "BKE_tessmesh.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "IMB_imbuf_types.h"
#include "ED_screen.h"
#include "ED_space_api.h"
#include "ED_view3d.h"
#include "ED_mesh.h"
#include "ED_numinput.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "UI_interface.h"
#include "WM_api.h"
#include "WM_types.h"
#include "mesh_intern.h"
Classes
struct tringselOpData
Defines
#define _USE_MATH_DEFINES
Typedefs
typedef struct tringselOpData tringselOpData
Functions
static void ringsel_draw (const bContext *C, ARegion *UNUSED(ar), void *arg)
static void edgering_find_order (BMEdge *lasteed, BMEdge *eed, BMVert *lastv1, BMVert *v[2][2])
static void edgering_sel (tringselOpData *lcd, int previewlines, int select)
static void ringsel_find_edge (tringselOpData *lcd, int cuts)
static void ringsel_finish (bContext *C, wmOperator *op)
static void ringsel_exit (bContext *UNUSED(C), wmOperator *op)
static int ringsel_init (bContext *C, wmOperator *op, int do_cut)
static int ringcut_cancel (bContext *C, wmOperator *op)
static int ringcut_invoke (bContext *C, wmOperator *op, wmEvent *evt)
static int loopcut_modal (bContext *C, wmOperator *op, wmEvent *event)
void MESH_OT_loopcut (wmOperatorType *ot)
Detailed Description
Definition in file editmesh_loopcut.c.
Define Documentation
#define _USE_MATH_DEFINES
Definition at line 32 of file editmesh_loopcut.c.
Typedef Documentation
typedef struct tringselOpData tringselOpData
Function Documentation
static void edgering_find_order (BMEdge * lasteed, BMEdge * eed, BMVert * lastv1, BMVert * v[2][2]) [static]
Definition at line 137 of file editmesh_loopcut.c.
References BM_edge_in_face(), BM_face_other_edge_loop(), BM_ITER_ELEM, BM_LOOPS_OF_LOOP, BMLoop::e, BMLoop::f, BMEdge::l, BMLoop::next, BMLoop::prev, BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by edgering_sel().
static void edgering_sel (tringselOpData * lcd, int previewlines, int select) [static]
Definition at line 179 of file editmesh_loopcut.c.
References BLI_array_declare, BLI_array_growitems, BMEditMesh::bm, BM_edge_select_set(), BM_edge_share_face_count(), BM_ELEM_SELECT, BMW_begin(), BMW_EDGERING, BMW_end(), BMW_FLAG_TEST_HIDDEN, BMW_init(), BMW_MASK_NOP, BMW_NIL_LAY, BMW_step(), co, BMVert::co, copy_v3_v3(), EDBM_flag_disable_all(), edgering_find_order(), tringselOpData::edges, tringselOpData::eed, tringselOpData::em, tringselOpData::extend, i, MEM_freeN(), NULL, tringselOpData::totedge, TRUE, BMEdge::v1, and BMEdge::v2.
Referenced by ringsel_find_edge(), and ringsel_finish().
static int loopcut_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 434 of file editmesh_loopcut.c.
References applyNumInput(), tringselOpData::ar, BLI_snprintf(), CLAMPIS, CTX_wm_area(), wmOperator::customdata, ED_area_headerprint(), ED_region_tag_redraw(), EDBM_edge_find_nearest(), tringselOpData::eed, ESCKEY, handleNumInput(), KM_PRESS, KM_RELEASE, LEFTMOUSE, MAX2, MOUSEMOVE, ViewContext::mval, NULL, tringselOpData::num, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, PADMINUS, PADPLUSKEY, PAGEDOWNKEY, PAGEUPKEY, wmOperator::ptr, RETKEY, RIGHTMOUSE, ringcut_cancel(), ringsel_exit(), ringsel_find_edge(), ringsel_finish(), RNA_int_get(), RNA_int_set(), TRUE, wmEvent::type, wmEvent::val, tringselOpData::vc, view3d_operator_needs_opengl(), WHEELDOWNMOUSE, and WHEELUPMOUSE.
Referenced by MESH_OT_loopcut().
void MESH_OT_loopcut (wmOperatorType * ot)
Definition at line 569 of file editmesh_loopcut.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_editmesh_region_view3d(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, loopcut_modal(), wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_SKIP_SAVE, ringcut_cancel(), ringcut_invoke(), RNA_def_int(), RNA_def_property_flag(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
static int ringcut_cancel (bContext * C, wmOperator * op) [static]
Definition at line 395 of file editmesh_loopcut.c.
References OPERATOR_CANCELLED, and ringsel_exit().
Referenced by loopcut_modal(), and MESH_OT_loopcut().
static int ringcut_invoke (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 402 of file editmesh_loopcut.c.
References BKE_report(), CTX_data_edit_object(), CTX_wm_area(), wmOperator::customdata, ED_area_headerprint(), EDBM_edge_find_nearest(), tringselOpData::eed, modifiers_isDeformedByArmature(), modifiers_isDeformedByLattice(), ViewContext::mval, wmEvent::mval, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, wmOperator::reports, ringsel_find_edge(), ringsel_init(), RPT_WARNING, tringselOpData::vc, view3d_operator_needs_opengl(), and WM_event_add_modal_handler().
Referenced by MESH_OT_loopcut().
static void ringsel_draw (const bContext * C, ARegion * UNUSEDar, void * arg) [static]
Definition at line 108 of file editmesh_loopcut.c.
References CTX_wm_view3d(), tringselOpData::edges, glMultMatrixf, i, tringselOpData::ob, Object::obmat, tringselOpData::totedge, and View3D::zbuf.
Referenced by ringsel_init().
static void ringsel_exit (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 351 of file editmesh_loopcut.c.
References tringselOpData::ar, wmOperator::customdata, tringselOpData::draw_handle, ED_region_draw_cb_exit(), ED_region_tag_redraw(), tringselOpData::edges, MEM_freeN(), NULL, and ARegion::type.
Referenced by loopcut_modal(), and ringcut_cancel().
static void ringsel_find_edge (tringselOpData * lcd, int cuts) [static]
Definition at line 293 of file editmesh_loopcut.c.
References edgering_sel(), tringselOpData::edges, tringselOpData::eed, MEM_freeN(), NULL, and tringselOpData::totedge.
Referenced by loopcut_modal(), and ringcut_invoke().
static void ringsel_finish (bContext * C, wmOperator * op) [static]
Definition at line 305 of file editmesh_loopcut.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BM_mesh_esubdivide(), BM_select_history_store, CTX_data_scene(), CTX_data_tool_settings(), wmOperator::customdata, DAG_id_tag_update(), Object::data, tringselOpData::do_cut, EDBM_selectmode_flush(), EDBM_selectmode_set(), edgering_sel(), tringselOpData::eed, tringselOpData::em, FALSE, NC_GEOM, NC_SCENE, ND_DATA, ND_SELECT, ND_TOOLSETTINGS, tringselOpData::ob, wmOperator::ptr, RNA_int_get(), SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, ToolSettings::selectmode, SUBD_PATH, SUBDIV_SELECT_LOOPCUT, BMEdge::v1, and WM_event_add_notifier().
Referenced by loopcut_modal().
static int ringsel_init (bContext * C, wmOperator * op, int do_cut) [static]
Definition at line 369 of file editmesh_loopcut.c.
References tringselOpData::ar, BMEdit_FromObject(), CTX_data_edit_object(), CTX_wm_region(), wmOperator::customdata, tringselOpData::do_cut, tringselOpData::draw_handle, ED_region_draw_cb_activate(), ED_region_tag_redraw(), tringselOpData::em, em_setup_viewcontext(), tringselOpData::extend, NumInput::flag, NumInput::idx_max, initNumInput(), MEM_callocN(), tringselOpData::num, NUM_NO_FRACTION, NUM_NO_NEGATIVE, tringselOpData::ob, wmOperator::ptr, REGION_DRAW_POST_VIEW, ringsel_draw(), RNA_boolean_get(), ARegion::type, and tringselOpData::vc.
Referenced by ringcut_invoke().