Blender: EXP_C-Api.h File Reference
EXP_C-Api.h File Reference
Expressions
Defines
#define EXP_DECLARE_HANDLE(name) typedef struct name##__ { int unused; } *name
Functions
EXP_DECLARE_HANDLE (EXP_ValueHandle)
EXP_DECLARE_HANDLE (EXP_ExpressionHandle)
EXP_ValueHandle EXP_CreateInt (int innie)
EXP_ValueHandle EXP_CreateBool (int innie)
EXP_ValueHandle EXP_CreateString (const char *str)
void EXP_SetName (EXP_ValueHandle, const char *newname)
EXP_ValueHandle EXP_ParseInput (const char *inputtext)
void EXP_ReleaseValue (EXP_ValueHandle)
int EXP_IsValid (EXP_ValueHandle)
void EXP_SetProperty (EXP_ValueHandle propval, EXP_ValueHandle destinationval)
EXP_ValueHandle EXP_GetProperty (EXP_ValueHandle inval, const char *propname)
const char * EXP_GetText (EXP_ValueHandle)
Detailed Description
Definition in file EXP_C-Api.h.
Define Documentation
#define EXP_DECLARE_HANDLE (name) typedef struct name##__ { int unused; } *name
Definition at line 35 of file EXP_C-Api.h.
Function Documentation
EXP_ValueHandle EXP_CreateBool (int innie)
Definition at line 46 of file EXP_C-Api.cpp.
EXP_ValueHandle EXP_CreateInt (int innie)
Definition at line 39 of file EXP_C-Api.cpp.
EXP_ValueHandle EXP_CreateString (const char * str)
Definition at line 53 of file EXP_C-Api.cpp.
EXP_DECLARE_HANDLE (EXP_ExpressionHandle)
EXP_DECLARE_HANDLE (EXP_ValueHandle)
EXP_ValueHandle EXP_GetProperty (EXP_ValueHandle inval, const char * propname)
Definition at line 120 of file EXP_C-Api.cpp.
const char* EXP_GetText (EXP_ValueHandle)
Definition at line 113 of file EXP_C-Api.cpp.
int EXP_IsValid (EXP_ValueHandle)
Definition at line 96 of file EXP_C-Api.cpp.
EXP_ValueHandle EXP_ParseInput (const char * inputtext)
Definition at line 69 of file EXP_C-Api.cpp.
References CExpression::Calculate(), NULL, CParser::ProcessText(), and CExpression::Release().
void EXP_ReleaseValue (EXP_ValueHandle)
Definition at line 89 of file EXP_C-Api.cpp.
void EXP_SetName (EXP_ValueHandle , const char * newname)
Definition at line 61 of file EXP_C-Api.cpp.
void EXP_SetProperty (EXP_ValueHandle propval, EXP_ValueHandle destinationval)