Blender: SceneExporter Class Reference
SceneExporter Class Reference
#include <SceneExporter.h>
Public Member Functions
SceneExporter (COLLADASW::StreamWriter *sw, ArmatureExporter *arm, const ExportSettings *export_settings)
void exportScene (Scene *sce)
Friends
class ArmatureExporter
Detailed Description
Definition at line 93 of file SceneExporter.h.
Constructor & Destructor Documentation
SceneExporter::SceneExporter (COLLADASW::StreamWriter * sw, ArmatureExporter * arm, const ExportSettings * export_settings)
Definition at line 29 of file SceneExporter.cpp.
Member Function Documentation
void SceneExporter::exportScene (Scene * sce)
Definition at line 33 of file SceneExporter.cpp.
References id_name(), and translate_id().
Referenced by DocumentExporter::exportCurrentScene().
Friends And Related Function Documentation
friend class ArmatureExporter [friend]
Definition at line 101 of file SceneExporter.h.
The documentation for this class was generated from the following files:
SceneExporter.h
SceneExporter.cpp