Blender: sp_preorder.c File Reference
sp_preorder.c File Reference
opennl
#include "ssp_defs.h"
Functions
int check_perm (char *, int, int *)
void sp_preorder (superlu_options_t *options, SuperMatrix *A, int *perm_c, int *etree, SuperMatrix *AC)
Detailed Description
Definition in file sp_preorder.c.
Function Documentation
int check_perm (char * what, int n, int * perm)
Definition at line 192 of file sp_preorder.c.
References ABORT, i, and SUPERLU_FREE.
Referenced by sp_preorder().
void sp_preorder (superlu_options_t * options, SuperMatrix * A, int * perm_c, int * etree, SuperMatrix * AC)
Definition at line 10 of file sp_preorder.c.
References ABORT, at_plus_a(), check_perm(), NCPformat::colbeg, NCPformat::colend, NCformat::colptr, DOFACT, SuperMatrix::Dtype, superlu_options_t::Fact, i, SuperMatrix::Mtype, SuperMatrix::ncol, NCformat::nnz, NCPformat::nnz, NO, SuperMatrix::nrow, NCformat::nzval, NCPformat::nzval, post, print_int_vec(), NCformat::rowind, NCPformat::rowind, SLU_NCP, sp_coletree(), sp_symetree(), SuperMatrix::Store, SuperMatrix::Stype, SUPERLU_FREE, SUPERLU_MALLOC, superlu_options_t::SymmetricMode, and TreePostorder().
Referenced by __nlFactorize_SUPERLU(), and sgssv().