Blender: drawobject.c File Reference
drawobject.c File Reference
3D view
#include <string.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "DNA_camera_types.h"
#include "DNA_curve_types.h"
#include "DNA_constraint_types.h"
#include "DNA_lamp_types.h"
#include "DNA_lattice_types.h"
#include "DNA_material_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_meta_types.h"
#include "DNA_scene_types.h"
#include "DNA_smoke_types.h"
#include "DNA_speaker_types.h"
#include "DNA_world_types.h"
#include "DNA_armature_types.h"
#include "BLI_utildefines.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_edgehash.h"
#include "BLI_rand.h"
#include "BKE_anim.h"
#include "BKE_armature.h"
#include "BKE_camera.h"
#include "BKE_constraint.h"
#include "BKE_curve.h"
#include "BKE_DerivedMesh.h"
#include "BKE_deform.h"
#include "BKE_displist.h"
#include "BKE_font.h"
#include "BKE_global.h"
#include "BKE_image.h"
#include "BKE_key.h"
#include "BKE_lattice.h"
#include "BKE_mesh.h"
#include "BKE_material.h"
#include "BKE_mball.h"
#include "BKE_modifier.h"
#include "BKE_object.h"
#include "BKE_paint.h"
#include "BKE_particle.h"
#include "BKE_pointcache.h"
#include "BKE_scene.h"
#include "BKE_unit.h"
#include "BKE_movieclip.h"
#include "BKE_tracking.h"
#include "BKE_tessmesh.h"
#include "smoke_API.h"
#include "IMB_imbuf.h"
#include "IMB_imbuf_types.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "GPU_draw.h"
#include "GPU_extensions.h"
#include "ED_mesh.h"
#include "ED_particle.h"
#include "ED_screen.h"
#include "ED_sculpt.h"
#include "ED_types.h"
#include "ED_curve.h"
#include "UI_resources.h"
#include "WM_api.h"
#include "wm_subwindow.h"
#include "BLF_api.h"
#include "view3d_intern.h"
Classes
struct foreachScreenVert_userData
struct foreachScreenEdge_userData
struct foreachScreenFace_userData
struct drawDMVerts_userData
struct drawDMEdgesSel_userData
struct drawDMFacesSel_userData
struct drawDMNormal_userData
struct bbsObmodeMeshVerts_userData
struct ViewCachedString
Defines
#define CIRCLE_RESOL 32
#define DRAW_EM_MEASURE_STATS_FACEAREA()
#define TH_HANDLE_COL_TOT ((TH_HANDLE_SEL_FREE - TH_HANDLE_FREE) + 1)
Typedefs
typedef enum eWireDrawMode eWireDrawMode
typedef struct
foreachScreenVert_userData foreachScreenVert_userData
typedef struct
foreachScreenEdge_userData foreachScreenEdge_userData
typedef struct
foreachScreenFace_userData foreachScreenFace_userData
typedef struct drawDMVerts_userData drawDMVerts_userData
typedef struct
drawDMEdgesSel_userData drawDMEdgesSel_userData
typedef struct
drawDMFacesSel_userData drawDMFacesSel_userData
typedef struct
drawDMNormal_userData drawDMNormal_userData
typedef struct
bbsObmodeMeshVerts_userData bbsObmodeMeshVerts_userData
typedef struct ViewCachedString ViewCachedString
Enumerations
enum eWireDrawMode { OBDRAW_WIRE_OFF = 0, OBDRAW_WIRE_ON = 1, OBDRAW_WIRE_ON_DEPTH = 2 }
Functions
static void draw_bounding_volume (Scene *scene, Object *ob, char type)
static void drawcube_size (float size)
static void drawcircle_size (float size)
static void draw_empty_sphere (float size)
static void draw_empty_cone (float size)
static int check_object_draw_texture (Scene *scene, View3D *v3d, int drawtype)
static int check_ob_drawface_dot (Scene *sce, View3D *vd, char dt)
static void view3d_project_short_clip (ARegion *ar, const float vec[3], short adr[2], int is_local)
static void UNUSED_FUNCTION() view3d_project_short_noclip (ARegion *ar, const float vec[3], short adr[2])
static void view3d_project_short_clip_persmat (ARegion *ar, const float vec[3], short adr[2], int is_local)
int draw_glsl_material (Scene *scene, Object *ob, View3D *v3d, int dt)
static int check_alpha_pass (Base *base)
static void draw_xyz_wire (const float c[3], float size, int axis)
void drawaxes (float size, char drawtype)
static void draw_empty_image (Object *ob)
static void circball_array_fill (float verts[CIRCLE_RESOL][3], const float cent[3], float rad, float tmat[][4])
void drawcircball (int mode, const float cent[3], float rad, float tmat[][4])
static void drawcentercircle (View3D *v3d, RegionView3D *rv3d, const float co[3], int selstate, int special_color)
void view3d_cached_text_draw_begin (void)
void view3d_cached_text_draw_add (const float co[3], const char *str, short xoffs, short flag, const unsigned char col[4])
void view3d_cached_text_draw_end (View3D *v3d, ARegion *ar, int depth_write, float mat[][4])
static void drawcube (void)
static void drawshadbuflimits (Lamp *la, float mat[][4])
static void spotvolume (float lvec[3], float vvec[3], const float inp)
static void draw_spot_cone (Lamp *la, float x, float z)
static void draw_transp_spot_volume (Lamp *la, float x, float z)
static void drawlamp (Scene *scene, View3D *v3d, RegionView3D *rv3d, Base *base, int dt, int flag)
static void draw_limit_line (float sta, float end, unsigned int col)
static void draw_focus_cross (float dist, float size)
static void draw_bundle_sphere (void)
static void draw_viewport_object_reconstruction (Scene *scene, Base *base, View3D *v3d, MovieClip *clip, MovieTrackingObject *tracking_object, int flag, int *global_track_index, int draw_selected)
static void draw_viewport_reconstruction (Scene *scene, Base *base, View3D *v3d, MovieClip *clip, int flag, int draw_selected)
static void drawcamera (Scene *scene, View3D *v3d, RegionView3D *rv3d, Base *base, int flag)
static void drawspeaker (Scene *UNUSED(scene), View3D *UNUSED(v3d), RegionView3D *UNUSED(rv3d), Object *UNUSED(ob), int UNUSED(flag))
static void lattice_draw_verts (Lattice *lt, DispList *dl, short sel)
void lattice_foreachScreenVert (ViewContext *vc, void(*func)(void *userData, BPoint *bp, int x, int y), void *userData)
static void drawlattice__point (Lattice *lt, DispList *dl, int u, int v, int w, int use_wcol)
static void drawlattice (Scene *scene, View3D *v3d, Object *ob)
static void mesh_foreachScreenVert__mapFunc (void *userData, int index, const float co[3], const float UNUSED(no_f[3]), const short UNUSED(no_s[3]))
void mesh_foreachScreenVert (ViewContext *vc, void(*func)(void *userData, BMVert *eve, int x, int y, int index), void *userData, eV3DClipTest clipVerts)
static void drawSelectedVertices__mapFunc (void *userData, int index, const float co[3], const float UNUSED(no_f[3]), const short UNUSED(no_s[3]))
static void drawSelectedVertices (DerivedMesh *dm, Mesh *me)
static void mesh_foreachScreenEdge__mapFunc (void *userData, int index, const float v0co[3], const float v1co[3])
void mesh_foreachScreenEdge (ViewContext *vc, void(*func)(void *userData, BMEdge *eed, int x0, int y0, int x1, int y1, int index), void *userData, eV3DClipTest clipVerts)
static void mesh_foreachScreenFace__mapFunc (void *userData, int index, const float cent[3], const float UNUSED(no[3]))
void mesh_foreachScreenFace (ViewContext *vc, void(*func)(void *userData, BMFace *efa, int x, int y, int index), void *userData)
void nurbs_foreachScreenVert (ViewContext *vc, void(*func)(void *userData, Nurb *nu, BPoint *bp, BezTriple *bezt, int beztindex, int x, int y), void *userData)
static void draw_dm_face_normals__mapFunc (void *userData, int index, const float cent[3], const float no[3])
static void draw_dm_face_normals (BMEditMesh *em, Scene *scene, DerivedMesh *dm)
static void draw_dm_face_centers__mapFunc (void *userData, int index, const float cent[3], const float UNUSED(no[3]))
static void draw_dm_face_centers (BMEditMesh *em, DerivedMesh *dm, int sel)
static void draw_dm_vert_normals__mapFunc (void *userData, int index, const float co[3], const float no_f[3], const short no_s[3])
static void draw_dm_vert_normals (BMEditMesh *em, Scene *scene, DerivedMesh *dm)
static void draw_dm_verts__mapFunc (void *userData, int index, const float co[3], const float UNUSED(no_f[3]), const short UNUSED(no_s[3]))
static void draw_dm_verts (BMEditMesh *em, DerivedMesh *dm, int sel, BMVert *eve_act)
static DMDrawOption draw_dm_edges_sel__setDrawOptions (void *userData, int index)
static void draw_dm_edges_sel (BMEditMesh *em, DerivedMesh *dm, unsigned char *baseCol, unsigned char *selCol, unsigned char *actCol, BMEdge *eed_act)
static DMDrawOption draw_dm_edges__setDrawOptions (void *userData, int index)
static void draw_dm_edges (BMEditMesh *em, DerivedMesh *dm)
static DMDrawOption draw_dm_edges_sel_interp__setDrawOptions (void *userData, int index)
static void draw_dm_edges_sel_interp__setDrawInterpOptions (void *userData, int index, float t)
static void draw_dm_edges_sel_interp (BMEditMesh *em, DerivedMesh *dm, unsigned char *baseCol, unsigned char *selCol)
static DMDrawOption draw_dm_edges_seams__setDrawOptions (void *userData, int index)
static void draw_dm_edges_seams (BMEditMesh *em, DerivedMesh *dm)
static DMDrawOption draw_dm_edges_sharp__setDrawOptions (void *userData, int index)
static void draw_dm_edges_sharp (BMEditMesh *em, DerivedMesh *dm)
static DMDrawOption draw_dm_faces_sel__setDrawOptions (void *userData, int index)
static int draw_dm_faces_sel__compareDrawOptions (void *userData, int index, int next_index)
static void draw_dm_faces_sel (BMEditMesh *em, DerivedMesh *dm, unsigned char *baseCol, unsigned char *selCol, unsigned char *actCol, BMFace *efa_act)
static DMDrawOption draw_dm_creases__setDrawOptions (void *userData, int index)
static void draw_dm_creases (BMEditMesh *em, DerivedMesh *dm)
static DMDrawOption draw_dm_bweights__setDrawOptions (void *userData, int index)
static void draw_dm_bweights__mapFunc (void *userData, int index, const float co[3], const float UNUSED(no_f[3]), const short UNUSED(no_s[3]))
static void draw_dm_bweights (BMEditMesh *em, Scene *scene, DerivedMesh *dm)
static void draw_em_fancy_verts (Scene *scene, View3D *v3d, Object *obedit, BMEditMesh *em, DerivedMesh *cageDM, BMVert *eve_act)
static void draw_em_fancy_edges (BMEditMesh *em, Scene *scene, View3D *v3d, Mesh *me, DerivedMesh *cageDM, short sel_only, BMEdge *eed_act)
static void draw_em_measure_stats (View3D *v3d, Object *ob, BMEditMesh *em, UnitSettings *unit)
static void draw_em_indices (BMEditMesh *em)
static DMDrawOption draw_em_fancy__setFaceOpts (void *userData, int index)
static DMDrawOption draw_em_fancy__setGLSLFaceOpts (void *userData, int index)
static void draw_em_fancy (Scene *scene, View3D *v3d, RegionView3D *rv3d, Object *ob, BMEditMesh *em, DerivedMesh *cageDM, DerivedMesh *finalDM, int dt)
static void draw_mesh_object_outline (View3D *v3d, Object *ob, DerivedMesh *dm)
static void draw_mesh_fancy (Scene *scene, ARegion *ar, View3D *v3d, RegionView3D *rv3d, Base *base, int dt, int flag)
static int draw_mesh_object (Scene *scene, ARegion *ar, View3D *v3d, RegionView3D *rv3d, Base *base, int dt, int flag)
static int drawDispListwire (ListBase *dlbase)
static void drawDispListsolid (ListBase *lb, Object *ob, int glsl)
static void drawCurveDMWired (Object *ob)
static int drawCurveDerivedMesh (Scene *scene, View3D *v3d, RegionView3D *rv3d, Base *base, int dt)
static int drawDispList (Scene *scene, View3D *v3d, RegionView3D *rv3d, Base *base, int dt)
static void draw_particle_arrays (int draw_as, int totpoint, int ob_dt, int select)
static void draw_particle (ParticleKey *state, int draw_as, short draw, float pixsize, float imat[4][4], float *draw_line, ParticleBillboardData *bb, ParticleDrawData *pdd)
static void draw_new_particle_system (Scene *scene, View3D *v3d, RegionView3D *rv3d, Base *base, ParticleSystem *psys, int ob_dt)
static void draw_update_ptcache_edit (Scene *scene, Object *ob, PTCacheEdit *edit)
static void draw_ptcache_edit (Scene *scene, View3D *v3d, PTCacheEdit *edit)
static void ob_draw_RE_motion (float com[3], float rotscale[3][3], float itw, float ith, float drw_size)
static void tekenhandlesN (Nurb *nu, short sel, short hide_handles)
static void tekenhandlesN_active (Nurb *nu)
static void tekenvertsN (Nurb *nu, short sel, short hide_handles, void *lastsel)
static void editnurb_draw_active_poly (Nurb *nu)
static void editnurb_draw_active_nurbs (Nurb *nu)
static void draw_editnurb (Object *ob, Nurb *nurb, int sel)
static void drawnurb (Scene *scene, View3D *v3d, RegionView3D *rv3d, Base *base, Nurb *nurb, int dt)
static void draw_textcurs (float textcurs[4][2])
static void drawspiral (const float cent[3], float rad, float tmat[][4], int start)
static void drawtube (const float vec[3], float radius, float height, float tmat[][4])
static void drawcone (const float vec[3], float radius, float height, float tmat[][4])
static int drawmball (Scene *scene, View3D *v3d, RegionView3D *rv3d, Base *base, int dt)
static void draw_forcefield (Scene *scene, Object *ob, RegionView3D *rv3d)
static void draw_box (float vec[8][3])
static void draw_bb_quadric (BoundBox *bb, char type)
static void drawtexspace (Object *ob)
static void drawObjectSelect (Scene *scene, View3D *v3d, ARegion *ar, Base *base)
static void drawWireExtra (Scene *scene, RegionView3D *rv3d, Object *ob)
static void draw_hooks (Object *ob)
static void drawRBpivot (bRigidBodyJointConstraint *data)
void draw_object (Scene *scene, ARegion *ar, View3D *v3d, Base *base, int flag)
static void bbs_obmode_mesh_verts__mapFunc (void *userData, int index, const float co[3], const float UNUSED(no_f[3]), const short UNUSED(no_s[3]))
static void bbs_obmode_mesh_verts (Object *ob, DerivedMesh *dm, int offset)
static void bbs_mesh_verts__mapFunc (void *userData, int index, const float co[3], const float UNUSED(no_f[3]), const short UNUSED(no_s[3]))
static void bbs_mesh_verts (BMEditMesh *em, DerivedMesh *dm, int offset)
static DMDrawOption bbs_mesh_wire__setDrawOptions (void *userData, int index)
static void bbs_mesh_wire (BMEditMesh *em, DerivedMesh *dm, int offset)
static DMDrawOption bbs_mesh_solid__setSolidDrawOptions (void *userData, int index)
static void bbs_mesh_solid__drawCenter (void *userData, int index, const float cent[3], const float UNUSED(no[3]))
static void bbs_mesh_solid_EM (BMEditMesh *em, Scene *scene, View3D *v3d, Object *ob, DerivedMesh *dm, int facecol)
static DMDrawOption bbs_mesh_solid__setDrawOpts (void *UNUSED(userData), int index)
static DMDrawOption bbs_mesh_solid_hide__setDrawOpts (void *userData, int index)
static DMDrawOption bbs_mesh_solid_hide2__setDrawOpts (void *userData, int index)
static void bbs_mesh_solid (Scene *scene, Object *ob)
void draw_object_backbufsel (Scene *scene, View3D *v3d, RegionView3D *rv3d, Object *ob)
static void draw_object_mesh_instance (Scene *scene, View3D *v3d, RegionView3D *rv3d, Object *ob, int dt, int outline)
void draw_object_instance (Scene *scene, View3D *v3d, RegionView3D *rv3d, Object *ob, int dt, int outline)
Variables
static unsigned int colortab [24]
static float cube [8][3]
static const float sinval [CIRCLE_RESOL]
static const float cosval [CIRCLE_RESOL]
static ListBase CachedText [3]
static int CachedTextLevel = 0
float view3d_camera_border_hack_col [4]
short view3d_camera_border_hack_test = FALSE
static int draw_index_wire = 1
static int index3_nors_incr = 1
Detailed Description
Definition in file drawobject.c.
Define Documentation
#define CIRCLE_RESOL 32
Definition at line 370 of file drawobject.c.
Referenced by circball_array_fill(), drawcentercircle(), drawcircball(), drawcircle_size(), and drawspiral().
#define DRAW_EM_MEASURE_STATS_FACEAREA ()
Value:
if (BM_elem_flag_test(f, BM_ELEM_SELECT)) {                               \
        mul_v3_fl(vmid, 1.0 / n);                                             \
        if (unit->system)                                                     \
            bUnit_AsString(numstr, sizeof(numstr), area * unit->scale_length, \
                           3, unit->system, B_UNIT_LENGTH, do_split, FALSE);  \
        else                                                                  \
            BLI_snprintf(numstr, sizeof(numstr), conv_float, area);           \
        view3d_cached_text_draw_add(vmid, numstr, 0, txt_flag, col);          \
    }
Referenced by draw_em_measure_stats().
#define TH_HANDLE_COL_TOT ((TH_HANDLE_SEL_FREE - TH_HANDLE_FREE) + 1)
Referenced by tekenhandlesN().
Typedef Documentation
typedef struct bbsObmodeMeshVerts_userData bbsObmodeMeshVerts_userData
typedef struct drawDMEdgesSel_userData drawDMEdgesSel_userData
typedef struct drawDMFacesSel_userData drawDMFacesSel_userData
typedef struct drawDMNormal_userData drawDMNormal_userData
typedef struct drawDMVerts_userData drawDMVerts_userData
typedef enum eWireDrawMode eWireDrawMode
typedef struct foreachScreenEdge_userData foreachScreenEdge_userData
typedef struct foreachScreenFace_userData foreachScreenFace_userData
typedef struct foreachScreenVert_userData foreachScreenVert_userData
typedef struct ViewCachedString ViewCachedString
Enumeration Type Documentation
enum eWireDrawMode
Enumerator:
OBDRAW_WIRE_OFF
OBDRAW_WIRE_ON
OBDRAW_WIRE_ON_DEPTH
Definition at line 112 of file drawobject.c.
Function Documentation
static void bbs_mesh_solid (Scene * scene, Object * ob) [static]
Definition at line 7303 of file drawobject.c.
References bbs_mesh_solid__setDrawOpts(), bbs_mesh_solid_hide__setDrawOpts(), Scene::customdata_mask, Object::data, DerivedMesh::drawMappedFaces, Mesh::editflag, GPU_enable_material(), ME_EDIT_PAINT_MASK, mesh_get_derived_final(), NULL, and DerivedMesh::release.
Referenced by draw_object_backbufsel().
static void bbs_mesh_solid__drawCenter (void * userData, int index, const float cent[3], const float UNUSEDno[3]) [static]
Definition at line 7236 of file drawobject.c.
References bglVertex3fv(), BM_elem_flag_test, BM_ELEM_HIDDEN, EDBM_face_at_index(), and WM_set_framebuffer_index_color().
Referenced by bbs_mesh_solid_EM().
static DMDrawOption bbs_mesh_solid__setDrawOpts (void * UNUSEDuserData, int index) [static]
Definition at line 7272 of file drawobject.c.
References DM_DRAW_OPTION_NORMAL, and WM_set_framebuffer_index_color().
Referenced by bbs_mesh_solid().
static DMDrawOption bbs_mesh_solid__setSolidDrawOptions (void * userData, int index) [static]
Definition at line 7221 of file drawobject.c.
References BM_elem_flag_test, BM_ELEM_HIDDEN, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, EDBM_face_at_index(), and WM_set_framebuffer_index_color().
Referenced by bbs_mesh_solid_EM().
static void bbs_mesh_solid_EM (BMEditMesh * em, Scene * scene, View3D * v3d, Object * ob, DerivedMesh * dm, int facecol) [static]
Definition at line 7248 of file drawobject.c.
References bbs_mesh_solid__drawCenter(), bbs_mesh_solid__setSolidDrawOptions(), bglBegin(), bglEnd(), check_ob_drawface_dot(), cpack, DerivedMesh::drawMappedFaces, Object::dt, DerivedMesh::foreachMappedFaceCenter, GPU_enable_material(), NULL, TH_FACEDOT_SIZE, and UI_GetThemeValuef().
Referenced by draw_object_backbufsel().
static DMDrawOption bbs_mesh_solid_hide2__setDrawOpts (void * userData, int index) [static]
Definition at line 7292 of file drawobject.c.
References DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, MPoly::flag, ME_HIDE, and Mesh::mpoly.
Referenced by draw_object_backbufsel().
static DMDrawOption bbs_mesh_solid_hide__setDrawOpts (void * userData, int index) [static]
Definition at line 7278 of file drawobject.c.
References DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, MPoly::flag, ME_HIDE, Mesh::mpoly, and WM_set_framebuffer_index_color().
Referenced by bbs_mesh_solid().
static void bbs_mesh_verts (BMEditMesh * em, DerivedMesh * dm, int offset) [static]
Definition at line 7190 of file drawobject.c.
References bbs_mesh_verts__mapFunc(), bglBegin(), bglEnd(), DerivedMesh::foreachMappedVert, TH_VERTEX_SIZE, and UI_GetThemeValuef().
Referenced by draw_object_backbufsel().
static void bbs_mesh_verts__mapFunc (void * userData, int index, const float co[3], const float UNUSEDno_f[3], const short UNUSEDno_s[3]) [static]
Definition at line 7178 of file drawobject.c.
References bglVertex3fv(), BM_elem_flag_test, BM_ELEM_HIDDEN, EDBM_vert_at_index(), and WM_set_framebuffer_index_color().
Referenced by bbs_mesh_verts().
static void bbs_mesh_wire (BMEditMesh * em, DerivedMesh * dm, int offset) [static]
Definition at line 7215 of file drawobject.c.
References bbs_mesh_wire__setDrawOptions(), and DerivedMesh::drawMappedEdges.
Referenced by draw_object_backbufsel().
static DMDrawOption bbs_mesh_wire__setDrawOptions (void * userData, int index) [static]
Definition at line 7201 of file drawobject.c.
References BM_elem_flag_test, BM_ELEM_HIDDEN, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, EDBM_edge_at_index(), and WM_set_framebuffer_index_color().
Referenced by bbs_mesh_wire().
static void bbs_obmode_mesh_verts (Object * ob, DerivedMesh * dm, int offset) [static]
Definition at line 7164 of file drawobject.c.
References bbs_obmode_mesh_verts__mapFunc(), bglBegin(), bglEnd(), Object::data, data, DerivedMesh::foreachMappedVert, bbsObmodeMeshVerts_userData::mvert, Mesh::mvert, bbsObmodeMeshVerts_userData::offset, TH_VERTEX_SIZE, and UI_GetThemeValuef().
Referenced by draw_object_backbufsel().
static void bbs_obmode_mesh_verts__mapFunc (void * userData, int index, const float co[3], const float UNUSEDno_f[3], const short UNUSEDno_s[3]) [static]
Definition at line 7151 of file drawobject.c.
References bglVertex3fv(), data, MVert::flag, if(), ME_HIDE, bbsObmodeMeshVerts_userData::mvert, bbsObmodeMeshVerts_userData::offset, and WM_set_framebuffer_index_color().
Referenced by bbs_obmode_mesh_verts().
static int check_alpha_pass (Base * base) [static]
Definition at line 337 of file drawobject.c.
References Object::dtx, Base::flag, G, G_PICKSEL, OB_DRAWTRANSP, OB_FROMDUPLI, and Base::object.
Referenced by draw_mesh_object().
static int check_ob_drawface_dot (Scene * sce, View3D * vd, char dt) [static]
Definition at line 195 of file drawobject.c.
References View3D::drawtype, View3D::flag, View3D::flag2, G, G_BACKBUFSEL, OB_SOLID, OB_TEXTURE, SCE_SELECT_FACE, ToolSettings::selectmode, Scene::toolsettings, V3D_SOLID_TEX, and V3D_ZBUF_SELECT.
Referenced by bbs_mesh_solid_EM(), and draw_em_fancy_verts().
static int check_object_draw_texture (Scene * scene, View3D * v3d, int drawtype) [static]
Definition at line 182 of file drawobject.c.
References View3D::drawtype, ELEM, FALSE, View3D::flag2, OB_MATERIAL, OB_SOLID, OB_TEXTURE, scene_use_new_shading_nodes(), TRUE, and V3D_SOLID_TEX.
Referenced by draw_em_fancy(), draw_glsl_material(), and draw_mesh_fancy().
static void circball_array_fill (float verts[CIRCLE_RESOL][3], const float cent[3], float rad, float tmat[][4]) [static]
Definition at line 729 of file drawobject.c.
References CIRCLE_RESOL, cosval, mul_v3_v3fl(), and sinval.
Referenced by drawcentercircle(), and drawcircball().
static void draw_bb_quadric (BoundBox * bb, char type) [static]
Definition at line 6094 of file drawobject.c.
References fabsf, OB_BOUND_CONE, OB_BOUND_CYLINDER, OB_BOUND_SPHERE, and BoundBox::vec.
Referenced by draw_bounding_volume().
static void draw_bounding_volume (Scene * scene, Object * ob, char type) [static]
Definition at line 6132 of file drawobject.c.
References Object::bb, BKE_armature_get_bb(), Object::data, draw_bb_quadric(), draw_box(), drawcube(), ELEM3, is_basis_mball(), makeDispListMBall(), mesh_get_bb(), NULL, OB_ARMATURE, OB_BOUND_BOX, OB_CURVE, OB_FONT, OB_MBALL, OB_MESH, OB_SURF, Object::type, and BoundBox::vec.
Referenced by draw_mesh_fancy(), and draw_object().
static void draw_box (float vec[8][3]) [static]
Definition at line 6057 of file drawobject.c.
Referenced by draw_bounding_volume(), and drawtexspace().
static void draw_bundle_sphere (void) [static]
Definition at line 1510 of file drawobject.c.
Referenced by draw_viewport_object_reconstruction().
static void draw_dm_bweights (BMEditMesh * em, Scene * scene, DerivedMesh * dm) [static]
Definition at line 2637 of file drawobject.c.
References bglBegin(), bglEnd(), draw_dm_bweights__mapFunc(), draw_dm_bweights__setDrawOptions(), DerivedMesh::drawMappedEdges, DerivedMesh::foreachMappedVert, SCE_SELECT_VERTEX, ToolSettings::selectmode, TH_VERTEX_SIZE, Scene::toolsettings, and UI_GetThemeValuef().
Referenced by draw_em_fancy().
static void draw_dm_bweights__mapFunc (void * userData, int index, const float co[3], const float UNUSEDno_f[3], const short UNUSEDno_s[3]) [static]
Definition at line 2622 of file drawobject.c.
References bglVertex3fv(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, CD_BWEIGHT, CustomData_bmesh_get(), BMHeader::data, EDBM_vert_at_index(), BMVert::head, TH_VERTEX, TH_VERTEX_SELECT, UI_ThemeColorBlend(), and BMesh::vdata.
Referenced by draw_dm_bweights().
static DMDrawOption draw_dm_bweights__setDrawOptions (void * userData, int index) [static]
Definition at line 2605 of file drawobject.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, CD_BWEIGHT, CustomData_bmesh_get(), BMHeader::data, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, BMesh::edata, EDBM_edge_at_index(), BMEdge::head, TH_EDGE_SELECT, TH_WIRE, and UI_ThemeColorBlend().
Referenced by draw_dm_bweights().
static void draw_dm_creases (BMEditMesh * em, DerivedMesh * dm) [static]
Definition at line 2598 of file drawobject.c.
References draw_dm_creases__setDrawOptions(), and DerivedMesh::drawMappedEdges.
Referenced by draw_em_fancy().
static DMDrawOption draw_dm_creases__setDrawOptions (void * userData, int index) [static]
Definition at line 2581 of file drawobject.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, CD_CREASE, CustomData_bmesh_get(), BMHeader::data, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, BMesh::edata, EDBM_edge_at_index(), BMEdge::head, NULL, TH_EDGE_CREASE, TH_WIRE, and UI_ThemeColorBlend().
Referenced by draw_dm_creases().
static void draw_dm_edges (BMEditMesh * em, DerivedMesh * dm) [static]
Definition at line 2442 of file drawobject.c.
References draw_dm_edges__setDrawOptions(), and DerivedMesh::drawMappedEdges.
Referenced by draw_em_fancy_edges().
static DMDrawOption draw_dm_edges__setDrawOptions (void * userData, int index) [static]
Definition at line 2434 of file drawobject.c.
References BM_elem_flag_test, BM_ELEM_HIDDEN, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, and EDBM_edge_at_index().
Referenced by draw_dm_edges().
static void draw_dm_edges_seams (BMEditMesh * em, DerivedMesh * dm) [static]
Definition at line 2486 of file drawobject.c.
References draw_dm_edges_seams__setDrawOptions(), and DerivedMesh::drawMappedEdges.
Referenced by draw_em_fancy().
static DMDrawOption draw_dm_edges_seams__setDrawOptions (void * userData, int index) [static]
Definition at line 2476 of file drawobject.c.
References BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SEAM, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, and EDBM_edge_at_index().
Referenced by draw_dm_edges_seams().
static void draw_dm_edges_sel (BMEditMesh * em, DerivedMesh * dm, unsigned char * baseCol, unsigned char * selCol, unsigned char * actCol, BMEdge * eed_act) [static]
Definition at line 2420 of file drawobject.c.
References drawDMEdgesSel_userData::actCol, drawDMEdgesSel_userData::baseCol, data, draw_dm_edges_sel__setDrawOptions(), DerivedMesh::drawMappedEdges, drawDMEdgesSel_userData::eed_act, drawDMEdgesSel_userData::em, and drawDMEdgesSel_userData::selCol.
Referenced by draw_em_fancy_edges().
static DMDrawOption draw_dm_edges_sel__setDrawOptions (void * userData, int index) [static]
Definition at line 2388 of file drawobject.c.
References drawDMEdgesSel_userData::actCol, drawDMEdgesSel_userData::baseCol, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, data, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, EDBM_edge_at_index(), drawDMEdgesSel_userData::eed_act, drawDMEdgesSel_userData::em, and drawDMEdgesSel_userData::selCol.
Referenced by draw_dm_edges_sel().
static void draw_dm_edges_sel_interp (BMEditMesh * em, DerivedMesh * dm, unsigned char * baseCol, unsigned char * selCol) [static]
Definition at line 2468 of file drawobject.c.
References draw_dm_edges_sel_interp__setDrawInterpOptions(), draw_dm_edges_sel_interp__setDrawOptions(), and DerivedMesh::drawMappedEdgesInterp.
Referenced by draw_em_fancy_edges().
static void draw_dm_edges_sel_interp__setDrawInterpOptions (void * userData, int index, float t) [static]
Definition at line 2455 of file drawobject.c.
References BM_elem_flag_test, BM_ELEM_SELECT, EDBM_edge_at_index(), BMEdge::v1, and BMEdge::v2.
Referenced by draw_dm_edges_sel_interp().
static DMDrawOption draw_dm_edges_sel_interp__setDrawOptions (void * userData, int index) [static]
Definition at line 2448 of file drawobject.c.
References BM_elem_flag_test, BM_ELEM_HIDDEN, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, and EDBM_edge_at_index().
Referenced by draw_dm_edges_sel_interp().
static void draw_dm_edges_sharp (BMEditMesh * em, DerivedMesh * dm) [static]
Definition at line 2502 of file drawobject.c.
References draw_dm_edges_sharp__setDrawOptions(), and DerivedMesh::drawMappedEdges.
Referenced by draw_em_fancy().
static DMDrawOption draw_dm_edges_sharp__setDrawOptions (void * userData, int index) [static]
Definition at line 2492 of file drawobject.c.
References BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SMOOTH, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, and EDBM_edge_at_index().
Referenced by draw_dm_edges_sharp().
static void draw_dm_face_centers (BMEditMesh * em, DerivedMesh * dm, int sel) [static]
Definition at line 2304 of file drawobject.c.
References bglBegin(), bglEnd(), draw_dm_face_centers__mapFunc(), and DerivedMesh::foreachMappedFaceCenter.
Referenced by draw_em_fancy_verts().
static void draw_dm_face_centers__mapFunc (void * userData, int index, const float cent[3], const float UNUSEDno[3]) [static]
Definition at line 2295 of file drawobject.c.
References bglVertex3fv(), BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, and EDBM_face_at_index().
Referenced by draw_dm_face_centers().
static void draw_dm_face_normals (BMEditMesh * em, Scene * scene, DerivedMesh * dm) [static]
Definition at line 2283 of file drawobject.c.
References data, draw_dm_face_normals__mapFunc(), drawDMNormal_userData::em, DerivedMesh::foreachMappedFaceCenter, drawDMNormal_userData::normalsize, ToolSettings::normalsize, and Scene::toolsettings.
Referenced by draw_em_fancy().
static void draw_dm_face_normals__mapFunc (void * userData, int index, const float cent[3], const float no[3]) [static]
Definition at line 2271 of file drawobject.c.
References BM_elem_flag_test, BM_ELEM_HIDDEN, data, EDBM_face_at_index(), drawDMNormal_userData::em, and drawDMNormal_userData::normalsize.
Referenced by draw_dm_face_normals().
static void draw_dm_faces_sel (BMEditMesh * em, DerivedMesh * dm, unsigned char * baseCol, unsigned char * selCol, unsigned char * actCol, BMFace * efa_act) [static]
Definition at line 2566 of file drawobject.c.
References CD_ORIGINDEX, drawDMFacesSel_userData::cols, data, drawDMFacesSel_userData::dm, DM_get_tessface_data_layer(), draw_dm_faces_sel__compareDrawOptions(), draw_dm_faces_sel__setDrawOptions(), DerivedMesh::drawMappedFaces, drawDMFacesSel_userData::efa_act, drawDMFacesSel_userData::em, GPU_enable_material(), and drawDMFacesSel_userData::orig_index.
Referenced by draw_em_fancy().
static int draw_dm_faces_sel__compareDrawOptions (void * userData, int index, int next_index) [static]
Definition at line 2535 of file drawobject.c.
References BM_elem_flag_test, BM_ELEM_SELECT, drawDMFacesSel_userData::cols, data, EDBM_face_at_index(), drawDMFacesSel_userData::efa_act, drawDMFacesSel_userData::em, and drawDMFacesSel_userData::orig_index.
Referenced by draw_dm_faces_sel().
static DMDrawOption draw_dm_faces_sel__setDrawOptions (void * userData, int index) [static]
Definition at line 2510 of file drawobject.c.
References BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, drawDMFacesSel_userData::cols, data, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, DM_DRAW_OPTION_STIPPLE, EDBM_face_at_index(), drawDMFacesSel_userData::efa_act, and drawDMFacesSel_userData::em.
Referenced by draw_dm_faces_sel().
static void draw_dm_vert_normals (BMEditMesh * em, Scene * scene, DerivedMesh * dm) [static]
Definition at line 2333 of file drawobject.c.
References data, draw_dm_vert_normals__mapFunc(), drawDMNormal_userData::em, DerivedMesh::foreachMappedVert, drawDMNormal_userData::normalsize, ToolSettings::normalsize, and Scene::toolsettings.
Referenced by draw_em_fancy().
static void draw_dm_vert_normals__mapFunc (void * userData, int index, const float co[3], const float no_f[3], const short no_s[3]) [static]
Definition at line 2313 of file drawobject.c.
References BM_elem_flag_test, BM_ELEM_HIDDEN, data, EDBM_vert_at_index(), drawDMNormal_userData::em, and drawDMNormal_userData::normalsize.
Referenced by draw_dm_vert_normals().
static void draw_dm_verts (BMEditMesh * em, DerivedMesh * dm, int sel, BMVert * eve_act) [static]
Definition at line 2375 of file drawobject.c.
References bglBegin(), bglEnd(), data, draw_dm_verts__mapFunc(), drawDMVerts_userData::em, drawDMVerts_userData::eve_act, DerivedMesh::foreachMappedVert, and drawDMVerts_userData::sel.
Referenced by draw_em_fancy_verts().
static void draw_dm_verts__mapFunc (void * userData, int index, const float co[3], const float UNUSEDno_f[3], const short UNUSEDno_s[3]) [static]
Definition at line 2346 of file drawobject.c.
References bglBegin(), bglEnd(), bglVertex3fv(), BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, data, EDBM_vert_at_index(), drawDMVerts_userData::em, drawDMVerts_userData::eve_act, drawDMVerts_userData::sel, size(), TH_EDITMESH_ACTIVE, TH_VERTEX, TH_VERTEX_SELECT, TH_VERTEX_SIZE, UI_GetThemeValuef(), and UI_ThemeColor4().
Referenced by draw_dm_verts().
static void draw_editnurb (Object * ob, Nurb * nurb, int sel) [static]
Definition at line 5373 of file drawobject.c.
References Curve::actnu, Nurb::bp, CU_NURBS, CU_POLY, Object::data, editnurb_draw_active_nurbs(), editnurb_draw_active_poly(), BPoint::f1, Nurb::flagu, BPoint::hide, Nurb::hide, Nurb::next, Nurb::pntsu, Nurb::pntsv, SELECT, TH_NURB_SEL_ULINE, TH_NURB_SEL_VLINE, TH_NURB_ULINE, TH_NURB_VLINE, Nurb::type, UI_ThemeColor(), and BPoint::vec.
Referenced by drawnurb().
static void draw_em_fancy (Scene * scene, View3D * v3d, RegionView3D * rv3d, Object * ob, BMEditMesh * em, DerivedMesh * cageDM, DerivedMesh * finalDM, int dt) [static]
Definition at line 3018 of file drawobject.c.
References bglPolygonOffset(), BMEditMesh::bm, BM_active_face_get(), BM_EDGE, BM_FACE, BM_VERT, CD_CREASE, check_object_draw_texture(), CustomData_has_layer(), Object::data, RegionView3D::dist, draw_dm_bweights(), draw_dm_creases(), draw_dm_edges_seams(), draw_dm_edges_sharp(), draw_dm_face_normals(), draw_dm_faces_sel(), draw_dm_vert_normals(), draw_em_fancy__setFaceOpts(), draw_em_fancy__setGLSLFaceOpts(), draw_em_fancy_edges(), draw_em_fancy_verts(), draw_em_indices(), draw_em_measure_stats(), draw_glsl_material(), draw_mesh_textured(), DerivedMesh::drawEdges, Mesh::drawflag, DerivedMesh::drawMappedFaces, DerivedMesh::drawMappedFacesGLSL, BMesh::edata, EDBM_index_arrays_free(), EDBM_index_arrays_init(), Mesh::edit_btmesh, BMEditSelection::ele, FALSE, Mesh::flag, View3D::flag2, G, G_DEBUG, GPU_disable_material(), GPU_enable_material(), BMEditSelection::htype, ListBase::last, ME_DRAW_VNORMALS, ME_DRAWBWEIGHTS, ME_DRAWCREASES, ME_DRAWEDGES, ME_DRAWEXTRA_EDGELEN, ME_DRAWEXTRA_FACEANG, ME_DRAWEXTRA_FACEAREA, ME_DRAWEXTRA_INDICES, ME_DRAWFACES, ME_DRAWNORMALS, ME_DRAWSEAMS, ME_DRAWSHARP, ME_TWOSIDED, NULL, OB_NEG_SCALE, OB_WIRE, BMesh::selected, TH_BACK, TH_EDGE_SEAM, TH_EDGE_SHARP, TH_EDITMESH_ACTIVE, TH_FACE, TH_FACE_SELECT, TH_NORMAL, TH_VNORMAL, TH_WIRE, Object::transflag, UI_GetThemeColor4ubv(), UI_ThemeColor(), UI_ThemeColorBlend(), Scene::unit, and V3D_RENDER_OVERRIDE.
Referenced by draw_mesh_object().
static DMDrawOption draw_em_fancy__setFaceOpts (void * userData, int index) [static]
Definition at line 2996 of file drawobject.c.
References BM_elem_flag_test, BM_ELEM_HIDDEN, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, EDBM_face_at_index(), GPU_enable_material(), BMFace::mat_nr, and NULL.
Referenced by draw_em_fancy().
static DMDrawOption draw_em_fancy__setGLSLFaceOpts (void * userData, int index) [static]
Definition at line 3008 of file drawobject.c.
References BM_elem_flag_test, BM_ELEM_HIDDEN, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, and EDBM_face_at_index().
Referenced by draw_em_fancy().
static void draw_em_fancy_edges (BMEditMesh * em, Scene * scene, View3D * v3d, Mesh * me, DerivedMesh * cageDM, short sel_only, BMEdge * eed_act) [static]
Definition at line 2723 of file drawobject.c.
References draw_dm_edges(), draw_dm_edges_sel(), draw_dm_edges_sel_interp(), Mesh::drawflag, DerivedMesh::drawMappedEdgesInterp, View3D::flag, ME_DRAWEDGES, SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, ToolSettings::selectmode, TH_EDGE_SELECT, TH_EDITMESH_ACTIVE, TH_WIRE, Scene::toolsettings, UI_GetThemeColor4ubv(), V3D_ZBUF_SELECT, and View3D::zbuf.
Referenced by draw_em_fancy().
static void draw_em_fancy_verts (Scene * scene, View3D * v3d, Object * obedit, BMEditMesh * em, DerivedMesh * cageDM, BMVert * eve_act) [static]
Definition at line 2663 of file drawobject.c.
References check_ob_drawface_dot(), draw_dm_face_centers(), draw_dm_verts(), Object::dt, View3D::flag, SCE_SELECT_VERTEX, ToolSettings::selectmode, size(), TH_FACE_DOT, TH_FACEDOT_SIZE, TH_VERTEX, TH_VERTEX_SELECT, TH_VERTEX_SIZE, TH_WIRE, Scene::toolsettings, UI_GetThemeColor3ubv(), UI_GetThemeValuef(), V3D_ZBUF_SELECT, and View3D::zbuf.
Referenced by draw_em_fancy().
static void draw_em_indices (BMEditMesh * em) [static]
Definition at line 2942 of file drawobject.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SELECT, BM_face_calc_center_mean(), BM_FACES_OF_MESH, BM_ITER_MESH, BM_VERTS_OF_MESH, BMVert::co, i, mid_v3_v3v3(), SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, TH_DRAWEXTRA_EDGELEN, TH_DRAWEXTRA_FACEANG, TH_DRAWEXTRA_FACEAREA, UI_GetThemeColor3ubv(), BMEdge::v1, BMEdge::v2, V3D_CACHE_TEXT_ASCII, V3D_CACHE_TEXT_LOCALCLIP, and view3d_cached_text_draw_add().
Referenced by draw_em_fancy().
static void draw_em_measure_stats (View3D * v3d, Object * ob, BMEditMesh * em, UnitSettings * unit) [static]
Definition at line 2786 of file drawobject.c.
References add_v3_v3(), angle_v3v3v3(), area_tri_v3(), B_UNIT_LENGTH, BLI_snprintf(), BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SELECT, BM_face_calc_center_bounds(), BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, bUnit_AsString(), BMVert::co, copy_v3_v3(), Object::data, DRAW_EM_MEASURE_STATS_FACEAREA, Mesh::drawflag, BMLoop::f, FALSE, View3D::flag, UnitSettings::flag, G, View3D::grid, i, interp_v3_v3v3(), len_v3v3(), BMEditMesh::looptris, ME_DRAWEXTRA_EDGELEN, ME_DRAWEXTRA_FACEANG, ME_DRAWEXTRA_FACEAREA, mid_v3_v3v3(), mul_mat3_m4_v3(), BMLoop::next, NULL, Object::obmat, BMLoop::prev, RAD2DEGF, UnitSettings::scale_length, UnitSettings::system, TH_DRAWEXTRA_EDGELEN, TH_DRAWEXTRA_FACEANG, TH_DRAWEXTRA_FACEAREA, BMEditMesh::tottri, UI_GetThemeColor3ubv(), USER_UNIT_OPT_SPLIT, BMLoop::v, BMEdge::v1, BMEdge::v2, V3D_CACHE_TEXT_ASCII, V3D_CACHE_TEXT_LOCALCLIP, V3D_GLOBAL_STATS, view3d_cached_text_draw_add(), and zero_v3().
Referenced by draw_em_fancy().
static void draw_empty_cone (float size) [static]
Definition at line 5613 of file drawobject.c.
References size().
Referenced by drawaxes().
static void draw_empty_image (Object * ob) [static]
Definition at line 641 of file drawobject.c.
References Image::aspx, Image::aspy, BKE_image_get_ibuf(), Object::col, Object::data, Object::empty_drawsize, Object::flag, glaDrawPixelsTex(), Object::ima_ofs, IMB_rect_from_float(), MAX2, NULL, SELECT, TH_SELECT, TH_WIRE, and UI_ThemeColor().
Referenced by draw_object(), and draw_object_instance().
static void draw_empty_sphere (float size) [static]
Definition at line 5579 of file drawobject.c.
Referenced by drawaxes().
static void draw_focus_cross (float dist, float size) [static]
Definition at line 1493 of file drawobject.c.
Referenced by drawcamera().
static void draw_forcefield (Scene * scene, Object * ob, RegionView3D * rv3d) [static]
Definition at line 5880 of file drawobject.c.
References copy_v3_v3(), cosf, CU_PATH, Object::data, Path::data, DEG2RADF, distance(), drawcircball(), drawcone(), drawspiral(), drawtube(), Object::empty_drawsize, PartDeflect::f_power, PartDeflect::f_strength, PartDeflect::falloff, PartDeflect::flag, Curve::flag, Object::flag, PartDeflect::forcefield, if(), invert_m4_m4(), PartDeflect::maxdist, PartDeflect::maxrad, PartDeflect::mindist, PartDeflect::minrad, NULL, OB_CURVE, OB_EMPTY, OBACT, Scene::obedit, Curve::path, Object::pd, PFIELD_FALL_CONE, PFIELD_FALL_SPHERE, PFIELD_FALL_TUBE, PFIELD_FORCE, PFIELD_GUIDE, PFIELD_POSZ, PFIELD_USEMAX, PFIELD_USEMAXR, PFIELD_USEMIN, PFIELD_USEMINR, PFIELD_VORTEX, PFIELD_WIND, powf, SELECT, setlinestyle(), sinf, size(), TH_ACTIVE, TH_BACK, TH_EMPTY, TH_SELECT, Object::type, UI_ThemeColorBlend(), unit_m4(), RegionView3D::viewmatob, and where_on_path().
Referenced by draw_object().
int draw_glsl_material (Scene * scene, Object * ob, View3D * v3d, int dt)
Definition at line 321 of file drawobject.c.
References check_object_draw_texture(), G, G_PICKSEL, GAME_MAT_GLSL, Scene::gm, GPU_glsl_support(), GameData::matmode, Object::mode, OB_MODE_WEIGHT_PAINT, OB_SOLID, OBACT, and scene_use_new_shading_nodes().
Referenced by draw_em_fancy(), draw_mesh_fancy(), draw_mesh_object(), draw_object_mesh_instance(), drawCurveDerivedMesh(), drawDispList(), ED_view3d_draw_offscreen(), and view3d_main_area_draw_objects().
static void draw_hooks (Object * ob) [static]
Definition at line 6304 of file drawobject.c.
References bglBegin(), bglEnd(), bglVertex3fv(), HookModifierData::cent, eModifierType_Hook, ListBase::first, Object::modifiers, mul_v3_m4v3(), ModifierData::next, HookModifierData::object, Object::obmat, setlinestyle(), and ModifierData::type.
Referenced by draw_object().
static void draw_limit_line (float sta, float end, unsigned int col) [static]
Definition at line 1474 of file drawobject.c.
References cpack.
Referenced by drawcamera().
static void draw_mesh_fancy (Scene * scene, ARegion * ar, View3D * v3d, RegionView3D * rv3d, Base * base, int dt, int flag) [static]
Definition at line 3225 of file drawobject.c.
References bglPolygonOffset(), Object::boundtype, CD_PREVIEW_MCOL, check_object_draw_texture(), Scene::customdata_mask, Object::data, RegionView3D::dist, DM_DRAW_ALWAYS_SMOOTH, DM_DRAW_USE_COLORS, DM_get_tessface_data_layer(), ARegion::do_draw, draw_bounding_volume(), DRAW_CONSTCOLOR, DRAW_FACE_SELECT, draw_glsl_material(), draw_mesh_object_outline(), draw_mesh_textured(), DRAW_MODIFIERS_PREVIEW, DRAW_PICKING, DerivedMesh::drawEdges, DerivedMesh::drawFacesGLSL, DerivedMesh::drawFacesSolid, Mesh::drawflag, DerivedMesh::drawLooseEdges, DerivedMesh::drawMappedFaces, drawSelectedVertices(), View3D::drawtype, DerivedMesh::drawVerts, Object::dtx, Base::flag, View3D::flag, Mesh::flag, Object::flag, View3D::flag2, Paint::flags, G, G_PICKSEL, DerivedMesh::getNumEdges, DerivedMesh::getNumTessFaces, give_current_material(), GPU_disable_material(), GPU_enable_material(), GPU_end_object_materials(), interp_v3_v3v3(), MA_TYPE_HALO, Material::material_type, ME_ALLEDGES, ME_TWOSIDED, mesh_get_derived_final(), Mesh::mloopcol, Object::mode, modifiers_isPreview(), Mesh::mpoly, NULL, OB_BOUNDBOX, OB_DRAWWIRE, OB_FROMGROUP, OB_MODE_PARTICLE_EDIT, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, OB_NEG_SCALE, OB_PAINT, OB_SOLID, OB_WIRE, OBACT, OBDRAW_WIRE_OFF, OBDRAW_WIRE_ON, OBDRAW_WIRE_ON_DEPTH, Base::object, p, paint_facesel_test(), PAINT_FAST_NAVIGATE, paint_get_active(), paint_vertsel_test(), SculptSession::partial_redraw, DerivedMesh::release, RegionView3D::rflag, RGN_DRAW_PARTIAL, RV3D_NAVIGATING, Object::sculpt, sculpt_get_redraw_planes(), SELECT, TH_ACTIVE, TH_BACK, TH_GROUP, TH_GROUP_ACTIVE, TH_SELECT, TH_VERTEX_SIZE, TH_WIRE, Object::transflag, UI_GetThemeColor3fv(), UI_GetThemeValuef(), UI_ThemeColor(), UI_ThemeColorShade(), V3D_RENDER_OVERRIDE, and V3D_SELECT_OUTLINE.
Referenced by draw_mesh_object().
static int draw_mesh_object (Scene * scene, ARegion * ar, View3D * v3d, RegionView3D * rv3d, Base * base, int dt, int flag) [static]
Definition at line 3535 of file drawobject.c.
References add_view3d_after(), View3D::afterdraw_transp, View3D::afterdraw_xray, View3D::afterdraw_xraytransp, Object::bb, Mesh::bb, check_alpha_pass(), Scene::customdata_mask, Object::data, draw_em_fancy(), draw_glsl_material(), draw_mesh_fancy(), Object::dtx, ED_view3d_boundbox_clip(), Mesh::edit_btmesh, editbmesh_get_derived_base(), editbmesh_get_derived_cage_and_final(), ListBase::first, View3D::flag2, give_current_material(), GPU_begin_object_materials(), GPU_end_object_materials(), i, MA_SHADBUF, Material::mode, Object::modifiers, NULL, OB_DRAWTRANSP, OB_DRAWXRAY, ob_get_key(), OB_SOLID, OB_WIRE, Scene::obedit, Base::object, Object::obmat, DerivedMesh::release, Object::totcol, Mesh::totpoly, Mesh::totvert, View3D::transp, V3D_RENDER_SHADOW, and View3D::xray.
Referenced by draw_object().
static void draw_mesh_object_outline (View3D * v3d, Object * ob, DerivedMesh * dm) [static]
Definition at line 3199 of file drawobject.c.
References DerivedMesh::drawEdges, DerivedMesh::drawFacesSolid, Object::dtx, FALSE, GPU_disable_material(), GPU_enable_material(), Object::mode, NULL, OB_DRAWTRANSP, OB_MODE_ALL_PAINT, TH_OUTLINE_WIDTH, View3D::transp, and UI_GetThemeValuef().
Referenced by draw_mesh_fancy(), draw_object_mesh_instance(), and drawObjectSelect().
static void draw_new_particle_system (Scene * scene, View3D * v3d, RegionView3D * rv3d, Base * base, ParticleSystem * psys, int ob_dt) [static]
Definition at line 4176 of file drawobject.c.
References add_v3_v3v3(), ParticleBillboardData::align, ParticleBillboardData::anim, ParticleSettings::bb_align, ParticleSettings::bb_anim, ParticleSettings::bb_ob, ParticleSettings::bb_offset, ParticleSettings::bb_rand_tilt, ParticleSettings::bb_size, ParticleSettings::bb_tilt, ParticleSettings::bb_vel_head, ParticleSettings::bb_vel_tail, BKE_curframe(), BLI_snprintf(), ParticleData::boid, View3D::camera, ParticleDrawData::cd, ParticleDrawData::cdata, ParticleSystem::child, ParticleSystem::childcache, CLAMP(), ParticleKey::co, ParticleCacheKey::co, ParticleCacheKey::col, ParticleSettings::color_vec_max, copy_m4_m4(), copy_v3_v3(), cpack, BoidParticle::data, ParticleData::dietime, ParticleSettings::disp, ParticleSettings::draw, ParticleSettings::draw_as, ParticleSettings::draw_col, ParticleSettings::draw_line, draw_particle(), draw_particle_arrays(), ParticleSettings::draw_size, drawcircball(), ParticleSettings::dup_group, ParticleSettings::dup_ob, ED_view3d_pixel_size(), ELEM, ELEM3, end_latt_deform(), Base::flag, Object::flag, ParticleEditSettings::flag, ParticleData::flag, ParticleSystem::flag, ParticleDrawData::flag, View3D::flag2, give_current_material(), glLoadMatrixf, glMultMatrixf, BoidData::health, i, if(), ParticleSystem::imat, Object::imat, invert_m4_m4(), ParticleSystem::lattice, len_v3(), len_v3v3(), length(), ParticleData::lifetime, ParticleBillboardData::lock, ParticleDrawData::ma_col, MEM_callocN(), MEM_freeN(), mul_m4_v3(), mul_v3_m4v3(), mul_v3_v3fl(), mult_m4_m4m4(), ParticleDrawData::nd, ParticleDrawData::ndata, normalize_v3(), NULL, ParticleSimulationData::ob, ParticleBillboardData::ob, OB_FROMDUPLI, OB_FROMGROUP, OB_WIRE, Base::object, Object::obmat, ParticleBillboardData::offset, ParticleSettings::omat, ParticleSystem::parent, PARS_NO_DISP, PARS_UNEXIST, ParticleSystem::part, PART_ABS_PATH_TIME, PART_BB_VEL, PART_DRAW_AXIS, PART_DRAW_BB, PART_DRAW_BB_LOCK, PART_DRAW_CIRC, PART_DRAW_COL_ACC, PART_DRAW_COL_MAT, PART_DRAW_COL_VEL, PART_DRAW_CROSS, PART_DRAW_DOT, PART_DRAW_GR, PART_DRAW_HEALTH, PART_DRAW_LINE, PART_DRAW_NOT, PART_DRAW_NUM, PART_DRAW_OB, PART_DRAW_PARENT, PART_DRAW_PATH, PART_DRAW_REND, PART_DRAW_SIZE, PART_DRAW_VEL, PART_HAIR, PART_PHYS_BOIDS, PART_PHYS_KEYED, PARTICLE_DRAW_DATA_UPDATED, ParticleSystem::particles, ParticleSettings::path_end, ParticleSystem::pathcache, ParticleSystem::pdd, PE_DRAW_PART, PE_settings(), ParticleSettings::phystype, ParticleData::prev_state, ParticleSimulationData::psmd, ParticleSimulationData::psys, psys_check_enabled(), psys_count_keyed_targets(), PSYS_DRAWING, PSYS_FRAND, psys_free_pdd(), psys_get_child_size(), psys_get_child_time(), psys_get_current(), psys_get_lattice(), psys_get_modifier(), psys_get_particle_on_path(), psys_get_particle_state(), psys_get_timestep(), psys_in_edit_mode(), PSYS_KEYED, psys_make_temp_pointcache(), Material::r, ParticleSettings::randlength, ParticleSettings::ren_as, rgb_float_to_uchar(), ParticleSimulationData::scene, SELECT, setlinestyle(), ParticleData::size, ParticleBillboardData::size, state, ParticleData::state, ParticleCacheKey::steps, TH_ACTIVE, TH_WIRE, ParticleBillboardData::tilt, ParticleKey::time, ParticleBillboardData::time, ParticleData::time, ParticleDrawData::tot_vec_size, ParticleSystem::totchild, ParticleSystem::totkeyed, ParticleSystem::totpart, ParticleDrawData::totpoint, ParticleSettings::trail_count, ParticleSettings::type, UI_ThemeColor(), V3D_CACHE_TEXT_ASCII, V3D_CACHE_TEXT_WORLDSPACE, V3D_RENDER_OVERRIDE, ParticleDrawData::vd, ParticleDrawData::vdata, ParticleDrawData::ved, ParticleDrawData::vedata, ParticleCacheKey::vel, ParticleKey::vel, view3d_cached_text_draw_add(), RegionView3D::viewinv, RegionView3D::viewmat, weight_to_rgb(), and View3D::zbuf.
Referenced by draw_object().
void draw_object (Scene * scene, ARegion * ar, View3D * v3d, Base * base, int flag)
Definition at line 6371 of file drawobject.c.
References Curve::actbox, ACTIVE, add_view3d_after(), View3D::afterdraw_xray, Object::avs, BA_WAS_SEL, Scene::basact, Object::bb, Curve::bb, bglBegin(), bglEnd(), bglVertex3fv(), BKE_curframe(), BKE_font_getselection(), Object::boundtype, bObjectSolverConstraint::camera, bFollowTrackConstraint::camera, View3D::camera, Scene::camera, SmokeModifierData::coll, Object::collision_boundtype, colortab, CONSTRAINT_DRAW_PIVOT, CONSTRAINT_EXPAND, constraint_get_typeinfo(), CONSTRAINT_OBTYPE_OBJECT, CONSTRAINT_TYPE_FOLLOWTRACK, CONSTRAINT_TYPE_OBJECTSOLVER, CONSTRAINT_TYPE_RIGIDBODYJOINT, Object::constraints, constraints_clear_evalob(), constraints_make_evalob(), copy_m3_m3(), copy_v3_v3(), cpack, CU_FAST, curve_editnurbs(), Object::data, data, bConstraint::data, DESELECT, Object::disp, SmokeModifierData::domain, draw_armature(), draw_bounding_volume(), DRAW_CONSTCOLOR, draw_empty_image(), draw_forcefield(), draw_hooks(), draw_mesh_object(), draw_motion_path_instance(), draw_motion_paths_cleanup(), draw_motion_paths_init(), draw_new_particle_system(), DRAW_PICKING, draw_ptcache_edit(), DRAW_SCENESET, draw_textcurs(), draw_update_ptcache_edit(), draw_volume(), drawaxes(), drawcamera(), drawcentercircle(), drawcircball(), drawDispList(), drawlamp(), drawlattice(), drawmball(), drawnurb(), drawObjectSelect(), drawRBpivot(), drawspeaker(), drawtexspace(), View3D::drawtype, drawWireExtra(), Object::dt, Object::dtx, SmokeDomainSettings::dx, SmokeDomainSettings::dx_wt, ED_view3d_boundbox_clip(), ED_view3d_init_mats_rv3d_gl(), MetaBall::editelems, Curve::editfont, Curve::editnurb, ELEM, ELEM3, eModifierType_Smoke, Object::empty_drawsize, Object::empty_drawtype, FALSE, ListBase::first, bConstraint::flag, Curve::flag, bRigidBodyJointConstraint::flag, Base::flag, View3D::flag, Object::flag, View3D::flag2, SmokeDomainSettings::fluid, bConstraintTypeInfo::flush_constraint_targets, PartDeflect::forcefield, free_old_images(), Curve::fsize, G, G_RENDER_OGL, G_TRANSFORM_OBJ, Object::gameflag, bConstraintTypeInfo::get_constraint_targets, bConstraintTypeInfo::get_target_matrix, glLoadMatrixf, glMultMatrixf, GPU_create_smoke(), GPU_disable_material(), GPU_enable_material(), GPU_free_smoke(), TextBox::h, SelBox::h, i, Object::id, if(), Object::imat, Object::inertia, invert_m4_m4(), Object::lay, View3D::lay, SoftBody::lcom, ID::lib, Curve::linedist, Curve::lines, Curve::linewidth, SoftBody::lrot, SoftBody::lscale, makeDispListCurveTypes(), bConstraintTarget::matrix, MIN2, MOD_SMOKE_TYPE_COLL, MOD_SMOKE_VIEW_SHOWBIG, Object::mode, modifiers_findByType(), Object::mpath, mul_m3_m3m3(), ID::name, bConstraint::next, ParticleSystem::next, bConstraintTarget::next, NULL, SmokeCollSettings::numpoints, OB_ARMATURE, OB_ARROWS, OB_AXIS, OB_BOUND_SPHERE, OB_BOUNDBOX, OB_BOUNDS, OB_CAMERA, OB_CURVE, ob_draw_RE_motion(), OB_DRAWNAME, OB_DRAWTRANSP, OB_DRAWWIRE, OB_DRAWXRAY, OB_DYNAMIC, OB_EMPTY, OB_EMPTY_IMAGE, OB_FONT, OB_FROMDUPLI, OB_FROMGROUP, OB_LAMP, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_EDIT, OB_MODE_PARTICLE_EDIT, OB_MODE_POSE, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, OB_PAINT, OB_RENDER, OB_RESTRICT_RENDER, OB_RESTRICT_VIEW, OB_SOLID, OB_SPEAKER, OB_SURF, OB_TEXSPACE, OB_WIRE, OBACT, Scene::obedit, Base::object, Object::obmat, Object::orig, SmokeDomainSettings::p0, SmokeDomainSettings::p1, Object::parent, Object::particlesystem, Object::pd, PE_create_current(), RegionView3D::persp, SmokeCollSettings::points, project_short(), PTCacheEdit::psys, ARegion::regiondata, SmokeDomainSettings::res, SmokeDomainSettings::res_wt, Object::restrictflag, rgb_float_to_uchar(), RV3D_CAMOB, SBSO_ESTIMATEIPO, Curve::selboxes, SELECT, set_inverted_drawing(), setlinestyle(), smoke_get_density(), smoke_get_index(), Object::soft, SoftBody::solverflags, Base::sx, Curve::tb, SmokeDomainSettings::tex, SmokeDomainSettings::tex_shadow, EditFont::textcurs, TH_ACTIVE, TH_CAMERA, TH_EMPTY, TH_GRID, TH_GROUP, TH_GROUP_ACTIVE, TH_LAMP, TH_SELECT, TH_SPEAKER, TH_TRANSFORM, TH_WIRE, Curve::totbox, View3D::transp, bConstraint::type, Object::type, SmokeModifierData::type, bConstraintTypeInfo::type, UI_GetThemeColor3ubv(), UI_make_axis_color(), UI_ThemeColor(), UI_ThemeColorShade(), unit_m4(), ID::us, V3D_DRAW_CENTERS, V3D_HIDE_HELPLINES, V3D_RENDER_OVERRIDE, V3D_SELECT_OUTLINE, view3d_cached_text_draw_add(), view3d_cached_text_draw_begin(), view3d_cached_text_draw_end(), RegionView3D::viewmat, RegionView3D::viewmatob, SmokeDomainSettings::viewsettings, SelBox::w, TextBox::w, SmokeDomainSettings::wt, TextBox::x, SelBox::x, Curve::xof, View3D::xray, TextBox::y, SelBox::y, Curve::yof, and View3D::zbuf.
Referenced by draw_depth(), draw_dupli_objects_color(), ED_view3d_draw_offscreen(), view3d_draw_transp(), view3d_draw_xray(), view3d_draw_xraytransp(), view3d_main_area_draw_objects(), and view3d_opengl_select().
void draw_object_backbufsel (Scene * scene, View3D * v3d, RegionView3D * rv3d, Object * ob)
Definition at line 7318 of file drawobject.c.
References bbs_mesh_solid(), bbs_mesh_solid_EM(), bbs_mesh_solid_hide2__setDrawOpts(), bbs_mesh_verts(), bbs_mesh_wire(), bbs_obmode_mesh_verts(), bglPolygonOffset(), BMEditMesh::bm, bm_solidoffs, bm_vertoffs, bm_wireoffs, CD_MASK_BAREMESH, Scene::customdata_mask, Object::data, RegionView3D::dist, DerivedMesh::drawMappedFaces, EDBM_index_arrays_free(), EDBM_index_arrays_init(), Mesh::edit_btmesh, editbmesh_get_derived_cage(), Mesh::editflag, G, G_TRANSFORM_EDIT, glLoadMatrixf, glMultMatrixf, GPU_enable_material(), ME_EDIT_VERT_SEL, mesh_get_derived_final(), Object::mode, NULL, OB_CURVE, OB_MESH, OB_MODE_EDIT, OB_MODE_WEIGHT_PAINT, OB_SURF, Object::obmat, DerivedMesh::release, SCE_SELECT_FACE, SCE_SELECT_VERTEX, ToolSettings::selectmode, Scene::toolsettings, BMesh::totedge, BMesh::totface, BMesh::totvert, Mesh::totvert, Object::type, and RegionView3D::viewmat.
Referenced by backdrawview3d().
void draw_object_instance (Scene * scene, View3D * v3d, RegionView3D * rv3d, Object * ob, int dt, int outline)
Definition at line 7447 of file drawobject.c.
References draw_empty_image(), draw_object_mesh_instance(), drawaxes(), Object::empty_drawsize, Object::empty_drawtype, NULL, OB_EMPTY, OB_EMPTY_IMAGE, OB_MESH, and Object::type.
Referenced by draw_custom_bone().
static void draw_object_mesh_instance (Scene * scene, View3D * v3d, RegionView3D * rv3d, Object * ob, int dt, int outline) [static]
Definition at line 7398 of file drawobject.c.
References CD_MASK_BAREMESH, Object::data, draw_glsl_material(), draw_mesh_object_outline(), DerivedMesh::drawEdges, DerivedMesh::drawFacesSolid, Mesh::edit_btmesh, editbmesh_get_derived_base(), GPU_begin_object_materials(), GPU_enable_material(), GPU_end_object_materials(), mesh_get_derived_final(), Object::mode, NULL, OB_MODE_EDIT, OB_NEG_SCALE, OB_WIRE, DerivedMesh::release, TH_BONE_SOLID, Object::transflag, and UI_ThemeColor().
Referenced by draw_object_instance().
static void draw_particle (ParticleKey * state, int draw_as, short draw, float pixsize, float imat[4][4], float * draw_line, ParticleBillboardData * bb, ParticleDrawData * pdd) [static]
Definition at line 4020 of file drawobject.c.
References add_v3_v3(), add_v3_v3v3(), ParticleDrawData::cd, ParticleKey::co, copy_v3_v3(), drawcircball(), len_v3(), ParticleDrawData::ma_col, madd_v3_v3v3fl(), mul_qt_v3(), mul_v3_fl(), ParticleDrawData::nd, normalize_v3(), NULL, PART_DRAW_AXIS, PART_DRAW_BB, PART_DRAW_CIRC, PART_DRAW_CROSS, PART_DRAW_DOT, PART_DRAW_LINE, PART_DRAW_VEL_LENGTH, psys_make_billboard(), ParticleKey::rot, sub_v3_v3v3(), ParticleDrawData::vd, ParticleBillboardData::vec, ParticleKey::vel, and ParticleBillboardData::vel.
Referenced by draw_new_particle_system().
static void draw_particle_arrays (int draw_as, int totpoint, int ob_dt, int select) [static]
Definition at line 3996 of file drawobject.c.
References OB_WIRE, PART_DRAW_AXIS, PART_DRAW_BB, PART_DRAW_CROSS, and PART_DRAW_LINE.
Referenced by draw_new_particle_system().
static void draw_ptcache_edit (Scene * scene, View3D * v3d, PTCacheEdit * edit) [static]
Definition at line 4819 of file drawobject.c.
References ParticleEditSettings::brushtype, CFRA, PTCacheEditKey::co, ParticleCacheKey::co, ParticleCacheKey::col, copy_v3_v3(), fabsf, ParticleEditSettings::fade_frames, View3D::flag, PTCacheEditPoint::flag, ParticleEditSettings::flag, PTCacheEditKey::flag, i, PTCacheEditPoint::keys, MEM_callocN(), MEM_freeN(), NULL, PTCacheEdit::pathcache, PE_BRUSH_WEIGHT, PE_FADE_TIME, PE_hide_keys_time(), PE_settings(), PEK_SELECT, PEK_USE_WCO, PEP_HIDE, PTCacheEdit::points, SCE_SELECT_END, SCE_SELECT_PATH, SCE_SELECT_POINT, ParticleEditSettings::selectmode, ParticleCacheKey::steps, TH_VERTEX, TH_VERTEX_SELECT, TH_VERTEX_SIZE, PTCacheEditKey::time, PTCacheEditPoint::totkey, PTCacheEdit::totpoint, UI_GetThemeColor3fv(), UI_GetThemeValuef(), V3D_ZBUF_SELECT, PTCacheEditKey::world_co, and View3D::zbuf.
Referenced by draw_object().
static void draw_spot_cone (Lamp * la, float x, float z) [static]
Definition at line 1120 of file drawobject.c.
References angle(), cosf, fabs(), LA_SQUARE, M_PI, Lamp::mode, and sinf.
Referenced by draw_transp_spot_volume().
static void draw_textcurs (float textcurs[4][2]) [static]
Definition at line 5667 of file drawobject.c.
References cpack, and set_inverted_drawing().
Referenced by draw_object().
static void draw_transp_spot_volume (Lamp * la, float x, float z) [static]
Definition at line 1147 of file drawobject.c.
References draw_spot_cone().
Referenced by drawlamp().
static void draw_update_ptcache_edit (Scene * scene, Object * ob, PTCacheEdit * edit) [static]
Definition at line 4809 of file drawobject.c.
References CFRA, ParticleSystem::flag, NULL, PTCacheEdit::pathcache, PE_update_object(), PTCacheEdit::psys, psys_cache_edit_paths(), and PSYS_HAIR_UPDATED.
Referenced by draw_object().
static void draw_viewport_object_reconstruction (Scene * scene, Base * base, View3D * v3d, MovieClip * clip, MovieTrackingObject * tracking_object, int flag, int * global_track_index, int draw_selected) [static]
Definition at line 1533 of file drawobject.c.
References BASACT, BKE_get_tracking_mat(), BKE_tracking_get_interpolated_camera(), BKE_tracking_object_reconstruction(), BKE_tracking_object_tracks(), View3D::bundle_drawtype, MovieTrackingTrack::bundle_pos, View3D::bundle_size, MovieTrackingReconstruction::cameras, MovieTrackingReconstruction::camnr, RenderData::cfra, MovieTrackingTrack::color, draw_bundle_sphere(), DRAW_PICKING, drawaxes(), View3D::drawtype, ListBase::first, MovieTrackingObject::flag, MovieTrackingTrack::flag, View3D::flag2, glMultMatrixf, invert_m4_m4(), MovieReconstructedCamera::mat, mul_v3_m4v3(), MovieTrackingTrack::name, MovieTrackingTrack::next, OB_EMPTY_SPHERE, OB_WIRE, Base::object, Object::obmat, Scene::r, Base::selcol, TH_ACTIVE, TH_BUNDLE_SOLID, TH_CAMERA_PATH, TH_SELECT, TH_TEXT, TH_WIRE, TRACK_CUSTOMCOLOR, TRACK_HAS_BUNDLE, TRACK_SELECTED, MovieClip::tracking, TRACKING_OBJECT_CAMERA, UI_GetThemeColor4ubv(), UI_ThemeColor(), V3D_CACHE_TEXT_GLOBALSPACE, V3D_SHOW_BUNDLENAME, V3D_SHOW_CAMERAPATH, and view3d_cached_text_draw_add().
Referenced by draw_viewport_reconstruction().
static void draw_viewport_reconstruction (Scene * scene, Base * base, View3D * v3d, MovieClip * clip, int flag, int draw_selected) [static]
Definition at line 1688 of file drawobject.c.
References DRAW_PICKING, draw_viewport_object_reconstruction(), ListBase::first, View3D::flag2, MovieTrackingObject::next, MovieTracking::objects, Base::selcol, MovieClip::tracking, V3D_RENDER_OVERRIDE, and V3D_SHOW_RECONSTRUCTION.
Referenced by drawcamera().
static void draw_xyz_wire (const float c[3], float size, int axis) [static]
Definition at line 443 of file drawobject.c.
References add_v3_v3(), add_v3_v3v3(), copy_v3_v3(), mul_v3_fl(), sub_v3_v3(), and sub_v3_v3v3().
Referenced by drawaxes().
void drawaxes (float size, char drawtype)
Definition at line 529 of file drawobject.c.
References draw_empty_cone(), draw_empty_sphere(), draw_xyz_wire(), drawcircle_size(), drawcube_size(), OB_ARROWS, OB_CIRCLE, OB_CUBE, OB_EMPTY_CONE, OB_EMPTY_SPHERE, OB_PLAINAXES, OB_SINGLE_ARROW, and size().
Referenced by draw_ebones(), draw_object(), draw_object_instance(), draw_pose_bones(), and draw_viewport_object_reconstruction().
static void drawcamera (Scene * scene, View3D * v3d, RegionView3D * rv3d, Base * base, int flag) [static]
Definition at line 1729 of file drawobject.c.
References CAM_SHOWLIMITS, CAM_SHOWMIST, View3D::camera, camera_view_frame_ex(), Camera::clipend, Camera::clipsta, copy_m4_m4(), draw_focus_cross(), draw_limit_line(), draw_viewport_reconstruction(), Camera::drawsize, FALSE, Camera::flag, G, G_PICKSEL, glLoadMatrixf, glMultMatrixf, i, len_v3(), World::mistdist, World::miststa, normalize_m4(), Base::object, object_camera_dof_distance(), object_get_movieclip(), RegionView3D::persp, RV3D_CAMOB, TRUE, view3d_camera_border_hack_col, view3d_camera_border_hack_test, RegionView3D::viewmat, Scene::world, and zero_v3().
Referenced by draw_object().
static void drawcentercircle (View3D * v3d, RegionView3D * rv3d, const float co[3], int selstate, int special_color) [static]
Definition at line 758 of file drawobject.c.
References ACTIVE, circball_array_fill(), CIRCLE_RESOL, DESELECT, ED_view3d_pixel_size(), if(), SELECT, size(), TH_ACTIVE, TH_SELECT, TH_TRANSFORM, TH_WIRE, UI_ThemeColorShadeAlpha(), RegionView3D::viewinv, and View3D::zbuf.
Referenced by draw_object().
void drawcircball (int mode, const float cent[3], float rad, float tmat[][4])
Definition at line 745 of file drawobject.c.
References circball_array_fill(), and CIRCLE_RESOL.
Referenced by draw_forcefield(), draw_manipulator_rotate(), draw_manipulator_rotate_cyl(), draw_manipulator_scale(), draw_manipulator_translate(), draw_new_particle_system(), draw_object(), draw_particle(), draw_sphere_bone_wire(), drawcone(), drawlamp(), drawmball(), drawPropCircle(), drawSnapping(), and drawtube().
static void drawcircle_size (float size) [static]
Definition at line 5750 of file drawobject.c.
References CIRCLE_RESOL, cosval, degrees(), and sinval.
Referenced by drawaxes().
static void drawcone (const float vec[3], float radius, float height, float tmat[][4]) [static]
Definition at line 5792 of file drawobject.c.
References copy_v3_v3(), and drawcircball().
Referenced by draw_forcefield(), and drawlamp().
static void drawcube (void) [static]
Definition at line 949 of file drawobject.c.
Referenced by draw_bounding_volume().
static void drawcube_size (float size) [static]
Definition at line 974 of file drawobject.c.
Referenced by drawaxes().
static int drawCurveDerivedMesh (Scene * scene, View3D * v3d, RegionView3D * rv3d, Base * base, int dt) [static]
Definition at line 3844 of file drawobject.c.
References Object::derivedFinal, draw_glsl_material(), drawCurveDMWired(), DerivedMesh::drawFacesGLSL, DerivedMesh::drawFacesSolid, View3D::drawtype, View3D::flag2, DerivedMesh::getNumTessFaces, GPU_begin_object_materials(), GPU_enable_material(), GPU_end_object_materials(), NULL, OB_SOLID, OB_WIRE, Base::object, and V3D_RENDER_OVERRIDE.
Referenced by drawDispList().
static void drawCurveDMWired (Object * ob) [static]
Definition at line 3837 of file drawobject.c.
References Object::derivedFinal, and DerivedMesh::drawEdges.
Referenced by drawCurveDerivedMesh(), and drawWireExtra().
static int drawDispList (Scene * scene, View3D * v3d, RegionView3D * rv3d, Base * base, int dt) [static]
Definition at line 3876 of file drawobject.c.
References addnormalsDispList(), Curve::bevobj, cpack, Object::data, Object::disp, displist_has_faces(), draw_glsl_material(), drawCurveDerivedMesh(), drawDispListsolid(), drawDispListwire(), Curve::editnurb, Curve::ext1, Curve::ext2, ListBase::first, View3D::flag2, GPU_begin_object_materials(), GPU_end_object_materials(), is_basis_mball(), makeDispListMBall(), DispList::nors, NULL, OB_CURVE, OB_FONT, OB_MBALL, OB_SURF, OB_WIRE, Base::object, Curve::taperobj, Object::type, and V3D_RENDER_OVERRIDE.
Referenced by draw_object(), drawmball(), and drawnurb().
static void drawDispListsolid (ListBase * lb, Object * ob, int glsl) [static]
Definition at line 3717 of file drawobject.c.
References DispList::col, CU_SMOOTH, data, DL_INDEX3, DL_INDEX4, DL_POLY, DL_SEGM, DL_SURF, ListBase::first, GPU_enable_material(), DispList::index, DispList::next, DispList::nors, DispList::nr, NULL, OB_MBALL, OB_NEG_SCALE, OB_SURF, DispList::parts, DispList::rt, DispList::totindex, Object::transflag, DispList::type, Object::type, and DispList::verts.
Referenced by drawDispList().
static int drawDispListwire (ListBase * dlbase) [static]
Definition at line 3626 of file drawobject.c.
References data, DL_CYCL_U, DL_CYCL_V, DL_INDEX3, DL_INDEX4, DL_POLY, DL_SEGM, DL_SURF, ListBase::first, DispList::flag, DispList::index, DispList::next, DispList::nr, NULL, DispList::parts, DispList::type, and DispList::verts.
Referenced by drawDispList(), drawObjectSelect(), and drawWireExtra().
static void drawlamp (Scene * scene, View3D * v3d, RegionView3D * rv3d, Base * base, int dt, int flag) [static]
Definition at line 1177 of file drawobject.c.
References add_view3d_after(), View3D::afterdraw_transp, Lamp::area_shape, Lamp::area_size, Lamp::area_sizey, View3D::camera, circ(), Lamp::clipsta, copy_m4_m4(), copy_v3_v3(), cosf, Object::data, Lamp::dist, draw_transp_spot_volume(), drawcircball(), drawcone(), drawshadbuflimits(), ED_view3d_pixel_size(), ELEM, fabs(), fabsf, FALSE, fdrawbox(), Base::flag, Object::flag, G, G_PICKSEL, glLoadMatrixf, Object::id, interp_v3_v3v3(), LA_AREA, LA_AREA_RECT, LA_AREA_SQUARE, LA_HEMI, LA_LOCAL, LA_SHAD_BUF, LA_SHAD_RAY, LA_SHOW_CONE, LA_SPHERE, LA_SPOT, LA_SQUARE, LA_SUN, LA_YF_PHOTON, M_PI, Lamp::mode, mul(), mul_m3_v3(), mul_v3_fl(), mul_v3_v3fl(), normalize_v3(), OB_FROMDUPLI, OB_WIRE, OBACT, Base::object, Object::obmat, RegionView3D::persmat, RegionView3D::persp, pow(), RV3D_CAMOB, SELECT, setlinestyle(), Lamp::spotblend, Lamp::spotsize, spotvolume(), sqrtf, TH_LAMP, View3D::transp, Lamp::type, UI_GetThemeColor4ubv(), ID::us, vec_rot_to_mat3(), RegionView3D::viewinv, RegionView3D::viewmat, and zero_v3().
Referenced by draw_object().
static void drawlattice (Scene * scene, View3D * v3d, Object * ob) [static]
Definition at line 1961 of file drawobject.c.
References Object::actdef, cpack, Object::data, Object::defbase, Object::disp, DL_VERTS, drawlattice__point(), Lattice::dvert, Lattice::editlatt, find_displist(), ListBase::first, Lattice::flag, EditLatt::latt, lattice_calc_modifiers(), lattice_draw_verts(), LT_OUTSIDE, NULL, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, and View3D::zbuf.
Referenced by draw_object().
static void drawlattice__point (Lattice * lt, DispList * dl, int u, int v, int w, int use_wcol) [static]
Definition at line 1939 of file drawobject.c.
References Lattice::def, defvert_find_index(), Lattice::dvert, Lattice::pntsu, Lattice::pntsv, BPoint::vec, DispList::verts, MDeformWeight::weight, and weight_to_rgb().
Referenced by drawlattice().
static int drawmball (Scene * scene, View3D * v3d, RegionView3D * rv3d, Base * base, int dt) [static]
Definition at line 5813 of file drawobject.c.
References atanf, cpack, Object::data, drawcircball(), drawDispList(), MetaBall::editelems, MetaBall::elems, ListBase::first, Base::flag, Object::flag, MetaElem::flag, View3D::flag2, G, G_PICKSEL, invert_m4_m4(), M_PI_2, MB_SCALE_RAD, MetaElem::next, normalize_v3(), NULL, OB_FROMDUPLI, OBACT, Base::object, MetaElem::rad, MetaElem::s, MetaElem::selcol1, MetaElem::selcol2, SELECT, TH_ACTIVE, TH_SELECT, TH_WIRE, UI_ThemeColor(), V3D_RENDER_OVERRIDE, RegionView3D::viewmatob, and MetaElem::x.
Referenced by draw_object().
static void drawnurb (Scene * scene, View3D * v3d, RegionView3D * rv3d, Base * base, Nurb * nurb, int dt) [static]
Definition at line 5489 of file drawobject.c.
References Curve::actnu, add_v3_v3(), Curve::bev, CU_3D, CU_BEZIER, CU_HIDE_HANDLES, CU_HIDE_NORMALS, Object::data, BevPoint::dir, draw_editnurb(), drawDispList(), Curve::drawflag, ListBase::first, Curve::flag, Curve::lastsel, madd_v3_v3fl(), mul_qt_v3(), BevList::next, Nurb::next, ToolSettings::normalsize, BevList::nr, NULL, Base::object, BevPoint::quat, BevPoint::radius, Nurb::resolu, tekenhandlesN(), tekenhandlesN_active(), tekenvertsN(), TH_WIRE, Scene::toolsettings, Nurb::type, UI_ThemeColor(), BevPoint::vec, and View3D::zbuf.
Referenced by draw_object().
static void drawObjectSelect (Scene * scene, View3D * v3d, ARegion * ar, Base * base) [static]
Definition at line 6202 of file drawobject.c.
References Scene::basact, Object::bb, Curve::bb, Object::data, Object::derivedFinal, Object::disp, displist_has_faces(), draw_armature(), draw_mesh_object_outline(), drawDispListwire(), ED_view3d_boundbox_clip(), ELEM3, FALSE, Base::flag, DerivedMesh::getNumTessFaces, is_basis_mball(), Object::mode, OB_ARMATURE, OB_CURVE, OB_FONT, OB_FROMDUPLI, OB_MBALL, OB_MODE_POSE, OB_SURF, OB_WIRE, Base::object, Object::obmat, ARegion::regiondata, TRUE, and Object::type.
Referenced by draw_object().
static void drawRBpivot (bRigidBodyJointConstraint * data) [static]
Definition at line 6333 of file drawobject.c.
References add_v3_v3(), bRigidBodyJointConstraint::axX, copy_v3_v3(), eul_to_mat4(), mul_m4_v3(), bRigidBodyJointConstraint::pivX, rgb_float_to_uchar(), setlinestyle(), V3D_CACHE_TEXT_ASCII, and view3d_cached_text_draw_add().
Referenced by draw_object().
static void drawSelectedVertices (DerivedMesh * dm, Mesh * me) [static]
Definition at line 2096 of file drawobject.c.
References drawSelectedVertices__mapFunc(), DerivedMesh::foreachMappedVert, and Mesh::mvert.
Referenced by draw_mesh_fancy().
static void drawSelectedVertices__mapFunc (void * userData, int index, const float co[3], const float UNUSEDno_f[3], const short UNUSEDno_s[3]) [static]
Definition at line 2076 of file drawobject.c.
References MVert::flag, ME_HIDE, and SELECT.
Referenced by drawSelectedVertices().
static void drawshadbuflimits (Lamp * la, float mat[][4]) [static]
Definition at line 1030 of file drawobject.c.
References bglBegin(), bglEnd(), bglVertex3fv(), Lamp::clipend, Lamp::clipsta, madd_v3_v3v3fl(), negate_v3_v3(), and normalize_v3().
Referenced by drawlamp().
static void drawspeaker (Scene * UNUSEDscene, View3D * UNUSEDv3d, RegionView3D * UNUSEDrv3d, Object * UNUSEDob, int UNUSEDflag) [static]
Definition at line 1846 of file drawobject.c.
References cosf, i, M_PI, and sinf.
Referenced by draw_object().
static void drawspiral (const float cent[3], float rad, float tmat[][4], int start) [static]
Definition at line 5681 of file drawobject.c.
References CIRCLE_RESOL, copy_v3_v3(), cosval, FALSE, inverse(), mul_v3_v3fl(), sinval, and TRUE.
Referenced by draw_forcefield().
static void drawtexspace (Object * ob) [static]
Definition at line 6166 of file drawobject.c.
References copy_v3_v3(), Object::data, draw_box(), ELEM3, Curve::loc, MetaBall::loc, mesh_get_texspace(), NULL, OB_CURVE, OB_FONT, OB_MBALL, OB_MESH, OB_SURF, setlinestyle(), Curve::size, MetaBall::size, and Object::type.
Referenced by draw_object().
static void drawtube (const float vec[3], float radius, float height, float tmat[][4]) [static]
Definition at line 5770 of file drawobject.c.
References copy_v3_v3(), and drawcircball().
Referenced by draw_forcefield().
static void drawWireExtra (Scene * scene, RegionView3D * rv3d, Object * ob) [static]
Definition at line 6248 of file drawobject.c.
References Object::bb, Curve::bb, bglPolygonOffset(), Object::data, Object::derivedFinal, Object::disp, RegionView3D::dist, drawCurveDMWired(), drawDispListwire(), Object::dtx, ED_view3d_boundbox_clip(), ELEM3, Object::flag, is_basis_mball(), OB_CURVE, OB_DRAWWIRE, OB_FONT, OB_FROMGROUP, OB_MBALL, OB_SURF, OBACT, Scene::obedit, Object::obmat, SELECT, TH_ACTIVE, TH_GROUP, TH_GROUP_ACTIVE, TH_SELECT, TH_WIRE, Object::type, UI_ThemeColor(), and UI_ThemeColorShade().
Referenced by draw_object().
static void editnurb_draw_active_nurbs (Nurb * nu) [static]
Definition at line 5328 of file drawobject.c.
References Nurb::bp, BPoint::hide, Nurb::pntsu, Nurb::pntsv, TH_ACTIVE_SPLINE, UI_ThemeColor(), and BPoint::vec.
Referenced by draw_editnurb().
static void editnurb_draw_active_poly (Nurb * nu) [static]
Definition at line 5304 of file drawobject.c.
References Nurb::bp, Nurb::flagu, Nurb::pntsu, Nurb::pntsv, TH_ACTIVE_SPLINE, UI_ThemeColor(), and BPoint::vec.
Referenced by draw_editnurb().
static void lattice_draw_verts (Lattice * lt, DispList * dl, short sel) [static]
Definition at line 1887 of file drawobject.c.
References bglBegin(), bglEnd(), bglVertex3fv(), co, Lattice::def, Lattice::flag, LT_OUTSIDE, NULL, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, SELECT, TH_VERTEX, TH_VERTEX_SELECT, TH_VERTEX_SIZE, UI_GetThemeValuef(), UI_ThemeColor(), and DispList::verts.
Referenced by drawlattice().
void lattice_foreachScreenVert (ViewContext * vc, void(*)(void *userData, BPoint *bp, int x, int y) func, void * userData)
Definition at line 1918 of file drawobject.c.
References ViewContext::ar, co, Object::data, Lattice::def, Object::disp, DL_VERTS, ED_view3d_clipping_local(), Lattice::editlatt, find_displist(), i, IS_CLIPPED, EditLatt::latt, N, NULL, ViewContext::obedit, Object::obmat, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, ViewContext::rv3d, TRUE, DispList::verts, and view3d_project_short_clip().
void mesh_foreachScreenEdge (ViewContext * vc, void(*)(void *userData, BMEdge *eed, int x0, int y0, int x1, int y1, int index) func, void * userData, eV3DClipTest clipVerts)
Definition at line 2138 of file drawobject.c.
References ViewContext::ar, CD_MASK_BAREMESH, foreachScreenEdge_userData::clipVerts, data, ED_view3d_clipping_local(), EDBM_index_arrays_free(), EDBM_index_arrays_init(), editbmesh_get_derived_cage(), ViewContext::em, DerivedMesh::foreachMappedEdge, foreachScreenEdge_userData::func, mesh_foreachScreenEdge__mapFunc(), ViewContext::obedit, Object::obmat, DerivedMesh::release, ViewContext::rv3d, ViewContext::scene, foreachScreenEdge_userData::userData, V3D_CLIP_TEST_OFF, foreachScreenEdge_userData::vc, foreachScreenEdge_userData::win_rect, ARegion::winx, ARegion::winy, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
static void mesh_foreachScreenEdge__mapFunc (void * userData, int index, const float v0co[3], const float v1co[3]) [static]
Definition at line 2103 of file drawobject.c.
References ViewContext::ar, BLI_segment_in_rcti(), BM_elem_flag_test, BM_ELEM_HIDDEN, foreachScreenEdge_userData::clipVerts, data, EDBM_edge_at_index(), ViewContext::em, foreachScreenEdge_userData::func, mul_v3_m4v3(), ViewContext::obedit, Object::obmat, project_short_noclip(), TRUE, foreachScreenEdge_userData::userData, V3D_CLIP_TEST_REGION, V3D_CLIP_TEST_RV3D_CLIPPING, foreachScreenEdge_userData::vc, view3d_project_short_clip(), and foreachScreenEdge_userData::win_rect.
Referenced by mesh_foreachScreenEdge().
void mesh_foreachScreenFace (ViewContext * vc, void(*)(void *userData, BMFace *efa, int x, int y, int index) func, void * userData)
Definition at line 2185 of file drawobject.c.
References CD_MASK_BAREMESH, data, ED_view3d_clipping_local(), EDBM_index_arrays_free(), EDBM_index_arrays_init(), editbmesh_get_derived_cage(), ViewContext::em, DerivedMesh::foreachMappedFaceCenter, foreachScreenFace_userData::func, mesh_foreachScreenFace__mapFunc(), ViewContext::obedit, Object::obmat, DerivedMesh::release, ViewContext::rv3d, ViewContext::scene, foreachScreenFace_userData::userData, and foreachScreenFace_userData::vc.
static void mesh_foreachScreenFace__mapFunc (void * userData, int index, const float cent[3], const float UNUSEDno[3]) [static]
Definition at line 2167 of file drawobject.c.
References ViewContext::ar, BM_elem_flag_test, BM_ELEM_HIDDEN, data, EDBM_face_at_index(), ViewContext::em, foreachScreenFace_userData::func, IS_CLIPPED, mul_v3_m4v3(), ViewContext::obedit, Object::obmat, project_short(), foreachScreenFace_userData::userData, and foreachScreenFace_userData::vc.
Referenced by mesh_foreachScreenFace().
void mesh_foreachScreenVert (ViewContext * vc, void(*)(void *userData, BMVert *eve, int x, int y, int index) func, void * userData, eV3DClipTest clipVerts)
Definition at line 2052 of file drawobject.c.
References CD_MASK_BAREMESH, foreachScreenVert_userData::clipVerts, data, ED_view3d_clipping_local(), EDBM_index_arrays_free(), EDBM_index_arrays_init(), editbmesh_get_derived_cage(), ViewContext::em, DerivedMesh::foreachMappedVert, foreachScreenVert_userData::func, mesh_foreachScreenVert__mapFunc(), ViewContext::obedit, Object::obmat, DerivedMesh::release, ViewContext::rv3d, ViewContext::scene, foreachScreenVert_userData::userData, V3D_CLIP_TEST_OFF, and foreachScreenVert_userData::vc.
static void mesh_foreachScreenVert__mapFunc (void * userData, int index, const float co[3], const float UNUSEDno_f[3], const short UNUSEDno_s[3]) [static]
Definition at line 2029 of file drawobject.c.
References ViewContext::ar, BM_elem_flag_test, BM_ELEM_HIDDEN, foreachScreenVert_userData::clipVerts, data, EDBM_vert_at_index(), ViewContext::em, foreachScreenVert_userData::func, IS_CLIPPED, mul_v3_m4v3(), ViewContext::obedit, Object::obmat, project_short_noclip(), TRUE, foreachScreenVert_userData::userData, V3D_CLIP_TEST_OFF, foreachScreenVert_userData::vc, and view3d_project_short_clip().
Referenced by mesh_foreachScreenVert().
void nurbs_foreachScreenVert (ViewContext * vc, void(*)(void *userData, Nurb *nu, BPoint *bp, BezTriple *bezt, int beztindex, int x, int y) func, void * userData)
Definition at line 2207 of file drawobject.c.
References ViewContext::ar, Nurb::bezt, Nurb::bp, CU_BEZIER, CU_HIDE_HANDLES, curve_editnurbs(), Object::data, Curve::drawflag, ED_view3d_clipping_local(), ListBase::first, BPoint::hide, BezTriple::hide, i, IS_CLIPPED, Nurb::next, NULL, ViewContext::obedit, Object::obmat, Nurb::pntsu, Nurb::pntsv, ViewContext::rv3d, TRUE, Nurb::type, BezTriple::vec, BPoint::vec, and view3d_project_short_clip().
static void ob_draw_RE_motion (float com[3], float rotscale[3][3], float itw, float ith, float drw_size) [static]
Definition at line 4975 of file drawobject.c.
References add_v3_v3(), copy_m3_m3(), and mul_m3_v3().
Referenced by draw_object().
static void spotvolume (float lvec[3], float vvec[3], const float inp) [static]
Definition at line 1055 of file drawobject.c.
References angle(), co, copy_v3_v3(), cosf, cross_v3_v3v3(), mul_m3_m3m3(), mul_m3_v3(), normalize_v3(), quat_to_mat3(), saacos(), si, sqrtf, transpose_m3(), and unit_m3().
Referenced by drawlamp().
static void tekenhandlesN (Nurb * nu, short sel, short hide_handles) [static]
Definition at line 5139 of file drawobject.c.
References Nurb::bezt, CU_BEZIER, BezTriple::f1, BezTriple::f2, BezTriple::f3, BezTriple::h1, BezTriple::h2, Nurb::hide, BezTriple::hide, MIN2, Nurb::pntsu, SELECT, TH_HANDLE_COL_TOT, TH_HANDLE_FREE, TH_HANDLE_SEL_FREE, Nurb::type, UI_GetThemeColor3ubv(), and BezTriple::vec.
Referenced by drawnurb().
static void tekenhandlesN_active (Nurb * nu) [static]
Definition at line 5199 of file drawobject.c.
References Nurb::bezt, CU_BEZIER, Nurb::hide, BezTriple::hide, Nurb::pntsu, TH_ACTIVE_SPLINE, Nurb::type, UI_ThemeColor(), and BezTriple::vec.
Referenced by drawnurb().
static void tekenvertsN (Nurb * nu, short sel, short hide_handles, void * lastsel) [static]
Definition at line 5234 of file drawobject.c.
References Nurb::bezt, bglBegin(), bglEnd(), bglVertex3fv(), Nurb::bp, CU_BEZIER, BezTriple::f1, BPoint::f1, BezTriple::f2, BezTriple::f3, BPoint::hide, Nurb::hide, BezTriple::hide, Nurb::pntsu, Nurb::pntsv, SELECT, size(), TH_LASTSEL_POINT, TH_VERTEX, TH_VERTEX_SELECT, TH_VERTEX_SIZE, Nurb::type, UI_GetThemeValuef(), UI_ThemeColor(), BezTriple::vec, and BPoint::vec.
Referenced by drawnurb().
void view3d_cached_text_draw_add (const float co[3], const char * str, short xoffs, short flag, const unsigned char col[4])
Definition at line 825 of file drawobject.c.
References BLI_addtail(), CachedTextLevel, ViewCachedString::col, copy_v3_v3(), ViewCachedString::flag, MEM_callocN(), ViewCachedString::pack, ViewCachedString::str_len, strings, strlen(), ViewCachedString::vec, and ViewCachedString::xoffs.
Referenced by draw_ebones(), draw_em_indices(), draw_em_measure_stats(), draw_motion_path_instance(), draw_new_particle_system(), draw_object(), draw_pose_bones(), draw_viewport_object_reconstruction(), and drawRBpivot().
void view3d_cached_text_draw_begin (void)
Definition at line 818 of file drawobject.c.
References CachedTextLevel, ListBase::first, ListBase::last, NULL, and strings.
Referenced by draw_object().
void view3d_cached_text_draw_end (View3D * v3d, ARegion * ar, int depth_write, float mat[][4])
Definition at line 846 of file drawobject.c.
References bgl_get_mats(), BLF_draw_default(), BLF_draw_default_ascii(), BLI_freelistN(), CachedTextLevel, ViewCachedString::col, ED_region_pixelspace(), ED_view3d_clipping_disable(), ED_view3d_clipping_enable(), ListBase::first, ViewCachedString::flag, IS_CLIPPED, bglMats::modelview, mul_m4_v3(), ViewCachedString::next, ViewCachedString::pack, bglMats::projection, ARegion::regiondata, RegionView3D::rflag, RV3D_CLIPPING, ViewCachedString::sco, str, ViewCachedString::str_len, strings, ViewCachedString::ub, V3D_CACHE_TEXT_ASCII, V3D_CACHE_TEXT_GLOBALSPACE, V3D_CACHE_TEXT_LOCALCLIP, V3D_CACHE_TEXT_WORLDSPACE, V3D_CACHE_TEXT_ZBUF, ViewCachedString::vec, view3d_project_short_clip(), view3d_project_short_clip_persmat(), bglMats::viewport, ARegion::winrct, rcti::xmin, ViewCachedString::xoffs, rcti::ymin, and View3D::zbuf.
Referenced by draw_object().
static void view3d_project_short_clip (ARegion * ar, const float vec[3], short adr[2], int is_local) [static]
Definition at line 219 of file drawobject.c.
References BL_NEAR_CLIP, copy_v3_v3(), ED_view3d_clipping_test(), floorf, IS_CLIPPED, mul_m4_v4(), RegionView3D::persmatob, ARegion::regiondata, RegionView3D::rflag, RV3D_CLIPPING, ARegion::winx, and ARegion::winy.
Referenced by lattice_foreachScreenVert(), mesh_foreachScreenEdge__mapFunc(), mesh_foreachScreenVert__mapFunc(), nurbs_foreachScreenVert(), and view3d_cached_text_draw_end().
static void view3d_project_short_clip_persmat (ARegion * ar, const float vec[3], short adr[2], int is_local) [static]
Definition at line 284 of file drawobject.c.
References BL_NEAR_CLIP, copy_v3_v3(), ED_view3d_clipping_test(), floorf, IS_CLIPPED, mul_m4_v4(), RegionView3D::persmat, ARegion::regiondata, RegionView3D::rflag, RV3D_CLIPPING, ARegion::winx, and ARegion::winy.
Referenced by view3d_cached_text_draw_end().
static void UNUSED_FUNCTION() view3d_project_short_noclip (ARegion * ar, const float vec[3], short adr[2]) [static]
Definition at line 256 of file drawobject.c.
References BL_NEAR_CLIP, copy_v3_v3(), floorf, IS_CLIPPED, mul_m4_v4(), and RegionView3D::persmatob.
Variable Documentation
ListBase CachedText[3] [static]
Definition at line 801 of file drawobject.c.
int CachedTextLevel = 0 [static]
Definition at line 802 of file drawobject.c.
Referenced by view3d_cached_text_draw_add(), view3d_cached_text_draw_begin(), and view3d_cached_text_draw_end().
unsigned int colortab[24] [static]
Initial value:
{0x0,       0xFF88FF, 0xFFBBFF,
 0x403000,  0xFFFF88, 0xFFFFBB,
 0x104040,  0x66CCCC, 0x77CCCC,
 0x104010,  0x55BB55, 0x66FF66,
 0xFFFFFF}
Definition at line 349 of file drawobject.c.
Referenced by draw_object().
const float cosval[CIRCLE_RESOL] [static]
Definition at line 408 of file drawobject.c.
Referenced by circball_array_fill(), drawcircle_size(), and drawspiral().
float cube[8][3] [static]
Initial value:
 {
    {-1.0, -1.0, -1.0},
    {-1.0, -1.0,  1.0},
    {-1.0,  1.0,  1.0},
    {-1.0,  1.0, -1.0},
    { 1.0, -1.0, -1.0},
    { 1.0, -1.0,  1.0},
    { 1.0,  1.0,  1.0},
    { 1.0,  1.0, -1.0},
}
Definition at line 357 of file drawobject.c.
int draw_index_wire = 1 [static]
Definition at line 3622 of file drawobject.c.
int index3_nors_incr = 1 [static]
Definition at line 3623 of file drawobject.c.
const float sinval[CIRCLE_RESOL] [static]
Definition at line 372 of file drawobject.c.
Referenced by circball_array_fill(), drawcircle_size(), and drawspiral().
float view3d_camera_border_hack_col[4]
Definition at line 1504 of file drawobject.c.
Referenced by drawcamera(), and drawviewborder().
short view3d_camera_border_hack_test = FALSE
Definition at line 1505 of file drawobject.c.
Referenced by drawcamera(), and drawviewborder().