Blender: node_shader_mapping.c File Reference
node_shader_mapping.c File Reference
shdnodes
#include "node_shader_util.h"
Functions
static void node_shader_exec_mapping (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_shader_init_mapping (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static int gpu_shader_mapping (GPUMaterial *mat, bNode *node, GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_mapping (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_mapping_in []
static bNodeSocketTemplate sh_node_mapping_out []
Detailed Description
Definition in file node_shader_mapping.c.
Function Documentation
static int gpu_shader_mapping (GPUMaterial * mat, bNode * node, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 75 of file node_shader_mapping.c.
References TexMapping::flag, GPU_stack_link(), GPU_uniform(), TexMapping::mat, TexMapping::max, TexMapping::min, bNode::storage, TEXMAP_CLIP_MAX, and TEXMAP_CLIP_MIN.
Referenced by register_node_type_sh_mapping().
static void node_shader_exec_mapping (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 47 of file node_shader_mapping.c.
References TexMapping::flag, TexMapping::mat, TexMapping::max, TexMapping::min, mul_m4_v3(), nodestack_get_vec(), SOCK_VECTOR, bNode::storage, TEXMAP_CLIP_MAX, TEXMAP_CLIP_MIN, and bNodeStack::vec.
Referenced by register_node_type_sh_mapping().
static void node_shader_init_mapping (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 70 of file node_shader_mapping.c.
References add_tex_mapping(), and bNode::storage.
Referenced by register_node_type_sh_mapping().
void register_node_type_sh_mapping (bNodeTreeType * ttype)
Definition at line 89 of file node_shader_mapping.c.
References gpu_shader_mapping(), NODE_CLASS_OP_VECTOR, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_mapping(), node_shader_init_mapping(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and SH_NODE_MAPPING.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_mapping_in[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 1, "Vector",   0.0f, 0.0f, 0.0f, 1.0f, -1.0f, 1.0f, PROP_NONE},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_shader_mapping.c.
bNodeSocketTemplate sh_node_mapping_out[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 0, "Vector"},
    {   -1, 0, ""   }
}
Definition at line 41 of file node_shader_mapping.c.