Blender: editarmature_generate.c File Reference
editarmature_generate.c File Reference
armature
#include <string.h>
#include <math.h>
#include <float.h>
#include "DNA_scene_types.h"
#include "DNA_armature_types.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_graph.h"
#include "BLI_utildefines.h"
#include "ED_armature.h"
#include "armature_intern.h"
#include "BIF_generate.h"
Functions
void setBoneRollFromNormal (EditBone *bone, float *no, float UNUSED(invmat[][4]), float tmat[][3])
float calcArcCorrelation (BArcIterator *iter, int start, int end, float v0[3], float n[3])
int nextFixedSubdivision (ToolSettings *toolsettings, BArcIterator *iter, int start, int end, float UNUSED(head[3]), float p[3])
int nextAdaptativeSubdivision (ToolSettings *toolsettings, BArcIterator *iter, int start, int end, float head[3], float p[3])
int nextLengthSubdivision (ToolSettings *toolsettings, BArcIterator *iter, int start, int end, float head[3], float p[3])
EditBone * subdivideArcBy (ToolSettings *toolsettings, bArmature *arm, ListBase *UNUSED(editbones), BArcIterator *iter, float invmat[][4], float tmat[][3], NextSubdivisionFunc next_subdividion)
Detailed Description
Definition in file editarmature_generate.c.
Function Documentation
float calcArcCorrelation (BArcIterator * iter, int start, int end, float v0[3], float n[3])
Definition at line 66 of file editarmature_generate.c.
References abs(), dot_v3v3(), i, IT_peek(), len(), len_v3(), BArcIterator::p, project_v3_v3v3(), sub_v3_v3(), and sub_v3_v3v3().
Referenced by nextAdaptativeSubdivision(), and sk_getSegments().
int nextAdaptativeSubdivision (ToolSettings * toolsettings, BArcIterator * iter, int start, int end, float head[3], float p[3])
Definition at line 176 of file editarmature_generate.c.
References calcArcCorrelation(), copy_v3_v3(), i, IT_peek(), BArcIterator::p, ToolSettings::skgen_correlation_limit, and sub_v3_v3v3().
Referenced by sk_convertStroke(), and sk_drawStrokeSubdivision().
int nextFixedSubdivision (ToolSettings * toolsettings, BArcIterator * iter, int start, int end, float UNUSEDhead[3], float p[3])
Definition at line 119 of file editarmature_generate.c.
References copy_v3_v3(), i, IT_peek(), len_v3v3(), BArcIterator::p, and ToolSettings::skgen_subdivision_number.
int nextLengthSubdivision (ToolSettings * toolsettings, BArcIterator * iter, int start, int end, float head[3], float p[3])
Definition at line 202 of file editarmature_generate.c.
References add_v3_v3(), copy_v3_v3(), dot_v3v3(), i, isnan(), IT_peek(), len_v3v3(), mul_v3_fl(), normalize_v3(), BArcIterator::p, ToolSettings::skgen_length_limit, sqrt(), and sub_v3_v3v3().
Referenced by sk_convertStroke(), and sk_drawStrokeSubdivision().
void setBoneRollFromNormal (EditBone * bone, float * no, float UNUSEDinvmat[][4], float tmat[][3])
Definition at line 53 of file editarmature_generate.c.
References copy_v3_v3(), ED_rollBoneToVector(), FALSE, is_zero_v3(), mul_m3_v3(), NULL, and EditBone::roll.
EditBone* subdivideArcBy (ToolSettings * toolsettings, bArmature * arm, ListBase * UNUSEDeditbones, BArcIterator * iter, float invmat[][4], float tmat[][3], NextSubdivisionFunc next_subdividion)
Definition at line 273 of file editarmature_generate.c.
References BONE_CONNECTED, copy_v3_v3(), ED_armature_edit_bone_add(), EditBone::flag, EditBone::head, IT_head(), IT_peek(), BArcIterator::length, mul_m4_v3(), BArcIterator::no, NULL, BArcIterator::p, EditBone::parent, EditBone::rad_head, EditBone::rad_tail, setBoneRollFromNormal(), BArcIterator::size, EditBone::tail, and BArcIterator::tail.