Blender: GIM_BOX_BOX_TRANSFORM_CACHE Class Reference
GIM_BOX_BOX_TRANSFORM_CACHE Class Reference
Class for transforming a model1 to the space of model0.
#include <gim_box_collision.h>
Public Member Functions
SIMD_FORCE_INLINE void calc_absolute_matrix ()
GIM_BOX_BOX_TRANSFORM_CACHE ()
GIM_BOX_BOX_TRANSFORM_CACHE (mat4f trans1_to_0)
SIMD_FORCE_INLINE void calc_from_homogenic (const btTransform &trans0, const btTransform &trans1)
Calc the transformation relative 1 to 0. Inverts matrics by transposing.
SIMD_FORCE_INLINE void calc_from_full_invert (const btTransform &trans0, const btTransform &trans1)
Calcs the full invertion of the matrices. Useful for scaling matrices.
SIMD_FORCE_INLINE btVector3 transform (const btVector3 &point)
Public Attributes
btVector3 m_T1to0
Transforms translation of model1 to model 0.
btMatrix3x3 m_R1to0
Transforms Rotation of model1 to model 0, equal to R0' * R1.
btMatrix3x3 m_AR
Absolute value of m_R1to0.
Detailed Description
Class for transforming a model1 to the space of model0.
Definition at line 135 of file gim_box_collision.h.
Constructor & Destructor Documentation
GIM_BOX_BOX_TRANSFORM_CACHE::GIM_BOX_BOX_TRANSFORM_CACHE () [inline]
Definition at line 150 of file gim_box_collision.h.
GIM_BOX_BOX_TRANSFORM_CACHE::GIM_BOX_BOX_TRANSFORM_CACHE (mat4f trans1_to_0) [inline]
Definition at line 155 of file gim_box_collision.h.
References calc_absolute_matrix(), COPY_MATRIX_3X3, m_R1to0, m_T1to0, and MAT_GET_TRANSLATION.
Member Function Documentation
SIMD_FORCE_INLINE void GIM_BOX_BOX_TRANSFORM_CACHE::calc_absolute_matrix () [inline]
Definition at line 142 of file gim_box_collision.h.
References btMatrix3x3::absolute(), m_AR, and m_R1to0.
Referenced by calc_from_full_invert(), calc_from_homogenic(), and GIM_BOX_BOX_TRANSFORM_CACHE().
SIMD_FORCE_INLINE void GIM_BOX_BOX_TRANSFORM_CACHE::calc_from_full_invert (const btTransform & trans0, const btTransform & trans1) [inline]
Calcs the full invertion of the matrices. Useful for scaling matrices.
Definition at line 176 of file gim_box_collision.h.
References calc_absolute_matrix(), btTransform::getBasis(), btTransform::getOrigin(), btMatrix3x3::inverse(), m_R1to0, and m_T1to0.
SIMD_FORCE_INLINE void GIM_BOX_BOX_TRANSFORM_CACHE::calc_from_homogenic (const btTransform & trans0, const btTransform & trans1) [inline]
Calc the transformation relative 1 to 0. Inverts matrics by transposing.
Definition at line 163 of file gim_box_collision.h.
References calc_absolute_matrix(), btTransform::getBasis(), btTransform::getOrigin(), m_R1to0, m_T1to0, and btMatrix3x3::transpose().
Referenced by GIM_TREE_TREE_COLLIDER< BOX_SET_CLASS0, BOX_SET_CLASS1 >::find_collision().
SIMD_FORCE_INLINE btVector3 GIM_BOX_BOX_TRANSFORM_CACHE::transform (const btVector3 & point) [inline]
Definition at line 187 of file gim_box_collision.h.
References dot(), m_R1to0, and m_T1to0.
Referenced by GIM_TREE_TREE_COLLIDER< BOX_SET_CLASS0, BOX_SET_CLASS1 >::retrieve_node1_triangle().
Member Data Documentation
btMatrix3x3 GIM_BOX_BOX_TRANSFORM_CACHE::m_AR
Absolute value of m_R1to0.
Definition at line 140 of file gim_box_collision.h.
Referenced by calc_absolute_matrix(), and GIM_AABB::overlapping_trans_cache().
btMatrix3x3 GIM_BOX_BOX_TRANSFORM_CACHE::m_R1to0
Transforms Rotation of model1 to model 0, equal to R0' * R1.
Definition at line 139 of file gim_box_collision.h.
Referenced by calc_absolute_matrix(), calc_from_full_invert(), calc_from_homogenic(), GIM_BOX_BOX_TRANSFORM_CACHE(), GIM_AABB::overlapping_trans_cache(), and transform().
btVector3 GIM_BOX_BOX_TRANSFORM_CACHE::m_T1to0
Transforms translation of model1 to model 0.
Definition at line 138 of file gim_box_collision.h.
Referenced by calc_from_full_invert(), calc_from_homogenic(), GIM_BOX_BOX_TRANSFORM_CACHE(), GIM_AABB::overlapping_trans_cache(), and transform().
The documentation for this class was generated from the following file:
gim_box_collision.h