Blender: KX_SCA_DynamicActuator Class Reference
KX_SCA_DynamicActuator Class Reference
#include <KX_SCA_DynamicActuator.h>
Public Types
enum DynamicOperation {
KX_DYN_RESTORE_DYNAMICS = 0, KX_DYN_DISABLE_DYNAMICS, KX_DYN_ENABLE_RIGID_BODY, KX_DYN_DISABLE_RIGID_BODY,
KX_DYN_SET_MASS
}
Public Member Functions
KX_SCA_DynamicActuator (SCA_IObject *gameobj, short dyn_operation, float setmass)
~KX_SCA_DynamicActuator ()
CValue * GetReplica ()
virtual bool Update ()
Detailed Description
Definition at line 43 of file KX_SCA_DynamicActuator.h.
Member Enumeration Documentation
enum KX_SCA_DynamicActuator::DynamicOperation
Enumerator:
KX_DYN_RESTORE_DYNAMICS
KX_DYN_DISABLE_DYNAMICS
KX_DYN_ENABLE_RIGID_BODY
KX_DYN_DISABLE_RIGID_BODY
KX_DYN_SET_MASS
Definition at line 68 of file KX_SCA_DynamicActuator.h.
Constructor & Destructor Documentation
KX_SCA_DynamicActuator::KX_SCA_DynamicActuator (SCA_IObject * gameobj, short dyn_operation, float setmass)
Definition at line 88 of file KX_SCA_DynamicActuator.cpp.
Referenced by GetReplica().
KX_SCA_DynamicActuator::~KX_SCA_DynamicActuator ()
Definition at line 99 of file KX_SCA_DynamicActuator.cpp.
Member Function Documentation
CValue * KX_SCA_DynamicActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 147 of file KX_SCA_DynamicActuator.cpp.
References KX_SCA_DynamicActuator(), NULL, and SCA_IActuator::ProcessReplica().
bool KX_SCA_DynamicActuator::Update (void) [virtual]
Reimplemented from SCA_IActuator.
Definition at line 106 of file KX_SCA_DynamicActuator.cpp.
References SCA_ILogicBrick::GetParent(), KX_GameObject::GetPhysicsController(), SCA_IActuator::IsNegativeEvent(), SCA_IActuator::RemoveAllEvents(), KX_GameObject::RestoreDynamics(), KX_IPhysicsController::SetMass(), KX_IPhysicsController::setRigidBody(), and KX_GameObject::SuspendDynamics().
The documentation for this class was generated from the following files:
KX_SCA_DynamicActuator.h
KX_SCA_DynamicActuator.cpp