Blender: RE_shader_ext.h File Reference
RE_shader_ext.h File Reference
Rendering
Classes
struct TexResult
struct ShadeResult
struct ShadeInputCopy
struct ShadeInputUV
struct ShadeInputCol
struct ShadeInput
Defines
#define BAKE_RESULT_OK 0
#define BAKE_RESULT_NO_OBJECTS 1
#define BAKE_RESULT_FEEDBACK_LOOP 2
Typedefs
typedef struct TexResult TexResult
typedef struct ShadeResult ShadeResult
typedef struct ShadeInputUV ShadeInputUV
typedef struct ShadeInputCol ShadeInputCol
typedef struct ShadeInput ShadeInput
Functions
int multitex_ext (struct Tex *tex, float *texvec, float *dxt, float *dyt, int osatex, struct TexResult *texres)
int multitex_ext_safe (struct Tex *tex, float *texvec, struct TexResult *texres)
int multitex_nodes (struct Tex *tex, float *texvec, float *dxt, float *dyt, int osatex, struct TexResult *texres, short thread, short which_output, struct ShadeInput *shi, struct MTex *mtex)
int RE_bake_shade_all_selected (struct Render *re, int type, struct Object *actob, short *do_update, float *progress)
struct Image * RE_bake_shade_get_image (void)
void RE_bake_ibuf_filter (struct ImBuf *ibuf, char *mask, const int filter)
Detailed Description
Definition in file RE_shader_ext.h.
Define Documentation
#define BAKE_RESULT_FEEDBACK_LOOP 2
Definition at line 215 of file RE_shader_ext.h.
Referenced by bake_freejob(), bake_image_exec(), and RE_bake_shade_all_selected().
#define BAKE_RESULT_NO_OBJECTS 1
Definition at line 214 of file RE_shader_ext.h.
Referenced by bake_freejob(), bake_image_exec(), and RE_bake_shade_all_selected().
#define BAKE_RESULT_OK 0
Definition at line 213 of file RE_shader_ext.h.
Referenced by finish_bake_internal(), and RE_bake_shade_all_selected().
Typedef Documentation
typedef struct ShadeInput ShadeInput
typedef struct ShadeInputCol ShadeInputCol
typedef struct ShadeInputUV ShadeInputUV
typedef struct ShadeResult ShadeResult
typedef struct TexResult TexResult
Function Documentation
int multitex_ext (struct Tex * tex, float * texvec, float * dxt, float * dyt, int osatex, struct TexResult * texres)
Definition at line 1366 of file render_texture.c.
References multitex_nodes(), and NULL.
Referenced by brush_gen_texture_cache(), do_texture_effector(), paint_get_tex_pixel(), and texture_procedural().
int multitex_ext_safe (struct Tex * tex, float * texvec, struct TexResult * texres)
Definition at line 1372 of file render_texture.c.
References multitex_nodes(), NULL, and Tex::use_nodes.
Referenced by dynamicPaint_setInitialColor(), and get_texture_value().
int multitex_nodes (struct Tex * tex, float * texvec, float * dxt, float * dyt, int osatex, struct TexResult * texres, short thread, short which_output, struct ShadeInput * shi, struct MTex * mtex)
Definition at line 1293 of file render_texture.c.
References BKE_image_get_ibuf(), copy_v3_v3(), do_2d_mapping(), ShadeInput::facenor, Tex::ima, Tex::iuser, MAP_COL, MAP_COLMIR, MAP_COLSPEC, MTex::mapping, MTex::mapto, MTEX_FLAT, multitex(), NULL, MTex::object, R, R_COLOR_MANAGEMENT, ImBuf::rect_float, srgb_to_linearrgb_v3_v3(), MTex::tex, TEX_IMAGE, MTex::texco, TEXCO_ORCO, TexResult::tr, Tex::type, ShadeInput::vlr, MTex::which_output, and zero_v3().
Referenced by do_proc(), multitex_ext(), multitex_ext_safe(), and node_shader_exec_texture().
void RE_bake_ibuf_filter (struct ImBuf * ibuf, char * mask, const int filter)
Definition at line 2567 of file rendercore.c.
References BKE_alphatest_ibuf(), IMB_filter_extend(), IMB_rectfill_alpha(), ImBuf::planes, and R_IMF_PLANES_RGBA.
Referenced by finish_images(), and RE_bake_shade_all_selected().
int RE_bake_shade_all_selected (struct Render * re, int type, struct Object * actob, short * do_update, float * progress)
Definition at line 2592 of file rendercore.c.
References BakeShade::actob, RenderData::bake_filter, BAKE_RESULT_FEEDBACK_LOOP, BAKE_RESULT_NO_OBJECTS, BAKE_RESULT_OK, BKE_image_get_ibuf(), BLI_end_threads(), BLI_init_threads(), BLI_insert_thread(), ShadeInput::combinedflag, do_bake_thread(), BakeShade::do_update, Image::flag, ID::flag, G, get_next_bake_face(), IB_BITMAPDIRTY, IB_PROFILE_LINEAR_RGB, Image::id, IMA_USED_FOR_RENDER, IMB_rect_from_float(), ShadeInput::lay, Render::lay, LIB_DOIT, MEM_callocN(), MEM_freeN(), ID::next, NULL, ShadeInput::passflag, PIL_sleep_ms(), ImBuf::profile, R, Render::r, RE_bake_ibuf_filter(), RE_BAKE_SHADOW, ImBuf::rect_float, SCE_PASS_COMBINED, SCE_PASS_SHADOW, SCE_PASS_SPEC, ShadeSample::shi, BakeShade::ssamp, ShadeInput::thread, RenderData::threads, threads, ShadeSample::tot, Render::totvlak, BakeShade::type, BakeShade::usemask, ImBuf::userdata, ImBuf::userflags, zbuf_free_span(), and BakeShade::zspan.
Referenced by bake_startjob(), and do_bake_render().
struct Image* RE_bake_shade_get_image (void) [read]
Definition at line 2703 of file rendercore.c.
References R.
Referenced by bake_update().