Blender: occlusion.h File Reference
occlusion.h File Reference
Rendering
Functions
void make_occ_tree (struct Render *re)
void free_occ (struct Render *re)
void sample_occ (struct Render *re, struct ShadeInput *shi)
void cache_occ_samples (struct Render *re, struct RenderPart *pa, struct ShadeSample *ssamp)
void free_occ_samples (struct Render *re, struct RenderPart *pa)
Detailed Description
Definition in file occlusion.h.
Function Documentation
void cache_occ_samples (struct Render * re, struct RenderPart * pa, struct ShadeSample * ssamp)
Definition at line 1811 of file occlusion.c.
References ShadeInput::ao, OcclusionCacheSample::ao, OcclusionTree::cache, CACHE_STEP, ShadeInput::co, OcclusionCacheSample::co, copy_v3_v3(), RenderPart::disprect, OcclusionCacheSample::dist2, dot_v3v3(), ShadeInput::dxco, ShadeInput::dyco, ShadeInput::env, OcclusionCacheSample::env, OccFace::facenr, PixStr::facenr, OcclusionCacheSample::filled, OcclusionCache::h, VlakRen::index, OcclusionCacheSample::indirect, ShadeInput::indirect, OcclusionCacheSample::intensity, MA_ONLYSHADOW, PixStr::mask, ShadeInput::mat, MAX2, MAX3(), MEM_callocN(), Material::mode, OcclusionCacheSample::n, PixStr::next, NULL, OccFace::obi, ShadeInput::obi, PixStr::obi, Render::objectinstance, Render::occlusiontree, Render::osa, RenderPart::rectdaps, RenderPart::recto, RenderPart::rectp, RenderPart::rectx, RenderPart::recty, RenderPart::rectz, OcclusionCache::sample, sample_occ_tree(), shade_samples_fill_with_ps(), ShadeSample::shi, OcclusionCache::step, step(), Render::tbh, Render::test_break, ShadeInput::thread, RenderPart::thread, ShadeInput::vlr, ShadeInput::vno, OcclusionCache::w, OcclusionCache::x, OcclusionCacheSample::x, rcti::xmax, rcti::xmin, ShadeInput::xs, OcclusionCache::y, OcclusionCacheSample::y, rcti::ymax, rcti::ymin, ShadeInput::ys, and PixStr::z.
Referenced by shadeDA_tile(), and zbufshade_tile().
void free_occ (struct Render * re)
Definition at line 1748 of file occlusion.c.
References NULL, occ_free_tree(), and Render::occlusiontree.
Referenced by RE_Database_Free().
void free_occ_samples (struct Render * re, struct RenderPart * pa)
Definition at line 1897 of file occlusion.c.
References OcclusionTree::cache, OcclusionCache::h, MEM_freeN(), Render::occlusiontree, OcclusionCache::sample, OcclusionCache::step, RenderPart::thread, and OcclusionCache::w.
Referenced by shadeDA_tile(), and zbufshade_tile().
void make_occ_tree (struct Render * re)
Definition at line 1647 of file occlusion.c.
References add_v3_v3(), StrandSurface::ao, World::ao_approx_passes, World::ao_indirect_bounces, OcclusionThread::begin, BLENDER_MAX_THREADS, BLI_end_threads(), BLI_init_threads(), BLI_insert_thread(), StrandSurface::co, copy_v3_v3(), OcclusionTree::doindirect, OcclusionThread::end, StrandSurface::env, exec_strandsurface_sample(), StrandSurface::face, OcclusionThread::faceao, OcclusionThread::faceenv, OcclusionThread::faceindirect, ListBase::first, Render::i, StrandSurface::indirect, RenderStats::infostr, MEM_callocN(), MEM_freeN(), OcclusionThread::mesh, World::mode, mul_v3_fl(), StrandSurface::next, occ_compute_bounces(), occ_compute_passes(), occ_tree_build(), Render::occlusiontree, Render::r, OcclusionThread::re, Render::sdh, Render::stats_draw, Render::strandsurface, OcclusionThread::thread, RenderData::threads, threads, StrandSurface::totface, StrandSurface::totvert, WO_INDIRECT_LIGHT, and Render::wrld.
Referenced by RE_Database_Baking(), and RE_Database_FromScene().
void sample_occ (struct Render * re, struct ShadeInput * shi)
Definition at line 1756 of file occlusion.c.
References ShadeInput::ao, OcclusionCacheSample::ao, OcclusionTree::cache, ShadeInput::co, OcclusionCacheSample::co, copy_v3_v3(), ShadeInput::depth, OcclusionCacheSample::dist2, dot_v3v3(), ShadeInput::dxco, ShadeInput::dyco, ShadeInput::env, OcclusionCacheSample::env, OccFace::facenr, OcclusionCacheSample::filled, VlakRen::index, OcclusionCacheSample::indirect, ShadeInput::indirect, OcclusionCacheSample::intensity, MA_ONLYSHADOW, ShadeInput::mat, MAX2, MAX3(), Material::mode, OcclusionCacheSample::n, OccFace::obi, ShadeInput::obi, Render::objectinstance, Render::occlusiontree, OcclusionCache::sample, sample_occ_cache(), sample_occ_surface(), sample_occ_tree(), OcclusionCache::step, ShadeInput::strand, ShadeInput::thread, ShadeInput::vlr, ShadeInput::vno, OcclusionCache::w, OcclusionCache::x, ShadeInput::xs, OcclusionCache::y, and ShadeInput::ys.
Referenced by ambient_occlusion().