Blender: AUD_LoopReader Class Reference
AUD_LoopReader Class Reference
#include <AUD_LoopReader.h>
Public Member Functions
AUD_LoopReader (AUD_Reference< AUD_IReader > reader, int loop)
virtual void seek (int position)
virtual int getLength () const
virtual int getPosition () const
virtual void read (int &length, bool &eos, sample_t *buffer)
Detailed Description
This class reads another reader and loops it.
Note:
The other reader must be seekable.
Definition at line 40 of file AUD_LoopReader.h.
Constructor & Destructor Documentation
AUD_LoopReader::AUD_LoopReader (AUD_Reference< AUD_IReader > reader, int loop)
Creates a new loop reader.
Parameters:
reader The reader to read from.
loop The desired loop count, negative values result in endless looping.
Definition at line 35 of file AUD_LoopReader.cpp.
Member Function Documentation
int AUD_LoopReader::getLength () const [virtual]
Returns an approximated length of the source in samples.
Returns:
The length as sample count. May be negative if unknown.
Reimplemented from AUD_EffectReader.
Definition at line 57 of file AUD_LoopReader.cpp.
References AUD_EffectReader::m_reader.
int AUD_LoopReader::getPosition () const [virtual]
Returns the position of the source as a sample count value.
Returns:
The current position in the source. A negative value indicates that the position is unknown.
Warning:
The value returned doesn't always have to be correct for readers, especially after seeking.
Reimplemented from AUD_EffectReader.
Definition at line 64 of file AUD_LoopReader.cpp.
References AUD_EffectReader::m_reader.
void AUD_LoopReader::read (int & length, bool & eos, sample_t * buffer) [virtual]
Request to read the next length samples out of the source. The buffer supplied has the needed size.
Parameters:
[in,out] length The count of samples that should be read. Shall contain the real count of samples after reading, in case there were only fewer samples available. A smaller value also indicates the end of the reader.
[out] eos End of stream, whether the end is reached or not.
[in] buffer The pointer to the buffer to read into.
Reimplemented from AUD_EffectReader.
Definition at line 69 of file AUD_LoopReader.cpp.
References AUD_Specs::channels, len(), length(), and AUD_EffectReader::m_reader.
void AUD_LoopReader::seek (int position) [virtual]
Seeks to a specific position in the source.
Parameters:
position The position to seek for measured in samples. To get from a given time to the samples you simply have to multiply the time value in seconds with the sample rate of the reader.
Warning:
This may work or not, depending on the actual reader.
Reimplemented from AUD_EffectReader.
Definition at line 40 of file AUD_LoopReader.cpp.
References len(), and AUD_EffectReader::m_reader.
The documentation for this class was generated from the following files:
AUD_LoopReader.h
AUD_LoopReader.cpp