Blender: time_intern.h File Reference
time_intern.h File Reference
time line
Functions
void time_operatortypes (void)
void time_keymap (struct wmKeyConfig *keyconf)
Detailed Description
Definition in file time_intern.h.
Function Documentation
void time_keymap (struct wmKeyConfig * keyconf)
Definition at line 188 of file time_ops.c.
References EKEY, HOMEKEY, KM_PRESS, SKEY, SPACE_TIME, WM_keymap_add_item(), and WM_keymap_find().
Referenced by ED_spacetype_time().
void time_operatortypes (void)
Definition at line 181 of file time_ops.c.
References TIME_OT_end_frame_set(), TIME_OT_start_frame_set(), TIME_OT_view_all(), and WM_operatortype_append().
Referenced by ED_spacetype_time().