Blender: BL_ModifierDeformer Class Reference
BL_ModifierDeformer Class Reference
#include <BL_ModifierDeformer.h>
Public Member Functions
BL_ModifierDeformer (BL_DeformableGameObject *gameobj, Scene *scene, Object *bmeshobj, RAS_MeshObject *mesh)
BL_ModifierDeformer (BL_DeformableGameObject *gameobj, struct Scene *scene, struct Object *bmeshobj_old, struct Object *bmeshobj_new, class RAS_MeshObject *mesh, bool release_object, BL_ArmatureObject *arma=NULL)
virtual void ProcessReplica ()
virtual RAS_Deformer * GetReplica ()
virtual ~BL_ModifierDeformer ()
virtual bool UseVertexArray ()
bool Update (void)
bool Apply (RAS_IPolyMaterial *mat)
void ForceUpdate ()
virtual struct DerivedMesh * GetFinalMesh ()
virtual struct DerivedMesh * GetPhysicsMesh ()
Static Public Member Functions
static bool HasCompatibleDeformer (Object *ob)
static bool HasArmatureDeformer (Object *ob)
Protected Attributes
double m_lastModifierUpdate
Scene * m_scene
DerivedMesh * m_dm
Detailed Description
Definition at line 46 of file BL_ModifierDeformer.h.
Constructor & Destructor Documentation
BL_ModifierDeformer::BL_ModifierDeformer (BL_DeformableGameObject * gameobj, Scene * scene, Object * bmeshobj, RAS_MeshObject * mesh) [inline]
Definition at line 53 of file BL_ModifierDeformer.h.
References BL_SkinDeformer::m_recalcNormal.
Referenced by GetReplica().
BL_ModifierDeformer::BL_ModifierDeformer (BL_DeformableGameObject * gameobj, struct Scene * scene, struct Object * bmeshobj_old, struct Object * bmeshobj_new, class RAS_MeshObject * mesh, bool release_object, BL_ArmatureObject * arma = NULL) [inline]
Definition at line 67 of file BL_ModifierDeformer.h.
BL_ModifierDeformer::~BL_ModifierDeformer () [virtual]
Definition at line 77 of file BL_ModifierDeformer.cpp.
References DerivedMesh::deformedOnly, m_dm, DerivedMesh::needsFree, and DerivedMesh::release.
Member Function Documentation
bool BL_ModifierDeformer::Apply (RAS_IPolyMaterial * mat) [virtual]
Reimplemented from BL_SkinDeformer.
Definition at line 211 of file BL_ModifierDeformer.cpp.
References RAS_MeshObject::GetMeshMaterial(), m_dm, BL_MeshDeformer::m_gameobj, BL_MeshDeformer::m_pMeshObject, RAS_MeshMaterial::m_slots, RAS_MeshObject::NumMaterials(), and Update().
void BL_ModifierDeformer::ForceUpdate () [inline]
Reimplemented from BL_ShapeDeformer.
Definition at line 92 of file BL_ModifierDeformer.h.
References m_lastModifierUpdate.
Referenced by GetPhysicsMesh().
virtual struct DerivedMesh* BL_ModifierDeformer::GetFinalMesh () [inline, read, virtual]
Reimplemented from RAS_Deformer.
Definition at line 96 of file BL_ModifierDeformer.h.
References m_dm.
struct DerivedMesh * BL_ModifierDeformer::GetPhysicsMesh () [read, virtual]
Reimplemented from RAS_Deformer.
Definition at line 142 of file BL_ModifierDeformer.cpp.
References CD_MASK_MESH, Object::data, ForceUpdate(), BL_DeformableGameObject::GetBlendObject(), BL_MeshDeformer::m_bmesh, BL_MeshDeformer::m_gameobj, m_scene, BL_MeshDeformer::m_transverts, mesh_create_derived_physics(), and Update().
RAS_Deformer * BL_ModifierDeformer::GetReplica (void) [virtual]
Reimplemented from BL_ShapeDeformer.
Definition at line 88 of file BL_ModifierDeformer.cpp.
References BL_ModifierDeformer(), and ProcessReplica().
bool BL_ModifierDeformer::HasArmatureDeformer (Object * ob) [static]
Definition at line 129 of file BL_ModifierDeformer.cpp.
References eModifierType_Armature, ListBase::first, if(), Object::modifiers, and ModifierData::type.
Referenced by BL_ConvertBlenderObjects(), gameobject_from_blenderobject(), and KX_Scene::ReplaceMesh().
bool BL_ModifierDeformer::HasCompatibleDeformer (Object * ob) [static]
Definition at line 108 of file BL_ModifierDeformer.cpp.
References eModifierMode_Realtime, eModifierType_Armature, ListBase::first, Object::gameflag, ModifierData::mode, modifier_dependsOnTime(), Object::modifiers, ModifierData::next, OB_SOFT_BODY, and ModifierData::type.
Referenced by gameobject_from_blenderobject(), and KX_Scene::ReplaceMesh().
void BL_ModifierDeformer::ProcessReplica () [virtual]
Reimplemented from BL_ShapeDeformer.
Definition at line 97 of file BL_ModifierDeformer.cpp.
References DerivedMesh::deformedOnly, m_dm, and m_lastModifierUpdate.
Referenced by GetReplica().
bool BL_ModifierDeformer::Update (void) [virtual]
Reimplemented from BL_ShapeDeformer.
Definition at line 165 of file BL_ModifierDeformer.cpp.
References CD_MASK_MESH, Object::data, DerivedMesh::deformedOnly, BL_DeformableGameObject::GetBlendObject(), KX_GameObject::GetGraphicController(), BL_DeformableGameObject::GetLastFrame(), DerivedMesh::getMinMax, INIT_MINMAX, RAS_Deformer::m_bDynamic, BL_MeshDeformer::m_bmesh, m_dm, BL_MeshDeformer::m_gameobj, m_lastModifierUpdate, m_scene, BL_MeshDeformer::m_transverts, mesh_create_derived_no_virtual(), DerivedMesh::needsFree, NULL, DerivedMesh::release, and PHY_IGraphicController::setLocalAabb().
Referenced by Apply(), and GetPhysicsMesh().
virtual bool BL_ModifierDeformer::UseVertexArray () [inline, virtual]
Reimplemented from RAS_Deformer.
Definition at line 85 of file BL_ModifierDeformer.h.
Member Data Documentation
DerivedMesh* BL_ModifierDeformer::m_dm [protected]
Definition at line 106 of file BL_ModifierDeformer.h.
Referenced by Apply(), GetFinalMesh(), ProcessReplica(), Update(), and ~BL_ModifierDeformer().
double BL_ModifierDeformer::m_lastModifierUpdate [protected]
Definition at line 104 of file BL_ModifierDeformer.h.
Referenced by ForceUpdate(), ProcessReplica(), and Update().
Scene* BL_ModifierDeformer::m_scene [protected]
Definition at line 105 of file BL_ModifierDeformer.h.
Referenced by GetPhysicsMesh(), and Update().
The documentation for this class was generated from the following files:
BL_ModifierDeformer.h
BL_ModifierDeformer.cpp