Blender: ed_util.c File Reference
ed_util.c File Reference
editor utilities
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "DNA_mesh_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_packedFile_types.h"
#include "BLI_blenlib.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_utildefines.h"
#include "BKE_packedFile.h"
#include "ED_armature.h"
#include "ED_mesh.h"
#include "ED_object.h"
#include "ED_sculpt.h"
#include "ED_util.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "WM_types.h"
#include "WM_api.h"
#include "RNA_access.h"
Functions
void ED_editors_init (bContext *C)
void ED_editors_exit (bContext *C)
void apply_keyb_grid (int shift, int ctrl, float *val, float fac1, float fac2, float fac3, int invert)
void unpack_menu (bContext *C, const char *opname, const char *id_name, const char *abs_name, const char *folder, struct PackedFile *pf)
Detailed Description
Definition in file ed_util.c.
Function Documentation
void apply_keyb_grid (int shift, int ctrl, float * val, float fac1, float fac2, float fac3, int invert)
Definition at line 135 of file ed_util.c.
References floorf.
Referenced by ed_marker_move_modal().
void ED_editors_exit (bContext * C)
Definition at line 92 of file ed_util.c.
References CTX_data_main(), Object::data, ED_armature_edit_free(), ED_undo_paint_free(), EDBM_mesh_free(), Mesh::edit_btmesh, ListBase::first, Scene::id, MEM_freeN(), mesh_mirrtopo_table(), mesh_octree_table(), ID::next, NULL, OB_ARMATURE, OB_MESH, Scene::obedit, Main::scene, Object::type, and undo_editmode_clear().
Referenced by WM_exit_ext(), and wm_window_match_init().
void ED_editors_init (bContext * C)
Definition at line 68 of file ed_util.c.
References Scene::basact, CTX_data_main(), CTX_data_scene(), Object::data, data, ED_object_toggle_modes(), ListBase::first, Object::id, ID::lib, Object::mode, ID::next, NULL, OB_MODE_POSE, Main::object, and Base::object.
Referenced by WM_read_file(), and WM_read_homefile().
void unpack_menu (bContext * C, const char * opname, const char * id_name, const char * abs_name, const char * folder, struct PackedFile * pf)
Definition at line 163 of file ed_util.c.
References BLI_snprintf(), BLI_splitdirstring(), BLI_strncpy(), checkPackedFile(), FILE_MAX, FILE_MAXDIR, G, NULL, PF_DIFFERS, PF_EQUAL, PF_NOFILE, PF_REMOVE, PF_USE_LOCAL, PF_USE_ORIGINAL, PF_WRITE_LOCAL, PF_WRITE_ORIGINAL, RNA_enum_set(), RNA_string_set(), UI_ITEM_O_RETURN_PROPS, uiItemFullO_ptr(), uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), WM_OP_EXEC_DEFAULT, and WM_operatortype_find().
Referenced by image_unpack_invoke(), and sound_unpack_invoke().