Blender: fluidsim.c File Reference
fluidsim.c File Reference
blenkernel
#include <stdlib.h>
#include <zlib.h>
#include <string.h>
#include <stdio.h>
#include "MEM_guardedalloc.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_fluidsim.h"
#include "DNA_object_force.h"
#include "DNA_object_types.h"
#include "DNA_particle_types.h"
#include "DNA_scene_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_customdata.h"
#include "BKE_DerivedMesh.h"
#include "BKE_fluidsim.h"
#include "BKE_global.h"
#include "BKE_modifier.h"
#include "BKE_mesh.h"
Functions
void initElbeemMesh (struct Scene *scene, struct Object *ob, int *numVertices, float **vertices, int *numTriangles, int **triangles, int useGlobalCoords, int modifierIndex)
Detailed Description
Definition in file fluidsim.c.
Function Documentation
void initElbeemMesh (struct Scene * scene, struct Object * ob, int * numVertices, float ** vertices, int * numTriangles, int ** triangles, int useGlobalCoords, int modifierIndex)
Definition at line 68 of file fluidsim.c.
References CD_MASK_BAREMESH, co, copy_v3_v3(), DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, DerivedMesh::getTessFaceArray, DerivedMesh::getVertArray, i, MEM_callocN(), mesh_create_derived_index_render(), mul_m4_v3(), NULL, Object::obmat, DerivedMesh::release, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.