Blender: BSP_MEdge Class Reference
BSP_MEdge Class Reference
#include <BSP_MeshPrimitives.h>
Public Member Functions
BSP_MEdge ()
bool operator== (BSP_MEdge &rhs)
void SwapFace (BSP_FaceInd old_f, BSP_FaceInd new_f)
BSP_VertexInd OpVertex (BSP_VertexInd vi) const
bool SelectTag () const
void SetSelectTag (bool tag)
int OpenTag () const
void SetOpenTag (int tag)
Public Attributes
BSP_VertexInd m_verts [2]
BSP_FaceList m_faces
Detailed Description
Definition at line 174 of file BSP_MeshPrimitives.h.
Constructor & Destructor Documentation
BSP_MEdge::BSP_MEdge ()
Edge Primitive Methods.
Definition at line 139 of file BSP_MeshPrimitives.cpp.
References CTR_TaggedIndex< 24, 0x00ffffff >::Empty(), and m_verts.
Member Function Documentation
int BSP_MEdge::OpenTag () const
We use one of the vertex indices for tag informtaion. This means these tags will not survive if you change the vertex indices.
Definition at line 220 of file BSP_MeshPrimitives.cpp.
References m_verts, and CTR_TaggedIndex< tag_shift, index_mask >::Tag().
bool BSP_MEdge::operator== (BSP_MEdge & rhs)
Definition at line 146 of file BSP_MeshPrimitives.cpp.
References m_verts.
BSP_VertexInd BSP_MEdge::OpVertex (BSP_VertexInd vi) const
Definition at line 192 of file BSP_MeshPrimitives.cpp.
References e_mesh_error, CTR_TaggedIndex< 24, 0x00ffffff >::Empty(), m_verts, and MT_assert.
bool BSP_MEdge::SelectTag () const
Definition at line 206 of file BSP_MeshPrimitives.cpp.
References m_verts.
void BSP_MEdge::SetOpenTag (int tag)
Definition at line 227 of file BSP_MeshPrimitives.cpp.
References m_verts, and CTR_TaggedIndex< tag_shift, index_mask >::SetTag().
void BSP_MEdge::SetSelectTag (bool tag)
Definition at line 212 of file BSP_MeshPrimitives.cpp.
References m_verts, and CTR_TaggedIndex< tag_shift, index_mask >::SetTag().
void BSP_MEdge::SwapFace (BSP_FaceInd old_f, BSP_FaceInd new_f)
Definition at line 175 of file BSP_MeshPrimitives.cpp.
References e_mesh_error, find(), m_faces, and MT_assert.
Member Data Documentation
BSP_FaceList BSP_MEdge::m_faces
Definition at line 177 of file BSP_MeshPrimitives.h.
Referenced by SwapFace(), and LOD_ManMesh2::VertexFaces().
BSP_VertexInd BSP_MEdge::m_verts[2]
Definition at line 176 of file BSP_MeshPrimitives.h.
Referenced by BSP_MEdge(), BSP_CSGMesh::FindEdge(), OpenTag(), operator==(), OpVertex(), SelectTag(), SetOpenTag(), and SetSelectTag().
The documentation for this class was generated from the following files:
BSP_MeshPrimitives.h
BSP_MeshPrimitives.cpp