Blender: uiWidgetType Struct Reference
uiWidgetType Struct Reference
Public Attributes
uiWidgetColors * wcol_theme
uiWidgetStateColors * wcol_state
uiWidgetColors wcol
void(* state)(struct uiWidgetType *, int state)
void(* draw)(uiWidgetColors *, rcti *, int state, int roundboxalign)
void(* custom)(uiBut *, uiWidgetColors *, rcti *, int state, int roundboxalign)
void(* text)(uiFontStyle *, uiWidgetColors *, uiBut *, rcti *)
Detailed Description
Definition at line 111 of file interface_widgets.c.
Member Data Documentation
void(* uiWidgetType::custom)(uiBut *, uiWidgetColors *, rcti *, int state, int roundboxalign)
Definition at line 122 of file interface_widgets.c.
Referenced by ui_draw_but(), and widget_type().
void(* uiWidgetType::draw)(uiWidgetColors *, rcti *, int state, int roundboxalign)
Definition at line 121 of file interface_widgets.c.
Referenced by ui_draw_but(), ui_draw_menu_back(), ui_draw_menu_item(), ui_draw_preview_item(), ui_draw_search_back(), ui_draw_tooltip_background(), and widget_type().
void(* uiWidgetType::state)(struct uiWidgetType *, int state)
Definition at line 120 of file interface_widgets.c.
Referenced by ui_draw_but(), ui_draw_menu_back(), ui_draw_menu_item(), ui_draw_preview_item(), ui_draw_search_back(), ui_draw_tooltip_background(), and widget_type().
void(* uiWidgetType::text)(uiFontStyle *, uiWidgetColors *, uiBut *, rcti *)
Definition at line 123 of file interface_widgets.c.
Referenced by ui_draw_but(), and widget_type().
uiWidgetColors uiWidgetType::wcol
Definition at line 118 of file interface_widgets.c.
Referenced by ui_draw_but(), ui_draw_menu_back(), ui_draw_menu_item(), ui_draw_preview_item(), ui_draw_search_back(), ui_draw_tooltip_background(), widget_draw_extra_mask(), widget_state(), widget_state_label(), widget_state_menu_item(), widget_state_nothing(), widget_state_numslider(), widget_state_option_menu(), and widget_state_pulldown().
uiWidgetStateColors* uiWidgetType::wcol_state
Definition at line 115 of file interface_widgets.c.
Referenced by widget_state(), widget_state_numslider(), and widget_type().
uiWidgetColors* uiWidgetType::wcol_theme
Definition at line 114 of file interface_widgets.c.
Referenced by ui_draw_but(), ui_tooltip_get_theme(), widget_draw_extra_mask(), widget_state(), widget_state_menu_item(), widget_state_nothing(), widget_state_pulldown(), and widget_type().
The documentation for this struct was generated from the following file:
interface_widgets.c