Blender: AnimationImporter.cpp File Reference
AnimationImporter.cpp File Reference
COLLADA
#include <stddef.h>
#include "COLLADABUPlatform.h"
#include "DNA_armature_types.h"
#include "ED_keyframing.h"
#include "BLI_listbase.h"
#include "BLI_math.h"
#include "BLI_path_util.h"
#include "BLI_string.h"
#include "BKE_action.h"
#include "BKE_armature.h"
#include "BKE_fcurve.h"
#include "BKE_object.h"
#include "MEM_guardedalloc.h"
#include "collada_utils.h"
#include "AnimationImporter.h"
#include "ArmatureImporter.h"
#include "MaterialExporter.h"
#include <algorithm>
Functions
template<class T >
static const char * bc_get_joint_name (T *node)
Detailed Description
Definition in file AnimationImporter.cpp.
Function Documentation
template<class T > static const char* bc_get_joint_name (T * node) [static]
Definition at line 57 of file AnimationImporter.cpp.
Referenced by AnimationImporter::add_bone_animation_sampled(), AnimationImporter::add_bone_fcurve(), AnimationImporter::apply_matrix_curves(), AnimationImporter::translate_animation_OLD(), and AnimationImporter::translate_Animations().