Blender: node_color.h File Reference
node_color.h File Reference
Functions
float color_srgb_to_scene_linear (float c)
float color_scene_linear_to_srgb (float c)
color color_srgb_to_scene_linear (color c)
color color_scene_linear_to_srgb (color c)
color rgb_to_hsv (color rgb)
color hsv_to_rgb (color hsv)
Function Documentation
float color_scene_linear_to_srgb (float c)
Definition at line 27 of file node_color.h.
References pow().
Referenced by color_scene_linear_to_srgb(), and film_map().
color color_scene_linear_to_srgb (color c)
Definition at line 43 of file node_color.h.
References color_scene_linear_to_srgb().
float color_srgb_to_scene_linear (float c)
Definition at line 19 of file node_color.h.
References pow().
Referenced by color_srgb_to_scene_linear(), create_mesh(), svm_node_tex_environment(), and svm_node_tex_image().
color color_srgb_to_scene_linear (color c)
Definition at line 35 of file node_color.h.
References color_srgb_to_scene_linear().
color hsv_to_rgb (color hsv)
Definition at line 91 of file node_color.h.
References i, and p.
color rgb_to_hsv (color rgb)
Definition at line 53 of file node_color.h.
References max, and min.