Blender: KX_WorldIpoController Class Reference
KX_WorldIpoController Class Reference
#include <KX_WorldIpoController.h>
Public Member Functions
KX_WorldIpoController ()
virtual ~KX_WorldIpoController ()
virtual SG_Controller * GetReplica (class SG_Node *destnode)
virtual bool Update (double time)
virtual void SetSimulatedTime (double time)
void SetModifyMistStart (bool modify)
void SetModifyMistColor (bool modify)
void SetModifyMistDist (bool modify)
void SetOption (int option, int value)
void AddInterpolator (KX_IInterpolator *interp)
Public Attributes
MT_Scalar m_mist_rgb [3]
MT_Scalar m_mist_start
MT_Scalar m_mist_dist
Detailed Description
Definition at line 39 of file KX_WorldIpoController.h.
Constructor & Destructor Documentation
KX_WorldIpoController::KX_WorldIpoController () [inline]
Definition at line 56 of file KX_WorldIpoController.h.
Referenced by GetReplica().
KX_WorldIpoController::~KX_WorldIpoController () [virtual]
Definition at line 110 of file KX_WorldIpoController.cpp.
References i.
Member Function Documentation
void KX_WorldIpoController::AddInterpolator (KX_IInterpolator * interp)
Definition at line 75 of file KX_WorldIpoController.cpp.
Referenced by BL_ConvertWorldIpos(), and GetReplica().
SG_Controller * KX_WorldIpoController::GetReplica (class SG_Node * destnode) [virtual]
Implements SG_Controller.
Definition at line 81 of file KX_WorldIpoController.cpp.
References AddInterpolator(), SG_Controller::ClearObject(), i, KX_WorldIpoController(), and KX_ScalarInterpolator::SetNewTarget().
void KX_WorldIpoController::SetModifyMistColor (bool modify) [inline]
Definition at line 79 of file KX_WorldIpoController.h.
Referenced by BL_ConvertWorldIpos().
void KX_WorldIpoController::SetModifyMistDist (bool modify) [inline]
Definition at line 83 of file KX_WorldIpoController.h.
Referenced by BL_ConvertWorldIpos().
void KX_WorldIpoController::SetModifyMistStart (bool modify) [inline]
Definition at line 75 of file KX_WorldIpoController.h.
Referenced by BL_ConvertWorldIpos().
void KX_WorldIpoController::SetOption (int option, int value) [inline, virtual]
Hacky way of passing options to specific controllers
Parameters:
option An integer identifying the option.
value The value of this option.
Attention:
This has been placed here to give sca-elements
some control over the controllers. This is
necessary because the identity of the controller
is lost on the way here.
Implements SG_Controller.
Definition at line 88 of file KX_WorldIpoController.h.
virtual void KX_WorldIpoController::SetSimulatedTime (double time) [inline, virtual]
Implements SG_Controller.
Definition at line 70 of file KX_WorldIpoController.h.
bool KX_WorldIpoController::Update (double time) [virtual]
Implements SG_Controller.
Definition at line 43 of file KX_WorldIpoController.cpp.
References i, m_mist_dist, m_mist_rgb, m_mist_start, NULL, KX_WorldInfo::setMistColorBlue(), KX_WorldInfo::setMistColorGreen(), KX_WorldInfo::setMistColorRed(), KX_WorldInfo::setMistDistance(), and KX_WorldInfo::setMistStart().
Member Data Documentation
MT_Scalar KX_WorldIpoController::m_mist_dist
Definition at line 44 of file KX_WorldIpoController.h.
Referenced by BL_ConvertWorldIpos(), and Update().
MT_Scalar KX_WorldIpoController::m_mist_rgb[3]
Definition at line 42 of file KX_WorldIpoController.h.
Referenced by BL_ConvertWorldIpos(), and Update().
MT_Scalar KX_WorldIpoController::m_mist_start
Definition at line 43 of file KX_WorldIpoController.h.
Referenced by BL_ConvertWorldIpos(), and Update().
The documentation for this class was generated from the following files:
KX_WorldIpoController.h
KX_WorldIpoController.cpp