Blender: KX_TrackToActuator Class Reference
KX_TrackToActuator Class Reference
#include <KX_TrackToActuator.h>
Public Member Functions
KX_TrackToActuator (SCA_IObject *gameobj, SCA_IObject *ob, int time, bool threedee, int trackflag, int upflag)
virtual ~KX_TrackToActuator ()
virtual CValue * GetReplica ()
virtual void ProcessReplica ()
virtual bool UnlinkObject (SCA_IObject *clientobj)
virtual void Relink (CTR_Map< CTR_HashedPtr, void * > *obj_map)
virtual bool Update (double curtime, bool frame)
Detailed Description
Definition at line 41 of file KX_TrackToActuator.h.
Constructor & Destructor Documentation
KX_TrackToActuator::KX_TrackToActuator (SCA_IObject * gameobj, SCA_IObject * ob, int time, bool threedee, int trackflag, int upflag)
Definition at line 55 of file KX_TrackToActuator.cpp.
References SG_Spatial::GetLocalOrientation(), KX_GameObject::GetParent(), KX_GameObject::GetSGNode(), SCA_IObject::RegisterActuator(), and CValue::Release().
Referenced by GetReplica().
KX_TrackToActuator::~KX_TrackToActuator () [virtual]
Definition at line 186 of file KX_TrackToActuator.cpp.
References SCA_IObject::UnregisterActuator().
Member Function Documentation
virtual CValue* KX_TrackToActuator::GetReplica (void) [inline, virtual]
Implements CValue.
Definition at line 61 of file KX_TrackToActuator.h.
References KX_TrackToActuator(), and ProcessReplica().
void KX_TrackToActuator::ProcessReplica () [virtual]
Makes sure any internal data owned by this class is deep copied.
Reimplemented from SCA_IActuator.
Definition at line 194 of file KX_TrackToActuator.cpp.
References SCA_IObject::RegisterActuator().
Referenced by GetReplica().
void KX_TrackToActuator::Relink (CTR_Map< CTR_HashedPtr, void * > * obj_map) [virtual]
Reimplemented from SCA_ILogicBrick.
Definition at line 221 of file KX_TrackToActuator.cpp.
References SCA_IObject::RegisterActuator(), and SCA_IObject::UnregisterActuator().
bool KX_TrackToActuator::UnlinkObject (SCA_IObject * clientobj) [virtual]
UnlinkObject(...) Certain actuator use gameobject pointers (like TractTo actuator) This function can be called when an object is removed to make sure that the actuator will not use it anymore.
Reimplemented from SCA_IActuator.
Definition at line 205 of file KX_TrackToActuator.cpp.
References NULL.
bool KX_TrackToActuator::Update (double curtime, bool frame) [virtual]
Update(...) Update the actuator based upon the events received since the last call to Update, the current time and deltatime the time elapsed in this frame ? It is the responsibility of concrete Actuators to clear their event's. This is usually done in the Update() method via a call to RemoveAllEvents()
Reimplemented from SCA_IActuator.
Definition at line 241 of file KX_TrackToActuator.cpp.
References MT_Vector3::cross(), MT_Vector3::dot(), SG_Spatial::GetLocalPosition(), SCA_ILogicBrick::GetParent(), KX_GameObject::GetSGNode(), MT_Matrix3x3::inverse(), SCA_IActuator::IsNegativeEvent(), left(), MT_Vector3::length2(), matrix3x3_interpol(), KX_GameObject::NodeGetWorldOrientation(), KX_GameObject::NodeGetWorldPosition(), KX_GameObject::NodeSetLocalOrientation(), KX_GameObject::NodeSetLocalPosition(), MT_Vector3::normalize(), SCA_IActuator::RemoveAllEvents(), MT_Vector3::safe_normalized(), MT_Matrix3x3::setValue(), and MT_Tuple3::setValue().
The documentation for this class was generated from the following files:
KX_TrackToActuator.h
KX_TrackToActuator.cpp