Blender: info_stats.c File Reference
info_stats.c File Reference
info space
#include <stdio.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_armature_types.h"
#include "DNA_curve_types.h"
#include "DNA_group_types.h"
#include "DNA_lattice_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meta_types.h"
#include "DNA_scene_types.h"
#include "BLI_utildefines.h"
#include "BKE_anim.h"
#include "BKE_blender.h"
#include "BKE_curve.h"
#include "BKE_displist.h"
#include "BKE_DerivedMesh.h"
#include "BKE_key.h"
#include "BKE_mesh.h"
#include "BKE_particle.h"
#include "BKE_tessmesh.h"
#include "ED_info.h"
#include "ED_armature.h"
#include "ED_mesh.h"
Classes
struct SceneStats
Typedefs
typedef struct SceneStats SceneStats
Functions
static void stats_object (Object *ob, int sel, int totob, SceneStats *stats)
static void stats_object_edit (Object *obedit, SceneStats *stats)
static void stats_object_pose (Object *ob, SceneStats *stats)
static void stats_dupli_object (Base *base, Object *ob, SceneStats *stats)
static void stats_update (Scene *scene)
static void stats_string (Scene *scene)
void ED_info_stats_clear (Scene *scene)
const char * ED_info_stats_string (Scene *scene)
Detailed Description
Definition in file info_stats.c.
Typedef Documentation
typedef struct SceneStats SceneStats
Function Documentation
void ED_info_stats_clear (Scene * scene)
Definition at line 397 of file info_stats.c.
References MEM_freeN(), NULL, and Scene::stats.
Referenced by wm_event_do_notifiers().
const char* ED_info_stats_string (Scene * scene)
Definition at line 405 of file info_stats.c.
References SceneStats::infostr, Scene::stats, stats_string(), and stats_update().
static void stats_dupli_object (Base * base, Object * ob, SceneStats * stats) [static]
Definition at line 254 of file info_stats.c.
References count_duplilist(), count_particles(), count_particles_mod(), ParticleSettings::draw_as, ParticleSettings::dup_group, Object::dup_group, ParticleSettings::dup_ob, ListBase::first, Base::flag, Group::gobject, GroupObject::next, ParticleSystem::next, GroupObject::ob, OB_DUPLIFACES, OB_DUPLIFRAMES, OB_DUPLIGROUP, OB_DUPLIPARTS, OB_DUPLIVERTS, Object::parent, ParticleSystem::part, PART_DRAW_GR, PART_DRAW_OB, Object::particlesystem, SELECT, stats_object(), SceneStats::totobj, SceneStats::totobjsel, and Object::transflag.
Referenced by stats_update().
static void stats_object (Object * ob, int sel, int totob, SceneStats * stats) [static]
Definition at line 69 of file info_stats.c.
References count_displist(), Object::derivedFinal, Object::disp, ListBase::first, DerivedMesh::getNumEdges, DerivedMesh::getNumPolys, DerivedMesh::getNumVerts, OB_CURVE, OB_FONT, OB_LAMP, OB_MBALL, OB_MESH, OB_SURF, SceneStats::totcurve, SceneStats::totedge, SceneStats::totface, SceneStats::totfacesel, SceneStats::totlamp, SceneStats::totmesh, SceneStats::totvert, SceneStats::totvertsel, and Object::type.
Referenced by stats_dupli_object().
static void stats_object_edit (Object * obedit, SceneStats * stats) [static]
Definition at line 140 of file info_stats.c.
References Nurb::bezt, BMEditMesh::bm, BMEdit_FromObject(), BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, Nurb::bp, CU_BEZIER, curve_editnurbs(), Object::data, Lattice::def, bArmature::edbo, MetaBall::editelems, Lattice::editlatt, ELEM, BezTriple::f1, BPoint::f1, BezTriple::f2, BezTriple::f3, ListBase::first, EditBone::flag, MetaElem::flag, EditLatt::latt, MetaElem::next, Nurb::next, EditBone::next, OB_ARMATURE, OB_CURVE, OB_LATTICE, OB_MBALL, OB_MESH, OB_SURF, EditBone::parent, Nurb::pntsu, Lattice::pntsu, Nurb::pntsv, Lattice::pntsv, Lattice::pntsw, SELECT, SceneStats::totbone, SceneStats::totbonesel, BMesh::totedge, SceneStats::totedge, BMesh::totedgesel, SceneStats::totedgesel, BMesh::totface, SceneStats::totface, BMesh::totfacesel, SceneStats::totfacesel, BMesh::totvert, SceneStats::totvert, BMesh::totvertsel, SceneStats::totvertsel, Object::type, and Nurb::type.
Referenced by stats_update().
static void stats_object_pose (Object * ob, SceneStats * stats) [static]
Definition at line 239 of file info_stats.c.
References bPoseChannel::bone, BONE_SELECTED, bPose::chanbase, Object::data, ListBase::first, Bone::flag, Bone::layer, bArmature::layer, bPoseChannel::next, Object::pose, SceneStats::totbone, and SceneStats::totbonesel.
Referenced by stats_update().
static void stats_string (Scene * scene) [static]
Definition at line 341 of file info_stats.c.
References Scene::basact, Object::id, SceneStats::infostr, MEM_get_mapped_memory_in_use(), MEM_get_memory_in_use(), mem_in_use, mmap_in_use, Object::mode, ID::name, NULL, OB_ARMATURE, ob_get_keyblock(), OB_MESH, OB_MODE_POSE, Scene::obedit, Base::object, SCE_SELECT_EDGE, SCE_SELECT_VERTEX, ToolSettings::selectmode, Scene::stats, Scene::toolsettings, SceneStats::totbone, SceneStats::totbonesel, SceneStats::totedge, SceneStats::totedgesel, SceneStats::totface, SceneStats::totfacesel, SceneStats::totlamp, SceneStats::totobj, SceneStats::totobjsel, SceneStats::totvert, SceneStats::totvertsel, Object::type, and versionstr.
Referenced by ED_info_stats_string().
static void stats_update (Scene * scene) [static]
Definition at line 314 of file info_stats.c.
References Scene::basact, Scene::base, ListBase::first, if(), Scene::lay, MEM_callocN(), Object::mode, NULL, OB_MODE_POSE, Scene::obedit, Base::object, Scene::stats, stats_dupli_object(), stats_object_edit(), and stats_object_pose().
Referenced by ED_info_stats_string().