Blender: EffectExporter.cpp File Reference
EffectExporter.cpp File Reference
COLLADA
#include <map>
#include "COLLADASWEffectProfile.h"
#include "EffectExporter.h"
#include "MaterialExporter.h"
#include "DNA_mesh_types.h"
#include "DNA_texture_types.h"
#include "DNA_world_types.h"
#include "BKE_customdata.h"
#include "collada_internal.h"
#include "collada_utils.h"
Functions
static std::string getActiveUVLayerName (Object *ob)
Detailed Description
Definition in file EffectExporter.cpp.
Function Documentation
static std::string getActiveUVLayerName (Object * ob) [static]
Definition at line 46 of file EffectExporter.cpp.
References bc_CustomData_get_active_layer_name(), CD_MTFACE, CustomData_number_of_layers(), Object::data, and Mesh::fdata.
Referenced by EffectsExporter::operator()().