Blender: pluginapi.c File Reference
pluginapi.c File Reference
#include "blenpluginapi/util.h"
#include "iff.h"
#include "plugin.h"
#include "MEM_guardedalloc.h"
#include "BLO_sys_types.h"
#include "BLI_blenlib.h"
#include "BLI_threads.h"
#include "IMB_imbuf.h"
Defines
#define PLUGIN_INTERN
#define GET_INT_FROM_POINTER(i) ((int)(intptr_t)(i))
Functions
LIBEXPORT void * mallocN (int len, char *str)
LIBEXPORT void * callocN (int len, char *str)
LIBEXPORT short freeN (void *vmemh)
LIBEXPORT void * mallocT (int len, char *str)
LIBEXPORT void * callocT (int len, char *str)
LIBEXPORT void freeT (void *vmemh)
LIBEXPORT struct ImBuf * allocImBuf (short x, short y, uchar d, uint flags)
LIBEXPORT struct ImBuf * dupImBuf (struct ImBuf *ib)
LIBEXPORT void freeImBuf (struct ImBuf *ib)
LIBEXPORT short saveiff (struct ImBuf *ib, char *c, int i)
LIBEXPORT struct ImBuf * loadifffile (int a, int b)
LIBEXPORT struct ImBuf * loadiffname (char *n, int flags)
LIBEXPORT struct ImBuf * testiffname (char *n, int flags)
LIBEXPORT struct ImBuf * onehalf (struct ImBuf *ib)
LIBEXPORT struct ImBuf * half_x (struct ImBuf *ib)
LIBEXPORT struct ImBuf * half_y (struct ImBuf *ib)
LIBEXPORT struct ImBuf * double_x (struct ImBuf *ib)
LIBEXPORT struct ImBuf * double_y (struct ImBuf *ib)
LIBEXPORT struct ImBuf * double_fast_x (struct ImBuf *ib)
LIBEXPORT struct ImBuf * double_fast_y (struct ImBuf *ib)
LIBEXPORT int ispic (char *name)
LIBEXPORT struct ImBuf * scaleImBuf (struct ImBuf *ib, short nx, short ny)
LIBEXPORT struct ImBuf * scalefastImBuf (struct ImBuf *ib, short x, short y)
LIBEXPORT void interlace (struct ImBuf *ibuf)
LIBEXPORT void de_interlace (struct ImBuf *ib)
LIBEXPORT float hnoise (float noisesize, float x, float y, float z)
LIBEXPORT float hnoisep (float noisesize, float x, float y, float z)
LIBEXPORT float turbulence (float noisesize, float x, float y, float z, int depth)
LIBEXPORT float turbulence1 (float noisesize, float x, float y, float z, int depth)
int pluginapi_force_ref (void)
Detailed Description
Definition in file pluginapi.c.
Define Documentation
#define GET_INT_FROM_POINTER (i) ((int)(intptr_t)(i))
Definition at line 61 of file pluginapi.c.
Referenced by pluginapi_force_ref().
#define PLUGIN_INTERN
Definition at line 44 of file pluginapi.c.
Function Documentation
LIBEXPORT struct ImBuf* allocImBuf (short x, short y, uchar d, uint flags) [read]
Definition at line 104 of file pluginapi.c.
References IMB_allocImBuf().
Referenced by pluginapi_force_ref().
LIBEXPORT void* callocN (int len, char * str)
Definition at line 72 of file pluginapi.c.
References MEM_callocN().
Referenced by pluginapi_force_ref().
LIBEXPORT void* callocT (int len, char * str)
Definition at line 88 of file pluginapi.c.
References MEM_callocN().
Referenced by pluginapi_force_ref().
LIBEXPORT void de_interlace (struct ImBuf * ib)
Definition at line 214 of file pluginapi.c.
References IMB_de_interlace().
Referenced by pluginapi_force_ref().
LIBEXPORT struct ImBuf* double_fast_x (struct ImBuf * ib) [read]
Definition at line 173 of file pluginapi.c.
References IMB_double_fast_x().
Referenced by pluginapi_force_ref().
LIBEXPORT struct ImBuf* double_fast_y (struct ImBuf * ib) [read]
Definition at line 178 of file pluginapi.c.
References IMB_double_fast_y().
Referenced by pluginapi_force_ref().
LIBEXPORT struct ImBuf* double_x (struct ImBuf * ib) [read]
Definition at line 163 of file pluginapi.c.
References IMB_double_x().
Referenced by pluginapi_force_ref().
LIBEXPORT struct ImBuf* double_y (struct ImBuf * ib) [read]
Definition at line 168 of file pluginapi.c.
References IMB_double_y().
Referenced by pluginapi_force_ref().
LIBEXPORT struct ImBuf* dupImBuf (struct ImBuf * ib) [read]
Definition at line 113 of file pluginapi.c.
References IMB_dupImBuf().
Referenced by pluginapi_force_ref().
LIBEXPORT void freeImBuf (struct ImBuf * ib)
Definition at line 118 of file pluginapi.c.
References IMB_freeImBuf().
Referenced by pluginapi_force_ref().
LIBEXPORT short freeN (void * vmemh)
Definition at line 77 of file pluginapi.c.
References MEM_freeN().
Referenced by pluginapi_force_ref().
LIBEXPORT void freeT (void * vmemh)
Definition at line 93 of file pluginapi.c.
References MEM_freeN().
Referenced by pluginapi_force_ref().
LIBEXPORT struct ImBuf* half_x (struct ImBuf * ib) [read]
Definition at line 153 of file pluginapi.c.
References IMB_half_x().
Referenced by pluginapi_force_ref().
LIBEXPORT struct ImBuf* half_y (struct ImBuf * ib) [read]
Definition at line 158 of file pluginapi.c.
References IMB_half_y().
Referenced by pluginapi_force_ref().
LIBEXPORT float hnoise (float noisesize, float x, float y, float z)
Definition at line 230 of file pluginapi.c.
References BLI_hnoise().
Referenced by pluginapi_force_ref().
LIBEXPORT float hnoisep (float noisesize, float x, float y, float z)
Definition at line 238 of file pluginapi.c.
References BLI_hnoisep().
Referenced by pluginapi_force_ref().
LIBEXPORT void interlace (struct ImBuf * ibuf)
Definition at line 209 of file pluginapi.c.
References IMB_interlace().
LIBEXPORT int ispic (char * name)
Definition at line 183 of file pluginapi.c.
References IMB_ispic().
Referenced by pluginapi_force_ref().
LIBEXPORT struct ImBuf* loadifffile (int a, int b) [read]
Definition at line 130 of file pluginapi.c.
References IMB_loadifffile().
Referenced by pluginapi_force_ref().
LIBEXPORT struct ImBuf* loadiffname (char * n, int flags) [read]
Definition at line 136 of file pluginapi.c.
References IMB_loadiffname().
Referenced by pluginapi_force_ref().
LIBEXPORT void* mallocN (int len, char * str)
Definition at line 67 of file pluginapi.c.
References MEM_mallocN().
Referenced by pluginapi_force_ref().
LIBEXPORT void* mallocT (int len, char * str)
Definition at line 83 of file pluginapi.c.
References MEM_mallocN().
Referenced by pluginapi_force_ref().
LIBEXPORT struct ImBuf* onehalf (struct ImBuf * ib) [read]
Definition at line 148 of file pluginapi.c.
References IMB_onehalf().
Referenced by pluginapi_force_ref().
int pluginapi_force_ref (void)
Definition at line 273 of file pluginapi.c.
References allocImBuf(), callocN(), callocT(), de_interlace(), double_fast_x(), double_fast_y(), double_x(), double_y(), dupImBuf(), freeImBuf(), freeN(), freeT(), GET_INT_FROM_POINTER, half_x(), half_y(), hnoise(), hnoisep(), interlace(), ispic(), loadifffile(), loadiffname(), mallocN(), mallocT(), onehalf(), saveiff(), scalefastImBuf(), scaleImBuf(), testiffname(), turbulence(), and turbulence1().
Referenced by main().
LIBEXPORT short saveiff (struct ImBuf * ib, char * c, int i)
Definition at line 123 of file pluginapi.c.
References IMB_saveiff().
Referenced by pluginapi_force_ref().
LIBEXPORT struct ImBuf* scalefastImBuf (struct ImBuf * ib, short x, short y) [read]
Definition at line 198 of file pluginapi.c.
References IMB_scalefastImBuf().
Referenced by pluginapi_force_ref().
LIBEXPORT struct ImBuf* scaleImBuf (struct ImBuf * ib, short nx, short ny) [read]
Definition at line 191 of file pluginapi.c.
References IMB_scaleImBuf().
Referenced by pluginapi_force_ref().
LIBEXPORT struct ImBuf* testiffname (char * n, int flags) [read]
Definition at line 142 of file pluginapi.c.
References IMB_testiffname().
Referenced by pluginapi_force_ref().
LIBEXPORT float turbulence (float noisesize, float x, float y, float z, int depth)
Definition at line 246 of file pluginapi.c.
References BLI_turbulence().
Referenced by pluginapi_force_ref().
LIBEXPORT float turbulence1 (float noisesize, float x, float y, float z, int depth)
Definition at line 255 of file pluginapi.c.
References BLI_turbulence1().
Referenced by pluginapi_force_ref().