Blender: rectop.c File Reference
rectop.c File Reference
IMage Buffer
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "imbuf.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_allocimbuf.h"
Functions
static void blend_color_mix (char *cp, char *cp1, char *cp2, int fac)
static void blend_color_add (char *cp, char *cp1, char *cp2, int fac)
static void blend_color_sub (char *cp, char *cp1, char *cp2, int fac)
static void blend_color_mul (char *cp, char *cp1, char *cp2, int fac)
static void blend_color_lighten (char *cp, char *cp1, char *cp2, int fac)
static void blend_color_darken (char *cp, char *cp1, char *cp2, int fac)
unsigned int IMB_blend_color (unsigned int src1, unsigned int src2, int fac, IMB_BlendMode mode)
static void blend_color_mix_float (float *cp, float *cp1, float *cp2, float fac)
static void blend_color_add_float (float *cp, float *cp1, float *cp2, float fac)
static void blend_color_sub_float (float *cp, float *cp1, float *cp2, float fac)
static void blend_color_mul_float (float *cp, float *cp1, float *cp2, float fac)
static void blend_color_lighten_float (float *cp, float *cp1, float *cp2, float fac)
static void blend_color_darken_float (float *cp, float *cp1, float *cp2, float fac)
void IMB_blend_color_float (float *dst, float *src1, float *src2, float fac, IMB_BlendMode mode)
void IMB_rectclip (struct ImBuf *dbuf, struct ImBuf *sbuf, int *destx, int *desty, int *srcx, int *srcy, int *width, int *height)
void IMB_rectcpy (struct ImBuf *dbuf, struct ImBuf *sbuf, int destx, int desty, int srcx, int srcy, int width, int height)
void IMB_rectblend (struct ImBuf *dbuf, struct ImBuf *sbuf, int destx, int desty, int srcx, int srcy, int width, int height, IMB_BlendMode mode)
void IMB_rectfill (struct ImBuf *drect, const float col[4])
void buf_rectfill_area (unsigned char *rect, float *rectf, int width, int height, const float col[4], int x1, int y1, int x2, int y2)
void IMB_rectfill_area (struct ImBuf *ibuf, float *col, int x1, int y1, int x2, int y2)
void IMB_rectfill_alpha (ImBuf *ibuf, const float value)
Detailed Description
Definition in file rectop.c.
Function Documentation
static void blend_color_add (char * cp, char * cp1, char * cp2, int fac) [static]
Definition at line 59 of file rectop.c.
Referenced by IMB_blend_color().
static void blend_color_add_float (float * cp, float * cp1, float * cp2, float fac) [static]
Definition at line 171 of file rectop.c.
Referenced by IMB_blend_color_float().
static void blend_color_darken (char * cp, char * cp1, char * cp2, int fac) [static]
Definition at line 106 of file rectop.c.
References blend_color_mix().
Referenced by IMB_blend_color().
static void blend_color_darken_float (float * cp, float * cp1, float * cp2, float fac) [static]
Definition at line 215 of file rectop.c.
References blend_color_mix_float().
Referenced by IMB_blend_color_float().
static void blend_color_lighten (char * cp, char * cp1, char * cp2, int fac) [static]
Definition at line 93 of file rectop.c.
References blend_color_mix().
Referenced by IMB_blend_color().
static void blend_color_lighten_float (float * cp, float * cp1, float * cp2, float fac) [static]
Definition at line 202 of file rectop.c.
References blend_color_mix_float().
Referenced by IMB_blend_color_float().
static void blend_color_mix (char * cp, char * cp1, char * cp2, int fac) [static]
Definition at line 47 of file rectop.c.
Referenced by blend_color_darken(), blend_color_lighten(), and IMB_blend_color().
static void blend_color_mix_float (float * cp, float * cp1, float * cp2, float fac) [static]
Definition at line 163 of file rectop.c.
Referenced by blend_color_darken_float(), blend_color_lighten_float(), and IMB_blend_color_float().
static void blend_color_mul (char * cp, char * cp1, char * cp2, int fac) [static]
Definition at line 83 of file rectop.c.
Referenced by IMB_blend_color().
static void blend_color_mul_float (float * cp, float * cp1, float * cp2, float fac) [static]
Definition at line 193 of file rectop.c.
Referenced by IMB_blend_color_float().
static void blend_color_sub (char * cp, char * cp1, char * cp2, int fac) [static]
Definition at line 71 of file rectop.c.
Referenced by IMB_blend_color().
static void blend_color_sub_float (float * cp, float * cp1, float * cp2, float fac) [static]
Definition at line 182 of file rectop.c.
Referenced by IMB_blend_color_float().
void buf_rectfill_area (unsigned char * rect, float * rectf, int width, int height, const float col[4], int x1, int y1, int x2, int y2)
Definition at line 484 of file rectop.c.
References CLAMP(), fb(), FTOCHAR, i, and SWAP.
Referenced by BKE_stamp_buf(), and IMB_rectfill_area().
unsigned int IMB_blend_color (unsigned int src1, unsigned int src2, int fac, IMB_BlendMode mode)
Definition at line 119 of file rectop.c.
References blend_color_add(), blend_color_darken(), blend_color_lighten(), blend_color_mix(), blend_color_mul(), blend_color_sub(), IMB_BLEND_ADD, IMB_BLEND_DARKEN, IMB_BLEND_ERASE_ALPHA, IMB_BLEND_LIGHTEN, IMB_BLEND_MIX, IMB_BLEND_MUL, and IMB_BLEND_SUB.
Referenced by do_projectpaint_clone(), do_projectpaint_draw(), and IMB_rectblend().
void IMB_blend_color_float (float * dst, float * src1, float * src2, float fac, IMB_BlendMode mode)
Definition at line 228 of file rectop.c.
References blend_color_add_float(), blend_color_darken_float(), blend_color_lighten_float(), blend_color_mix_float(), blend_color_mul_float(), blend_color_sub_float(), IMB_BLEND_ADD, IMB_BLEND_DARKEN, IMB_BLEND_ERASE_ALPHA, IMB_BLEND_LIGHTEN, IMB_BLEND_MIX, IMB_BLEND_MUL, and IMB_BLEND_SUB.
Referenced by do_projectpaint_clone_f(), do_projectpaint_draw_f(), and IMB_rectblend().
void IMB_rectblend (struct ImBuf * dbuf, struct ImBuf * sbuf, int destx, int desty, int srcx, int srcy, int width, int height, IMB_BlendMode mode)
Definition at line 324 of file rectop.c.
References ImBuf::channels, IMB_blend_color(), IMB_blend_color_float(), IMB_BLEND_COPY, IMB_BLEND_COPY_ALPHA, IMB_BLEND_COPY_RGB, IMB_rectclip(), NULL, ImBuf::rect, ImBuf::rect_float, and ImBuf::x.
Referenced by imapaint_lift_clone(), imapaint_lift_smear(), imapaint_paint_op(), IMB_rectcpy(), and ImageBuff::plot().
void IMB_rectclip (struct ImBuf * dbuf, struct ImBuf * sbuf, int * destx, int * desty, int * srcx, int * srcy, int * width, int * height)
Definition at line 269 of file rectop.c.
References NULL, ImBuf::x, and ImBuf::y.
Referenced by brush_painter_fixed_tex_partial_update(), imapaint_dirty_region(), imapaint_lift_clone(), imapaint_lift_soften(), imapaint_torus_split_region(), and IMB_rectblend().
void IMB_rectcpy (struct ImBuf * dbuf, struct ImBuf * sbuf, int destx, int desty, int srcx, int srcy, int width, int height)
Definition at line 317 of file rectop.c.
References IMB_BLEND_COPY, and IMB_rectblend().
Referenced by BKE_tracking_stabilize(), de_interlace_ng(), de_interlace_st(), envmap_split_ima(), get_area_imbuf(), IMB_de_interlace(), IMB_interlace(), input_preprocess(), my_envmap_split_ima(), RE_layer_load_from_file(), RE_WriteEnvmapResult(), save_jstjpeg(), and undo_copy_tile().
void IMB_rectfill (struct ImBuf * drect, const float col[4])
Attention:
Defined in rectop.c
Definition at line 452 of file rectop.c.
References ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by clear_images(), get_next_bake_face(), and stabilize_alloc_ibuf().
void IMB_rectfill_alpha (ImBuf * ibuf, const float value)
Definition at line 576 of file rectop.c.
References i, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by RE_bake_ibuf_filter().
void IMB_rectfill_area (struct ImBuf * ibuf, float * col, int x1, int y1, int x2, int y2)
Definition at line 569 of file rectop.c.
References buf_rectfill_area(), ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.