Blender: math_color_inline.c File Reference
math_color_inline.c File Reference
blenlib
#include "BLI_math_color.h"
#include "BLI_utildefines.h"
Defines
#define __MATH_COLOR_INLINE_C__
#define rgba_char_args_set_fl(col, r, g, b, a) rgba_char_args_set(col, r * 255, g * 255, b * 255, a * 255)
Functions
MINLINE void srgb_to_linearrgb_v3_v3 (float linear[3], const float srgb[3])
MINLINE void linearrgb_to_srgb_v3_v3 (float srgb[3], const float linear[3])
MINLINE void srgb_to_linearrgb_v4 (float linear[4], const float srgb[4])
MINLINE void linearrgb_to_srgb_v4 (float srgb[4], const float linear[4])
MINLINE void linearrgb_to_srgb_uchar3 (unsigned char srgb[3], const float linear[3])
MINLINE void linearrgb_to_srgb_uchar4 (unsigned char srgb[4], const float linear[4])
MINLINE void srgb_to_linearrgb_predivide_v4 (float linear[4], const float srgb[4])
MINLINE void linearrgb_to_srgb_predivide_v4 (float srgb[4], const float linear[4])
MINLINE unsigned short to_srgb_table_lookup (const float f)
MINLINE void linearrgb_to_srgb_ushort4 (unsigned short srgb[4], const float linear[4])
MINLINE void linearrgb_to_srgb_ushort4_predivide (unsigned short srgb[4], const float linear[4])
MINLINE void srgb_to_linearrgb_uchar4 (float linear[4], const unsigned char srgb[4])
MINLINE void srgb_to_linearrgb_uchar4_predivide (float linear[4], const unsigned char srgb[4])
MINLINE void rgba_char_args_set (char col[4], const char r, const char g, const char b, const char a)
MINLINE void rgba_char_args_test_set (char col[4], const char r, const char g, const char b, const char a)
Variables
float BLI_color_from_srgb_table [256]
unsigned short BLI_color_to_srgb_table [0x10000]
Detailed Description
Definition in file math_color_inline.c.
Define Documentation
#define __MATH_COLOR_INLINE_C__
Definition at line 35 of file math_color_inline.c.
#define rgba_char_args_set_fl (col, r, g, b, a) rgba_char_args_set(col, r * 255, g * 255, b * 255, a * 255)
Definition at line 198 of file math_color_inline.c.
Referenced by init_userdef_do_versions(), and ui_theme_init_default().
Function Documentation
MINLINE void linearrgb_to_srgb_predivide_v4 (float srgb[4], const float linear[4])
Definition at line 105 of file math_color_inline.c.
References linearrgb_to_srgb().
Referenced by IMB_buffer_byte_from_byte(), IMB_buffer_float_from_byte(), and IMB_buffer_float_from_float().
MINLINE void linearrgb_to_srgb_uchar3 (unsigned char srgb[3], const float linear[3])
Definition at line 65 of file math_color_inline.c.
References F3TOCHAR3, and linearrgb_to_srgb_v3_v3().
Referenced by bake_shade().
MINLINE void linearrgb_to_srgb_uchar4 (unsigned char srgb[4], const float linear[4])
Definition at line 73 of file math_color_inline.c.
References F4TOCHAR4, and linearrgb_to_srgb_v4().
Referenced by nodeAddToPreview().
MINLINE void linearrgb_to_srgb_ushort4 (unsigned short srgb[4], const float linear[4])
Definition at line 144 of file math_color_inline.c.
References FTOUSHORT, and to_srgb_table_lookup().
Referenced by IMB_buffer_byte_from_float(), and linearrgb_to_srgb_ushort4_predivide().
MINLINE void linearrgb_to_srgb_ushort4_predivide (unsigned short srgb[4], const float linear[4])
Definition at line 152 of file math_color_inline.c.
References FTOUSHORT, i, linearrgb_to_srgb(), linearrgb_to_srgb_ushort4(), and to_srgb_table_lookup().
Referenced by IMB_buffer_byte_from_float().
MINLINE void linearrgb_to_srgb_v3_v3 (float srgb[3], const float linear[3])
Definition at line 46 of file math_color_inline.c.
References linearrgb_to_srgb().
Referenced by add_tface_color_layer(), BlenderWorldInfo::BlenderWorldInfo(), draw_tface__set_draw_legacy(), ED_view3d_draw_offscreen(), gpu_material_to_fixed(), ibuftoimage(), image_new_exec(), image_sample_line_exec(), IMB_buffer_byte_from_float(), IMB_buffer_float_from_float(), imb_savetiff(), linearrgb_to_srgb_uchar3(), linearrgb_to_srgb_v4(), scopes_update(), ui_draw_but_COLORBAND(), ui_update_block_buts_rgb(), uiBlockPicker(), view3d_main_area_draw_objects(), and widget_swatch().
MINLINE void linearrgb_to_srgb_v4 (float srgb[4], const float linear[4])
Definition at line 59 of file math_color_inline.c.
References linearrgb_to_srgb_v3_v3().
Referenced by ED_image_draw_info(), IMB_buffer_byte_from_byte(), IMB_buffer_float_from_byte(), IMB_buffer_float_from_float(), and linearrgb_to_srgb_uchar4().
MINLINE void rgba_char_args_set (char col[4], const char r, const char g, const char b, const char a)
Definition at line 200 of file math_color_inline.c.
References g.
Referenced by init_userdef_do_versions(), ui_theme_init_boneColorSets(), and ui_theme_init_default().
MINLINE void rgba_char_args_test_set (char col[4], const char r, const char g, const char b, const char a)
Definition at line 208 of file math_color_inline.c.
References g.
Referenced by ui_theme_init_new_do().
MINLINE void srgb_to_linearrgb_predivide_v4 (float linear[4], const float srgb[4])
Definition at line 86 of file math_color_inline.c.
References srgb_to_linearrgb().
Referenced by IMB_buffer_byte_from_byte(), IMB_buffer_byte_from_float(), IMB_buffer_float_from_float(), and srgb_to_linearrgb_uchar4_predivide().
MINLINE void srgb_to_linearrgb_uchar4 (float linear[4], const unsigned char srgb[4])
Definition at line 173 of file math_color_inline.c.
References BLI_color_from_srgb_table.
Referenced by IMB_buffer_float_from_byte(), and srgb_to_linearrgb_uchar4_predivide().
MINLINE void srgb_to_linearrgb_uchar4_predivide (float linear[4], const unsigned char srgb[4])
Definition at line 181 of file math_color_inline.c.
References i, srgb_to_linearrgb_predivide_v4(), and srgb_to_linearrgb_uchar4().
Referenced by IMB_buffer_float_from_byte().
MINLINE void srgb_to_linearrgb_v3_v3 (float linear[3], const float srgb[3])
Definition at line 39 of file math_color_inline.c.
References srgb_to_linearrgb().
Referenced by brush_imbuf_new(), do_halo_tex(), do_hex_rna_cb(), do_lamp_tex(), do_material_tex(), do_projectpaint_draw_f(), do_sky_tex(), do_versions(), eyedropper_sample(), IMB_buffer_byte_from_float(), IMB_buffer_float_from_float(), multitex_nodes(), shade_input_set_shade_texco(), shade_input_set_strand_texco(), and srgb_to_linearrgb_v4().
MINLINE void srgb_to_linearrgb_v4 (float linear[4], const float srgb[4])
Definition at line 53 of file math_color_inline.c.
References srgb_to_linearrgb_v3_v3().
Referenced by IMB_buffer_byte_from_byte(), IMB_buffer_byte_from_float(), and IMB_buffer_float_from_float().
MINLINE unsigned short to_srgb_table_lookup (const float f)
Definition at line 129 of file math_color_inline.c.
References BLI_color_to_srgb_table.
Referenced by linearrgb_to_srgb_ushort4(), and linearrgb_to_srgb_ushort4_predivide().
Variable Documentation
float BLI_color_from_srgb_table[256]
Definition at line 519 of file math_color.c.
Referenced by BLI_init_srgb_conversion(), and srgb_to_linearrgb_uchar4().
unsigned short BLI_color_to_srgb_table[0x10000]
Definition at line 520 of file math_color.c.
Referenced by BLI_init_srgb_conversion(), and to_srgb_table_lookup().