Blender: volume_precache.h File Reference
volume_precache.h File Reference
Rendering
Defines
#define VOL_MS_TIMESTEP 0.1f
Functions
void global_bounds_obi (Render *re, ObjectInstanceRen *obi, float *bbmin, float *bbmax)
int point_inside_volume_objectinstance (Render *re, ObjectInstanceRen *obi, float *co)
void volume_precache (Render *re)
void free_volume_precache (Render *re)
Detailed Description
Definition in file volume_precache.h.
Define Documentation
#define VOL_MS_TIMESTEP 0.1f
Definition at line 39 of file volume_precache.h.
Referenced by ms_diffuse().
Function Documentation
void free_volume_precache (Render * re)
Definition at line 820 of file volume_precache.c.
References VolumePrecache::bbmax, VolumePrecache::bbmin, BLI_freelistN(), VolumePrecache::data_b, VolumePrecache::data_g, VolumePrecache::data_r, ListBase::first, Render::instancetable, MEM_freeN(), ObjectInstanceRen::next, NULL, ObjectInstanceRen::volume_precache, and Render::volumes.
Referenced by RE_Database_Free().
void global_bounds_obi (Render * re, ObjectInstanceRen * obi, float * bbmin, float * bbmax)
Definition at line 121 of file volume_precache.c.
References VolumePrecache::bbmax, VolumePrecache::bbmin, co, VertRen::co, copy_v3_v3(), DO_MINMAX, ObjectInstanceRen::flag, INIT_MINMAX, ObjectInstanceRen::mat, MEM_callocN(), mul_m4_v3(), NULL, ObjectInstanceRen::obr, R_TRANSFORMED, ObjectRen::totvert, VertTableNode::vert, ObjectRen::vertnodes, Render::viewinv, and ObjectInstanceRen::volume_precache.
Referenced by precache_init_parts(), precache_resolution(), and vol_get_precached_scattering().
int point_inside_volume_objectinstance (Render * re, ObjectInstanceRen * obi, float * co)
Definition at line 839 of file volume_precache.c.
References makeraytree_object(), and point_inside_obi().
Referenced by init_camera_inside_volumes().
void volume_precache (Render * re)
Definition at line 792 of file volume_precache.c.
References ListBase::first, Render::i, RenderStats::infostr, Render::instancetable, VolumeOb::ma, ObjectInstanceRen::next, VolumeOb::next, NULL, VolumeOb::obr, ObjectInstanceRen::obr, Render::sdh, Render::stats_draw, Render::tbh, Render::test_break, using_lightcache(), vol_precache_objectinstance_threads(), and Render::volumes.
Referenced by RE_Database_FromScene().