Blender: rna_material.c File Reference
rna_material.c File Reference
RNA
#include <float.h>
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_material_types.h"
#include "DNA_texture_types.h"
#include "WM_api.h"
#include "WM_types.h"
Functions
static void rna_def_material_mtex (BlenderRNA *brna)
static void rna_def_material_gamesettings (BlenderRNA *brna)
static void rna_def_material_colors (StructRNA *srna)
static void rna_def_material_diffuse (StructRNA *srna)
static void rna_def_material_raymirror (BlenderRNA *brna)
static void rna_def_material_raytra (BlenderRNA *brna)
static void rna_def_material_volume (BlenderRNA *brna)
static void rna_def_material_halo (BlenderRNA *brna)
static void rna_def_material_sss (BlenderRNA *brna)
static void rna_def_material_specularity (StructRNA *srna)
static void rna_def_material_strand (BlenderRNA *brna)
static void rna_def_material_physics (BlenderRNA *brna)
void RNA_def_material (BlenderRNA *brna)
static void rna_def_texture_slots (BlenderRNA *brna, PropertyRNA *cprop, const char *structname, const char *structname_slots)
void rna_def_mtex_common (BlenderRNA *brna, StructRNA *srna, const char *begin, const char *activeget, const char *activeset, const char *activeeditable, const char *structname, const char *structname_slots, const char *update)
Variables
static EnumPropertyItem prop_texture_coordinates_items []
EnumPropertyItem ramp_blend_items []
Detailed Description
Definition in file rna_material.c.
Function Documentation
void RNA_def_material (BlenderRNA * brna)
Definition at line 1671 of file rna_material.c.
References FLT_MAX, MA_APPROX_OCCLUSION, MA_CUBE, MA_CUBIC, MA_ENV, MA_FACETEXTURE, MA_FACETEXTURE_ALPHA, MA_FLAT, MA_FULL_OSA, MA_GROUP_NOLAY, MA_HAIR, MA_MONKEY, MA_NOMIST, MA_OBCOLOR, MA_ONLYCAST, MA_ONLYSHADOW, MA_RAYBIAS, MA_RAYTRANSP, MA_SHADBUF, MA_SHADOW, MA_SHADOW_TRA, MA_SHLESS, MA_SO_OLD, MA_SO_SHADED, MA_SO_SHADOW, MA_SPHERE, MA_SPHERE_A, MA_TANGENT_V, MA_TRACEBLE, MA_TRANSP, MA_TYPE_HALO, MA_TYPE_SURFACE, MA_TYPE_VOLUME, MA_TYPE_WIRE, MA_VERTEXCOL, MA_VERTEXCOLP, MA_ZINV, MA_ZTRANSP, NC_MATERIAL, NC_OBJECT, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, RNA_api_material(), rna_def_animdata_common(), rna_def_material_colors(), rna_def_material_diffuse(), rna_def_material_gamesettings(), rna_def_material_halo(), rna_def_material_mtex(), rna_def_material_physics(), rna_def_material_raymirror(), rna_def_material_raytra(), rna_def_material_specularity(), rna_def_material_sss(), rna_def_material_strand(), rna_def_material_volume(), rna_def_mtex_common(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
static void rna_def_material_colors (StructRNA * srna) [static]
Definition at line 810 of file rna_material.c.
References MA_RAMP_COL, MA_RAMP_IN_ENERGY, MA_RAMP_IN_NOR, MA_RAMP_IN_RESULT, MA_RAMP_IN_SHADER, MA_RAMP_SPEC, NULL, PROP_BOOLEAN, PROP_COLOR, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by RNA_def_material().
static void rna_def_material_diffuse (StructRNA * srna) [static]
Definition at line 912 of file rna_material.c.
References MA_DIFF_FRESNEL, MA_DIFF_LAMBERT, MA_DIFF_MINNAERT, MA_DIFF_ORENNAYAR, MA_DIFF_TOON, NULL, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by RNA_def_material().
static void rna_def_material_gamesettings (BlenderRNA * brna) [static]
Definition at line 753 of file rna_material.c.
References GEMAT_ADD, GEMAT_ALPHA, GEMAT_ALPHA_SORT, GEMAT_BACKCULL, GEMAT_BILLBOARD, GEMAT_CLIP, GEMAT_HALO, GEMAT_INVISIBLE, GEMAT_NOPHYSICS, GEMAT_NORMAL, GEMAT_SHADOW, GEMAT_SOLID, GEMAT_TEXT, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_material().
static void rna_def_material_halo (BlenderRNA * brna) [static]
Definition at line 1297 of file rna_material.c.
References MA_HALO_FLARE, MA_HALO_LINES, MA_HALO_RINGS, MA_HALO_SHADE, MA_HALO_SOFT, MA_HALO_XALPHA, MA_HALOPUNO, MA_HALOTEX, MA_STAR, NULL, PROP_BOOLEAN, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_material().
static void rna_def_material_mtex (BlenderRNA * brna) [static]
Definition at line 378 of file rna_material.c.
References MAP_ALPHA, MAP_AMB, MAP_COL, MAP_COLMIR, MAP_COLSPEC, MAP_DENSITY, MAP_DISPLACE, MAP_EMISSION, MAP_EMISSION_COL, MAP_EMIT, MAP_HAR, MAP_NORM, MAP_RAYMIRR, MAP_REF, MAP_REFLECTION, MAP_REFLECTION_COL, MAP_SCATTERING, MAP_SPEC, MAP_TRANSLU, MAP_TRANSMISSION_COL, MAP_WARP, MTEX_3TAP_BUMP, MTEX_5TAP_BUMP, MTEX_BICUBIC_BUMP, MTEX_BUMP_OBJECTSPACE, MTEX_BUMP_TEXTURESPACE, MTEX_COMPAT_BUMP, MTEX_CUBE, MTEX_DUPLI_MAPTO, MTEX_FLAT, MTEX_NSPACE_CAMERA, MTEX_NSPACE_OBJECT, MTEX_NSPACE_TANGENT, MTEX_NSPACE_WORLD, MTEX_OB_DUPLI_ORIG, MTEX_SPHERE, MTEX_TUBE, NC_TEXTURE, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_material().
static void rna_def_material_physics (BlenderRNA * brna) [static]
Definition at line 1627 of file rna_material.c.
References MA_FH_NOR, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_material().
static void rna_def_material_raymirror (BlenderRNA * brna) [static]
Definition at line 971 of file rna_material.c.
References MA_RAYMIR_FADETOMAT, MA_RAYMIR_FADETOSKY, MA_RAYMIRROR, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_material().
static void rna_def_material_raytra (BlenderRNA * brna) [static]
Definition at line 1061 of file rna_material.c.
References NULL, PROP_DISTANCE, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_material().
static void rna_def_material_specularity (StructRNA * srna) [static]
Definition at line 1496 of file rna_material.c.
References MA_SPEC_BLINN, MA_SPEC_COOKTORR, MA_SPEC_PHONG, MA_SPEC_TOON, MA_SPEC_WARDISO, NULL, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by RNA_def_material().
static void rna_def_material_sss (BlenderRNA * brna) [static]
Definition at line 1425 of file rna_material.c.
References FLT_MAX, MA_DIFF_SSS, NULL, PROP_BOOLEAN, PROP_COLOR, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_UNIT_LENGTH, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_material().
static void rna_def_material_strand (BlenderRNA * brna) [static]
Definition at line 1556 of file rna_material.c.
References MA_STR_B_UNITS, MA_STR_SURFDIFF, MA_TANGENT_STR, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_FLOAT, PROP_NONE, PROP_STRING, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_material().
static void rna_def_material_volume (BlenderRNA * brna) [static]
Definition at line 1140 of file rna_material.c.
References FLT_MAX, MA_VOL_PRECACHESHADING, MA_VOL_RECV_EXT_SHADOW, MA_VOL_SHADE_MULTIPLE, MA_VOL_SHADE_SHADED, MA_VOL_SHADE_SHADEDPLUSMULTIPLE, MA_VOL_SHADE_SHADELESS, MA_VOL_SHADE_SHADOWED, MA_VOL_STEP_CONSTANT, MA_VOL_STEP_RANDOMIZED, NULL, PROP_BOOLEAN, PROP_COLOR, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_material().
void rna_def_mtex_common (BlenderRNA * brna, StructRNA * srna, const char * begin, const char * activeget, const char * activeset, const char * activeeditable, const char * structname, const char * structname_slots, const char * update)
Definition at line 2054 of file rna_material.c.
References NULL, PROP_COLLECTION, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_collection_funcs(), RNA_def_property_editable_func(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), and rna_def_texture_slots().
Referenced by rna_def_lamp(), RNA_def_material(), rna_def_particle_settings(), and RNA_def_world().
static void rna_def_texture_slots (BlenderRNA * brna, PropertyRNA * cprop, const char * structname, const char * structname_slots) [static]
Definition at line 2022 of file rna_material.c.
References FUNC_NO_SELF, FUNC_USE_CONTEXT, FUNC_USE_REPORTS, FUNC_USE_SELF_ID, NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_int(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_mtex_common().
Variable Documentation
EnumPropertyItem prop_texture_coordinates_items[] [static]
Initial value:
 {
{TEXCO_GLOB, "GLOBAL", 0, "Global", "Use global coordinates for the texture coordinates"},
{TEXCO_OBJECT, "OBJECT", 0, "Object", "Use linked object's coordinates for texture coordinates"},
{TEXCO_UV, "UV", 0, "UV", "Use UV coordinates for texture coordinates"},
{TEXCO_ORCO, "ORCO", 0, "Generated", "Use the original undeformed coordinates of the object"},
{TEXCO_STRAND, "STRAND", 0, "Strand / Particle",
               "Use normalized strand texture coordinate (1D) or particle age (X) and trail position (Y)"},
{TEXCO_STICKY, "STICKY", 0, "Sticky", "Use mesh's sticky coordinates for the texture coordinates"},
{TEXCO_WINDOW, "WINDOW", 0, "Window", "Use screen coordinates as texture coordinates"},
{TEXCO_NORM, "NORMAL", 0, "Normal", "Use normal vector as texture coordinates"},
{TEXCO_REFL, "REFLECTION", 0, "Reflection", "Use reflection vector as texture coordinates"},
{TEXCO_STRESS, "STRESS", 0, "Stress",
               "Use the difference of edge lengths compared to original coordinates of the mesh"},
{TEXCO_TANGENT, "TANGENT", 0, "Tangent", "Use the optional tangent vector as texture coordinates"},
{0, NULL, 0, NULL, NULL}}
Definition at line 41 of file rna_material.c.
Referenced by rna_def_lamp_mtex(), and rna_def_modifier_generic_map_info().
EnumPropertyItem ramp_blend_items[]
Initial value:
 {
{MA_RAMP_BLEND, "MIX", 0, "Mix", ""},
{MA_RAMP_ADD, "ADD", 0, "Add", ""},
{MA_RAMP_MULT, "MULTIPLY", 0, "Multiply", ""},
{MA_RAMP_SUB, "SUBTRACT", 0, "Subtract", ""},
{MA_RAMP_SCREEN, "SCREEN", 0, "Screen", ""},
{MA_RAMP_DIV, "DIVIDE", 0, "Divide", ""},
{MA_RAMP_DIFF, "DIFFERENCE", 0, "Difference", ""},
{MA_RAMP_DARK, "DARKEN", 0, "Darken", ""},
{MA_RAMP_LIGHT, "LIGHTEN", 0, "Lighten", ""},
{MA_RAMP_OVERLAY, "OVERLAY", 0, "Overlay", ""},
{MA_RAMP_DODGE, "DODGE", 0, "Dodge", ""},
{MA_RAMP_BURN, "BURN", 0, "Burn", ""},
{MA_RAMP_HUE, "HUE", 0, "Hue", ""},
{MA_RAMP_SAT, "SATURATION", 0, "Saturation", ""},
{MA_RAMP_VAL, "VALUE", 0, "Value", ""},
{MA_RAMP_COLOR, "COLOR", 0, "Color", ""},
{MA_RAMP_SOFT, "SOFT_LIGHT", 0, "Soft Light", ""},
{MA_RAMP_LINEAR, "LINEAR_LIGHT", 0, "Linear Light", ""},
{0, NULL, 0, NULL, NULL}}
Definition at line 57 of file rna_material.c.
Referenced by def_mix_rgb(), node_blend_label(), and rna_def_lamp_sky_settings().