Blender: BKE_nla.h File Reference
BKE_nla.h File Reference
blenkernel
Enumerations
enum { NLATIME_CONVERT_EVAL = 0, NLATIME_CONVERT_UNMAP, NLATIME_CONVERT_MAP }
Functions
void free_nlastrip (ListBase *strips, struct NlaStrip *strip)
void free_nlatrack (ListBase *tracks, struct NlaTrack *nlt)
void free_nladata (ListBase *tracks)
struct NlaStrip * copy_nlastrip (struct NlaStrip *strip)
struct NlaTrack * copy_nlatrack (struct NlaTrack *nlt)
void copy_nladata (ListBase *dst, ListBase *src)
struct NlaTrack * add_nlatrack (struct AnimData *adt, struct NlaTrack *prev)
struct NlaStrip * add_nlastrip (struct bAction *act)
struct NlaStrip * add_nlastrip_to_stack (struct AnimData *adt, struct bAction *act)
struct NlaStrip * add_nla_soundstrip (struct Scene *scene, struct Speaker *spk)
short BKE_nlastrips_has_space (ListBase *strips, float start, float end)
void BKE_nlastrips_sort_strips (ListBase *strips)
short BKE_nlastrips_add_strip (ListBase *strips, struct NlaStrip *strip)
void BKE_nlastrips_make_metas (ListBase *strips, short temp)
void BKE_nlastrips_clear_metas (ListBase *strips, short onlySel, short onlyTemp)
void BKE_nlastrips_clear_metastrip (ListBase *strips, struct NlaStrip *strip)
short BKE_nlameta_add_strip (struct NlaStrip *mstrip, struct NlaStrip *strip)
void BKE_nlameta_flush_transforms (struct NlaStrip *mstrip)
struct NlaTrack * BKE_nlatrack_find_active (ListBase *tracks)
void BKE_nlatrack_set_active (ListBase *tracks, struct NlaTrack *nlt)
void BKE_nlatrack_solo_toggle (struct AnimData *adt, struct NlaTrack *nlt)
short BKE_nlatrack_has_space (struct NlaTrack *nlt, float start, float end)
void BKE_nlatrack_sort_strips (struct NlaTrack *nlt)
short BKE_nlatrack_add_strip (struct NlaTrack *nlt, struct NlaStrip *strip)
short BKE_nlatrack_get_bounds (struct NlaTrack *nlt, float bounds[2])
struct NlaStrip * BKE_nlastrip_find_active (struct NlaTrack *nlt)
void BKE_nlastrip_set_active (struct AnimData *adt, struct NlaStrip *strip)
short BKE_nlastrip_within_bounds (struct NlaStrip *strip, float min, float max)
void BKE_nlastrip_recalculate_bounds (struct NlaStrip *strip)
void BKE_nlastrip_validate_name (struct AnimData *adt, struct NlaStrip *strip)
short BKE_nlatrack_has_animated_strips (struct NlaTrack *nlt)
short BKE_nlatracks_have_animated_strips (ListBase *tracks)
void BKE_nlastrip_validate_fcurves (struct NlaStrip *strip)
void BKE_nla_validate_state (struct AnimData *adt)
void BKE_nla_action_pushdown (struct AnimData *adt)
short BKE_nla_tweakmode_enter (struct AnimData *adt)
void BKE_nla_tweakmode_exit (struct AnimData *adt)
float BKE_nla_tweakedit_remap (struct AnimData *adt, float cframe, short mode)
Variables
enum { ... } eNlaTime_ConvertModes
Detailed Description
Author:
Joshua Leung (full recode)
Definition in file BKE_nla.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
NLATIME_CONVERT_EVAL
NLATIME_CONVERT_UNMAP
NLATIME_CONVERT_MAP
Definition at line 117 of file BKE_nla.h.
Function Documentation
struct NlaStrip* add_nla_soundstrip (struct Scene * scene, struct Speaker * spk) [read]
Definition at line 347 of file nla.c.
References AUD_getInfo(), NlaStrip::end, NlaStrip::extendmode, NlaStrip::flag, FPS, AUD_SoundInfo::length, MEM_callocN(), NLASTRIP_EXTEND_NOTHING, NLASTRIP_FLAG_SELECT, NLASTRIP_TYPE_SOUND, bSound::playback_handle, NlaStrip::repeat, NlaStrip::scale, Speaker::sound, and NlaStrip::type.
Referenced by nlaedit_add_sound_exec(), and object_speaker_add_exec().
struct NlaStrip* add_nlastrip (struct bAction * act) [read]
Definition at line 274 of file nla.c.
References NlaStrip::act, NlaStrip::actend, NlaStrip::actstart, calc_action_range(), NlaStrip::end, NlaStrip::flag, bAction::id, id_us_plus(), IS_EQF, MEM_callocN(), NLASTRIP_FLAG_AUTO_BLENDS, NLASTRIP_FLAG_SELECT, NULL, NlaStrip::repeat, NlaStrip::scale, and NlaStrip::start.
Referenced by add_nlastrip_to_stack(), and nlaedit_add_actionclip_exec().
struct NlaStrip* add_nlastrip_to_stack (struct AnimData * adt, struct bAction * act) [read]
Definition at line 316 of file nla.c.
References add_nlastrip(), add_nlatrack(), BKE_nlastrip_validate_name(), BKE_nlatrack_add_strip(), ELEM, ListBase::last, AnimData::nla_tracks, and NULL.
Referenced by animrecord_check_state(), and BKE_nla_action_pushdown().
struct NlaTrack* add_nlatrack (struct AnimData * adt, struct NlaTrack * prev) [read]
Definition at line 243 of file nla.c.
References BKE_nlatrack_set_active(), BLI_addtail(), BLI_countlist(), BLI_insertlinkafter(), BLI_uniquename(), NlaTrack::flag, NlaTrack::index, MEM_callocN(), NlaTrack::name, AnimData::nla_tracks, NLATRACK_SELECTED, and NULL.
Referenced by add_nlastrip_to_stack(), nlaedit_add_actionclip_exec(), nlaedit_add_sound_exec(), nlaedit_add_tracks_exec(), nlaedit_duplicate_exec(), nlaedit_snap_exec(), nlastrips_to_animdata(), and object_speaker_add_exec().
void BKE_nla_action_pushdown (struct AnimData * adt)
Definition at line 1473 of file nla.c.
References AnimData::action, action_has_motion(), add_nlastrip_to_stack(), BKE_nlastrip_set_active(), ELEM, NlaStrip::extendmode, bAction::id, id_us_min(), NLASTRIP_EXTEND_HOLD_FORWARD, nlastrip_is_first(), and NULL.
Referenced by BKE_nla_bake(), and mouse_nla_channels().
float BKE_nla_tweakedit_remap (struct AnimData * adt, float cframe, short mode)
Definition at line 509 of file nla.c.
References AnimData::actstrip, ADT_NLA_EDIT_NOMAP, ADT_NLA_EDIT_ON, BKE_nlastrip_find_active(), BKE_nlatrack_find_active(), NlaStrip::flag, AnimData::flag, AnimData::nla_tracks, NLASTRIP_FLAG_USR_TIME, nlastrip_get_frame(), and NULL.
Referenced by actkeys_mselect_column(), applyTimeScale(), applyTimeSlide(), applyTimeTranslate(), bezt_nlamapping_apply(), bezt_nlamapping_restore(), bezt_to_transdata(), borderselect_action(), columnselect_action_keys(), columnselect_graph_keys(), createTransActionData(), delete_keyframe(), doAnimEdit_SnapFrame(), draw_ghost_poses(), flushTransGraphData(), get_graph_keyframe_extents(), get_keyframe_extents(), graphkeys_click_insert_exec(), graphkeys_mselect_column(), insert_action_keys(), insert_graph_keys(), insert_keyframe(), and mouse_action_keys().
short BKE_nla_tweakmode_enter (struct AnimData * adt)
Definition at line 1521 of file nla.c.
References NlaStrip::act, AnimData::action, AnimData::actstrip, ADT_NLA_EDIT_ON, BKE_nlastrip_find_active(), ELEM, ELEM3, ListBase::first, AnimData::flag, NlaStrip::flag, NlaTrack::flag, G, G_DEBUG, bAction::id, id_us_plus(), ListBase::last, NlaTrack::next, NlaStrip::next, AnimData::nla_tracks, NLASTRIP_FLAG_ACTIVE, NLASTRIP_FLAG_SELECT, NLASTRIP_FLAG_TWEAKUSER, NLATRACK_ACTIVE, NLATRACK_DISABLED, NLATRACK_SELECTED, NULL, NlaTrack::prev, NlaTrack::strips, and AnimData::tmpact.
Referenced by nlaedit_enable_tweakmode_exec().
void BKE_nla_tweakmode_exit (struct AnimData * adt)
Definition at line 1622 of file nla.c.
References AnimData::action, AnimData::actstrip, ADT_NLA_EDIT_ON, ELEM, ListBase::first, AnimData::flag, NlaStrip::flag, NlaTrack::flag, bAction::id, NlaTrack::next, NlaStrip::next, AnimData::nla_tracks, NLASTRIP_FLAG_TWEAKUSER, NLATRACK_DISABLED, NULL, NlaTrack::strips, AnimData::tmpact, and ID::us.
Referenced by nlaedit_disable_tweakmode_exec().
void BKE_nla_validate_state (struct AnimData * adt)
Definition at line 1419 of file nla.c.
References BKE_nlastrip_validate_autoblends(), NlaStrip::blendmode, ELEM, NlaStrip::extendmode, ListBase::first, NlaTrack::next, NlaStrip::next, AnimData::nla_tracks, NLASTRIP_EXTEND_HOLD, NLASTRIP_EXTEND_HOLD_FORWARD, NLASTRIP_EXTEND_NOTHING, NLASTRIP_MODE_REPLACE, NULL, NlaStrip::start, and NlaTrack::strips.
Referenced by ED_nla_postop_refresh().
short BKE_nlameta_add_strip (struct NlaStrip * mstrip, struct NlaStrip * strip)
Definition at line 769 of file nla.c.
References BKE_nlastrips_add_strip(), BKE_nlastrips_has_space(), BLI_addhead(), BLI_addtail(), ELEM, NlaStrip::end, NlaStrip::next, NULL, NlaStrip::prev, NlaStrip::start, and NlaStrip::strips.
void BKE_nlameta_flush_transforms (struct NlaStrip * mstrip)
Definition at line 819 of file nla.c.
References BKE_nlameta_flush_transforms(), ELEM, NlaStrip::end, ListBase::first, IS_EQF, ListBase::last, NlaStrip::next, NLASTRIP_TYPE_META, NULL, RNA_float_set(), RNA_NlaStrip, RNA_pointer_create(), NlaStrip::start, NlaStrip::strips, and NlaStrip::type.
Referenced by BKE_nlameta_flush_transforms(), nlaedit_snap_exec(), nlaedit_swap_exec(), and recalcData_nla().
struct NlaStrip* BKE_nlastrip_find_active (struct NlaTrack * nlt) [read]
Definition at line 1045 of file nla.c.
References ELEM, ListBase::first, NlaStrip::flag, NlaStrip::next, NLASTRIP_FLAG_ACTIVE, NULL, and NlaTrack::strips.
Referenced by BKE_nla_tweakedit_remap(), BKE_nla_tweakmode_enter(), and nla_panel_context().
void BKE_nlastrip_recalculate_bounds (struct NlaStrip * strip)
Definition at line 1119 of file nla.c.
References NlaStrip::actend, NlaStrip::actstart, NlaStrip::end, IS_EQF, NLASTRIP_TYPE_CLIP, NULL, NlaStrip::repeat, NlaStrip::scale, NlaStrip::start, and NlaStrip::type.
Referenced by nlaedit_sync_actlen_exec().
void BKE_nlastrip_set_active (struct AnimData * adt, struct NlaStrip * strip)
Definition at line 1064 of file nla.c.
References ListBase::first, NlaStrip::flag, NlaTrack::next, NlaStrip::next, AnimData::nla_tracks, NLASTRIP_FLAG_ACTIVE, NULL, and NlaTrack::strips.
Referenced by BKE_nla_action_pushdown().
void BKE_nlastrip_validate_fcurves (struct NlaStrip * strip)
Definition at line 1212 of file nla.c.
References BLI_addtail(), BLI_strdupn(), FCURVE_SELECTED, FCURVE_VISIBLE, NlaStrip::fcurves, FCurve::flag, NlaStrip::flag, list_find_fcurve(), MEM_callocN(), NLASTRIP_FLAG_USR_INFLUENCE, NLASTRIP_FLAG_USR_TIME, NULL, and FCurve::rna_path.
void BKE_nlastrip_validate_name (struct AnimData * adt, struct NlaStrip * strip)
Definition at line 1275 of file nla.c.
References NlaStrip::act, BLI_ghash_free(), BLI_ghash_insert(), BLI_ghash_new(), BLI_ghashutil_strcmp(), BLI_ghashutil_strhash(), BLI_strncpy(), BLI_uniquename_cb(), ELEM, ListBase::first, bAction::id, ID::name, NlaStrip::name, NlaStrip::next, NlaTrack::next, nla_editbone_name_check(), AnimData::nla_tracks, NLASTRIP_TYPE_CLIP, NLASTRIP_TYPE_META, NLASTRIP_TYPE_TRANSITION, NULL, NlaTrack::strips, and NlaStrip::type.
Referenced by add_nlastrip_to_stack(), nlaedit_add_actionclip_exec(), nlaedit_add_meta_exec(), nlaedit_add_sound_exec(), nlaedit_add_transition_exec(), nlaedit_duplicate_exec(), nlaedit_split_strip_actclip(), and object_speaker_add_exec().
short BKE_nlastrip_within_bounds (struct NlaStrip * strip, float min, float max)
Definition at line 1086 of file nla.c.
References NlaStrip::end, fabsf, IN_RANGE, IS_EQF, NULL, and NlaStrip::start.
Referenced by borderselect_nla_strips(), draw_nla_main_data(), mouse_nla_strips(), and nlaedit_select_leftright().
short BKE_nlastrips_add_strip (ListBase * strips, struct NlaStrip * strip)
Definition at line 627 of file nla.c.
References BKE_nlastrips_has_space(), BLI_addtail(), BLI_insertlinkbefore(), ELEM, NlaStrip::end, ListBase::first, NlaStrip::next, NULL, and NlaStrip::start.
Referenced by BKE_nlameta_add_strip(), and BKE_nlatrack_add_strip().
void BKE_nlastrips_clear_metas (ListBase * strips, short onlySel, short onlyTemp)
Definition at line 742 of file nla.c.
References BKE_nlastrips_clear_metastrip(), ELEM, ListBase::first, NlaStrip::flag, NlaStrip::next, NLASTRIP_FLAG_SELECT, NLASTRIP_FLAG_TEMP_META, NLASTRIP_TYPE_META, NULL, and NlaStrip::type.
Referenced by nlaedit_remove_meta_exec(), nlaedit_snap_exec(), nlaedit_swap_exec(), and special_aftertrans_update().
void BKE_nlastrips_clear_metastrip (ListBase * strips, struct NlaStrip * strip)
Definition at line 717 of file nla.c.
References BLI_insertlinkbefore(), BLI_remlink(), ELEM, ListBase::first, free_nlastrip(), NlaStrip::next, NULL, and NlaStrip::strips.
Referenced by BKE_nlastrips_clear_metas(), and nlaedit_split_strip_meta().
short BKE_nlastrips_has_space (ListBase * strips, float start, float end)
Definition at line 549 of file nla.c.
References NlaStrip::end, ListBase::first, IS_EQF, NlaStrip::next, NULL, NlaStrip::start, and SWAP.
Referenced by BKE_nlameta_add_strip(), BKE_nlastrips_add_strip(), BKE_nlatrack_has_space(), and nlaedit_swap_exec().
void BKE_nlastrips_make_metas (ListBase * strips, short temp)
Definition at line 665 of file nla.c.
References BLI_addtail(), BLI_insertlinkbefore(), BLI_remlink(), ELEM, NlaStrip::end, ListBase::first, NlaStrip::flag, MEM_callocN(), NlaStrip::next, NLASTRIP_FLAG_SELECT, NLASTRIP_FLAG_TEMP_META, NLASTRIP_TYPE_META, NULL, NlaStrip::repeat, NlaStrip::scale, NlaStrip::start, NlaStrip::strips, and NlaStrip::type.
Referenced by createTransNlaData(), nlaedit_add_meta_exec(), nlaedit_snap_exec(), and nlaedit_swap_exec().
void BKE_nlastrips_sort_strips (ListBase * strips)
Definition at line 583 of file nla.c.
References BLI_addhead(), BLI_insertlinkafter(), BLI_remlink(), ELEM, NlaStrip::end, ListBase::first, ListBase::last, NlaStrip::next, NULL, NlaStrip::prev, and NlaStrip::start.
Referenced by BKE_nlatrack_sort_strips().
short BKE_nlatrack_add_strip (struct NlaTrack * nlt, struct NlaStrip * strip)
Definition at line 1003 of file nla.c.
References BKE_nlastrips_add_strip(), ELEM, NULL, and NlaTrack::strips.
Referenced by add_nlastrip_to_stack(), nlaedit_add_actionclip_exec(), nlaedit_add_sound_exec(), nlaedit_duplicate_exec(), nlaedit_move_down_exec(), nlaedit_move_up_exec(), nlaedit_snap_exec(), nlaedit_swap_exec(), nlastrips_to_animdata(), object_speaker_add_exec(), and recalcData_nla().
struct NlaTrack* BKE_nlatrack_find_active (ListBase * tracks) [read]
Definition at line 897 of file nla.c.
References ELEM, ListBase::first, NlaTrack::flag, NlaTrack::next, NLATRACK_ACTIVE, and NULL.
Referenced by BKE_nla_tweakedit_remap().
short BKE_nlatrack_get_bounds (struct NlaTrack * nlt, float bounds[2])
Definition at line 1016 of file nla.c.
References ELEM, NlaStrip::end, ListBase::first, ListBase::last, NULL, NlaStrip::start, and NlaTrack::strips.
short BKE_nlatrack_has_animated_strips (struct NlaTrack * nlt)
Definition at line 1174 of file nla.c.
References ELEM, NlaStrip::fcurves, ListBase::first, NlaStrip::next, NULL, and NlaTrack::strips.
Referenced by BKE_nlatracks_have_animated_strips().
short BKE_nlatrack_has_space (struct NlaTrack * nlt, float start, float end)
Definition at line 968 of file nla.c.
References BKE_nlastrips_has_space(), NlaTrack::flag, IS_EQF, NLATRACK_PROTECTED, NULL, NlaTrack::strips, and SWAP.
Referenced by nlaedit_move_down_exec(), nlaedit_move_up_exec(), and recalcData_nla().
void BKE_nlatrack_set_active (ListBase * tracks, struct NlaTrack * nlt)
Definition at line 950 of file nla.c.
References ELEM, ListBase::first, NlaTrack::flag, NlaTrack::next, NLATRACK_ACTIVE, and NULL.
Referenced by add_nlatrack().
void BKE_nlatrack_solo_toggle (struct AnimData * adt, struct NlaTrack * nlt)
Definition at line 918 of file nla.c.
References ADT_NLA_SOLO_TRACK, ELEM, ListBase::first, AnimData::flag, NlaTrack::flag, NlaTrack::next, AnimData::nla_tracks, NLATRACK_SOLO, and NULL.
Referenced by mouse_nla_channels().
void BKE_nlatrack_sort_strips (struct NlaTrack * nlt)
Definition at line 990 of file nla.c.
References BKE_nlastrips_sort_strips(), ELEM, ListBase::first, NULL, and NlaTrack::strips.
Referenced by special_aftertrans_update().
short BKE_nlatracks_have_animated_strips (ListBase * tracks)
Definition at line 1193 of file nla.c.
References BKE_nlatrack_has_animated_strips(), ELEM, ListBase::first, NlaTrack::next, and NULL.
void copy_nladata (ListBase * dst, ListBase * src)
Definition at line 219 of file nla.c.
References BLI_addtail(), copy_nlatrack(), ELEM, ListBase::first, ListBase::last, NlaTrack::next, and NULL.
Referenced by BKE_copy_animdata().
struct NlaStrip* copy_nlastrip (struct NlaStrip * strip) [read]
Definition at line 159 of file nla.c.
References NlaStrip::act, BLI_addtail(), copy_fcurves(), copy_fmodifiers(), copy_nlastrip(), NlaStrip::fcurves, ListBase::first, bAction::id, id_us_plus(), ListBase::last, MEM_dupallocN(), NlaStrip::modifiers, NlaStrip::next, NULL, NlaStrip::prev, and NlaStrip::strips.
Referenced by copy_nlastrip(), copy_nlatrack(), nlaedit_duplicate_exec(), and nlaedit_split_strip_actclip().
struct NlaTrack* copy_nlatrack (struct NlaTrack * nlt) [read]
Definition at line 193 of file nla.c.
References BLI_addtail(), copy_nlastrip(), ListBase::first, ListBase::last, MEM_dupallocN(), NlaTrack::next, NlaStrip::next, NULL, NlaTrack::prev, and NlaTrack::strips.
Referenced by copy_nladata().
void free_nladata (ListBase * tracks)
Definition at line 138 of file nla.c.
References ELEM, ListBase::first, free_nlatrack(), ListBase::last, NlaTrack::next, and NULL.
Referenced by BKE_free_animdata().
void free_nlastrip (ListBase * strips, struct NlaStrip * strip)
Definition at line 76 of file nla.c.
References NlaStrip::act, BLI_freelinkN(), NlaStrip::fcurves, ListBase::first, free_fcurves(), free_fmodifiers(), free_nlastrip(), bAction::id, id_us_min(), MEM_freeN(), NlaStrip::modifiers, NlaStrip::next, NULL, and NlaStrip::strips.
Referenced by BKE_nlastrips_clear_metastrip(), free_nlastrip(), free_nlatrack(), and nlaedit_delete_exec().
void free_nlatrack (ListBase * tracks, struct NlaTrack * nlt)
Definition at line 114 of file nla.c.
References BLI_freelinkN(), ListBase::first, free_nlastrip(), MEM_freeN(), NlaStrip::next, NULL, and NlaTrack::strips.
Referenced by free_nladata(), and nlaedit_delete_tracks_exec().
Variable Documentation
enum { ... } eNlaTime_ConvertModes