Blender: CellIdentifierInterface Class Reference
CellIdentifierInterface Class Reference
cell identifier interface
#include <solver_interface.h>
Public Member Functions
CellIdentifierInterface ()
reset constructor
virtual ~CellIdentifierInterface ()
virtual destructor
virtual string getAsString ()=0
return node as string (with some basic info)
virtual bool equal (CellIdentifierInterface *other)=0
compare cids
void setEnd (bool set)
set/get end flag for grid traversal (not needed for marked cells)
bool getEnd ()
Public Attributes
bool mEnd
has the grid been traversed?
Detailed Description
cell identifier interface
Definition at line 207 of file solver_interface.h.
Constructor & Destructor Documentation
CellIdentifierInterface::CellIdentifierInterface () [inline]
reset constructor
Definition at line 210 of file solver_interface.h.
virtual CellIdentifierInterface::~CellIdentifierInterface () [inline, virtual]
virtual destructor
Definition at line 212 of file solver_interface.h.
Member Function Documentation
virtual bool CellIdentifierInterface::equal (CellIdentifierInterface * other) [pure virtual]
compare cids
Implemented in UniformFsgrCellIdentifier.
virtual string CellIdentifierInterface::getAsString () [pure virtual]
return node as string (with some basic info)
Implemented in UniformFsgrCellIdentifier.
Referenced by LbmFsgrSolver::debugPrintNodeInfo().
bool CellIdentifierInterface::getEnd (void) [inline]
Definition at line 222 of file solver_interface.h.
References mEnd.
Referenced by LbmFsgrSolver::advanceCell(), and LbmFsgrSolver::noEndCell().
void CellIdentifierInterface::setEnd (bool set) [inline]
set/get end flag for grid traversal (not needed for marked cells)
Definition at line 221 of file solver_interface.h.
References mEnd.
Referenced by LbmFsgrSolver::advanceCell().
Member Data Documentation
bool CellIdentifierInterface::mEnd
has the grid been traversed?
Definition at line 225 of file solver_interface.h.
Referenced by getEnd(), and setEnd().
The documentation for this class was generated from the following file:
solver_interface.h