Blender: rna_space.c File Reference
rna_space.c File Reference
RNA
#include <stdlib.h>
#include "MEM_guardedalloc.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "rna_internal.h"
#include "BLF_translation.h"
#include "BKE_key.h"
#include "BKE_movieclip.h"
#include "DNA_action_types.h"
#include "DNA_key_types.h"
#include "DNA_node_types.h"
#include "DNA_object_types.h"
#include "DNA_space_types.h"
#include "DNA_sequence_types.h"
#include "DNA_view3d_types.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RE_engine.h"
#include "RE_pipeline.h"
#include "RNA_enum_types.h"
Functions
static void rna_def_space (BlenderRNA *brna)
static void rna_def_space_image_uv (BlenderRNA *brna)
static void rna_def_space_outliner (BlenderRNA *brna)
static void rna_def_background_image (BlenderRNA *brna)
static void rna_def_backgroundImages (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_space_view3d (BlenderRNA *brna)
static void rna_def_space_buttons (BlenderRNA *brna)
static void rna_def_space_image (BlenderRNA *brna)
static void rna_def_space_sequencer (BlenderRNA *brna)
static void rna_def_space_text (BlenderRNA *brna)
static void rna_def_space_dopesheet (BlenderRNA *brna)
static void rna_def_space_graph (BlenderRNA *brna)
static void rna_def_space_nla (BlenderRNA *brna)
static void rna_def_space_time (BlenderRNA *brna)
static void rna_def_console_line (BlenderRNA *brna)
static void rna_def_space_console (BlenderRNA *brna)
static void rna_def_fileselect_params (BlenderRNA *brna)
static void rna_def_space_filebrowser (BlenderRNA *brna)
static void rna_def_space_info (BlenderRNA *brna)
static void rna_def_space_userpref (BlenderRNA *brna)
static void rna_def_space_node (BlenderRNA *brna)
static void rna_def_space_logic (BlenderRNA *brna)
static void rna_def_space_clip (BlenderRNA *brna)
void RNA_def_space (BlenderRNA *brna)
Variables
EnumPropertyItem space_type_items []
static EnumPropertyItem draw_channels_items []
static EnumPropertyItem transform_orientation_items []
EnumPropertyItem autosnap_items []
EnumPropertyItem viewport_shade_items []
Detailed Description
Definition in file rna_space.c.
Function Documentation
static void rna_def_background_image (BlenderRNA * brna) [static]
Definition at line 1246 of file rna_space.c.
References FLT_MAX, N_, NC_SPACE, ND_SPACE_VIEW3D, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), RV3D_VIEW_BACK, RV3D_VIEW_BOTTOM, RV3D_VIEW_CAMERA, RV3D_VIEW_FRONT, RV3D_VIEW_LEFT, RV3D_VIEW_RIGHT, RV3D_VIEW_TOP, V3D_BGPIC_CAMERACLIP, V3D_BGPIC_DISABLED, V3D_BGPIC_EXPANDED, V3D_BGPIC_FOREGROUND, V3D_BGPIC_IMAGE, and V3D_BGPIC_MOVIE.
Referenced by RNA_def_space().
static void rna_def_backgroundImages (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1362 of file rna_space.c.
References FUNC_USE_REPORTS, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_space_view3d().
static void rna_def_console_line (BlenderRNA * brna) [static]
Definition at line 2500 of file rna_space.c.
References NC_SPACE, ND_SPACE_CONSOLE, NULL, PROP_INT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_string_funcs(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_space().
static void rna_def_fileselect_params (BlenderRNA * brna) [static]
Definition at line 2563 of file rna_space.c.
References BLENDERFILE, FILE_FILTER, FILE_HIDE_DOT, FILE_IMGDISPLAY, FILE_LONGDISPLAY, FILE_SHORTDISPLAY, FILE_SORT_ALPHA, FILE_SORT_EXTENSION, FILE_SORT_SIZE, FILE_SORT_TIME, FOLDERFILE, FTFONTFILE, IMAGEFILE, MOVIEFILE, NC_SPACE, ND_SPACE_FILE_LIST, ND_SPACE_FILE_PARAMS, NULL, PROP_BOOLEAN, PROP_DIRPATH, PROP_EDITABLE, PROP_ENUM, PROP_FILENAME, PROP_NONE, PROP_STRING, PYSCRIPTFILE, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_text(), SOUNDFILE, and TEXTFILE.
Referenced by RNA_def_space().
static void rna_def_space (BlenderRNA * brna) [static]
Definition at line 1054 of file rna_space.c.
References NULL, PROP_EDITABLE, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_space().
void RNA_def_space (BlenderRNA * brna)
Definition at line 3110 of file rna_space.c.
References rna_def_background_image(), rna_def_console_line(), rna_def_fileselect_params(), rna_def_space(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_console(), rna_def_space_dopesheet(), rna_def_space_filebrowser(), rna_def_space_graph(), rna_def_space_image(), rna_def_space_info(), rna_def_space_logic(), rna_def_space_nla(), rna_def_space_node(), rna_def_space_outliner(), rna_def_space_sequencer(), rna_def_space_text(), rna_def_space_time(), rna_def_space_userpref(), and rna_def_space_view3d().
static void rna_def_space_buttons (BlenderRNA * brna) [static]
Definition at line 1783 of file rna_space.c.
References BCONTEXT_BONE, BCONTEXT_BONE_CONSTRAINT, BCONTEXT_CONSTRAINT, BCONTEXT_DATA, BCONTEXT_MATERIAL, BCONTEXT_MODIFIER, BCONTEXT_OBJECT, BCONTEXT_PARTICLE, BCONTEXT_PHYSICS, BCONTEXT_RENDER, BCONTEXT_SCENE, BCONTEXT_TEXTURE, BCONTEXT_WORLD, BUT_HORIZONTAL, BUT_VERTICAL, NC_SPACE, NC_TEXTURE, ND_SPACE_PROPERTIES, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SB_PIN_CONTEXT, and SB_TEXC_MAT_OR_LAMP.
Referenced by RNA_def_space().
static void rna_def_space_clip (BlenderRNA * brna) [static]
Definition at line 2918 of file rna_space.c.
References MOVIECLIP_DISABLE_BLUE, MOVIECLIP_DISABLE_GREEN, MOVIECLIP_DISABLE_RED, MOVIECLIP_PREVIEW_GRAYSCALE, NC_MOVIECLIP, NC_SPACE, ND_DISPLAY, ND_SPACE_CLIP, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SC_HIDE_DISABLED, SC_LOCK_SELECTION, SC_LOCK_TIMECURSOR, SC_MANUAL_CALIBRATION, SC_MODE_DISTORTION, SC_MODE_RECONSTRUCTION, SC_MODE_TRACKING, SC_MUTE_FOOTAGE, SC_SHOW_BUNDLES, SC_SHOW_FILTERS, SC_SHOW_GRAPH_FRAMES, SC_SHOW_GRAPH_TRACKS, SC_SHOW_GRID, SC_SHOW_MARKER_PATTERN, SC_SHOW_MARKER_SEARCH, SC_SHOW_NAMES, SC_SHOW_STABLE, SC_SHOW_TINY_MARKER, SC_SHOW_TRACK_PATH, SC_VIEW_CLIP, and SC_VIEW_GRAPH.
Referenced by RNA_def_space().
static void rna_def_space_console (BlenderRNA * brna) [static]
Definition at line 2521 of file rna_space.c.
References NC_SPACE, ND_SPACE_CONSOLE, NULL, PROP_COLLECTION, PROP_INT, PROP_NONE, PROP_STRING, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_collection_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_space().
static void rna_def_space_dopesheet (BlenderRNA * brna) [static]
Definition at line 2183 of file rna_space.c.
References NA_EDITED, NC_ANIMATION, NC_SPACE, ND_KEYFRAME, ND_SPACE_DOPESHEET, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SACTCONT_ACTION, SACTCONT_DOPESHEET, SACTCONT_GPENCIL, SACTCONT_SHAPEKEY, SACTION_DRAWTIME, SACTION_MARKERS_MOVE, SACTION_NODRAWCFRANUM, SACTION_NOREALTIMEUPDATES, SACTION_NOTRANSKEYCULL, SACTION_POSEMARKERS_SHOW, and SACTION_SLIDERS.
Referenced by RNA_def_space().
static void rna_def_space_filebrowser (BlenderRNA * brna) [static]
Definition at line 2678 of file rna_space.c.
References NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_pointer_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_space().
static void rna_def_space_graph (BlenderRNA * brna) [static]
Definition at line 2270 of file rna_space.c.
References NC_SPACE, ND_SPACE_GRAPH, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SIPO_BEAUTYDRAW_OFF, SIPO_DRAWTIME, SIPO_MODE_ANIMATION, SIPO_MODE_DRIVERS, SIPO_NODRAWCFRANUM, SIPO_NODRAWCURSOR, SIPO_NOHANDLES, SIPO_NOREALTIMEUPDATES, SIPO_NOTRANSKEYCULL, SIPO_SELCUVERTSONLY, SIPO_SELVHANDLESONLY, SIPO_SLIDERS, V3D_CENTER, V3D_CURSOR, and V3D_LOCAL.
Referenced by RNA_def_space().
static void rna_def_space_image (BlenderRNA * brna) [static]
Definition at line 1852 of file rna_space.c.
References NC_GEOM, NC_SPACE, ND_DATA, ND_SPACE_IMAGE, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), rna_def_space_image_uv(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SI_DISPGP, SI_DRAW_TILE, and SI_DRAWTOOL.
Referenced by RNA_def_space().
static void rna_def_space_image_uv (BlenderRNA * brna) [static]
Definition at line 1071 of file rna_space.c.
References NC_SPACE, ND_SPACE_IMAGE, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_funcs(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SI_CLIP_UV, SI_COORDFLOATS, SI_DRAW_OTHER, SI_DRAW_STRETCH, SI_DRAWSHADOW, SI_LIVE_UNWRAP, SI_NO_DRAWFACES, SI_PIXELSNAP, SI_SMOOTH_UV, SI_STICKY_DISABLE, SI_STICKY_LOC, SI_STICKY_VERTEX, SI_UVDT_BLACK, SI_UVDT_DASH, SI_UVDT_OUTLINE, SI_UVDT_STRETCH_ANGLE, SI_UVDT_STRETCH_AREA, SI_UVDT_WHITE, V3D_CENTER, V3D_CENTROID, and V3D_CURSOR.
Referenced by rna_def_space_image().
static void rna_def_space_info (BlenderRNA * brna) [static]
Definition at line 2702 of file rna_space.c.
References INFO_RPT_DEBUG, INFO_RPT_ERR, INFO_RPT_INFO, INFO_RPT_OP, INFO_RPT_WARN, NC_SPACE, ND_SPACE_INFO_REPORT, NULL, PROP_BOOLEAN, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_space().
static void rna_def_space_logic (BlenderRNA * brna) [static]
Definition at line 2849 of file rna_space.c.
References BUTS_ACT_ACT, BUTS_ACT_LINK, BUTS_ACT_SEL, BUTS_ACT_STATE, BUTS_CONT_ACT, BUTS_CONT_LINK, BUTS_CONT_SEL, BUTS_SENS_ACT, BUTS_SENS_LINK, BUTS_SENS_SEL, BUTS_SENS_STATE, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_space().
static void rna_def_space_nla (BlenderRNA * brna) [static]
Definition at line 2394 of file rna_space.c.
References NC_SPACE, ND_SPACE_NLA, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SNLA_DRAWTIME, SNLA_NODRAWCFRANUM, SNLA_NOREALTIMEUPDATES, and SNLA_NOSTRIPCURVES.
Referenced by RNA_def_space().
static void rna_def_space_node (BlenderRNA * brna) [static]
Definition at line 2753 of file rna_space.c.
References FLT_MAX, NC_SPACE, ND_SPACE_NODE, ND_SPACE_NODE_VIEW, nodetree_type_items, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_default(), RNA_def_property_float_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SNODE_AUTO_RENDER, SNODE_BACKDRAW, SNODE_SHADER_OBJECT, SNODE_SHADER_WORLD, SNODE_SHOW_ALPHA, SNODE_TEX_BRUSH, SNODE_TEX_OBJECT, SNODE_TEX_WORLD, SNODE_USE_ALPHA, and texture_type_items.
Referenced by RNA_def_space().
static void rna_def_space_outliner (BlenderRNA * brna) [static]
Definition at line 1194 of file rna_space.c.
References NC_SPACE, ND_SPACE_OUTLINER, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SO_ACTIVE, SO_ALL_SCENES, SO_CUR_SCENE, SO_DATABLOCKS, SO_FIND_CASE_SENSITIVE, SO_FIND_COMPLETE, SO_GROUPS, SO_HIDE_RESTRICTCOLS, SO_KEYMAP, SO_LIBRARIES, SO_SAME_TYPE, SO_SELECTED, SO_SEQUENCE, SO_USERDEF, and SO_VISIBLE.
Referenced by RNA_def_space().
static void rna_def_space_sequencer (BlenderRNA * brna) [static]
Definition at line 1969 of file rna_space.c.
References MAXSEQ, NC_SPACE, ND_SPACE_SEQUENCER, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SEQ_DRAW_COLOR_SEPARATED, SEQ_DRAW_GPENCIL, SEQ_DRAW_IMG_HISTOGRAM, SEQ_DRAW_IMG_IMBUF, SEQ_DRAW_IMG_VECTORSCOPE, SEQ_DRAW_IMG_WAVEFORM, SEQ_DRAW_SAFE_MARGINS, SEQ_DRAWFRAMES, SEQ_MARKER_TRANS, SEQ_NO_DRAW_CFRANUM, SEQ_PROXY_RENDER_SIZE_100, SEQ_PROXY_RENDER_SIZE_25, SEQ_PROXY_RENDER_SIZE_50, SEQ_PROXY_RENDER_SIZE_75, SEQ_PROXY_RENDER_SIZE_FULL, SEQ_PROXY_RENDER_SIZE_NONE, SEQ_PROXY_RENDER_SIZE_SCENE, SEQ_VIEW_PREVIEW, SEQ_VIEW_SEQUENCE, and SEQ_VIEW_SEQUENCE_PREVIEW.
Referenced by RNA_def_space().
static void rna_def_space_text (BlenderRNA * brna) [static]
Definition at line 2081 of file rna_space.c.
References NC_SPACE, ND_SPACE_TEXT, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), ST_FIND_ALL, ST_FIND_WRAP, ST_MATCH_CASE, and ST_SHOW_MARGIN.
Referenced by RNA_def_space().
static void rna_def_space_time (BlenderRNA * brna) [static]
Definition at line 2441 of file rna_space.c.
References NC_SPACE, ND_SPACE_TIME, NULL, PROP_BOOLEAN, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TIME_CACHE_CLOTH, TIME_CACHE_DISPLAY, TIME_CACHE_DYNAMICPAINT, TIME_CACHE_PARTICLES, TIME_CACHE_SMOKE, TIME_CACHE_SOFTBODY, TIME_CFRA_NUM, TIME_DRAWFRAMES, and TIME_ONLYACTSEL.
Referenced by RNA_def_space().
static void rna_def_space_userpref (BlenderRNA * brna) [static]
Definition at line 2738 of file rna_space.c.
References NULL, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_space().
static void rna_def_space_view3d (BlenderRNA * brna) [static]
Definition at line 1388 of file rna_space.c.
References FLT_MAX, FUNC_USE_SELF_ID, NC_SPACE, NC_WINDOW, ND_SPACE_VIEW3D, NULL, OB_ARROWS, OB_CIRCLE, OB_CUBE, OB_EMPTY_CONE, OB_EMPTY_SPHERE, OB_PLAINAXES, OB_SINGLE_ARROW, PROP_BOOLEAN, PROP_COLLECTION, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_LAYER_MEMBER, PROP_MATRIX, PROP_NONE, PROP_POINTER, PROP_QUATERNION, PROP_STRING, PROP_TRANSLATION, PROP_UNSIGNED, PROP_XYZ_LENGTH, rna_def_backgroundImages(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_ui_description(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_default(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_default(), RNA_def_property_int_sdna(), RNA_def_property_multi_array(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), RNA_TRANSLATION_PREC_DEFAULT, RV3D_BOXCLIP, RV3D_BOXVIEW, RV3D_CAMOB, RV3D_CAMZOOM_MAX, RV3D_CAMZOOM_MIN, RV3D_LOCKED, RV3D_ORTHO, RV3D_PERSP, V3D_ACTIVE, V3D_ALIGN, V3D_CENTER, V3D_CENTROID, V3D_CURSOR, V3D_DISPBGPICS, V3D_DRAW_CENTERS, V3D_HIDE_HELPLINES, V3D_LOCAL, V3D_LOCK_CAMERA, V3D_MANIP_ROTATE, V3D_MANIP_SCALE, V3D_MANIP_TRANSLATE, V3D_RENDER_OVERRIDE, V3D_SELECT_OUTLINE, V3D_SHOW_BUNDLENAME, V3D_SHOW_CAMERAPATH, V3D_SHOW_FLOOR, V3D_SHOW_RECONSTRUCTION, V3D_SHOW_X, V3D_SHOW_Y, V3D_SHOW_Z, V3D_SOLID_TEX, V3D_USE_MANIPULATOR, and V3D_ZBUF_SELECT.
Referenced by RNA_def_space().
Variable Documentation
EnumPropertyItem autosnap_items[]
Initial value:
 {
    {SACTSNAP_OFF, "NONE", 0, "No Auto-Snap", ""},
    {SACTSNAP_STEP, "STEP", 0, "Time Step", "Snap to 1.0 frame/second intervals"},
    {SACTSNAP_FRAME, "FRAME", 0, "Nearest Frame", "Snap to actual frames/seconds (nla-action time)"},
    {SACTSNAP_MARKER, "MARKER", 0, "Nearest Marker", "Snap to nearest marker"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 99 of file rna_space.c.
EnumPropertyItem draw_channels_items[] [static]
Initial value:
 {
    {0, "COLOR", ICON_IMAGE_RGB, "Color", "Draw image with RGB colors"},
    {SI_USE_ALPHA, "COLOR_ALPHA", ICON_IMAGE_RGB_ALPHA, "Color and Alpha",
                   "Draw image with RGB colors and alpha transparency"},
    {SI_SHOW_ALPHA, "ALPHA", ICON_IMAGE_ALPHA, "Alpha", "Draw alpha transparency channel"},
    {SI_SHOW_ZBUF, "Z_BUFFER", ICON_IMAGE_ZDEPTH, "Z-Buffer",
                   "Draw Z-buffer associated with image (mapped from camera clip start to end)"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 79 of file rna_space.c.
EnumPropertyItem space_type_items[]
Initial value:
 {
    {SPACE_EMPTY, "EMPTY", 0, "Empty", ""},
    {SPACE_VIEW3D, "VIEW_3D", 0, "3D View", ""},
    {SPACE_IPO, "GRAPH_EDITOR", 0, "Graph Editor", ""},
    {SPACE_OUTLINER, "OUTLINER", 0, "Outliner", ""},
    {SPACE_BUTS, "PROPERTIES", 0, "Properties", ""},
    {SPACE_FILE, "FILE_BROWSER", 0, "File Browser", ""},
    {SPACE_IMAGE, "IMAGE_EDITOR", 0, "Image Editor", ""},
    {SPACE_INFO, "INFO", 0, "Info", ""},
    {SPACE_SEQ, "SEQUENCE_EDITOR", 0, "Sequence Editor", ""},
    {SPACE_TEXT, "TEXT_EDITOR", 0, "Text Editor", ""},
    {SPACE_ACTION, "DOPESHEET_EDITOR", 0, "DopeSheet Editor", ""},
    {SPACE_NLA, "NLA_EDITOR", 0, "NLA Editor", ""},
    {SPACE_TIME, "TIMELINE", 0, "Timeline", ""},
    {SPACE_NODE, "NODE_EDITOR", 0, "Node Editor", ""},
    {SPACE_LOGIC, "LOGIC_EDITOR", 0, "Logic Editor", ""},
    {SPACE_CONSOLE, "CONSOLE", 0, "Python Console", ""},
    {SPACE_USERPREF, "USER_PREFERENCES", 0, "User Preferences", ""},
    {SPACE_CLIP, "CLIP_EDITOR", 0, "Clip Editor", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 58 of file rna_space.c.
Referenced by RNA_api_keymaps(), rna_def_area(), rna_def_header(), rna_def_keyconfig(), and rna_def_panel().
EnumPropertyItem transform_orientation_items[] [static]
Initial value:
 {
    {V3D_MANIP_GLOBAL, "GLOBAL", 0, "Global", "Align the transformation axes to world space"},
    {V3D_MANIP_LOCAL, "LOCAL", 0, "Local", "Align the transformation axes to the selected objects' local space"},
    {V3D_MANIP_GIMBAL, "GIMBAL", 0, "Gimbal", "Align each axis to the Euler rotation axis as used for input"},
    {V3D_MANIP_NORMAL, "NORMAL", 0, "Normal",
                       "Align the transformation axes to average normal of selected elements "
                       "(bone Y axis for pose mode)"},
    {V3D_MANIP_VIEW, "VIEW", 0, "View", "Align the transformation axes to the window"},
    {V3D_MANIP_CUSTOM, "CUSTOM", 0, "Custom", "Use a custom transform orientation"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 88 of file rna_space.c.
EnumPropertyItem viewport_shade_items[]
Initial value:
 {
    {OB_BOUNDBOX, "BOUNDBOX", ICON_BBOX, "Bounding Box", "Display the object's local bounding boxes only"},
    {OB_WIRE, "WIREFRAME", ICON_WIRE, "Wireframe", "Display the object as wire edges"},
    {OB_SOLID, "SOLID", ICON_SOLID, "Solid", "Display the object solid, lit with default OpenGL lights"},
    {OB_TEXTURE, "TEXTURED", ICON_POTATO, "Texture", "Display the object solid, with a texture"},
    {OB_MATERIAL, "MATERIAL", ICON_MATERIAL_DATA, "Material", "Display objects solid, with GLSL material"},
    {OB_RENDER, "RENDERED", ICON_SMOOTH, "Rendered", "Display render preview"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 106 of file rna_space.c.
Referenced by rna_def_scene_render_data().