Blender: KX_ScalarInterpolator Class Reference
KX_ScalarInterpolator Class Reference
#include <KX_ScalarInterpolator.h>
Public Member Functions
KX_ScalarInterpolator (MT_Scalar *target, KX_IScalarInterpolator *ipo)
virtual ~KX_ScalarInterpolator ()
virtual void Execute (float currentTime) const
void SetNewTarget (MT_Scalar *newtarget)
MT_Scalar * GetTarget ()
Detailed Description
Definition at line 40 of file KX_ScalarInterpolator.h.
Constructor & Destructor Documentation
KX_ScalarInterpolator::KX_ScalarInterpolator (MT_Scalar * target, KX_IScalarInterpolator * ipo) [inline]
Definition at line 42 of file KX_ScalarInterpolator.h.
virtual KX_ScalarInterpolator::~KX_ScalarInterpolator () [inline, virtual]
Definition at line 48 of file KX_ScalarInterpolator.h.
Member Function Documentation
void KX_ScalarInterpolator::Execute (float currentTime) const [virtual]
Implements KX_IInterpolator.
Definition at line 36 of file KX_ScalarInterpolator.cpp.
References KX_IScalarInterpolator::GetValue().
MT_Scalar* KX_ScalarInterpolator::GetTarget () [inline]
Definition at line 54 of file KX_ScalarInterpolator.h.
void KX_ScalarInterpolator::SetNewTarget (MT_Scalar * newtarget) [inline]
Definition at line 50 of file KX_ScalarInterpolator.h.
Referenced by KX_CameraIpoSGController::GetReplica(), KX_IpoSGController::GetReplica(), KX_ObColorIpoSGController::GetReplica(), KX_LightIpoSGController::GetReplica(), KX_MaterialIpoController::GetReplica(), and KX_WorldIpoController::GetReplica().
The documentation for this class was generated from the following files:
KX_ScalarInterpolator.h
KX_ScalarInterpolator.cpp