Blender: node_shader_holdout.c File Reference
node_shader_holdout.c File Reference
#include "../node_shader_util.h"
Functions
void register_node_type_sh_holdout (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_holdout_in []
static bNodeSocketTemplate sh_node_holdout_out []
Function Documentation
void register_node_type_sh_holdout (bNodeTreeType * ttype)
Definition at line 43 of file node_shader_holdout.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_HOLDOUT.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_holdout_in[] [static]
Initial value:
 {
    {   -1, 0, ""   }
}
Definition at line 32 of file node_shader_holdout.c.
bNodeSocketTemplate sh_node_holdout_out[] [static]
Initial value:
 {
    {   SOCK_SHADER, 0, "Holdout"},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_shader_holdout.c.