Blender: options.c File Reference
options.c File Reference
AVI
#include "AVI_avi.h"
#include "avi_intern.h"
#include "endian.h"
Functions
AviError AVI_set_compress_option (AviMovie *movie, int option_type, int stream, AviOption option, void *opt_data)
Detailed Description
Definition in file options.c.
Function Documentation
AviError AVI_set_compress_option (AviMovie * movie, int option_type, int stream, AviOption option, void * opt_data)
Choose a compression option for <movie>. Possible options are AVI_OPTION_TYPE_MAIN, AVI_OPTION_TYPE_STRH, AVI_OPTION_TYPE_STRF
Definition at line 47 of file options.c.
References AVI_BITMAPH, AVI_ERROR_NONE, AVI_ERROR_OPTION, avi_get_format_type(), AVI_MAINH, AVI_OPTION_FRAMERATE, AVI_OPTION_HEIGHT, AVI_OPTION_QUALITY, AVI_OPTION_TYPE_MAIN, AVI_OPTION_TYPE_STRF, AVI_OPTION_TYPE_STRH, AVI_OPTION_WIDTH, awrite(), _AviStreamHeader::bottom, FCC, _AviStreamRec::format, _AviMovie::fp, fseek, _AviMovie::header, _AviMainHeader::Height, i, _AviMainHeader::MicroSecPerFrame, _AviMovie::offset_table, _AviStreamHeader::Quality, _AviStreamHeader::right, _AviStreamHeader::Scale, _AviStreamRec::sf, _AviStreamRec::sf_size, _AviStreamRec::sh, _AviMovie::streams, _AviMainHeader::Streams, _AviStreamHeader::SuggestedBufferSize, _AviMainHeader::SuggestedBufferSize, _AviMainHeader::TotalFrames, and _AviMainHeader::Width.
Referenced by alloc_proxy_output_avi(), and start_avi().