Blender: SCA_IObject Class Reference
SCA_IObject Class Reference
#include <SCA_IObject.h>
Public Types
enum ObjectTypes { OBJ_ARMATURE = 0, OBJ_CAMERA = 1, OBJ_LIGHT = 2 }
typedef enum
SCA_IObject::ObjectTypes ObjectTypes
Public Member Functions
SCA_IObject ()
virtual ~SCA_IObject ()
SCA_ControllerList & GetControllers ()
SCA_SensorList & GetSensors ()
SCA_ActuatorList & GetActuators ()
SG_QList & GetActiveActuators ()
void AddSensor (SCA_ISensor *act)
void ReserveSensor (int num)
void AddController (SCA_IController *act)
void ReserveController (int num)
void AddActuator (SCA_IActuator *act)
void ReserveActuator (int num)
void RegisterActuator (SCA_IActuator *act)
void UnregisterActuator (SCA_IActuator *act)
void RegisterObject (SCA_IObject *objs)
void UnregisterObject (SCA_IObject *objs)
virtual bool UnlinkObject (SCA_IObject *clientobj)
SCA_ISensor * FindSensor (const STR_String &sensorname)
SCA_IActuator * FindActuator (const STR_String &actuatorname)
SCA_IController * FindController (const STR_String &controllername)
void SetCurrentTime (float currentTime)
virtual void ReParentLogic ()
void SetIgnoreActivityCulling (bool b)
bool GetIgnoreActivityCulling ()
void Suspend (void)
void Resume (void)
void SetInitState (unsigned int initState)
void ResetState (void)
void SetState (unsigned int state)
unsigned int GetState (void)
virtual int GetGameObjectType ()
Protected Attributes
SCA_SensorList m_sensors
SCA_ControllerList m_controllers
SCA_ActuatorList m_actuators
SCA_ActuatorList m_registeredActuators
SCA_ObjectList m_registeredObjects
SG_QList m_activeActuators
SG_QList m_activeControllers
bool m_ignore_activity_culling
bool m_suspended
unsigned int m_initState
unsigned int m_state
SG_QList * m_firstState
Static Protected Attributes
static SG_QList m_activeBookmarkedControllers
static class MT_Point3 m_sDummy = MT_Point3(0,0,0)
Friends
class KX_StateActuator
class SCA_IActuator
class SCA_IController
Detailed Description
Definition at line 54 of file SCA_IObject.h.
Member Typedef Documentation
typedef enum SCA_IObject::ObjectTypes SCA_IObject::ObjectTypes
Member Enumeration Documentation
enum SCA_IObject::ObjectTypes
Enumerator:
OBJ_ARMATURE
OBJ_CAMERA
OBJ_LIGHT
Definition at line 220 of file SCA_IObject.h.
Constructor & Destructor Documentation
SCA_IObject::SCA_IObject ()
Definition at line 45 of file SCA_IObject.cpp.
References m_suspended.
SCA_IObject::~SCA_IObject () [virtual]
Definition at line 54 of file SCA_IObject.cpp.
References m_actuators, m_controllers, m_registeredActuators, m_registeredObjects, and m_sensors.
Member Function Documentation
void SCA_IObject::AddActuator (SCA_IActuator * act)
Definition at line 108 of file SCA_IObject.cpp.
References CValue::AddRef(), and m_actuators.
Referenced by BL_ConvertActuators().
void SCA_IObject::AddController (SCA_IController * act)
Definition at line 100 of file SCA_IObject.cpp.
References CValue::AddRef(), and m_controllers.
Referenced by BL_ConvertControllers().
void SCA_IObject::AddSensor (SCA_ISensor * act)
Definition at line 92 of file SCA_IObject.cpp.
References CValue::AddRef(), and m_sensors.
Referenced by BL_ConvertSensors().
SCA_IActuator * SCA_IObject::FindActuator (const STR_String & actuatorname)
Definition at line 234 of file SCA_IObject.cpp.
References m_actuators, and NULL.
Referenced by SCA_ActuatorSensor::ReParent(), and SCA_ActuatorSensor::SCA_ActuatorSensor().
SCA_IController * SCA_IObject::FindController (const STR_String & controllername)
Definition at line 217 of file SCA_IObject.cpp.
References m_controllers, and NULL.
SCA_ISensor * SCA_IObject::FindSensor (const STR_String & sensorname)
Definition at line 200 of file SCA_IObject.cpp.
References m_sensors, and NULL.
SG_QList& SCA_IObject::GetActiveActuators () [inline]
Definition at line 129 of file SCA_IObject.h.
References m_activeActuators.
SCA_ActuatorList& SCA_IObject::GetActuators () [inline]
Definition at line 125 of file SCA_IObject.h.
References m_actuators.
Referenced by KX_BlenderSceneConverter::FreeBlendFile(), MergeScene_GameObject(), KX_Scene::NewRemoveObject(), KX_GameObject::Relink(), ReParentLogic(), and KX_Scene::ReplicateLogic().
SCA_ControllerList& SCA_IObject::GetControllers () [inline]
Definition at line 117 of file SCA_IObject.h.
References m_controllers.
Referenced by MergeScene_GameObject(), KX_Scene::NewRemoveObject(), ReParentLogic(), and KX_Scene::ReplicateLogic().
virtual int SCA_IObject::GetGameObjectType () [inline, virtual]
Reimplemented in BL_ArmatureObject, KX_Camera, and KX_LightObject.
Definition at line 218 of file SCA_IObject.h.
Referenced by KX_Scene::AddNodeReplicaObject(), BL_Action::BL_Action(), BL_ConvertBlenderObjects(), KX_ArmatureSensor::FindConstraint(), MergeScene_GameObject(), KX_Scene::NewRemoveObject(), BL_Action::Play(), KX_Scene::ReplaceMesh(), KX_SceneActuator::Update(), BL_Action::Update(), and BL_ArmatureConstraint::UpdateTarget().
bool SCA_IObject::GetIgnoreActivityCulling () [inline]
Set whether or not this object wants to ignore activity culling requests
Definition at line 181 of file SCA_IObject.h.
References m_ignore_activity_culling.
Referenced by KX_Scene::UpdateObjectActivity().
SCA_SensorList& SCA_IObject::GetSensors () [inline]
Definition at line 121 of file SCA_IObject.h.
References m_sensors.
Referenced by MergeScene_GameObject(), KX_Scene::NewRemoveObject(), KX_GameObject::Relink(), ReParentLogic(), and KX_Scene::ReplicateLogic().
unsigned int SCA_IObject::GetState (void) [inline]
Get the object state
Definition at line 214 of file SCA_IObject.h.
References m_state.
Referenced by KX_StateActuator::Update().
void SCA_IObject::RegisterActuator (SCA_IActuator * act)
Definition at line 114 of file SCA_IObject.cpp.
References m_registeredActuators.
Referenced by BL_ArmatureActuator::BL_ArmatureActuator(), KX_SCA_AddObjectActuator::InstantAddObject(), KX_CameraActuator::KX_CameraActuator(), KX_ObjectActuator::KX_ObjectActuator(), KX_ParentActuator::KX_ParentActuator(), KX_SCA_AddObjectActuator::KX_SCA_AddObjectActuator(), KX_SceneActuator::KX_SceneActuator(), KX_SteeringActuator::KX_SteeringActuator(), KX_TrackToActuator::KX_TrackToActuator(), KX_CameraActuator::ProcessReplica(), BL_ArmatureActuator::ProcessReplica(), SCA_PropertyActuator::ProcessReplica(), KX_ParentActuator::ProcessReplica(), KX_ObjectActuator::ProcessReplica(), KX_SCA_AddObjectActuator::ProcessReplica(), KX_SteeringActuator::ProcessReplica(), KX_TrackToActuator::ProcessReplica(), KX_SceneActuator::ProcessReplica(), KX_SCA_AddObjectActuator::Relink(), KX_SceneActuator::Relink(), KX_TrackToActuator::Relink(), KX_CameraActuator::Relink(), KX_ObjectActuator::Relink(), KX_ParentActuator::Relink(), KX_SteeringActuator::Relink(), BL_ArmatureActuator::Relink(), SCA_PropertyActuator::Relink(), and SCA_PropertyActuator::SCA_PropertyActuator().
void SCA_IObject::RegisterObject (SCA_IObject * objs)
Definition at line 133 of file SCA_IObject.cpp.
References m_registeredObjects.
Referenced by BL_ArmatureConstraint::BL_ArmatureConstraint(), BL_ArmatureConstraint::Relink(), BL_ArmatureConstraint::ReParent(), BL_ArmatureConstraint::SetSubtarget(), and BL_ArmatureConstraint::SetTarget().
void SCA_IObject::ReParentLogic () [virtual]
Reimplemented in BL_ArmatureObject.
Definition at line 153 of file SCA_IObject.cpp.
References SCA_ISensor::ClrLink(), SCA_IActuator::ClrLink(), GetActuators(), GetControllers(), SCA_ISensor::GetReplica(), CValue::GetReplica(), GetSensors(), m_registeredActuators, m_registeredObjects, SCA_ISensor::ReParent(), SCA_ILogicBrick::ReParent(), and SCA_ILogicBrick::SetActive().
void SCA_IObject::ReserveActuator (int num) [inline]
Definition at line 145 of file SCA_IObject.h.
References m_actuators.
Referenced by BL_ConvertActuators().
void SCA_IObject::ReserveController (int num) [inline]
Definition at line 140 of file SCA_IObject.h.
References m_controllers.
Referenced by BL_ConvertControllers().
void SCA_IObject::ReserveSensor (int num) [inline]
Definition at line 135 of file SCA_IObject.h.
References m_sensors.
Referenced by BL_ConvertSensors().
void SCA_IObject::ResetState (void) [inline]
initialize the state when object is created
Definition at line 204 of file SCA_IObject.h.
References m_initState, and SetState().
Referenced by BL_ConvertBlenderObjects(), and KX_Scene::ReplicateLogic().
void SCA_IObject::Resume (void)
Resume progress
Reimplemented in KX_GameObject.
Definition at line 267 of file SCA_IObject.cpp.
References i, m_sensors, and m_suspended.
void SCA_IObject::SetCurrentTime (float currentTime) [inline]
Definition at line 165 of file SCA_IObject.h.
void SCA_IObject::SetIgnoreActivityCulling (bool b) [inline]
Set whether or not to ignore activity culling requests
Definition at line 172 of file SCA_IObject.h.
References m_ignore_activity_culling.
Referenced by gameobject_from_blenderobject().
void SCA_IObject::SetInitState (unsigned int initState) [inline]
Set init state
Definition at line 199 of file SCA_IObject.h.
References m_initState.
Referenced by BL_ConvertBlenderObjects().
void SCA_IObject::SetState (unsigned int state)
Set the object state
Definition at line 280 of file SCA_IObject.cpp.
References m_controllers, m_state, and state.
Referenced by ResetState(), and KX_StateActuator::Update().
void SCA_IObject::Suspend (void)
Suspend all progress.
Reimplemented in KX_GameObject.
Definition at line 251 of file SCA_IObject.cpp.
References i, m_ignore_activity_culling, m_sensors, and m_suspended.
virtual bool SCA_IObject::UnlinkObject (SCA_IObject * clientobj) [inline, virtual]
UnlinkObject(...) this object is informed that one of the object to which it holds a reference is deleted returns true if there was indeed a reference.
Reimplemented in BL_ArmatureObject.
Definition at line 159 of file SCA_IObject.h.
void SCA_IObject::UnregisterActuator (SCA_IActuator * act)
Definition at line 120 of file SCA_IObject.cpp.
References m_registeredActuators.
Referenced by KX_SCA_AddObjectActuator::InstantAddObject(), BL_ArmatureActuator::ProcessReplica(), KX_SCA_AddObjectActuator::Relink(), KX_SceneActuator::Relink(), KX_TrackToActuator::Relink(), KX_CameraActuator::Relink(), KX_ObjectActuator::Relink(), KX_ParentActuator::Relink(), KX_SteeringActuator::Relink(), BL_ArmatureActuator::Relink(), SCA_PropertyActuator::Relink(), BL_ArmatureActuator::~BL_ArmatureActuator(), KX_CameraActuator::~KX_CameraActuator(), KX_ObjectActuator::~KX_ObjectActuator(), KX_ParentActuator::~KX_ParentActuator(), KX_SCA_AddObjectActuator::~KX_SCA_AddObjectActuator(), KX_SceneActuator::~KX_SceneActuator(), KX_SteeringActuator::~KX_SteeringActuator(), KX_TrackToActuator::~KX_TrackToActuator(), and SCA_PropertyActuator::~SCA_PropertyActuator().
void SCA_IObject::UnregisterObject (SCA_IObject * objs)
Definition at line 140 of file SCA_IObject.cpp.
References m_registeredObjects.
Referenced by BL_ArmatureConstraint::Relink(), BL_ArmatureConstraint::SetSubtarget(), BL_ArmatureConstraint::SetTarget(), and BL_ArmatureConstraint::~BL_ArmatureConstraint().
Friends And Related Function Documentation
friend class KX_StateActuator [friend]
Definition at line 60 of file SCA_IObject.h.
friend class SCA_IActuator [friend]
Definition at line 61 of file SCA_IObject.h.
friend class SCA_IController [friend]
Definition at line 62 of file SCA_IObject.h.
Member Data Documentation
SG_QList SCA_IObject::m_activeActuators [protected]
Definition at line 73 of file SCA_IObject.h.
Referenced by SCA_IActuator::Activate(), SCA_IActuator::Deactivate(), and GetActiveActuators().
SG_QList SCA_IObject::m_activeBookmarkedControllers [static, protected]
Definition at line 83 of file SCA_IObject.h.
Referenced by SCA_IController::Activate().
SG_QList SCA_IObject::m_activeControllers [protected]
Definition at line 78 of file SCA_IObject.h.
Referenced by SCA_IController::Activate().
SCA_ActuatorList SCA_IObject::m_actuators [protected]
Definition at line 65 of file SCA_IObject.h.
Referenced by AddActuator(), FindActuator(), GetActuators(), ReserveActuator(), and ~SCA_IObject().
SCA_ControllerList SCA_IObject::m_controllers [protected]
Definition at line 64 of file SCA_IObject.h.
Referenced by AddController(), FindController(), GetControllers(), ReserveController(), SetState(), and ~SCA_IObject().
SG_QList* SCA_IObject::m_firstState [protected]
pointer inside state actuator list for sorting
Definition at line 110 of file SCA_IObject.h.
Referenced by KX_StateActuator::Activate(), and KX_StateActuator::Update().
bool SCA_IObject::m_ignore_activity_culling [protected]
Ignore activity culling requests?
Definition at line 90 of file SCA_IObject.h.
Referenced by GetIgnoreActivityCulling(), KX_GameObject::KX_GameObject(), SetIgnoreActivityCulling(), KX_GameObject::Suspend(), and Suspend().
unsigned int SCA_IObject::m_initState [protected]
init state of object (used when object is created)
Definition at line 100 of file SCA_IObject.h.
Referenced by ResetState(), and SetInitState().
SCA_ActuatorList SCA_IObject::m_registeredActuators [protected]
Definition at line 66 of file SCA_IObject.h.
Referenced by RegisterActuator(), ReParentLogic(), UnregisterActuator(), and ~SCA_IObject().
SCA_ObjectList SCA_IObject::m_registeredObjects [protected]
Definition at line 67 of file SCA_IObject.h.
Referenced by RegisterObject(), ReParentLogic(), UnregisterObject(), and ~SCA_IObject().
MT_Point3 SCA_IObject::m_sDummy = MT_Point3(0,0,0) [static, protected]
Definition at line 85 of file SCA_IObject.h.
SCA_SensorList SCA_IObject::m_sensors [protected]
Definition at line 63 of file SCA_IObject.h.
Referenced by AddSensor(), FindSensor(), GetSensors(), ReserveSensor(), Resume(), Suspend(), and ~SCA_IObject().
unsigned int SCA_IObject::m_state [protected]
current state = bit mask of state that are active
Definition at line 105 of file SCA_IObject.h.
Referenced by GetState(), KX_GameObject::ProcessReplica(), and SetState().
bool SCA_IObject::m_suspended [protected]
Ignore updates?
Definition at line 95 of file SCA_IObject.h.
Referenced by KX_GameObject::Resume(), Resume(), SCA_IObject(), KX_GameObject::Suspend(), and Suspend().
The documentation for this class was generated from the following files:
SCA_IObject.h
SCA_IObject.cpp