Blender: IK_QElbowSegment Class Reference
IK_QElbowSegment Class Reference
#include <IK_QSegment.h>
Public Member Functions
IK_QElbowSegment (int axis)
MT_Vector3 Axis (int dof) const
bool UpdateAngle (const IK_QJacobian &jacobian, MT_Vector3 &delta, bool *clamp)
void Lock (int dof, IK_QJacobian &jacobian, MT_Vector3 &delta)
void UpdateAngleApply ()
void SetLimit (int axis, MT_Scalar lmin, MT_Scalar lmax)
void SetWeight (int axis, MT_Scalar weight)
void SetBasis (const MT_Matrix3x3 &basis)
Detailed Description
Definition at line 297 of file IK_QSegment.h.
Constructor & Destructor Documentation
IK_QElbowSegment::IK_QElbowSegment (int axis)
Definition at line 796 of file IK_QSegment.cpp.
Member Function Documentation
MT_Vector3 IK_QElbowSegment::Axis (int dof) const [virtual]
Implements IK_QSegment.
Definition at line 813 of file IK_QSegment.cpp.
References MT_Transform::getBasis(), MT_Matrix3x3::getColumn(), and IK_QSegment::m_global_transform.
void IK_QElbowSegment::Lock (int dof, IK_QJacobian & jacobian, MT_Vector3 & delta) [virtual]
Reimplemented from IK_QSegment.
Definition at line 872 of file IK_QSegment.cpp.
References IK_QJacobian::Lock(), IK_QSegment::m_DoF_id, and IK_QSegment::m_locked.
void IK_QElbowSegment::SetBasis (const MT_Matrix3x3 & basis) [virtual]
Reimplemented from IK_QSegment.
Definition at line 802 of file IK_QSegment.cpp.
References ComputeTwist(), ComputeTwistMatrix(), EulerAngleFromMatrix(), IK_QSegment::m_basis, RemoveTwist(), and RotationMatrix().
void IK_QElbowSegment::SetLimit (int axis, MT_Scalar lmin, MT_Scalar lmax) [virtual]
Reimplemented from IK_QSegment.
Definition at line 898 of file IK_QSegment.cpp.
References MT_clamp(), and MT_PI().
void IK_QElbowSegment::SetWeight (int axis, MT_Scalar weight) [virtual]
Reimplemented from IK_QSegment.
Definition at line 919 of file IK_QSegment.cpp.
References IK_QSegment::m_weight.
bool IK_QElbowSegment::UpdateAngle (const IK_QJacobian & jacobian, MT_Vector3 & delta, bool * clamp) [virtual]
Implements IK_QSegment.
Definition at line 828 of file IK_QSegment.cpp.
References IK_QJacobian::AngleUpdate(), IK_QSegment::m_DoF_id, and IK_QSegment::m_locked.
void IK_QElbowSegment::UpdateAngleApply () [virtual]
Implements IK_QSegment.
Definition at line 884 of file IK_QSegment.cpp.
References A, cos(), IK_QSegment::m_basis, RotationMatrix(), sin(), and T.
The documentation for this class was generated from the following files:
IK_QSegment.h
IK_QSegment.cpp