Blender: RNA_define.h File Reference
RNA_define.h File Reference
RNA
#include <float.h>
#include <limits.h>
#include "DNA_listBase.h"
#include "RNA_types.h"
Defines
#define IS_DNATYPE_FLOAT_COMPAT(_str) (strcmp(_str, "float") == 0 || strcmp(_str, "double") == 0)
#define IS_DNATYPE_INT_COMPAT(_str) (strcmp(_str, "int") == 0 || strcmp(_str, "short") == 0 || strcmp(_str, "char") == 0)
#define RNA_DYN_DESCR_MAX 240
Typedefs
typedef void StructOrFunctionRNA
Functions
BlenderRNA * RNA_create (void)
void RNA_define_free (BlenderRNA *brna)
void RNA_free (BlenderRNA *brna)
void RNA_define_verify_sdna (int verify)
void RNA_init (void)
void RNA_exit (void)
StructRNA * RNA_def_struct (BlenderRNA *brna, const char *identifier, const char *from)
void RNA_def_struct_sdna (StructRNA *srna, const char *structname)
void RNA_def_struct_sdna_from (StructRNA *srna, const char *structname, const char *propname)
void RNA_def_struct_name_property (StructRNA *srna, PropertyRNA *prop)
void RNA_def_struct_nested (BlenderRNA *brna, StructRNA *srna, const char *structname)
void RNA_def_struct_flag (StructRNA *srna, int flag)
void RNA_def_struct_clear_flag (StructRNA *srna, int flag)
void RNA_def_struct_refine_func (StructRNA *srna, const char *refine)
void RNA_def_struct_idprops_func (StructRNA *srna, const char *refine)
void RNA_def_struct_register_funcs (StructRNA *srna, const char *reg, const char *unreg, const char *instance)
void RNA_def_struct_path_func (StructRNA *srna, const char *path)
void RNA_def_struct_identifier (StructRNA *srna, const char *identifier)
void RNA_def_struct_ui_text (StructRNA *srna, const char *name, const char *description)
void RNA_def_struct_ui_icon (StructRNA *srna, int icon)
void RNA_struct_free_extension (StructRNA *srna, ExtensionRNA *ext)
void RNA_struct_free (BlenderRNA *brna, StructRNA *srna)
void RNA_def_struct_translation_context (StructRNA *srna, const char *context)
PropertyRNA * RNA_def_boolean (StructOrFunctionRNA *cont, const char *identifier, int default_value, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_boolean_array (StructOrFunctionRNA *cont, const char *identifier, int len, int *default_value, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_boolean_layer (StructOrFunctionRNA *cont, const char *identifier, int len, int *default_value, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_boolean_layer_member (StructOrFunctionRNA *cont, const char *identifier, int len, int *default_value, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_boolean_vector (StructOrFunctionRNA *cont, const char *identifier, int len, int *default_value, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_int (StructOrFunctionRNA *cont, const char *identifier, int default_value, int hardmin, int hardmax, const char *ui_name, const char *ui_description, int softmin, int softmax)
PropertyRNA * RNA_def_int_vector (StructOrFunctionRNA *cont, const char *identifier, int len, const int *default_value, int hardmin, int hardmax, const char *ui_name, const char *ui_description, int softmin, int softmax)
PropertyRNA * RNA_def_int_array (StructOrFunctionRNA *cont, const char *identifier, int len, const int *default_value, int hardmin, int hardmax, const char *ui_name, const char *ui_description, int softmin, int softmax)
PropertyRNA * RNA_def_string (StructOrFunctionRNA *cont, const char *identifier, const char *default_value, int maxlen, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_string_file_path (StructOrFunctionRNA *cont, const char *identifier, const char *default_value, int maxlen, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_string_dir_path (StructOrFunctionRNA *cont, const char *identifier, const char *default_value, int maxlen, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_string_file_name (StructOrFunctionRNA *cont, const char *identifier, const char *default_value, int maxlen, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_string_translate (StructOrFunctionRNA *cont, const char *identifier, const char *default_value, int maxlen, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_enum (StructOrFunctionRNA *cont, const char *identifier, const EnumPropertyItem *items, int default_value, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_enum_flag (StructOrFunctionRNA *cont, const char *identifier, const EnumPropertyItem *items, int default_value, const char *ui_name, const char *ui_description)
void RNA_def_enum_funcs (PropertyRNA *prop, EnumPropertyItemFunc itemfunc)
void RNA_def_enum_py_data (PropertyRNA *prop, void *py_data)
PropertyRNA * RNA_def_float (StructOrFunctionRNA *cont, const char *identifier, float default_value, float hardmin, float hardmax, const char *ui_name, const char *ui_description, float softmin, float softmax)
PropertyRNA * RNA_def_float_vector (StructOrFunctionRNA *cont, const char *identifier, int len, const float *default_value, float hardmin, float hardmax, const char *ui_name, const char *ui_description, float softmin, float softmax)
PropertyRNA * RNA_def_float_vector_xyz (StructOrFunctionRNA *cont, const char *identifier, int len, const float *default_value, float hardmin, float hardmax, const char *ui_name, const char *ui_description, float softmin, float softmax)
PropertyRNA * RNA_def_float_color (StructOrFunctionRNA *cont, const char *identifier, int len, const float *default_value, float hardmin, float hardmax, const char *ui_name, const char *ui_description, float softmin, float softmax)
PropertyRNA * RNA_def_float_matrix (StructOrFunctionRNA *cont, const char *identifier, int rows, int columns, const float *default_value, float hardmin, float hardmax, const char *ui_name, const char *ui_description, float softmin, float softmax)
PropertyRNA * RNA_def_float_rotation (StructOrFunctionRNA *cont, const char *identifier, int len, const float *default_value, float hardmin, float hardmax, const char *ui_name, const char *ui_description, float softmin, float softmax)
PropertyRNA * RNA_def_float_array (StructOrFunctionRNA *cont, const char *identifier, int len, const float *default_value, float hardmin, float hardmax, const char *ui_name, const char *ui_description, float softmin, float softmax)
PropertyRNA * RNA_def_float_percentage (StructOrFunctionRNA *cont, const char *identifier, float default_value, float hardmin, float hardmax, const char *ui_name, const char *ui_description, float softmin, float softmax)
PropertyRNA * RNA_def_float_factor (StructOrFunctionRNA *cont, const char *identifier, float default_value, float hardmin, float hardmax, const char *ui_name, const char *ui_description, float softmin, float softmax)
PropertyRNA * RNA_def_pointer (StructOrFunctionRNA *cont, const char *identifier, const char *type, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_pointer_runtime (StructOrFunctionRNA *cont, const char *identifier, StructRNA *type, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_collection (StructOrFunctionRNA *cont, const char *identifier, const char *type, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_collection_runtime (StructOrFunctionRNA *cont, const char *identifier, StructRNA *type, const char *ui_name, const char *ui_description)
PropertyRNA * RNA_def_property (StructOrFunctionRNA *cont, const char *identifier, int type, int subtype)
void RNA_def_property_boolean_sdna (PropertyRNA *prop, const char *structname, const char *propname, int bit)
void RNA_def_property_boolean_negative_sdna (PropertyRNA *prop, const char *structname, const char *propname, int bit)
void RNA_def_property_int_sdna (PropertyRNA *prop, const char *structname, const char *propname)
void RNA_def_property_float_sdna (PropertyRNA *prop, const char *structname, const char *propname)
void RNA_def_property_string_sdna (PropertyRNA *prop, const char *structname, const char *propname)
void RNA_def_property_enum_sdna (PropertyRNA *prop, const char *structname, const char *propname)
void RNA_def_property_enum_bitflag_sdna (PropertyRNA *prop, const char *structname, const char *propname)
void RNA_def_property_pointer_sdna (PropertyRNA *prop, const char *structname, const char *propname)
void RNA_def_property_collection_sdna (PropertyRNA *prop, const char *structname, const char *propname, const char *lengthpropname)
void RNA_def_property_flag (PropertyRNA *prop, int flag)
void RNA_def_property_clear_flag (PropertyRNA *prop, int flag)
void RNA_def_property_subtype (PropertyRNA *prop, PropertySubType subtype)
void RNA_def_property_array (PropertyRNA *prop, int length)
void RNA_def_property_multi_array (PropertyRNA *prop, int dimension, const int length[])
void RNA_def_property_range (PropertyRNA *prop, double min, double max)
void RNA_def_property_enum_items (PropertyRNA *prop, const EnumPropertyItem *item)
void RNA_def_property_string_maxlength (PropertyRNA *prop, int maxlength)
void RNA_def_property_struct_type (PropertyRNA *prop, const char *type)
void RNA_def_property_struct_runtime (PropertyRNA *prop, StructRNA *type)
void RNA_def_property_boolean_default (PropertyRNA *prop, int value)
void RNA_def_property_boolean_array_default (PropertyRNA *prop, const int *array)
void RNA_def_property_int_default (PropertyRNA *prop, int value)
void RNA_def_property_int_array_default (PropertyRNA *prop, const int *array)
void RNA_def_property_float_default (PropertyRNA *prop, float value)
void RNA_def_property_float_array_default (PropertyRNA *prop, const float *array)
void RNA_def_property_enum_default (PropertyRNA *prop, int value)
void RNA_def_property_string_default (PropertyRNA *prop, const char *value)
void RNA_def_property_ui_text (PropertyRNA *prop, const char *name, const char *description)
void RNA_def_property_ui_range (PropertyRNA *prop, double min, double max, double step, int precision)
void RNA_def_property_ui_icon (PropertyRNA *prop, int icon, int consecutive)
void RNA_def_property_update (PropertyRNA *prop, int noteflag, const char *updatefunc)
void RNA_def_property_editable_func (PropertyRNA *prop, const char *editable)
void RNA_def_property_editable_array_func (PropertyRNA *prop, const char *editable)
void RNA_def_property_update_runtime (PropertyRNA *prop, void *func)
void RNA_def_property_dynamic_array_funcs (PropertyRNA *prop, const char *getlength)
void RNA_def_property_boolean_funcs (PropertyRNA *prop, const char *get, const char *set)
void RNA_def_property_int_funcs (PropertyRNA *prop, const char *get, const char *set, const char *range)
void RNA_def_property_float_funcs (PropertyRNA *prop, const char *get, const char *set, const char *range)
void RNA_def_property_enum_funcs (PropertyRNA *prop, const char *get, const char *set, const char *item)
void RNA_def_property_string_funcs (PropertyRNA *prop, const char *get, const char *length, const char *set)
void RNA_def_property_pointer_funcs (PropertyRNA *prop, const char *get, const char *set, const char *typef, const char *poll)
void RNA_def_property_collection_funcs (PropertyRNA *prop, const char *begin, const char *next, const char *end, const char *get, const char *length, const char *lookupint, const char *lookupstring, const char *assignint)
void RNA_def_property_srna (PropertyRNA *prop, const char *type)
void RNA_def_py_data (PropertyRNA *prop, void *py_data)
void RNA_def_property_translation_context (PropertyRNA *prop, const char *context)
FunctionRNA * RNA_def_function (StructRNA *srna, const char *identifier, const char *call)
FunctionRNA * RNA_def_function_runtime (StructRNA *srna, const char *identifier, CallFunc call)
void RNA_def_function_return (FunctionRNA *func, PropertyRNA *ret)
void RNA_def_function_output (FunctionRNA *func, PropertyRNA *ret)
void RNA_def_function_flag (FunctionRNA *func, int flag)
void RNA_def_function_ui_description (FunctionRNA *func, const char *description)
void RNA_enum_item_add (EnumPropertyItem **items, int *totitem, const EnumPropertyItem *item)
void RNA_enum_item_add_separator (EnumPropertyItem **items, int *totitem)
void RNA_enum_items_add (EnumPropertyItem **items, int *totitem, EnumPropertyItem *item)
void RNA_enum_items_add_value (EnumPropertyItem **items, int *totitem, EnumPropertyItem *item, int value)
void RNA_enum_item_end (EnumPropertyItem **items, int *totitem)
void RNA_def_struct_duplicate_pointers (StructRNA *srna)
void RNA_def_struct_free_pointers (StructRNA *srna)
void RNA_def_func_duplicate_pointers (FunctionRNA *func)
void RNA_def_func_free_pointers (FunctionRNA *func)
void RNA_def_property_duplicate_pointers (StructOrFunctionRNA *cont_, PropertyRNA *prop)
void RNA_def_property_free_pointers (PropertyRNA *prop)
int RNA_def_property_free_identifier (StructOrFunctionRNA *cont_, const char *identifier)
const char * RNA_property_typename (PropertyType type)
Detailed Description
Functions used during preprocess and runtime, for defining the RNA.
Definition in file RNA_define.h.
Define Documentation
#define IS_DNATYPE_FLOAT_COMPAT (_str) (strcmp(_str, "float") == 0 || strcmp(_str, "double") == 0)
Definition at line 212 of file RNA_define.h.
Referenced by rna_color_quantize(), RNA_def_property_float_sdna(), and rna_def_property_get_func().
#define IS_DNATYPE_INT_COMPAT (_str) (strcmp(_str, "int") == 0 || strcmp(_str, "short") == 0 || strcmp(_str, "char") == 0)
Definition at line 213 of file RNA_define.h.
Referenced by RNA_def_property_boolean_sdna(), rna_def_property_get_func(), and RNA_def_property_int_sdna().
#define RNA_DYN_DESCR_MAX 240
Definition at line 217 of file RNA_define.h.
Referenced by rna_def_keyingset(), rna_def_keyingset_info(), rna_def_macro_operator(), rna_def_menu(), and rna_def_operator().
Typedef Documentation
typedef void StructOrFunctionRNA
Definition at line 73 of file RNA_define.h.
Function Documentation
BlenderRNA* RNA_create (void)
Definition at line 445 of file rna_define.c.
References DNA_sdna_from_data(), DNAlen, DNAstr, BlenderDefRNA::error, ListBase::first, ListBase::last, MEM_callocN(), NULL, BlenderDefRNA::preprocess, BlenderDefRNA::sdna, and BlenderDefRNA::structs.
Referenced by rna_preprocess().
PropertyRNA* RNA_def_boolean (StructOrFunctionRNA * cont, const char * identifier, int default_value, const char * ui_name, const char * ui_description)
Definition at line 2144 of file rna_define.c.
References PROP_BOOLEAN, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_default(), and RNA_def_property_ui_text().
Referenced by ACTION_OT_clickselect(), ACTION_OT_select_all_toggle(), ACTION_OT_select_border(), ACTION_OT_select_leftright(), ANIM_OT_channels_click(), ANIM_OT_channels_collapse(), ANIM_OT_channels_expand(), ANIM_OT_channels_select_all_toggle(), ANIM_OT_driver_button_add(), ANIM_OT_driver_button_remove(), ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_delete_button(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_button(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keyingset_button_add(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_extrude(), ARMATURE_OT_hide(), ARMATURE_OT_layers_show_all(), ARMATURE_OT_select_hierarchy(), ARMATURE_OT_select_linked(), CLIP_OT_clear_track_path(), CLIP_OT_graph_select(), CLIP_OT_hide_tracks(), CLIP_OT_mode_set(), CLIP_OT_select(), CLIP_OT_set_origin(), CLIP_OT_track_markers(), CLIP_OT_view_all(), CONSOLE_OT_clear(), CONSOLE_OT_history_append(), CONSOLE_OT_history_cycle(), CURVE_OT_hide(), CURVE_OT_select_linked_pick(), CURVE_OT_select_random(), ED_object_add_generic_props(), FILE_OT_execute(), FILE_OT_select(), FONT_OT_line_break(), FONT_OT_style_set(), FONT_OT_text_insert(), GRAPH_OT_clickselect(), GRAPH_OT_fmodifier_add(), GRAPH_OT_select_all_toggle(), GRAPH_OT_select_border(), GRAPH_OT_select_leftright(), GRAPH_OT_sound_bake(), IMAGE_OT_cycle_render_slot(), IMAGE_OT_invert(), IMAGE_OT_new(), IMAGE_OT_pack(), IMAGE_OT_save_as(), MARKER_OT_select(), MBALL_OT_hide_metaelems(), MESH_OT_bevel(), MESH_OT_blend_from_shape(), MESH_OT_bridge_edge_loops(), MESH_OT_dissolve(), MESH_OT_dupli_extrude_cursor(), MESH_OT_edgering_select(), MESH_OT_extrude_edges_indiv(), MESH_OT_extrude_faces_indiv(), MESH_OT_extrude_region(), MESH_OT_extrude_verts_indiv(), MESH_OT_hide(), MESH_OT_inset(), MESH_OT_knife_tool(), MESH_OT_loop_multi_select(), MESH_OT_loop_select(), MESH_OT_loop_to_region(), MESH_OT_mark_seam(), MESH_OT_mark_sharp(), MESH_OT_merge(), MESH_OT_normals_make_consistent(), MESH_OT_quads_convert_to_tris(), MESH_OT_rip(), MESH_OT_select_linked(), MESH_OT_select_linked_pick(), MESH_OT_select_mirror(), MESH_OT_select_random(), MESH_OT_select_shortest_path(), MESH_OT_spin(), MESH_OT_subdivide(), MESH_OT_tris_convert_to_quads(), NLA_OT_action_sync_length(), NLA_OT_channels_click(), NLA_OT_click_select(), NLA_OT_fmodifier_add(), NLA_OT_select_all_toggle(), NLA_OT_select_border(), NLA_OT_select_leftright(), NLA_OT_tracks_add(), NODE_OT_duplicate(), NODE_OT_link_make(), NODE_OT_select(), NODE_OT_select_border(), OBJECT_OT_add_named(), OBJECT_OT_convert(), OBJECT_OT_delete(), OBJECT_OT_duplicate(), OBJECT_OT_duplicates_make_real(), OBJECT_OT_hide_render_set(), OBJECT_OT_hide_view_set(), OBJECT_OT_make_single_user(), OBJECT_OT_mode_set(), OBJECT_OT_ocean_bake(), OBJECT_OT_select_by_layer(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_select_mirror(), OBJECT_OT_select_random(), OBJECT_OT_shape_key_add(), OBJECT_OT_transform_apply(), OBJECT_OT_vertex_group_assign(), OBJECT_OT_vertex_group_clean(), OBJECT_OT_vertex_group_invert(), OBJECT_OT_vertex_group_mirror(), OBJECT_OT_vertex_group_normalize_all(), OBJECT_OT_vertex_group_remove(), OBJECT_OT_vertex_group_remove_from(), OUTLINER_OT_item_activate(), OUTLINER_OT_item_openclose(), OUTLINER_OT_scroll_page(), OUTLINER_OT_show_one_level(), PAINT_OT_face_select_hide(), PAINT_OT_face_select_linked_pick(), PAINT_OT_face_select_reveal(), PARTICLE_OT_connect_hair(), PARTICLE_OT_disconnect_hair(), PARTICLE_OT_hide(), PARTICLE_OT_select_linked(), POSE_OT_hide(), POSE_OT_ik_add(), POSE_OT_paste(), POSE_OT_select_grouped(), POSE_OT_select_hierarchy(), POSE_OT_select_linked(), PTCACHE_OT_bake(), PTCACHE_OT_bake_all(), RENDER_OT_opengl(), RENDER_OT_render(), RNA_api_image(), RNA_api_keymapitem(), RNA_api_keymapitems(), RNA_api_keymaps(), RNA_api_macro(), RNA_api_mesh(), RNA_api_object(), RNA_api_operator(), RNA_api_scene(), RNA_api_ui_layout(), RNA_api_wm(), rna_def_canvas_surface(), rna_def_fcurve_keyframe_points(), rna_def_group_sockets_api(), rna_def_ID_materials(), rna_def_keyingset_info(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_gpencil(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_libraries(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_movieclips(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_screens(), RNA_def_main_sounds(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_window_managers(), RNA_def_main_worlds(), rna_def_menu(), rna_def_panel(), rna_def_render_engine(), SCREEN_OT_animation_cancel(), SCREEN_OT_animation_play(), SCREEN_OT_frame_jump(), SCREEN_OT_keyframe_jump(), SCREEN_OT_screencast(), SCREEN_OT_screenshot(), SCULPT_OT_brush_stroke(), sequencer_generic_props__internal(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_mute(), SEQUENCER_OT_reload(), SEQUENCER_OT_select(), SEQUENCER_OT_select_grouped(), SEQUENCER_OT_select_linked_pick(), SEQUENCER_OT_sound_strip_add(), SEQUENCER_OT_unmute(), SKETCH_OT_draw_preview(), SKETCH_OT_draw_stroke(), SKETCH_OT_gesture(), SOUND_OT_open(), SOUND_OT_open_mono(), TEXT_OT_open(), TEXT_OT_paste(), TEXT_OT_selection_set(), TEXT_OT_to_3d_object(), TRANSFORM_OT_create_orientation(), Transform_Properties(), UI_OT_copy_to_selected_button(), UI_OT_reset_default_button(), uv_map_clip_correct_properties(), UV_OT_from_view(), UV_OT_hide(), UV_OT_minimize_stretch(), UV_OT_pin(), UV_OT_seams_from_islands(), UV_OT_select(), UV_OT_select_border(), UV_OT_select_linked(), UV_OT_select_linked_pick(), UV_OT_select_loop(), UV_OT_stitch(), UV_OT_unwrap(), VIEW2D_OT_scroll_down(), VIEW2D_OT_scroll_up(), VIEW3D_OT_enable_manipulator(), VIEW3D_OT_layers(), VIEW3D_OT_select(), VIEW3D_OT_select_lasso(), VIEW3D_OT_select_menu(), VIEW3D_OT_view_all(), VIEW3D_OT_viewnumpad(), WM_operator_properties_filesel(), WM_operator_properties_gesture_border(), WM_OT_link_append(), WM_OT_ndof_sensitivity_change(), WM_OT_open_mainfile(), WM_OT_save_as_mainfile(), and WM_OT_save_mainfile().
PropertyRNA* RNA_def_boolean_array (StructOrFunctionRNA * cont, const char * identifier, int len, int * default_value, const char * ui_name, const char * ui_description)
Definition at line 2157 of file rna_define.c.
References PROP_BOOLEAN, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_array_default(), and RNA_def_property_ui_text().
Referenced by RNA_def_test().
PropertyRNA* RNA_def_boolean_layer (StructOrFunctionRNA * cont, const char * identifier, int len, int * default_value, const char * ui_name, const char * ui_description)
Definition at line 2171 of file rna_define.c.
References PROP_BOOLEAN, PROP_LAYER, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_array_default(), and RNA_def_property_ui_text().
PropertyRNA* RNA_def_boolean_layer_member (StructOrFunctionRNA * cont, const char * identifier, int len, int * default_value, const char * ui_name, const char * ui_description)
Definition at line 2185 of file rna_define.c.
References PROP_BOOLEAN, PROP_LAYER_MEMBER, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_array_default(), and RNA_def_property_ui_text().
Referenced by ARMATURE_OT_armature_layers(), ARMATURE_OT_bone_layers(), ED_object_add_generic_props(), OBJECT_OT_move_to_layer(), POSE_OT_armature_layers(), and POSE_OT_bone_layers().
PropertyRNA* RNA_def_boolean_vector (StructOrFunctionRNA * cont, const char * identifier, int len, int * default_value, const char * ui_name, const char * ui_description)
Definition at line 2199 of file rna_define.c.
References PROP_BOOLEAN, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_array_default(), and RNA_def_property_ui_text().
Referenced by Transform_Properties().
PropertyRNA* RNA_def_collection (StructOrFunctionRNA * cont, const char * identifier, const char * type, const char * ui_name, const char * ui_description)
Definition at line 2567 of file rna_define.c.
References PROP_COLLECTION, PROP_NONE, RNA_def_property(), RNA_def_property_struct_type(), and RNA_def_property_ui_text().
PropertyRNA* RNA_def_collection_runtime (StructOrFunctionRNA * cont, const char * identifier, StructRNA * type, const char * ui_name, const char * ui_description)
Definition at line 2580 of file rna_define.c.
References PROP_COLLECTION, PROP_NONE, RNA_def_property(), RNA_def_property_struct_runtime(), and RNA_def_property_ui_text().
Referenced by BPy_CollectionProperty(), GPENCIL_OT_draw(), PAINT_OT_image_paint(), PAINT_OT_vertex_paint(), PAINT_OT_weight_paint(), PARTICLE_OT_brush_edit(), SCULPT_OT_brush_stroke(), UV_OT_stitch(), VIEW3D_OT_select_lasso(), and WM_operator_properties_filesel().
PropertyRNA* RNA_def_enum (StructOrFunctionRNA * cont, const char * identifier, const EnumPropertyItem * items, int default_value, const char * ui_name, const char * ui_description)
Definition at line 2332 of file rna_define.c.
References NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_default(), RNA_def_property_enum_items(), and RNA_def_property_ui_text().
Referenced by ACTION_OT_extrapolation_type(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_mirror(), ACTION_OT_paste(), ACTION_OT_select_column(), ACTION_OT_select_leftright(), ACTION_OT_snap(), ANIM_OT_channels_editable_toggle(), ANIM_OT_channels_move(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), ANIM_OT_channels_setting_toggle(), ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_active_set(), ARMATURE_OT_autoside_names(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), ARMATURE_OT_parent_set(), ARMATURE_OT_select_hierarchy(), BOID_OT_rule_add(), BPy_EnumProperty(), BRUSH_OT_curve_preset(), BRUSH_OT_uv_sculpt_tool_set(), CLIP_OT_clean_tracks(), CLIP_OT_clear_track_path(), CLIP_OT_detect_features(), CLIP_OT_disable_markers(), CLIP_OT_frame_jump(), CLIP_OT_graph_disable_markers(), CLIP_OT_lock_tracks(), CLIP_OT_mode_set(), CLIP_OT_select_grouped(), CLIP_OT_set_axis(), CLIP_OT_set_plane(), CONSOLE_OT_delete(), CONSOLE_OT_move(), CONSOLE_OT_scrollback_append(), CURVE_OT_cyclic_toggle(), CURVE_OT_delete(), CURVE_OT_extrude(), CURVE_OT_handle_type_set(), CURVE_OT_spline_type_set(), DPAINT_OT_output_toggle(), DPAINT_OT_type_toggle(), edit_constraint_properties(), FILE_OT_unpack_all(), FONT_OT_case_set(), FONT_OT_delete(), FONT_OT_move(), FONT_OT_move_select(), FONT_OT_style_set(), FONT_OT_style_toggle(), GPENCIL_OT_convert(), GPENCIL_OT_draw(), GRAPH_OT_duplicate(), GRAPH_OT_extrapolation_type(), GRAPH_OT_fmodifier_add(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_paste(), GRAPH_OT_select_column(), GRAPH_OT_select_leftright(), GRAPH_OT_snap(), IMAGE_OT_curves_point_set(), IMAGE_OT_unpack(), LOGIC_OT_actuator_add(), LOGIC_OT_actuator_move(), LOGIC_OT_controller_add(), LOGIC_OT_controller_move(), LOGIC_OT_sensor_add(), LOGIC_OT_sensor_move(), MARKER_OT_make_links_scene(), MBALL_OT_duplicate_metaelems(), MESH_OT_blend_from_shape(), MESH_OT_colors_rotate(), MESH_OT_delete(), MESH_OT_edge_rotate(), MESH_OT_knife_cut(), MESH_OT_merge(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_select_axis(), MESH_OT_select_by_number_vertices(), MESH_OT_select_similar(), MESH_OT_select_vertex_path(), MESH_OT_separate(), MESH_OT_sort_faces(), MESH_OT_subdivide(), MESH_OT_uvs_rotate(), NLA_OT_actionclip_add(), NLA_OT_duplicate(), NLA_OT_fmodifier_add(), NLA_OT_select_leftright(), NLA_OT_snap(), NODE_OT_group_socket_add(), NODE_OT_group_socket_move_down(), NODE_OT_group_socket_move_up(), NODE_OT_group_socket_remove(), NODE_OT_new_node_tree(), OBJECT_OT_add(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_convert(), OBJECT_OT_duplicate(), OBJECT_OT_effector_add(), OBJECT_OT_game_property_copy(), OBJECT_OT_game_property_new(), OBJECT_OT_group_instance_add(), OBJECT_OT_group_link(), OBJECT_OT_hook_assign(), OBJECT_OT_hook_recenter(), OBJECT_OT_hook_remove(), OBJECT_OT_hook_reset(), OBJECT_OT_hook_select(), OBJECT_OT_lamp_add(), OBJECT_OT_make_links_data(), OBJECT_OT_make_links_scene(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_metaball_add(), OBJECT_OT_mode_set(), OBJECT_OT_modifier_add(), OBJECT_OT_modifier_apply(), OBJECT_OT_origin_set(), OBJECT_OT_parent_clear(), OBJECT_OT_parent_set(), OBJECT_OT_proxy_make(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_shape_key_move(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), OBJECT_OT_vertex_group_move(), OBJECT_OT_vertex_group_set_active(), OUTLINER_OT_action_set(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_object_operation(), OUTLINER_OT_parent_clear(), OUTLINER_OT_parent_drop(), PAINT_OT_brush_select(), PAINT_OT_hide_show(), PAINT_OT_project_image(), PAINT_OT_weight_from_bones(), PAINT_OT_weight_sample_group(), PARTICLE_OT_delete(), POSE_OT_autoside_names(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_group_move(), POSE_OT_propagate(), POSE_OT_rotation_mode_set(), POSE_OT_select_grouped(), POSE_OT_select_hierarchy(), POSELIB_OT_pose_remove(), POSELIB_OT_pose_rename(), RNA_api_image(), RNA_api_keymapitems(), RNA_api_keymaps(), RNA_api_object(), RNA_api_ui_layout(), rna_def_composite_nodetree_api(), rna_def_curve_splines(), rna_def_fcurve_modifiers(), rna_def_gpencil_layers(), rna_def_group_sockets_api(), rna_def_keyingset_paths(), RNA_def_main_curves(), RNA_def_main_lamps(), RNA_def_main_node_groups(), RNA_def_main_textures(), rna_def_metaball_elements(), rna_def_object_constraints(), rna_def_object_modifiers(), rna_def_pose_channel_constraints(), rna_def_shader_nodetree_api(), rna_def_texture_nodetree_api(), rna_def_vertex_group(), SCENE_OT_new(), SCREEN_OT_area_split(), SCULPT_OT_brush_stroke(), SCULPT_OT_uv_sculpt_stroke(), SEQUENCER_OT_change_effect_input(), SEQUENCER_OT_change_effect_type(), SEQUENCER_OT_cut(), SEQUENCER_OT_duplicate(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_scene_strip_add(), SEQUENCER_OT_select_active_side(), SEQUENCER_OT_select_grouped(), SEQUENCER_OT_select_handles(), SEQUENCER_OT_swap(), SOUND_OT_mixdown(), SOUND_OT_unpack(), TEXT_OT_convert_whitespace(), TEXT_OT_delete(), TEXT_OT_move(), TEXT_OT_move_select(), TEXT_OT_resolve_conflict(), TEXTURE_OT_slot_move(), TRANSFORM_OT_snap_type(), TRANSFORM_OT_transform(), Transform_Properties(), UV_OT_align(), UV_OT_snap_cursor(), UV_OT_snap_selected(), UV_OT_unwrap(), uv_transform_properties(), VIEW3D_OT_select_menu(), VIEW3D_OT_view_orbit(), VIEW3D_OT_view_pan(), VIEW3D_OT_viewnumpad(), WM_operator_properties_filesel(), WM_operator_properties_select_all(), and WM_OT_redraw_timer().
PropertyRNA* RNA_def_enum_flag (StructOrFunctionRNA * cont, const char * identifier, const EnumPropertyItem * items, int default_value, const char * ui_name, const char * ui_description)
Definition at line 2352 of file rna_define.c.
References NULL, PROP_ENUM, PROP_ENUM_FLAG, PROP_NONE, RNA_def_property(), RNA_def_property_enum_default(), RNA_def_property_enum_items(), RNA_def_property_flag(), and RNA_def_property_ui_text().
Referenced by BPy_EnumProperty(), RNA_api_macro(), RNA_api_operator(), rna_def_fcurve_keyframe_points(), rna_def_ID(), rna_def_render_engine(), and rna_generic_op_invoke().
void RNA_def_enum_funcs (PropertyRNA * prop, EnumPropertyItemFunc itemfunc)
Definition at line 2372 of file rna_define.c.
References EnumPropertyRNA::itemf.
Referenced by ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_active_set(), BPy_EnumProperty(), LOGIC_OT_actuator_add(), LOGIC_OT_sensor_add(), MARKER_OT_make_links_scene(), MESH_OT_blend_from_shape(), MESH_OT_merge(), MESH_OT_select_similar(), NLA_OT_actionclip_add(), OBJECT_OT_game_property_copy(), OBJECT_OT_group_instance_add(), OBJECT_OT_group_link(), OBJECT_OT_hook_assign(), OBJECT_OT_hook_recenter(), OBJECT_OT_hook_remove(), OBJECT_OT_hook_reset(), OBJECT_OT_hook_select(), OBJECT_OT_make_links_scene(), OBJECT_OT_mode_set(), OBJECT_OT_modifier_add(), OBJECT_OT_proxy_make(), OBJECT_OT_vertex_group_set_active(), OUTLINER_OT_action_set(), PAINT_OT_project_image(), PAINT_OT_weight_sample_group(), POSELIB_OT_pose_remove(), POSELIB_OT_pose_rename(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_scene_strip_add(), TRANSFORM_OT_select_orientation(), Transform_Properties(), and VIEW3D_OT_select_menu().
void RNA_def_enum_py_data (PropertyRNA * prop, void * py_data)
Definition at line 2378 of file rna_define.c.
References EnumPropertyRNA::py_data.
Referenced by BPy_EnumProperty().
PropertyRNA* RNA_def_float (StructOrFunctionRNA * cont, const char * identifier, float default_value, float hardmin, float hardmax, const char * ui_name, const char * ui_description, float softmin, float softmax)
Definition at line 2384 of file rna_define.c.
References PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_float_default(), RNA_def_property_range(), RNA_def_property_ui_range(), and RNA_def_property_ui_text().
Referenced by ACTION_OT_clean(), BRUSH_OT_scale_size(), CLIP_OT_clean_tracks(), CLIP_OT_set_scale(), CLIP_OT_set_solution_scale(), CLIP_OT_view_zoom(), CLIP_OT_view_zoom_ratio(), CURVE_OT_radius_set(), GRAPH_OT_clean(), GRAPH_OT_click_insert(), GRAPH_OT_cursor_set(), GRAPH_OT_sound_bake(), IMAGE_OT_view_zoom(), IMAGE_OT_view_zoom_ratio(), MESH_OT_bevel(), MESH_OT_blend_from_shape(), MESH_OT_edges_select_sharp(), MESH_OT_extrude_repeat(), MESH_OT_faces_select_linked_flat(), MESH_OT_inset(), MESH_OT_noise(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_uv_sphere_add(), MESH_OT_remove_doubles(), MESH_OT_select_similar(), MESH_OT_solidify(), MESH_OT_spin(), MESH_OT_subdivide(), MESH_OT_vert_slide(), NODE_OT_backimage_zoom(), OBJECT_OT_vertex_group_clean(), OBJECT_OT_vertex_group_fix(), OBJECT_OT_vertex_group_levels(), PARTICLE_OT_remove_doubles(), PARTICLE_OT_weight_set(), POSE_OT_propagate(), RNA_api_bone(), RNA_api_object(), RNA_api_pose_channel(), RNA_api_scene(), RNA_api_ui_layout(), rna_def_color_ramp(), rna_def_color_ramp_element_api(), rna_def_fcurve(), rna_def_fcurve_keyframe_points(), rna_def_render_engine(), rna_def_vertex_group(), SCREEN_OT_area_split(), SEQUENCER_OT_view_zoom_ratio(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), Transform_Properties(), UV_OT_cube_project(), UV_OT_stitch(), uv_transform_properties(), VIEW2D_OT_zoom(), VIEW2D_OT_zoom_in(), and VIEW2D_OT_zoom_out().
PropertyRNA* RNA_def_float_array (StructOrFunctionRNA * cont, const char * identifier, int len, const float * default_value, float hardmin, float hardmax, const char * ui_name, const char * ui_description, float softmin, float softmax)
Definition at line 2492 of file rna_define.c.
References PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_array_default(), RNA_def_property_range(), RNA_def_property_ui_range(), and RNA_def_property_ui_text().
Referenced by RNA_api_environment_map(), RNA_def_test(), and TEXTURE_OT_envmap_save().
PropertyRNA* RNA_def_float_color (StructOrFunctionRNA * cont, const char * identifier, int len, const float * default_value, float hardmin, float hardmax, const char * ui_name, const char * ui_description, float softmin, float softmax)
Definition at line 2430 of file rna_define.c.
References PROP_COLOR, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_array_default(), RNA_def_property_range(), RNA_def_property_ui_range(), and RNA_def_property_ui_text().
Referenced by IMAGE_OT_new(), and rna_def_color_ramp().
PropertyRNA* RNA_def_float_factor (StructOrFunctionRNA * cont, const char * identifier, float default_value, float hardmin, float hardmax, const char * ui_name, const char * ui_description, float softmin, float softmax)
Definition at line 2525 of file rna_define.c.
References PROP_FACTOR, PROP_FLOAT, RNA_def_property(), RNA_def_property_float_default(), RNA_def_property_range(), RNA_def_property_ui_range(), and RNA_def_property_ui_text().
Referenced by CURVE_OT_spline_weight_set(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_tosphere(), UV_OT_minimize_stretch(), and UV_OT_pack_islands().
PropertyRNA* RNA_def_float_matrix (StructOrFunctionRNA * cont, const char * identifier, int rows, int columns, const float * default_value, float hardmin, float hardmax, const char * ui_name, const char * ui_description, float softmin, float softmax)
Definition at line 2448 of file rna_define.c.
References length(), PROP_FLOAT, PROP_MATRIX, RNA_def_property(), RNA_def_property_float_array_default(), RNA_def_property_multi_array(), RNA_def_property_range(), RNA_def_property_ui_range(), and RNA_def_property_ui_text().
Referenced by RNA_api_mesh().
PropertyRNA* RNA_def_float_percentage (StructOrFunctionRNA * cont, const char * identifier, float default_value, float hardmin, float hardmax, const char * ui_name, const char * ui_description, float softmin, float softmax)
Definition at line 2509 of file rna_define.c.
References PROP_FLOAT, PROP_PERCENTAGE, RNA_def_property(), RNA_def_property_float_default(), RNA_def_property_range(), RNA_def_property_ui_range(), and RNA_def_property_ui_text().
Referenced by CURVE_OT_select_random(), MBALL_OT_select_random_metaelems(), MESH_OT_select_random(), OBJECT_OT_select_random(), and pose_slide_opdef_properties().
PropertyRNA* RNA_def_float_rotation (StructOrFunctionRNA * cont, const char * identifier, int len, const float * default_value, float hardmin, float hardmax, const char * ui_name, const char * ui_description, float softmin, float softmax)
Definition at line 2469 of file rna_define.c.
References BLI_assert, NULL, PROP_ANGLE, PROP_EULER, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_array_default(), RNA_def_property_range(), RNA_def_property_ui_range(), and RNA_def_property_ui_text().
Referenced by ED_object_add_generic_props(), MESH_OT_dissolve_limited(), MESH_OT_tris_convert_to_quads(), TRANSFORM_OT_rotate(), TRANSFORM_OT_tilt(), and TRANSFORM_OT_warp().
PropertyRNA* RNA_def_float_vector (StructOrFunctionRNA * cont, const char * identifier, int len, const float * default_value, float hardmin, float hardmax, const char * ui_name, const char * ui_description, float softmin, float softmax)
Definition at line 2400 of file rna_define.c.
References PROP_FLOAT, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_array_default(), RNA_def_property_range(), RNA_def_property_ui_range(), and RNA_def_property_ui_text().
Referenced by CLIP_OT_add_marker(), CLIP_OT_graph_select(), CLIP_OT_select(), CLIP_OT_slide_marker(), CLIP_OT_view_pan(), CLIP_OT_view_zoom_in(), CLIP_OT_view_zoom_out(), CURVE_OT_spin(), IMAGE_OT_view_pan(), IMAGE_OT_view_zoom_in(), IMAGE_OT_view_zoom_out(), MESH_OT_screw(), MESH_OT_spin(), PAINT_OT_clone_cursor_set(), PAINT_OT_grab_clone(), RNA_api_armature_edit_bone(), RNA_api_camera(), RNA_api_object(), RNA_api_texture(), rna_def_action(), rna_def_fcurve(), RNA_def_float_vector_xyz(), rna_def_image(), rna_def_trackingMarkers(), SEQUENCER_OT_effect_strip_add(), TRANSFORM_OT_resize(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), Transform_Properties(), UV_OT_cursor_set(), UV_OT_select(), UV_OT_select_linked_pick(), and UV_OT_select_loop().
PropertyRNA* RNA_def_float_vector_xyz (StructOrFunctionRNA * cont, const char * identifier, int len, const float * default_value, float hardmin, float hardmax, const char * ui_name, const char * ui_description, float softmin, float softmax)
Definition at line 2417 of file rna_define.c.
References PROP_XYZ_LENGTH, RNA_def_float_vector(), and PropertyRNA::subtype.
Referenced by CURVE_OT_spin(), CURVE_OT_vertex_add(), ED_object_add_generic_props(), RNA_api_bone(), RNA_api_pose_channel(), and TRANSFORM_OT_translate().
void RNA_def_func_duplicate_pointers (FunctionRNA * func)
void RNA_def_func_free_pointers (FunctionRNA * func)
Referenced by RNA_struct_free().
FunctionRNA* RNA_def_function (StructRNA * srna, const char * identifier, const char * call)
Definition at line 2628 of file rna_define.c.
References FunctionDefRNA::call, BlenderDefRNA::preprocess, rna_def_function(), and rna_find_function_def().
Referenced by RNA_api_actuator(), rna_api_animdata_drivers(), rna_api_animdata_nla_tracks(), RNA_api_armature_edit_bone(), RNA_api_bone(), RNA_api_camera(), RNA_api_controller(), RNA_api_environment_map(), RNA_api_image(), RNA_api_keyconfigs(), RNA_api_keyingset(), RNA_api_keymap(), RNA_api_keymapitem(), RNA_api_keymapitems(), RNA_api_keymaps(), RNA_api_macro(), RNA_api_main(), RNA_api_mesh(), rna_api_nlatrack_strips(), RNA_api_object(), RNA_api_object_base(), RNA_api_operator(), RNA_api_pose_channel(), RNA_api_scene(), RNA_api_scene_render(), RNA_api_sensor(), RNA_api_sequence_strip(), RNA_api_text(), RNA_api_texture(), RNA_api_ui_layout(), RNA_api_wm(), rna_def_action_fcurves(), rna_def_action_groups(), rna_def_action_pose_markers(), rna_def_area(), rna_def_armature_edit_bones(), rna_def_backgroundImages(), rna_def_canvas_surface(), rna_def_channeldriver_variables(), rna_def_color_ramp(), rna_def_color_ramp_element_api(), rna_def_composite_nodetree_api(), rna_def_curve_spline_bezpoints(), rna_def_curve_spline_points(), rna_def_curve_splines(), rna_def_fcurve(), rna_def_fcurve_keyframe_points(), rna_def_fcurve_modifiers(), rna_def_gpencil_layers(), rna_def_group_objects(), rna_def_group_sockets_api(), rna_def_header(), rna_def_ID(), rna_def_ID_materials(), rna_def_keyingset_info(), rna_def_keyingset_paths(), rna_def_loop_colors(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_gpencil(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_libraries(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_movieclips(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_screens(), RNA_def_main_sounds(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_window_managers(), RNA_def_main_worlds(), rna_def_menu(), rna_def_mesh_edges(), rna_def_mesh_loops(), rna_def_mesh_polygons(), rna_def_mesh_tessfaces(), rna_def_mesh_vertices(), rna_def_metaball_elements(), rna_def_nodetree_link_api(), rna_def_object_constraints(), rna_def_object_modifiers(), rna_def_object_vertex_groups(), rna_def_panel(), rna_def_polygon_float_layers(), rna_def_polygon_int_layers(), rna_def_polygon_string_layers(), rna_def_pose_channel_constraints(), rna_def_region(), rna_def_render_engine(), rna_def_render_layer(), rna_def_render_layers(), rna_def_render_result(), RNA_def_scene(), rna_def_scene_keying_sets(), rna_def_scene_objects(), rna_def_shader_nodetree_api(), rna_def_space_view3d(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), rna_def_texture_nodetree_api(), rna_def_texture_slots(), rna_def_timeline_markers(), rna_def_trackingMarkers(), rna_def_trackingObjects(), rna_def_trackingObjectTracks(), rna_def_trackingTracks(), rna_def_userdef_addon_collection(), rna_def_uv_textures(), and rna_def_vertex_group().
void RNA_def_function_flag (FunctionRNA * func, int flag)
Definition at line 2687 of file rna_define.c.
References FunctionRNA::flag.
Referenced by rna_api_animdata_drivers(), rna_api_animdata_nla_tracks(), RNA_api_environment_map(), RNA_api_image(), RNA_api_keyingset(), RNA_api_keymap(), RNA_api_keymapitems(), RNA_api_macro(), RNA_api_mesh(), rna_api_nlatrack_strips(), RNA_api_object(), RNA_api_operator(), RNA_api_sequence_strip(), RNA_api_ui_layout(), RNA_api_wm(), rna_def_action_fcurves(), rna_def_action_groups(), rna_def_action_pose_markers(), rna_def_armature_edit_bones(), rna_def_backgroundImages(), rna_def_channeldriver_variables(), rna_def_color_ramp_element_api(), rna_def_composite_nodetree_api(), rna_def_curve_spline_bezpoints(), rna_def_curve_spline_points(), rna_def_curve_splines(), rna_def_fcurve_keyframe_points(), rna_def_fcurve_modifiers(), rna_def_gpencil_layers(), rna_def_group_objects(), rna_def_group_sockets_api(), rna_def_header(), rna_def_ID(), rna_def_keyingset_info(), rna_def_keyingset_paths(), rna_def_loop_colors(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_movieclips(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_worlds(), rna_def_menu(), rna_def_mesh_edges(), rna_def_mesh_loops(), rna_def_mesh_polygons(), rna_def_mesh_tessfaces(), rna_def_mesh_vertices(), rna_def_metaball_elements(), rna_def_nodetree_link_api(), rna_def_object_constraints(), rna_def_object_modifiers(), rna_def_panel(), rna_def_polygon_float_layers(), rna_def_polygon_int_layers(), rna_def_polygon_string_layers(), rna_def_pose_channel_constraints(), rna_def_render_engine(), rna_def_render_layer(), rna_def_render_layers(), rna_def_render_result(), rna_def_scene_keying_sets(), rna_def_scene_objects(), rna_def_shader_nodetree_api(), rna_def_space_view3d(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), rna_def_texture_nodetree_api(), rna_def_texture_slots(), rna_def_timeline_markers(), rna_def_trackingObjectTracks(), rna_def_trackingTracks(), rna_def_userdef_addon_collection(), rna_def_uv_textures(), rna_def_vertex_group(), and rna_generic_op_invoke().
void RNA_def_function_output (FunctionRNA * func, PropertyRNA * ret)
void RNA_def_function_return (FunctionRNA * func, PropertyRNA * ret)
Definition at line 2664 of file rna_define.c.
References PropertyRNA::arraydimension, FunctionRNA::c_ret, PropertyRNA::flag, FunctionRNA::identifier, PropertyRNA::identifier, PROP_DYNAMIC, and RNA_def_function_output().
Referenced by rna_api_animdata_drivers(), rna_api_animdata_nla_tracks(), RNA_api_bone(), RNA_api_image(), RNA_api_keyconfigs(), RNA_api_keymap(), RNA_api_keymapitem(), RNA_api_keymapitems(), RNA_api_keymaps(), RNA_api_macro(), RNA_api_main(), RNA_api_mesh(), rna_api_nlatrack_strips(), RNA_api_object(), RNA_api_operator(), RNA_api_pose_channel(), RNA_api_sequence_strip(), RNA_api_ui_layout(), RNA_api_wm(), rna_def_action_fcurves(), rna_def_action_groups(), rna_def_action_pose_markers(), rna_def_armature_edit_bones(), rna_def_backgroundImages(), rna_def_canvas_surface(), rna_def_channeldriver_variables(), rna_def_color_ramp_element_api(), rna_def_composite_nodetree_api(), rna_def_curve_splines(), rna_def_fcurve(), rna_def_fcurve_keyframe_points(), rna_def_fcurve_modifiers(), rna_def_gpencil_layers(), rna_def_group_sockets_api(), rna_def_ID(), rna_def_ID_materials(), rna_def_keyingset_info(), rna_def_keyingset_paths(), rna_def_loop_colors(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_movieclips(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_worlds(), rna_def_menu(), rna_def_metaball_elements(), rna_def_nodetree_link_api(), rna_def_object_constraints(), rna_def_object_modifiers(), rna_def_object_vertex_groups(), rna_def_panel(), rna_def_polygon_float_layers(), rna_def_polygon_int_layers(), rna_def_polygon_string_layers(), rna_def_pose_channel_constraints(), rna_def_render_engine(), rna_def_render_layers(), RNA_def_scene(), rna_def_scene_keying_sets(), rna_def_scene_objects(), rna_def_shader_nodetree_api(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), rna_def_texture_nodetree_api(), rna_def_texture_slots(), rna_def_timeline_markers(), rna_def_trackingMarkers(), rna_def_trackingObjects(), rna_def_userdef_addon_collection(), rna_def_uv_textures(), rna_def_vertex_group(), and rna_generic_op_invoke().
FunctionRNA* RNA_def_function_runtime (StructRNA * srna, const char * identifier, CallFunc call)
Definition at line 2646 of file rna_define.c.
References FunctionRNA::call, BlenderDefRNA::preprocess, and rna_def_function().
void RNA_def_function_ui_description (FunctionRNA * func, const char * description)
Definition at line 2692 of file rna_define.c.
References FunctionRNA::description.
Referenced by RNA_api_actuator(), rna_api_animdata_drivers(), rna_api_animdata_nla_tracks(), RNA_api_armature_edit_bone(), RNA_api_bone(), RNA_api_camera(), RNA_api_controller(), RNA_api_environment_map(), RNA_api_image(), RNA_api_keyingset(), RNA_api_macro(), RNA_api_main(), RNA_api_mesh(), rna_api_nlatrack_strips(), RNA_api_object(), RNA_api_object_base(), RNA_api_operator(), RNA_api_pose_channel(), RNA_api_scene(), RNA_api_scene_render(), RNA_api_sensor(), RNA_api_sequence_strip(), RNA_api_text(), RNA_api_texture(), RNA_api_ui_layout(), RNA_api_wm(), rna_def_action_fcurves(), rna_def_action_groups(), rna_def_action_pose_markers(), rna_def_area(), rna_def_armature_edit_bones(), rna_def_backgroundImages(), rna_def_canvas_surface(), rna_def_channeldriver_variables(), rna_def_color_ramp(), rna_def_color_ramp_element_api(), rna_def_composite_nodetree_api(), rna_def_curve_spline_bezpoints(), rna_def_curve_spline_points(), rna_def_curve_splines(), rna_def_fcurve(), rna_def_fcurve_keyframe_points(), rna_def_fcurve_modifiers(), rna_def_gpencil_layers(), rna_def_group_objects(), rna_def_group_sockets_api(), rna_def_header(), rna_def_ID(), rna_def_ID_materials(), rna_def_keyingset_info(), rna_def_keyingset_paths(), rna_def_loop_colors(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_movieclips(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_worlds(), rna_def_menu(), rna_def_metaball_elements(), rna_def_nodetree_link_api(), rna_def_object_constraints(), rna_def_object_modifiers(), rna_def_object_vertex_groups(), rna_def_panel(), rna_def_polygon_float_layers(), rna_def_polygon_int_layers(), rna_def_polygon_string_layers(), rna_def_pose_channel_constraints(), rna_def_render_engine(), rna_def_render_layer(), rna_def_render_layers(), rna_def_render_result(), rna_def_scene_keying_sets(), rna_def_scene_objects(), rna_def_shader_nodetree_api(), rna_def_space_view3d(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), rna_def_texture_nodetree_api(), rna_def_timeline_markers(), rna_def_trackingMarkers(), rna_def_trackingObjects(), rna_def_trackingObjectTracks(), rna_def_trackingTracks(), rna_def_userdef_addon_collection(), rna_def_uv_textures(), and rna_def_vertex_group().
PropertyRNA* RNA_def_int (StructOrFunctionRNA * cont, const char * identifier, int default_value, int hardmin, int hardmax, const char * ui_name, const char * ui_description, int softmin, int softmax)
Definition at line 2213 of file rna_define.c.
References PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_int_default(), RNA_def_property_range(), RNA_def_property_ui_range(), and RNA_def_property_ui_text().
Referenced by ANIM_OT_change_frame(), ANIM_OT_previewrange_set(), ARMATURE_OT_subdivide(), CLIP_OT_change_frame(), CLIP_OT_clean_tracks(), CLIP_OT_detect_features(), CLIP_OT_select_circle(), CONSOLE_OT_history_append(), CURVE_OT_select_nth(), CURVE_OT_subdivide(), ED_OT_undo_history(), FILE_OT_delete_bookmark(), FILE_OT_filenum(), FONT_OT_change_character(), FONT_OT_change_spacing(), FONT_OT_textbox_remove(), GRAPH_OT_cursor_set(), IMAGE_OT_new(), INFO_OT_select_pick(), LOGIC_OT_links_cut(), MARKER_OT_duplicate(), MARKER_OT_move(), MESH_OT_duplicate(), MESH_OT_extrude_repeat(), MESH_OT_knife_cut(), MESH_OT_loopcut(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_uv_sphere_add(), MESH_OT_screw(), MESH_OT_select_by_number_vertices(), MESH_OT_select_nth(), MESH_OT_spin(), MESH_OT_subdivide(), MESH_OT_vertices_randomize(), MESH_OT_vertices_smooth(), NODE_OT_group_socket_move_down(), NODE_OT_group_socket_move_up(), NODE_OT_group_socket_remove(), NODE_OT_links_cut(), NODE_OT_select(), OBJECT_OT_game_property_remove(), OBJECT_OT_select_by_layer(), PAINT_OT_hide_show(), PARTICLE_OT_rekey(), POSE_OT_group_assign(), pose_slide_opdef_properties(), POSELIB_OT_apply_pose(), POSELIB_OT_browse_interactive(), POSELIB_OT_pose_add(), RNA_api_image(), rna_api_nlatrack_strips(), RNA_api_object(), RNA_api_scene(), RNA_api_scene_render(), RNA_api_sequence_strip(), RNA_api_ui_layout(), rna_def_action_fcurves(), rna_def_canvas_surface(), rna_def_curve_spline_bezpoints(), rna_def_curve_spline_points(), rna_def_fcurve_keyframe_points(), rna_def_ID_materials(), rna_def_keyingset_paths(), RNA_def_main_images(), rna_def_mesh_edges(), rna_def_mesh_loops(), rna_def_mesh_polygons(), rna_def_mesh_tessfaces(), rna_def_mesh_vertices(), rna_def_render_engine(), rna_def_render_layer(), rna_def_texture_slots(), rna_def_trackingMarkers(), rna_def_trackingObjectTracks(), rna_def_trackingTracks(), rna_def_vertex_group(), rna_generic_op_invoke(), SCREEN_OT_actionzone(), SCREEN_OT_area_join(), SCREEN_OT_area_move(), SCREEN_OT_area_split(), SCREEN_OT_frame_offset(), SCREEN_OT_repeat_history(), SCREEN_OT_screen_set(), sequencer_generic_props__internal(), SEQUENCER_OT_cut(), SEQUENCER_OT_images_separate(), SEQUENCER_OT_snap(), SOUND_OT_mixdown(), TEXT_OT_cursor_set(), TEXT_OT_jump(), TEXT_OT_scroll(), TEXT_OT_scroll_bar(), UV_OT_circle_select(), UV_OT_minimize_stretch(), UV_OT_stitch(), UV_OT_unwrap(), VIEW2D_OT_pan(), VIEW2D_OT_scroll_down(), VIEW2D_OT_scroll_left(), VIEW2D_OT_scroll_right(), VIEW2D_OT_scroll_up(), VIEW2D_OT_zoom_border(), VIEW3D_OT_background_image_remove(), VIEW3D_OT_clip_border(), VIEW3D_OT_dolly(), VIEW3D_OT_layers(), VIEW3D_OT_render_border(), VIEW3D_OT_select_circle(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), WM_operator_properties_filesel(), WM_operator_properties_gesture_border(), WM_operator_properties_gesture_straightline(), WM_OT_debug_menu(), and WM_OT_redraw_timer().
PropertyRNA* RNA_def_int_array (StructOrFunctionRNA * cont, const char * identifier, int len, const int * default_value, int hardmin, int hardmax, const char * ui_name, const char * ui_description, int softmin, int softmax)
Definition at line 2245 of file rna_define.c.
References PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_int_array_default(), RNA_def_property_range(), RNA_def_property_ui_range(), and RNA_def_property_ui_text().
Referenced by rna_def_image_paint(), RNA_def_test(), and rna_def_vertex_group().
PropertyRNA* RNA_def_int_vector (StructOrFunctionRNA * cont, const char * identifier, int len, const int * default_value, int hardmin, int hardmax, const char * ui_name, const char * ui_description, int softmin, int softmax)
Definition at line 2228 of file rna_define.c.
References PROP_INT, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_int_array_default(), RNA_def_property_range(), RNA_def_property_ui_range(), and RNA_def_property_ui_text().
Referenced by PAINT_OT_sample_color(), PARTICLE_OT_select_linked(), rna_def_image(), rna_def_movieclip(), and UV_OT_tile_set().
PropertyRNA* RNA_def_pointer (StructOrFunctionRNA * cont, const char * identifier, const char * type, const char * ui_name, const char * ui_description)
Definition at line 2541 of file rna_define.c.
References PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_struct_type(), and RNA_def_property_ui_text().
Referenced by api_ui_item_rna_common(), RNA_api_actuator(), rna_api_animdata_drivers(), rna_api_animdata_nla_tracks(), RNA_api_camera(), RNA_api_controller(), RNA_api_environment_map(), RNA_api_image(), RNA_api_keyconfigs(), RNA_api_keymap(), RNA_api_keymapitem(), RNA_api_keymapitems(), RNA_api_keymaps(), RNA_api_macro(), RNA_api_main(), RNA_api_mesh(), rna_api_nlatrack_strips(), RNA_api_object(), RNA_api_object_base(), RNA_api_operator(), RNA_api_sensor(), RNA_api_sequence_strip(), RNA_api_ui_layout(), RNA_api_wm(), rna_def_action_fcurves(), rna_def_action_groups(), rna_def_action_pose_markers(), rna_def_armature_edit_bones(), rna_def_backgroundImages(), rna_def_canvas_surface(), rna_def_channeldriver_variables(), rna_def_color_ramp_element_api(), rna_def_composite_nodetree_api(), rna_def_curve_spline_bezpoints(), rna_def_curve_splines(), rna_def_fcurve_keyframe_points(), rna_def_fcurve_modifiers(), rna_def_gpencil_layers(), rna_def_group_objects(), rna_def_group_sockets_api(), rna_def_header(), rna_def_ID(), rna_def_ID_materials(), rna_def_keyingset_info(), rna_def_keyingset_paths(), rna_def_loop_colors(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_movieclips(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_worlds(), rna_def_menu(), rna_def_metaball_elements(), rna_def_nodetree_link_api(), rna_def_object_constraints(), rna_def_object_modifiers(), rna_def_object_vertex_groups(), rna_def_panel(), rna_def_polygon_float_layers(), rna_def_polygon_int_layers(), rna_def_polygon_string_layers(), rna_def_pose_channel_constraints(), rna_def_render_engine(), rna_def_render_layers(), rna_def_scene_keying_sets(), rna_def_scene_objects(), rna_def_shader_nodetree_api(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), rna_def_texture_nodetree_api(), rna_def_texture_slots(), rna_def_timeline_markers(), rna_def_trackingMarkers(), rna_def_trackingObjects(), rna_def_userdef_addon_collection(), rna_def_uv_textures(), and rna_generic_op_invoke().
PropertyRNA* RNA_def_pointer_runtime (StructOrFunctionRNA * cont, const char * identifier, StructRNA * type, const char * ui_name, const char * ui_description)
Definition at line 2554 of file rna_define.c.
References PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_struct_runtime(), and RNA_def_property_ui_text().
Referenced by BPy_PointerProperty(), and WM_operatortype_macro_define().
PropertyRNA* RNA_def_property (StructOrFunctionRNA * cont, const char * identifier, int type, int subtype)
Definition at line 881 of file rna_define.c.
References BLI_ghash_insert(), PropertyDefRNA::cont, CONTAINER_RNA_ID, StringPropertyRNA::defaultvalue, PropertyRNA::description, ELEM, BlenderDefRNA::error, error(), PropertyRNA::flag, FLT_MAX, FloatPropertyRNA::hardmax, IntPropertyRNA::hardmax, FloatPropertyRNA::hardmin, IntPropertyRNA::hardmin, PropertyRNA::identifier, PropertyRNA::magic, MEM_callocN(), PropertyRNA::name, NULL, FloatPropertyRNA::precision, BlenderDefRNA::preprocess, PropertyDefRNA::prop, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_COLOR, PROP_COLOR_GAMMA, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_IDPROPERTY, PROP_INT, PROP_LAYER_MEMBER, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_RUNTIME, PROP_STRING, PROP_UNSIGNED, ContainerRNA::properties, ContainerDefRNA::properties, ContainerRNA::prophash, PropertyRNA::rawtype, rna_addtail(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_sdna(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), rna_find_container_def(), rna_findlink(), RNA_MAGIC, rna_property_type_sizeof(), rna_validate_identifier(), BlenderDefRNA::silent, FloatPropertyRNA::softmax, IntPropertyRNA::softmax, FloatPropertyRNA::softmin, IntPropertyRNA::softmin, FloatPropertyRNA::step, IntPropertyRNA::step, PropertyRNA::subtype, and PropertyRNA::type.
Referenced by api_ui_item_common(), BPy_BoolProperty(), BPy_BoolVectorProperty(), BPy_FloatProperty(), BPy_FloatVectorProperty(), BPy_IntProperty(), BPy_IntVectorProperty(), BPy_StringProperty(), def_cmp_alpha_over(), def_cmp_bilateral_blur(), def_cmp_blur(), def_cmp_channel_matte(), def_cmp_chroma_matte(), def_cmp_color_matte(), def_cmp_color_spill(), def_cmp_colorbalance(), def_cmp_crop(), def_cmp_dblur(), def_cmp_defocus(), def_cmp_diff_matte(), def_cmp_dilate_erode(), def_cmp_distance_matte(), def_cmp_double_edge_mask(), def_cmp_filter(), def_cmp_flip(), def_cmp_glare(), def_cmp_hue_saturation(), def_cmp_huecorrect(), def_cmp_id_mask(), def_cmp_image(), def_cmp_invert(), def_cmp_lensdist(), def_cmp_levels(), def_cmp_luma_matte(), def_cmp_map_uv(), def_cmp_map_value(), def_cmp_movieclip(), def_cmp_moviedistortion(), def_cmp_output_file(), def_cmp_premul_key(), def_cmp_render_layers(), def_cmp_rotate(), def_cmp_scale(), def_cmp_splitviewer(), def_cmp_stabilize2d(), def_cmp_tonemap(), def_cmp_vector_blur(), def_cmp_ycc(), def_cmp_zcombine(), def_colorramp(), def_forloop(), def_glossy(), def_group(), def_math(), def_mix_rgb(), def_rgb_curve(), def_sh_attribute(), def_sh_geometry(), def_sh_mapping(), def_sh_material(), def_sh_tex(), def_sh_tex_environment(), def_sh_tex_gradient(), def_sh_tex_image(), def_sh_tex_magic(), def_sh_tex_musgrave(), def_sh_tex_sky(), def_sh_tex_voronoi(), def_sh_tex_wave(), def_tex_bricks(), def_tex_image(), def_tex_output(), def_texture(), def_time(), def_vector_curve(), def_vector_math(), def_whileloop(), dev_cmd_transform(), LOGIC_OT_links_cut(), MESH_OT_knife_cut(), NODE_OT_links_cut(), OBJECT_OT_vertex_group_blend(), rna_api_animdata_nla_tracks(), RNA_api_keymapitems(), RNA_api_wm(), rna_def_action(), rna_def_action_actuator(), rna_def_action_group(), rna_def_action_pose_markers(), rna_def_actuator(), rna_def_actuator_sensor(), rna_def_animdata(), rna_def_animdata_common(), rna_def_animviz(), rna_def_animviz_common(), rna_def_animviz_ghosts(), rna_def_animviz_motion_path(), rna_def_animviz_motionpath_vert(), rna_def_animviz_paths(), rna_def_area(), rna_def_area_lamp(), rna_def_area_spaces(), rna_def_armature(), rna_def_armature_actuator(), rna_def_armature_bones(), rna_def_armature_edit_bones(), rna_def_armature_sensor(), rna_def_background_image(), rna_def_beztriple(), rna_def_boid_settings(), rna_def_boidrule(), rna_def_boidrule_average_speed(), rna_def_boidrule_avoid(), rna_def_boidrule_avoid_collision(), rna_def_boidrule_fight(), rna_def_boidrule_follow_leader(), rna_def_boidrule_goal(), rna_def_boidstate(), rna_def_bone(), rna_def_bone_common(), rna_def_bone_group(), rna_def_bone_groups(), RNA_def_boolean(), RNA_def_boolean_array(), RNA_def_boolean_layer(), RNA_def_boolean_layer_member(), RNA_def_boolean_vector(), rna_def_bpoint(), rna_def_brush(), rna_def_brush_texture_slot(), RNA_def_camera(), rna_def_camera_actuator(), rna_def_canvas_surface(), rna_def_canvas_surfaces(), rna_def_channeldriver(), rna_def_charinfo(), rna_def_cloth_collision_settings(), rna_def_cloth_sim_settings(), rna_def_cmp_output_file_socket(), RNA_def_collection(), RNA_def_collection_runtime(), rna_def_collision(), rna_def_collision_sensor(), rna_def_color_ramp(), rna_def_color_ramp_element(), rna_def_colormapping(), rna_def_common_keying_flags(), rna_def_composite_nodetree(), rna_def_compositor_node(), rna_def_console_line(), RNA_def_constraint(), rna_def_constraint_action(), rna_def_constraint_actuator(), rna_def_constraint_camera_solver(), rna_def_constraint_childof(), rna_def_constraint_clamp_to(), rna_def_constraint_damped_track(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_follow_track(), rna_def_constraint_kinematic(), rna_def_constraint_locate_like(), rna_def_constraint_location_limit(), rna_def_constraint_locked_track(), rna_def_constraint_minmax(), rna_def_constraint_object_solver(), rna_def_constraint_pivot(), rna_def_constraint_python(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_rotate_like(), rna_def_constraint_rotation_limit(), rna_def_constraint_same_volume(), rna_def_constraint_shrinkwrap(), rna_def_constraint_size_like(), rna_def_constraint_size_limit(), rna_def_constraint_spline_ik(), rna_def_constraint_stretch_to(), rna_def_constraint_track_to(), rna_def_constraint_transform(), rna_def_constraint_transform_like(), rna_def_constrainttarget(), RNA_def_context(), RNA_def_controller(), rna_def_curve(), rna_def_curve_nurb(), rna_def_curve_splines(), rna_def_curvemap(), rna_def_curvemapping(), rna_def_curvemappoint(), rna_def_delay_sensor(), rna_def_dopesheet(), rna_def_drivertarget(), rna_def_drivervar(), rna_def_dupli_object(), rna_def_dynamic_paint_brush_settings(), rna_def_dynamic_paint_canvas_settings(), rna_def_edit_bone(), rna_def_edit_object_actuator(), rna_def_editor(), rna_def_effector_weight(), RNA_def_enum(), RNA_def_enum_flag(), rna_def_enum_property(), rna_def_environment_map(), rna_def_event(), rna_def_fcurve(), rna_def_fcurve_modifiers(), rna_def_field(), rna_def_fileselect_params(), rna_def_filter_common(), rna_def_filter_video(), rna_def_fkeyframe(), RNA_def_float(), RNA_def_float_array(), RNA_def_float_color(), RNA_def_float_factor(), RNA_def_float_matrix(), RNA_def_float_percentage(), RNA_def_float_rotation(), RNA_def_float_vector(), rna_def_fluid_mesh_vertices(), rna_def_fluid_settings(), RNA_def_fluidsim(), rna_def_fluidsim_active(), rna_def_fluidsim_control(), rna_def_fluidsim_domain(), rna_def_fluidsim_fluid(), rna_def_fluidsim_inflow(), rna_def_fluidsim_obstacle(), rna_def_fluidsim_particle(), rna_def_fluidsim_slip(), rna_def_fluidsim_volume(), rna_def_fmodifier(), rna_def_fmodifier_cycles(), rna_def_fmodifier_envelope(), rna_def_fmodifier_envelope_ctrl(), rna_def_fmodifier_function_generator(), rna_def_fmodifier_generator(), rna_def_fmodifier_limits(), rna_def_fmodifier_noise(), rna_def_fmodifier_stepped(), rna_def_font(), rna_def_fpoint(), rna_def_function(), rna_def_game_actuator(), rna_def_game_softbody(), RNA_def_gameproperty(), rna_def_glow(), rna_def_gpencil_data(), rna_def_gpencil_frame(), rna_def_gpencil_layer(), rna_def_gpencil_layers(), rna_def_gpencil_stroke(), rna_def_gpencil_stroke_point(), RNA_def_group(), rna_def_header(), rna_def_histogram(), rna_def_ID(), rna_def_ID_properties(), rna_def_image(), rna_def_image_paint(), rna_def_imageuser(), rna_def_input(), RNA_def_int(), RNA_def_int_array(), RNA_def_int_vector(), rna_def_joystick_sensor(), rna_def_key(), rna_def_keyblock(), rna_def_keyboard_sensor(), rna_def_keyconfig(), rna_def_keydata(), rna_def_keyingset(), rna_def_keyingset_info(), rna_def_keyingset_path(), rna_def_keyingset_paths(), rna_def_lamp(), rna_def_lamp_falloff(), rna_def_lamp_mtex(), rna_def_lamp_shadow(), rna_def_lamp_sky_settings(), rna_def_lattice(), rna_def_latticepoint(), rna_def_library(), rna_def_lighting(), rna_def_loop_colors(), rna_def_macro_operator(), RNA_def_main(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_gpencil(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_libraries(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_screens(), RNA_def_main_sounds(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_window_managers(), RNA_def_main_worlds(), RNA_def_material(), rna_def_material_colors(), rna_def_material_diffuse(), rna_def_material_gamesettings(), rna_def_material_halo(), rna_def_material_mtex(), rna_def_material_physics(), rna_def_material_raymirror(), rna_def_material_raytra(), rna_def_material_slot(), rna_def_material_specularity(), rna_def_material_sss(), rna_def_material_strand(), rna_def_material_volume(), rna_def_mcol(), rna_def_medge(), rna_def_menu(), rna_def_mesh(), rna_def_mesh_polygons(), rna_def_mesh_tessfaces(), rna_def_message_actuator(), rna_def_message_sensor(), rna_def_meta(), rna_def_metaball(), rna_def_metaball_elements(), rna_def_metaelement(), rna_def_mface(), rna_def_mloop(), rna_def_mloopcol(), rna_def_mloopuv(), RNA_def_modifier(), rna_def_modifier_armature(), rna_def_modifier_array(), rna_def_modifier_bevel(), rna_def_modifier_boolean(), rna_def_modifier_build(), rna_def_modifier_cast(), rna_def_modifier_cloth(), rna_def_modifier_collision(), rna_def_modifier_curve(), rna_def_modifier_decimate(), rna_def_modifier_displace(), rna_def_modifier_dynamic_paint(), rna_def_modifier_edgesplit(), rna_def_modifier_explode(), rna_def_modifier_fluidsim(), rna_def_modifier_generic_map_info(), rna_def_modifier_hook(), rna_def_modifier_lattice(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_mirror(), rna_def_modifier_multires(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_particlesystem(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smoke(), rna_def_modifier_smooth(), rna_def_modifier_softbody(), rna_def_modifier_solidify(), rna_def_modifier_subsurf(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvg_mask(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), rna_def_modifier_weightvgproximity(), rna_def_motionpath_common(), rna_def_mouse_sensor(), rna_def_movie(), rna_def_movieclip(), rna_def_movieclip_proxy(), rna_def_moviecliUser(), rna_def_mpolygon(), rna_def_mproperties(), rna_def_msticky(), rna_def_mtex(), rna_def_mtex_common(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_multicam(), rna_def_mvert(), rna_def_mvert_group(), rna_def_near_sensor(), rna_def_nlastrip(), rna_def_nlatrack(), rna_def_node(), rna_def_node_link(), rna_def_node_socket(), rna_def_node_socket_subtype(), rna_def_nodetree(), rna_def_number_property(), rna_def_nurbs(), rna_def_object(), rna_def_object_actuator(), rna_def_object_base(), rna_def_object_constraints(), rna_def_object_game_settings(), rna_def_object_modifiers(), rna_def_object_particle_systems(), rna_def_object_vertex_groups(), rna_def_operator(), rna_def_operator_filelist_element(), rna_def_operator_stroke_element(), rna_def_operator_type_macro(), rna_def_operator_utils(), RNA_def_packedfile(), rna_def_paint(), rna_def_panel(), rna_def_parent_actuator(), rna_def_particle(), rna_def_particle_dupliweight(), rna_def_particle_edit(), rna_def_particle_hair_key(), rna_def_particle_key(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_particle_system(), rna_def_particle_target(), rna_def_path(), rna_def_plugin(), rna_def_pointcache(), RNA_def_pointer(), rna_def_pointer_property(), RNA_def_pointer_runtime(), rna_def_pose(), rna_def_pose_channel(), rna_def_pose_channel_constraints(), rna_def_pose_ikparam(), rna_def_pose_itasc(), rna_def_property(), rna_def_property_actuator(), rna_def_property_sensor(), rna_def_property_subdivision_common(), rna_def_proxy(), rna_def_ptcache_point_caches(), rna_def_radar_sensor(), rna_def_random_actuator(), rna_def_random_sensor(), rna_def_ray_sensor(), rna_def_reconstructedCamera(), rna_def_region(), rna_def_render_engine(), rna_def_render_layer(), rna_def_render_layer_common(), rna_def_render_layers(), rna_def_render_pass(), rna_def_render_result(), RNA_def_rna(), rna_def_scene(), RNA_def_scene(), rna_def_scene_actuator(), rna_def_scene_bases(), rna_def_scene_ffmpeg_settings(), rna_def_scene_game_data(), rna_def_scene_game_recast_data(), rna_def_scene_image_format_data(), rna_def_scene_keying_sets(), rna_def_scene_keying_sets_all(), rna_def_scene_objects(), rna_def_scene_render_data(), rna_def_scopes(), rna_def_screen(), rna_def_sculpt(), rna_def_selected_uv_element(), rna_def_sensor(), rna_def_sequence(), rna_def_shader_node(), rna_def_shader_nodetree(), rna_def_shape_action_actuator(), rna_def_smoke_domain_settings(), rna_def_smoke_flow_settings(), rna_def_softbody(), rna_def_solid_color(), rna_def_sound(), rna_def_sound_actuator(), rna_def_space(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_console(), rna_def_space_dopesheet(), rna_def_space_filebrowser(), rna_def_space_graph(), rna_def_space_image(), rna_def_space_image_uv(), rna_def_space_info(), rna_def_space_logic(), rna_def_space_nla(), rna_def_space_node(), rna_def_space_outliner(), rna_def_space_sequencer(), rna_def_space_text(), rna_def_space_time(), rna_def_space_userpref(), rna_def_space_view3d(), rna_def_speaker(), rna_def_speed_control(), rna_def_spot_lamp(), rna_def_state_actuator(), rna_def_steering_actuator(), RNA_def_string(), RNA_def_string_dir_path(), RNA_def_string_file_name(), RNA_def_string_file_path(), rna_def_string_property(), RNA_def_string_translate(), rna_def_strip_color_balance(), rna_def_strip_crop(), rna_def_strip_element(), rna_def_strip_proxy(), rna_def_strip_transform(), rna_def_struct(), RNA_def_struct(), rna_def_sun_lamp(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), RNA_def_test(), rna_def_texmapping(), rna_def_texmat_common(), rna_def_text(), rna_def_text_line(), rna_def_text_marker(), rna_def_textbox(), rna_def_texture(), rna_def_texture_blend(), rna_def_texture_clouds(), rna_def_texture_distorted_noise(), rna_def_texture_environment_map(), rna_def_texture_image(), rna_def_texture_magic(), rna_def_texture_marble(), rna_def_texture_musgrave(), rna_def_texture_node(), rna_def_texture_nodetree(), rna_def_texture_ocean(), rna_def_texture_pointdensity(), rna_def_texture_stucci(), rna_def_texture_voronoi(), rna_def_texture_voxeldata(), rna_def_texture_wood(), rna_def_timeline_marker(), rna_def_timer(), rna_def_tool_settings(), rna_def_touch_sensor(), rna_def_tracking(), rna_def_trackingCamera(), rna_def_trackingMarker(), rna_def_trackingObject(), rna_def_trackingObjects(), rna_def_trackingObjectTracks(), rna_def_trackingReconstruction(), rna_def_trackingSettings(), rna_def_trackingStabilization(), rna_def_trackingTrack(), rna_def_trackingTracks(), rna_def_transform(), rna_def_transform_orientation(), rna_def_twodfilter_actuator(), rna_def_ui_layout(), rna_def_unified_paint_settings(), rna_def_unit_settings(), RNA_def_userdef(), rna_def_userdef_addon(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_solidlight(), rna_def_userdef_system(), rna_def_userdef_theme_colorset(), rna_def_userdef_theme_space_action(), rna_def_userdef_theme_space_buts(), rna_def_userdef_theme_space_clip(), rna_def_userdef_theme_space_console(), rna_def_userdef_theme_space_file(), rna_def_userdef_theme_space_generic(), rna_def_userdef_theme_space_graph(), rna_def_userdef_theme_space_image(), rna_def_userdef_theme_space_list_generic(), rna_def_userdef_theme_space_logic(), rna_def_userdef_theme_space_nla(), rna_def_userdef_theme_space_node(), rna_def_userdef_theme_space_outliner(), rna_def_userdef_theme_space_seq(), rna_def_userdef_theme_space_text(), rna_def_userdef_theme_space_time(), rna_def_userdef_theme_space_view3d(), rna_def_userdef_theme_spaces_curves(), rna_def_userdef_theme_spaces_edge(), rna_def_userdef_theme_spaces_face(), rna_def_userdef_theme_spaces_list_main(), rna_def_userdef_theme_spaces_main(), rna_def_userdef_theme_spaces_vertex(), rna_def_userdef_theme_ui(), rna_def_userdef_theme_ui_font_style(), rna_def_userdef_theme_ui_panel(), rna_def_userdef_theme_ui_style(), rna_def_userdef_theme_ui_wcol(), rna_def_userdef_theme_ui_wcol_state(), rna_def_userdef_themes(), rna_def_userdef_view(), rna_def_uv_layers(), rna_def_uv_textures(), rna_def_vertex_group(), rna_def_vertex_paint(), RNA_def_vfont(), rna_def_visibility_actuator(), rna_def_window(), rna_def_windowmanager(), rna_def_wipe(), rna_def_wm_keyconfigs(), RNA_def_world(), rna_def_world_mist(), rna_def_world_mtex(), rna_def_world_stars(), SCREEN_OT_screencast(), TRANSFORM_OT_select_orientation(), and Transform_Properties().
void RNA_def_property_array (PropertyRNA * prop, int length)
Definition at line 1068 of file rna_define.c.
References PropertyRNA::arraydimension, PropertyRNA::arraylength, BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, length(), PROP_BOOLEAN, PROP_FLOAT, PROP_INT, RNA_MAX_ARRAY_LENGTH, PropertyRNA::totarraylength, and PropertyRNA::type.
Referenced by BPy_BoolVectorProperty(), BPy_FloatVectorProperty(), BPy_IntVectorProperty(), def_cmp_colorbalance(), def_cmp_map_value(), rna_def_animviz_motionpath_vert(), rna_def_armature(), rna_def_beztriple(), rna_def_bone(), rna_def_bone_common(), RNA_def_boolean_array(), RNA_def_boolean_layer(), RNA_def_boolean_layer_member(), RNA_def_boolean_vector(), rna_def_bpoint(), rna_def_brush(), rna_def_canvas_surface(), rna_def_cloth_sim_settings(), rna_def_color_ramp_element(), rna_def_colormapping(), rna_def_constraint_actuator(), rna_def_constraint_spline_ik(), rna_def_curve(), rna_def_curvemappoint(), rna_def_dynamic_paint_brush_settings(), rna_def_edit_bone(), rna_def_edit_object_actuator(), rna_def_environment_map(), rna_def_fcurve(), rna_def_fkeyframe(), RNA_def_float_array(), RNA_def_float_color(), RNA_def_float_rotation(), RNA_def_float_vector(), rna_def_fluid_mesh_vertices(), rna_def_fluidsim_domain(), rna_def_fluidsim_fluid(), rna_def_fluidsim_inflow(), rna_def_fmodifier_generator(), rna_def_fpoint(), rna_def_gpencil_layer(), rna_def_gpencil_stroke_point(), RNA_def_group(), rna_def_ID_properties(), rna_def_image(), RNA_def_int_array(), RNA_def_int_vector(), rna_def_keydata(), rna_def_lamp(), rna_def_lamp_shadow(), rna_def_latticepoint(), RNA_def_material(), rna_def_material_colors(), rna_def_material_volume(), rna_def_mcol(), rna_def_medge(), rna_def_metaball(), rna_def_metaelement(), rna_def_mface(), rna_def_mloopcol(), rna_def_modifier_simpledeform(), rna_def_movieclip(), rna_def_mpolygon(), rna_def_mtex(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_mvert(), rna_def_node(), rna_def_number_property(), rna_def_object(), rna_def_object_actuator(), rna_def_object_base(), rna_def_object_game_settings(), rna_def_operator_stroke_element(), rna_def_operator_utils(), rna_def_particle_hair_key(), rna_def_particle_settings(), rna_def_pose_channel(), rna_def_render_layer_common(), RNA_def_scene(), rna_def_scene_game_data(), rna_def_scene_render_data(), rna_def_space_image(), rna_def_space_image_uv(), rna_def_space_view3d(), rna_def_state_actuator(), rna_def_texture_image(), rna_def_tool_settings(), rna_def_trackingCamera(), rna_def_trackingMarker(), rna_def_trackingTrack(), rna_def_userdef_edit(), rna_def_userdef_solidlight(), rna_def_userdef_theme_colorset(), rna_def_userdef_theme_space_action(), rna_def_userdef_theme_space_buts(), rna_def_userdef_theme_space_clip(), rna_def_userdef_theme_space_console(), rna_def_userdef_theme_space_file(), rna_def_userdef_theme_space_generic(), rna_def_userdef_theme_space_graph(), rna_def_userdef_theme_space_image(), rna_def_userdef_theme_space_list_generic(), rna_def_userdef_theme_space_logic(), rna_def_userdef_theme_space_nla(), rna_def_userdef_theme_space_node(), rna_def_userdef_theme_space_outliner(), rna_def_userdef_theme_space_seq(), rna_def_userdef_theme_space_text(), rna_def_userdef_theme_space_time(), rna_def_userdef_theme_space_view3d(), rna_def_userdef_theme_spaces_curves(), rna_def_userdef_theme_spaces_edge(), rna_def_userdef_theme_spaces_face(), rna_def_userdef_theme_spaces_vertex(), rna_def_userdef_theme_ui_wcol(), rna_def_userdef_theme_ui_wcol_state(), RNA_def_world(), and Transform_Properties().
void RNA_def_property_boolean_array_default (PropertyRNA * prop, const int * array)
Definition at line 1350 of file rna_define.c.
References BoolPropertyRNA::defaultarray, BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, PROP_BOOLEAN, and PropertyRNA::type.
Referenced by BPy_BoolVectorProperty(), RNA_def_boolean_array(), RNA_def_boolean_layer(), RNA_def_boolean_layer_member(), and RNA_def_boolean_vector().
void RNA_def_property_boolean_default (PropertyRNA * prop, int value)
Definition at line 1333 of file rna_define.c.
References BoolPropertyRNA::defaultvalue, BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, PROP_BOOLEAN, and PropertyRNA::type.
Referenced by BPy_BoolProperty(), and RNA_def_boolean().
void RNA_def_property_boolean_funcs (PropertyRNA * prop, const char * get, const char * set)
Definition at line 1931 of file rna_define.c.
References PropertyRNA::arraydimension, BlenderDefRNA::error, BoolPropertyRNA::get, BoolPropertyRNA::getarray, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, BlenderDefRNA::preprocess, PROP_BOOLEAN, BoolPropertyRNA::set, BoolPropertyRNA::setarray, and PropertyRNA::type.
Referenced by rna_def_action_actuator(), rna_def_armature(), rna_def_bone_common(), rna_def_canvas_surface(), rna_def_constraint_actuator(), rna_def_curvemapping(), rna_def_editor(), rna_def_filter_common(), rna_def_filter_video(), rna_def_fmodifier(), rna_def_function(), rna_def_gpencil_layer(), rna_def_ID(), rna_def_image(), rna_def_keyconfig(), rna_def_lattice(), RNA_def_main(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_gpencil(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_libraries(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_screens(), RNA_def_main_sounds(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_window_managers(), RNA_def_main_worlds(), rna_def_material_colors(), rna_def_material_mtex(), rna_def_mcol(), rna_def_mloopcol(), rna_def_modifier_meshdeform(), rna_def_modifier_multires(), rna_def_modifier_ocean(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_nlastrip(), rna_def_number_property(), rna_def_object(), rna_def_object_base(), rna_def_object_game_settings(), rna_def_operator(), rna_def_particle_edit(), rna_def_particle_settings(), rna_def_particle_system(), rna_def_pose_channel(), rna_def_property(), rna_def_proxy(), rna_def_render_layer_common(), RNA_def_scene(), rna_def_scene_ffmpeg_settings(), rna_def_scene_game_data(), rna_def_scene_render_data(), rna_def_screen(), rna_def_sensor(), rna_def_softbody(), rna_def_sound(), rna_def_space_graph(), rna_def_space_image(), rna_def_space_text(), rna_def_space_view3d(), rna_def_state_actuator(), RNA_def_test(), rna_def_text(), rna_def_texture(), rna_def_tool_settings(), rna_def_trackingTrack(), and rna_def_ui_layout().
void RNA_def_property_boolean_negative_sdna (PropertyRNA * prop, const char * structname, const char * propname, int bit)
Definition at line 1597 of file rna_define.c.
References PropertyDefRNA::booleannegative, BlenderDefRNA::laststruct, RNA_def_property_boolean_sdna(), and rna_find_struct_property_def().
Referenced by def_cmp_defocus(), rna_def_action_actuator(), rna_def_animdata(), rna_def_area(), rna_def_armature(), rna_def_background_image(), rna_def_bone_common(), rna_def_brush(), rna_def_channeldriver(), RNA_def_constraint(), rna_def_constraint_kinematic(), rna_def_constraint_pivot(), rna_def_constraint_spline_ik(), rna_def_curve(), rna_def_dopesheet(), rna_def_edit_object_actuator(), rna_def_fcurve(), rna_def_fileselect_params(), rna_def_fluidsim_domain(), rna_def_fmodifier(), rna_def_gpencil_layer(), rna_def_image_paint(), rna_def_keyconfig(), rna_def_lamp(), RNA_def_material(), rna_def_material_gamesettings(), rna_def_modifier_mirror(), rna_def_modifier_multires(), rna_def_node_socket(), rna_def_object(), rna_def_object_game_settings(), rna_def_parent_actuator(), rna_def_particle(), rna_def_particle_settings(), rna_def_path(), rna_def_pointcache(), rna_def_render_engine(), rna_def_render_layer_common(), rna_def_scene_game_data(), rna_def_scene_render_data(), rna_def_shape_action_actuator(), rna_def_space_clip(), rna_def_space_dopesheet(), rna_def_space_graph(), rna_def_space_image_uv(), rna_def_space_nla(), rna_def_space_outliner(), rna_def_space_sequencer(), rna_def_space_time(), rna_def_space_view3d(), rna_def_tool_settings(), rna_def_trackingSettings(), rna_def_trackingTrack(), rna_def_twodfilter_actuator(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_system(), rna_def_userdef_view(), and rna_def_visibility_actuator().
void RNA_def_property_boolean_sdna (PropertyRNA * prop, const char * structname, const char * propname, int bit)
Definition at line 1565 of file rna_define.c.
References PropertyDefRNA::booleanbit, PropertyDefRNA::dnatype, BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, IS_DNATYPE_INT_COMPAT, BlenderDefRNA::laststruct, BlenderDefRNA::preprocess, PROP_BOOLEAN, rna_def_property_sdna(), RNA_property_typename(), BlenderDefRNA::silent, and PropertyRNA::type.
Referenced by def_cmp_alpha_over(), def_cmp_blur(), def_cmp_color_spill(), def_cmp_crop(), def_cmp_dblur(), def_cmp_defocus(), def_cmp_glare(), def_cmp_id_mask(), def_cmp_image(), def_cmp_invert(), def_cmp_lensdist(), def_cmp_map_value(), def_cmp_vector_blur(), def_cmp_zcombine(), def_mix_rgb(), def_sh_mapping(), def_sh_material(), rna_def_action_actuator(), rna_def_action_group(), rna_def_actuator(), rna_def_animviz_ghosts(), rna_def_animviz_motion_path(), rna_def_animviz_motionpath_vert(), rna_def_animviz_paths(), rna_def_area_lamp(), rna_def_armature(), rna_def_background_image(), rna_def_beztriple(), rna_def_boid_settings(), rna_def_boidrule(), rna_def_boidrule_avoid(), rna_def_boidrule_avoid_collision(), rna_def_boidrule_follow_leader(), rna_def_boidrule_goal(), rna_def_bone(), rna_def_bone_common(), rna_def_bpoint(), rna_def_brush(), RNA_def_camera(), rna_def_canvas_surface(), rna_def_channeldriver(), rna_def_charinfo(), rna_def_cloth_collision_settings(), rna_def_cloth_sim_settings(), rna_def_cmp_output_file_socket(), rna_def_collision(), rna_def_collision_sensor(), rna_def_colormapping(), RNA_def_constraint(), rna_def_constraint_actuator(), rna_def_constraint_camera_solver(), rna_def_constraint_childof(), rna_def_constraint_clamp_to(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_follow_track(), rna_def_constraint_kinematic(), rna_def_constraint_locate_like(), rna_def_constraint_location_limit(), rna_def_constraint_minmax(), rna_def_constraint_object_solver(), rna_def_constraint_python(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_rotate_like(), rna_def_constraint_rotation_limit(), rna_def_constraint_shrinkwrap(), rna_def_constraint_size_like(), rna_def_constraint_size_limit(), rna_def_constraint_spline_ik(), rna_def_constraint_track_to(), rna_def_constraint_transform(), RNA_def_controller(), rna_def_curve(), rna_def_curve_nurb(), rna_def_curvemapping(), rna_def_curvemappoint(), rna_def_delay_sensor(), rna_def_dopesheet(), rna_def_dupli_object(), rna_def_dynamic_paint_brush_settings(), rna_def_edit_bone(), rna_def_edit_object_actuator(), rna_def_editor(), rna_def_effector_weight(), rna_def_environment_map(), rna_def_event(), rna_def_fcurve(), rna_def_field(), rna_def_fileselect_params(), rna_def_filter_common(), rna_def_filter_video(), rna_def_fkeyframe(), rna_def_fluid_settings(), rna_def_fluidsim_active(), rna_def_fluidsim_control(), rna_def_fluidsim_domain(), rna_def_fluidsim_inflow(), rna_def_fluidsim_particle(), rna_def_fluidsim_volume(), rna_def_fmodifier(), rna_def_fmodifier_function_generator(), rna_def_fmodifier_generator(), rna_def_fmodifier_limits(), rna_def_fmodifier_stepped(), rna_def_font(), rna_def_fpoint(), rna_def_game_softbody(), RNA_def_gameproperty(), rna_def_glow(), rna_def_gpencil_data(), rna_def_gpencil_frame(), rna_def_gpencil_layer(), RNA_def_group(), rna_def_ID(), rna_def_image(), rna_def_image_paint(), rna_def_imageuser(), rna_def_joystick_sensor(), rna_def_key(), rna_def_keyblock(), rna_def_keyboard_sensor(), rna_def_keyconfig(), rna_def_keyingset(), rna_def_keyingset_path(), rna_def_lamp(), rna_def_lamp_falloff(), rna_def_lamp_mtex(), rna_def_lamp_shadow(), rna_def_lamp_sky_settings(), rna_def_lattice(), rna_def_lighting(), RNA_def_material(), rna_def_material_colors(), rna_def_material_gamesettings(), rna_def_material_halo(), rna_def_material_mtex(), rna_def_material_physics(), rna_def_material_raymirror(), rna_def_material_sss(), rna_def_material_strand(), rna_def_material_volume(), rna_def_mcol(), rna_def_medge(), rna_def_mesh(), rna_def_metaball(), rna_def_metaelement(), rna_def_mface(), rna_def_mloopcol(), rna_def_mloopuv(), RNA_def_modifier(), rna_def_modifier_armature(), rna_def_modifier_array(), rna_def_modifier_bevel(), rna_def_modifier_build(), rna_def_modifier_cast(), rna_def_modifier_edgesplit(), rna_def_modifier_explode(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_mirror(), rna_def_modifier_multires(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smooth(), rna_def_modifier_solidify(), rna_def_modifier_subsurf(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvgedit(), rna_def_movieclip(), rna_def_movieclip_proxy(), rna_def_moviecliUser(), rna_def_mpolygon(), rna_def_mtex(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_mvert(), rna_def_nlastrip(), rna_def_nlatrack(), rna_def_node(), rna_def_node_socket_subtype(), rna_def_nurbs(), rna_def_object(), rna_def_object_actuator(), rna_def_object_base(), rna_def_object_game_settings(), rna_def_paint(), rna_def_particle_edit(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_particle_system(), rna_def_particle_target(), rna_def_path(), rna_def_pointcache(), rna_def_pose_channel(), rna_def_pose_itasc(), RNA_def_property(), RNA_def_property_boolean_negative_sdna(), rna_def_proxy(), rna_def_random_actuator(), rna_def_ray_sensor(), rna_def_render_engine(), rna_def_render_layer_common(), RNA_def_scene(), rna_def_scene_ffmpeg_settings(), rna_def_scene_game_data(), rna_def_scene_image_format_data(), rna_def_scene_render_data(), rna_def_scopes(), rna_def_screen(), rna_def_sculpt(), rna_def_sensor(), rna_def_sequence(), rna_def_smoke_domain_settings(), rna_def_smoke_flow_settings(), rna_def_softbody(), rna_def_sound(), rna_def_sound_actuator(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_dopesheet(), rna_def_space_graph(), rna_def_space_image(), rna_def_space_image_uv(), rna_def_space_info(), rna_def_space_logic(), rna_def_space_nla(), rna_def_space_node(), rna_def_space_outliner(), rna_def_space_sequencer(), rna_def_space_text(), rna_def_space_time(), rna_def_space_view3d(), rna_def_speaker(), rna_def_speed_control(), rna_def_spot_lamp(), rna_def_state_actuator(), rna_def_steering_actuator(), rna_def_strip_color_balance(), rna_def_strip_proxy(), rna_def_texmapping(), rna_def_texmat_common(), rna_def_text(), rna_def_text_marker(), rna_def_texture(), rna_def_texture_image(), rna_def_texture_pointdensity(), rna_def_texture_voxeldata(), rna_def_timeline_marker(), rna_def_tool_settings(), rna_def_trackingMarker(), rna_def_trackingObject(), rna_def_trackingReconstruction(), rna_def_trackingSettings(), rna_def_trackingStabilization(), rna_def_trackingTrack(), rna_def_transform(), rna_def_unified_paint_settings(), rna_def_unit_settings(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_solidlight(), rna_def_userdef_system(), rna_def_userdef_theme_colorset(), rna_def_userdef_theme_ui_wcol(), rna_def_userdef_view(), rna_def_vertex_group(), rna_def_vertex_paint(), rna_def_visibility_actuator(), RNA_def_world(), rna_def_world_mist(), rna_def_world_mtex(), and rna_def_world_stars().
void RNA_def_property_clear_flag (PropertyRNA * prop, int flag)
Definition at line 1058 of file rna_define.c.
References PropertyRNA::flag.
Referenced by BPy_BoolProperty(), BPy_BoolVectorProperty(), BPy_CollectionProperty(), BPy_EnumProperty(), BPy_FloatProperty(), BPy_FloatVectorProperty(), BPy_IntProperty(), BPy_IntVectorProperty(), BPy_PointerProperty(), BPy_StringProperty(), def_cmp_output_file(), rna_def_action(), rna_def_actuator(), rna_def_animdata_common(), rna_def_animviz_motion_path(), rna_def_area(), rna_def_boidrule(), rna_def_bone(), rna_def_bone_common(), rna_def_brush(), RNA_def_camera(), rna_def_canvas_surface(), rna_def_canvas_surfaces(), rna_def_cloth_sim_settings(), rna_def_color_ramp(), rna_def_compositor_node(), RNA_def_constraint(), rna_def_constraint_childof(), rna_def_constraint_python(), RNA_def_context(), RNA_def_controller(), rna_def_curve_nurb(), rna_def_curvemap(), rna_def_curvemappoint(), rna_def_dupli_object(), rna_def_dynamic_paint_brush_settings(), rna_def_edit_bone(), rna_def_enum_property(), rna_def_environment_map(), rna_def_event(), rna_def_fcurve(), rna_def_fileselect_params(), rna_def_fluid_mesh_vertices(), RNA_def_fluidsim(), rna_def_fluidsim_control(), rna_def_fluidsim_domain(), rna_def_fluidsim_inflow(), rna_def_fluidsim_obstacle(), rna_def_fluidsim_slip(), rna_def_fluidsim_volume(), rna_def_fmodifier(), rna_def_function(), rna_def_ID(), rna_def_ID_properties(), rna_def_image(), rna_def_imageuser(), rna_def_input(), rna_def_key(), rna_def_keyblock(), rna_def_keyconfig(), rna_def_keyingset(), rna_def_lamp(), rna_def_latticepoint(), rna_def_macro_operator(), RNA_def_main(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_gpencil(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_libraries(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_screens(), RNA_def_main_sounds(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_window_managers(), RNA_def_main_worlds(), RNA_def_material(), rna_def_material_slot(), rna_def_material_strand(), rna_def_medge(), rna_def_menu(), rna_def_mesh(), rna_def_mface(), rna_def_mloop(), RNA_def_modifier(), rna_def_modifier_decimate(), rna_def_modifier_dynamic_paint(), rna_def_modifier_meshdeform(), rna_def_modifier_multires(), rna_def_modifier_ocean(), rna_def_movieclip(), rna_def_movieclip_proxy(), rna_def_moviecliUser(), rna_def_mpolygon(), rna_def_mtex(), rna_def_mvert(), rna_def_mvert_group(), rna_def_nlastrip(), rna_def_nlatrack(), rna_def_node(), rna_def_node_socket(), rna_def_nodetree(), rna_def_number_property(), rna_def_object(), rna_def_object_game_settings(), rna_def_object_particle_systems(), rna_def_object_vertex_groups(), rna_def_operator(), RNA_def_packedfile(), rna_def_particle(), rna_def_particle_dupliweight(), rna_def_particle_edit(), rna_def_particle_settings(), rna_def_particle_system(), rna_def_particle_target(), rna_def_plugin(), rna_def_pointcache(), rna_def_pointer_property(), rna_def_pose(), rna_def_pose_channel(), rna_def_pose_ikparam(), rna_def_property(), rna_def_reconstructedCamera(), rna_def_region(), rna_def_render_layer_common(), rna_def_render_pass(), rna_def_render_result(), RNA_def_rna(), RNA_def_scene(), rna_def_scene_ffmpeg_settings(), rna_def_scene_render_data(), rna_def_screen(), rna_def_sensor(), rna_def_sequence(), rna_def_shader_node(), rna_def_smoke_domain_settings(), rna_def_softbody(), rna_def_space(), rna_def_space_image(), rna_def_space_node(), rna_def_space_view3d(), rna_def_speaker(), rna_def_speed_control(), rna_def_string_property(), rna_def_strip_element(), rna_def_struct(), rna_def_text(), rna_def_text_marker(), rna_def_texture_node(), rna_def_texture_ocean(), rna_def_timer(), rna_def_tracking(), rna_def_trackingCamera(), rna_def_trackingObject(), rna_def_trackingReconstruction(), rna_def_trackingSettings(), rna_def_trackingStabilization(), rna_def_trackingTrack(), rna_def_transform(), rna_def_vertex_group(), RNA_def_vfont(), RNA_def_world(), and WM_operator_properties_sanitize().
void RNA_def_property_collection_funcs (PropertyRNA * prop, const char * begin, const char * next, const char * end, const char * get, const char * length, const char * lookupint, const char * lookupstring, const char * assignint)
Definition at line 2100 of file rna_define.c.
References CollectionPropertyRNA::assignint, CollectionPropertyRNA::begin, CollectionPropertyRNA::end, BlenderDefRNA::error, CollectionPropertyRNA::get, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, CollectionPropertyRNA::length, CollectionPropertyRNA::lookupint, CollectionPropertyRNA::lookupstring, CollectionPropertyRNA::next, BlenderDefRNA::preprocess, PROP_COLLECTION, and PropertyRNA::type.
Referenced by rna_def_action_group(), rna_def_armature(), RNA_def_controller(), rna_def_curve(), rna_def_curve_nurb(), rna_def_curvemapping(), rna_def_dynamic_paint_canvas_settings(), rna_def_editor(), rna_def_enum_property(), rna_def_fluidsim_domain(), rna_def_function(), RNA_def_group(), rna_def_ID_properties(), rna_def_image(), rna_def_keyblock(), rna_def_lattice(), rna_def_latticepoint(), RNA_def_main(), rna_def_mcol(), rna_def_mesh(), rna_def_metaball(), rna_def_mloopcol(), rna_def_mloopuv(), rna_def_modifier_uvproject(), rna_def_movie(), rna_def_mproperties(), rna_def_mtex_common(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_mvert(), rna_def_object(), rna_def_pointcache(), rna_def_pose(), rna_def_render_layer(), rna_def_render_result(), RNA_def_rna(), RNA_def_scene(), rna_def_sensor(), RNA_def_struct(), rna_def_struct(), rna_def_texmat_common(), rna_def_tracking(), rna_def_trackingObject(), and rna_def_trackingStabilization().
void RNA_def_property_collection_sdna (PropertyRNA * prop, const char * structname, const char * propname, const char * lengthpropname)
Definition at line 1799 of file rna_define.c.
References PropertyRNA::arraydimension, PropertyDefRNA::cont, PropertyDefRNA::dnalengthfixed, PropertyDefRNA::dnalengthname, PropertyDefRNA::dnalengthstructname, StructDefRNA::dnaname, PropertyDefRNA::dnapointerlevel, PropertyDefRNA::dnatype, CollectionPropertyRNA::end, BlenderDefRNA::error, CollectionPropertyRNA::get, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, CollectionPropertyRNA::next, BlenderDefRNA::preprocess, PROP_COLLECTION, rna_def_property_sdna(), rna_find_sdna_member(), rna_find_struct_def(), BlenderDefRNA::sdna, BlenderDefRNA::silent, PropertyRNA::totarraylength, and PropertyRNA::type.
Referenced by rna_def_action(), rna_def_action_group(), rna_def_animdata(), rna_def_animviz_motion_path(), rna_def_area(), rna_def_armature(), rna_def_bone(), rna_def_channeldriver(), rna_def_color_ramp(), rna_def_composite_nodetree(), rna_def_constraint_python(), RNA_def_controller(), rna_def_curve(), rna_def_curve_nurb(), rna_def_curvemap(), rna_def_drivervar(), rna_def_editor(), rna_def_fcurve(), rna_def_fmodifier_envelope(), rna_def_font(), rna_def_gpencil_data(), rna_def_gpencil_frame(), rna_def_gpencil_layer(), rna_def_gpencil_stroke(), RNA_def_group(), rna_def_image(), rna_def_key(), rna_def_keyblock(), rna_def_keyconfig(), rna_def_keyingset(), rna_def_mesh(), rna_def_meta(), rna_def_metaball(), rna_def_movie(), rna_def_node(), rna_def_nodetree(), rna_def_object(), rna_def_object_game_settings(), rna_def_particle(), rna_def_particle_settings(), rna_def_particle_system(), rna_def_pose(), RNA_def_property(), RNA_def_scene(), rna_def_scene_render_data(), rna_def_screen(), rna_def_sensor(), rna_def_shader_nodetree(), rna_def_space_console(), rna_def_space_view3d(), rna_def_texmat_common(), rna_def_texture_nodetree(), rna_def_trackingReconstruction(), rna_def_trackingTrack(), RNA_def_userdef(), rna_def_userdef_system(), and rna_def_userdef_themes().
void RNA_def_property_duplicate_pointers (StructOrFunctionRNA * cont_, PropertyRNA * prop)
Referenced by BPy_BoolProperty(), BPy_BoolVectorProperty(), BPy_CollectionProperty(), BPy_EnumProperty(), BPy_FloatProperty(), BPy_FloatVectorProperty(), BPy_IntProperty(), BPy_IntVectorProperty(), BPy_PointerProperty(), and BPy_StringProperty().
void RNA_def_property_dynamic_array_funcs (PropertyRNA * prop, const char * getlength)
Definition at line 1915 of file rna_define.c.
References BlenderDefRNA::error, PropertyRNA::flag, PropertyRNA::getlength, BlenderDefRNA::preprocess, and PROP_DYNAMIC.
Referenced by rna_def_constraint_spline_ik(), rna_def_fmodifier_generator(), rna_def_image(), rna_def_mface(), rna_def_mpolygon(), rna_def_mtface(), rna_def_number_property(), rna_def_render_layer(), rna_def_render_pass(), and RNA_def_test().
void RNA_def_property_editable_array_func (PropertyRNA * prop, const char * editable)
Definition at line 1889 of file rna_define.c.
References PropertyRNA::itemeditable, and BlenderDefRNA::preprocess.
Referenced by rna_def_object(), and rna_def_pose_channel().
void RNA_def_property_editable_func (PropertyRNA * prop, const char * editable)
Definition at line 1879 of file rna_define.c.
References PropertyRNA::editable, and BlenderDefRNA::preprocess.
Referenced by rna_def_animdata(), rna_def_curve(), rna_def_drivertarget(), rna_def_gpencil_layer(), rna_def_ID(), rna_def_keyingset_path(), rna_def_keyingset_paths(), rna_def_lattice(), rna_def_metaball(), rna_def_mtex_common(), rna_def_nlastrip(), rna_def_pose_channel(), rna_def_sequence(), and rna_def_texmat_common().
void RNA_def_property_enum_bitflag_sdna (PropertyRNA * prop, const char * structname, const char * propname)
Definition at line 1731 of file rna_define.c.
References PropertyDefRNA::enumbitflags, BlenderDefRNA::laststruct, RNA_def_property_enum_sdna(), and rna_find_struct_property_def().
Referenced by rna_def_animviz_paths(), rna_def_armature(), rna_def_brush(), RNA_def_camera(), rna_def_constraint_kinematic(), rna_def_curve(), rna_def_curvemap(), rna_def_curvemappoint(), rna_def_drivertarget(), RNA_def_fluidsim(), rna_def_fluidsim_slip(), rna_def_fluidsim_volume(), rna_def_gpencil_data(), rna_def_image(), rna_def_lamp_shadow(), RNA_def_material(), rna_def_material_mtex(), rna_def_object(), rna_def_particle_edit(), rna_def_pose_itasc(), rna_def_ray_sensor(), RNA_def_scene(), rna_def_scene_ffmpeg_settings(), rna_def_scene_image_format_data(), rna_def_scene_render_data(), rna_def_space_image(), rna_def_space_node(), rna_def_texture_blend(), rna_def_tool_settings(), rna_def_userdef_edit(), and rna_def_userdef_input().
void RNA_def_property_enum_default (PropertyRNA * prop, int value)
Definition at line 1452 of file rna_define.c.
References EnumPropertyRNA::defaultvalue, BlenderDefRNA::error, PropertyRNA::flag, i, StructRNA::identifier, PropertyRNA::identifier, EnumPropertyItem::identifier, EnumPropertyRNA::item, BlenderDefRNA::laststruct, PROP_ENUM, PROP_ENUM_FLAG, EnumPropertyRNA::totitem, PropertyRNA::type, and EnumPropertyItem::value.
Referenced by rna_def_drivertarget(), RNA_def_enum(), RNA_def_enum_flag(), rna_def_keyingset_path(), rna_def_modifier_weightvgproximity(), rna_def_node_socket(), rna_def_userdef_filepaths(), and rna_def_userdef_system().
void RNA_def_property_enum_funcs (PropertyRNA * prop, const char * get, const char * set, const char * item)
Definition at line 2023 of file rna_define.c.
References BlenderDefRNA::error, EnumPropertyRNA::get, StructRNA::identifier, PropertyRNA::identifier, EnumPropertyRNA::itemf, BlenderDefRNA::laststruct, BlenderDefRNA::preprocess, PROP_ENUM, EnumPropertyRNA::set, and PropertyRNA::type.
Referenced by def_cmp_channel_matte(), def_cmp_image(), def_cmp_render_layers(), rna_def_actuator(), rna_def_area(), rna_def_bone_group(), rna_def_brush(), rna_def_canvas_surface(), RNA_def_constraint(), rna_def_constraint_actuator(), rna_def_constraint_kinematic(), RNA_def_context(), RNA_def_controller(), rna_def_curve(), rna_def_curve_nurb(), rna_def_drivertarget(), rna_def_drivervar(), rna_def_enum_property(), rna_def_field(), RNA_def_gameproperty(), rna_def_image(), rna_def_keyboard_sensor(), rna_def_keyconfig(), rna_def_keyingset_path(), RNA_def_material(), rna_def_material_mtex(), rna_def_material_slot(), rna_def_modifier_shrinkwrap(), rna_def_mtex(), rna_def_object(), rna_def_object_actuator(), rna_def_object_game_settings(), rna_def_particle_edit(), rna_def_particle_settings(), rna_def_pose(), rna_def_pose_channel(), rna_def_property(), RNA_def_scene(), rna_def_scene_game_data(), rna_def_scene_image_format_data(), rna_def_scene_render_data(), rna_def_sensor(), rna_def_softbody(), rna_def_space_buttons(), rna_def_space_image(), rna_def_space_view3d(), rna_def_texture(), rna_def_ui_layout(), rna_def_userdef_edit(), rna_def_userdef_input(), rna_def_userdef_system(), and rna_def_userdef_view().
void RNA_def_property_enum_items (PropertyRNA * prop, const EnumPropertyItem * item)
Definition at line 1280 of file rna_define.c.
References EnumPropertyRNA::defaultvalue, BlenderDefRNA::error, i, StructRNA::identifier, PropertyRNA::identifier, EnumPropertyItem::identifier, EnumPropertyRNA::item, BlenderDefRNA::laststruct, PROP_ENUM, EnumPropertyRNA::totitem, PropertyRNA::type, and EnumPropertyItem::value.
Referenced by api_ui_item_common(), def_cmp_blur(), def_cmp_channel_matte(), def_cmp_color_spill(), def_cmp_colorbalance(), def_cmp_defocus(), def_cmp_double_edge_mask(), def_cmp_filter(), def_cmp_flip(), def_cmp_glare(), def_cmp_image(), def_cmp_levels(), def_cmp_moviedistortion(), def_cmp_premul_key(), def_cmp_render_layers(), def_cmp_rotate(), def_cmp_scale(), def_cmp_splitviewer(), def_cmp_stabilize2d(), def_cmp_tonemap(), def_cmp_ycc(), def_glossy(), def_math(), def_mix_rgb(), def_sh_tex_environment(), def_sh_tex_gradient(), def_sh_tex_image(), def_sh_tex_musgrave(), def_sh_tex_voronoi(), def_sh_tex_wave(), def_vector_math(), dev_cmd_transform(), rna_def_action(), rna_def_action_actuator(), rna_def_actuator(), rna_def_animdata(), rna_def_animviz_ghosts(), rna_def_animviz_paths(), rna_def_area(), rna_def_area_lamp(), rna_def_armature(), rna_def_armature_actuator(), rna_def_armature_sensor(), rna_def_background_image(), rna_def_beztriple(), rna_def_boidrule(), rna_def_boidstate(), rna_def_bone_group(), rna_def_brush(), rna_def_brush_texture_slot(), RNA_def_camera(), rna_def_camera_actuator(), rna_def_canvas_surface(), rna_def_channeldriver(), rna_def_color_ramp(), rna_def_colormapping(), rna_def_common_keying_flags(), rna_def_compositor_node(), RNA_def_constraint(), rna_def_constraint_action(), rna_def_constraint_actuator(), rna_def_constraint_clamp_to(), rna_def_constraint_damped_track(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_kinematic(), rna_def_constraint_locked_track(), rna_def_constraint_minmax(), rna_def_constraint_pivot(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_same_volume(), rna_def_constraint_shrinkwrap(), rna_def_constraint_spline_ik(), rna_def_constraint_stretch_to(), rna_def_constraint_track_to(), rna_def_constraint_transform(), RNA_def_context(), RNA_def_controller(), rna_def_curve(), rna_def_curve_nurb(), rna_def_curvemap(), rna_def_curvemappoint(), rna_def_drivertarget(), rna_def_drivervar(), rna_def_dynamic_paint_brush_settings(), rna_def_edit_object_actuator(), RNA_def_enum(), RNA_def_enum_flag(), rna_def_enum_property(), rna_def_environment_map(), rna_def_event(), rna_def_fcurve(), rna_def_field(), rna_def_fileselect_params(), rna_def_filter_common(), rna_def_fkeyframe(), RNA_def_fluidsim(), rna_def_fluidsim_domain(), rna_def_fluidsim_slip(), rna_def_fluidsim_volume(), rna_def_fmodifier(), rna_def_fmodifier_cycles(), rna_def_fmodifier_function_generator(), rna_def_fmodifier_generator(), rna_def_fmodifier_noise(), rna_def_font(), rna_def_game_actuator(), RNA_def_gameproperty(), rna_def_gpencil_data(), rna_def_header(), rna_def_histogram(), rna_def_image(), rna_def_joystick_sensor(), rna_def_keyblock(), rna_def_keyboard_sensor(), rna_def_keyconfig(), rna_def_keyingset_path(), rna_def_lamp(), rna_def_lamp_falloff(), rna_def_lamp_mtex(), rna_def_lamp_shadow(), rna_def_lamp_sky_settings(), rna_def_lattice(), rna_def_lighting(), rna_def_macro_operator(), RNA_def_material(), rna_def_material_colors(), rna_def_material_diffuse(), rna_def_material_gamesettings(), rna_def_material_mtex(), rna_def_material_raymirror(), rna_def_material_slot(), rna_def_material_specularity(), rna_def_material_volume(), rna_def_message_actuator(), rna_def_metaball(), rna_def_metaelement(), RNA_def_modifier(), rna_def_modifier_array(), rna_def_modifier_bevel(), rna_def_modifier_boolean(), rna_def_modifier_cast(), rna_def_modifier_curve(), rna_def_modifier_displace(), rna_def_modifier_dynamic_paint(), rna_def_modifier_generic_map_info(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smoke(), rna_def_modifier_warp(), rna_def_modifier_weightvg_mask(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), rna_def_modifier_weightvgproximity(), rna_def_mouse_sensor(), rna_def_movieclip(), rna_def_movieclip_proxy(), rna_def_moviecliUser(), rna_def_mtex(), rna_def_nlastrip(), rna_def_node_socket(), rna_def_node_socket_subtype(), rna_def_nodetree(), rna_def_object(), rna_def_object_actuator(), rna_def_object_game_settings(), rna_def_operator(), rna_def_panel(), rna_def_parent_actuator(), rna_def_particle(), rna_def_particle_edit(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_particle_target(), rna_def_pointcache(), rna_def_pose(), rna_def_pose_channel(), rna_def_pose_ikparam(), rna_def_pose_itasc(), rna_def_property(), rna_def_property_actuator(), rna_def_property_sensor(), rna_def_property_subdivision_common(), rna_def_radar_sensor(), rna_def_random_actuator(), rna_def_ray_sensor(), rna_def_region(), rna_def_render_pass(), RNA_def_scene(), rna_def_scene_actuator(), rna_def_scene_ffmpeg_settings(), rna_def_scene_game_data(), rna_def_scene_image_format_data(), rna_def_scene_render_data(), rna_def_scopes(), rna_def_sensor(), rna_def_sequence(), rna_def_shader_node(), rna_def_shape_action_actuator(), rna_def_smoke_domain_settings(), rna_def_softbody(), rna_def_sound_actuator(), rna_def_space(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_dopesheet(), rna_def_space_graph(), rna_def_space_image(), rna_def_space_image_uv(), rna_def_space_nla(), rna_def_space_node(), rna_def_space_outliner(), rna_def_space_sequencer(), rna_def_space_view3d(), rna_def_spot_lamp(), rna_def_state_actuator(), rna_def_steering_actuator(), rna_def_strip_proxy(), rna_def_texmapping(), rna_def_texture(), rna_def_texture_blend(), rna_def_texture_clouds(), rna_def_texture_distorted_noise(), rna_def_texture_image(), rna_def_texture_marble(), rna_def_texture_musgrave(), rna_def_texture_node(), rna_def_texture_ocean(), rna_def_texture_pointdensity(), rna_def_texture_stucci(), rna_def_texture_voronoi(), rna_def_texture_voxeldata(), rna_def_texture_wood(), rna_def_tool_settings(), rna_def_trackingCamera(), rna_def_trackingSettings(), rna_def_trackingStabilization(), rna_def_trackingTrack(), rna_def_transform(), rna_def_twodfilter_actuator(), rna_def_ui_layout(), rna_def_unit_settings(), RNA_def_userdef(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_system(), rna_def_userdef_theme_ui_font_style(), rna_def_userdef_themes(), rna_def_userdef_view(), rna_def_wipe(), rna_def_world_mist(), and rna_def_world_mtex().
void RNA_def_property_enum_sdna (PropertyRNA * prop, const char * structname, const char * propname)
Definition at line 1701 of file rna_define.c.
References PropertyRNA::arraydimension, BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, BlenderDefRNA::preprocess, PROP_ENUM, rna_def_property_sdna(), BlenderDefRNA::silent, PropertyRNA::totarraylength, and PropertyRNA::type.
Referenced by def_cmp_blur(), def_cmp_channel_matte(), def_cmp_color_spill(), def_cmp_colorbalance(), def_cmp_defocus(), def_cmp_double_edge_mask(), def_cmp_filter(), def_cmp_flip(), def_cmp_glare(), def_cmp_image(), def_cmp_levels(), def_cmp_moviedistortion(), def_cmp_premul_key(), def_cmp_render_layers(), def_cmp_rotate(), def_cmp_scale(), def_cmp_splitviewer(), def_cmp_stabilize2d(), def_cmp_tonemap(), def_cmp_ycc(), def_glossy(), def_math(), def_mix_rgb(), def_sh_tex_musgrave(), def_sh_tex_voronoi(), def_sh_tex_wave(), def_vector_math(), dev_cmd_transform(), rna_def_action(), rna_def_action_actuator(), rna_def_animdata(), rna_def_animviz_ghosts(), rna_def_animviz_paths(), rna_def_area(), rna_def_area_lamp(), rna_def_armature(), rna_def_armature_actuator(), rna_def_armature_sensor(), rna_def_background_image(), rna_def_beztriple(), rna_def_boidrule(), rna_def_bone_group(), rna_def_brush(), rna_def_brush_texture_slot(), RNA_def_camera(), rna_def_camera_actuator(), rna_def_canvas_surface(), rna_def_color_ramp(), rna_def_common_keying_flags(), RNA_def_constraint(), rna_def_constraint_action(), rna_def_constraint_actuator(), rna_def_constraint_clamp_to(), rna_def_constraint_damped_track(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_kinematic(), rna_def_constraint_locked_track(), rna_def_constraint_minmax(), rna_def_constraint_pivot(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_same_volume(), rna_def_constraint_shrinkwrap(), rna_def_constraint_spline_ik(), rna_def_constraint_stretch_to(), rna_def_constraint_track_to(), rna_def_constraint_transform(), rna_def_curve(), rna_def_curve_nurb(), rna_def_drivertarget(), rna_def_dynamic_paint_brush_settings(), rna_def_edit_object_actuator(), rna_def_environment_map(), rna_def_event(), rna_def_fcurve(), rna_def_field(), rna_def_fileselect_params(), rna_def_filter_common(), rna_def_fkeyframe(), rna_def_fluidsim_domain(), rna_def_fmodifier_cycles(), rna_def_fmodifier_function_generator(), rna_def_fmodifier_noise(), rna_def_font(), rna_def_game_actuator(), rna_def_header(), rna_def_histogram(), rna_def_image(), rna_def_joystick_sensor(), rna_def_keyblock(), rna_def_keyboard_sensor(), rna_def_keyconfig(), rna_def_keyingset_path(), rna_def_lamp_mtex(), rna_def_lamp_shadow(), rna_def_lamp_sky_settings(), rna_def_lattice(), rna_def_lighting(), rna_def_macro_operator(), RNA_def_material(), rna_def_material_colors(), rna_def_material_diffuse(), rna_def_material_gamesettings(), rna_def_material_mtex(), rna_def_material_raymirror(), rna_def_material_specularity(), rna_def_material_volume(), rna_def_message_actuator(), rna_def_metaball(), RNA_def_modifier(), rna_def_modifier_bevel(), rna_def_modifier_cast(), rna_def_modifier_curve(), rna_def_modifier_dynamic_paint(), rna_def_modifier_generic_map_info(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smoke(), rna_def_modifier_weightvgproximity(), rna_def_mouse_sensor(), rna_def_movieclip_proxy(), rna_def_moviecliUser(), rna_def_mtex(), rna_def_nlastrip(), rna_def_node_socket(), rna_def_node_socket_subtype(), rna_def_object(), rna_def_object_actuator(), rna_def_object_game_settings(), rna_def_operator(), rna_def_panel(), rna_def_parent_actuator(), rna_def_particle(), rna_def_particle_edit(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_particle_target(), rna_def_pose(), rna_def_pose_channel(), rna_def_pose_ikparam(), rna_def_pose_itasc(), RNA_def_property(), rna_def_property_actuator(), RNA_def_property_enum_bitflag_sdna(), rna_def_property_sensor(), rna_def_property_subdivision_common(), rna_def_ray_sensor(), rna_def_region(), rna_def_render_pass(), rna_def_scene_actuator(), rna_def_scene_ffmpeg_settings(), rna_def_scene_game_data(), rna_def_scene_image_format_data(), rna_def_scene_render_data(), rna_def_scopes(), rna_def_sequence(), rna_def_shape_action_actuator(), rna_def_smoke_domain_settings(), rna_def_softbody(), rna_def_sound_actuator(), rna_def_space(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_dopesheet(), rna_def_space_graph(), rna_def_space_image_uv(), rna_def_space_nla(), rna_def_space_node(), rna_def_space_outliner(), rna_def_space_sequencer(), rna_def_space_view3d(), rna_def_spot_lamp(), rna_def_state_actuator(), rna_def_steering_actuator(), rna_def_strip_proxy(), rna_def_texmapping(), rna_def_texture(), rna_def_texture_blend(), rna_def_texture_clouds(), rna_def_texture_distorted_noise(), rna_def_texture_image(), rna_def_texture_marble(), rna_def_texture_musgrave(), rna_def_texture_ocean(), rna_def_texture_pointdensity(), rna_def_texture_stucci(), rna_def_texture_voronoi(), rna_def_texture_voxeldata(), rna_def_texture_wood(), rna_def_tool_settings(), rna_def_trackingCamera(), rna_def_trackingSettings(), rna_def_trackingStabilization(), rna_def_trackingTrack(), rna_def_transform(), rna_def_twodfilter_actuator(), RNA_def_userdef(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_system(), rna_def_userdef_theme_ui_font_style(), rna_def_userdef_themes(), rna_def_userdef_view(), rna_def_wipe(), rna_def_world_mist(), and rna_def_world_mtex().
void RNA_def_property_flag (PropertyRNA * prop, int flag)
Definition at line 1053 of file rna_define.c.
References PropertyRNA::flag.
Referenced by ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_menu(), api_ui_item_op(), api_ui_item_rna_common(), ARMATURE_OT_subdivide(), BPy_BoolProperty(), BPy_BoolVectorProperty(), BPy_CollectionProperty(), BPy_EnumProperty(), BPy_FloatProperty(), BPy_FloatVectorProperty(), BPy_IntProperty(), BPy_IntVectorProperty(), BPy_PointerProperty(), bpy_prop_callback_assign(), BPy_StringProperty(), CONSOLE_OT_insert(), CURVE_OT_subdivide(), def_cmp_image(), def_cmp_movieclip(), def_cmp_moviedistortion(), def_cmp_render_layers(), def_cmp_stabilize2d(), def_forloop(), def_group(), def_sh_material(), def_sh_tex(), def_sh_tex_environment(), def_sh_tex_image(), def_tex_image(), def_texture(), def_whileloop(), ED_object_add_generic_props(), FILE_OT_execute(), MESH_OT_loopcut(), MESH_OT_subdivide(), MESH_OT_vert_slide(), OBJECT_OT_camera_add(), OBJECT_OT_duplicate(), POSE_OT_paste(), RENDER_OT_opengl(), RNA_api_actuator(), rna_api_animdata_nla_tracks(), RNA_api_armature_edit_bone(), RNA_api_bone(), RNA_api_camera(), RNA_api_environment_map(), RNA_api_image(), RNA_api_keyconfigs(), RNA_api_keymap(), RNA_api_keymapitem(), RNA_api_keymapitems(), RNA_api_keymaps(), RNA_api_macro(), RNA_api_main(), RNA_api_mesh(), rna_api_nlatrack_strips(), RNA_api_object(), RNA_api_object_base(), RNA_api_operator(), RNA_api_pose_channel(), RNA_api_scene(), RNA_api_scene_render(), RNA_api_sensor(), RNA_api_sequence_strip(), RNA_api_text(), RNA_api_texture(), RNA_api_ui_layout(), RNA_api_wm(), rna_def_action_actuator(), rna_def_action_fcurves(), rna_def_action_groups(), rna_def_action_pose_markers(), rna_def_animdata(), rna_def_animviz(), rna_def_animviz_common(), rna_def_area(), rna_def_armature(), rna_def_armature_actuator(), rna_def_armature_bones(), rna_def_armature_edit_bones(), rna_def_background_image(), rna_def_backgroundImages(), rna_def_boidrule_avoid(), rna_def_boidrule_follow_leader(), rna_def_boidrule_goal(), rna_def_bone_group(), rna_def_bone_groups(), rna_def_brush(), RNA_def_camera(), rna_def_camera_actuator(), rna_def_canvas_surface(), rna_def_channeldriver_variables(), rna_def_cloth_collision_settings(), rna_def_cloth_sim_settings(), rna_def_collision_sensor(), rna_def_color_ramp(), rna_def_color_ramp_element_api(), rna_def_common_keying_flags(), rna_def_composite_nodetree_api(), rna_def_constraint_action(), rna_def_constraint_actuator(), rna_def_constraint_camera_solver(), rna_def_constraint_childof(), rna_def_constraint_clamp_to(), rna_def_constraint_damped_track(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_follow_track(), rna_def_constraint_kinematic(), rna_def_constraint_locate_like(), rna_def_constraint_locked_track(), rna_def_constraint_minmax(), rna_def_constraint_object_solver(), rna_def_constraint_pivot(), rna_def_constraint_python(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_rotate_like(), rna_def_constraint_shrinkwrap(), rna_def_constraint_size_like(), rna_def_constraint_spline_ik(), rna_def_constraint_stretch_to(), rna_def_constraint_track_to(), rna_def_constraint_transform(), rna_def_constraint_transform_like(), rna_def_constrainttarget(), RNA_def_controller(), rna_def_curve(), rna_def_curve_spline_bezpoints(), rna_def_curve_splines(), rna_def_dopesheet(), rna_def_drivertarget(), rna_def_dynamic_paint_brush_settings(), rna_def_edit_bone(), rna_def_edit_object_actuator(), rna_def_editor(), rna_def_effector_weight(), RNA_def_enum_flag(), rna_def_enum_property(), rna_def_environment_map(), rna_def_fcurve(), rna_def_fcurve_keyframe_points(), rna_def_fcurve_modifiers(), rna_def_field(), rna_def_fmodifier_generator(), rna_def_font(), rna_def_gpencil_layers(), rna_def_group_objects(), rna_def_group_sockets_api(), rna_def_header(), rna_def_ID(), rna_def_ID_materials(), rna_def_ID_properties(), rna_def_image(), rna_def_key(), rna_def_keyblock(), rna_def_keyingset(), rna_def_keyingset_info(), rna_def_keyingset_path(), rna_def_keyingset_paths(), rna_def_lamp_mtex(), rna_def_loop_colors(), rna_def_macro_operator(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_gpencil(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_libraries(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_movieclips(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_screens(), RNA_def_main_sounds(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_window_managers(), RNA_def_main_worlds(), RNA_def_material(), rna_def_material_mtex(), rna_def_material_slot(), rna_def_menu(), rna_def_mesh(), rna_def_metaball_elements(), rna_def_mface(), RNA_def_modifier(), rna_def_modifier_armature(), rna_def_modifier_array(), rna_def_modifier_boolean(), rna_def_modifier_cast(), rna_def_modifier_cloth(), rna_def_modifier_collision(), rna_def_modifier_curve(), rna_def_modifier_fluidsim(), rna_def_modifier_generic_map_info(), rna_def_modifier_hook(), rna_def_modifier_lattice(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_mirror(), rna_def_modifier_particleinstance(), rna_def_modifier_particlesystem(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_softbody(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvg_mask(), rna_def_modifier_weightvgproximity(), rna_def_movieclip(), rna_def_mpolygon(), rna_def_mtex(), rna_def_mtex_common(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_nlastrip(), rna_def_nodetree(), rna_def_nodetree_link_api(), rna_def_number_property(), rna_def_object(), rna_def_object_actuator(), rna_def_object_constraints(), rna_def_object_modifiers(), rna_def_object_vertex_groups(), rna_def_operator(), rna_def_operator_filelist_element(), rna_def_operator_stroke_element(), rna_def_operator_type_macro(), rna_def_operator_utils(), rna_def_paint(), rna_def_panel(), rna_def_parent_actuator(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_particle_system(), rna_def_particle_target(), rna_def_polygon_float_layers(), rna_def_polygon_int_layers(), rna_def_polygon_string_layers(), rna_def_pose_channel(), rna_def_pose_channel_constraints(), RNA_def_property(), rna_def_property_actuator(), rna_def_ray_sensor(), rna_def_render_engine(), rna_def_render_layer(), rna_def_render_layer_common(), rna_def_render_layers(), rna_def_render_pass(), rna_def_render_result(), RNA_def_scene(), rna_def_scene(), rna_def_scene_actuator(), rna_def_scene_bases(), rna_def_scene_game_data(), rna_def_scene_keying_sets(), rna_def_scene_keying_sets_all(), rna_def_scene_objects(), rna_def_scene_render_data(), rna_def_screen(), rna_def_selected_uv_element(), rna_def_shader_nodetree_api(), rna_def_shape_action_actuator(), rna_def_smoke_domain_settings(), rna_def_smoke_flow_settings(), rna_def_sound_actuator(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_dopesheet(), rna_def_space_image(), rna_def_space_node(), rna_def_space_text(), rna_def_space_view3d(), rna_def_speaker(), rna_def_steering_actuator(), RNA_def_struct(), rna_def_sun_lamp(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), RNA_def_test(), rna_def_text(), rna_def_texture_environment_map(), rna_def_texture_image(), rna_def_texture_nodetree_api(), rna_def_texture_ocean(), rna_def_texture_pointdensity(), rna_def_texture_slots(), rna_def_texture_voxeldata(), rna_def_timeline_marker(), rna_def_timeline_markers(), rna_def_tool_settings(), rna_def_touch_sensor(), rna_def_trackingMarkers(), rna_def_trackingObjects(), rna_def_trackingObjectTracks(), rna_def_trackingStabilization(), rna_def_trackingTracks(), rna_def_twodfilter_actuator(), RNA_def_userdef(), rna_def_userdef_addon_collection(), rna_def_userdef_system(), rna_def_userdef_theme_spaces_list_main(), rna_def_userdef_theme_spaces_main(), rna_def_userdef_theme_ui(), rna_def_userdef_theme_ui_style(), rna_def_userdef_themes(), rna_def_uv_layers(), rna_def_uv_textures(), rna_def_vertex_group(), rna_def_window(), rna_def_wm_keyconfigs(), RNA_def_world(), rna_def_world_mtex(), rna_generic_op_invoke(), SCREEN_OT_animation_play(), SEQUENCER_OT_reload(), TEXT_OT_insert(), TEXTURE_OT_envmap_save(), TRANSFORM_OT_transform(), Transform_Properties(), UV_OT_stitch(), VIEW3D_OT_enable_manipulator(), VIEW3D_OT_select_menu(), VIEW3D_OT_viewnumpad(), WM_operator_properties_filesel(), and WM_operator_properties_sanitize().
void RNA_def_property_float_array_default (PropertyRNA * prop, const float * array)
Definition at line 1418 of file rna_define.c.
References FloatPropertyRNA::defaultarray, BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, PROP_FLOAT, and PropertyRNA::type.
Referenced by BPy_FloatVectorProperty(), def_cmp_colorbalance(), IMAGE_OT_new(), RNA_def_float_array(), RNA_def_float_color(), RNA_def_float_matrix(), RNA_def_float_rotation(), RNA_def_float_vector(), rna_def_object(), rna_def_pose_channel(), and rna_def_userdef_solidlight().
void RNA_def_property_float_default (PropertyRNA * prop, float value)
Definition at line 1401 of file rna_define.c.
References FloatPropertyRNA::defaultvalue, BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, PROP_FLOAT, and PropertyRNA::type.
Referenced by BPy_FloatProperty(), MESH_OT_dissolve_limited(), MESH_OT_tris_convert_to_quads(), OBJECT_OT_vertex_group_blend(), rna_def_animdata(), rna_def_brush(), rna_def_cloth_collision_settings(), RNA_def_float(), RNA_def_float_factor(), RNA_def_float_percentage(), rna_def_fmodifier(), rna_def_keyblock(), rna_def_particle_settings(), rna_def_space_node(), rna_def_space_view3d(), rna_def_trackingCamera(), rna_def_trackingObject(), rna_def_trackingSettings(), and rna_def_unified_paint_settings().
void RNA_def_property_float_funcs (PropertyRNA * prop, const char * get, const char * set, const char * range)
Definition at line 1992 of file rna_define.c.
References PropertyRNA::arraydimension, BlenderDefRNA::error, FloatPropertyRNA::get, FloatPropertyRNA::getarray, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, BlenderDefRNA::preprocess, PROP_FLOAT, FloatPropertyRNA::range, FloatPropertyRNA::set, FloatPropertyRNA::setarray, and PropertyRNA::type.
Referenced by def_cmp_channel_matte(), def_cmp_chroma_matte(), def_cmp_diff_matte(), def_cmp_distance_matte(), def_cmp_luma_matte(), rna_def_action(), rna_def_background_image(), rna_def_beztriple(), rna_def_brush(), RNA_def_camera(), rna_def_cloth_sim_settings(), rna_def_constraint_action(), rna_def_constraint_actuator(), rna_def_constraint_spline_ik(), rna_def_curve(), rna_def_curvemapping(), rna_def_edit_bone(), rna_def_fkeyframe(), rna_def_fmodifier(), rna_def_fmodifier_generator(), rna_def_fmodifier_limits(), rna_def_fmodifier_stepped(), RNA_def_gameproperty(), rna_def_image(), rna_def_keyblock(), rna_def_keydata(), rna_def_latticepoint(), rna_def_material_strand(), rna_def_mcol(), rna_def_medge(), rna_def_mesh(), rna_def_metaball(), rna_def_mface(), rna_def_mloopcol(), rna_def_modifier_bevel(), rna_def_modifier_edgesplit(), rna_def_modifier_ocean(), rna_def_mpolygon(), rna_def_mtface(), rna_def_mvert(), rna_def_nlastrip(), rna_def_node_socket_subtype(), rna_def_number_property(), rna_def_object(), rna_def_object_actuator(), rna_def_particle_hair_key(), rna_def_particle_settings(), rna_def_pose_channel(), rna_def_render_layer(), rna_def_render_pass(), RNA_def_scene(), rna_def_sequence(), rna_def_sound(), rna_def_space_image(), rna_def_space_image_uv(), rna_def_space_view3d(), rna_def_spot_lamp(), RNA_def_test(), rna_def_trackingCamera(), rna_def_ui_layout(), rna_def_unified_paint_settings(), and rna_def_wipe().
void RNA_def_property_float_sdna (PropertyRNA * prop, const char * structname, const char * propname)
Definition at line 1661 of file rna_define.c.
References PropertyDefRNA::dnatype, BlenderDefRNA::error, FloatPropertyRNA::hardmax, FloatPropertyRNA::hardmin, StructRNA::identifier, PropertyRNA::identifier, IS_DNATYPE_FLOAT_COMPAT, BlenderDefRNA::laststruct, BlenderDefRNA::preprocess, PROP_COLOR_GAMMA, PROP_FLOAT, rna_def_property_sdna(), RNA_property_typename(), BlenderDefRNA::silent, FloatPropertyRNA::softmax, FloatPropertyRNA::softmin, PropertyRNA::subtype, and PropertyRNA::type.
Referenced by def_cmp_alpha_over(), def_cmp_bilateral_blur(), def_cmp_blur(), def_cmp_channel_matte(), def_cmp_chroma_matte(), def_cmp_color_matte(), def_cmp_color_spill(), def_cmp_colorbalance(), def_cmp_crop(), def_cmp_dblur(), def_cmp_defocus(), def_cmp_diff_matte(), def_cmp_distance_matte(), def_cmp_glare(), def_cmp_hue_saturation(), def_cmp_luma_matte(), def_cmp_map_value(), def_cmp_tonemap(), def_cmp_vector_blur(), def_sh_mapping(), def_tex_bricks(), rna_def_action_actuator(), rna_def_animdata(), rna_def_area_lamp(), rna_def_armature_actuator(), rna_def_armature_sensor(), rna_def_background_image(), rna_def_beztriple(), rna_def_boid_settings(), rna_def_boidstate(), rna_def_bone(), rna_def_bone_common(), rna_def_bpoint(), rna_def_brush(), rna_def_brush_texture_slot(), RNA_def_camera(), rna_def_camera_actuator(), rna_def_canvas_surface(), rna_def_cloth_collision_settings(), rna_def_cloth_sim_settings(), rna_def_collision(), rna_def_color_ramp_element(), rna_def_colormapping(), RNA_def_constraint(), rna_def_constraint_action(), rna_def_constraint_actuator(), rna_def_constraint_childof(), rna_def_constraint_damped_track(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_kinematic(), rna_def_constraint_locate_like(), rna_def_constraint_location_limit(), rna_def_constraint_locked_track(), rna_def_constraint_pivot(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_rotation_limit(), rna_def_constraint_shrinkwrap(), rna_def_constraint_size_limit(), rna_def_constraint_stretch_to(), rna_def_constraint_track_to(), rna_def_constraint_transform(), rna_def_constraint_transform_like(), rna_def_curve(), rna_def_curvemapping(), rna_def_curvemappoint(), rna_def_dupli_object(), rna_def_dynamic_paint_brush_settings(), rna_def_edit_bone(), rna_def_edit_object_actuator(), rna_def_effector_weight(), rna_def_environment_map(), rna_def_field(), rna_def_filter_common(), rna_def_filter_video(), rna_def_fluid_mesh_vertices(), rna_def_fluid_settings(), rna_def_fluidsim_control(), rna_def_fluidsim_domain(), rna_def_fluidsim_fluid(), rna_def_fluidsim_inflow(), rna_def_fluidsim_obstacle(), rna_def_fluidsim_particle(), rna_def_fluidsim_slip(), rna_def_fmodifier(), rna_def_fmodifier_envelope(), rna_def_fmodifier_envelope_ctrl(), rna_def_fmodifier_limits(), rna_def_fmodifier_noise(), rna_def_fmodifier_stepped(), rna_def_font(), rna_def_fpoint(), rna_def_game_softbody(), rna_def_glow(), rna_def_gpencil_layer(), rna_def_gpencil_stroke_point(), RNA_def_group(), rna_def_image(), rna_def_key(), rna_def_keyblock(), rna_def_lamp(), rna_def_lamp_falloff(), rna_def_lamp_mtex(), rna_def_lamp_shadow(), rna_def_lamp_sky_settings(), rna_def_latticepoint(), rna_def_lighting(), RNA_def_material(), rna_def_material_colors(), rna_def_material_diffuse(), rna_def_material_halo(), rna_def_material_mtex(), rna_def_material_physics(), rna_def_material_raymirror(), rna_def_material_raytra(), rna_def_material_specularity(), rna_def_material_sss(), rna_def_material_strand(), rna_def_material_volume(), rna_def_metaball(), rna_def_metaelement(), rna_def_modifier_array(), rna_def_modifier_bevel(), rna_def_modifier_build(), rna_def_modifier_cast(), rna_def_modifier_decimate(), rna_def_modifier_displace(), rna_def_modifier_mirror(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smooth(), rna_def_modifier_solidify(), rna_def_modifier_uvproject(), rna_def_modifier_wave(), rna_def_modifier_weightvgedit(), rna_def_movieclip(), rna_def_mproperties(), rna_def_mtex(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_near_sensor(), rna_def_nlastrip(), rna_def_node(), rna_def_node_socket_subtype(), rna_def_object(), rna_def_object_actuator(), rna_def_object_game_settings(), rna_def_particle(), rna_def_particle_edit(), rna_def_particle_hair_key(), rna_def_particle_key(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_particle_target(), rna_def_pose_channel(), rna_def_pose_itasc(), RNA_def_property(), rna_def_radar_sensor(), rna_def_random_actuator(), rna_def_reconstructedCamera(), RNA_def_scene(), rna_def_scene_ffmpeg_settings(), rna_def_scene_game_data(), rna_def_scene_game_recast_data(), rna_def_scene_image_format_data(), rna_def_scene_render_data(), rna_def_scopes(), rna_def_sequence(), rna_def_shape_action_actuator(), rna_def_smoke_domain_settings(), rna_def_smoke_flow_settings(), rna_def_softbody(), rna_def_solid_color(), rna_def_sound(), rna_def_sound_actuator(), rna_def_space_graph(), rna_def_space_node(), rna_def_space_view3d(), rna_def_speaker(), rna_def_speed_control(), rna_def_spot_lamp(), rna_def_steering_actuator(), rna_def_texmapping(), rna_def_texmat_common(), rna_def_textbox(), rna_def_texture(), rna_def_texture_clouds(), rna_def_texture_distorted_noise(), rna_def_texture_image(), rna_def_texture_magic(), rna_def_texture_marble(), rna_def_texture_musgrave(), rna_def_texture_pointdensity(), rna_def_texture_stucci(), rna_def_texture_voronoi(), rna_def_texture_voxeldata(), rna_def_texture_wood(), rna_def_timer(), rna_def_tool_settings(), rna_def_trackingCamera(), rna_def_trackingMarker(), rna_def_trackingObject(), rna_def_trackingReconstruction(), rna_def_trackingSettings(), rna_def_trackingStabilization(), rna_def_trackingTrack(), rna_def_transform(), rna_def_transform_orientation(), rna_def_twodfilter_actuator(), rna_def_unified_paint_settings(), rna_def_userdef_edit(), rna_def_userdef_solidlight(), rna_def_userdef_system(), rna_def_userdef_theme_colorset(), rna_def_userdef_theme_space_action(), rna_def_userdef_theme_space_clip(), rna_def_userdef_theme_space_console(), rna_def_userdef_theme_space_file(), rna_def_userdef_theme_space_graph(), rna_def_userdef_theme_space_image(), rna_def_userdef_theme_space_nla(), rna_def_userdef_theme_space_node(), rna_def_userdef_theme_space_seq(), rna_def_userdef_theme_space_text(), rna_def_userdef_theme_space_time(), rna_def_userdef_theme_space_view3d(), rna_def_userdef_theme_spaces_curves(), rna_def_wipe(), RNA_def_world(), rna_def_world_mist(), rna_def_world_mtex(), and rna_def_world_stars().
int RNA_def_property_free_identifier (StructOrFunctionRNA * cont_, const char * identifier)
Referenced by BPy_RemoveProperty(), and pyrna_struct_meta_idprop_setattro().
void RNA_def_property_free_pointers (PropertyRNA * prop)
Referenced by RNA_struct_free().
void RNA_def_property_int_array_default (PropertyRNA * prop, const int * array)
Definition at line 1384 of file rna_define.c.
References IntPropertyRNA::defaultarray, BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, PROP_INT, and PropertyRNA::type.
Referenced by BPy_IntVectorProperty(), RNA_def_int_array(), and RNA_def_int_vector().
void RNA_def_property_int_default (PropertyRNA * prop, int value)
Definition at line 1367 of file rna_define.c.
References IntPropertyRNA::defaultvalue, BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, PROP_INT, and PropertyRNA::type.
Referenced by BPy_IntProperty(), RNA_def_int(), rna_def_sculpt(), rna_def_space_view3d(), rna_def_userdef_theme_space_node(), and rna_def_userdef_view().
void RNA_def_property_int_funcs (PropertyRNA * prop, const char * get, const char * set, const char * range)
Definition at line 1961 of file rna_define.c.
References PropertyRNA::arraydimension, BlenderDefRNA::error, IntPropertyRNA::get, IntPropertyRNA::getarray, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, BlenderDefRNA::preprocess, PROP_INT, IntPropertyRNA::range, IntPropertyRNA::set, IntPropertyRNA::setarray, and PropertyRNA::type.
Referenced by rna_def_action_pose_markers(), rna_def_animviz_ghosts(), rna_def_animviz_paths(), rna_def_armature(), rna_def_boid_settings(), rna_def_boidstate(), rna_def_bone_groups(), rna_def_brush(), rna_def_canvas_surfaces(), rna_def_console_line(), RNA_def_controller(), rna_def_curve_nurb(), rna_def_editor(), rna_def_enum_property(), rna_def_font(), rna_def_image(), rna_def_input(), rna_def_keyingset_paths(), rna_def_lattice(), rna_def_loop_colors(), rna_def_medge(), rna_def_mesh(), rna_def_mface(), rna_def_mloop(), rna_def_modifier_multires(), rna_def_modifier_uvproject(), rna_def_movieclip(), rna_def_mpolygon(), rna_def_mvert(), rna_def_node_socket_subtype(), rna_def_number_property(), rna_def_object(), rna_def_object_particle_systems(), rna_def_object_vertex_groups(), rna_def_particle_settings(), rna_def_particle_system(), rna_def_pointcache(), rna_def_pose_channel(), rna_def_ptcache_point_caches(), rna_def_render_layers(), RNA_def_scene(), rna_def_scene_keying_sets(), rna_def_scene_keying_sets_all(), rna_def_scene_render_data(), rna_def_sequence(), rna_def_spot_lamp(), rna_def_string_property(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), RNA_def_test(), rna_def_tracking(), rna_def_trackingMarker(), rna_def_trackingStabilization(), rna_def_unified_paint_settings(), rna_def_uv_layers(), rna_def_uv_textures(), and rna_def_vertex_group().
void RNA_def_property_int_sdna (PropertyRNA * prop, const char * structname, const char * propname)
Definition at line 1610 of file rna_define.c.
References PropertyDefRNA::dnatype, BlenderDefRNA::error, IntPropertyRNA::hardmax, IntPropertyRNA::hardmin, StructRNA::identifier, PropertyRNA::identifier, IS_DNATYPE_INT_COMPAT, BlenderDefRNA::laststruct, BlenderDefRNA::preprocess, PROP_FACTOR, PROP_INT, PROP_PERCENTAGE, PROP_UNSIGNED, rna_def_property_sdna(), RNA_property_typename(), BlenderDefRNA::silent, IntPropertyRNA::softmax, IntPropertyRNA::softmin, PropertyRNA::subtype, and PropertyRNA::type.
Referenced by def_cmp_bilateral_blur(), def_cmp_blur(), def_cmp_crop(), def_cmp_dblur(), def_cmp_defocus(), def_cmp_dilate_erode(), def_cmp_glare(), def_cmp_id_mask(), def_cmp_image(), def_cmp_map_uv(), def_cmp_output_file(), def_cmp_splitviewer(), def_cmp_vector_blur(), def_sh_tex_magic(), def_tex_bricks(), def_texture(), def_time(), def_whileloop(), rna_def_action_actuator(), rna_def_action_group(), rna_def_action_pose_markers(), rna_def_animviz_ghosts(), rna_def_animviz_motion_path(), rna_def_animviz_paths(), rna_def_area(), rna_def_armature(), rna_def_boidrule_follow_leader(), rna_def_bone_common(), rna_def_bone_groups(), rna_def_brush(), rna_def_canvas_surface(), rna_def_cloth_collision_settings(), rna_def_cloth_sim_settings(), rna_def_color_ramp(), rna_def_console_line(), rna_def_constraint_action(), rna_def_constraint_actuator(), rna_def_constraint_kinematic(), rna_def_constraint_python(), rna_def_constraint_spline_ik(), RNA_def_controller(), rna_def_curve(), rna_def_curve_nurb(), rna_def_environment_map(), rna_def_event(), rna_def_filter_common(), rna_def_fluidsim_domain(), rna_def_fmodifier_cycles(), rna_def_fmodifier_noise(), rna_def_font(), rna_def_game_softbody(), RNA_def_gameproperty(), rna_def_glow(), rna_def_gpencil_frame(), rna_def_gpencil_layer(), rna_def_ID(), rna_def_image(), rna_def_imageuser(), rna_def_input(), rna_def_joystick_sensor(), rna_def_key(), rna_def_keyconfig(), rna_def_keyingset_paths(), rna_def_lamp_shadow(), rna_def_lattice(), rna_def_lighting(), RNA_def_material(), rna_def_material_halo(), rna_def_material_raymirror(), rna_def_material_raytra(), rna_def_material_specularity(), rna_def_material_volume(), rna_def_medge(), rna_def_mesh(), rna_def_mesh_polygons(), rna_def_mesh_tessfaces(), rna_def_mface(), rna_def_mloop(), rna_def_modifier_decimate(), rna_def_modifier_meshdeform(), rna_def_modifier_multires(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_smooth(), rna_def_modifier_solidify(), rna_def_modifier_subsurf(), rna_def_modifier_uvproject(), rna_def_movie(), rna_def_movieclip_proxy(), rna_def_moviecliUser(), rna_def_mpolygon(), rna_def_mproperties(), rna_def_mtex_common(), rna_def_multicam(), rna_def_mvert_group(), rna_def_node_socket_subtype(), rna_def_object(), rna_def_object_vertex_groups(), rna_def_particle_edit(), rna_def_particle_settings(), rna_def_particle_system(), rna_def_particle_target(), rna_def_path(), rna_def_pointcache(), rna_def_pose_channel(), rna_def_pose_itasc(), RNA_def_property(), rna_def_random_actuator(), rna_def_reconstructedCamera(), rna_def_region(), rna_def_render_layers(), rna_def_render_pass(), rna_def_render_result(), RNA_def_scene(), rna_def_scene_ffmpeg_settings(), rna_def_scene_game_data(), rna_def_scene_game_recast_data(), rna_def_scene_image_format_data(), rna_def_scene_keying_sets(), rna_def_scene_keying_sets_all(), rna_def_scene_render_data(), rna_def_sculpt(), rna_def_sensor(), rna_def_sequence(), rna_def_shape_action_actuator(), rna_def_smoke_domain_settings(), rna_def_softbody(), rna_def_space_clip(), rna_def_space_console(), rna_def_space_sequencer(), rna_def_space_text(), rna_def_space_view3d(), rna_def_spot_lamp(), rna_def_steering_actuator(), rna_def_strip_crop(), rna_def_strip_element(), rna_def_strip_proxy(), rna_def_strip_transform(), rna_def_text(), rna_def_text_marker(), rna_def_texture_clouds(), rna_def_texture_image(), rna_def_texture_magic(), rna_def_texture_marble(), rna_def_texture_pointdensity(), rna_def_texture_voxeldata(), rna_def_tool_settings(), rna_def_tracking(), rna_def_trackingMarker(), rna_def_trackingSettings(), rna_def_trackingStabilization(), rna_def_trackingTrack(), rna_def_twodfilter_actuator(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_system(), rna_def_userdef_theme_space_node(), rna_def_userdef_theme_ui_font_style(), and rna_def_userdef_view().
void RNA_def_property_multi_array (PropertyRNA * prop, int dimension, const int length[])
Definition at line 1109 of file rna_define.c.
References PropertyRNA::arraydimension, PropertyRNA::arraylength, BlenderDefRNA::error, i, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, RNA_MAX_ARRAY_DIMENSION, PropertyRNA::totarraylength, and PropertyRNA::type.
Referenced by rna_def_bone(), rna_def_constraint_childof(), rna_def_dupli_object(), rna_def_edit_bone(), RNA_def_float_matrix(), rna_def_image(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_object(), rna_def_pose_channel(), rna_def_reconstructedCamera(), rna_def_render_layer(), rna_def_render_pass(), rna_def_softbody(), rna_def_space_view3d(), and rna_def_transform_orientation().
void RNA_def_property_pointer_funcs (PropertyRNA * prop, const char * get, const char * set, const char * typef, const char * poll)
Definition at line 2073 of file rna_define.c.
References BlenderDefRNA::error, PointerPropertyRNA::get, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, PointerPropertyRNA::poll, BlenderDefRNA::preprocess, PROP_POINTER, PointerPropertyRNA::set, PropertyRNA::type, and PointerPropertyRNA::typef.
Referenced by def_cmp_output_file(), def_cmp_render_layers(), rna_api_animdata_nla_tracks(), rna_def_action_actuator(), rna_def_action_pose_markers(), rna_def_animdata(), rna_def_animviz(), rna_def_armature_bones(), rna_def_armature_edit_bones(), rna_def_boid_settings(), rna_def_boidstate(), rna_def_bone_groups(), rna_def_brush(), rna_def_canvas_surfaces(), rna_def_cloth_sim_settings(), rna_def_constraint_clamp_to(), rna_def_constraint_follow_path(), rna_def_constraint_follow_track(), rna_def_constraint_object_solver(), rna_def_constraint_shrinkwrap(), RNA_def_context(), rna_def_curve(), rna_def_curve_splines(), rna_def_drivertarget(), rna_def_edit_bone(), rna_def_edit_object_actuator(), rna_def_fcurve(), rna_def_fcurve_modifiers(), rna_def_font(), rna_def_gpencil_layers(), rna_def_keyblock(), rna_def_keyconfig(), rna_def_keyingset(), rna_def_keyingset_path(), rna_def_keyingset_paths(), rna_def_loop_colors(), rna_def_macro_operator(), RNA_def_main(), RNA_def_material(), rna_def_material_slot(), rna_def_mesh(), rna_def_modifier_armature(), rna_def_modifier_array(), rna_def_modifier_boolean(), rna_def_modifier_cast(), rna_def_modifier_collision(), rna_def_modifier_curve(), rna_def_modifier_lattice(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_shrinkwrap(), rna_def_modifier_softbody(), rna_def_modifier_uvproject(), rna_def_mtex_common(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_nlastrip(), rna_def_object(), rna_def_object_constraints(), rna_def_object_modifiers(), rna_def_object_particle_systems(), rna_def_object_vertex_groups(), rna_def_operator(), rna_def_operator_type_macro(), rna_def_paint(), rna_def_particle_edit(), rna_def_particle_settings(), rna_def_particle_system(), rna_def_pointer_property(), rna_def_pose(), rna_def_pose_channel(), rna_def_pose_channel_constraints(), rna_def_property(), rna_def_render_layers(), RNA_def_scene(), rna_def_scene(), rna_def_scene_keying_sets(), rna_def_scene_keying_sets_all(), rna_def_scene_objects(), rna_def_screen(), rna_def_shape_action_actuator(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_dopesheet(), rna_def_space_image(), rna_def_space_node(), rna_def_space_text(), rna_def_space_view3d(), rna_def_steering_actuator(), RNA_def_struct(), rna_def_struct(), rna_def_sun_lamp(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), rna_def_texture_pointdensity(), rna_def_tool_settings(), rna_def_touch_sensor(), rna_def_trackingObjects(), rna_def_trackingObjectTracks(), rna_def_trackingTracks(), RNA_def_userdef(), rna_def_userdef_theme_spaces_list_main(), rna_def_userdef_theme_spaces_main(), rna_def_uv_layers(), rna_def_uv_textures(), rna_def_window(), rna_def_wm_keyconfigs(), and RNA_def_world().
void RNA_def_property_pointer_sdna (PropertyRNA * prop, const char * structname, const char * propname)
Definition at line 1769 of file rna_define.c.
References PropertyRNA::arraydimension, BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, BlenderDefRNA::preprocess, PROP_POINTER, rna_def_property_sdna(), BlenderDefRNA::silent, PropertyRNA::totarraylength, and PropertyRNA::type.
Referenced by def_cmp_huecorrect(), def_cmp_image(), def_cmp_movieclip(), def_cmp_moviedistortion(), def_cmp_render_layers(), def_cmp_stabilize2d(), def_colorramp(), def_forloop(), def_group(), def_rgb_curve(), def_sh_material(), def_sh_tex(), def_sh_tex_environment(), def_sh_tex_image(), def_tex_image(), def_texture(), def_time(), def_vector_curve(), def_whileloop(), rna_def_action_actuator(), rna_def_animdata_common(), rna_def_animviz_common(), rna_def_area_spaces(), rna_def_armature_actuator(), rna_def_armature_bones(), rna_def_armature_edit_bones(), rna_def_background_image(), rna_def_boidrule_avoid(), rna_def_boidrule_follow_leader(), rna_def_boidrule_goal(), rna_def_bone(), rna_def_bone_group(), rna_def_brush(), RNA_def_camera(), rna_def_camera_actuator(), rna_def_canvas_surface(), rna_def_collision_sensor(), rna_def_colormapping(), rna_def_constraint_action(), rna_def_constraint_camera_solver(), rna_def_constraint_childof(), rna_def_constraint_clamp_to(), rna_def_constraint_damped_track(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_follow_track(), rna_def_constraint_kinematic(), rna_def_constraint_locate_like(), rna_def_constraint_locked_track(), rna_def_constraint_minmax(), rna_def_constraint_object_solver(), rna_def_constraint_pivot(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_rotate_like(), rna_def_constraint_shrinkwrap(), rna_def_constraint_size_like(), rna_def_constraint_spline_ik(), rna_def_constraint_stretch_to(), rna_def_constraint_track_to(), rna_def_constraint_transform(), rna_def_constraint_transform_like(), rna_def_constrainttarget(), rna_def_curve(), rna_def_dopesheet(), rna_def_dupli_object(), rna_def_dynamic_paint_brush_settings(), rna_def_edit_object_actuator(), rna_def_editor(), rna_def_environment_map(), rna_def_fcurve(), rna_def_field(), rna_def_filter_video(), rna_def_font(), rna_def_gpencil_layer(), rna_def_header(), rna_def_ID(), rna_def_image(), rna_def_key(), rna_def_lamp(), rna_def_lamp_falloff(), rna_def_lamp_mtex(), rna_def_lattice(), RNA_def_material(), rna_def_material_colors(), rna_def_material_mtex(), rna_def_menu(), rna_def_mesh(), rna_def_metaball_elements(), rna_def_modifier_array(), rna_def_modifier_cloth(), rna_def_modifier_dynamic_paint(), rna_def_modifier_fluidsim(), rna_def_modifier_generic_map_info(), rna_def_modifier_mask(), rna_def_modifier_mirror(), rna_def_modifier_particleinstance(), rna_def_modifier_particlesystem(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_smoke(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvg_mask(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgproximity(), rna_def_motionpath_common(), rna_def_movieclip(), rna_def_mtex(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_nlastrip(), rna_def_node(), rna_def_node_link(), rna_def_node_socket(), rna_def_nodetree(), rna_def_object(), rna_def_object_actuator(), rna_def_object_base(), rna_def_object_game_settings(), rna_def_object_modifiers(), rna_def_parent_actuator(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_particle_system(), rna_def_particle_target(), rna_def_pose_channel(), RNA_def_property(), rna_def_property_actuator(), rna_def_proxy(), rna_def_ray_sensor(), rna_def_render_engine(), rna_def_render_layer_common(), RNA_def_scene(), rna_def_scene_bases(), rna_def_scene_game_data(), rna_def_scene_render_data(), rna_def_scopes(), rna_def_sequence(), rna_def_shape_action_actuator(), rna_def_smoke_domain_settings(), rna_def_smoke_flow_settings(), rna_def_softbody(), rna_def_sound(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_dopesheet(), rna_def_space_filebrowser(), rna_def_space_graph(), rna_def_space_image(), rna_def_space_nla(), rna_def_space_node(), rna_def_space_sequencer(), rna_def_space_view3d(), rna_def_speaker(), rna_def_steering_actuator(), rna_def_text(), rna_def_texture(), rna_def_texture_environment_map(), rna_def_texture_image(), rna_def_texture_ocean(), rna_def_texture_pointdensity(), rna_def_texture_voxeldata(), rna_def_tool_settings(), rna_def_touch_sensor(), rna_def_trackingStabilization(), rna_def_twodfilter_actuator(), rna_def_userdef_system(), rna_def_userdef_theme_ui_style(), rna_def_userdef_themes(), RNA_def_vfont(), rna_def_wm_keyconfigs(), RNA_def_world(), and rna_def_world_mtex().
void RNA_def_property_range (PropertyRNA * prop, double min, double max)
Definition at line 1192 of file rna_define.c.
References BlenderDefRNA::error, IntPropertyRNA::hardmax, FloatPropertyRNA::hardmax, FloatPropertyRNA::hardmin, IntPropertyRNA::hardmin, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, MAX2, MIN2, PROP_FLOAT, PROP_INT, IntPropertyRNA::softmax, FloatPropertyRNA::softmax, FloatPropertyRNA::softmin, IntPropertyRNA::softmin, and PropertyRNA::type.
Referenced by BPy_FloatProperty(), BPy_FloatVectorProperty(), BPy_IntProperty(), BPy_IntVectorProperty(), def_cmp_alpha_over(), def_cmp_bilateral_blur(), def_cmp_blur(), def_cmp_channel_matte(), def_cmp_chroma_matte(), def_cmp_color_matte(), def_cmp_color_spill(), def_cmp_colorbalance(), def_cmp_crop(), def_cmp_dblur(), def_cmp_defocus(), def_cmp_diff_matte(), def_cmp_dilate_erode(), def_cmp_distance_matte(), def_cmp_glare(), def_cmp_hue_saturation(), def_cmp_id_mask(), def_cmp_image(), def_cmp_luma_matte(), def_cmp_map_uv(), def_cmp_map_value(), def_cmp_splitviewer(), def_cmp_tonemap(), def_cmp_vector_blur(), def_sh_tex_magic(), def_tex_bricks(), def_whileloop(), OBJECT_OT_vertex_group_blend(), RNA_api_wm(), rna_def_action_actuator(), rna_def_animdata(), rna_def_animviz_ghosts(), rna_def_animviz_paths(), rna_def_armature(), rna_def_armature_actuator(), rna_def_background_image(), rna_def_beztriple(), rna_def_boid_settings(), rna_def_boidrule_average_speed(), rna_def_boidrule_avoid(), rna_def_boidrule_avoid_collision(), rna_def_boidrule_fight(), rna_def_boidrule_follow_leader(), rna_def_boidstate(), rna_def_bone_common(), rna_def_bpoint(), rna_def_brush(), rna_def_brush_texture_slot(), RNA_def_camera(), rna_def_camera_actuator(), rna_def_canvas_surface(), rna_def_cloth_collision_settings(), rna_def_cloth_sim_settings(), rna_def_collision(), rna_def_color_ramp(), rna_def_color_ramp_element(), rna_def_colormapping(), RNA_def_constraint(), rna_def_constraint_action(), rna_def_constraint_actuator(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_kinematic(), rna_def_constraint_location_limit(), rna_def_constraint_minmax(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_rotation_limit(), rna_def_constraint_same_volume(), rna_def_constraint_shrinkwrap(), rna_def_constraint_size_limit(), rna_def_constraint_spline_ik(), rna_def_constraint_stretch_to(), RNA_def_controller(), rna_def_curve(), rna_def_curve_nurb(), rna_def_curvemapping(), rna_def_delay_sensor(), rna_def_dynamic_paint_brush_settings(), rna_def_effector_weight(), rna_def_environment_map(), rna_def_fcurve(), rna_def_field(), rna_def_filter_common(), rna_def_filter_video(), RNA_def_float(), RNA_def_float_array(), RNA_def_float_color(), RNA_def_float_factor(), RNA_def_float_matrix(), RNA_def_float_percentage(), RNA_def_float_rotation(), RNA_def_float_vector(), rna_def_fluid_settings(), rna_def_fluidsim_control(), rna_def_fluidsim_domain(), rna_def_fluidsim_fluid(), rna_def_fluidsim_inflow(), rna_def_fluidsim_obstacle(), rna_def_fluidsim_particle(), rna_def_fluidsim_slip(), rna_def_fmodifier(), rna_def_font(), rna_def_game_softbody(), RNA_def_gameproperty(), rna_def_glow(), rna_def_gpencil_frame(), rna_def_gpencil_layer(), rna_def_gpencil_stroke_point(), rna_def_image(), rna_def_image_paint(), rna_def_imageuser(), RNA_def_int(), RNA_def_int_array(), RNA_def_int_vector(), rna_def_joystick_sensor(), rna_def_key(), rna_def_keyblock(), rna_def_lamp(), rna_def_lamp_falloff(), rna_def_lamp_shadow(), rna_def_lamp_sky_settings(), rna_def_lattice(), rna_def_lighting(), RNA_def_material(), rna_def_material_colors(), rna_def_material_diffuse(), rna_def_material_halo(), rna_def_material_physics(), rna_def_material_raymirror(), rna_def_material_raytra(), rna_def_material_specularity(), rna_def_material_sss(), rna_def_material_strand(), rna_def_material_volume(), rna_def_mcol(), rna_def_mesh(), rna_def_metaball(), rna_def_metaelement(), rna_def_mface(), rna_def_mloopcol(), rna_def_modifier_array(), rna_def_modifier_bevel(), rna_def_modifier_build(), rna_def_modifier_cast(), rna_def_modifier_decimate(), rna_def_modifier_displace(), rna_def_modifier_edgesplit(), rna_def_modifier_explode(), rna_def_modifier_hook(), rna_def_modifier_lattice(), rna_def_modifier_meshdeform(), rna_def_modifier_mirror(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smooth(), rna_def_modifier_solidify(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvg_mask(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), rna_def_modifier_weightvgproximity(), rna_def_movie(), rna_def_movieclip(), rna_def_moviecliUser(), rna_def_mpolygon(), rna_def_mtex_common(), rna_def_multicam(), rna_def_mvert(), rna_def_mvert_group(), rna_def_near_sensor(), rna_def_nlastrip(), rna_def_node(), rna_def_object(), rna_def_object_game_settings(), rna_def_operator_stroke_element(), rna_def_particle_dupliweight(), rna_def_particle_edit(), rna_def_particle_hair_key(), rna_def_particle_settings(), rna_def_particle_system(), rna_def_particle_target(), rna_def_path(), rna_def_pointcache(), rna_def_pose_channel(), rna_def_pose_itasc(), rna_def_radar_sensor(), rna_def_random_actuator(), rna_def_random_sensor(), rna_def_ray_sensor(), RNA_def_scene(), rna_def_scene_ffmpeg_settings(), rna_def_scene_game_data(), rna_def_scene_game_recast_data(), rna_def_scene_image_format_data(), rna_def_scene_render_data(), rna_def_scopes(), rna_def_sculpt(), rna_def_sensor(), rna_def_sequence(), rna_def_shape_action_actuator(), rna_def_smoke_domain_settings(), rna_def_smoke_flow_settings(), rna_def_softbody(), rna_def_sound(), rna_def_sound_actuator(), rna_def_space_clip(), rna_def_space_console(), rna_def_space_node(), rna_def_space_sequencer(), rna_def_space_text(), rna_def_space_view3d(), rna_def_speaker(), rna_def_spot_lamp(), rna_def_steering_actuator(), rna_def_text_marker(), rna_def_textbox(), rna_def_texture(), rna_def_texture_clouds(), rna_def_texture_distorted_noise(), rna_def_texture_image(), rna_def_texture_magic(), rna_def_texture_marble(), rna_def_texture_musgrave(), rna_def_texture_pointdensity(), rna_def_texture_stucci(), rna_def_texture_voronoi(), rna_def_texture_voxeldata(), rna_def_texture_wood(), rna_def_tool_settings(), rna_def_trackingCamera(), rna_def_trackingObject(), rna_def_trackingSettings(), rna_def_trackingStabilization(), rna_def_trackingTrack(), rna_def_transform(), rna_def_twodfilter_actuator(), rna_def_unified_paint_settings(), rna_def_unit_settings(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_system(), rna_def_userdef_theme_space_clip(), rna_def_userdef_theme_space_graph(), rna_def_userdef_theme_space_node(), rna_def_userdef_theme_space_view3d(), rna_def_userdef_theme_spaces_face(), rna_def_userdef_theme_spaces_vertex(), rna_def_userdef_theme_ui_font_style(), rna_def_userdef_theme_ui_wcol(), rna_def_userdef_view(), rna_def_wipe(), RNA_def_world(), rna_def_world_mist(), and rna_def_world_stars().
void RNA_def_property_srna (PropertyRNA * prop, const char * type)
Definition at line 2132 of file rna_define.c.
References PropertyRNA::srna.
Referenced by rna_api_animdata_drivers(), rna_api_animdata_nla_tracks(), rna_api_nlatrack_strips(), rna_def_action_fcurves(), rna_def_action_groups(), rna_def_action_pose_markers(), rna_def_area_spaces(), rna_def_armature_bones(), rna_def_armature_edit_bones(), rna_def_backgroundImages(), rna_def_bone_groups(), rna_def_canvas_surfaces(), rna_def_channeldriver_variables(), rna_def_color_ramp_element_api(), rna_def_composite_nodetree_api(), rna_def_curve(), rna_def_curve_spline_bezpoints(), rna_def_curve_spline_points(), rna_def_curve_splines(), rna_def_fcurve_keyframe_points(), rna_def_fcurve_modifiers(), rna_def_gpencil_layers(), rna_def_group_objects(), rna_def_group_sockets_api(), rna_def_keyingset_paths(), rna_def_keymap_items(), rna_def_loop_colors(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_gpencil(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_libraries(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_movieclips(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_screens(), RNA_def_main_sounds(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_window_managers(), RNA_def_main_worlds(), rna_def_mesh_edges(), rna_def_mesh_loops(), rna_def_mesh_polygons(), rna_def_mesh_tessfaces(), rna_def_mesh_vertices(), rna_def_metaball(), rna_def_metaball_elements(), rna_def_nodetree_link_api(), rna_def_object_constraints(), rna_def_object_modifiers(), rna_def_object_particle_systems(), rna_def_object_vertex_groups(), rna_def_polygon_float_layers(), rna_def_polygon_int_layers(), rna_def_polygon_string_layers(), rna_def_pose_channel_constraints(), rna_def_ptcache_point_caches(), rna_def_render_layers(), rna_def_scene_bases(), rna_def_scene_keying_sets(), rna_def_scene_keying_sets_all(), rna_def_scene_objects(), rna_def_shader_nodetree_api(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), rna_def_texmat_common(), rna_def_texture_nodetree_api(), rna_def_texture_slots(), rna_def_timeline_markers(), rna_def_tracking(), rna_def_trackingMarkers(), rna_def_trackingObject(), rna_def_trackingObjects(), rna_def_userdef_addon_collection(), rna_def_uv_layers(), rna_def_uv_textures(), rna_def_wm_keyconfigs(), and rna_def_wm_keymaps().
void RNA_def_property_string_default (PropertyRNA * prop, const char * value)
Definition at line 1435 of file rna_define.c.
References StringPropertyRNA::defaultvalue, BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, PROP_STRING, and PropertyRNA::type.
Referenced by BPy_StringProperty(), RNA_def_string(), RNA_def_string_dir_path(), RNA_def_string_file_name(), RNA_def_string_file_path(), and RNA_def_string_translate().
void RNA_def_property_string_funcs (PropertyRNA * prop, const char * get, const char * length, const char * set)
Definition at line 2048 of file rna_define.c.
References BlenderDefRNA::error, StringPropertyRNA::get, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, StringPropertyRNA::length, BlenderDefRNA::preprocess, PROP_STRING, StringPropertyRNA::set, and PropertyRNA::type.
Referenced by rna_def_actuator(), rna_def_bone_common(), rna_def_bone_group(), rna_def_canvas_surface(), rna_def_cloth_sim_settings(), rna_def_console_line(), RNA_def_constraint(), RNA_def_controller(), rna_def_drivertarget(), rna_def_enum_property(), rna_def_event(), rna_def_fcurve(), rna_def_fluidsim_domain(), rna_def_font(), rna_def_function(), RNA_def_gameproperty(), rna_def_gpencil_layer(), rna_def_ID(), rna_def_keyblock(), rna_def_keyconfig(), rna_def_keyingset_path(), rna_def_lattice(), rna_def_library(), rna_def_macro_operator(), RNA_def_main(), rna_def_material_slot(), rna_def_mcol(), rna_def_menu(), rna_def_mloopcol(), RNA_def_modifier(), rna_def_modifier_armature(), rna_def_modifier_cast(), rna_def_modifier_curve(), rna_def_modifier_displace(), rna_def_modifier_explode(), rna_def_modifier_generic_map_info(), rna_def_modifier_hook(), rna_def_modifier_lattice(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_multires(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smooth(), rna_def_modifier_solidify(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvg_mask(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), rna_def_modifier_weightvgproximity(), rna_def_movie(), rna_def_mtex(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_nlastrip(), rna_def_node(), rna_def_object(), rna_def_operator(), rna_def_particle_dupliweight(), rna_def_particle_system(), rna_def_particle_target(), rna_def_pose_channel(), rna_def_property(), rna_def_render_layer_common(), rna_def_scene_render_data(), rna_def_sensor(), rna_def_sequence(), rna_def_softbody(), rna_def_sound(), rna_def_string_property(), rna_def_strip_proxy(), rna_def_struct(), rna_def_text(), rna_def_text_line(), rna_def_trackingObject(), rna_def_trackingTrack(), rna_def_vertex_group(), and rna_def_windowmanager().
void RNA_def_property_string_maxlength (PropertyRNA * prop, int maxlength)
Definition at line 1316 of file rna_define.c.
References BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, StringPropertyRNA::maxlength, PROP_STRING, and PropertyRNA::type.
Referenced by BPy_StringProperty(), rna_def_fluidsim_domain(), rna_def_fluidsim_particle(), rna_def_font(), RNA_def_gameproperty(), rna_def_ID(), rna_def_keyingset(), rna_def_keyingset_info(), rna_def_macro_operator(), RNA_def_main(), rna_def_menu(), rna_def_modifier_explode(), rna_def_operator(), rna_def_particle_system(), rna_def_sequence(), RNA_def_string(), RNA_def_string_dir_path(), RNA_def_string_file_name(), RNA_def_string_file_path(), RNA_def_string_translate(), rna_def_trackingObject(), rna_def_trackingTrack(), and rna_def_userdef_system().
void RNA_def_property_string_sdna (PropertyRNA * prop, const char * structname, const char * propname)
Definition at line 1743 of file rna_define.c.
References PropertyRNA::arraydimension, BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, StringPropertyRNA::maxlength, BlenderDefRNA::preprocess, PROP_STRING, rna_def_property_sdna(), PropertyRNA::totarraylength, and PropertyRNA::type.
Referenced by def_cmp_output_file(), def_sh_attribute(), def_sh_geometry(), def_tex_output(), rna_def_action_actuator(), rna_def_actuator_sensor(), rna_def_armature_actuator(), rna_def_armature_sensor(), rna_def_bone_common(), rna_def_brush(), rna_def_canvas_surface(), rna_def_collision_sensor(), rna_def_constraint_action(), rna_def_constraint_actuator(), rna_def_constraint_childof(), rna_def_constraint_damped_track(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_track(), rna_def_constraint_kinematic(), rna_def_constraint_locate_like(), rna_def_constraint_locked_track(), rna_def_constraint_minmax(), rna_def_constraint_object_solver(), rna_def_constraint_pivot(), rna_def_constraint_rotate_like(), rna_def_constraint_size_like(), rna_def_constraint_stretch_to(), rna_def_constraint_track_to(), rna_def_constraint_transform(), rna_def_constraint_transform_like(), rna_def_constrainttarget(), RNA_def_controller(), rna_def_dopesheet(), rna_def_drivertarget(), rna_def_fileselect_params(), rna_def_fluidsim_domain(), rna_def_fluidsim_particle(), rna_def_font(), RNA_def_gameproperty(), rna_def_header(), rna_def_image(), rna_def_keyblock(), rna_def_keyboard_sensor(), rna_def_keyconfig(), rna_def_keyingset(), rna_def_keyingset_info(), rna_def_lattice(), rna_def_library(), rna_def_macro_operator(), rna_def_material_mtex(), rna_def_material_strand(), rna_def_menu(), rna_def_message_actuator(), rna_def_modifier_armature(), rna_def_modifier_cast(), rna_def_modifier_curve(), rna_def_modifier_displace(), rna_def_modifier_explode(), rna_def_modifier_generic_map_info(), rna_def_modifier_hook(), rna_def_modifier_lattice(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_ocean(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smooth(), rna_def_modifier_solidify(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvg_mask(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), rna_def_modifier_weightvgproximity(), rna_def_movieclip(), rna_def_movieclip_proxy(), rna_def_mproperties(), rna_def_near_sensor(), rna_def_node(), rna_def_object(), rna_def_operator(), rna_def_panel(), rna_def_particle_settings_mtex(), rna_def_particle_system(), rna_def_plugin(), rna_def_pointcache(), RNA_def_property(), rna_def_property_actuator(), rna_def_property_sensor(), rna_def_radar_sensor(), rna_def_random_actuator(), rna_def_ray_sensor(), rna_def_render_engine(), rna_def_render_layer_common(), rna_def_render_pass(), RNA_def_scene(), rna_def_scene_render_data(), rna_def_shape_action_actuator(), rna_def_softbody(), rna_def_sound(), rna_def_space_outliner(), rna_def_space_text(), rna_def_space_userpref(), rna_def_space_view3d(), rna_def_strip_element(), rna_def_strip_proxy(), rna_def_texture_voxeldata(), rna_def_tool_settings(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_system(), rna_def_userdef_theme_ui(), and RNA_def_vfont().
void RNA_def_property_struct_runtime (PropertyRNA * prop, StructRNA * type)
Definition at line 1248 of file rna_define.c.
References BlenderDefRNA::error, PropertyRNA::flag, StructRNA::flag, StructRNA::identifier, PropertyRNA::identifier, CollectionPropertyRNA::item_type, BlenderDefRNA::laststruct, BlenderDefRNA::preprocess, PROP_COLLECTION, PROP_ID_REFCOUNT, PROP_POINTER, STRUCT_ID_REFCOUNT, PointerPropertyRNA::type, and PropertyRNA::type.
Referenced by LOGIC_OT_links_cut(), MESH_OT_knife_cut(), NODE_OT_links_cut(), RNA_def_collection_runtime(), and RNA_def_pointer_runtime().
void RNA_def_property_struct_type (PropertyRNA * prop, const char * type)
Definition at line 1220 of file rna_define.c.
References BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, CollectionPropertyRNA::item_type, BlenderDefRNA::laststruct, BlenderDefRNA::preprocess, PROP_COLLECTION, PROP_POINTER, PointerPropertyRNA::type, and PropertyRNA::type.
Referenced by def_cmp_huecorrect(), def_cmp_image(), def_cmp_movieclip(), def_cmp_moviedistortion(), def_cmp_output_file(), def_cmp_render_layers(), def_cmp_stabilize2d(), def_colorramp(), def_forloop(), def_group(), def_rgb_curve(), def_sh_material(), def_sh_tex_environment(), def_sh_tex_image(), def_tex_image(), def_texture(), def_time(), def_vector_curve(), def_whileloop(), rna_api_animdata_nla_tracks(), rna_def_action(), rna_def_action_actuator(), rna_def_action_group(), rna_def_action_pose_markers(), rna_def_animdata(), rna_def_animviz(), rna_def_animviz_motion_path(), rna_def_area(), rna_def_area_spaces(), rna_def_armature(), rna_def_armature_actuator(), rna_def_armature_bones(), rna_def_armature_edit_bones(), rna_def_background_image(), rna_def_boid_settings(), rna_def_boidstate(), rna_def_bone(), rna_def_bone_group(), rna_def_bone_groups(), rna_def_brush(), RNA_def_camera(), rna_def_camera_actuator(), rna_def_canvas_surface(), rna_def_canvas_surfaces(), rna_def_channeldriver(), rna_def_cloth_sim_settings(), rna_def_cmp_output_file_socket(), RNA_def_collection(), rna_def_collision_sensor(), rna_def_color_ramp(), rna_def_colormapping(), rna_def_composite_nodetree(), rna_def_constraint_python(), RNA_def_context(), RNA_def_controller(), rna_def_curve(), rna_def_curve_nurb(), rna_def_curve_splines(), rna_def_curvemap(), rna_def_curvemapping(), rna_def_dopesheet(), rna_def_drivertarget(), rna_def_drivervar(), rna_def_dynamic_paint_brush_settings(), rna_def_dynamic_paint_canvas_settings(), rna_def_edit_bone(), rna_def_edit_object_actuator(), rna_def_editor(), rna_def_enum_property(), rna_def_fcurve(), rna_def_fcurve_modifiers(), rna_def_fluidsim_domain(), rna_def_fmodifier_envelope(), rna_def_font(), rna_def_function(), rna_def_gpencil_data(), rna_def_gpencil_frame(), rna_def_gpencil_layer(), rna_def_gpencil_layers(), rna_def_gpencil_stroke(), RNA_def_group(), rna_def_header(), rna_def_ID_properties(), rna_def_image(), rna_def_key(), rna_def_keyblock(), rna_def_keyconfig(), rna_def_keyingset(), rna_def_keyingset_path(), rna_def_keyingset_paths(), rna_def_lamp_mtex(), rna_def_lattice(), rna_def_latticepoint(), rna_def_library(), rna_def_loop_colors(), rna_def_macro_operator(), RNA_def_main(), RNA_def_material(), rna_def_material_colors(), rna_def_material_mtex(), rna_def_material_slot(), rna_def_mcol(), rna_def_menu(), rna_def_mesh(), rna_def_meta(), rna_def_metaball(), rna_def_mloopcol(), rna_def_mloopuv(), rna_def_modifier_collision(), rna_def_modifier_softbody(), rna_def_modifier_uvproject(), rna_def_movie(), rna_def_movieclip(), rna_def_mproperties(), rna_def_mtex(), rna_def_mtex_common(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_mvert(), rna_def_nlastrip(), rna_def_nlatrack(), rna_def_node(), rna_def_node_link(), rna_def_node_socket(), rna_def_nodetree(), rna_def_object(), rna_def_object_actuator(), rna_def_object_constraints(), rna_def_object_game_settings(), rna_def_object_modifiers(), rna_def_object_particle_systems(), rna_def_object_vertex_groups(), rna_def_operator(), rna_def_operator_type_macro(), rna_def_panel(), rna_def_parent_actuator(), rna_def_particle(), rna_def_particle_edit(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_particle_system(), rna_def_pointcache(), RNA_def_pointer(), rna_def_pointer_property(), rna_def_pose(), rna_def_pose_channel(), rna_def_pose_channel_constraints(), rna_def_property(), rna_def_property_actuator(), rna_def_ray_sensor(), rna_def_render_engine(), rna_def_render_layer(), rna_def_render_layer_common(), rna_def_render_layers(), rna_def_render_result(), RNA_def_rna(), RNA_def_scene(), rna_def_scene_actuator(), rna_def_scene_bases(), rna_def_scene_game_data(), rna_def_scene_keying_sets(), rna_def_scene_keying_sets_all(), rna_def_scene_objects(), rna_def_scene_render_data(), rna_def_scopes(), rna_def_screen(), rna_def_sensor(), rna_def_shader_nodetree(), rna_def_shape_action_actuator(), rna_def_smoke_domain_settings(), rna_def_smoke_flow_settings(), rna_def_softbody(), rna_def_sound(), rna_def_sound_actuator(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_console(), rna_def_space_dopesheet(), rna_def_space_graph(), rna_def_space_image(), rna_def_space_nla(), rna_def_space_sequencer(), rna_def_space_view3d(), rna_def_speaker(), rna_def_steering_actuator(), RNA_def_struct(), rna_def_struct(), rna_def_sun_lamp(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), rna_def_texmat_common(), rna_def_text(), rna_def_texture(), rna_def_texture_environment_map(), rna_def_texture_image(), rna_def_texture_nodetree(), rna_def_texture_ocean(), rna_def_texture_pointdensity(), rna_def_texture_voxeldata(), rna_def_timeline_marker(), rna_def_tool_settings(), rna_def_touch_sensor(), rna_def_tracking(), rna_def_trackingObject(), rna_def_trackingObjects(), rna_def_trackingObjectTracks(), rna_def_trackingReconstruction(), rna_def_trackingStabilization(), rna_def_trackingTrack(), rna_def_trackingTracks(), rna_def_twodfilter_actuator(), RNA_def_userdef(), rna_def_userdef_system(), rna_def_userdef_theme_spaces_list_main(), rna_def_userdef_theme_spaces_main(), rna_def_userdef_theme_ui_style(), rna_def_userdef_themes(), rna_def_uv_layers(), rna_def_uv_textures(), rna_def_window(), rna_def_windowmanager(), rna_def_wm_keyconfigs(), RNA_def_world(), and rna_def_world_mtex().
void RNA_def_property_subtype (PropertyRNA * prop, PropertySubType subtype)
Definition at line 1063 of file rna_define.c.
References PropertyRNA::subtype.
Referenced by MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_uv_sphere_add(), and RNA_api_scene().
void RNA_def_property_translation_context (PropertyRNA * prop, const char * context)
Definition at line 1872 of file rna_define.c.
References PropertyRNA::translation_context.
void RNA_def_property_ui_icon (PropertyRNA * prop, int icon, int consecutive)
Definition at line 1157 of file rna_define.c.
References PropertyRNA::flag, PropertyRNA::icon, and PROP_ICONS_CONSECUTIVE.
Referenced by rna_def_actuator(), rna_def_background_image(), rna_def_brush(), RNA_def_constraint(), RNA_def_controller(), rna_def_dopesheet(), rna_def_fileselect_params(), rna_def_fmodifier(), rna_def_keyblock(), rna_def_keyconfig(), rna_def_mesh(), RNA_def_modifier(), rna_def_object(), rna_def_object_game_settings(), rna_def_pose_channel(), rna_def_render_layer_common(), RNA_def_scene(), rna_def_scene_render_data(), rna_def_sensor(), rna_def_space_image(), rna_def_space_text(), rna_def_space_view3d(), rna_def_tool_settings(), rna_def_trackingSettings(), rna_def_unified_paint_settings(), and rna_def_userdef_edit().
void RNA_def_property_ui_range (PropertyRNA * prop, double min, double max, double step, int precision)
Definition at line 1164 of file rna_define.c.
References BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, BlenderDefRNA::laststruct, FloatPropertyRNA::precision, PROP_FLOAT, PROP_INT, IntPropertyRNA::softmax, FloatPropertyRNA::softmax, FloatPropertyRNA::softmin, IntPropertyRNA::softmin, FloatPropertyRNA::step, IntPropertyRNA::step, and PropertyRNA::type.
Referenced by BPy_FloatProperty(), BPy_FloatVectorProperty(), BPy_IntProperty(), BPy_IntVectorProperty(), def_cmp_colorbalance(), def_cmp_vector_blur(), MESH_OT_inset(), MESH_OT_solidify(), MESH_OT_vert_slide(), rna_def_action_actuator(), rna_def_area_lamp(), rna_def_beztriple(), rna_def_bone(), rna_def_bone_common(), rna_def_bpoint(), rna_def_brush(), RNA_def_camera(), rna_def_camera_actuator(), rna_def_canvas_surface(), rna_def_collision(), rna_def_constraint_actuator(), rna_def_constraint_transform(), rna_def_curve(), rna_def_curve_nurb(), rna_def_dynamic_paint_brush_settings(), rna_def_edit_bone(), rna_def_edit_object_actuator(), rna_def_effector_weight(), rna_def_environment_map(), rna_def_filter_common(), rna_def_filter_video(), RNA_def_float(), RNA_def_float_array(), RNA_def_float_color(), RNA_def_float_factor(), RNA_def_float_matrix(), RNA_def_float_percentage(), RNA_def_float_rotation(), RNA_def_float_vector(), rna_def_fluid_settings(), rna_def_font(), RNA_def_group(), rna_def_image_paint(), RNA_def_int(), RNA_def_int_array(), RNA_def_int_vector(), rna_def_keyblock(), rna_def_lamp(), rna_def_lamp_mtex(), rna_def_lamp_shadow(), rna_def_lamp_sky_settings(), rna_def_lighting(), RNA_def_material(), rna_def_material_mtex(), rna_def_material_physics(), rna_def_material_raymirror(), rna_def_material_raytra(), rna_def_material_sss(), rna_def_material_strand(), rna_def_material_volume(), rna_def_mesh(), rna_def_modifier_array(), rna_def_modifier_bevel(), rna_def_modifier_cast(), rna_def_modifier_decimate(), rna_def_modifier_displace(), rna_def_modifier_edgesplit(), rna_def_modifier_hook(), rna_def_modifier_lattice(), rna_def_modifier_mirror(), rna_def_modifier_ocean(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smooth(), rna_def_modifier_solidify(), rna_def_modifier_subsurf(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvg_mask(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), rna_def_modifier_weightvgproximity(), rna_def_movieclip(), rna_def_movieclip_proxy(), rna_def_mtex(), rna_def_object(), rna_def_object_actuator(), rna_def_object_game_settings(), rna_def_particle_edit(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_pose_channel(), rna_def_random_actuator(), RNA_def_scene(), rna_def_scene_game_data(), rna_def_scene_game_recast_data(), rna_def_scene_render_data(), rna_def_scopes(), rna_def_sculpt(), rna_def_shape_action_actuator(), rna_def_smoke_domain_settings(), rna_def_smoke_flow_settings(), rna_def_softbody(), rna_def_sound_actuator(), rna_def_space_node(), rna_def_space_view3d(), rna_def_speed_control(), rna_def_spot_lamp(), rna_def_steering_actuator(), rna_def_strip_color_balance(), rna_def_strip_crop(), rna_def_strip_proxy(), rna_def_strip_transform(), rna_def_texmapping(), rna_def_texture_clouds(), rna_def_texture_distorted_noise(), rna_def_texture_image(), rna_def_texture_magic(), rna_def_texture_marble(), rna_def_texture_musgrave(), rna_def_texture_stucci(), rna_def_texture_voronoi(), rna_def_texture_wood(), rna_def_tool_settings(), rna_def_trackingCamera(), rna_def_trackingMarker(), rna_def_trackingObject(), rna_def_trackingSettings(), rna_def_trackingTrack(), rna_def_transform(), rna_def_unified_paint_settings(), rna_def_unit_settings(), rna_def_world_mist(), and rna_def_world_mtex().
void RNA_def_property_ui_text (PropertyRNA * prop, const char * name, const char * description)
Definition at line 1149 of file rna_define.c.
References DESCR_CHECK, PropertyRNA::description, PropertyRNA::identifier, PropertyRNA::name, and NULL.
Referenced by api_ui_item_common(), BPy_BoolProperty(), BPy_BoolVectorProperty(), BPy_FloatProperty(), BPy_FloatVectorProperty(), BPy_IntProperty(), BPy_IntVectorProperty(), BPy_StringProperty(), def_cmp_alpha_over(), def_cmp_bilateral_blur(), def_cmp_blur(), def_cmp_channel_matte(), def_cmp_chroma_matte(), def_cmp_color_matte(), def_cmp_color_spill(), def_cmp_colorbalance(), def_cmp_crop(), def_cmp_dblur(), def_cmp_defocus(), def_cmp_diff_matte(), def_cmp_dilate_erode(), def_cmp_distance_matte(), def_cmp_double_edge_mask(), def_cmp_filter(), def_cmp_flip(), def_cmp_glare(), def_cmp_hue_saturation(), def_cmp_huecorrect(), def_cmp_id_mask(), def_cmp_image(), def_cmp_invert(), def_cmp_lensdist(), def_cmp_levels(), def_cmp_luma_matte(), def_cmp_map_uv(), def_cmp_map_value(), def_cmp_movieclip(), def_cmp_moviedistortion(), def_cmp_output_file(), def_cmp_premul_key(), def_cmp_render_layers(), def_cmp_rotate(), def_cmp_scale(), def_cmp_splitviewer(), def_cmp_stabilize2d(), def_cmp_tonemap(), def_cmp_vector_blur(), def_cmp_ycc(), def_cmp_zcombine(), def_colorramp(), def_forloop(), def_glossy(), def_group(), def_math(), def_mix_rgb(), def_rgb_curve(), def_sh_attribute(), def_sh_geometry(), def_sh_mapping(), def_sh_material(), def_sh_tex(), def_sh_tex_environment(), def_sh_tex_gradient(), def_sh_tex_image(), def_sh_tex_magic(), def_sh_tex_musgrave(), def_sh_tex_sky(), def_sh_tex_voronoi(), def_sh_tex_wave(), def_tex_bricks(), def_tex_image(), def_tex_output(), def_texture(), def_time(), def_vector_curve(), def_vector_math(), def_whileloop(), dev_cmd_transform(), OBJECT_OT_vertex_group_blend(), rna_api_animdata_nla_tracks(), RNA_api_keymapitems(), RNA_api_wm(), rna_def_action(), rna_def_action_actuator(), rna_def_action_group(), rna_def_action_pose_markers(), rna_def_actuator(), rna_def_actuator_sensor(), rna_def_animdata(), rna_def_animdata_common(), rna_def_animviz(), rna_def_animviz_common(), rna_def_animviz_ghosts(), rna_def_animviz_motion_path(), rna_def_animviz_motionpath_vert(), rna_def_animviz_paths(), rna_def_area(), rna_def_area_lamp(), rna_def_area_spaces(), rna_def_armature(), rna_def_armature_actuator(), rna_def_armature_bones(), rna_def_armature_edit_bones(), rna_def_armature_sensor(), rna_def_background_image(), rna_def_beztriple(), rna_def_boid_settings(), rna_def_boidrule(), rna_def_boidrule_average_speed(), rna_def_boidrule_avoid(), rna_def_boidrule_avoid_collision(), rna_def_boidrule_fight(), rna_def_boidrule_follow_leader(), rna_def_boidrule_goal(), rna_def_boidstate(), rna_def_bone(), rna_def_bone_common(), rna_def_bone_group(), rna_def_bone_groups(), RNA_def_boolean(), RNA_def_boolean_array(), RNA_def_boolean_layer(), RNA_def_boolean_layer_member(), RNA_def_boolean_vector(), rna_def_bpoint(), rna_def_brush(), rna_def_brush_texture_slot(), RNA_def_camera(), rna_def_camera_actuator(), rna_def_canvas_surface(), rna_def_canvas_surfaces(), rna_def_channeldriver(), rna_def_charinfo(), rna_def_cloth_collision_settings(), rna_def_cloth_sim_settings(), rna_def_cmp_output_file_socket(), RNA_def_collection(), RNA_def_collection_runtime(), rna_def_collision(), rna_def_collision_sensor(), rna_def_color_ramp(), rna_def_color_ramp_element(), rna_def_colormapping(), rna_def_common_keying_flags(), rna_def_composite_nodetree(), rna_def_compositor_node(), rna_def_console_line(), RNA_def_constraint(), rna_def_constraint_action(), rna_def_constraint_actuator(), rna_def_constraint_camera_solver(), rna_def_constraint_childof(), rna_def_constraint_clamp_to(), rna_def_constraint_damped_track(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_follow_track(), rna_def_constraint_kinematic(), rna_def_constraint_locate_like(), rna_def_constraint_location_limit(), rna_def_constraint_locked_track(), rna_def_constraint_minmax(), rna_def_constraint_object_solver(), rna_def_constraint_pivot(), rna_def_constraint_python(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_rotate_like(), rna_def_constraint_rotation_limit(), rna_def_constraint_same_volume(), rna_def_constraint_shrinkwrap(), rna_def_constraint_size_like(), rna_def_constraint_size_limit(), rna_def_constraint_spline_ik(), rna_def_constraint_stretch_to(), rna_def_constraint_track_to(), rna_def_constraint_transform(), rna_def_constraint_transform_like(), rna_def_constrainttarget(), RNA_def_controller(), rna_def_curve(), rna_def_curve_nurb(), rna_def_curve_splines(), rna_def_curvemap(), rna_def_curvemapping(), rna_def_curvemappoint(), rna_def_delay_sensor(), rna_def_dopesheet(), rna_def_drivertarget(), rna_def_drivervar(), rna_def_dupli_object(), rna_def_dynamic_paint_brush_settings(), rna_def_dynamic_paint_canvas_settings(), rna_def_edit_bone(), rna_def_edit_object_actuator(), rna_def_editor(), rna_def_effector_weight(), RNA_def_enum(), RNA_def_enum_flag(), rna_def_enum_property(), rna_def_environment_map(), rna_def_event(), rna_def_fcurve(), rna_def_fcurve_modifiers(), rna_def_field(), rna_def_fileselect_params(), rna_def_filter_common(), rna_def_filter_video(), rna_def_fkeyframe(), RNA_def_float(), RNA_def_float_array(), RNA_def_float_color(), RNA_def_float_factor(), RNA_def_float_matrix(), RNA_def_float_percentage(), RNA_def_float_rotation(), RNA_def_float_vector(), rna_def_fluid_mesh_vertices(), rna_def_fluid_settings(), RNA_def_fluidsim(), rna_def_fluidsim_active(), rna_def_fluidsim_control(), rna_def_fluidsim_domain(), rna_def_fluidsim_fluid(), rna_def_fluidsim_inflow(), rna_def_fluidsim_obstacle(), rna_def_fluidsim_particle(), rna_def_fluidsim_slip(), rna_def_fluidsim_volume(), rna_def_fmodifier(), rna_def_fmodifier_cycles(), rna_def_fmodifier_envelope(), rna_def_fmodifier_envelope_ctrl(), rna_def_fmodifier_function_generator(), rna_def_fmodifier_generator(), rna_def_fmodifier_limits(), rna_def_fmodifier_noise(), rna_def_fmodifier_stepped(), rna_def_font(), rna_def_fpoint(), rna_def_function(), rna_def_game_actuator(), rna_def_game_softbody(), RNA_def_gameproperty(), rna_def_glow(), rna_def_gpencil_data(), rna_def_gpencil_frame(), rna_def_gpencil_layer(), rna_def_gpencil_layers(), rna_def_gpencil_stroke(), rna_def_gpencil_stroke_point(), RNA_def_group(), rna_def_header(), rna_def_histogram(), rna_def_ID(), rna_def_ID_properties(), rna_def_image(), rna_def_image_paint(), rna_def_imageuser(), rna_def_input(), RNA_def_int(), RNA_def_int_array(), RNA_def_int_vector(), rna_def_joystick_sensor(), rna_def_key(), rna_def_keyblock(), rna_def_keyboard_sensor(), rna_def_keyconfig(), rna_def_keydata(), rna_def_keyingset(), rna_def_keyingset_info(), rna_def_keyingset_path(), rna_def_keyingset_paths(), rna_def_lamp(), rna_def_lamp_falloff(), rna_def_lamp_mtex(), rna_def_lamp_shadow(), rna_def_lamp_sky_settings(), rna_def_lattice(), rna_def_latticepoint(), rna_def_library(), rna_def_lighting(), rna_def_loop_colors(), rna_def_macro_operator(), RNA_def_main(), RNA_def_material(), rna_def_material_colors(), rna_def_material_diffuse(), rna_def_material_gamesettings(), rna_def_material_halo(), rna_def_material_mtex(), rna_def_material_physics(), rna_def_material_raymirror(), rna_def_material_raytra(), rna_def_material_slot(), rna_def_material_specularity(), rna_def_material_sss(), rna_def_material_strand(), rna_def_material_volume(), rna_def_mcol(), rna_def_medge(), rna_def_menu(), rna_def_mesh(), rna_def_mesh_polygons(), rna_def_mesh_tessfaces(), rna_def_message_actuator(), rna_def_message_sensor(), rna_def_meta(), rna_def_metaball(), rna_def_metaball_elements(), rna_def_metaelement(), rna_def_mface(), rna_def_mloop(), rna_def_mloopcol(), rna_def_mloopuv(), RNA_def_modifier(), rna_def_modifier_armature(), rna_def_modifier_array(), rna_def_modifier_bevel(), rna_def_modifier_boolean(), rna_def_modifier_build(), rna_def_modifier_cast(), rna_def_modifier_cloth(), rna_def_modifier_collision(), rna_def_modifier_curve(), rna_def_modifier_decimate(), rna_def_modifier_displace(), rna_def_modifier_dynamic_paint(), rna_def_modifier_edgesplit(), rna_def_modifier_explode(), rna_def_modifier_fluidsim(), rna_def_modifier_generic_map_info(), rna_def_modifier_hook(), rna_def_modifier_lattice(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_mirror(), rna_def_modifier_multires(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_particlesystem(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smoke(), rna_def_modifier_smooth(), rna_def_modifier_softbody(), rna_def_modifier_solidify(), rna_def_modifier_subsurf(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvg_mask(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), rna_def_modifier_weightvgproximity(), rna_def_motionpath_common(), rna_def_mouse_sensor(), rna_def_movie(), rna_def_movieclip(), rna_def_movieclip_proxy(), rna_def_moviecliUser(), rna_def_mpolygon(), rna_def_mproperties(), rna_def_msticky(), rna_def_mtex(), rna_def_mtex_common(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_multicam(), rna_def_mvert(), rna_def_mvert_group(), rna_def_near_sensor(), rna_def_nlastrip(), rna_def_nlatrack(), rna_def_node(), rna_def_node_link(), rna_def_node_socket(), rna_def_node_socket_subtype(), rna_def_nodetree(), rna_def_number_property(), rna_def_nurbs(), rna_def_object(), rna_def_object_actuator(), rna_def_object_base(), rna_def_object_constraints(), rna_def_object_game_settings(), rna_def_object_modifiers(), rna_def_object_particle_systems(), rna_def_object_vertex_groups(), rna_def_operator(), rna_def_operator_filelist_element(), rna_def_operator_stroke_element(), rna_def_operator_type_macro(), rna_def_operator_utils(), RNA_def_packedfile(), rna_def_paint(), rna_def_panel(), rna_def_parent_actuator(), rna_def_particle(), rna_def_particle_dupliweight(), rna_def_particle_edit(), rna_def_particle_hair_key(), rna_def_particle_key(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_particle_system(), rna_def_particle_target(), rna_def_path(), rna_def_plugin(), rna_def_pointcache(), RNA_def_pointer(), rna_def_pointer_property(), RNA_def_pointer_runtime(), rna_def_pose(), rna_def_pose_channel(), rna_def_pose_channel_constraints(), rna_def_pose_ikparam(), rna_def_pose_itasc(), rna_def_property(), rna_def_property_actuator(), rna_def_property_sensor(), rna_def_property_subdivision_common(), rna_def_proxy(), rna_def_ptcache_point_caches(), rna_def_radar_sensor(), rna_def_random_actuator(), rna_def_random_sensor(), rna_def_ray_sensor(), rna_def_reconstructedCamera(), rna_def_region(), rna_def_render_layer_common(), rna_def_render_layers(), RNA_def_rna(), RNA_def_scene(), rna_def_scene(), rna_def_scene_actuator(), rna_def_scene_bases(), rna_def_scene_ffmpeg_settings(), rna_def_scene_game_data(), rna_def_scene_game_recast_data(), rna_def_scene_image_format_data(), rna_def_scene_keying_sets(), rna_def_scene_keying_sets_all(), rna_def_scene_objects(), rna_def_scene_render_data(), rna_def_scopes(), rna_def_screen(), rna_def_sculpt(), rna_def_selected_uv_element(), rna_def_sensor(), rna_def_sequence(), rna_def_shader_node(), rna_def_shader_nodetree(), rna_def_shape_action_actuator(), rna_def_smoke_domain_settings(), rna_def_smoke_flow_settings(), rna_def_softbody(), rna_def_solid_color(), rna_def_sound(), rna_def_sound_actuator(), rna_def_space(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_console(), rna_def_space_dopesheet(), rna_def_space_filebrowser(), rna_def_space_graph(), rna_def_space_image(), rna_def_space_image_uv(), rna_def_space_info(), rna_def_space_logic(), rna_def_space_nla(), rna_def_space_node(), rna_def_space_outliner(), rna_def_space_sequencer(), rna_def_space_text(), rna_def_space_time(), rna_def_space_userpref(), rna_def_space_view3d(), rna_def_speaker(), rna_def_speed_control(), rna_def_spot_lamp(), rna_def_state_actuator(), rna_def_steering_actuator(), RNA_def_string(), RNA_def_string_dir_path(), RNA_def_string_file_name(), RNA_def_string_file_path(), rna_def_string_property(), RNA_def_string_translate(), rna_def_strip_color_balance(), rna_def_strip_crop(), rna_def_strip_element(), rna_def_strip_proxy(), rna_def_strip_transform(), RNA_def_struct(), rna_def_struct(), rna_def_sun_lamp(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), rna_def_texmapping(), rna_def_texmat_common(), rna_def_text(), rna_def_text_line(), rna_def_text_marker(), rna_def_textbox(), rna_def_texture(), rna_def_texture_blend(), rna_def_texture_clouds(), rna_def_texture_distorted_noise(), rna_def_texture_environment_map(), rna_def_texture_image(), rna_def_texture_magic(), rna_def_texture_marble(), rna_def_texture_musgrave(), rna_def_texture_node(), rna_def_texture_nodetree(), rna_def_texture_ocean(), rna_def_texture_pointdensity(), rna_def_texture_stucci(), rna_def_texture_voronoi(), rna_def_texture_voxeldata(), rna_def_texture_wood(), rna_def_timeline_marker(), rna_def_timer(), rna_def_tool_settings(), rna_def_touch_sensor(), rna_def_tracking(), rna_def_trackingCamera(), rna_def_trackingMarker(), rna_def_trackingObject(), rna_def_trackingObjects(), rna_def_trackingObjectTracks(), rna_def_trackingReconstruction(), rna_def_trackingSettings(), rna_def_trackingStabilization(), rna_def_trackingTrack(), rna_def_trackingTracks(), rna_def_transform(), rna_def_transform_orientation(), rna_def_twodfilter_actuator(), rna_def_ui_layout(), rna_def_unified_paint_settings(), rna_def_unit_settings(), RNA_def_userdef(), rna_def_userdef_addon(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_solidlight(), rna_def_userdef_system(), rna_def_userdef_theme_colorset(), rna_def_userdef_theme_space_action(), rna_def_userdef_theme_space_buts(), rna_def_userdef_theme_space_clip(), rna_def_userdef_theme_space_console(), rna_def_userdef_theme_space_file(), rna_def_userdef_theme_space_generic(), rna_def_userdef_theme_space_graph(), rna_def_userdef_theme_space_image(), rna_def_userdef_theme_space_list_generic(), rna_def_userdef_theme_space_logic(), rna_def_userdef_theme_space_nla(), rna_def_userdef_theme_space_node(), rna_def_userdef_theme_space_outliner(), rna_def_userdef_theme_space_seq(), rna_def_userdef_theme_space_text(), rna_def_userdef_theme_space_time(), rna_def_userdef_theme_space_view3d(), rna_def_userdef_theme_spaces_curves(), rna_def_userdef_theme_spaces_edge(), rna_def_userdef_theme_spaces_face(), rna_def_userdef_theme_spaces_list_main(), rna_def_userdef_theme_spaces_main(), rna_def_userdef_theme_spaces_vertex(), rna_def_userdef_theme_ui(), rna_def_userdef_theme_ui_font_style(), rna_def_userdef_theme_ui_panel(), rna_def_userdef_theme_ui_style(), rna_def_userdef_theme_ui_wcol(), rna_def_userdef_theme_ui_wcol_state(), rna_def_userdef_themes(), rna_def_userdef_view(), rna_def_uv_layers(), rna_def_uv_textures(), rna_def_vertex_group(), rna_def_vertex_paint(), RNA_def_vfont(), rna_def_visibility_actuator(), rna_def_window(), rna_def_windowmanager(), rna_def_wipe(), rna_def_wm_keyconfigs(), RNA_def_world(), rna_def_world_mist(), rna_def_world_mtex(), rna_def_world_stars(), TRANSFORM_OT_select_orientation(), and Transform_Properties().
void RNA_def_property_update (PropertyRNA * prop, int noteflag, const char * updatefunc)
Definition at line 1899 of file rna_define.c.
References PropertyRNA::noteflag, BlenderDefRNA::preprocess, and PropertyRNA::update.
Referenced by def_cmp_alpha_over(), def_cmp_bilateral_blur(), def_cmp_blur(), def_cmp_channel_matte(), def_cmp_chroma_matte(), def_cmp_color_matte(), def_cmp_color_spill(), def_cmp_colorbalance(), def_cmp_crop(), def_cmp_dblur(), def_cmp_defocus(), def_cmp_diff_matte(), def_cmp_dilate_erode(), def_cmp_distance_matte(), def_cmp_double_edge_mask(), def_cmp_filter(), def_cmp_flip(), def_cmp_glare(), def_cmp_hue_saturation(), def_cmp_huecorrect(), def_cmp_id_mask(), def_cmp_image(), def_cmp_invert(), def_cmp_lensdist(), def_cmp_levels(), def_cmp_luma_matte(), def_cmp_map_uv(), def_cmp_map_value(), def_cmp_movieclip(), def_cmp_moviedistortion(), def_cmp_output_file(), def_cmp_premul_key(), def_cmp_render_layers(), def_cmp_rotate(), def_cmp_scale(), def_cmp_splitviewer(), def_cmp_stabilize2d(), def_cmp_tonemap(), def_cmp_vector_blur(), def_cmp_ycc(), def_cmp_zcombine(), def_colorramp(), def_forloop(), def_glossy(), def_group(), def_math(), def_mix_rgb(), def_rgb_curve(), def_sh_attribute(), def_sh_geometry(), def_sh_mapping(), def_sh_material(), def_sh_tex_environment(), def_sh_tex_gradient(), def_sh_tex_image(), def_sh_tex_magic(), def_sh_tex_musgrave(), def_sh_tex_sky(), def_sh_tex_voronoi(), def_sh_tex_wave(), def_tex_bricks(), def_tex_image(), def_tex_output(), def_texture(), def_time(), def_vector_curve(), def_vector_math(), def_whileloop(), dev_cmd_transform(), RNA_api_actuator(), rna_api_animdata_nla_tracks(), RNA_api_controller(), RNA_api_sensor(), rna_def_action_actuator(), rna_def_action_group(), rna_def_actuator(), rna_def_actuator_sensor(), rna_def_animdata(), rna_def_animviz_ghosts(), rna_def_animviz_paths(), rna_def_area(), rna_def_area_lamp(), rna_def_armature(), rna_def_armature_actuator(), rna_def_armature_sensor(), rna_def_background_image(), rna_def_beztriple(), rna_def_boid_settings(), rna_def_boidrule(), rna_def_boidrule_average_speed(), rna_def_boidrule_avoid(), rna_def_boidrule_avoid_collision(), rna_def_boidrule_fight(), rna_def_boidrule_follow_leader(), rna_def_boidrule_goal(), rna_def_boidstate(), rna_def_bone(), rna_def_bone_common(), rna_def_bone_group(), rna_def_bone_groups(), rna_def_bpoint(), rna_def_brush(), rna_def_brush_texture_slot(), RNA_def_camera(), rna_def_camera_actuator(), rna_def_canvas_surface(), rna_def_canvas_surfaces(), rna_def_channeldriver(), rna_def_charinfo(), rna_def_cloth_collision_settings(), rna_def_cloth_sim_settings(), rna_def_cmp_output_file_socket(), rna_def_collision(), rna_def_collision_sensor(), rna_def_color_ramp(), rna_def_color_ramp_element(), rna_def_colormapping(), rna_def_console_line(), RNA_def_constraint(), rna_def_constraint_action(), rna_def_constraint_actuator(), rna_def_constraint_camera_solver(), rna_def_constraint_childof(), rna_def_constraint_clamp_to(), rna_def_constraint_damped_track(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_follow_track(), rna_def_constraint_kinematic(), rna_def_constraint_locate_like(), rna_def_constraint_location_limit(), rna_def_constraint_locked_track(), rna_def_constraint_minmax(), rna_def_constraint_object_solver(), rna_def_constraint_pivot(), rna_def_constraint_python(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_rotate_like(), rna_def_constraint_rotation_limit(), rna_def_constraint_same_volume(), rna_def_constraint_shrinkwrap(), rna_def_constraint_size_like(), rna_def_constraint_size_limit(), rna_def_constraint_spline_ik(), rna_def_constraint_stretch_to(), rna_def_constraint_track_to(), rna_def_constraint_transform(), rna_def_constraint_transform_like(), rna_def_constrainttarget(), RNA_def_controller(), rna_def_curve(), rna_def_curve_nurb(), rna_def_curve_splines(), rna_def_delay_sensor(), rna_def_dopesheet(), rna_def_drivertarget(), rna_def_drivervar(), rna_def_dynamic_paint_brush_settings(), rna_def_edit_bone(), rna_def_edit_object_actuator(), rna_def_editor(), rna_def_effector_weight(), rna_def_environment_map(), rna_def_fcurve(), rna_def_field(), rna_def_fileselect_params(), rna_def_filter_common(), rna_def_filter_video(), rna_def_fkeyframe(), rna_def_fluid_settings(), RNA_def_fluidsim(), rna_def_fluidsim_control(), rna_def_fluidsim_domain(), rna_def_fluidsim_particle(), rna_def_fmodifier(), rna_def_fmodifier_cycles(), rna_def_fmodifier_envelope(), rna_def_fmodifier_envelope_ctrl(), rna_def_fmodifier_function_generator(), rna_def_fmodifier_generator(), rna_def_fmodifier_limits(), rna_def_fmodifier_noise(), rna_def_fmodifier_stepped(), rna_def_font(), rna_def_fpoint(), rna_def_game_actuator(), RNA_def_gameproperty(), rna_def_glow(), rna_def_gpencil_layer(), rna_def_gpencil_stroke_point(), rna_def_ID(), rna_def_image(), rna_def_imageuser(), rna_def_input(), rna_def_joystick_sensor(), rna_def_key(), rna_def_keyblock(), rna_def_keyboard_sensor(), rna_def_keyconfig(), rna_def_keydata(), rna_def_keyingset(), rna_def_keyingset_path(), rna_def_lamp(), rna_def_lamp_falloff(), rna_def_lamp_mtex(), rna_def_lamp_shadow(), rna_def_lamp_sky_settings(), rna_def_lattice(), rna_def_latticepoint(), rna_def_lighting(), rna_def_loop_colors(), RNA_def_material(), rna_def_material_colors(), rna_def_material_diffuse(), rna_def_material_gamesettings(), rna_def_material_halo(), rna_def_material_mtex(), rna_def_material_raymirror(), rna_def_material_raytra(), rna_def_material_slot(), rna_def_material_specularity(), rna_def_material_sss(), rna_def_material_strand(), rna_def_material_volume(), rna_def_mcol(), rna_def_medge(), rna_def_mesh(), rna_def_message_actuator(), rna_def_message_sensor(), rna_def_metaball(), rna_def_metaelement(), rna_def_mface(), rna_def_mloopcol(), rna_def_mloopuv(), RNA_def_modifier(), rna_def_modifier_armature(), rna_def_modifier_array(), rna_def_modifier_bevel(), rna_def_modifier_boolean(), rna_def_modifier_build(), rna_def_modifier_cast(), rna_def_modifier_curve(), rna_def_modifier_decimate(), rna_def_modifier_displace(), rna_def_modifier_edgesplit(), rna_def_modifier_explode(), rna_def_modifier_generic_map_info(), rna_def_modifier_hook(), rna_def_modifier_lattice(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_mirror(), rna_def_modifier_multires(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smoke(), rna_def_modifier_smooth(), rna_def_modifier_solidify(), rna_def_modifier_subsurf(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvg_mask(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), rna_def_modifier_weightvgproximity(), rna_def_mouse_sensor(), rna_def_movie(), rna_def_movieclip(), rna_def_movieclip_proxy(), rna_def_moviecliUser(), rna_def_mpolygon(), rna_def_mproperties(), rna_def_msticky(), rna_def_mtex(), rna_def_mtex_common(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_multicam(), rna_def_mvert(), rna_def_mvert_group(), rna_def_near_sensor(), rna_def_nlastrip(), rna_def_nlatrack(), rna_def_node(), rna_def_node_socket(), rna_def_node_socket_subtype(), rna_def_nodetree(), rna_def_nurbs(), rna_def_object(), rna_def_object_actuator(), rna_def_object_base(), rna_def_object_game_settings(), rna_def_object_particle_systems(), rna_def_object_vertex_groups(), rna_def_paint(), rna_def_parent_actuator(), rna_def_particle_dupliweight(), rna_def_particle_edit(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_particle_system(), rna_def_particle_target(), rna_def_path(), rna_def_plugin(), rna_def_pointcache(), rna_def_pose(), rna_def_pose_channel(), rna_def_pose_itasc(), rna_def_property_actuator(), rna_def_property_sensor(), rna_def_property_subdivision_common(), rna_def_proxy(), rna_def_ptcache_point_caches(), rna_def_radar_sensor(), rna_def_random_actuator(), rna_def_random_sensor(), rna_def_ray_sensor(), rna_def_render_layer_common(), rna_def_render_layers(), RNA_def_scene(), rna_def_scene(), rna_def_scene_actuator(), rna_def_scene_bases(), rna_def_scene_ffmpeg_settings(), rna_def_scene_game_data(), rna_def_scene_game_recast_data(), rna_def_scene_image_format_data(), rna_def_scene_keying_sets(), rna_def_scene_keying_sets_all(), rna_def_scene_objects(), rna_def_scene_render_data(), rna_def_scopes(), rna_def_screen(), rna_def_sculpt(), rna_def_sensor(), rna_def_sequence(), rna_def_shape_action_actuator(), rna_def_smoke_domain_settings(), rna_def_smoke_flow_settings(), rna_def_softbody(), rna_def_solid_color(), rna_def_sound(), rna_def_sound_actuator(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_console(), rna_def_space_dopesheet(), rna_def_space_graph(), rna_def_space_image(), rna_def_space_image_uv(), rna_def_space_info(), rna_def_space_logic(), rna_def_space_nla(), rna_def_space_node(), rna_def_space_outliner(), rna_def_space_sequencer(), rna_def_space_text(), rna_def_space_time(), rna_def_space_view3d(), rna_def_speed_control(), rna_def_spot_lamp(), rna_def_state_actuator(), rna_def_steering_actuator(), rna_def_strip_color_balance(), rna_def_strip_crop(), rna_def_strip_element(), rna_def_strip_proxy(), rna_def_strip_transform(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), rna_def_texmapping(), rna_def_texmat_common(), rna_def_text_line(), rna_def_textbox(), rna_def_texture(), rna_def_texture_blend(), rna_def_texture_clouds(), rna_def_texture_distorted_noise(), rna_def_texture_environment_map(), rna_def_texture_image(), rna_def_texture_magic(), rna_def_texture_marble(), rna_def_texture_musgrave(), rna_def_texture_ocean(), rna_def_texture_pointdensity(), rna_def_texture_stucci(), rna_def_texture_voronoi(), rna_def_texture_voxeldata(), rna_def_texture_wood(), rna_def_timeline_marker(), rna_def_tool_settings(), rna_def_touch_sensor(), rna_def_tracking(), rna_def_trackingCamera(), rna_def_trackingMarker(), rna_def_trackingObject(), rna_def_trackingSettings(), rna_def_trackingStabilization(), rna_def_trackingTrack(), rna_def_transform(), rna_def_transform_orientation(), rna_def_twodfilter_actuator(), rna_def_unit_settings(), RNA_def_userdef(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_solidlight(), rna_def_userdef_system(), rna_def_userdef_theme_colorset(), rna_def_userdef_theme_space_action(), rna_def_userdef_theme_space_buts(), rna_def_userdef_theme_space_clip(), rna_def_userdef_theme_space_console(), rna_def_userdef_theme_space_file(), rna_def_userdef_theme_space_generic(), rna_def_userdef_theme_space_graph(), rna_def_userdef_theme_space_image(), rna_def_userdef_theme_space_list_generic(), rna_def_userdef_theme_space_logic(), rna_def_userdef_theme_space_nla(), rna_def_userdef_theme_space_node(), rna_def_userdef_theme_space_outliner(), rna_def_userdef_theme_space_seq(), rna_def_userdef_theme_space_text(), rna_def_userdef_theme_space_time(), rna_def_userdef_theme_space_view3d(), rna_def_userdef_theme_spaces_curves(), rna_def_userdef_theme_spaces_edge(), rna_def_userdef_theme_spaces_face(), rna_def_userdef_theme_spaces_vertex(), rna_def_userdef_theme_ui(), rna_def_userdef_theme_ui_font_style(), rna_def_userdef_theme_ui_panel(), rna_def_userdef_theme_ui_style(), rna_def_userdef_theme_ui_wcol(), rna_def_userdef_theme_ui_wcol_state(), rna_def_userdef_view(), rna_def_uv_layers(), rna_def_uv_textures(), rna_def_vertex_group(), rna_def_visibility_actuator(), rna_def_window(), rna_def_wipe(), RNA_def_world(), rna_def_world_mist(), rna_def_world_mtex(), and rna_def_world_stars().
void RNA_def_property_update_runtime (PropertyRNA * prop, void * func)
Definition at line 1910 of file rna_define.c.
References PropertyRNA::update.
Referenced by bpy_prop_callback_assign(), and ED_object_add_generic_props().
void RNA_def_py_data (PropertyRNA * prop, void * py_data)
Definition at line 2137 of file rna_define.c.
References PropertyRNA::py_data.
Referenced by bpy_prop_callback_assign().
PropertyRNA* RNA_def_string (StructOrFunctionRNA * cont, const char * identifier, const char * default_value, int maxlen, const char * ui_name, const char * ui_description)
Definition at line 2262 of file rna_define.c.
References PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_string_default(), RNA_def_property_string_maxlength(), and RNA_def_property_ui_text().
Referenced by api_ui_item_op(), api_ui_item_rna_common(), ARMATURE_OT_bone_primitive_add(), CONSOLE_OT_history_append(), CONSOLE_OT_insert(), CONSOLE_OT_scrollback_append(), ED_operatormacros_object(), ED_OT_undo_push(), edit_actuator_properties(), edit_constraint_properties(), edit_controller_properties(), edit_modifier_properties(), edit_sensor_properties(), FILE_OT_select_bookmark(), FONT_OT_text_insert(), GROUP_OT_create(), IMAGE_OT_new(), IMAGE_OT_unpack(), LOGIC_OT_actuator_add(), LOGIC_OT_controller_add(), LOGIC_OT_sensor_add(), MARKER_OT_rename(), MESH_OT_drop_named_image(), NODE_OT_add_file(), NODE_OT_group_socket_add(), NODE_OT_new_node_tree(), NODE_OT_output_file_add_socket(), OBJECT_OT_add_named(), OBJECT_OT_drop_named_material(), OBJECT_OT_game_property_new(), OBJECT_OT_select_same_group(), OUTLINER_OT_parent_clear(), OUTLINER_OT_parent_drop(), POSELIB_OT_pose_add(), POSELIB_OT_pose_rename(), RENDER_OT_render(), RNA_api_keyconfigs(), RNA_api_keymapitems(), RNA_api_keymaps(), RNA_api_macro(), RNA_api_mesh(), rna_api_nlatrack_strips(), RNA_api_object(), RNA_api_operator(), RNA_api_scene(), RNA_api_text(), RNA_api_ui_layout(), rna_def_action_fcurves(), rna_def_action_groups(), rna_def_action_pose_markers(), rna_def_area(), rna_def_armature_edit_bones(), rna_def_group_sockets_api(), rna_def_keyingset_paths(), rna_def_loop_colors(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_worlds(), rna_def_object_modifiers(), rna_def_object_vertex_groups(), rna_def_polygon_float_layers(), rna_def_polygon_int_layers(), rna_def_polygon_string_layers(), rna_def_render_engine(), rna_def_render_layer(), rna_def_render_layers(), RNA_def_scene(), rna_def_scene_keying_sets(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), rna_def_timeline_markers(), rna_def_trackingObjects(), rna_def_uv_textures(), SOUND_OT_unpack(), TEXT_OT_insert(), TRANSFORM_OT_create_orientation(), VIEW3D_OT_background_image_add(), WM_OT_call_menu(), and WM_OT_radial_control().
PropertyRNA* RNA_def_string_dir_path (StructOrFunctionRNA * cont, const char * identifier, const char * default_value, int maxlen, const char * ui_name, const char * ui_description)
Definition at line 2290 of file rna_define.c.
References PROP_DIRPATH, PROP_STRING, RNA_def_property(), RNA_def_property_string_default(), RNA_def_property_string_maxlength(), and RNA_def_property_ui_text().
Referenced by FILE_OT_directory_new(), and WM_operator_properties_filesel().
PropertyRNA* RNA_def_string_file_name (StructOrFunctionRNA * cont, const char * identifier, const char * default_value, int maxlen, const char * ui_name, const char * ui_description)
Definition at line 2304 of file rna_define.c.
References PROP_FILENAME, PROP_STRING, RNA_def_property(), RNA_def_property_string_default(), RNA_def_property_string_maxlength(), and RNA_def_property_ui_text().
Referenced by PAINT_OT_image_from_view(), RNA_api_environment_map(), rna_def_render_result(), and WM_operator_properties_filesel().
PropertyRNA* RNA_def_string_file_path (StructOrFunctionRNA * cont, const char * identifier, const char * default_value, int maxlen, const char * ui_name, const char * ui_description)
Definition at line 2276 of file rna_define.c.
References PROP_FILEPATH, PROP_STRING, RNA_def_property(), RNA_def_property_string_default(), RNA_def_property_string_maxlength(), and RNA_def_property_ui_text().
Referenced by RNA_api_image(), RNA_api_main(), RNA_api_scene_render(), RNA_def_main_fonts(), RNA_def_main_images(), RNA_def_main_movieclips(), RNA_def_main_texts(), SCRIPT_OT_python_file_run(), and WM_operator_properties_filesel().
PropertyRNA* RNA_def_string_translate (StructOrFunctionRNA * cont, const char * identifier, const char * default_value, int maxlen, const char * ui_name, const char * ui_description)
Definition at line 2318 of file rna_define.c.
References PROP_STRING, PROP_TRANSLATE, RNA_def_property(), RNA_def_property_string_default(), RNA_def_property_string_maxlength(), and RNA_def_property_ui_text().
Referenced by api_ui_item_common(), and RNA_api_ui_layout().
StructRNA* RNA_def_struct (BlenderRNA * brna, const char * identifier, const char * from)
Definition at line 605 of file rna_define.c.
References StructRNA::base, CollectionPropertyRNA::begin, StructRNA::cont, StructRNA::description, StructDefRNA::dnafromname, BlenderDefRNA::error, error(), ListBase::first, StructRNA::flag, StructRNA::functions, PointerPropertyRNA::get, CollectionPropertyRNA::get, StructRNA::icon, StructRNA::identifier, CollectionPropertyRNA::item_type, StructRNA::iteratorproperty, ListBase::last, BlenderDefRNA::laststruct, MEM_callocN(), StructRNA::name, StructRNA::nameproperty, CollectionPropertyRNA::next, ContainerRNA::next, NULL, BlenderDefRNA::preprocess, PROP_BUILTIN, PROP_COLLECTION, PROP_HIDDEN, PROP_NONE, PROP_POINTER, ContainerRNA::properties, ContainerRNA::prophash, StructRNA::py_type, rna_addtail(), rna_builtin_properties_begin(), rna_builtin_properties_get(), rna_builtin_properties_next(), rna_builtin_type_get(), RNA_def_property(), RNA_def_property_collection_funcs(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct_sdna(), rna_find_def_struct(), RNA_Property, RNA_Struct, rna_validate_identifier(), StructDefRNA::srna, STRUCT_RUNTIME, STRUCT_UNDO, BlenderDefRNA::structs, BlenderRNA::structs, and PointerPropertyRNA::type.
Referenced by def_node(), rna_api_animdata_drivers(), rna_api_animdata_nla_tracks(), rna_api_nlatrack_strips(), rna_def_action(), rna_def_action_actuator(), rna_def_action_fcurves(), rna_def_action_group(), rna_def_action_groups(), rna_def_action_pose_markers(), rna_def_actuator(), rna_def_actuator_sensor(), rna_def_adjustment(), rna_def_always_sensor(), rna_def_animdata(), rna_def_animviz(), rna_def_animviz_ghosts(), rna_def_animviz_motion_path(), rna_def_animviz_motionpath_vert(), rna_def_animviz_paths(), rna_def_area(), rna_def_area_lamp(), rna_def_area_spaces(), rna_def_armature(), rna_def_armature_actuator(), rna_def_armature_bones(), rna_def_armature_edit_bones(), rna_def_armature_sensor(), rna_def_background_image(), rna_def_backgroundImages(), rna_def_beztriple(), rna_def_boid_settings(), rna_def_boidrule(), rna_def_boidrule_average_speed(), rna_def_boidrule_avoid(), rna_def_boidrule_avoid_collision(), rna_def_boidrule_fight(), rna_def_boidrule_follow_leader(), rna_def_boidrule_goal(), rna_def_boidstate(), rna_def_bone(), rna_def_bone_group(), rna_def_bone_groups(), rna_def_bpoint(), rna_def_brush(), rna_def_brush_texture_slot(), RNA_def_camera(), rna_def_camera_actuator(), rna_def_canvas_surface(), rna_def_canvas_surfaces(), rna_def_channeldriver(), rna_def_channeldriver_variables(), rna_def_charinfo(), rna_def_child_particle(), rna_def_cloth_collision_settings(), rna_def_cloth_sim_settings(), rna_def_cmp_output_file_socket(), rna_def_collision(), rna_def_collision_sensor(), rna_def_color_ramp(), rna_def_color_ramp_element(), rna_def_color_ramp_element_api(), rna_def_colormapping(), rna_def_composite_nodetree(), rna_def_composite_nodetree_api(), rna_def_compositor_node(), rna_def_console_line(), RNA_def_constraint(), rna_def_constraint_action(), rna_def_constraint_actuator(), rna_def_constraint_camera_solver(), rna_def_constraint_childof(), rna_def_constraint_clamp_to(), rna_def_constraint_damped_track(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_follow_track(), rna_def_constraint_kinematic(), rna_def_constraint_locate_like(), rna_def_constraint_location_limit(), rna_def_constraint_locked_track(), rna_def_constraint_minmax(), rna_def_constraint_object_solver(), rna_def_constraint_pivot(), rna_def_constraint_python(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_rotate_like(), rna_def_constraint_rotation_limit(), rna_def_constraint_same_volume(), rna_def_constraint_shrinkwrap(), rna_def_constraint_size_like(), rna_def_constraint_size_limit(), rna_def_constraint_spline_ik(), rna_def_constraint_stretch_to(), rna_def_constraint_track_to(), rna_def_constraint_transform(), rna_def_constraint_transform_like(), rna_def_constrainttarget(), RNA_def_context(), RNA_def_controller(), rna_def_curve(), rna_def_curve_nurb(), rna_def_curve_spline_bezpoints(), rna_def_curve_spline_points(), rna_def_curve_splines(), rna_def_curvemap(), rna_def_curvemapping(), rna_def_curvemappoint(), rna_def_delay_sensor(), rna_def_dopesheet(), rna_def_drivertarget(), rna_def_drivervar(), rna_def_dupli_object(), rna_def_dynamic_paint_brush_settings(), rna_def_dynamic_paint_canvas_settings(), rna_def_edit_bone(), rna_def_edit_object_actuator(), rna_def_editor(), rna_def_effect(), rna_def_effector_weight(), rna_def_enum_property(), rna_def_environment_map(), rna_def_event(), rna_def_fcurve(), rna_def_fcurve_keyframe_points(), rna_def_fcurve_modifiers(), rna_def_field(), rna_def_fileselect_params(), rna_def_fkeyframe(), rna_def_fluid_mesh_vertices(), rna_def_fluid_settings(), RNA_def_fluidsim(), rna_def_fluidsim_control(), rna_def_fluidsim_domain(), rna_def_fluidsim_fluid(), rna_def_fluidsim_inflow(), rna_def_fluidsim_obstacle(), rna_def_fluidsim_outflow(), rna_def_fluidsim_particle(), rna_def_fmodifier(), rna_def_fmodifier_cycles(), rna_def_fmodifier_envelope(), rna_def_fmodifier_envelope_ctrl(), rna_def_fmodifier_function_generator(), rna_def_fmodifier_generator(), rna_def_fmodifier_limits(), rna_def_fmodifier_noise(), rna_def_fmodifier_python(), rna_def_fmodifier_stepped(), rna_def_fpoint(), rna_def_function(), rna_def_game_actuator(), rna_def_game_softbody(), RNA_def_gameproperty(), rna_def_glow(), rna_def_gpencil_data(), rna_def_gpencil_frame(), rna_def_gpencil_layer(), rna_def_gpencil_layers(), rna_def_gpencil_stroke(), rna_def_gpencil_stroke_point(), RNA_def_group(), rna_def_group_objects(), rna_def_group_sockets_api(), rna_def_header(), rna_def_hemi_lamp(), rna_def_histogram(), RNA_def_ID(), rna_def_ID(), rna_def_ID_materials(), rna_def_ID_properties(), rna_def_image(), rna_def_image_paint(), rna_def_imageuser(), rna_def_joystick_sensor(), rna_def_key(), rna_def_keyblock(), rna_def_keyboard_sensor(), rna_def_keyconfig(), rna_def_keydata(), rna_def_keyingset(), rna_def_keyingset_info(), rna_def_keyingset_path(), rna_def_keyingset_paths(), rna_def_keymap_items(), rna_def_lamp(), rna_def_lamp_mtex(), rna_def_lamp_sky_settings(), rna_def_lattice(), rna_def_latticepoint(), rna_def_library(), rna_def_lighting(), rna_def_loop_colors(), rna_def_macro_operator(), RNA_def_main(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_gpencil(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_libraries(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_movieclips(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_screens(), RNA_def_main_sounds(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_window_managers(), RNA_def_main_worlds(), RNA_def_material(), rna_def_material_gamesettings(), rna_def_material_halo(), rna_def_material_mtex(), rna_def_material_physics(), rna_def_material_raymirror(), rna_def_material_raytra(), rna_def_material_slot(), rna_def_material_sss(), rna_def_material_strand(), rna_def_material_volume(), rna_def_mcol(), rna_def_medge(), rna_def_menu(), rna_def_mesh(), rna_def_mesh_edges(), rna_def_mesh_loops(), rna_def_mesh_polygons(), rna_def_mesh_tessfaces(), rna_def_mesh_vertices(), rna_def_message_actuator(), rna_def_message_sensor(), rna_def_meta(), rna_def_metaball(), rna_def_metaball_elements(), rna_def_metaelement(), rna_def_mface(), rna_def_mloop(), rna_def_mloopcol(), rna_def_mloopuv(), RNA_def_modifier(), rna_def_modifier_armature(), rna_def_modifier_array(), rna_def_modifier_bevel(), rna_def_modifier_boolean(), rna_def_modifier_build(), rna_def_modifier_cast(), rna_def_modifier_cloth(), rna_def_modifier_collision(), rna_def_modifier_curve(), rna_def_modifier_decimate(), rna_def_modifier_displace(), rna_def_modifier_dynamic_paint(), rna_def_modifier_edgesplit(), rna_def_modifier_explode(), rna_def_modifier_fluidsim(), rna_def_modifier_hook(), rna_def_modifier_lattice(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_mirror(), rna_def_modifier_multires(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_particlesystem(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smoke(), rna_def_modifier_smooth(), rna_def_modifier_softbody(), rna_def_modifier_solidify(), rna_def_modifier_subsurf(), rna_def_modifier_surface(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), rna_def_modifier_weightvgproximity(), rna_def_mouse_sensor(), rna_def_movie(), rna_def_movieclip(), rna_def_movieclip_proxy(), rna_def_movieClipScopes(), rna_def_moviecliUser(), rna_def_mpolygon(), rna_def_mproperties(), rna_def_msticky(), rna_def_mtex(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_multicam(), rna_def_mvert(), rna_def_mvert_group(), rna_def_near_sensor(), rna_def_nlastrip(), rna_def_nlatrack(), rna_def_node(), rna_def_node_link(), rna_def_node_socket(), rna_def_node_socket_subtype(), rna_def_nodetree(), rna_def_nodetree_link_api(), rna_def_object(), rna_def_object_actuator(), rna_def_object_base(), rna_def_object_constraints(), rna_def_object_game_settings(), rna_def_object_modifiers(), rna_def_object_particle_systems(), rna_def_object_vertex_groups(), rna_def_operator(), rna_def_operator_filelist_element(), rna_def_operator_stroke_element(), rna_def_operator_type_macro(), rna_def_operator_utils(), RNA_def_packedfile(), rna_def_paint(), rna_def_panel(), rna_def_parent_actuator(), rna_def_particle(), rna_def_particle_dupliweight(), rna_def_particle_edit(), rna_def_particle_hair_key(), rna_def_particle_key(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_particle_system(), rna_def_particle_target(), rna_def_plugin(), rna_def_point_lamp(), rna_def_pointcache(), rna_def_polygon_float_layers(), rna_def_polygon_int_layers(), rna_def_polygon_string_layers(), rna_def_pose(), rna_def_pose_channel(), rna_def_pose_channel_constraints(), rna_def_pose_ikparam(), rna_def_pose_itasc(), rna_def_property(), rna_def_property_actuator(), rna_def_property_sensor(), rna_def_ptcache_point_caches(), rna_def_radar_sensor(), rna_def_random_actuator(), rna_def_random_sensor(), rna_def_ray_sensor(), rna_def_reconstructedCamera(), rna_def_region(), rna_def_render_engine(), rna_def_render_layer(), rna_def_render_layers(), rna_def_render_pass(), rna_def_render_result(), RNA_def_rna(), rna_def_scene(), RNA_def_scene(), rna_def_scene_actuator(), rna_def_scene_bases(), rna_def_scene_ffmpeg_settings(), rna_def_scene_game_data(), rna_def_scene_game_recast_data(), rna_def_scene_image_format_data(), rna_def_scene_keying_sets(), rna_def_scene_keying_sets_all(), rna_def_scene_objects(), rna_def_scene_render_data(), rna_def_scene_render_layer(), rna_def_scopes(), rna_def_screen(), rna_def_sculpt(), rna_def_sculpt_capabilities(), rna_def_selected_uv_element(), rna_def_sensor(), rna_def_sequence(), rna_def_shader_node(), rna_def_shader_nodetree(), rna_def_shader_nodetree_api(), rna_def_shape_action_actuator(), rna_def_smoke_coll_settings(), rna_def_smoke_domain_settings(), rna_def_smoke_flow_settings(), rna_def_softbody(), rna_def_solid_color(), rna_def_sound(), rna_def_sound_actuator(), rna_def_space(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_console(), rna_def_space_dopesheet(), rna_def_space_filebrowser(), rna_def_space_graph(), rna_def_space_image(), rna_def_space_image_uv(), rna_def_space_info(), rna_def_space_logic(), rna_def_space_nla(), rna_def_space_node(), rna_def_space_outliner(), rna_def_space_sequencer(), rna_def_space_text(), rna_def_space_time(), rna_def_space_userpref(), rna_def_space_view3d(), rna_def_speaker(), rna_def_speed_control(), rna_def_spot_lamp(), rna_def_state_actuator(), rna_def_steering_actuator(), rna_def_strip_color_balance(), rna_def_strip_crop(), rna_def_strip_element(), rna_def_strip_proxy(), rna_def_strip_transform(), rna_def_struct(), rna_def_sun_lamp(), rna_def_surface(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), RNA_def_test(), rna_def_texmapping(), rna_def_text(), rna_def_text_line(), rna_def_text_marker(), rna_def_textbox(), rna_def_texture(), rna_def_texture_blend(), rna_def_texture_clouds(), rna_def_texture_distorted_noise(), rna_def_texture_environment_map(), rna_def_texture_image(), rna_def_texture_magic(), rna_def_texture_marble(), rna_def_texture_musgrave(), rna_def_texture_node(), rna_def_texture_nodetree(), rna_def_texture_nodetree_api(), rna_def_texture_noise(), rna_def_texture_ocean(), rna_def_texture_plugin(), rna_def_texture_pointdensity(), rna_def_texture_slots(), rna_def_texture_stucci(), rna_def_texture_voronoi(), rna_def_texture_voxeldata(), rna_def_texture_wood(), rna_def_timeline_marker(), rna_def_timeline_markers(), rna_def_timer(), rna_def_tool_settings(), rna_def_touch_sensor(), rna_def_tracking(), rna_def_trackingCamera(), rna_def_trackingMarker(), rna_def_trackingMarkers(), rna_def_trackingObject(), rna_def_trackingObjects(), rna_def_trackingObjectTracks(), rna_def_trackingReconstruction(), rna_def_trackingSettings(), rna_def_trackingStabilization(), rna_def_trackingTrack(), rna_def_trackingTracks(), rna_def_transform(), rna_def_transform_orientation(), rna_def_twodfilter_actuator(), rna_def_ui_layout(), rna_def_unified_paint_settings(), rna_def_unit_settings(), RNA_def_userdef(), rna_def_userdef_addon(), rna_def_userdef_addon_collection(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_solidlight(), rna_def_userdef_system(), rna_def_userdef_theme_colorset(), rna_def_userdef_theme_space_action(), rna_def_userdef_theme_space_buts(), rna_def_userdef_theme_space_clip(), rna_def_userdef_theme_space_console(), rna_def_userdef_theme_space_file(), rna_def_userdef_theme_space_generic(), rna_def_userdef_theme_space_graph(), rna_def_userdef_theme_space_image(), rna_def_userdef_theme_space_info(), rna_def_userdef_theme_space_list_generic(), rna_def_userdef_theme_space_logic(), rna_def_userdef_theme_space_nla(), rna_def_userdef_theme_space_node(), rna_def_userdef_theme_space_outliner(), rna_def_userdef_theme_space_seq(), rna_def_userdef_theme_space_text(), rna_def_userdef_theme_space_time(), rna_def_userdef_theme_space_userpref(), rna_def_userdef_theme_space_view3d(), rna_def_userdef_theme_ui(), rna_def_userdef_theme_ui_font_style(), rna_def_userdef_theme_ui_panel(), rna_def_userdef_theme_ui_style(), rna_def_userdef_theme_ui_wcol(), rna_def_userdef_theme_ui_wcol_state(), rna_def_userdef_themes(), rna_def_userdef_view(), rna_def_uv_layers(), rna_def_uv_sculpt(), rna_def_uv_textures(), rna_def_vertex_group(), rna_def_vertex_paint(), RNA_def_vfont(), rna_def_visibility_actuator(), rna_def_window(), rna_def_windowmanager(), rna_def_wipe(), rna_def_wm_keyconfigs(), rna_def_wm_keymaps(), RNA_def_world(), rna_def_world_mist(), rna_def_world_mtex(), rna_def_world_stars(), WM_operatortype_append(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), and WM_operatortype_append_ptr().
void RNA_def_struct_clear_flag (StructRNA * srna, int flag)
Definition at line 804 of file rna_define.c.
References StructRNA::flag.
Referenced by RNA_def_group(), rna_def_object(), RNA_def_scene(), rna_def_text(), RNA_def_userdef(), rna_def_userdef_addon(), rna_def_userdef_addon_collection(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_solidlight(), rna_def_userdef_system(), rna_def_userdef_theme_colorset(), rna_def_userdef_theme_space_action(), rna_def_userdef_theme_space_buts(), rna_def_userdef_theme_space_clip(), rna_def_userdef_theme_space_console(), rna_def_userdef_theme_space_file(), rna_def_userdef_theme_space_graph(), rna_def_userdef_theme_space_image(), rna_def_userdef_theme_space_info(), rna_def_userdef_theme_space_logic(), rna_def_userdef_theme_space_nla(), rna_def_userdef_theme_space_node(), rna_def_userdef_theme_space_outliner(), rna_def_userdef_theme_space_seq(), rna_def_userdef_theme_space_text(), rna_def_userdef_theme_space_time(), rna_def_userdef_theme_space_userpref(), rna_def_userdef_theme_space_view3d(), rna_def_userdef_theme_ui(), rna_def_userdef_theme_ui_font_style(), rna_def_userdef_theme_ui_panel(), rna_def_userdef_theme_ui_style(), rna_def_userdef_theme_ui_wcol(), rna_def_userdef_theme_ui_wcol_state(), rna_def_userdef_themes(), rna_def_userdef_view(), and rna_def_windowmanager().
void RNA_def_struct_duplicate_pointers (StructRNA * srna)
void RNA_def_struct_flag (StructRNA * srna, int flag)
Definition at line 799 of file rna_define.c.
References StructRNA::flag.
Referenced by rna_def_ID().
void RNA_def_struct_free_pointers (StructRNA * srna)
Referenced by RNA_struct_free().
void RNA_def_struct_identifier (StructRNA * srna, const char * identifier)
Definition at line 851 of file rna_define.c.
References StructRNA::identifier, and BlenderDefRNA::preprocess.
Referenced by operator_properties_init(), WM_operatortype_append(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), and WM_operatortype_append_ptr().
void RNA_def_struct_idprops_func (StructRNA * srna, const char * refine)
Definition at line 819 of file rna_define.c.
References StructRNA::idproperties, and BlenderDefRNA::preprocess.
Referenced by rna_def_bone(), rna_def_edit_bone(), rna_def_ID(), rna_def_ID_properties(), rna_def_operator(), and rna_def_pose_channel().
void RNA_def_struct_name_property (StructRNA * srna, PropertyRNA * prop)
Definition at line 772 of file rna_define.c.
References BlenderDefRNA::error, StructRNA::identifier, PropertyRNA::identifier, StructRNA::nameproperty, PROP_STRING, and PropertyRNA::type.
Referenced by rna_def_action_group(), rna_def_actuator(), rna_def_boidrule(), rna_def_boidstate(), rna_def_bone_common(), rna_def_bone_group(), rna_def_canvas_surface(), RNA_def_constraint(), RNA_def_controller(), rna_def_drivervar(), rna_def_enum_property(), rna_def_fmodifier(), rna_def_function(), RNA_def_gameproperty(), rna_def_gpencil_layer(), rna_def_ID(), rna_def_ID_properties(), rna_def_keyblock(), rna_def_keyconfig(), rna_def_keyingset(), rna_def_keyingset_info(), rna_def_keyingset_path(), rna_def_macro_operator(), rna_def_material_slot(), rna_def_mcol(), rna_def_mloopcol(), RNA_def_modifier(), rna_def_mproperties(), rna_def_mtex(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_nlastrip(), rna_def_nlatrack(), rna_def_node(), rna_def_node_socket(), rna_def_operator(), rna_def_particle_dupliweight(), rna_def_particle_system(), rna_def_particle_target(), rna_def_pointcache(), rna_def_pose_channel(), rna_def_property(), rna_def_render_layer_common(), rna_def_render_pass(), rna_def_sensor(), rna_def_sequence(), rna_def_struct(), rna_def_timeline_marker(), rna_def_trackingObject(), rna_def_trackingTrack(), rna_def_transform_orientation(), rna_def_userdef_addon(), rna_def_userdef_themes(), and rna_def_vertex_group().
void RNA_def_struct_nested (BlenderRNA * brna, StructRNA * srna, const char * structname)
Definition at line 782 of file rna_define.c.
References StructRNA::cont, BlenderDefRNA::error, ListBase::first, StructRNA::identifier, StructRNA::nested, ContainerRNA::next, and BlenderRNA::structs.
Referenced by rna_def_animviz_ghosts(), rna_def_animviz_paths(), rna_def_lamp_sky_settings(), rna_def_lighting(), rna_def_material_gamesettings(), rna_def_material_halo(), rna_def_material_physics(), rna_def_material_raymirror(), rna_def_material_raytra(), rna_def_material_sss(), rna_def_material_strand(), rna_def_material_volume(), rna_def_object_game_settings(), rna_def_scene_game_data(), rna_def_scene_game_recast_data(), rna_def_scene_image_format_data(), rna_def_scene_render_data(), rna_def_sculpt_capabilities(), rna_def_space_image_uv(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_system(), rna_def_userdef_view(), rna_def_world_mist(), and rna_def_world_stars().
void RNA_def_struct_path_func (StructRNA * srna, const char * path)
Definition at line 841 of file rna_define.c.
References StructRNA::path, and BlenderDefRNA::preprocess.
Referenced by rna_def_beztriple(), rna_def_boid_settings(), rna_def_boidrule(), rna_def_bone(), rna_def_bpoint(), rna_def_canvas_surface(), rna_def_cloth_collision_settings(), rna_def_cloth_sim_settings(), rna_def_cmp_output_file_socket(), rna_def_collision(), rna_def_color_ramp(), rna_def_color_ramp_element(), rna_def_color_ramp_element_api(), RNA_def_constraint(), rna_def_curve_nurb(), rna_def_dynamic_paint_brush_settings(), rna_def_dynamic_paint_canvas_settings(), rna_def_effector_weight(), rna_def_field(), rna_def_fluid_settings(), RNA_def_fluidsim(), rna_def_imageuser(), rna_def_keyblock(), rna_def_keydata(), rna_def_latticepoint(), rna_def_mcol(), rna_def_medge(), rna_def_mface(), rna_def_mloop(), rna_def_mloopcol(), rna_def_mloopuv(), RNA_def_modifier(), rna_def_mpolygon(), rna_def_mproperties(), rna_def_msticky(), rna_def_mtex(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_mvert(), rna_def_mvert_group(), rna_def_nlastrip(), rna_def_node(), rna_def_node_socket(), rna_def_node_socket_subtype(), rna_def_particle_system(), rna_def_pose_channel(), rna_def_scene_render_data(), rna_def_sequence(), rna_def_smoke_coll_settings(), rna_def_smoke_domain_settings(), rna_def_smoke_flow_settings(), rna_def_softbody(), rna_def_strip_color_balance(), rna_def_strip_crop(), rna_def_strip_transform(), rna_def_textbox(), rna_def_texture_ocean(), rna_def_texture_pointdensity(), rna_def_texture_voxeldata(), rna_def_tracking(), rna_def_trackingCamera(), rna_def_trackingStabilization(), and rna_def_trackingTrack().
void RNA_def_struct_refine_func (StructRNA * srna, const char * refine)
Definition at line 809 of file rna_define.c.
References BlenderDefRNA::preprocess, and StructRNA::refine.
Referenced by rna_def_actuator(), rna_def_boidrule(), RNA_def_constraint(), RNA_def_controller(), rna_def_curve(), RNA_def_fluidsim(), rna_def_fmodifier(), RNA_def_gameproperty(), rna_def_header(), rna_def_ID(), rna_def_ID_properties(), rna_def_keyingset_info(), rna_def_lamp(), rna_def_macro_operator(), rna_def_menu(), RNA_def_modifier(), rna_def_node(), rna_def_node_socket(), rna_def_nodetree(), rna_def_operator(), rna_def_panel(), rna_def_pose_ikparam(), rna_def_property(), rna_def_render_engine(), rna_def_sensor(), rna_def_sequence(), rna_def_space(), and rna_def_texture().
void RNA_def_struct_register_funcs (StructRNA * srna, const char * reg, const char * unreg, const char * instance)
Definition at line 829 of file rna_define.c.
References StructRNA::instance, BlenderDefRNA::preprocess, StructRNA::reg, and StructRNA::unreg.
Referenced by rna_def_header(), rna_def_ID_properties(), rna_def_keyingset_info(), rna_def_macro_operator(), rna_def_menu(), rna_def_operator(), rna_def_panel(), and rna_def_render_engine().
void RNA_def_struct_sdna (StructRNA * srna, const char * structname)
Definition at line 722 of file rna_define.c.
References DNA_struct_find_nr(), StructDefRNA::dnaname, BlenderDefRNA::error, BlenderDefRNA::preprocess, rna_find_def_struct(), BlenderDefRNA::sdna, and BlenderDefRNA::silent.
Referenced by def_node(), rna_api_animdata_drivers(), rna_api_animdata_nla_tracks(), rna_api_nlatrack_strips(), rna_def_action(), rna_def_action_fcurves(), rna_def_action_group(), rna_def_action_groups(), rna_def_action_pose_markers(), rna_def_actuator(), rna_def_adjustment(), rna_def_animviz(), rna_def_animviz_ghosts(), rna_def_animviz_motion_path(), rna_def_animviz_motionpath_vert(), rna_def_animviz_paths(), rna_def_area(), rna_def_area_lamp(), rna_def_area_spaces(), rna_def_armature(), rna_def_armature_bones(), rna_def_armature_edit_bones(), rna_def_background_image(), rna_def_backgroundImages(), rna_def_beztriple(), rna_def_boidrule_avoid(), rna_def_boidrule_goal(), rna_def_bone_group(), rna_def_bone_groups(), rna_def_bpoint(), rna_def_brush_texture_slot(), rna_def_canvas_surface(), rna_def_canvas_surfaces(), rna_def_channeldriver(), rna_def_channeldriver_variables(), rna_def_charinfo(), rna_def_cloth_collision_settings(), rna_def_cloth_sim_settings(), rna_def_cmp_output_file_socket(), rna_def_collision(), rna_def_color_ramp(), rna_def_color_ramp_element(), rna_def_color_ramp_element_api(), rna_def_composite_nodetree(), rna_def_composite_nodetree_api(), rna_def_compositor_node(), RNA_def_constraint(), rna_def_constrainttarget(), RNA_def_context(), RNA_def_controller(), rna_def_curve_nurb(), rna_def_curve_spline_bezpoints(), rna_def_curve_spline_points(), rna_def_curve_splines(), rna_def_dopesheet(), rna_def_drivervar(), rna_def_dupli_object(), rna_def_dynamic_paint_brush_settings(), rna_def_dynamic_paint_canvas_settings(), rna_def_edit_bone(), rna_def_editor(), rna_def_effect(), rna_def_effector_weight(), rna_def_environment_map(), rna_def_event(), rna_def_fcurve_keyframe_points(), rna_def_fcurve_modifiers(), rna_def_field(), rna_def_fkeyframe(), rna_def_fluid_mesh_vertices(), RNA_def_fluidsim(), rna_def_fluidsim_control(), rna_def_fluidsim_domain(), rna_def_fluidsim_fluid(), rna_def_fluidsim_inflow(), rna_def_fluidsim_obstacle(), rna_def_fluidsim_outflow(), rna_def_fluidsim_particle(), rna_def_fmodifier_envelope_ctrl(), rna_def_fpoint(), rna_def_game_softbody(), RNA_def_gameproperty(), rna_def_gpencil_data(), rna_def_gpencil_frame(), rna_def_gpencil_layer(), rna_def_gpencil_layers(), rna_def_gpencil_stroke(), rna_def_gpencil_stroke_point(), rna_def_group_objects(), rna_def_group_sockets_api(), rna_def_header(), rna_def_hemi_lamp(), rna_def_ID_materials(), rna_def_ID_properties(), rna_def_image(), rna_def_image_paint(), rna_def_keyblock(), rna_def_keyconfig(), rna_def_keyingset_info(), rna_def_keyingset_path(), rna_def_keyingset_paths(), rna_def_keymap_items(), rna_def_lamp_mtex(), rna_def_lamp_sky_settings(), rna_def_latticepoint(), rna_def_lighting(), rna_def_loop_colors(), rna_def_macro_operator(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_gpencil(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_libraries(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_movieclips(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_screens(), RNA_def_main_sounds(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_window_managers(), RNA_def_main_worlds(), rna_def_material_gamesettings(), rna_def_material_halo(), rna_def_material_mtex(), rna_def_material_physics(), rna_def_material_raymirror(), rna_def_material_raytra(), rna_def_material_sss(), rna_def_material_strand(), rna_def_material_volume(), rna_def_mcol(), rna_def_medge(), rna_def_menu(), rna_def_mesh_edges(), rna_def_mesh_loops(), rna_def_mesh_polygons(), rna_def_mesh_tessfaces(), rna_def_mesh_vertices(), rna_def_meta(), rna_def_metaball_elements(), rna_def_metaelement(), rna_def_mface(), rna_def_mloop(), rna_def_mloopcol(), rna_def_mloopuv(), RNA_def_modifier(), rna_def_modifier_armature(), rna_def_modifier_array(), rna_def_modifier_bevel(), rna_def_modifier_boolean(), rna_def_modifier_build(), rna_def_modifier_cast(), rna_def_modifier_cloth(), rna_def_modifier_collision(), rna_def_modifier_curve(), rna_def_modifier_decimate(), rna_def_modifier_displace(), rna_def_modifier_dynamic_paint(), rna_def_modifier_edgesplit(), rna_def_modifier_explode(), rna_def_modifier_fluidsim(), rna_def_modifier_hook(), rna_def_modifier_lattice(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_mirror(), rna_def_modifier_multires(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_particlesystem(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smoke(), rna_def_modifier_smooth(), rna_def_modifier_softbody(), rna_def_modifier_solidify(), rna_def_modifier_subsurf(), rna_def_modifier_surface(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), rna_def_modifier_weightvgproximity(), rna_def_movie(), rna_def_movieclip(), rna_def_movieclip_proxy(), rna_def_mpolygon(), rna_def_mproperties(), rna_def_msticky(), rna_def_mtex(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_multicam(), rna_def_mvert(), rna_def_mvert_group(), rna_def_node(), rna_def_node_link(), rna_def_node_socket(), rna_def_node_socket_subtype(), rna_def_nodetree(), rna_def_nodetree_link_api(), rna_def_object_base(), rna_def_object_constraints(), rna_def_object_game_settings(), rna_def_object_modifiers(), rna_def_object_particle_systems(), rna_def_object_vertex_groups(), rna_def_operator(), rna_def_operator_type_macro(), rna_def_panel(), rna_def_particle(), rna_def_particle_dupliweight(), rna_def_particle_edit(), rna_def_particle_hair_key(), rna_def_particle_settings_mtex(), rna_def_point_lamp(), rna_def_polygon_float_layers(), rna_def_polygon_int_layers(), rna_def_polygon_string_layers(), rna_def_pose(), rna_def_pose_channel(), rna_def_pose_channel_constraints(), rna_def_pose_ikparam(), rna_def_pose_itasc(), rna_def_ptcache_point_caches(), rna_def_region(), rna_def_render_engine(), rna_def_render_layers(), rna_def_scene(), rna_def_scene_bases(), rna_def_scene_ffmpeg_settings(), rna_def_scene_game_data(), rna_def_scene_game_recast_data(), rna_def_scene_image_format_data(), rna_def_scene_keying_sets(), rna_def_scene_keying_sets_all(), rna_def_scene_objects(), rna_def_scene_render_data(), rna_def_screen(), rna_def_sculpt_capabilities(), rna_def_sensor(), rna_def_shader_node(), rna_def_shader_nodetree(), rna_def_shader_nodetree_api(), rna_def_smoke_coll_settings(), rna_def_smoke_domain_settings(), rna_def_smoke_flow_settings(), rna_def_softbody(), rna_def_sound(), rna_def_space(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_console(), rna_def_space_dopesheet(), rna_def_space_filebrowser(), rna_def_space_graph(), rna_def_space_image(), rna_def_space_image_uv(), rna_def_space_info(), rna_def_space_logic(), rna_def_space_nla(), rna_def_space_node(), rna_def_space_outliner(), rna_def_space_sequencer(), rna_def_space_text(), rna_def_space_time(), rna_def_space_userpref(), rna_def_space_view3d(), rna_def_spot_lamp(), rna_def_strip_color_balance(), rna_def_strip_crop(), rna_def_strip_element(), rna_def_strip_proxy(), rna_def_strip_transform(), RNA_def_struct(), rna_def_sun_lamp(), rna_def_surface(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), RNA_def_test(), rna_def_text(), rna_def_texture(), rna_def_texture_blend(), rna_def_texture_clouds(), rna_def_texture_distorted_noise(), rna_def_texture_environment_map(), rna_def_texture_image(), rna_def_texture_magic(), rna_def_texture_marble(), rna_def_texture_musgrave(), rna_def_texture_node(), rna_def_texture_nodetree(), rna_def_texture_nodetree_api(), rna_def_texture_noise(), rna_def_texture_ocean(), rna_def_texture_plugin(), rna_def_texture_pointdensity(), rna_def_texture_slots(), rna_def_texture_stucci(), rna_def_texture_voronoi(), rna_def_texture_voxeldata(), rna_def_texture_wood(), rna_def_timeline_marker(), rna_def_timeline_markers(), rna_def_timer(), rna_def_trackingMarkers(), rna_def_trackingObjects(), rna_def_trackingObjectTracks(), rna_def_trackingTracks(), rna_def_ui_layout(), RNA_def_userdef(), rna_def_userdef_addon(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_solidlight(), rna_def_userdef_system(), rna_def_userdef_theme_colorset(), rna_def_userdef_theme_space_action(), rna_def_userdef_theme_space_buts(), rna_def_userdef_theme_space_clip(), rna_def_userdef_theme_space_console(), rna_def_userdef_theme_space_file(), rna_def_userdef_theme_space_generic(), rna_def_userdef_theme_space_graph(), rna_def_userdef_theme_space_image(), rna_def_userdef_theme_space_info(), rna_def_userdef_theme_space_list_generic(), rna_def_userdef_theme_space_logic(), rna_def_userdef_theme_space_nla(), rna_def_userdef_theme_space_node(), rna_def_userdef_theme_space_outliner(), rna_def_userdef_theme_space_seq(), rna_def_userdef_theme_space_text(), rna_def_userdef_theme_space_time(), rna_def_userdef_theme_space_userpref(), rna_def_userdef_theme_space_view3d(), rna_def_userdef_theme_ui(), rna_def_userdef_theme_ui_font_style(), rna_def_userdef_theme_ui_panel(), rna_def_userdef_theme_ui_style(), rna_def_userdef_theme_ui_wcol(), rna_def_userdef_theme_ui_wcol_state(), rna_def_userdef_themes(), rna_def_userdef_view(), rna_def_uv_layers(), rna_def_uv_textures(), rna_def_vertex_group(), rna_def_vertex_paint(), RNA_def_vfont(), rna_def_window(), rna_def_windowmanager(), rna_def_wm_keyconfigs(), rna_def_wm_keymaps(), rna_def_world_mist(), rna_def_world_mtex(), and rna_def_world_stars().
void RNA_def_struct_sdna_from (StructRNA * srna, const char * structname, const char * propname)
Definition at line 744 of file rna_define.c.
References DNA_struct_find_nr(), StructDefRNA::dnafromprop, StructDefRNA::dnaname, BlenderDefRNA::error, BlenderDefRNA::preprocess, rna_find_def_struct(), BlenderDefRNA::sdna, and BlenderDefRNA::silent.
Referenced by def_cmp_alpha_over(), def_cmp_bilateral_blur(), def_cmp_blur(), def_cmp_channel_matte(), def_cmp_chroma_matte(), def_cmp_color_matte(), def_cmp_color_spill(), def_cmp_colorbalance(), def_cmp_crop(), def_cmp_dblur(), def_cmp_defocus(), def_cmp_diff_matte(), def_cmp_distance_matte(), def_cmp_glare(), def_cmp_hue_saturation(), def_cmp_image(), def_cmp_lensdist(), def_cmp_luma_matte(), def_cmp_map_value(), def_cmp_movieclip(), def_cmp_output_file(), def_cmp_tonemap(), def_cmp_vector_blur(), def_sh_attribute(), def_sh_geometry(), def_sh_mapping(), def_sh_tex_checker(), def_sh_tex_environment(), def_sh_tex_gradient(), def_sh_tex_image(), def_sh_tex_magic(), def_sh_tex_musgrave(), def_sh_tex_noise(), def_sh_tex_sky(), def_sh_tex_voronoi(), def_sh_tex_wave(), def_tex_output(), rna_def_action_actuator(), rna_def_actuator_sensor(), rna_def_armature_actuator(), rna_def_armature_sensor(), rna_def_camera_actuator(), rna_def_cmp_output_file_socket(), rna_def_collision_sensor(), rna_def_constraint_action(), rna_def_constraint_actuator(), rna_def_constraint_camera_solver(), rna_def_constraint_childof(), rna_def_constraint_clamp_to(), rna_def_constraint_damped_track(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_follow_track(), rna_def_constraint_kinematic(), rna_def_constraint_locate_like(), rna_def_constraint_location_limit(), rna_def_constraint_locked_track(), rna_def_constraint_minmax(), rna_def_constraint_object_solver(), rna_def_constraint_pivot(), rna_def_constraint_python(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_rotate_like(), rna_def_constraint_rotation_limit(), rna_def_constraint_same_volume(), rna_def_constraint_shrinkwrap(), rna_def_constraint_size_like(), rna_def_constraint_size_limit(), rna_def_constraint_spline_ik(), rna_def_constraint_stretch_to(), rna_def_constraint_track_to(), rna_def_constraint_transform(), rna_def_constraint_transform_like(), RNA_def_controller(), rna_def_delay_sensor(), rna_def_edit_object_actuator(), rna_def_fmodifier_cycles(), rna_def_fmodifier_envelope(), rna_def_fmodifier_function_generator(), rna_def_fmodifier_generator(), rna_def_fmodifier_limits(), rna_def_fmodifier_noise(), rna_def_fmodifier_python(), rna_def_fmodifier_stepped(), rna_def_game_actuator(), rna_def_glow(), rna_def_joystick_sensor(), rna_def_keyboard_sensor(), rna_def_message_actuator(), rna_def_message_sensor(), rna_def_mouse_sensor(), rna_def_near_sensor(), rna_def_node_socket_subtype(), rna_def_object_actuator(), rna_def_parent_actuator(), rna_def_plugin(), rna_def_property_actuator(), rna_def_property_sensor(), rna_def_radar_sensor(), rna_def_random_actuator(), rna_def_random_sensor(), rna_def_ray_sensor(), rna_def_scene_actuator(), rna_def_shape_action_actuator(), rna_def_solid_color(), rna_def_sound_actuator(), rna_def_speed_control(), rna_def_state_actuator(), rna_def_steering_actuator(), rna_def_touch_sensor(), rna_def_transform(), rna_def_twodfilter_actuator(), rna_def_visibility_actuator(), and rna_def_wipe().
void RNA_def_struct_translation_context (StructRNA * srna, const char * context)
Definition at line 874 of file rna_define.c.
References StructRNA::translation_context.
Referenced by WM_operatortype_append(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), and WM_operatortype_append_ptr().
void RNA_def_struct_ui_icon (StructRNA * srna, int icon)
Definition at line 869 of file rna_define.c.
References StructRNA::icon.
Referenced by rna_def_action(), rna_def_area_lamp(), rna_def_armature(), rna_def_bone(), rna_def_bone_group(), rna_def_brush(), RNA_def_camera(), rna_def_channeldriver(), rna_def_cmp_output_file_socket(), rna_def_composite_nodetree(), rna_def_curve(), rna_def_edit_bone(), rna_def_editor(), rna_def_effector_weight(), rna_def_enum_property(), rna_def_fcurve(), rna_def_field(), rna_def_fluid_mesh_vertices(), rna_def_function(), rna_def_gpencil_data(), RNA_def_group(), rna_def_hemi_lamp(), rna_def_image(), rna_def_key(), rna_def_keyblock(), rna_def_keyingset(), rna_def_lamp(), rna_def_lattice(), rna_def_library(), RNA_def_main(), RNA_def_material(), rna_def_material_slot(), rna_def_mcol(), rna_def_medge(), rna_def_mesh(), rna_def_metaball(), rna_def_metaelement(), rna_def_mface(), rna_def_mloop(), rna_def_mloopcol(), rna_def_modifier_armature(), rna_def_modifier_array(), rna_def_modifier_bevel(), rna_def_modifier_boolean(), rna_def_modifier_build(), rna_def_modifier_cast(), rna_def_modifier_cloth(), rna_def_modifier_collision(), rna_def_modifier_curve(), rna_def_modifier_decimate(), rna_def_modifier_displace(), rna_def_modifier_dynamic_paint(), rna_def_modifier_edgesplit(), rna_def_modifier_explode(), rna_def_modifier_fluidsim(), rna_def_modifier_hook(), rna_def_modifier_lattice(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_mirror(), rna_def_modifier_multires(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_particlesystem(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smoke(), rna_def_modifier_smooth(), rna_def_modifier_softbody(), rna_def_modifier_solidify(), rna_def_modifier_subsurf(), rna_def_modifier_surface(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), rna_def_modifier_weightvgproximity(), rna_def_movieclip(), rna_def_mpolygon(), rna_def_mtex(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_mvert(), rna_def_mvert_group(), rna_def_nlastrip(), rna_def_nlatrack(), rna_def_node(), rna_def_node_link(), rna_def_node_socket(), rna_def_node_socket_subtype(), rna_def_nodetree(), rna_def_object(), rna_def_object_base(), rna_def_object_game_settings(), rna_def_particle_settings(), rna_def_particle_system(), rna_def_point_lamp(), rna_def_pointcache(), rna_def_property(), RNA_def_rna(), RNA_def_scene(), rna_def_scene_render_layer(), rna_def_screen(), rna_def_shader_nodetree(), rna_def_sound(), rna_def_speaker(), rna_def_spot_lamp(), rna_def_struct(), rna_def_sun_lamp(), rna_def_surface(), rna_def_text(), rna_def_texture(), rna_def_texture_nodetree(), rna_def_trackingTrack(), rna_def_vertex_group(), RNA_def_vfont(), and RNA_def_world().
void RNA_def_struct_ui_text (StructRNA * srna, const char * name, const char * description)
Definition at line 861 of file rna_define.c.
References DESCR_CHECK, StructRNA::description, StructRNA::identifier, StructRNA::name, and NULL.
Referenced by def_node(), rna_api_animdata_drivers(), rna_api_animdata_nla_tracks(), rna_api_nlatrack_strips(), rna_def_action(), rna_def_action_actuator(), rna_def_action_fcurves(), rna_def_action_group(), rna_def_action_groups(), rna_def_action_pose_markers(), rna_def_actuator(), rna_def_actuator_sensor(), rna_def_adjustment(), rna_def_always_sensor(), rna_def_animdata(), rna_def_animviz(), rna_def_animviz_ghosts(), rna_def_animviz_motion_path(), rna_def_animviz_motionpath_vert(), rna_def_animviz_paths(), rna_def_area(), rna_def_area_lamp(), rna_def_area_spaces(), rna_def_armature(), rna_def_armature_actuator(), rna_def_armature_bones(), rna_def_armature_edit_bones(), rna_def_armature_sensor(), rna_def_background_image(), rna_def_backgroundImages(), rna_def_beztriple(), rna_def_boid_settings(), rna_def_boidrule(), rna_def_boidrule_average_speed(), rna_def_boidrule_avoid(), rna_def_boidrule_avoid_collision(), rna_def_boidrule_fight(), rna_def_boidrule_follow_leader(), rna_def_boidrule_goal(), rna_def_boidstate(), rna_def_bone(), rna_def_bone_group(), rna_def_bone_groups(), rna_def_bpoint(), rna_def_brush(), rna_def_brush_texture_slot(), RNA_def_camera(), rna_def_camera_actuator(), rna_def_canvas_surface(), rna_def_canvas_surfaces(), rna_def_channeldriver(), rna_def_channeldriver_variables(), rna_def_charinfo(), rna_def_child_particle(), rna_def_cloth_collision_settings(), rna_def_cloth_sim_settings(), rna_def_cmp_output_file_socket(), rna_def_collision(), rna_def_collision_sensor(), rna_def_color_ramp(), rna_def_color_ramp_element(), rna_def_color_ramp_element_api(), rna_def_colormapping(), rna_def_composite_nodetree(), rna_def_composite_nodetree_api(), rna_def_compositor_node(), rna_def_console_line(), RNA_def_constraint(), rna_def_constraint_action(), rna_def_constraint_actuator(), rna_def_constraint_camera_solver(), rna_def_constraint_childof(), rna_def_constraint_clamp_to(), rna_def_constraint_damped_track(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_follow_track(), rna_def_constraint_kinematic(), rna_def_constraint_locate_like(), rna_def_constraint_location_limit(), rna_def_constraint_locked_track(), rna_def_constraint_minmax(), rna_def_constraint_object_solver(), rna_def_constraint_pivot(), rna_def_constraint_python(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_rotate_like(), rna_def_constraint_rotation_limit(), rna_def_constraint_same_volume(), rna_def_constraint_shrinkwrap(), rna_def_constraint_size_like(), rna_def_constraint_size_limit(), rna_def_constraint_spline_ik(), rna_def_constraint_stretch_to(), rna_def_constraint_track_to(), rna_def_constraint_transform(), rna_def_constraint_transform_like(), rna_def_constrainttarget(), RNA_def_context(), RNA_def_controller(), rna_def_curve(), rna_def_curve_nurb(), rna_def_curve_spline_bezpoints(), rna_def_curve_spline_points(), rna_def_curve_splines(), rna_def_curvemap(), rna_def_curvemapping(), rna_def_curvemappoint(), rna_def_delay_sensor(), rna_def_dopesheet(), rna_def_drivertarget(), rna_def_drivervar(), rna_def_dupli_object(), rna_def_dynamic_paint_brush_settings(), rna_def_dynamic_paint_canvas_settings(), rna_def_edit_bone(), rna_def_edit_object_actuator(), rna_def_editor(), rna_def_effect(), rna_def_effector_weight(), rna_def_enum_property(), rna_def_environment_map(), rna_def_event(), rna_def_fcurve(), rna_def_fcurve_keyframe_points(), rna_def_fcurve_modifiers(), rna_def_field(), rna_def_fileselect_params(), rna_def_fkeyframe(), rna_def_fluid_mesh_vertices(), rna_def_fluid_settings(), RNA_def_fluidsim(), rna_def_fluidsim_control(), rna_def_fluidsim_domain(), rna_def_fluidsim_fluid(), rna_def_fluidsim_inflow(), rna_def_fluidsim_obstacle(), rna_def_fluidsim_outflow(), rna_def_fluidsim_particle(), rna_def_fmodifier(), rna_def_fmodifier_cycles(), rna_def_fmodifier_envelope(), rna_def_fmodifier_envelope_ctrl(), rna_def_fmodifier_function_generator(), rna_def_fmodifier_generator(), rna_def_fmodifier_limits(), rna_def_fmodifier_noise(), rna_def_fmodifier_python(), rna_def_fmodifier_stepped(), rna_def_fpoint(), rna_def_function(), rna_def_game_actuator(), rna_def_game_softbody(), RNA_def_gameproperty(), rna_def_glow(), rna_def_gpencil_data(), rna_def_gpencil_frame(), rna_def_gpencil_layer(), rna_def_gpencil_layers(), rna_def_gpencil_stroke(), rna_def_gpencil_stroke_point(), RNA_def_group(), rna_def_group_objects(), rna_def_group_sockets_api(), rna_def_header(), rna_def_hemi_lamp(), rna_def_histogram(), RNA_def_ID(), rna_def_ID(), rna_def_ID_materials(), rna_def_ID_properties(), rna_def_image(), rna_def_image_paint(), rna_def_imageuser(), rna_def_joystick_sensor(), rna_def_key(), rna_def_keyblock(), rna_def_keyboard_sensor(), rna_def_keyconfig(), rna_def_keydata(), rna_def_keyingset(), rna_def_keyingset_info(), rna_def_keyingset_path(), rna_def_keyingset_paths(), rna_def_keymap_items(), rna_def_lamp(), rna_def_lamp_mtex(), rna_def_lamp_sky_settings(), rna_def_lattice(), rna_def_latticepoint(), rna_def_library(), rna_def_lighting(), rna_def_loop_colors(), rna_def_macro_operator(), RNA_def_main(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_gpencil(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_libraries(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_movieclips(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_screens(), RNA_def_main_sounds(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_window_managers(), RNA_def_main_worlds(), RNA_def_material(), rna_def_material_gamesettings(), rna_def_material_halo(), rna_def_material_mtex(), rna_def_material_physics(), rna_def_material_raymirror(), rna_def_material_raytra(), rna_def_material_slot(), rna_def_material_sss(), rna_def_material_strand(), rna_def_material_volume(), rna_def_mcol(), rna_def_medge(), rna_def_menu(), rna_def_mesh(), rna_def_mesh_edges(), rna_def_mesh_loops(), rna_def_mesh_polygons(), rna_def_mesh_tessfaces(), rna_def_mesh_vertices(), rna_def_message_actuator(), rna_def_message_sensor(), rna_def_meta(), rna_def_metaball(), rna_def_metaball_elements(), rna_def_metaelement(), rna_def_mface(), rna_def_mloop(), rna_def_mloopcol(), RNA_def_modifier(), rna_def_modifier_armature(), rna_def_modifier_array(), rna_def_modifier_bevel(), rna_def_modifier_boolean(), rna_def_modifier_build(), rna_def_modifier_cast(), rna_def_modifier_cloth(), rna_def_modifier_collision(), rna_def_modifier_curve(), rna_def_modifier_decimate(), rna_def_modifier_displace(), rna_def_modifier_dynamic_paint(), rna_def_modifier_edgesplit(), rna_def_modifier_explode(), rna_def_modifier_fluidsim(), rna_def_modifier_hook(), rna_def_modifier_lattice(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_mirror(), rna_def_modifier_multires(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_particlesystem(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smoke(), rna_def_modifier_smooth(), rna_def_modifier_softbody(), rna_def_modifier_solidify(), rna_def_modifier_subsurf(), rna_def_modifier_surface(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), rna_def_modifier_weightvgproximity(), rna_def_mouse_sensor(), rna_def_movie(), rna_def_movieclip(), rna_def_movieclip_proxy(), rna_def_movieClipScopes(), rna_def_moviecliUser(), rna_def_mpolygon(), rna_def_mproperties(), rna_def_msticky(), rna_def_mtex(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_multicam(), rna_def_mvert(), rna_def_mvert_group(), rna_def_near_sensor(), rna_def_nlastrip(), rna_def_nlatrack(), rna_def_node(), rna_def_node_link(), rna_def_node_socket(), rna_def_node_socket_subtype(), rna_def_nodetree(), rna_def_nodetree_link_api(), rna_def_object(), rna_def_object_actuator(), rna_def_object_base(), rna_def_object_constraints(), rna_def_object_game_settings(), rna_def_object_modifiers(), rna_def_object_particle_systems(), rna_def_object_vertex_groups(), rna_def_operator(), rna_def_operator_filelist_element(), rna_def_operator_stroke_element(), rna_def_operator_type_macro(), rna_def_operator_utils(), RNA_def_packedfile(), rna_def_paint(), rna_def_panel(), rna_def_parent_actuator(), rna_def_particle(), rna_def_particle_dupliweight(), rna_def_particle_edit(), rna_def_particle_hair_key(), rna_def_particle_key(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_particle_system(), rna_def_particle_target(), rna_def_plugin(), rna_def_point_lamp(), rna_def_pointcache(), rna_def_polygon_float_layers(), rna_def_polygon_int_layers(), rna_def_polygon_string_layers(), rna_def_pose(), rna_def_pose_channel(), rna_def_pose_channel_constraints(), rna_def_pose_ikparam(), rna_def_pose_itasc(), rna_def_property(), rna_def_property_actuator(), rna_def_property_sensor(), rna_def_ptcache_point_caches(), rna_def_radar_sensor(), rna_def_random_actuator(), rna_def_random_sensor(), rna_def_ray_sensor(), rna_def_reconstructedCamera(), rna_def_region(), rna_def_render_engine(), rna_def_render_layer(), rna_def_render_layers(), rna_def_render_pass(), rna_def_render_result(), RNA_def_rna(), RNA_def_scene(), rna_def_scene(), rna_def_scene_actuator(), rna_def_scene_bases(), rna_def_scene_ffmpeg_settings(), rna_def_scene_game_data(), rna_def_scene_game_recast_data(), rna_def_scene_image_format_data(), rna_def_scene_keying_sets(), rna_def_scene_keying_sets_all(), rna_def_scene_objects(), rna_def_scene_render_data(), rna_def_scene_render_layer(), rna_def_scopes(), rna_def_screen(), rna_def_sculpt(), rna_def_sculpt_capabilities(), rna_def_selected_uv_element(), rna_def_sensor(), rna_def_sequence(), rna_def_shader_node(), rna_def_shader_nodetree(), rna_def_shader_nodetree_api(), rna_def_shape_action_actuator(), rna_def_smoke_coll_settings(), rna_def_smoke_domain_settings(), rna_def_smoke_flow_settings(), rna_def_softbody(), rna_def_solid_color(), rna_def_sound(), rna_def_sound_actuator(), rna_def_space(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_console(), rna_def_space_dopesheet(), rna_def_space_filebrowser(), rna_def_space_graph(), rna_def_space_image(), rna_def_space_image_uv(), rna_def_space_info(), rna_def_space_logic(), rna_def_space_nla(), rna_def_space_node(), rna_def_space_outliner(), rna_def_space_sequencer(), rna_def_space_text(), rna_def_space_time(), rna_def_space_userpref(), rna_def_space_view3d(), rna_def_speaker(), rna_def_speed_control(), rna_def_spot_lamp(), rna_def_state_actuator(), rna_def_steering_actuator(), rna_def_strip_color_balance(), rna_def_strip_crop(), rna_def_strip_element(), rna_def_strip_proxy(), rna_def_strip_transform(), rna_def_struct(), rna_def_sun_lamp(), rna_def_surface(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), rna_def_texmapping(), rna_def_text(), rna_def_text_line(), rna_def_text_marker(), rna_def_textbox(), rna_def_texture(), rna_def_texture_blend(), rna_def_texture_clouds(), rna_def_texture_distorted_noise(), rna_def_texture_environment_map(), rna_def_texture_image(), rna_def_texture_magic(), rna_def_texture_marble(), rna_def_texture_musgrave(), rna_def_texture_node(), rna_def_texture_nodetree(), rna_def_texture_nodetree_api(), rna_def_texture_noise(), rna_def_texture_ocean(), rna_def_texture_plugin(), rna_def_texture_pointdensity(), rna_def_texture_slots(), rna_def_texture_stucci(), rna_def_texture_voronoi(), rna_def_texture_voxeldata(), rna_def_texture_wood(), rna_def_timeline_marker(), rna_def_timeline_markers(), rna_def_timer(), rna_def_tool_settings(), rna_def_touch_sensor(), rna_def_tracking(), rna_def_trackingCamera(), rna_def_trackingMarker(), rna_def_trackingMarkers(), rna_def_trackingObject(), rna_def_trackingObjects(), rna_def_trackingObjectTracks(), rna_def_trackingReconstruction(), rna_def_trackingSettings(), rna_def_trackingStabilization(), rna_def_trackingTrack(), rna_def_trackingTracks(), rna_def_transform(), rna_def_twodfilter_actuator(), rna_def_ui_layout(), rna_def_unified_paint_settings(), rna_def_unit_settings(), RNA_def_userdef(), rna_def_userdef_addon(), rna_def_userdef_addon_collection(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_solidlight(), rna_def_userdef_system(), rna_def_userdef_theme_colorset(), rna_def_userdef_theme_space_action(), rna_def_userdef_theme_space_buts(), rna_def_userdef_theme_space_clip(), rna_def_userdef_theme_space_console(), rna_def_userdef_theme_space_file(), rna_def_userdef_theme_space_generic(), rna_def_userdef_theme_space_graph(), rna_def_userdef_theme_space_image(), rna_def_userdef_theme_space_info(), rna_def_userdef_theme_space_list_generic(), rna_def_userdef_theme_space_logic(), rna_def_userdef_theme_space_nla(), rna_def_userdef_theme_space_node(), rna_def_userdef_theme_space_outliner(), rna_def_userdef_theme_space_seq(), rna_def_userdef_theme_space_text(), rna_def_userdef_theme_space_time(), rna_def_userdef_theme_space_userpref(), rna_def_userdef_theme_space_view3d(), rna_def_userdef_theme_ui(), rna_def_userdef_theme_ui_font_style(), rna_def_userdef_theme_ui_panel(), rna_def_userdef_theme_ui_style(), rna_def_userdef_theme_ui_wcol(), rna_def_userdef_theme_ui_wcol_state(), rna_def_userdef_themes(), rna_def_userdef_view(), rna_def_uv_layers(), rna_def_uv_sculpt(), rna_def_uv_textures(), rna_def_vertex_group(), rna_def_vertex_paint(), RNA_def_vfont(), rna_def_visibility_actuator(), rna_def_window(), rna_def_windowmanager(), rna_def_wipe(), rna_def_wm_keyconfigs(), rna_def_wm_keymaps(), RNA_def_world(), rna_def_world_mist(), rna_def_world_mtex(), rna_def_world_stars(), WM_operatortype_append(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), and WM_operatortype_append_ptr().
void RNA_define_free (BlenderRNA * brna)
void RNA_define_verify_sdna (int verify)
Definition at line 487 of file rna_define.c.
References BlenderDefRNA::verify.
Referenced by rna_def_edit_bone(), rna_def_event(), rna_def_header(), rna_def_keyingset_info(), RNA_def_main(), rna_def_menu(), rna_def_render_engine(), rna_def_render_layer(), rna_def_render_pass(), rna_def_render_result(), and rna_def_timer().
void RNA_enum_item_add (EnumPropertyItem ** items, int * totitem, const EnumPropertyItem * item)
Definition at line 2768 of file rna_define.c.
References MEM_callocN(), and MEM_freeN().
Referenced by ANIM_keying_sets_enum_itemf(), BIF_enumTransformOrientation(), gameprops_itemf(), hook_mod_itemf(), modifier_add_itemf(), object_mode_set_itemsf(), object_select_menu_enum_itemf(), proxy_group_object_itemf(), RNA_enum_item_add_separator(), RNA_enum_item_end(), RNA_enum_items_add(), RNA_enum_items_add_value(), rna_id_itemf(), rna_undo_itemf(), shape_itemf(), vgroup_itemf(), and weight_paint_sample_enum_itemf().
void RNA_enum_item_add_separator (EnumPropertyItem ** items, int * totitem)
Definition at line 2788 of file rna_define.c.
References NULL, and RNA_enum_item_add().
Referenced by ANIM_keying_sets_enum_itemf(), and BIF_enumTransformOrientation().
void RNA_enum_item_end (EnumPropertyItem ** items, int * totitem)
Definition at line 2812 of file rna_define.c.
References NULL, and RNA_enum_item_add().
Referenced by ANIM_keying_sets_enum_itemf(), BIF_enumTransformOrientation(), gameprops_itemf(), hook_mod_itemf(), merge_type_itemf(), modifier_add_itemf(), object_mode_set_itemsf(), object_select_menu_enum_itemf(), proxy_group_object_itemf(), rna_id_itemf(), rna_undo_itemf(), select_similar_type_itemf(), shape_itemf(), vgroup_itemf(), and weight_paint_sample_enum_itemf().
void RNA_enum_items_add (EnumPropertyItem ** items, int * totitem, EnumPropertyItem * item)
Definition at line 2794 of file rna_define.c.
References EnumPropertyItem::identifier, and RNA_enum_item_add().
void RNA_enum_items_add_value (EnumPropertyItem ** items, int * totitem, EnumPropertyItem * item, int value)
Definition at line 2800 of file rna_define.c.
References EnumPropertyItem::identifier, RNA_enum_item_add(), and EnumPropertyItem::value.
Referenced by merge_type_itemf(), and select_similar_type_itemf().
void RNA_exit (void)
Definition at line 86 of file rna_access.c.
References BLENDER_RNA, BLI_ghash_free(), StructRNA::cont, ListBase::first, ContainerRNA::next, NULL, ContainerRNA::prophash, RNA_free(), RNA_property_update_cache_free(), and BlenderRNA::structs.
Referenced by main(), and WM_exit_ext().
void RNA_free (BlenderRNA * brna)
Definition at line 550 of file rna_define.c.
References FunctionRNA::cont, StructRNA::cont, ListBase::first, StructRNA::functions, MEM_freeN(), ContainerRNA::next, BlenderDefRNA::preprocess, ContainerRNA::properties, RNA_define_free(), rna_freelistN(), RNA_struct_free(), and BlenderRNA::structs.
Referenced by RNA_exit(), and rna_preprocess().
void RNA_init (void)
Definition at line 70 of file rna_access.c.
References BLENDER_RNA, BLI_ghash_insert(), BLI_ghash_new(), BLI_ghashutil_strcmp(), BLI_ghashutil_strhash(), StructRNA::cont, ListBase::first, PropertyRNA::flag, PropertyRNA::identifier, PropertyRNA::next, ContainerRNA::next, PROP_BUILTIN, ContainerRNA::properties, ContainerRNA::prophash, and BlenderRNA::structs.
Referenced by main().
const char* RNA_property_typename (PropertyType type)
Definition at line 3039 of file rna_define.c.
References PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_POINTER, and PROP_STRING.
Referenced by RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), rna_def_property_get_func(), RNA_def_property_int_sdna(), and rna_generate_property().
void RNA_struct_free (BlenderRNA * brna, StructRNA * srna)
Definition at line 501 of file rna_define.c.
References FunctionRNA::cont, StructRNA::cont, ListBase::first, PropertyRNA::flag, FunctionRNA::flag, StructRNA::flag, FUNC_RUNTIME, StructRNA::functions, PropertyRNA::next, ContainerRNA::next, PROP_RUNTIME, ContainerRNA::properties, RNA_def_func_free_pointers(), RNA_def_property_free_pointers(), RNA_def_struct_free_pointers(), rna_freelinkN(), STRUCT_RUNTIME, and BlenderRNA::structs.
Referenced by RNA_free(), and WM_operatortype_remove().
void RNA_struct_free_extension (StructRNA * srna, ExtensionRNA * ext)
Definition at line 492 of file rna_define.c.
References ExtensionRNA::data, ExtensionRNA::free, NULL, RNA_struct_blender_type_set(), and RNA_struct_py_type_set().