Blender: btStackAlloc Class Reference
btStackAlloc Class Reference
The StackAlloc class provides some fast stack-based memory allocator (LIFO last-in first-out)
#include <btStackAlloc.h>
Public Member Functions
btStackAlloc (unsigned int size)
~btStackAlloc ()
void create (unsigned int size)
void destroy ()
int getAvailableMemory () const
unsigned char * allocate (unsigned int size)
SIMD_FORCE_INLINE btBlock * beginBlock ()
SIMD_FORCE_INLINE void endBlock (btBlock *block)
Detailed Description
The StackAlloc class provides some fast stack-based memory allocator (LIFO last-in first-out)
Definition at line 34 of file btStackAlloc.h.
Constructor & Destructor Documentation
btStackAlloc::btStackAlloc (unsigned int size) [inline]
Definition at line 38 of file btStackAlloc.h.
References create().
btStackAlloc::~btStackAlloc () [inline]
Definition at line 39 of file btStackAlloc.h.
References destroy().
Referenced by btDefaultCollisionConfiguration::~btDefaultCollisionConfiguration().
Member Function Documentation
unsigned char* btStackAlloc::allocate (unsigned int size) [inline]
Definition at line 68 of file btStackAlloc.h.
References btAssert.
Referenced by beginBlock().
SIMD_FORCE_INLINE btBlock* btStackAlloc::beginBlock () [inline]
Definition at line 81 of file btStackAlloc.h.
References btBlock::address, allocate(), and btBlock::previous.
void btStackAlloc::create (unsigned int size) [inline]
Definition at line 41 of file btStackAlloc.h.
References btAlignedAlloc, destroy(), and size().
Referenced by btStackAlloc().
void btStackAlloc::destroy () [inline]
Definition at line 47 of file btStackAlloc.h.
References btAlignedFree, and btAssert.
Referenced by create(), btDefaultCollisionConfiguration::~btDefaultCollisionConfiguration(), and ~btStackAlloc().
SIMD_FORCE_INLINE void btStackAlloc::endBlock (btBlock * block) [inline]
Definition at line 89 of file btStackAlloc.h.
References btBlock::address, btAssert, and btBlock::previous.
int btStackAlloc::getAvailableMemory () const [inline]
Definition at line 63 of file btStackAlloc.h.
The documentation for this class was generated from the following file:
btStackAlloc.h