Blender: reeb.c File Reference
reeb.c File Reference
armature
#include <math.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <float.h>
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "MEM_guardedalloc.h"
#include "BKE_context.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BLI_editVert.h"
#include "BLI_edgehash.h"
#include "BLI_ghash.h"
#include "BLI_heap.h"
#include "BKE_mesh.h"
#include "ONL_opennl.h"
#include "reeb.h"
Classes
struct VertexData
struct EdgeIndex
Defines
#define DEBUG_REEB
#define DEBUG_REEB_NODE
Typedefs
typedef struct VertexData VertexData
typedef struct EdgeIndex EdgeIndex
Enumerations
enum MergeDirection { MERGE_LOWER, MERGE_HIGHER, MERGE_APPEND }
Functions
int mergeArcs (ReebGraph *rg, ReebArc *a0, ReebArc *a1)
void mergeArcEdges (ReebGraph *rg, ReebArc *aDst, ReebArc *aSrc, MergeDirection direction)
int mergeConnectedArcs (ReebGraph *rg, ReebArc *a0, ReebArc *a1)
EditEdge * NextEdgeForVert (EdgeIndex *indexed_edges, int index)
void mergeArcFaces (ReebGraph *rg, ReebArc *aDst, ReebArc *aSrc)
void addFacetoArc (ReebArc *arc, EditFace *efa)
void REEB_RadialSymmetry (BNode *root_node, RadialArc *ring, int count)
void REEB_AxialSymmetry (BNode *root_node, BNode *node1, BNode *node2, struct BArc *barc1, BArc *barc2)
void flipArcBuckets (ReebArc *arc)
void REEB_freeArc (BArc *barc)
void REEB_freeGraph (ReebGraph *rg)
ReebGraph * newReebGraph (void)
void BIF_flagMultiArcs (ReebGraph *rg, int flag)
ReebNode * BIF_otherNodeFromIndex (ReebArc *arc, ReebNode *node)
ReebNode * BIF_NodeFromIndex (ReebArc *arc, ReebNode *node)
ReebNode * BIF_lowestLevelNode (ReebNode *node)
ReebGraph * BIF_graphForMultiNode (ReebGraph *rg, ReebNode *node)
static void * headNode (void *arg)
static void * tailNode (void *arg)
static void * nextBucket (void *arg)
static void * nextNBucket (void *arg, int n)
static void * peekBucket (void *arg, int n)
static void * previousBucket (void *arg)
static int iteratorStopped (void *arg)
static void initIteratorFct (ReebArcIterator *iter)
static void setIteratorValues (ReebArcIterator *iter, EmbedBucket *bucket)
void initArcIterator (BArcIterator *arg, ReebArc *arc, ReebNode *head)
void initArcIteratorStart (BArcIterator *arg, struct ReebArc *arc, struct ReebNode *head, int start)
void initArcIterator2 (BArcIterator *arg, ReebArc *arc, int start, int end)
ReebGraph * BIF_ReebGraphMultiFromEditMesh (bContext *C)
Detailed Description
Definition in file reeb.c.
Define Documentation
#define DEBUG_REEB
Definition at line 81 of file reeb.c.
#define DEBUG_REEB_NODE
Definition at line 82 of file reeb.c.
Typedef Documentation
typedef struct EdgeIndex EdgeIndex
typedef struct VertexData VertexData
Enumeration Type Documentation
enum MergeDirection
Enumerator:
MERGE_LOWER
MERGE_HIGHER
MERGE_APPEND
Definition at line 97 of file reeb.c.
Function Documentation
void addFacetoArc (ReebArc * arc, EditFace * efa)
void BIF_flagMultiArcs (ReebGraph * rg, int flag)
Definition at line 230 of file reeb.c.
References BLI_flagArcs(), and ReebGraph::link_up.
Referenced by retargetGraphs().
ReebGraph* BIF_graphForMultiNode (ReebGraph * rg, ReebNode * node)
Definition at line 406 of file reeb.c.
References ReebGraph::link_up, ReebGraph::multi_level, and ReebNode::multi_level.
Referenced by matchMultiResolutionArc(), and matchMultiResolutionNode().
ReebNode* BIF_lowestLevelNode (ReebNode * node)
Definition at line 319 of file reeb.c.
References ReebNode::link_down.
ReebNode* BIF_NodeFromIndex (ReebArc * arc, ReebNode * node)
Definition at line 314 of file reeb.c.
References ReebArc::head, ReebNode::index, and ReebArc::tail.
Referenced by testFlipArc().
ReebNode* BIF_otherNodeFromIndex (ReebArc * arc, ReebNode * node)
Definition at line 309 of file reeb.c.
References ReebArc::head, ReebNode::index, and ReebArc::tail.
Referenced by retargetSubgraph().
ReebGraph* BIF_ReebGraphMultiFromEditMesh (bContext * C)
Definition at line 3390 of file reeb.c.
References BLI_buildAdjacencyList(), BLI_calcGraphLength(), BLI_markdownSymmetry(), CTX_data_edit_object(), CTX_data_scene(), data, Object::data, filterNullReebGraph(), ListBase::first, generateReebGraph(), i, BGraph::length, MEM_freeN(), BGraph::nodes, NULL, REEB_MAX_MULTI_LEVEL, removeNormalNodes(), renormalizeWeight(), repositionNodes(), SKGEN_FILTER_SMART, SKGEN_HARMONIC, ToolSettings::skgen_options, ToolSettings::skgen_postpro, ToolSettings::skgen_postpro_passes, ToolSettings::skgen_resolution, ToolSettings::skgen_symmetry_limit, ToolSettings::skgen_threshold_external, ToolSettings::skgen_threshold_internal, Scene::toolsettings, weightFromDistance(), and weightToHarmonic().
Referenced by BIF_retargetArmature().
void flipArcBuckets (ReebArc * arc)
static void * headNode (void * arg) [static]
Definition at line 3268 of file reeb.c.
References ReebArcIterator::arc, ReebArcIterator::end, ReebArc::head, ReebNode::no, ReebArcIterator::no, ReebArcIterator::p, ReebNode::p, ReebArcIterator::size, ReebArcIterator::start, and ReebArc::tail.
Referenced by initIteratorFct().
void initArcIterator (BArcIterator * arg, ReebArc * arc, ReebNode * head)
Definition at line 3189 of file reeb.c.
References ReebArcIterator::arc, ReebArc::bcount, ReebArcIterator::end, ReebArc::head, ReebArcIterator::index, initIteratorFct(), ReebArcIterator::length, ReebArcIterator::start, and ReebArcIterator::stride.
Referenced by REEB_AxialSymmetry(), REEB_RadialSymmetry(), retargetArctoArcAggresive(), and retargetArctoArcLength().
void initArcIterator2 (BArcIterator * arg, ReebArc * arc, int start, int end)
Definition at line 3244 of file reeb.c.
References abs(), ReebArcIterator::arc, ReebArcIterator::end, ReebArcIterator::index, initIteratorFct(), ReebArcIterator::length, ReebArcIterator::start, and ReebArcIterator::stride.
void initArcIteratorStart (BArcIterator * arg, struct ReebArc * arc, struct ReebNode * head, int start)
Definition at line 3214 of file reeb.c.
References ReebArcIterator::arc, ReebArc::bcount, ReebArcIterator::end, ReebArc::head, ReebArcIterator::index, initIteratorFct(), ReebArcIterator::length, ReebArcIterator::start, and ReebArcIterator::stride.
static void initIteratorFct (ReebArcIterator * iter) [static]
Definition at line 3163 of file reeb.c.
References ReebArcIterator::head, headNode(), iteratorStopped(), ReebArcIterator::next, nextBucket(), ReebArcIterator::nextN, nextNBucket(), ReebArcIterator::peek, peekBucket(), ReebArcIterator::previous, previousBucket(), ReebArcIterator::stopped, ReebArcIterator::tail, and tailNode().
Referenced by initArcIterator(), initArcIterator2(), and initArcIteratorStart().
static int iteratorStopped (void * arg) [static]
Definition at line 3374 of file reeb.c.
References ReebArcIterator::index, and ReebArcIterator::length.
Referenced by initIteratorFct().
void mergeArcEdges (ReebGraph * rg, ReebArc * aDst, ReebArc * aSrc, MergeDirection direction)
void mergeArcFaces (ReebGraph * rg, ReebArc * aDst, ReebArc * aSrc)
int mergeArcs (ReebGraph * rg, ReebArc * a0, ReebArc * a1)
int mergeConnectedArcs (ReebGraph * rg, ReebArc * a0, ReebArc * a1)
ReebGraph* newReebGraph (void)
Definition at line 213 of file reeb.c.
References ReebGraph::axial_symmetry, BLI_edgehash_new(), ReebGraph::emap, ReebGraph::free_arc, ReebGraph::free_node, MEM_callocN(), NULL, ReebGraph::radial_symmetry, REEB_AxialSymmetry(), REEB_freeArc(), REEB_RadialSymmetry(), and ReebGraph::totnodes.
static void * nextBucket (void * arg) [static]
Definition at line 3310 of file reeb.c.
References ReebArcIterator::arc, ReebArc::buckets, ReebArcIterator::index, ReebArcIterator::length, NULL, setIteratorValues(), ReebArcIterator::start, and ReebArcIterator::stride.
Referenced by initIteratorFct().
EditEdge* NextEdgeForVert (EdgeIndex * indexed_edges, int index)
static void * nextNBucket (void * arg, int n) [static]
Definition at line 3326 of file reeb.c.
References ReebArcIterator::arc, ReebArc::buckets, ReebArcIterator::index, ReebArcIterator::length, NULL, setIteratorValues(), ReebArcIterator::start, and ReebArcIterator::stride.
Referenced by initIteratorFct().
static void * peekBucket (void * arg, int n) [static]
Definition at line 3343 of file reeb.c.
References ReebArcIterator::arc, ReebArc::buckets, ReebArcIterator::index, length(), NULL, setIteratorValues(), ReebArcIterator::start, and ReebArcIterator::stride.
Referenced by initIteratorFct().
static void * previousBucket (void * arg) [static]
Definition at line 3359 of file reeb.c.
References ReebArcIterator::arc, ReebArc::buckets, ReebArcIterator::index, NULL, setIteratorValues(), ReebArcIterator::start, and ReebArcIterator::stride.
Referenced by initIteratorFct().
void REEB_AxialSymmetry (BNode * root_node, BNode * node1, BNode * node2, struct BArc * barc1, BArc * barc2)
Definition at line 1100 of file reeb.c.
References add_v3_v3(), ReebArc::bcount, BLI_mirrorAlongAxis(), copy_v3_v3(), initArcIterator(), interp_v3_v3v3(), IT_next(), mul_v3_fl(), NULL, EmbedBucket::nv, EmbedBucket::p, ReebNode::p, BNode::p, BNode::symmetry_axis, and EmbedBucket::val.
Referenced by newReebGraph().
void REEB_freeArc (BArc * barc)
Definition at line 166 of file reeb.c.
References BLI_freelistN(), BLI_ghash_free(), ReebArc::buckets, ReebArc::edges, ReebArc::faces, MEM_freeN(), and NULL.
Referenced by newReebGraph(), REEB_freeGraph(), and sk_retargetStroke().
void REEB_freeGraph (ReebGraph * rg)
Definition at line 180 of file reeb.c.
References ReebGraph::arcs, BLI_edgehash_free(), BLI_freelistN(), BLI_freeNode(), ReebGraph::emap, ListBase::first, ReebGraph::link_up, MEM_freeN(), ReebArc::next, next, ReebNode::next, ReebGraph::nodes, NULL, REEB_freeArc(), and REEB_freeGraph().
Referenced by REEB_freeGraph(), and RIG_freeRigGraph().
void REEB_RadialSymmetry (BNode * root_node, RadialArc * ring, int count)
Definition at line 969 of file reeb.c.
References add_v3_v3v3(), ReebArc::bcount, BLI_mirrorAlongAxis(), BLI_otherNode(), copy_v3_v3(), cross_v3_v3v3(), i, initArcIterator(), interp_v3_v3v3(), IT_next(), NULL, EmbedBucket::nv, EmbedBucket::p, BNode::p, ReebNode::p, BNode::symmetry_axis, and EmbedBucket::val.
Referenced by newReebGraph().
static void setIteratorValues (ReebArcIterator * iter, EmbedBucket * bucket) [static]
Definition at line 3174 of file reeb.c.
References ReebArcIterator::no, EmbedBucket::no, NULL, ReebArcIterator::p, EmbedBucket::p, and ReebArcIterator::size.
Referenced by nextBucket(), nextNBucket(), peekBucket(), and previousBucket().
static void * tailNode (void * arg) [static]
Definition at line 3289 of file reeb.c.
References ReebArcIterator::arc, ReebArcIterator::end, ReebArc::head, ReebNode::no, ReebArcIterator::no, ReebArcIterator::p, ReebNode::p, ReebArcIterator::size, ReebArcIterator::start, and ReebArc::tail.
Referenced by initIteratorFct().