Blender: node_composite_dilate.c File Reference
node_composite_dilate.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void morpho_dilate (CompBuf *cbuf)
static void morpho_erode (CompBuf *cbuf)
static void node_composit_exec_dilateerode (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_dilateerode (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_dilateerode_in []
static bNodeSocketTemplate cmp_node_dilateerode_out []
Detailed Description
Definition in file node_composite_dilate.c.
Function Documentation
static void morpho_dilate (CompBuf * cbuf) [static]
Definition at line 47 of file node_composite_dilate.c.
References MAX2, p, CompBuf::rect, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_dilateerode().
static void morpho_erode (CompBuf * cbuf) [static]
Definition at line 81 of file node_composite_dilate.c.
References MIN2, p, CompBuf::rect, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_dilateerode().
static void node_composit_exec_dilateerode (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 116 of file node_composite_dilate.c.
References CB_VAL, bNode::custom2, bNodeStack::data, data, dupalloc_compbuf(), free_compbuf(), i, morpho_dilate(), morpho_erode(), NULL, typecheck_compbuf(), and bNodeStack::vec.
Referenced by register_node_type_cmp_dilateerode().
void register_node_type_cmp_dilateerode (bNodeTreeType * ttype)
Definition at line 150 of file node_composite_dilate.c.
References CMP_NODE_DILATEERODE, NODE_CLASS_OP_FILTER, node_composit_exec_dilateerode(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_dilateerode_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Mask",      0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_FACTOR},
    {   -1, 0, ""   }
}
Definition at line 38 of file node_composite_dilate.c.
bNodeSocketTemplate cmp_node_dilateerode_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "Mask"},
    {   -1, 0, ""   }
}
Definition at line 42 of file node_composite_dilate.c.