Blender: report.c File Reference
report.c File Reference
blenkernel
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_dynstr.h"
#include "BLI_utildefines.h"
#include "BKE_report.h"
#include "BKE_global.h"
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
Functions
static const char * report_type_str (int type)
void BKE_reports_init (ReportList *reports, int flag)
void BKE_reports_clear (ReportList *reports)
void BKE_report (ReportList *reports, ReportType type, const char *message)
void BKE_reportf (ReportList *reports, ReportType type, const char *format,...)
void BKE_reports_prepend (ReportList *reports, const char *prepend)
void BKE_reports_prependf (ReportList *reports, const char *prepend,...)
ReportType BKE_report_print_level (ReportList *reports)
void BKE_report_print_level_set (ReportList *reports, ReportType level)
ReportType BKE_report_store_level (ReportList *reports)
void BKE_report_store_level_set (ReportList *reports, ReportType level)
char * BKE_reports_string (ReportList *reports, ReportType level)
void BKE_reports_print (ReportList *reports, ReportType level)
Report * BKE_reports_last_displayable (ReportList *reports)
int BKE_reports_contain (ReportList *reports, ReportType level)
Detailed Description
Definition in file report.c.
Function Documentation
void BKE_report (ReportList * reports, ReportType type, const char * message)
Definition at line 90 of file report.c.
References BLI_addtail(), ReportList::flag, G, Report::len, len(), ReportList::list, MEM_callocN(), Report::message, ReportList::printlevel, report_type_str(), RPT_PRINT, RPT_STORE, ReportList::storelevel, strlen(), Report::type, and Report::typestr.
Referenced by actkeys_copy_exec(), actkeys_paste_exec(), add_empty_ks_path_exec(), add_keyingset_button_exec(), add_verts_to_dgroups(), ANIM_paste_driver(), apply_armature_pose2bones_exec(), apply_objects_internal(), armature_align_bones_exec(), armature_calc_roll_exec(), armature_fill_bones_exec(), armature_parent_set_exec(), bake_freejob(), bake_image_exec(), BKE_animdata_set_action(), BKE_reportf_wrap(), blo_openblendermemfile(), blo_openblendermemory(), BLO_write_file(), BPy_errors_to_report(), childof_clear_inverse_exec(), childof_set_inverse_exec(), constraint_add_exec(), convert_tface_mt(), delete_key_exec(), delete_keyframe(), do_history(), do_item_rename(), do_outliner_operation_event(), do_set_scale(), drop_named_image_invoke(), dynamicPaint_initBake(), ED_armature_enter_posemode(), ed_marker_make_links_scene_exec(), ed_markers_opwrap_invoke_custom(), ED_mesh_edges_add(), ED_mesh_edges_remove(), ED_mesh_faces_remove(), ED_mesh_loops_add(), ED_mesh_polys_add(), ED_mesh_tessfaces_add(), ED_mesh_vertices_add(), ED_mesh_vertices_remove(), ED_object_add_generic_get_opts(), ED_object_modifier_add(), ED_object_modifier_apply(), ED_object_modifier_move_down(), ED_object_modifier_move_up(), ED_object_parent_set(), edbm_edge_rotate_selected_exec(), edbm_extrude_mesh(), edbm_noise_exec(), EDBM_op_finish(), edbm_rip_invoke(), edbm_rip_invoke__edge(), edbm_rip_invoke__vert(), edbm_screw_exec(), edbm_select_axis_exec(), edbm_select_non_manifold_exec(), edbm_select_nth_exec(), edbm_vertex_slide_exec(), file_browse_invoke(), file_directory_new_exec(), font_unlink_exec(), fullscreen_back_exec(), game_engine_exec(), gp_actframe_delete_exec(), gp_convert_layer_exec(), gp_data_add_exec(), gp_data_unlink_exec(), gp_layer_add_exec(), gpencil_draw_apply(), graph_fmodifier_add_exec(), graph_fmodifier_copy_exec(), graph_fmodifier_paste_exec(), graphkeys_click_insert_exec(), graphkeys_copy_exec(), graphkeys_euler_filter_exec(), graphkeys_sound_bake_exec(), image_pack_exec(), image_pack_test(), image_save_sequence_exec(), image_unpack_exec(), image_unpack_invoke(), initFlyInfo(), insert_key_button_exec(), insert_key_exec(), insert_keyframe_direct(), join_exec(), join_mesh_exec(), join_mesh_shapes_exec(), join_shapes_exec(), join_tracks_exec(), keyframe_jump_exec(), lib_link_object(), make_links_scene_exec(), make_paths_absolute_exec(), make_paths_relative_exec(), make_proxy_exec(), make_proxy_invoke(), make_segment_exec(), material_slot_remove_exec(), merge_2_nurb(), merge_nurb(), modifier_apply_obdata(), modifier_apply_shape(), multires_reshape_exec(), multiresbake_check(), multiresbake_image_exec(), multiresbake_image_exec_locked(), navmesh_create_exec(), navmesh_face_copy_exec(), nla_fmodifier_copy_exec(), nla_fmodifier_paste_exec(), nlaedit_add_actionclip_exec(), nlaedit_add_transition_exec(), nlaedit_disable_tweakmode_exec(), nlaedit_enable_tweakmode_exec(), nlaedit_swap_exec(), node_add_file_exec(), node_group_make_exec(), node_group_ungroup_exec(), object_add_hook_selob_exec(), object_armature_add_exec(), object_clear_transform_generic_exec(), object_constraint_add_exec(), object_hook_assign_exec(), object_hook_recenter_exec(), object_hook_remove_exec(), object_hook_reset_exec(), object_hook_select_exec(), object_origin_set_exec(), object_select_grouped_exec(), object_select_linked_exec(), object_track_clear_exec(), objects_add_active_exec(), objects_remove_active_exec(), objectsolver_clear_inverse_exec(), objectsolver_set_inverse_exec(), outliner_action_set_exec(), outliner_id_operation_exec(), outliner_keyingset_additems_exec(), parent_noinv_set_exec(), paste_animedit_keys(), paste_selection(), pose_clear_transform_generic_exec(), pose_constraint_add_exec(), pose_constraint_copy_exec(), pose_copy_exec(), pose_ik_add_invoke(), pose_paste_exec(), pose_slide_invoke_common(), poselib_preview_init_data(), poselib_remove_exec(), poselib_rename_exec(), poselib_rename_invoke(), poselib_sanitise_exec(), radial_control_get_properties(), radial_control_invoke(), RE_BlenderAnim(), RE_engine_report(), RE_InitState(), RE_is_rendering_allowed(), RE_WriteEnvmapResult(), RE_WriteRenderResult(), region_quadview_exec(), region_scale_invoke(), remove_active_keyingset_exec(), remove_active_ks_path_exec(), remove_keyingset_button_exec(), ringcut_invoke(), rna_raw_access(), save_image_doit(), screen_opengl_render_init(), screen_render_exec(), screen_render_invoke(), screenshot_startjob(), select_linked_internal(), select_nth_exec(), separate_exec(), sequencer_add_effect_strip_exec(), sequencer_add_effect_strip_invoke(), sequencer_add_image_strip_invoke(), sequencer_add_movie_strip_invoke(), sequencer_add_movieclip_strip_exec(), sequencer_add_movieclip_strip_invoke(), sequencer_add_scene_strip_exec(), sequencer_add_scene_strip_invoke(), sequencer_add_sound_strip_invoke(), sequencer_change_effect_input_exec(), sequencer_change_effect_type_exec(), sequencer_copy_exec(), sequencer_meta_make_exec(), sequencer_reassign_inputs_exec(), sequencer_select_grouped_exec(), sequencer_swap_data_exec(), sequencer_swap_inputs_exec(), set_axis_exec(), set_origin_exec(), set_plane_exec(), set_spline_type_exec(), shape_propagate(), solve_camera_exec(), solve_camera_freejob(), solve_camera_invoke(), sound_mixdown_exec(), sound_open_exec(), sound_unpack_exec(), sound_unpack_invoke(), spin_exec(), start_avi(), test_bake_internal(), text_reload_exec(), text_run_script(), text_run_script_exec(), texture_paint_camera_project_exec(), texture_paint_init(), texture_paint_toggle_exec(), tracking_object_remove_exec(), ui_do_button(), unlink_selection_exec(), unpack_all_invoke(), unwrap_exec(), vertex_group_fix_exec(), vertex_parent_set_exec(), vgroup_do_remap(), view3d_zoom_border_exec(), vtx_slide_init(), weight_sample_invoke(), WM_init_game(), wm_link_append_exec(), wm_open_mainfile_invoke(), wm_operator_finished(), wm_operator_reports(), WM_write_file(), and wpaint_stroke_test_start().
ReportType BKE_report_print_level (ReportList * reports)
Definition at line 197 of file report.c.
References ReportList::printlevel, and RPT_ERROR.
void BKE_report_print_level_set (ReportList * reports, ReportType level)
Definition at line 205 of file report.c.
References ReportList::printlevel.
ReportType BKE_report_store_level (ReportList * reports)
Definition at line 213 of file report.c.
References RPT_ERROR, and ReportList::storelevel.
void BKE_report_store_level_set (ReportList * reports, ReportType level)
Definition at line 221 of file report.c.
References ReportList::storelevel.
void BKE_reportf (ReportList * reports, ReportType type, const char * format, ...)
Definition at line 117 of file report.c.
References BLI_addtail(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_get_len(), BLI_dynstr_new(), BLI_dynstr_vappendf(), ReportList::flag, G, Report::len, ReportList::list, MEM_callocN(), Report::message, ReportList::printlevel, report_type_str(), RPT_PRINT, RPT_STORE, ReportList::storelevel, Report::type, and Report::typestr.
Referenced by ANIM_add_driver(), ANIM_apply_keyingset(), ANIM_copy_driver(), ANIM_paste_driver(), animviz_verify_motionpaths(), armature_fill_bones_exec(), BKE_animdata_set_action(), blo_decode_and_check(), blo_openblenderfile(), BLO_read_runtime(), BLO_write_file(), BPy_errors_to_report(), checkMissingFiles_visit_cb(), delete_key_exec(), delete_key_v3d_exec(), delete_keyframe(), ED_object_modifier_add(), ED_object_modifier_remove(), EDBM_op_call_and_selectf(), EDBM_op_callf(), EDBM_op_init(), edbm_remove_doubles_exec(), findMissingFiles_visit_cb(), graphkeys_euler_filter_exec(), handle_subversion_warning(), image_open_exec(), image_save_exec(), image_save_sequence_exec(), insert_key_exec(), insert_keyframe(), insert_keyframe_direct(), join_mesh_exec(), makeFilesAbsolute(), makeFilesAbsolute_visit_cb(), makeFilesRelative(), makeFilesRelative_visit_cb(), namebutton_cb(), newPackedFile(), nla_fmodifier_add_exec(), nlaedit_add_actionclip_exec(), nlaedit_swap_exec(), node_add_file_exec(), object_origin_set_exec(), open_exec(), outliner_action_set_exec(), packAll(), paint_exit(), paste_file(), poselib_remove_exec(), radial_control_get_path(), RE_layer_load_from_file(), RE_result_load_from_file(), redraw_timer_exec(), remove_doubles_exec(), rna_raw_access(), save_image_doit(), screen_opengl_render_anim_step(), screen_opengl_render_init(), screenshot_startjob(), sequencer_add_effect_strip_exec(), sequencer_add_generic_strip_exec(), solve_camera_freejob(), spacedata_cleanup(), text_find_and_replace(), texture_paint_image_from_view_exec(), txt_write_file(), ui_do_button(), vertex_group_copy_to_selected_exec(), wm_link_append_exec(), WM_operator_props_popup(), WM_operator_redo_popup(), WM_read_file(), WM_write_file(), and writePackedFile().
void BKE_reports_clear (ReportList * reports)
Definition at line 71 of file report.c.
References ListBase::first, ListBase::last, ReportList::list, MEM_freeN(), Report::message, Report::next, and NULL.
Referenced by bpy_lib_enter(), BPy_reports_to_error(), KX_BlenderSceneConverter::LinkBlendFile(), load_file(), load_game_data(), pyop_call(), GPC_Engine::Start(), wm_free_reports(), WM_operator_free(), and wm_reports_free().
int BKE_reports_contain (ReportList * reports, ReportType level)
Definition at line 276 of file report.c.
References FALSE, ListBase::first, ReportList::list, Report::next, NULL, TRUE, and Report::type.
Referenced by RE_engine_render().
void BKE_reports_init (ReportList * reports, int flag)
Definition at line 59 of file report.c.
References ReportList::flag, ReportList::printlevel, RPT_ERROR, RPT_INFO, and ReportList::storelevel.
Referenced by bpy_lib_enter(), direct_link_windowmanager(), KX_BlenderSceneConverter::LinkBlendFile(), load_file(), load_game_data(), pyop_call(), pyrna_func_call(), pyrna_register_class(), pyrna_struct_driver_add(), pyrna_struct_driver_remove(), pyrna_struct_keyframe_delete(), pyrna_struct_keyframe_insert(), render_animation(), render_frame(), screencast_exec(), GPC_Engine::Start(), thumbnails_start(), wm_init_reports(), and wm_operator_create().
Report* BKE_reports_last_displayable (ReportList * reports)
Definition at line 264 of file report.c.
References ELEM3, ListBase::last, ReportList::list, NULL, Report::prev, RPT_ERROR, RPT_INFO, RPT_WARNING, and Report::type.
Referenced by uiTemplateReportsBanner(), and update_reports_display_invoke().
void BKE_reports_prepend (ReportList * reports, const char * prepend)
Definition at line 150 of file report.c.
References BLI_dynstr_append(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_get_len(), BLI_dynstr_new(), ListBase::first, Report::len, ReportList::list, MEM_freeN(), Report::message, and Report::next.
Referenced by BKE_read_file_from_memfile(), BKE_read_file_from_memory(), createBoneSpace(), and createMeshSpace().
void BKE_reports_prependf (ReportList * reports, const char * prepend, ...)
Definition at line 172 of file report.c.
References BLI_dynstr_append(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_get_len(), BLI_dynstr_new(), BLI_dynstr_vappendf(), ListBase::first, Report::len, ReportList::list, MEM_freeN(), Report::message, and Report::next.
Referenced by BKE_read_file().
void BKE_reports_print (ReportList * reports, ReportType level)
Definition at line 252 of file report.c.
References BKE_reports_string(), MEM_freeN(), and NULL.
Referenced by load_game_data(), and wm_operator_reports().
char* BKE_reports_string (ReportList * reports, ReportType level)
Definition at line 229 of file report.c.
References BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_get_len(), BLI_dynstr_new(), ListBase::first, ReportList::list, Report::message, Report::next, NULL, Report::type, and Report::typestr.
Referenced by BKE_reports_print(), BPy_reports_to_error(), pyop_call(), and reports_to_text_exec().
static const char* report_type_str (int type) [static]
Definition at line 44 of file report.c.
References RPT_DEBUG, RPT_ERROR, RPT_ERROR_INVALID_CONTEXT, RPT_ERROR_INVALID_INPUT, RPT_ERROR_OUT_OF_MEMORY, RPT_INFO, RPT_OPERATOR, and RPT_WARNING.
Referenced by BKE_report(), and BKE_reportf().