Blender: CIntValue Class Reference
CIntValue Class Reference
#include <IntValue.h>
Public Member Functions
virtual const STR_String & GetText ()
virtual double GetNumber ()
cInt GetInt ()
CIntValue ()
CIntValue (cInt innie)
CIntValue (cInt innie, const char *name, AllocationTYPE alloctype=CValue::HEAPVALUE)
virtual CValue * Calc (VALUE_OPERATOR op, CValue *val)
virtual CValue * CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue *val)
virtual void SetValue (CValue *newval)
void Configure (CValue *menuvalue)
void AddConfigurationData (CValue *menuvalue)
virtual CValue * GetReplica ()
Protected Member Functions
virtual ~CIntValue ()
Detailed Description
Definition at line 27 of file IntValue.h.
Constructor & Destructor Documentation
CIntValue::CIntValue ()
Definition at line 29 of file IntValue.cpp.
References NULL.
Referenced by Calc(), CalcFinal(), and GetReplica().
CIntValue::CIntValue (cInt innie)
Definition at line 44 of file IntValue.cpp.
References NULL.
CIntValue::CIntValue (cInt innie, const char * name, AllocationTYPE alloctype = CValue::HEAPVALUE)
Definition at line 56 of file IntValue.cpp.
References CValue::DisableRefCount(), NULL, CPropValue::SetName(), and CValue::STACKVALUE.
CIntValue::~CIntValue () [protected, virtual]
Definition at line 71 of file IntValue.cpp.
Member Function Documentation
void CIntValue::AddConfigurationData (CValue * menuvalue)
CValue * CIntValue::Calc (VALUE_OPERATOR op, CValue * val) [virtual]
Implements CValue.
Definition at line 83 of file IntValue.cpp.
References CValue::CalcFinal(), CIntValue(), CValue::GetText(), CValue::op2str(), VALUE_AND_OPERATOR, VALUE_INT_TYPE, VALUE_NEG_OPERATOR, VALUE_NOT_OPERATOR, VALUE_OR_OPERATOR, and VALUE_POS_OPERATOR.
CValue * CIntValue::CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue * val) [virtual]
Implements CValue.
Definition at line 113 of file IntValue.cpp.
References CIntValue(), GetInt(), GetNumber(), GetText(), CValue::GetText(), CValue::op2str(), VALUE_ADD_OPERATOR, VALUE_BOOL_TYPE, VALUE_DIV_OPERATOR, VALUE_EMPTY_TYPE, VALUE_EQL_OPERATOR, VALUE_ERROR_TYPE, VALUE_FLOAT_TYPE, VALUE_GEQ_OPERATOR, VALUE_GRE_OPERATOR, VALUE_INT_TYPE, VALUE_LEQ_OPERATOR, VALUE_LES_OPERATOR, VALUE_MOD_OPERATOR, VALUE_MUL_OPERATOR, VALUE_NEG_OPERATOR, VALUE_NEQ_OPERATOR, VALUE_POS_OPERATOR, VALUE_STRING_TYPE, and VALUE_SUB_OPERATOR.
void CIntValue::Configure (CValue * menuvalue)
cInt CIntValue::GetInt ()
pre: ret: the cInt stored in the object
Definition at line 285 of file IntValue.cpp.
Referenced by CalcFinal().
double CIntValue::GetNumber () [virtual]
Implements CValue.
Definition at line 292 of file IntValue.cpp.
Referenced by CalcFinal().
CValue * CIntValue::GetReplica (void) [virtual]
Implements CValue.
Definition at line 310 of file IntValue.cpp.
References CIntValue(), NULL, and CValue::ProcessReplica().
const STR_String & CIntValue::GetText () [virtual]
Implements CValue.
Definition at line 299 of file IntValue.cpp.
References STR_String::Format().
Referenced by BL_ConvertActuators(), BL_ConvertControllers(), BL_ConvertSensors(), and CalcFinal().
void CIntValue::SetValue (CValue * newval) [virtual]
Sets the value to this cvalue.
Attention:
this particular function should never be called. Why not abstract?
Reimplemented from CValue.
Definition at line 321 of file IntValue.cpp.
References CValue::GetNumber(), and CValue::SetModified().
The documentation for this class was generated from the following files:
IntValue.h
IntValue.cpp