Blender: interface_templates.c File Reference
interface_templates.c File Reference
interface
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_anim_types.h"
#include "DNA_dynamicpaint_types.h"
#include "DNA_key_types.h"
#include "DNA_scene_types.h"
#include "DNA_userdef_types.h"
#include "BLI_utildefines.h"
#include "BLI_string.h"
#include "BLI_ghash.h"
#include "BLF_translation.h"
#include "BKE_animsys.h"
#include "BKE_colortools.h"
#include "BKE_context.h"
#include "BKE_dynamicpaint.h"
#include "BKE_global.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_object.h"
#include "BKE_material.h"
#include "BKE_texture.h"
#include "BKE_report.h"
#include "BKE_displist.h"
#include "BKE_scene.h"
#include "ED_screen.h"
#include "ED_object.h"
#include "ED_render.h"
#include "RNA_access.h"
#include "RNA_enum_types.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "interface_intern.h"
#include "BLF_api.h"
#include "DNA_object_force.h"
#include "BKE_depsgraph.h"
#include "BKE_modifier.h"
#include "BKE_particle.h"
#include "ED_util.h"
#include "BLI_math.h"
#include "BLI_listbase.h"
#include "DNA_constraint_types.h"
#include "BKE_action.h"
#include "BKE_constraint.h"
#include "DNA_lamp_types.h"
#include "DNA_material_types.h"
#include "DNA_world_types.h"
Classes
struct TemplateID
struct RNAUpdateCb
Defines
#define ERROR_LIBDATA_MESSAGE "Can't edit external libdata"
#define REDRAWIPO 1
#define REDRAWNLA 2
#define REDRAWBUTSOBJECT 3
#define REDRAWACTION 4
#define B_CONSTRAINT_TEST 5
#define B_CONSTRAINT_CHANGETARGET 6
#define REMAKEIPO 8
#define B_DIFF 9
#define B_MATPRV 1
#define B_BANDCOL 1
#define WHEEL_SIZE 100
#define B_STOPRENDER 1
#define B_STOPCAST 2
#define B_STOPANIM 3
#define B_STOPCOMPO 4
#define B_STOPSEQ 5
#define B_STOPCLIP 6
Typedefs
typedef struct TemplateID TemplateID
typedef struct RNAUpdateCb RNAUpdateCb
Functions
void UI_template_fix_linking (void)
void uiTemplateHeader (uiLayout *layout, bContext *C, int menus)
static void id_search_call_cb (bContext *C, void *arg_template, void *item)
static void id_search_cb (const bContext *C, void *arg_template, const char *str, uiSearchItems *items)
static uiBlock * id_search_menu (bContext *C, ARegion *ar, void *arg_litem)
void uiIDContextProperty (bContext *C, PointerRNA *ptr, PropertyRNA **prop)
static void template_id_cb (bContext *C, void *arg_litem, void *arg_event)
static const char * template_id_browse_tip (StructRNA *type)
static void template_ID (bContext *C, uiLayout *layout, TemplateID *template, StructRNA *type, short idcode, int flag, const char *newop, const char *openop, const char *unlinkop)
static void ui_template_id (uiLayout *layout, bContext *C, PointerRNA *ptr, const char *propname, const char *newop, const char *openop, const char *unlinkop, int flag, int prv_rows, int prv_cols)
void uiTemplateID (uiLayout *layout, bContext *C, PointerRNA *ptr, const char *propname, const char *newop, const char *openop, const char *unlinkop)
void uiTemplateIDBrowse (uiLayout *layout, bContext *C, PointerRNA *ptr, const char *propname, const char *newop, const char *openop, const char *unlinkop)
void uiTemplateIDPreview (uiLayout *layout, bContext *C, PointerRNA *ptr, const char *propname, const char *newop, const char *openop, const char *unlinkop, int rows, int cols)
void uiTemplateAnyID (uiLayout *layout, PointerRNA *ptr, const char *propname, const char *proptypename, const char *text)
void uiTemplatePathBuilder (uiLayout *layout, PointerRNA *ptr, const char *propname, PointerRNA *UNUSED(root_ptr), const char *text)
static void modifiers_setOnCage (bContext *C, void *ob_v, void *md_v)
static void modifiers_convertToReal (bContext *C, void *ob_v, void *md_v)
static int modifier_can_delete (ModifierData *md)
static int modifier_is_simulation (ModifierData *md)
static uiLayout * draw_modifier (uiLayout *layout, Scene *scene, Object *ob, ModifierData *md, int index, int cageIndex, int lastCageIndex)
uiLayout * uiTemplateModifier (uiLayout *layout, bContext *C, PointerRNA *ptr)
static void do_constraint_panels (bContext *C, void *ob_pt, int event)
static void constraint_active_func (bContext *UNUSED(C), void *ob_v, void *con_v)
static uiLayout * draw_constraint (uiLayout *layout, Object *ob, bConstraint *con)
uiLayout * uiTemplateConstraint (uiLayout *layout, PointerRNA *ptr)
static void do_preview_buttons (bContext *C, void *arg, int event)
void uiTemplatePreview (uiLayout *layout, ID *id, int show_buttons, ID *parent, MTex *slot)
static void rna_update_cb (bContext *C, void *arg_cb, void *UNUSED(arg))
static void colorband_add_cb (bContext *C, void *cb_v, void *coba_v)
static void colorband_del_cb (bContext *C, void *cb_v, void *coba_v)
static void colorband_flip_cb (bContext *C, void *cb_v, void *coba_v)
static void colorband_update_cb (bContext *UNUSED(C), void *bt_v, void *coba_v)
static void colorband_buttons_large (uiLayout *layout, uiBlock *block, ColorBand *coba, int xoffs, int yoffs, RNAUpdateCb *cb)
static void colorband_buttons_small (uiLayout *layout, uiBlock *block, ColorBand *coba, rctf *butr, RNAUpdateCb *cb)
static void colorband_buttons_layout (uiLayout *layout, uiBlock *block, ColorBand *coba, rctf *butr, int small, RNAUpdateCb *cb)
void uiTemplateColorRamp (uiLayout *layout, PointerRNA *ptr, const char *propname, int expand)
void uiTemplateHistogram (uiLayout *layout, PointerRNA *ptr, const char *propname)
void uiTemplateWaveform (uiLayout *layout, PointerRNA *ptr, const char *propname)
void uiTemplateVectorscope (uiLayout *layout, PointerRNA *ptr, const char *propname)
static void curvemap_buttons_zoom_in (bContext *C, void *cumap_v, void *UNUSED(arg))
static void curvemap_buttons_zoom_out (bContext *C, void *cumap_v, void *UNUSED(unused))
static void curvemap_buttons_setclip (bContext *UNUSED(C), void *cumap_v, void *UNUSED(arg))
static void curvemap_buttons_delete (bContext *C, void *cb_v, void *cumap_v)
static uiBlock * curvemap_clipping_func (bContext *C, struct ARegion *ar, void *cumap_v)
static void curvemap_tools_dofunc (bContext *C, void *cumap_v, int event)
static uiBlock * curvemap_tools_func (bContext *C, struct ARegion *ar, void *cumap_v)
static uiBlock * curvemap_brush_tools_func (bContext *C, struct ARegion *ar, void *cumap_v)
static void curvemap_buttons_redraw (bContext *C, void *UNUSED(arg1), void *UNUSED(arg2))
static void curvemap_buttons_reset (bContext *C, void *cb_v, void *cumap_v)
static void curvemap_buttons_layout (uiLayout *layout, PointerRNA *ptr, char labeltype, int levels, int brush, RNAUpdateCb *cb)
void uiTemplateCurveMapping (uiLayout *layout, PointerRNA *ptr, const char *propname, int type, int levels, int brush)
void uiTemplateColorWheel (uiLayout *layout, PointerRNA *ptr, const char *propname, int value_slider, int lock, int lock_luminosity, int cubic)
static void handle_layer_buttons (bContext *C, void *arg1, void *arg2)
void uiTemplateLayers (uiLayout *layout, PointerRNA *ptr, const char *propname, PointerRNA *used_ptr, const char *used_propname, int active_layer)
static int list_item_icon_get (bContext *C, PointerRNA *itemptr, int rnaicon, int big)
static void list_item_row (bContext *C, uiLayout *layout, PointerRNA *ptr, PointerRNA *itemptr, int i, int rnaicon, PointerRNA *activeptr, PropertyRNA *activeprop, const char *prop_list_id)
void uiTemplateList (uiLayout *layout, bContext *C, PointerRNA *ptr, const char *propname, PointerRNA *activeptr, const char *activepropname, const char *prop_list, int rows, int maxrows, int listtype)
static void operator_call_cb (bContext *C, void *UNUSED(arg1), void *arg2)
static void operator_search_cb (const bContext *C, void *UNUSED(arg), const char *str, uiSearchItems *items)
void uiTemplateOperatorSearch (uiLayout *layout)
static void do_running_jobs (bContext *C, void *UNUSED(arg), int event)
void uiTemplateRunningJobs (uiLayout *layout, bContext *C)
void uiTemplateReportsBanner (uiLayout *layout, bContext *C)
static void keymap_item_modified (bContext *UNUSED(C), void *kmi_p, void *UNUSED(unused))
static void template_keymap_item_properties (uiLayout *layout, const char *title, PointerRNA *ptr)
void uiTemplateKeymapItemProperties (uiLayout *layout, PointerRNA *ptr)
Detailed Description
Definition in file interface_templates.c.
Define Documentation
#define B_BANDCOL 1
Definition at line 1259 of file interface_templates.c.
#define B_CONSTRAINT_CHANGETARGET 6
Definition at line 931 of file interface_templates.c.
Referenced by do_constraint_panels().
#define B_CONSTRAINT_TEST 5
Definition at line 930 of file interface_templates.c.
Referenced by do_constraint_panels(), and draw_constraint().
#define B_DIFF 9
Definition at line 933 of file interface_templates.c.
#define B_MATPRV 1
Definition at line 1146 of file interface_templates.c.
Referenced by do_preview_buttons(), and uiTemplatePreview().
#define B_STOPANIM 3
Definition at line 2532 of file interface_templates.c.
Referenced by do_running_jobs(), and uiTemplateRunningJobs().
#define B_STOPCAST 2
Definition at line 2531 of file interface_templates.c.
Referenced by do_running_jobs(), and uiTemplateRunningJobs().
#define B_STOPCLIP 6
Definition at line 2535 of file interface_templates.c.
Referenced by do_running_jobs(), and uiTemplateRunningJobs().
#define B_STOPCOMPO 4
Definition at line 2533 of file interface_templates.c.
Referenced by do_running_jobs(), and uiTemplateRunningJobs().
#define B_STOPRENDER 1
Definition at line 2530 of file interface_templates.c.
Referenced by do_running_jobs(), and uiTemplateRunningJobs().
#define B_STOPSEQ 5
Definition at line 2534 of file interface_templates.c.
Referenced by do_running_jobs(), and uiTemplateRunningJobs().
#define ERROR_LIBDATA_MESSAGE "Can't edit external libdata"
Definition at line 625 of file interface_templates.c.
Referenced by draw_modifier(), uiTemplateConstraint(), and uiTemplateModifier().
#define REDRAWACTION 4
Definition at line 929 of file interface_templates.c.
Referenced by viewRedrawPost().
#define REDRAWBUTSOBJECT 3
Definition at line 928 of file interface_templates.c.
Referenced by viewRedrawPost().
#define REDRAWIPO 1
Definition at line 926 of file interface_templates.c.
Referenced by viewRedrawPost().
#define REDRAWNLA 2
Definition at line 927 of file interface_templates.c.
Referenced by viewRedrawPost().
#define REMAKEIPO 8
Definition at line 932 of file interface_templates.c.
#define WHEEL_SIZE 100
Definition at line 1921 of file interface_templates.c.
Referenced by uiTemplateColorWheel().
Typedef Documentation
typedef struct RNAUpdateCb RNAUpdateCb
typedef struct TemplateID TemplateID
Function Documentation
static void colorband_add_cb (bContext * C, void * cb_v, void * coba_v) [static]
Definition at line 1261 of file interface_templates.c.
References colorband_element_add(), ColorBand::cur, ColorBand::data, ED_undo_push(), NULL, CBData::pos, rna_update_cb(), and ColorBand::tot.
Referenced by colorband_buttons_large(), and colorband_buttons_small().
static void colorband_buttons_large (uiLayout * layout, uiBlock * block, ColorBand * coba, int xoffs, int yoffs, RNAUpdateCb * cb) [static]
Definition at line 1322 of file interface_templates.c.
References BUT, BUT_COLORBAND, uiBlock::buttons, colorband_add_cb(), colorband_del_cb(), colorband_flip_cb(), colorband_update_cb(), ColorBand::cur, PointerRNA::data, ColorBand::data, PointerRNA::id, IFACE_, ColorBand::ipotype, ListBase::last, MAX2, MEM_dupallocN(), MENU, NULL, NUM, RNAUpdateCb::ptr, RNA_ColorRampElement, RNA_pointer_create(), rna_update_cb(), TIP_, ColorBand::tot, UI_UNIT_Y, uiBlockEndAlign(), uiButSetFunc(), uiButSetNFunc(), uiDefBut(), uiDefButS(), uiItemR(), and uiLayoutRow().
Referenced by colorband_buttons_layout().
static void colorband_buttons_layout (uiLayout * layout, uiBlock * block, ColorBand * coba, rctf * butr, int small, RNAUpdateCb * cb) [static]
Definition at line 1408 of file interface_templates.c.
References colorband_buttons_large(), and colorband_buttons_small().
Referenced by uiTemplateColorRamp().
static void colorband_buttons_small (uiLayout * layout, uiBlock * block, ColorBand * coba, rctf * butr, RNAUpdateCb * cb) [static]
Definition at line 1373 of file interface_templates.c.
References BUT, BUT_COLORBAND, colorband_add_cb(), colorband_del_cb(), colorband_flip_cb(), ColorBand::cur, PointerRNA::data, ColorBand::data, PointerRNA::id, IFACE_, ColorBand::ipotype, MEM_dupallocN(), MENU, NULL, RNAUpdateCb::ptr, RNA_ColorRampElement, RNA_pointer_create(), rna_update_cb(), TIP_, ColorBand::tot, UI_UNIT_Y, uiBlockBeginAlign(), uiBlockEndAlign(), uiButSetNFunc(), uiDefBut(), uiDefButS(), uiItemR(), rctf::xmax, rctf::xmin, and rctf::ymin.
Referenced by colorband_buttons_layout().
static void colorband_del_cb (bContext * C, void * cb_v, void * coba_v) [static]
Definition at line 1277 of file interface_templates.c.
References colorband_element_remove(), ColorBand::cur, ED_undo_push(), NULL, and rna_update_cb().
Referenced by colorband_buttons_large(), and colorband_buttons_small().
static void colorband_flip_cb (bContext * C, void * cb_v, void * coba_v) [static]
Definition at line 1287 of file interface_templates.c.
References ColorBand::cur, ColorBand::data, ED_undo_push(), MAXCOLORBAND, NULL, CBData::pos, rna_update_cb(), and ColorBand::tot.
Referenced by colorband_buttons_large(), and colorband_buttons_small().
static void colorband_update_cb (bContext * UNUSEDC, void * bt_v, void * coba_v) [static]
Definition at line 1310 of file interface_templates.c.
References colorband_update_sort(), ColorBand::cur, PointerRNA::data, ColorBand::data, and uiBut::rnapoin.
Referenced by colorband_buttons_large().
static void constraint_active_func (bContext * UNUSEDC, void * ob_v, void * con_v) [static]
Definition at line 964 of file interface_templates.c.
References ED_object_constraint_set_active().
Referenced by draw_constraint().
static uiBlock* curvemap_brush_tools_func (bContext * C, struct ARegion * ar, void * cumap_v) [static]
Definition at line 1716 of file interface_templates.c.
References BUTM, curvemap_tools_dofunc(), IFACE_, NULL, UI_EMBOSS, UI_RIGHT, UI_UNIT_X, UI_UNIT_Y, uiBeginBlock(), uiBlockSetButmFunc(), uiBlockSetDirection(), uiDefIconTextBut(), uiEndBlock(), and uiTextBoundsBlock().
Referenced by curvemap_buttons_layout().
static void curvemap_buttons_delete (bContext * C, void * cb_v, void * cumap_v) [static]
Definition at line 1622 of file interface_templates.c.
References CurveMapping::cm, CurveMapping::cur, curvemap_remove(), curvemapping_changed(), NULL, rna_update_cb(), and SELECT.
Referenced by curvemap_buttons_layout().
static void curvemap_buttons_layout (uiLayout * layout, PointerRNA * ptr, char labeltype, int levels, int brush, RNAUpdateCb * cb) [static]
Definition at line 1760 of file interface_templates.c.
References BUT, BUT_CURVE, CurveMapping::cm, CUMA_DO_CLIP, CurveMapping::cur, CurveMap::curve, curvemap_brush_tools_func(), curvemap_buttons_delete(), curvemap_buttons_redraw(), curvemap_buttons_reset(), curvemap_buttons_zoom_in(), curvemap_buttons_zoom_out(), curvemap_clipping_func(), curvemap_tools_func(), PointerRNA::data, CurveMapping::flag, IFACE_, MEM_dupallocN(), MIN2, NULL, rna_update_cb(), ROW, size(), split(), TIP_, UI_EMBOSS, UI_EMBOSSN, UI_GRAD_H, UI_ITEM_R_EXPAND, UI_LAYOUT_ALIGN_LEFT, UI_LAYOUT_ALIGN_RIGHT, UI_UNIT_X, UI_UNIT_Y, uiBlockSetEmboss(), uiBlockSetNFunc(), uiButSetFunc(), uiButSetNFunc(), uiDefBut(), uiDefButI(), uiDefIconBlockBut(), uiDefIconBut(), uiItemR(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutGetWidth(), uiLayoutRow(), uiLayoutSetAlignment(), and uiLayoutSplit().
Referenced by uiTemplateCurveMapping().
static void curvemap_buttons_redraw (bContext * C, void * UNUSEDarg1, void * UNUSEDarg2) [static]
Definition at line 1736 of file interface_templates.c.
References CTX_wm_region(), and ED_region_tag_redraw().
Referenced by curvemap_buttons_layout().
static void curvemap_buttons_reset (bContext * C, void * cb_v, void * cumap_v) [static]
Definition at line 1741 of file interface_templates.c.
References CurveMapping::black, CurveMapping::clipr, CurveMapping::cm, CM_TOT, CURVE_PRESET_LINE, curvemap_reset(), CURVEMAP_SLOPE_POSITIVE, curvemapping_changed(), curvemapping_set_black_white(), NULL, CurveMapping::preset, rna_update_cb(), and CurveMapping::white.
Referenced by curvemap_buttons_layout().
static void curvemap_buttons_setclip (bContext * UNUSEDC, void * cumap_v, void * UNUSEDarg) [static]
Definition at line 1615 of file interface_templates.c.
References curvemapping_changed().
Referenced by curvemap_clipping_func().
static void curvemap_buttons_zoom_in (bContext * C, void * cumap_v, void * UNUSEDarg) [static]
Definition at line 1560 of file interface_templates.c.
References CurveMapping::clipr, CTX_wm_region(), CurveMapping::curr, ED_region_tag_redraw(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by curvemap_buttons_layout().
static void curvemap_buttons_zoom_out (bContext * C, void * cumap_v, void * UNUSEDunused) [static]
Definition at line 1578 of file interface_templates.c.
References CurveMapping::clipr, CTX_wm_region(), CUMA_DO_CLIP, CurveMapping::curr, ED_region_tag_redraw(), CurveMapping::flag, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by curvemap_buttons_layout().
static uiBlock* curvemap_clipping_func (bContext * C, struct ARegion * ar, void * cumap_v) [static]
Definition at line 1633 of file interface_templates.c.
References CurveMapping::clipr, CUMA_DO_CLIP, curvemap_buttons_setclip(), CurveMapping::flag, IFACE_, LABEL, NULL, NUM, TOG, UI_EMBOSS, UI_RIGHT, UI_UNIT_X, UI_UNIT_Y, uiBeginBlock(), uiBlockBeginAlign(), uiBlockSetDirection(), uiButSetFunc(), uiDefBut(), uiDefButBitI(), uiDefButF(), uiEndBlock(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by curvemap_buttons_layout().
static void curvemap_tools_dofunc (bContext * C, void * cumap_v, int event) [static]
Definition at line 1661 of file interface_templates.c.
References CurveMapping::clipr, CurveMapping::cm, CTX_wm_region(), CUMA_EXTEND_EXTRAPOLATE, CurveMapping::cur, CurveMapping::curr, curvemap_reset(), curvemap_sethandle(), CURVEMAP_SLOPE_POSITIVE, curvemapping_changed(), ED_region_tag_redraw(), CurveMap::flag, and CurveMapping::preset.
Referenced by curvemap_brush_tools_func(), and curvemap_tools_func().
static uiBlock* curvemap_tools_func (bContext * C, struct ARegion * ar, void * cumap_v) [static]
Definition at line 1694 of file interface_templates.c.
References BUTM, curvemap_tools_dofunc(), IFACE_, NULL, UI_EMBOSS, UI_RIGHT, UI_UNIT_X, UI_UNIT_Y, uiBeginBlock(), uiBlockSetButmFunc(), uiBlockSetDirection(), uiDefIconTextBut(), uiEndBlock(), and uiTextBoundsBlock().
Referenced by curvemap_buttons_layout().
static void do_constraint_panels (bContext * C, void * ob_pt, int event) [static]
Definition at line 935 of file interface_templates.c.
References B_CONSTRAINT_CHANGETARGET, B_CONSTRAINT_TEST, CTX_data_main(), CTX_data_scene(), DAG_id_tag_update(), DAG_scene_sort(), bPose::flag, Object::id, NC_OBJECT, ND_CONSTRAINT, OB_ARMATURE, OB_RECALC_DATA, OB_RECALC_OB, Object::pose, POSE_RECALC, Object::type, and WM_event_add_notifier().
Referenced by draw_constraint().
static void do_preview_buttons (bContext * C, void * arg, int event) [static]
Definition at line 1148 of file interface_templates.c.
References B_MATPRV, NC_MATERIAL, ND_SHADING, and WM_event_add_notifier().
Referenced by uiTemplatePreview().
static void do_running_jobs (bContext * C, void * UNUSEDarg, int event) [static]
Definition at line 2537 of file interface_templates.c.
References B_STOPANIM, B_STOPCAST, B_STOPCLIP, B_STOPCOMPO, B_STOPRENDER, B_STOPSEQ, CTX_wm_area(), CTX_wm_manager(), CTX_wm_screen(), G, NULL, WM_jobs_stop(), WM_OP_INVOKE_SCREEN, and WM_operator_name_call().
Referenced by uiTemplateRunningJobs().
static uiLayout* draw_constraint (uiLayout * layout, Object * ob, bConstraint * con) [static]
Definition at line 970 of file interface_templates.c.
References B_CONSTRAINT_TEST, BLI_strncpy(), BUT, constraint_active_func(), CONSTRAINT_DISABLE, CONSTRAINT_EXPAND, constraint_get_typeinfo(), CONSTRAINT_OFF, CONSTRAINT_PROXY_LOCAL, CONSTRAINT_TYPE_NULL, do_constraint_panels(), bConstraint::flag, get_active_posechannel(), Object::id, LABEL, bConstraintTypeInfo::name, bConstraint::name, bConstraint::next, NULL, bConstraint::prev, proxylocked_constraints_owner(), RNA_Constraint, RNA_pointer_create(), TIP_, bConstraint::type, UI_EMBOSS, UI_EMBOSSN, UI_ITEM_R_ICON_ONLY, uiBlockBeginAlign(), uiBlockClearButLock(), uiBlockEndAlign(), uiBlockSetButLock(), uiBlockSetEmboss(), uiBlockSetFunc(), uiBlockSetHandleFunc(), uiDefBut(), uiDefIconBut(), uiItemL(), uiItemO(), uiItemR(), uiLayoutAbsoluteBlock(), uiLayoutBox(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), uiLayoutSetContextPointer(), uiLayoutSetOperatorContext(), uiLayoutSetRedAlert(), and WM_OP_INVOKE_DEFAULT.
Referenced by uiTemplateConstraint().
static uiLayout* draw_modifier (uiLayout * layout, Scene * scene, Object * ob, ModifierData * md, int index, int cageIndex, int lastCageIndex) [static]
Definition at line 713 of file interface_templates.c.
References BLI_snprintf(), BUT, PartDeflect::deflect, ELEM, ELEM3, ELEM5, eModifierMode_ApplyOnSpline, eModifierMode_Expanded, eModifierMode_OnCage, eModifierMode_Virtual, eModifierType_Cloth, eModifierType_Collision, eModifierType_Fluidsim, eModifierType_Hook, eModifierType_MeshDeform, eModifierType_ParticleSystem, eModifierType_Smoke, eModifierType_Softbody, eModifierType_Surface, eModifierTypeFlag_SupportsEditmode, eModifierTypeType_Constructive, ModifierData::error, ERROR_LIBDATA_MESSAGE, ModifierTypeInfo::flags, Object::id, IFACE_, LABEL, ID::lib, ModifierData::mode, Object::mode, MODIFIER_APPLY_DATA, MODIFIER_APPLY_SHAPE, modifier_can_delete(), modifier_couldBeCage(), modifier_is_simulation(), modifier_nonGeometrical(), modifier_sameTopology(), modifiers_convertToReal(), modifiers_setOnCage(), modifierType_getInfo(), mti, ModifierData::name, NULL, OB_CURVE, OB_FONT, OB_MESH, OB_MODE_PARTICLE_EDIT, OB_SURF, object_data_is_libdata(), ParticleSystem::part, PART_DRAW_GR, PART_DRAW_OB, PART_DRAW_PATH, ParticleSystem::pathcache, Object::pd, ParticleSettings::ren_as, RNA_Modifier, RNA_pointer_create(), RNA_struct_ui_icon(), str, TIP_, TOG, ModifierData::type, Object::type, PointerRNA::type, ModifierTypeInfo::type, UI_BUT_DISABLED, UI_EMBOSS, UI_EMBOSSN, UI_LAYOUT_ALIGN_EXPAND, UI_UNIT_X, UI_UNIT_Y, uiBlockBeginAlign(), uiBlockClearButLock(), uiBlockEndAlign(), uiBlockSetButLock(), uiBlockSetEmboss(), uiButSetFlag(), uiButSetFunc(), uiDefBut(), uiDefIconBut(), uiDefIconButBitI(), uiItemEnumO(), uiItemL(), uiItemO(), uiItemR(), uiItemStringO(), uiLayoutAbsoluteBlock(), uiLayoutBox(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), uiLayoutSetAlignment(), uiLayoutSetContextPointer(), uiLayoutSetOperatorContext(), and WM_OP_INVOKE_DEFAULT.
Referenced by uiTemplateModifier().
static void handle_layer_buttons (bContext * C, void * arg1, void * arg2) [static]
Definition at line 1965 of file interface_templates.c.
References CTX_wm_window(), wmWindow::eventstate, FALSE, GET_INT_FROM_POINTER, i, RNA_property_array_length(), RNA_property_boolean_set_index(), uiBut::rnapoin, uiBut::rnaprop, wmEvent::shift, and TRUE.
Referenced by uiTemplateLayers().
static void id_search_call_cb (bContext * C, void * arg_template, void * item) [static]
Definition at line 103 of file interface_templates.c.
References RNA_id_pointer_create(), RNA_property_pointer_set(), and RNA_property_update().
Referenced by id_search_menu().
static void id_search_cb (const bContext * C, void * arg_template, const char * str, uiSearchItems * items) [static]
Definition at line 118 of file interface_templates.c.
References BLI_strcasestr(), ListBase::first, MAX_ID_NAME, ID::name, name_uiprefix_id(), ID::next, PROP_ID_SELF_CHECK, PROP_POINTER, RNA_id_pointer_create(), RNA_property_flag(), RNA_property_pointer_poll(), RNA_property_type(), ui_id_icon_get(), uiSearchItemAdd(), and USER_HIDE_DOT.
Referenced by id_search_menu().
static uiBlock* id_search_menu (bContext * C, ARegion * ar, void * arg_litem) [static]
Definition at line 157 of file interface_templates.c.
References CTX_wm_window(), PointerRNA::data, uiBut::flag, id_search_call_cb(), id_search_cb(), LABEL, NULL, RNA_property_pointer_get(), UI_BLOCK_LOOP, UI_BLOCK_REDRAW, UI_BLOCK_RET_1, UI_BUT_UNDO, UI_DOWN, UI_EMBOSS, uiBeginBlock(), uiBlockSetDirection(), uiBlockSetFlag(), uiBoundsBlock(), uiButSetFocusOnEnter(), uiButSetSearchFunc(), uiDefBut(), uiDefSearchBut(), uiEndBlock(), and uiSearchBoxhHeight().
Referenced by template_ID().
static void keymap_item_modified (bContext * UNUSEDC, void * kmi_p, void * UNUSEDunused) [static]
Definition at line 2689 of file interface_templates.c.
References NULL, and WM_keyconfig_update_tag().
Referenced by uiTemplateKeymapItemProperties().
static int list_item_icon_get (bContext * C, PointerRNA * itemptr, int rnaicon, int big) [static]
Definition at line 2061 of file interface_templates.c.
References PointerRNA::data, DynamicPaintSurface::format, PointerRNA::id, if(), MOD_DPAINT_SURFACE_F_IMAGESEQ, MOD_DPAINT_SURFACE_F_PTEX, MOD_DPAINT_SURFACE_F_VERTEX, NULL, RNA_DynamicPaintSurface, RNA_MaterialSlot, RNA_pointer_get(), RNA_struct_is_a(), RNA_struct_is_ID(), RNA_TextureSlot, PointerRNA::type, and ui_id_icon_get().
Referenced by list_item_row(), and uiTemplateList().
static void list_item_row (bContext * C, uiLayout * layout, PointerRNA * ptr, PointerRNA * itemptr, int i, int rnaicon, PointerRNA * activeptr, PropertyRNA * activeprop, const char * prop_list_id) [static]
Definition at line 2098 of file interface_templates.c.
References BLI_snprintf(), CTX_data_scene(), PointerRNA::data, DG_LOCK_WEIGHT, dynamicPaint_surfaceHasColorPreview(), bDeformGroup::flag, MovieTrackingObject::flag, KeyBlock::flag, DynamicPaintSurface::flags, give_current_material(), give_node_material(), Material::id, PointerRNA::id, id_type_items, KS_Path::idtype, KEY_RELATIVE, KEYBLOCK_MUTE, list_item_icon_get(), LISTROW, Object::mat, MAX_ID_NAME, MEM_freeN(), MOD_DPAINT_PREVIEW, Object::mode, ID::name, NULL, OB_MESH, OB_MODE_EDIT, OB_SHAPE_EDIT_MODE, OPTION, PROP_STRING, RNA_DynamicPaintSurface, RNA_enum_icon_from_value(), RNA_KeyingSetPath, RNA_MaterialSlot, RNA_MaterialTextureSlot, RNA_MeshLoopColorLayer, RNA_MeshTexturePolyLayer, RNA_MovieTrackingObject, RNA_property_enum_get(), RNA_property_enum_name(), RNA_property_string_get_alloc(), RNA_property_type(), RNA_SceneRenderLayer, RNA_ShapeKey, RNA_struct_find_property(), RNA_struct_is_a(), RNA_struct_name_get_alloc(), RNA_VertexGroup, scene_use_new_shading_nodes(), Object::shapeflag, split(), str, TOG, TRACKING_OBJECT_CAMERA, Object::type, PointerRNA::type, UI_BUT_NO_TOOLTIP, UI_EMBOSS, UI_EMBOSSN, ui_id_icon_get(), UI_UNIT_X, UI_UNIT_Y, uiBlockSetEmboss(), uiButSetFlag(), uiDefButR(), uiDefButR_prop(), uiDefIconButBitC(), uiDefIconButR(), uiItemL(), uiItemR(), uiLayoutGetBlock(), uiLayoutOverlap(), uiLayoutRow(), uiLayoutSetActive(), uiLayoutSplit(), and Material::use_nodes.
Referenced by uiTemplateList().
static int modifier_can_delete (ModifierData * md) [static]
Definition at line 685 of file interface_templates.c.
References eModifierType_ParticleSystem, PART_FLUID, and ModifierData::type.
Referenced by draw_modifier().
static int modifier_is_simulation (ModifierData * md) [static]
Definition at line 696 of file interface_templates.c.
References ELEM7, eModifierType_Cloth, eModifierType_Collision, eModifierType_DynamicPaint, eModifierType_Fluidsim, eModifierType_ParticleSystem, eModifierType_Smoke, eModifierType_Softbody, eModifierType_Surface, and ModifierData::type.
Referenced by draw_modifier().
static void modifiers_convertToReal (bContext * C, void * ob_v, void * md_v) [static]
Definition at line 664 of file interface_templates.c.
References BLI_addhead(), DAG_id_tag_update(), ED_undo_push(), eModifierMode_Virtual, Object::id, ModifierData::mode, modifier_copyData(), modifier_new(), modifier_unique_name(), Object::modifiers, NC_OBJECT, ND_MODIFIER, OB_RECALC_DATA, PAROBJECT, Object::partype, ModifierData::type, and WM_event_add_notifier().
Referenced by draw_modifier().
static void modifiers_setOnCage (bContext * C, void * ob_v, void * md_v) [static]
Definition at line 642 of file interface_templates.c.
References CTX_data_scene(), DAG_id_tag_update(), eModifierMode_OnCage, ListBase::first, i, Object::id, ModifierData::mode, Object::modifiers, modifiers_getCageIndex(), NC_OBJECT, ND_MODIFIER, ModifierData::next, NULL, OB_RECALC_DATA, and WM_event_add_notifier().
Referenced by draw_modifier().
static void operator_call_cb (bContext * C, void * UNUSEDarg1, void * arg2) [static]
Definition at line 2475 of file interface_templates.c.
References wmOperatorType::idname, NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by uiTemplateOperatorSearch().
static void operator_search_cb (const bContext * C, void * UNUSEDarg, const char * str, uiSearchItems * items) [static]
Definition at line 2483 of file interface_templates.c.
References BLI_ghashIterator_free(), BLI_ghashIterator_getValue(), BLI_ghashIterator_isDone(), BLI_ghashIterator_step(), BLI_strcasestr(), BLI_strncpy(), wmOperatorType::idname, len(), wmOperatorType::name, NULL, strlen(), TRUE, uiSearchItemAdd(), WM_key_event_operator_string(), WM_OP_EXEC_DEFAULT, WM_operator_poll(), and WM_operatortype_iter().
Referenced by uiTemplateOperatorSearch().
static void rna_update_cb (bContext * C, void * arg_cb, void * UNUSEDarg) [static]
Definition at line 1249 of file interface_templates.c.
References RNAUpdateCb::prop, RNAUpdateCb::ptr, and RNA_property_update().
Referenced by colorband_add_cb(), colorband_buttons_large(), colorband_buttons_small(), colorband_del_cb(), colorband_flip_cb(), curvemap_buttons_delete(), curvemap_buttons_layout(), curvemap_buttons_reset(), uiTemplateHistogram(), and uiTemplateVectorscope().
static void template_ID (bContext * C, uiLayout * layout, TemplateID * template, StructRNA * type, short idcode, int flag, const char * newop, const char * openop, const char * unlinkop) [static]
Definition at line 341 of file interface_templates.c.
References BLI_snprintf(), BUT, PointerRNA::data, ELEM5, ID::flag, GS, uiBut::icon, id_copy(), ID_GR, id_make_local(), ID_OB, ID_SCE, ID_SCR, id_search_menu(), ID_TE, ID_TXT, IFACE_, ID::lib, LIB_INDIRECT, MEM_dupallocN(), ID::name, NULL, PROP_NEVER_NULL, PROP_NEVER_UNLINK, RNA_property_editable(), RNA_property_flag(), RNA_property_pointer_get(), RNA_struct_ui_icon(), SET_INT_IN_POINTER, template_id_browse_tip(), template_id_cb(), TEX, TIP_, TOG, PointerRNA::type, UI_BUT_DISABLED, UI_BUT_REDALERT, UI_HAS_ICON, UI_ICON_LEFT, UI_ICON_PREVIEW, UI_ID_ADD_NEW, UI_ID_ALONE, UI_ID_BROWSE, UI_ID_DELETE, ui_id_icon_get(), UI_ID_LOCAL, UI_ID_OPEN, UI_ID_PREVIEWS, UI_ID_RENAME, UI_MAX_NAME_STR, UI_UNIT_X, UI_UNIT_Y, uiBlockBeginAlign(), uiBlockEndAlign(), uiButSetDragID(), uiButSetFlag(), uiButSetNFunc(), uiDefBlockButN(), uiDefBut(), uiDefButR(), uiDefIconBut(), uiDefIconButO(), uiDefIconTextBut(), uiDefIconTextButO(), uiLayoutGetBlock(), uiLayoutRow(), uiTemplateTextureShow(), ID::us, WM_OP_INVOKE_DEFAULT, and WM_OP_INVOKE_REGION_WIN.
Referenced by ui_template_id().
static const char* template_id_browse_tip (StructRNA * type) [static]
Definition at line 310 of file interface_templates.c.
References ID_AC, ID_AR, ID_BR, ID_CA, ID_CU, ID_GD, ID_IM, ID_LA, ID_LT, ID_MA, ID_MB, ID_ME, ID_NT, ID_OB, ID_PA, ID_SCE, ID_SCR, ID_SO, ID_SPK, ID_TE, ID_TXT, ID_WO, N_, and RNA_type_to_ID_code().
Referenced by template_ID().
static void template_id_cb (bContext * C, void * arg_litem, void * arg_event) [static]
Definition at line 243 of file interface_templates.c.
References CTX_data_scene(), CTX_wm_window(), PointerRNA::data, ED_object_single_user(), ID::flag, GET_INT_FROM_POINTER, GS, id_make_local(), ID_OB, id_single_user(), id_us_min(), id_us_plus(), LIB_FAKEUSER, ID::name, NC_SCENE, ND_OB_ACTIVE, RNA_property_pointer_get(), RNA_property_pointer_set(), RNA_property_update(), RNA_SceneObjects, RNA_warning, UI_ID_ADD_NEW, UI_ID_ALONE, UI_ID_AUTO_NAME, UI_ID_BROWSE, UI_ID_DELETE, UI_ID_FAKE_USER, UI_ID_LOCAL, UI_ID_OPEN, UI_ID_PIN, and WM_event_add_notifier().
Referenced by template_ID().
static void template_keymap_item_properties (uiLayout * layout, const char * title, PointerRNA * ptr) [static]
Definition at line 2695 of file interface_templates.c.
References PointerRNA::data, NULL, PROP_HIDDEN, PROP_POINTER, RNA_OperatorProperties, RNA_property_flag(), RNA_property_identifier(), RNA_property_pointer_get(), RNA_property_type(), RNA_property_ui_name(), RNA_STRUCT_BEGIN, RNA_STRUCT_END, RNA_struct_is_a(), PointerRNA::type, uiItemL(), uiItemR(), uiItemS(), and uiLayoutColumnFlow().
Referenced by uiTemplateKeymapItemProperties().
void UI_template_fix_linking (void)
Definition at line 76 of file interface_templates.c.
Referenced by uiBlockLayoutResolve().
static void ui_template_id (uiLayout * layout, bContext * C, PointerRNA * ptr, const char * propname, const char * newop, const char * openop, const char * unlinkop, int flag, int prv_rows, int prv_cols) [static]
Definition at line 495 of file interface_templates.c.
References CTX_data_main(), MEM_callocN(), MEM_freeN(), PROP_POINTER, RNA_property_pointer_type(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_type_to_ID_code(), RNA_warning, template_ID(), PointerRNA::type, UI_ID_ADD_NEW, UI_ID_OPEN, uiLayoutRow(), and which_libbase().
Referenced by uiTemplateID(), uiTemplateIDBrowse(), and uiTemplateIDPreview().
void uiIDContextProperty (bContext * C, PointerRNA * ptr, PropertyRNA ** prop)
Definition at line 214 of file interface_templates.c.
References uiBlock::buttons, CTX_wm_region(), ListBase::first, uiBut::flag, uiBut::func_argN, uiBut::next, uiBlock::next, NULL, UI_ACTIVE, UI_BUT_LAST_ACTIVE, and ARegion::uiblocks.
Referenced by act_new_exec(), font_ui_template_init(), font_unlink_exec(), image_new_exec(), image_open_init(), new_material_exec(), new_node_tree_exec(), new_texture_exec(), new_world_exec(), open_init(), sound_open_init(), text_new_exec(), and text_open_init().
void uiTemplateAnyID (uiLayout * layout, PointerRNA * ptr, const char * propname, const char * proptypename, const char * text)
Definition at line 557 of file interface_templates.c.
References PROP_ENUM, PROP_POINTER, RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, PointerRNA::type, UI_ITEM_R_ICON_ONLY, uiItemFullR(), uiItemL(), and uiLayoutRow().
Referenced by graph_panel_driverVar__locDiff(), graph_panel_driverVar__rotDiff(), graph_panel_driverVar__singleProp(), and graph_panel_driverVar__transChan().
void uiTemplateColorRamp (uiLayout * layout, PointerRNA * ptr, const char * propname, int expand)
Definition at line 1416 of file interface_templates.c.
References colorband_buttons_layout(), PointerRNA::data, MEM_callocN(), MEM_freeN(), RNAUpdateCb::prop, PROP_POINTER, RNAUpdateCb::ptr, RNA_ColorRamp, RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_is_a(), PointerRNA::type, uiLayoutAbsoluteBlock(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by node_buts_colorramp().
void uiTemplateColorWheel (uiLayout * layout, PointerRNA * ptr, const char * propname, int value_slider, int lock, int lock_luminosity, int cubic)
Definition at line 1923 of file interface_templates.c.
References uiBut::a2, uiBut::flag, HSVCIRCLE, HSVCUBE, len_v3(), RNA_property_float_get_array(), RNA_property_float_ui_range(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, step(), PointerRNA::type, UI_BUT_COLOR_CUBIC, UI_BUT_COLOR_LOCK, UI_BUT_VEC_SIZE_LOCK, UI_GRAD_V_ALT, uiDefButR_prop(), uiItemS(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), and WHEEL_SIZE.
Referenced by node_buts_rgb(), node_composit_buts_colorbalance(), and node_composit_buts_colorbalance_but().
uiLayout* uiTemplateConstraint (uiLayout * layout, PointerRNA * ptr)
Definition at line 1108 of file interface_templates.c.
References CONSTRAINT_IK_TEMP, CONSTRAINT_TYPE_KINEMATIC, bConstraint::data, data, PointerRNA::data, draw_constraint(), ERROR_LIBDATA_MESSAGE, bKinematicConstraint::flag, GS, Object::id, PointerRNA::id, ID_OB, ID::lib, ID::name, NULL, RNA_Constraint, RNA_struct_is_a(), RNA_warning, bConstraint::type, PointerRNA::type, uiBlockSetButLock(), and uiLayoutGetBlock().
void uiTemplateCurveMapping (uiLayout * layout, PointerRNA * ptr, const char * propname, int type, int levels, int brush)
Definition at line 1888 of file interface_templates.c.
References curvemap_buttons_layout(), PointerRNA::data, MEM_callocN(), MEM_freeN(), RNAUpdateCb::prop, PROP_POINTER, RNAUpdateCb::ptr, RNA_CurveMapping, RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_struct_is_a(), RNA_warning, and PointerRNA::type.
Referenced by image_panel_curves(), node_buts_curvecol(), node_buts_curvevec(), node_buts_time(), and node_composit_buts_huecorrect().
void uiTemplateHeader (uiLayout * layout, bContext * C, int menus)
Definition at line 82 of file interface_templates.c.
References ED_area_header_standardbuttons(), ED_area_header_switchbutton(), and uiLayoutAbsoluteBlock().
void uiTemplateHistogram (uiLayout * layout, PointerRNA * ptr, const char * propname)
Definition at line 1446 of file interface_templates.c.
References PointerRNA::data, Histogram::height, HISTOGRAM, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), NULL, RNAUpdateCb::prop, PROP_POINTER, RNAUpdateCb::ptr, RNA_Histogram, RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_is_a(), rna_update_cb(), PointerRNA::type, UI_UNIT_Y, uiButSetNFunc(), uiDefBut(), uiLayoutAbsoluteBlock(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
void uiTemplateID (uiLayout * layout, bContext * C, PointerRNA * ptr, const char * propname, const char * newop, const char * openop, const char * unlinkop)
Definition at line 535 of file interface_templates.c.
References UI_ID_BROWSE, UI_ID_DELETE, UI_ID_RENAME, and ui_template_id().
Referenced by draw_actuator_sound(), draw_gpencil_panel(), nla_panel_animdata(), node_composit_buts_image(), node_composit_buts_movieclip(), node_composit_buts_moviedistortion(), node_composit_buts_renderlayers(), node_composit_buts_stabilize2d(), node_shader_buts_material(), node_shader_buts_tex_environment(), node_shader_buts_tex_image(), node_texture_buts_image(), uiTemplateImage(), and uiTemplateMovieClip().
void uiTemplateIDBrowse (uiLayout * layout, bContext * C, PointerRNA * ptr, const char * propname, const char * newop, const char * openop, const char * unlinkop)
Definition at line 540 of file interface_templates.c.
References UI_ID_BROWSE, UI_ID_RENAME, and ui_template_id().
Referenced by node_draw_group(), and node_uifunc_group().
void uiTemplateIDPreview (uiLayout * layout, bContext * C, PointerRNA * ptr, const char * propname, const char * newop, const char * openop, const char * unlinkop, int rows, int cols)
Definition at line 545 of file interface_templates.c.
References UI_ID_BROWSE, UI_ID_DELETE, UI_ID_PREVIEWS, UI_ID_RENAME, and ui_template_id().
void uiTemplateKeymapItemProperties (uiLayout * layout, PointerRNA * ptr)
Definition at line 2729 of file interface_templates.c.
References uiBlock::buttons, PointerRNA::data, keymap_item_modified(), ListBase::last, uiBut::next, NULL, RNA_pointer_get(), template_keymap_item_properties(), uiButSetFunc(), and uiLayoutGetBlock().
void uiTemplateLayers (uiLayout * layout, PointerRNA * ptr, const char * propname, PointerRNA * used_ptr, const char * used_propname, int active_layer)
Definition at line 1991 of file interface_templates.c.
References handle_layer_buttons(), NULL, RNA_property_array_length(), RNA_property_boolean_get_index(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, SET_INT_IN_POINTER, TOG, uiBut::type, PointerRNA::type, UI_UNIT_X, UI_UNIT_Y, uiButSetFunc(), uiDefAutoButR(), uiLayoutColumn(), uiLayoutGetBlock(), and uiLayoutRow().
Referenced by draw_actuator_state(), logic_buttons_new(), and uiTemplateHeader3D().
void uiTemplateList (uiLayout * layout, bContext * C, PointerRNA * ptr, const char * propname, PointerRNA * activeptr, const char * activepropname, const char * prop_list, int rows, int maxrows, int listtype)
Definition at line 2295 of file interface_templates.c.
References BLI_snprintf(), CLAMPIS, PointerRNA::data, i, len(), Panel::list_grip_size, list_item_icon_get(), list_item_row(), Panel::list_last_len, Panel::list_scroll, Panel::list_size, LISTROW, max, MAX2, MEM_freeN(), min, MIN2, NULL, NUM, uiBlock::panel, PROP_COLLECTION, PROP_INT, RNA_PROP_BEGIN, RNA_PROP_END, RNA_property_collection_length(), RNA_property_int_get(), RNA_property_int_range(), RNA_property_pointer_type(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_struct_name_get_alloc(), RNA_struct_ui_icon(), RNA_warning, SCROLL, PointerRNA::type, UI_BUT_DISABLED, UI_BUT_NO_TOOLTIP, UI_UNIT_X, UI_UNIT_Y, uiButSetFlag(), uiDefButI(), uiDefIconButR_prop(), uiDefIconTextButR_prop(), uiItemL(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutListBox(), and uiLayoutRow().
Referenced by node_composit_buts_file_output_details().
uiLayout* uiTemplateModifier (uiLayout * layout, bContext * C, PointerRNA * ptr)
Definition at line 880 of file interface_templates.c.
References CTX_data_scene(), PointerRNA::data, draw_modifier(), eModifierMode_Virtual, ERROR_LIBDATA_MESSAGE, GS, i, Object::id, PointerRNA::id, ID_OB, ID::lib, modifiers_getCageIndex(), modifiers_getVirtualModifierList(), ID::name, ModifierData::next, NULL, RNA_Modifier, RNA_struct_is_a(), RNA_warning, PointerRNA::type, uiBlockSetButLock(), and uiLayoutGetBlock().
void uiTemplateOperatorSearch (uiLayout * layout)
Definition at line 2515 of file interface_templates.c.
References NULL, operator_call_cb(), operator_search_cb(), UI_UNIT_X, UI_UNIT_Y, uiBlockSetCurLayout(), uiButSetSearchFunc(), uiDefSearchBut(), and uiLayoutGetBlock().
void uiTemplatePathBuilder (uiLayout * layout, PointerRNA * ptr, const char * propname, PointerRNA * UNUSEDroot_ptr, const char * text)
Definition at line 602 of file interface_templates.c.
References PROP_STRING, RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, PointerRNA::type, uiItemR(), and uiLayoutRow().
void uiTemplatePreview (uiLayout * layout, ID * id, int show_buttons, ID * parent, MTex * slot)
Definition at line 1157 of file interface_templates.c.
References B_MATPRV, BUT_EXTRA, do_preview_buttons(), ED_preview_draw(), ELEM4, GS, ID_LA, ID_MA, ID_TE, ID_WO, IFACE_, ID::name, NULL, RNA_Material, RNA_pointer_create(), RNA_Texture, RNA_warning, ROW, TEX_PR_BOTH, TEX_PR_OTHER, TEX_PR_TEXTURE, UI_ITEM_R_EXPAND, UI_UNIT_X, UI_UNIT_Y, uiBlockSetDrawExtraFunc(), uiBlockSetHandleFunc(), uiDefBut(), uiDefButS(), uiItemR(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), uiLayoutSetKeepAspect(), and uiLayoutSetScaleX().
void uiTemplateReportsBanner (uiLayout * layout, bContext * C)
Definition at line 2623 of file interface_templates.c.
References BKE_reports_last_displayable(), BLF_width(), BUT, ReportTimerInfo::col, uiBut::col, CTX_wm_reports(), wmTimer::customdata, ListBase::first, FTOCHAR, ReportTimerInfo::greyscale, if(), LABEL, ListBase::last, ReportList::list, MAX2, Report::message, MIN2, NULL, ReportList::reporttimer, rgb_float_to_uchar(), ROUNDBOX, RPT_ERROR_ALL, RPT_INFO_ALL, RPT_WARNING_ALL, TIP_, Report::type, UI_EMBOSS, UI_EMBOSSN, UI_GetStyle(), UI_UNIT_X, UI_UNIT_Y, uiBlockBeginAlign(), uiBlockEndAlign(), uiBlockSetEmboss(), uiDefBut(), uiDefIconBut(), uiDefIconButO(), uiFontStyle::uifont_id, uiLayoutAbsolute(), uiLayoutGetBlock(), uiStyle::widget, ReportTimerInfo::widthfac, and WM_OP_INVOKE_REGION_WIN.
void uiTemplateRunningJobs (uiLayout * layout, bContext * C)
Definition at line 2561 of file interface_templates.c.
References bScreen::animtimer, B_STOPANIM, B_STOPCAST, B_STOPCLIP, B_STOPCOMPO, B_STOPRENDER, B_STOPSEQ, BUT, CTX_data_main(), CTX_wm_area(), CTX_wm_manager(), CTX_wm_screen(), do_running_jobs(), Scene::id, IFACE_, ID::next, NULL, PROGRESSBAR, SPACE_CLIP, SPACE_NODE, SPACE_SEQ, ScrArea::spacetype, TIP_, UI_UNIT_X, UI_UNIT_Y, uiBlockSetCurLayout(), uiBlockSetHandleFunc(), uiDefBut(), uiDefIconBut(), uiDefIconTextBut(), uiLayoutAbsolute(), uiLayoutGetBlock(), uiLayoutRow(), WM_jobs_name(), WM_jobs_progress(), and WM_jobs_test().
void uiTemplateVectorscope (uiLayout * layout, PointerRNA * ptr, const char * propname)
Definition at line 1522 of file interface_templates.c.
References PointerRNA::data, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), NULL, RNAUpdateCb::prop, PROP_POINTER, RNAUpdateCb::ptr, RNA_property_pointer_get(), RNA_property_type(), RNA_Scopes, RNA_struct_find_property(), RNA_struct_is_a(), rna_update_cb(), PointerRNA::type, UI_UNIT_Y, uiButSetNFunc(), uiDefBut(), uiLayoutAbsoluteBlock(), Scopes::vecscope_height, VECTORSCOPE, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
void uiTemplateWaveform (uiLayout * layout, PointerRNA * ptr, const char * propname)
Definition at line 1485 of file interface_templates.c.
References PointerRNA::data, MEM_callocN(), MEM_freeN(), RNAUpdateCb::prop, PROP_POINTER, RNAUpdateCb::ptr, RNA_property_pointer_get(), RNA_property_type(), RNA_Scopes, RNA_struct_find_property(), RNA_struct_is_a(), PointerRNA::type, UI_UNIT_Y, uiDefBut(), uiLayoutAbsoluteBlock(), WAVEFORM, Scopes::wavefrm_height, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.