Blender: anim_deps.c File Reference
anim_deps.c File Reference
animation
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_anim_types.h"
#include "DNA_armature_types.h"
#include "DNA_object_types.h"
#include "DNA_node_types.h"
#include "DNA_scene_types.h"
#include "DNA_sequence_types.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_animsys.h"
#include "BKE_action.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_global.h"
#include "BKE_node.h"
#include "BKE_sequencer.h"
#include "BKE_utildefines.h"
#include "RNA_access.h"
#include "ED_anim_api.h"
Functions
void ANIM_list_elem_update (Scene *scene, bAnimListElem *ale)
void ANIM_id_update (Scene *UNUSED(scene), ID *id)
static void animchan_sync_group (bAnimContext *UNUSED(ac), bAnimListElem *ale)
static void animchan_sync_fcurve (bAnimContext *UNUSED(ac), bAnimListElem *ale)
void ANIM_sync_animchannels_to_data (const bContext *C)
Detailed Description
Definition in file anim_deps.c.
Function Documentation
void ANIM_id_update (Scene * UNUSEDscene, ID * id)
Definition at line 103 of file anim_deps.c.
References ADT_RECALC_ANIM, BKE_animdata_from_id(), DAG_id_tag_update(), OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, and AnimData::recalc.
Referenced by recalcData_nla().
void ANIM_list_elem_update (Scene * scene, bAnimListElem * ale)
Definition at line 64 of file anim_deps.c.
References ADT_RECALC_ANIM, ALE_FCURVE, BKE_animdata_from_id(), DAG_id_tag_update(), bAnimListElem::datatype, G, bAnimListElem::id, if(), bAnimListElem::key_data, NULL, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, AnimData::recalc, RNA_id_pointer_create(), FCurve::rna_path, RNA_path_resolve(), and RNA_property_update_main().
Referenced by animchannels_enable_exec().
void ANIM_sync_animchannels_to_data (const bContext * C)
Definition at line 244 of file anim_deps.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), animchan_sync_fcurve(), animchan_sync_group(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMTYPE_FCURVE, ANIMTYPE_GROUP, BLI_freelistN(), bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, bAnimListElem::next, NULL, and bAnimListElem::type.
Referenced by action_refresh(), and graph_refresh().
static void animchan_sync_fcurve (bAnimContext * UNUSEDac, bAnimListElem * ale) [static]
Definition at line 161 of file anim_deps.c.
References BLI_getQuotedStr(), bPoseChannel::bone, BONE_SELECTED, bAnimListElem::data, ELEM3, FALSE, FCURVE_SELECTED, Sequence::flag, bNode::flag, FCurve::flag, Bone::flag, get_pose_channel(), get_seq_by_name(), GS, bAnimListElem::id, ID_NT, ID_OB, ID_SCE, if(), MEM_freeN(), NODE_SELECT, nodeFindNodebyName(), NULL, Object::pose, FCurve::rna_path, SELECT, seq_give_editing(), and Editing::seqbasep.
Referenced by ANIM_sync_animchannels_to_data().
static void animchan_sync_group (bAnimContext * UNUSEDac, bAnimListElem * ale) [static]
Definition at line 128 of file anim_deps.c.
References AGRP_SELECTED, bPoseChannel::bone, BONE_SELECTED, bAnimListElem::data, ELEM, bActionGroup::flag, Bone::flag, get_pose_channel(), GS, bAnimListElem::id, ID_OB, if(), bActionGroup::name, NULL, and Object::pose.
Referenced by ANIM_sync_animchannels_to_data().