Blender: MT_Tuple2 Class Reference
MT_Tuple2 Class Reference
#include <MT_Tuple2.h>
Public Member Functions
MT_Tuple2 ()
MT_Tuple2 (const float *vv)
MT_Tuple2 (const double *vv)
MT_Tuple2 (MT_Scalar xx, MT_Scalar yy)
MT_Scalar & operator[] (int i)
const MT_Scalar & operator[] (int i) const
MT_Scalar & x ()
const MT_Scalar & x () const
MT_Scalar & y ()
const MT_Scalar & y () const
MT_Scalar & u ()
const MT_Scalar & u () const
MT_Scalar & v ()
const MT_Scalar & v () const
MT_Scalar * getValue ()
const MT_Scalar * getValue () const
void getValue (float *vv) const
void getValue (double *vv) const
void setValue (const float *vv)
void setValue (const double *vv)
void setValue (MT_Scalar xx, MT_Scalar yy)
Protected Attributes
MT_Scalar m_co [2]
Detailed Description
Definition at line 53 of file MT_Tuple2.h.
Constructor & Destructor Documentation
MT_Tuple2::MT_Tuple2 () [inline]
Definition at line 55 of file MT_Tuple2.h.
MT_Tuple2::MT_Tuple2 (const float * vv) [inline]
Definition at line 56 of file MT_Tuple2.h.
References setValue().
MT_Tuple2::MT_Tuple2 (const double * vv) [inline]
Definition at line 57 of file MT_Tuple2.h.
References setValue().
MT_Tuple2::MT_Tuple2 (MT_Scalar xx, MT_Scalar yy) [inline]
Definition at line 58 of file MT_Tuple2.h.
References setValue().
Member Function Documentation
MT_Scalar* MT_Tuple2::getValue () [inline]
Definition at line 75 of file MT_Tuple2.h.
References m_co.
Referenced by RAS_TexVert::RAS_TexVert(), BL_Shader::SetUniform(), RAS_TexVert::SetUV(), and RAS_TexVert::SetUV2().
const MT_Scalar* MT_Tuple2::getValue () const [inline]
Definition at line 76 of file MT_Tuple2.h.
References m_co.
void MT_Tuple2::getValue (float * vv) const [inline]
Definition at line 78 of file MT_Tuple2.h.
References m_co.
void MT_Tuple2::getValue (double * vv) const [inline]
Definition at line 82 of file MT_Tuple2.h.
References m_co.
MT_Scalar& MT_Tuple2::operator[] (int i) [inline]
Definition at line 60 of file MT_Tuple2.h.
References i, and m_co.
const MT_Scalar& MT_Tuple2::operator[] (int i) const [inline]
Definition at line 61 of file MT_Tuple2.h.
References i, and m_co.
void MT_Tuple2::setValue (const double * vv) [inline]
Definition at line 90 of file MT_Tuple2.h.
References m_co.
void MT_Tuple2::setValue (MT_Scalar xx, MT_Scalar yy) [inline]
Definition at line 94 of file MT_Tuple2.h.
References m_co.
void MT_Tuple2::setValue (const float * vv) [inline]
Definition at line 86 of file MT_Tuple2.h.
References m_co.
Referenced by BL_ConvertMesh(), ConvertMaterial(), MT_Tuple2(), and KX_RayCast::reportHit().
MT_Scalar& MT_Tuple2::u () [inline]
Definition at line 69 of file MT_Tuple2.h.
References m_co.
const MT_Scalar& MT_Tuple2::u () const [inline]
Definition at line 70 of file MT_Tuple2.h.
References m_co.
MT_Scalar& MT_Tuple2::v () [inline]
Definition at line 72 of file MT_Tuple2.h.
References m_co.
const MT_Scalar& MT_Tuple2::v () const [inline]
Definition at line 73 of file MT_Tuple2.h.
References m_co.
MT_Scalar& MT_Tuple2::x () [inline]
Definition at line 63 of file MT_Tuple2.h.
References m_co.
Referenced by KX_ObstacleSimulationTOI_rays::sampleRVO().
const MT_Scalar& MT_Tuple2::x () const [inline]
Definition at line 64 of file MT_Tuple2.h.
References m_co.
MT_Scalar& MT_Tuple2::y () [inline]
Definition at line 66 of file MT_Tuple2.h.
References m_co.
Referenced by KX_ObstacleSimulationTOI_rays::sampleRVO().
const MT_Scalar& MT_Tuple2::y () const [inline]
Definition at line 67 of file MT_Tuple2.h.
References m_co.
Member Data Documentation
MT_Scalar MT_Tuple2::m_co[2] [protected]
Definition at line 99 of file MT_Tuple2.h.
Referenced by MT_Vector2::absolute(), MT_Vector2::dot(), getValue(), MT_Point2::lerp(), MT_Vector2::operator*=(), MT_Point2::operator+=(), MT_Vector2::operator+=(), MT_Point2::operator-=(), MT_Vector2::operator-=(), MT_Point2::operator=(), operator[](), MT_Vector2::scale(), MT_Vector2::scaled(), setValue(), u(), v(), x(), and y().
The documentation for this class was generated from the following file:
MT_Tuple2.h