Blender: image_gen.c File Reference
image_gen.c File Reference
blenkernel
#include <math.h>
#include <stdlib.h>
#include "BKE_image.h"
#include "BLI_math_color.h"
#include "BLI_math_base.h"
#include "BLF_api.h"
Defines
#define BLEND_FLOAT(real, add) (real+add <= 1.0f) ? (real+add) : 1.0f
#define BLEND_CHAR(real, add) ((real + (char)(add * 255.0f)) <= 255) ? (real + (char)(add * 255.0f)) : 255
Functions
void BKE_image_buf_fill_color (unsigned char *rect, float *rect_float, int width, int height, const float color[4])
void BKE_image_buf_fill_checker (unsigned char *rect, float *rect_float, int width, int height)
static void checker_board_color_fill (unsigned char *rect, float *rect_float, int width, int height)
static void checker_board_color_tint (unsigned char *rect, float *rect_float, int width, int height, int size, float blend)
static void checker_board_grid_fill (unsigned char *rect, float *rect_float, int width, int height, float blend)
static void checker_board_text (unsigned char *rect, float *rect_float, int width, int height, int step, int outline)
void BKE_image_buf_fill_checker_color (unsigned char *rect, float *rect_float, int width, int height)
Detailed Description
Definition in file image_gen.c.
Define Documentation
#define BLEND_CHAR (real, add) ((real + (char)(add * 255.0f)) <= 255) ? (real + (char)(add * 255.0f)) : 255
Definition at line 160 of file image_gen.c.
Referenced by checker_board_color_tint(), and checker_board_grid_fill().
#define BLEND_FLOAT (real, add) (real+add <= 1.0f) ? (real+add) : 1.0f
Definition at line 159 of file image_gen.c.
Referenced by checker_board_color_tint(), and checker_board_grid_fill().
Function Documentation
void BKE_image_buf_fill_checker (unsigned char * rect, float * rect_float, int width, int height)
Definition at line 69 of file image_gen.c.
References fabs(), floorf, fmodf, g, hsv_to_rgb(), and powf.
Referenced by add_ibuf_size().
void BKE_image_buf_fill_checker_color (unsigned char * rect, float * rect_float, int width, int height)
Definition at line 338 of file image_gen.c.
References checker_board_color_fill(), checker_board_color_tint(), checker_board_grid_fill(), and checker_board_text().
Referenced by add_ibuf_size().
void BKE_image_buf_fill_color (unsigned char * rect, float * rect_float, int width, int height, const float color[4])
Definition at line 36 of file image_gen.c.
References copy_v4_v4(), and rgba_float_to_uchar().
Referenced by add_ibuf_size().
static void checker_board_color_fill (unsigned char * rect, float * rect_float, int width, int height) [static]
Definition at line 162 of file image_gen.c.
References g, hsv_to_rgb(), and power_of_2_max_i().
Referenced by BKE_image_buf_fill_checker_color().
static void checker_board_color_tint (unsigned char * rect, float * rect_float, int width, int height, int size, float blend) [static]
Definition at line 202 of file image_gen.c.
References BLEND_CHAR, and BLEND_FLOAT.
Referenced by BKE_image_buf_fill_checker_color().
static void checker_board_grid_fill (unsigned char * rect, float * rect_float, int width, int height, float blend) [static]
Definition at line 250 of file image_gen.c.
References BLEND_CHAR, and BLEND_FLOAT.
Referenced by BKE_image_buf_fill_checker_color().
static void checker_board_text (unsigned char * rect, float * rect_float, int width, int height, int step, int outline) [static]
Definition at line 283 of file image_gen.c.
References BLF_buffer(), BLF_buffer_col(), BLF_draw_buffer(), blf_mono_font, BLF_position(), BLF_size(), mono, NULL, and step().
Referenced by BKE_image_buf_fill_checker_color().