Blender: KDL::Frame2 Class Reference
KDL::Frame2 Class Reference
#include <frames.hpp>
Public Member Functions
Frame2 (const Rotation2 &R, const Vector2 &V)
Frame2 (const Vector2 &V)
Frame2 (const Rotation2 &R)
Frame2 (void)
Frame2 (const Frame2 &arg)
void Make4x4 (double *d)
double operator() (int i, int j)
double operator() (int i, int j) const
void SetInverse ()
Frame2 Inverse () const
Vector2 Inverse (const Vector2 &arg) const
Frame2 & operator= (const Frame2 &arg)
Vector2 operator* (const Vector2 &arg)
void SetIdentity ()
void Integrate (const Twist &t_this, double frequency)
Static Public Member Functions
static Frame2 Identity ()
Public Attributes
Vector2 p
origine of the Frame
Rotation2 M
Orientation of the Frame.
Friends
Frame2 operator* (const Frame2 &lhs, const Frame2 &rhs)
bool Equal (const Frame2 &a, const Frame2 &b, double eps=epsilon)
Detailed Description
A 2D frame class, for further documentation see the Frames class for methods with unchanged semantics.
Definition at line 1031 of file frames.hpp.
Constructor & Destructor Documentation
IMETHOD Frame2::Frame2 (const Rotation2 & R, const Vector2 & V) [inline]
Definition at line 952 of file frames.inl.
References M, p, R, and V.
IMETHOD Frame2::Frame2 (const Vector2 & V) [inline, explicit]
Definition at line 946 of file frames.inl.
References Identity(), M, p, and V.
IMETHOD Frame2::Frame2 (const Rotation2 & R) [inline, explicit]
Definition at line 940 of file frames.inl.
References M, p, R, and KDL::Vector2::Zero().
KDL::Frame2::Frame2 (void) [inline]
IMETHOD Frame2::Frame2 (const Frame2 & arg) [inline]
Definition at line 1001 of file frames.inl.
Member Function Documentation
static Frame2 KDL::Frame2::Identity () [inline, static]
Definition at line 1062 of file frames.hpp.
References SetIdentity().
Referenced by Frame2().
void Frame::Integrate (const Twist & t_this, double frequency) [inline]
Definition at line 620 of file frames.inl.
References KDL::epsilon, KDL::Frame::Frame(), KDL::Frame::M, KDL::Vector::Norm(), KDL::Frame::p, KDL::Rotation::Rot(), KDL::Twist::rot, and KDL::Twist::vel.
Frame2 KDL::Frame2::Inverse () const [inline]
Vector2 KDL::Frame2::Inverse (const Vector2 & arg) const [inline]
void KDL::Frame2::Make4x4 (double * d) [inline]
IMETHOD double Frame2::operator() (int i, int j) [inline]
Treats a frame as a 3x3 matrix and returns element i,j Access to elements 0..2,0..2, bounds are checked when NDEBUG is not set
Definition at line 1006 of file frames.inl.
References FRAMES_CHECKI, M, and p.
double KDL::Frame2::operator() (int i, int j) const [inline]
Treats a frame as a 4x4 matrix and returns element i,j Access to elements 0..3,0..3, bounds are checked when NDEBUG is not set
IMETHOD Vector2 Frame2::operator* (const Vector2 & arg) [inline]
Definition at line 963 of file frames.inl.
References M, and p.
Frame2& KDL::Frame2::operator= (const Frame2 & arg) [inline]
IMETHOD void Frame2::SetIdentity () [inline]
Definition at line 918 of file frames.inl.
Referenced by Identity().
IMETHOD void Frame2::SetInverse () [inline]
Definition at line 664 of file frames.inl.
References KDL::Rotation::data.
Friends And Related Function Documentation
bool Equal (const Frame2 & a, const Frame2 & b, double eps = epsilon) [friend]
Frame2 operator* (const Frame2 & lhs, const Frame2 & rhs) [friend]
Member Data Documentation
Rotation2 KDL::Frame2::M
Orientation of the Frame.
Definition at line 1035 of file frames.hpp.
Referenced by Frame2(), operator()(), operator*(), KDL::operator<<(), and KDL::operator>>().
Vector2 KDL::Frame2::p
origine of the Frame
Definition at line 1034 of file frames.hpp.
Referenced by Frame2(), operator()(), operator*(), KDL::operator<<(), and KDL::operator>>().
The documentation for this class was generated from the following files:
frames.hpp
frames.inl