Blender: bmo_slide.c File Reference
bmo_slide.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "BKE_global.h"
#include "BLI_math.h"
#include "bmesh.h"
#include "intern/bmesh_operators_private.h"
Defines
#define EDGE_MARK 1
#define VERT_MARK 2
Functions
void bmo_vertex_slide_exec (BMesh *bm, BMOperator *op)
Detailed Description
Definition in file bmo_slide.c.
Define Documentation
#define EDGE_MARK 1
Definition at line 36 of file bmo_slide.c.
Referenced by bmo_vertex_slide_exec().
#define VERT_MARK 2
Definition at line 37 of file bmo_slide.c.
Referenced by bmo_vertex_slide_exec().
Function Documentation
void bmo_vertex_slide_exec (BMesh * bm, BMOperator * op)
Definition at line 43 of file bmo_slide.c.
References BM_EDGE, BM_edge_other_vert(), BM_EDGES_OF_VERT, BM_ITER_ELEM, BM_VERT, BM_vert_in_edge(), BMERR_INVALID_SELECTION, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_error_raise(), BMO_ITER, BMO_iter_new(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMVert::co, EDGE_MARK, G, G_DEBUG, BMHeader::htype, interp_v3_v3v3(), and VERT_MARK.