Blender: logmemfile.c File Reference
logmemfile.c File Reference
Cineon
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "logImageCore.h"
#include "logmemfile.h"
Functions
int logimage_fseek (void *logfile, intptr_t offsett, int origin)
int logimage_fwrite (void *buffer, unsigned int size, unsigned int count, void *logfile)
int logimage_fread (void *buffer, unsigned int size, unsigned int count, void *logfile)
Detailed Description
Definition in file logmemfile.c.
Function Documentation
int logimage_fread (void * buffer, unsigned int size, unsigned int count, void * logfile)
Definition at line 67 of file logmemfile.c.
References _Log_Image_File_t_::file, i, _Log_Image_File_t_::memcursor, and size().
Referenced by cineonGetRow(), cineonGetRowBytes(), cineonOpen(), cineonOpenFromMem(), dpxGetRowBytes(), and intern_dpxOpen().
int logimage_fseek (void * logfile, intptr_t offsett, int origin)
Definition at line 32 of file logmemfile.c.
References _Log_Image_File_t_::file, fseek, _Log_Image_File_t_::membuffer, _Log_Image_File_t_::membuffersize, and _Log_Image_File_t_::memcursor.
Referenced by cineonGetRow(), cineonGetRowBytes(), cineonOpen(), cineonOpenFromMem(), cineonSetRow(), cineonSetRowBytes(), dpxGetRowBytes(), dpxSetRowBytes(), and intern_dpxOpen().
int logimage_fwrite (void * buffer, unsigned int size, unsigned int count, void * logfile)
Definition at line 57 of file logmemfile.c.
References _Log_Image_File_t_::file.