Blender: bpy_app_handlers.h File Reference
bpy_app_handlers.h File Reference
Python RNA and Operators
Functions
PyObject * BPY_app_handlers_struct (void)
Detailed Description
Definition in file bpy_app_handlers.h.
Function Documentation
PyObject* BPY_app_handlers_struct (void)
Definition at line 196 of file bpy_app_handlers.c.
References bCallbackFuncStore::alloc, app_cb_info_desc, bCallbackFuncStore::arg, BlenderAppCbType, BLI_add_cb(), BLI_assert, BLI_CB_EVT_TOT, bpy_app_generic_callback(), bCallbackFuncStore::func, make_app_cb_info(), NULL, and SET_INT_IN_POINTER.
Referenced by make_app_info().