Blender: node_texture_valToNor.c File Reference
node_texture_valToNor.c File Reference
texnodes
#include "node_texture_util.h"
#include "NOD_texture.h"
Functions
static void normalfn (float *out, TexParams *p, bNode *UNUSED(node), bNodeStack **in, short thread)
static void exec (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_tex_valtonor (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate inputs []
static bNodeSocketTemplate outputs []
Detailed Description
Definition in file node_texture_valToNor.c.
Function Documentation
static void exec (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 78 of file node_texture_valToNor.c.
References normalfn(), and tex_output().
Referenced by register_node_type_tex_valtonor().
static void normalfn (float * out, TexParams * p, bNode * UNUSEDnode, bNodeStack ** in, short thread) [static]
Definition at line 47 of file node_texture_valToNor.c.
References co, TexParams::co, p, and tex_input_value().
Referenced by exec().
void register_node_type_tex_valtonor (bNodeTreeType * ttype)
Definition at line 83 of file node_texture_valToNor.c.
References exec(), NODE_CLASS_CONVERTOR, NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_VALTONOR.
Referenced by registerTextureNodes().
Variable Documentation
bNodeSocketTemplate inputs[] [static]
Initial value:
 {
    { SOCK_FLOAT, 1, "Val",   0.0f,   0.0f, 0.0f, 1.0f,  0.0f,   1.0f, PROP_NONE },
    { SOCK_FLOAT, 1, "Nabla", 0.025f, 0.0f, 0.0f, 0.0f,  0.001f, 0.1f, PROP_UNSIGNED },
    { -1, 0, "" }
}
Definition at line 36 of file node_texture_valToNor.c.
bNodeSocketTemplate outputs[] [static]
Initial value:
 {
    { SOCK_VECTOR, 0, "Normal" },
    { -1, 0, "" }
}
Definition at line 42 of file node_texture_valToNor.c.