Blender: node_composite_blur.c File Reference
node_composite_blur.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static float * make_gausstab (int filtertype, int rad)
static float * make_bloomtab (int rad)
static void blur_single_image (bNode *node, CompBuf *new, CompBuf *img, float scale)
static void bloom_with_reference (CompBuf *new, CompBuf *img, CompBuf *UNUSED(ref), float UNUSED(fac), NodeBlurData *nbd)
static void bokeh_single_image (bNode *node, CompBuf *new, CompBuf *img, float fac)
static void blur_with_reference (bNode *node, CompBuf *new, CompBuf *img, CompBuf *ref)
static void node_composit_exec_blur (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_blur (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_blur (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_blur_in []
static bNodeSocketTemplate cmp_node_blur_out []
Detailed Description
Definition in file node_composite_blur.c.
Function Documentation
static void bloom_with_reference (CompBuf * new, CompBuf * img, CompBuf * UNUSEDref, float UNUSEDfac, NodeBlurData * nbd) [static]
Definition at line 211 of file node_composite_blur.c.
References alloc_compbuf(), CB_VAL, free_compbuf(), i, if(), make_bloomtab(), MAX2, MEM_freeN(), MEM_mallocN(), CompBuf::rect, NodeBlurData::sizex, NodeBlurData::sizey, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_blur().
static void blur_single_image (bNode * node, CompBuf * new, CompBuf * img, float scale) [static]
Definition at line 88 of file node_composite_blur.c.
References alloc_compbuf(), bNode::exec, NodeBlurData::filtertype, free_compbuf(), i, if(), make_gausstab(), MEM_freeN(), NODE_BREAK, CompBuf::rect, NodeBlurData::sizex, NodeBlurData::sizey, bNode::storage, sum(), CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by blur_with_reference(), and node_composit_exec_blur().
static void blur_with_reference (bNode * node, CompBuf * new, CompBuf * img, CompBuf * ref) [static]
Definition at line 445 of file node_composite_blur.c.
References alloc_compbuf(), blur_single_image(), CB_VAL, compbuf_get_pixel(), copy_v4_v4(), bNode::exec, NodeBlurData::filtertype, free_compbuf(), i, if(), make_gausstab(), MAX2, MEM_freeN(), MEM_mallocN(), NODE_BREAK, CompBuf::rect, NodeBlurData::sizex, NodeBlurData::sizey, bNode::storage, sum(), CompBuf::type, typecheck_compbuf(), CompBuf::x, CompBuf::xof, CompBuf::xrad, CompBuf::y, CompBuf::yof, and CompBuf::yrad.
Referenced by node_composit_exec_blur().
static void bokeh_single_image (bNode * node, CompBuf * new, CompBuf * img, float fac) [static]
Definition at line 347 of file node_composite_blur.c.
References bNode::exec, NodeBlurData::filtertype, i, if(), MEM_freeN(), MEM_mallocN(), NODE_BREAK, NULL, RE_filter_value(), CompBuf::rect, NodeBlurData::sizex, NodeBlurData::sizey, sqrt(), bNode::storage, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_blur().
static float* make_bloomtab (int rad) [static]
Definition at line 70 of file node_composite_blur.c.
References fabsf, i, MEM_mallocN(), and powf.
Referenced by bloom_with_reference().
static float* make_gausstab (int filtertype, int rad) [static]
Definition at line 47 of file node_composite_blur.c.
References i, MEM_mallocN(), RE_filter_value(), and sum().
Referenced by blur_single_image(), and blur_with_reference().
static void node_composit_exec_blur (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 575 of file node_composite_blur.c.
References alloc_compbuf(), NodeBlurData::aspect, bloom_with_reference(), blur_single_image(), blur_with_reference(), NodeBlurData::bokeh, bokeh_single_image(), CB_RGBA, CB_VAL, CB_VEC2, CB_VEC3, CMP_NODE_BLUR_ASPECT_NONE, CMP_NODE_BLUR_ASPECT_X, CMP_NODE_BLUR_ASPECT_Y, bNodeStack::data, dupalloc_compbuf(), bNode::exec, NodeBlurData::filtertype, free_compbuf(), NodeBlurData::gamma, gamma_correct_compbuf(), generate_preview(), bNodeStack::hasoutput, IIR_gauss(), NodeBlurData::image_in_height, NodeBlurData::image_in_width, NODE_BREAK, NULL, pass_on_compbuf(), NodeBlurData::percentx, NodeBlurData::percenty, R_FILTER_FAST_GAUSS, NodeBlurData::relative, NodeBlurData::sizex, NodeBlurData::sizey, bNode::storage, CompBuf::type, typecheck_compbuf(), bNodeStack::vec, CompBuf::x, CompBuf::xof, CompBuf::y, and CompBuf::yof.
Referenced by register_node_type_cmp_blur().
static void node_composit_init_blur (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 720 of file node_composite_blur.c.
References MEM_callocN(), and bNode::storage.
Referenced by register_node_type_cmp_blur().
void register_node_type_cmp_blur (bNodeTreeType * ttype)
Definition at line 725 of file node_composite_blur.c.
References CMP_NODE_BLUR, NODE_CLASS_OP_FILTER, node_composit_exec_blur(), node_composit_init_blur(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_blur_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   SOCK_FLOAT, 1, "Size",          1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_FACTOR},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_composite_blur.c.
bNodeSocketTemplate cmp_node_blur_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 42 of file node_composite_blur.c.