Blender: btSoftColliders::CollideCL_RS Struct Reference
btSoftColliders::CollideCL_RS Struct Reference
#include <btSoftBodyInternals.h>
Public Member Functions
void Process (const btDbvtNode *leaf)
void Process (btSoftBody *ps, btCollisionObject *colOb)
Public Attributes
btSoftBody * psb
btCollisionObject * m_colObj
Detailed Description
Definition at line 717 of file btSoftBodyInternals.h.
Member Function Documentation
void btSoftColliders::CollideCL_RS::Process (const btDbvtNode * leaf) [inline]
don't collide an anchored cluster with a static/kinematic object
Reimplemented from btDbvt::ICollide.
Definition at line 722 of file btSoftBodyInternals.h.
References btAlignedAlloc, btDbvtNode::data, btTransform::getIdentity(), btSoftBody::Cluster::m_containsAnchor, btSoftBody::Joint::m_erp, btSoftBody::Joint::m_split, and btGjkEpaSolver2::SignedDistance().
Referenced by btSoftBody::defaultCollisionHandler().
void btSoftColliders::CollideCL_RS::Process (btSoftBody * ps, btCollisionObject * colOb) [inline]
Bullet rigid body uses multiply instead of minimum to determine combined friction. Some customization would be useful.
Definition at line 756 of file btSoftBodyInternals.h.
References ATTRIBUTE_ALIGNED16, btMin(), btDbvt::collideTV(), btDbvtAabbMm::FromMM(), btSoftBody::m_cdbvt, btDbvt::m_root, and btSoftBody::m_sst.
Member Data Documentation
btCollisionObject* btSoftColliders::CollideCL_RS::m_colObj
Definition at line 721 of file btSoftBodyInternals.h.
btSoftBody* btSoftColliders::CollideCL_RS::psb
Definition at line 719 of file btSoftBodyInternals.h.
The documentation for this struct was generated from the following file:
btSoftBodyInternals.h