Blender: utfconv.h File Reference
utfconv.h File Reference
#include <wchar.h>
#include <stdio.h>
#include <stdlib.h>
Defines
#define UTF_ERROR_NULL_IN 1 << 0
#define UTF_ERROR_ILLCHAR 1 << 1
#define UTF_ERROR_SMALL 1 << 2
#define UTF_ERROR_ILLSEQ 1 << 3
#define UTF16_ENCODE(in8str)
#define UTF16_UN_ENCODE(in8str) free(in8str ## _16); } (void)0
Functions
size_t count_utf_8_from_16 (const wchar_t *string16)
size_t count_utf_16_from_8 (const char *string8)
int conv_utf_16_to_8 (const wchar_t *in16, char *out8, size_t size8)
int conv_utf_8_to_16 (const char *in8, wchar_t *out16, size_t size16)
char * alloc_utf_8_from_16 (const wchar_t *in16, size_t add)
wchar_t * alloc_utf16_from_8 (const char *in8, size_t add)
Define Documentation
#define UTF16_ENCODE (in8str)
Value:
if (1) { \
        wchar_t *in8str ## _16 = alloc_utf16_from_8((char *)in8str, 0)
Definition at line 94 of file utfconv.h.
Referenced by GHOST_SystemPathsWin32::addToSystemRecentFiles(), bli_builddir(), BLI_file_older(), u_alloc_getenv(), ufopen(), umkdir(), uopen(), uput_getenv(), uputenv(), and urename().
#define UTF16_UN_ENCODE (in8str) free(in8str ## _16); } (void)0
Definition at line 97 of file utfconv.h.
Referenced by GHOST_SystemPathsWin32::addToSystemRecentFiles(), bli_builddir(), BLI_file_older(), u_alloc_getenv(), ufopen(), umkdir(), uopen(), uput_getenv(), uputenv(), and urename().
#define UTF_ERROR_ILLCHAR 1 << 1
Definition at line 54 of file utfconv.h.
Referenced by conv_utf_16_to_8(), and conv_utf_8_to_16().
#define UTF_ERROR_ILLSEQ 1 << 3
Definition at line 56 of file utfconv.h.
Referenced by conv_utf_8_to_16().
#define UTF_ERROR_NULL_IN 1 << 0
conv_utf_*** errors
Definition at line 53 of file utfconv.h.
Referenced by conv_utf_16_to_8(), and conv_utf_8_to_16().
#define UTF_ERROR_SMALL 1 << 2
Definition at line 55 of file utfconv.h.
Referenced by conv_utf_16_to_8(), and conv_utf_8_to_16().
Function Documentation
wchar_t* alloc_utf16_from_8 (const char * in8, size_t add)
Allocates and converts the utf-16 string from utf-8 in8 utf-8 string to convert add any additional size which will be allocated for new utf-16 string in wchar_t (two bytes)
Returns:
New allocated and converted utf-16 string or NULL if in8 is 0.
Definition at line 251 of file utfconv.c.
References add(), conv_utf_8_to_16(), count_utf_16_from_8(), and NULL.
Referenced by bli_builddir(), BLI_exists(), GHOST_WindowWin32::GHOST_WindowWin32(), and GHOST_WindowWin32::setTitle().
char* alloc_utf_8_from_16 (const wchar_t * in16, size_t add)
Allocates and converts the utf-8 string from utf-16 in16 utf-16 string to convert add any additional size which will be allocated for new utf-8 string in bytes
Returns:
New allocated and converted utf-8 string or NULL if in16 is 0.
Definition at line 241 of file utfconv.c.
References add(), conv_utf_16_to_8(), count_utf_8_from_16(), and NULL.
Referenced by GHOST_SystemWin32::getClipboard(), main(), and u_alloc_getenv().
int conv_utf_16_to_8 (const wchar_t * in16, char * out8, size_t size8)
Converts utf-16 string to allocated utf-8 string in16 utf-16 string to convert out8 utf-8 string to string the conversion size8 the allocated size in bytes of out8
Returns:
Returns any errors occured during conversion. See the block above,
Definition at line 115 of file utfconv.c.
References err, UTF_ERROR_ILLCHAR, UTF_ERROR_NULL_IN, and UTF_ERROR_SMALL.
Referenced by alloc_utf_8_from_16(), bli_where_am_i(), get_thumb_dir(), GHOST_SystemPathsWin32::getBinaryDir(), GHOST_SystemPathsWin32::getSystemDir(), GHOST_SystemPathsWin32::getUserDir(), GHOST_SystemWin32::processKeyEvent(), and uput_getenv().
int conv_utf_8_to_16 (const char * in8, wchar_t * out16, size_t size16)
Converts utf-8 string to allocated utf-16 string in8 utf-8 string to convert out16 utf-16 string to string the conversion size16 the allocated size in wchar_t (two byte) of out16
Returns:
Returns any errors occured during conversion. See the block above,
Definition at line 169 of file utfconv.c.
References err, UTF_ERROR_ILLCHAR, UTF_ERROR_ILLSEQ, UTF_ERROR_NULL_IN, and UTF_ERROR_SMALL.
Referenced by alloc_utf16_from_8(), and GHOST_SystemWin32::putClipboard().
size_t count_utf_16_from_8 (const char * string8)
Counts how many wchar_t (two byte) is requered for for future utf-16 string using utf-8
Parameters:
string-8 pointer to working utf-8 string
Returns:
How many bytes must be allocated includeng NULL.
Definition at line 76 of file utfconv.c.
Referenced by alloc_utf16_from_8(), and GHOST_SystemWin32::putClipboard().
size_t count_utf_8_from_16 (const wchar_t * string16)
Counts how many bytes is requered for for future utf-8 string using utf-16
Parameters:
string-16 pointer to working utf-16 string
Returns:
How many bytes must be allocated includeng NULL.
Definition at line 28 of file utfconv.c.
References i.
Referenced by alloc_utf_8_from_16().