Blender: GregoryAccStencil Class Reference
GregoryAccStencil Class Reference
Public Member Functions
GregoryAccStencil (SubdFaceRing *ring_)
StencilMask & get (int i)
float & get (int i, SubdVert *vert)
Public Attributes
SubdFaceRing * ring
StencilMask stencil [20]
Detailed Description
Definition at line 53 of file subd_build.cpp.
Constructor & Destructor Documentation
GregoryAccStencil::GregoryAccStencil (SubdFaceRing * ring_) [inline]
Definition at line 58 of file subd_build.cpp.
References i, SubdFaceRing::num_verts(), resize(), ring, and stencil.
Member Function Documentation
StencilMask& GregoryAccStencil::get (int i) [inline]
Definition at line 66 of file subd_build.cpp.
References assert, i, and stencil.
Referenced by SubdAccBuilder::computeCornerStencil(), SubdAccBuilder::computeEdgeStencil(), and SubdAccBuilder::computeInteriorStencil().
float& GregoryAccStencil::get (int i, SubdVert * vert) [inline]
Definition at line 72 of file subd_build.cpp.
References assert, i, ring, stencil, and SubdFaceRing::vert_index().
Member Data Documentation
SubdFaceRing* GregoryAccStencil::ring
Definition at line 55 of file subd_build.cpp.
Referenced by get(), and GregoryAccStencil().
StencilMask GregoryAccStencil::stencil[20]
Definition at line 56 of file subd_build.cpp.
Referenced by get(), GregoryAccStencil(), and SubdAccBuilder::run().
The documentation for this class was generated from the following file:
subd_build.cpp