Blender: logic_intern.h File Reference
logic_intern.h File Reference
game logic editor
Functions
struct ARegion * logic_has_buttons_region (struct ScrArea *sa)
void LOGIC_OT_properties (struct wmOperatorType *ot)
void LOGIC_OT_links_cut (struct wmOperatorType *ot)
void logic_buttons (struct bContext *C, struct ARegion *ar)
void make_unique_prop_names (struct bContext *C, char *str)
Detailed Description
Definition in file logic_intern.h.
Function Documentation
void logic_buttons (struct bContext * C, struct ARegion * ar)
Definition at line 4788 of file logic_window.c.
References ACT_DEL, ACT_LINKED, ACT_PIN, ACT_SHOW, ACT_VISIBLE, actuator_menu(), actuator_name(), actuator_pup(), Object::actuators, B_ADD_ACT, B_ADD_CONT, B_ADD_SENS, B_CHANGE_ACT, B_CHANGE_CONT, B_CHANGE_SENS, B_DEL_ACT, B_DEL_CONT, B_DEL_SENS, B_INIT_STATE_BIT, B_REDR, B_SET_STATE_BIT, BLI_snprintf(), BUT, BUT_TOGDUAL, BUTS_ACT_ACT, BUTS_ACT_LINK, BUTS_ACT_SEL, BUTS_ACT_STATE, BUTS_CONT_ACT, BUTS_CONT_LINK, BUTS_CONT_SEL, BUTS_SENS_ACT, BUTS_SENS_LINK, BUTS_SENS_SEL, BUTS_SENS_STATE, check_state_mask(), CONT_DEL, CONT_PRIO, CONT_SHOW, controller_menu(), controller_name(), controller_pup(), controller_state_mask_menu(), Object::controllers, cpack, CTX_data_active_object(), CTX_data_main(), CTX_wm_space_logic(), do_logic_buts(), draw_actuatorbuttons(), draw_controllerbuttons(), draw_sensorbuttons(), FALSE, ListBase::first, first_bit(), bActuator::flag, bController::flag, bSensor::flag, G, get_selected_and_linked_obs(), get_state_name(), ICONTOG, Object::id, INLINK, is_sensor_linked(), LABEL, LINK, LINK_ACTUATOR, LINK_CONTROLLER, LINK_SENSOR, bController::links, bSensor::links, logic_buttons_new(), make_unique_prop_names_cb(), MAX_NAME, MEM_freeN(), MENU, bSensor::name, bActuator::name, ID::name, bController::name, bController::next, bSensor::next, bActuator::next, NULL, OB_ADDACT, OB_ADDCONT, OB_ADDSENS, OB_ALLSTATE, OB_DEBUGSTATE, OB_INITSTBIT, OB_SHOWACT, OB_SHOWCONT, OB_SHOWSENS, OB_VIS_ACT, OB_VIS_CONT, OB_VIS_SENS, object_state_mask_menu(), old_sca_move_actuator(), old_sca_move_controller(), old_sca_move_sensor(), bSensor::otype, bActuator::otype, bController::otype, RNA_pointer_create(), RNA_SpaceLogicEditor, Object::scaflag, SpaceLogic::scaflag, Object::scavisflag, SENS_DEL, SENS_PIN, SENS_SHOW, SENS_VISIBLE, sensor_menu(), sensor_name(), sensor_pup(), Object::sensors, set_col_actuator(), set_col_sensor(), Object::state, bController::state_mask, TEX, TOG, bController::totlinks, bSensor::totlinks, TRUE, bController::type, bActuator::type, bSensor::type, UI_EMBOSS, UI_UNIT_X, UI_UNIT_Y, uiBeginBlock(), uiBlockBeginAlign(), uiBlockEndAlign(), uiBlockSetHandleFunc(), uiButSetFunc(), uiComposeLinks(), uiDefBlockBut(), uiDefBut(), uiDefButBitI(), uiDefButBitS(), uiDefButS(), uiDefIconBut(), uiDefIconButBitS(), uiDrawBlock(), uiEndBlock(), and uiSetButLink().
Referenced by logic_main_area_draw().
struct ARegion* logic_has_buttons_region (struct ScrArea * sa) [read]
Definition at line 61 of file space_logic.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_LEFT, RGN_FLAG_HIDDEN, RGN_TYPE_HEADER, and RGN_TYPE_UI.
Referenced by logic_properties().
void LOGIC_OT_links_cut (struct wmOperatorType * ot)
Definition at line 143 of file logic_buttons.c.
References BC_KNIFECURSOR, wmOperatorType::cancel, cut_links_exec(), wmOperatorType::description, ED_operator_logic_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_COLLECTION, PROP_NONE, RNA_def_int(), RNA_def_property(), RNA_def_property_struct_runtime(), RNA_OperatorMousePath, wmOperatorType::srna, WM_gesture_lines_cancel(), WM_gesture_lines_invoke(), and WM_gesture_lines_modal().
Referenced by logic_operatortypes().
void LOGIC_OT_properties (struct wmOperatorType * ot)
Definition at line 64 of file logic_buttons.c.
References wmOperatorType::description, ED_operator_logic_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, logic_properties(), wmOperatorType::name, and wmOperatorType::poll.
Referenced by logic_operatortypes().
void make_unique_prop_names (struct bContext * C, char * str)
Definition at line 115 of file logic_window.c.
References Object::actuators, BLI_countlist(), BLI_newname(), BUTS_ACT_ACT, BUTS_ACT_SEL, BUTS_CONT_ACT, BUTS_CONT_SEL, BUTS_SENS_ACT, BUTS_SENS_SEL, Object::controllers, ListBase::first, get_selected_and_linked_obs(), MEM_callocN(), MEM_freeN(), bSensor::name, bActuator::name, bProperty::name, bController::name, names, bController::next, bProperty::next, bSensor::next, bActuator::next, Object::prop, Object::sensors, and vergname().
Referenced by actuator_add_exec(), controller_add_exec(), do_logic_buts(), make_unique_prop_names_cb(), and sensor_add_exec().