Blender: GHOST_DropTargetX11 Class Reference
GHOST_DropTargetX11 Class Reference
#include <GHOST_DropTargetX11.h>
Public Member Functions
GHOST_DropTargetX11 (GHOST_WindowX11 *window, GHOST_SystemX11 *system)
~GHOST_DropTargetX11 ()
bool GHOST_HandleClientMessage (XEvent *event)
void * getGhostData (Atom dropType, unsigned char *dropBuffer, int dropBufferSize)
Detailed Description
Definition at line 41 of file GHOST_DropTargetX11.h.
Constructor & Destructor Documentation
GHOST_DropTargetX11::GHOST_DropTargetX11 (GHOST_WindowX11 * window, GHOST_SystemX11 * system)
Constructor
Parameters:
window The window to register as drop target.
system The associated system.
Definition at line 89 of file GHOST_DropTargetX11.cpp.
References GHOST_WindowX11::getXWindow(), GHOST_kDragnDropTypeUnknown, and GHOST_PRINT.
GHOST_DropTargetX11::~GHOST_DropTargetX11 ()
Destructor
Definition at line 109 of file GHOST_DropTargetX11.cpp.
References GHOST_PRINT.
Member Function Documentation
void * GHOST_DropTargetX11::getGhostData (Atom dropType, unsigned char * dropBuffer, int dropBufferSize)
Get data to pass in event. It checks the type and calls specific functions for each type.
Parameters:
dropType - type of dropped entity.
dropBuffer - buffer returned from source application
dropBufferSize - size of returned buffer
Returns:
Pointer to data.
Definition at line 250 of file GHOST_DropTargetX11.cpp.
References data, dndTypeOctetStream, dndTypePlainText, dndTypeURIList, dndTypeURL, GHOST_kDragnDropTypeFilenames, GHOST_kDragnDropTypeString, GHOST_kDragnDropTypeUnknown, and NULL.
Referenced by GHOST_HandleClientMessage().
bool GHOST_DropTargetX11::GHOST_HandleClientMessage (XEvent * event)
Handler of ClientMessage X11 event
Definition at line 288 of file GHOST_DropTargetX11.cpp.
References data, getGhostData(), GHOST_SystemX11::getXDisplay(), GHOST_kDragnDropTypeUnknown, and GHOST_kEventDraggingDropDone.
The documentation for this class was generated from the following files:
GHOST_DropTargetX11.h
GHOST_DropTargetX11.cpp