Blender: btHingeConstraint.h File Reference
btHingeConstraint.h File Reference
#include "LinearMath/btVector3.h"
#include "btJacobianEntry.h"
#include "btTypedConstraint.h"
Classes
struct btHingeConstraintDoubleData
do not change those serialization structures, it requires an updated sBulletDNAstr/sBulletDNAstr64
struct btHingeConstraintFloatData
do not change those serialization structures, it requires an updated sBulletDNAstr/sBulletDNAstr64
Defines
#define _BT_USE_CENTER_LIMIT_ 1
#define btHingeConstraintData btHingeConstraintFloatData
#define btHingeConstraintDataName "btHingeConstraintFloatData"
Enumerations
enum btHingeFlags { BT_HINGE_FLAGS_CFM_STOP = 1, BT_HINGE_FLAGS_ERP_STOP = 2, BT_HINGE_FLAGS_CFM_NORM = 4 }
Functions
ATTRIBUTE_ALIGNED16 (class) btHingeConstraint
Define Documentation
#define _BT_USE_CENTER_LIMIT_ 1
Definition at line 20 of file btHingeConstraint.h.
#define btHingeConstraintData btHingeConstraintFloatData
Definition at line 33 of file btHingeConstraint.h.
#define btHingeConstraintDataName "btHingeConstraintFloatData"
Definition at line 34 of file btHingeConstraint.h.
Enumeration Type Documentation
enum btHingeFlags
Enumerator:
BT_HINGE_FLAGS_CFM_STOP
BT_HINGE_FLAGS_ERP_STOP
BT_HINGE_FLAGS_CFM_NORM
Definition at line 39 of file btHingeConstraint.h.
Function Documentation
ATTRIBUTE_ALIGNED16 (class)
hinge constraint between two rigidbodies each with a pivotpoint that descibes the axis location in local space axis defines the orientation of the hinge axis
override the default global value of a parameter (such as ERP or CFM), optionally provide the axis (0..5). If no axis is provided, it uses the default axis for this constraint.
return the local value of parameter
fills the dataBuffer and returns the struct name (and 0 on failure)
Definition at line 49 of file btHingeConstraint.h.
References btNormalizeAngle(), btPlaneSpace1(), btRigidBody::calculateSerializeBufferSize(), btTransform::getBasis(), btAngularLimit::getHigh(), btAngularLimit::getLow(), btTransform::getOrigin(), btAngularLimit::getSign(), btMatrix3x3::inverse(), btAngularLimit::isLimit(), quatRotate(), btRigidBody::serialize(), btAngularLimit::set(), btMatrix3x3::setValue(), and shortestArcQuat().