Blender: bpy_internal_import.h File Reference
bpy_internal_import.h File Reference
Python Generic
Functions
void bpy_import_init (PyObject *builtins)
PyObject * bpy_text_import (struct Text *text)
PyObject * bpy_text_import_name (const char *name, int *found)
PyObject * bpy_text_reimport (PyObject *module, int *found)
void bpy_text_filename_get (char *fn, size_t fn_len, struct Text *text)
struct Main * bpy_import_main_get (void)
void bpy_import_main_set (struct Main *maggie)
Variables
PyMethodDef bpy_import_meth
PyMethodDef bpy_reload_meth
Detailed Description
Definition in file bpy_internal_import.h.
Function Documentation
void bpy_import_init (PyObject * builtins)
Definition at line 57 of file bpy_internal_import.c.
References BLI_assert, bpy_import_meth, bpy_reload_meth, mod(), and NULL.
Referenced by BPY_python_start().
struct Main* bpy_import_main_get (void) [read]
Definition at line 85 of file bpy_internal_import.c.
References bpy_import_main.
Referenced by BPY_string_exec().
void bpy_import_main_set (struct Main * maggie)
Definition at line 90 of file bpy_internal_import.c.
Referenced by bpy_context_clear(), bpy_context_update(), BPY_string_exec(), and pyop_call().
void bpy_text_filename_get (char * fn, size_t fn_len, struct Text * text)
Definition at line 96 of file bpy_internal_import.c.
References BLI_snprintf(), Text::id, ID_BLEND_PATH, ID::name, and SEP.
Referenced by bpy_text_import(), and python_script_exec().
PyObject* bpy_text_import (struct Text * text)
Definition at line 101 of file bpy_internal_import.c.
References BLI_strncpy(), bpy_text_filename_get(), Text::compiled, free_compiled_text(), Text::id, len(), MAX_ID_NAME, MEM_freeN(), ID::name, NULL, strlen(), and txt_to_buf().
Referenced by BPY_modules_load_user(), and bpy_text_import_name().
PyObject* bpy_text_import_name (const char * name, int * found)
Definition at line 130 of file bpy_internal_import.c.
References BLI_findstring(), bpy_import_main, bpy_text_import(), MAX_ID_NAME, NULL, strlen(), and Main::text.
Referenced by blender_import().
PyObject* bpy_text_reimport (PyObject * module, int * found)
Definition at line 166 of file bpy_internal_import.c.
References BLI_findstring(), BLI_path_basename(), bpy_import_main, Text::compiled, free_compiled_text(), Text::id, MEM_freeN(), Main::name, ID::name, NULL, Main::text, and txt_to_buf().
Referenced by blender_reload().
Variable Documentation
PyMethodDef bpy_import_meth
Definition at line 315 of file bpy_internal_import.c.
Referenced by bpy_import_init().
PyMethodDef bpy_reload_meth
Definition at line 316 of file bpy_internal_import.c.
Referenced by bpy_import_init().