Blender: BKE_multires.h File Reference
BKE_multires.h File Reference
blenkernel
Enumerations
enum { MULTIRES_SPACE_TANGENT, MULTIRES_SPACE_OBJECT, MULTIRES_SPACE_ABSOLUTE }
Functions
void multires_customdata_delete (struct Mesh *me)
void multires_mark_as_modified (struct Object *ob, enum MultiresModifiedFlags flags)
void multires_force_update (struct Object *ob)
void multires_force_render_update (struct Object *ob)
void multires_force_external_reload (struct Object *ob)
void multires_modifier_update_mdisps (struct DerivedMesh *dm)
void multires_modifier_update_hidden (struct DerivedMesh *dm)
void multiresModifier_set_levels_from_disps (struct MultiresModifierData *mmd, struct Object *ob)
struct DerivedMesh * multires_dm_create_from_derived (struct MultiresModifierData *, int local_mmd, struct DerivedMesh *, struct Object *, int)
struct MultiresModifierData * find_multires_modifier_before (struct Scene *scene, struct ModifierData *lastmd)
struct MultiresModifierData * get_multires_modifier (struct Scene *scene, struct Object *ob, int use_first)
struct DerivedMesh * get_multires_dm (struct Scene *scene, struct MultiresModifierData *mmd, struct Object *ob)
void multiresModifier_del_levels (struct MultiresModifierData *, struct Object *, int direction)
void multiresModifier_base_apply (struct MultiresModifierData *mmd, struct Object *ob)
void multiresModifier_subdivide (struct MultiresModifierData *mmd, struct Object *ob, int updateblock, int simple)
int multiresModifier_reshape (struct Scene *scene, struct MultiresModifierData *mmd, struct Object *dst, struct Object *src)
int multiresModifier_reshapeFromDM (struct Scene *scene, struct MultiresModifierData *mmd, struct Object *ob, struct DerivedMesh *srcdm)
int multiresModifier_reshapeFromDeformMod (struct Scene *scene, struct MultiresModifierData *mmd, struct Object *ob, struct ModifierData *md)
void multires_stitch_grids (struct Object *)
void multires_set_space (struct DerivedMesh *dm, struct Object *ob, int from, int to)
void multires_free (struct Multires *mr)
void multires_load_old (struct Object *ob, struct Mesh *me)
void multires_load_old_250 (struct Mesh *)
void multiresModifier_scale_disp (struct Scene *scene, struct Object *ob)
void multiresModifier_prepare_join (struct Scene *scene, struct Object *ob, struct Object *to_ob)
int multires_mdisp_corners (struct MDisps *s)
void multires_topology_changed (struct Mesh *me)
void old_mdisps_bilinear (float out[3], float(*disps)[3], const int st, float u, float v)
int mdisp_rot_face_to_crn (const int corners, const int face_side, const float u, const float v, float *x, float *y)
Detailed Description
Definition in file BKE_multires.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
MULTIRES_SPACE_TANGENT
MULTIRES_SPACE_OBJECT
MULTIRES_SPACE_ABSOLUTE
Definition at line 84 of file BKE_multires.h.
Function Documentation
struct MultiresModifierData* find_multires_modifier_before (struct Scene * scene, struct ModifierData * lastmd) [read]
Definition at line 290 of file multires.c.
References eModifierMode_Realtime, eModifierType_Multires, modifier_isEnabled(), NULL, ModifierData::prev, and ModifierData::type.
Referenced by modifier_apply_obdata().
struct DerivedMesh* get_multires_dm (struct Scene * scene, struct MultiresModifierData * mmd, struct Object * ob) [read]
Definition at line 275 of file multires.c.
References ModifierTypeInfo::applyModifier, CD_MASK_BAREMESH, CDDM_copy(), mesh_get_derived_deform(), modifierType_getInfo(), mti, and ModifierData::type.
Referenced by multires_apply_smat(), multiresModifier_reshapeFromDeformMod(), and multiresModifier_reshapeFromDM().
struct MultiresModifierData* get_multires_modifier (struct Scene * scene, struct Object * ob, int use_first) [read]
Definition at line 307 of file multires.c.
References eModifierMode_Realtime, eModifierType_Multires, ListBase::first, modifier_isEnabled(), Object::modifiers, ModifierData::next, NULL, and ModifierData::type.
Referenced by mesh_calc_modifiers(), multires_apply_smat(), multires_set_space(), multires_sync_levels(), multiresbake_check(), multiresbake_create_hiresdm(), multiresbake_create_loresdm(), and sculpt_get_first_deform_matrices().
int mdisp_rot_face_to_crn (const int corners, const int face_side, const float u, const float v, float * x, float * y)
Definition at line 2205 of file multires.c.
Referenced by get_ccgdm_data().
void multires_customdata_delete (Mesh * me)
Customdata
Definition at line 82 of file multires.c.
References BMEditMesh::bm, BM_data_layer_free(), CD_MDISPS, CustomData_external_remove(), CustomData_free_layer_active(), Mesh::edit_btmesh, Mesh::id, Mesh::ldata, BMesh::ldata, and Mesh::totloop.
Referenced by modifier_apply_obdata(), multires_del_higher(), multires_sync_levels(), and object_modifier_remove().
struct DerivedMesh* multires_dm_create_from_derived (struct MultiresModifierData * , int local_mmd, struct DerivedMesh * , struct Object * , int) [read]
Definition at line 1326 of file multires.c.
References APPLY_DISPLACEMENTS, CD_MASK_MDISPS, CustomData_external_read(), Object::data, eMultiresModifierFlag_ControlEdges, eMultiresModifierFlag_PlainUv, MultiresModifierData::flags, DerivedMesh::getGridData, DerivedMesh::getGridSize, DerivedMesh::getNumGrids, i, Mesh::id, Mesh::ldata, CCGDerivedMesh::local_mmd, CCGDerivedMesh::lvl, MEM_callocN(), MEM_freeN(), CCGDerivedMesh::mmd, CCGDerivedMesh::modified_flags, CCGDerivedMesh::multires, multires_get_level(), multires_output_hidden_to_ccgdm(), multires_set_tot_mdisps(), multiresModifier_disp_run(), NULL, CCGDerivedMesh::ob, MultiresModifierData::simple, subsurf_dm_create_local(), Mesh::totloop, MultiresModifierData::totlvl, and CCGDerivedMesh::totlvl.
Referenced by applyModifier(), multires_dm_create_local(), multires_load_old(), multiresbake_create_hiresdm(), and multiresbake_create_loresdm().
void multires_force_external_reload (struct Object * ob)
Definition at line 382 of file multires.c.
References CD_MASK_MDISPS, CustomData_external_reload(), get_mesh(), Mesh::id, Mesh::ldata, multires_force_update(), and Mesh::totloop.
void multires_force_render_update (struct Object * ob)
Definition at line 390 of file multires.c.
References eModifierType_Multires, Object::mode, modifiers_findByType(), multires_force_update(), and OB_MODE_SCULPT.
Referenced by screen_render_invoke().
void multires_force_update (struct Object * ob)
Definition at line 367 of file multires.c.
References BLI_pbvh_free(), Object::derivedFinal, DerivedMesh::needsFree, NULL, SculptSession::pbvh, DerivedMesh::release, and Object::sculpt.
Referenced by ED_sculpt_force_update(), init_multiresbake_job(), modifier_apply_obdata(), multires_del_higher(), multires_force_external_reload(), multires_force_render_update(), multires_subdivide(), multiresbake_image_exec_locked(), multiresModifier_base_apply(), multiresModifier_del_levels(), multiresModifier_reshapeFromDM(), sculpt_toggle_mode(), and set_mesh().
void multires_free (struct Multires * mr)
Definition at line 1519 of file multires.c.
References BLI_freelistN(), CustomData_free(), Multires::edge_creases, Multires::edge_flags, Multires::fdata, ListBase::first, Multires::levels, MEM_freeN(), multires_free_level(), MultiresLevel::next, MultiresLevel::totface, MultiresLevel::totvert, Multires::vdata, and Multires::verts.
Referenced by direct_link_mesh(), and multires_load_old().
void multires_load_old (struct Object * ob, struct Mesh * me)
Definition at line 1948 of file multires.c.
References BLI_insertlinkbefore(), CD_CALLOC, CD_MEDGE, CD_MFACE, CD_MVERT, CD_REFERENCE, CDDM_from_mesh(), CustomData_add_layer(), CustomData_free_layers(), CustomDataLayer::data, MultiresLevel::edges, eModifierType_Multires, eModifierTypeType_OnlyDeform, MultiresLevel::faces, Mesh::fdata, ListBase::first, i, CustomData::layers, MultiresModifierData::lvl, MultiresFace::mat_nr, MFace::mat_nr, Mesh::medge, Mesh::mface, modifier_new(), Object::modifiers, modifierType_getInfo(), MULTIRES_COORDS_MODIFIED, multires_dm_create_from_derived(), multires_dm_mark_as_modified(), multires_free(), multires_load_old_dm(), multires_load_old_face_flags(), multires_load_old_vcols(), multiresModifier_subdivide(), Mesh::mvert, ModifierData::next, NULL, DerivedMesh::release, Mesh::totedge, MultiresLevel::totedge, Mesh::totface, MultiresLevel::totface, MultiresModifierData::totlvl, Mesh::totvert, MultiresLevel::totvert, CustomDataLayer::type, ModifierTypeInfo::type, ModifierData::type, MultiresFace::v, MultiresEdge::v, MFace::v1, MEdge::v1, MFace::v2, MEdge::v2, MFace::v3, MFace::v4, and Mesh::verts.
Referenced by do_versions().
void multires_load_old_250 (struct Mesh *)
Definition at line 1476 of file multires.c.
References CD_CALLOC, CD_MDISPS, CustomData_add_layer(), CustomData_get_layer(), MDisps::disps, Mesh::fdata, i, Mesh::ldata, MDisps::level, MEM_callocN(), Mesh::mface, NULL, old_mdisps_convert(), MDisps::totdisp, Mesh::totface, Mesh::totloop, and MFace::v4.
Referenced by do_versions().
void multires_mark_as_modified (struct Object * ob, enum MultiresModifiedFlags flags)
Definition at line 361 of file multires.c.
References Object::derivedFinal, and multires_dm_mark_as_modified().
Referenced by partialvis_update_grids(), sculpt_flush_update(), and sculpt_undo_restore().
int multires_mdisp_corners (struct MDisps * s)
Definition at line 2131 of file multires.c.
References MDisps::totdisp.
Referenced by bm_corners_to_loops(), and layerSwap_mdisps().
void multires_modifier_update_hidden (struct DerivedMesh * dm)
Definition at line 1148 of file multires.c.
References CD_MDISPS, CustomData_get_layer(), Object::data, CCGDerivedMesh::gridHidden, MDisps::hidden, i, Mesh::ldata, CCGDerivedMesh::lvl, MEM_freeN(), CCGDerivedMesh::multires, multires_mdisps_upsample_hidden(), NULL, CCGDerivedMesh::ob, Mesh::totloop, and CCGDerivedMesh::totlvl.
Referenced by ccgDM_release().
void multires_modifier_update_mdisps (struct DerivedMesh * dm)
Definition at line 1053 of file multires.c.
References ADD_DISPLACEMENTS, CALC_DISPLACEMENTS, ccgSubSurf_updateFromFaces(), ccgSubSurf_updateLevels(), CD_MASK_BAREMESH, CD_MASK_MDISPS, CD_MDISPS, CDDM_copy(), CDDM_from_mesh(), co, CustomData_external_read(), CustomData_get_layer(), Object::data, Object::derivedDeform, DM_set_only_copy(), eMultiresModifierFlag_PlainUv, MultiresModifierData::flags, DerivedMesh::getGridData, DerivedMesh::getGridSize, DerivedMesh::getNumGrids, i, Mesh::id, Mesh::ldata, CCGDerivedMesh::lvl, MEM_callocN(), MEM_freeN(), CCGDerivedMesh::mmd, CCGDerivedMesh::multires, multires_copy_dm_grid(), multires_dm_create_local(), multires_set_tot_mdisps(), multiresModifier_disp_run(), NULL, CCGDerivedMesh::ob, DerivedMesh::release, MultiresModifierData::simple, sub_v3_v3v3(), subsurf_dm_create_local(), Mesh::totloop, CCGDerivedMesh::totlvl, and MultiresModifierData::totlvl.
Referenced by ccgDM_release().
void multires_set_space (struct DerivedMesh * dm, struct Object * ob, int from, int to)
Definition at line 1180 of file multires.c.
References add_v3_v3(), add_v3_v3v3(), CD_MDISPS, CD_MPOLY, DMGridData::co, co, column_vectors_to_mat3(), copy_v3_v3(), CustomData_get_layer(), data, MDisps::disps, eMultiresModifierFlag_ControlEdges, eMultiresModifierFlag_PlainUv, MultiresModifierData::flags, get_multires_modifier(), DerivedMesh::getGridData, DerivedMesh::getGridOffset, DerivedMesh::getGridSize, grid_tangent(), i, invert_m3(), MDisps::level, DerivedMesh::loopData, MPoly::loopstart, MEM_callocN(), mul_v3_m3v3(), multires_dm_create_local(), multires_side_tot, MULTIRES_SPACE_ABSOLUTE, MULTIRES_SPACE_OBJECT, MULTIRES_SPACE_TANGENT, DerivedMesh::needsFree, DMGridData::no, normalize_v3(), NULL, DerivedMesh::numPolyData, DerivedMesh::polyData, DerivedMesh::release, MultiresModifierData::simple, sub_v3_v3(), subsurf_dm_create_local(), MDisps::totdisp, MPoly::totloop, and MultiresModifierData::totlvl.
Referenced by bm_mdisps_space_set().
void multires_stitch_grids (struct Object *)
Definition at line 1307 of file multires.c.
References BLI_pbvh_get_grid_updates(), ccgSubSurf_stitchFaces(), Object::derivedFinal, if(), MEM_freeN(), CCGDerivedMesh::pbvh, and CCGDerivedMesh::ss.
Referenced by sculpt_fix_noise_tear(), and smooth().
void multires_topology_changed (struct Mesh * me)
Definition at line 2169 of file multires.c.
References CD_MASK_MDISPS, CD_MDISPS, CustomData_external_read(), CustomData_get_layer(), MDisps::disps, i, Mesh::id, Mesh::ldata, MEM_callocN(), NULL, MDisps::totdisp, Mesh::totface, and Mesh::totloop.
Referenced by BM_mesh_bm_to_me().
void multiresModifier_base_apply (struct MultiresModifierData * mmd, struct Object * ob)
Definition at line 710 of file multires.c.
References add_v3_v3(), CALC_DISPLACEMENTS, CD_MASK_BAREMESH, CDDM_from_mesh(), MVert::co, copy_v3_v3(), MeshElemMap::count, DM_set_only_copy(), eMultiresModifierFlag_PlainUv, MultiresModifierData::flags, get_mesh(), DerivedMesh::getGridData, DerivedMesh::getNumVerts, DerivedMesh::getPolyMap, DerivedMesh::getVertCo, i, MeshElemMap::indices, MPoly::loopstart, MEM_callocN(), MEM_freeN(), MEM_mallocN(), mesh_calc_poly_normal_coords(), Mesh::mloop, Mesh::mpoly, mul_v3_fl(), multires_dm_create_local(), multires_force_update(), multiresModifier_disp_run(), Mesh::mvert, normalize_v3(), NULL, p, DerivedMesh::release, subsurf_dm_create_local(), MPoly::totloop, MultiresModifierData::totlvl, Mesh::totvert, MLoop::v, and v3_dist_from_plane().
Referenced by multires_base_apply_exec().
void multiresModifier_del_levels (struct MultiresModifierData * , struct Object * , int direction)
Definition at line 651 of file multires.c.
References CD_MASK_MDISPS, CD_MDISPS, CustomData_external_read(), CustomData_get_layer(), get_mesh(), Mesh::id, Mesh::ldata, multires_del_higher(), multires_force_update(), multires_get_level(), multires_set_tot_level(), multires_set_tot_mdisps(), Mesh::totloop, and MultiresModifierData::totlvl.
Referenced by multires_higher_levels_delete_exec().
void multiresModifier_prepare_join (struct Scene * scene, struct Object * ob, struct Object * to_ob)
Definition at line 2154 of file multires.c.
References invert_m3(), mul_m3_m3m3(), multires_apply_smat(), multires_sync_levels(), and object_scale_to_mat3().
Referenced by join_mesh_exec().
int multiresModifier_reshape (struct Scene * scene, struct MultiresModifierData * mmd, struct Object * dst, struct Object * src)
Definition at line 418 of file multires.c.
References CD_MASK_BAREMESH, mesh_get_derived_final(), and multiresModifier_reshapeFromDM().
Referenced by multires_reshape_exec().
int multiresModifier_reshapeFromDeformMod (struct Scene * scene, struct MultiresModifierData * mmd, struct Object * ob, struct ModifierData * md)
Definition at line 424 of file multires.c.
References CDDM_apply_vert_coords(), CDDM_copy(), ModifierTypeInfo::deformVerts, get_multires_dm(), DerivedMesh::getNumVerts, DerivedMesh::getVertCos, MEM_callocN(), MEM_freeN(), modifierType_getInfo(), mti, multires_get_level(), multiresModifier_reshapeFromDM(), DerivedMesh::release, and ModifierData::type.
Referenced by modifier_apply_obdata().
int multiresModifier_reshapeFromDM (struct Scene * scene, struct MultiresModifierData * mmd, struct Object * ob, struct DerivedMesh * srcdm)
Definition at line 396 of file multires.c.
References get_multires_dm(), DerivedMesh::getNumVerts, DerivedMesh::getVertArray, MULTIRES_COORDS_MODIFIED, multires_dm_mark_as_modified(), multires_force_update(), multires_mvert_to_ss(), and DerivedMesh::release.
Referenced by multiresModifier_reshape(), and multiresModifier_reshapeFromDeformMod().
void multiresModifier_scale_disp (struct Scene * scene, struct Object * ob)
Definition at line 2144 of file multires.c.
References multires_apply_smat(), and object_scale_to_mat3().
Referenced by apply_objects_internal().
void multiresModifier_set_levels_from_disps (struct MultiresModifierData * mmd, struct Object * ob)
Definition at line 493 of file multires.c.
References BMEditMesh::bm, CD_MDISPS, CustomData_get_layer(), Object::data, Mesh::edit_btmesh, get_levels_from_disps(), Mesh::ldata, BMesh::ldata, MultiresModifierData::lvl, MIN2, MultiresModifierData::renderlvl, MultiresModifierData::sculptlvl, and MultiresModifierData::totlvl.
Referenced by ED_object_modifier_add(), and test_object_modifiers().
void multiresModifier_subdivide (struct MultiresModifierData * mmd, struct Object * ob, int updateblock, int simple)
Definition at line 909 of file multires.c.
References multires_subdivide(), and MultiresModifierData::totlvl.
Referenced by multires_load_old(), and multires_subdivide_exec().
void old_mdisps_bilinear (float out[3], float(*) disps[3], const int st, float u, float v)
Definition at line 1387 of file multires.c.
References add_v3_v3v3(), isnan(), mul_v3_fl(), and mul_v3_v3fl().
Referenced by bm_loop_interp_mdisps(), and old_mdisps_convert().