Blender: ssnode_bmod.c File Reference
ssnode_bmod.c File Reference
opennl
#include "ssp_defs.h"
Functions
void slsolve (int, int, float *, float *)
void smatvec (int, int, int, float *, float *, float *)
int ssnode_bmod (const int jcol, const int fsupc, float *dense, float *tempv, GlobalLU_t *Glu, SuperLUStat_t *stat)
Detailed Description
Definition in file ssnode_bmod.c.
Function Documentation
void slsolve (int , int , float * , float *)
Definition at line 33 of file smyblas2.c.
void smatvec (int , int , int , float * , float * , float *)
Definition at line 160 of file smyblas2.c.
int ssnode_bmod (const int jcol, const int fsupc, float * dense, float * tempv, GlobalLU_t * Glu, SuperLUStat_t * stat)
Definition at line 34 of file ssnode_bmod.c.
References GEMV, i, GlobalLU_t::lsub, GlobalLU_t::lusup, SuperLUStat_t::ops, slsolve(), smatvec(), strlen(), strsv_(), TRSV, GlobalLU_t::xlsub, and GlobalLU_t::xlusup.
Referenced by sgstrf().