Blender: BSP_CSGMesh_CFIterator.h File Reference
BSP_CSGMesh_CFIterator.h File Reference
bsp
#include "BSP_CSGMesh.h"
#include "../extern/CSG_BooleanOps.h"
Classes
struct BSP_CSGMesh_VertexIt
struct BSP_CSGMesh_FaceIt
Functions
void BSP_CSGMesh_VertexIt_Destruct (CSG_VertexIteratorDescriptor *iterator)
int BSP_CSGMesh_VertexIt_Done (CSG_IteratorPtr it)
void BSP_CSGMesh_VertexIt_Fill (CSG_IteratorPtr it, CSG_IVertex *vert)
void BSP_CSGMesh_VertexIt_Step (CSG_IteratorPtr it)
void BSP_CSGMesh_VertexIt_Reset (CSG_IteratorPtr it)
void BSP_CSGMeshVertexIt_Construct (BSP_CSGMesh *mesh, CSG_VertexIteratorDescriptor *output)
void BSP_CSGMesh_FaceIt_Destruct (CSG_FaceIteratorDescriptor *iterator)
int BSP_CSGMesh_FaceIt_Done (CSG_IteratorPtr it)
void BSP_CSGMesh_FaceIt_Fill (CSG_IteratorPtr it, CSG_IFace *face)
void BSP_CSGMesh_FaceIt_Step (CSG_IteratorPtr it)
void BSP_CSGMesh_FaceIt_Reset (CSG_IteratorPtr it)
void BSP_CSGMesh_FaceIt_Construct (BSP_CSGMesh *mesh, CSG_FaceIteratorDescriptor *output)
Detailed Description
Definition in file BSP_CSGMesh_CFIterator.h.
Function Documentation
void BSP_CSGMesh_FaceIt_Construct (BSP_CSGMesh * mesh, CSG_FaceIteratorDescriptor * output) [inline]
Definition at line 249 of file BSP_CSGMesh_CFIterator.h.
References BSP_CSGMesh_FaceIt_Done(), BSP_CSGMesh_FaceIt_Fill(), BSP_CSGMesh_FaceIt_Reset(), BSP_CSGMesh_FaceIt_Step(), CSG_FaceIteratorDescriptor::Done, BSP_CSGMesh_FaceIt::face_triangle, BSP_CSGMesh::FaceSet(), CSG_FaceIteratorDescriptor::Fill, CSG_FaceIteratorDescriptor::it, BSP_CSGMesh_FaceIt::mesh, CSG_FaceIteratorDescriptor::num_elements, BSP_CSGMesh_FaceIt::pos, CSG_FaceIteratorDescriptor::Reset, and CSG_FaceIteratorDescriptor::Step.
Referenced by CSG_OutputFaceDescriptor().
void BSP_CSGMesh_FaceIt_Destruct (CSG_FaceIteratorDescriptor * iterator) [inline]
Definition at line 149 of file BSP_CSGMesh_CFIterator.h.
References CSG_FaceIteratorDescriptor::Done, CSG_FaceIteratorDescriptor::Fill, CSG_FaceIteratorDescriptor::it, NULL, CSG_FaceIteratorDescriptor::num_elements, CSG_FaceIteratorDescriptor::Reset, and CSG_FaceIteratorDescriptor::Step.
Referenced by CSG_FreeFaceDescriptor().
int BSP_CSGMesh_FaceIt_Done (CSG_IteratorPtr it) [inline]
Definition at line 164 of file BSP_CSGMesh_CFIterator.h.
References BSP_CSGMesh_FaceIt::face_triangle, BSP_CSGMesh::FaceSet(), BSP_MFace::m_verts, BSP_CSGMesh_FaceIt::mesh, and BSP_CSGMesh_FaceIt::pos.
Referenced by BSP_CSGMesh_FaceIt_Construct().
void BSP_CSGMesh_FaceIt_Fill (CSG_IteratorPtr it, CSG_IFace * face) [inline]
Definition at line 183 of file BSP_CSGMesh_CFIterator.h.
References BSP_MFace::m_orig_face, BSP_MFace::m_verts, CSG_IFace::orig_face, BSP_CSGMesh_FaceIt::pos, CSG_IFace::vertex_index, and CSG_IFace::vertex_number.
Referenced by BSP_CSGMesh_FaceIt_Construct().
void BSP_CSGMesh_FaceIt_Reset (CSG_IteratorPtr it) [inline]
Definition at line 238 of file BSP_CSGMesh_CFIterator.h.
References BSP_CSGMesh_FaceIt::face_triangle, BSP_CSGMesh::FaceSet(), BSP_CSGMesh_FaceIt::mesh, and BSP_CSGMesh_FaceIt::pos.
Referenced by BSP_CSGMesh_FaceIt_Construct().
void BSP_CSGMesh_FaceIt_Step (CSG_IteratorPtr it) [inline]
Definition at line 216 of file BSP_CSGMesh_CFIterator.h.
References BSP_CSGMesh_FaceIt::face_triangle, BSP_CSGMesh::FaceSet(), BSP_CSGMesh_FaceIt::mesh, and BSP_CSGMesh_FaceIt::pos.
Referenced by BSP_CSGMesh_FaceIt_Construct().
void BSP_CSGMesh_VertexIt_Destruct (CSG_VertexIteratorDescriptor * iterator) [inline]
Definition at line 53 of file BSP_CSGMesh_CFIterator.h.
References CSG_VertexIteratorDescriptor::Done, CSG_VertexIteratorDescriptor::Fill, CSG_VertexIteratorDescriptor::it, NULL, CSG_VertexIteratorDescriptor::num_elements, CSG_VertexIteratorDescriptor::Reset, and CSG_VertexIteratorDescriptor::Step.
Referenced by CSG_FreeVertexDescriptor().
int BSP_CSGMesh_VertexIt_Done (CSG_IteratorPtr it) [inline]
Definition at line 68 of file BSP_CSGMesh_CFIterator.h.
References BSP_CSGMesh_VertexIt::mesh, BSP_CSGMesh_VertexIt::pos, and BSP_CSGMesh::VertexSet().
Referenced by BSP_CSGMeshVertexIt_Construct().
void BSP_CSGMesh_VertexIt_Fill (CSG_IteratorPtr it, CSG_IVertex * vert) [inline]
Definition at line 83 of file BSP_CSGMesh_CFIterator.h.
References MT_Tuple3::getValue(), BSP_MVertex::m_pos, BSP_CSGMesh_VertexIt::pos, and CSG_IVertex::position.
Referenced by BSP_CSGMeshVertexIt_Construct().
void BSP_CSGMesh_VertexIt_Reset (CSG_IteratorPtr it) [inline]
Definition at line 106 of file BSP_CSGMesh_CFIterator.h.
References BSP_CSGMesh_VertexIt::mesh, BSP_CSGMesh_VertexIt::pos, and BSP_CSGMesh::VertexSet().
Referenced by BSP_CSGMeshVertexIt_Construct().
void BSP_CSGMesh_VertexIt_Step (CSG_IteratorPtr it) [inline]
Definition at line 95 of file BSP_CSGMesh_CFIterator.h.
References BSP_CSGMesh_VertexIt::pos.
Referenced by BSP_CSGMeshVertexIt_Construct().
void BSP_CSGMeshVertexIt_Construct (BSP_CSGMesh * mesh, CSG_VertexIteratorDescriptor * output) [inline]
Definition at line 116 of file BSP_CSGMesh_CFIterator.h.
References BSP_CSGMesh_VertexIt_Done(), BSP_CSGMesh_VertexIt_Fill(), BSP_CSGMesh_VertexIt_Reset(), BSP_CSGMesh_VertexIt_Step(), CSG_VertexIteratorDescriptor::Done, CSG_VertexIteratorDescriptor::Fill, CSG_VertexIteratorDescriptor::it, BSP_CSGMesh_VertexIt::mesh, CSG_VertexIteratorDescriptor::num_elements, BSP_CSGMesh_VertexIt::pos, CSG_VertexIteratorDescriptor::Reset, CSG_VertexIteratorDescriptor::Step, and BSP_CSGMesh::VertexSet().
Referenced by CSG_OutputVertexDescriptor().