Blender: GHOST_SystemPathsWin32 Class Reference
GHOST_SystemPathsWin32 Class Reference
#include <GHOST_SystemPathsWin32.h>
Public Member Functions
GHOST_SystemPathsWin32 ()
virtual ~GHOST_SystemPathsWin32 ()
const GHOST_TUns8 * getSystemDir () const
const GHOST_TUns8 * getUserDir () const
const GHOST_TUns8 * getBinaryDir () const
void addToSystemRecentFiles (const char *filename) const
Detailed Description
WIN32 Implementation of GHOST_SystemPaths class.
See also:
GHOST_SystemPaths.
Author:
Andrea Weikert
Date:
August 1, 2010
Definition at line 53 of file GHOST_SystemPathsWin32.h.
Constructor & Destructor Documentation
GHOST_SystemPathsWin32::GHOST_SystemPathsWin32 ()
Constructor.
Definition at line 64 of file GHOST_SystemPathsWin32.cpp.
GHOST_SystemPathsWin32::~GHOST_SystemPathsWin32 () [virtual]
Destructor.
Definition at line 68 of file GHOST_SystemPathsWin32.cpp.
Member Function Documentation
void GHOST_SystemPathsWin32::addToSystemRecentFiles (const char * filename) const [virtual]
Add the file to the operating system most recently used files
Implements GHOST_SystemPaths.
Definition at line 117 of file GHOST_SystemPathsWin32.cpp.
References UTF16_ENCODE, and UTF16_UN_ENCODE.
const GHOST_TUns8 * GHOST_SystemPathsWin32::getBinaryDir () const [virtual]
Determine the directory of the current binary
Returns:
Unsigned char string pointing to the binary dir
Implements GHOST_SystemPaths.
Definition at line 104 of file GHOST_SystemPathsWin32.cpp.
References conv_utf_16_to_8(), and NULL.
const GHOST_TUns8 * GHOST_SystemPathsWin32::getSystemDir () const [virtual]
Determine the base dir in which shared resources are located. It will first try to use "unpack and run" path, then look for properly installed path, not including versioning.
Returns:
Unsigned char string pointing to system dir (eg /usr/share/).
Implements GHOST_SystemPaths.
Definition at line 72 of file GHOST_SystemPathsWin32.cpp.
References conv_utf_16_to_8(), HRESULT, NULL, and S_OK.
const GHOST_TUns8 * GHOST_SystemPathsWin32::getUserDir () const [virtual]
Determine the base dir in which user configuration is stored, not including versioning. If needed, it will create the base directory.
Returns:
Unsigned char string pointing to user dir (eg ~/).
Implements GHOST_SystemPaths.
Definition at line 88 of file GHOST_SystemPathsWin32.cpp.
References conv_utf_16_to_8(), HRESULT, NULL, and S_OK.
The documentation for this class was generated from the following files:
GHOST_SystemPathsWin32.h
GHOST_SystemPathsWin32.cpp