Blender: SCA_RandomNumberGenerator Class Reference
SCA_RandomNumberGenerator Class Reference
#include <SCA_RandomNumberGenerator.h>
Public Member Functions
SCA_RandomNumberGenerator (long seed)
~SCA_RandomNumberGenerator ()
unsigned long Draw ()
float DrawFloat ()
long GetSeed ()
void SetSeed (long newseed)
SCA_RandomNumberGenerator * AddRef ()
void Release ()
Detailed Description
Definition at line 42 of file SCA_RandomNumberGenerator.h.
Constructor & Destructor Documentation
SCA_RandomNumberGenerator::SCA_RandomNumberGenerator (long seed)
Definition at line 57 of file SCA_RandomNumberGenerator.cpp.
SCA_RandomNumberGenerator::~SCA_RandomNumberGenerator ()
Definition at line 65 of file SCA_RandomNumberGenerator.cpp.
Member Function Documentation
SCA_RandomNumberGenerator* SCA_RandomNumberGenerator::AddRef () [inline]
Definition at line 67 of file SCA_RandomNumberGenerator.h.
Referenced by SCA_RandomSensor::ProcessReplica(), and SCA_RandomActuator::ProcessReplica().
unsigned long SCA_RandomNumberGenerator::Draw ()
This is the important part: copied verbatim :)
Definition at line 91 of file SCA_RandomNumberGenerator.cpp.
References LOWER_MASK, M, MATRIX_A, N, TEMPERING_MASK_B, TEMPERING_MASK_C, TEMPERING_SHIFT_L, TEMPERING_SHIFT_S, TEMPERING_SHIFT_T, TEMPERING_SHIFT_U, and UPPER_MASK.
Referenced by DrawFloat(), SCA_RandomSensor::Evaluate(), SCA_RandomSensor::Init(), and SCA_RandomActuator::Update().
float SCA_RandomNumberGenerator::DrawFloat ()
Definition at line 128 of file SCA_RandomNumberGenerator.cpp.
References Draw().
Referenced by SCA_RandomActuator::Update().
long SCA_RandomNumberGenerator::GetSeed ()
Definition at line 81 of file SCA_RandomNumberGenerator.cpp.
Referenced by SCA_RandomActuator::Update().
void SCA_RandomNumberGenerator::Release () [inline]
Definition at line 72 of file SCA_RandomNumberGenerator.h.
Referenced by SCA_RandomActuator::~SCA_RandomActuator(), and SCA_RandomSensor::~SCA_RandomSensor().
void SCA_RandomNumberGenerator::SetSeed (long newseed)
Definition at line 82 of file SCA_RandomNumberGenerator.cpp.
The documentation for this class was generated from the following files:
SCA_RandomNumberGenerator.h
SCA_RandomNumberGenerator.cpp