Blender: main.cpp File Reference
main.cpp File Reference
#include "LOD_decimation.h"
#include "ply/ply.h"
#include "MEM_SmartPtr.h"
#include "common/GlutDrawer.h"
#include "GlutMeshDrawer.h"
#include "MyGlutKeyHandler.h"
#include "MyGlutMouseHandler.h"
#include "MT_Vector3.h"
#include "LOD_GhostTestApp.h"
#include <memory>
Classes
struct LoadVertex
struct LoadFace
Defines
#define DEBUG_PRINT 0
Functions
LOD_Decimation_InfoPtr NewVertsFromFile (char *file_name, MT_Vector3 &min, MT_Vector3 &max)
void init (MT_Vector3 min, MT_Vector3 max)
int main (int argc, char **argv)
Define Documentation
#define DEBUG_PRINT 0
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) 2001-2002 by NaN Holding BV. All rights reserved.
The Original Code is: all of this file.
Contributor(s): none yet.
***** END GPL LICENSE BLOCK *****
Definition at line 40 of file decimation/test/decimate_glut_test/intern/main.cpp.
Function Documentation
void init (MT_Vector3 min, MT_Vector3 max)
Definition at line 219 of file decimation/test/decimate_glut_test/intern/main.cpp.
References distance(), MT_Vector3::length(), max, min, MT_Tuple3::x(), MT_Tuple3::y(), and MT_Tuple3::z().
int main (int argc, char ** argv)
Definition at line 277 of file decimation/test/decimate_glut_test/intern/main.cpp.
References init(), LOD_GhostTestApp::InitApp(), GlutDrawManager::InstallDrawer(), GlutKeyboardManager::InstallHandler(), GlutMouseManager::InstallHandler(), GlutKeyboardManager::Instance(), GlutDrawManager::Instance(), GlutMouseManager::Instance(), LOD_LoadMesh(), LOD_PreprocessMesh(), MyGlutKeyHandler::New(), GlutMeshDrawer::New(), MyGlutMouseHandler::New(), NewVertsFromFile(), and LOD_GhostTestApp::Run().
LOD_Decimation_InfoPtr NewVertsFromFile (char * file_name, MT_Vector3 & min, MT_Vector3 & max)
Definition at line 54 of file decimation/test/decimate_glut_test/intern/main.cpp.
References equal_strings(), LOD_Decimation_Info::face_num, i, LOD_Decimation_Info::intern, MT_INFINITY(), NULL, ply_close(), PLY_FLOAT, ply_get_element(), ply_get_element_description(), ply_get_property(), PLY_INT, ply_open_for_reading(), PLY_UCHAR, LOD_Decimation_Info::triangle_index_buffer, LOD_Decimation_Info::vertex_buffer, LOD_Decimation_Info::vertex_normal_buffer, LOD_Decimation_Info::vertex_num, MT_Tuple3::x(), MT_Tuple3::y(), and MT_Tuple3::z().
Referenced by main().