Blender: BLI_linklist.h File Reference
BLI_linklist.h File Reference
blenlib
Routines for working with singly linked lists of 'links' - pointers to other data.
Classes
struct LinkNode
Typedefs
typedef void(* LinkNodeFreeFP)(void *link)
typedef void(* LinkNodeApplyFP)(void *link, void *userdata)
typedef struct LinkNode LinkNode
Functions
int BLI_linklist_length (struct LinkNode *list)
int BLI_linklist_index (struct LinkNode *list, void *ptr)
struct LinkNode * BLI_linklist_find (struct LinkNode *list, int index)
void BLI_linklist_reverse (struct LinkNode **listp)
void BLI_linklist_prepend (struct LinkNode **listp, void *ptr)
void BLI_linklist_append (struct LinkNode **listp, void *ptr)
void BLI_linklist_prepend_arena (struct LinkNode **listp, void *ptr, struct MemArena *ma)
void BLI_linklist_insert_after (struct LinkNode **listp, void *ptr)
void BLI_linklist_free (struct LinkNode *list, LinkNodeFreeFP freefunc)
void BLI_linklist_apply (struct LinkNode *list, LinkNodeApplyFP applyfunc, void *userdata)
Detailed Description
Routines for working with singly linked lists of 'links' - pointers to other data.
Definition in file BLI_linklist.h.
Typedef Documentation
typedef struct LinkNode LinkNode
typedef void(* LinkNodeApplyFP)(void *link, void *userdata)
Definition at line 41 of file BLI_linklist.h.
typedef void(* LinkNodeFreeFP)(void *link)
Definition at line 40 of file BLI_linklist.h.
Function Documentation
void BLI_linklist_append (struct LinkNode ** listp, void * ptr)
Definition at line 100 of file BLI_linklist.c.
References LinkNode::link, MEM_mallocN(), LinkNode::next, and NULL.
Referenced by cloth_build_springs(), createVertsTrisData(), navmesh_create_exec(), and project_paint_begin().
void BLI_linklist_apply (struct LinkNode * list, LinkNodeApplyFP applyfunc, void * userdata)
Definition at line 158 of file BLI_linklist.c.
References LinkNode::link, and LinkNode::next.
Referenced by bvhcache_find().
struct LinkNode* BLI_linklist_find (struct LinkNode * list, int index) [read]
Definition at line 64 of file BLI_linklist.c.
References i, LinkNode::next, and NULL.
void BLI_linklist_free (struct LinkNode * list, LinkNodeFreeFP freefunc)
Definition at line 145 of file BLI_linklist.c.
References LinkNode::link, MEM_freeN(), LinkNode::next, and next.
Referenced by _bpy_names(), BLI_file_free_lines(), BLI_memarena_free(), bvhcache_free(), cloth_build_springs(), cloth_free_errorsprings(), cloth_free_modifier(), cloth_free_modifier_extern(), createVertsTrisData(), editbmesh_calc_modifiers(), filelist_from_library(), layerInterp_mdeformvert(), KX_BlenderSceneConverter::LinkBlendFile(), mesh_calc_modifiers(), navmesh_create_exec(), object_mouse_select_menu(), and project_paint_begin().
int BLI_linklist_index (struct LinkNode * list, void * ptr)
Definition at line 53 of file BLI_linklist.c.
References LinkNode::link, and LinkNode::next.
Referenced by project_paint_begin().
void BLI_linklist_insert_after (struct LinkNode ** listp, void * ptr)
Definition at line 128 of file BLI_linklist.c.
References LinkNode::link, MEM_mallocN(), LinkNode::next, and NULL.
int BLI_linklist_length (struct LinkNode * list)
Definition at line 38 of file BLI_linklist.c.
References BLI_linklist_length(), len(), and LinkNode::next.
Referenced by BLI_linklist_length(), and filelist_from_library().
void BLI_linklist_prepend (struct LinkNode ** listp, void * ptr)
Definition at line 91 of file BLI_linklist.c.
References LinkNode::link, MEM_mallocN(), and LinkNode::next.
Referenced by BLI_file_read_as_lines(), BLI_memarena_alloc(), BLO_blendhandle_get_datablock_names(), BLO_blendhandle_get_linkable_groups(), BLO_blendhandle_get_previews(), bvhcache_insert(), cloth_add_spring(), cloth_build_springs(), layerInterp_mdeformvert(), and object_mouse_select_menu().
void BLI_linklist_prepend_arena (struct LinkNode ** listp, void * ptr, struct MemArena * ma)
Definition at line 119 of file BLI_linklist.c.
References BLI_memarena_alloc(), LinkNode::link, and LinkNode::next.
Referenced by do_projectpaint_smear(), do_projectpaint_smear_f(), project_paint_begin(), project_paint_delayed_face_init(), and project_paint_face_init().
void BLI_linklist_reverse (struct LinkNode ** listp)
Definition at line 75 of file BLI_linklist.c.
References next, and NULL.
Referenced by BLI_file_read_as_lines(), and modifiers_calcDataMasks().