Blender: ExtraHandler Class Reference
ExtraHandler Class Reference
Handler class for <extra> data, through which different profiles can be handled.
#include <ExtraHandler.h>
Public Member Functions
ExtraHandler (DocumentImporter *dimp, AnimationImporter *aimp)
virtual ~ExtraHandler ()
bool elementBegin (const char *elementName, const char **attributes)
bool elementEnd (const char *elementName)
bool textData (const char *text, size_t textLength)
bool parseElement (const char *profileName, const unsigned long &elementHash, const COLLADAFW::UniqueId &uniqueId)
Detailed Description
Handler class for <extra> data, through which different profiles can be handled.
Definition at line 41 of file ExtraHandler.h.
Constructor & Destructor Documentation
ExtraHandler::ExtraHandler (DocumentImporter * dimp, AnimationImporter * aimp)
Constructor.
Definition at line 32 of file ExtraHandler.cpp.
ExtraHandler::~ExtraHandler () [virtual]
Destructor.
Definition at line 38 of file ExtraHandler.cpp.
Member Function Documentation
bool ExtraHandler::elementBegin (const char * elementName, const char ** attributes)
Handle the beginning of an element.
Definition at line 40 of file ExtraHandler.cpp.
bool ExtraHandler::elementEnd (const char * elementName)
Handle the end of an element.
Definition at line 48 of file ExtraHandler.cpp.
bool ExtraHandler::parseElement (const char * profileName, const unsigned long & elementHash, const COLLADAFW::UniqueId & uniqueId)
Method to ask, if the current callback handler want to read the data of the given extra element.
Definition at line 64 of file ExtraHandler.cpp.
References DocumentImporter::addExtraTags(), BLI_strcaseeq(), DocumentImporter::getExtraTags(), and uniqueId.
bool ExtraHandler::textData (const char * text, size_t textLength)
Receive the data in text format.
Definition at line 53 of file ExtraHandler.cpp.
References ExtraTags::addTag(), and BLI_snprintf().
The documentation for this class was generated from the following files:
ExtraHandler.h
ExtraHandler.cpp