Blender: collada.cpp File Reference
collada.cpp File Reference
COLLADA
#include "COLLADABUPlatform.h"
#include "ExportSettings.h"
#include "DocumentExporter.h"
#include "DocumentImporter.h"
#include "BKE_scene.h"
#include "BKE_context.h"
#include "BLI_fileops.h"
#include "BLI_path_util.h"
Functions
int collada_import (bContext *C, const char *filepath)
int collada_export (Scene *sce, const char *filepath, int selected, int second_life)
Detailed Description
Definition in file collada.cpp.
Function Documentation
int collada_export (Scene * sce, const char * filepath, int selected, int second_life)
Definition at line 52 of file collada.cpp.
References BLI_exists(), BLI_file_touch(), BLI_make_existing_file(), DocumentExporter::exportCurrentScene(), ExportSettings::filepath, ExportSettings::second_life, and ExportSettings::selected.
int collada_import (bContext * C, const char * filepath)
Definition at line 44 of file collada.cpp.
References DocumentImporter::import().