Blender: node_shader_normal.c File Reference
node_shader_normal.c File Reference
shdnodes
#include "node_shader_util.h"
Functions
static void node_shader_init_normal (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static void node_shader_exec_normal (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static int gpu_shader_normal (GPUMaterial *mat, bNode *node, GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_normal (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_normal_in []
static bNodeSocketTemplate sh_node_normal_out []
Detailed Description
Definition in file node_shader_normal.c.
Function Documentation
static int gpu_shader_normal (GPUMaterial * mat, bNode * node, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 74 of file node_shader_normal.c.
References bNodeSocket::default_value, ListBase::first, GPU_stack_link(), GPU_uniform(), and bNode::outputs.
Referenced by register_node_type_sh_normal().
static void node_shader_exec_normal (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 59 of file node_shader_normal.c.
References copy_v3_v3(), bNodeSocket::default_value, dot_v3v3(), ListBase::first, nodestack_get_vec(), bNode::outputs, SOCK_VECTOR, and bNodeStack::vec.
Referenced by register_node_type_sh_normal().
static void node_shader_init_normal (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 47 of file node_shader_normal.c.
References bNodeSocket::default_value, ListBase::first, bNode::outputs, and bNodeSocketValueVector::value.
Referenced by register_node_type_sh_normal().
void register_node_type_sh_normal (bNodeTreeType * ttype)
Definition at line 82 of file node_shader_normal.c.
References gpu_shader_normal(), NODE_CLASS_OP_VECTOR, NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_normal(), node_shader_init_normal(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_NORMAL.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_normal_in[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 1, "Normal",   0.0f, 0.0f, 0.0f, 1.0f, -1.0f, 1.0f, PROP_NONE},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_shader_normal.c.
bNodeSocketTemplate sh_node_normal_out[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 0, "Normal"},
    {   SOCK_FLOAT, 0, "Dot"},
    {   -1, 0, ""   }
}
Definition at line 41 of file node_shader_normal.c.