Blender: nla_ops.c File Reference
nla_ops.c File Reference
NLA editor
#include <string.h>
#include <stdio.h>
#include "DNA_scene_types.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "ED_anim_api.h"
#include "ED_markers.h"
#include "ED_screen.h"
#include "ED_transform.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "nla_intern.h"
Functions
int nlaop_poll_tweakmode_off (bContext *C)
int nlaop_poll_tweakmode_on (bContext *C)
short nlaedit_is_tweakmode_on (bAnimContext *ac)
void nla_operatortypes (void)
static void nla_keymap_channels (wmKeyMap *keymap)
static void nla_keymap_main (wmKeyConfig *keyconf, wmKeyMap *keymap)
void nla_keymap (wmKeyConfig *keyconf)
Detailed Description
Definition in file nla_ops.c.
Function Documentation
void nla_keymap (wmKeyConfig * keyconf)
Definition at line 299 of file nla_ops.c.
References KM_PRESS, NKEY, nla_keymap_channels(), nla_keymap_main(), SPACE_NLA, WM_keymap_add_item(), and WM_keymap_find().
Referenced by ED_spacetype_nla().
static void nla_keymap_channels (wmKeyMap * keymap) [static]
Definition at line 170 of file nla_ops.c.
References AKEY, DELKEY, FALSE, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTMOUSE, wmKeyMapItem::ptr, RNA_boolean_set(), TRUE, WM_keymap_add_item(), and XKEY.
Referenced by nla_keymap().
static void nla_keymap_main (wmKeyConfig * keyconf, wmKeyMap * keymap) [static]
Definition at line 195 of file nla_ops.c.
References AKEY, BKEY, DELKEY, DKEY, ED_marker_keymap_animedit_conflictfree(), FALSE, FKEY, GKEY, HKEY, HOMEKEY, IKEY, KKEY, KM_ALT, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTBRACKETKEY, MKEY, NLAEDIT_LRSEL_LEFT, NLAEDIT_LRSEL_RIGHT, NLAEDIT_LRSEL_TEST, PADPERIOD, PAGEDOWNKEY, PAGEUPKEY, wmKeyMapItem::ptr, RIGHTBRACKETKEY, RNA_boolean_set(), RNA_enum_set(), SELECTMOUSE, SKEY, SPACE_NLA, TABKEY, TKEY, transform_keymap_for_space(), TRUE, WM_keymap_add_item(), XKEY, and YKEY.
Referenced by nla_keymap().
void nla_operatortypes (void)
Definition at line 114 of file nla_ops.c.
References NLA_OT_action_sync_length(), NLA_OT_actionclip_add(), NLA_OT_apply_scale(), NLA_OT_channels_click(), NLA_OT_clear_scale(), NLA_OT_click_select(), NLA_OT_delete(), NLA_OT_delete_tracks(), NLA_OT_duplicate(), NLA_OT_fmodifier_add(), NLA_OT_fmodifier_copy(), NLA_OT_fmodifier_paste(), NLA_OT_meta_add(), NLA_OT_meta_remove(), NLA_OT_move_down(), NLA_OT_move_up(), NLA_OT_mute_toggle(), NLA_OT_properties(), NLA_OT_select_all_toggle(), NLA_OT_select_border(), NLA_OT_select_leftright(), NLA_OT_snap(), NLA_OT_soundclip_add(), NLA_OT_split(), NLA_OT_swap(), NLA_OT_tracks_add(), NLA_OT_transition_add(), NLA_OT_tweakmode_enter(), NLA_OT_tweakmode_exit(), NLA_OT_view_all(), NLA_OT_view_selected(), and WM_operatortype_append().
Referenced by ED_spacetype_nla().
short nlaedit_is_tweakmode_on (bAnimContext * ac)
Definition at line 105 of file nla_ops.c.
References Scene::flag, SCE_NLA_EDIT_ON, and bAnimContext::scene.
Referenced by mouse_nla_channels().
int nlaop_poll_tweakmode_off (bContext * C)
Definition at line 61 of file nla_ops.c.
References CTX_data_scene(), ED_operator_nla_active(), Scene::flag, NULL, and SCE_NLA_EDIT_ON.
Referenced by NLA_OT_actionclip_add(), NLA_OT_apply_scale(), NLA_OT_bake(), NLA_OT_clear_scale(), NLA_OT_delete(), NLA_OT_delete_tracks(), NLA_OT_duplicate(), NLA_OT_fmodifier_add(), NLA_OT_fmodifier_copy(), NLA_OT_fmodifier_paste(), NLA_OT_meta_add(), NLA_OT_meta_remove(), NLA_OT_move_down(), NLA_OT_move_up(), NLA_OT_mute_toggle(), NLA_OT_select_all_toggle(), NLA_OT_select_border(), NLA_OT_snap(), NLA_OT_soundclip_add(), NLA_OT_split(), NLA_OT_swap(), NLA_OT_tracks_add(), NLA_OT_transition_add(), and NLA_OT_tweakmode_enter().
int nlaop_poll_tweakmode_on (bContext * C)
Definition at line 83 of file nla_ops.c.
References CTX_data_scene(), ED_operator_nla_active(), Scene::flag, NULL, and SCE_NLA_EDIT_ON.
Referenced by NLA_OT_tweakmode_exit().