Blender: editarmature.c File Reference
editarmature.c File Reference
armature
#include <ctype.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include <assert.h>
#include "DNA_anim_types.h"
#include "DNA_mesh_types.h"
#include "DNA_armature_types.h"
#include "DNA_constraint_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BLI_ghash.h"
#include "BKE_animsys.h"
#include "BKE_action.h"
#include "BKE_armature.h"
#include "BKE_constraint.h"
#include "BKE_context.h"
#include "BKE_deform.h"
#include "BKE_depsgraph.h"
#include "BKE_DerivedMesh.h"
#include "BKE_global.h"
#include "BKE_idprop.h"
#include "BKE_main.h"
#include "BKE_object.h"
#include "BKE_report.h"
#include "BKE_subsurf.h"
#include "BKE_modifier.h"
#include "DNA_object_types.h"
#include "BIF_gl.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_armature.h"
#include "ED_keyframing.h"
#include "ED_mesh.h"
#include "ED_object.h"
#include "ED_screen.h"
#include "ED_util.h"
#include "ED_view3d.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "armature_intern.h"
#include "meshlaplacian.h"
Classes
struct UndoArmature
struct EditBonePoint
Defines
#define ARM_PAR_CONNECT 1
#define ARM_PAR_OFFSET 2
Typedefs
typedef struct UndoArmature UndoArmature
typedef struct EditBonePoint EditBonePoint
Functions
void ED_armature_sync_selection (ListBase *edbo)
void ED_armature_validate_active (struct bArmature *arm)
static void bone_free (bArmature *arm, EditBone *bone)
void ED_armature_edit_bone_remove (bArmature *arm, EditBone *exBone)
EditBone * ED_armature_bone_get_mirrored (ListBase *edbo, EditBone *ebo)
static void armature_select_mirrored (bArmature *arm)
static void armature_tag_select_mirrored (bArmature *arm)
static void armature_tag_unselect (bArmature *arm)
EditBone * make_boneList (ListBase *edbo, ListBase *bones, EditBone *parent, Bone *actBone)
static void fix_bonelist_roll (ListBase *bonelist, ListBase *editbonelist)
void ED_armature_from_edit (Object *obedit)
void ED_armature_apply_transform (Object *ob, float mat[4][4])
void docenter_armature (Scene *scene, Object *ob, float cursor[3], int centermode, int around)
static EditBone * editbone_name_exists (ListBase *edbo, const char *name)
static int editbone_unique_check (void *arg, const char *name)
void unique_editbone_name (ListBase *edbo, char *name, EditBone *bone)
static void applyarmature_fix_boneparents (Scene *scene, Object *armob)
static int apply_armature_pose2bones_exec (bContext *C, wmOperator *op)
void POSE_OT_armature_apply (wmOperatorType *ot)
static int pose_visual_transform_apply_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_visual_transform_apply (wmOperatorType *ot)
static void joined_armature_fix_links (Object *tarArm, Object *srcArm, bPoseChannel *pchan, EditBone *curbone)
int join_armature_exec (bContext *C, wmOperator *UNUSED(op))
static void separated_armature_fix_links (Object *origArm, Object *newArm)
static void separate_armature_bones (Object *ob, short sel)
static int separate_armature_exec (bContext *C, wmOperator *UNUSED(op))
void ARMATURE_OT_separate (wmOperatorType *ot)
Bone * get_indexed_bone (Object *ob, int index)
static void * get_bone_from_selectbuffer (Scene *scene, Base *base, unsigned int *buffer, short hits, short findunsel)
static void * get_nearest_bone (bContext *C, short findunsel, int x, int y)
static EditBone * editbone_get_child (bArmature *arm, EditBone *pabone, short use_visibility)
static void selectconnected_posebonechildren (Object *ob, Bone *bone, int extend)
static int pose_select_connected_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int pose_select_linked_poll (bContext *C)
void POSE_OT_select_linked (wmOperatorType *ot)
static int armature_select_linked_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int armature_select_linked_poll (bContext *C)
void ARMATURE_OT_select_linked (wmOperatorType *ot)
static EditBone * get_nearest_editbonepoint (ViewContext *vc, const int mval[2], ListBase *edbo, int findunsel, int *selmask)
static int armature_delete_selected_exec (bContext *C, wmOperator *UNUSED(op))
void ARMATURE_OT_delete (wmOperatorType *ot)
void ED_armature_deselect_all (Object *obedit, int toggle)
void ED_armature_deselect_all_visible (Object *obedit)
static int ebone_select_flag (EditBone *ebone)
int mouse_armature (bContext *C, const int mval[2], int extend)
void ED_armature_edit_free (struct Object *ob)
void ED_armature_to_edit (Object *ob)
float ED_rollBoneToVector (EditBone *bone, const float align_axis[3], const short axis_only)
static int armature_calc_roll_exec (bContext *C, wmOperator *op)
void ARMATURE_OT_calculate_roll (wmOperatorType *ot)
static void undoBones_to_editBones (void *uarmv, void *armv, void *UNUSED(data))
static void * editBones_to_undoBones (void *armv, void *UNUSED(obdata))
static void free_undoBones (void *uarmv)
static void * get_armature_edit (bContext *C)
void undo_push_armature (bContext *C, const char *name)
EditBone * ED_armature_edit_bone_add (bArmature *arm, const char *name)
void add_primitive_bone (Scene *scene, View3D *v3d, RegionView3D *rv3d)
static int armature_click_extrude_exec (bContext *C, wmOperator *UNUSED(op))
static int armature_click_extrude_invoke (bContext *C, wmOperator *op, wmEvent *event)
void ARMATURE_OT_click_extrude (wmOperatorType *ot)
static EditBone * add_points_bone (Object *obedit, float head[], float tail[])
static EditBone * get_named_editbone (ListBase *edbo, char *name)
void preEditBoneDuplicate (ListBase *editbones)
void updateDuplicateSubtargetObjects (EditBone *dupBone, ListBase *editbones, Object *src_ob, Object *dst_ob)
void updateDuplicateSubtarget (EditBone *dupBone, ListBase *editbones, Object *ob)
EditBone * duplicateEditBoneObjects (EditBone *curBone, const char *name, ListBase *editbones, Object *src_ob, Object *dst_ob)
EditBone * duplicateEditBone (EditBone *curBone, const char *name, ListBase *editbones, Object *ob)
static int armature_duplicate_selected_exec (bContext *C, wmOperator *UNUSED(op))
void ARMATURE_OT_duplicate (wmOperatorType *ot)
static void chains_find_tips (ListBase *edbo, ListBase *list)
static void fill_add_joint (EditBone *ebo, short eb_tail, ListBase *points)
static int armature_fill_bones_exec (bContext *C, wmOperator *op)
void ARMATURE_OT_fill (wmOperatorType *ot)
static void bones_merge (Object *obedit, EditBone *start, EditBone *end, EditBone *endchild, ListBase *chains)
static int armature_merge_exec (bContext *C, wmOperator *op)
void ARMATURE_OT_merge (wmOperatorType *ot)
static int armature_hide_exec (bContext *C, wmOperator *op)
void ARMATURE_OT_hide (wmOperatorType *ot)
static int armature_reveal_exec (bContext *C, wmOperator *UNUSED(op))
void ARMATURE_OT_reveal (wmOperatorType *ot)
static int armature_extrude_exec (bContext *C, wmOperator *op)
void ARMATURE_OT_extrude (wmOperatorType *ot)
static int armature_bone_primitive_add_exec (bContext *C, wmOperator *op)
void ARMATURE_OT_bone_primitive_add (wmOperatorType *ot)
static int armature_subdivide_exec (bContext *C, wmOperator *op)
void ARMATURE_OT_subdivide (wmOperatorType *ot)
static int armature_switch_direction_exec (bContext *C, wmOperator *UNUSED(op))
void ARMATURE_OT_switch_direction (wmOperatorType *ot)
static void bone_connect_to_existing_parent (EditBone *bone)
static void bone_connect_to_new_parent (ListBase *edbo, EditBone *selbone, EditBone *actbone, short mode)
static int armature_parent_set_exec (bContext *C, wmOperator *op)
static int armature_parent_set_invoke (bContext *C, wmOperator *UNUSED(op), wmEvent *UNUSED(event))
void ARMATURE_OT_parent_set (wmOperatorType *ot)
static void editbone_clear_parent (EditBone *ebone, int mode)
static int armature_parent_clear_exec (bContext *C, wmOperator *op)
void ARMATURE_OT_parent_clear (wmOperatorType *ot)
static int armature_select_inverse_exec (bContext *C, wmOperator *UNUSED(op))
void ARMATURE_OT_select_inverse (wmOperatorType *ot)
static int armature_de_select_all_exec (bContext *C, wmOperator *op)
void ARMATURE_OT_select_all (wmOperatorType *ot)
static int armature_select_hierarchy_exec (bContext *C, wmOperator *op)
void ARMATURE_OT_select_hierarchy (wmOperatorType *ot)
static void fix_connected_bone (EditBone *ebone)
static void fix_editbone_connected_children (ListBase *edbo, EditBone *ebone)
static void bone_align_to_bone (ListBase *edbo, EditBone *selbone, EditBone *actbone)
static int armature_align_bones_exec (bContext *C, wmOperator *op)
void ARMATURE_OT_align (wmOperatorType *ot)
static int bone_looper (Object *ob, Bone *bone, void *data, int(*bone_func)(Object *, Bone *, void *))
int ED_do_pose_selectbuffer (Scene *scene, Base *base, unsigned int *buffer, short hits, short extend)
void ED_pose_deselectall (Object *ob, int test)
static int bone_skinnable_cb (Object *ob, Bone *bone, void *datap)
static int vgroup_add_unique_bone_cb (Object *ob, Bone *bone, void *UNUSED(ptr))
static int dgroup_skinnable_cb (Object *ob, Bone *bone, void *datap)
static void add_vgroups__mapFunc (void *userData, int index, const float co[3], const float UNUSED(no_f[3]), const short UNUSED(no_s[3]))
static void envelope_bone_weighting (Object *ob, Mesh *mesh, float(*verts)[3], int numbones, Bone **bonelist, bDeformGroup **dgrouplist, bDeformGroup **dgroupflip, float(*root)[3], float(*tip)[3], int *selected, float scale)
static void add_verts_to_dgroups (ReportList *reports, Scene *scene, Object *ob, Object *par, int heat, int mirror)
void create_vgroups_from_armature (ReportList *reports, Scene *scene, Object *ob, Object *par, int mode, int mirror)
static void pchan_clear_scale (bPoseChannel *pchan)
static void pchan_clear_loc (bPoseChannel *pchan)
static void pchan_clear_rot (bPoseChannel *pchan)
static void pchan_clear_transforms (bPoseChannel *pchan)
static int pose_clear_transform_generic_exec (bContext *C, wmOperator *op, void(*clear_func)(bPoseChannel *), const char default_ksName[])
static int pose_clear_scale_exec (bContext *C, wmOperator *op)
void POSE_OT_scale_clear (wmOperatorType *ot)
static int pose_clear_rot_exec (bContext *C, wmOperator *op)
void POSE_OT_rot_clear (wmOperatorType *ot)
static int pose_clear_loc_exec (bContext *C, wmOperator *op)
void POSE_OT_loc_clear (wmOperatorType *ot)
static int pose_clear_transforms_exec (bContext *C, wmOperator *op)
void POSE_OT_transforms_clear (wmOperatorType *ot)
static int pose_de_select_all_exec (bContext *C, wmOperator *op)
void POSE_OT_select_all (wmOperatorType *ot)
static int pose_select_parent_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_select_parent (wmOperatorType *ot)
static int hide_selected_pose_bone_cb (Object *ob, Bone *bone, void *UNUSED(ptr))
static int hide_unselected_pose_bone_cb (Object *ob, Bone *bone, void *UNUSED(ptr))
static int pose_hide_exec (bContext *C, wmOperator *op)
void POSE_OT_hide (wmOperatorType *ot)
static int show_pose_bone_cb (Object *ob, Bone *bone, void *UNUSED(ptr))
static int pose_reveal_exec (bContext *C, wmOperator *UNUSED(op))
void POSE_OT_reveal (wmOperatorType *ot)
static int bone_unique_check (void *arg, const char *name)
static void unique_bone_name (bArmature *arm, char *name)
static void constraint_bone_name_fix (Object *ob, ListBase *conlist, char *oldname, char *newname)
void ED_armature_bone_rename (bArmature *arm, const char *oldnamep, const char *newnamep)
static int armature_flip_names_exec (bContext *C, wmOperator *UNUSED(op))
void ARMATURE_OT_flip_names (wmOperatorType *ot)
static int armature_autoside_names_exec (bContext *C, wmOperator *op)
void ARMATURE_OT_autoside_names (wmOperatorType *ot)
void transform_armature_mirror_update (Object *obedit)
Variables
static EnumPropertyItem prop_calc_roll_types []
static EnumPropertyItem prop_editarm_make_parent_types []
static EnumPropertyItem prop_editarm_clear_parent_types []
Detailed Description
Definition in file editarmature.c.
Define Documentation
#define ARM_PAR_CONNECT 1
Definition at line 3708 of file editarmature.c.
Referenced by armature_parent_set_invoke(), and bone_connect_to_new_parent().
#define ARM_PAR_OFFSET 2
Definition at line 3709 of file editarmature.c.
Referenced by armature_parent_set_invoke().
Typedef Documentation
typedef struct EditBonePoint EditBonePoint
typedef struct UndoArmature UndoArmature
Function Documentation
static EditBone* add_points_bone (Object * obedit, float head[], float tail[]) [static]
Definition at line 2427 of file editarmature.c.
References copy_v3_v3(), Object::data, ED_armature_edit_bone_add(), EditBone::head, and EditBone::tail.
Referenced by armature_fill_bones_exec(), and bones_merge().
void add_primitive_bone (Scene * scene, View3D * v3d, RegionView3D * rv3d)
Definition at line 2246 of file editarmature.c.
References bArmature::act_edbone, add_v3_v3v3(), copy_m3_m4(), copy_v3_v3(), Object::data, ED_armature_deselect_all(), ED_armature_edit_bone_add(), give_cursor(), EditBone::head, Object::imat, invert_m3_m3(), invert_m4_m4(), mul_m3_m3m3(), mul_v3_m4v3(), Scene::obedit, Object::obmat, EditBone::tail, unit_m3(), USER_ADD_VIEWALIGNED, and RegionView3D::viewmat.
Referenced by object_armature_add_exec().
static void add_verts_to_dgroups (ReportList * reports, Scene * scene, Object * ob, Object * par, int heat, int mirror) [static]
Definition at line 4563 of file editarmature.c.
References add_vgroups__mapFunc(), Bone::arm_head, Bone::arm_mat, Bone::arm_tail, b_bone_spline_setup(), BKE_report(), bone_looper(), BONE_SELECTED, bone_skinnable_cb(), bArmature::bonebase, CD_MASK_BAREMESH, MVert::co, copy_v3_v3(), Object::data, defgroup_find_name(), dgroup_skinnable_cb(), eModifierType_Subsurf, envelope_bone_weighting(), error(), FALSE, ListBase::first, Bone::flag, flip_side_name(), DerivedMesh::foreachMappedVert, get_pose_channel(), heat_bone_weighting(), i, Bone::layer, bArmature::layer, Mat4::mat, mat4_to_scale(), MAXBONENAME, MEM_callocN(), MEM_freeN(), mesh_get_derived_final(), mesh_octree_table(), Object::mode, modifiers_findByType(), mul_m4_v3(), mul_v3_m4v3(), Mesh::mvert, bDeformGroup::name, Bone::name, NULL, OB_MODE_WEIGHT_PAINT, Object::obmat, Object::pose, DerivedMesh::release, RPT_WARNING, Bone::segments, subsurf_calculate_limit_positions(), and Mesh::totvert.
Referenced by create_vgroups_from_armature().
static void add_vgroups__mapFunc (void * userData, int index, const float co[3], const float UNUSEDno_f[3], const short UNUSEDno_s[3]) [static]
Definition at line 4511 of file editarmature.c.
References copy_v3_v3().
Referenced by add_verts_to_dgroups().
static int apply_armature_pose2bones_exec (bContext * C, wmOperator * op) [static]
Definition at line 643 of file editarmature.c.
References AnimData::action, Object::adt, applyarmature_fix_boneparents(), BKE_report(), BONE_UNKEYED, bPose::chanbase, copy_m3_m4(), copy_v3_v3(), CTX_data_active_object(), CTX_data_scene(), ED_armature_edit_free(), ED_armature_from_edit(), ED_armature_to_edit(), bArmature::edbo, editbone_name_exists(), bPoseChannel::eul, ListBase::first, EditBone::flag, get_armature(), EditBone::head, invert_m3_m3(), bPoseChannel::loc, mat3_to_eul(), mul_m3_m3m3(), bPoseChannel::name, NC_OBJECT, ND_POSE, bPoseChannel::next, OB_ARMATURE, object_data_is_libdata(), object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, bPoseChannel::pose_head, bPoseChannel::pose_mat, bPoseChannel::pose_tail, bPoseChannel::quat, wmOperator::reports, EditBone::roll, bPoseChannel::rotAngle, bPoseChannel::rotAxis, RPT_ERROR, RPT_WARNING, bPoseChannel::size, sub_v3_v3v3(), EditBone::tail, Object::type, unit_axis_angle(), unit_qt(), vec_roll_to_mat3(), where_is_pose(), WM_event_add_notifier(), and zero_v3().
Referenced by POSE_OT_armature_apply().
static void applyarmature_fix_boneparents (Scene * scene, Object * armob) [static]
Definition at line 623 of file editarmature.c.
References FALSE, G, Object::id, invert_m4_m4(), ID::next, object_apply_mat4(), Object::obmat, PARBONE, Object::parent, Object::parentinv, Object::partype, and what_does_parent().
Referenced by apply_armature_pose2bones_exec().
static int armature_align_bones_exec (bContext * C, wmOperator * op) [static]
Definition at line 4170 of file editarmature.c.
References ARM_MIRROR_EDIT, BKE_report(), bone_align_to_bone(), BONE_SELECTED, CTX_data_active_bone(), CTX_DATA_BEGIN, CTX_DATA_COUNT, CTX_data_edit_object(), CTX_DATA_END, Object::data, ED_armature_bone_get_mirrored(), bArmature::edbo, ELEM, EditBone::flag, bArmature::flag, NC_OBJECT, ND_TRANSFORM, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, EditBone::parent, wmOperator::reports, RPT_ERROR, and WM_event_add_notifier().
Referenced by ARMATURE_OT_align().
static int armature_autoside_names_exec (bContext * C, wmOperator * op) [static]
Definition at line 5471 of file editarmature.c.
References BLI_strncpy(), bone_autoside_name(), CTX_DATA_BEGIN, CTX_data_edit_object(), CTX_DATA_END, DAG_id_tag_update(), Object::data, ED_armature_bone_rename(), ELEM, EditBone::head, Object::id, MAXBONENAME, EditBone::name, NC_OBJECT, ND_POSE, NULL, OB_RECALC_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, wmOperator::ptr, RNA_enum_get(), EditBone::tail, and WM_event_add_notifier().
Referenced by ARMATURE_OT_autoside_names().
static int armature_bone_primitive_add_exec (bContext * C, wmOperator * op) [static]
Definition at line 3453 of file editarmature.c.
References add_v3_v3v3(), copy_m3_m4(), copy_v3_v3(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_region_view3d(), CTX_wm_view3d(), Object::data, ED_armature_deselect_all(), ED_armature_edit_bone_add(), give_cursor(), EditBone::head, Object::imat, invert_m3_m3(), invert_m4_m4(), MAXBONENAME, mul_m3_m3m3(), mul_m4_v3(), NC_OBJECT, ND_BONE_SELECT, Object::obmat, OPERATOR_FINISHED, wmOperator::ptr, RNA_string_get(), EditBone::tail, unit_m3(), USER_ADD_VIEWALIGNED, RegionView3D::viewmat, and WM_event_add_notifier().
Referenced by ARMATURE_OT_bone_primitive_add().
static int armature_calc_roll_exec (bContext * C, wmOperator * op) [static]
Definition at line 2008 of file editarmature.c.
References bArmature::act_edbone, ARM_MIRROR_EDIT, assert, BKE_report(), copy_m3_m4(), copy_v3_v3(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_region_view3d(), CTX_wm_view3d(), Object::data, EBONE_EDITABLE, EBONE_VISIBLE, ED_armature_bone_get_mirrored(), ED_rollBoneToVector(), bArmature::edbo, ListBase::first, bArmature::flag, give_cursor(), EditBone::head, if(), invert_m3(), mul_m3_v3(), NC_OBJECT, ND_POSE, negate_v3(), EditBone::next, NULL, Object::obmat, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_enum_get(), EditBone::roll, RPT_ERROR, sub_v3_v3v3(), EditBone::tail, vec_roll_to_mat3(), RegionView3D::viewinv, and WM_event_add_notifier().
Referenced by ARMATURE_OT_calculate_roll().
static int armature_click_extrude_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2284 of file editarmature.c.
References bArmature::act_edbone, ARM_MIRROR_EDIT, BONE_CONNECTED, BONE_ROOTSEL, BONE_TIPSEL, copy_m3_m4(), copy_v3_v3(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_view3d(), Object::data, EditBone::dist, EBONE_VISIBLE, ED_armature_bone_get_mirrored(), ED_armature_deselect_all(), ED_armature_edit_bone_add(), ED_armature_sync_selection(), bArmature::edbo, ListBase::first, EditBone::flag, bArmature::flag, give_cursor(), EditBone::head, invert_m3_m3(), len_v3v3(), EditBone::length, mul_m3_v3(), EditBone::name, NC_OBJECT, ND_BONE_SELECT, EditBone::next, NULL, Object::obmat, OPERATOR_CANCELLED, OPERATOR_FINISHED, EditBone::parent, EditBone::rad_head, EditBone::rad_tail, sub_v3_v3v3(), SWAP, EditBone::tail, and WM_event_add_notifier().
Referenced by armature_click_extrude_invoke(), and ARMATURE_OT_click_extrude().
static int armature_click_extrude_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2375 of file editarmature.c.
References armature_click_extrude_exec(), copy_v3_v3(), CTX_data_scene(), CTX_wm_region(), CTX_wm_view3d(), ED_view3d_win_to_3d(), give_cursor(), wmEvent::mval, NULL, and VECCOPY2D.
Referenced by ARMATURE_OT_click_extrude().
static int armature_de_select_all_exec (bContext * C, wmOperator * op) [static]
Definition at line 3972 of file editarmature.c.
References BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, BONE_UNSELECTABLE, CTX_DATA_BEGIN, CTX_DATA_COUNT, CTX_DATA_END, EditBone::flag, NC_OBJECT, ND_BONE_SELECT, NULL, OPERATOR_FINISHED, EditBone::parent, wmOperator::ptr, RNA_enum_get(), SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, and WM_event_add_notifier().
Referenced by ARMATURE_OT_select_all().
static int armature_delete_selected_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1672 of file editarmature.c.
References bArmature::act_edbone, armature_select_mirrored(), BLI_freelinkN(), BONE_SELECTED, bPose::chanbase, CONSTRAINT_DISABLE, constraint_get_typeinfo(), bPoseChannel::constraints, CTX_DATA_COUNT, CTX_data_edit_object(), Object::data, ED_armature_edit_bone_remove(), ED_armature_sync_selection(), bArmature::edbo, editbone_name_exists(), ListBase::first, bConstraint::flag, EditBone::flag, bConstraintTypeInfo::flush_constraint_targets, free_pose_channel(), free_pose_channels_hash(), bConstraintTypeInfo::get_constraint_targets, EditBone::layer, bArmature::layer, bPoseChannel::name, NC_OBJECT, ND_BONE_SELECT, bPoseChannel::next, bConstraint::next, bConstraintTarget::next, EditBone::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, bConstraintTarget::subtarget, bConstraintTarget::tar, and WM_event_add_notifier().
Referenced by ARMATURE_OT_delete().
static int armature_duplicate_selected_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2575 of file editarmature.c.
References bArmature::act_edbone, ARM_MIRROR_EDIT, BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, CTX_DATA_COUNT, CTX_data_edit_object(), Object::data, duplicateEditBone(), EBONE_VISIBLE, ED_armature_bone_get_mirrored(), ED_armature_sync_selection(), ED_armature_validate_active(), bArmature::edbo, ListBase::first, EditBone::flag, bArmature::flag, if(), EditBone::name, NC_OBJECT, ND_BONE_SELECT, EditBone::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, EditBone::parent, preEditBoneDuplicate(), EditBone::temp, updateDuplicateSubtarget(), and WM_event_add_notifier().
Referenced by ARMATURE_OT_duplicate().
static int armature_extrude_exec (bContext * C, wmOperator * op) [static]
Definition at line 3299 of file editarmature.c.
References bArmature::act_edbone, ARM_MIRROR_EDIT, BLI_addtail(), BLI_strncpy(), BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, copy_v3_v3(), CTX_data_edit_object(), Object::data, EditBone::dist, EditBone::ease1, EditBone::ease2, EBONE_VISIBLE, ED_armature_bone_get_mirrored(), ED_armature_sync_selection(), bArmature::edbo, ListBase::first, EditBone::flag, bArmature::flag, EditBone::head, EditBone::layer, MEM_callocN(), EditBone::name, NC_OBJECT, ND_BONE_SELECT, EditBone::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, EditBone::parent, wmOperator::ptr, EditBone::rad_head, EditBone::rad_tail, RNA_boolean_get(), EditBone::segments, strlen(), SWAP, EditBone::tail, unique_editbone_name(), EditBone::weight, WM_event_add_notifier(), EditBone::xwidth, and EditBone::zwidth.
Referenced by ARMATURE_OT_extrude().
static int armature_fill_bones_exec (bContext * C, wmOperator * op) [static]
Definition at line 2806 of file editarmature.c.
References add_points_bone(), BKE_report(), BKE_reportf(), BLI_countlist(), BLI_freelistN(), BONE_CONNECTED, BONE_ROOTSEL, BONE_TIPSEL, copy_v3_v3(), CTX_DATA_BEGIN, CTX_data_edit_object(), CTX_DATA_END, CTX_data_scene(), CTX_wm_view3d(), Object::data, ELEM, fill_add_joint(), ListBase::first, EditBone::flag, give_cursor(), EditBonePoint::head_owner, if(), Object::imat, invert_m4_m4(), len_v3(), mul_v3_m4v3(), NC_OBJECT, ND_POSE, EditBonePoint::next, NULL, Object::obmat, OPERATOR_CANCELLED, OPERATOR_FINISHED, EditBone::parent, wmOperator::reports, RPT_ERROR, sub_v3_v3v3(), EditBonePoint::tail_owner, EditBonePoint::vec, and WM_event_add_notifier().
Referenced by ARMATURE_OT_fill().
static int armature_flip_names_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 5427 of file editarmature.c.
References CTX_DATA_BEGIN, CTX_data_edit_object(), CTX_DATA_END, DAG_id_tag_update(), Object::data, ED_armature_bone_rename(), ELEM, flip_side_name(), Object::id, MAXBONENAME, EditBone::name, NC_OBJECT, ND_POSE, NULL, OB_RECALC_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, TRUE, and WM_event_add_notifier().
Referenced by ARMATURE_OT_flip_names().
static int armature_hide_exec (bContext * C, wmOperator * op) [static]
Definition at line 3156 of file editarmature.c.
References BONE_HIDDEN_A, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, CTX_DATA_COUNT, CTX_data_edit_object(), Object::data, EBONE_VISIBLE, ED_armature_sync_selection(), ED_armature_validate_active(), bArmature::edbo, ListBase::first, EditBone::flag, invert(), NC_OBJECT, ND_BONE_SELECT, EditBone::next, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), and WM_event_add_notifier().
Referenced by ARMATURE_OT_hide().
static int armature_merge_exec (bContext * C, wmOperator * op) [static]
Definition at line 3051 of file editarmature.c.
References armature_tag_select_mirrored(), armature_tag_unselect(), BLI_freelistN(), BLI_insertlinkbefore(), BLI_remlink(), BONE_CONNECTED, BONE_SELECTED, bones_merge(), chains_find_tips(), CTX_data_edit_object(), Object::data, LinkData::data, EBONE_VISIBLE, ED_armature_sync_selection(), bArmature::edbo, ELEM, ListBase::first, EditBone::flag, NC_OBJECT, ND_POSE, LinkData::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, EditBone::parent, wmOperator::ptr, RNA_enum_get(), and WM_event_add_notifier().
Referenced by ARMATURE_OT_merge().
void ARMATURE_OT_align (wmOperatorType * ot)
Definition at line 4237 of file editarmature.c.
References armature_align_bones_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_autoside_names (wmOperatorType * ot)
Definition at line 5501 of file editarmature.c.
References armature_autoside_names_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_bone_primitive_add (wmOperatorType * ot)
Definition at line 3495 of file editarmature.c.
References armature_bone_primitive_add_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAXBONENAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_calculate_roll (wmOperatorType * ot)
Definition at line 2101 of file editarmature.c.
References armature_calc_roll_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_click_extrude (wmOperatorType * ot)
Definition at line 2408 of file editarmature.c.
References armature_click_extrude_exec(), armature_click_extrude_invoke(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_delete (wmOperatorType * ot)
Definition at line 1746 of file editarmature.c.
References armature_delete_selected_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_duplicate (wmOperatorType * ot)
Definition at line 2676 of file editarmature.c.
References armature_duplicate_selected_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_extrude (wmOperatorType * ot)
Definition at line 3432 of file editarmature.c.
References armature_extrude_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_fill (wmOperatorType * ot)
Definition at line 2950 of file editarmature.c.
References armature_fill_bones_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_flip_names (wmOperatorType * ot)
Definition at line 5455 of file editarmature.c.
References armature_flip_names_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_hide (wmOperatorType * ot)
Definition at line 3183 of file editarmature.c.
References armature_hide_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_merge (wmOperatorType * ot)
Definition at line 3129 of file editarmature.c.
References armature_merge_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_parent_clear (wmOperatorType * ot)
Definition at line 3920 of file editarmature.c.
References armature_parent_clear_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_parent_set (wmOperatorType * ot)
Definition at line 3866 of file editarmature.c.
References armature_parent_set_exec(), armature_parent_set_invoke(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_reveal (wmOperatorType * ot)
Definition at line 3223 of file editarmature.c.
References armature_reveal_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_select_all (wmOperatorType * ot)
Definition at line 4017 of file editarmature.c.
References armature_de_select_all_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_properties_select_all().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_select_hierarchy (wmOperatorType * ot)
Definition at line 4092 of file editarmature.c.
References armature_select_hierarchy_exec(), BONE_SELECT_CHILD, BONE_SELECT_PARENT, wmOperatorType::description, direction_items, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_select_inverse (wmOperatorType * ot)
Definition at line 3957 of file editarmature.c.
References armature_select_inverse_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_select_linked (wmOperatorType * ot)
Definition at line 1561 of file editarmature.c.
References armature_select_linked_invoke(), armature_select_linked_poll(), wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_separate (wmOperatorType * ot)
Definition at line 1243 of file editarmature.c.
References wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, separate_armature_exec(), and WM_operator_confirm().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_subdivide (wmOperatorType * ot)
Definition at line 3585 of file editarmature.c.
References armature_subdivide_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_int(), RNA_def_property_flag(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_switch_direction (wmOperatorType * ot)
Definition at line 3691 of file editarmature.c.
References armature_switch_direction_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
static int armature_parent_clear_exec (bContext * C, wmOperator * op) [static]
Definition at line 3901 of file editarmature.c.
References CTX_DATA_BEGIN, CTX_data_edit_object(), CTX_DATA_END, Object::data, ED_armature_sync_selection(), bArmature::edbo, editbone_clear_parent(), NC_OBJECT, ND_BONE_SELECT, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), and WM_event_add_notifier().
Referenced by ARMATURE_OT_parent_clear().
static int armature_parent_set_exec (bContext * C, wmOperator * op) [static]
Definition at line 3773 of file editarmature.c.
References ARM_MIRROR_EDIT, BKE_report(), bone_connect_to_existing_parent(), bone_connect_to_new_parent(), BONE_SELECTED, CTX_data_active_bone(), CTX_DATA_BEGIN, CTX_DATA_COUNT, CTX_data_edit_object(), CTX_DATA_END, Object::data, ED_armature_bone_get_mirrored(), bArmature::edbo, ELEM, EditBone::flag, bArmature::flag, NC_OBJECT, ND_BONE_SELECT, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, EditBone::parent, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), RPT_ERROR, and WM_event_add_notifier().
Referenced by ARMATURE_OT_parent_set().
static int armature_parent_set_invoke (bContext * C, wmOperator * UNUSEDop, wmEvent * UNUSEDevent) [static]
Definition at line 3841 of file editarmature.c.
References ARM_PAR_CONNECT, ARM_PAR_OFFSET, CTX_data_active_bone(), CTX_DATA_BEGIN, CTX_DATA_END, NULL, OPERATOR_CANCELLED, EditBone::parent, uiItemEnumO(), uiPupMenuBegin(), uiPupMenuEnd(), and uiPupMenuLayout().
Referenced by ARMATURE_OT_parent_set().
static int armature_reveal_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3201 of file editarmature.c.
References BONE_HIDDEN_A, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, CTX_data_edit_object(), Object::data, ED_armature_sync_selection(), ED_armature_validate_active(), bArmature::edbo, ListBase::first, EditBone::flag, EditBone::layer, bArmature::layer, NC_OBJECT, ND_BONE_SELECT, EditBone::next, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by ARMATURE_OT_reveal().
static int armature_select_hierarchy_exec (bContext * C, wmOperator * op) [static]
Definition at line 4036 of file editarmature.c.
References bArmature::act_edbone, BONE_ROOTSEL, BONE_SELECT_PARENT, BONE_SELECTED, BONE_TIPSEL, BONE_UNSELECTABLE, CTX_data_edit_object(), Object::data, EBONE_VISIBLE, ED_armature_sync_selection(), bArmature::edbo, editbone_get_child(), ListBase::first, EditBone::flag, NC_OBJECT, ND_BONE_SELECT, EditBone::next, NULL, OPERATOR_FINISHED, EditBone::parent, wmOperator::ptr, RNA_boolean_get(), RNA_enum_get(), and WM_event_add_notifier().
Referenced by ARMATURE_OT_select_hierarchy().
static int armature_select_inverse_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3940 of file editarmature.c.
References BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, BONE_UNSELECTABLE, CTX_DATA_BEGIN, CTX_DATA_END, EditBone::flag, NC_OBJECT, ND_BONE_SELECT, NULL, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by ARMATURE_OT_select_inverse().
static int armature_select_linked_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1491 of file editarmature.c.
References BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, BONE_UNSELECTABLE, CTX_data_edit_object(), Object::data, ED_armature_sync_selection(), bArmature::edbo, ListBase::first, EditBone::flag, get_nearest_bone(), wmEvent::mval, NC_OBJECT, ND_BONE_SELECT, next, EditBone::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, EditBone::parent, wmOperator::ptr, RNA_boolean_get(), view3d_operator_needs_opengl(), and WM_event_add_notifier().
Referenced by ARMATURE_OT_select_linked().
static int armature_select_linked_poll (bContext * C) [static]
Definition at line 1556 of file editarmature.c.
References ED_operator_editarmature(), and ED_operator_view3d_active().
Referenced by ARMATURE_OT_select_linked().
static void armature_select_mirrored (bArmature * arm) [static]
Definition at line 183 of file editarmature.c.
References ARM_MIRROR_EDIT, BONE_SELECTED, ED_armature_bone_get_mirrored(), bArmature::edbo, ListBase::first, EditBone::flag, bArmature::flag, EditBone::layer, bArmature::layer, and EditBone::next.
Referenced by armature_delete_selected_exec().
static int armature_subdivide_exec (bContext * C, wmOperator * op) [static]
Definition at line 3522 of file editarmature.c.
References BLI_addtail(), BONE_CONNECTED, copy_v3_v3(), CTX_DATA_BEGIN, CTX_data_edit_object(), CTX_DATA_END, Object::data, bArmature::edbo, ListBase::first, EditBone::flag, EditBone::head, i, MEM_mallocN(), EditBone::name, NC_OBJECT, ND_BONE_SELECT, EditBone::next, NULL, OPERATOR_FINISHED, EditBone::parent, wmOperator::ptr, EditBone::rad_head, EditBone::rad_tail, RNA_int_get(), EditBone::tail, unique_editbone_name(), and WM_event_add_notifier().
Referenced by ARMATURE_OT_subdivide().
static int armature_switch_direction_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3615 of file editarmature.c.
References CTX_data_edit_object(), Object::data, and NULL.
Referenced by ARMATURE_OT_switch_direction().
static void armature_tag_select_mirrored (bArmature * arm) [static]
Definition at line 202 of file editarmature.c.
References ARM_MIRROR_EDIT, BONE_DONE, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, ED_armature_bone_get_mirrored(), bArmature::edbo, ListBase::first, EditBone::flag, bArmature::flag, EditBone::layer, bArmature::layer, and EditBone::next.
Referenced by armature_merge_exec().
static void armature_tag_unselect (bArmature * arm) [static]
Definition at line 235 of file editarmature.c.
References BONE_DONE, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, bArmature::edbo, ListBase::first, EditBone::flag, and EditBone::next.
Referenced by armature_merge_exec().
static void bone_align_to_bone (ListBase * edbo, EditBone * selbone, EditBone * actbone) [static]
Definition at line 4149 of file editarmature.c.
References add_v3_v3v3(), fix_editbone_connected_children(), EditBone::head, len_v3(), length(), mul_v3_fl(), normalize_v3(), EditBone::roll, sub_v3_v3v3(), and EditBone::tail.
Referenced by armature_align_bones_exec().
static void bone_connect_to_existing_parent (EditBone * bone) [static]
Definition at line 3712 of file editarmature.c.
References BONE_CONNECTED, copy_v3_v3(), EditBone::flag, EditBone::head, EditBone::parent, EditBone::rad_head, EditBone::rad_tail, and EditBone::tail.
Referenced by armature_parent_set_exec().
static void bone_connect_to_new_parent (ListBase * edbo, EditBone * selbone, EditBone * actbone, short mode) [static]
Definition at line 3719 of file editarmature.c.
References add_v3_v3(), ARM_PAR_CONNECT, BONE_CONNECTED, BONE_TIPSEL, copy_v3_v3(), ListBase::first, EditBone::flag, EditBone::head, EditBone::next, NULL, EditBone::parent, EditBone::rad_head, EditBone::rad_tail, sub_v3_v3v3(), and EditBone::tail.
Referenced by armature_parent_set_exec().
static void bone_free (bArmature * arm, EditBone * bone) [static]
Definition at line 132 of file editarmature.c.
References bArmature::act_edbone, BLI_freelinkN(), bArmature::edbo, IDP_FreeProperty(), MEM_freeN(), NULL, and EditBone::prop.
Referenced by bones_merge(), ED_armature_edit_bone_remove(), ED_armature_from_edit(), and separate_armature_bones().
static int bone_looper (Object * ob, Bone * bone, void * data, int(*)(Object *, Bone *, void *) bone_func) [static]
Definition at line 4256 of file editarmature.c.
References Bone::childbase, ListBase::first, and Bone::next.
Referenced by add_verts_to_dgroups(), create_vgroups_from_armature(), pose_hide_exec(), and pose_reveal_exec().
static int bone_skinnable_cb (Object * ob, Bone * bone, void * datap) [static]
Definition at line 4391 of file editarmature.c.
References BONE_HIDDEN_P, BONE_NO_DEFORM, Bone::flag, get_pose_channel(), Object::mode, Bone::name, NULL, OB_MODE_WEIGHT_PAINT, and Bone::segments.
Referenced by add_verts_to_dgroups().
static int bone_unique_check (void * arg, const char * name) [static]
Definition at line 5254 of file editarmature.c.
References get_named_bone(), and NULL.
Referenced by unique_bone_name().
static void bones_merge (Object * obedit, EditBone * start, EditBone * end, EditBone * endchild, ListBase * chains) [static]
Definition at line 2970 of file editarmature.c.
References add_points_bone(), BONE_DONE, bone_free(), BONE_HINGE, BONE_NO_CYCLICOFFSET, BONE_NO_DEFORM, BONE_NO_LOCAL_LOCATION, BONE_NO_SCALE, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, copy_v3_v3(), Object::data, LinkData::data, ED_armature_sync_selection(), bArmature::edbo, ListBase::first, EditBone::flag, G, G_DEBUG, EditBone::head, EditBone::name, LinkData::next, NULL, EditBone::parent, and EditBone::tail.
Referenced by armature_merge_exec().
static void chains_find_tips (ListBase * edbo, ListBase * list) [static]
Definition at line 2706 of file editarmature.c.
References BLI_addtail(), LinkData::data, ListBase::first, MEM_callocN(), LinkData::next, EditBone::next, and EditBone::parent.
Referenced by armature_merge_exec().
static void constraint_bone_name_fix (Object * ob, ListBase * conlist, char * oldname, char * newname) [static]
Definition at line 5265 of file editarmature.c.
References BLI_strncpy(), constraint_get_typeinfo(), ListBase::first, bConstraintTypeInfo::flush_constraint_targets, bConstraintTypeInfo::get_constraint_targets, MAXBONENAME, bConstraint::next, bConstraintTarget::next, NULL, bConstraintTarget::subtarget, and bConstraintTarget::tar.
Referenced by ED_armature_bone_rename().
void create_vgroups_from_armature (ReportList * reports, Scene * scene, Object * ob, Object * par, int mode, int mirror)
Definition at line 4736 of file editarmature.c.
References add_verts_to_dgroups(), ARM_GROUPS_AUTO, ARM_GROUPS_ENVELOPE, ARM_GROUPS_NAME, bone_looper(), bArmature::bonebase, Object::data, ED_vgroup_data_create(), ListBase::first, NULL, OB_MESH, Object::type, and vgroup_add_unique_bone_cb().
Referenced by ED_object_parent_set(), and weight_from_bones_exec().
static int dgroup_skinnable_cb (Object * ob, Bone * bone, void * datap) [static]
Definition at line 4455 of file editarmature.c.
References BONE_HIDDEN_P, BONE_NO_DEFORM, BONE_SELECTED, defgroup_find_name(), ED_vgroup_add_name(), Bone::flag, get_pose_channel(), if(), Bone::layer, bArmature::layer, Object::mode, Bone::name, NULL, OB_MODE_WEIGHT_PAINT, and Bone::segments.
Referenced by add_verts_to_dgroups().
void docenter_armature (Scene * scene, Object * ob, float cursor[3], int centermode, int around)
Definition at line 537 of file editarmature.c.
References add_v3_v3(), copy_v3_v3(), Object::data, DO_MINMAX, ED_armature_edit_free(), ED_armature_from_edit(), ED_armature_to_edit(), bArmature::edbo, ListBase::first, EditBone::head, Object::imat, INIT_MINMAX, invert_m4_m4(), Object::loc, max, mid_v3_v3v3(), min, mul_m4_v3(), mul_mat3_m4_v3(), mul_v3_fl(), EditBone::next, NULL, Scene::obedit, Object::obmat, sub_v3_v3(), EditBone::tail, V3D_CENTROID, and zero_v3().
Referenced by object_origin_set_exec().
EditBone* duplicateEditBone (EditBone * curBone, const char * name, ListBase * editbones, Object * ob) [read]
Definition at line 2569 of file editarmature.c.
References duplicateEditBoneObjects().
Referenced by armature_duplicate_selected_exec().
EditBone* duplicateEditBoneObjects (EditBone * curBone, const char * name, ListBase * editbones, Object * src_ob, Object * dst_ob) [read]
Definition at line 2526 of file editarmature.c.
References BLI_addtail(), BLI_strncpy(), duplicate_pose_channel_data(), IDP_CopyProperty(), MEM_mallocN(), EditBone::name, NULL, Object::pose, EditBone::prop, EditBone::temp, unique_editbone_name(), and verify_pose_channel().
Referenced by cloneArc(), cloneControl(), and duplicateEditBone().
static int ebone_select_flag (EditBone * ebone) [static]
Definition at line 1831 of file editarmature.c.
References BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, EditBone::flag, and EditBone::parent.
Referenced by mouse_armature().
void ED_armature_apply_transform (Object * ob, float mat[4][4])
Definition at line 490 of file editarmature.c.
References copy_m3_m4(), Object::data, EditBone::dist, ED_armature_edit_free(), ED_armature_from_edit(), ED_armature_to_edit(), bArmature::edbo, ListBase::first, EditBone::head, mat3_to_vec_roll(), mat4_to_scale(), mul_m3_m3m3(), mul_m4_v3(), EditBone::next, normalize_m3(), NULL, EditBone::rad_head, EditBone::rad_tail, EditBone::roll, sub_v3_v3v3(), EditBone::tail, vec_roll_to_mat3(), EditBone::xwidth, and EditBone::zwidth.
Referenced by apply_objects_internal().
EditBone* ED_armature_bone_get_mirrored (ListBase * edbo, EditBone * ebo)
Definition at line 161 of file editarmature.c.
References FALSE, ListBase::first, flip_side_name(), MAXBONENAME, EditBone::name, EditBone::next, and NULL.
Referenced by armature_align_bones_exec(), armature_calc_roll_exec(), armature_click_extrude_exec(), armature_duplicate_selected_exec(), armature_extrude_exec(), armature_parent_set_exec(), armature_select_mirrored(), armature_tag_select_mirrored(), ed_screen_context(), and transform_armature_mirror_update().
void ED_armature_bone_rename (bArmature * arm, const char * oldnamep, const char * newnamep)
Definition at line 5293 of file editarmature.c.
References bScreen::areabase, BKE_all_animdata_fix_paths_rename(), BLI_ghash_insert(), BLI_ghash_remove(), BLI_strncpy(), bPose::chanbase, bPose::chanhash, constraint_bone_name_fix(), bPoseChannel::constraints, Object::constraints, Object::data, defgroup_find_name(), bArmature::edbo, editbone_name_exists(), eModifierType_Hook, ListBase::first, G, get_named_bone(), get_pose_channel(), bScreen::id, bArmature::id, Object::id, MAXBONENAME, Object::modifiers, modifiers_usesArmature(), bDeformGroup::name, bPoseChannel::name, Bone::name, EditBone::name, SpaceLink::next, ScrArea::next, ModifierData::next, bPoseChannel::next, ID::next, NULL, View3D::ob_centre, View3D::ob_centre_bone, HookModifierData::object, PARBONE, Object::parent, Object::parsubstr, Object::partype, Object::pose, SPACE_VIEW3D, ScrArea::spacedata, SpaceLink::spacetype, HookModifierData::subtarget, ModifierData::type, unique_bone_name(), and unique_editbone_name().
Referenced by armature_autoside_names_exec(), armature_flip_names_exec(), namebutton_cb(), pose_autoside_names_exec(), and pose_flip_names_exec().
void ED_armature_deselect_all (Object * obedit, int toggle)
Definition at line 1766 of file editarmature.c.
References bArmature::act_edbone, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, Object::data, EBONE_VISIBLE, ED_armature_sync_selection(), bArmature::edbo, ListBase::first, EditBone::flag, EditBone::next, NULL, and EditBone::parent.
Referenced by add_primitive_bone(), armature_bone_primitive_add_exec(), armature_click_extrude_exec(), mouse_armature(), and tree_element_active_ebone().
void ED_armature_deselect_all_visible (Object * obedit)
Definition at line 1815 of file editarmature.c.
References BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, BONE_UNSELECTABLE, Object::data, EBONE_VISIBLE, ED_armature_sync_selection(), bArmature::edbo, ListBase::first, EditBone::flag, and EditBone::next.
Referenced by do_armature_box_select(), and do_lasso_select_armature().
EditBone* ED_armature_edit_bone_add (bArmature * arm, const char * name) [read]
Definition at line 2221 of file editarmature.c.
References BLI_addtail(), BLI_strncpy(), BONE_TIPSEL, EditBone::dist, EditBone::ease1, EditBone::ease2, bArmature::edbo, EditBone::flag, bArmature::layer, EditBone::layer, MEM_callocN(), EditBone::name, NULL, EditBone::rad_head, EditBone::rad_tail, EditBone::segments, unique_editbone_name(), EditBone::weight, EditBone::xwidth, and EditBone::zwidth.
Referenced by add_points_bone(), add_primitive_bone(), armature_bone_primitive_add_exec(), armature_click_extrude_exec(), sk_convertStroke(), and subdivideArcBy().
void ED_armature_edit_bone_remove (bArmature * arm, EditBone * exBone)
Definition at line 145 of file editarmature.c.
References BONE_CONNECTED, bone_free(), bArmature::edbo, ListBase::first, EditBone::flag, EditBone::next, and EditBone::parent.
Referenced by armature_delete_selected_exec().
void ED_armature_edit_free (struct Object * ob)
Definition at line 1921 of file editarmature.c.
References BLI_freelistN(), Object::data, bArmature::edbo, ListBase::first, IDP_FreeProperty(), MEM_freeN(), EditBone::next, NULL, and EditBone::prop.
Referenced by apply_armature_pose2bones_exec(), docenter_armature(), ED_armature_apply_transform(), ED_armature_to_edit(), ED_editors_exit(), ED_object_exit_editmode(), join_armature_exec(), separate_armature_bones(), and separate_armature_exec().
void ED_armature_from_edit (Object * obedit)
Definition at line 376 of file editarmature.c.
References bArmature::act_bone, bArmature::act_edbone, Bone::arm_head, Bone::arm_roll, Bone::arm_tail, armature_rebuild_pose(), BLI_addtail(), BLI_strncpy(), bone_free(), bArmature::bonebase, Bone::childbase, copy_v3_v3(), DAG_id_tag_update(), Object::data, EditBone::dist, Bone::dist, Bone::ease1, EditBone::ease1, Bone::ease2, EditBone::ease2, bArmature::edbo, ListBase::first, fix_bonelist_roll(), EditBone::flag, Bone::flag, free_bonelist(), G, G_DEBUG, EditBone::head, Bone::head, Object::id, IDP_CopyProperty(), if(), invert_m3_m3(), Bone::layer, EditBone::layer, len(), len_v3v3(), MEM_callocN(), mul_m3_v3(), Bone::name, EditBone::name, EditBone::next, ID::next, NULL, OB_RECALC_DATA, EditBone::parent, Bone::parent, Bone::prop, EditBone::prop, Bone::rad_head, EditBone::rad_head, Bone::rad_tail, EditBone::rad_tail, Bone::roll, EditBone::roll, EditBone::segments, Bone::segments, sub_v3_v3v3(), Bone::tail, EditBone::tail, EditBone::temp, vec_roll_to_mat3(), EditBone::weight, Bone::weight, EditBone::xwidth, Bone::xwidth, EditBone::zwidth, and Bone::zwidth.
Referenced by adjustGraphs(), apply_armature_pose2bones_exec(), docenter_armature(), ED_armature_apply_transform(), ED_object_exit_editmode(), join_armature_exec(), retargetGraphs(), separate_armature_bones(), and separate_armature_exec().
void ED_armature_sync_selection (ListBase * edbo)
Definition at line 100 of file editarmature.c.
References BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, BONE_UNSELECTABLE, ListBase::first, EditBone::flag, EditBone::next, and EditBone::parent.
Referenced by armature_circle_select(), armature_click_extrude_exec(), armature_delete_selected_exec(), armature_duplicate_selected_exec(), armature_extrude_exec(), armature_hide_exec(), armature_merge_exec(), armature_parent_clear_exec(), armature_reveal_exec(), armature_select_hierarchy_exec(), armature_select_linked_invoke(), bones_merge(), do_armature_box_select(), do_lasso_select_armature(), ED_armature_deselect_all(), ED_armature_deselect_all_visible(), and mouse_armature().
void ED_armature_to_edit (Object * ob)
Definition at line 1944 of file editarmature.c.
References bArmature::act_bone, bArmature::act_edbone, bArmature::bonebase, Object::data, ED_armature_edit_free(), bArmature::edbo, make_boneList(), MEM_callocN(), and NULL.
Referenced by apply_armature_pose2bones_exec(), docenter_armature(), ED_armature_apply_transform(), ED_object_enter_editmode(), join_armature_exec(), separate_armature_bones(), and separate_armature_exec().
void ED_armature_validate_active (struct bArmature * arm)
Definition at line 122 of file editarmature.c.
References bArmature::act_edbone, BONE_HIDDEN_A, EditBone::flag, and NULL.
Referenced by armature_circle_select(), armature_duplicate_selected_exec(), armature_hide_exec(), armature_reveal_exec(), BIF_retargetArc(), and do_lasso_select_armature().
int ED_do_pose_selectbuffer (Scene * scene, Base * base, unsigned int * buffer, short hits, short extend)
Definition at line 4285 of file editarmature.c.
References bArmature::act_bone, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, BONE_UNSELECTABLE, DAG_id_tag_update(), Object::data, ED_pose_deselectall(), ED_vgroup_select_by_name(), Bone::flag, get_bone_from_selectbuffer(), Object::mode, Bone::name, NULL, OB_MODE_WEIGHT_PAINT, OB_RECALC_DATA, OBACT, Base::object, and Object::pose.
Referenced by mouse_select().
void ED_pose_deselectall (Object * ob, int test)
Definition at line 4352 of file editarmature.c.
References bPoseChannel::bone, BONE_HIDDEN_P, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, BONE_UNSELECTABLE, bPose::chanbase, Object::data, ELEM, ListBase::first, Bone::flag, Bone::layer, bArmature::layer, bPoseChannel::next, NULL, PBONE_VISIBLE, and Object::pose.
Referenced by ED_do_pose_selectbuffer(), tree_element_active_bone(), and tree_element_active_posechannel().
float ED_rollBoneToVector (EditBone * bone, const float align_axis[3], const short axis_only)
Definition at line 1961 of file editarmature.c.
References angle_v3v3(), cross_v3_v3v3(), dot_v3v3(), EditBone::head, is_zero_v3(), M_PI, negate_v3(), project_v3_v3v3(), sub_v3_v3v3(), EditBone::tail, and vec_roll_to_mat3().
Referenced by armature_calc_roll_exec(), recalcData_view3d(), rollBoneByQuat(), rollBoneByQuatAligned(), rollBoneByQuatJoint(), and setBoneRollFromNormal().
static void editbone_clear_parent (EditBone * ebone, int mode) [static]
Definition at line 3890 of file editarmature.c.
References BONE_CONNECTED, BONE_TIPSEL, EditBone::flag, NULL, and EditBone::parent.
Referenced by armature_parent_clear_exec().
static EditBone* editbone_get_child (bArmature * arm, EditBone * pabone, short use_visibility) [static]
Definition at line 1371 of file editarmature.c.
References BONE_HIDDEN_A, bArmature::edbo, ListBase::first, EditBone::flag, EditBone::layer, bArmature::layer, EditBone::next, NULL, and EditBone::parent.
Referenced by armature_select_hierarchy_exec().
static EditBone* editbone_name_exists (ListBase * edbo, const char * name) [static]
Definition at line 600 of file editarmature.c.
References BLI_findstring().
Referenced by apply_armature_pose2bones_exec(), armature_delete_selected_exec(), ED_armature_bone_rename(), editbone_unique_check(), join_armature_exec(), and separate_armature_bones().
static int editbone_unique_check (void * arg, const char * name) [static]
Definition at line 606 of file editarmature.c.
References data, and editbone_name_exists().
Referenced by unique_editbone_name().
static void* editBones_to_undoBones (void * armv, void * UNUSEDobdata) [static]
Definition at line 2162 of file editarmature.c.
References bArmature::act_edbone, UndoArmature::act_edbone, BLI_addtail(), bArmature::edbo, ListBase::first, UndoArmature::lb, MEM_callocN(), MEM_dupallocN(), EditBone::next, EditBone::parent, and EditBone::temp.
Referenced by undo_push_armature().
static void envelope_bone_weighting (Object * ob, Mesh * mesh, float(*) verts[3], int numbones, Bone ** bonelist, bDeformGroup ** dgrouplist, bDeformGroup ** dgroupflip, float(*) root[3], float(*) tip[3], int * selected, float scale) [static]
Definition at line 4520 of file editarmature.c.
References Bone::dist, distance(), distfactor_to_bone(), ED_vgroup_vert_add(), ED_vgroup_vert_remove(), i, mesh_get_x_mirror_vert(), Bone::rad_head, Bone::rad_tail, Mesh::totvert, and WEIGHT_REPLACE.
Referenced by add_verts_to_dgroups().
static void fill_add_joint (EditBone * ebo, short eb_tail, ListBase * points) [static]
Definition at line 2754 of file editarmature.c.
References BLI_addtail(), copy_v3_v3(), equals_v3v3(), ListBase::first, EditBone::head, EditBonePoint::head_owner, MEM_callocN(), EditBonePoint::next, EditBone::parent, EditBone::tail, EditBonePoint::tail_owner, and EditBonePoint::vec.
Referenced by armature_fill_bones_exec().
static void fix_bonelist_roll (ListBase * bonelist, ListBase * editbonelist) [static]
Definition at line 330 of file editarmature.c.
References Bone::arm_mat, KDL::atan2(), Bone::childbase, copy_m3_m4(), ListBase::first, EditBone::head, invert_m3_m3(), mul_m3_m3m3(), Bone::name, Bone::next, EditBone::next, Bone::parent, print_m4(), RAD2DEGF, Bone::roll, EditBone::roll, sub_v3_v3v3(), EditBone::tail, EditBone::temp, vec_roll_to_mat3(), and where_is_armature_bone().
Referenced by ED_armature_from_edit().
static void fix_connected_bone (EditBone * ebone) [static]
Definition at line 4121 of file editarmature.c.
References add_v3_v3(), BONE_CONNECTED, KDL::diff(), equals_v3v3(), EditBone::flag, EditBone::head, EditBone::parent, sub_v3_v3v3(), and EditBone::tail.
Referenced by fix_editbone_connected_children().
static void fix_editbone_connected_children (ListBase * edbo, EditBone * ebone) [static]
Definition at line 4136 of file editarmature.c.
References BONE_CONNECTED, ListBase::first, fix_connected_bone(), EditBone::flag, EditBone::next, and EditBone::parent.
Referenced by bone_align_to_bone().
static void free_undoBones (void * uarmv) [static]
Definition at line 2191 of file editarmature.c.
References BLI_freelistN(), UndoArmature::lb, and MEM_freeN().
Referenced by undo_push_armature().
static void* get_armature_edit (bContext * C) [static]
Definition at line 2199 of file editarmature.c.
References CTX_data_edit_object(), Object::data, NULL, OB_ARMATURE, and Object::type.
Referenced by undo_push_armature().
static void* get_bone_from_selectbuffer (Scene * scene, Base * base, unsigned int * buffer, short hits, short findunsel) [static]
Definition at line 1275 of file editarmature.c.
References BLI_findlink(), BONE_SELECTED, BONESEL_ANY, BONESEL_NOSEL, Object::data, data, bArmature::edbo, EditBone::flag, Bone::flag, get_indexed_bone(), i, NULL, Scene::obedit, Base::object, and Base::selcol.
Referenced by ED_do_pose_selectbuffer(), and get_nearest_bone().
Bone* get_indexed_bone (Object * ob, int index) [read]
Definition at line 1263 of file editarmature.c.
References BLI_findlink(), bPoseChannel::bone, bPose::chanbase, NULL, and Object::pose.
Referenced by do_object_pose_box_select(), and get_bone_from_selectbuffer().
static EditBone* get_named_editbone (ListBase * edbo, char * name) [static]
Definition at line 2440 of file editarmature.c.
References ListBase::first, EditBone::name, EditBone::next, and NULL.
Referenced by updateDuplicateSubtargetObjects().
static void* get_nearest_bone (bContext * C, short findunsel, int x, int y) [static]
Definition at line 1348 of file editarmature.c.
References Scene::basact, get_bone_from_selectbuffer(), MAXPICKBUF, NULL, ViewContext::scene, view3d_opengl_select(), view3d_set_viewcontext(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by armature_select_linked_invoke(), and pose_select_connected_invoke().
static EditBone* get_nearest_editbonepoint (ViewContext * vc, const int mval[2], ListBase * edbo, int findunsel, int * selmask) [static]
Definition at line 1582 of file editarmature.c.
References BLI_findlink(), BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, BONESEL_ANY, BONESEL_BONE, BONESEL_NOSEL, BONESEL_ROOT, BONESEL_TIP, EditBone::flag, i, MAXPICKBUF, NULL, view3d_opengl_select(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by mouse_armature().
static int hide_selected_pose_bone_cb (Object * ob, Bone * bone, void * UNUSEDptr) [static]
Definition at line 5144 of file editarmature.c.
References bArmature::act_bone, BONE_HIDDEN_P, BONE_SELECTED, Object::data, Bone::flag, Bone::layer, bArmature::layer, and NULL.
Referenced by pose_hide_exec().
static int hide_unselected_pose_bone_cb (Object * ob, Bone * bone, void * UNUSEDptr) [static]
Definition at line 5159 of file editarmature.c.
References bArmature::act_bone, BONE_HIDDEN_P, BONE_SELECTED, Object::data, Bone::flag, Bone::layer, bArmature::layer, and NULL.
Referenced by pose_hide_exec().
int join_armature_exec (bContext * C, wmOperator * UNUSEDop)
Definition at line 901 of file editarmature.c.
References KDL::atan2(), BLI_addtail(), BLI_remlink(), BLI_strncpy(), copy_m4_m3(), CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_scene_sort(), Object::data, ED_armature_edit_free(), ED_armature_from_edit(), ED_armature_to_edit(), ED_base_object_free_and_unlink(), bArmature::edbo, editbone_name_exists(), free_pose_channels_hash(), if(), invert_m4_m4(), joined_armature_fix_links(), Object::mode, mul_m4_m3m4(), mul_m4_v3(), mult_m4_m4m4(), NC_SCENE, ND_OB_ACTIVE, NULL, OB_ARMATURE, OB_MODE_POSE, Object::obmat, OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, sub_v3_v3v3(), Object::type, unique_editbone_name(), unit_m4(), vec_roll_to_mat3(), and WM_event_add_notifier().
Referenced by join_exec().
static void joined_armature_fix_links (Object * tarArm, Object * srcArm, bPoseChannel * pchan, EditBone * curbone) [static]
Definition at line 798 of file editarmature.c.
References bActionConstraint::act, BLI_strncpy(), bPose::chanbase, bAction::chanbase, constraint_get_typeinfo(), CONSTRAINT_TYPE_ACTION, bPoseChannel::constraints, Object::constraints, data, bConstraint::data, ListBase::first, bConstraintTypeInfo::flush_constraint_targets, G, bConstraintTypeInfo::get_constraint_targets, Object::id, bPoseChannel::name, bActionChannel::name, EditBone::name, bPoseChannel::next, bConstraint::next, bConstraintTarget::next, bActionChannel::next, ID::next, NULL, OB_ARMATURE, PARBONE, Object::parent, Object::parsubstr, Object::partype, Object::pose, bConstraintTarget::subtarget, bConstraintTarget::tar, bConstraint::type, and Object::type.
Referenced by join_armature_exec().
EditBone* make_boneList (ListBase * edbo, ListBase * bones, EditBone * parent, Bone * actBone)
Definition at line 247 of file editarmature.c.
References Bone::arm_head, Bone::arm_roll, Bone::arm_tail, BLI_addtail(), BLI_strncpy(), BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, Bone::childbase, copy_v3_v3(), EditBone::dist, Bone::dist, Bone::ease1, EditBone::ease1, Bone::ease2, EditBone::ease2, ListBase::first, EditBone::flag, Bone::flag, EditBone::head, IDP_CopyProperty(), Bone::layer, EditBone::layer, EditBone::length, Bone::length, make_boneList(), MEM_callocN(), Bone::name, EditBone::name, Bone::next, NULL, EditBone::parent, Bone::prop, EditBone::prop, Bone::rad_head, EditBone::rad_head, Bone::rad_tail, EditBone::rad_tail, EditBone::roll, EditBone::segments, Bone::segments, EditBone::tail, EditBone::weight, Bone::weight, EditBone::xwidth, Bone::xwidth, EditBone::zwidth, and Bone::zwidth.
Referenced by armatureSelectedToGraph(), ED_armature_to_edit(), make_boneList(), and RIG_graphFromArmature().
int mouse_armature (bContext * C, const int mval[2], int extend)
Definition at line 1842 of file editarmature.c.
References bArmature::act_edbone, BIF_sk_selectStroke(), BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, CTX_data_edit_object(), Object::data, ebone_select_flag(), ED_armature_deselect_all(), ED_armature_sync_selection(), bArmature::edbo, EditBone::flag, get_nearest_editbonepoint(), NC_OBJECT, ND_BONE_SELECT, NULL, ViewContext::obedit, EditBone::parent, view3d_set_viewcontext(), and WM_event_add_notifier().
Referenced by view3d_select_invoke().
static void pchan_clear_loc (bPoseChannel * pchan) [static]
Definition at line 4774 of file editarmature.c.
References bPoseChannel::loc, OB_LOCK_LOCX, OB_LOCK_LOCY, OB_LOCK_LOCZ, and bPoseChannel::protectflag.
Referenced by pchan_clear_transforms(), and pose_clear_loc_exec().
static void pchan_clear_rot (bPoseChannel * pchan) [static]
Definition at line 4785 of file editarmature.c.
References axis_angle_to_eulO(), copy_v3_v3(), bPoseChannel::eul, eul_to_quat(), EULER_ORDER_DEFAULT, eulO_to_axis_angle(), IS_EQF, mul_qt_fl(), normalize_qt_qt(), OB_LOCK_ROT4D, OB_LOCK_ROTW, OB_LOCK_ROTX, OB_LOCK_ROTY, OB_LOCK_ROTZ, bPoseChannel::protectflag, bPoseChannel::quat, quat_to_eul(), ROT_MODE_AXISANGLE, ROT_MODE_QUAT, bPoseChannel::rotAngle, bPoseChannel::rotAxis, bPoseChannel::rotmode, unit_axis_angle(), unit_qt(), and zero_v3().
Referenced by pchan_clear_transforms(), and pose_clear_rot_exec().
static void pchan_clear_scale (bPoseChannel * pchan) [static]
Definition at line 4763 of file editarmature.c.
References OB_LOCK_SCALEX, OB_LOCK_SCALEY, OB_LOCK_SCALEZ, bPoseChannel::protectflag, and bPoseChannel::size.
Referenced by pchan_clear_transforms(), and pose_clear_scale_exec().
static void pchan_clear_transforms (bPoseChannel * pchan) [static]
Definition at line 4884 of file editarmature.c.
References pchan_clear_loc(), pchan_clear_rot(), and pchan_clear_scale().
Referenced by pose_clear_transforms_exec().
static int pose_clear_loc_exec (bContext * C, wmOperator * op) [static]
Definition at line 4995 of file editarmature.c.
References ANIM_KS_LOCATION_ID, pchan_clear_loc(), and pose_clear_transform_generic_exec().
Referenced by POSE_OT_loc_clear().
static int pose_clear_rot_exec (bContext * C, wmOperator * op) [static]
Definition at line 4974 of file editarmature.c.
References ANIM_KS_ROTATION_ID, pchan_clear_rot(), and pose_clear_transform_generic_exec().
Referenced by POSE_OT_rot_clear().
static int pose_clear_scale_exec (bContext * C, wmOperator * op) [static]
Definition at line 4953 of file editarmature.c.
References ANIM_KS_SCALING_ID, pchan_clear_scale(), and pose_clear_transform_generic_exec().
Referenced by POSE_OT_scale_clear().
static int pose_clear_transform_generic_exec (bContext * C, wmOperator * op, void(*)(bPoseChannel *) clear_func, const char default_ksName[]) [static]
Definition at line 4894 of file editarmature.c.
References ANIM_apply_keyingset(), ANIM_get_keyingset_for_autokeying(), autokeyframe_cfra_can_key(), bPose::avs, BKE_report(), BONE_UNKEYED, CFRA, CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_scene(), DAG_id_tag_update(), ED_pose_recalculate_paths(), ELEM, Object::id, MODIFYKEY_MODE_INSERT, MOTIONPATH_BAKE_HAS_PATHS, NC_OBJECT, ND_TRANSFORM, NULL, OB_RECALC_DATA, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, bAnimVizSettings::path_bakeflag, Object::pose, wmOperator::reports, RPT_ERROR, and WM_event_add_notifier().
Referenced by pose_clear_loc_exec(), pose_clear_rot_exec(), pose_clear_scale_exec(), and pose_clear_transforms_exec().
static int pose_clear_transforms_exec (bContext * C, wmOperator * op) [static]
Definition at line 5016 of file editarmature.c.
References ANIM_KS_LOC_ROT_SCALE_ID, pchan_clear_transforms(), and pose_clear_transform_generic_exec().
Referenced by POSE_OT_transforms_clear().
static int pose_de_select_all_exec (bContext * C, wmOperator * op) [static]
Definition at line 5038 of file editarmature.c.
References BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, BONE_UNSELECTABLE, CTX_DATA_BEGIN, CTX_DATA_COUNT, CTX_DATA_END, CTX_data_scene(), DAG_id_tag_update(), ED_object_context(), Object::id, ToolSettings::multipaint, NC_OBJECT, ND_BONE_SELECT, NULL, OB_RECALC_DATA, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, Scene::toolsettings, and WM_event_add_notifier().
Referenced by POSE_OT_select_all().
static int pose_hide_exec (bContext * C, wmOperator * op) [static]
Definition at line 5175 of file editarmature.c.
References bone_looper(), bArmature::bonebase, CTX_data_active_object(), Object::data, ListBase::first, hide_selected_pose_bone_cb(), hide_unselected_pose_bone_cb(), NC_OBJECT, ND_BONE_SELECT, NULL, object_pose_armature_get(), OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), and WM_event_add_notifier().
Referenced by POSE_OT_hide().
void POSE_OT_armature_apply (wmOperatorType * ot)
Definition at line 729 of file editarmature.c.
References apply_armature_pose2bones_exec(), wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void POSE_OT_hide (wmOperatorType * ot)
Definition at line 5191 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_hide_exec(), RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_loc_clear (wmOperatorType * ot)
Definition at line 5000 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_clear_loc_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_reveal (wmOperatorType * ot)
Definition at line 5237 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_reveal_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_rot_clear (wmOperatorType * ot)
Definition at line 4979 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_clear_rot_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_scale_clear (wmOperatorType * ot)
Definition at line 4958 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_clear_scale_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_select_all (wmOperatorType * ot)
Definition at line 5082 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_de_select_all_exec(), and WM_operator_properties_select_all().
Referenced by ED_operatortypes_armature().
void POSE_OT_select_linked (wmOperatorType * ot)
Definition at line 1467 of file editarmature.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_select_connected_invoke(), pose_select_linked_poll(), RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_select_parent (wmOperatorType * ot)
Definition at line 5126 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_select_parent_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_transforms_clear (wmOperatorType * ot)
Definition at line 5021 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_clear_transforms_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_visual_transform_apply (wmOperatorType * ot)
Definition at line 780 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_visual_transform_apply_exec().
Referenced by ED_operatortypes_armature().
static int pose_reveal_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 5224 of file editarmature.c.
References bone_looper(), bArmature::bonebase, CTX_data_active_object(), Object::data, ListBase::first, NC_OBJECT, ND_BONE_SELECT, NULL, object_pose_armature_get(), OPERATOR_FINISHED, show_pose_bone_cb(), and WM_event_add_notifier().
Referenced by POSE_OT_reveal().
static int pose_select_connected_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1416 of file editarmature.c.
References BONE_CONNECTED, BONE_SELECTED, BONE_UNSELECTABLE, Bone::childbase, CTX_data_edit_object(), ListBase::first, Bone::flag, get_nearest_bone(), wmEvent::mval, NC_OBJECT, ND_BONE_SELECT, next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Bone::parent, wmOperator::ptr, RNA_boolean_get(), selectconnected_posebonechildren(), view3d_operator_needs_opengl(), and WM_event_add_notifier().
Referenced by POSE_OT_select_linked().
static int pose_select_linked_poll (bContext * C) [static]
Definition at line 1462 of file editarmature.c.
References ED_operator_posemode(), and ED_operator_view3d_active().
Referenced by POSE_OT_select_linked().
static int pose_select_parent_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 5099 of file editarmature.c.
References bArmature::act_bone, bPoseChannel::bone, BONE_HIDDEN_P, BONE_SELECTED, BONE_UNSELECTABLE, CTX_data_active_object(), CTX_data_active_pose_bone(), Object::data, Bone::flag, NC_OBJECT, ND_BONE_SELECT, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, bPoseChannel::parent, and WM_event_add_notifier().
Referenced by POSE_OT_select_parent().
static int pose_visual_transform_apply_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 746 of file editarmature.c.
References copy_m4_m4(), CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, DAG_id_tag_update(), Object::id, NC_OBJECT, ND_POSE, OB_ARMATURE, OB_RECALC_DATA, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, pchan_apply_mat4(), TRUE, Object::type, and WM_event_add_notifier().
Referenced by POSE_OT_visual_transform_apply().
void preEditBoneDuplicate (ListBase * editbones)
Definition at line 2456 of file editarmature.c.
References ListBase::first, EditBone::next, NULL, and EditBone::temp.
Referenced by armature_duplicate_selected_exec(), and cloneRigGraph().
static void selectconnected_posebonechildren (Object * ob, Bone * bone, int extend) [static]
Definition at line 1394 of file editarmature.c.
References BONE_CONNECTED, BONE_SELECTED, BONE_UNSELECTABLE, Bone::childbase, ListBase::first, Bone::flag, and Bone::next.
Referenced by pose_select_connected_invoke().
static void separate_armature_bones (Object * ob, short sel) [static]
Definition at line 1119 of file editarmature.c.
References BLI_freelinkN(), BONE_CONNECTED, bone_free(), BONE_SELECTED, bPose::chanbase, Object::data, ED_armature_edit_free(), ED_armature_from_edit(), ED_armature_to_edit(), bArmature::edbo, editbone_name_exists(), ListBase::first, EditBone::flag, free_pose_channel(), free_pose_channels_hash(), bPoseChannel::name, bPoseChannel::next, EditBone::next, NULL, EditBone::parent, bPoseChannel::parent, Object::pose, and EditBone::temp.
Referenced by separate_armature_exec().
static int separate_armature_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1171 of file editarmature.c.
References BASACT, CTX_DATA_BEGIN, CTX_data_edit_object(), CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_id_tag_update(), ED_armature_edit_free(), ED_armature_from_edit(), ED_armature_to_edit(), ED_object_add_duplicate(), Base::flag, Object::id, Object::mode, NC_OBJECT, ND_POSE, NULL, OB_MODE_POSE, OB_RECALC_DATA, Base::object, OPERATOR_CANCELLED, OPERATOR_FINISHED, SELECT, separate_armature_bones(), separated_armature_fix_links(), USER_DUP_ARM, WM_cursor_wait(), and WM_event_add_notifier().
Referenced by ARMATURE_OT_separate().
static void separated_armature_fix_links (Object * origArm, Object * newArm) [static]
Definition at line 1014 of file editarmature.c.
References BLI_findstring(), bPose::chanbase, constraint_get_typeinfo(), bPoseChannel::constraints, Object::constraints, ListBase::first, bConstraintTypeInfo::flush_constraint_targets, G, bConstraintTypeInfo::get_constraint_targets, Object::id, bPoseChannel::next, bConstraint::next, bConstraintTarget::next, ID::next, NULL, OB_ARMATURE, PARBONE, Object::parent, Object::parsubstr, Object::partype, Object::pose, bConstraintTarget::subtarget, bConstraintTarget::tar, and Object::type.
Referenced by separate_armature_exec().
static int show_pose_bone_cb (Object * ob, Bone * bone, void * UNUSEDptr) [static]
Definition at line 5209 of file editarmature.c.
References BONE_HIDDEN_P, BONE_SELECTED, Object::data, Bone::flag, Bone::layer, and bArmature::layer.
Referenced by pose_reveal_exec().
void transform_armature_mirror_update (Object * obedit)
Definition at line 5530 of file editarmature.c.
References BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, copy_v3_v3(), Object::data, EditBone::dist, ED_armature_bone_get_mirrored(), bArmature::edbo, ListBase::first, EditBone::flag, EditBone::head, EditBone::next, EditBone::parent, EditBone::rad_head, EditBone::rad_tail, EditBone::roll, EditBone::tail, EditBone::xwidth, and EditBone::zwidth.
Referenced by recalcData_view3d(), and special_transvert_update().
void undo_push_armature (bContext * C, const char * name)
Definition at line 2209 of file editarmature.c.
References editBones_to_undoBones(), free_undoBones(), get_armature_edit(), NULL, undo_editmode_push(), and undoBones_to_editBones().
Referenced by ED_undo_push().
static void undoBones_to_editBones (void * uarmv, void * armv, void * UNUSEDdata) [static]
Definition at line 2129 of file editarmature.c.
References bArmature::act_edbone, UndoArmature::act_edbone, BLI_addtail(), BLI_freelistN(), bArmature::edbo, ListBase::first, UndoArmature::lb, MEM_dupallocN(), EditBone::next, NULL, EditBone::parent, and EditBone::temp.
Referenced by undo_push_armature().
static void unique_bone_name (bArmature * arm, char * name) [static]
Definition at line 5259 of file editarmature.c.
References BLI_uniquename_cb(), bone_unique_check(), and NULL.
Referenced by ED_armature_bone_rename().
void unique_editbone_name (ListBase * edbo, char * name, EditBone * bone)
Definition at line 613 of file editarmature.c.
References BLI_uniquename_cb(), data, editbone_unique_check(), and EditBone::name.
Referenced by armature_extrude_exec(), armature_subdivide_exec(), duplicateEditBoneObjects(), ED_armature_bone_rename(), ED_armature_edit_bone_add(), join_armature_exec(), and renameTemplateBone().
void updateDuplicateSubtarget (EditBone * dupBone, ListBase * editbones, Object * ob)
Definition at line 2520 of file editarmature.c.
References updateDuplicateSubtargetObjects().
Referenced by armature_duplicate_selected_exec().
void updateDuplicateSubtargetObjects (EditBone * dupBone, ListBase * editbones, Object * src_ob, Object * dst_ob)
Definition at line 2471 of file editarmature.c.
References BLI_strncpy(), constraint_get_typeinfo(), bPoseChannel::constraints, ListBase::first, bConstraintTypeInfo::flush_constraint_targets, bConstraintTypeInfo::get_constraint_targets, get_named_editbone(), EditBone::name, bConstraint::next, bConstraintTarget::next, NULL, Object::pose, bConstraintTarget::subtarget, bConstraintTarget::tar, EditBone::temp, and verify_pose_channel().
Referenced by cloneRigGraph(), and updateDuplicateSubtarget().
static int vgroup_add_unique_bone_cb (Object * ob, Bone * bone, void * UNUSEDptr) [static]
Definition at line 4440 of file editarmature.c.
References BONE_NO_DEFORM, defgroup_find_name(), ED_vgroup_add_name(), Bone::flag, and Bone::name.
Referenced by create_vgroups_from_armature().
Variable Documentation
EnumPropertyItem prop_calc_roll_types[] [static]
Initial value:
 {
    {0, "X", 0, "X Axis", ""},
    {1, "Y", 0, "Y Axis", ""},
    {2, "Z", 0, "Z Axis", ""},
    {5, "ACTIVE", 0, "Active Bone", ""},
    {6, "VIEW", 0, "View Axis", ""},
    {7, "CURSOR", 0, "Cursor", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 1997 of file editarmature.c.
EnumPropertyItem prop_editarm_clear_parent_types[] [static]
Initial value:
 {
    {1, "CLEAR", 0, "Clear Parent", ""},
    {2, "DISCONNECT", 0, "Disconnect Bone", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 3884 of file editarmature.c.
EnumPropertyItem prop_editarm_make_parent_types[] [static]
Initial value:
 {
    {ARM_PAR_CONNECT, "CONNECTED", 0, "Connected", ""},
    {ARM_PAR_OFFSET, "OFFSET", 0, "Keep Offset", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 3767 of file editarmature.c.