Blender: TransformBase Class Reference
TransformBase Class Reference
#include <collada_internal.h>
Public Member Functions
void decompose (float mat[][4], float *loc, float eul[3], float quat[4], float *size)
Detailed Description
Definition at line 77 of file collada_internal.h.
Member Function Documentation
void TransformBase::decompose (float mat[][4], float * loc, float eul[3], float quat[4], float * size)
Definition at line 101 of file collada_internal.cpp.
References copy_v3_v3(), mat4_to_eul(), mat4_to_quat(), and mat4_to_size().
Referenced by TransformWriter::add_node_transform().
The documentation for this class was generated from the following files:
collada_internal.h
collada_internal.cpp