Blender: DbvtCullingCallback Struct Reference
DbvtCullingCallback Struct Reference
Public Member Functions
DbvtCullingCallback (PHY_CullingCallback clientCallback, void *userData)
bool Descent (const btDbvtNode *node)
void Process (const btDbvtNode *node, btScalar depth)
void Process (const btDbvtNode *leaf)
Public Attributes
PHY_CullingCallback m_clientCallback
void * m_userData
OcclusionBuffer * m_ocb
Detailed Description
Definition at line 1713 of file CcdPhysicsEnvironment.cpp.
Constructor & Destructor Documentation
DbvtCullingCallback::DbvtCullingCallback (PHY_CullingCallback clientCallback, void * userData) [inline]
Definition at line 1719 of file CcdPhysicsEnvironment.cpp.
References NULL.
Member Function Documentation
bool DbvtCullingCallback::Descent (const btDbvtNode * node) [inline]
Reimplemented from btDbvt::ICollide.
Definition at line 1725 of file CcdPhysicsEnvironment.cpp.
References btDbvtAabbMm::Center(), btDbvtAabbMm::Extents(), and btDbvtNode::volume.
void DbvtCullingCallback::Process (const btDbvtNode * leaf) [inline]
Reimplemented from btDbvt::ICollide.
Definition at line 1733 of file CcdPhysicsEnvironment.cpp.
References btDbvtNode::data, KX_GameObject::GetClientObject(), KX_GameObject::GetMesh(), KX_GameObject::GetMeshCount(), KX_GameObject::GetOccluder(), KX_GameObject::GetOpenGLMatrixPtr(), MT_CmMatrix4x4::getPointer(), RAS_MeshObject::GetPolygon(), RAS_Polygon::GetVertex(), RAS_TexVert::getXYZ(), KX_GameObject::IsNegativeScaling(), RAS_Polygon::IsTwoside(), RAS_MeshObject::NumPolygons(), and RAS_Polygon::VertexCount().
void DbvtCullingCallback::Process (const btDbvtNode * node, btScalar depth) [inline]
Reimplemented from btDbvt::ICollide.
Definition at line 1729 of file CcdPhysicsEnvironment.cpp.
Member Data Documentation
PHY_CullingCallback DbvtCullingCallback::m_clientCallback
Definition at line 1715 of file CcdPhysicsEnvironment.cpp.
OcclusionBuffer* DbvtCullingCallback::m_ocb
Definition at line 1717 of file CcdPhysicsEnvironment.cpp.
Referenced by CcdPhysicsEnvironment::cullingTest().
void* DbvtCullingCallback::m_userData
Definition at line 1716 of file CcdPhysicsEnvironment.cpp.
The documentation for this struct was generated from the following file:
CcdPhysicsEnvironment.cpp