Blender: svm_attribute.h File Reference
svm_attribute.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void svm_node_attr_init (KernelGlobals *kg, ShaderData *sd, uint4 node, NodeAttributeType *type, NodeAttributeType *mesh_type, AttributeElement *elem, uint *offset, uint *out_offset)
__device void svm_node_attr (KernelGlobals *kg, ShaderData *sd, float *stack, uint4 node)
__device void svm_node_attr_bump_dx (KernelGlobals *kg, ShaderData *sd, float *stack, uint4 node)
__device void svm_node_attr_bump_dy (KernelGlobals *kg, ShaderData *sd, float *stack, uint4 node)
Function Documentation
__device void svm_node_attr (KernelGlobals * kg, ShaderData * sd, float * stack, uint4 node)
Definition at line 52 of file svm_attribute.h.
References average(), make_float3(), NODE_ATTR_FLOAT, NODE_ATTR_FLOAT3, NULL, stack_store_float(), stack_store_float3(), svm_node_attr_init(), triangle_attribute_float(), and triangle_attribute_float3().
Referenced by svm_eval_nodes().
__device void svm_node_attr_bump_dx (KernelGlobals * kg, ShaderData * sd, float * stack, uint4 node)
Definition at line 83 of file svm_attribute.h.
References average(), make_float3(), NODE_ATTR_FLOAT, NODE_ATTR_FLOAT3, NULL, stack_store_float(), stack_store_float3(), svm_node_attr_init(), triangle_attribute_float(), and triangle_attribute_float3().
Referenced by svm_eval_nodes().
__device void svm_node_attr_bump_dy (KernelGlobals * kg, ShaderData * sd, float * stack, uint4 node)
Definition at line 118 of file svm_attribute.h.
References average(), make_float3(), NODE_ATTR_FLOAT, NODE_ATTR_FLOAT3, NULL, stack_store_float(), stack_store_float3(), svm_node_attr_init(), triangle_attribute_float(), and triangle_attribute_float3().
Referenced by svm_eval_nodes().
CCL_NAMESPACE_BEGIN __device void svm_node_attr_init (KernelGlobals * kg, ShaderData * sd, uint4 node, NodeAttributeType * type, NodeAttributeType * mesh_type, AttributeElement * elem, uint * offset, uint * out_offset)
Definition at line 23 of file svm_attribute.h.
References ATTR_ELEMENT_NONE, kernel_data, kernel_tex_fetch, ShaderData::object, uint4::w, uint4::x, uint4::y, and uint4::z.
Referenced by svm_node_attr(), svm_node_attr_bump_dx(), and svm_node_attr_bump_dy().