Blender: bmesh_walkers.h File Reference
bmesh_walkers.h File Reference
BMesh
#include "BLI_ghash.h"
Classes
struct BMWalker
Defines
#define BMW_MASK_NOP 0
#define BMW_NIL_LAY 0
Typedefs
typedef struct BMWalker BMWalker
Enumerations
enum BMWOrder { BMW_DEPTH_FIRST, BMW_BREADTH_FIRST }
enum BMWFlag { BMW_FLAG_NOP = 0, BMW_FLAG_TEST_HIDDEN = (1 << 0) }
enum {
BMW_SHELL, BMW_LOOP, BMW_FACELOOP, BMW_EDGERING,
BMW_LOOPDATA_ISLAND, BMW_ISLANDBOUND, BMW_ISLAND, BMW_CONNECTED_VERTEX,
BMW_CUSTOM, BMW_MAXWALKERS
}
Functions
void BMW_init (struct BMWalker *walker, BMesh *bm, int type, short mask_vert, short mask_edge, short mask_face, BMWFlag flag, int layer)
Init Walker.
void * BMW_begin (BMWalker *walker, void *start)
void * BMW_step (struct BMWalker *walker)
Step Walker.
void BMW_end (struct BMWalker *walker)
End Walker.
int BMW_current_depth (BMWalker *walker)
Walker Current Depth.
void * BMW_current_state (BMWalker *walker)
Current Walker State.
void * BMW_state_add (BMWalker *walker)
Add a new Walker State.
void BMW_state_remove (BMWalker *walker)
Remove Current Walker State.
void * BMW_walk (BMWalker *walker)
Main Walking Function.
void BMW_reset (BMWalker *walker)
Reset Walker.
Detailed Description
Definition in file bmesh_walkers.h.
Define Documentation
#define BMW_MASK_NOP 0
Definition at line 76 of file bmesh_walkers.h.
Referenced by bmo_collapse_exec(), bmo_collapsecon_do_layer(), bmo_dissolve_faces_exec(), check_hole_in_region(), edbm_select_linked_exec(), edbm_select_linked_pick_invoke(), edgering_sel(), mesh_separate_loose(), and walker_select().
#define BMW_NIL_LAY 0
Definition at line 148 of file bmesh_walkers.h.
Referenced by bmo_collapse_exec(), bmo_dissolve_faces_exec(), check_hole_in_region(), edbm_select_linked_exec(), edbm_select_linked_pick_invoke(), edgering_sel(), mesh_separate_loose(), walker_deselect_nth(), and walker_select().
Typedef Documentation
typedef struct BMWalker BMWalker
Enumeration Type Documentation
anonymous enum
Enumerator:
BMW_SHELL
BMW_LOOP
BMW_FACELOOP
BMW_EDGERING
BMW_LOOPDATA_ISLAND
BMW_ISLANDBOUND
BMW_ISLAND
BMW_CONNECTED_VERTEX
BMW_CUSTOM
BMW_MAXWALKERS
Definition at line 111 of file bmesh_walkers.h.
enum BMWFlag
Enumerator:
BMW_FLAG_NOP
BMW_FLAG_TEST_HIDDEN
Definition at line 41 of file bmesh_walkers.h.
enum BMWOrder
Enumerator:
BMW_DEPTH_FIRST
BMW_BREADTH_FIRST
Definition at line 36 of file bmesh_walkers.h.
Function Documentation
void* BMW_begin (BMWalker * walker, void * start)
joeedh - design notes:
original desing: walkers directly emulation recursive functions. functions save their state onto a worklist, and also add new states to implement recursive or looping behavior. generally only one state push per call with a specific state is desired.
basic design pattern: the walker step function goes through it's list of possible choices for recursion, and recurses (by pushing a new state) using the first non-visited one. this choise is the flagged as visited using the ghash. each step may push multiple new states onto the worklist at once.
Walkers use tool flags, not header flags.
Walkers now use ghash for storing visited elements, rather then stealing flags. ghash can be rewritten to be faster if necessary, in the far future :) .
tools should ALWAYS have necessary error handling for if walkers fail.
Definition at line 61 of file bmesh_walkers.c.
References BMWalker::begin, BMW_current_state(), NULL, and BMWalker::step.
Referenced by bmo_collapse_exec(), bmo_collapsecon_do_layer(), bmo_dissolve_faces_exec(), check_hole_in_region(), edbm_select_linked_exec(), edbm_select_linked_pick_invoke(), edgering_sel(), mesh_separate_loose(), walker_deselect_nth(), and walker_select().
int BMW_current_depth (BMWalker * walker)
Walker Current Depth.
Returns the current depth of the walker.
Definition at line 152 of file bmesh_walkers.c.
References BMWalker::depth.
Referenced by walker_deselect_nth().
void* BMW_current_state (BMWalker * walker)
Current Walker State.
Returns the first state from the walker state worklist. This state is the the next in the worklist for processing.
Definition at line 182 of file bmesh_walkers.c.
References BMWalker::depth, BMwGenericWalker::depth, ListBase::first, and BMWalker::states.
Referenced by BMW_begin(), bmw_ConnectedVertexWalker_step(), bmw_ConnectedVertexWalker_yield(), bmw_EdgeringWalker_begin(), bmw_EdgeringWalker_step(), bmw_EdgeringWalker_yield(), bmw_FaceLoopWalker_begin(), bmw_FaceLoopWalker_step(), bmw_FaceLoopWalker_yield(), bmw_IslandboundWalker_step(), bmw_IslandboundWalker_yield(), bmw_IslandWalker_step(), bmw_IslandWalker_yield(), bmw_LoopWalker_begin(), bmw_LoopWalker_step(), bmw_LoopWalker_yield(), BMW_reset(), bmw_ShellWalker_step(), bmw_ShellWalker_yield(), BMW_state_remove(), bmw_UVEdgeWalker_step(), bmw_UVEdgeWalker_yield(), and BMW_walk().
void BMW_end (BMWalker * walker)
End Walker.
Frees a walker's worklist.
Definition at line 126 of file bmesh_walkers.c.
References BLI_ghash_free(), BLI_mempool_destroy(), NULL, BMWalker::secvisithash, BMWalker::visithash, and BMWalker::worklist.
Referenced by bmo_collapse_exec(), bmo_collapsecon_do_layer(), bmo_dissolve_faces_exec(), check_hole_in_region(), edbm_select_linked_exec(), edbm_select_linked_pick_invoke(), edgering_sel(), mesh_separate_loose(), walker_deselect_nth(), and walker_select().
void BMW_init (BMWalker * walker, BMesh * bm, int type, short mask_vert, short mask_edge, short mask_face, BMWFlag flag, int layer)
Init Walker.
Allocates and returns a new mesh walker of a given type. The elements visited are filtered by the bitmask 'searchmask'.
Definition at line 75 of file bmesh_walkers.c.
References BMWalker::begin, BLI_assert, BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BLI_mempool_create(), BLI_MEMPOOL_SYSMALLOC, BMWalker::bm, BM_EDGE, BM_FACE, BM_VERT, bm_walker_types, BMESH_ASSERT, BMW_CUSTOM, BMW_MAXWALKERS, ListBase::first, BMWalker::flag, ListBase::last, BMWalker::layer, BMWalker::mask_edge, BMWalker::mask_face, BMWalker::mask_vert, NULL, BMWalker::order, BMWalker::secvisithash, BMWalker::states, BMWalker::step, BMWalker::structsize, UNLIKELY, BMWalker::valid_mask, BMWalker::visithash, BMWalker::worklist, and BMWalker::yield.
Referenced by bmo_collapse_exec(), bmo_collapsecon_do_layer(), bmo_dissolve_faces_exec(), check_hole_in_region(), edbm_select_linked_exec(), edbm_select_linked_pick_invoke(), edgering_sel(), mesh_separate_loose(), walker_deselect_nth(), and walker_select().
void BMW_reset (BMWalker * walker)
Reset Walker.
Frees all states from the worklist, resetting the walker for reuse in a new walk.
Definition at line 250 of file bmesh_walkers.c.
References BLI_ghash_free(), BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BMW_current_state(), BMW_state_remove(), BMWalker::depth, NULL, BMWalker::secvisithash, and BMWalker::visithash.
Referenced by bmw_IslandboundWalker_step().
void* BMW_state_add (BMWalker * walker)
Add a new Walker State.
Allocate a new empty state and put it on the worklist. A pointer to the new state is returned so that the caller can fill in the state data. The new state will be inserted at the front for depth-first walks, and at the end for breadth-first walks.
Definition at line 224 of file bmesh_walkers.c.
References BLI_addhead(), BLI_addtail(), BLI_assert, BLI_mempool_alloc(), BMW_BREADTH_FIRST, BMW_DEPTH_FIRST, BMwGenericWalker::depth, BMWalker::depth, BMWalker::order, BMWalker::states, and BMWalker::worklist.
Referenced by bmw_ConnectedVertexWalker_visitVertex(), bmw_EdgeringWalker_begin(), bmw_EdgeringWalker_step(), bmw_FaceLoopWalker_begin(), bmw_FaceLoopWalker_step(), bmw_IslandboundWalker_begin(), bmw_IslandboundWalker_step(), bmw_IslandWalker_begin(), bmw_IslandWalker_step(), bmw_LoopWalker_begin(), bmw_LoopWalker_step(), bmw_ShellWalker_visitEdge(), bmw_UVEdgeWalker_begin(), and bmw_UVEdgeWalker_step().
void BMW_state_remove (BMWalker * walker)
Remove Current Walker State.
Remove and free an item from the end of the walker state worklist.
Definition at line 207 of file bmesh_walkers.c.
References BLI_mempool_free(), BLI_remlink(), BMW_current_state(), BMWalker::states, and BMWalker::worklist.
Referenced by bmw_ConnectedVertexWalker_step(), bmw_EdgeringWalker_step(), bmw_FaceLoopWalker_step(), bmw_IslandboundWalker_step(), bmw_IslandWalker_step(), bmw_LoopWalker_step(), BMW_reset(), bmw_ShellWalker_step(), and bmw_UVEdgeWalker_step().
void* BMW_step (struct BMWalker * walker)
Step Walker.
Definition at line 137 of file bmesh_walkers.c.
References BMW_walk().
Referenced by bmo_collapse_exec(), bmo_collapsecon_do_layer(), bmo_dissolve_faces_exec(), check_hole_in_region(), edbm_select_linked_exec(), edbm_select_linked_pick_invoke(), edgering_sel(), mesh_separate_loose(), walker_deselect_nth(), and walker_select().
void* BMW_walk (BMWalker * walker)
Main Walking Function.
Steps a mesh walker forward by one element
Definition at line 162 of file bmesh_walkers.c.
References BMW_current_state(), NULL, and BMWalker::step.
Referenced by bmw_EdgeringWalker_begin(), bmw_FaceLoopWalker_begin(), bmw_LoopWalker_begin(), and BMW_step().