Blender: get_perm_c.c File Reference
get_perm_c.c File Reference
opennl
#include "ssp_defs.h"
#include "colamd.h"
Functions
int genmmd_ (int *, int *, int *, int *, int *, int *, int *, int *, int *, int *, int *, int *)
static void get_colamd (const int m, const int n, const int nnz, int *colptr, int *rowind, int *perm_c)
static void getata (const int m, const int n, const int nz, int *colptr, int *rowind, int *atanz, int **ata_colptr, int **ata_rowind)
static void at_plus_a (const int n, const int nz, int *colptr, int *rowind, int *bnz, int **b_colptr, int **b_rowind)
void get_perm_c (int ispec, SuperMatrix *A, int *perm_c)
Detailed Description
Definition in file get_perm_c.c.
Function Documentation
static void at_plus_a (const int n, const int nz, int * colptr, int * rowind, int * bnz, int ** b_colptr, int ** b_rowind) [static]
Definition at line 197 of file get_perm_c.c.
References ABORT, i, SUPERLU_FREE, and SUPERLU_MALLOC.
Referenced by get_perm_c(), and sp_preorder().
int genmmd_ (int * neqns, int * xadj, int * adjncy, int * invp, int * perm, int * delta, int * dhead, int * qsize, int * llist, int * marker, int * maxint, int * nofsub)
Definition at line 67 of file mmd.c.
References i, mmdelm_(), mmdint_(), mmdnum_(), and mmdupd_().
Referenced by get_perm_c().
static void get_colamd (const int m, const int n, const int nnz, int * colptr, int * rowind, int * perm_c) [static]
Definition at line 19 of file get_perm_c.c.
References A, ABORT, FALSE, i, p, SUPERLU_FREE, and SUPERLU_MALLOC.
Referenced by get_perm_c().
void get_perm_c (int ispec, SuperMatrix * A, int * perm_c)
Definition at line 333 of file get_perm_c.c.
References ABORT, at_plus_a(), NCformat::colptr, genmmd_(), get_colamd(), getata(), i, SuperMatrix::ncol, NCformat::nnz, SuperMatrix::nrow, NULL, NCformat::rowind, SuperMatrix::Store, SUPERLU_FREE, and SUPERLU_MALLOC.
Referenced by __nlFactorize_SUPERLU(), and sgssv().
static void getata (const int m, const int n, const int nz, int * colptr, int * rowind, int * atanz, int ** ata_colptr, int ** ata_rowind) [static]
Definition at line 55 of file get_perm_c.c.
References ABORT, i, SUPERLU_FREE, SUPERLU_MALLOC, and SUPERLU_MAX.
Referenced by get_perm_c().