Blender: MOD_multires.c File Reference
MOD_multires.c File Reference
modifiers
#include <stddef.h>
#include "DNA_mesh_types.h"
#include "DNA_object_types.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_mesh.h"
#include "BKE_multires.h"
#include "BKE_modifier.h"
#include "BKE_paint.h"
#include "BKE_subsurf.h"
#include "MOD_util.h"
Functions
static void initData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static DerivedMesh * applyModifier (ModifierData *md, Object *ob, DerivedMesh *dm, int useRenderParams, int isFinalCalc)
Variables
ModifierTypeInfo modifierType_Multires
Detailed Description
Definition in file MOD_multires.c.
Function Documentation
static DerivedMesh* applyModifier (ModifierData * md, Object * ob, DerivedMesh * dm, int useRenderParams, int isFinalCalc) [static]
Definition at line 73 of file MOD_multires.c.
References CD_CALLOC, CD_MDISPS, CDDM_copy(), CustomData_add_layer(), CustomData_get_layer(), Object::data, DerivedMesh::getEdgeArray, DerivedMesh::getLoopArray, DerivedMesh::getNumEdges, DerivedMesh::getNumPolys, DerivedMesh::getPolyArray, DerivedMesh::getVertArray, if(), Mesh::ldata, mesh_flush_hidden_from_verts(), Mesh::mpoly, multires_dm_create_from_derived(), NULL, DerivedMesh::release, subsurf_copy_grid_hidden(), Mesh::totloop, and MultiresModifierData::totlvl.
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 60 of file MOD_multires.c.
References MultiresModifierData::flags, MultiresModifierData::lvl, MultiresModifierData::renderlvl, MultiresModifierData::sculptlvl, MultiresModifierData::simple, and MultiresModifierData::totlvl.
static void initData (ModifierData * md) [static]
Definition at line 50 of file MOD_multires.c.
References MultiresModifierData::lvl, MultiresModifierData::renderlvl, MultiresModifierData::sculptlvl, and MultiresModifierData::totlvl.
Variable Documentation
ModifierTypeInfo modifierType_Multires
Initial value:
 {
                  "Multires",
            "MultiresModifierData",
            sizeof(MultiresModifierData),
                  eModifierTypeType_Constructive,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_SupportsMapping
                            | eModifierTypeFlag_RequiresOriginalData,
              copyData,
           NULL,
        NULL,
         NULL,
      NULL,
         applyModifier,
       NULL,
              initData,
      NULL,
              NULL,
            NULL,
        NULL,
         NULL,
        NULL,
     NULL,
         NULL,
        NULL,
}
Definition at line 123 of file MOD_multires.c.