Blender: btSoftSingleRayCallback Struct Reference
btSoftSingleRayCallback Struct Reference
Public Member Functions
btSoftSingleRayCallback (const btVector3 &rayFromWorld, const btVector3 &rayToWorld, const btSoftRigidDynamicsWorld *world, btCollisionWorld::RayResultCallback &resultCallback)
virtual bool process (const btBroadphaseProxy *proxy)
Public Attributes
btVector3 m_rayFromWorld
btVector3 m_rayToWorld
btTransform m_rayFromTrans
btTransform m_rayToTrans
btVector3 m_hitNormal
const btSoftRigidDynamicsWorld * m_world
btCollisionWorld::RayResultCallback & m_resultCallback
Detailed Description
Definition at line 187 of file btSoftRigidDynamicsWorld.cpp.
Constructor & Destructor Documentation
btSoftSingleRayCallback::btSoftSingleRayCallback (const btVector3 & rayFromWorld, const btVector3 & rayToWorld, const btSoftRigidDynamicsWorld * world, btCollisionWorld::RayResultCallback & resultCallback) [inline]
what about division by zero? --> just set rayDirection[i] to INF/1e30
Definition at line 198 of file btSoftRigidDynamicsWorld.cpp.
References btBroadphaseRayCallback::m_lambda_max, btBroadphaseRayCallback::m_rayDirectionInverse, m_rayFromTrans, m_rayFromWorld, m_rayToTrans, m_rayToWorld, btBroadphaseRayCallback::m_signs, btTransform::setIdentity(), and btTransform::setOrigin().
Member Function Documentation
virtual bool btSoftSingleRayCallback::process (const btBroadphaseProxy * proxy) [inline, virtual]
terminate further ray tests, once the closestHitFraction reached zero
Implements btBroadphaseAabbCallback.
Definition at line 226 of file btSoftRigidDynamicsWorld.cpp.
References btCollisionWorld::RayResultCallback::m_closestHitFraction, m_rayFromTrans, m_rayToTrans, m_resultCallback, m_world, btCollisionWorld::RayResultCallback::needsCollision(), and btSoftRigidDynamicsWorld::rayTestSingle().
Referenced by btSoftRigidDynamicsWorld::rayTest().
Member Data Documentation
btVector3 btSoftSingleRayCallback::m_hitNormal
Definition at line 193 of file btSoftRigidDynamicsWorld.cpp.
btTransform btSoftSingleRayCallback::m_rayFromTrans
Definition at line 191 of file btSoftRigidDynamicsWorld.cpp.
Referenced by btSoftSingleRayCallback(), and process().
btVector3 btSoftSingleRayCallback::m_rayFromWorld
Definition at line 189 of file btSoftRigidDynamicsWorld.cpp.
Referenced by btSoftSingleRayCallback().
btTransform btSoftSingleRayCallback::m_rayToTrans
Definition at line 192 of file btSoftRigidDynamicsWorld.cpp.
Referenced by btSoftSingleRayCallback(), and process().
btVector3 btSoftSingleRayCallback::m_rayToWorld
Definition at line 190 of file btSoftRigidDynamicsWorld.cpp.
Referenced by btSoftSingleRayCallback().
btCollisionWorld::RayResultCallback& btSoftSingleRayCallback::m_resultCallback
Definition at line 196 of file btSoftRigidDynamicsWorld.cpp.
Referenced by process().
const btSoftRigidDynamicsWorld* btSoftSingleRayCallback::m_world
Definition at line 195 of file btSoftRigidDynamicsWorld.cpp.
Referenced by process().
The documentation for this struct was generated from the following file:
btSoftRigidDynamicsWorld.cpp