Blender: BKE_bmesh.h File Reference
BKE_bmesh.h File Reference
blenkernel
BMesh modeler structure and functions.
Classes
struct BME_TransData
struct BME_TransData_Head
struct BME_Glob
Defines
#define BME_BEVEL_ORIG 1
#define BME_BEVEL_BEVEL (1<<1)
#define BME_BEVEL_NONMAN (1<<2)
#define BME_BEVEL_WIRE (1<<3)
#define BME_BEVEL_SELECT 1
#define BME_BEVEL_VERT (1<<1)
#define BME_BEVEL_RADIUS (1<<2)
#define BME_BEVEL_ANGLE (1<<3)
#define BME_BEVEL_WEIGHT (1<<4)
#define BME_BEVEL_PERCENT (1<<6)
#define BME_BEVEL_EMIN (1<<7)
#define BME_BEVEL_EMAX (1<<8)
#define BME_BEVEL_RUNNING (1<<9)
#define BME_BEVEL_RES (1<<10)
#define BME_BEVEL_EVEN (1<<11)
#define BME_BEVEL_DIST (1<<12)
Typedefs
typedef struct BME_TransData BME_TransData
typedef struct BME_TransData_Head BME_TransData_Head
typedef struct BME_Glob BME_Glob
Functions
struct BME_TransData * BME_get_transdata (struct BME_TransData_Head *td, struct BMVert *v)
void BME_free_transdata (struct BME_TransData_Head *td)
struct BMesh * BME_bevel (struct BMEditMesh *em, float value, int res, int options, int defgrp_index, float angle, BME_TransData_Head **rtd, int do_tessface)
Detailed Description
BMesh modeler structure and functions.
Since:
January 2007
Definition in file BKE_bmesh.h.
Define Documentation
#define BME_BEVEL_ANGLE (1<<3)
Definition at line 54 of file BKE_bmesh.h.
Referenced by bevel_init_edges(), bevel_init_verts(), and rna_def_modifier_bevel().
#define BME_BEVEL_BEVEL (1<<1)
Definition at line 46 of file BKE_bmesh.h.
Referenced by bevel_init_edges(), bevel_init_verts(), BME_bevel_add_vweight(), BME_bevel_edge(), BME_bevel_mesh(), BME_bevel_poly(), and BME_bevel_split_edge().
#define BME_BEVEL_DIST (1<<12)
Definition at line 66 of file BKE_bmesh.h.
Referenced by rna_def_modifier_bevel().
#define BME_BEVEL_EMAX (1<<8)
Definition at line 60 of file BKE_bmesh.h.
Referenced by BME_bevel_add_vweight(), and rna_def_modifier_bevel().
#define BME_BEVEL_EMIN (1<<7)
Definition at line 59 of file BKE_bmesh.h.
Referenced by BME_bevel_add_vweight(), and rna_def_modifier_bevel().
#define BME_BEVEL_EVEN (1<<11)
Definition at line 64 of file BKE_bmesh.h.
Referenced by rna_def_modifier_bevel().
#define BME_BEVEL_NONMAN (1<<2)
Definition at line 47 of file BKE_bmesh.h.
Referenced by bevel_init_edges(), bevel_init_verts(), BME_bevel_add_vweight(), BME_bevel_edge(), and BME_bevel_initialize().
#define BME_BEVEL_ORIG 1
Definition at line 45 of file BKE_bmesh.h.
Referenced by BME_bevel_edge(), BME_bevel_initialize(), BME_bevel_is_split_vert(), BME_bevel_mesh(), BME_bevel_poly(), and BME_bevel_split_edge().
#define BME_BEVEL_PERCENT (1<<6)
Definition at line 58 of file BKE_bmesh.h.
#define BME_BEVEL_RADIUS (1<<2)
Definition at line 53 of file BKE_bmesh.h.
#define BME_BEVEL_RES (1<<10)
Definition at line 62 of file BKE_bmesh.h.
#define BME_BEVEL_RUNNING (1<<9)
Definition at line 61 of file BKE_bmesh.h.
#define BME_BEVEL_SELECT 1
Definition at line 51 of file BKE_bmesh.h.
Referenced by bevel_init_edges(), and bevel_init_verts().
#define BME_BEVEL_VERT (1<<1)
Definition at line 52 of file BKE_bmesh.h.
Referenced by Bevel(), BME_bevel_initialize(), handleEventBevel(), and rna_def_modifier_bevel().
#define BME_BEVEL_WEIGHT (1<<4)
Definition at line 55 of file BKE_bmesh.h.
Referenced by bevel_init_edges(), bevel_init_verts(), and rna_def_modifier_bevel().
#define BME_BEVEL_WIRE (1<<3)
Definition at line 48 of file BKE_bmesh.h.
Typedef Documentation
typedef struct BME_Glob BME_Glob
typedef struct BME_TransData BME_TransData
typedef struct BME_TransData_Head BME_TransData_Head
Function Documentation
struct BMesh* BME_bevel (struct BMEditMesh * em, float value, int res, int options, int defgrp_index, float angle, BME_TransData_Head ** rtd, int do_tessface) [read]
Definition at line 1095 of file BME_bevel.c.
References BLI_MEMARENA_STD_BUFSIZE, BMEditMesh::bm, BM_ITER_MESH, BM_VERTS_OF_MESH, BME_bevel_initialize(), BME_bevel_mesh(), BME_free_transdata(), BME_get_transdata(), BME_init_transdata(), BMEdit_RecalcTessellation(), bmesh_edit_begin(), bmesh_edit_end(), BMO_pop(), BMO_push(), BMVert::co, BME_TransData::factor, i, madd_v3_v3v3fl(), BME_TransData::max, NULL, BME_TransData::org, and BME_TransData::vec.
Referenced by applyModifier().
void BME_free_transdata (struct BME_TransData_Head * td)
Definition at line 82 of file BME_bevel.c.
References BLI_ghash_free(), BLI_memarena_free(), BME_TransData_Head::gh, BME_TransData_Head::ma, MEM_freeN(), and NULL.
Referenced by BME_bevel().
struct BME_TransData* BME_get_transdata (struct BME_TransData_Head * td, struct BMVert * v) [read]
Definition at line 136 of file BME_bevel.c.
References BLI_ghash_lookup(), and BME_TransData_Head::gh.
Referenced by BME_bevel(), BME_bevel_add_vweight(), BME_bevel_get_vec(), BME_bevel_poly(), and BME_bevel_split_edge().