Blender: Session Class Reference
Session Class Reference
#include <session.h>
Classes
struct DelayedReset
Public Member Functions
Session (const SessionParams &params)
~Session ()
void start ()
bool draw (BufferParams &params)
void wait ()
bool ready_to_reset ()
void reset (BufferParams &params, int samples)
void set_samples (int samples)
void set_pause (bool pause)
Public Attributes
Device * device
Scene * scene
RenderBuffers * buffers
DisplayBuffer * display
Progress progress
SessionParams params
int sample
Protected Member Functions
void run ()
void update_scene ()
void update_status_time (bool show_pause=false, bool show_done=false)
void tonemap ()
void path_trace (Tile &tile)
void reset_ (BufferParams &params, int samples)
void run_cpu ()
bool draw_cpu (BufferParams &params)
void reset_cpu (BufferParams &params, int samples)
void run_gpu ()
bool draw_gpu (BufferParams &params)
void reset_gpu (BufferParams &params, int samples)
Protected Attributes
struct Session::DelayedReset delayed_reset
TileManager tile_manager
bool device_use_gl
thread * session_thread
volatile bool display_outdated
volatile bool gpu_draw_ready
volatile bool gpu_need_tonemap
thread_condition_variable gpu_need_tonemap_cond
bool pause
thread_condition_variable pause_cond
thread_mutex pause_mutex
bool kernels_loaded
double start_time
double reset_time
double preview_time
double paused_time
Detailed Description
Definition at line 97 of file session.h.
Constructor & Destructor Documentation
CCL_NAMESPACE_BEGIN Session::Session (const SessionParams & params)
Definition at line 34 of file session.cpp.
References SessionParams::background, buffers, Device::create(), delayed_reset, SessionParams::device, device, DEVICE_CPU, device_use_gl, display, display_outdated, Session::DelayedReset::do_reset, gpu_draw_ready, gpu_need_tonemap, kernels_loaded, NULL, params, pause, paused_time, preview_time, reset_time, sample, Session::DelayedReset::samples, scene, session_thread, start_time, SessionParams::threads, and DeviceInfo::type.
Session::~Session ()
Definition at line 63 of file session.cpp.
References buffers, device, display, gpu_need_tonemap, gpu_need_tonemap_cond, SessionParams::output_path, params, pause, pause_cond, pause_mutex, progress, scene, session_thread, Progress::set_cancel(), Progress::set_status(), tonemap(), wait(), and DisplayBuffer::write().
Member Function Documentation
bool Session::draw (BufferParams & params)
Definition at line 452 of file session.cpp.
References device_use_gl, draw_cpu(), and draw_gpu().
Referenced by display(), and BlenderSession::draw().
bool Session::draw_cpu (BufferParams & params) [protected]
Definition at line 284 of file session.cpp.
References device, display, display_outdated, DisplayBuffer::draw(), DisplayBuffer::draw_ready(), BufferParams::modified(), DisplayBuffer::mutex, params, DisplayBuffer::params, reset_time, SessionParams::text_timeout, and time_dt().
Referenced by draw().
bool Session::draw_gpu (BufferParams & params) [protected]
Definition at line 129 of file session.cpp.
References buffers, device, display, display_outdated, DisplayBuffer::draw(), gpu_draw_ready, gpu_need_tonemap, gpu_need_tonemap_cond, BufferParams::modified(), RenderBuffers::mutex, DisplayBuffer::mutex, params, DisplayBuffer::params, reset_time, SessionParams::text_timeout, time_dt(), and tonemap().
Referenced by draw().
void Session::path_trace (Tile & tile) [protected]
Definition at line 585 of file session.cpp.
References TileManager::State::buffer, RenderBuffers::buffer, DeviceTask::buffer, buffers, device, device_memory::device_pointer, BufferParams::full_x, BufferParams::full_y, BufferParams::get_offset_stride(), DeviceTask::h, Tile::h, DeviceTask::offset, DeviceTask::PATH_TRACE, DeviceTask::resolution, TileManager::State::resolution, DeviceTask::rng_state, RenderBuffers::rng_state, DeviceTask::sample, TileManager::State::sample, TileManager::state, DeviceTask::stride, Device::task_add(), tile_manager, DeviceTask::w, Tile::w, DeviceTask::x, Tile::x, DeviceTask::y, and Tile::y.
Referenced by run_cpu(), and run_gpu().
bool Session::ready_to_reset ()
Definition at line 98 of file session.cpp.
References SessionParams::cancel_timeout, display_outdated, params, reset_time, SessionParams::reset_timeout, and time_dt().
Referenced by BlenderSession::draw(), and BlenderSession::synchronize().
void Session::reset (BufferParams & params, int samples)
Definition at line 479 of file session.cpp.
References device_use_gl, reset_cpu(), and reset_gpu().
Referenced by BlenderSession::create_session(), BlenderSession::draw(), keyboard(), BlenderSession::render(), resize(), session_init(), and BlenderSession::synchronize().
void Session::reset_ (BufferParams & params, int samples) [protected]
Definition at line 460 of file session.cpp.
References SessionParams::background, buffers, device, display, gpu_draw_ready, BufferParams::modified(), params, RenderBuffers::params, paused_time, preview_time, progress, TileManager::reset(), DisplayBuffer::reset(), RenderBuffers::reset(), sample, Progress::set_start_time(), start_time, tile_manager, and time_dt().
Referenced by reset_gpu(), and run_cpu().
void Session::reset_cpu (BufferParams & params, int samples) [protected]
Definition at line 269 of file session.cpp.
References delayed_reset, device, display_outdated, Session::DelayedReset::do_reset, Session::DelayedReset::mutex, Session::DelayedReset::params, pause_cond, reset_time, Session::DelayedReset::samples, Device::task_cancel(), and time_dt().
Referenced by reset().
void Session::reset_gpu (BufferParams & params, int samples) [protected]
Definition at line 110 of file session.cpp.
References buffers, display, display_outdated, gpu_need_tonemap, gpu_need_tonemap_cond, RenderBuffers::mutex, DisplayBuffer::mutex, pause_cond, reset_(), reset_time, and time_dt().
Referenced by reset().
void Session::run () [protected]
Definition at line 415 of file session.cpp.
References device, device_use_gl, Device::error_message(), SessionParams::experimental, Progress::get_cancel(), Progress::get_cancel_message(), kernels_loaded, Device::load_kernels(), params, progress, run_cpu(), run_gpu(), Progress::set_status(), and Progress::set_update().
Referenced by start().
void Session::run_cpu () [protected]
Definition at line 305 of file session.cpp.
References SessionParams::background, buffers, delayed_reset, device, display, Session::DelayedReset::do_reset, Device::error_message(), Progress::get_cancel(), RenderBuffers::mutex, DisplayBuffer::mutex, Session::DelayedReset::mutex, TileManager::next(), params, Session::DelayedReset::params, path_trace(), pause, pause_cond, pause_mutex, paused_time, progress, reset_(), Session::DelayedReset::samples, Progress::set_cancel(), Progress::set_start_time(), Progress::set_status(), Progress::set_update(), start_time, TileManager::state, Device::task_wait(), tile_manager, TileManager::State::tiles, time_dt(), tonemap(), update_scene(), and update_status_time().
Referenced by run().
void Session::run_gpu () [protected]
Definition at line 160 of file session.cpp.
References SessionParams::background, buffers, device, Device::error_message(), Progress::get_cancel(), gpu_draw_ready, gpu_need_tonemap, gpu_need_tonemap_cond, RenderBuffers::mutex, TileManager::next(), params, path_trace(), pause, pause_cond, pause_mutex, paused_time, progress, reset_time, Progress::set_cancel(), Progress::set_start_time(), Progress::set_status(), Progress::set_update(), start_time, TileManager::state, Device::task_wait(), tile_manager, TileManager::State::tiles, time_dt(), update_scene(), and update_status_time().
Referenced by run().
void Session::set_pause (bool pause)
Definition at line 500 of file session.cpp.
References pause, pause_cond, and pause_mutex.
Referenced by BlenderSession::create_session(), and BlenderSession::synchronize().
void Session::set_samples (int samples)
Definition at line 487 of file session.cpp.
References params, pause_cond, pause_mutex, SessionParams::samples, TileManager::set_samples(), and tile_manager.
Referenced by BlenderSession::synchronize().
void Session::start ()
Definition at line 93 of file session.cpp.
References function_bind, run(), and session_thread.
Referenced by BlenderSession::BlenderSession(), BlenderSession::render(), session_init(), and BlenderSession::synchronize().
void Session::tonemap () [protected]
Definition at line 603 of file session.cpp.
References TileManager::State::buffer, RenderBuffers::buffer, DeviceTask::buffer, buffers, device, device_memory::device_pointer, display, display_outdated, DisplayBuffer::draw_set(), BufferParams::full_x, BufferParams::full_y, BufferParams::get_offset_stride(), DeviceTask::h, BufferParams::height, DeviceTask::offset, DeviceTask::resolution, TileManager::State::resolution, DisplayBuffer::rgba, DeviceTask::rgba, DeviceTask::sample, TileManager::State::sample, TileManager::state, DeviceTask::stride, Device::task_add(), Device::task_wait(), tile_manager, DeviceTask::TONEMAP, DeviceTask::w, BufferParams::width, DeviceTask::x, and DeviceTask::y.
Referenced by draw_gpu(), run_cpu(), and ~Session().
void Session::update_scene () [protected]
Definition at line 525 of file session.cpp.
References TileManager::State::buffer, Scene::camera, device, Scene::device_update(), BufferParams::full_height, BufferParams::full_width, Camera::height, Scene::mutex, Scene::need_update(), progress, scene, Progress::set_status(), TileManager::state, Camera::tag_update(), tile_manager, and Camera::width.
Referenced by run_cpu(), and run_gpu().
void Session::update_status_time (bool show_pause = false, bool show_done = false) [protected]
Definition at line 549 of file session.cpp.
References params, paused_time, preview_time, progress, SessionParams::progressive, TileManager::State::resolution, sample, TileManager::State::sample, SessionParams::samples, Progress::set_sample(), Progress::set_status(), TileManager::state, string_printf(), tile_manager, and time_dt().
Referenced by run_cpu(), and run_gpu().
void Session::wait ()
Definition at line 517 of file session.cpp.
References thread::join(), NULL, and session_thread.
Referenced by main(), BlenderSession::render(), and ~Session().
Member Data Documentation
RenderBuffers* Session::buffers
Definition at line 101 of file session.h.
Referenced by draw_gpu(), path_trace(), reset_(), reset_gpu(), run_cpu(), run_gpu(), Session(), tonemap(), BlenderSession::write_render_result(), and ~Session().
struct Session::DelayedReset Session::delayed_reset [protected]
Referenced by reset_cpu(), run_cpu(), and Session().
Device* Session::device
Definition at line 99 of file session.h.
Referenced by draw_cpu(), draw_gpu(), path_trace(), reset_(), reset_cpu(), run(), run_cpu(), run_gpu(), Session(), tonemap(), update_scene(), and ~Session().
bool Session::device_use_gl [protected]
Definition at line 145 of file session.h.
Referenced by draw(), reset(), run(), and Session().
DisplayBuffer* Session::display
Definition at line 102 of file session.h.
Referenced by draw_cpu(), draw_gpu(), reset_(), reset_gpu(), run_cpu(), Session(), tonemap(), and ~Session().
volatile bool Session::display_outdated [protected]
Definition at line 149 of file session.h.
Referenced by draw_cpu(), draw_gpu(), ready_to_reset(), reset_cpu(), reset_gpu(), Session(), and tonemap().
volatile bool Session::gpu_draw_ready [protected]
Definition at line 151 of file session.h.
Referenced by draw_gpu(), reset_(), run_gpu(), and Session().
volatile bool Session::gpu_need_tonemap [protected]
Definition at line 152 of file session.h.
Referenced by draw_gpu(), reset_gpu(), run_gpu(), Session(), and ~Session().
thread_condition_variable Session::gpu_need_tonemap_cond [protected]
Definition at line 153 of file session.h.
Referenced by draw_gpu(), reset_gpu(), run_gpu(), and ~Session().
bool Session::kernels_loaded [protected]
Definition at line 159 of file session.h.
Referenced by run(), and Session().
SessionParams Session::params
Definition at line 104 of file session.h.
Referenced by draw_cpu(), draw_gpu(), BlenderSession::get_progress(), ready_to_reset(), reset_(), run(), run_cpu(), run_gpu(), Session(), set_samples(), BlenderSession::synchronize(), update_status_time(), and ~Session().
bool Session::pause [protected]
Definition at line 155 of file session.h.
Referenced by run_cpu(), run_gpu(), Session(), set_pause(), and ~Session().
thread_condition_variable Session::pause_cond [protected]
Definition at line 156 of file session.h.
Referenced by reset_cpu(), reset_gpu(), run_cpu(), run_gpu(), set_pause(), set_samples(), and ~Session().
thread_mutex Session::pause_mutex [protected]
Definition at line 157 of file session.h.
Referenced by run_cpu(), run_gpu(), set_pause(), set_samples(), and ~Session().
double Session::paused_time [protected]
Definition at line 164 of file session.h.
Referenced by reset_(), run_cpu(), run_gpu(), Session(), and update_status_time().
double Session::preview_time [protected]
Definition at line 163 of file session.h.
Referenced by reset_(), Session(), and update_status_time().
Progress Session::progress
Definition at line 103 of file session.h.
Referenced by BlenderSession::create_session(), display(), BlenderSession::get_progress(), BlenderSession::get_status(), keyboard(), BlenderSession::render(), reset_(), run(), run_cpu(), run_gpu(), session_init(), session_print_status(), BlenderSession::test_cancel(), update_scene(), update_status_time(), BlenderSession::write_render_result(), and ~Session().
double Session::reset_time [protected]
Definition at line 162 of file session.h.
Referenced by draw_cpu(), draw_gpu(), ready_to_reset(), reset_cpu(), reset_gpu(), run_gpu(), and Session().
int Session::sample
Definition at line 105 of file session.h.
Referenced by reset_(), Session(), and update_status_time().
Scene* Session::scene
Definition at line 100 of file session.h.
Referenced by BlenderSession::create_session(), BlenderSession::draw(), Session(), session_init(), BlenderSession::synchronize(), update_scene(), and ~Session().
thread* Session::session_thread [protected]
Definition at line 147 of file session.h.
Referenced by Session(), start(), wait(), and ~Session().
double Session::start_time [protected]
Definition at line 161 of file session.h.
Referenced by reset_(), run_cpu(), run_gpu(), and Session().
TileManager Session::tile_manager [protected]
Definition at line 144 of file session.h.
Referenced by path_trace(), reset_(), run_cpu(), run_gpu(), set_samples(), tonemap(), update_scene(), and update_status_time().
The documentation for this class was generated from the following files:
session.h
session.cpp