Blender: attributes.cpp File Reference
attributes.cpp File Reference
elbeem
#include "attributes.h"
#include "ntl_matrices.h"
#include "elbeem.h"
Functions
ntlVec3f channelFindMaxVf (AnimChannel< ntlVec3f > channel)
ntlVec3d channelFindMaxVd (AnimChannel< ntlVec3d > channel)
int channelFindMaxi (AnimChannel< float > channel)
float channelFindMaxf (AnimChannel< float > channel)
double channelFindMaxd (AnimChannel< double > channel)
template<class SCALAR >
static bool channelSimplifyScalarT (AnimChannel< SCALAR > &channel)
bool channelSimplifyi (AnimChannel< int > &channel)
bool channelSimplifyf (AnimChannel< float > &channel)
bool channelSimplifyd (AnimChannel< double > &channel)
template<class VEC >
static bool channelSimplifyVecT (AnimChannel< VEC > &channel)
bool channelSimplifyVf (AnimChannel< ntlVec3f > &channel)
bool channelSimplifyVd (AnimChannel< ntlVec3d > &channel)
void __forceAnimChannelInstantiation ()
std::ostream & operator<< (std::ostream &os, const ntlSetVec3f &vs)
Detailed Description
Definition in file attributes.cpp.
Function Documentation
void __forceAnimChannelInstantiation ()
Definition at line 294 of file attributes.cpp.
References AnimChannel< Scalar >::debugPrintChannel().
double channelFindMaxd (AnimChannel< double > channel)
Definition at line 206 of file attributes.cpp.
References ABS, AnimChannel< Scalar >::accessValues(), and i.
float channelFindMaxf (AnimChannel< float > channel)
Definition at line 197 of file attributes.cpp.
References ABS, AnimChannel< Scalar >::accessValues(), and i.
int channelFindMaxi (AnimChannel< float > channel)
Definition at line 188 of file attributes.cpp.
References ABS, AnimChannel< Scalar >::accessValues(), and i.
ntlVec3d channelFindMaxVd (AnimChannel< ntlVec3d > channel)
Definition at line 179 of file attributes.cpp.
References AnimChannel< Scalar >::accessValues(), i, and normNoSqrt().
ntlVec3f channelFindMaxVf (AnimChannel< ntlVec3f > channel)
Definition at line 170 of file attributes.cpp.
References AnimChannel< Scalar >::accessValues(), i, and normNoSqrt().
Referenced by ntlGeometryObject::initMovingPoints(), and ntlGeometryObject::initMovingPointsAnim().
bool channelSimplifyd (AnimChannel< double > & channel)
Definition at line 246 of file attributes.cpp.
bool channelSimplifyf (AnimChannel< float > & channel)
Definition at line 245 of file attributes.cpp.
bool channelSimplifyi (AnimChannel< int > & channel)
Definition at line 244 of file attributes.cpp.
template<class SCALAR > static bool channelSimplifyScalarT (AnimChannel< SCALAR > & channel) [static]
Definition at line 222 of file attributes.cpp.
References AnimChannel< Scalar >::accessTimes(), AnimChannel< Scalar >::accessValues(), elbeemSimplifyChannelFloat(), AnimChannel< Scalar >::getSize(), i, and size().
bool channelSimplifyVd (AnimChannel< ntlVec3d > & channel)
Definition at line 275 of file attributes.cpp.
template<class VEC > static bool channelSimplifyVecT (AnimChannel< VEC > & channel) [static]
Definition at line 248 of file attributes.cpp.
References AnimChannel< Scalar >::accessTimes(), AnimChannel< Scalar >::accessValues(), elbeemSimplifyChannelVec3(), AnimChannel< Scalar >::getSize(), i, and size().
bool channelSimplifyVf (AnimChannel< ntlVec3f > & channel)
Definition at line 272 of file attributes.cpp.
std::ostream& operator<< (std::ostream & os, const ntlSetVec3f & vs)
Definition at line 319 of file attributes.cpp.
References ntlSetVec3f::mVerts.