Blender: MOD_curve.c File Reference
MOD_curve.c File Reference
modifiers
#include <string.h>
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "BLI_utildefines.h"
#include "BLI_string.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_lattice.h"
#include "BKE_modifier.h"
#include "depsgraph_private.h"
#include "MOD_util.h"
Functions
static void initData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static CustomDataMask requiredDataMask (Object *UNUSED(ob), ModifierData *md)
static int isDisabled (ModifierData *md, int UNUSED(userRenderParams))
static void foreachObjectLink (ModifierData *md, Object *ob, void(*walk)(void *userData, Object *ob, Object **obpoin), void *userData)
static void updateDepgraph (ModifierData *md, DagForest *forest, Scene *UNUSED(scene), Object *UNUSED(ob), DagNode *obNode)
static void deformVerts (ModifierData *md, Object *ob, DerivedMesh *derivedData, float(*vertexCos)[3], int numVerts, int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
static void deformVertsEM (ModifierData *md, Object *ob, struct BMEditMesh *editData, DerivedMesh *derivedData, float(*vertexCos)[3], int numVerts)
Variables
ModifierTypeInfo modifierType_Curve
Detailed Description
Definition in file MOD_curve.c.
Function Documentation
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 60 of file MOD_curve.c.
References BLI_strncpy(), CurveModifierData::defaxis, CurveModifierData::name, and CurveModifierData::object.
static void deformVerts (ModifierData * md, Object * ob, DerivedMesh * derivedData, float(*) vertexCos[3], int numVerts, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 113 of file MOD_curve.c.
References curve_deform_verts(), CurveModifierData::defaxis, CurveModifierData::name, CurveModifierData::object, and ModifierData::scene.
Referenced by deformVertsEM().
static void deformVertsEM (ModifierData * md, Object * ob, struct BMEditMesh * editData, DerivedMesh * derivedData, float(*) vertexCos[3], int numVerts) [static]
Definition at line 128 of file MOD_curve.c.
References CDDM_from_BMEditMesh(), Object::data, deformVerts(), FALSE, and DerivedMesh::release.
static void foreachObjectLink (ModifierData * md, Object * ob, void(*)(void *userData, Object *ob, Object **obpoin) walk, void * userData) [static]
Definition at line 88 of file MOD_curve.c.
References CurveModifierData::object.
static void initData (ModifierData * md) [static]
Definition at line 53 of file MOD_curve.c.
References CurveModifierData::defaxis, and MOD_CURVE_POSX.
static int isDisabled (ModifierData * md, int UNUSEDuserRenderParams) [static]
Definition at line 81 of file MOD_curve.c.
References CurveModifierData::object.
static CustomDataMask requiredDataMask (Object * UNUSEDob, ModifierData * md) [static]
Definition at line 70 of file MOD_curve.c.
References CD_MASK_MDEFORMVERT, and CurveModifierData::name.
static void updateDepgraph (ModifierData * md, DagForest * forest, Scene * UNUSEDscene, Object * UNUSEDob, DagNode * obNode) [static]
Definition at line 98 of file MOD_curve.c.
References dag_add_relation(), dag_get_node(), DAG_RL_DATA_DATA, DAG_RL_OB_DATA, and CurveModifierData::object.
Variable Documentation
ModifierTypeInfo modifierType_Curve
Initial value:
 {
                  "Curve",
            "CurveModifierData",
            sizeof(CurveModifierData),
                  eModifierTypeType_OnlyDeform,
                 eModifierTypeFlag_AcceptsCVs
                            | eModifierTypeFlag_SupportsEditmode,
              copyData,
           deformVerts,
        NULL,
         deformVertsEM,
      NULL,
         NULL,
       NULL,
              initData,
      requiredDataMask,
              NULL,
            isDisabled,
        updateDepgraph,
         NULL,
        NULL,
     foreachObjectLink,
         NULL,
        NULL,
}
Definition at line 142 of file MOD_curve.c.