Blender: ssp_defs.h File Reference
ssp_defs.h File Reference
opennl
#include "Cnames.h"
#include "supermatrix.h"
#include "util.h"
Classes
struct GlobalLU_t
struct mem_usage_t
Typedefs
typedef int int_t
Functions
void sgssv (superlu_options_t *, SuperMatrix *, int *, int *, SuperMatrix *, SuperMatrix *, SuperMatrix *, SuperLUStat_t *, int *)
void sgssvx (superlu_options_t *, SuperMatrix *, int *, int *, int *, char *, float *, float *, SuperMatrix *, SuperMatrix *, void *, int, SuperMatrix *, SuperMatrix *, float *, float *, float *, float *, mem_usage_t *, SuperLUStat_t *, int *)
void sCreate_CompCol_Matrix (SuperMatrix *, int, int, int, float *, int *, int *, Stype_t, Dtype_t, Mtype_t)
void sCreate_CompRow_Matrix (SuperMatrix *, int, int, int, float *, int *, int *, Stype_t, Dtype_t, Mtype_t)
void sCopy_CompCol_Matrix (SuperMatrix *, SuperMatrix *)
void sCreate_Dense_Matrix (SuperMatrix *, int, int, float *, int, Stype_t, Dtype_t, Mtype_t)
void sCreate_SuperNode_Matrix (SuperMatrix *, int, int, int, float *, int *, int *, int *, int *, int *, Stype_t, Dtype_t, Mtype_t)
void sCopy_Dense_Matrix (int, int, float *, int, float *, int)
void countnz (const int, int *, int *, int *, GlobalLU_t *)
void fixupL (const int, const int *, GlobalLU_t *)
void sallocateA (int, int, float **, int **, int **)
void sgstrf (superlu_options_t *, SuperMatrix *, int, int, int *, void *, int, int *, int *, SuperMatrix *, SuperMatrix *, SuperLUStat_t *, int *)
int ssnode_dfs (const int, const int, const int *, const int *, const int *, int *, int *, GlobalLU_t *)
int ssnode_bmod (const int, const int, float *, float *, GlobalLU_t *, SuperLUStat_t *)
void spanel_dfs (const int, const int, const int, SuperMatrix *, int *, int *, float *, int *, int *, int *, int *, int *, int *, int *, GlobalLU_t *)
void spanel_bmod (const int, const int, const int, const int, float *, float *, int *, int *, GlobalLU_t *, SuperLUStat_t *)
int scolumn_dfs (const int, const int, int *, int *, int *, int *, int *, int *, int *, int *, int *, GlobalLU_t *)
int scolumn_bmod (const int, const int, float *, float *, int *, int *, int, GlobalLU_t *, SuperLUStat_t *)
int scopy_to_ucol (int, int, int *, int *, int *, float *, GlobalLU_t *)
int spivotL (const int, const float, int *, int *, int *, int *, int *, GlobalLU_t *, SuperLUStat_t *)
void spruneL (const int, const int *, const int, const int, const int *, const int *, int *, GlobalLU_t *)
void sreadmt (int *, int *, int *, float **, int **, int **)
void sGenXtrue (int, int, float *, int)
void sFillRHS (trans_t, int, float *, int, SuperMatrix *, SuperMatrix *)
void sgstrs (trans_t, SuperMatrix *, SuperMatrix *, int *, int *, SuperMatrix *, SuperLUStat_t *, int *)
void sgsequ (SuperMatrix *, float *, float *, float *, float *, float *, int *)
void slaqgs (SuperMatrix *, float *, float *, float, float, float, char *)
void sgscon (char *, SuperMatrix *, SuperMatrix *, float, float *, SuperLUStat_t *, int *)
float sPivotGrowth (int, SuperMatrix *, int *, SuperMatrix *, SuperMatrix *)
void sgsrfs (trans_t, SuperMatrix *, SuperMatrix *, SuperMatrix *, int *, int *, char *, float *, float *, SuperMatrix *, SuperMatrix *, float *, float *, SuperLUStat_t *, int *)
int sp_strsv (char *, char *, char *, SuperMatrix *, SuperMatrix *, float *, SuperLUStat_t *, int *)
int sp_sgemv (char *, float, SuperMatrix *, float *, int, float, float *, int)
int sp_sgemm (char *, int, float, SuperMatrix *, float *, int, float, float *, int)
int sLUMemInit (fact_t, void *, int, int, int, int, int, SuperMatrix *, SuperMatrix *, GlobalLU_t *, int **, float **)
void sSetRWork (int, int, float *, float **, float **)
void sLUWorkFree (int *, float *, GlobalLU_t *)
int sLUMemXpand (int, int, MemType, int *, GlobalLU_t *)
float * floatMalloc (int)
float * floatCalloc (int)
int smemory_usage (const int, const int, const int, const int)
int sQuerySpace (SuperMatrix *, SuperMatrix *, mem_usage_t *)
void sreadhb (int *, int *, int *, float **, int **, int **)
void sCompRow_to_CompCol (int, int, int, float *, int *, int *, float **, int **, int **)
void sfill (float *, int, float)
void sinf_norm_error (int, SuperMatrix *, float *)
void PrintPerf (SuperMatrix *, SuperMatrix *, mem_usage_t *, float, float, float *, float *, char *)
void sPrint_CompCol_Matrix (char *, SuperMatrix *)
void sPrint_SuperNode_Matrix (char *, SuperMatrix *)
void sPrint_Dense_Matrix (char *, SuperMatrix *)
void print_lu_col (char *, int, int, int *, GlobalLU_t *)
void check_tempv (int, float *)
int print_int_vec (char *what, int n, int *vec)
int sp_symetree (int *acolst, int *acolend, int *arow, int n, int *parent)
void sprint_lu_col (char *msg, int jcol, int pivrow, int *xprune, GlobalLU_t *Glu)
Detailed Description
Definition in file ssp_defs.h.
Typedef Documentation
typedef int int_t
Definition at line 27 of file ssp_defs.h.
Function Documentation
void check_tempv (int , float *)
void countnz (const int , int * , int * , int * , GlobalLU_t *)
Definition at line 136 of file intern/opennl/superlu/util.c.
References i, GlobalLU_t::supno, GlobalLU_t::xlsub, GlobalLU_t::xsup, and GlobalLU_t::xusub.
Referenced by sgstrf().
void fixupL (const int , const int * , GlobalLU_t *)
Definition at line 178 of file intern/opennl/superlu/util.c.
References i, GlobalLU_t::lsub, GlobalLU_t::supno, GlobalLU_t::xlsub, and GlobalLU_t::xsup.
Referenced by sgstrf().
float* floatCalloc (int)
Definition at line 656 of file smemory.c.
References ABORT, i, and SUPERLU_MALLOC.
Referenced by sgstrs(), and sp_strsv().
float* floatMalloc (int)
Definition at line 646 of file smemory.c.
References ABORT, and SUPERLU_MALLOC.
Referenced by sallocateA(), sCompRow_to_CompCol(), and sgstrs().
int print_int_vec (char * what, int n, int * vec)
Definition at line 394 of file intern/opennl/superlu/util.c.
References i.
Referenced by sp_preorder().
void print_lu_col (char * , int , int , int * , GlobalLU_t *)
void PrintPerf (SuperMatrix * , SuperMatrix * , mem_usage_t * , float , float , float * , float * , char *)
void sallocateA (int , int , float ** , int ** , int **)
Definition at line 638 of file smemory.c.
References floatMalloc(), and intMalloc().
int scolumn_bmod (const int , const int , float * , float * , int * , int * , int , GlobalLU_t * , SuperLUStat_t *)
Definition at line 42 of file scolumn_bmod.c.
References GEMV, i, GlobalLU_t::lsub, GlobalLU_t::lusup, LUSUP, GlobalLU_t::nzlumax, SuperLUStat_t::ops, slsolve(), sLUMemXpand(), smatvec(), strlen(), strsv_(), SUPERLU_MAX, GlobalLU_t::supno, TRSV, GlobalLU_t::xlsub, GlobalLU_t::xlusup, and GlobalLU_t::xsup.
Referenced by sgstrf().
int scolumn_dfs (const int , const int , int * , int * , int * , int * , int * , int * , int * , int * , int * , GlobalLU_t *)
Definition at line 32 of file scolumn_dfs.c.
References EMPTY, GlobalLU_t::lsub, LSUB, GlobalLU_t::nzlmax, sLUMemXpand(), sp_ienv(), GlobalLU_t::supno, GlobalLU_t::xlsub, and GlobalLU_t::xsup.
Referenced by sgstrf().
void sCompRow_to_CompCol (int , int , int , float * , int * , int * , float ** , int ** , int **)
Definition at line 168 of file sutil.c.
References floatMalloc(), i, intCalloc(), intMalloc(), and SUPERLU_FREE.
void sCopy_CompCol_Matrix (SuperMatrix * , SuperMatrix *)
Definition at line 80 of file sutil.c.
References NCformat::colptr, SuperMatrix::Dtype, i, SuperMatrix::Mtype, SuperMatrix::ncol, NCformat::nnz, SuperMatrix::nrow, NCformat::nzval, NCformat::rowind, SuperMatrix::Store, and SuperMatrix::Stype.
void sCopy_Dense_Matrix (int , int , float * , int , float * , int)
Definition at line 119 of file sutil.c.
References i, M, and N.
int scopy_to_ucol (int , int , int * , int * , int * , float * , GlobalLU_t *)
Definition at line 30 of file scopy_to_ucol.c.
References EMPTY, i, GlobalLU_t::lsub, GlobalLU_t::nzumax, sLUMemXpand(), GlobalLU_t::supno, UCOL, GlobalLU_t::ucol, USUB, GlobalLU_t::usub, GlobalLU_t::xlsub, GlobalLU_t::xsup, and GlobalLU_t::xusub.
Referenced by sgstrf().
void sCreate_CompCol_Matrix (SuperMatrix * , int , int , int , float * , int * , int * , Stype_t , Dtype_t , Mtype_t)
Definition at line 37 of file sutil.c.
References ABORT, NCformat::colptr, SuperMatrix::Dtype, SuperMatrix::Mtype, SuperMatrix::ncol, NCformat::nnz, SuperMatrix::nrow, NCformat::nzval, NCformat::rowind, SuperMatrix::Store, SuperMatrix::Stype, and SUPERLU_MALLOC.
Referenced by __nlFactorize_SUPERLU(), sgssv(), and sgstrf().
void sCreate_CompRow_Matrix (SuperMatrix * , int , int , int , float * , int * , int * , Stype_t , Dtype_t , Mtype_t)
Definition at line 58 of file sutil.c.
References ABORT, NRformat::colind, SuperMatrix::Dtype, SuperMatrix::Mtype, SuperMatrix::ncol, NRformat::nnz, SuperMatrix::nrow, NRformat::nzval, NRformat::rowptr, SuperMatrix::Store, SuperMatrix::Stype, and SUPERLU_MALLOC.
void sCreate_Dense_Matrix (SuperMatrix * , int , int , float * , int , Stype_t , Dtype_t , Mtype_t)
Definition at line 101 of file sutil.c.
References ABORT, SuperMatrix::Dtype, DNformat::lda, SuperMatrix::Mtype, SuperMatrix::ncol, SuperMatrix::nrow, DNformat::nzval, SuperMatrix::Store, SuperMatrix::Stype, and SUPERLU_MALLOC.
Referenced by __nlInvert_SUPERLU().
void sCreate_SuperNode_Matrix (SuperMatrix * , int , int , int , float * , int * , int * , int * , int * , int * , Stype_t , Dtype_t , Mtype_t)
Definition at line 137 of file sutil.c.
References ABORT, SCformat::col_to_sup, SuperMatrix::Dtype, SuperMatrix::Mtype, SuperMatrix::ncol, SCformat::nnz, SuperMatrix::nrow, SCformat::nsuper, SCformat::nzval, SCformat::nzval_colptr, SCformat::rowind, SCformat::rowind_colptr, SuperMatrix::Store, SuperMatrix::Stype, SCformat::sup_to_col, and SUPERLU_MALLOC.
Referenced by sgstrf().
void sfill (float * , int , float)
Definition at line 396 of file sutil.c.
References i.
Referenced by sSetRWork().
void sFillRHS (trans_t , int , float * , int , SuperMatrix * , SuperMatrix *)
Definition at line 370 of file sutil.c.
References DNformat::lda, NOTRANS, DNformat::nzval, sp_sgemm(), and SuperMatrix::Store.
void sGenXtrue (int , int , float * , int)
Definition at line 357 of file sutil.c.
References i.
void sgscon (char * , SuperMatrix * , SuperMatrix * , float , float * , SuperLUStat_t * , int *)
void sgsequ (SuperMatrix * , float * , float * , float * , float * , float * , int *)
void sgsrfs (trans_t , SuperMatrix * , SuperMatrix * , SuperMatrix * , int * , int * , char * , float * , float * , SuperMatrix * , SuperMatrix * , float * , float * , SuperLUStat_t * , int *)
void sgssv (superlu_options_t * , SuperMatrix * , int * , int * , SuperMatrix * , SuperMatrix * , SuperMatrix * , SuperLUStat_t * , int *)
Definition at line 16 of file sgssv.c.
References NRformat::colind, superlu_options_t::ColPerm, COLPERM, Destroy_CompCol_Permuted(), Destroy_SuperMatrix_Store(), DOFACT, SuperMatrix::Dtype, ETREE, FACT, superlu_options_t::Fact, get_perm_c(), i, intMalloc(), DNformat::lda, SuperMatrix::Mtype, MY_PERMC, SuperMatrix::ncol, NRformat::nnz, NOTRANS, SuperMatrix::nrow, NULL, NRformat::nzval, NRformat::rowptr, sCreate_CompCol_Matrix(), sgstrf(), sgstrs(), SLU_DN, SLU_GE, SLU_NC, SLU_NR, SLU_S, SOLVE, sp_ienv(), sp_preorder(), SuperMatrix::Store, SuperMatrix::Stype, SUPERLU_FREE, SUPERLU_MALLOC, SUPERLU_MAX, SuperLU_timer_(), TRANS, SuperLUStat_t::utime, and xerbla_().
void sgssvx (superlu_options_t * , SuperMatrix * , int * , int * , int * , char * , float * , float * , SuperMatrix * , SuperMatrix * , void * , int , SuperMatrix * , SuperMatrix * , float * , float * , float * , float * , mem_usage_t * , SuperLUStat_t * , int *)
void sgstrf (superlu_options_t * , SuperMatrix * , int , int , int * , void * , int , int * , int * , SuperMatrix * , SuperMatrix * , SuperLUStat_t * , int *)
Definition at line 28 of file sgstrf.c.
References NCPformat::colbeg, NCPformat::colend, countnz(), superlu_options_t::DiagPivotThresh, EMPTY, FACT, superlu_options_t::Fact, fixupL(), GEMV, heap_relax_snode(), i, ifill(), intMalloc(), GlobalLU_t::lsub, GlobalLU_t::lusup, LUSUP, SuperMatrix::ncol, NCPformat::nnz, NO_MARKER, SuperMatrix::nrow, NULL, GlobalLU_t::nzlumax, NCPformat::nzval, SuperLUStat_t::ops, SuperLUStat_t::panel_histo, relax_snode(), resetrep_col(), NCPformat::rowind, SamePattern_SameRowPerm, scolumn_bmod(), scolumn_dfs(), scopy_to_ucol(), sCreate_CompCol_Matrix(), sCreate_SuperNode_Matrix(), SetIWork(), SLU_NC, SLU_S, SLU_SC, SLU_TRLU, SLU_TRU, sLUMemInit(), sLUMemXpand(), sLUWorkFree(), spanel_bmod(), spanel_dfs(), spivotL(), sprint_lu_col(), spruneL(), sSetRWork(), ssnode_bmod(), ssnode_dfs(), SuperMatrix::Store, SUPERLU_FREE, SUPERLU_MIN, GlobalLU_t::supno, superlu_options_t::SymmetricMode, TRSV, GlobalLU_t::ucol, GlobalLU_t::usub, GlobalLU_t::xlsub, GlobalLU_t::xlusup, GlobalLU_t::xsup, GlobalLU_t::xusub, and YES.
Referenced by __nlFactorize_SUPERLU(), and sgssv().
void sgstrs (trans_t , SuperMatrix * , SuperMatrix * , int * , int * , SuperMatrix * , SuperLUStat_t * , int *)
Definition at line 37 of file sgstrs.c.
References ABORT, CONJ, SuperMatrix::Dtype, floatCalloc(), floatMalloc(), i, L_FST_SUPC, L_NZ_START, L_SUB, L_SUB_START, DNformat::lda, SuperMatrix::Mtype, SuperMatrix::ncol, NOTRANS, SuperMatrix::nrow, SCformat::nsuper, NCformat::nzval, SCformat::nzval, DNformat::nzval, SuperLUStat_t::ops, slsolve(), SLU_DN, SLU_GE, SLU_NC, SLU_S, SLU_SC, SLU_TRLU, SLU_TRU, smatvec(), SOLVE, sp_strsv(), sprint_soln(), SuperMatrix::Store, strlen(), SuperMatrix::Stype, SUPERLU_FREE, SUPERLU_MAX, susolve(), TRANS, U_NZ_START, U_SUB, and xerbla_().
Referenced by __nlInvert_SUPERLU(), and sgssv().
void sinf_norm_error (int , SuperMatrix * , float *)
Definition at line 407 of file sutil.c.
References err, fabs(), i, DNformat::lda, SuperMatrix::nrow, DNformat::nzval, SuperMatrix::Store, and SUPERLU_MAX.
void slaqgs (SuperMatrix * , float * , float * , float , float , float , char *)
int sLUMemInit (fact_t , void * , int , int , int , int , int , SuperMatrix * , SuperMatrix * , GlobalLU_t * , int ** , float **)
Definition at line 164 of file smemory.c.
References ABORT, SCformat::col_to_sup, NCformat::colptr, GluIntArray, HEAD, intMalloc(), GlobalLU_t::lsub, LSUB, GlobalLU_t::lusup, LUSUP, e_node::mem, GlobalLU_t::MemModel, GlobalLU_t::n, no_expand, NO_MEMTYPE, GlobalLU_t::nzlmax, GlobalLU_t::nzlumax, GlobalLU_t::nzumax, NCformat::nzval, SCformat::nzval, SCformat::nzval_colptr, NCformat::rowind, SCformat::rowind, SCformat::rowind_colptr, SamePattern_SameRowPerm, sexpand(), LU_stack_t::size, e_node::size, sLUWorkInit(), smemory_usage(), sp_ienv(), sSetupSpace(), SuperMatrix::Store, SCformat::sup_to_col, SUPERLU_FREE, SUPERLU_MALLOC, SUPERLU_MAX, GlobalLU_t::supno, suser_free(), suser_malloc(), SYSTEM, TempSpace, LU_stack_t::top2, UCOL, GlobalLU_t::ucol, USER, USUB, GlobalLU_t::usub, GlobalLU_t::xlsub, GlobalLU_t::xlusup, GlobalLU_t::xsup, and GlobalLU_t::xusub.
Referenced by sgstrf().
int sLUMemXpand (int , int , MemType , int * , GlobalLU_t *)
Definition at line 393 of file smemory.c.
References GlobalLU_t::lsub, LSUB, GlobalLU_t::lusup, LUSUP, GlobalLU_t::n, GlobalLU_t::nzlmax, GlobalLU_t::nzlumax, GlobalLU_t::nzumax, sexpand(), smemory_usage(), UCOL, GlobalLU_t::ucol, USUB, and GlobalLU_t::usub.
Referenced by scolumn_bmod(), scolumn_dfs(), scopy_to_ucol(), sgstrf(), and ssnode_dfs().
void sLUWorkFree (int * , float * , GlobalLU_t *)
Definition at line 373 of file smemory.c.
References GlobalLU_t::MemModel, LU_stack_t::size, SUPERLU_FREE, SYSTEM, LU_stack_t::top2, and LU_stack_t::used.
Referenced by sgstrf().
int smemory_usage (const int , const int , const int , const int)
Definition at line 670 of file smemory.c.
Referenced by sLUMemInit(), and sLUMemXpand().
int sp_sgemm (char * , int , float , SuperMatrix * , float * , int , float , float * , int)
Definition at line 22 of file ssp_blas3.c.
References sp_sgemv().
Referenced by sFillRHS().
int sp_sgemv (char * , float , SuperMatrix * , float * , int , float , float * , int)
Definition at line 309 of file ssp_blas2.c.
References ABORT, NCformat::colptr, i, lsame_(), SuperMatrix::ncol, SuperMatrix::nrow, NCformat::nzval, NCformat::rowind, SuperMatrix::Store, and xerbla_().
Referenced by sp_sgemm().
int sp_strsv (char * , char * , char * , SuperMatrix * , SuperMatrix * , float * , SuperLUStat_t * , int *)
Definition at line 28 of file ssp_blas2.c.
References ABORT, floatCalloc(), i, L_FST_SUPC, L_NZ_START, L_SUB, L_SUB_START, lsame_(), SuperMatrix::ncol, SuperMatrix::nrow, SCformat::nsuper, NCformat::nzval, SCformat::nzval, SuperLUStat_t::ops, slsolve(), smatvec(), SOLVE, SuperMatrix::Store, strlen(), strsv_(), SUPERLU_FREE, susolve(), U_NZ_START, U_SUB, and xerbla_().
Referenced by sgstrs().
int sp_symetree (int * acolst, int * acolend, int * arow, int n, int * parent)
Definition at line 300 of file sp_coletree.c.
References finalize_disjoint_sets(), find(), initialize_disjoint_sets(), link(), make_set(), mxCallocInt(), p, and SUPERLU_FREE.
Referenced by sp_preorder().
void spanel_bmod (const int , const int , const int , const int , float * , float * , int * , int * , GlobalLU_t * , SuperLUStat_t *)
Definition at line 37 of file spanel_bmod.c.
References EMPTY, GEMV, i, GlobalLU_t::lsub, GlobalLU_t::lusup, SuperLUStat_t::ops, slsolve(), smatvec(), sp_ienv(), strlen(), strsv_(), SUPERLU_MIN, GlobalLU_t::supno, TRSV, GlobalLU_t::xlsub, GlobalLU_t::xlusup, and GlobalLU_t::xsup.
Referenced by sgstrf().
void spanel_dfs (const int , const int , const int , SuperMatrix * , int * , int * , float * , int * , int * , int * , int * , int * , int * , int * , GlobalLU_t *)
Definition at line 30 of file spanel_dfs.c.
References NCPformat::colbeg, NCPformat::colend, EMPTY, i, GlobalLU_t::lsub, NCPformat::nzval, NCPformat::rowind, SuperMatrix::Store, GlobalLU_t::supno, GlobalLU_t::xlsub, and GlobalLU_t::xsup.
Referenced by sgstrf().
float sPivotGrowth (int , SuperMatrix * , int * , SuperMatrix * , SuperMatrix *)
int spivotL (const int , const float , int * , int * , int * , int * , int * , GlobalLU_t * , SuperLUStat_t *)
Definition at line 32 of file spivotL.c.
References EMPTY, fabs(), FACT, GlobalLU_t::lsub, GlobalLU_t::lusup, SuperLUStat_t::ops, GlobalLU_t::supno, thresh, GlobalLU_t::xlsub, GlobalLU_t::xlusup, and GlobalLU_t::xsup.
Referenced by sgstrf().
void sPrint_CompCol_Matrix (char * , SuperMatrix *)
Definition at line 206 of file sutil.c.
References NCformat::colptr, SuperMatrix::Dtype, i, SuperMatrix::Mtype, SuperMatrix::ncol, NCformat::nnz, SuperMatrix::nrow, NCformat::nzval, NCformat::rowind, SuperMatrix::Store, and SuperMatrix::Stype.
void sPrint_Dense_Matrix (char * , SuperMatrix *)
Definition at line 278 of file sutil.c.
References SuperMatrix::Dtype, i, DNformat::lda, SuperMatrix::Mtype, SuperMatrix::ncol, SuperMatrix::nrow, DNformat::nzval, SuperMatrix::Store, and SuperMatrix::Stype.
void sprint_lu_col (char * msg, int jcol, int pivrow, int * xprune, GlobalLU_t * Glu)
Definition at line 299 of file sutil.c.
References i, GlobalLU_t::lsub, GlobalLU_t::lusup, GlobalLU_t::supno, GlobalLU_t::ucol, GlobalLU_t::usub, GlobalLU_t::xlsub, GlobalLU_t::xlusup, GlobalLU_t::xsup, and GlobalLU_t::xusub.
Referenced by sgstrf().
void sPrint_SuperNode_Matrix (char * , SuperMatrix *)
Definition at line 229 of file sutil.c.
References SCformat::col_to_sup, SuperMatrix::Dtype, i, SuperMatrix::Mtype, SuperMatrix::ncol, SCformat::nnz, SuperMatrix::nrow, SCformat::nsuper, SCformat::nzval, SCformat::nzval_colptr, SCformat::rowind, SCformat::rowind_colptr, SuperMatrix::Store, SuperMatrix::Stype, and SCformat::sup_to_col.
void spruneL (const int , const int * , const int , const int , const int * , const int * , int * , GlobalLU_t *)
Definition at line 30 of file spruneL.c.
References EMPTY, FALSE, i, GlobalLU_t::lsub, GlobalLU_t::lusup, GlobalLU_t::supno, TRUE, GlobalLU_t::xlsub, GlobalLU_t::xlusup, and GlobalLU_t::xsup.
Referenced by sgstrf().
int sQuerySpace (SuperMatrix * , SuperMatrix * , mem_usage_t *)
Definition at line 127 of file smemory.c.
References NCformat::colptr, mem_usage_t::expansions, mem_usage_t::for_lu, SuperMatrix::ncol, no_expand, NO_MARKER, SCformat::nzval_colptr, SCformat::rowind_colptr, sp_ienv(), SuperMatrix::Store, and mem_usage_t::total_needed.
void sreadhb (int * , int * , int * , float ** , int ** , int **)
void sreadmt (int * , int * , int * , float ** , int ** , int **)
void sSetRWork (int , int , float * , float ** , float **)
Definition at line 357 of file smemory.c.
References NUM_TEMPV, sfill(), and sp_ienv().
Referenced by sgstrf().
int ssnode_bmod (const int , const int , float * , float * , GlobalLU_t * , SuperLUStat_t *)
Definition at line 34 of file ssnode_bmod.c.
References GEMV, i, GlobalLU_t::lsub, GlobalLU_t::lusup, SuperLUStat_t::ops, slsolve(), smatvec(), strlen(), strsv_(), TRSV, GlobalLU_t::xlsub, and GlobalLU_t::xlusup.
Referenced by sgstrf().
int ssnode_dfs (const int , const int , const int * , const int * , const int * , int * , int * , GlobalLU_t *)
Definition at line 30 of file ssnode_dfs.c.
References i, GlobalLU_t::lsub, LSUB, GlobalLU_t::nzlmax, sLUMemXpand(), GlobalLU_t::supno, GlobalLU_t::xlsub, and GlobalLU_t::xsup.
Referenced by sgstrf().