Blender: GHOST_DisplayManagerSDL.cpp File Reference
GHOST_DisplayManagerSDL.cpp File Reference
GHOST API
#include "GHOST_SystemSDL.h"
#include "GHOST_DisplayManagerSDL.h"
#include "GHOST_WindowManager.h"
Functions
static void ghost_mode_from_sdl (GHOST_DisplaySetting &setting, SDL_DisplayMode *mode)
static void ghost_mode_to_sdl (const GHOST_DisplaySetting &setting, SDL_DisplayMode *mode)
Detailed Description
Definition in file GHOST_DisplayManagerSDL.cpp.
Function Documentation
static void ghost_mode_from_sdl (GHOST_DisplaySetting & setting, SDL_DisplayMode * mode) [static]
Definition at line 63 of file GHOST_DisplayManagerSDL.cpp.
References GHOST_DisplaySetting::bpp, GHOST_DisplaySetting::frequency, GHOST_DisplaySetting::xPixels, and GHOST_DisplaySetting::yPixels.
Referenced by GHOST_DisplayManagerSDL::getCurrentDisplaySetting(), and GHOST_DisplayManagerSDL::getDisplaySetting().
static void ghost_mode_to_sdl (const GHOST_DisplaySetting & setting, SDL_DisplayMode * mode) [static]
Definition at line 72 of file GHOST_DisplayManagerSDL.cpp.
References GHOST_DisplaySetting::frequency, GHOST_DisplaySetting::xPixels, and GHOST_DisplaySetting::yPixels.
Referenced by GHOST_DisplayManagerSDL::setCurrentDisplaySetting().