Blender: FilterYV12 Class Reference
FilterYV12 Class Reference
class for YV12 conversion
#include <FilterSource.h>
Public Member Functions
FilterYV12 (void)
constructor
virtual ~FilterYV12 (void)
destructor
virtual unsigned int getPixelSize (void)
get source pixel size
void setBuffs (unsigned char *buff, short *size)
set pointers to color buffers
Protected Member Functions
int interpol (int a, int b, int c, int d)
interpolation function
int interpolH (unsigned char *src)
common horizontal interpolation
int interpolV (unsigned char *src)
common vertical interpolation
int interpolVH (unsigned char *src)
common joined vertical and horizontal interpolation
bool isEdge (short x, short y, short *size)
is pixel on edge
unsigned char * interParA (unsigned char *src, short x, short size, short shift)
get the first parameter on the low edge
unsigned char * interParC (unsigned char *src, short x, short size, short shift)
get the third parameter on the high edge
unsigned char * interParD (unsigned char *src, short x, short size, short shift)
get the fourth parameter on the high edge
int interpolEH (unsigned char *src, short x, short size)
horizontal interpolation on edges
int interpolEV (unsigned char *src, short y, short size)
vertical interpolation on edges
int interpolEVH (unsigned char *src, short x, short y, short *size)
joined vertical and horizontal interpolation on edges
virtual unsigned int filter (unsigned char *src, short x, short y, short *size, unsigned int pixSize, unsigned int val)
filter pixel, source byte buffer
Protected Attributes
unsigned char * m_buffV
begin of V buffer
unsigned char * m_buffU
begin of U buffer
short m_pitchUV
pitch for V & U buffers
Detailed Description
class for YV12 conversion
Definition at line 101 of file FilterSource.h.
Constructor & Destructor Documentation
FilterYV12::FilterYV12 (void) [inline]
constructor
Definition at line 105 of file FilterSource.h.
virtual FilterYV12::~FilterYV12 (void) [inline, virtual]
destructor
Definition at line 107 of file FilterSource.h.
Member Function Documentation
virtual unsigned int FilterYV12::filter (unsigned char * src, short x, short y, short * size, unsigned int pixSize, unsigned int val) [inline, protected, virtual]
filter pixel, source byte buffer
Reimplemented from FilterBase.
Definition at line 186 of file FilterSource.h.
References interpolEH(), interpolEV(), interpolEVH(), interpolH(), interpolV(), interpolVH(), isEdge(), m_buffU, m_buffV, m_pitchUV, and VT_RGBA.
virtual unsigned int FilterYV12::getPixelSize (void) [inline, virtual]
get source pixel size
Reimplemented from FilterBase.
Definition at line 110 of file FilterSource.h.
unsigned char* FilterYV12::interParA (unsigned char * src, short x, short size, short shift) [inline, protected]
get the first parameter on the low edge
Definition at line 153 of file FilterSource.h.
Referenced by interpolEH(), interpolEV(), and interpolEVH().
unsigned char* FilterYV12::interParC (unsigned char * src, short x, short size, short shift) [inline, protected]
get the third parameter on the high edge
Definition at line 156 of file FilterSource.h.
Referenced by interpolEH(), interpolEV(), and interpolEVH().
unsigned char* FilterYV12::interParD (unsigned char * src, short x, short size, short shift) [inline, protected]
get the fourth parameter on the high edge
Definition at line 159 of file FilterSource.h.
Referenced by interpolEH(), interpolEV(), and interpolEVH().
int FilterYV12::interpol (int a, int b, int c, int d) [inline, protected]
interpolation function
Definition at line 130 of file FilterSource.h.
Referenced by interpolEH(), interpolEV(), interpolEVH(), interpolH(), interpolV(), and interpolVH().
int FilterYV12::interpolEH (unsigned char * src, short x, short size) [inline, protected]
horizontal interpolation on edges
Definition at line 163 of file FilterSource.h.
References interParA(), interParC(), interParD(), and interpol().
Referenced by filter().
int FilterYV12::interpolEV (unsigned char * src, short y, short size) [inline, protected]
vertical interpolation on edges
Definition at line 170 of file FilterSource.h.
References interParA(), interParC(), interParD(), interpol(), and m_pitchUV.
Referenced by filter(), and interpolEVH().
int FilterYV12::interpolEVH (unsigned char * src, short x, short y, short * size) [inline, protected]
joined vertical and horizontal interpolation on edges
Definition at line 177 of file FilterSource.h.
References interParA(), interParC(), interParD(), interpol(), and interpolEV().
Referenced by filter().
int FilterYV12::interpolH (unsigned char * src) [inline, protected]
common horizontal interpolation
Definition at line 134 of file FilterSource.h.
References interpol().
Referenced by filter().
int FilterYV12::interpolV (unsigned char * src) [inline, protected]
common vertical interpolation
Definition at line 138 of file FilterSource.h.
References interpol(), and m_pitchUV.
Referenced by filter(), and interpolVH().
int FilterYV12::interpolVH (unsigned char * src) [inline, protected]
common joined vertical and horizontal interpolation
Definition at line 142 of file FilterSource.h.
References interpol(), and interpolV().
Referenced by filter().
bool FilterYV12::isEdge (short x, short y, short * size) [inline, protected]
is pixel on edge
Definition at line 149 of file FilterSource.h.
Referenced by filter().
void FilterYV12::setBuffs (unsigned char * buff, short * size) [inline]
set pointers to color buffers
Definition at line 113 of file FilterSource.h.
References m_buffU, m_buffV, and m_pitchUV.
Referenced by VideoBase::process().
Member Data Documentation
unsigned char* FilterYV12::m_buffU [protected]
begin of U buffer
Definition at line 125 of file FilterSource.h.
Referenced by filter(), and setBuffs().
unsigned char* FilterYV12::m_buffV [protected]
begin of V buffer
Definition at line 123 of file FilterSource.h.
Referenced by filter(), and setBuffs().
short FilterYV12::m_pitchUV [protected]
pitch for V & U buffers
Definition at line 127 of file FilterSource.h.
Referenced by filter(), interpolEV(), interpolV(), and setBuffs().
The documentation for this class was generated from the following file:
FilterSource.h