Blender: path_util.c File Reference
path_util.c File Reference
blenlib
#include <ctype.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include "MEM_guardedalloc.h"
#include "DNA_listBase.h"
#include "BLI_fileops.h"
#include "BLI_path_util.h"
#include "BLI_string.h"
#include "BLI_string_utf8.h"
#include "BLI_utildefines.h"
#include "BKE_utildefines.h"
#include "BKE_blender.h"
#include "GHOST_Path-api.h"
#include <fnmatch.h>
Defines
#define _GNU_SOURCE
#define BLENDER_USER_FORMAT "%s/.blender/%s"
#define BLENDER_SYSTEM_FORMAT "%s/blender/%s"
#define UNIQUE_NAME_MAX 128
#define GIVE_STRADDR(data, offset) (((char *)data) + offset)
Functions
static int add_win32_extension (char *name)
static char * blender_version_decimal (const int ver)
int BLI_stringdec (const char *string, char *head, char *tail, unsigned short *numlen)
void BLI_stringenc (char *string, const char *head, const char *tail, unsigned short numlen, int pic)
int BLI_split_name_num (char *left, int *nr, const char *name, const char delim)
void BLI_newname (char *name, int add)
int BLI_uniquename_cb (int(*unique_check)(void *, const char *), void *arg, const char defname[], char delim, char *name, short name_len)
static int uniquename_find_dupe (ListBase *list, void *vlink, const char *name, short name_offs)
static int uniquename_unique_check (void *arg, const char *name)
void BLI_uniquename (ListBase *list, void *vlink, const char defname[], char delim, short name_offs, short name_len)
void BLI_cleanup_path (const char *relabase, char *dir)
void BLI_cleanup_dir (const char *relabase, char *dir)
void BLI_cleanup_file (const char *relabase, char *dir)
void BLI_path_rel (char *file, const char *relfile)
int BLI_has_parent (char *path)
int BLI_parent_dir (char *path)
static int stringframe_chars (char *path, int *char_start, int *char_end)
static void ensure_digits (char *path, int digits)
int BLI_path_frame (char *path, int frame, int digits)
int BLI_path_frame_range (char *path, int sta, int end, int digits)
int BLI_path_abs (char *path, const char *basepath)
int BLI_path_cwd (char *path)
void BLI_splitdirstring (char *di, char *fi)
void BLI_getlastdir (const char *dir, char *last, const size_t maxlen)
const char * BLI_getDefaultDocumentFolder (void)
static int test_path (char *targetpath, const char *path_base, const char *path_sep, const char *folder_name)
static int test_env_path (char *path, const char *envvar)
static int get_path_local (char *targetpath, const char *folder_name, const char *subfolder_name, const int ver)
static int is_portable_install (void)
static int get_path_user (char *targetpath, const char *folder_name, const char *subfolder_name, const char *envvar, const int ver)
static int get_path_system (char *targetpath, const char *folder_name, const char *subfolder_name, const char *envvar, const int ver)
char * BLI_get_folder (int folder_id, const char *subfolder)
char * BLI_get_user_folder_notest (int folder_id, const char *subfolder)
char * BLI_get_folder_create (int folder_id, const char *subfolder)
char * BLI_get_folder_version (const int id, const int ver, const int do_check)
void BLI_setenv (const char *env, const char *val)
void BLI_setenv_if_new (const char *env, const char *val)
void BLI_clean (char *path)
void BLI_char_switch (char *string, char from, char to)
void BLI_make_exist (char *dir)
void BLI_make_existing_file (const char *name)
void BLI_make_file_string (const char *relabase, char *string, const char *dir, const char *file)
int BLI_testextensie (const char *str, const char *ext)
int BLI_testextensie_array (const char *str, const char **ext_array)
int BLI_testextensie_glob (const char *str, const char *ext_fnmatch)
int BLI_replace_extension (char *path, size_t maxlen, const char *ext)
int BLI_ensure_extension (char *path, size_t maxlen, const char *ext)
void BLI_split_dirfile (const char *string, char *dir, char *file, const size_t dirlen, const size_t filelen)
void BLI_split_dir_part (const char *string, char *dir, const size_t dirlen)
void BLI_split_file_part (const char *string, char *file, const size_t filelen)
void BLI_join_dirfile (char *dst, const size_t maxlen, const char *dir, const char *file)
char * BLI_path_basename (char *path)
int BKE_rebase_path (char *abs, size_t abs_len, char *rel, size_t rel_len, const char *base_dir, const char *src_dir, const char *dest_dir)
char * BLI_first_slash (char *string)
char * BLI_last_slash (const char *string)
int BLI_add_slash (char *string)
void BLI_del_slash (char *string)
static void bli_where_am_i (char *fullname, const size_t maxlen, const char *name)
void BLI_init_program_path (const char *argv0)
const char * BLI_program_path (void)
const char * BLI_program_dir (void)
static void BLI_where_is_temp (char *fullname, const size_t maxlen, char *userdir)
void BLI_init_temporary_dir (char *userdir)
const char * BLI_temporary_dir (void)
void BLI_system_temporary_dir (char *dir)
Variables
static char bprogname [FILE_MAX]
static char bprogdir [FILE_MAX]
static char btempdir [FILE_MAX]
Detailed Description
Definition in file path_util.c.
Define Documentation
#define _GNU_SOURCE
Definition at line 59 of file path_util.c.
#define BLENDER_SYSTEM_FORMAT "%s/blender/%s"
Definition at line 93 of file path_util.c.
Referenced by get_path_system().
#define BLENDER_USER_FORMAT "%s/.blender/%s"
Definition at line 89 of file path_util.c.
Referenced by get_path_user().
#define GIVE_STRADDR (data, offset) (((char *)data) + offset)
Definition at line 257 of file path_util.c.
Referenced by BLI_uniquename(), and uniquename_find_dupe().
#define UNIQUE_NAME_MAX 128
Definition at line 97 of file path_util.c.
Referenced by BLI_newname(), BLI_uniquename(), and BLI_uniquename_cb().
Function Documentation
static int add_win32_extension (char * name) [static]
Definition at line 1721 of file path_util.c.
References BLI_exists(), FILE_MAX, and S_ISDIR.
Referenced by bli_where_am_i().
int BKE_rebase_path (char * abs, size_t abs_len, char * rel, size_t rel_len, const char * base_dir, const char * src_dir, const char * dest_dir)
Produce image export path.
Fails returning 0 if image filename is empty or if destination path matches image path (i.e. both are the same file).
Trailing slash in dest_dir is optional.
Logic:
if an image is "below" current .blend file directory, rebuild the same dir structure in dest_dir
For example //textures/foo/bar.png becomes [dest_dir]/textures/foo/bar.png.
if an image is not "below" current .blend file directory, disregard it's path and copy it in the same directory where 3D file goes.
For example //../foo/bar.png becomes [dest_dir]/bar.png.
This logic will help ensure that all image paths are relative and that a user gets his images in one place. It'll also provide consistent behavior across exporters.
Definition at line 1594 of file path_util.c.
References BLI_join_dirfile(), BLI_path_abs(), BLI_path_cmp, BLI_split_dir_part(), BLI_split_dirfile(), BLI_strncpy(), FILE_MAX, len(), and strlen().
Referenced by ImagesExporter::operator()().
static char * blender_version_decimal (const int ver) [static]
Definition at line 863 of file path_util.c.
Referenced by get_path_local(), get_path_system(), and get_path_user().
int BLI_add_slash (char * string)
Definition at line 1695 of file path_util.c.
References len(), SEP, and strlen().
Referenced by autocomplete_directory(), BLI_cleanup_dir(), BLI_has_parent(), BLI_parent_dir(), BLI_where_is_temp(), file_browse_exec(), file_directory_exec(), file_panel_category(), file_select_do(), and ptcache_path().
void BLI_char_switch (char * string, char from, char to)
Change every from in string into to. The result will be in string
string The string to work on from The character to replace to The character to replace with
Definition at line 1238 of file path_util.c.
References NULL.
Referenced by BLI_clean(), BLI_make_exist(), BLI_make_file_string(), BLI_path_abs(), BLI_path_rel(), and uri_from_filename().
void BLI_clean (char * path)
Definition at line 1225 of file path_util.c.
References BLI_char_switch(), BLI_strnlen(), and NULL.
Referenced by BLI_has_parent(), BLI_make_file_string(), clean_paths(), and clean_paths_visit_cb().
void BLI_cleanup_dir (const char * relabase, char * dir)
Definition at line 417 of file path_util.c.
References BLI_add_slash(), and BLI_cleanup_path().
Referenced by BLI_parent_dir(), BLO_write_file(), bookmark_select_exec(), cleanup_path(), ED_fileselect_set_params(), file_directory_exec(), file_parent_exec(), file_select_do(), filelist_read_dir(), and filelist_read_library().
void BLI_cleanup_file (const char * relabase, char * dir)
dir can be any input, like from buttons, and this function converts it to a regular full path. Also removes garbage from directory paths, like /../ or double slashes etc
Definition at line 424 of file path_util.c.
References BLI_cleanup_path(), and BLI_del_slash().
Referenced by bpath_relocate_visitor().
void BLI_cleanup_path (const char * relabase, char * dir)
Definition at line 319 of file path_util.c.
References BLI_path_abs(), get_default_root(), and strlen().
Referenced by BLI_cleanup_dir(), BLI_cleanup_file(), BLI_path_abs(), and BLI_path_rel().
void BLI_del_slash (char * string)
Definition at line 1707 of file path_util.c.
References len(), SEP, and strlen().
Referenced by BLI_cleanup_file(), file_panel_category(), and strip_last_slash().
int BLI_ensure_extension (char * path, size_t maxlen, const char * ext)
Definition at line 1459 of file path_util.c.
References strlen().
Referenced by BKE_add_image_extension(), and blend_save_check().
char* BLI_first_slash (char * string)
Definition at line 1666 of file path_util.c.
char* BLI_get_folder (int folder_id, const char * subfolder)
Definition at line 1065 of file path_util.c.
References BLENDER_DATAFILES, BLENDER_SYSTEM_DATAFILES, BLENDER_SYSTEM_PYTHON, BLENDER_SYSTEM_SCRIPTS, BLENDER_USER_AUTOSAVE, BLENDER_USER_CONFIG, BLENDER_USER_DATAFILES, BLENDER_USER_SCRIPTS, BLENDER_VERSION, FILE_MAX, get_path_local(), get_path_system(), get_path_user(), and NULL.
Referenced by BLI_get_folder_create(), BPy_init_modules(), BPY_python_start(), bpy_script_paths(), bpy_user_resource(), ED_file_init(), get_brush_icon(), init_iconfile_list(), init_internal_icons(), WM_read_history(), and WM_read_homefile().
char* BLI_get_folder_create (int folder_id, const char * subfolder)
Definition at line 1137 of file path_util.c.
References BLENDER_USER_AUTOSAVE, BLENDER_USER_CONFIG, BLENDER_USER_DATAFILES, BLENDER_USER_SCRIPTS, BLI_dir_create_recursive(), BLI_get_folder(), BLI_get_user_folder_notest(), ELEM4, and NULL.
Referenced by BLO_write_file(), bookmark_add_exec(), bookmark_delete_exec(), file_exec(), wm_autosave_location(), WM_write_homefile(), and write_history().
char* BLI_get_folder_version (const int id, const int ver, const int do_check)
Definition at line 1155 of file path_util.c.
References BLENDER_RESOURCE_PATH_LOCAL, BLENDER_RESOURCE_PATH_SYSTEM, BLENDER_RESOURCE_PATH_USER, BLI_assert, FALSE, FILE_MAX, get_path_local(), get_path_system(), get_path_user(), and NULL.
Referenced by bpy_resource_path(), and wm_resource_check_prev().
char* BLI_get_user_folder_notest (int folder_id, const char * subfolder)
Definition at line 1112 of file path_util.c.
References BLENDER_USER_AUTOSAVE, BLENDER_USER_CONFIG, BLENDER_USER_DATAFILES, BLENDER_USER_SCRIPTS, BLENDER_VERSION, FILE_MAX, get_path_user(), and NULL.
Referenced by BLI_get_folder_create(), and bpy_user_resource().
const char* BLI_getDefaultDocumentFolder (void)
Definition at line 820 of file path_util.c.
References BLI_is_dir(), HRESULT, MAXPATHLEN, NULL, S_OK, and uput_getenv().
Referenced by file_expand_directory(), and WM_init().
void BLI_getlastdir (const char * dir, char * last, const size_t maxlen)
Definition at line 797 of file path_util.c.
References BLI_strncpy(), and NULL.
Referenced by file_panel_category().
int BLI_has_parent (char * path)
Definition at line 528 of file path_util.c.
References BLI_add_slash(), BLI_clean(), and len().
Referenced by file_parent_exec().
void BLI_init_program_path (const char * argv0)
Definition at line 1864 of file path_util.c.
References BLI_split_dir_part(), bli_where_am_i(), bprogdir, and bprogname.
Referenced by main().
void BLI_init_temporary_dir (char * userdir)
Definition at line 1937 of file path_util.c.
References BLI_where_is_temp(), btempdir, and FILE_MAX.
Referenced by main(), and wm_init_userdef().
void BLI_join_dirfile (char * dst, const size_t maxlen, const char * dir, const char * file)
Definition at line 1525 of file path_util.c.
References BLI_strncpy(), BLI_strnlen(), NULL, and SEP.
Referenced by autocomplete_directory(), BKE_ptcache_disk_cache_rename(), BKE_ptcache_id_clear(), BKE_ptcache_remove(), BKE_rebase_path(), blf_dir_search(), bli_where_am_i(), check_destination(), do_versions(), dynamicPaint_bakeImageSequence(), exec_output_file_singlelayer(), file_draw_check_exists(), file_expand_directory(), file_sfile_to_operator(), filelist_read_library(), findFileRecursive(), get_index_dir(), get_path_local(), get_path_system(), get_proxy_filename(), get_tc_filename(), init_iconfile_list(), init_internal_icons(), join_dirfile_alloc(), modifier_path_init(), new_folder_path(), particles_fluid_step(), reload_sequence_new_file(), rewrite_path_fixed_dirfile(), seq_open_anim_file(), seq_proxy_get_fname(), seq_render_strip(), sequencer_add_generic_strip_exec(), test_path(), and DocumentImporter::writeImage().
char* BLI_last_slash (const char * string)
Definition at line 1680 of file path_util.c.
Referenced by BLI_dir_create_recursive(), BLI_make_file_string(), BLI_path_abs(), BLI_path_basename(), BLI_path_rel(), BLI_split_dirfile(), BLI_splitdirstring(), BLI_stringdec(), bli_where_am_i(), BLO_is_a_library(), check_destination(), ensure_digits(), file_browse_invoke(), groupname_to_code(), image_info(), and untitled().
void BLI_make_exist (char * dir)
Definition at line 1247 of file path_util.c.
References ALTSEP, BLI_char_switch(), BLI_is_dir(), get_default_root(), SEP, and strlen().
Referenced by filelist_parent(), and filelist_read_library().
void BLI_make_existing_file (const char * name)
Definition at line 1275 of file path_util.c.
References BLI_dir_create_recursive(), BLI_exists(), BLI_splitdirstring(), BLI_strncpy(), FILE_MAX, and FILE_MAXFILE.
Referenced by BKE_write_ibuf(), collada_export(), dynamicPaint_outputSurfaceImage(), exec_output_file_multilayer(), filepath_avi(), IMB_index_builder_create(), index_fallback_create_context(), movieclip_build_proxy_ibuf(), ImagesExporter::operator()(), ptcache_file_open(), RE_BlenderAnim(), RE_WriteRenderResult(), seq_proxy_build_frame(), and writePackedFile().
void BLI_make_file_string (const char * relabase, char * string, const char * dir, const char * file)
Definition at line 1289 of file path_util.c.
References BLI_char_switch(), BLI_clean(), BLI_last_slash(), BLI_strncpy(), BLI_strnlen(), ELEM, get_default_root(), NULL, and strlen().
Referenced by BKE_undo_save_quit(), BKE_write_undo(), BLI_path_cwd(), BLO_write_file(), bookmark_add_exec(), bookmark_delete_exec(), ED_file_init(), file_delete_exec(), file_exec(), get_brush_icon(), renamebutton_cb(), render_result_exr_file_path(), test_path(), touch_seq_files(), wm_autosave_delete(), wm_autosave_location(), WM_init(), WM_read_history(), WM_read_homefile(), wm_recover_last_session_exec(), WM_write_homefile(), and write_history().
void BLI_newname (char * name, int add)
Definition at line 194 of file path_util.c.
References add(), BLI_stringdec(), BLI_stringenc(), KDL::exp(), i, and UNIQUE_NAME_MAX.
Referenced by file_filenum_exec(), and make_unique_prop_names().
int BLI_parent_dir (char * path)
Definition at line 543 of file path_util.c.
References BLI_add_slash(), BLI_cleanup_dir(), BLI_strncpy(), BLI_testextensie(), FILE_MAX, NULL, and SEP.
Referenced by file_parent_exec(), file_select_do(), filelist_parent(), and wm_link_append_invoke().
int BLI_path_abs (char * path, const char * basepath)
Blender's path code replacement function. Bases path strings leading with "//" by the directory basepath, and replaces instances of '#' with the framenum. Results are written back into path.
path The path to convert basepath The directory to base relative paths with. framenum The framenumber to replace the frame code with.
Return values:
Returns true if the path was relative (started with "//").
Definition at line 645 of file path_util.c.
References BLI_char_switch(), BLI_cleanup_path(), BLI_last_slash(), BLI_strncpy(), FILE_MAX, get_default_root(), NULL, and p.
Referenced by add_text(), BKE_add_image_file(), BKE_add_movieclip_file(), BKE_library_filepath_set(), BKE_makepicstring(), BKE_rebase_path(), BL_MakeScreenShot(), BLI_cleanup_path(), bpath_relocate_visitor(), bpy_lib_load(), cache_voxeldata(), checkPackedFile(), customdata_external_filename(), do_versions(), dynamicPaint_outputSurfaceImage(), ED_fileselect_set_params(), file_browse_exec(), file_operator_to_sfile(), filepath_avi(), get_brush_icon(), get_proxy_fname(), get_sequence_fname(), GetFontId(), image_load_image_file(), image_load_movie_file(), image_load_sequence_file(), image_save_sequence_exec(), main(), makeFilesAbsolute_visit_cb(), movieclip_open_anim_file(), namebutton_cb(), newPackedFile(), ImagesExporter::operator()(), particles_fluid_step(), ptcache_path(), RE_WriteEnvmapResult(), reload_sequence_new_file(), reopen_text(), rewrite_path_alloc(), rewrite_path_fixed(), rewrite_path_fixed_dirfile(), save_image_options_from_op(), save_image_options_init(), screenshot_exec(), seq_open_anim_file(), seq_proxy_get_fname(), seq_render_strip(), sequencer_add_movie_strip(), sequencer_generic_invoke_path__internal(), sound_mixdown_exec(), sound_new_file(), space_image_file_exists_poll(), StartKetsjiShell(), text_file_modified(), text_ignore_modified(), txt_write_file(), and writePackedFile().
char* BLI_path_basename (char * path)
Definition at line 1562 of file path_util.c.
References BLI_last_slash().
Referenced by add_text(), BKE_add_image_imbuf(), bpy_text_reimport(), findMissingFiles_visit_cb(), recent_files_menu_draw(), seq_load_operator_info(), and wm_block_create_splash().
int BLI_path_cwd (char * path)
Definition at line 743 of file path_util.c.
References BLI_current_working_dir(), BLI_make_file_string(), BLI_strncpy(), FILE_MAX, NULL, and strlen().
Referenced by load_file(), main(), and run_python().
int BLI_path_frame (char * path, int frame, int digits)
Definition at line 611 of file path_util.c.
References ensure_digits(), FILE_MAX, and stringframe_chars().
Referenced by BKE_makepicstring(), dynamicPaint_bakeImageSequence(), get_proxy_fname(), particles_fluid_step(), and seq_proxy_get_fname().
int BLI_path_frame_range (char * path, int sta, int end, int digits)
Definition at line 627 of file path_util.c.
References BLI_snprintf(), BLI_strncpy(), ensure_digits(), FILE_MAX, and stringframe_chars().
Referenced by filepath_avi().
void BLI_path_rel (char * file, const char * relfile)
Definition at line 430 of file path_util.c.
References BLI_char_switch(), BLI_cleanup_path(), BLI_last_slash(), BLI_strncpy(), BLI_strnlen(), FILE_MAX, get_default_root(), NULL, and p.
Referenced by bpath_relocate_visitor(), file_sfile_to_operator(), fix_relpaths_library(), library_append_end(), makeFilesRelative_visit_cb(), multires_external_save_exec(), save_image_doit(), seq_load_operator_info(), and sequencer_change_path_exec().
const char* BLI_program_dir (void)
Definition at line 1875 of file path_util.c.
References bprogdir.
const char* BLI_program_path (void)
Definition at line 1870 of file path_util.c.
References bprogname.
Referenced by BPY_python_start(), main(), and make_app_info().
int BLI_replace_extension (char * path, size_t maxlen, const char * ext)
Definition at line 1435 of file path_util.c.
References ELEM3, and strlen().
Referenced by BKE_add_image_extension(), imb_cache_filename(), WM_write_file(), and write_crash_blend().
void BLI_setenv (const char * env, const char * val)
Definition at line 1192 of file path_util.c.
References MEM_freeN(), MEM_mallocN(), strlen(), and uputenv().
Referenced by BLI_setenv_if_new(), BPY_python_start(), main(), PyC_SetHomePath(), and set_env().
void BLI_setenv_if_new (const char * env, const char * val)
Only set an env var if already not there. Like Unix setenv(env, val, 0);
Definition at line 1218 of file path_util.c.
References BLI_setenv(), and NULL.
void BLI_split_dir_part (const char * string, char * dir, const size_t dirlen)
Definition at line 1514 of file path_util.c.
References BLI_split_dirfile(), and NULL.
Referenced by autocomplete_directory(), BKE_rebase_path(), BLI_init_program_path(), BLO_write_file(), findMissingFiles(), ImagesExporter::operator()(), sequencer_add_generic_strip_exec(), and DocumentImporter::writeImage().
void BLI_split_dirfile (const char * string, char * dir, char * file, const size_t dirlen, const size_t filelen)
Definition at line 1495 of file path_util.c.
References BLI_last_slash(), BLI_strncpy(), and MIN2.
Referenced by BKE_rebase_path(), BLI_split_dir_part(), BLI_split_file_part(), ED_fileselect_set_params(), file_directory_exec(), file_operator_to_sfile(), get_proxy_fname(), rewrite_path_fixed_dirfile(), sequencer_add_movie_strip(), and sequencer_drop_copy().
void BLI_split_file_part (const char * string, char * file, const size_t filelen)
Definition at line 1519 of file path_util.c.
References BLI_split_dirfile(), and NULL.
Referenced by ptcache_path().
int BLI_split_name_num (char * left, int * nr, const char * name, const char delim)
Definition at line 164 of file path_util.c.
References strlen().
Referenced by BLI_uniquename_cb(), check_for_dupid(), copy_mball_properties(), find_basis_mball(), init_meta(), and is_mball_basis_for().
void BLI_splitdirstring (char * di, char * fi)
Definition at line 783 of file path_util.c.
References BLI_last_slash(), BLI_strncpy(), and FILE_MAXFILE.
Referenced by BLI_make_existing_file(), cleanup_path(), file_browse_exec(), get_index_dir(), image_save_sequence_exec(), load_vfont(), render_result_exr_file_path(), unpack_menu(), unpackImage(), unpackSound(), and unpackVFont().
int BLI_stringdec (const char * string, char * head, char * tail, unsigned short * numlen)
Definition at line 108 of file path_util.c.
References BLI_last_slash(), i, len(), and strlen().
Referenced by BLI_newname(), get_sequence_fname(), image_load_sequence_file(), and movieclip_calc_length().
void BLI_stringenc (char * string, const char * head, const char * tail, unsigned short numlen, int pic)
Definition at line 154 of file path_util.c.
Referenced by an_stringenc(), BLI_newname(), get_sequence_fname(), and image_load_sequence_file().
void BLI_system_temporary_dir (char * dir)
Definition at line 1947 of file path_util.c.
References BLI_where_is_temp(), FILE_MAX, and NULL.
Referenced by init_userdef_do_versions().
const char* BLI_temporary_dir (void)
Definition at line 1942 of file path_util.c.
References btempdir.
Referenced by BKE_undo_save_quit(), BKE_write_undo(), bpy_app_tempdir_get(), modifier_path_init(), modifier_path_relbase(), ptcache_path(), render_result_exr_file_path(), wm_autosave_delete(), wm_autosave_location(), and wm_recover_last_session_exec().
int BLI_testextensie (const char * str, const char * ext)
Definition at line 1371 of file path_util.c.
References BLI_strcasecmp(), and strlen().
Referenced by BKE_add_image_extension(), BLI_parent_dir(), BLI_testextensie_array(), BLO_has_bfile_extension(), BPY_modules_load_user(), do_write_image_or_movie(), file_extension_type(), filepath_avi(), IMB_isanim(), and init_iconfile_list().
int BLI_testextensie_array (const char * str, const char ** ext_array)
Definition at line 1392 of file path_util.c.
References BLI_testextensie(), and i.
Referenced by BKE_add_image_extension(), BKE_add_image_file(), BKE_add_movieclip_file(), BKE_movieclip_reload(), file_extension_type(), image_replace_exec(), and IMB_ispic().
int BLI_testextensie_glob (const char * str, const char * ext_fnmatch)
Definition at line 1407 of file path_util.c.
References BLI_strncpy(), and FNM_CASEFOLD.
Referenced by filelist_setfiletypes().
void BLI_uniquename (ListBase * list, void * vlink, const char defname[], char delim, short name_offs, short name_len)
Definition at line 291 of file path_util.c.
References assert, BLI_uniquename_cb(), data, ELEM, GIVE_STRADDR, NULL, UNIQUE_NAME_MAX, and uniquename_unique_check().
Referenced by action_groups_add_new(), AnimationImporter::add_bone_fcurve(), add_keyblock(), add_nlatrack(), BKE_keyingset_add(), BKE_track_unique_name(), BKE_tracking_object_unique_name(), driver_add_new_variable(), fcurve_add_to_list(), gpencil_layer_addnew(), modifier_unique_name(), namebutton_cb(), nodeUniqueName(), pose_add_group(), poselib_add_exec(), poselib_rename_exec(), scene_add_render_layer(), tracks_map_merge(), and unique_constraint_name().
int BLI_uniquename_cb (int(*)(void *, const char *) unique_check, void * arg, const char defname[], char delim, char * name, short name_len)
Definition at line 218 of file path_util.c.
References BLI_snprintf(), BLI_split_name_num(), BLI_strncat_utf8(), BLI_strncpy(), left(), len(), and UNIQUE_NAME_MAX.
Referenced by BKE_nlastrip_validate_name(), BLI_uniquename(), CustomData_set_layer_unique_name(), defgroup_unique_name(), dynamicPaintSurface_setUniqueName(), surface_setUniqueOutputName(), unique_bone_name(), unique_editbone_name(), and uniqueOrientationName().
static void bli_where_am_i (char * fullname, const size_t maxlen, const char * name) [static]
Checks if name is a fully qualified filename to an executable. If not it searches $PATH for the file. On Windows it also adds the correct extension (.com .exe etc) from $PATHEXT if necessary. Also on Windows it translates the name to its 8.3 version to prevent problems with spaces and stuff. Final result is returned in fullname.
Parameters:
fullname The full path and full name of the executable (must be FILE_MAX minimum)
name The name of the executable (usually argv[0]) to be checked
Definition at line 1776 of file path_util.c.
References add_win32_extension(), BLI_current_working_dir(), BLI_exists(), BLI_join_dirfile(), BLI_last_slash(), BLI_strncpy(), conv_utf_16_to_8(), FILE_MAX, MEM_freeN(), MEM_mallocN(), NULL, and SEP.
Referenced by BLI_init_program_path().
static void BLI_where_is_temp (char * fullname, const size_t maxlen, char * userdir) [static]
Gets the temp directory when blender first runs. If the default path is not found, use try $TEMP
Also make sure the temp dir has a trailing slash
Parameters:
fullname The full path to the temp directory
maxlen The size of the fullname buffer
userdir Directory specified in user preferences
Definition at line 1890 of file path_util.c.
References BLI_add_slash(), BLI_is_dir(), and BLI_strncpy().
Referenced by BLI_init_temporary_dir(), and BLI_system_temporary_dir().
static void ensure_digits (char * path, int digits) [static]
Definition at line 594 of file path_util.c.
References BLI_last_slash(), len(), NULL, and strlen().
Referenced by BLI_path_frame(), and BLI_path_frame_range().
static int get_path_local (char * targetpath, const char * folder_name, const char * subfolder_name, const int ver) [static]
Definition at line 913 of file path_util.c.
References blender_version_decimal(), BLI_join_dirfile(), BLI_strncpy(), bprogdir, FILE_MAX, and test_path().
Referenced by BLI_get_folder(), BLI_get_folder_version(), get_path_user(), and is_portable_install().
static int get_path_system (char * targetpath, const char * folder_name, const char * subfolder_name, const char * envvar, const int ver) [static]
Definition at line 992 of file path_util.c.
References BLENDER_SYSTEM_FORMAT, blender_version_decimal(), BLI_current_working_dir(), BLI_join_dirfile(), BLI_snprintf(), BLI_strncpy(), bprogdir, FILE_MAX, GHOST_getSystemDir(), NULL, test_env_path(), and test_path().
Referenced by BLI_get_folder(), and BLI_get_folder_version().
static int get_path_user (char * targetpath, const char * folder_name, const char * subfolder_name, const char * envvar, const int ver) [static]
Definition at line 949 of file path_util.c.
References BLENDER_USER_FORMAT, blender_version_decimal(), BLI_snprintf(), BLI_strncpy(), FILE_MAX, get_path_local(), GHOST_getUserDir(), is_portable_install(), NULL, test_env_path(), and test_path().
Referenced by BLI_get_folder(), BLI_get_folder_version(), and BLI_get_user_folder_notest().
static int is_portable_install (void) [static]
Definition at line 940 of file path_util.c.
References BLENDER_VERSION, FILE_MAX, get_path_local(), and NULL.
Referenced by get_path_user().
static int stringframe_chars (char * path, int * char_start, int * char_end) [static]
Definition at line 561 of file path_util.c.
References i.
Referenced by BLI_path_frame(), and BLI_path_frame_range().
static int test_env_path (char * path, const char * envvar) [static]
Definition at line 898 of file path_util.c.
References BLI_is_dir(), BLI_strncpy(), FILE_MAX, and NULL.
Referenced by get_path_system(), and get_path_user().
static int test_path (char * targetpath, const char * path_base, const char * path_sep, const char * folder_name) [static]
Definition at line 870 of file path_util.c.
References BLI_is_dir(), BLI_join_dirfile(), BLI_make_file_string(), BLI_strncpy(), and FILE_MAX.
Referenced by get_path_local(), get_path_system(), and get_path_user().
static int uniquename_find_dupe (ListBase * list, void * vlink, const char * name, short name_offs) [static]
Definition at line 270 of file path_util.c.
References ListBase::first, GIVE_STRADDR, link(), and Link::next.
Referenced by uniquename_unique_check().
static int uniquename_unique_check (void * arg, const char * name) [static]
Definition at line 285 of file path_util.c.
References data, and uniquename_find_dupe().
Referenced by BLI_uniquename().
Variable Documentation
char bprogdir[FILE_MAX] [static]
Definition at line 100 of file path_util.c.
Referenced by BLI_init_program_path(), BLI_program_dir(), get_path_local(), and get_path_system().
char bprogname[FILE_MAX] [static]
Definition at line 99 of file path_util.c.
Referenced by BLI_init_program_path(), and BLI_program_path().
char btempdir[FILE_MAX] [static]
Definition at line 101 of file path_util.c.
Referenced by BLI_init_temporary_dir(), and BLI_temporary_dir().