Blender: NG_LoopBackNetworkDeviceInterface Class Reference
NG_LoopBackNetworkDeviceInterface Class Reference
#include <NG_LoopBackNetworkDeviceInterface.h>
Public Member Functions
NG_LoopBackNetworkDeviceInterface ()
virtual ~NG_LoopBackNetworkDeviceInterface ()
virtual void NextFrame ()
bool Connect (char *address, unsigned int port, char *password, unsigned int localport, unsigned int timeout)
bool Disconnect (void)
virtual void SendNetworkMessage (class NG_NetworkMessage *msg)
virtual std::vector
< NG_NetworkMessage * > RetrieveNetworkMessages ()
Detailed Description
Definition at line 38 of file NG_LoopBackNetworkDeviceInterface.h.
Constructor & Destructor Documentation
NG_LoopBackNetworkDeviceInterface::NG_LoopBackNetworkDeviceInterface ()
Definition at line 44 of file NG_LoopBackNetworkDeviceInterface.cpp.
NG_LoopBackNetworkDeviceInterface::~NG_LoopBackNetworkDeviceInterface () [virtual]
Definition at line 50 of file NG_LoopBackNetworkDeviceInterface.cpp.
Member Function Documentation
bool NG_LoopBackNetworkDeviceInterface::Connect (char * address, unsigned int port, char * password, unsigned int localport, unsigned int timeout) [inline, virtual]
Implements NG_NetworkDeviceInterface.
Definition at line 52 of file NG_LoopBackNetworkDeviceInterface.h.
bool NG_LoopBackNetworkDeviceInterface::Disconnect (void) [inline, virtual]
Implements NG_NetworkDeviceInterface.
Definition at line 55 of file NG_LoopBackNetworkDeviceInterface.h.
Referenced by GPG_Application::stopEngine().
void NG_LoopBackNetworkDeviceInterface::NextFrame () [virtual]
Clear message buffer
Implements NG_NetworkDeviceInterface.
Definition at line 55 of file NG_LoopBackNetworkDeviceInterface.cpp.
References size().
vector< NG_NetworkMessage * > NG_LoopBackNetworkDeviceInterface::RetrieveNetworkMessages () [virtual]
read NG_NetworkMessage from library buffer, may be irrelevant for loopbackdevices
Implements NG_NetworkDeviceInterface.
Definition at line 87 of file NG_LoopBackNetworkDeviceInterface.cpp.
void NG_LoopBackNetworkDeviceInterface::SendNetworkMessage (class NG_NetworkMessage * msg) [virtual]
Implements NG_NetworkDeviceInterface.
Definition at line 71 of file NG_LoopBackNetworkDeviceInterface.cpp.
References NG_NetworkMessage::AddRef(), NG_NetworkMessage::GetDestinationName(), NG_NetworkMessage::GetMessageText(), NG_NetworkMessage::GetSenderName(), NG_NetworkMessage::GetSubject(), and STR_String::ReadPtr().
Referenced by GPC_Engine::UpdateLoadingAnimation().
The documentation for this class was generated from the following files:
NG_LoopBackNetworkDeviceInterface.h
NG_LoopBackNetworkDeviceInterface.cpp