Blender: AUD_ReverseReader Class Reference
AUD_ReverseReader Class Reference
#include <AUD_ReverseReader.h>
Public Member Functions
AUD_ReverseReader (AUD_Reference< AUD_IReader > reader)
virtual void seek (int position)
virtual int getLength () const
virtual int getPosition () const
virtual void read (int &length, bool &eos, sample_t *buffer)
Detailed Description
This class reads another reader from back to front.
Note:
The underlying reader must be seekable.
Definition at line 40 of file AUD_ReverseReader.h.
Constructor & Destructor Documentation
AUD_ReverseReader::AUD_ReverseReader (AUD_Reference< AUD_IReader > reader)
Creates a new reverse reader.
Parameters:
reader The reader to read from.
Exceptions:
AUD_Exception Thrown if the reader specified has an undeterminable/infinite length or is not seekable.
Definition at line 37 of file AUD_ReverseReader.cpp.
References AUD_ERROR_PROPS, AUD_THROW, AUD_EffectReader::isSeekable(), and props_error.
Member Function Documentation
int AUD_ReverseReader::getLength () const [virtual]
Returns an approximated length of the source in samples.
Returns:
The length as sample count. May be negative if unknown.
Reimplemented from AUD_EffectReader.
Definition at line 51 of file AUD_ReverseReader.cpp.
int AUD_ReverseReader::getPosition () const [virtual]
Returns the position of the source as a sample count value.
Returns:
The current position in the source. A negative value indicates that the position is unknown.
Warning:
The value returned doesn't always have to be correct for readers, especially after seeking.
Reimplemented from AUD_EffectReader.
Definition at line 56 of file AUD_ReverseReader.cpp.
void AUD_ReverseReader::read (int & length, bool & eos, sample_t * buffer) [virtual]
Request to read the next length samples out of the source. The buffer supplied has the needed size.
Parameters:
[in,out] length The count of samples that should be read. Shall contain the real count of samples after reading, in case there were only fewer samples available. A smaller value also indicates the end of the reader.
[out] eos End of stream, whether the end is reached or not.
[in] buffer The pointer to the buffer to read into.
Reimplemented from AUD_EffectReader.
Definition at line 61 of file AUD_ReverseReader.cpp.
References AUD_CHANNEL_MAX, AUD_SAMPLE_SIZE, AUD_Specs::channels, AUD_EffectReader::getSpecs(), i, len(), length(), and AUD_EffectReader::m_reader.
void AUD_ReverseReader::seek (int position) [virtual]
Seeks to a specific position in the source.
Parameters:
position The position to seek for measured in samples. To get from a given time to the samples you simply have to multiply the time value in seconds with the sample rate of the reader.
Warning:
This may work or not, depending on the actual reader.
Reimplemented from AUD_EffectReader.
Definition at line 46 of file AUD_ReverseReader.cpp.
The documentation for this class was generated from the following files:
AUD_ReverseReader.h
AUD_ReverseReader.cpp