Blender: bsdf_transparent.h File Reference
bsdf_transparent.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void bsdf_transparent_setup (ShaderData *sd, ShaderClosure *sc)
__device void bsdf_transparent_blur (ShaderClosure *sc, float roughness)
__device float3 bsdf_transparent_eval_reflect (const ShaderData *sd, const ShaderClosure *sc, const float3 I, const float3 omega_in, float *pdf)
__device float3 bsdf_transparent_eval_transmit (const ShaderData *sd, const ShaderClosure *sc, const float3 I, const float3 omega_in, float *pdf)
__device float bsdf_transparent_albedo (const ShaderData *sd, const ShaderClosure *sc, const float3 I)
__device int bsdf_transparent_sample (const ShaderData *sd, const ShaderClosure *sc, float randu, float randv, float3 *eval, float3 *omega_in, float3 *domega_in_dx, float3 *domega_in_dy, float *pdf)
Function Documentation
__device float bsdf_transparent_albedo (const ShaderData * sd, const ShaderClosure * sc, const float3 I)
Definition at line 58 of file bsdf_transparent.h.
__device void bsdf_transparent_blur (ShaderClosure * sc, float roughness)
Definition at line 44 of file bsdf_transparent.h.
Referenced by svm_bsdf_blur().
__device float3 bsdf_transparent_eval_reflect (const ShaderData * sd, const ShaderClosure * sc, const float3 I, const float3 omega_in, float * pdf)
Definition at line 48 of file bsdf_transparent.h.
References make_float3().
Referenced by svm_bsdf_eval().
__device float3 bsdf_transparent_eval_transmit (const ShaderData * sd, const ShaderClosure * sc, const float3 I, const float3 omega_in, float * pdf)
Definition at line 53 of file bsdf_transparent.h.
References make_float3().
Referenced by svm_bsdf_eval().
__device int bsdf_transparent_sample (const ShaderData * sd, const ShaderClosure * sc, float randu, float randv, float3 * eval, float3 * omega_in, float3 * domega_in_dx, float3 * domega_in_dy, float * pdf)
Definition at line 63 of file bsdf_transparent.h.
References ShaderData::dI, differential3::dx, differential3::dy, ShaderData::I, LABEL_TRANSMIT, LABEL_TRANSPARENT, and make_float3().
Referenced by svm_bsdf_sample().
CCL_NAMESPACE_BEGIN __device void bsdf_transparent_setup (ShaderData * sd, ShaderClosure * sc)
Definition at line 38 of file bsdf_transparent.h.
References CLOSURE_BSDF_TRANSPARENT_ID, ShaderData::flag, SD_BSDF, and ShaderClosure::type.
Referenced by svm_node_closure_bsdf().