Blender: iTaSC::Distance Class Reference
iTaSC::Distance Class Reference
#include <Distance.hpp>
Public Types
enum ID { ID_DISTANCE = 1 }
Public Member Functions
Distance (double armlength=1.0, double accuracy=1e-6, unsigned int maximum_iterations=100)
virtual ~Distance ()
virtual bool setControlParameters (struct ConstraintValues *_values, unsigned int _nvalues, double timestep)
virtual const ConstraintValues * getControlParameters (unsigned int *_nvalues)
Protected Member Functions
virtual void updateKinematics (const Timestamp &timestamp)
virtual void pushCache (const Timestamp &timestamp)
virtual void updateJacobian ()
virtual bool initialise (Frame &init_pose)
virtual void initCache (Cache *_cache)
virtual void updateControlOutput (const Timestamp &timestamp)
virtual bool closeLoop ()
Detailed Description
Definition at line 19 of file Distance.hpp.
Member Enumeration Documentation
enum iTaSC::Distance::ID
Enumerator:
ID_DISTANCE
Definition at line 31 of file Distance.hpp.
Constructor & Destructor Documentation
iTaSC::Distance::Distance (double armlength = 1.0, double accuracy = 1e-6, unsigned int maximum_iterations = 100)
Definition at line 21 of file Distance.cpp.
References KDL::Chain::addSegment(), iTaSC::ConstraintValues::alpha, KDL::epsilon, iTaSC::ConstraintValues::feedback, iTaSC::ConstraintValues::id, iTaSC::ConstraintSingleValue::id, ID_DISTANCE, iTaSC::ConstraintSet::m_Cf, iTaSC::ConstraintSet::m_Wy, iTaSC::ConstraintValues::number, KDL::Joint::RotX, KDL::Joint::RotY, KDL::Joint::RotZ, iTaSC::ConstraintValues::tolerance, KDL::Joint::TransY, and iTaSC::ConstraintValues::values.
iTaSC::Distance::~Distance () [virtual]
Definition at line 54 of file Distance.cpp.
Member Function Documentation
bool iTaSC::Distance::closeLoop () [protected, virtual]
Reimplemented from iTaSC::ConstraintSet.
Definition at line 109 of file Distance.cpp.
References KDL::Equal(), iTaSC::F_identity, KDL::Frame::Inverse(), iTaSC::ConstraintSet::m_externalPose, iTaSC::ConstraintSet::m_internalPose, iTaSC::ConstraintSet::m_threshold, and updateJacobian().
const ConstraintValues * iTaSC::Distance::getControlParameters (unsigned int * _nvalues) [virtual]
Implements iTaSC::ConstraintSet.
Definition at line 281 of file Distance.cpp.
References iTaSC::ConstraintValues::action, iTaSC::ConstraintSingleValue::action, iTaSC::ConstraintSet::m_chi, iTaSC::ConstraintSet::m_ydot, iTaSC::ConstraintSingleValue::y, iTaSC::ConstraintSingleValue::yd, iTaSC::ConstraintSingleValue::yddot, and iTaSC::ConstraintSingleValue::ydot.
void iTaSC::Distance::initCache (Cache * _cache) [protected, virtual]
Implements iTaSC::ConstraintSet.
Definition at line 118 of file Distance.cpp.
References iTaSC::Cache::addChannel(), and iTaSC::distanceCacheSize.
bool iTaSC::Distance::initialise (Frame & init_pose) [protected, virtual]
Reimplemented from iTaSC::ConstraintSet.
Definition at line 99 of file Distance.cpp.
References iTaSC::ConstraintSet::m_externalPose, and updateJacobian().
void iTaSC::Distance::pushCache (const Timestamp & timestamp) [protected, virtual]
Implements iTaSC::ConstraintSet.
Definition at line 166 of file Distance.cpp.
References iTaSC::Timestamp::cache, iTaSC::Timestamp::cacheTimestamp, and iTaSC::Timestamp::substep.
Referenced by updateKinematics().
bool iTaSC::Distance::setControlParameters (struct ConstraintValues * _values, unsigned int _nvalues, double timestep) [virtual]
Implements iTaSC::ConstraintSet.
Definition at line 202 of file Distance.cpp.
References iTaSC::ACT_ALPHA, iTaSC::ACT_FEEDBACK, iTaSC::ACT_TOLERANCE, iTaSC::ACT_VALUE, iTaSC::ACT_VELOCITY, iTaSC::ConstraintValues::action, iTaSC::ConstraintSingleValue::action, iTaSC::ConstraintValues::alpha, KDL::epsilon, iTaSC::ConstraintValues::feedback, i, iTaSC::ConstraintValues::id, iTaSC::ConstraintSingleValue::id, ID_DISTANCE, if(), iTaSC::ConstraintSet::m_Wy, iTaSC::ConstraintValues::tolerance, iTaSC::ConstraintValues::values, iTaSC::ConstraintSingleValue::yd, and iTaSC::ConstraintSingleValue::yddot.
Referenced by updateControlOutput().
void iTaSC::Distance::updateControlOutput (const Timestamp & timestamp) [protected, virtual]
Implements iTaSC::ConstraintSet.
Definition at line 294 of file Distance.cpp.
References iTaSC::ConstraintValues::action, iTaSC::ConstraintSingleValue::action, iTaSC::Timestamp::cacheTimestamp, error(), iTaSC::Timestamp::interpolate, iTaSC::ConstraintSet::m_chi, iTaSC::ConstraintSet::m_constraintCallback, iTaSC::ConstraintSet::m_constraintParam, iTaSC::ConstraintSet::m_substep, iTaSC::ConstraintSet::m_ydot, KDL::Norm(), iTaSC::Timestamp::realTimestep, iTaSC::Timestamp::reiterate, setControlParameters(), TNT::sign(), iTaSC::Timestamp::substep, iTaSC::ConstraintSingleValue::y, iTaSC::ConstraintSingleValue::yd, iTaSC::ConstraintSingleValue::yddot, and iTaSC::ConstraintSingleValue::ydot.
void iTaSC::Distance::updateJacobian () [protected, virtual]
Implements iTaSC::ConstraintSet.
Definition at line 189 of file Distance.cpp.
References KDL::changeRefPoint(), i, KDL::ChainFkSolverPos_recursive::JntToCart(), KDL::ChainJntToJacSolver::JntToJac(), iTaSC::ConstraintSet::m_chi, iTaSC::ConstraintSet::m_internalPose, iTaSC::ConstraintSet::m_Jf, and KDL::Frame::p.
Referenced by closeLoop(), and initialise().
void iTaSC::Distance::updateKinematics (const Timestamp & timestamp) [protected, virtual]
Implements iTaSC::ConstraintSet.
Definition at line 172 of file Distance.cpp.
References KDL::epsilon, iTaSC::Timestamp::interpolate, pushCache(), iTaSC::Timestamp::realTimestep, and iTaSC::Timestamp::substep.
The documentation for this class was generated from the following files:
Distance.hpp
Distance.cpp