Blender: MOD_smoke.c File Reference
MOD_smoke.c File Reference
modifiers
#include <stddef.h>
#include "MEM_guardedalloc.h"
#include "DNA_group_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_smoke_types.h"
#include "DNA_object_force.h"
#include "BLI_utildefines.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_modifier.h"
#include "BKE_smoke.h"
#include "depsgraph_private.h"
#include "MOD_util.h"
Functions
static void initData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static void freeData (ModifierData *md)
static void deformVerts (ModifierData *md, Object *ob, DerivedMesh *derivedData, float(*vertexCos)[3], int UNUSED(numVerts), int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
static int dependsOnTime (ModifierData *UNUSED(md))
static void updateDepgraph (ModifierData *md, DagForest *forest, struct Scene *scene, Object *UNUSED(ob), DagNode *obNode)
static void foreachIDLink (ModifierData *md, Object *ob, IDWalkFunc walk, void *userData)
Variables
ModifierTypeInfo modifierType_Smoke
Detailed Description
Definition in file MOD_smoke.c.
Function Documentation
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 69 of file MOD_smoke.c.
References smokeModifier_copy().
static void deformVerts (ModifierData * md, Object * ob, DerivedMesh * derivedData, float(*) vertexCos[3], int UNUSEDnumVerts, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 84 of file MOD_smoke.c.
References get_cddm(), NULL, DerivedMesh::release, ModifierData::scene, and smokeModifier_do().
static int dependsOnTime (ModifierData * UNUSEDmd) [static]
Definition at line 100 of file MOD_smoke.c.
static void foreachIDLink (ModifierData * md, Object * ob, IDWalkFunc walk, void * userData) [static]
Definition at line 157 of file MOD_smoke.c.
References SmokeDomainSettings::coll_group, SmokeModifierData::domain, SmokeDomainSettings::eff_group, SmokeDomainSettings::effector_weights, SmokeDomainSettings::fluid_group, EffectorWeights::group, MOD_SMOKE_TYPE_DOMAIN, and SmokeModifierData::type.
static void freeData (ModifierData * md) [static]
Definition at line 77 of file MOD_smoke.c.
References smokeModifier_free().
static void initData (ModifierData * md) [static]
Definition at line 58 of file MOD_smoke.c.
References SmokeModifierData::coll, SmokeModifierData::domain, SmokeModifierData::flow, NULL, SmokeModifierData::time, and SmokeModifierData::type.
static void updateDepgraph (ModifierData * md, DagForest * forest, struct Scene * scene, Object * UNUSEDob, DagNode * obNode) [static]
Definition at line 105 of file MOD_smoke.c.
References Scene::base, SmokeModifierData::coll, SmokeDomainSettings::coll_group, dag_add_relation(), dag_get_node(), DAG_RL_DATA_DATA, DAG_RL_OB_DATA, SmokeModifierData::domain, eModifierType_Smoke, ListBase::first, SmokeModifierData::flow, SmokeDomainSettings::fluid_group, Group::gobject, MOD_SMOKE_TYPE_COLL, MOD_SMOKE_TYPE_DOMAIN, MOD_SMOKE_TYPE_FLOW, modifiers_findByType(), GroupObject::next, Base::next, NULL, GroupObject::ob, Base::object, and SmokeModifierData::type.
Variable Documentation
ModifierTypeInfo modifierType_Smoke
Initial value:
 {
                  "Smoke",
            "SmokeModifierData",
            sizeof(SmokeModifierData),
                  eModifierTypeType_OnlyDeform,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_UsesPointCache
                            | eModifierTypeFlag_Single,
              copyData,
           deformVerts,
        NULL,
         NULL,
      NULL,
         NULL,
       NULL,
              initData,
      NULL,
              freeData,
            NULL,
        updateDepgraph,
         dependsOnTime,
        NULL,
     NULL,
         foreachIDLink,
        NULL
}
Definition at line 173 of file MOD_smoke.c.