Blender: KX_NormalParentRelation Class Reference
KX_NormalParentRelation Class Reference
#include <KX_SG_NodeRelationships.h>
Public Member Functions
bool UpdateChildCoordinates (SG_Spatial *child, const SG_Spatial *parent, bool &parentUpdated)
SG_ParentRelation * NewCopy ()
~KX_NormalParentRelation ()
Static Public Member Functions
static KX_NormalParentRelation * New ()
Detailed Description
Definition at line 48 of file KX_SG_NodeRelationships.h.
Constructor & Destructor Documentation
KX_NormalParentRelation::~KX_NormalParentRelation ()
Definition at line 91 of file KX_SG_NodeRelationships.cpp.
Member Function Documentation
KX_NormalParentRelation * KX_NormalParentRelation::New () [static]
Allocate and construct a new KX_NormalParentRelation on the heap.
Implementation of classes defined in KX_SG_NodeRelationships.h first of all KX_NormalParentRelation
Definition at line 45 of file KX_SG_NodeRelationships.cpp.
Referenced by KX_Scene::AddNodeReplicaObject(), bl_ConvertBlenderObject_Single(), and KX_GameObject::KX_GameObject().
SG_ParentRelation * KX_NormalParentRelation::NewCopy () [virtual]
Method inherited from KX_ParentRelation
Implements SG_ParentRelation.
Definition at line 85 of file KX_SG_NodeRelationships.cpp.
bool KX_NormalParentRelation::UpdateChildCoordinates (SG_Spatial * child, const SG_Spatial * parent, bool & parentUpdated) [virtual]
Method inherited from KX_ParentRelation
Implements SG_ParentRelation.
Definition at line 52 of file KX_SG_NodeRelationships.cpp.
References SG_Spatial::ClearModified(), SG_Spatial::GetLocalOrientation(), SG_Spatial::GetLocalPosition(), SG_Spatial::GetLocalScale(), SG_Spatial::GetWorldOrientation(), SG_Spatial::GetWorldPosition(), SG_Spatial::GetWorldScaling(), SG_Spatial::IsModified(), MT_assert, NULL, SG_Spatial::SetWorldFromLocalTransform(), SG_Spatial::SetWorldOrientation(), SG_Spatial::SetWorldPosition(), and SG_Spatial::SetWorldScale().
The documentation for this class was generated from the following files:
KX_SG_NodeRelationships.h
KX_SG_NodeRelationships.cpp