Blender: DerivedMesh Struct Reference
DerivedMesh Struct Reference
#include <BKE_DerivedMesh.h>
Public Attributes
CustomData vertData
CustomData edgeData
CustomData faceData
CustomData loopData
CustomData polyData
int numVertData
int numEdgeData
int numTessFaceData
int numLoopData
int numPolyData
int needsFree
int deformedOnly
BVHCache bvhCache
struct GPUDrawObject * drawObject
DerivedMeshType type
float auto_bump_scale
DMDirtyFlag dirty
void(* calcNormals)(DerivedMesh *dm)
void(* recalcTessellation)(DerivedMesh *dm)
int(* getNumVerts)(DerivedMesh *dm)
int(* getNumEdges)(DerivedMesh *dm)
int(* getNumTessFaces)(DerivedMesh *dm)
int(* getNumLoops)(DerivedMesh *dm)
int(* getNumPolys)(DerivedMesh *dm)
void(* getVert)(DerivedMesh *dm, int index, struct MVert *vert_r)
void(* getEdge)(DerivedMesh *dm, int index, struct MEdge *edge_r)
void(* getTessFace)(DerivedMesh *dm, int index, struct MFace *face_r)
struct MVert *(* getVertArray)(DerivedMesh *dm)
struct MEdge *(* getEdgeArray)(DerivedMesh *dm)
struct MFace *(* getTessFaceArray)(DerivedMesh *dm)
struct MLoop *(* getLoopArray)(DerivedMesh *dm)
struct MPoly *(* getPolyArray)(DerivedMesh *dm)
void(* copyVertArray)(DerivedMesh *dm, struct MVert *vert_r)
void(* copyEdgeArray)(DerivedMesh *dm, struct MEdge *edge_r)
void(* copyTessFaceArray)(DerivedMesh *dm, struct MFace *face_r)
void(* copyLoopArray)(DerivedMesh *dm, struct MLoop *loop_r)
void(* copyPolyArray)(DerivedMesh *dm, struct MPoly *poly_r)
struct MVert *(* dupVertArray)(DerivedMesh *dm)
struct MEdge *(* dupEdgeArray)(DerivedMesh *dm)
struct MFace *(* dupTessFaceArray)(DerivedMesh *dm)
struct MLoop *(* dupLoopArray)(DerivedMesh *dm)
struct MPoly *(* dupPolyArray)(DerivedMesh *dm)
void *(* getVertData)(DerivedMesh *dm, int index, int type)
void *(* getEdgeData)(DerivedMesh *dm, int index, int type)
void *(* getTessFaceData)(DerivedMesh *dm, int index, int type)
void *(* getVertDataArray)(DerivedMesh *dm, int type)
void *(* getEdgeDataArray)(DerivedMesh *dm, int type)
void *(* getTessFaceDataArray)(DerivedMesh *dm, int type)
CustomData *(* getVertDataLayout)(DerivedMesh *dm)
CustomData *(* getEdgeDataLayout)(DerivedMesh *dm)
CustomData *(* getTessFaceDataLayout)(DerivedMesh *dm)
CustomData *(* getLoopDataLayout)(DerivedMesh *dm)
CustomData *(* getPolyDataLayout)(DerivedMesh *dm)
void(* copyFromVertCData)(DerivedMesh *dm, int source, CustomData *dst, int dest)
void(* copyFromEdgeCData)(DerivedMesh *dm, int source, CustomData *dst, int dest)
void(* copyFromFaceCData)(DerivedMesh *dm, int source, CustomData *dst, int dest)
int(* getNumGrids)(DerivedMesh *dm)
int(* getGridSize)(DerivedMesh *dm)
DMGridData **(* getGridData)(DerivedMesh *dm)
DMGridAdjacency *(* getGridAdjacency)(DerivedMesh *dm)
int *(* getGridOffset)(DerivedMesh *dm)
DMFlagMat *(* getGridFlagMats)(DerivedMesh *dm)
unsigned int **(* getGridHidden)(DerivedMesh *dm)
void(* foreachMappedVert)(DerivedMesh *dm, void(*func)(void *userData, int index, const float co[3], const float no_f[3], const short no_s[3]), void *userData)
void(* foreachMappedEdge)(DerivedMesh *dm, void(*func)(void *userData, int index, const float v0co[3], const float v1co[3]), void *userData)
void(* foreachMappedFaceCenter)(DerivedMesh *dm, void(*func)(void *userData, int index, const float cent[3], const float no[3]), void *userData)
void(* getMinMax)(DerivedMesh *dm, float min_r[3], float max_r[3])
void(* getVertCo)(DerivedMesh *dm, int index, float co_r[3])
void(* getVertCos)(DerivedMesh *dm, float(*cos_r)[3])
void(* getVertNo)(DerivedMesh *dm, int index, float no_r[3])
struct MeshElemMap *(* getPolyMap)(struct Object *ob, DerivedMesh *dm)
struct PBVH *(* getPBVH)(struct Object *ob, DerivedMesh *dm)
void(* drawVerts)(DerivedMesh *dm)
void(* drawUVEdges)(DerivedMesh *dm)
void(* drawEdges)(DerivedMesh *dm, int drawLooseEdges, int drawAllEdges)
void(* drawLooseEdges)(DerivedMesh *dm)
void(* drawFacesSolid)(DerivedMesh *dm, float(*partial_redraw_planes)[4], int fast, DMSetMaterial setMaterial)
void(* drawFacesTex)(DerivedMesh *dm, DMSetDrawOptionsTex setDrawOptions, DMCompareDrawOptions compareDrawOptions, void *userData)
void(* drawFacesGLSL)(DerivedMesh *dm, DMSetMaterial setMaterial)
void(* drawMappedFaces)(DerivedMesh *dm, DMSetDrawOptions setDrawOptions, DMSetMaterial setMaterial, DMCompareDrawOptions compareDrawOptions, void *userData, DMDrawFlag flag)
void(* drawMappedFacesTex)(DerivedMesh *dm, DMSetDrawOptions setDrawOptions, DMCompareDrawOptions compareDrawOptions, void *userData)
void(* drawMappedFacesGLSL)(DerivedMesh *dm, DMSetMaterial setMaterial, DMSetDrawOptions setDrawOptions, void *userData)
void(* drawMappedEdges)(DerivedMesh *dm, DMSetDrawOptions setDrawOptions, void *userData)
void(* drawMappedEdgesInterp)(DerivedMesh *dm, DMSetDrawOptions setDrawOptions, DMSetDrawInterpOptions setDrawInterpOptions, void *userData)
void(* drawMappedFacesMat)(DerivedMesh *dm, void(*setMaterial)(void *userData, int, void *attribs), int(*setFace)(void *userData, int index), void *userData)
void(* release)(DerivedMesh *dm)
Detailed Description
Definition at line 156 of file BKE_DerivedMesh.h.
Member Data Documentation
float DerivedMesh::auto_bump_scale
Definition at line 165 of file BKE_DerivedMesh.h.
Referenced by DM_calc_auto_bump_scale(), DM_init(), DM_vertex_attributes_from_gpu(), GPU_enable_material(), ntap_bump_compute(), and LOD_QuadricEditor::Update().
BVHCache DerivedMesh::bvhCache
Definition at line 162 of file BKE_DerivedMesh.h.
Referenced by bvhtree_from_mesh_edges(), bvhtree_from_mesh_faces(), bvhtree_from_mesh_verts(), DM_init_funcs(), and DM_release().
void(* DerivedMesh::calcNormals)(DerivedMesh *dm)
Definition at line 169 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), editbmesh_calc_modifiers(), getCCGDerivedMesh(), and getEditDerivedBMesh().
void(* DerivedMesh::copyEdgeArray)(DerivedMesh *dm, struct MEdge *edge_r)
Definition at line 207 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), dm_dupEdgeArray(), dm_getEdgeArray(), doMirrorOnAxis(), getCCGDerivedMesh(), and getEditDerivedBMesh().
void(* DerivedMesh::copyFromEdgeCData)(DerivedMesh *dm, int source, CustomData *dst, int dest)
Definition at line 247 of file BKE_DerivedMesh.h.
void(* DerivedMesh::copyFromFaceCData)(DerivedMesh *dm, int source, CustomData *dst, int dest)
Definition at line 248 of file BKE_DerivedMesh.h.
void(* DerivedMesh::copyFromVertCData)(DerivedMesh *dm, int source, CustomData *dst, int dest)
Definition at line 246 of file BKE_DerivedMesh.h.
void(* DerivedMesh::copyLoopArray)(DerivedMesh *dm, struct MLoop *loop_r)
Definition at line 209 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), dm_dupLoopArray(), dm_getLoopArray(), doMirrorOnAxis(), getCCGDerivedMesh(), and getEditDerivedBMesh().
void(* DerivedMesh::copyPolyArray)(DerivedMesh *dm, struct MPoly *poly_r)
Definition at line 210 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), dm_dupPolyArray(), dm_getPolyArray(), doMirrorOnAxis(), getCCGDerivedMesh(), and getEditDerivedBMesh().
void(* DerivedMesh::copyTessFaceArray)(DerivedMesh *dm, struct MFace *face_r)
Definition at line 208 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), dm_dupFaceArray(), dm_getTessFaceArray(), getCCGDerivedMesh(), and getEditDerivedBMesh().
void(* DerivedMesh::copyVertArray)(DerivedMesh *dm, struct MVert *vert_r)
Definition at line 206 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), dm_dupVertArray(), dm_getVertArray(), doMirrorOnAxis(), getCCGDerivedMesh(), and getEditDerivedBMesh().
int DerivedMesh::deformedOnly
Definition at line 161 of file BKE_DerivedMesh.h.
Referenced by brush_add(), cddm_copy_ex(), CDDM_from_BMEditMesh(), CDDM_from_curve_customDB(), CDDM_from_mesh(), connect_hair(), distribute_threads_init_data(), BL_ModifierDeformer::ProcessReplica(), psys_calc_dmcache(), psys_map_index_on_dm(), BL_ModifierDeformer::Update(), and BL_ModifierDeformer::~BL_ModifierDeformer().
DMDirtyFlag DerivedMesh::dirty
Definition at line 166 of file BKE_DerivedMesh.h.
Referenced by cddm_copy_ex(), DM_ensure_tessface(), DM_from_template(), DM_init(), DM_init_origspace(), DM_update_tessface_data(), DM_update_weight_mcol(), dynamicPaint_Modifier_apply(), getCCGDerivedMesh(), and uvprojectModifier_do().
void(* DerivedMesh::drawEdges)(DerivedMesh *dm, int drawLooseEdges, int drawAllEdges)
Definition at line 327 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), draw_em_fancy(), draw_mesh_fancy(), draw_mesh_object_outline(), draw_object_mesh_instance(), drawCurveDMWired(), getCCGDerivedMesh(), and getEditDerivedBMesh().
void(* DerivedMesh::drawFacesGLSL)(DerivedMesh *dm, DMSetMaterial setMaterial)
Definition at line 354 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), draw_mesh_fancy(), drawCurveDerivedMesh(), getCCGDerivedMesh(), getEditDerivedBMesh(), and RAS_OpenGLRasterizer::IndexPrimitivesInternal().
void(* DerivedMesh::drawFacesSolid)(DerivedMesh *dm, float(*partial_redraw_planes)[4], int fast, DMSetMaterial setMaterial)
Definition at line 339 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), draw_mesh_fancy(), draw_mesh_object_outline(), draw_object_mesh_instance(), drawCurveDerivedMesh(), and getCCGDerivedMesh().
void(* DerivedMesh::drawFacesTex)(DerivedMesh *dm, DMSetDrawOptionsTex setDrawOptions, DMCompareDrawOptions compareDrawOptions, void *userData)
Definition at line 345 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), draw_mesh_textured_old(), getCCGDerivedMesh(), getEditDerivedBMesh(), and RAS_OpenGLRasterizer::IndexPrimitivesInternal().
void(* DerivedMesh::drawLooseEdges)(DerivedMesh *dm)
Definition at line 330 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), draw_mesh_fancy(), and getCCGDerivedMesh().
void(* DerivedMesh::drawMappedEdges)(DerivedMesh *dm, DMSetDrawOptions setDrawOptions, void *userData)
Definition at line 398 of file BKE_DerivedMesh.h.
Referenced by bbs_mesh_wire(), cdDM_create(), draw_dm_bweights(), draw_dm_creases(), draw_dm_edges(), draw_dm_edges_seams(), draw_dm_edges_sel(), draw_dm_edges_sharp(), draw_mesh_face_select(), getCCGDerivedMesh(), and getEditDerivedBMesh().
void(* DerivedMesh::drawMappedEdgesInterp)(DerivedMesh *dm, DMSetDrawOptions setDrawOptions, DMSetDrawInterpOptions setDrawInterpOptions, void *userData)
Definition at line 409 of file BKE_DerivedMesh.h.
Referenced by draw_dm_edges_sel_interp(), draw_em_fancy_edges(), getCCGDerivedMesh(), and getEditDerivedBMesh().
void(* DerivedMesh::drawMappedFaces)(DerivedMesh *dm, DMSetDrawOptions setDrawOptions, DMSetMaterial setMaterial, DMCompareDrawOptions compareDrawOptions, void *userData, DMDrawFlag flag)
Definition at line 369 of file BKE_DerivedMesh.h.
Referenced by bbs_mesh_solid(), bbs_mesh_solid_EM(), cdDM_create(), draw_dm_faces_sel(), draw_em_fancy(), draw_mesh_face_select(), draw_mesh_fancy(), draw_mesh_textured(), draw_mesh_textured_old(), draw_object_backbufsel(), getCCGDerivedMesh(), and getEditDerivedBMesh().
void(* DerivedMesh::drawMappedFacesGLSL)(DerivedMesh *dm, DMSetMaterial setMaterial, DMSetDrawOptions setDrawOptions, void *userData)
Definition at line 389 of file BKE_DerivedMesh.h.
Referenced by ccgDM_drawFacesGLSL(), cdDM_create(), cdDM_drawFacesGLSL(), draw_em_fancy(), emDM_drawFacesGLSL(), getCCGDerivedMesh(), and getEditDerivedBMesh().
void(* DerivedMesh::drawMappedFacesMat)(DerivedMesh *dm, void(*setMaterial)(void *userData, int, void *attribs), int(*setFace)(void *userData, int index), void *userData)
Definition at line 418 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), draw_mesh_textured(), getCCGDerivedMesh(), and getEditDerivedBMesh().
void(* DerivedMesh::drawMappedFacesTex)(DerivedMesh *dm, DMSetDrawOptions setDrawOptions, DMCompareDrawOptions compareDrawOptions, void *userData)
Definition at line 379 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), draw_mesh_textured_old(), getCCGDerivedMesh(), and getEditDerivedBMesh().
struct GPUDrawObject* DerivedMesh::drawObject
Definition at line 163 of file BKE_DerivedMesh.h.
Referenced by cdDM_drawEdges(), cdDM_drawFacesSolid(), cdDM_drawFacesTex_common(), cdDM_drawLooseEdges(), cdDM_drawMappedFaces(), cdDM_drawMappedFacesGLSL(), cdDM_drawVerts(), gpu_buffer_color_type(), GPU_buffer_copy_edge(), GPU_buffer_copy_vertex(), GPU_buffer_legacy(), gpu_buffer_setup(), gpu_buffer_setup_common(), gpu_buffer_setup_type(), gpu_buffer_size_from_type(), GPU_color3_upload(), GPU_color_setup(), GPU_drawobject_free(), GPU_edge_setup(), GPU_normal_setup(), GPU_uv_setup(), GPU_uvedge_setup(), and GPU_vertex_setup().
void(* DerivedMesh::drawUVEdges)(DerivedMesh *dm)
Definition at line 321 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), draw_uvs_dm_shadow(), getCCGDerivedMesh(), and getEditDerivedBMesh().
void(* DerivedMesh::drawVerts)(DerivedMesh *dm)
Definition at line 318 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), draw_mesh_fancy(), and getCCGDerivedMesh().
struct MEdge*(* DerivedMesh::dupEdgeArray)(DerivedMesh *dm) [read]
Definition at line 216 of file BKE_DerivedMesh.h.
Referenced by cddm_copy_ex(), DM_init_funcs(), DM_to_bmesh_ex(), and DM_to_mesh().
struct MLoop*(* DerivedMesh::dupLoopArray)(DerivedMesh *dm) [read]
Definition at line 218 of file BKE_DerivedMesh.h.
Referenced by DM_DupPolys(), DM_init_funcs(), and DM_to_mesh().
struct MPoly*(* DerivedMesh::dupPolyArray)(DerivedMesh *dm) [read]
Definition at line 219 of file BKE_DerivedMesh.h.
Referenced by DM_DupPolys(), DM_init_funcs(), and DM_to_mesh().
struct MFace*(* DerivedMesh::dupTessFaceArray)(DerivedMesh *dm) [read]
Definition at line 217 of file BKE_DerivedMesh.h.
Referenced by cddm_copy_ex(), deformVerts(), and DM_init_funcs().
struct MVert*(* DerivedMesh::dupVertArray)(DerivedMesh *dm) [read]
Definition at line 215 of file BKE_DerivedMesh.h.
Referenced by cddm_copy_ex(), deformVerts(), DM_init_funcs(), DM_to_bmesh_ex(), and DM_to_mesh().
CustomData DerivedMesh::edgeData
Definition at line 158 of file BKE_DerivedMesh.h.
Referenced by CDDM_calc_edges(), CDDM_calc_edges_tessface(), cddm_copy_ex(), CDDM_from_BMEditMesh(), CDDM_from_mesh(), CDDM_from_template(), CDDM_lower_num_edges(), CDDM_merge_verts(), CDDM_new(), CDDM_set_medge(), DM_add_edge_layer(), DM_copy_edge_data(), DM_free_edge_data(), DM_from_template(), DM_get_edge_data(), DM_get_edge_data_layer(), dm_getEdgeArray(), dm_getEdgeCData(), DM_interp_edge_data(), DM_release(), DM_set_edge_data(), DM_set_only_copy(), DM_to_bmesh_ex(), DM_to_mesh(), doMirrorOnAxis(), and getCCGDerivedMesh().
CustomData DerivedMesh::faceData
Definition at line 158 of file BKE_DerivedMesh.h.
Referenced by add_tface_color_layer(), apply_heights_callback(), apply_tangmat_callback(), BL_ConvertMesh(), bmDm_getTessFaceDataLayout(), CDDM_calc_normals_mapping_ex(), CDDM_calc_normals_tessface(), cddm_copy_ex(), cdDM_drawFacesSolid(), CDDM_from_BMEditMesh(), CDDM_from_mesh(), CDDM_from_template(), CDDM_lower_num_tessfaces(), CDDM_new(), CDDM_recalc_tessellation_ex(), CDDM_set_mface(), CDDM_tessfaces_to_faces(), cdDM_update_normals_from_pbvh(), ConvertCSGDescriptorsToDerivedMesh(), count_images(), cutEdges(), DM_add_tangent_layer(), DM_add_tessface_layer(), DM_copy_tessface_data(), DM_ensure_tessface(), DM_free_tessface_data(), DM_from_template(), DM_get_tessface_data(), DM_get_tessface_data_layer(), dm_getTessFaceArray(), dm_getTessFaceCData(), DM_interp_tessface_data(), DM_release(), DM_set_only_copy(), DM_set_tessface_data(), DM_swap_tessface_data(), DM_update_weight_mcol(), do_multires_bake(), draw_mesh_textured_old(), dynamicPaint_createUVSurface(), dynamicPaint_findNeighbourPixel(), dynamicPaint_Modifier_apply(), emDM_getTessFaceDataArray(), explodeMesh(), get_particle_uv(), get_particle_uvco_mcol(), getCCGDerivedMesh(), init_render_dm(), init_render_mesh(), InterpCSGFace(), multiresbake_startjob(), paintface_flush_flags(), project_paint_begin(), psys_get_dupli_texture(), psys_particle_on_dm(), RE_inithalo_particle(), RE_sample_material_color(), remap_uvs_15(), remap_uvs_19_21_22(), remap_uvs_23(), remap_uvs_3_6_9_12(), remap_uvs_5_10(), remap_uvs_7_11_13_14(), render_new_particle_system(), set_subsurf_uv(), texture_paint_init(), CcdShapeConstructionInfo::UpdateMesh(), use_mesh_edge_lookup(), vertex_paint_use_fast_update_check(), and vertex_paint_use_tessface_check().
void(* DerivedMesh::foreachMappedEdge)(DerivedMesh *dm, void(*func)(void *userData, int index,const float v0co[3], const float v1co[3]), void *userData)
Definition at line 274 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), getCCGDerivedMesh(), getEditDerivedBMesh(), and mesh_foreachScreenEdge().
void(* DerivedMesh::foreachMappedFaceCenter)(DerivedMesh *dm, void(*func)(void *userData, int index,const float cent[3], const float no[3]), void *userData)
Definition at line 283 of file BKE_DerivedMesh.h.
Referenced by bbs_mesh_solid_EM(), cdDM_create(), draw_dm_face_centers(), draw_dm_face_normals(), getCCGDerivedMesh(), getEditDerivedBMesh(), and mesh_foreachScreenFace().
void(* DerivedMesh::foreachMappedVert)(DerivedMesh *dm, void(*func)(void *userData, int index, const float co[3],const float no_f[3], const short no_s[3]), void *userData)
Definition at line 265 of file BKE_DerivedMesh.h.
Referenced by add_verts_to_dgroups(), bbs_mesh_verts(), bbs_obmode_mesh_verts(), BMBVH_NewBVH(), cdDM_create(), crazyspace_get_mapped_editverts(), draw_dm_bweights(), draw_dm_vert_normals(), draw_dm_verts(), drawSelectedVertices(), getCCGDerivedMesh(), getEditDerivedBMesh(), knifetool_init(), make_trans_verts(), mesh_foreachScreenVert(), mesh_get_mapped_verts_nors(), and vertex_duplilist().
void(* DerivedMesh::getEdge)(DerivedMesh *dm, int index, struct MEdge *edge_r)
Definition at line 189 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), cdDM_create(), getCCGDerivedMesh(), and getEditDerivedBMesh().
struct MEdge*(* DerivedMesh::getEdgeArray)(DerivedMesh *dm) [read]
Definition at line 198 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), BKE_mesh_validate_dm(), ccgDM_copyFinalLoopArray(), cloth_build_springs(), construct_param_handle_subsurfed(), DM_get_edge_data_layer(), DM_init_funcs(), dynamicPaint_initAdjacencyData(), getCCGDerivedMesh(), GPU_buffer_copy_edge(), init_render_mesh(), mesh_to_curve(), smoothModifier_do(), snapDerivedMesh(), and ss_sync_from_derivedmesh().
void*(* DerivedMesh::getEdgeData)(DerivedMesh *dm, int index, int type)
Definition at line 226 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), DM_init_funcs(), and getCCGDerivedMesh().
void*(* DerivedMesh::getEdgeDataArray)(DerivedMesh *dm, int type)
Definition at line 234 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), bvhtree_from_mesh_edges(), cddm_copy_ex(), cdDM_create(), CDDM_from_BMEditMesh(), CDDM_from_template(), construct_param_handle_subsurfed(), DM_init_funcs(), getCCGDerivedMesh(), snapDerivedMesh(), and ss_sync_from_derivedmesh().
CustomData*(* DerivedMesh::getEdgeDataLayout)(DerivedMesh *dm)
Definition at line 240 of file BKE_DerivedMesh.h.
Referenced by DM_init_funcs(), and getEditDerivedBMesh().
DMGridAdjacency*(* DerivedMesh::getGridAdjacency)(DerivedMesh *dm)
Definition at line 254 of file BKE_DerivedMesh.h.
Referenced by getCCGDerivedMesh().
DMGridData**(* DerivedMesh::getGridData)(DerivedMesh *dm)
Definition at line 253 of file BKE_DerivedMesh.h.
Referenced by get_ccgdm_data(), getCCGDerivedMesh(), multires_apply_smat(), multires_dm_create_from_derived(), multires_modifier_update_mdisps(), multires_set_space(), multires_subdivide(), multiresModifier_base_apply(), multiresModifier_disp_run(), sculpt_undo_restore(), sculpt_undo_restore_coords(), and sculpt_undo_restore_hidden().
DMFlagMat*(* DerivedMesh::getGridFlagMats)(DerivedMesh *dm)
Definition at line 256 of file BKE_DerivedMesh.h.
Referenced by getCCGDerivedMesh().
unsigned int**(* DerivedMesh::getGridHidden)(DerivedMesh *dm)
Definition at line 257 of file BKE_DerivedMesh.h.
Referenced by getCCGDerivedMesh(), and sculpt_undo_restore_hidden().
int*(* DerivedMesh::getGridOffset)(DerivedMesh *dm)
Definition at line 255 of file BKE_DerivedMesh.h.
Referenced by get_ccgdm_data(), getCCGDerivedMesh(), multires_apply_smat(), multires_output_hidden_to_ccgdm(), multires_set_space(), and multiresModifier_disp_run().
int(* DerivedMesh::getGridSize)(DerivedMesh *dm)
Definition at line 252 of file BKE_DerivedMesh.h.
Referenced by get_ccgdm_data(), getCCGDerivedMesh(), multires_apply_smat(), multires_dm_create_from_derived(), multires_modifier_update_mdisps(), multires_set_space(), multires_subdivide(), multiresModifier_disp_run(), sculpt_undo_restore(), and sculpt_undo_restore_coords().
struct MLoop*(* DerivedMesh::getLoopArray)(DerivedMesh *dm) [read]
Definition at line 200 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), BKE_mesh_validate_dm(), dm_calc_normal(), DM_init_funcs(), DM_to_bmesh_ex(), DM_update_tessface_data(), DM_update_weight_mcol(), dynamicPaint_initAdjacencyData(), face_duplilist(), get_texture_coords(), ss_sync_from_derivedmesh(), ss_sync_from_uv(), and uvprojectModifier_do().
CustomData*(* DerivedMesh::getLoopDataLayout)(DerivedMesh *dm)
Definition at line 242 of file BKE_DerivedMesh.h.
Referenced by DM_init_funcs(), DM_update_tessface_data(), DM_update_weight_mcol(), DM_vertex_attributes_from_gpu(), and getEditDerivedBMesh().
void(* DerivedMesh::getMinMax)(DerivedMesh *dm, float min_r[3], float max_r[3])
Definition at line 292 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), CDDM_Check(), cdDM_create(), DM_set_object_boundbox(), getCCGDerivedMesh(), getEditDerivedBMesh(), my_get_local_bounds(), and BL_ModifierDeformer::Update().
int(* DerivedMesh::getNumEdges)(DerivedMesh *dm)
Definition at line 178 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), BKE_mesh_validate_dm(), bvhtree_from_mesh_edges(), cdDM_create(), cloth_build_springs(), construct_param_handle_subsurfed(), deformVerts(), dm_calc_normal(), dm_dupEdgeArray(), dm_getEdgeArray(), DM_to_bmesh_ex(), DM_to_mesh(), do_hair_dynamics(), doMirrorOnAxis(), draw_mesh_fancy(), dynamicPaint_initAdjacencyData(), getCCGDerivedMesh(), getEditDerivedBMesh(), GPU_buffer_copy_edge(), GPU_drawobject_new(), init_render_mesh(), mesh_to_curve(), smoothModifier_do(), snapDerivedMesh(), ss_sync_from_derivedmesh(), and stats_object().
int(* DerivedMesh::getNumGrids)(DerivedMesh *dm)
Definition at line 251 of file BKE_DerivedMesh.h.
Referenced by ccgDM_release(), getCCGDerivedMesh(), multires_dm_create_from_derived(), multires_modifier_update_mdisps(), multires_subdivide(), and sculpt_undo_restore().
int(* DerivedMesh::getNumLoops)(DerivedMesh *dm)
Definition at line 180 of file BKE_DerivedMesh.h.
Referenced by BKE_mesh_validate_dm(), cdDM_create(), dm_dupLoopArray(), dm_getLoopArray(), DM_to_mesh(), doMirrorOnAxis(), getCCGDerivedMesh(), getEditDerivedBMesh(), and uvprojectModifier_do().
int(* DerivedMesh::getNumPolys)(DerivedMesh *dm)
Definition at line 181 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), BKE_mesh_validate_dm(), bvhtree_from_mesh_faces(), cdDM_create(), dm_calc_normal(), dm_dupPolyArray(), DM_ensure_tessface(), dm_getPolyArray(), DM_init_origspace(), DM_to_mesh(), doMirrorOnAxis(), dynamicPaint_initAdjacencyData(), face_duplilist(), get_texture_coords(), getCCGDerivedMesh(), getEditDerivedBMesh(), paintface_flush_flags(), sculpt_update_mesh_elements(), ss_sync_from_uv(), stats_object(), and uvprojectModifier_do().
int(* DerivedMesh::getNumTessFaces)(DerivedMesh *dm)
Definition at line 179 of file BKE_DerivedMesh.h.
Referenced by add_tface_color_layer(), applyModifier(), BL_ConvertMesh(), buildRawVertIndicesData(), bvhtree_from_mesh_faces(), cache_strand_surface(), cdDM_create(), cdDM_drawFacesTex_common(), cloth_build_springs(), cloth_from_mesh(), construct_param_handle_subsurfed(), ConvertCSGDescriptorsToDerivedMesh(), count_images(), createFacepa(), createVertsTrisData(), cutEdges(), deformVerts(), distribute_grid(), distribute_threads_exec(), distribute_threads_init_data(), DM_add_tangent_layer(), DM_calc_auto_bump_scale(), dm_dupFaceArray(), DM_ensure_tessface(), dm_getTessFaceArray(), DM_update_tessface_data(), DM_update_weight_mcol(), do_multires_bake(), draw_mesh_fancy(), drawCurveDerivedMesh(), drawObjectSelect(), dynamicPaint_createUVSurface(), dynamicPaint_findNeighbourPixel(), dynamicPaint_Modifier_apply(), explodeMesh(), FaceIt_Construct(), FaceIt_Done(), get_particle_uv(), getCCGDerivedMesh(), getEditDerivedBMesh(), GPU_buffer_copy_color3(), GPU_buffer_copy_mcol(), GPU_buffer_copy_normal(), GPU_buffer_copy_uv(), GPU_buffer_copy_vertex(), GPU_drawobject_new(), imapaint_pick_uv(), init_render_dm(), init_render_mesh(), initElbeemMesh(), make_mesh_edge_lookup(), mesh_to_curve(), meshdeform_intersect(), multiresbake_startjob(), NewBooleanDerivedMesh_intern(), NewBooleanMesh(), paintface_flush_flags(), particle_intersect_dm(), peelDerivedMesh(), project_paint_begin(), psys_calc_dmcache(), psys_face_mat(), psys_get_dupli_texture(), psys_map_index_on_dm(), psys_particle_dm_face_lookup(), psys_render_simplify_distribution(), recalc_emitter_field(), render_new_particle_system(), CcdShapeConstructionInfo::SetMesh(), snapDerivedMesh(), texture_paint_init(), and CcdShapeConstructionInfo::UpdateMesh().
int(* DerivedMesh::getNumVerts)(DerivedMesh *dm)
Definition at line 177 of file BKE_DerivedMesh.h.
Referenced by add_orco_dm(), add_shapekey_layers(), applyModifier(), arrayModifier_doArray(), BKE_mesh_validate_dm(), BKE_object_foreach_display_point(), BL_ConvertMesh(), buildRawVertIndicesData(), bvhtree_from_mesh_verts(), cache_strand_surface(), calc_weightpaint_vert_array(), cdDM_create(), cdDM_getPBVH(), cloth_apply_vgroup(), cloth_build_springs(), cloth_from_mesh(), cloth_from_object(), clothModifier_do(), connect_hair(), contarget_get_mesh_mat(), createFacepa(), createVertsTrisData(), curve_calc_modifiers_post(), cutEdges(), deformVerts(), distribute_grid(), distribute_threads_init_data(), DM_add_tangent_layer(), dm_calc_normal(), dm_dupVertArray(), dm_getVertArray(), DM_to_bmesh_ex(), DM_to_mesh(), DM_to_meshkey(), DM_update_weight_mcol(), do_hair_dynamics(), doMirrorOnAxis(), dynamicPaint_brushMeshCalculateVelocity(), dynamicPaint_generateBakeData(), dynamicPaint_paintMesh(), dynamicPaint_surfaceHasMoved(), dynamicPaint_surfaceNumOfPoints(), editbmesh_calc_modifiers(), explodeMesh(), getCCGDerivedMesh(), getEditDerivedBMesh(), give_parvert(), GPU_drawobject_new(), init_render_dm(), init_render_mesh(), initElbeemMesh(), mesh_calc_modifiers(), mesh_deform_bind(), multires_load_old_dm(), multiresModifier_base_apply(), multiresModifier_reshapeFromDeformMod(), multiresModifier_reshapeFromDM(), paintvert_flush_flags(), peelDerivedMesh(), pointdensity_cache_object(), project_paint_begin(), psys_cache_vgroup(), psys_calc_dmcache(), psys_map_index_on_dm(), sculpt_update_mesh_elements(), CcdShapeConstructionInfo::SetMesh(), shrinkwrapModifier_deform(), snapDerivedMesh(), ss_sync_from_derivedmesh(), ss_sync_from_uv(), stats_object(), CcdShapeConstructionInfo::UpdateMesh(), uvprojectModifier_do(), vertex_duplilist(), VertexIt_Construct(), and VertexIt_Done().
struct PBVH*(* DerivedMesh::getPBVH)(struct Object *ob, DerivedMesh *dm) [read]
Definition at line 313 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), free_sculptsession(), getCCGDerivedMesh(), hide_show_exec(), mesh_build_data(), and sculpt_update_mesh_elements().
struct MPoly*(* DerivedMesh::getPolyArray)(DerivedMesh *dm) [read]
Definition at line 201 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), BKE_mesh_validate_dm(), dm_calc_normal(), DM_init_funcs(), DM_init_origspace(), DM_to_bmesh_ex(), DM_update_tessface_data(), DM_update_weight_mcol(), dynamicPaint_initAdjacencyData(), face_duplilist(), get_texture_coords(), paintface_flush_flags(), psys_particle_dm_face_lookup(), ss_sync_from_derivedmesh(), ss_sync_from_uv(), and uvprojectModifier_do().
CustomData*(* DerivedMesh::getPolyDataLayout)(DerivedMesh *dm)
Definition at line 243 of file BKE_DerivedMesh.h.
Referenced by KX_NavMeshObject::BuildVertIndArrays(), DM_init_funcs(), DM_update_tessface_data(), and getEditDerivedBMesh().
struct MeshElemMap*(* DerivedMesh::getPolyMap)(struct Object *ob, DerivedMesh *dm) [read]
Definition at line 309 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), getCCGDerivedMesh(), multiresModifier_base_apply(), and sculpt_update_mesh_elements().
void(* DerivedMesh::getTessFace)(DerivedMesh *dm, int index, struct MFace *face_r)
Definition at line 190 of file BKE_DerivedMesh.h.
Referenced by apply_heights_callback(), apply_tangmat_callback(), cdDM_create(), explodeMesh(), get_ccgdm_data(), getCCGDerivedMesh(), getEditDerivedBMesh(), GPU_buffer_copy_uvedge(), and imapaint_pick_uv().
struct MFace*(* DerivedMesh::getTessFaceArray)(DerivedMesh *dm) [read]
Definition at line 199 of file BKE_DerivedMesh.h.
Referenced by add_tface_color_layer(), applyModifier(), BL_ConvertMesh(), buildRawVertIndicesData(), cache_strand_surface(), ccgDM_drawUVEdges(), cloth_build_springs(), cloth_from_mesh(), construct_param_handle_subsurfed(), createFacepa(), createVertsTrisData(), cutEdges(), DM_add_tangent_layer(), DM_calc_auto_bump_scale(), DM_get_tessface_data_layer(), DM_init_funcs(), DM_update_tessface_data(), DM_update_weight_mcol(), do_multires_bake(), dynamicPaint_createUVSurface(), dynamicPaint_doMaterialTex(), dynamicPaint_findNeighbourPixel(), dynamicPaint_paintMesh(), explodeMesh(), FaceIt_Fill(), GPU_buffer_copy_color3(), GPU_buffer_copy_mcol(), GPU_buffer_copy_normal(), GPU_buffer_copy_uv(), GPU_buffer_copy_vertex(), GPU_drawobject_new(), init_render_dm(), init_render_mesh(), initElbeemMesh(), InterpCSGFace(), make_mesh_edge_lookup(), mesh_to_curve(), meshdeform_intersect(), paintface_flush_flags(), peelDerivedMesh(), project_paint_begin(), psys_render_simplify_distribution(), RE_sample_material_color(), CcdShapeConstructionInfo::SetMesh(), snapDerivedMesh(), texture_paint_init(), and CcdShapeConstructionInfo::UpdateMesh().
void*(* DerivedMesh::getTessFaceData)(DerivedMesh *dm, int index, int type)
Definition at line 227 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), cutEdges(), distribute_threads_exec(), distribute_threads_init_data(), DM_init_funcs(), get_particle_uv(), get_particle_uvco_mcol(), getCCGDerivedMesh(), psys_face_mat(), psys_get_dupli_texture(), psys_interpolate_value_from_verts(), psys_map_index_on_dm(), psys_particle_on_dm(), and recalc_emitter_field().
void*(* DerivedMesh::getTessFaceDataArray)(DerivedMesh *dm, int type)
Definition at line 235 of file BKE_DerivedMesh.h.
Referenced by add_tface_color_layer(), BL_ConvertMesh(), bvhtree_from_mesh_faces(), bvhtree_from_mesh_verts(), ccgDM_drawFacesTex_common(), ccgDM_drawMappedFaces(), cddm_copy_ex(), cdDM_create(), cdDM_drawFacesSolid(), cdDM_drawFacesTex_common(), cdDM_drawMappedFacesGLSL(), cdDM_drawMappedFacesMat(), CDDM_from_BMEditMesh(), CDDM_from_template(), construct_param_handle_subsurfed(), ConvertCSGDescriptorsToDerivedMesh(), distribute_grid(), distribute_threads_exec(), distribute_threads_init_data(), DM_add_tangent_layer(), DM_calc_auto_bump_scale(), DM_init_funcs(), DM_update_weight_mcol(), do_multires_bake(), dynamicPaint_Modifier_apply(), getCCGDerivedMesh(), getEditDerivedBMesh(), GPU_buffer_copy_normal(), imapaint_pick_uv(), init_heights_data(), init_normal_data(), make_mesh_edge_lookup(), particle_intersect_dm(), project_paint_begin(), psys_calc_dmcache(), psys_map_index_on_dm(), psys_particle_dm_face_lookup(), psys_render_simplify_distribution(), render_new_particle_system(), CcdShapeConstructionInfo::SetMesh(), snapDerivedMesh(), texture_paint_init(), and CcdShapeConstructionInfo::UpdateMesh().
CustomData*(* DerivedMesh::getTessFaceDataLayout)(DerivedMesh *dm)
Definition at line 241 of file BKE_DerivedMesh.h.
Referenced by DM_init_funcs(), DM_update_tessface_data(), DM_vertex_attributes_from_gpu(), and getEditDerivedBMesh().
void(* DerivedMesh::getVert)(DerivedMesh *dm, int index, struct MVert *vert_r)
Definition at line 188 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), cdDM_create(), cutEdges(), explodeMesh(), getCCGDerivedMesh(), getEditDerivedBMesh(), imapaint_pick_uv(), moveCloserToDistanceFromPlane(), and vgroup_fix().
struct MVert*(* DerivedMesh::getVertArray)(DerivedMesh *dm) [read]
Definition at line 197 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), arrayModifier_doArray(), BKE_mesh_validate_dm(), BKE_object_foreach_display_point(), BL_ConvertMesh(), cache_strand_surface(), cloth_from_object(), construct_param_handle_subsurfed(), createFacepa(), createVertsTrisData(), deformVerts(), DM_add_tangent_layer(), DM_calc_auto_bump_scale(), dm_calc_normal(), DM_get_vert_data_layer(), DM_init_funcs(), do_multires_bake(), do_step_cloth(), dynamicPaint_applySurfaceDisplace(), dynamicPaint_brushMeshCalculateVelocity(), dynamicPaint_generateBakeData(), dynamicPaint_Modifier_apply(), dynamicPaint_paintMesh(), dynamicPaint_paintSinglePoint(), dynamicPaint_surfaceHasMoved(), face_duplilist(), give_parvert(), GPU_buffer_copy_normal(), GPU_buffer_copy_vertex(), init_render_dm(), init_render_mesh(), initElbeemMesh(), InterpCSGFace(), mesh_deform_bind(), mesh_to_curve(), multires_load_old_dm(), multiresModifier_reshapeFromDM(), paintvert_flush_flags(), peelDerivedMesh(), pointdensity_cache_object(), project_paint_begin(), psys_render_simplify_distribution(), RE_sample_material_color(), CcdShapeConstructionInfo::SetMesh(), shapekey_layers_to_keyblocks(), snapDerivedMesh(), ss_sync_from_derivedmesh(), ss_sync_from_uv(), CcdShapeConstructionInfo::UpdateMesh(), VertexIt_Fill(), and waveModifier_do().
void(* DerivedMesh::getVertCo)(DerivedMesh *dm, int index, float co_r[3])
Definition at line 299 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), contarget_get_mesh_mat(), draw_mesh_text(), get_effector_data(), getCCGDerivedMesh(), give_parvert(), interp_barycentric_mface(), interp_bilinear_mface(), mesh_get_mapped_verts_nors(), multiresModifier_base_apply(), psys_face_mat(), psys_particle_on_dm(), vertex_duplilist(), and weight_sample_invoke().
void(* DerivedMesh::getVertCos)(DerivedMesh *dm, float(*cos_r)[3])
Definition at line 302 of file BKE_DerivedMesh.h.
Referenced by add_orco_dm(), applyModifier(), buildRawVertIndicesData(), cdDM_create(), cdDM_getPBVH(), curve_calc_modifiers_post(), deformVerts(), do_hair_dynamics(), editbmesh_calc_modifiers(), getCCGDerivedMesh(), getEditDerivedBMesh(), mesh_calc_modifiers(), multiresModifier_reshapeFromDeformMod(), uvprojectModifier_do(), and weightvg_do_mask().
void*(* DerivedMesh::getVertData)(DerivedMesh *dm, int index, int type)
Definition at line 225 of file BKE_DerivedMesh.h.
Referenced by armature_deform_verts(), cdDM_create(), cloth_apply_vgroup(), curve_deform_verts(), distribute_threads_init_data(), DM_init_funcs(), getCCGDerivedMesh(), lattice_deform_verts(), and recalc_emitter_field().
void*(* DerivedMesh::getVertDataArray)(DerivedMesh *dm, int type)
Definition at line 233 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), BKE_mesh_validate_dm(), bvhtree_from_mesh_edges(), bvhtree_from_mesh_faces(), bvhtree_from_mesh_verts(), cddm_copy_ex(), cdDM_create(), CDDM_from_BMEditMesh(), CDDM_from_template(), cloth_from_object(), construct_param_handle_subsurfed(), contarget_get_mesh_mat(), createFacepa(), deformVerts_do(), distribute_grid(), distribute_threads_exec(), distribute_threads_init_data(), DM_add_tangent_layer(), DM_init_funcs(), DM_to_meshkey(), dynamicPaint_Modifier_apply(), getCCGDerivedMesh(), give_parvert(), init_render_mesh(), makeOrcoDispList(), modifier_get_vgroup(), paintvert_flush_flags(), particle_intersect_dm(), psys_cache_vgroup(), psys_calc_dmcache(), psys_face_mat(), psys_particle_on_dm(), shrinkwrapModifier_deform(), snapDerivedMesh(), ss_sync_from_derivedmesh(), and weightvg_do_mask().
CustomData*(* DerivedMesh::getVertDataLayout)(DerivedMesh *dm)
Definition at line 239 of file BKE_DerivedMesh.h.
Referenced by DM_init_funcs(), and getEditDerivedBMesh().
void(* DerivedMesh::getVertNo)(DerivedMesh *dm, int index, float no_r[3])
Definition at line 305 of file BKE_DerivedMesh.h.
Referenced by cdDM_create(), contarget_get_mesh_mat(), get_effector_data(), getCCGDerivedMesh(), interp_barycentric_mface(), interp_bilinear_mface(), mesh_get_mapped_verts_nors(), psys_particle_on_dm(), and vertex_duplilist().
CustomData DerivedMesh::loopData
Definition at line 158 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), bm_mdisps_space_set(), cddm_copy_ex(), CDDM_from_BMEditMesh(), CDDM_from_mesh(), CDDM_from_template(), CDDM_merge_verts(), CDDM_new(), CDDM_recalc_tessellation_ex(), CDDM_set_mloop(), CDDM_tessfaces_to_faces(), DM_add_loop_layer(), DM_copy_loop_data(), DM_DupPolys(), DM_free_loop_data(), DM_from_template(), DM_get_loop_data_layer(), dm_getLoopArray(), dm_getLoopCData(), DM_init_origspace(), DM_interp_loop_data(), DM_release(), DM_to_bmesh_ex(), DM_to_mesh(), DM_update_weight_mcol(), doMirrorOnAxis(), draw_uvs_dm_shadow(), dynamicPaint_Modifier_apply(), editbmesh_calc_modifiers(), get_texture_coords(), getCCGDerivedMesh(), mesh_calc_modifiers(), multires_set_space(), multiresModifier_disp_run(), set_subsurf_uv(), and uvprojectModifier_do().
int DerivedMesh::needsFree
Definition at line 160 of file BKE_DerivedMesh.h.
Referenced by BL_CreatePhysicsObjectNew(), bm_mdisps_space_set(), BMEdit_Free(), CDDM_merge_verts(), clear_mesh_caches(), deformVerts(), dm_deform_clear(), DM_from_template(), DM_init(), DM_release(), EDBM_mesh_clear(), editbmesh_build_data(), freeData(), mesh_build_data(), mesh_to_curve(), multires_force_update(), multires_set_space(), object_free_display(), psys_render_restore(), BL_ModifierDeformer::Update(), CcdShapeConstructionInfo::UpdateMesh(), and BL_ModifierDeformer::~BL_ModifierDeformer().
int DerivedMesh::numEdgeData
Definition at line 159 of file BKE_DerivedMesh.h.
Referenced by ccgDM_copyFinalLoopArray(), ccgDM_get_edge_data_layer(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), cddm_copy_ex(), cdDM_copyEdgeArray(), cdDM_drawEdges(), cdDM_drawLooseEdges(), cdDM_drawMappedEdges(), cdDM_foreachMappedEdge(), CDDM_from_BMEditMesh(), cdDM_getNumEdges(), CDDM_lower_num_edges(), CDDM_merge_verts(), CDDM_set_medge(), CDDM_tessfaces_to_faces(), DM_add_edge_layer(), DM_from_template(), DM_init(), DM_release(), getCCGDerivedMesh(), and mesh_calc_modifiers().
int DerivedMesh::numLoopData
Definition at line 159 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), CDDM_calc_normals(), CDDM_calc_normals_mapping_ex(), cddm_copy_ex(), cdDM_copyLoopArray(), CDDM_from_BMEditMesh(), cdDM_getNumLoops(), CDDM_merge_verts(), CDDM_recalc_tessellation_ex(), CDDM_set_mloop(), CDDM_tessfaces_to_faces(), DM_add_loop_layer(), DM_DupPolys(), DM_from_template(), DM_init(), DM_release(), dynamicPaint_Modifier_apply(), getCCGDerivedMesh(), and multiresModifier_disp_run().
int DerivedMesh::numPolyData
Definition at line 159 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), CDDM_calc_edges(), CDDM_calc_normals(), CDDM_calc_normals_mapping_ex(), cddm_copy_ex(), cdDM_copyPolyArray(), cdDM_foreachMappedFaceCenter(), CDDM_from_BMEditMesh(), cdDM_getNumPolys(), cdDM_getNumTessFaces(), CDDM_lower_num_polys(), CDDM_merge_verts(), CDDM_recalc_tessellation_ex(), CDDM_set_mpoly(), CDDM_tessfaces_to_faces(), DM_add_poly_layer(), DM_DupPolys(), DM_from_template(), DM_init(), DM_release(), DM_to_bmesh_ex(), DM_update_weight_mcol(), dynamicPaint_Modifier_apply(), getCCGDerivedMesh(), mesh_calc_modifiers(), multires_set_space(), multiresModifier_disp_run(), and ss_sync_from_derivedmesh().
int DerivedMesh::numTessFaceData
Definition at line 159 of file BKE_DerivedMesh.h.
Referenced by add_tface_color_layer(), ccgDM_drawFacesSolid(), ccgDM_drawUVEdges(), ccgDM_getFinalFace(), CDDM_calc_edges_tessface(), CDDM_calc_normals_mapping_ex(), CDDM_calc_normals_tessface(), cddm_copy_ex(), cdDM_copyTessFaceArray(), cdDM_drawFacesSolid(), cdDM_drawFacesTex_common(), cdDM_drawMappedFaces(), cdDM_drawMappedFacesGLSL(), cdDM_drawMappedFacesMat(), cdDM_drawUVEdges(), CDDM_from_BMEditMesh(), cdDM_getNumTessFaces(), CDDM_lower_num_tessfaces(), CDDM_recalc_tessellation_ex(), CDDM_set_mface(), CDDM_tessfaces_to_faces(), cdDM_update_normals_from_pbvh(), ConvertCSGDescriptorsToDerivedMesh(), distribute_threads_init_data(), DM_add_tessface_layer(), DM_from_template(), DM_init(), DM_release(), getCCGDerivedMesh(), and GPU_buffer_copy_uvedge().
int DerivedMesh::numVertData
Definition at line 159 of file BKE_DerivedMesh.h.
Referenced by add_shapekey_layers(), ccgDM_get_vert_data_layer(), CDDM_apply_vert_coords(), CDDM_apply_vert_normals(), CDDM_calc_normals(), CDDM_calc_normals_mapping_ex(), CDDM_calc_normals_tessface(), cddm_copy_ex(), cdDM_copyVertArray(), cdDM_drawVerts(), cdDM_foreachMappedVert(), CDDM_from_BMEditMesh(), cdDM_getMinMax(), cdDM_getNumVerts(), cdDM_getVertCos(), CDDM_lower_num_verts(), CDDM_merge_verts(), CDDM_set_mvert(), distribute_threads_init_data(), DM_add_vert_layer(), DM_from_template(), DM_init(), DM_release(), doMirrorOnAxis(), get_effector_tot(), getCCGDerivedMesh(), mesh_calc_modifiers(), and shapekey_layers_to_keyblocks().
CustomData DerivedMesh::polyData
Definition at line 158 of file BKE_DerivedMesh.h.
Referenced by applyModifier(), buildRawVertIndicesData(), CDDM_calc_normals(), cddm_copy_ex(), cdDM_foreachMappedFaceCenter(), CDDM_from_BMEditMesh(), CDDM_from_mesh(), CDDM_from_template(), CDDM_lower_num_polys(), CDDM_merge_verts(), CDDM_new(), CDDM_recalc_tessellation_ex(), CDDM_set_mpoly(), CDDM_tessfaces_to_faces(), DM_add_poly_layer(), dm_calc_normal(), DM_copy_poly_data(), DM_DupPolys(), DM_free_poly_data(), DM_from_template(), DM_get_poly_data_layer(), dm_getPolyArray(), dm_getPolyCData(), DM_interp_poly_data(), DM_release(), DM_to_bmesh_ex(), DM_to_mesh(), doMirrorOnAxis(), getCCGDerivedMesh(), multires_set_space(), multiresModifier_disp_run(), paintface_flush_flags(), and uvprojectModifier_do().
void(* DerivedMesh::recalcTessellation)(DerivedMesh *dm)
Definition at line 172 of file BKE_DerivedMesh.h.
Referenced by BMEdit_RecalcTessellation(), cdDM_create(), DM_ensure_tessface(), getCCGDerivedMesh(), and getEditDerivedBMesh().
void(* DerivedMesh::release)(DerivedMesh *dm)
Definition at line 424 of file BKE_DerivedMesh.h.
Referenced by add_verts_to_dgroups(), applyModifier(), bbs_mesh_solid(), BL_ConvertMesh(), BL_CreatePhysicsObjectNew(), bm_mdisps_space_set(), BMEdit_Free(), brush_add(), KX_NavMeshObject::BuildVertIndArrays(), canvas_copyDerivedMesh(), cdDM_create(), CDDM_merge_verts(), clear_mesh_caches(), connect_hair(), construct_param_handle_subsurfed(), contarget_get_mesh_mat(), convert_exec(), crazyspace_get_mapped_editverts(), createVertsTrisData(), curve_calc_modifiers_post(), curve_calc_orcodm(), deformMatrices(), deformMatricesEM(), deformVerts(), deformVertsEM(), distribute_particles_on_dm(), distribute_threads_init_data(), dm_deform_clear(), do_hair_dynamics(), draw_mesh_fancy(), draw_mesh_object(), draw_mesh_text(), draw_object_backbufsel(), draw_object_mesh_instance(), draw_uvs(), dupli_render_particle_set(), dynamicPaint_brushMeshCalculateVelocity(), dynamicPaint_freeBrush(), dynamicPaint_freeCanvas(), dynamicPaint_Modifier_apply(), dynamicPaint_paintMesh(), EDBM_mesh_clear(), editbmesh_build_data(), editbmesh_calc_modifiers(), editbmesh_get_first_deform_matrices(), face_duplilist(), free_hair(), free_heights_data(), freeData(), getCCGDerivedMesh(), getEditDerivedBMesh(), imapaint_pick_uv(), init_render_curve(), init_render_mesh(), init_render_object_data(), init_render_surf(), initElbeemMesh(), mesh_calc_modifiers(), mesh_create_derived_for_modifier(), mesh_deform_bind(), mesh_foreachScreenEdge(), mesh_foreachScreenFace(), mesh_foreachScreenVert(), mesh_get_mapped_verts_nors(), mesh_to_curve(), meshdeform_bind_exec(), mirrorModifier__doMirror(), modifier_apply_obdata(), modifier_apply_shape(), multires_apply_smat(), multires_force_update(), multires_load_old(), multires_modifier_update_mdisps(), multires_set_space(), multires_subdivide(), multiresbake_create_hiresdm(), multiresbake_create_loresdm(), multiresbake_freejob(), multiresbake_image_exec_locked(), multiresModifier_base_apply(), multiresModifier_reshapeFromDeformMod(), multiresModifier_reshapeFromDM(), NewBooleanMesh(), object_free_display(), object_handle_update(), GeometryExporter::operator()(), paint_exit(), peelObjects(), pointdensity_cache_object(), pointdensity_cache_psys(), project_paint_begin(), project_paint_end(), psys_render_restore(), sculpt_get_first_deform_matrices(), CcdShapeConstructionInfo::SetMesh(), shrinkwrap_get_tarmat(), shrinkwrapModifier_deform(), snapObject(), subsurf_calculate_limit_positions(), texture_paint_init(), BL_ModifierDeformer::Update(), CcdShapeConstructionInfo::UpdateMesh(), vertex_duplilist(), weight_sample_invoke(), and BL_ModifierDeformer::~BL_ModifierDeformer().
DerivedMeshType DerivedMesh::type
Definition at line 164 of file BKE_DerivedMesh.h.
Referenced by DM_ensure_tessface(), DM_from_template(), DM_init(), DM_vertex_attributes_from_gpu(), get_cddm(), mesh_calc_modifiers(), project_paint_begin(), project_paint_end(), BL_Uniform::SetData(), sphere_do(), and texttool_suggest_add().
CustomData DerivedMesh::vertData
Definition at line 158 of file BKE_DerivedMesh.h.
Referenced by add_shapekey_layers(), applyModifier(), CDDM_apply_vert_coords(), CDDM_apply_vert_normals(), CDDM_calc_normals(), CDDM_calc_normals_mapping(), CDDM_calc_normals_mapping_ex(), CDDM_calc_normals_tessface(), cddm_copy_ex(), CDDM_from_BMEditMesh(), CDDM_from_mesh(), CDDM_from_template(), CDDM_lower_num_verts(), CDDM_merge_verts(), CDDM_new(), CDDM_set_mvert(), DM_add_vert_layer(), dm_calc_normal(), DM_copy_vert_data(), DM_free_vert_data(), DM_from_template(), DM_get_vert_data(), DM_get_vert_data_layer(), dm_getVertArray(), dm_getVertCData(), DM_interp_vert_data(), DM_release(), DM_set_only_copy(), DM_set_vert_data(), DM_to_bmesh_ex(), DM_to_mesh(), DM_vertex_attributes_from_gpu(), doMirrorOnAxis(), dynamicPaint_Modifier_apply(), and shapekey_layers_to_keyblocks().
The documentation for this struct was generated from the following file:
BKE_DerivedMesh.h