Blender: iTaSC::WDLSSolver Class Reference
iTaSC::WDLSSolver Class Reference
#include <WDLSSolver.hpp>
Public Member Functions
WDLSSolver ()
virtual ~WDLSSolver ()
virtual bool init (unsigned int nq, unsigned int nc, const std::vector< bool > &gc)
virtual bool solve (const e_matrix &A, const e_vector &Wy, const e_vector &ydot, const e_matrix &Wq, e_vector &qdot, e_scalar &nlcoef)
virtual void setParam (SolverParam param, double value)
Detailed Description
Definition at line 15 of file WDLSSolver.hpp.
Constructor & Destructor Documentation
iTaSC::WDLSSolver::WDLSSolver ()
Definition at line 16 of file WDLSSolver.cpp.
iTaSC::WDLSSolver::~WDLSSolver () [virtual]
Definition at line 22 of file WDLSSolver.cpp.
Member Function Documentation
bool iTaSC::WDLSSolver::init (unsigned int nq, unsigned int nc, const std::vector< bool > & gc) [virtual]
Implements iTaSC::Solver.
Definition at line 25 of file WDLSSolver.cpp.
References e_zero_matrix, e_zero_vector, max, and min.
virtual void iTaSC::WDLSSolver::setParam (SolverParam param, double value) [inline, virtual]
Implements iTaSC::Solver.
Definition at line 30 of file WDLSSolver.hpp.
References iTaSC::Solver::DLS_EPSILON, iTaSC::Solver::DLS_LAMBDA_MAX, and iTaSC::Solver::DLS_QMAX.
bool iTaSC::WDLSSolver::solve (const e_matrix & A, const e_vector & Wy, const e_vector & ydot, const e_matrix & Wq, e_vector & qdot, e_scalar & nlcoef) [virtual]
Implements iTaSC::Solver.
Definition at line 49 of file WDLSSolver.cpp.
References e_scalar, KDL::epsilon, fabs(), i, norm(), KDL::sqr(), and KDL::svd_eigen_HH().
The documentation for this class was generated from the following files:
WDLSSolver.hpp
WDLSSolver.cpp