Blender: btMinkowskiPenetrationDepthSolver Class Reference
btMinkowskiPenetrationDepthSolver Class Reference
#include <btMinkowskiPenetrationDepthSolver.h>
Public Member Functions
virtual bool calcPenDepth (btSimplexSolverInterface &simplexSolver, const btConvexShape *convexA, const btConvexShape *convexB, const btTransform &transA, const btTransform &transB, btVector3 &v, btVector3 &pa, btVector3 &pb, class btIDebugDraw *debugDraw, btStackAlloc *stackAlloc)
Static Protected Member Functions
static btVector3 * getPenetrationDirections ()
Detailed Description
MinkowskiPenetrationDepthSolver implements bruteforce penetration depth estimation. Implementation is based on sampling the depth using support mapping, and using GJK step to get the witness points.
Definition at line 23 of file btMinkowskiPenetrationDepthSolver.h.
Member Function Documentation
bool btMinkowskiPenetrationDepthSolver::calcPenDepth (btSimplexSolverInterface & simplexSolver, const btConvexShape * convexA, const btConvexShape * convexB, const btTransform & transA, const btTransform & transB, btVector3 & v, btVector3 & pa, btVector3 & pb, class btIDebugDraw * debugDraw, btStackAlloc * stackAlloc) [virtual]
scale dependent
Implements btConvexPenetrationDepthSolver.
Definition at line 25 of file btMinkowskiPenetrationDepthSolver.cpp.
References BT_LARGE_FLOAT, btIDebugDraw::drawLine(), btTransform::getBasis(), btGjkPairDetector::getClosestPoints(), btTransform::getOrigin(), getPenetrationDirections(), i, btDiscreteCollisionDetectorInterface::ClosestPointInput::m_maximumDistanceSquared, btDiscreteCollisionDetectorInterface::ClosestPointInput::m_transformA, btDiscreteCollisionDetectorInterface::ClosestPointInput::m_transformB, MAX_PREFERRED_PENETRATION_DIRECTIONS, norm(), NUM_UNITSPHERE_POINTS, btGjkPairDetector::setCachedSeperatingAxis(), and btTransform::setOrigin().
btVector3 * btMinkowskiPenetrationDepthSolver::getPenetrationDirections () [static, protected]
Definition at line 311 of file btMinkowskiPenetrationDepthSolver.cpp.
References MAX_PREFERRED_PENETRATION_DIRECTIONS, and NUM_UNITSPHERE_POINTS.
Referenced by calcPenDepth().
The documentation for this class was generated from the following files:
btMinkowskiPenetrationDepthSolver.h
btMinkowskiPenetrationDepthSolver.cpp