Blender: mesh_intern.h File Reference
mesh_intern.h File Reference
mesh
Functions
int EDBM_op_callf (struct BMEditMesh *em, struct wmOperator *op, const char *fmt,...)
int EDBM_op_call_and_selectf (struct BMEditMesh *em, struct wmOperator *op, const char *selectslot, const char *fmt,...)
int EDBM_op_call_silentf (struct BMEditMesh *em, const char *fmt,...)
int EDBM_op_init (struct BMEditMesh *em, struct BMOperator *bmop, struct wmOperator *op, const char *fmt,...)
int EDBM_op_finish (struct BMEditMesh *em, struct BMOperator *bmop, struct wmOperator *op, const int report)
void EDBM_flag_disable_all (struct BMEditMesh *em, const char hflag)
void EDBM_stats_update (struct BMEditMesh *em)
float labda_PdistVL2Dfl (const float v1[3], const float v2[3], const float v3[3])
void em_setup_viewcontext (struct bContext *C, struct ViewContext *vc)
void MESH_OT_separate (struct wmOperatorType *ot)
void MESH_OT_primitive_plane_add (struct wmOperatorType *ot)
void MESH_OT_primitive_cube_add (struct wmOperatorType *ot)
void MESH_OT_primitive_circle_add (struct wmOperatorType *ot)
void MESH_OT_primitive_cylinder_add (struct wmOperatorType *ot)
void MESH_OT_primitive_cone_add (struct wmOperatorType *ot)
void MESH_OT_primitive_grid_add (struct wmOperatorType *ot)
void MESH_OT_primitive_monkey_add (struct wmOperatorType *ot)
void MESH_OT_primitive_uv_sphere_add (struct wmOperatorType *ot)
void MESH_OT_primitive_ico_sphere_add (struct wmOperatorType *ot)
void MESH_OT_edge_face_add (struct wmOperatorType *ot)
void MESH_OT_dupli_extrude_cursor (struct wmOperatorType *ot)
void MESH_OT_duplicate (struct wmOperatorType *ot)
int EM_view3d_poll (struct bContext *C)
struct wmKeyMap * knifetool_modal_keymap (struct wmKeyConfig *keyconf)
void MESH_OT_knife_cut (struct wmOperatorType *ot)
void MESH_OT_loop_select (struct wmOperatorType *ot)
void MESH_OT_select_all (struct wmOperatorType *ot)
void MESH_OT_select_interior_faces (struct wmOperatorType *ot)
void MESH_OT_select_more (struct wmOperatorType *ot)
void MESH_OT_select_less (struct wmOperatorType *ot)
void MESH_OT_select_non_manifold (struct wmOperatorType *ot)
void MESH_OT_select_linked (struct wmOperatorType *ot)
void MESH_OT_select_linked_pick (struct wmOperatorType *ot)
void MESH_OT_hide (struct wmOperatorType *ot)
void MESH_OT_reveal (struct wmOperatorType *ot)
void MESH_OT_select_by_number_vertices (struct wmOperatorType *ot)
void MESH_OT_select_loose_verts (struct wmOperatorType *ot)
void MESH_OT_select_mirror (struct wmOperatorType *ot)
void MESH_OT_normals_make_consistent (struct wmOperatorType *ot)
void MESH_OT_faces_select_linked_flat (struct wmOperatorType *ot)
void MESH_OT_edges_select_sharp (struct wmOperatorType *ot)
void MESH_OT_select_shortest_path (struct wmOperatorType *ot)
void MESH_OT_select_similar (struct wmOperatorType *ot)
void MESH_OT_select_random (struct wmOperatorType *ot)
void MESH_OT_loop_multi_select (struct wmOperatorType *ot)
void MESH_OT_mark_seam (struct wmOperatorType *ot)
void MESH_OT_mark_sharp (struct wmOperatorType *ot)
void MESH_OT_vertices_smooth (struct wmOperatorType *ot)
void MESH_OT_noise (struct wmOperatorType *ot)
void MESH_OT_flip_normals (struct wmOperatorType *ot)
void MESH_OT_solidify (struct wmOperatorType *ot)
void MESH_OT_select_nth (struct wmOperatorType *ot)
void MESH_OT_select_next_loop (struct wmOperatorType *ot)
void MESH_OT_merge (struct wmOperatorType *ot)
void MESH_OT_subdivide (struct wmOperatorType *ot)
void MESH_OT_remove_doubles (struct wmOperatorType *ot)
void MESH_OT_vertices_randomize (struct wmOperatorType *ot)
void MESH_OT_vertices_sort (struct wmOperatorType *ot)
void MESH_OT_spin (struct wmOperatorType *ot)
void MESH_OT_screw (struct wmOperatorType *ot)
void MESH_OT_fill (struct wmOperatorType *ot)
void MESH_OT_beautify_fill (struct wmOperatorType *ot)
void MESH_OT_quads_convert_to_tris (struct wmOperatorType *ot)
void MESH_OT_tris_convert_to_quads (struct wmOperatorType *ot)
void MESH_OT_dissolve (struct wmOperatorType *ot)
void MESH_OT_dissolve_limited (struct wmOperatorType *ot)
void MESH_OT_faces_shade_smooth (struct wmOperatorType *ot)
void MESH_OT_faces_shade_flat (struct wmOperatorType *ot)
void MESH_OT_split (struct wmOperatorType *ot)
void MESH_OT_extrude_repeat (struct wmOperatorType *ot)
void MESH_OT_edge_rotate (struct wmOperatorType *ot)
void MESH_OT_select_vertex_path (struct wmOperatorType *ot)
void MESH_OT_loop_to_region (struct wmOperatorType *ot)
void MESH_OT_region_to_loop (struct wmOperatorType *ot)
void MESH_OT_select_axis (struct wmOperatorType *ot)
void MESH_OT_uvs_rotate (struct wmOperatorType *ot)
void MESH_OT_uvs_reverse (struct wmOperatorType *ot)
void MESH_OT_colors_rotate (struct wmOperatorType *ot)
void MESH_OT_colors_reverse (struct wmOperatorType *ot)
void MESH_OT_delete (struct wmOperatorType *ot)
void MESH_OT_edge_collapse (struct wmOperatorType *ot)
void MESH_OT_edge_collapse_loop (struct wmOperatorType *ot)
void MESH_OT_rip (struct wmOperatorType *ot)
void MESH_OT_shape_propagate_to_all (struct wmOperatorType *ot)
void MESH_OT_blend_from_shape (struct wmOperatorType *ot)
void MESH_OT_sort_faces (struct wmOperatorType *ot)
void MESH_OT_uv_texture_add (struct wmOperatorType *ot)
void MESH_OT_uv_texture_remove (struct wmOperatorType *ot)
void MESH_OT_vertex_color_add (struct wmOperatorType *ot)
void MESH_OT_vertex_color_remove (struct wmOperatorType *ot)
void MESH_OT_sticky_add (struct wmOperatorType *ot)
void MESH_OT_sticky_remove (struct wmOperatorType *ot)
void MESH_OT_drop_named_image (struct wmOperatorType *ot)
void MESH_OT_vert_connect (struct wmOperatorType *ot)
void MESH_OT_edge_split (struct wmOperatorType *ot)
void MESH_OT_extrude_region (struct wmOperatorType *ot)
void MESH_OT_extrude_verts_indiv (struct wmOperatorType *ot)
void MESH_OT_extrude_edges_indiv (struct wmOperatorType *ot)
void MESH_OT_extrude_faces_indiv (struct wmOperatorType *ot)
void MESH_OT_edgering_select (struct wmOperatorType *ot)
void MESH_OT_loopcut (struct wmOperatorType *ot)
void MESH_OT_knife_tool (struct wmOperatorType *ot)
void MESH_OT_bevel (struct wmOperatorType *ot)
void MESH_OT_bridge_edge_loops (struct wmOperatorType *ot)
void MESH_OT_inset (struct wmOperatorType *ot)
void MESH_OT_vert_slide (struct wmOperatorType *ot)
void MESH_OT_navmesh_make (struct wmOperatorType *ot)
void MESH_OT_navmesh_face_copy (struct wmOperatorType *ot)
void MESH_OT_navmesh_face_add (struct wmOperatorType *ot)
void MESH_OT_navmesh_reset (struct wmOperatorType *ot)
void MESH_OT_navmesh_clear (struct wmOperatorType *ot)
Variables
struct EnumPropertyItem * corner_type_items
Detailed Description
Definition in file mesh_intern.h.
Function Documentation
void EDBM_flag_disable_all (struct BMEditMesh * em, const char hflag)
Definition at line 468 of file editmesh_utils.c.
References BMEditMesh::bm, BM_EDGE, BM_FACE, BM_mesh_elem_hflag_disable_all(), BM_VERT, and FALSE.
int EDBM_op_call_and_selectf (struct BMEditMesh * em, struct wmOperator * op, const char * selectslot, const char * fmt, ...)
Definition at line 208 of file editmesh_utils.c.
References BKE_reportf(), BMEditMesh::bm, BM_ALL, BM_EDGE, BM_ELEM_SELECT, BM_FACE, BM_mesh_elem_hflag_disable_all(), BM_VERT, BMEdit_Copy(), BMO_op_exec(), BMO_op_vinitf(), BMO_slot_buffer_hflag_enable(), EDBM_op_finish(), BMEditMesh::emcopy, BMEditMesh::emcopyusers, FALSE, wmOperator::reports, RPT_ERROR, and TRUE.
Referenced by add_primitive_circle_exec(), add_primitive_cone_exec(), add_primitive_cube_exec(), add_primitive_cylinder_exec(), add_primitive_grid_exec(), add_primitive_icosphere_exec(), add_primitive_monkey_exec(), add_primitive_plane_exec(), and add_primitive_uvsphere_exec().
int EDBM_op_call_silentf (struct BMEditMesh * em, const char * fmt, ...)
Definition at line 236 of file editmesh_utils.c.
References BMEditMesh::bm, BMEdit_Copy(), BMO_op_exec(), BMO_op_vinitf(), EDBM_op_finish(), BMEditMesh::emcopy, BMEditMesh::emcopyusers, FALSE, and NULL.
int EDBM_op_callf (struct BMEditMesh * em, struct wmOperator * op, const char * fmt, ...)
Definition at line 184 of file editmesh_utils.c.
References BKE_reportf(), BMEditMesh::bm, BMEdit_Copy(), BMO_op_exec(), BMO_op_vinitf(), EDBM_op_finish(), BMEditMesh::emcopy, BMEditMesh::emcopyusers, wmOperator::reports, RPT_ERROR, and TRUE.
Referenced by edbm_beautify_fill_exec(), edbm_bridge_edge_loops_exec(), edbm_collapse_edge_exec(), edbm_collapse_edge_loop_exec(), edbm_delete_exec(), edbm_dissolve_exec(), edbm_dissolve_limited_exec(), edbm_do_smooth_vertex_exec(), edbm_dupli_extrude_cursor_invoke(), edbm_flip_normals_exec(), edbm_merge_exec(), edbm_normals_make_consistent_exec(), edbm_quads_convert_to_tris_exec(), edbm_remove_doubles_exec(), edbm_tris_convert_to_quads_exec(), merge_firstlast(), merge_target(), mesh_separate_selected(), and vtx_slide_confirm().
int EDBM_op_finish (struct BMEditMesh * em, struct BMOperator * bmop, struct wmOperator * op, const int report)
Definition at line 140 of file editmesh_utils.c.
References BKE_report(), BMEditMesh::bm, BMEdit_Free(), BMEdit_RecalcTessellation(), BMO_error_get(), BMO_op_finish(), EDBM_mesh_free(), BMEditMesh::emcopy, BMEditMesh::emcopyusers, FALSE, BMEditMesh::looptris, MEM_freeN(), NULL, wmOperator::reports, RPT_ERROR, and TRUE.
Referenced by edbm_add_edge_face_exec(), edbm_bevel_exec(), edbm_dupli_extrude_cursor_invoke(), edbm_duplicate_exec(), edbm_edge_rotate_selected_exec(), edbm_edge_split_exec(), edbm_extrude_edges_indiv(), edbm_extrude_face_indiv(), edbm_extrude_verts_indiv(), edbm_fill_exec(), edbm_inset_exec(), edbm_knife_cut_exec(), EDBM_op_call_and_selectf(), EDBM_op_call_silentf(), EDBM_op_callf(), edbm_remove_doubles_exec(), edbm_reverse_colors_exec(), edbm_reverse_uvs_exec(), edbm_rip_call_edgesplit(), edbm_rotate_colors_exec(), edbm_rotate_uvs_exec(), edbm_screw_exec(), edbm_select_vertex_path_exec(), edbm_solidify_exec(), edbm_spin_exec(), edbm_split_exec(), edbm_vert_connect(), edbm_vertex_slide_exec(), similar_edge_select_exec(), similar_face_select_exec(), and similar_vert_select_exec().
int EDBM_op_init (struct BMEditMesh * em, struct BMOperator * bmop, struct wmOperator * op, const char * fmt, ...)
Definition at line 116 of file editmesh_utils.c.
References BKE_reportf(), BMEditMesh::bm, BMEdit_Copy(), BMO_op_vinitf(), BMEditMesh::emcopy, BMEditMesh::emcopyusers, wmOperator::reports, and RPT_ERROR.
Referenced by edbm_add_edge_face_exec(), edbm_bevel_exec(), edbm_dupli_extrude_cursor_invoke(), edbm_duplicate_exec(), edbm_edge_rotate_selected_exec(), edbm_edge_split_exec(), edbm_extrude_edges_indiv(), edbm_extrude_face_indiv(), edbm_extrude_verts_indiv(), edbm_fill_exec(), edbm_inset_exec(), edbm_knife_cut_exec(), edbm_remove_doubles_exec(), edbm_reverse_colors_exec(), edbm_reverse_uvs_exec(), edbm_rip_call_edgesplit(), edbm_rotate_colors_exec(), edbm_rotate_uvs_exec(), edbm_screw_exec(), edbm_select_vertex_path_exec(), edbm_solidify_exec(), edbm_spin_exec(), edbm_split_exec(), edbm_vert_connect(), edbm_vertex_slide_exec(), similar_edge_select_exec(), similar_face_select_exec(), and similar_vert_select_exec().
void EDBM_stats_update (struct BMEditMesh * em)
Definition at line 89 of file editmesh_utils.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, i, NULL, BMesh::totedgesel, BMesh::totfacesel, and BMesh::totvertsel.
void em_setup_viewcontext (struct bContext * C, struct ViewContext * vc)
Definition at line 2209 of file editmesh_select.c.
References Object::data, Mesh::edit_btmesh, ViewContext::em, ViewContext::obedit, and view3d_set_viewcontext().
Referenced by edbm_dupli_extrude_cursor_invoke(), edbm_select_linked_pick_invoke(), knifetool_init(), mouse_mesh(), mouse_mesh_loop(), mouse_mesh_shortest_path(), ringsel_init(), vtx_slide_init(), and xsortvert_flag().
int EM_view3d_poll (struct bContext * C)
Definition at line 2220 of file editmesh_select.c.
References ED_operator_editmesh(), and ED_operator_view3d_active().
Referenced by MESH_OT_knife_cut(), MESH_OT_rip(), MESH_OT_screw(), MESH_OT_spin(), and MESH_OT_vertices_sort().
struct wmKeyMap* knifetool_modal_keymap (struct wmKeyConfig * keyconf) [read]
Definition at line 2891 of file editmesh_knife.c.
References CKEY, EKEY, ESCKEY, KM_ANY, KM_PRESS, KM_RELEASE, KNF_MODAL_ADD_CUT, KNF_MODAL_ANGLE_SNAP_TOGGLE, KNF_MODAL_CANCEL, KNF_MODAL_CONFIRM, KNF_MODAL_CUT_THROUGH_TOGGLE, KNF_MODAL_MIDPOINT_OFF, KNF_MODAL_MIDPOINT_ON, KNF_MODAL_NEW_CUT, KNF_MODEL_IGNORE_SNAP_OFF, KNF_MODEL_IGNORE_SNAP_ON, LEFTCTRLKEY, LEFTMOUSE, LEFTSHIFTKEY, wmKeyMap::modal_items, NULL, PADENTER, RETKEY, RIGHTCTRLKEY, RIGHTMOUSE, RIGHTSHIFTKEY, SPACEKEY, WM_modalkeymap_add(), WM_modalkeymap_add_item(), WM_modalkeymap_assign(), WM_modalkeymap_get(), and ZKEY.
Referenced by ED_keymap_mesh().
float labda_PdistVL2Dfl (const float v1[3], const float v2[3], const float v3[3])
Definition at line 446 of file editmesh_select.c.
References len().
Referenced by findnearestedge__doClosest(), and knife_find_closest_edge().
void MESH_OT_beautify_fill (struct wmOperatorType * ot)
Definition at line 3054 of file editmesh_tools.c.
References ED_operator_editmesh(), edbm_beautify_fill_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_bevel (struct wmOperatorType * ot)
Definition at line 4156 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_bevel_exec(), wmOperatorType::exec, FALSE, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_blend_from_shape (struct wmOperatorType * ot)
Definition at line 2293 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_blend_from_shape_exec(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_float(), shape_itemf(), wmOperatorType::srna, and WM_operator_props_popup().
Referenced by ED_operatortypes_mesh().
void MESH_OT_bridge_edge_loops (struct wmOperatorType * ot)
Definition at line 4192 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_bridge_edge_loops_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_colors_reverse (struct wmOperatorType * ot)
Definition at line 1819 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_reverse_colors_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_colors_rotate (struct wmOperatorType * ot)
Definition at line 1801 of file editmesh_tools.c.
References wmOperatorType::description, DIRECTION_CCW, ED_operator_editmesh(), edbm_rotate_colors_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_delete (struct wmOperatorType * ot)
Definition at line 940 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_delete_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_mesh().
void MESH_OT_dissolve (struct wmOperatorType * ot)
Definition at line 3176 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_dissolve_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_dissolve_limited (struct wmOperatorType * ot)
Definition at line 3213 of file editmesh_tools.c.
References DEG2RADF, wmOperatorType::description, ED_operator_editmesh(), edbm_dissolve_limited_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_rotation(), RNA_def_property_float_default(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_drop_named_image (struct wmOperatorType * ot)
Definition at line 636 of file mesh_data.c.
References wmOperatorType::description, drop_named_image_invoke(), FILE_MAX, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, layers_poll(), MAX_ID_NAME, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_dupli_extrude_cursor (struct wmOperatorType * ot)
Definition at line 877 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_dupli_extrude_cursor_invoke(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_duplicate (struct wmOperatorType * ot)
Definition at line 1293 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_duplicate_exec(), edbm_duplicate_invoke(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, and TFM_TRANSLATION.
Referenced by ED_operatortypes_mesh().
void MESH_OT_edge_collapse (struct wmOperatorType * ot)
Definition at line 973 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_collapse_edge_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_edge_collapse_loop (struct wmOperatorType * ot)
Definition at line 1001 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_collapse_edge_loop_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_edge_face_add (struct wmOperatorType * ot)
Definition at line 1060 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_add_edge_face_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_edge_rotate (struct wmOperatorType * ot)
Definition at line 1403 of file editmesh_tools.c.
References wmOperatorType::description, DIRECTION_CW, ED_operator_editmesh(), edbm_edge_rotate_selected_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_edge_split (struct wmOperatorType * ot)
Definition at line 1246 of file editmesh_tools.c.
References ED_operator_editmesh(), edbm_edge_split_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_edgering_select (struct wmOperatorType * ot)
Definition at line 1097 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh_region_view3d(), edbm_select_loop_invoke(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_edges_select_sharp (struct wmOperatorType * ot)
Definition at line 2268 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_sharp_edges_exec(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_extrude_edges_indiv (struct wmOperatorType * ot)
Definition at line 589 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_extrude_edges_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_extrude_faces_indiv (struct wmOperatorType * ot)
Definition at line 620 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_extrude_faces_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_extrude_region (struct wmOperatorType * ot)
Definition at line 527 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_extrude_region_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_extrude_repeat (struct wmOperatorType * ot)
Definition at line 406 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh_view3d(), edbm_extrude_repeat_exec(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_extrude_verts_indiv (struct wmOperatorType * ot)
Definition at line 558 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_extrude_verts_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_faces_select_linked_flat (struct wmOperatorType * ot)
Definition at line 2349 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_linked_flat_faces_exec(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_faces_shade_flat (struct wmOperatorType * ot)
Definition at line 1646 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_faces_shade_flat_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_faces_shade_smooth (struct wmOperatorType * ot)
Definition at line 1619 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_faces_shade_smooth_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_fill (struct wmOperatorType * ot)
Definition at line 3026 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_fill_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_flip_normals (struct wmOperatorType * ot)
Definition at line 1323 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_flip_normals_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_hide (struct wmOperatorType * ot)
Definition at line 1434 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_hide_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_inset (struct wmOperatorType * ot)
Definition at line 4253 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_inset_exec(), wmOperatorType::exec, FALSE, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float(), RNA_def_property_ui_range(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_knife_cut (struct wmOperatorType * ot)
Definition at line 2756 of file editmesh_tools.c.
References BC_KNIFECURSOR, wmOperatorType::description, edbm_knife_cut_exec(), EM_view3d_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, KNIFE_EXACT, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_COLLECTION, PROP_NONE, RNA_def_enum(), RNA_def_int(), RNA_def_property(), RNA_def_property_struct_runtime(), RNA_OperatorMousePath, wmOperatorType::srna, WM_gesture_lines_invoke(), and WM_gesture_lines_modal().
void MESH_OT_knife_tool (struct wmOperatorType * ot)
Definition at line 3071 of file editmesh_knife.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_editmesh_view3d(), FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, knifetool_cancel(), knifetool_invoke(), knifetool_modal(), wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_loop_multi_select (struct wmOperatorType * ot)
Definition at line 973 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_loop_multiselect_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_loop_select (struct wmOperatorType * ot)
Definition at line 1078 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh_region_view3d(), edbm_select_loop_invoke(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_loop_to_region (struct wmOperatorType * ot)
Definition at line 2762 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_loop_to_region_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_loopcut (struct wmOperatorType * ot)
Definition at line 569 of file editmesh_loopcut.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_editmesh_region_view3d(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, loopcut_modal(), wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_SKIP_SAVE, ringcut_cancel(), ringcut_invoke(), RNA_def_int(), RNA_def_property_flag(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_mark_seam (struct wmOperatorType * ot)
Definition at line 1115 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_mark_seam(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_mark_sharp (struct wmOperatorType * ot)
Definition at line 1169 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_mark_sharp(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_merge (struct wmOperatorType * ot)
Definition at line 1998 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_merge_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, merge_type_itemf(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), RNA_def_enum_funcs(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_mesh().
void MESH_OT_navmesh_clear (struct wmOperatorType * ot)
Definition at line 680 of file mesh_navmesh.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, navmesh_clear_exec(), navmesh_obmode_data_poll(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_navmesh_face_add (struct wmOperatorType * ot)
Definition at line 603 of file mesh_navmesh.c.
References wmOperatorType::description, ED_operator_editmesh(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, navmesh_face_add_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_navmesh_face_copy (struct wmOperatorType * ot)
Definition at line 522 of file mesh_navmesh.c.
References wmOperatorType::description, ED_operator_editmesh(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, navmesh_face_copy_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_navmesh_make (struct wmOperatorType * ot)
Definition at line 472 of file mesh_navmesh.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, navmesh_create_exec(), OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by ED_operatortypes_mesh().
void MESH_OT_navmesh_reset (struct wmOperatorType * ot)
Definition at line 652 of file mesh_navmesh.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, navmesh_obmode_poll(), navmesh_reset_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_noise (struct wmOperatorType * ot)
Definition at line 4068 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_noise_exec(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_normals_make_consistent (struct wmOperatorType * ot)
Definition at line 1497 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_normals_make_consistent_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_circle_add (struct wmOperatorType * ot)
Definition at line 255 of file editmesh_add.c.
References add_primitive_circle_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_DISTANCE, RNA_def_enum(), RNA_def_float(), RNA_def_int(), RNA_def_property_subtype(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_cone_add (struct wmOperatorType * ot)
Definition at line 380 of file editmesh_add.c.
References add_primitive_cone_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_DISTANCE, RNA_def_enum(), RNA_def_float(), RNA_def_int(), RNA_def_property_subtype(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_cube_add (struct wmOperatorType * ot)
Definition at line 198 of file editmesh_add.c.
References add_primitive_cube_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_cylinder_add (struct wmOperatorType * ot)
Definition at line 318 of file editmesh_add.c.
References add_primitive_cylinder_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_DISTANCE, RNA_def_enum(), RNA_def_float(), RNA_def_int(), RNA_def_property_subtype(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_grid_add (struct wmOperatorType * ot)
Definition at line 440 of file editmesh_add.c.
References add_primitive_grid_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_DISTANCE, RNA_def_float(), RNA_def_int(), RNA_def_property_subtype(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_ico_sphere_add (struct wmOperatorType * ot)
Definition at line 599 of file editmesh_add.c.
References add_primitive_icosphere_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_DISTANCE, RNA_def_float(), RNA_def_int(), RNA_def_property_subtype(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_monkey_add (struct wmOperatorType * ot)
Definition at line 494 of file editmesh_add.c.
References add_primitive_monkey_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_plane_add (struct wmOperatorType * ot)
Definition at line 153 of file editmesh_add.c.
References add_primitive_plane_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_uv_sphere_add (struct wmOperatorType * ot)
Definition at line 542 of file editmesh_add.c.
References add_primitive_uvsphere_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_DISTANCE, RNA_def_float(), RNA_def_int(), RNA_def_property_subtype(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_quads_convert_to_tris (struct wmOperatorType * ot)
Definition at line 3084 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_quads_convert_to_tris_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_region_to_loop (struct wmOperatorType * ot)
Definition at line 2580 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_region_to_loop_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_remove_doubles (struct wmOperatorType * ot)
Definition at line 2048 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_remove_doubles_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_reveal (struct wmOperatorType * ot)
Definition at line 1464 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_reveal_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_rip (struct wmOperatorType * ot)
Definition at line 759 of file editmesh_rip.c.
References wmOperatorType::description, edbm_rip_invoke(), EM_view3d_poll(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, P_PROPORTIONAL, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, and Transform_Properties().
Referenced by ED_operatortypes_mesh().
void MESH_OT_screw (struct wmOperatorType * ot)
Definition at line 3452 of file editmesh_tools.c.
References wmOperatorType::description, edbm_screw_exec(), edbm_screw_invoke(), EM_view3d_poll(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_vector(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_all (struct wmOperatorType * ot)
Definition at line 666 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_all_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_properties_select_all().
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_axis (struct wmOperatorType * ot)
Definition at line 2368 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_axis_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_by_number_vertices (struct wmOperatorType * ot)
Definition at line 3515 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_by_number_vertices_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_interior_faces (struct wmOperatorType * ot)
Definition at line 699 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_faces_select_interior_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_less (struct wmOperatorType * ot)
Definition at line 2007 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_less_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_linked (struct wmOperatorType * ot)
Definition at line 1951 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_linked_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_linked_pick (struct wmOperatorType * ot)
Definition at line 1853 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_linked_pick_invoke(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_loose_verts (struct wmOperatorType * ot)
Definition at line 3571 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_loose_verts_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_mirror (struct wmOperatorType * ot)
Definition at line 3599 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_mirror_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_more (struct wmOperatorType * ot)
Definition at line 1981 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_more_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_next_loop (struct wmOperatorType * ot)
Definition at line 2516 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_next_loop_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_non_manifold (struct wmOperatorType * ot)
Definition at line 2401 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_non_manifold_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_nth (struct wmOperatorType * ot)
Definition at line 2191 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_nth_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_random (struct wmOperatorType * ot)
Definition at line 2461 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_random_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_percentage(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_shortest_path (struct wmOperatorType * ot)
Definition at line 1437 of file editmesh_select.c.
References wmOperatorType::description, edbm_shortest_path_select_invoke(), edbm_shortest_path_select_poll(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_similar (struct wmOperatorType * ot)
Definition at line 868 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_similar_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_float(), select_similar_type_itemf(), SIMVERT_NORMAL, wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_vertex_path (struct wmOperatorType * ot)
Definition at line 2128 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_vertex_path_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, VPATH_SELECT_EDGE_LENGTH, and VPATH_SELECT_TOPOLOGICAL.
Referenced by ED_operatortypes_mesh().
void MESH_OT_separate (struct wmOperatorType * ot)
Definition at line 2982 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_separate_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_mesh().
void MESH_OT_shape_propagate_to_all (struct wmOperatorType * ot)
Definition at line 2203 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_shape_propagate_to_all_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_solidify (struct wmOperatorType * ot)
Definition at line 2434 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_solidify_exec(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), RNA_def_property_ui_range(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_sort_faces (struct wmOperatorType * ot)
Definition at line 3903 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_sort_faces_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_mesh().
void MESH_OT_spin (struct wmOperatorType * ot)
Definition at line 3328 of file editmesh_tools.c.
References wmOperatorType::description, edbm_spin_exec(), edbm_spin_invoke(), EM_view3d_poll(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float(), RNA_def_float_vector(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_split (struct wmOperatorType * ot)
Definition at line 3256 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_split_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_sticky_add (struct wmOperatorType * ot)
Definition at line 759 of file mesh_data.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, layers_poll(), mesh_sticky_add_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_sticky_remove (struct wmOperatorType * ot)
Definition at line 791 of file mesh_data.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, layers_poll(), mesh_sticky_remove_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_subdivide (struct wmOperatorType * ot)
Definition at line 118 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_subdivide_exec(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_boolean(), RNA_def_enum(), RNA_def_float(), RNA_def_int(), RNA_def_property_flag(), wmOperatorType::srna, and SUBD_STRAIGHT_CUT.
Referenced by ED_operatortypes_mesh().
void MESH_OT_tris_convert_to_quads (struct wmOperatorType * ot)
Definition at line 3125 of file editmesh_tools.c.
References DEG2RADF, wmOperatorType::description, ED_operator_editmesh(), edbm_tris_convert_to_quads_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_rotation(), RNA_def_property_float_default(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_uv_texture_add (struct wmOperatorType * ot)
Definition at line 553 of file mesh_data.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, layers_poll(), mesh_uv_texture_add_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_uv_texture_remove (struct wmOperatorType * ot)
Definition at line 666 of file mesh_data.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, layers_poll(), mesh_uv_texture_remove_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_uvs_reverse (struct wmOperatorType * ot)
Definition at line 1783 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_reverse_uvs_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_uvs_rotate (struct wmOperatorType * ot)
Definition at line 1764 of file editmesh_tools.c.
References wmOperatorType::description, DIRECTION_CW, ED_operator_editmesh(), edbm_rotate_uvs_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_vert_connect (struct wmOperatorType * ot)
Definition at line 1209 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_vert_connect(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_vert_slide (struct wmOperatorType * ot)
Definition at line 716 of file editmesh_slide.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_editmesh_region_view3d(), edbm_vertex_slide_cancel(), edbm_vertex_slide_invoke(), edbm_vertex_slide_modal(), wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_float(), RNA_def_property_flag(), RNA_def_property_ui_range(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_vertex_color_add (struct wmOperatorType * ot)
Definition at line 695 of file mesh_data.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, layers_poll(), mesh_vertex_color_add_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_vertex_color_remove (struct wmOperatorType * ot)
Definition at line 721 of file mesh_data.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, layers_poll(), mesh_vertex_color_remove_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_vertices_randomize (struct wmOperatorType * ot)
Definition at line 3993 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_vertices_randomize_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_vertices_smooth (struct wmOperatorType * ot)
Definition at line 1574 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_do_smooth_vertex_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_vertices_sort (struct wmOperatorType * ot)
Definition at line 3732 of file editmesh_tools.c.
References wmOperatorType::description, edbm_vertices_sort_exec(), EM_view3d_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
Variable Documentation
struct EnumPropertyItem* corner_type_items