Blender: node_composite_premulkey.c File Reference
node_composite_premulkey.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void node_composit_exec_premulkey (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_premulkey (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_premulkey_in []
static bNodeSocketTemplate cmp_node_premulkey_out []
Detailed Description
Definition in file node_composite_premulkey.c.
Function Documentation
static void node_composit_exec_premulkey (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 47 of file node_composite_premulkey.c.
References CB_RGBA, bNode::custom1, bNodeStack::data, data, dupalloc_compbuf(), free_compbuf(), premul_compbuf(), and typecheck_compbuf().
Referenced by register_node_type_cmp_premulkey().
void register_node_type_cmp_premulkey (bNodeTreeType * ttype)
Definition at line 64 of file node_composite_premulkey.c.
References CMP_NODE_PREMULKEY, NODE_CLASS_CONVERTOR, node_composit_exec_premulkey(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_premulkey_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 38 of file node_composite_premulkey.c.
bNodeSocketTemplate cmp_node_premulkey_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 42 of file node_composite_premulkey.c.