Blender: node_composite_levels.c File Reference
node_composite_levels.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void rgb_tobw (float r, float g, float b, float *out)
static void fill_bins (bNode *node, CompBuf *in, int *bins)
static float brightness_mean (bNode *node, CompBuf *in)
static float brightness_standard_deviation (bNode *node, CompBuf *in, float mean)
static void draw_histogram (bNode *node, CompBuf *out, int *bins)
static void node_composit_exec_view_levels (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_view_levels (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_view_levels (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_view_levels_in []
static bNodeSocketTemplate cmp_node_view_levels_out []
Detailed Description
Definition in file node_composite_levels.c.
Function Documentation
static float brightness_mean (bNode * node, CompBuf * in) [static]
Definition at line 110 of file node_composite_levels.c.
References bNode::custom1, qd_getPixel(), rgb_to_yuv(), rgb_tobw(), sum(), CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_view_levels().
static float brightness_standard_deviation (bNode * node, CompBuf * in, float mean) [static]
Definition at line 162 of file node_composite_levels.c.
References bNode::custom1, qd_getPixel(), rgb_to_yuv(), rgb_tobw(), sqrt(), sum(), CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_view_levels().
static void draw_histogram (bNode * node, CompBuf * out, int * bins) [static]
Definition at line 218 of file node_composite_levels.c.
References bNode::custom1, max, qd_setPixel(), CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_view_levels().
static void fill_bins (bNode * node, CompBuf * in, int * bins) [static]
Definition at line 53 of file node_composite_levels.c.
References bNode::custom1, qd_getPixel(), rgb_to_yuv(), rgb_tobw(), CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_view_levels().
static void node_composit_exec_view_levels (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 272 of file node_composite_levels.c.
References alloc_compbuf(), brightness_mean(), brightness_standard_deviation(), CB_RGBA, draw_histogram(), fill_bins(), free_compbuf(), generate_preview(), NULL, typecheck_compbuf(), and bNodeStack::vec.
Referenced by register_node_type_cmp_view_levels().
static void node_composit_init_view_levels (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 318 of file node_composite_levels.c.
References bNode::custom1.
Referenced by register_node_type_cmp_view_levels().
void register_node_type_cmp_view_levels (bNodeTreeType * ttype)
Definition at line 323 of file node_composite_levels.c.
References CMP_NODE_VIEW_LEVELS, NODE_CLASS_OUTPUT, node_composit_exec_view_levels(), node_composit_init_view_levels(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
static void rgb_tobw (float r, float g, float b, float * out) [static]
Definition at line 48 of file node_composite_levels.c.
Referenced by brightness_mean(), brightness_standard_deviation(), and fill_bins().
Variable Documentation
bNodeSocketTemplate cmp_node_view_levels_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image", 0.0f, 0.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_composite_levels.c.
bNodeSocketTemplate cmp_node_view_levels_out[] [static]
Initial value:
{
    {SOCK_FLOAT, 0,"Mean"},
    {SOCK_FLOAT, 0,"Std Dev"},
    {-1,0,""}
}
Definition at line 42 of file node_composite_levels.c.