Blender: bmesh_operator_api_inline.h File Reference
bmesh_operator_api_inline.h File Reference
BMesh
Functions
BLI_INLINE short _bmo_elem_flag_test (BMesh *bm, BMFlagLayer *oflags, const short oflag)
BLI_INLINE short _bmo_elem_flag_test_bool (BMesh *bm, BMFlagLayer *oflags, const short oflag)
BLI_INLINE void _bmo_elem_flag_enable (BMesh *bm, BMFlagLayer *oflags, const short oflag)
BLI_INLINE void _bmo_elem_flag_disable (BMesh *bm, BMFlagLayer *oflags, const short oflag)
BLI_INLINE void _bmo_elem_flag_set (BMesh *bm, BMFlagLayer *oflags, const short oflag, int val)
BLI_INLINE void _bmo_elem_flag_toggle (BMesh *bm, BMFlagLayer *oflags, const short oflag)
BLI_INLINE void BMO_slot_map_int_insert (BMesh *bm, BMOperator *op, const char *slotname, void *element, int val)
BLI_INLINE void BMO_slot_map_float_insert (BMesh *bm, BMOperator *op, const char *slotname, void *element, float val)
BLI_INLINE void BMO_slot_map_ptr_insert (BMesh *bm, BMOperator *op, const char *slotname, void *element, void *val)
BLI_INLINE int BMO_slot_map_contains (BMesh *UNUSED(bm), BMOperator *op, const char *slotname, void *element)
BLI_INLINE void * BMO_slot_map_data_get (BMesh *UNUSED(bm), BMOperator *op, const char *slotname, void *element)
BLI_INLINE float BMO_slot_map_float_get (BMesh *bm, BMOperator *op, const char *slotname, void *element)
BLI_INLINE int BMO_slot_map_int_get (BMesh *bm, BMOperator *op, const char *slotname, void *element)
BLI_INLINE void * BMO_slot_map_ptr_get (BMesh *bm, BMOperator *op, const char *slotname, void *element)
Detailed Description
BMesh inline operator functions.
Definition in file bmesh_operator_api_inline.h.
Function Documentation
BLI_INLINE void _bmo_elem_flag_disable (BMesh * bm, BMFlagLayer * oflags, const short oflag)
Definition at line 56 of file bmesh_operator_api_inline.h.
References BMFlagLayer::f, and BMesh::stackdepth.
BLI_INLINE void _bmo_elem_flag_enable (BMesh * bm, BMFlagLayer * oflags, const short oflag)
Definition at line 51 of file bmesh_operator_api_inline.h.
References BMFlagLayer::f, and BMesh::stackdepth.
BLI_INLINE void _bmo_elem_flag_set (BMesh * bm, BMFlagLayer * oflags, const short oflag, int val)
Definition at line 61 of file bmesh_operator_api_inline.h.
References BMFlagLayer::f, and BMesh::stackdepth.
BLI_INLINE short _bmo_elem_flag_test (BMesh * bm, BMFlagLayer * oflags, const short oflag)
Definition at line 41 of file bmesh_operator_api_inline.h.
References BMFlagLayer::f, and BMesh::stackdepth.
BLI_INLINE short _bmo_elem_flag_test_bool (BMesh * bm, BMFlagLayer * oflags, const short oflag)
Definition at line 46 of file bmesh_operator_api_inline.h.
References BMFlagLayer::f, and BMesh::stackdepth.
BLI_INLINE void _bmo_elem_flag_toggle (BMesh * bm, BMFlagLayer * oflags, const short oflag)
Definition at line 67 of file bmesh_operator_api_inline.h.
References BMFlagLayer::f, and BMesh::stackdepth.
BLI_INLINE int BMO_slot_map_contains (BMesh * UNUSEDbm, BMOperator * op, const char * slotname, void * element)
Definition at line 96 of file bmesh_operator_api_inline.h.
References BLI_assert, BLI_ghash_haskey(), BMO_OP_SLOT_MAPPING, BMO_slot_get(), BMOpSlot::data, BMOpSlot::ghash, and BMOpSlot::slottype.
Referenced by bmo_edgenet_fill_exec(), bmo_extrude_face_region_exec(), and edge_find_shortest_path().
BLI_INLINE void* BMO_slot_map_data_get (BMesh * UNUSEDbm, BMOperator * op, const char * slotname, void * element)
Definition at line 107 of file bmesh_operator_api_inline.h.
References BLI_assert, BLI_ghash_lookup(), BMO_OP_SLOT_MAPPING, BMO_slot_get(), BMOpSlot::data, BMOpSlot::ghash, NULL, and BMOpSlot::slottype.
Referenced by bmo_esubd_exec(), BMO_slot_map_float_get(), BMO_slot_map_int_get(), and BMO_slot_map_ptr_get().
BLI_INLINE float BMO_slot_map_float_get (BMesh * bm, BMOperator * op, const char * slotname, void * element)
Definition at line 124 of file bmesh_operator_api_inline.h.
References BMO_slot_map_data_get().
Referenced by subdivideedgenum().
BLI_INLINE void BMO_slot_map_float_insert (BMesh * bm, BMOperator * op, const char * slotname, void * element, float val)
Definition at line 78 of file bmesh_operator_api_inline.h.
References BMO_slot_map_insert().
Referenced by edbm_knife_cut_exec().
BLI_INLINE int BMO_slot_map_int_get (BMesh * bm, BMOperator * op, const char * slotname, void * element)
Definition at line 133 of file bmesh_operator_api_inline.h.
References BMO_slot_map_data_get().
Referenced by bmo_edgenet_fill_exec(), and edge_find_shortest_path().
BLI_INLINE void BMO_slot_map_int_insert (BMesh * bm, BMOperator * op, const char * slotname, void * element, int val)
Definition at line 72 of file bmesh_operator_api_inline.h.
References BMO_slot_map_insert().
Referenced by bmo_edgenet_fill_exec().
BLI_INLINE void* BMO_slot_map_ptr_get (BMesh * bm, BMOperator * op, const char * slotname, void * element)
Definition at line 142 of file bmesh_operator_api_inline.h.
References BMO_slot_map_data_get(), and NULL.
Referenced by arrayModifier_doArray(), bmo_extrude_face_region_exec(), bmo_weldverts_exec(), and remdoubles_splitface().
BLI_INLINE void BMO_slot_map_ptr_insert (BMesh * bm, BMOperator * op, const char * slotname, void * element, void * val)
Definition at line 90 of file bmesh_operator_api_inline.h.
References BMO_slot_map_insert().
Referenced by arrayModifier_doArray(), bm_merge_dm_transform(), bmesh_finddoubles_common(), bmo_collapse_exec(), bmo_mirror_exec(), bmo_pointmerge_exec(), bmo_triangulate_exec(), copy_edge(), copy_face(), copy_mesh(), edbm_extrude_edge(), and merge_first_last().