Blender: bpy_util.c File Reference
bpy_util.c File Reference
Python RNA and Operators
#include <Python.h>
#include "bpy_util.h"
#include "BLI_dynstr.h"
#include "MEM_guardedalloc.h"
#include "BKE_report.h"
#include "BKE_context.h"
#include "../generic/py_capi_utils.h"
Functions
bContext * BPy_GetContext (void)
void BPy_SetContext (bContext *C)
char * BPy_enum_as_string (EnumPropertyItem *item)
short BPy_reports_to_error (ReportList *reports, PyObject *exception, const short clear)
short BPy_errors_to_report (ReportList *reports)
Variables
static bContext * __py_context = NULL
Detailed Description
This file contains blender/python utility functions for the api's internal use (unrelated to 'bpy.utils')
Definition in file bpy_util.c.
Function Documentation
char* BPy_enum_as_string (EnumPropertyItem * item)
Definition at line 44 of file bpy_util.c.
References BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), and EnumPropertyItem::identifier.
Referenced by pyop_call(), pyop_poll(), pyrna_enum_as_string(), and pyrna_enum_value_from_id().
short BPy_errors_to_report (ReportList * reports)
Definition at line 79 of file bpy_util.c.
References BKE_report(), BKE_reportf(), NULL, PyC_ExceptionBuffer(), PyC_FileAndNum(), and RPT_ERROR.
Referenced by BPY_button_exec(), bpy_class_call(), BPY_string_exec(), and python_script_exec().
bContext* BPy_GetContext (void) [read]
Definition at line 41 of file bpy_util.c.
References __py_context.
Referenced by bpy_atexit(), bpy_class_call(), BPy_init_modules(), bpy_lib_exit(), mathutils_rna_matrix_set(), mathutils_rna_vector_set(), mathutils_rna_vector_set_index(), pyop_as_string(), pyop_call(), pyop_poll(), pyrna_enum_as_string(), pyrna_enum_to_py(), pyrna_func_call(), pyrna_prop_array_ass_subscript(), pyrna_prop_to_enum_bitfield(), pyrna_py_to_prop(), pyrna_py_to_prop_array_index(), pyrna_register_class(), pyrna_string_to_enum(), pyrna_struct_driver_add(), pyrna_struct_driver_remove(), pyrna_struct_keyframe_parse(), and pyrna_unregister_class().
short BPy_reports_to_error (ReportList * reports, PyObject * exception, const short clear)
Definition at line 60 of file bpy_util.c.
References BKE_reports_clear(), BKE_reports_string(), MEM_freeN(), NULL, and RPT_ERROR.
Referenced by bpy_lib_enter(), pyop_call(), pyrna_func_call(), pyrna_register_class(), pyrna_struct_driver_add(), pyrna_struct_driver_remove(), pyrna_struct_keyframe_delete(), and pyrna_struct_keyframe_insert().
void BPy_SetContext (bContext * C)
Definition at line 42 of file bpy_util.c.
References C.
Referenced by bpy_context_clear(), BPY_context_set(), and bpy_context_update().
Variable Documentation
bContext* __py_context = NULL [static]
Definition at line 40 of file bpy_util.c.
Referenced by BPy_GetContext().