Blender: BKE_bvhutils.h File Reference
BKE_bvhutils.h File Reference
blenkernel
#include "BLI_kdopbvh.h"
Classes
struct BVHTreeFromMesh
Defines
#define BVHTREE_FROM_FACES 0
#define BVHTREE_FROM_VERTICES 1
#define BVHTREE_FROM_EDGES 2
Typedefs
typedef struct BVHTreeFromMesh BVHTreeFromMesh
typedef struct LinkNode * BVHCache
Functions
BVHTree * bvhtree_from_mesh_verts (struct BVHTreeFromMesh *data, struct DerivedMesh *mesh, float epsilon, int tree_type, int axis)
BVHTree * bvhtree_from_mesh_faces (struct BVHTreeFromMesh *data, struct DerivedMesh *mesh, float epsilon, int tree_type, int axis)
BVHTree * bvhtree_from_mesh_edges (struct BVHTreeFromMesh *data, struct DerivedMesh *mesh, float epsilon, int tree_type, int axis)
void free_bvhtree_from_mesh (struct BVHTreeFromMesh *data)
float bvhtree_ray_tri_intersection (const BVHTreeRay *ray, const float m_dist, const float v0[3], const float v1[3], const float v2[3])
float nearest_point_in_tri_surface (const float v0[3], const float v1[3], const float v2[3], const float p[3], int *v, int *e, float nearest[3])
BVHTree * bvhcache_find (BVHCache *cache, int type)
void bvhcache_insert (BVHCache *cache, BVHTree *tree, int type)
void bvhcache_init (BVHCache *cache)
void bvhcache_free (BVHCache *cache)
Detailed Description
Definition in file BKE_bvhutils.h.
Define Documentation
#define BVHTREE_FROM_EDGES 2
Definition at line 121 of file BKE_bvhutils.h.
Referenced by bvhtree_from_mesh_edges().
#define BVHTREE_FROM_FACES 0
Definition at line 119 of file BKE_bvhutils.h.
Referenced by bvhtree_from_mesh_faces().
#define BVHTREE_FROM_VERTICES 1
Definition at line 120 of file BKE_bvhutils.h.
Referenced by bvhtree_from_mesh_verts().
Typedef Documentation
typedef struct LinkNode* BVHCache
Definition at line 123 of file BKE_bvhutils.h.
typedef struct BVHTreeFromMesh BVHTreeFromMesh
Function Documentation
BVHTree* bvhcache_find (BVHCache * cache, int type)
Definition at line 734 of file bvhutils.c.
References BLI_linklist_apply(), bvhcacheitem_set_if_match(), NULL, BVHCacheItem::tree, and BVHCacheItem::type.
Referenced by bvhcache_insert(), bvhtree_from_mesh_edges(), bvhtree_from_mesh_faces(), and bvhtree_from_mesh_verts().
void bvhcache_free (BVHCache * cache)
Definition at line 775 of file bvhutils.c.
References BLI_linklist_free(), bvhcacheitem_free(), and NULL.
Referenced by DM_release().
void bvhcache_init (BVHCache * cache)
Definition at line 761 of file bvhutils.c.
References NULL.
Referenced by DM_init_funcs().
void bvhcache_insert (BVHCache * cache, BVHTree * tree, int type)
Definition at line 744 of file bvhutils.c.
References assert, BLI_linklist_prepend(), bvhcache_find(), MEM_mallocN(), NULL, BVHCacheItem::tree, and BVHCacheItem::type.
Referenced by bvhtree_from_mesh_edges(), bvhtree_from_mesh_faces(), and bvhtree_from_mesh_verts().
BVHTree* bvhtree_from_mesh_edges (struct BVHTreeFromMesh * data, struct DerivedMesh * mesh, float epsilon, int tree_type, int axis)
Definition at line 647 of file bvhutils.c.
References BLI_bvhtree_balance(), BLI_bvhtree_insert(), BLI_bvhtree_new(), DerivedMesh::bvhCache, bvhcache_find(), bvhcache_insert(), BVHTREE_FROM_EDGES, BVHTreeFromMesh::cached, CD_MEDGE, CD_MVERT, co, copy_v3_v3(), BVHTreeFromMesh::edge, KDL::epsilon, DerivedMesh::getEdgeDataArray, DerivedMesh::getNumEdges, DerivedMesh::getVertDataArray, i, BVHTreeFromMesh::mesh, mesh_edges_nearest_point(), BVHTreeFromMesh::nearest_callback, NULL, BVHTreeFromMesh::raycast_callback, BVHTreeFromMesh::sphere_radius, BVHTreeFromMesh::tree, TRUE, and BVHTreeFromMesh::vert.
Referenced by deformVerts(), and get_vert2geom_distance().
BVHTree* bvhtree_from_mesh_faces (struct BVHTreeFromMesh * data, struct DerivedMesh * mesh, float epsilon, int tree_type, int axis)
Definition at line 517 of file bvhutils.c.
References BLI_assert, BLI_bvhtree_balance(), BLI_bvhtree_insert(), BLI_bvhtree_new(), BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ITER_ELEM, BM_VERTS_OF_FACE, DerivedMesh::bvhCache, bvhcache_find(), bvhcache_insert(), BVHTREE_FROM_FACES, BVHTreeFromMesh::cached, CD_MFACE, CD_MVERT, BMVert::co, co, copy_v3_v3(), BVHTreeFromMesh::em_evil, KDL::epsilon, BMLoop::f, BVHTreeFromMesh::face, DerivedMesh::getNumPolys, DerivedMesh::getNumTessFaces, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVertDataArray, i, BMEditMesh::looptris, BVHTreeFromMesh::mesh, mesh_faces_nearest_point(), mesh_faces_spherecast(), BVHTreeFromMesh::nearest_callback, NULL, BVHTreeFromMesh::raycast_callback, BVHTreeFromMesh::sphere_radius, BMEditMesh::tottri, BVHTreeFromMesh::tree, TRUE, and BVHTreeFromMesh::vert.
Referenced by connect_hair(), deformVerts(), dynamicPaint_paintMesh(), followtrack_evaluate(), get_vert2geom_distance(), shrinkwrap_calc_nearest_surface_point(), shrinkwrap_calc_normal_projection(), shrinkwrap_get_tarmat(), and snapDerivedMesh().
BVHTree* bvhtree_from_mesh_verts (struct BVHTreeFromMesh * data, struct DerivedMesh * mesh, float epsilon, int tree_type, int axis)
Definition at line 463 of file bvhutils.c.
References BLI_bvhtree_balance(), BLI_bvhtree_insert(), BLI_bvhtree_new(), DerivedMesh::bvhCache, bvhcache_find(), bvhcache_insert(), BVHTREE_FROM_VERTICES, BVHTreeFromMesh::cached, CD_MFACE, CD_MVERT, co, KDL::epsilon, BVHTreeFromMesh::face, DerivedMesh::getNumVerts, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVertDataArray, i, BVHTreeFromMesh::mesh, BVHTreeFromMesh::nearest_callback, NULL, BVHTreeFromMesh::raycast_callback, BVHTreeFromMesh::sphere_radius, BVHTreeFromMesh::tree, TRUE, and BVHTreeFromMesh::vert.
Referenced by get_vert2geom_distance(), shrinkwrap_calc_nearest_vertex(), and shrinkwrap_get_tarmat().
float bvhtree_ray_tri_intersection (const BVHTreeRay * ray, const float m_dist, const float v0[3], const float v1[3], const float v2[3])
Referenced by mesh_faces_spherecast(), and mesh_faces_spherecast_dp().
void free_bvhtree_from_mesh (struct BVHTreeFromMesh * data)
Definition at line 705 of file bvhutils.c.
References BLI_bvhtree_free(), BVHTreeFromMesh::cached, and BVHTreeFromMesh::tree.
Referenced by connect_hair(), deformVerts(), dynamicPaint_paintMesh(), followtrack_evaluate(), freeData(), get_vert2geom_distance(), shrinkwrap_calc_nearest_surface_point(), shrinkwrap_calc_nearest_vertex(), shrinkwrap_calc_normal_projection(), and shrinkwrap_get_tarmat().
float nearest_point_in_tri_surface (const float v0[3], const float v1[3], const float v2[3], const float p[3], int * v, int * e, float nearest[3])
Definition at line 82 of file bvhutils.c.
References add_v3_v3v3(), C, copy_v3_v3(), KDL::diff(), dot_v3v3(), fabs(), fabsf, mul_v3_fl(), sub_v3_v3v3(), and T.
Referenced by mesh_faces_nearest_point(), and mesh_faces_nearest_point_dp().