Blender: anim_intern.h File Reference
anim_intern.h File Reference
animation
Functions
void ANIM_OT_keyframe_insert (struct wmOperatorType *ot)
void ANIM_OT_keyframe_delete (struct wmOperatorType *ot)
void ANIM_OT_keyframe_insert_menu (struct wmOperatorType *ot)
void ANIM_OT_keyframe_delete_v3d (struct wmOperatorType *ot)
void ANIM_OT_keyframe_insert_button (struct wmOperatorType *ot)
void ANIM_OT_keyframe_delete_button (struct wmOperatorType *ot)
void ANIM_OT_keyingset_button_add (struct wmOperatorType *ot)
void ANIM_OT_keyingset_button_remove (struct wmOperatorType *ot)
void ANIM_OT_keying_set_add (struct wmOperatorType *ot)
void ANIM_OT_keying_set_remove (struct wmOperatorType *ot)
void ANIM_OT_keying_set_path_add (struct wmOperatorType *ot)
void ANIM_OT_keying_set_path_remove (struct wmOperatorType *ot)
void ANIM_OT_keying_set_active_set (struct wmOperatorType *ot)
void ANIM_OT_driver_button_add (struct wmOperatorType *ot)
void ANIM_OT_driver_button_remove (struct wmOperatorType *ot)
void ANIM_OT_copy_driver_button (struct wmOperatorType *ot)
void ANIM_OT_paste_driver_button (struct wmOperatorType *ot)
Variables
ListBase builtin_keyingsets
Detailed Description
Definition in file anim_intern.h.
Function Documentation
void ANIM_OT_copy_driver_button (struct wmOperatorType * ot)
Definition at line 614 of file drivers.c.
References copy_driver_button_exec(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by ED_operatortypes_anim().
void ANIM_OT_driver_button_add (struct wmOperatorType * ot)
Definition at line 515 of file drivers.c.
References add_driver_button_exec(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_driver_button_remove (struct wmOperatorType * ot)
Definition at line 567 of file drivers.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, remove_driver_button_exec(), RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyframe_delete (struct wmOperatorType * ot)
Definition at line 1312 of file keyframing.c.
References ANIM_keying_sets_enum_itemf(), delete_key_exec(), wmOperatorType::description, DummyRNA_DEFAULT_items, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, modify_key_op_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, PROP_HIDDEN, RNA_def_boolean(), RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_property_flag(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyframe_delete_button (struct wmOperatorType * ot)
Definition at line 1549 of file keyframing.c.
References delete_key_button_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, modify_key_op_poll(), wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyframe_delete_v3d (struct wmOperatorType * ot)
Definition at line 1387 of file keyframing.c.
References delete_key_v3d_exec(), wmOperatorType::description, ED_operator_areaactive(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyframe_insert (struct wmOperatorType * ot)
Definition at line 1156 of file keyframing.c.
References ANIM_keying_sets_enum_itemf(), wmOperatorType::description, DummyRNA_DEFAULT_items, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, insert_key_exec(), modify_key_op_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, PROP_HIDDEN, RNA_def_boolean(), RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_property_flag(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyframe_insert_button (struct wmOperatorType * ot)
Definition at line 1477 of file keyframing.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, insert_key_button_exec(), modify_key_op_poll(), wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyframe_insert_menu (struct wmOperatorType * ot)
Definition at line 1217 of file keyframing.c.
References ANIM_keying_sets_enum_itemf(), wmOperatorType::description, DummyRNA_DEFAULT_items, ED_operator_areaactive(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, insert_key_exec(), insert_key_menu_invoke(), wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, PROP_HIDDEN, RNA_def_boolean(), RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_property_flag(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keying_set_active_set (struct wmOperatorType * ot)
Definition at line 497 of file keyingsets.c.
References ANIM_keying_sets_enum_itemf(), DummyRNA_DEFAULT_items, ED_operator_areaactive(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, keyingset_active_menu_exec(), keyingset_active_menu_invoke(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_enum_funcs(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keying_set_add (struct wmOperatorType * ot)
Definition at line 140 of file keyingsets.c.
References add_default_keyingset_exec(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, keyingset_poll_default_add(), wmOperatorType::name, and wmOperatorType::poll.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keying_set_path_add (struct wmOperatorType * ot)
Definition at line 230 of file keyingsets.c.
References add_empty_ks_path_exec(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, keyingset_poll_active_edit(), wmOperatorType::name, and wmOperatorType::poll.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keying_set_path_remove (struct wmOperatorType * ot)
Definition at line 273 of file keyingsets.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, keyingset_poll_activePath_edit(), wmOperatorType::name, wmOperatorType::poll, and remove_active_ks_path_exec().
Referenced by ED_operatortypes_anim().
void ANIM_OT_keying_set_remove (struct wmOperatorType * ot)
Definition at line 187 of file keyingsets.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, keyingset_poll_active_edit(), wmOperatorType::name, wmOperatorType::poll, and remove_active_keyingset_exec().
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyingset_button_add (struct wmOperatorType * ot)
Definition at line 371 of file keyingsets.c.
References add_keyingset_button_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyingset_button_remove (struct wmOperatorType * ot)
Definition at line 450 of file keyingsets.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and remove_keyingset_button_exec().
Referenced by ED_operatortypes_anim().
void ANIM_OT_paste_driver_button (struct wmOperatorType * ot)
Definition at line 658 of file drivers.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and paste_driver_button_exec().
Referenced by ED_operatortypes_anim().
Variable Documentation
ListBase builtin_keyingsets
Definition at line 526 of file keyingsets.c.
Referenced by delete_key_exec(), and insert_key_exec().