Blender: interface_ops.c File Reference
interface_ops.c File Reference
interface
#include <stdio.h>
#include <math.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_text_types.h"
#include "BLI_blenlib.h"
#include "BLI_math_color.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "BKE_global.h"
#include "BKE_text.h"
#include "BKE_report.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "BIF_gl.h"
#include "UI_interface.h"
#include "interface_intern.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_screen.h"
#include "BKE_main.h"
#include "BLI_ghash.h"
Classes
struct Eyedropper
Typedefs
typedef struct Eyedropper Eyedropper
Functions
static int eyedropper_init (bContext *C, wmOperator *op)
static void eyedropper_exit (bContext *C, wmOperator *op)
static int eyedropper_cancel (bContext *C, wmOperator *op)
static void eyedropper_sample (bContext *C, Eyedropper *eye, int mx, int my)
static int eyedropper_modal (bContext *C, wmOperator *op, wmEvent *event)
static int eyedropper_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int eyedropper_exec (bContext *C, wmOperator *op)
static int eyedropper_poll (bContext *C)
static void UI_OT_eyedropper (wmOperatorType *ot)
static int reset_default_theme_exec (bContext *C, wmOperator *UNUSED(op))
static void UI_OT_reset_default_theme (wmOperatorType *ot)
static int copy_data_path_button_exec (bContext *C, wmOperator *UNUSED(op))
static void UI_OT_copy_data_path_button (wmOperatorType *ot)
static int reset_default_button_poll (bContext *C)
static int reset_default_button_exec (bContext *C, wmOperator *op)
static void UI_OT_reset_default_button (wmOperatorType *ot)
static int copy_to_selected_list (bContext *C, PointerRNA *ptr, ListBase *lb, int *use_path)
static int copy_to_selected_button_poll (bContext *C)
static int copy_to_selected_button_exec (bContext *C, wmOperator *op)
static void UI_OT_copy_to_selected_button (wmOperatorType *ot)
static int reports_to_text_poll (bContext *C)
static int reports_to_text_exec (bContext *C, wmOperator *UNUSED(op))
static void UI_OT_reports_to_textblock (wmOperatorType *ot)
void UI_buttons_operatortypes (void)
Detailed Description
Definition in file interface_ops.c.
Typedef Documentation
typedef struct Eyedropper Eyedropper
Function Documentation
static int copy_data_path_button_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 237 of file interface_ops.c.
References PointerRNA::data, FALSE, PointerRNA::id, MEM_freeN(), OPERATOR_CANCELLED, OPERATOR_FINISHED, RNA_path_from_ID_to_property(), uiContextActiveProperty(), and WM_clipboard_text_set().
Referenced by UI_OT_copy_data_path_button().
static int copy_to_selected_button_exec (bContext * C, wmOperator * op) [static]
Definition at line 420 of file interface_ops.c.
References BLI_freelistN(), copy_to_selected_list(), PointerRNA::data, ListBase::first, PointerRNA::id, link(), MEM_freeN(), CollectionPointerLink::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, CollectionPointerLink::ptr, RNA_boolean_get(), RNA_id_pointer_create(), RNA_path_from_ID_to_property(), RNA_path_resolve(), RNA_property_copy(), RNA_property_editable(), RNA_property_update(), and uiContextActiveProperty().
Referenced by UI_OT_copy_to_selected_button().
static int copy_to_selected_button_poll (bContext * C) [static]
Definition at line 373 of file interface_ops.c.
References BLI_freelistN(), copy_to_selected_list(), PointerRNA::data, ListBase::first, PointerRNA::id, link(), MEM_freeN(), CollectionPointerLink::next, NULL, CollectionPointerLink::ptr, RNA_id_pointer_create(), RNA_path_from_ID_to_property(), RNA_path_resolve(), RNA_property_editable(), and uiContextActiveProperty().
Referenced by UI_OT_copy_to_selected_button().
static int copy_to_selected_list (bContext * C, PointerRNA * ptr, ListBase * lb, int * use_path) [static]
Definition at line 349 of file interface_ops.c.
References CTX_data_collection_get(), PointerRNA::data, GS, PointerRNA::id, ID_OB, ID::name, RNA_EditBone, RNA_PoseBone, RNA_Sequence, RNA_struct_is_a(), and PointerRNA::type.
Referenced by copy_to_selected_button_exec(), and copy_to_selected_button_poll().
static int eyedropper_cancel (bContext * C, wmOperator * op) [static]
Definition at line 97 of file interface_ops.c.
References eyedropper_exit(), and OPERATOR_CANCELLED.
Referenced by eyedropper_modal(), and UI_OT_eyedropper().
static int eyedropper_exec (bContext * C, wmOperator * op) [static]
Definition at line 168 of file interface_ops.c.
References eyedropper_exit(), eyedropper_init(), OPERATOR_CANCELLED, and OPERATOR_FINISHED.
Referenced by UI_OT_eyedropper().
static void eyedropper_exit (bContext * C, wmOperator * op) [static]
Definition at line 88 of file interface_ops.c.
References CTX_wm_window(), wmOperator::customdata, MEM_freeN(), NULL, and WM_cursor_restore().
Referenced by eyedropper_cancel(), eyedropper_exec(), eyedropper_invoke(), and eyedropper_modal().
static int eyedropper_init (bContext * C, wmOperator * op) [static]
Definition at line 77 of file interface_ops.c.
References wmOperator::customdata, PointerRNA::data, Eyedropper::index, MEM_callocN(), Eyedropper::prop, Eyedropper::ptr, RNA_property_editable(), and uiContextActiveProperty().
Referenced by eyedropper_exec(), and eyedropper_invoke().
static int eyedropper_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 150 of file interface_ops.c.
References BC_EYEDROPPER_CURSOR, CTX_wm_window(), eyedropper_exit(), eyedropper_init(), OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, WM_cursor_modal(), and WM_event_add_modal_handler().
Referenced by UI_OT_eyedropper().
static int eyedropper_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 129 of file interface_ops.c.
References wmOperator::customdata, ESCKEY, eyedropper_cancel(), eyedropper_exit(), eyedropper_sample(), KM_RELEASE, LEFTMOUSE, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, RIGHTMOUSE, wmEvent::type, wmEvent::val, wmEvent::x, and wmEvent::y.
Referenced by UI_OT_eyedropper().
static int eyedropper_poll (bContext * C) [static]
Definition at line 185 of file interface_ops.c.
References CTX_wm_window().
Referenced by UI_OT_eyedropper().
static void eyedropper_sample (bContext * C, Eyedropper * eye, int mx, int my) [static]
Definition at line 103 of file interface_ops.c.
References RenderData::color_mgt_flag, CTX_data_scene(), Eyedropper::prop, PROP_COLOR, PROP_FLOAT, Eyedropper::ptr, Scene::r, R_COLOR_MANAGEMENT, RNA_property_array_length(), RNA_property_float_get_array(), RNA_property_float_set_array(), RNA_property_subtype(), RNA_property_type(), RNA_property_update(), and srgb_to_linearrgb_v3_v3().
Referenced by eyedropper_modal().
static int reports_to_text_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 503 of file interface_ops.c.
References add_empty_text(), BKE_reports_string(), CTX_wm_reports(), G, G_DEBUG, MEM_freeN(), OPERATOR_CANCELLED, OPERATOR_FINISHED, RPT_DEBUG, RPT_INFO, str, and write_text().
Referenced by UI_OT_reports_to_textblock().
static int reports_to_text_poll (bContext * C) [static]
Definition at line 498 of file interface_ops.c.
References CTX_wm_reports(), and NULL.
Referenced by UI_OT_reports_to_textblock().
static int reset_default_button_exec (bContext * C, wmOperator * op) [static]
Definition at line 289 of file interface_ops.c.
References PointerRNA::data, PointerRNA::id, ID_CHECK_UNDO, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_property_editable(), RNA_property_reset(), RNA_property_update(), uiContextActiveProperty(), and uiContextActivePropertyHandle().
Referenced by UI_OT_reset_default_button().
static int reset_default_button_poll (bContext * C) [static]
Definition at line 278 of file interface_ops.c.
References PointerRNA::data, RNA_property_editable(), and uiContextActiveProperty().
Referenced by UI_OT_reset_default_button().
static int reset_default_theme_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 213 of file interface_ops.c.
References NC_WINDOW, NULL, OPERATOR_FINISHED, ui_theme_init_default(), and WM_event_add_notifier().
Referenced by UI_OT_reset_default_theme().
void UI_buttons_operatortypes (void)
Definition at line 764 of file interface_ops.c.
References UI_OT_copy_data_path_button(), UI_OT_copy_to_selected_button(), UI_OT_eyedropper(), UI_OT_reports_to_textblock(), UI_OT_reset_default_button(), UI_OT_reset_default_theme(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
static void UI_OT_copy_data_path_button (wmOperatorType * ot) [static]
Definition at line 261 of file interface_ops.c.
References copy_data_path_button_exec(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, and OPTYPE_REGISTER.
Referenced by UI_buttons_operatortypes().
static void UI_OT_copy_to_selected_button (wmOperatorType * ot) [static]
Definition at line 474 of file interface_ops.c.
References copy_to_selected_button_exec(), copy_to_selected_button_poll(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by UI_buttons_operatortypes().
static void UI_OT_eyedropper (wmOperatorType * ot) [static]
Definition at line 191 of file interface_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, eyedropper_cancel(), eyedropper_exec(), eyedropper_invoke(), eyedropper_modal(), eyedropper_poll(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, and wmOperatorType::poll.
Referenced by UI_buttons_operatortypes().
static void UI_OT_reports_to_textblock (wmOperatorType * ot) [static]
Definition at line 529 of file interface_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, reports_to_text_exec(), and reports_to_text_poll().
Referenced by UI_buttons_operatortypes().
static void UI_OT_reset_default_button (wmOperatorType * ot) [static]
Definition at line 329 of file interface_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, reset_default_button_exec(), reset_default_button_poll(), RNA_def_boolean(), and wmOperatorType::srna.
Referenced by UI_buttons_operatortypes().
static void UI_OT_reset_default_theme (wmOperatorType * ot) [static]
Definition at line 221 of file interface_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and reset_default_theme_exec().
Referenced by UI_buttons_operatortypes().