Blender: AUD_SquareFactory Class Reference
AUD_SquareFactory Class Reference
#include <AUD_SquareFactory.h>
Public Member Functions
AUD_SquareFactory (AUD_Reference< AUD_IFactory > factory, float threshold=0.0f)
float getThreshold () const
virtual AUD_Reference
< AUD_IReader > createReader ()
Static Public Member Functions
static sample_t squareFilter (AUD_CallbackIIRFilterReader *reader, float *threshold)
static void endSquareFilter (float *threshold)
Detailed Description
This factory Transforms any signal to a square signal.
Definition at line 39 of file AUD_SquareFactory.h.
Constructor & Destructor Documentation
AUD_SquareFactory::AUD_SquareFactory (AUD_Reference< AUD_IFactory > factory, float threshold = 0.0f)
Creates a new square factory.
Parameters:
factory The input factory.
threshold The threshold.
Definition at line 49 of file AUD_SquareFactory.cpp.
Member Function Documentation
AUD_Reference< AUD_IReader > AUD_SquareFactory::createReader () [virtual]
Creates a reader for playback of the sound source.
Returns:
A pointer to an AUD_IReader object or NULL if there has been an error.
Exceptions:
AUD_Exception An exception may be thrown if there has been a more unexpected error during reader creation.
Implements AUD_IFactory.
Definition at line 60 of file AUD_SquareFactory.cpp.
References endSquareFilter(), AUD_EffectFactory::getReader(), and squareFilter().
void AUD_SquareFactory::endSquareFilter (float * threshold) [static]
Definition at line 44 of file AUD_SquareFactory.cpp.
Referenced by createReader().
float AUD_SquareFactory::getThreshold () const
Returns the threshold.
Definition at line 55 of file AUD_SquareFactory.cpp.
sample_t AUD_SquareFactory::squareFilter (AUD_CallbackIIRFilterReader * reader, float * threshold) [static]
Definition at line 33 of file AUD_SquareFactory.cpp.
References AUD_BaseIIRFilterReader::x().
Referenced by createReader().
The documentation for this class was generated from the following files:
AUD_SquareFactory.h
AUD_SquareFactory.cpp