Blender: RE_render_ext.h File Reference
RE_render_ext.h File Reference
Rendering
Functions
void RE_make_sticky (struct Scene *scene, struct View3D *v3d)
int externtex (struct MTex *mtex, const float vec[3], float *tin, float *tr, float *tg, float *tb, float *ta, const int thread)
void texture_rgb_blend (float in[3], const float tex[3], const float out[3], float fact, float facg, int blendtype)
float texture_value_blend (float tex, float out, float fact, float facg, int blendtype)
void ibuf_sample (struct ImBuf *ibuf, float fx, float fy, float dx, float dy, float *result)
void antialias_tagbuf (int xsize, int ysize, char *rectmove)
struct Material * RE_init_sample_material (struct Material *orig_mat, struct Scene *scene)
void RE_free_sample_material (struct Material *mat)
void RE_sample_material_color (struct Material *mat, float color[3], float *alpha, const float volume_co[3], const float surface_co[3], int face_index, short hit_quad, struct DerivedMesh *orcoDm, struct Object *ob)
Detailed Description
Definition in file RE_render_ext.h.
Function Documentation
void antialias_tagbuf (int xsize, int ysize, char * rectmove)
Definition at line 2746 of file zbuf.c.
References next, and step().
Referenced by do_idmask(), node_composit_exec_zcombine(), and RE_zbuf_accumulate_vecblur().
int externtex (struct MTex * mtex, const float vec[3], float * tin, float * tr, float * tg, float * tb, float * ta, const int thread)
Definition at line 3422 of file render_texture.c.
References MTex::b, do_2d_mapping(), MTex::g, multitex(), TexResult::nor, NULL, MTex::ofs, MTex::projx, MTex::projy, MTex::projz, MTex::r, MTex::size, TexResult::ta, TexResult::tb, MTex::tex, TEX_IMAGE, TexResult::tg, TexResult::tin, TexResult::tr, Tex::type, and MTex::which_output.
Referenced by brush_sample_tex(), edbm_noise_exec(), get_cpa_texture(), psys_get_texture(), RE_inithalo(), RE_inithalo_particle(), and tex_strength().
void ibuf_sample (struct ImBuf * ibuf, float fx, float fy, float dx, float dy, float * result)
Definition at line 1824 of file imagetexture.c.
References afdata_t::dxt, afdata_t::dyt, ewa_eval(), afdata_t::extflag, afdata_t::intpol, NULL, TexResult::ta, TexResult::tb, TexResult::tg, TexResult::tr, and TXC_EXTD.
Referenced by do_displace(), and do_mapuv().
void RE_free_sample_material (struct Material * mat)
Definition at line 3636 of file render_texture.c.
References free_material(), free_texture(), MAX_MTEX, MEM_freeN(), Material::mtex, NULL, Material::septex, and MTex::tex.
Referenced by dynamicPaint_freeBrushMaterials().
struct Material* RE_init_sample_material (struct Material * orig_mat, struct Scene * scene) [read]
Definition at line 3549 of file render_texture.c.
References Tex::adt, Material::adt, ADT_RECALC_ANIM, BKE_animsys_evaluate_animdata(), BKE_curframe(), BKE_image_user_calc_frame(), cache_pointdensity(), cache_voxeldata(), RenderData::cfra, copy_m4_m4(), ELEM, ELEM3, ELEM4, ImageUser::flag, Tex::id, Material::id, Tex::ima, IMA_ANIM_ALWAYS, IMA_SRC_MOVIE, IMA_SRC_SEQUENCE, Object::imat, Object::imat_ren, invert_m4_m4(), Tex::iuser, localize_material(), localize_texture(), MA_TYPE_SURFACE, MA_TYPE_VOLUME, MAP_ALPHA, MAP_COL, MAP_DENSITY, MAP_REFLECTION_COL, MAP_TRANSMISSION_COL, MTex::mapto, Material::material_type, MAX_MTEX, Material::mtex, MTEX_ALPHAMIX, MTEX_NEGATIVE, MTEX_RGBTOINT, MTEX_STENCIL, NULL, MTex::object, Object::obmat, Scene::r, Render::scene, Material::septex, Image::source, MTex::tex, TEX_POINTDENSITY, TEX_VOXELDATA, MTex::texco, TEXCO_GLOB, TEXCO_OBJECT, TEXCO_ORCO, TEXCO_UV, MTex::texflag, Tex::type, unit_m4(), Render::viewinv, Render::viewmat, Render::winmat, Render::winx, and Render::winy.
Referenced by dynamicPaint_updateBrushMaterials().
void RE_make_sticky (struct Scene * scene, struct View3D * v3d)
Definition at line 5822 of file convertblender.c.
References Scene::camera, CD_CALLOC, CD_MSTICKY, MVert::co, copy_v3_v3(), CustomData_add_layer(), CustomData_free_layer_active(), Object::data, FIRSTBASE, invert_m4_m4(), Mesh::msticky, mul_m4_v3(), mult_m4_m4m4(), Mesh::mvert, Base::next, normalize_m4(), NULL, OB_MESH, Scene::obedit, Base::object, Object::obmat, projectverto(), Scene::r, RE_InitState(), RE_NewRender(), RE_SetCamera(), RE_SetView(), TESTBASELIB, Mesh::totvert, Object::type, V3D_CAMERA_LOCAL, Render::viewmat, where_is_object(), Render::winmat, RenderData::xsch, and RenderData::ysch.
Referenced by mesh_sticky_add_exec().
void RE_sample_material_color (struct Material * mat, float color[3], float * alpha, const float volume_co[3], const float surface_co[3], int face_index, short hit_quad, struct DerivedMesh * orcoDm, struct Object * ob)
Definition at line 3670 of file render_texture.c.
References ShadeInput::actuv, Material::alpha, ShadeInput::alpha, Material::b, ShadeInput::b, CD_MTFACE, MVert::co, ShadeInput::co, co, copy_v3_v3(), CustomData_get_active_layer_index(), CustomData_get_layer_index(), CustomData_number_of_layers(), CustomDataLayer::data, data, VolumeSettings::density, do_material_tex(), do_volume_tex(), DerivedMesh::faceData, Material::g, ShadeInput::g, DerivedMesh::getTessFaceArray, DerivedMesh::getVertArray, ShadeInput::gl, i, Object::imat, CustomData::layers, ShadeInput::lo, MA_TYPE_SURFACE, MA_TYPE_VOLUME, MAP_DENSITY, MAP_REFLECTION_COL, MAP_TRANSMISSION_COL, ShadeInput::mat, Material::material_type, mul_m4_v3(), CustomDataLayer::name, ShadeInputUV::name, normal_tri_v3(), ObjectInstanceRen::ob, ShadeInput::obi, Material::r, ShadeInput::r, VolumeSettings::reflection_col, textured_face_generate_uv(), ShadeInput::totuv, unit_m4(), ShadeInputUV::uv, MTFace::uv, ShadeInput::uv, MFace::v1, MFace::v2, MFace::v3, MFace::v4, Render::viewinv, and Material::vol.
Referenced by dynamicPaint_doMaterialTex().
void texture_rgb_blend (float in[3], const float tex[3], const float out[3], float fact, float facg, int blendtype)
Definition at line 1388 of file render_texture.c.
References copy_v3_v3(), fabsf, MA_RAMP_COLOR, MA_RAMP_HUE, MA_RAMP_LINEAR, MA_RAMP_SAT, MA_RAMP_SOFT, MA_RAMP_VAL, MTEX_ADD, MTEX_BLEND, MTEX_BLEND_COLOR, MTEX_BLEND_HUE, MTEX_BLEND_SAT, MTEX_BLEND_VAL, MTEX_DARK, MTEX_DIFF, MTEX_DIV, MTEX_LIGHT, MTEX_LIN_LIGHT, MTEX_MUL, MTEX_OVERLAY, MTEX_SCREEN, MTEX_SOFT_LIGHT, MTEX_SUB, and ramp_blend().
float texture_value_blend (float tex, float out, float fact, float facg, int blendtype)
Definition at line 1522 of file render_texture.c.
References fabsf, MTEX_ADD, MTEX_BLEND, MTEX_DARK, MTEX_DIFF, MTEX_DIV, MTEX_LIGHT, MTEX_LIN_LIGHT, MTEX_MUL, MTEX_OVERLAY, MTEX_SCREEN, MTEX_SOFT_LIGHT, MTEX_SUB, and SWAP.