Blender: editface.c File Reference
editface.c File Reference
mesh
#include <math.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_edgehash.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BKE_DerivedMesh.h"
#include "BKE_global.h"
#include "BKE_mesh.h"
#include "BKE_context.h"
#include "BKE_tessmesh.h"
#include "BIF_gl.h"
#include "ED_mesh.h"
#include "ED_screen.h"
#include "ED_view3d.h"
#include "WM_api.h"
#include "WM_types.h"
#include "mesh_intern.h"
Classes
struct MirrTopoVert_t
Typedefs
typedef int MirrTopoHash_t
typedef struct MirrTopoVert_t MirrTopoVert_t
Functions
void paintface_flush_flags (Object *ob)
static int facesel_face_pick (struct bContext *C, Mesh *me, Object *ob, const int mval[2], unsigned int *index, short rect)
void paintface_hide (Object *ob, const int unselected)
void paintface_reveal (Object *ob)
static void hash_add_face (EdgeHash *ehash, MPoly *mp, MLoop *mloop)
static void select_linked_tfaces_with_seams (int mode, Mesh *me, unsigned int index)
void paintface_select_linked (bContext *UNUSED(C), Object *ob, int UNUSED(mval[2]), int mode)
void paintface_deselect_all_visible (Object *ob, int action, short flush_flags)
int paintface_minmax (Object *ob, float *min, float *max)
int paintface_mouse_select (struct bContext *C, Object *ob, const int mval[2], int extend)
int do_paintface_box_select (ViewContext *vc, rcti *rect, int select, int extend)
void paintvert_flush_flags (Object *ob)
void paintvert_deselect_all_visible (Object *ob, int action, short flush_flags)
static int mirrtopo_hash_sort (const void *l1, const void *l2)
static int mirrtopo_vert_sort (const void *v1, const void *v2)
int ED_mesh_mirrtopo_recalc_check (Mesh *me, const int ob_mode, MirrTopoStore_t *mesh_topo_store)
void ED_mesh_mirrtopo_init (Mesh *me, const int ob_mode, MirrTopoStore_t *mesh_topo_store, const short skip_em_vert_array_init)
void ED_mesh_mirrtopo_free (MirrTopoStore_t *mesh_topo_store)
Detailed Description
Definition in file editface.c.
Typedef Documentation
typedef int MirrTopoHash_t
Definition at line 729 of file editface.c.
typedef struct MirrTopoVert_t MirrTopoVert_t
Function Documentation
int do_paintface_box_select (ViewContext * vc, rcti * rect, int select, int extend)
Definition at line 558 of file editface.c.
References ViewContext::ar, B_ENDIAN, ENDIAN_ORDER, FALSE, MPoly::flag, get_mesh(), IB_rect, IMB_allocImBuf(), IMB_convert_rgba_to_abgr(), IMB_freeImBuf(), ImBuf::index, ME_FACE_SEL, ME_HIDE, MEM_callocN(), MEM_freeN(), Mesh::mpoly, NULL, ViewContext::obact, OPERATOR_CANCELLED, OPERATOR_FINISHED, paintface_deselect_all_visible(), paintface_flush_flags(), ImBuf::rect, SEL_DESELECT, Mesh::totpoly, view3d_validate_backbuf(), ARegion::winrct, WM_framebuffer_to_index(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by view3d_borderselect_exec().
void ED_mesh_mirrtopo_free (MirrTopoStore_t * mesh_topo_store)
Definition at line 935 of file editface.c.
References MirrTopoStore_t::index_lookup, MEM_freeN(), NULL, MirrTopoStore_t::prev_edge_tot, and MirrTopoStore_t::prev_vert_tot.
Referenced by ED_mesh_mirrtopo_init(), EDBM_verts_mirror_cache_begin(), and mesh_mirrtopo_table().
void ED_mesh_mirrtopo_init (Mesh * me, const int ob_mode, MirrTopoStore_t * mesh_topo_store, const short skip_em_vert_array_init)
Definition at line 777 of file editface.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_index_get, BM_ITER_MESH, BM_mesh_elem_index_ensure(), BM_VERT, ED_mesh_mirrtopo_free(), EDBM_index_arrays_free(), EDBM_index_arrays_init(), EDBM_vert_at_index(), Mesh::edit_btmesh, FALSE, hash, MirrTopoVert_t::hash, MirrTopoStore_t::index_lookup, Mesh::medge, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), MEM_mallocN(), mirrtopo_hash_sort(), mirrtopo_vert_sort(), NULL, MirrTopoStore_t::prev_edge_tot, MirrTopoStore_t::prev_ob_mode, MirrTopoStore_t::prev_vert_tot, BMesh::totedge, Mesh::totedge, BMesh::totvert, Mesh::totvert, BMEdge::v1, MEdge::v1, BMEdge::v2, MEdge::v2, and MirrTopoVert_t::v_index.
Referenced by EDBM_verts_mirror_cache_begin(), and mesh_mirrtopo_table().
int ED_mesh_mirrtopo_recalc_check (Mesh * me, const int ob_mode, MirrTopoStore_t * mesh_topo_store)
Definition at line 750 of file editface.c.
References BMEditMesh::bm, Mesh::edit_btmesh, FALSE, MirrTopoStore_t::index_lookup, NULL, MirrTopoStore_t::prev_edge_tot, MirrTopoStore_t::prev_ob_mode, MirrTopoStore_t::prev_vert_tot, BMesh::totedge, Mesh::totedge, BMesh::totvert, Mesh::totvert, and TRUE.
Referenced by mesh_mirrtopo_table().
static int facesel_face_pick (struct bContext * C, Mesh * me, Object * ob, const int mval[2], unsigned int * index, short rect) [static]
Definition at line 127 of file editface.c.
References CD_MASK_BAREMESH, CTX_data_scene(), makeDerivedMesh(), NULL, Mesh::totpoly, view3d_sample_backbuf(), view3d_sample_backbuf_rect(), and view3d_set_viewcontext().
Referenced by paintface_mouse_select(), and paintface_select_linked().
static void hash_add_face (EdgeHash * ehash, MPoly * mp, MLoop * mloop) [static]
Definition at line 216 of file editface.c.
References BLI_edgehash_insert(), i, ME_POLY_LOOP_NEXT, NULL, MPoly::totloop, MLoop::v, and BMLoop::v.
Referenced by select_linked_tfaces_with_seams().
static int mirrtopo_hash_sort (const void * l1, const void * l2) [static]
Definition at line 736 of file editface.c.
Referenced by ED_mesh_mirrtopo_init().
static int mirrtopo_vert_sort (const void * v1, const void * v2) [static]
Definition at line 743 of file editface.c.
References hash.
Referenced by ED_mesh_mirrtopo_init().
void paintface_deselect_all_visible (Object * ob, int action, short flush_flags)
Definition at line 344 of file editface.c.
References MPoly::flag, get_mesh(), ME_FACE_SEL, ME_HIDE, Mesh::mpoly, NULL, paintface_flush_flags(), SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, and Mesh::totpoly.
Referenced by do_lasso_select_paintface(), do_paintface_box_select(), face_select_all_exec(), and face_select_inverse_exec().
void paintface_flush_flags (Object * ob)
Definition at line 68 of file editface.c.
References CD_ORIGINDEX, CD_POLYINDEX, CustomData_get_layer(), Object::derivedFinal, DerivedMesh::faceData, Mesh::fdata, MFace::flag, MPoly::flag, get_mesh(), DerivedMesh::getNumPolys, DerivedMesh::getNumTessFaces, DerivedMesh::getPolyArray, DerivedMesh::getTessFaceArray, i, Mesh::mface, Mesh::mpoly, NULL, DerivedMesh::polyData, and Mesh::totface.
Referenced by do_lasso_select_paintface(), do_paintface_box_select(), paintface_deselect_all_visible(), paintface_hide(), paintface_mouse_select(), paintface_reveal(), and paintface_select_linked().
void paintface_hide (Object * ob, const int unselected)
Definition at line 163 of file editface.c.
References MPoly::flag, get_mesh(), ME_FACE_SEL, ME_HIDE, Mesh::mpoly, NULL, paintface_flush_flags(), and Mesh::totpoly.
Referenced by face_select_hide_exec().
int paintface_minmax (Object * ob, float * min, float * max)
Definition at line 403 of file editface.c.
References add_v3_v3v3(), MVert::co, copy_m3_m4(), copy_v3_v3(), DO_MINMAX, MPoly::flag, get_mesh(), ME_FACE_SEL, ME_HIDE, Mesh::mloop, Mesh::mpoly, Mesh::mtpoly, mul_m3_v3(), Mesh::mvert, Object::obmat, MPoly::totloop, Mesh::totpoly, and MLoop::v.
Referenced by viewselected_exec().
int paintface_mouse_select (struct bContext * C, Object * ob, const int mval[2], int extend)
Definition at line 512 of file editface.c.
References Mesh::act_face, CTX_wm_region(), Object::data, ED_region_tag_redraw(), facesel_face_pick(), MPoly::flag, get_mesh(), ME_FACE_SEL, ME_HIDE, Mesh::mpoly, NC_GEOM, ND_SELECT, paintface_flush_flags(), Mesh::totpoly, and WM_event_add_notifier().
Referenced by view3d_select_invoke().
void paintface_reveal (Object * ob)
Definition at line 192 of file editface.c.
References MPoly::flag, get_mesh(), ME_FACE_SEL, ME_HIDE, Mesh::mpoly, NULL, paintface_flush_flags(), and Mesh::totpoly.
Referenced by face_select_reveal_exec().
void paintface_select_linked (bContext * UNUSEDC, Object * ob, int UNUSEDmval[2], int mode)
Definition at line 323 of file editface.c.
References C, facesel_face_pick(), get_mesh(), NULL, paintface_flush_flags(), select_linked_tfaces_with_seams(), and Mesh::totpoly.
void paintvert_deselect_all_visible (Object * ob, int action, short flush_flags)
Definition at line 665 of file editface.c.
References MVert::flag, get_mesh(), ME_HIDE, Mesh::mvert, NULL, paintvert_flush_flags(), SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, SELECT, and Mesh::totvert.
Referenced by do_lasso_select_paintvert(), do_paintvert_box_select(), mouse_weight_paint_vertex_select(), vert_select_all_exec(), and vert_select_inverse_exec().
void paintvert_flush_flags (Object * ob)
Definition at line 630 of file editface.c.
References CD_ORIGINDEX, Object::derivedFinal, MVert::flag, get_mesh(), DerivedMesh::getNumVerts, DerivedMesh::getVertArray, DerivedMesh::getVertDataArray, i, Mesh::mvert, NULL, and ORIGINDEX_NONE.
Referenced by do_lasso_select_paintvert(), do_paintvert_box_select(), mouse_weight_paint_vertex_select(), paint_vertsel_circle_select(), paintvert_deselect_all_visible(), and vgroup_select_verts().
static void select_linked_tfaces_with_seams (int mode, Mesh * me, unsigned int index) [static]
Definition at line 227 of file editface.c.
References BLI_edgehash_free(), BLI_edgehash_haskey(), BLI_edgehash_insert(), BLI_edgehash_new(), MEdge::flag, MPoly::flag, hash_add_face(), MPoly::loopstart, ME_FACE_SEL, ME_HIDE, ME_SEAM, Mesh::medge, MEM_callocN(), MEM_freeN(), Mesh::mloop, Mesh::mpoly, NULL, MPoly::totloop, Mesh::totpoly, MLoop::v, MEdge::v1, and MEdge::v2.
Referenced by paintface_select_linked().