Blender: BSP_GhostTestApp3D Class Reference
BSP_GhostTestApp3D Class Reference
#include <BSP_GhostTest3D.h>
Classes
struct BSP_RotationSetting
struct BSP_TranslationSetting
Public Member Functions
BSP_GhostTestApp3D ()
bool InitApp ()
void Run ()
~BSP_GhostTestApp3D ()
void SetMesh (MEM_SmartPtr< BSP_TMesh > mesh)
Detailed Description
Definition at line 42 of file BSP_GhostTest3D.h.
Constructor & Destructor Documentation
BSP_GhostTestApp3D::BSP_GhostTestApp3D ()
Definition at line 74 of file BSP_GhostTest3D.cpp.
BSP_GhostTestApp3D::~BSP_GhostTestApp3D ()
Definition at line 526 of file BSP_GhostTest3D.cpp.
References GHOST_ISystem::disposeSystem(), GHOST_ISystem::disposeWindow(), and NULL.
Member Function Documentation
bool BSP_GhostTestApp3D::InitApp ()
Definition at line 244 of file BSP_GhostTest3D.cpp.
References GHOST_ISystem::addEventConsumer(), GHOST_ISystem::createSystem(), GHOST_ISystem::createWindow(), GHOST_ISystem::disposeSystem(), GHOST_ISystem::getSystem(), GHOST_kDrawingContextTypeOpenGL, GHOST_kFailure, GHOST_kWindowStateNormal, max, min, and NULL.
Referenced by main().
void BSP_GhostTestApp3D::Run ()
Definition at line 285 of file BSP_GhostTest3D.cpp.
References GHOST_ISystem::dispatchEvents(), NULL, and GHOST_ISystem::processEvents().
Referenced by main().
void BSP_GhostTestApp3D::SetMesh (MEM_SmartPtr< BSP_TMesh > mesh)
Definition at line 86 of file BSP_GhostTest3D.cpp.
References e_wireframe_shaded.
Referenced by main().
The documentation for this class was generated from the following files:
BSP_GhostTest3D.h
BSP_GhostTest3D.cpp