Blender: SCA_ORController Class Reference
SCA_ORController Class Reference
#include <SCA_ORController.h>
Public Member Functions
SCA_ORController (SCA_IObject *gameobj)
virtual ~SCA_ORController ()
virtual CValue * GetReplica ()
virtual void Trigger (SCA_LogicManager *logicmgr)
Detailed Description
Definition at line 37 of file SCA_ORController.h.
Constructor & Destructor Documentation
SCA_ORController::SCA_ORController (SCA_IObject * gameobj)
Definition at line 45 of file SCA_ORController.cpp.
Referenced by GetReplica().
SCA_ORController::~SCA_ORController () [virtual]
Definition at line 52 of file SCA_ORController.cpp.
Member Function Documentation
CValue * SCA_ORController::GetReplica (void) [virtual]
Implements CValue.
Definition at line 58 of file SCA_ORController.cpp.
References CValue::ProcessReplica(), and SCA_ORController().
void SCA_ORController::Trigger (SCA_LogicManager * logicmgr) [virtual]
Implements SCA_IController.
Definition at line 68 of file SCA_ORController.cpp.
References SCA_LogicManager::AddActiveActuator(), SCA_ISensor::GetState(), i, SCA_IController::m_linkedactuators, and SCA_IController::m_linkedsensors.
The documentation for this class was generated from the following files:
SCA_ORController.h
SCA_ORController.cpp