Blender: node_composite_colorbalance.c File Reference
node_composite_colorbalance.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
DO_INLINE float colorbalance_cdl (float in, float offset, float power, float slope)
DO_INLINE float colorbalance_lgg (float in, float lift_lgg, float gamma_inv, float gain)
static void do_colorbalance_cdl (bNode *node, float *out, float *in)
static void do_colorbalance_cdl_fac (bNode *node, float *out, float *in, float *fac)
static void do_colorbalance_lgg (bNode *node, float *out, float *in)
static void do_colorbalance_lgg_fac (bNode *node, float *out, float *in, float *fac)
static void node_composit_exec_colorbalance (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_colorbalance (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_colorbalance (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_colorbalance_in []
static bNodeSocketTemplate cmp_node_colorbalance_out []
Detailed Description
Definition in file node_composite_colorbalance.c.
Function Documentation
DO_INLINE float colorbalance_cdl (float in, float offset, float power, float slope)
Definition at line 59 of file node_composite_colorbalance.c.
References CLAMP(), and powf.
Referenced by do_colorbalance_cdl(), and do_colorbalance_cdl_fac().
DO_INLINE float colorbalance_lgg (float in, float lift_lgg, float gamma_inv, float gain)
Definition at line 70 of file node_composite_colorbalance.c.
References linearrgb_to_srgb(), powf, and srgb_to_linearrgb().
Referenced by do_colorbalance_lgg(), and do_colorbalance_lgg_fac().
static void do_colorbalance_cdl (bNode * node, float * out, float * in) [static]
Definition at line 84 of file node_composite_colorbalance.c.
References colorbalance_cdl(), NodeColorBalance::gain, NodeColorBalance::gamma, NodeColorBalance::lift, and bNode::storage.
Referenced by node_composit_exec_colorbalance().
static void do_colorbalance_cdl_fac (bNode * node, float * out, float * in, float * fac) [static]
Definition at line 94 of file node_composite_colorbalance.c.
References colorbalance_cdl(), NodeColorBalance::gain, NodeColorBalance::gamma, NodeColorBalance::lift, and bNode::storage.
Referenced by node_composit_exec_colorbalance().
static void do_colorbalance_lgg (bNode * node, float * out, float * in) [static]
Definition at line 105 of file node_composite_colorbalance.c.
References colorbalance_lgg(), NodeColorBalance::gain, NodeColorBalance::gamma_inv, NodeColorBalance::lift_lgg, and bNode::storage.
Referenced by node_composit_exec_colorbalance().
static void do_colorbalance_lgg_fac (bNode * node, float * out, float * in, float * fac) [static]
Definition at line 115 of file node_composite_colorbalance.c.
References colorbalance_lgg(), NodeColorBalance::gain, NodeColorBalance::gamma_inv, NodeColorBalance::lift_lgg, and bNode::storage.
Referenced by node_composit_exec_colorbalance().
static void node_composit_exec_colorbalance (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 126 of file node_composite_colorbalance.c.
References alloc_compbuf(), CB_RGBA, CB_VAL, composit1_pixel_processor(), composit2_pixel_processor(), bNode::custom1, data, bNodeStack::data, do_colorbalance_cdl(), do_colorbalance_cdl_fac(), do_colorbalance_lgg(), do_colorbalance_lgg_fac(), NodeColorBalance::gamma, NodeColorBalance::gamma_inv, NodeColorBalance::lift, NodeColorBalance::lift_lgg, NULL, pass_on_compbuf(), bNode::storage, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_colorbalance().
static void node_composit_init_colorbalance (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 177 of file node_composite_colorbalance.c.
References NodeColorBalance::gain, NodeColorBalance::gamma, NodeColorBalance::lift, MEM_callocN(), and bNode::storage.
Referenced by register_node_type_cmp_colorbalance().
void register_node_type_cmp_colorbalance (bNodeTreeType * ttype)
Definition at line 186 of file node_composite_colorbalance.c.
References CMP_NODE_COLORBALANCE, NODE_CLASS_OP_COLOR, node_composit_exec_colorbalance(), node_composit_init_colorbalance(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_colorbalance_in[] [static]
Initial value:
{
    {SOCK_FLOAT, 1, "Fac",  1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_FACTOR},
    {SOCK_RGBA,1,"Image", 1.0f, 1.0f, 1.0f, 1.0f},
    {-1,0,""}
}
Definition at line 38 of file node_composite_colorbalance.c.
bNodeSocketTemplate cmp_node_colorbalance_out[] [static]
Initial value:
{
    {SOCK_RGBA,0,"Image"},
    {-1,0,""}
}
Definition at line 44 of file node_composite_colorbalance.c.