Blender: physics_ops.c File Reference
physics_ops.c File Reference
physics
#include <stdlib.h>
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_physics.h"
#include "ED_object.h"
#include "BLI_utildefines.h"
#include "physics_intern.h"
Functions
static void operatortypes_particle (void)
static void keymap_particle (wmKeyConfig *keyconf)
static void operatortypes_boids (void)
static void operatortypes_fluid (void)
static void operatortypes_pointcache (void)
static void operatortypes_dynamicpaint (void)
void ED_operatortypes_physics (void)
void ED_keymap_physics (wmKeyConfig *keyconf)
Detailed Description
Definition in file physics_ops.c.
Function Documentation
void ED_keymap_physics (wmKeyConfig * keyconf)
Definition at line 209 of file physics_ops.c.
References keymap_particle().
Referenced by ED_spacetypes_keymap().
void ED_operatortypes_physics (void)
Definition at line 200 of file physics_ops.c.
References operatortypes_boids(), operatortypes_dynamicpaint(), operatortypes_fluid(), operatortypes_particle(), and operatortypes_pointcache().
Referenced by ED_spacetypes_init().
static void keymap_particle (wmKeyConfig * keyconf) [static]
Definition at line 91 of file physics_ops.c.
References AKEY, DELKEY, ED_object_generic_keymap(), FALSE, FKEY, HKEY, IKEY, KKEY, KM_ALT, KM_ANY, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTMOUSE, LKEY, PADMINUS, PADPLUSKEY, PE_poll(), wmKeyMap::poll, wmKeyMapItem::ptr, RNA_boolean_set(), RNA_enum_set(), RNA_string_set(), SEL_INVERT, SEL_TOGGLE, TRUE, WKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), WM_keymap_verify_item(), and XKEY.
Referenced by ED_keymap_physics().
static void operatortypes_boids (void) [static]
Definition at line 144 of file physics_ops.c.
References BOID_OT_rule_add(), BOID_OT_rule_del(), BOID_OT_rule_move_down(), BOID_OT_rule_move_up(), BOID_OT_state_add(), BOID_OT_state_del(), BOID_OT_state_move_down(), BOID_OT_state_move_up(), and WM_operatortype_append().
Referenced by ED_operatortypes_physics().
static void operatortypes_dynamicpaint (void) [static]
Definition at line 179 of file physics_ops.c.
References DPAINT_OT_bake(), DPAINT_OT_output_toggle(), DPAINT_OT_surface_slot_add(), DPAINT_OT_surface_slot_remove(), DPAINT_OT_type_toggle(), and WM_operatortype_append().
Referenced by ED_operatortypes_physics().
static void operatortypes_fluid (void) [static]
Definition at line 159 of file physics_ops.c.
References FLUID_OT_bake(), and WM_operatortype_append().
Referenced by ED_operatortypes_physics().
static void operatortypes_particle (void) [static]
Definition at line 49 of file physics_ops.c.
References OBJECT_OT_particle_system_add(), OBJECT_OT_particle_system_remove(), PARTICLE_OT_brush_edit(), PARTICLE_OT_connect_hair(), PARTICLE_OT_delete(), PARTICLE_OT_disconnect_hair(), PARTICLE_OT_dupliob_copy(), PARTICLE_OT_dupliob_move_down(), PARTICLE_OT_dupliob_move_up(), PARTICLE_OT_dupliob_remove(), PARTICLE_OT_edited_clear(), PARTICLE_OT_hide(), PARTICLE_OT_mirror(), PARTICLE_OT_new(), PARTICLE_OT_new_target(), PARTICLE_OT_particle_edit_toggle(), PARTICLE_OT_rekey(), PARTICLE_OT_remove_doubles(), PARTICLE_OT_reveal(), PARTICLE_OT_select_all(), PARTICLE_OT_select_less(), PARTICLE_OT_select_linked(), PARTICLE_OT_select_more(), PARTICLE_OT_select_roots(), PARTICLE_OT_select_tips(), PARTICLE_OT_subdivide(), PARTICLE_OT_target_move_down(), PARTICLE_OT_target_move_up(), PARTICLE_OT_target_remove(), PARTICLE_OT_weight_set(), and WM_operatortype_append().
Referenced by ED_operatortypes_physics().
static void operatortypes_pointcache (void) [static]
Definition at line 166 of file physics_ops.c.
References PTCACHE_OT_add(), PTCACHE_OT_bake(), PTCACHE_OT_bake_all(), PTCACHE_OT_bake_from_cache(), PTCACHE_OT_free_bake(), PTCACHE_OT_free_bake_all(), PTCACHE_OT_remove(), and WM_operatortype_append().
Referenced by ED_operatortypes_physics().