Blender: LOD_ExternBufferEditor Class Reference
LOD_ExternBufferEditor Class Reference
#include <LOD_ExternBufferEditor.h>
Public Member Functions
void CopyModifiedVerts (LOD_ManMesh2 &mesh, const std::vector< LOD_VertexInd > &mod_vertices)
void CopyModifiedFaces (LOD_ManMesh2 &mesh, const std::vector< LOD_FaceInd > &mod_faces)
void CopyBackVertex (LOD_VertexInd vi)
void CopyBackFace (LOD_FaceInd fi)
Static Public Member Functions
static LOD_ExternBufferEditor * New (LOD_Decimation_InfoPtr extern_info)
Detailed Description
Copyright (C) 2001 NaN Technologies B.V.
Definition at line 51 of file LOD_ExternBufferEditor.h.
Member Function Documentation
void LOD_ExternBufferEditor::CopyBackFace (LOD_FaceInd fi) [inline]
Definition at line 134 of file LOD_ExternBufferEditor.h.
References LOD_Decimation_Info::face_num, and LOD_Decimation_Info::triangle_index_buffer.
Referenced by LOD_ManMesh2::DeleteFace().
void LOD_ExternBufferEditor::CopyBackVertex (LOD_VertexInd vi) [inline]
Definition at line 113 of file LOD_ExternBufferEditor.h.
References LOD_Decimation_Info::vertex_buffer, and LOD_Decimation_Info::vertex_num.
Referenced by LOD_ManMesh2::DeleteVertex().
void LOD_ExternBufferEditor::CopyModifiedFaces (LOD_ManMesh2 & mesh, const std::vector< LOD_FaceInd > & mod_faces) [inline]
Definition at line 90 of file LOD_ExternBufferEditor.h.
References LOD_ManMesh2::FaceSet(), and LOD_Decimation_Info::triangle_index_buffer.
Referenced by LOD_ManMesh2::DeleteVertex().
void LOD_ExternBufferEditor::CopyModifiedVerts (LOD_ManMesh2 & mesh, const std::vector< LOD_VertexInd > & mod_vertices) [inline]
Definition at line 69 of file LOD_ExternBufferEditor.h.
References LOD_Decimation_Info::vertex_buffer, and LOD_ManMesh2::VertexSet().
static LOD_ExternBufferEditor* LOD_ExternBufferEditor::New (LOD_Decimation_InfoPtr extern_info) [inline, static]
Definition at line 58 of file LOD_ExternBufferEditor.h.
References NULL.
Referenced by LOD_DecimationClass::New().
The documentation for this class was generated from the following file:
LOD_ExternBufferEditor.h