Blender: GHOST_ISystemPaths Class Reference
GHOST_ISystemPaths Class Reference
#include <GHOST_ISystemPaths.h>
Public Member Functions
virtual const GHOST_TUns8 * getSystemDir () const =0
virtual const GHOST_TUns8 * getUserDir () const =0
virtual const GHOST_TUns8 * getBinaryDir () const =0
virtual void addToSystemRecentFiles (const char *filename) const =0
Static Public Member Functions
static GHOST_TSuccess create ()
static GHOST_TSuccess dispose ()
static GHOST_ISystemPaths * get ()
Protected Member Functions
GHOST_ISystemPaths ()
virtual ~GHOST_ISystemPaths ()
Detailed Description
Definition at line 36 of file GHOST_ISystemPaths.h.
Constructor & Destructor Documentation
GHOST_ISystemPaths::GHOST_ISystemPaths () [inline, protected]
Constructor. Protected default constructor to force use of static createSystem member.
Definition at line 62 of file GHOST_ISystemPaths.h.
virtual GHOST_ISystemPaths::~GHOST_ISystemPaths () [inline, protected, virtual]
Destructor. Protected default constructor to force use of static dispose member.
Definition at line 68 of file GHOST_ISystemPaths.h.
Member Function Documentation
virtual void GHOST_ISystemPaths::addToSystemRecentFiles (const char * filename) const [pure virtual]
Add the file to the operating system most recently used files
Implemented in GHOST_SystemPaths, GHOST_SystemPathsCarbon, GHOST_SystemPathsCocoa, GHOST_SystemPathsWin32, and GHOST_SystemPathsX11.
Referenced by GHOST_addToSystemRecentFiles().
GHOST_TSuccess GHOST_ISystemPaths::create () [static]
Creates the one and only system.
Returns:
An indication of success.
Definition at line 60 of file GHOST_ISystemPaths.cpp.
References GHOST_kFailure, and GHOST_kSuccess.
Referenced by get(), and GHOST_CreateSystemPaths().
GHOST_TSuccess GHOST_ISystemPaths::dispose () [static]
Disposes the one and only system.
Returns:
An indication of success.
Definition at line 85 of file GHOST_ISystemPaths.cpp.
References GHOST_kFailure, and GHOST_kSuccess.
Referenced by GHOST_DisposeSystemPaths().
GHOST_ISystemPaths * GHOST_ISystemPaths::get () [static]
Returns a pointer to the one and only system (nil if it hasn't been created).
Returns:
A pointer to the system.
Definition at line 98 of file GHOST_ISystemPaths.cpp.
References create().
Referenced by GHOST_addToSystemRecentFiles(), GHOST_getBinaryDir(), GHOST_getSystemDir(), and GHOST_getUserDir().
virtual const GHOST_TUns8* GHOST_ISystemPaths::getBinaryDir () const [pure virtual]
Determine the directory of the current binary
Returns:
Unsigned char string pointing to the binary dir
Implemented in GHOST_SystemPaths, GHOST_SystemPathsCarbon, GHOST_SystemPathsCocoa, GHOST_SystemPathsWin32, and GHOST_SystemPathsX11.
Referenced by GHOST_getBinaryDir().
virtual const GHOST_TUns8* GHOST_ISystemPaths::getSystemDir () const [pure virtual]
Determine the base dir in which shared resources are located. It will first try to use "unpack and run" path, then look for properly installed path, not including versioning.
Returns:
Unsigned char string pointing to system dir (eg /usr/share/blender/).
Implemented in GHOST_SystemPaths, GHOST_SystemPathsCarbon, GHOST_SystemPathsCocoa, GHOST_SystemPathsWin32, and GHOST_SystemPathsX11.
Referenced by GHOST_getSystemDir().
virtual const GHOST_TUns8* GHOST_ISystemPaths::getUserDir () const [pure virtual]
Determine the base dir in which user configuration is stored, not including versioning. If needed, it will create the base directory.
Returns:
Unsigned char string pointing to user dir (eg ~/.blender/).
Implemented in GHOST_SystemPaths, GHOST_SystemPathsCarbon, GHOST_SystemPathsCocoa, GHOST_SystemPathsWin32, and GHOST_SystemPathsX11.
Referenced by GHOST_getUserDir().
The documentation for this class was generated from the following files:
GHOST_ISystemPaths.h
GHOST_ISystemPaths.cpp