Blender: KX_SlowParentRelation Class Reference
KX_SlowParentRelation Class Reference
#include <KX_SG_NodeRelationships.h>
Public Member Functions
bool UpdateChildCoordinates (SG_Spatial *child, const SG_Spatial *parent, bool &parentUpdated)
SG_ParentRelation * NewCopy ()
MT_Scalar GetTimeOffset ()
void SetTimeOffset (MT_Scalar relaxation)
~KX_SlowParentRelation ()
bool IsSlowRelation ()
Static Public Member Functions
static KX_SlowParentRelation * New (MT_Scalar relaxation)
Detailed Description
Definition at line 155 of file KX_SG_NodeRelationships.h.
Constructor & Destructor Documentation
KX_SlowParentRelation::~KX_SlowParentRelation ()
Definition at line 291 of file KX_SG_NodeRelationships.cpp.
Member Function Documentation
MT_Scalar KX_SlowParentRelation::GetTimeOffset () [inline]
Definition at line 191 of file KX_SG_NodeRelationships.h.
bool KX_SlowParentRelation::IsSlowRelation () [inline, virtual]
Need this to see if we are able to adjust time-offset from the python api
Reimplemented from SG_ParentRelation.
Definition at line 203 of file KX_SG_NodeRelationships.h.
KX_SlowParentRelation * KX_SlowParentRelation::New (MT_Scalar relaxation) [static]
Allocate and construct a new KX_VertexParentRelation on the heap.
Slow parent relationship
Definition at line 175 of file KX_SG_NodeRelationships.cpp.
Referenced by BL_ConvertBlenderObjects().
SG_ParentRelation * KX_SlowParentRelation::NewCopy () [virtual]
Method inherited from KX_ParentRelation
Implements SG_ParentRelation.
Definition at line 275 of file KX_SG_NodeRelationships.cpp.
void KX_SlowParentRelation::SetTimeOffset (MT_Scalar relaxation) [inline]
Definition at line 195 of file KX_SG_NodeRelationships.h.
bool KX_SlowParentRelation::UpdateChildCoordinates (SG_Spatial * child, const SG_Spatial * parent, bool & parentUpdated) [virtual]
Method inherited from KX_ParentRelation
Implements SG_ParentRelation.
Definition at line 187 of file KX_SG_NodeRelationships.cpp.
References SG_IObject::ActivateRecheduleUpdateCallback(), SG_Spatial::ClearModified(), SG_Spatial::GetLocalOrientation(), SG_Spatial::GetLocalPosition(), SG_Spatial::GetLocalScale(), MT_Matrix3x3::getRotation(), SG_Spatial::GetWorldOrientation(), SG_Spatial::GetWorldPosition(), SG_Spatial::GetWorldScaling(), MT_assert, NULL, MT_Matrix3x3::setRotation(), SG_Spatial::SetWorldOrientation(), SG_Spatial::SetWorldPosition(), SG_Spatial::SetWorldScale(), and MT_Quaternion::slerp().
The documentation for this class was generated from the following files:
KX_SG_NodeRelationships.h
KX_SG_NodeRelationships.cpp