Blender: btGjkEpaSolver2 Struct Reference
btGjkEpaSolver2 Struct Reference
btGjkEpaSolver contributed under zlib by Nathanael Presson
#include <btGjkEpa2.h>
Classes
struct sResults
Static Public Member Functions
static int StackSizeRequirement ()
static bool Distance (const btConvexShape *shape0, const btTransform &wtrs0, const btConvexShape *shape1, const btTransform &wtrs1, const btVector3 &guess, sResults &results)
static bool Penetration (const btConvexShape *shape0, const btTransform &wtrs0, const btConvexShape *shape1, const btTransform &wtrs1, const btVector3 &guess, sResults &results, bool usemargins=true)
static btScalar SignedDistance (const btVector3 &position, btScalar margin, const btConvexShape *shape, const btTransform &wtrs, sResults &results)
static bool SignedDistance (const btConvexShape *shape0, const btTransform &wtrs0, const btConvexShape *shape1, const btTransform &wtrs1, const btVector3 &guess, sResults &results)
Detailed Description
btGjkEpaSolver contributed under zlib by Nathanael Presson
Definition at line 30 of file btGjkEpa2.h.
Member Function Documentation
bool btGjkEpaSolver2::Distance (const btConvexShape * shape0, const btTransform & wtrs0, const btConvexShape * shape1, const btTransform & wtrs1, const btVector3 & guess, sResults & results) [static]
Definition at line 823 of file btGjkEpa2.cpp.
References btGjkEpaSolver2::sResults::distance, gjkepa2_impl::GJK::Evaluate(), GJK_MIN_DISTANCE, i, gjkepa2_impl::Initialize(), gjkepa2_impl::GJK::eStatus::Inside, gjkepa2_impl::GJK::m_simplex, btGjkEpaSolver2::sResults::normal, p, btGjkEpaSolver2::sResults::status, gjkepa2_impl::MinkowskiDiff::Support(), gjkepa2_impl::GJK::eStatus::Valid, and btGjkEpaSolver2::sResults::witnesses.
Referenced by btGjkEpaPenetrationDepthSolver::calcPenDepth().
bool btGjkEpaSolver2::Penetration (const btConvexShape * shape0, const btTransform & wtrs0, const btConvexShape * shape1, const btTransform & wtrs1, const btVector3 & guess, sResults & results, bool usemargins = true) [static]
Definition at line 861 of file btGjkEpa2.cpp.
References gjkepa2_impl::GJK::sSimplex::c, btGjkEpaSolver2::sResults::distance, gjkepa2_impl::EPA::Evaluate(), gjkepa2_impl::GJK::Evaluate(), gjkepa2_impl::EPA::eStatus::Failed, gjkepa2_impl::GJK::eStatus::Failed, i, gjkepa2_impl::Initialize(), gjkepa2_impl::GJK::eStatus::Inside, gjkepa2_impl::EPA::m_depth, gjkepa2_impl::EPA::m_normal, gjkepa2_impl::EPA::m_result, btGjkEpaSolver2::sResults::normal, gjkepa2_impl::GJK::sSimplex::p, gjkepa2_impl::GJK::sSimplex::rank, btGjkEpaSolver2::sResults::status, gjkepa2_impl::MinkowskiDiff::Support(), and btGjkEpaSolver2::sResults::witnesses.
Referenced by btGjkEpaPenetrationDepthSolver::calcPenDepth().
btScalar btGjkEpaSolver2::SignedDistance (const btVector3 & position, btScalar margin, const btConvexShape * shape, const btTransform & wtrs, sResults & results) [static]
Definition at line 907 of file btGjkEpa2.cpp.
References gjkepa2_impl::GJK::Evaluate(), i, gjkepa2_impl::Initialize(), gjkepa2_impl::GJK::eStatus::Inside, length(), gjkepa2_impl::GJK::m_ray, gjkepa2_impl::GJK::m_simplex, btGjkEpaSolver2::sResults::normal, p, SIMD_EPSILON, SIMD_INFINITY, gjkepa2_impl::MinkowskiDiff::Support(), gjkepa2_impl::GJK::eStatus::Valid, and btGjkEpaSolver2::sResults::witnesses.
Referenced by btSparseSdf< 3 >::DistanceToShape(), btSoftColliders::CollideCL_SS::Process(), and btSoftColliders::CollideCL_RS::Process().
bool btGjkEpaSolver2::SignedDistance (const btConvexShape * shape0, const btTransform & wtrs0, const btConvexShape * shape1, const btTransform & wtrs1, const btVector3 & guess, sResults & results) [static]
Definition at line 959 of file btGjkEpa2.cpp.
References Distance.
int btGjkEpaSolver2::StackSizeRequirement () [static]
Definition at line 817 of file btGjkEpa2.cpp.
The documentation for this struct was generated from the following files:
btGjkEpa2.h
btGjkEpa2.cpp