Blender: btPerturbedContactResult Struct Reference
btPerturbedContactResult Struct Reference
Public Member Functions
btPerturbedContactResult (btManifoldResult *originalResult, const btTransform &transformA, const btTransform &transformB, const btTransform &unPerturbedTransform, bool perturbA, btIDebugDraw *debugDrawer)
virtual ~btPerturbedContactResult ()
virtual void addContactPoint (const btVector3 &normalOnBInWorld, const btVector3 &pointInWorld, btScalar orgDepth)
Public Attributes
btManifoldResult * m_originalManifoldResult
btTransform m_transformA
btTransform m_transformB
btTransform m_unPerturbedTransform
bool m_perturbA
btIDebugDraw * m_debugDrawer
Detailed Description
Definition at line 227 of file btConvexConvexAlgorithm.cpp.
Constructor & Destructor Documentation
btPerturbedContactResult::btPerturbedContactResult (btManifoldResult * originalResult, const btTransform & transformA, const btTransform & transformB, const btTransform & unPerturbedTransform, bool perturbA, btIDebugDraw * debugDrawer) [inline]
Definition at line 237 of file btConvexConvexAlgorithm.cpp.
virtual btPerturbedContactResult::~btPerturbedContactResult () [inline, virtual]
Definition at line 246 of file btConvexConvexAlgorithm.cpp.
Member Function Documentation
virtual void btPerturbedContactResult::addContactPoint (const btVector3 & normalOnBInWorld, const btVector3 & pointInWorld, btScalar orgDepth) [inline, virtual]
Reimplemented from btManifoldResult.
Definition at line 250 of file btConvexConvexAlgorithm.cpp.
References btManifoldResult::addContactPoint(), dot(), btIDebugDraw::drawLine(), btIDebugDraw::drawSphere(), btTransform::inverse(), m_debugDrawer, m_originalManifoldResult, m_perturbA, m_transformA, m_transformB, and m_unPerturbedTransform.
Member Data Documentation
btIDebugDraw* btPerturbedContactResult::m_debugDrawer
Definition at line 234 of file btConvexConvexAlgorithm.cpp.
Referenced by addContactPoint().
btManifoldResult* btPerturbedContactResult::m_originalManifoldResult
Definition at line 229 of file btConvexConvexAlgorithm.cpp.
Referenced by addContactPoint().
bool btPerturbedContactResult::m_perturbA
Definition at line 233 of file btConvexConvexAlgorithm.cpp.
Referenced by addContactPoint().
btTransform btPerturbedContactResult::m_transformA
Definition at line 230 of file btConvexConvexAlgorithm.cpp.
Referenced by addContactPoint().
btTransform btPerturbedContactResult::m_transformB
Definition at line 231 of file btConvexConvexAlgorithm.cpp.
Referenced by addContactPoint().
btTransform btPerturbedContactResult::m_unPerturbedTransform
Definition at line 232 of file btConvexConvexAlgorithm.cpp.
Referenced by addContactPoint().
The documentation for this struct was generated from the following file:
btConvexConvexAlgorithm.cpp