Blender: EXP_C-Api.cpp File Reference
EXP_C-Api.cpp File Reference
Expressions
#include "EXP_C-Api.h"
#include "IntValue.h"
#include "BoolValue.h"
#include "StringValue.h"
#include "ErrorValue.h"
#include "InputParser.h"
Functions
EXP_ValueHandle EXP_CreateInt (int innie)
EXP_ValueHandle EXP_CreateBool (int innie)
EXP_ValueHandle EXP_CreateString (const char *str)
void EXP_SetName (EXP_ValueHandle inval, const char *newname)
EXP_ValueHandle EXP_ParseInput (const char *inputtext)
void EXP_ReleaseValue (EXP_ValueHandle inval)
int EXP_IsValid (EXP_ValueHandle inval)
void EXP_SetProperty (EXP_ValueHandle destinationval, const char *propname, EXP_ValueHandle propval)
const char * EXP_GetText (EXP_ValueHandle inval)
EXP_ValueHandle EXP_GetProperty (EXP_ValueHandle inval, const char *propname)
Detailed Description
Definition in file EXP_C-Api.cpp.
Function Documentation
EXP_ValueHandle EXP_CreateBool (int innie)
Definition at line 46 of file EXP_C-Api.cpp.
EXP_ValueHandle EXP_CreateInt (int innie)
Definition at line 39 of file EXP_C-Api.cpp.
EXP_ValueHandle EXP_CreateString (const char * str)
Definition at line 53 of file EXP_C-Api.cpp.
EXP_ValueHandle EXP_GetProperty (EXP_ValueHandle inval, const char * propname)
Definition at line 120 of file EXP_C-Api.cpp.
const char* EXP_GetText (EXP_ValueHandle inval)
Definition at line 113 of file EXP_C-Api.cpp.
int EXP_IsValid (EXP_ValueHandle inval)
Definition at line 96 of file EXP_C-Api.cpp.
EXP_ValueHandle EXP_ParseInput (const char * inputtext)
Definition at line 69 of file EXP_C-Api.cpp.
References CExpression::Calculate(), NULL, CParser::ProcessText(), and CExpression::Release().
void EXP_ReleaseValue (EXP_ValueHandle inval)
Definition at line 89 of file EXP_C-Api.cpp.
void EXP_SetName (EXP_ValueHandle inval, const char * newname)
Definition at line 61 of file EXP_C-Api.cpp.
void EXP_SetProperty (EXP_ValueHandle destinationval, const char * propname, EXP_ValueHandle propval)
Definition at line 104 of file EXP_C-Api.cpp.