Blender: node_exec.h File Reference
node_exec.h File Reference
nodes
#include "DNA_listBase.h"
#include "BLI_utildefines.h"
#include "BKE_node.h"
#include "RNA_types.h"
Classes
struct bNodeExec
struct bNodeTreeExec
struct bNodeThreadStack
Typedefs
typedef struct bNodeExec bNodeExec
typedef struct bNodeTreeExec bNodeTreeExec
typedef struct bNodeThreadStack bNodeThreadStack
Functions
struct bNodeStack * node_get_socket_stack (struct bNodeStack *stack, struct bNodeSocket *sock)
void node_get_stack (struct bNode *node, struct bNodeStack *stack, struct bNodeStack **in, struct bNodeStack **out)
void node_init_input_index (struct bNodeSocket *sock, int *index)
void node_init_output_index (struct bNodeSocket *sock, int *index)
struct bNodeTreeExec * ntree_exec_begin (struct bNodeTree *ntree)
void ntree_exec_end (struct bNodeTreeExec *exec)
void ntreeExecNodes (struct bNodeTreeExec *exec, void *callerdata, int thread)
struct bNodeThreadStack * ntreeGetThreadStack (struct bNodeTreeExec *exec, int thread)
void ntreeReleaseThreadStack (struct bNodeThreadStack *nts)
void ntreeExecThreadNodes (struct bNodeTreeExec *exec, struct bNodeThreadStack *nts, void *callerdata, int thread)
Detailed Description
Definition in file node_exec.h.
Typedef Documentation
typedef struct bNodeExec bNodeExec
typedef struct bNodeThreadStack bNodeThreadStack
typedef struct bNodeTreeExec bNodeTreeExec
Function Documentation
struct bNodeStack* node_get_socket_stack (struct bNodeStack * stack, struct bNodeSocket * sock) [read]
Definition at line 47 of file node_exec.c.
References bNodeSocket::stack_index.
Referenced by freeExecutableNode(), group_copy_inputs(), group_copy_outputs(), group_gpu_copy_inputs(), group_gpu_move_outputs(), group_initexec(), group_move_outputs(), node_get_stack(), ntreeCompositBeginExecTree(), ntreeCompositEndExecTree(), and setup_stack().
void node_get_stack (struct bNode * node, struct bNodeStack * stack, struct bNodeStack ** in, struct bNodeStack ** out)
Definition at line 52 of file node_exec.c.
References ListBase::first, bNode::inputs, bNodeSocket::next, node_get_socket_stack(), and bNode::outputs.
Referenced by exec_composite_node(), ntreeExecGPUNodes(), ntreeExecNodes(), ntreeExecThreadNodes(), and setExecutableNodes().
void node_init_input_index (struct bNodeSocket * sock, int * index)
Definition at line 70 of file node_exec.c.
References bNodeLink::fromsock, bNodeSocket::link, and bNodeSocket::stack_index.
Referenced by ntree_exec_begin().
void node_init_output_index (struct bNodeSocket * sock, int * index)
Definition at line 80 of file node_exec.c.
References bNodeSocket::stack_index.
Referenced by ntree_exec_begin().
struct bNodeTreeExec* ntree_exec_begin (struct bNodeTree * ntree) [read]
Definition at line 127 of file node_exec.c.
References bNodeExec::data, exec(), ListBase::first, bNodeLink::flag, bNodeStack::hasinput, bNodeStack::hasoutput, bNodeTree::init, bNodeType::initexecfunc, bNodeTree::inputs, bNode::inputs, bNodeSocket::link, MEM_callocN(), MEM_freeN(), bNode::need_exec, bNodeSocket::next, bNodeExec::node, node_init_input_index(), node_init_output_index(), NODE_LINK_VALID, bNodeTreeExec::nodeexec, bNodeTreeExec::nodetree, NTREE_TYPE_INIT, ntreeGetDependencyList(), ntreeInitTypes(), bNode::outputs, bNodeTree::outputs, setup_stack(), bNodeTreeExec::stack, bNode::stack_index, bNodeTreeExec::stacksize, bNodeTreeExec::totnodes, and bNode::typeinfo.
Referenced by ntreeCompositBeginExecTree(), ntreeShaderBeginExecTree(), and ntreeTexBeginExecTree().
void ntree_exec_end (struct bNodeTreeExec * exec)
Definition at line 217 of file node_exec.c.
References bNodeExec::data, bNodeType::freeexecfunc, MEM_freeN(), bNodeExec::node, bNodeTreeExec::nodeexec, bNodeTreeExec::stack, and bNode::typeinfo.
Referenced by ntreeCompositEndExecTree(), ntreeShaderEndExecTree(), and ntreeTexEndExecTree().
void ntreeExecNodes (struct bNodeTreeExec * exec, void * callerdata, int thread)
Definition at line 265 of file node_exec.c.
References bNodeExec::data, bNodeType::execfunc, MAX_SOCKET, bNode::need_exec, bNodeType::newexecfunc, bNodeExec::node, node_get_stack(), bNodeTreeExec::nodeexec, bNodeTreeExec::stack, and bNode::typeinfo.
Referenced by group_execute().
void ntreeExecThreadNodes (struct bNodeTreeExec * exec, struct bNodeThreadStack * nts, void * callerdata, int thread)
Definition at line 291 of file node_exec.c.
References bNodeExec::data, bNodeType::execfunc, MAX_SOCKET, bNode::need_exec, bNodeType::newexecfunc, bNodeExec::node, node_get_stack(), bNodeTreeExec::nodeexec, bNodeThreadStack::stack, and bNode::typeinfo.
Referenced by group_execute(), ntreeShaderExecTree(), and ntreeTexExecTree().
struct bNodeThreadStack* ntreeGetThreadStack (struct bNodeTreeExec * exec, int thread) [read]
Definition at line 238 of file node_exec.c.
References BLI_addtail(), ListBase::first, MEM_callocN(), MEM_dupallocN(), bNodeThreadStack::next, bNodeTreeExec::stack, bNodeThreadStack::stack, bNodeTreeExec::threadstack, and bNodeThreadStack::used.
Referenced by group_execute(), ntreeShaderExecTree(), and ntreeTexExecTree().
void ntreeReleaseThreadStack (struct bNodeThreadStack * nts)
Definition at line 260 of file node_exec.c.
References bNodeThreadStack::used.
Referenced by group_execute(), ntreeShaderExecTree(), and ntreeTexExecTree().