Blender: ED_gpencil.h File Reference
ED_gpencil.h File Reference
Editors
Classes
struct tGPspoint
Defines
#define GPENCIL_SKETCH_SESSIONS_ON(scene) ((scene)->toolsettings->gpencil_flags & GP_TOOL_FLAG_PAINTSESSIONS_ON)
Typedefs
typedef struct tGPspoint tGPspoint
Functions
struct bGPdata ** gpencil_data_get_pointers (struct bContext *C, struct PointerRNA *ptr)
struct bGPdata * gpencil_data_get_active (struct bContext *C)
struct bGPdata * gpencil_data_get_active_v3d (struct Scene *scene)
void ED_keymap_gpencil (struct wmKeyConfig *keyconf)
void ED_operatortypes_gpencil (void)
void draw_gpencil_2dimage (struct bContext *C, struct ImBuf *ibuf)
void draw_gpencil_view2d (struct bContext *C, short onlyv2d)
void draw_gpencil_view3d (struct Scene *scene, struct View3D *v3d, struct ARegion *ar, short only3d)
void gpencil_panel_standard (const struct bContext *C, struct Panel *pa)
short gplayer_frames_looper (struct bGPDlayer *gpl, struct Scene *scene, short(*gpf_cb)(struct bGPDframe *, struct Scene *))
void gplayer_make_cfra_list (struct bGPDlayer *gpl, ListBase *elems, short onlysel)
short is_gplayer_frame_selected (struct bGPDlayer *gpl)
void set_gplayer_frame_selection (struct bGPDlayer *gpl, short mode)
void select_gpencil_frames (struct bGPDlayer *gpl, short select_mode)
void select_gpencil_frame (struct bGPDlayer *gpl, int selx, short select_mode)
void borderselect_gplayer_frames (struct bGPDlayer *gpl, float min, float max, short select_mode)
void delete_gplayer_frames (struct bGPDlayer *gpl)
void duplicate_gplayer_frames (struct bGPDlayer *gpd)
void free_gpcopybuf (void)
void copy_gpdata (void)
void paste_gpdata (void)
void snap_gplayer_frames (struct bGPDlayer *gpl, short mode)
void mirror_gplayer_frames (struct bGPDlayer *gpl, short mode)
int ED_gpencil_session_active (void)
int ED_undo_gpencil_step (struct bContext *C, int step, const char *name)
Detailed Description
Definition in file ED_gpencil.h.
Define Documentation
#define GPENCIL_SKETCH_SESSIONS_ON (scene) ((scene)->toolsettings->gpencil_flags & GP_TOOL_FLAG_PAINTSESSIONS_ON)
Definition at line 63 of file ED_gpencil.h.
Referenced by gpencil_draw_modal(), and gpencil_draw_status_indicators().
Typedef Documentation
typedef struct tGPspoint tGPspoint
Function Documentation
void borderselect_gplayer_frames (struct bGPDlayer * gpl, float min, float max, short select_mode)
Definition at line 196 of file editaction_gpencil.c.
References ListBase::first, bGPDframe::framenum, bGPDlayer::frames, gpframe_select(), IN_RANGE, bGPDframe::next, and NULL.
Referenced by actkeys_select_leftright(), borderselect_action(), and markers_selectkeys_between().
void copy_gpdata (void)
void delete_gplayer_frames (struct bGPDlayer * gpl)
Definition at line 214 of file editaction_gpencil.c.
References ListBase::first, bGPDframe::flag, bGPDlayer::frames, GP_FRAME_SELECT, gpencil_layer_delframe(), bGPDframe::next, and NULL.
Referenced by delete_action_keys().
void draw_gpencil_2dimage (struct bContext * C, struct ImBuf * ibuf)
Definition at line 672 of file drawgpencil.c.
References CFRA, CTX_data_scene(), CTX_wm_area(), CTX_wm_region(), View2D::cur, ELEM, ListBase::first, gp_draw_data(), GP_DRAWDATA_IEDITHACK, GP_DRAWDATA_NOSTATUS, GP_DRAWDATA_ONLYI2D, GP_DRAWDATA_ONLYV2D, gpencil_data_get_active(), SpaceSeq::mainb, NULL, SEQ_DRAW_IMG_IMBUF, SEQ_ZOOM_FAC, SPACE_CLIP, SPACE_IMAGE, SPACE_SEQ, ScrArea::spacedata, ScrArea::spacetype, ARegion::v2d, ARegion::winx, ARegion::winy, wmOrtho2(), ImBuf::x, rctf::xmax, rctf::xmin, ImBuf::y, rctf::ymax, and rctf::ymin.
Referenced by clip_draw_grease_pencil(), and draw_image_grease_pencil().
void draw_gpencil_view2d (struct bContext * C, short onlyv2d)
Definition at line 748 of file drawgpencil.c.
References CFRA, CTX_data_scene(), CTX_wm_area(), CTX_wm_region(), ELEM, gp_draw_data(), GP_DRAWDATA_IEDITHACK, GP_DRAWDATA_NOSTATUS, GP_DRAWDATA_ONLYV2D, gpencil_data_get_active(), NULL, SPACE_CLIP, SPACE_IMAGE, ScrArea::spacetype, ARegion::winx, and ARegion::winy.
Referenced by clip_draw_grease_pencil(), draw_image_grease_pencil(), and drawnodespace().
void draw_gpencil_view3d (struct Scene * scene, struct View3D * v3d, struct ARegion * ar, short only3d)
Definition at line 775 of file drawgpencil.c.
References BLI_copy_rcti_rctf(), CFRA, ED_view3d_calc_camera_border(), G, G_RENDER_OGL, gp_draw_data(), GP_DRAWDATA_NOSTATUS, GP_DRAWDATA_ONLY3D, gpencil_data_get_active_v3d(), NULL, RegionView3D::persp, ARegion::regiondata, RV3D_CAMOB, TRUE, ARegion::winx, ARegion::winy, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by draw_depth_gpencil(), ED_view3d_draw_offscreen(), view3d_main_area_draw_info(), and view3d_main_area_draw_objects().
void duplicate_gplayer_frames (struct bGPDlayer * gpd)
Definition at line 232 of file editaction_gpencil.c.
References BLI_insertlinkafter(), ListBase::first, bGPDframe::flag, bGPDlayer::frames, GP_FRAME_SELECT, gpencil_frame_duplicate(), bGPDframe::next, and NULL.
Referenced by duplicate_action_keys().
int ED_gpencil_session_active (void)
Definition at line 61 of file gpencil_undo.c.
References ListBase::first, and NULL.
Referenced by ed_undo_step(), gp_draw_data(), gp_session_initdata(), and gpencil_draw_poll().
void ED_keymap_gpencil (struct wmKeyConfig * keyconf)
Definition at line 51 of file gpencil_ops.c.
References DKEY, GP_PAINTMODE_DRAW, GP_PAINTMODE_DRAW_POLY, GP_PAINTMODE_DRAW_STRAIGHT, GP_PAINTMODE_ERASER, KM_CTRL, KM_PRESS, LEFTMOUSE, wmKeyMapItem::ptr, RIGHTMOUSE, RNA_enum_set(), WM_keymap_add_item(), and WM_keymap_find().
Referenced by ED_spacetypes_keymap().
void ED_operatortypes_gpencil (void)
Definition at line 73 of file gpencil_ops.c.
References GPENCIL_OT_active_frame_delete(), GPENCIL_OT_convert(), GPENCIL_OT_data_add(), GPENCIL_OT_data_unlink(), GPENCIL_OT_draw(), GPENCIL_OT_layer_add(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
int ED_undo_gpencil_step (struct bContext * C, int step, const char * name)
Definition at line 66 of file gpencil_undo.c.
References BLI_addtail(), ListBase::first, free_gpencil_layers(), bGPundonode::gpd, gpencil_data_get_pointers(), gpencil_layer_duplicate(), ListBase::last, bGPdata::layers, NA_EDITED, bGPundonode::name, NC_SCREEN, ND_GPENCIL, bGPDlayer::next, bGPundonode::next, NULL, OPERATOR_FINISHED, bGPundonode::prev, and WM_event_add_notifier().
Referenced by ed_undo_step().
void free_gpcopybuf (void)
struct bGPdata* gpencil_data_get_active (struct bContext * C) [read]
Definition at line 165 of file gpencil_edit.c.
References gpencil_data_get_pointers(), and NULL.
Referenced by draw_gpencil_2dimage(), draw_gpencil_view2d(), gp_actframe_delete_exec(), gp_actframe_delete_poll(), gp_convert_layer_exec(), and gp_convert_poll().
struct bGPdata* gpencil_data_get_active_v3d (struct Scene * scene) [read]
Definition at line 172 of file gpencil_edit.c.
References Scene::basact, Scene::gpd, Object::gpd, NULL, and Base::object.
Referenced by draw_gpencil_view3d().
struct bGPdata** gpencil_data_get_pointers (struct bContext * C, struct PointerRNA * ptr) [read]
Definition at line 80 of file gpencil_edit.c.
References CTX_data_active_object(), CTX_data_scene(), CTX_wm_area(), CTX_wm_screen(), CTX_wm_space_data(), ED_space_clip(), bNodeTree::gpd, Object::gpd, MovieClip::gpd, SpaceImage::gpd, Object::id, MovieClip::id, bNodeTree::id, SpaceNode::nodetree, NULL, RNA_id_pointer_create(), RNA_pointer_create(), RNA_SpaceImageEditor, SPACE_CLIP, SPACE_IMAGE, SPACE_NODE, SPACE_SEQ, SPACE_VIEW3D, and ScrArea::spacetype.
Referenced by ED_undo_gpencil_step(), gp_add_poll(), gp_data_add_exec(), gp_data_unlink_exec(), gp_data_unlink_poll(), gp_layer_add_exec(), gp_session_initdata(), gpencil_data_get_active(), gpencil_draw_poll(), and gpencil_panel_standard().
void gpencil_panel_standard (const struct bContext * C, struct Panel * pa)
short gplayer_frames_looper (struct bGPDlayer * gpl, struct Scene * scene, short(*)(struct bGPDframe *, struct Scene *) gpf_cb)
void gplayer_make_cfra_list (struct bGPDlayer * gpl, ListBase * elems, short onlysel)
Definition at line 88 of file editaction_gpencil.c.
References BLI_addtail(), CfraElem::cfra, ELEM, ListBase::first, bGPDframe::flag, bGPDframe::framenum, bGPDlayer::frames, GP_FRAME_SELECT, MEM_callocN(), bGPDframe::next, NULL, and CfraElem::sel.
Referenced by columnselect_action_keys().
short is_gplayer_frame_selected (struct bGPDlayer * gpl)
Definition at line 114 of file editaction_gpencil.c.
References ListBase::first, bGPDframe::flag, bGPDlayer::frames, GP_FRAME_SELECT, bGPDframe::next, and NULL.
Referenced by deselect_action_keys().
void mirror_gplayer_frames (struct bGPDlayer * gpl, short mode)
void paste_gpdata (void)
void select_gpencil_frame (struct bGPDlayer * gpl, int selx, short select_mode)
Definition at line 178 of file editaction_gpencil.c.
References ListBase::first, bGPDframe::framenum, bGPDlayer::frames, gpframe_select(), bGPDframe::next, and NULL.
Referenced by actkeys_mselect_column(), actkeys_mselect_single(), and columnselect_action_keys().
void select_gpencil_frames (struct bGPDlayer * gpl, short select_mode)
Definition at line 152 of file editaction_gpencil.c.
References ListBase::first, bGPDlayer::frames, gpframe_select(), bGPDframe::next, and NULL.
Referenced by set_gplayer_frame_selection().
void set_gplayer_frame_selection (struct bGPDlayer * gpl, short mode)
Definition at line 167 of file editaction_gpencil.c.
References NULL, and select_gpencil_frames().
Referenced by deselect_action_keys().
void snap_gplayer_frames (struct bGPDlayer * gpl, short mode)