Blender: kernel_light.h File Reference
kernel_light.h File Reference
Classes
struct LightSample
Typedefs
typedef CCL_NAMESPACE_BEGIN
struct LightSample LightSample
Functions
__device float3 disk_light_sample (float3 v, float randu, float randv)
__device float3 distant_light_sample (float3 D, float size, float randu, float randv)
__device float3 sphere_light_sample (float3 P, float3 center, float size, float randu, float randv)
__device float3 area_light_sample (float3 axisu, float3 axisv, float randu, float randv)
__device float3 background_light_sample (KernelGlobals *kg, float randu, float randv, float *pdf)
__device float background_light_pdf (KernelGlobals *kg, float3 direction)
__device void regular_light_sample (KernelGlobals *kg, int point, float randu, float randv, float3 P, LightSample *ls, float *pdf)
__device float regular_light_pdf (KernelGlobals *kg, const float3 Ng, const float3 I, float t)
__device void triangle_light_sample (KernelGlobals *kg, int prim, int object, float randu, float randv, LightSample *ls)
__device float triangle_light_pdf (KernelGlobals *kg, const float3 Ng, const float3 I, float t)
__device int light_distribution_sample (KernelGlobals *kg, float randt)
__device void light_sample (KernelGlobals *kg, float randt, float randu, float randv, float3 P, LightSample *ls, float *pdf)
__device float light_sample_pdf (KernelGlobals *kg, LightSample *ls, float3 I, float t)
__device void light_select (KernelGlobals *kg, int index, float randu, float randv, float3 P, LightSample *ls, float *pdf)
__device float light_select_pdf (KernelGlobals *kg, LightSample *ls, float3 I, float t)
Typedef Documentation
typedef CCL_NAMESPACE_BEGIN struct LightSample LightSample
Function Documentation
__device float3 area_light_sample (float3 axisu, float3 axisv, float randu, float randv)
Definition at line 54 of file kernel_light.h.
Referenced by regular_light_sample().
__device float background_light_pdf (KernelGlobals * kg, float3 direction)
Definition at line 138 of file kernel_light.h.
References clamp, direction_to_equirectangular(), kernel_data, kernel_tex_fetch, M_PI_F, sinf, float2::x, and float2::y.
Referenced by indirect_background().
__device float3 background_light_sample (KernelGlobals * kg, float randu, float randv, float * pdf)
Definition at line 62 of file kernel_light.h.
References equirectangular_to_direction(), kernel_assert, kernel_data, kernel_tex_fetch, M_PI_F, max, sinf, step(), float2::x, and float2::y.
Referenced by regular_light_sample().
__device float3 disk_light_sample (float3 v, float randu, float randv)
Definition at line 34 of file kernel_light.h.
References make_orthonormals(), and to_unit_disk().
Referenced by distant_light_sample(), and sphere_light_sample().
__device float3 distant_light_sample (float3 D, float size, float randu, float randv)
Definition at line 44 of file kernel_light.h.
References disk_light_sample(), and normalize().
Referenced by regular_light_sample().
__device int light_distribution_sample (KernelGlobals * kg, float randt)
Definition at line 286 of file kernel_light.h.
References kernel_assert, kernel_data, kernel_tex_fetch, len(), and max.
Referenced by light_sample().
__device void light_sample (KernelGlobals * kg, float randt, float randu, float randv, float3 P, LightSample * ls, float * pdf)
Definition at line 316 of file kernel_light.h.
References __float_as_int(), LightSample::D, FLT_MAX, kernel_tex_fetch, light_distribution_sample(), normalize_len(), LightSample::P, regular_light_sample(), LightSample::t, triangle_light_sample(), float4::w, and float4::y.
Referenced by direct_emission().
__device float light_sample_pdf (KernelGlobals * kg, LightSample * ls, float3 I, float t)
Definition at line 339 of file kernel_light.h.
References LightSample::Ng, LightSample::prim, regular_light_pdf(), and triangle_light_pdf().
Referenced by direct_emission().
__device void light_select (KernelGlobals * kg, int index, float randu, float randv, float3 P, LightSample * ls, float * pdf)
Definition at line 351 of file kernel_light.h.
References regular_light_sample().
Referenced by direct_emission().
__device float light_select_pdf (KernelGlobals * kg, LightSample * ls, float3 I, float t)
Definition at line 356 of file kernel_light.h.
References LightSample::Ng, and regular_light_pdf().
__device float regular_light_pdf (KernelGlobals * kg, const float3 Ng, const float3 I, float t)
Definition at line 235 of file kernel_light.h.
References dot(), FLT_MAX, and kernel_data.
Referenced by light_sample_pdf(), and light_select_pdf().
__device void regular_light_sample (KernelGlobals * kg, int point, float randu, float randv, float3 P, LightSample * ls, float * pdf)
Definition at line 169 of file kernel_light.h.
References __float_as_int(), area_light_sample(), background_light_sample(), LightSample::D, D(), distant_light_sample(), FLT_MAX, kernel_tex_fetch, LIGHT_BACKGROUND, LIGHT_DISTANT, LIGHT_POINT, LIGHT_SIZE, make_float3(), LightSample::Ng, normalize(), LightSample::object, LightSample::P, LightSample::prim, LightSample::shader, size(), sphere_light_sample(), LightSample::t, LightSample::type, float4::w, float4::x, float4::y, and float4::z.
Referenced by light_sample(), and light_select().
__device float3 sphere_light_sample (float3 P, float3 center, float size, float randu, float randv)
Definition at line 49 of file kernel_light.h.
References disk_light_sample(), normalize(), and size().
Referenced by regular_light_sample().
__device float triangle_light_pdf (KernelGlobals * kg, const float3 Ng, const float3 I, float t)
Definition at line 273 of file kernel_light.h.
References dot(), fabsf, and kernel_data.
Referenced by indirect_emission(), and light_sample_pdf().
__device void triangle_light_sample (KernelGlobals * kg, int prim, int object, float randu, float randv, LightSample * ls)
Definition at line 253 of file kernel_light.h.
References LIGHT_AREA, LightSample::Ng, LightSample::object, object_normal_transform(), object_position_transform(), LightSample::P, LightSample::prim, LightSample::shader, LightSample::t, triangle_normal_MT(), triangle_sample_MT(), and LightSample::type.
Referenced by light_sample().