Blender: node_shader_valToRgb.c File Reference
node_shader_valToRgb.c File Reference
shdnodes
#include "node_shader_util.h"
Functions
static void node_shader_exec_valtorgb (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_shader_init_valtorgb (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static int gpu_shader_valtorgb (GPUMaterial *mat, bNode *node, GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_valtorgb (bNodeTreeType *ttype)
static void node_shader_exec_rgbtobw (void *UNUSED(data), bNode *UNUSED(node), bNodeStack **in, bNodeStack **out)
static int gpu_shader_rgbtobw (GPUMaterial *mat, bNode *UNUSED(node), GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_rgbtobw (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_valtorgb_in []
static bNodeSocketTemplate sh_node_valtorgb_out []
static bNodeSocketTemplate sh_node_rgbtobw_in []
static bNodeSocketTemplate sh_node_rgbtobw_out []
Detailed Description
Definition in file node_shader_valToRgb.c.
Function Documentation
static int gpu_shader_rgbtobw (GPUMaterial * mat, bNode * UNUSEDnode, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 110 of file node_shader_valToRgb.c.
References GPU_stack_link().
Referenced by register_node_type_sh_rgbtobw().
static int gpu_shader_valtorgb (GPUMaterial * mat, bNode * node, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 65 of file node_shader_valToRgb.c.
References colorband_table_RGBA(), GPU_stack_link(), GPU_texture(), size(), and bNode::storage.
Referenced by register_node_type_sh_valtorgb().
static void node_shader_exec_rgbtobw (void * UNUSEDdata, bNode * UNUSEDnode, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 102 of file node_shader_valToRgb.c.
References bNodeStack::vec.
Referenced by register_node_type_sh_rgbtobw().
static void node_shader_exec_valtorgb (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 46 of file node_shader_valToRgb.c.
References do_colorband(), nodestack_get_vec(), SOCK_FLOAT, bNode::storage, and bNodeStack::vec.
Referenced by register_node_type_sh_valtorgb().
static void node_shader_init_valtorgb (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 60 of file node_shader_valToRgb.c.
References add_colorband(), and bNode::storage.
Referenced by register_node_type_sh_valtorgb().
void register_node_type_sh_rgbtobw (bNodeTreeType * ttype)
Definition at line 115 of file node_shader_valToRgb.c.
References gpu_shader_rgbtobw(), NODE_CLASS_CONVERTOR, NODE_NEW_SHADING, NODE_OLD_SHADING, node_shader_exec_rgbtobw(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_RGBTOBW.
Referenced by registerShaderNodes().
void register_node_type_sh_valtorgb (bNodeTreeType * ttype)
Definition at line 74 of file node_shader_valToRgb.c.
References gpu_shader_valtorgb(), NODE_CLASS_CONVERTOR, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_valtorgb(), node_shader_init_valtorgb(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and SH_NODE_VALTORGB.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_rgbtobw_in[] [static]
Initial value:
 {
   {    SOCK_RGBA, 1, "Color",          0.5f, 0.5f, 0.5f, 1.0f, 0.0f, 1.0f},
   {    -1, 0, ""   }
}
Definition at line 92 of file node_shader_valToRgb.c.
bNodeSocketTemplate sh_node_rgbtobw_out[] [static]
Initial value:
 {
   {    SOCK_FLOAT, 0, "Val",           0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f},
   {    -1, 0, ""   }
}
Definition at line 96 of file node_shader_valToRgb.c.
bNodeSocketTemplate sh_node_valtorgb_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Fac",           0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_FACTOR},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_shader_valToRgb.c.
bNodeSocketTemplate sh_node_valtorgb_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Color"},
    {   SOCK_FLOAT, 0, "Alpha"},
    {   -1, 0, ""   }
}
Definition at line 40 of file node_shader_valToRgb.c.