Blender: ED_mball.h File Reference
ED_mball.h File Reference
Editors
Functions
void ED_operatortypes_metaball (void)
void ED_keymap_metaball (struct wmKeyConfig *keyconf)
struct MetaElem * add_metaball_primitive (struct bContext *C, float mat[4][4], int type, int newname)
int mouse_mball (struct bContext *C, const int mval[2], int extend)
void free_editMball (struct Object *obedit)
void make_editMball (struct Object *obedit)
void load_editMball (struct Object *obedit)
void undo_push_mball (struct bContext *C, const char *name)
Detailed Description
Definition in file ED_mball.h.
Function Documentation
struct MetaElem* add_metaball_primitive (struct bContext * C, float mat[4][4], int type, int newname) [read]
Referenced by object_metaball_add_exec().
void ED_keymap_metaball (struct wmKeyConfig * keyconf)
Definition at line 57 of file mball_ops.c.
References AKEY, DELKEY, DKEY, ED_object_generic_keymap(), ED_operator_editmball(), FALSE, HKEY, IKEY, KM_ALT, KM_CTRL, KM_PRESS, KM_SHIFT, wmKeyMap::poll, wmKeyMapItem::ptr, RNA_boolean_set(), RNA_enum_set(), SEL_INVERT, SEL_TOGGLE, TRUE, WM_keymap_add_item(), WM_keymap_find(), and XKEY.
Referenced by ED_spacetypes_keymap().
void ED_operatortypes_metaball (void)
Definition at line 45 of file mball_ops.c.
References MBALL_OT_delete_metaelems(), MBALL_OT_duplicate_metaelems(), MBALL_OT_hide_metaelems(), MBALL_OT_reveal_metaelems(), MBALL_OT_select_all(), MBALL_OT_select_random_metaelems(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
void free_editMball (struct Object * obedit)
Definition at line 68 of file mball_edit.c.
References Object::data, MetaBall::editelems, MetaBall::lastelem, and NULL.
Referenced by ED_object_exit_editmode().
void load_editMball (struct Object * obedit)
Referenced by ED_object_exit_editmode().
void make_editMball (struct Object * obedit)
Definition at line 78 of file mball_edit.c.
References Object::data, MetaBall::editelems, MetaBall::elems, ListBase::first, MetaBall::lastelem, MetaElem::next, and SELECT.
Referenced by ED_object_enter_editmode().
int mouse_mball (struct bContext * C, const int mval[2], int extend)
Definition at line 418 of file mball_edit.c.
References CTX_data_edit_object(), Object::data, MetaBall::editelems, ListBase::first, MetaElem::flag, MetaBall::lastelem, MAXPICKBUF, MB_SCALE_RAD, NC_GEOM, ND_SELECT, MetaElem::next, NULL, MetaElem::selcol1, MetaElem::selcol2, SELECT, view3d_opengl_select(), view3d_set_viewcontext(), and WM_event_add_notifier().
Referenced by view3d_select_invoke().
void undo_push_mball (struct bContext * C, const char * name)
Definition at line 584 of file mball_edit.c.
References editMball_to_undoMball(), free_undoMball(), get_data(), NULL, undo_editmode_push(), and undoMball_to_editMball().
Referenced by ED_undo_push().