Blender: iTaSC::WSDLSSolver Class Reference
iTaSC::WSDLSSolver Class Reference
#include <WSDLSSolver.hpp>
Public Member Functions
WSDLSSolver ()
virtual ~WSDLSSolver ()
virtual bool init (unsigned int _nq, unsigned int _nc, const std::vector< bool > &gc)
virtual bool solve (const e_matrix &A, const e_vector &Wy, const e_vector &ydot, const e_matrix &Wq, e_vector &qdot, e_scalar &nlcoef)
virtual void setParam (SolverParam param, double value)
Detailed Description
Definition at line 15 of file WSDLSSolver.hpp.
Constructor & Destructor Documentation
iTaSC::WSDLSSolver::WSDLSSolver ()
Definition at line 17 of file WSDLSSolver.cpp.
iTaSC::WSDLSSolver::~WSDLSSolver () [virtual]
Definition at line 25 of file WSDLSSolver.cpp.
Member Function Documentation
bool iTaSC::WSDLSSolver::init (unsigned int _nq, unsigned int _nc, const std::vector< bool > & gc) [virtual]
Implements iTaSC::Solver.
Definition at line 28 of file WSDLSSolver.cpp.
References e_zero_matrix, e_zero_vector, max, and min.
virtual void iTaSC::WSDLSSolver::setParam (SolverParam param, double value) [inline, virtual]
Implements iTaSC::Solver.
Definition at line 29 of file WSDLSSolver.hpp.
References iTaSC::Solver::DLS_QMAX.
bool iTaSC::WSDLSSolver::solve (const e_matrix & A, const e_vector & Wy, const e_vector & ydot, const e_matrix & Wq, e_vector & qdot, e_scalar & nlcoef) [virtual]
Implements iTaSC::Solver.
Definition at line 57 of file WSDLSSolver.cpp.
References e_scalar, KDL::epsilon, fabs(), i, M, N, norm(), sqrt(), and KDL::svd_eigen_HH().
The documentation for this class was generated from the following files:
WSDLSSolver.hpp
WSDLSSolver.cpp