Blender: GHOST_WindowWin32.cpp File Reference
GHOST_WindowWin32.cpp File Reference
GHOST API
#include <string.h>
#include "GHOST_WindowWin32.h"
#include "GHOST_SystemWin32.h"
#include "GHOST_DropTargetWin32.h"
#include "utfconv.h"
#include "utf_winfunc.h"
#include <GL/glew.h>
#include <GL/wglew.h>
#include <math.h>
Defines
#define M_PI 3.1415926536
#define WGL_SAMPLE_BUFERS_ARB 0x2041
#define WGL_SAMPLES_ARB 0x2042
Functions
static int WeightPixelFormat (PIXELFORMATDESCRIPTOR &pfd)
static int EnumPixelFormats (HDC hdc)
static int is_crappy_intel_card (void)
static GHOST_TUns8 uns8ReverseBits (GHOST_TUns8 ch)
static GHOST_TUns16 uns16ReverseBits (GHOST_TUns16 shrt)
Variables
static PIXELFORMATDESCRIPTOR sPreferredFormat
Detailed Description
Definition in file GHOST_WindowWin32.cpp.
Define Documentation
#define M_PI 3.1415926536
Copyright (C) 2001 NaN Technologies B.V.
Author:
Maarten Gribnau
Date:
May 10, 2001
Definition at line 54 of file GHOST_WindowWin32.cpp.
Referenced by GHOST_WindowWin32::processWin32TabletEvent().
#define WGL_SAMPLE_BUFERS_ARB 0x2041
Definition at line 58 of file GHOST_WindowWin32.cpp.
#define WGL_SAMPLES_ARB 0x2042
Definition at line 59 of file GHOST_WindowWin32.cpp.
Referenced by GHOST_WindowWin32::initMultisample().
Function Documentation
static int EnumPixelFormats (HDC hdc) [static]
Definition at line 1314 of file GHOST_WindowWin32.cpp.
References i, sPreferredFormat, and WeightPixelFormat().
Referenced by GHOST_WindowWin32::installDrawingContext().
static int is_crappy_intel_card (void) [static]
Definition at line 113 of file GHOST_WindowWin32.cpp.
Referenced by GHOST_WindowWin32::installDrawingContext(), and GHOST_WindowWin32::swapBuffers().
static GHOST_TUns16 uns16ReverseBits (GHOST_TUns16 shrt) [static]
Reverse the bits in a GHOST_TUns16
Definition at line 1198 of file GHOST_WindowWin32.cpp.
static GHOST_TUns8 uns8ReverseBits (GHOST_TUns8 ch) [static]
Reverse the bits in a GHOST_TUns8
Definition at line 1189 of file GHOST_WindowWin32.cpp.
Referenced by GHOST_WindowWin32::setWindowCustomCursorShape().
static int WeightPixelFormat (PIXELFORMATDESCRIPTOR & pfd) [static]
Definition at line 1280 of file GHOST_WindowWin32.cpp.
Referenced by EnumPixelFormats().
Variable Documentation
PIXELFORMATDESCRIPTOR sPreferredFormat [static]
Initial value:
 {
    sizeof(PIXELFORMATDESCRIPTOR),
    1,
    PFD_SUPPORT_OPENGL |
    PFD_DRAW_TO_WINDOW |
    PFD_SWAP_COPY |
    PFD_DOUBLEBUFFER,
    PFD_TYPE_RGBA,
    32,
    0, 0, 0, 0, 0, 0,
    0,
    0,
    0,
    0, 0, 0, 0,
    32,
    0,
    0,
    PFD_MAIN_PLANE,
    0,
    0, 0, 0
}
Definition at line 86 of file GHOST_WindowWin32.cpp.
Referenced by EnumPixelFormats(), and GHOST_WindowWin32::installDrawingContext().