Blender: blf_util.c File Reference
blf_util.c File Reference
blenfont
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "blf_internal.h"
#include "BLI_string_utf8.h"
Functions
unsigned int blf_next_p2 (unsigned int x)
unsigned int blf_hash (unsigned int val)
Detailed Description
Definition in file blf_util.c.
Function Documentation
unsigned int blf_hash (unsigned int val)
Definition at line 52 of file blf_util.c.
Referenced by blf_glyph_add(), and blf_glyph_search().
unsigned int blf_next_p2 (unsigned int x)
Definition at line 40 of file blf_util.c.
Referenced by blf_glyph_cache_texture().