Blender: node_shader_geom.c File Reference
node_shader_geom.c File Reference
shdnodes
#include "node_shader_util.h"
#include "DNA_customdata_types.h"
Functions
static void node_shader_exec_geom (void *data, bNode *node, bNodeStack **UNUSED(in), bNodeStack **out)
static void node_shader_init_geometry (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static int gpu_shader_geom (GPUMaterial *mat, bNode *node, GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_geom (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_geom_out []
Detailed Description
Definition in file node_shader_geom.c.
Function Documentation
static int gpu_shader_geom (GPUMaterial * mat, bNode * node, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 128 of file node_shader_geom.c.
References CD_MCOL, CD_MTFACE, CD_ORCO, NodeGeometry::colname, GPU_attribute(), GPU_builtin(), GPU_INVERSE_VIEW_MATRIX, GPU_stack_link(), GPU_VIEW_NORMAL, GPU_VIEW_POSITION, bNode::storage, and NodeGeometry::uvname.
Referenced by register_node_type_sh_geom().
static void node_shader_exec_geom (void * data, bNode * node, bNodeStack ** UNUSEDin, bNodeStack ** out) [static]
Definition at line 54 of file node_shader_geom.c.
References ShadeInput::actuv, ShadeInputCol::col, copy_v3_v3(), bNodeStack::data, bNodeStack::datatype, GEOM_OUT_FRONTBACK, GEOM_OUT_GLOB, GEOM_OUT_LOCAL, GEOM_OUT_NORMAL, GEOM_OUT_ORCO, GEOM_OUT_UV, GEOM_OUT_VCOL, GEOM_OUT_VCOL_ALPHA, GEOM_OUT_VIEW, i, NS_OSA_VALUES, NS_OSA_VECTORS, bNode::storage, ShadeInput::uv, and bNodeStack::vec.
Referenced by register_node_type_sh_geom().
static void node_shader_init_geometry (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 123 of file node_shader_geom.c.
References MEM_callocN(), and bNode::storage.
Referenced by register_node_type_sh_geom().
void register_node_type_sh_geom (bNodeTreeType * ttype)
Definition at line 141 of file node_shader_geom.c.
References gpu_shader_geom(), NODE_CLASS_INPUT, node_copy_standard_storage(), node_free_standard_storage(), NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_geom(), node_shader_init_geometry(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_GEOMETRY.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_geom_out[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 0, "Global"},
    {   SOCK_VECTOR, 0, "Local"},
    {   SOCK_VECTOR, 0, "View"},
    {   SOCK_VECTOR, 0, "Orco"},
    {   SOCK_VECTOR, 0, "UV"},
    {   SOCK_VECTOR, 0, "Normal"},
    {   SOCK_RGBA,   0, "Vertex Color"},
    {   SOCK_FLOAT,   0, "Vertex Alpha"},
    {   SOCK_FLOAT,   0, "Front/Back"},
    {   -1, 0, ""   }
}
Definition at line 40 of file node_shader_geom.c.