Blender: space_userpref.c File Reference
space_userpref.c File Reference
user preferences
#include <string.h>
#include <stdio.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "ED_screen.h"
#include "ED_space_api.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_view2d.h"
#include "userpref_intern.h"
Functions
static SpaceLink * userpref_new (const bContext *UNUSED(C))
static void userpref_free (SpaceLink *UNUSED(sl))
static void userpref_init (struct wmWindowManager *UNUSED(wm), ScrArea *UNUSED(sa))
static SpaceLink * userpref_duplicate (SpaceLink *sl)
static void userpref_main_area_init (wmWindowManager *wm, ARegion *ar)
static void userpref_main_area_draw (const bContext *C, ARegion *ar)
static void userpref_operatortypes (void)
static void userpref_keymap (struct wmKeyConfig *UNUSED(keyconf))
static void userpref_header_area_init (wmWindowManager *UNUSED(wm), ARegion *ar)
static void userpref_header_area_draw (const bContext *C, ARegion *ar)
static void userpref_main_area_listener (ARegion *UNUSED(ar), wmNotifier *UNUSED(wmn))
static void userpref_header_listener (ARegion *UNUSED(ar), wmNotifier *UNUSED(wmn))
void ED_spacetype_userpref (void)
Detailed Description
Definition in file space_userpref.c.
Function Documentation
void ED_spacetype_userpref (void)
Definition at line 156 of file space_userpref.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizey, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_USERPREF, SpaceType::spaceid, userpref_duplicate(), userpref_free(), userpref_header_area_draw(), userpref_header_area_init(), userpref_header_listener(), userpref_init(), userpref_keymap(), userpref_main_area_draw(), userpref_main_area_init(), userpref_main_area_listener(), userpref_new(), and userpref_operatortypes().
Referenced by ED_spacetypes_init().
static SpaceLink* userpref_duplicate (SpaceLink * sl) [static]
Definition at line 94 of file space_userpref.c.
References MEM_dupallocN().
Referenced by ED_spacetype_userpref().
static void userpref_free (SpaceLink * UNUSEDsl) [static]
Definition at line 81 of file space_userpref.c.
Referenced by ED_spacetype_userpref().
static void userpref_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 134 of file space_userpref.c.
References ED_region_header().
Referenced by ED_spacetype_userpref().
static void userpref_header_area_init (wmWindowManager * UNUSEDwm, ARegion * ar) [static]
Definition at line 129 of file space_userpref.c.
References ED_region_header_init().
Referenced by ED_spacetype_userpref().
static void userpref_header_listener (ARegion * UNUSEDar, wmNotifier * UNUSEDwmn) [static]
Definition at line 144 of file space_userpref.c.
Referenced by ED_spacetype_userpref().
static void userpref_init (struct wmWindowManager * UNUSEDwm, ScrArea * UNUSEDsa) [static]
Definition at line 89 of file space_userpref.c.
Referenced by ED_spacetype_userpref().
static void userpref_keymap (struct wmKeyConfig * UNUSEDkeyconf) [static]
Definition at line 123 of file space_userpref.c.
Referenced by ED_spacetype_userpref().
static void userpref_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 111 of file space_userpref.c.
References ED_region_panels(), NULL, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_PANELS_UI, ARegion::winx, and ARegion::winy.
Referenced by ED_spacetype_userpref().
static void userpref_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 106 of file space_userpref.c.
References ED_region_panels_init().
Referenced by ED_spacetype_userpref().
static void userpref_main_area_listener (ARegion * UNUSEDar, wmNotifier * UNUSEDwmn) [static]
Definition at line 139 of file space_userpref.c.
Referenced by ED_spacetype_userpref().
static SpaceLink* userpref_new (const bContext * UNUSEDC) [static]
Definition at line 56 of file space_userpref.c.
References ARegion::alignment, BLI_addtail(), MEM_callocN(), SpaceUserPref::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_USERPREF, and SpaceUserPref::spacetype.
Referenced by ED_spacetype_userpref().
static void userpref_operatortypes (void) [static]
Definition at line 119 of file space_userpref.c.
Referenced by ED_spacetype_userpref().