Blender: reeb.h File Reference
reeb.h File Reference
armature
#include "DNA_listBase.h"
#include "BLI_graph.h"
Classes
struct ReebGraph
struct EmbedBucket
struct ReebNode
struct ReebEdge
struct ReebArc
struct ReebArcIterator
Defines
#define WITH_BF_REEB
#define REEB_MAX_MULTI_LEVEL 10
Typedefs
typedef struct ReebGraph ReebGraph
typedef struct EmbedBucket EmbedBucket
typedef struct ReebNode ReebNode
typedef struct ReebEdge ReebEdge
typedef struct ReebArc ReebArc
typedef struct ReebArcIterator ReebArcIterator
Functions
int weightToHarmonic (struct EditMesh *em, struct EdgeIndex *indexed_edges)
int weightFromDistance (struct EditMesh *em, struct EdgeIndex *indexed_edges)
int weightFromLoc (struct EditMesh *me, int axis)
void weightToVCol (struct EditMesh *em, int index)
void arcToVCol (struct ReebGraph *rg, struct EditMesh *em, int index)
void angleToVCol (struct EditMesh *em, int index)
void renormalizeWeight (struct EditMesh *em, float newmax)
ReebGraph * generateReebGraph (struct EditMesh *me, int subdivisions)
ReebGraph * newReebGraph (void)
void initArcIterator (BArcIterator *iter, struct ReebArc *arc, struct ReebNode *head)
void initArcIterator2 (BArcIterator *iter, struct ReebArc *arc, int start, int end)
void initArcIteratorStart (BArcIterator *iter, struct ReebArc *arc, struct ReebNode *head, int start)
void filterNullReebGraph (ReebGraph *rg)
int filterSmartReebGraph (ReebGraph *rg, float threshold)
void repositionNodes (ReebGraph *rg)
void postprocessGraph (ReebGraph *rg, char mode)
void removeNormalNodes (ReebGraph *rg)
void sortNodes (ReebGraph *rg)
void sortArcs (ReebGraph *rg)
void verifyBuckets (ReebGraph *rg)
void verifyFaces (ReebGraph *rg)
void verifyArcs (ReebGraph *rg)
void verifyNodeDegree (ReebGraph *rg)
ReebGraph * BIF_ReebGraphFromEditMesh (void)
ReebGraph * BIF_ReebGraphMultiFromEditMesh (struct bContext *C)
void BIF_flagMultiArcs (ReebGraph *rg, int flag)
void BIF_GlobalReebGraphFromEditMesh (void)
void BIF_GlobalReebFree (void)
ReebNode * BIF_otherNodeFromIndex (ReebArc *arc, ReebNode *node)
ReebNode * BIF_NodeFromIndex (ReebArc *arc, ReebNode *node)
ReebNode * BIF_lowestLevelNode (ReebNode *node)
ReebGraph * BIF_graphForMultiNode (ReebGraph *rg, ReebNode *node)
void REEB_freeGraph (ReebGraph *rg)
void REEB_freeArc (BArc *barc)
void REEB_exportGraph (ReebGraph *rg, int count)
void REEB_draw (void)
Detailed Description
Definition in file reeb.h.
Define Documentation
#define REEB_MAX_MULTI_LEVEL 10
Definition at line 181 of file reeb.h.
Referenced by BIF_ReebGraphMultiFromEditMesh().
#define WITH_BF_REEB
Definition at line 31 of file reeb.h.
Typedef Documentation
typedef struct EmbedBucket EmbedBucket
typedef struct ReebArc ReebArc
typedef struct ReebArcIterator ReebArcIterator
typedef struct ReebEdge ReebEdge
typedef struct ReebGraph ReebGraph
typedef struct ReebNode ReebNode
Function Documentation
void angleToVCol (struct EditMesh * em, int index)
void arcToVCol (struct ReebGraph * rg, struct EditMesh * em, int index)
void BIF_flagMultiArcs (ReebGraph * rg, int flag)
Definition at line 230 of file reeb.c.
References BLI_flagArcs(), and ReebGraph::link_up.
Referenced by retargetGraphs().
void BIF_GlobalReebFree (void)
void BIF_GlobalReebGraphFromEditMesh (void)
ReebGraph* BIF_graphForMultiNode (ReebGraph * rg, ReebNode * node)
Definition at line 406 of file reeb.c.
References ReebGraph::link_up, ReebGraph::multi_level, and ReebNode::multi_level.
Referenced by matchMultiResolutionArc(), and matchMultiResolutionNode().
ReebNode* BIF_lowestLevelNode (ReebNode * node)
Definition at line 319 of file reeb.c.
References ReebNode::link_down.
ReebNode* BIF_NodeFromIndex (ReebArc * arc, ReebNode * node)
Definition at line 314 of file reeb.c.
References ReebArc::head, ReebNode::index, and ReebArc::tail.
Referenced by testFlipArc().
ReebNode* BIF_otherNodeFromIndex (ReebArc * arc, ReebNode * node)
Definition at line 309 of file reeb.c.
References ReebArc::head, ReebNode::index, and ReebArc::tail.
Referenced by retargetSubgraph().
ReebGraph* BIF_ReebGraphFromEditMesh (void)
ReebGraph* BIF_ReebGraphMultiFromEditMesh (struct bContext * C)
Definition at line 3390 of file reeb.c.
References BLI_buildAdjacencyList(), BLI_calcGraphLength(), BLI_markdownSymmetry(), CTX_data_edit_object(), CTX_data_scene(), data, Object::data, filterNullReebGraph(), ListBase::first, generateReebGraph(), i, BGraph::length, MEM_freeN(), BGraph::nodes, NULL, REEB_MAX_MULTI_LEVEL, removeNormalNodes(), renormalizeWeight(), repositionNodes(), SKGEN_FILTER_SMART, SKGEN_HARMONIC, ToolSettings::skgen_options, ToolSettings::skgen_postpro, ToolSettings::skgen_postpro_passes, ToolSettings::skgen_resolution, ToolSettings::skgen_symmetry_limit, ToolSettings::skgen_threshold_external, ToolSettings::skgen_threshold_internal, Scene::toolsettings, weightFromDistance(), and weightToHarmonic().
Referenced by BIF_retargetArmature().
void filterNullReebGraph (ReebGraph * rg)
Referenced by BIF_ReebGraphMultiFromEditMesh().
int filterSmartReebGraph (ReebGraph * rg, float threshold)
ReebGraph* generateReebGraph (struct EditMesh * me, int subdivisions)
Referenced by BIF_ReebGraphMultiFromEditMesh().
void initArcIterator (BArcIterator * iter, struct ReebArc * arc, struct ReebNode * head)
Definition at line 3189 of file reeb.c.
References ReebArcIterator::arc, ReebArc::bcount, ReebArcIterator::end, ReebArc::head, ReebArcIterator::index, initIteratorFct(), ReebArcIterator::length, ReebArcIterator::start, and ReebArcIterator::stride.
Referenced by REEB_AxialSymmetry(), REEB_RadialSymmetry(), retargetArctoArcAggresive(), and retargetArctoArcLength().
void initArcIterator2 (BArcIterator * iter, struct ReebArc * arc, int start, int end)
Definition at line 3244 of file reeb.c.
References abs(), ReebArcIterator::arc, ReebArcIterator::end, ReebArcIterator::index, initIteratorFct(), ReebArcIterator::length, ReebArcIterator::start, and ReebArcIterator::stride.
void initArcIteratorStart (BArcIterator * iter, struct ReebArc * arc, struct ReebNode * head, int start)
Definition at line 3214 of file reeb.c.
References ReebArcIterator::arc, ReebArc::bcount, ReebArcIterator::end, ReebArc::head, ReebArcIterator::index, initIteratorFct(), ReebArcIterator::length, ReebArcIterator::start, and ReebArcIterator::stride.
ReebGraph* newReebGraph (void)
Definition at line 213 of file reeb.c.
References ReebGraph::axial_symmetry, BLI_edgehash_new(), ReebGraph::emap, ReebGraph::free_arc, ReebGraph::free_node, MEM_callocN(), NULL, ReebGraph::radial_symmetry, REEB_AxialSymmetry(), REEB_freeArc(), REEB_RadialSymmetry(), and ReebGraph::totnodes.
void postprocessGraph (ReebGraph * rg, char mode)
void REEB_draw (void)
void REEB_exportGraph (ReebGraph * rg, int count)
void REEB_freeArc (BArc * barc)
Definition at line 166 of file reeb.c.
References BLI_freelistN(), BLI_ghash_free(), ReebArc::buckets, ReebArc::edges, ReebArc::faces, MEM_freeN(), and NULL.
Referenced by newReebGraph(), REEB_freeGraph(), and sk_retargetStroke().
void REEB_freeGraph (ReebGraph * rg)
Definition at line 180 of file reeb.c.
References ReebGraph::arcs, BLI_edgehash_free(), BLI_freelistN(), BLI_freeNode(), ReebGraph::emap, ListBase::first, ReebGraph::link_up, MEM_freeN(), ReebArc::next, next, ReebNode::next, ReebGraph::nodes, NULL, REEB_freeArc(), and REEB_freeGraph().
Referenced by REEB_freeGraph(), and RIG_freeRigGraph().
void removeNormalNodes (ReebGraph * rg)
Referenced by BIF_ReebGraphMultiFromEditMesh().
void renormalizeWeight (struct EditMesh * em, float newmax)
Referenced by BIF_ReebGraphMultiFromEditMesh().
void repositionNodes (ReebGraph * rg)
Referenced by BIF_ReebGraphMultiFromEditMesh().
void sortArcs (ReebGraph * rg)
void sortNodes (ReebGraph * rg)
void verifyArcs (ReebGraph * rg)
void verifyBuckets (ReebGraph * rg)
void verifyFaces (ReebGraph * rg)
void verifyNodeDegree (ReebGraph * rg)
int weightFromDistance (struct EditMesh * em, struct EdgeIndex * indexed_edges)
Referenced by BIF_ReebGraphMultiFromEditMesh().
int weightFromLoc (struct EditMesh * me, int axis)
int weightToHarmonic (struct EditMesh * em, struct EdgeIndex * indexed_edges)
Referenced by BIF_ReebGraphMultiFromEditMesh().
void weightToVCol (struct EditMesh * em, int index)