Blender: AUD_JackDevice Class Reference
AUD_JackDevice Class Reference
#include <AUD_JackDevice.h>
Public Member Functions
AUD_JackDevice (std::string name, AUD_DeviceSpecs specs, int buffersize=AUD_DEFAULT_BUFFER_SIZE)
virtual ~AUD_JackDevice ()
void startPlayback ()
void stopPlayback ()
void seekPlayback (float time)
void setSyncCallback (AUD_syncFunction sync, void *data)
float getPlaybackPosition ()
bool doesPlayback ()
Protected Member Functions
virtual void playing (bool playing)
Detailed Description
This device plays back through Jack.
Definition at line 51 of file AUD_JackDevice.h.
Constructor & Destructor Documentation
AUD_JackDevice::AUD_JackDevice (std::string name, AUD_DeviceSpecs specs, int buffersize = AUD_DEFAULT_BUFFER_SIZE)
Creates a Jack client for audio output.
Parameters:
name The client name.
specs The wanted audio specification, where only the channel count is important.
buffersize The size of the internal buffer.
Exceptions:
AUD_Exception Thrown if the audio device cannot be opened.
Definition at line 183 of file AUD_JackDevice.cpp.
References AUD_CHANNELS_INVALID, AUD_CHANNELS_STEREO, AUD_ERROR_JACK, AUD_FORMAT_FLOAT32, AUD_THROW, AUD_DeviceSpecs::channels, AUD_SoftwareDevice::create(), AUD_SoftwareDevice::destroy(), AUD_DeviceSpecs::format, i, AUD_SoftwareDevice::m_specs, NULL, options, AUD_DeviceSpecs::rate, and AUD_Buffer::resize().
AUD_JackDevice::~AUD_JackDevice () [virtual]
Closes the Jack client.
Definition at line 282 of file AUD_JackDevice.cpp.
References AUD_DeviceSpecs::channels, AUD_SoftwareDevice::destroy(), AUD_SoftwareDevice::m_specs, and NULL.
Member Function Documentation
bool AUD_JackDevice::doesPlayback ()
Returns whether jack transport plays back.
Returns:
Whether jack transport plays back.
Definition at line 340 of file AUD_JackDevice.cpp.
References NULL, and state.
Referenced by AUD_doesPlayback().
float AUD_JackDevice::getPlaybackPosition ()
Retrieves the jack transport playback time.
Returns:
The current time position.
Definition at line 333 of file AUD_JackDevice.cpp.
References AUD_SoftwareDevice::m_specs, and AUD_DeviceSpecs::rate.
Referenced by AUD_getSequencerPosition().
void AUD_JackDevice::playing (bool playing) [protected, virtual]
This function tells the device, to start or pause playback.
Parameters:
playing True if device should playback.
Implements AUD_SoftwareDevice.
Definition at line 304 of file AUD_JackDevice.cpp.
void AUD_JackDevice::seekPlayback (float time)
Seeks jack transport playback.
Parameters:
time The time to seek to.
Definition at line 321 of file AUD_JackDevice.cpp.
References AUD_SoftwareDevice::m_specs, and AUD_DeviceSpecs::rate.
Referenced by AUD_seekSequencer().
void AUD_JackDevice::setSyncCallback (AUD_syncFunction sync, void * data)
Sets the sync callback for jack transport playback.
Parameters:
sync The callback function.
data The data for the function.
Definition at line 327 of file AUD_JackDevice.cpp.
References data.
void AUD_JackDevice::startPlayback ()
Starts jack transport playback.
Definition at line 309 of file AUD_JackDevice.cpp.
Referenced by AUD_startPlayback().
void AUD_JackDevice::stopPlayback ()
Stops jack transport playback.
Definition at line 315 of file AUD_JackDevice.cpp.
Referenced by AUD_stopPlayback().
The documentation for this class was generated from the following files:
AUD_JackDevice.h
AUD_JackDevice.cpp