Blender: IK_QSphericalSegment Class Reference
IK_QSphericalSegment Class Reference
#include <IK_QSegment.h>
Public Member Functions
IK_QSphericalSegment ()
MT_Vector3 Axis (int dof) const
bool UpdateAngle (const IK_QJacobian &jacobian, MT_Vector3 &delta, bool *clamp)
void Lock (int dof, IK_QJacobian &jacobian, MT_Vector3 &delta)
void UpdateAngleApply ()
bool ComputeClampRotation (MT_Vector3 &clamp)
void SetLimit (int axis, MT_Scalar lmin, MT_Scalar lmax)
void SetWeight (int axis, MT_Scalar weight)
Detailed Description
Definition at line 215 of file IK_QSegment.h.
Constructor & Destructor Documentation
IK_QSphericalSegment::IK_QSphericalSegment ()
Definition at line 360 of file IK_QSegment.cpp.
Member Function Documentation
MT_Vector3 IK_QSphericalSegment::Axis (int dof) const [virtual]
Implements IK_QSegment.
Definition at line 365 of file IK_QSegment.cpp.
References MT_Transform::getBasis(), MT_Matrix3x3::getColumn(), and IK_QSegment::m_global_transform.
bool IK_QSphericalSegment::ComputeClampRotation (MT_Vector3 & clamp)
void IK_QSphericalSegment::Lock (int dof, IK_QJacobian & jacobian, MT_Vector3 & delta) [virtual]
Reimplemented from IK_QSegment.
Definition at line 527 of file IK_QSegment.cpp.
References IK_QJacobian::Lock(), IK_QSegment::m_DoF_id, and IK_QSegment::m_locked.
void IK_QSphericalSegment::SetLimit (int axis, MT_Scalar lmin, MT_Scalar lmax) [virtual]
Reimplemented from IK_QSegment.
Definition at line 370 of file IK_QSegment.cpp.
References MT_clamp(), MT_PI(), and sin().
void IK_QSphericalSegment::SetWeight (int axis, MT_Scalar weight) [virtual]
Reimplemented from IK_QSegment.
Definition at line 405 of file IK_QSegment.cpp.
References IK_QSegment::m_weight.
bool IK_QSphericalSegment::UpdateAngle (const IK_QJacobian & jacobian, MT_Vector3 & delta, bool * clamp) [virtual]
Implements IK_QSegment.
Definition at line 410 of file IK_QSegment.cpp.
References IK_QJacobian::AngleUpdate(), ComputeSwingMatrix(), ComputeTwistMatrix(), cos(), EllipseClamp(), MT_Vector3::length(), M, IK_QSegment::m_basis, IK_QSegment::m_DoF_id, IK_QSegment::m_locked, MatrixToAxisAngle(), MT_fuzzyZero(), sin(), SphericalRangeParameters(), MT_Matrix3x3::transposed(), MT_Tuple3::x(), MT_Tuple3::y(), and MT_Tuple3::z().
void IK_QSphericalSegment::UpdateAngleApply () [virtual]
Implements IK_QSegment.
Definition at line 540 of file IK_QSegment.cpp.
References IK_QSegment::m_basis.
The documentation for this class was generated from the following files:
IK_QSegment.h
IK_QSegment.cpp