Blender: iff.h File Reference
iff.h File Reference
Blender pluginapi
#include <sys/types.h>
#include "util.h"
#include "externdef.h"
Classes
struct ImBuf
Defines
#define IB_MIPMAP_LEVELS 20
#define IB_FILENAME_SIZE 1023
Typedefs
typedef struct ImBuf ImBuf
Functions
LIBIMPORT struct ImBuf * allocImBuf (short, short, uchar, uint)
LIBIMPORT struct ImBuf * dupImBuf (struct ImBuf *)
LIBIMPORT void freeImBuf (struct ImBuf *)
LIBIMPORT short saveiff (struct ImBuf *, char *, int)
LIBIMPORT struct ImBuf * loadifffile (int, int)
LIBIMPORT struct ImBuf * loadiffname (char *, int)
LIBIMPORT struct ImBuf * testiffname (char *, int)
LIBIMPORT struct ImBuf * onehalf (struct ImBuf *)
LIBIMPORT struct ImBuf * half_x (struct ImBuf *)
LIBIMPORT struct ImBuf * half_y (struct ImBuf *)
LIBIMPORT struct ImBuf * double_x (struct ImBuf *)
LIBIMPORT struct ImBuf * double_y (struct ImBuf *)
LIBIMPORT struct ImBuf * double_fast_x (struct ImBuf *)
LIBIMPORT struct ImBuf * double_fast_y (struct ImBuf *)
LIBIMPORT int ispic (char *)
LIBIMPORT struct ImBuf * scaleImBuf (struct ImBuf *, short, short)
LIBIMPORT struct ImBuf * scalefastImBuf (struct ImBuf *, short, short)
LIBIMPORT void de_interlace (struct ImBuf *ib)
LIBIMPORT void interlace (struct ImBuf *ib)
LIBIMPORT void IMB_rectcpy (struct ImBuf *dbuf, struct ImBuf *sbuf, int destx, int desty, int srcx, int srcy, int width, int height)
LIBIMPORT void IMB_rectfill (struct ImBuf *drect, const float col[4])
LIBIMPORT void IMB_rectfill_area (struct ImBuf *ibuf, float *col, int x1, int y1, int x2, int y2)
LIBIMPORT void buf_rectfill_area (unsigned char *rect, float *rectf, int width, int height, const float col[4], int x1, int y1, int x2, int y2)
LIBIMPORT void IMB_rectfill_alpha (struct ImBuf *drect, const float value)
Detailed Description
Definition in file iff.h.
Define Documentation
#define IB_FILENAME_SIZE 1023
Definition at line 43 of file iff.h.
Referenced by imb_cache_filename(), IMB_loadiffname(), and IMB_testiffname().
#define IB_MIPMAP_LEVELS 20
Definition at line 42 of file iff.h.
Referenced by image_mem_size(), imagewraposa_aniso(), IMB_dupImBuf(), IMB_makemipmap(), and IMB_remakemipmap().
Typedef Documentation
typedef struct ImBuf ImBuf
Function Documentation
LIBIMPORT struct ImBuf* allocImBuf (short , short , uchar , uint) [read]
Definition at line 104 of file pluginapi.c.
References IMB_allocImBuf().
Referenced by pluginapi_force_ref().
LIBIMPORT void buf_rectfill_area (unsigned char * rect, float * rectf, int width, int height, const float col[4], int x1, int y1, int x2, int y2)
Definition at line 484 of file rectop.c.
Referenced by BKE_stamp_buf(), and IMB_rectfill_area().
LIBIMPORT void de_interlace (struct ImBuf * ib)
Definition at line 214 of file pluginapi.c.
References IMB_de_interlace().
Referenced by pluginapi_force_ref().
LIBIMPORT struct ImBuf* double_fast_x (struct ImBuf *) [read]
Definition at line 173 of file pluginapi.c.
References IMB_double_fast_x().
Referenced by pluginapi_force_ref().
LIBIMPORT struct ImBuf* double_fast_y (struct ImBuf *) [read]
Definition at line 178 of file pluginapi.c.
References IMB_double_fast_y().
Referenced by pluginapi_force_ref().
LIBIMPORT struct ImBuf* double_x (struct ImBuf *) [read]
Definition at line 163 of file pluginapi.c.
References IMB_double_x().
Referenced by pluginapi_force_ref().
LIBIMPORT struct ImBuf* double_y (struct ImBuf *) [read]
Definition at line 168 of file pluginapi.c.
References IMB_double_y().
Referenced by pluginapi_force_ref().
LIBIMPORT struct ImBuf* dupImBuf (struct ImBuf *) [read]
Definition at line 113 of file pluginapi.c.
References IMB_dupImBuf().
Referenced by pluginapi_force_ref().
LIBIMPORT void freeImBuf (struct ImBuf *)
Definition at line 118 of file pluginapi.c.
References IMB_freeImBuf().
Referenced by pluginapi_force_ref().
LIBIMPORT struct ImBuf* half_x (struct ImBuf *) [read]
Definition at line 153 of file pluginapi.c.
References IMB_half_x().
Referenced by pluginapi_force_ref().
LIBIMPORT struct ImBuf* half_y (struct ImBuf *) [read]
Definition at line 158 of file pluginapi.c.
References IMB_half_y().
Referenced by pluginapi_force_ref().
LIBIMPORT void IMB_rectcpy (struct ImBuf * dbuf, struct ImBuf * sbuf, int destx, int desty, int srcx, int srcy, int width, int height)
Definition at line 317 of file rectop.c.
Referenced by BKE_tracking_stabilize(), de_interlace_ng(), de_interlace_st(), envmap_split_ima(), get_area_imbuf(), IMB_de_interlace(), IMB_interlace(), input_preprocess(), my_envmap_split_ima(), RE_layer_load_from_file(), RE_WriteEnvmapResult(), save_jstjpeg(), and undo_copy_tile().
LIBIMPORT void IMB_rectfill (struct ImBuf * drect, const float col[4])
Definition at line 452 of file rectop.c.
Referenced by clear_images(), get_next_bake_face(), and stabilize_alloc_ibuf().
LIBIMPORT void IMB_rectfill_alpha (struct ImBuf * drect, const float value)
Definition at line 576 of file rectop.c.
Referenced by RE_bake_ibuf_filter().
LIBIMPORT void IMB_rectfill_area (struct ImBuf * ibuf, float * col, int x1, int y1, int x2, int y2)
Definition at line 569 of file rectop.c.
LIBIMPORT void interlace (struct ImBuf * ib)
Definition at line 209 of file pluginapi.c.
References IMB_interlace().
LIBIMPORT int ispic (char *)
Definition at line 183 of file pluginapi.c.
References IMB_ispic().
Referenced by pluginapi_force_ref().
LIBIMPORT struct ImBuf* loadifffile (int , int) [read]
Definition at line 130 of file pluginapi.c.
References IMB_loadifffile().
Referenced by pluginapi_force_ref().
LIBIMPORT struct ImBuf* loadiffname (char * , int) [read]
Definition at line 136 of file pluginapi.c.
References IMB_loadiffname().
Referenced by pluginapi_force_ref().
LIBIMPORT struct ImBuf* onehalf (struct ImBuf *) [read]
Definition at line 148 of file pluginapi.c.
References IMB_onehalf().
Referenced by pluginapi_force_ref().
LIBIMPORT short saveiff (struct ImBuf * , char * , int)
Definition at line 123 of file pluginapi.c.
References IMB_saveiff().
Referenced by pluginapi_force_ref().
LIBIMPORT struct ImBuf* scalefastImBuf (struct ImBuf * , short , short) [read]
Definition at line 198 of file pluginapi.c.
References IMB_scalefastImBuf().
Referenced by pluginapi_force_ref().
LIBIMPORT struct ImBuf* scaleImBuf (struct ImBuf * , short , short) [read]
Definition at line 191 of file pluginapi.c.
References IMB_scaleImBuf().
Referenced by pluginapi_force_ref().
LIBIMPORT struct ImBuf* testiffname (char * , int) [read]
Definition at line 142 of file pluginapi.c.
References IMB_testiffname().
Referenced by pluginapi_force_ref().