Blender: btDbvt::IWriter Struct Reference
btDbvt::IWriter Struct Reference
#include <btDbvt.h>
Public Member Functions
virtual ~IWriter ()
virtual void Prepare (const btDbvtNode *root, int numnodes)=0
virtual void WriteNode (const btDbvtNode *, int index, int parent, int child0, int child1)=0
virtual void WriteLeaf (const btDbvtNode *, int index, int parent)=0
Detailed Description
Definition at line 233 of file btDbvt.h.
Constructor & Destructor Documentation
virtual btDbvt::IWriter::~IWriter () [inline, virtual]
Definition at line 235 of file btDbvt.h.
Member Function Documentation
virtual void btDbvt::IWriter::Prepare (const btDbvtNode * root, int numnodes) [pure virtual]
Referenced by btDbvt::write().
virtual void btDbvt::IWriter::WriteLeaf (const btDbvtNode * , int index, int parent) [pure virtual]
Referenced by btDbvt::write().
virtual void btDbvt::IWriter::WriteNode (const btDbvtNode * , int index, int parent, int child0, int child1) [pure virtual]
Referenced by btDbvt::write().
The documentation for this struct was generated from the following file:
btDbvt.h