Blender: readfile.h File Reference
readfile.h File Reference
.blend read and write functions
#include "zlib.h"
Classes
struct FileData
struct BHeadN
Defines
#define FD_FLAGS_SWITCH_ENDIAN (1<<0)
#define FD_FLAGS_FILE_POINTSIZE_IS_4 (1<<1)
#define FD_FLAGS_POINTSIZE_DIFFERS (1<<2)
#define FD_FLAGS_FILE_OK (1<<3)
#define FD_FLAGS_NOT_MY_BUFFER (1<<4)
#define FD_FLAGS_NOT_MY_LIBMAP (1<<5)
#define SIZEOFBLENDERHEADER 12
Typedefs
typedef struct FileData FileData
typedef struct BHeadN BHeadN
Functions
void blo_join_main (ListBase *mainlist)
void blo_split_main (ListBase *mainlist, struct Main *main)
BlendFileData * blo_read_file_internal (FileData *fd, const char *filepath)
FileData * blo_openblenderfile (const char *filepath, struct ReportList *reports)
FileData * blo_openblendermemory (void *buffer, int buffersize, struct ReportList *reports)
FileData * blo_openblendermemfile (struct MemFile *memfile, struct ReportList *reports)
void blo_clear_proxy_pointers_from_lib (Main *oldmain)
void blo_make_image_pointer_map (FileData *fd, Main *oldmain)
void blo_end_image_pointer_map (FileData *fd, Main *oldmain)
void blo_make_movieclip_pointer_map (FileData *fd, Main *oldmain)
void blo_end_movieclip_pointer_map (FileData *fd, Main *oldmain)
void blo_add_library_pointer_map (ListBase *mainlist, FileData *fd)
void blo_freefiledata (FileData *fd)
BHead * blo_firstbhead (FileData *fd)
BHead * blo_nextbhead (FileData *fd, BHead *thisblock)
BHead * blo_prevbhead (FileData *fd, BHead *thisblock)
char * bhead_id_name (FileData *fd, BHead *bhead)
Detailed Description
Definition in file readfile.h.
Define Documentation
#define FD_FLAGS_FILE_OK (1<<3)
Definition at line 104 of file readfile.h.
Referenced by blo_decode_and_check(), and decode_blender_header().
#define FD_FLAGS_FILE_POINTSIZE_IS_4 (1<<1)
Definition at line 102 of file readfile.h.
Referenced by decode_blender_header(), and get_bhead().
#define FD_FLAGS_NOT_MY_BUFFER (1<<4)
Definition at line 105 of file readfile.h.
Referenced by blo_freefiledata(), blo_openblendermemfile(), and blo_openblendermemory().
#define FD_FLAGS_NOT_MY_LIBMAP (1<<5)
Definition at line 106 of file readfile.h.
Referenced by blo_freefiledata().
#define FD_FLAGS_POINTSIZE_DIFFERS (1<<2)
Definition at line 103 of file readfile.h.
Referenced by decode_blender_header(), and get_bhead().
#define FD_FLAGS_SWITCH_ENDIAN (1<<0)
Definition at line 101 of file readfile.h.
Referenced by decode_blender_header(), direct_link_bones(), direct_link_constraints(), direct_link_curve(), direct_link_fmodifiers(), direct_link_key(), direct_link_keymapitem(), direct_link_mdisps(), direct_link_mesh(), direct_link_modifiers(), direct_link_object(), direct_link_pointcache(), direct_link_pose(), direct_link_scene(), get_bhead(), lib_link_image(), lib_link_material(), lib_link_mesh(), lib_link_object(), lib_link_scene(), library_append_end(), read_file_dna(), read_libblock(), read_struct(), and test_pointer_array().
#define SIZEOFBLENDERHEADER 12
Definition at line 108 of file readfile.h.
Referenced by blo_openblendermemory(), and decode_blender_header().
Typedef Documentation
typedef struct BHeadN BHeadN
typedef struct FileData FileData
Function Documentation
char* bhead_id_name (FileData * fd, BHead * bhead)
Definition at line 13589 of file readfile.c.
References FileData::id_name_offs.
Referenced by append_id_part(), append_named_part(), BLO_blendhandle_get_datablock_names(), BLO_blendhandle_get_previews(), and is_yet_read().
void blo_add_library_pointer_map (ListBase * mainlist, FileData * fd)
Definition at line 1359 of file readfile.c.
References ListBase::first, GS, i, FileData::libmap, MAX_LIBARRAY, ID::name, ID::next, Main::next, oldnewmap_insert(), and set_listbasepointers().
Referenced by BLO_read_from_memfile().
void blo_clear_proxy_pointers_from_lib (Main * oldmain)
Definition at line 1225 of file readfile.c.
References ListBase::first, Object::id, ID::lib, ID::next, NULL, Main::object, and Object::proxy_from.
Referenced by BLO_read_from_memfile().
void blo_end_image_pointer_map (FileData * fd, Main * oldmain)
Definition at line 1263 of file readfile.c.
References Image::bindcode, BLI_remlink(), OldNewMap::entries, ListBase::first, Image::gputexture, i, Image::ibufs, Scene::id, Image::id, IMA_MAX_RENDER_SLOT, Main::image, FileData::imamap, OldNewMap::nentries, newimaadr(), OldNew::newp, bNode::next, Link::next, next, ID::next, bNodeTree::nodes, Scene::nodetree, OldNew::nr, NULL, bNode::preview, Image::renders, and Main::scene.
Referenced by BLO_read_from_memfile().
void blo_end_movieclip_pointer_map (FileData * fd, Main * oldmain)
Definition at line 1329 of file readfile.c.
References MovieClip::cache, MovieTracking::camera, CMP_NODE_MOVIEDISTORTION, OldNewMap::entries, ListBase::first, i, Scene::id, MovieClip::id, MovieTrackingCamera::intrinsics, Main::movieclip, FileData::movieclipmap, OldNewMap::nentries, newmclipadr(), OldNew::newp, bNode::next, ID::next, bNodeTree::nodes, Scene::nodetree, OldNew::nr, NULL, Main::scene, bNode::storage, MovieClip::tracking, and bNode::type.
Referenced by BLO_read_from_memfile().
BHead* blo_firstbhead (FileData * fd)
Definition at line 738 of file readfile.c.
References BHeadN::bhead, ListBase::first, get_bhead(), FileData::listbase, and NULL.
Referenced by append_id_part(), append_named_part(), BLO_blendhandle_get_datablock_names(), BLO_blendhandle_get_linkable_groups(), BLO_blendhandle_get_previews(), BLO_blendhandle_print_sizes(), blo_read_file_internal(), find_bhead(), read_file_dna(), read_file_version(), and sort_bhead_old_map().
void blo_freefiledata (FileData * fd)
Definition at line 1056 of file readfile.c.
References FileData::bheadmap, BLI_freelistN(), FileData::buffer, FileData::compflags, FileData::datamap, DNA_sdna_free(), FD_FLAGS_NOT_MY_BUFFER, FD_FLAGS_NOT_MY_LIBMAP, FileData::filedes, FileData::filesdna, FileData::flags, FileData::globmap, FileData::gzfiledes, FileData::imamap, FileData::libmap, FileData::listbase, MEM_freeN(), FileData::memsdna, FileData::movieclipmap, NULL, and oldnewmap_free().
Referenced by BLO_blendhandle_close(), blo_decode_and_check(), blo_read_blendafterruntime(), BLO_read_from_file(), BLO_read_from_memfile(), BLO_read_from_memory(), library_append_end(), and read_libraries().
void blo_join_main (ListBase * mainlist)
Definition at line 440 of file readfile.c.
References add_main_to_main(), BLI_remlink(), ListBase::first, MEM_freeN(), and Main::next.
Referenced by blo_read_file_internal(), BLO_read_from_memfile(), library_append_end(), and write_file_handle().
void blo_make_image_pointer_map (FileData * fd, Main * oldmain)
Definition at line 1234 of file readfile.c.
References ListBase::first, Image::gputexture, Image::ibufs, Scene::id, Image::id, IMA_MAX_RENDER_SLOT, Main::image, FileData::imamap, bNode::next, Link::next, ID::next, bNodeTree::nodes, Scene::nodetree, oldnewmap_insert(), oldnewmap_new(), bNode::preview, Image::renders, and Main::scene.
Referenced by BLO_read_from_memfile().
void blo_make_movieclip_pointer_map (FileData * fd, Main * oldmain)
Definition at line 1302 of file readfile.c.
References MovieClip::cache, MovieTracking::camera, CMP_NODE_MOVIEDISTORTION, ListBase::first, Scene::id, MovieClip::id, MovieTrackingCamera::intrinsics, Main::movieclip, FileData::movieclipmap, bNode::next, ID::next, bNodeTree::nodes, Scene::nodetree, oldnewmap_insert(), oldnewmap_new(), Main::scene, bNode::storage, MovieClip::tracking, and bNode::type.
Referenced by BLO_read_from_memfile().
BHead* blo_nextbhead (FileData * fd, BHead * thisblock)
Definition at line 766 of file readfile.c.
References BHeadN::bhead, get_bhead(), GET_INT_FROM_POINTER, BHeadN::next, and NULL.
Referenced by append_id_part(), append_named_part(), BLO_blendhandle_get_datablock_names(), BLO_blendhandle_get_linkable_groups(), BLO_blendhandle_get_previews(), BLO_blendhandle_print_sizes(), blo_read_file_internal(), find_bhead(), read_data_into_oldnewmap(), read_file_dna(), read_file_version(), read_global(), read_libblock(), and sort_bhead_old_map().
FileData* blo_openblenderfile (const char * filepath, struct ReportList * reports)
Definition at line 999 of file readfile.c.
References BKE_reportf(), BLI_gzopen(), BLI_strncpy(), blo_decode_and_check(), fd_read_gzip_from_file(), filedata_new(), FileData::gzfiledes, NULL, FileData::read, FileData::relabase, and RPT_ERROR.
Referenced by BLO_blendhandle_from_file(), BLO_read_from_file(), and read_libraries().
FileData* blo_openblendermemfile (struct MemFile * memfile, struct ReportList * reports)
Definition at line 1038 of file readfile.c.
References BKE_report(), blo_decode_and_check(), FD_FLAGS_NOT_MY_BUFFER, fd_read_from_memfile(), filedata_new(), FileData::flags, FileData::memfile, NULL, FileData::read, and RPT_ERROR.
Referenced by BLO_read_from_memfile().
FileData* blo_openblendermemory (void * buffer, int buffersize, struct ReportList * reports)
Definition at line 1021 of file readfile.c.
References BKE_report(), blo_decode_and_check(), FileData::buffer, FileData::buffersize, FD_FLAGS_NOT_MY_BUFFER, fd_read_from_memory(), filedata_new(), FileData::flags, NULL, FileData::read, RPT_ERROR, and SIZEOFBLENDERHEADER.
Referenced by BLO_blendhandle_from_memory(), and BLO_read_from_memory().
BHead* blo_prevbhead (FileData * fd, BHead * thisblock)
BlendFileData* blo_read_file_internal (FileData * fd, const char * filepath)
Definition at line 13428 of file readfile.c.
References BLENFILETYPE_BLEND, BLI_addtail(), BLI_strncpy(), blo_firstbhead(), blo_join_main(), blo_nextbhead(), BHead::code, DATA, DNA1, do_versions(), ENDB, FileData::fileversion, fix_relpaths_library(), GLOB, ID_ID, ID_LI, ID_SCR, ID_SCRN, ListBase::last, LIB_EXTERN, lib_link_all(), LIB_LOCAL, LIB_READ, lib_verify_nodetree(), link_global(), BlendFileData::main, FileData::mainlist, MEM_callocN(), FileData::memfile, Main::name, NULL, read_global(), read_libblock(), read_libraries(), read_userdef(), FileData::relabase, REND, TEST, TRUE, BlendFileData::type, USER, and Main::versionfile.
Referenced by blo_read_blendafterruntime(), BLO_read_from_file(), BLO_read_from_memfile(), and BLO_read_from_memory().
void blo_split_main (ListBase * mainlist, struct Main * main)
Definition at line 479 of file readfile.c.
References BLI_addtail(), Main::curlib, ListBase::first, i, Library::id, ListBase::last, Main::library, main(), MAX_LIBARRAY, MEM_callocN(), ID::next, Main::next, NULL, set_listbasepointers(), and split_libdata().
Referenced by BLO_read_from_memfile(), library_append_begin(), and write_file_handle().