Blender: btPolyhedralConvexShape Class Reference
btPolyhedralConvexShape Class Reference
The btPolyhedralConvexShape is an internal interface class for polyhedral convex shapes.
#include <btPolyhedralConvexShape.h>
Public Member Functions
btPolyhedralConvexShape ()
virtual btVector3 localGetSupportingVertexWithoutMargin (const btVector3 &vec) const
virtual void batchedUnitVectorGetSupportingVertexWithoutMargin (const btVector3 *vectors, btVector3 *supportVerticesOut, int numVectors) const
virtual void calculateLocalInertia (btScalar mass, btVector3 &inertia) const
virtual int getNumVertices () const =0
virtual int getNumEdges () const =0
virtual void getEdge (int i, btVector3 &pa, btVector3 &pb) const =0
virtual void getVertex (int i, btVector3 &vtx) const =0
virtual int getNumPlanes () const =0
virtual void getPlane (btVector3 &planeNormal, btVector3 &planeSupport, int i) const =0
virtual bool isInside (const btVector3 &pt, btScalar tolerance) const =0
Detailed Description
The btPolyhedralConvexShape is an internal interface class for polyhedral convex shapes.
Definition at line 24 of file btPolyhedralConvexShape.h.
Constructor & Destructor Documentation
btPolyhedralConvexShape::btPolyhedralConvexShape ()
Definition at line 18 of file btPolyhedralConvexShape.cpp.
Member Function Documentation
void btPolyhedralConvexShape::batchedUnitVectorGetSupportingVertexWithoutMargin (const btVector3 * vectors, btVector3 * supportVerticesOut, int numVectors) const [virtual]
Reimplemented in btBox2dShape, btBoxShape, and btConvexTriangleMeshShape.
Definition at line 65 of file btPolyhedralConvexShape.cpp.
References BT_LARGE_FLOAT, getNumVertices(), getVertex(), and i.
Referenced by btPolyhedralConvexAabbCachingShape::recalcLocalAabb().
void btPolyhedralConvexShape::calculateLocalInertia (btScalar mass, btVector3 & inertia) const [virtual]
Reimplemented in btBox2dShape, and btBoxShape.
Definition at line 100 of file btPolyhedralConvexShape.cpp.
References btConvexInternalShape::getAabb(), btConvexInternalShape::getMargin(), and btTransform::setIdentity().
virtual void btPolyhedralConvexShape::getEdge (int i, btVector3 & pa, btVector3 & pb) const [pure virtual]
Implemented in btBox2dShape, btBoxShape, btConvexTriangleMeshShape, and btBU_Simplex1to4.
Referenced by btCollisionWorld::debugDrawObject().
virtual int btPolyhedralConvexShape::getNumEdges () const [pure virtual]
Implemented in btBox2dShape, btBoxShape, btConvexTriangleMeshShape, and btBU_Simplex1to4.
Referenced by btCollisionWorld::debugDrawObject().
virtual int btPolyhedralConvexShape::getNumPlanes () const [pure virtual]
Implemented in btBox2dShape, btBoxShape, btConvexTriangleMeshShape, and btBU_Simplex1to4.
virtual int btPolyhedralConvexShape::getNumVertices () const [pure virtual]
Implemented in btBox2dShape, btBoxShape, btConvexTriangleMeshShape, and btBU_Simplex1to4.
Referenced by batchedUnitVectorGetSupportingVertexWithoutMargin(), and localGetSupportingVertexWithoutMargin().
virtual void btPolyhedralConvexShape::getPlane (btVector3 & planeNormal, btVector3 & planeSupport, int i) const [pure virtual]
Implemented in btBox2dShape, btBoxShape, btConvexTriangleMeshShape, and btBU_Simplex1to4.
virtual void btPolyhedralConvexShape::getVertex (int i, btVector3 & vtx) const [pure virtual]
Implemented in btBox2dShape, btBoxShape, btConvexTriangleMeshShape, and btBU_Simplex1to4.
Referenced by batchedUnitVectorGetSupportingVertexWithoutMargin(), and localGetSupportingVertexWithoutMargin().
virtual bool btPolyhedralConvexShape::isInside (const btVector3 & pt, btScalar tolerance) const [pure virtual]
Implemented in btBox2dShape, btBoxShape, btConvexTriangleMeshShape, and btBU_Simplex1to4.
btVector3 btPolyhedralConvexShape::localGetSupportingVertexWithoutMargin (const btVector3 & vec) const [virtual]
Reimplemented in btBox2dShape, btBoxShape, and btConvexTriangleMeshShape.
Definition at line 24 of file btPolyhedralConvexShape.cpp.
References BT_LARGE_FLOAT, btSqrt(), getNumVertices(), getVertex(), and i.
The documentation for this class was generated from the following files:
btPolyhedralConvexShape.h
btPolyhedralConvexShape.cpp