Blender: node_composite_curves.c File Reference
node_composite_curves.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void node_composit_exec_curves_time (void *data, bNode *node, bNodeStack **UNUSED(in), bNodeStack **out)
static void node_composit_init_curves_time (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_curve_time (bNodeTreeType *ttype)
static void node_composit_exec_curve_vec (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_curve_vec (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_curve_vec (bNodeTreeType *ttype)
static void do_curves (bNode *node, float *out, float *in)
static void do_curves_fac (bNode *node, float *out, float *in, float *fac)
static void node_composit_exec_curve_rgb (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_curve_rgb (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_curve_rgb (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_time_out []
static bNodeSocketTemplate cmp_node_curve_vec_in []
static bNodeSocketTemplate cmp_node_curve_vec_out []
static bNodeSocketTemplate cmp_node_curve_rgb_in []
static bNodeSocketTemplate cmp_node_curve_rgb_out []
Detailed Description
Definition in file node_composite_curves.c.
Function Documentation
static void do_curves (bNode * node, float * out, float * in) [static]
Definition at line 134 of file node_composite_curves.c.
References curvemapping_evaluate_premulRGBF(), and bNode::storage.
Referenced by node_composit_exec_curve_rgb().
static void do_curves_fac (bNode * node, float * out, float * in, float * fac) [static]
Definition at line 140 of file node_composite_curves.c.
References copy_v3_v3(), curvemapping_evaluate_premulRGBF(), and bNode::storage.
Referenced by node_composit_exec_curve_rgb().
static void node_composit_exec_curve_rgb (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 158 of file node_composite_curves.c.
References alloc_compbuf(), CB_RGBA, CB_VAL, composit1_pixel_processor(), composit2_pixel_processor(), curvemapping_evaluateRGBF(), curvemapping_set_black_white(), bNodeStack::data, do_curves(), do_curves_fac(), NULL, bNode::storage, bNodeStack::vec, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_curve_rgb().
static void node_composit_exec_curve_vec (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 92 of file node_composite_curves.c.
References curvemapping_evaluate_premulRGBF(), bNode::storage, and bNodeStack::vec.
Referenced by register_node_type_cmp_curve_vec().
static void node_composit_exec_curves_time (void * data, bNode * node, bNodeStack ** UNUSEDin, bNodeStack ** out) [static]
Definition at line 44 of file node_composite_curves.c.
References RenderData::cfra, CLAMPIS, curvemapping_evaluateF(), bNode::custom1, bNode::custom2, data, bNode::storage, and bNodeStack::vec.
Referenced by register_node_type_cmp_curve_time().
static void node_composit_init_curve_rgb (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 187 of file node_composite_curves.c.
References curvemapping_add(), and bNode::storage.
Referenced by register_node_type_cmp_curve_rgb().
static void node_composit_init_curve_vec (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 100 of file node_composite_curves.c.
References curvemapping_add(), and bNode::storage.
Referenced by register_node_type_cmp_curve_vec().
static void node_composit_init_curves_time (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 58 of file node_composite_curves.c.
References curvemapping_add(), bNode::custom1, bNode::custom2, and bNode::storage.
Referenced by register_node_type_cmp_curve_time().
void register_node_type_cmp_curve_rgb (bNodeTreeType * ttype)
Definition at line 192 of file node_composite_curves.c.
References CMP_NODE_CURVE_RGB, NODE_CLASS_OP_COLOR, node_composit_exec_curve_rgb(), node_composit_init_curve_rgb(), node_copy_curves(), node_free_curves(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_curve_time (bNodeTreeType * ttype)
Definition at line 65 of file node_composite_curves.c.
References CMP_NODE_TIME, NODE_CLASS_INPUT, node_composit_exec_curves_time(), node_composit_init_curves_time(), node_copy_curves(), node_free_curves(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
void register_node_type_cmp_curve_vec (bNodeTreeType * ttype)
Definition at line 105 of file node_composite_curves.c.
References CMP_NODE_CURVE_VEC, NODE_CLASS_OP_VECTOR, node_composit_exec_curve_vec(), node_composit_init_curve_vec(), node_copy_curves(), node_free_curves(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_curve_rgb_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Fac",   1.0f, 0.0f, 0.0f, 1.0f, -1.0f, 1.0f, PROP_FACTOR},
    {   SOCK_RGBA, 1, "Image",  1.0f, 1.0f, 1.0f, 1.0f},
    {   SOCK_RGBA, 1, "Black Level",    0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_RGBA, 1, "White Level",    1.0f, 1.0f, 1.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 121 of file node_composite_curves.c.
bNodeSocketTemplate cmp_node_curve_rgb_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 129 of file node_composite_curves.c.
bNodeSocketTemplate cmp_node_curve_vec_in[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 1, "Vector",   0.0f, 0.0f, 0.0f, 1.0f, -1.0f, 1.0f, PROP_NONE},
    {   -1, 0, ""   }
}
Definition at line 82 of file node_composite_curves.c.
bNodeSocketTemplate cmp_node_curve_vec_out[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 0, "Vector"},
    {   -1, 0, ""   }
}
Definition at line 87 of file node_composite_curves.c.
bNodeSocketTemplate cmp_node_time_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "Fac"},
    {   -1, 0, ""   }
}
Definition at line 39 of file node_composite_curves.c.