Blender: BOP_Vertex Class Reference
BOP_Vertex Class Reference
#include <BOP_Vertex.h>
Public Member Functions
BOP_Vertex (double x, double y, double z)
BOP_Vertex (MT_Point3 d)
void addEdge (BOP_Index i)
void removeEdge (BOP_Index i)
BOP_Index getEdge (unsigned int i)
unsigned int getNumEdges ()
BOP_Indexs & getEdges ()
MT_Point3 getPoint () const
BOP_TAG getTAG ()
void setTAG (BOP_TAG t)
Detailed Description
Definition at line 41 of file BOP_Vertex.h.
Constructor & Destructor Documentation
BOP_Vertex::BOP_Vertex (double x, double y, double z)
Constructs a new vertex with the specified coordinates.
Parameters:
x X-axis coordinate
y Y-axis coordinate
z Z-axis coordinate
Definition at line 41 of file BOP_Vertex.cpp.
References MT_Tuple3::setValue(), and UNCLASSIFIED.
BOP_Vertex::BOP_Vertex (MT_Point3 p)
Constructs a new vertex with the specified point.
Parameters:
p point XYZ
Definition at line 51 of file BOP_Vertex.cpp.
References p, and UNCLASSIFIED.
Member Function Documentation
void BOP_Vertex::addEdge (BOP_Index i)
Adds a new edge index to this vertex.
Parameters:
i edge index
Definition at line 61 of file BOP_Vertex.cpp.
Referenced by BOP_Mesh::addFace(), and BOP_Mesh::replaceVertexIndex().
BOP_Index BOP_Vertex::getEdge (unsigned int i) [inline]
Definition at line 55 of file BOP_Vertex.h.
References i.
BOP_Indexs& BOP_Vertex::getEdges () [inline]
Definition at line 57 of file BOP_Vertex.h.
Referenced by clean_nonmanifold(), deleteFace(), and BOP_Mesh::replaceVertexIndex().
unsigned int BOP_Vertex::getNumEdges () [inline]
Definition at line 56 of file BOP_Vertex.h.
MT_Point3 BOP_Vertex::getPoint () const [inline]
Definition at line 58 of file BOP_Vertex.h.
Referenced by BOP_createFace3(), BOP_getNearestVertex(), BOP_getPoints(), BOP_isInsideCircle(), BOP_splitEdge(), BOP_splitFace(), and BOP_splitQuad().
BOP_TAG BOP_Vertex::getTAG () [inline]
Definition at line 59 of file BOP_Vertex.h.
void BOP_Vertex::removeEdge (BOP_Index i)
Removes an edge index from this vertex.
Parameters:
i edge index
Definition at line 71 of file BOP_Vertex.cpp.
References i.
Referenced by BOP_Mesh::replaceVertexIndex().
void BOP_Vertex::setTAG (BOP_TAG t) [inline]
Definition at line 60 of file BOP_Vertex.h.
Referenced by BOP_meshClassify(), and BOP_Mesh::replaceVertexIndex().
The documentation for this class was generated from the following files:
BOP_Vertex.h
BOP_Vertex.cpp