Blender: wm_gesture.c File Reference
wm_gesture.c File Reference
windowmanager
#include "DNA_screen_types.h"
#include "DNA_vec_types.h"
#include "DNA_userdef_types.h"
#include "DNA_windowmanager_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_scanfill.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "WM_api.h"
#include "WM_types.h"
#include "wm.h"
#include "wm_event_system.h"
#include "wm_subwindow.h"
#include "wm_draw.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
Functions
wmGesture * WM_gesture_new (bContext *C, wmEvent *event, int type)
void WM_gesture_end (bContext *C, wmGesture *gesture)
void WM_gestures_remove (bContext *C)
int wm_gesture_evaluate (wmGesture *gesture)
static void wm_gesture_draw_rect (wmGesture *gt)
static void wm_gesture_draw_line (wmGesture *gt)
static void wm_gesture_draw_circle (wmGesture *gt)
static void draw_filled_lasso (wmGesture *gt)
static void wm_gesture_draw_lasso (wmGesture *gt)
static void wm_gesture_draw_cross (wmWindow *win, wmGesture *gt)
void wm_gesture_draw (wmWindow *win)
void wm_gesture_tag_redraw (bContext *C)
Detailed Description
Definition in file wm_gesture.c.
Function Documentation
static void draw_filled_lasso (wmGesture * gt) [static]
Definition at line 231 of file wm_gesture.c.
References BLI_addfilledge(), BLI_addfillvert(), BLI_begin_edgefill(), BLI_edgefill_ex(), BLI_end_edgefill(), ScanFillVert::co, co, wmGesture::customdata, ScanFillVert::f, FALSE, ScanFillContext::fillfacebase, ListBase::first, i, ScanFillFace::next, NULL, wmGesture::points, ScanFillFace::v1, ScanFillFace::v2, and ScanFillFace::v3.
Referenced by wm_gesture_draw_lasso().
void wm_gesture_draw (wmWindow * win)
Definition at line 324 of file wm_gesture.c.
References ListBase::first, wmWindow::gesture, wmGesture::mode, wmGesture::next, wmGesture::swinid, wmGesture::type, WM_GESTURE_CIRCLE, WM_GESTURE_CROSS_RECT, wm_gesture_draw_circle(), wm_gesture_draw_cross(), wm_gesture_draw_lasso(), wm_gesture_draw_line(), wm_gesture_draw_rect(), WM_GESTURE_LASSO, WM_GESTURE_LINES, WM_GESTURE_RECT, WM_GESTURE_STRAIGHTLINE, and wmSubWindowSet().
Referenced by wm_method_draw_full(), wm_method_draw_overlap_all(), and wm_method_draw_triple().
static void wm_gesture_draw_circle (wmGesture * gt) [static]
Definition at line 207 of file wm_gesture.c.
References wmGesture::customdata, glutil_draw_filled_arc(), glutil_draw_lined_arc(), M_PI, rcti::xmax, rcti::xmin, and rcti::ymin.
Referenced by wm_gesture_draw().
static void wm_gesture_draw_cross (wmWindow * win, wmGesture * gt) [static]
Definition at line 306 of file wm_gesture.c.
References wmGesture::customdata, sdrawline(), wmWindow::sizex, wmWindow::sizey, rcti::xmin, and rcti::ymin.
Referenced by wm_gesture_draw().
static void wm_gesture_draw_lasso (wmGesture * gt) [static]
Definition at line 275 of file wm_gesture.c.
References wmGesture::customdata, draw_filled_lasso(), i, wmGesture::points, wmGesture::type, and WM_GESTURE_LASSO.
Referenced by wm_gesture_draw().
static void wm_gesture_draw_line (wmGesture * gt) [static]
Definition at line 191 of file wm_gesture.c.
References wmGesture::customdata, sdrawline(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by wm_gesture_draw().
static void wm_gesture_draw_rect (wmGesture * gt) [static]
Definition at line 167 of file wm_gesture.c.
References wmGesture::customdata, sdrawbox(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by wm_gesture_draw().
void WM_gesture_end (bContext * C, wmGesture * gesture)
Definition at line 108 of file wm_gesture.c.
References BLI_remlink(), CTX_wm_window(), wmGesture::customdata, wmWindow::gesture, MEM_freeN(), NULL, and wmWindow::tweak.
Referenced by tweak_gesture_modal(), wm_gesture_end(), WM_gestures_remove(), and wm_tweakevent_test().
int wm_gesture_evaluate (wmGesture * gesture)
Definition at line 129 of file wm_gesture.c.
References ABS, atan2f, wmGesture::customdata, EVT_GESTURE_E, EVT_GESTURE_N, EVT_GESTURE_NE, EVT_GESTURE_NW, EVT_GESTURE_S, EVT_GESTURE_SE, EVT_GESTURE_SW, EVT_GESTURE_W, M_PI, wmGesture::type, WM_GESTURE_TWEAK, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by tweak_gesture_modal().
wmGesture* WM_gesture_new (bContext * C, wmEvent * event, int type) [read]
Definition at line 61 of file wm_gesture.c.
References BLI_addtail(), circle_select_size, CTX_wm_region(), CTX_wm_window(), wmGesture::customdata, ELEM, ELEM5, wmGesture::event_type, wmWindow::gesture, MEM_callocN(), wmGesture::points, wmGesture::size, wmGesture::swinid, ARegion::swinid, wmGesture::type, WM_GESTURE_CIRCLE, WM_GESTURE_CROSS_RECT, WM_GESTURE_LASSO, WM_GESTURE_LINES, WM_GESTURE_RECT, WM_GESTURE_STRAIGHTLINE, WM_GESTURE_TWEAK, WM_LASSO_MIN_POINTS, wm_subwindow_getorigin(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by WM_border_select_invoke(), WM_gesture_circle_invoke(), WM_gesture_lasso_invoke(), WM_gesture_lines_invoke(), WM_gesture_straightline_invoke(), and wm_tweakevent_test().
void wm_gesture_tag_redraw (bContext * C)
Definition at line 353 of file wm_gesture.c.
References CTX_wm_region(), CTX_wm_screen(), CTX_wm_window(), bScreen::do_draw_gesture, and wm_tag_redraw_overlay().
Referenced by WM_border_select_invoke(), WM_border_select_modal(), WM_gesture_circle_invoke(), WM_gesture_circle_modal(), WM_gesture_lasso_invoke(), WM_gesture_lasso_modal(), WM_gesture_lines_invoke(), WM_gesture_straightline_invoke(), and WM_gesture_straightline_modal().
void WM_gestures_remove (bContext * C)
Definition at line 119 of file wm_gesture.c.
References CTX_wm_window(), ListBase::first, wmWindow::gesture, and WM_gesture_end().
Referenced by ui_but_start_drag().