Blender: node_composite_sepcombHSVA.c File Reference
node_composite_sepcombHSVA.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_sephsva (bNode *UNUSED(node), float *out, float *in)
static void node_composit_exec_sephsva (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_sephsva (bNodeTreeType *ttype)
static void do_comb_hsva (bNode *UNUSED(node), float *out, float *in1, float *in2, float *in3, float *in4)
static void node_composit_exec_combhsva (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_combhsva (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_sephsva_in []
static bNodeSocketTemplate cmp_node_sephsva_out []
static bNodeSocketTemplate cmp_node_combhsva_in []
static bNodeSocketTemplate cmp_node_combhsva_out []
Detailed Description
Definition in file node_composite_sepcombHSVA.c.
Function Documentation
static void do_comb_hsva (bNode * UNUSEDnode, float * out, float * in1, float * in2, float * in3, float * in4) [static]
Definition at line 128 of file node_composite_sepcombHSVA.c.
References g, and hsv_to_rgb().
Referenced by node_composit_exec_combhsva().
static void do_sephsva (bNode * UNUSEDnode, float * out, float * in) [static]
Definition at line 49 of file node_composite_sepcombHSVA.c.
References rgb_to_hsv().
Referenced by node_composit_exec_sephsva().
static void node_composit_exec_combhsva (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 139 of file node_composite_sepcombHSVA.c.
References alloc_compbuf(), CB_RGBA, CB_VAL, composit4_pixel_processor(), bNodeStack::data, data, do_comb_hsva(), hsv_to_rgb(), NULL, bNodeStack::vec, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_combhsva().
static void node_composit_exec_sephsva (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 61 of file node_composite_sepcombHSVA.c.
References CB_RGBA, CHAN_A, CHAN_B, CHAN_G, CHAN_R, composit1_pixel_processor(), bNodeStack::data, data, do_sephsva(), dupalloc_compbuf(), free_compbuf(), NULL, rgb_to_hsv(), typecheck_compbuf(), valbuf_from_rgbabuf(), and bNodeStack::vec.
Referenced by register_node_type_cmp_sephsva().
void register_node_type_cmp_combhsva (bNodeTreeType * ttype)
Definition at line 171 of file node_composite_sepcombHSVA.c.
References CMP_NODE_COMBHSVA, NODE_CLASS_CONVERTOR, node_composit_exec_combhsva(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_sephsva (bNodeTreeType * ttype)
Definition at line 102 of file node_composite_sepcombHSVA.c.
References CMP_NODE_SEPHSVA, NODE_CLASS_CONVERTOR, node_composit_exec_sephsva(), node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_combhsva_in[] [static]
Initial value:
 {
   {    SOCK_FLOAT, 1, "H",         0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
   {    SOCK_FLOAT, 1, "S",         0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
   {    SOCK_FLOAT, 1, "V",         0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
   {    SOCK_FLOAT, 1, "A",         1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
   {    -1, 0, ""   }
}
Definition at line 116 of file node_composite_sepcombHSVA.c.
bNodeSocketTemplate cmp_node_combhsva_out[] [static]
Initial value:
 {
   {    SOCK_RGBA, 0, "Image"},
   {    -1, 0, ""   }
}
Definition at line 123 of file node_composite_sepcombHSVA.c.
bNodeSocketTemplate cmp_node_sephsva_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_composite_sepcombHSVA.c.
bNodeSocketTemplate cmp_node_sephsva_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "H"},
    {   SOCK_FLOAT, 0, "S"},
    {   SOCK_FLOAT, 0, "V"},
    {   SOCK_FLOAT, 0, "A"},
    {   -1, 0, ""   }
}
Definition at line 41 of file node_composite_sepcombHSVA.c.