Blender: bpy_rna_anim.h File Reference
bpy_rna_anim.h File Reference
Python RNA and Operators
Functions
PyObject * pyrna_struct_keyframe_insert (BPy_StructRNA *self, PyObject *args, PyObject *kw)
PyObject * pyrna_struct_keyframe_delete (BPy_StructRNA *self, PyObject *args, PyObject *kw)
PyObject * pyrna_struct_driver_add (BPy_StructRNA *self, PyObject *args)
PyObject * pyrna_struct_driver_remove (BPy_StructRNA *self, PyObject *args)
Variables
char pyrna_struct_keyframe_insert_doc []
char pyrna_struct_keyframe_delete_doc []
char pyrna_struct_driver_add_doc []
char pyrna_struct_driver_remove_doc []
Detailed Description
Definition in file bpy_rna_anim.h.
Function Documentation
PyObject* pyrna_struct_driver_add (BPy_StructRNA * self, PyObject * args)
Definition at line 281 of file bpy_rna_anim.c.
References ANIM_add_driver(), BKE_animdata_from_id(), BKE_reports_init(), BPy_GetContext(), BPy_reports_to_error(), DRIVER_TYPE_PYTHON, AnimData::drivers, i, list_find_fcurve(), MEM_freeN(), NC_ANIMATION, ND_FCURVES_ORDER, NULL, pyrna_struct_anim_args_parse(), PYRNA_STRUCT_CHECK_OBJ, pyrna_struct_CreatePyObject(), RNA_FCurve, RNA_pointer_create(), RPT_STORE, TRUE, and WM_event_add_notifier().
PyObject* pyrna_struct_driver_remove (BPy_StructRNA * self, PyObject * args)
Definition at line 357 of file bpy_rna_anim.c.
References ANIM_remove_driver(), BKE_reports_init(), BPy_GetContext(), BPy_reports_to_error(), MEM_freeN(), NC_ANIMATION, ND_FCURVES_ORDER, NULL, pyrna_struct_anim_args_parse(), PYRNA_STRUCT_CHECK_OBJ, RPT_STORE, TRUE, and WM_event_add_notifier().
PyObject* pyrna_struct_keyframe_delete (BPy_StructRNA * self, PyObject * args, PyObject * kw)
Definition at line 235 of file bpy_rna_anim.c.
References BKE_reports_init(), BPy_reports_to_error(), delete_keyframe(), FLT_MAX, MEM_freeN(), NULL, PYRNA_STRUCT_CHECK_OBJ, pyrna_struct_keyframe_parse(), RPT_STORE, and TRUE.
PyObject* pyrna_struct_keyframe_insert (BPy_StructRNA * self, PyObject * args, PyObject * kw)
Definition at line 187 of file bpy_rna_anim.c.
References BKE_reports_init(), BPy_reports_to_error(), FLT_MAX, insert_keyframe(), MEM_freeN(), NULL, PYRNA_STRUCT_CHECK_OBJ, pyrna_struct_keyframe_parse(), RPT_STORE, and TRUE.
Variable Documentation
char pyrna_struct_driver_add_doc[]
Definition at line 269 of file bpy_rna_anim.c.
char pyrna_struct_driver_remove_doc[]
Definition at line 345 of file bpy_rna_anim.c.
char pyrna_struct_keyframe_delete_doc[]
Definition at line 219 of file bpy_rna_anim.c.
char pyrna_struct_keyframe_insert_doc[]
Definition at line 171 of file bpy_rna_anim.c.