Blender: rna_property.c File Reference
rna_property.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_property_types.h"
#include "WM_types.h"
Functions
void RNA_def_gameproperty (BlenderRNA *brna)
Variables
EnumPropertyItem gameproperty_type_items []
Detailed Description
Definition in file rna_property.c.
Function Documentation
void RNA_def_gameproperty (BlenderRNA * brna)
Definition at line 105 of file rna_property.c.
References MAX_PROPSTRING, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_DEBUG, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_float_funcs(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Variable Documentation
EnumPropertyItem gameproperty_type_items[]
Initial value:
 {
    {GPROP_BOOL, "BOOL", 0, "Boolean", "Boolean Property"},
    {GPROP_INT, "INT", 0, "Integer", "Integer Property"},
    {GPROP_FLOAT, "FLOAT", 0, "Float", "Floating-Point Property"},
    {GPROP_STRING, "STRING", 0, "String", "String Property"},
    {GPROP_TIME, "TIMER", 0, "Timer", "Timer Property"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 38 of file rna_property.c.
Referenced by OBJECT_OT_game_property_new().