Blender: render_result.h File Reference
render_result.h File Reference
Rendering
Defines
#define PASS_VECTOR_MAX 10000.0f
#define RR_USE_MEM 0
#define RR_USE_EXR 1
Functions
struct RenderResult * render_result_new (struct Render *re, struct rcti *partrct, int crop, int savebuffers)
struct RenderResult * render_result_new_full_sample (struct Render *re, struct ListBase *lb, struct rcti *partrct, int crop, int savebuffers)
struct RenderResult * render_result_new_from_exr (void *exrhandle, int rectx, int recty)
void render_result_merge (struct RenderResult *rr, struct RenderResult *rrpart)
void render_result_free (struct RenderResult *rr)
void render_result_free_list (struct ListBase *lb, struct RenderResult *rr)
void render_result_single_layer_begin (struct Render *re)
void render_result_single_layer_end (struct Render *re)
void render_result_exr_file_begin (struct Render *re)
void render_result_exr_file_end (struct Render *re)
void render_result_exr_file_merge (struct RenderResult *rr, struct RenderResult *rrpart)
void render_result_exr_file_path (struct Scene *scene, int sample, char *filepath)
int render_result_exr_file_read (struct Render *re, int sample)
int render_result_exr_file_read_path (struct RenderResult *rr, const char *filepath)
struct ImBuf * render_result_rect_to_ibuf (struct RenderResult *rr, struct RenderData *rd)
void render_result_rect_from_ibuf (struct RenderResult *rr, struct RenderData *rd, struct ImBuf *ibuf)
void render_result_rect_fill_zero (struct RenderResult *rr)
void render_result_rect_get_pixels (struct RenderResult *rr, struct RenderData *rd, unsigned int *rect, int rectx, int recty)
Detailed Description
Definition in file render_result.h.
Define Documentation
#define PASS_VECTOR_MAX 10000.0f
Definition at line 35 of file render_result.h.
Referenced by add_transp_speed(), get_avg_speed(), RE_zbuf_accumulate_vecblur(), render_layer_add_pass(), reset_sky_speed(), reset_sky_speedvectors(), and zbuffer_transp_shade().
#define RR_USE_EXR 1
Definition at line 38 of file render_result.h.
Referenced by threaded_tile_processor().
#define RR_USE_MEM 0
Definition at line 37 of file render_result.h.
Referenced by do_part_thread(), do_render_blur_3d(), do_render_composite_fields_blur_3d(), do_render_fields_3d(), do_render_fields_blur_3d(), RE_engine_begin_result(), render_result_exr_file_read(), and threaded_tile_processor().
Function Documentation
void render_result_exr_file_begin (struct Render * re)
Definition at line 889 of file render_result.c.
References RenderResult::exrhandle, FILE_MAX, IMB_exrtile_begin_write(), RenderResult::next, Render::partx, Render::party, RenderResult::rectx, RenderResult::recty, render_result_exr_file_path(), Render::result, RenderResult::sample_nr, Render::scene, and str.
Referenced by threaded_tile_processor().
void render_result_exr_file_end (struct Render * re)
Definition at line 903 of file render_result.c.
References RenderResult::exrhandle, Render::fullresult, IMB_exr_close(), RenderResult::next, NULL, render_result_exr_file_read(), render_result_free_list(), Render::result, and save_empty_result_tiles().
Referenced by threaded_tile_processor().
void render_result_exr_file_merge (struct RenderResult * rr, struct RenderResult * rrpart)
Definition at line 921 of file render_result.c.
References RenderResult::next, and save_render_result_tile().
Referenced by do_part_thread().
void render_result_exr_file_path (struct Scene * scene, int sample, char * filepath)
Definition at line 928 of file render_result.c.
References BLI_make_file_string(), BLI_snprintf(), BLI_splitdirstring(), BLI_strncpy(), BLI_temporary_dir(), FILE_MAX, FILE_MAXFILE, G, Scene::id, MAX_ID_NAME, ImBuf::name, and ID::name.
Referenced by RE_is_rendering_allowed(), render_result_exr_file_begin(), and render_result_exr_file_read().
int render_result_exr_file_read (struct Render * re, int sample)
Definition at line 944 of file render_result.c.
References Render::disprect, FALSE, FILE_MAX, RE_FreeRenderResult(), render_result_exr_file_path(), render_result_exr_file_read_path(), render_result_new(), Render::result, RR_USE_MEM, Render::scene, str, and TRUE.
Referenced by do_merge_fullsample(), RE_ReadRenderResult(), and render_result_exr_file_end().
int render_result_exr_file_read_path (struct RenderResult * rr, const char * filepath)
Definition at line 968 of file render_result.c.
References BLI_strncpy(), RenderPass::channels, ListBase::first, get_pass_name(), IMB_exr_begin_read(), IMB_exr_close(), IMB_exr_get_handle(), IMB_exr_read_channels(), IMB_exr_set_channel(), RenderResult::layers, RenderPass::name, RenderLayer::name, RenderPass::next, RenderLayer::next, NULL, RenderLayer::passes, RenderPass::passtype, RenderPass::rect, RenderLayer::rectf, RenderResult::rectx, RenderResult::recty, and SCE_PASS_COMBINED.
Referenced by RE_result_load_from_file(), and render_result_exr_file_read().
void render_result_free (struct RenderResult * rr)
Definition at line 61 of file render_result.c.
References RenderLayer::acolrect, BLI_remlink(), ListBase::first, RenderResult::layers, MEM_freeN(), NULL, RenderLayer::passes, RenderPass::rect, RenderResult::rect32, RenderLayer::rectf, RenderResult::rectf, RenderResult::rectz, RenderLayer::scolrect, and RenderResult::text.
Referenced by do_render_blur_3d(), do_render_composite_fields_blur_3d(), do_render_fields_3d(), do_render_fields_blur_3d(), RE_engine_render(), RE_FreeAllRenderResults(), RE_FreeRender(), RE_FreeRenderResult(), RE_InitState(), render_result_free_list(), and threaded_tile_processor().
void render_result_free_list (struct ListBase * lb, struct RenderResult * rr)
Definition at line 96 of file render_result.c.
References BLI_remlink(), ListBase::first, RenderResult::next, and render_result_free().
Referenced by RE_engine_end_result(), RE_engine_render(), render_result_exr_file_end(), and threaded_tile_processor().
void render_result_merge (struct RenderResult * rr, struct RenderResult * rrpart)
Definition at line 680 of file render_result.c.
References RenderPass::channels, do_merge_tile(), ListBase::first, RenderResult::layers, RenderPass::next, RenderLayer::next, RenderLayer::passes, RenderPass::rect, and RenderLayer::rectf.
Referenced by do_part_thread(), do_render_fields_blur_3d(), and RE_engine_end_result().
struct RenderResult* render_result_new (struct Render * re, struct rcti * partrct, int crop, int savebuffers) [read]
Definition at line 417 of file render_result.c.
References RenderData::actlay, BLI_addtail(), BLI_strncpy(), RenderResult::crop, Render::disprect, RenderResult::exrhandle, ListBase::first, IMB_exr_add_channel(), IMB_exr_get_handle(), SceneRenderLayer::lay, RenderLayer::lay, SceneRenderLayer::lay_zmask, RenderLayer::lay_zmask, RenderResult::layers, RenderData::layers, RenderLayer::layflag, SceneRenderLayer::layflag, SceneRenderLayer::light_override, RenderLayer::light_override, SceneRenderLayer::mat_override, RenderLayer::mat_override, MEM_callocN(), MEM_mapallocN(), SceneRenderLayer::name, RenderLayer::name, SceneRenderLayer::next, NULL, SceneRenderLayer::pass_xor, RenderLayer::pass_xor, SceneRenderLayer::passflag, RenderLayer::passflag, Render::r, R_SINGLE_LAYER, RenderLayer::rectf, RenderLayer::rectx, RenderResult::rectx, RenderLayer::recty, RenderResult::recty, render_layer_add_pass(), RenderResult::renrect, SCE_LAY_DISABLE, SCE_PASS_AO, SCE_PASS_COMBINED, SCE_PASS_DIFFUSE, SCE_PASS_DIFFUSE_COLOR, SCE_PASS_DIFFUSE_DIRECT, SCE_PASS_DIFFUSE_INDIRECT, SCE_PASS_EMIT, SCE_PASS_ENVIRONMENT, SCE_PASS_GLOSSY_COLOR, SCE_PASS_GLOSSY_DIRECT, SCE_PASS_GLOSSY_INDIRECT, SCE_PASS_INDEXMA, SCE_PASS_INDEXOB, SCE_PASS_INDIRECT, SCE_PASS_MIST, SCE_PASS_NORMAL, SCE_PASS_RAYHITS, SCE_PASS_REFLECT, SCE_PASS_REFRACT, SCE_PASS_RGBA, SCE_PASS_SHADOW, SCE_PASS_SPEC, SCE_PASS_TRANSM_COLOR, SCE_PASS_TRANSM_DIRECT, SCE_PASS_TRANSM_INDIRECT, SCE_PASS_UV, SCE_PASS_VECTOR, SCE_PASS_Z, RenderData::scemode, RenderResult::tilerect, Render::winx, Render::winy, rcti::xmax, rcti::xmin, RenderResult::xof, rcti::ymax, rcti::ymin, and RenderResult::yof.
Referenced by do_part_thread(), do_render_blur_3d(), do_render_composite_fields_blur_3d(), do_render_fields_3d(), do_render_fields_blur_3d(), RE_engine_begin_result(), RE_engine_render(), render_result_exr_file_read(), render_result_new_full_sample(), and threaded_tile_processor().
struct RenderResult* render_result_new_from_exr (void * exrhandle, int rectx, int recty) [read]
Definition at line 619 of file render_result.c.
References ListBase::first, IMB_exr_multilayer_convert(), RenderResult::layers, MEM_callocN(), ml_addlayer_cb(), ml_addpass_cb(), RenderPass::next, RenderLayer::next, RenderLayer::passes, RenderLayer::rectx, RenderPass::rectx, RenderResult::rectx, RenderLayer::recty, RenderPass::recty, and RenderResult::recty.
Referenced by RE_MultilayerConvert().
struct RenderResult* render_result_new_full_sample (struct Render * re, struct ListBase * lb, struct rcti * partrct, int crop, int savebuffers) [read]
Definition at line 568 of file render_result.c.
References BLI_addtail(), ListBase::first, Render::osa, render_result_new(), and RenderResult::sample_nr.
Referenced by do_part_thread(), and threaded_tile_processor().
void render_result_rect_fill_zero (struct RenderResult * rr)
Definition at line 1093 of file render_result.c.
References MEM_callocN(), RenderResult::rect32, RenderResult::rectf, RenderResult::rectx, and RenderResult::recty.
Referenced by do_render_seq().
void render_result_rect_from_ibuf (struct RenderResult * rr, struct RenderData * rd, struct ImBuf * ibuf)
Definition at line 1056 of file render_result.c.
References RenderData::color_mgt_flag, IB_PROFILE_LINEAR_RGB, IB_PROFILE_SRGB, IMB_buffer_float_from_float(), MEM_freeN(), MEM_mallocN(), NULL, ImBuf::profile, R_COLOR_MANAGEMENT, R_COLOR_MANAGEMENT_PREDIVIDE, ImBuf::rect, RenderResult::rect32, ImBuf::rect_float, RenderResult::rectf, RenderResult::rectx, and RenderResult::recty.
Referenced by do_render_seq().
void render_result_rect_get_pixels (struct RenderResult * rr, struct RenderData * rd, unsigned int * rect, int rectx, int recty)
Definition at line 1103 of file render_result.c.
References RenderData::color_mgt_flag, ImBuf::dither, IB_PROFILE_LINEAR_RGB, IB_PROFILE_SRGB, IMB_buffer_byte_from_float(), R_COLOR_MANAGEMENT, R_COLOR_MANAGEMENT_PREDIVIDE, RenderResult::rect32, RenderResult::rectf, RenderResult::rectx, and RenderResult::recty.
Referenced by RE_ResultGet32().
struct ImBuf* render_result_rect_to_ibuf (struct RenderResult * rr, struct RenderData * rd) [read]
Definition at line 1018 of file render_result.c.
References BKE_imtype_valid_depths(), RenderData::color_mgt_flag, ImBuf::dither, RenderData::dither_intensity, ImBuf::flags, IB_cm_predivide, IB_PROFILE_LINEAR_RGB, IB_PROFILE_SRGB, if(), RenderData::im_format, IMB_allocImBuf(), IMB_color_to_bw(), IMB_dupImBuf(), IMB_float_from_rect(), IMB_freeImBuf(), ImageFormatData::imtype, ImageFormatData::planes, ImBuf::profile, R_COLOR_MANAGEMENT, R_COLOR_MANAGEMENT_PREDIVIDE, R_IMF_CHAN_DEPTH_12, R_IMF_CHAN_DEPTH_16, R_IMF_CHAN_DEPTH_24, R_IMF_CHAN_DEPTH_32, R_IMF_PLANES_BW, ImBuf::rect, RenderResult::rect32, ImBuf::rect_float, RenderResult::rectf, RenderResult::rectx, RenderResult::recty, RenderResult::rectz, and ImBuf::zbuf_float.
Referenced by do_write_image_or_movie().
void render_result_single_layer_begin (struct Render * re)
Definition at line 774 of file render_result.c.
References NULL, Render::pushedresult, RE_FreeRenderResult(), and Render::result.
Referenced by render_initialize_from_main().
void render_result_single_layer_end (struct Render * re)
Definition at line 786 of file render_result.c.
References RenderData::actlay, BLI_addtail(), BLI_remlink(), ListBase::first, RenderData::layers, RenderResult::layers, SceneRenderLayer::name, SceneRenderLayer::next, NULL, Render::pushedresult, Scene::r, Render::r, RE_FreeRenderResult(), RE_GetRenderLayer(), RenderResult::rectx, RenderResult::recty, Render::result, and Render::scene.
Referenced by do_render_composite_fields_blur_3d().