Blender: IKPlugin Struct Reference
IKPlugin Struct Reference
#include <ikplugin_api.h>
Public Attributes
void(* initialize_tree_func)(struct Scene *scene, struct Object *ob, float ctime)
void(* execute_tree_func)(struct Scene *scene, struct Object *ob, struct bPoseChannel *pchan, float ctime)
void(* release_tree_func)(struct Scene *scene, struct Object *ob, float ctime)
void(* remove_armature_func)(struct bPose *pose)
void(* clear_cache)(struct bPose *pose)
void(* update_param)(struct bPose *pose)
void(* test_constraint)(struct Object *ob, struct bConstraint *cons)
Detailed Description
Definition at line 47 of file ikplugin_api.h.
Member Data Documentation
void(* IKPlugin::clear_cache)(struct bPose *pose)
Definition at line 52 of file ikplugin_api.h.
Referenced by BIK_clear_cache().
void(* IKPlugin::execute_tree_func)(struct Scene *scene, struct Object *ob, struct bPoseChannel *pchan, float ctime)
Definition at line 49 of file ikplugin_api.h.
Referenced by BIK_execute_tree().
void(* IKPlugin::initialize_tree_func)(struct Scene *scene, struct Object *ob, float ctime)
Definition at line 48 of file ikplugin_api.h.
Referenced by BIK_initialize_tree().
void(* IKPlugin::release_tree_func)(struct Scene *scene, struct Object *ob, float ctime)
Definition at line 50 of file ikplugin_api.h.
Referenced by BIK_release_tree().
void(* IKPlugin::remove_armature_func)(struct bPose *pose)
Definition at line 51 of file ikplugin_api.h.
Referenced by BIK_clear_data().
void(* IKPlugin::test_constraint)(struct Object *ob, struct bConstraint *cons)
Definition at line 54 of file ikplugin_api.h.
Referenced by BIK_test_constraint().
void(* IKPlugin::update_param)(struct bPose *pose)
Definition at line 53 of file ikplugin_api.h.
Referenced by BIK_update_param().
The documentation for this struct was generated from the following file:
ikplugin_api.h