Blender: light.cpp File Reference
light.cpp File Reference
#include "device.h"
#include "light.h"
#include "mesh.h"
#include "object.h"
#include "scene.h"
#include "shader.h"
#include "util_foreach.h"
#include "util_progress.h"
#include "kernel_montecarlo.h"
Functions
static CCL_NAMESPACE_BEGIN void dump_background_pixels (Device *device, DeviceScene *dscene, int res, vector< float3 > &pixels)
Function Documentation
static CCL_NAMESPACE_BEGIN void dump_background_pixels (Device * device, DeviceScene * dscene, int res, vector< float3 > & pixels) [static]
Definition at line 33 of file light.cpp.
References __float_as_int(), Device::const_copy_to(), DeviceScene::data, device_memory::data_pointer, device_memory::device_pointer, make_uint4(), Device::mem_alloc(), Device::mem_copy_from(), Device::mem_copy_to(), Device::mem_free(), MEM_READ_ONLY, MEM_WRITE_ONLY, device_memory::memory_size(), device_vector< T >::resize(), DeviceTask::SHADER, SHADER_EVAL_BACKGROUND, DeviceTask::shader_eval_type, DeviceTask::shader_input, DeviceTask::shader_output, DeviceTask::shader_w, DeviceTask::shader_x, device_vector< T >::size(), DeviceTask::split_max_size(), Device::task_add(), Device::task_wait(), float4::x, float4::y, and float4::z.
Referenced by LightManager::device_update_background().