Blender: CConstExpr Class Reference
CConstExpr Class Reference
#include <ConstExpr.h>
Public Member Functions
virtual bool MergeExpression (CExpression *otherexpr)
void BroadcastOperators (VALUE_OPERATOR op)
virtual unsigned char GetExpressionID ()
CExpression * CheckLink (std::vector< CBrokenLinkInfo * > &brokenlinks)
bool NeedsRecalculated ()
void ClearModified ()
virtual double GetNumber ()
virtual CValue * Calculate ()
CConstExpr (CValue *constval)
CConstExpr ()
virtual ~CConstExpr ()
Detailed Description
Definition at line 25 of file ConstExpr.h.
Constructor & Destructor Documentation
CConstExpr::CConstExpr (CValue * constval)
Definition at line 33 of file ConstExpr.cpp.
CConstExpr::CConstExpr ()
Definition at line 27 of file ConstExpr.cpp.
CConstExpr::~CConstExpr () [virtual]
Definition at line 45 of file ConstExpr.cpp.
References CValue::Release().
Member Function Documentation
void CConstExpr::BroadcastOperators (VALUE_OPERATOR op) [virtual]
Implements CExpression.
Definition at line 119 of file ConstExpr.cpp.
References assertd, and CValue::SetColorOperator().
CValue * CConstExpr::Calculate () [virtual]
Implements CExpression.
Definition at line 64 of file ConstExpr.cpp.
References CValue::AddRef().
CExpression * CConstExpr::CheckLink (std::vector< CBrokenLinkInfo * > & brokenlinks) [virtual]
Implements CExpression.
Definition at line 100 of file ConstExpr.cpp.
References CExpression::AddRef(), assertd, CValue::IsReleaseRequested(), and CExpression::Release().
void CConstExpr::ClearModified () [virtual]
Implements CExpression.
Definition at line 75 of file ConstExpr.cpp.
References CValue::SetAffected(), and CValue::SetModified().
unsigned char CConstExpr::GetExpressionID () [virtual]
Implements CExpression.
Definition at line 57 of file ConstExpr.cpp.
References CExpression::CCONSTEXPRESSIONID.
double CConstExpr::GetNumber () [virtual]
Definition at line 86 of file ConstExpr.cpp.
bool CConstExpr::MergeExpression (CExpression * otherexpr) [virtual]
Implements CExpression.
Definition at line 127 of file ConstExpr.cpp.
References assertd.
bool CConstExpr::NeedsRecalculated () [virtual]
Implements CExpression.
Definition at line 93 of file ConstExpr.cpp.
References CValue::IsAffected().
The documentation for this class was generated from the following files:
ConstExpr.h
ConstExpr.cpp