Blender: ImageViewport Class Reference
ImageViewport Class Reference
class for viewport access
#include <ImageViewport.h>
Public Member Functions
ImageViewport (void)
constructor
virtual ~ImageViewport (void)
destructor
bool getWhole (void)
is whole buffer used
void setWhole (bool whole)
set whole buffer use
bool getAlpha (void)
is alpha channel used
void setAlpha (bool alpha)
set whole buffer use
short * getCaptureSize (void)
get capture size in viewport
void setCaptureSize (short *size=NULL)
set capture size in viewport
GLint * getPosition (void)
get position in viewport
void setPosition (GLint *pos=NULL)
set position in viewport
Protected Member Functions
virtual void calcImage (unsigned int texId, double ts)
capture image from viewport
GLint * getViewportSize (void)
get viewport size
Protected Attributes
GLint m_viewport [4]
frame buffer rectangle
short m_capSize [2]
size of captured area
bool m_whole
use whole viewport
bool m_alpha
use alpha channel
GLint m_position [2]
position of capture rectangle in viewport
GLint m_upLeft [2]
upper left point for capturing
BYTE * m_viewportImage
buffer to copy viewport
bool m_texInit
texture is initialized
Detailed Description
class for viewport access
Definition at line 37 of file ImageViewport.h.
Constructor & Destructor Documentation
ImageViewport::ImageViewport (void)
constructor
Definition at line 42 of file ImageViewport.cpp.
References BYTE, RAS_Rect::GetBottom(), KX_KetsjiEngine::GetCanvas(), RAS_Rect::GetHeight(), RAS_Rect::GetLeft(), getViewportSize(), RAS_Rect::GetWidth(), RAS_ICanvas::GetWindowArea(), KX_GetActiveEngine(), m_viewport, m_viewportImage, and setWhole().
ImageViewport::~ImageViewport (void) [virtual]
destructor
Definition at line 59 of file ImageViewport.cpp.
References m_viewportImage.
Member Function Documentation
void ImageViewport::calcImage (unsigned int texId, double ts) [protected, virtual]
capture image from viewport
Reimplemented from ImageBase.
Reimplemented in ImageRender.
Definition at line 119 of file ImageViewport.cpp.
References ImageBase::calcSize(), ImageBase::filterImage(), ImageBase::init(), loadTexture(), m_alpha, ImageBase::m_avail, m_capSize, ImageBase::m_flip, ImageBase::m_image, ImageBase::m_pyfilter, ImageBase::m_scaleChange, ImageBase::m_size, m_texInit, m_upLeft, m_viewportImage, and NULL.
bool ImageViewport::getAlpha (void) [inline]
is alpha channel used
Definition at line 52 of file ImageViewport.h.
References m_alpha.
short* ImageViewport::getCaptureSize (void) [inline]
get capture size in viewport
Definition at line 57 of file ImageViewport.h.
References m_capSize.
GLint* ImageViewport::getPosition (void) [inline]
get position in viewport
Definition at line 62 of file ImageViewport.h.
References m_position.
GLint* ImageViewport::getViewportSize (void) [inline, protected]
get viewport size
Definition at line 91 of file ImageViewport.h.
References m_viewport.
Referenced by ImageViewport(), setCaptureSize(), setPosition(), and setWhole().
bool ImageViewport::getWhole (void) [inline]
is whole buffer used
Definition at line 47 of file ImageViewport.h.
References m_whole.
void ImageViewport::setAlpha (bool alpha) [inline]
set whole buffer use
Definition at line 54 of file ImageViewport.h.
References m_alpha.
Referenced by ImageViewport_setAlpha().
void ImageViewport::setCaptureSize (short * size = NULL)
set capture size in viewport
Definition at line 84 of file ImageViewport.cpp.
References getViewportSize(), ImageBase::init(), m_capSize, m_whole, NULL, and setPosition().
Referenced by ImageViewport_setCaptureSize().
void ImageViewport::setPosition (GLint * pos = NULL)
set position in viewport
Definition at line 104 of file ImageViewport.cpp.
References getViewportSize(), m_capSize, m_position, m_upLeft, m_viewport, and NULL.
Referenced by ImageViewport_setPosition(), setCaptureSize(), and setWhole().
void ImageViewport::setWhole (bool whole)
set whole buffer use
Definition at line 64 of file ImageViewport.cpp.
References ImageBase::calcSize(), getViewportSize(), ImageBase::init(), m_capSize, m_position, m_whole, and setPosition().
Referenced by ImageViewport(), and ImageViewport_setWhole().
Member Data Documentation
bool ImageViewport::m_alpha [protected]
use alpha channel
Definition at line 75 of file ImageViewport.h.
Referenced by calcImage(), getAlpha(), and setAlpha().
short ImageViewport::m_capSize[2] [protected]
size of captured area
Definition at line 71 of file ImageViewport.h.
Referenced by calcImage(), getCaptureSize(), ImageRender::Render(), setCaptureSize(), setPosition(), and setWhole().
GLint ImageViewport::m_position[2] [protected]
position of capture rectangle in viewport
Definition at line 78 of file ImageViewport.h.
Referenced by getPosition(), ImageRender::Render(), setPosition(), and setWhole().
bool ImageViewport::m_texInit [protected]
texture is initialized
Definition at line 85 of file ImageViewport.h.
Referenced by calcImage().
GLint ImageViewport::m_upLeft[2] [protected]
upper left point for capturing
Definition at line 80 of file ImageViewport.h.
Referenced by calcImage(), and setPosition().
GLint ImageViewport::m_viewport[4] [protected]
frame buffer rectangle
Definition at line 68 of file ImageViewport.h.
Referenced by getViewportSize(), ImageViewport(), and setPosition().
BYTE* ImageViewport::m_viewportImage [protected]
buffer to copy viewport
Definition at line 83 of file ImageViewport.h.
Referenced by calcImage(), ImageViewport(), and ~ImageViewport().
bool ImageViewport::m_whole [protected]
use whole viewport
Definition at line 73 of file ImageViewport.h.
Referenced by getWhole(), setCaptureSize(), and setWhole().
The documentation for this class was generated from the following files:
ImageViewport.h
ImageViewport.cpp