Blender: NOD_texture.h File Reference
NOD_texture.h File Reference
nodes
#include "BKE_node.h"
Functions
void register_node_type_tex_group (struct bNodeTreeType *ttype)
void register_node_type_tex_forloop (struct bNodeTreeType *ttype)
void register_node_type_tex_whileloop (struct bNodeTreeType *ttype)
void register_node_type_tex_math (struct bNodeTreeType *ttype)
void register_node_type_tex_mix_rgb (struct bNodeTreeType *ttype)
void register_node_type_tex_valtorgb (struct bNodeTreeType *ttype)
void register_node_type_tex_valtonor (struct bNodeTreeType *ttype)
void register_node_type_tex_rgbtobw (struct bNodeTreeType *ttype)
void register_node_type_tex_output (struct bNodeTreeType *ttype)
void register_node_type_tex_viewer (struct bNodeTreeType *ttype)
void register_node_type_tex_checker (struct bNodeTreeType *ttype)
void register_node_type_tex_texture (struct bNodeTreeType *ttype)
void register_node_type_tex_bricks (struct bNodeTreeType *ttype)
void register_node_type_tex_image (struct bNodeTreeType *ttype)
void register_node_type_tex_curve_rgb (struct bNodeTreeType *ttype)
void register_node_type_tex_curve_time (struct bNodeTreeType *ttype)
void register_node_type_tex_invert (struct bNodeTreeType *ttype)
void register_node_type_tex_hue_sat (struct bNodeTreeType *ttype)
void register_node_type_tex_coord (struct bNodeTreeType *ttype)
void register_node_type_tex_distance (struct bNodeTreeType *ttype)
void register_node_type_tex_rotate (struct bNodeTreeType *ttype)
void register_node_type_tex_translate (struct bNodeTreeType *ttype)
void register_node_type_tex_scale (struct bNodeTreeType *ttype)
void register_node_type_tex_at (struct bNodeTreeType *ttype)
void register_node_type_tex_compose (struct bNodeTreeType *ttype)
void register_node_type_tex_decompose (struct bNodeTreeType *ttype)
void register_node_type_tex_proc_voronoi (struct bNodeTreeType *ttype)
void register_node_type_tex_proc_blend (struct bNodeTreeType *ttype)
void register_node_type_tex_proc_magic (struct bNodeTreeType *ttype)
void register_node_type_tex_proc_marble (struct bNodeTreeType *ttype)
void register_node_type_tex_proc_clouds (struct bNodeTreeType *ttype)
void register_node_type_tex_proc_wood (struct bNodeTreeType *ttype)
void register_node_type_tex_proc_musgrave (struct bNodeTreeType *ttype)
void register_node_type_tex_proc_noise (struct bNodeTreeType *ttype)
void register_node_type_tex_proc_stucci (struct bNodeTreeType *ttype)
void register_node_type_tex_proc_distnoise (struct bNodeTreeType *ttype)
Variables
bNodeTreeType ntreeType_Texture
Detailed Description
Definition in file NOD_texture.h.
Function Documentation
void register_node_type_tex_at (struct bNodeTreeType * ttype)
Definition at line 61 of file node_texture_at.c.
References exec(), NODE_CLASS_DISTORT, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_AT.
Referenced by registerTextureNodes().
void register_node_type_tex_bricks (struct bNodeTreeType * ttype)
Definition at line 123 of file node_texture_bricks.c.
References exec(), init(), NODE_CLASS_PATTERN, NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_BRICKS.
Referenced by registerTextureNodes().
void register_node_type_tex_checker (struct bNodeTreeType * ttype)
Definition at line 73 of file node_texture_checker.c.
References exec(), NODE_CLASS_PATTERN, NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_CHECKER.
Referenced by registerTextureNodes().
void register_node_type_tex_compose (struct bNodeTreeType * ttype)
Definition at line 60 of file node_texture_compose.c.
References exec(), NODE_CLASS_OP_COLOR, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_COMPOSE.
Referenced by registerTextureNodes().
void register_node_type_tex_coord (struct bNodeTreeType * ttype)
Definition at line 53 of file node_texture_coord.c.
References exec(), NODE_CLASS_INPUT, NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and TEX_NODE_COORD.
Referenced by registerTextureNodes().
void register_node_type_tex_curve_rgb (struct bNodeTreeType * ttype)
Definition at line 113 of file node_texture_curves.c.
References NODE_CLASS_OP_COLOR, node_copy_curves(), node_free_curves(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), rgb_exec(), rgb_init(), and TEX_NODE_CURVE_RGB.
Referenced by registerTextureNodes().
void register_node_type_tex_curve_time (struct bNodeTreeType * ttype)
Definition at line 69 of file node_texture_curves.c.
References NODE_CLASS_INPUT, node_copy_curves(), node_free_curves(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, TEX_NODE_CURVE_TIME, time_exec(), and time_init().
Referenced by registerTextureNodes().
void register_node_type_tex_decompose (struct bNodeTreeType * ttype)
Definition at line 81 of file node_texture_decompose.c.
References exec(), NODE_CLASS_OP_COLOR, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_DECOMPOSE.
Referenced by registerTextureNodes().
void register_node_type_tex_distance (struct bNodeTreeType * ttype)
Definition at line 64 of file node_texture_distance.c.
References exec(), NODE_CLASS_CONVERTOR, NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and TEX_NODE_DISTANCE.
Referenced by registerTextureNodes().
void register_node_type_tex_forloop (struct bNodeTreeType * ttype)
void register_node_type_tex_group (struct bNodeTreeType * ttype)
Definition at line 128 of file node_texture_common.c.
References group_execute(), group_freeexec(), group_initexec(), NODE_CLASS_GROUP, NODE_CONST_OUTPUT, NODE_GROUP, node_group_edit_clear(), node_group_edit_get(), node_group_edit_set(), node_group_init(), node_group_label(), node_group_template(), node_group_valid(), node_group_verify(), NODE_OPTIONS, node_type_base(), node_type_exec_new(), node_type_group_edit(), node_type_init(), node_type_label(), node_type_size(), node_type_socket_templates(), node_type_template(), node_type_update(), node_type_valid(), nodeRegisterType(), and NULL.
Referenced by registerTextureNodes().
void register_node_type_tex_hue_sat (struct bNodeTreeType * ttype)
Definition at line 95 of file node_texture_hueSatVal.c.
References exec(), NODE_CLASS_OP_COLOR, NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_HUE_SAT.
Referenced by registerTextureNodes().
void register_node_type_tex_image (struct bNodeTreeType * ttype)
Definition at line 98 of file node_texture_image.c.
References exec(), init(), NODE_CLASS_INPUT, node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and TEX_NODE_IMAGE.
Referenced by registerTextureNodes().
void register_node_type_tex_invert (struct bNodeTreeType * ttype)
Definition at line 66 of file node_texture_invert.c.
References exec(), NODE_CLASS_OP_COLOR, NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_INVERT.
Referenced by registerTextureNodes().
void register_node_type_tex_math (struct bNodeTreeType * ttype)
Definition at line 189 of file node_texture_math.c.
References exec(), NODE_CLASS_CONVERTOR, node_math_label(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_label(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and TEX_NODE_MATH.
Referenced by registerTextureNodes().
void register_node_type_tex_mix_rgb (struct bNodeTreeType * ttype)
Definition at line 67 of file node_texture_mixRgb.c.
References exec(), node_blend_label(), NODE_CLASS_OP_COLOR, NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_label(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_MIX_RGB.
Referenced by registerTextureNodes().
void register_node_type_tex_output (struct bNodeTreeType * ttype)
Definition at line 161 of file node_texture_output.c.
References copy(), exec(), init(), NODE_CLASS_OUTPUT, node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and TEX_NODE_OUTPUT.
Referenced by registerTextureNodes().
void register_node_type_tex_proc_blend (struct bNodeTreeType * ttype)
Referenced by registerTextureNodes().
void register_node_type_tex_proc_clouds (struct bNodeTreeType * ttype)
Referenced by registerTextureNodes().
void register_node_type_tex_proc_distnoise (struct bNodeTreeType * ttype)
Referenced by registerTextureNodes().
void register_node_type_tex_proc_magic (struct bNodeTreeType * ttype)
Referenced by registerTextureNodes().
void register_node_type_tex_proc_marble (struct bNodeTreeType * ttype)
Referenced by registerTextureNodes().
void register_node_type_tex_proc_musgrave (struct bNodeTreeType * ttype)
Referenced by registerTextureNodes().
void register_node_type_tex_proc_noise (struct bNodeTreeType * ttype)
Referenced by registerTextureNodes().
void register_node_type_tex_proc_stucci (struct bNodeTreeType * ttype)
Referenced by registerTextureNodes().
void register_node_type_tex_proc_voronoi (struct bNodeTreeType * ttype)
Referenced by registerTextureNodes().
void register_node_type_tex_proc_wood (struct bNodeTreeType * ttype)
Referenced by registerTextureNodes().
void register_node_type_tex_rgbtobw (struct bNodeTreeType * ttype)
Definition at line 103 of file node_texture_valToRgb.c.
References NODE_CLASS_CONVERTOR, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), rgbtobw_exec(), and TEX_NODE_RGBTOBW.
Referenced by registerTextureNodes().
void register_node_type_tex_rotate (struct bNodeTreeType * ttype)
Definition at line 98 of file node_texture_rotate.c.
References exec(), NODE_CLASS_DISTORT, NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_ROTATE.
Referenced by registerTextureNodes().
void register_node_type_tex_scale (struct bNodeTreeType * ttype)
Definition at line 71 of file node_texture_scale.c.
References exec(), NODE_CLASS_DISTORT, NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_SCALE.
Referenced by registerTextureNodes().
void register_node_type_tex_texture (struct bNodeTreeType * ttype)
Definition at line 98 of file node_texture_texture.c.
References exec(), NODE_CLASS_INPUT, NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_TEXTURE.
Referenced by registerTextureNodes().
void register_node_type_tex_translate (struct bNodeTreeType * ttype)
Definition at line 67 of file node_texture_translate.c.
References exec(), NODE_CLASS_DISTORT, NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_TRANSLATE.
Referenced by registerTextureNodes().
void register_node_type_tex_valtonor (struct bNodeTreeType * ttype)
Definition at line 83 of file node_texture_valToNor.c.
References exec(), NODE_CLASS_CONVERTOR, NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_VALTONOR.
Referenced by registerTextureNodes().
void register_node_type_tex_valtorgb (struct bNodeTreeType * ttype)
Definition at line 65 of file node_texture_valToRgb.c.
References NODE_CLASS_CONVERTOR, node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), TEX_NODE_VALTORGB, valtorgb_exec(), and valtorgb_init().
Referenced by registerTextureNodes().
void register_node_type_tex_viewer (struct bNodeTreeType * ttype)
Definition at line 59 of file node_texture_viewer.c.
References exec(), NODE_CLASS_OUTPUT, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), NULL, and TEX_NODE_VIEWER.
Referenced by registerTextureNodes().
void register_node_type_tex_whileloop (struct bNodeTreeType * ttype)
Variable Documentation
bNodeTreeType ntreeType_Texture
Definition at line 115 of file node_texture_tree.c.
Referenced by ntreeGetType().