Blender: svm_displace.h File Reference
svm_displace.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void svm_node_set_bump (ShaderData *sd, float *stack, uint c_offset, uint x_offset, uint y_offset)
__device void svm_node_set_displacement (ShaderData *sd, float *stack, uint fac_offset)
Function Documentation
CCL_NAMESPACE_BEGIN __device void svm_node_set_bump (ShaderData * sd, float * stack, uint c_offset, uint x_offset, uint y_offset)
Definition at line 23 of file svm_displace.h.
References cross(), dot(), ShaderData::dP, differential3::dx, differential3::dy, fabsf, ShaderData::N, normalize(), signf(), and stack_load_float().
Referenced by svm_eval_nodes().
__device void svm_node_set_displacement (ShaderData * sd, float * stack, uint fac_offset)
Definition at line 45 of file svm_displace.h.
References ShaderData::N, ShaderData::P, and stack_load_float().
Referenced by svm_eval_nodes().