Blender: KX_IPhysicsController Class Reference
KX_IPhysicsController Class Reference
#include <KX_IPhysicsController.h>
Public Member Functions
KX_IPhysicsController (bool dyna, bool sensor, bool compound, void *userdata)
virtual ~KX_IPhysicsController ()
virtual void applyImpulse (const MT_Point3 &attach, const MT_Vector3 &impulse)=0
virtual void SetObject (SG_IObject *object)=0
virtual void setMargin (float collisionMargin)=0
virtual void RelativeTranslate (const MT_Vector3 &dloc, bool local)=0
virtual void RelativeRotate (const MT_Matrix3x3 &drot, bool local)=0
virtual void ApplyTorque (const MT_Vector3 &torque, bool local)=0
virtual void ApplyForce (const MT_Vector3 &force, bool local)=0
virtual MT_Vector3 GetLinearVelocity ()=0
virtual MT_Vector3 GetAngularVelocity ()=0
virtual MT_Vector3 GetVelocity (const MT_Point3 &pos)=0
virtual void SetAngularVelocity (const MT_Vector3 &ang_vel, bool local)=0
virtual void SetLinearVelocity (const MT_Vector3 &lin_vel, bool local)=0
virtual void resolveCombinedVelocities (float linvelX, float linvelY, float linvelZ, float angVelX, float angVelY, float angVelZ)=0
virtual void getOrientation (MT_Quaternion &orn)=0
virtual void setOrientation (const MT_Matrix3x3 &orn)=0
virtual void SetTransform ()=0
virtual void setPosition (const MT_Point3 &pos)=0
virtual void setScaling (const MT_Vector3 &scaling)=0
virtual MT_Scalar GetMass ()=0
virtual void SetMass (MT_Scalar newmass)=0
virtual float GetLinVelocityMin ()=0
virtual void SetLinVelocityMin (float newmass)=0
virtual float GetLinVelocityMax ()=0
virtual void SetLinVelocityMax (float newmass)=0
virtual MT_Vector3 GetLocalInertia ()=0
virtual MT_Vector3 getReactionForce ()=0
virtual void setRigidBody (bool rigid)=0
virtual void AddCompoundChild (KX_IPhysicsController *child)=0
virtual void RemoveCompoundChild (KX_IPhysicsController *child)=0
virtual void SuspendDynamics (bool ghost=false)=0
virtual void RestoreDynamics ()=0
virtual SG_Controller * GetReplica (class SG_Node *destnode)=0
void SetDyna (bool isDynamic)
void SetSensor (bool isSensor)
bool IsDyna (void)
bool IsSensor (void)
bool IsCompound (void)
virtual MT_Scalar GetRadius ()=0
virtual void SetSumoTransform (bool nondynaonly)=0
virtual void SetSimulatedTime (double time)=0
virtual bool Update (double time)=0
void * GetUserData ()
Protected Attributes
bool m_bDyna
bool m_bSensor
bool m_bCompound
bool m_suspendDynamics
void * m_userdata
Detailed Description
Physics Controller, a special kind of Scene Graph Transformation Controller. It get's callbacks from Physics in case a transformation change took place. Each time the scene graph get's updated, the controller get's a chance in the 'Update' method to reflect changed.
Definition at line 50 of file KX_IPhysicsController.h.
Constructor & Destructor Documentation
KX_IPhysicsController::KX_IPhysicsController (bool dyna, bool sensor, bool compound, void * userdata)
Definition at line 36 of file KX_IPhysicsController.cpp.
KX_IPhysicsController::~KX_IPhysicsController () [virtual]
Definition at line 46 of file KX_IPhysicsController.cpp.
Member Function Documentation
virtual void KX_IPhysicsController::AddCompoundChild (KX_IPhysicsController * child) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::SetParent().
virtual void KX_IPhysicsController::ApplyForce (const MT_Vector3 & force, bool local) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::ApplyForce(), and KX_IpoSGController::Update().
virtual void KX_IPhysicsController::applyImpulse (const MT_Point3 & attach, const MT_Vector3 & impulse) [pure virtual]
Implemented in KX_BulletPhysicsController.
virtual void KX_IPhysicsController::ApplyTorque (const MT_Vector3 & torque, bool local) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::ApplyTorque().
virtual MT_Vector3 KX_IPhysicsController::GetAngularVelocity () [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::GetAngularVelocity(), KX_GameObject::RemoveParent(), and KX_ConstraintActuator::Update().
virtual MT_Vector3 KX_IPhysicsController::GetLinearVelocity () [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::addLinearVelocity(), KX_GameObject::GetLinearVelocity(), and KX_ConstraintActuator::Update().
virtual float KX_IPhysicsController::GetLinVelocityMax () [pure virtual]
Implemented in KX_BulletPhysicsController.
virtual float KX_IPhysicsController::GetLinVelocityMin () [pure virtual]
Implemented in KX_BulletPhysicsController.
virtual MT_Vector3 KX_IPhysicsController::GetLocalInertia () [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::GetLocalInertia().
virtual MT_Scalar KX_IPhysicsController::GetMass () [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::GetMass().
virtual void KX_IPhysicsController::getOrientation (MT_Quaternion & orn) [pure virtual]
Implemented in KX_BulletPhysicsController.
virtual MT_Scalar KX_IPhysicsController::GetRadius () [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_ConstraintActuator::Update().
virtual MT_Vector3 KX_IPhysicsController::getReactionForce () [pure virtual]
Implemented in KX_BulletPhysicsController.
virtual SG_Controller* KX_IPhysicsController::GetReplica (class SG_Node * destnode) [pure virtual]
Implements SG_Controller.
Implemented in KX_BulletPhysicsController.
void* KX_IPhysicsController::GetUserData () [inline]
Reimplemented in KX_BulletPhysicsController.
Definition at line 131 of file KX_IPhysicsController.h.
References m_userdata.
Referenced by BL_ConvertBlenderObjects().
virtual MT_Vector3 KX_IPhysicsController::GetVelocity (const MT_Point3 & pos) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::GetVelocity(), and KX_GameObject::RemoveParent().
bool KX_IPhysicsController::IsCompound (void) [inline]
Definition at line 120 of file KX_IPhysicsController.h.
References m_bCompound.
Referenced by KX_GameObject::RemoveParent(), and KX_GameObject::SetParent().
bool KX_IPhysicsController::IsDyna (void) [inline]
Definition at line 112 of file KX_IPhysicsController.h.
References m_bDyna.
Referenced by KX_GameObject::RemoveParent(), KX_ConstraintActuator::Update(), and KX_GameObject::UpdateTransform().
bool KX_IPhysicsController::IsSensor (void) [inline]
Definition at line 116 of file KX_IPhysicsController.h.
References m_bSensor.
virtual void KX_IPhysicsController::RelativeRotate (const MT_Matrix3x3 & drot, bool local) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::ApplyRotation().
virtual void KX_IPhysicsController::RelativeTranslate (const MT_Vector3 & dloc, bool local) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::ApplyMovement().
virtual void KX_IPhysicsController::RemoveCompoundChild (KX_IPhysicsController * child) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::RemoveParent().
virtual void KX_IPhysicsController::resolveCombinedVelocities (float linvelX, float linvelY, float linvelZ, float angVelX, float angVelY, float angVelZ) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::ResolveCombinedVelocities().
virtual void KX_IPhysicsController::RestoreDynamics () [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::RemoveParent(), KX_GameObject::RestoreDynamics(), and KX_GameObject::Resume().
virtual void KX_IPhysicsController::SetAngularVelocity (const MT_Vector3 & ang_vel, bool local) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::RemoveParent(), KX_GameObject::setAngularVelocity(), and KX_ConstraintActuator::Update().
void KX_IPhysicsController::SetDyna (bool isDynamic) [inline]
Definition at line 104 of file KX_IPhysicsController.h.
References m_bDyna.
virtual void KX_IPhysicsController::SetLinearVelocity (const MT_Vector3 & lin_vel, bool local) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::addLinearVelocity(), KX_GameObject::RemoveParent(), KX_GameObject::setLinearVelocity(), and KX_ConstraintActuator::Update().
virtual void KX_IPhysicsController::SetLinVelocityMax (float newmass) [pure virtual]
Implemented in KX_BulletPhysicsController.
virtual void KX_IPhysicsController::SetLinVelocityMin (float newmass) [pure virtual]
Implemented in KX_BulletPhysicsController.
virtual void KX_IPhysicsController::setMargin (float collisionMargin) [pure virtual]
Implemented in KX_BulletPhysicsController.
virtual void KX_IPhysicsController::SetMass (MT_Scalar newmass) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_SCA_DynamicActuator::Update().
virtual void KX_IPhysicsController::SetObject (SG_IObject * object) [pure virtual]
Reimplemented from SG_Controller.
Implemented in KX_BulletPhysicsController.
virtual void KX_IPhysicsController::setOrientation (const MT_Matrix3x3 & orn) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::NodeSetLocalOrientation().
virtual void KX_IPhysicsController::setPosition (const MT_Point3 & pos) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::NodeSetLocalPosition().
virtual void KX_IPhysicsController::setRigidBody (bool rigid) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_SCA_DynamicActuator::Update().
virtual void KX_IPhysicsController::setScaling (const MT_Vector3 & scaling) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::NodeSetLocalScale(), and KX_GameObject::NodeSetRelativeScale().
void KX_IPhysicsController::SetSensor (bool isSensor) [inline]
Definition at line 108 of file KX_IPhysicsController.h.
References m_bSensor.
virtual void KX_IPhysicsController::SetSimulatedTime (double time) [pure virtual]
Implements SG_Controller.
Implemented in KX_BulletPhysicsController.
virtual void KX_IPhysicsController::SetSumoTransform (bool nondynaonly) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::UpdateTransform().
virtual void KX_IPhysicsController::SetTransform () [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::SynchronizeTransform().
virtual void KX_IPhysicsController::SuspendDynamics (bool ghost = false) [pure virtual]
Implemented in KX_BulletPhysicsController.
Referenced by KX_GameObject::SetParent(), KX_GameObject::Suspend(), and KX_GameObject::SuspendDynamics().
virtual bool KX_IPhysicsController::Update (double time) [pure virtual]
Implements SG_Controller.
Implemented in KX_BulletPhysicsController.
Member Data Documentation
bool KX_IPhysicsController::m_bCompound [protected]
Definition at line 56 of file KX_IPhysicsController.h.
Referenced by IsCompound().
bool KX_IPhysicsController::m_bDyna [protected]
Definition at line 54 of file KX_IPhysicsController.h.
Referenced by IsDyna(), and SetDyna().
bool KX_IPhysicsController::m_bSensor [protected]
Definition at line 55 of file KX_IPhysicsController.h.
Referenced by IsSensor(), and SetSensor().
bool KX_IPhysicsController::m_suspendDynamics [protected]
Definition at line 57 of file KX_IPhysicsController.h.
void* KX_IPhysicsController::m_userdata [protected]
Definition at line 58 of file KX_IPhysicsController.h.
Referenced by KX_BulletPhysicsController::GetUserData(), and GetUserData().
The documentation for this class was generated from the following files:
KX_IPhysicsController.h
KX_IPhysicsController.cpp