Blender: ED_sound.h File Reference
ED_sound.h File Reference
Editors
Functions
void ED_operatortypes_sound (void)
Detailed Description
Definition in file ED_sound.h.
Function Documentation
void ED_operatortypes_sound (void)
Definition at line 717 of file sound_ops.c.
References SOUND_OT_bake_animation(), SOUND_OT_mixdown(), SOUND_OT_open(), SOUND_OT_open_mono(), SOUND_OT_pack(), SOUND_OT_unpack(), SOUND_OT_update_animation_flags(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().