Blender: BKE_pointcache.h File Reference
BKE_pointcache.h File Reference
blenkernel
#include "DNA_ID.h"
#include "DNA_dynamicpaint_types.h"
#include "DNA_object_force.h"
#include "DNA_boid_types.h"
#include <stdio.h>
Classes
struct PTCacheData
struct PTCacheFile
struct PTCacheID
struct PTCacheBaker
struct PTCacheEditKey
struct PTCacheEditPoint
struct PTCacheUndo
struct PTCacheEdit
Defines
#define PTCACHE_CLEAR_ALL 0
#define PTCACHE_CLEAR_FRAME 1
#define PTCACHE_CLEAR_BEFORE 2
#define PTCACHE_CLEAR_AFTER 3
#define PTCACHE_RESET_DEPSGRAPH 0
#define PTCACHE_RESET_BAKED 1
#define PTCACHE_RESET_OUTDATED 2
#define PTCACHE_EXT ".bphys"
#define PTCACHE_PATH "blendcache_"
#define PTCACHE_FILE_READ 0
#define PTCACHE_FILE_WRITE 1
#define PTCACHE_FILE_UPDATE 2
#define PTCACHE_TYPE_SOFTBODY 0
#define PTCACHE_TYPE_PARTICLES 1
#define PTCACHE_TYPE_CLOTH 2
#define PTCACHE_TYPE_SMOKE_DOMAIN 3
#define PTCACHE_TYPE_SMOKE_HIGHRES 4
#define PTCACHE_TYPE_DYNAMICPAINT 5
#define PTCACHE_TYPEFLAG_COMPRESS (1<<16)
#define PTCACHE_TYPEFLAG_EXTRADATA (1<<17)
#define PTCACHE_TYPEFLAG_TYPEMASK 0x0000FFFF
#define PTCACHE_TYPEFLAG_FLAGMASK 0xFFFF0000
#define PTCACHE_READ_EXACT 1
#define PTCACHE_READ_INTERPOLATED 2
#define PTCACHE_READ_OLD 3
#define PTCACHE_VEL_PER_SEC 1
#define PEK_SELECT 1
#define PEK_TAG 2
#define PEK_HIDE 4
#define PEK_USE_WCO 8
#define PEP_TAG 1
#define PEP_EDIT_RECALC 2
#define PEP_TRANSFORM 4
#define PEP_HIDE 8
Typedefs
typedef struct PTCacheData PTCacheData
typedef struct PTCacheFile PTCacheFile
typedef struct PTCacheID PTCacheID
typedef struct PTCacheBaker PTCacheBaker
typedef struct PTCacheEditKey PTCacheEditKey
typedef struct PTCacheEditPoint PTCacheEditPoint
typedef struct PTCacheUndo PTCacheUndo
typedef struct PTCacheEdit PTCacheEdit
Functions
void BKE_ptcache_make_particle_key (struct ParticleKey *key, int index, void **data, float time)
void BKE_ptcache_id_from_softbody (PTCacheID *pid, struct Object *ob, struct SoftBody *sb)
void BKE_ptcache_id_from_particles (PTCacheID *pid, struct Object *ob, struct ParticleSystem *psys)
void BKE_ptcache_id_from_cloth (PTCacheID *pid, struct Object *ob, struct ClothModifierData *clmd)
void BKE_ptcache_id_from_smoke (PTCacheID *pid, struct Object *ob, struct SmokeModifierData *smd)
void BKE_ptcache_id_from_dynamicpaint (PTCacheID *pid, struct Object *ob, struct DynamicPaintSurface *surface)
void BKE_ptcache_ids_from_object (struct ListBase *lb, struct Object *ob, struct Scene *scene, int duplis)
void BKE_ptcache_remove (void)
void BKE_ptcache_id_clear (PTCacheID *id, int mode, unsigned int cfra)
int BKE_ptcache_id_exist (PTCacheID *id, int cfra)
int BKE_ptcache_id_reset (struct Scene *scene, PTCacheID *id, int mode)
void BKE_ptcache_id_time (PTCacheID *pid, struct Scene *scene, float cfra, int *startframe, int *endframe, float *timescale)
int BKE_ptcache_object_reset (struct Scene *scene, struct Object *ob, int mode)
void BKE_ptcache_update_info (PTCacheID *pid)
int BKE_ptcache_data_size (int data_type)
int BKE_ptcache_mem_index_find (struct PTCacheMem *pm, unsigned int index)
void BKE_ptcache_mem_pointers_init (struct PTCacheMem *pm)
void BKE_ptcache_mem_pointers_incr (struct PTCacheMem *pm)
int BKE_ptcache_mem_pointers_seek (int point_index, struct PTCacheMem *pm)
int BKE_ptcache_read (PTCacheID *pid, float cfra)
int BKE_ptcache_write (PTCacheID *pid, unsigned int cfra)
void BKE_ptcache_set_continue_physics (struct Main *bmain, struct Scene *scene, int enable)
int BKE_ptcache_get_continue_physics (void)
struct PointCache * BKE_ptcache_add (struct ListBase *ptcaches)
void BKE_ptcache_free_mem (struct ListBase *mem_cache)
void BKE_ptcache_free (struct PointCache *cache)
void BKE_ptcache_free_list (struct ListBase *ptcaches)
struct PointCache * BKE_ptcache_copy_list (struct ListBase *ptcaches_new, struct ListBase *ptcaches_old)
void BKE_ptcache_quick_cache_all (struct Main *bmain, struct Scene *scene)
void BKE_ptcache_bake (struct PTCacheBaker *baker)
void BKE_ptcache_disk_to_mem (struct PTCacheID *pid)
void BKE_ptcache_mem_to_disk (struct PTCacheID *pid)
void BKE_ptcache_toggle_disk_cache (struct PTCacheID *pid)
void BKE_ptcache_disk_cache_rename (struct PTCacheID *pid, const char *name_src, const char *name_dst)
void BKE_ptcache_load_external (struct PTCacheID *pid)
void BKE_ptcache_validate (struct PointCache *cache, int framenr)
void BKE_ptcache_invalidate (struct PointCache *cache)
Detailed Description
Definition in file BKE_pointcache.h.
Define Documentation
#define PEK_HIDE 4
Definition at line 187 of file BKE_pointcache.h.
Referenced by brush_puff(), createTransParticleVerts(), and PE_hide_keys_time().
#define PEK_SELECT 1
Definition at line 185 of file BKE_pointcache.h.
Referenced by brush_puff(), calc_manipulator_stats(), count_selected_keys(), createTransParticleVerts(), draw_ptcache_edit(), foreach_mouse_hit_key(), foreach_mouse_hit_point(), hide_exec(), PE_deselect_all_visible(), PE_lasso_select(), PE_mirror_particle(), PE_mouse_particles(), pe_select_all_exec(), psys_cache_edit_paths(), rekey_particle(), reveal_exec(), select_key(), select_keys(), select_less_keys(), select_more_keys(), select_root(), select_tip(), subdivide_particle(), and toggle_key_select().
#define PEK_TAG 2
Definition at line 186 of file BKE_pointcache.h.
Referenced by PE_mirror_particle(), remove_tagged_keys(), select_less_keys(), select_more_keys(), and set_delete_particle_key().
#define PEK_USE_WCO 8
Definition at line 188 of file BKE_pointcache.h.
Referenced by brush_add(), calc_manipulator_stats(), connect_hair(), createTransParticleVerts(), disconnect_hair(), draw_ptcache_edit(), PE_create_particle_edit(), rekey_particle(), and subdivide_particle().
#define PEP_EDIT_RECALC 2
Definition at line 204 of file BKE_pointcache.h.
Referenced by brush_add(), brush_comb(), brush_cut(), brush_length(), brush_puff(), brush_smooth_do(), brush_weight(), flushTransParticles(), hide_exec(), PE_apply_mirror(), PE_create_particle_edit(), PE_deselect_all_visible(), PE_lasso_select(), PE_mirror_particle(), PE_mouse_particles(), pe_select_all_exec(), PE_update_object(), PE_update_selection(), psys_cache_edit_paths(), psys_thread_create_path(), rekey_particle(), remove_tagged_keys(), reveal_exec(), select_key(), select_keys(), select_less_keys(), select_more_keys(), select_root(), select_tip(), subdivide_particle(), and toggle_key_select().
#define PEP_HIDE 8
Definition at line 206 of file BKE_pointcache.h.
Referenced by brush_cut(), calc_manipulator_stats(), createTransParticleVerts(), draw_ptcache_edit(), hide_exec(), PE_mirror_x(), point_is_selected(), reveal_exec(), select_root(), and select_tip().
#define PEP_TAG 1
Definition at line 203 of file BKE_pointcache.h.
Referenced by brush_add(), brush_cut(), PE_mirror_particle(), PE_mirror_x(), remove_doubles_exec(), remove_tagged_keys(), remove_tagged_particles(), and set_delete_particle().
#define PEP_TRANSFORM 4
Definition at line 205 of file BKE_pointcache.h.
Referenced by createTransParticleVerts(), and flushTransParticles().
#define PTCACHE_CLEAR_AFTER 3
Definition at line 46 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_clear(), BKE_ptcache_id_reset(), BKE_ptcache_read(), cloth_clear_cache(), and system_step().
#define PTCACHE_CLEAR_ALL 0
Definition at line 43 of file BKE_pointcache.h.
Referenced by BKE_ptcache_bake(), BKE_ptcache_disk_to_mem(), BKE_ptcache_id_clear(), BKE_ptcache_id_reset(), BKE_ptcache_mem_to_disk(), BKE_ptcache_toggle_disk_cache(), psys_changed_type(), psys_prepare_physics(), and ptcache_write_needed().
#define PTCACHE_CLEAR_BEFORE 2
Definition at line 45 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_clear().
#define PTCACHE_CLEAR_FRAME 1
Definition at line 44 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_clear(), ptcache_mem_frame_to_disk(), ptcache_write_needed(), and ptcache_write_stream().
#define PTCACHE_EXT ".bphys"
Definition at line 55 of file BKE_pointcache.h.
Referenced by BKE_ptcache_disk_cache_rename(), BKE_ptcache_id_clear(), BKE_ptcache_id_time(), BKE_ptcache_load_external(), BKE_ptcache_remove(), and ptcache_filename().
#define PTCACHE_FILE_READ 0
Definition at line 59 of file BKE_pointcache.h.
Referenced by BKE_ptcache_load_external(), ptcache_disk_frame_to_mem(), ptcache_file_open(), and ptcache_read_stream().
#define PTCACHE_FILE_UPDATE 2
Definition at line 61 of file BKE_pointcache.h.
Referenced by ptcache_file_open().
#define PTCACHE_FILE_WRITE 1
Definition at line 60 of file BKE_pointcache.h.
Referenced by ptcache_file_open(), ptcache_mem_frame_to_disk(), and ptcache_write_stream().
#define PTCACHE_PATH "blendcache_"
Definition at line 56 of file BKE_pointcache.h.
Referenced by ptcache_path().
#define PTCACHE_READ_EXACT 1
Definition at line 79 of file BKE_pointcache.h.
Referenced by BKE_ptcache_read(), clothModifier_do(), sbObjectStep(), and system_step().
#define PTCACHE_READ_INTERPOLATED 2
Definition at line 80 of file BKE_pointcache.h.
Referenced by BKE_ptcache_read(), clothModifier_do(), sbObjectStep(), and system_step().
#define PTCACHE_READ_OLD 3
Definition at line 81 of file BKE_pointcache.h.
Referenced by BKE_ptcache_read(), clothModifier_do(), sbObjectStep(), and system_step().
#define PTCACHE_RESET_BAKED 1
Definition at line 50 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_reset().
#define PTCACHE_RESET_DEPSGRAPH 0
Definition at line 49 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_reset(), dag_id_flush_update(), DAG_scene_flush_update(), and flush_pointcache_reset().
#define PTCACHE_RESET_OUTDATED 2
Definition at line 51 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_reset(), BKE_ptcache_set_continue_physics(), clothModifier_do(), dynamicPaint_frameUpdate(), ED_object_exit_editmode(), sbObjectStep(), special_aftertrans_update(), and system_step().
#define PTCACHE_TYPE_CLOTH 2
Definition at line 66 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_cloth(), BKE_ptcache_id_reset(), pe_get_current(), ptcache_old_elemsize(), and time_draw_cache().
#define PTCACHE_TYPE_DYNAMICPAINT 5
Definition at line 69 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_reset(), and time_draw_cache().
#define PTCACHE_TYPE_PARTICLES 1
Definition at line 65 of file BKE_pointcache.h.
Referenced by BKE_ptcache_bake(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_reset(), ED_object_exit_editmode(), pe_get_current(), ptcache_old_elemsize(), special_aftertrans_update(), and time_draw_cache().
#define PTCACHE_TYPE_SMOKE_DOMAIN 3
Definition at line 67 of file BKE_pointcache.h.
Referenced by BKE_ptcache_bake(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_reset(), BKE_ptcache_load_external(), BKE_ptcache_update_info(), and time_draw_cache().
#define PTCACHE_TYPE_SMOKE_HIGHRES 4
Definition at line 68 of file BKE_pointcache.h.
Referenced by BKE_ptcache_bake(), BKE_ptcache_id_reset(), and time_draw_cache().
#define PTCACHE_TYPE_SOFTBODY 0
Definition at line 64 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_softbody(), BKE_ptcache_id_reset(), pe_get_current(), ptcache_old_elemsize(), and time_draw_cache().
#define PTCACHE_TYPEFLAG_COMPRESS (1<<16)
Definition at line 72 of file BKE_pointcache.h.
Referenced by ptcache_disk_frame_to_mem(), and ptcache_mem_frame_to_disk().
#define PTCACHE_TYPEFLAG_EXTRADATA (1<<17)
Definition at line 73 of file BKE_pointcache.h.
Referenced by ptcache_disk_frame_to_mem(), and ptcache_mem_frame_to_disk().
#define PTCACHE_TYPEFLAG_FLAGMASK 0xFFFF0000
Definition at line 76 of file BKE_pointcache.h.
Referenced by ptcache_file_header_begin_read().
#define PTCACHE_TYPEFLAG_TYPEMASK 0x0000FFFF
Definition at line 75 of file BKE_pointcache.h.
Referenced by ptcache_file_header_begin_read().
#define PTCACHE_VEL_PER_SEC 1
Definition at line 118 of file BKE_pointcache.h.
Referenced by BKE_ptcache_id_from_particles(), and update_velocities().
Typedef Documentation
typedef struct PTCacheBaker PTCacheBaker
typedef struct PTCacheData PTCacheData
typedef struct PTCacheEdit PTCacheEdit
typedef struct PTCacheEditKey PTCacheEditKey
typedef struct PTCacheEditPoint PTCacheEditPoint
typedef struct PTCacheFile PTCacheFile
typedef struct PTCacheID PTCacheID
typedef struct PTCacheUndo PTCacheUndo
Function Documentation
struct PointCache* BKE_ptcache_add (struct ListBase * ptcaches) [read]
Definition at line 2603 of file pointcache.c.
References BLI_addtail(), PointCache::endframe, PointCache::index, MEM_callocN(), PointCache::startframe, and PointCache::step.
Referenced by do_versions(), dynamicPaint_createNewSurface(), free_hair(), initData(), object_add_particle_system(), ptcache_add_new_exec(), sbNew(), smokeModifier_createType(), and write_modifiers().
void BKE_ptcache_bake (struct PTCacheBaker * baker)
Definition at line 2772 of file pointcache.c.
References PTCacheBaker::anim_init, PTCacheBaker::bake, BKE_ptcache_id_clear(), BKE_ptcache_ids_from_object(), BKE_ptcache_write(), blender_test_break(), BLI_end_threads(), BLI_freelistN(), BLI_init_threads(), BLI_insert_thread(), ptcache_bake_data::break_operation, PTCacheID::cache, PTCacheID::calldata, CFRA, ptcache_bake_data::cfra_ptr, PointCache::endframe, ptcache_bake_data::endframe, FALSE, ListBase::first, PointCache::flag, RenderData::framelen, G, if(), PointCache::last_exact, Scene::lay, ptcache_bake_data::main, PTCacheBaker::main, MAX2, MAX_DUPLI_RECUR, MAXFRAME, MIN2, PTCacheID::next, NULL, PTCacheID::ob, Base::object, ParticleSystem::part, PART_EMITTER, PART_HAIR, PART_PHYS_KEYED, ParticleSettings::phystype, PTCacheBaker::pid, PIL_sleep_ms(), PTCacheBaker::progressbar, PTCacheBaker::progresscontext, PTCacheBaker::progressend, psys_get_pointcache_start_end(), ptcache_bake_thread(), PTCACHE_BAKED, PTCACHE_BAKING, PTCACHE_CLEAR_ALL, PTCACHE_DISK_CACHE, PTCACHE_OUTDATED, PTCACHE_QUICK_CACHE, PTCACHE_REDO_NEEDED, PTCACHE_SIMULATION_VALID, PTCACHE_TYPE_PARTICLES, PTCACHE_TYPE_SMOKE_DOMAIN, PTCACHE_TYPE_SMOKE_HIGHRES, PTCacheBaker::quick_step, Scene::r, PTCacheBaker::render, ptcache_bake_data::scene, PTCacheBaker::scene, scene_update_for_newframe(), SETLOOPER, RenderData::sfra, PointCache::startframe, ptcache_bake_data::step, ptcache_bake_data::thread_ended, threads, TRUE, ParticleSettings::type, PTCacheID::type, and WM_cursor_wait().
Referenced by BKE_ptcache_quick_cache_all(), ptcache_bake_all_exec(), ptcache_bake_exec(), and update_physics_cache().
struct PointCache* BKE_ptcache_copy_list (struct ListBase * ptcaches_new, struct ListBase * ptcaches_old) [read]
Definition at line 2669 of file pointcache.c.
References BLI_addtail(), ListBase::first, ListBase::last, PointCache::next, NULL, and ptcache_copy().
Referenced by copy_particlesystem(), copy_softbody(), and copyData().
int BKE_ptcache_data_size (int data_type)
Definition at line 1355 of file pointcache.c.
References ptcache_data_size.
Referenced by direct_link_pointcache().
void BKE_ptcache_disk_cache_rename (struct PTCacheID * pid, const char * name_src, const char * name_dst)
Definition at line 3066 of file pointcache.c.
References BLI_join_dirfile(), BLI_rename(), BLI_snprintf(), BLI_strncpy(), PTCacheID::cache, closedir(), dirent::d_name, len(), MAX_PTCACHE_FILE, MAX_PTCACHE_PATH, PointCache::name, NULL, opendir(), PTCACHE_EXT, ptcache_filename(), ptcache_path(), readdir(), PTCacheID::stack_index, and strlen().
void BKE_ptcache_disk_to_mem (struct PTCacheID * pid)
Definition at line 2984 of file pointcache.c.
References BKE_ptcache_id_clear(), BLI_addtail(), PTCacheID::cache, PointCache::endframe, PointCache::flag, PointCache::mem_cache, NULL, PTCACHE_BAKED, PTCACHE_CLEAR_ALL, ptcache_disk_frame_to_mem(), and PointCache::startframe.
Referenced by BKE_ptcache_toggle_disk_cache(), and psys_make_temp_pointcache().
void BKE_ptcache_free (struct PointCache * cache)
Definition at line 2631 of file pointcache.c.
References BKE_ptcache_free_mem(), PointCache::cached_frames, PointCache::edit, PointCache::free_edit, PointCache::mem_cache, and MEM_freeN().
Referenced by BKE_ptcache_free_list(), direct_link_modifiers(), and ptcache_remove_exec().
void BKE_ptcache_free_list (struct ListBase * ptcaches)
Definition at line 2640 of file pointcache.c.
References BKE_ptcache_free(), BLI_remlink(), and ListBase::first.
Referenced by copyData(), dynamicPaint_freeSurface(), free_hair(), freeData(), psys_free(), sbFree(), smokeModifier_freeDomain(), and write_modifiers().
void BKE_ptcache_free_mem (struct ListBase * mem_cache)
Definition at line 2618 of file pointcache.c.
References BLI_freelistN(), ListBase::first, PTCacheMem::next, ptcache_data_free(), and ptcache_extra_free().
Referenced by BKE_ptcache_free(), free_PTCacheUndo(), get_PTCacheUndo(), and psys_clear_temp_pointcache().
int BKE_ptcache_get_continue_physics (void)
Definition at line 2596 of file pointcache.c.
References CONTINUE_PHYSICS.
Referenced by BKE_ptcache_id_reset(), clothModifier_do(), deformVerts(), sbObjectStep(), system_step(), and transformApply().
void BKE_ptcache_id_clear (PTCacheID * id, int mode, unsigned int cfra)
Definition at line 2122 of file pointcache.c.
References BKE_ptcache_id_exist(), BKE_ptcache_update_info(), BLI_delete(), BLI_freelinkN(), BLI_freelistN(), BLI_join_dirfile(), BLI_snprintf(), BLI_strncpy(), PTCacheID::cache, PointCache::cached_frames, closedir(), dirent::d_name, PointCache::endframe, ListBase::first, PointCache::flag, PTCacheMem::frame, Object::id, PointCache::last_exact, len(), ID::lib, link(), MAX_PTCACHE_FILE, MAX_PTCACHE_PATH, MEM_allocN_len(), PointCache::mem_cache, MIN2, PTCacheMem::next, NULL, PTCacheID::ob, opendir(), PTCACHE_BAKED, PTCACHE_CLEAR_AFTER, PTCACHE_CLEAR_ALL, PTCACHE_CLEAR_BEFORE, PTCACHE_CLEAR_FRAME, ptcache_data_free(), PTCACHE_DISK_CACHE, PTCACHE_EXT, ptcache_extra_free(), ptcache_filename(), PTCACHE_IGNORE_CLEAR, ptcache_path(), readdir(), PTCacheID::stack_index, PointCache::startframe, and strlen().
Referenced by BKE_ptcache_bake(), BKE_ptcache_disk_to_mem(), BKE_ptcache_id_reset(), BKE_ptcache_mem_to_disk(), BKE_ptcache_read(), BKE_ptcache_toggle_disk_cache(), cloth_clear_cache(), psys_changed_type(), psys_prepare_physics(), ptcache_mem_frame_to_disk(), ptcache_write_needed(), ptcache_write_stream(), and system_step().
int BKE_ptcache_id_exist (PTCacheID * id, int cfra)
Definition at line 2264 of file pointcache.c.
References BLI_exists(), PTCacheID::cache, PointCache::cached_frames, PointCache::endframe, ListBase::first, PointCache::flag, PTCacheMem::frame, MAX_PTCACHE_FILE, PointCache::mem_cache, PTCacheMem::next, PTCACHE_DISK_CACHE, ptcache_filename(), and PointCache::startframe.
Referenced by BKE_ptcache_id_clear(), BKE_ptcache_read(), BKE_ptcache_update_info(), ptcache_find_frames_around(), ptcache_write(), and ptcache_write_needed().
void BKE_ptcache_id_from_cloth (PTCacheID * pid, struct Object * ob, struct ClothModifierData * clmd)
Definition at line 837 of file pointcache.c.
References BPHYS_DATA_LOCATION, BPHYS_DATA_VELOCITY, BPHYS_DATA_XCONST, PTCacheID::cache, PTCacheID::cache_ptr, PTCacheID::calldata, PTCacheID::data_types, PTCacheID::default_step, PointCache::index, PTCacheID::info_types, PTCacheID::interpolate_extra_data, PTCacheID::interpolate_point, PTCacheID::max_step, NULL, PTCacheID::ob, ClothModifierData::point_cache, ptcache_basic_header_read(), ptcache_basic_header_write(), ptcache_cloth_interpolate(), ptcache_cloth_read(), ptcache_cloth_totpoint(), ptcache_cloth_write(), PTCACHE_TYPE_CLOTH, ClothModifierData::ptcaches, PTCacheID::ptcaches, PTCacheID::read_extra_data, PTCacheID::read_header, PTCacheID::read_point, PTCacheID::read_stream, PTCacheID::stack_index, PTCacheID::totpoint, PTCacheID::totwrite, PTCacheID::type, PTCacheID::write_extra_data, PTCacheID::write_header, PTCacheID::write_point, and PTCacheID::write_stream.
Referenced by BKE_ptcache_ids_from_object(), BKE_ptcache_object_reset(), cloth_clear_cache(), and clothModifier_do().
void BKE_ptcache_id_from_dynamicpaint (PTCacheID * pid, struct Object * ob, struct DynamicPaintSurface * surface)
Definition at line 914 of file pointcache.c.
References BPHYS_DATA_DYNAMICPAINT, PTCacheID::cache, PTCacheID::cache_ptr, PTCacheID::calldata, PTCacheID::data_types, PTCacheID::default_step, PointCache::index, PTCacheID::info_types, PTCacheID::interpolate_extra_data, PTCacheID::interpolate_point, PTCacheID::max_step, NULL, PTCacheID::ob, DynamicPaintSurface::pointcache, ptcache_basic_header_read(), ptcache_basic_header_write(), ptcache_dynamicpaint_read(), ptcache_dynamicpaint_totpoint(), ptcache_dynamicpaint_write(), PTCACHE_TYPE_DYNAMICPAINT, DynamicPaintSurface::ptcaches, PTCacheID::ptcaches, PTCacheID::read_extra_data, PTCacheID::read_header, PTCacheID::read_point, PTCacheID::read_stream, PTCacheID::stack_index, PTCacheID::totpoint, PTCacheID::totwrite, PTCacheID::type, PTCacheID::write_extra_data, PTCacheID::write_header, PTCacheID::write_point, and PTCacheID::write_stream.
Referenced by BKE_ptcache_ids_from_object(), BKE_ptcache_object_reset(), and dynamicPaint_frameUpdate().
void BKE_ptcache_id_from_particles (PTCacheID * pid, struct Object * ob, struct ParticleSystem * psys)
Definition at line 780 of file pointcache.c.
References ParticleSettings::avefac, ParticleSettings::avemode, BPHYS_DATA_AVELOCITY, BPHYS_DATA_BOIDS, BPHYS_DATA_INDEX, BPHYS_DATA_LOCATION, BPHYS_DATA_ROTATION, BPHYS_DATA_TIMES, BPHYS_DATA_VELOCITY, PTCacheID::cache, PTCacheID::cache_ptr, PTCacheID::calldata, PTCacheID::data_types, PTCacheID::default_step, ParticleSettings::flag, SPHFluidSettings::flag, PTCacheID::flag, ParticleSettings::fluid, PointCache::index, PTCacheID::info_types, PTCacheID::interpolate_extra_data, PTCacheID::interpolate_point, PTCacheID::max_step, NULL, PTCacheID::ob, ParticleSystem::part, PART_AVE_RAND, PART_HAIR, PART_PHYS_BOIDS, PART_PHYS_FLUID, PART_ROT_VEL, PART_ROTATIONS, ParticleSettings::phystype, ParticleSystem::pointcache, ptcache_basic_header_read(), ptcache_basic_header_write(), ptcache_particle_extra_read(), ptcache_particle_extra_write(), ptcache_particle_interpolate(), ptcache_particle_read(), ptcache_particle_totpoint(), ptcache_particle_totwrite(), ptcache_particle_write(), PTCACHE_TYPE_PARTICLES, PTCACHE_VEL_PER_SEC, ParticleSystem::ptcaches, PTCacheID::ptcaches, PTCacheID::read_extra_data, PTCacheID::read_header, PTCacheID::read_point, PTCacheID::read_stream, ParticleSettings::rotmode, SPH_VISCOELASTIC_SPRINGS, PTCacheID::stack_index, PTCacheID::totpoint, PTCacheID::totwrite, ParticleSettings::type, PTCacheID::type, PTCacheID::write_extra_data, PTCacheID::write_header, PTCacheID::write_point, and PTCacheID::write_stream.
Referenced by BKE_ptcache_ids_from_object(), BKE_ptcache_object_reset(), psys_changed_type(), psys_make_temp_pointcache(), psys_prepare_physics(), and system_step().
void BKE_ptcache_id_from_smoke (PTCacheID * pid, struct Object * ob, struct SmokeModifierData * smd)
Definition at line 870 of file pointcache.c.
References BPHYS_DATA_SMOKE_HIGH, BPHYS_DATA_SMOKE_LOW, PTCacheID::cache, PTCacheID::cache_ptr, PTCacheID::calldata, PTCacheID::data_types, PTCacheID::default_step, SmokeModifierData::domain, SmokeDomainSettings::fluid, PointCache::index, PTCacheID::info_types, PTCacheID::interpolate_extra_data, PTCacheID::interpolate_point, PTCacheID::max_step, NULL, PTCacheID::ob, SmokeDomainSettings::point_cache, ptcache_basic_header_read(), ptcache_basic_header_write(), ptcache_smoke_read(), ptcache_smoke_totpoint(), ptcache_smoke_write(), PTCACHE_TYPE_SMOKE_DOMAIN, SmokeDomainSettings::ptcaches, PTCacheID::ptcaches, PTCacheID::read_extra_data, PTCacheID::read_header, PTCacheID::read_point, PTCacheID::read_stream, PTCacheID::stack_index, PTCacheID::totpoint, PTCacheID::totwrite, PTCacheID::type, PTCacheID::write_extra_data, PTCacheID::write_header, PTCacheID::write_point, PTCacheID::write_stream, and SmokeDomainSettings::wt.
Referenced by BKE_ptcache_ids_from_object(), and BKE_ptcache_object_reset().
void BKE_ptcache_id_from_softbody (PTCacheID * pid, struct Object * ob, struct SoftBody * sb)
Definition at line 746 of file pointcache.c.
References BPHYS_DATA_LOCATION, BPHYS_DATA_VELOCITY, PTCacheID::cache, PTCacheID::cache_ptr, PTCacheID::calldata, PTCacheID::data_types, PTCacheID::default_step, PointCache::index, PTCacheID::info_types, PTCacheID::interpolate_extra_data, PTCacheID::interpolate_point, PTCacheID::max_step, NULL, PTCacheID::ob, SoftBody::pointcache, ptcache_basic_header_read(), ptcache_basic_header_write(), ptcache_softbody_interpolate(), ptcache_softbody_read(), ptcache_softbody_totpoint(), ptcache_softbody_write(), PTCACHE_TYPE_SOFTBODY, SoftBody::ptcaches, PTCacheID::ptcaches, PTCacheID::read_extra_data, PTCacheID::read_header, PTCacheID::read_point, PTCacheID::read_stream, PTCacheID::stack_index, PTCacheID::totpoint, PTCacheID::totwrite, PTCacheID::type, PTCacheID::write_extra_data, PTCacheID::write_header, PTCacheID::write_point, and PTCacheID::write_stream.
Referenced by BKE_ptcache_ids_from_object(), BKE_ptcache_object_reset(), and sbObjectStep().
int BKE_ptcache_id_reset (struct Scene * scene, PTCacheID * id, int mode)
Definition at line 2402 of file pointcache.c.
References BKE_ptcache_get_continue_physics(), BKE_ptcache_id_clear(), BKE_ptcache_invalidate(), PTCacheID::cache, PTCacheID::calldata, CFRA, clear(), cloth_free_modifier(), dynamicPaint_clearSurface(), PointCache::flag, psys_reset(), PSYS_RESET_DEPSGRAPH, PTCACHE_BAKED, PTCACHE_CLEAR_AFTER, PTCACHE_CLEAR_ALL, PTCACHE_OUTDATED, PTCACHE_QUICK_CACHE, PTCACHE_REDO_NEEDED, PTCACHE_RESET_BAKED, PTCACHE_RESET_DEPSGRAPH, PTCACHE_RESET_OUTDATED, PTCACHE_TYPE_CLOTH, PTCACHE_TYPE_DYNAMICPAINT, PTCACHE_TYPE_PARTICLES, PTCACHE_TYPE_SMOKE_DOMAIN, PTCACHE_TYPE_SMOKE_HIGHRES, PTCACHE_TYPE_SOFTBODY, sbFreeSimulation(), smokeModifier_reset(), smokeModifier_reset_turbulence(), and PTCacheID::type.
Referenced by BKE_ptcache_object_reset(), clothModifier_do(), dynamicPaint_frameUpdate(), sbObjectStep(), and system_step().
void BKE_ptcache_id_time (PTCacheID * pid, struct Scene * scene, float cfra, int * startframe, int * endframe, float * timescale)
Definition at line 2292 of file pointcache.c.
References BKE_curframe(), BKE_frame_to_ctime(), BLI_snprintf(), BLI_strncpy(), PTCacheID::cache, PointCache::cached_frames, CFRA, closedir(), dirent::d_name, PointCache::endframe, ListBase::first, PointCache::flag, PTCacheMem::frame, len(), MAX2, MAX_PTCACHE_FILE, MAX_PTCACHE_PATH, MEM_allocN_len(), PointCache::mem_cache, MEM_callocN(), MEM_freeN(), PTCacheMem::next, NULL, opendir(), PARSLOW, PTCACHE_DISK_CACHE, PTCACHE_EXT, ptcache_filename(), ptcache_path(), readdir(), PTCacheID::stack_index, PointCache::startframe, and strlen().
Referenced by BKE_ptcache_toggle_disk_cache(), clothModifier_do(), dynamicPaint_frameUpdate(), sbObjectStep(), and system_step().
void BKE_ptcache_ids_from_object (struct ListBase * lb, struct Object * ob, struct Scene * scene, int duplis)
Definition at line 950 of file pointcache.c.
References BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_ids_from_object(), BLI_addtail(), BLI_movelisttolist(), DynamicPaintModifierData::canvas, ELEM, eModifierType_Cloth, eModifierType_DynamicPaint, eModifierType_Smoke, ListBase::first, free_object_duplilist(), ListBase::last, MEM_callocN(), MOD_SMOKE_TYPE_DOMAIN, Object::modifiers, DupliObject::next, DynamicPaintSurface::next, ModifierData::next, ParticleSystem::next, NULL, DupliObject::ob, OB_DUPLI, object_duplilist(), ParticleSystem::part, PART_FLUID, PART_PHYS_KEYED, PART_PHYS_NO, Object::particlesystem, ParticleSettings::phystype, Object::soft, DynamicPaintCanvasSettings::surfaces, Object::transflag, SmokeModifierData::type, ModifierData::type, and ParticleSettings::type.
Referenced by BKE_ptcache_bake(), BKE_ptcache_ids_from_object(), ED_object_exit_editmode(), object_cacheIgnoreClear(), object_handle_update(), pe_get_current(), ptcache_add_new_exec(), ptcache_bake_exec(), ptcache_free_bake_all_exec(), ptcache_remove_exec(), special_aftertrans_update(), and time_draw_cache().
void BKE_ptcache_invalidate (struct PointCache * cache)
Definition at line 3314 of file pointcache.c.
References PointCache::flag, PointCache::last_exact, MIN2, PTCACHE_SIMULATION_VALID, PointCache::simframe, and PointCache::startframe.
Referenced by BKE_ptcache_id_reset(), clothModifier_do(), do_init_cloth(), psys_reset(), sbObjectStep(), and system_step().
void BKE_ptcache_load_external (struct PTCacheID * pid)
Definition at line 3122 of file pointcache.c.
References BKE_ptcache_update_info(), BLI_snprintf(), BLI_strncpy(), PTCacheID::cache, closedir(), dirent::d_name, PointCache::endframe, PointCache::flag, PointCache::index, len(), MAX2, MAX_PTCACHE_FILE, MAX_PTCACHE_PATH, MAXFRAME, MIN2, NULL, opendir(), pf, PTCACHE_BAKED, PTCACHE_DISK_CACHE, PTCACHE_EXT, ptcache_file_close(), ptcache_file_header_begin_read(), ptcache_file_open(), ptcache_file_read(), PTCACHE_FILE_READ, ptcache_filename(), PTCACHE_FRAMES_SKIPPED, ptcache_old_elemsize(), PTCACHE_OUTDATED, ptcache_path(), PTCACHE_READ_INFO, PTCACHE_SIMULATION_VALID, PTCACHE_TYPE_SMOKE_DOMAIN, PTCacheID::read_header, readdir(), PointCache::startframe, strlen(), PTCacheFile::totpoint, PointCache::totpoint, PTCacheFile::type, and PTCacheID::type.
void BKE_ptcache_make_particle_key (struct ParticleKey * key, int index, void ** data, float time)
Definition at line 218 of file pointcache.c.
References ParticleKey::ave, BPHYS_DATA_AVELOCITY, BPHYS_DATA_LOCATION, BPHYS_DATA_ROTATION, BPHYS_DATA_VELOCITY, ParticleKey::co, NULL, OB_NEGX, OB_POSZ, PTCACHE_DATA_TO, ParticleKey::rot, ParticleKey::time, vec_to_quat(), and ParticleKey::vel.
Referenced by get_pointcache_keys_for_time(), ptcache_cloth_interpolate(), ptcache_particle_interpolate(), ptcache_particle_read(), and ptcache_softbody_interpolate().
int BKE_ptcache_mem_index_find (struct PTCacheMem * pm, unsigned int index)
Definition at line 1375 of file pointcache.c.
References BPHYS_DATA_INDEX, data, PTCacheMem::data, and PTCacheMem::totpoint.
Referenced by BKE_ptcache_mem_pointers_seek(), get_pointcache_keys_for_time(), get_pointcache_times_for_particle(), and psys_get_dietime_from_cache().
void BKE_ptcache_mem_pointers_incr (struct PTCacheMem * pm)
Definition at line 1415 of file pointcache.c.
References BPHYS_TOT_DATA, PTCacheMem::cur, i, and ptcache_data_size.
Referenced by get_PTCacheUndo(), PE_create_particle_edit(), ptcache_disk_frame_to_mem(), ptcache_interpolate(), ptcache_mem_frame_to_disk(), ptcache_read(), and ptcache_write().
void BKE_ptcache_mem_pointers_init (struct PTCacheMem * pm)
Definition at line 1406 of file pointcache.c.
References BPHYS_TOT_DATA, PTCacheMem::cur, PTCacheMem::data, PTCacheMem::data_types, i, and NULL.
Referenced by get_PTCacheUndo(), ptcache_disk_frame_to_mem(), ptcache_interpolate(), ptcache_mem_frame_to_disk(), ptcache_read(), and ptcache_write().
int BKE_ptcache_mem_pointers_seek (int point_index, struct PTCacheMem * pm)
Definition at line 1424 of file pointcache.c.
References BKE_ptcache_mem_index_find(), BPHYS_TOT_DATA, PTCacheMem::cur, PTCacheMem::data, PTCacheMem::data_types, i, NULL, and ptcache_data_size.
Referenced by PE_create_particle_edit(), and ptcache_write().
void BKE_ptcache_mem_to_disk (struct PTCacheID * pid)
Definition at line 3007 of file pointcache.c.
References BKE_ptcache_id_clear(), BKE_ptcache_write(), PTCacheID::cache, ListBase::first, PointCache::flag, PointCache::mem_cache, PTCacheMem::next, PTCACHE_BAKED, PTCACHE_CLEAR_ALL, PTCACHE_DISK_CACHE, and ptcache_mem_frame_to_disk().
Referenced by BKE_ptcache_toggle_disk_cache().
int BKE_ptcache_object_reset (struct Scene * scene, struct Object * ob, int mode)
Definition at line 2466 of file pointcache.c.
References BIK_clear_cache(), BKE_ptcache_id_from_cloth(), BKE_ptcache_id_from_dynamicpaint(), BKE_ptcache_id_from_particles(), BKE_ptcache_id_from_smoke(), BKE_ptcache_id_from_softbody(), BKE_ptcache_id_reset(), PTCacheID::cache, DynamicPaintModifierData::canvas, ParticleSystem::clmd, eModifierType_Cloth, eModifierType_DynamicPaint, eModifierType_Smoke, ListBase::first, PointCache::flag, MOD_SMOKE_TYPE_DOMAIN, Object::modifiers, DynamicPaintSurface::next, ModifierData::next, ParticleSystem::next, OB_ARMATURE, ParticleSystem::part, PART_HAIR, Object::particlesystem, Object::pose, PSYS_RECALC_CHILD, PSYS_RECALC_REDO, PSYS_RESET_ALL, PTCACHE_BAKED, ParticleSystem::recalc, Object::soft, DynamicPaintCanvasSettings::surfaces, Object::type, SmokeModifierData::type, ModifierData::type, and ParticleSettings::type.
Referenced by BKE_ptcache_set_continue_physics(), dag_id_flush_update(), DAG_scene_flush_update(), ED_object_exit_editmode(), flush_pointcache_reset(), and special_aftertrans_update().
void BKE_ptcache_quick_cache_all (struct Main * bmain, struct Scene * scene)
Definition at line 2683 of file pointcache.c.
References PTCacheBaker::anim_init, PTCacheBaker::bake, BKE_ptcache_bake(), PTCacheBaker::break_data, PTCacheBaker::break_test, PTCacheBaker::main, NULL, Scene::physics_settings, PTCacheBaker::pid, PTCacheBaker::progressbar, PTCacheBaker::progresscontext, PTCacheBaker::progressend, PhysicsSettings::quick_cache_step, PTCacheBaker::quick_step, PTCacheBaker::render, and PTCacheBaker::scene.
Referenced by scene_update_tagged().
int BKE_ptcache_read (PTCacheID * pid, float cfra)
Definition at line 1851 of file pointcache.c.
References BKE_ptcache_id_clear(), BKE_ptcache_id_exist(), PTCacheID::cache, PTCacheID::calldata, PointCache::flag, PTCacheID::interpolate_point, PointCache::last_exact, MAX2, PTCACHE_CLEAR_AFTER, ptcache_find_frames_around(), PTCACHE_FRAMES_SKIPPED, ptcache_interpolate(), PTCACHE_OUTDATED, PTCACHE_QUICK_CACHE, ptcache_read(), PTCACHE_READ_EXACT, PTCACHE_READ_INFO, PTCACHE_READ_INTERPOLATED, PTCACHE_READ_OLD, ptcache_read_stream(), PTCacheID::read_point, PTCacheID::read_stream, PointCache::simframe, and PTCacheID::totpoint.
Referenced by clothModifier_do(), dynamicPaint_frameUpdate(), sbObjectStep(), and system_step().
void BKE_ptcache_remove (void)
Definition at line 2535 of file pointcache.c.
References BLI_delete(), BLI_exists(), BLI_join_dirfile(), closedir(), dirent::d_name, MAX_PTCACHE_PATH, NULL, opendir(), PTCACHE_EXT, ptcache_path(), and readdir().
void BKE_ptcache_set_continue_physics (struct Main * bmain, struct Scene * scene, int enable)
Definition at line 2581 of file pointcache.c.
References BKE_ptcache_object_reset(), DAG_id_tag_update(), ListBase::first, Object::id, ID::next, OB_RECALC_DATA, Main::object, and PTCACHE_RESET_OUTDATED.
void BKE_ptcache_toggle_disk_cache (struct PTCacheID * pid)
Definition at line 3033 of file pointcache.c.
References BKE_ptcache_disk_to_mem(), BKE_ptcache_id_clear(), BKE_ptcache_id_time(), BKE_ptcache_mem_to_disk(), BKE_ptcache_update_info(), PTCacheID::cache, PointCache::cached_frames, PointCache::flag, G, G_DEBUG, PointCache::last_exact, MEM_freeN(), NULL, PTCACHE_CLEAR_ALL, and PTCACHE_DISK_CACHE.
void BKE_ptcache_update_info (PTCacheID * pid)
Definition at line 3223 of file pointcache.c.
References BKE_ptcache_id_exist(), BLI_snprintf(), BPHYS_TOT_DATA, PTCacheID::cache, PTCacheID::calldata, PTCacheExtra::data, PTCacheMem::data, PointCache::endframe, PTCacheMem::extradata, ListBase::first, PointCache::flag, i, PointCache::info, PointCache::last_exact, MEM_allocN_len(), PointCache::mem_cache, PTCacheExtra::next, PTCacheMem::next, NULL, PTCACHE_DISK_CACHE, PTCACHE_EXTERNAL, PTCACHE_FRAMES_SKIPPED, PTCACHE_OUTDATED, PTCACHE_TYPE_SMOKE_DOMAIN, PointCache::startframe, PTCacheID::totpoint, PointCache::totpoint, and PTCacheID::type.
Referenced by BKE_ptcache_id_clear(), BKE_ptcache_load_external(), BKE_ptcache_toggle_disk_cache(), and BKE_ptcache_write().
void BKE_ptcache_validate (struct PointCache * cache, int framenr)
Definition at line 3307 of file pointcache.c.
References PointCache::flag, PTCACHE_SIMULATION_VALID, and PointCache::simframe.
Referenced by clothModifier_do(), dynamicPaint_frameUpdate(), sbObjectStep(), and system_step().
int BKE_ptcache_write (PTCacheID * pid, unsigned int cfra)
Definition at line 2081 of file pointcache.c.
References BKE_ptcache_update_info(), PTCacheID::cache, PointCache::cached_frames, PTCacheID::calldata, PTCacheID::data_types, error(), PointCache::flag, PTCacheID::info_types, PointCache::last_exact, PTCACHE_FRAMES_SKIPPED, ptcache_write(), ptcache_write_needed(), ptcache_write_stream(), PointCache::startframe, PTCacheID::totpoint, PTCacheID::write_point, and PTCacheID::write_stream.
Referenced by BKE_ptcache_bake(), BKE_ptcache_mem_to_disk(), clothModifier_do(), dynamicPaint_frameUpdate(), sbObjectStep(), and system_step().