Blender: sp_coletree.c File Reference
sp_coletree.c File Reference
opennl
#include <stdio.h>
#include <stdlib.h>
#include "ssp_defs.h"
Functions
static int * mxCallocInt (int n)
static void initialize_disjoint_sets (int n)
static int make_set (int i)
static int link (int s, int t)
static int find (int i)
static void finalize_disjoint_sets (void)
int sp_coletree (int *acolst, int *acolend, int *arow, int nr, int nc, int *parent)
static void etdfs (int v)
int * TreePostorder (int n, int *parent)
int sp_symetree (int *acolst, int *acolend, int *arow, int n, int *parent)
Variables
static int * pp
static int * first_kid
static int * next_kid
static int * post
static int postnum
Detailed Description
Definition in file sp_coletree.c.
Function Documentation
static void etdfs (int v) [static]
Definition at line 222 of file sp_coletree.c.
Referenced by TreePostorder().
static void finalize_disjoint_sets (void) [static]
Definition at line 107 of file sp_coletree.c.
References pp, and SUPERLU_FREE.
Referenced by sp_coletree(), and sp_symetree().
static int find (int i) [static]
Definition at line 78 of file sp_coletree.c.
References i, p, and pp.
Referenced by GHOST_EventManager::addConsumer(), KX_ObstacleSimulationTOI::AdjustObstacleVelocity(), NG_NetworkScene::ConstraintsAreValid(), draw_brackets(), AnimationImporter::find_frames(), AnimationExporter::find_frames(), AnimationImporter::find_frames_old(), SkinInfo::find_root_joints(), GHOST_TimerManager::getTimerFound(), GHOST_WindowManager::getWindowFound(), SCA_PythonController::IsTriggered(), ForEachMaterialFunctor< Functor >::operator()(), ImagesExporter::operator()(), ExpDesc::registerDesc(), SG_Node::RemoveChild(), GHOST_EventManager::removeConsumer(), LOD_Vertex::RemoveEdge(), BSP_MVertex::RemoveEdge(), RAS_IRenderTools::RemoveLight(), GHOST_TimerManager::removeTimer(), GHOST_WindowManager::removeWindow(), IsoSurface::smoothNormals(), IsoSurface::smoothSurface(), sp_coletree(), sp_symetree(), LOD_Vertex::SwapEdge(), BSP_MVertex::SwapEdge(), BSP_MEdge::SwapFace(), and txt_format_line().
static void initialize_disjoint_sets (int n) [static]
Definition at line 47 of file sp_coletree.c.
References mxCallocInt(), and pp.
Referenced by sp_coletree(), and sp_symetree().
static int link (int s, int t) [static]
Definition at line 66 of file sp_coletree.c.
References pp.
Referenced by add_user_list(), addtail(), bake_images(), BKE_ptcache_id_clear(), BLI_addhead(), BLI_addtail(), BLI_countlist(), BLI_findindex(), BLI_findlink(), BLI_findstring(), BLI_findstring_ptr(), BLI_findstringindex(), BLI_freelinkN(), BLI_freelist(), BLI_freelistN(), BLI_remlink(), BLI_rfindlink(), BLI_rfindstring(), BLI_rfindstring_ptr(), bpy_class_validate(), BPY_context_member_get(), cmp_node_image_verify_outputs(), copy_to_selected_button_exec(), copy_to_selected_button_poll(), CTX_data_id_list_add(), CTX_data_list_add(), cut_links_exec(), data_dir_add(), direct_link_nodetree(), do_versions_nodetree_socket_use_flags_2_62(), ed_node_link_conditions(), ED_node_link_insert(), ED_node_link_intersect_test(), finish_images(), GPU_attribute(), GPU_builtin(), GPU_dynamic_texture(), GPU_dynamic_uniform(), GPU_image(), GPU_lamp_free(), GPU_lamp_from_blender(), GPU_link(), GPU_material_free(), GPU_material_from_blender(), GPU_material_output_link(), gpu_node_input_link(), gpu_node_input_socket(), GPU_node_link_create(), gpu_shader_material(), GPU_socket(), GPU_stack_link(), GPU_texture(), GPU_uniform(), IDP_CopyGroup(), image_assign_ibuf(), GEN_Link::insertAfter(), CTR_Link::insertAfter(), btGEN_Link::insertAfter(), GEN_Link::insertBefore(), CTR_Link::insertBefore(), btGEN_Link::insertBefore(), localize(), mmdelm_(), mmdupd_(), node_animation_properties(), node_draw_mute_line(), node_draw_nodetree(), node_duplicate_exec(), node_group_make_from_selected(), node_group_ungroup(), node_internal_connect_default(), node_link_init(), node_link_modal(), node_link_viewer(), node_select_linked_from_exec(), node_select_linked_to_exec(), node_shader_gpu_tex_checker(), node_shader_gpu_tex_environment(), node_shader_gpu_tex_gradient(), node_shader_gpu_tex_image(), node_shader_gpu_tex_magic(), node_shader_gpu_tex_mapping(), node_shader_gpu_tex_musgrave(), node_shader_gpu_tex_noise(), node_shader_gpu_tex_sky(), node_shader_gpu_tex_voronoi(), node_shader_gpu_tex_wave(), node_socket_add_replace(), nodeAddLink(), nodeCountSocketLinks(), nodeFindLink(), nodeInternalRelink(), nodeRemoveAllSockets(), nodeRemoveSocket(), nodeRemSocketLinks(), nodeUnlinkNode(), ntree_update_link_pointers(), ntree_validate_links(), ntreeCopyTree(), object_insert_ptcache(), phash_insert(), phash_lookup(), phash_next(), proxy_endjob(), proxy_startjob(), pyrna_param_to_py(), pyrna_py_to_prop(), pyrna_srna_contains_pointer_prop_srna(), pyrna_struct_dir(), pyrna_struct_getattro(), remlink(), RIG_parentControl(), RIG_reconnectControlBones(), rna_addtail(), rna_findlink(), rna_freelistN(), rna_function_arg_count(), rna_function_parameter_parse(), rna_idp_path(), rna_idp_path_create(), rna_remlink(), rna_sortlist(), seq_proxy_build_job(), setExecutableNodes(), snode_autoconnect_input(), sp_coletree(), sp_symetree(), ui_add_link(), ui_add_smart_controller(), ui_delete_active_linkline(), ui_delete_linkline(), ui_is_a_link(), uiComposeLinks(), uiSetButLink(), uniquename_find_dupe(), and write_nodetree().
static int make_set (int i) [static]
Definition at line 56 of file sp_coletree.c.
References i, and pp.
Referenced by sp_coletree(), and sp_symetree().
static int* mxCallocInt (int n) [static]
Definition at line 33 of file sp_coletree.c.
References ABORT, i, and SUPERLU_MALLOC.
Referenced by initialize_disjoint_sets(), sp_coletree(), sp_symetree(), and TreePostorder().
int sp_coletree (int * acolst, int * acolend, int * arow, int nr, int nc, int * parent)
Definition at line 136 of file sp_coletree.c.
References finalize_disjoint_sets(), find(), initialize_disjoint_sets(), link(), make_set(), mxCallocInt(), p, SUPERLU_FREE, and SUPERLU_MIN.
Referenced by sp_preorder().
int sp_symetree (int * acolst, int * acolend, int * arow, int n, int * parent)
Definition at line 300 of file sp_coletree.c.
References finalize_disjoint_sets(), find(), initialize_disjoint_sets(), link(), make_set(), mxCallocInt(), p, and SUPERLU_FREE.
Referenced by sp_preorder().
int* TreePostorder (int n, int * parent)
Definition at line 239 of file sp_coletree.c.
References etdfs(), mxCallocInt(), post, and SUPERLU_FREE.
Referenced by heap_relax_snode(), and sp_preorder().
Variable Documentation
int* first_kid [static]
Definition at line 215 of file sp_coletree.c.
int * next_kid
Definition at line 215 of file sp_coletree.c.
int* post [static]
Definition at line 216 of file sp_coletree.c.
Referenced by armature_deform_verts(), heap_relax_snode(), setInputPostFct(), sp_preorder(), and TreePostorder().
int postnum
Definition at line 216 of file sp_coletree.c.
int* pp [static]
Definition at line 30 of file sp_coletree.c.
Referenced by calc_curvepath(), dBoxBox2(), finalize_disjoint_sets(), find(), btSparseSdf< 3 >::GarbageCollect(), initialize_disjoint_sets(), link(), make_set(), btSparseSdf< 3 >::RemoveReferences(), TNT::SVD(), svd_m4(), and where_on_path().