Blender: ED_sculpt.h File Reference
ED_sculpt.h File Reference
Editors
Defines
#define UNDO_PAINT_IMAGE 0
#define UNDO_PAINT_MESH 1
Functions
void ED_operatortypes_sculpt (void)
void sculpt_get_redraw_planes (float planes[4][4], struct ARegion *ar, struct RegionView3D *rv3d, struct Object *ob)
void ED_sculpt_force_update (struct bContext *C)
void ED_operatortypes_paint (void)
void ED_keymap_paint (struct wmKeyConfig *keyconf)
int ED_undo_paint_step (struct bContext *C, int type, int step, const char *name)
void ED_undo_paint_free (void)
int ED_undo_paint_valid (int type, const char *name)
Detailed Description
Definition in file ED_sculpt.h.
Define Documentation
#define UNDO_PAINT_IMAGE 0
Definition at line 51 of file ED_sculpt.h.
Referenced by ED_undo_paint_step(), ED_undo_paint_valid(), ed_undo_step(), ED_undo_valid(), image_undo_push_tile(), paint_exit(), texture_paint_camera_project_exec(), texture_paint_init(), undo_paint_push_begin(), undo_paint_push_count_alloc(), undo_paint_push_end(), and undo_paint_push_get_list().
#define UNDO_PAINT_MESH 1
Definition at line 52 of file ED_sculpt.h.
Referenced by ED_undo_paint_step(), ED_undo_paint_valid(), ed_undo_step(), ED_undo_valid(), sculpt_undo_alloc_node(), sculpt_undo_get_node(), sculpt_undo_push_begin(), sculpt_undo_push_end(), undo_paint_push_begin(), undo_paint_push_count_alloc(), undo_paint_push_end(), and undo_paint_push_get_list().
Function Documentation
void ED_keymap_paint (struct wmKeyConfig * keyconf)
Definition at line 555 of file paint_ops.c.
References AKEY, BKEY, BRUSH_STROKE_INVERT, BRUSH_STROKE_NORMAL, BRUSH_STROKE_SMOOTH, CKEY, DKEY, ed_keymap_paint_brush_radial_control(), ed_keymap_paint_brush_size(), ed_keymap_paint_brush_switch(), EVT_TWEAK_A, facemask_paint_poll(), FALSE, GKEY, HKEY, i, IKEY, image_texture_paint_poll(), keymap_brush_select(), KKEY, KM_ALT, KM_ANY, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTMOUSE, LKEY, MKEY, OB_MODE_SCULPT, PAGEDOWNKEY, PAGEUPKEY, paint_partial_visibility_keys(), PKEY, wmKeyMap::poll, wmKeyMapItem::ptr, QKEY, RC_COLOR, RC_ROTATION, RC_ZOOM, RIGHTMOUSE, RKEY, RNA_boolean_set(), RNA_enum_set(), RNA_int_set(), RNA_string_set(), sculpt_poll(), SCULPT_TOOL_CLAY, SCULPT_TOOL_CREASE, SCULPT_TOOL_DRAW, SCULPT_TOOL_FLATTEN, SCULPT_TOOL_GRAB, SCULPT_TOOL_INFLATE, SCULPT_TOOL_LAYER, SCULPT_TOOL_PINCH, SCULPT_TOOL_SMOOTH, SKEY, TKEY, TRUE, uv_sculpt_poll(), UV_SCULPT_TOOL_GRAB, UV_SCULPT_TOOL_PINCH, UV_SCULPT_TOOL_RELAX, vert_paint_poll(), vertex_paint_mode_poll(), VKEY, weight_paint_mode_poll(), WKEY, WM_keymap_add_item(), WM_keymap_find(), WM_keymap_verify_item(), and ZEROKEY.
Referenced by ED_spacetypes_keymap().
void ED_operatortypes_paint (void)
Definition at line 394 of file paint_ops.c.
References BRUSH_OT_add(), BRUSH_OT_curve_preset(), BRUSH_OT_reset(), BRUSH_OT_scale_size(), BRUSH_OT_uv_sculpt_tool_set(), PAINT_OT_brush_select(), PAINT_OT_clone_cursor_set(), PAINT_OT_face_select_all(), PAINT_OT_face_select_hide(), PAINT_OT_face_select_inverse(), PAINT_OT_face_select_linked(), PAINT_OT_face_select_linked_pick(), PAINT_OT_face_select_reveal(), PAINT_OT_grab_clone(), PAINT_OT_hide_show(), PAINT_OT_image_from_view(), PAINT_OT_image_paint(), PAINT_OT_project_image(), PAINT_OT_sample_color(), PAINT_OT_texture_paint_toggle(), PAINT_OT_vert_select_all(), PAINT_OT_vert_select_inverse(), PAINT_OT_vertex_color_set(), PAINT_OT_vertex_paint(), PAINT_OT_vertex_paint_toggle(), PAINT_OT_weight_from_bones(), PAINT_OT_weight_paint(), PAINT_OT_weight_paint_toggle(), PAINT_OT_weight_sample(), PAINT_OT_weight_sample_group(), PAINT_OT_weight_set(), SCULPT_OT_uv_sculpt_stroke(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
void ED_operatortypes_sculpt (void)
Definition at line 3711 of file sculpt.c.
References SCULPT_OT_brush_stroke(), SCULPT_OT_sculptmode_toggle(), SCULPT_OT_set_persistent_base(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
void ED_sculpt_force_update (struct bContext * C)
Definition at line 96 of file sculpt.c.
References CTX_data_active_object(), Object::mode, multires_force_update(), and OB_MODE_SCULPT.
Referenced by WM_write_file().
void ED_undo_paint_free (void)
Definition at line 272 of file paint_undo.c.
References undo_stack_free().
Referenced by ED_editors_exit().
int ED_undo_paint_step (struct bContext * C, int type, int step, const char * name)
Definition at line 241 of file paint_undo.c.
References UNDO_PAINT_IMAGE, UNDO_PAINT_MESH, and undo_stack_step().
Referenced by ed_undo_step().
int ED_undo_paint_valid (int type, const char * name)
Definition at line 251 of file paint_undo.c.
References UndoStack::current, UndoStack::elems, ListBase::first, ImageUndoStack, ListBase::last, MeshUndoStack, UndoElem::name, NULL, stack, UNDO_PAINT_IMAGE, and UNDO_PAINT_MESH.
Referenced by ED_undo_valid().
void sculpt_get_redraw_planes (float planes[4][4], struct ARegion * ar, struct RegionView3D * rv3d, struct Object * ob)
Definition at line 287 of file sculpt.c.
References BLI_pbvh_update(), NULL, paint_calc_redraw_planes(), SculptSession::pbvh, PBVH_UpdateRedraw, Object::sculpt, and sculpt_get_redraw_rect().
Referenced by draw_mesh_fancy().