Blender: ED_mesh.h File Reference
ED_mesh.h File Reference
Editors
#include "../mesh/editmesh_bvh.h"
Classes
struct MirrTopoStore_t
Defines
#define WEIGHT_REPLACE 1
#define WEIGHT_ADD 2
#define WEIGHT_SUBTRACT 3
Typedefs
typedef struct MirrTopoStore_t MirrTopoStore_t
Functions
intptr_t mesh_octree_table (struct Object *ob, struct BMEditMesh *em, float *co, char mode)
int mesh_mirrtopo_table (struct Object *ob, char mode)
void EDBM_verts_mirror_cache_begin (struct BMEditMesh *em, const short use_select)
void EDBM_verts_mirror_apply (struct BMEditMesh *em, const int sel_from, const int sel_to)
struct BMVert * EDBM_verts_mirror_get (struct BMEditMesh *em, struct BMVert *v)
void EDBM_verts_mirror_cache_clear (struct BMEditMesh *em, struct BMVert *v)
void EDBM_verts_mirror_cache_end (struct BMEditMesh *em)
void EDBM_mesh_normals_update (struct BMEditMesh *em)
void EDBM_mesh_make (struct ToolSettings *ts, struct Scene *scene, struct Object *ob)
void EDBM_mesh_free (struct BMEditMesh *tm)
void EDBM_mesh_load (struct Object *ob)
void EDBM_index_arrays_init (struct BMEditMesh *em, int forvert, int foredge, int forface)
void EDBM_index_arrays_free (struct BMEditMesh *em)
struct BMVert * EDBM_vert_at_index (struct BMEditMesh *em, int index)
struct BMEdge * EDBM_edge_at_index (struct BMEditMesh *em, int index)
struct BMFace * EDBM_face_at_index (struct BMEditMesh *em, int index)
void EDBM_select_more (struct BMEditMesh *em)
void EDBM_select_less (struct BMEditMesh *em)
void EDBM_selectmode_flush_ex (struct BMEditMesh *em, int selectmode)
void EDBM_selectmode_flush (struct BMEditMesh *em)
void EDBM_deselect_flush (struct BMEditMesh *em)
void EDBM_select_flush (struct BMEditMesh *em)
void EDBM_selectmode_set (struct BMEditMesh *em)
void EDBM_selectmode_convert (struct BMEditMesh *em, short oldmode, short selectmode)
void undo_push_mesh (struct bContext *C, const char *name)
int EDBM_vert_color_check (struct BMEditMesh *em)
void EDBM_mesh_hide (struct BMEditMesh *em, int swap)
void EDBM_mesh_reveal (struct BMEditMesh *em)
void EDBM_update_generic (struct bContext *C, struct BMEditMesh *em, const short do_tessface)
int EDBM_backbuf_check (unsigned int index)
int EDBM_backbuf_border_mask_init (struct ViewContext *vc, int mcords[][2], short tot, short xmin, short ymin, short xmax, short ymax)
void EDBM_backbuf_free (void)
int EDBM_backbuf_border_init (struct ViewContext *vc, short xmin, short ymin, short xmax, short ymax)
int EDBM_backbuf_circle_init (struct ViewContext *vc, short xs, short ys, short rads)
void EDBM_deselect_by_material (struct BMEditMesh *em, const short index, const short select)
struct UvElementMap * EDBM_uv_element_map_create (struct BMEditMesh *em, int selected, int doIslands)
void EDBM_uv_element_map_free (struct UvElementMap *vmap)
int EDBM_mtexpoly_check (struct BMEditMesh *em)
struct MTexPoly * EDBM_mtexpoly_active_get (struct BMEditMesh *em, struct BMFace **r_act_efa, int sloppy)
void EDBM_uv_vert_map_free (struct UvVertMap *vmap)
struct UvMapVert * EDBM_uv_vert_map_at_index (struct UvVertMap *vmap, unsigned int v)
struct UvVertMap * EDBM_uv_vert_map_create (struct BMEditMesh *em, int selected, int do_face_idx_array, float *limit)
void EDBM_data_layer_add (struct BMEditMesh *em, struct CustomData *data, int type, const char *name)
void EDBM_data_layer_free (struct BMEditMesh *em, struct CustomData *data, int type)
void EDBM_select_toggle_all (struct BMEditMesh *em)
void EDBM_select_swap (struct BMEditMesh *em)
int EDBM_select_interior_faces (struct BMEditMesh *em)
void EDBM_flag_enable_all (struct BMEditMesh *em, const char hflag)
void EDBM_flag_disable_all (struct BMEditMesh *em, const char hflag)
void EDBM_select_mirrored (struct Object *obedit, struct BMEditMesh *em, int extend)
void EDBM_automerge (struct Scene *scene, struct Object *ob, int update)
int mouse_mesh (struct bContext *C, const int mval[2], short extend)
struct BMVert * editbmesh_get_x_mirror_vert (struct Object *ob, struct BMEditMesh *em, struct BMVert *eve, float *co, int index)
int mesh_get_x_mirror_vert (struct Object *ob, int index)
int * mesh_get_x_mirror_faces (struct Object *ob, struct BMEditMesh *em)
int join_mesh_exec (struct bContext *C, struct wmOperator *op)
int join_mesh_shapes_exec (struct bContext *C, struct wmOperator *op)
void ED_operatortypes_mesh (void)
void ED_operatormacros_mesh (void)
void ED_keymap_mesh (struct wmKeyConfig *keyconf)
void ED_spacetypes_init (void)
void EMBM_project_snap_verts (struct bContext *C, struct ARegion *ar, struct Object *obedit, struct BMEditMesh *em)
void paintface_flush_flags (struct Object *ob)
int paintface_mouse_select (struct bContext *C, struct Object *ob, const int mval[2], int extend)
int do_paintface_box_select (struct ViewContext *vc, struct rcti *rect, int select, int extend)
void paintface_deselect_all_visible (struct Object *ob, int action, short flush_flags)
void paintface_select_linked (struct bContext *C, struct Object *ob, int mval[2], int mode)
int paintface_minmax (struct Object *ob, float *min, float *max)
void paintface_hide (struct Object *ob, const int unselected)
void paintface_reveal (struct Object *ob)
void paintvert_deselect_all_visible (struct Object *ob, int action, short flush_flags)
void paintvert_flush_flags (struct Object *ob)
struct bDeformGroup * ED_vgroup_add (struct Object *ob)
struct bDeformGroup * ED_vgroup_add_name (struct Object *ob, const char *name)
void ED_vgroup_delete (struct Object *ob, struct bDeformGroup *defgroup)
void ED_vgroup_clear (struct Object *ob)
void ED_vgroup_select_by_name (struct Object *ob, const char *name)
int ED_vgroup_data_create (struct ID *id)
int ED_vgroup_give_array (struct ID *id, struct MDeformVert **dvert_arr, int *dvert_tot)
int ED_vgroup_copy_array (struct Object *ob, struct Object *ob_from)
void ED_vgroup_mirror (struct Object *ob, const short mirror_weights, const short flip_vgroups, const short all_vgroups)
int ED_vgroup_object_is_edit_mode (struct Object *ob)
void ED_vgroup_vert_add (struct Object *ob, struct bDeformGroup *dg, int vertnum, float weight, int assignmode)
void ED_vgroup_vert_remove (struct Object *ob, struct bDeformGroup *dg, int vertnum)
float ED_vgroup_vert_weight (struct Object *ob, struct bDeformGroup *dg, int vertnum)
struct BMVert * EDBM_vert_find_nearest (struct ViewContext *vc, int *dist, short sel, short strict)
struct BMEdge * EDBM_edge_find_nearest (struct ViewContext *vc, int *dist)
struct BMFace * EDBM_face_find_nearest (struct ViewContext *vc, int *dist)
void ED_mesh_polys_add (struct Mesh *mesh, struct ReportList *reports, int count)
void ED_mesh_tessfaces_add (struct Mesh *mesh, struct ReportList *reports, int count)
void ED_mesh_edges_add (struct Mesh *mesh, struct ReportList *reports, int count)
void ED_mesh_loops_add (struct Mesh *mesh, struct ReportList *reports, int count)
void ED_mesh_vertices_add (struct Mesh *mesh, struct ReportList *reports, int count)
void ED_mesh_faces_remove (struct Mesh *mesh, struct ReportList *reports, int count)
void ED_mesh_edges_remove (struct Mesh *mesh, struct ReportList *reports, int count)
void ED_mesh_vertices_remove (struct Mesh *mesh, struct ReportList *reports, int count)
void ED_mesh_transform (struct Mesh *me, float *mat)
void ED_mesh_calc_normals (struct Mesh *me)
void ED_mesh_calc_tessface (struct Mesh *mesh)
void ED_mesh_material_link (struct Mesh *me, struct Material *ma)
void ED_mesh_update (struct Mesh *mesh, struct bContext *C, int calc_edges, int calc_tessface)
int ED_mesh_uv_texture_add (struct bContext *C, struct Mesh *me, const char *name, int active_set)
int ED_mesh_uv_texture_remove (struct bContext *C, struct Object *ob, struct Mesh *me)
int ED_mesh_uv_loop_reset (struct bContext *C, struct Mesh *me)
int ED_mesh_uv_loop_reset_ex (struct bContext *C, struct Mesh *me, const int layernum)
int ED_mesh_color_add (struct bContext *C, struct Scene *scene, struct Object *ob, struct Mesh *me, const char *name, int active_set)
int ED_mesh_color_remove (struct bContext *C, struct Object *ob, struct Mesh *me)
int ED_mesh_color_remove_named (struct bContext *C, struct Object *ob, struct Mesh *me, const char *name)
void EDBM_selectmode_to_scene (struct bContext *C)
void EDBM_mesh_clear (struct BMEditMesh *em)
int ED_mesh_mirrtopo_recalc_check (struct Mesh *me, const int ob_mode, MirrTopoStore_t *mesh_topo_store)
void ED_mesh_mirrtopo_init (struct Mesh *me, const int ob_mode, MirrTopoStore_t *mesh_topo_store, const short skip_em_vert_array_init)
void ED_mesh_mirrtopo_free (MirrTopoStore_t *mesh_topo_store)
Variables
unsigned int bm_vertoffs
unsigned int bm_solidoffs
unsigned int bm_wireoffs
Detailed Description
Definition in file ED_mesh.h.
Define Documentation
#define WEIGHT_ADD 2
Definition at line 202 of file ED_mesh.h.
Referenced by ED_vgroup_nr_vert_add(), heat_bone_weighting(), and rna_def_vertex_group().
#define WEIGHT_REPLACE 1
Definition at line 201 of file ED_mesh.h.
Referenced by ED_vgroup_nr_vert_add(), envelope_bone_weighting(), heat_bone_weighting(), SkinInfo::link_armature(), and rna_def_vertex_group().
#define WEIGHT_SUBTRACT 3
Definition at line 203 of file ED_mesh.h.
Referenced by ED_vgroup_nr_vert_add(), and rna_def_vertex_group().
Typedef Documentation
typedef struct MirrTopoStore_t MirrTopoStore_t
Function Documentation
int do_paintface_box_select (struct ViewContext * vc, struct rcti * rect, int select, int extend)
Definition at line 558 of file editface.c.
References ViewContext::ar, B_ENDIAN, ENDIAN_ORDER, FALSE, MPoly::flag, get_mesh(), IB_rect, IMB_allocImBuf(), IMB_convert_rgba_to_abgr(), IMB_freeImBuf(), ImBuf::index, ME_FACE_SEL, ME_HIDE, MEM_callocN(), MEM_freeN(), Mesh::mpoly, NULL, ViewContext::obact, OPERATOR_CANCELLED, OPERATOR_FINISHED, paintface_deselect_all_visible(), paintface_flush_flags(), ImBuf::rect, SEL_DESELECT, Mesh::totpoly, view3d_validate_backbuf(), ARegion::winrct, WM_framebuffer_to_index(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by view3d_borderselect_exec().
void ED_keymap_mesh (struct wmKeyConfig * keyconf)
Definition at line 247 of file mesh_ops.c.
References ACTIONMOUSE, AKEY, DELKEY, DKEY, ED_object_generic_keymap(), ED_operator_editmesh(), EKEY, FALSE, FKEY, GKEY, HKEY, i, IKEY, JKEY, KKEY, KM_ALT, KM_CLICK, KM_CTRL, KM_PRESS, KM_SHIFT, knifetool_modal_keymap(), LKEY, MKEY, NKEY, PADMINUS, PADPLUSKEY, PKEY, wmKeyMap::poll, wmKeyMapItem::ptr, RKEY, RNA_boolean_set(), RNA_enum_set(), RNA_int_set(), SEL_INVERT, SEL_TOGGLE, SELECTMOUSE, SKEY, TABKEY, TKEY, TRUE, UKEY, VKEY, WKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), XKEY, YKEY, and ZEROKEY.
Referenced by ED_spacetypes_keymap().
void ED_mesh_calc_normals (struct Mesh * me)
Definition at line 1170 of file mesh_data.c.
References FALSE, mesh_calc_normals(), mesh_calc_normals_mapping_ex(), Mesh::mloop, Mesh::mpoly, Mesh::mvert, NULL, Mesh::totloop, Mesh::totpoly, and Mesh::totvert.
void ED_mesh_calc_tessface (struct Mesh * mesh)
Definition at line 1183 of file mesh_data.c.
References BKE_mesh_tessface_calc(), BMEdit_RecalcTessellation(), and Mesh::edit_btmesh.
int ED_mesh_color_add (struct bContext * C, struct Scene * scene, struct Object * ob, struct Mesh * me, const char * name, int active_set)
Referenced by mesh_vertex_color_add_exec(), and output_toggle_exec().
int ED_mesh_color_remove (struct bContext * C, struct Object * ob, struct Mesh * me)
Definition at line 495 of file mesh_data.c.
References CD_MLOOPCOL, CustomData_get_active_layer_index(), DAG_id_tag_update(), delete_customdata_layer(), GET_CD_DATA, Mesh::id, if(), CustomData::layers, NC_GEOM, ND_DATA, NULL, and WM_event_add_notifier().
Referenced by mesh_vertex_color_remove_exec().
int ED_mesh_color_remove_named (struct bContext * C, struct Object * ob, struct Mesh * me, const char * name)
Definition at line 514 of file mesh_data.c.
References CD_MLOOPCOL, CustomData_get_named_layer_index(), DAG_id_tag_update(), delete_customdata_layer(), GET_CD_DATA, Mesh::id, if(), CustomData::layers, NC_GEOM, ND_DATA, NULL, and WM_event_add_notifier().
Referenced by output_toggle_exec().
void ED_mesh_edges_add (struct Mesh * mesh, struct ReportList * reports, int count)
Definition at line 1088 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_add_edges(), and RPT_ERROR.
void ED_mesh_edges_remove (struct Mesh * mesh, struct ReportList * reports, int count)
Definition at line 1122 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_remove_edges(), RPT_ERROR, and Mesh::totedge.
void ED_mesh_faces_remove (struct Mesh * mesh, struct ReportList * reports, int count)
Definition at line 1108 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_remove_faces(), RPT_ERROR, and Mesh::totface.
void ED_mesh_loops_add (struct Mesh * mesh, struct ReportList * reports, int count)
Definition at line 1150 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_add_loops(), and RPT_ERROR.
void ED_mesh_material_link (struct Mesh * me, struct Material * ma)
void ED_mesh_mirrtopo_free (MirrTopoStore_t * mesh_topo_store)
Definition at line 935 of file editface.c.
References MirrTopoStore_t::index_lookup, MEM_freeN(), NULL, MirrTopoStore_t::prev_edge_tot, and MirrTopoStore_t::prev_vert_tot.
Referenced by ED_mesh_mirrtopo_init(), EDBM_verts_mirror_cache_begin(), and mesh_mirrtopo_table().
void ED_mesh_mirrtopo_init (struct Mesh * me, const int ob_mode, MirrTopoStore_t * mesh_topo_store, const short skip_em_vert_array_init)
Definition at line 777 of file editface.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_index_get, BM_ITER_MESH, BM_mesh_elem_index_ensure(), BM_VERT, ED_mesh_mirrtopo_free(), EDBM_index_arrays_free(), EDBM_index_arrays_init(), EDBM_vert_at_index(), Mesh::edit_btmesh, FALSE, hash, MirrTopoVert_t::hash, MirrTopoStore_t::index_lookup, Mesh::medge, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), MEM_mallocN(), mirrtopo_hash_sort(), mirrtopo_vert_sort(), NULL, MirrTopoStore_t::prev_edge_tot, MirrTopoStore_t::prev_ob_mode, MirrTopoStore_t::prev_vert_tot, BMesh::totedge, Mesh::totedge, BMesh::totvert, Mesh::totvert, BMEdge::v1, MEdge::v1, BMEdge::v2, MEdge::v2, and MirrTopoVert_t::v_index.
Referenced by EDBM_verts_mirror_cache_begin(), and mesh_mirrtopo_table().
int ED_mesh_mirrtopo_recalc_check (struct Mesh * me, const int ob_mode, MirrTopoStore_t * mesh_topo_store)
Definition at line 750 of file editface.c.
References BMEditMesh::bm, Mesh::edit_btmesh, FALSE, MirrTopoStore_t::index_lookup, NULL, MirrTopoStore_t::prev_edge_tot, MirrTopoStore_t::prev_ob_mode, MirrTopoStore_t::prev_vert_tot, BMesh::totedge, Mesh::totedge, BMesh::totvert, Mesh::totvert, and TRUE.
Referenced by mesh_mirrtopo_table().
void ED_mesh_polys_add (struct Mesh * mesh, struct ReportList * reports, int count)
Definition at line 1160 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_add_polys(), and RPT_ERROR.
void ED_mesh_tessfaces_add (struct Mesh * mesh, struct ReportList * reports, int count)
Definition at line 1073 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_add_tessfaces(), Mesh::mpoly, and RPT_ERROR.
void ED_mesh_transform (struct Mesh * me, float * mat)
Definition at line 891 of file mesh_data.c.
References MVert::co, i, mul_m4_v3(), Mesh::mvert, and Mesh::totvert.
void ED_mesh_update (struct Mesh * mesh, struct bContext * C, int calc_edges, int calc_tessface)
Definition at line 808 of file mesh_data.c.
References BKE_mesh_calc_edges(), BKE_mesh_convert_mfaces_to_mpolys(), BKE_mesh_tessface_calc(), BKE_mesh_tessface_clear(), CD_CALLOC, CD_NORMAL, CD_POLYINDEX, CustomData_add_layer(), CustomData_get_layer(), DAG_id_tag_update(), FALSE, Mesh::fdata, Mesh::id, mesh_calc_normals(), mesh_calc_normals_mapping_ex(), Mesh::mface, Mesh::mloop, Mesh::mpoly, Mesh::mvert, NC_GEOM, ND_DATA, NULL, Mesh::totedge, Mesh::totface, Mesh::totloop, Mesh::totpoly, Mesh::totvert, TRUE, and WM_event_add_notifier().
int ED_mesh_uv_loop_reset (struct bContext * C, struct Mesh * me)
Definition at line 336 of file mesh_data.c.
References CD_MTEXPOLY, CustomData_get_active_layer_index(), ED_mesh_uv_loop_reset_ex(), and GET_CD_DATA.
Referenced by reset_exec().
int ED_mesh_uv_loop_reset_ex (struct bContext * C, struct Mesh * me, const int layernum)
Definition at line 228 of file mesh_data.c.
References BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_free, BLI_assert, BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, CD_MLOOPUV, cos(), CustomData_bmesh_get_n(), CustomData_get_layer_n(), CustomData_has_layer(), DAG_id_tag_update(), BMHeader::data, Mesh::edit_btmesh, BMLoop::head, i, Mesh::id, Mesh::ldata, BMesh::ldata, len(), BMFace::len, MPoly::loopstart, M_PI, Mesh::mpoly, NC_GEOM, ND_DATA, NULL, sin(), MPoly::totloop, Mesh::totpoly, MLoopUV::uv, and WM_event_add_notifier().
Referenced by ED_mesh_uv_loop_reset(), ED_mesh_uv_texture_add(), and ED_uvedit_ensure_uvs().
int ED_mesh_uv_texture_add (struct bContext * C, struct Mesh * me, const char * name, int active_set)
Definition at line 345 of file mesh_data.c.
References BMEditMesh::bm, BM_data_layer_add_named(), CD_DEFAULT, CD_DUPLICATE, CD_MLOOPUV, CD_MTEXPOLY, CD_MTFACE, CustomData_add_layer_named(), CustomData_number_of_layers(), CustomData_set_layer_active(), DAG_id_tag_update(), ED_mesh_uv_loop_reset_ex(), Mesh::edit_btmesh, editmesh_face_copy_customdata(), editmesh_loop_copy_customdata(), FALSE, Mesh::fdata, Mesh::id, Mesh::ldata, BMesh::ldata, MAX_MTFACE, mesh_update_customdata_pointers(), Mesh::mloopuv, Mesh::mtface, Mesh::mtpoly, NC_GEOM, ND_DATA, NULL, BMesh::pdata, Mesh::totface, Mesh::totloop, Mesh::totpoly, TRUE, and WM_event_add_notifier().
Referenced by mesh_uv_texture_add_exec().
int ED_mesh_uv_texture_remove (struct bContext * C, struct Object * ob, struct Mesh * me)
Definition at line 418 of file mesh_data.c.
References CD_MLOOPUV, CD_MTEXPOLY, CustomData_get_active_layer_index(), DAG_id_tag_update(), delete_customdata_layer(), GET_CD_DATA, Mesh::id, if(), CustomData::layers, NC_GEOM, ND_DATA, NULL, and WM_event_add_notifier().
Referenced by mesh_uv_texture_remove_exec().
void ED_mesh_vertices_add (struct Mesh * mesh, struct ReportList * reports, int count)
Definition at line 1098 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_add_verts(), and RPT_ERROR.
void ED_mesh_vertices_remove (struct Mesh * mesh, struct ReportList * reports, int count)
Definition at line 1136 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_remove_verts(), RPT_ERROR, and Mesh::totvert.
void ED_operatormacros_mesh (void)
Definition at line 192 of file mesh_ops.c.
References wmOperatorType::description, FALSE, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorTypeMacro::ptr, RNA_boolean_set(), RNA_enum_set(), RNA_struct_idprops_unset(), WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().
void ED_operatortypes_mesh (void)
Definition at line 59 of file mesh_ops.c.
References MESH_OT_beautify_fill(), MESH_OT_bevel(), MESH_OT_blend_from_shape(), MESH_OT_bridge_edge_loops(), MESH_OT_colors_reverse(), MESH_OT_colors_rotate(), MESH_OT_delete(), MESH_OT_dissolve(), MESH_OT_dissolve_limited(), MESH_OT_drop_named_image(), MESH_OT_dupli_extrude_cursor(), MESH_OT_duplicate(), MESH_OT_edge_collapse(), MESH_OT_edge_collapse_loop(), MESH_OT_edge_face_add(), MESH_OT_edge_rotate(), MESH_OT_edge_split(), MESH_OT_edgering_select(), MESH_OT_edges_select_sharp(), MESH_OT_extrude_edges_indiv(), MESH_OT_extrude_faces_indiv(), MESH_OT_extrude_region(), MESH_OT_extrude_repeat(), MESH_OT_extrude_verts_indiv(), MESH_OT_faces_select_linked_flat(), MESH_OT_faces_shade_flat(), MESH_OT_faces_shade_smooth(), MESH_OT_fill(), MESH_OT_flip_normals(), MESH_OT_hide(), MESH_OT_inset(), MESH_OT_knife_tool(), MESH_OT_loop_multi_select(), MESH_OT_loop_select(), MESH_OT_loop_to_region(), MESH_OT_loopcut(), MESH_OT_mark_seam(), MESH_OT_mark_sharp(), MESH_OT_merge(), MESH_OT_navmesh_clear(), MESH_OT_navmesh_face_add(), MESH_OT_navmesh_face_copy(), MESH_OT_navmesh_make(), MESH_OT_navmesh_reset(), MESH_OT_noise(), MESH_OT_normals_make_consistent(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cube_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_monkey_add(), MESH_OT_primitive_plane_add(), MESH_OT_primitive_uv_sphere_add(), MESH_OT_quads_convert_to_tris(), MESH_OT_region_to_loop(), MESH_OT_remove_doubles(), MESH_OT_reveal(), MESH_OT_rip(), MESH_OT_screw(), MESH_OT_select_all(), MESH_OT_select_axis(), MESH_OT_select_by_number_vertices(), MESH_OT_select_interior_faces(), MESH_OT_select_less(), MESH_OT_select_linked(), MESH_OT_select_linked_pick(), MESH_OT_select_loose_verts(), MESH_OT_select_mirror(), MESH_OT_select_more(), MESH_OT_select_next_loop(), MESH_OT_select_non_manifold(), MESH_OT_select_nth(), MESH_OT_select_random(), MESH_OT_select_shortest_path(), MESH_OT_select_similar(), MESH_OT_select_vertex_path(), MESH_OT_separate(), MESH_OT_shape_propagate_to_all(), MESH_OT_solidify(), MESH_OT_sort_faces(), MESH_OT_spin(), MESH_OT_split(), MESH_OT_sticky_add(), MESH_OT_sticky_remove(), MESH_OT_subdivide(), MESH_OT_tris_convert_to_quads(), MESH_OT_uv_texture_add(), MESH_OT_uv_texture_remove(), MESH_OT_uvs_reverse(), MESH_OT_uvs_rotate(), MESH_OT_vert_connect(), MESH_OT_vert_slide(), MESH_OT_vertex_color_add(), MESH_OT_vertex_color_remove(), MESH_OT_vertices_randomize(), MESH_OT_vertices_smooth(), MESH_OT_vertices_sort(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
void ED_spacetypes_init (void)
Definition at line 67 of file spacetypes.c.
Referenced by WM_init().
struct bDeformGroup* ED_vgroup_add (struct Object * ob) [read]
Definition at line 121 of file object_vgroup.c.
References ED_vgroup_add_name().
Referenced by vertex_group_add_exec(), vertex_group_assign_exec(), and wpaint_stroke_test_start().
struct bDeformGroup* ED_vgroup_add_name (struct Object * ob, const char * name) [read]
Definition at line 102 of file object_vgroup.c.
References Object::actdef, BLI_addtail(), BLI_countlist(), BLI_strncpy(), Object::defbase, defgroup_unique_name(), MEM_callocN(), bDeformGroup::name, NULL, OB_TYPE_SUPPORT_VGROUP, and Object::type.
Referenced by dgroup_skinnable_cb(), ED_vgroup_add(), SkinInfo::link_armature(), output_toggle_exec(), vgroup_add_unique_bone_cb(), wpaint_mirror_vgroup_ensure(), and wpaint_stroke_test_start().
void ED_vgroup_clear (struct Object * ob)
Definition at line 145 of file object_vgroup.c.
References Object::defbase, ED_vgroup_object_is_edit_mode(), ListBase::first, bDeformGroup::next, vgroup_delete_edit_mode(), and vgroup_delete_object_mode().
int ED_vgroup_copy_array (struct Object * ob, struct Object * ob_from)
Definition at line 315 of file object_vgroup.c.
References Object::actdef, BLI_countlist(), BLI_duplicatelist(), BLI_freelistN(), Object::data, Object::defbase, ED_vgroup_data_create(), ED_vgroup_give_parray(), FALSE, i, MEM_dupallocN(), MEM_freeN(), MEM_mallocN(), NULL, TRUE, vgroup_delete_all(), and vgroup_remap_update_users().
Referenced by vertex_group_copy_to_selected_exec().
int ED_vgroup_data_create (struct ID * id)
Definition at line 162 of file object_vgroup.c.
References CD_CALLOC, CD_MDEFORMVERT, CustomData_add_layer(), Lattice::dvert, Mesh::dvert, FALSE, GS, ID_LT, ID_ME, MEM_callocN(), ID::name, NULL, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, Mesh::totvert, and TRUE.
Referenced by create_vgroups_from_armature(), ED_vgroup_copy_array(), ED_vgroup_vert_add(), vgroup_active_remove_verts(), vgroup_assign_verts(), and wpaint_stroke_test_start().
void ED_vgroup_delete (struct Object * ob, struct bDeformGroup * defgroup)
Definition at line 126 of file object_vgroup.c.
References Object::defbase, ED_vgroup_object_is_edit_mode(), ListBase::first, bDeformGroup::next, NULL, vgroup_delete_edit_mode(), and vgroup_delete_object_mode().
Referenced by output_toggle_exec().
int ED_vgroup_give_array (struct ID * id, struct MDeformVert ** dvert_arr, int * dvert_tot)
Definition at line 287 of file object_vgroup.c.
References Lattice::dvert, Mesh::dvert, Lattice::editlatt, FALSE, GS, ID_LT, ID_ME, EditLatt::latt, ID::name, NULL, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, Mesh::totvert, and TRUE.
Referenced by ED_vgroup_nr_vert_add(), ED_vgroup_vert_add(), ED_vgroup_vert_remove(), vgroup_delete_object_mode(), and vgroup_do_remap().
void ED_vgroup_mirror (struct Object * ob, const short mirror_weights, const short flip_vgroups, const short all_vgroups)
Definition at line 1520 of file object_vgroup.c.
References Object::actdef, BLI_assert, BLI_findlink(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, CD_MDEFORMVERT, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, Object::data, Lattice::def, Object::defbase, defgroup_flip_map(), defgroup_flip_map_single(), Lattice::dvert, Mesh::dvert, EDBM_verts_mirror_cache_begin(), EDBM_verts_mirror_cache_clear(), EDBM_verts_mirror_cache_end(), EDBM_verts_mirror_get(), Mesh::edit_btmesh, Mesh::editflag, BPoint::f1, FALSE, MVert::flag, BMVert::head, LT_INDEX, ME_EDIT_VERT_SEL, ME_VERT_TMP_TAG, MEM_freeN(), mesh_get_x_mirror_vert(), Mesh::mvert, NULL, OB_LATTICE, OB_MESH, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, SELECT, TRUE, Object::type, BMesh::vdata, vgroup_edit_lattice(), and VGROUP_MIRR_OP.
Referenced by do_view3d_vgroup_buttons(), and vertex_group_mirror_exec().
int ED_vgroup_object_is_edit_mode (struct Object * ob)
Definition at line 92 of file object_vgroup.c.
References BMEdit_FromObject(), Object::data, NULL, OB_LATTICE, OB_MESH, and Object::type.
Referenced by ED_vgroup_clear(), and ED_vgroup_delete().
void ED_vgroup_select_by_name (struct Object * ob, const char * name)
Definition at line 571 of file object_vgroup.c.
References Object::actdef, and defgroup_name_index().
Referenced by ED_do_pose_selectbuffer(), pose_bone_flip_active_exec(), and set_wpaint().
void ED_vgroup_vert_add (struct Object * ob, struct bDeformGroup * dg, int vertnum, float weight, int assignmode)
Definition at line 461 of file object_vgroup.c.
References BLI_findindex(), Object::data, Object::defbase, ED_vgroup_data_create(), ED_vgroup_give_array(), ED_vgroup_nr_vert_add(), and NULL.
Referenced by envelope_bone_weighting(), heat_bone_weighting(), and SkinInfo::link_armature().
void ED_vgroup_vert_remove (struct Object * ob, struct bDeformGroup * dg, int vertnum)
Definition at line 487 of file object_vgroup.c.
References BLI_findindex(), Object::data, Object::defbase, defvert_find_index(), defvert_remove_group(), ED_vgroup_give_array(), and NULL.
Referenced by envelope_bone_weighting(), and heat_bone_weighting().
float ED_vgroup_vert_weight (struct Object * ob, struct bDeformGroup * dg, int vertnum)
Definition at line 560 of file object_vgroup.c.
References BLI_findindex(), Object::defbase, and get_vert_def_nr().
Referenced by heat_bone_weighting().
void EDBM_automerge (struct Scene * scene, struct Object * ob, int update)
Definition at line 105 of file editmesh_select.c.
References ToolSettings::automerge, BMEditMesh::bm, BM_ELEM_SELECT, BMEdit_FromObject(), BMEdit_RecalcTessellation(), BMO_op_callf(), DAG_id_tag_update(), Object::data, ToolSettings::doublimit, OB_MESH, OB_RECALC_DATA, Scene::toolsettings, and Object::type.
Referenced by special_aftertrans_update().
int EDBM_backbuf_border_init (struct ViewContext * vc, short xmin, short ymin, short xmax, short ymax)
Definition at line 179 of file editmesh_select.c.
References bm_vertoffs, View3D::drawtype, View3D::flag, IMB_freeImBuf(), MEM_callocN(), NULL, OB_SOLID, ViewContext::obedit, ImBuf::rect, ViewContext::v3d, V3D_ZBUF_SELECT, and view3d_read_backbuf().
Referenced by do_mesh_box_select().
int EDBM_backbuf_border_mask_init (struct ViewContext * vc, int mcords[][2], short tot, short xmin, short ymin, short xmax, short ymax)
Definition at line 228 of file editmesh_select.c.
References ViewContext::ar, bm_vertoffs, draw_triangulated(), View3D::drawtype, ED_region_pixelspace(), View3D::flag, IMB_freeImBuf(), MEM_callocN(), NULL, OB_SOLID, ViewContext::obact, ViewContext::obedit, paint_facesel_test(), paint_vertsel_test(), ImBuf::rect, ViewContext::v3d, V3D_ZBUF_SELECT, and view3d_read_backbuf().
Referenced by do_lasso_select_mesh(), do_lasso_select_paintface(), and do_lasso_select_paintvert().
int EDBM_backbuf_check (unsigned int index)
Definition at line 208 of file editmesh_select.c.
References bm_vertoffs, ImBuf::index, and NULL.
Referenced by do_lasso_select_mesh__doSelectEdge(), do_mesh_box_select__doSelectEdge(), edbm_backbuf_check_and_select_edges(), edbm_backbuf_check_and_select_faces(), edbm_backbuf_check_and_select_tfaces(), edbm_backbuf_check_and_select_verts(), and edbm_backbuf_check_and_select_verts_obmode().
int EDBM_backbuf_circle_init (struct ViewContext * vc, short xs, short ys, short rads)
Definition at line 289 of file editmesh_select.c.
References bm_vertoffs, View3D::drawtype, View3D::flag, IMB_freeImBuf(), MEM_callocN(), NULL, OB_SOLID, ViewContext::obact, ViewContext::obedit, paint_facesel_test(), paint_vertsel_test(), ImBuf::rect, ViewContext::v3d, V3D_ZBUF_SELECT, and view3d_read_backbuf().
Referenced by mesh_circle_select(), paint_facesel_circle_select(), and paint_vertsel_circle_select().
void EDBM_backbuf_free (void)
Definition at line 216 of file editmesh_select.c.
References MEM_freeN(), and NULL.
Referenced by do_lasso_select_mesh(), do_lasso_select_paintface(), do_lasso_select_paintvert(), do_mesh_box_select(), mesh_circle_select(), paint_facesel_circle_select(), and paint_vertsel_circle_select().
void EDBM_data_layer_add (struct BMEditMesh * em, struct CustomData * data, int type, const char * name)
void EDBM_data_layer_free (struct BMEditMesh * em, struct CustomData * data, int type)
void EDBM_deselect_by_material (struct BMEditMesh * em, const short index, const short select)
Definition at line 1659 of file editmesh_select.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_face_select_set(), BM_FACES_OF_MESH, BM_ITER_MESH, and BMFace::mat_nr.
Referenced by material_slot_de_select().
void EDBM_deselect_flush (struct BMEditMesh * em)
Definition at line 421 of file editmesh_utils.c.
References BMEditMesh::bm, BM_mesh_deselect_flush(), BMEditMesh::selectmode, and BMesh::selectmode.
Referenced by border_select_exec(), mouse_select(), and vgroup_select_verts().
struct BMEdge* EDBM_edge_at_index (struct BMEditMesh * em, int index) [read]
Definition at line 399 of file editmesh_utils.c.
References BMEditMesh::bm, BMEditMesh::edge_index, NULL, and BMesh::totedge.
Referenced by bbs_mesh_wire__setDrawOptions(), construct_param_handle_subsurfed(), draw_dm_bweights__setDrawOptions(), draw_dm_creases__setDrawOptions(), draw_dm_edges__setDrawOptions(), draw_dm_edges_seams__setDrawOptions(), draw_dm_edges_sel__setDrawOptions(), draw_dm_edges_sel_interp__setDrawInterpOptions(), draw_dm_edges_sel_interp__setDrawOptions(), draw_dm_edges_sharp__setDrawOptions(), edgetag_add_adjacent(), edgetag_shortest_path(), mesh_foreachScreenEdge__mapFunc(), and snapDerivedMesh().
struct BMEdge* EDBM_edge_find_nearest (struct ViewContext * vc, int * dist) [read]
Definition at line 498 of file editmesh_select.c.
References BMEditMesh::bm, BM_edge_at_index(), bm_wireoffs, data, distance(), View3D::drawtype, ED_view3d_init_mats_rv3d(), ViewContext::em, findnearestedge__doClosest(), View3D::flag, mesh_foreachScreenEdge(), ViewContext::mval, NULL, OB_WIRE, ViewContext::obedit, ViewContext::rv3d, ViewContext::v3d, V3D_ZBUF_SELECT, view3d_sample_backbuf_rect(), and view3d_validate_backbuf().
Referenced by loopcut_modal(), mouse_mesh_loop(), mouse_mesh_shortest_path(), ringcut_invoke(), and unified_findnearest().
struct BMFace* EDBM_face_at_index (struct BMEditMesh * em, int index) [read]
Definition at line 404 of file editmesh_utils.c.
References BMEditMesh::face_index, and NULL.
Referenced by bbs_mesh_solid__drawCenter(), bbs_mesh_solid__setSolidDrawOptions(), construct_param_handle_subsurfed(), draw_dm_face_centers__mapFunc(), draw_dm_face_normals__mapFunc(), draw_dm_faces_sel__compareDrawOptions(), draw_dm_faces_sel__setDrawOptions(), draw_em_fancy__setFaceOpts(), draw_em_fancy__setGLSLFaceOpts(), draw_em_tf_mapped__set_draw(), EDBM_uv_vert_map_create(), mesh_foreachScreenFace__mapFunc(), select_edgeloop_uv_edge_tag_faces(), snapDerivedMesh(), stitch_init(), tex_mat_set_face_editmesh_cb(), and uv_faces_do_sticky().
struct BMFace* EDBM_face_find_nearest (struct ViewContext * vc, int * dist) [read]
Definition at line 571 of file editmesh_select.c.
References BMEditMesh::bm, BM_face_at_index(), data, View3D::drawtype, ED_view3d_init_mats_rv3d(), ViewContext::em, findnearestface__doClosest(), findnearestface__getDistance(), View3D::flag, mesh_foreachScreenFace(), ViewContext::mval, NULL, OB_WIRE, ViewContext::obedit, ViewContext::rv3d, SCE_SELECT_FACE, BMEditMesh::selectmode, ViewContext::v3d, V3D_ZBUF_SELECT, view3d_sample_backbuf(), and view3d_validate_backbuf().
Referenced by knife_find_closest_face(), and unified_findnearest().
void EDBM_flag_disable_all (struct BMEditMesh * em, const char hflag)
Definition at line 468 of file editmesh_utils.c.
Referenced by do_lasso_select_mesh(), do_mesh_box_select(), edbm_delete_exec(), edbm_duplicate_exec(), edbm_extrude_edge(), edbm_extrude_edges_indiv(), edbm_extrude_face_indiv(), edbm_inset_exec(), edbm_loop_to_region_exec(), EDBM_mesh_reveal(), edbm_region_to_loop_exec(), edbm_screw_exec(), edbm_select_all_exec(), EDBM_select_mirrored(), edbm_select_random_exec(), EDBM_select_toggle_all(), edbm_spin_exec(), edbm_vertex_slide_exec(), edgering_sel(), knife_make_cuts(), mesh_separate_loose(), mesh_separate_material(), mouse_mesh(), mouse_mesh_loop(), select_all_perform(), similar_edge_select_exec(), similar_face_select_exec(), similar_vert_select_exec(), and vtx_slide_confirm().
void EDBM_flag_enable_all (struct BMEditMesh * em, const char hflag)
Definition at line 473 of file editmesh_utils.c.
References BMEditMesh::bm, BM_EDGE, BM_FACE, BM_mesh_elem_hflag_enable_all(), BM_VERT, and TRUE.
Referenced by edbm_select_all_exec(), EDBM_select_toggle_all(), and select_all_perform().
void EDBM_index_arrays_free (struct BMEditMesh * em)
Definition at line 376 of file editmesh_utils.c.
References BMEditMesh::edge_index, BMEditMesh::face_index, MEM_freeN(), NULL, and BMEditMesh::vert_index.
Referenced by construct_param_handle_subsurfed(), createRepresentation(), draw_em_fancy(), draw_object_backbufsel(), ED_mesh_mirrtopo_init(), EDBM_index_arrays_init(), EDBM_uv_vert_map_create(), edgetag_shortest_path(), make_trans_verts(), mesh_foreachScreenEdge(), mesh_foreachScreenFace(), mesh_foreachScreenVert(), select_edgeloop(), select_linked(), snapDerivedMesh(), stitch_init(), and uv_faces_do_sticky().
void EDBM_index_arrays_init (struct BMEditMesh * em, int forvert, int foredge, int forface)
Definition at line 332 of file editmesh_utils.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, EDBM_index_arrays_free(), BMEditMesh::edge_index, BMEditMesh::face_index, i, MEM_mallocN(), NULL, BMesh::totedge, BMesh::totface, BMesh::totvert, and BMEditMesh::vert_index.
Referenced by construct_param_handle_subsurfed(), createRepresentation(), draw_em_fancy(), draw_object_backbufsel(), ED_mesh_mirrtopo_init(), EDBM_uv_vert_map_create(), EDBM_verts_mirror_cache_begin(), edgetag_shortest_path(), make_trans_verts(), mesh_foreachScreenEdge(), mesh_foreachScreenFace(), mesh_foreachScreenVert(), select_edgeloop(), select_linked(), snapDerivedMesh(), stitch_init(), and uv_faces_do_sticky().
void EDBM_mesh_clear (struct BMEditMesh * em)
Definition at line 66 of file editmesh_utils.c.
References BMEditMesh::bm, BM_mesh_clear(), BMEditMesh::derivedCage, BMEditMesh::derivedFinal, BMEditMesh::looptris, MEM_freeN(), DerivedMesh::needsFree, NULL, DerivedMesh::release, and BMEditMesh::tottri.
Referenced by createRepresentation().
void EDBM_mesh_free (BMEditMesh * em)
Should only be called on the active editmesh, otherwise call BMEdit_Free
Definition at line 321 of file editmesh_utils.c.
References BMEdit_Free(), mesh_mirrtopo_table(), mesh_octree_table(), and NULL.
Referenced by drop_named_image_invoke(), ED_editors_exit(), ED_object_exit_editmode(), EDBM_mesh_make(), EDBM_op_finish(), join_mesh_exec(), and undoMesh_to_editbtMesh().
void EDBM_mesh_hide (struct BMEditMesh * em, int swap)
Definition at line 1153 of file editmesh_utils.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_elem_hide_set, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_MESH, BM_VERTS_OF_MESH, EDBM_selectmode_flush(), NULL, SCE_SELECT_EDGE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, and TRUE.
Referenced by edbm_hide_exec(), and hide_exec().
void EDBM_mesh_load (struct Object * ob)
Definition at line 306 of file editmesh_utils.c.
References BKE_mesh_tessface_calc(), BMEditMesh::bm, BM_mesh_bm_to_me(), Object::data, Mesh::edit_btmesh, and FALSE.
Referenced by drop_named_image_invoke(), ED_object_exit_editmode(), join_mesh_exec(), object_hook_index_array(), and vertex_parent_set_exec().
void EDBM_mesh_make (struct ToolSettings * ts, struct Scene * scene, struct Object * ob)
Referenced by drop_named_image_invoke(), ED_object_enter_editmode(), join_mesh_exec(), object_hook_index_array(), and vertex_parent_set_exec().
void EDBM_mesh_normals_update (struct BMEditMesh * em)
Definition at line 61 of file editmesh_utils.c.
References BMEditMesh::bm, BM_mesh_normals_update(), and TRUE.
Referenced by ED_object_enter_editmode(), edbm_bevel_exec(), edbm_dupli_extrude_cursor_invoke(), edbm_extrude_region_exec(), edbm_extrude_repeat_exec(), EDBM_mesh_reveal(), edbm_noise_exec(), edbm_split_exec(), object_origin_set_exec(), recalcData_view3d(), and v3d_editvertex_buts().
void EDBM_mesh_reveal (struct BMEditMesh * em)
Definition at line 1185 of file editmesh_utils.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_set, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_select_set(), BM_ELEM_TAG, BM_FACES_OF_MESH, BM_ITER_MESH, BM_VERTS_OF_MESH, EDBM_flag_disable_all(), EDBM_mesh_normals_update(), EDBM_selectmode_flush(), i, SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, and TRUE.
Referenced by edbm_reveal_exec(), and reveal_exec().
struct MTexPoly* EDBM_mtexpoly_active_get (struct BMEditMesh * em, struct BMFace ** r_act_efa, int sloppy) [read]
Definition at line 950 of file editmesh_utils.c.
References BMEditMesh::bm, BM_active_face_get(), CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, EDBM_mtexpoly_check(), BMFace::head, NULL, and BMesh::pdata.
Referenced by draw_uvs(), and image_refresh().
int EDBM_mtexpoly_check (struct BMEditMesh * em)
Definition at line 969 of file editmesh_utils.c.
References BMEditMesh::bm, CD_MLOOPUV, CD_MTEXPOLY, CustomData_has_layer(), BMesh::ldata, BMesh::pdata, and BMesh::totface.
Referenced by ED_space_image_show_uvedit(), ED_space_image_show_uvshadow(), ED_uvedit_test(), EDBM_mtexpoly_active_get(), image_refresh(), and uv_sculpt_brush_poll().
void EDBM_select_flush (struct BMEditMesh * em)
Definition at line 429 of file editmesh_utils.c.
References BMEditMesh::bm, BM_mesh_select_flush(), BMEditMesh::selectmode, and BMesh::selectmode.
Referenced by EDBM_select_more(), EDBM_selectmode_set(), mouse_select(), select_editbmesh_hook(), and vgroup_select_verts().
int EDBM_select_interior_faces (struct BMEditMesh * em)
Definition at line 1713 of file editmesh_select.c.
References BMEditMesh::bm, BM_edge_face_count(), BM_EDGES_OF_FACE, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_face_select_set(), BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, FALSE, and TRUE.
Referenced by edbm_faces_select_interior_exec().
void EDBM_select_less (struct BMEditMesh * em)
Definition at line 452 of file editmesh_utils.c.
References BMEditMesh::bm, BM_ALL, BM_ELEM_SELECT, BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_hflag_disable(), EDBM_selectmode_flush(), FALSE, SCE_SELECT_FACE, BMEditMesh::selectmode, and TRUE.
Referenced by edbm_select_less_exec().
void EDBM_select_mirrored (struct Object * obedit, struct BMEditMesh * em, int extend)
Referenced by edbm_select_mirror_exec().
void EDBM_select_more (struct BMEditMesh * em)
Definition at line 436 of file editmesh_utils.c.
References BMEditMesh::bm, BM_ALL, BM_ELEM_SELECT, BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_hflag_enable(), EDBM_select_flush(), FALSE, SCE_SELECT_FACE, BMEditMesh::selectmode, and TRUE.
Referenced by edbm_select_more_exec().
void EDBM_select_swap (struct BMEditMesh * em)
Definition at line 1681 of file editmesh_select.c.
References BMEditMesh::bm, BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_face_select_set(), BM_FACES_OF_MESH, BM_ITER_MESH, BM_vert_select_set(), BM_VERTS_OF_MESH, SCE_SELECT_EDGE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, and BMesh::selectmode.
Referenced by edbm_select_all_exec(), and select_all_perform().
void EDBM_select_toggle_all (struct BMEditMesh * em)
Definition at line 1673 of file editmesh_select.c.
References BMEditMesh::bm, BM_ELEM_SELECT, EDBM_flag_disable_all(), EDBM_flag_enable_all(), BMesh::totedgesel, BMesh::totfacesel, and BMesh::totvertsel.
Referenced by edbm_select_all_exec(), and select_all_perform().
void EDBM_selectmode_convert (struct BMEditMesh * em, short oldmode, short selectmode)
Definition at line 1601 of file editmesh_select.c.
References BMEditMesh::bm, BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SELECT, BM_face_select_set(), BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, NULL, SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, TRUE, BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by do_view3d_header_buttons().
void EDBM_selectmode_flush (struct BMEditMesh * em)
Definition at line 416 of file editmesh_utils.c.
References EDBM_selectmode_flush_ex(), and BMEditMesh::selectmode.
Referenced by deselect_nth_active(), do_lasso_select_mesh(), do_mesh_box_select(), edbm_edge_rotate_selected_exec(), edbm_loop_multiselect_exec(), EDBM_mesh_hide(), EDBM_mesh_reveal(), edbm_rip_invoke__edge(), edbm_select_all_exec(), edbm_select_axis_exec(), edbm_select_by_number_vertices_exec(), EDBM_select_less(), edbm_select_loose_verts_exec(), edbm_select_mirror_exec(), edbm_select_random_exec(), edbm_select_vertex_path_exec(), EDBM_selectmode_set(), edbm_vertex_slide_exec(), mesh_circle_select(), mouse_mesh(), mouse_mesh_loop(), mouse_mesh_shortest_path(), mouse_select(), ringsel_finish(), select_all_perform(), similar_edge_select_exec(), similar_vert_select_exec(), vtx_slide_confirm(), and vtx_slide_init().
void EDBM_selectmode_flush_ex (struct BMEditMesh * em, int selectmode)
Definition at line 409 of file editmesh_utils.c.
References BMEditMesh::bm, BM_mesh_select_mode_flush(), BMEditMesh::selectmode, and BMesh::selectmode.
Referenced by edbm_select_linked_exec(), EDBM_selectmode_flush(), hide_exec(), make_prim_finish(), mesh_separate_loose(), and walker_deselect_nth().
void EDBM_selectmode_set (struct BMEditMesh * em)
Definition at line 1558 of file editmesh_select.c.
References BMEditMesh::bm, BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SELECT, BM_face_select_set(), BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_vert_select_set(), BM_VERTS_OF_MESH, EDBM_select_flush(), EDBM_selectmode_flush(), edbm_strip_selections(), FALSE, NULL, SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, BMesh::selectmode, and TRUE.
Referenced by do_view3d_header_buttons(), edbm_region_to_loop_exec(), and ringsel_finish().
void EDBM_selectmode_to_scene (struct bContext * C)
Definition at line 259 of file editmesh_utils.c.
References BMEdit_FromObject(), CTX_data_edit_object(), CTX_data_scene(), NC_SCENE, ND_TOOLSETTINGS, BMEditMesh::selectmode, ToolSettings::selectmode, Scene::toolsettings, and WM_event_add_notifier().
Referenced by edbm_region_to_loop_exec(), and undo_editmode_step().
void EDBM_update_generic (struct bContext * C, struct BMEditMesh * em, const short do_tessface)
Definition at line 1231 of file editmesh_utils.c.
References BMEdit_RecalcTessellation(), DAG_id_tag_update(), Object::data, NC_GEOM, ND_DATA, BMEditMesh::ob, OB_RECALC_DATA, and WM_event_add_notifier().
Referenced by edbm_add_edge_face_exec(), edbm_beautify_fill_exec(), edbm_bevel_exec(), edbm_blend_from_shape_exec(), edbm_bridge_edge_loops_exec(), edbm_collapse_edge_exec(), edbm_collapse_edge_loop_exec(), edbm_delete_exec(), edbm_dissolve_exec(), edbm_dissolve_limited_exec(), edbm_do_smooth_vertex_exec(), edbm_dupli_extrude_cursor_invoke(), edbm_duplicate_exec(), edbm_edge_rotate_selected_exec(), edbm_edge_split_exec(), edbm_extrude_region_exec(), edbm_extrude_repeat_exec(), edbm_faces_shade_flat_exec(), edbm_faces_shade_smooth_exec(), edbm_fill_exec(), edbm_flip_normals_exec(), edbm_hide_exec(), edbm_inset_exec(), edbm_knife_cut_exec(), edbm_mark_seam(), edbm_mark_sharp(), edbm_merge_exec(), edbm_noise_exec(), edbm_normals_make_consistent_exec(), edbm_quads_convert_to_tris_exec(), edbm_remove_doubles_exec(), edbm_reveal_exec(), edbm_reverse_colors_exec(), edbm_reverse_uvs_exec(), edbm_rip_invoke(), edbm_rotate_colors_exec(), edbm_rotate_uvs_exec(), edbm_screw_exec(), edbm_select_nth_exec(), edbm_select_vertex_path_exec(), edbm_separate_exec(), edbm_shape_propagate_to_all_exec(), edbm_solidify_exec(), edbm_spin_exec(), edbm_split_exec(), edbm_subdivide_exec(), edbm_tris_convert_to_quads_exec(), edbm_vert_connect(), edbm_vertex_slide_exec(), knifetool_finish(), make_prim_finish(), mouse_mesh_shortest_path(), similar_edge_select_exec(), similar_face_select_exec(), similar_vert_select_exec(), and vtx_slide_confirm().
struct UvElementMap* EDBM_uv_element_map_create (struct BMEditMesh * em, int selected, int doIslands) [read]
Definition at line 710 of file editmesh_utils.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_index_get, BM_ELEM_SELECT, BM_FACE, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_ELEM_INDEX, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_index_ensure(), BM_VERT, BM_VERTS_OF_MESH, UvElementMap::buf, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, EDBM_uv_element_map_free(), fabsf, UvElement::face, BMLoop::head, i, INVALID_ISLAND, UvElement::island, UvElementMap::islandIndices, UvElement::l, BMesh::ldata, BMFace::len, MEM_callocN(), MEM_freeN(), MEM_mallocN(), UvElement::next, next, NULL, UvElement::separate, stack, STD_UV_CONNECT_LIMIT, sub_v2_v2v2(), UvElement::tfindex, UvElementMap::totalIslands, UvElementMap::totalUVs, BMesh::totface, BMesh::totvert, MLoopUV::uv, BMLoop::v, and UvElementMap::vert.
Referenced by stitch_init(), and uv_sculpt_stroke_init().
void EDBM_uv_element_map_free (struct UvElementMap * vmap)
Definition at line 938 of file editmesh_utils.c.
References UvElementMap::buf, UvElementMap::islandIndices, MEM_freeN(), and UvElementMap::vert.
Referenced by EDBM_uv_element_map_create(), stitch_state_delete(), and uv_sculpt_stroke_exit().
struct UvMapVert* EDBM_uv_vert_map_at_index (struct UvVertMap * vmap, unsigned int v) [read]
Definition at line 701 of file editmesh_utils.c.
References UvVertMap::vert.
Referenced by select_edgeloop_uv_vertex_map_get(), select_linked(), and uv_faces_do_sticky().
struct UvVertMap* EDBM_uv_vert_map_create (struct BMEditMesh * em, int selected, int do_face_idx_array, float * limit) [read]
Definition at line 570 of file editmesh_utils.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_index_get, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_iter_at_index(), BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_index_ensure(), BM_VERT, BM_VERTS_OF_MESH, UvVertMap::buf, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, EDBM_face_at_index(), EDBM_index_arrays_free(), EDBM_index_arrays_init(), UvMapVert::f, fabs(), free_uv_vert_map(), BMLoop::head, i, BMesh::ldata, BMFace::len, MEM_callocN(), UvMapVert::next, next, NULL, UvMapVert::separate, sub_v2_v2v2(), UvMapVert::tfindex, BMesh::totvert, MLoopUV::uv, BMLoop::v, and UvVertMap::vert.
Referenced by select_edgeloop(), select_linked(), and uv_faces_do_sticky().
void EDBM_uv_vert_map_free (struct UvVertMap * vmap)
Definition at line 929 of file editmesh_utils.c.
References UvVertMap::buf, MEM_freeN(), and UvVertMap::vert.
Referenced by select_edgeloop(), select_linked(), and uv_faces_do_sticky().
struct BMVert* EDBM_vert_at_index (struct BMEditMesh * em, int index) [read]
Definition at line 394 of file editmesh_utils.c.
References BMEditMesh::bm, NULL, BMesh::totvert, and BMEditMesh::vert_index.
Referenced by bbs_mesh_verts__mapFunc(), createRepresentation(), draw_dm_bweights__mapFunc(), draw_dm_vert_normals__mapFunc(), draw_dm_verts__mapFunc(), ED_mesh_mirrtopo_init(), edgetag_add_adjacent(), mesh_foreachScreenVert__mapFunc(), set_mapped_co(), and snapDerivedMesh().
int EDBM_vert_color_check (struct BMEditMesh * em)
Definition at line 976 of file editmesh_utils.c.
References BMEditMesh::bm, CD_MLOOPCOL, CustomData_has_layer(), BMesh::ldata, and BMesh::totface.
struct BMVert* EDBM_vert_find_nearest (ViewContext * vc, int * dist, short sel, short strict) [read]
findnearestvert
dist (in/out): minimal distance to the nearest and at the end, actual distance sel: selection bias if SELECT, selected vertice are given a 5 pixel bias to make them further than unselect verts if 0, unselected vertice are given the bias strict: if 1, the vertice corresponding to the sel parameter are ignored and not just biased
Definition at line 380 of file editmesh_select.c.
References BMEditMesh::bm, BM_vert_at_index(), bm_wireoffs, data, distance(), View3D::drawtype, ED_view3d_init_mats_rv3d(), ViewContext::em, findnearestvert__backbufIndextest(), findnearestvert__doClosest(), View3D::flag, mesh_foreachScreenVert(), ViewContext::mval, NULL, OB_WIRE, ViewContext::obedit, ViewContext::rv3d, ViewContext::v3d, V3D_CLIP_TEST_RV3D_CLIPPING, V3D_ZBUF_SELECT, and view3d_sample_backbuf_rect().
Referenced by unified_findnearest().
void EDBM_verts_mirror_apply (struct BMEditMesh * em, const int sel_from, const int sel_to)
Definition at line 1131 of file editmesh_utils.c.
References BLI_assert, BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, BMVert::co, copy_v3_v3(), EDBM_verts_mirror_get(), NULL, and BMEditMesh::vert_index.
Referenced by edbm_do_smooth_vertex_exec().
void EDBM_verts_mirror_cache_begin (struct BMEditMesh * em, const short use_select)
Definition at line 1012 of file editmesh_utils.c.
References BMEditMesh::bm, BM_CD_LAYER_ID, BM_data_layer_add_named(), BM_elem_flag_test, BM_elem_index_get, BM_ELEM_SELECT, BM_ITER_MESH, BM_mesh_elem_index_ensure(), BM_SEARCH_MAXDIST_MIRR, BM_VERT, BM_VERTS_OF_MESH, BMBVH_FindClosestVert(), BMBVH_FreeBVH(), BMBVH_NewBVH(), cache_mirr_intptr_as_bmvert(), CD_FLAG_TEMPORARY, CD_PROP_INT, BMVert::co, co, CustomData_bmesh_get_layer_n(), CustomData_get_layer_named(), CustomData_get_named_layer_index(), BMHeader::data, ED_mesh_mirrtopo_free(), ED_mesh_mirrtopo_init(), EDBM_index_arrays_init(), Mesh::editflag, CustomDataLayer::flag, BMVert::head, MirrTopoStore_t::index_lookup, CustomData::layers, BMEditMesh::me, ME_EDIT_MIRROR_TOPO, mesh_topo_store, BMEditMesh::mirr_free_arrays, BMEditMesh::mirror_cdlayer, NULL, TRUE, BMesh::vdata, and BMEditMesh::vert_index.
Referenced by createTransEditVerts(), ED_vgroup_mirror(), edbm_do_smooth_vertex_exec(), and EDBM_select_mirrored().
void EDBM_verts_mirror_cache_clear (struct BMEditMesh * em, struct BMVert * v)
Definition at line 1110 of file editmesh_utils.c.
References BLI_assert, BMEditMesh::bm, CustomData_bmesh_get_layer_n(), BMHeader::data, BMVert::head, BMEditMesh::mirror_cdlayer, and BMesh::vdata.
Referenced by ED_vgroup_mirror().
void EDBM_verts_mirror_cache_end (struct BMEditMesh * em)
Definition at line 1121 of file editmesh_utils.c.
References MEM_freeN(), BMEditMesh::mirr_free_arrays, BMEditMesh::mirror_cdlayer, NULL, and BMEditMesh::vert_index.
Referenced by createTransEditVerts(), ED_vgroup_mirror(), edbm_do_smooth_vertex_exec(), and EDBM_select_mirrored().
struct BMVert* EDBM_verts_mirror_get (struct BMEditMesh * em, struct BMVert * v) [read]
Definition at line 1091 of file editmesh_utils.c.
References BLI_assert, BMEditMesh::bm, CustomData_bmesh_get_layer_n(), BMHeader::data, BMVert::head, BMEditMesh::mirror_cdlayer, NULL, BMesh::vdata, and BMEditMesh::vert_index.
Referenced by createTransEditVerts(), ED_vgroup_mirror(), EDBM_select_mirrored(), and EDBM_verts_mirror_apply().
struct BMVert* editbmesh_get_x_mirror_vert (struct Object * ob, struct BMEditMesh * em, struct BMVert * eve, float * co, int index) [read]
Definition at line 974 of file meshtools.c.
References Object::data, editbmesh_get_x_mirror_vert_spacial(), editbmesh_get_x_mirror_vert_topo(), and ME_EDIT_MIRROR_TOPO.
Referenced by editvert_mirror_update().
void EMBM_project_snap_verts (struct bContext * C, struct ARegion * ar, struct Object * obedit, struct BMEditMesh * em)
Definition at line 150 of file editmesh_tools.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, BMVert::co, Object::imat, mul_v3_m4v3(), Object::obmat, project_float_noclip(), SNAP_NOT_OBEDIT, and snapObjectsContext().
Referenced by edbm_dupli_extrude_cursor_invoke().
int join_mesh_exec (struct bContext * C, struct wmOperator * op)
Definition at line 92 of file meshtools.c.
References Object::actdef, add_key(), BKE_report(), BKE_reportf(), BLI_addtail(), BLI_findlink(), BLI_remlink(), Key::block, CD_CALLOC, CD_DEFAULT, CD_MASK_MESH, CD_MDEFORMVERT, CD_MEDGE, CD_MLOOP, CD_MPOLY, CD_MVERT, MVert::co, copy_key(), copy_v3_v3(), CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), CustomData_add_layer(), CustomData_copy_data(), CustomData_free(), CustomData_get(), CustomData_merge(), DAG_id_tag_update(), DAG_scene_sort(), Object::data, KeyBlock::data, MDeformWeight::def_nr, Object::defbase, defgroup_find_name(), MDeformVert::dw, MLoop::e, ED_base_object_free_and_unlink(), ED_object_enter_editmode(), ED_object_exit_editmode(), EDBM_mesh_free(), EDBM_mesh_load(), EDBM_mesh_make(), EM_DO_UNDO, EM_FREEDATA, EM_WAITCURSOR, ListBase::first, free_ipo(), free_key(), give_current_material(), i, Material::id, Object::id, id_us_plus(), if(), invert_m4_m4(), Main::ipo, Main::key, Mesh::key, key_get_named_keyblock(), KEY_RELATIVE, ListBase::last, Mesh::ldata, MPoly::loopstart, Object::mat, Mesh::mat, MPoly::mat_nr, Object::matbits, MAXMAT, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), MESH_MAX_VERTS, mesh_update_customdata_pointers(), mul_m4_v3(), mult_m4_m4m4(), multiresModifier_prepare_join(), bDeformGroup::name, KeyBlock::name, NC_SCENE, ND_OB_ACTIVE, KeyBlock::next, bDeformGroup::next, NULL, OB_MESH, OB_RECALC_DATA, OB_RECALC_OB, Scene::obedit, Object::obmat, OPERATOR_CANCELLED, OPERATOR_FINISHED, KeyBlock::pos, KeyBlock::prev, Key::refkey, wmOperator::reports, RPT_WARNING, STRINGIFY, test_object_materials(), Scene::toolsettings, Object::totcol, Mesh::totcol, Mesh::totedge, KeyBlock::totelem, Key::totkey, Mesh::totloop, Mesh::totpoly, LaplacianSystem::totvert, Mesh::totvert, MDeformVert::totweight, TRUE, Key::type, Object::type, ID::us, MLoop::v, MEdge::v1, MEdge::v2, KeyBlock::weights, and WM_event_add_notifier().
Referenced by join_exec().
int join_mesh_shapes_exec (struct bContext * C, struct wmOperator * op)
Definition at line 561 of file meshtools.c.
References add_key(), add_keyblock(), BKE_report(), CD_MASK_BAREMESH, CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_scene(), Object::data, DM_to_meshkey(), if(), Mesh::key, KEY_RELATIVE, mesh_get_derived_deform(), mesh_to_key(), NC_SCENE, ND_OB_ACTIVE, NULL, OB_MESH, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_WARNING, Mesh::totvert, and WM_event_add_notifier().
Referenced by join_shapes_exec().
int* mesh_get_x_mirror_faces (struct Object * ob, struct BMEditMesh * em)
Definition at line 1088 of file meshtools.c.
References BLI_ghash_free(), BLI_ghash_insert(), BLI_ghash_lookup(), BLI_ghash_new(), Object::data, if(), MEM_callocN(), MEM_freeN(), mesh_get_x_mirror_vert(), mesh_octree_table(), Mesh::mface, mirror_facecmp(), mirror_facehash(), mirror_facerotation(), Mesh::mvert, NULL, SWAP, Mesh::totface, Mesh::totvert, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by PE_mirror_x().
int mesh_get_x_mirror_vert (struct Object * ob, int index)
Definition at line 912 of file meshtools.c.
References Object::data, ME_EDIT_MIRROR_TOPO, mesh_get_x_mirror_vert_spacial(), and mesh_get_x_mirror_vert_topo().
Referenced by do_weight_paint_vertex(), ED_vgroup_mirror(), envelope_bone_weighting(), heat_bone_weighting(), mesh_get_x_mirror_faces(), object_shape_key_mirror(), and wpaint_fill().
int mesh_mirrtopo_table (struct Object * ob, char mode)
Definition at line 874 of file meshtools.c.
References Object::data, ED_mesh_mirrtopo_free(), ED_mesh_mirrtopo_init(), ED_mesh_mirrtopo_recalc_check(), FALSE, mesh_mirrtopo_table(), and Object::mode.
Referenced by ED_editors_exit(), ED_object_exit_editmode(), EDBM_mesh_free(), editbmesh_get_x_mirror_vert_topo(), mesh_get_x_mirror_vert_topo(), mesh_mirrtopo_table(), and set_wpaint().
intptr_t mesh_octree_table (struct Object * ob, struct BMEditMesh * em, float * co, char mode)
Definition at line 776 of file meshtools.c.
References BMEditMesh::bm, BM_ITER_MESH, BM_VERTS_OF_MESH, MVert::co, BMVert::co, copy_v3_v3(), Object::data, DO_MINMAX, Mesh::edit_btmesh, INIT_MINMAX, max, MEM_callocN(), MEM_freeN(), mesh_octree_add_nodes(), mesh_octree_find_index(), mesh_octree_free_node(), mesh_octree_get_base_offs(), mesh_octree_table(), MeshOctree, min, MOC_RES, MOC_THRESH, mul_v3_fl(), Mesh::mvert, NULL, and sub_v3_v3v3().
Referenced by add_verts_to_dgroups(), ED_editors_exit(), ED_object_exit_editmode(), EDBM_mesh_free(), editbmesh_get_x_mirror_vert_spacial(), mesh_get_x_mirror_faces(), mesh_get_x_mirror_vert_spacial(), mesh_octree_table(), object_shape_key_mirror(), set_wpaint(), and special_aftertrans_update().
int mouse_mesh (struct bContext * C, const int mval[2], short extend)
Definition at line 1458 of file editmesh_select.c.
References Object::actcol, BMEditMesh::bm, BM_active_face_set(), BM_edge_select_set(), BM_elem_flag_test, BM_ELEM_SELECT, BM_face_select_set(), BM_select_history_remove, BM_select_history_store, BM_vert_select_set(), EDBM_flag_disable_all(), EDBM_selectmode_flush(), ViewContext::em, em_setup_viewcontext(), FALSE, BMFace::mat_nr, BMEditMesh::mat_nr, ViewContext::mval, NC_GEOM, NC_MATERIAL, ND_SELECT, ND_SHADING, NULL, ViewContext::obedit, TRUE, unified_findnearest(), and WM_event_add_notifier().
Referenced by view3d_select_invoke().
void paintface_deselect_all_visible (struct Object * ob, int action, short flush_flags)
Definition at line 344 of file editface.c.
References MPoly::flag, get_mesh(), ME_FACE_SEL, ME_HIDE, Mesh::mpoly, NULL, paintface_flush_flags(), SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, and Mesh::totpoly.
Referenced by do_lasso_select_paintface(), do_paintface_box_select(), face_select_all_exec(), and face_select_inverse_exec().
void paintface_flush_flags (struct Object * ob)
Definition at line 68 of file editface.c.
References CD_ORIGINDEX, CD_POLYINDEX, CustomData_get_layer(), Object::derivedFinal, DerivedMesh::faceData, Mesh::fdata, MFace::flag, MPoly::flag, get_mesh(), DerivedMesh::getNumPolys, DerivedMesh::getNumTessFaces, DerivedMesh::getPolyArray, DerivedMesh::getTessFaceArray, i, Mesh::mface, Mesh::mpoly, NULL, DerivedMesh::polyData, and Mesh::totface.
Referenced by do_lasso_select_paintface(), do_paintface_box_select(), paintface_deselect_all_visible(), paintface_hide(), paintface_mouse_select(), paintface_reveal(), and paintface_select_linked().
void paintface_hide (struct Object * ob, const int unselected)
Definition at line 163 of file editface.c.
References MPoly::flag, get_mesh(), ME_FACE_SEL, ME_HIDE, Mesh::mpoly, NULL, paintface_flush_flags(), and Mesh::totpoly.
Referenced by face_select_hide_exec().
int paintface_minmax (struct Object * ob, float * min, float * max)
Definition at line 403 of file editface.c.
References add_v3_v3v3(), MVert::co, copy_m3_m4(), copy_v3_v3(), DO_MINMAX, MPoly::flag, get_mesh(), ME_FACE_SEL, ME_HIDE, Mesh::mloop, Mesh::mpoly, Mesh::mtpoly, mul_m3_v3(), Mesh::mvert, Object::obmat, MPoly::totloop, Mesh::totpoly, and MLoop::v.
Referenced by viewselected_exec().
int paintface_mouse_select (struct bContext * C, struct Object * ob, const int mval[2], int extend)
Definition at line 512 of file editface.c.
References Mesh::act_face, CTX_wm_region(), Object::data, ED_region_tag_redraw(), facesel_face_pick(), MPoly::flag, get_mesh(), ME_FACE_SEL, ME_HIDE, Mesh::mpoly, NC_GEOM, ND_SELECT, paintface_flush_flags(), Mesh::totpoly, and WM_event_add_notifier().
Referenced by view3d_select_invoke().
void paintface_reveal (struct Object * ob)
Definition at line 192 of file editface.c.
References MPoly::flag, get_mesh(), ME_FACE_SEL, ME_HIDE, Mesh::mpoly, NULL, paintface_flush_flags(), and Mesh::totpoly.
Referenced by face_select_reveal_exec().
void paintface_select_linked (struct bContext * C, struct Object * ob, int mval[2], int mode)
Referenced by paint_select_linked_exec(), and paint_select_linked_pick_invoke().
void paintvert_deselect_all_visible (struct Object * ob, int action, short flush_flags)
Definition at line 665 of file editface.c.
References MVert::flag, get_mesh(), ME_HIDE, Mesh::mvert, NULL, paintvert_flush_flags(), SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, SELECT, and Mesh::totvert.
Referenced by do_lasso_select_paintvert(), do_paintvert_box_select(), mouse_weight_paint_vertex_select(), vert_select_all_exec(), and vert_select_inverse_exec().
void paintvert_flush_flags (struct Object * ob)
Definition at line 630 of file editface.c.
References CD_ORIGINDEX, Object::derivedFinal, MVert::flag, get_mesh(), DerivedMesh::getNumVerts, DerivedMesh::getVertArray, DerivedMesh::getVertDataArray, i, Mesh::mvert, NULL, and ORIGINDEX_NONE.
Referenced by do_lasso_select_paintvert(), do_paintvert_box_select(), mouse_weight_paint_vertex_select(), paint_vertsel_circle_select(), paintvert_deselect_all_visible(), and vgroup_select_verts().
void undo_push_mesh (struct bContext * C, const char * name)
Definition at line 557 of file editmesh_utils.c.
References BMEdit_FromObject(), CTX_data_edit_object(), editbtMesh_to_undoMesh(), free_undo(), getEditMesh(), NULL, BMEditMesh::ob, undo_editmode_push(), and undoMesh_to_editbtMesh().
Referenced by ED_undo_push().
Variable Documentation
unsigned int bm_solidoffs
Definition at line 180 of file ED_mesh.h.
Referenced by do_lasso_select_mesh__doSelectEdge(), do_mesh_box_select__doSelectEdge(), draw_object_backbufsel(), and edbm_backbuf_check_and_select_edges().
unsigned int bm_vertoffs
Definition at line 180 of file ED_mesh.h.
Referenced by do_lasso_select_paintface(), do_lasso_select_paintvert(), draw_object_backbufsel(), EDBM_backbuf_border_init(), EDBM_backbuf_border_mask_init(), EDBM_backbuf_check(), EDBM_backbuf_circle_init(), paint_facesel_circle_select(), and paint_vertsel_circle_select().
unsigned int bm_wireoffs
Definition at line 180 of file ED_mesh.h.
Referenced by draw_object_backbufsel(), edbm_backbuf_check_and_select_verts(), EDBM_edge_find_nearest(), and EDBM_vert_find_nearest().