Blender: BKE_ocean.h File Reference
BKE_ocean.h File Reference
Classes
struct OceanResult
struct OceanCache
Defines
#define OCEAN_NOT_CACHED 0
#define OCEAN_CACHING 1
#define OCEAN_CACHED 2
Typedefs
typedef struct OceanResult OceanResult
typedef struct OceanCache OceanCache
Functions
struct Ocean * BKE_add_ocean (void)
void BKE_free_ocean_data (struct Ocean *oc)
void BKE_free_ocean (struct Ocean *oc)
void BKE_init_ocean (struct Ocean *o, int M, int N, float Lx, float Lz, float V, float l, float A, float w, float damp, float alignment, float depth, float time, short do_height_field, short do_chop, short do_normals, short do_jacobian, int seed)
void BKE_simulate_ocean (struct Ocean *o, float t, float scale, float chop_amount)
float BKE_ocean_jminus_to_foam (float jminus, float coverage)
void BKE_ocean_eval_uv (struct Ocean *oc, struct OceanResult *ocr, float u, float v)
void BKE_ocean_eval_uv_catrom (struct Ocean *oc, struct OceanResult *ocr, float u, float v)
void BKE_ocean_eval_xz (struct Ocean *oc, struct OceanResult *ocr, float x, float z)
void BKE_ocean_eval_xz_catrom (struct Ocean *oc, struct OceanResult *ocr, float x, float z)
void BKE_ocean_eval_ij (struct Ocean *oc, struct OceanResult *ocr, int i, int j)
struct OceanCache * BKE_init_ocean_cache (const char *bakepath, const char *relbase, int start, int end, float wave_scale, float chop_amount, float foam_coverage, float foam_fade, int resolution)
void BKE_simulate_ocean_cache (struct OceanCache *och, int frame)
void BKE_bake_ocean (struct Ocean *o, struct OceanCache *och, void(*update_cb)(void *, float progress, int *cancel), void *update_cb_data)
void BKE_ocean_cache_eval_uv (struct OceanCache *och, struct OceanResult *ocr, int f, float u, float v)
void BKE_ocean_cache_eval_ij (struct OceanCache *och, struct OceanResult *ocr, int f, int i, int j)
void BKE_free_ocean_cache (struct OceanCache *och)
Define Documentation
#define OCEAN_CACHED 2
Definition at line 75 of file BKE_ocean.h.
#define OCEAN_CACHING 1
Definition at line 74 of file BKE_ocean.h.
#define OCEAN_NOT_CACHED 0
Definition at line 73 of file BKE_ocean.h.
Typedef Documentation
typedef struct OceanCache OceanCache
typedef struct OceanResult OceanResult
Function Documentation
struct Ocean* BKE_add_ocean (void) [read]
Definition at line 1375 of file ocean.c.
References MEM_callocN().
Referenced by copyData(), initData(), and ocean_bake_exec().
void BKE_bake_ocean (struct Ocean * o, struct OceanCache * och, void(*)(void *, float progress, int *cancel) update_cb, void * update_cb_data)
Referenced by ocean_bake_exec(), and oceanbake_startjob().
void BKE_free_ocean (struct Ocean * oc)
Definition at line 1391 of file ocean.c.
References MEM_freeN().
Referenced by freeData(), and oceanbake_endjob().
void BKE_free_ocean_cache (struct OceanCache * och)
Definition at line 1401 of file ocean.c.
References MEM_freeN().
Referenced by freeData().
void BKE_free_ocean_data (struct Ocean * oc)
void BKE_init_ocean (struct Ocean * o, int M, int N, float Lx, float Lz, float V, float l, float A, float w, float damp, float alignment, float depth, float time, short do_height_field, short do_chop, short do_normals, short do_jacobian, int seed)
Referenced by init_ocean_modifier_bake().
struct OceanCache* BKE_init_ocean_cache (const char * bakepath, const char * relbase, int start, int end, float wave_scale, float chop_amount, float foam_coverage, float foam_fade, int resolution) [read]
Referenced by ocean_bake_exec().
void BKE_ocean_cache_eval_ij (struct OceanCache * och, struct OceanResult * ocr, int f, int i, int j)
void BKE_ocean_cache_eval_uv (struct OceanCache * och, struct OceanResult * ocr, int f, float u, float v)
Referenced by ocean_texture().
void BKE_ocean_eval_ij (struct Ocean * oc, struct OceanResult * ocr, int i, int j)
void BKE_ocean_eval_uv (struct Ocean * oc, struct OceanResult * ocr, float u, float v)
Referenced by ocean_texture().
void BKE_ocean_eval_uv_catrom (struct Ocean * oc, struct OceanResult * ocr, float u, float v)
Referenced by ocean_texture().
void BKE_ocean_eval_xz (struct Ocean * oc, struct OceanResult * ocr, float x, float z)
void BKE_ocean_eval_xz_catrom (struct Ocean * oc, struct OceanResult * ocr, float x, float z)
float BKE_ocean_jminus_to_foam (float jminus, float coverage)
Referenced by ocean_texture().
void BKE_simulate_ocean (struct Ocean * o, float t, float scale, float chop_amount)
void BKE_simulate_ocean_cache (struct OceanCache * och, int frame)