Blender: AUD_ReferenceHandler Class Reference
AUD_ReferenceHandler Class Reference
#include <AUD_Reference.h>
Static Public Member Functions
static void incref (void *reference)
static bool decref (void *reference)
Detailed Description
This class handles the reference counting.
Definition at line 45 of file AUD_Reference.h.
Member Function Documentation
static bool AUD_ReferenceHandler::decref (void * reference) [inline, static]
Reference decrement.
Parameters:
reference The reference.
Returns:
Whether the reference has to be deleted.
Definition at line 79 of file AUD_Reference.h.
Referenced by AUD_Reference< AUD_PitchReader >::operator=(), and AUD_Reference< AUD_PitchReader >::~AUD_Reference().
static void AUD_ReferenceHandler::incref (void * reference) [inline, static]
Reference increment.
Parameters:
reference The reference.
Definition at line 58 of file AUD_Reference.h.
Referenced by AUD_Reference< AUD_PitchReader >::AUD_Reference(), and AUD_Reference< AUD_PitchReader >::operator=().
The documentation for this class was generated from the following files:
AUD_Reference.h
AUD_ReferenceHandler.cpp