Blender: BlenderBulletMotionState Class Reference
BlenderBulletMotionState Class Reference
Public Member Functions
BlenderBulletMotionState (PHY_IMotionState *bms)
void getWorldTransform (btTransform &worldTrans) const
void setWorldTransform (const btTransform &worldTrans)
Detailed Description
Definition at line 121 of file CcdPhysicsController.cpp.
Constructor & Destructor Documentation
BlenderBulletMotionState::BlenderBulletMotionState (PHY_IMotionState * bms) [inline]
Definition at line 127 of file CcdPhysicsController.cpp.
Member Function Documentation
void BlenderBulletMotionState::getWorldTransform (btTransform & worldTrans) const [inline, virtual]
Implements btMotionState.
Definition at line 133 of file CcdPhysicsController.cpp.
References btTransform::getBasis(), PHY_IMotionState::getWorldOrientation(), PHY_IMotionState::getWorldPosition(), btMatrix3x3::setFromOpenGLSubMatrix(), and btTransform::setOrigin().
void BlenderBulletMotionState::setWorldTransform (const btTransform & worldTrans) [inline, virtual]
Implements btMotionState.
Definition at line 144 of file CcdPhysicsController.cpp.
References PHY_IMotionState::calculateWorldTransformations(), btTransform::getOrigin(), btTransform::getRotation(), PHY_IMotionState::setWorldOrientation(), and PHY_IMotionState::setWorldPosition().
The documentation for this class was generated from the following file:
CcdPhysicsController.cpp