Blender: BlenderSync Class Reference
BlenderSync Class Reference
#include <blender_sync.h>
Classes
struct RenderLayerInfo
Public Member Functions
BlenderSync (BL::BlendData b_data, BL::Scene b_scene, Scene *scene_, bool preview_)
~BlenderSync ()
bool sync_recalc ()
void sync_data (BL::SpaceView3D b_v3d, const char *layer=0)
void sync_camera (BL::Object b_override, int width, int height)
void sync_view (BL::SpaceView3D b_v3d, BL::RegionView3D b_rv3d, int width, int height)
Static Public Member Functions
static SceneParams get_scene_params (BL::Scene b_scene, bool background)
static SessionParams get_session_params (BL::UserPreferences b_userpref, BL::Scene b_scene, bool background)
static bool get_session_pause (BL::Scene b_scene, bool background)
static BufferParams get_buffer_params (BL::Scene b_scene, BL::RegionView3D b_rv3d, int width, int height)
Detailed Description
Definition at line 50 of file blender_sync.h.
Constructor & Destructor Documentation
CCL_NAMESPACE_BEGIN BlenderSync::BlenderSync (BL::BlendData b_data, BL::Scene b_scene, Scene * scene_, bool preview_)
Definition at line 43 of file blender_sync.cpp.
BlenderSync::~BlenderSync ()
Definition at line 57 of file blender_sync.cpp.
Member Function Documentation
BufferParams BlenderSync::get_buffer_params (BL::Scene b_scene, BL::RegionView3D b_rv3d, int width, int height) [static]
Definition at line 327 of file blender_camera.cpp.
References BufferParams::full_height, BufferParams::full_width, BufferParams::full_x, BufferParams::full_y, BufferParams::height, and BufferParams::width.
Referenced by BlenderSession::create_session(), BlenderSession::draw(), BlenderSession::render(), and BlenderSession::synchronize().
SceneParams BlenderSync::get_scene_params (BL::Scene b_scene, bool background) [static]
Definition at line 237 of file blender_sync.cpp.
References background(), SceneParams::BVH_STATIC, SceneParams::bvh_type, SceneParams::OSL, RNA_boolean_get(), RNA_enum_get(), RNA_pointer_get(), SceneParams::shadingsystem, SceneParams::SVM, SceneParams::use_bvh_cache, and SceneParams::use_bvh_spatial_split.
Referenced by BlenderSession::create_session(), and BlenderSession::synchronize().
SessionParams BlenderSync::get_session_params (BL::UserPreferences b_userpref, BL::Scene b_scene, bool background) [static]
Definition at line 267 of file blender_sync.cpp.
References Device::available_devices(), background(), SessionParams::background, SessionParams::cancel_timeout, SessionParams::device, DEVICE_MULTI, SessionParams::experimental, get_float(), get_int(), DeviceInfo::id, SessionParams::min_size, NULL, SessionParams::progressive, SessionParams::reset_timeout, RNA_enum_get(), RNA_pointer_get(), RNA_property_enum_identifier(), RNA_struct_find_property(), SessionParams::samples, SessionParams::text_timeout, SessionParams::threads, SessionParams::tile_size, and DeviceInfo::type.
Referenced by BlenderSession::create_session(), BlenderSession::draw(), BlenderSession::render(), and BlenderSession::synchronize().
bool BlenderSync::get_session_pause (BL::Scene b_scene, bool background) [static]
Definition at line 261 of file blender_sync.cpp.
References get_boolean(), and RNA_pointer_get().
Referenced by BlenderSession::create_session(), and BlenderSession::synchronize().
void BlenderSync::sync_camera (BL::Object b_override, int width, int height)
Definition at line 253 of file blender_camera.cpp.
References blender_camera_from_object(), blender_camera_init(), blender_camera_sync(), Scene::camera, get_transform(), BlenderCamera::matrix, BlenderCamera::pixelaspect, float2::x, and float2::y.
Referenced by BlenderSession::create_session(), and BlenderSession::synchronize().
void BlenderSync::sync_data (BL::SpaceView3D b_v3d, const char * layer = 0)
Definition at line 124 of file blender_sync.cpp.
Referenced by BlenderSession::create_session(), BlenderSession::render(), and BlenderSession::synchronize().
bool BlenderSync::sync_recalc ()
Definition at line 63 of file blender_sync.cpp.
References id_map< K, T >::has_recalc(), and id_map< K, T >::set_recalc().
Referenced by BlenderSession::synchronize().
void BlenderSync::sync_view (BL::SpaceView3D b_v3d, BL::RegionView3D b_rv3d, int width, int height)
Definition at line 282 of file blender_camera.cpp.
References blender_camera_from_object(), blender_camera_init(), blender_camera_sync(), Scene::camera, CAMERA_ORTHOGRAPHIC, BlenderCamera::farclip, get_float2(), get_transform(), BlenderCamera::lens, BlenderCamera::matrix, BlenderCamera::nearclip, BlenderCamera::offset, BlenderCamera::ortho_scale, sync_view(), transform_inverse(), BlenderCamera::type, and BlenderCamera::zoom.
Referenced by BlenderSession::create_session(), BlenderSession::draw(), sync_view(), and BlenderSession::synchronize().
The documentation for this class was generated from the following files:
blender_sync.h
blender_camera.cpp
blender_mesh.cpp
blender_object.cpp
blender_shader.cpp
blender_sync.cpp