Blender: BlockDXT3 Struct Reference
BlockDXT3 Struct Reference
DXT3 block.
#include <BlockDXT.h>
Public Member Functions
void decodeBlock (ColorBlock *block) const
void decodeBlockNV5x (ColorBlock *block) const
void flip4 ()
Flip DXT3 block vertically.
void flip2 ()
Flip half DXT3 block vertically.
Public Attributes
AlphaBlockDXT3 alpha
BlockDXT1 color
Detailed Description
DXT3 block.
Definition at line 133 of file BlockDXT.h.
Member Function Documentation
void BlockDXT3::decodeBlock (ColorBlock * block) const
Definition at line 280 of file BlockDXT.cpp.
References alpha, color, AlphaBlockDXT3::decodeBlock(), and BlockDXT1::decodeBlock().
void BlockDXT3::decodeBlockNV5x (ColorBlock * block) const
Definition at line 289 of file BlockDXT.cpp.
References alpha, color, AlphaBlockDXT3::decodeBlock(), and BlockDXT1::decodeBlockNV5x().
void BlockDXT3::flip2 ()
Flip half DXT3 block vertically.
Definition at line 336 of file BlockDXT.cpp.
References alpha, color, AlphaBlockDXT3::flip2(), and BlockDXT1::flip2().
void BlockDXT3::flip4 ()
Flip DXT3 block vertically.
Definition at line 329 of file BlockDXT.cpp.
References alpha, color, AlphaBlockDXT3::flip4(), and BlockDXT1::flip4().
Member Data Documentation
AlphaBlockDXT3 BlockDXT3::alpha
Definition at line 135 of file BlockDXT.h.
Referenced by decodeBlock(), decodeBlockNV5x(), flip2(), flip4(), and mem_read().
BlockDXT1 BlockDXT3::color
Definition at line 136 of file BlockDXT.h.
Referenced by decodeBlock(), decodeBlockNV5x(), flip2(), flip4(), and mem_read().
The documentation for this struct was generated from the following files:
BlockDXT.h
BlockDXT.cpp