Blender: BKE_writeavi.h File Reference
BKE_writeavi.h File Reference
blenkernel
Classes
struct bMovieHandle
Typedefs
typedef struct bMovieHandle bMovieHandle
Functions
bMovieHandle * BKE_get_movie_handle (const char imtype)
void BKE_makeanimstring (char *string, struct RenderData *rd)
Detailed Description
Definition in file BKE_writeavi.h.
Typedef Documentation
typedef struct bMovieHandle bMovieHandle
Function Documentation
bMovieHandle* BKE_get_movie_handle (const char imtype)
Definition at line 71 of file writeavi.c.
References append_avi(), append_frameserver(), bMovieHandle::append_movie, ELEM4, end_avi(), end_frameserver(), bMovieHandle::end_movie, filepath_avi(), frameserver_loop(), bMovieHandle::get_movie_path, bMovieHandle::get_next_frame, NULL, R_IMF_IMTYPE_AVICODEC, R_IMF_IMTYPE_FFMPEG, R_IMF_IMTYPE_FRAMESERVER, R_IMF_IMTYPE_H264, R_IMF_IMTYPE_QUICKTIME, R_IMF_IMTYPE_THEORA, R_IMF_IMTYPE_XVID, start_avi(), start_frameserver(), and bMovieHandle::start_movie.
Referenced by BKE_makeanimstring(), RE_BlenderAnim(), screen_opengl_render_anim_initialize(), and screenshot_startjob().
void BKE_makeanimstring (char * string, struct RenderData * rd)
Definition at line 231 of file writeavi.c.
References BKE_get_movie_handle(), bMovieHandle::get_movie_path, RenderData::im_format, and ImageFormatData::imtype.