Blender: ImFileType Struct Reference
ImFileType Struct Reference
#include <IMB_filetype.h>
Public Attributes
void(* init)(void)
void(* exit)(void)
int(* is_a)(unsigned char *buf)
int(* ftype)(struct ImFileType *type, struct ImBuf *ibuf)
struct ImBuf *(* load)(unsigned char *mem, size_t size, int flags)
int(* save)(struct ImBuf *ibuf, const char *name, int flags)
void(* load_tile)(struct ImBuf *ibuf, unsigned char *mem, size_t size, int tx, int ty, unsigned int *rect)
int flag
int filetype
Detailed Description
Definition at line 37 of file IMB_filetype.h.
Member Data Documentation
void(* ImFileType::exit)(void)
Definition at line 39 of file IMB_filetype.h.
Referenced by imb_filetypes_exit().
int ImFileType::filetype
Definition at line 48 of file IMB_filetype.h.
Referenced by imb_ftype_default(), and IMB_ispic_name().
int ImFileType::flag
Definition at line 47 of file IMB_filetype.h.
Referenced by IMB_saveiff().
int(* ImFileType::ftype)(struct ImFileType *type, struct ImBuf *ibuf)
Definition at line 42 of file IMB_filetype.h.
Referenced by imb_loadtilefile(), and IMB_saveiff().
void(* ImFileType::init)(void)
Definition at line 38 of file IMB_filetype.h.
Referenced by imb_filetypes_init().
int(* ImFileType::is_a)(unsigned char *buf)
Definition at line 41 of file IMB_filetype.h.
Referenced by imb_filetypes_exit(), imb_filetypes_init(), IMB_ibImageFromMemory(), IMB_ispic_name(), imb_loadtilefile(), and IMB_saveiff().
struct ImBuf*(* ImFileType::load)(unsigned char *mem, size_t size, int flags) [read]
Definition at line 43 of file IMB_filetype.h.
Referenced by IMB_ibImageFromMemory().
void(* ImFileType::load_tile)(struct ImBuf *ibuf, unsigned char *mem, size_t size, int tx, int ty, unsigned int *rect)
Definition at line 45 of file IMB_filetype.h.
Referenced by imb_loadtilefile().
int(* ImFileType::save)(struct ImBuf *ibuf, const char *name, int flags)
Definition at line 44 of file IMB_filetype.h.
Referenced by IMB_saveiff().
The documentation for this struct was generated from the following file:
IMB_filetype.h