Blender: BLO_writefile.h File Reference
BLO_writefile.h File Reference
.blend read and write functions
external writefile function prototypes.
Defines
#define BLEN_THUMB_SIZE 128
Functions
int BLO_write_file (struct Main *mainvar, const char *filepath, int write_flags, struct ReportList *reports, const int *thumb)
int BLO_write_file_mem (struct Main *mainvar, struct MemFile *compare, struct MemFile *current, int write_flags)
Detailed Description
external writefile function prototypes.
Definition in file BLO_writefile.h.
Define Documentation
#define BLEN_THUMB_SIZE 128
Definition at line 43 of file BLO_writefile.h.
Referenced by blend_file_thumb().
Function Documentation
int BLO_write_file (struct Main * mainvar, const char * filepath, int write_flags, struct ReportList * reports, const int * thumb)
Definition at line 2889 of file writefile.c.
References BKE_report(), BKE_reportf(), BLENDER_STARTUP_FILE, BLENDER_USER_CONFIG, BLI_cleanup_dir(), BLI_delete(), BLI_file_gzip(), BLI_get_folder_create(), BLI_make_file_string(), BLI_open(), BLI_path_cmp, BLI_rename(), BLI_snprintf(), BLI_split_dir_part(), do_history(), err, FILE_MAX, G, G_FILE_COMPRESS, G_FILE_HISTORY, G_FILE_RELATIVE_REMAP, makeFilesAbsolute(), makeFilesRelative(), Main::name, NULL, O_BINARY, RPT_ERROR, and write_file_handle().
Referenced by BKE_write_undo(), wm_autosave_timer(), WM_write_file(), WM_write_homefile(), and write_crash_blend().
int BLO_write_file_mem (struct Main * mainvar, struct MemFile * compare, struct MemFile * current, int write_flags)
Definition at line 2992 of file writefile.c.
References err, NULL, and write_file_handle().
Referenced by BKE_write_undo().