Blender: node_composite_rotate.c File Reference
node_composite_rotate.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void node_composit_exec_rotate (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_rotate (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_rotate (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_rotate_in []
static bNodeSocketTemplate cmp_node_rotate_out []
Detailed Description
Definition in file node_composite_rotate.c.
Function Documentation
static void node_composit_exec_rotate (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 48 of file node_composite_rotate.c.
References alloc_compbuf(), bicubic_interpolation(), bilinear_interpolation(), CB_RGBA, cos(), bNode::custom1, bNodeStack::data, data, free_compbuf(), IMB_allocImBuf(), IMB_freeImBuf(), neareast_interpolation(), CompBuf::rect, ImBuf::rect_float, sin(), typecheck_compbuf(), bNodeStack::vec, CompBuf::x, CompBuf::xof, CompBuf::y, and CompBuf::yof.
Referenced by register_node_type_cmp_rotate().
static void node_composit_init_rotate (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 124 of file node_composite_rotate.c.
References bNode::custom1.
Referenced by register_node_type_cmp_rotate().
void register_node_type_cmp_rotate (bNodeTreeType * ttype)
Definition at line 129 of file node_composite_rotate.c.
References CMP_NODE_ROTATE, NODE_CLASS_DISTORT, node_composit_exec_rotate(), node_composit_init_rotate(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_rotate_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   SOCK_FLOAT, 1, "Degr",          0.0f, 0.0f, 0.0f, 0.0f, -10000.0f, 10000.0f, PROP_ANGLE},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_composite_rotate.c.
bNodeSocketTemplate cmp_node_rotate_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 42 of file node_composite_rotate.c.