Blender: ImageRender.cpp File Reference
ImageRender.cpp File Reference
BGE Video Texture
#include <PyObjectPlus.h>
#include <structmember.h>
#include <float.h>
#include <math.h>
#include "GL/glew.h"
#include "KX_PythonInit.h"
#include "DNA_scene_types.h"
#include "RAS_CameraData.h"
#include "RAS_MeshObject.h"
#include "BLI_math.h"
#include "ImageRender.h"
#include "ImageBase.h"
#include "BlendType.h"
#include "Exception.h"
#include "Texture.h"
Functions
ImageRender * getImageRender (PyImage *self)
static int ImageRender_init (PyObject *pySelf, PyObject *args, PyObject *kwds)
PyObject * getBackground (PyImage *self, void *closure)
static int setBackground (PyImage *self, PyObject *value, void *closure)
static int ImageMirror_init (PyObject *pySelf, PyObject *args, PyObject *kwds)
PyObject * getClip (PyImage *self, void *closure)
static int setClip (PyImage *self, PyObject *value, void *closure)
Variables
ExceptionID SceneInvalid
ExceptionID CameraInvalid
ExceptionID ObserverInvalid
ExceptionID MirrorInvalid
ExceptionID MirrorSizeInvalid
ExceptionID MirrorNormalInvalid
ExceptionID MirrorHorizontal
ExceptionID MirrorTooSmall
ExpDesc SceneInvalidDesc (SceneInvalid,"Scene object is invalid")
ExpDesc CameraInvalidDesc (CameraInvalid,"Camera object is invalid")
ExpDesc ObserverInvalidDesc (ObserverInvalid,"Observer object is invalid")
ExpDesc MirrorInvalidDesc (MirrorInvalid,"Mirror object is invalid")
ExpDesc MirrorSizeInvalidDesc (MirrorSizeInvalid,"Mirror has no vertex or no size")
ExpDesc MirrorNormalInvalidDesc (MirrorNormalInvalid,"Cannot determine mirror plane")
ExpDesc MirrorHorizontalDesc (MirrorHorizontal,"Mirror is horizontal in local space")
ExpDesc MirrorTooSmallDesc (MirrorTooSmall,"Mirror is too small")
BlendType< KX_Scene > sceneType ("KX_Scene")
BlendType< KX_Camera > cameraType ("KX_Camera")
static PyMethodDef imageRenderMethods []
static PyGetSetDef imageRenderGetSets []
PyTypeObject ImageRenderType
static PyGetSetDef imageMirrorGetSets []
PyTypeObject ImageMirrorType
Detailed Description
Definition in file ImageRender.cpp.
Function Documentation
PyObject* getBackground (PyImage * self, void * closure)
Definition at line 336 of file ImageRender.cpp.
References getImageRender().
PyObject* getClip (PyImage * self, void * closure)
Definition at line 513 of file ImageRender.cpp.
References getImageRender().
ImageRender* getImageRender (PyImage * self) [inline]
Definition at line 280 of file ImageRender.cpp.
Referenced by getBackground(), getClip(), setBackground(), and setClip().
static int ImageMirror_init (PyObject * pySelf, PyObject * args, PyObject * kwds) [static]
Definition at line 437 of file ImageRender.cpp.
References KDL::exp(), getMaterial(), PyImage::m_image, ImageBase::m_image, MaterialNotAvail, NULL, Exception::report(), S_OK, and THRWEXCP.
static int ImageRender_init (PyObject * pySelf, PyObject * args, PyObject * kwds) [static]
Definition at line 293 of file ImageRender.cpp.
References cameraType, KDL::exp(), PyImage::m_image, ImageBase::m_image, NULL, Exception::report(), S_OK, sceneType, and THRWEXCP.
static int setBackground (PyImage * self, PyObject * value, void * closure) [static]
Definition at line 346 of file ImageRender.cpp.
References getImageRender(), NULL, and ImageRender::setBackground().
static int setClip (PyImage * self, PyObject * value, void * closure) [static]
Definition at line 519 of file ImageRender.cpp.
References getImageRender(), and ImageRender::setClip().
Variable Documentation
ExceptionID CameraInvalid
Definition at line 49 of file ImageRender.cpp.
ExpDesc CameraInvalidDesc(CameraInvalid,"Camera object is invalid")
Referenced by registerAllExceptions().
BlendType<KX_Camera> cameraType("KX_Camera")
Referenced by ImageRender_init().
PyGetSetDef imageMirrorGetSets[] [static]
Initial value:
{
    {(char*)"clip", (getter)getClip, (setter)setClip, (char*)"clipping distance", NULL},
    {(char*)"background", (getter)getBackground, (setter)setBackground, (char*)"background color", NULL},
    {(char*)"capsize", (getter)ImageViewport_getCaptureSize, (setter)ImageViewport_setCaptureSize, (char*)"size of render area", NULL},
    {(char*)"alpha", (getter)ImageViewport_getAlpha, (setter)ImageViewport_setAlpha, (char*)"use alpha in texture", NULL},
    {(char*)"whole", (getter)ImageViewport_getWhole, (setter)ImageViewport_setWhole, (char*)"use whole viewport to render", NULL},
    {(char*)"valid", (getter)Image_valid, NULL, (char*)"bool to tell if an image is available", NULL},
    {(char*)"image", (getter)Image_getImage, NULL, (char*)"image data", NULL},
    {(char*)"size", (getter)Image_getSize, NULL, (char*)"image size", NULL},
    {(char*)"scale", (getter)Image_getScale, (setter)Image_setScale, (char*)"fast scale of image (near neighbor)",  NULL},
    {(char*)"flip", (getter)Image_getFlip, (setter)Image_setFlip, (char*)"flip image vertically", NULL},
    {(char*)"filter", (getter)Image_getFilter, (setter)Image_setFilter, (char*)"pixel filter", NULL},
    {NULL}
}
Definition at line 535 of file ImageRender.cpp.
PyTypeObject ImageMirrorType
Definition at line 728 of file ImageRender.cpp.
Referenced by registerAllTypes().
PyGetSetDef imageRenderGetSets[] [static]
Initial value:
{
    {(char*)"background", (getter)getBackground, (setter)setBackground, (char*)"background color", NULL},
    {(char*)"capsize", (getter)ImageViewport_getCaptureSize, (setter)ImageViewport_setCaptureSize, (char*)"size of render area", NULL},
    {(char*)"alpha", (getter)ImageViewport_getAlpha, (setter)ImageViewport_setAlpha, (char*)"use alpha in texture", NULL},
    {(char*)"whole", (getter)ImageViewport_getWhole, (setter)ImageViewport_setWhole, (char*)"use whole viewport to render", NULL},
    {(char*)"valid", (getter)Image_valid, NULL, (char*)"bool to tell if an image is available", NULL},
    {(char*)"image", (getter)Image_getImage, NULL, (char*)"image data", NULL},
    {(char*)"size", (getter)Image_getSize, NULL, (char*)"image size", NULL},
    {(char*)"scale", (getter)Image_getScale, (setter)Image_setScale, (char*)"fast scale of image (near neighbor)",  NULL},
    {(char*)"flip", (getter)Image_getFlip, (setter)Image_setFlip, (char*)"flip image vertically", NULL},
    {(char*)"filter", (getter)Image_getFilter, (setter)Image_setFilter, (char*)"pixel filter", NULL},
    {NULL}
}
Definition at line 375 of file ImageRender.cpp.
PyMethodDef imageRenderMethods[] [static]
Initial value:
{
    {"refresh", (PyCFunction)Image_refresh, METH_NOARGS, "Refresh image - invalidate its current content"},
    {NULL}
}
Definition at line 369 of file ImageRender.cpp.
PyTypeObject ImageRenderType
Definition at line 394 of file ImageRender.cpp.
Referenced by registerAllTypes().
ExceptionID MirrorHorizontal
Definition at line 50 of file ImageRender.cpp.
ExpDesc MirrorHorizontalDesc(MirrorHorizontal,"Mirror is horizontal in local space")
Referenced by registerAllExceptions().
ExceptionID MirrorInvalid
Definition at line 50 of file ImageRender.cpp.
ExpDesc MirrorInvalidDesc(MirrorInvalid,"Mirror object is invalid")
Referenced by registerAllExceptions().
ExceptionID MirrorNormalInvalid
Definition at line 50 of file ImageRender.cpp.
ExpDesc MirrorNormalInvalidDesc(MirrorNormalInvalid,"Cannot determine mirror plane")
Referenced by registerAllExceptions().
ExceptionID MirrorSizeInvalid
Definition at line 50 of file ImageRender.cpp.
ExpDesc MirrorSizeInvalidDesc(MirrorSizeInvalid,"Mirror has no vertex or no size")
Referenced by registerAllExceptions().
ExceptionID MirrorTooSmall
Definition at line 50 of file ImageRender.cpp.
ExpDesc MirrorTooSmallDesc(MirrorTooSmall,"Mirror is too small")
Referenced by registerAllExceptions().
ExceptionID ObserverInvalid
Definition at line 49 of file ImageRender.cpp.
ExpDesc ObserverInvalidDesc(ObserverInvalid,"Observer object is invalid")
Referenced by registerAllExceptions().
ExceptionID SceneInvalid
Definition at line 49 of file ImageRender.cpp.
ExpDesc SceneInvalidDesc(SceneInvalid,"Scene object is invalid")
Referenced by registerAllExceptions().
BlendType<KX_Scene> sceneType("KX_Scene")
Referenced by ImageRender_init().