Blender: COperator2Expr Class Reference
COperator2Expr Class Reference
#include <Operator2Expr.h>
Public Member Functions
virtual bool MergeExpression (CExpression *otherexpr)
virtual unsigned char GetExpressionID ()
virtual void BroadcastOperators (VALUE_OPERATOR op)
CExpression * CheckLink (std::vector< CBrokenLinkInfo * > &brokenlinks)
bool NeedsRecalculated ()
void ClearModified ()
virtual CValue * Calculate ()
COperator2Expr (VALUE_OPERATOR op, CExpression *lhs, CExpression *rhs)
COperator2Expr ()
virtual ~COperator2Expr ()
Protected Attributes
CExpression * m_rhs
CExpression * m_lhs
CValue * m_cached_calculate
Detailed Description
Definition at line 26 of file Operator2Expr.h.
Constructor & Destructor Documentation
COperator2Expr::COperator2Expr (VALUE_OPERATOR op, CExpression * lhs, CExpression * rhs)
Definition at line 30 of file Operator2Expr.cpp.
COperator2Expr::COperator2Expr ()
Definition at line 44 of file Operator2Expr.cpp.
COperator2Expr::~COperator2Expr () [virtual]
Definition at line 57 of file Operator2Expr.cpp.
References m_cached_calculate, m_lhs, m_rhs, CExpression::Release(), and CValue::Release().
Member Function Documentation
void COperator2Expr::BroadcastOperators (VALUE_OPERATOR op) [virtual]
Implements CExpression.
Definition at line 269 of file Operator2Expr.cpp.
References CExpression::BroadcastOperators(), m_lhs, and m_rhs.
CValue * COperator2Expr::Calculate () [virtual]
Implements CExpression.
Definition at line 71 of file Operator2Expr.cpp.
References CValue::AddRef(), CValue::Calc(), CExpression::Calculate(), m_cached_calculate, m_lhs, m_rhs, CExpression::NeedsRecalculated(), NULL, CValue::Release(), and CValue::SetOwnerExpression().
CExpression * COperator2Expr::CheckLink (std::vector< CBrokenLinkInfo * > & brokenlinks) [virtual]
Implements CExpression.
Definition at line 200 of file Operator2Expr.cpp.
References assert, assertd, m_lhs, m_rhs, and CExpression::Release().
void COperator2Expr::ClearModified () [inline, virtual]
Implements CExpression.
Definition at line 39 of file Operator2Expr.h.
References CExpression::ClearModified(), m_lhs, and m_rhs.
virtual unsigned char COperator2Expr::GetExpressionID () [inline, virtual]
Implements CExpression.
Definition at line 32 of file Operator2Expr.h.
References CExpression::COPERATOR2EXPRESSIONID.
bool COperator2Expr::MergeExpression (CExpression * otherexpr) [virtual]
Implements CExpression.
Definition at line 251 of file Operator2Expr.cpp.
References CExpression::AddRef(), assertd, CExpression::CCONSTEXPRESSIONID, CExpression::GetExpressionID(), m_lhs, and CExpression::Release().
bool COperator2Expr::NeedsRecalculated () [virtual]
Implements CExpression.
Definition at line 181 of file Operator2Expr.cpp.
References assertd, m_lhs, m_rhs, and CExpression::NeedsRecalculated().
Member Data Documentation
CValue* COperator2Expr::m_cached_calculate [protected]
Definition at line 54 of file Operator2Expr.h.
Referenced by Calculate(), and ~COperator2Expr().
CExpression* COperator2Expr::m_lhs [protected]
Definition at line 53 of file Operator2Expr.h.
Referenced by BroadcastOperators(), Calculate(), CheckLink(), ClearModified(), MergeExpression(), NeedsRecalculated(), and ~COperator2Expr().
CExpression* COperator2Expr::m_rhs [protected]
Definition at line 52 of file Operator2Expr.h.
Referenced by BroadcastOperators(), Calculate(), CheckLink(), ClearModified(), NeedsRecalculated(), and ~COperator2Expr().
The documentation for this class was generated from the following files:
Operator2Expr.h
Operator2Expr.cpp