Blender: BLI_scanfill.h File Reference
BLI_scanfill.h File Reference
blenlib
Filling meshes.
Classes
struct ScanFillContext
struct ScanFillVert
struct ScanFillEdge
struct ScanFillFace
Defines
#define MEM_ELEM_BLOCKSIZE 16384
Typedefs
typedef struct ScanFillContext ScanFillContext
typedef struct ScanFillVert ScanFillVert
typedef struct ScanFillEdge ScanFillEdge
typedef struct ScanFillFace ScanFillFace
Functions
struct ScanFillVert * BLI_addfillvert (ScanFillContext *sf_ctx, const float vec[3])
struct ScanFillEdge * BLI_addfilledge (ScanFillContext *sf_ctx, struct ScanFillVert *v1, struct ScanFillVert *v2)
int BLI_begin_edgefill (ScanFillContext *sf_ctx)
int BLI_edgefill (ScanFillContext *sf_ctx, const short do_quad_tri_speedup)
int BLI_edgefill_ex (ScanFillContext *sf_ctx, const short do_quad_tri_speedup, const float nor_proj[3])
void BLI_end_edgefill (ScanFillContext *sf_ctx)
void BLI_setErrorCallBack (void(*f)(const char *))
void BLI_setInterruptCallBack (int(*f)(void))
Detailed Description
Filling meshes.
Since:
March 2001
Author:
nzc
Definition in file BLI_scanfill.h.
Define Documentation
#define MEM_ELEM_BLOCKSIZE 16384
Definition at line 54 of file BLI_scanfill.h.
Referenced by mem_element_new(), and mem_element_reset().
Typedef Documentation
typedef struct ScanFillContext ScanFillContext
typedef struct ScanFillEdge ScanFillEdge
typedef struct ScanFillFace ScanFillFace
typedef struct ScanFillVert ScanFillVert
Function Documentation
struct ScanFillEdge* BLI_addfilledge (ScanFillContext * sf_ctx, struct ScanFillVert * v1, struct ScanFillVert * v2) [read]
Definition at line 217 of file scanfill.c.
References BLI_addtail(), ScanFillContext::filledgebase, mem_element_new(), ScanFillEdge::v1, and ScanFillEdge::v2.
Referenced by BMEdit_RecalcTessellation_intern(), bmo_triangle_fill_exec(), construct_param_handle(), draw_filled_lasso(), filldisplist(), mesh_recalcTessellation(), scanfill(), and testvertexnearedge().
struct ScanFillVert* BLI_addfillvert (ScanFillContext * sf_ctx, const float vec[3]) [read]
Definition at line 205 of file scanfill.c.
References BLI_addtail(), ScanFillVert::co, copy_v3_v3(), ScanFillContext::fillvertbase, and mem_element_new().
Referenced by BMEdit_RecalcTessellation_intern(), bmo_triangle_fill_exec(), construct_param_handle(), draw_filled_lasso(), filldisplist(), and mesh_recalcTessellation().
int BLI_begin_edgefill (ScanFillContext * sf_ctx)
Definition at line 767 of file scanfill.c.
Referenced by BMEdit_RecalcTessellation_intern(), bmo_triangle_fill_exec(), construct_param_handle(), draw_filled_lasso(), filldisplist(), and mesh_recalcTessellation().
int BLI_edgefill (ScanFillContext * sf_ctx, const short do_quad_tri_speedup)
Definition at line 774 of file scanfill.c.
References BLI_edgefill_ex(), and NULL.
Referenced by bmo_triangle_fill_exec(), filldisplist(), and mesh_recalcTessellation().
int BLI_edgefill_ex (ScanFillContext * sf_ctx, const short do_quad_tri_speedup, const float nor_proj[3])
Definition at line 779 of file scanfill.c.
References add_newell_cross_v3_v3v3(), addfillface(), axis_dominant_v3(), BLI_movelisttolist(), BLI_remlink(), boundisect(), callLocalErrorCallBack(), ScanFillVert::co, compare_v3v3(), copy_v3_v3(), dot_v3v3(), PolyFill::edges, PolyFill::f, ScanFillVert::f, ScanFillContext::filledgebase, ScanFillContext::fillvertbase, ListBase::first, ScanFillVert::h, ListBase::last, LIKELY, PolyFill::max_xy, MEM_callocN(), MEM_freeN(), mergepolysSimp(), PolyFill::min_xy, ScanFillEdge::next, ScanFillVert::next, normalize_v3(), PolyFill::nr, NULL, pf, ScanFillEdge::poly_nr, ScanFillVert::poly_nr, ScanFillEdge::prev, PRINT2, scanfill(), SF_EPSILON, SF_VERT_UNKNOWN, splitlist(), sub_v3_v3v3(), testvertexnearedge(), UNLIKELY, ScanFillEdge::v1, ScanFillEdge::v2, vergpoly(), PolyFill::verts, ScanFillVert::xy, and zero_v3().
Referenced by BLI_edgefill(), BMEdit_RecalcTessellation_intern(), construct_param_handle(), and draw_filled_lasso().
void BLI_end_edgefill (ScanFillContext * sf_ctx)
Definition at line 194 of file scanfill.c.
References FALSE, ScanFillContext::filledgebase, ScanFillContext::fillfacebase, ScanFillContext::fillvertbase, ListBase::first, ListBase::last, mem_element_reset(), and NULL.
Referenced by BMEdit_RecalcTessellation_intern(), bmo_triangle_fill_exec(), construct_param_handle(), draw_filled_lasso(), filldisplist(), and mesh_recalcTessellation().
void BLI_setErrorCallBack (void(*)(const char *) f)
Set a function taking a char* as argument to flag errors. If the callback is not set, the error is discarded.
Parameters:
f The function to use as callback
Attention:
used in creator.c
Definition at line 50 of file scanfill.c.
References BLI_localErrorCallBack.
Referenced by setCallbacks().
void BLI_setInterruptCallBack (int(*)(void) f)
Set a function to be able to interrupt the execution of processing in this module. If the function returns true, the execution will terminate gracefully. If the callback is not set, interruption is not possible.
Parameters:
f The function to use as callback
Attention:
used in creator.c
Definition at line 55 of file scanfill.c.
References BLI_localInterruptCallBack.