Blender: node_composite_math.c File Reference
node_composite_math.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_math (bNode *node, float *out, float *in, float *in2)
static void node_composit_exec_math (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_math (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_math_in []
static bNodeSocketTemplate cmp_node_math_out []
Detailed Description
Definition in file node_composite_math.c.
Function Documentation
static void do_math (bNode * node, float * out, float * in, float * in2) [static]
Definition at line 47 of file node_composite_math.c.
References acos(), KDL::asin(), KDL::atan(), cos(), bNode::custom1, floorf, log(), pow(), powf, sin(), and KDL::tan().
Referenced by node_composit_exec_math().
static void node_composit_exec_math (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 169 of file node_composite_math.c.
References alloc_compbuf(), CB_VAL, composit2_pixel_processor(), data, bNodeStack::data, do_math(), NULL, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_math().
void register_node_type_cmp_math (bNodeTreeType * ttype)
Definition at line 199 of file node_composite_math.c.
References CMP_NODE_MATH, NODE_CLASS_CONVERTOR, node_composit_exec_math(), node_math_label(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_label(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_math_in[] [static]
Initial value:
 {
    { SOCK_FLOAT, 1, "Value", 0.5f, 0.5f, 0.5f, 1.0f, -10000.0f, 10000.0f, PROP_NONE},
    { SOCK_FLOAT, 1, "Value", 0.5f, 0.5f, 0.5f, 1.0f, -10000.0f, 10000.0f, PROP_NONE},
    { -1, 0, "" }
}
Definition at line 36 of file node_composite_math.c.
bNodeSocketTemplate cmp_node_math_out[] [static]
Initial value:
 {
    { SOCK_FLOAT, 0, "Value"},
    { -1, 0, "" }
}
Definition at line 42 of file node_composite_math.c.