Blender: svm_ramp.h File Reference
svm_ramp.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device float4 rgb_ramp_lookup (KernelGlobals *kg, int offset, float f)
__device void svm_node_rgb_ramp (KernelGlobals *kg, ShaderData *sd, float *stack, uint4 node, int *offset)
__device void svm_node_rgb_curves (KernelGlobals *kg, ShaderData *sd, float *stack, uint4 node, int *offset)
Function Documentation
CCL_NAMESPACE_BEGIN __device float4 rgb_ramp_lookup (KernelGlobals * kg, int offset, float f)
Definition at line 24 of file svm_ramp.h.
References clamp, fetch_node_float(), i, and RAMP_TABLE_SIZE.
Referenced by svm_node_rgb_curves(), and svm_node_rgb_ramp().
__device void svm_node_rgb_curves (KernelGlobals * kg, ShaderData * sd, float * stack, uint4 node, int * offset)
Definition at line 56 of file svm_ramp.h.
References g, make_float3(), RAMP_TABLE_SIZE, rgb_ramp_lookup(), stack_load_float(), stack_load_float3(), stack_store_float3(), float4::w, uint4::w, float3::x, float4::x, float3::y, float4::y, uint4::y, float3::z, float4::z, and uint4::z.
Referenced by svm_eval_nodes().
__device void svm_node_rgb_ramp (KernelGlobals * kg, ShaderData * sd, float * stack, uint4 node, int * offset)
Definition at line 39 of file svm_ramp.h.
References float4_to_float3(), RAMP_TABLE_SIZE, rgb_ramp_lookup(), stack_load_float(), stack_store_float(), stack_store_float3(), stack_valid(), float4::w, uint4::w, uint4::y, and uint4::z.
Referenced by svm_eval_nodes().