Blender: rna_texture_api.c File Reference
rna_texture_api.c File Reference
RNA
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "RNA_define.h"
#include "BKE_utildefines.h"
Functions
void RNA_api_texture (StructRNA *srna)
void RNA_api_environment_map (StructRNA *srna)
Detailed Description
Definition in file rna_texture_api.c.
Function Documentation
void RNA_api_environment_map (StructRNA * srna)
Definition at line 101 of file rna_texture_api.c.
References FILE_MAX, FUNC_USE_CONTEXT, FUNC_USE_REPORTS, PROP_REQUIRED, RNA_def_float_array(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), and RNA_def_string_file_name().
Referenced by rna_def_environment_map().
void RNA_api_texture (StructRNA * srna)
Definition at line 83 of file rna_texture_api.c.
References FLT_MAX, NULL, PROP_REQUIRED, PROP_THICK_WRAP, RNA_def_float_vector(), RNA_def_function(), RNA_def_function_output(), RNA_def_function_ui_description(), and RNA_def_property_flag().
Referenced by rna_def_texture().