Blender: ED_uvedit.h File Reference
ED_uvedit.h File Reference
Editors
Functions
void ED_operatortypes_uvedit (void)
void ED_keymap_uvedit (struct wmKeyConfig *keyconf)
void ED_uvedit_assign_image (struct Main *bmain, struct Scene *scene, struct Object *obedit, struct Image *ima, struct Image *previma)
int ED_uvedit_minmax (struct Scene *scene, struct Image *ima, struct Object *obedit, float *min, float *max)
int ED_object_get_active_image (struct Object *ob, int mat_nr, struct Image **ima, struct ImageUser **iuser, struct bNode **node)
void ED_object_assign_active_image (struct Main *bmain, struct Object *ob, int mat_nr, struct Image *ima)
int ED_uvedit_test (struct Object *obedit)
int uvedit_face_visible_test (struct Scene *scene, struct Image *ima, struct BMFace *efa, struct MTexPoly *tf)
int uvedit_face_select_test (struct Scene *scene, struct BMEditMesh *em, struct BMFace *efa)
int uvedit_edge_select_test (struct BMEditMesh *em, struct Scene *scene, struct BMLoop *l)
int uvedit_uv_select_test (struct BMEditMesh *em, struct Scene *scene, struct BMLoop *l)
int uvedit_face_select_enable (struct Scene *scene, struct BMEditMesh *em, struct BMFace *efa, const short do_history)
int uvedit_face_select_disable (struct Scene *scene, struct BMEditMesh *em, struct BMFace *efa)
void uvedit_edge_select_enable (struct BMEditMesh *em, struct Scene *scene, struct BMLoop *l, const short do_history)
void uvedit_edge_select_disable (struct BMEditMesh *em, struct Scene *scene, struct BMLoop *l)
void uvedit_uv_select_enable (struct BMEditMesh *em, struct Scene *scene, struct BMLoop *l, const short do_history)
void uvedit_uv_select_disable (struct BMEditMesh *em, struct Scene *scene, struct BMLoop *l)
int ED_uvedit_nearest_uv (struct Scene *scene, struct Object *obedit, struct Image *ima, float co[2], float uv[2])
void ED_uvedit_live_unwrap_begin (struct Scene *scene, struct Object *obedit)
void ED_uvedit_live_unwrap_re_solve (void)
void ED_uvedit_live_unwrap_end (short cancel)
void ED_uvedit_live_unwrap (struct Scene *scene, struct Object *obedit)
void ED_unwrap_lscm (struct Scene *scene, struct Object *obedit, const short sel)
void draw_uvedit_main (struct SpaceImage *sima, struct ARegion *ar, struct Scene *scene, struct Object *obedit, struct Object *obact)
void ED_uvedit_buttons_register (struct ARegionType *art)
Detailed Description
Definition in file ED_uvedit.h.
Function Documentation
void draw_uvedit_main (struct SpaceImage * sima, struct ARegion * ar, struct Scene * scene, struct Object * obedit, struct Object * obact)
Definition at line 874 of file uvedit_draw.c.
References draw_uvs(), draw_uvs_shadow(), draw_uvs_texpaint(), drawcursor_sima(), ED_space_image_show_uvedit(), ED_space_image_show_uvshadow(), Object::mode, OB_MESH, OB_MODE_TEXTURE_PAINT, Scene::toolsettings, Object::type, and ToolSettings::use_uv_sculpt.
Referenced by image_main_area_draw().
void ED_keymap_uvedit (struct wmKeyConfig * keyconf)
Definition at line 3595 of file uvedit_ops.c.
References ACTIONMOUSE, AKEY, BKEY, CKEY, COMMAKEY, ED_object_generic_keymap(), ED_operator_uvedit_can_uv_sculpt(), EKEY, FALSE, HKEY, IKEY, KM_ALT, KM_CTRL, KM_PRESS, KM_SHIFT, LKEY, PERIODKEY, PKEY, wmKeyMap::poll, wmKeyMapItem::ptr, QKEY, RNA_boolean_set(), RNA_enum_set(), RNA_string_set(), SEL_INVERT, SEL_TOGGLE, SELECTMOUSE, SKEY, SPACE_IMAGE, TABKEY, transform_keymap_for_space(), TRUE, VKEY, WKEY, WM_keymap_add_item(), WM_keymap_add_menu(), and WM_keymap_find().
Referenced by ED_spacetypes_keymap().
void ED_object_assign_active_image (struct Main * bmain, struct Object * ob, int mat_nr, struct Image * ima)
Definition at line 154 of file uvedit_ops.c.
References ED_node_generic_update(), give_current_material(), Image::id, bNode::id, is_image_texture_node(), nodeGetActiveTexture(), Material::nodetree, NULL, and Material::use_nodes.
Referenced by ED_uvedit_assign_image().
int ED_object_get_active_image (struct Object * ob, int mat_nr, struct Image ** ima, struct ImageUser ** iuser, struct bNode ** node)
Definition at line 135 of file uvedit_ops.c.
References FALSE, give_current_material(), bNode::id, if(), is_image_texture_node(), nodeGetActiveTexture(), Material::nodetree, NULL, TRUE, and Material::use_nodes.
Referenced by image_refresh(), imapaint_face_image(), project_paint_face_image(), and tex_mat_set_texture_cb().
void ED_operatortypes_uvedit (void)
Definition at line 3554 of file uvedit_ops.c.
References UV_OT_align(), UV_OT_average_islands_scale(), UV_OT_circle_select(), UV_OT_cube_project(), UV_OT_cursor_set(), UV_OT_cylinder_project(), UV_OT_from_view(), UV_OT_hide(), UV_OT_mark_seam(), UV_OT_minimize_stretch(), UV_OT_pack_islands(), UV_OT_pin(), UV_OT_reset(), UV_OT_reveal(), UV_OT_seams_from_islands(), UV_OT_select(), UV_OT_select_all(), UV_OT_select_border(), UV_OT_select_linked(), UV_OT_select_linked_pick(), UV_OT_select_loop(), UV_OT_select_pinned(), UV_OT_snap_cursor(), UV_OT_snap_selected(), UV_OT_sphere_project(), UV_OT_stitch(), UV_OT_tile_set(), UV_OT_unlink_selected(), UV_OT_unwrap(), UV_OT_weld(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
void ED_unwrap_lscm (struct Scene * scene, struct Object * obedit, const short sel)
Definition at line 1127 of file uvedit_unwrap_ops.c.
References BMEdit_FromObject(), construct_param_handle(), construct_param_handle_subsurfed(), param_delete(), PARAM_FALSE, param_flush(), param_lscm_begin(), param_lscm_end(), param_lscm_solve(), param_pack(), Scene::toolsettings, ToolSettings::unwrapper, UVCALC_FILLHOLES, ToolSettings::uvcalc_flag, ToolSettings::uvcalc_margin, UVCALC_NO_ASPECT_CORRECT, and UVCALC_USESUBSURF.
Referenced by ED_uvedit_live_unwrap(), mark_seam_exec(), and unwrap_exec().
void ED_uvedit_assign_image (struct Main * bmain, struct Scene * scene, struct Object * obedit, struct Image * ima, struct Image * previma)
Definition at line 167 of file uvedit_ops.c.
References BMEditMesh::bm, BM_active_face_get(), BM_data_layer_add(), BM_FACES_OF_MESH, BM_ITER_MESH, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), CustomData_has_layer(), DAG_id_tag_update(), Object::data, BMHeader::data, ED_object_assign_active_image(), BMFace::head, Image::id, id_lib_extern(), id_us_plus(), IMA_TYPE_COMPOSITE, IMA_TYPE_R_RESULT, BMesh::ldata, BMFace::mat_nr, NULL, OB_MESH, BMesh::pdata, scene_use_new_shading_nodes(), BMesh::totface, MTexPoly::tpage, Object::type, Image::type, update(), ID::us, and uvedit_face_visible_test().
Referenced by drop_named_image_invoke(), ED_space_image_set(), and ED_uvedit_ensure_uvs().
void ED_uvedit_buttons_register (struct ARegionType * art)
Definition at line 206 of file uvedit_buttons.c.
References BLI_addtail(), PanelType::draw, PanelType::idname, image_panel_uv(), image_panel_uv_poll(), PanelType::label, MEM_callocN(), ARegionType::paneltypes, and PanelType::poll.
Referenced by ED_spacetype_image().
void ED_uvedit_live_unwrap (struct Scene * scene, struct Object * obedit)
Definition at line 836 of file uvedit_unwrap_ops.c.
References BMEditMesh::bm, BMEdit_FromObject(), CD_MLOOPUV, CustomData_has_layer(), ED_unwrap_lscm(), ToolSettings::edge_mode_live_unwrap, FALSE, BMesh::ldata, and Scene::toolsettings.
Referenced by edbm_mark_seam(), and mouse_mesh_shortest_path().
void ED_uvedit_live_unwrap_begin (struct Scene * scene, struct Object * obedit)
Definition at line 798 of file uvedit_unwrap_ops.c.
References BMEdit_FromObject(), construct_param_handle(), construct_param_handle_subsurfed(), ED_uvedit_test(), param_lscm_begin(), PARAM_TRUE, Scene::toolsettings, ToolSettings::unwrapper, UVCALC_FILLHOLES, ToolSettings::uvcalc_flag, and UVCALC_USESUBSURF.
Referenced by createTransUVs(), and uvedit_live_unwrap_update().
void ED_uvedit_live_unwrap_end (short cancel)
Definition at line 825 of file uvedit_unwrap_ops.c.
References NULL, param_delete(), param_flush_restore(), and param_lscm_end().
Referenced by postTrans(), and uvedit_live_unwrap_update().
void ED_uvedit_live_unwrap_re_solve (void)
Definition at line 817 of file uvedit_unwrap_ops.c.
References param_flush(), and param_lscm_solve().
Referenced by recalcData_image(), and uvedit_live_unwrap_update().
int ED_uvedit_minmax (struct Scene * scene, struct Image * ima, struct Object * obedit, float * min, float * max)
Definition at line 584 of file uvedit_ops.c.
References BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, DO_MINMAX2, BMLoop::head, BMFace::head, INIT_MINMAX2, BMesh::ldata, BMesh::pdata, MLoopUV::uv, uvedit_face_visible_test(), and uvedit_uv_select_test().
Referenced by image_view_selected_exec(), and uvedit_center().
int ED_uvedit_nearest_uv (struct Scene * scene, struct Object * obedit, struct Image * ima, float co[2], float uv[2])
Definition at line 859 of file uvedit_ops.c.
References BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, fabs(), BMLoop::head, BMFace::head, BMesh::ldata, BMesh::pdata, MLoopUV::uv, and uvedit_face_visible_test().
Referenced by CalcSnapGeometry().
int ED_uvedit_test (struct Object * obedit)
Definition at line 89 of file uvedit_ops.c.
References BMEdit_FromObject(), EDBM_mtexpoly_check(), OB_MESH, and Object::type.
Referenced by ED_uvedit_ensure_uvs(), ED_uvedit_live_unwrap_begin(), image_panel_uv_poll(), and uvedit_set_tile().
void uvedit_edge_select_disable (struct BMEditMesh * em, struct Scene * scene, struct BMLoop * l)
Definition at line 432 of file uvedit_ops.c.
References BMEditMesh::bm, BM_edge_select_set(), BM_face_select_set(), BM_vert_select_set(), CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::e, BMLoop::f, FALSE, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, BMLoop::next, SCE_SELECT_EDGE, SCE_SELECT_FACE, ToolSettings::selectmode, Scene::toolsettings, ToolSettings::uv_flag, UV_SYNC_SELECTION, BMEdge::v1, and BMEdge::v2.
Referenced by mouse_select().
void uvedit_edge_select_enable (struct BMEditMesh * em, struct Scene * scene, struct BMLoop * l, const short do_history)
Definition at line 402 of file uvedit_ops.c.
References BMEditMesh::bm, BM_edge_select_set(), BM_face_select_set(), BM_select_history_store, BM_vert_select_set(), CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::e, BMLoop::f, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, BMLoop::next, SCE_SELECT_EDGE, SCE_SELECT_FACE, ToolSettings::selectmode, Scene::toolsettings, TRUE, ToolSettings::uv_flag, UV_SYNC_SELECTION, BMEdge::v1, and BMEdge::v2.
Referenced by mouse_select().
int uvedit_edge_select_test (struct BMEditMesh * em, struct Scene * scene, struct BMLoop * l)
Definition at line 376 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::e, BMLoop::f, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, BMLoop::next, SCE_SELECT_EDGE, SCE_SELECT_FACE, ToolSettings::selectmode, Scene::toolsettings, ToolSettings::uv_flag, UV_SYNC_SELECTION, and BMLoop::v.
Referenced by draw_uvs(), mark_seam_exec(), and mouse_select().
int uvedit_face_select_disable (struct Scene * scene, struct BMEditMesh * em, struct BMFace * efa)
Definition at line 353 of file uvedit_ops.c.
References BMEditMesh::bm, BM_face_select_set(), BM_ITER_ELEM, BM_LOOPS_OF_FACE, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, FALSE, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, Scene::toolsettings, ToolSettings::uv_flag, and UV_SYNC_SELECTION.
Referenced by hide_exec(), mouse_select(), and uv_faces_do_sticky().
int uvedit_face_select_enable (struct Scene * scene, struct BMEditMesh * em, struct BMFace * efa, const short do_history)
Definition at line 327 of file uvedit_ops.c.
References BMEditMesh::bm, BM_face_select_set(), BM_ITER_ELEM, BM_LOOPS_OF_FACE, BM_select_history_store, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, Scene::toolsettings, TRUE, ToolSettings::uv_flag, and UV_SYNC_SELECTION.
Referenced by ED_uvedit_ensure_uvs(), mouse_select(), and uv_faces_do_sticky().
int uvedit_face_select_test (struct Scene * scene, struct BMEditMesh * em, struct BMFace * efa)
Definition at line 306 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_ELEM, BM_LOOPS_OF_FACE, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, Scene::toolsettings, ToolSettings::uv_flag, and UV_SYNC_SELECTION.
Referenced by draw_uvs(), and mouse_select().
int uvedit_face_visible_test (struct Scene * scene, struct Image * ima, struct BMFace * efa, struct MTexPoly * tf)
Definition at line 296 of file uvedit_ops.c.
References Scene::toolsettings, MTexPoly::tpage, ToolSettings::uv_flag, UV_SHOW_SAME_IMAGE, and uvedit_face_visible_nolocal().
Referenced by border_select_exec(), createTransUVs(), draw_uvs(), draw_uvs_stretch(), ED_uvedit_assign_image(), ED_uvedit_median(), ED_uvedit_minmax(), ED_uvedit_nearest_uv(), find_nearest_uv_face(), hide_exec(), mouse_select(), pin_exec(), select_all_perform(), select_edgeloop(), select_linked(), select_pinned_exec(), snap_uvs_to_adjacent_unselected(), snap_uvs_to_cursor(), snap_uvs_to_pixels(), unlink_selection_exec(), uv_find_nearest_edge(), uv_find_nearest_vert(), uv_sel_co_from_eve(), uvedit_center(), and weld_align_uv().
void uvedit_uv_select_disable (struct BMEditMesh * em, struct Scene * scene, struct BMLoop * l)
Definition at line 496 of file uvedit_ops.c.
References BMEditMesh::bm, BM_face_select_set(), BM_vert_select_set(), CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::f, FALSE, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, SCE_SELECT_FACE, ToolSettings::selectmode, Scene::toolsettings, ToolSettings::uv_flag, UV_SYNC_SELECTION, and BMLoop::v.
Referenced by border_select_exec(), mouse_select(), select_edgeloop(), select_uv_inside_ellipse(), and uv_faces_do_sticky().
void uvedit_uv_select_enable (struct BMEditMesh * em, struct Scene * scene, struct BMLoop * l, const short do_history)
Definition at line 475 of file uvedit_ops.c.
References BMEditMesh::bm, BM_face_select_set(), BM_select_history_remove, BM_vert_select_set(), CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::f, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, SCE_SELECT_FACE, ToolSettings::selectmode, Scene::toolsettings, TRUE, ToolSettings::uv_flag, UV_SYNC_SELECTION, and BMLoop::v.
Referenced by border_select_exec(), mouse_select(), select_edgeloop(), select_pinned_exec(), select_uv_inside_ellipse(), stitch_process_data(), and uv_faces_do_sticky().
int uvedit_uv_select_test (struct BMEditMesh * em, struct Scene * scene, struct BMLoop * l)
Definition at line 458 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::f, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, SCE_SELECT_FACE, ToolSettings::selectmode, Scene::toolsettings, ToolSettings::uv_flag, UV_SYNC_SELECTION, and BMLoop::v.
Referenced by construct_param_handle(), createTransUVs(), draw_uvs(), ED_uvedit_median(), ED_uvedit_minmax(), mouse_select(), pin_exec(), select_edgeloop(), snap_uvs_to_adjacent_unselected(), snap_uvs_to_cursor(), snap_uvs_to_pixels(), stitch_init(), texface_from_original_index(), uv_find_nearest_vert(), uv_sel_co_from_eve(), uvedit_center(), uvedit_have_selection(), uvedit_translate(), and weld_align_uv().