Blender: BOP_CarveInterface.cpp File Reference
BOP_CarveInterface.cpp File Reference
#include "../extern/BOP_Interface.h"
#include "../../bsp/intern/BSP_CSGMesh_CFIterator.h"
#include <carve/csg_triangulator.hpp>
#include <carve/interpolator.hpp>
#include <carve/rescale.hpp>
#include <iostream>
Defines
#define MAX(x, y) ((x)>(y)?(x):(y))
#define MIN(x, y) ((x)<(y)?(x):(y))
Typedefs
typedef unsigned int uint
Functions
static bool isQuadPlanar (carve::geom3d::Vector &v1, carve::geom3d::Vector &v2, carve::geom3d::Vector &v3, carve::geom3d::Vector &v4)
static bool isFacePlanar (CSG_IFace &face, std::vector< carve::geom3d::Vector > &vertices)
static void Carve_copyMeshes (std::vector< MeshSet< 3 >::mesh_t * > &meshes, std::vector< MeshSet< 3 >::mesh_t * > &new_meshes)
static MeshSet< 3 > * Carve_meshSetFromMeshes (std::vector< MeshSet< 3 >::mesh_t * > &meshes)
static MeshSet< 3 > * Carve_meshSetFromTwoMeshes (std::vector< MeshSet< 3 >::mesh_t * > &left_meshes, std::vector< MeshSet< 3 >::mesh_t * > &right_meshes)
static bool Carve_checkEdgeFaceIntersections_do (carve::csg::Intersections &intersections, MeshSet< 3 >::face_t *face_a, MeshSet< 3 >::edge_t *edge_b)
static bool Carve_checkEdgeFaceIntersections (carve::csg::Intersections &intersections, MeshSet< 3 >::face_t *face_a, MeshSet< 3 >::face_t *face_b)
static bool Carve_facesAreCoplanar (const MeshSet< 3 >::face_t *a, const MeshSet< 3 >::face_t *b)
static bool Carve_checkMeshSetInterseciton_do (carve::csg::Intersections &intersections, const RTreeNode< 3, Face< 3 > * > *a_node, const RTreeNode< 3, Face< 3 > * > *b_node, bool descend_a=true)
static bool Carve_checkMeshSetInterseciton (RTreeNode< 3, Face< 3 > * > *rtree_a, RTreeNode< 3, Face< 3 > * > *rtree_b)
static void Carve_getIntersectedOperandMeshes (std::vector< MeshSet< 3 >::mesh_t * > &meshes, MeshSet< 3 >::aabb_t &otherAABB, std::vector< MeshSet< 3 >::mesh_t * > &operandMeshes)
static MeshSet< 3 > * Carve_getIntersectedOperand (std::vector< MeshSet< 3 >::mesh_t * > &meshes, MeshSet< 3 >::aabb_t &otherAABB)
static MeshSet< 3 > * Carve_unionIntersectingMeshes (MeshSet< 3 > *poly, MeshSet< 3 >::aabb_t &otherAABB, carve::interpolate::FaceAttr< uint > &oface_num)
static void Carve_unionIntersections (MeshSet< 3 > **left_r, MeshSet< 3 > **right_r, carve::interpolate::FaceAttr< uint > &oface_num)
static MeshSet< 3 > * Carve_addMesh (CSG_FaceIteratorDescriptor &face_it, CSG_VertexIteratorDescriptor &vertex_it, carve::interpolate::FaceAttr< uint > &oface_num, uint &num_origfaces)
static double triangleArea (carve::geom3d::Vector &v1, carve::geom3d::Vector &v2, carve::geom3d::Vector &v3)
static bool checkValidQuad (std::vector< MeshSet< 3 >::vertex_t > &vertex_storage, uint quad[4])
static uint quadMerge (std::map< MeshSet< 3 >::vertex_t *, uint > *vertexToIndex_map, std::vector< MeshSet< 3 >::vertex_t > &vertex_storage, MeshSet< 3 >::face_t *f1, MeshSet< 3 >::face_t *f2, uint v, uint quad[4])
static bool Carve_checkDegeneratedFace (MeshSet< 3 >::face_t *face)
static BSP_CSGMesh * Carve_exportMesh (MeshSet< 3 > *&poly, carve::interpolate::FaceAttr< uint > &oface_num, uint num_origfaces)
BoolOpState BOP_performBooleanOperation (BoolOpType opType, BSP_CSGMesh **outputMesh, CSG_FaceIteratorDescriptor obAFaces, CSG_VertexIteratorDescriptor obAVertices, CSG_FaceIteratorDescriptor obBFaces, CSG_VertexIteratorDescriptor obBVertices)
Detailed Description
Definition in file BOP_CarveInterface.cpp.
Define Documentation
#define MAX (x, y) ((x)>(y)?(x):(y))
Definition at line 46 of file BOP_CarveInterface.cpp.
Referenced by BOP_performBooleanOperation(), WTURBULENCE::computeEigenvalues(), LbmFsgrSolver::handleCpdata(), BasicVector::Vector3Dim< Scalar >::maximize(), and ntlVector3Dim< Scalar >::maximize().
#define MIN (x, y) ((x)<(y)?(x):(y))
Definition at line 47 of file BOP_CarveInterface.cpp.
Referenced by __nlSparseMatrixConstruct(), BOP_performBooleanOperation(), WTURBULENCE::computeEigenvalues(), LbmFsgrSolver::debugDisplayNode(), LbmFsgrSolver::handleCpdata(), BasicVector::Vector3Dim< Scalar >::minimize(), ntlVector3Dim< Scalar >::minimize(), ntlSetVec3f::operator*=(), and ntlSetVec3f::operator+=().
Typedef Documentation
typedef unsigned int uint
Definition at line 44 of file BOP_CarveInterface.cpp.
Function Documentation
BoolOpState BOP_performBooleanOperation (BoolOpType opType, BSP_CSGMesh ** outputMesh, CSG_FaceIteratorDescriptor obAFaces, CSG_VertexIteratorDescriptor obAVertices, CSG_FaceIteratorDescriptor obBFaces, CSG_VertexIteratorDescriptor obBVertices)
Performs a generic booleam operation, the entry point for external modules.
Parameters:
opType Boolean operation type BOP_INTERSECTION, BOP_UNION, BOP_DIFFERENCE
outputMesh Output mesh, the final result (the object C)
obAFaces Object A faces list
obAVertices Object A vertices list
obBFaces Object B faces list
obBVertices Object B vertices list
interpFunc Interpolating function
Returns:
operation state: BOP_OK, BOP_NO_SOLID, BOP_ERROR
Definition at line 714 of file BOP_CarveInterface.cpp.
References BOP_DIFFERENCE, BOP_ERROR, BOP_INTERSECTION, BOP_OK, BOP_UNION, Carve_addMesh(), Carve_exportMesh(), Carve_unionIntersections(), i, left(), MAX, max, MIN, min, and NULL.
static MeshSet<3>* Carve_addMesh (CSG_FaceIteratorDescriptor & face_it, CSG_VertexIteratorDescriptor & vertex_it, carve::interpolate::FaceAttr< uint > & oface_num, uint & num_origfaces) [static]
Definition at line 356 of file BOP_CarveInterface.cpp.
References CSG_FaceIteratorDescriptor::Done, CSG_VertexIteratorDescriptor::Done, CSG_VertexIteratorDescriptor::Fill, CSG_FaceIteratorDescriptor::Fill, i, isFacePlanar(), CSG_FaceIteratorDescriptor::it, CSG_VertexIteratorDescriptor::it, CSG_IFace::orig_face, CSG_IVertex::position, CSG_FaceIteratorDescriptor::Step, CSG_VertexIteratorDescriptor::Step, CSG_IFace::vertex_index, and CSG_IFace::vertex_number.
Referenced by BOP_performBooleanOperation().
static bool Carve_checkDegeneratedFace (MeshSet< 3 >::face_t * face) [static]
Definition at line 550 of file BOP_CarveInterface.cpp.
References triangleArea().
Referenced by Carve_exportMesh().
static bool Carve_checkEdgeFaceIntersections (carve::csg::Intersections & intersections, MeshSet< 3 >::face_t * face_a, MeshSet< 3 >::face_t * face_b) [static]
Definition at line 121 of file BOP_CarveInterface.cpp.
References Carve_checkEdgeFaceIntersections_do().
Referenced by Carve_checkMeshSetInterseciton_do().
static bool Carve_checkEdgeFaceIntersections_do (carve::csg::Intersections & intersections, MeshSet< 3 >::face_t * face_a, MeshSet< 3 >::edge_t * edge_b) [static]
Definition at line 108 of file BOP_CarveInterface.cpp.
Referenced by Carve_checkEdgeFaceIntersections().
static bool Carve_checkMeshSetInterseciton (RTreeNode< 3, Face< 3 > * > * rtree_a, RTreeNode< 3, Face< 3 > * > * rtree_b) [static]
Definition at line 195 of file BOP_CarveInterface.cpp.
References Carve_checkMeshSetInterseciton_do().
Referenced by Carve_getIntersectedOperandMeshes().
static bool Carve_checkMeshSetInterseciton_do (carve::csg::Intersections & intersections, const RTreeNode< 3, Face< 3 > * > * a_node, const RTreeNode< 3, Face< 3 > * > * b_node, bool descend_a = true) [static]
Definition at line 144 of file BOP_CarveInterface.cpp.
References Carve_checkEdgeFaceIntersections(), Carve_facesAreCoplanar(), EPSILON, fb(), and i.
Referenced by Carve_checkMeshSetInterseciton().
static void Carve_copyMeshes (std::vector< MeshSet< 3 >::mesh_t * > & meshes, std::vector< MeshSet< 3 >::mesh_t * > & new_meshes) [static]
Definition at line 76 of file BOP_CarveInterface.cpp.
Referenced by Carve_meshSetFromMeshes(), and Carve_meshSetFromTwoMeshes().
static BSP_CSGMesh* Carve_exportMesh (MeshSet< 3 > *& poly, carve::interpolate::FaceAttr< uint > & oface_num, uint num_origfaces) [static]
Definition at line 564 of file BOP_CarveInterface.cpp.
References BSP_CSGMesh::BuildEdges(), Carve_checkDegeneratedFace(), BSP_CSGMesh::FaceSet(), i, BSP_MVertex::m_edges, BSP_MFace::m_orig_face, BSP_MFace::m_plane, BSP_MFace::m_verts, BSP_CSGMesh::New(), NULL, quadMerge(), MT_Tuple4::setValue(), BSP_CSGMesh::SetVertices(), and BSP_CSGMesh::VertexSet().
Referenced by BOP_performBooleanOperation().
static bool Carve_facesAreCoplanar (const MeshSet< 3 >::face_t * a, const MeshSet< 3 >::face_t * b) [inline, static]
Definition at line 136 of file BOP_CarveInterface.cpp.
Referenced by Carve_checkMeshSetInterseciton_do().
static MeshSet<3>* Carve_getIntersectedOperand (std::vector< MeshSet< 3 >::mesh_t * > & meshes, MeshSet< 3 >::aabb_t & otherAABB) [static]
Definition at line 249 of file BOP_CarveInterface.cpp.
References Carve_getIntersectedOperandMeshes(), Carve_meshSetFromMeshes(), and NULL.
Referenced by Carve_unionIntersectingMeshes().
static void Carve_getIntersectedOperandMeshes (std::vector< MeshSet< 3 >::mesh_t * > & meshes, MeshSet< 3 >::aabb_t & otherAABB, std::vector< MeshSet< 3 >::mesh_t * > & operandMeshes) [static]
Definition at line 202 of file BOP_CarveInterface.cpp.
References Carve_checkMeshSetInterseciton().
Referenced by Carve_getIntersectedOperand().
static MeshSet<3>* Carve_meshSetFromMeshes (std::vector< MeshSet< 3 >::mesh_t * > & meshes) [static]
Definition at line 88 of file BOP_CarveInterface.cpp.
References Carve_copyMeshes().
Referenced by Carve_getIntersectedOperand().
static MeshSet<3>* Carve_meshSetFromTwoMeshes (std::vector< MeshSet< 3 >::mesh_t * > & left_meshes, std::vector< MeshSet< 3 >::mesh_t * > & right_meshes) [static]
Definition at line 97 of file BOP_CarveInterface.cpp.
References Carve_copyMeshes().
Referenced by Carve_unionIntersectingMeshes().
static MeshSet<3>* Carve_unionIntersectingMeshes (MeshSet< 3 > * poly, MeshSet< 3 >::aabb_t & otherAABB, carve::interpolate::FaceAttr< uint > & oface_num) [static]
Definition at line 260 of file BOP_CarveInterface.cpp.
References Carve_getIntersectedOperand(), Carve_meshSetFromTwoMeshes(), left(), and NULL.
Referenced by Carve_unionIntersections().
static void Carve_unionIntersections (MeshSet< 3 > ** left_r, MeshSet< 3 > ** right_r, carve::interpolate::FaceAttr< uint > & oface_num) [static]
Definition at line 335 of file BOP_CarveInterface.cpp.
References Carve_unionIntersectingMeshes(), and left().
Referenced by BOP_performBooleanOperation().
static bool checkValidQuad (std::vector< MeshSet< 3 >::vertex_t > & vertex_storage, uint quad[4]) [static]
Definition at line 441 of file BOP_CarveInterface.cpp.
References cross(), dot(), i, isQuadPlanar(), and triangleArea().
Referenced by quadMerge().
static bool isFacePlanar (CSG_IFace & face, std::vector< carve::geom3d::Vector > & vertices) [static]
Definition at line 66 of file BOP_CarveInterface.cpp.
References isQuadPlanar(), CSG_IFace::vertex_index, and CSG_IFace::vertex_number.
Referenced by Carve_addMesh().
static bool isQuadPlanar (carve::geom3d::Vector & v1, carve::geom3d::Vector & v2, carve::geom3d::Vector & v3, carve::geom3d::Vector & v4) [static]
Definition at line 49 of file BOP_CarveInterface.cpp.
References cross(), dot(), and fabs().
Referenced by checkValidQuad(), and isFacePlanar().
static uint quadMerge (std::map< MeshSet< 3 >::vertex_t *, uint > * vertexToIndex_map, std::vector< MeshSet< 3 >::vertex_t > & vertex_storage, MeshSet< 3 >::face_t * f1, MeshSet< 3 >::face_t * f2, uint v, uint quad[4]) [static]
Definition at line 500 of file BOP_CarveInterface.cpp.
References checkValidQuad().
Referenced by Carve_exportMesh().
static double triangleArea (carve::geom3d::Vector & v1, carve::geom3d::Vector & v2, carve::geom3d::Vector & v3) [static]
Definition at line 433 of file BOP_CarveInterface.cpp.
References cross().
Referenced by Carve_checkDegeneratedFace(), and checkValidQuad().