Blender: object_group.c File Reference
object_group.c File Reference
object
#include <string.h>
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "DNA_group_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_group.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "ED_screen.h"
#include "ED_object.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "object_intern.h"
Functions
static int objects_add_active_exec (bContext *C, wmOperator *op)
void GROUP_OT_objects_add_active (wmOperatorType *ot)
static int objects_remove_active_exec (bContext *C, wmOperator *op)
void GROUP_OT_objects_remove_active (wmOperatorType *ot)
static int group_objects_remove_exec (bContext *C, wmOperator *UNUSED(op))
void GROUP_OT_objects_remove (wmOperatorType *ot)
static int group_create_exec (bContext *C, wmOperator *op)
void GROUP_OT_create (wmOperatorType *ot)
static int group_add_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_group_add (wmOperatorType *ot)
static int group_link_exec (bContext *C, wmOperator *op)
void OBJECT_OT_group_link (wmOperatorType *ot)
static int group_remove_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_group_remove (wmOperatorType *ot)
Detailed Description
Definition in file object_group.c.
Function Documentation
static int group_add_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 236 of file object_group.c.
References add_group(), add_to_group(), CTX_data_scene(), ED_object_context(), NC_OBJECT, ND_DRAW, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by OBJECT_OT_group_add().
static int group_create_exec (bContext * C, wmOperator * op) [static]
Definition at line 195 of file object_group.c.
References add_group(), add_to_group(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_scene_sort(), MAX_ID_NAME, NA_EDITED, Object::name, NC_GROUP, NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_string_get(), and WM_event_add_notifier().
Referenced by GROUP_OT_create().
static int group_link_exec (bContext * C, wmOperator * op) [static]
Definition at line 267 of file object_group.c.
References add_to_group(), BLI_findlink(), CTX_data_main(), CTX_data_scene(), ED_object_context(), ELEM, NC_OBJECT, ND_DRAW, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), and WM_event_add_notifier().
Referenced by OBJECT_OT_group_link().
static int group_objects_remove_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 161 of file object_group.c.
References CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_scene_sort(), find_group(), NA_EDITED, NC_GROUP, NULL, OPERATOR_FINISHED, rem_from_group(), and WM_event_add_notifier().
Referenced by GROUP_OT_objects_remove().
void GROUP_OT_create (wmOperatorType * ot)
Definition at line 217 of file object_group.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, group_create_exec(), wmOperatorType::idname, MAX_ID_NAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void GROUP_OT_objects_add_active (wmOperatorType * ot)
Definition at line 99 of file object_group.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, objects_add_active_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void GROUP_OT_objects_remove (wmOperatorType * ot)
Definition at line 180 of file object_group.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, group_objects_remove_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void GROUP_OT_objects_remove_active (wmOperatorType * ot)
Definition at line 146 of file object_group.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, objects_remove_active_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
static int group_remove_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 305 of file object_group.c.
References CTX_data_pointer_get_type(), CTX_data_scene(), PointerRNA::data, ED_object_context(), NC_OBJECT, ND_DRAW, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, rem_from_group(), RNA_Group, and WM_event_add_notifier().
Referenced by OBJECT_OT_group_remove().
void OBJECT_OT_group_add (wmOperatorType * ot)
Definition at line 253 of file object_group.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, group_add_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by ED_operatortypes_object().
void OBJECT_OT_group_link (wmOperatorType * ot)
Definition at line 283 of file object_group.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, group_link_exec(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::prop, Object::prop, RNA_def_enum(), RNA_def_enum_funcs(), RNA_group_local_itemf(), wmOperatorType::srna, and WM_enum_search_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_group_remove (wmOperatorType * ot)
Definition at line 321 of file object_group.c.
References wmOperatorType::exec, wmOperatorType::flag, group_remove_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by ED_operatortypes_object().
static int objects_add_active_exec (bContext * C, wmOperator * op) [static]
Definition at line 62 of file object_group.c.
References add_to_group(), BKE_report(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_scene_sort(), ListBase::first, Main::group, Group::id, NA_EDITED, NC_GROUP, ID::next, NULL, OBACT, object_in_group(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, RPT_WARNING, and WM_event_add_notifier().
Referenced by GROUP_OT_objects_add_active().
static int objects_remove_active_exec (bContext * C, wmOperator * op) [static]
Definition at line 114 of file object_group.c.
References BKE_report(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_scene_sort(), ListBase::first, Main::group, Group::id, NA_EDITED, NC_GROUP, ID::next, NULL, OBACT, object_in_group(), OPERATOR_CANCELLED, OPERATOR_FINISHED, rem_from_group(), wmOperator::reports, RPT_ERROR, and WM_event_add_notifier().
Referenced by GROUP_OT_objects_remove_active().