Blender: TransformReader Class Reference
TransformReader Class Reference
#include <TransformReader.h>
Classes
struct Animation
Public Member Functions
TransformReader (UnitConverter *conv)
void get_node_mat (float mat[][4], COLLADAFW::Node *node, std::map< COLLADAFW::UniqueId, Animation > *animation_map, Object *ob)
void dae_rotate_to_mat4 (COLLADAFW::Transformation *tm, float m[][4])
void dae_translate_to_mat4 (COLLADAFW::Transformation *tm, float m[][4])
void dae_scale_to_mat4 (COLLADAFW::Transformation *tm, float m[][4])
void dae_matrix_to_mat4 (COLLADAFW::Transformation *tm, float m[][4])
void dae_translate_to_v3 (COLLADAFW::Transformation *tm, float v[3])
void dae_scale_to_v3 (COLLADAFW::Transformation *tm, float v[3])
void dae_vector3_to_v3 (const COLLADABU::Math::Vector3 &v3, float v[3])
Protected Attributes
UnitConverter * unit_converter
Detailed Description
Definition at line 46 of file TransformReader.h.
Constructor & Destructor Documentation
TransformReader::TransformReader (UnitConverter * conv)
Definition at line 32 of file TransformReader.cpp.
Member Function Documentation
void TransformReader::dae_matrix_to_mat4 (COLLADAFW::Transformation * tm, float m[][4])
Definition at line 110 of file TransformReader.cpp.
References UnitConverter::dae_matrix_to_mat4_(), getMatrix(), and unit_converter.
Referenced by AnimationImporter::evaluate_animation(), AnimationImporter::evaluate_transform_at_frame(), and get_node_mat().
void TransformReader::dae_rotate_to_mat4 (COLLADAFW::Transformation * tm, float m[][4])
Definition at line 79 of file TransformReader.cpp.
References angle(), axis_angle_to_mat4(), DEG2RAD, and Rotate.
Referenced by AnimationImporter::evaluate_transform_at_frame(), and get_node_mat().
void TransformReader::dae_scale_to_mat4 (COLLADAFW::Transformation * tm, float m[][4])
Definition at line 103 of file TransformReader.cpp.
References Scale, size(), and size_to_mat4().
Referenced by AnimationImporter::evaluate_transform_at_frame(), and get_node_mat().
void TransformReader::dae_scale_to_v3 (COLLADAFW::Transformation * tm, float v[3])
Definition at line 120 of file TransformReader.cpp.
References dae_vector3_to_v3(), and Scale.
Referenced by AnimationImporter::evaluate_animation().
void TransformReader::dae_translate_to_mat4 (COLLADAFW::Transformation * tm, float m[][4])
Definition at line 91 of file TransformReader.cpp.
References Translate, and unit_m4().
Referenced by AnimationImporter::evaluate_transform_at_frame(), and get_node_mat().
void TransformReader::dae_translate_to_v3 (COLLADAFW::Transformation * tm, float v[3])
Definition at line 115 of file TransformReader.cpp.
References dae_vector3_to_v3(), and Translate.
Referenced by AnimationImporter::evaluate_animation().
void TransformReader::dae_vector3_to_v3 (const COLLADABU::Math::Vector3 & v3, float v[3])
Definition at line 125 of file TransformReader.cpp.
Referenced by dae_scale_to_v3(), and dae_translate_to_v3().
void TransformReader::get_node_mat (float mat[][4], COLLADAFW::Node * node, std::map< COLLADAFW::UniqueId, Animation > * animation_map, Object * ob)
Definition at line 34 of file TransformReader.cpp.
References copy(), copy_m4_m4(), dae_matrix_to_mat4(), dae_rotate_to_mat4(), dae_scale_to_mat4(), dae_translate_to_mat4(), i, mult_m4_m4m4(), ROTATE, SCALE, TRANSLATE, and unit_m4().
Referenced by AnimationImporter::calc_joint_parent_mat_rest(), AnimationImporter::get_joint_rest_mat(), and AnimationImporter::read_node_transform().
Member Data Documentation
UnitConverter* TransformReader::unit_converter [protected]
Definition at line 50 of file TransformReader.h.
Referenced by dae_matrix_to_mat4().
The documentation for this class was generated from the following files:
TransformReader.h
TransformReader.cpp