Blender: BLI_voxel.h File Reference
BLI_voxel.h File Reference
blenlib
Defines
#define V_I(x, y, z, res) ((z)*(res)[1]*(res)[0] + (y)*(res)[0] + (x))
Functions
float voxel_sample_nearest (float *data, const int res[3], const float co[3])
float voxel_sample_trilinear (float *data, const int res[3], const float co[3])
float voxel_sample_triquadratic (float *data, const int res[3], const float co[3])
float voxel_sample_tricubic (float *data, const int res[3], const float co[3], int bspline)
Detailed Description
Definition in file BLI_voxel.h.
Define Documentation
#define V_I (x, y, z, res) ((z)*(res)[1]*(res)[0] + (y)*(res)[0] + (x))
find the index number of a voxel, given x/y/z integer coords and resolution vector
Definition at line 36 of file BLI_voxel.h.
Referenced by D(), get_avg_surrounds(), lightcache_filter(), load_frame_image_sequence(), total_ss_energy(), and vol_precache_part().
Function Documentation
float voxel_sample_nearest (float * data, const int res[3], const float co[3])
Definition at line 48 of file voxel.c.
References D().
Referenced by voxeldatatex().
float voxel_sample_tricubic (float * data, const int res[3], const float co[3], int bspline)
Definition at line 135 of file voxel.c.
References _clamp(), FLOORI(), and ShadeResult::z.
Referenced by voxeldatatex().
float voxel_sample_trilinear (float * data, const int res[3], const float co[3])
Definition at line 73 of file voxel.c.
References _clamp(), FLOORI(), and ShadeResult::z.
Referenced by voxeldatatex().
float voxel_sample_triquadratic (float * data, const int res[3], const float co[3])
Definition at line 105 of file voxel.c.
References _clamp(), FLOORI(), and ShadeResult::z.
Referenced by vol_get_precached_scattering(), and voxeldatatex().