Blender: Basic.c File Reference
Basic.c File Reference
#include "Basic.h"
Functions
int min_i (int a, int b)
int max_i (int a, int b)
int clamp_i (int val, int min, int max)
float min_f (float a, float b)
float max_f (float a, float b)
float clamp_f (float val, float min, float max)
void rect_copy (int dst[2][2], int src[2][2])
int rect_contains_pt (int rect[2][2], int pt[2])
int rect_width (int rect[2][2])
int rect_height (int rect[2][2])
Function Documentation
float clamp_f (float val, float min, float max)
Definition at line 46 of file Basic.c.
References max_f(), and min_f().
Referenced by scrollbar_keep_scrolling(), scrollbar_set_thumbpos(), and scrollbar_start_scrolling().
int clamp_i (int val, int min, int max)
Definition at line 36 of file Basic.c.
References max_i(), and min_i().
Referenced by scrollbar_get_thumbH().
float max_f (float a, float b)
Definition at line 43 of file Basic.c.
Referenced by clamp_f().
int max_i (int a, int b)
Definition at line 33 of file Basic.c.
Referenced by clamp_i(), and sk_filterStroke().
float min_f (float a, float b)
Definition at line 40 of file Basic.c.
Referenced by clamp_f().
int min_i (int a, int b)
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) 2001-2002 by NaN Holding BV. All rights reserved.
The Original Code is: all of this file.
Contributor(s): none yet.
***** END GPL LICENSE BLOCK *****
Definition at line 30 of file Basic.c.
Referenced by clamp_i(), and loggerwindow_do_draw().
int rect_contains_pt (int rect[2][2], int pt[2])
Definition at line 54 of file Basic.c.
Referenced by scrollbar_contains_pt().
void rect_copy (int dst[2][2], int src[2][2])
Definition at line 50 of file Basic.c.
Referenced by scrollbar_get_rect(), and scrollbar_set_rect().
int rect_height (int rect[2][2])
Definition at line 61 of file Basic.c.
Referenced by loggerwindow_new(), scrollbar_get_thumbableH(), and scrollbar_get_thumbH().
int rect_width (int rect[2][2])
Definition at line 58 of file Basic.c.