Blender: svm_sky.h File Reference
svm_sky.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device float3 xyY_to_xyz (float x, float y, float Y)
__device float3 xyz_to_rgb (float x, float y, float z)
__device float sky_angle_between (float thetav, float phiv, float theta, float phi)
__device float sky_perez_function (__constant float *lam, float theta, float gamma)
__device float3 sky_radiance (KernelGlobals *kg, float3 dir)
__device void svm_node_tex_sky (KernelGlobals *kg, ShaderData *sd, float *stack, uint dir_offset, uint out_offset)
Function Documentation
__device float sky_angle_between (float thetav, float phiv, float theta, float phi)
Definition at line 46 of file svm_sky.h.
References cosf, safe_acosf(), and sinf.
Referenced by sky_radiance().
__device float sky_perez_function (__constant float * lam, float theta, float gamma)
Definition at line 52 of file svm_sky.h.
References cosf, and expf.
Referenced by sky_radiance(), and sky_texture_precompute().
__device float3 sky_radiance (KernelGlobals * kg, float3 dir)
Definition at line 60 of file svm_sky.h.
References direction_to_spherical(), kernel_data, M_PI_2_F, min, sky_angle_between(), sky_perez_function(), float3::x, float2::x, xyY_to_xyz(), xyz_to_rgb(), float3::y, float2::y, and float3::z.
Referenced by svm_node_tex_sky().
__device void svm_node_tex_sky (KernelGlobals * kg, ShaderData * sd, float * stack, uint dir_offset, uint out_offset)
Definition at line 83 of file svm_sky.h.
References sky_radiance(), stack_load_float3(), and stack_store_float3().
Referenced by svm_eval_nodes().
CCL_NAMESPACE_BEGIN __device float3 xyY_to_xyz (float x, float y, float Y)
Definition at line 21 of file svm_sky.h.
References make_float3(), and X.
Referenced by sky_radiance().
__device float3 xyz_to_rgb (float x, float y, float z)
Definition at line 34 of file svm_sky.h.
References make_float3().