Blender: BL_System.h File Reference
BL_System.h File Reference
Blender Routines
Typedefs
typedef void * SYS_SystemHandle
Functions
SYS_SystemHandle SYS_GetSystem (void)
void SYS_DeleteSystem (SYS_SystemHandle sys)
int SYS_GetCommandLineInt (SYS_SystemHandle sys, const char *paramname, int defaultvalue)
float SYS_GetCommandLineFloat (SYS_SystemHandle sys, const char *paramname, float defaultvalue)
const char * SYS_GetCommandLineString (SYS_SystemHandle sys, const char *paramname, const char *defaultvalue)
void SYS_WriteCommandLineInt (SYS_SystemHandle sys, const char *paramname, int value)
void SYS_WriteCommandLineFloat (SYS_SystemHandle sys, const char *paramname, float value)
void SYS_WriteCommandLineString (SYS_SystemHandle sys, const char *paramname, const char *value)
void StartKetsjiShell (struct bContext *C, struct ARegion *ar, struct rcti *cam_frame, int always_use_expand_framing)
Detailed Description
Definition in file BL_System.h.
Typedef Documentation
typedef void* SYS_SystemHandle
Definition at line 43 of file BL_System.h.
Function Documentation
void StartKetsjiShell (struct bContext * C, struct ARegion * ar, struct rcti * cam_frame, int always_use_expand_framing)
Definition at line 129 of file BL_KetsjiEmbedStart.cpp.
References KX_ISceneConverter::addInitFromFrame, KX_KetsjiEngine::AddScene(), GameDome::angle, AUD_get3DDevice(), AUD_getDevice(), Scene::audio, BKE_screen_view3d_zoom_to_fac(), BLI_findstring(), BLI_path_abs(), BLI_remlink(), BLI_strncpy(), BLO_blendfiledata_free(), View3D::camera, Scene::camera, RegionView3D::camzoom, RenderData::cfra, GameFraming::col, KX_BlenderKeyboardDevice::ConvertBlenderEvent(), KX_BlenderMouseDevice::ConvertBlenderEvent(), ConvertKeyCode(), KX_ISceneConverter::ConvertScene(), CTX_data_main(), CTX_data_scene(), CTX_wm_region_view3d(), CTX_wm_view3d(), CTX_wm_window(), BlendFileData::curscene, NG_NetworkDeviceInterface::Disconnect(), AudioData::distance_model, do_versions_ipos_to_animato(), GameData::dome, AudioData::doppler_factor, View3D::drawtype, KX_KetsjiEngine::EnableCameraOverride(), GameData::exitkey, GameData::eyeseparation, View3D::far, FILE_MAX, FILE_MAXDIR, FILE_MAXFILE, ListBase::first, GameData::flag, FPS, GameData::framing, G, GAME_MAT_GLSL, GAME_MAT_TEXFACE, GAME_RESTRICT_ANIM_UPDATES, GAME_SHOW_MOUSE, KX_KetsjiEngine::GetExitCode(), KX_KetsjiEngine::GetExitString(), KX_KetsjiEngine::GetGlobalSettings(), GlobalSettings::glslflag, Scene::gm, GPU_glsl_support(), Scene::id, RAS_IRasterizer::Init(), KX_KetsjiEngine::InitDome(), bgl::InitExtensions(), KX_EXIT_REQUEST_BLENDER_ESC, KX_EXIT_REQUEST_NO_REQUEST, KX_EXIT_REQUEST_OUTSIDE, KX_EXIT_REQUEST_QUIT_GAME, KX_EXIT_REQUEST_RESTART_GAME, KX_EXIT_REQUEST_START_OTHER_GAME, View3D::lay, Scene::lay, View3D::lens, load_game_data(), BlendFileData::main, GlobalSettings::matmode, GameData::matmode, GameDome::mode, RAS_ICanvas::MOUSE_INVISIBLE, RAS_ICanvas::MOUSE_NORMAL, MOUSEMOVE, MOUSEX, MOUSEY, Main::name, ID::name, View3D::near, KX_KetsjiEngine::NextFrame(), NULL, RegionView3D::persp, STR_String::Ptr(), wmWindow::queue, Scene::r, RAS_IRasterizer::RAS_STEREO_QUADBUFFERED, KX_KetsjiEngine::Render(), GameDome::res, GameDome::resbuf, RV3D_CAMOB, RV3D_ORTHO, SCE_GAMEFRAMING_BARS, Main::scene, View3D::scenelock, KX_ISceneConverter::SetAlwaysUseExpandFraming(), KX_KetsjiEngine::SetAnimFrameRate(), KX_KetsjiEngine::SetAnimRecordMode(), RAS_IRasterizer::SetBackColor(), RAS_Rect::SetBottom(), KX_KetsjiEngine::SetCameraOverrideClipping(), KX_KetsjiEngine::SetCameraOverrideLens(), KX_KetsjiEngine::SetCameraOverrideProjectionMatrix(), KX_KetsjiEngine::SetCameraOverrideUseOrtho(), KX_KetsjiEngine::SetCameraOverrideViewMatrix(), KX_KetsjiEngine::SetCameraZoom(), KX_KetsjiEngine::SetCanvas(), AUD_I3DDevice::setDistanceModel(), AUD_I3DDevice::setDopplerFactor(), KX_KetsjiEngine::SetDrawType(), KX_KetsjiEngine::SetExitKey(), RAS_IRasterizer::SetEyeSeparation(), KX_KetsjiEngine::SetGlobalSettings(), KX_ISceneConverter::SetGLSLMaterials(), KX_KetsjiEngine::SetKeyboardDevice(), RAS_Rect::SetLeft(), KX_ISceneConverter::SetMaterials(), KX_KetsjiEngine::SetMouseDevice(), RAS_ICanvas::SetMouseState(), KX_KetsjiEngine::SetNetworkDevice(), KX_KetsjiEngine::SetRasterizer(), KX_KetsjiEngine::SetRenderTools(), KX_KetsjiEngine::SetRestrictAnimationFPS(), RAS_Rect::SetRight(), KX_KetsjiEngine::SetSceneConverter(), AUD_I3DDevice::setSpeedOfSound(), RAS_IRasterizer::SetStereoMode(), KX_KetsjiEngine::SetTimingDisplay(), RAS_Rect::SetTop(), KX_KetsjiEngine::SetUseFixedTime(), AudioData::speed_of_sound, KX_KetsjiEngine::StartEngine(), STEREO_DOME, STEREO_ENABLED, GameData::stereoflag, GameData::stereomode, KX_KetsjiEngine::StopEngine(), SYS_GetCommandLineInt(), SYS_GetSystem(), GameDome::tilt, GameFraming::type, USER_DISABLE_VBO, Main::versionfile, RegionView3D::viewmat, GameDome::warptext, RegionView3D::winmat, ARegion::winrct, ARegion::winy, wm_event_free(), wm_window_process_events_nosleep(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by game_engine_exec().
void SYS_DeleteSystem (SYS_SystemHandle sys)
Definition at line 53 of file BL_System.cpp.
References _system_instance, and NULL.
Referenced by main(), and WM_exit_ext().
float SYS_GetCommandLineFloat (SYS_SystemHandle sys, const char * paramname, float defaultvalue)
Definition at line 70 of file BL_System.cpp.
int SYS_GetCommandLineInt (SYS_SystemHandle sys, const char * paramname, int defaultvalue)
Definition at line 61 of file BL_System.cpp.
Referenced by KX_BlenderSceneConverter::ConvertScene(), GPG_Application::initEngine(), KX_Scene::KX_Scene(), main(), and StartKetsjiShell().
const char* SYS_GetCommandLineString (SYS_SystemHandle sys, const char * paramname, const char * defaultvalue)
Definition at line 79 of file BL_System.cpp.
SYS_SystemHandle SYS_GetSystem (void)
Definition at line 45 of file BL_System.cpp.
References _system_instance.
Referenced by KX_BlenderSceneConverter::ConvertScene(), GPG_Application::initEngine(), KX_Scene::KX_Scene(), main(), StartKetsjiShell(), and WM_exit_ext().
void SYS_WriteCommandLineFloat (SYS_SystemHandle sys, const char * paramname, float value)
Definition at line 93 of file BL_System.cpp.
Referenced by main().
void SYS_WriteCommandLineInt (SYS_SystemHandle sys, const char * paramname, int value)
Definition at line 88 of file BL_System.cpp.
Referenced by GPG_Application::initEngine(), main(), no_joystick(), and set_ge_parameters().
void SYS_WriteCommandLineString (SYS_SystemHandle sys, const char * paramname, const char * value)
Definition at line 98 of file BL_System.cpp.
Referenced by main(), and set_ge_parameters().