Blender: ED_image.h File Reference
ED_image.h File Reference
Editors
Functions
struct Image * ED_space_image (struct SpaceImage *sima)
void ED_space_image_set (struct SpaceImage *sima, struct Scene *scene, struct Object *obedit, struct Image *ima)
struct ImBuf * ED_space_image_acquire_buffer (struct SpaceImage *sima, void **lock_r)
void ED_space_image_release_buffer (struct SpaceImage *sima, void *lock)
int ED_space_image_has_buffer (struct SpaceImage *sima)
void ED_space_image_size (struct SpaceImage *sima, int *width, int *height)
void ED_space_image_aspect (struct SpaceImage *sima, float *aspx, float *aspy)
void ED_space_image_zoom (struct SpaceImage *sima, struct ARegion *ar, float *zoomx, float *zoomy)
void ED_space_image_uv_aspect (struct SpaceImage *sima, float *aspx, float *aspy)
void ED_space_image_paint_update (struct wmWindowManager *wm, struct ToolSettings *settings)
void ED_space_image_uv_sculpt_update (struct wmWindowManager *wm, struct ToolSettings *settings)
void ED_image_size (struct Image *ima, int *width, int *height)
void ED_image_aspect (struct Image *ima, float *aspx, float *aspy)
void ED_image_uv_aspect (struct Image *ima, float *aspx, float *aspy)
int ED_space_image_show_render (struct SpaceImage *sima)
int ED_space_image_show_paint (struct SpaceImage *sima)
int ED_space_image_show_uvedit (struct SpaceImage *sima, struct Object *obedit)
int ED_space_image_show_uvshadow (struct SpaceImage *sima, struct Object *obedit)
void ED_image_update_frame (const struct Main *mainp, int cfra)
void ED_image_draw_info (struct ARegion *ar, int color_manage, int channels, int x, int y, const unsigned char cp[4], const float fp[4], int *zp, float *zpf)
Detailed Description
Definition in file ED_image.h.
Function Documentation
void ED_image_aspect (struct Image * ima, float * aspx, float * aspy)
Definition at line 202 of file space_image.c.
References Image::aspx, Image::aspy, IMA_TYPE_COMPOSITE, IMA_TYPE_R_RESULT, NULL, and Image::type.
Referenced by draw_image_main(), ED_image_uv_aspect(), ED_space_image_aspect(), and image_view_selected_exec().
void ED_image_draw_info (struct ARegion * ar, int color_manage, int channels, int x, int y, const unsigned char cp[4], const float fp[4], int * zp, float * zpf)
Definition at line 114 of file image_draw.c.
References BLF_draw_ascii(), blf_mono_font, BLF_position(), BLF_size(), BLF_width(), BLI_assert, BLI_snprintf(), copy_v3_v3(), copy_v4_v4(), linearrgb_to_srgb_v4(), rgb_to_hsv(), rgb_to_yuv(), rgb_uchar_to_float(), rgba_uchar_to_float(), str, ARegion::winrct, rcti::xmax, rcti::xmin, zero_v3(), and zero_v4().
Referenced by image_sample_draw(), and sample_draw().
void ED_image_size (struct Image * ima, int * width, int * height)
Definition at line 148 of file space_image.c.
References BKE_image_acquire_ibuf(), BKE_image_release_ibuf(), NULL, ImBuf::x, and ImBuf::y.
Referenced by ED_image_uv_aspect().
void ED_image_update_frame (const struct Main * mainp, int cfra)
Referenced by ED_update_for_newframe(), and screen_opengl_render_anim_step().
void ED_image_uv_aspect (struct Image * ima, float * aspx, float * aspy)
Definition at line 249 of file space_image.c.
References ED_image_aspect(), and ED_image_size().
Referenced by construct_param_handle(), construct_param_handle_subsurfed(), and correct_uv_aspect().
struct Image* ED_space_image (struct SpaceImage * sima) [read]
Definition at line 80 of file space_image.c.
References SpaceImage::image.
Referenced by CalcSnapGeometry(), draw_image_main(), draw_uvs_texpaint(), ED_space_image_aspect(), image_context(), image_main_area_set_view2d(), image_refresh(), image_save_as_invoke(), image_view_selected_exec(), and save_image_doit().
struct ImBuf* ED_space_image_acquire_buffer (struct SpaceImage * sima, void ** lock_r) [read]
Definition at line 110 of file space_image.c.
References BKE_image_acquire_ibuf(), IMA_TYPE_R_RESULT, SpaceImage::image, SpaceImage::iuser, NULL, ImBuf::rect, ImBuf::rect_float, and Image::type.
Referenced by draw_image_grease_pencil(), draw_image_main(), ED_space_image_has_buffer(), ED_space_image_size(), image_panel_curves(), image_panel_poll(), image_sample_apply(), image_sample_line_exec(), image_scope_area_draw(), save_image_doit(), save_image_options_init(), and space_image_file_exists_poll().
void ED_space_image_aspect (struct SpaceImage * sima, float * aspx, float * aspy)
Definition at line 214 of file space_image.c.
References ED_image_aspect(), and ED_space_image().
Referenced by drawSnapping(), ED_space_image_uv_aspect(), image_view_all_exec(), and sima_zoom_set().
int ED_space_image_has_buffer (struct SpaceImage * sima)
Definition at line 135 of file space_image.c.
References ED_space_image_acquire_buffer(), ED_space_image_release_buffer(), and NULL.
Referenced by image_sample_invoke(), image_sample_line_invoke(), and space_image_buffer_exists_poll().
void ED_space_image_paint_update (struct wmWindowManager * wm, struct ToolSettings * settings)
Definition at line 5278 of file paint_image.c.
References brush_drawcursor(), image_paint_poll(), ToolSettings::imapaint, NULL, ImagePaintSettings::paintcursor, and WM_paint_cursor_activate().
void ED_space_image_release_buffer (struct SpaceImage * sima, void * lock)
Definition at line 129 of file space_image.c.
References BKE_image_release_ibuf(), and SpaceImage::image.
Referenced by draw_image_grease_pencil(), draw_image_main(), ED_space_image_has_buffer(), ED_space_image_size(), image_panel_curves(), image_panel_poll(), image_sample_apply(), image_sample_line_exec(), image_scope_area_draw(), save_image_doit(), save_image_options_init(), and space_image_file_exists_poll().
void ED_space_image_set (struct SpaceImage * sima, struct Scene * scene, struct Object * obedit, struct Image * ima)
Definition at line 86 of file space_image.c.
References BKE_image_signal(), Object::data, ED_uvedit_assign_image(), SpaceImage::flag, G, Image::id, IMA_SIGNAL_USER_NEW_IMAGE, IMA_TYPE_COMPOSITE, IMA_TYPE_R_RESULT, SpaceImage::image, SpaceImage::iuser, NC_GEOM, NC_SPACE, ND_DATA, ND_SPACE_IMAGE, NULL, SI_DRAWTOOL, Image::type, ID::us, and WM_main_add_notifier().
Referenced by image_new_exec(), and image_open_exec().
int ED_space_image_show_paint (struct SpaceImage * sima)
Definition at line 265 of file space_image.c.
References ED_space_image_show_render(), SpaceImage::flag, and SI_DRAWTOOL.
Referenced by ED_space_image_show_uvedit(), and ED_space_image_show_uvshadow().
int ED_space_image_show_render (struct SpaceImage * sima)
Definition at line 260 of file space_image.c.
References ELEM, IMA_TYPE_COMPOSITE, IMA_TYPE_R_RESULT, SpaceImage::image, and Image::type.
Referenced by ED_space_image_show_paint(), ED_space_image_show_uvedit(), ED_space_image_show_uvshadow(), and image_listener().
int ED_space_image_show_uvedit (struct SpaceImage * sima, struct Object * obedit)
Definition at line 273 of file space_image.c.
References BMEdit_FromObject(), ED_space_image_show_paint(), ED_space_image_show_render(), EDBM_mtexpoly_check(), OB_MESH, and Object::type.
Referenced by createTransUVs(), draw_uvedit_main(), ED_operator_uvedit(), ED_operator_uvedit_can_uv_sculpt(), and space_image_image_sample_poll().
int ED_space_image_show_uvshadow (struct SpaceImage * sima, struct Object * obedit)
Definition at line 290 of file space_image.c.
References BMEdit_FromObject(), ED_space_image_show_paint(), ED_space_image_show_render(), EDBM_mtexpoly_check(), OB_MESH, and Object::type.
Referenced by draw_uvedit_main().
void ED_space_image_size (struct SpaceImage * sima, int * width, int * height)
Definition at line 169 of file space_image.c.
References RenderData::border, ED_space_image_acquire_buffer(), ED_space_image_release_buffer(), IMA_TYPE_R_RESULT, SpaceImage::image, SpaceImage::iuser, RenderData::mode, Scene::r, R_BORDER, R_CROP, ImageUser::scene, RenderData::size, Image::type, ImBuf::x, rctf::xmax, rctf::xmin, RenderData::xsch, ImBuf::y, rctf::ymax, rctf::ymin, and RenderData::ysch.
Referenced by applyAspectRatio(), circle_select_exec(), do_uvedit_vertex(), drawcursor_sima(), ED_space_image_uv_aspect(), ED_space_image_zoom(), flushTransUVs(), image_main_area_set_view2d(), image_view_all_exec(), image_view_selected_exec(), removeAspectRatio(), sima_zoom_set(), snap_cursor_to_pixels(), snap_uvs_to_pixels(), uv_sculpt_stroke_apply(), uv_sculpt_stroke_init(), uvedit_pixel_to_float(), and uvedit_vertex_buttons().
void ED_space_image_uv_aspect (struct SpaceImage * sima, float * aspx, float * aspy)
Definition at line 229 of file space_image.c.
References ED_space_image_aspect(), and ED_space_image_size().
Referenced by applyAspectRatio(), applyGrid(), CalcSnapGeometry(), calculateCenterCursor2D(), clipUVTransform(), convertViewVec(), draw_uvs_stretch(), drawPropCircle(), flushTransUVs(), projectIntView(), removeAspectRatio(), and UVsToTransData().
void ED_space_image_uv_sculpt_update (struct wmWindowManager * wm, struct ToolSettings * settings)
Definition at line 5290 of file paint_image.c.
References brush_drawcursor(), Paint::flags, MEM_callocN(), NULL, UvSculpt::paint, PAINT_CURSOR_SCULPT, paint_init(), PAINT_SHOW_BRUSH, ToolSettings::use_uv_sculpt, ToolSettings::uv_relax_method, UV_SCULPT_ALL_ISLANDS, uv_sculpt_brush_poll(), UV_SCULPT_LOCK_BORDERS, ToolSettings::uv_sculpt_settings, ToolSettings::uv_sculpt_tool, UV_SCULPT_TOOL_GRAB, UV_SCULPT_TOOL_RELAX_LAPLACIAN, ToolSettings::uvsculpt, and WM_paint_cursor_activate().
Referenced by editmode_toggle_exec().
void ED_space_image_zoom (struct SpaceImage * sima, struct ARegion * ar, float * zoomx, float * zoomy)
Definition at line 219 of file space_image.c.
References View2D::cur, ED_space_image_size(), ARegion::v2d, ARegion::winrct, rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, rctf::ymax, rcti::ymax, rctf::ymin, and rcti::ymin.
Referenced by circle_select_exec(), draw_image_main(), drawcursor_sima(), get_imapaint_zoom(), uv_sculpt_stroke_apply(), and uv_sculpt_stroke_init().