Blender: node_composite_stabilize2d.c File Reference
node_composite_stabilize2d.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void node_composit_exec_stabilize2d (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_stabilize2d (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_stabilize2d_in []
static bNodeSocketTemplate cmp_node_stabilize2d_out []
Detailed Description
Definition in file node_composite_stabilize2d.c.
Function Documentation
static void node_composit_exec_stabilize2d (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 48 of file node_composite_stabilize2d.c.
References angle(), BKE_tracking_stabilization_data(), CB_RGBA, RenderData::cfra, bNode::custom1, bNodeStack::data, data, free_compbuf(), bNode::id, node_composit_transform(), MovieClip::tracking, and typecheck_compbuf().
Referenced by register_node_type_cmp_stabilize2d().
void register_node_type_cmp_stabilize2d (bNodeTreeType * ttype)
Definition at line 69 of file node_composite_stabilize2d.c.
References CMP_NODE_STABILIZE2D, NODE_CLASS_DISTORT, node_composit_exec_stabilize2d(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_stabilize2d_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          0.8f, 0.8f, 0.8f, 1.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 38 of file node_composite_stabilize2d.c.
bNodeSocketTemplate cmp_node_stabilize2d_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 43 of file node_composite_stabilize2d.c.