Blender: space_time.c File Reference
space_time.c File Reference
time line
#include <string.h>
#include <stdio.h>
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_dlrbTree.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_screen.h"
#include "BKE_pointcache.h"
#include "ED_anim_api.h"
#include "ED_keyframes_draw.h"
#include "ED_screen.h"
#include "WM_api.h"
#include "WM_types.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "ED_space_api.h"
#include "ED_markers.h"
#include "time_intern.h"
Defines
#define CACHE_DRAW_HEIGHT 3.0f
Functions
static void time_draw_sfra_efra (Scene *scene, View2D *v2d)
static void time_draw_cache (SpaceTime *stime, Object *ob)
static void time_cache_free (SpaceTime *stime)
static void time_cache_refresh (SpaceTime *stime)
static ActKeyColumn * time_cfra_find_ak (ActKeyColumn *ak, float cframe)
static void time_draw_idblock_keyframes (View2D *v2d, ID *id, short onlysel)
static void time_draw_keyframes (const bContext *C, SpaceTime *stime, ARegion *ar)
static void time_refresh (const bContext *UNUSED(C), ScrArea *sa)
static void time_listener (ScrArea *sa, wmNotifier *wmn)
static void time_main_area_init (wmWindowManager *wm, ARegion *ar)
static void time_main_area_draw (const bContext *C, ARegion *ar)
static void time_main_area_listener (ARegion *ar, wmNotifier *wmn)
static void time_header_area_init (wmWindowManager *UNUSED(wm), ARegion *ar)
static void time_header_area_draw (const bContext *C, ARegion *ar)
static void time_header_area_listener (ARegion *ar, wmNotifier *wmn)
static SpaceLink * time_new (const bContext *C)
static void time_free (SpaceLink *sl)
static void time_init (wmWindowManager *UNUSED(wm), ScrArea *sa)
static SpaceLink * time_duplicate (SpaceLink *sl)
void ED_spacetype_time (void)
Detailed Description
Definition in file space_time.c.
Define Documentation
#define CACHE_DRAW_HEIGHT 3.0f
Definition at line 93 of file space_time.c.
Referenced by time_draw_cache().
Function Documentation
void ED_spacetype_time (void)
Definition at line 661 of file space_time.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_ANIMATION, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_MARKERS, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, ARegionType::keymap, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, NULL, SpaceType::operatortypes, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_TIME, SpaceType::spaceid, time_duplicate(), time_free(), time_header_area_draw(), time_header_area_init(), time_header_area_listener(), time_init(), time_keymap(), time_listener(), time_main_area_draw(), time_main_area_init(), time_main_area_listener(), time_new(), time_operatortypes(), and time_refresh().
Referenced by ED_spacetypes_init().
static void time_cache_free (SpaceTime * stime) [static]
Definition at line 239 of file space_time.c.
References SpaceTimeCache::array, BLI_freelistN(), SpaceTime::caches, ListBase::first, MEM_freeN(), SpaceTimeCache::next, and NULL.
Referenced by time_cache_refresh(), time_free(), and time_init().
static void time_cache_refresh (SpaceTime * stime) [static]
Definition at line 253 of file space_time.c.
References time_cache_free().
Referenced by time_refresh().
static ActKeyColumn* time_cfra_find_ak (ActKeyColumn * ak, float cframe) [static]
Definition at line 260 of file space_time.c.
References ActKeyColumn::cfra, ActKeyColumn::left, NULL, and ActKeyColumn::right.
Referenced by time_draw_idblock_keyframes().
static void time_draw_cache (SpaceTime * stime, Object * ob) [static]
Definition at line 95 of file space_time.c.
References SpaceTimeCache::array, BKE_ptcache_ids_from_object(), BLI_addtail(), BLI_assert, BLI_freelistN(), BLI_remlink(), PTCacheID::cache, SpaceTime::cache_display, CACHE_DRAW_HEIGHT, PointCache::cached_frames, SpaceTime::caches, PointCache::endframe, ListBase::first, PointCache::flag, i, len(), MEM_allocN_len(), MEM_callocN(), MEM_freeN(), SpaceTimeCache::next, PTCacheID::next, NULL, PTCACHE_BAKED, PTCACHE_TYPE_CLOTH, PTCACHE_TYPE_DYNAMICPAINT, PTCACHE_TYPE_PARTICLES, PTCACHE_TYPE_SMOKE_DOMAIN, PTCACHE_TYPE_SMOKE_HIGHRES, PTCACHE_TYPE_SOFTBODY, PointCache::startframe, TIME_CACHE_CLOTH, TIME_CACHE_DISPLAY, TIME_CACHE_DYNAMICPAINT, TIME_CACHE_PARTICLES, TIME_CACHE_SMOKE, TIME_CACHE_SOFTBODY, PTCacheID::type, and V2D_SCROLL_HEIGHT.
Referenced by time_main_area_draw().
static void time_draw_idblock_keyframes (View2D * v2d, ID * id, short onlysel) [static]
Definition at line 282 of file space_time.c.
References ADS_FILTER_ONLYSEL, BLI_dlrbTree_free(), BLI_dlrbTree_init(), BLI_dlrbTree_linkedlist_sync(), ActKeyColumn::cfra, View2D::cur, bDopeSheet::filterflag, GS, ID_OB, ID_SCE, ID::name, ActKeyColumn::next, NULL, ob_to_keylist(), DLRBT_Tree::root, scene_to_keylist(), time_cfra_find_ak(), View2D::tot, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by time_draw_keyframes().
static void time_draw_keyframes (const bContext * C, SpaceTime * stime, ARegion * ar) [static]
Definition at line 328 of file space_time.c.
References CTX_data_active_object(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_scene(), SpaceTime::flag, Object::mode, OB_MODE_POSE, time_draw_idblock_keyframes(), TIME_ONLYACTSEL, and ARegion::v2d.
Referenced by time_main_area_draw().
static void time_draw_sfra_efra (Scene * scene, View2D * v2d) [static]
Definition at line 69 of file space_time.c.
References View2D::cur, fdrawline(), PEFRA, PSFRA, TH_BACK, UI_ThemeColorShade(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by time_main_area_draw().
static SpaceLink* time_duplicate (SpaceLink * sl) [static]
Definition at line 649 of file space_time.c.
References SpaceTime::caches, ListBase::first, ListBase::last, MEM_dupallocN(), and NULL.
Referenced by ED_spacetype_time().
static void time_free (SpaceLink * sl) [static]
Definition at line 628 of file space_time.c.
References time_cache_free().
Referenced by ED_spacetype_time().
static void time_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 544 of file space_time.c.
References ED_region_header().
Referenced by ED_spacetype_time().
static void time_header_area_init (wmWindowManager * UNUSEDwm, ARegion * ar) [static]
Definition at line 539 of file space_time.c.
References ED_region_header_init().
Referenced by ED_spacetype_time().
static void time_header_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 549 of file space_time.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NC_SCENE, NC_SCREEN, NC_SPACE, ND_ANIMPLAY, ND_FRAME, ND_FRAME_RANGE, ND_KEYINGSET, ND_OB_SELECT, ND_RENDER_OPTIONS, and ND_SPACE_TIME.
Referenced by ED_spacetype_time().
static void time_init (wmWindowManager * UNUSEDwm, ScrArea * sa) [static]
Definition at line 637 of file space_time.c.
References SpaceTime::cache_display, ListBase::first, ScrArea::spacedata, TIME_CACHE_CLOTH, TIME_CACHE_DISPLAY, TIME_CACHE_DYNAMICPAINT, time_cache_free(), TIME_CACHE_PARTICLES, TIME_CACHE_SMOKE, and TIME_CACHE_SOFTBODY.
Referenced by ED_spacetype_time().
static void time_listener (ScrArea * sa, wmNotifier * wmn) [static]
Definition at line 390 of file space_time.c.
References wmNotifier::category, wmNotifier::data, ED_area_tag_redraw(), ED_area_tag_refresh(), EFRA, ListBase::first, NC_OBJECT, NC_SCENE, NC_SPACE, NC_WM, ND_BONE_ACTIVE, ND_FILEREAD, ND_FRAME, ND_FRAME_RANGE, ND_MODIFIER, ND_OB_ACTIVE, ND_PARTICLE, ND_POINTCACHE, ND_SPACE_CHANGED, ARegion::next, wmNotifier::reference, ScrArea::regionbase, ARegion::regiontype, RGN_TYPE_WINDOW, SFRA, View2D::tot, ARegion::v2d, rctf::xmax, and rctf::xmin.
Referenced by ED_spacetype_time().
static void time_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 456 of file space_time.c.
References ANIM_draw_cfra(), CTX_data_active_object(), CTX_data_scene(), CTX_wm_space_time(), draw_markers_time(), DRAWCFRA_SHOW_NUMBOX, DRAWCFRA_UNIT_SECONDS, DRAWCFRA_WIDE, SpaceTime::flag, TH_BACK, TIME_CFRA_NUM, time_draw_cache(), time_draw_keyframes(), time_draw_sfra_efra(), TIME_DRAWFRAMES, UI_ThemeClearColor(), UI_view2d_grid_calc(), UI_view2d_grid_draw(), UI_view2d_grid_free(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_view_ortho(), UI_view2d_view_orthoSpecial(), UI_view2d_view_restore(), ARegion::v2d, V2D_ARG_DUMMY, V2D_GRID_CLAMP, V2D_UNIT_FRAMES, V2D_UNIT_SECONDS, V2D_VERTICAL_AXIS, V2D_VERTICAL_LINES, ARegion::winx, and ARegion::winy.
Referenced by ED_spacetype_time().
static void time_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 445 of file space_time.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, SPACE_TIME, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_CUSTOM, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_time().
static void time_main_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 509 of file space_time.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NC_ANIMATION, NC_SCENE, NC_SPACE, ND_FRAME, ND_FRAME_RANGE, ND_KEYINGSET, ND_OB_ACTIVE, ND_OB_SELECT, ND_RENDER_OPTIONS, and ND_SPACE_TIME.
Referenced by ED_spacetype_time().
static SpaceLink* time_new (const bContext * C) [static]
Definition at line 578 of file space_time.c.
References View2D::align, ARegion::alignment, BLI_addtail(), CTX_data_scene(), View2D::cur, EFRA, SpaceTime::flag, View2D::keepofs, View2D::keepzoom, View2D::max, MAXFRAMEF, View2D::maxzoom, MEM_callocN(), View2D::min, View2D::minzoom, SpaceTime::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, View2D::scroll, SFRA, SPACE_TIME, SpaceTime::spacetype, TIME_DRAWFRAMES, View2D::tot, ARegion::v2d, V2D_ALIGN_NO_NEG_Y, V2D_LOCKOFS_Y, V2D_LOCKZOOM_Y, V2D_SCROLL_BOTTOM, V2D_SCROLL_SCALE_HORIZONTAL, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by ED_spacetype_time().
static void time_refresh (const bContext * UNUSEDC, ScrArea * sa) [static]
Definition at line 379 of file space_time.c.
References BKE_area_find_region_type(), ListBase::first, RGN_TYPE_WINDOW, ScrArea::spacedata, and time_cache_refresh().
Referenced by ED_spacetype_time().