Blender: mesh_validate.c File Reference
mesh_validate.c File Reference
blenkernel
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "BLO_sys_types.h"
#include "BLI_edgehash.h"
#include "BLI_math_base.h"
#include "BLI_utildefines.h"
#include "BKE_deform.h"
#include "BKE_depsgraph.h"
#include "BKE_DerivedMesh.h"
#include "BKE_mesh.h"
#include "MEM_guardedalloc.h"
Classes
struct SortPoly
Defines
#define SELECT 1
#define PRINT if (do_verbose) printf
#define REMOVE_EDGE_TAG(_me) { _me->v2 = _me->v1; do_edge_free = TRUE; }
#define IS_REMOVED_EDGE(_me) (_me->v2 == _me->v1)
#define REMOVE_LOOP_TAG(_ml) { _ml->e = INVALID_LOOP_EDGE_MARKER; do_polyloop_free = TRUE; }
#define REMOVE_POLY_TAG(_mp) { _mp->totloop *= -1; do_polyloop_free = TRUE; }
Typedefs
typedef struct SortPoly SortPoly
Functions
static int int_cmp (const void *v1, const void *v2)
static int search_poly_cmp (const void *v1, const void *v2)
static int search_polyloop_cmp (const void *v1, const void *v2)
int BKE_mesh_validate_arrays (Mesh *mesh, MVert *mverts, unsigned int totvert, MEdge *medges, unsigned int totedge, MLoop *mloops, unsigned int totloop, MPoly *mpolys, unsigned int totpoly, MDeformVert *dverts, const short do_verbose, const short do_fixes)
static int mesh_validate_customdata (CustomData *data, short do_verbose, const short do_fixes)
static int BKE_mesh_validate_all_customdata (CustomData *vdata, CustomData *edata, CustomData *ldata, CustomData *pdata, short do_verbose, const short do_fixes)
int BKE_mesh_validate (Mesh *me, int do_verbose)
int BKE_mesh_validate_dm (DerivedMesh *dm)
void BKE_mesh_calc_edges (Mesh *mesh, int update)
Detailed Description
Definition in file mesh_validate.c.
Define Documentation
#define IS_REMOVED_EDGE (_me) (_me->v2 == _me->v1)
Referenced by BKE_mesh_validate_arrays().
#define PRINT if (do_verbose) printf
Definition at line 96 of file mesh_validate.c.
Referenced by BKE_mesh_validate_arrays(), and mesh_validate_customdata().
#define REMOVE_EDGE_TAG (_me) { _me->v2 = _me->v1; do_edge_free = TRUE; }
Referenced by BKE_mesh_validate_arrays().
#define REMOVE_LOOP_TAG (_ml) { _ml->e = INVALID_LOOP_EDGE_MARKER; do_polyloop_free = TRUE; }
Referenced by BKE_mesh_validate_arrays().
#define REMOVE_POLY_TAG (_mp) { _mp->totloop *= -1; do_polyloop_free = TRUE; }
Referenced by BKE_mesh_validate_arrays().
#define SELECT 1
Definition at line 51 of file mesh_validate.c.
Referenced by BKE_mesh_calc_edges().
Typedef Documentation
typedef struct SortPoly SortPoly
Function Documentation
void BKE_mesh_calc_edges (Mesh * mesh, int update)
Definition at line 631 of file mesh_validate.c.
References BLI_edgehash_free(), BLI_edgehash_haskey(), BLI_edgehash_insert(), BLI_edgehash_lookup(), BLI_edgehash_new(), BLI_edgehash_size(), BLI_edgehashIterator_free(), BLI_edgehashIterator_getKey(), BLI_edgehashIterator_getValue(), BLI_edgehashIterator_isDone(), BLI_edgehashIterator_new(), BLI_edgehashIterator_setValue(), BLI_edgehashIterator_step(), CD_CALLOC, CD_MEDGE, CustomData_add_layer(), CustomData_free(), CustomData_get_layer(), MLoop::e, FALSE, MEdge::flag, GET_INT_FROM_POINTER, i, MPoly::loopstart, ME_EDGEDRAW, ME_EDGERENDER, Mesh::medge, Mesh::mloop, Mesh::mpoly, NULL, SELECT, SET_INT_IN_POINTER, Mesh::totedge, MPoly::totloop, Mesh::totpoly, MLoop::v, MEdge::v1, and MEdge::v2.
Referenced by BKE_mesh_validate_arrays(), ED_mesh_update(), mball_to_mesh(), and nurbs_to_mesh().
int BKE_mesh_validate (Mesh * me, int do_verbose)
Definition at line 596 of file mesh_validate.c.
References BKE_mesh_validate_all_customdata(), BKE_mesh_validate_arrays(), DAG_id_tag_update(), Mesh::dvert, FALSE, Mesh::id, Mesh::ldata, Mesh::medge, Mesh::mloop, Mesh::mpoly, Mesh::mvert, ID::name, OB_RECALC_DATA, Mesh::totedge, Mesh::totloop, Mesh::totpoly, Mesh::totvert, and TRUE.
static int BKE_mesh_validate_all_customdata (CustomData * vdata, CustomData * edata, CustomData * ldata, CustomData * pdata, short do_verbose, const short do_fixes) [static]
Definition at line 582 of file mesh_validate.c.
References mesh_validate_customdata().
Referenced by BKE_mesh_validate().
int BKE_mesh_validate_arrays (Mesh * mesh, MVert * mverts, unsigned int totvert, MEdge * medges, unsigned int totedge, MLoop * mloops, unsigned int totloop, MPoly * mpolys, unsigned int totpoly, MDeformVert * dverts, const short do_verbose, const short do_fixes)
Definition at line 98 of file mesh_validate.c.
References BKE_mesh_calc_edges(), BLI_assert, BLI_edgehash_free(), BLI_edgehash_haskey(), BLI_edgehash_insert(), BLI_edgehash_lookup(), BLI_edgehash_new(), CLAMP(), MVert::co, MDeformWeight::def_nr, defvert_remove_group(), MDeformVert::dw, MLoop::e, FALSE, MVert::flag, GET_INT_FROM_POINTER, i, if(), SortPoly::index, int_cmp(), SortPoly::invalid, IS_REMOVED_EDGE, SortPoly::loopstart, ME_VERT_TMP_TAG, MEM_callocN(), MEM_freeN(), MEM_mallocN(), mesh_strip_loose_edges(), mesh_strip_loose_polysloops(), MVert::no, NULL, SortPoly::numverts, PRINT, REMOVE_EDGE_TAG, REMOVE_LOOP_TAG, REMOVE_POLY_TAG, search_poly_cmp(), search_polyloop_cmp(), SET_INT_IN_POINTER, TRUE, MLoop::v, MEdge::v1, MEdge::v2, SortPoly::verts, MDeformWeight::weight, and zero_v3().
Referenced by BKE_mesh_validate(), and BKE_mesh_validate_dm().
int BKE_mesh_validate_dm (DerivedMesh * dm)
Definition at line 620 of file mesh_validate.c.
References BKE_mesh_validate_arrays(), CD_MDEFORMVERT, FALSE, DerivedMesh::getEdgeArray, DerivedMesh::getLoopArray, DerivedMesh::getNumEdges, DerivedMesh::getNumLoops, DerivedMesh::getNumPolys, DerivedMesh::getNumVerts, DerivedMesh::getPolyArray, DerivedMesh::getVertArray, DerivedMesh::getVertDataArray, NULL, and TRUE.
static int int_cmp (const void * v1, const void * v2) [static]
Definition at line 64 of file mesh_validate.c.
Referenced by BKE_mesh_validate_arrays().
static int mesh_validate_customdata (CustomData * data, short do_verbose, const short do_fixes) [static]
Definition at line 554 of file mesh_validate.c.
References CD_MASK_MESH, CD_TYPE_AS_MASK, CustomData_free_layer(), i, CustomData::layers, PRINT, and CustomDataLayer::type.
Referenced by BKE_mesh_validate_all_customdata().
static int search_poly_cmp (const void * v1, const void * v2) [static]
Definition at line 69 of file mesh_validate.c.
References SortPoly::invalid, SortPoly::numverts, and SortPoly::verts.
Referenced by BKE_mesh_validate_arrays().
static int search_polyloop_cmp (const void * v1, const void * v2) [static]
Definition at line 85 of file mesh_validate.c.
References SortPoly::invalid, and SortPoly::loopstart.
Referenced by BKE_mesh_validate_arrays().