Blender: collada_utils.cpp File Reference
collada_utils.cpp File Reference
COLLADA
#include "COLLADABUPlatform.h"
#include "COLLADAFWGeometry.h"
#include "COLLADAFWMeshPrimitive.h"
#include "COLLADAFWMeshVertexData.h"
#include "DNA_customdata_types.h"
#include "DNA_object_types.h"
#include "BLI_math.h"
#include "BKE_context.h"
#include "BKE_customdata.h"
#include "BKE_depsgraph.h"
#include "BKE_object.h"
#include "WM_api.h"
#include "WM_types.h"
Functions
float bc_get_float_value (const COLLADAFW::FloatOrDoubleArray &array, unsigned int index)
int bc_test_parent_loop (Object *par, Object *ob)
int bc_set_parent (Object *ob, Object *par, bContext *C, bool is_parent_space)
Detailed Description
Definition in file collada_utils.cpp.
Function Documentation
float bc_get_float_value (const COLLADAFW::FloatOrDoubleArray & array, unsigned int index)
Definition at line 48 of file collada_utils.cpp.
Referenced by SkinInfo::borrow_skin_controller_data().
int bc_set_parent (Object * ob, Object * par, bContext * C, bool is_parent_space)
Definition at line 72 of file collada_utils.cpp.
References bc_test_parent_loop(), copy_m4_m4(), CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), DAG_scene_sort(), invert_m4_m4(), mult_m4_m4m4(), NC_OBJECT, ND_TRANSFORM, NULL, OB_RECALC_DATA, OB_RECALC_OB, object_apply_mat4(), Object::obmat, Object::parent, Object::parentinv, PAROBJECT, Object::parsubstr, Object::partype, Object::recalc, what_does_parent(), where_is_object(), and WM_event_add_notifier().
Referenced by DocumentImporter::create_instance_node(), SkinInfo::link_armature(), ArmatureImporter::make_armatures(), and DocumentImporter::write_node().
int bc_test_parent_loop (Object * par, Object * ob)
Definition at line 60 of file collada_utils.cpp.
References bc_test_parent_loop(), NULL, and Object::parent.
Referenced by bc_set_parent(), and bc_test_parent_loop().