Blender: KX_IpoConvert.cpp File Reference
KX_IpoConvert.cpp File Reference
Converter
#include "BKE_material.h"
#include "KX_GameObject.h"
#include "KX_IpoConvert.h"
#include "KX_IInterpolator.h"
#include "KX_ScalarInterpolator.h"
#include "KX_BlenderScalarInterpolator.h"
#include "KX_BlenderSceneConverter.h"
#include "DNA_object_types.h"
#include "DNA_action_types.h"
#include "DNA_anim_types.h"
#include "DNA_ipo_types.h"
#include "DNA_lamp_types.h"
#include "DNA_world_types.h"
#include "DNA_camera_types.h"
#include "DNA_material_types.h"
#include "KX_IPO_SGController.h"
#include "KX_LightIpoSGController.h"
#include "KX_CameraIpoSGController.h"
#include "KX_WorldIpoController.h"
#include "KX_ObColorIpoSGController.h"
#include "KX_MaterialIpoController.h"
#include "SG_Node.h"
#include "STR_HashedString.h"
Functions
static BL_InterpolatorList * GetAdtList (struct bAction *for_act, KX_BlenderSceneConverter *converter)
SG_Controller * BL_CreateIPO (struct bAction *action, KX_GameObject *gameobj, KX_BlenderSceneConverter *converter)
void BL_ConvertIpos (struct Object *blenderobject, KX_GameObject *gameobj, KX_BlenderSceneConverter *converter)
SG_Controller * BL_CreateLampIPO (struct bAction *action, KX_GameObject *lightobj, KX_BlenderSceneConverter *converter)
void BL_ConvertLampIpos (struct Lamp *blenderlamp, KX_GameObject *lightobj, KX_BlenderSceneConverter *converter)
SG_Controller * BL_CreateCameraIPO (struct bAction *action, KX_GameObject *cameraobj, KX_BlenderSceneConverter *converter)
void BL_ConvertCameraIpos (struct Camera *blendercamera, KX_GameObject *cameraobj, KX_BlenderSceneConverter *converter)
void BL_ConvertWorldIpos (struct World *blenderworld, KX_BlenderSceneConverter *converter)
static void ConvertMaterialIpos (Material *blendermaterial, dword matname_hash, KX_GameObject *gameobj, KX_BlenderSceneConverter *converter)
void BL_ConvertMaterialIpos (struct Object *blenderobject, KX_GameObject *gameobj, KX_BlenderSceneConverter *converter)
Detailed Description
Definition in file KX_IpoConvert.cpp.
Function Documentation
void BL_ConvertCameraIpos (struct Camera * blendercamera, KX_GameObject * cameraobj, KX_BlenderSceneConverter * converter)
Definition at line 289 of file KX_IpoConvert.cpp.
References AnimData::action, SG_IObject::AddSGController(), Camera::adt, BL_CreateCameraIPO(), KX_GameObject::GetSGNode(), and SG_Controller::SetObject().
void BL_ConvertIpos (struct Object * blenderobject, KX_GameObject * gameobj, KX_BlenderSceneConverter * converter)
Definition at line 185 of file KX_IpoConvert.cpp.
References AnimData::action, SG_IObject::AddSGController(), Object::adt, BL_CreateIPO(), KX_GameObject::GetSGNode(), and SG_Controller::SetObject().
void BL_ConvertLampIpos (struct Lamp * blenderlamp, KX_GameObject * lightobj, KX_BlenderSceneConverter * converter)
Definition at line 237 of file KX_IpoConvert.cpp.
References AnimData::action, SG_IObject::AddSGController(), Lamp::adt, BL_CreateLampIPO(), KX_GameObject::GetSGNode(), and SG_Controller::SetObject().
void BL_ConvertMaterialIpos (struct Object * blenderobject, KX_GameObject * gameobj, KX_BlenderSceneConverter * converter)
Definition at line 458 of file KX_IpoConvert.cpp.
References ConvertMaterialIpos(), give_current_material(), STR_HashedString::hash(), Material::id, ID::name, and Object::totcol.
Referenced by bl_ConvertBlenderObject_Single().
void BL_ConvertWorldIpos (struct World * blenderworld, KX_BlenderSceneConverter * converter)
Definition at line 300 of file KX_IpoConvert.cpp.
References AnimData::action, KX_WorldIpoController::AddInterpolator(), World::adt, GetAdtList(), BL_InterpolatorList::GetScalarInterpolator(), World::horb, World::horg, World::horr, i, interp(), KX_WorldIpoController::m_mist_dist, KX_WorldIpoController::m_mist_rgb, KX_WorldIpoController::m_mist_start, World::mistdist, World::miststa, KX_WorldIpoController::SetModifyMistColor(), KX_WorldIpoController::SetModifyMistDist(), and KX_WorldIpoController::SetModifyMistStart().
SG_Controller* BL_CreateCameraIPO (struct bAction * action, KX_GameObject * cameraobj, KX_BlenderSceneConverter * converter)
Definition at line 250 of file KX_IpoConvert.cpp.
References KX_CameraIpoSGController::AddInterpolator(), Camera::clipend, Camera::clipsta, Object::data, GetAdtList(), KX_GameObject::GetBlenderObject(), BL_InterpolatorList::GetScalarInterpolator(), interp(), Camera::lens, KX_CameraIpoSGController::m_clipend, KX_CameraIpoSGController::m_clipstart, KX_CameraIpoSGController::m_lens, KX_CameraIpoSGController::SetModifyClipEnd(), KX_CameraIpoSGController::SetModifyClipStart(), and KX_CameraIpoSGController::SetModifyLens().
Referenced by BL_ConvertCameraIpos(), and BL_Action::Play().
SG_Controller* BL_CreateIPO (struct bAction * action, KX_GameObject * gameobj, KX_BlenderSceneConverter * converter)
Definition at line 87 of file KX_IpoConvert.cpp.
References KX_ObColorIpoSGController::AddInterpolator(), KX_IpoSGController::AddInterpolator(), SG_IObject::AddSGController(), GetAdtList(), KX_GameObject::GetBlenderObject(), KX_IPOTransform::GetDeltaEulerAngles(), KX_IPOTransform::GetDeltaPosition(), KX_IPOTransform::GetDeltaScaling(), KX_IPOTransform::GetEulerAngles(), KX_IpoSGController::GetIPOTransform(), KX_IPOTransform::GetPosition(), BL_InterpolatorList::GetScalarInterpolator(), KX_IPOTransform::GetScaling(), KX_GameObject::GetSGNode(), i, interp(), Object::loc, KX_ObColorIpoSGController::m_rgba, NULL, OB_DLOC_X, OB_DROT_X, OB_DSIZE_X, OB_LOC_X, OB_ROT_X, OB_SIZE_X, Object::rot, ROT_MODE_AXISANGLE, ROT_MODE_QUAT, Object::rotmode, KX_IPOTransform::SetEulerAngles(), KX_IpoSGController::SetGameObject(), KX_IpoSGController::SetIPOChannelActive(), SG_Controller::SetObject(), KX_IPOTransform::SetPosition(), KX_IPOTransform::SetScaling(), and Object::size.
Referenced by BL_ConvertIpos(), and BL_Action::Play().
SG_Controller* BL_CreateLampIPO (struct bAction * action, KX_GameObject * lightobj, KX_BlenderSceneConverter * converter)
Definition at line 194 of file KX_IpoConvert.cpp.
References KX_LightIpoSGController::AddInterpolator(), Lamp::b, Object::data, Lamp::dist, Lamp::energy, Lamp::g, GetAdtList(), KX_GameObject::GetBlenderObject(), BL_InterpolatorList::GetScalarInterpolator(), i, interp(), KX_LightIpoSGController::m_col_rgb, KX_LightIpoSGController::m_dist, KX_LightIpoSGController::m_energy, Lamp::r, KX_LightIpoSGController::SetModifyColor(), KX_LightIpoSGController::SetModifyDist(), and KX_LightIpoSGController::SetModifyEnergy().
Referenced by BL_ConvertLampIpos(), and BL_Action::Play().
static void ConvertMaterialIpos (Material * blendermaterial, dword matname_hash, KX_GameObject * gameobj, KX_BlenderSceneConverter * converter) [static]
Definition at line 348 of file KX_IpoConvert.cpp.
References AnimData::action, KX_MaterialIpoController::AddInterpolator(), SG_IObject::AddSGController(), Material::adt, Material::alpha, Material::b, Material::emit, Material::g, GetAdtList(), BL_InterpolatorList::GetScalarInterpolator(), KX_GameObject::GetSGNode(), Material::har, i, KX_MaterialIpoController::m_alpha, KX_MaterialIpoController::m_emit, KX_MaterialIpoController::m_hard, KX_MaterialIpoController::m_ref, KX_MaterialIpoController::m_rgba, KX_MaterialIpoController::m_spec, KX_MaterialIpoController::m_specrgb, Material::r, Material::ref, SG_Controller::SetObject(), Material::spec, Material::specb, Material::specg, and Material::specr.
Referenced by BL_ConvertMaterialIpos().
static BL_InterpolatorList* GetAdtList (struct bAction * for_act, KX_BlenderSceneConverter * converter) [static]
Definition at line 75 of file KX_IpoConvert.cpp.
References KX_BlenderSceneConverter::FindInterpolatorList(), and KX_BlenderSceneConverter::RegisterInterpolatorList().
Referenced by BL_ConvertWorldIpos(), BL_CreateCameraIPO(), BL_CreateIPO(), BL_CreateLampIPO(), and ConvertMaterialIpos().