Blender: group.c File Reference
group.c File Reference
blenkernel
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "DNA_group_types.h"
#include "DNA_material_types.h"
#include "DNA_object_types.h"
#include "DNA_nla_types.h"
#include "DNA_scene_types.h"
#include "DNA_particle_types.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_global.h"
#include "BKE_group.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_object.h"
#include "BKE_scene.h"
Functions
static void free_group_object (GroupObject *go)
void free_group_objects (Group *group)
void unlink_group (Group *group)
Group * add_group (const char *name)
Group * copy_group (Group *group)
static int add_to_group_internal (Group *group, Object *ob)
int add_to_group (Group *group, Object *object, Scene *scene, Base *base)
static int rem_from_group_internal (Group *group, Object *ob)
int rem_from_group (Group *group, Object *object, Scene *scene, Base *base)
int object_in_group (Object *ob, Group *group)
Group * find_group (Object *ob, Group *group)
void group_tag_recalc (Group *group)
int group_is_animated (Object *UNUSED(parent), Group *group)
void group_handle_recalc_and_update (Scene *scene, Object *UNUSED(parent), Group *group)
Detailed Description
Definition in file group.c.
Function Documentation
Group* add_group (const char * name) [read]
Definition at line 141 of file group.c.
References alloc_libblock(), G, ID_GR, and Group::layer.
Referenced by group_add_exec(), and group_create_exec().
int add_to_group (Group * group, Object * object, Scene * scene, Base * base)
Definition at line 180 of file group.c.
References add_to_group_internal(), Base::flag, Object::flag, NULL, OB_FROMGROUP, and object_in_scene().
Referenced by group_add_exec(), group_create_exec(), group_link_exec(), object_add_duplicate_internal(), and objects_add_active_exec().
static int add_to_group_internal (Group * group, Object * ob) [static]
Definition at line 161 of file group.c.
References BLI_addtail(), ListBase::first, Group::gobject, MEM_callocN(), GroupObject::next, NULL, and GroupObject::ob.
Referenced by add_to_group().
Group* copy_group (Group * group) [read]
Definition at line 150 of file group.c.
References BLI_duplicatelist(), Group::gobject, and MEM_dupallocN().
Referenced by id_copy().
Group* find_group (Object * ob, Group * group) [read]
Definition at line 254 of file group.c.
References G, Group::id, ID::next, NULL, and object_in_group().
Referenced by group_objects_remove_exec(), rem_from_group(), and unlink_group().
static void free_group_object (GroupObject * go) [static]
Definition at line 58 of file group.c.
References MEM_freeN().
Referenced by free_group_objects(), and rem_from_group_internal().
void free_group_objects (Group * group)
Definition at line 64 of file group.c.
References BLI_remlink(), ListBase::first, free_group_object(), and Group::gobject.
Referenced by free_libblock(), and unlink_group().
void group_handle_recalc_and_update (Scene * scene, Object * UNUSEDparent, Group * group)
Definition at line 343 of file group.c.
References RenderData::cfra, ListBase::first, Group::gobject, GroupObject::next, GroupObject::ob, object_handle_update(), Scene::r, Object::recalc, and GroupObject::recalc.
int group_is_animated (Object * UNUSEDparent, Group * group)
Definition at line 281 of file group.c.
References ListBase::first, Group::gobject, GroupObject::next, GroupObject::ob, and Object::proxy.
void group_tag_recalc (Group * group)
Definition at line 269 of file group.c.
References ListBase::first, Group::gobject, GroupObject::next, NULL, GroupObject::ob, Object::recalc, and GroupObject::recalc.
int object_in_group (Object * ob, Group * group)
Definition at line 241 of file group.c.
References ListBase::first, Group::gobject, GroupObject::next, NULL, and GroupObject::ob.
Referenced by animdata_filter_dopesheet(), find_group(), object_add_duplicate_internal(), object_select_same_group_exec(), objects_add_active_exec(), objects_remove_active_exec(), psys_check_group_weights(), and select_grouped_group().
int rem_from_group (Group * group, Object * object, Scene * scene, Base * base)
Definition at line 221 of file group.c.
References find_group(), Base::flag, NULL, OB_FROMGROUP, object_in_scene(), and rem_from_group_internal().
Referenced by group_objects_remove_exec(), group_remove_exec(), lib_link_group(), objects_remove_active_exec(), unlink_group(), and unlink_object().
static int rem_from_group_internal (Group * group, Object * ob) [static]
Definition at line 201 of file group.c.
References BLI_remlink(), ListBase::first, free_group_object(), Group::gobject, GroupObject::next, NULL, and GroupObject::ob.
Referenced by rem_from_group().
void unlink_group (Group * group)
Definition at line 76 of file group.c.
References Scene::base, ParticleSettings::dup_group, Object::dup_group, find_group(), ListBase::first, Base::flag, Object::flag, free_group_objects(), G, Material::group, Group::id, Object::id, Scene::id, Material::id, RenderData::layers, SceneRenderLayer::light_override, Main::mat, ParticleSystem::next, bActionStrip::next, SceneRenderLayer::next, Base::next, ID::next, NULL, OB_FROMGROUP, bActionStrip::object, Main::object, Base::object, ParticleSystem::part, Object::particlesystem, Scene::r, rem_from_group(), Main::scene, and ID::us.
Referenced by id_unlink(), and unlink_group_cb().