Blender: outliner_edit.c File Reference
outliner_edit.c File Reference
outliner space
#include "MEM_guardedalloc.h"
#include "DNA_anim_types.h"
#include "DNA_group_types.h"
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BLF_translation.h"
#include "BKE_animsys.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "ED_object.h"
#include "ED_screen.h"
#include "ED_keyframing.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "outliner_intern.h"
Enumerations
enum { DRIVERS_EDITMODE_ADD = 0, DRIVERS_EDITMODE_REMOVE }
enum { KEYINGSET_EDITMODE_ADD = 0, KEYINGSET_EDITMODE_REMOVE }
Functions
static int do_outliner_item_openclose (bContext *C, SpaceOops *soops, TreeElement *te, int all, const float mval[2])
static int outliner_item_openclose (bContext *C, wmOperator *op, wmEvent *event)
void OUTLINER_OT_item_openclose (wmOperatorType *ot)
static void do_item_rename (ARegion *ar, TreeElement *te, TreeStoreElem *tselem, ReportList *reports)
void item_rename_cb (bContext *C, Scene *UNUSED(scene), TreeElement *te, TreeStoreElem *UNUSED(tsep), TreeStoreElem *tselem)
static int do_outliner_item_rename (bContext *C, ARegion *ar, SpaceOops *soops, TreeElement *te, const float mval[2])
static int outliner_item_rename (bContext *C, wmOperator *UNUSED(op), wmEvent *event)
void OUTLINER_OT_item_rename (wmOperatorType *ot)
static int outliner_count_levels (SpaceOops *soops, ListBase *lb, int curlevel)
int outliner_has_one_flag (SpaceOops *soops, ListBase *lb, short flag, short curlevel)
void outliner_set_flag (SpaceOops *soops, ListBase *lb, short flag, short set)
int common_restrict_check (bContext *C, Object *ob)
void object_toggle_visibility_cb (bContext *C, Scene *scene, TreeElement *te, TreeStoreElem *UNUSED(tsep), TreeStoreElem *tselem)
void group_toggle_visibility_cb (bContext *UNUSED(C), Scene *scene, TreeElement *UNUSED(te), TreeStoreElem *UNUSED(tsep), TreeStoreElem *tselem)
static int outliner_toggle_visibility_exec (bContext *C, wmOperator *UNUSED(op))
void OUTLINER_OT_visibility_toggle (wmOperatorType *ot)
void object_toggle_selectability_cb (bContext *UNUSED(C), Scene *scene, TreeElement *te, TreeStoreElem *UNUSED(tsep), TreeStoreElem *tselem)
void group_toggle_selectability_cb (bContext *UNUSED(C), Scene *scene, TreeElement *UNUSED(te), TreeStoreElem *UNUSED(tsep), TreeStoreElem *tselem)
static int outliner_toggle_selectability_exec (bContext *C, wmOperator *UNUSED(op))
void OUTLINER_OT_selectability_toggle (wmOperatorType *ot)
void object_toggle_renderability_cb (bContext *UNUSED(C), Scene *scene, TreeElement *te, TreeStoreElem *UNUSED(tsep), TreeStoreElem *tselem)
void group_toggle_renderability_cb (bContext *UNUSED(C), Scene *scene, TreeElement *UNUSED(te), TreeStoreElem *UNUSED(tsep), TreeStoreElem *tselem)
static int outliner_toggle_renderability_exec (bContext *C, wmOperator *UNUSED(op))
void OUTLINER_OT_renderability_toggle (wmOperatorType *ot)
static int outliner_toggle_expanded_exec (bContext *C, wmOperator *UNUSED(op))
void OUTLINER_OT_expanded_toggle (wmOperatorType *ot)
static int outliner_toggle_selected_exec (bContext *C, wmOperator *UNUSED(op))
void OUTLINER_OT_selected_toggle (wmOperatorType *ot)
static int outliner_show_active_exec (bContext *C, wmOperator *UNUSED(op))
void OUTLINER_OT_show_active (wmOperatorType *ot)
static int outliner_scroll_page_exec (bContext *C, wmOperator *op)
void OUTLINER_OT_scroll_page (wmOperatorType *ot)
static void outliner_openclose_level (SpaceOops *soops, ListBase *lb, int curlevel, int level, int open)
static int outliner_one_level_exec (bContext *C, wmOperator *op)
void OUTLINER_OT_show_one_level (wmOperatorType *ot)
static int subtree_has_objects (SpaceOops *soops, ListBase *lb)
static void tree_element_show_hierarchy (Scene *scene, SpaceOops *soops, ListBase *lb)
static int outliner_show_hierarchy_exec (bContext *C, wmOperator *UNUSED(op))
void OUTLINER_OT_show_hierarchy (wmOperatorType *ot)
static int ed_operator_outliner_datablocks_active (bContext *C)
static void tree_element_to_path (SpaceOops *soops, TreeElement *te, TreeStoreElem *tselem, ID **id, char **path, int *array_index, short *flag, short *UNUSED(groupmode))
static void do_outliner_drivers_editop (SpaceOops *soops, ListBase *tree, ReportList *reports, short mode)
static int outliner_drivers_addsel_exec (bContext *C, wmOperator *op)
void OUTLINER_OT_drivers_add_selected (wmOperatorType *ot)
static int outliner_drivers_deletesel_exec (bContext *C, wmOperator *op)
void OUTLINER_OT_drivers_delete_selected (wmOperatorType *ot)
static KeyingSet * verify_active_keyingset (Scene *scene, short add)
static void do_outliner_keyingset_editop (SpaceOops *soops, KeyingSet *ks, ListBase *tree, short mode)
static int outliner_keyingset_additems_exec (bContext *C, wmOperator *op)
void OUTLINER_OT_keyingset_add_selected (wmOperatorType *ot)
static int outliner_keyingset_removeitems_exec (bContext *C, wmOperator *UNUSED(op))
void OUTLINER_OT_keyingset_remove_selected (wmOperatorType *ot)
static int parent_drop_exec (bContext *C, wmOperator *op)
TreeElement * outliner_dropzone_parent (bContext *C, wmEvent *event, TreeElement *te, float *fmval)
static int parent_drop_invoke (bContext *C, wmOperator *op, wmEvent *event)
void OUTLINER_OT_parent_drop (wmOperatorType *ot)
int outliner_dropzone_parent_clear (bContext *C, wmEvent *event, TreeElement *te, float *fmval)
static int parent_clear_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void OUTLINER_OT_parent_clear (wmOperatorType *ot)
Detailed Description
Definition in file outliner_edit.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
DRIVERS_EDITMODE_ADD
DRIVERS_EDITMODE_REMOVE
Definition at line 1068 of file outliner_edit.c.
anonymous enum
Enumerator:
KEYINGSET_EDITMODE_ADD
KEYINGSET_EDITMODE_REMOVE
Definition at line 1223 of file outliner_edit.c.
Function Documentation
int common_restrict_check (bContext * C, Object * ob)
Definition at line 319 of file outliner_edit.c.
References CTX_data_edit_object(), OB_RESTRICT_SELECT, OB_RESTRICT_VIEW, and Object::restrictflag.
Referenced by object_toggle_visibility_cb(), restrictbutton_sel_cb(), and restrictbutton_view_cb().
static void do_item_rename (ARegion * ar, TreeElement * te, TreeStoreElem * tselem, ReportList * reports) [static]
Definition at line 182 of file outliner_edit.c.
References BKE_report(), ED_region_tag_redraw(), ELEM10, ELEM3, TreeStoreElem::flag, TreeStoreElem::id, ID_LI, TreeElement::idcode, ID::lib, TreeElement::parent, RPT_WARNING, TSE_ANIM_DATA, TSE_CONSTRAINT_BASE, TSE_DEFGROUP_BASE, TSE_MODIFIER_BASE, TSE_NLA, TSE_POSE_BASE, TSE_POSEGRP_BASE, TSE_R_LAYER_BASE, TSE_R_PASS, TSE_RNA_ARRAY_ELEM, TSE_RNA_PROPERTY, TSE_RNA_STRUCT, TSE_SCRIPT_BASE, TSE_SEQ_STRIP, TSE_SEQUENCE, TSE_SEQUENCE_DUP, TSE_TEXTBUT, and TreeStoreElem::type.
Referenced by do_outliner_item_rename(), and item_rename_cb().
static void do_outliner_drivers_editop (SpaceOops * soops, ListBase * tree, ReportList * reports, short mode) [static]
Definition at line 1076 of file outliner_edit.c.
References ANIM_add_driver(), ANIM_remove_driver(), CREATEDRIVER_WITH_DEFAULT_DVAR, TreeElement::directdata, DRIVER_TYPE_PYTHON, DRIVERS_EDITMODE_ADD, DRIVERS_EDITMODE_REMOVE, ELEM, ListBase::first, TreeStoreElem::flag, KSP_FLAG_WHOLE_ARRAY, KSP_GROUP_KSNAME, MEM_freeN(), TreeElement::next, NULL, RNA_property_animateable(), RNA_property_array_length(), TreeElement::rnaptr, TreeElement::subtree, tree_element_to_path(), TREESTORE, TSE_RNA_ARRAY_ELEM, TSE_RNA_PROPERTY, TSE_SELECTED, TSELEM_OPEN, and TreeStoreElem::type.
Referenced by outliner_drivers_addsel_exec(), and outliner_drivers_deletesel_exec().
static int do_outliner_item_openclose (bContext * C, SpaceOops * soops, TreeElement * te, int all, const float mval[2]) [static]
Definition at line 119 of file outliner_edit.c.
References ListBase::first, TreeStoreElem::flag, TreeElement::next, outliner_has_one_flag(), outliner_set_flag(), TreeElement::subtree, TREESTORE, TSE_CLOSED, UI_UNIT_Y, and TreeElement::ys.
Referenced by outliner_item_openclose().
static int do_outliner_item_rename (bContext * C, ARegion * ar, SpaceOops * soops, TreeElement * te, const float mval[2]) [static]
Definition at line 215 of file outliner_edit.c.
References CTX_wm_reports(), do_item_rename(), ListBase::first, TreeElement::next, TreeElement::subtree, TREESTORE, UI_UNIT_X, UI_UNIT_Y, TreeElement::xend, TreeElement::xs, and TreeElement::ys.
Referenced by outliner_item_rename().
static void do_outliner_keyingset_editop (SpaceOops * soops, KeyingSet * ks, ListBase * tree, short mode) [static]
Definition at line 1255 of file outliner_edit.c.
References KeyingSet::active_path, BKE_keyingset_add_path(), BKE_keyingset_find_path(), BKE_keyingset_free_path(), BLI_countlist(), TreeElement::directdata, ELEM, ListBase::first, TreeStoreElem::flag, KEYINGSET_EDITMODE_ADD, KEYINGSET_EDITMODE_REMOVE, KSP_GROUP_KSNAME, MEM_freeN(), TreeElement::next, NULL, KeyingSet::paths, RNA_property_animateable(), TreeElement::rnaptr, TreeElement::subtree, tree_element_to_path(), TREESTORE, TSE_RNA_ARRAY_ELEM, TSE_RNA_PROPERTY, TSE_SELECTED, TSELEM_OPEN, and TreeStoreElem::type.
Referenced by outliner_keyingset_additems_exec(), and outliner_keyingset_removeitems_exec().
static int ed_operator_outliner_datablocks_active (bContext * C) [static]
Definition at line 916 of file outliner_edit.c.
References CTX_wm_area(), CTX_wm_space_outliner(), SpaceOops::outlinevis, SO_DATABLOCKS, SPACE_OUTLINER, and ScrArea::spacetype.
Referenced by OUTLINER_OT_drivers_add_selected(), OUTLINER_OT_drivers_delete_selected(), OUTLINER_OT_keyingset_add_selected(), and OUTLINER_OT_keyingset_remove_selected().
void group_toggle_renderability_cb (bContext * UNUSEDC, Scene * scene, TreeElement * UNUSEDte, TreeStoreElem * UNUSEDtsep, TreeStoreElem * tselem)
Definition at line 450 of file outliner_edit.c.
References TreeStoreElem::id, OB_RESTRICT_RENDER, and restrictbutton_gr_restrict_flag().
Referenced by outliner_group_operation_exec().
void group_toggle_selectability_cb (bContext * UNUSEDC, Scene * scene, TreeElement * UNUSEDte, TreeStoreElem * UNUSEDtsep, TreeStoreElem * tselem)
Definition at line 404 of file outliner_edit.c.
References TreeStoreElem::id, OB_RESTRICT_SELECT, and restrictbutton_gr_restrict_flag().
Referenced by outliner_group_operation_exec().
void group_toggle_visibility_cb (bContext * UNUSEDC, Scene * scene, TreeElement * UNUSEDte, TreeStoreElem * UNUSEDtsep, TreeStoreElem * tselem)
Definition at line 358 of file outliner_edit.c.
References TreeStoreElem::id, OB_RESTRICT_VIEW, and restrictbutton_gr_restrict_flag().
Referenced by outliner_group_operation_exec().
void item_rename_cb (bContext * C, Scene * UNUSEDscene, TreeElement * te, TreeStoreElem * UNUSEDtsep, TreeStoreElem * tselem)
Definition at line 208 of file outliner_edit.c.
References CTX_wm_region(), CTX_wm_reports(), and do_item_rename().
Referenced by outliner_group_operation_exec(), outliner_id_operation_exec(), and outliner_object_operation_exec().
void object_toggle_renderability_cb (bContext * UNUSEDC, Scene * scene, TreeElement * te, TreeStoreElem * UNUSEDtsep, TreeStoreElem * tselem)
Definition at line 440 of file outliner_edit.c.
References TreeElement::directdata, TreeStoreElem::id, if(), NULL, OB_RESTRICT_RENDER, Base::object, object_in_scene(), and Object::restrictflag.
Referenced by outliner_object_operation_exec(), and outliner_toggle_renderability_exec().
void object_toggle_selectability_cb (bContext * UNUSEDC, Scene * scene, TreeElement * te, TreeStoreElem * UNUSEDtsep, TreeStoreElem * tselem)
Definition at line 394 of file outliner_edit.c.
References TreeElement::directdata, TreeStoreElem::id, if(), NULL, OB_RESTRICT_SELECT, Base::object, object_in_scene(), and Object::restrictflag.
Referenced by outliner_object_operation_exec(), and outliner_toggle_selectability_exec().
void object_toggle_visibility_cb (bContext * C, Scene * scene, TreeElement * te, TreeStoreElem * UNUSEDtsep, TreeStoreElem * tselem)
Definition at line 343 of file outliner_edit.c.
References BA_DESELECT, common_restrict_check(), TreeElement::directdata, ED_base_object_select(), TreeStoreElem::id, OB_RESTRICT_VIEW, Base::object, object_in_scene(), and Object::restrictflag.
Referenced by outliner_object_operation_exec(), and outliner_toggle_visibility_exec().
static int outliner_count_levels (SpaceOops * soops, ListBase * lb, int curlevel) [static]
Definition at line 272 of file outliner_edit.c.
References ListBase::first, TreeElement::next, and TreeElement::subtree.
Referenced by outliner_one_level_exec().
static int outliner_drivers_addsel_exec (bContext * C, wmOperator * op) [static]
Definition at line 1150 of file outliner_edit.c.
References CTX_wm_space_outliner(), do_outliner_drivers_editop(), DRIVERS_EDITMODE_ADD, NC_ANIMATION, ND_FCURVES_ORDER, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, SpaceOops::tree, and WM_event_add_notifier().
Referenced by OUTLINER_OT_drivers_add_selected().
static int outliner_drivers_deletesel_exec (bContext * C, wmOperator * op) [static]
Definition at line 1185 of file outliner_edit.c.
References CTX_wm_space_outliner(), do_outliner_drivers_editop(), DRIVERS_EDITMODE_REMOVE, ND_KEYS, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, SpaceOops::tree, and WM_event_add_notifier().
Referenced by OUTLINER_OT_drivers_delete_selected().
TreeElement* outliner_dropzone_parent (bContext * C, wmEvent * event, TreeElement * te, float * fmval)
Definition at line 1420 of file outliner_edit.c.
References CTX_wm_space_outliner(), ListBase::first, TreeStoreElem::flag, ID_OB, TreeElement::idcode, TreeElement::next, NULL, outliner_dropzone_parent(), TreeElement::subtree, TREESTORE, TSE_CLOSED, UI_UNIT_X, UI_UNIT_Y, TreeElement::xend, TreeElement::xs, and TreeElement::ys.
Referenced by outliner_dropzone_parent(), outliner_parent_drop_poll(), and parent_drop_invoke().
int outliner_dropzone_parent_clear (bContext * C, wmEvent * event, TreeElement * te, float * fmval)
Definition at line 1617 of file outliner_edit.c.
References CTX_wm_space_outliner(), ELEM3, ListBase::first, TreeStoreElem::flag, ID_OB, ID_SCE, TreeElement::idcode, TreeElement::next, outliner_dropzone_parent_clear(), TreeElement::subtree, TREESTORE, TSE_CLOSED, TSE_R_LAYER, TSE_R_LAYER_BASE, TSE_R_PASS, TreeStoreElem::type, UI_UNIT_X, UI_UNIT_Y, TreeElement::xend, TreeElement::xs, and TreeElement::ys.
Referenced by outliner_dropzone_parent_clear(), and outliner_parent_clear_poll().
int outliner_has_one_flag (SpaceOops * soops, ListBase * lb, short flag, short curlevel)
Definition at line 285 of file outliner_edit.c.
References ListBase::first, TreeStoreElem::flag, TreeElement::next, outliner_has_one_flag(), TreeElement::subtree, and TREESTORE.
Referenced by do_outliner_item_activate(), do_outliner_item_openclose(), do_outliner_operation_event(), outliner_has_one_flag(), outliner_one_level_exec(), outliner_toggle_expanded_exec(), and outliner_toggle_selected_exec().
static int outliner_item_openclose (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 147 of file outliner_edit.c.
References CTX_wm_region(), CTX_wm_space_outliner(), do_outliner_item_openclose(), ED_region_tag_redraw(), ListBase::first, wmEvent::mval, TreeElement::next, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), SpaceOops::tree, UI_view2d_region_to_view(), and ARegion::v2d.
Referenced by OUTLINER_OT_item_openclose().
static int outliner_item_rename (bContext * C, wmOperator * UNUSEDop, wmEvent * event) [static]
Definition at line 236 of file outliner_edit.c.
References CTX_wm_region(), CTX_wm_space_outliner(), do_outliner_item_rename(), ListBase::first, wmEvent::mval, TreeElement::next, OPERATOR_FINISHED, SpaceOops::tree, UI_view2d_region_to_view(), and ARegion::v2d.
Referenced by OUTLINER_OT_item_rename().
static int outliner_keyingset_additems_exec (bContext * C, wmOperator * op) [static]
Definition at line 1318 of file outliner_edit.c.
References BKE_report(), CTX_data_scene(), CTX_wm_space_outliner(), do_outliner_keyingset_editop(), KEYINGSET_EDITMODE_ADD, NC_SCENE, ND_KEYINGSET, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, SpaceOops::tree, verify_active_keyingset(), and WM_event_add_notifier().
Referenced by OUTLINER_OT_keyingset_add_selected().
static int outliner_keyingset_removeitems_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1359 of file outliner_edit.c.
References CTX_data_scene(), CTX_wm_space_outliner(), do_outliner_keyingset_editop(), KEYINGSET_EDITMODE_REMOVE, NC_SCENE, ND_KEYINGSET, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, SpaceOops::tree, verify_active_keyingset(), and WM_event_add_notifier().
Referenced by OUTLINER_OT_keyingset_remove_selected().
static int outliner_one_level_exec (bContext * C, wmOperator * op) [static]
Definition at line 802 of file outliner_edit.c.
References add(), CTX_wm_region(), CTX_wm_space_outliner(), ED_region_tag_redraw(), OPERATOR_FINISHED, outliner_count_levels(), outliner_has_one_flag(), outliner_openclose_level(), wmOperator::ptr, RNA_boolean_get(), SpaceOops::tree, and TSE_CLOSED.
Referenced by OUTLINER_OT_show_one_level().
static void outliner_openclose_level (SpaceOops * soops, ListBase * lb, int curlevel, int level, int open) [static]
Definition at line 783 of file outliner_edit.c.
References ListBase::first, TreeStoreElem::flag, TreeElement::next, TreeElement::subtree, TREESTORE, and TSE_CLOSED.
Referenced by outliner_one_level_exec().
void OUTLINER_OT_drivers_add_selected (wmOperatorType * ot)
Definition at line 1167 of file outliner_edit.c.
References wmOperatorType::description, ed_operator_outliner_datablocks_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_drivers_addsel_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_drivers_delete_selected (wmOperatorType * ot)
Definition at line 1202 of file outliner_edit.c.
References wmOperatorType::description, ed_operator_outliner_datablocks_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_drivers_deletesel_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_expanded_toggle (wmOperatorType * ot)
Definition at line 502 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, outliner_toggle_expanded_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_item_openclose (wmOperatorType * ot)
Definition at line 167 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_item_openclose(), wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by outliner_operatortypes().
void OUTLINER_OT_item_rename (wmOperatorType * ot)
Definition at line 253 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_item_rename(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_keyingset_add_selected (wmOperatorType * ot)
Definition at line 1341 of file outliner_edit.c.
References wmOperatorType::description, ed_operator_outliner_datablocks_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_keyingset_additems_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_keyingset_remove_selected (wmOperatorType * ot)
Definition at line 1378 of file outliner_edit.c.
References wmOperatorType::description, ed_operator_outliner_datablocks_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_keyingset_removeitems_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_parent_clear (wmOperatorType * ot)
Definition at line 1673 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, parent_clear_invoke(), wmOperatorType::poll, prop_clear_parent_types, RNA_def_enum(), RNA_def_string(), and wmOperatorType::srna.
Referenced by outliner_operatortypes().
void OUTLINER_OT_parent_drop (wmOperatorType * ot)
Definition at line 1595 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, parent_drop_exec(), parent_drop_invoke(), wmOperatorType::poll, prop_make_parent_types, RNA_def_enum(), RNA_def_string(), and wmOperatorType::srna.
Referenced by outliner_operatortypes().
void OUTLINER_OT_renderability_toggle (wmOperatorType * ot)
Definition at line 468 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_toggle_renderability_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_scroll_page (wmOperatorType * ot)
Definition at line 625 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, outliner_scroll_page_exec(), wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by outliner_operatortypes().
void OUTLINER_OT_selectability_toggle (wmOperatorType * ot)
Definition at line 424 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active_no_editobject(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_toggle_selectability_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_selected_toggle (wmOperatorType * ot)
Definition at line 537 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, outliner_toggle_selected_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_show_active (wmOperatorType * ot)
Definition at line 592 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, outliner_show_active_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_show_hierarchy (wmOperatorType * ot)
Definition at line 897 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, outliner_show_hierarchy_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_show_one_level (wmOperatorType * ot)
Definition at line 823 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, outliner_one_level_exec(), wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by outliner_operatortypes().
void OUTLINER_OT_visibility_toggle (wmOperatorType * ot)
Definition at line 378 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active_no_editobject(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_toggle_visibility_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
static int outliner_scroll_page_exec (bContext * C, wmOperator * op) [static]
Definition at line 606 of file outliner_edit.c.
References CTX_wm_region(), View2D::cur, ED_region_tag_redraw(), View2D::mask, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), ARegion::v2d, rctf::ymax, rcti::ymax, rctf::ymin, and rcti::ymin.
Referenced by OUTLINER_OT_scroll_page().
void outliner_set_flag (SpaceOops * soops, ListBase * lb, short flag, short set)
Definition at line 301 of file outliner_edit.c.
References ListBase::first, TreeStoreElem::flag, TreeElement::next, outliner_set_flag(), TreeElement::subtree, and TREESTORE.
Referenced by do_outliner_item_activate(), do_outliner_item_openclose(), do_outliner_operation_event(), outliner_set_flag(), outliner_toggle_expanded_exec(), and outliner_toggle_selected_exec().
static int outliner_show_active_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 556 of file outliner_edit.c.
References CTX_data_scene(), CTX_wm_region(), CTX_wm_space_outliner(), View2D::cur, ED_region_tag_redraw(), View2D::mask, NULL, OBACT, OPERATOR_CANCELLED, OPERATOR_FINISHED, outliner_find_id(), SO_TREESTORE_REDRAW, SpaceOops::storeflag, SpaceOops::tree, ARegion::v2d, rctf::xmax, rctf::xmin, TreeElement::xs, rctf::ymax, rcti::ymax, rctf::ymin, rcti::ymin, and TreeElement::ys.
Referenced by OUTLINER_OT_show_active().
static int outliner_show_hierarchy_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 883 of file outliner_edit.c.
References CTX_data_scene(), CTX_wm_region(), CTX_wm_space_outliner(), ED_region_tag_redraw(), OPERATOR_FINISHED, SpaceOops::tree, and tree_element_show_hierarchy().
Referenced by OUTLINER_OT_show_hierarchy().
static int outliner_toggle_expanded_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 487 of file outliner_edit.c.
References CTX_wm_region(), CTX_wm_space_outliner(), ED_region_tag_redraw(), OPERATOR_FINISHED, outliner_has_one_flag(), outliner_set_flag(), SpaceOops::tree, and TSE_CLOSED.
Referenced by OUTLINER_OT_expanded_toggle().
static int outliner_toggle_renderability_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 456 of file outliner_edit.c.
References CTX_data_scene(), CTX_wm_space_outliner(), NC_SCENE, ND_OB_RENDER, object_toggle_renderability_cb(), OPERATOR_FINISHED, outliner_do_object_operation(), SpaceOops::tree, and WM_event_add_notifier().
Referenced by OUTLINER_OT_renderability_toggle().
static int outliner_toggle_selectability_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 410 of file outliner_edit.c.
References CTX_data_scene(), CTX_wm_region(), CTX_wm_space_outliner(), ED_region_tag_redraw(), NC_SCENE, ND_OB_SELECT, object_toggle_selectability_cb(), OPERATOR_FINISHED, outliner_do_object_operation(), SpaceOops::tree, and WM_event_add_notifier().
Referenced by OUTLINER_OT_selectability_toggle().
static int outliner_toggle_selected_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 518 of file outliner_edit.c.
References CTX_data_scene(), CTX_wm_region(), CTX_wm_space_outliner(), ED_region_tag_redraw(), NC_SCENE, ND_OB_SELECT, OPERATOR_FINISHED, outliner_has_one_flag(), outliner_set_flag(), SO_TREESTORE_REDRAW, SpaceOops::storeflag, SpaceOops::tree, TSE_SELECTED, and WM_event_add_notifier().
Referenced by OUTLINER_OT_selected_toggle().
static int outliner_toggle_visibility_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 364 of file outliner_edit.c.
References CTX_data_scene(), CTX_wm_region(), CTX_wm_space_outliner(), ED_region_tag_redraw(), NC_SCENE, ND_OB_VISIBLE, object_toggle_visibility_cb(), OPERATOR_FINISHED, outliner_do_object_operation(), SpaceOops::tree, and WM_event_add_notifier().
Referenced by OUTLINER_OT_visibility_toggle().
static int parent_clear_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1655 of file outliner_edit.c.
References BA_SELECT, CTX_data_active_object(), CTX_data_scene(), ED_base_object_select(), ED_object_parent_clear(), find_id(), MAX_ID_NAME, NULL, object_in_scene(), OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), and RNA_string_get().
Referenced by OUTLINER_OT_parent_clear().
static int parent_drop_exec (bContext * C, wmOperator * op) [static]
Definition at line 1395 of file outliner_edit.c.
References CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), DAG_scene_sort(), ED_object_parent_set(), find_id(), MAX_ID_NAME, NC_OBJECT, ND_PARENT, ND_TRANSFORM, NULL, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), RNA_string_get(), and WM_event_add_notifier().
Referenced by OUTLINER_OT_parent_drop().
static int parent_drop_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1449 of file outliner_edit.c.
References BA_SELECT, CTX_data_active_object(), CTX_data_main(), CTX_data_scene(), CTX_wm_region(), CTX_wm_space_outliner(), DAG_ids_flush_update(), DAG_scene_sort(), PointerRNA::data, ED_base_object_select(), ED_object_parent_set(), ELEM, find_id(), ListBase::first, IFACE_, MAX_ID_NAME, wmEvent::mval, TreeElement::name, NC_OBJECT, ND_PARENT, ND_TRANSFORM, TreeElement::next, NULL, OB_ARMATURE, OB_CURVE, OB_LATTICE, object_in_scene(), OPERATOR_CANCELLED, OPERATOR_FINISHED, outliner_dropzone_parent(), PAR_ARMATURE, PAR_ARMATURE_AUTO, PAR_ARMATURE_ENVELOPE, PAR_ARMATURE_NAME, PAR_BONE, PAR_CURVE, PAR_FOLLOW, PAR_LATTICE, PAR_OBJECT, PAR_PATH_CONST, wmOperator::ptr, wmOperator::reports, RNA_enum_set(), RNA_string_get(), RNA_string_set(), SpaceOops::tree, Object::type, UI_view2d_region_to_view(), uiItemFullO(), uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), ARegion::v2d, WM_event_add_notifier(), WM_OP_EXEC_DEFAULT, and WM_operator_properties_create().
Referenced by OUTLINER_OT_parent_drop().
static int subtree_has_objects (SpaceOops * soops, ListBase * lb) [static]
Definition at line 843 of file outliner_edit.c.
References ListBase::first, ID_OB, TreeElement::idcode, TreeElement::next, TreeElement::subtree, TREESTORE, and TreeStoreElem::type.
Referenced by tree_element_show_hierarchy().
static void tree_element_show_hierarchy (Scene * scene, SpaceOops * soops, ListBase * lb) [static]
Definition at line 857 of file outliner_edit.c.
References ListBase::first, TreeStoreElem::flag, TreeStoreElem::id, ID_OB, ID_SCE, TreeElement::idcode, TreeElement::next, TreeElement::subtree, subtree_has_objects(), TREESTORE, TSE_CLOSED, TSELEM_OPEN, and TreeStoreElem::type.
Referenced by outliner_show_hierarchy_exec().
static void tree_element_to_path (SpaceOops * soops, TreeElement * te, TreeStoreElem * tselem, ID ** id, char ** path, int * array_index, short * flag, short * UNUSEDgroupmode) [static]
Definition at line 931 of file outliner_edit.c.
References BLI_addhead(), BLI_freelistN(), PointerRNA::data, LinkData::data, TreeElement::directdata, ListBase::first, if(), TreeElement::index, KSP_FLAG_WHOLE_ARRAY, MEM_callocN(), MEM_freeN(), TreeElement::next, LinkData::next, NULL, TreeElement::parent, PROP_COLLECTION, PROP_POINTER, RNA_path_append(), RNA_property_array_length(), RNA_property_type(), RNA_struct_is_ID(), RNA_struct_name_get_alloc(), TreeElement::rnaptr, TreeElement::subtree, TREESTORE, TSE_RNA_ARRAY_ELEM, TSE_RNA_PROPERTY, TSE_RNA_STRUCT, PointerRNA::type, and TreeStoreElem::type.
Referenced by do_outliner_drivers_editop(), and do_outliner_keyingset_editop().
static KeyingSet* verify_active_keyingset (Scene * scene, short add) [static]
Definition at line 1232 of file outliner_edit.c.
References Scene::active_keyingset, BKE_keyingset_add(), BLI_countlist(), BLI_findlink(), KEYINGSET_ABSOLUTE, Scene::keyingsets, and NULL.
Referenced by outliner_keyingset_additems_exec(), and outliner_keyingset_removeitems_exec().