Blender: BlockCTX1 Struct Reference
BlockCTX1 Struct Reference
CTX1 block.
#include <BlockDXT.h>
Public Member Functions
void evaluatePalette (Color32 color_array[4]) const
void setIndices (int *idx)
void decodeBlock (ColorBlock *block) const
void flip4 ()
Flip CTX1 block vertically.
void flip2 ()
Flip half CTX1 block vertically.
Public Attributes
uint8 col0 [2]
uint8 col1 [2]
union {
uint8 row [4]
uint indices
};
Detailed Description
CTX1 block.
Definition at line 247 of file BlockDXT.h.
Member Function Documentation
void BlockCTX1::decodeBlock (ColorBlock * block) const
Definition at line 583 of file BlockDXT.cpp.
References ColorBlock::color(), evaluatePalette(), i, and row.
void BlockCTX1::evaluatePalette (Color32 color_array[4]) const
Definition at line 559 of file BlockDXT.cpp.
References Color32::a, Color32::b, col0, col1, Color32::g, and Color32::r.
Referenced by decodeBlock().
void BlockCTX1::flip2 () [inline]
Flip half CTX1 block vertically.
Definition at line 615 of file BlockDXT.cpp.
References row, and swap().
void BlockCTX1::flip4 () [inline]
Flip CTX1 block vertically.
Definition at line 608 of file BlockDXT.cpp.
References row, and swap().
void BlockCTX1::setIndices (int * idx)
Definition at line 598 of file BlockDXT.cpp.
References i, and indices.
Member Data Documentation
union { ... }
uint8 BlockCTX1::col0[2]
Definition at line 249 of file BlockDXT.h.
Referenced by evaluatePalette(), and mem_read().
uint8 BlockCTX1::col1[2]
Definition at line 250 of file BlockDXT.h.
Referenced by evaluatePalette(), and mem_read().
uint BlockCTX1::indices
Definition at line 253 of file BlockDXT.h.
Referenced by mem_read(), and setIndices().
uint8 BlockCTX1::row[4]
Definition at line 252 of file BlockDXT.h.
Referenced by decodeBlock(), flip2(), and flip4().
The documentation for this struct was generated from the following files:
BlockDXT.h
BlockDXT.cpp