Blender: uvedit_ops.c File Reference
uvedit_ops.c File Reference
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "DNA_object_types.h"
#include "DNA_material_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_node_types.h"
#include "DNA_image_types.h"
#include "DNA_space_types.h"
#include "DNA_scene_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_array.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_customdata.h"
#include "BKE_depsgraph.h"
#include "BKE_image.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_material.h"
#include "BKE_mesh.h"
#include "BKE_node.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "BKE_tessmesh.h"
#include "ED_image.h"
#include "ED_mesh.h"
#include "ED_node.h"
#include "ED_uvedit.h"
#include "ED_object.h"
#include "ED_screen.h"
#include "ED_transform.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_view2d.h"
#include "uvedit_intern.h"
Defines
#define UV_SEL_TEST(luv, bool_test) ((((luv)->flag & MLOOPUV_VERTSEL) == MLOOPUV_VERTSEL) == bool_test)
Functions
static void select_all_perform (Scene *scene, Image *ima, BMEditMesh *em, int action)
int ED_uvedit_test (Object *obedit)
static int ED_operator_uvedit_can_uv_sculpt (struct bContext *C)
static int UNUSED_FUNCTION() ED_operator_uvmap_mesh (bContext *C)
static int is_image_texture_node (bNode *node)
int ED_object_get_active_image (Object *ob, int mat_nr, Image **ima, ImageUser **iuser, bNode **node_r)
void ED_object_assign_active_image (Main *bmain, Object *ob, int mat_nr, Image *ima)
void ED_uvedit_assign_image (Main *bmain, Scene *scene, Object *obedit, Image *ima, Image *previma)
static int uvedit_set_tile (Object *obedit, Image *ima, int curtile)
static void uvedit_pixel_to_float (SpaceImage *sima, float *dist, float pixeldist)
int uvedit_face_visible_nolocal (Scene *scene, BMFace *efa)
int uvedit_face_visible_test (Scene *scene, Image *ima, BMFace *efa, MTexPoly *tf)
int uvedit_face_select_test (Scene *scene, BMEditMesh *em, BMFace *efa)
int uvedit_face_select_enable (Scene *scene, BMEditMesh *em, BMFace *efa, const short do_history)
int uvedit_face_select_disable (Scene *scene, BMEditMesh *em, BMFace *efa)
int uvedit_edge_select_test (BMEditMesh *em, Scene *scene, BMLoop *l)
void uvedit_edge_select_enable (BMEditMesh *em, Scene *scene, BMLoop *l, const short do_history)
void uvedit_edge_select_disable (BMEditMesh *em, Scene *scene, BMLoop *l)
int uvedit_uv_select_test (BMEditMesh *em, Scene *scene, BMLoop *l)
void uvedit_uv_select_enable (BMEditMesh *em, Scene *scene, BMLoop *l, const short do_history)
void uvedit_uv_select_disable (BMEditMesh *em, Scene *scene, BMLoop *l)
void uvedit_live_unwrap_update (SpaceImage *sima, Scene *scene, Object *obedit)
void poly_uv_center (BMEditMesh *em, BMFace *f, float cent[2])
void uv_center (float uv[][2], float cent[2], int quad)
float uv_area (float uv[][2], int quad)
float poly_uv_area (float uv[][2], int len)
void poly_copy_aspect (float uv_orig[][2], float uv[][2], float aspx, float aspy, int len)
int ED_uvedit_minmax (Scene *scene, Image *ima, Object *obedit, float *min, float *max)
static int ED_uvedit_median (Scene *scene, Image *ima, Object *obedit, float co[2])
static int uvedit_center (Scene *scene, Image *ima, Object *obedit, float cent[2], char mode)
void uv_find_nearest_edge (Scene *scene, Image *ima, BMEditMesh *em, float co[2], NearestHit *hit)
static void find_nearest_uv_face (Scene *scene, Image *ima, BMEditMesh *em, float co[2], NearestHit *hit)
static int nearest_uv_between (BMEditMesh *em, BMFace *efa, int UNUSED(nverts), int id, float co[2], float uv[2])
void uv_find_nearest_vert (Scene *scene, Image *ima, BMEditMesh *em, float co[2], float penalty[2], NearestHit *hit)
int ED_uvedit_nearest_uv (Scene *scene, Object *obedit, Image *ima, float co[2], float uv[2])
UvElement * ED_uv_element_get (UvElementMap *map, BMFace *efa, BMLoop *l)
static void select_edgeloop_uv_vertex_loop_flag (UvMapVert *first)
static UvMapVert * select_edgeloop_uv_vertex_map_get (UvVertMap *vmap, BMFace *efa, int a)
static int select_edgeloop_uv_edge_tag_faces (BMEditMesh *em, UvMapVert *first1, UvMapVert *first2, int *totface)
static int select_edgeloop (Scene *scene, Image *ima, BMEditMesh *em, NearestHit *hit, float limit[2], const short extend)
static void select_linked (Scene *scene, Image *ima, BMEditMesh *em, float limit[2], NearestHit *hit, int extend)
static float * uv_sel_co_from_eve (Scene *scene, Image *ima, BMEditMesh *em, BMVert *eve)
static void weld_align_uv (bContext *C, int tool)
static int align_exec (bContext *C, wmOperator *op)
static void UV_OT_align (wmOperatorType *ot)
static int weld_exec (bContext *C, wmOperator *UNUSED(op))
static void UV_OT_weld (wmOperatorType *ot)
static int select_all_exec (bContext *C, wmOperator *op)
static void UV_OT_select_all (wmOperatorType *ot)
static int sticky_select (float *limit, int hitv[4], int v, float *hituv[4], float *uv, int sticky, int hitlen)
static int mouse_select (bContext *C, float co[2], int extend, int loop)
static int select_exec (bContext *C, wmOperator *op)
static int select_invoke (bContext *C, wmOperator *op, wmEvent *event)
static void UV_OT_select (wmOperatorType *ot)
static int select_loop_exec (bContext *C, wmOperator *op)
static int select_loop_invoke (bContext *C, wmOperator *op, wmEvent *event)
static void UV_OT_select_loop (wmOperatorType *ot)
static int select_linked_internal (bContext *C, wmOperator *op, wmEvent *event, int pick)
static int select_linked_exec (bContext *C, wmOperator *op)
static void UV_OT_select_linked (wmOperatorType *ot)
static int select_linked_pick_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int select_linked_pick_exec (bContext *C, wmOperator *op)
static void UV_OT_select_linked_pick (wmOperatorType *ot)
static int unlink_selection_exec (bContext *C, wmOperator *op)
static void UV_OT_unlink_selected (wmOperatorType *ot)
static void uv_faces_do_sticky (bContext *C, SpaceImage *sima, Scene *scene, Object *obedit, short select)
static int border_select_exec (bContext *C, wmOperator *op)
static void UV_OT_select_border (wmOperatorType *ot)
static void select_uv_inside_ellipse (BMEditMesh *em, SpaceImage *UNUSED(sima), Scene *scene, int select, float *offset, float *ell, BMLoop *l, MLoopUV *luv)
static int circle_select_exec (bContext *C, wmOperator *op)
static void UV_OT_circle_select (wmOperatorType *ot)
static void snap_uv_to_pixel (float *uvco, float w, float h)
static void snap_cursor_to_pixels (SpaceImage *sima)
static int snap_cursor_to_selection (Scene *scene, Image *ima, Object *obedit, SpaceImage *sima)
static int snap_cursor_exec (bContext *C, wmOperator *op)
static void UV_OT_snap_cursor (wmOperatorType *ot)
static int snap_uvs_to_cursor (Scene *scene, Image *ima, Object *obedit, SpaceImage *sima)
static int snap_uvs_to_adjacent_unselected (Scene *scene, Image *ima, Object *obedit)
static int snap_uvs_to_pixels (SpaceImage *sima, Scene *scene, Object *obedit)
static int snap_selection_exec (bContext *C, wmOperator *op)
static void UV_OT_snap_selected (wmOperatorType *ot)
static int pin_exec (bContext *C, wmOperator *op)
static void UV_OT_pin (wmOperatorType *ot)
static int select_pinned_exec (bContext *C, wmOperator *UNUSED(op))
static void UV_OT_select_pinned (wmOperatorType *ot)
static int bm_face_is_all_uv_sel (BMesh *bm, BMFace *f, int bool_test)
static int hide_exec (bContext *C, wmOperator *op)
static void UV_OT_hide (wmOperatorType *ot)
static int reveal_exec (bContext *C, wmOperator *UNUSED(op))
static void UV_OT_reveal (wmOperatorType *ot)
static int set_2d_cursor_exec (bContext *C, wmOperator *op)
static int set_2d_cursor_invoke (bContext *C, wmOperator *op, wmEvent *event)
static void UV_OT_cursor_set (wmOperatorType *ot)
static int set_tile_exec (bContext *C, wmOperator *op)
static int set_tile_invoke (bContext *C, wmOperator *op, wmEvent *event)
static void UV_OT_tile_set (wmOperatorType *ot)
static int seams_from_islands_exec (bContext *C, wmOperator *op)
static void UV_OT_seams_from_islands (wmOperatorType *ot)
static int mark_seam_exec (bContext *C, wmOperator *UNUSED(op))
static void UV_OT_mark_seam (wmOperatorType *ot)
void ED_operatortypes_uvedit (void)
void ED_keymap_uvedit (wmKeyConfig *keyconf)
Detailed Description
Definition in file uvedit_ops.c.
Define Documentation
#define UV_SEL_TEST (luv, bool_test) ((((luv)->flag & MLOOPUV_VERTSEL) == MLOOPUV_VERTSEL) == bool_test)
Definition at line 2999 of file uvedit_ops.c.
Referenced by bm_face_is_all_uv_sel(), and hide_exec().
Function Documentation
static int align_exec (bContext * C, wmOperator * op) [static]
Definition at line 1533 of file uvedit_ops.c.
References OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), and weld_align_uv().
Referenced by UV_OT_align().
static int bm_face_is_all_uv_sel (BMesh * bm, BMFace * f, int bool_test) [static]
Definition at line 3002 of file uvedit_ops.c.
References BM_FACE_FIRST_LOOP, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, FALSE, BMLoop::head, BMesh::ldata, BMLoop::next, TRUE, and UV_SEL_TEST.
Referenced by hide_exec().
static int border_select_exec (bContext * C, wmOperator * op) [static]
Definition at line 2419 of file uvedit_ops.c.
References BLI_in_rctf(), BMEditMesh::bm, BM_elem_flag_disable, BM_elem_flag_enable, BM_ELEM_TAG, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_select_history_validate(), BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CTX_data_edit_image(), CTX_data_edit_object(), CTX_data_scene(), CTX_data_tool_settings(), CTX_wm_region(), CTX_wm_space_image(), CustomData_bmesh_get(), Object::data, BMHeader::data, EDBM_deselect_flush(), FALSE, MLoopUV::flag, GESTURE_MODAL_SELECT, BMLoop::head, BMFace::head, BMesh::ldata, MLOOPUV_PINNED, NC_GEOM, ND_SELECT, OPERATOR_CANCELLED, OPERATOR_FINISHED, BMesh::pdata, poly_uv_center(), wmOperator::ptr, RNA_boolean_get(), RNA_int_get(), SCE_SELECT_FACE, SEL_DESELECT, select_all_perform(), ToolSettings::selectmode, UI_view2d_region_to_view(), MLoopUV::uv, uv_faces_do_sticky(), ToolSettings::uv_flag, UV_SELECT_FACE, ToolSettings::uv_selectmode, UV_SYNC_SELECTION, uvedit_face_visible_test(), uvedit_uv_select_disable(), uvedit_uv_select_enable(), ARegion::v2d, WM_event_add_notifier(), rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, rctf::ymax, rcti::ymax, rctf::ymin, and rcti::ymin.
Referenced by UV_OT_select_border().
static int circle_select_exec (bContext * C, wmOperator * op) [static]
Definition at line 2582 of file uvedit_ops.c.
References BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CTX_data_edit_object(), CTX_data_scene(), CTX_wm_region(), CTX_wm_space_image(), CustomData_bmesh_get(), Object::data, BMHeader::data, ED_space_image_size(), ED_space_image_zoom(), GESTURE_MODAL_SELECT, BMLoop::head, BMesh::ldata, NC_GEOM, ND_SELECT, OPERATOR_FINISHED, wmOperator::ptr, RNA_int_get(), select_uv_inside_ellipse(), UI_view2d_region_to_view(), ARegion::v2d, and WM_event_add_notifier().
Referenced by UV_OT_circle_select().
void ED_keymap_uvedit (wmKeyConfig * keyconf)
Definition at line 3595 of file uvedit_ops.c.
References ACTIONMOUSE, AKEY, BKEY, CKEY, COMMAKEY, ED_object_generic_keymap(), ED_operator_uvedit_can_uv_sculpt(), EKEY, FALSE, HKEY, IKEY, KM_ALT, KM_CTRL, KM_PRESS, KM_SHIFT, LKEY, PERIODKEY, PKEY, wmKeyMap::poll, wmKeyMapItem::ptr, QKEY, RNA_boolean_set(), RNA_enum_set(), RNA_string_set(), SEL_INVERT, SEL_TOGGLE, SELECTMOUSE, SKEY, SPACE_IMAGE, TABKEY, transform_keymap_for_space(), TRUE, VKEY, WKEY, WM_keymap_add_item(), WM_keymap_add_menu(), and WM_keymap_find().
Referenced by ED_spacetypes_keymap().
void ED_object_assign_active_image (Main * bmain, Object * ob, int mat_nr, Image * ima)
Definition at line 154 of file uvedit_ops.c.
References ED_node_generic_update(), give_current_material(), Image::id, bNode::id, is_image_texture_node(), nodeGetActiveTexture(), Material::nodetree, NULL, and Material::use_nodes.
Referenced by ED_uvedit_assign_image().
int ED_object_get_active_image (Object * ob, int mat_nr, Image ** ima, ImageUser ** iuser, bNode ** node_r)
Definition at line 135 of file uvedit_ops.c.
References FALSE, give_current_material(), bNode::id, if(), is_image_texture_node(), nodeGetActiveTexture(), Material::nodetree, NULL, TRUE, and Material::use_nodes.
Referenced by image_refresh(), imapaint_face_image(), project_paint_face_image(), and tex_mat_set_texture_cb().
static int ED_operator_uvedit_can_uv_sculpt (struct bContext * C) [static]
Definition at line 106 of file uvedit_ops.c.
References CTX_data_edit_object(), CTX_data_tool_settings(), CTX_wm_space_image(), ED_space_image_show_uvedit(), and ToolSettings::use_uv_sculpt.
Referenced by ED_keymap_uvedit().
static int UNUSED_FUNCTION() ED_operator_uvmap_mesh (bContext * C) [static]
Definition at line 115 of file uvedit_ops.c.
References C, CD_MTFACE, CTX_data_active_object(), CustomData_get_layer(), Object::data, Mesh::fdata, NULL, OB_MESH, and Object::type.
void ED_operatortypes_uvedit (void)
Definition at line 3554 of file uvedit_ops.c.
References UV_OT_align(), UV_OT_average_islands_scale(), UV_OT_circle_select(), UV_OT_cube_project(), UV_OT_cursor_set(), UV_OT_cylinder_project(), UV_OT_from_view(), UV_OT_hide(), UV_OT_mark_seam(), UV_OT_minimize_stretch(), UV_OT_pack_islands(), UV_OT_pin(), UV_OT_reset(), UV_OT_reveal(), UV_OT_seams_from_islands(), UV_OT_select(), UV_OT_select_all(), UV_OT_select_border(), UV_OT_select_linked(), UV_OT_select_linked_pick(), UV_OT_select_loop(), UV_OT_select_pinned(), UV_OT_snap_cursor(), UV_OT_snap_selected(), UV_OT_sphere_project(), UV_OT_stitch(), UV_OT_tile_set(), UV_OT_unlink_selected(), UV_OT_unwrap(), UV_OT_weld(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
UvElement* ED_uv_element_get (UvElementMap * map, BMFace * efa, BMLoop * l) [read]
Definition at line 896 of file uvedit_ops.c.
References BM_elem_index_get, UvElement::face, UvElement::next, NULL, BMLoop::v, and UvElementMap::vert.
Referenced by stitch_init(), stitch_process_data(), stitch_select(), uv_element_offset_from_face_get(), and uv_sculpt_stroke_init().
void ED_uvedit_assign_image (Main * bmain, Scene * scene, Object * obedit, Image * ima, Image * previma)
Definition at line 167 of file uvedit_ops.c.
References BMEditMesh::bm, BM_active_face_get(), BM_data_layer_add(), BM_FACES_OF_MESH, BM_ITER_MESH, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), CustomData_has_layer(), DAG_id_tag_update(), Object::data, BMHeader::data, ED_object_assign_active_image(), BMFace::head, Image::id, id_lib_extern(), id_us_plus(), IMA_TYPE_COMPOSITE, IMA_TYPE_R_RESULT, BMesh::ldata, BMFace::mat_nr, NULL, OB_MESH, BMesh::pdata, scene_use_new_shading_nodes(), BMesh::totface, MTexPoly::tpage, Object::type, Image::type, update(), ID::us, and uvedit_face_visible_test().
Referenced by drop_named_image_invoke(), ED_space_image_set(), and ED_uvedit_ensure_uvs().
static int ED_uvedit_median (Scene * scene, Image * ima, Object * obedit, float co[2]) [static]
Definition at line 614 of file uvedit_ops.c.
References add_v2_v2(), BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, BMLoop::head, BMFace::head, BMesh::ldata, mul_v2_fl(), BMesh::pdata, MLoopUV::uv, uvedit_face_visible_test(), uvedit_uv_select_test(), and zero_v2().
Referenced by uvedit_center().
int ED_uvedit_minmax (Scene * scene, Image * ima, Object * obedit, float * min, float * max)
Definition at line 584 of file uvedit_ops.c.
References BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, DO_MINMAX2, BMLoop::head, BMFace::head, INIT_MINMAX2, BMesh::ldata, BMesh::pdata, MLoopUV::uv, uvedit_face_visible_test(), and uvedit_uv_select_test().
Referenced by image_view_selected_exec(), and uvedit_center().
int ED_uvedit_nearest_uv (Scene * scene, Object * obedit, Image * ima, float co[2], float uv[2])
Definition at line 859 of file uvedit_ops.c.
References BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, fabs(), BMLoop::head, BMFace::head, BMesh::ldata, BMesh::pdata, MLoopUV::uv, and uvedit_face_visible_test().
Referenced by CalcSnapGeometry().
int ED_uvedit_test (Object * obedit)
Definition at line 89 of file uvedit_ops.c.
References BMEdit_FromObject(), EDBM_mtexpoly_check(), OB_MESH, and Object::type.
Referenced by ED_uvedit_ensure_uvs(), ED_uvedit_live_unwrap_begin(), image_panel_uv_poll(), and uvedit_set_tile().
static void find_nearest_uv_face (Scene * scene, Image * ima, BMEditMesh * em, float co[2], NearestHit * hit) [static]
Definition at line 713 of file uvedit_ops.c.
References add_v2_v2(), BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, NearestHit::efa, fabs(), BMLoop::head, BMFace::head, NearestHit::l, BMesh::ldata, BMFace::len, NearestHit::luv, NearestHit::nextl, NearestHit::nextluv, NULL, BMesh::pdata, NearestHit::tf, MLoopUV::uv, uv_find_nearest_edge(), and uvedit_face_visible_test().
Referenced by mouse_select().
static int hide_exec (bContext * C, wmOperator * op) [static]
Definition at line 3018 of file uvedit_ops.c.
References BMEditMesh::bm, bm_face_is_all_uv_sel(), BM_face_select_set(), BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_select_history_validate(), BM_vert_select_set(), BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CTX_data_edit_object(), CTX_data_scene(), CTX_data_tool_settings(), CTX_wm_space_image(), CustomData_bmesh_get(), BMHeader::data, Object::data, EDBM_mesh_hide(), EDBM_selectmode_flush_ex(), FALSE, MLoopUV::flag, BMLoop::head, BMFace::head, SpaceImage::image, BMesh::ldata, MLOOPUV_VERTSEL, NC_GEOM, ND_SELECT, NULL, OPERATOR_FINISHED, BMesh::pdata, wmOperator::ptr, RNA_boolean_get(), SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, swap(), TRUE, ToolSettings::uv_flag, UV_SEL_TEST, UV_SELECT_FACE, ToolSettings::uv_selectmode, UV_SYNC_SELECTION, uvedit_face_select_disable(), uvedit_face_visible_test(), BMLoop::v, and WM_event_add_notifier().
Referenced by UV_OT_hide().
static int is_image_texture_node (bNode * node) [static]
Definition at line 130 of file uvedit_ops.c.
References ELEM, SH_NODE_TEX_ENVIRONMENT, SH_NODE_TEX_IMAGE, and bNode::type.
Referenced by ED_object_assign_active_image(), and ED_object_get_active_image().
static int mark_seam_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3505 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_flag_enable, BM_ELEM_SEAM, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, CTX_data_edit_object(), CTX_data_scene(), DAG_id_tag_update(), Object::data, Mesh::drawflag, ED_unwrap_lscm(), ToolSettings::edge_mode_live_unwrap, Mesh::edit_btmesh, FALSE, Mesh::id, ME_DRAWSEAMS, NC_GEOM, ND_DATA, OPERATOR_FINISHED, Scene::toolsettings, uvedit_edge_select_test(), and WM_event_add_notifier().
Referenced by UV_OT_mark_seam().
static int mouse_select (bContext * C, float co[2], int extend, int loop) [static]
Definition at line 1719 of file uvedit_ops.c.
References BLI_array_declare, BLI_array_free, BLI_array_growitems, BMEditMesh::bm, BM_active_face_set(), BM_elem_index_get, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_index_ensure(), BM_select_history_validate(), BM_VERT, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CTX_data_edit_image(), CTX_data_edit_object(), CTX_data_scene(), CTX_data_tool_settings(), CTX_wm_space_image(), CustomData_bmesh_get(), DAG_id_tag_update(), Object::data, BMHeader::data, EDBM_deselect_flush(), EDBM_select_flush(), EDBM_selectmode_flush(), NearestHit::efa, FALSE, fill_vn_i(), find_nearest_uv_face(), BMFace::head, BMLoop::head, i, NearestHit::l, BMesh::ldata, BMFace::len, NearestHit::lindex, NearestHit::luv, NC_GEOM, ND_SELECT, NearestHit::nextluv, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, BMesh::pdata, SCE_SELECT_EDGE, SCE_SELECT_FACE, SEL_DESELECT, select_all_perform(), select_edgeloop(), select_linked(), ToolSettings::selectmode, SI_STICKY_DISABLE, SpaceImage::sticky, sticky_select(), TRUE, MLoopUV::uv, uv_find_nearest_edge(), uv_find_nearest_vert(), ToolSettings::uv_flag, UV_SELECT_EDGE, UV_SELECT_FACE, UV_SELECT_ISLAND, UV_SELECT_VERTEX, ToolSettings::uv_selectmode, UV_SYNC_SELECTION, uvedit_edge_select_disable(), uvedit_edge_select_enable(), uvedit_edge_select_test(), uvedit_face_select_disable(), uvedit_face_select_enable(), uvedit_face_select_test(), uvedit_face_visible_test(), uvedit_pixel_to_float(), uvedit_uv_select_disable(), uvedit_uv_select_enable(), uvedit_uv_select_test(), BMLoop::v, NearestHit::vert1, NearestHit::vert2, WM_event_add_notifier(), and SpaceImage::zoom.
Referenced by select_exec(), and select_loop_exec().
static int nearest_uv_between (BMEditMesh * em, BMFace * efa, int UNUSEDnverts, int id, float co[2], float uv[2]) [static]
Definition at line 754 of file uvedit_ops.c.
References BMEditMesh::bm, BM_ITER_ELEM, BM_LOOPS_OF_FACE, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::head, i, BMesh::ldata, BMFace::len, sub_v3_v3v3(), and MLoopUV::uv.
Referenced by uv_find_nearest_vert().
static int pin_exec (bContext * C, wmOperator * op) [static]
Definition at line 2897 of file uvedit_ops.c.
References BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, clear(), CTX_data_edit_image(), CTX_data_edit_object(), CTX_data_scene(), CustomData_bmesh_get(), Object::data, BMHeader::data, MLoopUV::flag, BMLoop::head, BMFace::head, BMesh::ldata, MLOOPUV_PINNED, NC_GEOM, ND_DATA, OPERATOR_FINISHED, BMesh::pdata, wmOperator::ptr, RNA_boolean_get(), uvedit_face_visible_test(), uvedit_uv_select_test(), and WM_event_add_notifier().
Referenced by UV_OT_pin().
void poly_copy_aspect (float uv_orig[][2], float uv[][2], float aspx, float aspy, int len)
Definition at line 575 of file uvedit_ops.c.
References i, and len().
Referenced by draw_uvs_stretch().
float poly_uv_area (float uv[][2], int len)
Definition at line 562 of file uvedit_ops.c.
References area_tri_v2().
Referenced by draw_uvs_stretch().
void poly_uv_center (BMEditMesh * em, BMFace * f, float cent[2])
Definition at line 525 of file uvedit_ops.c.
References add_v2_v2(), BMEditMesh::bm, BM_ITER_ELEM, BM_LOOPS_OF_FACE, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::head, BMesh::ldata, BMFace::len, mul_v2_fl(), MLoopUV::uv, and zero_v2().
Referenced by border_select_exec(), and draw_uvs().
static int reveal_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3133 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ELEM_TAG, BM_FACE, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_hflag_enable_test(), BMEdit_FromObject(), CD_MLOOPUV, CTX_data_edit_object(), CTX_data_tool_settings(), CTX_wm_space_image(), CustomData_bmesh_get(), BMHeader::data, Object::data, EDBM_mesh_reveal(), MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, NC_GEOM, ND_SELECT, OPERATOR_FINISHED, SCE_SELECT_FACE, BMEditMesh::selectmode, SI_STICKY_DISABLE, SpaceImage::sticky, TRUE, ToolSettings::uv_flag, UV_SELECT_FACE, ToolSettings::uv_selectmode, UV_SYNC_SELECTION, BMLoop::v, and WM_event_add_notifier().
Referenced by UV_OT_reveal().
static int seams_from_islands_exec (bContext * C, wmOperator * op) [static]
Definition at line 3376 of file uvedit_ops.c.
References CTX_data_edit_object(), Object::data, and STD_UV_CONNECT_LIMIT.
Referenced by UV_OT_seams_from_islands().
static int select_all_exec (bContext * C, wmOperator * op) [static]
Definition at line 1663 of file uvedit_ops.c.
References BMEdit_FromObject(), CTX_data_edit_image(), CTX_data_edit_object(), CTX_data_scene(), Object::data, NC_GEOM, ND_SELECT, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), select_all_perform(), and WM_event_add_notifier().
Referenced by UV_OT_select_all().
static void select_all_perform (Scene * scene, Image * ima, BMEditMesh * em, int action) [static]
Definition at line 1590 of file uvedit_ops.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, EDBM_flag_disable_all(), EDBM_flag_enable_all(), EDBM_select_swap(), EDBM_select_toggle_all(), EDBM_selectmode_flush(), MLoopUV::flag, BMLoop::head, BMFace::head, BMesh::ldata, MLOOPUV_VERTSEL, BMesh::pdata, SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, Scene::toolsettings, ToolSettings::uv_flag, UV_SYNC_SELECTION, and uvedit_face_visible_test().
Referenced by border_select_exec(), mouse_select(), select_all_exec(), and select_edgeloop().
static int select_edgeloop (Scene * scene, Image * ima, BMEditMesh * em, NearestHit * hit, float limit[2], const short extend) [static]
Definition at line 997 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_TAG, BM_FACE, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_hflag_disable_all(), BM_mesh_elem_index_ensure(), BM_VERT, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, EDBM_index_arrays_free(), EDBM_index_arrays_init(), EDBM_uv_vert_map_create(), EDBM_uv_vert_map_free(), NearestHit::efa, FALSE, UvMapVert::flag, BMFace::head, NearestHit::l, BMFace::len, NearestHit::lindex, BMesh::pdata, SEL_DESELECT, select_all_perform(), select_edgeloop_uv_edge_tag_faces(), select_edgeloop_uv_vertex_loop_flag(), select_edgeloop_uv_vertex_map_get(), uvedit_face_visible_test(), uvedit_uv_select_disable(), uvedit_uv_select_enable(), and uvedit_uv_select_test().
Referenced by mouse_select().
static int select_edgeloop_uv_edge_tag_faces (BMEditMesh * em, UvMapVert * first1, UvMapVert * first2, int * totface) [static]
Definition at line 945 of file uvedit_ops.c.
References BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_TAG, EDBM_face_at_index(), UvMapVert::f, UvMapVert::next, and UvMapVert::separate.
Referenced by select_edgeloop().
static void select_edgeloop_uv_vertex_loop_flag (UvMapVert * first) [static]
Definition at line 911 of file uvedit_ops.c.
References UvMapVert::flag, UvMapVert::next, and UvMapVert::separate.
Referenced by select_edgeloop().
static UvMapVert* select_edgeloop_uv_vertex_map_get (UvVertMap * vmap, BMFace * efa, int a) [static]
Definition at line 927 of file uvedit_ops.c.
References BM_elem_index_get, BM_iter_at_index(), BM_LOOPS_OF_FACE, EDBM_uv_vert_map_at_index(), UvMapVert::f, UvMapVert::next, NULL, UvMapVert::separate, and BMLoop::v.
Referenced by select_edgeloop().
static int select_exec (bContext * C, wmOperator * op) [static]
Definition at line 2031 of file uvedit_ops.c.
References co, mouse_select(), wmOperator::ptr, RNA_boolean_get(), and RNA_float_get_array().
Referenced by select_invoke(), and UV_OT_select().
static int select_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2043 of file uvedit_ops.c.
References co, CTX_wm_region(), wmEvent::mval, wmOperator::ptr, RNA_float_set_array(), select_exec(), UI_view2d_region_to_view(), and ARegion::v2d.
Referenced by UV_OT_select().
static void select_linked (Scene * scene, Image * ima, BMEditMesh * em, float limit[2], NearestHit * hit, int extend) [static]
Definition at line 1108 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_index_get, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_ITER_MESH_INDEX, BM_LOOPS_OF_FACE, CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, EDBM_index_arrays_free(), EDBM_index_arrays_init(), EDBM_uv_vert_map_at_index(), EDBM_uv_vert_map_create(), EDBM_uv_vert_map_free(), NearestHit::efa, UvMapVert::f, MLoopUV::flag, BMLoop::head, BMFace::head, i, BMesh::ldata, MEM_callocN(), MEM_freeN(), MEM_mallocN(), MLOOPUV_VERTSEL, UvMapVert::next, NULL, BMesh::pdata, UvMapVert::separate, stack, BMesh::totface, uvedit_face_visible_test(), and BMLoop::v.
Referenced by mouse_select(), and select_linked_internal().
static int select_linked_exec (bContext * C, wmOperator * op) [static]
Definition at line 2169 of file uvedit_ops.c.
References NULL, and select_linked_internal().
Referenced by UV_OT_select_linked().
static int select_linked_internal (bContext * C, wmOperator * op, wmEvent * event, int pick) [static]
Definition at line 2121 of file uvedit_ops.c.
References BKE_report(), BMEdit_FromObject(), co, CTX_data_edit_image(), CTX_data_edit_object(), CTX_data_scene(), CTX_data_tool_settings(), CTX_wm_region(), CTX_wm_space_image(), DAG_id_tag_update(), Object::data, wmEvent::mval, NC_GEOM, ND_SELECT, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_float_get_array(), RNA_float_set_array(), RPT_ERROR, select_linked(), UI_view2d_region_to_view(), uv_find_nearest_vert(), ToolSettings::uv_flag, UV_SYNC_SELECTION, uvedit_pixel_to_float(), ARegion::v2d, and WM_event_add_notifier().
Referenced by select_linked_exec(), select_linked_pick_exec(), and select_linked_pick_invoke().
static int select_linked_pick_exec (bContext * C, wmOperator * op) [static]
Definition at line 2196 of file uvedit_ops.c.
References NULL, and select_linked_internal().
Referenced by UV_OT_select_linked_pick().
static int select_linked_pick_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2191 of file uvedit_ops.c.
References select_linked_internal().
Referenced by UV_OT_select_linked_pick().
static int select_loop_exec (bContext * C, wmOperator * op) [static]
Definition at line 2076 of file uvedit_ops.c.
References co, mouse_select(), wmOperator::ptr, RNA_boolean_get(), and RNA_float_get_array().
Referenced by select_loop_invoke(), and UV_OT_select_loop().
static int select_loop_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2088 of file uvedit_ops.c.
References co, CTX_wm_region(), wmEvent::mval, wmOperator::ptr, RNA_float_set_array(), select_loop_exec(), UI_view2d_region_to_view(), and ARegion::v2d.
Referenced by UV_OT_select_loop().
static int select_pinned_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2952 of file uvedit_ops.c.
References BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CTX_data_edit_image(), CTX_data_edit_object(), CTX_data_scene(), CustomData_bmesh_get(), Object::data, BMHeader::data, FALSE, MLoopUV::flag, BMLoop::head, BMFace::head, BMesh::ldata, MLOOPUV_PINNED, NC_GEOM, ND_SELECT, OPERATOR_FINISHED, BMesh::pdata, uvedit_face_visible_test(), uvedit_uv_select_enable(), and WM_event_add_notifier().
Referenced by UV_OT_select_pinned().
static void select_uv_inside_ellipse (BMEditMesh * em, SpaceImage * UNUSEDsima, Scene * scene, int select, float * offset, float * ell, BMLoop * l, MLoopUV * luv) [static]
Definition at line 2563 of file uvedit_ops.c.
References FALSE, MLoopUV::uv, uvedit_uv_select_disable(), and uvedit_uv_select_enable().
Referenced by circle_select_exec().
static int set_2d_cursor_exec (bContext * C, wmOperator * op) [static]
Definition at line 3262 of file uvedit_ops.c.
References CTX_wm_space_image(), SpaceImage::cursor, NC_SPACE, ND_SPACE_IMAGE, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get_array(), and WM_event_add_notifier().
Referenced by set_2d_cursor_invoke(), and UV_OT_cursor_set().
static int set_2d_cursor_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 3279 of file uvedit_ops.c.
References CTX_wm_region(), wmEvent::mval, wmOperator::ptr, RNA_float_set_array(), set_2d_cursor_exec(), UI_view2d_region_to_view(), and ARegion::v2d.
Referenced by UV_OT_cursor_set().
static int set_tile_exec (bContext * C, wmOperator * op) [static]
Definition at line 3311 of file uvedit_ops.c.
References CTX_data_edit_image(), CTX_data_edit_object(), Object::data, NC_GEOM, NC_SPACE, ND_DATA, ND_SPACE_IMAGE, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_int_get_array(), uvedit_set_tile(), WM_event_add_notifier(), and Image::xrep.
Referenced by set_tile_invoke(), and UV_OT_tile_set().
static int set_tile_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 3329 of file uvedit_ops.c.
References CTX_data_edit_image(), CTX_wm_region(), CTX_wm_space_image(), SpaceImage::curtile, IMA_TILES, wmEvent::mval, OPERATOR_CANCELLED, wmOperator::ptr, RNA_int_set_array(), set_tile_exec(), Image::tpageflag, UI_view2d_region_to_view(), ARegion::v2d, Image::xrep, and Image::yrep.
Referenced by UV_OT_tile_set().
static int snap_cursor_exec (bContext * C, wmOperator * op) [static]
Definition at line 2675 of file uvedit_ops.c.
References CTX_data_edit_image(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_space_image(), NC_SPACE, ND_SPACE_IMAGE, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), snap_cursor_to_pixels(), snap_cursor_to_selection(), and WM_event_add_notifier().
Referenced by UV_OT_snap_cursor().
static void snap_cursor_to_pixels (SpaceImage * sima) [static]
Definition at line 2662 of file uvedit_ops.c.
References SpaceImage::cursor, ED_space_image_size(), and snap_uv_to_pixel().
Referenced by snap_cursor_exec().
static int snap_cursor_to_selection (Scene * scene, Image * ima, Object * obedit, SpaceImage * sima) [static]
Definition at line 2670 of file uvedit_ops.c.
References SpaceImage::around, SpaceImage::cursor, and uvedit_center().
Referenced by snap_cursor_exec().
static int snap_selection_exec (bContext * C, wmOperator * op) [static]
Definition at line 2843 of file uvedit_ops.c.
References CTX_data_edit_image(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_space_image(), DAG_id_tag_update(), Object::data, NC_GEOM, ND_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), snap_uvs_to_adjacent_unselected(), snap_uvs_to_cursor(), snap_uvs_to_pixels(), uvedit_live_unwrap_update(), and WM_event_add_notifier().
Referenced by UV_OT_snap_selected().
static void snap_uv_to_pixel (float * uvco, float w, float h) [static]
Definition at line 2656 of file uvedit_ops.c.
Referenced by snap_cursor_to_pixels(), and snap_uvs_to_pixels().
static int snap_uvs_to_adjacent_unselected (Scene * scene, Image * ima, Object * obedit) [static]
Definition at line 2751 of file uvedit_ops.c.
References add_v2_v2(), BMEditMesh::bm, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_set, BM_elem_flag_test, BM_ELEM_TAG, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_LOOPS_OF_VERT, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, BMLoop::f, FALSE, BMLoop::head, BMFace::head, BMesh::ldata, mul_v2_v2fl(), BMesh::pdata, TRUE, MLoopUV::uv, uvedit_face_visible_test(), uvedit_uv_select_test(), and BMLoop::v.
Referenced by snap_selection_exec().
static int snap_uvs_to_cursor (Scene * scene, Image * ima, Object * obedit, SpaceImage * sima) [static]
Definition at line 2724 of file uvedit_ops.c.
References BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, copy_v2_v2(), SpaceImage::cursor, CustomData_bmesh_get(), BMHeader::data, BMLoop::head, BMFace::head, BMesh::ldata, BMesh::pdata, MLoopUV::uv, uvedit_face_visible_test(), and uvedit_uv_select_test().
Referenced by snap_selection_exec().
static int snap_uvs_to_pixels (SpaceImage * sima, Scene * scene, Object * obedit) [static]
Definition at line 2808 of file uvedit_ops.c.
References BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, ED_space_image_size(), BMLoop::head, BMFace::head, SpaceImage::image, BMesh::ldata, BMesh::pdata, snap_uv_to_pixel(), MLoopUV::uv, uvedit_face_visible_test(), and uvedit_uv_select_test().
Referenced by snap_selection_exec().
static int sticky_select (float * limit, int hitv[4], int v, float * hituv[4], float * uv, int sticky, int hitlen) [static]
Definition at line 1696 of file uvedit_ops.c.
References fabsf, i, SI_STICKY_DISABLE, SI_STICKY_LOC, and SI_STICKY_VERTEX.
Referenced by mouse_select().
static int unlink_selection_exec (bContext * C, wmOperator * op) [static]
Definition at line 2224 of file uvedit_ops.c.
References BKE_report(), BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CTX_data_edit_image(), CTX_data_edit_object(), CTX_data_scene(), CTX_data_tool_settings(), CustomData_bmesh_get(), DAG_id_tag_update(), Object::data, BMHeader::data, MLoopUV::flag, BMLoop::head, BMFace::head, BMesh::ldata, MLOOPUV_VERTSEL, NC_GEOM, ND_SELECT, OPERATOR_CANCELLED, OPERATOR_FINISHED, BMesh::pdata, wmOperator::reports, RPT_ERROR, ToolSettings::uv_flag, UV_SYNC_SELECTION, uvedit_face_visible_test(), and WM_event_add_notifier().
Referenced by UV_OT_unlink_selected().
float uv_area (float uv[][2], int quad)
Definition at line 554 of file uvedit_ops.c.
References area_tri_v2().
void uv_center (float uv[][2], float cent[2], int quad)
Definition at line 542 of file uvedit_ops.c.
static void uv_faces_do_sticky (bContext * C, SpaceImage * sima, Scene * scene, Object * obedit, short select) [static]
Definition at line 2294 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_elem_index_get, BM_ELEM_TAG, BM_FACES_OF_MESH, BM_iter_at_index(), BM_ITER_ELEM, BM_ITER_MESH, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BM_VERTS_OF_MESH, BMEdit_FromObject(), CTX_data_tool_settings(), EDBM_face_at_index(), EDBM_index_arrays_free(), EDBM_index_arrays_init(), EDBM_uv_vert_map_at_index(), EDBM_uv_vert_map_create(), EDBM_uv_vert_map_free(), FALSE, UvMapVert::next, NULL, UvMapVert::separate, SI_STICKY_LOC, SI_STICKY_VERTEX, SpaceImage::sticky, ToolSettings::uv_flag, UV_SYNC_SELECTION, uvedit_face_select_disable(), uvedit_face_select_enable(), uvedit_pixel_to_float(), uvedit_uv_select_disable(), uvedit_uv_select_enable(), and BMLoop::v.
Referenced by border_select_exec().
void uv_find_nearest_edge (Scene * scene, Image * ima, BMEditMesh * em, float co[2], NearestHit * hit)
Definition at line 666 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_index_get, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_index_ensure(), BM_VERT, CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, dist_to_line_segment_v2(), NearestHit::efa, BMLoop::head, BMFace::head, i, NearestHit::l, BMesh::ldata, NearestHit::lindex, NearestHit::luv, BMLoop::next, NearestHit::nextl, NearestHit::nextluv, BMesh::pdata, NearestHit::tf, MLoopUV::uv, uvedit_face_visible_test(), BMLoop::v, NearestHit::vert1, and NearestHit::vert2.
Referenced by find_nearest_uv_face(), mouse_select(), and uv_find_nearest_vert().
void uv_find_nearest_vert (Scene * scene, Image * ima, BMEditMesh * em, float co[2], float penalty[2], NearestHit * hit)
Definition at line 800 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_index_get, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_index_ensure(), BM_VERT, CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, NearestHit::efa, fabs(), BMLoop::head, BMFace::head, i, NearestHit::l, BMesh::ldata, BMFace::len, NearestHit::lindex, NearestHit::luv, nearest_uv_between(), BMLoop::next, NearestHit::nextl, NearestHit::nextluv, NULL, BMesh::pdata, NearestHit::tf, MLoopUV::uv, uv_find_nearest_edge(), uvedit_face_visible_test(), uvedit_uv_select_test(), BMLoop::v, and NearestHit::vert1.
Referenced by mouse_select(), select_linked_internal(), stitch_select(), and uv_sculpt_stroke_init().
static void UV_OT_align (wmOperatorType * ot) [static]
Definition at line 1540 of file uvedit_ops.c.
References align_exec(), wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
static void UV_OT_circle_select (wmOperatorType * ot) [static]
Definition at line 2630 of file uvedit_ops.c.
References wmOperatorType::cancel, circle_select_exec(), wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, WM_gesture_circle_cancel(), WM_gesture_circle_invoke(), and WM_gesture_circle_modal().
Referenced by ED_operatortypes_uvedit().
static void UV_OT_cursor_set (wmOperatorType * ot) [static]
Definition at line 3290 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_vector(), set_2d_cursor_exec(), set_2d_cursor_invoke(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
static void UV_OT_hide (wmOperatorType * ot) [static]
Definition at line 3115 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, hide_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
static void UV_OT_mark_seam (wmOperatorType * ot) [static]
Definition at line 3536 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, mark_seam_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_uvedit().
static void UV_OT_pin (wmOperatorType * ot) [static]
Definition at line 2934 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, pin_exec(), wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
static void UV_OT_reveal (wmOperatorType * ot) [static]
Definition at line 3247 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and reveal_exec().
Referenced by ED_operatortypes_uvedit().
static void UV_OT_seams_from_islands (wmOperatorType * ot) [static]
Definition at line 3487 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), seams_from_islands_exec(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
static void UV_OT_select (wmOperatorType * ot) [static]
Definition at line 2054 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_vector(), select_exec(), select_invoke(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
static void UV_OT_select_all (wmOperatorType * ot) [static]
Definition at line 1679 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, select_all_exec(), and WM_operator_properties_select_all().
Referenced by ED_operatortypes_uvedit().
static void UV_OT_select_border (wmOperatorType * ot) [static]
Definition at line 2538 of file uvedit_ops.c.
References border_select_exec(), wmOperatorType::cancel, wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, TRUE, WM_border_select_cancel(), WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by ED_operatortypes_uvedit().
static void UV_OT_select_linked (wmOperatorType * ot) [static]
Definition at line 2174 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), select_linked_exec(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
static void UV_OT_select_linked_pick (wmOperatorType * ot) [static]
Definition at line 2201 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_vector(), select_linked_pick_exec(), select_linked_pick_invoke(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
static void UV_OT_select_loop (wmOperatorType * ot) [static]
Definition at line 2099 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_vector(), select_loop_exec(), select_loop_invoke(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
static void UV_OT_select_pinned (wmOperatorType * ot) [static]
Definition at line 2982 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and select_pinned_exec().
Referenced by ED_operatortypes_uvedit().
static void UV_OT_snap_cursor (wmOperatorType * ot) [static]
Definition at line 2701 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), snap_cursor_exec(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
static void UV_OT_snap_selected (wmOperatorType * ot) [static]
Definition at line 2873 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), snap_selection_exec(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
static void UV_OT_tile_set (wmOperatorType * ot) [static]
Definition at line 3356 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int_vector(), set_tile_exec(), set_tile_invoke(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
static void UV_OT_unlink_selected (wmOperatorType * ot) [static]
Definition at line 2272 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and unlink_selection_exec().
Referenced by ED_operatortypes_uvedit().
static void UV_OT_weld (wmOperatorType * ot) [static]
Definition at line 1574 of file uvedit_ops.c.
References wmOperatorType::description, ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and weld_exec().
Referenced by ED_operatortypes_uvedit().
static float* uv_sel_co_from_eve (Scene * scene, Image * ima, BMEditMesh * em, BMVert * eve) [static]
Definition at line 1285 of file uvedit_ops.c.
References BMEditMesh::bm, BM_ITER_ELEM, BM_LOOPS_OF_VERT, CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, BMLoop::f, BMLoop::head, BMFace::head, BMesh::ldata, NULL, BMesh::pdata, MLoopUV::uv, uvedit_face_visible_test(), and uvedit_uv_select_test().
Referenced by weld_align_uv().
static int uvedit_center (Scene * scene, Image * ima, Object * obedit, float cent[2], char mode) [static]
Definition at line 644 of file uvedit_ops.c.
References ED_uvedit_median(), ED_uvedit_minmax(), FALSE, max, mid_v2_v2v2(), min, TRUE, and V3D_CENTER.
Referenced by snap_cursor_to_selection(), and weld_align_uv().
void uvedit_edge_select_disable (BMEditMesh * em, Scene * scene, BMLoop * l)
Definition at line 432 of file uvedit_ops.c.
References BMEditMesh::bm, BM_edge_select_set(), BM_face_select_set(), BM_vert_select_set(), CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::e, BMLoop::f, FALSE, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, BMLoop::next, SCE_SELECT_EDGE, SCE_SELECT_FACE, ToolSettings::selectmode, Scene::toolsettings, ToolSettings::uv_flag, UV_SYNC_SELECTION, BMEdge::v1, and BMEdge::v2.
Referenced by mouse_select().
void uvedit_edge_select_enable (BMEditMesh * em, Scene * scene, BMLoop * l, const short do_history)
Definition at line 402 of file uvedit_ops.c.
References BMEditMesh::bm, BM_edge_select_set(), BM_face_select_set(), BM_select_history_store, BM_vert_select_set(), CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::e, BMLoop::f, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, BMLoop::next, SCE_SELECT_EDGE, SCE_SELECT_FACE, ToolSettings::selectmode, Scene::toolsettings, TRUE, ToolSettings::uv_flag, UV_SYNC_SELECTION, BMEdge::v1, and BMEdge::v2.
Referenced by mouse_select().
int uvedit_edge_select_test (BMEditMesh * em, Scene * scene, BMLoop * l)
Definition at line 376 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::e, BMLoop::f, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, BMLoop::next, SCE_SELECT_EDGE, SCE_SELECT_FACE, ToolSettings::selectmode, Scene::toolsettings, ToolSettings::uv_flag, UV_SYNC_SELECTION, and BMLoop::v.
Referenced by draw_uvs(), mark_seam_exec(), and mouse_select().
int uvedit_face_select_disable (Scene * scene, BMEditMesh * em, BMFace * efa)
Definition at line 353 of file uvedit_ops.c.
References BMEditMesh::bm, BM_face_select_set(), BM_ITER_ELEM, BM_LOOPS_OF_FACE, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, FALSE, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, Scene::toolsettings, ToolSettings::uv_flag, and UV_SYNC_SELECTION.
Referenced by hide_exec(), mouse_select(), and uv_faces_do_sticky().
int uvedit_face_select_enable (Scene * scene, BMEditMesh * em, BMFace * efa, const short do_history)
Definition at line 327 of file uvedit_ops.c.
References BMEditMesh::bm, BM_face_select_set(), BM_ITER_ELEM, BM_LOOPS_OF_FACE, BM_select_history_store, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, Scene::toolsettings, TRUE, ToolSettings::uv_flag, and UV_SYNC_SELECTION.
Referenced by ED_uvedit_ensure_uvs(), mouse_select(), and uv_faces_do_sticky().
int uvedit_face_select_test (Scene * scene, BMEditMesh * em, BMFace * efa)
Definition at line 306 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_ELEM, BM_LOOPS_OF_FACE, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, Scene::toolsettings, ToolSettings::uv_flag, and UV_SYNC_SELECTION.
Referenced by draw_uvs(), and mouse_select().
int uvedit_face_visible_nolocal (Scene * scene, BMFace * efa)
Definition at line 286 of file uvedit_ops.c.
References BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, Scene::toolsettings, ToolSettings::uv_flag, and UV_SYNC_SELECTION.
Referenced by uvedit_face_visible_test().
int uvedit_face_visible_test (Scene * scene, Image * ima, BMFace * efa, MTexPoly * tf)
Definition at line 296 of file uvedit_ops.c.
References Scene::toolsettings, MTexPoly::tpage, ToolSettings::uv_flag, UV_SHOW_SAME_IMAGE, and uvedit_face_visible_nolocal().
Referenced by border_select_exec(), createTransUVs(), draw_uvs(), draw_uvs_stretch(), ED_uvedit_assign_image(), ED_uvedit_median(), ED_uvedit_minmax(), ED_uvedit_nearest_uv(), find_nearest_uv_face(), hide_exec(), mouse_select(), pin_exec(), select_all_perform(), select_edgeloop(), select_linked(), select_pinned_exec(), snap_uvs_to_adjacent_unselected(), snap_uvs_to_cursor(), snap_uvs_to_pixels(), unlink_selection_exec(), uv_find_nearest_edge(), uv_find_nearest_vert(), uv_sel_co_from_eve(), uvedit_center(), and weld_align_uv().
void uvedit_live_unwrap_update (SpaceImage * sima, Scene * scene, Object * obedit)
Definition at line 515 of file uvedit_ops.c.
References ED_uvedit_live_unwrap_begin(), ED_uvedit_live_unwrap_end(), ED_uvedit_live_unwrap_re_solve(), SpaceImage::flag, and SI_LIVE_UNWRAP.
Referenced by snap_selection_exec(), stitch_exit(), and weld_align_uv().
static void uvedit_pixel_to_float (SpaceImage * sima, float * dist, float pixeldist) [static]
Definition at line 268 of file uvedit_ops.c.
References ED_space_image_size().
Referenced by mouse_select(), select_linked_internal(), and uv_faces_do_sticky().
static int uvedit_set_tile (Object * obedit, Image * ima, int curtile) [static]
Definition at line 234 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_MESH, BMEdit_FromObject(), CD_MTEXPOLY, CustomData_bmesh_get(), DAG_id_tag_update(), Object::data, BMHeader::data, ED_uvedit_test(), BMFace::head, IMA_TILES, IMA_TYPE_COMPOSITE, IMA_TYPE_R_RESULT, BMesh::pdata, MTexPoly::tile, Image::tpageflag, and Image::type.
Referenced by set_tile_exec().
void uvedit_uv_select_disable (BMEditMesh * em, Scene * scene, BMLoop * l)
Definition at line 496 of file uvedit_ops.c.
References BMEditMesh::bm, BM_face_select_set(), BM_vert_select_set(), CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::f, FALSE, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, SCE_SELECT_FACE, ToolSettings::selectmode, Scene::toolsettings, ToolSettings::uv_flag, UV_SYNC_SELECTION, and BMLoop::v.
Referenced by border_select_exec(), mouse_select(), select_edgeloop(), select_uv_inside_ellipse(), and uv_faces_do_sticky().
void uvedit_uv_select_enable (BMEditMesh * em, Scene * scene, BMLoop * l, const short do_history)
Definition at line 475 of file uvedit_ops.c.
References BMEditMesh::bm, BM_face_select_set(), BM_select_history_remove, BM_vert_select_set(), CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::f, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, SCE_SELECT_FACE, ToolSettings::selectmode, Scene::toolsettings, TRUE, ToolSettings::uv_flag, UV_SYNC_SELECTION, and BMLoop::v.
Referenced by border_select_exec(), mouse_select(), select_edgeloop(), select_pinned_exec(), select_uv_inside_ellipse(), stitch_process_data(), and uv_faces_do_sticky().
int uvedit_uv_select_test (BMEditMesh * em, Scene * scene, BMLoop * l)
Definition at line 458 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::f, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_VERTSEL, SCE_SELECT_FACE, ToolSettings::selectmode, Scene::toolsettings, ToolSettings::uv_flag, UV_SYNC_SELECTION, and BMLoop::v.
Referenced by construct_param_handle(), createTransUVs(), draw_uvs(), ED_uvedit_median(), ED_uvedit_minmax(), mouse_select(), pin_exec(), select_edgeloop(), snap_uvs_to_adjacent_unselected(), snap_uvs_to_cursor(), snap_uvs_to_pixels(), stitch_init(), texface_from_original_index(), uv_find_nearest_vert(), uv_sel_co_from_eve(), uvedit_center(), uvedit_have_selection(), uvedit_translate(), and weld_align_uv().
static void weld_align_uv (bContext * C, int tool) [static]
Definition at line 1307 of file uvedit_ops.c.
References BLI_array_append, BLI_array_count, BLI_array_declare, BMEditMesh::bm, BM_edge_other_vert(), BM_EDGES_OF_MESH, BM_EDGES_OF_VERT, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_set, BM_elem_flag_test, BM_ELEM_TAG, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_LOOPS_OF_VERT, BM_VERTS_OF_MESH, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, closest_to_line_segment_v2(), CTX_data_edit_image(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_space_image(), CustomData_bmesh_get(), DAG_id_tag_update(), Object::data, BMHeader::data, DO_MINMAX2, BMLoop::f, BMLoop::head, BMFace::head, i, INIT_MINMAX2, BMesh::ldata, max, MEM_freeN(), min, NC_GEOM, ND_DATA, NULL, BMesh::pdata, MLoopUV::uv, uv_sel_co_from_eve(), uvedit_center(), uvedit_face_visible_test(), uvedit_live_unwrap_update(), uvedit_uv_select_test(), BMEdge::v1, BMEdge::v2, and WM_event_add_notifier().
Referenced by align_exec(), and weld_exec().
static int weld_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1567 of file uvedit_ops.c.
References OPERATOR_FINISHED, and weld_align_uv().
Referenced by UV_OT_weld().