Blender: bpy_rna.h File Reference
bpy_rna.h File Reference
Python RNA and Operators
Classes
struct BPy_DummyPointerRNA
struct BPy_StructRNA
struct BPy_PropertyRNA
struct BPy_PropertyArrayRNA
struct BPy_PropertyCollectionIterRNA
struct BPy_FunctionRNA
Defines
#define USE_PYRNA_ITER
#define BPy_StructRNA_Check(v) (PyObject_TypeCheck(v, &pyrna_struct_Type))
#define BPy_StructRNA_CheckExact(v) (Py_TYPE(v) == &pyrna_struct_Type)
#define BPy_PropertyRNA_Check(v) (PyObject_TypeCheck(v, &pyrna_prop_Type))
#define BPy_PropertyRNA_CheckExact(v) (Py_TYPE(v) == &pyrna_prop_Type)
#define PYRNA_STRUCT_CHECK_OBJ(obj) if (UNLIKELY(pyrna_struct_validity_check(obj) == -1)) { return NULL; } (void)0
#define PYRNA_STRUCT_CHECK_INT(obj) if (UNLIKELY(pyrna_struct_validity_check(obj) == -1)) { return -1; } (void)0
#define PYRNA_PROP_CHECK_OBJ(obj) if (UNLIKELY(pyrna_prop_validity_check(obj) == -1)) { return NULL; } (void)0
#define PYRNA_PROP_CHECK_INT(obj) if (UNLIKELY(pyrna_prop_validity_check(obj) == -1)) { return -1; } (void)0
#define PYRNA_STRUCT_IS_VALID(pysrna) (LIKELY(((BPy_StructRNA *)(pysrna))->ptr.type != NULL))
#define PYRNA_PROP_IS_VALID(pysrna) (LIKELY(((BPy_PropertyRNA *)(pysrna))->ptr.type != NULL))
#define BPy_BaseTypeRNA BPy_PropertyRNA
Functions
StructRNA * srna_from_self (PyObject *self, const char *error_prefix)
StructRNA * pyrna_struct_as_srna (PyObject *self, int parent, const char *error_prefix)
void BPY_rna_init (void)
PyObject * BPY_rna_module (void)
void BPY_update_rna_module (void)
PyObject * BPY_rna_types (void)
PyObject * pyrna_struct_CreatePyObject (PointerRNA *ptr)
PyObject * pyrna_prop_CreatePyObject (PointerRNA *ptr, PropertyRNA *prop)
int pyrna_pydict_to_props (PointerRNA *ptr, PyObject *kw, int all_args, const char *error_prefix)
PyObject * pyrna_prop_to_py (PointerRNA *ptr, PropertyRNA *prop)
PyObject * pyrna_enum_bitfield_to_py (struct EnumPropertyItem *items, int value)
int pyrna_set_to_enum_bitfield (EnumPropertyItem *items, PyObject *value, int *r_value, const char *error_prefix)
int pyrna_enum_value_from_id (EnumPropertyItem *item, const char *identifier, int *value, const char *error_prefix)
int pyrna_deferred_register_class (struct StructRNA *srna, PyObject *py_class)
void pyrna_alloc_types (void)
void pyrna_free_types (void)
int pyrna_py_to_array (PointerRNA *ptr, PropertyRNA *prop, char *param_data, PyObject *py, const char *error_prefix)
int pyrna_py_to_array_index (PointerRNA *ptr, PropertyRNA *prop, int arraydim, int arrayoffset, int index, PyObject *py, const char *error_prefix)
PyObject * pyrna_array_index (PointerRNA *ptr, PropertyRNA *prop, int index)
PyObject * pyrna_py_from_array (PointerRNA *ptr, PropertyRNA *prop)
PyObject * pyrna_py_from_array_index (BPy_PropertyArrayRNA *self, PointerRNA *ptr, PropertyRNA *prop, int index)
PyObject * pyrna_math_object_from_array (PointerRNA *ptr, PropertyRNA *prop)
int pyrna_array_contains_py (PointerRNA *ptr, PropertyRNA *prop, PyObject *value)
int pyrna_write_check (void)
void pyrna_write_set (int val)
int pyrna_struct_validity_check (BPy_StructRNA *pysrna)
int pyrna_prop_validity_check (BPy_PropertyRNA *self)
Variables
PyTypeObject pyrna_struct_meta_idprop_Type
PyTypeObject pyrna_struct_Type
PyTypeObject pyrna_prop_Type
PyTypeObject pyrna_prop_array_Type
PyTypeObject pyrna_prop_collection_Type
PyTypeObject pyrna_func_Type
PyMethodDef meth_bpy_register_class
PyMethodDef meth_bpy_unregister_class
Detailed Description
Definition in file bpy_rna.h.
Define Documentation
#define BPy_BaseTypeRNA BPy_PropertyRNA
Definition at line 164 of file bpy_rna.h.
Referenced by BPY_rna_types().
#define BPy_PropertyRNA_Check (v) (PyObject_TypeCheck(v, &pyrna_prop_Type))
Definition at line 83 of file bpy_rna.h.
Referenced by pyrna_dir_members_py(), and pyrna_prop_richcmp().
#define BPy_PropertyRNA_CheckExact (v) (Py_TYPE(v) == &pyrna_prop_Type)
Definition at line 84 of file bpy_rna.h.
Referenced by pyrna_prop_dir().
#define BPy_StructRNA_Check (v) (PyObject_TypeCheck(v, &pyrna_struct_Type))
Definition at line 81 of file bpy_rna.h.
Referenced by BPY_context_member_get(), pyrna_prop_collection_type_check(), pyrna_py_to_prop(), pyrna_struct_as_srna(), and pyrna_struct_richcmp().
#define BPy_StructRNA_CheckExact (v) (Py_TYPE(v) == &pyrna_struct_Type)
Definition at line 82 of file bpy_rna.h.
Referenced by pyrna_struct_dir().
#define PYRNA_PROP_CHECK_INT (obj) if (UNLIKELY(pyrna_prop_validity_check(obj) == -1)) { return -1; } (void)0
Definition at line 90 of file bpy_rna.h.
Referenced by mathutils_rna_generic_check(), mathutils_rna_matrix_get(), mathutils_rna_matrix_set(), mathutils_rna_vector_get(), mathutils_rna_vector_get_index(), mathutils_rna_vector_set(), mathutils_rna_vector_set_index(), prop_subscript_ass_array_int(), pyrna_prop_array_ass_subscript(), pyrna_prop_array_bool(), pyrna_prop_array_length(), pyrna_prop_collection_ass_subscript(), pyrna_prop_collection_ass_subscript_int(), pyrna_prop_collection_bool(), and pyrna_prop_collection_length().
#define PYRNA_PROP_CHECK_OBJ (obj) if (UNLIKELY(pyrna_prop_validity_check(obj) == -1)) { return NULL; } (void)0
Definition at line 89 of file bpy_rna.h.
Referenced by pyrna_prop_array_iter(), pyrna_prop_array_subscript(), pyrna_prop_array_subscript_int(), pyrna_prop_array_subscript_slice(), pyrna_prop_array_to_py_index(), pyrna_prop_collection_find(), pyrna_prop_collection_foreach_get(), pyrna_prop_collection_foreach_set(), pyrna_prop_collection_get(), pyrna_prop_collection_subscript(), pyrna_prop_collection_subscript_int(), pyrna_prop_collection_subscript_slice(), pyrna_prop_collection_subscript_str(), pyrna_prop_repr(), and pyrna_prop_str().
#define PYRNA_PROP_IS_VALID (pysrna) (LIKELY(((BPy_PropertyRNA *)(pysrna))->ptr.type != NULL))
Definition at line 93 of file bpy_rna.h.
#define PYRNA_STRUCT_CHECK_INT (obj) if (UNLIKELY(pyrna_struct_validity_check(obj) == -1)) { return -1; } (void)0
Definition at line 87 of file bpy_rna.h.
Referenced by pyrna_struct_ass_subscript(), pyrna_struct_contains(), and pyrna_struct_setattro().
#define PYRNA_STRUCT_CHECK_OBJ (obj) if (UNLIKELY(pyrna_struct_validity_check(obj) == -1)) { return NULL; } (void)0
Definition at line 86 of file bpy_rna.h.
Referenced by pyrna_struct_dir(), pyrna_struct_driver_add(), pyrna_struct_driver_remove(), pyrna_struct_get(), pyrna_struct_getattro(), pyrna_struct_is_property_hidden(), pyrna_struct_is_property_set(), pyrna_struct_keyframe_delete(), pyrna_struct_keyframe_insert(), pyrna_struct_path_from_id(), pyrna_struct_path_resolve(), pyrna_struct_subscript(), and pyrna_struct_type_recast().
#define PYRNA_STRUCT_IS_VALID (pysrna) (LIKELY(((BPy_StructRNA *)(pysrna))->ptr.type != NULL))
Definition at line 92 of file bpy_rna.h.
Referenced by pyrna_struct_repr(), and pyrna_struct_str().
#define USE_PYRNA_ITER
Definition at line 68 of file bpy_rna.h.
Function Documentation
void BPY_rna_init (void)
Definition at line 6249 of file bpy_rna.c.
References Mathutils_RegisterCallback().
Referenced by BPy_init_modules().
PyObject* BPY_rna_module (void)
Definition at line 6294 of file bpy_rna.c.
References G, BPy_StructRNA::ptr, pyrna_struct_CreatePyObject(), and RNA_main_pointer_create().
Referenced by BPy_init_modules(), and BPY_modules_update().
PyObject* BPY_rna_types (void)
Definition at line 6427 of file bpy_rna.c.
References BPy_BaseTypeRNA, NULL, pyrna_basetype_getattro(), pyrna_basetype_methods, RNA_blender_rna_pointer_create(), and RNA_struct_find_property().
Referenced by BPy_init_modules(), and BPY_modules_update().
void BPY_update_rna_module (void)
Definition at line 6307 of file bpy_rna.c.
References PointerRNA::data, G, and RNA_main_pointer_create().
void pyrna_alloc_types (void)
Definition at line 7179 of file bpy_rna.c.
References pyrna_struct_Subtype(), RNA_blender_rna_pointer_create(), RNA_PROP_BEGIN, RNA_PROP_END, and RNA_struct_find_property().
Referenced by BPY_python_start().
int pyrna_array_contains_py (PointerRNA * ptr, PropertyRNA * prop, PyObject * value)
Definition at line 713 of file bpy_rna_array.c.
References i, len(), NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, RNA_property_array_dimension(), RNA_property_array_length(), RNA_property_boolean_get_array(), RNA_property_float_get_array(), RNA_property_int_get_array(), and RNA_property_type().
Referenced by pyrna_prop_array_contains().
PyObject* pyrna_array_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 598 of file bpy_rna_array.c.
References NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, RNA_property_boolean_get_index(), RNA_property_float_get_index(), RNA_property_int_get_index(), and RNA_property_type().
Referenced by pyrna_py_from_array_index(), and pyrna_struct_path_resolve().
int pyrna_deferred_register_class (struct StructRNA * srna, PyObject * py_class)
Definition at line 6667 of file bpy_rna.c.
References pyrna_deferred_register_class_recursive(), and RNA_struct_idprops_register_check().
Referenced by operator_properties_init(), and pyrna_register_class().
PyObject* pyrna_enum_bitfield_to_py (struct EnumPropertyItem * items, int value)
Definition at line 1241 of file bpy_rna.c.
References NULL, RNA_enum_bitflag_identifiers(), and RNA_ENUM_BITFLAG_SIZE.
Referenced by pyop_call().
int pyrna_enum_value_from_id (EnumPropertyItem * item, const char * identifier, int * value, const char * error_prefix)
Definition at line 732 of file bpy_rna.c.
References BPy_enum_as_string(), MEM_freeN(), and RNA_enum_value_from_id().
Referenced by pyrna_callback_add(), and pyrna_set_to_enum_bitfield().
void pyrna_free_types (void)
Definition at line 7210 of file bpy_rna.c.
References bpy_class_free(), RNA_blender_rna_pointer_create(), RNA_PROP_BEGIN, RNA_PROP_END, RNA_struct_find_property(), RNA_struct_py_type_get(), RNA_struct_py_type_set(), and srna_from_ptr().
Referenced by BPY_python_end().
PyObject* pyrna_math_object_from_array (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 603 of file bpy_rna.c.
References Color_CreatePyObject(), Color_CreatePyObject_cb(), Euler_CreatePyObject(), Euler_CreatePyObject_cb(), EULER_ORDER_XYZ, FALSE, len(), MATHUTILS_CB_SUBTYPE_COLOR, MATHUTILS_CB_SUBTYPE_EUL, MATHUTILS_CB_SUBTYPE_QUAT, MATHUTILS_CB_SUBTYPE_VEC, Matrix_CreatePyObject(), Matrix_CreatePyObject_cb(), NULL, PROP_ALL_VECTOR_SUBTYPES, PROP_COLOR, PROP_COLOR_GAMMA, PROP_DYNAMIC, PROP_EULER, PROP_FLOAT, PROP_MATRIX, PROP_QUATERNION, PROP_THICK_WRAP, Py_NEW, pyrna_prop_array_subscript_slice(), pyrna_prop_CreatePyObject(), pyrna_rotation_euler_order_get(), Quaternion_CreatePyObject(), Quaternion_CreatePyObject_cb(), RNA_property_array_dimension(), RNA_property_array_length(), RNA_property_flag(), RNA_property_float_get_array(), RNA_property_subtype(), RNA_property_type(), Vector_CreatePyObject(), and Vector_CreatePyObject_cb().
Referenced by pyrna_py_from_array().
PyObject* pyrna_prop_CreatePyObject (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 6199 of file bpy_rna.c.
References PointerRNA::data, PointerRNA::id, NULL, BPy_PropertyRNA::prop, PROP_COLLECTION, PROP_IDPROPERTY, BPy_PropertyRNA::ptr, pyrna_prop_collection_idprop_Type, pyrna_prop_collection_Type, pyrna_prop_Type, RNA_property_array_check(), RNA_property_flag(), and RNA_property_type().
Referenced by pyrna_math_object_from_array(), pyrna_prop_to_py(), pyrna_py_from_array(), pyrna_py_from_array_index(), and pyrna_struct_path_resolve().
PyObject* pyrna_prop_to_py (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1333 of file bpy_rna.c.
References PointerRNA::data, ELEM3, MEM_freeN(), NULL, PROP_BOOLEAN, PROP_BYTESTRING, PROP_COLLECTION, PROP_DIRPATH, PROP_ENUM, PROP_FILENAME, PROP_FILEPATH, PROP_FLOAT, PROP_INT, PROP_POINTER, PROP_STRING, PyC_UnicodeFromByteAndSize(), pyrna_enum_to_py(), pyrna_prop_CreatePyObject(), pyrna_py_from_array(), pyrna_struct_CreatePyObject(), RNA_property_array_check(), RNA_property_boolean_get(), RNA_property_enum_get(), RNA_property_float_get(), RNA_property_int_get(), RNA_property_pointer_get(), RNA_property_string_get_alloc(), RNA_property_subtype(), and RNA_property_type().
Referenced by pyrna_prop_collection_getattro(), pyrna_struct_getattro(), and pyrna_struct_path_resolve().
int pyrna_prop_validity_check (BPy_PropertyRNA * self)
Definition at line 109 of file bpy_rna.c.
References RNA_property_identifier().
PyObject* pyrna_py_from_array (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 700 of file bpy_rna_array.c.
References pyrna_math_object_from_array(), and pyrna_prop_CreatePyObject().
Referenced by pyrna_prop_to_py().
PyObject* pyrna_py_from_array_index (BPy_PropertyArrayRNA * self, PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 655 of file bpy_rna_array.c.
References BPy_PropertyArrayRNA::arraydim, BPy_PropertyArrayRNA::arrayoffset, G, G_DEBUG_PYTHON, i, len(), MAX_ARRAY_DIMENSION, NULL, pyrna_array_index(), pyrna_prop_CreatePyObject(), RNA_property_array_dimension(), and RNA_property_multi_array_length().
Referenced by pyrna_prop_array_to_py_index().
int pyrna_py_to_array (PointerRNA * ptr, PropertyRNA * prop, char * param_data, PyObject * py, const char * error_prefix)
Definition at line 548 of file bpy_rna_array.c.
References PROP_BOOLEAN, PROP_FLOAT, PROP_INT, py_bool_check(), py_float_check(), py_int_check(), py_to_array(), py_to_bool(), py_to_float(), py_to_int(), RNA_property_boolean_set_array(), RNA_property_float_set_array(), RNA_property_int_set_array(), and RNA_property_type().
Referenced by pyrna_py_to_prop().
int pyrna_py_to_array_index (PointerRNA * ptr, PropertyRNA * prop, int arraydim, int arrayoffset, int index, PyObject * py, const char * error_prefix)
Definition at line 573 of file bpy_rna_array.c.
References bool_set_index(), float_set_index(), int_set_index(), PROP_BOOLEAN, PROP_FLOAT, PROP_INT, py_bool_check(), py_float_check(), py_int_check(), py_to_array_index(), py_to_bool(), py_to_float(), py_to_int(), and RNA_property_type().
Referenced by pyrna_py_to_prop_array_index().
int pyrna_pydict_to_props (PointerRNA * ptr, PyObject * kw, int all_args, const char * error_prefix)
Definition at line 1418 of file bpy_rna.c.
References NULL, pyrna_py_to_prop(), RNA_property_identifier(), RNA_STRUCT_BEGIN, RNA_STRUCT_END, and RNA_struct_find_property().
Referenced by pyop_as_string(), pyop_call(), and pyrna_py_to_prop().
int pyrna_set_to_enum_bitfield (EnumPropertyItem * items, PyObject * value, int * r_value, const char * error_prefix)
Definition at line 1169 of file bpy_rna.c.
References hash, NULL, and pyrna_enum_value_from_id().
Referenced by pyrna_prop_to_enum_bitfield().
StructRNA* pyrna_struct_as_srna (PyObject * self, int parent, const char * error_prefix)
Definition at line 6453 of file bpy_rna.c.
References bpy_intern_str_bl_rna, BPy_StructRNA_Check, PointerRNA::data, NULL, BPy_StructRNA::ptr, RNA_Struct, and PointerRNA::type.
Referenced by pyrna_register_class(), pyrna_unregister_class(), and srna_from_self().
PyObject* pyrna_struct_CreatePyObject (PointerRNA * ptr)
Definition at line 6151 of file bpy_rna.c.
References PointerRNA::data, FALSE, PointerRNA::id, NULL, BPy_StructRNA::ptr, pyrna_struct_Subtype(), and PointerRNA::type.
Referenced by bpy_app_generic_callback(), bpy_class_call(), BPy_init_modules(), bpy_lib_exit(), BPY_rna_module(), pyop_getinstance(), pyop_getrna(), PYOP_wrap_macro_define(), pyrna_param_to_py(), pyrna_prop_collection_get(), pyrna_prop_collection_getattro(), pyrna_prop_collection_idprop_add(), pyrna_prop_collection_items(), pyrna_prop_collection_iter_next(), pyrna_prop_collection_subscript_int(), pyrna_prop_collection_subscript_slice(), pyrna_prop_collection_subscript_str(), pyrna_prop_collection_subscript_str_lib_pair(), pyrna_prop_to_py(), pyrna_py_to_prop(), pyrna_struct_as_instance(), pyrna_struct_driver_add(), pyrna_struct_get_data(), pyrna_struct_get_id_data(), pyrna_struct_getattro(), pyrna_struct_path_resolve(), pyrna_struct_type_recast(), and pyrna_subtype_set_rna().
int pyrna_struct_validity_check (BPy_StructRNA * pysrna)
Definition at line 98 of file bpy_rna.c.
References BPy_StructRNA::ptr, and PointerRNA::type.
int pyrna_write_check (void)
Definition at line 342 of file bpy_rna.c.
References rna_disallow_writes.
Referenced by bpy_prop_update_cb(), pyop_call(), pyrna_register_class(), pyrna_struct_meta_idprop_setattro(), and pyrna_unregister_class().
void pyrna_write_set (int val)
Definition at line 347 of file bpy_rna.c.
Referenced by bpy_prop_update_cb().
StructRNA* srna_from_self (PyObject * self, const char * error_prefix)
Definition at line 6505 of file bpy_rna.c.
References NULL, and pyrna_struct_as_srna().
Referenced by BPy_RemoveProperty(), pointer_type_from_py(), PYOP_wrap_macro_define(), and pyrna_struct_meta_idprop_setattro().
Variable Documentation
PyMethodDef meth_bpy_register_class
Definition at line 7260 of file bpy_rna.c.
Referenced by BPy_init_modules().
PyMethodDef meth_bpy_unregister_class
Definition at line 7404 of file bpy_rna.c.
Referenced by BPy_init_modules().
PyTypeObject pyrna_func_Type
Definition at line 5708 of file bpy_rna.c.
Referenced by pyrna_func_to_py().
PyTypeObject pyrna_prop_array_Type
Definition at line 5455 of file bpy_rna.c.
PyTypeObject pyrna_prop_collection_Type
Definition at line 5538 of file bpy_rna.c.
Referenced by pyrna_prop_CreatePyObject(), and pyrna_py_to_prop().
PyTypeObject pyrna_prop_Type
Definition at line 5371 of file bpy_rna.c.
Referenced by pyrna_prop_CreatePyObject(), and pyrna_prop_new().
PyTypeObject pyrna_struct_meta_idprop_Type
Definition at line 5197 of file bpy_rna.c.
Referenced by BPy_init_modules().
PyTypeObject pyrna_struct_Type
Definition at line 5282 of file bpy_rna.c.
Referenced by pyrna_struct_new().