Blender: AUD_LowpassFactory Class Reference
AUD_LowpassFactory Class Reference
#include <AUD_LowpassFactory.h>
Public Member Functions
AUD_LowpassFactory (AUD_Reference< AUD_IFactory > factory, float frequency, float Q=1.0f)
virtual void recalculateCoefficients (AUD_SampleRate rate, std::vector< float > &b, std::vector< float > &a)
Detailed Description
This factory creates a lowpass filter reader.
Definition at line 38 of file AUD_LowpassFactory.h.
Constructor & Destructor Documentation
AUD_LowpassFactory::AUD_LowpassFactory (AUD_Reference< AUD_IFactory > factory, float frequency, float Q = 1.0f)
Creates a new lowpass factory.
Parameters:
factory The input factory.
frequency The cutoff frequency.
Q The Q factor.
Definition at line 39 of file AUD_LowpassFactory.cpp.
Member Function Documentation
void AUD_LowpassFactory::recalculateCoefficients (AUD_SampleRate rate, std::vector< float > & b, std::vector< float > & a) [virtual]
Recalculates the filter coefficients.
Parameters:
rate The sample rate of the audio data.
[out] b The input filter coefficients.
[out] a The output filter coefficients.
Implements AUD_DynamicIIRFilterFactory.
Definition at line 47 of file AUD_LowpassFactory.cpp.
References cos(), M_PI, norm(), and sin().
The documentation for this class was generated from the following files:
AUD_LowpassFactory.h
AUD_LowpassFactory.cpp