Blender: thumbs_blend.c File Reference
thumbs_blend.c File Reference
IMage Buffer
#include <string.h>
#include "zlib.h"
#include "BLI_utildefines.h"
#include "BLI_fileops.h"
#include "BKE_utildefines.h"
#include "BKE_global.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_thumbs.h"
#include "MEM_guardedalloc.h"
Defines
#define MARGIN 2
Functions
static ImBuf * loadblend_thumb (gzFile gzfile)
ImBuf * IMB_loadblend_thumb (const char *path)
void IMB_overlayblend_thumb (unsigned int *thumb, int width, int height, float aspect)
Detailed Description
Definition in file thumbs_blend.c.
Define Documentation
#define MARGIN 2
Definition at line 144 of file thumbs_blend.c.
Referenced by IMB_overlayblend_thumb().
Function Documentation
ImBuf* IMB_loadblend_thumb (const char * path)
Definition at line 124 of file thumbs_blend.c.
References BLI_gzopen(), loadblend_thumb(), and NULL.
Referenced by IMB_thumb_create().
void IMB_overlayblend_thumb (unsigned int * thumb, int width, int height, float aspect)
Definition at line 146 of file thumbs_blend.c.
References CLAMP(), and MARGIN.
Referenced by blend_file_thumb().
static ImBuf* loadblend_thumb (gzFile gzfile) [static]
Definition at line 47 of file thumbs_blend.c.
References B_ENDIAN, ENDIAN_ORDER, IB_metadata, IB_rect, IMB_allocImBuf(), IMB_freeImBuf(), L_ENDIAN, NULL, ImBuf::rect, REND, size(), SWITCH_INT, and TEST.
Referenced by IMB_loadblend_thumb().