Blender: MT_Vector4.inl File Reference
MT_Vector4.inl File Reference
#include "MT_Optimize.h"
Functions
GEN_INLINE MT_Vector4 operator+ (const MT_Vector4 &v1, const MT_Vector4 &v2)
GEN_INLINE MT_Vector4 operator- (const MT_Vector4 &v1, const MT_Vector4 &v2)
GEN_INLINE MT_Vector4 operator- (const MT_Vector4 &v)
GEN_INLINE MT_Vector4 operator* (const MT_Vector4 &v, MT_Scalar s)
GEN_INLINE MT_Vector4 operator* (MT_Scalar s, const MT_Vector4 &v)
GEN_INLINE MT_Vector4 operator/ (const MT_Vector4 &v, MT_Scalar s)
GEN_INLINE MT_Scalar MT_dot (const MT_Vector4 &v1, const MT_Vector4 &v2)
GEN_INLINE MT_Scalar MT_length2 (const MT_Vector4 &v)
GEN_INLINE MT_Scalar MT_length (const MT_Vector4 &v)
GEN_INLINE bool MT_fuzzyZero (const MT_Vector4 &v)
GEN_INLINE bool MT_fuzzyEqual (const MT_Vector4 &v1, const MT_Vector4 &v2)
Function Documentation
GEN_INLINE MT_Scalar MT_dot (const MT_Vector4 & v1, const MT_Vector4 & v2)
Definition at line 70 of file MT_Vector4.inl.
References MT_Vector4::dot().
GEN_INLINE bool MT_fuzzyEqual (const MT_Vector4 & v1, const MT_Vector4 & v2)
Definition at line 78 of file MT_Vector4.inl.
References MT_fuzzyZero().
GEN_INLINE bool MT_fuzzyZero (const MT_Vector4 & v)
Definition at line 77 of file MT_Vector4.inl.
References MT_Vector4::fuzzyZero().
GEN_INLINE MT_Scalar MT_length (const MT_Vector4 & v)
Definition at line 75 of file MT_Vector4.inl.
References MT_Vector4::length().
GEN_INLINE MT_Scalar MT_length2 (const MT_Vector4 & v)
Definition at line 74 of file MT_Vector4.inl.
References MT_Vector4::length2().
GEN_INLINE MT_Vector4 operator* (MT_Scalar s, const MT_Vector4 & v)
Definition at line 39 of file MT_Vector4.inl.
GEN_INLINE MT_Vector4 operator* (const MT_Vector4 & v, MT_Scalar s)
Definition at line 35 of file MT_Vector4.inl.
GEN_INLINE MT_Vector4 operator+ (const MT_Vector4 & v1, const MT_Vector4 & v2)
Definition at line 23 of file MT_Vector4.inl.
GEN_INLINE MT_Vector4 operator- (const MT_Vector4 & v1, const MT_Vector4 & v2)
Definition at line 27 of file MT_Vector4.inl.
GEN_INLINE MT_Vector4 operator- (const MT_Vector4 & v)
Definition at line 31 of file MT_Vector4.inl.
GEN_INLINE MT_Vector4 operator/ (const MT_Vector4 & v, MT_Scalar s)
Definition at line 41 of file MT_Vector4.inl.
References MT_assert, and MT_fuzzyZero().