Blender: MultiDevice Class Reference
MultiDevice Class Reference
Classes
struct SubDevice
Public Member Functions
MultiDevice (DeviceInfo &info, bool background_)
~MultiDevice ()
const string & error_message ()
bool load_kernels (bool experimental)
void mem_alloc (device_memory &mem, MemoryType type)
void mem_copy_to (device_memory &mem)
void mem_copy_from (device_memory &mem, int y, int w, int h, int elem)
void mem_zero (device_memory &mem)
void mem_free (device_memory &mem)
void const_copy_to (const char *name, void *host, size_t size)
void tex_alloc (const char *name, device_memory &mem, bool interpolation, bool periodic)
void tex_free (device_memory &mem)
void pixels_alloc (device_memory &mem)
void pixels_free (device_memory &mem)
void pixels_copy_from (device_memory &mem, int y, int w, int h)
void draw_pixels (device_memory &rgba, int y, int w, int h, int dy, int width, int height, bool transparent)
void task_add (DeviceTask &task)
void task_wait ()
void task_cancel ()
Public Attributes
list< SubDevice > devices
device_ptr unique_ptr
Detailed Description
Definition at line 33 of file device_multi.cpp.
Constructor & Destructor Documentation
MultiDevice::MultiDevice (DeviceInfo & info, bool background_) [inline]
Definition at line 47 of file device_multi.cpp.
References Device::background, Device::create(), Device::device, device_network_create(), devices, DeviceInfo::multi_devices, and time_sleep().
MultiDevice::~MultiDevice () [inline]
Definition at line 73 of file device_multi.cpp.
References MultiDevice::SubDevice::device, and devices.
Member Function Documentation
void MultiDevice::const_copy_to (const char * name, void * host, size_t size) [inline, virtual]
Implements Device.
Definition at line 166 of file device_multi.cpp.
References Device::const_copy_to(), MultiDevice::SubDevice::device, and devices.
void MultiDevice::draw_pixels (device_memory & rgba, int y, int w, int h, int dy, int width, int height, bool transparent) [inline, virtual]
Reimplemented from Device.
Definition at line 237 of file device_multi.cpp.
References MultiDevice::SubDevice::device, device_memory::device_pointer, devices, Device::draw_pixels(), i, and MultiDevice::SubDevice::ptr_map.
const string& MultiDevice::error_message () [inline, virtual]
Reimplemented from Device.
Definition at line 79 of file device_multi.cpp.
References MultiDevice::SubDevice::device, devices, Device::error_message(), and Device::error_msg.
bool MultiDevice::load_kernels (bool experimental) [inline, virtual]
Reimplemented from Device.
Definition at line 92 of file device_multi.cpp.
References MultiDevice::SubDevice::device, devices, and Device::load_kernels().
void MultiDevice::mem_alloc (device_memory & mem, MemoryType type) [inline, virtual]
Implements Device.
Definition at line 101 of file device_multi.cpp.
References MultiDevice::SubDevice::device, device_memory::device_pointer, devices, Device::mem_alloc(), MultiDevice::SubDevice::ptr_map, and unique_ptr.
void MultiDevice::mem_copy_from (device_memory & mem, int y, int w, int h, int elem) [inline, virtual]
Implements Device.
Definition at line 124 of file device_multi.cpp.
References MultiDevice::SubDevice::device, device_memory::device_pointer, devices, i, Device::mem_copy_from(), and MultiDevice::SubDevice::ptr_map.
void MultiDevice::mem_copy_to (device_memory & mem) [inline, virtual]
Implements Device.
Definition at line 112 of file device_multi.cpp.
References MultiDevice::SubDevice::device, device_memory::device_pointer, devices, Device::mem_copy_to(), and MultiDevice::SubDevice::ptr_map.
void MultiDevice::mem_free (device_memory & mem) [inline, virtual]
Implements Device.
Definition at line 153 of file device_multi.cpp.
References MultiDevice::SubDevice::device, device_memory::device_pointer, devices, Device::mem_free(), and MultiDevice::SubDevice::ptr_map.
void MultiDevice::mem_zero (device_memory & mem) [inline, virtual]
Implements Device.
Definition at line 141 of file device_multi.cpp.
References MultiDevice::SubDevice::device, device_memory::device_pointer, devices, Device::mem_zero(), and MultiDevice::SubDevice::ptr_map.
void MultiDevice::pixels_alloc (device_memory & mem) [inline, virtual]
Reimplemented from Device.
Definition at line 196 of file device_multi.cpp.
References MultiDevice::SubDevice::device, device_memory::device_pointer, devices, Device::pixels_alloc(), MultiDevice::SubDevice::ptr_map, and unique_ptr.
void MultiDevice::pixels_copy_from (device_memory & mem, int y, int w, int h) [inline, virtual]
Reimplemented from Device.
Definition at line 220 of file device_multi.cpp.
References MultiDevice::SubDevice::device, device_memory::device_pointer, devices, i, Device::pixels_copy_from(), and MultiDevice::SubDevice::ptr_map.
void MultiDevice::pixels_free (device_memory & mem) [inline, virtual]
Reimplemented from Device.
Definition at line 207 of file device_multi.cpp.
References MultiDevice::SubDevice::device, device_memory::device_pointer, devices, Device::pixels_free(), and MultiDevice::SubDevice::ptr_map.
void MultiDevice::task_add (DeviceTask & task) [inline, virtual]
Implements Device.
Definition at line 258 of file device_multi.cpp.
References DeviceTask::buffer, MultiDevice::SubDevice::device, devices, MultiDevice::SubDevice::ptr_map, DeviceTask::rgba, DeviceTask::rng_state, DeviceTask::shader_input, DeviceTask::shader_output, DeviceTask::split(), Device::task_add(), and ThreadQueue< T >::worker_wait_pop().
void MultiDevice::task_cancel () [inline, virtual]
Implements Device.
Definition at line 284 of file device_multi.cpp.
References MultiDevice::SubDevice::device, devices, and Device::task_cancel().
void MultiDevice::task_wait () [inline, virtual]
Implements Device.
Definition at line 278 of file device_multi.cpp.
References MultiDevice::SubDevice::device, devices, and Device::task_wait().
void MultiDevice::tex_alloc (const char * name, device_memory & mem, bool interpolation, bool periodic) [inline, virtual]
Reimplemented from Device.
Definition at line 172 of file device_multi.cpp.
References MultiDevice::SubDevice::device, device_memory::device_pointer, devices, MultiDevice::SubDevice::ptr_map, Device::tex_alloc(), and unique_ptr.
void MultiDevice::tex_free (device_memory & mem) [inline, virtual]
Reimplemented from Device.
Definition at line 183 of file device_multi.cpp.
References MultiDevice::SubDevice::device, device_memory::device_pointer, devices, MultiDevice::SubDevice::ptr_map, and Device::tex_free().
Member Data Documentation
list<SubDevice> MultiDevice::devices
Definition at line 44 of file device_multi.cpp.
Referenced by const_copy_to(), draw_pixels(), error_message(), load_kernels(), mem_alloc(), mem_copy_from(), mem_copy_to(), mem_free(), mem_zero(), MultiDevice(), pixels_alloc(), pixels_copy_from(), pixels_free(), task_add(), task_cancel(), task_wait(), tex_alloc(), tex_free(), and ~MultiDevice().
device_ptr MultiDevice::unique_ptr
Definition at line 45 of file device_multi.cpp.
Referenced by mem_alloc(), pixels_alloc(), and tex_alloc().
The documentation for this class was generated from the following file:
device_multi.cpp