Blender: bmo_join_triangles.c File Reference
bmo_join_triangles.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "DNA_meshdata_types.h"
#include "BKE_customdata.h"
#include "BLI_math.h"
#include "BLI_array.h"
#include "bmesh.h"
#include "intern/bmesh_operators_private.h"
Classes
struct JoinEdge
Defines
#define T2QDELETE 1
#define T2QCOMPLEX 2
#define T2QJOIN 4
#define T2QUV_LIMIT 0.005f
#define T2QCOL_LIMIT 3
#define EDGE_MARK 1
#define EDGE_CHOSEN 2
#define FACE_MARK 1
#define FACE_INPUT 2
Typedefs
typedef struct JoinEdge JoinEdge
Functions
static float measure_facepair (BMVert *v1, BMVert *v2, BMVert *v3, BMVert *v4, float limit)
static int compareFaceAttribs (BMesh *bm, BMEdge *e, int douvs, int dovcols)
static int fplcmp (const void *v1, const void *v2)
void bmo_join_triangles_exec (BMesh *bm, BMOperator *op)
Detailed Description
Definition in file bmo_join_triangles.c.
Define Documentation
#define EDGE_CHOSEN 2
Definition at line 208 of file bmo_join_triangles.c.
Referenced by bmo_join_triangles_exec().
#define EDGE_MARK 1
Definition at line 207 of file bmo_join_triangles.c.
Referenced by bmo_join_triangles_exec().
#define FACE_INPUT 2
Definition at line 211 of file bmo_join_triangles.c.
Referenced by bmo_join_triangles_exec().
#define FACE_MARK 1
Definition at line 210 of file bmo_join_triangles.c.
Referenced by bmo_join_triangles_exec().
#define T2QCOL_LIMIT 3
Definition at line 111 of file bmo_join_triangles.c.
Referenced by compareFaceAttribs().
#define T2QCOMPLEX 2
Definition at line 42 of file bmo_join_triangles.c.
#define T2QDELETE 1
Definition at line 41 of file bmo_join_triangles.c.
#define T2QJOIN 4
Definition at line 43 of file bmo_join_triangles.c.
#define T2QUV_LIMIT 0.005f
Definition at line 110 of file bmo_join_triangles.c.
Referenced by compareFaceAttribs().
Typedef Documentation
typedef struct JoinEdge JoinEdge
Function Documentation
void bmo_join_triangles_exec (BMesh * bm, BMOperator * op)
Definition at line 223 of file bmo_join_triangles.c.
References BLI_array_count, BLI_array_declare, BLI_array_free, BLI_array_growone, BM_edge_face_pair(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SMOOTH, BM_FACE, BM_faces_join_pair(), BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMO_elem_flag_disable, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_bool_get(), BMO_slot_float_get(), compareFaceAttribs(), JoinEdge::e, BMLoop::e, EDGE_CHOSEN, EDGE_MARK, BMLoop::f, FACE_INPUT, FACE_MARK, fplcmp(), i, BMEdge::l, BMFace::len, BMFace::mat_nr, measure_facepair(), BMLoop::next, NULL, BMLoop::prev, BMLoop::radial_next, TRUE, BMLoop::v, and JoinEdge::weight.
static int compareFaceAttribs (BMesh * bm, BMEdge * e, int douvs, int dovcols) [static]
Definition at line 113 of file bmo_join_triangles.c.
References CD_MLOOPCOL, CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, BMLoop::f, FALSE, BMFace::head, BMLoop::head, i, BMEdge::l, BMesh::ldata, BMLoop::next, BMesh::pdata, BMLoop::radial_next, T2QCOL_LIMIT, T2QUV_LIMIT, MTexPoly::tpage, TRUE, MLoopUV::uv, and BMLoop::v.
Referenced by bmo_join_triangles_exec().
static int fplcmp (const void * v1, const void * v2) [static]
Definition at line 213 of file bmo_join_triangles.c.
References JoinEdge::weight.
Referenced by bmo_join_triangles_exec().
static float measure_facepair (BMVert * v1, BMVert * v2, BMVert * v3, BMVert * v4, float limit) [static]
Definition at line 46 of file bmo_join_triangles.c.
References angle_v3v3(), area_tri_v3(), BMVert::co, KDL::diff(), fabsf, M_PI_2, normal_tri_v3(), and sub_v3_v3v3().
Referenced by bmo_join_triangles_exec().