Blender: MT_Vector2 Class Reference
MT_Vector2 Class Reference
#include <MT_Vector2.h>
Public Member Functions
MT_Vector2 ()
MT_Vector2 (const float *v2)
MT_Vector2 (const double *v2)
MT_Vector2 (MT_Scalar xx, MT_Scalar yy)
MT_Vector2 & operator+= (const MT_Vector2 &v)
MT_Vector2 & operator-= (const MT_Vector2 &v)
MT_Vector2 & operator*= (MT_Scalar s)
MT_Vector2 & operator/= (MT_Scalar s)
MT_Scalar dot (const MT_Vector2 &v) const
MT_Scalar length2 () const
MT_Scalar length () const
MT_Vector2 absolute () const
void normalize ()
MT_Vector2 normalized () const
void scale (MT_Scalar x, MT_Scalar y)
MT_Vector2 scaled (MT_Scalar x, MT_Scalar y) const
bool fuzzyZero () const
MT_Scalar angle (const MT_Vector2 &v) const
MT_Vector2 cross (const MT_Vector2 &v) const
MT_Scalar triple (const MT_Vector2 &v1, const MT_Vector2 &v2) const
int closestAxis () const
Static Public Member Functions
static MT_Vector2 random ()
Detailed Description
Definition at line 53 of file MT_Vector2.h.
Constructor & Destructor Documentation
MT_Vector2::MT_Vector2 () [inline]
Definition at line 55 of file MT_Vector2.h.
Referenced by absolute(), and scaled().
MT_Vector2::MT_Vector2 (const float * v2) [inline]
Definition at line 56 of file MT_Vector2.h.
MT_Vector2::MT_Vector2 (const double * v2) [inline]
Definition at line 57 of file MT_Vector2.h.
MT_Vector2::MT_Vector2 (MT_Scalar xx, MT_Scalar yy) [inline]
Definition at line 58 of file MT_Vector2.h.
Member Function Documentation
GEN_INLINE MT_Vector2 MT_Vector2::absolute () const
Definition at line 53 of file MT_Vector2.inl.
References MT_Tuple2::m_co, MT_abs(), and MT_Vector2().
GEN_INLINE MT_Scalar MT_Vector2::angle (const MT_Vector2 & v) const
Definition at line 70 of file MT_Vector2.inl.
References acos(), dot(), length2(), MT_assert, MT_fuzzyZero(), and sqrt().
Referenced by MT_angle().
int MT_Vector2::closestAxis () const
MT_Vector2 MT_Vector2::cross (const MT_Vector2 & v) const
GEN_INLINE MT_Scalar MT_Vector2::dot (const MT_Vector2 & v) const
Definition at line 46 of file MT_Vector2.inl.
References MT_Tuple2::m_co.
Referenced by angle(), length2(), and MT_dot().
GEN_INLINE bool MT_Vector2::fuzzyZero () const
Definition at line 57 of file MT_Vector2.inl.
References length2(), and MT_fuzzyZero2().
Referenced by MT_fuzzyZero().
GEN_INLINE MT_Scalar MT_Vector2::length () const
Definition at line 51 of file MT_Vector2.inl.
References length2(), and sqrt().
Referenced by KX_Camera::ExtractFrustumSphere(), MT_length(), normalize(), normalized(), and KX_ObstacleSimulationTOI_rays::sampleRVO().
GEN_INLINE MT_Scalar MT_Vector2::length2 () const
Definition at line 50 of file MT_Vector2.inl.
References dot().
Referenced by angle(), fuzzyZero(), length(), MT_length2(), and sweepCircleCircle().
GEN_INLINE void MT_Vector2::normalize ()
Definition at line 59 of file MT_Vector2.inl.
References length().
Referenced by KX_ObstacleSimulationTOI_rays::sampleRVO().
GEN_INLINE MT_Vector2 MT_Vector2::normalized () const
Definition at line 60 of file MT_Vector2.inl.
References length().
GEN_INLINE MT_Vector2 & MT_Vector2::operator*= (MT_Scalar s)
Definition at line 13 of file MT_Vector2.inl.
References MT_Tuple2::m_co.
GEN_INLINE MT_Vector2 & MT_Vector2::operator+= (const MT_Vector2 & v)
Reimplemented in MT_Point2.
Definition at line 3 of file MT_Vector2.inl.
References MT_Tuple2::m_co.
GEN_INLINE MT_Vector2 & MT_Vector2::operator-= (const MT_Vector2 & v)
Reimplemented in MT_Point2.
Definition at line 8 of file MT_Vector2.inl.
References MT_Tuple2::m_co.
GEN_INLINE MT_Vector2 & MT_Vector2::operator/= (MT_Scalar s)
Definition at line 18 of file MT_Vector2.inl.
References MT_assert, and MT_fuzzyZero().
static MT_Vector2 MT_Vector2::random () [static]
GEN_INLINE void MT_Vector2::scale (MT_Scalar x, MT_Scalar y)
Definition at line 62 of file MT_Vector2.inl.
References MT_Tuple2::m_co.
GEN_INLINE MT_Vector2 MT_Vector2::scaled (MT_Scalar x, MT_Scalar y) const
Definition at line 66 of file MT_Vector2.inl.
References MT_Tuple2::m_co, and MT_Vector2().
MT_Scalar MT_Vector2::triple (const MT_Vector2 & v1, const MT_Vector2 & v2) const
The documentation for this class was generated from the following files:
MT_Vector2.h
MT_Vector2.inl