Blender: Filter Class Reference
Filter Class Reference
#include <filter.h>
Public Member Functions
Filter ()
~Filter ()
void device_update (Device *device, DeviceScene *dscene)
void device_free (Device *device, DeviceScene *dscene)
bool modified (const Filter &filter)
void tag_update (Scene *scene)
Public Attributes
FilterType filter_type
float filter_width
bool need_update
Detailed Description
Definition at line 33 of file filter.h.
Constructor & Destructor Documentation
CCL_NAMESPACE_BEGIN Filter::Filter ()
Definition at line 32 of file filter.cpp.
References FILTER_BOX, filter_type, filter_width, and need_update.
Filter::~Filter ()
Definition at line 39 of file filter.cpp.
Member Function Documentation
void Filter::device_free (Device * device, DeviceScene * dscene)
Definition at line 124 of file filter.cpp.
References device_vector< T >::clear(), DeviceScene::filter_table, and Device::tex_free().
Referenced by device_update(), and Scene::~Scene().
void Filter::device_update (Device * device, DeviceScene * dscene)
Definition at line 108 of file filter.cpp.
References device_vector< T >::copy(), device_free(), DeviceScene::filter_table, filter_table(), filter_type, filter_width, need_update, table, and Device::tex_alloc().
Referenced by Scene::device_update().
bool Filter::modified (const Filter & filter)
Definition at line 130 of file filter.cpp.
References filter_type, and filter_width.
void Filter::tag_update (Scene * scene)
Definition at line 136 of file filter.cpp.
References need_update.
Member Data Documentation
FilterType Filter::filter_type
Definition at line 36 of file filter.h.
Referenced by device_update(), Filter(), and modified().
float Filter::filter_width
Definition at line 37 of file filter.h.
Referenced by device_update(), Filter(), and modified().
bool Filter::need_update
Definition at line 38 of file filter.h.
Referenced by device_update(), Filter(), Scene::need_reset(), and tag_update().
The documentation for this class was generated from the following files:
filter.h
filter.cpp