Blender: gim_clip_polygon.h File Reference
gim_clip_polygon.h File Reference
Classes
class DISTANCE_PLANE_3D_FUNC
This function calcs the distance from a 3D plane.
Functions
template<typename CLASS_POINT >
SIMD_FORCE_INLINE void PLANE_CLIP_POLYGON_COLLECT (const CLASS_POINT &point0, const CLASS_POINT &point1, GREAL dist0, GREAL dist1, CLASS_POINT *clipped, GUINT &clipped_count)
template<typename CLASS_POINT , typename CLASS_PLANE , typename DISTANCE_PLANE_FUNC >
SIMD_FORCE_INLINE GUINT PLANE_CLIP_POLYGON_GENERIC (const CLASS_PLANE &plane, const CLASS_POINT *polygon_points, GUINT polygon_point_count, CLASS_POINT *clipped, DISTANCE_PLANE_FUNC distance_func)
Clips a polygon by a plane.
template<typename CLASS_POINT , typename CLASS_PLANE , typename DISTANCE_PLANE_FUNC >
SIMD_FORCE_INLINE GUINT PLANE_CLIP_TRIANGLE_GENERIC (const CLASS_PLANE &plane, const CLASS_POINT &point0, const CLASS_POINT &point1, const CLASS_POINT &point2, CLASS_POINT *clipped, DISTANCE_PLANE_FUNC distance_func)
Clips a polygon by a plane.
template<typename CLASS_POINT , typename CLASS_PLANE >
SIMD_FORCE_INLINE GUINT PLANE_CLIP_POLYGON3D (const CLASS_PLANE &plane, const CLASS_POINT *polygon_points, GUINT polygon_point_count, CLASS_POINT *clipped)
template<typename CLASS_POINT , typename CLASS_PLANE >
SIMD_FORCE_INLINE GUINT PLANE_CLIP_TRIANGLE3D (const CLASS_PLANE &plane, const CLASS_POINT &point0, const CLASS_POINT &point1, const CLASS_POINT &point2, CLASS_POINT *clipped)
Function Documentation
template<typename CLASS_POINT , typename CLASS_PLANE > SIMD_FORCE_INLINE GUINT PLANE_CLIP_POLYGON3D (const CLASS_PLANE & plane, const CLASS_POINT * polygon_points, GUINT polygon_point_count, CLASS_POINT * clipped)
Definition at line 187 of file gim_clip_polygon.h.
Referenced by GIM_TRIANGLE_CALCULATION_CACHE::clip_triangle().
template<typename CLASS_POINT > SIMD_FORCE_INLINE void PLANE_CLIP_POLYGON_COLLECT (const CLASS_POINT & point0, const CLASS_POINT & point1, GREAL dist0, GREAL dist1, CLASS_POINT * clipped, GUINT & clipped_count)
Definition at line 51 of file gim_clip_polygon.h.
References G_EPSILON, GREAL, GUINT, VEC_BLEND, and VEC_COPY.
Referenced by PLANE_CLIP_POLYGON_GENERIC(), and PLANE_CLIP_TRIANGLE_GENERIC().
template<typename CLASS_POINT , typename CLASS_PLANE , typename DISTANCE_PLANE_FUNC > SIMD_FORCE_INLINE GUINT PLANE_CLIP_POLYGON_GENERIC (const CLASS_PLANE & plane, const CLASS_POINT * polygon_points, GUINT polygon_point_count, CLASS_POINT * clipped, DISTANCE_PLANE_FUNC distance_func)
Clips a polygon by a plane.
Returns:
The count of the clipped counts
Definition at line 80 of file gim_clip_polygon.h.
References G_EPSILON, GREAL, GUINT, PLANE_CLIP_POLYGON_COLLECT(), and VEC_COPY.
template<typename CLASS_POINT , typename CLASS_PLANE > SIMD_FORCE_INLINE GUINT PLANE_CLIP_TRIANGLE3D (const CLASS_PLANE & plane, const CLASS_POINT & point0, const CLASS_POINT & point1, const CLASS_POINT & point2, CLASS_POINT * clipped)
Definition at line 198 of file gim_clip_polygon.h.
Referenced by GIM_TRIANGLE_CALCULATION_CACHE::clip_triangle().
template<typename CLASS_POINT , typename CLASS_PLANE , typename DISTANCE_PLANE_FUNC > SIMD_FORCE_INLINE GUINT PLANE_CLIP_TRIANGLE_GENERIC (const CLASS_PLANE & plane, const CLASS_POINT & point0, const CLASS_POINT & point1, const CLASS_POINT & point2, CLASS_POINT * clipped, DISTANCE_PLANE_FUNC distance_func)
Clips a polygon by a plane.
Returns:
The count of the clipped counts
Definition at line 130 of file gim_clip_polygon.h.
References G_EPSILON, GREAL, GUINT, PLANE_CLIP_POLYGON_COLLECT(), and VEC_COPY.