Blender: btQuadWord.h File Reference
btQuadWord.h File Reference
#include "btScalar.h"
#include "btMinMax.h"
Functions
ATTRIBUTE_ALIGNED16 (class) btQuadWord
The btQuadWord class is base class for btVector3 and btQuaternion. Some issues under PS3 Linux with IBM 2.1 SDK, gcc compiler prevent from using aligned quadword.
Function Documentation
ATTRIBUTE_ALIGNED16 (class)
The btQuadWord class is base class for btVector3 and btQuaternion. Some issues under PS3 Linux with IBM 2.1 SDK, gcc compiler prevent from using aligned quadword.
Return the x value
Return the y value
Return the z value
Set the x value
Set the y value
Set the z value
Set the w value
Return the x value
Return the y value
Return the z value
Return the w value
operator btScalar*() replaces operator[], using implicit conversion. We added operator != and operator == to avoid pointer comparisons.
Set x,y,z and zero w
Parameters:
x Value of x
y Value of y
z Value of z
Set the values
Parameters:
x Value of x
y Value of y
z Value of z
w Value of w
No initialization constructor
Three argument constructor (zeros w)
Parameters:
x Value of x
y Value of y
z Value of z
Initializing constructor
Parameters:
x Value of x
y Value of y
z Value of z
w Value of w
Set each element to the max of the current values and the values of another btQuadWord
Parameters:
other The other btQuadWord to compare with
Set each element to the min of the current values and the values of another btQuadWord
Parameters:
other The other btQuadWord to compare with
Definition at line 31 of file btQuadWord.h.
References btSetMax(), btSetMin(), operator!=(), operator==(), and SIMD_FORCE_INLINE.