Blender: MyGlutMouseHandler Class Reference
MyGlutMouseHandler Class Reference
#include <MyGlutMouseHandler.h>
Public Member Functions
void ButtonDown (GHOST_IWindow *window, GHOST_TButtonMask button_mask, int x, int y)
void ButtonUp (GHOST_IWindow *window, GHOST_TButtonMask button_mask, int x, int y)
void Motion (GHOST_IWindow *window, int x, int y)
const float AngleX () const
const float AngleY () const
void SetChain (IK_Chain_ExternPtr *chains, int num_chains)
void Mouse (int button, int state, int x, int y)
void Motion (int x, int y)
const float AngleX () const
const float AngleY () const
const MT_Vector3 Position () const
Static Public Member Functions
static MyGlutMouseHandler * New ()
static MyGlutMouseHandler * New ()
Detailed Description
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) 2001-2002 by NaN Holding BV. All rights reserved.
The Original Code is: all of this file.
Contributor(s): none yet.
***** END GPL LICENSE BLOCK *****
Definition at line 34 of file decimation/test/decimate_glut_test/intern/MyGlutMouseHandler.h.
Member Function Documentation
const float MyGlutMouseHandler::AngleX () const [inline]
Definition at line 92 of file decimation/test/decimate_glut_test/intern/MyGlutMouseHandler.h.
Referenced by GlutMeshDrawer::Draw(), and ChainDrawer::Draw().
const float MyGlutMouseHandler::AngleX () const [inline]
Definition at line 153 of file iksolver/test/ik_glut_test/intern/MyGlutMouseHandler.h.
const float MyGlutMouseHandler::AngleY () const [inline]
Definition at line 99 of file decimation/test/decimate_glut_test/intern/MyGlutMouseHandler.h.
Referenced by GlutMeshDrawer::Draw(), and ChainDrawer::Draw().
const float MyGlutMouseHandler::AngleY () const [inline]
Definition at line 160 of file iksolver/test/ik_glut_test/intern/MyGlutMouseHandler.h.
void MyGlutMouseHandler::ButtonDown (GHOST_IWindow * window, GHOST_TButtonMask button_mask, int x, int y) [inline, virtual]
Implements GlutMouseHandler.
Definition at line 47 of file decimation/test/decimate_glut_test/intern/MyGlutMouseHandler.h.
References GHOST_kButtonMaskLeft, and GHOST_IWindow::invalidate().
void MyGlutMouseHandler::ButtonUp (GHOST_IWindow * window, GHOST_TButtonMask button_mask, int x, int y) [inline, virtual]
Implements GlutMouseHandler.
Definition at line 62 of file decimation/test/decimate_glut_test/intern/MyGlutMouseHandler.h.
References GHOST_kButtonMaskLeft, and GHOST_IWindow::invalidate().
void MyGlutMouseHandler::Motion (int x, int y) [inline, virtual]
Implements GlutMouseHandler.
Definition at line 95 of file iksolver/test/ik_glut_test/intern/MyGlutMouseHandler.h.
References MT_Tuple3::getValue(), MT_Tuple3::x(), MT_Tuple3::y(), and MT_Tuple3::z().
void MyGlutMouseHandler::Motion (GHOST_IWindow * window, int x, int y) [inline, virtual]
Implements GlutMouseHandler.
Definition at line 75 of file decimation/test/decimate_glut_test/intern/MyGlutMouseHandler.h.
References GHOST_IWindow::invalidate().
void MyGlutMouseHandler::Mouse (int button, int state, int x, int y) [inline, virtual]
Implements GlutMouseHandler.
Definition at line 62 of file iksolver/test/ik_glut_test/intern/MyGlutMouseHandler.h.
static MyGlutMouseHandler* MyGlutMouseHandler::New () [inline, static]
Definition at line 41 of file decimation/test/decimate_glut_test/intern/MyGlutMouseHandler.h.
Referenced by main().
static MyGlutMouseHandler* MyGlutMouseHandler::New () [inline, static]
Definition at line 42 of file iksolver/test/ik_glut_test/intern/MyGlutMouseHandler.h.
References NULL, and MEM_SmartPtr< T >::Release().
const MT_Vector3 MyGlutMouseHandler::Position () const [inline]
Definition at line 167 of file iksolver/test/ik_glut_test/intern/MyGlutMouseHandler.h.
void MyGlutMouseHandler::SetChain (IK_Chain_ExternPtr * chains, int num_chains) [inline]
Definition at line 54 of file iksolver/test/ik_glut_test/intern/MyGlutMouseHandler.h.
The documentation for this class was generated from the following files:
decimation/test/decimate_glut_test/intern/MyGlutMouseHandler.h
iksolver/test/ik_glut_test/intern/MyGlutMouseHandler.h