Blender: iTaSC::MovingFrame Class Reference
iTaSC::MovingFrame Class Reference
#include <MovingFrame.hpp>
Public Member Functions
MovingFrame (const Frame &frame=F_identity)
virtual ~MovingFrame ()
bool setFrame (const Frame &frame)
bool setCallback (MovingFrameCallback _function, void *_param)
virtual void updateCoordinates (const Timestamp &timestamp)
virtual void updateKinematics (const Timestamp &timestamp)
virtual void pushCache (const Timestamp &timestamp)
virtual void initCache (Cache *_cache)
virtual void finalize ()
Protected Member Functions
virtual void updateJacobian ()
Detailed Description
Definition at line 19 of file MovingFrame.hpp.
Constructor & Destructor Documentation
iTaSC::MovingFrame::MovingFrame (const Frame & frame = F_identity)
Definition at line 17 of file MovingFrame.cpp.
References e_identity_matrix, e_matrix, iTaSC::UncontrolledObject::initialize(), iTaSC::Object::m_internalPose, and iTaSC::UncontrolledObject::m_JuArray.
iTaSC::MovingFrame::~MovingFrame () [virtual]
Definition at line 26 of file MovingFrame.cpp.
Member Function Documentation
void iTaSC::MovingFrame::finalize () [virtual]
Reimplemented from iTaSC::Object.
Definition at line 30 of file MovingFrame.cpp.
References updateJacobian().
void iTaSC::MovingFrame::initCache (Cache * _cache) [virtual]
Implements iTaSC::Object.
Definition at line 35 of file MovingFrame.cpp.
References iTaSC::Cache::addChannel(), iTaSC::frameCacheSize, and iTaSC::Object::m_cache.
void iTaSC::MovingFrame::pushCache (const Timestamp & timestamp) [virtual]
Implements iTaSC::Object.
Definition at line 119 of file MovingFrame.cpp.
References iTaSC::Timestamp::cache, iTaSC::Timestamp::cacheTimestamp, and iTaSC::Timestamp::substep.
Referenced by updateKinematics().
bool iTaSC::MovingFrame::setCallback (MovingFrameCallback _function, void * _param)
Definition at line 85 of file MovingFrame.cpp.
Referenced by convert_tree().
bool iTaSC::MovingFrame::setFrame (const Frame & frame)
Definition at line 79 of file MovingFrame.cpp.
References iTaSC::Object::m_internalPose.
void iTaSC::MovingFrame::updateCoordinates (const Timestamp & timestamp) [virtual]
Implements iTaSC::UncontrolledObject.
Definition at line 92 of file MovingFrame.cpp.
References iTaSC::Timestamp::cacheTimestamp, KDL::diff(), e_zero_vector, iTaSC::Timestamp::interpolate, iTaSC::Object::m_internalPose, iTaSC::UncontrolledObject::m_xudot, iTaSC::Timestamp::realTimestep, iTaSC::Timestamp::reiterate, iTaSC::Timestamp::substep, updateJacobian(), and KDL::Twist::Zero().
void iTaSC::MovingFrame::updateJacobian () [protected, virtual]
Implements iTaSC::Object.
Definition at line 141 of file MovingFrame.cpp.
References e_matrix, iTaSC::Object::m_internalPose, iTaSC::UncontrolledObject::m_JuArray, iTaSC::Object::m_updated, KDL::Frame::p, KDL::Vector::x(), KDL::Vector::y(), and KDL::Vector::z().
Referenced by finalize(), updateCoordinates(), and updateKinematics().
void iTaSC::MovingFrame::updateKinematics (const Timestamp & timestamp) [virtual]
Implements iTaSC::Object.
Definition at line 125 of file MovingFrame.cpp.
References KDL::Frame::Integrate(), iTaSC::Timestamp::interpolate, KDL::Rotation::Inverse(), KDL::Frame::M, iTaSC::Object::m_internalPose, pushCache(), iTaSC::Timestamp::realTimestep, iTaSC::Timestamp::substep, and updateJacobian().
The documentation for this class was generated from the following files:
MovingFrame.hpp
MovingFrame.cpp