Blender: image_intern.h File Reference
image_intern.h File Reference
image and UV editor
Functions
struct ARegion * image_has_buttons_region (struct ScrArea *sa)
struct ARegion * image_has_scope_region (struct ScrArea *sa)
void draw_image_main (struct SpaceImage *sima, struct ARegion *ar, struct Scene *scene)
void draw_image_grease_pencil (struct bContext *C, short onlyv2d)
int space_image_main_area_poll (struct bContext *C)
void IMAGE_OT_view_all (struct wmOperatorType *ot)
void IMAGE_OT_view_pan (struct wmOperatorType *ot)
void IMAGE_OT_view_selected (struct wmOperatorType *ot)
void IMAGE_OT_view_zoom (struct wmOperatorType *ot)
void IMAGE_OT_view_zoom_in (struct wmOperatorType *ot)
void IMAGE_OT_view_zoom_out (struct wmOperatorType *ot)
void IMAGE_OT_view_zoom_ratio (struct wmOperatorType *ot)
void IMAGE_OT_view_ndof (struct wmOperatorType *ot)
void IMAGE_OT_new (struct wmOperatorType *ot)
void IMAGE_OT_open (struct wmOperatorType *ot)
void IMAGE_OT_replace (struct wmOperatorType *ot)
void IMAGE_OT_reload (struct wmOperatorType *ot)
void IMAGE_OT_save (struct wmOperatorType *ot)
void IMAGE_OT_save_as (struct wmOperatorType *ot)
void IMAGE_OT_save_sequence (struct wmOperatorType *ot)
void IMAGE_OT_pack (struct wmOperatorType *ot)
void IMAGE_OT_unpack (struct wmOperatorType *ot)
void IMAGE_OT_invert (struct wmOperatorType *ot)
void IMAGE_OT_cycle_render_slot (struct wmOperatorType *ot)
void IMAGE_OT_sample (struct wmOperatorType *ot)
void IMAGE_OT_sample_line (struct wmOperatorType *ot)
void IMAGE_OT_curves_point_set (struct wmOperatorType *ot)
void IMAGE_OT_record_composite (struct wmOperatorType *ot)
struct ImageUser * ntree_get_active_iuser (struct bNodeTree *ntree)
void image_buttons_register (struct ARegionType *art)
void IMAGE_OT_properties (struct wmOperatorType *ot)
void IMAGE_OT_scopes (struct wmOperatorType *ot)
Variables
const char * image_context_dir []
Detailed Description
Definition in file image_intern.h.
Function Documentation
void draw_image_grease_pencil (struct bContext * C, short onlyv2d)
Definition at line 622 of file image_draw.c.
References CTX_wm_space_data(), draw_gpencil_2dimage(), draw_gpencil_view2d(), ED_space_image_acquire_buffer(), and ED_space_image_release_buffer().
Referenced by image_main_area_draw().
void draw_image_main (struct SpaceImage * sima, struct ARegion * ar, struct Scene * scene)
Definition at line 746 of file image_draw.c.
References RenderData::cfra, RenderData::disprect, draw_image_buffer(), draw_image_buffer_repeated(), draw_image_buffer_tiled(), draw_image_grid(), draw_image_paint_helpers(), draw_render_info(), ED_image_aspect(), ED_space_image(), ED_space_image_acquire_buffer(), ED_space_image_release_buffer(), ED_space_image_zoom(), SpaceImage::flag, G, IMA_SRC_VIEWER, IMA_TILES, IMA_TYPE_COMPOSITE, IMA_TYPE_R_RESULT, SpaceImage::image, SpaceImage::iuser, Scene::nodetree, ntree_get_active_iuser(), NULL, Scene::r, SI_DRAW_TILE, SI_DRAWTOOL, Image::source, Image::tpageflag, Image::type, rcti::xmin, and rcti::ymin.
Referenced by image_main_area_draw().
void image_buttons_register (struct ARegionType * art)
Definition at line 890 of file image_buttons.c.
References BLI_addtail(), PanelType::draw, PanelType::flag, gpencil_panel_standard(), PanelType::idname, image_panel_curves(), image_panel_poll(), PanelType::label, MEM_callocN(), ARegionType::paneltypes, PNL_DEFAULT_CLOSED, and PanelType::poll.
Referenced by ED_spacetype_image().
struct ARegion* image_has_buttons_region (struct ScrArea * sa) [read]
Definition at line 326 of file space_image.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_LEFT, RGN_FLAG_HIDDEN, RGN_TYPE_HEADER, and RGN_TYPE_UI.
Referenced by image_properties().
struct ARegion* image_has_scope_region (struct ScrArea * sa) [read]
Definition at line 350 of file space_image.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, image_scopes_tag_refresh(), MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_RIGHT, RGN_FLAG_HIDDEN, RGN_TYPE_PREVIEW, and RGN_TYPE_UI.
Referenced by image_scopes().
void IMAGE_OT_curves_point_set (struct wmOperatorType * ot)
Definition at line 2148 of file image_ops.c.
References wmOperatorType::cancel, wmOperatorType::flag, wmOperatorType::idname, image_sample_cancel(), image_sample_invoke(), image_sample_modal(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), space_image_main_area_not_uv_brush_poll(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_cycle_render_slot (struct wmOperatorType * ot)
Definition at line 2359 of file image_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_cycle_render_slot_exec(), image_cycle_render_slot_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_invert (struct wmOperatorType * ot)
Definition at line 1643 of file image_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_invert_exec(), image_invert_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_new (struct wmOperatorType * ot)
Definition at line 1550 of file image_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, image_new_exec(), image_new_invoke(), wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::name, NULL, OPTYPE_UNDO, RNA_def_boolean(), RNA_def_float_color(), RNA_def_int(), RNA_def_property_float_array_default(), RNA_def_string(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_open (struct wmOperatorType * ot)
Definition at line 909 of file image_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, image_open_cancel(), image_open_exec(), image_open_invoke(), IMAGEFILE, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, WM_FILESEL_FILEPATH, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by image_operatortypes().
void IMAGE_OT_pack (struct wmOperatorType * ot)
Definition at line 1731 of file image_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_pack_exec(), image_pack_invoke(), wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_properties (struct wmOperatorType * ot)
Definition at line 920 of file image_buttons.c.
References wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_properties(), wmOperatorType::name, and wmOperatorType::poll.
Referenced by image_operatortypes().
void IMAGE_OT_record_composite (struct wmOperatorType * ot)
Definition at line 2308 of file image_ops.c.
References wmOperatorType::cancel, wmOperatorType::exec, wmOperatorType::idname, image_record_composite_cancel(), image_record_composite_exec(), image_record_composite_invoke(), image_record_composite_modal(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, wmOperatorType::poll, and space_image_buffer_exists_poll().
Referenced by image_operatortypes().
void IMAGE_OT_reload (struct wmOperatorType * ot)
Definition at line 1471 of file image_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_reload_exec(), wmOperatorType::name, and OPTYPE_REGISTER.
Referenced by image_operatortypes().
void IMAGE_OT_replace (struct wmOperatorType * ot)
Definition at line 975 of file image_ops.c.
References wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, image_replace_exec(), image_replace_invoke(), IMAGEFILE, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, space_image_poll(), WM_FILESEL_FILEPATH, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by image_operatortypes().
void IMAGE_OT_sample (struct wmOperatorType * ot)
Definition at line 2018 of file image_ops.c.
References wmOperatorType::cancel, wmOperatorType::flag, wmOperatorType::idname, image_sample_cancel(), image_sample_invoke(), image_sample_modal(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, and space_image_image_sample_poll().
Referenced by image_operatortypes().
void IMAGE_OT_sample_line (struct wmOperatorType * ot)
Definition at line 2127 of file image_ops.c.
References wmOperatorType::cancel, CURSOR_EDIT, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_sample_line_exec(), image_sample_line_invoke(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, wmOperatorType::poll, space_image_main_area_poll(), WM_gesture_straightline_cancel(), WM_gesture_straightline_modal(), and WM_operator_properties_gesture_straightline().
Referenced by image_operatortypes().
void IMAGE_OT_save (struct wmOperatorType * ot)
Definition at line 1359 of file image_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_save_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and space_image_file_exists_poll().
Referenced by image_operatortypes().
void IMAGE_OT_save_as (struct wmOperatorType * ot)
Definition at line 1311 of file image_ops.c.
References wmOperatorType::cancel, wmOperatorType::check, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_SAVE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, image_save_as_cancel(), image_save_as_check(), image_save_as_draw(), image_save_as_exec(), image_save_as_invoke(), IMAGEFILE, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), space_image_buffer_exists_poll(), wmOperatorType::srna, wmOperatorType::ui, WM_FILESEL_FILEPATH, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by image_operatortypes().
void IMAGE_OT_save_sequence (struct wmOperatorType * ot)
Definition at line 1436 of file image_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_save_sequence_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and space_image_buffer_exists_poll().
Referenced by image_operatortypes().
void IMAGE_OT_scopes (struct wmOperatorType * ot)
Definition at line 944 of file image_buttons.c.
References wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_scopes(), wmOperatorType::name, and wmOperatorType::poll.
Referenced by image_operatortypes().
void IMAGE_OT_unpack (struct wmOperatorType * ot)
Definition at line 1808 of file image_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_unpack_exec(), image_unpack_invoke(), wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PF_USE_LOCAL, RNA_def_enum(), RNA_def_string(), wmOperatorType::srna, and unpack_method_items.
Referenced by image_operatortypes().
void IMAGE_OT_view_all (struct wmOperatorType * ot)
Definition at line 589 of file image_ops.c.
References wmOperatorType::exec, wmOperatorType::idname, image_view_all_exec(), wmOperatorType::name, wmOperatorType::poll, and space_image_main_area_poll().
Referenced by image_operatortypes().
void IMAGE_OT_view_ndof (struct wmOperatorType * ot)
Definition at line 536 of file image_ops.c.
References wmOperatorType::idname, image_view_ndof_invoke(), wmOperatorType::invoke, and wmOperatorType::name.
Referenced by image_operatortypes().
void IMAGE_OT_view_pan (struct wmOperatorType * ot)
Definition at line 331 of file image_ops.c.
References wmOperatorType::cancel, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, image_view_pan_cancel(), image_view_pan_exec(), image_view_pan_invoke(), image_view_pan_modal(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, wmOperatorType::poll, RNA_def_float_vector(), space_image_main_area_poll(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_view_selected (struct wmOperatorType * ot)
Definition at line 650 of file image_ops.c.
References wmOperatorType::exec, wmOperatorType::idname, image_view_selected_exec(), image_view_selected_poll(), wmOperatorType::name, and wmOperatorType::poll.
Referenced by image_operatortypes().
void IMAGE_OT_view_zoom (struct wmOperatorType * ot)
Definition at line 468 of file image_ops.c.
References wmOperatorType::cancel, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, image_view_zoom_cancel(), image_view_zoom_exec(), image_view_zoom_invoke(), image_view_zoom_modal(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, RNA_def_float(), space_image_main_area_poll(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_view_zoom_in (struct wmOperatorType * ot)
Definition at line 689 of file image_ops.c.
References wmOperatorType::exec, FLT_MAX, wmOperatorType::idname, image_view_zoom_in_exec(), image_view_zoom_in_invoke(), wmOperatorType::invoke, wmOperatorType::name, NULL, wmOperatorType::poll, RNA_def_float_vector(), space_image_main_area_poll(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_view_zoom_out (struct wmOperatorType * ot)
Definition at line 730 of file image_ops.c.
References wmOperatorType::exec, FLT_MAX, wmOperatorType::idname, image_view_zoom_out_exec(), image_view_zoom_out_invoke(), wmOperatorType::invoke, wmOperatorType::name, NULL, wmOperatorType::poll, RNA_def_float_vector(), space_image_main_area_poll(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_view_zoom_ratio (struct wmOperatorType * ot)
Definition at line 772 of file image_ops.c.
References wmOperatorType::exec, FLT_MAX, wmOperatorType::idname, image_view_zoom_ratio_exec(), wmOperatorType::name, wmOperatorType::poll, RNA_def_float(), space_image_main_area_poll(), and wmOperatorType::srna.
Referenced by image_operatortypes().
struct ImageUser* ntree_get_active_iuser (struct bNodeTree * ntree) [read]
Definition at line 157 of file image_buttons.c.
References CMP_NODE_SPLITVIEWER, CMP_NODE_VIEWER, ELEM, ListBase::first, bNode::flag, bNode::next, NODE_DO_OUTPUT, bNodeTree::nodes, NULL, bNode::storage, and bNode::type.
Referenced by draw_image_main(), and uiTemplateImage().
int space_image_main_area_poll (struct bContext * C)
Definition at line 182 of file image_ops.c.
References CTX_wm_space_image().
Referenced by IMAGE_OT_sample_line(), IMAGE_OT_view_all(), IMAGE_OT_view_pan(), IMAGE_OT_view_zoom(), IMAGE_OT_view_zoom_in(), IMAGE_OT_view_zoom_out(), IMAGE_OT_view_zoom_ratio(), image_view_selected_poll(), and space_image_image_sample_poll().
Variable Documentation
const char* image_context_dir[]
Definition at line 694 of file space_image.c.