Blender: node_shader_geometry.c File Reference
node_shader_geometry.c File Reference
#include "../node_shader_util.h"
Functions
static int node_shader_gpu_geometry (GPUMaterial *mat, bNode *UNUSED(node), GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_geometry (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_geometry_out []
Function Documentation
static int node_shader_gpu_geometry (GPUMaterial * mat, bNode * UNUSEDnode, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 43 of file node_shader_geometry.c.
References GPU_builtin(), GPU_INVERSE_VIEW_MATRIX, GPU_stack_link(), GPU_VIEW_NORMAL, and GPU_VIEW_POSITION.
Referenced by register_node_type_sh_geometry().
void register_node_type_sh_geometry (bNodeTreeType * ttype)
Definition at line 51 of file node_shader_geometry.c.
References NODE_CLASS_INPUT, NODE_NEW_SHADING, node_shader_gpu_geometry(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_NEW_GEOMETRY.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_geometry_out[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 0, "Position",         0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_VECTOR, 0, "Normal",           0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_VECTOR, 0, "Tangent",          0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_VECTOR, 0, "True Normal",      0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_VECTOR, 0, "Incoming",         0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_VECTOR, 0, "Parametric",       0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_FLOAT,  0, "Backfacing",       0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 32 of file node_shader_geometry.c.