Blender: pointdensity.h File Reference
pointdensity.h File Reference
Rendering
Functions
void cache_pointdensity (struct Render *re, struct Tex *tex)
void make_pointdensities (struct Render *re)
void free_pointdensities (struct Render *re)
int pointdensitytex (struct Tex *tex, float *texvec, struct TexResult *texres)
Detailed Description
Definition in file pointdensity.h.
Function Documentation
void cache_pointdensity (struct Render * re, struct Tex * tex)
Definition at line 244 of file pointdensity.c.
References BLI_bvhtree_free(), BLI_findlink(), NULL, OB_MESH, PointDensity::object, Object::particlesystem, Tex::pd, PointDensity::point_tree, pointdensity_cache_object(), pointdensity_cache_psys(), PointDensity::psys, PointDensity::source, TEX_PD_OBJECT, TEX_PD_PSYS, and Object::type.
Referenced by make_pointdensities(), and RE_init_sample_material().
void free_pointdensities (struct Render * re)
Definition at line 314 of file pointdensity.c.
References ListBase::first, free_pointdensity(), Tex::id, Render::main, ID::next, Scene::r, R_PREVIEWBUTS, RenderData::scemode, Render::scene, Main::tex, TEX_POINTDENSITY, Tex::type, and ID::us.
Referenced by RE_Database_Free().
void make_pointdensities (struct Render * re)
Definition at line 294 of file pointdensity.c.
References cache_pointdensity(), ListBase::first, Render::i, Tex::id, RenderStats::infostr, Render::main, ID::next, NULL, Scene::r, R_PREVIEWBUTS, RenderData::scemode, Render::scene, Render::sdh, Render::stats_draw, Main::tex, TEX_POINTDENSITY, Tex::type, and ID::us.
Referenced by RE_Database_Baking(), and RE_Database_FromScene().
int pointdensitytex (struct Tex * tex, float * texvec, struct TexResult * texres)
Definition at line 408 of file pointdensity.c.
References accum_density(), BLI_bvhtree_range_query(), BLI_gTurbulence(), BRICONT, BRICONTRGB, co, PointDensity::coba, PointDensity::color_source, copy_v3_v3(), do_colorband(), PointDensity::falloff_curve, PointDensity::falloff_speed_scale, PointDensity::flag, init_pointdensityrangedata(), len_v3(), mul_v3_fl(), PointDensity::noise_basis, PointDensity::noise_depth, PointDensity::noise_fac, PointDensity::noise_influence, PointDensity::noise_size, TexResult::nor, NULL, Tex::pd, point_data_used(), PointDensity::point_tree, R, PointDensity::radius, PointDensity::speed_scale, TexResult::ta, TexResult::talpha, TexResult::tb, TEX_INT, TEX_PD_COLOR_CONSTANT, TEX_PD_COLOR_PARTAGE, TEX_PD_COLOR_PARTSPEED, TEX_PD_COLOR_PARTVEL, TEX_PD_FALLOFF_CURVE, TEX_PD_NOISE_AGE, TEX_PD_NOISE_TIME, TEX_PD_TURBULENCE, TEX_RGB, TexResult::tg, TexResult::tin, TexResult::tr, and turb().
Referenced by multitex().