Blender: btCylinderShapeX Class Reference
btCylinderShapeX Class Reference
#include <btCylinderShape.h>
Public Member Functions
btCylinderShapeX (const btVector3 &halfExtents)
virtual btVector3 localGetSupportingVertexWithoutMargin (const btVector3 &vec) const
virtual void batchedUnitVectorGetSupportingVertexWithoutMargin (const btVector3 *vectors, btVector3 *supportVerticesOut, int numVectors) const
virtual const char * getName () const
virtual btScalar getRadius () const
Detailed Description
Definition at line 128 of file btCylinderShape.h.
Constructor & Destructor Documentation
btCylinderShapeX::btCylinderShapeX (const btVector3 & halfExtents)
Definition at line 28 of file btCylinderShape.cpp.
References btCylinderShape::m_upAxis.
Member Function Documentation
void btCylinderShapeX::batchedUnitVectorGetSupportingVertexWithoutMargin (const btVector3 * vectors, btVector3 * supportVerticesOut, int numVectors) const [virtual]
Reimplemented from btCylinderShape.
Definition at line 271 of file btCylinderShape.cpp.
References CylinderLocalSupportX(), btCylinderShape::getHalfExtentsWithoutMargin(), and i.
virtual const char* btCylinderShapeX::getName (void) const [inline, virtual]
Reimplemented from btCylinderShape.
Definition at line 137 of file btCylinderShape.h.
virtual btScalar btCylinderShapeX::getRadius () const [inline, virtual]
Reimplemented from btCylinderShape.
Definition at line 142 of file btCylinderShape.h.
References btCylinderShape::getHalfExtentsWithMargin().
btVector3 btCylinderShapeX::localGetSupportingVertexWithoutMargin (const btVector3 & vec) const [virtual]
Reimplemented from btCylinderShape.
Definition at line 237 of file btCylinderShape.cpp.
References CylinderLocalSupportX(), and btCylinderShape::getHalfExtentsWithoutMargin().
The documentation for this class was generated from the following files:
btCylinderShape.h
btCylinderShape.cpp