Blender: BoundBox Class Reference
BoundBox Class Reference
#include <DNA_object_types.h>
Public Member Functions
BoundBox (void)
BoundBox (const float3 &min_, const float3 &max_)
void grow (const float3 &pt)
void grow (const BoundBox &bbox)
void intersect (const BoundBox &bbox)
float area (void) const
bool valid (void) const
BoundBox transformed (const Transform *tfm)
Public Attributes
float vec [8][3]
int flag
int pad
float3 min
float3 max
Detailed Description
The following illustrates the orientation of the bounding box in local space
Z Y | / |/ .-----X
2----------6 /| /| / | / | 1----------5 | | | | | | 3-------|--7 | / | / |/ |/ 0----------4
Definition at line 94 of file DNA_object_types.h.
Constructor & Destructor Documentation
BoundBox::BoundBox (void) [inline]
Definition at line 38 of file util_boundbox.h.
References FLT_MAX, make_float3(), max, and min.
BoundBox::BoundBox (const float3 & min_, const float3 & max_) [inline]
Definition at line 44 of file util_boundbox.h.
Member Function Documentation
float BoundBox::area (void) const [inline]
Definition at line 67 of file util_boundbox.h.
References dot(), max, and min.
Referenced by BVHBuild::build_node(), BVHNode::computeSubtreeSAHCost(), BVHBuild::do_spatial_split(), BVHBuild::find_object_split(), BVHBuild::find_spatial_split(), BVHNode::getArea(), and BVHBuild::run().
void BoundBox::grow (const float3 & pt) [inline]
Definition at line 49 of file util_boundbox.h.
References max, and min.
Referenced by BVHBuild::add_reference_mesh(), BVHBuild::add_reference_object(), BVHBuild::add_references(), BicubicTangentPatch::bound(), GregoryQuadPatch::bound(), GregoryTrianglePatch::bound(), BicubicPatch::bound(), LinearTrianglePatch::bound(), LinearQuadPatch::bound(), Mesh::compute_bounds(), BVHBuild::create_leaf_node(), BVHBuild::create_object_leaf_nodes(), BVHBuild::do_spatial_split(), BVHBuild::find_object_split(), BVHBuild::find_spatial_split(), RegularBVH::refit_node(), BVHBuild::split_reference(), and transformed().
void BoundBox::grow (const BoundBox & bbox) [inline]
Definition at line 55 of file util_boundbox.h.
References max, and min.
void BoundBox::intersect (const BoundBox & bbox) [inline]
Definition at line 61 of file util_boundbox.h.
References max, max, min, and min.
Referenced by BVHBuild::build_node(), and BVHBuild::split_reference().
BoundBox BoundBox::transformed (const Transform * tfm) [inline]
Definition at line 83 of file util_boundbox.h.
References grow(), i, max, min, p, transform_point(), float3::x, float3::y, and float3::z.
Referenced by Object::compute_bounds().
bool BoundBox::valid (void) const [inline]
Definition at line 76 of file util_boundbox.h.
References isfinite(), max, and min.
Referenced by BVHBuild::add_reference_mesh(), BVHBuild::add_references(), Object::apply_transform(), and Mesh::compute_bounds().
Member Data Documentation
int BoundBox::flag
Definition at line 96 of file DNA_object_types.h.
Referenced by ED_view3d_boundbox_clip(), and object_boundbox_flag().
float3 BoundBox::max
Definition at line 36 of file util_boundbox.h.
Referenced by BVHBuild::find_spatial_split(), grow(), intersect(), BVHReferenceCompare::operator()(), QBVH::pack_inner(), RegularBVH::pack_node(), and BVHBuild::split_reference().
float3 BoundBox::min
Definition at line 36 of file util_boundbox.h.
Referenced by BVHBuild::find_spatial_split(), grow(), intersect(), BVHReferenceCompare::operator()(), QBVH::pack_inner(), RegularBVH::pack_node(), and BVHBuild::split_reference().
int BoundBox::pad
Definition at line 96 of file DNA_object_types.h.
float BoundBox::vec[8][3]
Definition at line 95 of file DNA_object_types.h.
Referenced by boundbox_set_from_min_max(), calc_clipping_plane(), calc_local_clipping(), draw_bb_quadric(), draw_bounding_volume(), ED_view3d_boundbox_clip(), ED_view3d_calc_clipping(), init_meta(), init_metaball_octal_tree(), make_orco_mball(), minmax_object(), minmax_object_duplis(), my_boundbox_mesh(), my_get_local_bounds(), object_get_dimensions(), object_origin_set_exec(), object_set_dimensions(), ray_hit_boundbox(), snapEdge(), subdivide_metaball_octal_node(), TargetSnapClosest(), view3d_boxview_clip(), and view3d_draw_clipping().
The documentation for this class was generated from the following files:
DNA_object_types.h
util_boundbox.h