Blender: OcclusionThread Struct Reference
OcclusionThread Struct Reference
Public Attributes
Render * re
StrandSurface * mesh
float(* faceao)[3]
float(* faceenv)[3]
float(* faceindirect)[3]
int begin
int end
int thread
Detailed Description
Definition at line 124 of file occlusion.c.
Member Data Documentation
int OcclusionThread::begin
Definition at line 130 of file occlusion.c.
Referenced by exec_strandsurface_sample(), and make_occ_tree().
int OcclusionThread::end
Definition at line 130 of file occlusion.c.
Referenced by make_occ_tree().
float(* OcclusionThread::faceao)[3]
Definition at line 127 of file occlusion.c.
Referenced by exec_strandsurface_sample(), and make_occ_tree().
float(* OcclusionThread::faceenv)[3]
Definition at line 128 of file occlusion.c.
Referenced by exec_strandsurface_sample(), and make_occ_tree().
float(* OcclusionThread::faceindirect)[3]
Definition at line 129 of file occlusion.c.
Referenced by exec_strandsurface_sample(), and make_occ_tree().
StrandSurface* OcclusionThread::mesh
Definition at line 126 of file occlusion.c.
Referenced by exec_strandsurface_sample(), and make_occ_tree().
Render* OcclusionThread::re
Definition at line 125 of file occlusion.c.
Referenced by exec_strandsurface_sample(), and make_occ_tree().
int OcclusionThread::thread
Definition at line 131 of file occlusion.c.
Referenced by exec_strandsurface_sample(), and make_occ_tree().
The documentation for this struct was generated from the following file:
occlusion.c