Blender: bmesh_py_types.c File Reference
bmesh_py_types.c File Reference
#include <Python.h>
#include "BLI_math.h"
#include "DNA_mesh_types.h"
#include "DNA_object_types.h"
#include "DNA_material_types.h"
#include "BKE_depsgraph.h"
#include "BKE_customdata.h"
#include "BKE_DerivedMesh.h"
#include "bmesh.h"
#include "../mathutils/mathutils.h"
#include "../generic/py_capi_utils.h"
#include "bmesh_py_types.h"
#include "bmesh_py_types_select.h"
#include "bmesh_py_types_customdata.h"
#include "bmesh_py_types_meshdata.h"
Defines
#define MODULE_TYPE_ADD(s, t) PyModule_AddObject(s, t.tp_name, (PyObject *)&t); Py_INCREF((PyObject *)&t)
Functions
PyDoc_STRVAR (bpy_bm_elem_select_doc,"Selected state of this element.\n\n:type: boolean")
PyDoc_STRVAR (bpy_bm_elem_hide_doc,"Hidden state of this element.\n\n:type: boolean")
PyDoc_STRVAR (bpy_bm_elem_tag_doc,"Generic attribute scripts can use for own logic\n\n:type: boolean")
PyDoc_STRVAR (bpy_bm_elem_smooth_doc,"Smooth state of this element.\n\n:type: boolean")
PyDoc_STRVAR (bpy_bm_elem_seam_doc,"Seam for UV unwrapping.\n\n:type: boolean")
static PyObject * bpy_bm_elem_hflag_get (BPy_BMElem *self, void *flag)
static int bpy_bm_elem_hflag_set (BPy_BMElem *self, PyObject *value, void *flag)
PyDoc_STRVAR (bpy_bm_elem_index_doc,"Index of this element.\n""\n"":type: int\n""\n"".. note::\n""\n"" This value is not necessarily valid, while editing the mesh it can become *dirty*.\n""\n"" It's also possible to assign any number to this attribute for a scripts internal logic.\n""\n"" To ensure the value is up to date - see :class:`BMElemSeq.index_update`.\n")
static PyObject * bpy_bm_elem_index_get (BPy_BMElem *self, void *UNUSED(flag))
static int bpy_bm_elem_index_set (BPy_BMElem *self, PyObject *value, void *UNUSED(flag))
PyDoc_STRVAR (bpy_bmvertseq_doc,"This meshes vert sequence (read-only).\n\n:type: :class:`BMVertSeq`")
static PyObject * bpy_bmvertseq_get (BPy_BMesh *self, void *UNUSED(closure))
PyDoc_STRVAR (bpy_bmedgeseq_doc,"This meshes edge sequence (read-only).\n\n:type: :class:`BMEdgeSeq`")
static PyObject * bpy_bmedgeseq_get (BPy_BMesh *self, void *UNUSED(closure))
PyDoc_STRVAR (bpy_bmfaceseq_doc,"This meshes face sequence (read-only).\n\n:type: :class:`BMFaceSeq`")
static PyObject * bpy_bmfaceseq_get (BPy_BMesh *self, void *UNUSED(closure))
PyDoc_STRVAR (bpy_bmloopseq_doc,"This meshes face sequence (read-only).\n\n:type: :class:`BMLoopSeq`")
static PyObject * bpy_bmloopseq_get (BPy_BMesh *self, void *UNUSED(closure))
PyDoc_STRVAR (bpy_bmvert_link_edges_doc,"Edges connected to this vertex (read-only).\n\n:type: :class:`BMElemSeq` of :class:`BMVert`")
PyDoc_STRVAR (bpy_bmvert_link_faces_doc,"Faces connected to this vertex (read-only).\n\n:type: :class:`BMElemSeq` of :class:`BMFace`")
PyDoc_STRVAR (bpy_bmvert_link_loops_doc,"Loops that use this vertex (read-only).\n\n:type: :class:`BMElemSeq` of :class:`BMLoop`")
PyDoc_STRVAR (bpy_bmedge_verts_doc,"Verts this edge uses (always 2), (read-only).\n\n:type: :class:`BMElemSeq` of :class:`BMVert`")
PyDoc_STRVAR (bpy_bmedge_link_faces_doc,"Faces connected to this edge, (read-only).\n\n:type: :class:`BMElemSeq` of :class:`BMFace`")
PyDoc_STRVAR (bpy_bmedge_link_loops_doc,"Loops connected to this edge, (read-only).\n\n:type: :class:`BMElemSeq` of :class:`BMLoop`")
PyDoc_STRVAR (bpy_bmface_verts_doc,"Verts of this face, (read-only).\n\n:type: :class:`BMElemSeq` of :class:`BMVert`")
PyDoc_STRVAR (bpy_bmface_edges_doc,"Edges of this face, (read-only).\n\n:type: :class:`BMElemSeq` of :class:`BMEdge`")
PyDoc_STRVAR (bpy_bmface_loops_doc,"Loops of this face, (read-only).\n\n:type: :class:`BMElemSeq` of :class:`BMLoop`")
PyDoc_STRVAR (bpy_bmloops_link_loops_doc,"Loops connected to this loop, (read-only).\n\n:type: :class:`BMElemSeq` of :class:`BMLoop`")
static PyObject * bpy_bmelemseq_elem_get (BPy_BMElem *self, void *itype)
PyDoc_STRVAR (bpy_bm_is_valid_doc,"True when this element is valid (hasn't been removed).\n\n:type: boolean")
static PyObject * bpy_bm_is_valid_get (BPy_BMGeneric *self)
PyDoc_STRVAR (bpy_bmesh_is_wrapped_doc,"True when this mesh is owned by blender (typically the editmode BMesh).\n\n:type: boolean")
static PyObject * bpy_bmesh_is_wrapped_get (BPy_BMesh *self)
PyDoc_STRVAR (bpy_bmesh_select_mode_doc,"The selection mode, values can be {'VERT', 'EDGE', 'FACE'}, can't be assigned an empty set.\n\n:type: set")
static PyObject * bpy_bmesh_select_mode_get (BPy_BMesh *self)
static int bpy_bmesh_select_mode_set (BPy_BMesh *self, PyObject *value)
PyDoc_STRVAR (bpy_bmesh_select_history_doc,"Sequence of selected items (the last is displayed as active).\n\n:type: :class:`BMEditSelSeq`")
static PyObject * bpy_bmesh_select_history_get (BPy_BMesh *self)
static int bpy_bmesh_select_history_set (BPy_BMesh *self, PyObject *value)
PyDoc_STRVAR (bpy_bmvert_co_doc,"The coordinates for this vertex as a 3D, wrapped vector.\n\n:type: :class:`mathutils.Vector`")
static PyObject * bpy_bmvert_co_get (BPy_BMVert *self)
static int bpy_bmvert_co_set (BPy_BMVert *self, PyObject *value)
PyDoc_STRVAR (bpy_bmvert_normal_doc,"The normal for this vertex as a 3D, wrapped vector.\n\n:type: :class:`mathutils.Vector`")
static PyObject * bpy_bmvert_normal_get (BPy_BMVert *self)
static int bpy_bmvert_normal_set (BPy_BMVert *self, PyObject *value)
PyDoc_STRVAR (bpy_bmvert_is_manifold_doc,"True when this vertex is manifold (read-only).\n\n:type: boolean")
static PyObject * bpy_bmvert_is_manifold_get (BPy_BMVert *self)
PyDoc_STRVAR (bpy_bmvert_is_wire_doc,"True when this vertex is not connected to any faces (read-only).\n\n:type: boolean")
static PyObject * bpy_bmvert_is_wire_get (BPy_BMVert *self)
PyDoc_STRVAR (bpy_bmedge_is_manifold_doc,"True when this edge is manifold (read-only).\n\n:type: boolean")
static PyObject * bpy_bmedge_is_manifold_get (BPy_BMEdge *self)
PyDoc_STRVAR (bpy_bmedge_is_wire_doc,"True when this edge is not connected to any faces (read-only).\n\n:type: boolean")
static PyObject * bpy_bmedge_is_wire_get (BPy_BMEdge *self)
PyDoc_STRVAR (bpy_bmedge_is_boundary_doc,"True when this edge is at the boundary of a face (read-only).\n\n:type: boolean")
static PyObject * bpy_bmedge_is_boundary_get (BPy_BMEdge *self)
PyDoc_STRVAR (bpy_bmface_normal_doc,"The normal for this face as a 3D, wrapped vector.\n\n:type: :class:`mathutils.Vector`")
static PyObject * bpy_bmface_normal_get (BPy_BMFace *self)
static int bpy_bmface_normal_set (BPy_BMFace *self, PyObject *value)
PyDoc_STRVAR (bpy_bmface_material_index_doc,"The faces material index.\n\n:type: int")
static PyObject * bpy_bmface_material_index_get (BPy_BMFace *self)
static int bpy_bmface_material_index_set (BPy_BMFace *self, PyObject *value)
PyDoc_STRVAR (bpy_bmloop_vert_doc,"The loops vertex (read-only).\n\n:type: :class:`BMVert`")
static PyObject * bpy_bmloop_vert_get (BPy_BMLoop *self)
PyDoc_STRVAR (bpy_bmloop_edge_doc,"The loops edge (between this loop and the next), (read-only).\n\n:type: :class:`BMEdge`")
static PyObject * bpy_bmloop_edge_get (BPy_BMLoop *self)
PyDoc_STRVAR (bpy_bmloop_face_doc,"The face this loop makes (read-only).\n\n:type: :class:`BMFace`")
static PyObject * bpy_bmloop_face_get (BPy_BMLoop *self)
PyDoc_STRVAR (bpy_bmloop_link_loop_next_doc,"The next face corner (read-only).\n\n:type: :class:`BMLoop`")
static PyObject * bpy_bmloop_link_loop_next_get (BPy_BMLoop *self)
PyDoc_STRVAR (bpy_bmloop_link_loop_prev_doc,"The previous face corner (read-only).\n\n:type: :class:`BMLoop`")
static PyObject * bpy_bmloop_link_loop_prev_get (BPy_BMLoop *self)
PyDoc_STRVAR (bpy_bmelemseq_layers_doc,"blah blah (read-only).\n\n:type: :class:`BMLayerAccess`")
static PyObject * bpy_bmelemseq_layers_get (BPy_BMElemSeq *self, void *htype)
PyDoc_STRVAR (bpy_bmesh_copy_doc,".. method:: copy()\n""\n"" :return: A copy of this BMesh.\n"" :rtype: :class:`BMesh`\n")
static PyObject * bpy_bmesh_copy (BPy_BMesh *self)
PyDoc_STRVAR (bpy_bmesh_clear_doc,".. method:: clear()\n""\n"" Clear all mesh data.\n")
static PyObject * bpy_bmesh_clear (BPy_BMesh *self)
PyDoc_STRVAR (bpy_bmesh_free_doc,".. method:: free()\n""\n"" Explicitly free the BMesh data from memory, causing exceptions on further access.\n""\n"" .. note::\n""\n"" The BMesh is freed automatically, typically when the script finishes executing.\n"" However in some cases its hard to predict when this will be and its useful to\n"" explicitly free the data.\n")
static PyObject * bpy_bmesh_free (BPy_BMesh *self)
PyDoc_STRVAR (bpy_bmesh_to_mesh_doc,".. method:: to_mesh(mesh)\n""\n"" Writes this BMesh data into an existing Mesh datablock.\n""\n"" :arg mesh: The mesh data to write into.\n"" :type mesh: :class:`Mesh`\n")
static PyObject * bpy_bmesh_to_mesh (BPy_BMesh *self, PyObject *args)
PyDoc_STRVAR (bpy_bmesh_from_object_doc,".. method:: from_object(mesh, apply_modifiers=True)\n""\n"" Initialize this bmesh from existing object datablock.\n""\n"" :arg object: The object data to load.\n"" :type object: :class:`Object`\n"" :arg apply_modifiers: Use the final display mesh rather then the deformed cage.\n"" :type apply_modifiers: boolean\n")
static PyObject * bpy_bmesh_from_object (BPy_BMesh *self, PyObject *args)
PyDoc_STRVAR (bpy_bmesh_from_mesh_doc,".. method:: from_mesh(mesh, use_shape_key=False, shape_key_index=0)\n""\n"" Initialize this bmesh from existing mesh datablock.\n""\n"" :arg mesh: The mesh data to load.\n"" :type mesh: :class:`Mesh`\n"" :arg use_shape_key: Use the locations from a shape key.\n"" :type use_shape_key: boolean\n"" :arg shape_key_index: The shape key index to use.\n"" :type shape_key_index: int\n")
static PyObject * bpy_bmesh_from_mesh (BPy_BMesh *self, PyObject *args, PyObject *kw)
PyDoc_STRVAR (bpy_bmesh_select_flush_mode_doc,".. method:: select_flush_mode()\n""\n"" flush selection based on the current mode current :class:`BMesh.select_mode`.\n")
static PyObject * bpy_bmesh_select_flush_mode (BPy_BMesh *self)
PyDoc_STRVAR (bpy_bmesh_select_flush_doc,".. method:: select_flush(select)\n""\n"" Flush selection, independent of the current selection mode.\n""\n"" :arg select: flush selection or de-selected elements.\n"" :type select: boolean\n")
static PyObject * bpy_bmesh_select_flush (BPy_BMesh *self, PyObject *value)
PyDoc_STRVAR (bpy_bmesh_normal_update_doc,".. method:: normal_update(skip_hidden=False)\n""\n"" Update mesh normals.\n""\n"" :arg skip_hidden: When True hidden elements are ignored.\n"" :type skip_hidden: boolean\n")
static PyObject * bpy_bmesh_normal_update (BPy_BMesh *self, PyObject *args)
PyDoc_STRVAR (bpy_bmesh_transform_doc,".. method:: transform(matrix, filter=None)\n""\n"" Transform the mesh (optionally filtering flagged data only).\n""\n"" :arg matrix: transform matrix.\n"" :type matrix: 4x4 :class:`mathutils.Matrix`\n"" :arg filter: set of values in ('SELECT', 'HIDE', 'SEAM', 'SMOOTH', 'TAG').\n"" :type filter: set\n")
static PyObject * bpy_bmesh_transform (BPy_BMElem *self, PyObject *args, PyObject *kw)
PyDoc_STRVAR (bpy_bm_elem_select_set_doc,".. method:: select_set(select)\n""\n"" Set the selection.\n"" This is different from the *select* attribute because it updates the selection state of assosiated geometry.\n""\n"" :arg select: Select or de-select.\n"" :type select: boolean\n""\n"" .. note::\n""\n"" Currently this only flushes down, so selecting a face will select all its vertices but de-selecting a vertex "" won't de-select all the faces that use it, before finishing with a mesh typically flushing is still needed.\n")
static PyObject * bpy_bm_elem_select_set (BPy_BMElem *self, PyObject *value)
PyDoc_STRVAR (bpy_bm_elem_hide_set_doc,".. method:: hide_set(hide)\n""\n"" Set the hide state.\n"" This is different from the *hide* attribute because it updates the selection and hide state of assosiated geometry.\n""\n"" :arg hide: Hidden or visible.\n"" :type hide: boolean\n")
static PyObject * bpy_bm_elem_hide_set (BPy_BMElem *self, PyObject *value)
PyDoc_STRVAR (bpy_bm_elem_copy_from_doc,".. method:: copy_from(other)\n""\n"" Copy values from another element of matching type.\n")
static PyObject * bpy_bm_elem_copy_from (BPy_BMElem *self, BPy_BMElem *value)
PyDoc_STRVAR (bpy_bmvert_copy_from_vert_interp_doc,".. method:: copy_from_vert_interp(vert_pair, fac)\n""\n"" Interpolate the customdata from a vert between 2 other verts.\n""\n"" :arg vert_pair: The vert to interpolate data from.\n"" :type vert_pair: :class:`BMVert`\n")
static PyObject * bpy_bmvert_copy_from_vert_interp (BPy_BMVert *self, PyObject *args)
PyDoc_STRVAR (bpy_bmvert_copy_from_face_interp_doc,".. method:: copy_from_face_interp(face)\n""\n"" Interpolate the customdata from a face onto this loop (the loops vert should overlap the face).\n""\n"" :arg face: The face to interpolate data from.\n"" :type face: :class:`BMFace`\n")
static PyObject * bpy_bmvert_copy_from_face_interp (BPy_BMVert *self, PyObject *args)
PyDoc_STRVAR (bpy_bmvert_calc_edge_angle_doc,".. method:: calc_edge_angle()\n""\n"" Return the angle between this verts 2 connected edges.\n""\n"" :return: Angle between edges in radians.\n"" :rtype: float\n")
static PyObject * bpy_bmvert_calc_edge_angle (BPy_BMVert *self)
PyDoc_STRVAR (bpy_bmvert_calc_shell_factor_doc,".. method:: calc_shell_factor()\n""\n"" Return a multiplier calculated based on the sharpness of the vertex.\n"" Where a flat surface gives 1.0, and higher values sharper edges.\n"" This is used to maintain shell thickness when offsetting verts along their normals.\n""\n"" :return: offset multiplier\n"" :rtype: float\n")
static PyObject * bpy_bmvert_calc_shell_factor (BPy_BMVert *self)
PyDoc_STRVAR (bpy_bmvert_normal_update_doc,".. method:: normal_update()\n""\n"" Update vertex normal.\n")
static PyObject * bpy_bmvert_normal_update (BPy_BMVert *self)
PyDoc_STRVAR (bpy_bmedge_calc_length_doc,".. method:: calc_length()\n""\n"" :return: The length between both verts.\n"" :rtype: float\n")
static PyObject * bpy_bmedge_calc_length (BPy_BMEdge *self)
PyDoc_STRVAR (bpy_bmedge_calc_face_angle_doc,".. method:: calc_face_angle()\n""\n"" :return: The angle between 2 connected faces in radians.\n"" :rtype: float\n")
static PyObject * bpy_bmedge_calc_face_angle (BPy_BMEdge *self)
PyDoc_STRVAR (bpy_bmedge_calc_tangent_doc,".. method:: calc_tangent(loop)\n""\n"" Return the tangent at this edge relative to a face (pointing inward into the face).\n"" This uses the face normal for calculation.\n""\n"" :arg loop: The loop used for tangent calculation.\n"" :type loop: :class:`BMLoop`\n"" :return: a normalized vector.\n"" :rtype: :class:`mathutils.Vector`\n")
static PyObject * bpy_bmedge_calc_tangent (BPy_BMEdge *self, PyObject *args)
PyDoc_STRVAR (bpy_bmedge_other_vert_doc,".. method:: other_vert(vert)\n""\n"" Return the other vertex on this edge or None if the vertex is not used by this edge.\n""\n"" :arg vert: a vert in this edge.\n"" :type vert: :class:`BMVert`\n"" :return: The edges other vert.\n"" :rtype: :class:`BMVert` or None\n")
static PyObject * bpy_bmedge_other_vert (BPy_BMEdge *self, BPy_BMVert *value)
PyDoc_STRVAR (bpy_bmedge_normal_update_doc,".. method:: normal_update()\n""\n"" Update edges vertex normals.\n")
static PyObject * bpy_bmedge_normal_update (BPy_BMEdge *self)
PyDoc_STRVAR (bpy_bmface_copy_from_face_interp_doc,".. method:: copy_from_face_interp(face)\n""\n"" Interpolate the customdata from another face onto this one (faces should overlap).\n""\n"" :arg face: The face to interpolate data from.\n"" :type face: :class:`BMFace`\n")
static PyObject * bpy_bmface_copy_from_face_interp (BPy_BMFace *self, PyObject *args)
PyDoc_STRVAR (bpy_bmface_copy_doc,".. method:: copy(verts=True, edges=True)\n""\n"" Make a copy of this face.\n""\n"" :arg verts: When set, the faces verts will be duplicated too.\n"" :type verts: boolean\n"" :arg edges: When set, the faces edges will be duplicated too.\n"" :type edges: boolean\n"" :return: The newly created face.\n"" :rtype: :class:`BMFace`\n")
static PyObject * bpy_bmface_copy (BPy_BMFace *self, PyObject *args, PyObject *kw)
PyDoc_STRVAR (bpy_bmface_calc_area_doc,".. method:: calc_area()\n""\n"" Return the area of the face.\n""\n"" :return: Return the area of the face.\n"" :rtype: float\n")
static PyObject * bpy_bmface_calc_area (BPy_BMFace *self)
PyDoc_STRVAR (bpy_bmface_calc_perimeter_doc,".. method:: calc_perimeter()\n""\n"" Return the perimeter of the face.\n""\n"" :return: Return the perimeter of the face.\n"" :rtype: float\n")
static PyObject * bpy_bmface_calc_perimeter (BPy_BMFace *self)
PyDoc_STRVAR (bpy_bmface_calc_center_mean_doc,".. method:: calc_center_median()\n""\n"" Return median center of the face.\n""\n"" :return: a 3D vector.\n"" :rtype: :class:`mathutils.Vector`\n")
static PyObject * bpy_bmface_calc_center_mean (BPy_BMFace *self)
PyDoc_STRVAR (bpy_bmface_calc_center_bounds_doc,".. method:: calc_center_bounds()\n""\n"" Return bounds center of the face.\n""\n"" :return: a 3D vector.\n"" :rtype: :class:`mathutils.Vector`\n")
static PyObject * bpy_bmface_calc_center_bounds (BPy_BMFace *self)
PyDoc_STRVAR (bpy_bmface_normal_update_doc,".. method:: normal_update()\n""\n"" Update faces normal.\n")
static PyObject * bpy_bmface_normal_update (BPy_BMFace *self)
PyDoc_STRVAR (bpy_bmloop_copy_from_face_interp_doc,".. method:: copy_from_face_interp(face, vert=True, multires=True)\n""\n"" Interpolate the customdata from a face onto this loop (the loops vert should overlap the face).\n""\n"" :arg face: The face to interpolate data from.\n"" :type face: :class:`BMFace`\n"" :arg vert: When enabled, interpolate the loops vertex data (optional).\n"" :type vert: boolean\n"" :arg multires: When enabled, interpolate the loops multires data (optional).\n"" :type multires: boolean\n")
static PyObject * bpy_bmloop_copy_from_face_interp (BPy_BMLoop *self, PyObject *args)
PyDoc_STRVAR (bpy_bmloop_calc_angle_doc,".. method:: calc_angle()\n""\n"" Return the angle at this loops corner of the face.\n"" This is calculated so sharper corners give lower angles.\n""\n"" :return: The angle in radians.\n"" :rtype: float\n")
static PyObject * bpy_bmloop_calc_angle (BPy_BMLoop *self)
PyDoc_STRVAR (bpy_bmloop_calc_normal_doc,".. method:: calc_normal()\n""\n"" Return normal at this loops corner of the face.\n"" Falls back to the face normal for straignt lines.\n""\n"" :return: a normalized vector.\n"" :rtype: :class:`mathutils.Vector`\n")
static PyObject * bpy_bmloop_calc_normal (BPy_BMLoop *self)
PyDoc_STRVAR (bpy_bmloop_calc_tangent_doc,".. method:: calc_tangent()\n""\n"" Return the tangent at this loops corner of the face (pointing inward into the face).\n"" Falls back to the face normal for straignt lines.\n""\n"" :return: a normalized vector.\n"" :rtype: :class:`mathutils.Vector`\n")
static PyObject * bpy_bmloop_calc_tangent (BPy_BMLoop *self)
PyDoc_STRVAR (bpy_bmvertseq_new_doc,".. method:: new(co=(0.0, 0.0, 0.0), example=None)\n""\n"" Create a new vertex.\n""\n"" :arg co: The initial location of the vertex (optional argument).\n"" :type co: float triplet\n"" :arg example: Existing vert to initialize settings.\n"" :type example: :class:`BMVert`\n"" :return: The newly created edge.\n"" :rtype: :class:`BMVert`\n")
static PyObject * bpy_bmvertseq_new (BPy_BMElemSeq *self, PyObject *args)
PyDoc_STRVAR (bpy_bmedgeseq_new_doc,".. method:: new(verts, example=None)\n""\n"" Create a new edge from a given pair of verts.\n""\n"" :arg verts: Vertex pair.\n"" :type verts: pair of :class:`BMVert`\n"" :arg example: Existing edge to initialize settings (optional argument).\n"" :type example: :class:`BMEdge`\n"" :return: The newly created edge.\n"" :rtype: :class:`BMEdge`\n")
static PyObject * bpy_bmedgeseq_new (BPy_BMElemSeq *self, PyObject *args)
PyDoc_STRVAR (bpy_bmfaceseq_new_doc,".. method:: new(verts, example=None)\n""\n"" Create a new face from a given set of verts.\n""\n"" :arg verts: Sequence of 3 or more verts.\n"" :type verts: :class:`BMVert`\n"" :arg example: Existing face to initialize settings (optional argument).\n"" :type example: :class:`BMFace`\n"" :return: The newly created face.\n"" :rtype: :class:`BMFace`\n")
static PyObject * bpy_bmfaceseq_new (BPy_BMElemSeq *self, PyObject *args)
PyDoc_STRVAR (bpy_bmvertseq_remove_doc,".. method:: remove(vert)\n""\n"" Remove a vert.\n")
static PyObject * bpy_bmvertseq_remove (BPy_BMElemSeq *self, BPy_BMVert *value)
PyDoc_STRVAR (bpy_bmedgeseq_remove_doc,".. method:: remove(edge)\n""\n"" Remove a edge.\n")
static PyObject * bpy_bmedgeseq_remove (BPy_BMElemSeq *self, BPy_BMEdge *value)
PyDoc_STRVAR (bpy_bmfaceseq_remove_doc,".. method:: remove(face)\n""\n"" Remove a face.\n")
static PyObject * bpy_bmfaceseq_remove (BPy_BMElemSeq *self, BPy_BMFace *value)
PyDoc_STRVAR (bpy_bmedgeseq_get__method_doc,".. method:: get(verts, fallback=None)\n""\n"" Return a edge which uses the **verts** passed.\n""\n"" :arg verts: Sequence of verts.\n"" :type verts: :class:`BMVert`\n"" :arg fallback: Return this value if nothing is found.\n"" :return: The edge found or None\n"" :rtype: :class:`BMEdge`\n")
static PyObject * bpy_bmedgeseq_get__method (BPy_BMElemSeq *self, PyObject *args)
PyDoc_STRVAR (bpy_bmfaceseq_get__method_doc,".. method:: get(verts, fallback=None)\n""\n"" Return a face which uses the **verts** passed.\n""\n"" :arg verts: Sequence of verts.\n"" :type verts: :class:`BMVert`\n"" :arg fallback: Return this value if nothing is found.\n"" :return: The face found or None\n"" :rtype: :class:`BMFace`\n")
static PyObject * bpy_bmfaceseq_get__method (BPy_BMElemSeq *self, PyObject *args)
PyDoc_STRVAR (bpy_bmelemseq_index_update_doc,".. method:: index_update()\n""\n"" Initialize the index values of this sequence.\n""\n"" This is the equivalent of looping over all elements and assigning the index values.\n""\n"" .. code-block:: python\n""\n"" for index, ele in enumerate(sequence):\n"" ele.index = index\n""\n"" .. note::\n""\n"" Running this on sequences besides :class:`BMesh.verts`, :class:`BMesh.edges`, :class:`BMesh.faces`\n"" works but wont result in each element having a valid index, insted its order in the sequence will be set.\n")
static PyObject * bpy_bmelemseq_index_update (BPy_BMElemSeq *self)
static PyTypeObject * bpy_bm_itype_as_pytype (const char itype)
static Py_ssize_t bpy_bmelemseq_length (BPy_BMElemSeq *self)
static PyObject * bpy_bmelemseq_subscript_int (BPy_BMElemSeq *self, int keynum)
static PyObject * bpy_bmelemseq_subscript_slice (BPy_BMElemSeq *self, Py_ssize_t start, Py_ssize_t stop)
static PyObject * bpy_bmelemseq_subscript (BPy_BMElemSeq *self, PyObject *key)
static int bpy_bmelemseq_contains (BPy_BMElemSeq *self, PyObject *value)
static PyObject * bpy_bmelem_subscript (BPy_BMElem *self, BPy_BMLayerItem *key)
static int bpy_bmelem_ass_subscript (BPy_BMElem *self, BPy_BMLayerItem *key, PyObject *value)
static PyObject * bpy_bmelemseq_iter (BPy_BMElemSeq *self)
static PyObject * bpy_bmiter_next (BPy_BMIter *self)
static void bpy_bmesh_dealloc (BPy_BMesh *self)
static void bpy_bmvert_dealloc (BPy_BMElem *self)
static void bpy_bmedge_dealloc (BPy_BMElem *self)
static void bpy_bmface_dealloc (BPy_BMElem *self)
static void bpy_bmloop_dealloc (BPy_BMElem *self)
static void bpy_bmelemseq_dealloc (BPy_BMElemSeq *self)
static Py_hash_t bpy_bm_elem_hash (PyObject *self)
static Py_hash_t bpy_bm_hash (PyObject *self)
PyDoc_STRVAR (bpy_bmesh_doc,"The BMesh data structure\n")
PyDoc_STRVAR (bpy_bmvert_doc,"The BMesh vertex type\n")
PyDoc_STRVAR (bpy_bmedge_doc,"The BMesh edge connecting 2 verts\n")
PyDoc_STRVAR (bpy_bmface_doc,"The BMesh face with 3 or more sides\n")
PyDoc_STRVAR (bpy_bmloop_doc,"This is normally accessed from :class:`BMFace.loops` where each face corner represents a corner of a face.\n")
PyDoc_STRVAR (bpy_bmelemseq_doc,"General sequence type used for accessing any sequence of \n"":class:`BMVert`, :class:`BMEdge`, :class:`BMFace`, :class:`BMLoop`.\n""\n""When accessed via :class:`BMesh.verts`, :class:`BMesh.edges`, :class:`BMesh.faces` \n""there are also functions to create/remomove items.\n")
PyDoc_STRVAR (bpy_bmiter_doc,"Internal BMesh type for looping over verts/faces/edges,\n""used for iterating over :class:`BMElemSeq` types.\n")
static PyObject * bpy_bmesh_repr (BPy_BMesh *self)
static PyObject * bpy_bmvert_repr (BPy_BMVert *self)
static PyObject * bpy_bmedge_repr (BPy_BMEdge *self)
static PyObject * bpy_bmface_repr (BPy_BMFace *self)
static PyObject * bpy_bmloop_repr (BPy_BMLoop *self)
void BPy_BM_init_types (void)
PyObject * BPyInit_bmesh_types (void)
PyObject * BPy_BMesh_CreatePyObject (BMesh *bm, int flag)
PyObject * BPy_BMVert_CreatePyObject (BMesh *bm, BMVert *v)
PyObject * BPy_BMEdge_CreatePyObject (BMesh *bm, BMEdge *e)
PyObject * BPy_BMFace_CreatePyObject (BMesh *bm, BMFace *f)
PyObject * BPy_BMLoop_CreatePyObject (BMesh *bm, BMLoop *l)
PyObject * BPy_BMElemSeq_CreatePyObject (BMesh *bm, BPy_BMElem *py_ele, const char itype)
PyObject * BPy_BMVertSeq_CreatePyObject (BMesh *bm)
PyObject * BPy_BMEdgeSeq_CreatePyObject (BMesh *bm)
PyObject * BPy_BMFaceSeq_CreatePyObject (BMesh *bm)
PyObject * BPy_BMLoopSeq_CreatePyObject (BMesh *bm)
PyObject * BPy_BMIter_CreatePyObject (BMesh *bm)
PyObject * BPy_BMElem_CreatePyObject (BMesh *bm, BMHeader *ele)
int bpy_bm_generic_valid_check (BPy_BMGeneric *self)
void bpy_bm_generic_invalidate (BPy_BMGeneric *self)
void * BPy_BMElem_PySeq_As_Array (BMesh **r_bm, PyObject *seq, Py_ssize_t min, Py_ssize_t max, Py_ssize_t *r_size, const char htype, const char do_unique_check, const char do_bm_check, const char *error_prefix)
PyObject * BPy_BMElem_Array_As_Tuple (BMesh *bm, BMHeader **elem, Py_ssize_t elem_len)
int BPy_BMElem_CheckHType (PyTypeObject *type, const char htype)
char * BPy_BMElem_StringFromHType_ex (const char htype, char ret[32])
char * BPy_BMElem_StringFromHType (const char htype)
Variables
PyC_FlagSet bpy_bm_scene_vert_edge_face_flags []
PyC_FlagSet bpy_bm_htype_vert_edge_face_flags []
PyC_FlagSet bpy_bm_htype_all_flags []
PyC_FlagSet bpy_bm_hflag_all_flags []
static PyGetSetDef bpy_bmesh_getseters []
static PyGetSetDef bpy_bmvert_getseters []
static PyGetSetDef bpy_bmedge_getseters []
static PyGetSetDef bpy_bmface_getseters []
static PyGetSetDef bpy_bmloop_getseters []
static PyGetSetDef bpy_bmvertseq_getseters []
static PyGetSetDef bpy_bmedgeseq_getseters []
static PyGetSetDef bpy_bmfaceseq_getseters []
static PyGetSetDef bpy_bmloopseq_getseters []
static struct PyMethodDef bpy_bmesh_methods []
static struct PyMethodDef bpy_bmvert_methods []
static struct PyMethodDef bpy_bmedge_methods []
static struct PyMethodDef bpy_bmface_methods []
static struct PyMethodDef bpy_bmloop_methods []
static struct PyMethodDef bpy_bmelemseq_methods []
static struct PyMethodDef bpy_bmvertseq_methods []
static struct PyMethodDef bpy_bmedgeseq_methods []
static struct PyMethodDef bpy_bmfaceseq_methods []
static struct PyMethodDef bpy_bmloopseq_methods []
static PySequenceMethods bpy_bmelemseq_as_sequence
static PyMappingMethods bpy_bmelemseq_as_mapping
static PyMappingMethods bpy_bm_elem_as_mapping
PyTypeObject BPy_BMesh_Type = {{{0}}}
PyTypeObject BPy_BMVert_Type = {{{0}}}
PyTypeObject BPy_BMEdge_Type = {{{0}}}
PyTypeObject BPy_BMFace_Type = {{{0}}}
PyTypeObject BPy_BMLoop_Type = {{{0}}}
PyTypeObject BPy_BMElemSeq_Type = {{{0}}}
PyTypeObject BPy_BMVertSeq_Type = {{{0}}}
PyTypeObject BPy_BMEdgeSeq_Type = {{{0}}}
PyTypeObject BPy_BMFaceSeq_Type = {{{0}}}
PyTypeObject BPy_BMLoopSeq_Type = {{{0}}}
PyTypeObject BPy_BMIter_Type = {{{0}}}
static struct PyModuleDef BPy_BM_types_module_def
Detailed Description
Definition in file bmesh_py_types.c.
Define Documentation
#define MODULE_TYPE_ADD (s, t) PyModule_AddObject(s, t.tp_name, (PyObject *)&t); Py_INCREF((PyObject *)&t)
Referenced by BPyInit_bmesh_types(), and BPyInit_idprop_types().
Function Documentation
static PyObject* bpy_bm_elem_copy_from (BPy_BMElem * self, BPy_BMElem * value) [static]
Definition at line 1089 of file bmesh_py_types.c.
References BPy_BMElem::bm, BM_elem_attrs_copy(), BPY_BM_CHECK_OBJ, BPy_BMElem::ele, and NULL.
static Py_hash_t bpy_bm_elem_hash (PyObject * self) [static]
Definition at line 2565 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
static PyObject* bpy_bm_elem_hflag_get (BPy_BMElem * self, void * flag) [static]
Definition at line 105 of file bmesh_py_types.c.
References BM_elem_flag_test, BPY_BM_CHECK_OBJ, and GET_INT_FROM_POINTER.
static int bpy_bm_elem_hflag_set (BPy_BMElem * self, PyObject * value, void * flag) [static]
Definition at line 114 of file bmesh_py_types.c.
References BM_elem_flag_disable, BM_elem_flag_enable, BPY_BM_CHECK_INT, FALSE, GET_INT_FROM_POINTER, and TRUE.
static PyObject* bpy_bm_elem_hide_set (BPy_BMElem * self, PyObject * value) [static]
Definition at line 1065 of file bmesh_py_types.c.
References BM_elem_hide_set, BPY_BM_CHECK_OBJ, FALSE, NULL, and TRUE.
static PyObject* bpy_bm_elem_index_get (BPy_BMElem * self, void * UNUSEDflag) [static]
Definition at line 153 of file bmesh_py_types.c.
References BM_elem_index_get, and BPY_BM_CHECK_OBJ.
static int bpy_bm_elem_index_set (BPy_BMElem * self, PyObject * value, void * UNUSEDflag) [static]
Definition at line 160 of file bmesh_py_types.c.
References BM_EDGE, BM_elem_index_set, BM_FACE, BM_VERT, and BPY_BM_CHECK_INT.
static PyObject* bpy_bm_elem_select_set (BPy_BMElem * self, PyObject * value) [static]
Definition at line 1037 of file bmesh_py_types.c.
References BM_elem_select_set(), BPY_BM_CHECK_OBJ, FALSE, NULL, and TRUE.
void bpy_bm_generic_invalidate (BPy_BMGeneric * self)
Definition at line 3128 of file bmesh_py_types.c.
References NULL.
int bpy_bm_generic_valid_check (BPy_BMGeneric * self)
Definition at line 3115 of file bmesh_py_types.c.
References LIKELY.
static Py_hash_t bpy_bm_hash (PyObject * self) [static]
Definition at line 2570 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
void BPy_BM_init_types (void)
Definition at line 2697 of file bmesh_py_types.c.
References bpy_bm_elem_as_mapping, bpy_bm_elem_hash(), bpy_bm_hash(), bpy_bmedge_dealloc(), bpy_bmedge_getseters, bpy_bmedge_methods, bpy_bmedge_repr(), bpy_bmedgeseq_getseters, bpy_bmedgeseq_methods, bpy_bmelemseq_as_mapping, bpy_bmelemseq_as_sequence, bpy_bmelemseq_dealloc(), bpy_bmelemseq_iter(), bpy_bmelemseq_methods, bpy_bmesh_dealloc(), bpy_bmesh_getseters, bpy_bmesh_methods, bpy_bmesh_repr(), bpy_bmface_dealloc(), bpy_bmface_getseters, bpy_bmface_methods, bpy_bmface_repr(), bpy_bmfaceseq_getseters, bpy_bmfaceseq_methods, bpy_bmiter_next(), bpy_bmloop_dealloc(), bpy_bmloop_getseters, bpy_bmloop_methods, bpy_bmloop_repr(), bpy_bmloopseq_getseters, bpy_bmloopseq_methods, bpy_bmvert_dealloc(), bpy_bmvert_getseters, bpy_bmvert_methods, bpy_bmvert_repr(), bpy_bmvertseq_getseters, bpy_bmvertseq_methods, and NULL.
Referenced by BPyInit_bmesh().
static PyObject* bpy_bm_is_valid_get (BPy_BMGeneric * self) [static]
Definition at line 275 of file bmesh_py_types.c.
References BPY_BM_IS_VALID.
static PyTypeObject* bpy_bm_itype_as_pytype (const char itype) [static]
Definition at line 2215 of file bmesh_py_types.c.
References BM_ALL_LOOPS_OF_FACE, BM_EDGES_OF_FACE, BM_EDGES_OF_MESH, BM_EDGES_OF_VERT, BM_FACES_OF_EDGE, BM_FACES_OF_MESH, BM_FACES_OF_VERT, BM_LOOPS_OF_EDGE, BM_LOOPS_OF_FACE, BM_LOOPS_OF_LOOP, BM_LOOPS_OF_VERT, BM_VERTS_OF_EDGE, BM_VERTS_OF_FACE, BM_VERTS_OF_MESH, BPy_BMEdge_Type, BPy_BMFace_Type, BPy_BMLoop_Type, BPy_BMVert_Type, and NULL.
Referenced by bpy_bmelemseq_contains().
static PyObject* bpy_bmedge_calc_face_angle (BPy_BMEdge * self) [static]
Definition at line 1256 of file bmesh_py_types.c.
References BM_edge_calc_face_angle(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmedge_calc_length (BPy_BMEdge * self) [static]
Definition at line 1244 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, and len_v3v3().
static PyObject* bpy_bmedge_calc_tangent (BPy_BMEdge * self, PyObject * args) [static]
Definition at line 1273 of file bmesh_py_types.c.
References BM_edge_calc_face_tangent(), BPY_BM_CHECK_OBJ, BPy_BMLoop_Type, BPy_BMLoop::l, NULL, Py_NEW, and Vector_CreatePyObject().
PyObject* BPy_BMEdge_CreatePyObject (BMesh * bm, BMEdge * e)
Definition at line 2965 of file bmesh_py_types.c.
References BLI_assert, BM_data_layer_add(), CD_BM_ELEM_PYPTR, CustomData_bmesh_get(), BMHeader::data, BMesh::edata, BMEdge::head, NULL, and UNLIKELY.
Referenced by bpy_bm_utils_edge_rotate(), bpy_bm_utils_edge_split(), bpy_bm_utils_vert_collapse_edge(), bpy_bm_utils_vert_collapse_faces(), bpy_bmedgeseq_get__method(), bpy_bmedgeseq_new(), BPy_BMElem_CreatePyObject(), and bpy_bmloop_edge_get().
static void bpy_bmedge_dealloc (BPy_BMElem * self) [static]
Definition at line 2527 of file bmesh_py_types.c.
References CD_BM_ELEM_PYPTR, CustomData_bmesh_get(), BMesh::edata, and NULL.
Referenced by BPy_BM_init_types().
static PyObject* bpy_bmedge_is_boundary_get (BPy_BMEdge * self) [static]
Definition at line 429 of file bmesh_py_types.c.
References BM_edge_is_boundary(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmedge_is_manifold_get (BPy_BMEdge * self) [static]
Definition at line 409 of file bmesh_py_types.c.
References BM_edge_is_manifold(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmedge_is_wire_get (BPy_BMEdge * self) [static]
Definition at line 419 of file bmesh_py_types.c.
References BM_edge_is_wire(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmedge_normal_update (BPy_BMEdge * self) [static]
Definition at line 1340 of file bmesh_py_types.c.
References BM_edge_normals_update(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmedge_other_vert (BPy_BMEdge * self, BPy_BMVert * value) [static]
Definition at line 1303 of file bmesh_py_types.c.
References BPy_BMVert::bm, BM_edge_other_vert(), BPY_BM_CHECK_OBJ, BPy_BMVert_Check, BPy_BMVert_CreatePyObject(), NULL, and BPy_BMVert::v.
static PyObject* bpy_bmedge_repr (BPy_BMEdge * self) [static]
Definition at line 2632 of file bmesh_py_types.c.
References BM_elem_index_get, BMEdge::v1, and BMEdge::v2.
Referenced by BPy_BM_init_types().
PyObject* BPy_BMEdgeSeq_CreatePyObject (BMesh * bm)
Definition at line 3062 of file bmesh_py_types.c.
References BM_EDGES_OF_MESH, and NULL.
Referenced by bpy_bmedgeseq_get().
static PyObject* bpy_bmedgeseq_get (BPy_BMesh * self, void * UNUSEDclosure) [static]
Definition at line 206 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, and BPy_BMEdgeSeq_CreatePyObject().
static PyObject* bpy_bmedgeseq_get__method (BPy_BMElemSeq * self, PyObject * args) [static]
Definition at line 1935 of file bmesh_py_types.c.
References BM_edge_exists(), BM_VERT, BPY_BM_CHECK_OBJ, BPy_BMEdge_CreatePyObject(), BPy_BMElem_PySeq_As_Array(), NULL, and TRUE.
static PyObject* bpy_bmedgeseq_new (BPy_BMElemSeq * self, PyObject * args) [static]
Definition at line 1682 of file bmesh_py_types.c.
References BPy_BMEdge::bm, BM_edge_create(), BM_edge_exists(), BM_elem_attrs_copy(), BM_VERT, BPY_BM_CHECK_OBJ, BPy_BMEdge_CreatePyObject(), BPy_BMEdge_Type, BPy_BMElem_PySeq_As_Array(), BPy_BMEdge::e, FALSE, NULL, and TRUE.
static PyObject* bpy_bmedgeseq_remove (BPy_BMElemSeq * self, BPy_BMEdge * value) [static]
Definition at line 1869 of file bmesh_py_types.c.
References BPy_BMEdge::bm, BM_edge_kill(), BPY_BM_CHECK_OBJ, bpy_bm_generic_invalidate(), BPy_BMEdge_Check, BPy_BMEdge::e, and NULL.
PyObject* BPy_BMElem_Array_As_Tuple (BMesh * bm, BMHeader ** elem, Py_ssize_t elem_len)
Definition at line 3238 of file bmesh_py_types.c.
References BPy_BMElem_CreatePyObject(), and i.
Referenced by bpy_bm_utils_vert_separate().
static int bpy_bmelem_ass_subscript (BPy_BMElem * self, BPy_BMLayerItem * key, PyObject * value) [static]
Definition at line 2433 of file bmesh_py_types.c.
References BPY_BM_CHECK_INT, and BPy_BMLayerItem_SetItem().
int BPy_BMElem_CheckHType (PyTypeObject * type, const char htype)
Definition at line 3249 of file bmesh_py_types.c.
References BM_EDGE, BM_FACE, BM_LOOP, and BM_VERT.
Referenced by BPy_BMElem_PySeq_As_Array().
PyObject* BPy_BMElem_CreatePyObject (BMesh * bm, BMHeader * ele)
Definition at line 3098 of file bmesh_py_types.c.
References BM_EDGE, BM_FACE, BM_LOOP, BM_VERT, BPy_BMEdge_CreatePyObject(), BPy_BMFace_CreatePyObject(), BPy_BMLoop_CreatePyObject(), BPy_BMVert_CreatePyObject(), BMHeader::htype, and NULL.
Referenced by bpy_bmeditseliter_next(), bpy_bmeditselseq_active_get(), bpy_bmeditselseq_subscript_int(), bpy_bmeditselseq_subscript_slice(), BPy_BMElem_Array_As_Tuple(), bpy_bmelemseq_subscript_int(), bpy_bmelemseq_subscript_slice(), and bpy_bmiter_next().
void* BPy_BMElem_PySeq_As_Array (BMesh ** r_bm, PyObject * seq, Py_ssize_t min, Py_ssize_t max, Py_ssize_t * r_size, const char htype, const char do_unique_check, const char do_bm_check, const char * error_prefix)
Definition at line 3138 of file bmesh_py_types.c.
References BPy_BMElem::bm, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_INTERNAL_TAG, BPY_BM_IS_VALID, BPy_BMElem_CheckHType(), BPy_BMElem_StringFromHType(), BPy_BMElem::ele, FALSE, i, NULL, TRUE, and UNLIKELY.
Referenced by bpy_bm_utils_face_join(), bpy_bm_utils_vert_separate(), bpy_bmedgeseq_get__method(), bpy_bmedgeseq_new(), BPy_BMEditSel_Assign(), bpy_bmfaceseq_get__method(), bpy_bmfaceseq_new(), and bpy_bmvert_copy_from_vert_interp().
char* BPy_BMElem_StringFromHType (const char htype)
Definition at line 3274 of file bmesh_py_types.c.
References BPy_BMElem_StringFromHType_ex().
Referenced by BPy_BMElem_PySeq_As_Array().
char* BPy_BMElem_StringFromHType_ex (const char htype, char ret[32])
Use for error strings only, not thread safe,
Returns:
a sting like '(BMVert/BMEdge/BMFace/BMLoop)'
Definition at line 3262 of file bmesh_py_types.c.
References BM_EDGE, BM_FACE, BM_LOOP, and BM_VERT.
Referenced by BPy_BMElem_StringFromHType(), and bpy_bmlayeritem_ptr_get().
static PyObject* bpy_bmelem_subscript (BPy_BMElem * self, BPy_BMLayerItem * key) [static]
Definition at line 2426 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, and BPy_BMLayerItem_GetItem().
static int bpy_bmelemseq_contains (BPy_BMElemSeq * self, PyObject * value) [static]
Definition at line 2403 of file bmesh_py_types.c.
References BPy_BMElem::bm, BM_ITER_BPY_BM_SEQ, BPY_BM_CHECK_INT, bpy_bm_itype_as_pytype(), and BPy_BMElem::ele.
PyObject* BPy_BMElemSeq_CreatePyObject (BMesh * bm, BPy_BMElem * py_ele, const char itype)
Definition at line 3043 of file bmesh_py_types.c.
Referenced by bpy_bmelemseq_elem_get().
static void bpy_bmelemseq_dealloc (BPy_BMElemSeq * self) [static]
Definition at line 2557 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
static PyObject* bpy_bmelemseq_elem_get (BPy_BMElem * self, void * itype) [static]
Definition at line 265 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, BPy_BMElemSeq_CreatePyObject(), and GET_INT_FROM_POINTER.
static PyObject* bpy_bmelemseq_index_update (BPy_BMElemSeq * self) [static]
Definition at line 2045 of file bmesh_py_types.c.
References BM_EDGE, BM_EDGES_OF_MESH, BM_elem_index_set, BM_FACE, BM_FACES_OF_MESH, BM_ITER_BPY_BM_SEQ, bm_iter_itype_htype_map, BM_mesh_elem_index_ensure(), BM_VERT, BM_VERTS_OF_MESH, BPY_BM_CHECK_OBJ, and BMesh::elem_index_dirty.
static PyObject* bpy_bmelemseq_iter (BPy_BMElemSeq * self) [static]
Definition at line 2469 of file bmesh_py_types.c.
References BM_iter_init(), BPY_BM_CHECK_OBJ, BPy_BMIter_CreatePyObject(), BPy_BMIter::iter, and NULL.
Referenced by BPy_BM_init_types().
static PyObject* bpy_bmelemseq_layers_get (BPy_BMElemSeq * self, void * htype) [static]
Definition at line 551 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, BPy_BMLayerAccess_CreatePyObject(), and GET_INT_FROM_POINTER.
static Py_ssize_t bpy_bmelemseq_length (BPy_BMElemSeq * self) [static]
Definition at line 2245 of file bmesh_py_types.c.
References BM_EDGES_OF_FACE, BM_EDGES_OF_MESH, BM_FACES_OF_MESH, BM_ITER_BPY_BM_SEQ, BM_LOOPS_OF_FACE, BM_VERTS_OF_EDGE, BM_VERTS_OF_FACE, BM_VERTS_OF_MESH, and BPY_BM_CHECK_INT.
Referenced by bpy_bmelemseq_subscript(), and bpy_bmelemseq_subscript_int().
static PyObject* bpy_bmelemseq_subscript (BPy_BMElemSeq * self, PyObject * key) [static]
Definition at line 2350 of file bmesh_py_types.c.
References bpy_bmelemseq_length(), bpy_bmelemseq_subscript_int(), bpy_bmelemseq_subscript_slice(), i, len(), NULL, and step().
static PyObject* bpy_bmelemseq_subscript_int (BPy_BMElemSeq * self, int keynum) [static]
Definition at line 2288 of file bmesh_py_types.c.
References BM_iter_at_index(), BPY_BM_CHECK_OBJ, BPy_BMElem_CreatePyObject(), bpy_bmelemseq_length(), and NULL.
Referenced by bpy_bmelemseq_subscript().
static PyObject* bpy_bmelemseq_subscript_slice (BPy_BMElemSeq * self, Py_ssize_t start, Py_ssize_t stop) [static]
Definition at line 2305 of file bmesh_py_types.c.
References BLI_assert, BMIter::bm, BM_iter_init(), BM_iter_step(), BPY_BM_CHECK_OBJ, BPy_BMElem_CreatePyObject(), FALSE, NULL, TRUE, and UNLIKELY.
Referenced by bpy_bmelemseq_subscript().
static PyObject* bpy_bmesh_clear (BPy_BMesh * self) [static]
Definition at line 725 of file bmesh_py_types.c.
References BM_mesh_clear(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmesh_copy (BPy_BMesh * self) [static]
Definition at line 700 of file bmesh_py_types.c.
References BM_mesh_copy(), BPY_BM_CHECK_OBJ, BPy_BMesh_CreatePyObject(), BPY_BMFLAG_NOP, and NULL.
PyObject* BPy_BMesh_CreatePyObject (BMesh * bm, int flag)
Definition at line 2913 of file bmesh_py_types.c.
References BM_data_layer_add(), CD_BM_ELEM_PYPTR, BMesh::edata, BMesh::ldata, BMesh::pdata, BMesh::py_handle, and BMesh::vdata.
Referenced by bpy_bm_from_edit_mesh(), bpy_bm_new(), and bpy_bmesh_copy().
static void bpy_bmesh_dealloc (BPy_BMesh * self) [static]
Definition at line 2496 of file bmesh_py_types.c.
References BM_data_layer_free(), BM_mesh_free(), BPY_BMFLAG_IS_WRAPPED, CD_BM_ELEM_PYPTR, BMesh::edata, BMesh::ldata, NULL, BMesh::pdata, BMesh::py_handle, and BMesh::vdata.
Referenced by BPy_BM_init_types().
static PyObject* bpy_bmesh_free (BPy_BMesh * self) [static]
Definition at line 749 of file bmesh_py_types.c.
References BM_mesh_free(), bpy_bm_generic_invalidate(), and BPY_BMFLAG_IS_WRAPPED.
static PyObject* bpy_bmesh_from_mesh (BPy_BMesh * self, PyObject * args, PyObject * kw) [static]
Definition at line 859 of file bmesh_py_types.c.
References BM_mesh_bm_from_me(), FALSE, NULL, and PyC_RNA_AsPointer().
static PyObject* bpy_bmesh_from_object (BPy_BMesh * self, PyObject * args) [static]
Definition at line 815 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, Object::derivedDeform, Object::derivedFinal, DM_to_bmesh_ex(), Object::id, ID::name, NULL, PyC_RNA_AsPointer(), and TRUE.
static PyObject* bpy_bmesh_is_wrapped_get (BPy_BMesh * self) [static]
Definition at line 283 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, and BPY_BMFLAG_IS_WRAPPED.
static PyObject* bpy_bmesh_normal_update (BPy_BMesh * self, PyObject * args) [static]
Definition at line 934 of file bmesh_py_types.c.
References BM_mesh_normals_update(), BPY_BM_CHECK_OBJ, FALSE, and NULL.
static PyObject* bpy_bmesh_repr (BPy_BMesh * self) [static]
Definition at line 2605 of file bmesh_py_types.c.
References BMesh::totedge, BMesh::totface, BMesh::totloop, and BMesh::totvert.
Referenced by BPy_BM_init_types().
static PyObject* bpy_bmesh_select_flush (BPy_BMesh * self, PyObject * value) [static]
Definition at line 906 of file bmesh_py_types.c.
References BM_mesh_deselect_flush(), BM_mesh_select_flush(), BPY_BM_CHECK_OBJ, FALSE, NULL, and TRUE.
static PyObject* bpy_bmesh_select_flush_mode (BPy_BMesh * self) [static]
Definition at line 888 of file bmesh_py_types.c.
References BM_mesh_select_mode_flush(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmesh_select_history_get (BPy_BMesh * self) [static]
Definition at line 322 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, and BPy_BMEditSel_CreatePyObject().
static int bpy_bmesh_select_history_set (BPy_BMesh * self, PyObject * value) [static]
Definition at line 329 of file bmesh_py_types.c.
References BPY_BM_CHECK_INT, and BPy_BMEditSel_Assign().
static PyObject* bpy_bmesh_select_mode_get (BPy_BMesh * self) [static]
Definition at line 293 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, and PyC_FlagSet_FromBitfield().
static int bpy_bmesh_select_mode_set (BPy_BMesh * self, PyObject * value) [static]
Definition at line 300 of file bmesh_py_types.c.
References BPY_BM_CHECK_INT, and PyC_FlagSet_ToBitfield().
static PyObject* bpy_bmesh_to_mesh (BPy_BMesh * self, PyObject * args) [static]
Definition at line 772 of file bmesh_py_types.c.
References BM_mesh_bm_to_me(), BPY_BM_CHECK_OBJ, DAG_id_tag_update(), Mesh::edit_btmesh, FALSE, Mesh::id, ID::name, NULL, OB_RECALC_DATA, and PyC_RNA_AsPointer().
static PyObject* bpy_bmesh_transform (BPy_BMElem * self, PyObject * args, PyObject * kw) [static]
Definition at line 961 of file bmesh_py_types.c.
References BaseMath_ReadCallback, BMIter::bm, BM_ITER_MESH, BM_VERTS_OF_MESH, BPY_BM_CHECK_OBJ, BMVert::co, filter(), BMVert::head, BMHeader::hflag, matrix_Type, mul_m4_v3(), NULL, MatrixObject::num_col, MatrixObject::num_row, and PyC_FlagSet_ToBitfield().
static PyObject* bpy_bmface_calc_area (BPy_BMFace * self) [static]
Definition at line 1442 of file bmesh_py_types.c.
References BM_face_calc_area(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmface_calc_center_bounds (BPy_BMFace * self) [static]
Definition at line 1490 of file bmesh_py_types.c.
References BM_face_calc_center_bounds(), BPY_BM_CHECK_OBJ, NULL, Py_NEW, and Vector_CreatePyObject().
static PyObject* bpy_bmface_calc_center_mean (BPy_BMFace * self) [static]
Definition at line 1472 of file bmesh_py_types.c.
References BM_face_calc_center_mean(), BPY_BM_CHECK_OBJ, NULL, Py_NEW, and Vector_CreatePyObject().
static PyObject* bpy_bmface_calc_perimeter (BPy_BMFace * self) [static]
Definition at line 1457 of file bmesh_py_types.c.
References BM_face_calc_perimeter(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmface_copy (BPy_BMFace * self, PyObject * args, PyObject * kw) [static]
Definition at line 1402 of file bmesh_py_types.c.
References BM_face_copy(), BPY_BM_CHECK_OBJ, BPy_BMFace_CreatePyObject(), NULL, and TRUE.
static PyObject* bpy_bmface_copy_from_face_interp (BPy_BMFace * self, PyObject * args) [static]
Definition at line 1361 of file bmesh_py_types.c.
References BPy_BMFace::bm, BM_face_interp_from_face(), BPY_BM_CHECK_OBJ, BPy_BMFace_Type, BPy_BMFace::f, and NULL.
PyObject* BPy_BMFace_CreatePyObject (BMesh * bm, BMFace * f)
Definition at line 2991 of file bmesh_py_types.c.
References BLI_assert, BM_data_layer_add(), CD_BM_ELEM_PYPTR, CustomData_bmesh_get(), BMHeader::data, BMFace::head, NULL, BMesh::pdata, and UNLIKELY.
Referenced by bpy_bm_utils_face_join(), bpy_bm_utils_face_split(), BPy_BMElem_CreatePyObject(), bpy_bmface_copy(), bpy_bmfaceseq_get__method(), bpy_bmfaceseq_new(), and bpy_bmloop_face_get().
static void bpy_bmface_dealloc (BPy_BMElem * self) [static]
Definition at line 2537 of file bmesh_py_types.c.
References CD_BM_ELEM_PYPTR, CustomData_bmesh_get(), NULL, and BMesh::pdata.
Referenced by BPy_BM_init_types().
static PyObject* bpy_bmface_material_index_get (BPy_BMFace * self) [static]
Definition at line 463 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ.
static int bpy_bmface_material_index_set (BPy_BMFace * self, PyObject * value) [static]
Definition at line 469 of file bmesh_py_types.c.
References BPY_BM_CHECK_INT, and MAXMAT.
static PyObject* bpy_bmface_normal_get (BPy_BMFace * self) [static]
Definition at line 442 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, NULL, Py_WRAP, and Vector_CreatePyObject().
static int bpy_bmface_normal_set (BPy_BMFace * self, PyObject * value) [static]
Definition at line 448 of file bmesh_py_types.c.
References BPY_BM_CHECK_INT, and mathutils_array_parse().
static PyObject* bpy_bmface_normal_update (BPy_BMFace * self) [static]
Definition at line 1505 of file bmesh_py_types.c.
References BM_face_normal_update(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmface_repr (BPy_BMFace * self) [static]
Definition at line 2648 of file bmesh_py_types.c.
References BM_elem_index_get, and BMFace::len.
Referenced by BPy_BM_init_types().
PyObject* BPy_BMFaceSeq_CreatePyObject (BMesh * bm)
Definition at line 3071 of file bmesh_py_types.c.
References BM_FACES_OF_MESH, and NULL.
Referenced by bpy_bmfaceseq_get().
static PyObject* bpy_bmfaceseq_get (BPy_BMesh * self, void * UNUSEDclosure) [static]
Definition at line 215 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, and BPy_BMFaceSeq_CreatePyObject().
static PyObject* bpy_bmfaceseq_get__method (BPy_BMElemSeq * self, PyObject * args) [static]
Definition at line 1987 of file bmesh_py_types.c.
References BM_face_exists(), BM_VERT, BPY_BM_CHECK_OBJ, BPy_BMElem_PySeq_As_Array(), BPy_BMFace_CreatePyObject(), NULL, and TRUE.
static PyObject* bpy_bmfaceseq_new (BPy_BMElemSeq * self, PyObject * args) [static]
Definition at line 1755 of file bmesh_py_types.c.
References BPy_BMFace::bm, BM_edge_create(), BM_elem_attrs_copy(), BM_face_create(), BM_face_exists(), BM_VERT, BPY_BM_CHECK_OBJ, BPy_BMElem_PySeq_As_Array(), BPy_BMFace_CreatePyObject(), BPy_BMFace_Type, BPy_BMFace::f, FALSE, i, NULL, and TRUE.
static PyObject* bpy_bmfaceseq_remove (BPy_BMElemSeq * self, BPy_BMFace * value) [static]
Definition at line 1899 of file bmesh_py_types.c.
References BPy_BMFace::bm, BM_face_kill(), BPY_BM_CHECK_OBJ, bpy_bm_generic_invalidate(), BPy_BMFace_Check, BPy_BMFace::f, and NULL.
PyObject* BPy_BMIter_CreatePyObject (BMesh * bm)
Definition at line 3089 of file bmesh_py_types.c.
Referenced by bpy_bmelemseq_iter().
static PyObject* bpy_bmiter_next (BPy_BMIter * self) [static]
Definition at line 2479 of file bmesh_py_types.c.
References BM_iter_step(), BPy_BMElem_CreatePyObject(), and NULL.
Referenced by BPy_BM_init_types().
static PyObject* bpy_bmloop_calc_angle (BPy_BMLoop * self) [static]
Definition at line 1571 of file bmesh_py_types.c.
References BM_loop_calc_face_angle(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmloop_calc_normal (BPy_BMLoop * self) [static]
Definition at line 1586 of file bmesh_py_types.c.
References BM_loop_calc_face_normal(), BPY_BM_CHECK_OBJ, NULL, Py_NEW, and Vector_CreatePyObject().
static PyObject* bpy_bmloop_calc_tangent (BPy_BMLoop * self) [static]
Definition at line 1603 of file bmesh_py_types.c.
References BM_loop_calc_face_tangent(), BPY_BM_CHECK_OBJ, NULL, Py_NEW, and Vector_CreatePyObject().
static PyObject* bpy_bmloop_copy_from_face_interp (BPy_BMLoop * self, PyObject * args) [static]
Definition at line 1530 of file bmesh_py_types.c.
References BPy_BMFace::bm, BM_loop_interp_from_face(), BPY_BM_CHECK_OBJ, BPy_BMFace_Type, BPy_BMFace::f, NULL, and TRUE.
PyObject* BPy_BMLoop_CreatePyObject (BMesh * bm, BMLoop * l)
Definition at line 3017 of file bmesh_py_types.c.
References BLI_assert, BM_data_layer_add(), CD_BM_ELEM_PYPTR, CustomData_bmesh_get(), BMHeader::data, BMLoop::head, BMesh::ldata, NULL, and UNLIKELY.
Referenced by bpy_bm_utils_face_split(), BPy_BMElem_CreatePyObject(), bpy_bmloop_link_loop_next_get(), and bpy_bmloop_link_loop_prev_get().
static void bpy_bmloop_dealloc (BPy_BMElem * self) [static]
Definition at line 2547 of file bmesh_py_types.c.
References CD_BM_ELEM_PYPTR, CustomData_bmesh_get(), BMesh::ldata, and NULL.
Referenced by BPy_BM_init_types().
static PyObject* bpy_bmloop_edge_get (BPy_BMLoop * self) [static]
Definition at line 510 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, and BPy_BMEdge_CreatePyObject().
static PyObject* bpy_bmloop_face_get (BPy_BMLoop * self) [static]
Definition at line 520 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, and BPy_BMFace_CreatePyObject().
static PyObject* bpy_bmloop_link_loop_next_get (BPy_BMLoop * self) [static]
Definition at line 529 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, and BPy_BMLoop_CreatePyObject().
static PyObject* bpy_bmloop_link_loop_prev_get (BPy_BMLoop * self) [static]
Definition at line 538 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, and BPy_BMLoop_CreatePyObject().
static PyObject* bpy_bmloop_repr (BPy_BMLoop * self) [static]
Definition at line 2663 of file bmesh_py_types.c.
References BM_elem_index_get, BMLoop::e, BMLoop::f, and BMLoop::v.
Referenced by BPy_BM_init_types().
static PyObject* bpy_bmloop_vert_get (BPy_BMLoop * self) [static]
Definition at line 500 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, and BPy_BMVert_CreatePyObject().
PyObject* BPy_BMLoopSeq_CreatePyObject (BMesh * bm)
Definition at line 3080 of file bmesh_py_types.c.
References NULL.
Referenced by bpy_bmloopseq_get().
static PyObject* bpy_bmloopseq_get (BPy_BMesh * self, void * UNUSEDclosure) [static]
Definition at line 224 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, and BPy_BMLoopSeq_CreatePyObject().
static PyObject* bpy_bmvert_calc_edge_angle (BPy_BMVert * self) [static]
Definition at line 1198 of file bmesh_py_types.c.
References BM_vert_calc_edge_angle(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmvert_calc_shell_factor (BPy_BMVert * self) [static]
Definition at line 1214 of file bmesh_py_types.c.
References BM_vert_calc_shell_factor(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmvert_co_get (BPy_BMVert * self) [static]
Definition at line 342 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, NULL, Py_WRAP, and Vector_CreatePyObject().
static int bpy_bmvert_co_set (BPy_BMVert * self, PyObject * value) [static]
Definition at line 348 of file bmesh_py_types.c.
References BPY_BM_CHECK_INT, and mathutils_array_parse().
static PyObject* bpy_bmvert_copy_from_face_interp (BPy_BMVert * self, PyObject * args) [static]
Definition at line 1161 of file bmesh_py_types.c.
References BPy_BMFace::bm, BM_vert_interp_from_face(), BPY_BM_CHECK_OBJ, BPy_BMFace_Type, BPy_BMFace::f, and NULL.
static PyObject* bpy_bmvert_copy_from_vert_interp (BPy_BMVert * self, PyObject * args) [static]
Definition at line 1120 of file bmesh_py_types.c.
References BM_data_interp_from_verts(), BM_VERT, BPY_BM_CHECK_OBJ, BPy_BMElem_PySeq_As_Array(), CLAMPIS, NULL, and TRUE.
PyObject* BPy_BMVert_CreatePyObject (BMesh * bm, BMVert * v)
Definition at line 2939 of file bmesh_py_types.c.
References BLI_assert, BM_data_layer_add(), CD_BM_ELEM_PYPTR, CustomData_bmesh_get(), BMHeader::data, BMVert::head, NULL, UNLIKELY, and BMesh::vdata.
Referenced by bpy_bm_utils_edge_split(), bpy_bm_utils_face_vert_separate(), bpy_bm_utils_loop_separate(), bpy_bmedge_other_vert(), BPy_BMElem_CreatePyObject(), bpy_bmloop_vert_get(), and bpy_bmvertseq_new().
static void bpy_bmvert_dealloc (BPy_BMElem * self) [static]
Definition at line 2517 of file bmesh_py_types.c.
References CD_BM_ELEM_PYPTR, CustomData_bmesh_get(), NULL, and BMesh::vdata.
Referenced by BPy_BM_init_types().
static PyObject* bpy_bmvert_is_manifold_get (BPy_BMVert * self) [static]
Definition at line 386 of file bmesh_py_types.c.
References BM_vert_is_manifold(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmvert_is_wire_get (BPy_BMVert * self) [static]
Definition at line 396 of file bmesh_py_types.c.
References BM_vert_is_wire(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmvert_normal_get (BPy_BMVert * self) [static]
Definition at line 364 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, NULL, Py_WRAP, and Vector_CreatePyObject().
static int bpy_bmvert_normal_set (BPy_BMVert * self, PyObject * value) [static]
Definition at line 370 of file bmesh_py_types.c.
References BPY_BM_CHECK_INT, and mathutils_array_parse().
static PyObject* bpy_bmvert_normal_update (BPy_BMVert * self) [static]
Definition at line 1225 of file bmesh_py_types.c.
References BM_vert_normal_update(), and BPY_BM_CHECK_OBJ.
static PyObject* bpy_bmvert_repr (BPy_BMVert * self) [static]
Definition at line 2618 of file bmesh_py_types.c.
References BM_elem_index_get.
Referenced by BPy_BM_init_types().
PyObject* BPy_BMVertSeq_CreatePyObject (BMesh * bm)
Definition at line 3053 of file bmesh_py_types.c.
References BM_VERTS_OF_MESH, and NULL.
Referenced by bpy_bmvertseq_get().
static PyObject* bpy_bmvertseq_get (BPy_BMesh * self, void * UNUSEDclosure) [static]
Definition at line 197 of file bmesh_py_types.c.
References BPY_BM_CHECK_OBJ, and BPy_BMVertSeq_CreatePyObject().
static PyObject* bpy_bmvertseq_new (BPy_BMElemSeq * self, PyObject * args) [static]
Definition at line 1625 of file bmesh_py_types.c.
References BPy_BMVert::bm, BM_elem_attrs_copy(), BM_vert_create(), BPY_BM_CHECK_OBJ, BPy_BMVert_CreatePyObject(), BPy_BMVert_Type, co, mathutils_array_parse(), NULL, and BPy_BMVert::v.
static PyObject* bpy_bmvertseq_remove (BPy_BMElemSeq * self, BPy_BMVert * value) [static]
Definition at line 1839 of file bmesh_py_types.c.
References BPy_BMVert::bm, BM_vert_kill(), BPY_BM_CHECK_OBJ, bpy_bm_generic_invalidate(), BPy_BMVert_Check, NULL, and BPy_BMVert::v.
PyObject* BPyInit_bmesh_types (void)
Definition at line 2870 of file bmesh_py_types.c.
References BPy_BMDeformVert_Type, BPy_BMEditSelIter_Type, BPy_BMEditSelSeq_Type, BPy_BMLayerAccessEdge_Type, BPy_BMLayerAccessFace_Type, BPy_BMLayerAccessLoop_Type, BPy_BMLayerAccessVert_Type, BPy_BMLayerCollection_Type, BPy_BMLayerItem_Type, BPy_BMLoopUV_Type, and MODULE_TYPE_ADD.
Referenced by BPyInit_bmesh().
PyDoc_STRVAR (bpy_bmesh_normal_update_doc , ".. method:: normal_update(skip_hidden=False)\n""\n"" Update mesh normals.\n""\n"" :arg skip_hidden: When True hidden elements are ignored.\n"" :type skip_hidden: boolean\n")
PyDoc_STRVAR (bpy_bmedge_verts_doc , "Verts this edge uses always 2, (read-only).\n\n:type::class:`BMElemSeq`of:class:`BMVert`")
PyDoc_STRVAR (bpy_bmface_verts_doc , "Verts of this face, (read-only).\n\n:type::class:`BMElemSeq`of:class:`BMVert`")
PyDoc_STRVAR (bpy_bmelemseq_index_update_doc , ".. method:: index_update()\n""\n"" Initialize the index values of this sequence.\n""\n"" This is the equivalent of looping over all elements and assigning the index values.\n""\n"" .. code-block:: python\n""\n"" for index, ele in enumerate(sequence):\n""ele. index = index\n""\n"" .. note::\n""\n"" Running this on sequences besides :class:`BMesh.verts`, :class:`BMesh.edges` , :class:`BMesh.faces`\n""works but wont result in each element having a valid index, insted its order in the sequence will be set.\n")
PyDoc_STRVAR (bpy_bm_elem_seam_doc , "Seam for UV unwrapping.\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmfaceseq_remove_doc , ".. method:: remove(face)\n""\n"" Remove a face.\n")
PyDoc_STRVAR (bpy_bmloop_doc , "This is normally accessed from :class:`BMFace.loops` where each face corner represents a corner of a face.\n")
PyDoc_STRVAR (bpy_bm_elem_tag_doc , "Generic attribute scripts can use for own logic\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmedge_doc , "The BMesh edge connecting 2 verts\n")
PyDoc_STRVAR (bpy_bmesh_from_object_doc , ".. method:: from_object(mesh, apply_modifiers=True)\n""\n"" Initialize this bmesh from existing object datablock.\n""\n"" :arg object: The object data to load.\n"" :type object: :class:`Object`\n"" :arg apply_modifiers: Use the final display mesh rather then the deformed cage.\n"" :type apply_modifiers: boolean\n")
PyDoc_STRVAR (bpy_bmvert_link_faces_doc , "Faces connected to this vertex (read-only).\n\n:type: :class:`BMElemSeq` of :class:`BMFace`")
PyDoc_STRVAR (bpy_bmesh_from_mesh_doc , ".. method:: from_mesh(mesh, use_shape_key=False, shape_key_index=0)\n""\n"" Initialize this bmesh from existing mesh datablock.\n""\n"" :arg mesh: The mesh data to load.\n"" :type mesh: :class:`Mesh`\n"" :arg use_shape_key: Use the locations from a shape key.\n"" :type use_shape_key: boolean\n"" :arg shape_key_index: The shape key index to use.\n"" :type shape_key_index: int\n")
PyDoc_STRVAR (bpy_bmfaceseq_get__method_doc , ".. method:: get(verts, fallback=None)\n""\n"" Return a face which uses the **verts** passed.\n""\n"" :arg verts: Sequence of verts.\n"" :type verts: :class:`BMVert`\n"" :arg fallback: Return this value if nothing is found.\n"" :return: The face found or None\n"" :rtype: :class:`BMFace`\n")
PyDoc_STRVAR (bpy_bmiter_doc , "Internal BMesh type for looping over verts/faces/ edges, \n""used for iterating over:class:`BMElemSeq`types.\n")
PyDoc_STRVAR (bpy_bmvert_copy_from_vert_interp_doc , ".. method:: copy_from_vert_interp(vert_pair, fac)\n""\n"" Interpolate the customdata from a vert between 2 other verts.\n""\n"" :arg vert_pair: The vert to interpolate data from.\n"" :type vert_pair: :class:`BMVert`\n")
PyDoc_STRVAR (bpy_bmelemseq_doc , "General sequence type used for accessing any sequence of \n"":class:`BMVert` , :class:`BMEdge` , :class:`BMFace` , :class:`BMLoop`.\n""\n""When accessed via:class:`BMesh.verts` , :class:`BMesh.edges` , :class:`BMesh.faces`\n""there are also functions to create/remomove items.\n")
PyDoc_STRVAR (bpy_bmvert_co_doc , "The coordinates for this vertex as a 3D, wrapped vector.\n\n:type::class:`mathutils.Vector`")
PyDoc_STRVAR (bpy_bmvert_normal_doc , "The normal for this vertex as a 3D, wrapped vector.\n\n:type::class:`mathutils.Vector`")
PyDoc_STRVAR (bpy_bmvert_copy_from_face_interp_doc , ".. method:: copy_from_face_interp(face)\n""\n"" Interpolate the customdata from a face onto this loop (the loops vert should overlap the face).\n""\n"" :arg face: The face to interpolate data from.\n"" :type face: :class:`BMFace`\n")
PyDoc_STRVAR (bpy_bmedge_normal_update_doc , ".. method:: normal_update()\n""\n"" Update edges vertex normals.\n")
PyDoc_STRVAR (bpy_bmfaceseq_doc , "This meshes face sequence (read-only).\n\n:type: :class:`BMFaceSeq`")
PyDoc_STRVAR (bpy_bmloopseq_doc , "This meshes face sequence (read-only).\n\n:type: :class:`BMLoopSeq`")
PyDoc_STRVAR (bpy_bmloop_link_loop_next_doc , "The next face corner (read-only).\n\n:type: :class:`BMLoop`")
PyDoc_STRVAR (bpy_bmvertseq_remove_doc , ".. method:: remove(vert)\n""\n"" Remove a vert.\n")
PyDoc_STRVAR (bpy_bmelemseq_layers_doc , "blah blah (read-only).\n\n:type: :class:`BMLayerAccess`")
PyDoc_STRVAR (bpy_bmedgeseq_remove_doc , ".. method:: remove(edge)\n""\n"" Remove a edge.\n")
PyDoc_STRVAR (bpy_bm_elem_hide_doc , "Hidden state of this element.\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmesh_select_flush_mode_doc , ".. method:: select_flush_mode()\n""\n"" flush selection based on the current mode current :class:`BMesh.select_mode`.\n")
PyDoc_STRVAR (bpy_bmloop_calc_normal_doc , ".. method:: calc_normal()\n""\n"" Return normal at this loops corner of the face.\n"" Falls back to the face normal for straignt lines.\n""\n"" :return: a normalized vector.\n"" :rtype: :class:`mathutils.Vector`\n")
PyDoc_STRVAR (bpy_bmloop_link_loop_prev_doc , "The previous face corner (read-only).\n\n:type: :class:`BMLoop`")
PyDoc_STRVAR (bpy_bmedgeseq_new_doc , ".. method:: new(verts, example=None)\n""\n"" Create a new edge from a given pair of verts.\n""\n"" :arg verts: Vertex pair.\n"" :type verts: pair of :class:`BMVert`\n"" :arg example: Existing edge to initialize settings (optional argument).\n"" :type example: :class:`BMEdge`\n"" :return: The newly created edge.\n"" :rtype: :class:`BMEdge`\n")
PyDoc_STRVAR (bpy_bmloop_calc_angle_doc , ".. method:: calc_angle()\n""\n"" Return the angle at this loops corner of the face.\n"" This is calculated so sharper corners give lower angles.\n""\n"" :return: The angle in radians.\n"" :rtype: float\n")
PyDoc_STRVAR (bpy_bm_elem_copy_from_doc , ".. method:: copy_from(other)\n""\n"" Copy values from another element of matching type.\n")
PyDoc_STRVAR (bpy_bmedge_is_manifold_doc , "True when this edge is manifold (read-only).\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmedge_link_faces_doc , "Faces connected to this edge, (read-only).\n\n:type::class:`BMElemSeq`of:class:`BMFace`")
PyDoc_STRVAR (bpy_bmvert_is_wire_doc , "True when this vertex is not connected to any faces (read-only).\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmedge_is_wire_doc , "True when this edge is not connected to any faces (read-only).\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmloop_vert_doc , "The loops vertex (read-only).\n\n:type: :class:`BMVert`")
PyDoc_STRVAR (bpy_bmesh_doc , "The BMesh data structure\n")
PyDoc_STRVAR (bpy_bmface_calc_center_bounds_doc , ".. method:: calc_center_bounds()\n""\n"" Return bounds center of the face.\n""\n"" :return: a 3D vector.\n"" :rtype: :class:`mathutils.Vector`\n")
PyDoc_STRVAR (bpy_bmesh_select_mode_doc , "The selection mode)
PyDoc_STRVAR (bpy_bm_elem_hide_set_doc , ".. method:: hide_set(hide)\n""\n"" Set the hide state.\n"" This is different from the *hide* attribute because it updates the selection and hide state of assosiated geometry.\n""\n"" :arg hide: Hidden or visible.\n"" :type hide: boolean\n")
PyDoc_STRVAR (bpy_bmloop_face_doc , "The face this loop makes (read-only).\n\n:type: :class:`BMFace`")
PyDoc_STRVAR (bpy_bmface_doc , "The BMesh face with 3 or more sides\n")
PyDoc_STRVAR (bpy_bmvert_calc_shell_factor_doc , ".. method:: calc_shell_factor()\n""\n"" Return a multiplier calculated based on the sharpness of the vertex.\n"" Where a flat surface gives 1. 0, and higher values sharper edges.\n""This is used to maintain shell thickness when offsetting verts along their normals.\n""\n"":return:offset multiplier\n"":rtype:float\n")
PyDoc_STRVAR (bpy_bmvert_link_edges_doc , "Edges connected to this vertex (read-only).\n\n:type: :class:`BMElemSeq` of :class:`BMVert`")
PyDoc_STRVAR (bpy_bmvertseq_new_doc , ".. method:: new(co=(0.0, 0.0, 0.0), example=None)\n""\n"" Create a new vertex.\n""\n"" :arg co: The initial location of the vertex (optional argument).\n"" :type co: float triplet\n"" :arg example: Existing vert to initialize settings.\n"" :type example: :class:`BMVert`\n"" :return: The newly created edge.\n"" :rtype: :class:`BMVert`\n")
PyDoc_STRVAR (bpy_bmfaceseq_new_doc , ".. method:: new(verts, example=None)\n""\n"" Create a new face from a given set of verts.\n""\n"" :arg verts: Sequence of 3 or more verts.\n"" :type verts: :class:`BMVert`\n"" :arg example: Existing face to initialize settings (optional argument).\n"" :type example: :class:`BMFace`\n"" :return: The newly created face.\n"" :rtype: :class:`BMFace`\n")
PyDoc_STRVAR (bpy_bmface_normal_update_doc , ".. method:: normal_update()\n""\n"" Update faces normal.\n")
PyDoc_STRVAR (bpy_bmesh_clear_doc , ".. method:: clear()\n""\n"" Clear all mesh data.\n")
PyDoc_STRVAR (bpy_bmface_calc_perimeter_doc , ".. method:: calc_perimeter()\n""\n"" Return the perimeter of the face.\n""\n"" :return: Return the perimeter of the face.\n"" :rtype: float\n")
PyDoc_STRVAR (bpy_bmesh_select_history_doc , "Sequence of selected items (the last is displayed as active).\n\n:type: :class:`BMEditSelSeq`")
PyDoc_STRVAR (bpy_bmesh_copy_doc , ".. method:: copy()\n""\n"" :return: A copy of this BMesh.\n"" :rtype: :class:`BMesh`\n")
PyDoc_STRVAR (bpy_bmface_calc_center_mean_doc , ".. method:: calc_center_median()\n""\n"" Return median center of the face.\n""\n"" :return: a 3D vector.\n"" :rtype: :class:`mathutils.Vector`\n")
PyDoc_STRVAR (bpy_bmesh_is_wrapped_doc , "True when this mesh is owned by blender (typically the editmode BMesh).\n\n:type: boolean")
PyDoc_STRVAR (bpy_bm_elem_select_doc , "Selected state of this element.\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmface_calc_area_doc , ".. method:: calc_area()\n""\n"" Return the area of the face.\n""\n"" :return: Return the area of the face.\n"" :rtype: float\n")
PyDoc_STRVAR (bpy_bmface_copy_doc , ".. method:: copy(verts=True, edges=True)\n""\n"" Make a copy of this face.\n""\n"" :arg verts: When set, the faces verts will be duplicated too.\n"":type verts:boolean\n"":arg edges:When set, the faces edges will be duplicated too.\n"":type edges:boolean\n"":return:The newly created face.\n"":rtype::class:`BMFace`\n")
PyDoc_STRVAR (bpy_bmesh_to_mesh_doc , ".. method:: to_mesh(mesh)\n""\n"" Writes this BMesh data into an existing Mesh datablock.\n""\n"" :arg mesh: The mesh data to write into.\n"" :type mesh: :class:`Mesh`\n")
PyDoc_STRVAR (bpy_bmloop_copy_from_face_interp_doc , ".. method:: copy_from_face_interp(face, vert=True, multires=True)\n""\n"" Interpolate the customdata from a face onto this loop (the loops vert should overlap the face).\n""\n"" :arg face: The face to interpolate data from.\n"" :type face: :class:`BMFace`\n"" :arg vert: When enabled, interpolate the loops vertex data(optional).\n"":type vert:boolean\n"":arg multires:When enabled, interpolate the loops multires data(optional).\n"":type multires:boolean\n")
PyDoc_STRVAR (bpy_bmloop_calc_tangent_doc , ".. method:: calc_tangent()\n""\n"" Return the tangent at this loops corner of the face (pointing inward into the face).\n"" Falls back to the face normal for straignt lines.\n""\n"" :return: a normalized vector.\n"" :rtype: :class:`mathutils.Vector`\n")
PyDoc_STRVAR (bpy_bm_elem_index_doc , "Index of this element.\n""\n"":type: int\n""\n"".. note::\n""\n"" This value is not necessarily valid, while editing the mesh it can become *dirty *.\n""\n""It's also possible to assign any number to this attribute for a scripts internal logic.\n""\n""To ensure the value is up to date-see:class:`BMElemSeq.index_update`.\n")
PyDoc_STRVAR (bpy_bmvert_is_manifold_doc , "True when this vertex is manifold (read-only).\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmface_loops_doc , "Loops of this face, (read-only).\n\n:type::class:`BMElemSeq`of:class:`BMLoop`")
PyDoc_STRVAR (bpy_bmedge_calc_face_angle_doc , ".. method:: calc_face_angle()\n""\n"" :return: The angle between 2 connected faces in radians.\n"" :rtype: float\n")
PyDoc_STRVAR (bpy_bmedge_is_boundary_doc , "True when this edge is at the boundary of a face (read-only).\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmesh_transform_doc , ".. method:: transform(matrix, filter=None)\n""\n"" Transform the mesh (optionally filtering flagged data only).\n""\n"" :arg matrix: transform matrix.\n"" :type matrix: 4x4 :class:`mathutils.Matrix`\n"" :arg filter: set of values in ('SELECT', 'HIDE', 'SEAM', 'SMOOTH', 'TAG').\n"" :type filter: set\n")
PyDoc_STRVAR (bpy_bmvert_normal_update_doc , ".. method:: normal_update()\n""\n"" Update vertex normal.\n")
PyDoc_STRVAR (bpy_bm_elem_select_set_doc , ".. method:: select_set(select)\n""\n"" Set the selection.\n"" This is different from the *select* attribute because it updates the selection state of assosiated geometry.\n""\n"" :arg select: Select or de-select.\n"" :type select: boolean\n""\n"" .. note::\n""\n"" Currently this only flushes down, so selecting a face will select all its vertices but de-selecting a vertex""won't de-select all the faces that use it, before finishing with a mesh typically flushing is still needed.\n")
PyDoc_STRVAR (bpy_bmedge_calc_length_doc , ".. method:: calc_length()\n""\n"" :return: The length between both verts.\n"" :rtype: float\n")
PyDoc_STRVAR (bpy_bmface_copy_from_face_interp_doc , ".. method:: copy_from_face_interp(face)\n""\n"" Interpolate the customdata from another face onto this one (faces should overlap).\n""\n"" :arg face: The face to interpolate data from.\n"" :type face: :class:`BMFace`\n")
PyDoc_STRVAR (bpy_bmloop_edge_doc , "The loops edge between this loop and the next, (read-only).\n\n:type::class:`BMEdge`")
PyDoc_STRVAR (bpy_bmloops_link_loops_doc , "Loops connected to this loop, (read-only).\n\n:type::class:`BMElemSeq`of:class:`BMLoop`")
PyDoc_STRVAR (bpy_bmedge_other_vert_doc , ".. method:: other_vert(vert)\n""\n"" Return the other vertex on this edge or None if the vertex is not used by this edge.\n""\n"" :arg vert: a vert in this edge.\n"" :type vert: :class:`BMVert`\n"" :return: The edges other vert.\n"" :rtype: :class:`BMVert` or None\n")
PyDoc_STRVAR (bpy_bm_is_valid_doc , "True when this element is valid (hasn't been removed).\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmface_material_index_doc , "The faces material index.\n\n:type: int")
PyDoc_STRVAR (bpy_bmface_normal_doc , "The normal for this face as a 3D, wrapped vector.\n\n:type::class:`mathutils.Vector`")
PyDoc_STRVAR (bpy_bmvert_calc_edge_angle_doc , ".. method:: calc_edge_angle()\n""\n"" Return the angle between this verts 2 connected edges.\n""\n"" :return: Angle between edges in radians.\n"" :rtype: float\n")
PyDoc_STRVAR (bpy_bmvert_link_loops_doc , "Loops that use this vertex (read-only).\n\n:type: :class:`BMElemSeq` of :class:`BMLoop`")
PyDoc_STRVAR (bpy_bmedgeseq_doc , "This meshes edge sequence (read-only).\n\n:type: :class:`BMEdgeSeq`")
PyDoc_STRVAR (bpy_bmface_edges_doc , "Edges of this face, (read-only).\n\n:type::class:`BMElemSeq`of:class:`BMEdge`")
PyDoc_STRVAR (bpy_bmesh_select_flush_doc , ".. method:: select_flush(select)\n""\n"" Flush selection, independent of the current selection mode.\n""\n"":arg select:flush selection or de-selected elements.\n"":type select:boolean\n")
PyDoc_STRVAR (bpy_bmedge_calc_tangent_doc , ".. method:: calc_tangent(loop)\n""\n"" Return the tangent at this edge relative to a face (pointing inward into the face).\n"" This uses the face normal for calculation.\n""\n"" :arg loop: The loop used for tangent calculation.\n"" :type loop: :class:`BMLoop`\n"" :return: a normalized vector.\n"" :rtype: :class:`mathutils.Vector`\n")
PyDoc_STRVAR (bpy_bmvert_doc , "The BMesh vertex type\n")
PyDoc_STRVAR (bpy_bmedgeseq_get__method_doc , ".. method:: get(verts, fallback=None)\n""\n"" Return a edge which uses the **verts** passed.\n""\n"" :arg verts: Sequence of verts.\n"" :type verts: :class:`BMVert`\n"" :arg fallback: Return this value if nothing is found.\n"" :return: The edge found or None\n"" :rtype: :class:`BMEdge`\n")
PyDoc_STRVAR (bpy_bmedge_link_loops_doc , "Loops connected to this edge, (read-only).\n\n:type::class:`BMElemSeq`of:class:`BMLoop`")
PyDoc_STRVAR (bpy_bm_elem_smooth_doc , "Smooth state of this element.\n\n:type: boolean")
PyDoc_STRVAR (bpy_bmesh_free_doc , ".. method:: free()\n""\n"" Explicitly free the BMesh data from memory, causing exceptions on further access.\n""\n""..note::\n""\n""The BMesh is freed automatically, typically when the script finishes executing.\n""However in some cases its hard to predict when this will be and its useful to\n""explicitly free the data.\n")
PyDoc_STRVAR (bpy_bmvertseq_doc , "This meshes vert sequence (read-only).\n\n:type: :class:`BMVertSeq`")
Variable Documentation
PyMappingMethods bpy_bm_elem_as_mapping [static]
Initial value:
 {
    (lenfunc)NULL,
    (binaryfunc)bpy_bmelem_subscript,
    (objobjargproc)bpy_bmelem_ass_subscript,
}
Definition at line 2460 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
PyC_FlagSet bpy_bm_hflag_all_flags[]
Initial value:
 {
    {BM_ELEM_SELECT,  "SELECT"},
    {BM_ELEM_HIDDEN,  "HIDE"},
    {BM_ELEM_SEAM,    "SEAM"},
    {BM_ELEM_SMOOTH,  "SMOOTH"},
    {BM_ELEM_TAG,     "TAG"},
    {0, NULL}
}
Definition at line 79 of file bmesh_py_types.c.
PyC_FlagSet bpy_bm_htype_all_flags[]
Initial value:
 {
    {BM_VERT, "VERT"},
    {BM_LOOP, "EDGE"},
    {BM_FACE, "FACE"},
    {BM_LOOP, "LOOP"},
    {0, NULL}
}
Definition at line 71 of file bmesh_py_types.c.
PyC_FlagSet bpy_bm_htype_vert_edge_face_flags[]
Initial value:
 {
    {BM_VERT, "VERT"},
    {BM_EDGE, "EDGE"},
    {BM_FACE, "FACE"},
    {0, NULL}
}
Definition at line 64 of file bmesh_py_types.c.
PyC_FlagSet bpy_bm_scene_vert_edge_face_flags[]
Initial value:
 {
    {1, "VERT"},
    {2, "EDGE"},
    {4, "FACE"},
    {0, NULL}
}
Definition at line 57 of file bmesh_py_types.c.
struct PyModuleDef BPy_BM_types_module_def [static]
Initial value:
 {
    PyModuleDef_HEAD_INIT,
    "bmesh.types",
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
}
Definition at line 2858 of file bmesh_py_types.c.
PyGetSetDef bpy_bmedge_getseters[] [static]
Initial value:
 {
    {(char *)"select", (getter)bpy_bm_elem_hflag_get, (setter)bpy_bm_elem_hflag_set, (char *)bpy_bm_elem_select_doc, (void *)BM_ELEM_SELECT},
    {(char *)"hide",   (getter)bpy_bm_elem_hflag_get, (setter)bpy_bm_elem_hflag_set, (char *)bpy_bm_elem_hide_doc,   (void *)BM_ELEM_SELECT},
    {(char *)"tag",    (getter)bpy_bm_elem_hflag_get, (setter)bpy_bm_elem_hflag_set, (char *)bpy_bm_elem_tag_doc,    (void *)BM_ELEM_TAG},
    {(char *)"index",  (getter)bpy_bm_elem_index_get, (setter)bpy_bm_elem_index_set, (char *)bpy_bm_elem_index_doc,  NULL},
    {(char *)"smooth", (getter)bpy_bm_elem_hflag_get, (setter)bpy_bm_elem_hflag_set, (char *)bpy_bm_elem_smooth_doc, (void *)BM_ELEM_SMOOTH},
    {(char *)"seam",   (getter)bpy_bm_elem_hflag_get, (setter)bpy_bm_elem_hflag_set, (char *)bpy_bm_elem_seam_doc, (void *)BM_ELEM_SEAM},
    {(char *)"verts", (getter)bpy_bmelemseq_elem_get, (setter)NULL, (char *)bpy_bmedge_verts_doc, (void *)BM_VERTS_OF_EDGE},
    {(char *)"link_faces", (getter)bpy_bmelemseq_elem_get, (setter)NULL, (char *)bpy_bmedge_link_faces_doc, (void *)BM_FACES_OF_EDGE},
    {(char *)"link_loops", (getter)bpy_bmelemseq_elem_get, (setter)NULL, (char *)bpy_bmedge_link_loops_doc, (void *)BM_LOOPS_OF_EDGE},
    {(char *)"is_manifold",  (getter)bpy_bmedge_is_manifold_get,  (setter)NULL, (char *)bpy_bmedge_is_manifold_doc, NULL},
    {(char *)"is_wire",      (getter)bpy_bmedge_is_wire_get,      (setter)NULL, (char *)bpy_bmedge_is_wire_doc, NULL},
    {(char *)"is_boundary",   (getter)bpy_bmedge_is_boundary_get,   (setter)NULL, (char *)bpy_bmedge_is_boundary_doc, NULL},
    {(char *)"is_valid",     (getter)bpy_bm_is_valid_get,         (setter)NULL, (char *)bpy_bm_is_valid_doc, NULL},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 597 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
struct PyMethodDef bpy_bmedge_methods[] [static]
Initial value:
 {
    {"select_set", (PyCFunction)bpy_bm_elem_select_set, METH_O, bpy_bm_elem_select_set_doc},
    {"hide_set", (PyCFunction)bpy_bm_elem_hide_set, METH_O, bpy_bm_elem_hide_set_doc},
    {"copy_from", (PyCFunction)bpy_bm_elem_copy_from, METH_O, bpy_bm_elem_copy_from_doc},
    {"other_vert", (PyCFunction)bpy_bmedge_other_vert, METH_O, bpy_bmedge_other_vert_doc},
    {"calc_length",     (PyCFunction)bpy_bmedge_calc_length,     METH_NOARGS,  bpy_bmedge_calc_length_doc},
    {"calc_face_angle", (PyCFunction)bpy_bmedge_calc_face_angle, METH_NOARGS,  bpy_bmedge_calc_face_angle_doc},
    {"calc_tangent",    (PyCFunction)bpy_bmedge_calc_tangent,    METH_VARARGS, bpy_bmedge_calc_tangent_doc},
    {"normal_update",  (PyCFunction)bpy_bmedge_normal_update,  METH_NOARGS,  bpy_bmedge_normal_update_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 2121 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
PyTypeObject BPy_BMEdge_Type = {{{0}}}
Definition at line 2685 of file bmesh_py_types.c.
Referenced by bpy_bm_itype_as_pytype(), bpy_bm_utils_edge_rotate(), bpy_bm_utils_edge_split(), bpy_bm_utils_face_split(), bpy_bm_utils_vert_collapse_edge(), bpy_bm_utils_vert_collapse_faces(), and bpy_bmedgeseq_new().
PyGetSetDef bpy_bmedgeseq_getseters[] [static]
Initial value:
 {
    {(char *)"layers",    (getter)bpy_bmelemseq_layers_get, (setter)NULL, (char *)bpy_bmelemseq_layers_doc, (void *)BM_EDGE},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 673 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
struct PyMethodDef bpy_bmedgeseq_methods[] [static]
Initial value:
 {
    {"new",     (PyCFunction)bpy_bmedgeseq_new,         METH_VARARGS, bpy_bmedgeseq_new_doc},
    {"remove",  (PyCFunction)bpy_bmedgeseq_remove,      METH_O,       bpy_bmedgeseq_remove_doc},
    {"get",     (PyCFunction)bpy_bmedgeseq_get__method, METH_VARARGS, bpy_bmedgeseq_get__method_doc},
    {"index_update", (PyCFunction)bpy_bmelemseq_index_update, METH_NOARGS, bpy_bmelemseq_index_update_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 2181 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
PyTypeObject BPy_BMEdgeSeq_Type = {{{0}}}
Definition at line 2690 of file bmesh_py_types.c.
PyMappingMethods bpy_bmelemseq_as_mapping [static]
Initial value:
 {
    (lenfunc)bpy_bmelemseq_length,
    (binaryfunc)bpy_bmelemseq_subscript,
    (objobjargproc)NULL,
}
Definition at line 2453 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
PySequenceMethods bpy_bmelemseq_as_sequence [static]
Initial value:
 {
    (lenfunc)bpy_bmelemseq_length,
    NULL,
    NULL,
    (ssizeargfunc)bpy_bmelemseq_subscript_int,
    NULL,
    (ssizeobjargproc)NULL,
    NULL,
    (objobjproc)bpy_bmelemseq_contains,
    (binaryfunc) NULL,
    (ssizeargfunc) NULL,
}
Definition at line 2440 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
struct PyMethodDef bpy_bmelemseq_methods[] [static]
Initial value:
 {
    {"index_update", (PyCFunction)bpy_bmelemseq_index_update, METH_NOARGS, bpy_bmelemseq_index_update_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 2166 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
PyTypeObject BPy_BMElemSeq_Type = {{{0}}}
Definition at line 2688 of file bmesh_py_types.c.
PyGetSetDef bpy_bmesh_getseters[] [static]
Initial value:
 {
    {(char *)"verts", (getter)bpy_bmvertseq_get, (setter)NULL, (char *)bpy_bmvertseq_doc, NULL},
    {(char *)"edges", (getter)bpy_bmedgeseq_get, (setter)NULL, (char *)bpy_bmedgeseq_doc, NULL},
    {(char *)"faces", (getter)bpy_bmfaceseq_get, (setter)NULL, (char *)bpy_bmfaceseq_doc, NULL},
    {(char *)"loops", (getter)bpy_bmloopseq_get, (setter)NULL, (char *)bpy_bmloopseq_doc, NULL},
    {(char *)"select_mode", (getter)bpy_bmesh_select_mode_get, (setter)bpy_bmesh_select_mode_set, (char *)bpy_bmesh_select_mode_doc, NULL},
    {(char *)"select_history", (getter)bpy_bmesh_select_history_get, (setter)bpy_bmesh_select_history_set, (char *)bpy_bmesh_select_history_doc, NULL},
    {(char *)"is_wrapped", (getter)bpy_bmesh_is_wrapped_get, (setter)NULL, (char *)bpy_bmesh_is_wrapped_doc, NULL},
    {(char *)"is_valid",   (getter)bpy_bm_is_valid_get,   (setter)NULL, (char *)bpy_bm_is_valid_doc, NULL},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 558 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
struct PyMethodDef bpy_bmesh_methods[] [static]
Initial value:
 {
    {"copy",  (PyCFunction)bpy_bmesh_copy,  METH_NOARGS, bpy_bmesh_copy_doc},
    {"clear", (PyCFunction)bpy_bmesh_clear, METH_NOARGS, bpy_bmesh_clear_doc},
    {"free",  (PyCFunction)bpy_bmesh_free,  METH_NOARGS, bpy_bmesh_free_doc},
    {"from_object", (PyCFunction)bpy_bmesh_from_object, METH_VARARGS | METH_KEYWORDS, bpy_bmesh_from_object_doc},
    {"from_mesh",   (PyCFunction)bpy_bmesh_from_mesh,   METH_VARARGS | METH_KEYWORDS, bpy_bmesh_from_mesh_doc},
    {"to_mesh",     (PyCFunction)bpy_bmesh_to_mesh,     METH_VARARGS,                 bpy_bmesh_to_mesh_doc},
    {"select_flush_mode", (PyCFunction)bpy_bmesh_select_flush_mode, METH_NOARGS, bpy_bmesh_select_flush_mode_doc},
    {"select_flush", (PyCFunction)bpy_bmesh_select_flush, METH_O, bpy_bmesh_select_flush_doc},
    {"normal_update", (PyCFunction)bpy_bmesh_normal_update, METH_VARARGS, bpy_bmesh_normal_update_doc},
    {"transform", (PyCFunction)bpy_bmesh_transform, METH_VARARGS|METH_KEYWORDS, bpy_bmesh_transform_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 2087 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
PyTypeObject BPy_BMesh_Type = {{{0}}}
Definition at line 2683 of file bmesh_py_types.c.
PyGetSetDef bpy_bmface_getseters[] [static]
Initial value:
 {
    {(char *)"select", (getter)bpy_bm_elem_hflag_get, (setter)bpy_bm_elem_hflag_set, (char *)bpy_bm_elem_select_doc, (void *)BM_ELEM_SELECT},
    {(char *)"hide",   (getter)bpy_bm_elem_hflag_get, (setter)bpy_bm_elem_hflag_set, (char *)bpy_bm_elem_hide_doc,   (void *)BM_ELEM_SELECT},
    {(char *)"tag",    (getter)bpy_bm_elem_hflag_get, (setter)bpy_bm_elem_hflag_set, (char *)bpy_bm_elem_tag_doc,    (void *)BM_ELEM_TAG},
    {(char *)"index",  (getter)bpy_bm_elem_index_get, (setter)bpy_bm_elem_index_set, (char *)bpy_bm_elem_index_doc,  NULL},
    {(char *)"smooth", (getter)bpy_bm_elem_hflag_get, (setter)bpy_bm_elem_hflag_set, (char *)bpy_bm_elem_smooth_doc, (void *)BM_ELEM_SMOOTH},
    {(char *)"normal", (getter)bpy_bmface_normal_get, (setter)bpy_bmface_normal_set, (char *)bpy_bmface_normal_doc, NULL},
    {(char *)"material_index",  (getter)bpy_bmface_material_index_get, (setter)bpy_bmface_material_index_set, (char *)bpy_bmface_material_index_doc,  NULL},
    {(char *)"verts", (getter)bpy_bmelemseq_elem_get, (setter)NULL, (char *)bpy_bmface_verts_doc, (void *)BM_VERTS_OF_FACE},
    {(char *)"edges", (getter)bpy_bmelemseq_elem_get, (setter)NULL, (char *)bpy_bmface_edges_doc, (void *)BM_EDGES_OF_FACE},
    {(char *)"loops", (getter)bpy_bmelemseq_elem_get, (setter)NULL, (char *)bpy_bmface_loops_doc, (void *)BM_LOOPS_OF_FACE},
    {(char *)"is_valid",   (getter)bpy_bm_is_valid_get, (setter)NULL, (char *)bpy_bm_is_valid_doc, NULL},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 622 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
struct PyMethodDef bpy_bmface_methods[] [static]
Initial value:
 {
    {"select_set", (PyCFunction)bpy_bm_elem_select_set, METH_O, bpy_bm_elem_select_set_doc},
    {"hide_set", (PyCFunction)bpy_bm_elem_hide_set, METH_O, bpy_bm_elem_hide_set_doc},
    {"copy_from", (PyCFunction)bpy_bm_elem_copy_from, METH_O, bpy_bm_elem_copy_from_doc},
    {"copy_from_face_interp", (PyCFunction)bpy_bmface_copy_from_face_interp, METH_O, bpy_bmface_copy_from_face_interp_doc},
    {"copy", (PyCFunction)bpy_bmface_copy, METH_VARARGS|METH_KEYWORDS, bpy_bmface_copy_doc},
    {"calc_area",          (PyCFunction)bpy_bmface_calc_area,          METH_NOARGS, bpy_bmface_calc_area_doc},
    {"calc_perimeter",     (PyCFunction)bpy_bmface_calc_perimeter,     METH_NOARGS, bpy_bmface_calc_perimeter_doc},
    {"calc_center_median", (PyCFunction)bpy_bmface_calc_center_mean,   METH_NOARGS, bpy_bmface_calc_center_mean_doc},
    {"calc_center_bounds", (PyCFunction)bpy_bmface_calc_center_bounds, METH_NOARGS, bpy_bmface_calc_center_bounds_doc},
    {"normal_update",  (PyCFunction)bpy_bmface_normal_update,  METH_NOARGS,  bpy_bmface_normal_update_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 2137 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
PyTypeObject BPy_BMFace_Type = {{{0}}}
Definition at line 2686 of file bmesh_py_types.c.
Referenced by bpy_bm_itype_as_pytype(), bpy_bm_utils_face_split(), bpy_bm_utils_face_vert_separate(), bpy_bmface_copy_from_face_interp(), bpy_bmfaceseq_new(), bpy_bmloop_copy_from_face_interp(), and bpy_bmvert_copy_from_face_interp().
PyGetSetDef bpy_bmfaceseq_getseters[] [static]
Initial value:
 {
    {(char *)"layers",    (getter)bpy_bmelemseq_layers_get, (setter)NULL, (char *)bpy_bmelemseq_layers_doc, (void *)BM_FACE},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 677 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
struct PyMethodDef bpy_bmfaceseq_methods[] [static]
Initial value:
 {
    {"new",     (PyCFunction)bpy_bmfaceseq_new,         METH_VARARGS, bpy_bmfaceseq_new_doc},
    {"remove",  (PyCFunction)bpy_bmfaceseq_remove,      METH_O,       bpy_bmfaceseq_remove_doc},
    {"get",     (PyCFunction)bpy_bmfaceseq_get__method, METH_VARARGS, bpy_bmfaceseq_get__method_doc},
    {"index_update", (PyCFunction)bpy_bmelemseq_index_update, METH_NOARGS, bpy_bmelemseq_index_update_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 2192 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
PyTypeObject BPy_BMFaceSeq_Type = {{{0}}}
Definition at line 2691 of file bmesh_py_types.c.
PyTypeObject BPy_BMIter_Type = {{{0}}}
Definition at line 2693 of file bmesh_py_types.c.
PyGetSetDef bpy_bmloop_getseters[] [static]
Initial value:
 {
    {(char *)"tag",    (getter)bpy_bm_elem_hflag_get, (setter)bpy_bm_elem_hflag_set, (char *)bpy_bm_elem_tag_doc,    (void *)BM_ELEM_TAG},
    {(char *)"index",  (getter)bpy_bm_elem_index_get, (setter)bpy_bm_elem_index_set, (char *)bpy_bm_elem_index_doc,  NULL},
    {(char *)"vert", (getter)bpy_bmloop_vert_get, (setter)NULL, (char *)bpy_bmloop_vert_doc, NULL},
    {(char *)"edge", (getter)bpy_bmloop_edge_get, (setter)NULL, (char *)bpy_bmloop_edge_doc, NULL},
    {(char *)"face", (getter)bpy_bmloop_face_get, (setter)NULL, (char *)bpy_bmloop_face_doc, NULL},
    {(char *)"link_loops", (getter)bpy_bmelemseq_elem_get, (setter)NULL, (char *)bpy_bmloops_link_loops_doc, (void *)BM_LOOPS_OF_LOOP},
    {(char *)"link_loop_next", (getter)bpy_bmloop_link_loop_next_get, (setter)NULL, (char *)bpy_bmloop_link_loop_next_doc, NULL},
    {(char *)"link_loop_prev", (getter)bpy_bmloop_link_loop_prev_get, (setter)NULL, (char *)bpy_bmloop_link_loop_prev_doc, NULL},
    {(char *)"is_valid",   (getter)bpy_bm_is_valid_get, (setter)NULL, (char *)bpy_bm_is_valid_doc, NULL},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 646 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
struct PyMethodDef bpy_bmloop_methods[] [static]
Initial value:
 {
    {"copy_from", (PyCFunction)bpy_bm_elem_copy_from, METH_O, bpy_bm_elem_copy_from_doc},
    {"copy_from_face_interp", (PyCFunction)bpy_bmloop_copy_from_face_interp, METH_O, bpy_bmloop_copy_from_face_interp_doc},
    {"calc_angle",   (PyCFunction)bpy_bmloop_calc_angle,   METH_NOARGS, bpy_bmloop_calc_angle_doc},
    {"calc_normal",  (PyCFunction)bpy_bmloop_calc_normal,  METH_NOARGS, bpy_bmloop_calc_normal_doc},
    {"calc_tangent", (PyCFunction)bpy_bmloop_calc_tangent, METH_NOARGS, bpy_bmloop_calc_tangent_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 2156 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
PyTypeObject BPy_BMLoop_Type = {{{0}}}
Definition at line 2687 of file bmesh_py_types.c.
Referenced by bpy_bm_itype_as_pytype(), and bpy_bmedge_calc_tangent().
PyGetSetDef bpy_bmloopseq_getseters[] [static]
Initial value:
 {
    {(char *)"layers",    (getter)bpy_bmelemseq_layers_get, (setter)NULL, (char *)bpy_bmelemseq_layers_doc, (void *)BM_LOOP},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 681 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
struct PyMethodDef bpy_bmloopseq_methods[] [static]
Initial value:
 {
    {NULL, NULL, 0, NULL}
}
Definition at line 2203 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
PyTypeObject BPy_BMLoopSeq_Type = {{{0}}}
Definition at line 2692 of file bmesh_py_types.c.
PyGetSetDef bpy_bmvert_getseters[] [static]
Initial value:
 {
    {(char *)"select", (getter)bpy_bm_elem_hflag_get, (setter)bpy_bm_elem_hflag_set, (char *)bpy_bm_elem_select_doc, (void *)BM_ELEM_SELECT},
    {(char *)"hide",   (getter)bpy_bm_elem_hflag_get, (setter)bpy_bm_elem_hflag_set, (char *)bpy_bm_elem_hide_doc,   (void *)BM_ELEM_SELECT},
    {(char *)"tag",    (getter)bpy_bm_elem_hflag_get, (setter)bpy_bm_elem_hflag_set, (char *)bpy_bm_elem_tag_doc,    (void *)BM_ELEM_TAG},
    {(char *)"index",  (getter)bpy_bm_elem_index_get, (setter)bpy_bm_elem_index_set, (char *)bpy_bm_elem_index_doc,  NULL},
    {(char *)"co",     (getter)bpy_bmvert_co_get,     (setter)bpy_bmvert_co_set,     (char *)bpy_bmvert_co_doc, NULL},
    {(char *)"normal", (getter)bpy_bmvert_normal_get, (setter)bpy_bmvert_normal_set, (char *)bpy_bmvert_normal_doc, NULL},
    {(char *)"link_edges", (getter)bpy_bmelemseq_elem_get, (setter)NULL, (char *)bpy_bmvert_link_edges_doc, (void *)BM_EDGES_OF_VERT},
    {(char *)"link_faces", (getter)bpy_bmelemseq_elem_get, (setter)NULL, (char *)bpy_bmvert_link_faces_doc, (void *)BM_FACES_OF_VERT},
    {(char *)"link_loops", (getter)bpy_bmelemseq_elem_get, (setter)NULL, (char *)bpy_bmvert_link_loops_doc, (void *)BM_LOOPS_OF_VERT},
    {(char *)"is_manifold",  (getter)bpy_bmvert_is_manifold_get,  (setter)NULL, (char *)bpy_bmvert_is_manifold_doc, NULL},
    {(char *)"is_wire",      (getter)bpy_bmvert_is_wire_get,      (setter)NULL, (char *)bpy_bmvert_is_wire_doc, NULL},
    {(char *)"is_valid",     (getter)bpy_bm_is_valid_get,         (setter)NULL, (char *)bpy_bm_is_valid_doc, NULL},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 574 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
struct PyMethodDef bpy_bmvert_methods[] [static]
Initial value:
 {
    {"select_set", (PyCFunction)bpy_bm_elem_select_set, METH_O, bpy_bm_elem_select_set_doc},
    {"hide_set", (PyCFunction)bpy_bm_elem_hide_set, METH_O, bpy_bm_elem_hide_set_doc},
    {"copy_from", (PyCFunction)bpy_bm_elem_copy_from, METH_O, bpy_bm_elem_copy_from_doc},
    {"copy_from_face_interp", (PyCFunction)bpy_bmvert_copy_from_face_interp, METH_VARARGS, bpy_bmvert_copy_from_face_interp_doc},
    {"copy_from_vert_interp", (PyCFunction)bpy_bmvert_copy_from_vert_interp, METH_VARARGS, bpy_bmvert_copy_from_vert_interp_doc},
    {"calc_vert_angle",   (PyCFunction)bpy_bmvert_calc_edge_angle,   METH_NOARGS, bpy_bmvert_calc_edge_angle_doc},
    {"calc_shell_factor", (PyCFunction)bpy_bmvert_calc_shell_factor, METH_NOARGS, bpy_bmvert_calc_shell_factor_doc},
    {"normal_update",  (PyCFunction)bpy_bmvert_normal_update,  METH_NOARGS,  bpy_bmvert_normal_update_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 2106 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
PyTypeObject BPy_BMVert_Type = {{{0}}}
Definition at line 2684 of file bmesh_py_types.c.
Referenced by bpy_bm_itype_as_pytype(), bpy_bm_utils_edge_split(), bpy_bm_utils_face_split(), bpy_bm_utils_face_vert_separate(), bpy_bm_utils_vert_collapse_edge(), bpy_bm_utils_vert_collapse_faces(), bpy_bm_utils_vert_dissolve(), bpy_bm_utils_vert_separate(), and bpy_bmvertseq_new().
PyGetSetDef bpy_bmvertseq_getseters[] [static]
Initial value:
 {
    {(char *)"layers",    (getter)bpy_bmelemseq_layers_get, (setter)NULL, (char *)bpy_bmelemseq_layers_doc, (void *)BM_VERT},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 669 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
struct PyMethodDef bpy_bmvertseq_methods[] [static]
Initial value:
 {
    {"new",     (PyCFunction)bpy_bmvertseq_new,         METH_VARARGS, bpy_bmvertseq_new_doc},
    {"remove",  (PyCFunction)bpy_bmvertseq_remove,      METH_O,       bpy_bmvertseq_remove_doc},
    {"index_update", (PyCFunction)bpy_bmelemseq_index_update, METH_NOARGS, bpy_bmelemseq_index_update_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 2172 of file bmesh_py_types.c.
Referenced by BPy_BM_init_types().
PyTypeObject BPy_BMVertSeq_Type = {{{0}}}
Definition at line 2689 of file bmesh_py_types.c.