Blender: svm_checker.h File Reference
svm_checker.h File Reference
Functions
CCL_NAMESPACE_BEGIN
__device_noinline float svm_checker (float3 p, float scale)
__device void svm_node_tex_checker (KernelGlobals *kg, ShaderData *sd, float *stack, uint4 node, int *offset)
Function Documentation
CCL_NAMESPACE_BEGIN __device_noinline float svm_checker (float3 p, float scale)
Definition at line 23 of file svm_checker.h.
References fabsf, floorf, float3::x, float3::y, and float3::z.
Referenced by svm_node_tex_checker().
__device void svm_node_tex_checker (KernelGlobals * kg, ShaderData * sd, float * stack, uint4 node, int * offset)
Definition at line 39 of file svm_checker.h.
References co, decode_node_uchar4(), NULL, stack_load_float3(), stack_load_float_default(), stack_store_float(), stack_store_float3(), stack_valid(), svm_checker(), uint4::w, uint4::y, and uint4::z.
Referenced by svm_eval_nodes().