Blender: CocoaWindowDelegate Class Reference
CocoaWindowDelegate Class Reference
Public Member Functions
(void) - setSystemAndWindowCocoa:windowCocoa:
(void) - windowWillClose:
(void) - windowDidBecomeKey:
(void) - windowDidResignKey:
(void) - windowDidExpose:
(void) - windowDidResize:
(void) - windowDidMove:
(void) - windowWillMove:
Protected Attributes
GHOST_SystemCocoa * systemCocoa
GHOST_WindowCocoa * associatedWindow
Detailed Description
Definition at line 60 of file GHOST_WindowCocoa.mm.
Member Function Documentation
- (void) setSystemAndWindowCocoa: (GHOST_SystemCocoa *) sysCocoa windowCocoa: (GHOST_WindowCocoa *) winCocoa
- (void) windowDidBecomeKey: (NSNotification *) notification
Definition at line 91 of file GHOST_WindowCocoa.mm.
References associatedWindow, GHOST_kEventWindowActivate, GHOST_SystemCocoa::handleWindowEvent(), and systemCocoa.
- (void) windowDidExpose: (NSNotification *) notification
Definition at line 101 of file GHOST_WindowCocoa.mm.
References associatedWindow, GHOST_kEventWindowUpdate, GHOST_SystemCocoa::handleWindowEvent(), and systemCocoa.
- (void) windowDidMove: (NSNotification *) notification
Definition at line 106 of file GHOST_WindowCocoa.mm.
References associatedWindow, GHOST_kEventWindowMove, GHOST_SystemCocoa::handleWindowEvent(), and systemCocoa.
- (void) windowDidResignKey: (NSNotification *) notification
Definition at line 96 of file GHOST_WindowCocoa.mm.
References associatedWindow, GHOST_kEventWindowDeactivate, GHOST_SystemCocoa::handleWindowEvent(), and systemCocoa.
- (void) windowDidResize: (NSNotification *) notification
Definition at line 116 of file GHOST_WindowCocoa.mm.
References associatedWindow, GHOST_kEventWindowSize, GHOST_SystemCocoa::handleWindowEvent(), and systemCocoa.
- (void) windowWillClose: (NSNotification *) notification
Definition at line 86 of file GHOST_WindowCocoa.mm.
References associatedWindow, GHOST_kEventWindowClose, GHOST_SystemCocoa::handleWindowEvent(), and systemCocoa.
- (void) windowWillMove: (NSNotification *) notification
Definition at line 111 of file GHOST_WindowCocoa.mm.
References associatedWindow, GHOST_kEventWindowMove, GHOST_SystemCocoa::handleWindowEvent(), and systemCocoa.
Member Data Documentation
- (GHOST_WindowCocoa*) associatedWindow [protected]
Definition at line 66 of file GHOST_WindowCocoa.mm.
Referenced by windowDidBecomeKey:, windowDidExpose:, windowDidMove:, windowDidResignKey:, windowDidResize:, windowWillClose:, and windowWillMove:.
- (GHOST_SystemCocoa*) systemCocoa [protected]
Definition at line 65 of file GHOST_WindowCocoa.mm.
Referenced by windowDidBecomeKey:, windowDidExpose:, windowDidMove:, windowDidResignKey:, windowDidResize:, windowWillClose:, and windowWillMove:.
The documentation for this class was generated from the following file:
GHOST_WindowCocoa.mm