Blender: undo.c File Reference
undo.c File Reference
editor utilities
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "DNA_mesh_types.h"
#include "DNA_object_types.h"
#include "BLI_blenlib.h"
#include "BLI_dynstr.h"
#include "BLI_utildefines.h"
#include "BLF_translation.h"
#include "BKE_blender.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_screen.h"
#include "ED_armature.h"
#include "ED_particle.h"
#include "ED_curve.h"
#include "ED_gpencil.h"
#include "ED_mball.h"
#include "ED_mesh.h"
#include "ED_object.h"
#include "ED_screen.h"
#include "ED_sculpt.h"
#include "ED_util.h"
#include "ED_text.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "util_intern.h"
Defines
#define MAXUNDONAME 64
#define UNDOSYSTEM_GLOBAL 1
#define UNDOSYSTEM_EDITMODE 2
#define UNDOSYSTEM_PARTICLE 3
Functions
void ED_undo_push (bContext *C, const char *str)
static int ed_undo_step (bContext *C, int step, const char *undoname)
void ED_undo_pop (bContext *C)
void ED_undo_redo (bContext *C)
void ED_undo_push_op (bContext *C, wmOperator *op)
void ED_undo_pop_op (bContext *C, wmOperator *op)
int ED_undo_valid (const bContext *C, const char *undoname)
static int ed_undo_exec (bContext *C, wmOperator *UNUSED(op))
static int ed_undo_push_exec (bContext *C, wmOperator *op)
static int ed_redo_exec (bContext *C, wmOperator *UNUSED(op))
void ED_OT_undo (wmOperatorType *ot)
void ED_OT_undo_push (wmOperatorType *ot)
void ED_OT_redo (wmOperatorType *ot)
int ED_undo_operator_repeat (bContext *C, struct wmOperator *op)
void ED_undo_operator_repeat_cb (bContext *C, void *arg_op, void *UNUSED(arg_unused))
void ED_undo_operator_repeat_cb_evt (bContext *C, void *arg_op, int UNUSED(arg_event))
static int get_undo_system (bContext *C)
static EnumPropertyItem * rna_undo_itemf (bContext *C, int undosys, int *totitem)
static int undo_history_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int undo_history_exec (bContext *C, wmOperator *op)
void ED_OT_undo_history (wmOperatorType *ot)
Detailed Description
Definition in file undo.c.
Define Documentation
#define MAXUNDONAME 64
Definition at line 77 of file undo.c.
Referenced by ED_OT_undo_push(), and ed_undo_push_exec().
#define UNDOSYSTEM_EDITMODE 2
Definition at line 417 of file undo.c.
Referenced by get_undo_system(), rna_undo_itemf(), and undo_history_exec().
#define UNDOSYSTEM_GLOBAL 1
Definition at line 416 of file undo.c.
Referenced by get_undo_system().
#define UNDOSYSTEM_PARTICLE 3
Definition at line 418 of file undo.c.
Referenced by get_undo_system(), rna_undo_itemf(), and undo_history_exec().
Function Documentation
void ED_OT_redo (wmOperatorType * ot)
Definition at line 327 of file undo.c.
References wmOperatorType::description, ED_operator_screenactive(), ed_redo_exec(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by ED_operatortypes_screen().
void ED_OT_undo (wmOperatorType * ot)
Definition at line 300 of file undo.c.
References wmOperatorType::description, ED_operator_screenactive(), ed_undo_exec(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by ED_operatortypes_screen().
void ED_OT_undo_history (wmOperatorType * ot)
Definition at line 538 of file undo.c.
References wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, undo_history_exec(), and undo_history_invoke().
Referenced by ED_operatortypes_screen().
void ED_OT_undo_push (wmOperatorType * ot)
Definition at line 312 of file undo.c.
References wmOperatorType::description, ed_undo_push_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAXUNDONAME, wmOperatorType::name, OPTYPE_INTERNAL, RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_screen().
static int ed_redo_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 292 of file undo.c.
References ed_undo_step(), and NULL.
Referenced by ED_OT_redo().
static int ed_undo_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 277 of file undo.c.
References CTX_wm_manager(), ed_undo_step(), NULL, and WM_operator_stack_clear().
Referenced by ED_OT_undo().
int ED_undo_operator_repeat (bContext * C, struct wmOperator * op)
Definition at line 341 of file undo.c.
References BKE_area_find_region_type(), wmOperatorType::check, CTX_data_scene(), CTX_wm_area(), CTX_wm_manager(), CTX_wm_region(), CTX_wm_region_set(), ED_undo_pop_op(), ED_undo_redo(), G, G_DEBUG, wmOperatorType::name, OPERATOR_FINISHED, RGN_TYPE_WINDOW, wmOperator::type, WM_jobs_test(), WM_operator_poll(), WM_operator_repeat(), and WM_operator_repeat_check().
Referenced by ED_undo_operator_repeat_cb(), ED_undo_operator_repeat_cb_evt(), and file_browse_exec().
void ED_undo_operator_repeat_cb (bContext * C, void * arg_op, void * UNUSEDarg_unused)
Definition at line 403 of file undo.c.
References ED_undo_operator_repeat().
void ED_undo_operator_repeat_cb_evt (bContext * C, void * arg_op, int UNUSEDarg_event)
Definition at line 408 of file undo.c.
References ED_undo_operator_repeat().
void ED_undo_pop (bContext * C)
Definition at line 210 of file undo.c.
References ed_undo_step(), and NULL.
Referenced by redraw_timer_exec().
void ED_undo_pop_op (bContext * C, wmOperator * op)
Definition at line 225 of file undo.c.
References ed_undo_step(), wmOperatorType::name, and wmOperator::type.
Referenced by ED_undo_operator_repeat().
void ED_undo_push (bContext * C, const char * str)
Definition at line 81 of file undo.c.
References BKE_write_undo(), CTX_data_active_object(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_manager(), ELEM, wmWindowManager::file_saved, G, G_DEBUG, Object::mode, NC_WM, ND_DATACHANGED, NULL, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_PARTICLE_EDIT, OB_SURF, PE_undo_push(), Object::type, undo_push_armature(), undo_push_curve(), undo_push_font(), undo_push_lattice(), undo_push_mball(), undo_push_mesh(), USER_GLOBALUNDO, and WM_event_add_notifier().
Referenced by adjustGraphs(), BIF_retargetArmature(), colorband_add_cb(), colorband_del_cb(), colorband_flip_cb(), curvesurf_prim_add(), delete_fmodifier_cb(), do_logic_buts(), do_view3d_header_buttons(), ED_object_enter_editmode(), ED_object_exit_editmode(), ed_undo_push_exec(), ED_undo_push_op(), modifiers_convertToReal(), old_sca_move_actuator(), old_sca_move_controller(), old_sca_move_sensor(), outliner_action_set_exec(), outliner_animdata_operation_exec(), outliner_data_operation_exec(), outliner_group_operation_exec(), outliner_id_operation_exec(), outliner_item_activate(), outliner_object_operation_exec(), ui_apply_but_funcs_after(), and ui_node_link().
static int ed_undo_push_exec (bContext * C, wmOperator * op) [static]
Definition at line 284 of file undo.c.
References ED_undo_push(), MAXUNDONAME, OPERATOR_FINISHED, wmOperator::ptr, RNA_string_get(), and str.
Referenced by ED_OT_undo_push().
void ED_undo_push_op (bContext * C, wmOperator * op)
Definition at line 219 of file undo.c.
References ED_undo_push(), wmOperatorType::name, and wmOperator::type.
Referenced by wm_handler_fileselect_call(), wm_operator_finished(), and WM_operator_props_popup().
void ED_undo_redo (bContext * C)
Definition at line 214 of file undo.c.
References ed_undo_step(), and NULL.
Referenced by ED_undo_operator_repeat(), and redraw_timer_exec().
static int ed_undo_step (bContext * C, int step, const char * undoname) [static]
Definition at line 124 of file undo.c.
References BKE_undo_name(), BKE_undo_step(), CTX_data_active_object(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_area(), CTX_wm_manager(), ED_gpencil_session_active(), ED_text_undo_step(), ED_undo_gpencil_step(), ED_undo_paint_step(), ELEM7, ListBase::first, SpaceImage::flag, if(), Object::mode, NC_GEOM, NC_SCENE, NC_WINDOW, ND_DATA, ND_LAYER_CONTENT, NULL, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_PARTICLE_EDIT, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_SURF, OPERATOR_CANCELLED, OPERATOR_FINISHED, PE_redo(), PE_undo(), SI_DRAWTOOL, SPACE_IMAGE, SPACE_TEXT, ScrArea::spacedata, ScrArea::spacetype, Object::type, undo_editmode_name(), undo_editmode_step(), UNDO_PAINT_IMAGE, UNDO_PAINT_MESH, USER_GLOBALUNDO, WM_event_add_notifier(), and WM_jobs_test().
Referenced by ed_redo_exec(), ed_undo_exec(), ED_undo_pop(), ED_undo_pop_op(), and ED_undo_redo().
int ED_undo_valid (const bContext * C, const char * undoname)
Definition at line 232 of file undo.c.
References BKE_undo_valid(), CTX_data_active_object(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_area(), ED_undo_paint_valid(), ELEM7, ListBase::first, SpaceImage::flag, if(), Object::mode, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_PARTICLE_EDIT, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_SURF, PE_undo_valid(), SI_DRAWTOOL, SPACE_IMAGE, SPACE_TEXT, ScrArea::spacedata, ScrArea::spacetype, Object::type, undo_editmode_valid(), UNDO_PAINT_IMAGE, UNDO_PAINT_MESH, and USER_GLOBALUNDO.
static int get_undo_system (bContext * C) [static]
Definition at line 420 of file undo.c.
References CTX_data_active_object(), CTX_data_edit_object(), ELEM7, Object::mode, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_PARTICLE_EDIT, OB_SURF, Scene::obedit, Object::type, UNDOSYSTEM_EDITMODE, UNDOSYSTEM_GLOBAL, UNDOSYSTEM_PARTICLE, and USER_GLOBALUNDO.
Referenced by undo_history_exec(), and undo_history_invoke().
static EnumPropertyItem* rna_undo_itemf (bContext * C, int undosys, int * totitem) [static]
Definition at line 442 of file undo.c.
References BKE_undo_get_name(), CTX_data_scene(), i, EnumPropertyItem::icon, EnumPropertyItem::identifier, IFACE_, EnumPropertyItem::name, NULL, PE_undo_get_name(), RNA_enum_item_add(), RNA_enum_item_end(), TRUE, undo_editmode_get_name(), UNDOSYSTEM_EDITMODE, UNDOSYSTEM_PARTICLE, and EnumPropertyItem::value.
Referenced by undo_history_invoke().
static int undo_history_exec (bContext * C, wmOperator * op) [static]
Definition at line 514 of file undo.c.
References BKE_undo_number(), CTX_data_scene(), get_undo_system(), NC_GEOM, NC_SCENE, NC_WINDOW, ND_DATA, ND_LAYER_CONTENT, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, PE_undo_number(), wmOperator::ptr, RNA_int_get(), RNA_struct_property_is_set(), undo_editmode_number(), UNDOSYSTEM_EDITMODE, UNDOSYSTEM_PARTICLE, and WM_event_add_notifier().
Referenced by ED_OT_undo_history().
static int undo_history_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 481 of file undo.c.
References get_undo_system(), i, wmOperatorType::idname, MEM_freeN(), NULL, OPERATOR_CANCELLED, RNA_struct_ui_name(), rna_undo_itemf(), split(), wmOperatorType::srna, wmOperator::type, uiItemIntO(), uiLayoutColumn(), uiLayoutSplit(), uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), and EnumPropertyItem::value.
Referenced by ED_OT_undo_history().