Blender: KX_CameraActuator Class Reference
KX_CameraActuator Class Reference
#include <KX_CameraActuator.h>
Public Member Functions
KX_CameraActuator (SCA_IObject *gameobj, SCA_IObject *ob, float hght, float minhght, float maxhght, short axis, float damping)
~KX_CameraActuator ()
CValue * GetReplica ()
virtual void ProcessReplica ()
virtual bool Update (double curtime, bool frame)
virtual bool UnlinkObject (SCA_IObject *clientobj)
virtual void Relink (CTR_Map< CTR_HashedPtr, void * > *obj_map)
Static Public Attributes
static STR_String X_AXIS_STRING
static STR_String Y_AXIS_STRING
Detailed Description
The camera actuator does a Robbie Muller perspective for you. This is a weird set of rules that positions the camera sort of behind the object, tracking, while avoiding any objects between the 'ideal' position and the actor being tracked.
Definition at line 50 of file KX_CameraActuator.h.
Constructor & Destructor Documentation
KX_CameraActuator::KX_CameraActuator (SCA_IObject * gameobj, SCA_IObject * ob, float hght, float minhght, float maxhght, short axis, float damping)
Set the bool toggle to true to use x lock, false for y lock
Definition at line 50 of file KX_CameraActuator.cpp.
References SCA_IObject::RegisterActuator().
Referenced by GetReplica().
KX_CameraActuator::~KX_CameraActuator ()
Definition at line 71 of file KX_CameraActuator.cpp.
References SCA_IObject::UnregisterActuator().
Member Function Documentation
CValue * KX_CameraActuator::GetReplica (void) [virtual]
Methods Inherited from CValue
Implements CValue.
Definition at line 79 of file KX_CameraActuator.cpp.
References KX_CameraActuator(), and ProcessReplica().
void KX_CameraActuator::ProcessReplica () [virtual]
Makes sure any internal data owned by this class is deep copied.
Reimplemented from SCA_IActuator.
Definition at line 86 of file KX_CameraActuator.cpp.
References SCA_IObject::RegisterActuator().
Referenced by GetReplica().
void KX_CameraActuator::Relink (CTR_Map< CTR_HashedPtr, void * > * obj_map) [virtual]
Methods inherited from SCA_ILogicBrick
Reimplemented from SCA_ILogicBrick.
Definition at line 105 of file KX_CameraActuator.cpp.
References SCA_IObject::RegisterActuator(), and SCA_IObject::UnregisterActuator().
bool KX_CameraActuator::UnlinkObject (SCA_IObject * clientobj) [virtual]
UnlinkObject(...) Certain actuator use gameobject pointers (like TractTo actuator) This function can be called when an object is removed to make sure that the actuator will not use it anymore.
Reimplemented from SCA_IActuator.
Definition at line 93 of file KX_CameraActuator.cpp.
References NULL.
bool KX_CameraActuator::Update (double curtime, bool frame) [virtual]
Methods inherited from SCA_IActuator
Reimplemented from SCA_IActuator.
Definition at line 211 of file KX_CameraActuator.cpp.
References assert, SCA_ILogicBrick::GetParent(), SCA_IActuator::IsNegativeEvent(), Kx_VecUpMat3(), KX_GameObject::NodeGetWorldOrientation(), KX_GameObject::NodeGetWorldPosition(), KX_GameObject::NodeSetLocalOrientation(), KX_GameObject::NodeSetLocalPosition(), OB_NEGX, OB_NEGY, OB_POSX, OB_POSY, and SCA_IActuator::RemoveAllEvents().
Member Data Documentation
STR_String KX_CameraActuator::X_AXIS_STRING [static]
Definition at line 86 of file KX_CameraActuator.h.
STR_String KX_CameraActuator::Y_AXIS_STRING [static]
Definition at line 87 of file KX_CameraActuator.h.
The documentation for this class was generated from the following files:
KX_CameraActuator.h
KX_CameraActuator.cpp