Blender: MOD_subsurf.c File Reference
MOD_subsurf.c File Reference
modifiers
#include <stddef.h>
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "BLI_utildefines.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_scene.h"
#include "BKE_subsurf.h"
#include "MOD_modifiertypes.h"
#include "CCGSubSurf.h"
Functions
static void initData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static void freeData (ModifierData *md)
static int isDisabled (ModifierData *md, int useRenderParams)
static DerivedMesh * applyModifier (ModifierData *md, Object *ob, DerivedMesh *derivedData, int useRenderParams, int isFinalCalc)
static DerivedMesh * applyModifierEM (ModifierData *md, Object *UNUSED(ob), struct BMEditMesh *UNUSED(editData), DerivedMesh *derivedData)
Variables
ModifierTypeInfo modifierType_Subsurf
Detailed Description
Definition in file MOD_subsurf.c.
Function Documentation
static DerivedMesh* applyModifier (ModifierData * md, Object * ob, DerivedMesh * derivedData, int useRenderParams, int isFinalCalc) [static]
Definition at line 92 of file MOD_subsurf.c.
References CDDM_copy(), Object::flag, NULL, OB_MODE_EDIT, DerivedMesh::release, and subsurf_make_derived_from_derived().
static DerivedMesh* applyModifierEM (ModifierData * md, Object * UNUSEDob, struct BMEditMesh * UNUSEDeditData, DerivedMesh * derivedData) [static]
Definition at line 112 of file MOD_subsurf.c.
References NULL, and subsurf_make_derived_from_derived().
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 61 of file MOD_subsurf.c.
References SubsurfModifierData::flags, SubsurfModifierData::levels, SubsurfModifierData::renderLevels, and SubsurfModifierData::subdivType.
static void freeData (ModifierData * md) [static]
Definition at line 72 of file MOD_subsurf.c.
References ccgSubSurf_free(), SubsurfModifierData::emCache, and SubsurfModifierData::mCache.
static void initData (ModifierData * md) [static]
Definition at line 52 of file MOD_subsurf.c.
References eSubsurfModifierFlag_SubsurfUv, SubsurfModifierData::flags, SubsurfModifierData::levels, and SubsurfModifierData::renderLevels.
static int isDisabled (ModifierData * md, int useRenderParams) [static]
Definition at line 84 of file MOD_subsurf.c.
References get_render_subsurf_level(), SubsurfModifierData::levels, Scene::r, SubsurfModifierData::renderLevels, and ModifierData::scene.
Variable Documentation
ModifierTypeInfo modifierType_Subsurf
Initial value:
 {
                  "Subsurf",
            "SubsurfModifierData",
            sizeof(SubsurfModifierData),
                  eModifierTypeType_Constructive,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_SupportsMapping
                            | eModifierTypeFlag_SupportsEditmode
                            | eModifierTypeFlag_EnableInEditmode
                            | eModifierTypeFlag_AcceptsCVs,
              copyData,
           NULL,
        NULL,
         NULL,
      NULL,
         applyModifier,
       applyModifierEM,
              initData,
      NULL,
              freeData,
            isDisabled,
        NULL,
         NULL,
        NULL,
     NULL,
         NULL,
        NULL,
}
Definition at line 126 of file MOD_subsurf.c.