Blender: node_composite_colorSpill.c File Reference
node_composite_colorSpill.c File Reference
cmpnodes
#include "node_composite_util.h"
Defines
#define AVG(a, b) ((a + b) / 2)
Functions
static void do_simple_spillmap_red (bNode *node, float *out, float *in)
static void do_simple_spillmap_red_fac (bNode *node, float *out, float *in, float *fac)
static void do_simple_spillmap_green (bNode *node, float *out, float *in)
static void do_simple_spillmap_green_fac (bNode *node, float *out, float *in, float *fac)
static void do_simple_spillmap_blue (bNode *node, float *out, float *in)
static void do_simple_spillmap_blue_fac (bNode *node, float *out, float *in, float *fac)
static void do_average_spillmap_red (bNode *node, float *out, float *in)
static void do_average_spillmap_red_fac (bNode *node, float *out, float *in, float *fac)
static void do_average_spillmap_green (bNode *node, float *out, float *in)
static void do_average_spillmap_green_fac (bNode *node, float *out, float *in, float *fac)
static void do_average_spillmap_blue (bNode *node, float *out, float *in)
static void do_average_spillmap_blue_fac (bNode *node, float *out, float *in, float *fac)
static void do_apply_spillmap_red (bNode *node, float *out, float *in, float *map)
static void do_apply_spillmap_green (bNode *node, float *out, float *in, float *map)
static void do_apply_spillmap_blue (bNode *node, float *out, float *in, float *map)
static void node_composit_exec_color_spill (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_color_spill (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_color_spill (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_color_spill_in []
static bNodeSocketTemplate cmp_node_color_spill_out []
Detailed Description
Definition in file node_composite_colorSpill.c.
Define Documentation
#define AVG (a, b) ((a + b) / 2)
Definition at line 36 of file node_composite_colorSpill.c.
Referenced by do_average_spillmap_blue(), do_average_spillmap_blue_fac(), do_average_spillmap_green(), do_average_spillmap_green_fac(), do_average_spillmap_red(), and do_average_spillmap_red_fac().
Function Documentation
static void do_apply_spillmap_blue (bNode * node, float * out, float * in, float * map) [static]
Definition at line 172 of file node_composite_colorSpill.c.
References bNode::storage, NodeColorspill::uspillb, NodeColorspill::uspillg, and NodeColorspill::uspillr.
Referenced by node_composit_exec_color_spill().
static void do_apply_spillmap_green (bNode * node, float * out, float * in, float * map) [static]
Definition at line 156 of file node_composite_colorSpill.c.
References bNode::storage, NodeColorspill::uspillb, NodeColorspill::uspillg, and NodeColorspill::uspillr.
Referenced by node_composit_exec_color_spill().
static void do_apply_spillmap_red (bNode * node, float * out, float * in, float * map) [static]
Definition at line 140 of file node_composite_colorSpill.c.
References bNode::storage, NodeColorspill::uspillb, NodeColorspill::uspillg, and NodeColorspill::uspillr.
Referenced by node_composit_exec_color_spill().
static void do_average_spillmap_blue (bNode * node, float * out, float * in) [static]
Definition at line 125 of file node_composite_colorSpill.c.
References AVG, NodeColorspill::limscale, and bNode::storage.
Referenced by node_composit_exec_color_spill().
static void do_average_spillmap_blue_fac (bNode * node, float * out, float * in, float * fac) [static]
Definition at line 132 of file node_composite_colorSpill.c.
References AVG, NodeColorspill::limscale, and bNode::storage.
Referenced by node_composit_exec_color_spill().
static void do_average_spillmap_green (bNode * node, float * out, float * in) [static]
Definition at line 110 of file node_composite_colorSpill.c.
References AVG, NodeColorspill::limscale, and bNode::storage.
Referenced by node_composit_exec_color_spill().
static void do_average_spillmap_green_fac (bNode * node, float * out, float * in, float * fac) [static]
Definition at line 117 of file node_composite_colorSpill.c.
References AVG, NodeColorspill::limscale, and bNode::storage.
Referenced by node_composit_exec_color_spill().
static void do_average_spillmap_red (bNode * node, float * out, float * in) [static]
Definition at line 95 of file node_composite_colorSpill.c.
References AVG, NodeColorspill::limscale, and bNode::storage.
Referenced by node_composit_exec_color_spill().
static void do_average_spillmap_red_fac (bNode * node, float * out, float * in, float * fac) [static]
Definition at line 102 of file node_composite_colorSpill.c.
References AVG, NodeColorspill::limscale, and bNode::storage.
Referenced by node_composit_exec_color_spill().
static void do_simple_spillmap_blue (bNode * node, float * out, float * in) [static]
Definition at line 80 of file node_composite_colorSpill.c.
References NodeColorspill::limchan, NodeColorspill::limscale, and bNode::storage.
Referenced by node_composit_exec_color_spill().
static void do_simple_spillmap_blue_fac (bNode * node, float * out, float * in, float * fac) [static]
Definition at line 87 of file node_composite_colorSpill.c.
References NodeColorspill::limchan, NodeColorspill::limscale, and bNode::storage.
Referenced by node_composit_exec_color_spill().
static void do_simple_spillmap_green (bNode * node, float * out, float * in) [static]
Definition at line 65 of file node_composite_colorSpill.c.
References NodeColorspill::limchan, NodeColorspill::limscale, and bNode::storage.
Referenced by node_composit_exec_color_spill().
static void do_simple_spillmap_green_fac (bNode * node, float * out, float * in, float * fac) [static]
Definition at line 72 of file node_composite_colorSpill.c.
References NodeColorspill::limchan, NodeColorspill::limscale, and bNode::storage.
Referenced by node_composit_exec_color_spill().
static void do_simple_spillmap_red (bNode * node, float * out, float * in) [static]
Definition at line 50 of file node_composite_colorSpill.c.
References NodeColorspill::limchan, NodeColorspill::limscale, and bNode::storage.
Referenced by node_composit_exec_color_spill().
static void do_simple_spillmap_red_fac (bNode * node, float * out, float * in, float * fac) [static]
Definition at line 57 of file node_composite_colorSpill.c.
References NodeColorspill::limchan, NodeColorspill::limscale, and bNode::storage.
Referenced by node_composit_exec_color_spill().
static void node_composit_exec_color_spill (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 188 of file node_composite_colorSpill.c.
References alloc_compbuf(), CB_RGBA, CB_VAL, composit1_pixel_processor(), composit2_pixel_processor(), bNode::custom1, bNode::custom2, bNodeStack::data, data, do_apply_spillmap_blue(), do_apply_spillmap_green(), do_apply_spillmap_red(), do_average_spillmap_blue(), do_average_spillmap_blue_fac(), do_average_spillmap_green(), do_average_spillmap_green_fac(), do_average_spillmap_red(), do_average_spillmap_red_fac(), do_simple_spillmap_blue(), do_simple_spillmap_blue_fac(), do_simple_spillmap_green(), do_simple_spillmap_green_fac(), do_simple_spillmap_red(), do_simple_spillmap_red_fac(), dupalloc_compbuf(), free_compbuf(), NULL, bNode::storage, typecheck_compbuf(), NodeColorspill::unspill, NodeColorspill::uspillb, NodeColorspill::uspillg, NodeColorspill::uspillr, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_color_spill().
static void node_composit_init_color_spill (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 322 of file node_composite_colorSpill.c.
References bNode::custom1, bNode::custom2, NodeColorspill::limchan, NodeColorspill::limscale, MEM_callocN(), bNode::storage, and NodeColorspill::unspill.
Referenced by register_node_type_cmp_color_spill().
void register_node_type_cmp_color_spill (bNodeTreeType * ttype)
Definition at line 333 of file node_composite_colorSpill.c.
References CMP_NODE_COLOR_SPILL, NODE_CLASS_MATTE, node_composit_exec_color_spill(), node_composit_init_color_spill(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_color_spill_in[] [static]
Initial value:
{
    {SOCK_RGBA,1,"Image", 1.0f, 1.0f, 1.0f, 1.0f},
    {SOCK_FLOAT, 1, "Fac",  1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_FACTOR},
    {-1,0,""}
}
Definition at line 39 of file node_composite_colorSpill.c.
bNodeSocketTemplate cmp_node_color_spill_out[] [static]
Initial value:
{
    {SOCK_RGBA,0,"Image"},
    {-1,0,""}
}
Definition at line 45 of file node_composite_colorSpill.c.