Blender: GHOST_SystemCocoa.mm File Reference
GHOST_SystemCocoa.mm File Reference
#import <Cocoa/Cocoa.h>
#include <Carbon/Carbon.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/sysctl.h>
#include "GHOST_SystemCocoa.h"
#include "GHOST_DisplayManagerCocoa.h"
#include "GHOST_EventKey.h"
#include "GHOST_EventButton.h"
#include "GHOST_EventCursor.h"
#include "GHOST_EventWheel.h"
#include "GHOST_EventTrackpad.h"
#include "GHOST_EventDragnDrop.h"
#include "GHOST_EventString.h"
#include "GHOST_TimerManager.h"
#include "GHOST_TimerTask.h"
#include "GHOST_WindowManager.h"
#include "GHOST_WindowCocoa.h"
#include "AssertMacros.h"
Classes
class NSEvent(GestureEvents)
class CocoaAppDelegate
Defines
#define FIRSTFILEBUFLG 512
Enumerations
enum {
kVK_ANSI_A = 0x00, kVK_ANSI_S = 0x01, kVK_ANSI_D = 0x02, kVK_ANSI_F = 0x03,
kVK_ANSI_H = 0x04, kVK_ANSI_G = 0x05, kVK_ANSI_Z = 0x06, kVK_ANSI_X = 0x07,
kVK_ANSI_C = 0x08, kVK_ANSI_V = 0x09, kVK_ANSI_B = 0x0B, kVK_ANSI_Q = 0x0C,
kVK_ANSI_W = 0x0D, kVK_ANSI_E = 0x0E, kVK_ANSI_R = 0x0F, kVK_ANSI_Y = 0x10,
kVK_ANSI_T = 0x11, kVK_ANSI_1 = 0x12, kVK_ANSI_2 = 0x13, kVK_ANSI_3 = 0x14,
kVK_ANSI_4 = 0x15, kVK_ANSI_6 = 0x16, kVK_ANSI_5 = 0x17, kVK_ANSI_Equal = 0x18,
kVK_ANSI_9 = 0x19, kVK_ANSI_7 = 0x1A, kVK_ANSI_Minus = 0x1B, kVK_ANSI_8 = 0x1C,
kVK_ANSI_0 = 0x1D, kVK_ANSI_RightBracket = 0x1E, kVK_ANSI_O = 0x1F, kVK_ANSI_U = 0x20,
kVK_ANSI_LeftBracket = 0x21, kVK_ANSI_I = 0x22, kVK_ANSI_P = 0x23, kVK_ANSI_L = 0x25,
kVK_ANSI_J = 0x26, kVK_ANSI_Quote = 0x27, kVK_ANSI_K = 0x28, kVK_ANSI_Semicolon = 0x29,
kVK_ANSI_Backslash = 0x2A, kVK_ANSI_Comma = 0x2B, kVK_ANSI_Slash = 0x2C, kVK_ANSI_N = 0x2D,
kVK_ANSI_M = 0x2E, kVK_ANSI_Period = 0x2F, kVK_ANSI_Grave = 0x32, kVK_ANSI_KeypadDecimal = 0x41,
kVK_ANSI_KeypadMultiply = 0x43, kVK_ANSI_KeypadPlus = 0x45, kVK_ANSI_KeypadClear = 0x47, kVK_ANSI_KeypadDivide = 0x4B,
kVK_ANSI_KeypadEnter = 0x4C, kVK_ANSI_KeypadMinus = 0x4E, kVK_ANSI_KeypadEquals = 0x51, kVK_ANSI_Keypad0 = 0x52,
kVK_ANSI_Keypad1 = 0x53, kVK_ANSI_Keypad2 = 0x54, kVK_ANSI_Keypad3 = 0x55, kVK_ANSI_Keypad4 = 0x56,
kVK_ANSI_Keypad5 = 0x57, kVK_ANSI_Keypad6 = 0x58, kVK_ANSI_Keypad7 = 0x59, kVK_ANSI_Keypad8 = 0x5B,
kVK_ANSI_Keypad9 = 0x5C
}
enum {
kVK_Return = 0x24, kVK_Tab = 0x30, kVK_Space = 0x31, kVK_Delete = 0x33,
kVK_Escape = 0x35, kVK_Command = 0x37, kVK_Shift = 0x38, kVK_CapsLock = 0x39,
kVK_Option = 0x3A, kVK_Control = 0x3B, kVK_RightShift = 0x3C, kVK_RightOption = 0x3D,
kVK_RightControl = 0x3E, kVK_Function = 0x3F, kVK_F17 = 0x40, kVK_VolumeUp = 0x48,
kVK_VolumeDown = 0x49, kVK_Mute = 0x4A, kVK_F18 = 0x4F, kVK_F19 = 0x50,
kVK_F20 = 0x5A, kVK_F5 = 0x60, kVK_F6 = 0x61, kVK_F7 = 0x62,
kVK_F3 = 0x63, kVK_F8 = 0x64, kVK_F9 = 0x65, kVK_F11 = 0x67,
kVK_F13 = 0x69, kVK_F16 = 0x6A, kVK_F14 = 0x6B, kVK_F10 = 0x6D,
kVK_F12 = 0x6F, kVK_F15 = 0x71, kVK_Help = 0x72, kVK_Home = 0x73,
kVK_PageUp = 0x74, kVK_ForwardDelete = 0x75, kVK_F4 = 0x76, kVK_End = 0x77,
kVK_F2 = 0x78, kVK_PageDown = 0x79, kVK_F1 = 0x7A, kVK_LeftArrow = 0x7B,
kVK_RightArrow = 0x7C, kVK_DownArrow = 0x7D, kVK_UpArrow = 0x7E
}
enum { kVK_ISO_Section = 0x0A }
enum {
kVK_JIS_Yen = 0x5D, kVK_JIS_Underscore = 0x5E, kVK_JIS_KeypadComma = 0x5F, kVK_JIS_Eisu = 0x66,
kVK_JIS_Kana = 0x68
}
enum {
NSEventTypeGesture = 29, NSEventTypeMagnify = 30, NSEventTypeSwipe = 31, NSEventTypeRotate = 18,
NSEventTypeBeginGesture = 19, NSEventTypeEndGesture = 20
}
Functions
static GHOST_TButtonMask convertButton (int button)
static GHOST_TKey convertKey (int rawCode, unichar recvChar, UInt16 keyAction)
int GHOST_HACK_getFirstFile (char buf[FIRSTFILEBUFLG])
Variables
static bool g_hasFirstFile = false
static char g_firstFileBuf [512]
__pad0__
Define Documentation
#define FIRSTFILEBUFLG 512
Definition at line 449 of file GHOST_SystemCocoa.mm.
Enumeration Type Documentation
anonymous enum
Enumerator:
kVK_ANSI_A
kVK_ANSI_S
kVK_ANSI_D
kVK_ANSI_F
kVK_ANSI_H
kVK_ANSI_G
kVK_ANSI_Z
kVK_ANSI_X
kVK_ANSI_C
kVK_ANSI_V
kVK_ANSI_B
kVK_ANSI_Q
kVK_ANSI_W
kVK_ANSI_E
kVK_ANSI_R
kVK_ANSI_Y
kVK_ANSI_T
kVK_ANSI_1
kVK_ANSI_2
kVK_ANSI_3
kVK_ANSI_4
kVK_ANSI_6
kVK_ANSI_5
kVK_ANSI_Equal
kVK_ANSI_9
kVK_ANSI_7
kVK_ANSI_Minus
kVK_ANSI_8
kVK_ANSI_0
kVK_ANSI_RightBracket
kVK_ANSI_O
kVK_ANSI_U
kVK_ANSI_LeftBracket
kVK_ANSI_I
kVK_ANSI_P
kVK_ANSI_L
kVK_ANSI_J
kVK_ANSI_Quote
kVK_ANSI_K
kVK_ANSI_Semicolon
kVK_ANSI_Backslash
kVK_ANSI_Comma
kVK_ANSI_Slash
kVK_ANSI_N
kVK_ANSI_M
kVK_ANSI_Period
kVK_ANSI_Grave
kVK_ANSI_KeypadDecimal
kVK_ANSI_KeypadMultiply
kVK_ANSI_KeypadPlus
kVK_ANSI_KeypadClear
kVK_ANSI_KeypadDivide
kVK_ANSI_KeypadEnter
kVK_ANSI_KeypadMinus
kVK_ANSI_KeypadEquals
kVK_ANSI_Keypad0
kVK_ANSI_Keypad1
kVK_ANSI_Keypad2
kVK_ANSI_Keypad3
kVK_ANSI_Keypad4
kVK_ANSI_Keypad5
kVK_ANSI_Keypad6
kVK_ANSI_Keypad7
kVK_ANSI_Keypad8
kVK_ANSI_Keypad9
Definition at line 76 of file GHOST_SystemCocoa.mm.
anonymous enum
Enumerator:
kVK_Return
kVK_Tab
kVK_Space
kVK_Delete
kVK_Escape
kVK_Command
kVK_Shift
kVK_CapsLock
kVK_Option
kVK_Control
kVK_RightShift
kVK_RightOption
kVK_RightControl
kVK_Function
kVK_F17
kVK_VolumeUp
kVK_VolumeDown
kVK_Mute
kVK_F18
kVK_F19
kVK_F20
kVK_F5
kVK_F6
kVK_F7
kVK_F3
kVK_F8
kVK_F9
kVK_F11
kVK_F13
kVK_F16
kVK_F14
kVK_F10
kVK_F12
kVK_F15
kVK_Help
kVK_Home
kVK_PageUp
kVK_ForwardDelete
kVK_F4
kVK_End
kVK_F2
kVK_PageDown
kVK_F1
kVK_LeftArrow
kVK_RightArrow
kVK_DownArrow
kVK_UpArrow
Definition at line 145 of file GHOST_SystemCocoa.mm.
anonymous enum
Enumerator:
kVK_ISO_Section
Definition at line 196 of file GHOST_SystemCocoa.mm.
anonymous enum
Enumerator:
kVK_JIS_Yen
kVK_JIS_Underscore
kVK_JIS_KeypadComma
kVK_JIS_Eisu
kVK_JIS_Kana
Definition at line 201 of file GHOST_SystemCocoa.mm.
anonymous enum
Enumerator:
NSEventTypeGesture
NSEventTypeMagnify
NSEventTypeSwipe
NSEventTypeRotate
NSEventTypeBeginGesture
NSEventTypeEndGesture
Definition at line 425 of file GHOST_SystemCocoa.mm.
Function Documentation
static GHOST_TButtonMask convertButton (int button) [static]
Definition at line 210 of file GHOST_SystemCocoa.mm.
References GHOST_kButtonMaskButton4, GHOST_kButtonMaskButton5, GHOST_kButtonMaskLeft, GHOST_kButtonMaskMiddle, and GHOST_kButtonMaskRight.
Referenced by GHOST_SystemCocoa::handleMouseEvent(), and GHOST_SystemCocoa::handleWindowEvent().
static GHOST_TKey convertKey (int rawCode, unichar recvChar, UInt16 keyAction) [static]
Converts Mac rawkey codes (same for Cocoa & Carbon) into GHOST key codes
Parameters:
rawCode The raw physical key code
recvChar the character ignoring modifiers (except for shift)
Returns:
Ghost key code
Definition at line 235 of file GHOST_SystemCocoa.mm.
References GHOST_kKey0, GHOST_kKey1, GHOST_kKey2, GHOST_kKey3, GHOST_kKey4, GHOST_kKey5, GHOST_kKey6, GHOST_kKey7, GHOST_kKey8, GHOST_kKey9, GHOST_kKeyA, GHOST_kKeyAccentGrave, GHOST_kKeyBackslash, GHOST_kKeyBackSpace, GHOST_kKeyComma, GHOST_kKeyDelete, GHOST_kKeyDownArrow, GHOST_kKeyDownPage, GHOST_kKeyEnd, GHOST_kKeyEnter, GHOST_kKeyEqual, GHOST_kKeyEsc, GHOST_kKeyF1, GHOST_kKeyF10, GHOST_kKeyF11, GHOST_kKeyF12, GHOST_kKeyF13, GHOST_kKeyF14, GHOST_kKeyF15, GHOST_kKeyF16, GHOST_kKeyF17, GHOST_kKeyF18, GHOST_kKeyF19, GHOST_kKeyF2, GHOST_kKeyF20, GHOST_kKeyF3, GHOST_kKeyF4, GHOST_kKeyF5, GHOST_kKeyF6, GHOST_kKeyF7, GHOST_kKeyF8, GHOST_kKeyF9, GHOST_kKeyHome, GHOST_kKeyLeftArrow, GHOST_kKeyLeftBracket, GHOST_kKeyMinus, GHOST_kKeyNumpad0, GHOST_kKeyNumpad1, GHOST_kKeyNumpad2, GHOST_kKeyNumpad3, GHOST_kKeyNumpad4, GHOST_kKeyNumpad5, GHOST_kKeyNumpad6, GHOST_kKeyNumpad7, GHOST_kKeyNumpad8, GHOST_kKeyNumpad9, GHOST_kKeyNumpadAsterisk, GHOST_kKeyNumpadEnter, GHOST_kKeyNumpadMinus, GHOST_kKeyNumpadPeriod, GHOST_kKeyNumpadPlus, GHOST_kKeyNumpadSlash, GHOST_kKeyPeriod, GHOST_kKeyQuote, GHOST_kKeyRightArrow, GHOST_kKeyRightBracket, GHOST_kKeySemicolon, GHOST_kKeySlash, GHOST_kKeySpace, GHOST_kKeyTab, GHOST_kKeyUnknown, GHOST_kKeyUpArrow, GHOST_kKeyUpPage, kVK_ANSI_0, kVK_ANSI_1, kVK_ANSI_2, kVK_ANSI_3, kVK_ANSI_4, kVK_ANSI_5, kVK_ANSI_6, kVK_ANSI_7, kVK_ANSI_8, kVK_ANSI_9, kVK_ANSI_Keypad0, kVK_ANSI_Keypad1, kVK_ANSI_Keypad2, kVK_ANSI_Keypad3, kVK_ANSI_Keypad4, kVK_ANSI_Keypad5, kVK_ANSI_Keypad6, kVK_ANSI_Keypad7, kVK_ANSI_Keypad8, kVK_ANSI_Keypad9, kVK_ANSI_KeypadClear, kVK_ANSI_KeypadDecimal, kVK_ANSI_KeypadDivide, kVK_ANSI_KeypadEnter, kVK_ANSI_KeypadMinus, kVK_ANSI_KeypadMultiply, kVK_ANSI_KeypadPlus, kVK_Delete, kVK_DownArrow, kVK_End, kVK_Escape, kVK_F1, kVK_F10, kVK_F11, kVK_F12, kVK_F13, kVK_F14, kVK_F15, kVK_F16, kVK_F17, kVK_F18, kVK_F19, kVK_F2, kVK_F20, kVK_F3, kVK_F4, kVK_F5, kVK_F6, kVK_F7, kVK_F8, kVK_F9, kVK_ForwardDelete, kVK_Home, kVK_ISO_Section, kVK_LeftArrow, kVK_Mute, kVK_PageDown, kVK_PageUp, kVK_Return, kVK_RightArrow, kVK_Space, kVK_Tab, kVK_UpArrow, kVK_VolumeDown, and kVK_VolumeUp.
Referenced by GHOST_SystemCocoa::handleKeyEvent().
int GHOST_HACK_getFirstFile (char buf[FIRSTFILEBUFLG])
Definition at line 454 of file GHOST_SystemCocoa.mm.
References g_firstFileBuf, and g_hasFirstFile.
Variable Documentation
__pad0__
Definition at line 507 of file GHOST_SystemCocoa.mm.
char g_firstFileBuf[512] [static]
Definition at line 451 of file GHOST_SystemCocoa.mm.
Referenced by GHOST_HACK_getFirstFile().
bool g_hasFirstFile = false [static]
Definition at line 450 of file GHOST_SystemCocoa.mm.
Referenced by GHOST_HACK_getFirstFile().