Blender: external_engine.c File Reference
external_engine.c File Reference
Rendering
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "BLF_translation.h"
#include "BLI_listbase.h"
#include "BLI_string.h"
#include "BLI_utildefines.h"
#include "BKE_global.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "IMB_imbuf.h"
#include "IMB_imbuf_types.h"
#include "RE_engine.h"
#include "RE_pipeline.h"
#include "render_types.h"
#include "render_result.h"
Functions
void RE_engines_init (void)
void RE_engines_exit (void)
RenderEngineType * RE_engines_find (const char *idname)
int RE_engine_is_external (Render *re)
RenderEngine * RE_engine_create (RenderEngineType *type)
void RE_engine_free (RenderEngine *engine)
RenderResult * RE_engine_begin_result (RenderEngine *engine, int x, int y, int w, int h)
void RE_engine_update_result (RenderEngine *engine, RenderResult *result)
void RE_engine_end_result (RenderEngine *engine, RenderResult *result)
int RE_engine_test_break (RenderEngine *engine)
void RE_engine_update_stats (RenderEngine *engine, const char *stats, const char *info)
void RE_engine_update_progress (RenderEngine *engine, float progress)
void RE_engine_report (RenderEngine *engine, int type, const char *msg)
int RE_engine_render (Render *re, int do_all)
Variables
static RenderEngineType internal_render_type
ListBase R_engines = {NULL, NULL}
Detailed Description
Definition in file external_engine.c.
Function Documentation
RenderResult* RE_engine_begin_result (RenderEngine * engine, int x, int y, int w, int h) [read]
Definition at line 151 of file external_engine.c.
References BLI_addtail(), CLAMP(), Render::disprect, RenderEngine::fullresult, RenderEngine::re, RenderResult::rectx, RenderResult::recty, render_result_new(), Render::result, RR_USE_MEM, RenderResult::tilerect, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by BlenderSession::render().
RenderEngine* RE_engine_create (RenderEngineType * type)
Definition at line 127 of file external_engine.c.
References MEM_callocN(), and RenderEngine::type.
Referenced by RE_engine_render(), and view3d_main_area_draw_engine().
void RE_engine_end_result (RenderEngine * engine, RenderResult * result)
Definition at line 195 of file external_engine.c.
References Render::ddh, Render::display_draw, ListBase::first, RenderEngine::fullresult, RenderResult::layers, NULL, Render::r, R_PREVIEWBUTS, RenderEngine::re, render_result_free_list(), render_result_merge(), RenderResult::renlay, Render::result, RenderData::scemode, Render::tbh, and Render::test_break.
Referenced by BlenderSession::render().
void RE_engine_free (RenderEngine * engine)
Definition at line 135 of file external_engine.c.
References BPY_DECREF(), MEM_freeN(), RenderEngine::py_instance, and RenderEngine::text.
Referenced by ED_render_engine_area_exit(), lib_link_screen_restore(), RE_engine_render(), and view3d_main_area_free().
int RE_engine_is_external (Render * re)
Definition at line 119 of file external_engine.c.
References RenderData::engine, Render::r, RE_engines_find(), and RenderEngineType::render.
Referenced by validate_render_settings().
int RE_engine_render (Render * re, int do_all)
Definition at line 274 of file external_engine.c.
References BKE_reports_contain(), BLI_rw_mutex_lock(), BLI_rw_mutex_unlock(), BLI_strncpy(), Render::camera_override, RenderEngine::camera_override, RenderData::cfra, RenderStats::cfra, Render::disprect, RenderData::engine, ListBase::first, RenderEngine::flag, Render::flag, RenderEngineType::flag, RenderEngine::fullresult, G, Render::i, Scene::id, Render::lay, Render::main, ID::name, NULL, Scene::r, Render::r, R_ANIMATION, R_NO_FRAME_UPDATE, R_PREVIEWBUTS, RenderEngine::re, RE_ENGINE_ANIMATION, RE_engine_create(), RE_engine_free(), RE_ENGINE_PREVIEW, RE_engines_find(), RE_USE_POSTPROCESS, RE_USE_PREVIEW, RenderEngineType::render, render_result_free(), render_result_free_list(), render_result_new(), Render::reports, Render::result, Render::resultmutex, RPT_ERROR, RenderData::scemode, Render::scene, scene_update_for_newframe(), RenderStats::scenename, THREAD_LOCK_WRITE, RenderStats::totface, RenderStats::tothalo, RenderStats::totlamp, RenderStats::totstrand, RenderStats::totvert, and RenderEngineType::update.
Referenced by do_render_3d(), and do_render_all_options().
void RE_engine_report (RenderEngine * engine, int type, const char * msg)
Definition at line 267 of file external_engine.c.
References BKE_report(), RenderEngine::re, and Render::reports.
int RE_engine_test_break (RenderEngine * engine)
Definition at line 218 of file external_engine.c.
References RenderEngine::re, Render::tbh, and Render::test_break.
Referenced by BlenderSession::test_cancel().
void RE_engine_update_progress (RenderEngine * engine, float progress)
Definition at line 257 of file external_engine.c.
References CLAMP(), Render::prh, Render::progress, and RenderEngine::re.
Referenced by BlenderSession::update_status_progress().
void RE_engine_update_result (RenderEngine * engine, RenderResult * result)
Definition at line 185 of file external_engine.c.
References Render::ddh, Render::display_draw, ListBase::first, RenderResult::layers, NULL, RenderEngine::re, and RenderResult::renlay.
Referenced by BlenderSession::write_render_result().
void RE_engine_update_stats (RenderEngine * engine, const char * stats, const char * info)
Definition at line 230 of file external_engine.c.
References BLI_sprintfN(), BLI_strdup(), Render::i, RenderStats::infostr, MEM_freeN(), NULL, RenderEngine::re, Render::sdh, Render::stats_draw, RenderStats::statstr, and RenderEngine::text.
Referenced by BlenderSession::update_status_progress().
void RE_engines_exit (void)
Definition at line 90 of file external_engine.c.
References BLI_remlink(), ExtensionRNA::data, RenderEngineType::ext, ListBase::first, RenderEngineType::flag, ExtensionRNA::free, MEM_freeN(), RenderEngineType::next, next, and RE_INTERNAL.
Referenced by WM_exit_ext().
RenderEngineType* RE_engines_find (const char * idname)
Definition at line 108 of file external_engine.c.
References BLI_findstring(), and internal_render_type.
Referenced by RE_engine_is_external(), RE_engine_render(), scene_use_new_shading_nodes(), and view3d_main_area_draw_engine().
void RE_engines_init (void)
Definition at line 82 of file external_engine.c.
References BLI_addtail().
Referenced by main().
Variable Documentation
RenderEngineType internal_render_type [static]
Initial value:
 {
    NULL, NULL,
    "BLENDER_RENDER", N_("Blender Render"), RE_INTERNAL,
    NULL, NULL, NULL, NULL,
    {NULL, NULL, NULL}}
Definition at line 64 of file external_engine.c.
Referenced by RE_engines_find().
ListBase R_engines = {NULL, NULL}
Definition at line 80 of file external_engine.c.
Referenced by set_engine(), and WM_read_file().