Blender: btVector4 Class Reference
btVector4 Class Reference
#include <btVector3.h>
Public Member Functions
SIMD_FORCE_INLINE btVector4 ()
SIMD_FORCE_INLINE btVector4 (const btScalar &x, const btScalar &y, const btScalar &z, const btScalar &w)
SIMD_FORCE_INLINE btVector4 absolute4 () const
btScalar getW () const
SIMD_FORCE_INLINE int maxAxis4 () const
SIMD_FORCE_INLINE int minAxis4 () const
SIMD_FORCE_INLINE int closestAxis4 () const
SIMD_FORCE_INLINE void setValue (const btScalar &x, const btScalar &y, const btScalar &z, const btScalar &w)
Set x,y,z and zero w.
Detailed Description
Definition at line 507 of file btVector3.h.
Constructor & Destructor Documentation
SIMD_FORCE_INLINE btVector4::btVector4 () [inline]
Definition at line 511 of file btVector3.h.
Referenced by absolute4().
SIMD_FORCE_INLINE btVector4::btVector4 (const btScalar & x, const btScalar & y, const btScalar & z, const btScalar & w) [inline]
Definition at line 514 of file btVector3.h.
Member Function Documentation
SIMD_FORCE_INLINE btVector4 btVector4::absolute4 () const [inline]
Definition at line 521 of file btVector3.h.
References btFabs(), and btVector4().
Referenced by closestAxis4().
SIMD_FORCE_INLINE int btVector4::closestAxis4 () const [inline]
Definition at line 598 of file btVector3.h.
References absolute4(), and maxAxis4().
btScalar btVector4::getW () const [inline]
Definition at line 532 of file btVector3.h.
SIMD_FORCE_INLINE int btVector4::maxAxis4 () const [inline]
Definition at line 535 of file btVector3.h.
References BT_LARGE_FLOAT.
Referenced by closestAxis4().
SIMD_FORCE_INLINE int btVector4::minAxis4 () const [inline]
Definition at line 568 of file btVector3.h.
References BT_LARGE_FLOAT.
void Frame::setValue (const btScalar & x, const btScalar & y, const btScalar & z, const btScalar & w) [inline]
Set x,y,z and zero w.
Parameters:
x Value of x
y Value of y
z Value of zSet the values
x Value of x
y Value of y
z Value of z
w Value of w
Definition at line 626 of file btVector3.h.
Referenced by bt_edge_plane(), bt_segment_collision(), btTriangleShapeEx::buildTriPlane(), btPrimitiveTriangle::buildTriPlane(), btBox2dShape::getPlaneEquation(), and btBoxShape::getPlaneEquation().
The documentation for this class was generated from the following files:
btVector3.h
frames.inl