Blender: MOD_surface.c File Reference
MOD_surface.c File Reference
modifiers
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "DNA_meshdata_types.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_cdderivedmesh.h"
#include "MOD_modifiertypes.h"
#include "MOD_util.h"
#include "MEM_guardedalloc.h"
Functions
static void initData (ModifierData *md)
static void freeData (ModifierData *md)
static int dependsOnTime (ModifierData *UNUSED(md))
static void deformVerts (ModifierData *md, Object *ob, DerivedMesh *derivedData, float(*vertexCos)[3], int UNUSED(numVerts), int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
Variables
ModifierTypeInfo modifierType_Surface
Detailed Description
Definition in file MOD_surface.c.
Function Documentation
static void deformVerts (ModifierData * md, Object * ob, DerivedMesh * derivedData, float(*) vertexCos[3], int UNUSEDnumVerts, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 88 of file MOD_surface.c.
References SurfaceModifierData::bvhtree, bvhtree_from_mesh_edges(), bvhtree_from_mesh_faces(), CDDM_apply_vert_coords(), CDDM_calc_normals(), CDDM_copy(), CDDM_get_vert(), SurfaceModifierData::cfra, RenderData::cfra, MVert::co, copy_v3_v3(), SurfaceModifierData::dm, free_bvhtree_from_mesh(), get_dm(), DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, i, init(), MEM_callocN(), MEM_freeN(), mul_m4_v3(), NULL, SurfaceModifierData::numverts, Object::obmat, Object::pd, Scene::r, DerivedMesh::release, ModifierData::scene, sub_v3_v3v3(), SurfaceModifierData::v, and SurfaceModifierData::x.
static int dependsOnTime (ModifierData * UNUSEDmd) [static]
Definition at line 83 of file MOD_surface.c.
static void freeData (ModifierData * md) [static]
Definition at line 59 of file MOD_surface.c.
References SurfaceModifierData::bvhtree, SurfaceModifierData::dm, free_bvhtree_from_mesh(), MEM_freeN(), NULL, DerivedMesh::release, SurfaceModifierData::v, and SurfaceModifierData::x.
static void initData (ModifierData * md) [static]
Definition at line 52 of file MOD_surface.c.
References SurfaceModifierData::bvhtree, and NULL.
Variable Documentation
ModifierTypeInfo modifierType_Surface
Initial value:
 {
                  "Surface",
            "SurfaceModifierData",
            sizeof(SurfaceModifierData),
                  eModifierTypeType_OnlyDeform,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_NoUserAdd,
              NULL,
           deformVerts,
        NULL,
         NULL,
      NULL,
         NULL,
       NULL,
              initData,
      NULL,
              freeData,
            NULL,
        NULL,
         dependsOnTime,
        NULL,
     NULL,
         NULL,
        NULL,
}
Definition at line 166 of file MOD_surface.c.