Blender: info_ops.c File Reference
info_ops.c File Reference
info space
#include <string.h>
#include <stdio.h>
#include "DNA_packedFile_types.h"
#include "DNA_space_types.h"
#include "DNA_windowmanager_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_bpath.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_image.h"
#include "BKE_main.h"
#include "BKE_packedFile.h"
#include "BKE_report.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "IMB_imbuf_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "info_intern.h"
Defines
#define INFO_TIMEOUT 5.0f
#define INFO_COLOR_TIMEOUT 3.0f
#define ERROR_TIMEOUT 10.0f
#define ERROR_COLOR_TIMEOUT 6.0f
#define COLLAPSE_TIMEOUT 0.25f
Functions
static int pack_all_exec (bContext *C, wmOperator *op)
static int pack_all_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void FILE_OT_pack_all (wmOperatorType *ot)
static int unpack_all_exec (bContext *C, wmOperator *op)
static int unpack_all_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void FILE_OT_unpack_all (wmOperatorType *ot)
static int make_paths_relative_exec (bContext *C, wmOperator *op)
void FILE_OT_make_paths_relative (wmOperatorType *ot)
static int make_paths_absolute_exec (bContext *C, wmOperator *op)
void FILE_OT_make_paths_absolute (wmOperatorType *ot)
static int report_missing_files_exec (bContext *C, wmOperator *op)
void FILE_OT_report_missing_files (wmOperatorType *ot)
static int find_missing_files_exec (bContext *C, wmOperator *op)
static int find_missing_files_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void FILE_OT_find_missing_files (wmOperatorType *ot)
static int update_reports_display_invoke (bContext *C, wmOperator *UNUSED(op), wmEvent *event)
void INFO_OT_reports_display_update (wmOperatorType *ot)
Variables
static const EnumPropertyItem unpack_all_method_items []
Detailed Description
Definition in file info_ops.c.
Define Documentation
#define COLLAPSE_TIMEOUT 0.25f
Definition at line 328 of file info_ops.c.
Referenced by update_reports_display_invoke().
#define ERROR_COLOR_TIMEOUT 6.0f
Definition at line 327 of file info_ops.c.
Referenced by update_reports_display_invoke().
#define ERROR_TIMEOUT 10.0f
Definition at line 326 of file info_ops.c.
Referenced by update_reports_display_invoke().
#define INFO_COLOR_TIMEOUT 3.0f
Definition at line 325 of file info_ops.c.
Referenced by update_reports_display_invoke().
#define INFO_TIMEOUT 5.0f
Definition at line 324 of file info_ops.c.
Referenced by update_reports_display_invoke().
Function Documentation
void FILE_OT_find_missing_files (wmOperatorType * ot)
Definition at line 298 of file info_ops.c.
References wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, find_missing_files_exec(), find_missing_files_invoke(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, WM_FILESEL_FILEPATH, and WM_operator_properties_filesel().
Referenced by info_operatortypes().
void FILE_OT_make_paths_absolute (wmOperatorType * ot)
Definition at line 241 of file info_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, make_paths_absolute_exec(), wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by info_operatortypes().
void FILE_OT_make_paths_relative (wmOperatorType * ot)
Definition at line 209 of file info_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, make_paths_relative_exec(), wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by info_operatortypes().
void FILE_OT_pack_all (wmOperatorType * ot)
Definition at line 105 of file info_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, pack_all_exec(), and pack_all_invoke().
Referenced by info_operatortypes().
void FILE_OT_report_missing_files (wmOperatorType * ot)
Definition at line 266 of file info_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, and report_missing_files_exec().
Referenced by info_operatortypes().
void FILE_OT_unpack_all (wmOperatorType * ot)
Definition at line 173 of file info_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PF_USE_LOCAL, RNA_def_enum(), wmOperatorType::srna, unpack_all_exec(), and unpack_all_invoke().
Referenced by info_operatortypes().
static int find_missing_files_exec (bContext * C, wmOperator * op) [static]
Definition at line 281 of file info_ops.c.
References CTX_data_main(), findMissingFiles(), MEM_freeN(), NULL, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, and RNA_string_get_alloc().
Referenced by FILE_OT_find_missing_files().
static int find_missing_files_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 291 of file info_ops.c.
References OPERATOR_RUNNING_MODAL, and WM_event_add_fileselect().
Referenced by FILE_OT_find_missing_files().
void INFO_OT_reports_display_update (wmOperatorType * ot)
Definition at line 412 of file info_ops.c.
References wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, and update_reports_display_invoke().
Referenced by info_operatortypes().
static int make_paths_absolute_exec (bContext * C, wmOperator * op) [static]
Definition at line 224 of file info_ops.c.
References BKE_report(), CTX_data_main(), G, makeFilesAbsolute(), Main::name, NC_WINDOW, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_WARNING, and WM_main_add_notifier().
Referenced by FILE_OT_make_paths_absolute().
static int make_paths_relative_exec (bContext * C, wmOperator * op) [static]
Definition at line 192 of file info_ops.c.
References BKE_report(), CTX_data_main(), G, makeFilesRelative(), Main::name, NC_WINDOW, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_WARNING, and WM_main_add_notifier().
Referenced by FILE_OT_make_paths_relative().
static int pack_all_exec (bContext * C, wmOperator * op) [static]
Definition at line 71 of file info_ops.c.
References CTX_data_main(), G, G_AUTOPACK, OPERATOR_FINISHED, packAll(), and wmOperator::reports.
Referenced by FILE_OT_pack_all(), and pack_all_invoke().
static int pack_all_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 81 of file info_ops.c.
References BKE_image_get_ibuf(), CTX_data_main(), ListBase::first, IB_BITMAPDIRTY, Image::ibufs, Image::id, Main::image, ID::next, NULL, OPERATOR_CANCELLED, pack_all_exec(), uiPupMenuOkee(), and ImBuf::userflags.
Referenced by FILE_OT_pack_all().
static int report_missing_files_exec (bContext * C, wmOperator * op) [static]
Definition at line 256 of file info_ops.c.
References checkMissingFiles(), CTX_data_main(), OPERATOR_FINISHED, and wmOperator::reports.
Referenced by FILE_OT_report_missing_files().
static int unpack_all_exec (bContext * C, wmOperator * op) [static]
Definition at line 130 of file info_ops.c.
References CTX_data_main(), G, G_AUTOPACK, OPERATOR_FINISHED, PF_KEEP, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), and unpackAll().
Referenced by FILE_OT_unpack_all().
static int unpack_all_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 141 of file info_ops.c.
References BKE_report(), BLI_snprintf(), countPackedFiles(), CTX_data_main(), G, G_AUTOPACK, OPERATOR_CANCELLED, wmOperator::reports, RPT_WARNING, uiItemsEnumO(), uiLayoutSetOperatorContext(), uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), and WM_OP_EXEC_DEFAULT.
Referenced by FILE_OT_unpack_all().
static int update_reports_display_invoke (bContext * C, wmOperator * UNUSEDop, wmEvent * event) [static]
Definition at line 329 of file info_ops.c.
References BKE_reports_last_displayable(), ReportTimerInfo::col, COLLAPSE_TIMEOUT, CTX_wm_manager(), CTX_wm_reports(), wmTimer::customdata, wmEvent::customdata, wmTimer::duration, ERROR_COLOR_TIMEOUT, ERROR_TIMEOUT, ReportTimerInfo::greyscale, INFO_COLOR_TIMEOUT, INFO_TIMEOUT, interp_v3_v3v3(), interpf(), NC_SPACE, ND_SPACE_INFO, NULL, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, ReportList::reporttimer, RPT_ERROR_ALL, RPT_INFO_ALL, RPT_WARNING_ALL, Report::type, ReportTimerInfo::widthfac, WM_event_add_notifier(), and WM_event_remove_timer().
Referenced by INFO_OT_reports_display_update().
Variable Documentation
const EnumPropertyItem unpack_all_method_items[] [static]
Initial value:
 {
    {PF_USE_LOCAL, "USE_LOCAL", 0, "Use files in current directory (create when necessary)", ""},
    {PF_WRITE_LOCAL, "WRITE_LOCAL", 0, "Write files to current directory (overwrite existing files)", ""},
    {PF_USE_ORIGINAL, "USE_ORIGINAL", 0, "Use files in original location (create when necessary)", ""},
    {PF_WRITE_ORIGINAL, "WRITE_ORIGINAL", 0, "Write files to original location (overwrite existing files)", ""},
    {PF_KEEP, "KEEP", 0, "Disable AutoPack, keep all packed files", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 121 of file info_ops.c.