Blender: KX_ConvertSensors.h File Reference
KX_ConvertSensors.h File Reference
Converter
Functions
void BL_ConvertSensors (struct Object *blenderobject, class KX_GameObject *gameobj, class SCA_LogicManager *logicmgr, class KX_Scene *kxscene, class KX_KetsjiEngine *kxengine, int activeLayerBitInfo, bool isInActiveLayer, class RAS_ICanvas *canvas, class KX_BlenderSceneConverter *converter)
Detailed Description
Definition in file KX_ConvertSensors.h.
Function Documentation
void BL_ConvertSensors (struct Object * blenderobject, class KX_GameObject * gameobj, class SCA_LogicManager * logicmgr, class KX_Scene * kxscene, class KX_KetsjiEngine * kxengine, int activeLayerBitInfo, bool isInActiveLayer, class RAS_ICanvas * canvas, class KX_BlenderSceneConverter * converter)
Definition at line 91 of file KX_ConvertSensors.cpp.
References SCA_EventManager::ACTUATOR_EVENTMGR, SCA_IObject::AddSensor(), bRadarSensor::angle, bJoystickSensor::axis, bRadarSensor::axis, bJoystickSensor::axis_single, bJoystickSensor::axisf, bRaySensor::axisflag, SCA_EventManager::BASIC_EVENTMGR, BL_SENS_MOUSE_LEFT_BUTTON, BL_SENS_MOUSE_MIDDLE_BUTTON, BL_SENS_MOUSE_MOUSEOVER, BL_SENS_MOUSE_MOUSEOVER_ANY, BL_SENS_MOUSE_MOVEMENT, BL_SENS_MOUSE_RIGHT_BUTTON, BL_SENS_MOUSE_WHEEL_DOWN, BL_SENS_MOUSE_WHEEL_UP, bJoystickSensor::button, bArmatureSensor::constraint, ConvertKeyCode(), PHY_IPhysicsEnvironment::CreateConeController(), PHY_IPhysicsEnvironment::CreateSphereController(), bSensor::data, bDelaySensor::delay, bNearSensor::dist, distance(), bDelaySensor::duration, SCA_LogicManager::FindEventManager(), KX_BlenderSceneConverter::FindGameController(), ListBase::first, bMouseSensor::flag, bJoystickSensor::flag, bDelaySensor::flag, bSensor::freq, RAS_ICanvas::GetHeight(), KX_Scene::GetNetworkScene(), KX_GameObject::GetPhysicsController(), KX_Scene::GetPhysicsEnvironment(), KX_KetsjiEngine::GetRealTime(), CIntValue::GetText(), RAS_ICanvas::GetWidth(), bJoystickSensor::hat, bJoystickSensor::hatf, i, Material::id, Object::id, if(), SCA_ISensor::IncLink(), bSensor::invert, invert(), SCA_EventManager::JOY_EVENTMGR, bJoystickSensor::joyindex, bKeyboardSensor::key, SCA_EventManager::KEYBOARD_EVENTMGR, SCA_MouseSensor::KX_MOUSESENSORMODE_LEFTBUTTON, SCA_MouseSensor::KX_MOUSESENSORMODE_MIDDLEBUTTON, SCA_MouseSensor::KX_MOUSESENSORMODE_MOVEMENT, SCA_MouseSensor::KX_MOUSESENSORMODE_NODEF, SCA_MouseSensor::KX_MOUSESENSORMODE_RIGHTBUTTON, SCA_MouseSensor::KX_MOUSESENSORMODE_WHEELDOWN, SCA_MouseSensor::KX_MOUSESENSORMODE_WHEELUP, SCA_PropertySensor::KX_PROPSENSOR_CHANGED, SCA_PropertySensor::KX_PROPSENSOR_EQUAL, SCA_PropertySensor::KX_PROPSENSOR_EXPRESSION, SCA_PropertySensor::KX_PROPSENSOR_INTERVAL, SCA_PropertySensor::KX_PROPSENSOR_NODEF, SCA_PropertySensor::KX_PROPSENSOR_NOTEQUAL, bSensor::level, bSensor::links, bTouchSensor::ma, bCollisionSensor::materialName, bRaySensor::matname, bPropertySensor::maxvalue, bRaySensor::mode, bCollisionSensor::mode, SCA_EventManager::MOUSE_EVENTMGR, MT_radians(), bPropertySensor::name, bRadarSensor::name, bCollisionSensor::name, bSensor::name, bNearSensor::name, ID::name, bActuatorSensor::name, SCA_EventManager::NETWORK_EVENTMGR, bSensor::next, KX_GameObject::NodeGetWorldPosition(), NULL, bArmatureSensor::posechannel, bJoystickSensor::precision, bRaySensor::propname, bSensor::pulse, bKeyboardSensor::qual, bKeyboardSensor::qual2, bRadarSensor::range, bRaySensor::range, SCA_LogicManager::RegisterToSensor(), CValue::Release(), SCA_ISensor::ReserveController(), SCA_IObject::ReserveSensor(), bNearSensor::resetdist, bRandomSensor::seed, SENS_ACTUATOR, SENS_ALL_KEYS, SENS_ALWAYS, SENS_ARMATURE, SENS_COLLISION, SENS_COLLISION_MATERIAL, SENS_COLLISION_PULSE, SENS_DELAY, SENS_DELAY_REPEAT, SENS_JOY_ANY_EVENT, SENS_JOY_AXIS, SENS_JOY_AXIS_SINGLE, SENS_JOY_BUTTON, SENS_JOY_HAT, SENS_JOYSTICK, SENS_KEYBOARD, SENS_MESSAGE, SENS_MOUSE, SENS_MOUSE_FOCUS_PULSE, SENS_NEAR, SENS_NEG_PULSE_MODE, SENS_PROP_CHANGED, SENS_PROP_EQUAL, SENS_PROP_EXPRESSION, SENS_PROP_INTERVAL, SENS_PROP_NEQUAL, SENS_PROPERTY, SENS_PULSE_REPEAT, SENS_RADAR, SENS_RANDOM, SENS_RAY, SENS_RAY_XRAY, SENS_TOUCH, Object::sensors, SCA_ILogicBrick::SetExecutePriority(), SCA_ISensor::SetInvert(), SCA_ISensor::SetLevel(), SCA_ILogicBrick::SetName(), SCA_ISensor::SetPulseMode(), SCA_ISensor::SetTap(), bMessageSensor::subject, KDL::tan(), bSensor::tap, bKeyboardSensor::targetName, bKeyboardSensor::toggleName, bSensor::totlinks, SCA_EventManager::TOUCH_EVENTMGR, bKeyboardSensor::type, bJoystickSensor::type, bPropertySensor::type, bArmatureSensor::type, bSensor::type, bMouseSensor::type, bPropertySensor::value, and bArmatureSensor::value.
Referenced by BL_ConvertBlenderObjects().