Blender: BKE_speaker.h File Reference
BKE_speaker.h File Reference
blenkernel
General operations for speakers.
Functions
void * add_speaker (const char *name)
struct Speaker * copy_speaker (struct Speaker *spk)
void make_local_speaker (struct Speaker *spk)
void free_speaker (struct Speaker *spk)
Detailed Description
General operations for speakers.
Definition in file BKE_speaker.h.
Function Documentation
void* add_speaker (const char * name)
Definition at line 46 of file speaker.c.
References alloc_libblock(), Speaker::attenuation, Speaker::cone_angle_inner, Speaker::cone_angle_outer, Speaker::cone_volume_outer, Speaker::distance_max, Speaker::distance_reference, Speaker::flag, FLT_MAX, G, ID_SPK, NULL, Speaker::pitch, Speaker::sound, Speaker::volume, Speaker::volume_max, and Speaker::volume_min.
Referenced by add_obdata_from_type().
struct Speaker* copy_speaker (struct Speaker * spk) [read]
Definition at line 68 of file speaker.c.
References copy_libblock(), bSound::id, Speaker::id, Speaker::sound, and ID::us.
Referenced by id_copy(), make_local_speaker(), object_add_duplicate_internal(), and single_obdata_users().
void free_speaker (struct Speaker * spk)
Definition at line 130 of file speaker.c.
References BKE_free_animdata(), bSound::id, Speaker::sound, and ID::us.
Referenced by free_libblock().
void make_local_speaker (struct Speaker * spk)
Definition at line 79 of file speaker.c.
References BKE_id_lib_local_paths(), copy_speaker(), Object::data, FALSE, ListBase::first, G, Object::id, Speaker::id, id_clear_lib_data(), ID::lib, ID::next, NULL, Main::object, TRUE, and ID::us.
Referenced by id_make_local().