Blender: KX_ConvertProperties.cpp File Reference
KX_ConvertProperties.cpp File Reference
Converter
#include "KX_ConvertProperties.h"
#include "DNA_object_types.h"
#include "DNA_property_types.h"
#include "Value.h"
#include "VectorValue.h"
#include "BoolValue.h"
#include "StringValue.h"
#include "FloatValue.h"
#include "KX_GameObject.h"
#include "IntValue.h"
#include "SCA_TimeEventManager.h"
#include "SCA_IScene.h"
#include "KX_FontObject.h"
#include "DNA_curve_types.h"
#include "BKE_property.h"
Functions
void BL_ConvertTextProperty (Object *object, KX_FontObject *fontobj, SCA_TimeEventManager *timemgr, SCA_IScene *scene, bool isInActiveLayer)
void BL_ConvertProperties (Object *object, KX_GameObject *gameobj, SCA_TimeEventManager *timemgr, SCA_IScene *scene, bool isInActiveLayer)
Detailed Description
Definition in file KX_ConvertProperties.cpp.
Function Documentation
void BL_ConvertProperties (Object * object, KX_GameObject * gameobj, SCA_TimeEventManager * timemgr, SCA_IScene * scene, bool isInActiveLayer)
Definition at line 66 of file KX_ConvertProperties.cpp.
References SCA_IScene::AddDebugProperty(), SCA_TimeEventManager::AddTimeProperty(), BL_ConvertTextProperty(), bProperty::data, ListBase::first, bProperty::flag, GPROP_BOOL, GPROP_FLOAT, GPROP_INT, GPROP_STRING, GPROP_TIME, Object::id, bProperty::name, ID::name, bProperty::next, NULL, OB_DEBUGSTATE, OB_FONT, bProperty::poin, Object::prop, PROP_DEBUG, CValue::Release(), Object::scaflag, CValue::SetProperty(), Object::type, and bProperty::type.
Referenced by bl_ConvertBlenderObject_Single().
void BL_ConvertTextProperty (Object * object, KX_FontObject * fontobj, SCA_TimeEventManager * timemgr, SCA_IScene * scene, bool isInActiveLayer)
Definition at line 176 of file KX_ConvertProperties.cpp.
References SCA_TimeEventManager::AddTimeProperty(), get_ob_property(), CValue::GetProperty(), GPROP_BOOL, GPROP_FLOAT, GPROP_INT, GPROP_STRING, GPROP_TIME, NULL, CValue::Release(), CValue::SetProperty(), CValue::SetValue(), str, Curve::str, and bProperty::type.
Referenced by BL_ConvertProperties().