Blender: LOD_QSDecimator Class Reference
LOD_QSDecimator Class Reference
#include <LOD_QSDecimator.h>
Public Member Functions
bool Arm ()
bool Step ()
Static Public Member Functions
static LOD_QSDecimator * New (LOD_ManMesh2 &mesh, LOD_ExternNormalEditor &face_editor, LOD_ExternBufferEditor &extern_editor)
Detailed Description
Definition at line 44 of file LOD_QSDecimator.h.
Member Function Documentation
bool LOD_QSDecimator::Arm ()
Definition at line 69 of file LOD_QSDecimator.cpp.
References MT_assert.
Referenced by LOD_PreprocessMesh().
LOD_QSDecimator * LOD_QSDecimator::New (LOD_ManMesh2 & mesh, LOD_ExternNormalEditor & face_editor, LOD_ExternBufferEditor & extern_editor) [static]
Definition at line 41 of file LOD_QSDecimator.cpp.
References LOD_QuadricEditor::New(), LOD_EdgeCollapser::New(), NULL, and MEM_SmartPtr< T >::Release().
Referenced by LOD_DecimationClass::New().
bool LOD_QSDecimator::Step ()
Definition at line 82 of file LOD_QSDecimator.cpp.
Referenced by LOD_CollapseEdge().
The documentation for this class was generated from the following files:
LOD_QSDecimator.h
LOD_NdQSDecimator.cpp
LOD_EdgeCollapser.cpp
LOD_QSDecimator.cpp