Blender: TNT::Array1D< T > Class Template Reference
TNT::Array1D< T > Class Template Reference
#include <tnt_array1d.h>
Public Types
typedef T value_type
Public Member Functions
Array1D ()
Array1D (int n)
Array1D (int n, const T &a)
Array1D (int n, T *a)
Array1D (const Array1D &A)
operator T * ()
operator const T * ()
Array1D & operator= (const T &a)
Array1D & operator= (const Array1D &A)
Array1D & ref (const Array1D &A)
Array1D copy () const
Array1D & inject (const Array1D &A)
T & operator[] (int i)
const T & operator[] (int i) const
int dim1 () const
int dim () const
~Array1D ()
int ref_count () const
Array1D< T > subarray (int i0, int i1)
Detailed Description
template<class T>
class TNT::Array1D< T >
Definition at line 42 of file tnt_array1d.h.
Member Typedef Documentation
template<class T> typedef T TNT::Array1D< T >::value_type
Definition at line 61 of file tnt_array1d.h.
Constructor & Destructor Documentation
template<class T > TNT::Array1D< T >::Array1D ()
Definition at line 94 of file tnt_array1d.h.
template<class T > TNT::Array1D< T >::Array1D (int n) [explicit]
Definition at line 108 of file tnt_array1d.h.
template<class T> TNT::Array1D< T >::Array1D (int n, const T & a)
Definition at line 116 of file tnt_array1d.h.
template<class T> TNT::Array1D< T >::Array1D (int n, T * a)
Definition at line 126 of file tnt_array1d.h.
template<class T> TNT::Array1D< T >::Array1D (const Array1D< T > & A) [inline]
Definition at line 97 of file tnt_array1d.h.
template<class T > TNT::Array1D< T >::~Array1D ()
Definition at line 227 of file tnt_array1d.h.
Member Function Documentation
template<class T > Array1D< T > TNT::Array1D< T >::copy () const
Definition at line 179 of file tnt_array1d.h.
References A.
template<class T > int TNT::Array1D< T >::dim () const [inline]
Definition at line 224 of file tnt_array1d.h.
Referenced by TNT::const_Region1D< Array1D >::const_Region1D(), TNT::Region1D< Array1D >::operator=(), and TNT::Region1D< Array1D >::Region1D().
template<class T > int TNT::Array1D< T >::dim1 () const [inline]
Definition at line 221 of file tnt_array1d.h.
Referenced by TNT::operator*(), TNT::operator*=(), TNT::operator+(), TNT::operator+=(), TNT::operator-(), TNT::operator-=(), TNT::operator/(), TNT::operator/=(), and JAMA::LU< Real >::solve().
template<class T > Array1D< T > & TNT::Array1D< T >::inject (const Array1D< T > & A)
Definition at line 189 of file tnt_array1d.h.
template<class T > TNT::Array1D< T >::operator const T * () [inline]
Definition at line 141 of file tnt_array1d.h.
template<class T > TNT::Array1D< T >::operator T * () [inline]
Definition at line 134 of file tnt_array1d.h.
template<class T> Array1D< T > & TNT::Array1D< T >::operator= (const Array1D< T > & A) [inline]
Definition at line 215 of file tnt_array1d.h.
template<class T> Array1D< T > & TNT::Array1D< T >::operator= (const T & a) [inline]
Definition at line 172 of file tnt_array1d.h.
template<class T > T & TNT::Array1D< T >::operator[] (int i) [inline]
Definition at line 149 of file tnt_array1d.h.
References assert, and i.
template<class T > const T & TNT::Array1D< T >::operator[] (int i) const [inline]
Definition at line 159 of file tnt_array1d.h.
References assert, and i.
template<class T > Array1D< T > & TNT::Array1D< T >::ref (const Array1D< T > & A) [inline]
Definition at line 202 of file tnt_array1d.h.
template<class T > int TNT::Array1D< T >::ref_count () const [inline]
Definition at line 233 of file tnt_array1d.h.
template<class T > Array1D< T > TNT::Array1D< T >::subarray (int i0, int i1) [inline]
Definition at line 239 of file tnt_array1d.h.
References X.
The documentation for this class was generated from the following file:
tnt_array1d.h