Blender: EventToBuf.h File Reference
EventToBuf.h File Reference
Functions
char * eventtype_to_string (GHOST_TEventType type)
void event_to_buf (GHOST_EventHandle evt, char buf[128])
Function Documentation
void event_to_buf (GHOST_EventHandle evt, char buf[128])
Definition at line 196 of file EventToBuf.c.
References GHOST_TEventKeyData::ascii, GHOST_TEventButtonData::button, data, eventtype_to_string(), GHOST_GetEventData(), GHOST_GetEventTime(), GHOST_GetEventType(), GHOST_GetEventWindow(), GHOST_GetTitle(), GHOST_kEventButtonDown, GHOST_kEventButtonUp, GHOST_kEventCursorMove, GHOST_kEventKeyDown, GHOST_kEventKeyUp, GHOST_TEventKeyData::key, keytype_to_string(), GHOST_TEventCursorData::x, and GHOST_TEventCursorData::y.
Referenced by extrawindow_handle(), and mainwindow_handle().
char* eventtype_to_string (GHOST_TEventType type)
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) 2001-2002 by NaN Holding BV. All rights reserved.
The Original Code is: all of this file.
Contributor(s): none yet.
***** END GPL LICENSE BLOCK *****
Definition at line 37 of file EventToBuf.c.
References GHOST_kEventButtonDown, GHOST_kEventButtonUp, GHOST_kEventCursorMove, GHOST_kEventKeyDown, GHOST_kEventKeyUp, GHOST_kEventQuit, GHOST_kEventWindowActivate, GHOST_kEventWindowClose, GHOST_kEventWindowDeactivate, GHOST_kEventWindowSize, and GHOST_kEventWindowUpdate.
Referenced by event_to_buf(), and multitest_event_handler().