Blender: BOP_Tag.h File Reference
BOP_Tag.h File Reference
#include <string.h>
#include <stdio.h>
Defines
#define IN_TAG 0x02
#define ON_TAG 0x00
#define OUT_TAG 0x01
#define INOUT_TAG 0x0E
#define INON_TAG 0x12
#define OUTON_TAG 0x11
#define UNCLASSIFIED_TAG 0x0F
#define PHANTOM_TAG 0x0C
#define OVERLAPPED_TAG 0x0D
#define BROKEN_TAG 0x0B
#define ON_ON_IN_TAG IN_TAG
#define ON_IN_ON_TAG IN_TAG << 2
#define IN_ON_ON_TAG IN_TAG << 4
#define ON_ON_OUT_TAG OUT_TAG
#define ON_OUT_ON_TAG OUT_TAG << 2
#define OUT_ON_ON_TAG OUT_TAG << 4
#define ON_ON_ON_TAG ON_TAG
#define IN_IN_IN_TAG IN_ON_ON_TAG | ON_IN_ON_TAG | ON_ON_IN_TAG
#define OUT_OUT_OUT_TAG OUT_ON_ON_TAG | ON_OUT_ON_TAG | ON_ON_OUT_TAG
#define IN_IN_ON_TAG IN_ON_ON_TAG | ON_IN_ON_TAG
#define IN_ON_IN_TAG IN_ON_ON_TAG | ON_ON_IN_TAG
#define ON_IN_IN_TAG ON_IN_ON_TAG | ON_ON_IN_TAG
#define OUT_OUT_ON_TAG OUT_ON_ON_TAG | ON_OUT_ON_TAG
#define OUT_ON_OUT_TAG OUT_ON_ON_TAG | ON_ON_OUT_TAG
#define ON_OUT_OUT_TAG ON_OUT_ON_TAG | ON_ON_OUT_TAG
#define IN_OUT_OUT_TAG IN_ON_ON_TAG | ON_OUT_OUT_TAG
#define OUT_IN_OUT_TAG ON_IN_ON_TAG | OUT_ON_OUT_TAG
#define OUT_OUT_IN_TAG ON_ON_IN_TAG | OUT_OUT_ON_TAG
#define OUT_IN_IN_TAG ON_IN_IN_TAG | OUT_ON_ON_TAG
#define IN_OUT_IN_TAG IN_ON_IN_TAG | ON_OUT_ON_TAG
#define IN_IN_OUT_TAG IN_IN_ON_TAG | ON_ON_OUT_TAG
#define IN_ON_OUT_TAG IN_ON_ON_TAG | ON_ON_OUT_TAG
#define IN_OUT_ON_TAG IN_ON_ON_TAG | ON_OUT_ON_TAG
#define ON_IN_OUT_TAG ON_IN_ON_TAG | ON_ON_OUT_TAG
#define ON_OUT_IN_TAG ON_ON_IN_TAG | ON_OUT_ON_TAG
#define OUT_IN_ON_TAG ON_IN_ON_TAG | OUT_ON_ON_TAG
#define OUT_ON_IN_TAG ON_ON_IN_TAG | OUT_ON_ON_TAG
Typedefs
typedef enum BOP_TAGEnum BOP_TAG
Enumerations
enum BOP_TAGEnum {
IN = IN_TAG, ON = ON_TAG, OUT = OUT_TAG, INOUT = INOUT_TAG,
INON = INON_TAG, OUTON = OUTON_TAG, UNCLASSIFIED = UNCLASSIFIED_TAG, PHANTOM = PHANTOM_TAG,
OVERLAPPED = OVERLAPPED_TAG, BROKEN = BROKEN_TAG, IN_ON_ON = IN_ON_ON_TAG, ON_IN_ON = ON_IN_ON_TAG,
ON_ON_IN = ON_ON_IN_TAG, OUT_ON_ON = OUT_ON_ON_TAG, ON_OUT_ON = ON_OUT_ON_TAG, ON_ON_OUT = ON_ON_OUT_TAG,
ON_ON_ON = ON_ON_ON_TAG, IN_IN_IN = IN_IN_IN_TAG, OUT_OUT_OUT = OUT_OUT_OUT_TAG, IN_IN_ON = IN_IN_ON_TAG,
IN_ON_IN = IN_ON_IN_TAG, ON_IN_IN = ON_IN_IN_TAG, OUT_OUT_ON = OUT_OUT_ON_TAG, OUT_ON_OUT = OUT_ON_OUT_TAG,
ON_OUT_OUT = ON_OUT_OUT_TAG, IN_OUT_OUT = IN_OUT_OUT_TAG, OUT_IN_OUT = OUT_IN_OUT_TAG, OUT_OUT_IN = OUT_OUT_IN_TAG,
OUT_IN_IN = OUT_IN_IN_TAG, IN_OUT_IN = IN_OUT_IN_TAG, IN_IN_OUT = IN_IN_OUT_TAG, IN_ON_OUT = IN_ON_OUT_TAG,
IN_OUT_ON = IN_OUT_ON_TAG, ON_IN_OUT = ON_IN_OUT_TAG, ON_OUT_IN = ON_OUT_IN_TAG, OUT_IN_ON = OUT_IN_ON_TAG,
OUT_ON_IN = OUT_ON_IN_TAG
}
Functions
BOP_TAG BOP_createTAG (BOP_TAG tag1, BOP_TAG tag2, BOP_TAG tag3)
BOP_TAG BOP_createTAG (int i)
BOP_TAG BOP_addON (BOP_TAG tag)
void BOP_stringTAG (BOP_TAG tag, char *dest)
bool BOP_compTAG (BOP_TAG tag1, BOP_TAG tag2)
Detailed Description
Definition in file BOP_Tag.h.
Define Documentation
#define BROKEN_TAG 0x0B
Definition at line 49 of file BOP_Tag.h.
#define IN_IN_IN_TAG IN_ON_ON_TAG | ON_IN_ON_TAG | ON_ON_IN_TAG
Definition at line 60 of file BOP_Tag.h.
#define IN_IN_ON_TAG IN_ON_ON_TAG | ON_IN_ON_TAG
Definition at line 63 of file BOP_Tag.h.
#define IN_IN_OUT_TAG IN_IN_ON_TAG | ON_ON_OUT_TAG
Definition at line 77 of file BOP_Tag.h.
#define IN_ON_IN_TAG IN_ON_ON_TAG | ON_ON_IN_TAG
Definition at line 64 of file BOP_Tag.h.
#define IN_ON_ON_TAG IN_TAG << 4
Definition at line 53 of file BOP_Tag.h.
#define IN_ON_OUT_TAG IN_ON_ON_TAG | ON_ON_OUT_TAG
Definition at line 79 of file BOP_Tag.h.
#define IN_OUT_IN_TAG IN_ON_IN_TAG | ON_OUT_ON_TAG
Definition at line 76 of file BOP_Tag.h.
#define IN_OUT_ON_TAG IN_ON_ON_TAG | ON_OUT_ON_TAG
Definition at line 80 of file BOP_Tag.h.
#define IN_OUT_OUT_TAG IN_ON_ON_TAG | ON_OUT_OUT_TAG
Definition at line 71 of file BOP_Tag.h.
#define IN_TAG 0x02
Definition at line 39 of file BOP_Tag.h.
#define INON_TAG 0x12
Definition at line 43 of file BOP_Tag.h.
#define INOUT_TAG 0x0E
Definition at line 42 of file BOP_Tag.h.
#define ON_IN_IN_TAG ON_IN_ON_TAG | ON_ON_IN_TAG
Definition at line 65 of file BOP_Tag.h.
#define ON_IN_ON_TAG IN_TAG << 2
Definition at line 52 of file BOP_Tag.h.
#define ON_IN_OUT_TAG ON_IN_ON_TAG | ON_ON_OUT_TAG
Definition at line 81 of file BOP_Tag.h.
#define ON_ON_IN_TAG IN_TAG
Definition at line 51 of file BOP_Tag.h.
#define ON_ON_ON_TAG ON_TAG
Definition at line 59 of file BOP_Tag.h.
#define ON_ON_OUT_TAG OUT_TAG
Definition at line 55 of file BOP_Tag.h.
#define ON_OUT_IN_TAG ON_ON_IN_TAG | ON_OUT_ON_TAG
Definition at line 82 of file BOP_Tag.h.
#define ON_OUT_ON_TAG OUT_TAG << 2
Definition at line 56 of file BOP_Tag.h.
#define ON_OUT_OUT_TAG ON_OUT_ON_TAG | ON_ON_OUT_TAG
Definition at line 69 of file BOP_Tag.h.
#define ON_TAG 0x00
Definition at line 40 of file BOP_Tag.h.
#define OUT_IN_IN_TAG ON_IN_IN_TAG | OUT_ON_ON_TAG
Definition at line 75 of file BOP_Tag.h.
#define OUT_IN_ON_TAG ON_IN_ON_TAG | OUT_ON_ON_TAG
Definition at line 83 of file BOP_Tag.h.
#define OUT_IN_OUT_TAG ON_IN_ON_TAG | OUT_ON_OUT_TAG
Definition at line 72 of file BOP_Tag.h.
#define OUT_ON_IN_TAG ON_ON_IN_TAG | OUT_ON_ON_TAG
Definition at line 84 of file BOP_Tag.h.
#define OUT_ON_ON_TAG OUT_TAG << 4
Definition at line 57 of file BOP_Tag.h.
#define OUT_ON_OUT_TAG OUT_ON_ON_TAG | ON_ON_OUT_TAG
Definition at line 68 of file BOP_Tag.h.
#define OUT_OUT_IN_TAG ON_ON_IN_TAG | OUT_OUT_ON_TAG
Definition at line 73 of file BOP_Tag.h.
#define OUT_OUT_ON_TAG OUT_ON_ON_TAG | ON_OUT_ON_TAG
Definition at line 67 of file BOP_Tag.h.
#define OUT_OUT_OUT_TAG OUT_ON_ON_TAG | ON_OUT_ON_TAG | ON_ON_OUT_TAG
Definition at line 61 of file BOP_Tag.h.
#define OUT_TAG 0x01
Definition at line 41 of file BOP_Tag.h.
#define OUTON_TAG 0x11
Definition at line 44 of file BOP_Tag.h.
#define OVERLAPPED_TAG 0x0D
Definition at line 48 of file BOP_Tag.h.
#define PHANTOM_TAG 0x0C
Definition at line 47 of file BOP_Tag.h.
#define UNCLASSIFIED_TAG 0x0F
Definition at line 45 of file BOP_Tag.h.
Typedef Documentation
typedef enum BOP_TAGEnum BOP_TAG
Enumeration Type Documentation
enum BOP_TAGEnum
Enumerator:
IN
ON
OUT
INOUT
INON
OUTON
UNCLASSIFIED
PHANTOM
OVERLAPPED
BROKEN
IN_ON_ON
ON_IN_ON
ON_ON_IN
OUT_ON_ON
ON_OUT_ON
ON_ON_OUT
ON_ON_ON
IN_IN_IN
OUT_OUT_OUT
IN_IN_ON
IN_ON_IN
ON_IN_IN
OUT_OUT_ON
OUT_ON_OUT
ON_OUT_OUT
IN_OUT_OUT
OUT_IN_OUT
OUT_OUT_IN
OUT_IN_IN
IN_OUT_IN
IN_IN_OUT
IN_ON_OUT
IN_OUT_ON
ON_IN_OUT
ON_OUT_IN
OUT_IN_ON
OUT_ON_IN
Definition at line 86 of file BOP_Tag.h.
Function Documentation
BOP_TAG BOP_addON (BOP_TAG tag) [inline]
Definition at line 135 of file BOP_Tag.h.
References IN, INON, OUT, and OUTON.
Referenced by BOP_compTAG(), and BOP_BSPNode::classifyFace().
bool BOP_compTAG (BOP_TAG tag1, BOP_TAG tag2) [inline]
Definition at line 142 of file BOP_Tag.h.
References BOP_addON().
Referenced by BOP_BSPNode::classifyFace().
BOP_TAG BOP_createTAG (int i) [inline]
Definition at line 130 of file BOP_Tag.h.
References ON, and OUT.
BOP_TAG BOP_createTAG (BOP_TAG tag1, BOP_TAG tag2, BOP_TAG tag3) [inline]
Definition at line 125 of file BOP_Tag.h.
Referenced by BOP_overlap(), BOP_splitFace(), BOP_BSPNode::classifyFace(), BOP_BSPNode::simplifiedClassifyFace(), and BOP_BSPNode::testPoint().
void BOP_stringTAG (BOP_TAG t, char * dest)
Gets the tag description.
Parameters:
t tag
dest tag description
Definition at line 40 of file BOP_Tag.cpp.
References BROKEN, IN_IN_IN, IN_IN_ON, IN_IN_OUT, IN_ON_IN, IN_ON_ON, IN_ON_OUT, IN_OUT_IN, IN_OUT_ON, IN_OUT_OUT, INOUT, ON_IN_IN, ON_IN_ON, ON_IN_OUT, ON_ON_IN, ON_ON_ON, ON_ON_OUT, ON_OUT_IN, ON_OUT_ON, ON_OUT_OUT, OUT_IN_IN, OUT_IN_ON, OUT_IN_OUT, OUT_ON_IN, OUT_ON_ON, OUT_ON_OUT, OUT_OUT_IN, OUT_OUT_ON, OUT_OUT_OUT, OVERLAPPED, PHANTOM, and UNCLASSIFIED.