Blender: editmesh_bvh.h File Reference
editmesh_bvh.h File Reference
mesh
Defines
#define BM_SEARCH_MAXDIST 0.4f
Typedefs
typedef struct BMBVHTree BMBVHTree
Enumerations
enum { BMBVH_USE_CAGE = 1, BMBVH_RETURN_ORIG = 2, BMBVH_RESPECT_SELECT = 4, BMBVH_RESPECT_HIDDEN = 8 }
Functions
struct BMBVHTree * BMBVH_NewBVH (struct BMEditMesh *em, int flag, struct Scene *scene, struct Object *obedit)
void BMBVH_FreeBVH (struct BMBVHTree *tree)
struct BVHTree * BMBVH_BVHTree (struct BMBVHTree *tree)
struct BMFace * BMBVH_RayCast (struct BMBVHTree *tree, float *co, float *dir, float *hitout, float *cagehit)
int BMBVH_EdgeVisible (struct BMBVHTree *tree, struct BMEdge *e, struct ARegion *ar, struct View3D *v3d, struct Object *obedit)
struct BMVert * BMBVH_FindClosestVert (struct BMBVHTree *tree, float *co, float maxdist)
Detailed Description
Definition in file editmesh_bvh.h.
Define Documentation
#define BM_SEARCH_MAXDIST 0.4f
Definition at line 58 of file editmesh_bvh.h.
Typedef Documentation
typedef struct BMBVHTree BMBVHTree
Definition at line 46 of file editmesh_bvh.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
BMBVH_USE_CAGE
BMBVH_RETURN_ORIG
BMBVH_RESPECT_SELECT
BMBVH_RESPECT_HIDDEN
Definition at line 64 of file editmesh_bvh.h.
Function Documentation
struct BVHTree* BMBVH_BVHTree (struct BMBVHTree * tree) [read]
Definition at line 283 of file editmesh_bvh.c.
References BMBVHTree::tree.
Referenced by knife_edge_tri_isect().
int BMBVH_EdgeVisible (struct BMBVHTree * tree, struct BMEdge * e, struct ARegion * ar, struct View3D * v3d, struct Object * obedit)
Definition at line 390 of file editmesh_bvh.c.
References add_v3_v3v3(), BMVert::co, copy_v3_v3(), ED_view3d_win_to_segment_clip(), edge_ray_cast(), KDL::epsilon, invert_m4_m4(), mul_m4_v3(), mul_v3_fl(), normalize_v3(), NULL, Object::obmat, scale_point(), sub_v3_v3v3(), BMEdge::v1, BMEdge::v2, ARegion::winx, and ARegion::winy.
Referenced by createSlideVerts().
struct BMVert* BMBVH_FindClosestVert (struct BMBVHTree * tree, float * co, float maxdist) [read]
Definition at line 310 of file editmesh_bvh.c.
References BLI_bvhtree_find_nearest(), BMVert::co, BVHTreeNearest::co, copy_v3_v3(), BVHTreeNearest::dist, BMBVHTree::em, FLT_MAX, i, BVHTreeNearest::index, len_v3(), BMEditMesh::looptris, BMBVHTree::maxdist, NULL, sub_v3_v3v3(), BMBVHTree::tree, BMLoop::v, and vertsearchcallback().
Referenced by EDBM_verts_mirror_cache_begin().
void BMBVH_FreeBVH (struct BMBVHTree * tree)
Definition at line 191 of file editmesh_bvh.c.
References BLI_bvhtree_free(), BMBVHTree::cagecos, BMBVHTree::cos, MEM_freeN(), and BMBVHTree::tree.
Referenced by createSlideVerts(), EDBM_verts_mirror_cache_begin(), and knifetool_exit().
struct BMBVHTree* BMBVH_NewBVH (struct BMEditMesh * em, int flag, struct Scene * scene, struct Object * obedit) [read]
Definition at line 86 of file editmesh_bvh.c.
References BLI_bvhtree_balance(), BLI_bvhtree_insert(), BLI_bvhtree_new(), BLI_smallhash_init(), BLI_smallhash_release(), BMBVHTree::bm, BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_index_get, BM_elem_index_set, BM_ELEM_SELECT, BM_ITER_MESH_INDEX, BM_VERT, BM_VERTS_OF_MESH, BMBVH_RESPECT_HIDDEN, BMBVH_RESPECT_SELECT, BMBVH_USE_CAGE, BMEdit_RecalcTessellation(), cage_mapped_verts_callback(), BMBVHTree::cagecos, CD_MASK_DERIVEDMESH, BMVert::co, copy_v3_v3(), BMBVHTree::cos, cos(), data, editbmesh_get_derived_cage_and_final(), BMesh::elem_index_dirty, BMBVHTree::em, BMBVHTree::epsilon, BMLoop::f, BMBVHTree::flag, DerivedMesh::foreachMappedVert, i, BMEditMesh::looptris, MEM_callocN(), NULL, BMBVHTree::ob, BMBVHTree::scene, BMEditMesh::tottri, BMesh::totvert, BMBVHTree::tree, and BMLoop::v.
Referenced by createSlideVerts(), EDBM_verts_mirror_cache_begin(), and knifetool_init().
struct BMFace* BMBVH_RayCast (struct BMBVHTree * tree, float * co, float * dir, float * hitout, float * cagehit) [read]
Definition at line 242 of file editmesh_bvh.c.
References BLI_bvhtree_ray_cast(), BMBVH_RETURN_ORIG, BVHTreeRayHit::co, BMVert::co, copy_v3_v3(), BVHTreeRayHit::dist, BMBVHTree::em, BMLoop::f, BMBVHTree::flag, FLT_MAX, i, BVHTreeRayHit::index, BMEditMesh::looptris, NULL, raycallback(), BMBVHTree::tree, BMBVHTree::uv, and BMLoop::v.
Referenced by edge_ray_cast(), knife_edge_tri_isect(), and knife_find_closest_face().