Blender: indexer.c File Reference
indexer.c File Reference
#include "IMB_indexer.h"
#include "IMB_anim.h"
#include "AVI_avi.h"
#include "imbuf.h"
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_blenlib.h"
#include "BLI_math_base.h"
#include "DNA_userdef_types.h"
#include "BKE_global.h"
#include <stdlib.h>
Classes
struct IndexBuildContext
struct FallbackIndexBuilderContext
Defines
#define INDEX_FILE_VERSION 1
Typedefs
typedef struct IndexBuildContext IndexBuildContext
typedef struct
FallbackIndexBuilderContext FallbackIndexBuilderContext
Functions
anim_index_builder * IMB_index_builder_create (const char *name)
void IMB_index_builder_add_entry (anim_index_builder *fp, int frameno, unsigned long long seek_pos, unsigned long long seek_pos_dts, unsigned long long pts)
void IMB_index_builder_proc_frame (anim_index_builder *fp, unsigned char *buffer, int data_size, int frameno, unsigned long long seek_pos, unsigned long long seek_pos_dts, unsigned long long pts)
void IMB_index_builder_finish (anim_index_builder *fp, int rollback)
struct anim_index * IMB_indexer_open (const char *name)
unsigned long long IMB_indexer_get_seek_pos (struct anim_index *idx, int frame_index)
unsigned long long IMB_indexer_get_seek_pos_dts (struct anim_index *idx, int frame_index)
int IMB_indexer_get_frame_index (struct anim_index *idx, int frameno)
unsigned long long IMB_indexer_get_pts (struct anim_index *idx, int frame_index)
int IMB_indexer_get_duration (struct anim_index *idx)
int IMB_indexer_can_scan (struct anim_index *idx, int old_frame_index, int new_frame_index)
void IMB_indexer_close (struct anim_index *idx)
int IMB_proxy_size_to_array_index (IMB_Proxy_Size pr_size)
int IMB_timecode_to_array_index (IMB_Timecode_Type tc)
static void get_index_dir (struct anim *anim, char *index_dir)
static void get_proxy_filename (struct anim *anim, IMB_Proxy_Size preview_size, char *fname, int temp)
static void get_tc_filename (struct anim *anim, IMB_Timecode_Type tc, char *fname)
static AviMovie * alloc_proxy_output_avi (struct anim *anim, char *filename, int width, int height, int quality)
static IndexBuildContext * index_fallback_create_context (struct anim *anim, IMB_Timecode_Type UNUSED(tcs_in_use), IMB_Proxy_Size proxy_sizes_in_use, int quality)
static void index_rebuild_fallback_finish (FallbackIndexBuilderContext *context, int stop)
static void index_rebuild_fallback (FallbackIndexBuilderContext *context, short *stop, short *do_update, float *progress)
IndexBuildContext * IMB_anim_index_rebuild_context (struct anim *anim, IMB_Timecode_Type tcs_in_use, IMB_Proxy_Size proxy_sizes_in_use, int quality)
void IMB_anim_index_rebuild (struct IndexBuildContext *context, short *stop, short *do_update, float *progress)
void IMB_anim_index_rebuild_finish (IndexBuildContext *context, short stop)
void IMB_free_indices (struct anim *anim)
void IMB_anim_set_index_dir (struct anim *anim, const char *dir)
struct anim * IMB_anim_open_proxy (struct anim *anim, IMB_Proxy_Size preview_size)
struct anim_index * IMB_anim_open_index (struct anim *anim, IMB_Timecode_Type tc)
int IMB_anim_index_get_frame_index (struct anim *anim, IMB_Timecode_Type tc, int position)
Variables
static char magic [] = "BlenMIdx"
static char temp_ext [] = "_part"
static int proxy_sizes []
static float proxy_fac [] = { 0.25, 0.50, 0.75, 1.00 }
Define Documentation
#define INDEX_FILE_VERSION 1
Definition at line 62 of file indexer.c.
Referenced by IMB_index_builder_create(), and IMB_indexer_open().
Typedef Documentation
typedef struct FallbackIndexBuilderContext FallbackIndexBuilderContext
typedef struct IndexBuildContext IndexBuildContext
Function Documentation
static AviMovie* alloc_proxy_output_avi (struct anim * anim, char * filename, int width, int height, int quality) [static]
Definition at line 966 of file indexer.c.
References avi, AVI_ERROR_NONE, AVI_FORMAT_MJPEG, AVI_open_compress(), AVI_OPTION_FRAMERATE, AVI_OPTION_HEIGHT, AVI_OPTION_QUALITY, AVI_OPTION_TYPE_MAIN, AVI_OPTION_WIDTH, AVI_set_compress_option(), anim::frs_sec, anim::frs_sec_base, IMB_anim_get_fps(), _AviMovie::interlace, MEM_freeN(), MEM_mallocN(), NULL, _AviMovie::odd_fields, anim::x, and anim::y.
Referenced by index_fallback_create_context().
static void get_index_dir (struct anim * anim, char * index_dir) [static]
Definition at line 360 of file indexer.c.
References BLI_join_dirfile(), BLI_splitdirstring(), BLI_strncpy(), FILE_MAXDIR, FILE_MAXFILE, anim::index_dir, and anim::name.
Referenced by get_proxy_filename(), and get_tc_filename().
static void get_proxy_filename (struct anim * anim, IMB_Proxy_Size preview_size, char * fname, int temp) [static]
Definition at line 374 of file indexer.c.
References BLI_join_dirfile(), BLI_snprintf(), FILE_MAXDIR, FILE_MAXFILE, get_index_dir(), i, IMB_proxy_size_to_array_index(), proxy_fac, and anim::streamindex.
Referenced by IMB_anim_open_proxy(), index_fallback_create_context(), and index_rebuild_fallback_finish().
static void get_tc_filename (struct anim * anim, IMB_Timecode_Type tc, char * fname) [static]
Definition at line 401 of file indexer.c.
References BLI_join_dirfile(), BLI_snprintf(), FILE_MAXDIR, FILE_MAXFILE, get_index_dir(), i, IMB_timecode_to_array_index(), and anim::streamindex.
Referenced by IMB_anim_open_index().
int IMB_anim_index_get_frame_index (struct anim * anim, IMB_Timecode_Type tc, int position)
Definition at line 1253 of file indexer.c.
References IMB_anim_open_index(), and IMB_indexer_get_frame_index().
Referenced by IMB_anim_absolute(), and seq_proxy_fetch().
void IMB_anim_index_rebuild (struct IndexBuildContext * context, short * stop, short * do_update, float * progress)
Definition at line 1144 of file indexer.c.
References ANIM_FFMPEG, IndexBuildContext::anim_type, and index_rebuild_fallback().
Referenced by proxy_startjob(), and seq_proxy_rebuild().
IndexBuildContext* IMB_anim_index_rebuild_context (struct anim * anim, IMB_Timecode_Type tcs_in_use, IMB_Proxy_Size proxy_sizes_in_use, int quality) [read]
Definition at line 1122 of file indexer.c.
References ANIM_FFMPEG, IndexBuildContext::anim_type, anim::curtype, index_fallback_create_context(), and NULL.
Referenced by clip_rebuild_proxy_exec(), and seq_proxy_rebuild_context().
void IMB_anim_index_rebuild_finish (IndexBuildContext * context, short stop)
Definition at line 1159 of file indexer.c.
References ANIM_FFMPEG, IndexBuildContext::anim_type, and index_rebuild_fallback_finish().
Referenced by proxy_endjob(), and seq_proxy_rebuild_finish().
struct anim_index* IMB_anim_open_index (struct anim * anim, IMB_Timecode_Type tc) [read]
Definition at line 1230 of file indexer.c.
References anim::curr_idx, FILE_MAX, get_tc_filename(), i, IMB_indexer_open(), IMB_timecode_to_array_index(), anim::indices_tried, and NULL.
Referenced by avi_fetchibuf(), IMB_anim_get_duration(), and IMB_anim_index_get_frame_index().
struct anim* IMB_anim_open_proxy (struct anim * anim, IMB_Proxy_Size preview_size) [read]
Definition at line 1207 of file indexer.c.
References FALSE, FILE_MAX, get_proxy_filename(), i, IMB_open_anim(), IMB_proxy_size_to_array_index(), NULL, anim::proxies_tried, and anim::proxy_anim.
Referenced by IMB_anim_absolute().
void IMB_anim_set_index_dir (struct anim * anim, const char * dir)
Definition at line 1197 of file indexer.c.
References BLI_strncpy(), IMB_free_indices(), and anim::index_dir.
Referenced by movieclip_open_anim_file(), and seq_open_anim_file().
void IMB_free_indices (struct anim * anim)
Definition at line 1174 of file indexer.c.
References anim::curr_idx, i, IMB_close_anim(), IMB_indexer_close(), IMB_PROXY_MAX_SLOT, IMB_TC_MAX_SLOT, anim::indices_tried, NULL, anim::proxies_tried, and anim::proxy_anim.
Referenced by IMB_anim_set_index_dir(), IMB_close_anim_proxies(), and IMB_free_anim().
void IMB_index_builder_add_entry (anim_index_builder * fp, int frameno, unsigned long long seek_pos, unsigned long long seek_pos_dts, unsigned long long pts)
Definition at line 99 of file indexer.c.
References anim_index_builder::fp.
Referenced by IMB_index_builder_proc_frame(), and write_index().
anim_index_builder* IMB_index_builder_create (const char * name)
Definition at line 68 of file indexer.c.
References B_ENDIAN, BLI_fopen(), BLI_make_existing_file(), BLI_strncpy(), ENDIAN_ORDER, anim_index_builder::fp, INDEX_FILE_VERSION, magic, MEM_callocN(), MEM_freeN(), anim_index_builder::name, NULL, temp_ext, and anim_index_builder::temp_name.
void IMB_index_builder_finish (anim_index_builder * fp, int rollback)
Definition at line 132 of file indexer.c.
References BLI_rename(), anim_index_builder::delete_priv_data, anim_index_builder::fp, MEM_freeN(), anim_index_builder::name, and anim_index_builder::temp_name.
void IMB_index_builder_proc_frame (anim_index_builder * fp, unsigned char * buffer, int data_size, int frameno, unsigned long long seek_pos, unsigned long long seek_pos_dts, unsigned long long pts)
Definition at line 110 of file indexer.c.
References anim_index_entry::frameno, IMB_index_builder_add_entry(), anim_index_builder::proc_frame, anim_index_entry::pts, anim_index_entry::seek_pos, and anim_index_entry::seek_pos_dts.
int IMB_indexer_can_scan (struct anim_index * idx, int old_frame_index, int new_frame_index)
Definition at line 299 of file indexer.c.
References IMB_indexer_get_seek_pos().
Referenced by avi_fetchibuf().
void IMB_indexer_close (struct anim_index * idx)
Definition at line 309 of file indexer.c.
References anim_index::entries, and MEM_freeN().
Referenced by IMB_free_indices().
int IMB_indexer_get_duration (struct anim_index * idx)
Definition at line 291 of file indexer.c.
References anim_index::entries, anim_index_entry::frameno, and anim_index::num_entries.
Referenced by IMB_anim_get_duration().
int IMB_indexer_get_frame_index (struct anim_index * idx, int frameno)
Definition at line 246 of file indexer.c.
References anim_index::entries, anim_index_entry::frameno, len(), and anim_index::num_entries.
Referenced by avi_fetchibuf(), and IMB_anim_index_get_frame_index().
unsigned long long IMB_indexer_get_pts (struct anim_index * idx, int frame_index)
Definition at line 279 of file indexer.c.
References anim_index::entries, anim_index::num_entries, and anim_index_entry::pts.
Referenced by avi_fetchibuf().
unsigned long long IMB_indexer_get_seek_pos (struct anim_index * idx, int frame_index)
Definition at line 222 of file indexer.c.
References anim_index::entries, anim_index::num_entries, and anim_index_entry::seek_pos.
Referenced by avi_fetchibuf(), and IMB_indexer_can_scan().
unsigned long long IMB_indexer_get_seek_pos_dts (struct anim_index * idx, int frame_index)
Definition at line 234 of file indexer.c.
References anim_index::entries, anim_index::num_entries, and anim_index_entry::seek_pos_dts.
Referenced by avi_fetchibuf().
struct anim_index* IMB_indexer_open (const char * name) [read]
Definition at line 151 of file indexer.c.
References B_ENDIAN, BLI_fopen(), BLI_strncpy(), ENDIAN_ORDER, anim_index::entries, anim_index_entry::frameno, fseek, ftell, i, INDEX_FILE_VERSION, magic, MEM_callocN(), anim_index::name, NULL, anim_index::num_entries, anim_index_entry::pts, anim_index_entry::seek_pos, anim_index_entry::seek_pos_dts, SWITCH_INT, and SWITCH_INT64.
Referenced by IMB_anim_open_index().
int IMB_proxy_size_to_array_index (IMB_Proxy_Size pr_size)
Definition at line 315 of file indexer.c.
References IMB_PROXY_100, IMB_PROXY_25, IMB_PROXY_50, IMB_PROXY_75, and IMB_PROXY_NONE.
Referenced by get_proxy_filename(), and IMB_anim_open_proxy().
int IMB_timecode_to_array_index (IMB_Timecode_Type tc)
Definition at line 335 of file indexer.c.
References IMB_TC_FREE_RUN, IMB_TC_INTERPOLATED_REC_DATE_FREE_RUN, IMB_TC_NONE, IMB_TC_RECORD_RUN, and IMB_TC_RECORD_RUN_NO_GAPS.
Referenced by get_tc_filename(), and IMB_anim_open_index().
static IndexBuildContext* index_fallback_create_context (struct anim * anim, IMB_Timecode_Type UNUSEDtcs_in_use, IMB_Proxy_Size proxy_sizes_in_use, int quality) [static]
Definition at line 1005 of file indexer.c.
References alloc_proxy_output_avi(), FallbackIndexBuilderContext::anim, BLI_make_existing_file(), FILE_MAX, get_proxy_filename(), i, IMB_PROXY_MAX_SLOT, IMB_PROXY_NONE, MEM_callocN(), NULL, FallbackIndexBuilderContext::proxy_ctx, proxy_fac, proxy_sizes, FallbackIndexBuilderContext::proxy_sizes_in_use, TRUE, anim::x, and anim::y.
Referenced by IMB_anim_index_rebuild_context().
static void index_rebuild_fallback (FallbackIndexBuilderContext * context, short * stop, short * do_update, float * progress) [static]
Definition at line 1068 of file indexer.c.
References FallbackIndexBuilderContext::anim, AVI_FORMAT_RGB32, AVI_write_frame(), i, IMB_anim_absolute(), IMB_anim_get_duration(), IMB_convert_rgba_to_abgr(), IMB_dupImBuf(), IMB_flipy(), IMB_freeImBuf(), IMB_PROXY_MAX_SLOT, IMB_PROXY_NONE, IMB_scalefastImBuf(), IMB_TC_NONE, NULL, FallbackIndexBuilderContext::proxy_ctx, proxy_fac, proxy_sizes, FallbackIndexBuilderContext::proxy_sizes_in_use, ImBuf::rect, ImBuf::x, anim::x, ImBuf::y, and anim::y.
Referenced by IMB_anim_index_rebuild().
static void index_rebuild_fallback_finish (FallbackIndexBuilderContext * context, int stop) [static]
Definition at line 1042 of file indexer.c.
References FallbackIndexBuilderContext::anim, AVI_close_compress(), FALSE, FILE_MAX, get_proxy_filename(), i, IMB_PROXY_MAX_SLOT, MEM_freeN(), FallbackIndexBuilderContext::proxy_ctx, proxy_sizes, FallbackIndexBuilderContext::proxy_sizes_in_use, and TRUE.
Referenced by IMB_anim_index_rebuild_finish().
Variable Documentation
char magic[] = "BlenMIdx" [static]
Definition at line 47 of file indexer.c.
Referenced by add_node(), IMB_index_builder_create(), IMB_indexer_open(), logImageDump(), and xml_read_shader_graph().
float proxy_fac[] = { 0.25, 0.50, 0.75, 1.00 } [static]
Definition at line 52 of file indexer.c.
Referenced by get_proxy_filename(), index_fallback_create_context(), and index_rebuild_fallback().
int proxy_sizes[] [static]
Initial value:
 { IMB_PROXY_25, IMB_PROXY_50, IMB_PROXY_75,
                             IMB_PROXY_100 }
Definition at line 50 of file indexer.c.
Referenced by index_fallback_create_context(), index_rebuild_fallback(), and index_rebuild_fallback_finish().
char temp_ext[] = "_part" [static]
Definition at line 48 of file indexer.c.
Referenced by IMB_index_builder_create().