Blender: btSoftBody::RayFromToCaster Struct Reference
btSoftBody::RayFromToCaster Struct Reference
RayFromToCaster takes a ray from, ray to (instead of direction!)
#include <btSoftBody.h>
Public Member Functions
RayFromToCaster (const btVector3 &rayFrom, const btVector3 &rayTo, btScalar mxt)
void Process (const btDbvtNode *leaf)
Static Public Member Functions
static btScalar rayFromToTriangle (const btVector3 &rayFrom, const btVector3 &rayTo, const btVector3 &rayNormalizedDirection, const btVector3 &a, const btVector3 &b, const btVector3 &c, btScalar maxt=SIMD_INFINITY)
Public Attributes
btVector3 m_rayFrom
btVector3 m_rayTo
btVector3 m_rayNormalizedDirection
btScalar m_mint
Face * m_face
int m_tests
Detailed Description
RayFromToCaster takes a ray from, ray to (instead of direction!)
Definition at line 598 of file btSoftBody.h.
Constructor & Destructor Documentation
btSoftBody::RayFromToCaster::RayFromToCaster (const btVector3 & rayFrom, const btVector3 & rayTo, btScalar mxt)
Definition at line 1760 of file btSoftBody.cpp.
References m_face, m_mint, m_rayFrom, m_rayNormalizedDirection, m_rayTo, and m_tests.
Member Function Documentation
void btSoftBody::RayFromToCaster::Process (const btDbvtNode * leaf)
Reimplemented from btDbvt::ICollide.
Definition at line 1771 of file btSoftBody.cpp.
References btDbvtNode::data, btSoftBody::Face::m_n, and btSoftBody::Node::m_x.
btScalar btSoftBody::RayFromToCaster::rayFromToTriangle (const btVector3 & rayFrom, const btVector3 & rayTo, const btVector3 & rayNormalizedDirection, const btVector3 & a, const btVector3 & b, const btVector3 & c, btScalar maxt = SIMD_INFINITY) [inline, static]
Definition at line 1787 of file btSoftBody.cpp.
References btCross(), btDot(), btFuzzyZero(), and SIMD_EPSILON.
Referenced by btSoftBody::rayTest().
Member Data Documentation
Face* btSoftBody::RayFromToCaster::m_face
Definition at line 604 of file btSoftBody.h.
Referenced by RayFromToCaster(), and btSoftBody::rayTest().
btScalar btSoftBody::RayFromToCaster::m_mint
Definition at line 603 of file btSoftBody.h.
Referenced by RayFromToCaster(), and btSoftBody::rayTest().
btVector3 btSoftBody::RayFromToCaster::m_rayFrom
Definition at line 600 of file btSoftBody.h.
Referenced by RayFromToCaster().
btVector3 btSoftBody::RayFromToCaster::m_rayNormalizedDirection
Definition at line 602 of file btSoftBody.h.
Referenced by RayFromToCaster().
btVector3 btSoftBody::RayFromToCaster::m_rayTo
Definition at line 601 of file btSoftBody.h.
Referenced by RayFromToCaster().
int btSoftBody::RayFromToCaster::m_tests
Definition at line 605 of file btSoftBody.h.
Referenced by RayFromToCaster().
The documentation for this struct was generated from the following files:
btSoftBody.h
btSoftBody.cpp