Blender: CcdGraphicController Class Reference
CcdGraphicController Class Reference
CcdGraphicController is a graphic object that supports view frustrum culling and occlusion.
#include <CcdGraphicController.h>
Public Member Functions
CcdGraphicController (CcdPhysicsEnvironment *phyEnv, PHY_IMotionState *motionState)
virtual ~CcdGraphicController ()
void setLocalAabb (const btVector3 &aabbMin, const btVector3 &aabbMax)
void setLocalAabb (const MT_Point3 &aabbMin, const MT_Point3 &aabbMax)
virtual void setLocalAabb (const PHY__Vector3 &aabbMin, const PHY__Vector3 &aabbMax)
virtual void setLocalAabb (const float aabbMin[3], const float aabbMax[3])
PHY_IMotionState * GetMotionState ()
void getAabb (btVector3 &aabbMin, btVector3 &aabbMax)
virtual void setBroadphaseHandle (btBroadphaseProxy *handle)
virtual btBroadphaseProxy * getBroadphaseHandle ()
virtual void SetPhysicsEnvironment (class PHY_IPhysicsEnvironment *env)
virtual bool SetGraphicTransform ()
virtual void Activate (bool active)
virtual void * getNewClientInfo ()
virtual void setNewClientInfo (void *clientinfo)
virtual PHY_IGraphicController * GetReplica (class PHY_IMotionState *motionstate)
Detailed Description
CcdGraphicController is a graphic object that supports view frustrum culling and occlusion.
Definition at line 36 of file CcdGraphicController.h.
Constructor & Destructor Documentation
CcdGraphicController::CcdGraphicController (CcdPhysicsEnvironment * phyEnv, PHY_IMotionState * motionState)
Definition at line 25 of file CcdGraphicController.cpp.
Referenced by GetReplica().
CcdGraphicController::~CcdGraphicController () [virtual]
Definition at line 35 of file CcdGraphicController.cpp.
References CcdPhysicsEnvironment::removeCcdGraphicController().
Member Function Documentation
void CcdGraphicController::Activate (bool active) [virtual]
Add/remove to environment
Implements PHY_IGraphicController.
Definition at line 145 of file CcdGraphicController.cpp.
References CcdPhysicsEnvironment::addCcdGraphicController(), and CcdPhysicsEnvironment::removeCcdGraphicController().
Referenced by SetPhysicsEnvironment().
void CcdGraphicController::getAabb (btVector3 & aabbMin, btVector3 & aabbMax)
Definition at line 72 of file CcdGraphicController.cpp.
References btMatrix3x3::absolute(), PHY_IMotionState::getWorldOrientation(), PHY_IMotionState::getWorldPosition(), PHY_IMotionState::getWorldScaling(), and rot.
Referenced by CcdPhysicsEnvironment::addCcdGraphicController(), and SetGraphicTransform().
virtual btBroadphaseProxy* CcdGraphicController::getBroadphaseHandle () [inline, virtual]
Definition at line 52 of file CcdGraphicController.h.
Referenced by CcdPhysicsEnvironment::addCcdGraphicController(), CcdPhysicsEnvironment::removeCcdGraphicController(), and SetPhysicsEnvironment().
PHY_IMotionState* CcdGraphicController::GetMotionState () [inline]
Definition at line 48 of file CcdGraphicController.h.
virtual void* CcdGraphicController::getNewClientInfo () [inline, virtual]
Implements PHY_IController.
Definition at line 70 of file CcdGraphicController.h.
PHY_IGraphicController * CcdGraphicController::GetReplica (class PHY_IMotionState * motionstate) [virtual]
Reimplemented from PHY_IGraphicController.
Definition at line 118 of file CcdGraphicController.cpp.
References CcdGraphicController(), and NULL.
virtual void CcdGraphicController::setBroadphaseHandle (btBroadphaseProxy * handle) [inline, virtual]
Definition at line 51 of file CcdGraphicController.h.
Referenced by CcdPhysicsEnvironment::addCcdGraphicController(), and CcdPhysicsEnvironment::removeCcdGraphicController().
bool CcdGraphicController::SetGraphicTransform () [virtual]
Updates the Aabb based on the motion state
Implements PHY_IGraphicController.
Definition at line 106 of file CcdGraphicController.cpp.
References getAabb(), CcdPhysicsEnvironment::getCullingTree(), NULL, and btDbvtBroadphase::setAabb().
Referenced by setLocalAabb().
virtual void CcdGraphicController::setLocalAabb (const float aabbMin[3], const float aabbMax[3]) [virtual]
void CcdGraphicController::setLocalAabb (const PHY__Vector3 & aabbMin, const PHY__Vector3 & aabbMax) [virtual]
Implements PHY_IGraphicController.
Definition at line 58 of file CcdGraphicController.cpp.
References SetGraphicTransform().
void CcdGraphicController::setLocalAabb (const btVector3 & aabbMin, const btVector3 & aabbMax)
Definition at line 44 of file CcdGraphicController.cpp.
References SetGraphicTransform().
void CcdGraphicController::setLocalAabb (const MT_Point3 & aabbMin, const MT_Point3 & aabbMax)
Definition at line 51 of file CcdGraphicController.cpp.
References SetGraphicTransform().
virtual void CcdGraphicController::setNewClientInfo (void * clientinfo) [inline, virtual]
Implements PHY_IController.
Definition at line 71 of file CcdGraphicController.h.
void CcdGraphicController::SetPhysicsEnvironment (class PHY_IPhysicsEnvironment * env) [virtual]
Implements PHY_IController.
Definition at line 130 of file CcdGraphicController.cpp.
References Activate(), and getBroadphaseHandle().
The documentation for this class was generated from the following files:
CcdGraphicController.h
CcdGraphicController.cpp