Blender: btPolyhedralConvexAabbCachingShape Class Reference
btPolyhedralConvexAabbCachingShape Class Reference
The btPolyhedralConvexAabbCachingShape adds aabb caching to the btPolyhedralConvexShape.
#include <btPolyhedralConvexShape.h>
Public Member Functions
btPolyhedralConvexAabbCachingShape ()
void getNonvirtualAabb (const btTransform &trans, btVector3 &aabbMin, btVector3 &aabbMax, btScalar margin) const
virtual void setLocalScaling (const btVector3 &scaling)
virtual void getAabb (const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const
getAabb's default implementation is brute force, expected derived classes to implement a fast dedicated version
void recalcLocalAabb ()
Protected Member Functions
void setCachedLocalAabb (const btVector3 &aabbMin, const btVector3 &aabbMax)
void getCachedLocalAabb (btVector3 &aabbMin, btVector3 &aabbMax) const
Detailed Description
The btPolyhedralConvexAabbCachingShape adds aabb caching to the btPolyhedralConvexShape.
Definition at line 55 of file btPolyhedralConvexShape.h.
Constructor & Destructor Documentation
btPolyhedralConvexAabbCachingShape::btPolyhedralConvexAabbCachingShape ()
Definition at line 133 of file btPolyhedralConvexShape.cpp.
Member Function Documentation
void btPolyhedralConvexAabbCachingShape::getAabb (const btTransform & t, btVector3 & aabbMin, btVector3 & aabbMax) const [virtual]
getAabb's default implementation is brute force, expected derived classes to implement a fast dedicated version
Reimplemented from btConvexInternalShape.
Reimplemented in btBU_Simplex1to4.
Definition at line 141 of file btPolyhedralConvexShape.cpp.
References btConvexInternalShape::getMargin(), and getNonvirtualAabb().
void btPolyhedralConvexAabbCachingShape::getCachedLocalAabb (btVector3 & aabbMin, btVector3 & aabbMax) const [inline, protected]
Definition at line 71 of file btPolyhedralConvexShape.h.
References btAssert.
void btPolyhedralConvexAabbCachingShape::getNonvirtualAabb (const btTransform & trans, btVector3 & aabbMin, btVector3 & aabbMax, btScalar margin) const [inline]
Definition at line 82 of file btPolyhedralConvexShape.h.
References btAssert, and btTransformAabb().
Referenced by getAabb().
void btPolyhedralConvexAabbCachingShape::recalcLocalAabb ()
Definition at line 146 of file btPolyhedralConvexShape.cpp.
References btPolyhedralConvexShape::batchedUnitVectorGetSupportingVertexWithoutMargin(), i, btConvexInternalShape::localGetSupportingVertex(), and btConvexInternalShape::m_collisionMargin.
Referenced by btBU_Simplex1to4::addVertex(), btConvexTriangleMeshShape::btConvexTriangleMeshShape(), setLocalScaling(), btConvexTriangleMeshShape::setLocalScaling(), and btTetrahedronShapeEx::setVertices().
void btPolyhedralConvexAabbCachingShape::setCachedLocalAabb (const btVector3 & aabbMin, const btVector3 & aabbMax) [inline, protected]
Definition at line 64 of file btPolyhedralConvexShape.h.
void btPolyhedralConvexAabbCachingShape::setLocalScaling (const btVector3 & scaling) [virtual]
Reimplemented from btConvexInternalShape.
Reimplemented in btConvexTriangleMeshShape.
Definition at line 127 of file btPolyhedralConvexShape.cpp.
References recalcLocalAabb().
The documentation for this class was generated from the following files:
btPolyhedralConvexShape.h
btPolyhedralConvexShape.cpp