Blender: KX_FontObject Class Reference
KX_FontObject Class Reference
#include <KX_FontObject.h>
Public Member Functions
Py_Header KX_FontObject (void *sgReplicationInfo, SG_Callbacks callbacks, RAS_IRenderTools *rendertools, Object *ob)
virtual ~KX_FontObject ()
void DrawText ()
virtual CValue * GetReplica ()
virtual void ProcessReplica ()
Protected Attributes
std::vector< STR_String > m_text
Object * m_object
int m_fontid
int m_dpi
float m_fsize
float m_resolution
float m_color [4]
float m_line_spacing
MT_Vector3 m_offset
class RAS_IRenderTools * m_rendertools
Detailed Description
Definition at line 38 of file KX_FontObject.h.
Constructor & Destructor Documentation
KX_FontObject::KX_FontObject (void * sgReplicationInfo, SG_Callbacks callbacks, RAS_IRenderTools * rendertools, Object * ob)
Definition at line 76 of file KX_FontObject.cpp.
References Object::col, copy_v4_v4(), Object::data, Curve::fsize, GetFontId(), Curve::linedist, m_color, m_fontid, m_fsize, m_line_spacing, m_offset, m_text, KX_GameObject::SetObjectColor(), split_string(), Curve::str, Curve::vfont, Curve::xof, and Curve::yof.
Referenced by GetReplica().
KX_FontObject::~KX_FontObject () [virtual]
Definition at line 101 of file KX_FontObject.cpp.
Member Function Documentation
void KX_FontObject::DrawText ()
Definition at line 165 of file KX_FontObject.cpp.
References BGE_FONT_RES, KX_GameObject::GetObjectColor(), KX_GameObject::GetOpenGLMatrix(), CValue::GetProperty(), KX_GameObject::GetText(), MT_Tuple4::getValue(), KX_GameObject::GetVisible(), i, m_color, m_dpi, m_fontid, m_fsize, m_line_spacing, m_offset, m_rendertools, m_resolution, m_text, KX_GameObject::NodeGetWorldOrientation(), KX_GameObject::NodeGetWorldScaling(), RAS_IRenderTools::RenderText3D(), RES, size(), and split_string().
CValue * KX_FontObject::GetReplica (void) [virtual]
Inherited from CValue -- return a new copy of this instance allocated on the heap. Ownership of the new object belongs with the caller.
Reimplemented from KX_GameObject.
Definition at line 107 of file KX_FontObject.cpp.
References KX_FontObject(), and ProcessReplica().
void KX_FontObject::ProcessReplica () [virtual]
Inherited from CValue -- Makes sure any internal data owned by this class is deep copied. Called internally
Reimplemented from KX_GameObject.
Definition at line 114 of file KX_FontObject.cpp.
References KX_Scene::AddFont(), and KX_GetActiveScene().
Referenced by GetReplica().
Member Data Documentation
float KX_FontObject::m_color[4] [protected]
Definition at line 66 of file KX_FontObject.h.
Referenced by DrawText(), and KX_FontObject().
int KX_FontObject::m_dpi [protected]
Definition at line 63 of file KX_FontObject.h.
Referenced by DrawText().
int KX_FontObject::m_fontid [protected]
Definition at line 62 of file KX_FontObject.h.
Referenced by DrawText(), and KX_FontObject().
float KX_FontObject::m_fsize [protected]
Definition at line 64 of file KX_FontObject.h.
Referenced by DrawText(), and KX_FontObject().
float KX_FontObject::m_line_spacing [protected]
Definition at line 67 of file KX_FontObject.h.
Referenced by DrawText(), and KX_FontObject().
Object* KX_FontObject::m_object [protected]
Definition at line 61 of file KX_FontObject.h.
MT_Vector3 KX_FontObject::m_offset [protected]
Definition at line 68 of file KX_FontObject.h.
Referenced by DrawText(), and KX_FontObject().
class RAS_IRenderTools* KX_FontObject::m_rendertools [protected]
Definition at line 70 of file KX_FontObject.h.
Referenced by DrawText().
float KX_FontObject::m_resolution [protected]
Definition at line 65 of file KX_FontObject.h.
Referenced by DrawText().
std::vector<STR_String> KX_FontObject::m_text [protected]
Reimplemented from KX_GameObject.
Definition at line 60 of file KX_FontObject.h.
Referenced by DrawText(), and KX_FontObject().
The documentation for this class was generated from the following files:
KX_FontObject.h
KX_FontObject.cpp