Blender: KX_SteeringActuator.cpp File Reference
KX_SteeringActuator.cpp File Reference
#include "BLI_math.h"
#include "KX_SteeringActuator.h"
#include "KX_GameObject.h"
#include "KX_NavMeshObject.h"
#include "KX_ObstacleSimulation.h"
#include "KX_PythonInit.h"
#include "KX_PyMath.h"
#include "Recast.h"
Functions
float vdot2 (const float *a, const float *b)
static bool barDistSqPointToTri (const float *p, const float *a, const float *b, const float *c)
void flipAxes (float *vec)
static bool getNavmeshNormal (dtStatNavMesh *navmesh, const MT_Vector3 &pos, MT_Vector3 &normal)
Function Documentation
static bool barDistSqPointToTri (const float * p, const float * a, const float * b, const float * c) [static]
Definition at line 327 of file KX_SteeringActuator.cpp.
References vdot2().
Referenced by getNavmeshNormal().
void flipAxes (float * vec) [inline]
Definition at line 350 of file KX_SteeringActuator.cpp.
References swap().
static bool getNavmeshNormal (dtStatNavMesh * navmesh, const MT_Vector3 & pos, MT_Vector3 & normal) [static]
Definition at line 355 of file KX_SteeringActuator.cpp.
References barDistSqPointToTri(), MT_Vector3::cross(), flipAxes(), FLT_MAX, MT_Tuple3::getValue(), i, p, polyPickExt, and MT_Vector3::safe_normalized().
float vdot2 (const float * a, const float * b) [inline]
Definition at line 323 of file KX_SteeringActuator.cpp.
Referenced by barDistSqPointToTri().