Blender: SCA_KeyboardManager Class Reference
SCA_KeyboardManager Class Reference
#include <SCA_KeyboardManager.h>
Public Member Functions
SCA_KeyboardManager (class SCA_LogicManager *logicmgr, class SCA_IInputDevice *inputdev)
virtual ~SCA_KeyboardManager ()
bool IsPressed (SCA_IInputDevice::KX_EnumInputs inputcode)
virtual void NextFrame ()
SCA_IInputDevice * GetInputDevice ()
SCA_KeyboardManager (class SCA_LogicManager *logicmgr, class SCA_IInputDevice *inputdev)
virtual ~SCA_KeyboardManager ()
bool IsPressed (SCA_IInputDevice::KX_EnumInputs inputcode)
virtual void NextFrame ()
SCA_IInputDevice * GetInputDevice ()
SCA_KeyboardManager (class SCA_LogicManager *logicmgr, class SCA_IInputDevice *inputdev)
virtual ~SCA_KeyboardManager ()
bool IsPressed (SCA_IInputDevice::KX_EnumInputs inputcode)
virtual void NextFrame ()
SCA_IInputDevice * GetInputDevice ()
Detailed Description
Definition at line 47 of file SCA_KeyboardManager.h.
Constructor & Destructor Documentation
SCA_KeyboardManager::SCA_KeyboardManager (class SCA_LogicManager * logicmgr, class SCA_IInputDevice * inputdev)
Definition at line 42 of file SCA_KeyboardManager.cpp.
SCA_KeyboardManager::~SCA_KeyboardManager () [virtual]
Definition at line 51 of file SCA_KeyboardManager.cpp.
SCA_KeyboardManager::SCA_KeyboardManager (class SCA_LogicManager * logicmgr, class SCA_IInputDevice * inputdev)
virtual SCA_KeyboardManager::~SCA_KeyboardManager () [virtual]
SCA_KeyboardManager::SCA_KeyboardManager (class SCA_LogicManager * logicmgr, class SCA_IInputDevice * inputdev)
virtual SCA_KeyboardManager::~SCA_KeyboardManager () [virtual]
Member Function Documentation
SCA_IInputDevice * SCA_KeyboardManager::GetInputDevice ()
Definition at line 57 of file SCA_KeyboardManager.cpp.
Referenced by SCA_KeyboardSensor::SCA_KeyboardSensor().
SCA_IInputDevice* SCA_KeyboardManager::GetInputDevice ()
SCA_IInputDevice* SCA_KeyboardManager::GetInputDevice ()
bool SCA_KeyboardManager::IsPressed (SCA_IInputDevice::KX_EnumInputs inputcode)
bool SCA_KeyboardManager::IsPressed (SCA_IInputDevice::KX_EnumInputs inputcode)
bool SCA_KeyboardManager::IsPressed (SCA_IInputDevice::KX_EnumInputs inputcode)
Definition at line 75 of file SCA_KeyboardManager.cpp.
void SCA_KeyboardManager::NextFrame () [virtual]
Reimplemented from SCA_EventManager.
Definition at line 64 of file SCA_KeyboardManager.cpp.
References SG_DList::iterator< T >::begin(), SG_DList::iterator< T >::end(), SCA_EventManager::m_logicmgr, and SCA_EventManager::m_sensors.
virtual void SCA_KeyboardManager::NextFrame () [virtual]
Reimplemented from SCA_EventManager.
virtual void SCA_KeyboardManager::NextFrame () [virtual]
Reimplemented from SCA_EventManager.
The documentation for this class was generated from the following files:
SCA_KeyboardManager.h
SCA_mysensorManager.h
MY_sensorMananger.h
SCA_KeyboardManager.cpp
SCA_mysensorManager.cpp
MY_sensorMananger.cpp