Blender: ED_lattice.h File Reference
ED_lattice.h File Reference
Editors
Functions
void free_editLatt (struct Object *ob)
void make_editLatt (struct Object *obedit)
void load_editLatt (struct Object *obedit)
Detailed Description
Definition in file ED_lattice.h.
Function Documentation
void free_editLatt (struct Object * ob)
Definition at line 69 of file object_lattice.c.
References Object::data, Lattice::def, Lattice::dvert, Lattice::editlatt, free_dverts(), EditLatt::latt, MEM_freeN(), NULL, Lattice::pntsu, Lattice::pntsv, and Lattice::pntsw.
Referenced by ED_object_exit_editmode(), and make_editLatt().
void load_editLatt (struct Object * obedit)
Definition at line 112 of file object_lattice.c.
References BLI_findlink(), Key::block, copy_dverts(), copy_v3_v3(), KeyBlock::data, Object::data, Lattice::def, Lattice::dvert, Lattice::editlatt, Key::elemsize, Lattice::flag, free_dverts(), Lattice::key, EditLatt::latt, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), MEM_mallocN(), NULL, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, EditLatt::shapenr, KeyBlock::totelem, Lattice::typeu, Lattice::typev, Lattice::typew, and BPoint::vec.
Referenced by ED_object_exit_editmode().
void make_editLatt (struct Object * obedit)
Definition at line 88 of file object_lattice.c.
References copy_dverts(), Object::data, Lattice::def, Lattice::dvert, Lattice::editlatt, free_editLatt(), Lattice::key, key_to_latt(), EditLatt::latt, MEM_callocN(), MEM_dupallocN(), MEM_mallocN(), ob_get_keyblock(), Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, Object::shapenr, and EditLatt::shapenr.
Referenced by ED_object_enter_editmode().