Blender: CProfileNode Class Reference
CProfileNode Class Reference
A node in the Profile Hierarchy Tree.
#include <btQuickprof.h>
Public Member Functions
CProfileNode (const char *name, CProfileNode *parent)
~CProfileNode (void)
CProfileNode * Get_Sub_Node (const char *name)
CProfileNode * Get_Parent (void)
CProfileNode * Get_Sibling (void)
CProfileNode * Get_Child (void)
void CleanupMemory ()
void Reset (void)
void Call (void)
bool Return (void)
const char * Get_Name (void)
int Get_Total_Calls (void)
float Get_Total_Time (void)
Protected Attributes
const char * Name
int TotalCalls
float TotalTime
unsigned long int StartTime
int RecursionCounter
CProfileNode * Parent
CProfileNode * Child
CProfileNode * Sibling
Detailed Description
A node in the Profile Hierarchy Tree.
Definition at line 65 of file btQuickprof.h.
Constructor & Destructor Documentation
CProfileNode::CProfileNode (const char * name, CProfileNode * parent)
Definition at line 271 of file btQuickprof.cpp.
References Reset().
Referenced by Get_Sub_Node().
CProfileNode::~CProfileNode (void)
Definition at line 293 of file btQuickprof.cpp.
References Child, and Sibling.
Member Function Documentation
void CProfileNode::Call (void)
Definition at line 343 of file btQuickprof.cpp.
References Profile_Get_Ticks(), RecursionCounter, StartTime, and TotalCalls.
Referenced by CProfileManager::Reset(), and CProfileManager::Start_Profile().
void CProfileNode::CleanupMemory ()
Definition at line 285 of file btQuickprof.cpp.
References Child, NULL, and Sibling.
Referenced by CProfileManager::CleanupMemory().
CProfileNode* CProfileNode::Get_Child (void) [inline]
Definition at line 75 of file btQuickprof.h.
References Child.
Referenced by CProfileIterator::CProfileIterator(), CProfileIterator::Enter_Child(), CProfileIterator::Enter_Parent(), and CProfileIterator::First().
const char* CProfileNode::Get_Name (void) [inline]
Definition at line 82 of file btQuickprof.h.
References Name.
Referenced by CProfileIterator::Get_Current_Name(), CProfileIterator::Get_Current_Parent_Name(), and CProfileManager::Start_Profile().
CProfileNode* CProfileNode::Get_Parent (void) [inline]
Definition at line 73 of file btQuickprof.h.
References Parent.
Referenced by CProfileIterator::Enter_Parent(), CProfileIterator::Is_Root(), and CProfileManager::Stop_Profile().
CProfileNode* CProfileNode::Get_Sibling (void) [inline]
Definition at line 74 of file btQuickprof.h.
References Sibling.
Referenced by CProfileIterator::Enter_Child(), and CProfileIterator::Next().
CProfileNode * CProfileNode::Get_Sub_Node (const char * name)
Definition at line 308 of file btQuickprof.cpp.
References Child, CProfileNode(), Name, and Sibling.
Referenced by CProfileManager::Start_Profile().
int CProfileNode::Get_Total_Calls (void) [inline]
Definition at line 83 of file btQuickprof.h.
References TotalCalls.
Referenced by CProfileIterator::Get_Current_Parent_Total_Calls(), and CProfileIterator::Get_Current_Total_Calls().
float CProfileNode::Get_Total_Time (void) [inline]
Definition at line 84 of file btQuickprof.h.
References TotalTime.
Referenced by CProfileIterator::Get_Current_Parent_Total_Time(), and CProfileIterator::Get_Current_Total_Time().
void CProfileNode::Reset (void)
Definition at line 328 of file btQuickprof.cpp.
References Child, Reset(), Sibling, TotalCalls, and TotalTime.
Referenced by CProfileNode(), Reset(), and CProfileManager::Reset().
bool CProfileNode::Return (void)
Definition at line 352 of file btQuickprof.cpp.
References Profile_Get_Tick_Rate(), Profile_Get_Ticks(), RecursionCounter, StartTime, TotalCalls, and TotalTime.
Referenced by CProfileManager::Stop_Profile().
Member Data Documentation
CProfileNode* CProfileNode::Child [protected]
Definition at line 95 of file btQuickprof.h.
Referenced by CleanupMemory(), Get_Child(), Get_Sub_Node(), Reset(), and ~CProfileNode().
const char* CProfileNode::Name [protected]
Definition at line 88 of file btQuickprof.h.
Referenced by Get_Name(), and Get_Sub_Node().
CProfileNode* CProfileNode::Parent [protected]
Definition at line 94 of file btQuickprof.h.
Referenced by Get_Parent().
int CProfileNode::RecursionCounter [protected]
Definition at line 92 of file btQuickprof.h.
Referenced by Call(), and Return().
CProfileNode* CProfileNode::Sibling [protected]
Definition at line 96 of file btQuickprof.h.
Referenced by CleanupMemory(), Get_Sibling(), Get_Sub_Node(), Reset(), and ~CProfileNode().
unsigned long int CProfileNode::StartTime [protected]
Definition at line 91 of file btQuickprof.h.
Referenced by Call(), and Return().
int CProfileNode::TotalCalls [protected]
Definition at line 89 of file btQuickprof.h.
Referenced by Call(), Get_Total_Calls(), Reset(), and Return().
float CProfileNode::TotalTime [protected]
Definition at line 90 of file btQuickprof.h.
Referenced by Get_Total_Time(), Reset(), and Return().
The documentation for this class was generated from the following files:
btQuickprof.h
btQuickprof.cpp