Blender: blendVideoTex.cpp File Reference
blendVideoTex.cpp File Reference
BGE Video Texture
#include <PyObjectPlus.h>
#include <RAS_GLExtensionManager.h>
#include <RAS_IPolygonMaterial.h>
#include "ImageBase.h"
#include "VideoBase.h"
#include "FilterBase.h"
#include "Texture.h"
#include "Exception.h"
Functions
static PyObject * getMaterialID (PyObject *self, PyObject *args)
static PyObject * getLastError (PyObject *self, PyObject *args)
static PyObject * setLogFile (PyObject *self, PyObject *args)
static PyObject * imageToArray (PyObject *self, PyObject *args)
static void registerAllTypes (void)
PyObject * initVideoTexture (void)
Variables
static PyMethodDef moduleMethods []
PyTypeObject FilterBlueScreenType
PyTypeObject FilterGrayType
PyTypeObject FilterColorType
PyTypeObject FilterLevelType
PyTypeObject FilterNormalType
PyTypeObject FilterRGB24Type
PyTypeObject FilterRGBA32Type
PyTypeObject FilterBGR24Type
PyTypeObject ImageBuffType
PyTypeObject ImageMixType
PyTypeObject ImageRenderType
PyTypeObject ImageMirrorType
PyTypeObject ImageViewportType
static struct PyModuleDef VideoTexture_module_def
Detailed Description
Definition in file blendVideoTex.cpp.
Function Documentation
static PyObject* getLastError (PyObject * self, PyObject * args) [static]
Definition at line 73 of file blendVideoTex.cpp.
References Exception::m_lastError.
static PyObject* getMaterialID (PyObject * self, PyObject * args) [static]
Definition at line 49 of file blendVideoTex.cpp.
References NULL.
static PyObject* imageToArray (PyObject * self, PyObject * args) [static]
Definition at line 90 of file blendVideoTex.cpp.
References Image_getImage(), PyTypeList::in(), NULL, and pyImageTypes.
PyObject* initVideoTexture (void)
Definition at line 171 of file blendVideoTex.cpp.
References Exception::m_lastError, NULL, pyFilterTypes, pyImageTypes, PyTypeList::ready(), PyTypeList::reg(), registerAllExceptions(), registerAllTypes(), SourceEmpty, SourceError, SourcePlaying, SourceReady, SourceStopped, TextureType, and VideoTexture_module_def.
static void registerAllTypes (void) [static]
Definition at line 137 of file blendVideoTex.cpp.
References PyTypeList::add(), FilterBGR24Type, FilterBlueScreenType, FilterColorType, FilterGrayType, FilterLevelType, FilterNormalType, FilterRGB24Type, FilterRGBA32Type, ImageBuffType, ImageMirrorType, ImageMixType, ImageRenderType, ImageViewportType, pyFilterTypes, and pyImageTypes.
Referenced by initVideoTexture().
static PyObject* setLogFile (PyObject * self, PyObject * args) [static]
Definition at line 79 of file blendVideoTex.cpp.
References Exception::m_logFile.
Variable Documentation
PyTypeObject FilterBGR24Type
Definition at line 131 of file FilterSource.cpp.
Referenced by registerAllTypes().
PyTypeObject FilterBlueScreenType
Definition at line 139 of file FilterBlueScreen.cpp.
Referenced by registerAllTypes().
PyTypeObject FilterColorType
Definition at line 176 of file FilterColor.cpp.
Referenced by registerAllTypes().
PyTypeObject FilterGrayType
Definition at line 45 of file FilterColor.cpp.
Referenced by registerAllTypes().
PyTypeObject FilterLevelType
Definition at line 309 of file FilterColor.cpp.
Referenced by registerAllTypes().
PyTypeObject FilterNormalType
Definition at line 128 of file FilterNormal.cpp.
Referenced by registerAllTypes().
PyTypeObject FilterRGB24Type
Definition at line 41 of file FilterSource.cpp.
Referenced by registerAllTypes().
PyTypeObject FilterRGBA32Type
Definition at line 86 of file FilterSource.cpp.
Referenced by registerAllTypes().
PyTypeObject ImageBuffType
Definition at line 381 of file ImageBuff.cpp.
Referenced by plot(), and registerAllTypes().
PyTypeObject ImageMirrorType
Definition at line 728 of file ImageRender.cpp.
Referenced by registerAllTypes().
PyTypeObject ImageMixType
Definition at line 173 of file ImageMix.cpp.
Referenced by registerAllTypes().
PyTypeObject ImageRenderType
Definition at line 394 of file ImageRender.cpp.
Referenced by registerAllTypes().
PyTypeObject ImageViewportType
Definition at line 134 of file blendVideoTex.cpp.
Referenced by registerAllTypes().
PyMethodDef moduleMethods[] [static]
Initial value:
{
    {"materialID", getMaterialID, METH_VARARGS, "Gets object's Blender Material ID"},
    {"getLastError", getLastError, METH_NOARGS, "Gets last error description"},
    {"setLogFile", setLogFile, METH_VARARGS, "Sets log file name"},
    {"imageToArray", imageToArray, METH_VARARGS, "get buffer from image source, color channels are selectable"},
    {NULL}
}
Definition at line 108 of file blendVideoTex.cpp.
struct PyModuleDef VideoTexture_module_def [static]
Initial value:
 {
    {},
    "VideoTexture",
    "Module that allows to play video files on textures in GameBlender.",
    0,
    moduleMethods,
    0,
    0,
    0,
    0,
}
Definition at line 159 of file blendVideoTex.cpp.
Referenced by initVideoTexture().