Blender: main.cpp File Reference
main.cpp File Reference
#include "BSP_GhostTest3D.h"
#include "BSP_TMesh.h"
#include "MEM_SmartPtr.h"
#include "BSP_PlyLoader.h"
#include <iostream>
Functions
MEM_SmartPtr< BSP_TMesh > NewTestMesh (int x, int y, MT_Scalar fx, MT_Scalar fy, MT_Scalar ampx, MT_Scalar ampy, MT_Scalar sx, MT_Scalar sy)
int main ()
Function Documentation
int main ()
Definition at line 96 of file bsp/test/BSP_GhostTest/main.cpp.
References BSP_GhostTestApp3D::InitApp(), max, min, BSP_PlyLoader::NewMeshFromFile(), NewTestMesh(), BSP_GhostTestApp3D::Run(), and BSP_GhostTestApp3D::SetMesh().
MEM_SmartPtr<BSP_TMesh> NewTestMesh (int x, int y, MT_Scalar fx, MT_Scalar fy, MT_Scalar ampx, MT_Scalar ampy, MT_Scalar sx, MT_Scalar sy)
Definition at line 39 of file bsp/test/BSP_GhostTest/main.cpp.
References i, BSP_TVertex::m_pos, MT_PI(), and sin().
Referenced by main().