Blender: EditDerivedBMesh Struct Reference
EditDerivedBMesh Struct Reference
Public Attributes
DerivedMesh dm
Object * ob
BMEditMesh * tc
float(* vertexCos)[3]
float(* vertexNos)[3]
float(* polyNos)[3]
int tv
int te
int tf
Detailed Description
Definition at line 329 of file editderivedmesh.c.
Member Data Documentation
DerivedMesh EditDerivedBMesh::dm
Definition at line 330 of file editderivedmesh.c.
Referenced by bmDm_getTessFaceDataLayout().
Object* EditDerivedBMesh::ob
Definition at line 332 of file editderivedmesh.c.
float(* EditDerivedBMesh::polyNos)[3]
Definition at line 337 of file editderivedmesh.c.
Referenced by emDM_drawFacesTex_common(), emDM_drawMappedFaces(), emDM_drawMappedFacesGLSL(), emDM_drawMappedFacesMat(), emDM_foreachMappedFaceCenter(), and emDM_release().
BMEditMesh* EditDerivedBMesh::tc
Definition at line 333 of file editderivedmesh.c.
Referenced by bmDm_getEdgeDataLayout(), bmDm_getLoopDataLayout(), bmDm_getPolyDataLayout(), bmDm_getVertDataLayout(), emDM_copyLoopArray(), emDM_copyPolyArray(), emDM_copyTessFaceArray(), emDM_copyVertArray(), emDM_drawFacesTex_common(), emDM_drawMappedEdges(), emDM_drawMappedEdgesInterp(), emDM_drawMappedFaces(), emDM_drawMappedFacesGLSL(), emDM_drawMappedFacesMat(), emDM_drawUVEdges(), emDM_foreachMappedEdge(), emDM_foreachMappedFaceCenter(), emDM_foreachMappedVert(), emDM_getEdge(), emDM_getMinMax(), emDM_getNumEdges(), emDM_getNumLoops(), emDM_getNumPolys(), emDM_getNumTessFaces(), emDM_getNumVerts(), emDM_getTessFace(), emDM_getTessFaceDataArray(), emDM_getVert(), emDM_getVertCos(), and getEditDerivedBMesh().
int EditDerivedBMesh::te
Definition at line 341 of file editderivedmesh.c.
Referenced by emDM_getEdge().
int EditDerivedBMesh::tf
Definition at line 341 of file editderivedmesh.c.
Referenced by emDM_getTessFace().
int EditDerivedBMesh::tv
Definition at line 341 of file editderivedmesh.c.
Referenced by emDM_getVert().
float(* EditDerivedBMesh::vertexCos)[3]
Definition at line 335 of file editderivedmesh.c.
Referenced by emDM_copyVertArray(), emDM_drawFacesTex_common(), emDM_drawMappedEdges(), emDM_drawMappedEdgesInterp(), emDM_drawMappedFaces(), emDM_drawMappedFacesGLSL(), emDM_drawMappedFacesMat(), emDM_foreachMappedEdge(), emDM_foreachMappedFaceCenter(), emDM_foreachMappedVert(), emDM_getMinMax(), emDM_getVert(), emDM_getVertCos(), and emDM_release().
float(* EditDerivedBMesh::vertexNos)[3]
Definition at line 336 of file editderivedmesh.c.
Referenced by emDM_drawFacesTex_common(), emDM_drawMappedFaces(), emDM_drawMappedFacesGLSL(), emDM_drawMappedFacesMat(), emDM_foreachMappedVert(), and emDM_release().
The documentation for this struct was generated from the following file:
editderivedmesh.c