Blender: bmesh_py_api.c File Reference
bmesh_py_api.c File Reference
#include <Python.h>
#include "BLI_utildefines.h"
#include "bmesh.h"
#include "bmesh_py_types.h"
#include "bmesh_py_types_select.h"
#include "bmesh_py_types_customdata.h"
#include "bmesh_py_types_meshdata.h"
#include "bmesh_py_utils.h"
#include "BKE_tessmesh.h"
#include "DNA_mesh_types.h"
#include "../generic/py_capi_utils.h"
#include "bmesh_py_api.h"
Functions
PyDoc_STRVAR (bpy_bm_new_doc,".. method:: new()\n""\n"" :return: Return a new, empty BMesh.\n"" :rtype: :class:`bmesh.types.BMesh`\n")
static PyObject * bpy_bm_new (PyObject *UNUSED(self))
PyDoc_STRVAR (bpy_bm_from_edit_mesh_doc,".. method:: from_edit_mesh(mesh)\n""\n"" Return a BMesh from this mesh, currently the mesh must already be in editmode.\n""\n"" :return: the BMesh assosiated with this mesh.\n"" :rtype: :class:`bmesh.types.BMesh`\n")
static PyObject * bpy_bm_from_edit_mesh (PyObject *UNUSED(self), PyObject *value)
PyDoc_STRVAR (BPy_BM_doc,"This module provides access to blenders bmesh data structures.\n""\n""\n""Submodules:\n""\n""* :mod:`bmesh.utils`\n""* :mod:`bmesh.types`\n""\n""\n"".. include:: include__bmesh.rst\n")
PyObject * BPyInit_bmesh (void)
Variables
static struct PyMethodDef BPy_BM_methods []
static struct PyModuleDef BPy_BM_module_def
Detailed Description
This file defines the 'bmesh' module.
This file defines the 'bmesh.utils' module. Utility functions for operating on 'bmesh.types'
Definition in file bmesh_py_api.c.
Function Documentation
static PyObject* bpy_bm_from_edit_mesh (PyObject * UNUSEDself, PyObject * value) [static]
Definition at line 78 of file bmesh_py_api.c.
References BMEditMesh::bm, BPy_BMesh_CreatePyObject(), BPY_BMFLAG_IS_WRAPPED, Mesh::edit_btmesh, NULL, and PyC_RNA_AsPointer().
static PyObject* bpy_bm_new (PyObject * UNUSEDself) [static]
Definition at line 61 of file bmesh_py_api.c.
References bm_mesh_allocsize_default, BM_mesh_create(), BPy_BMesh_CreatePyObject(), and BPY_BMFLAG_NOP.
PyObject* BPyInit_bmesh (void)
Definition at line 128 of file bmesh_py_api.c.
References BPy_BM_init_types(), BPy_BM_init_types_customdata(), BPy_BM_init_types_meshdata(), BPy_BM_init_types_select(), BPyInit_bmesh_types(), BPyInit_bmesh_utils(), and mod().
PyDoc_STRVAR (bpy_bm_new_doc , ".. method:: new()\n""\n"" :return: Return a new, empty BMesh.\n"":rtype::class:`bmesh.types.BMesh`\n")
PyDoc_STRVAR (BPy_BM_doc , "This module provides access to blenders bmesh data structures.\n""\n""\n""Submodules:\n""\n""* :mod:`bmesh.utils`\n""* :mod:`bmesh.types`\n""\n""\n"".. include:: include__bmesh.rst\n")
PyDoc_STRVAR (bpy_bm_from_edit_mesh_doc , ".. method:: from_edit_mesh(mesh)\n""\n"" Return a BMesh from this mesh, currently the mesh must already be in editmode.\n""\n"":return:the BMesh assosiated with this mesh.\n"":rtype::class:`bmesh.types.BMesh`\n")
Variable Documentation
struct PyMethodDef BPy_BM_methods[] [static]
Initial value:
 {
    {"new",            (PyCFunction)bpy_bm_new,            METH_NOARGS,  bpy_bm_new_doc},
    {"from_edit_mesh", (PyCFunction)bpy_bm_from_edit_mesh, METH_O,       bpy_bm_from_edit_mesh_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 98 of file bmesh_py_api.c.
struct PyModuleDef BPy_BM_module_def [static]
Initial value:
 {
    PyModuleDef_HEAD_INIT,
    "bmesh",
    BPy_BM_doc,
    0,
    BPy_BM_methods,
    NULL,
    NULL,
    NULL,
    NULL,
}
Definition at line 116 of file bmesh_py_api.c.