Blender: UI_interface.h File Reference
UI_interface.h File Reference
Interface and Widgets
#include "BLO_sys_types.h"
#include "RNA_types.h"
#include "DNA_userdef_types.h"
Defines
#define UI_MAX_DRAW_STR 400
#define UI_MAX_NAME_STR 128
#define UI_EMBOSS 0
#define UI_EMBOSSN 1
#define UI_EMBOSSP 2
#define UI_EMBOSST 3
#define UI_DIRECTION (UI_TOP|UI_DOWN|UI_LEFT|UI_RIGHT)
#define UI_TOP 1
#define UI_DOWN 2
#define UI_LEFT 4
#define UI_RIGHT 8
#define UI_CENTER 16
#define UI_SHIFT_FLIPPED 32
#define UI_BLOCK_LOOP 1
#define UI_BLOCK_REDRAW 2
#define UI_BLOCK_RET_1 4
#define UI_BLOCK_NUMSELECT 8
#define UI_BLOCK_CLIPBOTTOM 32
#define UI_BLOCK_CLIPTOP 64
#define UI_BLOCK_MOVEMOUSE_QUIT 128
#define UI_BLOCK_KEEP_OPEN 256
#define UI_BLOCK_POPUP 512
#define UI_BLOCK_OUT_1 1024
#define UI_BLOCK_NO_FLIP 2048
#define UI_BLOCK_POPUP_MEMORY 4096
#define UI_BLOCK_CLIP_EVENTS 8192
#define UI_RETURN_CANCEL 1
#define UI_RETURN_OK 2
#define UI_RETURN_OUT 4
#define UI_RETURN_UPDATE 8
#define UI_RETURN_POPUP_OK 16
#define UI_PNL_SOLID 2
#define UI_PNL_CLOSE 32
#define UI_PNL_SCALE 512
#define UI_TEXT_LEFT 64
#define UI_ICON_LEFT 128
#define UI_ICON_SUBMENU 256
#define UI_ICON_PREVIEW 512
#define UI_TEXT_RIGHT 1024
#define UI_BUT_NODE_LINK 2048
#define UI_BUT_NODE_ACTIVE 4096
#define UI_FLAG_UNUSED 8192
#define UI_BUT_ALIGN (UI_BUT_ALIGN_TOP|UI_BUT_ALIGN_LEFT|UI_BUT_ALIGN_RIGHT|UI_BUT_ALIGN_DOWN)
#define UI_BUT_ALIGN_TOP (1<<14)
#define UI_BUT_ALIGN_LEFT (1<<15)
#define UI_BUT_ALIGN_RIGHT (1<<16)
#define UI_BUT_ALIGN_DOWN (1<<17)
#define UI_BUT_DISABLED (1<<18)
#define UI_BUT_COLOR_LOCK (1<<19)
#define UI_BUT_ANIMATED (1<<20)
#define UI_BUT_ANIMATED_KEY (1<<21)
#define UI_BUT_DRIVEN (1<<22)
#define UI_BUT_REDALERT (1<<23)
#define UI_BUT_INACTIVE (1<<24)
#define UI_BUT_LAST_ACTIVE (1<<25)
#define UI_BUT_UNDO (1<<26)
#define UI_BUT_IMMEDIATE (1<<27)
#define UI_BUT_NO_TOOLTIP (1<<28)
#define UI_BUT_NO_UTF8 (1<<29)
#define UI_BUT_VEC_SIZE_LOCK (1<<30)
#define UI_BUT_COLOR_CUBIC (1<<31)
#define UI_PANEL_WIDTH 340
#define UI_COMPACT_PANEL_WIDTH 160
#define UI_DPI_FAC (sqrtf((float)U.dpi) / 8.48528137423857f)
#define UI_DPI_ICON_FAC (((float)U.dpi) / 72.0f)
#define UI_DPI_ICON_SIZE ((float)16 * UI_DPI_ICON_FAC)
#define CHA 32
#define SHO 64
#define INT 96
#define FLO 128
#define BIT 256
#define BUTPOIN (128+64+32)
#define BUT (1<<9)
#define ROW (2<<9)
#define TOG (3<<9)
#define SLI (4<<9)
#define NUM (5<<9)
#define TEX (6<<9)
#define TOG3 (7<<9)
#define TOGR (8<<9)
#define TOGN (9<<9)
#define LABEL (10<<9)
#define MENU (11<<9)
#define ICONROW (12<<9)
#define ICONTOG (13<<9)
#define NUMSLI (14<<9)
#define COL (15<<9)
#define IDPOIN (16<<9)
#define HSVSLI (17<<9)
#define SCROLL (18<<9)
#define BLOCK (19<<9)
#define BUTM (20<<9)
#define SEPR (21<<9)
#define LINK (22<<9)
#define INLINK (23<<9)
#define KEYEVT (24<<9)
#define ICONTEXTROW (25<<9)
#define HSVCUBE (26<<9)
#define PULLDOWN (27<<9)
#define ROUNDBOX (28<<9)
#define CHARTAB (29<<9)
#define BUT_COLORBAND (30<<9)
#define BUT_NORMAL (31<<9)
#define BUT_CURVE (32<<9)
#define BUT_TOGDUAL (33<<9)
#define ICONTOGN (34<<9)
#define FTPREVIEW (35<<9)
#define NUMABS (36<<9)
#define TOGBUT (37<<9)
#define OPTION (38<<9)
#define OPTIONN (39<<9)
#define TRACKPREVIEW (40<<9)
#define SEARCH_MENU (41<<9)
#define BUT_EXTRA (42<<9)
#define HSVCIRCLE (43<<9)
#define LISTBOX (44<<9)
#define LISTROW (45<<9)
#define HOTKEYEVT (46<<9)
#define BUT_IMAGE (47<<9)
#define HISTOGRAM (48<<9)
#define WAVEFORM (49<<9)
#define VECTORSCOPE (50<<9)
#define PROGRESSBAR (51<<9)
#define BUTTYPE (63<<9)
#define UI_GRAD_SV 0
#define UI_GRAD_HV 1
#define UI_GRAD_HS 2
#define UI_GRAD_H 3
#define UI_GRAD_S 4
#define UI_GRAD_V 5
#define UI_GRAD_V_ALT 9
#define UI_SCROLL_PRESSED 1
#define UI_SCROLL_ARROWS 2
#define UI_SCROLL_NO_OUTLINE 4
#define UI_ID_RENAME 1
#define UI_ID_BROWSE 2
#define UI_ID_ADD_NEW 4
#define UI_ID_OPEN 8
#define UI_ID_ALONE 16
#define UI_ID_DELETE 32
#define UI_ID_LOCAL 64
#define UI_ID_AUTO_NAME 128
#define UI_ID_FAKE_USER 256
#define UI_ID_PIN 512
#define UI_ID_BROWSE_RENDER 1024
#define UI_ID_PREVIEWS 2048
#define UI_ID_FULL (UI_ID_RENAME|UI_ID_BROWSE|UI_ID_ADD_NEW|UI_ID_OPEN|UI_ID_ALONE|UI_ID_DELETE|UI_ID_LOCAL)
#define UI_LAYOUT_HORIZONTAL 0
#define UI_LAYOUT_VERTICAL 1
#define UI_LAYOUT_PANEL 0
#define UI_LAYOUT_HEADER 1
#define UI_LAYOUT_MENU 2
#define UI_LAYOUT_TOOLBAR 3
#define UI_UNIT_X U.widget_unit
#define UI_UNIT_Y U.widget_unit
#define UI_LAYOUT_ALIGN_EXPAND 0
#define UI_LAYOUT_ALIGN_LEFT 1
#define UI_LAYOUT_ALIGN_CENTER 2
#define UI_LAYOUT_ALIGN_RIGHT 3
#define UI_ITEM_O_RETURN_PROPS 1
#define UI_ITEM_R_EXPAND 2
#define UI_ITEM_R_SLIDER 4
#define UI_ITEM_R_TOGGLE 8
#define UI_ITEM_R_ICON_ONLY 16
#define UI_ITEM_R_EVENT 32
#define UI_ITEM_R_FULL_EVENT 64
#define UI_ITEM_R_NO_BG 128
#define UI_ITEM_R_IMMEDIATE 256
#define UI_LAYOUT_OP_SHOW_TITLE 1
#define UI_LAYOUT_OP_SHOW_EMPTY 2
#define UI_RB_ALPHA (UI_CNR_ALL + 1)
Typedefs
typedef struct uiBut uiBut
typedef struct uiBlock uiBlock
typedef struct uiPopupBlockHandle uiPopupBlockHandle
typedef struct uiLayout uiLayout
typedef struct uiSearchItems uiSearchItems
typedef void(* uiButHandleFunc)(struct bContext *C, void *arg1, void *arg2)
typedef void(* uiButHandleRenameFunc)(struct bContext *C, void *arg, char *origstr)
typedef void(* uiButHandleNFunc)(struct bContext *C, void *argN, void *arg2)
typedef void(* uiButCompleteFunc)(struct bContext *C, char *str, void *arg)
typedef void(* uiButSearchFunc)(const struct bContext *C, void *arg, const char *str, uiSearchItems *items)
typedef void(* uiBlockHandleFunc)(struct bContext *C, void *arg, int event)
typedef void(* uiMenuCreateFunc)(struct bContext *C, struct uiLayout *layout, void *arg1)
typedef void(* uiMenuHandleFunc)(struct bContext *C, void *arg, int event)
typedef struct uiPopupMenu uiPopupMenu
typedef uiBlock *(* uiBlockCreateFunc)(struct bContext *C, struct ARegion *ar, void *arg1)
typedef void(* uiBlockCancelFunc)(void *arg1)
typedef void(* uiIDPoinFuncFP)(struct bContext *C, const char *str, struct ID **idpp)
typedef void(* uiIDPoinFunc)(struct bContext *C, struct ID *id, int event)
typedef struct AutoComplete AutoComplete
Enumerations
enum {
UI_BLOCK_BOUNDS = 1, UI_BLOCK_BOUNDS_TEXT, UI_BLOCK_BOUNDS_POPUP_MOUSE, UI_BLOCK_BOUNDS_POPUP_MENU,
UI_BLOCK_BOUNDS_POPUP_CENTER
}
enum {
UI_CNR_TOP_LEFT = 1, UI_CNR_TOP_RIGHT = 2, UI_CNR_BOTTOM_RIGHT = 4, UI_CNR_BOTTOM_LEFT = 8,
UI_CNR_NONE = 0, UI_CNR_ALL = (UI_CNR_TOP_LEFT | UI_CNR_TOP_RIGHT | UI_CNR_BOTTOM_RIGHT | UI_CNR_BOTTOM_LEFT)
}
Functions
void uiEmboss (float x1, float y1, float x2, float y2, int sel)
void uiRoundBox (float minx, float miny, float maxx, float maxy, float rad)
void uiSetRoundBox (int type)
int uiGetRoundBox (void)
void uiRoundRect (float minx, float miny, float maxx, float maxy, float rad)
void uiDrawBoxShadow (unsigned char alpha, float minx, float miny, float maxx, float maxy)
void uiDrawBox (int mode, float minx, float miny, float maxx, float maxy, float rad)
void uiDrawBoxShade (int mode, float minx, float miny, float maxx, float maxy, float rad, float shadetop, float shadedown)
void uiDrawBoxVerticalShade (int mode, float minx, float miny, float maxx, float maxy, float rad, float shadeLeft, float shadeRight)
void uiWidgetScrollDraw (struct uiWidgetColors *wcol, struct rcti *rect, struct rcti *slider, int state)
uiPopupMenu * uiPupMenuBegin (struct bContext *C, const char *title, int icon)
void uiPupMenuEnd (struct bContext *C, struct uiPopupMenu *head)
struct uiLayout * uiPupMenuLayout (uiPopupMenu *head)
void uiPupMenuOkee (struct bContext *C, const char *opname, const char *str,...)
void uiPupMenuSaveOver (struct bContext *C, struct wmOperator *op, const char *filename)
void uiPupMenuNotice (struct bContext *C, const char *str,...)
void uiPupMenuError (struct bContext *C, const char *str,...)
void uiPupMenuReports (struct bContext *C, struct ReportList *reports)
void uiPupMenuInvoke (struct bContext *C, const char *idname)
void uiPupBlock (struct bContext *C, uiBlockCreateFunc func, void *arg)
void uiPupBlockO (struct bContext *C, uiBlockCreateFunc func, void *arg, const char *opname, int opcontext)
void uiPupBlockEx (struct bContext *C, uiBlockCreateFunc func, uiBlockHandleFunc popup_func, uiBlockCancelFunc cancel_func, void *arg)
void uiPupBlockClose (struct bContext *C, uiBlock *block)
uiBlock * uiBeginBlock (const struct bContext *C, struct ARegion *region, const char *name, short dt)
void uiEndBlock (const struct bContext *C, uiBlock *block)
void uiDrawBlock (const struct bContext *C, struct uiBlock *block)
uiBlock * uiGetBlock (const char *name, struct ARegion *ar)
void uiBlockSetEmboss (uiBlock *block, char dt)
void uiFreeBlock (const struct bContext *C, uiBlock *block)
void uiFreeBlocks (const struct bContext *C, struct ListBase *lb)
void uiFreeInactiveBlocks (const struct bContext *C, struct ListBase *lb)
void uiFreeActiveButtons (const struct bContext *C, struct bScreen *screen)
void uiBlockSetRegion (uiBlock *block, struct ARegion *region)
void uiBlockSetButLock (uiBlock *block, int val, const char *lockstr)
void uiBlockClearButLock (uiBlock *block)
void uiBlockBeginAlign (uiBlock *block)
void uiBlockEndAlign (uiBlock *block)
void uiBoundsBlock (struct uiBlock *block, int addval)
void uiTextBoundsBlock (uiBlock *block, int addval)
void uiPopupBoundsBlock (uiBlock *block, int addval, int mx, int my)
void uiMenuPopupBoundsBlock (uiBlock *block, int addvall, int mx, int my)
void uiCenteredBoundsBlock (uiBlock *block, int addval)
void uiExplicitBoundsBlock (uiBlock *block, int minx, int miny, int maxx, int maxy)
int uiBlocksGetYMin (struct ListBase *lb)
void uiBlockSetDirection (uiBlock *block, int direction)
void uiBlockFlipOrder (uiBlock *block)
void uiBlockSetFlag (uiBlock *block, int flag)
void uiBlockClearFlag (uiBlock *block, int flag)
void uiBlockSetXOfs (uiBlock *block, int xofs)
int uiButGetRetVal (uiBut *but)
void uiButSetDragID (uiBut *but, struct ID *id)
void uiButSetDragRNA (uiBut *but, struct PointerRNA *ptr)
void uiButSetDragPath (uiBut *but, const char *path)
void uiButSetDragName (uiBut *but, const char *name)
void uiButSetDragValue (uiBut *but)
void uiButSetDragImage (uiBut *but, const char *path, int icon, struct ImBuf *ima, float scale)
int UI_but_active_drop_name (struct bContext *C)
void uiButSetFlag (uiBut *but, int flag)
void uiButClearFlag (uiBut *but, int flag)
int uiButActiveOnly (const struct bContext *C, uiBlock *block, uiBut *but)
uiBut * uiDefBut (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, void *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButF (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, float *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButBitF (uiBlock *block, int type, int bit, int retval, const char *str, int x1, int y1, short x2, short y2, float *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButI (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, int *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButBitI (uiBlock *block, int type, int bit, int retval, const char *str, int x1, int y1, short x2, short y2, int *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButS (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, short *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButBitS (uiBlock *block, int type, int bit, int retval, const char *str, int x1, int y1, short x2, short y2, short *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButC (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, char *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButBitC (uiBlock *block, int type, int bit, int retval, const char *str, int x1, int y1, short x2, short y2, char *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButR (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, struct PointerRNA *ptr, const char *propname, int index, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButR_prop (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, struct PointerRNA *ptr, struct PropertyRNA *prop, int index, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButO (uiBlock *block, int type, const char *opname, int opcontext, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefButO_ptr (uiBlock *block, int type, struct wmOperatorType *ot, int opcontext, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefButTextO (uiBlock *block, int type, const char *opname, int opcontext, const char *str, int x1, int y1, short x2, short y2, void *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconBut (uiBlock *block, int type, int retval, int icon, int x1, int y1, short x2, short y2, void *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButF (uiBlock *block, int type, int retval, int icon, int x1, int y1, short x2, short y2, float *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButBitF (uiBlock *block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, float *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButI (uiBlock *block, int type, int retval, int icon, int x1, int y1, short x2, short y2, int *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButBitI (uiBlock *block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, int *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButS (uiBlock *block, int type, int retval, int icon, int x1, int y1, short x2, short y2, short *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButBitS (uiBlock *block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, short *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButC (uiBlock *block, int type, int retval, int icon, int x1, int y1, short x2, short y2, char *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButBitC (uiBlock *block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, char *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButR (uiBlock *block, int type, int retval, int icon, int x1, int y1, short x2, short y2, struct PointerRNA *ptr, const char *propname, int index, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButR_prop (uiBlock *block, int type, int retval, int icon, int x1, int y1, short x2, short y2, struct PointerRNA *ptr, PropertyRNA *prop, int index, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButO (uiBlock *block, int type, const char *opname, int opcontext, int icon, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefIconButO_ptr (uiBlock *block, int type, struct wmOperatorType *ot, int opcontext, int icon, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefIconTextBut (uiBlock *block, int type, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, void *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButF (uiBlock *block, int type, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, float *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButBitF (uiBlock *block, int type, int bit, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, float *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButI (uiBlock *block, int type, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, int *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButBitI (uiBlock *block, int type, int bit, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, int *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButS (uiBlock *block, int type, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, short *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButBitS (uiBlock *block, int type, int bit, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, short *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButC (uiBlock *block, int type, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, char *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButBitC (uiBlock *block, int type, int bit, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, char *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButR (uiBlock *block, int type, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, struct PointerRNA *ptr, const char *propname, int index, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButR_prop (uiBlock *block, int type, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, struct PointerRNA *ptr, struct PropertyRNA *prop, int index, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButO (uiBlock *block, int type, const char *opname, int opcontext, int icon, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefIconTextButO_ptr (uiBlock *block, int type, struct wmOperatorType *ot, int opcontext, int icon, const char *str, int x1, int y1, short x2, short y2, const char *tip)
struct PointerRNA * uiButGetOperatorPtrRNA (uiBut *but)
void uiButSetUnitType (uiBut *but, const int unit_type)
int uiButGetUnitType (uiBut *but)
uiBut * uiDefIDPoinBut (uiBlock *block, uiIDPoinFuncFP func, short blocktype, int retval, const char *str, int x1, int y1, short x2, short y2, void *idpp, const char *tip)
int uiIconFromID (struct ID *id)
uiBut * uiDefPulldownBut (uiBlock *block, uiBlockCreateFunc func, void *arg, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefMenuBut (uiBlock *block, uiMenuCreateFunc func, void *arg, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefIconTextMenuBut (uiBlock *block, uiMenuCreateFunc func, void *arg, int icon, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefIconMenuBut (uiBlock *block, uiMenuCreateFunc func, void *arg, int icon, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefBlockBut (uiBlock *block, uiBlockCreateFunc func, void *func_arg1, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefBlockButN (uiBlock *block, uiBlockCreateFunc func, void *argN, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefIconBlockBut (uiBlock *block, uiBlockCreateFunc func, void *arg, int retval, int icon, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefIconTextBlockBut (uiBlock *block, uiBlockCreateFunc func, void *arg, int icon, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefKeyevtButS (uiBlock *block, int retval, const char *str, int x1, int y1, short x2, short y2, short *spoin, const char *tip)
uiBut * uiDefHotKeyevtButS (uiBlock *block, int retval, const char *str, int x1, int y1, short x2, short y2, short *keypoin, short *modkeypoin, const char *tip)
uiBut * uiDefSearchBut (uiBlock *block, void *arg, int retval, int icon, int maxlen, int x1, int y1, short x2, short y2, float a1, float a2, const char *tip)
uiBut * uiDefAutoButR (uiBlock *block, struct PointerRNA *ptr, struct PropertyRNA *prop, int index, const char *name, int icon, int x1, int y1, int x2, int y2)
int uiDefAutoButsRNA (uiLayout *layout, struct PointerRNA *ptr, int(*check_prop)(struct PointerRNA *, struct PropertyRNA *), const char label_align)
void uiSetButLink (struct uiBut *but, void **poin, void ***ppoin, short *tot, int from, int to)
void uiComposeLinks (uiBlock *block)
uiBut * uiFindInlink (uiBlock *block, void *poin)
int uiSearchItemAdd (uiSearchItems *items, const char *name, void *poin, int iconid)
void uiButSetSearchFunc (uiBut *but, uiButSearchFunc sfunc, void *arg1, uiButHandleFunc bfunc, void *active)
int uiSearchBoxhHeight (void)
void uiBlockSetHandleFunc (uiBlock *block, uiBlockHandleFunc func, void *arg)
void uiBlockSetButmFunc (uiBlock *block, uiMenuHandleFunc func, void *arg)
void uiBlockSetFunc (uiBlock *block, uiButHandleFunc func, void *arg1, void *arg2)
void uiBlockSetNFunc (uiBlock *block, uiButHandleFunc func, void *argN, void *arg2)
void uiButSetRenameFunc (uiBut *but, uiButHandleRenameFunc func, void *arg1)
void uiButSetFunc (uiBut *but, uiButHandleFunc func, void *arg1, void *arg2)
void uiButSetNFunc (uiBut *but, uiButHandleNFunc func, void *argN, void *arg2)
void uiButSetCompleteFunc (uiBut *but, uiButCompleteFunc func, void *arg)
void uiBlockSetDrawExtraFunc (uiBlock *block, void(*func)(const struct bContext *C, void *, void *, void *, struct rcti *rect), void *arg1, void *arg2)
void uiButSetFocusOnEnter (struct wmWindow *win, uiBut *but)
AutoComplete * autocomplete_begin (const char *startname, size_t maxlen)
void autocomplete_do_name (AutoComplete *autocpl, const char *name)
void autocomplete_end (AutoComplete *autocpl, char *autoname)
void uiBeginPanels (const struct bContext *C, struct ARegion *ar)
void uiEndPanels (const struct bContext *C, struct ARegion *ar, int *x, int *y)
void uiDrawPanels (const struct bContext *C, struct ARegion *ar)
struct Panel * uiBeginPanel (struct ScrArea *sa, struct ARegion *ar, uiBlock *block, struct PanelType *pt, int *open)
void uiEndPanel (uiBlock *block, int width, int height)
void UI_add_region_handlers (struct ListBase *handlers)
void UI_add_popup_handlers (struct bContext *C, struct ListBase *handlers, uiPopupBlockHandle *popup)
void UI_remove_popup_handlers (struct ListBase *handlers, uiPopupBlockHandle *popup)
void UI_init (void)
void UI_init_userdef (void)
void UI_reinit_font (void)
void UI_exit (void)
uiLayout * uiBlockLayout (uiBlock *block, int dir, int type, int x, int y, int size, int em, struct uiStyle *style)
void uiBlockSetCurLayout (uiBlock *block, uiLayout *layout)
void uiBlockLayoutResolve (uiBlock *block, int *x, int *y)
uiBlock * uiLayoutGetBlock (uiLayout *layout)
void uiLayoutSetFunc (uiLayout *layout, uiMenuHandleFunc handlefunc, void *argv)
void uiLayoutSetContextPointer (uiLayout *layout, const char *name, struct PointerRNA *ptr)
void uiLayoutContextCopy (uiLayout *layout, struct bContextStore *context)
const char * uiLayoutIntrospect (uiLayout *layout)
void uiLayoutOperatorButs (const struct bContext *C, struct uiLayout *layout, struct wmOperator *op, int(*check_prop)(struct PointerRNA *, struct PropertyRNA *), const char label_align, const short flag)
struct MenuType * uiButGetMenuType (uiBut *but)
void uiLayoutSetOperatorContext (uiLayout *layout, int opcontext)
void uiLayoutSetActive (uiLayout *layout, int active)
void uiLayoutSetEnabled (uiLayout *layout, int enabled)
void uiLayoutSetRedAlert (uiLayout *layout, int redalert)
void uiLayoutSetAlignment (uiLayout *layout, int alignment)
void uiLayoutSetKeepAspect (uiLayout *layout, int keepaspect)
void uiLayoutSetScaleX (uiLayout *layout, float scale)
void uiLayoutSetScaleY (uiLayout *layout, float scale)
int uiLayoutGetOperatorContext (uiLayout *layout)
int uiLayoutGetActive (uiLayout *layout)
int uiLayoutGetEnabled (uiLayout *layout)
int uiLayoutGetRedAlert (uiLayout *layout)
int uiLayoutGetAlignment (uiLayout *layout)
int uiLayoutGetKeepAspect (uiLayout *layout)
int uiLayoutGetWidth (uiLayout *layout)
float uiLayoutGetScaleX (uiLayout *layout)
float uiLayoutGetScaleY (uiLayout *layout)
uiLayout * uiLayoutRow (uiLayout *layout, int align)
uiLayout * uiLayoutColumn (uiLayout *layout, int align)
uiLayout * uiLayoutColumnFlow (uiLayout *layout, int number, int align)
uiLayout * uiLayoutBox (uiLayout *layout)
uiLayout * uiLayoutListBox (uiLayout *layout, struct PointerRNA *ptr, struct PropertyRNA *prop, struct PointerRNA *actptr, struct PropertyRNA *actprop)
uiLayout * uiLayoutAbsolute (uiLayout *layout, int align)
uiLayout * uiLayoutSplit (uiLayout *layout, float percentage, int align)
uiLayout * uiLayoutOverlap (uiLayout *layout)
uiBlock * uiLayoutAbsoluteBlock (uiLayout *layout)
void uiTemplateHeader (uiLayout *layout, struct bContext *C, int menus)
void uiTemplateDopeSheetFilter (uiLayout *layout, struct bContext *C, struct PointerRNA *ptr)
void uiTemplateID (uiLayout *layout, struct bContext *C, struct PointerRNA *ptr, const char *propname, const char *newop, const char *openop, const char *unlinkop)
void uiTemplateIDBrowse (uiLayout *layout, struct bContext *C, struct PointerRNA *ptr, const char *propname, const char *newop, const char *openop, const char *unlinkop)
void uiTemplateIDPreview (uiLayout *layout, struct bContext *C, struct PointerRNA *ptr, const char *propname, const char *newop, const char *openop, const char *unlinkop, int rows, int cols)
void uiTemplateAnyID (uiLayout *layout, struct PointerRNA *ptr, const char *propname, const char *proptypename, const char *text)
void uiTemplatePathBuilder (uiLayout *layout, struct PointerRNA *ptr, const char *propname, struct PointerRNA *root_ptr, const char *text)
uiLayout * uiTemplateModifier (uiLayout *layout, struct bContext *C, struct PointerRNA *ptr)
uiLayout * uiTemplateConstraint (uiLayout *layout, struct PointerRNA *ptr)
void uiTemplatePreview (uiLayout *layout, struct ID *id, int show_buttons, struct ID *parent, struct MTex *slot)
void uiTemplateColorRamp (uiLayout *layout, struct PointerRNA *ptr, const char *propname, int expand)
void uiTemplateHistogram (uiLayout *layout, struct PointerRNA *ptr, const char *propname)
void uiTemplateWaveform (uiLayout *layout, struct PointerRNA *ptr, const char *propname)
void uiTemplateVectorscope (uiLayout *layout, struct PointerRNA *ptr, const char *propname)
void uiTemplateCurveMapping (uiLayout *layout, struct PointerRNA *ptr, const char *propname, int type, int levels, int brush)
void uiTemplateColorWheel (uiLayout *layout, struct PointerRNA *ptr, const char *propname, int value_slider, int lock, int lock_luminosity, int cubic)
void uiTemplateLayers (uiLayout *layout, struct PointerRNA *ptr, const char *propname, PointerRNA *used_ptr, const char *used_propname, int active_layer)
void uiTemplateImage (uiLayout *layout, struct bContext *C, struct PointerRNA *ptr, const char *propname, struct PointerRNA *userptr, int compact)
void uiTemplateImageSettings (uiLayout *layout, struct PointerRNA *imfptr)
void uiTemplateImageLayers (uiLayout *layout, struct bContext *C, struct Image *ima, struct ImageUser *iuser)
void uiTemplateRunningJobs (uiLayout *layout, struct bContext *C)
void uiTemplateOperatorSearch (uiLayout *layout)
void uiTemplateHeader3D (uiLayout *layout, struct bContext *C)
void uiTemplateEditModeSelection (uiLayout *layout, struct bContext *C)
void uiTemplateTextureImage (uiLayout *layout, struct bContext *C, struct Tex *tex)
void uiTemplateReportsBanner (uiLayout *layout, struct bContext *C)
void uiTemplateKeymapItemProperties (uiLayout *layout, struct PointerRNA *ptr)
void uiTemplateList (uiLayout *layout, struct bContext *C, struct PointerRNA *ptr, const char *propname, struct PointerRNA *activeptr, const char *activeprop, const char *prop_list, int rows, int maxrows, int type)
void uiTemplateNodeLink (uiLayout *layout, struct bNodeTree *ntree, struct bNode *node, struct bNodeSocket *input)
void uiTemplateNodeView (uiLayout *layout, struct bContext *C, struct bNodeTree *ntree, struct bNode *node, struct bNodeSocket *input)
void uiTemplateTextureUser (uiLayout *layout, struct bContext *C)
void uiTemplateTextureShow (uiLayout *layout, struct bContext *C, struct PointerRNA *ptr, struct PropertyRNA *prop)
void uiTemplateMovieClip (struct uiLayout *layout, struct bContext *C, struct PointerRNA *ptr, const char *propname, int compact)
void uiTemplateTrack (struct uiLayout *layout, struct PointerRNA *ptr, const char *propname)
void uiTemplateMarker (struct uiLayout *layout, struct PointerRNA *ptr, const char *propname, PointerRNA *userptr, PointerRNA *trackptr, int cmpact)
void uiItemO (uiLayout *layout, const char *name, int icon, const char *opname)
void uiItemEnumO_ptr (uiLayout *layout, struct wmOperatorType *ot, const char *name, int icon, const char *propname, int value)
void uiItemEnumO (uiLayout *layout, const char *opname, const char *name, int icon, const char *propname, int value)
void uiItemEnumO_value (uiLayout *layout, const char *name, int icon, const char *opname, const char *propname, int value)
void uiItemEnumO_string (uiLayout *layout, const char *name, int icon, const char *opname, const char *propname, const char *value)
void uiItemsEnumO (uiLayout *layout, const char *opname, const char *propname)
void uiItemBooleanO (uiLayout *layout, const char *name, int icon, const char *opname, const char *propname, int value)
void uiItemIntO (uiLayout *layout, const char *name, int icon, const char *opname, const char *propname, int value)
void uiItemFloatO (uiLayout *layout, const char *name, int icon, const char *opname, const char *propname, float value)
void uiItemStringO (uiLayout *layout, const char *name, int icon, const char *opname, const char *propname, const char *value)
PointerRNA uiItemFullO_ptr (uiLayout *layout, struct wmOperatorType *ot, const char *name, int icon, IDProperty *properties, int context, int flag)
PointerRNA uiItemFullO (uiLayout *layout, const char *idname, const char *name, int icon, struct IDProperty *properties, int context, int flag)
void uiItemR (uiLayout *layout, struct PointerRNA *ptr, const char *propname, int flag, const char *name, int icon)
void uiItemFullR (uiLayout *layout, struct PointerRNA *ptr, struct PropertyRNA *prop, int index, int value, int flag, const char *name, int icon)
void uiItemEnumR (uiLayout *layout, const char *name, int icon, struct PointerRNA *ptr, const char *propname, int value)
void uiItemEnumR_string (uiLayout *layout, struct PointerRNA *ptr, const char *propname, const char *value, const char *name, int icon)
void uiItemsEnumR (uiLayout *layout, struct PointerRNA *ptr, const char *propname)
void uiItemPointerR (uiLayout *layout, struct PointerRNA *ptr, const char *propname, struct PointerRNA *searchptr, const char *searchpropname, const char *name, int icon)
void uiItemsFullEnumO (uiLayout *layout, const char *opname, const char *propname, struct IDProperty *properties, int context, int flag)
void uiItemL (uiLayout *layout, const char *name, int icon)
void uiItemLDrag (uiLayout *layout, struct PointerRNA *ptr, const char *name, int icon)
void uiItemM (uiLayout *layout, struct bContext *C, const char *menuname, const char *name, int icon)
void uiItemV (uiLayout *layout, const char *name, int icon, int argval)
void uiItemS (uiLayout *layout)
void uiItemMenuF (uiLayout *layout, const char *name, int icon, uiMenuCreateFunc func, void *arg)
void uiItemMenuEnumO (uiLayout *layout, const char *opname, const char *propname, const char *name, int icon)
void uiItemMenuEnumR (uiLayout *layout, struct PointerRNA *ptr, const char *propname, const char *name, int icon)
void UI_buttons_operatortypes (void)
uiBut * uiContextActiveButton (const struct bContext *C)
void uiContextActiveProperty (const struct bContext *C, struct PointerRNA *ptr, struct PropertyRNA **prop, int *index)
void uiContextActivePropertyHandle (struct bContext *C)
struct wmOperator * uiContextActiveOperator (const struct bContext *C)
void uiContextAnimUpdate (const struct bContext *C)
void uiFileBrowseContextProperty (const struct bContext *C, struct PointerRNA *ptr, struct PropertyRNA **prop)
void uiIDContextProperty (struct bContext *C, struct PointerRNA *ptr, struct PropertyRNA **prop)
void uiStyleFontSet (struct uiFontStyle *fs)
void uiStyleFontDrawExt (struct uiFontStyle *fs, struct rcti *rect, const char *str, float *r_xofs, float *r_yofs)
void uiStyleFontDraw (struct uiFontStyle *fs, struct rcti *rect, const char *str)
void uiStyleFontDrawRotated (struct uiFontStyle *fs, struct rcti *rect, const char *str)
int UI_GetStringWidth (const char *str)
void UI_DrawString (float x, float y, const char *str)
void UI_DrawTriIcon (float x, float y, char dir)
uiStyle * UI_GetStyle (void)
void UI_template_fix_linking (void)
int UI_editsource_enable_check (void)
void UI_editsource_active_but_test (uiBut *but)
Variables
enum { ... } eBlockBoundsCalc
Detailed Description
Definition in file UI_interface.h.
Define Documentation
#define BIT 256
Definition at line 193 of file UI_interface.h.
Referenced by draw_actuatorbuttons(), ui_def_but(), uiDefButBit(), uiDefIconButBit(), and uiDefIconTextButBit().
#define BLOCK (19<<9)
Definition at line 215 of file UI_interface.h.
Referenced by button_activate_state(), ui_apply_button(), ui_blockopen_begin(), ui_def_but(), ui_do_button(), ui_draw_but(), ui_handle_menu_event(), ui_menu_block_set_keyaccels(), ui_popup_block_create(), uiDefBlockBut(), uiDefBlockButN(), uiDefIconBlockBut(), and uiDefIconTextBlockBut().
#define BUT (1<<9)
Definition at line 197 of file UI_interface.h.
Referenced by ANIM_uiTemplate_fmodifier_draw(), colorband_buttons_large(), colorband_buttons_small(), curvemap_buttons_layout(), draw_actuatorbuttons(), draw_constraint(), draw_group_socket(), draw_modifier(), draw_modifier__envelope(), file_draw_buttons(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_modifiers(), logic_buttons(), nla_panel_modifiers(), node_shader_buts_dynamic(), template_ID(), template_texture_user_menu(), ui_apply_button(), ui_but_menu(), ui_def_but(), ui_do_button(), ui_draw_but(), ui_handle_menu_event(), ui_is_but_sel(), ui_item_with_label(), ui_menu_block_set_keyaccels(), ui_node_menu_column(), ui_template_node_link_menu(), uiblock_layer_pass_arrow_buttons(), uiBlockPicker(), uiItemFullO_ptr(), uiItemV(), uiLayoutOperatorButs(), uiTemplateImage(), uiTemplateReportsBanner(), uiTemplateRunningJobs(), uiTemplateTextureShow(), view3d_panel_vgroup(), widget_draw_text_icon(), and wm_block_dialog_create().
#define BUT_COLORBAND (30<<9)
Definition at line 226 of file UI_interface.h.
Referenced by colorband_buttons_large(), colorband_buttons_small(), ui_apply_button(), ui_but_copy_paste(), ui_do_button(), ui_draw_but(), and ui_numedit_begin().
#define BUT_CURVE (32<<9)
Definition at line 228 of file UI_interface.h.
Referenced by button_activate_init(), curvemap_buttons_layout(), ui_apply_button(), ui_do_button(), ui_draw_but(), and ui_numedit_begin().
#define BUT_EXTRA (42<<9)
Definition at line 239 of file UI_interface.h.
Referenced by ui_draw_but(), and uiTemplatePreview().
#define BUT_IMAGE (47<<9)
Definition at line 244 of file UI_interface.h.
Referenced by ui_apply_button(), ui_do_button(), ui_draw_but(), ui_free_but(), and wm_block_create_splash().
#define BUT_NORMAL (31<<9)
Definition at line 227 of file UI_interface.h.
Referenced by node_buts_normal(), ui_apply_button(), ui_do_button(), ui_draw_but(), ui_get_but_vectorf(), ui_item_array(), and ui_numedit_begin().
#define BUT_TOGDUAL (33<<9)
Definition at line 229 of file UI_interface.h.
Referenced by logic_buttons(), ui_apply_but_TOG(), ui_apply_button(), ui_check_but(), ui_def_but(), ui_do_button(), ui_is_but_sel(), widget_draw_icon(), and widget_draw_text_icon().
#define BUTM (20<<9)
Definition at line 216 of file UI_interface.h.
Referenced by actuator_menu(), controller_menu(), curvemap_brush_tools_func(), curvemap_tools_func(), object_state_mask_menu(), sensor_menu(), ui_apply_but_func(), ui_apply_button(), ui_block_func_ICONROW(), ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), ui_def_but(), ui_do_button(), and ui_draw_but().
#define BUTPOIN (128+64+32)
Definition at line 195 of file UI_interface.h.
Referenced by ui_def_but().
#define BUTTYPE (63<<9)
Definition at line 250 of file UI_interface.h.
Referenced by ui_def_but().
#define CHA 32
Definition at line 188 of file UI_interface.h.
#define CHARTAB (29<<9)
Definition at line 225 of file UI_interface.h.
Referenced by ui_apply_button(), and ui_do_button().
#define COL (15<<9)
Definition at line 211 of file UI_interface.h.
#define FLO 128
Definition at line 191 of file UI_interface.h.
#define FTPREVIEW (35<<9)
Definition at line 231 of file UI_interface.h.
Referenced by ui_def_but().
#define HISTOGRAM (48<<9)
Definition at line 245 of file UI_interface.h.
Referenced by ui_apply_button(), ui_do_button(), ui_draw_but(), and uiTemplateHistogram().
#define HOTKEYEVT (46<<9)
Definition at line 243 of file UI_interface.h.
Referenced by button_activate_init(), ui_apply_button(), ui_check_but(), ui_do_button(), ui_is_but_sel(), ui_item_with_label(), and uiDefHotKeyevtButS().
#define HSVCIRCLE (43<<9)
Definition at line 240 of file UI_interface.h.
Referenced by circle_picker(), ui_apply_button(), ui_check_but(), ui_do_button(), ui_draw_but(), ui_is_a_warp_but(), ui_numedit_begin(), and uiTemplateColorWheel().
#define HSVCUBE (26<<9)
Definition at line 222 of file UI_interface.h.
Referenced by circle_picker(), square_picker(), ui_apply_button(), ui_check_but(), ui_do_button(), ui_draw_but(), ui_numedit_begin(), ui_picker_small_wheel_cb(), and uiTemplateColorWheel().
#define HSVSLI (17<<9)
Definition at line 213 of file UI_interface.h.
Referenced by ui_apply_button(), ui_but_copy_paste(), ui_check_but(), ui_def_but(), ui_do_button(), ui_draw_but(), ui_get_but_val(), ui_numedit_but_SLI(), ui_set_but_val(), ui_textedit_next_but(), and ui_textedit_prev_but().
#define ICONROW (12<<9)
Definition at line 208 of file UI_interface.h.
Referenced by ui_apply_but_BLOCK(), ui_apply_button(), ui_blockopen_begin(), ui_check_but(), ui_do_but_BLOCK(), ui_do_button(), ui_handle_button_return_submenu(), and widget_draw_icon().
#define ICONTEXTROW (25<<9)
Definition at line 221 of file UI_interface.h.
Referenced by button_activate_state(), ED_area_header_switchbutton(), ui_apply_autokey_undo(), ui_apply_but_BLOCK(), ui_apply_button(), ui_blockopen_begin(), ui_check_but(), ui_do_but_BLOCK(), ui_do_button(), ui_draw_but(), ui_handle_button_return_submenu(), widget_draw_icon(), and widget_draw_text_icon().
#define ICONTOG (13<<9)
Definition at line 209 of file UI_interface.h.
Referenced by buttons_context_draw(), draw_setting_widget(), logic_buttons(), outliner_draw_restrictbuts(), ui_apply_but_TOG(), ui_apply_button(), ui_check_but(), ui_do_button(), ui_is_but_sel(), and uiDefAutoButR().
#define ICONTOGN (34<<9)
Definition at line 230 of file UI_interface.h.
Referenced by draw_setting_widget(), outliner_draw_restrictbuts(), ui_apply_but_TOG(), ui_apply_button(), ui_check_but(), ui_do_button(), and ui_is_but_sel().
#define IDPOIN (16<<9)
Definition at line 212 of file UI_interface.h.
Referenced by ui_apply_button(), UI_but_active_drop_name(), ui_but_copy_paste(), ui_but_drop(), ui_check_but(), ui_def_but(), ui_do_button(), ui_get_but_string(), ui_get_but_string_max_length(), ui_set_but_string(), ui_textedit_next_but(), ui_textedit_prev_but(), ui_tooltip_create(), uiDefAutoButR(), and uiDefIDPoinBut().
#define INLINK (23<<9)
Definition at line 219 of file UI_interface.h.
Referenced by logic_buttons(), logic_buttons_new(), ui_add_link(), ui_add_smart_controller(), ui_apply_autokey_undo(), ui_apply_but_LINK(), ui_apply_button(), ui_do_button(), ui_draw_but(), ui_find_inlink(), and ui_handle_button_event().
#define INT 96
Definition at line 190 of file UI_interface.h.
#define KEYEVT (24<<9)
Definition at line 220 of file UI_interface.h.
Referenced by ui_apply_button(), ui_check_but(), ui_do_button(), ui_is_but_sel(), ui_item_with_label(), and uiDefKeyevtButS().
#define LABEL (10<<9)
Definition at line 206 of file UI_interface.h.
#define LINK (22<<9)
Definition at line 218 of file UI_interface.h.
Referenced by cut_links_exec(), logic_buttons(), logic_buttons_new(), ui_add_link(), ui_add_smart_controller(), ui_apply_autokey_undo(), ui_apply_but_LINK(), ui_apply_button(), ui_but_update_linklines(), ui_delete_active_linkline(), ui_do_button(), ui_draw_but(), ui_draw_links(), ui_handle_button_event(), and uiComposeLinks().
#define LISTBOX (44<<9)
Definition at line 241 of file UI_interface.h.
Referenced by ui_but_editable(), ui_but_find_mouse_over(), ui_def_but(), ui_do_button(), ui_draw_but(), ui_list_find_mouse_over(), ui_textedit_next_but(), ui_textedit_prev_but(), and uiLayoutListBox().
#define LISTROW (45<<9)
Definition at line 242 of file UI_interface.h.
Referenced by file_panel_category(), list_item_row(), ui_apply_but_ROW(), ui_apply_button(), ui_but_update_from_old_block(), ui_def_but_rna(), ui_do_button(), ui_draw_but(), ui_is_but_sel(), uiTemplateList(), and widget_draw_icon().
#define MENU (11<<9)
Definition at line 207 of file UI_interface.h.
Referenced by colorband_buttons_large(), colorband_buttons_small(), draw_actuatorbuttons(), draw_controllerbuttons(), draw_modifier__generator(), draw_sensorbuttons(), logic_buttons(), node_shader_buts_dynamic(), outliner_draw_keymapbuts(), ui_apply_autokey_undo(), ui_apply_but_BLOCK(), ui_apply_button(), ui_blockopen_begin(), ui_check_but(), ui_def_but(), ui_def_but_rna(), ui_do_but_BLOCK(), ui_do_button(), ui_draw_but(), ui_handle_button_return_submenu(), ui_handle_menu_event(), ui_item_menu(), ui_menu_block_set_keyaccels(), ui_tooltip_create(), uiblock_layer_pass_buttons(), uiDefAutoButR(), uiTemplateHeader3D(), uiTemplateNodeLink(), uiTemplateTextureUser(), and widget_draw_text_icon().
#define NUM (5<<9)
Definition at line 201 of file UI_interface.h.
#define NUMABS (36<<9)
Definition at line 232 of file UI_interface.h.
Referenced by ui_apply_button(), ui_but_copy_paste(), ui_check_but(), ui_def_but(), ui_do_but_textedit(), ui_do_button(), ui_is_a_warp_but(), ui_set_but_string(), ui_textedit_begin(), ui_textedit_next_but(), ui_textedit_prev_but(), widget_draw_text(), and widget_draw_text_icon().
#define NUMSLI (14<<9)
Definition at line 210 of file UI_interface.h.
#define OPTION (38<<9)
Definition at line 234 of file UI_interface.h.
Referenced by list_item_row(), outliner_draw_keymapbuts(), ui_apply_button(), ui_but_can_align(), ui_do_button(), ui_draw_but(), ui_is_but_sel(), ui_item_array(), uiDefAutoButR(), and uiItemFullR().
#define OPTIONN (39<<9)
Definition at line 235 of file UI_interface.h.
Referenced by ui_apply_but_TOG(), ui_apply_button(), ui_but_can_align(), ui_do_button(), ui_draw_but(), ui_is_but_sel(), and uiTemplateMarker().
#define PROGRESSBAR (51<<9)
Definition at line 248 of file UI_interface.h.
Referenced by ui_but_editable(), ui_def_but(), ui_do_button(), ui_draw_but(), and uiTemplateRunningJobs().
#define PULLDOWN (27<<9)
Definition at line 223 of file UI_interface.h.
Referenced by button_activate_state(), ui_apply_button(), ui_block_func_POPUP(), ui_blockopen_begin(), ui_def_but(), ui_do_button(), ui_draw_but(), ui_handle_menu_event(), ui_menu_block_set_keyaccels(), ui_popup_block_create(), ui_tooltip_create(), uiDefIconMenuBut(), uiDefIconTextMenuBut(), uiDefMenuBut(), and uiDefPulldownBut().
#define ROUNDBOX (28<<9)
Definition at line 224 of file UI_interface.h.
Referenced by ui_but_editable(), ui_but_find_mouse_over(), ui_def_but(), ui_do_button(), ui_draw_but(), ui_textedit_next_but(), ui_textedit_prev_but(), uiLayoutBox(), and uiTemplateReportsBanner().
#define ROW (2<<9)
Definition at line 198 of file UI_interface.h.
#define SCROLL (18<<9)
Definition at line 214 of file UI_interface.h.
Referenced by ui_apply_button(), ui_check_but(), ui_def_but(), ui_do_button(), ui_draw_but(), ui_numedit_but_SLI(), and uiTemplateList().
#define SEARCH_MENU (41<<9)
Definition at line 238 of file UI_interface.h.
Referenced by button_activate_init(), ui_apply_button(), UI_but_active_drop_name(), ui_but_add_search(), ui_but_copy_paste(), ui_but_drop(), ui_check_but(), ui_def_but(), ui_do_button(), ui_draw_but(), ui_get_but_string(), ui_get_but_string_max_length(), ui_handle_menu_event(), ui_set_but_string(), ui_textedit_begin(), ui_textedit_next_but(), ui_textedit_prev_but(), ui_textedit_set_cursor_pos(), ui_tooltip_create(), uiDefSearchBut(), widget_draw_icon(), and widget_draw_text_icon().
#define SEPR (21<<9)
Definition at line 217 of file UI_interface.h.
Referenced by actuator_menu(), controller_menu(), object_state_mask_menu(), sensor_menu(), ui_but_editable(), ui_but_find_mouse_over(), ui_def_but(), ui_draw_but(), ui_handle_menu_event(), ui_text_bounds_block(), ui_textedit_next_but(), ui_textedit_prev_but(), and uiItemS().
#define SHO 64
Definition at line 189 of file UI_interface.h.
Referenced by ui_apply_but_TOG(), ui_apply_but_TOG3(), ui_get_but_val(), ui_set_but_val(), uiDefButBitS(), uiDefButS(), uiDefHotKeyevtButS(), uiDefIconButBitS(), uiDefIconButS(), uiDefIconTextButBitS(), uiDefIconTextButS(), uiDefKeyevtButS(), and widget_draw_text_icon().
#define SLI (4<<9)
Definition at line 200 of file UI_interface.h.
Referenced by ui_apply_button(), ui_check_but(), ui_do_but_SLI(), ui_do_button(), widget_draw_text(), and widget_draw_text_icon().
#define TEX (6<<9)
Definition at line 202 of file UI_interface.h.
#define TOG (3<<9)
Definition at line 199 of file UI_interface.h.
#define TOG3 (7<<9)
Definition at line 203 of file UI_interface.h.
Referenced by ui_apply_button(), ui_do_button(), ui_draw_but(), and ui_is_but_sel().
#define TOGBUT (37<<9)
Definition at line 233 of file UI_interface.h.
Referenced by node_draw_basis(), node_draw_hidden(), ui_apply_button(), ui_do_button(), ui_draw_but(), and ui_is_but_sel().
#define TOGN (9<<9)
Definition at line 205 of file UI_interface.h.
Referenced by draw_actuatorbuttons(), ui_apply_but_TOG(), ui_apply_button(), ui_do_button(), ui_draw_but(), ui_is_but_sel(), uiTemplateMarker(), v3d_editvertex_buts(), and widget_draw_icon().
#define TOGR (8<<9)
Definition at line 204 of file UI_interface.h.
Referenced by ui_apply_but_TOG(), ui_apply_button(), ui_do_button(), ui_handle_menu_event(), and ui_is_but_sel().
#define TRACKPREVIEW (40<<9)
Definition at line 236 of file UI_interface.h.
Referenced by ui_apply_button(), ui_do_button(), ui_draw_but(), ui_is_a_warp_but(), and uiTemplateTrack().
#define UI_BLOCK_CLIP_EVENTS 8192
Definition at line 120 of file UI_interface.h.
Referenced by node_uiblocks_init(), and ui_but_find_mouse_over().
#define UI_BLOCK_CLIPBOTTOM 32
Definition at line 112 of file UI_interface.h.
Referenced by ui_draw_menu_back(), ui_menu_scroll_test(), and ui_popup_block_scrolltest().
#define UI_BLOCK_CLIPTOP 64
Definition at line 113 of file UI_interface.h.
Referenced by ui_draw_menu_back(), ui_menu_scroll_test(), and ui_popup_block_scrolltest().
#define UI_BLOCK_KEEP_OPEN 256
Definition at line 115 of file UI_interface.h.
Referenced by button_activate_exit(), socket_component_menu(), ui_block_func_COL(), ui_handle_menu_return_submenu(), wm_block_create_redo(), wm_block_create_splash(), wm_block_dialog_create(), and wm_operator_ui_create().
#define UI_BLOCK_LOOP 1
Definition at line 107 of file UI_interface.h.
Referenced by button_activate_state(), id_search_menu(), operator_search_menu(), tool_search_menu(), ui_block_func_COL(), ui_block_func_POPUP(), ui_def_but(), ui_draw_but(), ui_handle_menu_event(), ui_popup_block_create(), ui_popup_bounds_block(), ui_popup_menu_create(), ui_searchbox_create(), ui_tooltip_create(), uiBeginBlock(), uiButSetSearchFunc(), uiDrawBlock(), uiEndBlock(), widget_draw_icon(), widget_draw_text(), widget_draw_text_icon(), wm_block_create_redo(), wm_block_dialog_create(), wm_block_search_menu(), wm_enum_search_menu(), and wm_operator_ui_create().
#define UI_BLOCK_MOVEMOUSE_QUIT 128
Definition at line 114 of file UI_interface.h.
Referenced by menu_change_shortcut(), ui_block_func_COL(), ui_block_func_ICONROW(), ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), ui_block_func_POPUP(), ui_handle_menu_event(), wm_block_create_redo(), wm_block_dialog_create(), wm_block_search_menu(), wm_enum_search_menu(), and wm_operator_ui_create().
#define UI_BLOCK_NO_FLIP 2048
Definition at line 118 of file UI_interface.h.
Referenced by ui_block_func_MENUSTR(), ui_popup_block_scrolltest(), ui_popup_menu_create(), uiBlockFlipOrder(), uiItemsEnumR(), and uiItemsFullEnumO().
#define UI_BLOCK_NUMSELECT 8
Definition at line 110 of file UI_interface.h.
Referenced by ui_block_func_POPUP(), ui_handle_menu_event(), ui_popup_block_create(), and uiEndBlock().
#define UI_BLOCK_OUT_1 1024
Definition at line 117 of file UI_interface.h.
Referenced by ui_block_func_COL(), and ui_handle_menu_event().
#define UI_BLOCK_POPUP 512
Definition at line 116 of file UI_interface.h.
Referenced by ui_popup_block_create(), and widget_menu_back().
#define UI_BLOCK_POPUP_MEMORY 4096
Definition at line 119 of file UI_interface.h.
Referenced by button_activate_exit(), ui_block_func_POPUP(), and uiPupMenuBegin().
#define UI_BLOCK_REDRAW 2
Definition at line 108 of file UI_interface.h.
Referenced by id_search_menu(), operator_search_menu(), tool_search_menu(), ui_block_func_COL(), and ui_block_func_POPUP().
#define UI_BLOCK_RET_1 4
Definition at line 109 of file UI_interface.h.
Referenced by id_search_menu(), menu_add_shortcut(), operator_search_menu(), tool_search_menu(), ui_block_func_POPUP(), wm_block_create_redo(), wm_block_dialog_create(), wm_block_search_menu(), wm_enum_search_menu(), and wm_operator_ui_create().
#define UI_BUT_ALIGN (UI_BUT_ALIGN_TOP|UI_BUT_ALIGN_LEFT|UI_BUT_ALIGN_RIGHT|UI_BUT_ALIGN_DOWN)
Definition at line 149 of file UI_interface.h.
Referenced by ui_block_do_align_but(), ui_def_but(), uiBlockBeginAlign(), uiBlockEndAlign(), uiBlockFlipOrder(), uiEndBlock(), and widget_roundbox_set().
#define UI_BUT_ALIGN_DOWN (1<<17)
Definition at line 153 of file UI_interface.h.
Referenced by ui_block_do_align_but(), uiBlockBeginAlign(), and widget_roundbox_set().
#define UI_BUT_ALIGN_LEFT (1<<15)
Definition at line 151 of file UI_interface.h.
Referenced by ui_block_do_align_but(), and widget_roundbox_set().
#define UI_BUT_ALIGN_RIGHT (1<<16)
Definition at line 152 of file UI_interface.h.
Referenced by ui_block_do_align_but(), ui_text_label_rightclip(), ui_text_leftclip(), and widget_roundbox_set().
#define UI_BUT_ALIGN_TOP (1<<14)
Definition at line 150 of file UI_interface.h.
Referenced by ui_block_do_align_but(), and widget_roundbox_set().
#define UI_BUT_ANIMATED (1<<20)
Definition at line 157 of file UI_interface.h.
Referenced by ui_but_anim_flag(), ui_but_menu(), widget_icon_has_anim(), widget_state(), widget_state_numslider(), and widget_swatch().
#define UI_BUT_ANIMATED_KEY (1<<21)
Definition at line 158 of file UI_interface.h.
Referenced by ui_but_anim_flag(), ui_but_menu(), widget_icon_has_anim(), widget_state(), widget_state_numslider(), and widget_swatch().
#define UI_BUT_COLOR_CUBIC (1<<31)
Definition at line 169 of file UI_interface.h.
Referenced by ui_draw_but_HSVCIRCLE(), ui_numedit_but_HSVCIRCLE(), and uiTemplateColorWheel().
#define UI_BUT_COLOR_LOCK (1<<19)
Definition at line 156 of file UI_interface.h.
Referenced by ui_draw_but_HSVCIRCLE(), ui_ndofedit_but_HSVCIRCLE(), ui_numedit_but_HSVCIRCLE(), and uiTemplateColorWheel().
#define UI_BUT_DISABLED (1<<18)
Definition at line 155 of file UI_interface.h.
Referenced by draw_group_socket(), draw_modifier(), template_ID(), ui_def_but(), ui_def_but_operator_ptr(), ui_def_but_operator_text(), ui_do_button(), ui_draw_but(), ui_item_disabled(), ui_item_layout(), ui_textedit_next_but(), ui_textedit_prev_but(), ui_tooltip_create(), uiDefAutoButR(), uiEndBlock(), uiTemplateList(), and widget_state_menu_item().
#define UI_BUT_DRIVEN (1<<22)
Definition at line 159 of file UI_interface.h.
Referenced by ui_but_anim_flag(), ui_but_menu(), ui_tooltip_create(), widget_icon_has_anim(), widget_state(), widget_state_numslider(), and widget_swatch().
#define UI_BUT_IMMEDIATE (1<<27)
Definition at line 164 of file UI_interface.h.
Referenced by button_activate_init(), ui_do_but_HOTKEYEVT(), and ui_item_with_label().
#define UI_BUT_INACTIVE (1<<24)
Definition at line 161 of file UI_interface.h.
Referenced by ui_draw_but(), ui_item_layout(), and widget_state_menu_item().
#define UI_BUT_LAST_ACTIVE (1<<25)
Definition at line 162 of file UI_interface.h.
Referenced by button_activate_exit(), ui_context_button_active(), uiContextAnimUpdate(), uiFileBrowseContextProperty(), and uiIDContextProperty().
#define UI_BUT_NO_TOOLTIP (1<<28)
Definition at line 165 of file UI_interface.h.
Referenced by list_item_row(), ui_tooltip_create(), and uiTemplateList().
#define UI_BUT_NO_UTF8 (1<<29)
Definition at line 166 of file UI_interface.h.
Referenced by file_draw_buttons(), file_draw_list(), and ui_is_but_utf8().
#define UI_BUT_NODE_ACTIVE 4096
Definition at line 145 of file UI_interface.h.
Referenced by uiTemplateNodeLink(), and widget_state().
#define UI_BUT_NODE_LINK 2048
Definition at line 144 of file UI_interface.h.
Referenced by ui_draw_but(), uiTemplateNodeLink(), and widget_draw_text_icon().
#define UI_BUT_REDALERT (1<<23)
Definition at line 160 of file UI_interface.h.
Referenced by file_draw_buttons(), template_ID(), ui_but_search_test(), uiItemFullO_ptr(), uiItemFullR(), widget_icon_has_anim(), widget_state(), and widget_swatch().
#define UI_BUT_UNDO (1<<26)
Definition at line 163 of file UI_interface.h.
Referenced by buttons_context_draw(), ED_area_header_standardbuttons(), ED_area_header_switchbutton(), file_draw_buttons(), file_draw_list(), id_search_menu(), ui_apply_autokey_undo(), ui_def_but(), ui_def_but_operator_ptr(), ui_def_but_operator_text(), ui_def_but_rna(), uiLayoutOperatorButs(), and uiTemplateHeader3D().
#define UI_BUT_VEC_SIZE_LOCK (1<<30)
Definition at line 168 of file UI_interface.h.
Referenced by ui_ndofedit_but_HSVCIRCLE(), ui_numedit_but_HSVCIRCLE(), and uiTemplateColorWheel().
#define UI_CENTER 16
Definition at line 99 of file UI_interface.h.
Referenced by menu_add_shortcut(), menu_change_shortcut(), and ui_block_position().
#define UI_COMPACT_PANEL_WIDTH 160
Definition at line 172 of file UI_interface.h.
Referenced by ED_spacetype_clip(), and ED_spacetype_text().
#define UI_DIRECTION (UI_TOP|UI_DOWN|UI_LEFT|UI_RIGHT)
Definition at line 93 of file UI_interface.h.
Referenced by ui_block_position().
#define UI_DOWN 2
Definition at line 95 of file UI_interface.h.
Referenced by id_search_menu(), operator_search_menu(), tool_search_menu(), ui_block_func_POPUP(), ui_block_position(), ui_handle_menu_event(), and widget_menu_back().
#define UI_DPI_FAC (sqrtf((float)U.dpi) / 8.48528137423857f)
Definition at line 176 of file UI_interface.h.
Referenced by file_font_pointsize(), node_resize_modal(), uiblock_layer_pass_arrow_buttons(), uiTemplateHeader3D(), and uiTemplateImageLayers().
#define UI_DPI_ICON_FAC (((float)U.dpi) / 72.0f)
Definition at line 177 of file UI_interface.h.
Referenced by icon_draw_size(), v3d_editvertex_buts(), and widget_draw_text_icon().
#define UI_DPI_ICON_SIZE ((float)16 * UI_DPI_ICON_FAC)
Definition at line 179 of file UI_interface.h.
Referenced by ui_draw_menu_item(), ui_text_leftclip(), ui_textedit_set_cursor_pos(), widget_draw_icon(), and widget_draw_text().
#define UI_EMBOSS 0
Definition at line 87 of file UI_interface.h.
Referenced by ANIM_channel_draw_widgets(), ANIM_uiTemplate_fmodifier_draw(), buttons_header_buttons(), controller_state_mask_menu(), curvemap_brush_tools_func(), curvemap_buttons_layout(), curvemap_clipping_func(), curvemap_tools_func(), draw_actuatorbuttons(), draw_channel_names(), draw_constraint(), draw_group_socket(), draw_modifier(), draw_nla_channel_list(), draw_outliner(), ED_area_header_standardbuttons(), ED_region_header(), ED_region_panels(), file_draw_buttons(), file_draw_list(), file_panel_category(), gp_drawui_layer(), graph_draw_channel_names(), graph_panel_drivers(), id_search_menu(), list_item_row(), logic_buttons(), logic_buttons_new(), menu_add_shortcut(), menu_change_shortcut(), node_draw_basis(), node_draw_hidden(), node_uiblocks_init(), operator_search_menu(), outliner_draw_restrictbuts(), socket_component_menu(), tool_search_menu(), ui_block_func_COL(), ui_item_menu(), ui_node_draw_input(), uiItemFullO_ptr(), uiItemFullR(), uiTemplateHeader3D(), uiTemplateReportsBanner(), wm_block_create_redo(), wm_block_create_splash(), wm_block_dialog_create(), wm_block_search_menu(), wm_enum_search_menu(), and wm_operator_ui_create().
#define UI_EMBOSSN 1
Definition at line 88 of file UI_interface.h.
Referenced by ANIM_channel_draw_widgets(), ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), curvemap_buttons_layout(), draw_constraint(), draw_group_socket(), draw_modifier(), ED_area_header_standardbuttons(), file_panel_category(), gp_drawui_layer(), graph_panel_drivers(), list_item_row(), node_draw_basis(), node_draw_hidden(), node_socket_button_output_file(), outliner_draw_restrictbuts(), ui_do_but_TEX(), ui_draw_but(), ui_item_array(), ui_node_draw_input(), uiItemFullO_ptr(), uiItemFullR(), and uiTemplateReportsBanner().
#define UI_EMBOSSP 2
Definition at line 89 of file UI_interface.h.
Referenced by actuator_menu(), controller_menu(), node_socket_button_output_file(), object_state_mask_menu(), sensor_menu(), ui_but_draw_menu_icon(), ui_draw_but(), ui_item_array(), ui_popup_menu_create(), uiPupMenuBegin(), and wm_block_create_splash().
#define UI_EMBOSST 3
Definition at line 90 of file UI_interface.h.
Referenced by outliner_draw_keymapbuts(), and outliner_draw_rnabuts().
#define UI_FLAG_UNUSED 8192
Definition at line 146 of file UI_interface.h.
#define UI_GRAD_H 3
Definition at line 256 of file UI_interface.h.
Referenced by curvemap_buttons_layout(), ui_draw_but_CURVE(), ui_draw_but_HSVCUBE(), ui_draw_gradient(), ui_ndofedit_but_HSVCUBE(), and ui_numedit_but_HSVCUBE().
#define UI_GRAD_HS 2
Definition at line 255 of file UI_interface.h.
Referenced by ui_draw_but_HSVCUBE(), ui_draw_gradient(), ui_ndofedit_but_HSVCUBE(), ui_numedit_but_HSVCUBE(), and uiBlockPicker().
#define UI_GRAD_HV 1
Definition at line 254 of file UI_interface.h.
Referenced by ui_draw_but_HSVCUBE(), ui_draw_gradient(), ui_ndofedit_but_HSVCUBE(), ui_numedit_but_HSVCUBE(), and uiBlockPicker().
#define UI_GRAD_S 4
Definition at line 257 of file UI_interface.h.
Referenced by ui_draw_but_HSVCUBE(), ui_draw_gradient(), ui_ndofedit_but_HSVCUBE(), and ui_numedit_but_HSVCUBE().
#define UI_GRAD_SV 0
Definition at line 253 of file UI_interface.h.
Referenced by ui_draw_but_HSVCUBE(), ui_draw_gradient(), ui_ndofedit_but_HSVCUBE(), ui_numedit_but_HSVCUBE(), and uiBlockPicker().
#define UI_GRAD_V 5
Definition at line 258 of file UI_interface.h.
Referenced by ui_draw_but_HSVCUBE(), ui_draw_gradient(), ui_ndofedit_but_HSVCUBE(), and ui_numedit_but_HSVCUBE().
#define UI_GRAD_V_ALT 9
Definition at line 260 of file UI_interface.h.
Referenced by circle_picker(), ui_do_but_HSVCUBE(), ui_do_button(), ui_draw_but(), ui_ndofedit_but_HSVCUBE(), ui_numedit_but_HSVCUBE(), and uiTemplateColorWheel().
#define UI_ICON_LEFT 128
Definition at line 139 of file UI_interface.h.
Referenced by file_panel_category(), template_ID(), ui_but_add_search(), ui_but_mouse_inside_icon(), ui_def_but(), ui_def_but_rna(), uiDefIconBlockBut(), uiDefIconMenuBut(), uiDefIconTextBlockBut(), uiDefIconTextBut(), uiDefIconTextButO_ptr(), uiDefIconTextButR(), uiDefIconTextButR_prop(), uiDefIconTextMenuBut(), uiDefSearchBut(), and widget_draw_icon().
#define UI_ICON_PREVIEW 512
Definition at line 141 of file UI_interface.h.
Referenced by template_ID(), and widget_draw_icon().
#define UI_ICON_SUBMENU 256
Definition at line 140 of file UI_interface.h.
Referenced by ui_but_draw_menu_icon(), uiDefIconTextBlockBut(), uiDefIconTextMenuBut(), uiTemplateTextureUser(), and widget_draw_icon().
#define UI_ID_ADD_NEW 4
Definition at line 524 of file UI_interface.h.
Referenced by template_ID(), template_id_cb(), and ui_template_id().
#define UI_ID_ALONE 16
Definition at line 526 of file UI_interface.h.
Referenced by template_ID(), and template_id_cb().
#define UI_ID_AUTO_NAME 128
Definition at line 529 of file UI_interface.h.
Referenced by template_id_cb().
#define UI_ID_BROWSE 2
Definition at line 523 of file UI_interface.h.
Referenced by template_ID(), template_id_cb(), uiTemplateID(), uiTemplateIDBrowse(), and uiTemplateIDPreview().
#define UI_ID_BROWSE_RENDER 1024
Definition at line 532 of file UI_interface.h.
#define UI_ID_DELETE 32
Definition at line 527 of file UI_interface.h.
Referenced by template_ID(), template_id_cb(), uiTemplateID(), and uiTemplateIDPreview().
#define UI_ID_FAKE_USER 256
Definition at line 530 of file UI_interface.h.
Referenced by template_id_cb().
#define UI_ID_FULL (UI_ID_RENAME|UI_ID_BROWSE|UI_ID_ADD_NEW|UI_ID_OPEN|UI_ID_ALONE|UI_ID_DELETE|UI_ID_LOCAL)
Definition at line 534 of file UI_interface.h.
#define UI_ID_LOCAL 64
Definition at line 528 of file UI_interface.h.
Referenced by template_ID(), and template_id_cb().
#define UI_ID_OPEN 8
Definition at line 525 of file UI_interface.h.
Referenced by template_ID(), template_id_cb(), and ui_template_id().
#define UI_ID_PIN 512
Definition at line 531 of file UI_interface.h.
Referenced by template_id_cb().
#define UI_ID_PREVIEWS 2048
Definition at line 533 of file UI_interface.h.
Referenced by template_ID(), and uiTemplateIDPreview().
#define UI_ID_RENAME 1
Definition at line 522 of file UI_interface.h.
Referenced by template_ID(), uiTemplateID(), uiTemplateIDBrowse(), and uiTemplateIDPreview().
#define UI_ITEM_O_RETURN_PROPS 1
Definition at line 667 of file UI_interface.h.
Referenced by graph_fmodifier_add_invoke(), make_proxy_invoke(), poselib_add_menu_invoke__replacemenu(), uiItemFullO_ptr(), and unpack_menu().
#define UI_ITEM_R_EVENT 32
Definition at line 672 of file UI_interface.h.
Referenced by draw_sensor_keyboard(), and ui_item_with_label().
#define UI_ITEM_R_EXPAND 2
Definition at line 668 of file UI_interface.h.
Referenced by curvemap_buttons_layout(), node_composit_buts_blur(), node_composit_buts_channel_matte(), node_composit_buts_color_spill(), node_composit_buts_splitviewer(), node_composit_buts_view_levels(), node_texture_buts_proc(), socket_component_menu(), uiItemFullR(), uiTemplateImage(), uiTemplateImageSettings(), and uiTemplatePreview().
#define UI_ITEM_R_FULL_EVENT 64
Definition at line 673 of file UI_interface.h.
Referenced by menu_add_shortcut(), menu_change_shortcut(), and ui_item_with_label().
#define UI_ITEM_R_ICON_ONLY 16
Definition at line 671 of file UI_interface.h.
Referenced by ANIM_uiTemplate_fmodifier_draw(), draw_constraint(), node_composit_buts_file_output_details(), node_composit_buts_image(), ui_item_with_label(), ui_node_draw_input(), uiItemFullR(), uiTemplateAnyID(), uiTemplateHeader3D(), and v3d_transform_butsR().
#define UI_ITEM_R_IMMEDIATE 256
Definition at line 675 of file UI_interface.h.
Referenced by menu_add_shortcut(), menu_change_shortcut(), and ui_item_with_label().
#define UI_ITEM_R_NO_BG 128
Definition at line 674 of file UI_interface.h.
Referenced by draw_actuator_header(), draw_controller_header(), draw_sensor_header(), logic_buttons_new(), uiItemFullO_ptr(), and uiItemFullR().
#define UI_ITEM_R_SLIDER 4
Definition at line 669 of file UI_interface.h.
Referenced by draw_actuator_constraint(), draw_actuator_motion(), gp_drawui_layer(), node_composit_buts_channel_matte(), node_composit_buts_chroma_matte(), node_composit_buts_color_matte(), node_composit_buts_color_spill(), node_composit_buts_diff_matte(), node_composit_buts_distance_matte(), node_composit_buts_glare(), node_composit_buts_hue_sat(), node_composit_buts_luma_matte(), node_composit_buts_tonemap(), and uiItemFullR().
#define UI_ITEM_R_TOGGLE 8
Definition at line 670 of file UI_interface.h.
Referenced by draw_actuator_action(), draw_actuator_constraint(), draw_actuator_edit_object(), draw_actuator_filter_2d(), draw_actuator_motion(), draw_actuator_random(), draw_controller_python(), draw_modifier__fn_generator(), draw_sensor_collision(), draw_sensor_internal_header(), draw_sensor_keyboard(), draw_sensor_ray(), logic_buttons_new(), uiItemFullR(), and v3d_transform_butsR().
#define UI_LAYOUT_ALIGN_CENTER 2
Definition at line 664 of file UI_interface.h.
Referenced by rna_def_ui_layout().
#define UI_LAYOUT_ALIGN_EXPAND 0
Definition at line 662 of file UI_interface.h.
Referenced by draw_modifier(), gp_drawui_layer(), rna_def_ui_layout(), ui_item_fit(), and ui_layout_vary_direction().
#define UI_LAYOUT_ALIGN_LEFT 1
Definition at line 663 of file UI_interface.h.
Referenced by ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), curvemap_buttons_layout(), file_panel_category(), logic_buttons_new(), and rna_def_ui_layout().
#define UI_LAYOUT_ALIGN_RIGHT 3
Definition at line 665 of file UI_interface.h.
Referenced by ANIM_uiTemplate_fmodifier_draw(), curvemap_buttons_layout(), gp_drawui_layer(), and rna_def_ui_layout().
#define UI_LAYOUT_HEADER 1
Definition at line 655 of file UI_interface.h.
Referenced by ED_region_header(), ED_region_panels(), ui_item_menu(), ui_layout_vary_direction(), and ui_litem_layout_root().
#define UI_LAYOUT_HORIZONTAL 0
Definition at line 651 of file UI_interface.h.
Referenced by ED_region_header(), ED_region_panels(), ui_item_enum_expand(), ui_item_local_sublayout(), ui_layout_local_dir(), and uiBlockLayout().
#define UI_LAYOUT_MENU 2
Definition at line 656 of file UI_interface.h.
Referenced by ui_item_menu(), ui_popup_menu_create(), uiBlockLayout(), uiItemFullO_ptr(), uiItemFullR(), uiItemL_(), uiItemM(), uiItemMenuEnumO(), uiItemMenuEnumR(), uiItemV(), and uiPupMenuBegin().
#define UI_LAYOUT_OP_SHOW_EMPTY 2
Definition at line 679 of file UI_interface.h.
Referenced by file_panel_operator(), and uiLayoutOperatorButs().
#define UI_LAYOUT_OP_SHOW_TITLE 1
Definition at line 678 of file UI_interface.h.
Referenced by uiLayoutOperatorButs(), wm_block_create_redo(), and wm_block_dialog_create().
#define UI_LAYOUT_PANEL 0
Definition at line 654 of file UI_interface.h.
Referenced by ED_region_panels(), logic_buttons_new(), menu_add_shortcut(), menu_change_shortcut(), node_draw_group(), node_socket_button_output_file(), node_update_basis(), socket_component_menu(), ui_item_menu(), wm_block_create_redo(), wm_block_create_splash(), wm_block_dialog_create(), and wm_operator_ui_create().
#define UI_LAYOUT_TOOLBAR 3
Definition at line 657 of file UI_interface.h.
Referenced by ED_region_panels(), ui_item_menu(), and uiItemFullO_ptr().
#define UI_LAYOUT_VERTICAL 1
Definition at line 652 of file UI_interface.h.
Referenced by ED_region_panels(), logic_buttons_new(), menu_add_shortcut(), menu_change_shortcut(), node_draw_group(), node_socket_button_output_file(), node_update_basis(), socket_component_menu(), ui_layout_local_dir(), ui_popup_menu_create(), uiPupMenuBegin(), wm_block_create_redo(), wm_block_create_splash(), wm_block_dialog_create(), and wm_operator_ui_create().
#define UI_LEFT 4
Definition at line 96 of file UI_interface.h.
Referenced by ui_block_position().
#define UI_MAX_DRAW_STR 400
Definition at line 83 of file UI_interface.h.
Referenced by ui_but_copy_paste(), ui_check_but(), ui_def_but_rna(), ui_get_but_string_max_length(), ui_text_leftclip(), and ui_textedit_copypaste().
#define UI_MAX_NAME_STR 128
Definition at line 84 of file UI_interface.h.
Referenced by node_sockets_panel(), template_ID(), template_texture_user_menu(), ui_def_but(), ui_node_draw_input(), ui_node_menu_column(), ui_node_sock_name(), uiBeginPanel(), uiItemFullR(), uiTemplateNodeLink(), and uiTemplateTextureUser().
#define UI_PANEL_WIDTH 340
Definition at line 171 of file UI_interface.h.
Referenced by ED_region_panels(), and ui_panels_size().
#define UI_PNL_CLOSE 32
Definition at line 133 of file UI_interface.h.
Referenced by ui_draw_aligned_panel(), ui_draw_aligned_panel_header(), and ui_handle_panel_header().
#define UI_PNL_SCALE 512
Definition at line 134 of file UI_interface.h.
Referenced by ui_draw_aligned_panel(), and ui_handler_panel_region().
#define UI_PNL_SOLID 2
Definition at line 132 of file UI_interface.h.
Referenced by ui_draw_aligned_panel().
#define UI_RB_ALPHA (UI_CNR_ALL + 1)
Definition at line 698 of file UI_interface.h.
Referenced by region_draw_azone_tab(), uiRoundBox(), uiRoundRect(), and wm_drop_operator_draw().
#define UI_RETURN_CANCEL 1
Definition at line 123 of file UI_interface.h.
Referenced by button_activate_exit(), ui_handle_button_return_submenu(), ui_handle_menu_event(), and ui_handle_menu_return_submenu().
#define UI_RETURN_OK 2
Definition at line 124 of file UI_interface.h.
Referenced by button_activate_exit(), close_popup_cb(), ui_handle_button_return_submenu(), ui_handle_menu_event(), ui_handle_menu_return_submenu(), and ui_handler_popup().
#define UI_RETURN_OUT 4
Definition at line 125 of file UI_interface.h.
Referenced by ui_handle_button_return_submenu(), and ui_handle_menu_event().
#define UI_RETURN_POPUP_OK 16
Definition at line 127 of file UI_interface.h.
Referenced by ui_handle_menu_event(), and ui_handler_popup().
#define UI_RETURN_UPDATE 8
Definition at line 126 of file UI_interface.h.
Referenced by do_hex_rna_cb(), do_hsv_rna_cb(), do_picker_rna_cb(), ui_handle_button_return_submenu(), ui_handle_menu_event(), ui_handle_menu_return_submenu(), and ui_picker_small_wheel_cb().
#define UI_RIGHT 8
Definition at line 97 of file UI_interface.h.
Referenced by curvemap_brush_tools_func(), curvemap_clipping_func(), curvemap_tools_func(), ui_block_func_POPUP(), ui_block_position(), and ui_handle_menu_event().
#define UI_SCROLL_ARROWS 2
Definition at line 279 of file UI_interface.h.
Referenced by UI_view2d_scrollers_draw(), and uiWidgetScrollDraw().
#define UI_SCROLL_NO_OUTLINE 4
Definition at line 280 of file UI_interface.h.
Referenced by uiWidgetScrollDraw(), and widget_progressbar().
#define UI_SCROLL_PRESSED 1
Definition at line 278 of file UI_interface.h.
Referenced by draw_textscroll(), UI_view2d_scrollers_draw(), uiWidgetScrollDraw(), and widget_scroll().
#define UI_SHIFT_FLIPPED 32
Definition at line 100 of file UI_interface.h.
Referenced by ui_block_position().
#define UI_TEXT_LEFT 64
Definition at line 138 of file UI_interface.h.
Referenced by file_panel_category(), template_texture_user_menu(), ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), ui_but_add_search(), ui_def_but(), ui_draw_but(), ui_item_enum_expand(), ui_item_menu(), ui_node_draw_input(), ui_node_menu_column(), ui_template_node_link_menu(), uiDefSearchBut(), uiItemFullO_ptr(), uiItemsEnumR(), uiItemsFullEnumO(), uiPupMenuBegin(), uiTemplateNodeLink(), uiTemplateTextureUser(), widget_draw_text(), and widget_draw_text_icon().
#define UI_TEXT_RIGHT 1024
Definition at line 143 of file UI_interface.h.
#define UI_TOP 1
Definition at line 94 of file UI_interface.h.
Referenced by actuator_menu(), controller_menu(), controller_state_mask_menu(), draw_group_socket(), object_state_mask_menu(), sensor_menu(), ui_block_func_COL(), ui_block_func_POPUP(), ui_block_position(), ui_handle_menu_event(), ui_popup_block_scrolltest(), and widget_menu_back().
#define UI_UNIT_X U.widget_unit
Definition at line 659 of file UI_interface.h.
Referenced by ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), buttons_header_buttons(), curvemap_brush_tools_func(), curvemap_buttons_layout(), curvemap_clipping_func(), curvemap_tools_func(), do_outliner_item_activate(), do_outliner_item_rename(), draw_group_socket(), draw_modifier(), ED_area_header_standardbuttons(), ED_area_header_switchbutton(), ED_region_header(), file_draw_buttons(), file_panel_category(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_key_properties(), list_item_row(), logic_buttons(), logic_buttons_new(), node_draw_basis(), node_draw_hidden(), outliner_buttons(), outliner_draw_hierarchy(), outliner_draw_iconrow(), outliner_draw_keymapbuts(), outliner_draw_restrictbuts(), outliner_draw_tree_element(), outliner_dropzone_parent(), outliner_dropzone_parent_clear(), outliner_rna_width(), outliner_set_coord_tree_element(), region_scale_get_maxsize(), region_scale_modal(), template_ID(), template_texture_user_menu(), tselem_draw_icon_uibut(), ui_block_func_ICONROW(), ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), ui_item_array(), ui_item_rna_size(), ui_item_with_label(), ui_litem_min_width(), ui_node_draw_input(), ui_node_menu_column(), ui_template_node_link_menu(), ui_text_icon_width(), uiBlockLayout(), uiBlockPicker(), uiTemplateEditModeSelection(), uiTemplateHeader3D(), uiTemplateImage(), uiTemplateLayers(), uiTemplateList(), uiTemplateNodeLink(), uiTemplateOperatorSearch(), uiTemplatePreview(), uiTemplateReportsBanner(), uiTemplateRunningJobs(), uiTemplateTextureShow(), uiTemplateTextureUser(), view3d_panel_tool_shelf(), wm_block_search_menu(), wm_debug_menu_invoke(), and wm_enum_search_menu().
#define UI_UNIT_Y U.widget_unit
Definition at line 660 of file UI_interface.h.
Referenced by ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), colorband_buttons_large(), colorband_buttons_small(), curvemap_brush_tools_func(), curvemap_buttons_layout(), curvemap_clipping_func(), curvemap_tools_func(), do_outliner_item_activate(), do_outliner_item_openclose(), do_outliner_item_rename(), do_outliner_operation_event(), draw_controller_header(), draw_modifier(), draw_modifier__generator(), ED_area_header_standardbuttons(), ED_area_header_switchbutton(), ED_area_headersize(), ED_region_header(), ED_region_panels(), file_draw_buttons(), file_draw_list(), file_panel_category(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_key_properties(), list_item_row(), logic_buttons(), logic_buttons_new(), node_draw_basis(), operator_search_menu(), outliner_back(), outliner_buttons(), outliner_draw_hierarchy(), outliner_draw_iconrow(), outliner_draw_keymapbuts(), outliner_draw_restrictbuts(), outliner_draw_restrictcols(), outliner_draw_rnabuts(), outliner_draw_selection(), outliner_draw_struct_marks(), outliner_draw_tree(), outliner_draw_tree_element(), outliner_dropzone_parent(), outliner_dropzone_parent_clear(), outliner_height(), outliner_item_activate(), outliner_item_border_select(), region_rect_recursive(), region_scale_get_maxsize(), region_scale_modal(), template_ID(), template_texture_user_menu(), tselem_draw_icon_uibut(), ui_block_func_ICONROW(), ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), ui_block_func_POPUP(), ui_but_menu(), ui_item_array(), ui_item_disabled(), ui_item_menu(), ui_item_rna_size(), ui_node_menu_column(), ui_template_node_link_menu(), uiblock_layer_pass_buttons(), uiBlockLayout(), uiBlockPicker(), uiItemFullO_ptr(), uiItemL_(), uiItemV(), uiPupMenuBegin(), uiSearchBoxhHeight(), uiTemplateEditModeSelection(), uiTemplateHeader3D(), uiTemplateHistogram(), uiTemplateImage(), uiTemplateLayers(), uiTemplateList(), uiTemplateNodeLink(), uiTemplateOperatorSearch(), uiTemplatePreview(), uiTemplateReportsBanner(), uiTemplateRunningJobs(), uiTemplateTextureShow(), uiTemplateTextureUser(), uiTemplateTrack(), uiTemplateVectorscope(), uiTemplateWaveform(), view3d_panel_tool_shelf(), wm_block_create_redo(), wm_block_create_splash(), wm_block_dialog_create(), wm_block_search_menu(), wm_debug_menu_invoke(), and wm_enum_search_menu().
#define VECTORSCOPE (50<<9)
Definition at line 247 of file UI_interface.h.
Referenced by ui_do_button(), ui_draw_but(), and uiTemplateVectorscope().
#define WAVEFORM (49<<9)
Definition at line 246 of file UI_interface.h.
Referenced by ui_apply_button(), ui_do_button(), ui_draw_but(), and uiTemplateWaveform().
Typedef Documentation
typedef struct AutoComplete AutoComplete
Definition at line 601 of file UI_interface.h.
typedef struct uiBlock uiBlock
Definition at line 76 of file UI_interface.h.
typedef void(* uiBlockCancelFunc)(void *arg1)
Definition at line 350 of file UI_interface.h.
typedef uiBlock*(* uiBlockCreateFunc)(struct bContext *C, struct ARegion *ar, void *arg1)
Definition at line 349 of file UI_interface.h.
typedef void(* uiBlockHandleFunc)(struct bContext *C, void *arg, int event)
Definition at line 305 of file UI_interface.h.
typedef struct uiBut uiBut
Definition at line 75 of file UI_interface.h.
typedef void(* uiButCompleteFunc)(struct bContext *C, char *str, void *arg)
Definition at line 303 of file UI_interface.h.
typedef void(* uiButHandleFunc)(struct bContext *C, void *arg1, void *arg2)
Definition at line 300 of file UI_interface.h.
typedef void(* uiButHandleNFunc)(struct bContext *C, void *argN, void *arg2)
Definition at line 302 of file UI_interface.h.
typedef void(* uiButHandleRenameFunc)(struct bContext *C, void *arg, char *origstr)
Definition at line 301 of file UI_interface.h.
typedef void(* uiButSearchFunc)(const struct bContext *C, void *arg, const char *str, uiSearchItems *items)
Definition at line 304 of file UI_interface.h.
typedef void(* uiIDPoinFunc)(struct bContext *C, struct ID *id, int event)
Definition at line 537 of file UI_interface.h.
typedef void(* uiIDPoinFuncFP)(struct bContext *C, const char *str, struct ID **idpp)
Definition at line 536 of file UI_interface.h.
typedef struct uiLayout uiLayout
Definition at line 78 of file UI_interface.h.
typedef void(* uiMenuCreateFunc)(struct bContext *C, struct uiLayout *layout, void *arg1)
Definition at line 309 of file UI_interface.h.
typedef void(* uiMenuHandleFunc)(struct bContext *C, void *arg, int event)
Definition at line 310 of file UI_interface.h.
typedef struct uiPopupBlockHandle uiPopupBlockHandle
Definition at line 77 of file UI_interface.h.
typedef struct uiPopupMenu uiPopupMenu
Definition at line 319 of file UI_interface.h.
typedef struct uiSearchItems uiSearchItems
Definition at line 298 of file UI_interface.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
UI_BLOCK_BOUNDS
UI_BLOCK_BOUNDS_TEXT
UI_BLOCK_BOUNDS_POPUP_MOUSE
UI_BLOCK_BOUNDS_POPUP_MENU
UI_BLOCK_BOUNDS_POPUP_CENTER
Definition at line 393 of file UI_interface.h.
anonymous enum
Enumerator:
UI_CNR_TOP_LEFT
UI_CNR_TOP_RIGHT
UI_CNR_BOTTOM_RIGHT
UI_CNR_BOTTOM_LEFT
UI_CNR_NONE
UI_CNR_ALL
Definition at line 687 of file UI_interface.h.
Function Documentation
AutoComplete* autocomplete_begin (const char * startname, size_t maxlen)
Definition at line 2921 of file interface.c.
References AutoComplete::maxlen, MEM_callocN(), AutoComplete::startname, and AutoComplete::truncate.
Referenced by autocomplete_directory(), autocomplete_file(), autocomplete_id(), and ui_searchbox_autocomplete().
void autocomplete_do_name (AutoComplete * autocpl, const char * name)
Definition at line 2933 of file interface.c.
References BLI_strncpy(), AutoComplete::maxlen, AutoComplete::startname, and AutoComplete::truncate.
Referenced by autocomplete_directory(), autocomplete_file(), autocomplete_id(), and uiSearchItemAdd().
void autocomplete_end (AutoComplete * autocpl, char * autoname)
Definition at line 2962 of file interface.c.
References BLI_strncpy(), AutoComplete::maxlen, MEM_freeN(), AutoComplete::startname, and AutoComplete::truncate.
Referenced by autocomplete_directory(), autocomplete_file(), autocomplete_id(), and ui_searchbox_autocomplete().
void UI_add_popup_handlers (struct bContext * C, struct ListBase * handlers, uiPopupBlockHandle * popup)
Definition at line 6556 of file interface_handlers.c.
References ui_handler_popup(), ui_handler_remove_popup(), and WM_event_add_ui_handler().
Referenced by ui_popup_menu_create(), uiPupBlockEx(), uiPupBlockO(), and uiPupMenuEnd().
void UI_add_region_handlers (struct ListBase * handlers)
Definition at line 6550 of file interface_handlers.c.
References NULL, ui_handler_region(), ui_handler_remove_region(), WM_event_add_ui_handler(), and WM_event_remove_ui_handler().
Referenced by ed_default_handlers(), and ui_popup_block_create().
int UI_but_active_drop_name (struct bContext * C)
Definition at line 4845 of file interface_handlers.c.
References CTX_wm_region(), ELEM3, IDPOIN, SEARCH_MENU, TEX, uiBut::type, and ui_but_find_activated().
Referenced by wm_drop_operator_options().
void UI_buttons_operatortypes (void)
Definition at line 764 of file interface_ops.c.
References UI_OT_copy_data_path_button(), UI_OT_copy_to_selected_button(), UI_OT_eyedropper(), UI_OT_reports_to_textblock(), UI_OT_reset_default_button(), UI_OT_reset_default_theme(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
void UI_DrawString (float x, float y, const char * str)
Definition at line 284 of file interface_style.c.
References BLF_disable(), BLF_draw(), BLF_DRAW_STR_DUMMY_MAX, BLF_enable(), BLF_KERNING_DEFAULT, BLF_position(), uiFontStyle::kerning, UI_GetStyle(), uiFontStyle::uifont_id, uiStyleFontSet(), and uiStyle::widget.
Referenced by ANIM_channel_draw(), draw_cfra_number(), draw_marker(), draw_nla_channel_list_gl(), outliner_draw_tree_element(), wm_drags_draw(), and wm_drop_operator_draw().
void UI_DrawTriIcon (float x, float y, char dir)
Definition at line 333 of file interface_panel.c.
References ui_draw_anti_tria().
Referenced by node_draw_basis(), node_draw_hidden(), and ui_draw_menu_back().
void UI_editsource_active_but_test (uiBut * but)
Referenced by ui_def_but().
int UI_editsource_enable_check (void)
Referenced by ui_def_but().
void UI_exit (void)
Definition at line 3683 of file interface.c.
References ui_resources_free().
Referenced by WM_exit_ext().
int UI_GetStringWidth (const char * str)
Definition at line 265 of file interface_style.c.
References BLF_disable(), BLF_enable(), BLF_KERNING_DEFAULT, BLF_width(), uiFontStyle::kerning, UI_GetStyle(), uiFontStyle::uifont_id, uiStyleFontSet(), and uiStyle::widget.
Referenced by draw_cfra_number(), file_draw_buttons(), node_draw_basis(), outliner_buttons(), outliner_draw_tree_element(), ui_item_with_label(), ui_text_icon_width(), wm_drags_draw(), and wm_drop_operator_draw().
uiStyle* UI_GetStyle (void)
Definition at line 256 of file interface_style.c.
References NULL.
Referenced by clip_draw_curfra_label(), ED_region_header(), ED_region_info_draw(), ED_region_panels(), file_draw_string(), file_font_pointsize(), file_string_width(), logic_buttons_new(), menu_add_shortcut(), menu_change_shortcut(), node_draw_group(), node_socket_button_output_file(), node_update_basis(), reset_exec(), socket_component_menu(), UI_DrawString(), UI_GetStringWidth(), ui_offset_panel_block(), ui_popup_menu_create(), ui_searchbox_create(), ui_text_bounds_block(), ui_textedit_set_cursor_pos(), ui_tooltip_create(), ui_tooltip_region_draw_cb(), UI_view2d_region_reinit(), uiDrawBlock(), uiPupMenuBegin(), uiTemplateReportsBanner(), wm_block_create_redo(), wm_block_create_splash(), wm_block_dialog_create(), and wm_operator_ui_create().
void UI_init (void)
Definition at line 3665 of file interface.c.
References ui_resources_init().
Referenced by WM_init().
void UI_init_userdef (void)
Definition at line 3671 of file interface.c.
References init_userdef_do_versions(), and uiStyleInit().
Referenced by wm_init_userdef().
void UI_reinit_font (void)
Definition at line 3678 of file interface.c.
References uiStyleInit().
void UI_remove_popup_handlers (struct ListBase * handlers, uiPopupBlockHandle * popup)
Definition at line 6561 of file interface_handlers.c.
References ui_handler_popup(), ui_handler_remove_popup(), and WM_event_remove_ui_handler().
Referenced by ui_handler_popup(), and uiPupBlockClose().
void UI_template_fix_linking (void)
Definition at line 76 of file interface_templates.c.
Referenced by uiBlockLayoutResolve().
uiBlock* uiBeginBlock (const struct bContext * C, struct ARegion * region, const char * name, short dt)
Referenced by actuator_menu(), buttons_header_buttons(), controller_menu(), controller_state_mask_menu(), curvemap_brush_tools_func(), curvemap_clipping_func(), curvemap_tools_func(), draw_channel_names(), draw_nla_channel_list(), draw_outliner(), ED_region_header(), ED_region_panels(), file_draw_buttons(), file_draw_list(), graph_draw_channel_names(), id_search_menu(), logic_buttons(), logic_buttons_new(), menu_add_shortcut(), menu_change_shortcut(), node_uiblocks_init(), object_state_mask_menu(), operator_search_menu(), sensor_menu(), socket_component_menu(), tool_search_menu(), ui_block_func_COL(), ui_popup_menu_create(), uiPupMenuBegin(), wm_block_create_redo(), wm_block_create_splash(), wm_block_dialog_create(), wm_block_search_menu(), wm_enum_search_menu(), and wm_operator_ui_create().
struct Panel* uiBeginPanel (struct ScrArea * sa, struct ARegion * ar, uiBlock * block, struct PanelType * pt, int * open) [read]
Definition at line 175 of file interface_panel.c.
References BLI_addtail(), BLI_strncpy(), BUT_VERTICAL, Panel::drawname, ListBase::first, PanelType::flag, Panel::flag, PanelType::idname, PanelType::label, MEM_callocN(), Panel::next, NULL, Panel::ofsx, Panel::ofsy, uiBlock::panel, panel_aligned(), Panel::panelname, ARegion::panels, Panel::paneltab, PNL_ACTIVE, PNL_CLOSED, PNL_CLOSEDX, PNL_CLOSEDY, PNL_DEFAULT_CLOSED, PNL_LAST_ADDED, PNL_NEW_ADDED, Panel::runtime_flag, Panel::sizex, Panel::sizey, Panel::sortorder, Panel::tabname, Panel::type, UI_MAX_NAME_STR, and ui_panel_copy_offset().
Referenced by ED_region_panels().
void uiBeginPanels (const struct bContext * C, struct ARegion * ar)
Referenced by ED_region_panels().
void uiBlockBeginAlign (uiBlock * block)
Definition at line 2336 of file interface.c.
References uiBlock::alignnr, uiBlock::flag, UI_BUT_ALIGN, UI_BUT_ALIGN_DOWN, and uiBlockEndAlign().
Referenced by buttons_header_buttons(), colorband_buttons_small(), controller_state_mask_menu(), curvemap_clipping_func(), draw_actuatorbuttons(), draw_constraint(), draw_controllerbuttons(), draw_default_sensor_header(), draw_group_socket(), draw_modifier(), draw_modifier__envelope(), draw_modifier__generator(), draw_sensorbuttons(), file_draw_buttons(), logic_buttons(), template_ID(), ui_item_array(), uiBlockPicker(), uiTemplateImage(), uiTemplateMarker(), uiTemplateReportsBanner(), uvedit_vertex_buttons(), v3d_editvertex_buts(), and view3d_panel_vgroup().
void uiBlockClearButLock (uiBlock * block)
Definition at line 1202 of file interface.c.
References uiBlock::lock, uiBlock::lockstr, and NULL.
Referenced by draw_constraint(), and draw_modifier().
void uiBlockClearFlag (uiBlock * block, int flag)
Definition at line 3318 of file interface.c.
References uiBlock::flag.
Referenced by wm_block_create_redo(), wm_block_dialog_create(), and wm_operator_ui_create().
void uiBlockEndAlign (uiBlock * block)
Definition at line 2358 of file interface.c.
References uiBlock::flag, and UI_BUT_ALIGN.
Referenced by buttons_header_buttons(), colorband_buttons_large(), colorband_buttons_small(), controller_state_mask_menu(), draw_actuatorbuttons(), draw_constraint(), draw_controllerbuttons(), draw_default_sensor_header(), draw_group_socket(), draw_modifier(), draw_modifier__generator(), draw_sensorbuttons(), file_draw_buttons(), logic_buttons(), node_update_basis(), template_ID(), ui_item_array(), uiblock_layer_pass_arrow_buttons(), uiBlockBeginAlign(), uiBlockPicker(), uiEndBlock(), uiTemplateMarker(), uiTemplateReportsBanner(), uvedit_vertex_buttons(), v3d_editvertex_buts(), and view3d_panel_vgroup().
void uiBlockFlipOrder (uiBlock * block)
Definition at line 3276 of file interface.c.
References BLI_addtail(), BLI_remlink(), uiBlock::buttons, ListBase::first, uiBut::flag, uiBlock::flag, ListBase::last, uiBut::next, next, NULL, SWAP, UI_BLOCK_NO_FLIP, UI_BUT_ALIGN, USER_MENUFIXEDORDER, uiBut::y1, and uiBut::y2.
Referenced by ui_block_func_POPUP(), and ui_block_position().
uiLayout* uiBlockLayout (uiBlock * block, int dir, int type, int x, int y, int size, int em, struct uiStyle * style)
Definition at line 2612 of file interface_layout.c.
References uiLayout::active, BLI_addtail(), uiLayoutRoot::block, uiLayout::context, uiBlock::curlayout, uiLayoutRoot::emh, uiLayoutRoot::emw, uiLayout::enabled, uiLayout::h, uiLayout::item, ITEM_LAYOUT_ROOT, uiLayoutRoot::layout, uiBlock::layouts, MEM_callocN(), NULL, uiLayoutRoot::opcontext, uiLayout::root, size(), uiLayout::space, uiLayoutRoot::style, uiStyle::templatespace, uiItem::type, uiLayoutRoot::type, UI_LAYOUT_HORIZONTAL, UI_LAYOUT_MENU, UI_UNIT_X, UI_UNIT_Y, uiLayout::w, WM_OP_INVOKE_REGION_WIN, uiLayout::x, and uiLayout::y.
Referenced by ED_region_header(), ED_region_panels(), logic_buttons_new(), menu_add_shortcut(), menu_change_shortcut(), node_draw_group(), node_socket_button_output_file(), node_update_basis(), socket_component_menu(), ui_popup_menu_create(), uiPupMenuBegin(), wm_block_create_redo(), wm_block_create_splash(), wm_block_dialog_create(), and wm_operator_ui_create().
void uiBlockLayoutResolve (uiBlock * block, int * x, int * y)
Definition at line 2695 of file interface_layout.c.
References BLI_freelistN(), uiBlock::curlayout, ListBase::first, uiLayoutRoot::layout, uiBlock::layouts, uiLayoutRoot::next, NULL, ui_layout_end(), ui_layout_free(), and UI_template_fix_linking().
Referenced by ED_region_header(), ED_region_panels(), logic_buttons_new(), node_draw_group(), node_socket_button_output_file(), node_update_basis(), ui_block_func_POPUP(), and uiEndBlock().
void uiBlockSetButLock (uiBlock * block, int val, const char * lockstr)
Definition at line 1194 of file interface.c.
References uiBlock::lock, and uiBlock::lockstr.
Referenced by draw_constraint(), draw_modifier(), uiLayoutOperatorButs(), uiTemplateConstraint(), and uiTemplateModifier().
void uiBlockSetButmFunc (uiBlock * block, uiMenuHandleFunc func, void * arg)
Definition at line 3419 of file interface.c.
References uiBlock::butm_func, and uiBlock::butm_func_arg.
Referenced by actuator_menu(), controller_menu(), curvemap_brush_tools_func(), curvemap_tools_func(), object_state_mask_menu(), and sensor_menu().
void uiBlockSetCurLayout (uiBlock * block, uiLayout * layout)
Definition at line 2664 of file interface_layout.c.
References uiBlock::curlayout.
Referenced by ui_item_array(), ui_item_disabled(), ui_item_enum_expand(), ui_item_menu(), ui_item_with_label(), ui_layout_box(), ui_node_menu_column(), ui_template_node_link_menu(), uiItemFullO_ptr(), uiItemFullR(), uiItemL_(), uiItemS(), uiItemV(), uiLayoutAbsolute(), uiLayoutColumn(), uiLayoutColumnFlow(), uiLayoutOverlap(), uiLayoutRow(), uiLayoutSplit(), uiTemplateNodeLink(), uiTemplateOperatorSearch(), and uiTemplateRunningJobs().
void uiBlockSetDirection (uiBlock * block, int direction)
Definition at line 3270 of file interface.c.
References uiBlock::direction.
Referenced by actuator_menu(), controller_menu(), controller_state_mask_menu(), curvemap_brush_tools_func(), curvemap_clipping_func(), curvemap_tools_func(), draw_group_socket(), id_search_menu(), menu_add_shortcut(), menu_change_shortcut(), object_state_mask_menu(), operator_search_menu(), sensor_menu(), tool_search_menu(), and ui_block_func_POPUP().
void uiBlockSetDrawExtraFunc (uiBlock * block, void(*)(const struct bContext *C, void *, void *, void *, struct rcti *rect) func, void * arg1, void * arg2)
Referenced by uiTemplatePreview().
void uiBlockSetEmboss (uiBlock * block, char dt)
Definition at line 2138 of file interface.c.
References uiBlock::dt.
Referenced by ANIM_channel_draw_widgets(), ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), buttons_header_buttons(), curvemap_buttons_layout(), draw_actuatorbuttons(), draw_constraint(), draw_group_socket(), draw_modifier(), ED_area_header_standardbuttons(), file_panel_category(), gp_drawui_layer(), graph_panel_drivers(), list_item_row(), node_draw_basis(), node_draw_hidden(), node_socket_button_output_file(), outliner_draw_keymapbuts(), outliner_draw_restrictbuts(), outliner_draw_rnabuts(), ui_item_menu(), ui_node_draw_input(), uiItemFullO_ptr(), uiItemFullR(), uiTemplateHeader3D(), uiTemplateReportsBanner(), and wm_block_create_splash().
void uiBlockSetFlag (uiBlock * block, int flag)
Definition at line 3313 of file interface.c.
References uiBlock::flag.
Referenced by id_search_menu(), menu_add_shortcut(), menu_change_shortcut(), node_uiblocks_init(), operator_search_menu(), socket_component_menu(), tool_search_menu(), ui_block_func_COL(), ui_block_func_ICONROW(), ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), ui_block_func_POPUP(), wm_block_create_redo(), wm_block_create_splash(), wm_block_dialog_create(), wm_block_search_menu(), wm_enum_search_menu(), and wm_operator_ui_create().
void uiBlockSetFunc (uiBlock * block, uiButHandleFunc func, void * arg1, void * arg2)
Definition at line 3425 of file interface.c.
References uiBlock::func, uiBlock::func_arg1, and uiBlock::func_arg2.
Referenced by draw_constraint(), file_draw_buttons(), file_panel_operator(), gp_drawui_layer(), wm_block_create_splash(), and wm_block_dialog_create().
void uiBlockSetHandleFunc (uiBlock * block, uiBlockHandleFunc func, void * arg)
Definition at line 3413 of file interface.c.
References uiBlock::handle_func, and uiBlock::handle_func_arg.
Referenced by buttons_header_buttons(), clip_panel_operator_redo(), draw_constraint(), file_draw_buttons(), graph_panel_drivers(), graph_panel_key_properties(), graph_panel_modifiers(), graph_panel_properties(), image_panel_uv(), logic_buttons(), logic_buttons_new(), menu_add_shortcut(), menu_change_shortcut(), nla_panel_actclip(), nla_panel_animdata(), nla_panel_evaluation(), nla_panel_modifiers(), nla_panel_properties(), nla_panel_track(), node_uiblocks_init(), ui_layout_end(), uiTemplateEditModeSelection(), uiTemplateHeader3D(), uiTemplateMarker(), uiTemplatePreview(), uiTemplateRunningJobs(), view3d_panel_object(), view3d_panel_operator_redo(), view3d_panel_vgroup(), and wm_block_create_redo().
void uiBlockSetNFunc (uiBlock * block, uiButHandleFunc func, void * argN, void * arg2)
Definition at line 3432 of file interface.c.
References uiBlock::func_arg2, uiBlock::func_argN, uiBlock::funcN, and MEM_freeN().
Referenced by curvemap_buttons_layout(), uiTemplateImage(), and uiTemplateMarker().
void uiBlockSetRegion (uiBlock * block, struct ARegion * region)
Definition at line 2059 of file interface.c.
References uiBlock::active, BLI_addhead(), BLI_findstring(), uiBlock::name, NULL, uiBlock::oldblock, uiBlock::panel, and ARegion::uiblocks.
Referenced by ui_block_func_POPUP(), and uiBeginBlock().
void uiBlockSetXOfs (uiBlock * block, int xofs)
Definition at line 3323 of file interface.c.
References uiBlock::xofs.
int uiBlocksGetYMin (struct ListBase * lb)
Definition at line 3258 of file interface.c.
References ListBase::first, min, uiBlock::miny, and uiBlock::next.
void uiBoundsBlock (struct uiBlock * block, int addval)
Definition at line 396 of file interface.c.
References uiBlock::bounds, uiBlock::dobounds, NULL, and UI_BLOCK_BOUNDS.
Referenced by id_search_menu(), operator_search_menu(), tool_search_menu(), ui_block_func_COL(), and uiEndBlock().
int uiButActiveOnly (const struct bContext * C, uiBlock * block, uiBut * but)
Referenced by ANIM_channel_draw_widgets(), file_draw_list(), and outliner_buttons().
void uiButClearFlag (uiBut * but, int flag)
Definition at line 3333 of file interface.c.
References uiBut::flag.
Referenced by buttons_context_draw(), ED_area_header_standardbuttons(), ED_area_header_switchbutton(), file_draw_buttons(), file_draw_list(), uiLayoutOperatorButs(), and uiTemplateHeader3D().
struct MenuType* uiButGetMenuType (uiBut * but) [read]
Definition at line 2920 of file interface_layout.c.
References uiBut::menu_create_func, NULL, uiBut::poin, and ui_item_menutype_func().
Referenced by ui_menu_block_set_keymaps(), and ui_tooltip_create().
struct PointerRNA* uiButGetOperatorPtrRNA (uiBut * but) [read]
Definition at line 3382 of file interface.c.
References MEM_callocN(), uiBut::opptr, uiBut::optype, and WM_operator_properties_create_ptr().
Referenced by draw_group_socket(), file_draw_buttons(), ui_but_copy_paste(), ui_tooltip_create(), and uiItemFullO_ptr().
int uiButGetRetVal (uiBut * but)
Definition at line 3338 of file interface.c.
References uiBut::retval.
int uiButGetUnitType (uiBut * but)
Definition at line 3397 of file interface.c.
References if(), NULL, RNA_property_subtype(), RNA_SUBTYPE_UNIT, uiBut::rnaprop, and uiBut::unit_type.
Referenced by ui_convert_to_unit_alt_name(), ui_get_but_scale_unit(), ui_get_but_step_unit(), ui_get_but_string_unit(), ui_is_but_unit(), ui_numedit_apply_snapf(), and ui_tooltip_create().
void uiButSetCompleteFunc (uiBut * but, uiButCompleteFunc func, void * arg)
Definition at line 3474 of file interface.c.
References uiBut::autocomplete_func, and uiBut::autofunc_arg.
Referenced by file_draw_buttons(), and uiDefIDPoinBut().
void uiButSetDragID (uiBut * but, struct ID * id)
Definition at line 3343 of file interface.c.
References uiBut::dragpoin, uiBut::dragtype, and WM_DRAG_ID.
Referenced by template_ID(), tselem_draw_icon_uibut(), and uiItemLDrag().
void uiButSetDragImage (uiBut * but, const char * path, int icon, struct ImBuf * ima, float scale)
Definition at line 3373 of file interface.c.
References uiBut::dragpoin, uiBut::dragtype, uiBut::icon, uiBut::imb, uiBut::imb_scale, and WM_DRAG_PATH.
Referenced by file_draw_preview().
void uiButSetDragName (uiBut * but, const char * name)
Definition at line 3361 of file interface.c.
References uiBut::dragpoin, uiBut::dragtype, and WM_DRAG_NAME.
void uiButSetDragPath (uiBut * but, const char * path)
Definition at line 3355 of file interface.c.
References uiBut::dragpoin, uiBut::dragtype, and WM_DRAG_PATH.
Referenced by file_draw_icon().
void uiButSetDragRNA (uiBut * but, struct PointerRNA * ptr)
Definition at line 3349 of file interface.c.
References uiBut::dragpoin, uiBut::dragtype, and WM_DRAG_RNA.
void uiButSetDragValue (uiBut * but)
Definition at line 3368 of file interface.c.
References uiBut::dragtype, and WM_DRAG_VALUE.
void uiButSetFlag (uiBut * but, int flag)
Definition at line 3328 of file interface.c.
References uiBut::flag.
Referenced by draw_group_socket(), draw_modifier(), file_draw_buttons(), file_draw_list(), file_panel_category(), list_item_row(), template_ID(), ui_but_search_test(), ui_item_with_label(), uiDefAutoButR(), uiItemFullO_ptr(), uiItemFullR(), and uiTemplateList().
void uiButSetFocusOnEnter (struct wmWindow * win, uiBut * but)
Definition at line 3650 of file interface.c.
References wmWindow::eventstate, EVT_BUT_OPEN, FALSE, KM_PRESS, wmEvent::type, and wm_event_add().
Referenced by id_search_menu(), and uiLayoutOperatorButs().
void uiButSetFunc (uiBut * but, uiButHandleFunc func, void * arg1, void * arg2)
Definition at line 3456 of file interface.c.
References uiBut::func, uiBut::func_arg1, and uiBut::func_arg2.
Referenced by ANIM_channel_draw_widgets(), ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), circle_picker(), colorband_buttons_large(), controller_state_mask_menu(), curvemap_buttons_layout(), curvemap_clipping_func(), draw_actuatorbuttons(), draw_default_sensor_header(), draw_group_socket_name(), draw_modifier(), draw_modifier__envelope(), draw_modifier__generator(), draw_sensorbuttons(), draw_setting_widget(), ED_area_header_switchbutton(), file_panel_category(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_key_properties(), logic_buttons(), node_buts_normal(), node_draw_basis(), node_draw_hidden(), node_shader_buts_dynamic(), node_socket_button_color(), node_socket_button_default(), outliner_draw_keymapbuts(), outliner_draw_restrictbuts(), square_picker(), ui_but_menu(), ui_item_array(), ui_item_with_label(), uiblock_layer_pass_arrow_buttons(), uiblock_layer_pass_buttons(), uiBlockPicker(), uiButSetSearchFunc(), uiLayoutOperatorButs(), uiTemplateImage(), uiTemplateKeymapItemProperties(), uiTemplateLayers(), uiTemplateTextureShow(), wm_block_create_splash(), and wm_block_dialog_create().
void uiButSetNFunc (uiBut * but, uiButHandleNFunc func, void * argN, void * arg2)
Definition at line 3463 of file interface.c.
References uiBut::func_arg2, uiBut::func_argN, uiBut::funcN, and MEM_freeN().
Referenced by colorband_buttons_large(), colorband_buttons_small(), curvemap_buttons_layout(), draw_setting_widget(), graph_panel_drivers(), template_ID(), template_texture_user_menu(), ui_node_menu_column(), ui_template_node_link_menu(), uiTemplateHistogram(), uiTemplateMarker(), and uiTemplateVectorscope().
void uiButSetRenameFunc (uiBut * but, uiButHandleRenameFunc func, void * arg1)
Definition at line 3443 of file interface.c.
References uiBut::rename_arg1, and uiBut::rename_func.
Referenced by file_draw_list(), and outliner_buttons().
void uiButSetSearchFunc (uiBut * but, uiButSearchFunc sfunc, void * arg1, uiButHandleFunc bfunc, void * active)
Definition at line 3632 of file interface.c.
References uiBut::block, uiBut::drawstr, uiBlock::flag, uiBut::search_arg, uiBut::search_func, UI_BLOCK_LOOP, ui_but_search_test(), and uiButSetFunc().
Referenced by id_search_menu(), operator_search_menu(), tool_search_menu(), ui_but_add_search(), uiTemplateOperatorSearch(), wm_block_search_menu(), and wm_enum_search_menu().
void uiButSetUnitType (uiBut * but, const int unit_type)
Definition at line 3392 of file interface.c.
References RNA_SUBTYPE_UNIT_VALUE, and uiBut::unit_type.
Referenced by graph_panel_key_properties(), and v3d_editvertex_buts().
void uiCenteredBoundsBlock (uiBlock * block, int addval)
Definition at line 431 of file interface.c.
References uiBlock::bounds, uiBlock::dobounds, and UI_BLOCK_BOUNDS_POPUP_CENTER.
Referenced by wm_block_create_splash().
void uiComposeLinks (uiBlock * block)
Definition at line 1156 of file interface.c.
References uiBlock::buttons, ListBase::first, uiLink::lines, link(), LINK, uiBut::link, uiBut::next, uiLink::poin, uiLink::ppoin, uiLink::totlink, uiBut::type, ui_add_link_line(), and ui_find_inlink().
Referenced by logic_buttons(), and logic_buttons_new().
uiBut* uiContextActiveButton (const struct bContext * C)
Definition at line 5353 of file interface_handlers.c.
References NULL, and ui_context_button_active().
struct wmOperator* uiContextActiveOperator (const struct bContext * C) [read]
Definition at line 5390 of file interface_handlers.c.
References CTX_wm_region(), CTX_wm_screen(), ListBase::first, ARegion::next, uiBlock::next, NULL, bScreen::regionbase, uiBlock::ui_operator, and ARegion::uiblocks.
Referenced by ed_screen_context().
void uiContextActiveProperty (const struct bContext * C, struct PointerRNA * ptr, struct PropertyRNA ** prop, int * index)
Referenced by add_driver_button_exec(), add_keyingset_button_exec(), copy_data_path_button_exec(), copy_driver_button_exec(), copy_to_selected_button_exec(), copy_to_selected_button_poll(), delete_key_button_exec(), eyedropper_init(), insert_key_button_exec(), paste_driver_button_exec(), remove_driver_button_exec(), remove_keyingset_button_exec(), reset_default_button_exec(), and reset_default_button_poll().
void uiContextActivePropertyHandle (struct bContext * C)
Definition at line 5376 of file interface_handlers.c.
References uiBut::block, uiBlock::handle_func, uiBlock::handle_func_arg, and ui_context_rna_button_active().
Referenced by reset_default_button_exec().
void uiContextAnimUpdate (const struct bContext * C)
Referenced by add_driver_button_exec(), copy_driver_button_exec(), delete_key_button_exec(), insert_key_button_exec(), paste_driver_button_exec(), and remove_driver_button_exec().
uiBut* uiDefAutoButR (uiBlock * block, struct PointerRNA * ptr, struct PropertyRNA * prop, int index, const char * name, int icon, int x1, int y1, int x2, int y2)
Definition at line 54 of file interface_utils.c.
References BLI_snprintf(), COL, ELEM, ICONTOG, IDPOIN, IFACE_, LABEL, MENU, NULL, NUM, NUMSLI, OPTION, PROP_BOOLEAN, PROP_COLLECTION, PROP_COLOR, PROP_COLOR_GAMMA, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_PERCENTAGE, PROP_POINTER, PROP_STRING, RNA_property_array_length(), RNA_property_collection_length(), RNA_property_pointer_get(), RNA_property_pointer_type(), RNA_property_subtype(), RNA_property_type(), RNA_struct_ui_icon(), TEX, PointerRNA::type, UI_BUT_DISABLED, uiButSetFlag(), uiDefBut(), uiDefButR_prop(), uiDefIconButR_prop(), and uiDefIconTextButR_prop().
Referenced by ANIM_channel_draw_widgets(), outliner_draw_rnabuts(), ui_item_array(), ui_item_with_label(), uiItemFullR(), and uiTemplateLayers().
int uiDefAutoButsRNA (uiLayout * layout, struct PointerRNA * ptr, int(*)(struct PointerRNA *, struct PropertyRNA *) check_prop, const char label_align)
Referenced by image_save_as_draw(), screenshot_draw(), and uiLayoutOperatorButs().
uiBut* uiDefBlockBut (uiBlock * block, uiBlockCreateFunc func, void * func_arg1, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3493 of file interface.c.
References BLOCK, uiBut::block_create_func, ui_check_but(), and ui_def_but().
Referenced by draw_controller_header(), logic_buttons(), logic_buttons_new(), outliner_draw_keymapbuts(), and view3d_panel_tool_shelf().
uiBut* uiDefBlockButN (uiBlock * block, uiBlockCreateFunc func, void * argN, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3501 of file interface.c.
References BLOCK, uiBut::block_create_func, uiBut::func_argN, MEM_freeN(), NULL, ui_check_but(), and ui_def_but().
Referenced by node_socket_button_components(), and template_ID().
uiBut* uiDefBut (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, void * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 2883 of file interface.c.
References ui_check_but(), and ui_def_but().
Referenced by actuator_menu(), colorband_buttons_large(), colorband_buttons_small(), controller_menu(), controller_state_mask_menu(), curvemap_buttons_layout(), curvemap_clipping_func(), draw_actuatorbuttons(), draw_constraint(), draw_controllerbuttons(), draw_group_socket_name(), draw_modifier(), draw_modifier__envelope(), draw_modifier__generator(), draw_sensorbuttons(), file_draw_buttons(), file_draw_list(), file_draw_preview(), graph_panel_drivers(), id_search_menu(), logic_buttons(), node_draw_basis(), node_draw_hidden(), node_shader_buts_dynamic(), node_socket_button_color(), node_socket_button_label(), object_state_mask_menu(), operator_search_menu(), outliner_buttons(), outliner_draw_keymapbuts(), sensor_menu(), template_ID(), tool_search_menu(), ui_block_func_ICONTEXTROW(), ui_item_array(), ui_item_disabled(), ui_item_with_label(), ui_layout_box(), ui_node_menu_column(), ui_template_node_link_menu(), uiBlockPicker(), uiDefAutoButR(), uiDefButBit(), uiDefButC(), uiDefButF(), uiDefButI(), uiDefButS(), uiItemL_(), uiItemS(), uiPupMenuBegin(), uiTemplateHistogram(), uiTemplateImage(), uiTemplateMarker(), uiTemplateMovieClip(), uiTemplatePreview(), uiTemplateReportsBanner(), uiTemplateRunningJobs(), uiTemplateTrack(), uiTemplateVectorscope(), uiTemplateWaveform(), v3d_editvertex_buts(), view3d_panel_vgroup(), wm_block_create_splash(), wm_block_dialog_create(), wm_block_search_menu(), and wm_enum_search_menu().
uiBut* uiDefButBitC (uiBlock * block, int type, int bit, int retval, const char * str, int x1, int y1, short x2, short y2, char * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3042 of file interface.c.
References CHA, and uiDefButBit().
uiBut* uiDefButBitF (uiBlock * block, int type, int bit, int retval, const char * str, int x1, int y1, short x2, short y2, float * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3018 of file interface.c.
References FLO, and uiDefButBit().
uiBut* uiDefButBitI (uiBlock * block, int type, int bit, int retval, const char * str, int x1, int y1, short x2, short y2, int * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3026 of file interface.c.
References INT, and uiDefButBit().
Referenced by controller_state_mask_menu(), curvemap_clipping_func(), draw_actuatorbuttons(), draw_controllerbuttons(), logic_buttons(), and uiTemplateMarker().
uiBut* uiDefButBitS (uiBlock * block, int type, int bit, int retval, const char * str, int x1, int y1, short x2, short y2, short * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3034 of file interface.c.
References SHO, and uiDefButBit().
Referenced by draw_actuatorbuttons(), draw_sensorbuttons(), logic_buttons(), logic_buttons_new(), and v3d_editvertex_buts().
uiBut* uiDefButC (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, char * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3038 of file interface.c.
References CHA, and uiDefBut().
Referenced by draw_sensorbuttons(), and uiTemplateHeader3D().
uiBut* uiDefButF (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, float * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3014 of file interface.c.
References FLO, and uiDefBut().
Referenced by curvemap_clipping_func(), draw_actuatorbuttons(), draw_modifier__envelope(), draw_modifier__generator(), draw_sensorbuttons(), node_buts_normal(), ui_block_func_MENUSTR(), uiBlockPicker(), uiItemV(), uiTemplateMarker(), uvedit_vertex_buttons(), v3d_editvertex_buts(), and view3d_panel_vgroup().
uiBut* uiDefButI (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, int * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3022 of file interface.c.
References INT, and uiDefBut().
Referenced by curvemap_buttons_layout(), draw_actuatorbuttons(), draw_controllerbuttons(), draw_modifier__generator(), draw_sensorbuttons(), uiTemplateImage(), and uiTemplateList().
uiBut* uiDefButO (uiBlock * block, int type, const char * opname, int opcontext, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3068 of file interface.c.
References NULL, uiDefButO_ptr(), and WM_operatortype_find().
Referenced by draw_actuatorbuttons(), file_draw_buttons(), graph_panel_modifiers(), and nla_panel_modifiers().
uiBut* uiDefButO_ptr (uiBlock * block, int type, struct wmOperatorType * ot, int opcontext, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3061 of file interface.c.
References ui_check_but(), and ui_def_but_operator_ptr().
Referenced by uiDefButO(), and uiItemFullO_ptr().
uiBut* uiDefButR (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, struct PointerRNA * ptr, const char * propname, int index, float min, float max, float a1, float a2, const char * tip)
Definition at line 3046 of file interface.c.
References ui_check_but(), and ui_def_but_rna_propname().
Referenced by ANIM_channel_draw_widgets(), draw_modifier__generator(), graph_panel_key_properties(), list_item_row(), node_socket_button_color(), node_socket_button_default(), and template_ID().
uiBut* uiDefButR_prop (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, struct PointerRNA * ptr, struct PropertyRNA * prop, int index, float min, float max, float a1, float a2, const char * tip)
Definition at line 3053 of file interface.c.
References ui_check_but(), and ui_def_but_rna().
Referenced by circle_picker(), list_item_row(), square_picker(), ui_item_array(), ui_item_enum_expand(), ui_item_with_label(), uiBlockPicker(), uiDefAutoButR(), uiItemFullR(), and uiTemplateColorWheel().
uiBut* uiDefButS (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, short * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3030 of file interface.c.
References SHO, and uiDefBut().
Referenced by colorband_buttons_large(), colorband_buttons_small(), draw_actuatorbuttons(), draw_default_sensor_header(), draw_sensorbuttons(), logic_buttons(), node_shader_buts_dynamic(), outliner_draw_keymapbuts(), uiblock_layer_pass_buttons(), uiBlockPicker(), and uiTemplatePreview().
uiBut* uiDefButTextO (uiBlock * block, int type, const char * opname, int opcontext, const char * str, int x1, int y1, short x2, short y2, void * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3075 of file interface.c.
References ui_check_but(), and ui_def_but_operator_text().
Referenced by file_draw_buttons().
uiBut* uiDefHotKeyevtButS (uiBlock * block, int retval, const char * str, int x1, int y1, short x2, short y2, short * keypoin, short * modkeypoin, const char * tip)
Definition at line 3604 of file interface.c.
References HOTKEYEVT, uiBut::modifier_key, SHO, ui_check_but(), and ui_def_but().
uiBut* uiDefIconBlockBut (uiBlock * block, uiBlockCreateFunc func, void * arg, int retval, int icon, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3580 of file interface.c.
References BLOCK, uiBut::block_create_func, uiBut::flag, uiBut::icon, ui_check_but(), ui_def_but(), UI_HAS_ICON, and UI_ICON_LEFT.
Referenced by curvemap_buttons_layout().
uiBut* uiDefIconBut (uiBlock * block, int type, int retval, int icon, int x1, int y1, short x2, short y2, void * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3083 of file interface.c.
References ui_check_but_and_iconize(), and ui_def_but().
Referenced by ANIM_uiTemplate_fmodifier_draw(), curvemap_buttons_layout(), draw_constraint(), draw_modifier(), draw_modifier__envelope(), file_draw_icon(), gp_drawui_layer(), graph_panel_drivers(), logic_buttons(), logic_buttons_new(), node_draw_basis(), outliner_draw_restrictbuts(), template_ID(), tselem_draw_icon_uibut(), uiblock_layer_pass_arrow_buttons(), uiDefIconButBit(), uiDefIconButC(), uiDefIconButF(), uiDefIconButI(), uiDefIconButS(), uiItemL_(), uiTemplateReportsBanner(), uiTemplateRunningJobs(), and uiTemplateTextureShow().
uiBut* uiDefIconButBitC (uiBlock * block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, char * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3128 of file interface.c.
References CHA, and uiDefIconButBit().
Referenced by buttons_context_draw(), draw_setting_widget(), list_item_row(), and uiTemplateHeader3D().
uiBut* uiDefIconButBitF (uiBlock * block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, float * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3104 of file interface.c.
References FLO, and uiDefIconButBit().
uiBut* uiDefIconButBitI (uiBlock * block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, int * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3112 of file interface.c.
References INT, and uiDefIconButBit().
Referenced by draw_modifier(), draw_setting_widget(), gp_drawui_layer(), outliner_draw_restrictbuts(), and uiTemplateMarker().
uiBut* uiDefIconButBitS (uiBlock * block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, short * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3120 of file interface.c.
References SHO, and uiDefIconButBit().
Referenced by draw_default_sensor_header(), draw_setting_widget(), ED_area_header_standardbuttons(), logic_buttons(), and uiTemplateEditModeSelection().
uiBut* uiDefIconButC (uiBlock * block, int type, int retval, int icon, int x1, int y1, short x2, short y2, char * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3124 of file interface.c.
References CHA, and uiDefIconBut().
uiBut* uiDefIconButF (uiBlock * block, int type, int retval, int icon, int x1, int y1, short x2, short y2, float * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3100 of file interface.c.
References FLO, and uiDefIconBut().
Referenced by ui_block_func_ICONROW(), and uiItemV().
uiBut* uiDefIconButI (uiBlock * block, int type, int retval, int icon, int x1, int y1, short x2, short y2, int * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3108 of file interface.c.
References INT, and uiDefIconBut().
uiBut* uiDefIconButO (uiBlock * block, int type, const char * opname, int opcontext, int icon, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3154 of file interface.c.
References uiDefIconButO_ptr(), and WM_operatortype_find().
Referenced by draw_group_socket(), file_draw_buttons(), template_ID(), ui_item_with_label(), uiBlockPicker(), and uiTemplateReportsBanner().
uiBut* uiDefIconButO_ptr (uiBlock * block, int type, struct wmOperatorType * ot, int opcontext, int icon, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3147 of file interface.c.
References ui_check_but_and_iconize(), and ui_def_but_operator_ptr().
Referenced by uiDefIconButO(), and uiItemFullO_ptr().
uiBut* uiDefIconButR (uiBlock * block, int type, int retval, int icon, int x1, int y1, short x2, short y2, struct PointerRNA * ptr, const char * propname, int index, float min, float max, float a1, float a2, const char * tip)
Definition at line 3132 of file interface.c.
References ui_check_but_and_iconize(), and ui_def_but_rna_propname().
Referenced by list_item_row(), and outliner_draw_restrictbuts().
uiBut* uiDefIconButR_prop (uiBlock * block, int type, int retval, int icon, int x1, int y1, short x2, short y2, struct PointerRNA * ptr, PropertyRNA * prop, int index, float min, float max, float a1, float a2, const char * tip)
Definition at line 3139 of file interface.c.
References ui_check_but_and_iconize(), and ui_def_but_rna().
Referenced by ui_item_enum_expand(), uiDefAutoButR(), uiItemFullR(), and uiTemplateList().
uiBut* uiDefIconButS (uiBlock * block, int type, int retval, int icon, int x1, int y1, short x2, short y2, short * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3116 of file interface.c.
References SHO, and uiDefIconBut().
uiBut* uiDefIconMenuBut (uiBlock * block, uiMenuCreateFunc func, void * arg, int icon, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3546 of file interface.c.
References uiBut::flag, uiBut::icon, uiBut::menu_create_func, PULLDOWN, ui_check_but(), ui_def_but(), UI_HAS_ICON, and UI_ICON_LEFT.
Referenced by ui_item_menu(), and uiTemplateNodeLink().
uiBut* uiDefIconTextBlockBut (uiBlock * block, uiBlockCreateFunc func, void * arg, int icon, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3561 of file interface.c.
References BLOCK, uiBut::block_create_func, uiBut::flag, uiBut::icon, ui_check_but(), ui_def_but(), UI_HAS_ICON, UI_ICON_LEFT, and UI_ICON_SUBMENU.
uiBut* uiDefIconTextBut (uiBlock * block, int type, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, void * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3161 of file interface.c.
References uiBut::flag, ui_check_but_and_iconize(), ui_def_but(), and UI_ICON_LEFT.
Referenced by curvemap_brush_tools_func(), curvemap_tools_func(), template_ID(), template_texture_user_menu(), ui_but_menu(), uiDefIconTextButBit(), uiDefIconTextButC(), uiDefIconTextButF(), uiDefIconTextButI(), uiDefIconTextButS(), uiItemL_(), uiLayoutOperatorButs(), uiPupMenuBegin(), uiTemplateImage(), and uiTemplateRunningJobs().
uiBut* uiDefIconTextButBitC (uiBlock * block, int type, int bit, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, char * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3207 of file interface.c.
References CHA, and uiDefIconTextButBit().
uiBut* uiDefIconTextButBitF (uiBlock * block, int type, int bit, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, float * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3183 of file interface.c.
References FLO, and uiDefIconTextButBit().
uiBut* uiDefIconTextButBitI (uiBlock * block, int type, int bit, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, int * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3191 of file interface.c.
References INT, and uiDefIconTextButBit().
uiBut* uiDefIconTextButBitS (uiBlock * block, int type, int bit, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, short * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3199 of file interface.c.
References SHO, and uiDefIconTextButBit().
uiBut* uiDefIconTextButC (uiBlock * block, int type, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, char * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3203 of file interface.c.
References CHA, and uiDefIconTextBut().
Referenced by ED_area_header_switchbutton().
uiBut* uiDefIconTextButF (uiBlock * block, int type, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, float * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3179 of file interface.c.
References FLO, and uiDefIconTextBut().
Referenced by ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), and uiItemV().
uiBut* uiDefIconTextButI (uiBlock * block, int type, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, int * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3187 of file interface.c.
References INT, and uiDefIconTextBut().
uiBut* uiDefIconTextButO (uiBlock * block, int type, const char * opname, int opcontext, int icon, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3235 of file interface.c.
References uiDefIconTextButO_ptr(), and WM_operatortype_find().
Referenced by template_ID().
uiBut* uiDefIconTextButO_ptr (uiBlock * block, int type, struct wmOperatorType * ot, int opcontext, int icon, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3227 of file interface.c.
References uiBut::flag, ui_check_but_and_iconize(), ui_def_but_operator_ptr(), and UI_ICON_LEFT.
Referenced by uiDefIconTextButO(), and uiItemFullO_ptr().
uiBut* uiDefIconTextButR (uiBlock * block, int type, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, struct PointerRNA * ptr, const char * propname, int index, float min, float max, float a1, float a2, const char * tip)
Definition at line 3211 of file interface.c.
References uiBut::flag, ui_check_but_and_iconize(), ui_def_but_rna_propname(), and UI_ICON_LEFT.
uiBut* uiDefIconTextButR_prop (uiBlock * block, int type, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, struct PointerRNA * ptr, struct PropertyRNA * prop, int index, float min, float max, float a1, float a2, const char * tip)
Definition at line 3219 of file interface.c.
References uiBut::flag, ui_check_but_and_iconize(), ui_def_but_rna(), and UI_ICON_LEFT.
Referenced by ui_item_enum_expand(), uiDefAutoButR(), uiItemFullR(), and uiTemplateList().
uiBut* uiDefIconTextButS (uiBlock * block, int type, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, short * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3195 of file interface.c.
References SHO, and uiDefIconTextBut().
Referenced by file_panel_category(), and uiTemplateHeader3D().
uiBut* uiDefIconTextMenuBut (uiBlock * block, uiMenuCreateFunc func, void * arg, int icon, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3530 of file interface.c.
References uiBut::flag, uiBut::icon, uiBut::menu_create_func, PULLDOWN, ui_check_but(), ui_def_but(), UI_HAS_ICON, UI_ICON_LEFT, and UI_ICON_SUBMENU.
Referenced by ui_item_menu(), and uiTemplateTextureUser().
uiBut* uiDefIDPoinBut (uiBlock * block, uiIDPoinFuncFP func, short blocktype, int retval, const char * str, int x1, int y1, short x2, short y2, void * idpp, const char * tip)
Definition at line 3480 of file interface.c.
References autocomplete_id(), IDPOIN, uiBut::idpoin_func, uiBut::idpoin_idpp, NULL, ui_check_but(), ui_def_but(), and uiButSetCompleteFunc().
Referenced by draw_actuatorbuttons(), draw_controllerbuttons(), and draw_sensorbuttons().
uiBut* uiDefKeyevtButS (uiBlock * block, int retval, const char * str, int x1, int y1, short x2, short y2, short * spoin, const char * tip)
Definition at line 3595 of file interface.c.
References KEYEVT, SHO, ui_check_but(), and ui_def_but().
Referenced by draw_sensorbuttons(), and outliner_draw_keymapbuts().
uiBut* uiDefMenuBut (uiBlock * block, uiMenuCreateFunc func, void * arg, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3522 of file interface.c.
References uiBut::menu_create_func, PULLDOWN, ui_check_but(), and ui_def_but().
Referenced by ui_item_menu(), uiTemplateNodeLink(), and uiTemplateTextureUser().
uiBut* uiDefPulldownBut (uiBlock * block, uiBlockCreateFunc func, void * arg, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3514 of file interface.c.
References uiBut::block_create_func, PULLDOWN, ui_check_but(), and ui_def_but().
uiBut* uiDefSearchBut (uiBlock * block, void * arg, int retval, int icon, int maxlen, int x1, int y1, short x2, short y2, float a1, float a2, const char * tip)
Definition at line 3615 of file interface.c.
References uiBut::flag, uiBut::icon, SEARCH_MENU, ui_check_but(), ui_def_but(), UI_HAS_ICON, UI_ICON_LEFT, and UI_TEXT_LEFT.
Referenced by id_search_menu(), operator_search_menu(), tool_search_menu(), uiTemplateOperatorSearch(), wm_block_search_menu(), and wm_enum_search_menu().
void uiDrawBlock (const struct bContext * C, struct uiBlock * block)
Referenced by buttons_header_buttons(), draw_channel_names(), draw_nla_channel_list(), draw_outliner(), ED_region_header(), file_draw_buttons(), file_draw_list(), graph_draw_channel_names(), logic_buttons(), logic_buttons_new(), node_draw_basis(), node_draw_group(), node_draw_hidden(), ui_block_region_draw(), and uiDrawPanels().
void uiDrawBox (int mode, float minx, float miny, float maxx, float maxy, float rad)
Definition at line 79 of file interface_draw.c.
References roundboxtype, UI_CNR_BOTTOM_LEFT, UI_CNR_BOTTOM_RIGHT, UI_CNR_TOP_LEFT, and UI_CNR_TOP_RIGHT.
Referenced by acf_generic_root_backdrop(), acf_group_backdrop(), acf_summary_backdrop(), draw_image_seq(), draw_nla_channel_list_gl(), draw_scope_end(), drawviewborder(), node_draw_basis(), node_draw_group(), node_draw_hidden(), ui_draw_anti_roundbox(), ui_draw_but_HISTOGRAM(), ui_draw_but_NORMAL(), ui_draw_but_TRACKPREVIEW(), ui_dropshadow(), and uiRoundRect().
void uiDrawBoxShade (int mode, float minx, float miny, float maxx, float maxy, float rad, float shadetop, float shadedown)
Definition at line 147 of file interface_draw.c.
References div, round_box_shade_col(), roundboxtype, UI_CNR_BOTTOM_LEFT, UI_CNR_BOTTOM_RIGHT, UI_CNR_TOP_LEFT, and UI_CNR_TOP_RIGHT.
Referenced by draw_seq_strip(), nla_draw_strip(), and region_draw_azone_tab().
void uiDrawBoxShadow (unsigned char alpha, float minx, float miny, float maxx, float maxy)
Definition at line 1631 of file interface_draw.c.
References ui_shadowbox().
Referenced by file_draw_preview().
void uiDrawBoxVerticalShade (int mode, float minx, float miny, float maxx, float maxy, float rad, float shadeLeft, float shadeRight)
Definition at line 255 of file interface_draw.c.
References div, round_box_shade_col(), roundboxtype, UI_CNR_BOTTOM_LEFT, UI_CNR_BOTTOM_RIGHT, UI_CNR_TOP_LEFT, and UI_CNR_TOP_RIGHT.
void uiDrawPanels (const struct bContext * C, struct ARegion * ar)
Referenced by ED_region_panels().
void uiEmboss (float x1, float y1, float x2, float y2, int sel)
Definition at line 400 of file interface_draw.c.
References fdrawline().
Referenced by draw_actuatorbuttons(), draw_controllerbuttons(), and draw_sensorbuttons().
void uiEndBlock (const struct bContext * C, uiBlock * block)
Referenced by actuator_menu(), buttons_header_buttons(), controller_menu(), controller_state_mask_menu(), curvemap_brush_tools_func(), curvemap_clipping_func(), curvemap_tools_func(), draw_channel_names(), draw_nla_channel_list(), draw_outliner(), ED_region_header(), ED_region_panels(), file_draw_buttons(), file_draw_list(), graph_draw_channel_names(), id_search_menu(), logic_buttons(), logic_buttons_new(), menu_add_shortcut(), menu_change_shortcut(), node_draw_basis(), node_draw_group(), node_draw_hidden(), object_state_mask_menu(), operator_search_menu(), sensor_menu(), tool_search_menu(), ui_block_func_POPUP(), ui_popup_block_create(), uiDrawBlock(), wm_block_create_redo(), wm_block_create_splash(), wm_block_dialog_create(), wm_block_search_menu(), wm_enum_search_menu(), and wm_operator_ui_create().
void uiEndPanel (uiBlock * block, int width, int height)
Definition at line 268 of file interface_panel.c.
References ELEM, Panel::ofsy, uiBlock::panel, PNL_ANIM_ALIGN, PNL_NEW_ADDED, Panel::runtime_flag, Panel::sizex, and Panel::sizey.
Referenced by ED_region_panels().
void uiEndPanels (const struct bContext * C, struct ARegion * ar, int * x, int * y)
Referenced by ED_region_panels().
void uiExplicitBoundsBlock (uiBlock * block, int minx, int miny, int maxx, int maxy)
Definition at line 437 of file interface.c.
References uiBlock::dobounds, uiBlock::maxx, uiBlock::maxy, uiBlock::minx, and uiBlock::miny.
Referenced by node_update_basis(), node_update_group(), and node_update_hidden().
void uiFileBrowseContextProperty (const struct bContext * C, struct PointerRNA * ptr, struct PropertyRNA ** prop)
Referenced by file_browse_invoke().
uiBut* uiFindInlink (uiBlock * block, void * poin)
Definition at line 1151 of file interface.c.
References ui_find_inlink().
Referenced by is_sensor_linked().
void uiFreeActiveButtons (const struct bContext * C, struct bScreen * screen)
Referenced by ED_screen_do_listen().
void uiFreeBlock (const struct bContext * C, uiBlock * block)
Referenced by uiFreeBlocks(), and uiFreeInactiveBlocks().
void uiFreeBlocks (const struct bContext * C, struct ListBase * lb)
Referenced by ED_area_initialize(), ED_screen_full_toggle(), and ui_handler_remove_region().
void uiFreeInactiveBlocks (const struct bContext * C, struct ListBase * lb)
Referenced by ED_region_do_draw().
uiBlock* uiGetBlock (const char * name, struct ARegion * ar)
Definition at line 2133 of file interface.c.
References BLI_findstring(), and ARegion::uiblocks.
int uiGetRoundBox (void)
Definition at line 74 of file interface_draw.c.
References roundboxtype.
int uiIconFromID (struct ID * id)
Definition at line 191 of file interface_utils.c.
References Object::data, GS, ID_OB, ID::name, NULL, OB_EMPTY, RNA_id_pointer_create(), RNA_struct_ui_icon(), PointerRNA::type, Object::type, and uiIconFromID().
Referenced by object_mouse_select_menu(), and uiIconFromID().
void uiIDContextProperty (struct bContext * C, struct PointerRNA * ptr, struct PropertyRNA ** prop)
Definition at line 214 of file interface_templates.c.
References uiBlock::buttons, CTX_wm_region(), ListBase::first, uiBut::flag, uiBut::func_argN, uiBut::next, uiBlock::next, NULL, UI_ACTIVE, UI_BUT_LAST_ACTIVE, and ARegion::uiblocks.
Referenced by act_new_exec(), font_ui_template_init(), font_unlink_exec(), image_new_exec(), image_open_init(), new_material_exec(), new_node_tree_exec(), new_texture_exec(), new_world_exec(), open_init(), sound_open_init(), text_new_exec(), and text_open_init().
void uiItemBooleanO (uiLayout * layout, const char * name, int icon, const char * opname, const char * propname, int value)
Definition at line 924 of file interface_layout.c.
References PointerRNA::data, uiLayoutRoot::opcontext, RNA_boolean_set(), uiLayout::root, UI_OPERATOR_ERROR_RET, uiItemFullO_ptr(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
Referenced by image_pack_invoke(), pose_ik_add_invoke(), and ui_but_menu().
void uiItemEnumO (uiLayout * layout, const char * opname, const char * name, int icon, const char * propname, int value)
Definition at line 763 of file interface_layout.c.
References RNA_warning, ui_item_disabled(), uiItemEnumO_ptr(), and WM_operatortype_find().
Referenced by armature_parent_set_invoke(), draw_actuator_header(), draw_controller_header(), draw_modifier(), draw_sensor_header(), graph_panel_view(), nla_fmodifier_add_invoke(), and parent_set_invoke().
void uiItemEnumO_ptr (uiLayout * layout, struct wmOperatorType * ot, const char * name, int icon, const char * propname, int value)
Definition at line 741 of file interface_layout.c.
References PointerRNA::data, uiLayoutRoot::opcontext, RNA_property_enum_set(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, uiLayout::root, PointerRNA::type, ui_menu_enumpropname(), uiItemFullO_ptr(), and WM_operator_properties_create_ptr().
Referenced by delete_invoke(), text_resolve_conflict_invoke(), and uiItemEnumO().
void uiItemEnumO_string (uiLayout * layout, const char * name, int icon, const char * opname, const char * propname, const char * value)
Definition at line 882 of file interface_layout.c.
References uiLayoutRoot::block, PointerRNA::data, uiBlock::evil_C, MEM_freeN(), NULL, uiLayoutRoot::opcontext, RNA_enum_value_from_id(), RNA_property_enum_items_gettexted(), RNA_property_enum_set(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, uiLayout::root, PointerRNA::type, ui_menu_enumpropname(), UI_OPERATOR_ERROR_RET, uiItemFullO_ptr(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
void uiItemEnumO_value (uiLayout * layout, const char * name, int icon, const char * opname, const char * propname, int value)
Definition at line 854 of file interface_layout.c.
References PointerRNA::data, uiLayoutRoot::opcontext, RNA_property_enum_set(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, uiLayout::root, PointerRNA::type, ui_menu_enumpropname(), UI_OPERATOR_ERROR_RET, uiItemFullO_ptr(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
void uiItemEnumR (uiLayout * layout, const char * name, int icon, struct PointerRNA * ptr, const char * propname, int value)
Definition at line 1137 of file interface_layout.c.
References PROP_ENUM, RNA_ENUM_VALUE, RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, PointerRNA::type, ui_item_disabled(), and uiItemFullR().
Referenced by uiItemsEnumR().
void uiItemEnumR_string (uiLayout * layout, struct PointerRNA * ptr, const char * propname, const char * value, const char * name, int icon)
Definition at line 1150 of file interface_layout.c.
References uiLayoutRoot::block, uiBlock::evil_C, EnumPropertyItem::identifier, MEM_freeN(), NULL, PROP_ENUM, RNA_ENUM_VALUE, RNA_enum_value_from_id(), RNA_property_enum_items_gettexted(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, uiLayout::root, PointerRNA::type, ui_item_disabled(), and uiItemFullR().
Referenced by draw_gpencil_panel().
void uiItemFloatO (uiLayout * layout, const char * name, int icon, const char * opname, const char * propname, float value)
Definition at line 950 of file interface_layout.c.
References PointerRNA::data, uiLayoutRoot::opcontext, RNA_float_set(), uiLayout::root, UI_OPERATOR_ERROR_RET, uiItemFullO_ptr(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
PointerRNA uiItemFullO (uiLayout * layout, const char * idname, const char * name, int icon, struct IDProperty * properties, int context, int flag)
Definition at line 702 of file interface_layout.c.
References PointerRNA_NULL, UI_OPERATOR_ERROR_RET, uiItemFullO_ptr(), and WM_operatortype_find().
Referenced by node_composit_buts_file_output_details(), parent_drop_invoke(), screen_area_options_invoke(), ui_but_menu(), uiItemO(), uiLayoutOperatorButs(), and view3d_panel_tool_shelf().
PointerRNA uiItemFullO_ptr (uiLayout * layout, struct wmOperatorType * ot, const char * name, int icon, IDProperty * properties, int context, int flag)
Definition at line 635 of file interface_layout.c.
References assert, uiLayoutRoot::block, BUT, PointerRNA::data, uiBut::flag, IDP_GROUP, IDP_New(), NULL, uiBut::optype, PointerRNA_NULL, uiLayout::redalert, RNA_struct_ui_name(), uiLayout::root, wmOperatorType::srna, uiLayoutRoot::type, UI_BUT_REDALERT, UI_EMBOSS, UI_EMBOSSN, UI_ITEM_O_RETURN_PROPS, UI_ITEM_R_NO_BG, UI_LAYOUT_MENU, UI_LAYOUT_TOOLBAR, ui_text_icon_width(), UI_TEXT_LEFT, UI_UNIT_Y, uiBlockSetCurLayout(), uiBlockSetEmboss(), uiButGetOperatorPtrRNA(), uiButSetFlag(), uiDefButO_ptr(), uiDefIconButO_ptr(), and uiDefIconTextButO_ptr().
Referenced by graph_fmodifier_add_invoke(), make_proxy_invoke(), node_composit_buts_renderlayers(), poselib_add_menu_invoke__replacemenu(), uiItemBooleanO(), uiItemEnumO_ptr(), uiItemEnumO_ptr__internal(), uiItemEnumO_string(), uiItemEnumO_value(), uiItemFloatO(), uiItemFullO(), uiItemIntO(), uiItemsFullEnumO(), uiItemStringO(), unpack_menu(), and WM_operator_confirm_message().
void uiItemFullR (uiLayout * layout, struct PointerRNA * ptr, struct PropertyRNA * prop, int index, int value, int flag, const char * name, int icon)
Definition at line 1027 of file interface_layout.c.
References uiLayoutRoot::block, ELEM4, FALSE, len(), NULL, NUM, NUMSLI, OPTION, PROP_BOOLEAN, PROP_ENUM, PROP_ENUM_FLAG, PROP_FLOAT, PROP_INT, PROP_POINTER, PROP_STRING, uiLayout::redalert, RNA_ENUM_VALUE, RNA_NO_INDEX, RNA_property_array_check(), RNA_property_array_length(), RNA_property_boolean_get(), RNA_property_boolean_get_index(), RNA_property_enum_get(), RNA_property_flag(), RNA_property_type(), RNA_property_ui_icon(), RNA_property_ui_name(), uiLayout::root, ROW, TOG, uiBut::type, uiLayoutRoot::type, ui_but_add_search(), UI_BUT_REDALERT, UI_EMBOSS, UI_EMBOSSN, ui_item_array(), ui_item_enum_expand(), ui_item_name_add_colon(), UI_ITEM_R_EXPAND, UI_ITEM_R_ICON_ONLY, UI_ITEM_R_NO_BG, UI_ITEM_R_SLIDER, UI_ITEM_R_TOGGLE, ui_item_rna_size(), ui_item_with_label(), UI_LAYOUT_MENU, UI_MAX_NAME_STR, uiBlockSetCurLayout(), uiBlockSetEmboss(), uiButSetFlag(), uiDefAutoButR(), uiDefButR_prop(), uiDefIconButR_prop(), and uiDefIconTextButR_prop().
Referenced by uiDefAutoButsRNA(), uiItemEnumR(), uiItemEnumR_string(), uiItemR(), and uiTemplateAnyID().
void uiItemIntO (uiLayout * layout, const char * name, int icon, const char * opname, const char * propname, int value)
Definition at line 937 of file interface_layout.c.
References PointerRNA::data, uiLayoutRoot::opcontext, RNA_int_set(), uiLayout::root, UI_OPERATOR_ERROR_RET, uiItemFullO_ptr(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
Referenced by file_panel_category(), pose_groups_menu_invoke(), poselib_add_menu_invoke(), repeat_history_invoke(), and undo_history_invoke().
void uiItemL (uiLayout * layout, const char * name, int icon)
Definition at line 1532 of file interface_layout.c.
References uiItemL_().
Referenced by ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), clip_panel_operator_redo_operator(), draw_actuator_armature(), draw_actuator_constraint(), draw_actuator_edit_object(), draw_actuator_header(), draw_actuator_motion(), draw_actuator_random(), draw_actuator_shape_action(), draw_actuator_sound(), draw_constraint(), draw_controller_header(), draw_gpencil_panel(), draw_modifier(), draw_modifier__cycles(), draw_modifier__envelope(), draw_sensor_armature(), draw_sensor_header(), draw_sensor_keyboard(), file_panel_bookmarks(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_key_properties(), graph_panel_properties(), list_item_row(), logic_buttons_new(), nla_panel_actclip(), nla_panel_properties(), node_composit_buts_blur(), node_composit_buts_channel_matte(), node_composit_buts_color_spill(), node_composit_buts_dblur(), node_composit_buts_defocus(), node_composit_buts_double_edge_mask(), node_composit_buts_file_output(), node_composit_buts_file_output_details(), node_composit_buts_image(), node_composit_buts_vecblur(), node_shader_buts_mapping(), node_socket_button_output_file(), node_sockets_panel(), recent_files_menu_draw(), template_keymap_item_properties(), template_texture_user_menu(), ui_block_func_MENUSTR(), ui_node_draw_input(), ui_node_menu_column(), ui_template_node_link_menu(), uiblock_layer_pass_arrow_buttons(), uiDefAutoButsRNA(), uiItemsEnumR(), uiItemsFullEnumO(), uiLayoutOperatorButs(), uiTemplateAnyID(), uiTemplateImage(), uiTemplateImageSettings(), uiTemplateList(), uiTemplateTextureUser(), v3d_editarmature_buts(), v3d_editmetaball_buts(), v3d_posearmature_buts(), v3d_transform_butsR(), view3d_panel_operator_redo_operator(), wm_block_create_redo(), and wm_block_create_splash().
void uiItemLDrag (uiLayout * layout, struct PointerRNA * ptr, const char * name, int icon)
Definition at line 1537 of file interface_layout.c.
References PointerRNA::data, PointerRNA::id, RNA_struct_is_ID(), PointerRNA::type, uiButSetDragID(), and uiItemL_().
Referenced by buttons_context_draw().
void uiItemM (uiLayout * layout, struct bContext * C, const char * menuname, const char * name, int icon)
Referenced by uiLayoutOperatorButs().
void uiItemMenuEnumO (uiLayout * layout, const char * opname, const char * propname, const char * name, int icon)
Definition at line 1607 of file interface_layout.c.
References BLI_strncpy(), MEM_callocN(), menu_item_enum_opname_menu(), NULL, uiLayoutRoot::opcontext, MenuItemLevel::opcontext, MenuItemLevel::opname, MenuItemLevel::propname, RNA_struct_ui_description(), RNA_struct_ui_name(), RNA_warning, uiLayout::root, wmOperatorType::srna, uiLayoutRoot::type, ui_item_disabled(), ui_item_menu(), UI_LAYOUT_MENU, UI_OPERATOR_ERROR_RET, and WM_operatortype_find().
Referenced by logic_buttons_new().
void uiItemMenuEnumR (uiLayout * layout, struct PointerRNA * ptr, const char * propname, const char * name, int icon)
Definition at line 1641 of file interface_layout.c.
References BLI_strncpy(), MEM_callocN(), menu_item_enum_rna_menu(), NULL, uiLayoutRoot::opcontext, MenuItemLevel::opcontext, MenuItemLevel::propname, RNA_property_description(), RNA_property_ui_name(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, MenuItemLevel::rnapoin, uiLayout::root, PointerRNA::type, uiLayoutRoot::type, ui_item_disabled(), ui_item_menu(), and UI_LAYOUT_MENU.
void uiItemMenuF (uiLayout * layout, const char * name, int icon, uiMenuCreateFunc func, void * arg)
Definition at line 1582 of file interface_layout.c.
References NULL, and ui_item_menu().
Referenced by node_menu_add_foreach_cb(), and poselib_add_menu_invoke().
void uiItemO (uiLayout * layout, const char * name, int icon, const char * opname)
Definition at line 976 of file interface_layout.c.
References NULL, uiLayoutRoot::opcontext, uiLayout::root, and uiItemFullO().
Referenced by active_node_panel(), draw_actuator_header(), draw_constraint(), draw_controller_header(), draw_gpencil_panel(), draw_modifier(), draw_sensor_header(), file_panel_bookmarks(), graph_panel_modifiers(), graph_panel_view(), header_toolbox_invoke(), nla_panel_actclip(), nla_panel_modifiers(), node_composit_buts_file_output_details(), ui_but_menu(), uiTemplateImage(), uiTemplateMovieClip(), and wm_block_create_splash().
void uiItemPointerR (uiLayout * layout, struct PointerRNA * ptr, const char * propname, struct PointerRNA * searchptr, const char * searchpropname, const char * name, int icon)
Definition at line 1376 of file interface_layout.c.
References ELEM, PROP_COLLECTION, PROP_POINTER, PROP_STRING, RNA_property_pointer_type(), RNA_property_type(), RNA_property_ui_name(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_struct_ui_icon(), RNA_warning, PointerRNA::type, ui_but_add_search(), ui_item_rna_size(), ui_item_with_label(), and uiLayoutGetBlock().
Referenced by draw_actuator_action(), draw_actuator_armature(), draw_actuator_constraint(), draw_actuator_message(), draw_actuator_property(), draw_actuator_random(), draw_actuator_shape_action(), draw_sensor_actuator(), draw_sensor_armature(), draw_sensor_collision(), draw_sensor_keyboard(), draw_sensor_property(), draw_sensor_ray(), graph_panel_driverVar__locDiff(), graph_panel_driverVar__rotDiff(), graph_panel_driverVar__transChan(), and node_shader_buts_geometry().
void uiItemR (uiLayout * layout, struct PointerRNA * ptr, const char * propname, int flag, const char * name, int icon)
Definition at line 1124 of file interface_layout.c.
References RNA_NO_INDEX, RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, PointerRNA::type, ui_item_disabled(), and uiItemFullR().
Referenced by active_node_panel(), ANIM_uiTemplate_fmodifier_draw(), colorband_buttons_large(), colorband_buttons_small(), curvemap_buttons_layout(), draw_actuator_action(), draw_actuator_armature(), draw_actuator_camera(), draw_actuator_constraint(), draw_actuator_edit_object(), draw_actuator_filter_2d(), draw_actuator_game(), draw_actuator_header(), draw_actuator_message(), draw_actuator_motion(), draw_actuator_parent(), draw_actuator_property(), draw_actuator_random(), draw_actuator_scene(), draw_actuator_shape_action(), draw_actuator_sound(), draw_actuator_state(), draw_actuator_steering(), draw_actuator_visibility(), draw_constraint(), draw_controller_expression(), draw_controller_header(), draw_controller_python(), draw_gpencil_panel(), draw_modifier(), draw_modifier__cycles(), draw_modifier__envelope(), draw_modifier__fn_generator(), draw_modifier__limits(), draw_modifier__noise(), draw_modifier__stepped(), draw_sensor_armature(), draw_sensor_collision(), draw_sensor_delay(), draw_sensor_header(), draw_sensor_internal_header(), draw_sensor_joystick(), draw_sensor_keyboard(), draw_sensor_message(), draw_sensor_mouse(), draw_sensor_near(), draw_sensor_property(), draw_sensor_radar(), draw_sensor_random(), draw_sensor_ray(), draw_sensor_touch(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_driverVar__locDiff(), graph_panel_driverVar__transChan(), graph_panel_key_properties(), graph_panel_properties(), graph_panel_view(), list_item_row(), logic_buttons_new(), menu_add_shortcut(), menu_change_shortcut(), nla_panel_actclip(), nla_panel_animdata(), nla_panel_evaluation(), nla_panel_properties(), nla_panel_track(), node_buts_math(), node_buts_mix_rgb(), node_buts_rgb(), node_buts_texture(), node_buts_time(), node_buts_value(), node_common_buts_whileloop(), node_composit_buts_alphaover(), node_composit_buts_bilateralblur(), node_composit_buts_blur(), node_composit_buts_channel_matte(), node_composit_buts_chroma_matte(), node_composit_buts_color_matte(), node_composit_buts_color_spill(), node_composit_buts_colorbalance(), node_composit_buts_colorbalance_but(), node_composit_buts_crop(), node_composit_buts_dblur(), node_composit_buts_defocus(), node_composit_buts_diff_matte(), node_composit_buts_dilateerode(), node_composit_buts_distance_matte(), node_composit_buts_double_edge_mask(), node_composit_buts_file_output(), node_composit_buts_file_output_details(), node_composit_buts_filter(), node_composit_buts_flip(), node_composit_buts_glare(), node_composit_buts_hue_sat(), node_composit_buts_id_mask(), node_composit_buts_image(), node_composit_buts_invert(), node_composit_buts_lensdist(), node_composit_buts_luma_matte(), node_composit_buts_map_uv(), node_composit_buts_map_value(), node_composit_buts_moviedistortion(), node_composit_buts_premulkey(), node_composit_buts_renderlayers(), node_composit_buts_rotate(), node_composit_buts_scale(), node_composit_buts_splitviewer(), node_composit_buts_stabilize2d(), node_composit_buts_tonemap(), node_composit_buts_transform(), node_composit_buts_vecblur(), node_composit_buts_view_levels(), node_composit_buts_ycc(), node_composit_buts_zcombine(), node_shader_buts_attribute(), node_shader_buts_geometry(), node_shader_buts_glossy(), node_shader_buts_mapping(), node_shader_buts_material(), node_shader_buts_tex_environment(), node_shader_buts_tex_gradient(), node_shader_buts_tex_image(), node_shader_buts_tex_magic(), node_shader_buts_tex_musgrave(), node_shader_buts_tex_sky(), node_shader_buts_tex_voronoi(), node_shader_buts_tex_wave(), node_shader_buts_vect_math(), node_texture_buts_bricks(), node_texture_buts_output(), node_texture_buts_proc(), socket_component_menu(), template_keymap_item_properties(), ui_node_draw_input(), uiTemplateHeader3D(), uiTemplateImage(), uiTemplateImageSettings(), uiTemplateMovieClip(), uiTemplatePathBuilder(), uiTemplatePreview(), v3d_editarmature_buts(), v3d_editmetaball_buts(), and v3d_transform_butsR().
void uiItemS (uiLayout * layout)
Definition at line 1573 of file interface_layout.c.
References uiLayoutRoot::block, EM_SEPR_X, EM_SEPR_Y, NULL, uiLayout::root, SEPR, uiBlockSetCurLayout(), and uiDefBut().
Referenced by active_node_panel(), graph_fmodifier_add_invoke(), header_toolbox_invoke(), logic_buttons_new(), nla_fmodifier_add_invoke(), node_add_menu(), node_composit_buts_dblur(), node_composit_buts_file_output_details(), pose_groups_menu_invoke(), template_keymap_item_properties(), ui_block_func_ICONTEXTROW(), ui_but_menu(), ui_node_draw_input(), uiItemsEnumR(), uiItemsFullEnumO(), uiTemplateColorWheel(), uiTemplateImage(), and wm_block_create_splash().
void uiItemsEnumO (uiLayout * layout, const char * opname, const char * propname)
Definition at line 848 of file interface_layout.c.
References NULL, uiLayoutRoot::opcontext, uiLayout::root, and uiItemsFullEnumO().
Referenced by delete_invoke(), insert_key_menu_invoke(), keyingset_active_menu_invoke(), menu_item_enum_opname_menu(), object_metaball_add_invoke(), select_orientation_invoke(), toggle_cyclic_invoke(), and unpack_all_invoke().
void uiItemsEnumR (uiLayout * layout, struct PointerRNA * ptr, const char * propname)
Definition at line 1185 of file interface_layout.c.
References uiLayoutRoot::block, uiBlock::buttons, uiBlock::evil_C, uiBut::flag, uiBlock::flag, i, ListBase::last, MEM_freeN(), PROP_ENUM, RNA_property_enum_items_gettexted(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, uiLayout::root, split(), PointerRNA::type, UI_BLOCK_NO_FLIP, ui_item_disabled(), UI_TEXT_LEFT, uiItemEnumR(), uiItemL(), uiItemS(), uiLayoutColumn(), and uiLayoutSplit().
Referenced by menu_item_enum_rna_menu(), and toolbox_invoke().
void uiItemsFullEnumO (uiLayout * layout, const char * opname, const char * propname, struct IDProperty * properties, int context, int flag)
Definition at line 777 of file interface_layout.c.
References BLI_assert, uiLayoutRoot::block, uiBlock::buttons, PointerRNA::data, uiBlock::evil_C, uiBut::flag, uiBlock::flag, i, IDP_CopyProperty(), IDP_FreeProperty(), ListBase::last, MEM_freeN(), NULL, PROP_ENUM, RNA_pointer_create(), RNA_property_enum_items_gettexted(), RNA_property_enum_set(), RNA_property_type(), RNA_struct_find_property(), RNA_warning, uiLayout::root, split(), wmOperatorType::srna, UI_BLOCK_NO_FLIP, ui_item_disabled(), UI_TEXT_LEFT, uiItemEnumO_ptr__internal(), uiItemFullO_ptr(), uiItemL(), uiItemS(), uiLayoutColumn(), uiLayoutSplit(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
Referenced by uiItemsEnumO(), and WM_menu_invoke().
void uiItemStringO (uiLayout * layout, const char * name, int icon, const char * opname, const char * propname, const char * value)
Definition at line 963 of file interface_layout.c.
References PointerRNA::data, uiLayoutRoot::opcontext, RNA_string_set(), uiLayout::root, UI_OPERATOR_ERROR_RET, uiItemFullO_ptr(), WM_operator_properties_create_ptr(), and WM_operatortype_find().
Referenced by draw_modifier(), recent_files_menu_draw(), select_grouped_group(), and wm_block_create_splash().
void uiItemV (uiLayout * layout, const char * name, int icon, int argval)
Definition at line 1548 of file interface_layout.c.
References uiLayoutRoot::block, BUT, uiBlock::handle, NULL, uiPopupBlockHandle::retvalue, uiLayout::root, uiLayoutRoot::type, UI_LAYOUT_MENU, ui_text_icon_width(), UI_UNIT_Y, uiBlockSetCurLayout(), uiDefButF(), uiDefIconButF(), and uiDefIconTextButF().
Referenced by node_add_menu().
uiLayout* uiLayoutAbsolute (uiLayout * layout, int align)
Definition at line 2279 of file interface_layout.c.
References uiLayout::active, uiLayout::align, BLI_addtail(), uiLayoutRoot::block, uiLayout::context, uiLayout::enabled, uiLayout::item, ITEM_LAYOUT_ABSOLUTE, uiLayout::items, MEM_callocN(), uiLayout::root, uiItem::type, and uiBlockSetCurLayout().
Referenced by ui_item_array(), uiLayoutAbsoluteBlock(), uiTemplateReportsBanner(), and uiTemplateRunningJobs().
uiBlock* uiLayoutAbsoluteBlock (uiLayout * layout)
Definition at line 2297 of file interface_layout.c.
References uiLayoutAbsolute(), and uiLayoutGetBlock().
Referenced by draw_constraint(), draw_modifier(), image_panel_uv(), node_buts_normal(), node_shader_buts_dynamic(), uiTemplateColorRamp(), uiTemplateHeader(), uiTemplateHistogram(), uiTemplateMarker(), uiTemplateTrack(), uiTemplateVectorscope(), uiTemplateWaveform(), v3d_editvertex_buts(), and view3d_panel_vgroup().
uiLayout* uiLayoutBox (uiLayout * layout)
Definition at line 2261 of file interface_layout.c.
References ROUNDBOX, and ui_layout_box().
Referenced by ANIM_uiTemplate_fmodifier_draw(), draw_actuator_header(), draw_brick_actuator(), draw_brick_controller(), draw_brick_sensor(), draw_constraint(), draw_controller_header(), draw_modifier(), draw_sensor_header(), draw_sensor_internal_header(), file_panel_category(), gp_drawui_layer(), graph_panel_drivers(), and logic_buttons_new().
uiLayout* uiLayoutColumn (uiLayout * layout, int align)
Definition at line 2199 of file interface_layout.c.
References uiLayout::active, uiLayout::align, BLI_addtail(), uiLayoutRoot::block, uiStyle::buttonspacey, uiLayout::context, uiLayout::enabled, uiLayout::item, ITEM_LAYOUT_COLUMN, uiLayout::items, MEM_callocN(), uiLayout::root, uiLayout::space, uiLayoutRoot::style, uiItem::type, uiBlockSetCurLayout(), and uiLayout::w.
Referenced by ANIM_uiTemplate_fmodifier_draw(), curvemap_buttons_layout(), draw_actuator_action(), draw_actuator_constraint(), draw_actuator_motion(), draw_actuator_sound(), draw_actuator_steering(), draw_constraint(), draw_gpencil_panel(), draw_modifier(), draw_modifier__cycles(), draw_modifier__envelope(), draw_modifier__fn_generator(), draw_modifier__limits(), draw_modifier__noise(), draw_modifier__stepped(), draw_sensor_joystick(), draw_sensor_keyboard(), file_panel_category(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_driverVar__locDiff(), graph_panel_driverVar__rotDiff(), graph_panel_driverVar__singleProp(), graph_panel_driverVar__transChan(), graph_panel_key_properties(), graph_panel_modifiers(), graph_panel_properties(), graph_panel_view(), logic_buttons_new(), nla_panel_actclip(), nla_panel_evaluation(), nla_panel_modifiers(), nla_panel_properties(), node_buts_rgb(), node_composit_buts_alphaover(), node_composit_buts_bilateralblur(), node_composit_buts_blur(), node_composit_buts_channel_matte(), node_composit_buts_chroma_matte(), node_composit_buts_color_matte(), node_composit_buts_color_spill(), node_composit_buts_colorbalance(), node_composit_buts_crop(), node_composit_buts_dblur(), node_composit_buts_defocus(), node_composit_buts_diff_matte(), node_composit_buts_distance_matte(), node_composit_buts_double_edge_mask(), node_composit_buts_file_output_details(), node_composit_buts_hue_sat(), node_composit_buts_image(), node_composit_buts_invert(), node_composit_buts_lensdist(), node_composit_buts_luma_matte(), node_composit_buts_map_value(), node_composit_buts_renderlayers(), node_composit_buts_splitviewer(), node_composit_buts_tonemap(), node_composit_buts_vecblur(), node_composit_buts_zcombine(), node_shader_buts_geometry(), node_shader_buts_material(), node_texture_buts_bricks(), node_texture_buts_proc(), socket_component_menu(), ui_block_func_MENUSTR(), ui_item_local_sublayout(), ui_node_draw_input(), ui_node_draw_node(), ui_node_menu_column(), ui_template_node_link_menu(), uiDefAutoButsRNA(), uiItemsEnumR(), uiItemsFullEnumO(), uiLayoutOperatorButs(), uiTemplateColorWheel(), uiTemplateImage(), uiTemplateImageSettings(), uiTemplateLayers(), uiTemplateList(), uiTemplateMarker(), uiTemplatePreview(), undo_history_invoke(), v3d_editarmature_buts(), v3d_editmetaball_buts(), v3d_posearmature_buts(), v3d_transform_butsR(), view3d_panel_object(), view3d_panel_tool_shelf(), view3d_panel_vgroup(), wm_block_create_splash(), and wm_block_dialog_create().
uiLayout* uiLayoutColumnFlow (uiLayout * layout, int number, int align)
Definition at line 2219 of file interface_layout.c.
References uiLayout::active, uiLayout::align, BLI_addtail(), uiLayoutRoot::block, uiStyle::columnspace, uiLayout::context, uiLayout::enabled, uiLayout::item, ITEM_LAYOUT_COLUMN_FLOW, uiLayout::items, uiLayoutItemFlow::litem, MEM_callocN(), uiLayoutItemFlow::number, uiLayout::root, uiLayout::space, uiLayoutRoot::style, uiItem::type, uiBlockSetCurLayout(), and uiLayout::w.
Referenced by template_keymap_item_properties().
void uiLayoutContextCopy (uiLayout * layout, struct bContextStore * context)
Definition at line 2725 of file interface_layout.c.
References uiLayoutRoot::block, uiLayout::context, uiBlock::contexts, CTX_store_add_all(), and uiLayout::root.
Referenced by ui_popup_menu_create().
int uiLayoutGetActive (uiLayout * layout)
Definition at line 2380 of file interface_layout.c.
References uiLayout::active.
int uiLayoutGetAlignment (uiLayout * layout)
Definition at line 2400 of file interface_layout.c.
References uiLayout::alignment.
uiBlock* uiLayoutGetBlock (uiLayout * layout)
Definition at line 2653 of file interface_layout.c.
References uiLayoutRoot::block, and uiLayout::root.
Referenced by ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), clip_panel_operator_redo(), curvemap_buttons_layout(), draw_constraint(), draw_controller_header(), draw_modifier(), draw_modifier__envelope(), draw_modifier__generator(), file_panel_category(), file_panel_operator(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_key_properties(), graph_panel_modifiers(), graph_panel_properties(), list_item_row(), nla_panel_actclip(), nla_panel_animdata(), nla_panel_evaluation(), nla_panel_modifiers(), nla_panel_properties(), nla_panel_track(), template_ID(), template_texture_user_menu(), ui_block_func_ICONROW(), ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), ui_but_menu(), ui_node_draw_input(), ui_node_menu_column(), ui_template_node_link_menu(), uiblock_layer_pass_arrow_buttons(), uiblock_layer_pass_buttons(), uiItemPointerR(), uiLayoutAbsoluteBlock(), uiLayoutOperatorButs(), uiTemplateColorWheel(), uiTemplateConstraint(), uiTemplateEditModeSelection(), uiTemplateHeader3D(), uiTemplateImage(), uiTemplateKeymapItemProperties(), uiTemplateLayers(), uiTemplateList(), uiTemplateMarker(), uiTemplateModifier(), uiTemplateMovieClip(), uiTemplateNodeLink(), uiTemplateOperatorSearch(), uiTemplatePreview(), uiTemplateReportsBanner(), uiTemplateRunningJobs(), uiTemplateTextureShow(), uiTemplateTextureUser(), view3d_panel_object(), view3d_panel_operator_redo(), view3d_panel_tool_shelf(), and wm_block_dialog_create().
int uiLayoutGetEnabled (uiLayout * layout)
Definition at line 2385 of file interface_layout.c.
References uiLayout::enabled.
int uiLayoutGetKeepAspect (uiLayout * layout)
Definition at line 2395 of file interface_layout.c.
References uiLayout::keepaspect.
int uiLayoutGetOperatorContext (uiLayout * layout)
Definition at line 2658 of file interface_layout.c.
References uiLayoutRoot::opcontext, and uiLayout::root.
int uiLayoutGetRedAlert (uiLayout * layout)
Definition at line 2390 of file interface_layout.c.
References uiLayout::redalert.
float uiLayoutGetScaleX (uiLayout * layout)
Definition at line 2410 of file interface_layout.c.
References uiLayout::scale.
float uiLayoutGetScaleY (uiLayout * layout)
Definition at line 2415 of file interface_layout.c.
References uiLayout::scale.
int uiLayoutGetWidth (uiLayout * layout)
Definition at line 2405 of file interface_layout.c.
References uiLayout::w.
Referenced by curvemap_buttons_layout(), ED_region_header(), and ui_but_menu().
const char* uiLayoutIntrospect (uiLayout * layout)
Definition at line 2803 of file interface_layout.c.
References BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), MEM_freeN(), str, and ui_intro_uiLayout().
uiLayout* uiLayoutListBox (uiLayout * layout, struct PointerRNA * ptr, struct PropertyRNA * prop, struct PointerRNA * actptr, struct PropertyRNA * actprop)
Definition at line 2266 of file interface_layout.c.
References LISTBOX, uiBut::rnapoin, uiBut::rnaprop, uiBut::rnasearchpoin, uiBut::rnasearchprop, uiLayoutItemBx::roundbox, and ui_layout_box().
Referenced by uiTemplateList().
void uiLayoutOperatorButs (const struct bContext * C, struct uiLayout * layout, struct wmOperator * op, int(*)(struct PointerRNA *, struct PropertyRNA *) check_prop, const char label_align, const short flag)
Referenced by clip_panel_operator_redo_buts(), file_panel_operator(), view3d_panel_operator_redo_buts(), wm_block_create_redo(), wm_block_dialog_create(), and wm_operator_ui_create().
uiLayout* uiLayoutOverlap (uiLayout * layout)
Definition at line 2307 of file interface_layout.c.
References uiLayout::active, BLI_addtail(), uiLayoutRoot::block, uiLayout::context, uiLayout::enabled, uiLayout::item, ITEM_LAYOUT_OVERLAP, uiLayout::items, MEM_callocN(), uiLayout::root, uiItem::type, and uiBlockSetCurLayout().
Referenced by list_item_row().
uiLayout* uiLayoutRow (uiLayout * layout, int align)
Definition at line 2179 of file interface_layout.c.
References uiLayout::active, uiLayout::align, BLI_addtail(), uiLayoutRoot::block, uiStyle::buttonspacex, uiLayout::context, uiLayout::enabled, uiLayout::item, ITEM_LAYOUT_ROW, uiLayout::items, MEM_callocN(), uiLayout::root, uiLayout::space, uiLayoutRoot::style, uiItem::type, uiBlockSetCurLayout(), and uiLayout::w.
Referenced by ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), colorband_buttons_large(), curvemap_buttons_layout(), draw_actuator_action(), draw_actuator_camera(), draw_actuator_constraint(), draw_actuator_edit_object(), draw_actuator_filter_2d(), draw_actuator_header(), draw_actuator_message(), draw_actuator_motion(), draw_actuator_parent(), draw_actuator_property(), draw_actuator_random(), draw_actuator_shape_action(), draw_actuator_sound(), draw_actuator_steering(), draw_actuator_visibility(), draw_constraint(), draw_controller_header(), draw_gpencil_panel(), draw_modifier(), draw_modifier__envelope(), draw_modifier__generator(), draw_sensor_armature(), draw_sensor_collision(), draw_sensor_delay(), draw_sensor_header(), draw_sensor_internal_header(), draw_sensor_joystick(), draw_sensor_keyboard(), draw_sensor_near(), draw_sensor_property(), draw_sensor_radar(), draw_sensor_ray(), file_panel_bookmarks(), file_panel_category(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_driverVar__singleProp(), graph_panel_modifiers(), graph_panel_properties(), list_item_row(), logic_buttons_new(), nla_panel_actclip(), nla_panel_animdata(), nla_panel_evaluation(), nla_panel_modifiers(), nla_panel_properties(), nla_panel_track(), node_buts_mix_rgb(), node_buts_time(), node_composit_buts_blur(), node_composit_buts_channel_matte(), node_composit_buts_color_spill(), node_composit_buts_colorbalance(), node_composit_buts_file_output_details(), node_composit_buts_renderlayers(), node_composit_buts_splitviewer(), node_shader_buts_mapping(), node_socket_button_output_file(), node_texture_buts_proc(), template_ID(), ui_item_local_sublayout(), ui_item_with_label(), ui_node_draw_input(), ui_template_id(), uiblock_layer_pass_arrow_buttons(), uiblock_layer_pass_buttons(), uiLayoutOperatorButs(), uiTemplateAnyID(), uiTemplateColorWheel(), uiTemplateEditModeSelection(), uiTemplateHeader3D(), uiTemplateImage(), uiTemplateImageSettings(), uiTemplateLayers(), uiTemplateList(), uiTemplateMovieClip(), uiTemplatePathBuilder(), uiTemplatePreview(), and uiTemplateRunningJobs().
void uiLayoutSetActive (uiLayout * layout, int active)
Definition at line 2345 of file interface_layout.c.
References uiLayout::active.
Referenced by draw_actuator_action(), draw_actuator_constraint(), draw_actuator_filter_2d(), draw_actuator_header(), draw_actuator_motion(), draw_actuator_parent(), draw_actuator_property(), draw_actuator_sound(), draw_actuator_steering(), draw_gpencil_panel(), draw_modifier__stepped(), draw_sensor_header(), draw_sensor_internal_header(), draw_sensor_joystick(), draw_sensor_keyboard(), graph_panel_view(), list_item_row(), logic_buttons_new(), nla_panel_actclip(), nla_panel_properties(), node_composit_buts_defocus(), node_composit_buts_file_output_details(), node_composit_buts_lensdist(), node_composit_buts_map_value(), node_menu_add(), node_texture_buts_proc(), uiTemplateImage(), uiTemplateMarker(), and v3d_transform_butsR().
void uiLayoutSetAlignment (uiLayout * layout, int alignment)
Definition at line 2365 of file interface_layout.c.
References uiLayout::alignment.
Referenced by ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), curvemap_buttons_layout(), draw_modifier(), file_panel_category(), gp_drawui_layer(), and logic_buttons_new().
void uiLayoutSetContextPointer (uiLayout * layout, const char * name, struct PointerRNA * ptr)
Definition at line 2719 of file interface_layout.c.
References uiLayoutRoot::block, uiLayout::context, uiBlock::contexts, CTX_store_add(), and uiLayout::root.
Referenced by draw_constraint(), draw_modifier(), logic_buttons_new(), uiTemplateImage(), and uiTemplateMovieClip().
void uiLayoutSetEnabled (uiLayout * layout, int enabled)
Definition at line 2350 of file interface_layout.c.
References uiLayout::enabled.
Referenced by clip_panel_operator_redo(), graph_panel_properties(), nla_panel_evaluation(), uiTemplateImage(), view3d_panel_operator_redo(), and wm_block_create_redo().
void uiLayoutSetFunc (uiLayout * layout, uiMenuHandleFunc handlefunc, void * argv)
Definition at line 2689 of file interface_layout.c.
References uiLayoutRoot::argv, uiLayoutRoot::handlefunc, and uiLayout::root.
Referenced by node_add_menu().
void uiLayoutSetKeepAspect (uiLayout * layout, int keepaspect)
Definition at line 2360 of file interface_layout.c.
References uiLayout::keepaspect.
Referenced by uiTemplatePreview().
void uiLayoutSetOperatorContext (uiLayout * layout, int opcontext)
Definition at line 2684 of file interface_layout.c.
References uiLayoutRoot::opcontext, and uiLayout::root.
Referenced by draw_constraint(), draw_modifier(), menu_item_enum_opname_menu(), menu_item_enum_rna_menu(), parent_set_invoke(), poselib_add_menu_invoke(), poselib_add_menu_invoke__replacemenu(), recent_files_menu_draw(), ui_but_menu(), ui_popup_menu_create(), uiPupMenuBegin(), unpack_all_invoke(), and wm_block_create_splash().
void uiLayoutSetRedAlert (uiLayout * layout, int redalert)
Definition at line 2355 of file interface_layout.c.
References uiLayout::redalert.
Referenced by draw_constraint().
void uiLayoutSetScaleX (uiLayout * layout, float scale)
Definition at line 2370 of file interface_layout.c.
References uiLayout::scale.
Referenced by uiTemplatePreview().
void uiLayoutSetScaleY (uiLayout * layout, float scale)
Definition at line 2375 of file interface_layout.c.
References uiLayout::scale.
uiLayout* uiLayoutSplit (uiLayout * layout, float percentage, int align)
Definition at line 2324 of file interface_layout.c.
References uiLayout::active, uiLayout::align, BLI_addtail(), uiLayoutRoot::block, uiStyle::columnspace, uiLayout::context, uiLayout::enabled, uiLayout::item, ITEM_LAYOUT_SPLIT, uiLayout::items, uiLayoutItemSplit::litem, MEM_callocN(), uiLayoutItemSplit::percentage, uiLayout::root, uiLayout::space, split(), uiLayoutRoot::style, uiItem::type, uiBlockSetCurLayout(), and uiLayout::w.
Referenced by curvemap_buttons_layout(), draw_actuator_constraint(), draw_actuator_edit_object(), draw_actuator_filter_2d(), draw_actuator_motion(), draw_actuator_state(), draw_controller_python(), draw_modifier__cycles(), draw_modifier__limits(), draw_modifier__noise(), draw_sensor_collision(), draw_sensor_internal_header(), draw_sensor_ray(), gp_drawui_layer(), graph_panel_view(), list_item_row(), logic_buttons_new(), node_composit_buts_colorbalance(), node_sockets_panel(), ui_block_func_MENUSTR(), ui_node_draw_input(), ui_node_draw_node(), ui_template_node_link_menu(), uiDefAutoButsRNA(), uiItemsEnumR(), uiItemsFullEnumO(), uiTemplateImage(), uiTemplateImageSettings(), uiTemplateMovieClip(), undo_history_invoke(), v3d_transform_butsR(), and wm_block_create_splash().
void uiMenuPopupBoundsBlock (uiBlock * block, int addvall, int mx, int my)
Definition at line 422 of file interface.c.
References uiBlock::bounds, uiBlock::dobounds, uiBlock::mx, uiBlock::my, and UI_BLOCK_BOUNDS_POPUP_MENU.
Referenced by ui_block_func_POPUP().
void uiPopupBoundsBlock (uiBlock * block, int addval, int mx, int my)
Definition at line 413 of file interface.c.
References uiBlock::bounds, uiBlock::dobounds, uiBlock::mx, uiBlock::my, and UI_BLOCK_BOUNDS_POPUP_MOUSE.
Referenced by menu_add_shortcut(), menu_change_shortcut(), wm_block_create_redo(), wm_block_dialog_create(), wm_block_search_menu(), wm_enum_search_menu(), and wm_operator_ui_create().
void uiPupBlock (struct bContext * C, uiBlockCreateFunc func, void * arg)
Definition at line 2683 of file interface_regions.c.
References NULL, and uiPupBlockO().
Referenced by popup_add_shortcut_func(), popup_change_shortcut_func(), wm_block_splash_refreshmenu(), WM_enum_search_invoke(), WM_operator_props_popup(), WM_operator_redo_popup(), wm_search_menu_invoke(), and wm_splash_invoke().
void uiPupBlockClose (struct bContext * C, uiBlock * block)
Definition at line 2726 of file interface_regions.c.
References CTX_wm_window(), uiBlock::handle, wmWindow::modalhandlers, ui_popup_block_free(), and UI_remove_popup_handlers().
Referenced by dialog_exec_cb(), wm_block_splash_close(), and wm_block_splash_refreshmenu().
void uiPupBlockEx (struct bContext * C, uiBlockCreateFunc func, uiBlockHandleFunc popup_func, uiBlockCancelFunc cancel_func, void * arg)
Definition at line 2688 of file interface_regions.c.
References uiPopupBlockHandle::cancel_func, CTX_wm_window(), wmWindow::modalhandlers, NULL, uiPopupBlockHandle::popup, uiPopupBlockHandle::popup_arg, uiPopupBlockHandle::popup_func, uiPopupBlockHandle::retvalue, UI_add_popup_handlers(), ui_popup_block_create(), and WM_event_add_mousemove().
Referenced by WM_operator_props_dialog_popup(), and WM_operator_ui_popup().
void uiPupBlockO (struct bContext * C, uiBlockCreateFunc func, void * arg, const char * opname, int opcontext)
Definition at line 2669 of file interface_regions.c.
References CTX_wm_window(), wmWindow::modalhandlers, NULL, uiPopupBlockHandle::opcontext, uiPopupBlockHandle::optype, uiPopupBlockHandle::popup, UI_add_popup_handlers(), ui_popup_block_create(), WM_event_add_mousemove(), and WM_operatortype_find().
Referenced by uiPupBlock().
uiPopupMenu* uiPupMenuBegin (struct bContext * C, const char * title, int icon)
Definition at line 2449 of file interface_regions.c.
References BLI_snprintf(), uiPopupMenu::block, uiBut::flag, uiBlock::flag, uiBlock::handle, LABEL, uiPopupMenu::layout, MEM_callocN(), NULL, uiBlock::puphash, UI_BLOCK_POPUP_MEMORY, UI_EMBOSSP, UI_GetStyle(), UI_LAYOUT_MENU, UI_LAYOUT_VERTICAL, ui_popup_menu_hash(), UI_TEXT_LEFT, UI_UNIT_Y, uiBeginBlock(), uiBlockLayout(), uiDefBut(), uiDefIconTextBut(), uiLayoutSetOperatorContext(), and WM_OP_EXEC_REGION_WIN.
Referenced by armature_parent_set_invoke(), delete_invoke(), graph_fmodifier_add_invoke(), header_toolbox_invoke(), image_pack_invoke(), insert_key_menu_invoke(), keyingset_active_menu_invoke(), make_proxy_invoke(), nla_fmodifier_add_invoke(), object_metaball_add_invoke(), parent_drop_invoke(), parent_set_invoke(), pose_groups_menu_invoke(), pose_ik_add_invoke(), poselib_add_menu_invoke(), repeat_history_invoke(), screen_area_options_invoke(), select_grouped_group(), select_orientation_invoke(), text_resolve_conflict_invoke(), toggle_cyclic_invoke(), toolbox_invoke(), ui_but_menu(), uiPupMenuInvoke(), undo_history_invoke(), unpack_all_invoke(), unpack_menu(), WM_menu_invoke(), and WM_operator_confirm_message().
void uiPupMenuEnd (struct bContext * C, struct uiPopupMenu * head)
Definition at line 2482 of file interface_regions.c.
References CTX_wm_window(), wmWindow::eventstate, MEM_freeN(), wmWindow::modalhandlers, uiPopupMenu::mx, uiPopupMenu::my, NULL, uiPopupBlockHandle::popup, uiPopupMenu::popup, UI_add_popup_handlers(), ui_block_func_POPUP(), ui_popup_block_create(), WM_event_add_mousemove(), wmEvent::x, and wmEvent::y.
Referenced by armature_parent_set_invoke(), delete_invoke(), graph_fmodifier_add_invoke(), header_toolbox_invoke(), image_pack_invoke(), insert_key_menu_invoke(), keyingset_active_menu_invoke(), make_proxy_invoke(), nla_fmodifier_add_invoke(), object_metaball_add_invoke(), parent_drop_invoke(), parent_set_invoke(), pose_groups_menu_invoke(), pose_ik_add_invoke(), poselib_add_menu_invoke(), repeat_history_invoke(), screen_area_options_invoke(), select_grouped_group(), select_orientation_invoke(), text_resolve_conflict_invoke(), toggle_cyclic_invoke(), toolbox_invoke(), ui_but_menu(), uiPupMenuInvoke(), undo_history_invoke(), unpack_all_invoke(), unpack_menu(), WM_menu_invoke(), and WM_operator_confirm_message().
void uiPupMenuError (struct bContext * C, const char * str, ...)
Definition at line 2593 of file interface_regions.c.
References BLI_snprintf(), BLI_strncpy(), NULL, and vconfirm_opname().
void uiPupMenuInvoke (struct bContext * C, const char * idname)
Definition at line 2640 of file interface_regions.c.
References MenuType::draw, IFACE_, MenuType::label, Menu::layout, mt, NULL, MenuType::poll, TRUE, Menu::type, uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), and WM_menutype_find().
Referenced by wm_call_menu_exec().
struct uiLayout* uiPupMenuLayout (uiPopupMenu * head) [read]
Definition at line 2500 of file interface_regions.c.
References uiPopupMenu::layout.
Referenced by armature_parent_set_invoke(), delete_invoke(), graph_fmodifier_add_invoke(), header_toolbox_invoke(), image_pack_invoke(), insert_key_menu_invoke(), keyingset_active_menu_invoke(), make_proxy_invoke(), nla_fmodifier_add_invoke(), object_metaball_add_invoke(), parent_drop_invoke(), parent_set_invoke(), pose_groups_menu_invoke(), pose_ik_add_invoke(), poselib_add_menu_invoke(), repeat_history_invoke(), screen_area_options_invoke(), select_grouped_group(), select_orientation_invoke(), text_resolve_conflict_invoke(), toggle_cyclic_invoke(), toolbox_invoke(), ui_but_menu(), uiPupMenuInvoke(), undo_history_invoke(), unpack_all_invoke(), unpack_menu(), WM_menu_invoke(), and WM_operator_confirm_message().
void uiPupMenuNotice (struct bContext * C, const char * str, ...)
Definition at line 2584 of file interface_regions.c.
References NULL, and vconfirm_opname().
void uiPupMenuOkee (struct bContext * C, const char * opname, const char * str, ...)
Definition at line 2562 of file interface_regions.c.
References BLI_snprintf(), and vconfirm_opname().
Referenced by node_group_edit_invoke(), and pack_all_invoke().
void uiPupMenuReports (struct bContext * C, struct ReportList * reports)
Definition at line 2608 of file interface_regions.c.
References BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), CTX_wm_window(), ListBase::first, ReportList::list, MEM_freeN(), Report::message, Report::next, NULL, ReportList::printlevel, RPT_ERROR, RPT_INFO, RPT_WARNING, str, Report::type, and ui_popup_menu_create().
Referenced by wm_handler_fileselect_call(), and wm_operator_reports().
void uiPupMenuSaveOver (struct bContext * C, struct wmOperator * op, const char * filename)
Definition at line 2579 of file interface_regions.c.
References confirm_operator().
Referenced by wm_handler_fileselect_call(), and wm_save_mainfile_invoke().
void uiRoundBox (float minx, float miny, float maxx, float maxy, float rad)
Definition at line 381 of file interface_draw.c.
References roundboxtype, ui_draw_anti_roundbox(), and UI_RB_ALPHA.
Referenced by draw_textscroll(), draw_tile(), node_draw_basis(), node_draw_hidden(), outliner_draw_iconrow(), outliner_draw_tree_element(), region_draw_azone_tab_plus(), and wm_drop_operator_draw().
void uiRoundRect (float minx, float miny, float maxx, float maxy, float rad)
Definition at line 359 of file interface_draw.c.
References roundboxtype, UI_RB_ALPHA, and uiDrawBox().
Referenced by region_draw_azone_tab(), and ui_draw_aligned_panel().
int uiSearchBoxhHeight (void)
Definition at line 759 of file interface_regions.c.
References MENU_TOP, SEARCH_ITEMS, and UI_UNIT_Y.
Referenced by id_search_menu(), operator_search_menu(), tool_search_menu(), ui_searchbox_create(), wm_block_search_menu(), and wm_enum_search_menu().
int uiSearchItemAdd (uiSearchItems * items, const char * name, void * poin, int iconid)
Definition at line 720 of file interface_regions.c.
References uiSearchItems::active, autocomplete_do_name(), uiSearchItems::autocpl, BLI_strncpy(), uiSearchItems::icons, uiSearchItems::maxitem, uiSearchItems::maxstrlen, uiSearchItems::more, uiSearchItems::names, uiSearchItems::offset_i, uiSearchItems::pointers, and uiSearchItems::totitem.
Referenced by id_search_cb(), operator_enum_search_cb(), operator_search_cb(), and rna_search_cb().
void uiSetButLink (struct uiBut * but, void ** poin, void *** ppoin, short * tot, int from, int to)
Definition at line 3243 of file interface.c.
References uiLink::fromcode, link(), uiBut::link, MEM_callocN(), uiLink::poin, uiLink::ppoin, uiLink::tocode, and uiLink::totlink.
Referenced by logic_buttons(), logic_buttons_new(), and ui_add_smart_controller().
void uiSetRoundBox (int type)
Definition at line 65 of file interface_draw.c.
References roundboxtype.
Referenced by acf_generic_root_backdrop(), acf_group_backdrop(), acf_summary_backdrop(), draw_image_seq(), draw_nla_channel_list_gl(), draw_scope_end(), draw_textscroll(), draw_tile(), drawviewborder(), file_draw_list(), nla_draw_strip(), node_draw_basis(), node_draw_group(), node_draw_hidden(), outliner_draw_iconrow(), outliner_draw_tree_element(), region_draw_azone_tab(), region_draw_azone_tab_plus(), ui_draw_aligned_panel(), ui_draw_but_HISTOGRAM(), ui_draw_but_NORMAL(), ui_draw_but_TRACKPREVIEW(), and wm_drop_operator_draw().
void uiStyleFontDraw (struct uiFontStyle * fs, struct rcti * rect, const char * str)
Definition at line 193 of file interface_style.c.
References uiStyleFontDrawExt().
Referenced by file_draw_string(), ui_draw_aligned_panel_header(), ui_draw_menu_item(), ui_draw_preview_item(), ui_tooltip_region_draw_cb(), and widget_draw_text().
void uiStyleFontDrawExt (struct uiFontStyle * fs, struct rcti * rect, const char * str, float * r_xofs, float * r_yofs)
Definition at line 146 of file interface_style.c.
References uiFontStyle::align, BLF_ascender(), BLF_CLIPPING, BLF_clipping(), BLF_disable(), BLF_draw(), BLF_DRAW_STR_DUMMY_MAX, BLF_enable(), BLF_KERNING_DEFAULT, BLF_position(), BLF_shadow(), BLF_SHADOW, BLF_shadow_offset(), BLF_width(), uiFontStyle::kerning, uiFontStyle::shadow, uiFontStyle::shadowalpha, uiFontStyle::shadowcolor, uiFontStyle::shadx, uiFontStyle::shady, UI_STYLE_TEXT_CENTER, UI_STYLE_TEXT_RIGHT, uiFontStyle::uifont_id, uiStyleFontSet(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by uiStyleFontDraw(), and widget_draw_text().
void uiStyleFontDrawRotated (struct uiFontStyle * fs, struct rcti * rect, const char * str)
Definition at line 201 of file interface_style.c.
References angle(), BLF_ascender(), BLF_CLIPPING, BLF_clipping(), BLF_disable(), BLF_draw(), BLF_DRAW_STR_DUMMY_MAX, BLF_enable(), BLF_KERNING_DEFAULT, BLF_position(), BLF_ROTATION, BLF_rotation(), BLF_shadow(), BLF_SHADOW, BLF_shadow_offset(), BLF_width(), uiFontStyle::kerning, uiFontStyle::shadow, uiFontStyle::shadowalpha, uiFontStyle::shadowcolor, uiFontStyle::shadx, uiFontStyle::shady, uiFontStyle::uifont_id, uiStyleFontSet(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_aligned_panel_header().
void uiStyleFontSet (struct uiFontStyle * fs)
Definition at line 390 of file interface_style.c.
References uiFont::blf_id, BLF_size(), uiFontStyle::points, uiFontStyle::uifont_id, and uifont_to_blfont().
Referenced by file_font_pointsize(), file_string_width(), ui_draw_menu_item(), UI_DrawString(), UI_GetStringWidth(), ui_searchbox_create(), ui_text_bounds_block(), ui_text_label_rightclip(), ui_text_leftclip(), ui_textedit_set_cursor_pos(), ui_tooltip_create(), ui_tooltip_region_draw_cb(), uiStyleFontDrawExt(), uiStyleFontDrawRotated(), and widget_draw_text().
void uiTemplateAnyID (uiLayout * layout, struct PointerRNA * ptr, const char * propname, const char * proptypename, const char * text)
Definition at line 557 of file interface_templates.c.
References PROP_ENUM, PROP_POINTER, RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, PointerRNA::type, UI_ITEM_R_ICON_ONLY, uiItemFullR(), uiItemL(), and uiLayoutRow().
Referenced by graph_panel_driverVar__locDiff(), graph_panel_driverVar__rotDiff(), graph_panel_driverVar__singleProp(), and graph_panel_driverVar__transChan().
void uiTemplateColorRamp (uiLayout * layout, struct PointerRNA * ptr, const char * propname, int expand)
Definition at line 1416 of file interface_templates.c.
References colorband_buttons_layout(), PointerRNA::data, MEM_callocN(), MEM_freeN(), RNAUpdateCb::prop, PROP_POINTER, RNAUpdateCb::ptr, RNA_ColorRamp, RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_is_a(), PointerRNA::type, uiLayoutAbsoluteBlock(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by node_buts_colorramp().
void uiTemplateColorWheel (uiLayout * layout, struct PointerRNA * ptr, const char * propname, int value_slider, int lock, int lock_luminosity, int cubic)
Definition at line 1923 of file interface_templates.c.
References uiBut::a2, uiBut::flag, HSVCIRCLE, HSVCUBE, len_v3(), RNA_property_float_get_array(), RNA_property_float_ui_range(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, step(), PointerRNA::type, UI_BUT_COLOR_CUBIC, UI_BUT_COLOR_LOCK, UI_BUT_VEC_SIZE_LOCK, UI_GRAD_V_ALT, uiDefButR_prop(), uiItemS(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), and WHEEL_SIZE.
Referenced by node_buts_rgb(), node_composit_buts_colorbalance(), and node_composit_buts_colorbalance_but().
uiLayout* uiTemplateConstraint (uiLayout * layout, struct PointerRNA * ptr)
Definition at line 1108 of file interface_templates.c.
References CONSTRAINT_IK_TEMP, CONSTRAINT_TYPE_KINEMATIC, data, bConstraint::data, PointerRNA::data, draw_constraint(), ERROR_LIBDATA_MESSAGE, bKinematicConstraint::flag, GS, Object::id, PointerRNA::id, ID_OB, ID::lib, ID::name, NULL, RNA_Constraint, RNA_struct_is_a(), RNA_warning, bConstraint::type, PointerRNA::type, uiBlockSetButLock(), and uiLayoutGetBlock().
void uiTemplateCurveMapping (uiLayout * layout, struct PointerRNA * ptr, const char * propname, int type, int levels, int brush)
Definition at line 1888 of file interface_templates.c.
References curvemap_buttons_layout(), PointerRNA::data, MEM_callocN(), MEM_freeN(), RNAUpdateCb::prop, PROP_POINTER, RNAUpdateCb::ptr, RNA_CurveMapping, RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_struct_is_a(), RNA_warning, and PointerRNA::type.
Referenced by image_panel_curves(), node_buts_curvecol(), node_buts_curvevec(), node_buts_time(), and node_composit_buts_huecorrect().
void uiTemplateDopeSheetFilter (uiLayout * layout, struct bContext * C, struct PointerRNA * ptr)
void uiTemplateEditModeSelection (uiLayout * layout, struct bContext * C)
Definition at line 442 of file view3d_header.c.
References B_SEL_EDGE, B_SEL_FACE, B_SEL_VERT, BMEdit_FromObject(), CTX_data_edit_object(), do_view3d_header_buttons(), NULL, OB_MESH, SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, TOG, Object::type, UI_UNIT_X, UI_UNIT_Y, uiBlockSetHandleFunc(), uiDefIconButBitS(), uiLayoutGetBlock(), and uiLayoutRow().
Referenced by uiTemplateHeader3D().
void uiTemplateHeader (uiLayout * layout, struct bContext * C, int menus)
Definition at line 82 of file interface_templates.c.
References ED_area_header_standardbuttons(), ED_area_header_switchbutton(), and uiLayoutAbsoluteBlock().
void uiTemplateHeader3D (uiLayout * layout, struct bContext * C)
Definition at line 461 of file view3d_header.c.
References B_MAN_MODE, B_MAN_ROT, B_MAN_SCALE, B_MAN_TRANS, B_MODESELECT, BIF_countTransformOrientation(), BIF_menustringTransformOrientation(), CTX_data_edit_object(), CTX_data_scene(), CTX_data_tool_settings(), CTX_wm_area(), CTX_wm_screen(), Object::data, do_view3d_header_buttons(), ELEM, ELEM4, ListBase::first, Scene::id, Object::id, bScreen::id, Object::lay, View3D::localvd, MEM_freeN(), MENU, Object::mode, View3D::modeselect, NULL, OB_MODE_OBJECT, OB_MODE_PARTICLE_EDIT, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, OBACT, object_mode_icon(), RNA_Mesh, RNA_pointer_create(), RNA_Scene, RNA_SpaceView3D, RNA_ToolSettings, View3D::scenelock, ScrArea::spacedata, TIP_, TOG, View3D::twflag, View3D::twmode, View3D::twtype, UI_BUT_UNDO, UI_DPI_FAC, UI_EMBOSS, UI_ITEM_R_ICON_ONLY, UI_UNIT_X, UI_UNIT_Y, uiBlockSetEmboss(), uiBlockSetHandleFunc(), uiButClearFlag(), uiDefButC(), uiDefIconButBitC(), uiDefIconTextButS(), uiItemR(), uiLayoutGetBlock(), uiLayoutRow(), uiTemplateEditModeSelection(), uiTemplateLayers(), V3D_MANIP_CUSTOM, V3D_MANIP_ROTATE, V3D_MANIP_SCALE, V3D_MANIP_TRANSLATE, V3D_USE_MANIPULATOR, and view3d_modeselect_pup().
void uiTemplateHistogram (uiLayout * layout, struct PointerRNA * ptr, const char * propname)
Definition at line 1446 of file interface_templates.c.
References PointerRNA::data, Histogram::height, HISTOGRAM, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), NULL, RNAUpdateCb::prop, PROP_POINTER, RNAUpdateCb::ptr, RNA_Histogram, RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_is_a(), rna_update_cb(), PointerRNA::type, UI_UNIT_Y, uiButSetNFunc(), uiDefBut(), uiLayoutAbsoluteBlock(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
void uiTemplateID (uiLayout * layout, struct bContext * C, struct PointerRNA * ptr, const char * propname, const char * newop, const char * openop, const char * unlinkop)
Definition at line 535 of file interface_templates.c.
References UI_ID_BROWSE, UI_ID_DELETE, UI_ID_RENAME, and ui_template_id().
Referenced by draw_actuator_sound(), draw_gpencil_panel(), nla_panel_animdata(), node_composit_buts_image(), node_composit_buts_movieclip(), node_composit_buts_moviedistortion(), node_composit_buts_renderlayers(), node_composit_buts_stabilize2d(), node_shader_buts_material(), node_shader_buts_tex_environment(), node_shader_buts_tex_image(), node_texture_buts_image(), uiTemplateImage(), and uiTemplateMovieClip().
void uiTemplateIDBrowse (uiLayout * layout, struct bContext * C, struct PointerRNA * ptr, const char * propname, const char * newop, const char * openop, const char * unlinkop)
Definition at line 540 of file interface_templates.c.
References UI_ID_BROWSE, UI_ID_RENAME, and ui_template_id().
Referenced by node_draw_group(), and node_uifunc_group().
void uiTemplateIDPreview (uiLayout * layout, struct bContext * C, struct PointerRNA * ptr, const char * propname, const char * newop, const char * openop, const char * unlinkop, int rows, int cols)
Definition at line 545 of file interface_templates.c.
References UI_ID_BROWSE, UI_ID_DELETE, UI_ID_PREVIEWS, UI_ID_RENAME, and ui_template_id().
void uiTemplateImage (uiLayout * layout, struct bContext * C, struct PointerRNA * ptr, const char * propname, struct PointerRNA * userptr, int compact)
Definition at line 614 of file image_buttons.c.
References Image::anim, B_IMAGECHANGED, B_NOP, B_SIMA_PLAY, B_SIMA_RECORD, BKE_image_acquire_ibuf(), BKE_image_release_ibuf(), BLI_snprintf(), BUT, CTX_data_scene(), PointerRNA::data, ELEM, ImageUser::flag, ImageUser::framenr, ImageUser::frames, Scene::id, Image::id, IMA_ANIM_REFRESHED, IMA_SRC_GENERATED, IMA_SRC_MOVIE, IMA_SRC_SEQUENCE, IMA_SRC_VIEWER, IMA_TYPE_COMPOSITE, IMA_TYPE_MULTILAYER, IMA_TYPE_R_RESULT, image_info(), RNAUpdateCb::iuser, MAXFRAMEF, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), ID::name, NC_IMAGE, Scene::nodetree, ntree_get_active_iuser(), NULL, NUM, Image::packedfile, RNAUpdateCb::prop, PROP_POINTER, RNAUpdateCb::ptr, RE_AcquireResultRead(), RE_GetRender(), RE_ReleaseResult(), Image::render_slot, RNA_boolean_get(), RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), rna_update_cb(), Image::rr, set_frames_cb(), ImageUser::sfra, Image::source, split(), str, Image::type, PointerRNA::type, UI_ITEM_R_EXPAND, UI_UNIT_X, UI_UNIT_Y, uiblock_layer_pass_arrow_buttons(), uiBlockBeginAlign(), uiBlockSetNFunc(), uiButSetFunc(), uiDefBut(), uiDefButI(), uiDefIconTextBut(), uiItemL(), uiItemO(), uiItemR(), uiItemS(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), uiLayoutSetActive(), uiLayoutSetContextPointer(), uiLayoutSetEnabled(), uiLayoutSplit(), uiTemplateID(), and WM_event_add_notifier().
void uiTemplateImageLayers (uiLayout * layout, struct bContext * C, struct Image * ima, struct ImageUser * iuser)
Definition at line 874 of file image_buttons.c.
References CTX_data_scene(), Scene::id, IMA_TYPE_R_RESULT, ID::name, NULL, RE_AcquireResultRead(), RE_GetRender(), RE_ReleaseResult(), Image::render_slot, Image::type, UI_DPI_FAC, and uiblock_layer_pass_buttons().
void uiTemplateImageSettings (uiLayout * layout, struct PointerRNA * imfptr)
Definition at line 802 of file image_buttons.c.
References BKE_imtype_supports_compress(), BKE_imtype_supports_quality(), BKE_imtype_supports_zbuf(), BKE_imtype_valid_depths(), PointerRNA::data, ELEM, ELEM6, GS, PointerRNA::id, ID_SCE, ImageFormatData::imtype, ID::name, NULL, R_IMF_CHAN_DEPTH_1, R_IMF_CHAN_DEPTH_12, R_IMF_CHAN_DEPTH_16, R_IMF_CHAN_DEPTH_24, R_IMF_CHAN_DEPTH_32, R_IMF_CHAN_DEPTH_8, R_IMF_IMTYPE_CINEON, R_IMF_IMTYPE_JP2, R_IMF_IMTYPE_MULTILAYER, R_IMF_IMTYPE_OPENEXR, split(), UI_ITEM_R_EXPAND, uiItemL(), uiItemR(), uiLayoutColumn(), uiLayoutRow(), and uiLayoutSplit().
Referenced by image_save_as_draw(), node_composit_buts_file_output_details(), and screenshot_draw().
void uiTemplateKeymapItemProperties (uiLayout * layout, struct PointerRNA * ptr)
Definition at line 2729 of file interface_templates.c.
References uiBlock::buttons, PointerRNA::data, keymap_item_modified(), ListBase::last, uiBut::next, NULL, RNA_pointer_get(), template_keymap_item_properties(), uiButSetFunc(), and uiLayoutGetBlock().
void uiTemplateLayers (uiLayout * layout, struct PointerRNA * ptr, const char * propname, PointerRNA * used_ptr, const char * used_propname, int active_layer)
Definition at line 1991 of file interface_templates.c.
References handle_layer_buttons(), NULL, RNA_property_array_length(), RNA_property_boolean_get_index(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_warning, SET_INT_IN_POINTER, TOG, uiBut::type, PointerRNA::type, UI_UNIT_X, UI_UNIT_Y, uiButSetFunc(), uiDefAutoButR(), uiLayoutColumn(), uiLayoutGetBlock(), and uiLayoutRow().
Referenced by draw_actuator_state(), logic_buttons_new(), and uiTemplateHeader3D().
void uiTemplateList (uiLayout * layout, struct bContext * C, struct PointerRNA * ptr, const char * propname, struct PointerRNA * activeptr, const char * activeprop, const char * prop_list, int rows, int maxrows, int type)
Definition at line 2295 of file interface_templates.c.
References BLI_snprintf(), CLAMPIS, PointerRNA::data, i, len(), Panel::list_grip_size, list_item_icon_get(), list_item_row(), Panel::list_last_len, Panel::list_scroll, Panel::list_size, LISTROW, max, MAX2, MEM_freeN(), min, MIN2, NULL, NUM, uiBlock::panel, PROP_COLLECTION, PROP_INT, RNA_PROP_BEGIN, RNA_PROP_END, RNA_property_collection_length(), RNA_property_int_get(), RNA_property_int_range(), RNA_property_pointer_type(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), RNA_struct_name_get_alloc(), RNA_struct_ui_icon(), RNA_warning, SCROLL, PointerRNA::type, UI_BUT_DISABLED, UI_BUT_NO_TOOLTIP, UI_UNIT_X, UI_UNIT_Y, uiButSetFlag(), uiDefButI(), uiDefIconButR_prop(), uiDefIconTextButR_prop(), uiItemL(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutListBox(), and uiLayoutRow().
Referenced by node_composit_buts_file_output_details().
void uiTemplateMarker (struct uiLayout * layout, struct PointerRNA * ptr, const char * propname, PointerRNA * userptr, PointerRNA * trackptr, int cmpact)
Definition at line 318 of file clip_buttons.c.
References add_v2_v2v2(), B_MARKER_FLAG, B_MARKER_OFFSET, B_MARKER_PAT_DIM, B_MARKER_POS, B_MARKER_SEARCH_DIM, B_MARKER_SEARCH_POS, BKE_movieclip_get_size(), BKE_tracking_get_marker(), MarkerUpdateCb::clip, MarkerUpdateCb::compact, PointerRNA::data, MovieTrackingMarker::flag, MovieTrackingTrack::flag, MarkerUpdateCb::framenr, MovieClipUser::framenr, LABEL, marker_block_handler(), MARKER_DISABLED, MarkerUpdateCb::marker_flag, MarkerUpdateCb::marker_pos, marker_update_cb(), MEM_callocN(), mul_v2_fl(), NULL, NUM, MovieTrackingTrack::offset, OPTIONN, MovieTrackingTrack::pat_max, MovieTrackingTrack::pat_min, MovieTrackingMarker::pos, PROP_POINTER, RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), MovieTrackingTrack::search_max, MovieTrackingTrack::search_min, step(), sub_v2_v2v2(), to_pixel_space(), TOGN, MarkerUpdateCb::track, TRACK_LOCKED, MarkerUpdateCb::track_offset, MarkerUpdateCb::track_pat, MarkerUpdateCb::track_search, MarkerUpdateCb::track_search_pos, PointerRNA::type, uiBlockBeginAlign(), uiBlockEndAlign(), uiBlockSetHandleFunc(), uiBlockSetNFunc(), uiButSetNFunc(), uiDefBut(), uiDefButBitI(), uiDefButF(), uiDefIconButBitI(), uiLayoutAbsoluteBlock(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutSetActive(), and MarkerUpdateCb::user.
uiLayout* uiTemplateModifier (uiLayout * layout, struct bContext * C, struct PointerRNA * ptr)
Definition at line 880 of file interface_templates.c.
References CTX_data_scene(), PointerRNA::data, draw_modifier(), eModifierMode_Virtual, ERROR_LIBDATA_MESSAGE, GS, i, Object::id, PointerRNA::id, ID_OB, ID::lib, modifiers_getCageIndex(), modifiers_getVirtualModifierList(), ID::name, ModifierData::next, NULL, RNA_Modifier, RNA_struct_is_a(), RNA_warning, PointerRNA::type, uiBlockSetButLock(), and uiLayoutGetBlock().
void uiTemplateMovieClip (struct uiLayout * layout, struct bContext * C, struct PointerRNA * ptr, const char * propname, int compact)
Definition at line 80 of file clip_buttons.c.
References PointerRNA::data, LABEL, NULL, PROP_POINTER, RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), split(), PointerRNA::type, uiDefBut(), uiItemO(), uiItemR(), uiLayoutGetBlock(), uiLayoutRow(), uiLayoutSetContextPointer(), uiLayoutSplit(), and uiTemplateID().
void uiTemplateNodeLink (uiLayout * layout, struct bNodeTree * ntree, struct bNode * node, struct bNodeSocket * input)
Definition at line 496 of file node_templates.c.
References uiBut::flag, bNode::flag, bNodeSocket::flag, bNodeLink::fromnode, uiBut::func_argN, bNodeSocket::link, MEM_callocN(), MENU, NodeLinkArg::node, NODE_ACTIVE_TEXTURE, NodeLinkArg::ntree, NULL, NodeLinkArg::output, uiBut::poin, NodeLinkArg::sock, SOCK_HIDE_VALUE, SOCK_SHADER, bNodeSocket::type, uiBut::type, NodeLinkArg::type, UI_BUT_NODE_ACTIVE, UI_BUT_NODE_LINK, UI_MAX_NAME_STR, ui_node_sock_name(), ui_template_node_link_menu(), UI_TEXT_LEFT, UI_UNIT_X, UI_UNIT_Y, uiBlockSetCurLayout(), uiDefIconMenuBut(), uiDefMenuBut(), and uiLayoutGetBlock().
Referenced by node_sockets_panel(), and ui_node_draw_input().
void uiTemplateNodeView (uiLayout * layout, struct bContext * C, struct bNodeTree * ntree, struct bNode * node, struct bNodeSocket * input)
Definition at line 650 of file node_templates.c.
References ListBase::first, bNode::flag, bNode::next, NODE_TEST, bNodeTree::nodes, ui_node_draw_input(), and ui_node_draw_node().
void uiTemplateOperatorSearch (uiLayout * layout)
Definition at line 2515 of file interface_templates.c.
References NULL, operator_call_cb(), operator_search_cb(), UI_UNIT_X, UI_UNIT_Y, uiBlockSetCurLayout(), uiButSetSearchFunc(), uiDefSearchBut(), and uiLayoutGetBlock().
void uiTemplatePathBuilder (uiLayout * layout, struct PointerRNA * ptr, const char * propname, struct PointerRNA * root_ptr, const char * text)
Referenced by graph_panel_driverVar__singleProp().
void uiTemplatePreview (uiLayout * layout, struct ID * id, int show_buttons, struct ID * parent, struct MTex * slot)
Definition at line 1157 of file interface_templates.c.
References B_MATPRV, BUT_EXTRA, do_preview_buttons(), ED_preview_draw(), ELEM4, GS, ID_LA, ID_MA, ID_TE, ID_WO, IFACE_, ID::name, NULL, RNA_Material, RNA_pointer_create(), RNA_Texture, RNA_warning, ROW, TEX_PR_BOTH, TEX_PR_OTHER, TEX_PR_TEXTURE, UI_ITEM_R_EXPAND, UI_UNIT_X, UI_UNIT_Y, uiBlockSetDrawExtraFunc(), uiBlockSetHandleFunc(), uiDefBut(), uiDefButS(), uiItemR(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), uiLayoutSetKeepAspect(), and uiLayoutSetScaleX().
void uiTemplateReportsBanner (uiLayout * layout, struct bContext * C)
Definition at line 2623 of file interface_templates.c.
References BKE_reports_last_displayable(), BLF_width(), BUT, uiBut::col, ReportTimerInfo::col, CTX_wm_reports(), wmTimer::customdata, ListBase::first, FTOCHAR, ReportTimerInfo::greyscale, if(), LABEL, ListBase::last, ReportList::list, MAX2, Report::message, MIN2, NULL, ReportList::reporttimer, rgb_float_to_uchar(), ROUNDBOX, RPT_ERROR_ALL, RPT_INFO_ALL, RPT_WARNING_ALL, TIP_, Report::type, UI_EMBOSS, UI_EMBOSSN, UI_GetStyle(), UI_UNIT_X, UI_UNIT_Y, uiBlockBeginAlign(), uiBlockEndAlign(), uiBlockSetEmboss(), uiDefBut(), uiDefIconBut(), uiDefIconButO(), uiFontStyle::uifont_id, uiLayoutAbsolute(), uiLayoutGetBlock(), uiStyle::widget, ReportTimerInfo::widthfac, and WM_OP_INVOKE_REGION_WIN.
void uiTemplateRunningJobs (uiLayout * layout, struct bContext * C)
Definition at line 2561 of file interface_templates.c.
References bScreen::animtimer, B_STOPANIM, B_STOPCAST, B_STOPCLIP, B_STOPCOMPO, B_STOPRENDER, B_STOPSEQ, BUT, CTX_data_main(), CTX_wm_area(), CTX_wm_manager(), CTX_wm_screen(), do_running_jobs(), Scene::id, IFACE_, ID::next, NULL, PROGRESSBAR, SPACE_CLIP, SPACE_NODE, SPACE_SEQ, ScrArea::spacetype, TIP_, UI_UNIT_X, UI_UNIT_Y, uiBlockSetCurLayout(), uiBlockSetHandleFunc(), uiDefBut(), uiDefIconBut(), uiDefIconTextBut(), uiLayoutAbsolute(), uiLayoutGetBlock(), uiLayoutRow(), WM_jobs_name(), WM_jobs_progress(), and WM_jobs_test().
void uiTemplateTextureImage (uiLayout * layout, struct bContext * C, struct Tex * tex)
void uiTemplateTextureShow (uiLayout * layout, struct bContext * C, struct PointerRNA * ptr, struct PropertyRNA * prop)
Definition at line 441 of file buttons_texture.c.
References BCONTEXT_TEXTURE, BUT, CTX_wm_space_buts(), PointerRNA::data, ListBase::first, if(), SpaceButs::mainb, NULL, template_texture_show(), SpaceButs::texuser, UI_UNIT_X, UI_UNIT_Y, uiButSetFunc(), uiDefIconBut(), uiLayoutGetBlock(), and ButsContextTexture::users.
Referenced by template_ID().
void uiTemplateTextureUser (uiLayout * layout, struct bContext * C)
Definition at line 371 of file buttons_texture.c.
References BLI_snprintf(), CTX_wm_space_buts(), uiBut::flag, ButsTextureUser::icon, MENU, ButsTextureUser::name, NULL, template_texture_user_menu(), SpaceButs::texuser, uiBut::type, UI_ICON_SUBMENU, UI_MAX_NAME_STR, UI_TEXT_LEFT, UI_UNIT_X, UI_UNIT_Y, uiDefIconTextMenuBut(), uiDefMenuBut(), uiItemL(), uiLayoutGetBlock(), and ButsContextTexture::user.
void uiTemplateTrack (struct uiLayout * layout, struct PointerRNA * ptr, const char * propname)
Definition at line 128 of file clip_buttons.c.
References PointerRNA::data, PROP_POINTER, RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), MovieClipScopes::track_preview_height, TRACKPREVIEW, PointerRNA::type, UI_UNIT_Y, uiDefBut(), uiLayoutAbsoluteBlock(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
void uiTemplateVectorscope (uiLayout * layout, struct PointerRNA * ptr, const char * propname)
Definition at line 1522 of file interface_templates.c.
References PointerRNA::data, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), NULL, RNAUpdateCb::prop, PROP_POINTER, RNAUpdateCb::ptr, RNA_property_pointer_get(), RNA_property_type(), RNA_Scopes, RNA_struct_find_property(), RNA_struct_is_a(), rna_update_cb(), PointerRNA::type, UI_UNIT_Y, uiButSetNFunc(), uiDefBut(), uiLayoutAbsoluteBlock(), Scopes::vecscope_height, VECTORSCOPE, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
void uiTemplateWaveform (uiLayout * layout, struct PointerRNA * ptr, const char * propname)
Definition at line 1485 of file interface_templates.c.
References PointerRNA::data, MEM_callocN(), MEM_freeN(), RNAUpdateCb::prop, PROP_POINTER, RNAUpdateCb::ptr, RNA_property_pointer_get(), RNA_property_type(), RNA_Scopes, RNA_struct_find_property(), RNA_struct_is_a(), PointerRNA::type, UI_UNIT_Y, uiDefBut(), uiLayoutAbsoluteBlock(), WAVEFORM, Scopes::wavefrm_height, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
void uiTextBoundsBlock (uiBlock * block, int addval)
Definition at line 406 of file interface.c.
References uiBlock::bounds, uiBlock::dobounds, and UI_BLOCK_BOUNDS_TEXT.
Referenced by curvemap_brush_tools_func(), curvemap_tools_func(), and ui_block_func_POPUP().
void uiWidgetScrollDraw (struct uiWidgetColors * wcol, struct rcti * rect, struct rcti * slider, int state)
Definition at line 2266 of file interface_widgets.c.
References copy_v4_v4_char(), uiWidgetBase::emboss, uiWidgetColors::inner, uiWidgetColors::item, uiWidgetBase::outline, uiWidgetColors::outline, round_box_edges(), uiWidgetBase::shadedir, uiWidgetColors::shadedown, uiWidgetColors::shadetop, SWAP, uiWidgetBase::tria1, uiWidgetBase::tria2, UI_CNR_ALL, UI_SCROLL_ARROWS, UI_SCROLL_NO_OUTLINE, UI_SCROLL_PRESSED, widget_init(), widget_scroll_circle(), widgetbase_draw(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by draw_textscroll(), UI_view2d_scrollers_draw(), widget_progressbar(), and widget_scroll().
Variable Documentation
enum { ... } eBlockBoundsCalc