Blender: avi_intern.h File Reference
avi_intern.h File Reference
AVI
#include <stdio.h>
Defines
#define PUT_FCC(ch4, fp) putc(ch4[0],fp); putc(ch4[1],fp); putc(ch4[2],fp); putc(ch4[3],fp)
#define PUT_FCCN(num, fp) putc((num>>0)&0377,fp); putc((num>>8)&0377,fp); putc((num>>16)&0377,fp); putc((num>>24)&0377,fp)
#define PUT_TCC(ch2, fp) putc(ch2[0],fp); putc(ch2[1],fp)
Functions
unsigned int GET_FCC (FILE *fp)
unsigned int GET_TCC (FILE *fp)
void * avi_format_convert (AviMovie *movie, int stream, void *buffer, AviFormat from, AviFormat to, int *size)
int avi_get_data_id (AviFormat format, int stream)
int avi_get_format_type (AviFormat format)
int avi_get_format_fcc (AviFormat format)
int avi_get_format_compression (AviFormat format)
Detailed Description
Definition in file avi_intern.h.
Define Documentation
#define PUT_FCC (ch4, fp) putc(ch4[0],fp); putc(ch4[1],fp); putc(ch4[2],fp); putc(ch4[3],fp)
Definition at line 40 of file avi_intern.h.
Referenced by AVI_close_compress().
#define PUT_FCCN (num, fp) putc((num>>0)&0377,fp); putc((num>>8)&0377,fp); putc((num>>16)&0377,fp); putc((num>>24)&0377,fp)
Definition at line 41 of file avi_intern.h.
Referenced by AVI_close_compress(), AVI_open_compress(), and AVI_write_frame().
#define PUT_TCC (ch2, fp) putc(ch2[0],fp); putc(ch2[1],fp)
Definition at line 42 of file avi_intern.h.
Function Documentation
void* avi_format_convert (AviMovie * movie, int stream, void * buffer, AviFormat from, AviFormat to, int * size)
Definition at line 43 of file codecs.c.
References avi_converter_from_avi_rgb(), avi_converter_from_mjpeg(), avi_converter_from_rgb32(), avi_converter_to_avi_rgb(), avi_converter_to_mjpeg(), avi_converter_to_rgb32(), AVI_FORMAT_AVI_RGB, avi_format_convert(), AVI_FORMAT_MJPEG, AVI_FORMAT_RGB24, and AVI_FORMAT_RGB32.
Referenced by avi_format_convert(), AVI_read_frame(), and AVI_write_frame().
int avi_get_data_id (AviFormat format, int stream)
Definition at line 86 of file codecs.c.
References avi_get_format_type(), and FCC.
Referenced by AVI_write_frame().
int avi_get_format_compression (AviFormat format)
Definition at line 132 of file codecs.c.
References AVI_FORMAT_AVI_RGB, AVI_FORMAT_MJPEG, AVI_FORMAT_RGB24, AVI_FORMAT_RGB32, and FCC.
Referenced by AVI_open_compress().
int avi_get_format_fcc (AviFormat format)
Definition at line 115 of file codecs.c.
References AVI_FORMAT_AVI_RGB, AVI_FORMAT_MJPEG, AVI_FORMAT_RGB24, AVI_FORMAT_RGB32, and FCC.
Referenced by AVI_open_compress().
int avi_get_format_type (AviFormat format)
Definition at line 100 of file codecs.c.
References AVI_FORMAT_AVI_RGB, AVI_FORMAT_MJPEG, AVI_FORMAT_RGB24, AVI_FORMAT_RGB32, and FCC.
Referenced by avi_get_data_id(), AVI_open_compress(), and AVI_set_compress_option().
unsigned int GET_FCC (FILE * fp)
Definition at line 68 of file avi.c.
References FCC.
Referenced by AVI_is_avi(), AVI_open_movie(), and AVI_read_frame().
unsigned int GET_TCC (FILE * fp)
Definition at line 80 of file avi.c.
References FCC.
Referenced by AVI_is_avi(), and AVI_open_movie().