Blender: IK_QTranslateSegment Class Reference
IK_QTranslateSegment Class Reference
#include <IK_QSegment.h>
Public Member Functions
IK_QTranslateSegment (int axis1)
IK_QTranslateSegment (int axis1, int axis2)
IK_QTranslateSegment ()
MT_Vector3 Axis (int dof) const
bool UpdateAngle (const IK_QJacobian &jacobian, MT_Vector3 &delta, bool *clamp)
void Lock (int, IK_QJacobian &, MT_Vector3 &)
void UpdateAngleApply ()
void SetWeight (int axis, MT_Scalar weight)
void SetLimit (int axis, MT_Scalar lmin, MT_Scalar lmax)
void Scale (float scale)
Detailed Description
Definition at line 324 of file IK_QSegment.h.
Constructor & Destructor Documentation
IK_QTranslateSegment::IK_QTranslateSegment (int axis1)
Definition at line 929 of file IK_QSegment.cpp.
IK_QTranslateSegment::IK_QTranslateSegment (int axis1, int axis2)
Definition at line 940 of file IK_QSegment.cpp.
IK_QTranslateSegment::IK_QTranslateSegment ()
Definition at line 953 of file IK_QSegment.cpp.
Member Function Documentation
MT_Vector3 IK_QTranslateSegment::Axis (int dof) const [virtual]
Implements IK_QSegment.
Definition at line 965 of file IK_QSegment.cpp.
References MT_Transform::getBasis(), MT_Matrix3x3::getColumn(), and IK_QSegment::m_global_transform.
void IK_QTranslateSegment::Lock (int dof, IK_QJacobian & jacobian, MT_Vector3 & delta) [virtual]
Reimplemented from IK_QSegment.
Definition at line 1013 of file IK_QSegment.cpp.
References IK_QJacobian::Lock(), IK_QSegment::m_DoF_id, and IK_QSegment::m_locked.
void IK_QTranslateSegment::Scale (float scale) [virtual]
Reimplemented from IK_QSegment.
Definition at line 1038 of file IK_QSegment.cpp.
References i.
void IK_QTranslateSegment::SetLimit (int axis, MT_Scalar lmin, MT_Scalar lmax) [virtual]
Reimplemented from IK_QSegment.
Definition at line 1028 of file IK_QSegment.cpp.
void IK_QTranslateSegment::SetWeight (int axis, MT_Scalar weight) [virtual]
Reimplemented from IK_QSegment.
Definition at line 1019 of file IK_QSegment.cpp.
References i, IK_QSegment::m_num_DoF, and IK_QSegment::m_weight.
bool IK_QTranslateSegment::UpdateAngle (const IK_QJacobian & jacobian, MT_Vector3 & delta, bool * clamp) [virtual]
Implements IK_QSegment.
Definition at line 970 of file IK_QSegment.cpp.
References IK_QJacobian::AngleUpdate(), i, IK_QSegment::m_DoF_id, IK_QSegment::m_locked, and IK_QSegment::m_translation.
void IK_QTranslateSegment::UpdateAngleApply () [virtual]
Implements IK_QSegment.
Definition at line 1008 of file IK_QSegment.cpp.
References IK_QSegment::m_translation.
The documentation for this class was generated from the following files:
IK_QSegment.h
IK_QSegment.cpp