Blender: ScrollBar.c File Reference
ScrollBar.c File Reference
#include <stdlib.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "Basic.h"
#include "ScrollBar.h"
Classes
struct _ScrollBar
Functions
static int scrollbar_get_thumbH (ScrollBar *sb)
static int scrollbar_get_thumbableH (ScrollBar *sb)
static float scrollbar_co_to_pos (ScrollBar *sb, int yco)
ScrollBar * scrollbar_new (int inset, int minthumb)
void scrollbar_get_thumb (ScrollBar *sb, int thumb_r[2][2])
int scrollbar_is_scrolling (ScrollBar *sb)
int scrollbar_contains_pt (ScrollBar *sb, int pt[2])
void scrollbar_start_scrolling (ScrollBar *sb, int yco)
void scrollbar_keep_scrolling (ScrollBar *sb, int yco)
void scrollbar_stop_scrolling (ScrollBar *sb)
void scrollbar_set_thumbpct (ScrollBar *sb, float pct)
void scrollbar_set_thumbpos (ScrollBar *sb, float pos)
void scrollbar_set_rect (ScrollBar *sb, int rect[2][2])
float scrollbar_get_thumbpct (ScrollBar *sb)
float scrollbar_get_thumbpos (ScrollBar *sb)
void scrollbar_get_rect (ScrollBar *sb, int rect_r[2][2])
void scrollbar_free (ScrollBar *sb)
Function Documentation
static float scrollbar_co_to_pos (ScrollBar * sb, int yco) [static]
Definition at line 60 of file ScrollBar.c.
References _ScrollBar::inset, _ScrollBar::rect, scrollbar_get_thumbableH(), and scrollbar_get_thumbH().
Referenced by scrollbar_keep_scrolling(), and scrollbar_start_scrolling().
int scrollbar_contains_pt (ScrollBar * sb, int pt[2])
Definition at line 92 of file ScrollBar.c.
References _ScrollBar::rect, and rect_contains_pt().
Referenced by loggerwindow_do_button().
void scrollbar_free (ScrollBar * sb)
Definition at line 139 of file ScrollBar.c.
References MEM_freeN().
void scrollbar_get_rect (ScrollBar * sb, int rect_r[2][2])
Definition at line 135 of file ScrollBar.c.
References _ScrollBar::rect, and rect_copy().
Referenced by loggerwindow_do_draw().
void scrollbar_get_thumb (ScrollBar * sb, int thumb_r[2][2])
Definition at line 78 of file ScrollBar.c.
References _ScrollBar::inset, _ScrollBar::rect, scrollbar_get_thumbableH(), scrollbar_get_thumbH(), and _ScrollBar::thumbpos.
Referenced by loggerwindow_do_draw().
static int scrollbar_get_thumbableH (ScrollBar * sb) [static]
Definition at line 53 of file ScrollBar.c.
References _ScrollBar::inset, _ScrollBar::rect, rect_height(), and scrollbar_get_thumbH().
Referenced by scrollbar_co_to_pos(), scrollbar_get_thumb(), and scrollbar_start_scrolling().
static int scrollbar_get_thumbH (ScrollBar * sb) [static]
Definition at line 48 of file ScrollBar.c.
References clamp_i(), _ScrollBar::inset, _ScrollBar::minthumb, _ScrollBar::rect, rect_height(), and _ScrollBar::thumbpct.
Referenced by scrollbar_co_to_pos(), scrollbar_get_thumb(), scrollbar_get_thumbableH(), and scrollbar_start_scrolling().
float scrollbar_get_thumbpct (ScrollBar * sb)
Definition at line 129 of file ScrollBar.c.
References _ScrollBar::thumbpct.
float scrollbar_get_thumbpos (ScrollBar * sb)
Definition at line 132 of file ScrollBar.c.
References _ScrollBar::thumbpos.
Referenced by loggerwindow_do_draw().
int scrollbar_is_scrolling (ScrollBar * sb)
Definition at line 89 of file ScrollBar.c.
References _ScrollBar::scrolling.
Referenced by loggerwindow_do_button(), loggerwindow_do_draw(), and loggerwindow_do_move().
void scrollbar_keep_scrolling (ScrollBar * sb, int yco)
Definition at line 109 of file ScrollBar.c.
References clamp_f(), scrollbar_co_to_pos(), _ScrollBar::scrolloffs, and _ScrollBar::thumbpos.
Referenced by loggerwindow_do_move().
ScrollBar* scrollbar_new (int inset, int minthumb)
Definition at line 70 of file ScrollBar.c.
References _ScrollBar::inset, MEM_callocN(), and _ScrollBar::minthumb.
Referenced by loggerwindow_new().
void scrollbar_set_rect (ScrollBar * sb, int rect[2][2])
Definition at line 125 of file ScrollBar.c.
References _ScrollBar::rect, and rect_copy().
Referenced by loggerwindow_recalc_regions().
void scrollbar_set_thumbpct (ScrollBar * sb, float pct)
Definition at line 119 of file ScrollBar.c.
References _ScrollBar::thumbpct.
Referenced by loggerwindow_log(), and loggerwindow_recalc_regions().
void scrollbar_set_thumbpos (ScrollBar * sb, float pos)
Definition at line 122 of file ScrollBar.c.
References clamp_f(), and _ScrollBar::thumbpos.
void scrollbar_start_scrolling (ScrollBar * sb, int yco)
Definition at line 96 of file ScrollBar.c.
References clamp_f(), fabs(), scrollbar_co_to_pos(), scrollbar_get_thumbableH(), scrollbar_get_thumbH(), _ScrollBar::scrolling, _ScrollBar::scrolloffs, and _ScrollBar::thumbpos.
Referenced by loggerwindow_do_button().
void scrollbar_stop_scrolling (ScrollBar * sb)
Definition at line 114 of file ScrollBar.c.
References _ScrollBar::scrolling, and _ScrollBar::scrolloffs.
Referenced by loggerwindow_do_button().