Blender: KDL::Wrench Class Reference
KDL::Wrench Class Reference
represents both translational and rotational acceleration.
#include <frames.hpp>
Public Member Functions
Wrench ()
Does initialise force and torque to zero via the underlying constructor of Vector.
Wrench (const Vector &_force, const Vector &_torque)
Wrench & operator-= (const Wrench &arg)
Wrench & operator+= (const Wrench &arg)
double & operator() (int i)
index-based access to components, first force(0..2), then torque(3..5)
double operator() (int i) const
double operator[] (int index) const
double & operator[] (int index)
void ReverseSign ()
Reverses the sign of the current Wrench.
Wrench RefPoint (const Vector &v_base_AB) const
Static Public Member Functions
static Wrench Zero ()
Public Attributes
Vector force
Force that is applied at the origin of the current ref frame.
Vector torque
Torque that is applied at the origin of the current ref frame.
Friends
class Rotation
class Frame
Wrench operator* (const Wrench &lhs, double rhs)
Scalar multiplication.
Wrench operator* (double lhs, const Wrench &rhs)
Scalar multiplication.
Wrench operator/ (const Wrench &lhs, double rhs)
Scalar division.
Wrench operator+ (const Wrench &lhs, const Wrench &rhs)
Wrench operator- (const Wrench &lhs, const Wrench &rhs)
Wrench operator- (const Wrench &arg)
An unary - operator.
void SetToZero (Wrench &v)
bool Equal (const Wrench &a, const Wrench &b, double eps=epsilon)
bool operator== (const Wrench &a, const Wrench &b)
The literal equality operator==(), also identical.
bool operator!= (const Wrench &a, const Wrench &b)
The literal inequality operator!=().
Detailed Description
represents both translational and rotational acceleration.
This class represents an acceleration twist. A acceleration twist is the combination of translational acceleration and rotational acceleration applied at one point. represents the combination of a force and a torque.
This class represents a Wrench. A Wrench is the force and torque applied at a point
Definition at line 832 of file frames.hpp.
Constructor & Destructor Documentation
KDL::Wrench::Wrench () [inline]
Does initialise force and torque to zero via the underlying constructor of Vector.
Definition at line 840 of file frames.hpp.
KDL::Wrench::Wrench (const Vector & _force, const Vector & _torque) [inline]
Definition at line 841 of file frames.hpp.
Member Function Documentation
double & Wrench::operator() (int i) [inline]
index-based access to components, first force(0..2), then torque(3..5)
Definition at line 235 of file frames.inl.
Referenced by operator[]().
double KDL::Wrench::operator() (int i) const [inline]
index-based access to components, first force(0..2), then torque(3..5) for use with a const Wrench
Wrench& KDL::Wrench::operator+= (const Wrench & arg) [inline]
Wrench& KDL::Wrench::operator-= (const Wrench & arg) [inline]
double KDL::Wrench::operator[] (int index) const [inline]
Definition at line 854 of file frames.hpp.
References operator()().
double& KDL::Wrench::operator[] (int index) [inline]
Definition at line 859 of file frames.hpp.
References operator()().
Wrench KDL::Wrench::RefPoint (const Vector & v_base_AB) const [inline]
Changes the reference point of the wrench. The vector v_base_AB is expressed in the same base as the twist The vector v_base_AB is a vector from the old point to the new point.
Complexity : 6M+6A
void KDL::Wrench::ReverseSign () [inline]
Reverses the sign of the current Wrench.
static Wrench KDL::Wrench::Zero () [inline, static]
Returns:
a zero Wrench
Friends And Related Function Documentation
bool Equal (const Wrench & a, const Wrench & b, double eps = epsilon) [friend]
do not use operator == because the definition of Equal(.,.) is slightly different. It compares whether the 2 arguments are equal in an eps-interval
friend class Frame [friend]
Definition at line 906 of file frames.hpp.
bool operator!= (const Wrench & a, const Wrench & b) [friend]
The literal inequality operator!=().
Wrench operator* (double lhs, const Wrench & rhs) [friend]
Scalar multiplication.
Wrench operator* (const Wrench & lhs, double rhs) [friend]
Scalar multiplication.
Wrench operator+ (const Wrench & lhs, const Wrench & rhs) [friend]
Wrench operator- (const Wrench & arg) [friend]
An unary - operator.
Wrench operator- (const Wrench & lhs, const Wrench & rhs) [friend]
Wrench operator/ (const Wrench & lhs, double rhs) [friend]
Scalar division.
bool operator== (const Wrench & a, const Wrench & b) [friend]
The literal equality operator==(), also identical.
friend class Rotation [friend]
Definition at line 905 of file frames.hpp.
void SetToZero (Wrench & v) [friend]
Sets the Wrench to Zero, to have a uniform function that sets an object or double to zero.
Member Data Documentation
Vector KDL::Wrench::force
Force that is applied at the origin of the current ref frame.
Definition at line 835 of file frames.hpp.
Referenced by KDL::operator<<(), and KDL::operator>>().
Vector KDL::Wrench::torque
Torque that is applied at the origin of the current ref frame.
Definition at line 836 of file frames.hpp.
Referenced by KDL::operator<<(), and KDL::operator>>().
The documentation for this class was generated from the following files:
frames.hpp
frames.inl