Blender: IK_QSegment.cpp File Reference
IK_QSegment.cpp File Reference
iksolver
#include "IK_QSegment.h"
#include <cmath>
Functions
static MT_Matrix3x3 RotationMatrix (MT_Scalar sine, MT_Scalar cosine, int axis)
static MT_Matrix3x3 RotationMatrix (MT_Scalar angle, int axis)
static MT_Scalar EulerAngleFromMatrix (const MT_Matrix3x3 &R, int axis)
static MT_Scalar safe_acos (MT_Scalar f)
static MT_Scalar ComputeTwist (const MT_Matrix3x3 &R)
static MT_Matrix3x3 ComputeTwistMatrix (MT_Scalar tau)
static void RemoveTwist (MT_Matrix3x3 &R)
static MT_Vector3 SphericalRangeParameters (const MT_Matrix3x3 &R)
static MT_Matrix3x3 ComputeSwingMatrix (MT_Scalar ax, MT_Scalar az)
static MT_Vector3 MatrixToAxisAngle (const MT_Matrix3x3 &R)
static bool EllipseClamp (MT_Scalar &ax, MT_Scalar &az, MT_Scalar *amin, MT_Scalar *amax)
Detailed Description
Definition in file IK_QSegment.cpp.
Function Documentation
static MT_Matrix3x3 ComputeSwingMatrix (MT_Scalar ax, MT_Scalar az) [static]
Definition at line 136 of file IK_QSegment.cpp.
References sqrt().
Referenced by IK_QSwingSegment::UpdateAngle(), and IK_QSphericalSegment::UpdateAngle().
static MT_Scalar ComputeTwist (const MT_Matrix3x3 & R) [static]
Definition at line 86 of file IK_QSegment.cpp.
References KDL::atan2().
Referenced by RemoveTwist(), IK_QElbowSegment::SetBasis(), IK_QRevoluteSegment::SetBasis(), and SphericalRangeParameters().
static MT_Matrix3x3 ComputeTwistMatrix (MT_Scalar tau) [static]
Definition at line 97 of file IK_QSegment.cpp.
References RotationMatrix().
Referenced by RemoveTwist(), IK_QElbowSegment::SetBasis(), IK_QRevoluteSegment::SetBasis(), and IK_QSphericalSegment::UpdateAngle().
static bool EllipseClamp (MT_Scalar & ax, MT_Scalar & az, MT_Scalar * amin, MT_Scalar * amax) [static]
Definition at line 163 of file IK_QSegment.cpp.
References MT_fuzzyZero(), and sqrt().
Referenced by IK_QSwingSegment::UpdateAngle(), and IK_QSphericalSegment::UpdateAngle().
static MT_Scalar EulerAngleFromMatrix (const MT_Matrix3x3 & R, int axis) [static]
Definition at line 61 of file IK_QSegment.cpp.
References KDL::atan2(), MT_EPSILON(), and sqrt().
Referenced by IK_QElbowSegment::SetBasis(), and IK_QRevoluteSegment::SetBasis().
static MT_Vector3 MatrixToAxisAngle (const MT_Matrix3x3 & R) [static]
Definition at line 148 of file IK_QSegment.cpp.
References MT_Vector3::length(), MT_fuzzyZero(), and safe_acos().
Referenced by IK_QSwingSegment::UpdateAngle(), and IK_QSphericalSegment::UpdateAngle().
static void RemoveTwist (MT_Matrix3x3 & R) [static]
Definition at line 102 of file IK_QSegment.cpp.
References ComputeTwist(), ComputeTwistMatrix(), T, and MT_Matrix3x3::transposed().
Referenced by IK_QElbowSegment::SetBasis(), IK_QSwingSegment::SetBasis(), and IK_QSwingSegment::UpdateAngle().
static MT_Matrix3x3 RotationMatrix (MT_Scalar angle, int axis) [static]
Definition at line 55 of file IK_QSegment.cpp.
References cos(), RotationMatrix(), and sin().
static MT_Matrix3x3 RotationMatrix (MT_Scalar sine, MT_Scalar cosine, int axis) [static]
Definition at line 39 of file IK_QSegment.cpp.
Referenced by ComputeTwistMatrix(), RotationMatrix(), IK_QElbowSegment::SetBasis(), IK_QRevoluteSegment::SetBasis(), IK_QElbowSegment::UpdateAngleApply(), and IK_QRevoluteSegment::UpdateAngleApply().
static MT_Scalar safe_acos (MT_Scalar f) [static]
Definition at line 76 of file IK_QSegment.cpp.
References acos(), and MT_PI().
Referenced by MatrixToAxisAngle().
static MT_Vector3 SphericalRangeParameters (const MT_Matrix3x3 & R) [static]
Definition at line 114 of file IK_QSegment.cpp.
References ComputeTwist(), MT_abs(), MT_EPSILON(), and sqrt().
Referenced by IK_QSwingSegment::UpdateAngle(), and IK_QSphericalSegment::UpdateAngle().