Blender: kernel_camera.h File Reference
kernel_camera.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device float2 camera_sample_aperture (KernelGlobals *kg, float u, float v)
__device void camera_sample_perspective (KernelGlobals *kg, float raster_x, float raster_y, float lens_u, float lens_v, Ray *ray)
__device void camera_sample_orthographic (KernelGlobals *kg, float raster_x, float raster_y, Ray *ray)
__device void camera_sample_environment (KernelGlobals *kg, float raster_x, float raster_y, Ray *ray)
__device void camera_sample (KernelGlobals *kg, int x, int y, float filter_u, float filter_v, float lens_u, float lens_v, Ray *ray)
Function Documentation
__device void camera_sample (KernelGlobals * kg, int x, int y, float filter_u, float filter_v, float lens_u, float lens_v, Ray * ray)
Definition at line 165 of file kernel_camera.h.
References CAMERA_ORTHOGRAPHIC, CAMERA_PERSPECTIVE, camera_sample_environment(), camera_sample_orthographic(), camera_sample_perspective(), FILTER_TABLE_SIZE, kernel_data, and kernel_tex_interp.
Referenced by kernel_path_trace().
CCL_NAMESPACE_BEGIN __device float2 camera_sample_aperture (KernelGlobals * kg, float u, float v)
Definition at line 23 of file kernel_camera.h.
References concentric_sample_disk(), kernel_data, and regular_polygon_sample().
Referenced by camera_sample_perspective().
__device void camera_sample_environment (KernelGlobals * kg, float raster_x, float raster_y, Ray * ray)
Definition at line 127 of file kernel_camera.h.
References Ray::D, Ray::dD, Ray::dP, differential3::dx, differential3::dy, equirectangular_to_direction(), FLT_MAX, kernel_data, make_float3(), normalize(), Ray::P, Ray::t, transform_direction(), transform_perspective(), transform_point(), float3::x, and float3::y.
Referenced by camera_sample().
__device void camera_sample_orthographic (KernelGlobals * kg, float raster_x, float raster_y, Ray * ray)
Definition at line 92 of file kernel_camera.h.
References Ray::D, Ray::dD, Ray::dP, differential3::dx, differential3::dy, float4_to_float3(), FLT_MAX, kernel_data, make_float3(), normalize(), Ray::P, Ray::t, transform_direction(), transform_perspective(), and transform_point().
Referenced by camera_sample().
__device void camera_sample_perspective (KernelGlobals * kg, float raster_x, float raster_y, float lens_u, float lens_v, Ray * ray)
Definition at line 38 of file kernel_camera.h.
References camera_sample_aperture(), Ray::D, Ray::dD, Ray::dP, differential3::dx, differential3::dy, float4_to_float3(), FLT_MAX, kernel_data, make_float3(), normalize(), Ray::P, Ray::t, transform_direction(), transform_perspective(), transform_point(), float2::x, float2::y, and float3::z.
Referenced by camera_sample().