Blender: QBVH Class Reference
QBVH Class Reference
#include <bvh.h>
Protected Member Functions
QBVH (const BVHParams &params, const vector< Object * > &objects)
void pack_nodes (const array< int > &prims, const BVHNode *root)
void pack_leaf (const BVHStackEntry &e, const LeafNode *leaf)
void pack_inner (const BVHStackEntry &e, const BVHStackEntry *en, int num)
void refit_nodes ()
Friends
class BVH
Detailed Description
Definition at line 141 of file intern/cycles/bvh/bvh.h.
Constructor & Destructor Documentation
QBVH::QBVH (const BVHParams & params, const vector< Object * > & objects) [protected]
Definition at line 591 of file bvh.cpp.
References BVH::params, and BVHParams::use_qbvh.
Member Function Documentation
void QBVH::pack_inner (const BVHStackEntry & e, const BVHStackEntry * en, int num) [protected]
Definition at line 619 of file bvh.cpp.
References __int_as_float(), BVH_QNODE_SIZE, data, i, BVHStackEntry::idx, BVHNode::m_bounds, BoundBox::max, BoundBox::min, BVHStackEntry::node, PackedBVH::nodes, BVH::pack, float3::x, float3::y, and float3::z.
Referenced by pack_nodes().
void QBVH::pack_leaf (const BVHStackEntry & e, const LeafNode * leaf) [protected]
Definition at line 599 of file bvh.cpp.
References __int_as_float(), BVH_QNODE_SIZE, data, BVHStackEntry::idx, LeafNode::m_hi, LeafNode::m_lo, PackedBVH::nodes, LeafNode::num_triangles(), BVH::pack, PackedBVH::prim_index, float4::x, and float4::y.
Referenced by pack_nodes().
void QBVH::pack_nodes (const array< int > & prims, const BVHNode * root) [protected, virtual]
Implements BVH.
Definition at line 656 of file bvh.cpp.
References BVH_QNODE_SIZE, BVH_STAT_NODE_COUNT, array< T >::clear(), BVHNode::get_child(), BVHNode::getSubtreeSize(), i, BVHStackEntry::idx, PackedBVH::is_leaf, BVHNode::is_leaf(), BVHStackEntry::node, nodes, PackedBVH::nodes, BVH::pack, pack_inner(), BVH::pack_instances(), pack_leaf(), BVH::params, array< T >::resize(), PackedBVH::root_index, stack, and BVHParams::top_level.
void QBVH::refit_nodes () [protected, virtual]
Implements BVH.
Definition at line 726 of file bvh.cpp.
References assert.
Friends And Related Function Documentation
friend class BVH [friend]
Definition at line 144 of file intern/cycles/bvh/bvh.h.
The documentation for this class was generated from the following files:
intern/cycles/bvh/bvh.h
bvh.cpp