Blender: CTR_Link Class Reference
CTR_Link Class Reference
#include <CTR_List.h>
Public Member Functions
CTR_Link ()
CTR_Link (CTR_Link *next, CTR_Link *prev)
CTR_Link * getNext () const
CTR_Link * getPrev () const
bool isHead () const
bool isTail () const
void insertBefore (CTR_Link *link)
void insertAfter (CTR_Link *link)
void remove ()
Detailed Description
Definition at line 37 of file CTR_List.h.
Constructor & Destructor Documentation
CTR_Link::CTR_Link ()
Definition at line 37 of file CTR_List.cpp.
CTR_Link::CTR_Link (CTR_Link * next, CTR_Link * prev)
Definition at line 45 of file CTR_List.cpp.
Member Function Documentation
CTR_Link * CTR_Link::getNext () const
Definition at line 56 of file CTR_List.cpp.
Referenced by CTR_List::getHead().
CTR_Link * CTR_Link::getPrev () const
Definition at line 63 of file CTR_List.cpp.
Referenced by CTR_List::getTail().
void CTR_Link::insertAfter (CTR_Link * link)
Definition at line 95 of file CTR_List.cpp.
References link().
Referenced by CTR_List::addHead().
void CTR_Link::insertBefore (CTR_Link * link)
Definition at line 84 of file CTR_List.cpp.
References link().
Referenced by CTR_List::addTail().
bool CTR_Link::isHead () const
Definition at line 70 of file CTR_List.cpp.
bool CTR_Link::isTail () const
Definition at line 77 of file CTR_List.cpp.
void CTR_Link::remove ()
Definition at line 106 of file CTR_List.cpp.
The documentation for this class was generated from the following files:
CTR_List.h
CTR_List.cpp