Blender: wm.h File Reference
wm.h File Reference
windowmanager
Classes
struct wmPaintCursor
Defines
#define WM_LASSO_MIN_POINTS 1024
#define GESTURE_MEMORY
Typedefs
typedef struct wmPaintCursor wmPaintCursor
Functions
void wm_close_and_free (bContext *C, wmWindowManager *)
void wm_close_and_free_all (bContext *C, ListBase *)
void wm_add_default (bContext *C)
void wm_clear_default_size (bContext *C)
void wm_operator_register (bContext *C, wmOperator *op)
void wm_operatortype_free (void)
void wm_operatortype_init (void)
void wm_window_keymap (wmKeyConfig *keyconf)
void wm_tweakevent_test (bContext *C, wmEvent *event, int action)
void wm_gesture_draw (struct wmWindow *win)
int wm_gesture_evaluate (wmGesture *gesture)
void wm_gesture_tag_redraw (bContext *C)
void wm_jobs_timer (const bContext *C, wmWindowManager *wm, wmTimer *wt)
void wm_jobs_timer_ended (wmWindowManager *wm, wmTimer *wt)
void wm_autosave_timer (const bContext *C, wmWindowManager *wm, wmTimer *wt)
void wm_autosave_timer_ended (wmWindowManager *wm)
void wm_autosave_delete (void)
void wm_autosave_read (bContext *C, struct ReportList *reports)
void wm_autosave_location (char *filepath)
Variables
int circle_select_size
Detailed Description
Definition in file wm.h.
Define Documentation
#define GESTURE_MEMORY
Definition at line 80 of file wm.h.
#define WM_LASSO_MIN_POINTS 1024
Definition at line 63 of file wm.h.
Referenced by WM_gesture_lasso_modal(), and WM_gesture_new().
Typedef Documentation
typedef struct wmPaintCursor wmPaintCursor
Function Documentation
void wm_add_default (bContext * C)
Definition at line 292 of file wm.c.
References alloc_libblock(), BLI_strncpy(), CTX_data_main(), CTX_wm_manager_set(), CTX_wm_screen(), wmWindowManager::file_saved, bScreen::id, ID_WM, ID::name, wmWindow::screen, wmWindow::screenname, wmWindowManager::winactive, wmWindow::winid, bScreen::winid, wm_window_make_drawable(), and wm_window_new().
Referenced by load_file(), and wm_window_match_do().
void wm_autosave_delete (void)
Definition at line 963 of file wm_files.c.
References BLI_delete(), BLI_exists(), BLI_make_file_string(), BLI_rename(), BLI_temporary_dir(), FILE_MAX, str, USER_GLOBALUNDO, and wm_autosave_location().
Referenced by WM_exit_ext().
void wm_autosave_location (char * filepath)
Definition at line 888 of file wm_files.c.
References abs(), BLENDER_USER_AUTOSAVE, BLI_exists(), BLI_get_folder_create(), BLI_make_file_string(), BLI_snprintf(), BLI_temporary_dir(), and NULL.
Referenced by wm_autosave_delete(), wm_autosave_read(), wm_autosave_timer(), and wm_recover_auto_save_invoke().
void wm_autosave_read (bContext * C, struct ReportList * reports)
Definition at line 979 of file wm_files.c.
References FILE_MAX, wm_autosave_location(), and WM_read_file().
void wm_autosave_timer (const bContext * C, wmWindowManager * wm, wmTimer * wt)
void wm_autosave_timer_ended (wmWindowManager * wm)
Definition at line 955 of file wm_files.c.
References wmWindowManager::autosavetimer, NULL, and WM_event_remove_timer().
Referenced by WM_autosave_init(), and wm_close_and_free().
void wm_clear_default_size (bContext * C)
Definition at line 269 of file wm.c.
References CTX_data_main(), CTX_wm_manager(), CTX_wm_manager_set(), ListBase::first, wmWindow::next, NULL, wmWindow::posx, wmWindow::posy, wmWindow::sizex, wmWindow::sizey, wmWindowManager::windows, and Main::wm.
Referenced by WM_read_homefile().
void wm_close_and_free (bContext * C, wmWindowManager *)
Definition at line 311 of file wm.c.
References wmWindowManager::autosavetimer, BLI_freelistN(), BLI_remlink(), CTX_wm_manager(), CTX_wm_manager_set(), wmWindowManager::drags, ListBase::first, wmWindowManager::keyconfigs, NULL, wmWindowManager::operators, wmWindowManager::paintcursors, wmWindowManager::queue, wmWindow::screen, wmWindowManager::windows, wm_autosave_timer_ended(), wm_draw_window_clear(), WM_keyconfig_free(), WM_operator_free(), wm_reports_free(), and wm_window_free().
Referenced by wm_close_and_free_all(), and WM_init().
void wm_close_and_free_all (bContext * C, ListBase *)
Definition at line 347 of file wm.c.
References BLI_remlink(), ListBase::first, MEM_freeN(), and wm_close_and_free().
Referenced by wm_window_match_do().
void wm_gesture_draw (struct wmWindow * win)
Definition at line 324 of file wm_gesture.c.
References ListBase::first, wmWindow::gesture, wmGesture::mode, wmGesture::next, wmGesture::swinid, wmGesture::type, WM_GESTURE_CIRCLE, WM_GESTURE_CROSS_RECT, wm_gesture_draw_circle(), wm_gesture_draw_cross(), wm_gesture_draw_lasso(), wm_gesture_draw_line(), wm_gesture_draw_rect(), WM_GESTURE_LASSO, WM_GESTURE_LINES, WM_GESTURE_RECT, WM_GESTURE_STRAIGHTLINE, and wmSubWindowSet().
Referenced by wm_method_draw_full(), wm_method_draw_overlap_all(), and wm_method_draw_triple().
int wm_gesture_evaluate (wmGesture * gesture)
Definition at line 129 of file wm_gesture.c.
References ABS, atan2f, wmGesture::customdata, EVT_GESTURE_E, EVT_GESTURE_N, EVT_GESTURE_NE, EVT_GESTURE_NW, EVT_GESTURE_S, EVT_GESTURE_SE, EVT_GESTURE_SW, EVT_GESTURE_W, M_PI, wmGesture::type, WM_GESTURE_TWEAK, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by tweak_gesture_modal().
void wm_gesture_tag_redraw (bContext * C)
Definition at line 353 of file wm_gesture.c.
References CTX_wm_region(), CTX_wm_screen(), CTX_wm_window(), bScreen::do_draw_gesture, and wm_tag_redraw_overlay().
Referenced by WM_border_select_invoke(), WM_border_select_modal(), WM_gesture_circle_invoke(), WM_gesture_circle_modal(), WM_gesture_lasso_invoke(), WM_gesture_lasso_modal(), WM_gesture_lines_invoke(), WM_gesture_straightline_invoke(), and WM_gesture_straightline_modal().
void wm_jobs_timer (const bContext * C, wmWindowManager * wm, wmTimer * wt)
Definition at line 428 of file wm_jobs.c.
References BLI_end_threads(), BLI_remlink(), wmJob::customdata, wmJob::do_update, wmJob::endjob, wmJob::endnote, ListBase::first, wmJob::flag, wmWindowManager::jobs, MEM_freeN(), NC_WM, ND_JOB, wmJob::next, wmJob::note, NULL, wmJob::progress, wmJob::ready, wmJob::run_customdata, wmJob::run_free, wmJob::running, wmJob::suspended, wmJob::threads, wmJob::update, wmJob::win, wmWindowManager::winactive, WM_event_add_notifier(), WM_event_remove_timer(), WM_JOB_PROGRESS, WM_jobs_start(), WM_progress_clear(), WM_progress_set(), and wmJob::wt.
Referenced by wm_window_timer().
void wm_jobs_timer_ended (wmWindowManager * wm, wmTimer * wt)
Definition at line 415 of file wm_jobs.c.
References ListBase::first, wmWindowManager::jobs, wmJob::next, wm_jobs_kill_job(), and wmJob::wt.
Referenced by wm_window_free().
void wm_operator_register (bContext * C, wmOperator * op)
Definition at line 119 of file wm.c.
References BLI_addtail(), BLI_countlist(), BLI_remlink(), CTX_wm_manager(), ListBase::first, MAX_OP_REGISTERED, NC_SPACE, NC_WM, ND_HISTORY, ND_SPACE_INFO_REPORT, NULL, wmWindowManager::operators, WM_event_add_notifier(), and WM_operator_free().
Referenced by wm_operator_finished(), and WM_operator_props_popup().
void wm_operatortype_free (void)
Definition at line 3670 of file wm_operators.c.
References BLI_ghash_free(), NULL, and operatortype_ghash_free_cb().
Referenced by WM_exit_ext().
void wm_operatortype_init (void)
Definition at line 3677 of file wm_operators.c.
References BLI_ghash_new(), BLI_ghashutil_strcmp(), BLI_ghashutil_strhash(), WM_operatortype_append(), WM_OT_call_menu(), WM_OT_debug_menu(), WM_OT_dependency_relations(), WM_OT_link_append(), WM_OT_memory_statistics(), WM_OT_ndof_sensitivity_change(), WM_OT_open_mainfile(), WM_OT_quit_blender(), WM_OT_radial_control(), WM_OT_read_factory_settings(), WM_OT_read_homefile(), WM_OT_recover_auto_save(), WM_OT_recover_last_session(), WM_OT_redraw_timer(), WM_OT_save_as_mainfile(), WM_OT_save_homefile(), WM_OT_save_mainfile(), WM_OT_search_menu(), WM_OT_splash(), WM_OT_window_duplicate(), and WM_OT_window_fullscreen_toggle().
Referenced by WM_init().
void wm_tweakevent_test (bContext * C, wmEvent * event, int action)
Definition at line 2618 of file wm_operators.c.
References CTX_wm_region(), CTX_wm_window(), ELEM3, KM_PRESS, LEFTMOUSE, MIDDLEMOUSE, NULL, RIGHTMOUSE, wmWindow::tweak, tweak_gesture_modal(), wmEvent::type, wmEvent::val, WM_gesture_end(), WM_gesture_new(), WM_GESTURE_TWEAK, and WM_HANDLER_BREAK.
Referenced by wm_event_do_handlers().
void wm_window_keymap (wmKeyConfig * keyconf)
Definition at line 3886 of file wm_operators.c.
References DKEY, F10KEY, F11KEY, F12KEY, F1KEY, F2KEY, F3KEY, F4KEY, F5KEY, F6KEY, F7KEY, F8KEY, F9KEY, FALSE, gesture_border_modal_keymap(), gesture_circle_modal_keymap(), gesture_straightline_modal_keymap(), gesture_zoom_border_modal_keymap(), KM_ALT, KM_CTRL, KM_OSKEY, KM_PRESS, KM_SHIFT, NDOF_BUTTON_MENU, NDOF_BUTTON_MINUS, NDOF_BUTTON_PLUS, NKEY, OKEY, wmKeyMapItem::ptr, QKEY, RNA_boolean_set(), RNA_string_set(), SKEY, SPACEKEY, TKEY, TRUE, UKEY, WKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), and WM_keymap_verify_item().
Referenced by WM_keymap_init().
Variable Documentation
int circle_select_size
Referenced by WM_gesture_new().