Blender: OcclusionBuffer Struct Reference
OcclusionBuffer Struct Reference
Classes
struct QueryOCL
struct WriteOCL
Public Member Functions
OcclusionBuffer ()
template<typename T1 , typename T2 >
void CMmat4mul (btScalar *m, const T1 *m1, const T2 *m2)
void setup (int size)
void initialize ()
void SetModelMatrix (double *fl)
void transformW (const btVector3 &x, btVector4 &t)
void transformM (const float *x, btVector4 &t)
template<typename POLICY >
bool draw (const btVector4 &a, const btVector4 &b, const btVector4 &c, const float face, const btScalar minarea)
template<const int NP, typename POLICY >
bool clipDraw (const btVector4 *p, const float face, btScalar minarea)
void appendOccluderM (const float *a, const float *b, const float *c, const float face)
void appendOccluderM (const float *a, const float *b, const float *c, const float *d, const float face)
bool queryOccluderW (const btVector3 &c, const btVector3 &e)
Static Public Member Functions
static bool project (btVector4 *p, int n)
template<const int NP>
static int clip (const btVector4 *pi, btVector4 *po)
Public Attributes
btScalar * m_buffer
size_t m_bufferSize
bool m_initialized
bool m_occlusion
int m_sizes [2]
btScalar m_scales [2]
btScalar m_offsets [2]
btScalar m_wtc [16]
btScalar m_mtc [16]
Detailed Description
Definition at line 1246 of file CcdPhysicsEnvironment.cpp.
Constructor & Destructor Documentation
OcclusionBuffer::OcclusionBuffer () [inline]
Definition at line 1269 of file CcdPhysicsEnvironment.cpp.
References m_buffer, m_bufferSize, m_initialized, m_occlusion, and NULL.
Member Function Documentation
void OcclusionBuffer::appendOccluderM (const float * a, const float * b, const float * c, const float face) [inline]
Definition at line 1647 of file CcdPhysicsEnvironment.cpp.
References p, and transformM().
void OcclusionBuffer::appendOccluderM (const float * a, const float * b, const float * c, const float * d, const float face) [inline]
Definition at line 1659 of file CcdPhysicsEnvironment.cpp.
References p, and transformM().
template<const int NP> static int OcclusionBuffer::clip (const btVector4 * pi, btVector4 * po) [inline, static]
Definition at line 1391 of file CcdPhysicsEnvironment.cpp.
References i.
template<const int NP, typename POLICY > bool OcclusionBuffer::clipDraw (const btVector4 * p, const float face, btScalar minarea) [inline]
Definition at line 1626 of file CcdPhysicsEnvironment.cpp.
References i, p, and project().
template<typename T1 , typename T2 > void OcclusionBuffer::CMmat4mul (btScalar * m, const T1 * m1, const T2 * m2) [inline]
Definition at line 1278 of file CcdPhysicsEnvironment.cpp.
Referenced by SetModelMatrix(), and setup().
template<typename POLICY > bool OcclusionBuffer::draw (const btVector4 & a, const btVector4 & b, const btVector4 & c, const float face, const btScalar minarea) [inline]
Definition at line 1461 of file CcdPhysicsEnvironment.cpp.
References btCross(), btFabs(), btMax(), btMin(), m_buffer, m_occlusion, m_offsets, m_scales, m_sizes, and mix().
void OcclusionBuffer::initialize () [inline]
Definition at line 1328 of file CcdPhysicsEnvironment.cpp.
References assert, m_buffer, m_bufferSize, m_initialized, m_occlusion, m_sizes, and NULL.
Referenced by SetModelMatrix().
static bool OcclusionBuffer::project (btVector4 * p, int n) [inline, static]
Definition at line 1378 of file CcdPhysicsEnvironment.cpp.
References i.
Referenced by clipDraw().
bool OcclusionBuffer::queryOccluderW (const btVector3 & c, const btVector3 & e) [inline]
Definition at line 1673 of file CcdPhysicsEnvironment.cpp.
References i, m_occlusion, p, and transformW().
void OcclusionBuffer::SetModelMatrix (double * fl) [inline]
Definition at line 1355 of file CcdPhysicsEnvironment.cpp.
References CMmat4mul(), initialize(), m_initialized, m_mtc, and m_wtc.
void OcclusionBuffer::setup (int size) [inline]
Definition at line 1300 of file CcdPhysicsEnvironment.cpp.
References assert, CMmat4mul(), m_initialized, m_occlusion, m_offsets, m_scales, m_sizes, m_wtc, and p.
Referenced by CcdPhysicsEnvironment::cullingTest().
void OcclusionBuffer::transformM (const float * x, btVector4 & t) [inline]
Definition at line 1370 of file CcdPhysicsEnvironment.cpp.
References m_mtc.
Referenced by appendOccluderM().
void OcclusionBuffer::transformW (const btVector3 & x, btVector4 & t) [inline]
Definition at line 1363 of file CcdPhysicsEnvironment.cpp.
References m_wtc.
Referenced by queryOccluderW().
Member Data Documentation
btScalar* OcclusionBuffer::m_buffer
Definition at line 1258 of file CcdPhysicsEnvironment.cpp.
Referenced by draw(), initialize(), and OcclusionBuffer().
size_t OcclusionBuffer::m_bufferSize
Definition at line 1259 of file CcdPhysicsEnvironment.cpp.
Referenced by initialize(), and OcclusionBuffer().
bool OcclusionBuffer::m_initialized
Definition at line 1260 of file CcdPhysicsEnvironment.cpp.
Referenced by initialize(), OcclusionBuffer(), SetModelMatrix(), and setup().
btScalar OcclusionBuffer::m_mtc[16]
Definition at line 1266 of file CcdPhysicsEnvironment.cpp.
Referenced by SetModelMatrix(), and transformM().
bool OcclusionBuffer::m_occlusion
Definition at line 1261 of file CcdPhysicsEnvironment.cpp.
Referenced by draw(), initialize(), OcclusionBuffer(), queryOccluderW(), and setup().
btScalar OcclusionBuffer::m_offsets[2]
Definition at line 1264 of file CcdPhysicsEnvironment.cpp.
Referenced by draw(), and setup().
btScalar OcclusionBuffer::m_scales[2]
Definition at line 1263 of file CcdPhysicsEnvironment.cpp.
Referenced by draw(), and setup().
int OcclusionBuffer::m_sizes[2]
Definition at line 1262 of file CcdPhysicsEnvironment.cpp.
Referenced by draw(), initialize(), and setup().
btScalar OcclusionBuffer::m_wtc[16]
Definition at line 1265 of file CcdPhysicsEnvironment.cpp.
Referenced by SetModelMatrix(), setup(), and transformW().
The documentation for this struct was generated from the following file:
CcdPhysicsEnvironment.cpp