Blender: drawmesh.c File Reference
drawmesh.c File Reference
3D view
#include <string.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_edgehash.h"
#include "DNA_material_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_node_types.h"
#include "DNA_object_types.h"
#include "DNA_property_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_view3d_types.h"
#include "DNA_windowmanager_types.h"
#include "BKE_DerivedMesh.h"
#include "BKE_effect.h"
#include "BKE_image.h"
#include "BKE_material.h"
#include "BKE_paint.h"
#include "BKE_property.h"
#include "BKE_tessmesh.h"
#include "BKE_scene.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "UI_resources.h"
#include "GPU_buffers.h"
#include "GPU_extensions.h"
#include "GPU_draw.h"
#include "GPU_material.h"
#include "ED_mesh.h"
#include "ED_uvedit.h"
#include "view3d_intern.h"
Classes
struct drawMeshFaceSelect_userData
struct drawEMTFMapped_userData
struct drawTFace_userData
struct TextureDrawState
struct TexMatCallback
Typedefs
typedef struct
drawMeshFaceSelect_userData drawMeshFaceSelect_userData
typedef struct
drawEMTFMapped_userData drawEMTFMapped_userData
typedef struct drawTFace_userData drawTFace_userData
typedef struct TexMatCallback TexMatCallback
Enumerations
enum { eEdge_Visible = (1 << 0), eEdge_Select = (1 << 1) }
Functions
static void get_marked_edge_info__orFlags (EdgeHash *eh, int v0, int v1, int flags)
static EdgeHash * get_tface_mesh_marked_edge_info (Mesh *me)
static DMDrawOption draw_mesh_face_select__setHiddenOpts (void *userData, int index)
static DMDrawOption draw_mesh_face_select__setSelectOpts (void *userData, int index)
static DMDrawOption draw_mesh_face_select__drawFaceOptsInv (void *userData, int index)
static void draw_mesh_face_select (RegionView3D *rv3d, Mesh *me, DerivedMesh *dm)
static Material * give_current_material_or_def (Object *ob, int matnr)
static int set_draw_settings_cached (int clearcache, MTFace *texface, Material *ma, struct TextureDrawState gtexdraw)
static void draw_textured_begin (Scene *scene, View3D *v3d, RegionView3D *rv3d, Object *ob)
static void draw_textured_end (void)
static DMDrawOption draw_tface__set_draw_legacy (MTFace *tface, int has_mcol, int matnr)
static DMDrawOption draw_mcol__set_draw_legacy (MTFace *UNUSED(tface), int has_mcol, int UNUSED(matnr))
static DMDrawOption draw_tface__set_draw (MTFace *tface, int has_mcol, int matnr)
static void add_tface_color_layer (DerivedMesh *dm)
static DMDrawOption draw_tface_mapped__set_draw (void *userData, int index)
static DMDrawOption draw_em_tf_mapped__set_draw (void *userData, int index)
static DMDrawOption wpaint__setSolidDrawOptions_material (void *userData, int index)
static DMDrawOption wpaint__setSolidDrawOptions_facemask (void *userData, int index)
static void draw_mesh_text (Scene *scene, Object *ob, int glsl)
static int compareDrawOptions (void *userData, int cur_index, int next_index)
static int compareDrawOptionsEm (void *userData, int cur_index, int next_index)
void draw_mesh_textured_old (Scene *scene, View3D *v3d, RegionView3D *rv3d, Object *ob, DerivedMesh *dm, int draw_flags)
static void tex_mat_set_material_cb (void *UNUSED(userData), int mat_nr, void *attribs)
static void tex_mat_set_texture_cb (void *userData, int mat_nr, void *attribs)
static int tex_mat_set_face_mesh_cb (void *userData, int index)
static int tex_mat_set_face_editmesh_cb (void *userData, int index)
void draw_mesh_textured (Scene *scene, View3D *v3d, RegionView3D *rv3d, Object *ob, DerivedMesh *dm, int draw_flags)
Variables
static struct TextureDrawState Gtexdraw
Detailed Description
Definition in file drawmesh.c.
Typedef Documentation
typedef struct drawEMTFMapped_userData drawEMTFMapped_userData
typedef struct drawMeshFaceSelect_userData drawMeshFaceSelect_userData
typedef struct drawTFace_userData drawTFace_userData
typedef struct TexMatCallback TexMatCallback
Enumeration Type Documentation
anonymous enum
Enumerator:
eEdge_Visible
eEdge_Select
Definition at line 98 of file drawmesh.c.
Function Documentation
static void add_tface_color_layer (DerivedMesh * dm) [static]
Definition at line 469 of file drawmesh.c.
References MCol::b, CD_ASSIGN, CD_MCOL, CD_MTFACE, CD_PREVIEW_MCOL, CD_TEXTURE_MCOL, TextureDrawState::color_profile, copy_v3_v3(), CustomData_add_layer(), DM_get_tessface_data_layer(), DerivedMesh::faceData, GameSettings::flag, FTOCHAR, MCol::g, Material::game, GEMAT_INVISIBLE, DerivedMesh::getNumTessFaces, DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceDataArray, give_current_material(), Gtexdraw, i, linearrgb_to_srgb_v3_v3(), MFace::mat_nr, MEM_mallocN(), MTFace::mode, DerivedMesh::numTessFaceData, TextureDrawState::ob, TextureDrawState::obcol, MCol::r, Material::r, set_draw_settings_cached(), and TF_OBCOL.
Referenced by draw_mesh_textured_old().
static int compareDrawOptions (void * userData, int cur_index, int next_index) [static]
Definition at line 747 of file drawmesh.c.
References data, MFace::mat_nr, drawTFace_userData::mf, drawTFace_userData::tf, and MTFace::tpage.
Referenced by cdDM_drawFacesTex_common(), cdDM_drawMappedFaces(), and draw_mesh_textured_old().
static int compareDrawOptionsEm (void * userData, int cur_index, int next_index) [static]
Definition at line 760 of file drawmesh.c.
References data, MFace::mat_nr, drawEMTFMapped_userData::mf, drawEMTFMapped_userData::tf, and MTFace::tpage.
Referenced by draw_mesh_textured_old().
static DMDrawOption draw_em_tf_mapped__set_draw (void * userData, int index) [static]
Definition at line 573 of file drawmesh.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, CD_MTEXPOLY, CustomData_bmesh_get(), data, BMHeader::data, DM_DRAW_OPTION_SKIP, draw_tface__set_draw_legacy(), EDBM_face_at_index(), drawEMTFMapped_userData::em, drawEMTFMapped_userData::has_mcol, drawEMTFMapped_userData::has_mtface, BMFace::head, BMFace::mat_nr, ME_MTEXFACE_CPY, NULL, and BMesh::pdata.
Referenced by draw_mesh_textured_old().
static DMDrawOption draw_mcol__set_draw_legacy (MTFace * UNUSEDtface, int has_mcol, int UNUSEDmatnr) [static]
Definition at line 441 of file drawmesh.c.
References DM_DRAW_OPTION_NO_MCOL, and DM_DRAW_OPTION_NORMAL.
Referenced by draw_mesh_textured_old().
static void draw_mesh_face_select (RegionView3D * rv3d, Mesh * me, DerivedMesh * dm) [static]
Definition at line 182 of file drawmesh.c.
References bglPolygonOffset(), BLI_edgehash_free(), data, RegionView3D::dist, draw_mesh_face_select__drawFaceOptsInv(), draw_mesh_face_select__setHiddenOpts(), draw_mesh_face_select__setSelectOpts(), Mesh::drawflag, DerivedMesh::drawMappedEdges, DerivedMesh::drawMappedFaces, drawMeshFaceSelect_userData::eh, get_tface_mesh_marked_edge_info(), drawMeshFaceSelect_userData::me, ME_DRAWFACES, NULL, setlinestyle(), TH_EDGE_FACESEL, and UI_ThemeColor().
Referenced by draw_mesh_textured(), and draw_mesh_textured_old().
static DMDrawOption draw_mesh_face_select__drawFaceOptsInv (void * userData, int index) [static]
Definition at line 171 of file drawmesh.c.
References DM_DRAW_OPTION_NO_MCOL, DM_DRAW_OPTION_SKIP, MPoly::flag, ME_FACE_SEL, ME_HIDE, and Mesh::mpoly.
Referenced by draw_mesh_face_select().
static DMDrawOption draw_mesh_face_select__setHiddenOpts (void * userData, int index) [static]
Definition at line 142 of file drawmesh.c.
References BLI_edgehash_lookup(), data, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, Mesh::drawflag, eEdge_Select, eEdge_Visible, drawMeshFaceSelect_userData::eh, drawMeshFaceSelect_userData::me, ME_DRAWEDGES, ME_HIDDENEDGES, Mesh::medge, MEdge::v1, and MEdge::v2.
Referenced by draw_mesh_face_select().
static DMDrawOption draw_mesh_face_select__setSelectOpts (void * userData, int index) [static]
Definition at line 161 of file drawmesh.c.
References BLI_edgehash_lookup(), data, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, eEdge_Select, drawMeshFaceSelect_userData::eh, drawMeshFaceSelect_userData::me, Mesh::medge, MEdge::v1, and MEdge::v2.
Referenced by draw_mesh_face_select().
static void draw_mesh_text (Scene * scene, Object * ob, int glsl) [static]
Definition at line 620 of file drawmesh.c.
References BKE_image_get_ibuf(), CD_MASK_BAREMESH, CD_MTFACE, copy_v2_v2(), Object::data, GameSettings::flag, MPoly::flag, Material::game, GEMAT_INVISIBLE, GEMAT_TEXT, get_ob_property(), DerivedMesh::getVertCo, GPUVertexAttribs::glindex, GPU_enable_material(), GPU_render_text(), Gtexdraw, i, GPUVertexAttribs::layer, MPoly::loopstart, Mesh::mat, MPoly::mat_nr, MAX_PROPSTRING, ME_MTEXFACE_CPY, ME_SMOOTH, mesh_get_derived_deform(), MESH_MLOOPCOL_TO_MCOL, MIN2, Mesh::mloop, Mesh::mloopcol, Mesh::mloopuv, Object::mode, Mesh::mpoly, Mesh::mtpoly, normal_tri_v3(), NULL, OB_MODE_EDIT, OBACT, paint_facesel_test(), paint_vertsel_test(), DerivedMesh::release, set_draw_settings_cached(), set_property_valstr(), strlen(), GPUVertexAttribs::totlayer, MPoly::totloop, Mesh::totpoly, GPUVertexAttribs::type, MTFace::uv, MLoopUV::uv, and MLoop::v.
Referenced by draw_mesh_textured_old().
void draw_mesh_textured (Scene * scene, View3D * v3d, RegionView3D * rv3d, Object * ob, DerivedMesh * dm, int draw_flags)
Definition at line 943 of file drawmesh.c.
References Object::data, data, DM_DRAW_ALWAYS_SMOOTH, DM_DRAW_USE_COLORS, DRAW_FACE_SELECT, draw_mesh_face_select(), draw_mesh_textured_old(), DRAW_MODIFIERS_PREVIEW, DerivedMesh::drawMappedFaces, DerivedMesh::drawMappedFacesMat, View3D::drawtype, GPU_begin_object_materials(), GPU_enable_material(), GPU_end_object_materials(), GPU_glsl_support(), Object::mode, NULL, OB_MATERIAL, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, OB_NEG_SCALE, Scene::obedit, scene_use_new_shading_nodes(), tex_mat_set_face_editmesh_cb(), tex_mat_set_face_mesh_cb(), tex_mat_set_material_cb(), tex_mat_set_texture_cb(), Object::transflag, and wpaint__setSolidDrawOptions_material().
Referenced by draw_em_fancy(), and draw_mesh_fancy().
void draw_mesh_textured_old (Scene * scene, View3D * v3d, RegionView3D * rv3d, Object * ob, DerivedMesh * dm, int draw_flags)
Definition at line 773 of file drawmesh.c.
References add_tface_color_layer(), BMEditMesh::bm, CD_MFACE, CD_MLOOPCOL, CD_MTEXPOLY, CD_MTFACE, CD_TEXTURE_MCOL, compareDrawOptions(), compareDrawOptionsEm(), CustomData_has_layer(), Object::data, data, DM_DRAW_ALWAYS_SMOOTH, DM_DRAW_USE_COLORS, DM_get_tessface_data_layer(), draw_em_tf_mapped__set_draw(), DRAW_FACE_SELECT, draw_mcol__set_draw_legacy(), draw_mesh_face_select(), draw_mesh_text(), DRAW_MODIFIERS_PREVIEW, draw_textured_begin(), draw_textured_end(), draw_tface__set_draw(), draw_tface__set_draw_legacy(), draw_tface_mapped__set_draw(), DerivedMesh::drawFacesTex, DerivedMesh::drawMappedFaces, DerivedMesh::drawMappedFacesTex, Mesh::edit_btmesh, drawEMTFMapped_userData::em, DerivedMesh::faceData, get_ob_property(), GPU_buffer_legacy(), GPU_enable_material(), drawEMTFMapped_userData::has_mcol, drawEMTFMapped_userData::has_mtface, BMesh::ldata, drawEMTFMapped_userData::mf, drawTFace_userData::mf, Object::mode, Mesh::mpoly, NULL, OB_MODE_EDIT, OB_MODE_WEIGHT_PAINT, OB_NEG_SCALE, Scene::obedit, BMesh::pdata, drawTFace_userData::tf, drawEMTFMapped_userData::tf, Object::transflag, and wpaint__setSolidDrawOptions_facemask().
Referenced by draw_mesh_textured().
static void draw_textured_begin (Scene * scene, View3D * v3d, RegionView3D * rv3d, Object * ob) [static]
Definition at line 343 of file drawmesh.c.
References Object::col, RenderData::color_mgt_flag, TextureDrawState::color_profile, View3D::drawtype, FALSE, GPU_scene_object_lights(), Gtexdraw, RegionView3D::is_persp, TextureDrawState::islit, TextureDrawState::istex, View3D::lay, Object::mode, NULL, TextureDrawState::ob, OB_MODE_EDIT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, OB_SOLID, OB_TEXTURE, OB_WIRE, TextureDrawState::obcol, Scene::r, R_COLOR_MANAGEMENT, rgba_float_to_uchar(), set_draw_settings_cached(), TRUE, and RegionView3D::viewmat.
Referenced by draw_mesh_textured_old().
static void draw_textured_end (void) [static]
Definition at line 381 of file drawmesh.c.
References GPU_default_lights(), GPU_set_tpage(), and NULL.
Referenced by draw_mesh_textured_old().
static DMDrawOption draw_tface__set_draw (MTFace * tface, int has_mcol, int matnr) [static]
Definition at line 449 of file drawmesh.c.
References DM_DRAW_OPTION_NO_MCOL, DM_DRAW_OPTION_NORMAL, GameSettings::flag, Material::game, GEMAT_INVISIBLE, give_current_material(), Gtexdraw, MTFace::mode, TextureDrawState::ob, set_draw_settings_cached(), and TF_OBCOL.
Referenced by draw_mesh_textured_old().
static DMDrawOption draw_tface__set_draw_legacy (MTFace * tface, int has_mcol, int matnr) [static]
Definition at line 404 of file drawmesh.c.
References TextureDrawState::color_profile, copy_v3_v3(), DM_DRAW_OPTION_NO_MCOL, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, GameSettings::flag, Material::game, GEMAT_INVISIBLE, give_current_material(), Gtexdraw, linearrgb_to_srgb_v3_v3(), MA_OBCOLOR, TextureDrawState::ob, TextureDrawState::obcol, Material::r, set_draw_settings_cached(), and Material::shade_flag.
Referenced by draw_em_tf_mapped__set_draw(), and draw_mesh_textured_old().
static DMDrawOption draw_tface_mapped__set_draw (void * userData, int index) [static]
Definition at line 548 of file drawmesh.c.
References BLI_assert, DM_DRAW_OPTION_SKIP, MPoly::flag, ME_HIDE, Mesh::mpoly, Mesh::mtpoly, and NULL.
Referenced by draw_mesh_textured_old().
static void get_marked_edge_info__orFlags (EdgeHash * eh, int v0, int v1, int flags) [static]
Definition at line 104 of file drawmesh.c.
References BLI_edgehash_haskey(), BLI_edgehash_insert(), BLI_edgehash_lookup_p(), and NULL.
Referenced by get_tface_mesh_marked_edge_info().
static EdgeHash* get_tface_mesh_marked_edge_info (Mesh * me) [static]
Definition at line 115 of file drawmesh.c.
References BLI_edgehash_new(), eEdge_Select, eEdge_Visible, MPoly::flag, get_marked_edge_info__orFlags(), i, MPoly::loopstart, ME_FACE_SEL, ME_HIDE, ME_POLY_LOOP_NEXT, Mesh::mloop, Mesh::mpoly, MPoly::totloop, Mesh::totpoly, and MLoop::v.
Referenced by draw_mesh_face_select().
static Material* give_current_material_or_def (Object * ob, int matnr) [static]
Definition at line 224 of file drawmesh.c.
References defmaterial, and give_current_material().
Referenced by set_draw_settings_cached().
static int set_draw_settings_cached (int clearcache, MTFace * texface, Material * ma, struct TextureDrawState gtexdraw) [static]
Definition at line 241 of file drawmesh.c.
References GameSettings::alpha_blend, BKE_image_has_alpha(), CLAMPIS, FALSE, GameSettings::flag, Material::game, GEMAT_BACKCULL, give_current_material_or_def(), GPU_BLEND_ALPHA, GPU_set_tpage(), Material::har, TextureDrawState::islit, TextureDrawState::istex, MA_SHLESS, Material::mode, Object::mode, NULL, TextureDrawState::ob, OB_MODE_TEXTURE_PAINT, spec(), Material::spec, Material::specb, Material::specg, Material::specr, and MTFace::tpage.
Referenced by add_tface_color_layer(), draw_mesh_text(), draw_textured_begin(), draw_tface__set_draw(), and draw_tface__set_draw_legacy().
static int tex_mat_set_face_editmesh_cb (void * userData, int index) [static]
Definition at line 933 of file drawmesh.c.
References BM_elem_flag_test, BM_ELEM_HIDDEN, data, EDBM_face_at_index(), Mesh::edit_btmesh, and TexMatCallback::me.
Referenced by draw_mesh_textured().
static int tex_mat_set_face_mesh_cb (void * userData, int index) [static]
Definition at line 923 of file drawmesh.c.
References data, TexMatCallback::me, ME_HIDE, and Mesh::mpoly.
Referenced by draw_mesh_textured().
static void tex_mat_set_material_cb (void * UNUSEDuserData, int mat_nr, void * attribs) [static]
Definition at line 850 of file drawmesh.c.
References GPU_enable_material().
Referenced by draw_mesh_textured().
static void tex_mat_set_texture_cb (void * userData, int mat_nr, void * attribs) [static]
Definition at line 859 of file drawmesh.c.
References Image::bindcode, CD_MTFACE, data, ED_object_get_active_image(), glLoadMatrixf, GPUVertexAttribs::gltexco, GPU_disable_material(), GPU_enable_material(), GPU_verify_image(), GPUVertexAttribs::layer, TexMapping::mat, GPUVertexAttribs::name, TexMatCallback::ob, bNode::storage, NodeTexBase::tex_mapping, GPUVertexAttribs::totlayer, and GPUVertexAttribs::type.
Referenced by draw_mesh_textured().
static DMDrawOption wpaint__setSolidDrawOptions_facemask (void * userData, int index) [static]
Definition at line 611 of file drawmesh.c.
References DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, MPoly::flag, ME_HIDE, and Mesh::mpoly.
Referenced by draw_mesh_textured_old().
static DMDrawOption wpaint__setSolidDrawOptions_material (void * userData, int index) [static]
Definition at line 596 of file drawmesh.c.
References DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, GameSettings::flag, Material::game, GEMAT_INVISIBLE, Mesh::mat, MPoly::mat_nr, and Mesh::mpoly.
Referenced by draw_mesh_textured().
Variable Documentation
struct TextureDrawState Gtexdraw [static]
Referenced by add_tface_color_layer(), draw_mesh_text(), draw_textured_begin(), draw_tface__set_draw(), and draw_tface__set_draw_legacy().