Blender: KX_MotionState Class Reference
KX_MotionState Class Reference
#include <KX_MotionState.h>
Public Member Functions
KX_MotionState (class SG_Spatial *spatial)
virtual ~KX_MotionState ()
virtual void getWorldPosition (float &posX, float &posY, float &posZ)
virtual void getWorldScaling (float &scaleX, float &scaleY, float &scaleZ)
virtual void getWorldOrientation (float &quatIma0, float &quatIma1, float &quatIma2, float &quatReal)
virtual void setWorldPosition (float posX, float posY, float posZ)
virtual void setWorldOrientation (float quatIma0, float quatIma1, float quatIma2, float quatReal)
virtual void getWorldOrientation (float *ori)
virtual void setWorldOrientation (const float *ori)
virtual void calculateWorldTransformations ()
Detailed Description
Definition at line 41 of file KX_MotionState.h.
Constructor & Destructor Documentation
KX_MotionState::KX_MotionState (class SG_Spatial * spatial)
Definition at line 35 of file KX_MotionState.cpp.
KX_MotionState::~KX_MotionState () [virtual]
Definition at line 40 of file KX_MotionState.cpp.
Member Function Documentation
void KX_MotionState::calculateWorldTransformations () [virtual]
Implements PHY_IMotionState.
Definition at line 99 of file KX_MotionState.cpp.
void KX_MotionState::getWorldOrientation (float & quatIma0, float & quatIma1, float & quatIma2, float & quatReal) [virtual]
Implements PHY_IMotionState.
Definition at line 60 of file KX_MotionState.cpp.
References MT_Matrix3x3::getRotation(), and SG_Spatial::GetWorldOrientation().
void KX_MotionState::getWorldOrientation (float * ori) [virtual]
Implements PHY_IMotionState.
Definition at line 69 of file KX_MotionState.cpp.
References MT_Matrix3x3::getValue(), and SG_Spatial::GetWorldOrientation().
void KX_MotionState::getWorldPosition (float & posX, float & posY, float & posZ) [virtual]
Implements PHY_IMotionState.
Definition at line 44 of file KX_MotionState.cpp.
References SG_Spatial::GetWorldPosition().
void KX_MotionState::getWorldScaling (float & scaleX, float & scaleY, float & scaleZ) [virtual]
Implements PHY_IMotionState.
Definition at line 52 of file KX_MotionState.cpp.
References SG_Spatial::GetWorldScaling().
void KX_MotionState::setWorldOrientation (float quatIma0, float quatIma1, float quatIma2, float quatReal) [virtual]
Implements PHY_IMotionState.
Definition at line 86 of file KX_MotionState.cpp.
References SG_Spatial::SetLocalOrientation().
void KX_MotionState::setWorldOrientation (const float * ori) [virtual]
Implements PHY_IMotionState.
Definition at line 75 of file KX_MotionState.cpp.
References SG_Spatial::SetLocalOrientation().
void KX_MotionState::setWorldPosition (float posX, float posY, float posZ) [virtual]
Implements PHY_IMotionState.
Definition at line 80 of file KX_MotionState.cpp.
References SG_Spatial::SetLocalPosition().
The documentation for this class was generated from the following files:
KX_MotionState.h
KX_MotionState.cpp