Blender: LOD_QuadricEditor Class Reference
LOD_QuadricEditor Class Reference
#include <LOD_QuadricEditor.h>
Public Member Functions
void Remove (std::vector< LOD_VertexInd > &sorted_vertices)
void Update (std::vector< LOD_FaceInd > &sorted_vertices)
std::vector< LOD_Quadric > & Quadrics () const
bool BuildQuadrics (LOD_ExternNormalEditor &normal_editor, bool preserve_boundaries)
void ComputeEdgeCosts (std::vector< LOD_EdgeInd > &edges)
MT_Vector3 TargetVertex (LOD_Edge &e)
~LOD_QuadricEditor ()
Static Public Member Functions
static LOD_QuadricEditor * New (LOD_ManMesh2 &mesh)
Detailed Description
Definition at line 44 of file LOD_QuadricEditor.h.
Constructor & Destructor Documentation
LOD_QuadricEditor::~LOD_QuadricEditor () [inline]
Definition at line 99 of file LOD_QuadricEditor.h.
Member Function Documentation
bool LOD_QuadricEditor::BuildQuadrics (LOD_ExternNormalEditor & normal_editor, bool preserve_boundaries)
Definition at line 99 of file LOD_QuadricEditor.cpp.
References MT_Vector3::cross(), MT_Vector3::dot(), LOD_ManMesh2::EdgeSet(), CTR_TaggedIndex< 24, 0x00ffffff >::Empty(), LOD_Quadric::Evaluate(), LOD_ManMesh2::FaceSet(), MT_Vector3::fuzzyZero(), CTR_UHeapable::HeapKey(), LOD_Edge::m_verts, MT_Vector3::normalize(), LOD_ExternNormalEditor::Normals(), NULL, TargetVertex(), and LOD_ManMesh2::VertexSet().
void LOD_QuadricEditor::ComputeEdgeCosts (std::vector< LOD_EdgeInd > & edges)
Definition at line 282 of file LOD_NdQuadricEditor.cpp.
References LOD_ManMesh2::EdgeSet(), LOD_NdQuadric::Evaluate(), CTR_UHeapable::HeapKey(), LOD_Edge::m_verts, and LOD_NdQuadricEditor::TargetVertex().
LOD_QuadricEditor * LOD_QuadricEditor::New (LOD_ManMesh2 & mesh) [static]
Definition at line 53 of file LOD_QuadricEditor.cpp.
References NULL, and MEM_SmartPtr< T >::Release().
Referenced by LOD_QSDecimator::New().
std::vector<LOD_Quadric>& LOD_QuadricEditor::Quadrics () const [inline]
Definition at line 73 of file LOD_QuadricEditor.h.
void LOD_QuadricEditor::Remove (std::vector< LOD_VertexInd > & sorted_vertices)
Definition at line 72 of file LOD_QuadricEditor.cpp.
MT_Vector3 LOD_QuadricEditor::TargetVertex (LOD_Edge & e)
Definition at line 194 of file LOD_QuadricEditor.cpp.
References LOD_Edge::m_verts, LOD_Quadric::Optimize(), and LOD_ManMesh2::VertexSet().
Referenced by BuildQuadrics().
void BL_Shader::Update (std::vector< LOD_FaceInd > & sorted_vertices)
Definition at line 125 of file BL_BlenderShader.cpp.
References DerivedMesh::auto_bump_scale, MT_Tuple4::getValue(), MT_Matrix4x4::getValue(), RAS_IRasterizer::GetViewInvMatrix(), RAS_IRasterizer::GetViewMatrix(), GPU_material_alpha_blend(), GPU_material_bind_uniforms(), GPU_material_bound(), RAS_MeshSlot::m_bObjectColor, RAS_MeshSlot::m_OpenGLMatrix, RAS_MeshSlot::m_pDerivedMesh, RAS_MeshSlot::m_RGBAcolor, and MT_Matrix4x4::setValue().
The documentation for this class was generated from the following files:
LOD_QuadricEditor.h
BL_BlenderShader.cpp
BL_Shader.cpp
LOD_NdQuadricEditor.cpp
LOD_QuadricEditor.cpp