Blender: KX_NetworkMessageSensor Class Reference
KX_NetworkMessageSensor Class Reference
#include <KX_NetworkMessageSensor.h>
Public Member Functions
KX_NetworkMessageSensor (KX_NetworkEventManager *eventmgr, NG_NetworkScene *NetworkScene, SCA_IObject *gameobj, const STR_String &subject)
virtual ~KX_NetworkMessageSensor ()
virtual CValue * GetReplica ()
virtual bool Evaluate ()
virtual bool IsPositiveTrigger ()
virtual void Init ()
void EndFrame ()
virtual void Replace_NetworkScene (NG_NetworkScene *val)
Detailed Description
Definition at line 40 of file KX_NetworkMessageSensor.h.
Constructor & Destructor Documentation
KX_NetworkMessageSensor::KX_NetworkMessageSensor (KX_NetworkEventManager * eventmgr, NG_NetworkScene * NetworkScene, SCA_IObject * gameobj, const STR_String & subject)
Definition at line 50 of file KX_NetworkMessageSensor.cpp.
References Init().
Referenced by GetReplica().
KX_NetworkMessageSensor::~KX_NetworkMessageSensor () [virtual]
Definition at line 71 of file KX_NetworkMessageSensor.cpp.
Member Function Documentation
void KX_NetworkMessageSensor::EndFrame ()
bool KX_NetworkMessageSensor::Evaluate () [virtual]
Implements SCA_ISensor.
Definition at line 88 of file KX_NetworkMessageSensor.cpp.
References CListValue::Add(), NG_NetworkScene::FindMessages(), CValue::GetName(), SCA_ILogicBrick::GetParent(), NULL, and CValue::Release().
CValue * KX_NetworkMessageSensor::GetReplica (void) [virtual]
Implements SCA_ISensor.
Definition at line 75 of file KX_NetworkMessageSensor.cpp.
References KX_NetworkMessageSensor(), NULL, and CValue::ProcessReplica().
void KX_NetworkMessageSensor::Init (void) [virtual]
Reimplemented from SCA_ISensor.
Definition at line 66 of file KX_NetworkMessageSensor.cpp.
Referenced by KX_NetworkMessageSensor().
bool KX_NetworkMessageSensor::IsPositiveTrigger () [virtual]
Reimplemented from SCA_ISensor.
Definition at line 154 of file KX_NetworkMessageSensor.cpp.
virtual void KX_NetworkMessageSensor::Replace_NetworkScene (NG_NetworkScene * val) [inline, virtual]
Reimplemented from SCA_ILogicBrick.
Definition at line 71 of file KX_NetworkMessageSensor.h.
The documentation for this class was generated from the following files:
KX_NetworkMessageSensor.h
KX_NetworkMessageSensor.cpp