Blender: ImageBase.h File Reference
ImageBase.h File Reference
BGE Video Texture
#include "Common.h"
#include <vector>
#include <PyObjectPlus.h>
#include "PyTypeList.h"
#include "FilterBase.h"
Classes
class ImageBase
base class for image filters
struct PyImage
class ImageSource
class for source of image
Typedefs
typedef std::vector
< ImageSource * > ImageSourceList
type for list of image sources
Functions
template<class T >
static int Image_init (PyObject *pySelf, PyObject *args, PyObject *kwds)
PyObject * Image_allocNew (PyTypeObject *type, PyObject *args, PyObject *kwds)
void Image_dealloc (PyImage *self)
PyObject * Image_getImage (PyImage *self, char *mode)
PyObject * Image_getSize (PyImage *self, void *closure)
PyObject * Image_refresh (PyImage *self)
PyObject * Image_getScale (PyImage *self, void *closure)
int Image_setScale (PyImage *self, PyObject *value, void *closure)
PyObject * Image_getFlip (PyImage *self, void *closure)
int Image_setFlip (PyImage *self, PyObject *value, void *closure)
PyObject * Image_getSource (PyImage *self, PyObject *args)
PyObject * Image_setSource (PyImage *self, PyObject *args)
PyObject * Image_getFilter (PyImage *self, void *closure)
int Image_setFilter (PyImage *self, PyObject *value, void *closure)
PyObject * Image_valid (PyImage *self, void *closure)
Variables
const int SourceIdSize = 32
PyTypeList pyImageTypes
PyBufferProcs imageBufferProcs
Detailed Description
Definition in file ImageBase.h.
Typedef Documentation
typedef std::vector<ImageSource*> ImageSourceList
type for list of image sources
Definition at line 42 of file ImageBase.h.
Function Documentation
PyObject* Image_allocNew (PyTypeObject * type, PyObject * args, PyObject * kwds)
Definition at line 360 of file ImageBase.cpp.
References PyImage::m_image, and NULL.
void Image_dealloc (PyImage * self)
Definition at line 371 of file ImageBase.cpp.
References NULL.
PyObject* Image_getFilter (PyImage * self, void * closure)
Definition at line 595 of file ImageBase.cpp.
References NULL.
PyObject* Image_getFlip (PyImage * self, void * closure)
Definition at line 513 of file ImageBase.cpp.
References NULL.
PyObject* Image_getImage (PyImage * self, char * mode)
Definition at line 390 of file ImageBase.cpp.
References _Buffer::asbyte, BGL_MakeBuffer(), _Buffer::buf, KDL::exp(), i, NULL, Exception::report(), S_OK, and THRWEXCP.
Referenced by imageToArray().
PyObject* Image_getScale (PyImage * self, void * closure)
Definition at line 491 of file ImageBase.cpp.
References NULL.
PyObject* Image_getSize (PyImage * self, void * closure)
Definition at line 477 of file ImageBase.cpp.
PyObject* Image_getSource (PyImage * self, PyObject * args)
Definition at line 536 of file ImageBase.cpp.
References NULL.
template<class T > static int Image_init (PyObject * pySelf, PyObject * args, PyObject * kwds) [static]
Definition at line 315 of file ImageBase.h.
References PyImage::m_image, ImageBase::m_image, NULL, and T.
PyObject* Image_refresh (PyImage * self)
Definition at line 484 of file ImageBase.cpp.
int Image_setFilter (PyImage * self, PyObject * value, void * closure)
Definition at line 616 of file ImageBase.cpp.
References PyTypeList::in(), NULL, and pyFilterTypes.
int Image_setFlip (PyImage * self, PyObject * value, void * closure)
Definition at line 520 of file ImageBase.cpp.
References NULL.
int Image_setScale (PyImage * self, PyObject * value, void * closure)
Definition at line 498 of file ImageBase.cpp.
References NULL.
PyObject* Image_setSource (PyImage * self, PyObject * args)
Definition at line 560 of file ImageBase.cpp.
References PyTypeList::in(), and NULL.
PyObject* Image_valid (PyImage * self, void * closure)
Definition at line 634 of file ImageBase.cpp.
Variable Documentation
PyBufferProcs imageBufferProcs
Definition at line 698 of file ImageBase.cpp.
PyTypeList pyImageTypes
Definition at line 353 of file ImageBase.cpp.
Referenced by imageToArray(), initVideoTexture(), registerAllTypes(), and Texture_setSource().
const int SourceIdSize = 32
Definition at line 259 of file ImageBase.h.
Referenced by ImageSource::ImageSource().