Blender: EIGENVALUE_HELPER.h File Reference
EIGENVALUE_HELPER.h File Reference
smoke
#include <algorithm>
#include <cmath>
Classes
struct sEigenvalue
Functions
void Eigentred2 (sEigenvalue &eval)
void Eigencdiv (sEigenvalue &eval, float xr, float xi, float yr, float yi)
void Eigentql2 (sEigenvalue &eval)
void Eigenorthes (sEigenvalue &eval)
void Eigenhqr2 (sEigenvalue &eval)
int computeEigenvalues3x3 (float dout[3], float a[3][3])
Detailed Description
Definition in file EIGENVALUE_HELPER.h.
Function Documentation
int computeEigenvalues3x3 (float dout[3], float a[3][3])
Definition at line 812 of file EIGENVALUE_HELPER.cpp.
References sEigenvalue::d, sEigenvalue::e, Eigenhqr2(), Eigenorthes(), Eigentql2(), Eigentred2(), sEigenvalue::H, i, sEigenvalue::issymmetric, sEigenvalue::n, sEigenvalue::ort, sqrt(), and sEigenvalue::V.
Referenced by WTURBULENCE::computeEigenvalues(), and WTURBULENCE::stepTurbulenceFull().
void Eigencdiv (sEigenvalue & eval, float xr, float xi, float yr, float yi)
Definition at line 125 of file EIGENVALUE_HELPER.cpp.
References sEigenvalue::cdivi, sEigenvalue::cdivr, and fabs().
Referenced by Eigenhqr2().
void Eigenhqr2 (sEigenvalue & eval)
Definition at line 356 of file EIGENVALUE_HELPER.cpp.
References sEigenvalue::cdivi, sEigenvalue::cdivr, sEigenvalue::d, sEigenvalue::e, Eigencdiv(), fabs(), sEigenvalue::H, i, max, min, sEigenvalue::n, norm(), p, pow(), sqrt(), and sEigenvalue::V.
Referenced by computeEigenvalues3x3().
void Eigenorthes (sEigenvalue & eval)
Definition at line 263 of file EIGENVALUE_HELPER.cpp.
References fabs(), g, sEigenvalue::H, i, sEigenvalue::n, sEigenvalue::ort, sqrt(), and sEigenvalue::V.
Referenced by computeEigenvalues3x3().
void Eigentql2 (sEigenvalue & eval)
Definition at line 140 of file EIGENVALUE_HELPER.cpp.
References sEigenvalue::d, sEigenvalue::e, fabs(), g, hypot(), i, max, sEigenvalue::n, p, pow(), and sEigenvalue::V.
Referenced by computeEigenvalues3x3().
void Eigentred2 (sEigenvalue & eval)
Definition at line 8 of file EIGENVALUE_HELPER.cpp.
References sEigenvalue::d, sEigenvalue::e, fabs(), g, i, sEigenvalue::n, sqrt(), and sEigenvalue::V.
Referenced by computeEigenvalues3x3().