Blender: STR_HashedString Class Reference
STR_HashedString Class Reference
#include <STR_HashedString.h>
Public Member Functions
STR_HashedString ()
STR_HashedString (const char *str)
STR_HashedString (const STR_String &str)
dword hash (dword init=0) const
Detailed Description
Definition at line 129 of file STR_HashedString.h.
Constructor & Destructor Documentation
STR_HashedString::STR_HashedString () [inline]
Definition at line 132 of file STR_HashedString.h.
STR_HashedString::STR_HashedString (const char * str) [inline]
Definition at line 133 of file STR_HashedString.h.
STR_HashedString::STR_HashedString (const STR_String & str) [inline]
Definition at line 134 of file STR_HashedString.h.
Member Function Documentation
dword STR_HashedString::hash (dword init = 0) const [inline]
Definition at line 136 of file STR_HashedString.h.
References init(), STR_String::Length(), length(), str, and STR_gHash().
Referenced by BL_ConvertMaterialIpos(), RAS_IPolyMaterial::Equals(), RAS_IPolyMaterial::GetMaterialNameHash(), and RAS_IPolyMaterial::hash().
The documentation for this class was generated from the following file:
STR_HashedString.h