Blender: btDbvtBroadphase.cpp File Reference
btDbvtBroadphase.cpp File Reference
#include "btDbvtBroadphase.h"
Classes
struct btDbvtTreeCollider
struct BroadphaseRayTester
struct BroadphaseAabbTester
Defines
#define SPC(_value_)
btDbvtBroadphase implementation by Nathanael Presson
Functions
template<typename T >
static void listappend (T *item, T *&list)
template<typename T >
static void listremove (T *item, T *&list)
template<typename T >
static int listcount (T *root)
template<typename T >
static void clear (T &value)
Define Documentation
#define SPC (_value_)
btDbvtBroadphase implementation by Nathanael Presson
Definition at line 45 of file btDbvtBroadphase.cpp.
Referenced by btDbvtBroadphase::collide().
Function Documentation
template<typename T > static void clear (T & value) [inline, static]
Definition at line 81 of file btDbvtBroadphase.cpp.
References T.
Referenced by BKE_ptcache_id_reset(), btDbvtBroadphase::btDbvtBroadphase(), btDbvtBroadphase::calculateOverlappingPairs(), edbm_mark_seam(), edbm_mark_sharp(), pin_exec(), set_style_exec(), shade_smooth_exec(), toggle_style_exec(), and iTaSC::CacheEntry::~CacheEntry().
template<typename T > static void listappend (T * item, T *& list) [inline, static]
Definition at line 54 of file btDbvtBroadphase.cpp.
Referenced by btDbvtBroadphase::collide(), btDbvtBroadphase::createProxy(), btDbvtBroadphase::setAabb(), and btDbvtBroadphase::setAabbForceUpdate().
template<typename T > static int listcount (T * root) [inline, static]
Definition at line 72 of file btDbvtBroadphase.cpp.
template<typename T > static void listremove (T * item, T *& list) [inline, static]
Definition at line 64 of file btDbvtBroadphase.cpp.
Referenced by btDbvtBroadphase::collide(), btDbvtBroadphase::destroyProxy(), btDbvtBroadphase::setAabb(), and btDbvtBroadphase::setAabbForceUpdate().