Blender: device_multi.cpp File Reference
device_multi.cpp File Reference
#include <stdlib.h>
#include <sstream>
#include "device.h"
#include "device_intern.h"
#include "device_network.h"
#include "util_foreach.h"
#include "util_list.h"
#include "util_map.h"
#include "util_time.h"
Classes
class MultiDevice
struct MultiDevice::SubDevice
Functions
Device * device_multi_create (DeviceInfo &info, bool background)
static bool device_multi_add (vector< DeviceInfo > &devices, DeviceType type, bool with_display, bool with_advanced_shading, const char *id_fmt, int num)
void device_multi_info (vector< DeviceInfo > &devices)
Function Documentation
static bool device_multi_add (vector< DeviceInfo > & devices, DeviceType type, bool with_display, bool with_advanced_shading, const char * id_fmt, int num) [static]
Definition at line 296 of file device_multi.cpp.
References DeviceInfo::advanced_shading, DeviceInfo::description, DEVICE_MULTI, DeviceInfo::display_device, i, DeviceInfo::id, DeviceInfo::multi_devices, DeviceInfo::num, string_printf(), string_split(), and DeviceInfo::type.
Referenced by device_multi_info().
Device* device_multi_create (DeviceInfo & info, bool background)
Definition at line 291 of file device_multi.cpp.
Referenced by Device::create().
void device_multi_info (vector< DeviceInfo > & devices)
Definition at line 391 of file device_multi.cpp.
References DEVICE_CUDA, device_multi_add(), and DEVICE_OPENCL.
Referenced by Device::available_devices().