Blender: LOD_ExternVColorEditor Class Reference
LOD_ExternVColorEditor Class Reference
#include <LOD_ExternVColorEditor.h>
Public Member Functions
void RemoveVertexColors (const std::vector< LOD_VertexInd > &sorted_verts)
MT_Vector3 IndexColor (const LOD_VertexInd &v) const
void SetColor (MT_Vector3 c, const LOD_VertexInd &v)
Static Public Member Functions
static LOD_ExternVColorEditor * New (LOD_Decimation_InfoPtr)
Detailed Description
Definition at line 41 of file LOD_ExternVColorEditor.h.
Member Function Documentation
MT_Vector3 LOD_ExternVColorEditor::IndexColor (const LOD_VertexInd & v) const
Definition at line 101 of file LOD_ExternVColorEditor.cpp.
Referenced by LOD_NdQuadricEditor::InitializeHeapKeys(), and LOD_NdQuadricEditor::TargetVertex().
LOD_ExternVColorEditor * LOD_ExternVColorEditor::New (LOD_Decimation_InfoPtr extern_info) [static]
Definition at line 50 of file LOD_ExternVColorEditor.cpp.
References NULL.
void LOD_ExternVColorEditor::RemoveVertexColors (const std::vector< LOD_VertexInd > & sorted_verts)
Definition at line 66 of file LOD_ExternVColorEditor.cpp.
References MT_Tuple3::getValue(), and LOD_Decimation_Info::vertex_num.
void LOD_ExternVColorEditor::SetColor (MT_Vector3 c, const LOD_VertexInd & v)
Definition at line 112 of file LOD_ExternVColorEditor.cpp.
References MT_Tuple3::getValue().
The documentation for this class was generated from the following files:
LOD_ExternVColorEditor.h
LOD_ExternVColorEditor.cpp