Blender: node_composite_common.c File Reference
node_composite_common.c File Reference
cmpnodes
#include "DNA_node_types.h"
#include "BKE_node.h"
#include "node_composite_util.h"
#include "node_common.h"
#include "node_exec.h"
Functions
static void copy_stack (bNodeStack *to, bNodeStack *from)
static void move_stack (bNodeStack *to, bNodeStack *from)
static void * group_initexec (bNode *node)
static void group_freeexec (bNode *UNUSED(node), void *nodedata)
static void group_copy_inputs (bNode *node, bNodeStack **in, bNodeStack *gstack)
static void group_move_outputs (bNode *node, bNodeStack **out, bNodeStack *gstack)
static void group_free_internal (bNodeTreeExec *gexec)
static void group_execute (void *data, int thread, struct bNode *node, void *nodedata, struct bNodeStack **in, struct bNodeStack **out)
void register_node_type_cmp_group (bNodeTreeType *ttype)
Detailed Description
Definition in file node_composite_common.c.
Function Documentation
static void copy_stack (bNodeStack * to, bNodeStack * from) [static]
Definition at line 86 of file node_composite_common.c.
References copy_v4_v4(), bNodeStack::data, bNodeStack::datatype, bNodeStack::is_copy, and bNodeStack::vec.
Referenced by group_copy_inputs().
static void group_copy_inputs (bNode * node, bNodeStack ** in, bNodeStack * gstack) [static]
Definition at line 150 of file node_composite_common.c.
References copy_stack(), ListBase::first, bNodeSocket::groupsock, bNode::inputs, bNodeSocket::next, and node_get_socket_stack().
Referenced by group_execute().
static void group_execute (void * data, int thread, struct bNode * node, void * nodedata, struct bNodeStack ** in, struct bNodeStack ** out) [static]
Definition at line 194 of file node_composite_common.c.
References ListBase::first, group_copy_inputs(), group_free_internal(), group_move_outputs(), bNode::need_exec, bNode::next, bNodeTree::nodes, bNodeTreeExec::nodetree, ntreeExecNodes(), and bNodeTreeExec::stack.
Referenced by register_node_type_cmp_group().
static void group_free_internal (bNodeTreeExec * gexec) [static]
Definition at line 179 of file node_composite_common.c.
References bNodeStack::data, bNodeStack::external, free_compbuf(), i, bNodeStack::is_copy, NULL, and bNodeTreeExec::stack.
Referenced by group_execute().
static void group_freeexec (bNode * UNUSEDnode, void * nodedata) [static]
Definition at line 139 of file node_composite_common.c.
References ntreeCompositEndExecTree().
Referenced by register_node_type_cmp_group().
static void* group_initexec (bNode * node) [static]
Definition at line 115 of file node_composite_common.c.
References exec(), bNodeStack::external, ListBase::first, bNodeSocket::flag, bNode::id, if(), bNodeSocket::next, node_get_socket_stack(), ntreeCompositBeginExecTree(), NULL, bNodeTree::outputs, SOCK_INTERNAL, and bNodeTreeExec::stack.
Referenced by register_node_type_cmp_group().
static void group_move_outputs (bNode * node, bNodeStack ** out, bNodeStack * gstack) [static]
Definition at line 165 of file node_composite_common.c.
References ListBase::first, bNodeSocket::groupsock, move_stack(), bNodeSocket::next, node_get_socket_stack(), and bNode::outputs.
Referenced by group_execute().
static void move_stack (bNodeStack * to, bNodeStack * from) [static]
Definition at line 98 of file node_composite_common.c.
References copy_v4_v4(), bNodeStack::data, bNodeStack::datatype, bNodeStack::is_copy, NULL, bNodeStack::vec, and zero_v4().
Referenced by group_move_outputs().
void register_node_type_cmp_group (bNodeTreeType * ttype)
Definition at line 216 of file node_composite_common.c.
References group_execute(), group_freeexec(), group_initexec(), NODE_CLASS_GROUP, NODE_CONST_OUTPUT, NODE_GROUP, node_group_edit_clear(), node_group_edit_get(), node_group_edit_set(), node_group_init(), node_group_label(), node_group_template(), node_group_valid(), node_group_verify(), NODE_OPTIONS, node_type_base(), node_type_exec_new(), node_type_group_edit(), node_type_init(), node_type_label(), node_type_size(), node_type_socket_templates(), node_type_template(), node_type_update(), node_type_valid(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().