Blender: KX_BoneParentRelation Class Reference
KX_BoneParentRelation Class Reference
#include <KX_SG_BoneParentNodeRelationship.h>
Public Member Functions
bool UpdateChildCoordinates (SG_Spatial *child, const SG_Spatial *parent, bool &parentUpdated)
SG_ParentRelation * NewCopy ()
~KX_BoneParentRelation ()
Static Public Member Functions
static KX_BoneParentRelation * New (Bone *bone)
Detailed Description
Bone parent relationship parents a child SG_Spatial frame to a bone in an armature object.
Definition at line 45 of file KX_SG_BoneParentNodeRelationship.h.
Constructor & Destructor Documentation
KX_BoneParentRelation::~KX_BoneParentRelation ()
Definition at line 143 of file KX_SG_BoneParentNodeRelationship.cpp.
Member Function Documentation
KX_BoneParentRelation * KX_BoneParentRelation::New (Bone * bone) [static]
Allocate and construct a new KX_SG_BoneParentRelation on the heap.
bone is the bone id to use. Currently it is a pointer to a Blender struct Bone - this should be fixed if
Implementation of classes defined in KX_SG_BoneParentNodeRelationship.h first of all KX_SG_BoneParentRelation
Definition at line 51 of file KX_SG_BoneParentNodeRelationship.cpp.
Referenced by BL_ConvertBlenderObjects().
SG_ParentRelation * KX_BoneParentRelation::NewCopy () [virtual]
Create a copy of this relationship
Implements SG_ParentRelation.
Definition at line 136 of file KX_SG_BoneParentNodeRelationship.cpp.
bool KX_BoneParentRelation::UpdateChildCoordinates (SG_Spatial * child, const SG_Spatial * parent, bool & parentUpdated) [virtual]
Updates the childs world coordinates relative to the parent's world coordinates.
Parent should be a BL_ArmatureObject.
Implements SG_ParentRelation.
Definition at line 58 of file KX_SG_BoneParentNodeRelationship.cpp.
References SG_IObject::ActivateRecheduleUpdateCallback(), SG_Spatial::ClearModified(), BL_ArmatureObject::GetBoneLength(), BL_ArmatureObject::GetBoneMatrix(), SG_Spatial::GetLocalOrientation(), SG_Spatial::GetLocalPosition(), SG_Spatial::GetLocalScale(), SG_IObject::GetSGClientObject(), SG_Spatial::GetWorldTransform(), length(), MT_assert, NULL, MT_Matrix3x3::scale(), MT_Matrix3x3::scaled(), MT_Matrix3x3::setValue(), MT_Tuple3::setValue(), SG_Spatial::SetWorldFromLocalTransform(), SG_Spatial::SetWorldOrientation(), SG_Spatial::SetWorldPosition(), and SG_Spatial::SetWorldScale().
The documentation for this class was generated from the following files:
KX_SG_BoneParentNodeRelationship.h
KX_SG_BoneParentNodeRelationship.cpp