Blender: btBoxShape Class Reference
btBoxShape Class Reference
The btBoxShape is a box primitive around the origin, its sides axis aligned with length specified by half extents, in local shape coordinates. When used as part of a btCollisionObject or btRigidBody it will be an oriented box in world space.
#include <btBoxShape.h>
Public Member Functions
btVector3 getHalfExtentsWithMargin () const
const btVector3 & getHalfExtentsWithoutMargin () const
virtual btVector3 localGetSupportingVertex (const btVector3 &vec) const
SIMD_FORCE_INLINE btVector3 localGetSupportingVertexWithoutMargin (const btVector3 &vec) const
virtual void batchedUnitVectorGetSupportingVertexWithoutMargin (const btVector3 *vectors, btVector3 *supportVerticesOut, int numVectors) const
btBoxShape (const btVector3 &boxHalfExtents)
virtual void setMargin (btScalar collisionMargin)
virtual void setLocalScaling (const btVector3 &scaling)
virtual void getAabb (const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const
getAabb's default implementation is brute force, expected derived classes to implement a fast dedicated version
virtual void calculateLocalInertia (btScalar mass, btVector3 &inertia) const
virtual void getPlane (btVector3 &planeNormal, btVector3 &planeSupport, int i) const
virtual int getNumPlanes () const
virtual int getNumVertices () const
virtual int getNumEdges () const
virtual void getVertex (int i, btVector3 &vtx) const
virtual void getPlaneEquation (btVector4 &plane, int i) const
virtual void getEdge (int i, btVector3 &pa, btVector3 &pb) const
virtual bool isInside (const btVector3 &pt, btScalar tolerance) const
virtual const char * getName () const
virtual int getNumPreferredPenetrationDirections () const
virtual void getPreferredPenetrationDirection (int index, btVector3 &penetrationVector) const
Detailed Description
The btBoxShape is a box primitive around the origin, its sides axis aligned with length specified by half extents, in local shape coordinates. When used as part of a btCollisionObject or btRigidBody it will be an oriented box in world space.
Definition at line 26 of file btBoxShape.h.
Constructor & Destructor Documentation
btBoxShape::btBoxShape (const btVector3 & boxHalfExtents) [inline]
Definition at line 83 of file btBoxShape.h.
References BOX_SHAPE_PROXYTYPE, btConvexInternalShape::getMargin(), btConvexInternalShape::m_implicitShapeDimensions, and btConvexInternalShape::m_localScaling.
Member Function Documentation
virtual void btBoxShape::batchedUnitVectorGetSupportingVertexWithoutMargin (const btVector3 * vectors, btVector3 * supportVerticesOut, int numVectors) const [inline, virtual]
Reimplemented from btPolyhedralConvexShape.
Definition at line 68 of file btBoxShape.h.
References btFsels, getHalfExtentsWithoutMargin(), and i.
void btBoxShape::calculateLocalInertia (btScalar mass, btVector3 & inertia) const [virtual]
Reimplemented from btPolyhedralConvexShape.
Definition at line 27 of file btBoxShape.cpp.
References getHalfExtentsWithMargin().
void btBoxShape::getAabb (const btTransform & t, btVector3 & aabbMin, btVector3 & aabbMax) const [virtual]
getAabb's default implementation is brute force, expected derived classes to implement a fast dedicated version
Reimplemented from btConvexInternalShape.
Definition at line 21 of file btBoxShape.cpp.
References btTransformAabb(), getHalfExtentsWithoutMargin(), and btConvexInternalShape::getMargin().
virtual void btBoxShape::getEdge (int i, btVector3 & pa, btVector3 & pb) const [inline, virtual]
Implements btPolyhedralConvexShape.
Definition at line 187 of file btBoxShape.h.
References btAssert, getVertex(), and i.
btVector3 btBoxShape::getHalfExtentsWithMargin () const [inline]
Definition at line 34 of file btBoxShape.h.
References getHalfExtentsWithoutMargin(), and btConvexInternalShape::getMargin().
Referenced by calculateLocalInertia(), btCollisionWorld::debugDrawObject(), and btBoxBoxDetector::getClosestPoints().
const btVector3& btBoxShape::getHalfExtentsWithoutMargin () const [inline]
Definition at line 42 of file btBoxShape.h.
References btConvexInternalShape::m_implicitShapeDimensions.
Referenced by batchedUnitVectorGetSupportingVertexWithoutMargin(), getAabb(), getHalfExtentsWithMargin(), getPlaneEquation(), btSphereBoxCollisionAlgorithm::getSphereDistance(), getVertex(), isInside(), localGetSupportingVertex(), and localGetSupportingVertexWithoutMargin().
virtual const char* btBoxShape::getName (void) const [inline, virtual]
Definition at line 276 of file btBoxShape.h.
virtual int btBoxShape::getNumEdges () const [inline, virtual]
Implements btPolyhedralConvexShape.
Definition at line 140 of file btBoxShape.h.
virtual int btBoxShape::getNumPlanes () const [inline, virtual]
Implements btPolyhedralConvexShape.
Definition at line 130 of file btBoxShape.h.
virtual int btBoxShape::getNumPreferredPenetrationDirections () const [inline, virtual]
Reimplemented from btConvexInternalShape.
Definition at line 281 of file btBoxShape.h.
virtual int btBoxShape::getNumVertices () const [inline, virtual]
Implements btPolyhedralConvexShape.
Definition at line 135 of file btBoxShape.h.
virtual void btBoxShape::getPlane (btVector3 & planeNormal, btVector3 & planeSupport, int i) const [inline, virtual]
Implements btPolyhedralConvexShape.
Definition at line 120 of file btBoxShape.h.
References getPlaneEquation(), and localGetSupportingVertex().
virtual void btBoxShape::getPlaneEquation (btVector4 & plane, int i) const [inline, virtual]
Definition at line 157 of file btBoxShape.h.
References btAssert, getHalfExtentsWithoutMargin(), and btVector4::setValue().
Referenced by getPlane().
virtual void btBoxShape::getPreferredPenetrationDirection (int index, btVector3 & penetrationVector) const [inline, virtual]
Reimplemented from btConvexInternalShape.
Definition at line 286 of file btBoxShape.h.
References btAssert.
virtual void btBoxShape::getVertex (int i, btVector3 & vtx) const [inline, virtual]
Implements btPolyhedralConvexShape.
Definition at line 146 of file btBoxShape.h.
References getHalfExtentsWithoutMargin().
Referenced by getEdge().
virtual bool btBoxShape::isInside (const btVector3 & pt, btScalar tolerance) const [inline, virtual]
Implements btPolyhedralConvexShape.
Definition at line 258 of file btBoxShape.h.
References getHalfExtentsWithoutMargin().
virtual btVector3 btBoxShape::localGetSupportingVertex (const btVector3 & vec) const [inline, virtual]
Reimplemented from btConvexInternalShape.
Definition at line 48 of file btBoxShape.h.
References btFsels, getHalfExtentsWithoutMargin(), and btConvexInternalShape::getMargin().
Referenced by getPlane().
SIMD_FORCE_INLINE btVector3 btBoxShape::localGetSupportingVertexWithoutMargin (const btVector3 & vec) const [inline, virtual]
Reimplemented from btPolyhedralConvexShape.
Definition at line 59 of file btBoxShape.h.
References btFsels, and getHalfExtentsWithoutMargin().
virtual void btBoxShape::setLocalScaling (const btVector3 & scaling) [inline, virtual]
Reimplemented from btConvexInternalShape.
Definition at line 102 of file btBoxShape.h.
References btConvexInternalShape::getMargin(), btConvexInternalShape::m_implicitShapeDimensions, and btConvexInternalShape::m_localScaling.
virtual void btBoxShape::setMargin (btScalar collisionMargin) [inline, virtual]
Reimplemented from btConvexInternalShape.
Definition at line 91 of file btBoxShape.h.
References btConvexInternalShape::getMargin(), and btConvexInternalShape::m_implicitShapeDimensions.
The documentation for this class was generated from the following files:
btBoxShape.h
btBoxShape.cpp