Blender: node_composite_rgb.c File Reference
node_composite_rgb.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void node_composit_init_rgb (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static void node_composit_exec_rgb (void *UNUSED(data), bNode *node, bNodeStack **UNUSED(in), bNodeStack **out)
void register_node_type_cmp_rgb (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_rgb_out []
Detailed Description
Definition in file node_composite_rgb.c.
Function Documentation
static void node_composit_exec_rgb (void * UNUSEDdata, bNode * node, bNodeStack ** UNUSEDin, bNodeStack ** out) [static]
Definition at line 53 of file node_composite_rgb.c.
References copy_v4_v4(), bNodeSocket::default_value, ListBase::first, and bNode::outputs.
Referenced by register_node_type_cmp_rgb().
static void node_composit_init_rgb (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 42 of file node_composite_rgb.c.
References bNodeSocket::default_value, ListBase::first, and bNode::outputs.
Referenced by register_node_type_cmp_rgb().
void register_node_type_cmp_rgb (bNodeTreeType * ttype)
Definition at line 61 of file node_composite_rgb.c.
References CMP_NODE_RGB, NODE_CLASS_INPUT, node_composit_exec_rgb(), node_composit_init_rgb(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_rgb_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "RGBA",           0.5f, 0.5f, 0.5f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_composite_rgb.c.