Blender: node_composite_glare.c File Reference
node_composite_glare.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void mixImages (CompBuf *dst, CompBuf *src, float mix)
static void addImage (CompBuf *dst, CompBuf *src, float scale)
static CompBuf * BTP (CompBuf *src, float threshold, int scaledown)
static void star4 (NodeGlare *ndg, CompBuf *dst, CompBuf *src)
static void streaks (NodeGlare *ndg, CompBuf *dst, CompBuf *src)
static float smoothMask (float x, float y)
static void ghosts (NodeGlare *ndg, CompBuf *dst, CompBuf *src)
static void fglow (NodeGlare *ndg, CompBuf *dst, CompBuf *src)
static void node_composit_exec_glare (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_glare (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_glare (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_glare_in []
static bNodeSocketTemplate cmp_node_glare_out []
Detailed Description
Definition in file node_composite_glare.c.
Function Documentation
static void addImage (CompBuf * dst, CompBuf * src, float scale) [static]
Definition at line 92 of file node_composite_glare.c.
References p, CompBuf::rect, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by streaks().
static CompBuf* BTP (CompBuf * src, float threshold, int scaledown) [static]
Definition at line 103 of file node_composite_glare.c.
References MAX2, qd_downScaledCopy(), CompBuf::rect, CompBuf::x, and CompBuf::y.
Referenced by fglow(), ghosts(), star4(), and streaks().
static void fglow (NodeGlare * ndg, CompBuf * dst, CompBuf * src) [static]
Definition at line 389 of file node_composite_glare.c.
References alloc_compbuf(), BTP(), CB_RGBA, convolve(), cos(), expf, free_compbuf(), fRGB_mult, M_PI, NodeGlare::mix, mixImages(), qd_setPixel(), NodeGlare::quality, NodeGlare::size, sqrtf, and NodeGlare::threshold.
Referenced by node_composit_exec_glare().
static void ghosts (NodeGlare * ndg, CompBuf * dst, CompBuf * src) [static]
Definition at line 304 of file node_composite_glare.c.
References BTP(), NodeGlare::colmod, dupalloc_compbuf(), free_compbuf(), fRGB_colormult, fRGB_madd, fRGB_mult, fRGB_rgbmult, IIR_gauss(), NodeGlare::iter, NodeGlare::mix, mixImages(), p, qd_getPixelLerp(), qd_setPixel(), NodeGlare::quality, CompBuf::rect, smoothMask(), NodeGlare::threshold, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_glare().
static void mixImages (CompBuf * dst, CompBuf * src, float mix) [static]
Definition at line 46 of file node_composite_glare.c.
References fabsf, fRGB_copy, fRGB_mult, qd_getPixelLerp(), CompBuf::rect, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by fglow(), ghosts(), and streaks().
static void node_composit_exec_glare (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 429 of file node_composite_glare.c.
References CB_RGBA, bNodeStack::data, dupalloc_compbuf(), fglow(), free_compbuf(), ghosts(), MAX2, NULL, star4(), bNode::storage, streaks(), NodeGlare::type, CompBuf::type, and typecheck_compbuf().
Referenced by register_node_type_cmp_glare().
static void node_composit_init_glare (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 477 of file node_composite_glare.c.
References NodeGlare::angle, NodeGlare::angle_ofs, NodeGlare::colmod, NodeGlare::fade, NodeGlare::iter, MEM_callocN(), NodeGlare::mix, NodeGlare::quality, NodeGlare::size, bNode::storage, NodeGlare::threshold, and NodeGlare::type.
Referenced by register_node_type_cmp_glare().
void register_node_type_cmp_glare (bNodeTreeType * ttype)
Definition at line 493 of file node_composite_glare.c.
References CMP_NODE_GLARE, NODE_CLASS_OP_FILTER, node_composit_exec_glare(), node_composit_init_glare(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
static float smoothMask (float x, float y) [static]
Definition at line 296 of file node_composite_glare.c.
References sqrtf.
Referenced by ghosts().
static void star4 (NodeGlare * ndg, CompBuf * dst, CompBuf * src) [static]
Definition at line 124 of file node_composite_glare.c.
References NodeGlare::angle, BTP(), dupalloc_compbuf(), NodeGlare::fade, free_compbuf(), fRGB_madd, fRGB_mult, i, NodeGlare::iter, NodeGlare::mix, p, qd_getPixel(), qd_getPixelLerp(), qd_setPixel(), NodeGlare::quality, CompBuf::rect, NodeGlare::threshold, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_glare().
static void streaks (NodeGlare * ndg, CompBuf * dst, CompBuf * src) [static]
Definition at line 235 of file node_composite_glare.c.
References addImage(), alloc_compbuf(), NodeGlare::angle, NodeGlare::angle_ofs, BTP(), NodeGlare::colmod, cos(), DEG2RADF, dupalloc_compbuf(), NodeGlare::fade, free_compbuf(), fRGB_rgbmult, NodeGlare::iter, NodeGlare::mix, mixImages(), pow(), qd_getPixel(), qd_getPixelLerp(), NodeGlare::quality, CompBuf::rect, sin(), NodeGlare::threshold, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_glare().
Variable Documentation
bNodeSocketTemplate cmp_node_glare_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 35 of file node_composite_glare.c.
bNodeSocketTemplate cmp_node_glare_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 39 of file node_composite_glare.c.