Blender: sequencer_intern.h File Reference
sequencer_intern.h File Reference
sequencer
#include "RNA_access.h"
#include "DNA_sequence_types.h"
Defines
#define SCE_MARKERS 0
Enumerations
enum { SEQ_SIDE_NONE = 0, SEQ_SIDE_LEFT, SEQ_SIDE_RIGHT, SEQ_SIDE_BOTH }
enum { SEQ_CUT_SOFT, SEQ_CUT_HARD }
enum { SEQ_SELECTED, SEQ_UNSELECTED }
Functions
struct ARegion * sequencer_has_buttons_region (struct ScrArea *sa)
void draw_timeline_seq (const struct bContext *C, struct ARegion *ar)
void draw_image_seq (const struct bContext *C, struct Scene *scene, struct ARegion *ar, struct SpaceSeq *sseq, int cfra, int offset)
void seq_reset_imageofs (struct SpaceSeq *sseq)
void seq_rectf (struct Sequence *seq, struct rctf *rectf)
void boundbox_seq (struct Scene *scene, struct rctf *rect)
struct Sequence * find_nearest_seq (struct Scene *scene, struct View2D *v2d, int *hand, const int mval[2])
struct Sequence * find_neighboring_sequence (struct Scene *scene, struct Sequence *test, int lr, int sel)
void deselect_all_seq (struct Scene *scene)
void recurs_sel_seq (struct Sequence *seqm)
int seq_effect_find_selected (struct Scene *scene, struct Sequence *activeseq, int type, struct Sequence **selseq1, struct Sequence **selseq2, struct Sequence **selseq3, const char **error_str)
int sequencer_edit_poll (struct bContext *C)
int sequencer_strip_poll (struct bContext *C)
int sequencer_strip_has_path_poll (struct bContext *C)
int sequencer_view_poll (struct bContext *C)
void SEQUENCER_OT_cut (struct wmOperatorType *ot)
void SEQUENCER_OT_mute (struct wmOperatorType *ot)
void SEQUENCER_OT_unmute (struct wmOperatorType *ot)
void SEQUENCER_OT_lock (struct wmOperatorType *ot)
void SEQUENCER_OT_unlock (struct wmOperatorType *ot)
void SEQUENCER_OT_reload (struct wmOperatorType *ot)
void SEQUENCER_OT_refresh_all (struct wmOperatorType *ot)
void SEQUENCER_OT_reassign_inputs (struct wmOperatorType *ot)
void SEQUENCER_OT_swap_inputs (struct wmOperatorType *ot)
void SEQUENCER_OT_duplicate (struct wmOperatorType *ot)
void SEQUENCER_OT_delete (struct wmOperatorType *ot)
void SEQUENCER_OT_offset_clear (struct wmOperatorType *ot)
void SEQUENCER_OT_images_separate (struct wmOperatorType *ot)
void SEQUENCER_OT_meta_toggle (struct wmOperatorType *ot)
void SEQUENCER_OT_meta_make (struct wmOperatorType *ot)
void SEQUENCER_OT_meta_separate (struct wmOperatorType *ot)
void SEQUENCER_OT_snap (struct wmOperatorType *ot)
void SEQUENCER_OT_previous_edit (struct wmOperatorType *ot)
void SEQUENCER_OT_next_edit (struct wmOperatorType *ot)
void SEQUENCER_OT_swap (struct wmOperatorType *ot)
void SEQUENCER_OT_swap_data (struct wmOperatorType *ot)
void SEQUENCER_OT_rendersize (struct wmOperatorType *ot)
void SEQUENCER_OT_view_toggle (struct wmOperatorType *ot)
void SEQUENCER_OT_view_all (struct wmOperatorType *ot)
void SEQUENCER_OT_view_selected (struct wmOperatorType *ot)
void SEQUENCER_OT_view_zoom_ratio (struct wmOperatorType *ot)
void SEQUENCER_OT_view_ghost_border (struct wmOperatorType *ot)
void SEQUENCER_OT_change_effect_input (struct wmOperatorType *ot)
void SEQUENCER_OT_change_effect_type (struct wmOperatorType *ot)
void SEQUENCER_OT_change_path (struct wmOperatorType *ot)
void SEQUENCER_OT_copy (struct wmOperatorType *ot)
void SEQUENCER_OT_paste (struct wmOperatorType *ot)
void SEQUENCER_OT_rebuild_proxy (struct wmOperatorType *ot)
void SEQUENCER_OT_update_strip_length (struct wmOperatorType *ot)
void SEQUENCER_OT_view_all_preview (struct wmOperatorType *ot)
void SEQUENCER_OT_select_all (struct wmOperatorType *ot)
void SEQUENCER_OT_select (struct wmOperatorType *ot)
void SEQUENCER_OT_select_more (struct wmOperatorType *ot)
void SEQUENCER_OT_select_less (struct wmOperatorType *ot)
void SEQUENCER_OT_select_linked (struct wmOperatorType *ot)
void SEQUENCER_OT_select_linked_pick (struct wmOperatorType *ot)
void SEQUENCER_OT_select_handles (struct wmOperatorType *ot)
void SEQUENCER_OT_select_active_side (struct wmOperatorType *ot)
void SEQUENCER_OT_select_border (struct wmOperatorType *ot)
void SEQUENCER_OT_select_inverse (struct wmOperatorType *ot)
void SEQUENCER_OT_select_grouped (struct wmOperatorType *ot)
void SEQUENCER_OT_scene_strip_add (struct wmOperatorType *ot)
void SEQUENCER_OT_movie_strip_add (struct wmOperatorType *ot)
void SEQUENCER_OT_movieclip_strip_add (struct wmOperatorType *ot)
void SEQUENCER_OT_sound_strip_add (struct wmOperatorType *ot)
void SEQUENCER_OT_image_strip_add (struct wmOperatorType *ot)
void SEQUENCER_OT_effect_strip_add (struct wmOperatorType *ot)
void sequencer_operatortypes (void)
void sequencer_keymap (struct wmKeyConfig *keyconf)
struct ImBuf * make_waveform_view_from_ibuf (struct ImBuf *ibuf)
struct ImBuf * make_sep_waveform_view_from_ibuf (struct ImBuf *ibuf)
struct ImBuf * make_vectorscope_view_from_ibuf (struct ImBuf *ibuf)
struct ImBuf * make_zebra_view_from_ibuf (struct ImBuf *ibuf, float perc)
struct ImBuf * make_histogram_view_from_ibuf (struct ImBuf *ibuf)
void SEQUENCER_OT_properties (struct wmOperatorType *ot)
Variables
EnumPropertyItem sequencer_prop_effect_types []
EnumPropertyItem prop_side_types []
Detailed Description
Definition in file sequencer_intern.h.
Define Documentation
#define SCE_MARKERS 0
Definition at line 163 of file sequencer_intern.h.
Referenced by sequencer_select_invoke().
Enumeration Type Documentation
anonymous enum
Enumerator:
SEQ_SIDE_NONE
SEQ_SIDE_LEFT
SEQ_SIDE_RIGHT
SEQ_SIDE_BOTH
Definition at line 147 of file sequencer_intern.h.
anonymous enum
Enumerator:
SEQ_CUT_SOFT
SEQ_CUT_HARD
Definition at line 153 of file sequencer_intern.h.
anonymous enum
Enumerator:
SEQ_SELECTED
SEQ_UNSELECTED
Definition at line 157 of file sequencer_intern.h.
Function Documentation
void boundbox_seq (struct Scene * scene, struct rctf * rect)
Definition at line 255 of file sequencer_edit.c.
References EFRA, Sequence::enddisp, FALSE, ListBase::first, Sequence::machine, max, min, Sequence::next, NULL, seq_give_editing(), Editing::seqbasep, Sequence::startdisp, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by draw_timeline_seq().
void deselect_all_seq (struct Scene * scene)
Definition at line 457 of file sequencer_edit.c.
References FALSE, Sequence::flag, NULL, SEQ_ALLSEL, SEQ_END, seq_give_editing(), and SEQP_BEGIN.
Referenced by select_single_seq(), sequencer_add_effect_strip_exec(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_paste_exec(), sequencer_select_invoke(), and sequencer_select_linked_pick_invoke().
void draw_image_seq (const struct bContext * C, struct Scene * scene, struct ARegion * ar, struct SpaceSeq * sseq, int cfra, int offset)
void draw_timeline_seq (const struct bContext * C, struct ARegion * ar)
struct Sequence* find_nearest_seq (struct Scene * scene, struct View2D * v2d, int * hand, const int mval[2]) [read]
Definition at line 382 of file sequencer_edit.c.
References abs(), CLAMP(), View2D::cur, Sequence::enddisp, FALSE, ListBase::first, Sequence::handsize, Sequence::machine, View2D::mask, Sequence::next, NULL, seq_give_editing(), SEQ_SIDE_LEFT, SEQ_SIDE_NONE, SEQ_SIDE_RIGHT, seq_tx_test(), Editing::seqbasep, Sequence::startdisp, UI_view2d_region_to_view(), rcti::xmax, rctf::xmax, rcti::xmin, and rctf::xmin.
Referenced by sequencer_select_invoke(), and sequencer_select_linked_pick_invoke().
struct Sequence* find_neighboring_sequence (struct Scene * scene, struct Sequence * test, int lr, int sel) [read]
Definition at line 301 of file sequencer_edit.c.
References Sequence::enddisp, FALSE, ListBase::first, Sequence::flag, Sequence::machine, Sequence::next, NULL, SELECT, seq_give_editing(), SEQ_SIDE_LEFT, SEQ_SIDE_RIGHT, Editing::seqbasep, and Sequence::startdisp.
Referenced by select_more_less_seq__internal(), select_surrounding_handles(), and sequencer_select_invoke().
struct ImBuf* make_histogram_view_from_ibuf (struct ImBuf * ibuf) [read]
Definition at line 560 of file sequencer_scopes.c.
References make_histogram_view_from_ibuf_byte(), make_histogram_view_from_ibuf_float(), and ImBuf::rect_float.
Referenced by draw_image_seq().
struct ImBuf* make_sep_waveform_view_from_ibuf (struct ImBuf * ibuf) [read]
Definition at line 351 of file sequencer_scopes.c.
References make_sep_waveform_view_from_ibuf_byte(), make_sep_waveform_view_from_ibuf_float(), and ImBuf::rect_float.
Referenced by draw_image_seq().
struct ImBuf* make_vectorscope_view_from_ibuf (struct ImBuf * ibuf) [read]
Definition at line 696 of file sequencer_scopes.c.
References make_vectorscope_view_from_ibuf_byte(), make_vectorscope_view_from_ibuf_float(), and ImBuf::rect_float.
Referenced by draw_image_seq().
struct ImBuf* make_waveform_view_from_ibuf (struct ImBuf * ibuf) [read]
Definition at line 239 of file sequencer_scopes.c.
References make_waveform_view_from_ibuf_byte(), make_waveform_view_from_ibuf_float(), and ImBuf::rect_float.
Referenced by draw_image_seq().
struct ImBuf* make_zebra_view_from_ibuf (struct ImBuf * ibuf, float perc) [read]
Definition at line 423 of file sequencer_scopes.c.
References draw_zebra_byte(), draw_zebra_float(), IB_rect, IMB_allocImBuf(), ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by draw_image_seq().
void recurs_sel_seq (struct Sequence * seqm)
Definition at line 473 of file sequencer_edit.c.
References ListBase::first, Sequence::flag, Sequence::next, recurs_sel_seq(), SELECT, SEQ_ALLSEL, SEQ_LEFTSEL, SEQ_RIGHTSEL, and Sequence::seqbase.
Referenced by recurs_sel_seq(), select_linked_time(), select_more_less_seq__internal(), select_single_seq(), select_surrounding_handles(), sequencer_borderselect_exec(), sequencer_meta_toggle_exec(), sequencer_select_invoke(), and sequencer_select_linked_pick_invoke().
int seq_effect_find_selected (struct Scene * scene, struct Sequence * activeseq, int type, struct Sequence ** selseq1, struct Sequence ** selseq2, struct Sequence ** selseq3, const char ** error_str)
Definition at line 490 of file sequencer_edit.c.
References FALSE, ListBase::first, get_sequence_effect_num_inputs(), NULL, SELECT, seq_active_get(), seq_give_editing(), SEQ_SOUND, and Editing::seqbasep.
Referenced by sequencer_add_effect_strip_exec(), and sequencer_reassign_inputs_exec().
void seq_rectf (struct Sequence * seq, struct rctf * rectf)
Definition at line 224 of file sequencer_edit.c.
References Sequence::enddisp, Sequence::endstill, Sequence::len, Sequence::machine, SEQ_STRIP_OFSBOTTOM, SEQ_STRIP_OFSTOP, Sequence::start, Sequence::startdisp, Sequence::startstill, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by sequencer_borderselect_exec().
void seq_reset_imageofs (struct SpaceSeq * sseq)
Referenced by sequencer_view_all_preview_exec().
int sequencer_edit_poll (struct bContext * C)
Definition at line 1001 of file sequencer_edit.c.
References CTX_data_scene(), FALSE, NULL, and seq_give_editing().
Referenced by SEQUENCER_OT_copy(), SEQUENCER_OT_cut(), SEQUENCER_OT_delete(), SEQUENCER_OT_images_separate(), SEQUENCER_OT_lock(), SEQUENCER_OT_meta_make(), SEQUENCER_OT_meta_separate(), SEQUENCER_OT_meta_toggle(), SEQUENCER_OT_mute(), SEQUENCER_OT_next_edit(), SEQUENCER_OT_offset_clear(), SEQUENCER_OT_previous_edit(), SEQUENCER_OT_refresh_all(), SEQUENCER_OT_reload(), SEQUENCER_OT_rendersize(), SEQUENCER_OT_select_active_side(), SEQUENCER_OT_select_all(), SEQUENCER_OT_select_grouped(), SEQUENCER_OT_select_handles(), SEQUENCER_OT_select_inverse(), SEQUENCER_OT_select_less(), SEQUENCER_OT_select_linked(), SEQUENCER_OT_select_more(), SEQUENCER_OT_snap(), SEQUENCER_OT_swap(), SEQUENCER_OT_unlock(), and SEQUENCER_OT_unmute().
struct ARegion* sequencer_has_buttons_region (struct ScrArea * sa) [read]
Definition at line 63 of file space_sequencer.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_RIGHT, RGN_FLAG_HIDDEN, RGN_TYPE_HEADER, and RGN_TYPE_UI.
Referenced by sequencer_properties().
void sequencer_keymap (struct wmKeyConfig * keyconf)
Definition at line 119 of file sequencer_ops.c.
References AKEY, BKEY, CKEY, DELKEY, DKEY, ED_marker_keymap_animedit_conflictfree(), EIGHTKEY, FALSE, FIVEKEY, FOURKEY, GKEY, HKEY, HOMEKEY, i, IKEY, KKEY, KM_ALT, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTARROWKEY, LKEY, NINEKEY, NKEY, OKEY, ONEKEY, PAD1, PAD2, PAD4, PAD8, PADMINUS, PADPERIOD, PADPLUSKEY, PAGEDOWNKEY, PAGEUPKEY, wmKeyMapItem::ptr, RIGHTARROWKEY, RKEY, RNA_boolean_set(), RNA_enum_set(), RNA_float_set(), RNA_int_set(), RNA_string_set(), SEL_INVERT, SEL_TOGGLE, SELECTMOUSE, SEQ_CUT_HARD, SEQ_CUT_SOFT, SEQ_SIDE_LEFT, SEQ_SIDE_RIGHT, SEVENKEY, SIXKEY, SKEY, SPACE_SEQ, TABKEY, THREEKEY, transform_keymap_for_space(), TRUE, TWOKEY, VKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), XKEY, YKEY, and ZEROKEY.
Referenced by ED_spacetype_sequencer().
void sequencer_operatortypes (void)
Definition at line 55 of file sequencer_ops.c.
References SEQUENCER_OT_change_effect_input(), SEQUENCER_OT_change_effect_type(), SEQUENCER_OT_change_path(), SEQUENCER_OT_copy(), SEQUENCER_OT_cut(), SEQUENCER_OT_delete(), SEQUENCER_OT_duplicate(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_images_separate(), SEQUENCER_OT_lock(), SEQUENCER_OT_meta_make(), SEQUENCER_OT_meta_separate(), SEQUENCER_OT_meta_toggle(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_mute(), SEQUENCER_OT_next_edit(), SEQUENCER_OT_offset_clear(), SEQUENCER_OT_paste(), SEQUENCER_OT_previous_edit(), SEQUENCER_OT_properties(), SEQUENCER_OT_reassign_inputs(), SEQUENCER_OT_rebuild_proxy(), SEQUENCER_OT_refresh_all(), SEQUENCER_OT_reload(), SEQUENCER_OT_rendersize(), SEQUENCER_OT_scene_strip_add(), SEQUENCER_OT_select(), SEQUENCER_OT_select_active_side(), SEQUENCER_OT_select_all(), SEQUENCER_OT_select_border(), SEQUENCER_OT_select_grouped(), SEQUENCER_OT_select_handles(), SEQUENCER_OT_select_less(), SEQUENCER_OT_select_linked(), SEQUENCER_OT_select_linked_pick(), SEQUENCER_OT_select_more(), SEQUENCER_OT_snap(), SEQUENCER_OT_sound_strip_add(), SEQUENCER_OT_swap(), SEQUENCER_OT_swap_data(), SEQUENCER_OT_swap_inputs(), SEQUENCER_OT_unlock(), SEQUENCER_OT_unmute(), SEQUENCER_OT_view_all(), SEQUENCER_OT_view_all_preview(), SEQUENCER_OT_view_ghost_border(), SEQUENCER_OT_view_selected(), SEQUENCER_OT_view_toggle(), SEQUENCER_OT_view_zoom_ratio(), and WM_operatortype_append().
Referenced by ED_spacetype_sequencer().
void SEQUENCER_OT_change_effect_input (struct wmOperatorType * ot)
Definition at line 2911 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), sequencer_change_effect_input_exec(), sequencer_effect_poll(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_change_effect_type (struct wmOperatorType * ot)
Definition at line 2971 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), SEQ_CROSS, sequencer_change_effect_type_exec(), sequencer_effect_poll(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_change_path (struct wmOperatorType * ot)
Definition at line 3077 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, IMAGEFILE, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_change_path_exec(), sequencer_change_path_invoke(), sequencer_strip_has_path_poll(), WM_FILESEL_DIRECTORY, WM_FILESEL_FILEPATH, WM_FILESEL_FILES, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_copy (struct wmOperatorType * ot)
Definition at line 2641 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, sequencer_copy_exec(), and sequencer_edit_poll().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_cut (struct wmOperatorType * ot)
Definition at line 1532 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_int(), SEQ_CUT_SOFT, SEQ_SIDE_BOTH, sequencer_cut_exec(), sequencer_cut_invoke(), sequencer_edit_poll(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_delete (struct wmOperatorType * ot)
Definition at line 1674 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_delete_exec(), sequencer_edit_poll(), and WM_operator_confirm().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_duplicate (struct wmOperatorType * ot)
Definition at line 1602 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), sequencer_add_duplicate_exec(), sequencer_add_duplicate_invoke(), wmOperatorType::srna, TFM_TRANSLATION, and transform_mode_types.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_effect_strip_add (struct wmOperatorType * ot)
Definition at line 827 of file sequencer_add.c.
References wmOperatorType::description, ED_operator_scene_editable(), wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_float_vector(), SEQ_CROSS, SEQPROP_ENDFRAME, SEQPROP_STARTFRAME, sequencer_add_effect_strip_exec(), sequencer_add_effect_strip_invoke(), sequencer_generic_props__internal(), sequencer_prop_effect_types, wmOperatorType::srna, WM_FILESEL_FILEPATH, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_image_strip_add (struct wmOperatorType * ot)
Definition at line 650 of file sequencer_add.c.
References wmOperatorType::description, ED_operator_scene_editable(), wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, IMAGEFILE, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, SEQPROP_ENDFRAME, SEQPROP_STARTFRAME, sequencer_add_image_strip_exec(), sequencer_add_image_strip_invoke(), sequencer_generic_props__internal(), WM_FILESEL_DIRECTORY, WM_FILESEL_FILES, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_images_separate (struct wmOperatorType * ot)
Definition at line 1820 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), sequencer_edit_poll(), sequencer_separate_images_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_lock (struct wmOperatorType * ot)
Definition at line 1235 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_lock_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_meta_make (struct wmOperatorType * ot)
Definition at line 1958 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), sequencer_meta_make_exec(), and WM_operator_confirm().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_meta_separate (struct wmOperatorType * ot)
Definition at line 2029 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), sequencer_meta_separate_exec(), and WM_operator_confirm().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_meta_toggle (struct wmOperatorType * ot)
Definition at line 1892 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_meta_toggle_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_movie_strip_add (struct wmOperatorType * ot)
Definition at line 492 of file sequencer_add.c.
References wmOperatorType::description, ED_operator_scene_editable(), wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), SEQPROP_STARTFRAME, sequencer_add_movie_strip_exec(), sequencer_add_movie_strip_invoke(), sequencer_generic_props__internal(), wmOperatorType::srna, TRUE, WM_FILESEL_FILEPATH, WM_FILESEL_FILES, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_movieclip_strip_add (struct wmOperatorType * ot)
Definition at line 375 of file sequencer_add.c.
References wmOperatorType::description, DummyRNA_NULL_items, ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), RNA_movieclip_itemf(), SEQPROP_STARTFRAME, sequencer_add_movieclip_strip_exec(), sequencer_add_movieclip_strip_invoke(), sequencer_generic_props__internal(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_mute (struct wmOperatorType * ot)
Definition at line 1152 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), sequencer_edit_poll(), sequencer_mute_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_next_edit (struct wmOperatorType * ot)
Definition at line 2369 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_next_edit_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_offset_clear (struct wmOperatorType * ot)
Definition at line 1727 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_offset_clear_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_paste (struct wmOperatorType * ot)
Definition at line 2709 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and sequencer_paste_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_previous_edit (struct wmOperatorType * ot)
Definition at line 2399 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_previous_edit_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_properties (struct wmOperatorType * ot)
Definition at line 64 of file sequencer_buttons.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and sequencer_properties().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_reassign_inputs (struct wmOperatorType * ot)
Definition at line 1399 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_effect_poll(), and sequencer_reassign_inputs_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_rebuild_proxy (struct wmOperatorType * ot)
Definition at line 2846 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, and sequencer_rebuild_proxy_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_refresh_all (struct wmOperatorType * ot)
Definition at line 1342 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_refresh_all_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_reload (struct wmOperatorType * ot)
Definition at line 1308 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_boolean(), RNA_def_property_flag(), sequencer_edit_poll(), sequencer_reload_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_rendersize (struct wmOperatorType * ot)
Definition at line 2562 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_rendersize_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_scene_strip_add (struct wmOperatorType * ot)
Definition at line 276 of file sequencer_add.c.
References wmOperatorType::description, DummyRNA_NULL_items, ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), RNA_scene_itemf(), SEQPROP_STARTFRAME, sequencer_add_scene_strip_exec(), sequencer_add_scene_strip_invoke(), sequencer_generic_props__internal(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select (struct wmOperatorType * ot)
Definition at line 532 of file sequencer_select.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), sequencer_select_invoke(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_active_side (struct wmOperatorType * ot)
Definition at line 826 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, prop_side_types, RNA_def_enum(), SEQ_SIDE_BOTH, sequencer_edit_poll(), sequencer_select_active_side_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_all (struct wmOperatorType * ot)
Definition at line 262 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_de_select_all_exec(), sequencer_edit_poll(), and WM_operator_properties_select_all().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_border (struct wmOperatorType * ot)
Definition at line 895 of file sequencer_select.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_borderselect_exec(), TRUE, WM_border_select_cancel(), WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_grouped (struct wmOperatorType * ot)
Definition at line 1179 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), sequencer_edit_poll(), sequencer_select_grouped_exec(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_handles (struct wmOperatorType * ot)
Definition at line 789 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, prop_side_types, RNA_def_enum(), SEQ_SIDE_BOTH, sequencer_edit_poll(), sequencer_select_handles_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_inverse (struct wmOperatorType * ot)
Definition at line 302 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_select_inverse_exec().
void SEQUENCER_OT_select_less (struct wmOperatorType * ot)
Definition at line 654 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_select_less_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_linked (struct wmOperatorType * ot)
Definition at line 739 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_select_linked_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_linked_pick (struct wmOperatorType * ot)
Definition at line 704 of file sequencer_select.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), sequencer_select_linked_pick_invoke(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_more (struct wmOperatorType * ot)
Definition at line 623 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_select_more_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_snap (struct wmOperatorType * ot)
Definition at line 1105 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), sequencer_edit_poll(), sequencer_snap_exec(), sequencer_snap_invoke(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_sound_strip_add (struct wmOperatorType * ot)
Definition at line 546 of file sequencer_add.c.
References wmOperatorType::description, ED_operator_scene_editable(), wmOperatorType::exec, FALSE, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), SEQPROP_STARTFRAME, sequencer_add_sound_strip_exec(), sequencer_add_sound_strip_invoke(), sequencer_generic_props__internal(), SOUNDFILE, wmOperatorType::srna, WM_FILESEL_FILEPATH, WM_FILESEL_FILES, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_swap (struct wmOperatorType * ot)
Definition at line 2503 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), SEQ_SIDE_RIGHT, sequencer_edit_poll(), sequencer_swap_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_swap_data (struct wmOperatorType * ot)
Definition at line 2760 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and sequencer_swap_data_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_swap_inputs (struct wmOperatorType * ot)
Definition at line 1435 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_effect_poll(), and sequencer_swap_inputs_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_unlock (struct wmOperatorType * ot)
Definition at line 1268 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_unlock_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_unmute (struct wmOperatorType * ot)
Definition at line 1199 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), sequencer_edit_poll(), sequencer_unmute_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_update_strip_length (struct wmOperatorType * ot)
void SEQUENCER_OT_view_all (struct wmOperatorType * ot)
Definition at line 2062 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, and sequencer_view_all_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_view_all_preview (struct wmOperatorType * ot)
Definition at line 2128 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, and sequencer_view_all_preview_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_view_ghost_border (struct wmOperatorType * ot)
Definition at line 2817 of file sequencer_edit.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, wmOperatorType::poll, sequencer_view_poll(), view_ghost_border_exec(), WM_border_select_cancel(), WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_view_selected (struct wmOperatorType * ot)
Definition at line 2283 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, and sequencer_view_selected_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_view_toggle (struct wmOperatorType * ot)
Definition at line 2203 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, and sequencer_view_toggle_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_view_zoom_ratio (struct wmOperatorType * ot)
Definition at line 2164 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_float(), sequencer_view_zoom_ratio_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
int sequencer_strip_has_path_poll (struct bContext * C)
Definition at line 1014 of file sequencer_edit.c.
References Editing::act_seq, CTX_data_scene(), FALSE, NULL, seq_give_editing(), and SEQ_HAS_PATH.
Referenced by SEQUENCER_OT_change_path().
int sequencer_strip_poll (struct bContext * C)
int sequencer_view_poll (struct bContext * C)
Definition at line 1021 of file sequencer_edit.c.
References CTX_data_scene(), CTX_wm_space_seq(), FALSE, SpaceSeq::mainb, SEQ_DRAW_IMG_IMBUF, and seq_give_editing().
Referenced by SEQUENCER_OT_view_ghost_border().
Variable Documentation
EnumPropertyItem prop_side_types[]
Definition at line 103 of file sequencer_edit.c.
Referenced by SEQUENCER_OT_select_active_side(), and SEQUENCER_OT_select_handles().
EnumPropertyItem sequencer_prop_effect_types[]
Definition at line 81 of file sequencer_edit.c.
Referenced by SEQUENCER_OT_effect_strip_add().