Blender: bmo_removedoubles.c File Reference
bmo_removedoubles.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_array.h"
#include "BKE_customdata.h"
#include "bmesh.h"
#include "intern/bmesh_private.h"
#include "intern/bmesh_operators_private.h"
Defines
#define ELE_DEL 1
#define EDGE_COL 2
#define FACE_MARK 2
#define VERT_TESTED 1
#define VERT_DOUBLE 2
#define VERT_TARGET 4
#define VERT_KEEP 8
#define VERT_MARK 16
#define VERT_IN 32
#define EDGE_MARK 1
Functions
static void remdoubles_splitface (BMFace *f, BMesh *bm, BMOperator *op)
void bmo_weldverts_exec (BMesh *bm, BMOperator *op)
static int vergaverco (const void *e1, const void *e2)
void bmo_pointmerge_facedata_exec (BMesh *bm, BMOperator *op)
void bmo_vert_average_facedata_exec (BMesh *bm, BMOperator *op)
void bmo_pointmerge_exec (BMesh *bm, BMOperator *op)
void bmo_collapse_exec (BMesh *bm, BMOperator *op)
static void bmo_collapsecon_do_layer (BMesh *bm, BMOperator *op, int layer)
void bmo_collapse_uvs_exec (BMesh *bm, BMOperator *op)
void bmesh_finddoubles_common (BMesh *bm, BMOperator *op, BMOperator *optarget, const char *targetmapname)
void bmo_removedoubles_exec (BMesh *bm, BMOperator *op)
void bmo_finddoubles_exec (BMesh *bm, BMOperator *op)
void bmo_automerge_exec (BMesh *bm, BMOperator *op)
Detailed Description
Definition in file bmo_removedoubles.c.
Define Documentation
#define EDGE_COL 2
Definition at line 70 of file bmo_removedoubles.c.
Referenced by bmo_weldverts_exec().
#define EDGE_MARK 1
Definition at line 254 of file bmo_removedoubles.c.
Referenced by bmo_collapse_exec(), and bmo_collapsecon_do_layer().
#define ELE_DEL 1
Definition at line 69 of file bmo_removedoubles.c.
Referenced by bmo_weldverts_exec().
#define FACE_MARK 2
Definition at line 71 of file bmo_removedoubles.c.
Referenced by bmo_weldverts_exec().
#define VERT_DOUBLE 2
Definition at line 248 of file bmo_removedoubles.c.
Referenced by bmesh_finddoubles_common().
#define VERT_IN 32
Definition at line 252 of file bmo_removedoubles.c.
Referenced by bmo_automerge_exec().
#define VERT_KEEP 8
Definition at line 250 of file bmo_removedoubles.c.
Referenced by bmesh_finddoubles_common(), and bmo_automerge_exec().
#define VERT_MARK 16
Definition at line 251 of file bmo_removedoubles.c.
#define VERT_TARGET 4
Definition at line 249 of file bmo_removedoubles.c.
Referenced by bmesh_finddoubles_common().
#define VERT_TESTED 1
Definition at line 247 of file bmo_removedoubles.c.
Function Documentation
void bmesh_finddoubles_common (BMesh * bm, BMOperator * op, BMOperator * optarget, const char * targetmapname)
Definition at line 490 of file bmo_removedoubles.c.
References BLI_array_count, BLI_array_declare, BLI_array_free, BLI_array_growone, BM_VERT, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_iter_new(), BMO_slot_buffer_flag_enable(), BMO_slot_exists(), BMO_slot_float_get(), BMO_slot_map_ptr_insert(), BMVert::co, compare_len_v3v3(), i, len(), NULL, SWAP, vergaverco(), VERT_DOUBLE, VERT_KEEP, and VERT_TARGET.
Referenced by bmo_finddoubles_exec(), and bmo_removedoubles_exec().
void bmo_automerge_exec (BMesh * bm, BMOperator * op)
Definition at line 576 of file bmo_removedoubles.c.
References BM_ITER_MESH, BM_VERT, BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_op_initf(), BMO_slot_buffer_flag_enable(), BMO_slot_copy(), VERT_IN, and VERT_KEEP.
void bmo_collapse_exec (BMesh * bm, BMOperator * op)
Definition at line 367 of file bmo_removedoubles.c.
References add_v3_v3v3(), BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growone, BM_EDGE, BM_EDGES_OF_MESH, BM_ITER_MESH, BMO_elem_flag_test, BMO_op_callf(), BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_slot_buffer_flag_enable(), BMO_slot_map_ptr_insert(), BMW_begin(), BMW_end(), BMW_FLAG_NOP, BMW_init(), BMW_MASK_NOP, BMW_NIL_LAY, BMW_SHELL, BMW_step(), copy_v3_v3(), DO_MINMAX, EDGE_MARK, i, INIT_MINMAX, max, min, mul_v3_fl(), NULL, and BMEdge::v1.
void bmo_collapse_uvs_exec (BMesh * bm, BMOperator * op)
Definition at line 480 of file bmo_removedoubles.c.
References bmo_collapsecon_do_layer(), CustomData_layer_has_math(), i, BMesh::ldata, and CustomData::totlayer.
static void bmo_collapsecon_do_layer (BMesh * bm, BMOperator * op, int layer) [static]
Definition at line 426 of file bmo_removedoubles.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growone, BM_ALL, BM_EDGE, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMO_elem_flag_test, BMO_mesh_flag_disable_all(), BMO_slot_buffer_flag_enable(), BMW_begin(), BMW_end(), BMW_FLAG_NOP, BMW_init(), BMW_LOOPDATA_ISLAND, BMW_MASK_NOP, BMW_step(), CustomData_bmesh_get_layer_n(), CustomData_data_add(), CustomData_data_copy_value(), CustomData_data_dominmax(), CustomData_data_initminmax(), CustomData_data_multiply(), BMLoop::e, EDGE_MARK, i, CustomData::layers, BMesh::ldata, max, min, NULL, and CustomDataLayer::type.
Referenced by bmo_collapse_uvs_exec().
void bmo_finddoubles_exec (BMesh * bm, BMOperator * op)
Definition at line 571 of file bmo_removedoubles.c.
References bmesh_finddoubles_common().
void bmo_pointmerge_exec (BMesh * bm, BMOperator * op)
Definition at line 341 of file bmo_removedoubles.c.
References BM_VERT, BMO_ITER, BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_slot_map_ptr_insert(), BMO_slot_vec_get(), BMVert::co, copy_v3_v3(), and NULL.
void bmo_pointmerge_facedata_exec (BMesh * bm, BMOperator * op)
Definition at line 256 of file bmo_removedoubles.c.
References BM_ITER_ELEM, BM_LOOPS_OF_VERT, BM_VERT, BM_vert_face_count(), BMO_ITER, BMO_iter_new(), CustomData_bmesh_copy_data(), CustomData_bmesh_get_layer_n(), CustomData_data_add(), CustomData_data_multiply(), CustomData_layer_has_math(), BMHeader::data, BMLoop::head, i, CustomData::layers, BMesh::ldata, NULL, CustomData::totlayer, and CustomDataLayer::type.
void bmo_removedoubles_exec (BMesh * bm, BMOperator * op)
Definition at line 560 of file bmo_removedoubles.c.
References bmesh_finddoubles_common(), BMO_op_exec(), BMO_op_finish(), and BMO_op_init().
void bmo_vert_average_facedata_exec (BMesh * bm, BMOperator * op)
Definition at line 304 of file bmo_removedoubles.c.
References BM_ITER_ELEM, BM_LOOPS_OF_VERT, BM_VERT, BMO_ITER, CustomData_bmesh_get_layer_n(), CustomData_data_add(), CustomData_data_copy_value(), CustomData_data_dominmax(), CustomData_data_initminmax(), CustomData_data_multiply(), CustomData_layer_has_math(), BMHeader::data, BMLoop::head, i, CustomData::layers, BMesh::ldata, max, min, CustomData::totlayer, and CustomDataLayer::type.
void bmo_weldverts_exec (BMesh * bm, BMOperator * op)
Definition at line 99 of file bmo_removedoubles.c.
References BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growone, BM_edge_create(), BM_edge_exists(), BM_EDGES_OF_MESH, BM_elem_attrs_copy(), BM_elem_flag_merge, BM_elem_index_get, BM_elem_index_set, BM_FACE, BM_face_create_ngon(), BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_op_callf(), BMO_slot_map_ptr_get(), DEL_ONLYTAGGED, BMLoop::e, EDGE_COL, ELE_DEL, BMesh::elem_index_dirty, FACE_MARK, BMFace::len, BMLoop::next, NULL, remdoubles_splitface(), TRUE, BMLoop::v, BMEdge::v1, and BMEdge::v2.
static void remdoubles_splitface (BMFace * f, BMesh * bm, BMOperator * op) [static]
Definition at line 39 of file bmo_removedoubles.c.
References BM_face_split(), BM_ITER_ELEM, BM_LOOPS_OF_FACE, BM_vert_in_face(), BMO_slot_map_ptr_get(), FALSE, BMLoop::next, NULL, BMLoop::prev, split(), TRUE, and BMLoop::v.
Referenced by bmo_weldverts_exec().
static int vergaverco (const void * e1, const void * e2) [static]
Definition at line 236 of file bmo_removedoubles.c.
References BMVert::co.
Referenced by bmesh_finddoubles_common().