Blender: paint_intern.h File Reference
paint_intern.h File Reference
sculpt and paint
Typedefs
typedef int(* StrokeGetLocation)(struct bContext *C, float location[3], float mouse[2])
typedef int(* StrokeTestStart)(struct bContext *C, struct wmOperator *op, struct wmEvent *event)
typedef void(* StrokeUpdateStep)(struct bContext *C, struct PaintStroke *stroke, struct PointerRNA *itemptr)
typedef void(* StrokeDone)(struct bContext *C, struct PaintStroke *stroke)
typedef enum BrushStrokeMode BrushStrokeMode
typedef void(* UndoRestoreCb)(struct bContext *C, struct ListBase *lb)
typedef void(* UndoFreeCb)(struct ListBase *lb)
Enumerations
enum BrushStrokeMode { BRUSH_STROKE_NORMAL, BRUSH_STROKE_INVERT, BRUSH_STROKE_SMOOTH }
enum PartialVisAction { PARTIALVIS_HIDE, PARTIALVIS_SHOW }
enum PartialVisArea { PARTIALVIS_INSIDE, PARTIALVIS_OUTSIDE, PARTIALVIS_ALL }
Functions
struct PaintStroke * paint_stroke_new (struct bContext *C, StrokeGetLocation get_location, StrokeTestStart test_start, StrokeUpdateStep update_step, StrokeDone done, int event_type)
void paint_stroke_free (struct PaintStroke *stroke)
int paint_space_stroke_enabled (struct Brush *br)
int paint_stroke_modal (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int paint_stroke_exec (struct bContext *C, struct wmOperator *op)
int paint_stroke_cancel (struct bContext *C, struct wmOperator *op)
struct ViewContext * paint_stroke_view_context (struct PaintStroke *stroke)
void * paint_stroke_mode_data (struct PaintStroke *stroke)
void paint_stroke_set_mode_data (struct PaintStroke *stroke, void *mode_data)
int paint_poll (struct bContext *C)
void paint_cursor_start (struct bContext *C, int(*poll)(struct bContext *C))
int weight_paint_poll (struct bContext *C)
int weight_paint_mode_poll (struct bContext *C)
int vertex_paint_poll (struct bContext *C)
int vertex_paint_mode_poll (struct bContext *C)
void vpaint_fill (struct Object *ob, unsigned int paintcol)
void wpaint_fill (struct VPaint *wp, struct Object *ob, float paintweight)
void PAINT_OT_weight_paint_toggle (struct wmOperatorType *ot)
void PAINT_OT_weight_paint (struct wmOperatorType *ot)
void PAINT_OT_weight_set (struct wmOperatorType *ot)
void PAINT_OT_weight_from_bones (struct wmOperatorType *ot)
void PAINT_OT_weight_sample (struct wmOperatorType *ot)
void PAINT_OT_weight_sample_group (struct wmOperatorType *ot)
void PAINT_OT_vertex_paint_toggle (struct wmOperatorType *ot)
void PAINT_OT_vertex_paint (struct wmOperatorType *ot)
unsigned int vpaint_get_current_col (struct VPaint *vp)
int image_texture_paint_poll (struct bContext *C)
void PAINT_OT_image_paint (struct wmOperatorType *ot)
void PAINT_OT_grab_clone (struct wmOperatorType *ot)
void PAINT_OT_sample_color (struct wmOperatorType *ot)
void PAINT_OT_clone_cursor_set (struct wmOperatorType *ot)
void PAINT_OT_texture_paint_toggle (struct wmOperatorType *ot)
void PAINT_OT_project_image (struct wmOperatorType *ot)
void PAINT_OT_image_from_view (struct wmOperatorType *ot)
int uv_sculpt_poll (struct bContext *C)
void SCULPT_OT_uv_sculpt_stroke (struct wmOperatorType *ot)
int paint_convert_bb_to_rect (struct rcti *rect, const float bb_min[3], const float bb_max[3], const struct ARegion *ar, struct RegionView3D *rv3d, struct Object *ob)
void paint_calc_redraw_planes (float planes[4][4], const struct ARegion *ar, struct RegionView3D *rv3d, struct Object *ob, const struct rcti *screen_rect)
void projectf (struct bglMats *mats, const float v[3], float p[2])
float paint_calc_object_space_radius (struct ViewContext *vc, const float center[3], float pixel_radius)
float paint_get_tex_pixel (struct Brush *br, float u, float v)
int imapaint_pick_face (struct ViewContext *vc, const int mval[2], unsigned int *index, unsigned int totface)
void imapaint_pick_uv (struct Scene *scene, struct Object *ob, unsigned int faceindex, const int xy[2], float uv[2])
void paint_sample_color (struct Scene *scene, struct ARegion *ar, int x, int y)
void BRUSH_OT_curve_preset (struct wmOperatorType *ot)
void PAINT_OT_face_select_linked (struct wmOperatorType *ot)
void PAINT_OT_face_select_linked_pick (struct wmOperatorType *ot)
void PAINT_OT_face_select_all (struct wmOperatorType *ot)
void PAINT_OT_face_select_inverse (struct wmOperatorType *ot)
void PAINT_OT_face_select_hide (struct wmOperatorType *ot)
void PAINT_OT_face_select_reveal (struct wmOperatorType *ot)
void PAINT_OT_vert_select_all (struct wmOperatorType *ot)
void PAINT_OT_vert_select_inverse (struct wmOperatorType *ot)
int vert_paint_poll (struct bContext *C)
int mask_paint_poll (struct bContext *C)
int facemask_paint_poll (struct bContext *C)
void undo_paint_push_begin (int type, const char *name, UndoRestoreCb restore, UndoFreeCb free)
struct ListBase * undo_paint_push_get_list (int type)
void undo_paint_push_count_alloc (int type, int size)
void undo_paint_push_end (int type)
void PAINT_OT_hide_show (struct wmOperatorType *ot)
Detailed Description
Definition in file paint_intern.h.
Typedef Documentation
typedef enum BrushStrokeMode BrushStrokeMode
typedef void(* StrokeDone)(struct bContext *C, struct PaintStroke *stroke)
Definition at line 56 of file paint_intern.h.
typedef int(* StrokeGetLocation)(struct bContext *C, float location[3], float mouse[2])
Definition at line 53 of file paint_intern.h.
typedef int(* StrokeTestStart)(struct bContext *C, struct wmOperator *op, struct wmEvent *event)
Definition at line 54 of file paint_intern.h.
typedef void(* StrokeUpdateStep)(struct bContext *C, struct PaintStroke *stroke, struct PointerRNA *itemptr)
Definition at line 55 of file paint_intern.h.
typedef void(* UndoFreeCb)(struct ListBase *lb)
Definition at line 164 of file paint_intern.h.
typedef void(* UndoRestoreCb)(struct bContext *C, struct ListBase *lb)
Definition at line 163 of file paint_intern.h.
Enumeration Type Documentation
enum BrushStrokeMode
Enumerator:
BRUSH_STROKE_NORMAL
BRUSH_STROKE_INVERT
BRUSH_STROKE_SMOOTH
Definition at line 156 of file paint_intern.h.
enum PartialVisAction
Enumerator:
PARTIALVIS_HIDE
PARTIALVIS_SHOW
Definition at line 173 of file paint_intern.h.
enum PartialVisArea
Enumerator:
PARTIALVIS_INSIDE
PARTIALVIS_OUTSIDE
PARTIALVIS_ALL
Definition at line 178 of file paint_intern.h.
Function Documentation
void BRUSH_OT_curve_preset (struct wmOperatorType * ot)
Definition at line 373 of file paint_utils.c.
References brush_curve_preset_exec(), brush_curve_preset_poll(), CURVE_PRESET_LINE, CURVE_PRESET_MAX, CURVE_PRESET_ROOT, CURVE_PRESET_ROUND, CURVE_PRESET_SHARP, CURVE_PRESET_SMOOTH, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, NULL, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_paint().
int facemask_paint_poll (struct bContext * C)
Definition at line 5636 of file paint_image.c.
References CTX_data_active_object(), and paint_facesel_test().
Referenced by ED_keymap_paint(), PAINT_OT_face_select_all(), PAINT_OT_face_select_hide(), PAINT_OT_face_select_inverse(), PAINT_OT_face_select_linked(), PAINT_OT_face_select_linked_pick(), and PAINT_OT_face_select_reveal().
int image_texture_paint_poll (struct bContext * C)
Definition at line 5626 of file paint_image.c.
References image_paint_poll(), and texture_paint_poll().
Referenced by ED_keymap_paint().
int imapaint_pick_face (struct ViewContext * vc, const int mval[2], unsigned int * index, unsigned int totface)
Definition at line 318 of file paint_utils.c.
References view3d_sample_backbuf().
Referenced by imapaint_paint_stroke().
void imapaint_pick_uv (struct Scene * scene, struct Object * ob, unsigned int faceindex, const int xy[2], float uv[2])
Definition at line 252 of file paint_utils.c.
References CD_MASK_BAREMESH, CD_MTFACE, CD_ORIGINDEX, co, fabs(), DerivedMesh::getNumTessFaces, DerivedMesh::getTessFace, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVert, imapaint_tri_weights(), mesh_get_derived_final(), p, DerivedMesh::release, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by imapaint_paint_stroke().
int mask_paint_poll (struct bContext * C)
Definition at line 5646 of file paint_image.c.
References CTX_data_active_object(), paint_facesel_test(), and paint_vertsel_test().
Referenced by PAINT_OT_weight_set().
float paint_calc_object_space_radius (struct ViewContext * vc, const float center[3], float pixel_radius)
Definition at line 154 of file paint_utils.c.
References ViewContext::ar, ED_view3d_win_to_delta(), fabsf, initgrabz(), len_v3(), mat4_to_scale(), mul_v3_m4v3(), ViewContext::obact, Object::obmat, and ViewContext::rv3d.
Referenced by paint_cursor_on_hit(), and sculpt_update_cache_variants().
void paint_calc_redraw_planes (float planes[4][4], const struct ARegion * ar, struct RegionView3D * rv3d, struct Object * ob, const struct rcti * screen_rect)
Referenced by sculpt_get_redraw_planes().
int paint_convert_bb_to_rect (struct rcti * rect, const float bb_min[3], const float bb_max[3], const struct ARegion * ar, struct RegionView3D * rv3d, struct Object * ob)
Referenced by sculpt_get_redraw_rect().
void paint_cursor_start (struct bContext * C, int(*)(struct bContext *C) poll)
float paint_get_tex_pixel (struct Brush * br, float u, float v)
Definition at line 175 of file paint_utils.c.
References co, Brush::mtex, multitex_ext(), NULL, TexResult::ta, TexResult::tb, MTex::tex, TEX_RGB, TexResult::tg, TexResult::tin, and TexResult::tr.
Referenced by load_tex(), and tex_strength().
void PAINT_OT_clone_cursor_set (struct wmOperatorType * ot)
Definition at line 5521 of file paint_image.c.
References wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, image_paint_3d_poll(), wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_vector(), set_clone_cursor_exec(), set_clone_cursor_invoke(), and wmOperatorType::srna.
Referenced by ED_operatortypes_paint().
void PAINT_OT_face_select_all (struct wmOperatorType * ot)
Definition at line 447 of file paint_utils.c.
References wmOperatorType::description, wmOperatorType::exec, face_select_all_exec(), facemask_paint_poll(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_properties_select_all().
Referenced by ED_operatortypes_paint().
void PAINT_OT_face_select_hide (struct wmOperatorType * ot)
Definition at line 534 of file paint_utils.c.
References wmOperatorType::description, wmOperatorType::exec, face_select_hide_exec(), facemask_paint_poll(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_paint().
void PAINT_OT_face_select_inverse (struct wmOperatorType * ot)
Definition at line 513 of file paint_utils.c.
References wmOperatorType::description, wmOperatorType::exec, face_select_inverse_exec(), facemask_paint_poll(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_paint().
void PAINT_OT_face_select_linked (struct wmOperatorType * ot)
Definition at line 403 of file paint_utils.c.
References wmOperatorType::description, wmOperatorType::exec, facemask_paint_poll(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, paint_select_linked_exec(), and wmOperatorType::poll.
Referenced by ED_operatortypes_paint().
void PAINT_OT_face_select_linked_pick (struct wmOperatorType * ot)
Definition at line 423 of file paint_utils.c.
References wmOperatorType::description, facemask_paint_poll(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, paint_select_linked_pick_invoke(), wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_paint().
void PAINT_OT_face_select_reveal (struct wmOperatorType * ot)
Definition at line 556 of file paint_utils.c.
References wmOperatorType::description, wmOperatorType::exec, face_select_reveal_exec(), facemask_paint_poll(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_paint().
void PAINT_OT_grab_clone (struct wmOperatorType * ot)
Definition at line 5388 of file paint_image.c.
References wmOperatorType::cancel, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, grab_clone_cancel(), grab_clone_exec(), grab_clone_invoke(), grab_clone_modal(), wmOperatorType::idname, image_paint_2d_clone_poll(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_vector(), and wmOperatorType::srna.
Referenced by ED_operatortypes_paint().
void PAINT_OT_hide_show (struct wmOperatorType * ot)
Definition at line 353 of file paint_hide.c.
References wmOperatorType::exec, wmOperatorType::flag, hide_show_exec(), hide_show_invoke(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OPTYPE_REGISTER, PARTIALVIS_ALL, PARTIALVIS_HIDE, PARTIALVIS_INSIDE, PARTIALVIS_OUTSIDE, PARTIALVIS_SHOW, wmOperatorType::poll, RNA_def_enum(), RNA_def_int(), sculpt_mode_poll(), wmOperatorType::srna, and WM_border_select_modal().
Referenced by ED_operatortypes_paint().
void PAINT_OT_image_from_view (struct wmOperatorType * ot)
Definition at line 5832 of file paint_image.c.
References wmOperatorType::description, ED_operator_region_view3d_active(), wmOperatorType::exec, FILE_MAX, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, RNA_def_string_file_name(), wmOperatorType::srna, and texture_paint_image_from_view_exec().
Referenced by ED_operatortypes_paint().
void PAINT_OT_image_paint (struct wmOperatorType * ot)
Definition at line 5161 of file paint_image.c.
References wmOperatorType::cancel, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_paint_poll(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, paint_cancel(), paint_exec(), paint_invoke(), paint_modal(), wmOperatorType::poll, RNA_def_collection_runtime(), RNA_OperatorStrokeElement, and wmOperatorType::srna.
Referenced by ED_operatortypes_paint().
void PAINT_OT_project_image (struct wmOperatorType * ot)
Definition at line 5751 of file paint_image.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), RNA_image_itemf(), wmOperatorType::srna, texture_paint_camera_project_exec(), and WM_enum_search_invoke().
Referenced by ED_operatortypes_paint().
void PAINT_OT_sample_color (struct wmOperatorType * ot)
Definition at line 5470 of file paint_image.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_paint_sample_color_poll(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int_vector(), sample_color_exec(), sample_color_invoke(), sample_color_modal(), and wmOperatorType::srna.
Referenced by ED_operatortypes_paint().
void PAINT_OT_texture_paint_toggle (struct wmOperatorType * ot)
Definition at line 5603 of file paint_image.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, texture_paint_toggle_exec(), and texture_paint_toggle_poll().
Referenced by ED_operatortypes_paint().
void PAINT_OT_vert_select_all (struct wmOperatorType * ot)
Definition at line 471 of file paint_utils.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vert_paint_poll(), vert_select_all_exec(), and WM_operator_properties_select_all().
Referenced by ED_operatortypes_paint().
void PAINT_OT_vert_select_inverse (struct wmOperatorType * ot)
Definition at line 493 of file paint_utils.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vert_paint_poll(), and vert_select_inverse_exec().
Referenced by ED_operatortypes_paint().
void PAINT_OT_vertex_paint (struct wmOperatorType * ot)
Definition at line 2992 of file paint_vertex.c.
References wmOperatorType::cancel, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, paint_stroke_modal(), wmOperatorType::poll, RNA_def_collection_runtime(), RNA_OperatorStrokeElement, wmOperatorType::srna, vertex_paint_poll(), vpaint_cancel(), and vpaint_invoke().
Referenced by ED_operatortypes_paint().
void PAINT_OT_vertex_paint_toggle (struct wmOperatorType * ot)
Definition at line 2586 of file paint_vertex.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, paint_poll_test(), wmOperatorType::poll, and set_vpaint().
Referenced by ED_operatortypes_paint().
void PAINT_OT_weight_from_bones (struct wmOperatorType * ot)
Definition at line 3036 of file paint_vertex.c.
References ARM_GROUPS_AUTO, ARM_GROUPS_ENVELOPE, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, weight_from_bones_exec(), weight_from_bones_poll(), and WM_menu_invoke().
Referenced by ED_operatortypes_paint().
void PAINT_OT_weight_paint (struct wmOperatorType * ot)
Definition at line 2493 of file paint_vertex.c.
References wmOperatorType::cancel, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, paint_stroke_modal(), wmOperatorType::poll, RNA_def_collection_runtime(), RNA_OperatorStrokeElement, wmOperatorType::srna, weight_paint_poll(), wpaint_cancel(), and wpaint_invoke().
Referenced by ED_operatortypes_paint().
void PAINT_OT_weight_paint_toggle (struct wmOperatorType * ot)
Definition at line 2041 of file paint_vertex.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, paint_poll_test(), wmOperatorType::poll, and set_wpaint().
Referenced by ED_operatortypes_paint().
void PAINT_OT_weight_sample (struct wmOperatorType * ot)
Definition at line 1079 of file paint_vertex.c.
References wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, weight_paint_mode_poll(), and weight_sample_invoke().
Referenced by ED_operatortypes_paint().
void PAINT_OT_weight_sample_group (struct wmOperatorType * ot)
Definition at line 1178 of file paint_vertex.c.
References DummyRNA_DEFAULT_items, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), wmOperatorType::srna, weight_paint_mode_poll(), weight_paint_sample_enum_itemf(), weight_sample_group_exec(), and WM_menu_invoke().
Referenced by ED_operatortypes_paint().
void PAINT_OT_weight_set (struct wmOperatorType * ot)
Definition at line 2523 of file paint_vertex.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, mask_paint_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and weight_paint_set_exec().
Referenced by ED_operatortypes_paint().
int paint_poll (struct bContext * C)
Definition at line 421 of file paint_stroke.c.
References CTX_data_active_object(), CTX_data_scene(), CTX_wm_area(), CTX_wm_region(), p, paint_brush(), paint_get_active(), ARegion::regiontype, RGN_TYPE_WINDOW, SPACE_VIEW3D, and ScrArea::spacetype.
Referenced by paint_stroke_modal(), and sculpt_poll().
void paint_sample_color (struct Scene * scene, struct ARegion * ar, int x, int y)
Definition at line 336 of file paint_utils.c.
References CLAMP(), paint_brush(), paint_get_active(), Brush::rgb, ARegion::winrct, ARegion::winx, ARegion::winy, rcti::xmin, and rcti::ymin.
Referenced by sample_color_exec().
int paint_space_stroke_enabled (struct Brush * br)
Definition at line 285 of file paint_stroke.c.
References BRUSH_ANCHORED, BRUSH_SPACE, ELEM4, Brush::flag, Brush::sculpt_tool, SCULPT_TOOL_GRAB, SCULPT_TOOL_ROTATE, SCULPT_TOOL_SNAKE_HOOK, and SCULPT_TOOL_THUMB.
Referenced by paint_space_stroke(), paint_stroke_modal(), and sculpt_update_cache_variants().
int paint_stroke_cancel (struct bContext * C, struct wmOperator * op)
Definition at line 393 of file paint_stroke.c.
References wmOperator::customdata, PaintStroke::done, MEM_freeN(), NULL, and OPERATOR_CANCELLED.
Referenced by sculpt_brush_stroke_cancel(), vpaint_cancel(), and wpaint_cancel().
int paint_stroke_exec (struct bContext * C, struct wmOperator * op)
Definition at line 369 of file paint_stroke.c.
References wmOperator::customdata, PaintStroke::done, MEM_freeN(), NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_BEGIN, RNA_END, PaintStroke::stroke_started, PaintStroke::test_start, and PaintStroke::update_step.
Referenced by sculpt_brush_stroke_exec().
void paint_stroke_free (struct PaintStroke * stroke)
Definition at line 279 of file paint_stroke.c.
References MEM_freeN().
Referenced by sculpt_brush_stroke_invoke().
int paint_stroke_modal (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
Definition at line 292 of file paint_stroke.c.
References PaintStroke::brush, BRUSH_AIRBRUSH, BRUSH_ANCHORED, BRUSH_SMOOTH_STROKE, CTX_wm_manager(), CTX_wm_window(), wmOperator::customdata, wmEvent::customdata, PaintStroke::done, ELEM, PaintStroke::event_type, Brush::flag, INBETWEEN_MOUSEMOVE, KM_RELEASE, PaintStroke::last_mouse_position, MEM_freeN(), MOUSEMOVE, NDOF_MOTION, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, paint_brush_stroke_add_step(), paint_draw_smooth_stroke(), paint_poll(), paint_smooth_stroke(), paint_space_stroke(), paint_space_stroke_enabled(), Brush::rate, PaintStroke::smooth_stroke_cursor, PaintStroke::stroke_started, PaintStroke::test_start, TIMER, PaintStroke::timer, wmEvent::type, wmEvent::val, WM_event_add_timer(), WM_event_remove_timer(), WM_paint_cursor_activate(), and WM_paint_cursor_end().
Referenced by PAINT_OT_vertex_paint(), PAINT_OT_weight_paint(), and SCULPT_OT_brush_stroke().
void* paint_stroke_mode_data (struct PaintStroke * stroke)
Definition at line 411 of file paint_stroke.c.
References PaintStroke::mode_data.
Referenced by vpaint_stroke_done(), vpaint_stroke_update_step(), wpaint_stroke_done(), and wpaint_stroke_update_step().
struct PaintStroke* paint_stroke_new (struct bContext * C, StrokeGetLocation get_location, StrokeTestStart test_start, StrokeUpdateStep update_step, StrokeDone done, int event_type) [read]
Definition at line 258 of file paint_stroke.c.
References ViewContext::ar, PaintStroke::brush, CTX_data_scene(), PaintStroke::done, PaintStroke::event_type, PaintStroke::get_location, PaintStroke::mats, MEM_callocN(), ViewContext::obact, paint_brush(), paint_get_active(), ViewContext::rv3d, PaintStroke::test_start, PaintStroke::update_step, PaintStroke::vc, view3d_get_transformation(), and view3d_set_viewcontext().
Referenced by sculpt_brush_stroke_exec(), sculpt_brush_stroke_invoke(), vpaint_invoke(), and wpaint_invoke().
void paint_stroke_set_mode_data (struct PaintStroke * stroke, void * mode_data)
Definition at line 416 of file paint_stroke.c.
References PaintStroke::mode_data.
Referenced by vpaint_stroke_test_start(), and wpaint_stroke_test_start().
struct ViewContext* paint_stroke_view_context (struct PaintStroke * stroke) [read]
Definition at line 406 of file paint_stroke.c.
References PaintStroke::vc.
Referenced by sculpt_update_cache_invariants(), and sculpt_update_cache_variants().
void projectf (struct bglMats * mats, const float v[3], float p[2])
Definition at line 144 of file paint_utils.c.
References bglMats::modelview, bglMats::projection, and bglMats::viewport.
void SCULPT_OT_uv_sculpt_stroke (struct wmOperatorType * ot)
Definition at line 787 of file sculpt_uv.c.
References BRUSH_STROKE_INVERT, BRUSH_STROKE_NORMAL, BRUSH_STROKE_SMOOTH, wmOperatorType::description, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, uv_sculpt_poll(), uv_sculpt_stroke_invoke(), and uv_sculpt_stroke_modal().
Referenced by ED_operatortypes_paint().
void undo_paint_push_begin (int type, const char * name, UndoRestoreCb restore, UndoFreeCb free)
Definition at line 203 of file paint_undo.c.
References UNDO_PAINT_IMAGE, UNDO_PAINT_MESH, and undo_stack_push_begin().
Referenced by sculpt_undo_push_begin(), texture_paint_camera_project_exec(), and texture_paint_init().
void undo_paint_push_count_alloc (int type, int size)
Definition at line 225 of file paint_undo.c.
References UndoStack::current, size(), UNDO_PAINT_IMAGE, UNDO_PAINT_MESH, and UndoElem::undosize.
Referenced by image_undo_push_tile(), and sculpt_undo_alloc_node().
void undo_paint_push_end (int type)
Definition at line 233 of file paint_undo.c.
References UNDO_PAINT_IMAGE, UNDO_PAINT_MESH, and undo_stack_push_end().
Referenced by paint_exit(), and sculpt_undo_push_end().
struct ListBase* undo_paint_push_get_list (int type) [read]
Definition at line 211 of file paint_undo.c.
References UndoStack::current, UndoElem::elems, NULL, UNDO_PAINT_IMAGE, and UNDO_PAINT_MESH.
Referenced by image_undo_push_tile(), sculpt_undo_alloc_node(), sculpt_undo_get_node(), and sculpt_undo_push_end().
int uv_sculpt_poll (struct bContext * C)
Definition at line 5631 of file paint_image.c.
References uv_sculpt_brush_poll().
Referenced by BRUSH_OT_uv_sculpt_tool_set(), ED_keymap_paint(), and SCULPT_OT_uv_sculpt_stroke().
int vert_paint_poll (struct bContext * C)
Definition at line 5641 of file paint_image.c.
References CTX_data_active_object(), and paint_vertsel_test().
Referenced by ED_keymap_paint(), PAINT_OT_vert_select_all(), and PAINT_OT_vert_select_inverse().
int vertex_paint_mode_poll (struct bContext * C)
Definition at line 123 of file paint_vertex.c.
References CTX_data_active_object(), Object::data, Object::mode, and OB_MODE_VERTEX_PAINT.
Referenced by ED_keymap_paint(), PAINT_OT_vertex_color_set(), and vertex_paint_poll().
int vertex_paint_poll (struct bContext * C)
Definition at line 130 of file paint_vertex.c.
References CTX_data_tool_settings(), CTX_wm_area(), CTX_wm_region(), paint_brush(), ARegion::regiontype, RGN_TYPE_WINDOW, SPACE_VIEW3D, ScrArea::spacetype, and vertex_paint_mode_poll().
Referenced by PAINT_OT_vertex_paint(), and set_vpaint().
void vpaint_fill (struct Object * ob, unsigned int paintcol)
Definition at line 438 of file paint_vertex.c.
References BKE_mesh_tessface_clear(), DAG_id_tag_update(), Mesh::editflag, MPoly::flag, get_mesh(), i, Mesh::id, MPoly::loopstart, make_vertexcol(), ME_EDIT_PAINT_MASK, ME_FACE_SEL, Mesh::mloopcol, Mesh::mpoly, NULL, MPoly::totloop, and Mesh::totpoly.
Referenced by vertex_color_set_exec().
unsigned int vpaint_get_current_col (struct VPaint * vp)
Definition at line 188 of file paint_vertex.c.
References VPaint::paint, paint_brush(), Brush::rgb, and rgb_float_to_uchar().
Referenced by vertex_color_set_exec(), and vpaint_stroke_test_start().
int weight_paint_mode_poll (struct bContext * C)
Definition at line 145 of file paint_vertex.c.
References CTX_data_active_object(), Object::data, Object::mode, and OB_MODE_WEIGHT_PAINT.
Referenced by ED_keymap_paint(), PAINT_OT_weight_sample(), and PAINT_OT_weight_sample_group().
int weight_paint_poll (struct bContext * C)
Definition at line 152 of file paint_vertex.c.
References CTX_data_active_object(), CTX_data_tool_settings(), CTX_wm_area(), CTX_wm_region(), Object::mode, NULL, OB_MODE_WEIGHT_PAINT, paint_brush(), ARegion::regiontype, RGN_TYPE_WINDOW, SPACE_VIEW3D, and ScrArea::spacetype.
Referenced by PAINT_OT_weight_paint(), and set_wpaint().
void wpaint_fill (struct VPaint * wp, struct Object * ob, float paintweight)
Definition at line 473 of file paint_vertex.c.
References Object::actdef, copy_wpaint_prev(), DAG_id_tag_update(), Object::data, defvert_verify_index(), Mesh::dvert, Mesh::editflag, MDeformVert::flag, MVert::flag, MPoly::flag, Mesh::id, MPoly::loopstart, ME_EDIT_MIRROR_X, ME_EDIT_PAINT_SEL_MODE, ME_FACE_SEL, mesh_get_x_mirror_vert(), Mesh::mloop, Mesh::mpoly, Mesh::mvert, NULL, SCE_SELECT_FACE, SCE_SELECT_VERTEX, SELECT, MPoly::totloop, Mesh::totpoly, Mesh::totvert, MLoop::v, MDeformWeight::weight, wpaint_mirror_vgroup_ensure(), and VPaint::wpaint_prev.
Referenced by weight_paint_set_exec().