Blender: SCA_RandomActuator Class Reference
SCA_RandomActuator Class Reference
#include <SCA_RandomActuator.h>
Public Types
enum KX_RANDOMACT_MODE {
KX_RANDOMACT_NODEF, KX_RANDOMACT_BOOL_CONST, KX_RANDOMACT_BOOL_UNIFORM, KX_RANDOMACT_BOOL_BERNOUILLI,
KX_RANDOMACT_INT_CONST, KX_RANDOMACT_INT_UNIFORM, KX_RANDOMACT_INT_POISSON, KX_RANDOMACT_FLOAT_CONST,
KX_RANDOMACT_FLOAT_UNIFORM, KX_RANDOMACT_FLOAT_NORMAL, KX_RANDOMACT_FLOAT_NEGATIVE_EXPONENTIAL, KX_RANDOMACT_MAX
}
Public Member Functions
SCA_RandomActuator (class SCA_IObject *gameobj, long seed, KX_RANDOMACT_MODE mode, float para1, float para2, const STR_String &propName)
virtual ~SCA_RandomActuator ()
virtual bool Update ()
virtual CValue * GetReplica ()
virtual void ProcessReplica ()
Public Attributes
KX_RANDOMACT_MODE m_distribution
Detailed Description
Definition at line 39 of file SCA_RandomActuator.h.
Member Enumeration Documentation
enum SCA_RandomActuator::KX_RANDOMACT_MODE
Enumerator:
KX_RANDOMACT_NODEF
KX_RANDOMACT_BOOL_CONST
KX_RANDOMACT_BOOL_UNIFORM
KX_RANDOMACT_BOOL_BERNOUILLI
KX_RANDOMACT_INT_CONST
KX_RANDOMACT_INT_UNIFORM
KX_RANDOMACT_INT_POISSON
KX_RANDOMACT_FLOAT_CONST
KX_RANDOMACT_FLOAT_UNIFORM
KX_RANDOMACT_FLOAT_NORMAL
KX_RANDOMACT_FLOAT_NEGATIVE_EXPONENTIAL
KX_RANDOMACT_MAX
Definition at line 66 of file SCA_RandomActuator.h.
Constructor & Destructor Documentation
SCA_RandomActuator::SCA_RandomActuator (class SCA_IObject * gameobj, long seed, SCA_RandomActuator::KX_RANDOMACT_MODE mode, float para1, float para2, const STR_String & propName)
Definition at line 50 of file SCA_RandomActuator.cpp.
Referenced by GetReplica().
SCA_RandomActuator::~SCA_RandomActuator () [virtual]
Definition at line 69 of file SCA_RandomActuator.cpp.
References SCA_RandomNumberGenerator::Release().
Member Function Documentation
CValue * SCA_RandomActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 76 of file SCA_RandomActuator.cpp.
References ProcessReplica(), and SCA_RandomActuator().
void SCA_RandomActuator::ProcessReplica () [virtual]
Makes sure any internal data owned by this class is deep copied.
Reimplemented from SCA_IActuator.
Definition at line 84 of file SCA_RandomActuator.cpp.
References SCA_RandomNumberGenerator::AddRef().
Referenced by GetReplica().
bool SCA_RandomActuator::Update (void) [virtual]
Reimplemented from SCA_IActuator.
Definition at line 93 of file SCA_RandomActuator.cpp.
References SCA_RandomNumberGenerator::Draw(), SCA_RandomNumberGenerator::DrawFloat(), KDL::exp(), SCA_ILogicBrick::GetName(), SCA_ILogicBrick::GetParent(), CValue::GetProperty(), SCA_RandomNumberGenerator::GetSeed(), SCA_IActuator::IsNegativeEvent(), KX_RANDOMACT_BOOL_BERNOUILLI, KX_RANDOMACT_BOOL_CONST, KX_RANDOMACT_BOOL_UNIFORM, KX_RANDOMACT_FLOAT_CONST, KX_RANDOMACT_FLOAT_NEGATIVE_EXPONENTIAL, KX_RANDOMACT_FLOAT_NORMAL, KX_RANDOMACT_FLOAT_UNIFORM, KX_RANDOMACT_INT_CONST, KX_RANDOMACT_INT_POISSON, KX_RANDOMACT_INT_UNIFORM, log(), m_distribution, NULL, CValue::Release(), SCA_IActuator::RemoveAllEvents(), CValue::SetValue(), and sqrt().
Member Data Documentation
KX_RANDOMACT_MODE SCA_RandomActuator::m_distribution
distribution type
Definition at line 81 of file SCA_RandomActuator.h.
Referenced by Update().
The documentation for this class was generated from the following files:
SCA_RandomActuator.h
SCA_RandomActuator.cpp