Blender: ArmatureExporter Class Reference
ArmatureExporter Class Reference
#include <ArmatureExporter.h>
Public Member Functions
ArmatureExporter (COLLADASW::StreamWriter *sw, const ExportSettings *export_settings)
void add_armature_bones (Object *ob_arm, Scene *sce, SceneExporter *se, std::list< Object * > &child_objects)
bool is_skinned_mesh (Object *ob)
void add_instance_controller (Object *ob)
void export_controllers (Scene *sce)
void operator() (Object *ob)
Detailed Description
Definition at line 56 of file ArmatureExporter.h.
Constructor & Destructor Documentation
ArmatureExporter::ArmatureExporter (COLLADASW::StreamWriter * sw, const ExportSettings * export_settings)
Definition at line 51 of file ArmatureExporter.cpp.
Member Function Documentation
void ArmatureExporter::add_armature_bones (Object * ob_arm, Scene * sce, SceneExporter * se, std::list< Object * > & child_objects)
Definition at line 54 of file ArmatureExporter.cpp.
References bArmature::bonebase, Object::data, and ListBase::first.
void ArmatureExporter::add_instance_controller (Object * ob)
Definition at line 72 of file ArmatureExporter.cpp.
References InstanceWriter::add_material_bindings(), bArmature::bonebase, Object::data, ListBase::first, get_joint_id(), Bone::next, and Bone::parent.
void ArmatureExporter::export_controllers (Scene * sce)
Definition at line 94 of file ArmatureExporter.cpp.
References GeometryFunctor::forEachMeshObjectInScene(), and ExportSettings::selected.
Referenced by DocumentExporter::exportCurrentScene().
bool ArmatureExporter::is_skinned_mesh (Object * ob)
Definition at line 67 of file ArmatureExporter.cpp.
References NULL.
void ArmatureExporter::operator() (Object * ob)
Definition at line 106 of file ArmatureExporter.cpp.
The documentation for this class was generated from the following files:
ArmatureExporter.h
ArmatureExporter.cpp