Blender: ForEachMaterialFunctor< Functor > Class Template Reference
ForEachMaterialFunctor< Functor > Class Template Reference
#include <MaterialExporter.h>
Public Member Functions
ForEachMaterialFunctor (Functor *f)
void operator() (Object *ob)
Detailed Description
template<class Functor>
class ForEachMaterialFunctor< Functor >
Definition at line 61 of file MaterialExporter.h.
Constructor & Destructor Documentation
template<class Functor> ForEachMaterialFunctor< Functor >::ForEachMaterialFunctor (Functor * f) [inline]
Definition at line 66 of file MaterialExporter.h.
Member Function Documentation
template<class Functor> void ForEachMaterialFunctor< Functor >::operator() (Object * ob) [inline]
Definition at line 68 of file MaterialExporter.h.
References find(), give_current_material(), id_name(), Object::totcol, and translate_id().
The documentation for this class was generated from the following file:
MaterialExporter.h