Blender: SCA_PropertyActuator Class Reference
SCA_PropertyActuator Class Reference
#include <SCA_PropertyActuator.h>
Public Member Functions
SCA_PropertyActuator (SCA_IObject *gameobj, SCA_IObject *sourceObj, const STR_String &propname, const STR_String &expr, int acttype)
~SCA_PropertyActuator ()
CValue * GetReplica ()
virtual void ProcessReplica ()
virtual bool UnlinkObject (SCA_IObject *clientobj)
virtual void Relink (CTR_Map< CTR_HashedPtr, void * > *obj_map)
virtual bool Update ()
Detailed Description
Definition at line 37 of file SCA_PropertyActuator.h.
Constructor & Destructor Documentation
SCA_PropertyActuator::SCA_PropertyActuator (SCA_IObject * gameobj, SCA_IObject * sourceObj, const STR_String & propname, const STR_String & expr, int acttype)
Definition at line 47 of file SCA_PropertyActuator.cpp.
References SCA_IObject::RegisterActuator().
Referenced by GetReplica().
SCA_PropertyActuator::~SCA_PropertyActuator ()
Definition at line 60 of file SCA_PropertyActuator.cpp.
References SCA_IObject::UnregisterActuator().
Member Function Documentation
CValue * SCA_PropertyActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 186 of file SCA_PropertyActuator.cpp.
References ProcessReplica(), and SCA_PropertyActuator().
void SCA_PropertyActuator::ProcessReplica () [virtual]
Makes sure any internal data owned by this class is deep copied.
Reimplemented from SCA_IActuator.
Definition at line 196 of file SCA_PropertyActuator.cpp.
References SCA_IObject::RegisterActuator().
Referenced by GetReplica().
void SCA_PropertyActuator::Relink (CTR_Map< CTR_HashedPtr, void * > * obj_map) [virtual]
Reimplemented from SCA_ILogicBrick.
Definition at line 216 of file SCA_PropertyActuator.cpp.
References SCA_IObject::RegisterActuator(), and SCA_IObject::UnregisterActuator().
bool SCA_PropertyActuator::UnlinkObject (SCA_IObject * clientobj) [virtual]
UnlinkObject(...) Certain actuator use gameobject pointers (like TractTo actuator) This function can be called when an object is removed to make sure that the actuator will not use it anymore.
Reimplemented from SCA_IActuator.
Definition at line 205 of file SCA_PropertyActuator.cpp.
References NULL.
bool SCA_PropertyActuator::Update (void) [virtual]
Reimplemented from SCA_IActuator.
Definition at line 66 of file SCA_PropertyActuator.cpp.
References CExpression::AddRef(), CValue::AddRef(), CExpression::Calculate(), CValue::GetNumber(), SCA_ILogicBrick::GetParent(), CValue::GetProperty(), CValue::GetReplica(), SCA_IActuator::IsNegativeEvent(), NULL, CParser::ProcessText(), CExpression::Release(), CValue::Release(), SCA_IActuator::RemoveAllEvents(), CParser::SetContext(), CValue::SetProperty(), CValue::SetValue(), and VALUE_ADD_OPERATOR.
The documentation for this class was generated from the following files:
SCA_PropertyActuator.h
SCA_PropertyActuator.cpp