Blender: ED_logic.h File Reference
ED_logic.h File Reference
Editors
Functions
void ED_operatortypes_logic (void)
Detailed Description
Definition in file ED_logic.h.
Function Documentation
void ED_operatortypes_logic (void)
Definition at line 725 of file logic_ops.c.
References LOGIC_OT_actuator_add(), LOGIC_OT_actuator_move(), LOGIC_OT_actuator_remove(), LOGIC_OT_controller_add(), LOGIC_OT_controller_move(), LOGIC_OT_controller_remove(), LOGIC_OT_sensor_add(), LOGIC_OT_sensor_move(), LOGIC_OT_sensor_remove(), LOGIC_OT_texface_convert(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().