Blender: LightsExporter Class Reference
LightsExporter Class Reference
#include <LightExporter.h>
Public Member Functions
LightsExporter (COLLADASW::StreamWriter *sw, const ExportSettings *export_settings)
void exportLights (Scene *sce)
void operator() (Object *ob)
Detailed Description
Definition at line 40 of file LightExporter.h.
Constructor & Destructor Documentation
LightsExporter::LightsExporter (COLLADASW::StreamWriter * sw, const ExportSettings * export_settings)
Definition at line 53 of file LightExporter.cpp.
Member Function Documentation
void LightsExporter::exportLights (Scene * sce)
Definition at line 55 of file LightExporter.cpp.
References forEachLampObjectInScene(), and ExportSettings::selected.
Referenced by DocumentExporter::exportCurrentScene().
void LightsExporter::operator() (Object * ob)
Definition at line 64 of file LightExporter.cpp.
References Lamp::b, Object::data, Lamp::dist, Lamp::energy, Lamp::falloff_type, Lamp::g, get_light_id(), id_name(), LA_FALLOFF_INVLINEAR, LA_HEMI, LA_LOCAL, LA_SPOT, LA_SUN, Lamp::r, Lamp::spotblend, Lamp::spotsize, and Lamp::type.
The documentation for this class was generated from the following files:
LightExporter.h
LightExporter.cpp