Blender: PHY_IMotionState Class Reference
PHY_IMotionState Class Reference
#include <PHY_IMotionState.h>
Public Member Functions
virtual ~PHY_IMotionState ()
virtual void getWorldPosition (float &posX, float &posY, float &posZ)=0
virtual void getWorldScaling (float &scaleX, float &scaleY, float &scaleZ)=0
virtual void getWorldOrientation (float &quatIma0, float &quatIma1, float &quatIma2, float &quatReal)=0
virtual void getWorldOrientation (float *ori)=0
virtual void setWorldOrientation (const float *ori)=0
virtual void setWorldPosition (float posX, float posY, float posZ)=0
virtual void setWorldOrientation (float quatIma0, float quatIma1, float quatIma2, float quatReal)=0
virtual void calculateWorldTransformations ()=0
Detailed Description
PHY_IMotionState is the Interface to explicitly synchronize the world transformation. Default implementations for mayor graphics libraries like OpenGL and DirectX can be provided.
Definition at line 43 of file PHY_IMotionState.h.
Constructor & Destructor Documentation
PHY_IMotionState::~PHY_IMotionState () [virtual]
Definition at line 34 of file PHY_IMotionState.cpp.
Member Function Documentation
virtual void PHY_IMotionState::calculateWorldTransformations () [pure virtual]
Implemented in KX_MotionState, and DefaultMotionState.
Referenced by BlenderBulletMotionState::setWorldTransform(), and CcdPhysicsController::SynchronizeMotionStates().
virtual void PHY_IMotionState::getWorldOrientation (float & quatIma0, float & quatIma1, float & quatIma2, float & quatReal) [pure virtual]
Implemented in KX_MotionState, and DefaultMotionState.
Referenced by CcdGraphicController::getAabb(), CcdPhysicsController::GetTransformFromMotionState(), CcdPhysicsController::GetWorldOrientation(), and BlenderBulletMotionState::getWorldTransform().
virtual void PHY_IMotionState::getWorldOrientation (float * ori) [pure virtual]
Implemented in KX_MotionState, and DefaultMotionState.
virtual void PHY_IMotionState::getWorldPosition (float & posX, float & posY, float & posZ) [pure virtual]
Implemented in KX_MotionState, and DefaultMotionState.
Referenced by CcdGraphicController::getAabb(), CcdPhysicsController::GetTransformFromMotionState(), and BlenderBulletMotionState::getWorldTransform().
virtual void PHY_IMotionState::getWorldScaling (float & scaleX, float & scaleY, float & scaleZ) [pure virtual]
Implemented in KX_MotionState, and DefaultMotionState.
Referenced by CcdGraphicController::getAabb(), and CcdPhysicsController::SynchronizeMotionStates().
virtual void PHY_IMotionState::setWorldOrientation (float quatIma0, float quatIma1, float quatIma2, float quatReal) [pure virtual]
Implemented in KX_MotionState, and DefaultMotionState.
virtual void PHY_IMotionState::setWorldOrientation (const float * ori) [pure virtual]
Implemented in KX_MotionState, and DefaultMotionState.
Referenced by BlenderBulletMotionState::setWorldTransform(), CcdPhysicsController::SynchronizeMotionStates(), KX_RadarSensor::SynchronizeTransform(), KX_NearSensor::SynchronizeTransform(), and WrapperVehicle::SyncWheels().
virtual void PHY_IMotionState::setWorldPosition (float posX, float posY, float posZ) [pure virtual]
Implemented in KX_MotionState, and DefaultMotionState.
Referenced by BlenderBulletMotionState::setWorldTransform(), CcdPhysicsController::SynchronizeMotionStates(), KX_RadarSensor::SynchronizeTransform(), KX_NearSensor::SynchronizeTransform(), and WrapperVehicle::SyncWheels().
The documentation for this class was generated from the following files:
PHY_IMotionState.h
PHY_IMotionState.cpp