Blender: NOD_socket.h File Reference
NOD_socket.h File Reference
nodes
#include "DNA_listBase.h"
#include "BLI_utildefines.h"
#include "BKE_node.h"
#include "RNA_types.h"
Defines
#define SOCK_VECTOR_X 1
#define SOCK_VECTOR_Y 2
#define SOCK_VECTOR_Z 3
#define SOCK_RGBA_R 1
#define SOCK_RGBA_G 2
#define SOCK_RGBA_B 3
#define SOCK_RGBA_A 4
#define SOCK_MESH_VERT_CO 1
#define SOCK_MESH_VERT_NO 2
Functions
void node_socket_type_init (struct bNodeSocketType *types[])
void * node_socket_make_default_value (int type)
void node_socket_free_default_value (int type, void *default_value)
void node_socket_init_default_value (int type, void *default_value)
void node_socket_copy_default_value (int type, void *to_default_value, void *from_default_value)
void node_socket_convert_default_value (int to_type, void *to_default_value, int from_type, void *from_default_value)
void node_socket_set_default_value_int (void *default_value, PropertySubType subtype, int value, int min, int max)
void node_socket_set_default_value_float (void *default_value, PropertySubType subtype, float value, float min, float max)
void node_socket_set_default_value_boolean (void *default_value, char value)
void node_socket_set_default_value_vector (void *default_value, PropertySubType subtype, float x, float y, float z, float min, float max)
void node_socket_set_default_value_rgba (void *default_value, float r, float g, float b, float a)
void node_socket_set_default_value_shader (void *default_value)
void node_socket_set_default_value_mesh (void *default_value)
struct bNodeSocket * node_add_input_from_template (struct bNodeTree *ntree, struct bNode *node, struct bNodeSocketTemplate *stemp)
struct bNodeSocket * node_add_output_from_template (struct bNodeTree *ntree, struct bNode *node, struct bNodeSocketTemplate *stemp)
void node_verify_socket_templates (struct bNodeTree *ntree, struct bNode *node)
Detailed Description
Definition in file NOD_socket.h.
Define Documentation
#define SOCK_MESH_VERT_CO 1
Definition at line 81 of file NOD_socket.h.
#define SOCK_MESH_VERT_NO 2
Definition at line 82 of file NOD_socket.h.
#define SOCK_RGBA_A 4
Definition at line 79 of file NOD_socket.h.
#define SOCK_RGBA_B 3
Definition at line 78 of file NOD_socket.h.
#define SOCK_RGBA_G 2
Definition at line 77 of file NOD_socket.h.
#define SOCK_RGBA_R 1
Definition at line 76 of file NOD_socket.h.
#define SOCK_VECTOR_X 1
Definition at line 72 of file NOD_socket.h.
#define SOCK_VECTOR_Y 2
Definition at line 73 of file NOD_socket.h.
#define SOCK_VECTOR_Z 3
Definition at line 74 of file NOD_socket.h.
Function Documentation
struct bNodeSocket* node_add_input_from_template (struct bNodeTree * ntree, struct bNode * node, struct bNodeSocketTemplate * stemp) [read]
Definition at line 446 of file node_socket.c.
References bNodeSocket::default_value, bNodeSocketTemplate::flag, bNodeSocket::flag, bNodeSocketTemplate::max, bNodeSocketTemplate::min, bNodeSocketTemplate::name, node_socket_set_default_value_boolean(), node_socket_set_default_value_float(), node_socket_set_default_value_int(), node_socket_set_default_value_mesh(), node_socket_set_default_value_rgba(), node_socket_set_default_value_shader(), node_socket_set_default_value_vector(), nodeAddSocket(), SOCK_BOOLEAN, SOCK_FLOAT, SOCK_IN, SOCK_INT, SOCK_MESH, SOCK_RGBA, SOCK_SHADER, SOCK_VECTOR, bNodeSocketTemplate::subtype, bNodeSocketTemplate::type, bNodeSocketTemplate::val1, bNodeSocketTemplate::val2, bNodeSocketTemplate::val3, and bNodeSocketTemplate::val4.
Referenced by node_add_sockets_from_type(), and verify_socket_template().
struct bNodeSocket* node_add_output_from_template (struct bNodeTree * ntree, struct bNode * node, struct bNodeSocketTemplate * stemp) [read]
Definition at line 478 of file node_socket.c.
References bNodeSocketTemplate::name, nodeAddSocket(), SOCK_OUT, and bNodeSocketTemplate::type.
Referenced by cmp_node_image_add_render_pass_output(), node_add_sockets_from_type(), and verify_socket_template().
void node_socket_convert_default_value (int to_type, void * to_default_value, int from_type, void * from_default_value)
Definition at line 330 of file node_socket.c.
References copy_v3_v3(), copy_v4_v4(), SOCK_BOOLEAN, SOCK_FLOAT, SOCK_INT, SOCK_RGBA, SOCK_VECTOR, bNodeSocketValueBoolean::value, bNodeSocketValueFloat::value, bNodeSocketValueVector::value, bNodeSocketValueInt::value, and bNodeSocketValueRGBA::value.
Referenced by node_group_ungroup(), and nodeSocketSetType().
void node_socket_copy_default_value (int type, void * to_default_value, void * from_default_value)
Definition at line 277 of file node_socket.c.
References SOCK_BOOLEAN, SOCK_FLOAT, SOCK_INT, SOCK_RGBA, and SOCK_VECTOR.
Referenced by node_group_add_extern_socket(), node_group_expose_all_sockets(), node_group_expose_socket(), node_socket_add_replace(), nodeCopyNode(), and ntreeCopyTree().
void node_socket_free_default_value (int type, void * default_value)
void node_socket_init_default_value (int type, void * default_value)
Definition at line 197 of file node_socket.c.
References FALSE, FLT_MAX, node_socket_set_default_value_boolean(), node_socket_set_default_value_float(), node_socket_set_default_value_int(), node_socket_set_default_value_mesh(), node_socket_set_default_value_rgba(), node_socket_set_default_value_shader(), node_socket_set_default_value_vector(), PROP_NONE, SOCK_BOOLEAN, SOCK_FLOAT, SOCK_INT, SOCK_MESH, SOCK_RGBA, SOCK_SHADER, and SOCK_VECTOR.
Referenced by make_socket(), and nodeSocketSetType().
void* node_socket_make_default_value (int type)
Definition at line 176 of file node_socket.c.
References MEM_callocN(), ntreeGetSocketType(), NULL, and bNodeSocketType::value_structsize.
Referenced by make_socket(), node_group_add_extern_socket(), node_socket_add_replace(), nodeCopyNode(), nodeSocketSetType(), and ntreeCopyTree().
void node_socket_set_default_value_boolean (void * default_value, char value)
Definition at line 242 of file node_socket.c.
References bNodeSocketValueBoolean::value.
Referenced by node_add_input_from_template(), and node_socket_init_default_value().
void node_socket_set_default_value_float (void * default_value, PropertySubType subtype, float value, float min, float max)
Definition at line 233 of file node_socket.c.
References max, bNodeSocketValueFloat::max, bNodeSocketValueFloat::min, min, bNodeSocketValueFloat::subtype, and bNodeSocketValueFloat::value.
Referenced by node_add_input_from_template(), node_forloop_init(), node_socket_init_default_value(), and node_whileloop_init().
void node_socket_set_default_value_int (void * default_value, PropertySubType subtype, int value, int min, int max)
Definition at line 224 of file node_socket.c.
References max, bNodeSocketValueInt::max, min, bNodeSocketValueInt::min, bNodeSocketValueInt::subtype, and bNodeSocketValueInt::value.
Referenced by node_add_input_from_template(), and node_socket_init_default_value().
void node_socket_set_default_value_mesh (void * default_value)
void node_socket_set_default_value_rgba (void * default_value, float r, float g, float b, float a)
Definition at line 259 of file node_socket.c.
References g, and bNodeSocketValueRGBA::value.
Referenced by node_add_input_from_template(), and node_socket_init_default_value().
void node_socket_set_default_value_shader (void * default_value)
void node_socket_set_default_value_vector (void * default_value, PropertySubType subtype, float x, float y, float z, float min, float max)
Definition at line 248 of file node_socket.c.
References max, bNodeSocketValueVector::max, bNodeSocketValueVector::min, min, bNodeSocketValueVector::subtype, and bNodeSocketValueVector::value.
Referenced by node_add_input_from_template(), and node_socket_init_default_value().
void node_socket_type_init (struct bNodeSocketType * types[])
Definition at line 161 of file node_socket.c.
References INIT_TYPE.
Referenced by ntreeGetSocketType().
void node_verify_socket_templates (struct bNodeTree * ntree, struct bNode * node)
Definition at line 596 of file node_socket.c.
References bNode::inputs, bNodeType::inputs, bNode::outputs, bNodeType::outputs, SOCK_IN, SOCK_OUT, bNodeSocketTemplate::type, bNode::typeinfo, and verify_socket_template_list().
Referenced by lib_nodetree_init_types_cb().