Blender: rna_text.c File Reference
rna_text.c File Reference
RNA
#include <stdlib.h>
#include <limits.h>
#include "MEM_guardedalloc.h"
#include "BKE_text.h"
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_text_types.h"
#include "WM_types.h"
Functions
static void rna_def_text_line (BlenderRNA *brna)
static void rna_def_text_marker (BlenderRNA *brna)
static void rna_def_text (BlenderRNA *brna)
void RNA_def_text (BlenderRNA *brna)
Detailed Description
Definition in file rna_text.c.
Function Documentation
static void rna_def_text (BlenderRNA * brna) [static]
Definition at line 175 of file rna_text.c.
References NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_UNSIGNED, RNA_api_text(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), STRUCT_ID_REFCOUNT, TXT_ISDIRTY, TXT_ISMEM, TXT_ISSCRIPT, and TXT_TABSTOSPACES.
Referenced by RNA_def_text().
void RNA_def_text (BlenderRNA * brna)
Definition at line 251 of file rna_text.c.
References rna_def_text(), rna_def_text_line(), and rna_def_text_marker().
static void rna_def_text_line (BlenderRNA * brna) [static]
Definition at line 118 of file rna_text.c.
References NA_EDITED, NC_TEXT, NULL, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_string_funcs(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_text().
static void rna_def_text_marker (BlenderRNA * brna) [static]
Definition at line 132 of file rna_text.c.
References NULL, PROP_BOOLEAN, PROP_COLOR_GAMMA, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_ui_text(), TMARK_EDITALL, and TMARK_TEMP.
Referenced by RNA_def_text().