Blender: util_intern.h File Reference
util_intern.h File Reference
editor utilities
Functions
void undo_editmode_name (struct bContext *C, const char *undoname)
int undo_editmode_valid (const char *undoname)
const char * undo_editmode_get_name (struct bContext *C, int nr, int *active)
void * undo_editmode_get_prev (struct Object *ob)
void undo_editmode_step (struct bContext *C, int step)
void undo_editmode_number (struct bContext *C, int nr)
Detailed Description
Definition in file util_intern.h.
Function Documentation
const char* undo_editmode_get_name (struct bContext * C, int nr, int * active)
Definition at line 339 of file editmode_undo.c.
References BLI_findlink(), UndoElem::name, NULL, and undo_clean_stack().
Referenced by rna_undo_itemf().
void* undo_editmode_get_prev (struct Object * ob)
Definition at line 358 of file editmode_undo.c.
References ListBase::last, NULL, UndoElem::ob, UndoElem::prev, and UndoElem::undodata.
void undo_editmode_name (struct bContext * C, const char * undoname)
Definition at line 307 of file editmode_undo.c.
References ListBase::last, UndoElem::name, UndoElem::prev, and undo_editmode_step().
Referenced by ed_undo_step().
void undo_editmode_number (struct bContext * C, int nr)
Definition at line 295 of file editmode_undo.c.
References ListBase::first, UndoElem::next, and undo_editmode_step().
Referenced by undo_history_exec().
void undo_editmode_step (struct bContext * C, int step)
Definition at line 241 of file editmode_undo.c.
References CTX_data_edit_object(), DAG_id_tag_update(), Object::data, EDBM_selectmode_to_scene(), error(), G, G_DEBUG, UndoElem::getdata, Object::id, UndoElem::name, UndoElem::next, NULL, OB_MESH, OB_RECALC_DATA, UndoElem::prev, Object::type, undo_clean_stack(), and undo_restore().
Referenced by ed_undo_step(), undo_editmode_name(), and undo_editmode_number().
int undo_editmode_valid (const char * undoname)
Definition at line 322 of file editmode_undo.c.
References ListBase::first, ListBase::last, UndoElem::name, NULL, and UndoElem::prev.
Referenced by ED_undo_valid().