Blender: SkinInfo Class Reference
SkinInfo Class Reference
#include <SkinInfo.h>
Classes
struct JointData
Public Member Functions
SkinInfo ()
SkinInfo (const SkinInfo &skin)
SkinInfo (UnitConverter *conv)
template<typename T >
void transfer_array_data (T &src, T &dest)
void transfer_int_array_data_const (const COLLADAFW::IntValuesArray &src, COLLADAFW::IntValuesArray &dest)
void transfer_uint_array_data_const (const COLLADAFW::UIntValuesArray &src, COLLADAFW::UIntValuesArray &dest)
void borrow_skin_controller_data (const COLLADAFW::SkinControllerData *skin)
void free ()
void add_joint (const COLLADABU::Math::Matrix4 &matrix)
void set_controller (const COLLADAFW::SkinController *co)
Object * create_armature (Scene *scene)
Object * set_armature (Object *ob_arm)
bool get_joint_inv_bind_matrix (float inv_bind_mat[][4], COLLADAFW::Node *node)
Object * get_armature ()
const COLLADAFW::UniqueId & get_controller_uid ()
bool uses_joint_or_descendant (COLLADAFW::Node *node)
void link_armature (bContext *C, Object *ob, std::map< COLLADAFW::UniqueId, COLLADAFW::Node * > &joint_by_uid, TransformReader *tm)
bPoseChannel * get_pose_channel_from_node (COLLADAFW::Node *node)
void set_parent (Object *_parent)
Object * get_parent ()
void find_root_joints (const std::vector< COLLADAFW::Node * > &root_joints, std::map< COLLADAFW::UniqueId, COLLADAFW::Node * > &joint_by_uid, std::vector< COLLADAFW::Node * > &result)
bool find_node_in_tree (COLLADAFW::Node *node, COLLADAFW::Node *tree_root)
Detailed Description
Definition at line 48 of file SkinInfo.h.
Constructor & Destructor Documentation
SkinInfo::SkinInfo ()
Definition at line 60 of file SkinInfo.cpp.
SkinInfo::SkinInfo (const SkinInfo & skin)
Definition at line 62 of file SkinInfo.cpp.
References copy_m4_m4(), transfer_int_array_data_const(), and transfer_uint_array_data_const().
SkinInfo::SkinInfo (UnitConverter * conv)
Definition at line 76 of file SkinInfo.cpp.
Member Function Documentation
void SkinInfo::add_joint (const COLLADABU::Math::Matrix4 & matrix)
Definition at line 126 of file SkinInfo.cpp.
References UnitConverter::dae_matrix_to_mat4_().
Referenced by ArmatureImporter::write_skin_controller_data().
void SkinInfo::borrow_skin_controller_data (const COLLADAFW::SkinControllerData * skin)
Definition at line 100 of file SkinInfo.cpp.
References bc_get_float_value(), UnitConverter::dae_matrix_to_mat4_(), i, and transfer_array_data().
Referenced by ArmatureImporter::write_skin_controller_data().
Object * SkinInfo::create_armature (Scene * scene)
Definition at line 152 of file SkinInfo.cpp.
References add_object(), and OB_ARMATURE.
bool SkinInfo::find_node_in_tree (COLLADAFW::Node * node, COLLADAFW::Node * tree_root)
Definition at line 326 of file SkinInfo.cpp.
References i.
Referenced by find_root_joints().
void SkinInfo::find_root_joints (const std::vector< COLLADAFW::Node * > & root_joints, std::map< COLLADAFW::UniqueId, COLLADAFW::Node * > & joint_by_uid, std::vector< COLLADAFW::Node * > & result)
Definition at line 304 of file SkinInfo.cpp.
References find(), and find_node_in_tree().
void SkinInfo::free ()
Definition at line 115 of file SkinInfo.cpp.
Referenced by ArmatureImporter::make_armatures().
Object * SkinInfo::get_armature ()
Definition at line 181 of file SkinInfo.cpp.
Referenced by ArmatureImporter::get_armature_for_joint(), and ArmatureImporter::make_armatures().
const COLLADAFW::UniqueId & SkinInfo::get_controller_uid ()
Definition at line 186 of file SkinInfo.cpp.
Referenced by ArmatureImporter::make_armatures().
bool SkinInfo::get_joint_inv_bind_matrix (float inv_bind_mat[][4], COLLADAFW::Node * node)
Definition at line 167 of file SkinInfo.cpp.
References copy_m4_m4().
Referenced by ArmatureImporter::get_joint_bind_mat().
Object * SkinInfo::get_parent ()
Definition at line 299 of file SkinInfo.cpp.
Referenced by ArmatureImporter::make_armatures().
bPoseChannel * SkinInfo::get_pose_channel_from_node (COLLADAFW::Node * node)
Definition at line 289 of file SkinInfo.cpp.
References bc_get_joint_name(), get_pose_channel(), and Object::pose.
void SkinInfo::link_armature (bContext * C, Object * ob, std::map< COLLADAFW::UniqueId, COLLADAFW::Node * > & joint_by_uid, TransformReader * tm)
Definition at line 214 of file SkinInfo.cpp.
References ARM_DEF_VGROUP, bc_get_joint_name(), bc_set_parent(), BLI_findlink(), copy_m4_m4(), CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), DAG_scene_sort(), Object::data, Object::defbase, ED_object_modifier_add(), ED_vgroup_add_name(), ED_vgroup_vert_add(), eModifierType_Armature, invert_m4_m4(), NC_OBJECT, ND_TRANSFORM, NULL, OB_RECALC_DATA, OB_RECALC_OB, object_apply_mat4(), Object::obmat, Object::parent, Object::parentinv, PAROBJECT, Object::partype, Object::recalc, WEIGHT_REPLACE, what_does_parent(), and WM_event_add_notifier().
Referenced by ArmatureImporter::make_armatures().
Object * SkinInfo::set_armature (Object * ob_arm)
Definition at line 158 of file SkinInfo.cpp.
void SkinInfo::set_controller (const COLLADAFW::SkinController * co)
Definition at line 133 of file SkinInfo.cpp.
References i.
void SkinInfo::set_parent (Object * _parent)
Definition at line 294 of file SkinInfo.cpp.
template<class T > void SkinInfo::transfer_array_data (T & src, T & dest)
Definition at line 80 of file SkinInfo.cpp.
Referenced by borrow_skin_controller_data().
void SkinInfo::transfer_int_array_data_const (const COLLADAFW::IntValuesArray & src, COLLADAFW::IntValuesArray & dest)
Definition at line 88 of file SkinInfo.cpp.
Referenced by SkinInfo().
void SkinInfo::transfer_uint_array_data_const (const COLLADAFW::UIntValuesArray & src, COLLADAFW::UIntValuesArray & dest)
Definition at line 94 of file SkinInfo.cpp.
Referenced by SkinInfo().
bool SkinInfo::uses_joint_or_descendant (COLLADAFW::Node * node)
Definition at line 196 of file SkinInfo.cpp.
References i.
Referenced by ArmatureImporter::get_armature_for_joint().
The documentation for this class was generated from the following files:
SkinInfo.h
SkinInfo.cpp