Blender: smoke.c File Reference
smoke.c File Reference
blenkernel
#include <GL/glew.h>
#include "MEM_guardedalloc.h"
#include <float.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include "BLI_linklist.h"
#include "BLI_rand.h"
#include "BLI_jitter.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_edgehash.h"
#include "BLI_kdtree.h"
#include "BLI_kdopbvh.h"
#include "BLI_utildefines.h"
#include "BKE_bvhutils.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_customdata.h"
#include "BKE_DerivedMesh.h"
#include "BKE_effect.h"
#include "BKE_modifier.h"
#include "BKE_particle.h"
#include "BKE_pointcache.h"
#include "BKE_smoke.h"
#include "DNA_customdata_types.h"
#include "DNA_group_types.h"
#include "DNA_lamp_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_modifier_types.h"
#include "DNA_object_types.h"
#include "DNA_particle_types.h"
#include "DNA_scene_types.h"
#include "DNA_smoke_types.h"
Functions
struct WTURBULENCE * smoke_turbulence_init (int *UNUSED(res), int UNUSED(amplify), int UNUSED(noisetype))
struct FLUID_3D * smoke_init (int *UNUSED(res), float *UNUSED(p0))
void smoke_free (struct FLUID_3D *UNUSED(fluid))
void smoke_turbulence_free (struct WTURBULENCE *UNUSED(wt))
void smoke_initWaveletBlenderRNA (struct WTURBULENCE *UNUSED(wt), float *UNUSED(strength))
void smoke_initBlenderRNA (struct FLUID_3D *UNUSED(fluid), float *UNUSED(alpha), float *UNUSED(beta), float *UNUSED(dt_factor), float *UNUSED(vorticity), int *UNUSED(border_colli))
long long smoke_get_mem_req (int UNUSED(xres), int UNUSED(yres), int UNUSED(zres), int UNUSED(amplify))
void smokeModifier_do (SmokeModifierData *UNUSED(smd), Scene *UNUSED(scene), Object *UNUSED(ob), DerivedMesh *UNUSED(dm))
static void smokeModifier_freeDomain (SmokeModifierData *smd)
static void smokeModifier_freeFlow (SmokeModifierData *smd)
static void smokeModifier_freeCollision (SmokeModifierData *smd)
void smokeModifier_reset_turbulence (struct SmokeModifierData *smd)
void smokeModifier_reset (struct SmokeModifierData *smd)
void smokeModifier_free (SmokeModifierData *smd)
void smokeModifier_createType (struct SmokeModifierData *smd)
void smokeModifier_copy (struct SmokeModifierData *smd, struct SmokeModifierData *tsmd)
Detailed Description
Definition in file smoke.c.
Function Documentation
void smoke_free (struct FLUID_3D * UNUSEDfluid)
Definition at line 149 of file smoke.c.
Referenced by smokeModifier_freeDomain(), and smokeModifier_reset().
long long smoke_get_mem_req (int UNUSEDxres, int UNUSEDyres, int UNUSEDzres, int UNUSEDamplify)
Definition at line 153 of file smoke.c.
struct FLUID_3D* smoke_init (int * UNUSEDres, float * UNUSEDp0) [read]
Definition at line 148 of file smoke.c.
References NULL.
void smoke_initBlenderRNA (struct FLUID_3D * UNUSEDfluid, float * UNUSEDalpha, float * UNUSEDbeta, float * UNUSEDdt_factor, float * UNUSEDvorticity, int * UNUSEDborder_colli)
Definition at line 152 of file smoke.c.
void smoke_initWaveletBlenderRNA (struct WTURBULENCE * UNUSEDwt, float * UNUSEDstrength)
Definition at line 151 of file smoke.c.
void smoke_turbulence_free (struct WTURBULENCE * UNUSEDwt)
Definition at line 150 of file smoke.c.
Referenced by smokeModifier_freeDomain(), and smokeModifier_reset_turbulence().
struct WTURBULENCE* smoke_turbulence_init (int * UNUSEDres, int UNUSEDamplify, int UNUSEDnoisetype) [read]
Definition at line 147 of file smoke.c.
References NULL.
void smokeModifier_copy (struct SmokeModifierData * smd, struct SmokeModifierData * tsmd)
Definition at line 795 of file smoke.c.
References SmokeDomainSettings::alpha, SmokeDomainSettings::amplify, SmokeDomainSettings::beta, SmokeDomainSettings::border_collisions, SmokeModifierData::coll, SmokeDomainSettings::coll_group, SmokeFlowSettings::density, SmokeDomainSettings::diss_speed, SmokeModifierData::domain, SmokeDomainSettings::effector_weights, SmokeFlowSettings::flags, SmokeDomainSettings::flags, SmokeModifierData::flow, SmokeDomainSettings::fluid_group, SmokeDomainSettings::maxres, MEM_dupallocN(), MEM_freeN(), SmokeDomainSettings::noise, SmokeDomainSettings::omega, SmokeFlowSettings::psys, smokeModifier_createType(), SmokeDomainSettings::strength, SmokeFlowSettings::temp, SmokeModifierData::time, SmokeDomainSettings::time_scale, SmokeFlowSettings::type, SmokeModifierData::type, SmokeFlowSettings::vel_multi, SmokeDomainSettings::viewsettings, and SmokeDomainSettings::vorticity.
Referenced by copyData().
void smokeModifier_createType (struct SmokeModifierData * smd)
Definition at line 715 of file smoke.c.
References SmokeDomainSettings::alpha, SmokeDomainSettings::amplify, SmokeDomainSettings::beta, BKE_add_effector_weights(), BKE_ptcache_add(), SmokeDomainSettings::border_collisions, SmokeCollSettings::bvhtree, SmokeModifierData::coll, SmokeDomainSettings::coll_group, SmokeFlowSettings::density, SmokeDomainSettings::diss_speed, SmokeModifierData::domain, SmokeDomainSettings::eff_group, SmokeDomainSettings::effector_weights, ListBase::first, PointCache::flag, SmokeFlowSettings::flags, SmokeDomainSettings::flags, SmokeModifierData::flow, SmokeDomainSettings::fluid, SmokeDomainSettings::fluid_group, ListBase::last, SmokeDomainSettings::maxres, MEM_callocN(), MOD_SMOKE_DISSOLVE_LOG, MOD_SMOKE_FLOW_ABSOLUTE, MOD_SMOKE_HIGH_SMOOTH, MOD_SMOKE_NOISEWAVE, MOD_SMOKE_TYPE_COLL, MOD_SMOKE_TYPE_DOMAIN, MOD_SMOKE_TYPE_FLOW, MOD_SMOKE_VIEW_SHOWBIG, SmokeDomainSettings::noise, NULL, SmokeCollSettings::numpoints, SmokeDomainSettings::omega, SmokeDomainSettings::point_cache, SmokeCollSettings::points, SmokeFlowSettings::psys, PTCACHE_DISK_CACHE, SmokeDomainSettings::ptcaches, SmokeCollSettings::smd, SmokeFlowSettings::smd, SmokeDomainSettings::smd, smokeModifier_freeCollision(), smokeModifier_freeDomain(), smokeModifier_freeFlow(), PointCache::step, SmokeDomainSettings::strength, SmokeFlowSettings::temp, SmokeDomainSettings::time_scale, SmokeModifierData::type, SmokeFlowSettings::vel_multi, SmokeDomainSettings::viewsettings, SmokeDomainSettings::vorticity, and SmokeDomainSettings::wt.
Referenced by smokeModifier_copy().
void smokeModifier_do (SmokeModifierData * UNUSEDsmd, Scene * UNUSEDscene, Object * UNUSEDob, DerivedMesh * UNUSEDdm)
Definition at line 154 of file smoke.c.
void smokeModifier_free (SmokeModifierData * smd)
Definition at line 705 of file smoke.c.
References smokeModifier_freeCollision(), smokeModifier_freeDomain(), and smokeModifier_freeFlow().
Referenced by freeData().
static void smokeModifier_freeCollision (SmokeModifierData * smd) [static]
Definition at line 612 of file smoke.c.
References BLI_bvhtree_free(), SmokeCollSettings::bvhtree, SmokeModifierData::coll, MEM_freeN(), NULL, and SmokeCollSettings::points.
Referenced by smokeModifier_createType(), and smokeModifier_free().
static void smokeModifier_freeDomain (SmokeModifierData * smd) [static]
Definition at line 569 of file smoke.c.
References BKE_ptcache_free_list(), SmokeModifierData::domain, SmokeDomainSettings::effector_weights, SmokeDomainSettings::fluid, MEM_freeN(), NULL, SmokeDomainSettings::point_cache, SmokeDomainSettings::ptcaches, SmokeDomainSettings::shadow, smoke_free(), smoke_turbulence_free(), and SmokeDomainSettings::wt.
Referenced by smokeModifier_createType(), and smokeModifier_free().
static void smokeModifier_freeFlow (SmokeModifierData * smd) [static]
Definition at line 595 of file smoke.c.
References SmokeModifierData::flow, MEM_freeN(), and NULL.
Referenced by smokeModifier_createType(), and smokeModifier_free().
void smokeModifier_reset (struct SmokeModifierData * smd)
Definition at line 648 of file smoke.c.
References BLI_bvhtree_free(), SmokeCollSettings::bvhtree, SmokeModifierData::coll, SmokeModifierData::domain, SmokeModifierData::flow, SmokeDomainSettings::fluid, MEM_freeN(), NULL, SmokeCollSettings::points, SmokeDomainSettings::shadow, smoke_free(), smokeModifier_reset_turbulence(), and SmokeModifierData::time.
Referenced by BKE_ptcache_id_reset().
void smokeModifier_reset_turbulence (struct SmokeModifierData * smd)
Definition at line 639 of file smoke.c.
References SmokeModifierData::domain, NULL, smoke_turbulence_free(), and SmokeDomainSettings::wt.
Referenced by BKE_ptcache_id_reset(), and smokeModifier_reset().