Blender: bpy_app_ffmpeg.c File Reference
bpy_app_ffmpeg.c File Reference
Python RNA and Operators
#include <Python.h>
#include "BLI_utildefines.h"
#include "BLI_callbacks.h"
#include "RNA_types.h"
#include "RNA_access.h"
#include "bpy_rna.h"
Defines
#define DEF_FFMPEG_LIB_VERSION(lib)
#define SetIntItem(flag) PyStructSequence_SET_ITEM(ffmpeg_info, pos++, PyLong_FromLong(flag))
#define SetStrItem(str) PyStructSequence_SET_ITEM(ffmpeg_info, pos++, PyUnicode_FromString(str))
#define SetObjItem(obj) PyStructSequence_SET_ITEM(ffmpeg_info, pos++, obj)
#define FFMPEG_LIB_VERSION(lib)
Functions
static PyObject * make_ffmpeg_info (void)
PyObject * BPY_app_ffmpeg_struct (void)
Variables
static PyTypeObject BlenderAppFFmpegType
static PyStructSequence_Field app_ffmpeg_info_fields []
static PyStructSequence_Desc app_ffmpeg_info_desc
Detailed Description
Definition in file bpy_app_ffmpeg.c.
Define Documentation
#define DEF_FFMPEG_LIB_VERSION (lib)
Value:
{(char *)(#lib "_version"), (char *)("The " #lib " version  as a tuple of 3 numbers")}, \
    {(char *)(#lib "_version_string"), (char *)("The " #lib " version formatted as a string")},
Definition at line 45 of file bpy_app_ffmpeg.c.
#define FFMPEG_LIB_VERSION (lib)
Value:
{ \
        SetStrItem("Unknown"); \
        SetStrItem("Unknown"); \
} (void)0
Referenced by make_ffmpeg_info().
#define SetIntItem (flag) PyStructSequence_SET_ITEM(ffmpeg_info, pos++, PyLong_FromLong(flag))
#define SetObjItem (obj) PyStructSequence_SET_ITEM(ffmpeg_info, pos++, obj)
#define SetStrItem (str) PyStructSequence_SET_ITEM(ffmpeg_info, pos++, PyUnicode_FromString(str))
Function Documentation
PyObject* BPY_app_ffmpeg_struct (void)
Definition at line 131 of file bpy_app_ffmpeg.c.
References BlenderAppFFmpegType, make_ffmpeg_info(), and NULL.
Referenced by make_app_info().
static PyObject* make_ffmpeg_info (void) [static]
Definition at line 69 of file bpy_app_ffmpeg.c.
References BlenderAppFFmpegType, FFMPEG_LIB_VERSION, NULL, and SetObjItem.
Referenced by BPY_app_ffmpeg_struct().
Variable Documentation
PyStructSequence_Desc app_ffmpeg_info_desc [static]
Initial value:
 {
    (char *)"bpy.app.ffmpeg",
    (char *)"This module contains information about FFmpeg blender is linked against",
    app_ffmpeg_info_fields,
    (sizeof(app_ffmpeg_info_fields) / sizeof(PyStructSequence_Field)) - 1
}
Definition at line 62 of file bpy_app_ffmpeg.c.
PyStructSequence_Field app_ffmpeg_info_fields[] [static]
Initial value:
 {
    {(char *)"supported", (char *)("Boolean, True when Blender is built with FFmpeg support")},
    DEF_FFMPEG_LIB_VERSION(swscale)
    {NULL}
}
Definition at line 49 of file bpy_app_ffmpeg.c.
PyTypeObject BlenderAppFFmpegType [static]
Definition at line 43 of file bpy_app_ffmpeg.c.
Referenced by BPY_app_ffmpeg_struct(), and make_ffmpeg_info().