Blender: rna_object_force.c File Reference
rna_object_force.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_cloth_types.h"
#include "DNA_object_types.h"
#include "DNA_object_force.h"
#include "DNA_particle_types.h"
#include "DNA_scene_types.h"
#include "DNA_smoke_types.h"
#include "WM_api.h"
#include "WM_types.h"
Functions
static void rna_def_ptcache_point_caches (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_pointcache (BlenderRNA *brna)
static void rna_def_collision (BlenderRNA *brna)
static void rna_def_effector_weight (BlenderRNA *brna)
static void rna_def_field (BlenderRNA *brna)
static void rna_def_game_softbody (BlenderRNA *brna)
static void rna_def_softbody (BlenderRNA *brna)
void RNA_def_object_force (BlenderRNA *brna)
Variables
static EnumPropertyItem effector_shape_items []
Detailed Description
Definition in file rna_object_force.c.
Function Documentation
static void rna_def_collision (BlenderRNA * brna) [static]
Definition at line 851 of file rna_object_force.c.
References NULL, PDEFLE_KILL_PART, PROP_BOOLEAN, PROP_FACTOR, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_object_force().
static void rna_def_effector_weight (BlenderRNA * brna) [static]
Definition at line 937 of file rna_object_force.c.
References EFF_WEIGHT_DO_HAIR, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_object_force().
static void rna_def_field (BlenderRNA * brna) [static]
Definition at line 1060 of file rna_object_force.c.
References field_type_items, NULL, PFIELD_BOID, PFIELD_CHARGE, PFIELD_DO_LOCATION, PFIELD_DO_ROTATION, PFIELD_DRAG, PFIELD_FALL_CONE, PFIELD_FALL_SPHERE, PFIELD_FALL_TUBE, PFIELD_FORCE, PFIELD_GLOBAL_CO, PFIELD_GUIDE, PFIELD_GUIDE_PATH_ADD, PFIELD_GUIDE_PATH_WEIGHT, PFIELD_HARMONIC, PFIELD_LENNARDJ, PFIELD_MAGNET, PFIELD_MULTIPLE_SPRINGS, PFIELD_TEX_2D, PFIELD_TEX_CURL, PFIELD_TEX_GRAD, PFIELD_TEX_OBJECT, PFIELD_TEX_RGB, PFIELD_TEX_ROOTCO, PFIELD_TEXTURE, PFIELD_TURBULENCE, PFIELD_USEMAX, PFIELD_USEMAXR, PFIELD_USEMIN, PFIELD_USEMINR, PFIELD_VISIBILITY, PFIELD_VORTEX, PFIELD_WIND, PFIELD_Z_BOTH, PFIELD_Z_NEG, PFIELD_Z_POS, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_object_force().
static void rna_def_game_softbody (BlenderRNA * brna) [static]
Definition at line 1413 of file rna_object_force.c.
References NULL, OB_BSB_BENDING_CONSTRAINTS, OB_BSB_COL_CL_RS, OB_BSB_COL_CL_SS, OB_BSB_SHAPE_MATCHING, PROP_BOOLEAN, PROP_DISTANCE, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_object_force().
void RNA_def_object_force (BlenderRNA * brna)
Definition at line 1794 of file rna_object_force.c.
References rna_def_collision(), rna_def_effector_weight(), rna_def_field(), rna_def_game_softbody(), rna_def_pointcache(), and rna_def_softbody().
static void rna_def_pointcache (BlenderRNA * brna) [static]
Definition at line 746 of file rna_object_force.c.
References MAXFRAME, NC_OBJECT, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_DIRPATH, PROP_EDITABLE, PROP_ENUM, PROP_INT, PROP_NONE, PROP_STRING, PROP_TIME, PTCACHE_BAKED, PTCACHE_BAKING, PTCACHE_COMPRESS_LZMA, PTCACHE_COMPRESS_LZO, PTCACHE_COMPRESS_NO, PTCACHE_DISK_CACHE, PTCACHE_EXTERNAL, PTCACHE_FRAMES_SKIPPED, PTCACHE_IGNORE_LIBPATH, PTCACHE_OUTDATED, PTCACHE_QUICK_CACHE, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_enum_items(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), rna_def_ptcache_point_caches(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_object_force().
static void rna_def_ptcache_point_caches (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 725 of file rna_object_force.c.
References NC_OBJECT, NULL, PROP_INT, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_int_funcs(), RNA_def_property_srna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_pointcache().
static void rna_def_softbody (BlenderRNA * brna) [static]
Definition at line 1485 of file rna_object_force.c.
References FLT_MAX, NULL, PROP_ACCELERATION, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_MATRIX, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_TRANSLATION, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_multi_array(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), RNA_TRANSLATION_PREC_DEFAULT, SBC_MODE_AVG, SBC_MODE_AVGMINMAX, SBC_MODE_MANUAL, SBC_MODE_MAX, SBC_MODE_MIN, SBSO_ESTIMATEIPO, SBSO_MONITOR, and SBSO_OLDERR.
Referenced by RNA_def_object_force().
Variable Documentation
EnumPropertyItem effector_shape_items[] [static]
Initial value:
 {
    {PFIELD_SHAPE_POINT, "POINT", 0, "Point", ""},
    {PFIELD_SHAPE_PLANE, "PLANE", 0, "Plane", ""},
    {PFIELD_SHAPE_SURFACE, "SURFACE", 0, "Surface", ""},
    {PFIELD_SHAPE_POINTS, "POINTS", 0, "Every Point", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 44 of file rna_object_force.c.