Blender: MT_Plane3 Class Reference
MT_Plane3 Class Reference
#include <MT_Plane3.h>
Public Member Functions
MT_Plane3 (const MT_Vector3 &a, const MT_Vector3 &b, const MT_Vector3 &c)
MT_Plane3 (const MT_Vector3 &n, const MT_Vector3 &p)
MT_Plane3 ()
MT_Plane3 (const MT_Plane3 &p)
MT_Vector3 Normal () const
MT_Scalar Scalar () const
void Invert ()
MT_Plane3 & operator= (const MT_Plane3 &rhs)
MT_Scalar signedDistance (const MT_Vector3 &) const
Detailed Description
A simple 3d plane class.
This class represents a plane in 3d. The internal parameterization used is n.x + d =0 where n is a unit vector and d is a scalar.
It inherits data from MT_Tuple4 please see this class for low level access to the internal representation.
Definition at line 50 of file MT_Plane3.h.
Constructor & Destructor Documentation
GEN_INLINE MT_Plane3::MT_Plane3 (const MT_Vector3 & a, const MT_Vector3 & b, const MT_Vector3 & c)
Constructor from 3 points
Definition at line 6 of file MT_Plane3.inl.
References MT_Vector3::cross(), MT_Vector3::dot(), MT_Tuple4::m_co, MT_Vector3::safe_normalized(), MT_Tuple3::x(), MT_Tuple3::y(), and MT_Tuple3::z().
GEN_INLINE MT_Plane3::MT_Plane3 (const MT_Vector3 & n, const MT_Vector3 & p)
Construction from vector and a point.
Definition at line 29 of file MT_Plane3.inl.
References MT_Vector3::dot(), MT_Tuple4::m_co, MT_Vector3::safe_normalized(), MT_Tuple3::x(), MT_Tuple3::y(), and MT_Tuple3::z().
GEN_INLINE MT_Plane3::MT_Plane3 ()
Default constructor
Definition at line 49 of file MT_Plane3.inl.
References MT_Tuple4::m_co.
MT_Plane3::MT_Plane3 (const MT_Plane3 & p) [inline]
Default constructor
Definition at line 81 of file MT_Plane3.h.
Member Function Documentation
GEN_INLINE void MT_Plane3::Invert ()
Invert the plane - just swaps direction of normal.
Definition at line 86 of file MT_Plane3.inl.
References MT_Tuple4::m_co.
Referenced by BSP_MFace::Invert(), and BOP_Face::invert().
GEN_INLINE MT_Vector3 MT_Plane3::Normal () const
Return plane normal
Definition at line 66 of file MT_Plane3.inl.
References MT_Tuple4::m_co.
Referenced by BOP_getCircleCenter(), and signedDistance().
GEN_INLINE MT_Plane3 & MT_Plane3::operator= (const MT_Plane3 & rhs)
Assignment operator
Definition at line 102 of file MT_Plane3.inl.
References MT_Tuple4::m_co.
GEN_INLINE MT_Scalar MT_Plane3::Scalar () const
Return plane scalar i.e the d from n.x + d = 0
Definition at line 78 of file MT_Plane3.inl.
References MT_Tuple4::m_co.
GEN_INLINE MT_Scalar MT_Plane3::signedDistance (const MT_Vector3 & v) const
Return the signed perpendicular distance from a point to the plane
Return the distance from a point to the plane
Definition at line 119 of file MT_Plane3.inl.
References MT_Vector3::dot(), MT_Tuple4::m_co, and Normal().
Referenced by BOP_classify(), BOP_containsPoint(), and BSP_CSGMesh::SC_Face().
The documentation for this class was generated from the following files:
MT_Plane3.h
MT_Plane3.inl