Blender: poseUtils.c File Reference
poseUtils.c File Reference
armature
#include <stdlib.h>
#include <stdio.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_dynstr.h"
#include "BLI_dlrbTree.h"
#include "BLI_utildefines.h"
#include "DNA_anim_types.h"
#include "DNA_armature_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BKE_action.h"
#include "BKE_armature.h"
#include "BKE_depsgraph.h"
#include "BKE_idprop.h"
#include "BKE_context.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_armature.h"
#include "ED_keyframing.h"
#include "armature_intern.h"
Functions
static void fcurves_to_pchan_links_get (ListBase *pfLinks, Object *ob, bAction *act, bPoseChannel *pchan)
void poseAnim_mapping_get (bContext *C, ListBase *pfLinks, Object *ob, bAction *act)
void poseAnim_mapping_free (ListBase *pfLinks)
void poseAnim_mapping_refresh (bContext *C, Scene *scene, Object *ob)
void poseAnim_mapping_reset (ListBase *pfLinks)
void poseAnim_mapping_autoKeyframe (bContext *C, Scene *scene, Object *ob, ListBase *pfLinks, float cframe)
LinkData * poseAnim_mapping_getNextFCurve (ListBase *fcuLinks, LinkData *prev, const char *path)
Detailed Description
Definition in file poseUtils.c.
Function Documentation
static void fcurves_to_pchan_links_get (ListBase * pfLinks, Object * ob, bAction * act, bPoseChannel * pchan) [static]
Definition at line 82 of file poseUtils.c.
References ACT_TRANS_LOC, ACT_TRANS_PROP, ACT_TRANS_ROT, ACT_TRANS_SCALE, action_get_item_transforms(), BLI_addtail(), copy_qt_qt(), copy_v3_v3(), bPoseChannel::eul, tPChanFCurveLink::fcurves, bPoseChannel::flag, IDP_CopyProperty(), bPoseChannel::loc, MEM_callocN(), NULL, tPChanFCurveLink::oldangle, tPChanFCurveLink::oldaxis, tPChanFCurveLink::oldloc, tPChanFCurveLink::oldprops, tPChanFCurveLink::oldquat, tPChanFCurveLink::oldrot, tPChanFCurveLink::oldscale, tPChanFCurveLink::pchan, tPChanFCurveLink::pchan_path, POSE_LOC, POSE_ROT, POSE_SIZE, bPoseChannel::prop, bPoseChannel::quat, RNA_path_from_ID_to_struct(), RNA_pointer_create(), RNA_PoseBone, bPoseChannel::rotAngle, bPoseChannel::rotAxis, and bPoseChannel::size.
Referenced by poseAnim_mapping_get().
void poseAnim_mapping_autoKeyframe (bContext * C, Scene * scene, Object * ob, ListBase * pfLinks, float cframe)
Definition at line 222 of file poseUtils.c.
References ANIM_apply_keyingset(), ANIM_get_keyingset_for_autokeying(), ANIM_KS_WHOLE_CHARACTER_ID, ANIM_relative_keyingset_add_source(), autokeyframe_cfra_can_key(), bPose::avs, BLI_freelistN(), bPoseChannel::bone, BONE_UNKEYED, ED_pose_recalculate_paths(), ListBase::first, Bone::flag, Object::id, MODIFYKEY_MODE_INSERT, MOTIONPATH_BAKE_HAS_PATHS, tPChanFCurveLink::next, NULL, bAnimVizSettings::path_bakeflag, tPChanFCurveLink::pchan, Object::pose, and RNA_PoseBone.
Referenced by pose_slide_autoKeyframe().
void poseAnim_mapping_free (ListBase * pfLinks)
Definition at line 153 of file poseUtils.c.
References BLI_freelinkN(), BLI_freelistN(), tPChanFCurveLink::fcurves, ListBase::first, IDP_FreeProperty(), MEM_freeN(), tPChanFCurveLink::next, NULL, tPChanFCurveLink::oldprops, and tPChanFCurveLink::pchan_path.
Referenced by pose_slide_exit().
void poseAnim_mapping_get (bContext * C, ListBase * pfLinks, Object * ob, bAction * act)
Definition at line 129 of file poseUtils.c.
References CTX_DATA_BEGIN, CTX_DATA_END, fcurves_to_pchan_links_get(), ListBase::first, and NULL.
Referenced by pose_slide_init().
LinkData* poseAnim_mapping_getNextFCurve (ListBase * fcuLinks, LinkData * prev, const char * path)
Definition at line 265 of file poseUtils.c.
References LinkData::data, ListBase::first, if(), LinkData::next, NULL, and FCurve::rna_path.
Referenced by pose_slide_apply_quat(), and pose_slide_apply_vec3().
void poseAnim_mapping_refresh (bContext * C, Scene * scene, Object * ob)
Definition at line 181 of file poseUtils.c.
References ARM_DELAYDEFORM, DAG_id_tag_update(), Object::data, bArmature::flag, Object::id, if(), NC_OBJECT, ND_POSE, OB_RECALC_DATA, where_is_pose(), and WM_event_add_notifier().
Referenced by pose_slide_refresh().
void poseAnim_mapping_reset (ListBase * pfLinks)
Definition at line 199 of file poseUtils.c.
References copy_qt_qt(), copy_v3_v3(), bPoseChannel::eul, ListBase::first, IDP_SyncGroupValues(), bPoseChannel::loc, tPChanFCurveLink::next, tPChanFCurveLink::oldangle, tPChanFCurveLink::oldaxis, tPChanFCurveLink::oldloc, tPChanFCurveLink::oldprops, tPChanFCurveLink::oldquat, tPChanFCurveLink::oldrot, tPChanFCurveLink::oldscale, tPChanFCurveLink::pchan, bPoseChannel::prop, bPoseChannel::quat, bPoseChannel::rotAngle, bPoseChannel::rotAxis, and bPoseChannel::size.
Referenced by pose_slide_reset().