Blender: CErrorValue Class Reference
CErrorValue Class Reference
#include <ErrorValue.h>
Public Member Functions
virtual const STR_String & GetText ()
virtual double GetNumber ()
CErrorValue ()
CErrorValue (const char *errmsg)
virtual ~CErrorValue ()
virtual CValue * Calc (VALUE_OPERATOR op, CValue *val)
virtual CValue * CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue *val)
virtual CValue * GetReplica ()
Detailed Description
Definition at line 24 of file ErrorValue.h.
Constructor & Destructor Documentation
CErrorValue::CErrorValue ()
Definition at line 24 of file ErrorValue.cpp.
References CValue::SetError().
Referenced by Calc(), and CalcFinal().
CErrorValue::CErrorValue (const char * errmsg)
Definition at line 36 of file ErrorValue.cpp.
References CValue::SetError().
CErrorValue::~CErrorValue () [virtual]
Definition at line 50 of file ErrorValue.cpp.
Member Function Documentation
CValue * CErrorValue::Calc (VALUE_OPERATOR op, CValue * val) [virtual]
Implements CValue.
Definition at line 61 of file ErrorValue.cpp.
References CValue::CalcFinal(), CErrorValue(), GetText(), CValue::op2str(), VALUE_ERROR_TYPE, VALUE_NEG_OPERATOR, VALUE_NOT_OPERATOR, and VALUE_POS_OPERATOR.
CValue * CErrorValue::CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue * val) [virtual]
Implements CValue.
Definition at line 91 of file ErrorValue.cpp.
References CErrorValue(), GetText(), CValue::GetText(), and CValue::op2str().
double CErrorValue::GetNumber () [virtual]
Implements CValue.
Definition at line 103 of file ErrorValue.cpp.
CValue * CErrorValue::GetReplica (void) [virtual]
Implements CValue.
Definition at line 117 of file ErrorValue.cpp.
References assertd, NULL, and trace.
const STR_String & CErrorValue::GetText () [virtual]
Implements CValue.
Definition at line 110 of file ErrorValue.cpp.
Referenced by Calc(), and CalcFinal().
The documentation for this class was generated from the following files:
ErrorValue.h
ErrorValue.cpp