Blender: SG_DList::const_iterator< T > Class Template Reference
SG_DList::const_iterator< T > Class Template Reference
#include <SG_DList.h>
Public Types
typedef const_iterator< T > _myT
Public Member Functions
const_iterator (const SG_DList &head)
~const_iterator ()
void begin ()
void back ()
bool end ()
const T * operator* ()
_myT & operator++ ()
_myT & operator-- ()
Detailed Description
template<typename T>
class SG_DList::const_iterator< T >
Definition at line 95 of file SG_DList.h.
Member Typedef Documentation
template<typename T> typedef const_iterator<T> SG_DList::const_iterator< T >::_myT
Definition at line 101 of file SG_DList.h.
Constructor & Destructor Documentation
template<typename T> SG_DList::const_iterator< T >::const_iterator (const SG_DList & head) [inline]
Definition at line 102 of file SG_DList.h.
template<typename T> SG_DList::const_iterator< T >::~const_iterator () [inline]
Definition at line 103 of file SG_DList.h.
Member Function Documentation
template<typename T> void SG_DList::const_iterator< T >::back () [inline]
Definition at line 109 of file SG_DList.h.
References SG_DList::Back(), and T.
template<typename T> void SG_DList::const_iterator< T >::begin () [inline]
Definition at line 105 of file SG_DList.h.
References SG_DList::Peek(), and T.
Referenced by SG_DListHead< BL_ArmatureConstraint >::SG_DListHead().
template<typename T> bool SG_DList::const_iterator< T >::end () [inline]
Definition at line 113 of file SG_DList.h.
References SG_DList::Self(), and T.
Referenced by SG_DListHead< BL_ArmatureConstraint >::SG_DListHead().
template<typename T> const T* SG_DList::const_iterator< T >::operator* () [inline]
Definition at line 117 of file SG_DList.h.
template<typename T> _myT& SG_DList::const_iterator< T >::operator++ () [inline]
Definition at line 121 of file SG_DList.h.
References T.
template<typename T> _myT& SG_DList::const_iterator< T >::operator-- () [inline]
Definition at line 127 of file SG_DList.h.
References T.
The documentation for this class was generated from the following file:
SG_DList.h