Blender: AnimChannel< Scalar > Class Template Reference
AnimChannel< Scalar > Class Template Reference
An animated attribute channel.
#include <attributes.h>
Public Member Functions
AnimChannel ()
AnimChannel (Scalar null)
AnimChannel (vector< Scalar > &v, vector< double > &t)
~AnimChannel ()
Scalar get (double t) const
Scalar getConstant (double t) const
void reset (Scalar null)
string printChannel ()
debug function, prints channel as string
void debugPrintChannel ()
debug function, prints to stdout if DEBUG_CHANNELS flag is enabled, used in constructors
bool isInited () const
valid init?
int getSize () const
get number of entries (value and time sizes have to be equal)
vector< Scalar > & accessValues ()
raw access of value vector
vector< double > & accessTimes ()
raw access of time vector
Protected Attributes
bool mInited
vector< Scalar > mValue
vector< double > mTimes
Detailed Description
template<class Scalar>
class AnimChannel< Scalar >
An animated attribute channel.
Definition at line 25 of file attributes.h.
Constructor & Destructor Documentation
template<class Scalar> AnimChannel< Scalar >::AnimChannel () [inline]
Definition at line 29 of file attributes.h.
template<class Scalar> AnimChannel< Scalar >::AnimChannel (Scalar null) [inline]
Definition at line 33 of file attributes.h.
template<class Scalar> AnimChannel< Scalar >::AnimChannel (vector< Scalar > & v, vector< double > & t) [inline]
Definition at line 37 of file attributes.h.
template<class Scalar> AnimChannel< Scalar >::~AnimChannel () [inline]
Definition at line 41 of file attributes.h.
Member Function Documentation
template<class Scalar> vector<double>& AnimChannel< Scalar >::accessTimes () [inline]
raw access of time vector
Definition at line 103 of file attributes.h.
Referenced by channelSimplifyScalarT(), channelSimplifyVecT(), and ntlGeometryObject::initChannels().
template<class Scalar> vector<Scalar>& AnimChannel< Scalar >::accessValues () [inline]
raw access of value vector
Definition at line 101 of file attributes.h.
Referenced by ntlGeometryObject::applyTransformation(), ntlGeometryObjModel::calcTriangleDivs(), channelFindMaxd(), channelFindMaxf(), channelFindMaxi(), channelFindMaxVd(), channelFindMaxVf(), channelSimplifyScalarT(), channelSimplifyVecT(), ntlGeometryObject::checkIsAnimated(), ntlGeometryObjModel::getExtends(), ntlGeometryObject::initChannels(), ntlGeometryObjModel::initModel(), ntlGeometryObject::initMovingPoints(), and ntlGeometryObjModel::loadBobjModel().
template<class Scalar > void AnimChannel< Scalar >::debugPrintChannel ()
debug function, prints to stdout if DEBUG_CHANNELS flag is enabled, used in constructors
debug function, prints to stdout if DEBUG_PCHANNELS flag is enabled, used in constructors
Definition at line 218 of file attributes.h.
Referenced by __forceAnimChannelInstantiation(), and AnimChannel< ntlVec3f >::AnimChannel().
template<class Scalar> Scalar AnimChannel< Scalar >::get (double t) const [inline]
Definition at line 44 of file attributes.h.
Referenced by ntlGeometryObject::applyTransformation(), Parametrizer::calculateAllMissingValues(), Parametrizer::calculateGravity(), Parametrizer::calculateLatticeViscosity(), Parametrizer::getAniFrameTime(), ntlGeometryObject::getGeoActive(), ntlGeometryObject::getGeoImpactFactor(), Parametrizer::getGravity(), ntlGeometryObject::getInitialVelocity(), ntlGeometryObject::getTranslation(), ntlGeometryObjModel::getTriangles(), LbmFsgrSolver::handleCpdata(), ntlGeometryObjModel::loadBobjModel(), and LbmControlData::parseControldataAttrList().
template<class Scalar> Scalar AnimChannel< Scalar >::getConstant (double t) const [inline]
Definition at line 69 of file attributes.h.
template<class Scalar> int AnimChannel< Scalar >::getSize (void) const [inline]
get number of entries (value and time sizes have to be equal)
Definition at line 99 of file attributes.h.
Referenced by channelSimplifyScalarT(), channelSimplifyVecT(), ntlGeometryObjModel::getMeshAnimated(), ntlGeometryObjModel::getTriangles(), and ntlGeometryObjModel::loadBobjModel().
template<class Scalar> bool AnimChannel< Scalar >::isInited () const [inline]
valid init?
Definition at line 96 of file attributes.h.
Referenced by ntlGeometryObjModel::initialize(), and ntlGeometryObject::initialize().
template<class Scalar > string AnimChannel< Scalar >::printChannel ()
debug function, prints channel as string
Definition at line 281 of file attributes.cpp.
References i.
Referenced by Parametrizer::initAniFrameTimeChannel(), Parametrizer::initGravityChannel(), Parametrizer::initViscosityChannel(), Parametrizer::setAniFrameTimeChannel(), Parametrizer::setGravity(), and Parametrizer::setViscosity().
template<class Scalar> void AnimChannel< Scalar >::reset (Scalar null) [inline]
Definition at line 84 of file attributes.h.
Member Data Documentation
template<class Scalar> bool AnimChannel< Scalar >::mInited [protected]
inited at least once?
Definition at line 108 of file attributes.h.
Referenced by AnimChannel< ntlVec3f >::AnimChannel(), AnimChannel< ntlVec3f >::get(), AnimChannel< ntlVec3f >::getConstant(), and AnimChannel< ntlVec3f >::isInited().
template<class Scalar> vector<double> AnimChannel< Scalar >::mTimes [protected]
anim channel attr times
Definition at line 112 of file attributes.h.
Referenced by AnimChannel< ntlVec3f >::accessTimes(), AnimChannel< ntlVec3f >::AnimChannel(), AnimChannel< ntlVec3f >::get(), AnimChannel< ntlVec3f >::getConstant(), and AnimChannel< ntlVec3f >::reset().
template<class Scalar> vector<Scalar> AnimChannel< Scalar >::mValue [protected]
anim channel attribute values
Definition at line 110 of file attributes.h.
Referenced by AnimChannel< ntlVec3f >::accessValues(), AnimChannel< ntlVec3f >::AnimChannel(), AnimChannel< ntlVec3f >::get(), AnimChannel< ntlVec3f >::getConstant(), AnimChannel< ntlVec3f >::getSize(), and AnimChannel< ntlVec3f >::reset().
The documentation for this class was generated from the following files:
attributes.h
attributes.cpp