Blender: logImageCore.c File Reference
logImageCore.c File Reference
Cineon
#include "logImageCore.h"
#include <time.h>
#include <math.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <sys/param.h>
Classes
union Hack
Defines
#define rint(x) floor(x+0.5)
#define UNDEF_FLOAT 0x7F800000
Functions
static double convertTo (int inp, int white, float gamma)
static double convertFrom (double inp, int white, float gamma)
void setupLut (LogImageFile *logImage)
void setupLut16 (LogImageFile *logImage)
int pixelsToLongs (int numPixels)
R32 htonf (R32 f)
R32 ntohf (R32 f)
R32 undefined (void)
U16 reverseU16 (U16 value)
U32 reverseU32 (U32 value)
R32 reverseR32 (R32 value)
Detailed Description
Definition in file logImageCore.c.
Define Documentation
#define rint (x) floor(x+0.5)
Definition at line 30 of file logImageCore.c.
Referenced by setupLut(), and setupLut16().
#define UNDEF_FLOAT 0x7F800000
Definition at line 157 of file logImageCore.c.
Referenced by undefined().
Function Documentation
static double convertFrom (double inp, int white, float gamma) [static]
Definition at line 66 of file logImageCore.c.
Referenced by setupLut(), and setupLut16().
static double convertTo (int inp, int white, float gamma) [static]
Definition at line 60 of file logImageCore.c.
References pow().
Referenced by setupLut(), and setupLut16().
R32 htonf (R32 f)
Definition at line 142 of file logImageCore.c.
References Hack::f, and Hack::i.
Referenced by fillCineonChannelInfo(), fillCineonImageInfo(), fillCineonOriginationInfo(), and fillDpxChannelInfo().
R32 ntohf (R32 f)
Definition at line 150 of file logImageCore.c.
References Hack::f, and Hack::i.
Referenced by dumpCineonChannelInfo(), dumpCineonImageInfo(), dumpCineonOriginationInfo(), dumpDpxChannelInfo(), and dumpDpxOriginationInfo().
int pixelsToLongs (int numPixels)
Definition at line 130 of file logImageCore.c.
Referenced by cineonCreate(), cineonOpen(), cineonOpenFromMem(), dpxCreate(), dpxGetRowBytes(), dpxSetRowBytes(), fillDpxFileInfo(), intern_dpxOpen(), and verboseMe().
R32 reverseR32 (R32 value)
Definition at line 203 of file logImageCore.c.
U16 reverseU16 (U16 value)
Definition at line 168 of file logImageCore.c.
U32 reverseU32 (U32 value)
Definition at line 184 of file logImageCore.c.
void setupLut (LogImageFile * logImage)
Definition at line 72 of file logImageCore.c.
References LogImageByteConversionParameters::blackPoint, convertFrom(), convertTo(), LogImageByteConversionParameters::gamma, i, _Log_Image_File_t_::lut10, _Log_Image_File_t_::lut8, _Log_Image_File_t_::params, rint, and LogImageByteConversionParameters::whitePoint.
Referenced by cineonCreate(), cineonOpen(), cineonOpenFromMem(), dpxCreate(), and intern_dpxOpen().
void setupLut16 (LogImageFile * logImage)
Definition at line 101 of file logImageCore.c.
References LogImageByteConversionParameters::blackPoint, convertFrom(), convertTo(), LogImageByteConversionParameters::gamma, i, _Log_Image_File_t_::lut10_16, _Log_Image_File_t_::lut16_16, _Log_Image_File_t_::params, rint, and LogImageByteConversionParameters::whitePoint.
Referenced by logImageSetByteConversion().
R32 undefined (void)
Definition at line 160 of file logImageCore.c.
References Hack::f, Hack::i, and UNDEF_FLOAT.
Referenced by fillCineonImageInfo(), and fillCineonOriginationInfo().