Blender: LayerTypeInfo Struct Reference
LayerTypeInfo Struct Reference
Public Attributes
int size
const char * structname
int structnum
const char * defaultname
void(* copy)(const void *source, void *dest, int count)
void(* free)(void *data, int count, int size)
void(* interp)(void **sources, float *weights, float *sub_weights, int count, void *dest)
void(* swap)(void *data, const int *corner_indices)
void(* set_default)(void *data, int count)
int(* equal)(void *data1, void *data2)
void(* multiply)(void *data, float fac)
void(* initminmax)(void *min, void *max)
void(* add)(void *data1, void *data2)
void(* dominmax)(void *data1, void *min, void *max)
void(* copyvalue)(void *source, void *dest)
int(* read)(CDataFile *cdf, void *data, int count)
int(* write)(CDataFile *cdf, void *data, int count)
size_t(* filesize)(CDataFile *cdf, void *data, int count)
Detailed Description
Definition at line 70 of file customdata.c.
Member Data Documentation
void(* LayerTypeInfo::add)(void *data1, void *data2)
Definition at line 112 of file customdata.c.
Referenced by CustomData_data_add(), and CustomData_layer_has_math().
void(* LayerTypeInfo::copy)(const void *source, void *dest, int count)
Definition at line 80 of file customdata.c.
Referenced by customData_add_layer__internal(), CustomData_bmesh_copy_data(), CustomData_bmesh_set(), CustomData_bmesh_set_layer_n(), CustomData_bmesh_set_n(), CustomData_copy_data(), CustomData_copy_elements(), CustomData_duplicate_referenced_layer(), CustomData_duplicate_referenced_layer_named(), CustomData_from_bmesh_block(), CustomData_set(), and CustomData_to_bmesh_block().
void(* LayerTypeInfo::copyvalue)(void *source, void *dest)
Definition at line 114 of file customdata.c.
Referenced by CustomData_data_copy_value().
const char* LayerTypeInfo::defaultname
Definition at line 74 of file customdata.c.
Referenced by CustomData_add_layer(), customData_add_layer__internal(), CustomData_set_layer_unique_name(), and CustomData_verify_versions().
void(* LayerTypeInfo::dominmax)(void *data1, void *min, void *max)
Definition at line 113 of file customdata.c.
Referenced by CustomData_data_dominmax(), and CustomData_layer_has_math().
int(* LayerTypeInfo::equal)(void *data1, void *data2)
Definition at line 109 of file customdata.c.
Referenced by CustomData_data_equals(), and CustomData_layer_has_math().
size_t(* LayerTypeInfo::filesize)(CDataFile *cdf, void *data, int count)
Definition at line 123 of file customdata.c.
Referenced by CustomData_external_write().
void(* LayerTypeInfo::free)(void *data, int count, int size)
Definition at line 87 of file customdata.c.
Referenced by CustomData_bmesh_free_block(), CustomData_external_reload(), CustomData_external_write(), CustomData_free_elem(), and customData_free_layer__internal().
void(* LayerTypeInfo::initminmax)(void *min, void *max)
Definition at line 111 of file customdata.c.
Referenced by CustomData_data_initminmax(), and CustomData_layer_has_math().
void(* LayerTypeInfo::interp)(void **sources, float *weights, float *sub_weights, int count, void *dest)
Definition at line 98 of file customdata.c.
Referenced by CustomData_bmesh_interp(), and CustomData_interp().
void(* LayerTypeInfo::multiply)(void *data, float fac)
Definition at line 110 of file customdata.c.
Referenced by CustomData_data_multiply(), and CustomData_layer_has_math().
int(* LayerTypeInfo::read)(CDataFile *cdf, void *data, int count)
Definition at line 117 of file customdata.c.
Referenced by CustomData_external_read().
void(* LayerTypeInfo::set_default)(void *data, int count)
Definition at line 106 of file customdata.c.
Referenced by customData_add_layer__internal(), and CustomData_bmesh_set_default().
int LayerTypeInfo::size
Definition at line 71 of file customdata.c.
Referenced by customData_add_layer__internal(), CustomData_bmesh_copy_data(), CustomData_bmesh_free_block(), CustomData_bmesh_set(), CustomData_bmesh_set_default(), CustomData_bmesh_set_layer_n(), CustomData_bmesh_set_n(), CustomData_copy_data(), CustomData_copy_elements(), CustomData_data_copy_value(), CustomData_data_equals(), CustomData_duplicate_referenced_layer(), CustomData_duplicate_referenced_layer_named(), CustomData_external_reload(), CustomData_external_write(), CustomData_free_elem(), customData_free_layer__internal(), CustomData_from_bmesh_block(), CustomData_get(), CustomData_get_n(), CustomData_interp(), CustomData_set(), CustomData_sizeof(), CustomData_swap(), CustomData_to_bmesh_block(), and customData_update_offsets().
const char* LayerTypeInfo::structname
Definition at line 72 of file customdata.c.
Referenced by CustomData_file_write_info().
int LayerTypeInfo::structnum
Definition at line 73 of file customdata.c.
Referenced by CustomData_file_write_info().
void(* LayerTypeInfo::swap)(void *data, const int *corner_indices)
Definition at line 102 of file customdata.c.
Referenced by CustomData_swap().
int(* LayerTypeInfo::write)(CDataFile *cdf, void *data, int count)
Definition at line 120 of file customdata.c.
Referenced by CustomData_external_write().
The documentation for this struct was generated from the following file:
customdata.c