Blender: KX_OrientationInterpolator Class Reference
KX_OrientationInterpolator Class Reference
#include <KX_OrientationInterpolator.h>
Public Member Functions
KX_OrientationInterpolator (MT_Matrix3x3 &target, KX_IScalarInterpolator **ipos)
virtual void Execute (float currentTime) const
Detailed Description
Definition at line 40 of file KX_OrientationInterpolator.h.
Constructor & Destructor Documentation
KX_OrientationInterpolator::KX_OrientationInterpolator (MT_Matrix3x3 & target, KX_IScalarInterpolator ** ipos) [inline]
Definition at line 42 of file KX_OrientationInterpolator.h.
Member Function Documentation
void KX_OrientationInterpolator::Execute (float currentTime) const [virtual]
Implements KX_IInterpolator.
Definition at line 37 of file KX_OrientationInterpolator.cpp.
References cos(), MT_Matrix3x3::setValue(), si, and sin().
The documentation for this class was generated from the following files:
KX_OrientationInterpolator.h
KX_OrientationInterpolator.cpp