Blender: MOD_util.c File Reference
MOD_util.c File Reference
modifiers
#include <string.h>
#include "DNA_curve_types.h"
#include "DNA_image_types.h"
#include "DNA_lattice_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_modifier_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_utildefines.h"
#include "BLI_math_vector.h"
#include "BLI_math_matrix.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_deform.h"
#include "BKE_image.h"
#include "BKE_lattice.h"
#include "BKE_mesh.h"
#include "BKE_displist.h"
#include "BKE_modifier.h"
#include "MOD_util.h"
#include "MOD_modifiertypes.h"
#include "MEM_guardedalloc.h"
#include "RE_shader_ext.h"
Defines
#define INIT_TYPE(typeName) (types[eModifierType_##typeName] = &modifierType_##typeName)
Functions
void modifier_init_texture (Scene *scene, Tex *tex)
void get_texture_value (Tex *texture, float *tex_co, TexResult *texres)
void get_texture_coords (MappingInfoModifierData *dmd, Object *ob, DerivedMesh *dm, float(*co)[3], float(*texco)[3], int numVerts)
void modifier_vgroup_cache (ModifierData *md, float(*vertexCos)[3])
DerivedMesh * get_cddm (Object *ob, struct BMEditMesh *em, DerivedMesh *dm, float(*vertexCos)[3])
DerivedMesh * get_dm (Object *ob, struct BMEditMesh *em, DerivedMesh *dm, float(*vertexCos)[3], int orco)
void modifier_get_vgroup (Object *ob, DerivedMesh *dm, const char *name, MDeformVert **dvert, int *defgrp_index)
void modifier_type_init (ModifierTypeInfo *types[])
Detailed Description
Definition in file MOD_util.c.
Define Documentation
#define INIT_TYPE (typeName) (types[eModifierType_##typeName] = &modifierType_##typeName)
Referenced by modifier_type_init(), and node_socket_type_init().
Function Documentation
DerivedMesh* get_cddm (Object * ob, struct BMEditMesh * em, DerivedMesh * dm, float(*) vertexCos[3]) [read]
Definition at line 175 of file MOD_util.c.
References CDDM_apply_vert_coords(), CDDM_calc_normals(), CDDM_copy(), DM_TYPE_CDDM, get_dm(), and DerivedMesh::type.
Referenced by deformVerts(), and deformVertsEM().
DerivedMesh* get_dm (Object * ob, struct BMEditMesh * em, DerivedMesh * dm, float(*) vertexCos[3], int orco) [read]
Definition at line 195 of file MOD_util.c.
References CD_ASSIGN, CD_ORCO, CDDM_apply_vert_coords(), CDDM_from_BMEditMesh(), CDDM_from_curve(), CDDM_from_mesh(), Object::data, DM_add_vert_layer(), ELEM3, FALSE, get_mesh_orco_verts(), OB_CURVE, OB_FONT, OB_MESH, OB_SURF, and Object::type.
Referenced by deformVerts(), deformVertsEM(), get_cddm(), and meshdeformModifier_do().
void get_texture_coords (MappingInfoModifierData * dmd, Object * ob, DerivedMesh * dm, float(*) co[3], float(*) texco[3], int numVerts)
Definition at line 90 of file MOD_util.c.
References CD_MLOOPUV, co, copy_v3_v3(), CustomData_get_layer_named(), CustomData_has_layer(), CustomData_validate_layer_name(), DerivedMesh::getLoopArray, DerivedMesh::getNumPolys, DerivedMesh::getPolyArray, i, invert_m4_m4(), DerivedMesh::loopData, MPoly::loopstart, MappingInfoModifierData::map_object, MAX_CUSTOMDATA_LAYER_NAME, MEM_callocN(), MEM_freeN(), MOD_DISP_MAP_GLOBAL, MOD_DISP_MAP_LOCAL, MOD_DISP_MAP_OBJECT, MOD_DISP_MAP_UV, mul_m4_v3(), mul_v3_m4v3(), Object::obmat, MappingInfoModifierData::texmapping, MPoly::totloop, MLoopUV::uv, MappingInfoModifierData::uvlayer_name, and MLoop::v.
Referenced by displaceModifier_do(), warpModifier_do(), waveModifier_do(), and weightvg_do_mask().
void get_texture_value (Tex * texture, float * tex_co, TexResult * texres)
Definition at line 72 of file MOD_util.c.
References multitex_ext_safe(), TexResult::tb, TEX_RGB, TexResult::tg, TexResult::tin, and TexResult::tr.
Referenced by displaceModifier_do(), warpModifier_do(), waveModifier_do(), and weightvg_do_mask().
void modifier_get_vgroup (Object * ob, DerivedMesh * dm, const char * name, MDeformVert ** dvert, int * defgrp_index)
Definition at line 219 of file MOD_util.c.
References CD_MDEFORMVERT, defgroup_name_index(), DerivedMesh::getVertDataArray, lattice_get_deform_verts(), NULL, OB_LATTICE, and Object::type.
Referenced by applyModifier(), cuboid_do(), deformVerts_do(), displaceModifier_do(), meshdeformModifier_do(), SimpleDeformModifier_do(), smoothModifier_do(), sphere_do(), warpModifier_do(), and waveModifier_do().
void modifier_init_texture (Scene * scene, Tex * tex)
Definition at line 63 of file MOD_util.c.
References BKE_image_user_calc_frame(), RenderData::cfra, ELEM, Tex::ima, IMA_SRC_MOVIE, IMA_SRC_SEQUENCE, Tex::iuser, Scene::r, and Image::source.
Referenced by displaceModifier_do(), warpModifier_do(), waveModifier_do(), and weightvg_do_mask().
void modifier_type_init (ModifierTypeInfo * types[])
Definition at line 233 of file MOD_util.c.
References Bevel(), INIT_TYPE, Mask, Mirror(), None, and Warp().
Referenced by modifierType_getInfo().
void modifier_vgroup_cache (ModifierData * md, float(*) vertexCos[3])
Definition at line 162 of file MOD_util.c.
References eModifierType_Armature, MEM_dupallocN(), ArmatureModifierData::multi, ModifierData::next, NULL, ArmatureModifierData::prevCos, and ModifierData::type.
Referenced by deformVerts(), and deformVertsEM().