Blender: btTriangleCallback Class Reference
btTriangleCallback Class Reference
#include <btTriangleCallback.h>
Public Member Functions
virtual ~btTriangleCallback ()
virtual void processTriangle (btVector3 *triangle, int partId, int triangleIndex)=0
Detailed Description
The btTriangleCallback provides a callback for each overlapping triangle when calling processAllTriangles. This callback is called by processAllTriangles for all btConcaveShape derived class, such as btBvhTriangleMeshShape, btStaticPlaneShape and btHeightfieldTerrainShape.
Definition at line 24 of file btTriangleCallback.h.
Constructor & Destructor Documentation
btTriangleCallback::~btTriangleCallback () [virtual]
Definition at line 18 of file btTriangleCallback.cpp.
Member Function Documentation
virtual void btTriangleCallback::processTriangle (btVector3 * triangle, int partId, int triangleIndex) [pure virtual]
Implemented in DebugDrawcallback, btConvexTriangleCallback, btConnectivityProcessor, btScaledTriangleCallback, btTriangleBuffer, SupportVertexCallback, btGImpactTriangleCallback, btTriangleRaycastCallback, btTriangleConvexcastCallback, and btSoftBodyTriangleCallback.
Referenced by btGImpactMeshShapePart::processAllTriangles(), btHeightfieldTerrainShape::processAllTriangles(), and btScaledTriangleCallback::processTriangle().
The documentation for this class was generated from the following files:
btTriangleCallback.h
btTriangleCallback.cpp