Blender: SG_Controller Class Reference
SG_Controller Class Reference
#include <SG_Controller.h>
Public Types
enum SG_Controller_option {
SG_CONTR_NODEF = 0, SG_CONTR_IPO_IPO_AS_FORCE, SG_CONTR_IPO_IPO_ADD, SG_CONTR_IPO_LOCAL,
SG_CONTR_IPO_RESET, SG_CONTR_CAMIPO_LENS, SG_CONTR_CAMIPO_CLIPEND, SG_CONTR_CAMIPO_CLIPSTART,
SG_CONTR_MAX
}
Public Member Functions
SG_Controller ()
virtual ~SG_Controller ()
virtual bool Update (double time)=0
virtual void SetObject (SG_IObject *object)
void ClearObject ()
virtual void SetSimulatedTime (double time)=0
virtual SG_Controller * GetReplica (class SG_Node *destnode)=0
virtual void SetOption (int option, int value)=0
Protected Attributes
SG_IObject * m_pObject
Detailed Description
A scenegraph controller
Definition at line 43 of file SG_Controller.h.
Member Enumeration Documentation
enum SG_Controller::SG_Controller_option
Option-identifiers: SG_CONTR_<controller-type>_<option>. Options only apply to a specific controller type. The semantics are defined by whoever uses the setting.
Enumerator:
SG_CONTR_NODEF
SG_CONTR_IPO_IPO_AS_FORCE
SG_CONTR_IPO_IPO_ADD
SG_CONTR_IPO_LOCAL
SG_CONTR_IPO_RESET
SG_CONTR_CAMIPO_LENS
SG_CONTR_CAMIPO_CLIPEND
SG_CONTR_CAMIPO_CLIPSTART
SG_CONTR_MAX
Definition at line 110 of file SG_Controller.h.
Constructor & Destructor Documentation
SG_Controller::SG_Controller () [inline]
Definition at line 52 of file SG_Controller.h.
virtual SG_Controller::~SG_Controller () [inline, virtual]
Definition at line 58 of file SG_Controller.h.
Member Function Documentation
void SG_Controller::ClearObject ()
Definition at line 43 of file SG_Controller.cpp.
References m_pObject, and NULL.
Referenced by KX_CameraIpoSGController::GetReplica(), KX_IpoSGController::GetReplica(), KX_ObColorIpoSGController::GetReplica(), KX_LightIpoSGController::GetReplica(), KX_MaterialIpoController::GetReplica(), and KX_WorldIpoController::GetReplica().
virtual SG_Controller* SG_Controller::GetReplica (class SG_Node * destnode) [pure virtual]
Implemented in KX_BulletPhysicsController, KX_CameraIpoSGController, KX_IPhysicsController, KX_IpoSGController, KX_LightIpoSGController, KX_MaterialIpoController, KX_ObColorIpoSGController, and KX_WorldIpoController.
Referenced by KX_Scene::AddNodeReplicaObject().
void SG_Controller::SetObject (SG_IObject * object) [virtual]
Reimplemented in KX_BulletPhysicsController, and KX_IPhysicsController.
Definition at line 36 of file SG_Controller.cpp.
References m_pObject.
Referenced by KX_Scene::AddNodeReplicaObject(), BL_ConvertCameraIpos(), BL_ConvertIpos(), BL_ConvertLampIpos(), BL_CreateIPO(), ConvertMaterialIpos(), and BL_Action::Play().
virtual void SG_Controller::SetOption (int option, int value) [pure virtual]
Hacky way of passing options to specific controllers
Parameters:
option An integer identifying the option.
value The value of this option.
Attention:
This has been placed here to give sca-elements
some control over the controllers. This is
necessary because the identity of the controller
is lost on the way here.
Implemented in KX_BulletPhysicsController, KX_CameraIpoSGController, KX_IpoSGController, KX_LightIpoSGController, KX_MaterialIpoController, KX_ObColorIpoSGController, and KX_WorldIpoController.
virtual void SG_Controller::SetSimulatedTime (double time) [pure virtual]
Implemented in KX_BulletPhysicsController, KX_CameraIpoSGController, KX_IPhysicsController, KX_IpoSGController, KX_LightIpoSGController, KX_MaterialIpoController, KX_ObColorIpoSGController, and KX_WorldIpoController.
virtual bool SG_Controller::Update (double time) [pure virtual]
Implemented in KX_BulletPhysicsController, KX_CameraIpoSGController, KX_IPhysicsController, KX_IpoSGController, KX_LightIpoSGController, KX_MaterialIpoController, KX_ObColorIpoSGController, and KX_WorldIpoController.
Member Data Documentation
SG_IObject* SG_Controller::m_pObject [protected]
Definition at line 123 of file SG_Controller.h.
Referenced by ClearObject(), SetObject(), KX_IpoSGController::Update(), KX_LightIpoSGController::Update(), KX_ObColorIpoSGController::Update(), KX_CameraIpoSGController::Update(), and KX_MaterialIpoController::Update().
The documentation for this class was generated from the following files:
SG_Controller.h
SG_Controller.cpp