Blender: btPrimitiveManagerBase Class Reference
btPrimitiveManagerBase Class Reference
Prototype Base class for primitive classification.
#include <btGImpactBvh.h>
Public Member Functions
virtual ~btPrimitiveManagerBase ()
virtual bool is_trimesh () const =0
determines if this manager consist on only triangles, which special case will be optimized
virtual int get_primitive_count () const =0
virtual void get_primitive_box (int prim_index, btAABB &primbox) const =0
virtual void get_primitive_triangle (int prim_index, btPrimitiveTriangle &triangle) const =0
retrieves only the points of the triangle, and the collision margin
Detailed Description
Prototype Base class for primitive classification.
This class is a wrapper for primitive collections. This tells relevant info for the Bounding Box set classes, which take care of space classification. This class can manage Compound shapes and trimeshes, and if it is managing trimesh then the Hierarchy Bounding Box classes will take advantage of primitive Vs Box overlapping tests for getting optimal results and less Per Box compairisons.
Definition at line 230 of file btGImpactBvh.h.
Constructor & Destructor Documentation
virtual btPrimitiveManagerBase::~btPrimitiveManagerBase () [inline, virtual]
Definition at line 234 of file btGImpactBvh.h.
Member Function Documentation
virtual void btPrimitiveManagerBase::get_primitive_box (int prim_index, btAABB & primbox) const [pure virtual]
Implemented in btGImpactCompoundShape::CompoundPrimitiveManager, and btGImpactMeshShapePart::TrimeshPrimitiveManager.
Referenced by btGImpactQuantizedBvh::buildSet(), btGImpactBvh::buildSet(), btGImpactShapeInterface::getChildAabb(), btGImpactBvh::refit(), and btGImpactQuantizedBvh::refit().
virtual int btPrimitiveManagerBase::get_primitive_count () const [pure virtual]
Implemented in btGImpactCompoundShape::CompoundPrimitiveManager, and btGImpactMeshShapePart::TrimeshPrimitiveManager.
Referenced by btGImpactQuantizedBvh::buildSet(), and btGImpactBvh::buildSet().
virtual void btPrimitiveManagerBase::get_primitive_triangle (int prim_index, btPrimitiveTriangle & triangle) const [pure virtual]
retrieves only the points of the triangle, and the collision margin
Implemented in btGImpactCompoundShape::CompoundPrimitiveManager, and btGImpactMeshShapePart::TrimeshPrimitiveManager.
Referenced by btGImpactBvh::getNodeTriangle(), btGImpactQuantizedBvh::getNodeTriangle(), and btGImpactShapeInterface::getPrimitiveTriangle().
virtual bool btPrimitiveManagerBase::is_trimesh () const [pure virtual]
determines if this manager consist on only triangles, which special case will be optimized
Implemented in btGImpactCompoundShape::CompoundPrimitiveManager, and btGImpactMeshShapePart::TrimeshPrimitiveManager.
Referenced by btGImpactQuantizedBvh::isTrimesh(), and btGImpactBvh::isTrimesh().
The documentation for this class was generated from the following file:
btGImpactBvh.h