Blender: kernel_random.h File Reference
kernel_random.h File Reference
Functions
__device float path_rng (KernelGlobals *kg, RNG *rng, int sample, int dimension)
__device void path_rng_init (KernelGlobals *kg, __global uint *rng_state, int sample, RNG *rng, int x, int y, float *fx, float *fy)
__device void path_rng_end (KernelGlobals *kg, __global uint *rng_state, RNG rng)
Variables
CCL_NAMESPACE_BEGIN typedef uint RNG
Function Documentation
__device float path_rng (KernelGlobals * kg, RNG * rng, int sample, int dimension)
Definition at line 171 of file kernel_random.h.
Referenced by kernel_path_integrate(), kernel_path_trace(), and path_rng_init().
__device void path_rng_end (KernelGlobals * kg, __global uint * rng_state, RNG rng)
Definition at line 195 of file kernel_random.h.
Referenced by kernel_path_trace().
__device void path_rng_init (KernelGlobals * kg, __global uint * rng_state, int sample, RNG * rng, int x, int y, float * fx, float * fy)
Definition at line 178 of file kernel_random.h.
References kernel_data, path_rng(), PRNG_FILTER_U, and PRNG_FILTER_V.
Referenced by kernel_path_trace().
Variable Documentation
CCL_NAMESPACE_BEGIN typedef uint RNG
Definition at line 21 of file kernel_random.h.