Blender: sound_ops.c File Reference
sound_ops.c File Reference
sound
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <stddef.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "DNA_anim_types.h"
#include "DNA_packedFile_types.h"
#include "DNA_scene_types.h"
#include "DNA_space_types.h"
#include "DNA_sequence_types.h"
#include "DNA_sound_types.h"
#include "DNA_userdef_types.h"
#include "BKE_context.h"
#include "BKE_fcurve.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "BKE_packedFile.h"
#include "BKE_scene.h"
#include "BKE_sound.h"
#include "BKE_sequencer.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "UI_interface.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_sound.h"
#include "ED_util.h"
#include "sound_intern.h"
Functions
static int sound_open_cancel (bContext *UNUSED(C), wmOperator *op)
static void sound_open_init (bContext *C, wmOperator *op)
static int sound_open_exec (bContext *UNUSED(C), wmOperator *op)
static int sound_open_invoke (bContext *C, wmOperator *op, wmEvent *event)
static void SOUND_OT_open (wmOperatorType *ot)
static void SOUND_OT_open_mono (wmOperatorType *ot)
static int sound_update_animation_flags_exec (bContext *C, wmOperator *UNUSED(op))
static void SOUND_OT_update_animation_flags (wmOperatorType *ot)
static int sound_bake_animation_exec (bContext *C, wmOperator *UNUSED(op))
static void SOUND_OT_bake_animation (wmOperatorType *ot)
static int sound_mixdown_exec (bContext *C, wmOperator *op)
static int sound_mixdown_invoke (bContext *C, wmOperator *op, wmEvent *event)
static void SOUND_OT_mixdown (wmOperatorType *ot)
static int sound_poll (bContext *C)
static int sound_pack_exec (bContext *C, wmOperator *op)
static void SOUND_OT_pack (wmOperatorType *ot)
static int sound_unpack_exec (bContext *C, wmOperator *op)
static int sound_unpack_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static void SOUND_OT_unpack (wmOperatorType *ot)
void ED_operatortypes_sound (void)
Detailed Description
Definition in file sound_ops.c.
Function Documentation
void ED_operatortypes_sound (void)
Definition at line 717 of file sound_ops.c.
References SOUND_OT_bake_animation(), SOUND_OT_mixdown(), SOUND_OT_open(), SOUND_OT_open_mono(), SOUND_OT_pack(), SOUND_OT_unpack(), SOUND_OT_update_animation_flags(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
static int sound_bake_animation_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 277 of file sound_ops.c.
References RenderData::cfra, CTX_data_main(), CTX_data_scene(), Scene::lay, NULL, OPERATOR_FINISHED, Scene::r, scene_update_for_newframe(), RenderData::sfra, and sound_update_animation_flags_exec().
Referenced by sound_mixdown_exec(), and SOUND_OT_bake_animation().
static int sound_mixdown_exec (bContext * C, wmOperator * op) [static]
Definition at line 314 of file sound_ops.c.
References AUD_mixdown(), FFMpegCodecData::audio_channels, FFMpegCodecData::audio_mixrate, BKE_report(), BLI_path_abs(), BLI_strncpy(), AUD_DeviceSpecs::channels, CTX_data_main(), CTX_data_scene(), EFRA, RenderData::ffcodecdata, FILE_MAX, AUD_DeviceSpecs::format, FPS, Main::name, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, Scene::r, AUD_DeviceSpecs::rate, wmOperator::reports, RNA_enum_get(), RNA_int_get(), RNA_string_get(), RPT_ERROR, SFRA, sound_bake_animation_exec(), and Scene::sound_scene.
Referenced by sound_mixdown_invoke(), and SOUND_OT_mixdown().
static int sound_mixdown_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 358 of file sound_ops.c.
References wmOperator::ptr, RNA_struct_property_is_set(), sound_mixdown_exec(), and WM_operator_filesel().
Referenced by SOUND_OT_mixdown().
static int sound_open_cancel (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 80 of file sound_ops.c.
References wmOperator::customdata, MEM_freeN(), NULL, and OPERATOR_CANCELLED.
Referenced by SOUND_OT_open(), and SOUND_OT_open_mono().
static int sound_open_exec (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 154 of file sound_ops.c.
References BKE_report(), OPERATOR_CANCELLED, wmOperator::reports, and RPT_ERROR.
Referenced by sound_open_invoke(), SOUND_OT_open(), and SOUND_OT_open_mono().
static void sound_open_init (bContext * C, wmOperator * op) [static]
Definition at line 87 of file sound_ops.c.
References wmOperator::customdata, MEM_callocN(), PropertyPointerRNA::prop, PropertyPointerRNA::ptr, and uiIDContextProperty().
Referenced by sound_open_invoke().
static int sound_open_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 163 of file sound_ops.c.
References wmOperator::ptr, RNA_struct_property_is_set(), sound_open_exec(), sound_open_init(), and WM_operator_filesel().
Referenced by SOUND_OT_open(), and SOUND_OT_open_mono().
static void SOUND_OT_bake_animation (wmOperatorType * ot) [static]
Definition at line 297 of file sound_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and sound_bake_animation_exec().
Referenced by ED_operatortypes_sound().
static void SOUND_OT_mixdown (wmOperatorType * ot) [static]
Definition at line 530 of file sound_ops.c.
References AUD_CODEC_AAC, AUD_CODEC_AC3, AUD_CODEC_FLAC, AUD_CODEC_MP2, AUD_CODEC_MP3, AUD_CODEC_PCM, AUD_CODEC_VORBIS, AUD_CONTAINER_AC3, AUD_CONTAINER_FLAC, AUD_CONTAINER_MATROSKA, AUD_CONTAINER_MP2, AUD_CONTAINER_MP3, AUD_CONTAINER_OGG, AUD_CONTAINER_WAV, AUD_FORMAT_FLOAT32, AUD_FORMAT_FLOAT64, AUD_FORMAT_S16, AUD_FORMAT_S24, AUD_FORMAT_S32, AUD_FORMAT_U8, wmOperatorType::description, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_SAVE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, RNA_def_enum(), RNA_def_int(), sound_mixdown_exec(), sound_mixdown_invoke(), SOUNDFILE, wmOperatorType::srna, wmOperatorType::ui, WM_FILESEL_FILEPATH, and WM_operator_properties_filesel().
Referenced by ED_operatortypes_sound().
static void SOUND_OT_open (wmOperatorType * ot) [static]
Definition at line 173 of file sound_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, FALSE, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, RNA_def_boolean(), sound_open_cancel(), sound_open_exec(), sound_open_invoke(), SOUNDFILE, wmOperatorType::srna, WM_FILESEL_FILEPATH, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by ED_operatortypes_sound().
static void SOUND_OT_open_mono (wmOperatorType * ot) [static]
Definition at line 194 of file sound_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, FALSE, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, RNA_def_boolean(), sound_open_cancel(), sound_open_exec(), sound_open_invoke(), SOUNDFILE, wmOperatorType::srna, TRUE, WM_FILESEL_FILEPATH, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by ED_operatortypes_sound().
static void SOUND_OT_pack (wmOperatorType * ot) [static]
Definition at line 631 of file sound_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sound_pack_exec(), and sound_poll().
Referenced by ED_operatortypes_sound().
static void SOUND_OT_unpack (wmOperatorType * ot) [static]
Definition at line 695 of file sound_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PF_USE_LOCAL, wmOperatorType::poll, RNA_def_enum(), RNA_def_string(), sound_poll(), sound_unpack_exec(), sound_unpack_invoke(), wmOperatorType::srna, and unpack_method_items.
Referenced by ED_operatortypes_sound().
static void SOUND_OT_update_animation_flags (wmOperatorType * ot) [static]
Definition at line 254 of file sound_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and sound_update_animation_flags_exec().
Referenced by ED_operatortypes_sound().
static int sound_pack_exec (bContext * C, wmOperator * op) [static]
Definition at line 611 of file sound_ops.c.
References Editing::act_seq, CTX_data_main(), CTX_data_scene(), Scene::ed, bSound::id, ID_BLEND_PATH, bSound::name, newPackedFile(), OPERATOR_CANCELLED, OPERATOR_FINISHED, bSound::packedfile, wmOperator::reports, SEQ_SOUND, Sequence::sound, sound_load(), and Sequence::type.
Referenced by SOUND_OT_pack().
static int sound_poll (bContext * C) [static]
Definition at line 600 of file sound_ops.c.
References Editing::act_seq, CTX_data_scene(), Scene::ed, SEQ_SOUND, and Sequence::type.
Referenced by SOUND_OT_pack(), and SOUND_OT_unpack().
static int sound_unpack_exec (bContext * C, wmOperator * op) [static]
Definition at line 648 of file sound_ops.c.
References BKE_report(), BLI_findstring(), CTX_data_main(), G, G_AUTOPACK, MAX_ID_NAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, bSound::packedfile, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), RNA_string_get(), RNA_struct_property_is_set(), RPT_WARNING, and unpackSound().
Referenced by SOUND_OT_unpack(), and sound_unpack_invoke().
static int sound_unpack_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 671 of file sound_ops.c.
References Editing::act_seq, BKE_report(), CTX_data_scene(), Scene::ed, G, G_AUTOPACK, bSound::id, bSound::name, ID::name, OPERATOR_CANCELLED, OPERATOR_FINISHED, bSound::packedfile, wmOperator::ptr, wmOperator::reports, RNA_struct_property_is_set(), RPT_WARNING, SEQ_SOUND, Sequence::sound, sound_unpack_exec(), Sequence::type, and unpack_menu().
Referenced by SOUND_OT_unpack().
static int sound_update_animation_flags_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 217 of file sound_ops.c.
References Scene::audio, AUDIO_VOLUME_ANIMATED, CTX_data_scene(), Scene::ed, AudioData::flag, Sequence::flag, Scene::id, id_data_find_fcurve(), OPERATOR_FINISHED, RNA_Scene, RNA_Sequence, SEQ_AUDIO_PAN_ANIMATED, SEQ_AUDIO_PITCH_ANIMATED, SEQ_AUDIO_VOLUME_ANIMATED, SEQ_BEGIN, and SEQ_END.
Referenced by sound_bake_animation_exec(), and SOUND_OT_update_animation_flags().