Blender: FilterLevel Class Reference
FilterLevel Class Reference
pixel filter for color calculation
#include <FilterColor.h>
Public Member Functions
FilterLevel (void)
constructor
virtual ~FilterLevel (void)
destructor
ColorLevel & getLevels (void)
get color matrix
void setLevels (ColorLevel &lev)
set color matrix
Protected Member Functions
unsigned int calcColor (unsigned int val, short idx)
calculate one color component
template<class SRC >
unsigned int tFilter (SRC src, short x, short y, short *size, unsigned int pixSize, unsigned int val)
filter pixel template, source int buffer
virtual unsigned int filter (unsigned char *src, short x, short y, short *size, unsigned int pixSize, unsigned int val=0)
virtual filtering function for byte source
virtual unsigned int filter (unsigned int *src, short x, short y, short *size, unsigned int pixSize, unsigned int val=0)
virtual filtering function for unsigned int source
Protected Attributes
ColorLevel levels
color calculation matrix
Detailed Description
pixel filter for color calculation
Definition at line 124 of file FilterColor.h.
Constructor & Destructor Documentation
FilterLevel::FilterLevel (void)
constructor
Definition at line 221 of file FilterColor.cpp.
References levels.
virtual FilterLevel::~FilterLevel (void) [inline, virtual]
destructor
Definition at line 130 of file FilterColor.h.
Member Function Documentation
unsigned int FilterLevel::calcColor (unsigned int val, short idx) [inline, protected]
calculate one color component
Definition at line 142 of file FilterColor.h.
References levels, and VT_C.
Referenced by tFilter().
virtual unsigned int FilterLevel::filter (unsigned char * src, short x, short y, short * size, unsigned int pixSize, unsigned int val = 0) [inline, protected, virtual]
virtual filtering function for byte source
Reimplemented from FilterBase.
Definition at line 162 of file FilterColor.h.
References tFilter().
virtual unsigned int FilterLevel::filter (unsigned int * src, short x, short y, short * size, unsigned int pixSize, unsigned int val = 0) [inline, protected, virtual]
virtual filtering function for unsigned int source
Reimplemented from FilterBase.
Definition at line 166 of file FilterColor.h.
References tFilter().
ColorLevel& FilterLevel::getLevels (void) [inline]
get color matrix
Definition at line 133 of file FilterColor.h.
References levels.
Referenced by getLevels().
void FilterLevel::setLevels (ColorLevel & lev)
set color matrix
Definition at line 233 of file FilterColor.cpp.
References levels.
Referenced by setLevels().
template<class SRC > unsigned int FilterLevel::tFilter (SRC src, short x, short y, short * size, unsigned int pixSize, unsigned int val) [inline, protected]
filter pixel template, source int buffer
Definition at line 152 of file FilterColor.h.
References calcColor(), and VT_RGBA.
Referenced by filter().
Member Data Documentation
ColorLevel FilterLevel::levels [protected]
color calculation matrix
Definition at line 139 of file FilterColor.h.
Referenced by calcColor(), FilterLevel(), getLevels(), and setLevels().
The documentation for this class was generated from the following files:
FilterColor.h
FilterColor.cpp