Blender: interface.c File Reference
interface.c File Reference
interface
#include <float.h>
#include <limits.h>
#include <math.h>
#include <string.h>
#include <ctype.h>
#include "MEM_guardedalloc.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_userdef_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_dynstr.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_library.h"
#include "BKE_unit.h"
#include "BKE_screen.h"
#include "BKE_idprop.h"
#include "BKE_utildefines.h"
#include "BIF_gl.h"
#include "BLF_api.h"
#include "BLF_translation.h"
#include "UI_interface.h"
#include "IMB_imbuf.h"
#include "WM_api.h"
#include "WM_types.h"
#include "wm_subwindow.h"
#include "wm_window.h"
#include "RNA_access.h"
#include "BPY_extern.h"
#include "interface_intern.h"
Classes
struct AutoComplete
Defines
#define MENU_WIDTH 120
#define MENU_ITEM_HEIGHT 20
#define MENU_SEP_HEIGHT 6
#define PRECISION_FLOAT_MAX 6
#define PRECISION_FLOAT_MAX_POW 1000000
#define UI_BUT_VALUE_UNSET DBL_MAX
#define UI_GET_BUT_VALUE_INIT(_but, _value) if (_value == DBL_MAX) { (_value) = ui_get_but_val(_but); }
#define UI_DEF_BUT_RNA_DISABLE(but)
Functions
static void ui_free_but (const bContext *C, uiBut *but)
void ui_block_to_window_fl (const ARegion *ar, uiBlock *block, float *x, float *y)
void ui_block_to_window (const ARegion *ar, uiBlock *block, int *x, int *y)
void ui_block_to_window_rct (const ARegion *ar, uiBlock *block, rctf *graph, rcti *winr)
void ui_window_to_block_fl (const ARegion *ar, uiBlock *block, float *x, float *y)
void ui_window_to_block (const ARegion *ar, uiBlock *block, int *x, int *y)
void ui_window_to_region (const ARegion *ar, int *x, int *y)
void ui_block_translate (uiBlock *block, int x, int y)
static void ui_text_bounds_block (uiBlock *block, float offset)
void ui_bounds_block (uiBlock *block)
static void ui_centered_bounds_block (const bContext *C, uiBlock *block)
static void ui_popup_bounds_block (const bContext *C, uiBlock *block, int bounds_calc)
void uiBoundsBlock (uiBlock *block, int addval)
void uiTextBoundsBlock (uiBlock *block, int addval)
void uiPopupBoundsBlock (uiBlock *block, int addval, int mx, int my)
void uiMenuPopupBoundsBlock (uiBlock *block, int addval, int mx, int my)
void uiCenteredBoundsBlock (uiBlock *block, int addval)
void uiExplicitBoundsBlock (uiBlock *block, int minx, int miny, int maxx, int maxy)
static int ui_but_float_precision (uiBut *but, double value)
static void ui_draw_linkline (uiLinkLine *line)
static void ui_draw_links (uiBlock *block)
static int ui_but_equals_old (uiBut *but, uiBut *oldbut)
static void ui_but_update_linklines (uiBlock *block, uiBut *oldbut, uiBut *newbut)
static int ui_but_update_from_old_block (const bContext *C, uiBlock *block, uiBut **butpp)
int uiButActiveOnly (const bContext *C, uiBlock *block, uiBut *but)
static int ui_but_is_rna_undo (uiBut *but)
static void ui_menu_block_set_keyaccels (uiBlock *block)
void ui_but_add_shortcut (uiBut *but, const char *shortcut_str, const short do_strip)
static void ui_menu_block_set_keymaps (const bContext *C, uiBlock *block)
void uiEndBlock (const bContext *C, uiBlock *block)
void ui_fontscale (short *points, float aspect)
static void ui_but_to_pixelrect (rcti *rect, const ARegion *ar, uiBlock *block, uiBut *but)
void uiDrawBlock (const bContext *C, uiBlock *block)
static void ui_is_but_sel (uiBut *but, double *value)
static uiBut * ui_find_inlink (uiBlock *block, void *poin)
static void ui_add_link_line (ListBase *listb, uiBut *but, uiBut *bt)
uiBut * uiFindInlink (uiBlock *block, void *poin)
void uiComposeLinks (uiBlock *block)
void uiBlockSetButLock (uiBlock *block, int val, const char *lockstr)
void uiBlockClearButLock (uiBlock *block)
void ui_delete_linkline (uiLinkLine *line, uiBut *but)
void ui_get_but_vectorf (uiBut *but, float vec[3])
void ui_set_but_vectorf (uiBut *but, const float vec[3])
int ui_is_but_float (uiBut *but)
int ui_is_but_unit (uiBut *but)
int ui_is_but_rna_valid (uiBut *but)
double ui_get_but_val (uiBut *but)
void ui_set_but_val (uiBut *but, double value)
int ui_get_but_string_max_length (uiBut *but)
static double ui_get_but_scale_unit (uiBut *but, double value)
void ui_convert_to_unit_alt_name (uiBut *but, char *str, size_t maxlen)
static void ui_get_but_string_unit (uiBut *but, char *str, int len_max, double value, int pad)
static float ui_get_but_step_unit (uiBut *but, float step_default)
void ui_get_but_string (uiBut *but, char *str, size_t maxlen)
int ui_set_but_string_eval_num (bContext *C, uiBut *but, const char *str, double *value)
int ui_set_but_string (bContext *C, uiBut *but, const char *str)
void ui_set_but_default (bContext *C, short all)
static double soft_range_round_up (double value, double max)
static double soft_range_round_down (double value, double max)
void ui_set_but_soft_range (uiBut *but, double value)
static void ui_free_link (uiLink *link)
void uiFreeBlock (const bContext *C, uiBlock *block)
void uiFreeBlocks (const bContext *C, ListBase *lb)
void uiFreeInactiveBlocks (const bContext *C, ListBase *lb)
void uiBlockSetRegion (uiBlock *block, ARegion *region)
uiBlock * uiBeginBlock (const bContext *C, ARegion *region, const char *name, short dt)
uiBlock * uiGetBlock (const char *name, ARegion *ar)
void uiBlockSetEmboss (uiBlock *block, char dt)
void ui_check_but (uiBut *but)
void uiBlockBeginAlign (uiBlock *block)
static int buts_are_horiz (uiBut *but1, uiBut *but2)
void uiBlockEndAlign (uiBlock *block)
int ui_but_can_align (uiBut *but)
static void ui_block_do_align_but (uiBut *first, short nr)
void ui_block_do_align (uiBlock *block)
static uiBut * ui_def_but (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, void *poin, float min, float max, float a1, float a2, const char *tip)
ui_def_but is the function that draws many button types
static uiBut * ui_def_but_rna (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, PointerRNA *ptr, PropertyRNA *prop, int index, float min, float max, float a1, float a2, const char *tip)
static uiBut * ui_def_but_rna_propname (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, PointerRNA *ptr, const char *propname, int index, float min, float max, float a1, float a2, const char *tip)
static uiBut * ui_def_but_operator_ptr (uiBlock *block, int type, wmOperatorType *ot, int opcontext, const char *str, int x1, int y1, short x2, short y2, const char *tip)
static uiBut * ui_def_but_operator_text (uiBlock *block, int type, const char *opname, int opcontext, const char *str, int x1, int y1, short x2, short y2, void *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefBut (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, void *poin, float min, float max, float a1, float a2, const char *tip)
static int findBitIndex (unsigned int x)
AutoComplete * autocomplete_begin (const char *startname, size_t maxlen)
void autocomplete_do_name (AutoComplete *autocpl, const char *name)
void autocomplete_end (AutoComplete *autocpl, char *autoname)
static void autocomplete_id (bContext *C, char *str, void *arg_v)
static void ui_check_but_and_iconize (uiBut *but, int icon)
static uiBut * uiDefButBit (uiBlock *block, int type, int bit, int retval, const char *str, int x1, int y1, short x2, short y2, void *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButF (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, float *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButBitF (uiBlock *block, int type, int bit, int retval, const char *str, int x1, int y1, short x2, short y2, float *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButI (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, int *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButBitI (uiBlock *block, int type, int bit, int retval, const char *str, int x1, int y1, short x2, short y2, int *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButS (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, short *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButBitS (uiBlock *block, int type, int bit, int retval, const char *str, int x1, int y1, short x2, short y2, short *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButC (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, char *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButBitC (uiBlock *block, int type, int bit, int retval, const char *str, int x1, int y1, short x2, short y2, char *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButR (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, PointerRNA *ptr, const char *propname, int index, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButR_prop (uiBlock *block, int type, int retval, const char *str, int x1, int y1, short x2, short y2, PointerRNA *ptr, PropertyRNA *prop, int index, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefButO_ptr (uiBlock *block, int type, wmOperatorType *ot, int opcontext, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefButO (uiBlock *block, int type, const char *opname, int opcontext, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefButTextO (uiBlock *block, int type, const char *opname, int opcontext, const char *str, int x1, int y1, short x2, short y2, void *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconBut (uiBlock *block, int type, int retval, int icon, int x1, int y1, short x2, short y2, void *poin, float min, float max, float a1, float a2, const char *tip)
static uiBut * uiDefIconButBit (uiBlock *block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, void *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButF (uiBlock *block, int type, int retval, int icon, int x1, int y1, short x2, short y2, float *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButBitF (uiBlock *block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, float *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButI (uiBlock *block, int type, int retval, int icon, int x1, int y1, short x2, short y2, int *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButBitI (uiBlock *block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, int *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButS (uiBlock *block, int type, int retval, int icon, int x1, int y1, short x2, short y2, short *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButBitS (uiBlock *block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, short *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButC (uiBlock *block, int type, int retval, int icon, int x1, int y1, short x2, short y2, char *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButBitC (uiBlock *block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, char *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButR (uiBlock *block, int type, int retval, int icon, int x1, int y1, short x2, short y2, PointerRNA *ptr, const char *propname, int index, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButR_prop (uiBlock *block, int type, int retval, int icon, int x1, int y1, short x2, short y2, PointerRNA *ptr, PropertyRNA *prop, int index, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconButO_ptr (uiBlock *block, int type, wmOperatorType *ot, int opcontext, int icon, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefIconButO (uiBlock *block, int type, const char *opname, int opcontext, int icon, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefIconTextBut (uiBlock *block, int type, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, void *poin, float min, float max, float a1, float a2, const char *tip)
static uiBut * uiDefIconTextButBit (uiBlock *block, int type, int bit, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, void *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButF (uiBlock *block, int type, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, float *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButBitF (uiBlock *block, int type, int bit, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, float *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButI (uiBlock *block, int type, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, int *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButBitI (uiBlock *block, int type, int bit, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, int *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButS (uiBlock *block, int type, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, short *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButBitS (uiBlock *block, int type, int bit, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, short *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButC (uiBlock *block, int type, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, char *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButBitC (uiBlock *block, int type, int bit, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, char *poin, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButR (uiBlock *block, int type, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, PointerRNA *ptr, const char *propname, int index, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButR_prop (uiBlock *block, int type, int retval, int icon, const char *str, int x1, int y1, short x2, short y2, PointerRNA *ptr, PropertyRNA *prop, int index, float min, float max, float a1, float a2, const char *tip)
uiBut * uiDefIconTextButO_ptr (uiBlock *block, int type, wmOperatorType *ot, int opcontext, int icon, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefIconTextButO (uiBlock *block, int type, const char *opname, int opcontext, int icon, const char *str, int x1, int y1, short x2, short y2, const char *tip)
void uiSetButLink (uiBut *but, void **poin, void ***ppoin, short *tot, int from, int to)
int uiBlocksGetYMin (ListBase *lb)
void uiBlockSetDirection (uiBlock *block, int direction)
void uiBlockFlipOrder (uiBlock *block)
void uiBlockSetFlag (uiBlock *block, int flag)
void uiBlockClearFlag (uiBlock *block, int flag)
void uiBlockSetXOfs (uiBlock *block, int xofs)
void uiButSetFlag (uiBut *but, int flag)
void uiButClearFlag (uiBut *but, int flag)
int uiButGetRetVal (uiBut *but)
void uiButSetDragID (uiBut *but, ID *id)
void uiButSetDragRNA (uiBut *but, PointerRNA *ptr)
void uiButSetDragPath (uiBut *but, const char *path)
void uiButSetDragName (uiBut *but, const char *name)
void uiButSetDragValue (uiBut *but)
void uiButSetDragImage (uiBut *but, const char *path, int icon, struct ImBuf *imb, float scale)
PointerRNA * uiButGetOperatorPtrRNA (uiBut *but)
void uiButSetUnitType (uiBut *but, const int unit_type)
int uiButGetUnitType (uiBut *but)
void uiBlockSetHandleFunc (uiBlock *block, uiBlockHandleFunc func, void *arg)
void uiBlockSetButmFunc (uiBlock *block, uiMenuHandleFunc func, void *arg)
void uiBlockSetFunc (uiBlock *block, uiButHandleFunc func, void *arg1, void *arg2)
void uiBlockSetNFunc (uiBlock *block, uiButHandleFunc func, void *argN, void *arg2)
void uiButSetRenameFunc (uiBut *but, uiButHandleRenameFunc func, void *arg1)
void uiBlockSetDrawExtraFunc (uiBlock *block, void(*func)(const bContext *C, void *idv, void *arg1, void *arg2, rcti *rect), void *arg1, void *arg2)
void uiButSetFunc (uiBut *but, uiButHandleFunc func, void *arg1, void *arg2)
void uiButSetNFunc (uiBut *but, uiButHandleNFunc funcN, void *argN, void *arg2)
void uiButSetCompleteFunc (uiBut *but, uiButCompleteFunc func, void *arg)
uiBut * uiDefIDPoinBut (uiBlock *block, uiIDPoinFuncFP func, short blocktype, int retval, const char *str, int x1, int y1, short x2, short y2, void *idpp, const char *tip)
uiBut * uiDefBlockBut (uiBlock *block, uiBlockCreateFunc func, void *arg, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefBlockButN (uiBlock *block, uiBlockCreateFunc func, void *argN, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefPulldownBut (uiBlock *block, uiBlockCreateFunc func, void *arg, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefMenuBut (uiBlock *block, uiMenuCreateFunc func, void *arg, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefIconTextMenuBut (uiBlock *block, uiMenuCreateFunc func, void *arg, int icon, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefIconMenuBut (uiBlock *block, uiMenuCreateFunc func, void *arg, int icon, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefIconTextBlockBut (uiBlock *block, uiBlockCreateFunc func, void *arg, int icon, const char *str, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefIconBlockBut (uiBlock *block, uiBlockCreateFunc func, void *arg, int retval, int icon, int x1, int y1, short x2, short y2, const char *tip)
uiBut * uiDefKeyevtButS (uiBlock *block, int retval, const char *str, int x1, int y1, short x2, short y2, short *spoin, const char *tip)
uiBut * uiDefHotKeyevtButS (uiBlock *block, int retval, const char *str, int x1, int y1, short x2, short y2, short *keypoin, short *modkeypoin, const char *tip)
uiBut * uiDefSearchBut (uiBlock *block, void *arg, int retval, int icon, int maxlen, int x1, int y1, short x2, short y2, float a1, float a2, const char *tip)
void uiButSetSearchFunc (uiBut *but, uiButSearchFunc sfunc, void *arg, uiButHandleFunc bfunc, void *active)
void uiButSetFocusOnEnter (wmWindow *win, uiBut *but)
void UI_init (void)
void UI_init_userdef (void)
void UI_reinit_font (void)
void UI_exit (void)
Detailed Description
Definition in file interface.c.
Define Documentation
#define MENU_ITEM_HEIGHT 20
Definition at line 76 of file interface.c.
#define MENU_SEP_HEIGHT 6
Definition at line 77 of file interface.c.
#define MENU_WIDTH 120
Definition at line 75 of file interface.c.
#define PRECISION_FLOAT_MAX 6
Definition at line 79 of file interface.c.
Referenced by ui_but_float_precision(), and ui_get_but_string_unit().
#define PRECISION_FLOAT_MAX_POW 1000000
Definition at line 80 of file interface.c.
Referenced by ui_but_float_precision().
#define UI_BUT_VALUE_UNSET DBL_MAX
Definition at line 83 of file interface.c.
Referenced by ui_check_but(), and ui_set_but_val().
#define UI_DEF_BUT_RNA_DISABLE (but)
Value:
but->flag |= UI_BUT_DISABLED; \
    but->lock = 1; \
    but->lockstr = ""
Definition at line 2646 of file interface.c.
Referenced by ui_def_but_rna(), and ui_def_but_rna_propname().
#define UI_GET_BUT_VALUE_INIT (_but, _value) if (_value == DBL_MAX) { (_value) = ui_get_but_val(_but); }
Definition at line 84 of file interface.c.
Referenced by ui_check_but(), and ui_is_but_sel().
Function Documentation
AutoComplete* autocomplete_begin (const char * startname, size_t maxlen)
Definition at line 2921 of file interface.c.
References AutoComplete::maxlen, MEM_callocN(), AutoComplete::startname, and AutoComplete::truncate.
Referenced by autocomplete_directory(), autocomplete_file(), autocomplete_id(), and ui_searchbox_autocomplete().
void autocomplete_do_name (AutoComplete * autocpl, const char * name)
Definition at line 2933 of file interface.c.
References BLI_strncpy(), AutoComplete::maxlen, AutoComplete::startname, and AutoComplete::truncate.
Referenced by autocomplete_directory(), autocomplete_file(), autocomplete_id(), and uiSearchItemAdd().
void autocomplete_end (AutoComplete * autocpl, char * autoname)
Definition at line 2962 of file interface.c.
References BLI_strncpy(), AutoComplete::maxlen, MEM_freeN(), AutoComplete::startname, and AutoComplete::truncate.
Referenced by autocomplete_directory(), autocomplete_file(), autocomplete_id(), and ui_searchbox_autocomplete().
static void autocomplete_id (bContext * C, char * str, void * arg_v) [static]
Definition at line 2975 of file interface.c.
References autocomplete_begin(), autocomplete_do_name(), autocomplete_end(), CTX_data_main(), ListBase::first, MAX_ID_NAME, ID::name, ID::next, NULL, and which_libbase().
Referenced by uiDefIDPoinBut().
static int buts_are_horiz (uiBut * but1, uiBut * but2) [static]
Definition at line 2347 of file interface.c.
References fabs(), uiBut::x1, uiBut::x2, uiBut::y1, and uiBut::y2.
Referenced by ui_block_do_align_but().
static int findBitIndex (unsigned int x) [static]
Definition at line 2896 of file interface.c.
References is_power_of_2_i().
Referenced by uiDefButBit(), uiDefIconButBit(), and uiDefIconTextButBit().
static double soft_range_round_down (double value, double max) [static]
Definition at line 1869 of file interface.c.
References log(), M_LN10, and pow().
Referenced by ui_set_but_soft_range().
static double soft_range_round_up (double value, double max) [static]
Definition at line 1856 of file interface.c.
References log(), M_LN10, and pow().
Referenced by ui_set_but_soft_range().
static void ui_add_link_line (ListBase * listb, uiBut * but, uiBut * bt) [static]
Definition at line 1141 of file interface.c.
References BLI_addtail(), uiLinkLine::from, MEM_callocN(), and uiLinkLine::to.
Referenced by uiComposeLinks().
void ui_block_do_align (uiBlock * block)
Definition at line 2502 of file interface.c.
References uiBut::alignnr, uiBlock::buttons, ListBase::first, uiBut::next, and ui_block_do_align_but().
Referenced by uiEndBlock().
static void ui_block_do_align_but (uiBut * first, short nr) [static]
Definition at line 2368 of file interface.c.
References uiBut::alignnr, buts_are_horiz(), uiBut::next, next, NULL, uiBut::prev, UI_BUT_ALIGN, UI_BUT_ALIGN_DOWN, UI_BUT_ALIGN_LEFT, UI_BUT_ALIGN_RIGHT, UI_BUT_ALIGN_TOP, uiBut::x1, uiBut::x2, uiBut::y1, and uiBut::y2.
Referenced by ui_block_do_align().
void ui_block_to_window (const ARegion * ar, uiBlock * block, int * x, int * y)
Definition at line 119 of file interface.c.
References ui_block_to_window_fl().
void ui_block_to_window_fl (const ARegion * ar, uiBlock * block, float * x, float * y)
Definition at line 97 of file interface.c.
References Panel::ofsx, Panel::ofsy, uiBlock::panel, uiBlock::winmat, ARegion::winrct, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_block_position(), ui_block_to_window(), and ui_block_to_window_rct().
void ui_block_to_window_rct (const ARegion * ar, uiBlock * block, rctf * graph, rcti * winr)
Definition at line 132 of file interface.c.
References ui_block_to_window_fl(), rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
void ui_block_translate (uiBlock * block, int x, int y)
Definition at line 197 of file interface.c.
References uiBlock::buttons, ListBase::first, uiBlock::maxx, uiBlock::maxy, uiBlock::minx, uiBlock::miny, uiBut::next, uiBut::x1, uiBut::x2, uiBut::y1, and uiBut::y2.
Referenced by ui_centered_bounds_block(), and ui_popup_bounds_block().
void ui_bounds_block (uiBlock * block)
Definition at line 258 of file interface.c.
References uiBlock::bounds, uiBlock::buttons, ListBase::first, MAX2, uiBlock::maxx, uiBlock::maxy, uiBlock::minbounds, uiBlock::minx, uiBlock::miny, uiBut::next, NULL, uiBlock::panel, uiBlock::safety, Panel::sizex, Panel::sizey, uiBut::str, uiBut::x1, uiBut::x2, rctf::xmax, rctf::xmin, uiBut::y1, uiBut::y2, rctf::ymax, and rctf::ymin.
Referenced by ui_centered_bounds_block(), ui_offset_panel_block(), ui_popup_bounds_block(), and uiEndBlock().
void ui_but_add_shortcut (uiBut * but, const char * shortcut_str, const short do_strip)
Definition at line 806 of file interface.c.
References BLI_snprintf(), BLI_strdup(), MEM_freeN(), uiBut::str, uiBut::strdata, and ui_check_but().
Referenced by but_shortcut_name_func(), and ui_menu_block_set_keymaps().
int ui_but_can_align (uiBut * but)
Definition at line 2363 of file interface.c.
References ELEM3, LABEL, OPTION, OPTIONN, and uiBut::type.
Referenced by ui_def_but(), and ui_item_align().
static int ui_but_equals_old (uiBut * but, uiBut * oldbut) [static]
Definition at line 541 of file interface.c.
References PointerRNA::data, uiBut::func, uiBut::func_arg1, uiBut::func_arg2, uiBut::funcN, uiBut::optype, uiBut::poin, uiBut::pointype, uiBut::retval, uiBut::rnaindex, uiBut::rnapoin, and uiBut::rnaprop.
Referenced by ui_but_update_from_old_block(), and uiButActiveOnly().
static int ui_but_float_precision (uiBut * but, double value) [static]
Definition at line 450 of file interface.c.
References uiBut::a2, ABS, CLAMP(), uiBut::hardmax, i, PRECISION_FLOAT_MAX, and PRECISION_FLOAT_MAX_POW.
Referenced by ui_check_but(), and ui_get_but_string().
static int ui_but_is_rna_undo (uiBut * but) [static]
Definition at line 711 of file interface.c.
References PointerRNA::data, FALSE, PointerRNA::id, ID_CHECK_UNDO, RNA_struct_undo_check(), uiBut::rnapoin, TRUE, and PointerRNA::type.
Referenced by ui_def_but_rna().
static void ui_but_to_pixelrect (rcti * rect, const ARegion * ar, uiBlock * block, uiBut * but) [static]
Definition at line 967 of file interface.c.
References floorf, uiBlock::maxx, uiBlock::maxy, uiBlock::minx, uiBlock::miny, Panel::ofsx, Panel::ofsy, uiBlock::panel, uiBlock::winmat, ARegion::winx, ARegion::winy, uiBut::x1, uiBut::x2, rcti::xmax, rcti::xmin, uiBut::y1, uiBut::y2, rcti::ymax, and rcti::ymin.
Referenced by uiDrawBlock().
static int ui_but_update_from_old_block (const bContext * C, uiBlock * block, uiBut ** butpp) [static]
Definition at line 591 of file interface.c.
References uiBut::active, BLI_insertlink(), BLI_remlink(), uiBut::block, uiBlock::buttons, uiBut::context, ELEM, ListBase::first, uiBut::func_argN, uiBut::hardmax, LISTROW, uiBut::next, uiBlock::oldblock, uiBut::poin, ROW, SWAP, ui_but_equals_old(), ui_but_update_linklines(), ui_free_but(), uiBut::x1, uiBut::x2, uiBut::y1, and uiBut::y2.
Referenced by uiEndBlock().
static void ui_but_update_linklines (uiBlock * block, uiBut * oldbut, uiBut * newbut) [static]
Definition at line 560 of file interface.c.
References uiBlock::buttons, ListBase::first, uiLinkLine::from, uiLink::lines, LINK, uiBut::link, uiLinkLine::next, uiBut::next, SWAP, uiLinkLine::to, and uiBut::type.
Referenced by ui_but_update_from_old_block().
static void ui_centered_bounds_block (const bContext * C, uiBlock * block) [static]
Definition at line 304 of file interface.c.
References CTX_wm_window(), uiBlock::maxx, uiBlock::maxy, uiBlock::minx, uiBlock::miny, ui_block_translate(), ui_bounds_block(), and wm_window_get_size_ghost().
Referenced by uiEndBlock().
void ui_check_but (uiBut * but)
Definition at line 2143 of file interface.c.
References BLI_snprintf(), BLI_strncpy(), BUT_TOGDUAL, uiBut::drawstr, uiBut::editstr, uiBut::editval, uiBut::editvec, fabs(), uiBut::flag, FLT_MAX, uiBut::hardmax, uiBut::hardmin, HOTKEYEVT, HSVCIRCLE, HSVCUBE, HSVSLI, uiBut::iconadd, ICONROW, ICONTEXTROW, ICONTOG, ICONTOGN, IDPOIN, KEYEVT, KM_ALT, KM_CTRL, KM_OSKEY, KM_SHIFT, LABEL, MENU, uiBut::modifier_key, NUM, NUMABS, NUMSLI, PROP_ICONS_CONSECUTIVE, PROP_PERCENTAGE, RNA_property_flag(), RNA_property_subtype(), uiBut::rnaprop, SCROLL, SEARCH_MENU, SLI, uiBut::str, strlen(), TEX, TRUE, uiBut::type, ui_but_float_precision(), UI_BUT_VALUE_UNSET, ui_get_but_string(), ui_get_but_string_unit(), UI_GET_BUT_VALUE_INIT, ui_is_but_float(), ui_is_but_sel(), ui_is_but_unit(), UI_MAX_DRAW_STR, UI_SELECT, ui_set_but_soft_range(), ui_set_but_val(), ui_set_name_menu(), WM_key_event_string(), uiBut::x1, and uiBut::x2.
Referenced by button_activate_exit(), button_activate_state(), ui_apply_but_BLOCK(), ui_apply_but_IDPOIN(), ui_apply_but_NUM(), ui_apply_but_ROW(), ui_apply_but_TEX(), ui_apply_but_TOG(), ui_apply_but_TOG3(), ui_apply_but_VEC(), ui_block_position(), ui_but_add_shortcut(), ui_check_but_and_iconize(), ui_do_but_HOTKEYEVT(), ui_do_but_textedit(), ui_do_but_textedit_select(), ui_handle_button_return_submenu(), ui_item_position(), ui_layer_but_cb(), ui_numedit_apply(), ui_text_bounds_block(), ui_textedit_begin(), ui_textedit_move(), ui_textedit_set_cursor_select(), ui_update_block_buts_rgb(), uiDefBlockBut(), uiDefBlockButN(), uiDefBut(), uiDefButO_ptr(), uiDefButR(), uiDefButR_prop(), uiDefButTextO(), uiDefHotKeyevtButS(), uiDefIconBlockBut(), uiDefIconMenuBut(), uiDefIconTextBlockBut(), uiDefIconTextMenuBut(), uiDefIDPoinBut(), uiDefKeyevtButS(), uiDefMenuBut(), uiDefPulldownBut(), uiDefSearchBut(), and uiEndBlock().
static void ui_check_but_and_iconize (uiBut * but, int icon) [static]
Definition at line 2994 of file interface.c.
References uiBut::flag, uiBut::icon, ui_check_but(), and UI_HAS_ICON.
Referenced by uiDefIconBut(), uiDefIconButO_ptr(), uiDefIconButR(), uiDefIconButR_prop(), uiDefIconTextBut(), uiDefIconTextButO_ptr(), uiDefIconTextButR(), and uiDefIconTextButR_prop().
void ui_convert_to_unit_alt_name (uiBut * but, char * str, size_t maxlen)
Definition at line 1581 of file interface.c.
References uiBut::block, bUnit_ToUnitAltName(), MEM_callocN(), MEM_freeN(), RNA_SUBTYPE_UNIT_VALUE, UnitSettings::system, ui_is_but_unit(), uiButGetUnitType(), and uiBlock::unit.
Referenced by ui_textedit_begin().
static uiBut* ui_def_but (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, void * poin, float min, float max, float a1, float a2, const char * tip) [static]
ui_def_but is the function that draws many button types
for float buttons:
a1 Click Step (how much to change the value each click)
a2 Number of decimal point values to display. 0 defaults to 3 (0.000) 1,2,3, and a maximum of 4, all greater values will be clamped to 4.
Definition at line 2532 of file interface.c.
References uiBut::a1, uiBut::a2, uiBut::alignnr, uiBlock::alignnr, uiBut::aspect, BIT, uiBut::bit, uiBut::bitnr, BLI_addtail(), BLOCK, uiBut::block, BUT, BUT_TOGDUAL, BUTM, BUTPOIN, uiBlock::buttons, BUTTYPE, uiBlock::curlayout, uiBut::dt, uiBlock::dt, ELEM3, ELEM4, ELEM7, ELEM8, uiBut::flag, uiBlock::flag, FTPREVIEW, uiBlock::func, uiBut::func, uiBut::func_arg1, uiBlock::func_arg1, uiBut::func_arg2, uiBlock::func_arg2, uiBlock::func_argN, uiBut::func_argN, uiBlock::funcN, uiBut::funcN, uiBut::hardmax, uiBut::hardmin, HSVSLI, uiBut::icon, uiBut::iconadd, IDPOIN, if(), LABEL, LISTBOX, uiBlock::lock, uiBut::lock, uiBlock::lockstr, uiBut::lockstr, max, MEM_callocN(), MEM_dupallocN(), MEM_mallocN(), MENU, min, NULL, NUM, NUMABS, NUMSLI, uiBut::poin, uiBut::pointype, uiBut::pos, PROGRESSBAR, PULLDOWN, uiBut::retval, ROUNDBOX, SCROLL, SEARCH_MENU, SEPR, uiBut::softmax, uiBut::softmin, uiBut::str, uiBut::strdata, strlen(), TEX, uiBut::tip, uiBut::type, UI_BLOCK_LOOP, UI_BUT_ALIGN, ui_but_can_align(), UI_BUT_DISABLED, UI_BUT_UNDO, UI_editsource_active_but_test(), UI_editsource_enable_check(), UI_ICON_LEFT, ui_layout_add_but(), UI_MAX_NAME_STR, UI_TEXT_LEFT, uiBut::x1, uiBut::x2, uiBut::y1, and uiBut::y2.
Referenced by ui_def_but_operator_ptr(), ui_def_but_operator_text(), ui_def_but_rna(), ui_def_but_rna_propname(), uiDefBlockBut(), uiDefBlockButN(), uiDefBut(), uiDefHotKeyevtButS(), uiDefIconBlockBut(), uiDefIconBut(), uiDefIconMenuBut(), uiDefIconTextBlockBut(), uiDefIconTextBut(), uiDefIconTextMenuBut(), uiDefIDPoinBut(), uiDefKeyevtButS(), uiDefMenuBut(), uiDefPulldownBut(), and uiDefSearchBut().
static uiBut* ui_def_but_operator_ptr (uiBlock * block, int type, wmOperatorType * ot, int opcontext, const char * str, int x1, int y1, short x2, short y2, const char * tip) [static]
Definition at line 2815 of file interface.c.
References uiBut::flag, uiBut::lock, uiBut::lockstr, NULL, uiBut::opcontext, uiBut::optype, RNA_struct_ui_description(), RNA_struct_ui_name(), wmOperatorType::srna, UI_BUT_DISABLED, UI_BUT_UNDO, and ui_def_but().
Referenced by uiDefButO_ptr(), uiDefIconButO_ptr(), and uiDefIconTextButO_ptr().
static uiBut* ui_def_but_operator_text (uiBlock * block, int type, const char * opname, int opcontext, const char * str, int x1, int y1, short x2, short y2, void * poin, float min, float max, float a1, float a2, const char * tip) [static]
Definition at line 2853 of file interface.c.
References wmOperatorType::description, uiBut::flag, uiBut::lock, uiBut::lockstr, wmOperatorType::name, uiBut::opcontext, uiBut::optype, UI_BUT_DISABLED, UI_BUT_UNDO, ui_def_but(), and WM_operatortype_find().
Referenced by uiDefButTextO().
static uiBut* ui_def_but_rna (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, PointerRNA * ptr, PropertyRNA * prop, int index, float min, float max, float a1, float a2, const char * tip) [static]
Definition at line 2652 of file interface.c.
References uiBut::a1, BLI_dynstr_append(), BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), ELEM, uiBlock::evil_C, FALSE, uiBut::flag, i, EnumPropertyItem::icon, uiBut::icon, LISTROW, MEM_freeN(), MENU, EnumPropertyItem::name, NULL, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_STRING, RNA_property_array_length(), RNA_property_editable(), RNA_property_enum_get(), RNA_property_enum_items_gettexted(), RNA_property_float_range(), RNA_property_float_ui_range(), RNA_property_int_range(), RNA_property_int_ui_range(), RNA_property_string_maxlength(), RNA_property_type(), RNA_property_ui_description(), RNA_property_ui_icon(), RNA_property_ui_name(), uiBut::rnaindex, uiBut::rnapoin, uiBut::rnaprop, ROW, step(), ui_but_is_rna_undo(), UI_BUT_UNDO, ui_def_but(), UI_DEF_BUT_RNA_DISABLE, ui_get_but_step_unit(), UI_HAS_ICON, UI_ICON_LEFT, ui_is_but_unit(), and UI_MAX_DRAW_STR.
Referenced by ui_def_but_rna_propname(), uiDefButR_prop(), uiDefIconButR_prop(), and uiDefIconTextButR_prop().
static uiBut* ui_def_but_rna_propname (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, PointerRNA * ptr, const char * propname, int index, float min, float max, float a1, float a2, const char * tip) [static]
Definition at line 2798 of file interface.c.
References NULL, RNA_struct_find_property(), ui_def_but(), ui_def_but_rna(), and UI_DEF_BUT_RNA_DISABLE.
Referenced by uiDefButR(), uiDefIconButR(), and uiDefIconTextButR().
void ui_delete_linkline (uiLinkLine * line, uiBut * but)
Definition at line 1210 of file interface.c.
References BLI_remlink(), uiLinkLine::from, uiLink::lines, link(), uiBut::link, MEM_freeN(), NULL, uiLink::poin, uiBut::poin, uiLink::ppoin, uiLinkLine::to, and uiLink::totlink.
Referenced by cut_links_exec().
static void ui_draw_linkline (uiLinkLine * line) [static]
Definition at line 501 of file interface.c.
References uiLinkLine::flag, uiLinkLine::from, NULL, uiLinkLine::to, ui_draw_link_bezier(), UI_SELECT, uiBut::x1, uiBut::x2, rcti::xmax, rcti::xmin, uiBut::y1, uiBut::y2, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_links().
static void ui_draw_links (uiBlock * block) [static]
Definition at line 520 of file interface.c.
References uiBlock::buttons, ListBase::first, uiLink::lines, LINK, uiBut::link, uiLinkLine::next, uiBut::next, uiBut::type, and ui_draw_linkline().
Referenced by uiDrawBlock().
void UI_exit (void)
Definition at line 3683 of file interface.c.
References ui_resources_free().
Referenced by WM_exit_ext().
static uiBut* ui_find_inlink (uiBlock * block, void * poin) [static]
Definition at line 1127 of file interface.c.
References uiBlock::buttons, ListBase::first, INLINK, uiBut::next, NULL, uiBut::poin, and uiBut::type.
Referenced by uiComposeLinks(), and uiFindInlink().
void ui_fontscale (short * points, float aspect)
Definition at line 950 of file interface.c.
References ceilf, floorf, and sqrt().
Referenced by ui_searchbox_create(), and uiDrawBlock().
static void ui_free_but (const bContext * C, uiBut * but) [static]
Definition at line 1969 of file interface.c.
References uiBut::active, BUT_IMAGE, uiBut::func_argN, IMB_freeImBuf(), uiBut::link, MEM_freeN(), uiBut::opptr, uiBut::poin, uiBut::str, uiBut::strdata, uiBut::type, ui_button_active_free(), ui_free_link(), and WM_operator_properties_free().
Referenced by ui_but_update_from_old_block(), uiButActiveOnly(), and uiFreeBlock().
static void ui_free_link (uiLink * link) [static]
Definition at line 1960 of file interface.c.
References BLI_freelistN(), uiLink::lines, and MEM_freeN().
Referenced by ui_free_but().
static double ui_get_but_scale_unit (uiBut * but, double value) [static]
Definition at line 1557 of file interface.c.
References uiBut::block, CTX_data_scene(), uiBlock::evil_C, FRA2TIME, pow(), PROP_UNIT_AREA, PROP_UNIT_LENGTH, PROP_UNIT_TIME, PROP_UNIT_VOLUME, UnitSettings::scale_length, uiButGetUnitType(), and uiBlock::unit.
Referenced by ui_get_but_step_unit(), and ui_get_but_string_unit().
static float ui_get_but_step_unit (uiBut * but, float step_default) [static]
Definition at line 1614 of file interface.c.
References uiBut::block, bUnit_ClosestScalar(), RNA_SUBTYPE_UNIT_VALUE, step(), UnitSettings::system, ui_get_but_scale_unit(), uiButGetUnitType(), and uiBlock::unit.
Referenced by ui_def_but_rna().
void ui_get_but_string (uiBut * but, char * str, size_t maxlen)
Definition at line 1630 of file interface.c.
References BLI_snprintf(), BLI_strncpy(), ELEM3, IDPOIN, uiBut::idpoin_idpp, MEM_freeN(), MIN2, ID::name, NULL, uiBut::poin, PROP_POINTER, PROP_STRING, RNA_property_pointer_get(), RNA_property_string_get_alloc(), RNA_property_type(), RNA_struct_name_get_alloc(), uiBut::rnapoin, uiBut::rnaprop, SEARCH_MENU, TEX, uiBut::type, ui_but_anim_expression_get(), ui_but_float_precision(), ui_get_but_string_unit(), ui_get_but_val(), ui_is_but_float(), and ui_is_but_unit().
Referenced by ui_but_copy_paste(), ui_check_but(), ui_textedit_begin(), and ui_tooltip_create().
int ui_get_but_string_max_length (uiBut * but)
Definition at line 1547 of file interface.c.
References ELEM, uiBut::hardmax, IDPOIN, MAX_ID_NAME, SEARCH_MENU, TEX, uiBut::type, and UI_MAX_DRAW_STR.
Referenced by ui_searchbox_autocomplete(), and ui_textedit_begin().
static void ui_get_but_string_unit (uiBut * but, char * str, int len_max, double value, int pad) [static]
Definition at line 1597 of file interface.c.
References uiBut::a2, uiBut::block, bUnit_AsString(), UnitSettings::flag, PRECISION_FLOAT_MAX, RNA_SUBTYPE_UNIT_VALUE, UnitSettings::scale_length, UnitSettings::system, ui_get_but_scale_unit(), uiButGetUnitType(), uiBlock::unit, and USER_UNIT_OPT_SPLIT.
Referenced by ui_check_but(), and ui_get_but_string().
double ui_get_but_val (uiBut * but)
Definition at line 1380 of file interface.c.
References CHA, PointerRNA::data, uiBut::editval, uiBut::editvec, FLO, HSVSLI, INT, NULL, uiBut::poin, uiBut::pointype, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, rgb_to_hsv(), RNA_property_array_check(), RNA_property_boolean_get(), RNA_property_boolean_get_index(), RNA_property_enum_get(), RNA_property_float_get(), RNA_property_float_get_index(), RNA_property_int_get(), RNA_property_int_get_index(), RNA_property_type(), uiBut::rnaindex, uiBut::rnapoin, uiBut::rnaprop, SHO, uiBut::str, and uiBut::type.
Referenced by do_picker_new_mode_cb(), ui_apply_but_NUM(), ui_apply_but_TOG(), ui_blockopen_begin(), ui_but_start_drag(), ui_get_but_string(), ui_numedit_begin(), ui_step_name_menu(), ui_tooltip_create(), widget_numslider(), and widget_scroll().
void ui_get_but_vectorf (uiBut * but, float vec[3])
Definition at line 1252 of file interface.c.
References BUT_NORMAL, CHA, copy_v3_v3(), uiBut::editvec, FLO, MIN2, normalize_v3(), NULL, uiBut::poin, uiBut::pointype, PROP_FLOAT, RNA_property_array_length(), RNA_property_float_get_index(), RNA_property_type(), uiBut::rnapoin, uiBut::rnaprop, and uiBut::type.
Referenced by ui_blockopen_begin(), ui_but_copy_paste(), ui_do_but_BLOCK(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_draw_but_HSV_v(), ui_draw_but_HSVCIRCLE(), ui_draw_but_HSVCUBE(), ui_draw_but_NORMAL(), ui_ndofedit_but_HSVCIRCLE(), ui_ndofedit_but_HSVCUBE(), ui_numedit_begin(), ui_numedit_but_HSVCIRCLE(), ui_numedit_but_HSVCUBE(), ui_picker_small_wheel_cb(), and widget_swatch().
void UI_init (void)
Definition at line 3665 of file interface.c.
References ui_resources_init().
Referenced by WM_init().
void UI_init_userdef (void)
Definition at line 3671 of file interface.c.
References init_userdef_do_versions(), and uiStyleInit().
Referenced by wm_init_userdef().
int ui_is_but_float (uiBut * but)
Definition at line 1332 of file interface.c.
References FLO, uiBut::poin, uiBut::pointype, PROP_FLOAT, RNA_property_type(), and uiBut::rnaprop.
Referenced by ui_check_but(), ui_do_but_NUM(), ui_do_but_SLI(), ui_get_but_string(), ui_numedit_but_NUM(), ui_numedit_but_SLI(), and ui_set_but_string().
int ui_is_but_rna_valid (uiBut * but)
Definition at line 1369 of file interface.c.
References uiBut::drawstr, FALSE, NULL, RNA_struct_contains_property(), uiBut::rnapoin, uiBut::rnaprop, and TRUE.
static void ui_is_but_sel (uiBut * but, double * value) [static]
Definition at line 1064 of file interface.c.
References uiBut::bit, uiBut::bitnr, BTST, BUT, BUT_TOGDUAL, COL, ELEM3, uiBut::flag, uiBut::hardmax, uiBut::hardmin, HOTKEYEVT, ICONTOG, ICONTOGN, KEYEVT, LISTROW, OPTION, OPTIONN, PROP_ENUM_FLAG, RNA_property_flag(), uiBut::rnaprop, ROW, TOG, TOG3, TOGBUT, TOGN, TOGR, uiBut::type, UI_GET_BUT_VALUE_INIT, and UI_SELECT.
Referenced by ui_check_but(), and ui_set_but_val().
int ui_is_but_unit (uiBut * but)
Definition at line 1343 of file interface.c.
References uiBut::block, PROP_UNIT_NONE, PROP_UNIT_ROTATION, PROP_UNIT_TIME, UnitSettings::system, UnitSettings::system_rotation, uiButGetUnitType(), uiBlock::unit, USER_UNIT_NONE, and USER_UNIT_ROT_RADIANS.
Referenced by ui_check_but(), ui_convert_to_unit_alt_name(), ui_def_but_rna(), ui_get_but_string(), ui_numedit_apply_snapf(), and ui_set_but_string_eval_num().
static void ui_menu_block_set_keyaccels (uiBlock * block) [static]
Definition at line 735 of file interface.c.
References BLOCK, BUT, uiBlock::buttons, ELEM4, ListBase::first, uiBut::flag, uiBlock::maxx, MENU, uiBut::menu_key, uiBlock::minx, uiBut::next, PULLDOWN, uiBut::str, uiBut::type, and UI_HIDDEN.
Referenced by uiEndBlock().
static void ui_menu_block_set_keymaps (const bContext * C, uiBlock * block) [static]
Definition at line 836 of file interface.c.
References uiBlock::buttons, PointerRNA::data, FALSE, ListBase::first, wmOperatorType::idname, MenuType::idname, IDP_AddToGroup(), IDP_AssignString(), IDP_FreeProperty(), IDP_GROUP, IDP_New(), IDP_NewString(), if(), uiBlock::maxx, MEM_freeN(), uiBlock::minx, mt, uiBut::next, NULL, uiBut::opcontext, uiBut::opptr, uiBut::optype, TRUE, ui_but_add_shortcut(), uiButGetMenuType(), WM_key_event_operator_string(), and WM_OP_INVOKE_REGION_WIN.
Referenced by uiEndBlock().
static void ui_popup_bounds_block (const bContext * C, uiBlock * block, int bounds_calc) [static]
Definition at line 331 of file interface.c.
References uiBlock::bounds, CTX_wm_window(), wmWindow::eventstate, uiBlock::flag, MAX2, uiBlock::maxx, uiBlock::maxy, uiBlock::minx, uiBlock::miny, uiBlock::mx, uiBlock::my, UI_BLOCK_BOUNDS_POPUP_MENU, UI_BLOCK_LOOP, ui_block_translate(), ui_bounds_block(), ui_text_bounds_block(), wm_window_get_size(), wmEvent::x, and wmEvent::y.
Referenced by uiEndBlock().
void UI_reinit_font (void)
Definition at line 3678 of file interface.c.
References uiStyleInit().
void ui_set_but_default (bContext * C, short all)
Definition at line 1846 of file interface.c.
References RNA_boolean_set(), WM_OP_EXEC_DEFAULT, WM_operator_name_call(), WM_operator_properties_create(), and WM_operator_properties_free().
Referenced by ui_do_button().
void ui_set_but_soft_range (uiBut * but, double value)
Definition at line 1882 of file interface.c.
References FLT_MAX, uiBut::hardmax, uiBut::hardmin, PROP_FLOAT, PROP_INT, RNA_property_array_length(), RNA_property_float_get_array_range(), RNA_property_float_ui_range(), RNA_property_int_get_array_range(), RNA_property_int_ui_range(), RNA_property_type(), uiBut::rnapoin, uiBut::rnaprop, soft_range_round_down(), soft_range_round_up(), uiBut::softmax, and uiBut::softmin.
Referenced by ui_check_but().
int ui_set_but_string (bContext * C, uiBut * but, const char * str)
Definition at line 1763 of file interface.c.
References BLI_strncpy(), BLI_strncpy_utf8(), ELEM3, fabs(), FALSE, uiBut::hardmax, uiBut::hardmin, IDPOIN, uiBut::idpoin_func, uiBut::idpoin_idpp, NULL, NUMABS, uiBut::poin, PointerRNA_NULL, PROP_POINTER, PROP_STRING, RNA_property_collection_lookup_string(), RNA_property_editable(), RNA_property_pointer_set(), RNA_property_string_set(), RNA_property_type(), uiBut::rnapoin, uiBut::rnaprop, uiBut::rnasearchpoin, uiBut::rnasearchprop, SEARCH_MENU, TEX, uiBut::type, ui_but_anim_expression_create(), ui_but_anim_expression_set(), ui_is_but_float(), ui_is_but_utf8(), ui_set_but_string_eval_num(), and ui_set_but_val().
Referenced by ui_apply_but_IDPOIN(), ui_apply_but_NUM(), ui_apply_but_TEX(), and ui_but_copy_paste().
int ui_set_but_string_eval_num (bContext * C, uiBut * but, const char * str, double * value)
Definition at line 1722 of file interface.c.
References BLI_snprintf(), BPY_button_exec(), FALSE, TRUE, and ui_is_but_unit().
Referenced by ui_but_copy_paste(), and ui_set_but_string().
void ui_set_but_val (uiBut * but, double value)
Definition at line 1446 of file interface.c.
References CHA, uiBut::editval, uiBut::editvec, FLO, hsv_to_rgb(), HSVSLI, INT, uiBut::poin, uiBut::pointype, PROP_BOOLEAN, PROP_ENUM, PROP_ENUM_FLAG, PROP_FLOAT, PROP_INT, rgb_to_hsv(), RNA_property_array_length(), RNA_property_boolean_set(), RNA_property_boolean_set_index(), RNA_property_editable(), RNA_property_enum_get(), RNA_property_enum_set(), RNA_property_flag(), RNA_property_float_set(), RNA_property_float_set_index(), RNA_property_int_set(), RNA_property_int_set_index(), RNA_property_type(), uiBut::rnaindex, uiBut::rnapoin, uiBut::rnaprop, SHO, uiBut::str, uiBut::type, UI_BUT_VALUE_UNSET, and ui_is_but_sel().
Referenced by ui_apply_but_BLOCK(), ui_apply_but_BUTM(), ui_apply_but_NUM(), ui_apply_but_ROW(), ui_apply_but_TOG(), ui_check_but(), ui_do_but_HOTKEYEVT(), ui_do_but_KEYEVT(), ui_set_but_string(), and ui_update_block_buts_rgb().
void ui_set_but_vectorf (uiBut * but, const float vec[3])
Definition at line 1297 of file interface.c.
References CHA, copy_v3_v3(), uiBut::editvec, FLO, MIN2, uiBut::poin, uiBut::pointype, PROP_FLOAT, RNA_property_array_length(), RNA_property_float_set_index(), RNA_property_type(), uiBut::rnapoin, and uiBut::rnaprop.
Referenced by ui_apply_but_VEC(), ui_but_copy_paste(), ui_do_but_BLOCK(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_ndofedit_but_HSVCIRCLE(), ui_ndofedit_but_HSVCUBE(), ui_numedit_but_HSVCIRCLE(), ui_picker_small_wheel_cb(), ui_set_but_hsv(), and ui_update_block_buts_rgb().
static void ui_text_bounds_block (uiBlock * block, float offset) [static]
Definition at line 214 of file interface.c.
References BLF_width(), uiBlock::bounds, uiBlock::buttons, uiBut::drawstr, ListBase::first, i, MAX2, uiBlock::minbounds, uiBut::next, SEPR, uiBut::type, ui_check_but(), UI_GetStyle(), uiFontStyle::uifont_id, uiStyleFontSet(), uiStyle::widget, uiBut::x1, and uiBut::x2.
Referenced by ui_popup_bounds_block(), and uiEndBlock().
void ui_window_to_block (const ARegion * ar, uiBlock * block, int * x, int * y)
Definition at line 176 of file interface.c.
References ui_window_to_block_fl().
Referenced by ui_but_find_mouse_over(), ui_but_mouse_inside_icon(), ui_do_but_COLORBAND(), ui_do_but_CURVE(), ui_do_but_HISTOGRAM(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_do_but_NORMAL(), ui_do_but_NUM(), ui_do_but_SCROLL(), ui_do_but_SLI(), ui_do_but_textedit(), ui_do_but_textedit_select(), ui_do_but_TRACKPREVIEW(), ui_do_but_VECTORSCOPE(), ui_do_but_WAVEFORM(), ui_handle_menu_event(), ui_handle_menu_return_submenu(), ui_handler_panel_region(), ui_list_find_mouse_over(), and ui_mouse_inside_button().
void ui_window_to_block_fl (const ARegion * ar, uiBlock * block, float * x, float * y)
Definition at line 146 of file interface.c.
References Panel::ofsx, Panel::ofsy, uiBlock::panel, uiBlock::winmat, ARegion::winrct, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_window_to_block().
void ui_window_to_region (const ARegion * ar, int * x, int * y)
Definition at line 189 of file interface.c.
References ARegion::winrct, rcti::xmin, and rcti::ymin.
Referenced by ui_mouse_inside_region().
uiBlock* uiBeginBlock (const bContext * C, ARegion * region, const char * name, short dt)
Definition at line 2081 of file interface.c.
References uiBlock::active, uiBlock::aspect, uiBlock::auto_open, BLI_strncpy(), RenderData::color_mgt_flag, uiBlock::color_profile, CTX_data_scene(), CTX_wm_window(), uiBlock::dt, uiBlock::evil_C, fabs(), uiBlock::flag, bScreen::mainwin, MEM_callocN(), MEM_mallocN(), uiBlock::name, Scene::r, R_COLOR_MANAGEMENT, wmWindow::screen, ARegion::swinid, TRUE, UI_BLOCK_LOOP, uiBlockSetRegion(), Scene::unit, uiBlock::unit, uiBlock::winmat, wm_subwindow_getmatrix(), and wm_subwindow_getsize().
void uiBlockBeginAlign (uiBlock * block)
Definition at line 2336 of file interface.c.
References uiBlock::alignnr, uiBlock::flag, UI_BUT_ALIGN, UI_BUT_ALIGN_DOWN, and uiBlockEndAlign().
Referenced by buttons_header_buttons(), colorband_buttons_small(), controller_state_mask_menu(), curvemap_clipping_func(), draw_actuatorbuttons(), draw_constraint(), draw_controllerbuttons(), draw_default_sensor_header(), draw_group_socket(), draw_modifier(), draw_modifier__envelope(), draw_modifier__generator(), draw_sensorbuttons(), file_draw_buttons(), logic_buttons(), template_ID(), ui_item_array(), uiBlockPicker(), uiTemplateImage(), uiTemplateMarker(), uiTemplateReportsBanner(), uvedit_vertex_buttons(), v3d_editvertex_buts(), and view3d_panel_vgroup().
void uiBlockClearButLock (uiBlock * block)
Definition at line 1202 of file interface.c.
References uiBlock::lock, uiBlock::lockstr, and NULL.
Referenced by draw_constraint(), and draw_modifier().
void uiBlockClearFlag (uiBlock * block, int flag)
Definition at line 3318 of file interface.c.
References uiBlock::flag.
Referenced by wm_block_create_redo(), wm_block_dialog_create(), and wm_operator_ui_create().
void uiBlockEndAlign (uiBlock * block)
Definition at line 2358 of file interface.c.
References uiBlock::flag, and UI_BUT_ALIGN.
Referenced by buttons_header_buttons(), colorband_buttons_large(), colorband_buttons_small(), controller_state_mask_menu(), draw_actuatorbuttons(), draw_constraint(), draw_controllerbuttons(), draw_default_sensor_header(), draw_group_socket(), draw_modifier(), draw_modifier__generator(), draw_sensorbuttons(), file_draw_buttons(), logic_buttons(), node_update_basis(), template_ID(), ui_item_array(), uiblock_layer_pass_arrow_buttons(), uiBlockBeginAlign(), uiBlockPicker(), uiEndBlock(), uiTemplateMarker(), uiTemplateReportsBanner(), uvedit_vertex_buttons(), v3d_editvertex_buts(), and view3d_panel_vgroup().
void uiBlockFlipOrder (uiBlock * block)
Definition at line 3276 of file interface.c.
References BLI_addtail(), BLI_remlink(), uiBlock::buttons, ListBase::first, uiBut::flag, uiBlock::flag, ListBase::last, uiBut::next, next, NULL, SWAP, UI_BLOCK_NO_FLIP, UI_BUT_ALIGN, USER_MENUFIXEDORDER, uiBut::y1, and uiBut::y2.
Referenced by ui_block_func_POPUP(), and ui_block_position().
void uiBlockSetButLock (uiBlock * block, int val, const char * lockstr)
Definition at line 1194 of file interface.c.
References uiBlock::lock, and uiBlock::lockstr.
Referenced by draw_constraint(), draw_modifier(), uiLayoutOperatorButs(), uiTemplateConstraint(), and uiTemplateModifier().
void uiBlockSetButmFunc (uiBlock * block, uiMenuHandleFunc func, void * arg)
Definition at line 3419 of file interface.c.
References uiBlock::butm_func, and uiBlock::butm_func_arg.
Referenced by actuator_menu(), controller_menu(), curvemap_brush_tools_func(), curvemap_tools_func(), object_state_mask_menu(), and sensor_menu().
void uiBlockSetDirection (uiBlock * block, int direction)
Definition at line 3270 of file interface.c.
References uiBlock::direction.
Referenced by actuator_menu(), controller_menu(), controller_state_mask_menu(), curvemap_brush_tools_func(), curvemap_clipping_func(), curvemap_tools_func(), draw_group_socket(), id_search_menu(), menu_add_shortcut(), menu_change_shortcut(), object_state_mask_menu(), operator_search_menu(), sensor_menu(), tool_search_menu(), and ui_block_func_POPUP().
void uiBlockSetDrawExtraFunc (uiBlock * block, void(*)(const bContext *C, void *idv, void *arg1, void *arg2, rcti *rect) func, void * arg1, void * arg2)
Definition at line 3449 of file interface.c.
References uiBlock::drawextra, uiBlock::drawextra_arg1, and uiBlock::drawextra_arg2.
void uiBlockSetEmboss (uiBlock * block, char dt)
Definition at line 2138 of file interface.c.
References uiBlock::dt.
Referenced by ANIM_channel_draw_widgets(), ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), buttons_header_buttons(), curvemap_buttons_layout(), draw_actuatorbuttons(), draw_constraint(), draw_group_socket(), draw_modifier(), ED_area_header_standardbuttons(), file_panel_category(), gp_drawui_layer(), graph_panel_drivers(), list_item_row(), node_draw_basis(), node_draw_hidden(), node_socket_button_output_file(), outliner_draw_keymapbuts(), outliner_draw_restrictbuts(), outliner_draw_rnabuts(), ui_item_menu(), ui_node_draw_input(), uiItemFullO_ptr(), uiItemFullR(), uiTemplateHeader3D(), uiTemplateReportsBanner(), and wm_block_create_splash().
void uiBlockSetFlag (uiBlock * block, int flag)
Definition at line 3313 of file interface.c.
References uiBlock::flag.
Referenced by id_search_menu(), menu_add_shortcut(), menu_change_shortcut(), node_uiblocks_init(), operator_search_menu(), socket_component_menu(), tool_search_menu(), ui_block_func_COL(), ui_block_func_ICONROW(), ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), ui_block_func_POPUP(), wm_block_create_redo(), wm_block_create_splash(), wm_block_dialog_create(), wm_block_search_menu(), wm_enum_search_menu(), and wm_operator_ui_create().
void uiBlockSetFunc (uiBlock * block, uiButHandleFunc func, void * arg1, void * arg2)
Definition at line 3425 of file interface.c.
References uiBlock::func, uiBlock::func_arg1, and uiBlock::func_arg2.
Referenced by draw_constraint(), file_draw_buttons(), file_panel_operator(), gp_drawui_layer(), wm_block_create_splash(), and wm_block_dialog_create().
void uiBlockSetHandleFunc (uiBlock * block, uiBlockHandleFunc func, void * arg)
Definition at line 3413 of file interface.c.
References uiBlock::handle_func, and uiBlock::handle_func_arg.
Referenced by buttons_header_buttons(), clip_panel_operator_redo(), draw_constraint(), file_draw_buttons(), graph_panel_drivers(), graph_panel_key_properties(), graph_panel_modifiers(), graph_panel_properties(), image_panel_uv(), logic_buttons(), logic_buttons_new(), menu_add_shortcut(), menu_change_shortcut(), nla_panel_actclip(), nla_panel_animdata(), nla_panel_evaluation(), nla_panel_modifiers(), nla_panel_properties(), nla_panel_track(), node_uiblocks_init(), ui_layout_end(), uiTemplateEditModeSelection(), uiTemplateHeader3D(), uiTemplateMarker(), uiTemplatePreview(), uiTemplateRunningJobs(), view3d_panel_object(), view3d_panel_operator_redo(), view3d_panel_vgroup(), and wm_block_create_redo().
void uiBlockSetNFunc (uiBlock * block, uiButHandleFunc func, void * argN, void * arg2)
Definition at line 3432 of file interface.c.
References uiBlock::func_arg2, uiBlock::func_argN, uiBlock::funcN, and MEM_freeN().
Referenced by curvemap_buttons_layout(), uiTemplateImage(), and uiTemplateMarker().
void uiBlockSetRegion (uiBlock * block, ARegion * region)
Definition at line 2059 of file interface.c.
References uiBlock::active, BLI_addhead(), BLI_findstring(), uiBlock::name, NULL, uiBlock::oldblock, uiBlock::panel, and ARegion::uiblocks.
Referenced by ui_block_func_POPUP(), and uiBeginBlock().
void uiBlockSetXOfs (uiBlock * block, int xofs)
Definition at line 3323 of file interface.c.
References uiBlock::xofs.
int uiBlocksGetYMin (ListBase * lb)
Definition at line 3258 of file interface.c.
References ListBase::first, min, uiBlock::miny, and uiBlock::next.
void uiBoundsBlock (uiBlock * block, int addval)
Definition at line 396 of file interface.c.
References uiBlock::bounds, uiBlock::dobounds, NULL, and UI_BLOCK_BOUNDS.
Referenced by id_search_menu(), operator_search_menu(), tool_search_menu(), ui_block_func_COL(), and uiEndBlock().
int uiButActiveOnly (const bContext * C, uiBlock * block, uiBut * but)
Definition at line 675 of file interface.c.
References uiBut::active, BLI_remlink(), uiBlock::buttons, CTX_wm_region(), ListBase::first, uiBut::next, uiBlock::oldblock, ui_but_equals_old(), ui_button_activate_do(), and ui_free_but().
void uiButClearFlag (uiBut * but, int flag)
Definition at line 3333 of file interface.c.
References uiBut::flag.
Referenced by buttons_context_draw(), ED_area_header_standardbuttons(), ED_area_header_switchbutton(), file_draw_buttons(), file_draw_list(), uiLayoutOperatorButs(), and uiTemplateHeader3D().
PointerRNA* uiButGetOperatorPtrRNA (uiBut * but) [read]
Definition at line 3382 of file interface.c.
References MEM_callocN(), uiBut::opptr, uiBut::optype, and WM_operator_properties_create_ptr().
Referenced by draw_group_socket(), file_draw_buttons(), ui_but_copy_paste(), ui_tooltip_create(), and uiItemFullO_ptr().
int uiButGetRetVal (uiBut * but)
Definition at line 3338 of file interface.c.
References uiBut::retval.
int uiButGetUnitType (uiBut * but)
Definition at line 3397 of file interface.c.
References if(), NULL, RNA_property_subtype(), RNA_SUBTYPE_UNIT, uiBut::rnaprop, and uiBut::unit_type.
Referenced by ui_convert_to_unit_alt_name(), ui_get_but_scale_unit(), ui_get_but_step_unit(), ui_get_but_string_unit(), ui_is_but_unit(), ui_numedit_apply_snapf(), and ui_tooltip_create().
void uiButSetCompleteFunc (uiBut * but, uiButCompleteFunc func, void * arg)
Definition at line 3474 of file interface.c.
References uiBut::autocomplete_func, and uiBut::autofunc_arg.
Referenced by file_draw_buttons(), and uiDefIDPoinBut().
void uiButSetDragID (uiBut * but, ID * id)
Definition at line 3343 of file interface.c.
References uiBut::dragpoin, uiBut::dragtype, and WM_DRAG_ID.
Referenced by template_ID(), tselem_draw_icon_uibut(), and uiItemLDrag().
void uiButSetDragImage (uiBut * but, const char * path, int icon, struct ImBuf * imb, float scale)
Definition at line 3373 of file interface.c.
References uiBut::dragpoin, uiBut::dragtype, uiBut::icon, uiBut::imb, uiBut::imb_scale, and WM_DRAG_PATH.
Referenced by file_draw_preview().
void uiButSetDragName (uiBut * but, const char * name)
Definition at line 3361 of file interface.c.
References uiBut::dragpoin, uiBut::dragtype, and WM_DRAG_NAME.
void uiButSetDragPath (uiBut * but, const char * path)
Definition at line 3355 of file interface.c.
References uiBut::dragpoin, uiBut::dragtype, and WM_DRAG_PATH.
Referenced by file_draw_icon().
void uiButSetDragRNA (uiBut * but, PointerRNA * ptr)
Definition at line 3349 of file interface.c.
References uiBut::dragpoin, uiBut::dragtype, and WM_DRAG_RNA.
void uiButSetDragValue (uiBut * but)
Definition at line 3368 of file interface.c.
References uiBut::dragtype, and WM_DRAG_VALUE.
void uiButSetFlag (uiBut * but, int flag)
Definition at line 3328 of file interface.c.
References uiBut::flag.
Referenced by draw_group_socket(), draw_modifier(), file_draw_buttons(), file_draw_list(), file_panel_category(), list_item_row(), template_ID(), ui_but_search_test(), ui_item_with_label(), uiDefAutoButR(), uiItemFullO_ptr(), uiItemFullR(), and uiTemplateList().
void uiButSetFocusOnEnter (wmWindow * win, uiBut * but)
Definition at line 3650 of file interface.c.
References wmWindow::eventstate, EVT_BUT_OPEN, FALSE, KM_PRESS, wmEvent::type, and wm_event_add().
Referenced by id_search_menu(), and uiLayoutOperatorButs().
void uiButSetFunc (uiBut * but, uiButHandleFunc func, void * arg1, void * arg2)
Definition at line 3456 of file interface.c.
References uiBut::func, uiBut::func_arg1, and uiBut::func_arg2.
Referenced by ANIM_channel_draw_widgets(), ANIM_uiTemplate_fmodifier_draw(), buttons_context_draw(), circle_picker(), colorband_buttons_large(), controller_state_mask_menu(), curvemap_buttons_layout(), curvemap_clipping_func(), draw_actuatorbuttons(), draw_default_sensor_header(), draw_group_socket_name(), draw_modifier(), draw_modifier__envelope(), draw_modifier__generator(), draw_sensorbuttons(), draw_setting_widget(), ED_area_header_switchbutton(), file_panel_category(), gp_drawui_layer(), graph_panel_drivers(), graph_panel_key_properties(), logic_buttons(), node_buts_normal(), node_draw_basis(), node_draw_hidden(), node_shader_buts_dynamic(), node_socket_button_color(), node_socket_button_default(), outliner_draw_keymapbuts(), outliner_draw_restrictbuts(), square_picker(), ui_but_menu(), ui_item_array(), ui_item_with_label(), uiblock_layer_pass_arrow_buttons(), uiblock_layer_pass_buttons(), uiBlockPicker(), uiButSetSearchFunc(), uiLayoutOperatorButs(), uiTemplateImage(), uiTemplateKeymapItemProperties(), uiTemplateLayers(), uiTemplateTextureShow(), wm_block_create_splash(), and wm_block_dialog_create().
void uiButSetNFunc (uiBut * but, uiButHandleNFunc funcN, void * argN, void * arg2)
Definition at line 3463 of file interface.c.
References uiBut::func_arg2, uiBut::func_argN, uiBut::funcN, and MEM_freeN().
Referenced by colorband_buttons_large(), colorband_buttons_small(), curvemap_buttons_layout(), draw_setting_widget(), graph_panel_drivers(), template_ID(), template_texture_user_menu(), ui_node_menu_column(), ui_template_node_link_menu(), uiTemplateHistogram(), uiTemplateMarker(), and uiTemplateVectorscope().
void uiButSetRenameFunc (uiBut * but, uiButHandleRenameFunc func, void * arg1)
Definition at line 3443 of file interface.c.
References uiBut::rename_arg1, and uiBut::rename_func.
Referenced by file_draw_list(), and outliner_buttons().
void uiButSetSearchFunc (uiBut * but, uiButSearchFunc sfunc, void * arg, uiButHandleFunc bfunc, void * active)
Definition at line 3632 of file interface.c.
References uiBut::block, uiBut::drawstr, uiBlock::flag, uiBut::search_arg, uiBut::search_func, UI_BLOCK_LOOP, ui_but_search_test(), and uiButSetFunc().
Referenced by id_search_menu(), operator_search_menu(), tool_search_menu(), ui_but_add_search(), uiTemplateOperatorSearch(), wm_block_search_menu(), and wm_enum_search_menu().
void uiButSetUnitType (uiBut * but, const int unit_type)
Definition at line 3392 of file interface.c.
References RNA_SUBTYPE_UNIT_VALUE, and uiBut::unit_type.
Referenced by graph_panel_key_properties(), and v3d_editvertex_buts().
void uiCenteredBoundsBlock (uiBlock * block, int addval)
Definition at line 431 of file interface.c.
References uiBlock::bounds, uiBlock::dobounds, and UI_BLOCK_BOUNDS_POPUP_CENTER.
Referenced by wm_block_create_splash().
void uiComposeLinks (uiBlock * block)
Definition at line 1156 of file interface.c.
References uiBlock::buttons, ListBase::first, uiLink::lines, link(), LINK, uiBut::link, uiBut::next, uiLink::poin, uiLink::ppoin, uiLink::totlink, uiBut::type, ui_add_link_line(), and ui_find_inlink().
Referenced by logic_buttons(), and logic_buttons_new().
uiBut* uiDefBlockBut (uiBlock * block, uiBlockCreateFunc func, void * arg, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3493 of file interface.c.
References BLOCK, uiBut::block_create_func, ui_check_but(), and ui_def_but().
Referenced by draw_controller_header(), logic_buttons(), logic_buttons_new(), outliner_draw_keymapbuts(), and view3d_panel_tool_shelf().
uiBut* uiDefBlockButN (uiBlock * block, uiBlockCreateFunc func, void * argN, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3501 of file interface.c.
References BLOCK, uiBut::block_create_func, uiBut::func_argN, MEM_freeN(), NULL, ui_check_but(), and ui_def_but().
Referenced by node_socket_button_components(), and template_ID().
uiBut* uiDefBut (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, void * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 2883 of file interface.c.
References ui_check_but(), and ui_def_but().
Referenced by actuator_menu(), colorband_buttons_large(), colorband_buttons_small(), controller_menu(), controller_state_mask_menu(), curvemap_buttons_layout(), curvemap_clipping_func(), draw_actuatorbuttons(), draw_constraint(), draw_controllerbuttons(), draw_group_socket_name(), draw_modifier(), draw_modifier__envelope(), draw_modifier__generator(), draw_sensorbuttons(), file_draw_buttons(), file_draw_list(), file_draw_preview(), graph_panel_drivers(), id_search_menu(), logic_buttons(), node_draw_basis(), node_draw_hidden(), node_shader_buts_dynamic(), node_socket_button_color(), node_socket_button_label(), object_state_mask_menu(), operator_search_menu(), outliner_buttons(), outliner_draw_keymapbuts(), sensor_menu(), template_ID(), tool_search_menu(), ui_block_func_ICONTEXTROW(), ui_item_array(), ui_item_disabled(), ui_item_with_label(), ui_layout_box(), ui_node_menu_column(), ui_template_node_link_menu(), uiBlockPicker(), uiDefAutoButR(), uiDefButBit(), uiDefButC(), uiDefButF(), uiDefButI(), uiDefButS(), uiItemL_(), uiItemS(), uiPupMenuBegin(), uiTemplateHistogram(), uiTemplateImage(), uiTemplateMarker(), uiTemplateMovieClip(), uiTemplatePreview(), uiTemplateReportsBanner(), uiTemplateRunningJobs(), uiTemplateTrack(), uiTemplateVectorscope(), uiTemplateWaveform(), v3d_editvertex_buts(), view3d_panel_vgroup(), wm_block_create_splash(), wm_block_dialog_create(), wm_block_search_menu(), and wm_enum_search_menu().
static uiBut* uiDefButBit (uiBlock * block, int type, int bit, int retval, const char * str, int x1, int y1, short x2, short y2, void * poin, float min, float max, float a1, float a2, const char * tip) [static]
Definition at line 3004 of file interface.c.
References BIT, findBitIndex(), NULL, and uiDefBut().
Referenced by uiDefButBitC(), uiDefButBitF(), uiDefButBitI(), and uiDefButBitS().
uiBut* uiDefButBitC (uiBlock * block, int type, int bit, int retval, const char * str, int x1, int y1, short x2, short y2, char * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3042 of file interface.c.
References CHA, and uiDefButBit().
uiBut* uiDefButBitF (uiBlock * block, int type, int bit, int retval, const char * str, int x1, int y1, short x2, short y2, float * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3018 of file interface.c.
References FLO, and uiDefButBit().
uiBut* uiDefButBitI (uiBlock * block, int type, int bit, int retval, const char * str, int x1, int y1, short x2, short y2, int * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3026 of file interface.c.
References INT, and uiDefButBit().
Referenced by controller_state_mask_menu(), curvemap_clipping_func(), draw_actuatorbuttons(), draw_controllerbuttons(), logic_buttons(), and uiTemplateMarker().
uiBut* uiDefButBitS (uiBlock * block, int type, int bit, int retval, const char * str, int x1, int y1, short x2, short y2, short * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3034 of file interface.c.
References SHO, and uiDefButBit().
Referenced by draw_actuatorbuttons(), draw_sensorbuttons(), logic_buttons(), logic_buttons_new(), and v3d_editvertex_buts().
uiBut* uiDefButC (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, char * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3038 of file interface.c.
References CHA, and uiDefBut().
Referenced by draw_sensorbuttons(), and uiTemplateHeader3D().
uiBut* uiDefButF (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, float * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3014 of file interface.c.
References FLO, and uiDefBut().
Referenced by curvemap_clipping_func(), draw_actuatorbuttons(), draw_modifier__envelope(), draw_modifier__generator(), draw_sensorbuttons(), node_buts_normal(), ui_block_func_MENUSTR(), uiBlockPicker(), uiItemV(), uiTemplateMarker(), uvedit_vertex_buttons(), v3d_editvertex_buts(), and view3d_panel_vgroup().
uiBut* uiDefButI (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, int * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3022 of file interface.c.
References INT, and uiDefBut().
Referenced by curvemap_buttons_layout(), draw_actuatorbuttons(), draw_controllerbuttons(), draw_modifier__generator(), draw_sensorbuttons(), uiTemplateImage(), and uiTemplateList().
uiBut* uiDefButO (uiBlock * block, int type, const char * opname, int opcontext, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3068 of file interface.c.
References NULL, uiDefButO_ptr(), and WM_operatortype_find().
Referenced by draw_actuatorbuttons(), file_draw_buttons(), graph_panel_modifiers(), and nla_panel_modifiers().
uiBut* uiDefButO_ptr (uiBlock * block, int type, wmOperatorType * ot, int opcontext, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3061 of file interface.c.
References ui_check_but(), and ui_def_but_operator_ptr().
Referenced by uiDefButO(), and uiItemFullO_ptr().
uiBut* uiDefButR (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, PointerRNA * ptr, const char * propname, int index, float min, float max, float a1, float a2, const char * tip)
Definition at line 3046 of file interface.c.
References ui_check_but(), and ui_def_but_rna_propname().
Referenced by ANIM_channel_draw_widgets(), draw_modifier__generator(), graph_panel_key_properties(), list_item_row(), node_socket_button_color(), node_socket_button_default(), and template_ID().
uiBut* uiDefButR_prop (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, PointerRNA * ptr, PropertyRNA * prop, int index, float min, float max, float a1, float a2, const char * tip)
Definition at line 3053 of file interface.c.
References ui_check_but(), and ui_def_but_rna().
Referenced by circle_picker(), list_item_row(), square_picker(), ui_item_array(), ui_item_enum_expand(), ui_item_with_label(), uiBlockPicker(), uiDefAutoButR(), uiItemFullR(), and uiTemplateColorWheel().
uiBut* uiDefButS (uiBlock * block, int type, int retval, const char * str, int x1, int y1, short x2, short y2, short * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3030 of file interface.c.
References SHO, and uiDefBut().
Referenced by colorband_buttons_large(), colorband_buttons_small(), draw_actuatorbuttons(), draw_default_sensor_header(), draw_sensorbuttons(), logic_buttons(), node_shader_buts_dynamic(), outliner_draw_keymapbuts(), uiblock_layer_pass_buttons(), uiBlockPicker(), and uiTemplatePreview().
uiBut* uiDefButTextO (uiBlock * block, int type, const char * opname, int opcontext, const char * str, int x1, int y1, short x2, short y2, void * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3075 of file interface.c.
References ui_check_but(), and ui_def_but_operator_text().
Referenced by file_draw_buttons().
uiBut* uiDefHotKeyevtButS (uiBlock * block, int retval, const char * str, int x1, int y1, short x2, short y2, short * keypoin, short * modkeypoin, const char * tip)
Definition at line 3604 of file interface.c.
References HOTKEYEVT, uiBut::modifier_key, SHO, ui_check_but(), and ui_def_but().
uiBut* uiDefIconBlockBut (uiBlock * block, uiBlockCreateFunc func, void * arg, int retval, int icon, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3580 of file interface.c.
References BLOCK, uiBut::block_create_func, uiBut::flag, uiBut::icon, ui_check_but(), ui_def_but(), UI_HAS_ICON, and UI_ICON_LEFT.
Referenced by curvemap_buttons_layout().
uiBut* uiDefIconBut (uiBlock * block, int type, int retval, int icon, int x1, int y1, short x2, short y2, void * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3083 of file interface.c.
References ui_check_but_and_iconize(), and ui_def_but().
Referenced by ANIM_uiTemplate_fmodifier_draw(), curvemap_buttons_layout(), draw_constraint(), draw_modifier(), draw_modifier__envelope(), file_draw_icon(), gp_drawui_layer(), graph_panel_drivers(), logic_buttons(), logic_buttons_new(), node_draw_basis(), outliner_draw_restrictbuts(), template_ID(), tselem_draw_icon_uibut(), uiblock_layer_pass_arrow_buttons(), uiDefIconButBit(), uiDefIconButC(), uiDefIconButF(), uiDefIconButI(), uiDefIconButS(), uiItemL_(), uiTemplateReportsBanner(), uiTemplateRunningJobs(), and uiTemplateTextureShow().
static uiBut* uiDefIconButBit (uiBlock * block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, void * poin, float min, float max, float a1, float a2, const char * tip) [static]
Definition at line 3089 of file interface.c.
References BIT, findBitIndex(), NULL, and uiDefIconBut().
Referenced by uiDefIconButBitC(), uiDefIconButBitF(), uiDefIconButBitI(), and uiDefIconButBitS().
uiBut* uiDefIconButBitC (uiBlock * block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, char * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3128 of file interface.c.
References CHA, and uiDefIconButBit().
Referenced by buttons_context_draw(), draw_setting_widget(), list_item_row(), and uiTemplateHeader3D().
uiBut* uiDefIconButBitF (uiBlock * block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, float * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3104 of file interface.c.
References FLO, and uiDefIconButBit().
uiBut* uiDefIconButBitI (uiBlock * block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, int * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3112 of file interface.c.
References INT, and uiDefIconButBit().
Referenced by draw_modifier(), draw_setting_widget(), gp_drawui_layer(), outliner_draw_restrictbuts(), and uiTemplateMarker().
uiBut* uiDefIconButBitS (uiBlock * block, int type, int bit, int retval, int icon, int x1, int y1, short x2, short y2, short * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3120 of file interface.c.
References SHO, and uiDefIconButBit().
Referenced by draw_default_sensor_header(), draw_setting_widget(), ED_area_header_standardbuttons(), logic_buttons(), and uiTemplateEditModeSelection().
uiBut* uiDefIconButC (uiBlock * block, int type, int retval, int icon, int x1, int y1, short x2, short y2, char * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3124 of file interface.c.
References CHA, and uiDefIconBut().
uiBut* uiDefIconButF (uiBlock * block, int type, int retval, int icon, int x1, int y1, short x2, short y2, float * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3100 of file interface.c.
References FLO, and uiDefIconBut().
Referenced by ui_block_func_ICONROW(), and uiItemV().
uiBut* uiDefIconButI (uiBlock * block, int type, int retval, int icon, int x1, int y1, short x2, short y2, int * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3108 of file interface.c.
References INT, and uiDefIconBut().
uiBut* uiDefIconButO (uiBlock * block, int type, const char * opname, int opcontext, int icon, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3154 of file interface.c.
References uiDefIconButO_ptr(), and WM_operatortype_find().
Referenced by draw_group_socket(), file_draw_buttons(), template_ID(), ui_item_with_label(), uiBlockPicker(), and uiTemplateReportsBanner().
uiBut* uiDefIconButO_ptr (uiBlock * block, int type, wmOperatorType * ot, int opcontext, int icon, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3147 of file interface.c.
References ui_check_but_and_iconize(), and ui_def_but_operator_ptr().
Referenced by uiDefIconButO(), and uiItemFullO_ptr().
uiBut* uiDefIconButR (uiBlock * block, int type, int retval, int icon, int x1, int y1, short x2, short y2, PointerRNA * ptr, const char * propname, int index, float min, float max, float a1, float a2, const char * tip)
Definition at line 3132 of file interface.c.
References ui_check_but_and_iconize(), and ui_def_but_rna_propname().
Referenced by list_item_row(), and outliner_draw_restrictbuts().
uiBut* uiDefIconButR_prop (uiBlock * block, int type, int retval, int icon, int x1, int y1, short x2, short y2, PointerRNA * ptr, PropertyRNA * prop, int index, float min, float max, float a1, float a2, const char * tip)
Definition at line 3139 of file interface.c.
References ui_check_but_and_iconize(), and ui_def_but_rna().
Referenced by ui_item_enum_expand(), uiDefAutoButR(), uiItemFullR(), and uiTemplateList().
uiBut* uiDefIconButS (uiBlock * block, int type, int retval, int icon, int x1, int y1, short x2, short y2, short * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3116 of file interface.c.
References SHO, and uiDefIconBut().
uiBut* uiDefIconMenuBut (uiBlock * block, uiMenuCreateFunc func, void * arg, int icon, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3546 of file interface.c.
References uiBut::flag, uiBut::icon, uiBut::menu_create_func, PULLDOWN, ui_check_but(), ui_def_but(), UI_HAS_ICON, and UI_ICON_LEFT.
Referenced by ui_item_menu(), and uiTemplateNodeLink().
uiBut* uiDefIconTextBlockBut (uiBlock * block, uiBlockCreateFunc func, void * arg, int icon, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3561 of file interface.c.
References BLOCK, uiBut::block_create_func, uiBut::flag, uiBut::icon, ui_check_but(), ui_def_but(), UI_HAS_ICON, UI_ICON_LEFT, and UI_ICON_SUBMENU.
uiBut* uiDefIconTextBut (uiBlock * block, int type, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, void * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3161 of file interface.c.
References uiBut::flag, ui_check_but_and_iconize(), ui_def_but(), and UI_ICON_LEFT.
Referenced by curvemap_brush_tools_func(), curvemap_tools_func(), template_ID(), template_texture_user_menu(), ui_but_menu(), uiDefIconTextButBit(), uiDefIconTextButC(), uiDefIconTextButF(), uiDefIconTextButI(), uiDefIconTextButS(), uiItemL_(), uiLayoutOperatorButs(), uiPupMenuBegin(), uiTemplateImage(), and uiTemplateRunningJobs().
static uiBut* uiDefIconTextButBit (uiBlock * block, int type, int bit, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, void * poin, float min, float max, float a1, float a2, const char * tip) [static]
Definition at line 3168 of file interface.c.
References BIT, findBitIndex(), NULL, and uiDefIconTextBut().
Referenced by uiDefIconTextButBitC(), uiDefIconTextButBitF(), uiDefIconTextButBitI(), and uiDefIconTextButBitS().
uiBut* uiDefIconTextButBitC (uiBlock * block, int type, int bit, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, char * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3207 of file interface.c.
References CHA, and uiDefIconTextButBit().
uiBut* uiDefIconTextButBitF (uiBlock * block, int type, int bit, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, float * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3183 of file interface.c.
References FLO, and uiDefIconTextButBit().
uiBut* uiDefIconTextButBitI (uiBlock * block, int type, int bit, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, int * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3191 of file interface.c.
References INT, and uiDefIconTextButBit().
uiBut* uiDefIconTextButBitS (uiBlock * block, int type, int bit, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, short * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3199 of file interface.c.
References SHO, and uiDefIconTextButBit().
uiBut* uiDefIconTextButC (uiBlock * block, int type, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, char * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3203 of file interface.c.
References CHA, and uiDefIconTextBut().
Referenced by ED_area_header_switchbutton().
uiBut* uiDefIconTextButF (uiBlock * block, int type, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, float * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3179 of file interface.c.
References FLO, and uiDefIconTextBut().
Referenced by ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), and uiItemV().
uiBut* uiDefIconTextButI (uiBlock * block, int type, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, int * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3187 of file interface.c.
References INT, and uiDefIconTextBut().
uiBut* uiDefIconTextButO (uiBlock * block, int type, const char * opname, int opcontext, int icon, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3235 of file interface.c.
References uiDefIconTextButO_ptr(), and WM_operatortype_find().
Referenced by template_ID().
uiBut* uiDefIconTextButO_ptr (uiBlock * block, int type, wmOperatorType * ot, int opcontext, int icon, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3227 of file interface.c.
References uiBut::flag, ui_check_but_and_iconize(), ui_def_but_operator_ptr(), and UI_ICON_LEFT.
Referenced by uiDefIconTextButO(), and uiItemFullO_ptr().
uiBut* uiDefIconTextButR (uiBlock * block, int type, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, PointerRNA * ptr, const char * propname, int index, float min, float max, float a1, float a2, const char * tip)
Definition at line 3211 of file interface.c.
References uiBut::flag, ui_check_but_and_iconize(), ui_def_but_rna_propname(), and UI_ICON_LEFT.
uiBut* uiDefIconTextButR_prop (uiBlock * block, int type, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, PointerRNA * ptr, PropertyRNA * prop, int index, float min, float max, float a1, float a2, const char * tip)
Definition at line 3219 of file interface.c.
References uiBut::flag, ui_check_but_and_iconize(), ui_def_but_rna(), and UI_ICON_LEFT.
Referenced by ui_item_enum_expand(), uiDefAutoButR(), uiItemFullR(), and uiTemplateList().
uiBut* uiDefIconTextButS (uiBlock * block, int type, int retval, int icon, const char * str, int x1, int y1, short x2, short y2, short * poin, float min, float max, float a1, float a2, const char * tip)
Definition at line 3195 of file interface.c.
References SHO, and uiDefIconTextBut().
Referenced by file_panel_category(), and uiTemplateHeader3D().
uiBut* uiDefIconTextMenuBut (uiBlock * block, uiMenuCreateFunc func, void * arg, int icon, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3530 of file interface.c.
References uiBut::flag, uiBut::icon, uiBut::menu_create_func, PULLDOWN, ui_check_but(), ui_def_but(), UI_HAS_ICON, UI_ICON_LEFT, and UI_ICON_SUBMENU.
Referenced by ui_item_menu(), and uiTemplateTextureUser().
uiBut* uiDefIDPoinBut (uiBlock * block, uiIDPoinFuncFP func, short blocktype, int retval, const char * str, int x1, int y1, short x2, short y2, void * idpp, const char * tip)
Definition at line 3480 of file interface.c.
References autocomplete_id(), IDPOIN, uiBut::idpoin_func, uiBut::idpoin_idpp, NULL, ui_check_but(), ui_def_but(), and uiButSetCompleteFunc().
Referenced by draw_actuatorbuttons(), draw_controllerbuttons(), and draw_sensorbuttons().
uiBut* uiDefKeyevtButS (uiBlock * block, int retval, const char * str, int x1, int y1, short x2, short y2, short * spoin, const char * tip)
Definition at line 3595 of file interface.c.
References KEYEVT, SHO, ui_check_but(), and ui_def_but().
Referenced by draw_sensorbuttons(), and outliner_draw_keymapbuts().
uiBut* uiDefMenuBut (uiBlock * block, uiMenuCreateFunc func, void * arg, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3522 of file interface.c.
References uiBut::menu_create_func, PULLDOWN, ui_check_but(), and ui_def_but().
Referenced by ui_item_menu(), uiTemplateNodeLink(), and uiTemplateTextureUser().
uiBut* uiDefPulldownBut (uiBlock * block, uiBlockCreateFunc func, void * arg, const char * str, int x1, int y1, short x2, short y2, const char * tip)
Definition at line 3514 of file interface.c.
References uiBut::block_create_func, PULLDOWN, ui_check_but(), and ui_def_but().
uiBut* uiDefSearchBut (uiBlock * block, void * arg, int retval, int icon, int maxlen, int x1, int y1, short x2, short y2, float a1, float a2, const char * tip)
Definition at line 3615 of file interface.c.
References uiBut::flag, uiBut::icon, SEARCH_MENU, ui_check_but(), ui_def_but(), UI_HAS_ICON, UI_ICON_LEFT, and UI_TEXT_LEFT.
Referenced by id_search_menu(), operator_search_menu(), tool_search_menu(), uiTemplateOperatorSearch(), wm_block_search_menu(), and wm_enum_search_menu().
void uiDrawBlock (const bContext * C, uiBlock * block)
Definition at line 990 of file interface.c.
References uiBlock::aspect, uiBlock::buttons, CTX_wm_menu(), CTX_wm_region(), uiBlock::endblock, ListBase::first, uiBut::flag, uiBlock::flag, uiStyle::grouplabel, uiBut::next, NULL, uiBlock::panel, uiStyle::paneltitle, uiFontStyle::points, UI_BLOCK_LOOP, ui_but_to_pixelrect(), ui_draw_aligned_panel(), ui_draw_but(), ui_draw_links(), ui_draw_menu_back(), ui_fontscale(), UI_GetStyle(), UI_HIDDEN, UI_SCROLLED, uiEndBlock(), uiStyle::widget, uiStyle::widgetlabel, ARegion::winx, ARegion::winy, wmOrtho2(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
void uiEndBlock (const bContext * C, uiBlock * block)
Definition at line 888 of file interface.c.
References uiBlock::auto_open, uiBlock::auto_open_last, uiBlock::buttons, RenderData::cfra, uiBut::context, CTX_data_scene(), CTX_store_set(), uiBlock::dobounds, uiBlock::endblock, ListBase::first, uiBlock::flag, uiBut::flag, uiBlock::layouts, uiBut::lock, uiBlock::maxx, uiBlock::minx, uiBut::next, NULL, uiBlock::oldblock, uiBut::opcontext, uiBut::optype, Scene::r, uiBlock::tooltipdisabled, UI_BLOCK_BOUNDS, UI_BLOCK_BOUNDS_POPUP_CENTER, UI_BLOCK_BOUNDS_TEXT, ui_block_do_align(), UI_BLOCK_LOOP, UI_BLOCK_NUMSELECT, ui_bounds_block(), UI_BUT_ALIGN, ui_but_anim_flag(), UI_BUT_DISABLED, ui_but_update_from_old_block(), ui_centered_bounds_block(), ui_check_but(), ui_menu_block_set_keyaccels(), ui_menu_block_set_keymaps(), ui_popup_bounds_block(), ui_text_bounds_block(), uiBlockEndAlign(), uiBlockLayoutResolve(), uiBoundsBlock(), and WM_operator_poll_context().
void uiExplicitBoundsBlock (uiBlock * block, int minx, int miny, int maxx, int maxy)
Definition at line 437 of file interface.c.
References uiBlock::dobounds, uiBlock::maxx, uiBlock::maxy, uiBlock::minx, and uiBlock::miny.
Referenced by node_update_basis(), node_update_group(), and node_update_hidden().
uiBut* uiFindInlink (uiBlock * block, void * poin)
Definition at line 1151 of file interface.c.
References ui_find_inlink().
Referenced by is_sensor_linked().
void uiFreeBlock (const bContext * C, uiBlock * block)
Definition at line 2006 of file interface.c.
References BLI_freelistN(), BLI_remlink(), uiBlock::buttons, uiBlock::contexts, CTX_store_free_list(), ListBase::first, uiBlock::func_argN, MEM_freeN(), uiBlock::saferct, ui_free_but(), and uiBlock::unit.
void uiFreeBlocks (const bContext * C, ListBase * lb)
Definition at line 2031 of file interface.c.
References BLI_remlink(), ListBase::first, and uiFreeBlock().
void uiFreeInactiveBlocks (const bContext * C, ListBase * lb)
Definition at line 2041 of file interface.c.
References uiBlock::active, BLI_remlink(), ListBase::first, uiBlock::handle, uiBlock::next, and uiFreeBlock().
uiBlock* uiGetBlock (const char * name, ARegion * ar)
Definition at line 2133 of file interface.c.
References BLI_findstring(), and ARegion::uiblocks.
void uiMenuPopupBoundsBlock (uiBlock * block, int addval, int mx, int my)
Definition at line 422 of file interface.c.
References uiBlock::bounds, uiBlock::dobounds, uiBlock::mx, uiBlock::my, and UI_BLOCK_BOUNDS_POPUP_MENU.
Referenced by ui_block_func_POPUP().
void uiPopupBoundsBlock (uiBlock * block, int addval, int mx, int my)
Definition at line 413 of file interface.c.
References uiBlock::bounds, uiBlock::dobounds, uiBlock::mx, uiBlock::my, and UI_BLOCK_BOUNDS_POPUP_MOUSE.
Referenced by menu_add_shortcut(), menu_change_shortcut(), wm_block_create_redo(), wm_block_dialog_create(), wm_block_search_menu(), wm_enum_search_menu(), and wm_operator_ui_create().
void uiSetButLink (uiBut * but, void ** poin, void *** ppoin, short * tot, int from, int to)
Definition at line 3243 of file interface.c.
References uiLink::fromcode, link(), uiBut::link, MEM_callocN(), uiLink::poin, uiLink::ppoin, uiLink::tocode, and uiLink::totlink.
Referenced by logic_buttons(), logic_buttons_new(), and ui_add_smart_controller().
void uiTextBoundsBlock (uiBlock * block, int addval)
Definition at line 406 of file interface.c.
References uiBlock::bounds, uiBlock::dobounds, and UI_BLOCK_BOUNDS_TEXT.
Referenced by curvemap_brush_tools_func(), curvemap_tools_func(), and ui_block_func_POPUP().