Blender: imageprocess.c File Reference
imageprocess.c File Reference
IMage Buffer
#include <stdlib.h>
#include "BLI_utildefines.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include <math.h>
Defines
#define MAX2(x, y) ((x)>(y) ? (x) : (y))
Functions
void IMB_convert_rgba_to_abgr (struct ImBuf *ibuf)
static void pixel_from_buffer (struct ImBuf *ibuf, unsigned char **outI, float **outF, int x, int y)
static float P (float k)
void bicubic_interpolation_color (struct ImBuf *in, unsigned char *outI, float *outF, float u, float v)
void bicubic_interpolation (ImBuf *in, ImBuf *out, float u, float v, int xout, int yout)
void bilinear_interpolation_color (struct ImBuf *in, unsigned char *outI, float *outF, float u, float v)
void bilinear_interpolation_color_wrap (struct ImBuf *in, unsigned char *outI, float *outF, float u, float v)
void bilinear_interpolation (ImBuf *in, ImBuf *out, float u, float v, int xout, int yout)
void neareast_interpolation_color (struct ImBuf *in, unsigned char *outI, float *outF, float u, float v)
void neareast_interpolation (ImBuf *in, ImBuf *out, float x, float y, int xout, int yout)
Detailed Description
Definition in file imageprocess.c.
Define Documentation
#define MAX2 (x, y) ((x)>(y) ? (x) : (y))
Definition at line 53 of file imageprocess.c.
Referenced by P().
Function Documentation
void bicubic_interpolation (struct ImBuf * in, struct ImBuf * out, float u, float v, int xout, int yout)
Attention:
defined in imageprocess.c
Definition at line 231 of file imageprocess.c.
References bicubic_interpolation_color(), NULL, pixel_from_buffer(), ImBuf::rect, and ImBuf::rect_float.
Referenced by BKE_tracking_stabilize(), node_composit_exec_rotate(), node_composit_transform(), scale_trackpreview_ibuf(), and transform_image().
void bicubic_interpolation_color (struct ImBuf * in, unsigned char * outI, float * outF, float u, float v)
Definition at line 132 of file imageprocess.c.
References CLAMP(), i, P(), ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by bicubic_interpolation(), and do_projectpaint_thread().
void bilinear_interpolation (ImBuf * in, ImBuf * out, float u, float v, int xout, int yout)
Definition at line 383 of file imageprocess.c.
References bilinear_interpolation_color(), NULL, pixel_from_buffer(), ImBuf::rect, and ImBuf::rect_float.
Referenced by BKE_tracking_stabilize(), node_composit_exec_rotate(), node_composit_transform(), and transform_image().
void bilinear_interpolation_color (struct ImBuf * in, unsigned char * outI, float * outF, float u, float v)
Definition at line 246 of file imageprocess.c.
References floorf, if(), ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by bilinear_interpolation().
void bilinear_interpolation_color_wrap (struct ImBuf * in, unsigned char * outI, float * outF, float u, float v)
Definition at line 322 of file imageprocess.c.
References floorf, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by project_face_pixel(), and project_paint_PickColor().
void IMB_convert_rgba_to_abgr (struct ImBuf * ibuf)
Change the ordering of the color bytes pointed to by rect from rgba to abgr. size * 4 color bytes are reordered.
Attention:
Defined in imageprocess.c
Definition at line 56 of file imageprocess.c.
References if(), ImBuf::rect, ImBuf::rect_float, size(), ImBuf::x, and ImBuf::y.
Referenced by do_paintface_box_select(), do_paintvert_box_select(), do_plugin_effect(), IMB_anim_absolute(), imb_cocoaLoadImage(), imb_loadiris(), imb_loadtarga(), imb_read_tiff_pixels(), imb_saveiris(), index_rebuild_fallback(), and view3d_read_backbuf().
void neareast_interpolation (ImBuf * in, ImBuf * out, float x, float y, int xout, int yout)
Definition at line 445 of file imageprocess.c.
References neareast_interpolation_color(), NULL, pixel_from_buffer(), ImBuf::rect, and ImBuf::rect_float.
Referenced by BKE_tracking_stabilize(), node_composit_exec_rotate(), node_composit_transform(), and transform_image().
void neareast_interpolation_color (struct ImBuf * in, unsigned char * outI, float * outF, float u, float v)
Definition at line 398 of file imageprocess.c.
References if(), ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by neareast_interpolation().
static float P (float k) [static]
Definition at line 113 of file imageprocess.c.
References MAX2.
Referenced by EdgeDice::add_vert(), bicubic_interpolation_color(), bvh_triangle_refine(), QuadDice::eval_projected(), kernel_shader_evaluate(), mbvh_triangle_intersect(), DiagSplit::project(), QuadDice::scale_factor(), scene_intersect(), shader_setup_from_displace(), shader_setup_from_sample(), DiagSplit::T(), xml_read_mesh(), and xml_read_patch().
static void pixel_from_buffer (struct ImBuf * ibuf, unsigned char ** outI, float ** outF, int x, int y) [static]
Definition at line 90 of file imageprocess.c.
References if(), ImBuf::rect, ImBuf::rect_float, and ImBuf::x.
Referenced by bicubic_interpolation(), bilinear_interpolation(), and neareast_interpolation().