Blender: CTR_List Class Reference
CTR_List Class Reference
#include <CTR_List.h>
Public Member Functions
CTR_List ()
CTR_Link * getHead () const
CTR_Link * getTail () const
void addHead (CTR_Link *link)
void addTail (CTR_Link *link)
Detailed Description
Definition at line 82 of file CTR_List.h.
Constructor & Destructor Documentation
CTR_List::CTR_List ()
Definition at line 114 of file CTR_List.cpp.
Member Function Documentation
void CTR_List::addHead (CTR_Link * link)
Definition at line 137 of file CTR_List.cpp.
References CTR_Link::insertAfter().
void CTR_List::addTail (CTR_Link * link)
Definition at line 145 of file CTR_List.cpp.
References CTR_Link::insertBefore().
CTR_Link * CTR_List::getHead () const
Definition at line 123 of file CTR_List.cpp.
References CTR_Link::getNext().
CTR_Link * CTR_List::getTail () const
Definition at line 130 of file CTR_List.cpp.
References CTR_Link::getPrev().
The documentation for this class was generated from the following files:
CTR_List.h
CTR_List.cpp