Blender: BKE_font.h File Reference
BKE_font.h File Reference
blenkernel
#include <wchar.h>
Classes
struct chartrans
struct SelBox
struct EditFont
Typedefs
typedef struct SelBox SelBox
typedef struct EditFont EditFont
Functions
void BKE_font_register_builtin (void *mem, int size)
void free_vfont (struct VFont *sc)
void free_ttfont (void)
struct VFont * get_builtin_font (void)
struct VFont * load_vfont (struct Main *bmain, const char *name)
struct TmpFont * vfont_find_tmpfont (struct VFont *vfont)
struct chartrans * BKE_text_to_curve (struct Main *bmain, struct Scene *scene, struct Object *ob, int mode)
int BKE_font_getselection (struct Object *ob, int *start, int *end)
Detailed Description
Definition in file BKE_font.h.
Typedef Documentation
typedef struct EditFont EditFont
typedef struct SelBox SelBox
Function Documentation
int BKE_font_getselection (struct Object * ob, int * start, int * end)
Definition at line 493 of file font.c.
References Object::data, Curve::editfont, NULL, OB_FONT, Curve::selend, Curve::selstart, and Object::type.
Referenced by BKE_text_to_curve(), copy_selection(), cut_text_exec(), delete_exec(), draw_object(), kill_selection(), material_slot_assign_exec(), set_style(), and toggle_style_exec().
void BKE_font_register_builtin (void * mem, int size)
Definition at line 97 of file font.c.
References builtin_font_data, builtin_font_size, and size().
Referenced by main().
struct chartrans* BKE_text_to_curve (struct Main * bmain, struct Scene * scene, struct Object * ob, int mode) [read]
Definition at line 526 of file font.c.
References KDL::atan2(), BKE_font_getselection(), BLI_strlen_utf8(), BLI_strncpy_wchar_from_utf8(), BLI_vfontchar_from_freetypefont(), build_underline(), buildchar(), ceilf, char_width(), CLAMP(), co, copy_m3_m4(), cos(), CU_CHINFO_SMALLCAPS, CU_CHINFO_SMALLCAPS_CHECK, CU_CHINFO_UNDERLINE, CU_CHINFO_WRAP, CU_FLUSH, CU_FOLLOW, CU_JUSTIFY, CU_LEFT, CU_MIDDLE, CU_PATH, CU_RIGHT, Object::data, chartrans::dobreak, Curve::editfont, ELEM3, find_vfont_char(), Curve::flag, CharInfo::flag, FO_BUILTIN_NAME, FO_CURSDOWN, FO_CURSUP, FO_DUPLI, FO_EDIT, FO_PAGEDOWN, FO_PAGEUP, FO_SELCHANGE, freeNurblist(), Curve::fsize, SelBox::h, TextBox::h, i, if(), invert_m4_m4(), CharInfo::kern, Curve::len, Curve::linedist, Curve::lines, Object::loc, M_PI, makeDispListCurveTypes(), CharInfo::mat_nr, MAX2, MAXTEXTBOX, MEM_callocN(), MEM_freeN(), MEM_mallocN(), mul_m3_m3m3(), mul_v3_fl(), mul_v3_m4v3(), VFont::name, normalize_v3(), NULL, Curve::nurb, OB_CURVE, OB_FONT, Object::obmat, Curve::path, Curve::pos, Curve::selboxes, Curve::sepchar, si, sin(), Curve::spacemode, Curve::spacing, Curve::str, Curve::strinfo, Curve::tb, EditFont::textbufinfo, EditFont::textcurs, Curve::textoncurve, Curve::totbox, Object::totcol, Path::totdist, Object::type, Curve::ulheight, Curve::ulpos, Curve::vfont, vfont_get_data(), SelBox::w, TextBox::w, where_on_path(), which_vfont(), Curve::wordspace, SelBox::x, TextBox::x, Curve::xof, chartrans::xof, SelBox::y, TextBox::y, Curve::yof, and chartrans::yof.
Referenced by copy_attr(), do_makeDispListCurveTypes(), font_duplilist(), move_cursor(), and text_update_edited().
void free_ttfont (void)
Definition at line 119 of file font.c.
References BLI_freelistN(), ListBase::first, freePackedFile(), TmpFont::next, NULL, TmpFont::pf, and TmpFont::vfont.
Referenced by WM_exit_ext(), and WM_read_homefile().
void free_vfont (struct VFont * sc)
Definition at line 66 of file font.c.
References Nurb::bezt, BLI_freelinkN(), VFontData::characters, VFont::data, ListBase::first, freePackedFile(), MEM_freeN(), NULL, VChar::nurbsbase, and VFont::packedfile.
Referenced by free_libblock().
struct VFont* get_builtin_font (void) [read]
Definition at line 295 of file font.c.
References FO_BUILTIN_NAME, G, VFont::id, load_vfont(), VFont::name, and ID::next.
Referenced by add_curve(), font_unlink_exec(), and txt_add_object().
struct VFont* load_vfont (struct Main * bmain, const char * name) [read]
Definition at line 215 of file font.c.
References alloc_libblock(), BLI_addtail(), BLI_splitdirstring(), BLI_strncpy(), BLI_vfontdata_from_freetypefont(), VFont::data, FILE_MAXDIR, FILE_MAXFILE, FO_BUILTIN_NAME, freePackedFile(), G, G_AUTOPACK, get_builtin_packedfile(), VFont::id, ID_VF, MEM_callocN(), VFont::name, ID::name, VFontData::name, Main::name, newPackedFile(), NULL, VFont::packedfile, TmpFont::pf, pf, Main::vfont, and TmpFont::vfont.
Referenced by font_open_exec(), and get_builtin_font().
struct TmpFont* vfont_find_tmpfont (struct VFont * vfont) [read]
Definition at line 131 of file font.c.
References ListBase::first, TmpFont::next, NULL, and TmpFont::vfont.
Referenced by objchr_to_ftvfontdata(), and vfont_get_data().