Blender: SupportVertexCallback Class Reference
SupportVertexCallback Class Reference
Public Member Functions
SupportVertexCallback (const btVector3 &supportVecWorld, const btTransform &trans)
virtual void processTriangle (btVector3 *triangle, int partId, int triangleIndex)
btVector3 GetSupportVertexWorldSpace ()
btVector3 GetSupportVertexLocal ()
Public Attributes
btTransform m_worldTrans
btScalar m_maxDot
btVector3 m_supportVecLocal
Detailed Description
Definition at line 83 of file btTriangleMeshShape.cpp.
Constructor & Destructor Documentation
SupportVertexCallback::SupportVertexCallback (const btVector3 & supportVecWorld, const btTransform & trans) [inline]
Definition at line 93 of file btTriangleMeshShape.cpp.
References btTransform::getBasis(), m_supportVecLocal, and m_worldTrans.
Member Function Documentation
btVector3 SupportVertexCallback::GetSupportVertexLocal () [inline]
Definition at line 120 of file btTriangleMeshShape.cpp.
Referenced by btTriangleMeshShape::localGetSupportingVertex().
btVector3 SupportVertexCallback::GetSupportVertexWorldSpace () [inline]
Definition at line 115 of file btTriangleMeshShape.cpp.
References m_worldTrans.
virtual void SupportVertexCallback::processTriangle (btVector3 * triangle, int partId, int triangleIndex) [inline, virtual]
Implements btTriangleCallback.
Definition at line 100 of file btTriangleMeshShape.cpp.
References dot(), i, m_maxDot, and m_supportVecLocal.
Member Data Documentation
btScalar SupportVertexCallback::m_maxDot
Definition at line 90 of file btTriangleMeshShape.cpp.
Referenced by processTriangle().
btVector3 SupportVertexCallback::m_supportVecLocal
Definition at line 91 of file btTriangleMeshShape.cpp.
Referenced by processTriangle(), and SupportVertexCallback().
btTransform SupportVertexCallback::m_worldTrans
Definition at line 89 of file btTriangleMeshShape.cpp.
Referenced by GetSupportVertexWorldSpace(), and SupportVertexCallback().
The documentation for this class was generated from the following file:
btTriangleMeshShape.cpp