Blender: BKE_sound.h File Reference
BKE_sound.h File Reference
blenkernel
Classes
struct SoundWaveform
Defines
#define SOUND_WAVE_SAMPLES_PER_SECOND 250
Typedefs
typedef struct SoundWaveform SoundWaveform
Functions
void sound_init_once (void)
void sound_init (struct Main *main)
void sound_init_main (struct Main *bmain)
void sound_exit (void)
void sound_force_device (int device)
int sound_define_from_str (const char *str)
struct bSound * sound_new_file (struct Main *main, const char *filename)
void sound_delete (struct Main *bmain, struct bSound *sound)
void sound_cache (struct bSound *sound)
void sound_cache_notifying (struct Main *main, struct bSound *sound)
void sound_delete_cache (struct bSound *sound)
void sound_load (struct Main *main, struct bSound *sound)
void sound_free (struct bSound *sound)
void sound_create_scene (struct Scene *scene)
void sound_destroy_scene (struct Scene *scene)
void sound_mute_scene (struct Scene *scene, int muted)
void sound_update_fps (struct Scene *scene)
void sound_update_scene_listener (struct Scene *scene)
void * sound_scene_add_scene_sound (struct Scene *scene, struct Sequence *sequence, int startframe, int endframe, int frameskip)
void * sound_scene_add_scene_sound_defaults (struct Scene *scene, struct Sequence *sequence)
void * sound_add_scene_sound (struct Scene *scene, struct Sequence *sequence, int startframe, int endframe, int frameskip)
void * sound_add_scene_sound_defaults (struct Scene *scene, struct Sequence *sequence)
void sound_remove_scene_sound (struct Scene *scene, void *handle)
void sound_mute_scene_sound (void *handle, char mute)
void sound_move_scene_sound (struct Scene *scene, void *handle, int startframe, int endframe, int frameskip)
void sound_move_scene_sound_defaults (struct Scene *scene, struct Sequence *sequence)
void sound_update_scene_sound (void *handle, struct bSound *sound)
void sound_set_cfra (int cfra)
void sound_set_scene_volume (struct Scene *scene, float volume)
void sound_set_scene_sound_volume (void *handle, float volume, char animated)
void sound_set_scene_sound_pitch (void *handle, float pitch, char animated)
void sound_set_scene_sound_pan (void *handle, float pan, char animated)
void sound_update_sequencer (struct Main *main, struct bSound *sound)
void sound_play_scene (struct Scene *scene)
void sound_stop_scene (struct Scene *scene)
void sound_seek_scene (struct Main *bmain, struct Scene *scene)
float sound_sync_scene (struct Scene *scene)
int sound_scene_playing (struct Scene *scene)
void sound_free_waveform (struct bSound *sound)
void sound_read_waveform (struct bSound *sound)
void sound_update_scene (struct Scene *scene)
void * sound_get_factory (void *sound)
Detailed Description
Since:
March 2001
Author:
nzc
Definition in file BKE_sound.h.
Define Documentation
#define SOUND_WAVE_SAMPLES_PER_SECOND 250
Definition at line 36 of file BKE_sound.h.
Referenced by drawseqwave().
Typedef Documentation
typedef struct SoundWaveform SoundWaveform
Function Documentation
void* sound_add_scene_sound (struct Scene * scene, struct Sequence * sequence, int startframe, int endframe, int frameskip)
void* sound_add_scene_sound_defaults (struct Scene * scene, struct Sequence * sequence)
Referenced by lib_link_scene(), seq_dupli(), seq_paste_add_sound(), seq_sound_init(), and sequencer_swap_data_exec().
void sound_cache (struct bSound * sound)
Referenced by seq_load_apply().
void sound_cache_notifying (struct Main * main, struct bSound * sound)
void sound_create_scene (struct Scene * scene)
Referenced by add_scene(), copy_scene(), and direct_link_scene().
int sound_define_from_str (const char * str)
Referenced by set_audio().
void sound_delete (struct Main * bmain, struct bSound * sound)
void sound_delete_cache (struct bSound * sound)
void sound_destroy_scene (struct Scene * scene)
Referenced by free_scene().
void sound_exit (void)
Definition at line 797 of file sound.c.
Referenced by GPG_Application::exitEngine(), GPG_Application::initEngine(), WM_exit_ext(), and WM_init_game().
void sound_force_device (int device)
Referenced by no_audio(), and set_audio().
void sound_free (struct bSound * sound)
Definition at line 107 of file sound.c.
References AUD_unload(), bSound::cache, freePackedFile(), bSound::handle, NULL, bSound::packedfile, bSound::playback_handle, and sound_free_waveform().
Referenced by free_libblock().
void sound_free_waveform (struct bSound * sound)
Referenced by sound_free().
void* sound_get_factory (void * sound)
void sound_init (struct Main * main)
Referenced by GPG_Application::initEngine(), and wm_init_userdef().
void sound_init_main (struct Main * bmain)
Definition at line 819 of file sound.c.
Referenced by setup_app_data().
void sound_init_once (void)
Definition at line 795 of file sound.c.
Referenced by main().
void sound_load (struct Main * main, struct bSound * sound)
Referenced by lib_link_sound(), sound_new_file(), sound_pack_exec(), and unpackSound().
void sound_move_scene_sound (struct Scene * scene, void * handle, int startframe, int endframe, int frameskip)
Referenced by seq_update_sound_bounds_recursive().
void sound_move_scene_sound_defaults (struct Scene * scene, struct Sequence * sequence)
Referenced by seq_update_sound_bounds().
void sound_mute_scene (struct Scene * scene, int muted)
void sound_mute_scene_sound (void * handle, char mute)
Referenced by seq_update_muting_recursive().
struct bSound* sound_new_file (struct Main * main, const char * filename) [read]
Definition at line 73 of file sound.c.
References alloc_libblock(), BLI_path_abs(), BLI_strncpy(), FILE_MAX, free_libblock(), G, ID_SO, len(), bSound::name, NULL, bSound::playback_handle, Main::sound, sound_load(), str, and strlen().
Referenced by do_versions().
void sound_play_scene (struct Scene * scene)
Referenced by ED_screen_animation_play().
void sound_read_waveform (struct bSound * sound)
Definition at line 818 of file sound.c.
Referenced by drawseqwave().
void sound_remove_scene_sound (struct Scene * scene, void * handle)
Referenced by seq_copy_del_sound(), seq_free_sequence(), and sequencer_swap_data_exec().
void* sound_scene_add_scene_sound (struct Scene * scene, struct Sequence * sequence, int startframe, int endframe, int frameskip)
Referenced by sequencer_add_scene_strip_exec().
void* sound_scene_add_scene_sound_defaults (struct Scene * scene, struct Sequence * sequence)
Referenced by lib_link_scene(), seq_dupli(), and seq_sound_init().
int sound_scene_playing (struct Scene * scene)
Referenced by wm_event_do_handlers().
void sound_seek_scene (struct Main * bmain, struct Scene * scene)
Referenced by change_frame_apply(), frame_jump_exec(), frame_offset_exec(), graphview_cursor_apply(), keyframe_jump_exec(), and screen_animation_step().
void sound_set_cfra (int cfra)
Definition at line 820 of file sound.c.
Referenced by scene_update_for_newframe().
void sound_set_scene_sound_pan (void * handle, float pan, char animated)
Definition at line 827 of file sound.c.
void sound_set_scene_sound_pitch (void * handle, float pitch, char animated)
Definition at line 829 of file sound.c.
void sound_set_scene_sound_volume (void * handle, float volume, char animated)
Definition at line 826 of file sound.c.
void sound_set_scene_volume (struct Scene * scene, float volume)
Definition at line 828 of file sound.c.
void sound_stop_scene (struct Scene * scene)
Referenced by ED_screen_animation_play().
float sound_sync_scene (struct Scene * scene)
Referenced by screen_animation_step(), and wm_event_do_handlers().
void sound_update_fps (struct Scene * scene)
Definition at line 825 of file sound.c.
void sound_update_scene (struct Scene * scene)
Definition at line 822 of file sound.c.
Referenced by scene_update_tagged_recursive().
void sound_update_scene_listener (struct Scene * scene)
Definition at line 824 of file sound.c.
void sound_update_scene_sound (void * handle, struct bSound * sound)
Definition at line 823 of file sound.c.
Referenced by seq_update_sound_recursive().
void sound_update_sequencer (struct Main * main, struct bSound * sound)
Definition at line 821 of file sound.c.