Blender: MOD_solidify.c File Reference
MOD_solidify.c File Reference
modifiers
#include "DNA_meshdata_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "BLI_edgehash.h"
#include "BLI_array.h"
#include "BLI_string.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_mesh.h"
#include "BKE_particle.h"
#include "BKE_deform.h"
#include "MOD_modifiertypes.h"
#include "MOD_util.h"
Classes
struct EdgeFaceRef
Defines
#define NOCALC_EDGEWEIGHT_ADD_EDGEREF_FACE(EDV1, EDV2)
#define INVALID_UNUSED -1
#define INVALID_PAIR -2
#define ADD_EDGE_USER(_v1, _v2, edge_ord)
#define SOLIDIFY_SIDE_NORMALS
Typedefs
typedef struct EdgeFaceRef EdgeFaceRef
Functions
static void dm_calc_normal (DerivedMesh *dm, float(*temp_nors)[3])
static void initData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static CustomDataMask requiredDataMask (Object *UNUSED(ob), ModifierData *md)
static DerivedMesh * applyModifier (ModifierData *md, Object *ob, DerivedMesh *dm, int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
static DerivedMesh * applyModifierEM (ModifierData *md, Object *ob, struct BMEditMesh *UNUSED(editData), DerivedMesh *derivedData)
Variables
ModifierTypeInfo modifierType_Solidify
Detailed Description
Definition in file MOD_solidify.c.
Define Documentation
#define ADD_EDGE_USER (_v1, _v2, edge_ord)
Value:
{ \
            const unsigned int ml_v1 = _v1; \
            const unsigned int ml_v2 = _v2; \
            eidx= GET_INT_FROM_POINTER(BLI_edgehash_lookup(edgehash, ml_v1, ml_v2)); \
            if (edge_users[eidx] == INVALID_UNUSED) { \
                ed= orig_medge + eidx; \
                edge_users[eidx] = (ml_v1 < ml_v2) == (ed->v1 < ed->v2) ? i : (i + numFaces); \
                edge_order[eidx] = edge_ord; \
            } \
            else { \
                edge_users[eidx] = INVALID_PAIR; \
            } \
        }
Referenced by applyModifier().
#define INVALID_PAIR -2
#define INVALID_UNUSED -1
Referenced by applyModifier().
#define NOCALC_EDGEWEIGHT_ADD_EDGEREF_FACE (EDV1, EDV2)
Value:
; \
            { \
                const unsigned int ml_v1 = EDV1; \
                const unsigned int ml_v2 = EDV2; \
                edge_ref = (EdgeFaceRef *)BLI_edgehash_lookup(edge_hash, ml_v1, ml_v2); \
                if (!edge_ref) { \
                    edge_ref = &edge_ref_array[edge_ref_count]; edge_ref_count++; \
                    edge_ref->f1 = i; \
                    edge_ref->f2 =- 1; \
                    BLI_edgehash_insert(edge_hash, ml_v1, ml_v2, edge_ref); \
                } \
                else { \
                    edge_ref->f2 = i; \
                } \
            }
Referenced by dm_calc_normal().
#define SOLIDIFY_SIDE_NORMALS
Typedef Documentation
typedef struct EdgeFaceRef EdgeFaceRef
Function Documentation
static DerivedMesh* applyModifier (ModifierData * md, Object * ob, DerivedMesh * dm, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 202 of file MOD_solidify.c.
References ADD_EDGE_USER, add_v3_v3(), angle(), angle_normalized_v3v3(), BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_staticdeclare, BLI_edgehash_free(), BLI_edgehash_insert(), BLI_edgehash_new(), BLI_edgehashIterator_free(), BLI_edgehashIterator_getKey(), BLI_edgehashIterator_getValue(), BLI_edgehashIterator_isDone(), BLI_edgehashIterator_new(), BLI_edgehashIterator_step(), CD_CALLOC, CD_NORMAL, CD_ORIGINDEX, CDDM_calc_normals(), CDDM_from_template(), CDDM_get_edges(), CDDM_get_loops(), CDDM_get_polys(), CDDM_get_verts(), CLAMP(), MVert::co, co, copy_v3_v3(), MEdge::crease, SolidifyModifierData::crease_inner, SolidifyModifierData::crease_outer, SolidifyModifierData::crease_rim, CustomData_add_layer(), CustomData_copy_data(), CustomData_get_layer(), SolidifyModifierData::defgrp_name, defvert_find_weight(), dm_calc_normal(), DM_copy_edge_data(), DM_copy_loop_data(), DM_copy_poly_data(), DM_copy_vert_data(), DM_get_poly_data_layer(), MLoop::e, fill_vn_i(), MEdge::flag, SolidifyModifierData::flag, MVert::flag, MPoly::flag, GET_INT_FROM_POINTER, DerivedMesh::getEdgeArray, DerivedMesh::getEdgeDataArray, DerivedMesh::getLoopArray, DerivedMesh::getNumEdges, DerivedMesh::getNumPolys, DerivedMesh::getNumVerts, DerivedMesh::getPolyArray, DerivedMesh::getVertArray, i, INVALID_UNUSED, DerivedMesh::loopData, MPoly::loopstart, M_PI, madd_v3_v3fl(), MPoly::mat_nr, SolidifyModifierData::mat_ofs, SolidifyModifierData::mat_ofs_rim, ME_EDGEDRAW, ME_POLY_LOOP_NEXT, ME_POLY_LOOP_PREV, ME_VERT_TMP_TAG, MEM_callocN(), MEM_freeN(), MEM_mallocN(), mesh_calc_poly_normal(), MOD_SOLIDIFY_EVEN, MOD_SOLIDIFY_NORMAL_CALC, MOD_SOLIDIFY_RIM, MOD_SOLIDIFY_VGROUP_INV, modifier_get_vgroup(), negate_v3_v3(), MVert::no, normal_float_to_short_v3(), normal_quad_v3(), normal_short_to_float_v3(), normalize_v3(), normalize_v3_v3(), NULL, DerivedMesh::numLoopData, DerivedMesh::numPolyData, SolidifyModifierData::offset, SolidifyModifierData::offset_fac, SolidifyModifierData::offset_fac_vg, ORIGINDEX_NONE, DerivedMesh::polyData, SET_INT_IN_POINTER, shell_angle_to_dist(), sub_v3_v3v3(), Object::totcol, MPoly::totloop, MLoop::v, MEdge::v1, MEdge::v2, and VECADDFAC.
Referenced by applyModifierEM().
static DerivedMesh* applyModifierEM (ModifierData * md, Object * ob, struct BMEditMesh * UNUSEDeditData, DerivedMesh * derivedData) [static]
Definition at line 728 of file MOD_solidify.c.
References applyModifier().
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 177 of file MOD_solidify.c.
References BLI_strncpy(), SolidifyModifierData::crease_inner, SolidifyModifierData::crease_outer, SolidifyModifierData::crease_rim, SolidifyModifierData::defgrp_name, SolidifyModifierData::flag, SolidifyModifierData::offset, and SolidifyModifierData::offset_fac.
static void dm_calc_normal (DerivedMesh * dm, float(*) temp_nors[3]) [static]
Definition at line 60 of file MOD_solidify.c.
References add_v3_v3(), add_v3_v3v3(), angle_normalized_v3v3(), BLI_edgehash_free(), BLI_edgehash_new(), BLI_edgehashIterator_free(), BLI_edgehashIterator_getKey(), BLI_edgehashIterator_getValue(), BLI_edgehashIterator_isDone(), BLI_edgehashIterator_new(), BLI_edgehashIterator_step(), CD_CALLOC, CD_MVERT, CD_NORMAL, CustomData_add_layer(), CustomData_duplicate_referenced_layer(), CustomData_get_layer(), EdgeFaceRef::f1, EdgeFaceRef::f2, DerivedMesh::getLoopArray, DerivedMesh::getNumEdges, DerivedMesh::getNumPolys, DerivedMesh::getNumVerts, DerivedMesh::getPolyArray, DerivedMesh::getVertArray, i, MPoly::loopstart, M_PI, ME_POLY_LOOP_NEXT, MEM_callocN(), MEM_freeN(), mesh_calc_poly_normal(), mul_v3_fl(), mul_v3_v3fl(), MVert::no, NOCALC_EDGEWEIGHT_ADD_EDGEREF_FACE, normal_short_to_float_v3(), normalize_v3(), NULL, DerivedMesh::polyData, MPoly::totloop, MLoop::v, and DerivedMesh::vertData.
Referenced by applyModifier().
static void initData (ModifierData * md) [static]
Definition at line 169 of file MOD_solidify.c.
References SolidifyModifierData::flag, MOD_SOLIDIFY_RIM, SolidifyModifierData::offset, and SolidifyModifierData::offset_fac.
static CustomDataMask requiredDataMask (Object * UNUSEDob, ModifierData * md) [static]
Definition at line 190 of file MOD_solidify.c.
References CD_MASK_MDEFORMVERT, and SolidifyModifierData::defgrp_name.
Variable Documentation
ModifierTypeInfo modifierType_Solidify
Initial value:
 {
                  "Solidify",
            "SolidifyModifierData",
            sizeof(SolidifyModifierData),
                  eModifierTypeType_Constructive,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_AcceptsCVs
                            | eModifierTypeFlag_SupportsMapping
                            | eModifierTypeFlag_SupportsEditmode
                            | eModifierTypeFlag_EnableInEditmode,
              copyData,
           NULL,
        NULL,
         NULL,
      NULL,
         applyModifier,
       applyModifierEM,
              initData,
      requiredDataMask,
              NULL,
            NULL,
        NULL,
         NULL,
        NULL,
     NULL,
         NULL,
        NULL,
}
Definition at line 737 of file MOD_solidify.c.