Blender: GHOST_ITimerTask Class Reference
GHOST_ITimerTask Class Reference
#include <GHOST_ITimerTask.h>
Public Member Functions
virtual ~GHOST_ITimerTask ()
virtual GHOST_TimerProcPtr getTimerProc () const =0
virtual void setTimerProc (const GHOST_TimerProcPtr timerProc)=0
virtual GHOST_TUserDataPtr getUserData () const =0
virtual void setUserData (const GHOST_TUserDataPtr userData)=0
Detailed Description
Interface for a timer task. Timer tasks are created by the system and can be installed by the system. After installation, the timer callback-procedure or "timerProc" will be called periodically. You should not need to inherit this class. It is passed to the application in the timer-callback.
Note that GHOST processes timers in the UI thread. You should ask GHOST process messages in order for the timer-callbacks to be called.
See also:
GHOST_ISystem::installTimer
GHOST_TimerProcPtr
Author:
Maarten Gribnau
Date:
May 31, 2001
Definition at line 53 of file GHOST_ITimerTask.h.
Constructor & Destructor Documentation
virtual GHOST_ITimerTask::~GHOST_ITimerTask () [inline, virtual]
Destructor.
Definition at line 59 of file GHOST_ITimerTask.h.
Member Function Documentation
virtual GHOST_TimerProcPtr GHOST_ITimerTask::getTimerProc () const [pure virtual]
Returns the timer callback.
Returns:
The timer callback.
Implemented in GHOST_TimerTask.
Referenced by GHOST_GetTimerProc().
virtual GHOST_TUserDataPtr GHOST_ITimerTask::getUserData () const [pure virtual]
Returns the timer user data.
Returns:
The timer user data.
Implemented in GHOST_TimerTask.
Referenced by frameTimerProc(), gearsTimerProc(), and GHOST_GetTimerTaskUserData().
virtual void GHOST_ITimerTask::setTimerProc (const GHOST_TimerProcPtr timerProc) [pure virtual]
Changes the timer callback.
Parameters:
timerProc The timer callback.
Implemented in GHOST_TimerTask.
Referenced by GHOST_SetTimerProc().
virtual void GHOST_ITimerTask::setUserData (const GHOST_TUserDataPtr userData) [pure virtual]
Changes the time user data.
Parameters:
data The timer user data.
Implemented in GHOST_TimerTask.
Referenced by GHOST_SetTimerTaskUserData().
The documentation for this class was generated from the following file:
GHOST_ITimerTask.h