Blender: clip_buttons.c File Reference
clip_buttons.c File Reference
#include <string.h>
#include <stdio.h>
#include "MEM_guardedalloc.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BLI_listbase.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_screen.h"
#include "BKE_movieclip.h"
#include "BKE_tracking.h"
#include "ED_clip.h"
#include "ED_gpencil.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
#include "clip_intern.h"
Classes
struct MarkerUpdateCb
Defines
#define B_MARKER_POS 3
#define B_MARKER_OFFSET 4
#define B_MARKER_PAT_DIM 5
#define B_MARKER_SEARCH_POS 6
#define B_MARKER_SEARCH_DIM 7
#define B_MARKER_FLAG 8
Functions
void ED_clip_buttons_register (ARegionType *art)
void uiTemplateMovieClip (uiLayout *layout, bContext *C, PointerRNA *ptr, const char *propname, int compact)
void uiTemplateTrack (uiLayout *layout, PointerRNA *ptr, const char *propname)
static void to_pixel_space (float r[2], float a[2], int width, int height)
static void marker_update_cb (bContext *C, void *arg_cb, void *UNUSED(arg))
static void marker_block_handler (bContext *C, void *arg_cb, int event)
void uiTemplateMarker (uiLayout *layout, PointerRNA *ptr, const char *propname, PointerRNA *userptr, PointerRNA *trackptr, int compact)
Detailed Description
Definition in file clip_buttons.c.
Define Documentation
#define B_MARKER_FLAG 8
Definition at line 172 of file clip_buttons.c.
Referenced by marker_block_handler(), and uiTemplateMarker().
#define B_MARKER_OFFSET 4
Definition at line 168 of file clip_buttons.c.
Referenced by marker_block_handler(), and uiTemplateMarker().
#define B_MARKER_PAT_DIM 5
Definition at line 169 of file clip_buttons.c.
Referenced by marker_block_handler(), and uiTemplateMarker().
#define B_MARKER_POS 3
Definition at line 167 of file clip_buttons.c.
Referenced by marker_block_handler(), and uiTemplateMarker().
#define B_MARKER_SEARCH_DIM 7
Definition at line 171 of file clip_buttons.c.
Referenced by marker_block_handler(), and uiTemplateMarker().
#define B_MARKER_SEARCH_POS 6
Definition at line 170 of file clip_buttons.c.
Referenced by marker_block_handler(), and uiTemplateMarker().
Function Documentation
void ED_clip_buttons_register (ARegionType * art)
Definition at line 66 of file clip_buttons.c.
References BLI_addtail(), PanelType::draw, PanelType::flag, gpencil_panel_standard(), PanelType::idname, PanelType::label, MEM_callocN(), ARegionType::paneltypes, and PNL_DEFAULT_CLOSED.
Referenced by ED_spacetype_clip().
static void marker_block_handler (bContext * C, void * arg_cb, int event) [static]
Definition at line 211 of file clip_buttons.c.
References add_v2_v2v2(), B_MARKER_FLAG, B_MARKER_OFFSET, B_MARKER_PAT_DIM, B_MARKER_POS, B_MARKER_SEARCH_DIM, B_MARKER_SEARCH_POS, BKE_movieclip_get_size(), BKE_tracking_clamp_track(), BKE_tracking_ensure_marker(), CLAMP_PAT_DIM, CLAMP_SEARCH_DIM, CLAMP_SEARCH_POS, MarkerUpdateCb::clip, copy_v2_v2(), DAG_id_tag_update(), FALSE, MovieTrackingMarker::flag, MarkerUpdateCb::framenr, i, MovieClip::id, MarkerUpdateCb::marker_flag, MarkerUpdateCb::marker_pos, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, mul_v2_fl(), NA_EDITED, NC_MOVIECLIP, NC_SPACE, ND_SPACE_VIEW3D, NULL, MovieTrackingTrack::offset, MovieTrackingTrack::pat_max, MovieTrackingTrack::pat_min, MovieTrackingMarker::pos, MovieTrackingTrack::search_max, MovieTrackingTrack::search_min, sub_v2_v2(), sub_v2_v2v2(), MarkerUpdateCb::track, MarkerUpdateCb::track_offset, MarkerUpdateCb::track_pat, MarkerUpdateCb::track_search, MarkerUpdateCb::track_search_pos, TRUE, MarkerUpdateCb::user, and WM_event_add_notifier().
Referenced by uiTemplateMarker().
static void marker_update_cb (bContext * C, void * arg_cb, void * UNUSEDarg) [static]
Definition at line 196 of file clip_buttons.c.
References BKE_tracking_ensure_marker(), MarkerUpdateCb::compact, MovieTrackingMarker::flag, MarkerUpdateCb::framenr, MarkerUpdateCb::marker_flag, NA_EDITED, NC_MOVIECLIP, NULL, MarkerUpdateCb::track, and WM_event_add_notifier().
Referenced by uiTemplateMarker().
static void to_pixel_space (float r[2], float a[2], int width, int height) [static]
Definition at line 189 of file clip_buttons.c.
References copy_v2_v2().
Referenced by uiTemplateMarker().
void uiTemplateMarker (uiLayout * layout, PointerRNA * ptr, const char * propname, PointerRNA * userptr, PointerRNA * trackptr, int compact)
Definition at line 318 of file clip_buttons.c.
References add_v2_v2v2(), B_MARKER_FLAG, B_MARKER_OFFSET, B_MARKER_PAT_DIM, B_MARKER_POS, B_MARKER_SEARCH_DIM, B_MARKER_SEARCH_POS, BKE_movieclip_get_size(), BKE_tracking_get_marker(), MarkerUpdateCb::clip, MarkerUpdateCb::compact, PointerRNA::data, MovieTrackingMarker::flag, MovieTrackingTrack::flag, MarkerUpdateCb::framenr, MovieClipUser::framenr, LABEL, marker_block_handler(), MARKER_DISABLED, MarkerUpdateCb::marker_flag, MarkerUpdateCb::marker_pos, marker_update_cb(), MEM_callocN(), mul_v2_fl(), NULL, NUM, MovieTrackingTrack::offset, OPTIONN, MovieTrackingTrack::pat_max, MovieTrackingTrack::pat_min, MovieTrackingMarker::pos, PROP_POINTER, RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), MovieTrackingTrack::search_max, MovieTrackingTrack::search_min, step(), sub_v2_v2v2(), to_pixel_space(), TOGN, MarkerUpdateCb::track, TRACK_LOCKED, MarkerUpdateCb::track_offset, MarkerUpdateCb::track_pat, MarkerUpdateCb::track_search, MarkerUpdateCb::track_search_pos, PointerRNA::type, uiBlockBeginAlign(), uiBlockEndAlign(), uiBlockSetHandleFunc(), uiBlockSetNFunc(), uiButSetNFunc(), uiDefBut(), uiDefButBitI(), uiDefButF(), uiDefIconButBitI(), uiLayoutAbsoluteBlock(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutSetActive(), and MarkerUpdateCb::user.
void uiTemplateMovieClip (uiLayout * layout, bContext * C, PointerRNA * ptr, const char * propname, int compact)
Definition at line 80 of file clip_buttons.c.
References PointerRNA::data, LABEL, NULL, PROP_POINTER, RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), split(), PointerRNA::type, uiDefBut(), uiItemO(), uiItemR(), uiLayoutGetBlock(), uiLayoutRow(), uiLayoutSetContextPointer(), uiLayoutSplit(), and uiTemplateID().
void uiTemplateTrack (uiLayout * layout, PointerRNA * ptr, const char * propname)
Definition at line 128 of file clip_buttons.c.
References PointerRNA::data, PROP_POINTER, RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_identifier(), MovieClipScopes::track_preview_height, TRACKPREVIEW, PointerRNA::type, UI_UNIT_Y, uiDefBut(), uiLayoutAbsoluteBlock(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.