Blender: BL_ActionActuator Class Reference
BL_ActionActuator Class Reference
#include <BL_ActionActuator.h>
Public Member Functions
Py_Header BL_ActionActuator (SCA_IObject *gameobj, const STR_String &propname, const STR_String &framepropname, float starttime, float endtime, struct bAction *action, short playtype, short blendin, short priority, short layer, float layer_weight, short ipo_flags, short end_reset, float stride)
virtual ~BL_ActionActuator ()
virtual bool Update (double curtime, bool frame)
virtual CValue * GetReplica ()
virtual void ProcessReplica ()
void SetBlendTime (float newtime)
void SetLocalTime (float curtime)
void ResetStartTime (float curtime)
bAction * GetAction ()
void SetAction (bAction *act)
Protected Attributes
MT_Point3 m_lastpos
float m_blendframe
int m_flag
float m_startframe
float m_endframe
float m_starttime
float m_localtime
float m_lastUpdate
float m_blendin
float m_blendstart
float m_stridelength
float m_layer_weight
short m_playtype
short m_priority
short m_layer
short m_ipo_flags
struct bPose * m_pose
struct bPose * m_blendpose
struct bPose * m_userpose
struct bAction * m_action
STR_String m_propname
STR_String m_framepropname
Detailed Description
Definition at line 40 of file BL_ActionActuator.h.
Constructor & Destructor Documentation
BL_ActionActuator::BL_ActionActuator (SCA_IObject * gameobj, const STR_String & propname, const STR_String & framepropname, float starttime, float endtime, struct bAction * action, short playtype, short blendin, short priority, short layer, float layer_weight, short ipo_flags, short end_reset, float stride)
Definition at line 62 of file BL_ActionActuator.cpp.
References ACT_FLAG_CONTINUE, and m_flag.
Referenced by GetReplica().
BL_ActionActuator::~BL_ActionActuator () [virtual]
Definition at line 105 of file BL_ActionActuator.cpp.
References game_free_pose(), m_blendpose, m_pose, and m_userpose.
Member Function Documentation
bAction* BL_ActionActuator::GetAction () [inline]
Definition at line 68 of file BL_ActionActuator.h.
References m_action.
Referenced by KX_BlenderSceneConverter::FreeBlendFile().
CValue * BL_ActionActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 178 of file BL_ActionActuator.cpp.
References BL_ActionActuator(), and ProcessReplica().
void BL_ActionActuator::ProcessReplica () [virtual]
Makes sure any internal data owned by this class is deep copied.
Reimplemented from SCA_IActuator.
Definition at line 115 of file BL_ActionActuator.cpp.
References m_blendpose, m_lastUpdate, m_localtime, m_pose, m_startframe, and NULL.
Referenced by GetReplica().
void BL_ActionActuator::ResetStartTime (float curtime)
Definition at line 170 of file BL_ActionActuator.cpp.
References KX_KetsjiEngine::GetAnimFrameRate(), m_localtime, m_startframe, and m_starttime.
Referenced by Update().
void BL_ActionActuator::SetAction (bAction * act) [inline]
Definition at line 69 of file BL_ActionActuator.h.
References m_action.
Referenced by KX_BlenderSceneConverter::FreeBlendFile().
void BL_ActionActuator::SetBlendTime (float newtime)
Definition at line 126 of file BL_ActionActuator.cpp.
References m_blendframe.
Referenced by BL_ArmatureObject::SetActiveAction().
void BL_ActionActuator::SetLocalTime (float curtime)
Definition at line 131 of file BL_ActionActuator.cpp.
References ACT_ACTION_LOOP_END, ACT_ACTION_PINGPONG, ACT_ACTION_PLAY, ACT_FLAG_REVERSE, KX_KetsjiEngine::GetAnimFrameRate(), SCA_ILogicBrick::GetParent(), m_endframe, m_flag, m_layer, m_localtime, m_playtype, m_startframe, m_starttime, max, and min.
Referenced by Update().
bool BL_ActionActuator::Update (double curtime, bool frame) [virtual]
Update(...) Update the actuator based upon the events received since the last call to Update, the current time and deltatime the time elapsed in this frame ? It is the responsibility of concrete Actuators to clear their event's. This is usually done in the Update() method via a call to RemoveAllEvents()
Reimplemented from SCA_IActuator.
Definition at line 185 of file BL_ActionActuator.cpp.
References ACT_ACTION_FLIPPER, ACT_ACTION_FROM_PROP, ACT_ACTION_LOOP_END, ACT_ACTION_LOOP_STOP, ACT_ACTION_PINGPONG, ACT_ACTION_PLAY, ACT_FLAG_ACTIVE, ACT_FLAG_ATTEMPT_PLAY, ACT_FLAG_CONTINUE, ACT_FLAG_PLAY_END, ACT_FLAG_REVERSE, BL_Action::ACT_MODE_LOOP, BL_Action::ACT_MODE_PLAY, KX_GameObject::GetActionFrame(), KX_GameObject::GetCurrentAction(), CValue::GetNumber(), SCA_ILogicBrick::GetParent(), CValue::GetProperty(), bAction::id, KX_GameObject::IsActionDone(), m_action, m_blendin, m_endframe, m_flag, m_framepropname, m_ipo_flags, m_layer, m_layer_weight, m_localtime, SCA_IActuator::m_negevent, m_playtype, SCA_IActuator::m_posevent, m_priority, m_propname, m_startframe, ID::name, KX_GameObject::PlayAction(), CValue::Release(), SCA_IActuator::RemoveAllEvents(), ResetStartTime(), KX_GameObject::SetActionFrame(), SetLocalTime(), KX_GameObject::SetPlayMode(), CValue::SetProperty(), CValue::SetValue(), and KX_GameObject::StopAction().
Member Data Documentation
struct bAction* BL_ActionActuator::m_action [protected]
Definition at line 138 of file BL_ActionActuator.h.
Referenced by GetAction(), SetAction(), and Update().
float BL_ActionActuator::m_blendframe [protected]
Definition at line 115 of file BL_ActionActuator.h.
Referenced by SetBlendTime().
float BL_ActionActuator::m_blendin [protected]
Definition at line 127 of file BL_ActionActuator.h.
Referenced by Update().
struct bPose* BL_ActionActuator::m_blendpose [protected]
Definition at line 136 of file BL_ActionActuator.h.
Referenced by ProcessReplica(), and ~BL_ActionActuator().
float BL_ActionActuator::m_blendstart [protected]
Definition at line 128 of file BL_ActionActuator.h.
float BL_ActionActuator::m_endframe [protected]
The frame this action ends
Definition at line 120 of file BL_ActionActuator.h.
Referenced by SetLocalTime(), and Update().
int BL_ActionActuator::m_flag [protected]
Definition at line 116 of file BL_ActionActuator.h.
Referenced by BL_ActionActuator(), SetLocalTime(), and Update().
STR_String BL_ActionActuator::m_framepropname [protected]
Definition at line 140 of file BL_ActionActuator.h.
Referenced by Update().
short BL_ActionActuator::m_ipo_flags [protected]
Definition at line 134 of file BL_ActionActuator.h.
Referenced by Update().
MT_Point3 BL_ActionActuator::m_lastpos [protected]
Definition at line 114 of file BL_ActionActuator.h.
float BL_ActionActuator::m_lastUpdate [protected]
Definition at line 126 of file BL_ActionActuator.h.
Referenced by ProcessReplica().
short BL_ActionActuator::m_layer [protected]
Definition at line 133 of file BL_ActionActuator.h.
Referenced by SetLocalTime(), and Update().
float BL_ActionActuator::m_layer_weight [protected]
Definition at line 130 of file BL_ActionActuator.h.
Referenced by Update().
float BL_ActionActuator::m_localtime [protected]
The current time of the action
Definition at line 124 of file BL_ActionActuator.h.
Referenced by ProcessReplica(), ResetStartTime(), SetLocalTime(), and Update().
short BL_ActionActuator::m_playtype [protected]
Definition at line 131 of file BL_ActionActuator.h.
Referenced by SetLocalTime(), and Update().
struct bPose* BL_ActionActuator::m_pose [protected]
Definition at line 135 of file BL_ActionActuator.h.
Referenced by ProcessReplica(), and ~BL_ActionActuator().
short BL_ActionActuator::m_priority [protected]
Definition at line 132 of file BL_ActionActuator.h.
Referenced by Update().
STR_String BL_ActionActuator::m_propname [protected]
Definition at line 139 of file BL_ActionActuator.h.
Referenced by Update().
float BL_ActionActuator::m_startframe [protected]
The frame this action starts
Definition at line 118 of file BL_ActionActuator.h.
Referenced by ProcessReplica(), ResetStartTime(), SetLocalTime(), and Update().
float BL_ActionActuator::m_starttime [protected]
The time this action started
Definition at line 122 of file BL_ActionActuator.h.
Referenced by ResetStartTime(), and SetLocalTime().
float BL_ActionActuator::m_stridelength [protected]
Definition at line 129 of file BL_ActionActuator.h.
struct bPose* BL_ActionActuator::m_userpose [protected]
Definition at line 137 of file BL_ActionActuator.h.
Referenced by ~BL_ActionActuator().
The documentation for this class was generated from the following files:
BL_ActionActuator.h
BL_ActionActuator.cpp