Blender: bmesh_marking.h File Reference
bmesh_marking.h File Reference
BMesh
Classes
struct BMEditSelection
Defines
#define BM_elem_hide_set(bm, ele, hide) _bm_elem_hide_set(bm, &(ele)->head, hide)
#define BM_select_history_check(bm, ele) _bm_select_history_check(bm, &(ele)->head)
#define BM_select_history_remove(bm, ele) _bm_select_history_remove(bm, &(ele)->head)
#define BM_select_history_store_notest(bm, ele) _bm_select_history_store_notest(bm, &(ele)->head)
#define BM_select_history_store(bm, ele) _bm_select_history_store(bm, &(ele)->head)
Typedefs
typedef struct BMEditSelection BMEditSelection
Functions
void _bm_elem_hide_set (BMesh *bm, BMHeader *ele, int hide)
void BM_vert_hide_set (BMVert *v, int hide)
void BM_edge_hide_set (BMEdge *e, int hide)
void BM_face_hide_set (BMFace *f, int hide)
void BM_elem_select_set (BMesh *bm, BMElem *ele, int select)
void BM_mesh_elem_hflag_enable_test (BMesh *bm, const char htype, const char hflag, int respecthide, const char hflag_test)
void BM_mesh_elem_hflag_disable_test (BMesh *bm, const char htype, const char hflag, int respecthide, const char hflag_test)
void BM_mesh_elem_hflag_enable_all (BMesh *bm, const char htype, const char hflag, int respecthide)
void BM_mesh_elem_hflag_disable_all (BMesh *bm, const char htype, const char hflag, int respecthide)
void BM_vert_select_set (BMesh *bm, BMVert *v, int select)
Select Vert.
void BM_edge_select_set (BMesh *bm, BMEdge *e, int select)
Select Edge.
void BM_face_select_set (BMesh *bm, BMFace *f, int select)
Select Face.
void BM_mesh_select_mode_set (BMesh *bm, int selectmode)
void BM_mesh_select_mode_flush (BMesh *bm)
Select Mode Flush.
void BM_mesh_deselect_flush (BMesh *bm)
void BM_mesh_select_flush (BMesh *bm)
int BM_mesh_elem_hflag_count_enabled (BMesh *bm, const char htype, const char hflag, int respecthide)
int BM_mesh_elem_hflag_count_disabled (BMesh *bm, const char htype, const char hflag, int respecthide)
void BM_active_face_set (BMesh *bm, BMFace *f)
BMFace * BM_active_face_get (BMesh *bm, int sloppy)
void BM_editselection_center (BMEditSelection *ese, float r_center[3])
void BM_editselection_normal (BMEditSelection *ese, float r_normal[3])
void BM_editselection_plane (BMEditSelection *ese, float r_plane[3])
int _bm_select_history_check (BMesh *bm, const BMHeader *ele)
int _bm_select_history_remove (BMesh *bm, BMHeader *ele)
void _bm_select_history_store_notest (BMesh *bm, BMHeader *ele)
void _bm_select_history_store (BMesh *bm, BMHeader *ele)
void BM_select_history_validate (BMesh *bm)
void BM_select_history_clear (BMesh *em)
int BM_select_history_active_get (BMesh *bm, struct BMEditSelection *ese)
Detailed Description
Definition in file bmesh_marking.h.
Define Documentation
#define BM_elem_hide_set (bm, ele, hide) _bm_elem_hide_set(bm, &(ele)->head, hide)
Definition at line 38 of file bmesh_marking.h.
Referenced by BMO_slot_buffer_hflag_disable(), BMO_slot_buffer_hflag_enable(), bpy_bm_elem_hide_set(), EDBM_mesh_hide(), and projectSVData().
#define BM_select_history_check (bm, ele) _bm_select_history_check(bm, &(ele)->head)
Definition at line 80 of file bmesh_marking.h.
Referenced by _bm_select_history_store(), and bpy_bmeditselseq_contains().
#define BM_select_history_remove (bm, ele) _bm_select_history_remove(bm, &(ele)->head)
Definition at line 81 of file bmesh_marking.h.
Referenced by bm_kill_only_edge(), bm_kill_only_face(), bm_kill_only_vert(), bpy_bmeditselseq_remove(), edbm_rip_invoke__vert(), mouse_mesh(), mouse_mesh_shortest_path(), uvedit_uv_select_enable(), and walker_select().
#define BM_select_history_store (bm, ele) _bm_select_history_store(bm, &(ele)->head)
Definition at line 83 of file bmesh_marking.h.
Referenced by BM_mesh_bm_from_me(), BM_mesh_copy(), bpy_bmeditselseq_add(), edbm_rip_invoke__vert(), edbm_vertex_slide_exec(), mouse_mesh(), mouse_mesh_loop(), mouse_mesh_shortest_path(), ringsel_finish(), uvedit_edge_select_enable(), uvedit_face_select_enable(), and vtx_slide_confirm().
#define BM_select_history_store_notest (bm, ele) _bm_select_history_store_notest(bm, &(ele)->head)
Definition at line 82 of file bmesh_marking.h.
Referenced by _bm_select_history_store(), and BPy_BMEditSel_Assign().
Typedef Documentation
typedef struct BMEditSelection BMEditSelection
Function Documentation
void _bm_elem_hide_set (BMesh * bm, BMHeader * ele, int hide)
Definition at line 1014 of file bmesh_marking.c.
References BM_EDGE, BM_edge_hide_set(), BM_edge_select_set(), BM_FACE, BM_face_hide_set(), BM_face_select_set(), BM_VERT, BM_vert_hide_set(), BM_vert_select_set(), BMESH_ASSERT, FALSE, and BMHeader::htype.
int _bm_select_history_check (BMesh * bm, const BMHeader * ele)
Definition at line 718 of file bmesh_marking.c.
References BMEditSelection::ele, FALSE, ListBase::first, BMEditSelection::next, BMesh::selected, and TRUE.
int _bm_select_history_remove (BMesh * bm, BMHeader * ele)
Definition at line 731 of file bmesh_marking.c.
References BLI_freelinkN(), BMEditSelection::ele, FALSE, ListBase::first, BMEditSelection::next, BMesh::selected, and TRUE.
void _bm_select_history_store (BMesh * bm, BMHeader * ele)
Definition at line 752 of file bmesh_marking.c.
References BM_select_history_check, and BM_select_history_store_notest.
void _bm_select_history_store_notest (BMesh * bm, BMHeader * ele)
Definition at line 744 of file bmesh_marking.c.
References BLI_addtail(), BMEditSelection::ele, BMHeader::htype, BMEditSelection::htype, MEM_callocN(), and BMesh::selected.
BMFace* BM_active_face_get (BMesh * bm, int sloppy)
Definition at line 523 of file bmesh_marking.c.
References BMesh::act_face, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_FACE, BM_FACES_OF_MESH, BM_ITER_MESH, BMEditSelection::ele, BMEditSelection::htype, if(), ListBase::last, NULL, BMEditSelection::prev, and BMesh::selected.
Referenced by BM_select_history_active_get(), construct_param_handle(), construct_param_handle_subsurfed(), correct_uv_aspect(), deselect_nth_active(), draw_em_fancy(), draw_uvs(), ED_uvedit_assign_image(), EDBM_mtexpoly_active_get(), image_refresh(), and navmesh_face_copy_exec().
void BM_active_face_set (BMesh * bm, BMFace * f)
Definition at line 518 of file bmesh_marking.c.
References BMesh::act_face.
Referenced by mouse_mesh(), and mouse_select().
void BM_edge_hide_set (BMEdge * e, int hide)
Definition at line 980 of file bmesh_marking.c.
References BM_elem_flag_set, BM_ELEM_HIDDEN, BM_FACES_OF_EDGE, BM_ITER_ELEM, BMEdge::v1, BMEdge::v2, and vert_flush_hide_set().
Referenced by _bm_elem_hide_set().
void BM_edge_select_set (BMesh * bm, BMEdge * e, int select)
Select Edge.
Changes selection state of a single edge in a mesh.
Definition at line 273 of file bmesh_marking.c.
References BLI_assert, BM_EDGE, BM_EDGES_OF_VERT, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_iter_new(), BM_iter_step(), BM_vert_select_set(), FALSE, BMEdge::head, BMHeader::htype, i, SCE_SELECT_EDGE, SCE_SELECT_FACE, BMesh::selectmode, BMesh::totedgesel, TRUE, BMEdge::v1, and BMEdge::v2.
Referenced by _bm_elem_hide_set(), BM_elem_select_set(), BM_face_select_set(), BM_mesh_bm_from_me(), BM_mesh_esubdivide(), BM_mesh_select_mode_set(), createSlideVerts(), do_lasso_select_mesh__doSelectEdge(), do_mesh_box_select__doSelectEdge(), edbm_backbuf_check_and_select_edges(), edbm_extrude_vert(), edbm_region_to_loop_exec(), edbm_ripsel_deselect_helper(), edbm_select_linked_pick_invoke(), edbm_select_loose_verts_exec(), edbm_select_non_manifold_exec(), edbm_select_random_exec(), edbm_select_sharp_edges_exec(), EDBM_select_swap(), EDBM_selectmode_convert(), EDBM_selectmode_set(), edbm_vertex_slide_exec(), edgering_sel(), edgetag_context_set(), init_rotsys(), knife_make_chain_cut(), mesh_circle_doSelectEdge(), mesh_separate_selected(), mouse_mesh(), uvedit_edge_select_disable(), uvedit_edge_select_enable(), and vtx_slide_confirm().
void BM_editselection_center (BMEditSelection * ese, float r_center[3])
Generic way to get data from an EditSelection type These functions were written to be used by the Modifier widget when in Rotate about active mode, but can be used anywhere.
#EM_editselection_center
#EM_editselection_normal
#EM_editselection_plane
Definition at line 569 of file bmesh_marking.c.
References add_v3_v3v3(), BM_EDGE, BM_FACE, BM_face_calc_center_bounds(), BM_VERT, BMVert::co, copy_v3_v3(), BMEditSelection::ele, BMEditSelection::htype, mul_v3_fl(), BMEdge::v1, and BMEdge::v2.
Referenced by BM_editselection_plane(), calc_manipulator_stats(), calculateCenter(), and snap_curs_to_active().
void BM_editselection_normal (BMEditSelection * ese, float r_normal[3])
Definition at line 586 of file bmesh_marking.c.
References add_v3_v3v3(), BM_EDGE, BM_FACE, BM_VERT, BMVert::co, copy_v3_v3(), cross_v3_v3v3(), BMEditSelection::ele, BMEditSelection::htype, BMFace::no, BMVert::no, normalize_v3(), sub_v3_v3v3(), BMEdge::v1, and BMEdge::v2.
Referenced by getTransformOrientation().
void BM_editselection_plane (BMEditSelection * ese, float r_plane[3])
Definition at line 620 of file bmesh_marking.c.
References BM_editselection_center(), BM_VERT, cross_v3_v3v3(), BMEditSelection::ele, BMEditSelection::htype, BMEditSelection::prev, and sub_v3_v3v3().
Referenced by getTransformOrientation().
void BM_elem_select_set (BMesh * bm, BMElem * ele, int select)
Note:
use BM_elem_flag_test(ele, BM_ELEM_SELECT) to test selection
by design, this will not touch the editselection history stuff
Definition at line 499 of file bmesh_marking.c.
References BLI_assert, BM_EDGE, BM_edge_select_set(), BM_FACE, BM_face_select_set(), BM_VERT, BM_vert_select_set(), BMElem::head, and BMHeader::htype.
Referenced by BM_elem_attrs_copy(), BM_mesh_elem_hflag_disable_test(), BM_mesh_elem_hflag_enable_test(), BM_mesh_esubdivide(), BMO_slot_buffer_hflag_disable(), BMO_slot_buffer_hflag_enable(), bpy_bm_elem_select_set(), edbm_extrude_edge(), EDBM_mesh_reveal(), walker_deselect_nth(), and walker_select().
void BM_face_hide_set (BMFace * f, int hide)
Definition at line 998 of file bmesh_marking.c.
References BM_elem_flag_set, BM_ELEM_HIDDEN, BM_ITER_ELEM, BM_LOOPS_OF_FACE, BMLoop::e, edge_flush_hide(), BMLoop::v, and vert_flush_hide_set().
Referenced by _bm_elem_hide_set().
void BM_face_select_set (BMesh * bm, BMFace * f, int select)
Select Face.
Changes selection state of a single face in a mesh.
Definition at line 335 of file bmesh_marking.c.
References BLI_assert, BM_edge_select_set(), BM_EDGES_OF_VERT, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_FACE, BM_FACE_FIRST_LOOP, BM_FACES_OF_EDGE, BM_ITER_ELEM, BM_LOOPS_OF_FACE, BM_vert_select_set(), BMLoop::e, FALSE, BMFace::head, BMHeader::htype, BMLoop::next, BMesh::totfacesel, TRUE, and BMLoop::v.
Referenced by _bm_elem_hide_set(), BM_elem_select_set(), BM_mesh_bm_from_me(), BM_mesh_select_mode_set(), createSlideVerts(), do_lasso_select_mesh__doSelectFace(), do_mesh_box_select__doSelectFace(), edbm_backbuf_check_and_select_faces(), EDBM_deselect_by_material(), edbm_extrude_face_indiv(), edbm_loop_to_region_exec(), edbm_select_by_number_vertices_exec(), EDBM_select_interior_faces(), edbm_select_linked_exec(), edbm_select_linked_flat_faces_exec(), edbm_select_linked_pick_invoke(), edbm_select_random_exec(), EDBM_select_swap(), EDBM_selectmode_convert(), EDBM_selectmode_set(), hide_exec(), mesh_circle_doSelectFace(), mesh_separate_material(), mouse_mesh(), projectSVData(), uvedit_edge_select_disable(), uvedit_edge_select_enable(), uvedit_face_select_disable(), uvedit_face_select_enable(), uvedit_uv_select_disable(), and uvedit_uv_select_enable().
void BM_mesh_deselect_flush (BMesh * bm)
mode independent flushing up/down
Definition at line 145 of file bmesh_marking.c.
References BM_EDGES_OF_MESH, BM_elem_flag_disable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_FACE_FIRST_LOOP, BM_FACES_OF_MESH, BM_ITER_MESH, BM_select_history_validate(), FALSE, BMLoop::next, recount_totsels(), TRUE, BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by bpy_bmesh_select_flush(), and EDBM_deselect_flush().
int BM_mesh_elem_hflag_count_disabled (BMesh * bm, const char htype, const char hflag, int respecthide)
Definition at line 490 of file bmesh_marking.c.
References bm_mesh_flag_count(), and FALSE.
Referenced by bmo_slot_buffer_from_hflag().
int BM_mesh_elem_hflag_count_enabled (BMesh * bm, const char htype, const char hflag, int respecthide)
Definition at line 485 of file bmesh_marking.c.
References bm_mesh_flag_count(), and TRUE.
Referenced by bmo_slot_buffer_from_hflag().
void BM_mesh_elem_hflag_disable_all (BMesh * bm, const char htype, const char hflag, int respecthide)
Definition at line 920 of file bmesh_marking.c.
References BM_mesh_elem_hflag_disable_test().
Referenced by BM_mesh_esubdivide(), bmo_inset_exec(), EDBM_flag_disable_all(), edbm_inset_exec(), EDBM_op_call_and_selectf(), edbm_region_to_loop_exec(), edbm_split_exec(), and select_edgeloop().
void BM_mesh_elem_hflag_disable_test (BMesh * bm, const char htype, const char hflag, int respecthide, const char hflag_test)
Definition at line 818 of file bmesh_marking.c.
References BM_EDGE, BM_EDGES_OF_MESH, BM_elem_flag_disable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_elem_select_set(), BM_FACE, BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_select_history_clear(), BM_VERT, BM_VERTS_OF_MESH, FALSE, i, NULL, BMesh::totedgesel, BMesh::totfacesel, and BMesh::totvertsel.
Referenced by BM_mesh_elem_hflag_disable_all().
void BM_mesh_elem_hflag_enable_all (BMesh * bm, const char htype, const char hflag, int respecthide)
Definition at line 927 of file bmesh_marking.c.
References BM_mesh_elem_hflag_enable_test().
Referenced by arrayModifier_doArray(), bmo_inset_exec(), and EDBM_flag_enable_all().
void BM_mesh_elem_hflag_enable_test (BMesh * bm, const char htype, const char hflag, int respecthide, const char hflag_test)
Definition at line 873 of file bmesh_marking.c.
References BM_EDGE, BM_EDGES_OF_MESH, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_elem_select_set(), BM_FACE, BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_select_history_clear(), BM_VERT, BM_VERTS_OF_MESH, i, NULL, and TRUE.
Referenced by BM_mesh_elem_hflag_enable_all(), edbm_inset_exec(), and reveal_exec().
void BM_mesh_select_flush (BMesh * bm)
mode independent flushing up/down
Definition at line 196 of file bmesh_marking.c.
References BM_EDGES_OF_MESH, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_FACE_FIRST_LOOP, BM_FACES_OF_MESH, BM_ITER_MESH, FALSE, BMLoop::next, recount_totsels(), TRUE, BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by bpy_bmesh_select_flush(), and EDBM_select_flush().
void BM_mesh_select_mode_flush (BMesh * bm)
Select Mode Flush.
Makes sure to flush selections 'upwards' (ie: all verts of an edge selects the edge and so on). This should only be called by system and not tool authors.
Definition at line 74 of file bmesh_marking.c.
References BM_EDGES_OF_MESH, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_set, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_FACE_FIRST_LOOP, BM_FACES_OF_MESH, BM_ITER_MESH, BM_select_history_validate(), BMLoop::e, FALSE, BMLoop::next, recount_totsels(), SCE_SELECT_EDGE, SCE_SELECT_VERTEX, BMesh::selectmode, TRUE, BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by BM_mesh_select_mode_set(), bmesh_edit_end(), bpy_bmesh_select_flush_mode(), ED_object_enter_editmode(), edbm_select_linked_pick_invoke(), and EDBM_selectmode_flush_ex().
void BM_mesh_select_mode_set (BMesh * bm, int selectmode)
Select Mode Set
Sets the selection mode for the bmesh, updating the selection state.
Definition at line 401 of file bmesh_marking.c.
References BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_flag_disable, BM_elem_flag_test, BM_ELEM_SELECT, BM_face_select_set(), BM_FACES_OF_MESH, BM_ITER_MESH, BM_mesh_select_mode_flush(), BM_VERTS_OF_MESH, SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMesh::selectmode, and TRUE.
int BM_select_history_active_get (BMesh * bm, struct BMEditSelection * ese)
Definition at line 784 of file bmesh_marking.c.
References BM_active_face_get(), BM_FACE, BMEditSelection::ele, FALSE, BMEditSelection::htype, ListBase::last, BMEditSelection::next, NULL, BMEditSelection::prev, BMesh::selected, and TRUE.
Referenced by calc_manipulator_stats(), calculateCenter(), edbm_rip_invoke__vert(), getTransformOrientation(), and snap_curs_to_active().
void BM_select_history_clear (BMesh * em)
Definition at line 761 of file bmesh_marking.c.
References BLI_freelistN(), ListBase::first, ListBase::last, NULL, and BMesh::selected.
Referenced by BM_mesh_elem_hflag_disable_test(), BM_mesh_elem_hflag_enable_test(), BPy_BMEditSel_Assign(), and bpy_bmeditselseq_clear().
void BM_select_history_validate (BMesh * bm)
Definition at line 768 of file bmesh_marking.c.
References BLI_freelinkN(), BM_elem_flag_test, BM_ELEM_SELECT, BMEditSelection::ele, ListBase::first, BMEditSelection::next, and BMesh::selected.
Referenced by BM_mesh_deselect_flush(), BM_mesh_select_mode_flush(), border_select_exec(), bpy_bmeditselseq_validate(), hide_exec(), and mouse_select().
void BM_vert_hide_set (BMVert * v, int hide)
Definition at line 962 of file bmesh_marking.c.
References BM_EDGES_OF_VERT, BM_elem_flag_set, BM_ELEM_HIDDEN, BM_FACES_OF_EDGE, and BM_ITER_ELEM.
Referenced by _bm_elem_hide_set().
void BM_vert_select_set (BMesh * bm, BMVert * v, int select)
Select Vert.
Changes selection state of a single vertex in a mesh
Definition at line 246 of file bmesh_marking.c.
References BLI_assert, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_VERT, BMVert::head, BMHeader::htype, and BMesh::totvertsel.
Referenced by _bm_elem_hide_set(), BM_edge_select_set(), BM_elem_select_set(), BM_face_select_set(), BM_mesh_bm_from_me(), createSlideVerts(), do_lasso_select_mesh__doSelectVert(), do_mesh_box_select__doSelectVert(), edbm_backbuf_check_and_select_verts(), edbm_dupli_extrude_cursor_invoke(), edbm_extrude_vert(), edbm_rip_invoke__vert(), edbm_select_axis_exec(), edbm_select_linked_exec(), edbm_select_loose_verts_exec(), EDBM_select_mirrored(), edbm_select_next_loop_exec(), edbm_select_non_manifold_exec(), edbm_select_random_exec(), EDBM_select_swap(), EDBM_selectmode_set(), edbm_vertex_slide_exec(), hide_exec(), init_rotsys(), mesh_circle_doSelectVert(), mesh_separate_loose(), mesh_separate_selected(), mouse_mesh(), select_editbmesh_hook(), uvedit_edge_select_disable(), uvedit_edge_select_enable(), uvedit_uv_select_disable(), uvedit_uv_select_enable(), vgroup_select_verts(), and vtx_slide_confirm().