Blender: bmo_dissolve.c File Reference
bmo_dissolve.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "BLI_array.h"
#include "BLI_math.h"
#include "bmesh.h"
#include "intern/bmesh_private.h"
#include "intern/bmesh_operators_private.h"
Classes
struct DissolveElemWeight
Defines
#define FACE_MARK 1
#define FACE_ORIG 2
#define FACE_NEW 4
#define EDGE_MARK 1
#define VERT_MARK 1
#define UNIT_TO_ANGLE DEG2RADF(90.0)
#define ANGLE_TO_UNIT (1.0 / UNIT_TO_ANGLE)
Typedefs
typedef struct DissolveElemWeight DissolveElemWeight
Functions
static int UNUSED_FUNCTION() check_hole_in_region (BMesh *bm, BMFace *f)
void bmo_dissolve_faces_exec (BMesh *bm, BMOperator *op)
void bmo_dissolve_edgeloop_exec (BMesh *bm, BMOperator *op)
void bmo_dissolve_edges_exec (BMesh *bm, BMOperator *op)
static int test_extra_verts (BMesh *bm, BMVert *v)
void bmo_dissolve_verts_exec (BMesh *bm, BMOperator *op)
float bm_vert_edge_face_angle (BMVert *v)
static int dissolve_elem_cmp (const void *a1, const void *a2)
void bmo_dissolve_limit_exec (BMesh *bm, BMOperator *op)
Detailed Description
Definition in file bmo_dissolve.c.
Define Documentation
#define ANGLE_TO_UNIT (1.0 / UNIT_TO_ANGLE)
Definition at line 482 of file bmo_dissolve.c.
Referenced by bm_vert_edge_face_angle().
#define EDGE_MARK 1
Definition at line 40 of file bmo_dissolve.c.
Referenced by check_hole_in_region().
#define FACE_MARK 1
Definition at line 37 of file bmo_dissolve.c.
Referenced by bmo_dissolve_faces_exec(), bmo_dissolve_verts_exec(), check_hole_in_region(), and test_extra_verts().
#define FACE_NEW 4
Definition at line 39 of file bmo_dissolve.c.
Referenced by bmo_dissolve_faces_exec().
#define FACE_ORIG 2
Definition at line 38 of file bmo_dissolve.c.
Referenced by bmo_dissolve_faces_exec(), and bmo_dissolve_verts_exec().
#define UNIT_TO_ANGLE DEG2RADF(90.0)
Definition at line 481 of file bmo_dissolve.c.
Referenced by bm_vert_edge_face_angle().
#define VERT_MARK 1
Definition at line 42 of file bmo_dissolve.c.
Referenced by bmo_dissolve_edgeloop_exec(), bmo_dissolve_edges_exec(), bmo_dissolve_faces_exec(), bmo_dissolve_verts_exec(), and test_extra_verts().
Typedef Documentation
typedef struct DissolveElemWeight DissolveElemWeight
Function Documentation
float bm_vert_edge_face_angle (BMVert * v)
Definition at line 487 of file bmo_dissolve.c.
References angle(), ANGLE_TO_UNIT, BM_edge_calc_face_angle(), BM_edge_is_manifold(), BM_vert_calc_edge_angle(), BMVert::e, and UNIT_TO_ANGLE.
Referenced by bmo_dissolve_limit_exec().
void bmo_dissolve_edgeloop_exec (BMesh * bm, BMOperator * op)
Definition at line 199 of file bmo_dissolve.c.
References BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_free, BM_EDGE, BM_edge_face_pair(), BM_faces_join_pair(), BM_ITER_MESH, BM_vert_collapse_edge(), BM_vert_edge_count(), BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, fb(), i, NULL, TRUE, BMEdge::v1, BMEdge::v2, and VERT_MARK.
void bmo_dissolve_edges_exec (BMesh * bm, BMOperator * op)
Definition at line 246 of file bmo_dissolve.c.
References BM_EDGE, BM_edge_face_pair(), BM_faces_join_pair(), BM_ITER_MESH, BM_vert_collapse_edge(), BM_vert_edge_count(), BM_VERTS_OF_MESH, BMO_elem_flag_set, BMO_elem_flag_test, BMO_ITER, BMO_slot_bool_get(), BMVert::e, fb(), TRUE, and VERT_MARK.
void bmo_dissolve_faces_exec (BMesh * bm, BMOperator * op)
Definition at line 77 of file bmo_dissolve.c.
References BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BM_FACE, BM_faces_join(), BM_ITER_MESH, BM_vert_collapse_edge(), BM_vert_edge_count(), BM_VERTS_OF_MESH, BMERR_DISSOLVEFACES_FAILED, BMO_elem_flag_disable, BMO_elem_flag_enable, BMO_elem_flag_set, BMO_elem_flag_test, BMO_error_clear(), BMO_error_occurred(), BMO_error_raise(), BMO_ITER, BMO_op_callf(), BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMW_begin(), BMW_end(), BMW_FLAG_NOP, BMW_init(), BMW_ISLAND, BMW_MASK_NOP, BMW_NIL_LAY, BMW_step(), DEL_FACES, BMVert::e, FACE_MARK, FACE_NEW, FACE_ORIG, i, MEM_freeN(), NULL, TRUE, and VERT_MARK.
void bmo_dissolve_limit_exec (BMesh * bm, BMOperator * op)
Definition at line 516 of file bmo_dissolve.c.
References angle(), BM_edge_calc_face_angle(), BM_edge_is_manifold(), BM_edge_is_wire(), BM_edge_kill(), BM_edge_normals_update(), BM_face_normal_update(), BM_faces_join_pair(), BM_vert_collapse_edge(), BM_vert_edge_count(), bm_vert_edge_face_angle(), BM_vert_kill(), BMO_error_clear(), BMO_slot_float_get(), BMO_slot_get(), BMOpSlot::data, dissolve_elem_cmp(), BMVert::e, DissolveElemWeight::ele, BMLoop::f, FALSE, i, BMEdge::l, BMOpSlot::len, M_PI, MAX2, MEM_freeN(), MEM_mallocN(), minf(), NULL, BMOpSlot::p, BMLoop::radial_next, TRUE, BMEdge::v1, BMEdge::v2, and DissolveElemWeight::weight.
void bmo_dissolve_verts_exec (BMesh * bm, BMOperator * op)
Definition at line 334 of file bmo_dissolve.c.
References BM_FACES_OF_VERT, BM_iter_new(), BM_iter_step(), BM_VERT, BM_vert_collapse_edge(), BM_vert_collapse_faces(), BM_vert_dissolve(), BM_vert_edge_count(), BM_VERTS_OF_MESH, BMERR_DISSOLVEVERTS_FAILED, BMO_elem_flag_disable, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_error_clear(), BMO_error_get(), BMO_error_occurred(), BMO_error_raise(), BMO_op_callf(), BMO_slot_buffer_flag_enable(), BMVert::e, FACE_MARK, FACE_ORIG, NULL, test_extra_verts(), TRUE, and VERT_MARK.
static int UNUSED_FUNCTION() check_hole_in_region (BMesh * bm, BMFace * f) [static]
Definition at line 44 of file bmo_dissolve.c.
References BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BMO_elem_flag_test, BMW_begin(), BMW_end(), BMW_FLAG_NOP, BMW_init(), BMW_ISLAND, BMW_MASK_NOP, BMW_NIL_LAY, BMW_step(), BMLoop::e, EDGE_MARK, BMLoop::f, FACE_MARK, FALSE, BMLoop::radial_next, and TRUE.
static int dissolve_elem_cmp (const void * a1, const void * a2) [static]
Definition at line 507 of file bmo_dissolve.c.
References DissolveElemWeight::weight.
Referenced by bmo_dissolve_limit_exec().
static int test_extra_verts (BMesh * bm, BMVert * v) [static]
Definition at line 289 of file bmo_dissolve.c.
References BM_edge_is_boundary(), BM_EDGES_OF_VERT, BM_FACES_OF_EDGE, BM_FACES_OF_VERT, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BMO_elem_flag_test, FACE_MARK, FALSE, TRUE, BMLoop::v, and VERT_MARK.
Referenced by bmo_dissolve_verts_exec().