Blender: BLI_fileops.h File Reference
BLI_fileops.h File Reference
blenlib
File and directory operations.
#include <stdio.h>
#include "BLI_fileops_types.h"
#include <stddef.h>
Functions
int BLI_exists (const char *path)
int BLI_copy (const char *path, const char *to)
int BLI_rename (const char *from, const char *to)
int BLI_delete (const char *path, int dir, int recursive)
int BLI_move (const char *path, const char *to)
int BLI_create_symlink (const char *path, const char *to)
int BLI_is_dir (const char *path)
int BLI_is_file (const char *path)
void BLI_dir_create_recursive (const char *dir)
double BLI_dir_free_space (const char *dir)
char * BLI_current_working_dir (char *dir, const int maxlen)
unsigned int BLI_dir_contents (const char *dir, struct direntry **filelist)
FILE * BLI_fopen (const char *filename, const char *mode)
void * BLI_gzopen (const char *filename, const char *mode)
int BLI_open (const char *filename, int oflag, int pmode)
int BLI_file_is_writable (const char *file)
int BLI_file_touch (const char *file)
int BLI_file_gzip (const char *from, const char *to)
char * BLI_file_ungzip_to_mem (const char *from_file, int *size_r)
size_t BLI_file_descriptor_size (int file)
size_t BLI_file_size (const char *file)
int BLI_file_older (const char *file1, const char *file2)
struct LinkNode * BLI_file_read_as_lines (const char *file)
void BLI_file_free_lines (struct LinkNode *lines)
Detailed Description
File and directory operations.
Definition in file BLI_fileops.h.
Function Documentation
int BLI_copy (const char * path, const char * to)
Definition at line 820 of file fileops.c.
References check_destination(), copy_callback_pre(), copy_single_file(), MEM_freeN(), NULL, and recursive_operation().
Referenced by ImagesExporter::operator()(), and writePackedFile().
int BLI_create_symlink (const char * path, const char * to)
Definition at line 833 of file fileops.c.
char* BLI_current_working_dir (char * dir, const int maxlen)
Definition at line 105 of file storage.c.
References BLI_strncpy().
Referenced by BLI_path_cwd(), bli_where_am_i(), filelist_read_dir(), get_path_system(), and init_iconfile_list().
int BLI_delete (const char * path, int dir, int recursive)
Definition at line 576 of file fileops.c.
References delete_callback_post(), delete_single_file(), NULL, and recursive_operation().
Referenced by BKE_ptcache_id_clear(), BKE_ptcache_remove(), BLI_file_is_writable(), BLI_rename(), BLO_write_file(), cdf_remove(), file_delete_exec(), IMB_thumb_delete(), IMB_thumb_manage(), RE_BlenderAnim(), wm_autosave_delete(), and writePackedFile().
unsigned int BLI_dir_contents (const char * dir, struct direntry ** filelist)
Definition at line 420 of file storage.c.
References actnum, bli_adddirstrings(), bli_builddir(), NULL, and totnum.
Referenced by filelist_read_dir(), and init_iconfile_list().
void BLI_dir_create_recursive (const char * dir)
Definition at line 838 of file fileops.c.
References BLI_dir_create_recursive(), BLI_exists(), BLI_last_slash(), BLI_strncpy(), MAXPATHLEN, MEM_callocN(), MEM_freeN(), size(), and strlen().
Referenced by BLI_dir_create_recursive(), BLI_get_folder_create(), BLI_make_existing_file(), file_directory_exec(), file_directory_new_exec(), and IMB_thumb_makedirs().
double BLI_dir_free_space (const char * dir)
Definition at line 146 of file storage.c.
References DWORD, FILE_MAXDIR, len(), and strlen().
int BLI_exists (const char * path)
Definition at line 467 of file storage.c.
References alloc_utf16_from_8(), L, and len().
Referenced by add_win32_extension(), autocomplete_directory(), BKE_ptcache_id_exist(), BKE_ptcache_remove(), blf_dir_metrics_search(), blf_dir_search(), BLI_dir_create_recursive(), BLI_is_dir(), BLI_is_file(), BLI_make_existing_file(), BLI_rename(), bli_where_am_i(), cache_voxeldata(), checkMissingFiles_visit_cb(), collada_export(), file_directory_exec(), file_directory_invoke(), file_directory_new_exec(), file_exec(), fsmenu_read_bookmarks(), fsmenu_read_system(), get_filename(), image_save_exec(), IMB_exr_begin_read(), IMB_thumb_delete(), IMB_thumb_manage(), movieclip_calc_length(), namebutton_cb(), new_folder_path(), openanim(), ptcache_file_open(), RE_BlenderAnim(), renamebutton_cb(), seq_proxy_fetch(), space_image_file_exists_poll(), text_file_modified(), text_ignore_modified(), unpackFile(), wm_autosave_delete(), wm_autosave_location(), WM_read_history(), WM_read_homefile(), wm_save_mainfile_invoke(), and writePackedFile().
size_t BLI_file_descriptor_size (int file)
Definition at line 445 of file storage.c.
Referenced by BLI_file_size(), BLO_read_runtime(), IMB_loadifffile(), imb_loadtilefile(), and newPackedFile().
void BLI_file_free_lines (struct LinkNode * lines)
Definition at line 549 of file storage.c.
References BLI_linklist_free(), and MEM_freeN().
Referenced by WM_read_history().
int BLI_file_gzip (const char * from, const char * to)
Definition at line 72 of file fileops.c.
References BLI_gzopen(), BLI_open(), err, NULL, and O_BINARY.
Referenced by BLO_write_file().
int BLI_file_is_writable (const char * file)
Definition at line 157 of file fileops.c.
References BLI_delete(), BLI_open(), and O_BINARY.
Referenced by image_save_exec(), RE_is_rendering_allowed(), and space_image_file_exists_poll().
int BLI_file_older (const char * file1, const char * file2)
is file1 older then file2
Definition at line 555 of file storage.c.
References UTF16_ENCODE, and UTF16_UN_ENCODE.
Referenced by imb_cache_filename(), and IMB_thumb_manage().
struct LinkNode* BLI_file_read_as_lines (const char * file) [read]
Definition at line 508 of file storage.c.
References BLI_fopen(), BLI_linklist_prepend(), BLI_linklist_reverse(), BLI_strdupn(), fseek, ftell, i, MEM_freeN(), MEM_mallocN(), NULL, and size().
Referenced by WM_read_history().
size_t BLI_file_size (const char * file)
Definition at line 454 of file storage.c.
References BLI_file_descriptor_size(), BLI_open(), O_BINARY, and size().
Referenced by IMB_exr_begin_read(), IMB_thumb_create(), and RE_BlenderAnim().
int BLI_file_touch (const char * file)
Definition at line 185 of file fileops.c.
References BLI_fopen(), and NULL.
Referenced by collada_export(), RE_BlenderAnim(), and touch_seq_files().
char* BLI_file_ungzip_to_mem (const char * from_file, int * size_r)
Definition at line 116 of file fileops.c.
References BLI_gzopen(), MEM_callocN(), MEM_freeN(), MEM_reallocN(), NULL, and size().
FILE* BLI_fopen (const char * filename, const char * mode)
Definition at line 561 of file fileops.c.
Referenced by add_text(), BLI_file_read_as_lines(), BLI_file_touch(), cache_voxeldata(), cdf_read_open(), cdf_write_open(), cineonCreate(), cineonOpen(), dpxCreate(), dpxDump(), fsmenu_read_bookmarks(), fsmenu_write_file(), IMB_index_builder_create(), IMB_indexer_open(), imb_savebmp(), imb_savehdr(), imb_savejp2(), imb_savepng(), imb_savetarga(), intern_dpxOpen(), logImageDump(), output_iris(), paste_file(), ptcache_file_open(), python_script_exec(), reopen_text(), save_maxjpeg(), save_stdjpeg(), save_vidjpeg(), txt_write_file(), and write_history().
void* BLI_gzopen (const char * filename, const char * mode)
Definition at line 566 of file fileops.c.
Referenced by BLI_file_gzip(), BLI_file_ungzip_to_mem(), blo_openblenderfile(), IMB_loadblend_thumb(), particles_fluid_step(), and wm_read_exotic().
int BLI_is_dir (const char * path)
Definition at line 497 of file storage.c.
References BLI_exists(), and S_ISDIR.
Referenced by BLI_getDefaultDocumentFolder(), BLI_make_exist(), BLI_where_is_temp(), file_browse_exec(), file_change_dir(), test_env_path(), and test_path().
int BLI_is_file (const char * path)
Definition at line 502 of file storage.c.
References BLI_exists(), and S_ISDIR.
Referenced by file_directory_exec(), and file_draw_check_exists().
int BLI_move (const char * path, const char * to)
Definition at line 776 of file fileops.c.
References delete_callback_post(), delete_single_file(), move_callback_pre(), move_single_file(), NULL, and recursive_operation().
int BLI_open (const char * filename, int oflag, int pmode)
Definition at line 571 of file fileops.c.
Referenced by BKE_add_image_file(), BKE_add_movieclip_file(), BKE_undo_save_quit(), BLI_file_gzip(), BLI_file_is_writable(), BLI_file_size(), BLO_is_a_runtime(), BLO_read_runtime(), BLO_write_file(), checkPackedFile(), IMB_ispic_name(), IMB_loadiffname(), imb_loadtile(), IMB_testiffname(), newPackedFile(), and writePackedFile().
int BLI_rename (const char * from, const char * to)
Definition at line 875 of file fileops.c.
References BLI_delete(), and BLI_exists().
Referenced by BKE_ptcache_disk_cache_rename(), BLO_write_file(), do_history(), IMB_index_builder_finish(), IMB_thumb_create(), renamebutton_cb(), wm_autosave_delete(), and writePackedFile().