Blender: logic_buttons.c File Reference
logic_buttons.c File Reference
game logic editor
#include <string.h>
#include <stdio.h>
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "ED_screen.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_view2d.h"
#include "interface_intern.h"
#include "logic_intern.h"
Defines
#define LINK_RESOL 12
Functions
static int logic_properties (bContext *C, wmOperator *UNUSED(op))
void LOGIC_OT_properties (wmOperatorType *ot)
static int cut_links_intersect (uiLinkLine *line, float mcoords[][2], int tot)
static int cut_links_exec (bContext *C, wmOperator *op)
void LOGIC_OT_links_cut (wmOperatorType *ot)
Detailed Description
Definition in file logic_buttons.c.
Define Documentation
#define LINK_RESOL 12
Definition at line 80 of file logic_buttons.c.
Referenced by cut_links_intersect().
Function Documentation
static int cut_links_exec (bContext * C, wmOperator * op) [static]
Definition at line 101 of file logic_buttons.c.
References uiBlock::buttons, CTX_wm_region(), cut_links_intersect(), ListBase::first, i, uiLink::lines, uiBut::link, LINK, uiBut::next, uiLinkLine::next, uiBlock::next, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_BEGIN, RNA_END, RNA_float_get_array(), uiBut::type, ui_delete_linkline(), UI_view2d_region_to_view(), ARegion::uiblocks, and ARegion::v2d.
Referenced by LOGIC_OT_links_cut().
static int cut_links_intersect (uiLinkLine * line, float mcoords[][2], int tot) [static]
Definition at line 81 of file logic_buttons.c.
References uiLinkLine::from, i, isect_line_line_v2(), LINK_RESOL, uiLinkLine::to, ui_link_bezier_points(), uiBut::x1, uiBut::x2, rcti::xmax, rcti::xmin, uiBut::y1, uiBut::y2, rcti::ymax, and rcti::ymin.
Referenced by cut_links_exec().
void LOGIC_OT_links_cut (wmOperatorType * ot)
Definition at line 143 of file logic_buttons.c.
References BC_KNIFECURSOR, wmOperatorType::cancel, cut_links_exec(), wmOperatorType::description, ED_operator_logic_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_COLLECTION, PROP_NONE, RNA_def_int(), RNA_def_property(), RNA_def_property_struct_runtime(), RNA_OperatorMousePath, wmOperatorType::srna, WM_gesture_lines_cancel(), WM_gesture_lines_invoke(), and WM_gesture_lines_modal().
Referenced by logic_operatortypes().
void LOGIC_OT_properties (wmOperatorType * ot)
Definition at line 64 of file logic_buttons.c.
References wmOperatorType::description, ED_operator_logic_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, logic_properties(), wmOperatorType::name, and wmOperatorType::poll.
Referenced by logic_operatortypes().
static int logic_properties (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 53 of file logic_buttons.c.
References CTX_wm_area(), ED_region_toggle_hidden(), logic_has_buttons_region(), and OPERATOR_FINISHED.
Referenced by LOGIC_OT_properties().