Blender: renderdatabase.h File Reference
renderdatabase.h File Reference
Rendering
Classes
struct VertTableNode
struct VlakTableNode
struct StrandTableNode
Defines
#define RE_QUAD_MASK 0x7FFFFFF
#define RE_QUAD_OFFS 0x8000000
#define HA_ONLYSKY 1
#define HA_VECT 2
#define HA_XALPHA 4
#define HA_FLARECIRC 8
Typedefs
typedef struct VertTableNode VertTableNode
typedef struct VlakTableNode VlakTableNode
typedef struct StrandTableNode StrandTableNode
Functions
void free_renderdata_tables (struct Render *re)
void free_renderdata_vertnodes (struct VertTableNode *vertnodes)
void free_renderdata_vlaknodes (struct VlakTableNode *vlaknodes)
void project_renderdata (struct Render *re, void(*projectfunc)(const float *, float mat[][4], float *), int do_pano, float xoffs, int do_buckets)
int clip_render_object (float boundbox[][3], float *bounds, float mat[][4])
struct VlakRen * RE_findOrAddVlak (struct ObjectRen *obr, int nr)
struct VertRen * RE_findOrAddVert (struct ObjectRen *obr, int nr)
struct StrandRen * RE_findOrAddStrand (struct ObjectRen *obr, int nr)
struct HaloRen * RE_findOrAddHalo (struct ObjectRen *obr, int nr)
struct HaloRen * RE_inithalo (struct Render *re, struct ObjectRen *obr, struct Material *ma, float *vec, float *vec1, float *orco, float hasize, float vectsize, int seed)
struct HaloRen * RE_inithalo_particle (struct Render *re, struct ObjectRen *obr, struct DerivedMesh *dm, struct Material *ma, float *vec, float *vec1, float *orco, float *uvco, float hasize, float vectsize, int seed, float *pa_co)
struct StrandBuffer * RE_addStrandBuffer (struct ObjectRen *obr, int totvert)
struct ObjectRen * RE_addRenderObject (struct Render *re, struct Object *ob, struct Object *par, int index, int psysindex, int lay)
struct ObjectInstanceRen * RE_addRenderInstance (struct Render *re, struct ObjectRen *obr, struct Object *ob, struct Object *par, int index, int psysindex, float mat[][4], int lay)
void RE_makeRenderInstances (struct Render *re)
float * RE_vertren_get_sticky (struct ObjectRen *obr, struct VertRen *ver, int verify)
float * RE_vertren_get_stress (struct ObjectRen *obr, struct VertRen *ver, int verify)
float * RE_vertren_get_rad (struct ObjectRen *obr, struct VertRen *ver, int verify)
float * RE_vertren_get_strand (struct ObjectRen *obr, struct VertRen *ver, int verify)
float * RE_vertren_get_tangent (struct ObjectRen *obr, struct VertRen *ver, int verify)
float * RE_vertren_get_winspeed (struct ObjectInstanceRen *obi, struct VertRen *ver, int verify)
struct MTFace * RE_vlakren_get_tface (struct ObjectRen *obr, VlakRen *ren, int n, char **name, int verify)
struct MCol * RE_vlakren_get_mcol (struct ObjectRen *obr, VlakRen *ren, int n, char **name, int verify)
float * RE_vlakren_get_surfnor (struct ObjectRen *obr, VlakRen *ren, int verify)
float * RE_vlakren_get_nmap_tangent (struct ObjectRen *obr, VlakRen *ren, int verify)
RadFace ** RE_vlakren_get_radface (struct ObjectRen *obr, VlakRen *ren, int verify)
void RE_vlakren_get_normal (struct Render *re, struct ObjectInstanceRen *obi, struct VlakRen *vlr, float *nor)
float * RE_strandren_get_surfnor (struct ObjectRen *obr, struct StrandRen *strand, int verify)
float * RE_strandren_get_uv (struct ObjectRen *obr, struct StrandRen *strand, int n, char **name, int verify)
struct MCol * RE_strandren_get_mcol (struct ObjectRen *obr, struct StrandRen *strand, int n, char **name, int verify)
float * RE_strandren_get_simplify (struct ObjectRen *obr, struct StrandRen *strand, int verify)
int * RE_strandren_get_face (struct ObjectRen *obr, struct StrandRen *strand, int verify)
float * RE_strandren_get_winspeed (struct ObjectInstanceRen *obi, struct StrandRen *strand, int verify)
struct VertRen * RE_vertren_copy (struct ObjectRen *obr, struct VertRen *ver)
struct VlakRen * RE_vlakren_copy (struct ObjectRen *obr, struct VlakRen *vlr)
void RE_set_customdata_names (struct ObjectRen *obr, struct CustomData *data)
void init_render_world (Render *re)
void RE_Database_FromScene_Vectors (Render *re, struct Main *bmain, struct Scene *sce, unsigned int lay)
Detailed Description
Definition in file renderdatabase.h.
Define Documentation
#define HA_FLARECIRC 8
Definition at line 138 of file renderdatabase.h.
Referenced by renderflare(), and shadeHaloFloat().
#define HA_ONLYSKY 1
Definition at line 135 of file renderdatabase.h.
Referenced by calchalo_z(), project_renderdata(), RE_make_stars(), and shadeHaloFloat().
#define HA_VECT 2
Definition at line 136 of file renderdatabase.h.
Referenced by RE_inithalo(), RE_inithalo_particle(), and shadeHaloFloat().
#define HA_XALPHA 4
Definition at line 137 of file renderdatabase.h.
Referenced by RE_inithalo(), RE_inithalo_particle(), and shadeHaloFloat().
#define RE_QUAD_MASK 0x7FFFFFF
Definition at line 51 of file renderdatabase.h.
Referenced by deep_alpha(), isb_make_buffer(), isb_make_buffer_transp(), shade_input_set_triangle(), and zbufshade_sss_tile().
#define RE_QUAD_OFFS 0x8000000
Definition at line 52 of file renderdatabase.h.
Referenced by isb_add_shadfac(), isb_bsp_test_face(), isb_bsp_test_strand(), isb_make_buffer(), isb_make_buffer_transp(), shade_input_set_triangle(), zbuffer_abuf(), zbuffer_solid(), zbuffer_sss(), and zbufshade_sss_tile().
Typedef Documentation
typedef struct StrandTableNode StrandTableNode
typedef struct VertTableNode VertTableNode
typedef struct VlakTableNode VlakTableNode
Function Documentation
int clip_render_object (float boundbox[][3], float * bounds, float mat[][4])
Definition at line 1379 of file renderdatabase.c.
References copy_m4_m4(), and mul_m4_v4().
Referenced by zbuffer_abuf(), zbuffer_shadow(), zbuffer_solid(), zbuffer_sss(), and zbuffer_strands_abuf().
void free_renderdata_tables (struct Render * re)
Definition at line 808 of file renderdatabase.c.
References BLI_freelistN(), ObjectRen::bloha, ObjectRen::blohalen, StrandBuffer::bound, Render::customdata_names, ListBase::first, free_renderdata_strandnodes(), free_renderdata_vertnodes(), free_renderdata_vlaknodes(), Render::instancetable, ListBase::last, ObjectRen::mcol, MEM_freeN(), ObjectRen::mtface, ObjectInstanceRen::next, ObjectRen::next, NULL, Render::objectinstance, Render::objecttable, ObjectRen::rayfaces, ObjectRen::rayprimitives, ObjectRen::raytree, ObjectInstanceRen::raytree, RE_rayobject_free(), Render::sortedhalos, ObjectRen::strandbuf, ObjectRen::strandnodes, ObjectRen::strandnodeslen, Render::totinstance, ObjectRen::totvlak, ObjectInstanceRen::vectors, StrandBuffer::vert, ObjectRen::vertnodes, ObjectRen::vertnodeslen, ObjectRen::vlaknodes, and ObjectRen::vlaknodeslen.
Referenced by RE_Database_Free(), and RE_FreeRender().
void free_renderdata_vertnodes (struct VertTableNode * vertnodes)
Definition at line 732 of file renderdatabase.c.
References MEM_freeN(), NULL, and VertTableNode::vert.
Referenced by free_renderdata_tables().
void free_renderdata_vlaknodes (struct VlakTableNode * vlaknodes)
Definition at line 758 of file renderdatabase.c.
References MEM_freeN(), NULL, and VlakTableNode::vlak.
Referenced by free_renderdata_tables().
void init_render_world (Render * re)
Definition at line 4005 of file convertblender.c.
References World::ao_gather_method, World::aosamp, Render::clipend, Render::clipsta, copy_m3_m4(), copy_v3_v3(), World::exp, World::fastcol, Render::grvec, World::horb, World::horg, World::horr, Render::imat, World::linfac, logf, World::logfac, MAX_MTEX, World::misi, World::mistdist, World::miststa, RenderData::mode, World::mode, World::mtex, normalize_v3(), Render::osa, powf, Render::r, R_RAYTRACE, World::range, Render::scene, World::skytype, MTex::tex, Render::viewinv, Render::viewmat, WO_AMB_OCC, WO_AOGATHER_RAYTRACE, WO_ENV_LIGHT, WO_INDIRECT_LIGHT, WO_SKYTEX, Scene::world, and Render::wrld.
Referenced by RE_Database_Baking(), RE_Database_FromScene(), and render_envmap().
void project_renderdata (struct Render * re, void(*)(const float *, float mat[][4], float *) projectfunc, int do_pano, float xoffs, int do_buckets)
Referenced by add_halo_flare(), database_fromscene_vectors(), find_next_pano_slice(), RE_DataBase_ApplyWindow(), RE_Database_FromScene(), and render_envmap().
struct ObjectInstanceRen* RE_addRenderInstance (struct Render * re, struct ObjectRen * obr, struct Object * ob, struct Object * par, int index, int psysindex, float mat[][4], int lay) [read]
Definition at line 1324 of file renderdatabase.c.
References BLI_addtail(), copy_m3_m4(), copy_m4_m4(), ObjectInstanceRen::flag, ObjectInstanceRen::index, Render::instancetable, invert_m3_m3(), ObjectInstanceRen::lay, ObjectInstanceRen::mat, MEM_callocN(), ObjectInstanceRen::nmat, ObjectInstanceRen::ob, ObjectInstanceRen::obr, ObjectInstanceRen::par, ObjectInstanceRen::psysindex, R_DUPLI_TRANSFORMED, and transpose_m3().
Referenced by add_render_object(), and database_init_objects().
struct ObjectRen* RE_addRenderObject (struct Render * re, struct Object * ob, struct Object * par, int index, int psysindex, int lay) [read]
Definition at line 718 of file renderdatabase.c.
References BLI_addtail(), ObjectRen::index, ObjectRen::lay, MEM_callocN(), ObjectRen::ob, Render::objecttable, ObjectRen::par, and ObjectRen::psysindex.
Referenced by add_render_object(), and RE_make_stars().
struct StrandBuffer* RE_addStrandBuffer (struct ObjectRen * obr, int totvert) [read]
Definition at line 702 of file renderdatabase.c.
References MEM_callocN(), StrandBuffer::obr, ObjectRen::strandbuf, StrandBuffer::totvert, and StrandBuffer::vert.
Referenced by render_new_particle_system().
void RE_Database_FromScene_Vectors (Render * re, struct Main * bmain, struct Scene * sce, unsigned int lay)
Definition at line 5572 of file convertblender.c.
References calculate_speedvectors(), copy_dbase_object_vectors(), database_fromscene_vectors(), eModifierType_Fluidsim, ListBase::first, free_dbase_object_vectors(), FluidsimModifierData::fss, get_vector_renderlayers(), Render::i, Object::id, ObjectInstanceRen::index, RenderStats::infostr, Render::instancetable, ObjectInstanceRen::lay, load_fluidsimspeedvectors(), MEM_freeN(), RenderData::mode, modifiers_findByType(), ID::name, ObjectInstanceRen::next, StrandSurface::next, StrandSurface::nextco, NULL, ObjectInstanceRen::ob, OB_FLUIDSIM_DOMAIN, ObjectInstanceRen::obr, ObjectInstanceRen::par, StrandSurface::prevco, ObjectInstanceRen::psysindex, Render::r, R_SPEED, RE_Database_Free(), RE_Database_FromScene(), Render::scene, Render::sdh, speedvector_project(), Render::stats_draw, step(), Render::strandsurface, table, Render::tbh, Render::test_break, ObjectInstanceRen::totvector, ObjectRen::totvert, FluidsimSettings::type, and ObjectInstanceRen::vectors.
Referenced by do_render_3d().
struct HaloRen* RE_findOrAddHalo (struct ObjectRen * obr, int nr) [read]
Definition at line 901 of file renderdatabase.c.
References ObjectRen::bloha, ObjectRen::blohalen, MEM_callocN(), MEM_freeN(), NULL, and TABLEINITSIZE.
Referenced by initstar(), RE_inithalo(), and RE_inithalo_particle().
struct StrandRen* RE_findOrAddStrand (struct ObjectRen * obr, int nr) [read]
Definition at line 664 of file renderdatabase.c.
References i, MEM_callocN(), MEM_freeN(), MEM_mallocN(), NULL, StrandTableNode::strand, ObjectRen::strandnodes, ObjectRen::strandnodeslen, and TABLEINITSIZE.
Referenced by deep_alpha(), finalize_render_object(), render_new_particle_system(), shade_strand_samples(), unref_strand_samples(), zbuffer_shadow(), and zbuffer_strands_abuf().
struct VertRen* RE_findOrAddVert (struct ObjectRen * obr, int nr) [read]
Definition at line 250 of file renderdatabase.c.
References i, VertRen::index, MEM_callocN(), MEM_freeN(), MEM_mallocN(), NULL, TABLEINITSIZE, VertTableNode::vert, ObjectRen::vertnodes, and ObjectRen::vertnodeslen.
Referenced by autosmooth(), calc_edge_stress(), calc_vertexnormals(), dl_surf_to_renderdata(), do_displacement(), init_render_curve(), init_render_dm(), init_render_mball(), init_render_mesh(), particle_billboard(), RE_vertren_copy(), shadowbuf_autoclip(), static_particle_strand(), and static_particle_wire().
struct VlakRen* RE_findOrAddVlak (struct ObjectRen * obr, int nr) [read]
Definition at line 493 of file renderdatabase.c.
References i, MEM_callocN(), MEM_freeN(), MEM_mallocN(), NULL, TABLEINITSIZE, VlakTableNode::vlak, ObjectRen::vlaknodes, and ObjectRen::vlaknodeslen.
Referenced by autosmooth(), calc_edge_stress(), calc_vertexnormals(), check_non_flat_quads(), deep_alpha(), dl_surf_to_renderdata(), do_displacement(), get_next_bake_face(), GetNormal(), GetNumVertsOfFace(), GetPosition(), GetTextureCoordinate(), init_render_curve(), init_render_dm(), init_render_mball(), init_render_mesh(), isb_make_buffer(), isb_make_buffer_transp(), occ_build_shade(), occ_face(), occ_form_factor(), particle_billboard(), RE_vlakren_copy(), set_fullsample_trace_flag(), set_phong_threshold(), SetTSpace(), shade_input_set_triangle(), split_quads(), split_v_renderfaces(), static_particle_strand(), static_particle_wire(), and zbufshade_sss_tile().
struct HaloRen* RE_inithalo (struct Render * re, struct ObjectRen * obr, struct Material * ma, float * vec, float * vec1, float * orco, float hasize, float vectsize, int seed) [read]
Definition at line 935 of file renderdatabase.c.
References Material::add, HaloRen::add, HaloRen::alfa, Material::alpha, KDL::atan2(), Material::b, HaloRen::b, HaloRen::co, MTex::colfac, copy_v3_v3(), HaloRen::cos, cos(), externtex(), HaloRen::flarec, Material::flarec, Material::g, HaloRen::g, HA_VECT, HA_XALPHA, Material::har, HaloRen::hard, HaloRen::hasize, if(), len_v3v3(), Material::linec, HaloRen::linec, MA_HALO_FLARE, MA_HALO_LINES, MA_HALO_RINGS, MA_HALO_XALPHA, MA_HALOTEX, MA_STAR, MAP_ALPHA, MAP_COL, MTex::mapto, HaloRen::mat, Material::mode, Material::mtex, HaloRen::no, normalize_v3(), NULL, projectverto(), Material::r, HaloRen::r, RE_findOrAddHalo(), Material::ringc, HaloRen::ringc, HaloRen::seed, Material::septex, HaloRen::sin, sin(), Material::starc, HaloRen::starpoints, sub_v3_v3v3(), HaloRen::tex, MTex::texco, TEXCO_NORM, TEXCO_OBJECT, TEXCO_UV, ObjectRen::tothalo, HaloRen::type, Render::winmat, Render::winx, Render::winy, HaloRen::xs, HaloRen::ys, HaloRen::zBufDist, and HaloRen::zs.
Referenced by make_render_halos().
struct HaloRen* RE_inithalo_particle (struct Render * re, struct ObjectRen * obr, struct DerivedMesh * dm, struct Material * ma, float * vec, float * vec1, float * orco, float * uvco, float hasize, float vectsize, int seed, float * pa_co) [read]
Definition at line 1048 of file renderdatabase.c.
References Material::add, add(), HaloRen::add, HaloRen::alfa, Material::alpha, MTex::alphafac, KDL::atan2(), Material::b, HaloRen::b, MTex::blendtype, CD_MTFACE, CLAMP(), HaloRen::co, MTex::colfac, copy_v3_v3(), HaloRen::cos, cos(), CustomData_get_active_layer_index(), CustomData_get_layer_index(), CustomData_get_named_layer_index(), MTex::def_var, externtex(), DerivedMesh::faceData, HaloRen::flarec, Material::flarec, Material::g, HaloRen::g, HA_VECT, HA_XALPHA, Material::har, HaloRen::hard, MTex::hardfac, HaloRen::hasize, i, Object::imat_ren, len_v3v3(), Material::linec, HaloRen::linec, MA_HALO_FLARE, MA_HALO_LINES, MA_HALO_RINGS, MA_HALO_XALPHA, MA_HALOTEX, MA_STAR, MAP_ALPHA, MAP_COL, MAP_HAR, MAP_RAYMIRR, MAP_TRANSLU, MTex::mapto, HaloRen::mat, MAX_MTEX, Material::mode, Material::mtex, mul_m4_v3(), HaloRen::no, normalize_v3(), NULL, MTex::object, projectverto(), Material::r, HaloRen::r, MTex::raymirrfac, RE_findOrAddHalo(), Material::ringc, HaloRen::ringc, HaloRen::seed, Material::septex, HaloRen::sin, sin(), Material::starc, HaloRen::starpoints, sub_v3_v3v3(), HaloRen::tex, MTex::texco, TEXCO_GLOB, TEXCO_NORM, TEXCO_OBJECT, TEXCO_PARTICLE, TEXCO_UV, texture_rgb_blend(), texture_value_blend(), ObjectRen::tothalo, MTex::translfac, HaloRen::type, MTex::uvname, Render::winmat, Render::winx, Render::winy, HaloRen::xs, HaloRen::ys, HaloRen::zBufDist, and HaloRen::zs.
Referenced by particle_curve(), and particle_normal_ren().
void RE_makeRenderInstances (struct Render * re)
Definition at line 1350 of file renderdatabase.c.
References BLI_addtail(), BLI_countlist(), BLI_freelistN(), ListBase::first, Render::instancetable, ListBase::last, MEM_callocN(), ObjectInstanceRen::next, NULL, Render::objectinstance, ObjectInstanceRen::obr, ObjectInstanceRen::prev, and Render::totinstance.
Referenced by database_init_objects().
void RE_set_customdata_names (struct ObjectRen * obr, struct CustomData * data)
Definition at line 460 of file renderdatabase.c.
References CustomDataLayer::active, CustomDataLayer::active_rnd, ObjectRen::actmcol, ObjectRen::actmtface, ObjectRen::bakemtface, BLI_strncpy(), CD_MCOL, CD_MTFACE, CLAMPIS, CustomData_has_layer(), CustomData_number_of_layers(), i, CustomData::layers, ObjectRen::mcol, MEM_callocN(), ObjectRen::mtface, CustomDataLayer::name, CustomData::totlayer, and CustomDataLayer::type.
Referenced by init_render_dm(), init_render_mesh(), and render_new_particle_system().
int* RE_strandren_get_face (struct ObjectRen * obr, struct StrandRen * strand, int verify)
Definition at line 631 of file renderdatabase.c.
References StrandTableNode::face, StrandRen::index, MEM_callocN(), NULL, RE_FACE_ELEMS, and ObjectRen::strandnodes.
Referenced by calculate_speedvectors(), render_new_particle_system(), and sample_occ_surface().
struct MCol* RE_strandren_get_mcol (struct ObjectRen * obr, struct StrandRen * strand, int n, char ** name, int verify) [read]
Definition at line 582 of file renderdatabase.c.
References StrandRen::index, ObjectRen::mcol, StrandTableNode::mcol, MEM_callocN(), MEM_freeN(), NULL, RE_MCOL_ELEMS, size(), ObjectRen::strandnodes, and StrandTableNode::totmcol.
Referenced by render_new_particle_system(), and shade_input_set_strand_texco().
float* RE_strandren_get_simplify (struct ObjectRen * obr, struct StrandRen * strand, int verify)
Definition at line 616 of file renderdatabase.c.
References StrandRen::index, MEM_callocN(), NULL, RE_SIMPLIFY_ELEMS, StrandTableNode::simplify, and ObjectRen::strandnodes.
Referenced by render_new_particle_system(), and strand_eval_point().
float* RE_strandren_get_surfnor (struct ObjectRen * obr, struct StrandRen * strand, int verify)
Definition at line 533 of file renderdatabase.c.
References StrandRen::index, MEM_callocN(), NULL, RE_SURFNOR_ELEMS, ObjectRen::strandnodes, and StrandTableNode::surfnor.
Referenced by render_new_particle_system(), and shade_input_set_strand_texco().
float* RE_strandren_get_uv (struct ObjectRen * obr, struct StrandRen * strand, int n, char ** name, int verify)
Definition at line 548 of file renderdatabase.c.
References StrandRen::index, MEM_callocN(), MEM_freeN(), ObjectRen::mtface, NULL, RE_UV_ELEMS, size(), ObjectRen::strandnodes, StrandTableNode::totuv, and StrandTableNode::uv.
Referenced by render_new_particle_system(), and shade_input_set_strand_texco().
float* RE_strandren_get_winspeed (struct ObjectInstanceRen * obi, struct StrandRen * strand, int verify)
Definition at line 647 of file renderdatabase.c.
References StrandRen::index, MEM_callocN(), NULL, ObjectInstanceRen::obr, RE_WINSPEED_ELEMS, ObjectRen::totstrand, ObjectRen::totvert, and ObjectInstanceRen::vectors.
Referenced by calculate_speedvectors(), and shade_input_set_strand_texco().
struct VertRen* RE_vertren_copy (struct ObjectRen * obr, struct VertRen * ver) [read]
Definition at line 213 of file renderdatabase.c.
References VertRen::index, RE_findOrAddVert(), RE_RAD_ELEMS, RE_STICKY_ELEMS, RE_STRAND_ELEMS, RE_STRESS_ELEMS, RE_TANGENT_ELEMS, RE_vertren_get_rad(), RE_vertren_get_sticky(), RE_vertren_get_strand(), RE_vertren_get_stress(), RE_vertren_get_tangent(), and ObjectRen::totvert.
Referenced by autosmooth(), and split_v_renderfaces().
float* RE_vertren_get_rad (struct ObjectRen * obr, struct VertRen * ver, int verify)
Definition at line 148 of file renderdatabase.c.
References VertRen::index, MEM_callocN(), NULL, VertTableNode::rad, RE_RAD_ELEMS, and ObjectRen::vertnodes.
Referenced by RE_vertren_copy().
float* RE_vertren_get_sticky (struct ObjectRen * obr, struct VertRen * ver, int verify)
Definition at line 117 of file renderdatabase.c.
References VertRen::index, MEM_mallocN(), NULL, RE_STICKY_ELEMS, VertTableNode::sticky, and ObjectRen::vertnodes.
Referenced by displace_render_vert(), init_render_mesh(), RE_vertren_copy(), and shade_input_set_shade_texco().
float* RE_vertren_get_strand (struct ObjectRen * obr, struct VertRen * ver, int verify)
Definition at line 163 of file renderdatabase.c.
References VertRen::index, MEM_mallocN(), NULL, RE_STRAND_ELEMS, VertTableNode::strand, and ObjectRen::vertnodes.
Referenced by RE_vertren_copy().
float* RE_vertren_get_stress (struct ObjectRen * obr, struct VertRen * ver, int verify)
Definition at line 132 of file renderdatabase.c.
References VertRen::index, MEM_mallocN(), NULL, RE_STRESS_ELEMS, VertTableNode::stress, and ObjectRen::vertnodes.
Referenced by calc_edge_stress(), displace_render_vert(), RE_vertren_copy(), and shade_input_set_shade_texco().
float* RE_vertren_get_tangent (struct ObjectRen * obr, struct VertRen * ver, int verify)
Definition at line 179 of file renderdatabase.c.
References VertRen::index, MEM_callocN(), NULL, RE_TANGENT_ELEMS, VertTableNode::tangent, and ObjectRen::vertnodes.
Referenced by calc_tangent_vector(), calc_vertexnormals(), RE_vertren_copy(), and shade_input_set_shade_texco().
float* RE_vertren_get_winspeed (struct ObjectInstanceRen * obi, struct VertRen * ver, int verify)
Definition at line 196 of file renderdatabase.c.
References VertRen::index, MEM_callocN(), NULL, ObjectInstanceRen::obr, RE_WINSPEED_ELEMS, ObjectRen::totstrand, ObjectRen::totvert, and ObjectInstanceRen::vectors.
Referenced by calculate_speedvectors(), load_fluidsimspeedvectors(), and shade_input_set_shade_texco().
struct VlakRen* RE_vlakren_copy (struct ObjectRen * obr, struct VlakRen * vlr) [read]
Definition at line 403 of file renderdatabase.c.
References copy_v3_v3(), i, VlakRen::index, NULL, RE_findOrAddVlak(), RE_MCOL_ELEMS, RE_MTFACE_ELEMS, RE_NMAP_TANGENT_ELEMS, RE_vlakren_get_mcol(), RE_vlakren_get_nmap_tangent(), RE_vlakren_get_radface(), RE_vlakren_get_surfnor(), RE_vlakren_get_tface(), and ObjectRen::totvlak.
Referenced by check_non_flat_quads(), and split_quads().
struct MCol* RE_vlakren_get_mcol (struct ObjectRen * obr, VlakRen * ren, int n, char ** name, int verify) [read]
Definition at line 324 of file renderdatabase.c.
References VlakRen::index, ObjectRen::mcol, VlakTableNode::mcol, MEM_callocN(), MEM_freeN(), NULL, RE_MCOL_ELEMS, size(), VlakTableNode::totmcol, and ObjectRen::vlaknodes.
Referenced by init_render_dm(), init_render_mesh(), RE_vlakren_copy(), shade_input_set_shade_texco(), static_particle_strand(), and use_mesh_edge_lookup().
float* RE_vlakren_get_nmap_tangent (struct ObjectRen * obr, VlakRen * ren, int verify)
Definition at line 373 of file renderdatabase.c.
References VlakRen::index, MEM_callocN(), NULL, RE_NMAP_TANGENT_ELEMS, VlakTableNode::tangent, and ObjectRen::vlaknodes.
Referenced by calc_vertexnormals(), init_render_mesh(), RE_vlakren_copy(), SetTSpace(), and shade_input_set_shade_texco().
void RE_vlakren_get_normal (struct Render * re, struct ObjectInstanceRen * obi, struct VlakRen * vlr, float * nor)
Referenced by shade_input_set_triangle_i(), and viewpixel_to_lampbuf().
RadFace** RE_vlakren_get_radface (struct ObjectRen * obr, VlakRen * ren, int verify)
Definition at line 388 of file renderdatabase.c.
References VlakRen::index, MEM_callocN(), NULL, VlakTableNode::radface, RE_RADFACE_ELEMS, and ObjectRen::vlaknodes.
Referenced by RE_vlakren_copy().
float* RE_vlakren_get_surfnor (struct ObjectRen * obr, VlakRen * ren, int verify)
Definition at line 358 of file renderdatabase.c.
References VlakRen::index, MEM_callocN(), NULL, RE_SURFNOR_ELEMS, VlakTableNode::surfnor, and ObjectRen::vlaknodes.
Referenced by RE_vlakren_copy(), shade_input_set_shade_texco(), and static_particle_strand().
struct MTFace* RE_vlakren_get_tface (struct ObjectRen * obr, VlakRen * ren, int n, char ** name, int verify) [read]
Definition at line 290 of file renderdatabase.c.
References VlakRen::index, MEM_callocN(), MEM_freeN(), ObjectRen::mtface, VlakTableNode::mtface, NULL, size(), VlakTableNode::totmtface, and ObjectRen::vlaknodes.
Referenced by calc_tangent_vector(), calc_vertexnormals(), compatible_bump_uv_derivs(), displace_render_vert(), get_next_bake_face(), GetTextureCoordinate(), init_render_dm(), init_render_mesh(), particle_billboard(), RE_vlakren_copy(), shade_input_set_shade_texco(), shade_tface(), static_particle_strand(), and use_mesh_edge_lookup().