Blender: MT_Quaternion Class Reference
MT_Quaternion Class Reference
#include <MT_Quaternion.h>
Public Member Functions
MT_Quaternion ()
MT_Quaternion (const MT_Vector4 &v)
MT_Quaternion (const float v[4])
MT_Quaternion (const double v[4])
MT_Quaternion (MT_Scalar xx, MT_Scalar yy, MT_Scalar zz, MT_Scalar ww)
MT_Quaternion (const MT_Vector3 &axis, MT_Scalar mt_angle)
MT_Quaternion (MT_Scalar yaw, MT_Scalar pitch, MT_Scalar roll)
void setRotation (const MT_Vector3 &axis, MT_Scalar mt_angle)
void setEuler (MT_Scalar yaw, MT_Scalar pitch, MT_Scalar roll)
MT_Quaternion & operator*= (const MT_Quaternion &q)
void conjugate ()
MT_Quaternion conjugate () const
void invert ()
MT_Quaternion inverse () const
MT_Scalar angle (const MT_Quaternion &q) const
MT_Quaternion slerp (const MT_Quaternion &q, const MT_Scalar &t) const
Static Public Member Functions
static MT_Quaternion random ()
Detailed Description
Definition at line 55 of file MT_Quaternion.h.
Constructor & Destructor Documentation
MT_Quaternion::MT_Quaternion () [inline]
Definition at line 57 of file MT_Quaternion.h.
Referenced by conjugate(), and random().
MT_Quaternion::MT_Quaternion (const MT_Vector4 & v) [inline]
Definition at line 58 of file MT_Quaternion.h.
MT_Quaternion::MT_Quaternion (const float v[4]) [inline]
Definition at line 59 of file MT_Quaternion.h.
MT_Quaternion::MT_Quaternion (const double v[4]) [inline]
Definition at line 60 of file MT_Quaternion.h.
MT_Quaternion::MT_Quaternion (MT_Scalar xx, MT_Scalar yy, MT_Scalar zz, MT_Scalar ww) [inline]
Definition at line 61 of file MT_Quaternion.h.
MT_Quaternion::MT_Quaternion (const MT_Vector3 & axis, MT_Scalar mt_angle) [inline]
Definition at line 63 of file MT_Quaternion.h.
References setRotation().
MT_Quaternion::MT_Quaternion (MT_Scalar yaw, MT_Scalar pitch, MT_Scalar roll) [inline]
Definition at line 66 of file MT_Quaternion.h.
References setEuler().
Member Function Documentation
GEN_INLINE MT_Scalar MT_Quaternion::angle (const MT_Quaternion & q) const
Definition at line 63 of file MT_Quaternion.inl.
References acos(), assert, MT_Vector4::dot(), MT_Vector4::length2(), MT_clamp(), and sqrt().
GEN_INLINE void MT_Quaternion::conjugate ()
Definition at line 11 of file MT_Quaternion.inl.
References MT_Tuple4::m_co.
Referenced by inverse(), and invert().
GEN_INLINE MT_Quaternion MT_Quaternion::conjugate () const
Definition at line 15 of file MT_Quaternion.inl.
References MT_Tuple4::m_co, and MT_Quaternion().
GEN_INLINE MT_Quaternion MT_Quaternion::inverse () const
Definition at line 24 of file MT_Quaternion.inl.
References conjugate(), and MT_Vector4::length2().
GEN_INLINE void MT_Quaternion::invert ()
Definition at line 19 of file MT_Quaternion.inl.
References conjugate(), and MT_Vector4::length2().
GEN_INLINE MT_Quaternion & MT_Quaternion::operator*= (const MT_Quaternion & q)
Definition at line 3 of file MT_Quaternion.inl.
References MT_Tuple4::m_co, and MT_Tuple4::setValue().
GEN_INLINE MT_Quaternion MT_Quaternion::random () [static]
Definition at line 30 of file MT_Quaternion.inl.
References cos(), MT_2_PI(), MT_Quaternion(), MT_random(), sin(), and sqrt().
void MT_Quaternion::setEuler (MT_Scalar yaw, MT_Scalar pitch, MT_Scalar roll) [inline]
Definition at line 78 of file MT_Quaternion.h.
References cos(), MT_Tuple4::setValue(), and sin().
Referenced by main(), and MT_Quaternion().
void MT_Quaternion::setRotation (const MT_Vector3 & axis, MT_Scalar mt_angle) [inline]
Definition at line 70 of file MT_Quaternion.h.
References cos(), MT_Vector3::length(), MT_assert, MT_fuzzyZero(), MT_Tuple4::setValue(), and sin().
Referenced by MT_Quaternion().
GEN_INLINE MT_Quaternion MT_Quaternion::slerp (const MT_Quaternion & q, const MT_Scalar & t) const
Definition at line 75 of file MT_Quaternion.inl.
References acos(), MT_Vector4::dot(), and sin().
Referenced by KX_SlowParentRelation::UpdateChildCoordinates().
The documentation for this class was generated from the following files:
MT_Quaternion.h
MT_Quaternion.inl