Blender: AUD_ChannelMapperReader Class Reference
AUD_ChannelMapperReader Class Reference
#include <AUD_ChannelMapperReader.h>
Public Member Functions
AUD_ChannelMapperReader (AUD_Reference< AUD_IReader > reader, AUD_Channels channels)
~AUD_ChannelMapperReader ()
void setChannels (AUD_Channels channels)
void setMonoAngle (float angle)
virtual AUD_Specs getSpecs () const
virtual void read (int &length, bool &eos, sample_t *buffer)
Detailed Description
This class maps a sound source's channels to a specific output channel count.
Note:
The input sample format must be float.
Definition at line 40 of file AUD_ChannelMapperReader.h.
Constructor & Destructor Documentation
AUD_ChannelMapperReader::AUD_ChannelMapperReader (AUD_Reference< AUD_IReader > reader, AUD_Channels channels)
Creates a channel mapper reader.
Parameters:
reader The reader to map.
mapping The mapping specification as two dimensional float array.
Definition at line 41 of file AUD_ChannelMapperReader.cpp.
AUD_ChannelMapperReader::~AUD_ChannelMapperReader ()
Destroys the reader.
Definition at line 48 of file AUD_ChannelMapperReader.cpp.
Member Function Documentation
AUD_Specs AUD_ChannelMapperReader::getSpecs () const [virtual]
Returns the specification of the reader.
Returns:
The AUD_Specs structure.
Reimplemented from AUD_EffectReader.
Definition at line 168 of file AUD_ChannelMapperReader.cpp.
References AUD_Specs::channels, and AUD_EffectReader::m_reader.
void AUD_ChannelMapperReader::read (int & length, bool & eos, sample_t * buffer) [virtual]
Request to read the next length samples out of the source. The buffer supplied has the needed size.
Parameters:
[in,out] length The count of samples that should be read. Shall contain the real count of samples after reading, in case there were only fewer samples available. A smaller value also indicates the end of the reader.
[out] eos End of stream, whether the end is reached or not.
[in] buffer The pointer to the buffer to read into.
Reimplemented from AUD_EffectReader.
Definition at line 175 of file AUD_ChannelMapperReader.cpp.
References AUD_Buffer::assureSize(), AUD_Buffer::getBuffer(), i, length(), AUD_EffectReader::m_reader, and sum().
void AUD_ChannelMapperReader::setChannels (AUD_Channels channels)
Sets the requested channel output count.
Parameters:
channels The channel output count.
Definition at line 53 of file AUD_ChannelMapperReader.cpp.
void AUD_ChannelMapperReader::setMonoAngle (float angle)
Sets the angle for mono sources.
Parameters:
angle The angle for mono sources.
Definition at line 59 of file AUD_ChannelMapperReader.cpp.
References angle(), and AUD_CHANNELS_MONO.
The documentation for this class was generated from the following files:
AUD_ChannelMapperReader.h
AUD_ChannelMapperReader.cpp