Blender: KDL::Twist Class Reference
KDL::Twist Class Reference
represents both translational and rotational velocities.
#include <frames.hpp>
Public Member Functions
Twist ()
The default constructor initialises to Zero via the constructor of Vector.
Twist (const Vector &_vel, const Vector &_rot)
Twist & operator-= (const Twist &arg)
Twist & operator+= (const Twist &arg)
double & operator() (int i)
index-based access to components, first vel(0..2), then rot(3..5)
double operator() (int i) const
double operator[] (int index) const
double & operator[] (int index)
void ReverseSign ()
Reverses the sign of the twist.
Twist RefPoint (const Vector &v_base_AB) const
Static Public Member Functions
static Twist Zero ()
Public Attributes
Vector vel
The velocity of that point.
Vector rot
The rotational velocity of that point.
Friends
class Rotation
class Frame
Twist operator* (const Twist &lhs, double rhs)
Twist operator* (double lhs, const Twist &rhs)
Twist operator/ (const Twist &lhs, double rhs)
Twist operator+ (const Twist &lhs, const Twist &rhs)
Twist operator- (const Twist &lhs, const Twist &rhs)
Twist operator- (const Twist &arg)
double dot (const Twist &lhs, const Wrench &rhs)
double dot (const Wrench &rhs, const Twist &lhs)
void SetToZero (Twist &v)
bool Equal (const Twist &a, const Twist &b, double eps=epsilon)
bool operator== (const Twist &a, const Twist &b)
The literal equality operator==(), also identical.
bool operator!= (const Twist &a, const Twist &b)
The literal inequality operator!=().
Detailed Description
represents both translational and rotational velocities.
This class represents a twist. A twist is the combination of translational velocity and rotational velocity applied at one point.
Definition at line 677 of file frames.hpp.
Constructor & Destructor Documentation
KDL::Twist::Twist () [inline]
The default constructor initialises to Zero via the constructor of Vector.
Definition at line 684 of file frames.hpp.
KDL::Twist::Twist (const Vector & _vel, const Vector & _rot) [inline]
Definition at line 686 of file frames.hpp.
Member Function Documentation
double & Twist::operator() (int i) [inline]
index-based access to components, first vel(0..2), then rot(3..5)
Definition at line 338 of file frames.inl.
References rot.
Referenced by operator[]().
double KDL::Twist::operator() (int i) const [inline]
index-based access to components, first vel(0..2), then rot(3..5) For use with a const Twist
Twist& KDL::Twist::operator+= (const Twist & arg) [inline]
Twist& KDL::Twist::operator-= (const Twist & arg) [inline]
double KDL::Twist::operator[] (int index) const [inline]
Definition at line 697 of file frames.hpp.
References operator()().
double& KDL::Twist::operator[] (int index) [inline]
Definition at line 702 of file frames.hpp.
References operator()().
Twist KDL::Twist::RefPoint (const Vector & v_base_AB) const [inline]
Changes the reference point of the twist. The vector v_base_AB is expressed in the same base as the twist The vector v_base_AB is a vector from the old point to the new point.
Complexity : 6M+6A
Referenced by KDL::changeRefPoint(), iTaSC::ConstraintSet::closeLoop(), KDL::ChainJntToJacSolver::JntToJac(), KDL::TreeJntToJacSolver::JntToJac(), and KDL::Segment::twist().
void KDL::Twist::ReverseSign () [inline]
Reverses the sign of the twist.
static Twist KDL::Twist::Zero () [inline, static]
Returns:
a zero Twist : Twist(Vector::Zero(),Vector::Zero())
Referenced by KDL::Joint::twist(), and iTaSC::MovingFrame::updateCoordinates().
Friends And Related Function Documentation
double dot (const Twist & lhs, const Wrench & rhs) [friend]
double dot (const Wrench & rhs, const Twist & lhs) [friend]
bool Equal (const Twist & a, const Twist & b, double eps = epsilon) [friend]
do not use operator == because the definition of Equal(.,.) is slightly different. It compares whether the 2 arguments are equal in an eps-interval
friend class Frame [friend]
Definition at line 744 of file frames.hpp.
bool operator!= (const Twist & a, const Twist & b) [friend]
The literal inequality operator!=().
Twist operator* (double lhs, const Twist & rhs) [friend]
Twist operator* (const Twist & lhs, double rhs) [friend]
Twist operator+ (const Twist & lhs, const Twist & rhs) [friend]
Twist operator- (const Twist & arg) [friend]
Twist operator- (const Twist & lhs, const Twist & rhs) [friend]
Twist operator/ (const Twist & lhs, double rhs) [friend]
bool operator== (const Twist & a, const Twist & b) [friend]
The literal equality operator==(), also identical.
friend class Rotation [friend]
Definition at line 743 of file frames.hpp.
void SetToZero (Twist & v) [friend]
Member Data Documentation
Vector KDL::Twist::rot
The rotational velocity of that point.
Definition at line 680 of file frames.hpp.
Referenced by iTaSC::CopyPose::getControlParameters(), iTaSC::Armature::getMaxEndEffectorChange(), KDL::Frame2::Integrate(), KDL::operator<<(), KDL::operator>>(), and iTaSC::CopyPose::updateControlOutput().
Vector KDL::Twist::vel
The velocity of that point.
Definition at line 679 of file frames.hpp.
Referenced by iTaSC::CopyPose::getControlParameters(), iTaSC::Armature::getMaxEndEffectorChange(), KDL::Frame2::Integrate(), KDL::operator<<(), KDL::operator>>(), and iTaSC::CopyPose::updateControlOutput().
The documentation for this class was generated from the following files:
frames.hpp
frames.inl