Blender: Cache Class Reference
Cache Class Reference
#include <util_cache.h>
Public Member Functions
void insert (CacheData &key, CacheData &value)
bool lookup (CacheData &key, CacheData &value)
void clear_except (const string &name, const set< string > &except)
Static Public Attributes
static Cache global
Protected Member Functions
string data_filename (CacheData &key)
Detailed Description
Definition at line 152 of file util_cache.h.
Member Function Documentation
void Cache::clear_except (const string & name, const set< string > & except)
Definition at line 112 of file util_cache.cpp.
References path_user_get().
Referenced by BVH::clear_cache_except().
string Cache::data_filename (CacheData & key) [protected]
Definition at line 71 of file util_cache.cpp.
References CacheData::get_filename(), path_join(), and path_user_get().
Referenced by insert(), and lookup().
void Cache::insert (CacheData & key, CacheData & value)
Definition at line 76 of file util_cache.cpp.
References CacheData::buffers, CacheBuffer::data, data_filename(), path_create_directories(), and CacheBuffer::size.
Referenced by BVH::cache_write().
bool Cache::lookup (CacheData & key, CacheData & value)
Definition at line 98 of file util_cache.cpp.
References data_filename(), CacheData::f, and CacheData::name.
Member Data Documentation
Cache Cache::global [static]
Definition at line 154 of file util_cache.h.
Referenced by BVH::cache_read(), BVH::cache_write(), and BVH::clear_cache_except().
The documentation for this class was generated from the following files:
util_cache.h
util_cache.cpp