Blender: bmo_connect.c File Reference
bmo_connect.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_array.h"
#include "BLI_utildefines.h"
#include "bmesh.h"
#include "intern/bmesh_operators_private.h"
Defines
#define VERT_INPUT 1
#define EDGE_OUT 1
#define FACE_NEW 2
#define EDGE_MARK 4
#define EDGE_DONE 8
#define ARRAY_SWAP(elemtype, arr1, arr2)
Functions
void bmo_connectverts_exec (BMesh *bm, BMOperator *op)
static BMVert * get_outer_vert (BMesh *bm, BMEdge *e)
static int clamp_index (const int x, const int len)
static void bm_vert_loop_pair (BMesh *bm, BMVert *v1, BMVert *v2, BMLoop **l1, BMLoop **l2)
void bmo_bridge_loops_exec (BMesh *bm, BMOperator *op)
Detailed Description
Definition in file bmo_connect.c.
Define Documentation
#define ARRAY_SWAP (elemtype, arr1, arr2)
Value:
{                                                                         \
        int i;                                                                \
        elemtype *arr_tmp = NULL;                                             \
        BLI_array_declare(arr_tmp);                                           \
        for (i = 0; i < BLI_array_count(arr1); i++) {                         \
            BLI_array_append(arr_tmp, arr1[i]);                               \
        }                                                                     \
        BLI_array_empty(arr1);                                                \
        for (i = 0; i < BLI_array_count(arr2); i++) {                         \
            BLI_array_append(arr1, arr2[i]);                                  \
        }                                                                     \
        BLI_array_empty(arr2);                                                \
        for (i = 0; i < BLI_array_count(arr_tmp); i++) {                      \
            BLI_array_append(arr2, arr_tmp[i]);                               \
        }                                                                     \
        BLI_array_free(arr_tmp);                                              \
    }
Definition at line 164 of file bmo_connect.c.
Referenced by bmo_bridge_loops_exec().
#define EDGE_DONE 8
Definition at line 41 of file bmo_connect.c.
Referenced by bmo_bridge_loops_exec().
#define EDGE_MARK 4
Definition at line 40 of file bmo_connect.c.
Referenced by bmo_bridge_loops_exec(), and get_outer_vert().
#define EDGE_OUT 1
Definition at line 38 of file bmo_connect.c.
Referenced by bmo_connectverts_exec(), and bmo_edgerotate_exec().
#define FACE_NEW 2
Definition at line 39 of file bmo_connect.c.
Referenced by bmo_connectverts_exec().
#define VERT_INPUT 1
Definition at line 37 of file bmo_connect.c.
Referenced by bmo_connectverts_exec().
Function Documentation
static void bm_vert_loop_pair (BMesh * bm, BMVert * v1, BMVert * v2, BMLoop ** l1, BMLoop ** l2) [static]
Definition at line 186 of file bmo_connect.c.
References BM_iter_at_index(), BM_ITER_ELEM, BM_LOOPS_OF_VERT, BMVert::e, BMEdge::l, BMLoop::next, BMLoop::prev, and BMLoop::v.
Referenced by bmo_bridge_loops_exec().
void bmo_bridge_loops_exec (BMesh * bm, BMOperator * op)
Definition at line 213 of file bmo_connect.c.
References ARRAY_SWAP, BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_free, BLI_assert, BM_EDGE, BM_edge_other_vert(), BM_EDGES_OF_VERT, BM_elem_attrs_copy(), BM_face_create_quad_tri(), BM_FACE_FIRST_LOOP, BM_ITER_ELEM, bm_vert_loop_pair(), BMERR_INVALID_SELECTION, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_error_raise(), BMO_ITER, BMO_slot_buffer_flag_enable(), clamp_index(), co, BMVert::co, EDGE_DONE, EDGE_MARK, BMLoop::f, get_outer_vert(), i, BMFace::len, len_squared_v3v3(), len_v3v3(), min, BMLoop::next, NULL, SWAP, TRUE, and BMEdge::v1.
void bmo_connectverts_exec (BMesh * bm, BMOperator * op)
Definition at line 43 of file bmo_connect.c.
References BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growone, BM_EDGE, BM_face_legal_splits(), BM_face_split(), BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BM_VERT, BMERR_CONNECTVERT_FAILED, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_error_raise(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMLoop::e, EDGE_OUT, FACE_NEW, FALSE, i, BMLoop::next, NULL, BMLoop::prev, BMLoop::v, and VERT_INPUT.
static int clamp_index (const int x, const int len) [static]
Definition at line 148 of file bmo_connect.c.
References len().
Referenced by bmo_bridge_loops_exec().
static BMVert* get_outer_vert (BMesh * bm, BMEdge * e) [static]
Definition at line 131 of file bmo_connect.c.
References BM_EDGES_OF_VERT, BM_ITER_ELEM, BMO_elem_flag_test, EDGE_MARK, i, BMEdge::v1, and BMEdge::v2.
Referenced by bmo_bridge_loops_exec().