Blender: RNA_access.h File Reference
RNA_access.h File Reference
RNA
#include <stdarg.h>
#include "RNA_types.h"
Defines
#define RNA_BEGIN(sptr, itemptr, propname)
#define RNA_END
#define RNA_PROP_BEGIN(sptr, itemptr, prop)
#define RNA_PROP_END
#define RNA_STRUCT_BEGIN(sptr, prop)
#define RNA_STRUCT_END
#define RNA_warning(format,...) _RNA_warning("%s: " format "\n", __FUNCTION__, __VA_ARGS__)
Functions
void RNA_main_pointer_create (struct Main *main, PointerRNA *r_ptr)
void RNA_id_pointer_create (struct ID *id, PointerRNA *r_ptr)
void RNA_pointer_create (struct ID *id, StructRNA *type, void *data, PointerRNA *r_ptr)
void RNA_blender_rna_pointer_create (PointerRNA *r_ptr)
void RNA_pointer_recast (PointerRNA *ptr, PointerRNA *r_ptr)
StructRNA * RNA_struct_find (const char *identifier)
const char * RNA_struct_identifier (StructRNA *type)
const char * RNA_struct_ui_name (StructRNA *type)
const char * RNA_struct_ui_description (StructRNA *type)
int RNA_struct_ui_icon (StructRNA *type)
PropertyRNA * RNA_struct_name_property (StructRNA *type)
PropertyRNA * RNA_struct_iterator_property (StructRNA *type)
StructRNA * RNA_struct_base (StructRNA *type)
int RNA_struct_is_ID (StructRNA *type)
int RNA_struct_is_a (StructRNA *type, StructRNA *srna)
int RNA_struct_undo_check (StructRNA *type)
StructRegisterFunc RNA_struct_register (StructRNA *type)
StructUnregisterFunc RNA_struct_unregister (StructRNA *type)
void ** RNA_struct_instance (PointerRNA *ptr)
void * RNA_struct_py_type_get (StructRNA *srna)
void RNA_struct_py_type_set (StructRNA *srna, void *py_type)
void * RNA_struct_blender_type_get (StructRNA *srna)
void RNA_struct_blender_type_set (StructRNA *srna, void *blender_type)
struct IDProperty * RNA_struct_idprops (PointerRNA *ptr, int create)
int RNA_struct_idprops_check (StructRNA *srna)
int RNA_struct_idprops_register_check (StructRNA *type)
int RNA_struct_idprops_unset (PointerRNA *ptr, const char *identifier)
PropertyRNA * RNA_struct_find_property (PointerRNA *ptr, const char *identifier)
int RNA_struct_contains_property (PointerRNA *ptr, PropertyRNA *prop_test)
struct ListBase * RNA_struct_type_properties (StructRNA *srna)
PropertyRNA * RNA_struct_type_find_property (StructRNA *srna, const char *identifier)
FunctionRNA * RNA_struct_find_function (PointerRNA *ptr, const char *identifier)
struct ListBase * RNA_struct_type_functions (StructRNA *srna)
char * RNA_struct_name_get_alloc (PointerRNA *ptr, char *fixedbuf, int fixedlen, int *r_len)
const char * RNA_property_identifier (PropertyRNA *prop)
const char * RNA_property_description (PropertyRNA *prop)
PropertyType RNA_property_type (PropertyRNA *prop)
PropertySubType RNA_property_subtype (PropertyRNA *prop)
PropertyUnit RNA_property_unit (PropertyRNA *prop)
int RNA_property_flag (PropertyRNA *prop)
void * RNA_property_py_data_get (PropertyRNA *prop)
int RNA_property_array_length (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_array_check (PropertyRNA *prop)
int RNA_property_multi_array_length (PointerRNA *ptr, PropertyRNA *prop, int dimension)
int RNA_property_array_dimension (PointerRNA *ptr, PropertyRNA *prop, int length[])
char RNA_property_array_item_char (PropertyRNA *prop, int index)
int RNA_property_array_item_index (PropertyRNA *prop, char name)
int RNA_property_string_maxlength (PropertyRNA *prop)
const char * RNA_property_ui_name (PropertyRNA *prop)
const char * RNA_property_ui_description (PropertyRNA *prop)
int RNA_property_ui_icon (PropertyRNA *prop)
void RNA_property_int_range (PointerRNA *ptr, PropertyRNA *prop, int *hardmin, int *hardmax)
void RNA_property_int_ui_range (PointerRNA *ptr, PropertyRNA *prop, int *softmin, int *softmax, int *step)
void RNA_property_float_range (PointerRNA *ptr, PropertyRNA *prop, float *hardmin, float *hardmax)
void RNA_property_float_ui_range (PointerRNA *ptr, PropertyRNA *prop, float *softmin, float *softmax, float *step, float *precision)
int RNA_property_float_clamp (PointerRNA *ptr, PropertyRNA *prop, float *value)
int RNA_property_int_clamp (PointerRNA *ptr, PropertyRNA *prop, int *value)
int RNA_enum_identifier (EnumPropertyItem *item, const int value, const char **identifier)
int RNA_enum_bitflag_identifiers (EnumPropertyItem *item, const int value, const char **identifier)
int RNA_enum_name (EnumPropertyItem *item, const int value, const char **name)
int RNA_enum_description (EnumPropertyItem *item, const int value, const char **description)
void RNA_property_enum_items (struct bContext *C, PointerRNA *ptr, PropertyRNA *prop, EnumPropertyItem **item, int *totitem, int *free)
void RNA_property_enum_items_gettexted (struct bContext *C, PointerRNA *ptr, PropertyRNA *prop, EnumPropertyItem **item, int *totitem, int *free)
int RNA_property_enum_value (struct bContext *C, PointerRNA *ptr, PropertyRNA *prop, const char *identifier, int *value)
int RNA_property_enum_identifier (struct bContext *C, PointerRNA *ptr, PropertyRNA *prop, const int value, const char **identifier)
int RNA_property_enum_name (struct bContext *C, PointerRNA *ptr, PropertyRNA *prop, const int value, const char **name)
int RNA_property_enum_bitflag_identifiers (struct bContext *C, PointerRNA *ptr, PropertyRNA *prop, const int value, const char **identifier)
StructRNA * RNA_property_pointer_type (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_pointer_poll (PointerRNA *ptr, PropertyRNA *prop, PointerRNA *value)
int RNA_property_editable (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_editable_index (PointerRNA *ptr, PropertyRNA *prop, int index)
int RNA_property_editable_flag (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_animateable (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_animated (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_path_from_ID_check (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_update (struct bContext *C, PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_update_main (struct Main *bmain, struct Scene *scene, PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_update_check (struct PropertyRNA *prop)
void RNA_property_update_cache_add (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_update_cache_flush (struct Main *bmain, struct Scene *scene)
void RNA_property_update_cache_free (void)
int RNA_property_boolean_get (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_boolean_set (PointerRNA *ptr, PropertyRNA *prop, int value)
void RNA_property_boolean_get_array (PointerRNA *ptr, PropertyRNA *prop, int *values)
int RNA_property_boolean_get_index (PointerRNA *ptr, PropertyRNA *prop, int index)
void RNA_property_boolean_set_array (PointerRNA *ptr, PropertyRNA *prop, const int *values)
void RNA_property_boolean_set_index (PointerRNA *ptr, PropertyRNA *prop, int index, int value)
int RNA_property_boolean_get_default (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_boolean_get_default_array (PointerRNA *ptr, PropertyRNA *prop, int *values)
int RNA_property_boolean_get_default_index (PointerRNA *ptr, PropertyRNA *prop, int index)
int RNA_property_int_get (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_int_set (PointerRNA *ptr, PropertyRNA *prop, int value)
void RNA_property_int_get_array (PointerRNA *ptr, PropertyRNA *prop, int *values)
void RNA_property_int_get_array_range (PointerRNA *ptr, PropertyRNA *prop, int values[2])
int RNA_property_int_get_index (PointerRNA *ptr, PropertyRNA *prop, int index)
void RNA_property_int_set_array (PointerRNA *ptr, PropertyRNA *prop, const int *values)
void RNA_property_int_set_index (PointerRNA *ptr, PropertyRNA *prop, int index, int value)
int RNA_property_int_get_default (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_int_get_default_array (PointerRNA *ptr, PropertyRNA *prop, int *values)
int RNA_property_int_get_default_index (PointerRNA *ptr, PropertyRNA *prop, int index)
float RNA_property_float_get (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_float_set (PointerRNA *ptr, PropertyRNA *prop, float value)
void RNA_property_float_get_array (PointerRNA *ptr, PropertyRNA *prop, float *values)
void RNA_property_float_get_array_range (PointerRNA *ptr, PropertyRNA *prop, float values[2])
float RNA_property_float_get_index (PointerRNA *ptr, PropertyRNA *prop, int index)
void RNA_property_float_set_array (PointerRNA *ptr, PropertyRNA *prop, const float *values)
void RNA_property_float_set_index (PointerRNA *ptr, PropertyRNA *prop, int index, float value)
float RNA_property_float_get_default (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_float_get_default_array (PointerRNA *ptr, PropertyRNA *prop, float *values)
float RNA_property_float_get_default_index (PointerRNA *ptr, PropertyRNA *prop, int index)
void RNA_property_string_get (PointerRNA *ptr, PropertyRNA *prop, char *value)
char * RNA_property_string_get_alloc (PointerRNA *ptr, PropertyRNA *prop, char *fixedbuf, int fixedlen, int *r_len)
void RNA_property_string_set (PointerRNA *ptr, PropertyRNA *prop, const char *value)
int RNA_property_string_length (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_string_get_default (PointerRNA *ptr, PropertyRNA *prop, char *value)
char * RNA_property_string_get_default_alloc (PointerRNA *ptr, PropertyRNA *prop, char *fixedbuf, int fixedlen)
int RNA_property_string_default_length (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_enum_get (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_enum_set (PointerRNA *ptr, PropertyRNA *prop, int value)
int RNA_property_enum_get_default (PointerRNA *ptr, PropertyRNA *prop)
void * RNA_property_enum_py_data_get (PropertyRNA *prop)
PointerRNA RNA_property_pointer_get (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_pointer_set (PointerRNA *ptr, PropertyRNA *prop, PointerRNA ptr_value)
PointerRNA RNA_property_pointer_get_default (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_collection_begin (PointerRNA *ptr, PropertyRNA *prop, CollectionPropertyIterator *iter)
void RNA_property_collection_next (CollectionPropertyIterator *iter)
void RNA_property_collection_end (CollectionPropertyIterator *iter)
int RNA_property_collection_length (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_collection_lookup_index (PointerRNA *ptr, PropertyRNA *prop, PointerRNA *t_ptr)
int RNA_property_collection_lookup_int (PointerRNA *ptr, PropertyRNA *prop, int key, PointerRNA *r_ptr)
int RNA_property_collection_lookup_string (PointerRNA *ptr, PropertyRNA *prop, const char *key, PointerRNA *r_ptr)
int RNA_property_collection_assign_int (PointerRNA *ptr, PropertyRNA *prop, const int key, const PointerRNA *assign_ptr)
int RNA_property_collection_type_get (PointerRNA *ptr, PropertyRNA *prop, PointerRNA *r_ptr)
int RNA_property_collection_raw_array (PointerRNA *ptr, PropertyRNA *prop, PropertyRNA *itemprop, RawArray *array)
int RNA_property_collection_raw_get (struct ReportList *reports, PointerRNA *ptr, PropertyRNA *prop, const char *propname, void *array, RawPropertyType type, int len)
int RNA_property_collection_raw_set (struct ReportList *reports, PointerRNA *ptr, PropertyRNA *prop, const char *propname, void *array, RawPropertyType type, int len)
int RNA_raw_type_sizeof (RawPropertyType type)
RawPropertyType RNA_property_raw_type (PropertyRNA *prop)
void RNA_property_pointer_add (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_pointer_remove (PointerRNA *ptr, PropertyRNA *prop)
void RNA_property_collection_add (PointerRNA *ptr, PropertyRNA *prop, PointerRNA *r_ptr)
int RNA_property_collection_remove (PointerRNA *ptr, PropertyRNA *prop, int key)
void RNA_property_collection_clear (PointerRNA *ptr, PropertyRNA *prop)
int RNA_property_collection_move (PointerRNA *ptr, PropertyRNA *prop, int key, int pos)
int RNA_property_copy (PointerRNA *ptr, PointerRNA *fromptr, PropertyRNA *prop, int index)
int RNA_property_reset (PointerRNA *ptr, PropertyRNA *prop, int index)
char * RNA_path_append (const char *path, PointerRNA *ptr, PropertyRNA *prop, int intkey, const char *strkey)
char * RNA_path_back (const char *path)
int RNA_path_resolve (PointerRNA *ptr, const char *path, PointerRNA *r_ptr, PropertyRNA **r_prop)
int RNA_path_resolve_full (PointerRNA *ptr, const char *path, PointerRNA *r_ptr, PropertyRNA **r_prop, int *index)
char * RNA_path_from_ID_to_struct (PointerRNA *ptr)
char * RNA_path_from_ID_to_property (PointerRNA *ptr, PropertyRNA *prop)
int RNA_boolean_get (PointerRNA *ptr, const char *name)
void RNA_boolean_set (PointerRNA *ptr, const char *name, int value)
void RNA_boolean_get_array (PointerRNA *ptr, const char *name, int *values)
void RNA_boolean_set_array (PointerRNA *ptr, const char *name, const int *values)
int RNA_int_get (PointerRNA *ptr, const char *name)
void RNA_int_set (PointerRNA *ptr, const char *name, int value)
void RNA_int_get_array (PointerRNA *ptr, const char *name, int *values)
void RNA_int_set_array (PointerRNA *ptr, const char *name, const int *values)
float RNA_float_get (PointerRNA *ptr, const char *name)
void RNA_float_set (PointerRNA *ptr, const char *name, float value)
void RNA_float_get_array (PointerRNA *ptr, const char *name, float *values)
void RNA_float_set_array (PointerRNA *ptr, const char *name, const float *values)
int RNA_enum_get (PointerRNA *ptr, const char *name)
void RNA_enum_set (PointerRNA *ptr, const char *name, int value)
void RNA_enum_set_identifier (PointerRNA *ptr, const char *name, const char *id)
int RNA_enum_is_equal (struct bContext *C, PointerRNA *ptr, const char *name, const char *enumname)
int RNA_enum_value_from_id (EnumPropertyItem *item, const char *identifier, int *value)
int RNA_enum_id_from_value (EnumPropertyItem *item, int value, const char **identifier)
int RNA_enum_icon_from_value (EnumPropertyItem *item, int value, int *icon)
void RNA_string_get (PointerRNA *ptr, const char *name, char *value)
char * RNA_string_get_alloc (PointerRNA *ptr, const char *name, char *fixedbuf, int fixedlen)
int RNA_string_length (PointerRNA *ptr, const char *name)
void RNA_string_set (PointerRNA *ptr, const char *name, const char *value)
PointerRNA RNA_pointer_get (PointerRNA *ptr, const char *name)
void RNA_pointer_set (PointerRNA *ptr, const char *name, PointerRNA ptr_value)
void RNA_pointer_add (PointerRNA *ptr, const char *name)
void RNA_collection_begin (PointerRNA *ptr, const char *name, CollectionPropertyIterator *iter)
int RNA_collection_length (PointerRNA *ptr, const char *name)
void RNA_collection_add (PointerRNA *ptr, const char *name, PointerRNA *r_value)
void RNA_collection_clear (PointerRNA *ptr, const char *name)
int RNA_property_is_set (PointerRNA *ptr, PropertyRNA *prop)
int RNA_struct_property_is_set (PointerRNA *ptr, const char *identifier)
int RNA_property_is_idprop (PropertyRNA *prop)
char * RNA_property_as_string (struct bContext *C, PointerRNA *ptr, PropertyRNA *prop)
char * RNA_pointer_as_string (struct bContext *C, PointerRNA *ptr)
char * RNA_pointer_as_string_keywords_ex (struct bContext *C, PointerRNA *ptr, PointerRNA *ptr_default, const short skip_optional_value, const short all_args, PropertyRNA *iterprop)
char * RNA_pointer_as_string_keywords (struct bContext *C, PointerRNA *ptr, PointerRNA *ptr_default, const short skip_optional_value, const short all_args)
char * RNA_function_as_string_keywords (struct bContext *C, FunctionRNA *func, PointerRNA *ptr_default, const short as_function, const short all_args)
const char * RNA_function_identifier (FunctionRNA *func)
const char * RNA_function_ui_description (FunctionRNA *func)
int RNA_function_flag (FunctionRNA *func)
int RNA_function_defined (FunctionRNA *func)
PropertyRNA * RNA_function_get_parameter (PointerRNA *ptr, FunctionRNA *func, int index)
PropertyRNA * RNA_function_find_parameter (PointerRNA *ptr, FunctionRNA *func, const char *identifier)
struct ListBase * RNA_function_defined_parameters (FunctionRNA *func)
ParameterList * RNA_parameter_list_create (ParameterList *parms, PointerRNA *ptr, FunctionRNA *func)
void RNA_parameter_list_free (ParameterList *parms)
int RNA_parameter_list_size (ParameterList *parms)
int RNA_parameter_list_arg_count (ParameterList *parms)
int RNA_parameter_list_ret_count (ParameterList *parms)
void RNA_parameter_list_begin (ParameterList *parms, ParameterIterator *iter)
void RNA_parameter_list_next (ParameterIterator *iter)
void RNA_parameter_list_end (ParameterIterator *iter)
void RNA_parameter_get (ParameterList *parms, PropertyRNA *parm, void **value)
void RNA_parameter_get_lookup (ParameterList *parms, const char *identifier, void **value)
void RNA_parameter_set (ParameterList *parms, PropertyRNA *parm, const void *value)
void RNA_parameter_set_lookup (ParameterList *parms, const char *identifier, const void *value)
int RNA_parameter_length_get (ParameterList *parms, PropertyRNA *parm)
int RNA_parameter_length_get_data (ParameterList *parms, PropertyRNA *parm, void *data)
void RNA_parameter_length_set (ParameterList *parms, PropertyRNA *parm, int length)
void RNA_parameter_length_set_data (ParameterList *parms, PropertyRNA *parm, void *data, int length)
int RNA_function_call (struct bContext *C, struct ReportList *reports, PointerRNA *ptr, FunctionRNA *func, ParameterList *parms)
int RNA_function_call_lookup (struct bContext *C, struct ReportList *reports, PointerRNA *ptr, const char *identifier, ParameterList *parms)
int RNA_function_call_direct (struct bContext *C, struct ReportList *reports, PointerRNA *ptr, FunctionRNA *func, const char *format,...)
int RNA_function_call_direct_lookup (struct bContext *C, struct ReportList *reports, PointerRNA *ptr, const char *identifier, const char *format,...)
int RNA_function_call_direct_va (struct bContext *C, struct ReportList *reports, PointerRNA *ptr, FunctionRNA *func, const char *format, va_list args)
int RNA_function_call_direct_va_lookup (struct bContext *C, struct ReportList *reports, PointerRNA *ptr, const char *identifier, const char *format, va_list args)
short RNA_type_to_ID_code (StructRNA *type)
StructRNA * ID_code_to_RNA_type (short idcode)
void _RNA_warning (const char *format,...)
Variables
BlenderRNA BLENDER_RNA
StructRNA RNA_Action
StructRNA RNA_ActionConstraint
StructRNA RNA_ActionFCurves
StructRNA RNA_ActionGroup
StructRNA RNA_ActionGroups
StructRNA RNA_ActionPoseMarkers
StructRNA RNA_Actuator
StructRNA RNA_ActuatorSensor
StructRNA RNA_Addon
StructRNA RNA_AdjustmentSequence
StructRNA RNA_AlwaysSensor
StructRNA RNA_AndController
StructRNA RNA_AnimData
StructRNA RNA_AnimViz
StructRNA RNA_AnimVizMotionPaths
StructRNA RNA_AnimVizOnionSkinning
StructRNA RNA_AnyType
StructRNA RNA_Area
StructRNA RNA_AreaLamp
StructRNA RNA_Armature
StructRNA RNA_ArmatureModifier
StructRNA RNA_ArmatureSensor
StructRNA RNA_ArrayModifier
StructRNA RNA_BackgroundImage
StructRNA RNA_BevelModifier
StructRNA RNA_SplinePoint
StructRNA RNA_BezierSplinePoint
StructRNA RNA_BlendData
StructRNA RNA_BlendTexture
StructRNA RNA_BlenderRNA
StructRNA RNA_BoidRule
StructRNA RNA_BoidRuleAverageSpeed
StructRNA RNA_BoidRuleAvoid
StructRNA RNA_BoidRuleAvoidCollision
StructRNA RNA_BoidRuleFight
StructRNA RNA_BoidRuleFollowLeader
StructRNA RNA_BoidRuleGoal
StructRNA RNA_BoidSettings
StructRNA RNA_BoidState
StructRNA RNA_Bone
StructRNA RNA_BoneGroup
StructRNA RNA_BooleanModifier
StructRNA RNA_BoolProperty
StructRNA RNA_Brush
StructRNA RNA_BrushTextureSlot
StructRNA RNA_BuildModifier
StructRNA RNA_Camera
StructRNA RNA_CastModifier
StructRNA RNA_ChildOfConstraint
StructRNA RNA_ChildParticle
StructRNA RNA_ClampToConstraint
StructRNA RNA_ClothCollisionSettings
StructRNA RNA_ClothModifier
StructRNA RNA_ClothSettings
StructRNA RNA_CloudsTexture
StructRNA RNA_CollectionProperty
StructRNA RNA_CollisionModifier
StructRNA RNA_CollisionSensor
StructRNA RNA_CollisionSettings
StructRNA RNA_ColorRamp
StructRNA RNA_ColorRampElement
StructRNA RNA_ColorSequence
StructRNA RNA_CompositorNode
StructRNA RNA_CompositorNodeAlphaOver
StructRNA RNA_CompositorNodeBilateralblur
StructRNA RNA_CompositorNodeBlur
StructRNA RNA_CompositorNodeBrightContrast
StructRNA RNA_CompositorNodeChannelMatte
StructRNA RNA_CompositorNodeChromaMatte
StructRNA RNA_CompositorNodeColorMatte
StructRNA RNA_CompositorNodeColorSpill
StructRNA RNA_CompositorNodeCombHSVA
StructRNA RNA_CompositorNodeCombRGBA
StructRNA RNA_CompositorNodeCombYCCA
StructRNA RNA_CompositorNodeCombYUVA
StructRNA RNA_CompositorNodeComposite
StructRNA RNA_CompositorNodeCrop
StructRNA RNA_CompositorNodeCurveRGB
StructRNA RNA_CompositorNodeCurveVec
StructRNA RNA_CompositorNodeDBlur
StructRNA RNA_CompositorNodeDefocus
StructRNA RNA_CompositorNodeDiffMatte
StructRNA RNA_CompositorNodeDilateErode
StructRNA RNA_CompositorNodeDisplace
StructRNA RNA_CompositorNodeDistanceMatte
StructRNA RNA_CompositorNodeFilter
StructRNA RNA_CompositorNodeFlip
StructRNA RNA_CompositorNodeGamma
StructRNA RNA_CompositorNodeGlare
StructRNA RNA_CompositorNodeHueSat
StructRNA RNA_CompositorNodeIDMask
StructRNA RNA_CompositorNodeDoubleEdgeMask
StructRNA RNA_CompositorNodeImage
StructRNA RNA_CompositorNodeInvert
StructRNA RNA_CompositorNodeLensdist
StructRNA RNA_CompositorNodeLevels
StructRNA RNA_CompositorNodeLumaMatte
StructRNA RNA_CompositorNodeMapUV
StructRNA RNA_CompositorNodeMapValue
StructRNA RNA_CompositorNodeMath
StructRNA RNA_CompositorNodeMixRGB
StructRNA RNA_CompositorNodeNormal
StructRNA RNA_CompositorNodeNormalize
StructRNA RNA_CompositorNodeOutputFile
StructRNA RNA_CompositorNodePremulKey
StructRNA RNA_CompositorNodeRGB
StructRNA RNA_CompositorNodeRGBToBW
StructRNA RNA_CompositorNodeRLayers
StructRNA RNA_CompositorNodeRotate
StructRNA RNA_CompositorNodeScale
StructRNA RNA_CompositorNodeSepHSVA
StructRNA RNA_CompositorNodeSepRGBA
StructRNA RNA_CompositorNodeSepYCCA
StructRNA RNA_CompositorNodeSepYUVA
StructRNA RNA_CompositorNodeSetAlpha
StructRNA RNA_CompositorNodeSplitViewer
StructRNA RNA_CompositorNodeTexture
StructRNA RNA_CompositorNodeTime
StructRNA RNA_CompositorNodeTonemap
StructRNA RNA_CompositorNodeTranslate
StructRNA RNA_CompositorNodeTree
StructRNA RNA_CompositorNodeValToRGB
StructRNA RNA_CompositorNodeValue
StructRNA RNA_CompositorNodeVecBlur
StructRNA RNA_CompositorNodeViewer
StructRNA RNA_CompositorNodeZcombine
StructRNA RNA_ConsoleLine
StructRNA RNA_Constraint
StructRNA RNA_ConstraintTarget
StructRNA RNA_Context
StructRNA RNA_ControlFluidSettings
StructRNA RNA_Controller
StructRNA RNA_CopyLocationConstraint
StructRNA RNA_CopyRotationConstraint
StructRNA RNA_CopyScaleConstraint
StructRNA RNA_CopyTransformsConstraint
StructRNA RNA_Curve
StructRNA RNA_CurveMap
StructRNA RNA_CurveMapPoint
StructRNA RNA_CurveMapping
StructRNA RNA_CurveModifier
StructRNA RNA_CurvePoint
StructRNA RNA_DampedTrackConstraint
StructRNA RNA_DecimateModifier
StructRNA RNA_DelaySensor
StructRNA RNA_DisplaceModifier
StructRNA RNA_DistortedNoiseTexture
StructRNA RNA_DomainFluidSettings
StructRNA RNA_DopeSheet
StructRNA RNA_Driver
StructRNA RNA_DriverTarget
StructRNA RNA_DriverVariable
StructRNA RNA_DupliObject
StructRNA RNA_DynamicPaintBrushSettings
StructRNA RNA_DynamicPaintCanvasSettings
StructRNA RNA_DynamicPaintModifier
StructRNA RNA_DynamicPaintSurface
StructRNA RNA_EdgeSplitModifier
StructRNA RNA_EditBone
StructRNA RNA_EffectSequence
StructRNA RNA_EffectorWeights
StructRNA RNA_EnumProperty
StructRNA RNA_EnumPropertyItem
StructRNA RNA_EnvironmentMap
StructRNA RNA_EnvironmentMapTexture
StructRNA RNA_Event
StructRNA RNA_ExplodeModifier
StructRNA RNA_ExpressionController
StructRNA RNA_FCurve
StructRNA RNA_FCurveSample
StructRNA RNA_FFmpegSettings
StructRNA RNA_FModifier
StructRNA RNA_FModifierCycles
StructRNA RNA_FModifierEnvelope
StructRNA RNA_FModifierEnvelopeControlPoint
StructRNA RNA_FModifierFunctionGenerator
StructRNA RNA_FModifierGenerator
StructRNA RNA_FModifierLimits
StructRNA RNA_FModifierNoise
StructRNA RNA_FModifierPython
StructRNA RNA_FModifierStepped
StructRNA RNA_FieldSettings
StructRNA RNA_FileSelectParams
StructRNA RNA_FloatProperty
StructRNA RNA_FloorConstraint
StructRNA RNA_FluidFluidSettings
StructRNA RNA_FluidSettings
StructRNA RNA_FluidSimulationModifier
StructRNA RNA_FollowPathConstraint
StructRNA RNA_Function
StructRNA RNA_GPencilFrame
StructRNA RNA_GPencilLayer
StructRNA RNA_GPencilStroke
StructRNA RNA_GPencilStrokePoint
StructRNA RNA_GameBooleanProperty
StructRNA RNA_GameFloatProperty
StructRNA RNA_GameIntProperty
StructRNA RNA_GameObjectSettings
StructRNA RNA_GameProperty
StructRNA RNA_GameSoftBodySettings
StructRNA RNA_GameStringProperty
StructRNA RNA_GameTimerProperty
StructRNA RNA_GlowSequence
StructRNA RNA_GreasePencil
StructRNA RNA_Group
StructRNA RNA_Header
StructRNA RNA_HemiLamp
StructRNA RNA_Histogram
StructRNA RNA_HookModifier
StructRNA RNA_ID
StructRNA RNA_IKParam
StructRNA RNA_Image
StructRNA RNA_ImageFormatSettings
StructRNA RNA_ImagePaint
StructRNA RNA_ImageSequence
StructRNA RNA_ImageTexture
StructRNA RNA_ImageUser
StructRNA RNA_InflowFluidSettings
StructRNA RNA_IntProperty
StructRNA RNA_Itasc
StructRNA RNA_JoystickSensor
StructRNA RNA_Key
StructRNA RNA_KeyConfig
StructRNA RNA_KeyMap
StructRNA RNA_KeyMapItem
StructRNA RNA_KeyMapItems
StructRNA RNA_KeyboardSensor
StructRNA RNA_Keyframe
StructRNA RNA_KeyingSet
StructRNA RNA_KeyingSetInfo
StructRNA RNA_KeyingSetPath
StructRNA RNA_KeyingSetsAll
StructRNA RNA_KinematicConstraint
StructRNA RNA_Lamp
StructRNA RNA_LampSkySettings
StructRNA RNA_LampTextureSlot
StructRNA RNA_Lattice
StructRNA RNA_LatticeModifier
StructRNA RNA_LatticePoint
StructRNA RNA_Library
StructRNA RNA_LimitDistanceConstraint
StructRNA RNA_LimitLocationConstraint
StructRNA RNA_LimitRotationConstraint
StructRNA RNA_LimitScaleConstraint
StructRNA RNA_LockedTrackConstraint
StructRNA RNA_Macro
StructRNA RNA_MagicTexture
StructRNA RNA_MarbleTexture
StructRNA RNA_MaskModifier
StructRNA RNA_Material
StructRNA RNA_MaterialHalo
StructRNA RNA_MaterialPhysics
StructRNA RNA_MaterialRaytraceMirror
StructRNA RNA_MaterialRaytraceTransparency
StructRNA RNA_MaterialSlot
StructRNA RNA_MaterialStrand
StructRNA RNA_MaterialSubsurfaceScattering
StructRNA RNA_MaterialTextureSlot
StructRNA RNA_MaterialVolume
StructRNA RNA_Menu
StructRNA RNA_Mesh
StructRNA RNA_MeshColor
StructRNA RNA_MeshColorLayer
StructRNA RNA_MeshLoopColorLayer
StructRNA RNA_MeshDeformModifier
StructRNA RNA_MeshEdge
StructRNA RNA_MeshPolygon
StructRNA RNA_MeshTessFace
StructRNA RNA_MeshLoop
StructRNA RNA_MeshFloatProperty
StructRNA RNA_MeshFloatPropertyLayer
StructRNA RNA_MeshIntProperty
StructRNA RNA_MeshIntPropertyLayer
StructRNA RNA_MeshSticky
StructRNA RNA_MeshStringProperty
StructRNA RNA_MeshStringPropertyLayer
StructRNA RNA_MeshTextureFace
StructRNA RNA_MeshTextureFaceLayer
StructRNA RNA_MeshTexturePoly
StructRNA RNA_MeshTexturePolyLayer
StructRNA RNA_MeshVertex
StructRNA RNA_MessageSensor
StructRNA RNA_MetaBall
StructRNA RNA_MetaElement
StructRNA RNA_MetaSequence
StructRNA RNA_MirrorModifier
StructRNA RNA_Modifier
StructRNA RNA_MotionPath
StructRNA RNA_MotionPathVert
StructRNA RNA_MouseSensor
StructRNA RNA_MovieSequence
StructRNA RNA_MovieClipSequence
StructRNA RNA_MovieTrackingObject
StructRNA RNA_MulticamSequence
StructRNA RNA_MultiresModifier
StructRNA RNA_MusgraveTexture
StructRNA RNA_NandController
StructRNA RNA_NearSensor
StructRNA RNA_NlaStrip
StructRNA RNA_NlaTrack
StructRNA RNA_Node
StructRNA RNA_NodeForLoop
StructRNA RNA_NodeGroup
StructRNA RNA_NodeImageFileSocket
StructRNA RNA_NodeLink
StructRNA RNA_NodeSocket
StructRNA RNA_NodeSocketPanel
StructRNA RNA_NodeTree
StructRNA RNA_NodeWhileLoop
StructRNA RNA_NoiseTexture
StructRNA RNA_NorController
StructRNA RNA_Object
StructRNA RNA_ObjectBase
StructRNA RNA_ObstacleFluidSettings
StructRNA RNA_OceanModifier
StructRNA RNA_OceanTexData
StructRNA RNA_OceanTexture
StructRNA RNA_Operator
StructRNA RNA_OperatorFileListElement
StructRNA RNA_OperatorMousePath
StructRNA RNA_OperatorProperties
StructRNA RNA_OperatorStrokeElement
StructRNA RNA_OperatorMacro
StructRNA RNA_OrController
StructRNA RNA_OutflowFluidSettings
StructRNA RNA_PackedFile
StructRNA RNA_Paint
StructRNA RNA_Panel
StructRNA RNA_Particle
StructRNA RNA_ParticleBrush
StructRNA RNA_ParticleDupliWeight
StructRNA RNA_ParticleEdit
StructRNA RNA_ParticleFluidSettings
StructRNA RNA_ParticleHairKey
StructRNA RNA_ParticleInstanceModifier
StructRNA RNA_ParticleKey
StructRNA RNA_ParticleSettings
StructRNA RNA_ParticleSettingsTextureSlot
StructRNA RNA_ParticleSystem
StructRNA RNA_ParticleSystemModifier
StructRNA RNA_ParticleTarget
StructRNA RNA_PivotConstraint
StructRNA RNA_PluginSequence
StructRNA RNA_PluginTexture
StructRNA RNA_PointCache
StructRNA RNA_PointDensity
StructRNA RNA_PointDensityTexture
StructRNA RNA_PointLamp
StructRNA RNA_PointerProperty
StructRNA RNA_Pose
StructRNA RNA_PoseBone
StructRNA RNA_Property
StructRNA RNA_PropertyGroup
StructRNA RNA_PropertyGroupItem
StructRNA RNA_PropertySensor
StructRNA RNA_PythonConstraint
StructRNA RNA_PythonController
StructRNA RNA_QuickTimeSettings
StructRNA RNA_RadarSensor
StructRNA RNA_RandomSensor
StructRNA RNA_RaySensor
StructRNA RNA_Region
StructRNA RNA_RenderEngine
StructRNA RNA_RenderLayer
StructRNA RNA_RenderPass
StructRNA RNA_RenderResult
StructRNA RNA_RenderSettings
StructRNA RNA_RigidBodyJointConstraint
StructRNA RNA_SPHFluidSettings
StructRNA RNA_Scene
StructRNA RNA_SceneGameData
StructRNA RNA_SceneRenderLayer
StructRNA RNA_SceneSequence
StructRNA RNA_SceneObjects
StructRNA RNA_Scopes
StructRNA RNA_Screen
StructRNA RNA_ScrewModifier
StructRNA RNA_Sculpt
StructRNA RNA_SelectedUvElement
StructRNA RNA_Sensor
StructRNA RNA_Sequence
StructRNA RNA_SequenceColorBalance
StructRNA RNA_SequenceCrop
StructRNA RNA_SequenceEditor
StructRNA RNA_SequenceElement
StructRNA RNA_SequenceProxy
StructRNA RNA_SequenceTransform
StructRNA RNA_ShaderNode
StructRNA RNA_ShaderNodeCameraData
StructRNA RNA_ShaderNodeCombineRGB
StructRNA RNA_ShaderNodeExtendedMaterial
StructRNA RNA_ShaderNodeGeometry
StructRNA RNA_ShaderNodeHueSaturation
StructRNA RNA_ShaderNodeInvert
StructRNA RNA_ShaderNodeMapping
StructRNA RNA_ShaderNodeMaterial
StructRNA RNA_ShaderNodeMath
StructRNA RNA_ShaderNodeMixRGB
StructRNA RNA_ShaderNodeNormal
StructRNA RNA_ShaderNodeOutput
StructRNA RNA_ShaderNodeRGB
StructRNA RNA_ShaderNodeRGBCurve
StructRNA RNA_ShaderNodeRGBToBW
StructRNA RNA_ShaderNodeSeparateRGB
StructRNA RNA_ShaderNodeSqueeze
StructRNA RNA_ShaderNodeTexture
StructRNA RNA_ShaderNodeTree
StructRNA RNA_ShaderNodeValToRGB
StructRNA RNA_ShaderNodeValue
StructRNA RNA_ShaderNodeVectorCurve
StructRNA RNA_ShaderNodeVectorMath
StructRNA RNA_ShapeKey
StructRNA RNA_ShapeKeyBezierPoint
StructRNA RNA_ShapeKeyCurvePoint
StructRNA RNA_ShapeKeyPoint
StructRNA RNA_ShrinkwrapConstraint
StructRNA RNA_ShrinkwrapModifier
StructRNA RNA_SimpleDeformModifier
StructRNA RNA_SmokeCollSettings
StructRNA RNA_SmokeDomainSettings
StructRNA RNA_SmokeFlowSettings
StructRNA RNA_SmokeModifier
StructRNA RNA_SmoothModifier
StructRNA RNA_SoftBodyModifier
StructRNA RNA_SoftBodySettings
StructRNA RNA_SolidifyModifier
StructRNA RNA_Sound
StructRNA RNA_SoundSequence
StructRNA RNA_Space
StructRNA RNA_SpaceConsole
StructRNA RNA_SpaceDopeSheetEditor
StructRNA RNA_SpaceFileBrowser
StructRNA RNA_SpaceGraphEditor
StructRNA RNA_SpaceImageEditor
StructRNA RNA_SpaceInfo
StructRNA RNA_SpaceLogicEditor
StructRNA RNA_SpaceNLA
StructRNA RNA_SpaceNodeEditor
StructRNA RNA_SpaceOutliner
StructRNA RNA_SpaceProperties
StructRNA RNA_SpaceSequenceEditor
StructRNA RNA_SpaceTextEditor
StructRNA RNA_SpaceTimeline
StructRNA RNA_SpaceUVEditor
StructRNA RNA_SpaceUserPreferences
StructRNA RNA_SpaceView3D
StructRNA RNA_SpaceClipEditor
StructRNA RNA_Speaker
StructRNA RNA_SpeedControlSequence
StructRNA RNA_Spline
StructRNA RNA_SplineIKConstraint
StructRNA RNA_SpotLamp
StructRNA RNA_StretchToConstraint
StructRNA RNA_StringProperty
StructRNA RNA_Struct
StructRNA RNA_StucciTexture
StructRNA RNA_SubsurfModifier
StructRNA RNA_SunLamp
StructRNA RNA_SurfaceCurve
StructRNA RNA_SurfaceModifier
StructRNA RNA_TexMapping
StructRNA RNA_Text
StructRNA RNA_TextBox
StructRNA RNA_TextCharacterFormat
StructRNA RNA_TextCurve
StructRNA RNA_TextLine
StructRNA RNA_TextMarker
StructRNA RNA_Texture
StructRNA RNA_TextureNode
StructRNA RNA_TextureNodeBricks
StructRNA RNA_TextureNodeChecker
StructRNA RNA_TextureNodeCompose
StructRNA RNA_TextureNodeCoordinates
StructRNA RNA_TextureNodeCurveRGB
StructRNA RNA_TextureNodeCurveTime
StructRNA RNA_TextureNodeDecompose
StructRNA RNA_TextureNodeDistance
StructRNA RNA_TextureNodeHueSaturation
StructRNA RNA_TextureNodeImage
StructRNA RNA_TextureNodeInvert
StructRNA RNA_TextureNodeMath
StructRNA RNA_TextureNodeMixRGB
StructRNA RNA_TextureNodeOutput
StructRNA RNA_TextureNodeRGBToBW
StructRNA RNA_TextureNodeRotate
StructRNA RNA_TextureNodeScale
StructRNA RNA_TextureNodeTexture
StructRNA RNA_TextureNodeTranslate
StructRNA RNA_TextureNodeTree
StructRNA RNA_TextureNodeValToNor
StructRNA RNA_TextureNodeValToRGB
StructRNA RNA_TextureNodeViewer
StructRNA RNA_TextureSlot
StructRNA RNA_Theme
StructRNA RNA_ThemeAudioWindow
StructRNA RNA_ThemeBoneColorSet
StructRNA RNA_ThemeConsole
StructRNA RNA_ThemeDopeSheet
StructRNA RNA_ThemeFileBrowser
StructRNA RNA_ThemeFontStyle
StructRNA RNA_ThemeGraphEditor
StructRNA RNA_ThemeImageEditor
StructRNA RNA_ThemeInfo
StructRNA RNA_ThemeLogicEditor
StructRNA RNA_ThemeNLAEditor
StructRNA RNA_ThemeNodeEditor
StructRNA RNA_ThemeOutliner
StructRNA RNA_ThemeProperties
StructRNA RNA_ThemeSequenceEditor
StructRNA RNA_ThemeSpaceGeneric
StructRNA RNA_ThemeSpaceListGeneric
StructRNA RNA_ThemeStyle
StructRNA RNA_ThemeTextEditor
StructRNA RNA_ThemeTimeline
StructRNA RNA_ThemeUserInterface
StructRNA RNA_ThemeUserPreferences
StructRNA RNA_ThemeView3D
StructRNA RNA_ThemeWidgetColors
StructRNA RNA_ThemeWidgetStateColors
StructRNA RNA_TimelineMarker
StructRNA RNA_Timer
StructRNA RNA_ToolSettings
StructRNA RNA_TouchSensor
StructRNA RNA_TrackToConstraint
StructRNA RNA_TransformConstraint
StructRNA RNA_TransformSequence
StructRNA RNA_UILayout
StructRNA RNA_UIListItem
StructRNA RNA_UVProjectModifier
StructRNA RNA_UVProjector
StructRNA RNA_UnitSettings
StructRNA RNA_UnknownType
StructRNA RNA_UserPreferences
StructRNA RNA_UserPreferencesEdit
StructRNA RNA_UserPreferencesFilePaths
StructRNA RNA_UserPreferencesInput
StructRNA RNA_UserPreferencesSystem
StructRNA RNA_UserPreferencesView
StructRNA RNA_UserSolidLight
StructRNA RNA_VectorFont
StructRNA RNA_VertexGroup
StructRNA RNA_VertexGroupElement
StructRNA RNA_VertexPaint
StructRNA RNA_VoronoiTexture
StructRNA RNA_VoxelData
StructRNA RNA_VoxelDataTexture
StructRNA RNA_WarpModifier
StructRNA RNA_WaveModifier
StructRNA RNA_VertexWeightEditModifier
StructRNA RNA_VertexWeightMixModifier
StructRNA RNA_VertexWeightProximityModifier
StructRNA RNA_Window
StructRNA RNA_WindowManager
StructRNA RNA_WipeSequence
StructRNA RNA_WoodTexture
StructRNA RNA_World
StructRNA RNA_WorldAmbientOcclusion
StructRNA RNA_WorldLighting
StructRNA RNA_WorldMistSettings
StructRNA RNA_WorldStarsSettings
StructRNA RNA_WorldTextureSlot
StructRNA RNA_XnorController
StructRNA RNA_XorController
const PointerRNA PointerRNA_NULL
Detailed Description
Definition in file RNA_access.h.
Define Documentation
#define RNA_BEGIN (sptr, itemptr, propname)
Value:
{                                                                         \
        CollectionPropertyIterator rna_macro_iter;                            \
        for (RNA_collection_begin(sptr, propname, &rna_macro_iter);           \
             rna_macro_iter.valid;                                            \
             RNA_property_collection_next(&rna_macro_iter))                   \
        {                                                                     \
            PointerRNA itemptr = rna_macro_iter.ptr;
Definition at line 902 of file RNA_access.h.
Referenced by brush_edit_exec(), cut_links_exec(), edbm_knife_cut_exec(), gpencil_draw_exec(), paint_exec(), paint_stroke_exec(), seq_load_operator_info(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_change_path_exec(), stitch_init(), view3d_lasso_select_exec(), and wm_link_append_exec().
#define RNA_END
Value:
}                                                                     \
        RNA_property_collection_end(&rna_macro_iter);                         \
    }
Definition at line 911 of file RNA_access.h.
Referenced by brush_edit_exec(), cut_links_exec(), edbm_knife_cut_exec(), gpencil_draw_exec(), paint_exec(), paint_stroke_exec(), seq_load_operator_info(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_change_path_exec(), stitch_init(), view3d_lasso_select_exec(), and wm_link_append_exec().
#define RNA_PROP_BEGIN (sptr, itemptr, prop)
Value:
{                                                                         \
        CollectionPropertyIterator rna_macro_iter;                            \
        for (RNA_property_collection_begin(sptr, prop, &rna_macro_iter);      \
             rna_macro_iter.valid;                                            \
             RNA_property_collection_next(&rna_macro_iter))                   \
        {                                                                     \
            PointerRNA itemptr = rna_macro_iter.ptr;
Definition at line 916 of file RNA_access.h.
Referenced by foreach_attr_type(), pyrna_alloc_types(), pyrna_basetype_dir(), pyrna_dir_members_rna(), pyrna_free_types(), pyrna_prop_collection_find(), pyrna_prop_collection_items(), pyrna_prop_collection_keys(), pyrna_prop_collection_subscript_str_lib_pair_ptr(), pyrna_unregister_class(), RNA_pointer_as_string_keywords_ex(), rna_raw_access(), rna_search_cb(), RNA_struct_contains_property(), RNA_struct_find_function(), uiTemplateList(), and WM_operator_properties_reset().
#define RNA_PROP_END
Value:
}                                                                     \
        RNA_property_collection_end(&rna_macro_iter);                         \
    }
Definition at line 925 of file RNA_access.h.
Referenced by foreach_attr_type(), pyrna_alloc_types(), pyrna_basetype_dir(), pyrna_dir_members_rna(), pyrna_free_types(), pyrna_prop_collection_find(), pyrna_prop_collection_items(), pyrna_prop_collection_keys(), pyrna_prop_collection_subscript_str_lib_pair_ptr(), pyrna_unregister_class(), RNA_pointer_as_string_keywords_ex(), rna_raw_access(), rna_search_cb(), RNA_struct_contains_property(), RNA_struct_find_function(), RNA_struct_find_nested(), uiTemplateList(), and WM_operator_properties_reset().
#define RNA_STRUCT_BEGIN (sptr, prop)
Value:
{                                                                         \
        CollectionPropertyIterator rna_macro_iter;                            \
        for (RNA_property_collection_begin(                                   \
                     sptr,                                                    \
                     RNA_struct_iterator_property(sptr->type),                \
                     &rna_macro_iter);                                        \
             rna_macro_iter.valid;                                            \
             RNA_property_collection_next(&rna_macro_iter))                   \
        {                                                                     \
            PropertyRNA *prop = rna_macro_iter.ptr.data;
Definition at line 930 of file RNA_access.h.
Referenced by pyrna_pydict_to_props(), RNA_pointer_as_string(), RNA_struct_find_nested(), search_id_collection(), template_keymap_item_properties(), uiDefAutoButsRNA(), wm_operator_create(), and WM_operator_properties_sanitize().
#define RNA_STRUCT_END
Value:
}                                                                     \
        RNA_property_collection_end(&rna_macro_iter);                         \
    }
Definition at line 942 of file RNA_access.h.
Referenced by pyrna_pydict_to_props(), RNA_pointer_as_string(), search_id_collection(), template_keymap_item_properties(), uiDefAutoButsRNA(), wm_operator_create(), and WM_operator_properties_sanitize().
#define RNA_warning (format, ...) _RNA_warning("%s: " format "\n", __FUNCTION__, __VA_ARGS__)
Definition at line 1021 of file RNA_access.h.
Referenced by template_id_cb(), ui_template_id(), uiItemEnumO(), uiItemEnumO_ptr(), uiItemEnumO_string(), uiItemEnumO_value(), uiItemEnumR(), uiItemEnumR_string(), uiItemM(), uiItemMenuEnumO(), uiItemMenuEnumR(), uiItemPointerR(), uiItemR(), uiItemsEnumR(), uiItemsFullEnumO(), uiTemplateAnyID(), uiTemplateColorWheel(), uiTemplateConstraint(), uiTemplateCurveMapping(), uiTemplateLayers(), uiTemplateList(), uiTemplateModifier(), uiTemplatePathBuilder(), and uiTemplatePreview().
Function Documentation
void _RNA_warning (const char * format, ...)
Definition at line 5713 of file rna_access.c.
References PyC_LineSpit().
StructRNA* ID_code_to_RNA_type (short idcode)
void RNA_blender_rna_pointer_create (PointerRNA * r_ptr)
Definition at line 173 of file rna_access.c.
References BLENDER_RNA, PointerRNA::data, PointerRNA::id, NULL, RNA_BlenderRNA, and PointerRNA::type.
Referenced by BPY_rna_types(), pyrna_alloc_types(), pyrna_free_types(), and pyrna_unregister_class().
int RNA_boolean_get (PointerRNA * ptr, const char * name)
Definition at line 4101 of file rna_access.c.
References StructRNA::identifier, RNA_property_boolean_get(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by actkeys_borderselect_exec(), actkeys_clickselect_invoke(), actkeys_deselectall_exec(), actkeys_select_leftright_exec(), add_driver_button_exec(), add_keyingset_button_exec(), add_named_exec(), animchannels_borderselect_exec(), animchannels_collapse_exec(), animchannels_deselectall_exec(), animchannels_expand_exec(), animchannels_mouseclick_invoke(), armature_calc_roll_exec(), armature_extrude_exec(), armature_hide_exec(), armature_select_hierarchy_exec(), armature_select_linked_invoke(), border_select_exec(), border_select_graph_exec(), borderselect_exec(), brush_edit_apply(), clear_track_path_exec(), connect_hair_exec(), console_clear_exec(), console_history_append_exec(), console_history_cycle_exec(), convert_exec(), copy_to_selected_button_exec(), create_orientation_exec(), delete_key_button_exec(), delete_key_exec(), disconnect_hair_exec(), draw_actuator_action(), draw_actuator_constraint(), draw_actuator_filter_2d(), draw_actuator_header(), draw_actuator_motion(), draw_actuator_parent(), draw_actuator_sound(), draw_actuator_steering(), draw_brick_actuator(), draw_brick_controller(), draw_brick_sensor(), draw_controller_header(), draw_modifier__stepped(), draw_sensor_collision(), draw_sensor_header(), draw_sensor_internal_header(), draw_sensor_joystick(), draw_sensor_keyboard(), duplicate_exec(), ED_fileselect_set_params(), ed_marker_border_select_exec(), ed_marker_select_invoke(), ED_object_add_generic_get_opts(), edbm_bevel_exec(), edbm_blend_from_shape_exec(), edbm_dissolve_exec(), edbm_dupli_extrude_cursor_invoke(), edbm_hide_exec(), edbm_inset_exec(), edbm_loop_multiselect_exec(), edbm_loop_to_region_exec(), edbm_mark_seam(), edbm_mark_sharp(), edbm_merge_exec(), edbm_normals_make_consistent_exec(), edbm_quads_convert_to_tris_exec(), edbm_select_linked_exec(), edbm_select_linked_pick_invoke(), edbm_select_loop_invoke(), edbm_select_mirror_exec(), edbm_select_random_exec(), edbm_spin_exec(), edbm_subdivide_exec(), edbm_tris_convert_to_quads_exec(), enable_manipulator_invoke(), face_select_hide_exec(), file_border_select_exec(), file_draw_check_exists(), file_exec(), file_select_invoke(), file_sfile_to_operator(), frame_jump_exec(), get_boolean(), BlenderSync::get_scene_params(), gpencil_draw_exec(), graph_fmodifier_add_exec(), graph_fmodifier_add_invoke(), graph_panel_view(), graphkeys_borderselect_exec(), graphkeys_clickselect_invoke(), graphkeys_deselectall_exec(), graphkeys_select_leftright_exec(), hide_exec(), hide_metaelems_exec(), hide_tracks_exec(), image_cycle_render_slot_exec(), image_invert_exec(), image_new_exec(), image_pack_exec(), image_pack_invoke(), image_pack_test(), image_save_as_draw_check_prop(), initSnapping(), initTransInfo(), insert_key_button_exec(), insert_key_exec(), insert_key_menu_invoke(), keyframe_jump_exec(), knifetool_init(), line_break_exec(), logic_buttons_new(), make_single_user_exec(), minimize_stretch_init(), mode_set_exec(), multires_external_save_exec(), nla_fmodifier_add_exec(), nla_panel_actclip(), nla_panel_evaluation(), nla_panel_properties(), nlachannels_mouseclick_invoke(), nlaedit_add_tracks_exec(), nlaedit_borderselect_exec(), nlaedit_clickselect_invoke(), nlaedit_deselectall_exec(), nlaedit_select_leftright_exec(), nlaedit_sync_actlen_exec(), node_border_select_invoke(), node_borderselect_exec(), node_composit_buts_blur(), node_composit_buts_color_spill(), node_composit_buts_crop(), node_composit_buts_defocus(), node_composit_buts_file_output_details(), node_composit_buts_lensdist(), node_composit_buts_map_value(), node_duplicate_exec(), node_make_link_exec(), node_select_exec(), node_socket_button_output_file(), object_delete_exec(), object_duplicates_make_real_exec(), object_hide_render_set_exec(), object_hide_view_set_exec(), object_mode_set_exec(), object_select_by_layer_exec(), object_select_by_type_exec(), object_select_grouped_exec(), object_select_linked_exec(), object_select_menu_exec(), object_select_mirror_exec(), object_select_random_exec(), object_transform_apply_exec(), ocean_bake_exec(), outliner_item_activate(), outliner_item_openclose(), outliner_one_level_exec(), outliner_scroll_page_exec(), paint_select_linked_pick_invoke(), pin_exec(), pose_armature_layers_showall_exec(), pose_hide_exec(), pose_ik_add_exec(), pose_paste_exec(), pose_select_connected_invoke(), pose_select_grouped_exec(), pose_select_hierarchy_exec(), ptcache_bake_all_exec(), ptcache_bake_exec(), remove_driver_button_exec(), reset_default_button_exec(), ringsel_init(), save_image_doit(), screen_animation_cancel_exec(), screen_animation_play_exec(), screen_opengl_render_exec(), screen_opengl_render_init(), screen_opengl_render_invoke(), screen_opengl_render_modal(), screen_render_exec(), screen_render_invoke(), screencast_exec(), screenshot_exec(), sculpt_brush_stroke_invoke(), sculpt_update_cache_variants(), select_exec(), select_invoke(), select_linked_exec(), select_linked_internal(), select_linked_pick_invoke(), select_loop_exec(), select_random_exec(), seq_load_operator_info(), sequencer_add_effect_strip_exec(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_borderselect_exec(), sequencer_change_path_exec(), sequencer_mute_exec(), sequencer_reload_exec(), sequencer_select_grouped_exec(), sequencer_select_invoke(), sequencer_select_linked_pick_invoke(), sequencer_unmute_exec(), set_style_exec(), shape_key_add_exec(), sketch_draw_gesture(), sketch_draw_modal(), sketch_draw_preview(), sketch_draw_stroke(), stitch_init(), text_open_exec(), text_paste_exec(), text_set_selection_invoke(), text_to_3d_object_exec(), track_markers_exec(), track_markers_invoke(), uiTemplateImage(), unwrap_exec(), uv_from_view_exec(), uv_map_clip_correct(), v3d_transform_butsR(), vertex_group_assign_exec(), vertex_group_clean_exec(), vertex_group_invert_exec(), vertex_group_mirror_exec(), vertex_group_normalize_all_exec(), vertex_group_remove_exec(), vertex_group_remove_from_exec(), view3d_all_exec(), view3d_borderselect_exec(), view3d_lasso_select_exec(), view3d_layers_exec(), view3d_select_invoke(), view_all_exec(), view_scrolldown_exec(), view_scrollup_exec(), viewnumpad_exec(), wm_handler_fileselect_call(), wm_link_append_exec(), wm_link_append_flag(), wm_ndof_sensitivity_exec(), wm_open_mainfile_exec(), wm_save_as_mainfile_exec(), wm_save_mainfile_invoke(), and wpaint_stroke_update_step().
void RNA_boolean_get_array (PointerRNA * ptr, const char * name, int * values)
Definition at line 4124 of file rna_access.c.
References StructRNA::identifier, RNA_property_boolean_get_array(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by armature_bone_layers_exec(), ED_object_add_generic_get_opts(), move_to_layer_init(), pose_armature_layers_exec(), pose_armature_layers_invoke(), and pose_bone_layers_exec().
void RNA_boolean_set (PointerRNA * ptr, const char * name, int value)
Definition at line 4114 of file rna_access.c.
References StructRNA::identifier, RNA_property_boolean_set(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by action_keymap_keyframes(), brush_edit_apply_event(), clip_keymap(), console_keymap(), ED_fileselect_set_params(), ED_keymap_animchannels(), ED_keymap_armature(), ED_keymap_curve(), ED_keymap_mesh(), ED_keymap_metaball(), ED_keymap_object(), ED_keymap_paint(), ED_keymap_screen(), ED_keymap_uvedit(), ED_marker_keymap(), ED_object_add_generic_get_opts(), ED_operatormacros_armature(), ED_operatormacros_clip(), ED_operatormacros_curve(), ED_operatormacros_mesh(), ED_operatormacros_node(), ED_operatormacros_object(), file_browse_invoke(), file_keymap(), gpencil_draw_apply_event(), graph_fmodifier_add_invoke(), graphedit_keymap_keyframes(), image_keymap(), image_replace_invoke(), image_save_as_invoke(), initTransInfo(), insert_key_menu_invoke(), keymap_particle(), linked_limit_default(), nla_keymap_channels(), nla_keymap_main(), node_keymap(), object_add_generic_invoke_options(), object_camera_add_exec(), object_mouse_select_menu(), open_invoke(), open_set_load_ui(), open_set_use_scripts(), outliner_keymap(), paint_brush_stroke_add_step(), save_set_compress(), screen_opengl_render_init(), sequencer_change_path_invoke(), sequencer_keymap(), sketch_draw_modal(), stitch_exit(), text_keymap(), transform_keymap_for_space(), ui_keymap_but_cb(), ui_set_but_default(), UI_view2d_keymap(), uiItemBooleanO(), uiLayoutOperatorButs(), view3d_keymap(), view3d_layers_invoke(), and wm_window_keymap().
void RNA_boolean_set_array (PointerRNA * ptr, const char * name, const int * values)
Definition at line 4134 of file rna_access.c.
References StructRNA::identifier, RNA_property_boolean_set_array(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by armature_bone_layers_exec(), armature_bone_layers_invoke(), BIF_do_manipulator(), move_to_layer_init(), object_add_generic_invoke_options(), pose_armature_layers_exec(), pose_armature_layers_invoke(), pose_armature_layers_showall_exec(), pose_bone_layers_exec(), and pose_bone_layers_invoke().
void RNA_collection_add (PointerRNA * ptr, const char * name, PointerRNA * r_value)
Definition at line 4425 of file rna_access.c.
References StructRNA::identifier, RNA_property_collection_add(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by brush_edit_apply_event(), gesture_lasso_apply(), gpencil_draw_apply_event(), paint_apply_event(), paint_brush_stroke_add_step(), sequencer_drop_copy(), and stitch_exit().
void RNA_collection_begin (PointerRNA * ptr, const char * name, CollectionPropertyIterator * iter)
Definition at line 4415 of file rna_access.c.
References StructRNA::identifier, RNA_property_collection_begin(), RNA_struct_find_property(), and PointerRNA::type.
void RNA_collection_clear (PointerRNA * ptr, const char * name)
Definition at line 4435 of file rna_access.c.
References StructRNA::identifier, RNA_property_collection_clear(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by gesture_lasso_apply(), sequencer_drop_copy(), and stitch_init().
int RNA_collection_length (PointerRNA * ptr, const char * name)
Definition at line 4445 of file rna_access.c.
References StructRNA::identifier, RNA_property_collection_length(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by sequencer_add_image_strip_invoke(), sequencer_add_movie_strip_invoke(), and sequencer_add_sound_strip_invoke().
int RNA_enum_bitflag_identifiers (EnumPropertyItem * item, const int value, const char ** identifier)
Definition at line 1267 of file rna_access.c.
References EnumPropertyItem::identifier, NULL, and EnumPropertyItem::value.
Referenced by pyrna_enum_bitfield_to_py(), and RNA_property_enum_bitflag_identifiers().
int RNA_enum_description (EnumPropertyItem * item, const int value, const char ** description)
Definition at line 1290 of file rna_access.c.
References EnumPropertyItem::description, EnumPropertyItem::identifier, and EnumPropertyItem::value.
Referenced by redraw_timer_exec().
int RNA_enum_get (PointerRNA * ptr, const char * name)
Definition at line 4230 of file rna_access.c.
References StructRNA::identifier, RNA_property_enum_get(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by actkeys_columnselect_exec(), actkeys_expo_exec(), actkeys_handletype_exec(), actkeys_insertkey_exec(), actkeys_ipo_exec(), actkeys_keytype_exec(), actkeys_mirror_exec(), actkeys_paste_exec(), actkeys_select_leftright_exec(), actkeys_select_leftright_invoke(), actkeys_snap_exec(), actuator_add_exec(), add_primitive_circle_exec(), add_primitive_cone_exec(), add_primitive_cylinder_exec(), align_exec(), animchannels_rearrange_exec(), animchannels_setflag_exec(), area_split_apply(), area_split_init(), area_split_menu_init(), area_split_modal(), armature_autoside_names_exec(), armature_calc_roll_exec(), armature_de_select_all_exec(), armature_merge_exec(), armature_parent_clear_exec(), armature_parent_set_exec(), armature_select_hierarchy_exec(), BL_ConvertActuators(), blender_camera_from_object(), brush_curve_preset_exec(), brush_select_exec(), brush_uv_sculpt_tool_set_exec(), clean_tracks_exec(), clear_track_path_exec(), console_delete_exec(), console_move_exec(), console_scrollback_append_exec(), controller_add_exec(), convert_exec(), de_select_all_exec(), delete_exec(), delete_key_exec(), detect_features_exec(), disable_markers_exec(), draw_actuator_action(), draw_actuator_armature(), draw_actuator_constraint(), draw_actuator_edit_object(), draw_actuator_filter_2d(), draw_actuator_game(), draw_actuator_message(), draw_actuator_motion(), draw_actuator_parent(), draw_actuator_property(), draw_actuator_random(), draw_actuator_scene(), draw_actuator_shape_action(), draw_actuator_steering(), draw_brick_actuator(), draw_brick_controller(), draw_brick_sensor(), draw_controller_python(), draw_sensor_armature(), draw_sensor_joystick(), draw_sensor_property(), draw_sensor_ray(), ED_fileselect_set_params(), ed_marker_make_links_scene_exec(), ed_marker_select_all_exec(), edbm_blend_from_shape_exec(), edbm_delete_exec(), edbm_edge_rotate_selected_exec(), edbm_merge_exec(), edbm_rotate_colors_exec(), edbm_rotate_uvs_exec(), edbm_select_all_exec(), edbm_select_axis_exec(), edbm_select_by_number_vertices_exec(), edbm_select_similar_exec(), edbm_select_vertex_path_exec(), edbm_separate_exec(), edbm_sort_faces_exec(), edbm_subdivide_exec(), edit_constraint_property_get(), effector_add_exec(), face_select_all_exec(), frame_jump_exec(), game_property_copy_exec(), game_property_new(), get_enum(), BlenderSync::get_scene_params(), BlenderSync::get_session_params(), gp_convert_layer_exec(), gpencil_draw_init(), graph_disable_markers_exec(), graph_fmodifier_add_exec(), graph_select_all_markers_exec(), graphkeys_columnselect_exec(), graphkeys_expo_exec(), graphkeys_handletype_exec(), graphkeys_insertkey_exec(), graphkeys_ipo_exec(), graphkeys_mirror_exec(), graphkeys_paste_exec(), graphkeys_select_leftright_exec(), graphkeys_select_leftright_invoke(), graphkeys_snap_exec(), group_instance_add_exec(), group_link_exec(), group_move_exec(), hide_exec(), hide_show_exec(), hide_show_invoke(), image_sample_apply(), image_unpack_exec(), initSnapping(), initTransInfo(), insert_key_exec(), keyingset_active_menu_exec(), lattice_select_all_exec(), lock_tracks_exec(), logicbricks_move_property_get(), make_links_data_exec(), make_links_scene_exec(), make_local_exec(), make_proxy_exec(), make_single_user_exec(), mball_select_all_exec(), mode_set_exec(), modifier_add_exec(), modifier_apply_exec(), move_exec(), move_select_exec(), new_node_tree_exec(), nla_fmodifier_add_exec(), nla_panel_properties(), nlaedit_add_actionclip_exec(), nlaedit_select_leftright_exec(), nlaedit_select_leftright_invoke(), nlaedit_snap_exec(), node_composit_buts_blur(), node_composit_buts_channel_matte(), node_composit_buts_color_spill(), node_composit_buts_colorbalance(), node_composit_buts_colorbalance_but(), node_composit_buts_file_output(), node_composit_buts_file_output_details(), node_composit_buts_glare(), node_composit_buts_image(), node_composit_buts_tonemap(), node_group_socket_add_exec(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_socket_remove_exec(), node_shader_buts_geometry(), node_socket_button_output_file(), node_texture_buts_proc(), object_add_exec(), object_constraint_add_exec(), object_hook_assign_exec(), object_hook_recenter_exec(), object_hook_remove_exec(), object_hook_reset_exec(), object_hook_select_exec(), object_lamp_add_exec(), object_metaball_add_exec(), object_mode_set_compat(), object_mode_set_exec(), object_origin_set_exec(), object_select_all_exec(), object_select_by_type_exec(), object_select_grouped_exec(), object_select_linked_exec(), object_select_menu_exec(), object_track_clear_exec(), outliner_action_set_exec(), outliner_animdata_operation_exec(), outliner_data_operation_exec(), outliner_group_operation_exec(), outliner_id_operation_exec(), outliner_object_operation_exec(), output_toggle_exec(), parent_clear_exec(), parent_clear_invoke(), parent_drop_exec(), parent_set_exec(), pe_select_all_exec(), pose_autoside_names_exec(), pose_bone_rotmode_exec(), pose_constraint_add_exec(), pose_de_select_all_exec(), pose_propagate_fcurve(), pose_select_grouped_exec(), pose_select_hierarchy_exec(), redraw_timer_exec(), rule_add_exec(), scene_new_exec(), sculpt_brush_stroke_init(), sculpt_update_cache_invariants(), select_all_exec(), select_groped_exec(), select_orientation_exec(), sensor_add_exec(), sequencer_add_effect_strip_exec(), sequencer_add_effect_strip_invoke(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_change_effect_input_exec(), sequencer_change_effect_type_exec(), sequencer_cut_exec(), sequencer_de_select_all_exec(), sequencer_select_active_side_exec(), sequencer_select_grouped_exec(), sequencer_select_handles_exec(), sequencer_swap_exec(), set_active_group_exec(), set_axis_exec(), set_case_exec(), set_handle_type_exec(), set_plane_exec(), set_spline_type_exec(), set_style_exec(), shape_key_move_exec(), similar_edge_select_exec(), similar_face_select_exec(), similar_vert_select_exec(), snap_cursor_exec(), snap_selection_exec(), snap_type_exec(), sound_mixdown_exec(), sound_unpack_exec(), text_convert_whitespace_exec(), text_delete_exec(), text_move_exec(), text_move_select_exec(), text_resolve_conflict_exec(), texture_paint_camera_project_exec(), texture_slot_move(), toggle_cyclic_exec(), toggle_style_exec(), track_set_exec(), transformops_data(), type_toggle_exec(), unpack_all_exec(), unwrap_exec(), uv_map_transform(), uv_sculpt_stroke_init(), v3d_editmetaball_buts(), v3d_transform_butsR(), vert_select_all_exec(), vertex_group_lock_exec(), vgroup_move_exec(), viewnumpad_exec(), vieworbit_exec(), viewpan_exec(), weight_from_bones_exec(), and weight_sample_group_exec().
int RNA_enum_icon_from_value (EnumPropertyItem * item, int value, int * icon)
Definition at line 4318 of file rna_access.c.
References EnumPropertyItem::icon, EnumPropertyItem::identifier, and EnumPropertyItem::value.
Referenced by list_item_row(), and ui_id_brush_get_icon().
int RNA_enum_id_from_value (EnumPropertyItem * item, int value, const char ** identifier)
Definition at line 4306 of file rna_access.c.
References EnumPropertyItem::identifier, and EnumPropertyItem::value.
Referenced by pyrna_prop_str().
int RNA_enum_identifier (EnumPropertyItem * item, const int value, const char ** identifier)
Definition at line 1256 of file rna_access.c.
References EnumPropertyItem::identifier, and EnumPropertyItem::value.
Referenced by RNA_property_enum_identifier(), and WM_event_print().
int RNA_enum_is_equal (struct bContext * C, PointerRNA * ptr, const char * name, const char * enumname)
Definition at line 4269 of file rna_access.c.
References StructRNA::identifier, EnumPropertyItem::identifier, MEM_freeN(), NULL, RNA_property_enum_get(), RNA_property_enum_items(), RNA_struct_find_property(), PointerRNA::type, and EnumPropertyItem::value.
int RNA_enum_name (EnumPropertyItem * item, const int value, const char ** name)
Definition at line 1279 of file rna_access.c.
References EnumPropertyItem::identifier, EnumPropertyItem::name, and EnumPropertyItem::value.
Referenced by node_blend_label(), node_filter_label(), node_math_label(), node_vect_math_label(), RNA_property_enum_name(), ui_menu_enumpropname(), and WM_key_event_string().
void RNA_enum_set (PointerRNA * ptr, const char * name, int value)
Definition at line 4243 of file rna_access.c.
References StructRNA::identifier, RNA_property_enum_set(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by action_keymap_keyframes(), actkeys_select_leftright_invoke(), area_split_invoke(), area_split_modal(), BIF_do_manipulator(), clean_tracks_invoke(), clip_keymap(), console_keymap(), do_view3d_header_buttons(), draw_group_socket(), duplicate_metaelems_invoke(), ED_keymap_animchannels(), ED_keymap_armature(), ED_keymap_curve(), ED_keymap_gpencil(), ED_keymap_mesh(), ED_keymap_metaball(), ED_keymap_object(), ED_keymap_paint(), ED_keymap_uvedit(), ED_operatormacros_action(), ED_operatormacros_armature(), ED_operatormacros_curve(), ED_operatormacros_graph(), ED_operatormacros_mesh(), ED_operatormacros_object(), edbm_subdivide_exec(), edit_constraint_invoke_properties(), graph_fmodifier_add_invoke(), graphedit_keymap_keyframes(), graphkeys_select_leftright_invoke(), image_keymap(), insert_key_menu_invoke(), keymap_brush_select(), keymap_particle(), nla_keymap_main(), nlaedit_duplicate_invoke(), outliner_parent_clear_copy(), paint_partial_visibility_keys(), parent_drop_invoke(), poselib_rename_invoke(), saveTransform(), sequencer_add_duplicate_invoke(), sequencer_cut_invoke(), sequencer_keymap(), text_keymap(), transform_keymap_for_space(), unpack_menu(), and view3d_keymap().
void RNA_enum_set_identifier (PointerRNA * ptr, const char * name, const char * id)
Definition at line 4253 of file rna_access.c.
References StructRNA::identifier, NULL, RNA_property_enum_set(), RNA_property_enum_value(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by ED_keymap_object().
int RNA_enum_value_from_id (EnumPropertyItem * item, const char * identifier, int * value)
Definition at line 4294 of file rna_access.c.
References EnumPropertyItem::identifier, and EnumPropertyItem::value.
Referenced by BPy_FloatProperty(), BPy_FloatVectorProperty(), pyop_call(), pyop_poll(), pyrna_enum_value_from_id(), uiItemEnumO_string(), uiItemEnumR_string(), and wm_user_modal_keymap_set_items().
float RNA_float_get (PointerRNA * ptr, const char * name)
Definition at line 4187 of file rna_access.c.
References StructRNA::identifier, RNA_property_float_get(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by actkeys_clean_exec(), add_primitive_circle_exec(), add_primitive_cone_exec(), add_primitive_cylinder_exec(), add_primitive_grid_exec(), add_primitive_icosphere_exec(), add_primitive_uvsphere_exec(), area_split_apply(), backimage_zoom(), blender_camera_from_object(), brush_scale_size_exec(), clean_tracks_exec(), create_subd_mesh(), cube_project_exec(), do_set_scale(), edbm_bevel_exec(), edbm_blend_from_shape_exec(), edbm_dissolve_limited_exec(), edbm_extrude_repeat_exec(), edbm_inset_exec(), edbm_noise_exec(), edbm_remove_doubles_exec(), edbm_select_linked_flat_faces_exec(), edbm_select_random_exec(), edbm_select_sharp_edges_exec(), edbm_solidify_exec(), edbm_spin_exec(), edbm_subdivide_exec(), edbm_tris_convert_to_quads_exec(), edbm_vertex_slide_exec(), DocumentExporter::exportCurrentScene(), get_float(), gpencil_draw_exec(), graphkeys_clean_exec(), graphkeys_click_insert_exec(), graphview_cursor_apply(), image_view_zoom_exec(), image_view_zoom_ratio_exec(), initTransform(), initTransInfo(), minimize_stretch_init(), object_select_random_exec(), pack_islands_exec(), paint_apply(), pose_slide_init(), remove_doubles_exec(), sculpt_update_cache_variants(), select_random_exec(), select_random_metaelems_exec(), sequencer_view_zoom_ratio_exec(), set_goal_weight_exec(), set_radius_exec(), similar_edge_select_exec(), similar_face_select_exec(), similar_vert_select_exec(), stitch_init(), uv_map_transform(), vertex_group_blend_exec(), vertex_group_clean_exec(), vertex_group_fix_exec(), vertex_group_levels_exec(), view_zoom_exec(), view_zoom_ratio_exec(), view_zoomdrag_apply(), view_zoomstep_apply(), vpaint_stroke_update_step(), weight_set_exec(), and wpaint_stroke_update_step().
void RNA_float_get_array (PointerRNA * ptr, const char * name, float * values)
Definition at line 4210 of file rna_access.c.
References StructRNA::identifier, RNA_property_float_get_array(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by add_marker_exec(), add_vertex_exec(), brush_edit_apply(), cut_links_exec(), ED_object_add_generic_get_opts(), edbm_knife_cut_exec(), edbm_screw_exec(), edbm_spin_exec(), gpencil_draw_exec(), grab_clone_apply(), image_new_exec(), image_view_pan_exec(), image_view_zoom_in_exec(), image_view_zoom_out_exec(), initSnapping(), initTransform(), paint_apply(), save_envmap(), sculpt_update_cache_variants(), select_exec(), select_linked_internal(), select_loop_exec(), sequencer_add_effect_strip_exec(), set_2d_cursor_exec(), set_clone_cursor_exec(), spin_exec(), view3d_lasso_select_exec(), view_pan_exec(), view_zoom_in_exec(), view_zoom_out_exec(), vpaint_stroke_update_step(), and wpaint_stroke_update_step().
void RNA_float_set (PointerRNA * ptr, const char * name, float value)
Definition at line 4200 of file rna_access.c.
References StructRNA::identifier, RNA_property_float_set(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by area_split_invoke(), area_split_modal(), BKE_nlameta_flush_transforms(), clean_tracks_invoke(), clip_keymap(), ed_keymap_paint_brush_size(), edbm_vertex_slide_exec(), gpencil_draw_apply_event(), graphkeys_click_insert_invoke(), graphview_cursor_setprops(), image_keymap(), image_view_zoom_invoke(), image_view_zoom_modal(), minimize_stretch_modal(), nlaedit_clear_scale_exec(), node_keymap(), pack_islands_exec(), paint_apply_event(), paint_brush_stroke_add_step(), pose_slide_modal(), recalcData_nla(), saveTransform(), sequencer_keymap(), set_scale_invoke(), set_solution_scale_invoke(), stitch_exit(), uiItemFloatO(), view_zoom_invoke(), view_zoom_modal(), view_zoomdrag_invoke(), view_zoomdrag_modal(), view_zoomin_exec(), and view_zoomout_exec().
void RNA_float_set_array (PointerRNA * ptr, const char * name, const float * values)
Definition at line 4220 of file rna_access.c.
References StructRNA::identifier, RNA_property_float_set_array(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by add_marker_invoke(), add_vertex_invoke(), brush_edit_apply_event(), ED_object_add_generic_get_opts(), edbm_screw_invoke(), edbm_spin_invoke(), gesture_lasso_apply(), gpencil_draw_apply_event(), grab_clone_modal(), image_view_pan_invoke(), image_view_pan_modal(), image_view_zoom_in_invoke(), image_view_zoom_out_invoke(), object_add_generic_invoke_options(), paint_apply_event(), paint_brush_stroke_add_step(), select_invoke(), select_linked_internal(), select_loop_invoke(), set_2d_cursor_invoke(), set_clone_cursor_invoke(), spin_invoke(), view_pan_invoke(), view_pan_modal(), view_zoom_in_invoke(), and view_zoom_out_invoke().
char* RNA_function_as_string_keywords (struct bContext * C, FunctionRNA * func, PointerRNA * ptr_default, const short as_function, const short all_args)
Definition at line 4621 of file rna_access.c.
References NULL, RNA_Function, RNA_pointer_as_string_keywords_ex(), RNA_pointer_create(), RNA_struct_find_property(), RNA_struct_iterator_property(), and PointerRNA::type.
Referenced by pyrna_func_doc_get().
int RNA_function_call (struct bContext * C, struct ReportList * reports, PointerRNA * ptr, FunctionRNA * func, ParameterList * parms)
Definition at line 5089 of file rna_access.c.
References FunctionRNA::call.
Referenced by pyrna_func_call(), RNA_function_call_direct_va(), RNA_function_call_lookup(), RNA_property_collection_add(), and RNA_property_collection_remove().
int RNA_function_call_direct (struct bContext * C, struct ReportList * reports, PointerRNA * ptr, FunctionRNA * func, const char * format, ...)
Definition at line 5113 of file rna_access.c.
References RNA_function_call_direct_va().
int RNA_function_call_direct_lookup (struct bContext * C, struct ReportList * reports, PointerRNA * ptr, const char * identifier, const char * format, ...)
Definition at line 5128 of file rna_access.c.
References RNA_function_call_direct_va(), and RNA_struct_find_function().
int RNA_function_call_direct_va (struct bContext * C, struct ReportList * reports, PointerRNA * ptr, FunctionRNA * func, const char * format, va_list args)
Definition at line 5313 of file rna_access.c.
References FunctionRNA::c_ret, ParameterIterator::data, err, i, len(), NULL, ParameterIterator::parm, PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_OUTPUT, PROP_POINTER, PROP_REQUIRED, PROP_STRING, RNA_Function, RNA_function_call(), rna_function_format_array_length(), RNA_function_identifier(), rna_function_parameter_parse(), RNA_parameter_list_begin(), RNA_parameter_list_create(), RNA_parameter_list_end(), RNA_parameter_list_free(), RNA_parameter_list_next(), RNA_pointer_create(), RNA_property_array_length(), RNA_property_flag(), RNA_property_identifier(), RNA_property_type(), RNA_struct_identifier(), strlen(), PointerRNA::type, and ParameterIterator::valid.
Referenced by RNA_function_call_direct(), RNA_function_call_direct_lookup(), and RNA_function_call_direct_va_lookup().
int RNA_function_call_direct_va_lookup (struct bContext * C, struct ReportList * reports, PointerRNA * ptr, const char * identifier, const char * format, va_list args)
Definition at line 5503 of file rna_access.c.
References RNA_function_call_direct_va(), and RNA_struct_find_function().
int RNA_function_call_lookup (struct bContext * C, struct ReportList * reports, PointerRNA * ptr, const char * identifier, ParameterList * parms)
Definition at line 5100 of file rna_access.c.
References RNA_function_call(), and RNA_struct_find_function().
int RNA_function_defined (FunctionRNA * func)
Definition at line 4811 of file rna_access.c.
References FunctionRNA::call, and NULL.
Referenced by pyrna_struct_getattro().
struct ListBase* RNA_function_defined_parameters (FunctionRNA * func) [read]
Definition at line 4826 of file rna_access.c.
References FunctionRNA::cont, and ContainerRNA::properties.
Referenced by rna_function_arg_count().
PropertyRNA* RNA_function_find_parameter (PointerRNA * ptr, FunctionRNA * func, const char * identifier)
int RNA_function_flag (FunctionRNA * func)
Definition at line 4806 of file rna_access.c.
References FunctionRNA::flag.
Referenced by bpy_class_call(), bpy_class_validate(), and rna_function_arg_count().
PropertyRNA* RNA_function_get_parameter (PointerRNA * ptr, FunctionRNA * func, int index)
const char* RNA_function_identifier (FunctionRNA * func)
Definition at line 4796 of file rna_access.c.
References FunctionRNA::identifier.
Referenced by bpy_class_call(), bpy_class_validate(), pyrna_dir_members_rna(), pyrna_func_call(), pyrna_func_doc_get(), pyrna_func_repr(), RNA_function_call_direct_va(), and RNA_struct_find_function().
const char* RNA_function_ui_description (FunctionRNA * func)
Definition at line 4801 of file rna_access.c.
References FunctionRNA::description.
Referenced by pyrna_func_doc_get().
void RNA_id_pointer_create (struct ID * id, PointerRNA * r_ptr)
Definition at line 111 of file rna_access.c.
References PointerRNA::data, PointerRNA::id, NULL, StructRNA::refine, rna_ID_refine(), and PointerRNA::type.
Referenced by acf_generic_idblock_nameprop(), acf_generic_idfill_nameprop(), achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), act_new_exec(), action_get_item_transforms(), ANIM_add_driver(), ANIM_apply_keyingset(), ANIM_channel_draw_widgets(), ANIM_copy_driver(), ANIM_list_elem_update(), ANIM_paste_driver(), ANIM_relative_keyingset_add_source(), ANIM_unit_mapping_get_factor(), BKE_animsys_evaluate_animdata(), BL_Action::BL_Action(), BL_ShapeActionActuator::BL_ShapeActionActuator(), bpy_app_generic_callback(), bpy_lib_exit(), buttons_context_path(), buttons_context_path_brush(), buttons_context_path_data(), buttons_context_path_material(), buttons_context_path_object(), buttons_context_path_texture(), buttons_context_path_world(), check_rna_path_is_valid(), copy_to_selected_button_exec(), copy_to_selected_button_poll(), create_func(), CTX_data_id_list_add(), CTX_data_id_pointer_set(), delete_keyframe(), draw_gpencil_panel(), dtar_get_prop_val(), DocumentExporter::exportCurrentScene(), DocumentImporter::finish(), font_open_exec(), font_unlink_exec(), getname_anim_fcurve(), gpencil_data_get_pointers(), graph_panel_driverVar__singleProp(), graph_panel_key_properties(), graph_panel_view(), id_search_call_cb(), id_search_cb(), id_single_user(), image_new_exec(), image_open_exec(), insert_keyframe(), new_material_exec(), new_node_tree_exec(), new_texture_exec(), new_world_exec(), object_to_mesh(), open_exec(), pastebuf_match_path_property(), pose_armature_layers_exec(), pose_armature_layers_invoke(), pose_armature_layers_showall_exec(), pose_propagate_get_refVal(), poselib_preview_init_data(), pyrna_param_to_py(), pyrna_struct_get_id_data(), rna_path_from_ID_to_idpgroup(), RNA_path_from_ID_to_struct(), RNA_pointer_recast(), RNA_property_path_from_ID_check(), text_new_exec(), text_open_exec(), uiIconFromID(), view3d_panel_object(), and what_does_obaction().
int RNA_int_get (PointerRNA * ptr, const char * name)
Definition at line 4144 of file rna_access.c.
References StructRNA::identifier, RNA_property_int_get(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by actionzone_apply(), actkeys_borderselect_exec(), add_primitive_circle_exec(), add_primitive_cone_exec(), add_primitive_cylinder_exec(), add_primitive_grid_exec(), add_primitive_icosphere_exec(), add_primitive_uvsphere_exec(), animchannels_borderselect_exec(), area_join_init(), area_move_apply(), area_move_init(), area_move_modal(), area_split_invoke(), armature_subdivide_exec(), background_image_remove_exec(), blender_camera_from_object(), bookmark_delete_exec(), border_select_exec(), border_select_graph_exec(), borderselect_exec(), change_character_exec(), change_frame_apply(), change_spacing_exec(), circle_select_exec(), clean_tracks_exec(), console_history_append_exec(), detect_features_exec(), draw_controller_header(), ED_fileselect_set_params(), ed_marker_border_select_exec(), ed_marker_move_apply(), edbm_do_smooth_vertex_exec(), edbm_extrude_repeat_exec(), edbm_knife_cut_exec(), edbm_screw_exec(), edbm_select_by_number_vertices_exec(), edbm_select_nth_exec(), edbm_spin_exec(), edbm_subdivide_exec(), edbm_vertices_randomize_exec(), file_border_select_exec(), file_border_select_modal(), file_filenum_exec(), frame_offset_exec(), game_property_remove(), gesture_circle_apply(), get_int(), graphkeys_borderselect_exec(), graphview_cursor_apply(), image_new_exec(), image_sample_line_exec(), loopcut_modal(), minimize_stretch_exec(), minimize_stretch_init(), nlaedit_borderselect_exec(), node_borderselect_exec(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_socket_remove_exec(), node_select_exec(), object_select_by_layer_exec(), outliner_border_select_exec(), pose_group_assign_exec(), pose_slide_init(), poselib_add_exec(), poselib_preview_init_data(), poselib_rename_exec(), previewrange_define_exec(), rect_from_props(), redraw_timer_exec(), rekey_exec(), render_border_exec(), repeat_history_exec(), ringsel_finish(), screen_set_exec(), select_nth_exec(), select_report_pick_exec(), seq_load_operator_info(), sequencer_add_effect_strip_exec(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_borderselect_exec(), sequencer_cut_exec(), sequencer_separate_images_exec(), sequencer_snap_exec(), sound_mixdown_exec(), stitch_init(), subdivide_exec(), text_cursor_set_exec(), text_jump_exec(), text_scroll_exec(), textbox_remove_exec(), undo_history_exec(), unwrap_exec(), view3d_borderselect_exec(), view3d_circle_select_exec(), view3d_clipping_exec(), view3d_layers_exec(), view3d_layers_invoke(), view3d_zoom_border_exec(), view_borderzoom_exec(), view_ghost_border_exec(), view_pan_apply(), viewdolly_exec(), viewzoom_exec(), wm_debug_menu_exec(), WM_gesture_lasso_invoke(), WM_gesture_lines_invoke(), and WM_gesture_straightline_invoke().
void RNA_int_get_array (PointerRNA * ptr, const char * name, int * values)
Definition at line 4167 of file rna_access.c.
References StructRNA::identifier, RNA_property_int_get_array(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by sample_color_exec(), select_linked_exec(), and set_tile_exec().
void RNA_int_set (PointerRNA * ptr, const char * name, int value)
Definition at line 4157 of file rna_access.c.
References StructRNA::identifier, RNA_property_int_set(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by area_join_invoke(), area_move_cancel(), area_move_invoke(), area_move_modal(), border_apply(), border_apply_rect(), change_frame_invoke(), change_frame_modal(), clean_tracks_invoke(), draw_group_socket(), ED_keymap_curve(), ED_keymap_mesh(), ED_keymap_object(), ED_keymap_paint(), ed_keymap_paint_brush_switch(), ED_keymap_screen(), ed_marker_move_cancel(), ed_marker_move_invoke(), ed_marker_move_modal(), file_draw_buttons(), file_keymap(), gesture_circle_apply(), graphview_cursor_setprops(), image_keymap(), loopcut_modal(), minimize_stretch_iteration(), nlaedit_select_leftright_invoke(), node_select_invoke(), pose_groups_menu_invoke(), pose_slide_invoke_common(), poselib_add_menu_invoke__replacemenu(), poselib_preview_apply(), screen_area_options_invoke(), select_report_pick_invoke(), sequencer_cut_invoke(), sequencer_generic_invoke_xy__internal(), sequencer_keymap(), sequencer_snap_invoke(), stitch_exit(), straightline_apply(), text_cursor_set_invoke(), text_keymap(), uiItemIntO(), view3d_keymap(), view3d_layers_invoke(), view_pan_invoke(), view_pan_modal(), view_scrolldown_exec(), view_scrollleft_exec(), view_scrollright_exec(), view_scrollup_exec(), viewdolly_invoke(), viewzoom_invoke(), wm_debug_menu_invoke(), and WM_gesture_circle_modal().
void RNA_int_set_array (PointerRNA * ptr, const char * name, const int * values)
Definition at line 4177 of file rna_access.c.
References StructRNA::identifier, RNA_property_int_set_array(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by sample_color_invoke(), sample_color_modal(), select_linked_invoke(), and set_tile_invoke().
void RNA_main_pointer_create (struct Main * main, PointerRNA * r_ptr)
Definition at line 104 of file rna_access.c.
References PointerRNA::data, PointerRNA::id, main(), NULL, RNA_BlendData, and PointerRNA::type.
Referenced by BPY_rna_module(), BPY_update_rna_module(), draw_actuator_constraint(), draw_actuator_message(), draw_sensor_collision(), draw_sensor_ray(), outliner_build_tree(), and search_id_collection().
void RNA_parameter_get (ParameterList * parms, PropertyRNA * parm, void ** value)
Definition at line 4984 of file rna_access.c.
References ParameterIterator::data, NULL, ParameterIterator::parm, RNA_parameter_list_begin(), RNA_parameter_list_end(), RNA_parameter_list_next(), and ParameterIterator::valid.
Referenced by RNA_parameter_get_lookup().
void RNA_parameter_get_lookup (ParameterList * parms, const char * identifier, void ** value)
Definition at line 5002 of file rna_access.c.
References FunctionRNA::cont, ListBase::first, ParameterList::func, PropertyRNA::next, ContainerRNA::properties, RNA_parameter_get(), and RNA_property_identifier().
int RNA_parameter_length_get (ParameterList * parms, PropertyRNA * parm)
Definition at line 5044 of file rna_access.c.
References ParameterIterator::data, len(), ParameterIterator::parm, RNA_parameter_length_get_data(), RNA_parameter_list_begin(), RNA_parameter_list_end(), RNA_parameter_list_next(), and ParameterIterator::valid.
int RNA_parameter_length_get_data (ParameterList * parms, PropertyRNA * parm, void * data)
void RNA_parameter_length_set (ParameterList * parms, PropertyRNA * parm, int length)
Definition at line 5063 of file rna_access.c.
References ParameterIterator::data, ParameterIterator::parm, RNA_parameter_length_set_data(), RNA_parameter_list_begin(), RNA_parameter_list_end(), RNA_parameter_list_next(), and ParameterIterator::valid.
void RNA_parameter_length_set_data (ParameterList * parms, PropertyRNA * parm, void * data, int length)
int RNA_parameter_list_arg_count (ParameterList * parms)
Definition at line 4941 of file rna_access.c.
References ParameterList::arg_count.
Referenced by pyrna_func_call().
void RNA_parameter_list_begin (ParameterList * parms, ParameterIterator * iter)
Definition at line 4951 of file rna_access.c.
References FunctionRNA::cont, ParameterIterator::data, ParameterList::data, ListBase::first, ParameterList::func, NULL, ParameterIterator::offset, ParameterIterator::parm, ParameterIterator::parms, ContainerRNA::properties, rna_parameter_size_alloc(), ParameterIterator::size, and ParameterIterator::valid.
Referenced by bpy_class_call(), pyrna_func_call(), RNA_function_call_direct_va(), RNA_parameter_get(), RNA_parameter_length_get(), RNA_parameter_length_set(), and RNA_parameter_set().
ParameterList* RNA_parameter_list_create (ParameterList * parms, PointerRNA * ptr, FunctionRNA * func)
void RNA_parameter_list_end (ParameterIterator * iter)
void RNA_parameter_list_free (ParameterList * parms)
Definition at line 4911 of file rna_access.c.
References ParameterDynAlloc::array, BLI_freelistN(), FunctionRNA::cont, ParameterList::data, ListBase::first, PropertyRNA::flag, ParameterList::func, MEM_freeN(), PropertyRNA::next, NULL, PROP_COLLECTION, PROP_DYNAMIC, ContainerRNA::properties, rna_parameter_size_alloc(), and PropertyRNA::type.
Referenced by pyrna_func_call(), RNA_function_call_direct_va(), RNA_property_collection_add(), and RNA_property_collection_remove().
void RNA_parameter_list_next (ParameterIterator * iter)
Definition at line 4967 of file rna_access.c.
References ParameterIterator::data, ParameterList::data, PropertyRNA::next, NULL, ParameterIterator::offset, ParameterIterator::parm, ParameterIterator::parms, rna_parameter_size_alloc(), ParameterIterator::size, and ParameterIterator::valid.
Referenced by bpy_class_call(), pyrna_func_call(), RNA_function_call_direct_va(), RNA_parameter_get(), RNA_parameter_length_get(), RNA_parameter_length_set(), and RNA_parameter_set().
int RNA_parameter_list_ret_count (ParameterList * parms)
Definition at line 4946 of file rna_access.c.
References ParameterList::ret_count.
int RNA_parameter_list_size (ParameterList * parms)
Definition at line 4936 of file rna_access.c.
References ParameterList::alloc_size.
void RNA_parameter_set (ParameterList * parms, PropertyRNA * parm, const void * value)
Definition at line 5015 of file rna_access.c.
References ParameterIterator::data, ParameterIterator::parm, RNA_parameter_list_begin(), RNA_parameter_list_end(), RNA_parameter_list_next(), ParameterIterator::size, and ParameterIterator::valid.
Referenced by RNA_parameter_set_lookup().
void RNA_parameter_set_lookup (ParameterList * parms, const char * identifier, const void * value)
Definition at line 5031 of file rna_access.c.
References FunctionRNA::cont, ListBase::first, ParameterList::func, PropertyRNA::next, ContainerRNA::properties, RNA_parameter_set(), and RNA_property_identifier().
char* RNA_path_append (const char * path, PointerRNA * ptr, PropertyRNA * prop, int intkey, const char * strkey)
char* RNA_path_back (const char * path)
Definition at line 3846 of file rna_access.c.
References BLI_strdup(), i, MEM_freeN(), NULL, and rna_path_token().
char* RNA_path_from_ID_to_property (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 4071 of file rna_access.c.
References BLI_sprintfN(), BLI_strdup(), PointerRNA::data, PointerRNA::id, PropertyRNA::magic, MEM_freeN(), NULL, RNA_MAGIC, RNA_path_from_ID_to_struct(), and RNA_property_identifier().
Referenced by add_keyingset_button_exec(), copy_data_path_button_exec(), copy_to_selected_button_exec(), copy_to_selected_button_poll(), delete_key_button_exec(), get_driver_path_hack(), id_data_find_fcurve(), insert_key_button_exec(), key_get_curValue_rnaPath(), pyrna_prop_path_from_id(), pyrna_prop_repr(), pyrna_struct_anim_args_parse(), pyrna_struct_path_from_id(), remove_keyingset_button_exec(), rna_get_fcurve(), RNA_property_path_from_ID_check(), and ui_but_anim_expression_create().
char* RNA_path_from_ID_to_struct (PointerRNA * ptr)
Definition at line 4033 of file rna_access.c.
References BLI_strdup(), PointerRNA::data, PointerRNA::id, StructRNA::nested, NULL, StructRNA::path, RNA_id_pointer_create(), rna_path_from_ID_to_idpgroup(), RNA_property_identifier(), RNA_PropertyGroup, RNA_struct_find_nested(), RNA_struct_is_a(), RNA_struct_is_ID(), and PointerRNA::type.
Referenced by action_get_item_transforms(), fcurves_to_pchan_links_get(), node_group_make_from_selected(), node_group_ungroup(), pyrna_struct_path_from_id(), pyrna_struct_repr(), and RNA_path_from_ID_to_property().
int RNA_path_resolve (PointerRNA * ptr, const char * path, PointerRNA * r_ptr, PropertyRNA ** r_prop)
Definition at line 3597 of file rna_access.c.
References NULL, and RNA_path_resolve_full().
Referenced by achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), ANIM_add_driver(), ANIM_apply_keyingset(), ANIM_channel_draw_widgets(), ANIM_copy_driver(), ANIM_list_elem_update(), ANIM_paste_driver(), ANIM_unit_mapping_get_factor(), animsys_write_rna_setting(), check_rna_path_is_valid(), copy_to_selected_button_exec(), copy_to_selected_button_poll(), delete_keyframe(), getname_anim_fcurve(), graph_panel_key_properties(), insert_keyframe(), insert_keyframe_direct(), nlaevalchan_verify(), pastebuf_match_path_property(), pose_propagate_get_refVal(), radial_control_get_path(), RNA_property_path_from_ID_check(), and RNA_struct_find_property().
int RNA_path_resolve_full (PointerRNA * ptr, const char * path, PointerRNA * r_ptr, PropertyRNA ** r_prop, int * index)
Definition at line 3602 of file rna_access.c.
References PointerRNA::data, i, IDP_GetPropertyFromGroup(), len(), MEM_freeN(), NULL, PROP_COLLECTION, PROP_POINTER, tRnaUpdateCacheElem::ptr, RNA_MAX_ARRAY_DIMENSION, rna_path_token(), RNA_property_array_dimension(), RNA_property_array_item_index(), RNA_property_collection_lookup_int(), RNA_property_collection_lookup_string(), RNA_property_collection_type_get(), RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), RNA_struct_idprops(), and rna_token_strip_quotes().
Referenced by dtar_get_prop_val(), pyrna_struct_anim_args_parse(), pyrna_struct_path_resolve(), and RNA_path_resolve().
void RNA_pointer_add (PointerRNA * ptr, const char * name)
Definition at line 4405 of file rna_access.c.
References StructRNA::identifier, RNA_property_pointer_add(), RNA_struct_find_property(), and PointerRNA::type.
char* RNA_pointer_as_string (struct bContext * C, PointerRNA * ptr)
Definition at line 4491 of file rna_access.c.
References BLI_dynstr_append(), BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), MEM_freeN(), RNA_property_as_string(), RNA_property_identifier(), RNA_STRUCT_BEGIN, and RNA_STRUCT_END.
Referenced by RNA_property_as_string().
char* RNA_pointer_as_string_keywords (struct bContext * C, PointerRNA * ptr, PointerRNA * ptr_default, const short skip_optional_value, const short all_args)
Definition at line 4610 of file rna_access.c.
References RNA_pointer_as_string_keywords_ex(), RNA_struct_iterator_property(), and PointerRNA::type.
Referenced by WM_operator_pystring().
char* RNA_pointer_as_string_keywords_ex (struct bContext * C, PointerRNA * ptr, PointerRNA * ptr_default, const short skip_optional_value, const short all_args, PropertyRNA * iterprop)
Definition at line 4527 of file rna_access.c.
References BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), BLI_strdup(), FALSE, MEM_freeN(), NULL, PROP_NEVER_NULL, PROP_OUTPUT, PROP_POINTER, PROP_REQUIRED, RNA_PROP_BEGIN, RNA_PROP_END, RNA_property_as_string(), RNA_property_flag(), RNA_property_identifier(), RNA_property_type(), RNA_struct_find_property(), and TRUE.
Referenced by RNA_function_as_string_keywords(), and RNA_pointer_as_string_keywords().
void RNA_pointer_create (struct ID * id, StructRNA * type, void * data, PointerRNA * r_ptr)
Definition at line 135 of file rna_access.c.
References data, PointerRNA::data, PointerRNA::id, NULL, StructRNA::refine, rna_ID_refine(), and PointerRNA::type.
Referenced by acf_gpl_name_prop(), acf_group_name_prop(), acf_shapekey_nameprop(), action_get_item_transforms(), active_node_panel(), actuator_add_exec(), ANIM_relative_keyingset_add_source(), ANIM_uiTemplate_fmodifier_draw(), armature_bone_layers_exec(), BKE_nlameta_flush_transforms(), BL_ConvertActuators(), bpy_class_call(), BPy_init_modules(), buttons_context_path_bone(), buttons_context_path_particle(), buttons_context_path_pose_bone(), buttons_texture_modifier_foreach(), buttons_texture_users_find_nodetree(), buttons_texture_users_from_context(), colorband_buttons_large(), colorband_buttons_small(), controller_add_exec(), create_func(), CTX_data_list_add(), CTX_data_pointer_set(), draw_actuator_action(), draw_actuator_armature(), draw_actuator_message(), draw_actuator_motion(), draw_actuator_property(), draw_actuator_random(), draw_actuator_shape_action(), draw_actuator_state(), draw_constraint(), draw_modifier(), draw_modifier__cycles(), draw_modifier__envelope(), draw_modifier__fn_generator(), draw_modifier__generator(), draw_modifier__limits(), draw_modifier__noise(), draw_modifier__stepped(), draw_sensor_actuator(), draw_sensor_armature(), draw_sensor_keyboard(), draw_sensor_property(), fcurves_to_pchan_links_get(), get_driver_path_hack(), gp_drawui_layer(), gpencil_data_get_pointers(), graph_panel_drivers(), graph_panel_driverVar__locDiff(), graph_panel_driverVar__rotDiff(), graph_panel_driverVar__singleProp(), graph_panel_driverVar__transChan(), graph_panel_key_properties(), graph_panel_properties(), graph_panel_view(), id_data_find_fcurve(), image_panel_curves(), image_save_as_draw(), key_get_curValue_rnaPath(), logic_buttons(), logic_buttons_new(), menu_add_shortcut(), menu_change_shortcut(), nla_panel_context(), nlaedit_clear_scale_exec(), nlastrip_evaluate_controls(), node_animation_properties(), node_draw_basis(), node_draw_group(), node_group_make_from_selected(), node_group_ungroup(), node_socket_button_color(), node_socket_button_components(), node_socket_button_default(), node_socket_button_output_file(), node_texture_buts_proc(), node_update_basis(), operator_enum_search_cb(), operator_wrapper(), outliner_build_tree(), outliner_draw_restrictbuts(), pose_bone_layers_exec(), pose_slide_apply_props(), pyop_as_string(), pyop_getinstance(), PYOP_wrap_macro_define(), pyrna_dir_members_rna(), pyrna_func_call(), pyrna_param_to_py(), pyrna_py_to_prop(), pyrna_srna_contains_pointer_prop_srna(), pyrna_struct_driver_add(), pyrna_struct_get_rna_type(), pyrna_subtype_set_rna(), radial_control_get_properties(), recalcData_nla(), BlenderSession::render(), RNA_function_as_string_keywords(), RNA_function_call_direct_va(), rna_function_parameter_parse(), RNA_property_update_cache_add(), rna_raw_access(), RNA_struct_find_function(), screenshot_draw(), sensor_add_exec(), sequencer_change_path_exec(), toolbox_invoke(), ui_node_draw_input(), ui_node_draw_node(), uiItemsFullEnumO(), uiLayoutOperatorButs(), uiTemplateHeader3D(), uiTemplatePreview(), v3d_editarmature_buts(), v3d_editmetaball_buts(), v3d_editvertex_buts(), v3d_posearmature_buts(), wm_operator_create(), WM_operator_properties_create(), and WM_operator_properties_create_ptr().
PointerRNA RNA_pointer_get (PointerRNA * ptr, const char * name)
Retrieve the named property from PointerRNA.
Definition at line 4379 of file rna_access.c.
References StructRNA::identifier, PointerRNA_NULL, RNA_property_pointer_get(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by blender_camera_from_object(), draw_actuator_sound(), draw_actuator_steering(), DocumentExporter::exportCurrentScene(), DocumentImporter::finish(), BlenderSync::get_scene_params(), BlenderSync::get_session_params(), BlenderSync::get_session_pause(), list_item_icon_get(), node_composit_buts_file_output(), node_composit_buts_file_output_details(), node_composit_buts_renderlayers(), node_shader_buts_geometry(), node_socket_button_output_file(), object_ray_visibility(), rna_idp_path(), uiTemplateKeymapItemProperties(), v3d_editarmature_buts(), v3d_transform_butsR(), and view3d_ob_drop_copy().
void RNA_pointer_recast (PointerRNA * ptr, PointerRNA * r_ptr)
Definition at line 204 of file rna_access.c.
References StructRNA::base, PointerRNA::data, PointerRNA::id, RNA_id_pointer_create(), rna_pointer_inherit_refine(), RNA_struct_is_ID(), and PointerRNA::type.
Referenced by pyrna_struct_type_recast().
void RNA_pointer_set (PointerRNA * ptr, const char * name, PointerRNA ptr_value)
Definition at line 4393 of file rna_access.c.
References StructRNA::identifier, RNA_property_pointer_set(), RNA_struct_find_property(), and PointerRNA::type.
int RNA_property_animateable (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1406 of file rna_access.c.
References PointerRNA::data, PropertyRNA::flag, PointerRNA::id, id_type_can_have_animdata(), PROP_ANIMATABLE, PROP_EDITABLE, and rna_ensure_property().
Referenced by add_driver_button_exec(), add_keyingset_button_exec(), animsys_write_rna_setting(), copy_driver_button_exec(), do_outliner_drivers_editop(), do_outliner_keyingset_editop(), insert_key_button_exec(), nlaevalchan_verify(), paste_driver_button_exec(), pyrna_struct_anim_args_parse(), rna_get_fcurve(), and ui_but_menu().
int RNA_property_animated (PointerRNA * ptr, PropertyRNA * prop)
int RNA_property_array_check (PropertyRNA * prop)
Definition at line 803 of file rna_access.c.
References rna_ensure_property_array_check().
Referenced by dtar_get_prop_val(), initTransform(), node_animation_properties(), pose_propagate_get_refVal(), pyrna_param_to_py(), pyrna_prop_CreatePyObject(), pyrna_prop_str(), pyrna_prop_to_py(), pyrna_py_to_prop(), pyrna_struct_anim_args_parse(), RNA_property_boolean_get(), RNA_property_boolean_get_array(), RNA_property_boolean_get_default(), RNA_property_boolean_get_default_array(), RNA_property_boolean_get_default_index(), RNA_property_boolean_get_index(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_boolean_set_index(), RNA_property_float_get(), RNA_property_float_get_array(), RNA_property_float_get_default(), RNA_property_float_get_default_array(), RNA_property_float_get_default_index(), RNA_property_float_get_index(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_float_set_index(), RNA_property_int_get(), RNA_property_int_get_array(), RNA_property_int_get_default_array(), RNA_property_int_get_index(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_int_set_index(), saveTransform(), ui_get_but_val(), ui_tooltip_create(), uiDefAutoButsRNA(), and uiItemFullR().
int RNA_property_array_dimension (PointerRNA * ptr, PropertyRNA * prop, int length[])
Definition at line 809 of file rna_access.c.
References PropertyRNA::arraydimension, rna_ensure_property(), and rna_ensure_property_multi_array_length().
Referenced by copy_values(), py_to_array_index(), pyrna_array_contains_py(), pyrna_math_object_from_array(), pyrna_prop_array_length(), pyrna_prop_array_subscript_slice(), pyrna_py_from_array_index(), pyrna_py_to_prop_array_index(), RNA_path_resolve_full(), ui_item_array(), validate_array(), and validate_array_length().
char RNA_property_array_item_char (PropertyRNA * prop, int index)
Definition at line 829 of file rna_access.c.
References ELEM, ELEM8, PROP_ACCELERATION, PROP_AXISANGLE, PROP_COLOR, PROP_COLOR_GAMMA, PROP_COORDS, PROP_DIRECTION, PROP_EULER, PROP_QUATERNION, PROP_TRANSLATION, PROP_VELOCITY, PROP_XYZ, PROP_XYZ_LENGTH, rna_ensure_property(), and PropertyRNA::subtype.
Referenced by getname_anim_fcurve(), and ui_item_array().
int RNA_property_array_item_index (PropertyRNA * prop, char name)
Definition at line 852 of file rna_access.c.
References ELEM, ELEM6, PROP_ACCELERATION, PROP_AXISANGLE, PROP_COLOR, PROP_COLOR_GAMMA, PROP_DIRECTION, PROP_EULER, PROP_QUATERNION, PROP_TRANSLATION, PROP_VELOCITY, PROP_XYZ, rna_ensure_property(), and PropertyRNA::subtype.
Referenced by RNA_path_resolve_full().
int RNA_property_array_length (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 798 of file rna_access.c.
References rna_ensure_property_array_length().
Referenced by ANIM_add_driver(), ANIM_apply_keyingset(), animsys_write_rna_setting(), delete_key_button_exec(), delete_keyframe(), do_outliner_drivers_editop(), dtar_get_prop_val(), eyedropper_sample(), foreach_attr_type(), foreach_parse_args(), getname_anim_fcurve(), handle_layer_buttons(), insert_key_button_exec(), insert_keyframe(), mathutils_rna_vector_set(), nladata_flush_channels(), node_animation_properties(), pose_propagate_get_refVal(), pyrna_array_contains_py(), pyrna_math_object_from_array(), pyrna_param_to_py(), pyrna_prop_array_ass_subscript(), pyrna_prop_array_bool(), pyrna_prop_array_length(), pyrna_struct_anim_args_parse(), pyrna_struct_path_resolve(), radial_control_get_path(), RNA_function_call_direct_va(), RNA_property_as_string(), RNA_property_copy(), RNA_property_float_get_array_range(), RNA_property_int_get_array_range(), RNA_property_reset(), rna_raw_access(), setting_get_rna_value(), tree_element_to_path(), ui_but_menu(), ui_def_but_rna(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_get_but_vectorf(), ui_item_rna_size(), ui_layer_but_cb(), ui_set_but_soft_range(), ui_set_but_val(), ui_set_but_vectorf(), uiDefAutoButR(), uiItemFullR(), uiTemplateLayers(), validate_array_length(), and widget_swatch().
char* RNA_property_as_string (struct bContext * C, PointerRNA * ptr, PropertyRNA * prop)
Definition at line 4637 of file rna_access.c.
References BLI_dynstr_append(), BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), BLI_strescape(), FALSE, i, EnumPropertyItem::identifier, len(), length(), MEM_freeN(), MEM_mallocN(), NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_ENUM_FLAG, PROP_FLOAT, PROP_INT, PROP_POINTER, PROP_STRING, CollectionPropertyIterator::ptr, RNA_pointer_as_string(), RNA_property_array_length(), RNA_property_boolean_get(), RNA_property_boolean_get_index(), RNA_property_collection_begin(), RNA_property_collection_end(), RNA_property_collection_next(), RNA_property_enum_get(), RNA_property_enum_identifier(), RNA_property_enum_items(), RNA_property_flag(), RNA_property_float_get(), RNA_property_float_get_index(), RNA_property_int_get(), RNA_property_int_get_index(), RNA_property_pointer_get(), RNA_property_string_get(), RNA_property_string_length(), RNA_property_type(), TRUE, CollectionPropertyIterator::valid, and EnumPropertyItem::value.
Referenced by RNA_pointer_as_string(), and RNA_pointer_as_string_keywords_ex().
int RNA_property_boolean_get (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1615 of file rna_access.c.
References BLI_assert, BoolPropertyRNA::defaultvalue, BoolPropertyRNA::get, IDP_Int, PROP_BOOLEAN, rna_idproperty_check(), RNA_property_array_check(), and RNA_property_type().
Referenced by ANIM_add_driver(), dtar_get_prop_val(), initTransform(), pose_propagate_get_refVal(), pyrna_prop_to_py(), radial_control_get_properties(), RNA_boolean_get(), RNA_property_as_string(), RNA_property_boolean_get_array(), RNA_property_copy(), rna_raw_access(), setting_get_rna_value(), ui_get_but_val(), and uiItemFullR().
void RNA_property_boolean_get_array (PointerRNA * ptr, PropertyRNA * prop, int * values)
Definition at line 1660 of file rna_access.c.
References PropertyRNA::arraydimension, BLI_assert, BoolPropertyRNA::defaultarray, BoolPropertyRNA::getarray, IDP_Array, IDProperty::len, PROP_BOOLEAN, rna_idproperty_check(), RNA_property_array_check(), RNA_property_boolean_get(), RNA_property_type(), and PropertyRNA::totarraylength.
Referenced by initTransform(), prop_subscript_ass_array_slice(), pyrna_array_contains_py(), pyrna_prop_array_subscript_slice(), RNA_boolean_get_array(), RNA_property_boolean_get_index(), RNA_property_boolean_set_index(), RNA_property_copy(), rna_raw_access(), and ui_item_array().
int RNA_property_boolean_get_default (PointerRNA * ptr, PropertyRNA * prop)
void RNA_property_boolean_get_default_array (PointerRNA * ptr, PropertyRNA * prop, int * values)
int RNA_property_boolean_get_default_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 1793 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_BOOLEAN, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_boolean_get_default_array(), and RNA_property_type().
Referenced by RNA_property_reset().
int RNA_property_boolean_get_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 1684 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_BOOLEAN, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_boolean_get_array(), and RNA_property_type().
Referenced by ANIM_add_driver(), dtar_get_prop_val(), pose_propagate_get_refVal(), pyrna_array_index(), RNA_property_as_string(), RNA_property_copy(), setting_get_rna_value(), ui_get_but_val(), uiItemFullR(), and uiTemplateLayers().
void RNA_property_boolean_set (PointerRNA * ptr, PropertyRNA * prop, int value)
Definition at line 1631 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, IDPropertyTemplate::i, PropertyRNA::identifier, IDP_AddToGroup(), IDP_INT, IDP_Int, IDP_New(), PROP_BOOLEAN, PROP_EDITABLE, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_array_check(), RNA_property_type(), RNA_struct_idprops(), and BoolPropertyRNA::set.
Referenced by animsys_write_rna_setting(), nladata_flush_channels(), pyrna_py_to_prop(), RNA_boolean_set(), RNA_property_boolean_set_array(), RNA_property_copy(), RNA_property_reset(), rna_raw_access(), saveTransform(), and ui_set_but_val().
void RNA_property_boolean_set_array (PointerRNA * ptr, PropertyRNA * prop, const int * values)
Definition at line 1708 of file rna_access.c.
References IDPropertyTemplate::array, PropertyRNA::arraydimension, BLI_assert, PropertyRNA::flag, PropertyRNA::identifier, IDP_AddToGroup(), IDP_ARRAY, IDP_Array, IDP_INT, IDP_Int, IDP_New(), IDPropertyTemplate::len, IDProperty::len, PROP_BOOLEAN, PROP_EDITABLE, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_array_check(), RNA_property_boolean_set(), RNA_property_type(), RNA_struct_idprops(), BoolPropertyRNA::setarray, PropertyRNA::totarraylength, and IDPropertyTemplate::type.
Referenced by prop_subscript_ass_array_slice(), pyrna_py_to_array(), RNA_boolean_set_array(), RNA_property_boolean_set_index(), RNA_property_copy(), RNA_property_reset(), rna_raw_access(), and saveTransform().
void RNA_property_boolean_set_index (PointerRNA * ptr, PropertyRNA * prop, int index, int value)
Definition at line 1744 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_BOOLEAN, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_boolean_get_array(), RNA_property_boolean_set_array(), and RNA_property_type().
Referenced by animsys_write_rna_setting(), bool_set_index(), handle_layer_buttons(), nladata_flush_channels(), pyrna_py_to_prop_array_index(), RNA_property_copy(), RNA_property_reset(), ui_layer_but_cb(), and ui_set_but_val().
void RNA_property_collection_add (PointerRNA * ptr, PropertyRNA * prop, PointerRNA * r_ptr)
Definition at line 2705 of file rna_access.c.
References BLI_assert, PointerRNA::data, PropertyRNA::flag, FUNC_USE_CONTEXT, PropertyRNA::identifier, IDP_AddToGroup(), IDP_AppendArray(), IDP_GetIndexArray(), IDP_GROUP, IDP_New(), IDP_NewIDPArray(), CollectionPropertyRNA::item_type, IDProperty::len, MEM_freeN(), NULL, PROP_COLLECTION, PROP_IDPROPERTY, RNA_function_call(), rna_idproperty_check(), RNA_parameter_list_create(), RNA_parameter_list_free(), rna_pointer_inherit_id(), RNA_property_type(), RNA_struct_idprops(), and PointerRNA::type.
Referenced by file_sfile_to_operator(), pyrna_prop_collection_idprop_add(), pyrna_py_to_prop(), and RNA_collection_add().
int RNA_property_collection_assign_int (PointerRNA * ptr, PropertyRNA * prop, const int key, const PointerRNA * assign_ptr)
Definition at line 2952 of file rna_access.c.
References CollectionPropertyRNA::assignint, BLI_assert, PROP_COLLECTION, rna_ensure_property(), and RNA_property_type().
Referenced by pyrna_prop_collection_ass_subscript_int().
void RNA_property_collection_begin (PointerRNA * ptr, PropertyRNA * prop, CollectionPropertyIterator * iter)
Definition at line 2627 of file rna_access.c.
References CollectionPropertyRNA::begin, BLI_assert, PropertyRNA::flag, IDP_IDPArray, CollectionPropertyIterator::idprop, IDProperty::len, NULL, CollectionPropertyIterator::parent, CollectionPropertyIterator::prop, PROP_COLLECTION, PROP_IDPROPERTY, tRnaUpdateCacheElem::ptr, rna_idproperty_check(), rna_iterator_array_begin(), rna_property_collection_get_idp(), RNA_property_type(), and CollectionPropertyIterator::valid.
Referenced by pyrna_prop_collection_bool(), pyrna_prop_collection_iter_CreatePyObject(), pyrna_prop_collection_subscript_slice(), RNA_collection_begin(), RNA_property_as_string(), RNA_property_collection_length(), RNA_property_collection_lookup_index(), RNA_property_collection_lookup_int(), RNA_property_collection_lookup_string(), and RNA_property_collection_raw_array().
void RNA_property_collection_clear (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2842 of file rna_access.c.
References BLI_assert, IDP_ResizeIDPArray(), PROP_COLLECTION, rna_idproperty_check(), and RNA_property_type().
Referenced by file_sfile_to_operator(), pyrna_prop_collection_idprop_clear(), and RNA_collection_clear().
void RNA_property_collection_end (CollectionPropertyIterator * iter)
Definition at line 2669 of file rna_access.c.
References CollectionPropertyRNA::end, CollectionPropertyIterator::idprop, CollectionPropertyIterator::prop, rna_ensure_property(), and rna_iterator_array_end().
Referenced by pyrna_prop_collection_bool(), pyrna_prop_collection_iter_dealloc(), pyrna_prop_collection_subscript_slice(), RNA_property_as_string(), RNA_property_collection_length(), RNA_property_collection_lookup_index(), RNA_property_collection_lookup_int(), RNA_property_collection_lookup_string(), and RNA_property_collection_raw_array().
int RNA_property_collection_length (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2679 of file rna_access.c.
References BLI_assert, IDProperty::len, length(), CollectionPropertyRNA::length, PROP_COLLECTION, rna_idproperty_check(), RNA_property_collection_begin(), RNA_property_collection_end(), RNA_property_collection_next(), RNA_property_type(), and CollectionPropertyIterator::valid.
Referenced by foreach_parse_args(), pyrna_prop_collection_ass_subscript(), pyrna_prop_collection_ass_subscript_int(), pyrna_prop_collection_length(), pyrna_prop_collection_subscript(), pyrna_prop_collection_subscript_int(), RNA_collection_length(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_change_path_exec(), uiDefAutoButR(), uiTemplateList(), and wm_link_append_exec().
int RNA_property_collection_lookup_index (PointerRNA * ptr, PropertyRNA * prop, PointerRNA * t_ptr)
Definition at line 2852 of file rna_access.c.
References BLI_assert, PointerRNA::data, PROP_COLLECTION, CollectionPropertyIterator::ptr, RNA_property_collection_begin(), RNA_property_collection_end(), RNA_property_collection_next(), RNA_property_type(), and CollectionPropertyIterator::valid.
int RNA_property_collection_lookup_int (PointerRNA * ptr, PropertyRNA * prop, int key, PointerRNA * r_ptr)
Definition at line 2873 of file rna_access.c.
References BLI_assert, i, CollectionPropertyRNA::lookupint, PROP_COLLECTION, CollectionPropertyIterator::ptr, rna_ensure_property(), RNA_property_collection_begin(), RNA_property_collection_end(), RNA_property_collection_next(), RNA_property_type(), and CollectionPropertyIterator::valid.
Referenced by node_buts_rgb(), node_buts_value(), pyrna_prop_collection_subscript_int(), rna_idp_path(), and RNA_path_resolve_full().
int RNA_property_collection_lookup_string (PointerRNA * ptr, PropertyRNA * prop, const char * key, PointerRNA * r_ptr)
Definition at line 2904 of file rna_access.c.
References BLI_assert, PointerRNA::data, CollectionPropertyRNA::lookupstring, MEM_freeN(), StructRNA::nameproperty, PROP_COLLECTION, CollectionPropertyIterator::ptr, rna_ensure_property(), RNA_property_collection_begin(), RNA_property_collection_end(), RNA_property_collection_next(), RNA_property_string_get_alloc(), RNA_property_type(), strlen(), PointerRNA::type, and CollectionPropertyIterator::valid.
Referenced by draw_actuator_armature(), draw_sensor_armature(), pyrna_basetype_getattro(), pyrna_prop_collection_contains(), pyrna_prop_collection_get(), pyrna_prop_collection_subscript_str(), RNA_path_resolve_full(), RNA_struct_find_property(), and ui_set_but_string().
int RNA_property_collection_move (PointerRNA * ptr, PropertyRNA * prop, int key, int pos)
Definition at line 2812 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, IDP_IDPArray, IDProperty::len, len(), PROP_COLLECTION, PROP_IDPROPERTY, rna_idproperty_check(), and RNA_property_type().
Referenced by pyrna_prop_collection_idprop_move().
void RNA_property_collection_next (CollectionPropertyIterator * iter)
Definition at line 2655 of file rna_access.c.
References CollectionPropertyIterator::idprop, CollectionPropertyRNA::next, CollectionPropertyIterator::prop, rna_ensure_property(), rna_iterator_array_next(), rna_property_collection_get_idp(), and CollectionPropertyIterator::valid.
Referenced by pyrna_prop_collection_iter_next(), pyrna_prop_collection_subscript_slice(), RNA_property_as_string(), RNA_property_collection_length(), RNA_property_collection_lookup_index(), RNA_property_collection_lookup_int(), and RNA_property_collection_lookup_string().
int RNA_property_collection_raw_array (PointerRNA * ptr, PropertyRNA * prop, PropertyRNA * itemprop, RawArray * array)
Definition at line 2974 of file rna_access.c.
References RawArray::array, BLI_assert, PointerRNA::data, PropertyRNA::flag, if(), CollectionPropertyIterator::internal, RawArray::len, NULL, PROP_COLLECTION, PROP_RAW_ACCESS, PROP_RAW_ARRAY, CollectionPropertyIterator::ptr, PropertyRNA::rawoffset, PropertyRNA::rawtype, RNA_property_collection_begin(), RNA_property_collection_end(), RNA_property_editable(), RNA_property_type(), RawArray::stride, RawArray::type, and CollectionPropertyIterator::valid.
Referenced by rna_raw_access().
int RNA_property_collection_raw_get (struct ReportList * reports, PointerRNA * ptr, PropertyRNA * prop, const char * propname, void * array, RawPropertyType type, int len)
Definition at line 3351 of file rna_access.c.
References rna_raw_access().
Referenced by foreach_getset().
int RNA_property_collection_raw_set (struct ReportList * reports, PointerRNA * ptr, PropertyRNA * prop, const char * propname, void * array, RawPropertyType type, int len)
Definition at line 3357 of file rna_access.c.
References rna_raw_access().
Referenced by foreach_getset().
int RNA_property_collection_remove (PointerRNA * ptr, PropertyRNA * prop, int key)
Definition at line 2764 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, FUNC_USE_CONTEXT, IDP_IDPArray, IDP_ResizeIDPArray(), IDProperty::len, len(), NULL, PROP_COLLECTION, PROP_IDPROPERTY, RNA_function_call(), rna_idproperty_check(), RNA_parameter_list_create(), RNA_parameter_list_free(), and RNA_property_type().
Referenced by pyrna_prop_collection_idprop_remove().
int RNA_property_collection_type_get (PointerRNA * ptr, PropertyRNA * prop, PointerRNA * r_ptr)
Definition at line 2966 of file rna_access.c.
References BLI_assert, PROP_COLLECTION, tRnaUpdateCacheElem::ptr, rna_ensure_property(), RNA_property_type(), and PointerRNA::type.
Referenced by pyrna_dir_members_py(), pyrna_prop_collection_getattro(), pyrna_prop_collection_setattro(), pyrna_prop_dir(), pyrna_prop_str(), pyrna_py_to_prop(), and RNA_path_resolve_full().
int RNA_property_copy (PointerRNA * ptr, PointerRNA * fromptr, PropertyRNA * prop, int index)
Definition at line 5613 of file rna_access.c.
References len(), MEM_callocN(), MEM_freeN(), NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_POINTER, PROP_STRING, RNA_property_array_length(), RNA_property_boolean_get(), RNA_property_boolean_get_array(), RNA_property_boolean_get_index(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_boolean_set_index(), RNA_property_enum_get(), RNA_property_enum_set(), RNA_property_float_get(), RNA_property_float_get_array(), RNA_property_float_get_index(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_float_set_index(), RNA_property_int_get(), RNA_property_int_get_array(), RNA_property_int_get_index(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_int_set_index(), RNA_property_pointer_get(), RNA_property_pointer_set(), RNA_property_string_get_alloc(), RNA_property_string_set(), and RNA_property_type().
Referenced by copy_to_selected_button_exec().
const char* RNA_property_description (PropertyRNA * prop)
Definition at line 768 of file rna_access.c.
References rna_ensure_property_description().
Referenced by ui_but_menu(), ui_tooltip_create(), and uiItemMenuEnumR().
int RNA_property_editable (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1366 of file rna_access.c.
References PointerRNA::data, PropertyRNA::editable, PropertyRNA::flag, PointerRNA::id, PROP_EDITABLE, PROP_LIB_EXCEPTION, and rna_ensure_property().
Referenced by copy_to_selected_button_exec(), copy_to_selected_button_poll(), eyedropper_init(), id_single_user(), reset_default_button_exec(), reset_default_button_poll(), RNA_property_collection_raw_array(), rna_raw_access(), template_ID(), ui_def_but_rna(), ui_set_but_string(), and ui_set_but_val().
int RNA_property_editable_flag (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1376 of file rna_access.c.
References PropertyRNA::editable, PropertyRNA::flag, PROP_EDITABLE, and rna_ensure_property().
Referenced by mathutils_rna_matrix_set(), mathutils_rna_vector_set(), mathutils_rna_vector_set_index(), pyrna_prop_array_ass_subscript(), and pyrna_struct_setattro().
int RNA_property_editable_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 1386 of file rna_access.c.
References PointerRNA::data, PropertyRNA::editable, PropertyRNA::flag, PointerRNA::id, PropertyRNA::itemeditable, PROP_EDITABLE, PROP_LIB_EXCEPTION, and rna_ensure_property().
int RNA_property_enum_bitflag_identifiers (struct bContext * C, PointerRNA * ptr, PropertyRNA * prop, const int value, const char ** identifier)
Definition at line 1334 of file rna_access.c.
References MEM_freeN(), NULL, RNA_enum_bitflag_identifiers(), and RNA_property_enum_items().
Referenced by pyrna_enum_to_py().
int RNA_property_enum_get (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2459 of file rna_access.c.
References BLI_assert, EnumPropertyRNA::defaultvalue, EnumPropertyRNA::get, IDP_Int, PROP_ENUM, rna_idproperty_check(), and RNA_property_type().
Referenced by actuator_add_exec(), controller_add_exec(), dtar_get_prop_val(), DocumentExporter::exportCurrentScene(), get_enum_identifier(), list_item_row(), node_composit_buts_renderlayers(), node_socket_button_output_file(), pose_propagate_get_refVal(), poselib_remove_exec(), pyrna_prop_to_py(), pyrna_rotation_euler_order_get(), RNA_enum_get(), RNA_enum_is_equal(), RNA_property_as_string(), RNA_property_copy(), sensor_add_exec(), setting_get_rna_value(), ui_def_but_rna(), ui_get_but_val(), ui_set_but_val(), and uiItemFullR().
int RNA_property_enum_get_default (PointerRNA * ptr, PropertyRNA * prop)
int RNA_property_enum_identifier (struct bContext * C, PointerRNA * ptr, PropertyRNA * prop, const int value, const char ** identifier)
Definition at line 1301 of file rna_access.c.
References MEM_freeN(), NULL, RNA_enum_identifier(), and RNA_property_enum_items().
Referenced by get_enum_identifier(), BlenderSync::get_session_params(), node_composit_buts_renderlayers(), pyrna_enum_to_py(), and RNA_property_as_string().
void RNA_property_enum_items (struct bContext * C, PointerRNA * ptr, PropertyRNA * prop, EnumPropertyItem ** item, int * totitem, int * free)
Definition at line 1152 of file rna_access.c.
References PropertyRNA::flag, EnumPropertyRNA::item, EnumPropertyRNA::itemf, NULL, PROP_ENUM_NO_CONTEXT, rna_ensure_property(), and EnumPropertyRNA::totitem.
Referenced by operator_enum_search_cb(), pyrna_enum_as_string(), pyrna_enum_to_py(), pyrna_prop_to_enum_bitfield(), RNA_enum_is_equal(), RNA_property_as_string(), RNA_property_enum_bitflag_identifiers(), RNA_property_enum_identifier(), RNA_property_enum_items_gettexted(), RNA_property_enum_name(), and RNA_property_enum_value().
void RNA_property_enum_items_gettexted (struct bContext * C, PointerRNA * ptr, PropertyRNA * prop, EnumPropertyItem ** item, int * totitem, int * free)
Definition at line 1183 of file rna_access.c.
References BLF_gettext(), BLF_pgettext(), BLF_translate_iface(), EnumPropertyItem::description, i, EnumPropertyItem::identifier, MEM_callocN(), EnumPropertyItem::name, RNA_property_enum_items(), and PropertyRNA::translation_context.
Referenced by ui_def_but_rna(), ui_item_enum_expand(), ui_menu_enumpropname(), ui_tooltip_create(), uiItemEnumO_string(), uiItemEnumR_string(), uiItemsEnumR(), and uiItemsFullEnumO().
int RNA_property_enum_name (struct bContext * C, PointerRNA * ptr, PropertyRNA * prop, const int value, const char ** name)
Definition at line 1318 of file rna_access.c.
References MEM_freeN(), NULL, RNA_enum_name(), and RNA_property_enum_items().
Referenced by actuator_add_exec(), controller_add_exec(), list_item_row(), node_socket_button_output_file(), and sensor_add_exec().
void* RNA_property_enum_py_data_get (PropertyRNA * prop)
Definition at line 2509 of file rna_access.c.
References BLI_assert, PROP_ENUM, EnumPropertyRNA::py_data, and RNA_property_type().
Referenced by bpy_props_enum_itemf().
void RNA_property_enum_set (PointerRNA * ptr, PropertyRNA * prop, int value)
Definition at line 2474 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, IDPropertyTemplate::i, PropertyRNA::identifier, IDP_AddToGroup(), IDP_INT, IDP_Int, IDP_New(), PROP_EDITABLE, PROP_ENUM, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_type(), RNA_struct_idprops(), and EnumPropertyRNA::set.
Referenced by animsys_write_rna_setting(), DocumentImporter::finish(), mathutils_rna_vector_set(), nladata_flush_channels(), operator_enum_call_cb(), pyrna_py_to_prop(), RNA_enum_set(), RNA_enum_set_identifier(), RNA_property_copy(), RNA_property_reset(), saveTransform(), ui_set_but_val(), uiItemEnumO_ptr(), uiItemEnumO_ptr__internal(), uiItemEnumO_string(), uiItemEnumO_value(), and uiItemsFullEnumO().
int RNA_property_enum_value (struct bContext * C, PointerRNA * ptr, PropertyRNA * prop, const char * identifier, int * value)
Definition at line 1229 of file rna_access.c.
References EnumPropertyItem::identifier, MEM_freeN(), NULL, RNA_property_enum_items(), and EnumPropertyItem::value.
Referenced by pyrna_string_to_enum(), and RNA_enum_set_identifier().
int RNA_property_flag (PropertyRNA * prop)
Definition at line 788 of file rna_access.c.
References PropertyRNA::flag, and rna_ensure_property().
Referenced by bpy_class_call(), bpy_class_validate(), bpy_props_enum_itemf(), id_search_cb(), py_to_array(), pyrna_enum_to_py(), pyrna_func_call(), pyrna_math_object_from_array(), pyrna_param_to_py(), pyrna_prop_collection_type_check(), pyrna_prop_CreatePyObject(), pyrna_py_to_prop(), pyrna_srna_contains_pointer_prop_srna(), pyrna_struct_is_property_hidden(), rna_function_arg_count(), RNA_function_call_direct_va(), RNA_pointer_as_string_keywords_ex(), RNA_property_as_string(), rna_search_cb(), template_ID(), template_keymap_item_properties(), ui_check_but(), ui_is_but_sel(), ui_set_but_val(), uiDefAutoButsRNA(), uiItemFullR(), validate_array_length(), and WM_operator_properties_reset().
int RNA_property_float_clamp (PointerRNA * ptr, PropertyRNA * prop, float * value)
Definition at line 1056 of file rna_access.c.
References max, min, and RNA_property_float_range().
Referenced by mathutils_rna_vector_set_index(), pyrna_py_to_prop(), and pyrna_py_to_prop_array_index().
float RNA_property_float_get (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2048 of file rna_access.c.
References BLI_assert, FloatPropertyRNA::defaultvalue, FloatPropertyRNA::get, IDP_Double, IDP_Float, IDP_FLOAT, PROP_FLOAT, rna_idproperty_check(), RNA_property_array_check(), RNA_property_type(), and IDProperty::type.
Referenced by ANIM_add_driver(), dtar_get_prop_val(), edbm_select_similar_exec(), pose_propagate_get_refVal(), pose_slide_apply_props(), pyrna_prop_to_py(), radial_control_invoke(), radial_control_paint_tex(), RNA_float_get(), RNA_property_as_string(), RNA_property_copy(), RNA_property_float_get_array(), rna_raw_access(), setting_get_rna_value(), ui_get_but_val(), and ui_tooltip_create().
void RNA_property_float_get_array (PointerRNA * ptr, PropertyRNA * prop, float * values)
Definition at line 2101 of file rna_access.c.
References PropertyRNA::arraydimension, BLI_assert, FloatPropertyRNA::defaultarray, FloatPropertyRNA::getarray, i, IDP_Array, IDP_FLOAT, IDProperty::len, PROP_FLOAT, rna_idproperty_check(), RNA_property_array_check(), RNA_property_float_get(), RNA_property_type(), IDProperty::subtype, and PropertyRNA::totarraylength.
Referenced by do_picker_rna_cb(), eyedropper_sample(), initTransform(), mathutils_rna_matrix_get(), mathutils_rna_vector_get(), prop_subscript_ass_array_slice(), pyrna_array_contains_py(), pyrna_math_object_from_array(), pyrna_prop_array_subscript_slice(), radial_control_modal(), radial_control_paint_cursor(), radial_control_paint_tex(), radial_control_set_initial_mouse(), RNA_float_get_array(), RNA_property_copy(), RNA_property_float_get_array_range(), RNA_property_float_get_index(), RNA_property_float_set_index(), rna_raw_access(), uiBlockPicker(), and uiTemplateColorWheel().
void RNA_property_float_get_array_range (PointerRNA * ptr, PropertyRNA * prop, float values[2])
Definition at line 2131 of file rna_access.c.
References i, MAX2, MEM_freeN(), MEM_mallocN(), MIN2, RNA_property_array_length(), and RNA_property_float_get_array().
Referenced by ui_set_but_soft_range().
float RNA_property_float_get_default (PointerRNA * ptr, PropertyRNA * prop)
void RNA_property_float_get_default_array (PointerRNA * ptr, PropertyRNA * prop, float * values)
float RNA_property_float_get_default_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 2289 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_FLOAT, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_float_get_default_array(), and RNA_property_type().
Referenced by RNA_property_reset().
float RNA_property_float_get_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 2168 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_FLOAT, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_float_get_array(), and RNA_property_type().
Referenced by ANIM_add_driver(), dtar_get_prop_val(), mathutils_rna_vector_get_index(), pose_propagate_get_refVal(), pyrna_array_index(), RNA_property_as_string(), RNA_property_copy(), setting_get_rna_value(), ui_get_but_val(), ui_get_but_vectorf(), ui_tooltip_create(), and widget_swatch().
void RNA_property_float_range (PointerRNA * ptr, PropertyRNA * prop, float * hardmin, float * hardmax)
Definition at line 976 of file rna_access.c.
References FLT_MAX, FloatPropertyRNA::hardmax, FloatPropertyRNA::hardmin, IDP_Double, IDP_DOUBLE, IDP_GetPropertyTypeFromGroup(), PropertyRNA::magic, FloatPropertyRNA::range, rna_ensure_property(), rna_idproperty_ui(), and RNA_MAGIC.
Referenced by mathutils_rna_vector_set(), prop_subscript_ass_array_slice(), RNA_property_float_clamp(), and ui_def_but_rna().
void RNA_property_float_set (PointerRNA * ptr, PropertyRNA * prop, float value)
Definition at line 2068 of file rna_access.c.
References BLI_assert, IDPropertyTemplate::f, PropertyRNA::flag, PropertyRNA::identifier, IDP_AddToGroup(), IDP_Double, IDP_Float, IDP_FLOAT, IDP_New(), PROP_EDITABLE, PROP_FLOAT, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_array_check(), RNA_property_type(), RNA_struct_idprops(), FloatPropertyRNA::set, and IDProperty::type.
Referenced by animsys_write_rna_setting(), edbm_select_similar_exec(), DocumentImporter::finish(), nladata_flush_channels(), pose_slide_apply_props(), pyrna_py_to_prop(), radial_control_set_value(), RNA_float_set(), RNA_property_copy(), RNA_property_float_set_array(), RNA_property_reset(), rna_raw_access(), saveTransform(), and ui_set_but_val().
void RNA_property_float_set_array (PointerRNA * ptr, PropertyRNA * prop, const float * values)
Definition at line 2193 of file rna_access.c.
References IDPropertyTemplate::array, PropertyRNA::arraydimension, BLI_assert, PropertyRNA::flag, i, PropertyRNA::identifier, IDP_AddToGroup(), IDP_ARRAY, IDP_Array, IDP_Double, IDP_Float, IDP_FLOAT, IDP_New(), IDPropertyTemplate::len, IDProperty::len, PROP_EDITABLE, PROP_FLOAT, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_array_check(), RNA_property_float_set(), RNA_property_type(), RNA_struct_idprops(), FloatPropertyRNA::setarray, IDProperty::subtype, PropertyRNA::totarraylength, IDPropertyTemplate::type, and IDProperty::type.
Referenced by eyedropper_sample(), mathutils_rna_matrix_set(), mathutils_rna_vector_set(), prop_subscript_ass_array_slice(), pyrna_py_to_array(), RNA_float_set_array(), RNA_property_copy(), RNA_property_float_set_index(), RNA_property_reset(), rna_raw_access(), and saveTransform().
void RNA_property_float_set_index (PointerRNA * ptr, PropertyRNA * prop, int index, float value)
Definition at line 2240 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_FLOAT, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_float_get_array(), RNA_property_float_set_array(), and RNA_property_type().
Referenced by animsys_write_rna_setting(), float_set_index(), mathutils_rna_vector_set_index(), nladata_flush_channels(), pyrna_py_to_prop_array_index(), RNA_property_copy(), RNA_property_reset(), ui_set_but_val(), and ui_set_but_vectorf().
void RNA_property_float_ui_range (PointerRNA * ptr, PropertyRNA * prop, float * softmin, float * softmax, float * step, float * precision)
Definition at line 1010 of file rna_access.c.
References FLT_MAX, IDP_Double, IDP_DOUBLE, IDP_GetPropertyTypeFromGroup(), PropertyRNA::magic, MAX2, MIN2, FloatPropertyRNA::precision, FloatPropertyRNA::range, rna_ensure_property(), rna_idproperty_ui(), RNA_MAGIC, FloatPropertyRNA::softmax, FloatPropertyRNA::softmin, and FloatPropertyRNA::step.
Referenced by radial_control_invoke(), ui_def_but_rna(), ui_set_but_soft_range(), uiBlockPicker(), and uiTemplateColorWheel().
const char* RNA_property_identifier (PropertyRNA * prop)
Definition at line 763 of file rna_access.c.
References rna_ensure_property_identifier().
Referenced by ANIM_channel_draw_widgets(), bpy_class_validate(), file_panel_check_prop(), image_save_as_draw_check_prop(), insert_key_button_exec(), mathutils_rna_matrix_set(), mathutils_rna_vector_set(), mathutils_rna_vector_set_index(), operator_enum_search_cb(), pastebuf_match_path_property(), py_to_array_index(), pyrna_enum_to_py(), pyrna_func_call(), pyrna_prop_array_ass_subscript(), pyrna_prop_path_from_id(), pyrna_prop_repr(), pyrna_prop_str(), pyrna_prop_to_enum_bitfield(), pyrna_prop_validity_check(), pyrna_py_to_prop(), pyrna_pydict_to_props(), pyrna_srna_contains_pointer_prop_srna(), pyrna_struct_setattro(), RNA_function_call_direct_va(), RNA_parameter_get_lookup(), RNA_parameter_set_lookup(), RNA_path_append(), RNA_path_from_ID_to_property(), RNA_path_from_ID_to_struct(), RNA_pointer_as_string(), RNA_pointer_as_string_keywords_ex(), screenshot_draw_check_prop(), template_keymap_item_properties(), ui_but_menu(), ui_intro_button(), ui_tooltip_create(), validate_array(), validate_array_length(), visualkey_can_use(), visualkey_get_value(), WM_menu_invoke(), wm_operator_create(), and WM_operator_properties_reset().
int RNA_property_int_clamp (PointerRNA * ptr, PropertyRNA * prop, int * value)
Definition at line 1075 of file rna_access.c.
References max, min, and RNA_property_int_range().
Referenced by pyrna_py_to_prop(), and pyrna_py_to_prop_array_index().
int RNA_property_int_get (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1817 of file rna_access.c.
References BLI_assert, IntPropertyRNA::defaultvalue, IntPropertyRNA::get, IDP_Int, PROP_INT, rna_idproperty_check(), RNA_property_array_check(), and RNA_property_type().
Referenced by ANIM_add_driver(), dtar_get_prop_val(), pose_propagate_get_refVal(), pose_slide_apply_props(), pyrna_prop_to_py(), radial_control_invoke(), RNA_int_get(), RNA_property_as_string(), RNA_property_copy(), RNA_property_int_get_array(), rna_raw_access(), setting_get_rna_value(), ui_get_but_val(), ui_handle_list_event(), and uiTemplateList().
void RNA_property_int_get_array (PointerRNA * ptr, PropertyRNA * prop, int * values)
Definition at line 1861 of file rna_access.c.
References PropertyRNA::arraydimension, BLI_assert, IntPropertyRNA::defaultarray, IntPropertyRNA::getarray, IDP_Array, IDProperty::len, PROP_INT, rna_idproperty_check(), RNA_property_array_check(), RNA_property_int_get(), RNA_property_type(), and PropertyRNA::totarraylength.
Referenced by prop_subscript_ass_array_slice(), pyrna_array_contains_py(), pyrna_prop_array_subscript_slice(), RNA_int_get_array(), RNA_property_copy(), RNA_property_int_get_array_range(), RNA_property_int_get_index(), RNA_property_int_set_index(), and rna_raw_access().
void RNA_property_int_get_array_range (PointerRNA * ptr, PropertyRNA * prop, int values[2])
Definition at line 1885 of file rna_access.c.
References i, MAX2, MEM_freeN(), MEM_mallocN(), MIN2, RNA_property_array_length(), and RNA_property_int_get_array().
Referenced by ui_set_but_soft_range().
int RNA_property_int_get_default (PointerRNA * ptr, PropertyRNA * prop)
void RNA_property_int_get_default_array (PointerRNA * ptr, PropertyRNA * prop, int * values)
int RNA_property_int_get_default_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 2027 of file rna_access.c.
References len(), MEM_callocN(), MEM_freeN(), rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, and RNA_property_int_get_default_array().
Referenced by RNA_property_reset().
int RNA_property_int_get_index (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 1922 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_INT, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_int_get_array(), and RNA_property_type().
Referenced by ANIM_add_driver(), dtar_get_prop_val(), pose_propagate_get_refVal(), pyrna_array_index(), RNA_property_as_string(), RNA_property_copy(), setting_get_rna_value(), and ui_get_but_val().
void RNA_property_int_range (PointerRNA * ptr, PropertyRNA * prop, int * hardmin, int * hardmax)
Definition at line 901 of file rna_access.c.
References IntPropertyRNA::hardmax, IntPropertyRNA::hardmin, IDP_GetPropertyTypeFromGroup(), IDP_Int, IDP_INT, PropertyRNA::magic, IntPropertyRNA::range, rna_ensure_property(), rna_idproperty_ui(), and RNA_MAGIC.
Referenced by prop_subscript_ass_array_slice(), RNA_property_int_clamp(), ui_def_but_rna(), ui_handle_list_event(), and uiTemplateList().
void RNA_property_int_set (PointerRNA * ptr, PropertyRNA * prop, int value)
Definition at line 1833 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, IDPropertyTemplate::i, PropertyRNA::identifier, IDP_AddToGroup(), IDP_INT, IDP_Int, IDP_New(), PROP_EDITABLE, PROP_INT, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_array_check(), RNA_property_type(), RNA_struct_idprops(), and IntPropertyRNA::set.
Referenced by animsys_write_rna_setting(), nladata_flush_channels(), pose_slide_apply_props(), pyrna_py_to_prop(), radial_control_set_value(), RNA_int_set(), RNA_property_copy(), RNA_property_int_set_array(), RNA_property_reset(), rna_raw_access(), ui_handle_list_event(), and ui_set_but_val().
void RNA_property_int_set_array (PointerRNA * ptr, PropertyRNA * prop, const int * values)
Definition at line 1946 of file rna_access.c.
References IDPropertyTemplate::array, PropertyRNA::arraydimension, BLI_assert, PropertyRNA::flag, PropertyRNA::identifier, IDP_AddToGroup(), IDP_ARRAY, IDP_Array, IDP_INT, IDP_Int, IDP_New(), IDPropertyTemplate::len, IDProperty::len, PROP_EDITABLE, PROP_INT, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_array_check(), RNA_property_int_set(), RNA_property_type(), RNA_struct_idprops(), IntPropertyRNA::setarray, PropertyRNA::totarraylength, and IDPropertyTemplate::type.
Referenced by prop_subscript_ass_array_slice(), pyrna_py_to_array(), RNA_int_set_array(), RNA_property_copy(), RNA_property_int_set_index(), RNA_property_reset(), and rna_raw_access().
void RNA_property_int_set_index (PointerRNA * ptr, PropertyRNA * prop, int index, int value)
Definition at line 1982 of file rna_access.c.
References BLI_assert, len(), MEM_callocN(), MEM_freeN(), PROP_INT, rna_ensure_property_array_length(), RNA_MAX_ARRAY_LENGTH, RNA_property_array_check(), RNA_property_int_get_array(), RNA_property_int_set_array(), and RNA_property_type().
Referenced by animsys_write_rna_setting(), int_set_index(), nladata_flush_channels(), pyrna_py_to_prop_array_index(), RNA_property_copy(), RNA_property_reset(), and ui_set_but_val().
void RNA_property_int_ui_range (PointerRNA * ptr, PropertyRNA * prop, int * softmin, int * softmax, int * step)
Definition at line 935 of file rna_access.c.
References IDP_GetPropertyTypeFromGroup(), IDP_Int, IDP_INT, PropertyRNA::magic, MAX2, MIN2, IntPropertyRNA::range, rna_ensure_property(), rna_idproperty_ui(), RNA_MAGIC, IntPropertyRNA::softmax, IntPropertyRNA::softmin, and IntPropertyRNA::step.
Referenced by radial_control_invoke(), ui_def_but_rna(), and ui_set_but_soft_range().
int RNA_property_is_idprop (PropertyRNA * prop)
Definition at line 4483 of file rna_access.c.
References PropertyRNA::magic, and RNA_MAGIC.
int RNA_property_is_set (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 4458 of file rna_access.c.
References IDProperty::flag, PropertyRNA::flag, PropertyRNA::identifier, IDP_FLAG_GHOST, NULL, PROP_IDPROPERTY, and rna_idproperty_find().
Referenced by edbm_select_similar_exec(), initTransform(), poselib_remove_exec(), pyrna_struct_is_property_set(), RNA_struct_property_is_set(), saveTransform(), and WM_menu_invoke().
int RNA_property_multi_array_length (PointerRNA * ptr, PropertyRNA * prop, int dimension)
Definition at line 820 of file rna_access.c.
References len(), rna_ensure_property_multi_array_length(), and RNA_MAX_ARRAY_DIMENSION.
Referenced by pyrna_prop_array_length(), and pyrna_py_from_array_index().
int RNA_property_path_from_ID_check (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1430 of file rna_access.c.
References PointerRNA::data, FALSE, PointerRNA::id, MEM_freeN(), RNA_id_pointer_create(), RNA_path_from_ID_to_property(), RNA_path_resolve(), and TRUE.
Referenced by ui_but_menu().
void RNA_property_pointer_add (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2576 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, IDPropertyTemplate::i, StructRNA::identifier, PropertyRNA::identifier, IDP_AddToGroup(), IDP_GROUP, IDP_New(), PROP_IDPROPERTY, PROP_POINTER, rna_idproperty_check(), RNA_property_type(), RNA_struct_idprops(), and PointerRNA::type.
Referenced by RNA_pointer_add(), and RNA_property_pointer_get().
PointerRNA RNA_property_pointer_get (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2518 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, PointerPropertyRNA::get, PointerRNA_NULL, PROP_IDPROPERTY, PROP_POINTER, rna_idproperty_check(), rna_pointer_inherit_refine(), RNA_property_pointer_add(), RNA_property_pointer_get(), RNA_property_type(), and PointerPropertyRNA::type.
Referenced by act_new_exec(), buttons_texture_context_compute(), id_search_menu(), node_composit_buts_image(), open_invoke(), pyrna_prop_str(), pyrna_prop_to_py(), pyrna_py_to_prop(), RNA_path_resolve_full(), RNA_pointer_get(), RNA_property_as_string(), RNA_property_copy(), RNA_property_pointer_get(), template_ID(), template_id_cb(), template_keymap_item_properties(), template_texture_select(), ui_get_but_string(), uiDefAutoButR(), uiTemplateColorRamp(), uiTemplateCurveMapping(), uiTemplateHistogram(), uiTemplateImage(), uiTemplateMarker(), uiTemplateMovieClip(), uiTemplateTrack(), uiTemplateVectorscope(), uiTemplateWaveform(), wm_operator_create(), and WM_operator_properties_sanitize().
PointerRNA RNA_property_pointer_get_default (PointerRNA * ptr, PropertyRNA * prop)
int RNA_property_pointer_poll (PointerRNA * ptr, PropertyRNA * prop, PointerRNA * value)
Definition at line 1125 of file rna_access.c.
References PropertyRNA::identifier, PointerPropertyRNA::poll, PROP_POINTER, rna_ensure_property(), and PropertyRNA::type.
Referenced by id_search_cb(), and rna_search_cb().
void RNA_property_pointer_remove (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2599 of file rna_access.c.
References BLI_assert, PropertyRNA::identifier, StructRNA::identifier, IDP_FreeProperty(), IDP_RemFromGroup(), MEM_freeN(), PROP_POINTER, rna_idproperty_check(), RNA_property_type(), RNA_struct_idprops(), and PointerRNA::type.
void RNA_property_pointer_set (PointerRNA * ptr, PropertyRNA * prop, PointerRNA ptr_value)
Definition at line 2545 of file rna_access.c.
References BLI_assert, PointerRNA::data, PropertyRNA::flag, PointerRNA::id, NULL, PROP_ID_SELF_CHECK, PROP_NEVER_NULL, PROP_POINTER, rna_idproperty_check(), RNA_property_type(), and PointerPropertyRNA::set.
Referenced by act_new_exec(), font_open_exec(), font_unlink_exec(), id_search_call_cb(), id_single_user(), image_new_exec(), image_open_exec(), new_material_exec(), new_node_tree_exec(), new_texture_exec(), new_world_exec(), open_exec(), pyrna_py_to_prop(), RNA_pointer_set(), RNA_property_copy(), RNA_property_reset(), template_id_cb(), text_new_exec(), text_open_exec(), and ui_set_but_string().
StructRNA* RNA_property_pointer_type (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1102 of file rna_access.c.
References CollectionPropertyRNA::item_type, PROP_COLLECTION, PROP_POINTER, rna_ensure_property(), RNA_UnknownType, PointerPropertyRNA::type, PropertyRNA::type, and PointerPropertyRNA::typef.
Referenced by pyrna_param_to_py(), pyrna_prop_collection_type_check(), pyrna_py_to_prop(), pyrna_srna_contains_pointer_prop_srna(), rna_function_parameter_parse(), rna_raw_access(), RNA_struct_find_nested(), search_id_collection(), ui_but_add_search(), ui_template_id(), uiDefAutoButR(), uiItemPointerR(), uiTemplateList(), and WM_operator_properties_sanitize().
void* RNA_property_py_data_get (PropertyRNA * prop)
Definition at line 793 of file rna_access.c.
References PropertyRNA::py_data.
Referenced by bpy_prop_update_cb().
RawPropertyType RNA_property_raw_type (PropertyRNA * prop)
Definition at line 3331 of file rna_access.c.
References PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_RAW_FLOAT, PROP_RAW_INT, PROP_RAW_UNSET, PropertyRNA::rawtype, and PropertyRNA::type.
Referenced by foreach_attr_type().
int RNA_property_reset (PointerRNA * ptr, PropertyRNA * prop, int index)
Definition at line 5516 of file rna_access.c.
References len(), MEM_callocN(), MEM_freeN(), NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_POINTER, PROP_STRING, RNA_property_array_length(), RNA_property_boolean_get_default(), RNA_property_boolean_get_default_array(), RNA_property_boolean_get_default_index(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_boolean_set_index(), RNA_property_enum_get_default(), RNA_property_enum_set(), RNA_property_float_get_default(), RNA_property_float_get_default_array(), RNA_property_float_get_default_index(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_float_set_index(), RNA_property_int_get_default(), RNA_property_int_get_default_array(), RNA_property_int_get_default_index(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_int_set_index(), RNA_property_pointer_get_default(), RNA_property_pointer_set(), RNA_property_string_get_default_alloc(), RNA_property_string_set(), and RNA_property_type().
Referenced by reset_default_button_exec().
int RNA_property_string_default_length (PointerRNA * ptr, PropertyRNA * prop)
void RNA_property_string_get (PointerRNA * ptr, PropertyRNA * prop, char * value)
Definition at line 2313 of file rna_access.c.
References BLI_assert, StringPropertyRNA::defaultvalue, StringPropertyRNA::get, IDP_String, IDP_STRING_SUB_BYTE, IDProperty::len, PROP_STRING, rna_idproperty_check(), RNA_property_type(), and IDProperty::subtype.
Referenced by file_operator_to_sfile(), RNA_property_as_string(), RNA_property_string_get_alloc(), RNA_string_get(), and WM_operator_filesel_ensure_ext_imtype().
char* RNA_property_string_get_alloc (PointerRNA * ptr, PropertyRNA * prop, char * fixedbuf, int fixedlen, int * r_len)
Definition at line 2339 of file rna_access.c.
References BLI_assert, length(), MEM_mallocN(), PROP_STRING, RNA_property_string_get(), RNA_property_string_length(), and RNA_property_type().
Referenced by file_browse_invoke(), getname_anim_fcurve(), list_item_row(), pyrna_prop_to_py(), RNA_property_collection_lookup_string(), RNA_property_copy(), RNA_string_get_alloc(), RNA_struct_name_get_alloc(), and ui_get_but_string().
void RNA_property_string_get_default (PointerRNA * ptr, PropertyRNA * prop, char * value)
char* RNA_property_string_get_default_alloc (PointerRNA * ptr, PropertyRNA * prop, char * fixedbuf, int fixedlen)
Definition at line 2430 of file rna_access.c.
References BLI_assert, length(), MEM_callocN(), PROP_STRING, RNA_property_string_default_length(), RNA_property_string_get_default(), and RNA_property_type().
Referenced by RNA_property_reset().
int RNA_property_string_length (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 2373 of file rna_access.c.
References BLI_assert, StringPropertyRNA::defaultvalue, IDP_String, IDP_STRING_SUB_BYTE, IDProperty::len, StringPropertyRNA::length, PROP_STRING, rna_idproperty_check(), RNA_property_type(), strlen(), and IDProperty::subtype.
Referenced by RNA_property_as_string(), RNA_property_string_get_alloc(), and RNA_string_length().
int RNA_property_string_maxlength (PropertyRNA * prop)
Definition at line 1096 of file rna_access.c.
References StringPropertyRNA::maxlength, and rna_ensure_property().
Referenced by RNA_property_string_set(), and ui_def_but_rna().
void RNA_property_string_set (PointerRNA * ptr, PropertyRNA * prop, const char * value)
Definition at line 2398 of file rna_access.c.
References BLI_assert, PropertyRNA::flag, PropertyRNA::identifier, IDP_AddToGroup(), IDP_AssignString(), IDP_NewString(), PROP_EDITABLE, PROP_STRING, rna_idproperty_check(), rna_idproperty_touch(), RNA_property_string_maxlength(), RNA_property_type(), RNA_struct_idprops(), and StringPropertyRNA::set.
Referenced by file_browse_exec(), pyrna_py_to_prop(), RNA_property_copy(), RNA_property_reset(), RNA_string_set(), sequencer_change_path_exec(), ui_set_but_string(), and WM_operator_filesel_ensure_ext_imtype().
PropertySubType RNA_property_subtype (PropertyRNA * prop)
Definition at line 778 of file rna_access.c.
References rna_ensure_property(), and PropertyRNA::subtype.
Referenced by ANIM_unit_mapping_get_factor(), eyedropper_sample(), file_browse_exec(), foreach_attr_type(), graph_panel_key_properties(), insert_keyframe(), pyrna_math_object_from_array(), pyrna_param_to_py(), pyrna_prop_to_py(), pyrna_py_to_prop(), radial_control_invoke(), ui_block_func_COL(), ui_check_but(), ui_draw_but_HSV_v(), ui_draw_but_HSVCIRCLE(), ui_handle_menu_event(), ui_is_but_utf8(), ui_item_array(), ui_item_rna_size(), ui_item_with_label(), ui_ndofedit_but_HSVCUBE(), ui_numedit_but_HSVCUBE(), uiButGetUnitType(), uiDefAutoButR(), and widget_swatch().
PropertyType RNA_property_type (PropertyRNA * prop)
Definition at line 773 of file rna_access.c.
References rna_ensure_property(), and PropertyRNA::type.
Referenced by ANIM_add_driver(), animsys_write_rna_setting(), dtar_get_prop_val(), eyedropper_sample(), foreach_parse_args(), id_search_cb(), insert_keyframe_direct(), list_item_row(), nladata_flush_channels(), node_composit_buts_image(), operator_enum_search_cb(), outliner_draw_rnabuts(), pose_propagate_get_refVal(), pose_slide_apply_props(), prop_subscript_ass_array_slice(), pyrna_array_contains_py(), pyrna_array_index(), pyrna_dir_members_py(), pyrna_math_object_from_array(), pyrna_param_to_py(), pyrna_prop_array_subscript_slice(), pyrna_prop_CreatePyObject(), pyrna_prop_dir(), pyrna_prop_str(), pyrna_prop_to_py(), pyrna_py_to_array(), pyrna_py_to_array_index(), pyrna_py_to_prop(), pyrna_py_to_prop_array_index(), pyrna_srna_contains_pointer_prop_srna(), radial_control_get_path(), radial_control_invoke(), RNA_function_call_direct_va(), RNA_path_append(), RNA_path_resolve_full(), RNA_pointer_as_string_keywords_ex(), RNA_property_as_string(), RNA_property_boolean_get(), RNA_property_boolean_get_array(), RNA_property_boolean_get_default(), RNA_property_boolean_get_default_array(), RNA_property_boolean_get_default_index(), RNA_property_boolean_get_index(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_boolean_set_index(), RNA_property_collection_add(), RNA_property_collection_assign_int(), RNA_property_collection_begin(), RNA_property_collection_clear(), RNA_property_collection_length(), RNA_property_collection_lookup_index(), RNA_property_collection_lookup_int(), RNA_property_collection_lookup_string(), RNA_property_collection_move(), RNA_property_collection_raw_array(), RNA_property_collection_remove(), RNA_property_collection_type_get(), RNA_property_copy(), RNA_property_enum_get(), RNA_property_enum_get_default(), RNA_property_enum_py_data_get(), RNA_property_enum_set(), RNA_property_float_get(), RNA_property_float_get_array(), RNA_property_float_get_default(), RNA_property_float_get_default_array(), RNA_property_float_get_default_index(), RNA_property_float_get_index(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_float_set_index(), RNA_property_int_get(), RNA_property_int_get_array(), RNA_property_int_get_default_array(), RNA_property_int_get_index(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_int_set_index(), RNA_property_pointer_add(), RNA_property_pointer_get(), RNA_property_pointer_remove(), RNA_property_pointer_set(), RNA_property_reset(), RNA_property_string_default_length(), RNA_property_string_get(), RNA_property_string_get_alloc(), RNA_property_string_get_default(), RNA_property_string_get_default_alloc(), RNA_property_string_length(), RNA_property_string_set(), rna_raw_access(), rna_search_cb(), search_id_collection(), setting_get_rna_value(), template_keymap_item_properties(), tree_element_to_path(), ui_but_add_search(), ui_but_search_test(), ui_def_but_rna(), ui_get_but_string(), ui_get_but_val(), ui_get_but_vectorf(), ui_is_but_float(), ui_item_array(), ui_item_rna_size(), ui_item_with_label(), ui_popup_menu_create(), ui_set_but_soft_range(), ui_set_but_string(), ui_set_but_val(), ui_set_but_vectorf(), ui_template_id(), ui_tooltip_create(), uiDefAutoButR(), uiDefAutoButsRNA(), uiFileBrowseContextProperty(), uiItemEnumR(), uiItemEnumR_string(), uiItemFullR(), uiItemPointerR(), uiItemsEnumR(), uiItemsFullEnumO(), uiTemplateAnyID(), uiTemplateColorRamp(), uiTemplateCurveMapping(), uiTemplateHistogram(), uiTemplateImage(), uiTemplateList(), uiTemplateMarker(), uiTemplateMovieClip(), uiTemplatePathBuilder(), uiTemplateTrack(), uiTemplateVectorscope(), uiTemplateWaveform(), validate_array(), WM_menu_invoke(), and WM_operator_properties_sanitize().
const char* RNA_property_ui_description (PropertyRNA * prop)
Definition at line 1356 of file rna_access.c.
References rna_ensure_property_description().
Referenced by ui_def_but_rna().
int RNA_property_ui_icon (PropertyRNA * prop)
Definition at line 1361 of file rna_access.c.
References PropertyRNA::icon, and rna_ensure_property().
Referenced by ui_def_but_rna(), and uiItemFullR().
const char* RNA_property_ui_name (PropertyRNA * prop)
Definition at line 1351 of file rna_access.c.
References rna_ensure_property_name().
Referenced by getname_anim_fcurve(), template_keymap_item_properties(), ui_but_menu(), ui_def_but_rna(), uiDefAutoButsRNA(), uiItemFullR(), uiItemMenuEnumR(), and uiItemPointerR().
PropertyUnit RNA_property_unit (PropertyRNA * prop)
Definition at line 783 of file rna_access.c.
References rna_ensure_property(), and RNA_SUBTYPE_UNIT.
void RNA_property_update (struct bContext * C, PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1496 of file rna_access.c.
References CTX_data_main(), CTX_data_scene(), and rna_property_update().
Referenced by act_new_exec(), copy_to_selected_button_exec(), eyedropper_sample(), file_browse_exec(), font_open_exec(), font_unlink_exec(), id_search_call_cb(), id_single_user(), image_new_exec(), image_open_exec(), mathutils_rna_matrix_set(), mathutils_rna_vector_set(), mathutils_rna_vector_set_index(), new_material_exec(), new_node_tree_exec(), new_texture_exec(), new_world_exec(), open_exec(), pyrna_prop_array_ass_subscript(), pyrna_py_to_prop(), pyrna_py_to_prop_array_index(), reset_default_button_exec(), rna_update_cb(), sequencer_change_path_exec(), template_id_cb(), text_new_exec(), text_open_exec(), ui_apply_but_funcs_after(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_handle_list_event(), and ui_layer_but_cb().
void RNA_property_update_cache_add (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1534 of file rna_access.c.
References BLI_addtail(), BLI_genericNodeN(), LinkData::data, PointerRNA::data, ELEM, ListBase::first, PropertyRNA::flag, PointerRNA::id, tRnaUpdateCacheElem::L2Funcs, PropertyRNA::magic, MEM_callocN(), LinkData::next, tRnaUpdateCacheElem::next, NULL, PROP_CONTEXT_UPDATE, tRnaUpdateCacheElem::ptr, rna_ensure_property(), RNA_MAGIC, RNA_pointer_create(), PointerRNA::type, and PropertyRNA::update.
Referenced by animsys_write_rna_setting().
void RNA_property_update_cache_flush (struct Main * bmain, struct Scene * scene)
Definition at line 1579 of file rna_access.c.
References LinkData::data, ListBase::first, tRnaUpdateCacheElem::L2Funcs, LinkData::next, tRnaUpdateCacheElem::next, and tRnaUpdateCacheElem::ptr.
Referenced by BKE_animsys_evaluate_animdata().
void RNA_property_update_cache_free (void)
Definition at line 1596 of file rna_access.c.
References BLI_freelinkN(), BLI_freelistN(), ListBase::first, tRnaUpdateCacheElem::L2Funcs, and tRnaUpdateCacheElem::next.
Referenced by BKE_animsys_evaluate_animdata(), RNA_exit(), and setup_app_data().
int RNA_property_update_check (struct PropertyRNA * prop)
Definition at line 1491 of file rna_access.c.
References PropertyRNA::magic, PropertyRNA::noteflag, RNA_MAGIC, and PropertyRNA::update.
Referenced by animsys_write_rna_setting(), mathutils_rna_matrix_set(), mathutils_rna_vector_set(), mathutils_rna_vector_set_index(), pyrna_prop_array_ass_subscript(), pyrna_py_to_prop(), and pyrna_py_to_prop_array_index().
void RNA_property_update_main (struct Main * bmain, struct Scene * scene, PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1501 of file rna_access.c.
References NULL, and rna_property_update().
Referenced by ANIM_list_elem_update().
int RNA_raw_type_sizeof (RawPropertyType type)
Definition at line 3035 of file rna_access.c.
References PROP_RAW_CHAR, PROP_RAW_DOUBLE, PROP_RAW_FLOAT, PROP_RAW_INT, and PROP_RAW_SHORT.
Referenced by foreach_parse_args(), and rna_raw_access().
void RNA_string_get (PointerRNA * ptr, const char * name, char * value)
Definition at line 4330 of file rna_access.c.
References StructRNA::identifier, RNA_property_string_get(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by actuator_add_exec(), add_named_exec(), armature_bone_primitive_add_exec(), background_image_add_invoke(), blend_save_check(), bookmark_select_exec(), controller_add_exec(), create_orientation_exec(), drop_named_image_invoke(), drop_named_material_invoke(), ED_fileselect_set_params(), ed_marker_rename_exec(), ed_undo_push_exec(), edit_actuator_property_get(), edit_constraint_property_get(), edit_controller_property_get(), edit_modifier_property_get(), edit_object_property_get(), edit_sensor_property_get(), envmap_save_exec(), file_directory_new_exec(), font_open_exec(), game_property_new(), group_create_exec(), image_new_exec(), image_open_exec(), image_replace_exec(), image_unpack_exec(), multires_external_save_exec(), new_node_tree_exec(), node_add_file_exec(), node_composit_buts_renderlayers(), node_group_socket_add_exec(), node_output_file_add_socket_exec(), object_select_same_group_exec(), open_exec(), parent_clear_invoke(), parent_drop_exec(), parent_drop_invoke(), poselib_add_exec(), poselib_rename_exec(), run_pyfile_exec(), save_image_options_from_op(), screen_render_scene_layer_set(), screenshot_exec(), sensor_add_exec(), seq_load_operator_info(), sequencer_add_effect_strip_exec(), sequencer_add_generic_strip_exec(), sequencer_change_path_exec(), sound_mixdown_exec(), sound_unpack_exec(), text_open_exec(), text_save_as_exec(), texture_paint_image_from_view_exec(), wm_call_menu_exec(), wm_link_append_exec(), wm_open_mainfile_exec(), wm_recover_auto_save_exec(), and wm_save_as_mainfile_exec().
char* RNA_string_get_alloc (PointerRNA * ptr, const char * name, char * fixedbuf, int fixedlen)
Definition at line 4343 of file rna_access.c.
References StructRNA::identifier, NULL, RNA_property_string_get_alloc(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by console_history_append_exec(), console_insert_exec(), console_scrollback_append_exec(), file_browse_exec(), find_missing_files_exec(), insert_text_exec(), paste_file_exec(), radial_control_get_path(), seq_load_operator_info(), sequencer_add_image_strip_exec(), sequencer_change_path_exec(), text_insert_exec(), and wm_handler_fileselect_call().
int RNA_string_length (PointerRNA * ptr, const char * name)
Definition at line 4356 of file rna_access.c.
References StructRNA::identifier, RNA_property_string_length(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by console_insert_invoke(), and text_insert_invoke().
void RNA_string_set (PointerRNA * ptr, const char * name, const char * value)
Definition at line 4369 of file rna_access.c.
References StructRNA::identifier, RNA_property_string_set(), RNA_struct_find_property(), and PointerRNA::type.
Referenced by blend_save_check(), clip_filesel(), clip_keymap(), console_insert_invoke(), console_keymap(), ED_keymap_anim(), ED_keymap_paint(), ed_keymap_paint_brush_switch(), ED_keymap_uvedit(), ed_marker_rename_invoke_wrapper(), ED_object_generic_keymap(), edit_actuator_invoke_properties(), edit_constraint_invoke_properties(), edit_controller_invoke_properties(), edit_modifier_invoke_properties(), edit_sensor_invoke_properties(), envmap_save_invoke(), file_browse_invoke(), file_panel_cb(), file_sfile_to_operator(), ghost_event_proc(), graphedit_keymap_keyframes(), id_drop_copy(), image_drop_copy(), image_filesel(), image_keymap(), insert_text_invoke(), keymap_particle(), multires_external_save_invoke(), node_composit_buts_renderlayers(), node_id_path_drop_copy(), node_render_changed_exec(), open_file_drop_copy(), open_invoke(), outliner_parent_clear_copy(), outliner_parent_drop_copy(), parent_drop_invoke(), path_drop_copy(), poselib_add_menu_invoke__replacemenu(), poselib_rename_invoke(), save_image_options_to_op(), screenshot_invoke(), script_keymap(), sequencer_change_path_invoke(), sequencer_drop_copy(), sequencer_generic_invoke_path__internal(), sequencer_keymap(), set_brush_rc_path(), set_brush_rc_props(), text_drop_copy(), text_insert_invoke(), text_keymap(), text_open_invoke(), text_save_as_invoke(), transform_keymap_for_space(), ui_but_menu(), uiItemStringO(), uiLayoutOperatorButs(), unpack_menu(), view3d_id_drop_copy(), view3d_id_path_drop_copy(), view3d_keymap(), view3d_ob_drop_copy(), WM_keymap_add_menu(), wm_link_append_invoke(), wm_open_mainfile_invoke(), wm_recover_auto_save_invoke(), wm_save_as_mainfile_invoke(), wm_save_mainfile_invoke(), and wm_window_keymap().
StructRNA* RNA_struct_base (StructRNA * type)
Definition at line 538 of file rna_access.c.
References StructRNA::base.
Referenced by pyrna_basetype_dir(), and pyrna_srna_PyBase().
void* RNA_struct_blender_type_get (StructRNA * srna)
Definition at line 741 of file rna_access.c.
References StructRNA::blender_type.
void RNA_struct_blender_type_set (StructRNA * srna, void * blender_type)
Definition at line 746 of file rna_access.c.
References StructRNA::blender_type.
Referenced by operator_properties_init(), and RNA_struct_free_extension().
int RNA_struct_contains_property (PointerRNA * ptr, PropertyRNA * prop_test)
Definition at line 630 of file rna_access.c.
References FALSE, RNA_PROP_BEGIN, RNA_PROP_END, RNA_struct_iterator_property(), TRUE, and PointerRNA::type.
Referenced by ui_is_but_rna_valid().
StructRNA* RNA_struct_find (const char * identifier)
Definition at line 494 of file rna_access.c.
References BLENDER_RNA, StructRNA::cont, ListBase::first, StructRNA::identifier, ContainerRNA::next, NULL, and BlenderRNA::structs.
FunctionRNA* RNA_struct_find_function (PointerRNA * ptr, const char * identifier)
Definition at line 663 of file rna_access.c.
References StructRNA::base, BLI_findstring_ptr(), StructRNA::functions, NULL, RNA_function_identifier(), RNA_pointer_create(), RNA_PROP_BEGIN, RNA_PROP_END, RNA_Struct, RNA_struct_find_property(), and PointerRNA::type.
Referenced by pyrna_prop_collection_getattro(), pyrna_struct_getattro(), RNA_function_call_direct_lookup(), RNA_function_call_direct_va_lookup(), and RNA_function_call_lookup().
PropertyRNA* RNA_struct_find_property (PointerRNA * ptr, const char * identifier)
Definition at line 591 of file rna_access.c.
References PointerRNA::data, NULL, RNA_path_resolve(), RNA_property_collection_lookup_string(), RNA_struct_iterator_property(), and PointerRNA::type.
Referenced by actuator_add_exec(), bookmark_delete_exec(), bookmark_select_exec(), border_apply(), BPY_rna_types(), buttons_texture_modifier_foreach(), buttons_texture_users_from_context(), controller_add_exec(), draw_actuator_armature(), draw_sensor_armature(), ED_fileselect_set_params(), ED_object_add_generic_get_opts(), edbm_select_similar_exec(), DocumentExporter::exportCurrentScene(), file_browse_exec(), file_browse_invoke(), file_directory_new_exec(), file_draw_check_exists(), file_operator_to_sfile(), file_sfile_to_operator(), DocumentImporter::finish(), foreach_attr_type(), get_enum_identifier(), BlenderSync::get_session_params(), id_data_find_fcurve(), image_sample_apply(), initSnapping(), initTransform(), initTransInfo(), key_get_curValue_rnaPath(), list_item_row(), node_animation_properties(), node_buts_rgb(), node_buts_value(), node_composit_buts_image(), node_composit_buts_renderlayers(), node_socket_button_output_file(), object_add_generic_invoke_options(), operator_wrapper(), pose_slide_apply_props(), poselib_remove_exec(), pyrna_alloc_types(), pyrna_dir_members_rna(), pyrna_free_types(), pyrna_prop_collection_getattro(), pyrna_prop_collection_setattro(), pyrna_pydict_to_props(), pyrna_rotation_euler_order_get(), pyrna_struct_anim_args_parse(), pyrna_struct_getattro(), pyrna_struct_is_property_hidden(), pyrna_struct_is_property_set(), pyrna_struct_path_from_id(), pyrna_struct_setattro(), pyrna_unregister_class(), RNA_boolean_get(), RNA_boolean_get_array(), RNA_boolean_set(), RNA_boolean_set_array(), RNA_collection_add(), RNA_collection_begin(), RNA_collection_clear(), RNA_collection_length(), RNA_enum_get(), RNA_enum_is_equal(), RNA_enum_set(), RNA_enum_set_identifier(), RNA_float_get(), RNA_float_get_array(), RNA_float_set(), RNA_float_set_array(), RNA_function_as_string_keywords(), rna_idp_path(), RNA_int_get(), RNA_int_get_array(), RNA_int_set(), RNA_int_set_array(), RNA_path_resolve_full(), RNA_pointer_add(), RNA_pointer_as_string_keywords_ex(), RNA_pointer_get(), RNA_pointer_set(), rna_raw_access(), RNA_string_get(), RNA_string_get_alloc(), RNA_string_length(), RNA_string_set(), RNA_struct_find_function(), RNA_struct_property_is_set(), save_envmap(), save_image_doit(), saveTransform(), sensor_add_exec(), seq_load_operator_info(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_change_path_exec(), sequencer_drop_copy(), sequencer_generic_invoke_path__internal(), ui_def_but_rna_propname(), ui_template_id(), uiItemEnumO_ptr(), uiItemEnumO_string(), uiItemEnumO_value(), uiItemEnumR(), uiItemEnumR_string(), uiItemMenuEnumR(), uiItemPointerR(), uiItemR(), uiItemsEnumR(), uiItemsFullEnumO(), uiTemplateAnyID(), uiTemplateColorRamp(), uiTemplateColorWheel(), uiTemplateCurveMapping(), uiTemplateHistogram(), uiTemplateImage(), uiTemplateLayers(), uiTemplateList(), uiTemplateMarker(), uiTemplateMovieClip(), uiTemplatePathBuilder(), uiTemplateTrack(), uiTemplateVectorscope(), uiTemplateWaveform(), uv_map_transform(), WM_gesture_circle_modal(), wm_gesture_end(), WM_gesture_lasso_invoke(), WM_gesture_lines_invoke(), WM_gesture_straightline_invoke(), wm_handler_fileselect_call(), wm_link_append_exec(), WM_operator_filesel_ensure_ext_imtype(), wm_save_as_mainfile_exec(), and wm_save_mainfile_invoke().
const char* RNA_struct_identifier (StructRNA * type)
Definition at line 505 of file rna_access.c.
References StructRNA::identifier.
Referenced by bpy_class_call(), bpy_class_validate(), deferred_register_prop(), mathutils_rna_matrix_set(), mathutils_rna_vector_set(), mathutils_rna_vector_set_index(), py_to_array_index(), PYOP_wrap_macro_define(), pyrna_basetype_dir(), pyrna_enum_to_py(), pyrna_func_call(), pyrna_func_doc_get(), pyrna_func_repr(), pyrna_prop_array_ass_subscript(), pyrna_prop_collection_subscript_str_lib_pair_ptr(), pyrna_prop_collection_type_check(), pyrna_prop_path_from_id(), pyrna_prop_str(), pyrna_prop_to_enum_bitfield(), pyrna_py_to_prop(), pyrna_register_class(), pyrna_srna_ExternalType(), pyrna_srna_Subtype(), pyrna_struct_is_property_hidden(), pyrna_struct_is_property_set(), pyrna_struct_path_from_id(), pyrna_struct_path_resolve(), pyrna_struct_repr(), pyrna_struct_setattro(), pyrna_struct_str(), pyrna_unregister_class(), RNA_function_call_direct_va(), rna_function_parameter_parse(), rna_id_write_error(), ui_but_menu(), ui_intro_button(), ui_template_id(), ui_tooltip_create(), uiItemEnumO_ptr(), uiItemEnumO_string(), uiItemEnumO_value(), uiItemEnumR(), uiItemEnumR_string(), uiItemMenuEnumR(), uiItemPointerR(), uiItemR(), uiItemsEnumR(), uiTemplateAnyID(), uiTemplateColorWheel(), uiTemplateCurveMapping(), uiTemplateImage(), uiTemplateLayers(), uiTemplateList(), uiTemplateMarker(), uiTemplateMovieClip(), uiTemplatePathBuilder(), uiTemplateTrack(), validate_array(), and validate_array_length().
struct IDProperty* RNA_struct_idprops (PointerRNA * ptr, int create) [read]
Definition at line 259 of file rna_access.c.
References StructRNA::idproperties, NULL, and PointerRNA::type.
Referenced by pyrna_struct_ass_subscript(), pyrna_struct_contains(), pyrna_struct_get(), pyrna_struct_items(), pyrna_struct_keys(), pyrna_struct_subscript(), pyrna_struct_values(), rna_idproperty_check(), rna_idproperty_find(), rna_path_from_ID_to_idpgroup(), RNA_path_resolve_full(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_collection_add(), RNA_property_enum_set(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_pointer_add(), RNA_property_pointer_remove(), RNA_property_string_set(), and RNA_struct_idprops_unset().
int RNA_struct_idprops_check (StructRNA * srna)
Definition at line 269 of file rna_access.c.
References StructRNA::idproperties.
Referenced by pyrna_srna_Subtype(), pyrna_struct_contains(), pyrna_struct_get(), pyrna_struct_getattro(), pyrna_struct_items(), pyrna_struct_keys(), pyrna_struct_subscript(), and pyrna_struct_values().
int RNA_struct_idprops_register_check (StructRNA * type)
Definition at line 553 of file rna_access.c.
References StructRNA::flag, and STRUCT_NO_IDPROPERTIES.
Referenced by pyrna_deferred_register_class().
int RNA_struct_idprops_unset (PointerRNA * ptr, const char * identifier)
Definition at line 559 of file rna_access.c.
References IDP_FreeProperty(), IDP_GetPropertyFromGroup(), IDP_RemFromGroup(), MEM_freeN(), and RNA_struct_idprops().
Referenced by ED_operatormacros_clip(), ED_operatormacros_mesh(), view_align_update(), and WM_operator_properties_reset().
void** RNA_struct_instance (PointerRNA * ptr)
Definition at line 719 of file rna_access.c.
References StructRNA::base, StructRNA::instance, NULL, and PointerRNA::type.
Referenced by bpy_class_call(), and pyrna_struct_as_instance().
int RNA_struct_is_a (StructRNA * type, StructRNA * srna)
Definition at line 576 of file rna_access.c.
References StructRNA::base.
Referenced by bpy_class_call(), buttons_context_path_brush(), buttons_context_path_data(), buttons_context_path_material(), buttons_context_path_object(), buttons_context_path_particle(), buttons_context_path_pose_bone(), buttons_context_path_scene(), buttons_context_path_texture(), buttons_context_path_world(), buttons_texture_context_compute(), copy_to_selected_list(), CTX_data_pointer_get_type(), get_pointer_type(), list_item_icon_get(), list_item_row(), pointer_type_from_py(), pyrna_callback_add(), pyrna_callback_remove(), pyrna_prop_collection_type_check(), pyrna_py_to_prop(), rna_function_parameter_parse(), RNA_path_from_ID_to_struct(), set_pointer_type(), template_keymap_item_properties(), template_texture_select(), ui_item_with_label(), uiTemplateColorRamp(), uiTemplateConstraint(), uiTemplateCurveMapping(), uiTemplateHistogram(), uiTemplateModifier(), uiTemplateVectorscope(), uiTemplateWaveform(), and WM_operator_properties_sanitize().
int RNA_struct_is_ID (StructRNA * type)
Definition at line 543 of file rna_access.c.
References StructRNA::flag, and STRUCT_ID.
Referenced by list_item_icon_get(), pyrna_param_to_py(), pyrna_struct_anim_args_parse(), pyrna_struct_repr(), radial_control_get_properties(), RNA_path_from_ID_to_struct(), RNA_pointer_recast(), rna_search_cb(), tree_element_to_path(), tselem_draw_icon(), and uiItemLDrag().
PropertyRNA* RNA_struct_iterator_property (StructRNA * type)
Definition at line 533 of file rna_access.c.
References StructRNA::iteratorproperty.
Referenced by pyrna_dir_members_rna(), RNA_function_as_string_keywords(), RNA_pointer_as_string_keywords(), RNA_struct_contains_property(), RNA_struct_find_property(), and WM_operator_properties_reset().
char* RNA_struct_name_get_alloc (PointerRNA * ptr, char * fixedbuf, int fixedlen, int * r_len)
Definition at line 751 of file rna_access.c.
References PointerRNA::data, NULL, RNA_property_string_get_alloc(), RNA_struct_name_property(), and PointerRNA::type.
Referenced by buttons_context_draw(), list_item_row(), pyrna_dir_members_rna(), pyrna_enum_to_py(), pyrna_prop_collection_find(), pyrna_prop_collection_items(), pyrna_prop_collection_keys(), pyrna_prop_str(), pyrna_struct_str(), rna_search_cb(), tree_element_to_path(), ui_get_but_string(), and uiTemplateList().
PropertyRNA* RNA_struct_name_property (StructRNA * type)
Definition at line 528 of file rna_access.c.
References StructRNA::nameproperty.
Referenced by acf_generic_idblock_nameprop(), acf_generic_idfill_nameprop(), acf_gpl_name_prop(), acf_group_name_prop(), acf_shapekey_nameprop(), getname_anim_fcurve(), and RNA_struct_name_get_alloc().
int RNA_struct_property_is_set (PointerRNA * ptr, const char * identifier)
Definition at line 4469 of file rna_access.c.
References RNA_property_is_set(), and RNA_struct_find_property().
Referenced by add_vertex_invoke(), area_split_invoke(), background_image_add_invoke(), clean_tracks_invoke(), drop_named_image_invoke(), ED_fileselect_set_params(), ED_object_add_generic_get_opts(), edit_actuator_invoke_properties(), edit_constraint_invoke_properties(), edit_controller_invoke_properties(), edit_modifier_invoke_properties(), edit_sensor_invoke_properties(), envmap_save_invoke(), file_browse_exec(), file_browse_invoke(), image_open_invoke(), image_replace_invoke(), image_save_as_invoke(), image_unpack_exec(), image_unpack_invoke(), initSnapping(), initTransInfo(), insert_text_exec(), insert_text_invoke(), linked_limit_default(), move_to_layer_init(), multires_external_save_invoke(), new_node_tree_exec(), node_add_file_exec(), node_add_file_invoke(), node_group_socket_add_exec(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_socket_remove_exec(), object_add_generic_invoke_options(), object_origin_set_exec(), open_invoke(), open_set_load_ui(), open_set_use_scripts(), pack_islands_exec(), paste_file_invoke(), save_image_options_from_op(), save_set_compress(), screen_animation_play_exec(), screen_render_invoke(), screen_render_scene_layer_set(), screenshot_invoke(), sequencer_add_effect_strip_exec(), sequencer_add_effect_strip_invoke(), sequencer_add_image_strip_invoke(), sequencer_add_movie_strip_invoke(), sequencer_add_movieclip_strip_invoke(), sequencer_add_scene_strip_invoke(), sequencer_add_sound_strip_invoke(), sequencer_generic_invoke_xy__internal(), set_scale_invoke(), set_solution_scale_invoke(), sound_mixdown_invoke(), sound_open_invoke(), sound_unpack_exec(), sound_unpack_invoke(), stitch_init(), text_open_invoke(), text_save_as_invoke(), text_scroll_bar_invoke(), text_scroll_invoke(), transform_invoke(), undo_history_exec(), viewdolly_invoke(), viewzoom_exec(), viewzoom_invoke(), wm_link_append_invoke(), WM_operator_filesel(), and wm_save_as_mainfile_exec().
void* RNA_struct_py_type_get (StructRNA * srna)
Definition at line 731 of file rna_access.c.
References StructRNA::py_type.
Referenced by bpy_class_call(), bpy_class_validate(), pyrna_free_types(), pyrna_register_class(), pyrna_srna_Subtype(), and pyrna_subtype_set_rna().
void RNA_struct_py_type_set (StructRNA * srna, void * py_type)
Definition at line 736 of file rna_access.c.
References StructRNA::py_type.
Referenced by pyrna_free_types(), pyrna_register_class(), pyrna_subtype_set_rna(), and RNA_struct_free_extension().
StructRegisterFunc RNA_struct_register (StructRNA * type)
Definition at line 704 of file rna_access.c.
References StructRNA::reg.
Referenced by pyrna_register_class().
PropertyRNA* RNA_struct_type_find_property (StructRNA * srna, const char * identifier)
Definition at line 658 of file rna_access.c.
References BLI_findstring_ptr(), StructRNA::cont, and ContainerRNA::properties.
Referenced by OBJECT_OT_camera_add(), and pyrna_struct_meta_idprop_setattro().
struct ListBase* RNA_struct_type_functions (StructRNA * srna) [read]
Definition at line 699 of file rna_access.c.
References StructRNA::functions.
Referenced by bpy_class_validate().
struct ListBase* RNA_struct_type_properties (StructRNA * srna) [read]
Definition at line 653 of file rna_access.c.
References StructRNA::cont, and ContainerRNA::properties.
Referenced by bpy_class_validate(), node_animation_properties(), and pyrna_srna_contains_pointer_prop_srna().
const char* RNA_struct_ui_description (StructRNA * type)
Definition at line 523 of file rna_access.c.
References StructRNA::description, and TIP_.
Referenced by ui_def_but_operator_ptr(), and uiItemMenuEnumO().
int RNA_struct_ui_icon (StructRNA * type)
Definition at line 515 of file rna_access.c.
References StructRNA::icon.
Referenced by buttons_context_compute(), buttons_context_draw(), buttons_texture_modifier_foreach(), buttons_texture_users_find_nodetree(), buttons_texture_users_from_context(), draw_modifier(), getname_anim_fcurve(), template_ID(), tselem_draw_icon(), uiDefAutoButR(), uiIconFromID(), uiItemPointerR(), and uiTemplateList().
const char* RNA_struct_ui_name (StructRNA * type)
Definition at line 510 of file rna_access.c.
References CTX_IFACE_, StructRNA::name, and StructRNA::translation_context.
Referenced by dropbox_active(), ED_fileselect_set_params(), getname_anim_fcurve(), ui_def_but_operator_ptr(), uiItemFullO_ptr(), uiItemMenuEnumO(), uiLayoutOperatorButs(), undo_history_invoke(), wm_block_create_redo(), wm_enum_search_menu(), and WM_menu_invoke().
int RNA_struct_undo_check (StructRNA * type)
Definition at line 548 of file rna_access.c.
References StructRNA::flag, and STRUCT_UNDO.
Referenced by ui_but_is_rna_undo().
StructUnregisterFunc RNA_struct_unregister (StructRNA * type)
Definition at line 709 of file rna_access.c.
References StructRNA::base, NULL, and StructRNA::unreg.
Referenced by pyrna_unregister_class().
short RNA_type_to_ID_code (StructRNA * type)
Referenced by radial_control_set_tex(), template_id_browse_tip(), and ui_template_id().
Variable Documentation
BlenderRNA BLENDER_RNA
const PointerRNA PointerRNA_NULL
Definition at line 66 of file rna_access.c.
Referenced by CTX_data_pointer_get(), CTX_data_pointer_get_type(), pyrna_prop_collection_ass_subscript_int(), rna_array_lookup_int(), RNA_pointer_get(), rna_pointer_inherit_refine(), RNA_property_pointer_get(), RNA_property_pointer_get_default(), ui_set_but_string(), uiItemFullO(), and uiItemFullO_ptr().
StructRNA RNA_Action
StructRNA RNA_ActionConstraint
StructRNA RNA_ActionFCurves
StructRNA RNA_ActionGroup
Referenced by acf_group_name_prop().
StructRNA RNA_ActionGroups
StructRNA RNA_ActionPoseMarkers
StructRNA RNA_Actuator
Referenced by actuator_add_exec(), edit_actuator_invoke_properties(), edit_actuator_poll(), and logic_buttons_new().
StructRNA RNA_ActuatorSensor
StructRNA RNA_Addon
StructRNA RNA_AdjustmentSequence
StructRNA RNA_AlwaysSensor
StructRNA RNA_AndController
StructRNA RNA_AnimData
Referenced by nla_panel_context().
StructRNA RNA_AnimViz
StructRNA RNA_AnimVizMotionPaths
StructRNA RNA_AnimVizOnionSkinning
StructRNA RNA_AnyType
Referenced by pyrna_py_to_prop().
StructRNA RNA_Area
StructRNA RNA_AreaLamp
StructRNA RNA_Armature
Referenced by buttons_context(), buttons_context_path_data(), and ui_item_array().
StructRNA RNA_ArmatureModifier
StructRNA RNA_ArmatureSensor
StructRNA RNA_ArrayModifier
StructRNA RNA_BackgroundImage
StructRNA RNA_BevelModifier
StructRNA RNA_BezierSplinePoint
Referenced by v3d_editvertex_buts().
StructRNA RNA_BlendData
Referenced by pyrna_prop_collection_subscript_str_lib_pair_ptr(), and RNA_main_pointer_create().
StructRNA RNA_BlenderRNA
Referenced by RNA_blender_rna_pointer_create().
StructRNA RNA_BlendTexture
StructRNA RNA_BoidRule
StructRNA RNA_BoidRuleAverageSpeed
StructRNA RNA_BoidRuleAvoid
StructRNA RNA_BoidRuleAvoidCollision
StructRNA RNA_BoidRuleFight
StructRNA RNA_BoidRuleFollowLeader
StructRNA RNA_BoidRuleGoal
StructRNA RNA_BoidSettings
StructRNA RNA_BoidState
StructRNA RNA_Bone
Referenced by buttons_context(), buttons_context_path_bone(), ed_screen_context(), and pose_bone_layers_exec().
StructRNA RNA_BoneGroup
StructRNA RNA_BooleanModifier
StructRNA RNA_BoolProperty
StructRNA RNA_Brush
Referenced by buttons_context(), and buttons_context_path_brush().
StructRNA RNA_BrushTextureSlot
Referenced by buttons_context(), and buttons_texture_users_from_context().
StructRNA RNA_BuildModifier
StructRNA RNA_Camera
Referenced by blender_camera_from_object(), buttons_context(), and buttons_context_path_data().
StructRNA RNA_CastModifier
StructRNA RNA_ChildOfConstraint
StructRNA RNA_ChildParticle
StructRNA RNA_ClampToConstraint
StructRNA RNA_ClothCollisionSettings
StructRNA RNA_ClothModifier
Referenced by buttons_context().
StructRNA RNA_ClothSettings
StructRNA RNA_CloudsTexture
StructRNA RNA_CollectionProperty
StructRNA RNA_CollisionModifier
Referenced by buttons_context().
StructRNA RNA_CollisionSensor
StructRNA RNA_CollisionSettings
StructRNA RNA_ColorRamp
Referenced by uiTemplateColorRamp().
StructRNA RNA_ColorRampElement
Referenced by colorband_buttons_large(), and colorband_buttons_small().
StructRNA RNA_ColorSequence
StructRNA RNA_CompositorNode
StructRNA RNA_CompositorNodeAlphaOver
StructRNA RNA_CompositorNodeBilateralblur
StructRNA RNA_CompositorNodeBlur
StructRNA RNA_CompositorNodeBrightContrast
StructRNA RNA_CompositorNodeChannelMatte
StructRNA RNA_CompositorNodeChromaMatte
StructRNA RNA_CompositorNodeColorMatte
StructRNA RNA_CompositorNodeColorSpill
StructRNA RNA_CompositorNodeCombHSVA
StructRNA RNA_CompositorNodeCombRGBA
StructRNA RNA_CompositorNodeCombYCCA
StructRNA RNA_CompositorNodeCombYUVA
StructRNA RNA_CompositorNodeComposite
StructRNA RNA_CompositorNodeCrop
StructRNA RNA_CompositorNodeCurveRGB
StructRNA RNA_CompositorNodeCurveVec
StructRNA RNA_CompositorNodeDBlur
StructRNA RNA_CompositorNodeDefocus
StructRNA RNA_CompositorNodeDiffMatte
StructRNA RNA_CompositorNodeDilateErode
StructRNA RNA_CompositorNodeDisplace
StructRNA RNA_CompositorNodeDistanceMatte
StructRNA RNA_CompositorNodeDoubleEdgeMask
StructRNA RNA_CompositorNodeFilter
StructRNA RNA_CompositorNodeFlip
StructRNA RNA_CompositorNodeGamma
StructRNA RNA_CompositorNodeGlare
StructRNA RNA_CompositorNodeHueSat
StructRNA RNA_CompositorNodeIDMask
StructRNA RNA_CompositorNodeImage
StructRNA RNA_CompositorNodeInvert
StructRNA RNA_CompositorNodeLensdist
StructRNA RNA_CompositorNodeLevels
StructRNA RNA_CompositorNodeLumaMatte
StructRNA RNA_CompositorNodeMapUV
StructRNA RNA_CompositorNodeMapValue
StructRNA RNA_CompositorNodeMath
StructRNA RNA_CompositorNodeMixRGB
StructRNA RNA_CompositorNodeNormal
StructRNA RNA_CompositorNodeNormalize
StructRNA RNA_CompositorNodeOutputFile
StructRNA RNA_CompositorNodePremulKey
StructRNA RNA_CompositorNodeRGB
StructRNA RNA_CompositorNodeRGBToBW
StructRNA RNA_CompositorNodeRLayers
StructRNA RNA_CompositorNodeRotate
StructRNA RNA_CompositorNodeScale
StructRNA RNA_CompositorNodeSepHSVA
StructRNA RNA_CompositorNodeSepRGBA
StructRNA RNA_CompositorNodeSepYCCA
StructRNA RNA_CompositorNodeSepYUVA
StructRNA RNA_CompositorNodeSetAlpha
StructRNA RNA_CompositorNodeSplitViewer
StructRNA RNA_CompositorNodeTexture
StructRNA RNA_CompositorNodeTime
StructRNA RNA_CompositorNodeTonemap
StructRNA RNA_CompositorNodeTranslate
StructRNA RNA_CompositorNodeTree
StructRNA RNA_CompositorNodeValToRGB
StructRNA RNA_CompositorNodeValue
StructRNA RNA_CompositorNodeVecBlur
StructRNA RNA_CompositorNodeViewer
StructRNA RNA_CompositorNodeZcombine
StructRNA RNA_ConsoleLine
StructRNA RNA_Constraint
Referenced by constraint_delete_exec(), constraint_poll(), draw_constraint(), edit_constraint_invoke_properties(), edit_constraint_poll(), and uiTemplateConstraint().
StructRNA RNA_ConstraintTarget
StructRNA RNA_Context
Referenced by BPy_init_modules(), pyrna_struct_dir(), pyrna_struct_getattro(), pyrna_struct_setattro(), and radial_control_get_properties().
StructRNA RNA_ControlFluidSettings
StructRNA RNA_Controller
Referenced by controller_add_exec(), edit_controller_invoke_properties(), edit_controller_poll(), and logic_buttons_new().
StructRNA RNA_CopyLocationConstraint
StructRNA RNA_CopyRotationConstraint
StructRNA RNA_CopyScaleConstraint
StructRNA RNA_CopyTransformsConstraint
StructRNA RNA_Curve
Referenced by buttons_context(), and buttons_context_path_data().
StructRNA RNA_CurveMap
StructRNA RNA_CurveMapping
Referenced by uiTemplateCurveMapping().
StructRNA RNA_CurveMapPoint
StructRNA RNA_CurveModifier
StructRNA RNA_CurvePoint
StructRNA RNA_DampedTrackConstraint
StructRNA RNA_DecimateModifier
StructRNA RNA_DelaySensor
StructRNA RNA_DisplaceModifier
StructRNA RNA_DistortedNoiseTexture
StructRNA RNA_DomainFluidSettings
StructRNA RNA_DopeSheet
StructRNA RNA_Driver
Referenced by graph_panel_drivers().
StructRNA RNA_DriverTarget
Referenced by graph_panel_driverVar__locDiff(), graph_panel_driverVar__rotDiff(), graph_panel_driverVar__singleProp(), and graph_panel_driverVar__transChan().
StructRNA RNA_DriverVariable
Referenced by graph_panel_drivers().
StructRNA RNA_DupliObject
StructRNA RNA_DynamicPaintBrushSettings
StructRNA RNA_DynamicPaintCanvasSettings
StructRNA RNA_DynamicPaintModifier
Referenced by buttons_context().
StructRNA RNA_DynamicPaintSurface
Referenced by list_item_icon_get(), and list_item_row().
StructRNA RNA_EdgeSplitModifier
StructRNA RNA_EditBone
Referenced by armature_bone_layers_exec(), buttons_context(), buttons_context_path_bone(), copy_to_selected_list(), ed_screen_context(), and v3d_editarmature_buts().
StructRNA RNA_EffectorWeights
StructRNA RNA_EffectSequence
StructRNA RNA_EnumProperty
StructRNA RNA_EnumPropertyItem
StructRNA RNA_EnvironmentMap
StructRNA RNA_EnvironmentMapTexture
StructRNA RNA_Event
StructRNA RNA_ExplodeModifier
Referenced by explode_poll().
StructRNA RNA_ExpressionController
StructRNA RNA_FCurve
Referenced by graph_panel_properties(), and pyrna_struct_driver_add().
StructRNA RNA_FCurveSample
StructRNA RNA_FFmpegSettings
StructRNA RNA_FieldSettings
Referenced by buttons_texture_users_from_context().
StructRNA RNA_FileSelectParams
StructRNA RNA_FloatProperty
StructRNA RNA_FloorConstraint
StructRNA RNA_FluidFluidSettings
StructRNA RNA_FluidSettings
StructRNA RNA_FluidSimulationModifier
Referenced by buttons_context().
StructRNA RNA_FModifier
Referenced by ANIM_uiTemplate_fmodifier_draw().
StructRNA RNA_FModifierCycles
Referenced by draw_modifier__cycles().
StructRNA RNA_FModifierEnvelope
Referenced by draw_modifier__envelope().
StructRNA RNA_FModifierEnvelopeControlPoint
StructRNA RNA_FModifierFunctionGenerator
Referenced by draw_modifier__fn_generator(), and draw_modifier__generator().
StructRNA RNA_FModifierGenerator
StructRNA RNA_FModifierLimits
Referenced by draw_modifier__limits().
StructRNA RNA_FModifierNoise
Referenced by draw_modifier__noise().
StructRNA RNA_FModifierPython
StructRNA RNA_FModifierStepped
Referenced by draw_modifier__stepped().
StructRNA RNA_FollowPathConstraint
StructRNA RNA_Function
Referenced by bpy_class_call(), pyrna_func_call(), RNA_function_as_string_keywords(), and RNA_function_call_direct_va().
StructRNA RNA_GameBooleanProperty
StructRNA RNA_GameFloatProperty
StructRNA RNA_GameIntProperty
StructRNA RNA_GameObjectSettings
Referenced by BL_ConvertActuators(), draw_actuator_action(), draw_actuator_message(), draw_actuator_motion(), draw_actuator_property(), draw_actuator_random(), draw_actuator_shape_action(), draw_actuator_state(), draw_sensor_actuator(), draw_sensor_keyboard(), draw_sensor_property(), and logic_buttons_new().
StructRNA RNA_GameProperty
StructRNA RNA_GameSoftBodySettings
StructRNA RNA_GameStringProperty
StructRNA RNA_GameTimerProperty
StructRNA RNA_GlowSequence
StructRNA RNA_GPencilFrame
StructRNA RNA_GPencilLayer
Referenced by acf_gpl_name_prop(), and gp_drawui_layer().
StructRNA RNA_GPencilStroke
StructRNA RNA_GPencilStrokePoint
StructRNA RNA_GreasePencil
StructRNA RNA_Group
Referenced by group_remove_exec().
StructRNA RNA_Header
StructRNA RNA_HemiLamp
StructRNA RNA_Histogram
Referenced by uiTemplateHistogram().
StructRNA RNA_HookModifier
Referenced by object_hook_assign_exec(), object_hook_recenter_exec(), object_hook_reset_exec(), and object_hook_select_exec().
StructRNA RNA_ID
StructRNA RNA_IKParam
StructRNA RNA_Image
StructRNA RNA_ImageFormatSettings
Referenced by image_save_as_draw(), and screenshot_draw().
StructRNA RNA_ImagePaint
StructRNA RNA_ImageSequence
StructRNA RNA_ImageTexture
StructRNA RNA_ImageUser
StructRNA RNA_InflowFluidSettings
StructRNA RNA_IntProperty
StructRNA RNA_Itasc
StructRNA RNA_JoystickSensor
StructRNA RNA_Key
StructRNA RNA_KeyboardSensor
StructRNA RNA_KeyConfig
StructRNA RNA_Keyframe
Referenced by graph_panel_key_properties().
StructRNA RNA_KeyingSet
StructRNA RNA_KeyingSetInfo
StructRNA RNA_KeyingSetPath
Referenced by list_item_row().
StructRNA RNA_KeyingSetsAll
StructRNA RNA_KeyMap
StructRNA RNA_KeyMapItem
Referenced by menu_add_shortcut(), menu_change_shortcut(), and ui_item_with_label().
StructRNA RNA_KeyMapItems
StructRNA RNA_KinematicConstraint
StructRNA RNA_Lamp
Referenced by buttons_context(), buttons_context_path_data(), and paste_mtex_exec().
StructRNA RNA_LampSkySettings
StructRNA RNA_LampTextureSlot
Referenced by buttons_context().
StructRNA RNA_Lattice
Referenced by buttons_context(), and buttons_context_path_data().
StructRNA RNA_LatticeModifier
StructRNA RNA_LatticePoint
StructRNA RNA_Library
StructRNA RNA_LimitDistanceConstraint
StructRNA RNA_LimitLocationConstraint
StructRNA RNA_LimitRotationConstraint
StructRNA RNA_LimitScaleConstraint
StructRNA RNA_LockedTrackConstraint
StructRNA RNA_Macro
StructRNA RNA_MagicTexture
StructRNA RNA_MarbleTexture
StructRNA RNA_MaskModifier
StructRNA RNA_Material
Referenced by buttons_context(), buttons_context_path_material(), copy_material_exec(), new_material_exec(), paste_material_exec(), paste_mtex_exec(), and uiTemplatePreview().
StructRNA RNA_MaterialHalo
StructRNA RNA_MaterialPhysics
StructRNA RNA_MaterialRaytraceMirror
StructRNA RNA_MaterialRaytraceTransparency
StructRNA RNA_MaterialSlot
Referenced by buttons_context(), list_item_icon_get(), and list_item_row().
StructRNA RNA_MaterialStrand
StructRNA RNA_MaterialSubsurfaceScattering
StructRNA RNA_MaterialTextureSlot
Referenced by buttons_context(), and list_item_row().
StructRNA RNA_MaterialVolume
StructRNA RNA_Menu
StructRNA RNA_Mesh
Referenced by buttons_context(), buttons_context_path_data(), and uiTemplateHeader3D().
StructRNA RNA_MeshColor
StructRNA RNA_MeshColorLayer
StructRNA RNA_MeshDeformModifier
Referenced by meshdeform_poll().
StructRNA RNA_MeshEdge
StructRNA RNA_MeshFloatProperty
StructRNA RNA_MeshFloatPropertyLayer
StructRNA RNA_MeshIntProperty
StructRNA RNA_MeshIntPropertyLayer
StructRNA RNA_MeshLoop
StructRNA RNA_MeshLoopColorLayer
Referenced by list_item_row().
StructRNA RNA_MeshPolygon
StructRNA RNA_MeshSticky
StructRNA RNA_MeshStringProperty
StructRNA RNA_MeshStringPropertyLayer
StructRNA RNA_MeshTessFace
StructRNA RNA_MeshTextureFace
StructRNA RNA_MeshTextureFaceLayer
StructRNA RNA_MeshTexturePoly
StructRNA RNA_MeshTexturePolyLayer
Referenced by list_item_row().
StructRNA RNA_MeshVertex
StructRNA RNA_MessageSensor
StructRNA RNA_MetaBall
Referenced by buttons_context(), buttons_context_path_data(), and v3d_editmetaball_buts().
StructRNA RNA_MetaElement
Referenced by v3d_editmetaball_buts().
StructRNA RNA_MetaSequence
StructRNA RNA_MirrorModifier
StructRNA RNA_Modifier
Referenced by buttons_texture_modifier_foreach(), draw_modifier(), edit_modifier_invoke_properties(), edit_modifier_poll(), and uiTemplateModifier().
StructRNA RNA_MotionPath
StructRNA RNA_MotionPathVert
StructRNA RNA_MouseSensor
StructRNA RNA_MovieClipSequence
StructRNA RNA_MovieSequence
StructRNA RNA_MovieTrackingObject
Referenced by list_item_row().
StructRNA RNA_MulticamSequence
StructRNA RNA_MultiresModifier
Referenced by multires_poll().
StructRNA RNA_MusgraveTexture
StructRNA RNA_NandController
StructRNA RNA_NearSensor
StructRNA RNA_NlaStrip
Referenced by BKE_nlameta_flush_transforms(), insert_key_button_exec(), nla_panel_context(), nlaedit_clear_scale_exec(), nlastrip_evaluate_controls(), and recalcData_nla().
StructRNA RNA_NlaTrack
Referenced by nla_panel_context().
StructRNA RNA_Node
Referenced by active_node_panel(), buttons_context(), buttons_texture_users_find_nodetree(), node_animation_properties(), node_context(), node_draw_group(), node_group_make_from_selected(), node_group_ungroup(), node_socket_button_output_file(), node_update_basis(), and ui_node_draw_node().
StructRNA RNA_NodeForLoop
StructRNA RNA_NodeGroup
Referenced by add_nodes().
StructRNA RNA_NodeImageFileSocket
StructRNA RNA_NodeLink
StructRNA RNA_NodeSocket
Referenced by node_animation_properties(), node_draw_basis(), node_socket_button_color(), node_socket_button_components(), node_socket_button_default(), node_socket_button_output_file(), and ui_node_draw_input().
StructRNA RNA_NodeSocketPanel
StructRNA RNA_NodeTree
StructRNA RNA_NodeWhileLoop
StructRNA RNA_NoiseTexture
StructRNA RNA_NorController
StructRNA RNA_Object
Referenced by buttons_context(), buttons_context_path_object(), ED_object_context(), gp_get_3d_reference(), outliner_draw_restrictbuts(), v3d_transform_butsR(), visualkey_can_use(), and visualkey_get_value().
StructRNA RNA_ObjectBase
Referenced by ed_screen_context(), and view3d_context().
StructRNA RNA_ObstacleFluidSettings
StructRNA RNA_OceanModifier
Referenced by ocean_bake_poll().
StructRNA RNA_OceanTexData
StructRNA RNA_OceanTexture
StructRNA RNA_Operator
Referenced by bpy_class_call(), ed_screen_context(), pyop_getinstance(), pyrna_basetype_dir(), and pyrna_py_to_prop().
StructRNA RNA_OperatorFileListElement
Referenced by WM_operator_properties_filesel().
StructRNA RNA_OperatorMacro
Referenced by PYOP_wrap_macro_define().
StructRNA RNA_OperatorMousePath
Referenced by LOGIC_OT_links_cut(), MESH_OT_knife_cut(), NODE_OT_links_cut(), and VIEW3D_OT_select_lasso().
StructRNA RNA_OperatorProperties
Referenced by pyrna_py_to_prop(), template_keymap_item_properties(), WM_operator_properties_create(), and WM_operator_properties_sanitize().
StructRNA RNA_OperatorStrokeElement
Referenced by GPENCIL_OT_draw(), PAINT_OT_image_paint(), PAINT_OT_vertex_paint(), PAINT_OT_weight_paint(), PARTICLE_OT_brush_edit(), and SCULPT_OT_brush_stroke().
StructRNA RNA_OrController
StructRNA RNA_OutflowFluidSettings
StructRNA RNA_PackedFile
StructRNA RNA_Paint
StructRNA RNA_Panel
StructRNA RNA_Particle
StructRNA RNA_ParticleBrush
StructRNA RNA_ParticleDupliWeight
StructRNA RNA_ParticleEdit
StructRNA RNA_ParticleFluidSettings
StructRNA RNA_ParticleHairKey
StructRNA RNA_ParticleInstanceModifier
StructRNA RNA_ParticleKey
StructRNA RNA_ParticleSettings
Referenced by buttons_context_path_particle(), buttons_context_path_texture(), and buttons_texture_users_from_context().
StructRNA RNA_ParticleSettingsTextureSlot
Referenced by buttons_context(), and buttons_texture_users_from_context().
StructRNA RNA_ParticleSystem
Referenced by buttons_context(), buttons_context_id_path(), buttons_context_path_particle(), connect_hair_exec(), copy_particle_dupliob_exec(), disconnect_hair_exec(), dupliob_move_down_exec(), dupliob_move_up_exec(), new_particle_settings_exec(), new_particle_target_exec(), paste_mtex_exec(), psys_poll(), remove_particle_dupliob_exec(), remove_particle_target_exec(), rule_add_exec(), rule_del_exec(), rule_move_down_exec(), rule_move_up_exec(), state_add_exec(), state_del_exec(), state_move_down_exec(), state_move_up_exec(), target_move_down_exec(), and target_move_up_exec().
StructRNA RNA_ParticleSystemModifier
StructRNA RNA_ParticleTarget
StructRNA RNA_PivotConstraint
StructRNA RNA_PluginSequence
StructRNA RNA_PluginTexture
StructRNA RNA_PointCache
Referenced by ptcache_add_new_exec(), ptcache_bake_exec(), ptcache_bake_from_cache_exec(), ptcache_free_bake_exec(), ptcache_poll(), and ptcache_remove_exec().
StructRNA RNA_PointDensity
StructRNA RNA_PointDensityTexture
StructRNA RNA_PointerProperty
StructRNA RNA_PointLamp
StructRNA RNA_Pose
Referenced by draw_actuator_armature(), draw_sensor_armature(), graph_panel_driverVar__locDiff(), graph_panel_driverVar__rotDiff(), and graph_panel_driverVar__transChan().
StructRNA RNA_PoseBone
Referenced by action_get_item_transforms(), animsys_write_rna_setting(), autokeyframe_pose_cb_func(), buttons_context(), buttons_context_path_pose_bone(), copy_to_selected_list(), ED_autokeyframe_pchan(), ed_screen_context(), fcurves_to_pchan_links_get(), pose_slide_apply_props(), poseAnim_mapping_autoKeyframe(), poselib_keytag_pose(), v3d_posearmature_buts(), v3d_transform_butsR(), visualkey_can_use(), and visualkey_get_value().
StructRNA RNA_Property
Referenced by pyrna_struct_get_rna_type(), and RNA_def_struct().
StructRNA RNA_PropertyGroup
StructRNA RNA_PropertyGroupItem
StructRNA RNA_PropertySensor
StructRNA RNA_PythonConstraint
StructRNA RNA_PythonController
StructRNA RNA_QuickTimeSettings
StructRNA RNA_RadarSensor
StructRNA RNA_RandomSensor
StructRNA RNA_RaySensor
StructRNA RNA_Region
Referenced by pyrna_callback_add(), and pyrna_callback_remove().
StructRNA RNA_RenderEngine
Referenced by create_func().
StructRNA RNA_RenderLayer
StructRNA RNA_RenderPass
StructRNA RNA_RenderResult
Referenced by BlenderSession::render().
StructRNA RNA_RenderSettings
StructRNA RNA_RigidBodyJointConstraint
StructRNA RNA_Scene
Referenced by buttons_context_draw(), buttons_context_path_scene(), sound_update_animation_flags_exec(), and uiTemplateHeader3D().
StructRNA RNA_SceneGameData
StructRNA RNA_SceneObjects
Referenced by template_id_cb().
StructRNA RNA_SceneRenderLayer
Referenced by list_item_row().
StructRNA RNA_SceneSequence
StructRNA RNA_Scopes
Referenced by uiTemplateVectorscope(), and uiTemplateWaveform().
StructRNA RNA_Screen
StructRNA RNA_ScrewModifier
StructRNA RNA_Sculpt
StructRNA RNA_SelectedUvElement
Referenced by UV_OT_stitch().
StructRNA RNA_Sensor
Referenced by edit_sensor_invoke_properties(), edit_sensor_poll(), logic_buttons_new(), and sensor_add_exec().
StructRNA RNA_Sequence
Referenced by copy_to_selected_list(), ed_screen_context(), seq_render_effect_strip_impl(), sequence_effect_speed_rebuild_map(), sequencer_change_path_exec(), and sound_update_animation_flags_exec().
StructRNA RNA_SequenceColorBalance
StructRNA RNA_SequenceCrop
StructRNA RNA_SequenceEditor
StructRNA RNA_SequenceElement
StructRNA RNA_SequenceProxy
StructRNA RNA_SequenceTransform
StructRNA RNA_ShaderNode
StructRNA RNA_ShaderNodeCameraData
StructRNA RNA_ShaderNodeCombineRGB
StructRNA RNA_ShaderNodeExtendedMaterial
StructRNA RNA_ShaderNodeGeometry
StructRNA RNA_ShaderNodeHueSaturation
StructRNA RNA_ShaderNodeInvert
StructRNA RNA_ShaderNodeMapping
StructRNA RNA_ShaderNodeMaterial
StructRNA RNA_ShaderNodeMath
StructRNA RNA_ShaderNodeMixRGB
StructRNA RNA_ShaderNodeNormal
StructRNA RNA_ShaderNodeOutput
StructRNA RNA_ShaderNodeRGB
StructRNA RNA_ShaderNodeRGBCurve
StructRNA RNA_ShaderNodeRGBToBW
StructRNA RNA_ShaderNodeSeparateRGB
StructRNA RNA_ShaderNodeSqueeze
StructRNA RNA_ShaderNodeTexture
StructRNA RNA_ShaderNodeTree
StructRNA RNA_ShaderNodeValToRGB
StructRNA RNA_ShaderNodeValue
StructRNA RNA_ShaderNodeVectorCurve
StructRNA RNA_ShaderNodeVectorMath
StructRNA RNA_ShapeKey
Referenced by acf_shapekey_nameprop(), key_get_curValue_rnaPath(), and list_item_row().
StructRNA RNA_ShapeKeyBezierPoint
StructRNA RNA_ShapeKeyCurvePoint
StructRNA RNA_ShapeKeyPoint
StructRNA RNA_ShrinkwrapConstraint
StructRNA RNA_ShrinkwrapModifier
StructRNA RNA_SimpleDeformModifier
StructRNA RNA_SmokeCollSettings
StructRNA RNA_SmokeDomainSettings
StructRNA RNA_SmokeFlowSettings
StructRNA RNA_SmokeModifier
Referenced by buttons_context().
StructRNA RNA_SmoothModifier
StructRNA RNA_SoftBodyModifier
Referenced by buttons_context().
StructRNA RNA_SoftBodySettings
StructRNA RNA_SolidifyModifier
StructRNA RNA_Sound
StructRNA RNA_SoundSequence
StructRNA RNA_Space
StructRNA RNA_SpaceClipEditor
StructRNA RNA_SpaceConsole
StructRNA RNA_SpaceDopeSheetEditor
StructRNA RNA_SpaceFileBrowser
StructRNA RNA_SpaceGraphEditor
Referenced by graph_panel_view().
StructRNA RNA_SpaceImageEditor
Referenced by gpencil_data_get_pointers(), and image_panel_curves().
StructRNA RNA_SpaceInfo
StructRNA RNA_SpaceLogicEditor
Referenced by logic_buttons(), and logic_buttons_new().
StructRNA RNA_SpaceNLA
StructRNA RNA_SpaceNodeEditor
StructRNA RNA_SpaceOutliner
StructRNA RNA_SpaceProperties
Referenced by toolbox_invoke().
StructRNA RNA_SpaceSequenceEditor
StructRNA RNA_SpaceTextEditor
StructRNA RNA_SpaceTimeline
StructRNA RNA_SpaceUserPreferences
StructRNA RNA_SpaceUVEditor
StructRNA RNA_SpaceView3D
Referenced by uiTemplateHeader3D().
StructRNA RNA_Speaker
Referenced by buttons_context(), and buttons_context_path_data().
StructRNA RNA_SpeedControlSequence
StructRNA RNA_SPHFluidSettings
StructRNA RNA_Spline
StructRNA RNA_SplineIKConstraint
StructRNA RNA_SplinePoint
Referenced by v3d_editvertex_buts().
StructRNA RNA_SpotLamp
StructRNA RNA_StretchToConstraint
StructRNA RNA_StringProperty
StructRNA RNA_Struct
Referenced by pyrna_dir_members_rna(), pyrna_srna_contains_pointer_prop_srna(), pyrna_struct_as_srna(), pyrna_subtype_set_rna(), RNA_def_struct(), RNA_struct_find_function(), and srna_from_ptr().
StructRNA RNA_StucciTexture
StructRNA RNA_SubsurfModifier
StructRNA RNA_SunLamp
StructRNA RNA_SurfaceCurve
StructRNA RNA_SurfaceModifier
StructRNA RNA_TexMapping
StructRNA RNA_Text
StructRNA RNA_TextBox
StructRNA RNA_TextCharacterFormat
StructRNA RNA_TextCurve
StructRNA RNA_TextLine
StructRNA RNA_TextMarker
StructRNA RNA_Texture
Referenced by buttons_context(), buttons_context_path_texture(), buttons_texture_context_compute(), envmap_clear_exec(), envmap_clear_poll(), envmap_save_exec(), envmap_save_poll(), image_open_exec(), image_open_invoke(), new_texture_exec(), node_texture_buts_proc(), template_texture_select(), and uiTemplatePreview().
StructRNA RNA_TextureNode
StructRNA RNA_TextureNodeBricks
StructRNA RNA_TextureNodeChecker
StructRNA RNA_TextureNodeCompose
StructRNA RNA_TextureNodeCoordinates
StructRNA RNA_TextureNodeCurveRGB
StructRNA RNA_TextureNodeCurveTime
StructRNA RNA_TextureNodeDecompose
StructRNA RNA_TextureNodeDistance
StructRNA RNA_TextureNodeHueSaturation
StructRNA RNA_TextureNodeImage
StructRNA RNA_TextureNodeInvert
StructRNA RNA_TextureNodeMath
StructRNA RNA_TextureNodeMixRGB
StructRNA RNA_TextureNodeOutput
StructRNA RNA_TextureNodeRGBToBW
StructRNA RNA_TextureNodeRotate
StructRNA RNA_TextureNodeScale
StructRNA RNA_TextureNodeTexture
StructRNA RNA_TextureNodeTranslate
StructRNA RNA_TextureNodeTree
StructRNA RNA_TextureNodeValToNor
StructRNA RNA_TextureNodeValToRGB
StructRNA RNA_TextureNodeViewer
StructRNA RNA_TextureSlot
Referenced by copy_mtex_exec(), copy_mtex_poll(), list_item_icon_get(), paste_mtex_exec(), and texture_slot_move().
StructRNA RNA_Theme
StructRNA RNA_ThemeAudioWindow
StructRNA RNA_ThemeBoneColorSet
StructRNA RNA_ThemeConsole
StructRNA RNA_ThemeDopeSheet
StructRNA RNA_ThemeFileBrowser
StructRNA RNA_ThemeFontStyle
StructRNA RNA_ThemeGraphEditor
StructRNA RNA_ThemeImageEditor
StructRNA RNA_ThemeInfo
StructRNA RNA_ThemeLogicEditor
StructRNA RNA_ThemeNLAEditor
StructRNA RNA_ThemeNodeEditor
StructRNA RNA_ThemeOutliner
StructRNA RNA_ThemeProperties
StructRNA RNA_ThemeSequenceEditor
StructRNA RNA_ThemeSpaceGeneric
StructRNA RNA_ThemeSpaceListGeneric
StructRNA RNA_ThemeStyle
StructRNA RNA_ThemeTextEditor
StructRNA RNA_ThemeTimeline
StructRNA RNA_ThemeUserInterface
StructRNA RNA_ThemeUserPreferences
StructRNA RNA_ThemeView3D
StructRNA RNA_ThemeWidgetColors
StructRNA RNA_ThemeWidgetStateColors
StructRNA RNA_TimelineMarker
StructRNA RNA_Timer
StructRNA RNA_ToolSettings
Referenced by uiTemplateHeader3D().
StructRNA RNA_TouchSensor
StructRNA RNA_TrackToConstraint
StructRNA RNA_TransformConstraint
StructRNA RNA_TransformSequence
StructRNA RNA_UILayout
StructRNA RNA_UIListItem
StructRNA RNA_UnitSettings
StructRNA RNA_UnknownType
Referenced by RNA_property_pointer_type().
StructRNA RNA_UserPreferences
Referenced by outliner_build_tree().
StructRNA RNA_UserPreferencesEdit
StructRNA RNA_UserPreferencesFilePaths
StructRNA RNA_UserPreferencesInput
StructRNA RNA_UserPreferencesSystem
StructRNA RNA_UserPreferencesView
StructRNA RNA_UserSolidLight
StructRNA RNA_UVProjectModifier
StructRNA RNA_UVProjector
StructRNA RNA_VectorFont
StructRNA RNA_VertexGroup
Referenced by list_item_row().
StructRNA RNA_VertexGroupElement
StructRNA RNA_VertexPaint
StructRNA RNA_VertexWeightEditModifier
StructRNA RNA_VertexWeightMixModifier
StructRNA RNA_VertexWeightProximityModifier
StructRNA RNA_VoronoiTexture
StructRNA RNA_VoxelData
StructRNA RNA_VoxelDataTexture
StructRNA RNA_WarpModifier
StructRNA RNA_WaveModifier
StructRNA RNA_Window
StructRNA RNA_WindowManager
StructRNA RNA_WipeSequence
StructRNA RNA_WoodTexture
StructRNA RNA_World
Referenced by buttons_context(), buttons_context_path_world(), new_world_exec(), and paste_mtex_exec().
StructRNA RNA_WorldAmbientOcclusion
StructRNA RNA_WorldLighting
StructRNA RNA_WorldMistSettings
StructRNA RNA_WorldStarsSettings
StructRNA RNA_WorldTextureSlot
Referenced by buttons_context().
StructRNA RNA_XnorController
StructRNA RNA_XorController