Blender: svm_hsv.h File Reference
svm_hsv.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device float3 rgb_to_hsv (float3 rgb)
__device float3 hsv_to_rgb (float3 hsv)
__device void svm_node_hsv (KernelGlobals *kg, ShaderData *sd, float *stack, uint in_color_offset, uint fac_offset, uint out_color_offset, int *offset)
Function Documentation
__device float3 hsv_to_rgb (float3 hsv)
Definition at line 63 of file svm_hsv.h.
References i, make_float3(), p, float3::x, float3::y, and float3::z.
CCL_NAMESPACE_BEGIN __device float3 rgb_to_hsv (float3 rgb)
Definition at line 24 of file svm_hsv.h.
References fmaxf, make_float3(), min, float3::x, float3::y, and float3::z.
__device void svm_node_hsv (KernelGlobals * kg, ShaderData * sd, float * stack, uint in_color_offset, uint fac_offset, uint out_color_offset, int * offset)
Definition at line 98 of file svm_hsv.h.
References hsv_to_rgb(), if(), read_node(), rgb_to_hsv(), stack_load_float(), stack_load_float3(), stack_store_float3(), stack_valid(), uint4::w, float3::x, float3::y, uint4::y, float3::z, and uint4::z.
Referenced by svm_eval_nodes().