Blender: kernel_passes.h File Reference
kernel_passes.h File Reference
Functions
CCL_NAMESPACE_BEGIN
__device_inline void kernel_write_pass_float (__global float *buffer, int sample, float value)
__device_inline void kernel_write_pass_float3 (__global float *buffer, int sample, float3 value)
__device_inline void kernel_write_pass_float4 (__global float *buffer, int sample, float4 value)
__device_inline void kernel_write_data_passes (KernelGlobals *kg, __global float *buffer, PathRadiance *L, ShaderData *sd, int sample, int path_flag, float3 throughput)
__device_inline void kernel_write_light_passes (KernelGlobals *kg, __global float *buffer, PathRadiance *L, int sample)
Function Documentation
__device_inline void kernel_write_data_passes (KernelGlobals * kg, __global float * buffer, PathRadiance * L, ShaderData * sd, int sample, int path_flag, float3 throughput)
Definition at line 39 of file kernel_passes.h.
References PathRadiance::color_diffuse, PathRadiance::color_glossy, PathRadiance::color_transmission, kernel_data, kernel_write_pass_float(), kernel_write_pass_float3(), len(), make_float3(), ShaderData::N, ShaderData::object, object_pass_id(), ShaderData::P, PASS_ALL, PASS_DEPTH, PASS_DIFFUSE_COLOR, PASS_DIFFUSE_DIRECT, PASS_DIFFUSE_INDIRECT, PASS_GLOSSY_COLOR, PASS_GLOSSY_DIRECT, PASS_GLOSSY_INDIRECT, PASS_MATERIAL_ID, PASS_NORMAL, PASS_OBJECT_ID, PASS_TRANSMISSION_COLOR, PASS_TRANSMISSION_DIRECT, PASS_TRANSMISSION_INDIRECT, PASS_UV, PATH_RAY_CAMERA, PATH_RAY_TRANSPARENT, shader_bsdf_diffuse(), shader_bsdf_glossy(), shader_bsdf_transmission(), shader_pass_id(), and transform_point().
Referenced by kernel_path_integrate().
__device_inline void kernel_write_light_passes (KernelGlobals * kg, __global float * buffer, PathRadiance * L, int sample)
Definition at line 89 of file kernel_passes.h.
References PathRadiance::ao, PathRadiance::background, PathRadiance::color_diffuse, PathRadiance::color_glossy, PathRadiance::color_transmission, PathRadiance::direct_diffuse, PathRadiance::direct_glossy, PathRadiance::direct_transmission, PathRadiance::emission, PathRadiance::indirect_diffuse, PathRadiance::indirect_glossy, PathRadiance::indirect_transmission, kernel_data, kernel_write_pass_float3(), kernel_write_pass_float4(), PASS_AO, PASS_BACKGROUND, PASS_DIFFUSE_COLOR, PASS_DIFFUSE_DIRECT, PASS_DIFFUSE_INDIRECT, PASS_EMISSION, PASS_GLOSSY_COLOR, PASS_GLOSSY_DIRECT, PASS_GLOSSY_INDIRECT, PASS_SHADOW, PASS_TRANSMISSION_COLOR, PASS_TRANSMISSION_DIRECT, PASS_TRANSMISSION_INDIRECT, and PathRadiance::shadow.
Referenced by kernel_path_integrate().
CCL_NAMESPACE_BEGIN __device_inline void kernel_write_pass_float (__global float * buffer, int sample, float value)
Definition at line 21 of file kernel_passes.h.
References __global.
Referenced by kernel_write_data_passes().
__device_inline void kernel_write_pass_float3 (__global float * buffer, int sample, float3 value)
Definition at line 27 of file kernel_passes.h.
References __global.
Referenced by kernel_write_data_passes(), and kernel_write_light_passes().
__device_inline void kernel_write_pass_float4 (__global float * buffer, int sample, float4 value)
Definition at line 33 of file kernel_passes.h.
References __global.
Referenced by kernel_path_trace(), and kernel_write_light_passes().