Blender: btSoftBody::LJoint Struct Reference
btSoftBody::LJoint Struct Reference
#include <btSoftBody.h>
Classes
struct Specs
Public Member Functions
void Prepare (btScalar dt, int iterations)
void Solve (btScalar dt, btScalar sor)
void Terminate (btScalar dt)
eType::_ Type () const
Public Attributes
btVector3 m_rpos [2]
Detailed Description
Definition at line 508 of file btSoftBody.h.
Member Function Documentation
void btSoftBody::LJoint::Prepare (btScalar dt, int iterations) [virtual]
Reimplemented from btSoftBody::Joint.
Definition at line 2459 of file btSoftBody.cpp.
References Clamp(), ImpulseMatrix(), and btSoftBody::Joint::Prepare().
void btSoftBody::LJoint::Solve (btScalar dt, btScalar sor) [virtual]
Implements btSoftBody::Joint.
Definition at line 2479 of file btSoftBody.cpp.
References btSoftBody::Impulse::m_asVelocity, and btSoftBody::Impulse::m_velocity.
void btSoftBody::LJoint::Terminate (btScalar dt) [virtual]
Implements btSoftBody::Joint.
Definition at line 2492 of file btSoftBody.cpp.
eType::_ btSoftBody::LJoint::Type () const [inline, virtual]
Implements btSoftBody::Joint.
Definition at line 518 of file btSoftBody.h.
References btSoftBody::Joint::eType::Linear.
Member Data Documentation
btVector3 btSoftBody::LJoint::m_rpos[2]
Definition at line 514 of file btSoftBody.h.
The documentation for this struct was generated from the following files:
btSoftBody.h
btSoftBody.cpp