Blender: spacetypes.c File Reference
spacetypes.c File Reference
space API
#include <stdlib.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "DNA_object_types.h"
#include "DNA_windowmanager_types.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "UI_interface.h"
#include "UI_view2d.h"
#include "ED_anim_api.h"
#include "ED_armature.h"
#include "ED_curve.h"
#include "ED_fileselect.h"
#include "ED_gpencil.h"
#include "ED_markers.h"
#include "ED_mesh.h"
#include "ED_node.h"
#include "ED_object.h"
#include "ED_physics.h"
#include "ED_render.h"
#include "ED_screen.h"
#include "ED_sculpt.h"
#include "ED_space_api.h"
#include "ED_sound.h"
#include "ED_uvedit.h"
#include "ED_mball.h"
#include "ED_logic.h"
#include "ED_clip.h"
Classes
struct RegionDrawCB
Typedefs
typedef struct RegionDrawCB RegionDrawCB
Functions
void ED_spacetypes_init (void)
void ED_spacetypes_keymap (wmKeyConfig *keyconf)
void * ED_region_draw_cb_activate (ARegionType *art, void(*draw)(const struct bContext *, struct ARegion *, void *), void *customdata, int type)
void ED_region_draw_cb_exit (ARegionType *art, void *handle)
void * ED_region_draw_cb_customdata (void *handle)
void ED_region_draw_cb_draw (const bContext *C, ARegion *ar, int type)
void ED_spacetype_xxx (void)
static SpaceLink * xxx_new (const bContext *UNUSED(C))
static void xxx_free (SpaceLink *UNUSED(sl))
static void xxx_init (wmWindowManager *UNUSED(wm), ScrArea *UNUSED(sa))
static SpaceLink * xxx_duplicate (SpaceLink *UNUSED(sl))
static void xxx_operatortypes (void)
static void xxx_keymap (wmKeyConfig *UNUSED(keyconf))
Detailed Description
Definition in file spacetypes.c.
Typedef Documentation
typedef struct RegionDrawCB RegionDrawCB
Function Documentation
void* ED_region_draw_cb_activate (ARegionType * art, void(*)(const struct bContext *, struct ARegion *, void *) draw, void * customdata, int type)
Definition at line 194 of file spacetypes.c.
References BLI_addtail(), RegionDrawCB::customdata, RegionDrawCB::draw, ARegionType::drawcalls, MEM_callocN(), ARegion::type, and RegionDrawCB::type.
Referenced by image_sample_invoke(), initFlyInfo(), initTransform(), knifetool_init(), pyrna_callback_add(), ringsel_init(), sample_invoke(), and vtx_slide_init().
void* ED_region_draw_cb_customdata (void * handle)
Definition at line 221 of file spacetypes.c.
Referenced by pyrna_callback_remove().
void ED_region_draw_cb_draw (const bContext * C, ARegion * ar, int type)
Definition at line 226 of file spacetypes.c.
References RegionDrawCB::customdata, RegionDrawCB::draw, ARegionType::drawcalls, ListBase::first, RegionDrawCB::next, RegionDrawCB::type, and ARegion::type.
void ED_region_draw_cb_exit (ARegionType * art, void * handle)
Definition at line 208 of file spacetypes.c.
References BLI_remlink(), ARegionType::drawcalls, ListBase::first, MEM_freeN(), and RegionDrawCB::next.
Referenced by flyEnd(), image_sample_exit(), knifetool_exit(), postTrans(), pyrna_callback_remove(), ringsel_exit(), sample_exit(), and vtx_slide_exit().
void ED_spacetype_xxx (void)
Definition at line 282 of file spacetypes.c.
References BKE_spacetype_register(), SpaceType::duplicate, SpaceType::free, SpaceType::init, SpaceType::keymap, SpaceType::new, SpaceType::operatortypes, SPACE_VIEW3D, SpaceType::spaceid, xxx_duplicate(), xxx_free(), xxx_init(), xxx_keymap(), xxx_new(), and xxx_operatortypes().
void ED_spacetypes_init (void)
Definition at line 67 of file spacetypes.c.
References BKE_spacetypes_list(), SpaceType::dropboxes, ED_operatormacros_action(), ED_operatormacros_armature(), ED_operatormacros_clip(), ED_operatormacros_curve(), ED_operatormacros_file(), ED_operatormacros_graph(), ED_operatormacros_mesh(), ED_operatormacros_node(), ED_operatormacros_object(), ED_operatortypes_anim(), ED_operatortypes_animchannels(), ED_operatortypes_armature(), ED_operatortypes_curve(), ED_operatortypes_gpencil(), ED_operatortypes_logic(), ED_operatortypes_marker(), ED_operatortypes_mesh(), ED_operatortypes_metaball(), ED_operatortypes_object(), ED_operatortypes_paint(), ED_operatortypes_physics(), ED_operatortypes_render(), ED_operatortypes_screen(), ED_operatortypes_sculpt(), ED_operatortypes_sound(), ED_operatortypes_uvedit(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), ListBase::first, SpaceType::next, SpaceType::operatortypes, spacetypes, UI_buttons_operatortypes(), and UI_view2d_operatortypes().
Referenced by WM_init().
void ED_spacetypes_keymap (wmKeyConfig * keyconf)
Definition at line 149 of file spacetypes.c.
References BKE_spacetypes_list(), ED_keymap_anim(), ED_keymap_animchannels(), ED_keymap_armature(), ED_keymap_curve(), ED_keymap_gpencil(), ED_keymap_mesh(), ED_keymap_metaball(), ED_keymap_object(), ED_keymap_paint(), ED_keymap_physics(), ED_keymap_screen(), ED_keymap_uvedit(), ED_marker_keymap(), ListBase::first, ARegionType::keymap, SpaceType::keymap, ARegionType::next, SpaceType::next, SpaceType::regiontypes, spacetypes, and UI_view2d_keymap().
Referenced by WM_keymap_init().
static SpaceLink* xxx_duplicate (SpaceLink * UNUSEDsl) [static]
Definition at line 265 of file spacetypes.c.
References NULL.
Referenced by ED_spacetype_xxx().
static void xxx_free (SpaceLink * UNUSEDsl) [static]
Definition at line 249 of file spacetypes.c.
Referenced by ED_spacetype_xxx().
static void xxx_init (wmWindowManager * UNUSEDwm, ScrArea * UNUSEDsa) [static]
Definition at line 255 of file spacetypes.c.
Referenced by ED_spacetype_xxx().
static void xxx_keymap (wmKeyConfig * UNUSEDkeyconf) [static]
Definition at line 276 of file spacetypes.c.
Referenced by ED_spacetype_xxx().
static SpaceLink* xxx_new (const bContext * UNUSEDC) [static]
Definition at line 243 of file spacetypes.c.
References NULL.
Referenced by ED_spacetype_xxx().
static void xxx_operatortypes (void) [static]
Definition at line 271 of file spacetypes.c.
Referenced by ED_spacetype_xxx().