Blender: NOD_shader.h File Reference
NOD_shader.h File Reference
nodes
#include "BKE_node.h"
Functions
void register_node_type_sh_group (struct bNodeTreeType *ttype)
void register_node_type_sh_forloop (struct bNodeTreeType *ttype)
void register_node_type_sh_whileloop (struct bNodeTreeType *ttype)
void register_node_type_sh_output (struct bNodeTreeType *ttype)
void register_node_type_sh_material (struct bNodeTreeType *ttype)
void register_node_type_sh_camera (struct bNodeTreeType *ttype)
void register_node_type_sh_value (struct bNodeTreeType *ttype)
void register_node_type_sh_rgb (struct bNodeTreeType *ttype)
void register_node_type_sh_mix_rgb (struct bNodeTreeType *ttype)
void register_node_type_sh_valtorgb (struct bNodeTreeType *ttype)
void register_node_type_sh_rgbtobw (struct bNodeTreeType *ttype)
void register_node_type_sh_texture (struct bNodeTreeType *ttype)
void register_node_type_sh_normal (struct bNodeTreeType *ttype)
void register_node_type_sh_gamma (struct bNodeTreeType *ttype)
void register_node_type_sh_brightcontrast (struct bNodeTreeType *ttype)
void register_node_type_sh_geom (struct bNodeTreeType *ttype)
void register_node_type_sh_mapping (struct bNodeTreeType *ttype)
void register_node_type_sh_curve_vec (struct bNodeTreeType *ttype)
void register_node_type_sh_curve_rgb (struct bNodeTreeType *ttype)
void register_node_type_sh_math (struct bNodeTreeType *ttype)
void register_node_type_sh_vect_math (struct bNodeTreeType *ttype)
void register_node_type_sh_squeeze (struct bNodeTreeType *ttype)
void register_node_type_sh_dynamic (struct bNodeTreeType *ttype)
void register_node_type_sh_material_ext (struct bNodeTreeType *ttype)
void register_node_type_sh_invert (struct bNodeTreeType *ttype)
void register_node_type_sh_seprgb (struct bNodeTreeType *ttype)
void register_node_type_sh_combrgb (struct bNodeTreeType *ttype)
void register_node_type_sh_hue_sat (struct bNodeTreeType *ttype)
void register_node_type_sh_attribute (struct bNodeTreeType *ttype)
void register_node_type_sh_geometry (struct bNodeTreeType *ttype)
void register_node_type_sh_light_path (struct bNodeTreeType *ttype)
void register_node_type_sh_fresnel (struct bNodeTreeType *ttype)
void register_node_type_sh_layer_weight (struct bNodeTreeType *ttype)
void register_node_type_sh_tex_coord (struct bNodeTreeType *ttype)
void register_node_type_sh_background (struct bNodeTreeType *ttype)
void register_node_type_sh_bsdf_diffuse (struct bNodeTreeType *ttype)
void register_node_type_sh_bsdf_glossy (struct bNodeTreeType *ttype)
void register_node_type_sh_bsdf_glass (struct bNodeTreeType *ttype)
void register_node_type_sh_bsdf_translucent (struct bNodeTreeType *ttype)
void register_node_type_sh_bsdf_transparent (struct bNodeTreeType *ttype)
void register_node_type_sh_bsdf_velvet (struct bNodeTreeType *ttype)
void register_node_type_sh_emission (struct bNodeTreeType *ttype)
void register_node_type_sh_holdout (struct bNodeTreeType *ttype)
void register_node_type_sh_volume_transparent (struct bNodeTreeType *ttype)
void register_node_type_sh_volume_isotropic (struct bNodeTreeType *ttype)
void register_node_type_sh_mix_shader (struct bNodeTreeType *ttype)
void register_node_type_sh_add_shader (struct bNodeTreeType *ttype)
void register_node_type_sh_output_lamp (struct bNodeTreeType *ttype)
void register_node_type_sh_output_material (struct bNodeTreeType *ttype)
void register_node_type_sh_output_world (struct bNodeTreeType *ttype)
void register_node_type_sh_tex_image (struct bNodeTreeType *ttype)
void register_node_type_sh_tex_environment (struct bNodeTreeType *ttype)
void register_node_type_sh_tex_sky (struct bNodeTreeType *ttype)
void register_node_type_sh_tex_voronoi (struct bNodeTreeType *ttype)
void register_node_type_sh_tex_gradient (struct bNodeTreeType *ttype)
void register_node_type_sh_tex_magic (struct bNodeTreeType *ttype)
void register_node_type_sh_tex_wave (struct bNodeTreeType *ttype)
void register_node_type_sh_tex_musgrave (struct bNodeTreeType *ttype)
void register_node_type_sh_tex_noise (struct bNodeTreeType *ttype)
void register_node_type_sh_tex_checker (struct bNodeTreeType *ttype)
Variables
struct bNodeTreeType ntreeType_Shader
Detailed Description
Definition in file NOD_shader.h.
Function Documentation
void register_node_type_sh_add_shader (struct bNodeTreeType * ttype)
Definition at line 49 of file node_shader_add_shader.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_shader_gpu_add_shader(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_ADD_SHADER.
Referenced by registerShaderNodes().
void register_node_type_sh_attribute (struct bNodeTreeType * ttype)
Definition at line 46 of file node_shader_attribute.c.
References NODE_CLASS_INPUT, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OPTIONS, node_shader_init_attribute(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_ATTRIBUTE.
Referenced by registerShaderNodes().
void register_node_type_sh_background (struct bNodeTreeType * ttype)
Definition at line 44 of file node_shader_background.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_BACKGROUND.
Referenced by registerShaderNodes().
void register_node_type_sh_brightcontrast (struct bNodeTreeType * ttype)
Definition at line 46 of file node_shader_brightness.c.
References NODE_CLASS_OP_COLOR, NODE_NEW_SHADING, NODE_OPTIONS, node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_BRIGHTCONTRAST.
Referenced by registerShaderNodes().
void register_node_type_sh_bsdf_diffuse (struct bNodeTreeType * ttype)
Definition at line 49 of file node_shader_bsdf_diffuse.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_shader_gpu_bsdf_diffuse(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_BSDF_DIFFUSE.
Referenced by registerShaderNodes().
void register_node_type_sh_bsdf_glass (struct bNodeTreeType * ttype)
Definition at line 50 of file node_shader_bsdf_glass.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, NODE_OPTIONS, node_shader_gpu_bsdf_glass(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_BSDF_GLASS.
Referenced by registerShaderNodes().
void register_node_type_sh_bsdf_glossy (struct bNodeTreeType * ttype)
Definition at line 50 of file node_shader_bsdf_glossy.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, NODE_OPTIONS, node_shader_gpu_bsdf_glossy(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_BSDF_GLOSSY.
Referenced by registerShaderNodes().
void register_node_type_sh_bsdf_translucent (struct bNodeTreeType * ttype)
Definition at line 48 of file node_shader_bsdf_translucent.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_shader_gpu_bsdf_translucent(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_BSDF_TRANSLUCENT.
Referenced by registerShaderNodes().
void register_node_type_sh_bsdf_transparent (struct bNodeTreeType * ttype)
Definition at line 48 of file node_shader_bsdf_transparent.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_shader_gpu_bsdf_transparent(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_BSDF_TRANSPARENT.
Referenced by registerShaderNodes().
void register_node_type_sh_bsdf_velvet (struct bNodeTreeType * ttype)
Definition at line 49 of file node_shader_bsdf_velvet.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_shader_gpu_bsdf_velvet(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_BSDF_VELVET.
Referenced by registerShaderNodes().
void register_node_type_sh_camera (struct bNodeTreeType * ttype)
Definition at line 60 of file node_shader_camera.c.
References gpu_shader_camera(), NODE_CLASS_INPUT, NODE_NEW_SHADING, NODE_OLD_SHADING, node_shader_exec_camera(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_CAMERA.
Referenced by registerShaderNodes().
void register_node_type_sh_combrgb (struct bNodeTreeType * ttype)
Definition at line 99 of file node_shader_sepcombRGB.c.
References gpu_shader_combrgb(), NODE_CLASS_CONVERTOR, NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_combrgb(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_COMBRGB.
Referenced by registerShaderNodes().
void register_node_type_sh_curve_rgb (struct bNodeTreeType * ttype)
Definition at line 127 of file node_shader_curves.c.
References gpu_shader_curve_rgb(), NODE_CLASS_OP_COLOR, node_copy_curves(), node_free_curves(), NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_curve_rgb(), node_shader_init_curve_rgb(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and SH_NODE_CURVE_RGB.
Referenced by registerShaderNodes().
void register_node_type_sh_curve_vec (struct bNodeTreeType * ttype)
Definition at line 72 of file node_shader_curves.c.
References gpu_shader_curve_vec(), NODE_CLASS_OP_VECTOR, node_copy_curves(), node_free_curves(), NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_curve_vec(), node_shader_init_curve_vec(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and SH_NODE_CURVE_VEC.
Referenced by registerShaderNodes().
void register_node_type_sh_dynamic (struct bNodeTreeType * ttype)
Definition at line 788 of file node_shader_dynamic.c.
References NODE_CLASS_OP_DYNAMIC, NODE_DYNAMIC, NODE_OLD_SHADING, node_type_base(), node_type_compatibility(), and nodeRegisterType().
void register_node_type_sh_emission (struct bNodeTreeType * ttype)
Definition at line 49 of file node_shader_emission.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_shader_gpu_emission(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_EMISSION.
Referenced by registerShaderNodes().
void register_node_type_sh_forloop (struct bNodeTreeType * ttype)
void register_node_type_sh_fresnel (struct bNodeTreeType * ttype)
Definition at line 48 of file node_shader_fresnel.c.
References NODE_CLASS_INPUT, NODE_NEW_SHADING, node_shader_gpu_fresnel(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_FRESNEL.
Referenced by registerShaderNodes().
void register_node_type_sh_gamma (struct bNodeTreeType * ttype)
Definition at line 44 of file node_shader_gamma.c.
References NODE_CLASS_OP_COLOR, NODE_NEW_SHADING, NODE_OPTIONS, node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_GAMMA.
Referenced by registerShaderNodes().
void register_node_type_sh_geom (struct bNodeTreeType * ttype)
Definition at line 141 of file node_shader_geom.c.
References gpu_shader_geom(), NODE_CLASS_INPUT, node_copy_standard_storage(), node_free_standard_storage(), NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_geom(), node_shader_init_geometry(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_GEOMETRY.
Referenced by registerShaderNodes().
void register_node_type_sh_geometry (struct bNodeTreeType * ttype)
Definition at line 51 of file node_shader_geometry.c.
References NODE_CLASS_INPUT, NODE_NEW_SHADING, node_shader_gpu_geometry(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_NEW_GEOMETRY.
Referenced by registerShaderNodes().
void register_node_type_sh_group (struct bNodeTreeType * ttype)
Definition at line 183 of file node_shader_common.c.
References gpu_group_execute(), group_execute(), group_freeexec(), group_initexec(), NODE_CLASS_GROUP, NODE_CONST_OUTPUT, NODE_GROUP, node_group_edit_clear(), node_group_edit_get(), node_group_edit_set(), node_group_init(), node_group_label(), node_group_template(), node_group_valid(), node_group_verify(), NODE_OPTIONS, node_type_base(), node_type_exec_new(), node_type_gpu_ext(), node_type_group_edit(), node_type_init(), node_type_label(), node_type_size(), node_type_socket_templates(), node_type_template(), node_type_update(), node_type_valid(), nodeRegisterType(), and NULL.
Referenced by registerShaderNodes().
void register_node_type_sh_holdout (struct bNodeTreeType * ttype)
Definition at line 43 of file node_shader_holdout.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_HOLDOUT.
Referenced by registerShaderNodes().
void register_node_type_sh_hue_sat (struct bNodeTreeType * ttype)
Definition at line 83 of file node_shader_hueSatVal.c.
References gpu_shader_hue_sat(), NODE_CLASS_OP_COLOR, NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_hue_sat(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_HUE_SAT.
Referenced by registerShaderNodes().
void register_node_type_sh_invert (struct bNodeTreeType * ttype)
Definition at line 75 of file node_shader_invert.c.
References gpu_shader_invert(), NODE_CLASS_OP_COLOR, NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_invert(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_INVERT.
Referenced by registerShaderNodes().
void register_node_type_sh_layer_weight (struct bNodeTreeType * ttype)
Definition at line 49 of file node_shader_layer_weight.c.
References NODE_CLASS_INPUT, NODE_NEW_SHADING, node_shader_gpu_layer_weight(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_LAYER_WEIGHT.
Referenced by registerShaderNodes().
void register_node_type_sh_light_path (struct bNodeTreeType * ttype)
Definition at line 49 of file node_shader_light_path.c.
References NODE_CLASS_INPUT, NODE_NEW_SHADING, node_shader_gpu_light_path(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_LIGHT_PATH.
Referenced by registerShaderNodes().
void register_node_type_sh_mapping (struct bNodeTreeType * ttype)
Definition at line 89 of file node_shader_mapping.c.
References gpu_shader_mapping(), NODE_CLASS_OP_VECTOR, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_mapping(), node_shader_init_mapping(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and SH_NODE_MAPPING.
Referenced by registerShaderNodes().
void register_node_type_sh_material (struct bNodeTreeType * ttype)
Definition at line 303 of file node_shader_material.c.
References gpu_shader_material(), NODE_CLASS_INPUT, NODE_OLD_SHADING, NODE_OPTIONS, NODE_PREVIEW, node_shader_exec_material(), node_shader_init_material(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_MATERIAL.
Referenced by registerShaderNodes().
void register_node_type_sh_material_ext (struct bNodeTreeType * ttype)
Definition at line 319 of file node_shader_material.c.
References gpu_shader_material(), NODE_CLASS_INPUT, NODE_OLD_SHADING, NODE_OPTIONS, NODE_PREVIEW, node_shader_exec_material(), node_shader_init_material(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_MATERIAL_EXT.
Referenced by registerShaderNodes().
void register_node_type_sh_math (struct bNodeTreeType * ttype)
Definition at line 239 of file node_shader_math.c.
References gpu_shader_math(), NODE_CLASS_CONVERTOR, node_math_label(), NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_math(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_label(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_MATH.
Referenced by registerShaderNodes().
void register_node_type_sh_mix_rgb (struct bNodeTreeType * ttype)
Definition at line 76 of file node_shader_mixRgb.c.
References gpu_shader_mix_rgb(), node_blend_label(), NODE_CLASS_OP_COLOR, NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_mix_rgb(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_label(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_MIX_RGB.
Referenced by registerShaderNodes().
void register_node_type_sh_mix_shader (struct bNodeTreeType * ttype)
Definition at line 50 of file node_shader_mix_shader.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_shader_gpu_mix_shader(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_MIX_SHADER.
Referenced by registerShaderNodes().
void register_node_type_sh_normal (struct bNodeTreeType * ttype)
Definition at line 82 of file node_shader_normal.c.
References gpu_shader_normal(), NODE_CLASS_OP_VECTOR, NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_normal(), node_shader_init_normal(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_NORMAL.
Referenced by registerShaderNodes().
void register_node_type_sh_output (struct bNodeTreeType * ttype)
Definition at line 83 of file node_shader_output.c.
References gpu_shader_output(), NODE_CLASS_OUTPUT, NODE_OLD_SHADING, NODE_PREVIEW, node_shader_exec_output(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), NULL, and SH_NODE_OUTPUT.
Referenced by registerShaderNodes().
void register_node_type_sh_output_lamp (struct bNodeTreeType * ttype)
Definition at line 38 of file node_shader_output_lamp.c.
References NODE_CLASS_OUTPUT, NODE_NEW_SHADING, node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_OUTPUT_LAMP.
Referenced by registerShaderNodes().
void register_node_type_sh_output_material (struct bNodeTreeType * ttype)
Definition at line 51 of file node_shader_output_material.c.
References NODE_CLASS_OUTPUT, NODE_NEW_SHADING, node_shader_gpu_output_material(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_OUTPUT_MATERIAL.
Referenced by registerShaderNodes().
void register_node_type_sh_output_world (struct bNodeTreeType * ttype)
Definition at line 39 of file node_shader_output_world.c.
References NODE_CLASS_OUTPUT, NODE_NEW_SHADING, node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_OUTPUT_WORLD.
Referenced by registerShaderNodes().
void register_node_type_sh_rgb (struct bNodeTreeType * ttype)
Definition at line 69 of file node_shader_rgb.c.
References gpu_shader_rgb(), NODE_CLASS_INPUT, NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_rgb(), node_shader_init_rgb(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), NULL, and SH_NODE_RGB.
Referenced by registerShaderNodes().
void register_node_type_sh_rgbtobw (struct bNodeTreeType * ttype)
Definition at line 115 of file node_shader_valToRgb.c.
References gpu_shader_rgbtobw(), NODE_CLASS_CONVERTOR, NODE_NEW_SHADING, NODE_OLD_SHADING, node_shader_exec_rgbtobw(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_RGBTOBW.
Referenced by registerShaderNodes().
void register_node_type_sh_seprgb (struct bNodeTreeType * ttype)
Definition at line 59 of file node_shader_sepcombRGB.c.
References gpu_shader_seprgb(), NODE_CLASS_CONVERTOR, NODE_NEW_SHADING, NODE_OLD_SHADING, node_shader_exec_seprgb(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_SEPRGB.
Referenced by registerShaderNodes().
void register_node_type_sh_squeeze (struct bNodeTreeType * ttype)
Definition at line 65 of file node_shader_squeeze.c.
References gpu_shader_squeeze(), NODE_CLASS_CONVERTOR, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_squeeze(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_SQUEEZE.
Referenced by registerShaderNodes().
void register_node_type_sh_tex_checker (struct bNodeTreeType * ttype)
Definition at line 66 of file node_shader_tex_checker.c.
References NODE_CLASS_TEXTURE, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, node_shader_gpu_tex_checker(), node_shader_init_tex_checker(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_CHECKER.
Referenced by registerShaderNodes().
void register_node_type_sh_tex_coord (struct bNodeTreeType * ttype)
Definition at line 55 of file node_shader_tex_coord.c.
References NODE_CLASS_INPUT, NODE_NEW_SHADING, node_shader_gpu_tex_coord(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_COORD.
Referenced by registerShaderNodes().
void register_node_type_sh_tex_environment (struct bNodeTreeType * ttype)
Definition at line 73 of file node_shader_tex_environment.c.
References NODE_CLASS_TEXTURE, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OPTIONS, node_shader_gpu_tex_environment(), node_shader_init_tex_environment(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_ENVIRONMENT.
Referenced by registerShaderNodes().
void register_node_type_sh_tex_gradient (struct bNodeTreeType * ttype)
Definition at line 64 of file node_shader_tex_gradient.c.
References NODE_CLASS_TEXTURE, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OPTIONS, node_shader_gpu_tex_gradient(), node_shader_init_tex_gradient(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_GRADIENT.
Referenced by registerShaderNodes().
void register_node_type_sh_tex_image (struct bNodeTreeType * ttype)
Definition at line 73 of file node_shader_tex_image.c.
References NODE_CLASS_TEXTURE, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OPTIONS, node_shader_gpu_tex_image(), node_shader_init_tex_image(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_IMAGE.
Referenced by registerShaderNodes().
void register_node_type_sh_tex_magic (struct bNodeTreeType * ttype)
Definition at line 69 of file node_shader_tex_magic.c.
References NODE_CLASS_TEXTURE, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OPTIONS, node_shader_gpu_tex_magic(), node_shader_init_tex_magic(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_MAGIC.
Referenced by registerShaderNodes().
void register_node_type_sh_tex_musgrave (struct bNodeTreeType * ttype)
Definition at line 70 of file node_shader_tex_musgrave.c.
References NODE_CLASS_TEXTURE, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OPTIONS, node_shader_gpu_tex_musgrave(), node_shader_init_tex_musgrave(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_MUSGRAVE.
Referenced by registerShaderNodes().
void register_node_type_sh_tex_noise (struct bNodeTreeType * ttype)
Definition at line 66 of file node_shader_tex_noise.c.
References NODE_CLASS_TEXTURE, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, node_shader_gpu_tex_noise(), node_shader_init_tex_noise(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_NOISE.
Referenced by registerShaderNodes().
void register_node_type_sh_tex_sky (struct bNodeTreeType * ttype)
Definition at line 66 of file node_shader_tex_sky.c.
References NODE_CLASS_TEXTURE, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OPTIONS, node_shader_gpu_tex_sky(), node_shader_init_tex_sky(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_SKY.
Referenced by registerShaderNodes().
void register_node_type_sh_tex_voronoi (struct bNodeTreeType * ttype)
Definition at line 65 of file node_shader_tex_voronoi.c.
References NODE_CLASS_TEXTURE, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OPTIONS, node_shader_gpu_tex_voronoi(), node_shader_init_tex_voronoi(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_VORONOI.
Referenced by registerShaderNodes().
void register_node_type_sh_tex_wave (struct bNodeTreeType * ttype)
Definition at line 68 of file node_shader_tex_wave.c.
References NODE_CLASS_TEXTURE, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OPTIONS, node_shader_gpu_tex_wave(), node_shader_init_tex_wave(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_WAVE.
Referenced by registerShaderNodes().
void register_node_type_sh_texture (struct bNodeTreeType * ttype)
Definition at line 136 of file node_shader_texture.c.
References gpu_shader_texture(), NODE_CLASS_INPUT, NODE_OLD_SHADING, NODE_OPTIONS, NODE_PREVIEW, node_shader_exec_texture(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_TEXTURE.
Referenced by registerShaderNodes().
void register_node_type_sh_valtorgb (struct bNodeTreeType * ttype)
Definition at line 74 of file node_shader_valToRgb.c.
References gpu_shader_valtorgb(), NODE_CLASS_CONVERTOR, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_valtorgb(), node_shader_init_valtorgb(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and SH_NODE_VALTORGB.
Referenced by registerShaderNodes().
void register_node_type_sh_value (struct bNodeTreeType * ttype)
Definition at line 69 of file node_shader_value.c.
References gpu_shader_value(), NODE_CLASS_INPUT, NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_value(), node_shader_init_value(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), NULL, and SH_NODE_VALUE.
Referenced by registerShaderNodes().
void register_node_type_sh_vect_math (struct bNodeTreeType * ttype)
Definition at line 133 of file node_shader_vectMath.c.
References gpu_shader_vect_math(), NODE_CLASS_CONVERTOR, NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_vect_math(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_label(), node_type_size(), node_type_socket_templates(), node_type_storage(), node_vect_math_label(), nodeRegisterType(), NULL, and SH_NODE_VECT_MATH.
Referenced by registerShaderNodes().
void register_node_type_sh_volume_isotropic (struct bNodeTreeType * ttype)
Definition at line 49 of file node_shader_volume_isotropic.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_shader_gpu_volume_isotropic(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_VOLUME_ISOTROPIC.
void register_node_type_sh_volume_transparent (struct bNodeTreeType * ttype)
Definition at line 49 of file node_shader_volume_transparent.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_shader_gpu_volume_transparent(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_VOLUME_TRANSPARENT.
void register_node_type_sh_whileloop (struct bNodeTreeType * ttype)
Variable Documentation
struct bNodeTreeType ntreeType_Shader
Definition at line 138 of file node_shader_tree.c.
Referenced by ntreeGetType().