Blender: bullet.c File Reference
bullet.c File Reference
blenkernel
#include "MEM_guardedalloc.h"
#include "DNA_object_force.h"
#include "BKE_bullet.h"
Functions
BulletSoftBody * bsbNew (void)
void bsbFree (BulletSoftBody *bsb)
Detailed Description
Definition in file bullet.c.
Function Documentation
void bsbFree (BulletSoftBody * bsb)
Definition at line 93 of file bullet.c.
References MEM_freeN().
Referenced by free_object(), and object_free_bulletsoftbody().
BulletSoftBody* bsbNew (void) [read]
Definition at line 44 of file bullet.c.
References BulletSoftBody::angStiff, BulletSoftBody::citerations, BulletSoftBody::collisionflags, BulletSoftBody::diterations, BulletSoftBody::flag, BulletSoftBody::kAHR, BulletSoftBody::kCHR, BulletSoftBody::kDF, BulletSoftBody::kDG, BulletSoftBody::kDP, BulletSoftBody::kKHR, BulletSoftBody::kLF, BulletSoftBody::kMT, BulletSoftBody::kPR, BulletSoftBody::kSHR, BulletSoftBody::kSK_SPLT_CL, BulletSoftBody::kSKHR_CL, BulletSoftBody::kSR_SPLT_CL, BulletSoftBody::kSRHR_CL, BulletSoftBody::kSS_SPLT_CL, BulletSoftBody::kSSHR_CL, BulletSoftBody::kVC, BulletSoftBody::kVCF, BulletSoftBody::linStiff, MEM_callocN(), BulletSoftBody::numclusteriterations, OB_BSB_AERO_VPOINT, OB_BSB_BENDING_CONSTRAINTS, OB_BSB_SHAPE_MATCHING, BulletSoftBody::piterations, BulletSoftBody::viterations, BulletSoftBody::volume, and BulletSoftBody::welding.