Blender: AUD_SequencerReader Class Reference
AUD_SequencerReader Class Reference
#include <AUD_SequencerReader.h>
Public Member Functions
AUD_SequencerReader (AUD_Reference< AUD_SequencerFactory > factory, bool quality=false)
~AUD_SequencerReader ()
virtual bool isSeekable () const
virtual void seek (int position)
virtual int getLength () const
virtual int getPosition () const
virtual AUD_Specs getSpecs () const
virtual void read (int &length, bool &eos, sample_t *buffer)
Detailed Description
This reader plays back sequenced entries.
Definition at line 41 of file AUD_SequencerReader.h.
Constructor & Destructor Documentation
AUD_SequencerReader::AUD_SequencerReader (AUD_Reference< AUD_SequencerFactory > factory, bool quality = false)
Creates a resampling reader.
Parameters:
reader The reader to mix.
specs The target specification.
Definition at line 35 of file AUD_SequencerReader.cpp.
References AUD_SoftwareDevice::setQuality().
AUD_SequencerReader::~AUD_SequencerReader ()
Destroys the reader.
Definition at line 41 of file AUD_SequencerReader.cpp.
Member Function Documentation
int AUD_SequencerReader::getLength () const [virtual]
Returns an approximated length of the source in samples.
Returns:
The length as sample count. May be negative if unknown.
Implements AUD_IReader.
Definition at line 63 of file AUD_SequencerReader.cpp.
int AUD_SequencerReader::getPosition () const [virtual]
Returns the position of the source as a sample count value.
Returns:
The current position in the source. A negative value indicates that the position is unknown.
Warning:
The value returned doesn't always have to be correct for readers, especially after seeking.
Implements AUD_IReader.
Definition at line 68 of file AUD_SequencerReader.cpp.
AUD_Specs AUD_SequencerReader::getSpecs () const [virtual]
Returns the specification of the reader.
Returns:
The AUD_Specs structure.
Implements AUD_IReader.
Definition at line 73 of file AUD_SequencerReader.cpp.
bool AUD_SequencerReader::isSeekable () const [virtual]
Tells whether the source provides seeking functionality or not.
Warning:
This doesn't mean that the seeking always has to succeed.
Returns:
Always returns true for readers of buffering types.
Implements AUD_IReader.
Definition at line 45 of file AUD_SequencerReader.cpp.
void AUD_SequencerReader::read (int & length, bool & eos, sample_t * buffer) [virtual]
Request to read the next length samples out of the source. The buffer supplied has the needed size.
Parameters:
[in,out] length The count of samples that should be read. Shall contain the real count of samples after reading, in case there were only fewer samples available. A smaller value also indicates the end of the reader.
[out] eos End of stream, whether the end is reached or not.
[in] buffer The pointer to the buffer to read into.
Implements AUD_IReader.
Definition at line 78 of file AUD_SequencerReader.cpp.
References AUD_MAX, AUD_MIN, AUD_ReadDevice::changeSpecs(), AUD_Specs::channels, AUD_Vector3::get(), AUD_Quaternion::get(), len(), length(), AUD_Specs::rate, AUD_ReadDevice::read(), AUD_SoftwareDevice::setDistanceModel(), AUD_SoftwareDevice::setDopplerFactor(), AUD_SoftwareDevice::setListenerLocation(), AUD_SoftwareDevice::setListenerOrientation(), AUD_SoftwareDevice::setListenerVelocity(), AUD_SoftwareDevice::setSpeedOfSound(), and AUD_SoftwareDevice::setVolume().
void AUD_SequencerReader::seek (int position) [virtual]
Seeks to a specific position in the source.
Parameters:
position The position to seek for measured in samples. To get from a given time to the samples you simply have to multiply the time value in seconds with the sample rate of the reader.
Warning:
This may work or not, depending on the actual reader.
Implements AUD_IReader.
Definition at line 50 of file AUD_SequencerReader.cpp.
The documentation for this class was generated from the following files:
AUD_SequencerReader.h
AUD_SequencerReader.cpp