Blender: CM_SOLVER_DEF Struct Reference
CM_SOLVER_DEF Struct Reference
#include <BKE_cloth.h>
Public Attributes
const char * name
CM_SOLVER_ID id
int(* init)(struct Object *ob, struct ClothModifierData *clmd)
int(* solver)(struct Object *ob, float framenr, struct ClothModifierData *clmd, struct ListBase *effectors)
int(* free)(struct ClothModifierData *clmd)
Detailed Description
Definition at line 241 of file BKE_cloth.h.
Member Data Documentation
int(* CM_SOLVER_DEF::free)(struct ClothModifierData *clmd)
Definition at line 247 of file BKE_cloth.h.
Referenced by cloth_free_modifier(), and cloth_free_modifier_extern().
CM_SOLVER_ID CM_SOLVER_DEF::id
Definition at line 244 of file BKE_cloth.h.
int(* CM_SOLVER_DEF::init)(struct Object *ob, struct ClothModifierData *clmd)
Definition at line 245 of file BKE_cloth.h.
Referenced by cloth_from_object().
const char* CM_SOLVER_DEF::name
Definition at line 243 of file BKE_cloth.h.
int(* CM_SOLVER_DEF::solver)(struct Object *ob, float framenr, struct ClothModifierData *clmd, struct ListBase *effectors)
Definition at line 246 of file BKE_cloth.h.
Referenced by do_step_cloth().
The documentation for this struct was generated from the following file:
BKE_cloth.h