Blender: string_utf8.c File Reference
string_utf8.c File Reference
blenlib
#include <string.h>
#include <wchar.h>
#include <wctype.h>
#include "BLI_string_utf8.h"
Defines
#define BLI_STR_UTF8_CPY(dst, src, maxncpy)
#define UTF8_COMPUTE(Char, Mask, Len)
#define UTF8_GET(Result, Chars, Count, Mask, Len, Err)
Functions
int BLI_utf8_invalid_byte (const char *str, int length)
int BLI_utf8_invalid_strip (char *str, int length)
char * BLI_strncpy_utf8 (char *dst, const char *src, size_t maxncpy)
char * BLI_strncat_utf8 (char *dst, const char *src, size_t maxncpy)
size_t BLI_strncpy_wchar_as_utf8 (char *dst, const wchar_t *src, const size_t maxcpy)
size_t BLI_wstrlen_utf8 (const wchar_t *src)
size_t BLI_strlen_utf8 (const char *strc)
size_t BLI_strncpy_wchar_from_utf8 (wchar_t *dst_w, const char *src_c, const size_t maxcpy)
int BLI_str_utf8_size (const char *p)
unsigned int BLI_str_utf8_as_unicode (const char *p)
unsigned int BLI_str_utf8_as_unicode_and_size (const char *p, size_t *index)
unsigned int BLI_str_utf8_as_unicode_step (const char *p, size_t *index)
size_t BLI_str_utf8_from_unicode (unsigned int c, char *outbuf)
char * BLI_str_find_prev_char_utf8 (const char *str, const char *p)
char * BLI_str_find_next_char_utf8 (const char *p, const char *end)
char * BLI_str_prev_char_utf8 (const char *p)
Variables
static const char trailingBytesForUTF8 [256]
static const size_t utf8_skip_data [256]
Detailed Description
Definition in file string_utf8.c.
Define Documentation
#define BLI_STR_UTF8_CPY (dst, src, maxncpy)
Value:
{                                                                         \
        size_t utf8_size;                                                     \
        while (*src != '\0' && (utf8_size= utf8_skip_data[*src]) < maxncpy) {  \
            maxncpy -= utf8_size;                                             \
            switch(utf8_size) {                                               \
                case 6: *dst ++ = *src ++;                                    \
                case 5: *dst ++ = *src ++;                                    \
                case 4: *dst ++ = *src ++;                                    \
                case 3: *dst ++ = *src ++;                                    \
                case 2: *dst ++ = *src ++;                                    \
                case 1: *dst ++ = *src ++;                                    \
            }                                                                 \
        }                                                                     \
        *dst= '\0';                                                           \
    }
Definition at line 166 of file string_utf8.c.
Referenced by BLI_strncat_utf8(), and BLI_strncpy_utf8().
#define UTF8_COMPUTE (Char, Mask, Len)
Value:
if (Char < 128) {                                                         \
        Len = 1;                                                              \
        Mask = 0x7f;                                                          \
    }                                                                         \
    else if ((Char & 0xe0) == 0xc0) {                                         \
        Len = 2;                                                              \
        Mask = 0x1f;                                                          \
    }                                                                         \
    else if ((Char & 0xf0) == 0xe0) {                                         \
        Len = 3;                                                              \
        Mask = 0x0f;                                                          \
    }                                                                         \
    else if ((Char & 0xf8) == 0xf0) {                                         \
        Len = 4;                                                              \
        Mask = 0x07;                                                          \
    }                                                                         \
    else if ((Char & 0xfc) == 0xf8) {                                         \
        Len = 5;                                                              \
        Mask = 0x03;                                                          \
    }                                                                         \
    else if ((Char & 0xfe) == 0xfc) {                                         \
        Len = 6;                                                              \
        Mask = 0x01;                                                          \
    }                                                                         \
    else {                                                                    \
        Len = -1;                                                             \
    }
Definition at line 291 of file string_utf8.c.
Referenced by BLI_str_utf8_as_unicode(), BLI_str_utf8_as_unicode_and_size(), BLI_str_utf8_as_unicode_step(), and BLI_str_utf8_size().
#define UTF8_GET (Result, Chars, Count, Mask, Len, Err)
Value:
(Result) = (Chars)[0] & (Mask);                                           \
    for ((Count) = 1; (Count) < (Len); ++(Count)) {                           \
        if (((Chars)[(Count)] & 0xc0) != 0x80) {                              \
            (Result) = Err;                                                   \
            break;                                                            \
        }                                                                     \
        (Result) <<= 6;                                                       \
        (Result) |= ((Chars)[(Count)] & 0x3f);                                \
    }
Definition at line 321 of file string_utf8.c.
Referenced by BLI_str_utf8_as_unicode(), BLI_str_utf8_as_unicode_and_size(), and BLI_str_utf8_as_unicode_step().
Function Documentation
char* BLI_str_find_next_char_utf8 (const char * p, const char * end)
BLI_str_find_next_char_utf8: a pointer to a position within a UTF-8 encoded string a pointer to the byte following the end of the string, or NULL to indicate that the string is nul-terminated.
Finds the start of the next UTF-8 character in the string after
does not have to be at the beginning of a UTF-8 character. No check is made to see if the character found is actually valid other than it starts with an appropriate byte.
Return value: a pointer to the found character or NULL
Definition at line 530 of file string_utf8.c.
References NULL, and p.
Referenced by BLI_str_cursor_step_next_utf8(), BLI_str_utf8_as_unicode_step(), BLI_strncpy_wchar_from_utf8(), and ui_text_clip_give_next_off().
char* BLI_str_find_prev_char_utf8 (const char * str, const char * p)
BLI_str_find_prev_char_utf8: : pointer to the beginning of a UTF-8 encoded string pointer to some position within
Given a position with a UTF-8 encoded string , find the start of the previous UTF-8 character starting before. Returns NULL if no UTF-8 characters are present in before
does not have to be at the beginning of a UTF-8 character. No check is made to see if the character found is actually valid other than it starts with an appropriate byte.
Return value: a pointer to the found character or NULL.
Definition at line 505 of file string_utf8.c.
References NULL, p, and str.
Referenced by BLI_str_cursor_step_prev_utf8(), ui_text_clip_give_prev_off(), ui_text_label_rightclip(), and ui_text_leftclip().
char* BLI_str_prev_char_utf8 (const char * p)
BLI_str_prev_char_utf8: a pointer to a position within a UTF-8 encoded string
Finds the previous UTF-8 character in the string before
does not have to be at the beginning of a UTF-8 character. No check is made to see if the character found is actually valid other than it starts with an appropriate byte. If might be the first character of the string, you must use g_utf8_find_prev_char() instead.
Return value: a pointer to the found character.
Definition at line 561 of file string_utf8.c.
References p.
Referenced by draw_brackets(), txt_backspace_char(), txt_move_left(), txt_wrap_move_eol(), and unit_find_str().
unsigned int BLI_str_utf8_as_unicode (const char * p)
BLI_str_utf8_as_unicode: a pointer to Unicode character encoded as UTF-8
Converts a sequence of bytes encoded as UTF-8 to a Unicode character. If does not point to a valid UTF-8 encoded character, results are undefined. If you are not sure that the bytes are complete valid Unicode characters, you should use g_utf8_get_char_validated() instead.
Return value: the resulting character
Definition at line 360 of file string_utf8.c.
References BLI_UTF8_ERR, i, len(), UTF8_COMPUTE, and UTF8_GET.
Referenced by test_special_char(), txt_redo_read_unicode(), and txt_undo_read_unicode().
unsigned int BLI_str_utf8_as_unicode_and_size (const char * p, size_t * index)
Definition at line 375 of file string_utf8.c.
References BLI_UTF8_ERR, i, len(), UTF8_COMPUTE, and UTF8_GET.
Referenced by BLI_strncpy_wchar_from_utf8(), txt_backspace_char(), txt_delete_char(), and txt_replace_char().
unsigned int BLI_str_utf8_as_unicode_step (const char * p, size_t * index)
Definition at line 391 of file string_utf8.c.
References BLI_str_find_next_char_utf8(), BLI_UTF8_ERR, i, len(), NULL, p, UTF8_COMPUTE, and UTF8_GET.
Referenced by text_insert_exec(), and txt_insert_buf().
size_t BLI_str_utf8_from_unicode (unsigned int c, char * outbuf)
BLI_str_utf8_from_unicode: a Unicode character code
Parameters:
outbuf output buffer, must have at least 6 bytes of space. If NULL, the length will be computed and returned and nothing will be written to outbuf.
Converts a single character to UTF-8.
Return value: number of bytes written
Definition at line 446 of file string_utf8.c.
References i, and len().
Referenced by BLI_strncpy_wchar_as_utf8(), BLI_wstrlen_utf8(), text_insert_invoke(), txt_add_char_intern(), txt_extended_ascii_as_utf8(), txt_print_undo(), txt_replace_char(), and txt_undo_add_charop().
int BLI_str_utf8_size (const char * p)
Definition at line 335 of file string_utf8.c.
References len(), and UTF8_COMPUTE.
Referenced by draw_brackets(), flatten_index_to_offset(), flatten_len(), flatten_string(), text_cursor_set_to_pos_wrapped(), text_draw(), text_draw_wrapped(), text_font_draw_character_utf8(), text_get_char_pos(), text_get_cursor_rel(), text_get_visible_lines(), text_insert_invoke(), txt_format_line(), txt_move_right(), txt_utf8_get_nth(), txt_utf8_index_to_offset(), txt_utf8_len(), txt_utf8_offset_to_index(), txt_wrap_move_bol(), txt_wrap_move_eol(), ui_do_but_textedit(), ui_text_label_rightclip(), ui_text_leftclip(), ui_textedit_type_ascii(), wm_event_add_ghostevent(), WM_event_print(), wrap_offset(), and wrap_offset_in_line().
size_t BLI_strlen_utf8 (const char * strc)
Definition at line 235 of file string_utf8.c.
References len().
Referenced by BKE_text_to_curve(), and insert_text_exec().
char* BLI_strncat_utf8 (char * dst, const char * src, size_t maxncpy)
Definition at line 193 of file string_utf8.c.
References BLI_STR_UTF8_CPY.
Referenced by BLI_uniquename_cb().
char* BLI_strncpy_utf8 (char * dst, const char * src, size_t maxncpy)
Definition at line 183 of file string_utf8.c.
References BLI_STR_UTF8_CPY.
Referenced by set_engine(), ui_but_anim_expression_create(), ui_but_anim_expression_set(), ui_but_copy_paste(), ui_set_but_string(), and ui_text_leftclip().
size_t BLI_strncpy_wchar_as_utf8 (char * dst, const wchar_t * src, const size_t maxcpy)
Definition at line 210 of file string_utf8.c.
References BLI_str_utf8_from_unicode(), and len().
Referenced by insert_text_invoke(), and update_string().
size_t BLI_strncpy_wchar_from_utf8 (wchar_t * dst_w, const char * src_c, const size_t maxcpy)
Definition at line 260 of file string_utf8.c.
References BLI_str_find_next_char_utf8(), BLI_str_utf8_as_unicode_and_size(), BLI_UTF8_ERR, len(), NULL, and step().
Referenced by BKE_text_to_curve(), BPY_python_start(), insert_text_exec(), insert_text_invoke(), make_editText(), paste_file(), and PyC_SetHomePath().
int BLI_utf8_invalid_byte (const char * str, int length)
Definition at line 59 of file string_utf8.c.
References p, str, and trailingBytesForUTF8.
Referenced by BLI_utf8_invalid_strip(), and txt_extended_ascii_as_utf8().
int BLI_utf8_invalid_strip (char * str, int length)
Definition at line 125 of file string_utf8.c.
References BLI_utf8_invalid_byte().
Referenced by new_id(), and ui_textedit_end().
size_t BLI_wstrlen_utf8 (const wchar_t * src)
Definition at line 223 of file string_utf8.c.
References BLI_str_utf8_from_unicode(), len(), and NULL.
Referenced by update_string().
Variable Documentation
const char trailingBytesForUTF8[256] [static]
Initial value:
 {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,4,4,4,4,5,5,5,5
}
Definition at line 48 of file string_utf8.c.
Referenced by BLI_utf8_invalid_byte().
const size_t utf8_skip_data[256] [static]
Initial value:
 {
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
    3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,6,6,1,1
}
Definition at line 155 of file string_utf8.c.