Blender: context.c File Reference
context.c File Reference
blenkernel
#include <string.h>
#include <stddef.h>
#include "MEM_guardedalloc.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "DNA_view3d_types.h"
#include "DNA_windowmanager_types.h"
#include "DNA_object_types.h"
#include "RNA_access.h"
#include "BLI_listbase.h"
#include "BLI_string.h"
#include "BKE_context.h"
#include "BKE_main.h"
#include "BKE_screen.h"
Classes
struct bContext
struct bContextDataResult
Functions
bContext * CTX_create (void)
bContext * CTX_copy (const bContext *C)
void CTX_free (bContext *C)
bContextStore * CTX_store_add (ListBase *contexts, const char *name, PointerRNA *ptr)
bContextStore * CTX_store_add_all (ListBase *contexts, bContextStore *context)
void CTX_store_set (bContext *C, bContextStore *store)
bContextStore * CTX_store_copy (bContextStore *store)
void CTX_store_free (bContextStore *store)
void CTX_store_free_list (ListBase *contexts)
int CTX_py_init_get (bContext *C)
void CTX_py_init_set (bContext *C, int value)
void * CTX_py_dict_get (const bContext *C)
void CTX_py_dict_set (bContext *C, void *value)
wmWindowManager * CTX_wm_manager (const bContext *C)
wmWindow * CTX_wm_window (const bContext *C)
bScreen * CTX_wm_screen (const bContext *C)
ScrArea * CTX_wm_area (const bContext *C)
SpaceLink * CTX_wm_space_data (const bContext *C)
ARegion * CTX_wm_region (const bContext *C)
void * CTX_wm_region_data (const bContext *C)
struct ARegion * CTX_wm_menu (const bContext *C)
struct ReportList * CTX_wm_reports (const bContext *C)
View3D * CTX_wm_view3d (const bContext *C)
RegionView3D * CTX_wm_region_view3d (const bContext *C)
struct SpaceText * CTX_wm_space_text (const bContext *C)
struct SpaceConsole * CTX_wm_space_console (const bContext *C)
struct SpaceImage * CTX_wm_space_image (const bContext *C)
struct SpaceButs * CTX_wm_space_buts (const bContext *C)
struct SpaceFile * CTX_wm_space_file (const bContext *C)
struct SpaceSeq * CTX_wm_space_seq (const bContext *C)
struct SpaceOops * CTX_wm_space_outliner (const bContext *C)
struct SpaceNla * CTX_wm_space_nla (const bContext *C)
struct SpaceTime * CTX_wm_space_time (const bContext *C)
struct SpaceNode * CTX_wm_space_node (const bContext *C)
struct SpaceLogic * CTX_wm_space_logic (const bContext *C)
struct SpaceIpo * CTX_wm_space_graph (const bContext *C)
struct SpaceAction * CTX_wm_space_action (const bContext *C)
struct SpaceInfo * CTX_wm_space_info (const bContext *C)
struct SpaceUserPref * CTX_wm_space_userpref (const bContext *C)
struct SpaceClip * CTX_wm_space_clip (const bContext *C)
void CTX_wm_manager_set (bContext *C, wmWindowManager *wm)
void CTX_wm_window_set (bContext *C, wmWindow *win)
void CTX_wm_screen_set (bContext *C, bScreen *screen)
void CTX_wm_area_set (bContext *C, ScrArea *area)
void CTX_wm_region_set (bContext *C, ARegion *region)
void CTX_wm_menu_set (bContext *C, ARegion *menu)
void CTX_wm_operator_poll_msg_set (bContext *C, const char *msg)
const char * CTX_wm_operator_poll_msg_get (bContext *C)
static int ctx_data_get (bContext *C, const char *member, bContextDataResult *result)
static void * ctx_data_pointer_get (const bContext *C, const char *member)
static int ctx_data_pointer_verify (const bContext *C, const char *member, void **pointer)
static int ctx_data_collection_get (const bContext *C, const char *member, ListBase *list)
PointerRNA CTX_data_pointer_get (const bContext *C, const char *member)
PointerRNA CTX_data_pointer_get_type (const bContext *C, const char *member, StructRNA *type)
ListBase CTX_data_collection_get (const bContext *C, const char *member)
int CTX_data_get (const bContext *C, const char *member, PointerRNA *r_ptr, ListBase *r_lb, short *r_type)
static void data_dir_add (ListBase *lb, const char *member)
ListBase CTX_data_dir_get (const bContext *C)
int CTX_data_equals (const char *member, const char *str)
int CTX_data_dir (const char *member)
void CTX_data_id_pointer_set (bContextDataResult *result, ID *id)
void CTX_data_pointer_set (bContextDataResult *result, ID *id, StructRNA *type, void *data)
void CTX_data_id_list_add (bContextDataResult *result, ID *id)
void CTX_data_list_add (bContextDataResult *result, ID *id, StructRNA *type, void *data)
int ctx_data_list_count (const bContext *C, int(*func)(const bContext *, ListBase *))
void CTX_data_dir_set (bContextDataResult *result, const char **dir)
void CTX_data_type_set (bContextDataResult *result, short type)
short CTX_data_type_get (bContextDataResult *result)
Main * CTX_data_main (const bContext *C)
void CTX_data_main_set (bContext *C, Main *bmain)
Scene * CTX_data_scene (const bContext *C)
int CTX_data_mode_enum (const bContext *C)
const char * CTX_data_mode_string (const bContext *C)
void CTX_data_scene_set (bContext *C, Scene *scene)
ToolSettings * CTX_data_tool_settings (const bContext *C)
int CTX_data_selected_nodes (const bContext *C, ListBase *list)
int CTX_data_selected_editable_objects (const bContext *C, ListBase *list)
int CTX_data_selected_editable_bases (const bContext *C, ListBase *list)
int CTX_data_selected_objects (const bContext *C, ListBase *list)
int CTX_data_selected_bases (const bContext *C, ListBase *list)
int CTX_data_visible_objects (const bContext *C, ListBase *list)
int CTX_data_visible_bases (const bContext *C, ListBase *list)
int CTX_data_selectable_objects (const bContext *C, ListBase *list)
int CTX_data_selectable_bases (const bContext *C, ListBase *list)
struct Object * CTX_data_active_object (const bContext *C)
struct Base * CTX_data_active_base (const bContext *C)
struct Object * CTX_data_edit_object (const bContext *C)
struct Image * CTX_data_edit_image (const bContext *C)
struct Text * CTX_data_edit_text (const bContext *C)
struct MovieClip * CTX_data_edit_movieclip (const bContext *C)
struct EditBone * CTX_data_active_bone (const bContext *C)
int CTX_data_selected_bones (const bContext *C, ListBase *list)
int CTX_data_selected_editable_bones (const bContext *C, ListBase *list)
int CTX_data_visible_bones (const bContext *C, ListBase *list)
int CTX_data_editable_bones (const bContext *C, ListBase *list)
struct bPoseChannel * CTX_data_active_pose_bone (const bContext *C)
int CTX_data_selected_pose_bones (const bContext *C, ListBase *list)
int CTX_data_visible_pose_bones (const bContext *C, ListBase *list)
Variables
static const char * data_mode_strings []
Detailed Description
Definition in file context.c.
Function Documentation
bContext* CTX_copy (const bContext * C)
Definition at line 100 of file context.c.
References MEM_dupallocN().
bContext* CTX_create (void)
Definition at line 91 of file context.c.
References C, and MEM_callocN().
Referenced by ED_render_scene_update(), and main().
struct Base* CTX_data_active_base (const bContext * C) [read]
Definition at line 903 of file context.c.
References ctx_data_pointer_get().
Referenced by createObjectSpace(), createTransParticleVerts(), ED_object_enter_editmode(), ed_screen_context(), edbm_separate_exec(), posemode_exec(), select_grouped_parent(), and separate_exec().
struct EditBone* CTX_data_active_bone (const bContext * C) [read]
Definition at line 928 of file context.c.
References ctx_data_pointer_get().
Referenced by armature_align_bones_exec(), armature_parent_set_exec(), and armature_parent_set_invoke().
struct Object* CTX_data_active_object (const bContext * C) [read]
Definition at line 898 of file context.c.
References ctx_data_pointer_get().
Referenced by apply_armature_pose2bones_exec(), axis_set_view(), BIF_createTransformOrientation(), brush_edit_init(), brush_reset_exec(), brush_select_exec(), buttons_shading_context(), buttons_shading_new_context(), check_armature_actuator(), check_armature_sensor(), clear_edited_exec(), convert_exec(), convert_poll(), createTransParticleVerts(), CTX_data_mode_enum(), dependency_relations_exec(), do_logic_buts(), ED_object_active_context(), ED_operator_objectmode(), ED_operator_posemode(), ED_operator_uvmap_mesh(), ED_preview_shader_job(), ed_screen_context(), ED_sculpt_force_update(), ED_undo_push(), ed_undo_step(), ED_undo_valid(), editmode_toggle_poll(), face_select_all_exec(), face_select_hide_exec(), face_select_inverse_exec(), face_select_reveal_exec(), facemask_paint_poll(), forcefield_toggle_exec(), game_property_new(), game_property_remove(), get_driver_path_hack(), get_poselib_object(), get_selected_and_linked_obs(), get_undo_system(), gpencil_data_get_pointers(), hide_exec(), hide_show_exec(), image_main_area_draw(), image_paint_poll(), image_paint_sample_color_poll(), initTransformOrientation(), join_armature_exec(), join_curve_exec(), join_exec(), join_mesh_exec(), join_mesh_shapes_exec(), join_poll(), join_shapes_exec(), join_shapes_poll(), keyframe_jump_exec(), logic_buttons(), logic_buttons_new(), make_regular_exec(), make_regular_poll(), mask_paint_poll(), mirror_exec(), object_mode_poll(), object_mode_set_exec(), object_mode_set_itemsf(), objects_selectable_poll(), paint_poll(), paint_poll_test(), paint_select_linked_exec(), paint_select_linked_pick_invoke(), parent_clear_invoke(), parent_drop_invoke(), particle_edit_toggle_exec(), particle_edit_toggle_poll(), PE_border_select(), PE_circle_select(), PE_hair_poll(), PE_lasso_select(), PE_mouse_particles(), PE_poll(), pe_select_all_exec(), PE_set_data(), pose_armature_layers_exec(), pose_armature_layers_invoke(), pose_armature_layers_showall_exec(), pose_autoside_names_exec(), pose_bone_flip_active_exec(), pose_bone_layers_exec(), pose_bone_rotmode_exec(), pose_calculate_paths_exec(), pose_clear_paths_exec(), pose_clear_transform_generic_exec(), pose_clear_user_transforms_exec(), pose_constraints_clear_exec(), pose_copy_exec(), pose_flip_names_exec(), pose_flip_quats_exec(), pose_group_add_exec(), pose_group_assign_exec(), pose_group_deselect_exec(), pose_group_remove_exec(), pose_group_select_exec(), pose_group_unassign_exec(), pose_groups_menu_invoke(), pose_hide_exec(), pose_ik_add_exec(), pose_ik_add_invoke(), pose_ik_clear_exec(), pose_paste_exec(), pose_propagate_exec(), pose_reveal_exec(), pose_select_constraint_target_exec(), pose_select_grouped_exec(), pose_select_hierarchy_exec(), pose_select_parent_exec(), pose_slide_init(), pose_visual_transform_apply_exec(), poselib_rename_exec(), remove_doubles_exec(), reveal_exec(), screen_render_invoke(), sculpt_brush_stroke_cancel(), sculpt_brush_stroke_init(), sculpt_flush_update(), sculpt_mode_poll(), sculpt_set_persistent_base(), sculpt_stroke_done(), sculpt_stroke_test_start(), sculpt_stroke_update_step(), sculpt_toggle_mode(), sculpt_undo_restore(), sculpt_undo_restore_coords(), sculpt_undo_restore_hidden(), sculpt_update_cache_invariants(), set_texture_context(), set_vpaint(), set_wpaint(), snap_curs_to_active(), snap_curs_to_sel(), test_bake_internal(), textbox_add_exec(), textbox_remove_exec(), texture_paint_poll(), texture_paint_toggle_exec(), texture_paint_toggle_poll(), time_draw_keyframes(), time_main_area_draw(), ui_id_brush_get_icon(), vert_paint_poll(), vert_select_all_exec(), vert_select_inverse_exec(), vertex_color_set_exec(), vertex_group_fix_exec(), vertex_group_lock_exec(), vertex_paint_mode_poll(), view3d_circle_select_exec(), view3d_lasso_select(), view3d_select_invoke(), view3d_selectable_data(), view3d_set_viewcontext(), view3d_setobjectascamera_exec(), vpaint_stroke_test_start(), weight_from_bones_exec(), weight_from_bones_poll(), weight_paint_mode_poll(), weight_paint_poll(), weight_paint_set_exec(), weight_set_exec(), wpaint_stroke_done(), and wpaint_stroke_test_start().
struct bPoseChannel* CTX_data_active_pose_bone (const bContext * C) [read]
Definition at line 953 of file context.c.
References ctx_data_pointer_get().
Referenced by pose_constraint_copy_exec(), and pose_select_parent_exec().
static int ctx_data_collection_get (const bContext * C, const char * member, ListBase * list) [static]
Definition at line 554 of file context.c.
References ctx_data_get(), ListBase::first, ListBase::last, bContextDataResult::list, and NULL.
Referenced by CTX_data_editable_bones(), CTX_data_selectable_bases(), CTX_data_selectable_objects(), CTX_data_selected_bases(), CTX_data_selected_bones(), CTX_data_selected_editable_bases(), CTX_data_selected_editable_bones(), CTX_data_selected_editable_objects(), CTX_data_selected_nodes(), CTX_data_selected_objects(), CTX_data_selected_pose_bones(), CTX_data_visible_bases(), CTX_data_visible_bones(), CTX_data_visible_objects(), and CTX_data_visible_pose_bones().
ListBase CTX_data_collection_get (const bContext * C, const char * member)
Definition at line 589 of file context.c.
References ctx_data_get(), bContextDataResult::list, and NULL.
Referenced by copy_to_selected_list().
int CTX_data_dir (const char * member)
Definition at line 685 of file context.c.
Referenced by buttons_context(), clip_context(), ed_screen_context(), image_context(), node_context(), text_context(), and view3d_context().
ListBase CTX_data_dir_get (const bContext * C)
Definition at line 637 of file context.c.
References bContext::area, SpaceType::context, ARegionType::context, bScreen::context, data_dir_add(), bContextDataResult::dir, bContextStore::entries, ListBase::first, bContextStoreEntry::name, bContextStoreEntry::next, bContext::region, bContext::screen, bContext::store, ScrArea::type, ARegion::type, and bContext::wm.
Referenced by pyrna_struct_dir().
void CTX_data_dir_set (bContextDataResult * result, const char ** dir)
Definition at line 733 of file context.c.
References bContextDataResult::dir.
Referenced by buttons_context(), clip_context(), ed_screen_context(), image_context(), node_context(), text_context(), and view3d_context().
struct Image* CTX_data_edit_image (const bContext * C) [read]
Definition at line 913 of file context.c.
References ctx_data_pointer_get().
Referenced by border_select_exec(), createTransUVs(), ED_uvedit_ensure_uvs(), image_cycle_render_slot_exec(), image_cycle_render_slot_poll(), image_invert_exec(), image_invert_poll(), image_pack_exec(), image_pack_invoke(), image_pack_test(), image_reload_exec(), image_unpack_exec(), image_unpack_invoke(), mouse_select(), pin_exec(), select_all_exec(), select_linked_internal(), select_pinned_exec(), set_tile_exec(), set_tile_invoke(), snap_cursor_exec(), snap_selection_exec(), stitch_select(), unlink_selection_exec(), uv_sculpt_stroke_init(), and weld_align_uv().
struct MovieClip* CTX_data_edit_movieclip (const bContext * C) [read]
Definition at line 923 of file context.c.
References ctx_data_pointer_get().
Referenced by reload_exec().
struct Object* CTX_data_edit_object (const bContext * C) [read]
Definition at line 908 of file context.c.
References ctx_data_pointer_get().
Referenced by add_metaball_primitive(), add_nurbs_primitive(), add_primitive_circle_exec(), add_primitive_cone_exec(), add_primitive_cube_exec(), add_primitive_cylinder_exec(), add_primitive_grid_exec(), add_primitive_icosphere_exec(), add_primitive_monkey_exec(), add_primitive_plane_exec(), add_primitive_uvsphere_exec(), addvert_Nurb(), armature_align_bones_exec(), armature_autoside_names_exec(), armature_bone_layers_exec(), armature_bone_primitive_add_exec(), armature_calc_roll_exec(), armature_click_extrude_exec(), armature_delete_selected_exec(), armature_duplicate_selected_exec(), armature_extrude_exec(), armature_fill_bones_exec(), armature_flip_names_exec(), armature_hide_exec(), armature_merge_exec(), armature_parent_clear_exec(), armature_parent_set_exec(), armature_reveal_exec(), armature_select_hierarchy_exec(), armature_select_linked_invoke(), armature_subdivide_exec(), armature_switch_direction_exec(), armatureSelectedToGraph(), average_islands_scale_exec(), BIF_createTransformOrientation(), BIF_makeListTemplates(), BIF_ReebGraphMultiFromEditMesh(), BIF_retargetArc(), border_select_exec(), calc_manipulator_stats(), change_character_exec(), change_spacing_exec(), circle_select_exec(), clear_tilt_exec(), common_restrict_check(), contextSketch(), copy_text_exec(), createTransCurveVerts(), CTX_data_mode_enum(), cube_project_exec(), curvesurf_prim_add(), cut_text_exec(), cylinder_project_exec(), de_select_all_exec(), de_select_first_exec(), de_select_last_exec(), delete_exec(), delete_invoke(), delete_metaelems_exec(), deleteflagNurb(), do_uvedit_vertex(), do_view3d_header_buttons(), duplicate_exec(), duplicate_metaelems_exec(), ED_object_add_type(), ED_object_exit_editmode(), ED_operator_editarmature(), ED_operator_editcurve(), ED_operator_editcurve_3d(), ED_operator_editfont(), ED_operator_editlattice(), ED_operator_editmball(), ED_operator_editmesh(), ED_operator_editsurf(), ED_operator_editsurfcurve(), ED_operator_objectmode(), ED_operator_outliner_active_no_editobject(), ED_operator_sketch_full_mode(), ED_operator_sketch_mode(), ED_operator_uvedit(), ED_operator_uvedit_can_uv_sculpt(), ED_operator_uvmap(), ed_screen_context(), ED_undo_push(), ed_undo_step(), ED_undo_valid(), edbm_add_edge_face_exec(), edbm_beautify_fill_exec(), edbm_bevel_exec(), edbm_blend_from_shape_exec(), edbm_bridge_edge_loops_exec(), edbm_collapse_edge_exec(), edbm_collapse_edge_loop_exec(), edbm_delete_exec(), edbm_dissolve_exec(), edbm_dissolve_limited_exec(), edbm_do_smooth_vertex_exec(), edbm_duplicate_exec(), edbm_edge_rotate_selected_exec(), edbm_edge_split_exec(), edbm_extrude_edges_exec(), edbm_extrude_faces_exec(), edbm_extrude_region_exec(), edbm_extrude_repeat_exec(), edbm_extrude_verts_exec(), edbm_faces_select_interior_exec(), edbm_faces_shade_flat_exec(), edbm_faces_shade_smooth_exec(), edbm_fill_exec(), edbm_flip_normals_exec(), edbm_hide_exec(), edbm_inset_exec(), edbm_knife_cut_exec(), edbm_loop_multiselect_exec(), edbm_loop_to_region_exec(), edbm_mark_seam(), edbm_mark_sharp(), edbm_merge_exec(), edbm_noise_exec(), edbm_normals_make_consistent_exec(), edbm_quads_convert_to_tris_exec(), edbm_region_to_loop_exec(), edbm_remove_doubles_exec(), edbm_reveal_exec(), edbm_reverse_colors_exec(), edbm_reverse_uvs_exec(), edbm_rip_invoke(), edbm_rip_invoke__edge(), edbm_rip_invoke__vert(), edbm_rotate_colors_exec(), edbm_rotate_uvs_exec(), edbm_screw_exec(), edbm_select_all_exec(), edbm_select_axis_exec(), edbm_select_by_number_vertices_exec(), edbm_select_less_exec(), edbm_select_linked_exec(), edbm_select_linked_flat_faces_exec(), edbm_select_linked_pick_invoke(), edbm_select_loose_verts_exec(), edbm_select_mirror_exec(), edbm_select_more_exec(), edbm_select_next_loop_exec(), edbm_select_non_manifold_exec(), edbm_select_nth_exec(), edbm_select_random_exec(), edbm_select_sharp_edges_exec(), edbm_select_vertex_path_exec(), EDBM_selectmode_to_scene(), edbm_shape_propagate_to_all_exec(), edbm_shortest_path_select_poll(), edbm_solidify_exec(), edbm_sort_faces_exec(), edbm_spin_exec(), edbm_split_exec(), edbm_subdivide_exec(), edbm_tris_convert_to_quads_exec(), edbm_vert_connect(), edbm_vertex_slide_exec(), edbm_vertices_randomize_exec(), editmode_toggle_exec(), extrude_exec(), get_armature_edit(), get_data(), get_editlatt(), get_undo_system(), get_undoFont(), getEditMesh(), getTransformOrientation(), hide_exec(), hide_metaelems_exec(), hook_mod_itemf(), hook_op_edit_poll(), image_main_area_draw(), image_new_exec(), image_open_exec(), image_panel_uv_poll(), image_refresh(), image_view_selected_exec(), initTransInfo(), insert_lorem_exec(), insert_text_exec(), insert_text_invoke(), knifetool_init(), knifetool_modal(), lattice_select_all_exec(), line_break_exec(), linked_limit_default(), make_prim_finish(), make_prim_init(), make_regular_exec(), make_segment_exec(), mark_seam_exec(), material_slot_remove_exec(), mball_select_all_exec(), merge_nurb(), merge_type_itemf(), minimize_stretch_init(), mouse_armature(), mouse_mball(), mouse_nurb(), mouse_select(), move_cursor(), namebutton_cb(), navmesh_face_add_exec(), navmesh_face_copy_exec(), new_primitive_matrix(), object_add_hook_newob_exec(), object_add_hook_selob_exec(), object_add_text_exec(), object_armature_add_exec(), object_delete_exec(), object_hook_assign_exec(), object_hook_recenter_exec(), object_hook_remove_exec(), object_hook_reset_exec(), object_hook_select_exec(), object_metaball_add_exec(), object_metaball_add_invoke(), object_origin_set_exec(), object_track_clear_exec(), objects_selectable_poll(), pack_islands_exec(), paint_poll_test(), paste_file(), paste_text_exec(), peelObjectsContext(), pin_exec(), pose_select_connected_invoke(), posemode_exec(), reset_exec(), reveal_exec(), reveal_metaelems_exec(), RIG_graphFromArmature(), ringcut_invoke(), ringsel_init(), seams_from_islands_exec(), select_all_exec(), select_less_exec(), select_linked_exec(), select_linked_internal(), select_linked_pick_invoke(), select_more_exec(), select_next_exec(), select_nth_exec(), select_pinned_exec(), select_previous_exec(), select_random_exec(), select_random_metaelems_exec(), select_row_exec(), select_similar_type_itemf(), separate_armature_exec(), set_case(), set_goal_weight_exec(), set_handle_type_exec(), set_radius_exec(), set_spline_type_exec(), set_style(), set_tile_exec(), shade_smooth_exec(), shape_itemf(), similar_edge_select_exec(), similar_face_select_exec(), similar_vert_select_exec(), sk_convertStroke(), sk_makeTemplateGraph(), sk_retargetStroke(), smooth_exec(), smooth_radius_exec(), snap_curs_to_active(), snap_curs_to_sel(), snap_cursor_exec(), snap_sel_to_curs(), snap_sel_to_grid(), snap_selection_exec(), snapObjectsContext(), space_image_image_sample_poll(), sphere_project_exec(), spin_exec(), stitch_exit(), stitch_init(), stitch_invoke(), subdivide_exec(), switch_direction_exec(), texture_paint_toggle_poll(), toggle_case_exec(), toggle_cyclic_exec(), toggle_cyclic_invoke(), toggle_style_exec(), uiTemplateEditModeSelection(), uiTemplateHeader3D(), undo_clean_stack(), undo_editmode_push(), undo_editmode_step(), undo_push_mesh(), unlink_selection_exec(), unwrap_exec(), uv_from_view_exec(), uv_map_transform(), uv_sculpt_brush_poll(), uv_sculpt_stroke_init(), uv_sculpt_stroke_invoke(), uv_sculpt_stroke_modal(), uvedit_vertex_buttons(), vertex_parent_set_exec(), view3d_circle_select_exec(), view3d_panel_object(), view3d_select_invoke(), view3d_set_viewcontext(), viewselected_exec(), vtx_slide_init(), weld_align_uv(), wm_link_append_poll(), and wm_search_menu_poll().
struct Text* CTX_data_edit_text (const bContext * C) [read]
Definition at line 918 of file context.c.
References ctx_data_pointer_get().
Referenced by ED_text_undo_step(), text_clear_all_markers_exec(), text_comment_exec(), text_convert_whitespace_exec(), text_copy_exec(), text_cut_exec(), text_delete_exec(), text_edit_poll(), text_find_set_selected_exec(), text_indent_exec(), text_insert_exec(), text_jump_exec(), text_line_break_exec(), text_line_number_invoke(), text_make_internal_exec(), text_move_cursor(), text_next_marker_exec(), text_open_invoke(), text_paste_exec(), text_previous_marker_exec(), text_refresh_pyconstraints_exec(), text_region_edit_poll(), text_region_scroll_poll(), text_reload_exec(), text_replace_set_selected_exec(), text_resolve_conflict_exec(), text_resolve_conflict_invoke(), text_run_script(), text_run_script_poll(), text_save_as_exec(), text_save_as_invoke(), text_save_exec(), text_save_poll(), text_scroll_poll(), text_select_all_exec(), text_select_line_exec(), text_select_word_exec(), text_space_edit_poll(), text_to_3d_object_exec(), text_uncomment_exec(), text_unindent_exec(), text_unlink_exec(), and text_unlink_poll().
int CTX_data_editable_bones (const bContext * C, ListBase * list)
Definition at line 948 of file context.c.
References ctx_data_collection_get().
int CTX_data_equals (const char * member, const char * str)
Definition at line 680 of file context.c.
Referenced by buttons_context(), clip_context(), ed_screen_context(), image_context(), node_context(), text_context(), and view3d_context().
static int ctx_data_get (bContext * C, const char * member, bContextDataResult * result) [static]
Definition at line 463 of file context.c.
References bContext::area, BLI_rfindstring(), BPY_context_member_get(), SpaceType::context, ARegionType::context, bScreen::context, CTX_py_dict_get(), bContext::data, bContextStore::entries, bContextDataResult::ptr, bContextStoreEntry::ptr, bContext::recursion, bContext::region, bContext::screen, bContext::store, ScrArea::type, ARegion::type, and bContext::wm.
Referenced by CTX_data_collection_get(), ctx_data_collection_get(), CTX_data_get(), ctx_data_pointer_get(), CTX_data_pointer_get(), and ctx_data_pointer_verify().
int CTX_data_get (const bContext * C, const char * member, PointerRNA * r_ptr, ListBase * r_lb, short * r_type)
Definition at line 603 of file context.c.
References ctx_data_get(), bContextDataResult::list, bContextDataResult::ptr, and bContextDataResult::type.
Referenced by pyrna_struct_getattro(), and pyrna_struct_setattro().
void CTX_data_id_list_add (bContextDataResult * result, ID * id)
Definition at line 700 of file context.c.
References BLI_addtail(), link(), bContextDataResult::list, MEM_callocN(), CollectionPointerLink::ptr, and RNA_id_pointer_create().
Referenced by ed_screen_context(), and view3d_context().
void CTX_data_id_pointer_set (bContextDataResult * result, ID * id)
Definition at line 690 of file context.c.
References bContextDataResult::ptr, and RNA_id_pointer_create().
Referenced by clip_context(), ed_screen_context(), image_context(), text_context(), and view3d_context().
void CTX_data_list_add (bContextDataResult * result, ID * id, StructRNA * type, void * data)
Definition at line 710 of file context.c.
References BLI_addtail(), link(), bContextDataResult::list, MEM_callocN(), CollectionPointerLink::ptr, and RNA_pointer_create().
Referenced by BPY_context_member_get(), ed_screen_context(), node_context(), and view3d_context().
int ctx_data_list_count (const bContext * C, int(*)(const bContext *, ListBase *) func)
Definition at line 720 of file context.c.
References BLI_countlist(), and BLI_freelistN().
Main* CTX_data_main (const bContext * C) [read]
Definition at line 750 of file context.c.
References ctx_data_pointer_verify(), bContext::data, and bContext::main.
Referenced by add_driver_button_exec(), add_keyingset_button_exec(), add_named_exec(), apply_objects_internal(), autocomplete_id(), bake_image_exec(), bc_set_parent(), BKE_read_file_from_memfile(), BKE_write_undo(), bpy_context_update(), bpy_lib_exit(), BPY_modules_load_user(), BPY_string_exec(), brush_select_exec(), change_frame_apply(), clip_rebuild_proxy_exec(), constraint_add_exec(), convert_exec(), copy_object_set_idnew(), DocumentImporter::create_instance_node(), delete_key_button_exec(), delete_key_exec(), delete_key_v3d_exec(), dependency_relations_exec(), do_constraint_panels(), do_graph_region_driver_buttons(), do_logic_buts(), do_node_add(), do_node_add_group(), do_node_add_static(), draw_actuator_constraint(), draw_actuator_message(), draw_image_seq(), draw_outliner(), draw_sensor_collision(), draw_sensor_ray(), drop_named_image_invoke(), drop_named_material_invoke(), duplicate_exec(), dynamicPaint_bakeImageSequence(), ED_editors_exit(), ED_editors_init(), ed_marker_make_links_scene_exec(), ED_object_add_type(), ED_object_parent_clear(), ED_object_shape_key_remove(), ED_screen_delete(), ED_screen_delete_scene(), ED_screen_full_toggle(), ED_screen_set(), ED_screen_set_scene(), ED_uvedit_ensure_uvs(), edbm_separate_exec(), edit_object_property_get(), effector_add_type(), envmap_clear_all_exec(), find_missing_files_exec(), DocumentImporter::finish(), font_open_exec(), frame_jump_exec(), frame_offset_exec(), game_engine_exec(), get_selected_and_linked_obs(), graphview_cursor_apply(), group_create_exec(), group_instance_add_exec(), group_link_exec(), group_objects_remove_exec(), handle_view3d_lock(), id_local_cb(), image_pack_exec(), image_save_sequence_exec(), image_undo_restore(), image_unpack_exec(), init_bake_internal(), insert_key_button_exec(), insert_key_exec(), join_armature_exec(), join_curve_exec(), join_mesh_exec(), keyframe_jump_exec(), SkinInfo::link_armature(), load_file(), localview_exec(), logic_buttons(), make_links_data_exec(), make_links_scene_exec(), make_local_exec(), make_paths_absolute_exec(), make_paths_relative_exec(), make_proxy_exec(), make_single_user_exec(), modifier_add_exec(), modifier_convert_exec(), modifier_remove_exec(), move_cursor(), move_to_layer_exec(), new_particle_settings_exec(), new_particle_target_exec(), nlaedit_add_actionclip_exec(), node_add_file_exec(), node_add_menu(), node_browse_text_cb(), node_dynamic_update_cb(), node_link_viewer(), node_normal_cb(), node_read_fullsamplelayers_exec(), node_read_renderlayers_exec(), node_select_exec(), node_select_single(), node_shader_buts_dynamic(), object_add_hook_newob_exec(), object_add_hook_selob_exec(), object_clear_transform_generic_exec(), object_constraint_copy_exec(), object_constraints_clear_exec(), object_delete_cb(), object_delete_exec(), object_duplicates_make_real_exec(), object_hide_view_clear_exec(), object_hide_view_set_exec(), object_origin_clear_exec(), object_origin_set_exec(), object_select_same_group_exec(), object_slow_parent_clear_exec(), object_slow_parent_set_exec(), object_track_clear_exec(), objects_add_active_exec(), objects_remove_active_exec(), outliner_action_set_exec(), outliner_animdata_operation_exec(), outliner_object_operation_exec(), pack_all_exec(), pack_all_invoke(), parent_drop_exec(), parent_drop_invoke(), parent_noinv_set_exec(), parent_set_exec(), pose_constraint_copy_exec(), pose_constraints_clear_exec(), ptcache_bake_all_exec(), ptcache_bake_exec(), pyop_call(), pyrna_register_class(), pyrna_unregister_class(), redraw_timer_exec(), remove_driver_button_exec(), remove_keyingset_button_exec(), remove_particle_target_exec(), render_animation(), render_frame(), render_layer_remove_exec(), report_missing_files_exec(), RNA_action_itemf(), RNA_group_itemf(), RNA_group_local_itemf(), RNA_image_itemf(), RNA_image_local_itemf(), RNA_movieclip_itemf(), RNA_movieclip_local_itemf(), RNA_property_update(), RNA_scene_itemf(), RNA_scene_local_itemf(), rule_del_exec(), save_image_doit(), scene_new_exec(), screen_animation_step(), screen_opengl_render_anim_step(), screen_opengl_render_end(), screen_opengl_render_init(), screen_render_exec(), screen_render_invoke(), screen_set_exec(), screencast_exec(), select_grouped_group(), separate_armature_exec(), separate_exec(), seq_proxy_build_job(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_change_path_exec(), set_scene(), snap_sel_to_curs(), snap_sel_to_grid(), sound_bake_animation_exec(), sound_mixdown_exec(), sound_pack_exec(), sound_unpack_exec(), space_image_file_exists_poll(), spacedata_cleanup(), StartKetsjiShell(), state_del_exec(), template_texture_select(), test_actionpoin_but(), test_matpoin_but(), test_meshpoin_but(), test_obpoin_but(), test_scenepoin_but(), test_scriptpoin_but(), texface_convert_exec(), text_find_and_replace(), text_refresh_pyconstraints_exec(), text_unlink_exec(), text_update_edited(), texture_paint_camera_project_exec(), track_markers_initjob(), track_set_exec(), type_toggle_exec(), ui_node_link(), ui_template_id(), ui_template_node_link_menu(), uiTemplateRunningJobs(), unpack_all_exec(), unpack_all_invoke(), vertex_parent_set_exec(), view3d_layers_exec(), wm_add_default(), wm_autosave_timer(), WM_check(), wm_clear_default_size(), wm_event_do_handlers(), wm_event_do_notifiers(), WM_init_game(), wm_init_userdef(), wm_link_append_exec(), WM_read_file(), WM_read_homefile(), wm_window_close(), WM_write_file(), and WM_write_homefile().
void CTX_data_main_set (bContext * C, Main * bmain)
Definition at line 760 of file context.c.
References bContext::data, and bContext::main.
Referenced by ED_render_scene_update(), and setup_app_data().
int CTX_data_mode_enum (const bContext * C)
Definition at line 775 of file context.c.
References CTX_data_active_object(), CTX_data_edit_object(), CTX_MODE_EDIT_ARMATURE, CTX_MODE_EDIT_CURVE, CTX_MODE_EDIT_LATTICE, CTX_MODE_EDIT_MESH, CTX_MODE_EDIT_METABALL, CTX_MODE_EDIT_SURFACE, CTX_MODE_EDIT_TEXT, CTX_MODE_OBJECT, CTX_MODE_PAINT_TEXTURE, CTX_MODE_PAINT_VERTEX, CTX_MODE_PAINT_WEIGHT, CTX_MODE_PARTICLE, CTX_MODE_POSE, CTX_MODE_SCULPT, Object::mode, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_PARTICLE_EDIT, OB_MODE_POSE, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, OB_SURF, and Object::type.
Referenced by CTX_data_mode_string(), game_engine_poll(), and WM_keymap_guess_opname().
const char* CTX_data_mode_string (const bContext * C)
Definition at line 833 of file context.c.
References CTX_data_mode_enum().
Referenced by operator_call_cb(), view3d_panel_tool_shelf(), and view3d_tools_area_draw().
PointerRNA CTX_data_pointer_get (const bContext * C, const char * member)
Definition at line 569 of file context.c.
References ctx_data_get(), PointerRNA_NULL, and bContextDataResult::ptr.
Referenced by CTX_data_pointer_get_type(), and node_shader_buts_geometry().
static void* ctx_data_pointer_get (const bContext * C, const char * member) [static]
Definition at line 525 of file context.c.
References ctx_data_get(), PointerRNA::data, NULL, and bContextDataResult::ptr.
Referenced by CTX_data_active_base(), CTX_data_active_bone(), CTX_data_active_object(), CTX_data_active_pose_bone(), CTX_data_edit_image(), CTX_data_edit_movieclip(), CTX_data_edit_object(), and CTX_data_edit_text().
PointerRNA CTX_data_pointer_get_type (const bContext * C, const char * member, StructRNA * type)
Definition at line 579 of file context.c.
References CTX_data_pointer_get(), PointerRNA::data, PointerRNA_NULL, RNA_struct_is_a(), and PointerRNA::type.
Referenced by connect_hair_exec(), constraint_delete_exec(), constraint_poll(), copy_material_exec(), copy_mtex_exec(), copy_mtex_poll(), copy_particle_dupliob_exec(), disconnect_hair_exec(), dupliob_move_down_exec(), dupliob_move_up_exec(), ED_object_context(), edit_actuator_invoke_properties(), edit_actuator_poll(), edit_constraint_invoke_properties(), edit_constraint_poll_generic(), edit_controller_invoke_properties(), edit_controller_poll(), edit_modifier_invoke_properties(), edit_modifier_poll_generic(), edit_sensor_invoke_properties(), edit_sensor_poll(), envmap_clear_exec(), envmap_clear_poll(), envmap_save_exec(), envmap_save_poll(), group_remove_exec(), image_open_exec(), image_open_invoke(), new_material_exec(), new_particle_settings_exec(), new_particle_target_exec(), new_texture_exec(), new_world_exec(), object_hook_assign_exec(), object_hook_recenter_exec(), object_hook_reset_exec(), object_hook_select_exec(), paste_material_exec(), paste_mtex_exec(), psys_poll(), ptcache_add_new_exec(), ptcache_bake_exec(), ptcache_bake_from_cache_exec(), ptcache_free_bake_exec(), ptcache_poll(), ptcache_remove_exec(), remove_particle_dupliob_exec(), remove_particle_target_exec(), rule_add_exec(), rule_del_exec(), rule_move_down_exec(), rule_move_up_exec(), state_add_exec(), state_del_exec(), state_move_down_exec(), state_move_up_exec(), target_move_down_exec(), target_move_up_exec(), and texture_slot_move().
void CTX_data_pointer_set (bContextDataResult * result, ID * id, StructRNA * type, void * data)
Definition at line 695 of file context.c.
References bContextDataResult::ptr, and RNA_pointer_create().
Referenced by BPY_context_member_get(), buttons_context(), ed_screen_context(), node_context(), set_pointer_type(), and view3d_context().
static int ctx_data_pointer_verify (const bContext * C, const char * member, void ** pointer) [static]
Definition at line 535 of file context.c.
References ctx_data_get(), PointerRNA::data, NULL, and bContextDataResult::ptr.
Referenced by CTX_data_main(), and CTX_data_scene().
Scene* CTX_data_scene (const bContext * C) [read]
Definition at line 765 of file context.c.
References ctx_data_pointer_verify(), bContext::data, and bContext::scene.
Referenced by achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), action_main_area_draw(), add_default_keyingset_exec(), add_empty_ks_path_exec(), add_keyingset_button_exec(), add_named_exec(), addMatrixSpace(), ANIM_animdata_get_context(), ANIM_apply_keyingset(), ANIM_draw_cfra(), ANIM_draw_previewrange(), ANIM_keying_sets_enum_itemf(), animedit_poll_channels_nla_tweakmode_off(), append_named_part_ex(), apply_armature_pose2bones_exec(), apply_objects_internal(), applyTransformOrientation(), area_dupli_invoke(), armature_bone_primitive_add_exec(), armature_calc_roll_exec(), armature_click_extrude_exec(), armature_click_extrude_invoke(), armature_fill_bones_exec(), armatureSelectedToGraph(), average_islands_scale_exec(), bake_image_exec(), bc_set_parent(), BDR_drawSketch(), BIF_clearTransformOrientation(), BIF_countTransformOrientation(), BIF_draw_manipulator(), BIF_enumTransformOrientation(), BIF_makeListTemplates(), BIF_menustringTransformOrientation(), BIF_ReebGraphMultiFromEditMesh(), BIF_removeTransformOrientation(), BIF_removeTransformOrientationIndex(), BIF_retargetArc(), BIF_selectTransformOrientation(), border_select_exec(), brush_add_exec(), brush_curve_preset_exec(), brush_curve_preset_poll(), brush_drawcursor(), brush_edit_init(), brush_reset_exec(), brush_scale_size_exec(), brush_uv_sculpt_tool_set_exec(), buttons_context_path(), buttons_texture_context_compute(), buttons_texture_users_from_context(), calc_manipulator_stats(), center_current_frame_exec(), change_character_exec(), change_frame_apply(), change_spacing_exec(), childof_set_inverse_exec(), circle_select_exec(), clip_main_area_draw(), clip_preview_area_draw(), clip_rebuild_proxy_exec(), clip_refresh(), connect_hair_exec(), constraint_add_exec(), convert_exec(), convert_poll(), create_orientation_exec(), createRepresentation(), createVertsTrisData(), CTX_data_tool_settings(), cube_project_exec(), cut_text_exec(), cylinder_project_exec(), delete_exec(), delete_key_button_exec(), delete_key_exec(), delete_key_v3d_exec(), delete_orientation_exec(), dependency_relations_exec(), disconnect_hair_exec(), do_constraint_panels(), do_graph_region_driver_buttons(), do_node_add(), do_node_add_group(), do_node_add_static(), do_set_scale(), do_uvedit_vertex(), do_view3d_region_buttons(), do_view3d_vgroup_buttons(), draw_gpencil_2dimage(), draw_gpencil_view2d(), draw_markers_time(), draw_outliner(), draw_seq_strips(), draw_timeline_seq(), drawnodespace(), drop_named_image_invoke(), duplicate_exec(), dynamicPaint_bakeImageSequence(), ED_base_object_activate(), ED_context_get_markers(), ED_editors_init(), ed_marker_add(), ed_marker_make_links_scene_exec(), ed_marker_move_modal(), ed_marker_select(), ED_object_add_generic_get_opts(), ED_object_add_type(), ED_object_base_init_transform(), ED_object_enter_editmode(), ED_object_exit_editmode(), ED_object_location_from_view(), ED_object_parent_clear(), ED_operator_objectmode(), ED_operator_scene_editable(), ED_preview_draw(), ED_preview_icon_job(), ED_preview_shader_job(), ED_refresh_viewport_fps(), ED_screen_animation_play(), ED_screen_animation_timer(), ED_undo_operator_repeat(), ED_undo_push(), ed_undo_step(), ED_undo_valid(), edbm_extrude_region_exec(), edbm_mark_seam(), edbm_merge_exec(), edbm_screw_invoke(), EDBM_selectmode_to_scene(), edbm_separate_exec(), edbm_sort_faces_exec(), edbm_spin_invoke(), effector_add_type(), envmap_save_exec(), eyedropper_sample(), facesel_face_pick(), DocumentImporter::finish(), fmod_envelope_addpoint_cb(), frame_from_event(), frame_jump_exec(), frame_offset_exec(), game_engine_exec(), get_new_constraint_target(), get_orientation_object(), get_selected_and_linked_obs(), getTransformOrientation(), gp_actframe_delete_exec(), gp_camera_view_subrect(), gp_convert_layer_exec(), gp_convert_poll(), gp_layer_to_curve(), gp_session_initdata(), gp_strokepoint_convertcoords(), gpencil_data_get_pointers(), graph_main_area_draw(), graph_new(), graph_panel_view(), graphview_cursor_apply(), group_add_exec(), group_create_exec(), group_instance_add_exec(), group_link_exec(), group_objects_remove_exec(), group_remove_exec(), handle_view3d_lock(), hide_exec(), hide_show_exec(), image_main_area_draw(), image_new_exec(), image_open_exec(), image_paint_brush(), image_record_composite_apply(), image_record_composite_exit(), image_record_composite_init(), image_refresh(), image_sample_line_exec(), image_save_as_exec(), image_save_as_invoke(), image_save_exec(), image_scope_area_draw(), image_view_selected_exec(), init_bake_internal(), init_multiresbake_job(), init_preview_region(), initFlyInfo(), initTransInfo(), insert_key_button_exec(), insert_key_exec(), insert_key_menu_invoke(), insert_text_exec(), insert_text_invoke(), join_armature_exec(), join_curve_exec(), join_exec(), join_mesh_exec(), join_mesh_shapes_exec(), join_shapes_exec(), keyframe_jump_exec(), keyingset_active_menu_exec(), keyingset_poll_active_edit(), keyingset_poll_activePath_edit(), keyingset_poll_default_add(), knifetool_init(), library_append_end(), line_break_exec(), SkinInfo::link_armature(), list_item_row(), localview_exec(), make_links_data_exec(), make_links_scene_exec(), make_proxy_exec(), make_proxy_invoke(), make_single_user_exec(), mark_seam_exec(), mesh_sticky_add_exec(), mesh_vertex_color_add_exec(), meshdeform_bind_exec(), minimize_stretch_init(), mirror_exec(), modifier_add_exec(), modifier_apply_exec(), modifier_convert_exec(), modifier_remove_exec(), modifiers_setOnCage(), modify_key_op_poll(), mouse_select(), move_cursor(), move_to_layer_exec(), multires_reshape_exec(), multiresbake_check(), multiresbake_image_exec(), multiresbake_image_exec_locked(), namebutton_cb(), navmesh_create_exec(), new_material_exec(), new_node_tree_exec(), new_particle_settings_exec(), new_particle_target_exec(), new_world_exec(), nla_main_area_draw(), nla_new(), nlaop_poll_tweakmode_off(), nlaop_poll_tweakmode_on(), node_add_file_exec(), node_add_menu(), node_area_refresh(), node_composit_buts_image(), node_header_area_draw(), node_link_viewer(), node_menu_add(), node_output_file_add_socket_exec(), node_read_fullsamplelayers_exec(), node_read_renderlayers_exec(), node_render_changed_exec(), object_add_generic_invoke_options(), object_add_hook_newob_exec(), object_add_hook_selob_exec(), object_armature_add_exec(), object_calculate_paths_exec(), object_camera_add_exec(), object_clear_transform_generic_exec(), object_constraint_copy_exec(), object_constraints_clear_exec(), object_delete_exec(), object_duplicates_make_real_exec(), object_hide_view_clear_exec(), object_hide_view_set_exec(), object_hook_assign_exec(), object_hook_recenter_exec(), object_lamp_add_exec(), object_origin_set_exec(), object_select_all_exec(), object_select_by_layer_exec(), object_select_by_type_exec(), object_select_grouped_exec(), object_select_linked_exec(), object_select_menu_exec(), object_select_mirror_exec(), object_select_random_exec(), object_select_same_group_exec(), object_slow_parent_clear_exec(), object_slow_parent_set_exec(), object_speaker_add_exec(), object_track_clear_exec(), objects_add_active_exec(), objects_bake_render_invoke(), objects_bake_render_modal(), objects_remove_active_exec(), objectsolver_set_inverse_exec(), ocean_bake_exec(), old_sca_move_actuator(), old_sca_move_controller(), old_sca_move_sensor(), outliner_animdata_operation_exec(), outliner_border_select_exec(), outliner_group_operation_exec(), outliner_id_operation_exec(), outliner_item_activate(), outliner_keyingset_additems_exec(), outliner_keyingset_removeitems_exec(), outliner_object_operation_exec(), outliner_operation(), outliner_show_active_exec(), outliner_show_hierarchy_exec(), outliner_toggle_renderability_exec(), outliner_toggle_selectability_exec(), outliner_toggle_selected_exec(), outliner_toggle_visibility_exec(), output_toggle_exec(), pack_islands_exec(), paint_apply_event(), paint_brush_stroke_add_step(), paint_cursor_start(), paint_draw_cursor(), paint_draw_smooth_stroke(), paint_exit(), paint_poll(), paint_space_stroke(), paint_stroke_new(), parent_clear_invoke(), parent_drop_exec(), parent_drop_invoke(), parent_noinv_set_exec(), parent_set_exec(), particle_edit_toggle_exec(), particle_edit_toggle_poll(), particle_system_add_exec(), particle_system_remove_exec(), paste_file(), paste_text_exec(), PE_border_select(), PE_circle_select(), PE_hair_poll(), PE_lasso_select(), PE_mouse_particles(), PE_poll(), pe_select_all_exec(), PE_set_data(), peelObjectsContext(), pin_exec(), pose_calculate_paths_exec(), pose_clear_transform_generic_exec(), pose_clear_user_transforms_exec(), pose_constraint_copy_exec(), pose_constraints_clear_exec(), pose_de_select_all_exec(), pose_flip_quats_exec(), pose_paste_exec(), pose_propagate_exec(), pose_select_same_keyingset(), pose_slide_init(), poselib_add_menu_invoke(), poselib_preview_init_data(), previewrange_clear_exec(), previewrange_define_exec(), project_state_init(), ptcache_add_new_exec(), ptcache_bake_all_exec(), ptcache_bake_all_poll(), ptcache_bake_exec(), ptcache_free_bake_all_exec(), ptcache_remove_exec(), pyrna_struct_keyframe_parse(), redraw_timer_exec(), remove_active_keyingset_exec(), remove_active_ks_path_exec(), remove_doubles_exec(), remove_keyingset_button_exec(), remove_particle_target_exec(), render_animation(), render_border_exec(), render_frame(), render_layer_add_exec(), render_layer_remove_exec(), render_view_open(), repositionBone(), reset_exec(), reveal_exec(), RIG_graphFromArmature(), ringsel_finish(), RNA_property_update(), rna_undo_itemf(), rule_del_exec(), sample_color_exec(), sample_draw(), save_image_doit(), scene_delete_exec(), scene_new_exec(), screen_animation_cancel_exec(), screen_animation_step(), screen_opengl_render_exec(), screen_opengl_render_init(), screen_render_exec(), screen_render_invoke(), screen_render_modal(), screencast_exec(), sculpt_brush_stroke_init(), sculpt_get_brush_geometry(), sculpt_stroke_modifiers_check(), sculpt_toggle_mode(), sculpt_undo_restore(), sculpt_undo_restore_coords(), sculpt_update_cache_variants(), select_all_exec(), select_grouped_keyingset(), select_grouped_object_hooks(), select_grouped_parent(), select_linked_internal(), select_pinned_exec(), separate_armature_exec(), separate_exec(), seq_proxy_build_job(), sequencer_add_duplicate_exec(), sequencer_add_effect_strip_exec(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip(), sequencer_add_image_strip_exec(), sequencer_add_movie_strip(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_borderselect_exec(), sequencer_change_effect_input_exec(), sequencer_change_effect_type_exec(), sequencer_change_path_exec(), sequencer_change_path_invoke(), sequencer_copy_exec(), sequencer_cut_exec(), sequencer_cut_invoke(), sequencer_de_select_all_exec(), sequencer_delete_exec(), sequencer_edit_poll(), sequencer_effect_poll(), sequencer_generic_invoke_path__internal(), sequencer_lock_exec(), sequencer_meta_make_exec(), sequencer_meta_separate_exec(), sequencer_meta_toggle_exec(), sequencer_mute_exec(), sequencer_new(), sequencer_next_edit_exec(), sequencer_offset_clear_exec(), sequencer_paste_exec(), sequencer_preview_area_draw(), sequencer_previous_edit_exec(), sequencer_reassign_inputs_exec(), sequencer_refresh_all_exec(), sequencer_reload_exec(), sequencer_rendersize_exec(), sequencer_select_active_side_exec(), sequencer_select_grouped_exec(), sequencer_select_handles_exec(), sequencer_select_inverse_exec(), sequencer_select_invoke(), sequencer_select_less_exec(), sequencer_select_linked_exec(), sequencer_select_linked_pick_invoke(), sequencer_select_more_exec(), sequencer_separate_images_exec(), sequencer_snap_exec(), sequencer_snap_invoke(), sequencer_strip_has_path_poll(), sequencer_swap_data_exec(), sequencer_swap_exec(), sequencer_swap_inputs_exec(), sequencer_unlock_exec(), sequencer_unmute_exec(), sequencer_view_all_preview_exec(), sequencer_view_poll(), sequencer_view_selected_exec(), sequencer_view_zoom_ratio_exec(), set_3dcursor_invoke(), set_axis_exec(), set_case(), set_clone_cursor_exec(), set_clone_cursor_invoke(), set_end_frame(), set_engine(), set_extension(), set_frames_cb(), set_image_type(), set_orientation_poll(), set_origin_exec(), set_output(), set_plane_exec(), set_skip_frame(), set_start_frame(), set_vpaint(), set_wpaint(), setup_app_data(), shape_key_add_exec(), snap_curs_to_active(), snap_curs_to_center(), snap_curs_to_grid(), snap_curs_to_sel(), snap_cursor_exec(), snap_sel_to_curs(), snap_sel_to_grid(), snap_selection_exec(), snapObjectsContext(), snode_composite_job(), solve_camera_initjob(), sound_bake_animation_exec(), sound_mixdown_exec(), sound_pack_exec(), sound_poll(), sound_unpack_invoke(), sound_update_animation_flags_exec(), space_image_image_sample_poll(), space_image_main_area_not_uv_brush_poll(), sphere_project_exec(), spin_invoke(), StartKetsjiShell(), state_del_exec(), stitch_exec(), stitch_exit(), stitch_init(), stitch_modal(), surface_slot_add_exec(), template_id_cb(), test_bake_internal(), texture_paint_camera_project_exec(), texture_paint_image_from_view_exec(), texture_paint_init(), texture_paint_toggle_exec(), texture_slot_move(), time_draw_keyframes(), time_main_area_draw(), time_new(), time_set_efra_exec(), time_set_sfra_exec(), time_view_all_exec(), toggle_paint_cursor(), toggle_particle_cursor(), track_markers_exec(), track_markers_initjob(), track_set_exec(), txt_add_object(), type_toggle_exec(), ui_apply_autokey_undo(), ui_get_but_scale_unit(), ui_node_link(), ui_template_node_link_menu(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), uiBeginBlock(), uiContextAnimUpdate(), uiEndBlock(), uiTemplateHeader3D(), uiTemplateImage(), uiTemplateImageLayers(), uiTemplateModifier(), undo_history_exec(), unlink_selection_exec(), unwrap_exec(), uv_from_view_exec(), uv_map_transform(), uv_sculpt_brush(), uv_sculpt_brush_poll(), uv_sculpt_stroke_apply(), uv_sculpt_stroke_init(), uvedit_vertex_buttons(), vertex_color_set_exec(), vertex_group_copy_to_linked_exec(), vertex_group_fix_exec(), vertex_parent_set_exec(), view3d_all_exec(), view3d_camera_to_view_selected_exec(), view3d_center_camera_exec(), view3d_circle_select_exec(), view3d_context(), view3d_layers_exec(), view3d_main_area_draw_engine(), view3d_main_area_draw_info(), view3d_main_area_draw_objects(), view3d_new(), view3d_panel_object(), view3d_panel_vgroup(), view3d_panel_vgroup_poll(), view3d_set_viewcontext(), view3d_setobjectascamera_exec(), view3d_zoom_1_to_1_camera_exec(), view3d_zoom_border_exec(), view_all_exec(), view_ghost_border_exec(), viewcenter_cursor_exec(), viewnumpad_exec(), viewops_data_create(), viewops_data_free(), viewRedrawPost(), viewselected_exec(), visual_transform_apply_exec(), vpaint_stroke_update_step(), weight_from_bones_exec(), weight_paint_set_exec(), weight_set_exec(), weld_align_uv(), wm_event_do_notifiers(), WM_init_game(), wm_link_append_exec(), WM_operator_check_ui_enabled(), WM_read_file(), WM_window_open_temp(), WM_write_file(), wpaint_stroke_test_start(), wpaint_stroke_update_step(), and DocumentImporter::writeLibraryNodes().
void CTX_data_scene_set (bContext * C, Scene * scene)
Definition at line 838 of file context.c.
References bContext::data, and bContext::scene.
Referenced by ED_render_scene_update(), ED_screen_set_scene(), set_scene(), setup_app_data(), and wm_event_do_handlers().
int CTX_data_selectable_bases (const bContext * C, ListBase * list)
Definition at line 893 of file context.c.
References ctx_data_collection_get().
int CTX_data_selectable_objects (const bContext * C, ListBase * list)
Definition at line 888 of file context.c.
References ctx_data_collection_get().
int CTX_data_selected_bases (const bContext * C, ListBase * list)
Definition at line 873 of file context.c.
References ctx_data_collection_get().
int CTX_data_selected_bones (const bContext * C, ListBase * list)
Definition at line 933 of file context.c.
References ctx_data_collection_get().
int CTX_data_selected_editable_bases (const bContext * C, ListBase * list)
Definition at line 863 of file context.c.
References ctx_data_collection_get().
int CTX_data_selected_editable_bones (const bContext * C, ListBase * list)
Definition at line 938 of file context.c.
References ctx_data_collection_get().
int CTX_data_selected_editable_objects (const bContext * C, ListBase * list)
Definition at line 858 of file context.c.
References ctx_data_collection_get().
int CTX_data_selected_nodes (const bContext * C, ListBase * list)
Definition at line 853 of file context.c.
References ctx_data_collection_get().
int CTX_data_selected_objects (const bContext * C, ListBase * list)
Definition at line 868 of file context.c.
References ctx_data_collection_get().
int CTX_data_selected_pose_bones (const bContext * C, ListBase * list)
Definition at line 958 of file context.c.
References ctx_data_collection_get().
ToolSettings* CTX_data_tool_settings (const bContext * C) [read]
Definition at line 843 of file context.c.
References CTX_data_scene(), NULL, and Scene::toolsettings.
Referenced by BIF_currentTemplate(), BIF_makeListTemplates(), BIF_nameBoneTemplate(), BIF_nbJointsTemplate(), BIF_setTemplate(), BIF_sk_selectStroke(), border_select_exec(), brush_select_exec(), calc_manipulator_stats(), createTransEditVerts(), do_view3d_header_buttons(), ED_object_enter_editmode(), ED_operator_sketch_full_mode(), ED_operator_sketch_mode(), ED_operator_sketch_mode_active_stroke(), ED_operator_sketch_mode_gesture(), ED_operator_uvedit_can_uv_sculpt(), edbm_select_axis_exec(), edbm_select_similar_exec(), editmode_toggle_exec(), hide_exec(), initTransInfo(), mouse_mesh_shortest_path(), mouse_select(), paint_draw_cursor(), reveal_exec(), ringsel_finish(), saveTransform(), sculpt_brush_stroke_cancel(), sculpt_brush_stroke_init(), sculpt_get_brush_geometry(), sculpt_stroke_done(), sculpt_stroke_modifiers_check(), sculpt_stroke_test_start(), sculpt_stroke_update_step(), sculpt_toggle_mode(), sculpt_undo_restore(), sculpt_undo_restore_coords(), select_linked_internal(), sk_addStrokePoint(), sk_autoname(), sk_convert(), sk_convertStroke(), sk_endStroke(), sk_finish_stroke(), sk_getStrokeSnapPoint(), sk_retargetStroke(), snap_type_exec(), uiTemplateHeader3D(), unlink_selection_exec(), uv_faces_do_sticky(), uv_sculpt_stroke_apply(), vertex_group_assign_exec(), vertex_paint_poll(), vpaint_stroke_done(), vpaint_stroke_test_start(), vpaint_stroke_update_step(), weight_paint_poll(), wpaint_stroke_done(), and wpaint_stroke_update_step().
short CTX_data_type_get (bContextDataResult * result)
Definition at line 743 of file context.c.
References bContextDataResult::type.
void CTX_data_type_set (bContextDataResult * result, short type)
Definition at line 738 of file context.c.
References bContextDataResult::type.
Referenced by ed_screen_context(), node_context(), and view3d_context().
int CTX_data_visible_bases (const bContext * C, ListBase * list)
Definition at line 883 of file context.c.
References ctx_data_collection_get().
int CTX_data_visible_bones (const bContext * C, ListBase * list)
Definition at line 943 of file context.c.
References ctx_data_collection_get().
int CTX_data_visible_objects (const bContext * C, ListBase * list)
Definition at line 878 of file context.c.
References ctx_data_collection_get().
int CTX_data_visible_pose_bones (const bContext * C, ListBase * list)
Definition at line 963 of file context.c.
References ctx_data_collection_get().
void CTX_free (bContext * C)
Definition at line 107 of file context.c.
References MEM_freeN().
Referenced by ED_render_scene_update(), and WM_exit_ext().
void* CTX_py_dict_get (const bContext * C)
Definition at line 214 of file context.c.
References bContext::data, and bContext::py_context.
Referenced by BPY_context_member_get(), ctx_data_get(), pyop_call(), and pyop_poll().
void CTX_py_dict_set (bContext * C, void * value)
Definition at line 218 of file context.c.
References bContext::data, and bContext::py_context.
Referenced by pyop_call(), and pyop_poll().
int CTX_py_init_get (bContext * C)
Definition at line 205 of file context.c.
References bContext::data, and bContext::py_init.
Referenced by WM_keymap_init(), and WM_read_homefile().
void CTX_py_init_set (bContext * C, int value)
Definition at line 209 of file context.c.
References bContext::data, and bContext::py_init.
Referenced by main().
bContextStore* CTX_store_add (ListBase * contexts, const char * name, PointerRNA * ptr)
Definition at line 114 of file context.c.
References BLI_addtail(), BLI_duplicatelist(), BLI_strncpy(), bContextStore::entries, ListBase::last, MEM_callocN(), MEM_dupallocN(), bContextStoreEntry::name, bContextStoreEntry::ptr, and bContextStore::used.
Referenced by uiLayoutSetContextPointer().
bContextStore* CTX_store_add_all (ListBase * contexts, bContextStore * context)
Definition at line 144 of file context.c.
References BLI_addtail(), BLI_duplicatelist(), bContextStore::entries, ListBase::first, ListBase::last, MEM_callocN(), MEM_dupallocN(), bContextStoreEntry::next, and bContextStore::used.
Referenced by uiLayoutContextCopy().
bContextStore* CTX_store_copy (bContextStore * store)
Definition at line 178 of file context.c.
References BLI_duplicatelist(), bContextStore::entries, and MEM_dupallocN().
Referenced by ui_apply_but_func().
void CTX_store_free (bContextStore * store)
Definition at line 188 of file context.c.
References BLI_freelistN(), bContextStore::entries, and MEM_freeN().
Referenced by CTX_store_free_list(), and ui_apply_but_funcs_after().
void CTX_store_free_list (ListBase * contexts)
Definition at line 194 of file context.c.
References BLI_remlink(), CTX_store_free(), and ListBase::first.
Referenced by uiFreeBlock().
void CTX_store_set (bContext * C, bContextStore * store)
Definition at line 173 of file context.c.
References bContext::store, and bContext::wm.
Referenced by ui_apply_but_funcs_after(), and uiEndBlock().
ScrArea* CTX_wm_area (const bContext * C) [read]
Definition at line 240 of file context.c.
References bContext::area, and bContext::wm.
Referenced by action_new(), actionzone_area_poll(), actionzone_invoke(), actkeys_viewall(), ANIM_animdata_get_context(), animchannels_enable_poll(), animedit_poll_channels_active(), animedit_poll_channels_nla_tweakmode_off(), area_dupli_invoke(), area_join_apply(), area_split_cancel(), area_split_init(), area_split_invoke(), area_split_menu_init(), BIF_do_manipulator(), BIF_draw_manipulator(), BIF_sk_selectStroke(), bookmark_add_exec(), bookmark_delete_exec(), borderselect_exec(), calc_manipulator_stats(), change_frame_poll(), clip_rebuild_proxy_exec(), console_clear_exec(), console_delete_exec(), console_history_append_exec(), console_history_cycle_exec(), console_insert_exec(), console_modal_select_apply(), console_move_exec(), console_paste_exec(), console_scrollback_append_exec(), do_buttons_buttons(), do_node_add(), do_running_jobs(), do_view3d_header_buttons(), do_view3d_region_buttons(), draw_gpencil_2dimage(), draw_gpencil_view2d(), ED_area_exit(), ED_area_header_standardbuttons(), ED_area_header_switchbutton(), ED_context_get_markers(), ed_marker_move_exit(), ed_marker_move_modal(), ed_markers_opwrap_invoke_custom(), ED_object_enter_editmode(), ED_operator_areaactive(), ed_operator_outliner_datablocks_active(), ED_preview_draw(), ED_region_do_draw(), ED_region_panels(), ED_region_set(), ED_region_toggle_hidden(), ED_screen_area_active(), ED_undo_operator_repeat(), ed_undo_step(), ED_undo_valid(), ED_view3d_context_activate(), ED_view3d_context_rv3d(), ED_view3d_context_user_region(), edbm_vertex_slide_modal(), file_bookmark_toggle_exec(), file_draw_buttons(), file_draw_check_cb(), file_filenum_exec(), file_highlight_invoke(), file_rename_exec(), file_select_all_exec(), file_smoothscroll_invoke(), game_engine_exec(), game_engine_poll(), get_driver_path_hack(), get_poselib_object(), gp_convert_poll(), gp_session_initdata(), gpencil_data_get_pointers(), gpencil_stroke_begin(), graph_properties(), graphkeys_clear_ghostcurves_exec(), graphkeys_create_ghostcurves_exec(), graphkeys_viewall(), graphop_active_fcurve_poll(), graphop_editable_keyframes_poll(), graphop_selected_fcurve_poll(), graphop_visible_keyframes_poll(), handle_view3d_lock(), header_flip_exec(), header_toolbox_invoke(), image_properties(), image_record_composite_apply(), image_sample_apply(), image_sample_exit(), image_sample_line_exec(), image_scopes(), initTransInfo(), knife_update_header(), knifetool_modal(), localview_exec(), logic_properties(), loopcut_modal(), minimize_stretch_exit(), minimize_stretch_iteration(), modify_key_op_poll(), nla_new(), nla_properties(), nlaedit_viewall(), node_properties(), node_properties_poll(), node_view_all_exec(), object_hide_view_clear_exec(), paint_poll(), PE_poll_view3d(), peelObjectsContext(), pin_cb(), pose_calculate_paths_exec(), pose_clear_paths_exec(), pose_group_add_exec(), pose_group_assign_exec(), pose_group_deselect_exec(), pose_group_remove_exec(), pose_group_select_exec(), pose_group_unassign_exec(), pose_groups_menu_invoke(), pose_slide_init(), poselib_preview_init_data(), previewrange_clear_exec(), properties_exec(), redraw_timer_exec(), region_event_inside(), region_flip_exec(), region_quadview_exec(), render_view_cancel_exec(), render_view_open(), report_delete_exec(), report_replay_exec(), report_select_all_toggle_exec(), reset_exec(), ringcut_invoke(), sample_apply(), sample_exit(), screen_full_area_exec(), screen_opengl_render_init(), screen_set_exec(), screencast_exec(), screenshot_data_create(), scroller_activate_apply(), select_report_pick_exec(), seq_proxy_build_job(), sequencer_preview_area_draw(), sequencer_properties(), sequencer_view_all_exec(), sequencer_view_all_preview_exec(), sequencer_view_selected_exec(), sequencer_view_toggle_exec(), set_clone_cursor_exec(), sk_getIntersections(), sk_interpolateDepth(), sketch_cancel(), sketch_convert(), sketch_draw_modal(), sketch_draw_preview(), sketch_finish(), sketch_select(), smooth_view(), snapObjectsContext(), solve_camera_invoke(), solve_camera_modal(), spacefunc(), stitch_exit(), stitch_update_header(), template_texture_show(), text_properties_exec(), text_scroll_apply(), text_scroll_exec(), text_scroll_modal(), text_update_cursor_moved(), tools_exec(), track_markers_invoke(), track_markers_modal(), ui_block_func_POPUP(), ui_do_animate(), ui_do_drag(), ui_handle_menu_event(), ui_handle_panel_header(), ui_handler_panel(), ui_handler_panel_region(), ui_popup_block_create(), UI_view2d_fromcontext(), UI_view2d_fromcontext_rwin(), uiEndPanels(), uiTemplateHeader3D(), uiTemplateRunningJobs(), vertex_paint_poll(), view3d_circle_select_exec(), view3d_layers_exec(), view3d_main_area_draw_objects(), view3d_properties(), view3d_smoothview_invoke(), view3d_toolshelf(), view3d_zoom_border_exec(), view_borderzoom_exec(), view_pan_init(), view_zoomdrag_apply(), view_zoomstep_apply(), viewdolly_exec(), viewops_data_create(), viewpan_exec(), viewzoom_exec(), vtx_slide_exit(), vtx_slide_init(), weight_paint_poll(), wm_dropbox_active(), WM_event_add_fileselect(), WM_event_add_modal_handler(), WM_event_add_ui_handler(), WM_event_remove_handlers(), wm_gesture_end(), wm_handler_fileselect_call(), wm_handler_operator_call(), wm_handler_ui_call(), wm_keymap_item_find_props(), wm_operator_call_internal(), wm_operator_invoke(), wm_operator_reports(), wm_paintcursor_test(), WM_redraw_windows(), and wm_search_menu_poll().
void CTX_wm_area_set (bContext * C, ScrArea * area)
Definition at line 428 of file context.c.
References bContext::area, NULL, bContext::region, and bContext::wm.
Referenced by area_join_apply(), area_split_cancel(), ED_area_exit(), ED_render_scene_update(), ED_screen_full_toggle(), ED_view3d_context_activate(), game_engine_exec(), redraw_timer_exec(), screen_opengl_render_end(), setup_app_data(), ui_handle_menu_event(), wm_event_do_handlers(), wm_event_do_notifiers(), WM_event_remove_handlers(), wm_handler_fileselect_call(), wm_handler_op_context(), wm_handler_operator_call(), wm_handler_ui_call(), WM_init_game(), wm_method_draw_full(), wm_method_draw_overlap_all(), wm_method_draw_triple(), wm_operator_call_internal(), wm_operator_reports(), wm_paintcursor_test(), WM_redraw_windows(), and WM_window_open_temp().
wmWindowManager* CTX_wm_manager (const bContext * C) [read]
Definition at line 225 of file context.c.
References bContext::manager, and bContext::wm.
Referenced by bpy_class_call(), button_activate_init(), button_tooltip_timer_reset(), clip_rebuild_proxy_exec(), clip_refresh(), do_running_jobs(), ED_area_newspace(), ED_area_swapspace(), ED_preview_icon_job(), ED_preview_kill_jobs(), ED_preview_shader_job(), ED_region_toggle_hidden(), ED_screen_animation_timer(), ED_screen_delete(), ED_screen_exit(), ED_screen_set(), ED_screen_set_scene(), ed_undo_exec(), ED_undo_operator_repeat(), ED_undo_push(), ed_undo_step(), editmode_toggle_exec(), file_directory_new_exec(), file_smoothscroll_invoke(), find_area_showing_r_result(), flyEnd(), game_engine_exec(), ghost_event_proc(), image_record_composite_exit(), image_record_composite_invoke(), initFlyInfo(), initTransform(), load_file(), menu_add_shortcut(), menu_change_shortcut(), minimize_stretch_exit(), minimize_stretch_invoke(), multiresbake_image_exec(), objects_bake_render_invoke(), objects_bake_render_modal(), ocean_bake_exec(), paint_cursor_start(), paint_exit(), paint_invoke(), paint_stroke_modal(), panel_activate_state(), postTrans(), radial_control_cancel(), radial_control_invoke(), read_undosave(), render_view_show_invoke(), repeat_history_exec(), repeat_history_invoke(), repeat_last_exec(), screen_opengl_render_end(), screen_opengl_render_init(), screen_opengl_render_invoke(), screen_render_invoke(), screen_render_modal(), screencast_exec(), seq_proxy_build_job(), sequencer_refresh(), smooth_view(), snode_composite_job(), solve_camera_invoke(), solve_camera_modal(), thumbnails_running(), thumbnails_start(), thumbnails_stop(), toggle_paint_cursor(), toggle_particle_cursor(), track_markers_invoke(), track_markers_modal(), ui_handle_menu_event(), ui_popup_block_free(), uiLayoutOperatorButs(), uiTemplateRunningJobs(), update_reports_display_invoke(), uv_sculpt_stroke_exit(), uv_sculpt_stroke_invoke(), view3d_smoothview_invoke(), view_zoomdrag_exit(), view_zoomdrag_invoke(), viewops_data_free(), viewzoom_invoke(), WM_check(), wm_clear_default_size(), wm_close_and_free(), wm_debug_menu_exec(), wm_drags_check_ops(), wm_drags_draw(), wm_draw_update(), WM_event_add_notifier(), wm_event_do_handlers(), wm_event_do_notifiers(), WM_event_fileselect_event(), wm_event_modalkeymap(), WM_event_remove_handlers(), WM_event_start_drag(), WM_exit_ext(), wm_handler_fileselect_call(), wm_handler_operator_call(), wm_handlers_do(), WM_init_game(), WM_init_splash(), WM_keymap_find_all(), WM_keymap_init(), wm_keymap_item_find_handlers(), WM_keymap_restore_item_to_default(), WM_keymap_restore_to_default(), wm_method_draw_overlap_all(), wm_method_draw_triple(), WM_operator_call_py(), WM_operator_check_ui_enabled(), wm_operator_exec(), wm_operator_finished(), wm_operator_invoke(), WM_operator_last_redo(), wm_operator_register(), wm_operator_reports(), wm_paintcursor_draw(), wm_paintcursor_test(), WM_read_file(), wm_window_make_drawable(), wm_window_new(), WM_window_open_temp(), wm_window_timer(), and WM_write_homefile().
void CTX_wm_manager_set (bContext * C, wmWindowManager * wm)
Definition at line 400 of file context.c.
References bContext::area, bContext::manager, NULL, bContext::region, bContext::screen, bContext::window, and bContext::wm.
Referenced by ED_render_scene_update(), load_file(), setup_app_data(), wm_add_default(), WM_check(), wm_clear_default_size(), and wm_close_and_free().
struct ARegion* CTX_wm_menu (const bContext * C) [read]
Definition at line 260 of file context.c.
References bContext::menu, and bContext::wm.
Referenced by ui_handler_region_menu(), uiDrawBlock(), WM_event_add_ui_handler(), WM_event_remove_handlers(), and wm_handler_ui_call().
void CTX_wm_menu_set (bContext * C, ARegion * menu)
Definition at line 439 of file context.c.
References bContext::menu, and bContext::wm.
Referenced by setup_app_data(), WM_event_remove_handlers(), wm_handler_ui_call(), wm_method_draw_full(), wm_method_draw_overlap_all(), and wm_method_draw_triple().
const char* CTX_wm_operator_poll_msg_get (bContext * C)
Definition at line 449 of file context.c.
References bContext::operator_poll_msg, and bContext::wm.
Referenced by pyop_call(), and ui_tooltip_create().
void CTX_wm_operator_poll_msg_set (bContext * C, const char * msg)
Definition at line 444 of file context.c.
References bContext::operator_poll_msg, and bContext::wm.
Referenced by ED_operator_animview_active(), ED_operator_editmesh_region_view3d(), ED_operator_editsurfcurve_region_view3d(), ED_operator_region_view3d_active(), gpencil_draw_poll(), pyop_call(), space_image_file_exists_poll(), ui_tooltip_create(), vertex_group_blend_poll(), view3d_camera_to_view_selected_poll(), wm_operator_call_internal(), and wm_operator_exec().
ARegion* CTX_wm_region (const bContext * C) [read]
Definition at line 250 of file context.c.
References bContext::region, and bContext::wm.
Referenced by ANIM_animdata_get_context(), ANIM_draw_cfra(), animchannels_enable_poll(), animedit_poll_channels_active(), animedit_poll_channels_nla_tweakmode_off(), armature_click_extrude_invoke(), backimage_zoom(), BIF_do_manipulator(), BIF_draw_manipulator(), border_select_exec(), border_select_graph_exec(), borderselect_exec(), brush_edit_apply(), brush_edit_init(), calc_manipulator_stats(), center_current_frame_exec(), change_frame_invoke(), circle_select_exec(), console_clear_exec(), console_delete_exec(), console_history_append_exec(), console_history_cycle_exec(), console_insert_exec(), console_modal_select_apply(), console_move_exec(), console_paste_exec(), console_scrollback_append_exec(), createTransTrackingData(), curvemap_buttons_redraw(), curvemap_buttons_zoom_in(), curvemap_buttons_zoom_out(), curvemap_tools_dofunc(), cut_links_exec(), draw_gpencil_2dimage(), draw_gpencil_view2d(), draw_outliner(), ED_clip_point_stable_pos(), ed_marker_select(), ED_operator_regionactive(), ED_region_exit(), ED_screen_animation_play(), ED_screen_animation_timer(), ED_space_clip_graph_poll(), ED_undo_operator_repeat(), ED_view3d_context_user_region(), edbm_knife_cut_exec(), edbm_rip_invoke__edge(), edbm_rip_invoke__vert(), face_select_all_exec(), face_select_hide_exec(), face_select_inverse_exec(), face_select_reveal_exec(), file_border_select_exec(), file_border_select_modal(), file_highlight_invoke(), file_select_invoke(), file_selection_get(), file_smoothscroll_invoke(), fly_modal(), frame_from_event(), game_engine_exec(), get_imapaint_zoom(), gp_camera_view_subrect(), gp_session_initdata(), gp_strokepoint_convertcoords(), grab_clone_apply(), grab_clone_modal(), graphview_cursor_setprops(), header_flip_exec(), header_toolbox_invoke(), helpline_poll(), hide_show_exec(), image_paint_poll(), image_sample_apply(), image_sample_invoke(), image_sample_line_exec(), image_view_all_exec(), image_view_ndof_invoke(), image_view_pan_exec(), image_view_pan_exit(), image_view_selected_exec(), image_view_zoom_exec(), image_view_zoom_exit(), image_view_zoom_in_exec(), image_view_zoom_in_invoke(), image_view_zoom_init(), image_view_zoom_invoke(), image_view_zoom_modal(), image_view_zoom_out_exec(), image_view_zoom_out_invoke(), image_view_zoom_ratio_exec(), initFlyInfo(), initTransInfo(), item_rename_cb(), keymap_type_cb(), knifetool_init(), mouse_select(), mouse_select_knot(), ndof_orbit_invoke(), ndof_pan_invoke(), node_add_file_invoke(), node_border_select_invoke(), node_borderselect_exec(), node_link_invoke(), node_link_modal(), node_resize_invoke(), node_resize_modal(), node_select_exec(), node_uiblocks_init(), node_view_all_exec(), outliner_border_select_exec(), outliner_item_activate(), outliner_item_openclose(), outliner_item_rename(), outliner_one_level_exec(), outliner_operation(), outliner_parent_clear_poll(), outliner_parent_drop_poll(), outliner_scroll_page_exec(), outliner_show_active_exec(), outliner_show_hierarchy_exec(), outliner_toggle_expanded_exec(), outliner_toggle_selectability_exec(), outliner_toggle_selected_exec(), outliner_toggle_visibility_exec(), paint_draw_smooth_stroke(), paint_poll(), paint_redraw(), paint_select_linked_exec(), paint_select_linked_pick_invoke(), paintface_mouse_select(), panel_activate_state(), parent_drop_invoke(), PE_lasso_select(), PE_poll_view3d(), peelObjectsContext(), pose_slide_init(), previewrange_define_exec(), project_state_init(), radial_control_modal(), radial_control_paint_cursor(), redraw_timer_exec(), region_flip_exec(), region_quadview_exec(), renamebutton_cb(), render_border_exec(), reset_exec(), ringsel_init(), run_pyfile_exec(), sample_apply(), sample_color_exec(), sample_invoke(), sclip_zoom_set_factor_exec(), screen_opengl_render_init(), scroller_activate_exit(), scroller_activate_init(), scroller_activate_invoke(), sculpt_flush_update(), select_invoke(), select_linked_internal(), select_loop_invoke(), select_report_pick_invoke(), sequencer_view_all_preview_exec(), sequencer_view_zoom_ratio_exec(), set_2d_cursor_invoke(), set_3dcursor_invoke(), set_clone_cursor_invoke(), set_tile_invoke(), sk_addStrokeDrawPoint(), sk_addStrokeSnapPoint(), sk_detectMergeGesture(), sk_distanceDepth(), sk_getIntersections(), sk_getSelfIntersections(), sk_interpolateDepth(), sk_projectDrawPoint(), sk_snapPointStroke(), snapObjectsContext(), snode_bg_viewmove_invoke(), snode_bg_viewmove_modal(), stitch_modal(), stitch_select(), text_cursor_set_apply(), text_cursor_set_exec(), text_line_number_invoke(), text_move_cursor(), text_region_edit_poll(), text_region_scroll_poll(), text_scroll_apply(), text_scroll_bar_invoke(), text_scroll_exec(), text_scroll_modal(), texture_paint_image_from_view_exec(), texture_paint_init(), time_view_all_exec(), ui_apply_but_LINK(), ui_block_func_POPUP(), UI_but_active_drop_name(), ui_context_button_active(), ui_do_animate(), ui_do_button(), ui_do_drag(), ui_handle_menu_event(), ui_handle_panel_header(), ui_handler_panel(), ui_handler_panel_region(), ui_handler_region(), ui_handler_region_menu(), ui_handler_remove_region(), ui_popup_block_create(), UI_view2d_fromcontext(), UI_view2d_fromcontext_rwin(), UI_view2d_mouse_in_scrollers(), UI_view2d_view_restore(), uiButActiveOnly(), uiContextActiveOperator(), uiContextAnimUpdate(), uiDrawBlock(), uiFileBrowseContextProperty(), uiIDContextProperty(), uv_from_view_exec(), uv_sculpt_brush_poll(), uv_sculpt_stroke_apply(), uv_sculpt_stroke_init(), uv_sculpt_stroke_modal(), vert_select_all_exec(), vert_select_inverse_exec(), vertex_color_set_exec(), vertex_paint_poll(), view2d_poll(), view3d_all_exec(), view3d_circle_select_exec(), view3d_clipping_invoke(), view3d_operator_needs_opengl(), view3d_set_viewcontext(), view3d_smoothview_invoke(), view3d_zoom_border_exec(), view_all_exec(), view_borderzoom_exec(), view_pan_exec(), view_pan_exit(), view_pan_init(), view_scrolldown_exec(), view_scrollup_exec(), view_selected_exec(), view_zoom_exec(), view_zoom_exit(), view_zoom_in_exec(), view_zoom_modal(), view_zoom_out_exec(), view_zoom_poll(), view_zoom_ratio_exec(), view_zoomdrag_init(), view_zoomdrag_invoke(), view_zoomin_invoke(), view_zoomout_invoke(), view_zoomstep_apply(), viewcenter_cursor_exec(), viewdolly_exec(), viewops_data_create(), viewops_data_free(), viewpan_exec(), viewselected_exec(), viewzoom_exec(), vtx_slide_init(), weight_paint_poll(), weight_paint_set_exec(), wm_dropbox_active(), WM_event_add_fileselect(), WM_event_add_modal_handler(), WM_event_add_notifier(), WM_event_add_ui_handler(), WM_event_remove_handlers(), WM_gesture_new(), wm_gesture_tag_redraw(), wm_handler_fileselect_call(), wm_handler_operator_call(), wm_handler_ui_call(), wm_handler_ui_cancel(), wm_keymap_item_find_props(), wm_macro_modal(), wm_operator_call_internal(), wm_operator_invoke(), wm_operator_reports(), wm_paintcursor_draw(), wm_paintcursor_test(), WM_redraw_windows(), wm_region_mouse_co(), wm_tweakevent_test(), and wpaint_stroke_update_step().
void* CTX_wm_region_data (const bContext * C)
Definition at line 255 of file context.c.
References NULL, bContext::region, ARegion::regiondata, and bContext::wm.
Referenced by snap_curs_to_grid(), and snap_sel_to_grid().
void CTX_wm_region_set (bContext * C, ARegion * region)
Definition at line 434 of file context.c.
References bContext::region, and bContext::wm.
Referenced by area_join_apply(), area_split_cancel(), ED_region_exit(), ED_render_scene_update(), ED_undo_operator_repeat(), ED_view3d_context_activate(), file_smoothscroll_invoke(), game_engine_exec(), redraw_timer_exec(), screen_opengl_render_end(), setup_app_data(), ui_handle_menu_event(), wm_event_do_handlers(), WM_event_remove_handlers(), wm_handler_fileselect_call(), wm_handler_op_context(), wm_handler_operator_call(), wm_handler_ui_call(), WM_init_game(), wm_method_draw_full(), wm_method_draw_overlap_all(), wm_method_draw_triple(), wm_operator_call_internal(), wm_operator_reports(), wm_paintcursor_test(), and WM_redraw_windows().
RegionView3D* CTX_wm_region_view3d (const bContext * C) [read]
Definition at line 280 of file context.c.
References bContext::area, NULL, bContext::region, ARegion::regiondata, SPACE_VIEW3D, ScrArea::spacetype, and bContext::wm.
Referenced by add_vertex_invoke(), armature_bone_primitive_add_exec(), armature_calc_roll_exec(), createTransData(), drawPropCircle(), drawSnapping(), ED_object_rotation_from_view(), ED_operator_editmesh_region_view3d(), ED_operator_editsurfcurve_region_view3d(), ED_operator_region_view3d_active(), ED_text_to_object(), ED_view3d_context_rv3d(), edbm_extrude_repeat_exec(), edbm_rip_invoke__edge(), edbm_rip_invoke__vert(), fly_invoke(), game_engine_exec(), get_imapaint_zoom(), image_paint_2d_clone_poll(), image_paint_3d_poll(), image_paint_poll(), initFlyInfo(), ndof_orbit_invoke(), ndof_pan_invoke(), object_armature_add_exec(), project_state_init(), sculpt_flush_update(), sculpt_stroke_test_start(), set_3dcursor_invoke(), StartKetsjiShell(), test_manipulator_axis(), texture_paint_image_from_view_exec(), texture_paint_init(), uv_from_view_exec(), uv_from_view_poll(), uv_map_transform(), view3d_all_exec(), view3d_camera_active_poll(), view3d_camera_to_view_exec(), view3d_camera_to_view_poll(), view3d_camera_to_view_selected_poll(), view3d_clipping_exec(), view3d_clipping_invoke(), view3d_main_area_draw_engine(), view3d_main_area_draw_info(), view3d_main_area_draw_objects(), view3d_set_viewcontext(), view3d_smoothview_invoke(), view3d_zoom_border_exec(), view3d_zoom_border_invoke(), viewcenter_cursor_exec(), viewdolly_poll(), viewpan_exec(), and viewselected_exec().
struct ReportList* CTX_wm_reports (const bContext * C) [read]
Definition at line 265 of file context.c.
References bContext::manager, NULL, wmWindowManager::reports, and bContext::wm.
Referenced by achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), ANIM_apply_keyingset(), autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), borderselect_exec(), BPY_button_exec(), bpy_class_call(), BPY_string_exec(), do_outliner_item_rename(), do_outliner_operation_event(), driver_remove_cb(), ED_armature_enter_posemode(), info_main_area_draw(), info_textview_update_rect(), item_rename_cb(), namebutton_cb(), report_copy_exec(), report_delete_exec(), report_select_all_toggle_exec(), reports_to_text_exec(), reports_to_text_poll(), select_report_pick_exec(), select_report_pick_invoke(), ui_but_anim_autokey(), uiTemplateReportsBanner(), unlink_action_cb(), update_reports_display_invoke(), wm_free_reports(), wm_handler_fileselect_call(), wm_init_reports(), wm_operator_finished(), WM_operator_redo_popup(), and wm_operator_reports().
bScreen* CTX_wm_screen (const bContext * C) [read]
Definition at line 235 of file context.c.
References bContext::screen, and bContext::wm.
Referenced by actionzone_modal(), actkeys_viewall(), area_dupli_invoke(), area_event_inside(), area_join_apply(), area_join_exit(), area_join_init(), area_join_modal(), area_move_apply_do(), area_move_exit(), area_move_init(), area_split_apply(), area_split_cancel(), area_split_exit(), area_split_invoke(), area_split_modal(), area_swap_modal(), biggest_non_image_area(), do_outliner_item_activate(), do_running_jobs(), ED_area_overdraw(), ED_operator_areaactive(), ED_operator_regionactive(), ED_operator_screen_mainwinactive(), ED_operator_screenactive(), ED_operator_screenactive_norender(), ED_refresh_viewport_fps(), ED_screen_animation_play(), ED_screen_animation_timer(), ED_screen_area_active(), ed_screen_context(), ED_screen_delete_scene(), ED_screen_full_newspace(), ED_screen_set(), ED_uvedit_ensure_uvs(), ED_view3d_context_activate(), find_area_image_empty(), frame_jump_exec(), fullscreen_back_exec(), game_engine_poll(), gpencil_area_exists(), gpencil_data_get_pointers(), graph_panel_view(), graphkeys_viewall(), image_panel_curves(), init_bake_internal(), initTransInfo(), nlaedit_viewall(), outliner_do_object_operation(), outliner_object_operation_exec(), redraw_timer_exec(), redraw_timer_window_swap(), region_event_inside(), render_view_open(), reset_exec(), scene_new_exec(), screen_active_editable(), screen_animation_cancel_exec(), screen_animation_step(), screen_area_options_invoke(), screen_delete_exec(), screen_full_area_exec(), screen_new_exec(), screen_render_exec(), screen_render_invoke(), screen_set_exec(), screencast_exec(), scroller_activate_apply(), sequencer_view_all_exec(), sequencer_view_all_preview_exec(), sequencer_view_selected_exec(), setup_app_data(), texture_paint_init(), toolbox_invoke(), track_markers_initjob(), tree_element_active_world(), ui_handler_remove_region(), ui_popup_block_create(), ui_popup_block_free(), ui_searchbox_create(), ui_searchbox_free(), ui_tooltip_create(), ui_tooltip_free(), uiContextActiveOperator(), uiTemplateHeader3D(), uiTemplateRunningJobs(), view3d_main_area_draw_info(), view_borderzoom_exec(), view_pan_init(), view_zoomdrag_apply(), view_zoomstep_apply(), wm_add_default(), WM_event_add_fileselect(), wm_gesture_tag_redraw(), wm_handler_fileselect_call(), wm_handler_op_context(), WM_init_game(), wm_operator_invoke(), wm_window_match_do(), and WM_write_file().
void CTX_wm_screen_set (bContext * C, bScreen * screen)
Definition at line 419 of file context.c.
References bContext::area, bContext::data, NULL, bContext::region, bContext::scene, bScreen::scene, bContext::screen, and bContext::wm.
Referenced by ED_render_scene_update(), load_file(), setup_app_data(), and wm_event_do_handlers().
struct SpaceAction* CTX_wm_space_action (const bContext * C) [read]
Definition at line 372 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_ACTION, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by act_markers_make_local_exec(), act_markers_make_local_poll(), and action_main_area_draw().
struct SpaceButs* CTX_wm_space_buts (const bContext * C) [read]
Definition at line 309 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_BUTS, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by buttons_context(), buttons_context_draw(), buttons_context_id_path(), buttons_context_path(), buttons_header_buttons(), buttons_main_area_draw(), do_buttons_buttons(), pin_cb(), template_texture_select(), template_texture_show(), template_texture_user_menu(), toolbox_invoke(), uiTemplateTextureShow(), and uiTemplateTextureUser().
struct SpaceClip* CTX_wm_space_clip (const bContext * C) [read]
Definition at line 393 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_CLIP, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by add_marker_exec(), border_select_exec(), border_select_graph_exec(), circle_select_exec(), clean_tracks_exec(), clean_tracks_invoke(), clear_solution_exec(), clear_track_path_exec(), clip_context(), clip_draw_grease_pencil(), clip_main_area_draw(), clip_preview_area_draw(), clip_properties_area_draw(), clip_rebuild_proxy_exec(), copy_tracks_exec(), count_selected_bundles(), createTransTrackingCurvesData(), createTransTrackingData(), createTransTrackingTracksData(), delete_curve_exec(), delete_knot_exec(), delete_marker_exec(), delete_track_exec(), detect_features_exec(), disable_markers_exec(), do_set_scale(), ED_clip_point_stable_pos(), ED_space_clip_graph_poll(), ED_space_clip_poll(), frame_jump_exec(), get_orientation_object(), graph_disable_markers_exec(), graph_select_all_markers_exec(), hide_tracks_clear_exec(), hide_tracks_exec(), join_tracks_exec(), lock_tracks_exec(), mode_set_exec(), mouse_select(), mouse_select_curve(), mouse_select_knot(), open_exec(), open_invoke(), paste_tracks_exec(), properties_poll(), sclip_zoom_set_factor_exec(), select_all_exec(), select_groped_exec(), select_invoke(), set_axis_exec(), set_center_principal_exec(), set_orientation_poll(), set_origin_exec(), set_plane_exec(), set_scale_invoke(), set_solution_scale_invoke(), set_solution_scale_poll(), slide_marker_customdata(), slide_marker_invoke(), slide_marker_modal(), solve_camera_initjob(), solve_camera_invoke(), space_clip_frame_poll(), stabilize_2d_add_exec(), stabilize_2d_remove_exec(), stabilize_2d_select_exec(), stabilize_2d_set_rotation_exec(), tools_poll(), track_copy_color_exec(), track_markers_exec(), track_markers_initjob(), track_markers_invoke(), tracking_object_new_exec(), tracking_object_remove_exec(), view_all_exec(), view_pan_exec(), view_pan_init(), view_pan_invoke(), view_pan_modal(), view_selected_exec(), view_zoom_exec(), view_zoom_exit(), view_zoom_in_exec(), view_zoom_init(), view_zoom_modal(), view_zoom_out_exec(), and view_zoom_ratio_exec().
struct SpaceConsole* CTX_wm_space_console (const bContext * C) [read]
Definition at line 295 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_CONSOLE, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by console_clear_exec(), console_copy_exec(), console_delete_exec(), console_history_add(), console_history_append_exec(), console_history_cycle_exec(), console_history_verify(), console_insert_exec(), console_main_area_draw(), console_modal_select_apply(), console_modal_select_invoke(), console_paste_exec(), and console_scrollback_append_exec().
SpaceLink* CTX_wm_space_data (const bContext * C) [read]
Definition at line 245 of file context.c.
References bContext::area, ListBase::first, NULL, ScrArea::spacedata, and bContext::wm.
Referenced by ANIM_animdata_get_context(), draw_image_grease_pencil(), ED_area_prevspace(), ed_marker_move_init(), ED_operator_animview_active(), ed_spacetype_test(), file_rename_exec(), gpencil_data_get_pointers(), renamebutton_cb(), script_main_area_draw(), sequencer_view_toggle_exec(), view3d_panel_tool_shelf(), and WM_keymap_guess_opname().
struct SpaceFile* CTX_wm_space_file (const bContext * C) [read]
Definition at line 316 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_FILE, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by autocomplete_directory(), autocomplete_file(), bookmark_add_exec(), bookmark_select_exec(), ed_screen_context(), file_border_select_exec(), file_border_select_modal(), file_browse_invoke(), file_calc_previews(), file_cancel_exec(), file_change_dir(), file_delete_exec(), file_delete_poll(), file_directory_exec(), file_directory_invoke(), file_directory_new_exec(), file_directory_poll(), file_draw_buttons(), file_draw_check_cb(), file_draw_list(), file_exec(), file_expand_directory(), file_filename_exec(), file_filenum_exec(), file_hidedot_exec(), file_highlight_invoke(), file_main_area_draw(), file_next_exec(), file_operator_poll(), file_panel_bookmarks(), file_panel_category(), file_panel_operator(), file_panel_operator_header(), file_panel_operator_poll(), file_panel_recent(), file_panel_system(), file_parent_exec(), file_previous_exec(), file_refresh(), file_refresh_exec(), file_rename_poll(), file_select(), file_select_all_exec(), file_select_do(), file_select_invoke(), file_selection_get(), and file_smoothscroll_invoke().
struct SpaceIpo* CTX_wm_space_graph (const bContext * C) [read]
Definition at line 365 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_IPO, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by graph_main_area_draw(), graph_panel_drivers_poll(), graph_panel_view(), graphedit_activekey_update_cb(), and graphview_cursor_apply().
struct SpaceImage* CTX_wm_space_image (const bContext * C) [read]
Definition at line 302 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_IMAGE, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by border_select_exec(), circle_select_exec(), createTransUVs(), do_uvedit_vertex(), ED_operator_uvedit(), ED_operator_uvedit_can_uv_sculpt(), get_imapaint_zoom(), hide_exec(), image_context(), image_main_area_draw(), image_new_exec(), image_open_exec(), image_open_invoke(), image_paint_poll(), image_panel_curves(), image_panel_poll(), image_record_composite_apply(), image_record_composite_exit(), image_record_composite_init(), image_refresh(), image_reload_exec(), image_replace_exec(), image_replace_invoke(), image_sample_apply(), image_sample_invoke(), image_sample_line_exec(), image_sample_line_invoke(), image_save_as_exec(), image_save_as_invoke(), image_save_exec(), image_save_sequence_exec(), image_scope_area_draw(), image_view_all_exec(), image_view_ndof_invoke(), image_view_pan_exec(), image_view_pan_exit(), image_view_pan_init(), image_view_pan_invoke(), image_view_pan_modal(), image_view_selected_exec(), image_view_zoom_exec(), image_view_zoom_exit(), image_view_zoom_in_exec(), image_view_zoom_init(), image_view_zoom_invoke(), image_view_zoom_modal(), image_view_zoom_out_exec(), image_view_zoom_ratio_exec(), mouse_select(), reveal_exec(), select_linked_internal(), set_2d_cursor_exec(), set_tile_invoke(), snap_cursor_exec(), snap_selection_exec(), space_image_buffer_exists_poll(), space_image_file_exists_poll(), space_image_image_sample_poll(), space_image_main_area_not_uv_brush_poll(), space_image_main_area_poll(), space_image_poll(), stitch_exit(), texture_paint_init(), ui_id_brush_get_icon(), uv_sculpt_brush_poll(), uv_sculpt_stroke_apply(), uv_sculpt_stroke_init(), uvedit_vertex_buttons(), and weld_align_uv().
struct SpaceInfo* CTX_wm_space_info (const bContext * C) [read]
Definition at line 379 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_INFO, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by borderselect_exec(), info_main_area_draw(), info_textview_update_rect(), report_copy_exec(), report_delete_exec(), report_select_all_toggle_exec(), and select_report_pick_invoke().
struct SpaceLogic* CTX_wm_space_logic (const bContext * C) [read]
Definition at line 358 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_LOGIC, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by do_actuator_menu(), do_controller_menu(), do_sensor_menu(), logic_buttons(), and logic_buttons_new().
struct SpaceNla* CTX_wm_space_nla (const bContext * C) [read]
Definition at line 337 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_NLA, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by nla_main_area_draw().
struct SpaceNode* CTX_wm_space_node (const bContext * C) [read]
Definition at line 351 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_NODE, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by active_node_panel(), active_node_poll(), active_nodetree_poll(), backimage_zoom(), composite_node_active(), cut_links_exec(), detach_links_exec(), do_node_add(), do_node_add_group(), do_node_internal_buttons(), drawnodespace(), ED_operator_node_active(), new_node_tree_exec(), node_active_link_viewer(), node_add_file_exec(), node_add_file_invoke(), node_add_menu(), node_border_select_invoke(), node_borderselect_exec(), node_context(), node_delete_exec(), node_delete_reconnect_exec(), node_duplicate_exec(), node_group_edit_exec(), node_group_edit_invoke(), node_group_make_exec(), node_group_socket_add_exec(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_socket_remove_exec(), node_group_ungroup_exec(), node_header_area_draw(), node_hide_toggle_exec(), node_link_cancel(), node_link_invoke(), node_link_modal(), node_link_viewer(), node_make_link_exec(), node_menu_add(), node_mute_exec(), node_options_toggle_exec(), node_output_file_add_socket_exec(), node_output_file_remove_active_socket_exec(), node_preview_toggle_exec(), node_read_fullsamplelayers_exec(), node_read_renderlayers_exec(), node_resize_invoke(), node_resize_modal(), node_select_all_exec(), node_select_exec(), node_select_linked_from_exec(), node_select_linked_to_exec(), node_select_same_type_exec(), node_select_same_type_next_exec(), node_select_same_type_prev_exec(), node_select_single(), node_show_cycles_exec(), node_socket_button_color(), node_socket_button_components(), node_socket_button_default(), node_socket_toggle_exec(), node_sockets_panel(), node_sockets_poll(), node_view_all_exec(), sample_apply(), sample_invoke(), and snode_bg_viewmove_modal().
struct SpaceOops* CTX_wm_space_outliner (const bContext * C) [read]
Definition at line 330 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_OUTLINER, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by draw_outliner(), ed_operator_outliner_datablocks_active(), modify_key_op_poll(), namebutton_cb(), outliner_action_set_exec(), outliner_animdata_operation_exec(), outliner_border_select_exec(), outliner_data_operation_exec(), outliner_drivers_addsel_exec(), outliner_drivers_deletesel_exec(), outliner_dropzone_parent(), outliner_dropzone_parent_clear(), outliner_group_operation_exec(), outliner_id_operation_exec(), outliner_item_activate(), outliner_item_openclose(), outliner_item_rename(), outliner_keyingset_additems_exec(), outliner_keyingset_removeitems_exec(), outliner_object_operation_exec(), outliner_one_level_exec(), outliner_operation(), outliner_parent_clear_poll(), outliner_parent_drop_poll(), outliner_show_active_exec(), outliner_show_hierarchy_exec(), outliner_toggle_expanded_exec(), outliner_toggle_renderability_exec(), outliner_toggle_selectability_exec(), outliner_toggle_selected_exec(), outliner_toggle_visibility_exec(), and parent_drop_invoke().
struct SpaceSeq* CTX_wm_space_seq (const bContext * C) [read]
Definition at line 323 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_SEQ, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by draw_timeline_seq(), screen_opengl_render_init(), sequencer_select_invoke(), and sequencer_view_poll().
struct SpaceText* CTX_wm_space_text (const bContext * C) [read]
Definition at line 288 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_TEXT, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by ED_text_undo_step(), scroll_exit(), text_comment_exec(), text_context(), text_convert_whitespace_exec(), text_cursor_set_apply(), text_cursor_set_exec(), text_cursor_set_exit(), text_cursor_set_invoke(), text_cut_exec(), text_delete_exec(), text_find_and_replace(), text_find_set_selected_exec(), text_indent_exec(), text_insert_exec(), text_insert_invoke(), text_line_break_exec(), text_line_number_invoke(), text_main_area_draw(), text_move_cursor(), text_new_exec(), text_open_exec(), text_paste_exec(), text_properties_poll(), text_region_edit_poll(), text_region_scroll_poll(), text_reload_exec(), text_replace_set_selected_exec(), text_scroll_apply(), text_scroll_bar_invoke(), text_scroll_exec(), text_scroll_invoke(), text_scroll_modal(), text_set_selection_invoke(), text_space_edit_poll(), text_toggle_overwrite_exec(), text_uncomment_exec(), text_unindent_exec(), text_unlink_exec(), and text_update_cursor_moved().
struct SpaceTime* CTX_wm_space_time (const bContext * C) [read]
Definition at line 344 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_TIME, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by time_main_area_draw().
struct SpaceUserPref* CTX_wm_space_userpref (const bContext * C) [read]
Definition at line 386 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_USERPREF, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
View3D* CTX_wm_view3d (const bContext * C) [read]
Definition at line 273 of file context.c.
References bContext::area, ListBase::first, NULL, SPACE_VIEW3D, ScrArea::spacedata, ScrArea::spacetype, and bContext::wm.
Referenced by add_nurbs_primitive(), append_named_part_ex(), applyTransformOrientation(), armature_bone_primitive_add_exec(), armature_calc_roll_exec(), armature_click_extrude_exec(), armature_click_extrude_invoke(), armature_fill_bones_exec(), background_image_add(), background_image_add_invoke(), background_image_remove_exec(), BDR_drawSketch(), BIF_clearTransformOrientation(), BIF_removeTransformOrientation(), BIF_removeTransformOrientationIndex(), BIF_selectTransformOrientation(), BIF_selectTransformOrientationValue(), create_orientation_exec(), delete_orientation_exec(), delete_orientation_poll(), do_view3d_region_buttons(), draw_gpencil_panel(), drawSnapping(), drop_named_image_invoke(), drop_named_material_invoke(), ED_object_add_generic_get_opts(), ED_object_location_from_view(), ED_object_new_primitive_matrix(), edbm_merge_exec(), edbm_screw_invoke(), edbm_sort_faces_exec(), edbm_spin_invoke(), enable_manipulator_invoke(), game_engine_exec(), getTransformOrientation(), gp_camera_view_subrect(), gp_strokepoint_convertcoords(), handle_view3d_lock(), image_paint_sample_color_poll(), initFlyInfo(), initTransformOrientation(), knifetool_draw(), localview_exec(), make_links_data_exec(), make_single_user_exec(), manipulator_invoke(), mesh_sticky_add_exec(), mouse_select(), move_to_layer_exec(), move_to_layer_invoke(), ndof_orbit_invoke(), ndof_pan_invoke(), new_primitive_matrix(), object_add_generic_invoke_options(), object_armature_add_exec(), object_camera_add_exec(), object_origin_set_exec(), project_state_init(), render_border_exec(), ringsel_draw(), screen_render_exec(), screen_render_invoke(), select_grouped_object_hooks(), select_grouped_parent(), select_orientation_exec(), set_3dcursor_invoke(), set_clone_cursor_exec(), set_clone_cursor_invoke(), snap_curs_to_active(), snap_curs_to_center(), snap_curs_to_grid(), snap_curs_to_sel(), snap_sel_to_curs(), spin_invoke(), StartKetsjiShell(), texture_paint_image_from_view_exec(), ui_id_brush_get_icon(), uv_from_view_exec(), uv_map_transform(), view3d_all_exec(), view3d_camera_to_view_exec(), view3d_camera_to_view_poll(), view3d_camera_to_view_selected_exec(), view3d_camera_to_view_selected_poll(), view3d_center_camera_exec(), view3d_context(), view3d_layers_poll(), view3d_main_area_draw(), view3d_main_area_draw_engine(), view3d_main_area_draw_info(), view3d_main_area_draw_objects(), view3d_panel_object(), view3d_set_viewcontext(), view3d_smoothview_invoke(), view3d_zoom_border_exec(), view3d_zoom_border_invoke(), viewcenter_cursor_exec(), viewdolly_poll(), vieworbit_exec(), viewselected_exec(), and vtx_slide_draw().
wmWindow* CTX_wm_window (const bContext * C) [read]
Definition at line 230 of file context.c.
References bContext::window, and bContext::wm.
Referenced by actionzone_apply(), actionzone_area_poll(), area_dupli_invoke(), area_move_apply_do(), area_split_exit(), area_split_modal(), area_swap_exit(), area_swap_invoke(), button_activate_init(), button_activate_state(), check_state_mask(), clip_rebuild_proxy_exec(), clip_refresh(), do_node_add(), do_view3d_header_buttons(), dynamicPaint_bakeImageSequence(), dynamicPaint_initBake(), ED_area_newspace(), ED_area_overdraw(), ED_area_swapspace(), ED_operator_areaactive(), ED_operator_regionactive(), ED_operator_screen_mainwinactive(), ED_operator_screenactive(), ED_operator_screenactive_norender(), ED_preview_icon_job(), ED_preview_shader_job(), ED_region_do_draw(), ED_region_exit(), ED_region_init(), ED_region_set(), ED_region_toggle_hidden(), ED_screen_animation_timer(), ED_screen_area_active(), ED_screen_delete(), ED_screen_do_listen(), ED_screen_exit(), ED_screen_full_newspace(), ED_screen_full_prevspace(), ED_screen_full_restore(), ED_screen_set(), ED_screen_set_subwinactive(), eyedropper_exit(), eyedropper_invoke(), eyedropper_poll(), file_directory_new_exec(), file_main_area_draw(), file_smoothscroll_invoke(), flyEnd(), game_engine_exec(), game_engine_poll(), ghost_event_proc(), gp_session_initdata(), gpencil_draw_exit(), gpencil_draw_invoke(), handle_layer_buttons(), hide_cursor(), id_search_menu(), image_record_composite_apply(), image_record_composite_exit(), image_record_composite_invoke(), image_view_pan_exit(), image_view_pan_init(), image_view_zoom_exit(), image_view_zoom_init(), initFlyInfo(), knifetool_exit(), knifetool_invoke(), minimize_stretch_exit(), minimize_stretch_invoke(), multiresbake_image_exec(), objects_bake_render_invoke(), ocean_bake_exec(), operator_search_menu(), paint_exit(), paint_invoke(), paint_stroke_modal(), panel_activate_state(), pose_slide_invoke_common(), pose_slide_modal(), ptcache_bake_all_exec(), ptcache_bake_exec(), redraw_timer_exec(), redraw_timer_window_swap(), render_view_cancel_exec(), render_view_open(), render_view_show_invoke(), screen_full_area_exec(), screen_new_exec(), screen_opengl_render_end(), screen_opengl_render_invoke(), screen_render_invoke(), screencast_exec(), screenshot(), select_report_pick_invoke(), seq_proxy_build_job(), sequencer_refresh(), show_cursor(), smooth_view(), snode_composite_job(), solve_camera_invoke(), StartKetsjiShell(), template_id_cb(), thumbnails_start(), tool_search_menu(), track_markers_invoke(), tweak_gesture_modal(), ui_button_activate_do(), ui_centered_bounds_block(), ui_handle_menu_event(), ui_handler_popup(), ui_layer_but_cb(), ui_popup_block_create(), ui_popup_block_free(), ui_popup_bounds_block(), ui_popup_menu_create(), ui_remove_temporary_region(), ui_searchbox_create(), ui_textedit_begin(), ui_textedit_end(), ui_tooltip_create(), uiBeginBlock(), uiLayoutOperatorButs(), uiPupBlockClose(), uiPupBlockEx(), uiPupBlockO(), uiPupMenuEnd(), uiPupMenuReports(), userpref_show_invoke(), uv_sculpt_stroke_exit(), uv_sculpt_stroke_invoke(), view3d_operator_needs_opengl(), view3d_smoothview_invoke(), view_pan_exit(), view_pan_init(), view_pan_invoke(), view_pan_modal(), view_zoom_exit(), view_zoom_init(), view_zoomdrag_exit(), view_zoomdrag_invoke(), view_zoomdrag_modal(), viewzoom_invoke(), weight_paint_sample_enum_itemf(), wm_block_search_menu(), WM_border_select_modal(), wm_debug_menu_exec(), wm_drop_operator_options(), wm_dropbox_active(), wm_enum_search_menu(), WM_event_add_fileselect(), WM_event_add_modal_handler(), WM_event_add_mousemove(), WM_event_add_notifier(), wm_event_do_handlers(), WM_event_remove_handlers(), WM_gesture_circle_modal(), wm_gesture_end(), WM_gesture_end(), WM_gesture_lasso_invoke(), WM_gesture_lasso_modal(), WM_gesture_lines_invoke(), WM_gesture_new(), WM_gesture_straightline_invoke(), WM_gesture_straightline_modal(), wm_gesture_tag_redraw(), WM_gestures_remove(), wm_handler_fileselect_call(), wm_handler_operator_call(), wm_handler_ui_cancel(), wm_handlers_do(), WM_init_game(), WM_init_splash(), wm_keymap_item_find_props(), wm_macro_modal(), wm_open_mainfile_invoke(), wm_operator_call_internal(), wm_operator_invoke(), wm_operator_reports(), WM_operator_winactive(), wm_operator_winactive_normal(), wm_paintcursor_draw(), wm_paintcursor_tag(), WM_redraw_windows(), wm_save_mainfile_invoke(), wm_search_menu_poll(), wm_tweakevent_test(), wm_window_duplicate_exec(), wm_window_free(), wm_window_fullscreen_toggle_exec(), wm_window_match_init(), and WM_write_homefile().
void CTX_wm_window_set (bContext * C, wmWindow * win)
Definition at line 409 of file context.c.
References bContext::area, bContext::data, if(), NULL, bContext::region, bContext::scene, bScreen::scene, bContext::screen, wmWindow::screen, bContext::window, and bContext::wm.
Referenced by ED_screen_exit(), ED_screen_set(), game_engine_exec(), ghost_event_proc(), redraw_timer_exec(), redraw_timer_window_swap(), wm_draw_update(), wm_event_do_handlers(), wm_event_do_notifiers(), WM_exit_ext(), wm_handler_fileselect_call(), WM_init_game(), WM_init_splash(), wm_operator_reports(), WM_read_file(), WM_read_homefile(), WM_redraw_windows(), wm_window_close(), wm_window_free(), wm_window_match_init(), and WM_window_open_temp().
static void data_dir_add (ListBase * lb, const char * member) [static]
Definition at line 622 of file context.c.
References BLI_addtail(), BLI_findstring(), data, LinkData::data, link(), and MEM_callocN().
Referenced by CTX_data_dir_get().
Variable Documentation
const char* data_mode_strings[] [static]
Initial value:
 {
    "mesh_edit",
    "curve_edit",
    "surface_edit",
    "text_edit",
    "armature_edit",
    "mball_edit",
    "lattice_edit",
    "posemode",
    "sculpt_mode",
    "weightpaint",
    "vertexpaint",
    "imagepaint",
    "particlemode",
    "objectmode",
    NULL
}
Definition at line 816 of file context.c.