Blender: anim_channels_edit.c File Reference
anim_channels_edit.c File Reference
animation
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_library.h"
#include "DNA_anim_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_key_types.h"
#include "DNA_gpencil_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "BKE_action.h"
#include "BKE_fcurve.h"
#include "BKE_gpencil.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "UI_view2d.h"
#include "ED_anim_api.h"
#include "ED_keyframes_edit.h"
#include "ED_screen.h"
#include "WM_api.h"
#include "WM_types.h"
Classes
struct tReorderChannelIsland
Typedefs
typedef struct
tReorderChannelIsland tReorderChannelIsland
typedef enum eReorderIslandFlag eReorderIslandFlag
typedef short(* AnimChanRearrangeFp)(ListBase *list, tReorderChannelIsland *island)
Enumerations
enum { REARRANGE_ANIMCHAN_TOP = -2, REARRANGE_ANIMCHAN_UP = -1, REARRANGE_ANIMCHAN_DOWN = 1, REARRANGE_ANIMCHAN_BOTTOM = 2 }
enum eReorderIslandFlag { REORDER_ISLAND_SELECTED = (1<<0), REORDER_ISLAND_UNTOUCHABLE = (1<<1), REORDER_ISLAND_MOVED = (1<<2) }
Functions
void ANIM_set_active_channel (bAnimContext *ac, void *data, short datatype, int filter, void *channel_data, short channel_type)
void ANIM_deselect_anim_channels (bAnimContext *ac, void *data, short datatype, short test, short sel)
void ANIM_flush_setting_anim_channels (bAnimContext *ac, ListBase *anim_data, bAnimListElem *ale_setting, int setting, short on)
void ANIM_fcurve_delete_from_animdata (bAnimContext *ac, AnimData *adt, FCurve *fcu)
static int animedit_poll_channels_active (bContext *C)
static int animedit_poll_channels_nla_tweakmode_off (bContext *C)
static short rearrange_island_ok (tReorderChannelIsland *island)
static short rearrange_island_top (ListBase *list, tReorderChannelIsland *island)
static short rearrange_island_up (ListBase *list, tReorderChannelIsland *island)
static short rearrange_island_down (ListBase *list, tReorderChannelIsland *island)
static short rearrange_island_bottom (ListBase *list, tReorderChannelIsland *island)
static AnimChanRearrangeFp rearrange_get_mode_func (short mode)
static void rearrange_animchannel_add_to_islands (ListBase *islands, ListBase *srcList, Link *channel, short type)
static void rearrange_animchannel_flatten_islands (ListBase *islands, ListBase *srcList)
static short rearrange_animchannel_islands (ListBase *list, AnimChanRearrangeFp rearrange_func, short mode, short type)
static void rearrange_nla_channels (bAnimContext *UNUSED(ac), AnimData *adt, short mode)
static void rearrange_driver_channels (bAnimContext *UNUSED(ac), AnimData *adt, short mode)
static void split_groups_action_temp (bAction *act, bActionGroup *tgrp)
static void join_groups_action_temp (bAction *act)
static void rearrange_action_channels (bAnimContext *ac, bAction *act, short mode)
static int animchannels_rearrange_exec (bContext *C, wmOperator *op)
static void ANIM_OT_channels_move (wmOperatorType *ot)
static int animchannels_delete_exec (bContext *C, wmOperator *UNUSED(op))
static void ANIM_OT_channels_delete (wmOperatorType *ot)
static int animchannels_visibility_set_exec (bContext *C, wmOperator *UNUSED(op))
static void ANIM_OT_channels_visibility_set (wmOperatorType *ot)
static int animchannels_visibility_toggle_exec (bContext *C, wmOperator *UNUSED(op))
static void ANIM_OT_channels_visibility_toggle (wmOperatorType *ot)
static void setflag_anim_channels (bAnimContext *ac, short setting, short mode, short onlysel, short flush)
static int animchannels_setflag_exec (bContext *C, wmOperator *op)
static void ANIM_OT_channels_setting_enable (wmOperatorType *ot)
static void ANIM_OT_channels_setting_disable (wmOperatorType *ot)
static void ANIM_OT_channels_setting_toggle (wmOperatorType *ot)
static void ANIM_OT_channels_editable_toggle (wmOperatorType *ot)
static int animchannels_expand_exec (bContext *C, wmOperator *op)
static void ANIM_OT_channels_expand (wmOperatorType *ot)
static int animchannels_collapse_exec (bContext *C, wmOperator *op)
static void ANIM_OT_channels_collapse (wmOperatorType *ot)
static int animchannels_enable_poll (bContext *C)
static int animchannels_enable_exec (bContext *C, wmOperator *UNUSED(op))
static void ANIM_OT_channels_fcurves_enable (wmOperatorType *ot)
static int animchannels_deselectall_exec (bContext *C, wmOperator *op)
static void ANIM_OT_channels_select_all_toggle (wmOperatorType *ot)
static void borderselect_anim_channels (bAnimContext *ac, rcti *rect, short selectmode)
static int animchannels_borderselect_exec (bContext *C, wmOperator *op)
static void ANIM_OT_channels_select_border (wmOperatorType *ot)
static void rename_anim_channels (bAnimContext *ac, int channel_index)
static int animchannels_rename_invoke (bContext *C, wmOperator *UNUSED(op), wmEvent *evt)
static void ANIM_OT_channels_rename (wmOperatorType *ot)
static int mouse_anim_channels (bAnimContext *ac, float UNUSED(x), int channel_index, short selectmode)
static int animchannels_mouseclick_invoke (bContext *C, wmOperator *op, wmEvent *event)
static void ANIM_OT_channels_click (wmOperatorType *ot)
void ED_operatortypes_animchannels (void)
void ED_keymap_animchannels (wmKeyConfig *keyconf)
Variables
static EnumPropertyItem prop_animchannel_rearrange_types []
static EnumPropertyItem prop_animchannel_setflag_types []
static EnumPropertyItem prop_animchannel_settings_types []
Detailed Description
Definition in file anim_channels_edit.c.
Typedef Documentation
typedef short(* AnimChanRearrangeFp)(ListBase *list, tReorderChannelIsland *island)
Definition at line 741 of file anim_channels_edit.c.
typedef enum eReorderIslandFlag eReorderIslandFlag
typedef struct tReorderChannelIsland tReorderChannelIsland
Enumeration Type Documentation
anonymous enum
Enumerator:
REARRANGE_ANIMCHAN_TOP
REARRANGE_ANIMCHAN_UP
REARRANGE_ANIMCHAN_DOWN
REARRANGE_ANIMCHAN_BOTTOM
Definition at line 602 of file anim_channels_edit.c.
enum eReorderIslandFlag
Enumerator:
REORDER_ISLAND_SELECTED
REORDER_ISLAND_UNTOUCHABLE
REORDER_ISLAND_MOVED
Definition at line 629 of file anim_channels_edit.c.
Function Documentation
void ANIM_deselect_anim_channels (bAnimContext * ac, void * data, short datatype, short test, short sel)
Definition at line 191 of file anim_channels_edit.c.
References ACHANNEL_SET_FLAG, ACHANNEL_SETFLAG_CLEAR, Scene::adt, bAnimListElem::adt, ADT_UI_ACTIVE, ADT_UI_SELECTED, AGRP_ACTIVE, AGRP_SELECTED, ANIM_animdata_filter(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMTYPE_DSARM, ANIMTYPE_DSCAM, ANIMTYPE_DSCUR, ANIMTYPE_DSLAM, ANIMTYPE_DSLAT, ANIMTYPE_DSMAT, ANIMTYPE_DSMBALL, ANIMTYPE_DSMESH, ANIMTYPE_DSNTREE, ANIMTYPE_DSPART, ANIMTYPE_DSSKEY, ANIMTYPE_DSSPK, ANIMTYPE_DSTEX, ANIMTYPE_DSWOR, ANIMTYPE_FCURVE, ANIMTYPE_FILLACTD, ANIMTYPE_GPLAYER, ANIMTYPE_GROUP, ANIMTYPE_NLATRACK, ANIMTYPE_OBJECT, ANIMTYPE_SCENE, ANIMTYPE_SHAPEKEY, BLI_freelistN(), bAnimListElem::data, FCURVE_ACTIVE, FCURVE_SELECTED, filter(), ListBase::first, NlaTrack::flag, FCurve::flag, bActionGroup::flag, AnimData::flag, bAnimListElem::flag, GP_LAYER_SELECT, KEYBLOCK_SEL, bAnimListElem::next, NLATRACK_ACTIVE, NLATRACK_SELECTED, NULL, Base::object, SCE_DS_SELECTED, SELECT, and bAnimListElem::type.
Referenced by animchannels_borderselect_exec(), animchannels_deselectall_exec(), mouse_action_keys(), mouse_anim_channels(), mouse_graph_keys(), mouse_nla_channels(), and mouse_nla_strips().
void ANIM_fcurve_delete_from_animdata (bAnimContext * ac, AnimData * adt, FCurve * fcu)
Definition at line 507 of file anim_channels_edit.c.
References AnimData::action, action_groups_remove_channel(), ADT_NLA_EDIT_ON, ANIMCONT_DRIVERS, BLI_remlink(), bAction::curves, bAnimContext::datatype, AnimData::drivers, ELEM, ListBase::first, AnimData::flag, free_fcurve(), FCurve::grp, bAction::id, id_us_min(), and NULL.
Referenced by animchannels_delete_exec(), delete_action_keys(), delete_graph_keys(), and delete_keyframe().
void ANIM_flush_setting_anim_channels (bAnimContext * ac, ListBase * anim_data, bAnimListElem * ale_setting, int setting, short on)
Definition at line 375 of file anim_channels_edit.c.
References ACHANNEL_SETTING_VISIBLE, ANIM_channel_get_typeinfo(), ANIM_channel_setting_set(), bAnimListElem::data, ELEM, ListBase::first, bAnimChannelType::get_offset, bAnimListElem::id, bAnimListElem::next, NULL, bAnimListElem::prev, and bAnimListElem::type.
Referenced by achannel_setting_flush_widget_cb(), animchannels_visibility_set_exec(), animchannels_visibility_toggle_exec(), and setflag_anim_channels().
static void ANIM_OT_channels_click (wmOperatorType * ot) [static]
Definition at line 2349 of file anim_channels_edit.c.
References animchannels_mouseclick_invoke(), animedit_poll_channels_active(), wmOperatorType::description, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_animchannels().
static void ANIM_OT_channels_collapse (wmOperatorType * ot) [static]
Definition at line 1685 of file anim_channels_edit.c.
References animchannels_collapse_exec(), animedit_poll_channels_active(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_animchannels().
static void ANIM_OT_channels_delete (wmOperatorType * ot) [static]
Definition at line 1220 of file anim_channels_edit.c.
References animchannels_delete_exec(), animedit_poll_channels_active(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_animchannels().
static void ANIM_OT_channels_editable_toggle (wmOperatorType * ot) [static]
Definition at line 1598 of file anim_channels_edit.c.
References ACHANNEL_SETFLAG_TOGGLE, ACHANNEL_SETTING_PROTECT, animchannels_setflag_exec(), animedit_poll_channels_active(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_animchannels().
static void ANIM_OT_channels_expand (wmOperatorType * ot) [static]
Definition at line 1643 of file anim_channels_edit.c.
References animchannels_expand_exec(), animedit_poll_channels_active(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_animchannels().
static void ANIM_OT_channels_fcurves_enable (wmOperatorType * ot) [static]
Definition at line 1761 of file anim_channels_edit.c.
References animchannels_enable_exec(), animchannels_enable_poll(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_animchannels().
static void ANIM_OT_channels_move (wmOperatorType * ot) [static]
Definition at line 1104 of file anim_channels_edit.c.
References animchannels_rearrange_exec(), animedit_poll_channels_nla_tweakmode_off(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, REARRANGE_ANIMCHAN_DOWN, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_animchannels().
static void ANIM_OT_channels_rename (wmOperatorType * ot) [static]
Definition at line 2040 of file anim_channels_edit.c.
References animchannels_rename_invoke(), animedit_poll_channels_active(), wmOperatorType::description, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, and wmOperatorType::poll.
Referenced by ED_operatortypes_animchannels().
static void ANIM_OT_channels_select_all_toggle (wmOperatorType * ot) [static]
Definition at line 1798 of file anim_channels_edit.c.
References animchannels_deselectall_exec(), animedit_poll_channels_nla_tweakmode_off(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_animchannels().
static void ANIM_OT_channels_select_border (wmOperatorType * ot) [static]
Definition at line 1929 of file anim_channels_edit.c.
References animchannels_borderselect_exec(), animedit_poll_channels_nla_tweakmode_off(), wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, TRUE, WM_border_select_cancel(), WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by ED_operatortypes_animchannels().
static void ANIM_OT_channels_setting_disable (wmOperatorType * ot) [static]
Definition at line 1554 of file anim_channels_edit.c.
References ACHANNEL_SETFLAG_CLEAR, animchannels_setflag_exec(), animedit_poll_channels_active(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_animchannels().
static void ANIM_OT_channels_setting_enable (wmOperatorType * ot) [static]
Definition at line 1532 of file anim_channels_edit.c.
References ACHANNEL_SETFLAG_ADD, animchannels_setflag_exec(), animedit_poll_channels_active(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_animchannels().
static void ANIM_OT_channels_setting_toggle (wmOperatorType * ot) [static]
Definition at line 1576 of file anim_channels_edit.c.
References ACHANNEL_SETFLAG_TOGGLE, animchannels_setflag_exec(), animedit_poll_channels_active(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_animchannels().
static void ANIM_OT_channels_visibility_set (wmOperatorType * ot) [static]
Definition at line 1312 of file anim_channels_edit.c.
References animchannels_visibility_set_exec(), wmOperatorType::description, ED_operator_graphedit_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_animchannels().
static void ANIM_OT_channels_visibility_toggle (wmOperatorType * ot) [static]
Definition at line 1389 of file anim_channels_edit.c.
References animchannels_visibility_toggle_exec(), wmOperatorType::description, ED_operator_graphedit_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_animchannels().
void ANIM_set_active_channel (bAnimContext * ac, void * data, short datatype, int filter, void * channel_data, short channel_type)
Definition at line 72 of file anim_channels_edit.c.
References ACHANNEL_SET_FLAG, ACHANNEL_SETFLAG_CLEAR, bAnimListElem::adt, ADT_UI_ACTIVE, AGRP_ACTIVE, ANIM_animdata_filter(), ANIMTYPE_DSARM, ANIMTYPE_DSCAM, ANIMTYPE_DSCUR, ANIMTYPE_DSLAM, ANIMTYPE_DSLAT, ANIMTYPE_DSMAT, ANIMTYPE_DSMBALL, ANIMTYPE_DSMESH, ANIMTYPE_DSPART, ANIMTYPE_DSSKEY, ANIMTYPE_DSSPK, ANIMTYPE_DSTEX, ANIMTYPE_DSWOR, ANIMTYPE_FCURVE, ANIMTYPE_FILLACTD, ANIMTYPE_GROUP, ANIMTYPE_NLATRACK, BLI_freelistN(), bAnimListElem::data, FCURVE_ACTIVE, ListBase::first, AnimData::flag, NlaTrack::flag, FCurve::flag, bActionGroup::flag, bAnimListElem::next, NLATRACK_ACTIVE, NULL, and bAnimListElem::type.
Referenced by mouse_action_keys(), mouse_anim_channels(), mouse_graph_keys(), mouse_nla_channels(), and mouse_nla_strips().
static int animchannels_borderselect_exec (bContext * C, wmOperator * op) [static]
Definition at line 1892 of file anim_channels_edit.c.
References ACHANNEL_SETFLAG_ADD, ACHANNEL_SETFLAG_CLEAR, ANIM_animdata_get_context(), ANIM_deselect_anim_channels(), borderselect_anim_channels(), bAnimContext::data, bAnimContext::datatype, GESTURE_MODAL_SELECT, NA_SELECTED, NC_ANIMATION, ND_ANIMCHAN, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_int_get(), WM_event_add_notifier(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ANIM_OT_channels_select_border().
static int animchannels_collapse_exec (bContext * C, wmOperator * op) [static]
Definition at line 1663 of file anim_channels_edit.c.
References ACHANNEL_SETFLAG_CLEAR, ACHANNEL_SETTING_EXPAND, ANIM_animdata_get_context(), NA_EDITED, NC_ANIMATION, ND_ANIMCHAN, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), setflag_anim_channels(), and WM_event_add_notifier().
Referenced by ANIM_OT_channels_collapse().
static int animchannels_delete_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1124 of file anim_channels_edit.c.
References action_groups_remove_channel(), bAnimListElem::adt, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIM_fcurve_delete_from_animdata(), ANIMCONT_DRIVERS, ANIMCONT_SHAPEKEY, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, ANIMFILTER_SEL, ANIMTYPE_FCURVE, ANIMTYPE_GPLAYER, ANIMTYPE_GROUP, BLI_freelinkN(), BLI_freelistN(), bActionGroup::channels, bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, filter(), ListBase::first, free_fcurve(), free_gpencil_frames(), FCurve::grp, bAnimListElem::id, if(), bGPdata::layers, MEM_freeN(), NA_EDITED, NC_ANIMATION, ND_ANIMCHAN, FCurve::next, bAnimListElem::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, bAnimListElem::type, and WM_event_add_notifier().
Referenced by ANIM_OT_channels_delete().
static int animchannels_deselectall_exec (bContext * C, wmOperator * op) [static]
Definition at line 1778 of file anim_channels_edit.c.
References ACHANNEL_SETFLAG_ADD, ACHANNEL_SETFLAG_TOGGLE, ANIM_animdata_get_context(), ANIM_deselect_anim_channels(), bAnimContext::data, bAnimContext::datatype, NA_SELECTED, NC_ANIMATION, ND_ANIMCHAN, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), and WM_event_add_notifier().
Referenced by ANIM_OT_channels_select_all_toggle().
static int animchannels_enable_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1721 of file anim_channels_edit.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIM_list_elem_update(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_NODUPLIS, BLI_freelistN(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, FCurve::driver, DRIVER_FLAG_INVALID, FCURVE_DISABLED, filter(), ListBase::first, FCurve::flag, ChannelDriver::flag, if(), NA_EDITED, NC_ANIMATION, ND_ANIMCHAN, bAnimListElem::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, bAnimContext::scene, and WM_event_add_notifier().
Referenced by ANIM_OT_channels_fcurves_enable().
static int animchannels_enable_poll (bContext * C) [static]
Definition at line 1705 of file anim_channels_edit.c.
References CTX_wm_area(), CTX_wm_region(), ELEM, NULL, SPACE_ACTION, SPACE_IPO, and ScrArea::spacetype.
Referenced by ANIM_OT_channels_fcurves_enable().
static int animchannels_expand_exec (bContext * C, wmOperator * op) [static]
Definition at line 1621 of file anim_channels_edit.c.
References ACHANNEL_SETFLAG_ADD, ACHANNEL_SETTING_EXPAND, ANIM_animdata_get_context(), NA_EDITED, NC_ANIMATION, ND_ANIMCHAN, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), setflag_anim_channels(), and WM_event_add_notifier().
Referenced by ANIM_OT_channels_expand().
static int animchannels_mouseclick_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2305 of file anim_channels_edit.c.
References ACHANNEL_HEIGHT_HALF, ACHANNEL_NAMEWIDTH, ACHANNEL_STEP, ANIM_animdata_get_context(), bAnimContext::ar, mouse_anim_channels(), wmEvent::mval, NC_ANIMATION, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), SELECT_INVERT, SELECT_REPLACE, UI_view2d_listview_view_to_cell(), UI_view2d_region_to_view(), ARegion::v2d, and WM_event_add_notifier().
Referenced by ANIM_OT_channels_click().
static int animchannels_rearrange_exec (bContext * C, wmOperator * op) [static]
Definition at line 1041 of file anim_channels_edit.c.
References AnimData::action, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMCONT_ACTION, ANIMCONT_DRIVERS, ANIMCONT_GPENCIL, ANIMCONT_NLA, ANIMCONT_SHAPEKEY, ANIMFILTER_ANIMDATA, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_VISIBLE, BLI_freelistN(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, filter(), ListBase::first, G, G_DEBUG, NA_EDITED, NC_ANIMATION, ND_ANIMCHAN, bAnimListElem::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, rearrange_action_channels(), rearrange_driver_channels(), rearrange_nla_channels(), RNA_enum_get(), and WM_event_add_notifier().
Referenced by ANIM_OT_channels_move().
static int animchannels_rename_invoke (bContext * C, wmOperator * UNUSEDop, wmEvent * evt) [static]
Definition at line 2003 of file anim_channels_edit.c.
References ACHANNEL_HEIGHT_HALF, ACHANNEL_NAMEWIDTH, ACHANNEL_STEP, ANIM_animdata_get_context(), ANIMCONT_NLA, bAnimContext::ar, bAnimContext::datatype, wmEvent::mval, NLACHANNEL_HEIGHT_HALF, NLACHANNEL_NAMEWIDTH, NLACHANNEL_STEP, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, rename_anim_channels(), bAnimContext::sl, UI_view2d_listview_view_to_cell(), UI_view2d_region_to_view(), and ARegion::v2d.
Referenced by ANIM_OT_channels_rename().
static int animchannels_setflag_exec (bContext * C, wmOperator * op) [static]
Definition at line 1502 of file anim_channels_edit.c.
References ACHANNEL_SETTING_EXPAND, ANIM_animdata_get_context(), NA_EDITED, NC_ANIMATION, ND_ANIMCHAN, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), setflag_anim_channels(), and WM_event_add_notifier().
Referenced by ANIM_OT_channels_editable_toggle(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), and ANIM_OT_channels_setting_toggle().
static int animchannels_visibility_set_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1238 of file anim_channels_edit.c.
References ACHANNEL_SETFLAG_ADD, ACHANNEL_SETFLAG_CLEAR, ACHANNEL_SETTING_VISIBLE, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIM_channel_setting_set(), ANIM_flush_setting_anim_channels(), ANIMFILTER_CURVE_VISIBLE, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, ANIMFILTER_SEL, ANIMFILTER_UNSEL, ANIMTYPE_OBJECT, BLI_freelistN(), bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, NA_EDITED, NC_ANIMATION, ND_ANIMCHAN, bAnimListElem::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, bAnimContext::regiontype, RGN_TYPE_CHANNELS, SPACE_IPO, bAnimContext::spacetype, bAnimListElem::type, and WM_event_add_notifier().
Referenced by ANIM_OT_channels_visibility_set().
static int animchannels_visibility_toggle_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1331 of file anim_channels_edit.c.
References ACHANNEL_SETFLAG_ADD, ACHANNEL_SETFLAG_CLEAR, ACHANNEL_SETTING_VISIBLE, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIM_channel_setting_get(), ANIM_channel_setting_set(), ANIM_flush_setting_anim_channels(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, ANIMFILTER_SEL, ANIMTYPE_OBJECT, BLI_freelistN(), bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, NA_EDITED, NC_ANIMATION, ND_ANIMCHAN, bAnimListElem::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, bAnimListElem::type, and WM_event_add_notifier().
Referenced by ANIM_OT_channels_visibility_toggle().
static int animedit_poll_channels_active (bContext * C) [static]
Definition at line 560 of file anim_channels_edit.c.
References CTX_wm_area(), CTX_wm_region(), ELEM, ELEM3, NULL, SPACE_ACTION, SPACE_IPO, SPACE_NLA, and ScrArea::spacetype.
Referenced by ANIM_OT_channels_click(), ANIM_OT_channels_collapse(), ANIM_OT_channels_delete(), ANIM_OT_channels_editable_toggle(), ANIM_OT_channels_expand(), ANIM_OT_channels_rename(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), and ANIM_OT_channels_setting_toggle().
static int animedit_poll_channels_nla_tweakmode_off (bContext * C) [static]
Definition at line 576 of file anim_channels_edit.c.
References CTX_data_scene(), CTX_wm_area(), CTX_wm_region(), ELEM, ELEM3, Scene::flag, NULL, SCE_NLA_EDIT_ON, SPACE_ACTION, SPACE_IPO, SPACE_NLA, and ScrArea::spacetype.
Referenced by ANIM_OT_channels_move(), ANIM_OT_channels_select_all_toggle(), and ANIM_OT_channels_select_border().
static void borderselect_anim_channels (bAnimContext * ac, rcti * rect, short selectmode) [static]
Definition at line 1818 of file anim_channels_edit.c.
References ACHANNEL_HEIGHT, ACHANNEL_SET_FLAG, ACHANNEL_SETTING_SELECT, ACHANNEL_STEP, AGRP_ACTIVE, ANIM_animdata_filter(), ANIM_channel_setting_set(), ANIMCONT_NLA, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, ANIMTYPE_GROUP, ANIMTYPE_NLATRACK, bAnimContext::ar, BLI_freelistN(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, filter(), ListBase::first, bActionGroup::flag, if(), bAnimListElem::next, NLACHANNEL_HEIGHT, NLACHANNEL_STEP, NLATRACK_SELECTED, NULL, bAnimContext::sl, bAnimListElem::type, UI_view2d_region_to_view(), ARegion::v2d, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by animchannels_borderselect_exec().
void ED_keymap_animchannels (wmKeyConfig * keyconf)
Definition at line 2400 of file anim_channels_edit.c.
References AKEY, BKEY, DELKEY, EVT_TWEAK_L, FALSE, IKEY, KM_ALT, KM_ANY, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTMOUSE, PADMINUS, PADPLUSKEY, PAGEDOWNKEY, PAGEUPKEY, wmKeyMapItem::ptr, REARRANGE_ANIMCHAN_BOTTOM, REARRANGE_ANIMCHAN_DOWN, REARRANGE_ANIMCHAN_TOP, REARRANGE_ANIMCHAN_UP, RNA_boolean_set(), RNA_enum_set(), TABKEY, TRUE, VKEY, WKEY, WM_keymap_add_item(), WM_keymap_find(), and XKEY.
Referenced by ED_spacetypes_keymap().
void ED_operatortypes_animchannels (void)
Definition at line 2371 of file anim_channels_edit.c.
References ANIM_OT_channels_click(), ANIM_OT_channels_collapse(), ANIM_OT_channels_delete(), ANIM_OT_channels_editable_toggle(), ANIM_OT_channels_expand(), ANIM_OT_channels_fcurves_enable(), ANIM_OT_channels_move(), ANIM_OT_channels_rename(), ANIM_OT_channels_select_all_toggle(), ANIM_OT_channels_select_border(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), ANIM_OT_channels_setting_toggle(), ANIM_OT_channels_visibility_set(), ANIM_OT_channels_visibility_toggle(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
static void join_groups_action_temp (bAction * act) [static]
Definition at line 978 of file anim_channels_edit.c.
References AGRP_MOVED, AGRP_TEMP, BLI_movelisttolist(), BLI_remlink(), bActionGroup::channels, bAction::curves, ListBase::first, bActionGroup::flag, bAction::groups, and bActionGroup::next.
Referenced by rearrange_action_channels().
static int mouse_anim_channels (bAnimContext * ac, float UNUSEDx, int channel_index, short selectmode) [static]
Definition at line 2055 of file anim_channels_edit.c.
References ACHANNEL_SETFLAG_CLEAR, bAnimListElem::adt, Scene::adt, Object::adt, ADT_UI_ACTIVE, ADT_UI_SELECTED, AGRP_SELECTED, ANIM_animdata_filter(), ANIM_deselect_anim_channels(), ANIM_set_active_channel(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, ANIMTYPE_DSARM, ANIMTYPE_DSCAM, ANIMTYPE_DSCUR, ANIMTYPE_DSLAM, ANIMTYPE_DSLAT, ANIMTYPE_DSMAT, ANIMTYPE_DSMBALL, ANIMTYPE_DSMESH, ANIMTYPE_DSNTREE, ANIMTYPE_DSPART, ANIMTYPE_DSSKEY, ANIMTYPE_DSSPK, ANIMTYPE_DSTEX, ANIMTYPE_DSWOR, ANIMTYPE_FCURVE, ANIMTYPE_FILLACTD, ANIMTYPE_GPDATABLOCK, ANIMTYPE_GPLAYER, ANIMTYPE_GROUP, ANIMTYPE_OBJECT, ANIMTYPE_SCENE, ANIMTYPE_SHAPEKEY, BLI_findlink(), BLI_freelistN(), bActionGroup::channels, bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, FCURVE_SELECTED, filter(), ListBase::first, AnimData::flag, Base::flag, Object::flag, KeyBlock::flag, bGPdata::flag, bGPDlayer::flag, Scene::flag, FCurve::flag, bActionGroup::flag, G, G_DEBUG, GP_DATA_EXPAND, GP_LAYER_SELECT, FCurve::grp, if(), KEYBLOCK_SEL, NA_EDITED, NA_SELECTED, ND_ANIMCHAN, FCurve::next, Base::next, NULL, Base::object, SCE_DS_SELECTED, SELECT, SELECT_INVERT, bDopeSheet::source, and bAnimListElem::type.
Referenced by animchannels_mouseclick_invoke().
static void rearrange_action_channels (bAnimContext * ac, bAction * act, short mode) [static]
Definition at line 1004 of file anim_channels_edit.c.
References ANIMTYPE_FCURVE, ANIMTYPE_GROUP, bActionGroup::channels, EXPANDED_AGRP, ListBase::first, bAction::groups, join_groups_action_temp(), bActionGroup::next, NULL, rearrange_animchannel_islands(), rearrange_get_mode_func(), and split_groups_action_temp().
Referenced by animchannels_rearrange_exec().
static void rearrange_animchannel_add_to_islands (ListBase * islands, ListBase * srcList, Link * channel, short type) [static]
Definition at line 763 of file anim_channels_edit.c.
References AGRP_TEMP, ANIMTYPE_FCURVE, ANIMTYPE_GROUP, ANIMTYPE_NLATRACK, BLI_addtail(), BLI_remlink(), tReorderChannelIsland::channels, tReorderChannelIsland::flag, bActionGroup::flag, ListBase::last, MEM_callocN(), NULL, REORDER_ISLAND_SELECTED, REORDER_ISLAND_UNTOUCHABLE, SEL_AGRP, SEL_FCU, and SEL_NLT.
Referenced by rearrange_animchannel_islands().
static void rearrange_animchannel_flatten_islands (ListBase * islands, ListBase * srcList) [static]
Definition at line 819 of file anim_channels_edit.c.
References BLI_assert, BLI_freelinkN(), BLI_movelisttolist(), tReorderChannelIsland::channels, ListBase::first, tReorderChannelIsland::next, and NULL.
Referenced by rearrange_animchannel_islands().
static short rearrange_animchannel_islands (ListBase * list, AnimChanRearrangeFp rearrange_func, short mode, short type) [static]
Definition at line 839 of file anim_channels_edit.c.
References ListBase::first, tReorderChannelIsland::flag, if(), ListBase::last, tReorderChannelIsland::next, Link::next, NULL, tReorderChannelIsland::prev, rearrange_animchannel_add_to_islands(), rearrange_animchannel_flatten_islands(), and REORDER_ISLAND_MOVED.
Referenced by rearrange_action_channels(), rearrange_driver_channels(), and rearrange_nla_channels().
static void rearrange_driver_channels (bAnimContext * UNUSEDac, AnimData * adt, short mode) [static]
Definition at line 912 of file anim_channels_edit.c.
References ANIMTYPE_FCURVE, AnimData::drivers, EXPANDED_DRVD, NULL, rearrange_animchannel_islands(), and rearrange_get_mode_func().
Referenced by animchannels_rearrange_exec().
static AnimChanRearrangeFp rearrange_get_mode_func (short mode) [static]
Definition at line 744 of file anim_channels_edit.c.
References NULL, REARRANGE_ANIMCHAN_BOTTOM, REARRANGE_ANIMCHAN_DOWN, REARRANGE_ANIMCHAN_TOP, REARRANGE_ANIMCHAN_UP, rearrange_island_bottom(), rearrange_island_down(), rearrange_island_top(), and rearrange_island_up().
Referenced by rearrange_action_channels(), rearrange_driver_channels(), and rearrange_nla_channels().
static short rearrange_island_bottom (ListBase * list, tReorderChannelIsland * island) [static]
Definition at line 709 of file anim_channels_edit.c.
References BLI_addtail(), BLI_insertlinkbefore(), BLI_remlink(), tReorderChannelIsland::flag, ListBase::last, rearrange_island_ok(), and REORDER_ISLAND_UNTOUCHABLE.
Referenced by rearrange_get_mode_func().
static short rearrange_island_down (ListBase * list, tReorderChannelIsland * island) [static]
Definition at line 685 of file anim_channels_edit.c.
References BLI_insertlinkafter(), BLI_remlink(), tReorderChannelIsland::flag, tReorderChannelIsland::next, next, rearrange_island_ok(), and REORDER_ISLAND_UNTOUCHABLE.
Referenced by rearrange_get_mode_func().
static short rearrange_island_ok (tReorderChannelIsland * island) [static]
Definition at line 638 of file anim_channels_edit.c.
References tReorderChannelIsland::flag, REORDER_ISLAND_MOVED, REORDER_ISLAND_SELECTED, and REORDER_ISLAND_UNTOUCHABLE.
Referenced by rearrange_island_bottom(), rearrange_island_down(), rearrange_island_top(), and rearrange_island_up().
static short rearrange_island_top (ListBase * list, tReorderChannelIsland * island) [static]
Definition at line 650 of file anim_channels_edit.c.
References BLI_insertlinkbefore(), BLI_remlink(), ListBase::first, and rearrange_island_ok().
Referenced by rearrange_get_mode_func().
static short rearrange_island_up (ListBase * list, tReorderChannelIsland * island) [static]
Definition at line 665 of file anim_channels_edit.c.
References BLI_insertlinkbefore(), BLI_remlink(), tReorderChannelIsland::prev, and rearrange_island_ok().
Referenced by rearrange_get_mode_func().
static void rearrange_nla_channels (bAnimContext * UNUSEDac, AnimData * adt, short mode) [static]
Definition at line 887 of file anim_channels_edit.c.
References ANIMTYPE_NLATRACK, AnimData::nla_tracks, NULL, rearrange_animchannel_islands(), and rearrange_get_mode_func().
Referenced by animchannels_rearrange_exec().
static void rename_anim_channels (bAnimContext * ac, int channel_index) [static]
Definition at line 1954 of file anim_channels_edit.c.
References bAnimContext::ads, ANIM_animdata_filter(), ANIM_channel_get_typeinfo(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, bAnimContext::ar, BLI_findlink(), BLI_freelistN(), bAnimContext::data, bAnimContext::datatype, ED_region_tag_redraw(), filter(), G, G_DEBUG, bAnimChannelType::name_prop, NULL, and bDopeSheet::renameIndex.
Referenced by animchannels_rename_invoke().
static void setflag_anim_channels (bAnimContext * ac, short setting, short mode, short onlysel, short flush) [static]
Definition at line 1432 of file anim_channels_edit.c.
References ACHANNEL_SETFLAG_ADD, ACHANNEL_SETFLAG_CLEAR, ACHANNEL_SETFLAG_TOGGLE, ANIM_animdata_filter(), ANIM_channel_setting_get(), ANIM_channel_setting_set(), ANIM_flush_setting_anim_channels(), ANIMFILTER_CURVE_VISIBLE, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_NODUPLIS, ANIMFILTER_SEL, BLI_freelistN(), bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, bAnimListElem::next, NULL, bAnimContext::regiontype, RGN_TYPE_CHANNELS, SPACE_IPO, and bAnimContext::spacetype.
Referenced by animchannels_collapse_exec(), animchannels_expand_exec(), and animchannels_setflag_exec().
static void split_groups_action_temp (bAction * act, bActionGroup * tgrp) [static]
Definition at line 931 of file anim_channels_edit.c.
References AGRP_EXPANDED, AGRP_TEMP, BLI_addtail(), BLI_strncpy(), bActionGroup::channels, bAction::curves, ListBase::first, bActionGroup::flag, bAction::groups, ListBase::last, bActionGroup::name, FCurve::next, bActionGroup::next, NULL, and FCurve::prev.
Referenced by rearrange_action_channels().
Variable Documentation
EnumPropertyItem prop_animchannel_rearrange_types[] [static]
Initial value:
 {
    {REARRANGE_ANIMCHAN_TOP, "TOP", 0, "To Top", ""},
    {REARRANGE_ANIMCHAN_UP, "UP", 0, "Up", ""},
    {REARRANGE_ANIMCHAN_DOWN, "DOWN", 0, "Down", ""},
    {REARRANGE_ANIMCHAN_BOTTOM, "BOTTOM", 0, "To Bottom", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 610 of file anim_channels_edit.c.
EnumPropertyItem prop_animchannel_setflag_types[] [static]
Initial value:
 {
    {ACHANNEL_SETFLAG_TOGGLE, "TOGGLE", 0, "Toggle", ""},
    {ACHANNEL_SETFLAG_CLEAR, "DISABLE", 0, "Disable", ""},
    {ACHANNEL_SETFLAG_ADD, "ENABLE", 0, "Enable", ""},
    {ACHANNEL_SETFLAG_INVERT, "INVERT", 0, "Invert", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 1407 of file anim_channels_edit.c.
EnumPropertyItem prop_animchannel_settings_types[] [static]
Initial value:
 {
    {ACHANNEL_SETTING_PROTECT, "PROTECT", 0, "Protect", ""},
    {ACHANNEL_SETTING_MUTE, "MUTE", 0, "Mute", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 1417 of file anim_channels_edit.c.