Blender: IK_QJacobianSolver.cpp File Reference
IK_QJacobianSolver.cpp File Reference
iksolver
#include <stdio.h>
#include "IK_QJacobianSolver.h"
#include "MT_Quaternion.h"
Functions
static MT_Scalar safe_acos (MT_Scalar f)
static MT_Vector3 normalize (const MT_Vector3 &v)
static float angle (const MT_Vector3 &v1, const MT_Vector3 &v2)
Detailed Description
Definition in file IK_QJacobianSolver.cpp.
Function Documentation
static float angle (const MT_Vector3 & v1, const MT_Vector3 & v2) [static]
Definition at line 188 of file IK_QJacobianSolver.cpp.
References MT_Vector3::dot(), and safe_acos().
static MT_Vector3 normalize (const MT_Vector3 & v) [static]
Definition at line 180 of file IK_QJacobianSolver.cpp.
References len(), MT_Vector3::length(), and MT_fuzzyZero().
static MT_Scalar safe_acos (MT_Scalar f) [static]
Definition at line 172 of file IK_QJacobianSolver.cpp.
References acos(), and MT_PI().
Referenced by angle().