Blender: KX_BlenderKeyboardDevice Class Reference
KX_BlenderKeyboardDevice Class Reference
#include <KX_BlenderKeyboardDevice.h>
Public Member Functions
KX_BlenderKeyboardDevice ()
virtual ~KX_BlenderKeyboardDevice ()
virtual bool IsPressed (SCA_IInputDevice::KX_EnumInputs inputcode)
virtual bool ConvertBlenderEvent (unsigned short incode, short val)
virtual void NextFrame ()
virtual void HookEscape ()
Detailed Description
Definition at line 41 of file KX_BlenderKeyboardDevice.h.
Constructor & Destructor Documentation
KX_BlenderKeyboardDevice::KX_BlenderKeyboardDevice ()
Definition at line 41 of file KX_BlenderKeyboardDevice.cpp.
KX_BlenderKeyboardDevice::~KX_BlenderKeyboardDevice () [virtual]
Definition at line 46 of file KX_BlenderKeyboardDevice.cpp.
Member Function Documentation
bool KX_BlenderKeyboardDevice::ConvertBlenderEvent (unsigned short incode, short val) [virtual]
ConvertBlenderEvent translates blender keyboard events into ketsji kbd events extra event information is stored, like ramp-mode (just released/pressed)
Implements BL_BlenderInputDevice.
Definition at line 96 of file KX_BlenderKeyboardDevice.cpp.
References KX_KetsjiEngine::GetExitKey(), IsPressed(), KM_PRESS, KM_RELEASE, SCA_InputEvent::KX_ACTIVE, SCA_IInputDevice::KX_BEGINKEY, SCA_IInputDevice::KX_ENDKEY, SCA_InputEvent::KX_JUSTACTIVATED, SCA_InputEvent::KX_JUSTRELEASED, SCA_IInputDevice::KX_LEFTCTRLKEY, SCA_InputEvent::KX_NO_INPUTSTATUS, SCA_IInputDevice::KX_PAUSEKEY, SCA_IInputDevice::KX_RIGHTCTRLKEY, SCA_IInputDevice::m_currentTable, SCA_IInputDevice::m_eventStatusTables, SCA_InputEvent::m_eventval, SCA_InputEvent::m_status, and BL_BlenderInputDevice::ToNative().
Referenced by StartKetsjiShell().
void KX_BlenderKeyboardDevice::HookEscape () [virtual]
Reimplemented from SCA_IInputDevice.
Definition at line 167 of file KX_BlenderKeyboardDevice.cpp.
bool KX_BlenderKeyboardDevice::IsPressed (SCA_IInputDevice::KX_EnumInputs inputcode) [virtual]
IsPressed gives boolean information about keyboard status, true if pressed, false if not
Implements BL_BlenderInputDevice.
Definition at line 55 of file KX_BlenderKeyboardDevice.cpp.
References SCA_InputEvent::KX_ACTIVE, SCA_InputEvent::KX_JUSTACTIVATED, SCA_IInputDevice::m_currentTable, SCA_IInputDevice::m_eventStatusTables, and SCA_InputEvent::m_status.
Referenced by ConvertBlenderEvent().
void KX_BlenderKeyboardDevice::NextFrame () [virtual]
NextFrame toggles currentTable with previousTable, and copy relevant event information from previous to current (pressed keys need to be remembered)
Reimplemented from SCA_IInputDevice.
Definition at line 72 of file KX_BlenderKeyboardDevice.cpp.
References SCA_InputEvent::KX_ACTIVE, SCA_IInputDevice::KX_BEGINKEY, SCA_IInputDevice::KX_ENDKEY, SCA_InputEvent::KX_JUSTACTIVATED, SCA_IInputDevice::m_currentTable, SCA_IInputDevice::m_eventStatusTables, and SCA_InputEvent::m_status.
The documentation for this class was generated from the following files:
KX_BlenderKeyboardDevice.h
KX_BlenderKeyboardDevice.cpp