Blender: dpxlib.h File Reference
dpxlib.h File Reference
Cineon
#include "logImageCore.h"
Typedefs
typedef struct _Log_Image_File_t_ DpxFile
Functions
void dpxSetVerbose (int)
DpxFile * dpxOpen (const char *filename)
DpxFile * dpxCreate (const char *filename, int xsize, int ysize, int channels)
DpxFile * dpxOpenFromMem (unsigned char *buffer, unsigned int size)
int dpxIsMemFileCineon (void *buffer)
int dpxGetRowBytes (DpxFile *dpx, unsigned short *row, int y)
int dpxSetRowBytes (DpxFile *dpx, const unsigned short *row, int y)
void dpxClose (DpxFile *dpx)
void dpxDump (const char *filename)
Detailed Description
Definition in file dpxlib.h.
Typedef Documentation
typedef struct _Log_Image_File_t_ DpxFile
Definition at line 34 of file dpxlib.h.
Function Documentation
void dpxClose (DpxFile * dpx)
Definition at line 666 of file dpxlib.c.
References _Log_Image_File_t_::file, _Log_Image_File_t_::lineBuffer, and _Log_Image_File_t_::pixelBuffer.
Referenced by dpxCreate(), and intern_dpxOpen().
DpxFile* dpxCreate (const char * filename, int xsize, int ysize, int channels)
Definition at line 576 of file dpxlib.c.
References _Log_Image_File_t_::bitsPerPixel, BLI_fopen(), DpxImageInformation::channel, _Log_Image_File_t_::close, d_printf, _Log_Image_File_t_::depth, LogImageByteConversionParameters::doLogarithm, dpxClose(), dpxSetRowBytes(), _Log_Image_File_t_::file, _Log_Image_File_t_::fileYPos, _Log_Image_File_t_::getRow, _Log_Image_File_t_::height, DpxMainHeader::imageInfo, _Log_Image_File_t_::imageOffset, initDpxMainHeader(), _Log_Image_File_t_::lineBuffer, _Log_Image_File_t_::lineBufferLength, logImageGetByteConversionDefaults(), _Log_Image_File_t_::params, _Log_Image_File_t_::pixelBuffer, _Log_Image_File_t_::pixelBufferUsed, pixelsToLongs(), _Log_Image_File_t_::reading, _Log_Image_File_t_::setRow, setupLut(), DpxChannelInformation::transfer_characteristics, verbose, and _Log_Image_File_t_::width.
Referenced by logImageCreate().
void dpxDump (const char * filename)
Definition at line 691 of file dpxlib.c.
References BLI_fopen(), d_printf, and dumpDpxMainHeader().
Referenced by logImageDump().
int dpxGetRowBytes (DpxFile * dpx, unsigned short * row, int y)
Definition at line 230 of file dpxlib.c.
References d_printf, _Log_Image_File_t_::depth, LogImageByteConversionParameters::doLogarithm, _Log_Image_File_t_::fileYPos, _Log_Image_File_t_::imageOffset, _Log_Image_File_t_::lineBuffer, logimage_fread(), logimage_fseek(), _Log_Image_File_t_::lut10_16, _Log_Image_File_t_::params, _Log_Image_File_t_::pixelBuffer, _Log_Image_File_t_::pixelBufferUsed, pixelsToLongs(), verbose, and _Log_Image_File_t_::width.
Referenced by intern_dpxOpen().
int dpxIsMemFileCineon (void * buffer)
Definition at line 568 of file dpxlib.c.
References DPX_FILE_MAGIC.
Referenced by imb_is_dpx().
DpxFile* dpxOpen (const char * filename)
Definition at line 558 of file dpxlib.c.
References intern_dpxOpen(), and LFREALFILE.
Referenced by logImageOpen().
DpxFile* dpxOpenFromMem (unsigned char * buffer, unsigned int size)
Definition at line 563 of file dpxlib.c.
References intern_dpxOpen(), and LFMEMFILE.
Referenced by logImageOpenFromMem().
int dpxSetRowBytes (DpxFile * dpx, const unsigned short * row, int y)
Definition at line 309 of file dpxlib.c.
References d_printf, _Log_Image_File_t_::depth, LogImageByteConversionParameters::doLogarithm, _Log_Image_File_t_::file, _Log_Image_File_t_::fileYPos, _Log_Image_File_t_::height, _Log_Image_File_t_::imageOffset, _Log_Image_File_t_::lineBuffer, logimage_fseek(), _Log_Image_File_t_::lut16_16, _Log_Image_File_t_::params, _Log_Image_File_t_::pixelBuffer, _Log_Image_File_t_::pixelBufferUsed, pixelsToLongs(), verbose, and _Log_Image_File_t_::width.
Referenced by dpxCreate().
void dpxSetVerbose (int)
Definition at line 216 of file dpxlib.c.
References verbose.
Referenced by logImageSetVerbose().