Blender: AUD_IIRFilterReader Class Reference
AUD_IIRFilterReader Class Reference
#include <AUD_IIRFilterReader.h>
Public Member Functions
AUD_IIRFilterReader (AUD_Reference< AUD_IReader > reader, const std::vector< float > &b, const std::vector< float > &a)
virtual sample_t filter ()
void setCoefficients (const std::vector< float > &b, const std::vector< float > &a)
Detailed Description
This class is for infinite impulse response filters with simple coefficients.
Definition at line 40 of file AUD_IIRFilterReader.h.
Constructor & Destructor Documentation
AUD_IIRFilterReader::AUD_IIRFilterReader (AUD_Reference< AUD_IReader > reader, const std::vector< float > & b, const std::vector< float > & a)
Creates a new IIR filter reader.
Parameters:
reader The reader to read from.
b The input filter coefficients.
a The output filter coefficients.
Definition at line 32 of file AUD_IIRFilterReader.cpp.
References i.
Member Function Documentation
sample_t AUD_IIRFilterReader::filter () [virtual]
Runs the filtering function.
Returns:
The current output sample value.
Implements AUD_BaseIIRFilterReader.
Definition at line 47 of file AUD_IIRFilterReader.cpp.
References i, AUD_BaseIIRFilterReader::x(), and AUD_BaseIIRFilterReader::y().
void AUD_IIRFilterReader::setCoefficients (const std::vector< float > & b, const std::vector< float > & a)
Definition at line 59 of file AUD_IIRFilterReader.cpp.
References AUD_BaseIIRFilterReader::setLengths().
Referenced by AUD_DynamicIIRFilterReader::sampleRateChanged().
The documentation for this class was generated from the following files:
AUD_IIRFilterReader.h
AUD_IIRFilterReader.cpp