Blender: anim_markers.c File Reference
anim_markers.c File Reference
animation
#include <math.h>
#include "MEM_guardedalloc.h"
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_fcurve.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "BKE_screen.h"
#include "WM_api.h"
#include "WM_types.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "UI_interface.h"
#include "UI_interface_icons.h"
#include "UI_view2d.h"
#include "UI_resources.h"
#include "ED_anim_api.h"
#include "ED_markers.h"
#include "ED_screen.h"
#include "ED_util.h"
#include "ED_numinput.h"
#include "ED_object.h"
#include "ED_transform.h"
#include "ED_types.h"
Classes
struct MarkerMove
Typedefs
typedef struct MarkerMove MarkerMove
Functions
static ListBase * context_get_markers (Scene *scene, ScrArea *sa)
ListBase * ED_context_get_markers (const bContext *C)
ListBase * ED_animcontext_get_markers (const bAnimContext *ac)
int ED_markers_post_apply_transform (ListBase *markers, Scene *scene, int mode, float value, char side)
TimeMarker * ED_markers_find_nearest_marker (ListBase *markers, float x)
int ED_markers_find_nearest_marker_time (ListBase *markers, float x)
void ED_markers_get_minmax (ListBase *markers, short sel, float *first, float *last)
static void add_marker_to_cfra_elem (ListBase *lb, TimeMarker *marker, short only_sel)
void ED_markers_make_cfra_list (ListBase *markers, ListBase *lb, short only_sel)
TimeMarker * ED_markers_get_first_selected (ListBase *markers)
void debug_markers_print_list (ListBase *markers)
static void draw_marker (View2D *v2d, TimeMarker *marker, int cfra, int flag)
void draw_markers_time (const bContext *C, int flag)
static int ed_markers_poll_selected_markers (bContext *C)
static int ed_markers_poll_markers_exist (bContext *C)
static int ed_markers_opwrap_invoke_custom (bContext *C, wmOperator *op, wmEvent *evt, int(*invoke_func)(bContext *, wmOperator *, wmEvent *))
static int ed_markers_opwrap_invoke (bContext *C, wmOperator *op, wmEvent *evt)
static int ed_marker_add (bContext *C, wmOperator *UNUSED(op))
static void MARKER_OT_add (wmOperatorType *ot)
static int ed_marker_move_init (bContext *C, wmOperator *op)
static void ed_marker_move_exit (bContext *C, wmOperator *op)
static int ed_marker_move_invoke (bContext *C, wmOperator *op, wmEvent *evt)
static int ed_marker_move_invoke_wrapper (bContext *C, wmOperator *op, wmEvent *evt)
static void ed_marker_move_apply (wmOperator *op)
static int ed_marker_move_cancel (bContext *C, wmOperator *op)
static int ed_marker_move_modal (bContext *C, wmOperator *op, wmEvent *evt)
static int ed_marker_move_exec (bContext *C, wmOperator *op)
static void MARKER_OT_move (wmOperatorType *ot)
static void ed_marker_duplicate_apply (bContext *C)
static int ed_marker_duplicate_exec (bContext *C, wmOperator *op)
static int ed_marker_duplicate_invoke (bContext *C, wmOperator *op, wmEvent *evt)
static int ed_marker_duplicate_invoke_wrapper (bContext *C, wmOperator *op, wmEvent *evt)
static void MARKER_OT_duplicate (wmOperatorType *ot)
static void select_timeline_marker_frame (ListBase *markers, int frame, unsigned char shift)
static int ed_marker_select (bContext *C, wmEvent *evt, int extend, int camera)
static int ed_marker_select_invoke (bContext *C, wmOperator *op, wmEvent *evt)
static int ed_marker_select_invoke_wrapper (bContext *C, wmOperator *op, wmEvent *evt)
static void MARKER_OT_select (wmOperatorType *ot)
static int ed_marker_border_select_exec (bContext *C, wmOperator *op)
static int ed_marker_select_border_invoke_wrapper (bContext *C, wmOperator *op, wmEvent *evt)
static void MARKER_OT_select_border (wmOperatorType *ot)
static int ed_marker_select_all_exec (bContext *C, wmOperator *op)
static void MARKER_OT_select_all (wmOperatorType *ot)
static int ed_marker_delete_exec (bContext *C, wmOperator *UNUSED(op))
static int ed_marker_delete_invoke_wrapper (bContext *C, wmOperator *op, wmEvent *evt)
static void MARKER_OT_delete (wmOperatorType *ot)
static int ed_marker_rename_exec (bContext *C, wmOperator *op)
static int ed_marker_rename_invoke_wrapper (bContext *C, wmOperator *op, wmEvent *evt)
static void MARKER_OT_rename (wmOperatorType *ot)
static int ed_marker_make_links_scene_exec (bContext *C, wmOperator *op)
static void MARKER_OT_make_links_scene (wmOperatorType *ot)
void ED_operatortypes_marker (void)
void ED_marker_keymap (wmKeyConfig *keyconf)
void ED_marker_keymap_animedit_conflictfree (wmKeyMap *keymap)
Detailed Description
Definition in file anim_markers.c.
Typedef Documentation
typedef struct MarkerMove MarkerMove
Function Documentation
static void add_marker_to_cfra_elem (ListBase * lb, TimeMarker * marker, short only_sel) [static]
Definition at line 264 of file anim_markers.c.
References BLI_addtail(), BLI_insertlinkbefore(), CfraElem::cfra, ListBase::first, TimeMarker::flag, TimeMarker::frame, MEM_callocN(), CfraElem::next, CfraElem::sel, and SELECT.
Referenced by ED_markers_make_cfra_list().
static ListBase* context_get_markers (Scene * scene, ScrArea * sa) [static]
Definition at line 76 of file anim_markers.c.
References SpaceAction::action, ELEM, ListBase::first, SpaceAction::flag, if(), bAction::markers, Scene::markers, SpaceAction::mode, SACTCONT_ACTION, SACTCONT_SHAPEKEY, SACTION_POSEMARKERS_SHOW, SPACE_ACTION, ScrArea::spacedata, and ScrArea::spacetype.
Referenced by ED_animcontext_get_markers(), and ED_context_get_markers().
void debug_markers_print_list (ListBase * markers)
Definition at line 328 of file anim_markers.c.
References ListBase::first, TimeMarker::flag, TimeMarker::frame, TimeMarker::name, TimeMarker::next, and NULL.
static void draw_marker (View2D * v2d, TimeMarker * marker, int cfra, int flag) [static]
Definition at line 349 of file anim_markers.c.
References ACTIVE, TimeMarker::camera, View2D::cur, DRAW_MARKERS_LINES, DRAW_MARKERS_LOCAL, TimeMarker::flag, TimeMarker::frame, View2D::mask, TimeMarker::name, OB_RESTRICT_RENDER, Object::restrictflag, SELECT, setlinestyle(), TH_TEXT, TH_TEXT_HI, UI_DrawString(), UI_icon_draw(), UI_ThemeColor(), UI_view2d_getscale(), rcti::ymax, rctf::ymax, and rcti::ymin.
Referenced by draw_markers_time().
void draw_markers_time (const bContext * C, int flag)
Definition at line 439 of file anim_markers.c.
References RenderData::cfra, CTX_data_scene(), draw_marker(), ED_context_get_markers(), ListBase::first, TimeMarker::flag, TimeMarker::next, NULL, Scene::r, SELECT, and UI_view2d_fromcontext().
Referenced by action_main_area_draw(), draw_timeline_seq(), graph_main_area_draw(), nla_main_area_draw(), and time_main_area_draw().
ListBase* ED_animcontext_get_markers (const bAnimContext * ac)
Definition at line 107 of file anim_markers.c.
References context_get_markers(), NULL, bAnimContext::sa, and bAnimContext::scene.
Referenced by actkeys_select_leftright().
ListBase* ED_context_get_markers (const bContext * C)
Definition at line 101 of file anim_markers.c.
References context_get_markers(), CTX_data_scene(), and CTX_wm_area().
Referenced by act_markers_make_local_exec(), act_markers_make_local_poll(), ANIM_animdata_get_context(), draw_markers_time(), ed_marker_add(), ed_marker_border_select_exec(), ed_marker_delete_exec(), ed_marker_duplicate_apply(), ed_marker_make_links_scene_exec(), ed_marker_move_init(), ed_marker_rename_exec(), ed_marker_rename_invoke_wrapper(), ed_marker_select(), ed_marker_select_all_exec(), ed_markers_poll_markers_exist(), ed_markers_poll_selected_markers(), and special_aftertrans_update().
static int ed_marker_add (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 550 of file anim_markers.c.
References BLI_addtail(), BLI_snprintf(), RenderData::cfra, CTX_data_scene(), ED_context_get_markers(), ListBase::first, TimeMarker::flag, TimeMarker::frame, MEM_callocN(), TimeMarker::name, NC_ANIMATION, NC_SCENE, ND_MARKERS, TimeMarker::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Scene::r, SELECT, and WM_event_add_notifier().
Referenced by MARKER_OT_add().
static int ed_marker_border_select_exec (bContext * C, wmOperator * op) [static]
Definition at line 1142 of file anim_markers.c.
References ED_context_get_markers(), ListBase::first, TimeMarker::flag, TimeMarker::frame, GESTURE_MODAL_DESELECT, GESTURE_MODAL_SELECT, NC_ANIMATION, NC_SCENE, ND_MARKERS, TimeMarker::next, NULL, wmOperator::ptr, RNA_boolean_get(), RNA_int_get(), SELECT, UI_view2d_fromcontext(), UI_view2d_region_to_view(), and WM_event_add_notifier().
Referenced by MARKER_OT_select_border().
static int ed_marker_delete_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1268 of file anim_markers.c.
References BLI_freelinkN(), ED_context_get_markers(), ListBase::first, TimeMarker::flag, NC_ANIMATION, NC_SCENE, ND_MARKERS, TimeMarker::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, SELECT, and WM_event_add_notifier().
Referenced by MARKER_OT_delete().
static int ed_marker_delete_invoke_wrapper (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 1293 of file anim_markers.c.
References ed_markers_opwrap_invoke_custom(), and WM_operator_confirm().
Referenced by MARKER_OT_delete().
static void ed_marker_duplicate_apply (bContext * C) [static]
Definition at line 923 of file anim_markers.c.
References BLI_addhead(), BLI_strncpy(), TimeMarker::camera, ED_context_get_markers(), ListBase::first, TimeMarker::flag, TimeMarker::frame, MEM_callocN(), TimeMarker::name, TimeMarker::next, NULL, and SELECT.
Referenced by ed_marker_duplicate_exec(), and ed_marker_duplicate_invoke().
static int ed_marker_duplicate_exec (bContext * C, wmOperator * op) [static]
Definition at line 956 of file anim_markers.c.
References ed_marker_duplicate_apply(), ed_marker_move_exec(), and OPERATOR_FINISHED.
Referenced by MARKER_OT_duplicate().
static int ed_marker_duplicate_invoke (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 965 of file anim_markers.c.
References ed_marker_duplicate_apply(), and ed_marker_move_invoke().
Referenced by ed_marker_duplicate_invoke_wrapper().
static int ed_marker_duplicate_invoke_wrapper (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 971 of file anim_markers.c.
References ed_marker_duplicate_invoke(), and ed_markers_opwrap_invoke_custom().
Referenced by MARKER_OT_duplicate().
void ED_marker_keymap (wmKeyConfig * keyconf)
Definition at line 1487 of file anim_markers.c.
References AKEY, BKEY, DELKEY, DKEY, EVT_TWEAK_S, FALSE, GKEY, KM_ANY, KM_CTRL, KM_PRESS, KM_SHIFT, MKEY, wmKeyMapItem::ptr, RNA_boolean_set(), SELECTMOUSE, TRUE, WM_keymap_add_item(), WM_keymap_find(), WM_keymap_verify_item(), and XKEY.
Referenced by ED_spacetypes_keymap().
void ED_marker_keymap_animedit_conflictfree (wmKeyMap * keymap)
Definition at line 1524 of file anim_markers.c.
References KM_CTRL, KM_PRESS, MKEY, and WM_keymap_add_item().
Referenced by action_keymap_keyframes(), graphedit_keymap_keyframes(), nla_keymap_main(), and sequencer_keymap().
static int ed_marker_make_links_scene_exec (bContext * C, wmOperator * op) [static]
Definition at line 1369 of file anim_markers.c.
References BKE_report(), BLI_addtail(), BLI_findlink(), CTX_data_main(), CTX_data_scene(), ED_context_get_markers(), ListBase::first, TimeMarker::flag, Scene::markers, MEM_dupallocN(), TimeMarker::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, TimeMarker::prev, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), RPT_ERROR, and SELECT.
Referenced by MARKER_OT_make_links_scene().
static void ed_marker_move_apply (wmOperator * op) [static]
Definition at line 709 of file anim_markers.c.
References wmOperator::customdata, ListBase::first, TimeMarker::flag, TimeMarker::frame, MarkerMove::markers, TimeMarker::next, offs, MarkerMove::oldframe, wmOperator::ptr, RNA_int_get(), and SELECT.
Referenced by ed_marker_move_cancel(), ed_marker_move_exec(), and ed_marker_move_modal().
static int ed_marker_move_cancel (bContext * C, wmOperator * op) [static]
Definition at line 725 of file anim_markers.c.
References ed_marker_move_apply(), ed_marker_move_exit(), NC_ANIMATION, NC_SCENE, ND_MARKERS, NULL, OPERATOR_CANCELLED, wmOperator::ptr, RNA_int_set(), and WM_event_add_notifier().
Referenced by ed_marker_move_modal(), MARKER_OT_duplicate(), and MARKER_OT_move().
static int ed_marker_move_exec (bContext * C, wmOperator * op) [static]
Definition at line 873 of file anim_markers.c.
References ed_marker_move_apply(), ed_marker_move_exit(), ed_marker_move_init(), OPERATOR_FINISHED, and OPERATOR_PASS_THROUGH.
Referenced by ed_marker_duplicate_exec(), and MARKER_OT_move().
static void ed_marker_move_exit (bContext * C, wmOperator * op) [static]
Definition at line 669 of file anim_markers.c.
References CTX_wm_area(), wmOperator::customdata, ED_area_headerprint(), MEM_freeN(), NULL, and MarkerMove::oldframe.
Referenced by ed_marker_move_cancel(), ed_marker_move_exec(), and ed_marker_move_modal().
static int ed_marker_move_init (bContext * C, wmOperator * op) [static]
Definition at line 633 of file anim_markers.c.
References CTX_wm_space_data(), wmOperator::customdata, ED_context_get_markers(), ListBase::first, NumInput::flag, TimeMarker::flag, TimeMarker::frame, NumInput::idx_max, NumInput::increment, initNumInput(), MarkerMove::markers, MEM_callocN(), TimeMarker::next, NULL, MarkerMove::num, NUM_NO_FRACTION, MarkerMove::oldframe, SELECT, and MarkerMove::slink.
Referenced by ed_marker_move_exec(), and ed_marker_move_invoke().
static int ed_marker_move_invoke (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 682 of file anim_markers.c.
References wmOperator::customdata, ed_marker_move_init(), MarkerMove::event_type, MarkerMove::evtx, MarkerMove::firstx, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_int_set(), wmEvent::type, WM_event_add_modal_handler(), and wmEvent::x.
Referenced by ed_marker_duplicate_invoke(), and ed_marker_move_invoke_wrapper().
static int ed_marker_move_invoke_wrapper (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 703 of file anim_markers.c.
References ed_marker_move_invoke(), and ed_markers_opwrap_invoke_custom().
Referenced by MARKER_OT_move().
static int ed_marker_move_modal (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 739 of file anim_markers.c.
References apply_keyb_grid(), applyNumInput(), BLI_snprintf(), wmEvent::ctrl, CTX_data_scene(), CTX_wm_area(), View2D::cur, wmOperator::customdata, ED_area_headerprint(), ed_marker_move_apply(), ed_marker_move_cancel(), ed_marker_move_exit(), ESCKEY, MarkerMove::event_type, MarkerMove::evtx, ListBase::first, MarkerMove::firstx, SpaceAction::flag, SpaceTime::flag, TimeMarker::flag, FPS, FRA2TIME, TimeMarker::frame, handleNumInput(), hasNumInput(), if(), KM_PRESS, LEFTMOUSE, MarkerMove::markers, View2D::mask, MIDDLEMOUSE, MOUSEMOVE, NC_ANIMATION, NC_SCENE, ND_MARKERS, TimeMarker::next, NULL, MarkerMove::num, offs, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, outputNumInput(), PADENTER, wmOperator::ptr, RETKEY, RIGHTMOUSE, RNA_int_set(), SACTION_DRAWTIME, SELECT, wmEvent::shift, MarkerMove::slink, SPACE_ACTION, SPACE_TIME, SpaceLink::spacetype, str, TIME_DRAWFRAMES, wmEvent::type, UI_view2d_fromcontext(), wmEvent::val, WM_event_add_notifier(), WM_modal_tweak_exit(), wmEvent::x, rcti::xmax, rctf::xmax, rcti::xmin, and rctf::xmin.
Referenced by MARKER_OT_duplicate(), and MARKER_OT_move().
static int ed_marker_rename_exec (bContext * C, wmOperator * op) [static]
Definition at line 1319 of file anim_markers.c.
References ED_context_get_markers(), ED_markers_get_first_selected(), TimeMarker::name, NC_ANIMATION, NC_SCENE, ND_MARKERS, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_string_get(), and WM_event_add_notifier().
Referenced by MARKER_OT_rename().
static int ed_marker_rename_invoke_wrapper (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 1336 of file anim_markers.c.
References ED_context_get_markers(), ED_markers_get_first_selected(), ed_markers_opwrap_invoke_custom(), TimeMarker::name, wmOperator::ptr, RNA_string_set(), and WM_operator_props_popup().
Referenced by MARKER_OT_rename().
static int ed_marker_select (bContext * C, wmEvent * evt, int extend, int camera) [static]
Definition at line 1020 of file anim_markers.c.
References TimeMarker::camera, CTX_data_scene(), CTX_wm_region(), ED_base_object_activate(), ED_base_object_select(), ED_context_get_markers(), ED_markers_find_nearest_marker_time(), ListBase::first, TimeMarker::flag, TimeMarker::frame, NC_ANIMATION, NC_SCENE, ND_MARKERS, ND_OB_SELECT, TimeMarker::next, NULL, object_in_scene(), OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, scene_deselect_all(), SELECT, select_timeline_marker_frame(), UI_view2d_fromcontext(), UI_view2d_region_to_view(), ARegion::winrct, WM_event_add_notifier(), wmEvent::x, rcti::xmin, wmEvent::y, and rcti::ymin.
Referenced by ed_marker_select_invoke().
static int ed_marker_select_all_exec (bContext * C, wmOperator * op) [static]
Definition at line 1213 of file anim_markers.c.
References ED_context_get_markers(), ED_markers_get_first_selected(), ListBase::first, TimeMarker::flag, NC_ANIMATION, NC_SCENE, ND_MARKERS, TimeMarker::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, SELECT, and WM_event_add_notifier().
Referenced by MARKER_OT_select_all().
static int ed_marker_select_border_invoke_wrapper (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 1184 of file anim_markers.c.
References ed_markers_opwrap_invoke_custom(), and WM_border_select_invoke().
Referenced by MARKER_OT_select_border().
static int ed_marker_select_invoke (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 1086 of file anim_markers.c.
References ed_marker_select(), wmOperator::ptr, and RNA_boolean_get().
Referenced by ed_marker_select_invoke_wrapper().
static int ed_marker_select_invoke_wrapper (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 1096 of file anim_markers.c.
References ed_marker_select_invoke(), and ed_markers_opwrap_invoke_custom().
Referenced by MARKER_OT_select().
TimeMarker* ED_markers_find_nearest_marker (ListBase * markers, float x) [read]
Definition at line 170 of file anim_markers.c.
References ABS, ListBase::first, TimeMarker::frame, TimeMarker::next, and NULL.
Referenced by ED_markers_find_nearest_marker_time().
int ED_markers_find_nearest_marker_time (ListBase * markers, float x)
Definition at line 190 of file anim_markers.c.
References ED_markers_find_nearest_marker(), and TimeMarker::frame.
Referenced by doAnimEdit_SnapFrame(), ed_marker_select(), flushTransGraphData(), nlaedit_snap_exec(), recalcData_nla(), and snap_bezier_nearmarker().
TimeMarker* ED_markers_get_first_selected (ListBase * markers) [read]
Definition at line 309 of file anim_markers.c.
References ListBase::first, TimeMarker::flag, TimeMarker::next, NULL, and SELECT.
Referenced by act_markers_make_local_poll(), ed_marker_rename_exec(), ed_marker_rename_invoke_wrapper(), ed_marker_select_all_exec(), ed_markers_poll_selected_markers(), mirror_action_keys(), and mirror_graph_keys().
void ED_markers_get_minmax (ListBase * markers, short sel, float * first, float * last)
Definition at line 197 of file anim_markers.c.
References BLI_countlist(), ListBase::first, TimeMarker::flag, TimeMarker::frame, if(), ListBase::last, max, min, TimeMarker::next, NULL, and SELECT.
Referenced by markers_selectkeys_between().
void ED_markers_make_cfra_list (ListBase * markers, ListBase * lb, short only_sel)
Definition at line 295 of file anim_markers.c.
References add_marker_to_cfra_elem(), ListBase::first, TimeMarker::next, and NULL.
Referenced by columnselect_action_keys(), and columnselect_graph_keys().
static int ed_markers_opwrap_invoke (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 542 of file anim_markers.c.
References ed_markers_opwrap_invoke_custom(), and NULL.
Referenced by MARKER_OT_add(), MARKER_OT_make_links_scene(), and MARKER_OT_select_all().
static int ed_markers_opwrap_invoke_custom (bContext * C, wmOperator * op, wmEvent * evt, int(*)(bContext *, wmOperator *, wmEvent *) invoke_func) [static]
Definition at line 511 of file anim_markers.c.
References BKE_report(), CTX_wm_area(), wmOperatorType::exec, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::reports, RPT_ERROR, SPACE_TIME, ScrArea::spacetype, and wmOperator::type.
Referenced by ed_marker_delete_invoke_wrapper(), ed_marker_duplicate_invoke_wrapper(), ed_marker_move_invoke_wrapper(), ed_marker_rename_invoke_wrapper(), ed_marker_select_border_invoke_wrapper(), ed_marker_select_invoke_wrapper(), and ed_markers_opwrap_invoke().
static int ed_markers_poll_markers_exist (bContext * C) [static]
Definition at line 489 of file anim_markers.c.
References ED_context_get_markers(), ED_operator_animview_active(), and ListBase::first.
Referenced by MARKER_OT_select(), MARKER_OT_select_all(), and MARKER_OT_select_border().
static int ed_markers_poll_selected_markers (bContext * C) [static]
Definition at line 476 of file anim_markers.c.
References ED_context_get_markers(), ED_markers_get_first_selected(), ED_operator_animview_active(), and NULL.
Referenced by MARKER_OT_delete(), MARKER_OT_duplicate(), MARKER_OT_make_links_scene(), MARKER_OT_move(), and MARKER_OT_rename().
int ED_markers_post_apply_transform (ListBase * markers, Scene * scene, int mode, float value, char side)
Definition at line 124 of file anim_markers.c.
References CFRA, ListBase::first, TimeMarker::flag, floorf, TimeMarker::frame, TimeMarker::next, NULL, SELECT, TFM_TIME_EXTEND, TFM_TIME_SCALE, and TFM_TIME_TRANSLATE.
Referenced by special_aftertrans_update().
void ED_operatortypes_marker (void)
Definition at line 1470 of file anim_markers.c.
References MARKER_OT_add(), MARKER_OT_delete(), MARKER_OT_duplicate(), MARKER_OT_make_links_scene(), MARKER_OT_move(), MARKER_OT_rename(), MARKER_OT_select(), MARKER_OT_select_all(), MARKER_OT_select_border(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
static void MARKER_OT_add (wmOperatorType * ot) [static]
Definition at line 582 of file anim_markers.c.
References wmOperatorType::description, ed_marker_add(), ed_markers_opwrap_invoke(), ED_operator_animview_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_marker().
static void MARKER_OT_delete (wmOperatorType * ot) [static]
Definition at line 1299 of file anim_markers.c.
References wmOperatorType::description, ed_marker_delete_exec(), ed_marker_delete_invoke_wrapper(), ed_markers_poll_selected_markers(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_marker().
static void MARKER_OT_duplicate (wmOperatorType * ot) [static]
Definition at line 976 of file anim_markers.c.
References wmOperatorType::cancel, wmOperatorType::description, ed_marker_duplicate_exec(), ed_marker_duplicate_invoke_wrapper(), ed_marker_move_cancel(), ed_marker_move_modal(), ed_markers_poll_selected_markers(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_marker().
static void MARKER_OT_make_links_scene (wmOperatorType * ot) [static]
Definition at line 1398 of file anim_markers.c.
References wmOperatorType::description, DummyRNA_NULL_items, ed_marker_make_links_scene_exec(), ed_markers_opwrap_invoke(), ed_markers_poll_selected_markers(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), RNA_scene_itemf(), and wmOperatorType::srna.
Referenced by ED_operatortypes_marker().
static void MARKER_OT_move (wmOperatorType * ot) [static]
Definition at line 883 of file anim_markers.c.
References wmOperatorType::cancel, wmOperatorType::description, ed_marker_move_cancel(), ed_marker_move_exec(), ed_marker_move_invoke_wrapper(), ed_marker_move_modal(), ed_markers_poll_selected_markers(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_marker().
static void MARKER_OT_rename (wmOperatorType * ot) [static]
Definition at line 1347 of file anim_markers.c.
References wmOperatorType::description, ed_marker_rename_exec(), ed_marker_rename_invoke_wrapper(), ed_markers_poll_selected_markers(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_marker().
static void MARKER_OT_select (wmOperatorType * ot) [static]
Definition at line 1101 of file anim_markers.c.
References wmOperatorType::description, ed_marker_select_invoke_wrapper(), ed_markers_poll_markers_exist(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_marker().
static void MARKER_OT_select_all (wmOperatorType * ot) [static]
Definition at line 1246 of file anim_markers.c.
References wmOperatorType::description, ed_marker_select_all_exec(), ed_markers_opwrap_invoke(), ed_markers_poll_markers_exist(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_properties_select_all().
Referenced by ED_operatortypes_marker().
static void MARKER_OT_select_border (wmOperatorType * ot) [static]
Definition at line 1189 of file anim_markers.c.
References wmOperatorType::cancel, wmOperatorType::description, ed_marker_border_select_exec(), ed_marker_select_border_invoke_wrapper(), ed_markers_poll_markers_exist(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, TRUE, WM_border_select_cancel(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by ED_operatortypes_marker().
static void select_timeline_marker_frame (ListBase * markers, int frame, unsigned char shift) [static]
Definition at line 1000 of file anim_markers.c.
References ListBase::first, TimeMarker::flag, TimeMarker::frame, TimeMarker::next, and SELECT.
Referenced by ed_marker_select().