Blender: script_intern.h File Reference
script_intern.h File Reference
script space
Functions
void script_operatortypes (void)
void script_keymap (struct wmKeyConfig *keyconf)
void SCRIPT_OT_reload (struct wmOperatorType *ot)
void SCRIPT_OT_python_file_run (struct wmOperatorType *ot)
Detailed Description
Definition in file script_intern.h.
Function Documentation
void script_keymap (struct wmKeyConfig * keyconf)
Definition at line 61 of file script_ops.c.
References KM_ALT, KM_CTRL, KM_PRESS, KM_SHIFT, PKEY, RNA_string_set(), SPACE_SCRIPT, WM_keymap_add_item(), and WM_keymap_find().
Referenced by ED_spacetype_script().
void script_operatortypes (void)
Definition at line 55 of file script_ops.c.
References SCRIPT_OT_python_file_run(), SCRIPT_OT_reload(), and WM_operatortype_append().
Referenced by ED_spacetype_script().
void SCRIPT_OT_python_file_run (struct wmOperatorType * ot)
Definition at line 71 of file script_edit.c.
References wmOperatorType::description, ED_operator_areaactive(), wmOperatorType::exec, FILE_MAX, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string_file_path(), run_pyfile_exec(), and wmOperatorType::srna.
Referenced by script_operatortypes().
void SCRIPT_OT_reload (struct wmOperatorType * ot)
Definition at line 103 of file script_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and script_reload_exec().
Referenced by script_operatortypes().