Blender: MT_Vector2.inl File Reference
MT_Vector2.inl File Reference
#include "MT_Optimize.h"
Functions
GEN_INLINE MT_Vector2 operator+ (const MT_Vector2 &v1, const MT_Vector2 &v2)
GEN_INLINE MT_Vector2 operator- (const MT_Vector2 &v1, const MT_Vector2 &v2)
GEN_INLINE MT_Vector2 operator- (const MT_Vector2 &v)
GEN_INLINE MT_Vector2 operator* (const MT_Vector2 &v, MT_Scalar s)
GEN_INLINE MT_Vector2 operator* (MT_Scalar s, const MT_Vector2 &v)
GEN_INLINE MT_Vector2 operator/ (const MT_Vector2 &v, MT_Scalar s)
GEN_INLINE MT_Scalar MT_dot (const MT_Vector2 &v1, const MT_Vector2 &v2)
GEN_INLINE MT_Scalar MT_length2 (const MT_Vector2 &v)
GEN_INLINE MT_Scalar MT_length (const MT_Vector2 &v)
GEN_INLINE bool MT_fuzzyZero (const MT_Vector2 &v)
GEN_INLINE bool MT_fuzzyEqual (const MT_Vector2 &v1, const MT_Vector2 &v2)
GEN_INLINE MT_Scalar MT_angle (const MT_Vector2 &v1, const MT_Vector2 &v2)
Function Documentation
GEN_INLINE MT_Scalar MT_angle (const MT_Vector2 & v1, const MT_Vector2 & v2)
Definition at line 89 of file MT_Vector2.inl.
References MT_Vector2::angle().
GEN_INLINE MT_Scalar MT_dot (const MT_Vector2 & v1, const MT_Vector2 & v2)
Definition at line 77 of file MT_Vector2.inl.
References MT_Vector2::dot().
Referenced by RAS_MeshObject::polygonSlot::get(), MT_Matrix3x3::inverse(), MT_Transform::invert(), MT_Vector4::length2(), MT_Transform::operator()(), operator*(), RAS_BucketManager::sortedmeshslot::set(), sweepCircleCircle(), and sweepCircleSegment().
GEN_INLINE bool MT_fuzzyEqual (const MT_Vector2 & v1, const MT_Vector2 & v2)
Definition at line 85 of file MT_Vector2.inl.
References MT_fuzzyZero().
Referenced by RAS_TexVert::closeTo().
GEN_INLINE bool MT_fuzzyZero (const MT_Vector2 & v)
Definition at line 84 of file MT_Vector2.inl.
References MT_Vector2::fuzzyZero().
GEN_INLINE MT_Scalar MT_length (const MT_Vector2 & v)
Definition at line 82 of file MT_Vector2.inl.
References MT_Vector2::length().
GEN_INLINE MT_Scalar MT_length2 (const MT_Vector2 & v)
Definition at line 81 of file MT_Vector2.inl.
References MT_Vector2::length2().
GEN_INLINE MT_Vector2 operator* (MT_Scalar s, const MT_Vector2 & v)
Definition at line 39 of file MT_Vector2.inl.
GEN_INLINE MT_Vector2 operator* (const MT_Vector2 & v, MT_Scalar s)
Definition at line 35 of file MT_Vector2.inl.
GEN_INLINE MT_Vector2 operator+ (const MT_Vector2 & v1, const MT_Vector2 & v2)
Definition at line 23 of file MT_Vector2.inl.
GEN_INLINE MT_Vector2 operator- (const MT_Vector2 & v1, const MT_Vector2 & v2)
Definition at line 27 of file MT_Vector2.inl.
GEN_INLINE MT_Vector2 operator- (const MT_Vector2 & v)
Definition at line 31 of file MT_Vector2.inl.
GEN_INLINE MT_Vector2 operator/ (const MT_Vector2 & v, MT_Scalar s)
Definition at line 41 of file MT_Vector2.inl.
References MT_assert, and MT_fuzzyZero().