Blender: object_vgroup.c File Reference
object_vgroup.c File Reference
object
#include <string.h>
#include <stddef.h>
#include <math.h>
#include <assert.h>
#include "MEM_guardedalloc.h"
#include "DNA_cloth_types.h"
#include "DNA_curve_types.h"
#include "DNA_lattice_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_mesh_types.h"
#include "DNA_modifier_types.h"
#include "DNA_object_types.h"
#include "DNA_object_force.h"
#include "DNA_scene_types.h"
#include "DNA_particle_types.h"
#include "BLI_array.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_customdata.h"
#include "BKE_deform.h"
#include "BKE_depsgraph.h"
#include "BKE_global.h"
#include "BKE_mesh.h"
#include "BKE_tessmesh.h"
#include "BKE_report.h"
#include "BKE_DerivedMesh.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_object.h"
#include "ED_mesh.h"
#include "UI_resources.h"
#include "object_intern.h"
Defines
#define VGROUP_MIRR_OP
Functions
static void vgroup_remap_update_users (Object *ob, int *map)
static void vgroup_delete_edit_mode (Object *ob, bDeformGroup *defgroup)
static void vgroup_delete_object_mode (Object *ob, bDeformGroup *dg)
static void vgroup_delete_all (Object *ob)
static Lattice * vgroup_edit_lattice (Object *ob)
int ED_vgroup_object_is_edit_mode (Object *ob)
bDeformGroup * ED_vgroup_add_name (Object *ob, const char *name)
bDeformGroup * ED_vgroup_add (Object *ob)
void ED_vgroup_delete (Object *ob, bDeformGroup *defgroup)
void ED_vgroup_clear (Object *ob)
int ED_vgroup_data_create (ID *id)
static int ED_vgroup_give_parray (ID *id, MDeformVert ***dvert_arr, int *dvert_tot, const short use_vert_sel)
int ED_vgroup_give_array (ID *id, MDeformVert **dvert_arr, int *dvert_tot)
int ED_vgroup_copy_array (Object *ob, Object *ob_from)
static void ED_vgroup_nr_vert_add (Object *ob, const int def_nr, const int vertnum, const float weight, const int assignmode)
void ED_vgroup_vert_add (Object *ob, bDeformGroup *dg, int vertnum, float weight, int assignmode)
void ED_vgroup_vert_remove (Object *ob, bDeformGroup *dg, int vertnum)
static float get_vert_def_nr (Object *ob, const int def_nr, const int vertnum)
float ED_vgroup_vert_weight (Object *ob, bDeformGroup *dg, int vertnum)
void ED_vgroup_select_by_name (Object *ob, const char *name)
static void vgroup_select_verts (Object *ob, int select)
static void vgroup_duplicate (Object *ob)
static void vgroup_normalize (Object *ob)
static int * getSurroundingVerts (Mesh *me, int vert, int *count)
static void getSingleCoordinate (MVert *points, int count, float coord[3])
static void getVerticalAndHorizontalChange (const float norm[3], float d, const float coord[3], const float start[3], float distToStart, float *end, float(*changes)[2], float *dists, int index)
static void dm_deform_clear (DerivedMesh *dm, Object *ob)
static DerivedMesh * dm_deform_recalc (Scene *scene, Object *ob)
static void moveCloserToDistanceFromPlane (Scene *scene, Object *ob, Mesh *me, int index, float norm[3], float coord[3], float d, float distToBe, float strength, float cp)
static void vgroup_fix (Scene *scene, Object *ob, float distToBe, float strength, float cp)
static void vgroup_levels (Object *ob, float offset, float gain)
static void vgroup_normalize_all (Object *ob, int lock_active)
static void vgroup_lock_all (Object *ob, int action)
static void vgroup_invert (Object *ob, const short auto_assign, const short auto_remove)
static void vgroup_blend (Object *ob, const float fac)
static void vgroup_clean (Object *ob, const float epsilon, int keep_single)
static void vgroup_clean_all (Object *ob, const float epsilon, const int keep_single)
static void dvert_mirror_op (MDeformVert *dvert, MDeformVert *dvert_mirr, const char sel, const char sel_mirr, const int *flip_map, const int flip_map_len, const short mirror_weights, const short flip_vgroups, const short all_vgroups, const int act_vgroup)
void ED_vgroup_mirror (Object *ob, const short mirror_weights, const short flip_vgroups, const short all_vgroups)
static void vgroup_delete_update_users (Object *ob, int id)
static void vgroup_active_remove_verts (Object *ob, const int allverts, bDeformGroup *dg)
static int vgroup_object_in_edit_mode (Object *ob)
static int vgroup_object_in_wpaint_vert_select (Object *ob)
static void vgroup_delete (Object *ob)
static void vgroup_assign_verts (Object *ob, const float weight)
static void vgroup_remove_verts (Object *ob, int allverts)
static int vertex_group_poll (bContext *C)
static int UNUSED_FUNCTION() vertex_group_poll_edit (bContext *C)
static int vertex_group_poll_edit_or_wpaint_vert_select (bContext *C)
static int vertex_group_add_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_vertex_group_add (wmOperatorType *ot)
static int vertex_group_remove_exec (bContext *C, wmOperator *op)
void OBJECT_OT_vertex_group_remove (wmOperatorType *ot)
static int vertex_group_assign_exec (bContext *C, wmOperator *op)
void OBJECT_OT_vertex_group_assign (wmOperatorType *ot)
static int vertex_group_remove_from_exec (bContext *C, wmOperator *op)
void OBJECT_OT_vertex_group_remove_from (wmOperatorType *ot)
static int vertex_group_select_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_vertex_group_select (wmOperatorType *ot)
static int vertex_group_deselect_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_vertex_group_deselect (wmOperatorType *ot)
static int vertex_group_copy_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_vertex_group_copy (wmOperatorType *ot)
static int vertex_group_levels_exec (bContext *C, wmOperator *op)
void OBJECT_OT_vertex_group_levels (wmOperatorType *ot)
static int vertex_group_normalize_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_vertex_group_normalize (wmOperatorType *ot)
static int vertex_group_normalize_all_exec (bContext *C, wmOperator *op)
void OBJECT_OT_vertex_group_normalize_all (wmOperatorType *ot)
static int vertex_group_fix_exec (bContext *C, wmOperator *op)
void OBJECT_OT_vertex_group_fix (wmOperatorType *ot)
static int vertex_group_lock_exec (bContext *C, wmOperator *op)
void OBJECT_OT_vertex_group_lock (wmOperatorType *ot)
static int vertex_group_invert_exec (bContext *C, wmOperator *op)
void OBJECT_OT_vertex_group_invert (wmOperatorType *ot)
static int vertex_group_blend_exec (bContext *C, wmOperator *op)
static int vertex_group_blend_poll (bContext *C)
void OBJECT_OT_vertex_group_blend (wmOperatorType *ot)
static int vertex_group_clean_exec (bContext *C, wmOperator *op)
void OBJECT_OT_vertex_group_clean (wmOperatorType *ot)
static int vertex_group_mirror_exec (bContext *C, wmOperator *op)
void OBJECT_OT_vertex_group_mirror (wmOperatorType *ot)
static int vertex_group_copy_to_linked_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_vertex_group_copy_to_linked (wmOperatorType *ot)
static int vertex_group_copy_to_selected_exec (bContext *C, wmOperator *op)
void OBJECT_OT_vertex_group_copy_to_selected (wmOperatorType *ot)
static int set_active_group_exec (bContext *C, wmOperator *op)
static EnumPropertyItem * vgroup_itemf (bContext *C, PointerRNA *UNUSED(ptr), PropertyRNA *UNUSED(prop), int *free)
void OBJECT_OT_vertex_group_set_active (wmOperatorType *ot)
static char * vgroup_init_remap (Object *ob)
static int vgroup_do_remap (Object *ob, char *name_array, wmOperator *op)
static int vgroup_sort (void *def_a_ptr, void *def_b_ptr)
static int vertex_group_sort_exec (bContext *C, wmOperator *op)
void OBJECT_OT_vertex_group_sort (wmOperatorType *ot)
static int vgroup_move_exec (bContext *C, wmOperator *op)
void OBJECT_OT_vertex_group_move (wmOperatorType *ot)
Variables
static EnumPropertyItem vgroup_items []
Detailed Description
Definition in file object_vgroup.c.
Define Documentation
#define VGROUP_MIRR_OP
Value:
dvert_mirror_op(dvert, dvert_mirr,                                    \
                        sel, sel_mirr,                                        \
                        flip_map, flip_map_len,                               \
                        mirror_weights, flip_vgroups,                         \
                        all_vgroups, def_nr                                   \
                        )
Referenced by ED_vgroup_mirror().
Function Documentation
static void dm_deform_clear (DerivedMesh * dm, Object * ob) [static]
Definition at line 854 of file object_vgroup.c.
References Object::derivedDeform, DerivedMesh::needsFree, NULL, and DerivedMesh::release.
Referenced by moveCloserToDistanceFromPlane().
static DerivedMesh* dm_deform_recalc (Scene * scene, Object * ob) [static]
Definition at line 868 of file object_vgroup.c.
References CD_MASK_BAREMESH, and mesh_get_derived_deform().
Referenced by moveCloserToDistanceFromPlane().
static void dvert_mirror_op (MDeformVert * dvert, MDeformVert * dvert_mirr, const char sel, const char sel_mirr, const int * flip_map, const int flip_map_len, const short mirror_weights, const short flip_vgroups, const short all_vgroups, const int act_vgroup) [static]
Definition at line 1462 of file object_vgroup.c.
References BLI_assert, defvert_copy(), defvert_copy_index(), defvert_find_index(), defvert_flip(), defvert_verify_index(), NULL, SWAP, and MDeformWeight::weight.
bDeformGroup* ED_vgroup_add (Object * ob) [read]
Definition at line 121 of file object_vgroup.c.
References ED_vgroup_add_name().
Referenced by vertex_group_add_exec(), vertex_group_assign_exec(), and wpaint_stroke_test_start().
bDeformGroup* ED_vgroup_add_name (Object * ob, const char * name) [read]
Definition at line 102 of file object_vgroup.c.
References Object::actdef, BLI_addtail(), BLI_countlist(), BLI_strncpy(), Object::defbase, defgroup_unique_name(), MEM_callocN(), bDeformGroup::name, NULL, OB_TYPE_SUPPORT_VGROUP, and Object::type.
Referenced by dgroup_skinnable_cb(), ED_vgroup_add(), SkinInfo::link_armature(), output_toggle_exec(), vgroup_add_unique_bone_cb(), wpaint_mirror_vgroup_ensure(), and wpaint_stroke_test_start().
void ED_vgroup_clear (Object * ob)
Definition at line 145 of file object_vgroup.c.
References Object::defbase, ED_vgroup_object_is_edit_mode(), ListBase::first, bDeformGroup::next, vgroup_delete_edit_mode(), and vgroup_delete_object_mode().
int ED_vgroup_copy_array (Object * ob, Object * ob_from)
Definition at line 315 of file object_vgroup.c.
References Object::actdef, BLI_countlist(), BLI_duplicatelist(), BLI_freelistN(), Object::data, Object::defbase, ED_vgroup_data_create(), ED_vgroup_give_parray(), FALSE, i, MEM_dupallocN(), MEM_freeN(), MEM_mallocN(), NULL, TRUE, vgroup_delete_all(), and vgroup_remap_update_users().
Referenced by vertex_group_copy_to_selected_exec().
int ED_vgroup_data_create (ID * id)
Definition at line 162 of file object_vgroup.c.
References CD_CALLOC, CD_MDEFORMVERT, CustomData_add_layer(), Lattice::dvert, Mesh::dvert, FALSE, GS, ID_LT, ID_ME, MEM_callocN(), ID::name, NULL, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, Mesh::totvert, and TRUE.
Referenced by create_vgroups_from_armature(), ED_vgroup_copy_array(), ED_vgroup_vert_add(), vgroup_active_remove_verts(), vgroup_assign_verts(), and wpaint_stroke_test_start().
void ED_vgroup_delete (Object * ob, bDeformGroup * defgroup)
Definition at line 126 of file object_vgroup.c.
References Object::defbase, ED_vgroup_object_is_edit_mode(), ListBase::first, bDeformGroup::next, NULL, vgroup_delete_edit_mode(), and vgroup_delete_object_mode().
Referenced by output_toggle_exec().
int ED_vgroup_give_array (ID * id, MDeformVert ** dvert_arr, int * dvert_tot)
Definition at line 287 of file object_vgroup.c.
References Lattice::dvert, Mesh::dvert, Lattice::editlatt, FALSE, GS, ID_LT, ID_ME, EditLatt::latt, ID::name, NULL, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, Mesh::totvert, and TRUE.
Referenced by ED_vgroup_nr_vert_add(), ED_vgroup_vert_add(), ED_vgroup_vert_remove(), vgroup_delete_object_mode(), and vgroup_do_remap().
static int ED_vgroup_give_parray (ID * id, MDeformVert *** dvert_arr, int * dvert_tot, const short use_vert_sel) [static]
Definition at line 181 of file object_vgroup.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, CD_MDEFORMVERT, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, Lattice::def, Lattice::dvert, Mesh::dvert, Mesh::edit_btmesh, Lattice::editlatt, BPoint::f1, MVert::flag, GS, BMVert::head, i, ID_LT, ID_ME, if(), EditLatt::latt, MEM_mallocN(), Mesh::mvert, ID::name, NULL, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, SELECT, Mesh::totvert, BMesh::totvert, and BMesh::vdata.
Referenced by ED_vgroup_copy_array(), vgroup_clean(), vgroup_clean_all(), vgroup_duplicate(), vgroup_invert(), vgroup_levels(), vgroup_normalize(), and vgroup_normalize_all().
void ED_vgroup_mirror (Object * ob, const short mirror_weights, const short flip_vgroups, const short all_vgroups)
Definition at line 1520 of file object_vgroup.c.
References Object::actdef, BLI_assert, BLI_findlink(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, CD_MDEFORMVERT, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, Object::data, Lattice::def, Object::defbase, defgroup_flip_map(), defgroup_flip_map_single(), Lattice::dvert, Mesh::dvert, EDBM_verts_mirror_cache_begin(), EDBM_verts_mirror_cache_clear(), EDBM_verts_mirror_cache_end(), EDBM_verts_mirror_get(), Mesh::edit_btmesh, Mesh::editflag, BPoint::f1, FALSE, MVert::flag, BMVert::head, LT_INDEX, ME_EDIT_VERT_SEL, ME_VERT_TMP_TAG, MEM_freeN(), mesh_get_x_mirror_vert(), Mesh::mvert, NULL, OB_LATTICE, OB_MESH, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, SELECT, TRUE, Object::type, BMesh::vdata, vgroup_edit_lattice(), and VGROUP_MIRR_OP.
Referenced by do_view3d_vgroup_buttons(), and vertex_group_mirror_exec().
static void ED_vgroup_nr_vert_add (Object * ob, const int def_nr, const int vertnum, const float weight, const int assignmode) [static]
Definition at line 382 of file object_vgroup.c.
References Object::data, defvert_add_index_notest(), defvert_find_index(), defvert_remove_group(), ED_vgroup_give_array(), NULL, MDeformWeight::weight, WEIGHT_ADD, WEIGHT_REPLACE, and WEIGHT_SUBTRACT.
Referenced by ED_vgroup_vert_add().
int ED_vgroup_object_is_edit_mode (Object * ob)
Definition at line 92 of file object_vgroup.c.
References BMEdit_FromObject(), Object::data, NULL, OB_LATTICE, OB_MESH, and Object::type.
Referenced by ED_vgroup_clear(), and ED_vgroup_delete().
void ED_vgroup_select_by_name (Object * ob, const char * name)
Definition at line 571 of file object_vgroup.c.
References Object::actdef, and defgroup_name_index().
Referenced by ED_do_pose_selectbuffer(), pose_bone_flip_active_exec(), and set_wpaint().
void ED_vgroup_vert_add (Object * ob, bDeformGroup * dg, int vertnum, float weight, int assignmode)
Definition at line 461 of file object_vgroup.c.
References BLI_findindex(), Object::data, Object::defbase, ED_vgroup_data_create(), ED_vgroup_give_array(), ED_vgroup_nr_vert_add(), and NULL.
Referenced by envelope_bone_weighting(), heat_bone_weighting(), and SkinInfo::link_armature().
void ED_vgroup_vert_remove (Object * ob, bDeformGroup * dg, int vertnum)
Definition at line 487 of file object_vgroup.c.
References BLI_findindex(), Object::data, Object::defbase, defvert_find_index(), defvert_remove_group(), ED_vgroup_give_array(), and NULL.
Referenced by envelope_bone_weighting(), and heat_bone_weighting().
float ED_vgroup_vert_weight (Object * ob, bDeformGroup * dg, int vertnum)
Definition at line 560 of file object_vgroup.c.
References BLI_findindex(), Object::defbase, and get_vert_def_nr().
Referenced by heat_bone_weighting().
static float get_vert_def_nr (Object * ob, const int def_nr, const int vertnum) [static]
Definition at line 515 of file object_vgroup.c.
References BMEditMesh::bm, BM_vert_at_index(), CD_MDEFORMVERT, CustomData_bmesh_get(), BMHeader::data, Object::data, defvert_find_index(), Lattice::dvert, Mesh::dvert, Mesh::edit_btmesh, BMVert::head, NULL, OB_LATTICE, OB_MESH, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, Mesh::totvert, Object::type, BMesh::vdata, vgroup_edit_lattice(), and MDeformWeight::weight.
Referenced by ED_vgroup_vert_weight().
static void getSingleCoordinate (MVert * points, int count, float coord[3]) [static]
Definition at line 819 of file object_vgroup.c.
References add_v3_v3(), co, i, mul_v3_fl(), and zero_v3().
Referenced by vgroup_fix().
static int* getSurroundingVerts (Mesh * me, int vert, int * count) [static]
Definition at line 754 of file object_vgroup.c.
References BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_reserve, i, MPoly::loopstart, Mesh::mloop, Mesh::mpoly, NULL, MPoly::totloop, Mesh::totpoly, and MLoop::v.
Referenced by vgroup_fix().
static void getVerticalAndHorizontalChange (const float norm[3], float d, const float coord[3], const float start[3], float distToStart, float * end, float(*) changes[2], float * dists, int index) [static]
Definition at line 833 of file object_vgroup.c.
References closest_to_plane_v3(), dot_v3v3(), and len_v3v3().
Referenced by moveCloserToDistanceFromPlane().
static void moveCloserToDistanceFromPlane (Scene * scene, Object * ob, Mesh * me, int index, float norm[3], float coord[3], float d, float distToBe, float strength, float cp) [static]
Definition at line 882 of file object_vgroup.c.
References MVert::co, copy_v3_v3(), dm_deform_clear(), dm_deform_recalc(), dot_v3v3(), Mesh::dvert, MDeformVert::dw, fabs(), fabsf, FALSE, DerivedMesh::getVert, getVerticalAndHorizontalChange(), i, MEM_callocN(), MEM_freeN(), MEM_mallocN(), NULL, MDeformVert::totweight, TRUE, and MDeformWeight::weight.
Referenced by vgroup_fix().
void OBJECT_OT_vertex_group_add (wmOperatorType * ot)
Definition at line 2119 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_add_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_assign (wmOperatorType * ot)
Definition at line 2184 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, vertex_group_assign_exec(), and vertex_group_poll_edit_or_wpaint_vert_select().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_blend (wmOperatorType * ot)
Definition at line 2568 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_FACTOR, PROP_FLOAT, RNA_def_property(), RNA_def_property_float_default(), RNA_def_property_range(), RNA_def_property_ui_text(), wmOperatorType::srna, vertex_group_blend_exec(), and vertex_group_blend_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_clean (wmOperatorType * ot)
Definition at line 2609 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float(), wmOperatorType::srna, vertex_group_clean_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_copy (wmOperatorType * ot)
Definition at line 2309 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_copy_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_copy_to_linked (wmOperatorType * ot)
Definition at line 2694 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_copy_to_linked_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_copy_to_selected (wmOperatorType * ot)
Definition at line 2734 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_copy_to_selected_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_deselect (wmOperatorType * ot)
Definition at line 2283 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_deselect_exec(), and vertex_group_poll_edit_or_wpaint_vert_select().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_fix (wmOperatorType * ot)
Definition at line 2444 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), wmOperatorType::srna, vertex_group_fix_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_invert (wmOperatorType * ot)
Definition at line 2507 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, TRUE, vertex_group_invert_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_levels (wmOperatorType * ot)
Definition at line 2339 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), wmOperatorType::srna, vertex_group_levels_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_lock (wmOperatorType * ot)
Definition at line 2477 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_lock_exec(), vertex_group_poll(), and WM_operator_properties_select_all().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_mirror (wmOperatorType * ot)
Definition at line 2646 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, TRUE, vertex_group_mirror_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_move (wmOperatorType * ot)
Definition at line 2986 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, vertex_group_poll(), and vgroup_move_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_normalize (wmOperatorType * ot)
Definition at line 2369 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_normalize_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_normalize_all (wmOperatorType * ot)
Definition at line 2397 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, TRUE, vertex_group_normalize_all_exec(), and vertex_group_poll().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_remove (wmOperatorType * ot)
Definition at line 2149 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, vertex_group_poll(), and vertex_group_remove_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_remove_from (wmOperatorType * ot)
Definition at line 2226 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, vertex_group_poll_edit_or_wpaint_vert_select(), and vertex_group_remove_from_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_select (wmOperatorType * ot)
Definition at line 2259 of file object_vgroup.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_poll_edit_or_wpaint_vert_select(), and vertex_group_select_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_set_active (wmOperatorType * ot)
Definition at line 2791 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), set_active_group_exec(), wmOperatorType::srna, vertex_group_poll(), vgroup_itemf(), and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_group_sort (wmOperatorType * ot)
Definition at line 2933 of file object_vgroup.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_group_poll(), and vertex_group_sort_exec().
Referenced by ED_operatortypes_object().
static int set_active_group_exec (bContext * C, wmOperator * op) [static]
Definition at line 2752 of file object_vgroup.c.
References Object::actdef, BLI_assert, DAG_id_tag_update(), ED_object_context(), Object::id, NC_GEOM, ND_DATA, OB_RECALC_DATA, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_set_active().
static int vertex_group_add_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2107 of file object_vgroup.c.
References DAG_id_tag_update(), Object::data, ED_object_context(), ED_vgroup_add(), Object::id, NC_GEOM, NC_OBJECT, ND_DATA, ND_DRAW, OB_RECALC_DATA, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_add().
static int vertex_group_assign_exec (bContext * C, wmOperator * op) [static]
Definition at line 2169 of file object_vgroup.c.
References CTX_data_tool_settings(), DAG_id_tag_update(), Object::data, ED_object_context(), ED_vgroup_add(), Object::id, NC_GEOM, ND_DATA, OB_RECALC_DATA, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), vgroup_assign_verts(), ToolSettings::vgroup_weight, and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_assign().
static int vertex_group_blend_exec (bContext * C, wmOperator * op) [static]
Definition at line 2527 of file object_vgroup.c.
References DAG_id_tag_update(), Object::data, ED_object_context(), Object::id, NC_GEOM, NC_OBJECT, ND_DATA, ND_DRAW, OB_RECALC_DATA, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get(), vgroup_blend(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_blend().
static int vertex_group_blend_poll (bContext * C) [static]
Definition at line 2542 of file object_vgroup.c.
References CTX_wm_operator_poll_msg_set(), Object::data, data, ED_object_context(), FALSE, Object::id, if(), ID::lib, ME_EDIT_PAINT_SEL_MODE, Object::mode, NULL, OB_MESH, OB_MODE_WEIGHT_PAINT, SCE_SELECT_VERTEX, TRUE, Object::type, and vgroup_object_in_edit_mode().
Referenced by OBJECT_OT_vertex_group_blend().
static int vertex_group_clean_exec (bContext * C, wmOperator * op) [static]
Definition at line 2591 of file object_vgroup.c.
References DAG_id_tag_update(), Object::data, ED_object_context(), Object::id, NC_GEOM, NC_OBJECT, ND_DATA, ND_DRAW, OB_RECALC_DATA, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_float_get(), vgroup_clean(), vgroup_clean_all(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_clean().
static int vertex_group_copy_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2297 of file object_vgroup.c.
References DAG_id_tag_update(), Object::data, ED_object_context(), Object::id, NC_GEOM, NC_OBJECT, ND_DATA, ND_DRAW, OB_RECALC_DATA, OPERATOR_FINISHED, vgroup_duplicate(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_copy().
static int vertex_group_copy_to_linked_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2668 of file object_vgroup.c.
References Object::actdef, Scene::base, BLI_duplicatelist(), BLI_freelistN(), CTX_data_scene(), DAG_id_tag_update(), Object::data, Object::defbase, ED_object_context(), ListBase::first, Object::id, NC_GEOM, NC_OBJECT, ND_DATA, ND_DRAW, Base::next, OB_RECALC_DATA, Base::object, OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::type, and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_copy_to_linked().
static int vertex_group_copy_to_selected_exec (bContext * C, wmOperator * op) [static]
Definition at line 2709 of file object_vgroup.c.
References BKE_reportf(), CTX_DATA_BEGIN, CTX_DATA_END, ED_object_context(), ED_vgroup_copy_array(), OPERATOR_FINISHED, wmOperator::reports, and RPT_ERROR.
Referenced by OBJECT_OT_vertex_group_copy_to_selected().
static int vertex_group_deselect_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2273 of file object_vgroup.c.
References Object::data, ED_object_context(), NC_GEOM, ND_SELECT, OPERATOR_FINISHED, vgroup_select_verts(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_deselect().
static int vertex_group_fix_exec (bContext * C, wmOperator * op) [static]
Definition at line 2414 of file object_vgroup.c.
References BKE_report(), CTX_data_active_object(), CTX_data_scene(), DAG_id_tag_update(), Object::data, eModifierMode_Realtime, eModifierType_Mirror, ListBase::first, Object::id, ModifierData::mode, Object::modifiers, NC_GEOM, NC_OBJECT, ND_DATA, ND_DRAW, ModifierData::next, OB_RECALC_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_float_get(), RPT_ERROR_INVALID_CONTEXT, ModifierData::type, vgroup_fix(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_fix().
static int vertex_group_invert_exec (bContext * C, wmOperator * op) [static]
Definition at line 2493 of file object_vgroup.c.
References DAG_id_tag_update(), Object::data, ED_object_context(), Object::id, NC_GEOM, NC_OBJECT, ND_DATA, ND_DRAW, OB_RECALC_DATA, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), vgroup_invert(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_invert().
static int vertex_group_levels_exec (bContext * C, wmOperator * op) [static]
Definition at line 2323 of file object_vgroup.c.
References DAG_id_tag_update(), Object::data, ED_object_context(), Object::id, NC_GEOM, NC_OBJECT, ND_DATA, ND_DRAW, OB_RECALC_DATA, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get(), vgroup_levels(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_levels().
static int vertex_group_lock_exec (bContext * C, wmOperator * op) [static]
Definition at line 2466 of file object_vgroup.c.
References CTX_data_active_object(), OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), and vgroup_lock_all().
Referenced by OBJECT_OT_vertex_group_lock().
static int vertex_group_mirror_exec (bContext * C, wmOperator * op) [static]
Definition at line 2630 of file object_vgroup.c.
References DAG_id_tag_update(), Object::data, ED_object_context(), ED_vgroup_mirror(), Object::id, NC_GEOM, NC_OBJECT, ND_DATA, ND_DRAW, OB_RECALC_DATA, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_mirror().
static int vertex_group_normalize_all_exec (bContext * C, wmOperator * op) [static]
Definition at line 2383 of file object_vgroup.c.
References DAG_id_tag_update(), Object::data, ED_object_context(), Object::id, NC_GEOM, NC_OBJECT, ND_DATA, ND_DRAW, OB_RECALC_DATA, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), vgroup_normalize_all(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_normalize_all().
static int vertex_group_normalize_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2356 of file object_vgroup.c.
References DAG_id_tag_update(), Object::data, ED_object_context(), Object::id, NC_GEOM, NC_OBJECT, ND_DATA, ND_DRAW, OB_RECALC_DATA, OPERATOR_FINISHED, vgroup_normalize(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_normalize().
static int vertex_group_poll (bContext * C) [static]
Definition at line 2076 of file object_vgroup.c.
References Object::data, data, ED_object_context(), Object::id, ID::lib, NULL, OB_TYPE_SUPPORT_VGROUP, and Object::type.
Referenced by OBJECT_OT_vertex_group_add(), OBJECT_OT_vertex_group_clean(), OBJECT_OT_vertex_group_copy(), OBJECT_OT_vertex_group_copy_to_linked(), OBJECT_OT_vertex_group_copy_to_selected(), OBJECT_OT_vertex_group_fix(), OBJECT_OT_vertex_group_invert(), OBJECT_OT_vertex_group_levels(), OBJECT_OT_vertex_group_lock(), OBJECT_OT_vertex_group_mirror(), OBJECT_OT_vertex_group_move(), OBJECT_OT_vertex_group_normalize(), OBJECT_OT_vertex_group_normalize_all(), OBJECT_OT_vertex_group_remove(), OBJECT_OT_vertex_group_set_active(), and OBJECT_OT_vertex_group_sort().
static int UNUSED_FUNCTION() vertex_group_poll_edit (bContext * C) [static]
Definition at line 2083 of file object_vgroup.c.
References C, Object::data, data, ED_object_context(), Object::id, if(), ID::lib, NULL, and vgroup_object_in_edit_mode().
static int vertex_group_poll_edit_or_wpaint_vert_select (bContext * C) [static]
Definition at line 2095 of file object_vgroup.c.
References Object::data, data, ED_object_context(), Object::id, if(), ID::lib, NULL, vgroup_object_in_edit_mode(), and vgroup_object_in_wpaint_vert_select().
Referenced by OBJECT_OT_vertex_group_assign(), OBJECT_OT_vertex_group_deselect(), OBJECT_OT_vertex_group_remove_from(), and OBJECT_OT_vertex_group_select().
static int vertex_group_remove_exec (bContext * C, wmOperator * op) [static]
Definition at line 2133 of file object_vgroup.c.
References DAG_id_tag_update(), Object::data, ED_object_context(), Object::id, NC_GEOM, NC_OBJECT, ND_DATA, ND_DRAW, OB_RECALC_DATA, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), vgroup_delete(), vgroup_delete_all(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_remove().
static int vertex_group_remove_from_exec (bContext * C, wmOperator * op) [static]
Definition at line 2204 of file object_vgroup.c.
References Object::actdef, BLI_findlink(), DAG_id_tag_update(), Object::data, Object::defbase, ED_object_context(), FALSE, Object::id, NC_GEOM, ND_DATA, NULL, OB_RECALC_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), vgroup_active_remove_verts(), vgroup_remove_verts(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_remove_from().
static int vertex_group_select_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2246 of file object_vgroup.c.
References Object::data, ED_object_context(), Object::id, ID::lib, NC_GEOM, ND_SELECT, OPERATOR_CANCELLED, OPERATOR_FINISHED, vgroup_select_verts(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_select().
static int vertex_group_sort_exec (bContext * C, wmOperator * op) [static]
Definition at line 2908 of file object_vgroup.c.
References BLI_sortlist(), DAG_id_tag_update(), Object::defbase, ED_object_context(), Object::id, MEM_freeN(), NC_GEOM, ND_DATA, OB_RECALC_DATA, OPERATOR_CANCELLED, vgroup_do_remap(), vgroup_init_remap(), vgroup_sort(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_sort().
static void vgroup_active_remove_verts (Object * ob, const int allverts, bDeformGroup * dg) [static]
Definition at line 1787 of file object_vgroup.c.
References BLI_findindex(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, CD_MDEFORMVERT, CustomData_bmesh_get(), BMHeader::data, Object::data, Lattice::def, Object::defbase, defvert_find_index(), defvert_remove_group(), Lattice::dvert, Mesh::dvert, MDeformVert::dw, ED_vgroup_data_create(), Mesh::edit_btmesh, BPoint::f1, BMVert::head, i, Mesh::id, Mesh::mvert, OB_LATTICE, OB_MESH, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, SELECT, Mesh::totvert, Object::type, BMesh::vdata, and vgroup_edit_lattice().
Referenced by vertex_group_remove_from_exec(), vgroup_delete_edit_mode(), and vgroup_remove_verts().
static void vgroup_assign_verts (Object * ob, const float weight) [static]
Definition at line 1982 of file object_vgroup.c.
References Object::actdef, BLI_findlink(), BMEditMesh::bm, BM_data_layer_add(), BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, CD_MDEFORMVERT, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, Object::data, Lattice::def, Object::defbase, defvert_verify_index(), Lattice::dvert, Mesh::dvert, ED_vgroup_data_create(), Mesh::edit_btmesh, BPoint::f1, BMVert::head, i, Lattice::id, Mesh::id, Mesh::mvert, NULL, OB_LATTICE, OB_MESH, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, SELECT, Mesh::totvert, Object::type, BMesh::vdata, vgroup_edit_lattice(), and MDeformWeight::weight.
Referenced by vertex_group_assign_exec().
static void vgroup_blend (Object * ob, const float fac) [static]
Definition at line 1252 of file object_vgroup.c.
References Object::actdef, BLI_assert, BLI_findlink(), BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_elem_index_get, BM_ELEM_SELECT, BM_ITER_MESH, BM_ITER_MESH_INDEX, BM_mesh_elem_index_ensure(), BM_VERT, BM_VERTS_OF_MESH, BMEdit_FromObject(), CD_MDEFORMVERT, CLAMP(), CustomData_bmesh_get(), BMHeader::data, Object::data, Object::defbase, defvert_find_index(), defvert_verify_index(), Mesh::dvert, MVert::flag, BMVert::head, i, Mesh::medge, MEM_callocN(), MEM_freeN(), Mesh::mvert, NULL, OB_MESH, SELECT, Mesh::totedge, Mesh::totvert, BMesh::totvert, Object::type, MEdge::v1, BMEdge::v1, MEdge::v2, BMEdge::v2, BMesh::vdata, and MDeformWeight::weight.
Referenced by vertex_group_blend_exec().
static void vgroup_clean (Object * ob, const float epsilon, int keep_single) [static]
Definition at line 1384 of file object_vgroup.c.
References Object::actdef, BLI_findlink(), Object::data, Object::defbase, defvert_find_index(), defvert_remove_group(), ED_vgroup_give_parray(), FALSE, i, ME_EDIT_VERT_SEL, MEM_freeN(), NULL, OB_MESH, MDeformVert::totweight, Object::type, and MDeformWeight::weight.
Referenced by vertex_group_clean_exec().
static void vgroup_clean_all (Object * ob, const float epsilon, const int keep_single) [static]
Definition at line 1422 of file object_vgroup.c.
References Object::data, defvert_remove_group(), MDeformVert::dw, ED_vgroup_give_parray(), i, ME_EDIT_VERT_SEL, MEM_freeN(), NULL, OB_MESH, MDeformVert::totweight, Object::type, and MDeformWeight::weight.
Referenced by vertex_group_clean_exec().
static void vgroup_delete (Object * ob) [static]
Definition at line 1946 of file object_vgroup.c.
References Object::actdef, BLI_findlink(), Object::defbase, vgroup_delete_edit_mode(), vgroup_delete_object_mode(), and vgroup_object_in_edit_mode().
Referenced by vertex_group_remove_exec().
static void vgroup_delete_all (Object * ob) [static]
Definition at line 1958 of file object_vgroup.c.
References Object::actdef, BLI_freelistN(), CD_MDEFORMVERT, CustomData_free_layer_active(), Object::data, Object::defbase, Lattice::dvert, Mesh::dvert, MEM_freeN(), NULL, OB_LATTICE, OB_MESH, Mesh::totvert, Object::type, and vgroup_edit_lattice().
Referenced by ED_vgroup_copy_array(), and vertex_group_remove_exec().
static void vgroup_delete_edit_mode (Object * ob, bDeformGroup * defgroup) [static]
Definition at line 1852 of file object_vgroup.c.
References Object::actdef, assert, BLI_findindex(), BLI_freelinkN(), BMEditMesh::bm, BM_ITER_MESH, BM_VERTS_OF_MESH, CD_MDEFORMVERT, CustomData_bmesh_get(), CustomData_free_layer_active(), BMHeader::data, Object::data, Lattice::def, MDeformWeight::def_nr, Object::defbase, Mesh::dvert, Lattice::dvert, MDeformVert::dw, Mesh::edit_btmesh, ListBase::first, BMVert::head, i, MEM_freeN(), NULL, OB_LATTICE, OB_MESH, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, Mesh::totvert, MDeformVert::totweight, TRUE, Object::type, BMesh::vdata, vgroup_active_remove_verts(), vgroup_delete_update_users(), and vgroup_edit_lattice().
Referenced by ED_vgroup_clear(), ED_vgroup_delete(), and vgroup_delete().
static void vgroup_delete_object_mode (Object * ob, bDeformGroup * dg) [static]
Definition at line 1743 of file object_vgroup.c.
References Object::actdef, assert, BLI_findindex(), BLI_freelinkN(), Object::data, MDeformWeight::def_nr, Object::defbase, defvert_find_index(), defvert_remove_group(), MDeformVert::dw, ED_vgroup_give_array(), ListBase::first, i, NULL, MDeformVert::totweight, and vgroup_delete_update_users().
Referenced by ED_vgroup_clear(), ED_vgroup_delete(), and vgroup_delete().
static void vgroup_delete_update_users (Object * ob, int id) [static]
Definition at line 1729 of file object_vgroup.c.
References BLI_countlist(), Object::defbase, i, MEM_freeN(), MEM_mallocN(), and vgroup_remap_update_users().
Referenced by vgroup_delete_edit_mode(), and vgroup_delete_object_mode().
static int vgroup_do_remap (Object * ob, char * name_array, wmOperator * op) [static]
Definition at line 2832 of file object_vgroup.c.
References Object::actdef, BKE_report(), BLI_assert, BLI_countlist(), BLI_findstringindex(), BMEditMesh::bm, BM_ITER_MESH, BM_VERTS_OF_MESH, BMEdit_FromObject(), CD_MDEFORMVERT, CustomData_bmesh_get(), Object::data, BMHeader::data, Object::defbase, defvert_remap(), ED_vgroup_give_array(), ListBase::first, BMVert::head, i, MAX_VGROUP_NAME, MEM_freeN(), MEM_mallocN(), Object::mode, bDeformGroup::next, NULL, OB_MESH, OB_MODE_EDIT, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, MDeformVert::totweight, Object::type, BMesh::vdata, and vgroup_remap_update_users().
Referenced by vertex_group_sort_exec(), and vgroup_move_exec().
static void vgroup_duplicate (Object * ob) [static]
Definition at line 651 of file object_vgroup.c.
References Object::actdef, BLI_addtail(), BLI_countlist(), BLI_findlink(), BLI_snprintf(), BLI_strncpy(), Object::data, Object::defbase, defgroup_duplicate(), defgroup_unique_name(), defvert_find_index(), defvert_verify_index(), ED_vgroup_give_parray(), FALSE, i, MEM_freeN(), bDeformGroup::name, and NULL.
Referenced by vertex_group_copy_exec().
static Lattice* vgroup_edit_lattice (Object * ob) [static]
Definition at line 85 of file object_vgroup.c.
References BLI_assert, Object::data, Lattice::editlatt, EditLatt::latt, OB_LATTICE, and Object::type.
Referenced by ED_vgroup_mirror(), get_vert_def_nr(), vgroup_active_remove_verts(), vgroup_assign_verts(), vgroup_delete_all(), vgroup_delete_edit_mode(), and vgroup_select_verts().
static void vgroup_fix (Scene * scene, Object * ob, float distToBe, float strength, float cp) [static]
Definition at line 1056 of file object_vgroup.c.
References CD_MASK_BAREMESH, MVert::co, Object::data, dot_v3v3(), Mesh::editflag, MVert::flag, getSingleCoordinate(), getSurroundingVerts(), DerivedMesh::getVert, i, ME_EDIT_VERT_SEL, MEM_callocN(), MEM_freeN(), mesh_get_derived_deform(), moveCloserToDistanceFromPlane(), Mesh::mvert, normalize_v3(), NULL, p, SELECT, sub_v3_v3v3(), and Mesh::totvert.
Referenced by vertex_group_fix_exec().
static char* vgroup_init_remap (Object * ob) [static]
Definition at line 2816 of file object_vgroup.c.
References BLI_countlist(), BLI_strncpy(), Object::defbase, ListBase::first, MAX_VGROUP_NAME, MEM_mallocN(), bDeformGroup::name, and bDeformGroup::next.
Referenced by vertex_group_sort_exec(), and vgroup_move_exec().
static void vgroup_invert (Object * ob, const short auto_assign, const short auto_remove) [static]
Definition at line 1210 of file object_vgroup.c.
References Object::actdef, BLI_findlink(), Object::data, Object::defbase, defvert_find_index(), defvert_remove_group(), defvert_verify_index(), ED_vgroup_give_parray(), i, ME_EDIT_VERT_SEL, MEM_freeN(), NULL, OB_MESH, Object::type, and MDeformWeight::weight.
Referenced by vertex_group_invert_exec().
static EnumPropertyItem* vgroup_itemf (bContext * C, PointerRNA * UNUSEDptr, PropertyRNA * UNUSEDprop, int * free) [static]
Definition at line 2766 of file object_vgroup.c.
References Object::defbase, ED_object_context(), ListBase::first, EnumPropertyItem::icon, EnumPropertyItem::identifier, bDeformGroup::name, EnumPropertyItem::name, bDeformGroup::next, NULL, RNA_enum_item_add(), RNA_enum_item_end(), EnumPropertyItem::value, and vgroup_items.
Referenced by OBJECT_OT_vertex_group_set_active().
static void vgroup_levels (Object * ob, float offset, float gain) [static]
Definition at line 1102 of file object_vgroup.c.
References Object::actdef, BLI_findlink(), CLAMP(), Object::data, Object::defbase, defvert_find_index(), ED_vgroup_give_parray(), i, ME_EDIT_VERT_SEL, MEM_freeN(), NULL, OB_MESH, Object::type, and MDeformWeight::weight.
Referenced by vertex_group_levels_exec().
static void vgroup_lock_all (Object * ob, int action) [static]
Definition at line 1181 of file object_vgroup.c.
References Object::defbase, DG_LOCK_WEIGHT, ListBase::first, bDeformGroup::flag, bDeformGroup::next, SEL_DESELECT, SEL_INVERT, SEL_SELECT, and SEL_TOGGLE.
Referenced by vertex_group_lock_exec().
static int vgroup_move_exec (bContext * C, wmOperator * op) [static]
Definition at line 2947 of file object_vgroup.c.
References Object::actdef, BLI_findlink(), BLI_insertlinkafter(), BLI_insertlinkbefore(), BLI_remlink(), DAG_id_tag_update(), Object::defbase, ED_object_context(), Object::id, MEM_freeN(), NC_GEOM, ND_DATA, bDeformGroup::next, next, OB_RECALC_DATA, OPERATOR_CANCELLED, bDeformGroup::prev, wmOperator::ptr, RNA_enum_get(), vgroup_do_remap(), vgroup_init_remap(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_group_move().
static void vgroup_normalize (Object * ob) [static]
Definition at line 698 of file object_vgroup.c.
References Object::actdef, BLI_findlink(), CLAMP(), Object::data, Object::defbase, defvert_find_index(), ED_vgroup_give_parray(), i, MAX2, ME_EDIT_VERT_SEL, MEM_freeN(), NULL, OB_MESH, Object::type, and MDeformWeight::weight.
Referenced by vertex_group_normalize_exec().
static void vgroup_normalize_all (Object * ob, int lock_active) [static]
Definition at line 1138 of file object_vgroup.c.
References Object::actdef, BLI_findlink(), Object::data, Object::defbase, defvert_normalize(), defvert_normalize_lock(), ED_vgroup_give_parray(), i, ME_EDIT_VERT_SEL, MEM_freeN(), NULL, OB_MESH, and Object::type.
Referenced by vertex_group_normalize_all_exec().
static int vgroup_object_in_edit_mode (Object * ob) [static]
Definition at line 1924 of file object_vgroup.c.
References BMEdit_FromObject(), Object::data, NULL, OB_LATTICE, OB_MESH, and Object::type.
Referenced by vertex_group_blend_poll(), vertex_group_poll_edit(), vertex_group_poll_edit_or_wpaint_vert_select(), and vgroup_delete().
static int vgroup_object_in_wpaint_vert_select (Object * ob) [static]
Definition at line 1934 of file object_vgroup.c.
References Object::data, Mesh::edit_btmesh, ME_EDIT_PAINT_SEL_MODE, Object::mode, NULL, OB_MESH, OB_MODE_WEIGHT_PAINT, SCE_SELECT_VERTEX, and Object::type.
Referenced by vertex_group_poll_edit_or_wpaint_vert_select().
static void vgroup_remap_update_users (Object * ob, int * map) [static]
Definition at line 1690 of file object_vgroup.c.
References eModifierType_Cloth, eModifierType_Explode, ListBase::first, Object::modifiers, ModifierData::next, ParticleSystem::next, Object::particlesystem, PSYS_TOT_VG, ClothModifierData::sim_parms, Object::soft, ModifierData::type, SoftBody::vertgroup, ParticleSystem::vgroup, ExplodeModifierData::vgroup, ClothSimSettings::vgroup_bend, ClothSimSettings::vgroup_mass, and ClothSimSettings::vgroup_struct.
Referenced by ED_vgroup_copy_array(), vgroup_delete_update_users(), and vgroup_do_remap().
static void vgroup_remove_verts (Object * ob, int allverts) [static]
Definition at line 2062 of file object_vgroup.c.
References Object::defbase, ListBase::first, bDeformGroup::next, and vgroup_active_remove_verts().
Referenced by vertex_group_remove_from_exec().
static void vgroup_select_verts (Object * ob, int select) [static]
Definition at line 579 of file object_vgroup.c.
References Object::actdef, BLI_findlink(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ITER_MESH, BM_vert_select_set(), BM_VERTS_OF_MESH, CD_MDEFORMVERT, CustomData_bmesh_get(), BMHeader::data, Object::data, Lattice::def, Object::defbase, defvert_find_index(), Lattice::dvert, Mesh::dvert, EDBM_deselect_flush(), EDBM_select_flush(), Mesh::edit_btmesh, BPoint::f1, MDeformVert::flag, BMVert::head, i, ME_HIDE, Mesh::mvert, OB_LATTICE, OB_MESH, paintvert_flush_flags(), Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, SELECT, Mesh::totvert, Object::type, BMesh::vdata, and vgroup_edit_lattice().
Referenced by vertex_group_deselect_exec(), and vertex_group_select_exec().
static int vgroup_sort (void * def_a_ptr, void * def_b_ptr) [static]
Definition at line 2900 of file object_vgroup.c.
References BLI_natstrcmp(), and bDeformGroup::name.
Referenced by vertex_group_sort_exec().
Variable Documentation
EnumPropertyItem vgroup_items[] [static]
Initial value:
 {
    {0, NULL, 0, NULL, NULL}}
Definition at line 2749 of file object_vgroup.c.
Referenced by vgroup_itemf().