Blender: svm_musgrave.h File Reference
svm_musgrave.h File Reference
Functions
CCL_NAMESPACE_BEGIN
__device_noinline float noise_musgrave_fBm (float3 p, NodeNoiseBasis basis, float H, float lacunarity, float octaves)
__device_noinline float noise_musgrave_multi_fractal (float3 p, NodeNoiseBasis basis, float H, float lacunarity, float octaves)
__device_noinline float noise_musgrave_hetero_terrain (float3 p, NodeNoiseBasis basis, float H, float lacunarity, float octaves, float offset)
__device_noinline float noise_musgrave_hybrid_multi_fractal (float3 p, NodeNoiseBasis basis, float H, float lacunarity, float octaves, float offset, float gain)
__device_noinline float noise_musgrave_ridged_multi_fractal (float3 p, NodeNoiseBasis basis, float H, float lacunarity, float octaves, float offset, float gain)
__device float svm_musgrave (NodeMusgraveType type, float dimension, float lacunarity, float octaves, float offset, float intensity, float gain, float scale, float3 p)
__device void svm_node_tex_musgrave (KernelGlobals *kg, ShaderData *sd, float *stack, uint4 node, int *offset)
Function Documentation
CCL_NAMESPACE_BEGIN __device_noinline float noise_musgrave_fBm (float3 p, NodeNoiseBasis basis, float H, float lacunarity, float octaves)
Definition at line 30 of file svm_musgrave.h.
References i, pow(), and snoise().
Referenced by svm_musgrave().
__device_noinline float noise_musgrave_hetero_terrain (float3 p, NodeNoiseBasis basis, float H, float lacunarity, float octaves, float offset)
Definition at line 87 of file svm_musgrave.h.
References i, pow(), and snoise().
Referenced by svm_musgrave().
__device_noinline float noise_musgrave_hybrid_multi_fractal (float3 p, NodeNoiseBasis basis, float H, float lacunarity, float octaves, float offset, float gain)
Definition at line 122 of file svm_musgrave.h.
References i, pow(), and snoise().
Referenced by svm_musgrave().
__device_noinline float noise_musgrave_multi_fractal (float3 p, NodeNoiseBasis basis, float H, float lacunarity, float octaves)
Definition at line 58 of file svm_musgrave.h.
References i, pow(), and snoise().
Referenced by svm_musgrave().
__device_noinline float noise_musgrave_ridged_multi_fractal (float3 p, NodeNoiseBasis basis, float H, float lacunarity, float octaves, float offset, float gain)
Definition at line 159 of file svm_musgrave.h.
References clamp, fabsf, i, pow(), and snoise().
Referenced by svm_musgrave().
__device float svm_musgrave (NodeMusgraveType type, float dimension, float lacunarity, float octaves, float offset, float intensity, float gain, float scale, float3 p)
Definition at line 186 of file svm_musgrave.h.
References NODE_MUSGRAVE_FBM, NODE_MUSGRAVE_HETERO_TERRAIN, NODE_MUSGRAVE_HYBRID_MULTIFRACTAL, NODE_MUSGRAVE_MULTIFRACTAL, NODE_MUSGRAVE_RIDGED_MULTIFRACTAL, NODE_NOISE_PERLIN, noise_musgrave_fBm(), noise_musgrave_hetero_terrain(), noise_musgrave_hybrid_multi_fractal(), noise_musgrave_multi_fractal(), and noise_musgrave_ridged_multi_fractal().
Referenced by svm_node_tex_musgrave().
__device void svm_node_tex_musgrave (KernelGlobals * kg, ShaderData * sd, float * stack, uint4 node, int * offset)
Definition at line 205 of file svm_musgrave.h.
References clamp, co, decode_node_uchar4(), fmaxf, make_float3(), NULL, read_node(), stack_load_float3(), stack_load_float_default(), stack_store_float(), stack_store_float3(), stack_valid(), svm_musgrave(), uint4::w, uint4::x, uint4::y, and uint4::z.
Referenced by svm_eval_nodes().