Blender: btSingleRayCallback Struct Reference
btSingleRayCallback Struct Reference
Public Member Functions
btSingleRayCallback (const btVector3 &rayFromWorld, const btVector3 &rayToWorld, const btCollisionWorld *world, btCollisionWorld::RayResultCallback &resultCallback)
virtual bool process (const btBroadphaseProxy *proxy)
Public Attributes
btVector3 m_rayFromWorld
btVector3 m_rayToWorld
btTransform m_rayFromTrans
btTransform m_rayToTrans
btVector3 m_hitNormal
const btCollisionWorld * m_world
btCollisionWorld::RayResultCallback & m_resultCallback
Detailed Description
Definition at line 787 of file btCollisionWorld.cpp.
Constructor & Destructor Documentation
btSingleRayCallback::btSingleRayCallback (const btVector3 & rayFromWorld, const btVector3 & rayToWorld, const btCollisionWorld * world, btCollisionWorld::RayResultCallback & resultCallback) [inline]
what about division by zero? --> just set rayDirection[i] to INF/BT_LARGE_FLOAT
Definition at line 799 of file btCollisionWorld.cpp.
References BT_LARGE_FLOAT, btBroadphaseRayCallback::m_lambda_max, btBroadphaseRayCallback::m_rayDirectionInverse, m_rayFromTrans, m_rayFromWorld, m_rayToTrans, m_rayToWorld, btBroadphaseRayCallback::m_signs, btTransform::setIdentity(), and btTransform::setOrigin().
Member Function Documentation
virtual bool btSingleRayCallback::process (const btBroadphaseProxy * proxy) [inline, virtual]
terminate further ray tests, once the closestHitFraction reached zero
Implements btBroadphaseAabbCallback.
Definition at line 827 of file btCollisionWorld.cpp.
References btCollisionWorld::RayResultCallback::m_closestHitFraction, m_rayFromTrans, m_rayToTrans, m_resultCallback, m_world, btCollisionWorld::RayResultCallback::needsCollision(), and btCollisionWorld::rayTestSingle().
Referenced by btCollisionWorld::rayTest().
Member Data Documentation
btVector3 btSingleRayCallback::m_hitNormal
Definition at line 794 of file btCollisionWorld.cpp.
btTransform btSingleRayCallback::m_rayFromTrans
Definition at line 792 of file btCollisionWorld.cpp.
Referenced by btSingleRayCallback(), and process().
btVector3 btSingleRayCallback::m_rayFromWorld
Definition at line 790 of file btCollisionWorld.cpp.
Referenced by btSingleRayCallback().
btTransform btSingleRayCallback::m_rayToTrans
Definition at line 793 of file btCollisionWorld.cpp.
Referenced by btSingleRayCallback(), and process().
btVector3 btSingleRayCallback::m_rayToWorld
Definition at line 791 of file btCollisionWorld.cpp.
Referenced by btSingleRayCallback().
btCollisionWorld::RayResultCallback& btSingleRayCallback::m_resultCallback
Definition at line 797 of file btCollisionWorld.cpp.
Referenced by process().
const btCollisionWorld* btSingleRayCallback::m_world
Definition at line 796 of file btCollisionWorld.cpp.
Referenced by process().
The documentation for this struct was generated from the following file:
btCollisionWorld.cpp