Blender: node_composite_distanceMatte.c File Reference
node_composite_distanceMatte.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_distance_matte (bNode *node, float *out, float *in)
static void node_composit_exec_distance_matte (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_distance_matte (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_distance_matte (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_distance_matte_in []
static bNodeSocketTemplate cmp_node_distance_matte_out []
Detailed Description
Definition in file node_composite_distanceMatte.c.
Function Documentation
static void do_distance_matte (bNode * node, float * out, float * in) [static]
Definition at line 50 of file node_composite_distanceMatte.c.
References copy_v3_v3(), distance(), NodeChroma::key, sqrt(), bNode::storage, NodeChroma::t1, and NodeChroma::t2.
Referenced by node_composit_exec_distance_matte().
static void node_composit_exec_distance_matte (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 85 of file node_composite_distanceMatte.c.
References CB_RGBA, CHAN_A, composit1_pixel_processor(), bNodeStack::data, do_distance_matte(), dupalloc_compbuf(), free_compbuf(), generate_preview(), NodeChroma::key, NULL, bNode::storage, typecheck_compbuf(), valbuf_from_rgbabuf(), and bNodeStack::vec.
Referenced by register_node_type_cmp_distance_matte().
static void node_composit_init_distance_matte (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 123 of file node_composite_distanceMatte.c.
References MEM_callocN(), bNode::storage, NodeChroma::t1, and NodeChroma::t2.
Referenced by register_node_type_cmp_distance_matte().
void register_node_type_cmp_distance_matte (bNodeTreeType * ttype)
Definition at line 131 of file node_composite_distanceMatte.c.
References CMP_NODE_DIST_MATTE, NODE_CLASS_MATTE, node_composit_exec_distance_matte(), node_composit_init_distance_matte(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_distance_matte_in[] [static]
Initial value:
{
    {SOCK_RGBA,1,"Image", 1.0f, 1.0f, 1.0f, 1.0f},
    {SOCK_RGBA,1,"Key Color", 1.0f, 1.0f, 1.0f, 1.0f},
    {-1,0,""}
}
Definition at line 36 of file node_composite_distanceMatte.c.
bNodeSocketTemplate cmp_node_distance_matte_out[] [static]
Initial value:
{
    {SOCK_RGBA,0,"Image"},
    {SOCK_FLOAT,0,"Matte"},
    {-1,0,""}
}
Definition at line 42 of file node_composite_distanceMatte.c.