Blender: util_types.h File Reference
util_types.h File Reference
#include <stdlib.h>
#include <stdint.h>
Classes
struct uchar2
struct uchar3
struct uchar4
struct int2
class int3
class int4
struct uint2
struct uint3
struct uint4
struct float2
struct float3
struct float4
Defines
#define __device static inline
#define __device_noinline static
#define __global
#define __local
#define __shared
#define __constant
#define __device_inline static __forceinline
Typedefs
typedef unsigned int uint
typedef uint64_t device_ptr
Functions
__device uchar2 make_uchar2 (uchar x, uchar y)
__device uchar3 make_uchar3 (uchar x, uchar y, uchar z)
__device uchar4 make_uchar4 (uchar x, uchar y, uchar z, uchar w)
__device int2 make_int2 (int x, int y)
__device int3 make_int3 (int x, int y, int z)
__device int4 make_int4 (int x, int y, int z, int w)
__device uint2 make_uint2 (uint x, uint y)
__device uint3 make_uint3 (uint x, uint y, uint z)
__device uint4 make_uint4 (uint x, uint y, uint z, uint w)
__device float2 make_float2 (float x, float y)
__device float3 make_float3 (float x, float y, float z)
__device float4 make_float4 (float x, float y, float z, float w)
__device int align_up (int offset, int alignment)
Variables
CCL_NAMESPACE_BEGIN typedef
unsigned char uchar
Define Documentation
#define __constant
Definition at line 37 of file util_types.h.
#define __device static inline
Definition at line 32 of file util_types.h.
#define __device_inline static __forceinline
Definition at line 42 of file util_types.h.
#define __device_noinline static
Definition at line 33 of file util_types.h.
#define __global
Definition at line 34 of file util_types.h.
#define __local
Definition at line 35 of file util_types.h.
#define __shared
Definition at line 36 of file util_types.h.
Typedef Documentation
typedef uint64_t device_ptr
Definition at line 104 of file util_types.h.
typedef unsigned int uint
Definition at line 78 of file util_types.h.
Function Documentation
__device int align_up (int offset, int alignment)
Definition at line 280 of file util_types.h.
Referenced by Film::device_update(), BufferParams::get_passes_size(), CUDADevice::path_trace(), CUDADevice::shader(), and CUDADevice::tonemap().
__device float2 make_float2 (float x, float y)
Definition at line 258 of file util_types.h.
Referenced by TriangleDice::add_grid(), as_float2(), blender_camera_init(), concentric_sample_disk(), direction_to_equirectangular(), direction_to_mirrorball(), direction_to_spherical(), fabs(), get_float2(), regular_polygon_sample(), sky_spherical_coordinates(), DiagSplit::split_quad(), and DiagSplit::split_triangle().
__device float3 make_float3 (float x, float y, float z)
Definition at line 264 of file util_types.h.
Referenced by ShaderManager::add_default(), BVHBuild::add_references(), BoundBox::BoundBox(), bsdf_ashikhmin_velvet_eval_reflect(), bsdf_ashikhmin_velvet_eval_transmit(), bsdf_ashikhmin_velvet_sample(), bsdf_diffuse_eval_reflect(), bsdf_diffuse_eval_transmit(), bsdf_diffuse_sample(), bsdf_eval_init(), bsdf_microfacet_beckmann_eval_reflect(), bsdf_microfacet_beckmann_eval_transmit(), bsdf_microfacet_beckmann_sample(), bsdf_microfacet_ggx_eval_reflect(), bsdf_microfacet_ggx_eval_transmit(), bsdf_microfacet_ggx_sample(), bsdf_oren_nayar_eval_reflect(), bsdf_oren_nayar_eval_transmit(), bsdf_oren_nayar_get_intensity(), bsdf_oren_nayar_sample(), bsdf_reflection_eval_reflect(), bsdf_reflection_eval_transmit(), bsdf_reflection_sample(), bsdf_refraction_eval_reflect(), bsdf_refraction_eval_transmit(), bsdf_refraction_sample(), bsdf_translucent_eval_reflect(), bsdf_translucent_eval_transmit(), bsdf_translucent_sample(), bsdf_transparent_eval_reflect(), bsdf_transparent_eval_transmit(), bsdf_transparent_sample(), bsdf_ward_eval_reflect(), bsdf_ward_eval_transmit(), bsdf_ward_sample(), bsdf_westin_backscatter_eval_reflect(), bsdf_westin_backscatter_eval_transmit(), bsdf_westin_backscatter_sample(), bsdf_westin_sheen_eval_reflect(), bsdf_westin_sheen_eval_transmit(), bsdf_westin_sheen_sample(), Camera::Camera(), camera_sample_environment(), camera_sample_orthographic(), camera_sample_perspective(), cellnoise_color(), color_scene_linear_to_srgb(), color_srgb_to_scene_linear(), Mesh::compute_bounds(), TextureMapping::compute_transform(), create_mesh(), cross(), direct_emissive_eval(), emissive_eval(), equirectangular_to_direction(), SubdFaceRing::evaluate_stencils(), fabs(), flatten_background_closure_tree(), float4_to_float3(), fresnel_dielectric(), get_float3(), get_mesh_attribute_convert(), RenderBuffers::get_pass(), hsv_to_rgb(), indirect_background(), kernel_path_integrate(), kernel_shader_evaluate(), kernel_write_data_passes(), Light::Light(), make_orthonormals(), max(), min(), mirrorball_to_direction(), operator*(), operator+(), operator-(), operator/(), path_radiance_clamp(), path_radiance_init(), qbvh_node_intersect(), regular_light_sample(), rgb_to_hsv(), safe_divide_color(), sample_uniform_sphere(), ShaderInput::set(), shader_bsdf_diffuse(), shader_bsdf_eval(), shader_bsdf_glossy(), shader_bsdf_transmission(), shader_bsdf_transparency(), shader_emissive_eval(), shader_eval_background(), shader_eval_surface(), shader_holdout_eval(), shader_setup_from_background(), shader_setup_from_displace(), shader_setup_from_ray(), shader_setup_from_sample(), shader_volume_eval_phase(), ShaderInput::ShaderInput(), shadow_blocked(), TextureMapping::skip(), spherical_to_direction(), stack_load_float3(), SubdVert::SubdVert(), svm_background_offset(), svm_bsdf_eval(), svm_magic(), svm_mix(), svm_mix_screen(), svm_mix_soft(), svm_node_attr(), svm_node_attr_bump_dx(), svm_node_attr_bump_dy(), svm_node_closure_holdout(), svm_node_closure_set_weight(), svm_node_convert(), svm_node_emission_set_weight_total(), svm_node_geometry(), svm_node_geometry_bump_dx(), svm_node_geometry_bump_dy(), svm_node_rgb_curves(), svm_node_tex_environment(), svm_node_tex_gradient(), svm_node_tex_image(), svm_node_tex_musgrave(), svm_node_tex_voronoi(), svm_node_tex_wave(), svm_node_value_v(), svm_noise(), svm_vector_math(), svm_voronoi(), DiagSplit::T(), TextureMapping::TextureMapping(), transform_direction(), transform_euler(), transform_get_column(), transform_perspective(), transform_point(), transform_scale(), transform_translate(), triangle_attribute_float3(), triangle_normal_MT(), Camera::update(), volume_eval_phase(), volume_isotropic_eval_phase(), volume_transparent_eval_phase(), voronoi(), xml_read_float3(), xml_read_float3_array(), xml_read_transform(), xyY_to_xyz(), and xyz_to_rgb().
__device float4 make_float4 (float x, float y, float z, float w)
Definition at line 274 of file util_types.h.
Referenced by colorramp_to_array(), MeshManager::device_update_attributes(), LightManager::device_update_points(), ObjectManager::device_update_transforms(), fetch_node_float(), float3_to_float4(), RenderBuffers::get_pass(), texture_image< T >::interp(), kernel_path_integrate(), kernel_shader_evaluate(), max(), min(), operator*(), Mesh::pack_normals(), BVH::pack_triangle(), Mesh::pack_verts(), path_radiance_init(), texture_image< T >::read(), read_node_float(), svm_image_texture(), svm_voronoi(), transform_direction(), transform_perspective(), transform_point(), xml_read_float4(), and xml_read_transform().
__device int2 make_int2 (int x, int y)
Definition at line 222 of file util_types.h.
__device int3 make_int3 (int x, int y, int z)
Definition at line 228 of file util_types.h.
Referenced by BVHBuild::find_spatial_split().
__device int4 make_int4 (int x, int y, int z, int w)
Definition at line 234 of file util_types.h.
Referenced by SVMCompiler::add_node(), SVMShaderManager::device_update(), get_int4(), operator>=(), and RegularBVH::pack_node().
__device uchar2 make_uchar2 (uchar x, uchar y)
Definition at line 204 of file util_types.h.
__device uchar3 make_uchar3 (uchar x, uchar y, uchar z)
Definition at line 210 of file util_types.h.
__device uchar4 make_uchar4 (uchar x, uchar y, uchar z, uchar w)
Definition at line 216 of file util_types.h.
__device uint2 make_uint2 (uint x, uint y)
Definition at line 240 of file util_types.h.
__device uint3 make_uint3 (uint x, uint y, uint z)
Definition at line 246 of file util_types.h.
__device uint4 make_uint4 (uint x, uint y, uint z, uint w)
Definition at line 252 of file util_types.h.
Referenced by MeshManager::displace(), and dump_background_pixels().
Variable Documentation
CCL_NAMESPACE_BEGIN typedef unsigned char uchar
Definition at line 77 of file util_types.h.