Blender: KDL::RotationVel Class Reference
KDL::RotationVel Class Reference
#include <framevel.hpp>
Public Member Functions
RotationVel ()
RotationVel (const Rotation &R_)
RotationVel (const Rotation &R_, const Vector &_w)
Rotation value () const
Vector deriv () const
IMETHOD RotationVel & operator= (const RotationVel &arg)
IMETHOD RotationVel & operator= (const Rotation &arg)
IMETHOD VectorVel UnitX () const
IMETHOD VectorVel UnitY () const
IMETHOD VectorVel UnitZ () const
IMETHOD RotationVel Inverse () const
IMETHOD VectorVel Inverse (const VectorVel &arg) const
IMETHOD VectorVel Inverse (const Vector &arg) const
IMETHOD VectorVel operator* (const VectorVel &arg) const
IMETHOD VectorVel operator* (const Vector &arg) const
IMETHOD void DoRotX (const doubleVel &angle)
IMETHOD void DoRotY (const doubleVel &angle)
IMETHOD void DoRotZ (const doubleVel &angle)
IMETHOD TwistVel Inverse (const TwistVel &arg) const
IMETHOD TwistVel Inverse (const Twist &arg) const
IMETHOD TwistVel operator* (const TwistVel &arg) const
IMETHOD TwistVel operator* (const Twist &arg) const
Static Public Member Functions
static IMETHOD RotationVel Identity ()
static IMETHOD RotationVel RotX (const doubleVel &angle)
static IMETHOD RotationVel RotY (const doubleVel &angle)
static IMETHOD RotationVel RotZ (const doubleVel &angle)
static IMETHOD RotationVel Rot (const Vector &rotvec, const doubleVel &angle)
static IMETHOD RotationVel Rot2 (const Vector &rotvec, const doubleVel &angle)
Public Attributes
Rotation R
Vector w
Friends
IMETHOD friend RotationVel operator* (const RotationVel &r1, const RotationVel &r2)
IMETHOD friend RotationVel operator* (const Rotation &r1, const RotationVel &r2)
IMETHOD friend RotationVel operator* (const RotationVel &r1, const Rotation &r2)
IMETHOD friend bool Equal (const RotationVel &r1, const RotationVel &r2, double eps=epsilon)
IMETHOD friend bool Equal (const Rotation &r1, const RotationVel &r2, double eps=epsilon)
IMETHOD friend bool Equal (const RotationVel &r1, const Rotation &r2, double eps=epsilon)
Detailed Description
Definition at line 124 of file framevel.hpp.
Constructor & Destructor Documentation
KDL::RotationVel::RotationVel () [inline]
Definition at line 134 of file framevel.hpp.
KDL::RotationVel::RotationVel (const Rotation & R_) [inline, explicit]
Definition at line 135 of file framevel.hpp.
KDL::RotationVel::RotationVel (const Rotation & R_, const Vector & _w) [inline]
Definition at line 136 of file framevel.hpp.
Member Function Documentation
Vector KDL::RotationVel::deriv () const [inline]
Definition at line 140 of file framevel.hpp.
References w.
Referenced by KDL::FrameVel::deriv().
void RotationVel::DoRotX (const doubleVel & angle)
Definition at line 552 of file frames.inl.
References KDL::cos(), and KDL::sin().
void RotationVel::DoRotY (const doubleVel & angle)
Definition at line 568 of file frames.inl.
References KDL::cos(), and KDL::sin().
void RotationVel::DoRotZ (const doubleVel & angle)
Definition at line 584 of file frames.inl.
References KDL::cos(), and KDL::sin().
RotationVel KDL::RotationVel::Identity () [static]
Definition at line 131 of file framevel.hpp.
TwistVel KDL::RotationVel::Inverse (const TwistVel & arg) const
Definition at line 475 of file framevel.hpp.
TwistVel KDL::RotationVel::Inverse (const Twist & arg) const
Definition at line 485 of file framevel.hpp.
RotationVel KDL::RotationVel::Inverse () const
Definition at line 135 of file framevel.hpp.
VectorVel KDL::RotationVel::Inverse (const VectorVel & arg) const
Definition at line 139 of file framevel.hpp.
VectorVel KDL::RotationVel::Inverse (const Vector & arg) const
Definition at line 146 of file framevel.hpp.
VectorVel KDL::RotationVel::operator* (const Vector & arg) const
Definition at line 159 of file framevel.hpp.
VectorVel KDL::RotationVel::operator* (const VectorVel & arg) const
Definition at line 154 of file framevel.hpp.
TwistVel KDL::RotationVel::operator* (const TwistVel & arg) const
Definition at line 480 of file framevel.hpp.
TwistVel KDL::RotationVel::operator* (const Twist & arg) const
Definition at line 490 of file framevel.hpp.
RotationVel & RotationVel::operator= (const Rotation & arg)
Definition at line 111 of file framevel.hpp.
RotationVel & RotationVel::operator= (const RotationVel & arg)
Definition at line 106 of file framevel.hpp.
RotationVel RotationVel::Rot (const Vector & rotvec, const doubleVel & angle) [static]
Definition at line 928 of file frames.inl.
References KDL::cos(), KDL::Rotation2::Rotation2(), and KDL::sin().
RotationVel RotationVel::Rot2 (const Vector & rotvec, const doubleVel & angle) [static]
Definition at line 203 of file framevel.hpp.
RotationVel RotationVel::RotX (const doubleVel & angle) [static]
Definition at line 601 of file frames.inl.
References KDL::cos(), KDL::Rotation::Rotation(), and KDL::sin().
RotationVel RotationVel::RotY (const doubleVel & angle) [static]
Definition at line 606 of file frames.inl.
References KDL::cos(), KDL::Rotation::Rotation(), and KDL::sin().
RotationVel RotationVel::RotZ (const doubleVel & angle) [static]
Definition at line 611 of file frames.inl.
References KDL::cos(), KDL::Rotation::Rotation(), and KDL::sin().
VectorVel RotationVel::UnitX () const
Definition at line 117 of file framevel.hpp.
VectorVel RotationVel::UnitY () const
Definition at line 121 of file framevel.hpp.
VectorVel RotationVel::UnitZ () const
Definition at line 125 of file framevel.hpp.
Rotation KDL::RotationVel::value () const [inline]
Definition at line 139 of file framevel.hpp.
References R.
Referenced by KDL::FrameVel::value().
Friends And Related Function Documentation
IMETHOD friend bool Equal (const RotationVel & r1, const RotationVel & r2, double eps = epsilon) [friend]
Definition at line 333 of file framevel.hpp.
IMETHOD friend bool Equal (const Rotation & r1, const RotationVel & r2, double eps = epsilon) [friend]
Definition at line 336 of file framevel.hpp.
IMETHOD friend bool Equal (const RotationVel & r1, const Rotation & r2, double eps = epsilon) [friend]
Definition at line 339 of file framevel.hpp.
IMETHOD friend RotationVel operator* (const Rotation & r1, const RotationVel & r2) [friend]
Definition at line 98 of file framevel.hpp.
IMETHOD friend RotationVel operator* (const RotationVel & r1, const RotationVel & r2) [friend]
Definition at line 94 of file framevel.hpp.
IMETHOD friend RotationVel operator* (const RotationVel & r1, const Rotation & r2) [friend]
Definition at line 102 of file framevel.hpp.
Member Data Documentation
Rotation KDL::RotationVel::R
Definition at line 131 of file framevel.hpp.
Referenced by KDL::addDelta(), KDL::diff(), KDL::posrandom(), KDL::random(), and value().
Vector KDL::RotationVel::w
Definition at line 132 of file framevel.hpp.
Referenced by KDL::addDelta(), deriv(), KDL::diff(), and KDL::random().
The documentation for this class was generated from the following files:
framevel.hpp
frames.inl
framevel.inl