Blender: BKE_blender.h File Reference
BKE_blender.h File Reference
blenkernel
Blender util stuff.
Defines
#define BLENDER_VERSION 263
#define BLENDER_SUBVERSION 0
#define BLENDER_MINVERSION 250
#define BLENDER_MINSUBVERSION 0
#define BLENDER_VERSION_CHAR
#define BLENDER_VERSION_CYCLE release
#define BKE_READ_FILE_FAIL 0
#define BKE_READ_FILE_OK 1
#define BKE_READ_FILE_OK_USERPREFS 2
Functions
int BKE_read_file (struct bContext *C, const char *filepath, struct ReportList *reports)
int BKE_read_file_from_memory (struct bContext *C, char *filebuf, int filelength, struct ReportList *reports)
int BKE_read_file_from_memfile (struct bContext *C, struct MemFile *memfile, struct ReportList *reports)
void free_blender (void)
void initglobals (void)
void BKE_userdef_free (void)
void set_blender_test_break_cb (void(*func)(void))
int blender_test_break (void)
void BKE_write_undo (struct bContext *C, const char *name)
void BKE_undo_step (struct bContext *C, int step)
void BKE_undo_name (struct bContext *C, const char *name)
int BKE_undo_valid (const char *name)
void BKE_reset_undo (void)
char * BKE_undo_menu_string (void)
void BKE_undo_number (struct bContext *C, int nr)
const char * BKE_undo_get_name (int nr, int *active)
void BKE_undo_save_quit (void)
struct Main * BKE_undo_get_main (struct Scene **scene)
Variables
char versionstr []
Detailed Description
Blender util stuff.
Since:
March 2001
Author:
nzc
Definition in file BKE_blender.h.
Define Documentation
#define BKE_READ_FILE_FAIL 0
Definition at line 67 of file BKE_blender.h.
Referenced by BKE_read_file(), load_file(), read_undosave(), WM_read_file(), and WM_read_homefile().
#define BKE_READ_FILE_OK 1
Definition at line 68 of file BKE_blender.h.
Referenced by BKE_read_file().
#define BKE_READ_FILE_OK_USERPREFS 2
Definition at line 69 of file BKE_blender.h.
Referenced by BKE_read_file(), and WM_read_file().
#define BLENDER_MINSUBVERSION 0
Definition at line 48 of file BKE_blender.h.
Referenced by write_global().
#define BLENDER_MINVERSION 250
Definition at line 47 of file BKE_blender.h.
Referenced by write_global().
#define BLENDER_SUBVERSION 0
Definition at line 45 of file BKE_blender.h.
Referenced by DocumentExporter::exportCurrentScene(), handle_subversion_warning(), initglobals(), make_app_info(), wm_block_create_splash(), and write_global().
#define BLENDER_VERSION 263
Definition at line 44 of file BKE_blender.h.
Referenced by BLI_get_folder(), BLI_get_user_folder_notest(), bpy_resource_path(), DocumentExporter::exportCurrentScene(), handle_subversion_warning(), initglobals(), is_portable_install(), make_app_info(), wm_block_create_splash(), wm_resource_check_prev(), and write_file_handle().
#define BLENDER_VERSION_CHAR
Definition at line 52 of file BKE_blender.h.
Referenced by make_app_info(), and wm_block_create_splash().
#define BLENDER_VERSION_CYCLE release
Definition at line 54 of file BKE_blender.h.
Referenced by make_app_info(), and wm_block_create_splash().
Function Documentation
int BKE_read_file (struct bContext * C, const char * filepath, struct ReportList * reports)
Definition at line 377 of file blender.c.
References BKE_READ_FILE_FAIL, BKE_READ_FILE_OK, BKE_READ_FILE_OK_USERPREFS, BKE_reports_prependf(), BLENDER_STARTUP_FILE, BLO_read_from_file(), free_main(), handle_subversion_warning(), BlendFileData::main, MEM_freeN(), NULL, setup_app_data(), and BlendFileData::user.
Referenced by load_file(), read_undosave(), WM_read_file(), and WM_read_homefile().
int BKE_read_file_from_memfile (struct bContext * C, struct MemFile * memfile, struct ReportList * reports)
Definition at line 418 of file blender.c.
References BKE_reports_prepend(), BLO_read_from_memfile(), CTX_data_main(), Global::main, Main::name, and setup_app_data().
Referenced by read_undosave().
int BKE_read_file_from_memory (struct bContext * C, char * filebuf, int filelength, struct ReportList * reports)
Definition at line 404 of file blender.c.
References BKE_reports_prepend(), BLO_read_from_memory(), and setup_app_data().
Referenced by WM_read_homefile().
void BKE_reset_undo (void)
Definition at line 626 of file blender.c.
References BLI_freelistN(), BLO_free_memfile(), ListBase::first, UndoElem::memfile, UndoElem::next, and NULL.
Referenced by WM_exit_ext(), WM_read_file(), and WM_read_homefile().
struct Main* BKE_undo_get_main (struct Scene ** scene) [read]
Definition at line 744 of file blender.c.
References BLO_read_from_memfile(), BlendFileData::curscene, Global::main, BlendFileData::main, MEM_freeN(), UndoElem::memfile, Main::name, and NULL.
Referenced by screen_render_invoke().
const char* BKE_undo_get_name (int nr, int * active)
Definition at line 671 of file blender.c.
References BLI_findlink(), UndoElem::name, and NULL.
Referenced by rna_undo_itemf().
char* BKE_undo_menu_string (void)
Definition at line 685 of file blender.c.
References BLI_dynstr_append(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), ListBase::first, UndoElem::name, and UndoElem::next.
void BKE_undo_name (struct bContext * C, const char * name)
Definition at line 648 of file blender.c.
References BKE_undo_step(), BLI_rfindstring(), and UndoElem::prev.
Referenced by ed_undo_step().
void BKE_undo_number (struct bContext * C, int nr)
Definition at line 641 of file blender.c.
References BKE_undo_step(), and BLI_findlink().
Referenced by undo_history_exec().
void BKE_undo_save_quit (void)
Definition at line 705 of file blender.c.
References BLI_make_file_string(), BLI_open(), BLI_temporary_dir(), MemFileChunk::buf, MemFile::chunks, curundo, FILE_MAX, ListBase::first, ListBase::last, UndoElem::memfile, MemFileChunk::next, NULL, O_BINARY, MemFileChunk::size, str, UserDef::uiflag, and USER_GLOBALUNDO.
Referenced by WM_exit_ext().
void BKE_undo_step (struct bContext * C, int step)
Definition at line 599 of file blender.c.
References Global::debug, G_DEBUG, UndoElem::name, UndoElem::next, NULL, UndoElem::prev, and read_undosave().
Referenced by BKE_undo_name(), BKE_undo_number(), and ed_undo_step().
int BKE_undo_valid (const char * name)
Definition at line 659 of file blender.c.
References BLI_rfindstring(), ListBase::first, ListBase::last, and UndoElem::prev.
Referenced by ED_undo_valid().
void BKE_userdef_free (void)
Definition at line 345 of file blender.c.
References wmKeyMapDiffItem::add_item, UserDef::addons, BLI_freelistN(), wmKeyMap::diff_items, ListBase::first, wmKeyMap::items, keymap_item_free(), MEM_freeN(), wmKeyMap::next, wmKeyMapDiffItem::next, wmKeyMapItem::next, wmKeyMapDiffItem::remove_item, UserDef::themes, UserDef::uifonts, UserDef::uistyles, and UserDef::user_keymaps.
Referenced by setup_app_data(), and WM_exit_ext().
void BKE_write_undo (struct bContext * C, const char * name)
Definition at line 501 of file blender.c.
References BLI_addtail(), BLI_make_file_string(), BLI_remlink(), BLI_snprintf(), BLI_strncpy(), BLI_temporary_dir(), BLO_free_memfile(), BLO_merge_memfile(), BLO_write_file(), BLO_write_file_mem(), CTX_data_main(), FILE_MAX, Global::fileflags, ListBase::first, G_FILE_HISTORY, ListBase::last, MEM_callocN(), MEM_freeN(), MEM_get_memory_in_use(), UndoElem::memfile, UndoElem::name, UndoElem::next, NULL, UndoElem::prev, UndoElem::str, UserDef::uiflag, UNDO_DISK, UserDef::undomemory, UndoElem::undosize, UserDef::undosteps, and USER_GLOBALUNDO.
Referenced by ED_undo_push(), WM_read_file(), and WM_read_homefile().
int blender_test_break (void)
Definition at line 442 of file blender.c.
References Global::afbreek, Global::background, and blender_test_break_cb.
Referenced by bake_image_exec(), BKE_ptcache_bake(), dynamicPaint_bakeImageSequence(), and screen_render_exec().
void free_blender (void)
Definition at line 103 of file blender.c.
References BKE_spacetypes_free(), BLI_cb_finalize(), free_main(), free_nodesystem(), IMB_exit(), IMB_moviecache_destruct(), Global::main, NULL, and seq_stripelem_cache_destruct().
Referenced by WM_exit_ext().
void initglobals (void)
Definition at line 121 of file blender.c.
References BLENDER_SUBVERSION, BLENDER_VERSION, BLI_snprintf(), Global::charmax, Global::charmin, Global::charstart, Global::f, G_SCRIPT_AUTOEXEC, G_WINDOWSTATE_USERDEF, Global::ima, Global::main, MEM_callocN(), UserDef::savetime, versionstr, and Global::windowstate.
Referenced by main().
void set_blender_test_break_cb (void(*)(void) func)
Definition at line 436 of file blender.c.
References blender_test_break_cb.
Referenced by WM_init().
Variable Documentation
char versionstr[]
Definition at line 98 of file blender.c.
Referenced by initglobals(), and stats_string().