Blender: btCylinderShapeZ Class Reference
btCylinderShapeZ Class Reference
#include <btCylinderShape.h>
Public Member Functions
btCylinderShapeZ (const btVector3 &halfExtents)
virtual btVector3 localGetSupportingVertexWithoutMargin (const btVector3 &vec) const
virtual void batchedUnitVectorGetSupportingVertexWithoutMargin (const btVector3 *vectors, btVector3 *supportVerticesOut, int numVectors) const
virtual const char * getName () const
virtual btScalar getRadius () const
Detailed Description
Definition at line 149 of file btCylinderShape.h.
Constructor & Destructor Documentation
btCylinderShapeZ::btCylinderShapeZ (const btVector3 & halfExtents)
Definition at line 36 of file btCylinderShape.cpp.
References btCylinderShape::m_upAxis.
Member Function Documentation
void btCylinderShapeZ::batchedUnitVectorGetSupportingVertexWithoutMargin (const btVector3 * vectors, btVector3 * supportVerticesOut, int numVectors) const [virtual]
Reimplemented from btCylinderShape.
Definition at line 260 of file btCylinderShape.cpp.
References CylinderLocalSupportZ(), btCylinderShape::getHalfExtentsWithoutMargin(), and i.
virtual const char* btCylinderShapeZ::getName (void) const [inline, virtual]
Reimplemented from btCylinderShape.
Definition at line 158 of file btCylinderShape.h.
virtual btScalar btCylinderShapeZ::getRadius () const [inline, virtual]
Reimplemented from btCylinderShape.
Definition at line 163 of file btCylinderShape.h.
References btCylinderShape::getHalfExtentsWithMargin().
btVector3 btCylinderShapeZ::localGetSupportingVertexWithoutMargin (const btVector3 & vec) const [virtual]
Reimplemented from btCylinderShape.
Definition at line 243 of file btCylinderShape.cpp.
References CylinderLocalSupportZ(), and btCylinderShape::getHalfExtentsWithoutMargin().
The documentation for this class was generated from the following files:
btCylinderShape.h
btCylinderShape.cpp