Blender: btSymMatrix< T > Struct Template Reference
btSymMatrix< T > Struct Template Reference
btSoftBody implementation by Nathanael Presson
#include <btSoftBodyInternals.h>
Public Member Functions
btSymMatrix ()
btSymMatrix (int n, const T &init=T())
void resize (int n, const T &init=T())
int index (int c, int r) const
T & operator() (int c, int r)
const T & operator() (int c, int r) const
Public Attributes
btAlignedObjectArray< T > store
int dim
Detailed Description
template<typename T>
struct btSymMatrix< T >
btSoftBody implementation by Nathanael Presson
Definition at line 33 of file btSoftBodyInternals.h.
Constructor & Destructor Documentation
template<typename T> btSymMatrix< T >::btSymMatrix () [inline]
Definition at line 35 of file btSoftBodyInternals.h.
template<typename T> btSymMatrix< T >::btSymMatrix (int n, const T & init = T()) [inline]
Definition at line 36 of file btSoftBodyInternals.h.
References init(), and btSymMatrix< T >::resize().
Member Function Documentation
template<typename T> int btSymMatrix< T >::index (int c, int r) const [inline]
Definition at line 38 of file btSoftBodyInternals.h.
References btAssert, btSwap(), and btSymMatrix< T >::dim.
Referenced by btSymMatrix< T >::operator()().
template<typename T> const T& btSymMatrix< T >::operator() (int c, int r) const [inline]
Definition at line 40 of file btSoftBodyInternals.h.
References btSymMatrix< T >::index(), and btSymMatrix< T >::store.
template<typename T> T& btSymMatrix< T >::operator() (int c, int r) [inline]
Definition at line 39 of file btSoftBodyInternals.h.
References btSymMatrix< T >::index(), and btSymMatrix< T >::store.
template<typename T> void btSymMatrix< T >::resize (int n, const T & init = T()) [inline]
Definition at line 37 of file btSoftBodyInternals.h.
References btSymMatrix< T >::dim, init(), and btSymMatrix< T >::store.
Referenced by btSymMatrix< T >::btSymMatrix().
Member Data Documentation
template<typename T> int btSymMatrix< T >::dim
Definition at line 42 of file btSoftBodyInternals.h.
Referenced by btSymMatrix< T >::index(), and btSymMatrix< T >::resize().
template<typename T> btAlignedObjectArray<T> btSymMatrix< T >::store
Definition at line 41 of file btSoftBodyInternals.h.
Referenced by btSymMatrix< T >::operator()(), and btSymMatrix< T >::resize().
The documentation for this struct was generated from the following file:
btSoftBodyInternals.h