Blender: CListValue Class Reference
CListValue Class Reference
#include <ListValue.h>
Public Member Functions
CListValue ()
virtual ~CListValue ()
void AddConfigurationData (CValue *menuvalue)
void Configure (CValue *menuvalue)
void Add (CValue *value)
virtual CValue * Calc (VALUE_OPERATOR op, CValue *val)
virtual CValue * CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue *val)
virtual double GetNumber ()
virtual CValue * GetReplica ()
void MergeList (CListValue *otherlist)
bool RemoveValue (CValue *val)
void SetReleaseOnDestruct (bool bReleaseContents)
bool SearchValue (CValue *val)
CValue * FindValue (const STR_String &name)
CValue * FindValue (const char *name)
void ReleaseAndRemoveAll ()
virtual void SetModified (bool bModified)
virtual bool IsModified ()
void Remove (int i)
void Resize (int num)
void SetValue (int i, CValue *val)
CValue * GetValue (int i)
int GetCount ()
virtual const STR_String & GetText ()
bool CheckEqual (CValue *first, CValue *second)
Detailed Description
Definition at line 24 of file ListValue.h.
Constructor & Destructor Documentation
CListValue::CListValue ()
Definition at line 35 of file ListValue.cpp.
Referenced by GetReplica().
CListValue::~CListValue () [virtual]
Definition at line 43 of file ListValue.cpp.
References i.
Member Function Documentation
void CListValue::Add (CValue * value)
Definition at line 239 of file ListValue.cpp.
Referenced by KX_Scene::AddAnimatedObject(), KX_Scene::AddNodeReplicaObject(), KX_Scene::AddReplicaObject(), bl_ConvertBlenderObject_Single(), BL_ConvertBlenderObjects(), KX_Scene::DelayedRemoveObject(), KX_Scene::DupliGroupRecurse(), KX_NetworkMessageSensor::Evaluate(), gameobject_from_blenderobject(), KX_TouchSensor::NewHandleCollision(), KX_NearSensor::NewHandleCollision(), KX_KetsjiEngine::PostProcessScene(), KX_GameObject::RemoveParent(), and walk_children().
void CListValue::AddConfigurationData (CValue * menuvalue)
CValue * CListValue::Calc (VALUE_OPERATOR op, CValue * val) [virtual]
Attention:
not implemented yet :(
Implements CValue.
Definition at line 213 of file ListValue.cpp.
References NULL.
CValue * CListValue::CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue * val) [virtual]
Implements CValue.
Definition at line 224 of file ListValue.cpp.
References NULL.
bool CListValue::CheckEqual (CValue * first, CValue * second)
Definition at line 191 of file ListValue.cpp.
References CValue::Calc(), CValue::GetText(), NULL, CValue::Release(), CBoolValue::sTrueString, and VALUE_EQL_OPERATOR.
void CListValue::Configure (CValue * menuvalue)
CValue * CListValue::FindValue (const STR_String & name)
Definition at line 126 of file ListValue.cpp.
References GetCount(), CValue::GetName(), GetValue(), i, and NULL.
CValue * CListValue::FindValue (const char * name)
Definition at line 135 of file ListValue.cpp.
References GetCount(), CValue::GetName(), GetValue(), i, and NULL.
int CListValue::GetCount () [inline]
Definition at line 61 of file ListValue.h.
Referenced by BL_ConvertBlenderObjects(), KX_Scene::CalculateVisibleMeshes(), KX_TouchSensor::Evaluate(), FindValue(), KX_BlenderSceneConverter::FreeBlendFile(), getGameOb(), getPhId(), GetText(), IsModified(), KX_Scene::LogicBeginFrame(), KX_Scene::LogicEndFrame(), MergeList(), KX_Scene::MergeScene(), RemoveValue(), KX_BlenderSceneConverter::resetNoneDynamicObjectToIpo(), KX_BlenderSceneConverter::ResetPhysicsObjectsAnimationIpo(), SearchValue(), SetModified(), KX_BlenderSceneConverter::TestHandlesPhysicsObjectToAnimationIpo(), KX_Scene::UpdateAnimations(), KX_Scene::UpdateMeshTransformations(), KX_Scene::UpdateObjectActivity(), and KX_BlenderSceneConverter::WritePhysicsObjectToAnimationIpo().
double CListValue::GetNumber () [virtual]
Implements CValue.
Definition at line 246 of file ListValue.cpp.
CValue * CListValue::GetReplica (void) [virtual]
Implements CValue.
Definition at line 74 of file ListValue.cpp.
References CListValue(), i, and CValue::ProcessReplica().
const STR_String & CListValue::GetText () [virtual]
Implements CValue.
Definition at line 56 of file ListValue.cpp.
References GetCount(), CValue::GetText(), GetValue(), gstrListRep, and i.
CValue* CListValue::GetValue (int i) [inline]
Definition at line 60 of file ListValue.h.
References assertd, and i.
Referenced by BL_ConvertBlenderObjects(), KX_Scene::CalculateVisibleMeshes(), FindValue(), KX_BlenderSceneConverter::FreeBlendFile(), getGameOb(), getPhId(), GetText(), IsModified(), KX_Scene::LogicBeginFrame(), KX_Scene::LogicEndFrame(), MergeList(), KX_Scene::MergeScene(), RemoveValue(), KX_BlenderSceneConverter::resetNoneDynamicObjectToIpo(), KX_BlenderSceneConverter::ResetPhysicsObjectsAnimationIpo(), SearchValue(), SetModified(), KX_BlenderSceneConverter::TestHandlesPhysicsObjectToAnimationIpo(), KX_Scene::UpdateAnimations(), KX_Scene::UpdateMeshTransformations(), KX_Scene::UpdateObjectActivity(), KX_BlenderSceneConverter::WritePhysicsObjectToAnimationIpo(), and KX_Scene::~KX_Scene().
bool CListValue::IsModified () [inline, virtual]
Reimplemented from CValue.
Definition at line 264 of file ListValue.cpp.
References GetCount(), GetValue(), i, and CValue::IsModified().
void CListValue::MergeList (CListValue * otherlist)
Definition at line 176 of file ListValue.cpp.
References CValue::AddRef(), GetCount(), GetValue(), i, Resize(), and SetValue().
Referenced by KX_Scene::MergeScene().
void CListValue::ReleaseAndRemoveAll ()
Definition at line 117 of file ListValue.cpp.
References i, and CValue::Release().
Referenced by KX_TouchSensor::EndFrame(), and KX_Scene::MergeScene().
void CListValue::Remove (int i)
Definition at line 109 of file ListValue.cpp.
References assertd, and i.
Referenced by KX_Scene::LogicEndFrame().
bool CListValue::RemoveValue (CValue * val)
Definition at line 161 of file ListValue.cpp.
References GetCount(), GetValue(), i, and SG_DList::Remove().
Referenced by BL_ConvertBlenderObjects(), KX_Scene::NewRemoveObject(), KX_Scene::RemoveAnimatedObject(), and KX_GameObject::SetParent().
void CListValue::Resize (int num)
Definition at line 102 of file ListValue.cpp.
Referenced by MergeList().
bool CListValue::SearchValue (CValue * val)
Definition at line 144 of file ListValue.cpp.
References GetCount(), GetValue(), and i.
Referenced by BL_ConvertBlenderObjects(), KX_Scene::DelayedRemoveObject(), KX_NearSensor::NewHandleCollision(), KX_TouchSensor::NewHandleCollision(), KX_GameObject::RemoveParent(), and KX_Scene::ReplicateLogic().
void CListValue::SetModified (bool bModified) [virtual]
Reimplemented from CValue.
Definition at line 253 of file ListValue.cpp.
References GetCount(), GetValue(), i, and CValue::SetModified().
void CListValue::SetReleaseOnDestruct (bool bReleaseContents)
Definition at line 154 of file ListValue.cpp.
void CListValue::SetValue (int i, CValue * val)
Definition at line 94 of file ListValue.cpp.
References assertd, and i.
Referenced by MergeList().
The documentation for this class was generated from the following files:
ListValue.h
ListValue.cpp