Blender: btSliderConstraint Class Reference
btSliderConstraint Class Reference
#include <btSliderConstraint.h>
Public Member Functions
btSliderConstraint (btRigidBody &rbA, btRigidBody &rbB, const btTransform &frameInA, const btTransform &frameInB, bool useLinearReferenceFrameA)
btSliderConstraint (btRigidBody &rbB, const btTransform &frameInB, bool useLinearReferenceFrameA)
virtual void getInfo1 (btConstraintInfo1 *info)
internal method used by the constraint solver, don't use them directly
void getInfo1NonVirtual (btConstraintInfo1 *info)
virtual void getInfo2 (btConstraintInfo2 *info)
internal method used by the constraint solver, don't use them directly
void getInfo2NonVirtual (btConstraintInfo2 *info, const btTransform &transA, const btTransform &transB, const btVector3 &linVelA, const btVector3 &linVelB, btScalar rbAinvMass, btScalar rbBinvMass)
const btRigidBody & getRigidBodyA () const
const btRigidBody & getRigidBodyB () const
const btTransform & getCalculatedTransformA () const
const btTransform & getCalculatedTransformB () const
const btTransform & getFrameOffsetA () const
const btTransform & getFrameOffsetB () const
btTransform & getFrameOffsetA ()
btTransform & getFrameOffsetB ()
btScalar getLowerLinLimit ()
void setLowerLinLimit (btScalar lowerLimit)
btScalar getUpperLinLimit ()
void setUpperLinLimit (btScalar upperLimit)
btScalar getLowerAngLimit ()
void setLowerAngLimit (btScalar lowerLimit)
btScalar getUpperAngLimit ()
void setUpperAngLimit (btScalar upperLimit)
bool getUseLinearReferenceFrameA ()
btScalar getSoftnessDirLin ()
btScalar getRestitutionDirLin ()
btScalar getDampingDirLin ()
btScalar getSoftnessDirAng ()
btScalar getRestitutionDirAng ()
btScalar getDampingDirAng ()
btScalar getSoftnessLimLin ()
btScalar getRestitutionLimLin ()
btScalar getDampingLimLin ()
btScalar getSoftnessLimAng ()
btScalar getRestitutionLimAng ()
btScalar getDampingLimAng ()
btScalar getSoftnessOrthoLin ()
btScalar getRestitutionOrthoLin ()
btScalar getDampingOrthoLin ()
btScalar getSoftnessOrthoAng ()
btScalar getRestitutionOrthoAng ()
btScalar getDampingOrthoAng ()
void setSoftnessDirLin (btScalar softnessDirLin)
void setRestitutionDirLin (btScalar restitutionDirLin)
void setDampingDirLin (btScalar dampingDirLin)
void setSoftnessDirAng (btScalar softnessDirAng)
void setRestitutionDirAng (btScalar restitutionDirAng)
void setDampingDirAng (btScalar dampingDirAng)
void setSoftnessLimLin (btScalar softnessLimLin)
void setRestitutionLimLin (btScalar restitutionLimLin)
void setDampingLimLin (btScalar dampingLimLin)
void setSoftnessLimAng (btScalar softnessLimAng)
void setRestitutionLimAng (btScalar restitutionLimAng)
void setDampingLimAng (btScalar dampingLimAng)
void setSoftnessOrthoLin (btScalar softnessOrthoLin)
void setRestitutionOrthoLin (btScalar restitutionOrthoLin)
void setDampingOrthoLin (btScalar dampingOrthoLin)
void setSoftnessOrthoAng (btScalar softnessOrthoAng)
void setRestitutionOrthoAng (btScalar restitutionOrthoAng)
void setDampingOrthoAng (btScalar dampingOrthoAng)
void setPoweredLinMotor (bool onOff)
bool getPoweredLinMotor ()
void setTargetLinMotorVelocity (btScalar targetLinMotorVelocity)
btScalar getTargetLinMotorVelocity ()
void setMaxLinMotorForce (btScalar maxLinMotorForce)
btScalar getMaxLinMotorForce ()
void setPoweredAngMotor (bool onOff)
bool getPoweredAngMotor ()
void setTargetAngMotorVelocity (btScalar targetAngMotorVelocity)
btScalar getTargetAngMotorVelocity ()
void setMaxAngMotorForce (btScalar maxAngMotorForce)
btScalar getMaxAngMotorForce ()
btScalar getLinearPos ()
bool getSolveLinLimit ()
btScalar getLinDepth ()
bool getSolveAngLimit ()
btScalar getAngDepth ()
void calculateTransforms (const btTransform &transA, const btTransform &transB)
void testLinLimits ()
void testAngLimits ()
btVector3 getAncorInA ()
btVector3 getAncorInB ()
bool getUseFrameOffset ()
void setUseFrameOffset (bool frameOffsetOnOff)
void setFrames (const btTransform &frameA, const btTransform &frameB)
virtual void setParam (int num, btScalar value, int axis=-1)
virtual btScalar getParam (int num, int axis=-1) const
return the local value of parameter
virtual int calculateSerializeBufferSize () const
virtual const char * serialize (void *dataBuffer, btSerializer *serializer) const
fills the dataBuffer and returns the struct name (and 0 on failure)
Protected Member Functions
void initParams ()
Protected Attributes
bool m_useSolveConstraintObsolete
for backwards compatibility during the transition to 'getInfo/getInfo2'
bool m_useOffsetForConstraintFrame
btTransform m_frameInA
btTransform m_frameInB
bool m_useLinearReferenceFrameA
btScalar m_lowerLinLimit
btScalar m_upperLinLimit
btScalar m_lowerAngLimit
btScalar m_upperAngLimit
btScalar m_softnessDirLin
btScalar m_restitutionDirLin
btScalar m_dampingDirLin
btScalar m_cfmDirLin
btScalar m_softnessDirAng
btScalar m_restitutionDirAng
btScalar m_dampingDirAng
btScalar m_cfmDirAng
btScalar m_softnessLimLin
btScalar m_restitutionLimLin
btScalar m_dampingLimLin
btScalar m_cfmLimLin
btScalar m_softnessLimAng
btScalar m_restitutionLimAng
btScalar m_dampingLimAng
btScalar m_cfmLimAng
btScalar m_softnessOrthoLin
btScalar m_restitutionOrthoLin
btScalar m_dampingOrthoLin
btScalar m_cfmOrthoLin
btScalar m_softnessOrthoAng
btScalar m_restitutionOrthoAng
btScalar m_dampingOrthoAng
btScalar m_cfmOrthoAng
bool m_solveLinLim
bool m_solveAngLim
int m_flags
btJacobianEntry m_jacLin [3]
btScalar m_jacLinDiagABInv [3]
btJacobianEntry m_jacAng [3]
btScalar m_timeStep
btTransform m_calculatedTransformA
btTransform m_calculatedTransformB
btVector3 m_sliderAxis
btVector3 m_realPivotAInW
btVector3 m_realPivotBInW
btVector3 m_projPivotInW
btVector3 m_delta
btVector3 m_depth
btVector3 m_relPosA
btVector3 m_relPosB
btScalar m_linPos
btScalar m_angPos
btScalar m_angDepth
btScalar m_kAngle
bool m_poweredLinMotor
btScalar m_targetLinMotorVelocity
btScalar m_maxLinMotorForce
btScalar m_accumulatedLinMotorImpulse
bool m_poweredAngMotor
btScalar m_targetAngMotorVelocity
btScalar m_maxAngMotorForce
btScalar m_accumulatedAngMotorImpulse
Detailed Description
Definition at line 63 of file btSliderConstraint.h.
Constructor & Destructor Documentation
btSliderConstraint::btSliderConstraint (btRigidBody & rbA, btRigidBody & rbB, const btTransform & frameInA, const btTransform & frameInB, bool useLinearReferenceFrameA)
Definition at line 83 of file btSliderConstraint.cpp.
References initParams().
btSliderConstraint::btSliderConstraint (btRigidBody & rbB, const btTransform & frameInB, bool useLinearReferenceFrameA)
not providing rigidbody A means implicitly using worldspace for body A
Definition at line 95 of file btSliderConstraint.cpp.
References btRigidBody::getCenterOfMassTransform(), initParams(), m_frameInA, and m_frameInB.
Member Function Documentation
SIMD_FORCE_INLINE int btSliderConstraint::calculateSerializeBufferSize () const [virtual]
Reimplemented from btTypedConstraint.
Definition at line 300 of file btSliderConstraint.h.
void btSliderConstraint::calculateTransforms (const btTransform & transA, const btTransform & transB)
Definition at line 159 of file btSliderConstraint.cpp.
References btTransform::getBasis(), btMatrix3x3::getColumn(), btTransform::getOrigin(), i, m_calculatedTransformA, m_calculatedTransformB, m_delta, m_depth, m_frameInA, m_frameInB, m_projPivotInW, m_realPivotAInW, m_realPivotBInW, m_sliderAxis, m_useLinearReferenceFrameA, and m_useSolveConstraintObsolete.
Referenced by getInfo1(), initParams(), and setFrames().
btVector3 btSliderConstraint::getAncorInA (void)
Definition at line 250 of file btSliderConstraint.cpp.
References btRigidBody::getCenterOfMassTransform(), btTransform::inverse(), m_lowerLinLimit, btTypedConstraint::m_rbA, m_realPivotAInW, m_sliderAxis, and m_upperLinLimit.
btVector3 btSliderConstraint::getAncorInB (void)
Definition at line 260 of file btSliderConstraint.cpp.
References btTransform::getOrigin(), and m_frameInB.
btScalar btSliderConstraint::getAngDepth () [inline]
Definition at line 246 of file btSliderConstraint.h.
References m_angDepth.
Referenced by getInfo2NonVirtual().
const btTransform& btSliderConstraint::getCalculatedTransformA () const [inline]
Definition at line 176 of file btSliderConstraint.h.
References m_calculatedTransformA.
Referenced by btDiscreteDynamicsWorld::debugDrawConstraint(), and getInfo2NonVirtual().
const btTransform& btSliderConstraint::getCalculatedTransformB () const [inline]
Definition at line 177 of file btSliderConstraint.h.
References m_calculatedTransformB.
Referenced by btDiscreteDynamicsWorld::debugDrawConstraint(), and getInfo2NonVirtual().
btScalar btSliderConstraint::getDampingDirAng () [inline]
Definition at line 196 of file btSliderConstraint.h.
References m_dampingDirAng.
btScalar btSliderConstraint::getDampingDirLin () [inline]
Definition at line 193 of file btSliderConstraint.h.
References m_dampingDirLin.
btScalar btSliderConstraint::getDampingLimAng () [inline]
Definition at line 202 of file btSliderConstraint.h.
References m_dampingLimAng.
Referenced by getInfo2NonVirtual().
btScalar btSliderConstraint::getDampingLimLin () [inline]
Definition at line 199 of file btSliderConstraint.h.
References m_dampingLimLin.
Referenced by getInfo2NonVirtual().
btScalar btSliderConstraint::getDampingOrthoAng () [inline]
Definition at line 208 of file btSliderConstraint.h.
References m_dampingOrthoAng.
btScalar btSliderConstraint::getDampingOrthoLin () [inline]
Definition at line 205 of file btSliderConstraint.h.
References m_dampingOrthoLin.
const btTransform& btSliderConstraint::getFrameOffsetA () const [inline]
Definition at line 178 of file btSliderConstraint.h.
References m_frameInA.
btTransform& btSliderConstraint::getFrameOffsetA () [inline]
Definition at line 180 of file btSliderConstraint.h.
References m_frameInA.
const btTransform& btSliderConstraint::getFrameOffsetB () const [inline]
Definition at line 179 of file btSliderConstraint.h.
References m_frameInB.
btTransform& btSliderConstraint::getFrameOffsetB () [inline]
Definition at line 181 of file btSliderConstraint.h.
References m_frameInB.
void btSliderConstraint::getInfo1 (btConstraintInfo1 * info) [virtual]
internal method used by the constraint solver, don't use them directly
Implements btTypedConstraint.
Definition at line 113 of file btSliderConstraint.cpp.
References calculateTransforms(), btRigidBody::getCenterOfMassTransform(), getPoweredAngMotor(), getPoweredLinMotor(), getSolveAngLimit(), getSolveLinLimit(), btTypedConstraint::btConstraintInfo1::m_numConstraintRows, btTypedConstraint::m_rbA, btTypedConstraint::m_rbB, m_useSolveConstraintObsolete, btTypedConstraint::btConstraintInfo1::nub, testAngLimits(), and testLinLimits().
void btSliderConstraint::getInfo1NonVirtual (btConstraintInfo1 * info)
Definition at line 141 of file btSliderConstraint.cpp.
References btTypedConstraint::btConstraintInfo1::m_numConstraintRows, and btTypedConstraint::btConstraintInfo1::nub.
void btSliderConstraint::getInfo2 (btConstraintInfo2 * info) [virtual]
internal method used by the constraint solver, don't use them directly
Implements btTypedConstraint.
Definition at line 148 of file btSliderConstraint.cpp.
References btRigidBody::getCenterOfMassTransform(), getInfo2NonVirtual(), btRigidBody::getInvMass(), btRigidBody::getLinearVelocity(), btTypedConstraint::m_rbA, and btTypedConstraint::m_rbB.
void btSliderConstraint::getInfo2NonVirtual (btConstraintInfo2 * info, const btTransform & transA, const btTransform & transB, const btVector3 & linVelA, const btVector3 & linVelB, btScalar rbAinvMass, btScalar rbBinvMass)
Definition at line 268 of file btSliderConstraint.cpp.
References BT_SLIDER_FLAGS_CFM_DIRANG, BT_SLIDER_FLAGS_CFM_DIRLIN, BT_SLIDER_FLAGS_CFM_LIMANG, BT_SLIDER_FLAGS_CFM_LIMLIN, BT_SLIDER_FLAGS_CFM_ORTANG, BT_SLIDER_FLAGS_CFM_ORTLIN, BT_SLIDER_FLAGS_ERP_LIMANG, BT_SLIDER_FLAGS_ERP_LIMLIN, BT_SLIDER_FLAGS_ERP_ORTANG, BT_SLIDER_FLAGS_ERP_ORTLIN, btAssert, btFabs(), btPlaneSpace1(), btSqrt(), btTypedConstraint::btConstraintInfo2::cfm, btTypedConstraint::btConstraintInfo2::erp, btTypedConstraint::btConstraintInfo2::fps, getAngDepth(), btRigidBody::getAngularVelocity(), btTransform::getBasis(), getCalculatedTransformA(), getCalculatedTransformB(), btMatrix3x3::getColumn(), getDampingLimAng(), getDampingLimLin(), getLinDepth(), getLowerAngLimit(), getLowerLinLimit(), getMaxAngMotorForce(), getMaxLinMotorForce(), btTypedConstraint::getMotorFactor(), btTransform::getOrigin(), getPoweredAngMotor(), getPoweredLinMotor(), getSoftnessLimAng(), getSoftnessLimLin(), getSolveAngLimit(), getSolveLinLimit(), getTargetAngMotorVelocity(), getTargetLinMotorVelocity(), getUpperAngLimit(), getUpperLinLimit(), i, m_angPos, m_cfmDirAng, m_cfmDirLin, m_cfmLimAng, m_cfmLimLin, m_cfmOrthoAng, m_cfmOrthoLin, btTypedConstraint::btConstraintInfo2::m_constraintError, m_depth, m_flags, btTypedConstraint::btConstraintInfo2::m_J1angularAxis, btTypedConstraint::btConstraintInfo2::m_J1linearAxis, btTypedConstraint::btConstraintInfo2::m_J2angularAxis, m_linPos, m_lowerAngLimit, btTypedConstraint::btConstraintInfo2::m_lowerLimit, m_lowerLinLimit, btTypedConstraint::m_rbA, btTypedConstraint::m_rbB, m_softnessLimAng, m_softnessLimLin, m_softnessOrthoAng, m_softnessOrthoLin, m_upperAngLimit, btTypedConstraint::btConstraintInfo2::m_upperLimit, m_upperLinLimit, m_useLinearReferenceFrameA, m_useOffsetForConstraintFrame, m_useSolveConstraintObsolete, p, btTypedConstraint::btConstraintInfo2::rowskip, SIMD_EPSILON, and SIMD_INFINITY.
Referenced by getInfo2().
btScalar btSliderConstraint::getLinDepth () [inline]
Definition at line 244 of file btSliderConstraint.h.
References m_depth.
Referenced by getInfo2NonVirtual().
btScalar btSliderConstraint::getLinearPos () [inline]
Definition at line 239 of file btSliderConstraint.h.
References m_linPos.
btScalar btSliderConstraint::getLowerAngLimit () [inline]
Definition at line 186 of file btSliderConstraint.h.
References m_lowerAngLimit.
Referenced by btDiscreteDynamicsWorld::debugDrawConstraint(), and getInfo2NonVirtual().
btScalar btSliderConstraint::getLowerLinLimit () [inline]
Definition at line 182 of file btSliderConstraint.h.
References m_lowerLinLimit.
Referenced by btDiscreteDynamicsWorld::debugDrawConstraint(), and getInfo2NonVirtual().
btScalar btSliderConstraint::getMaxAngMotorForce () [inline]
Definition at line 238 of file btSliderConstraint.h.
References m_maxAngMotorForce.
Referenced by getInfo2NonVirtual().
btScalar btSliderConstraint::getMaxLinMotorForce () [inline]
Definition at line 232 of file btSliderConstraint.h.
References m_maxLinMotorForce.
Referenced by getInfo2NonVirtual().
btScalar btSliderConstraint::getParam (int num, int axis = -1) const [virtual]
return the local value of parameter
Implements btTypedConstraint.
Definition at line 779 of file btSliderConstraint.cpp.
References BT_CONSTRAINT_CFM, BT_CONSTRAINT_STOP_CFM, BT_CONSTRAINT_STOP_ERP, BT_SLIDER_FLAGS_CFM_DIRANG, BT_SLIDER_FLAGS_CFM_DIRLIN, BT_SLIDER_FLAGS_CFM_LIMANG, BT_SLIDER_FLAGS_CFM_LIMLIN, BT_SLIDER_FLAGS_CFM_ORTANG, BT_SLIDER_FLAGS_CFM_ORTLIN, BT_SLIDER_FLAGS_ERP_LIMANG, BT_SLIDER_FLAGS_ERP_LIMLIN, BT_SLIDER_FLAGS_ERP_ORTANG, BT_SLIDER_FLAGS_ERP_ORTLIN, btAssertConstrParams, m_cfmDirAng, m_cfmDirLin, m_cfmLimAng, m_cfmLimLin, m_cfmOrthoAng, m_cfmOrthoLin, m_flags, m_softnessLimAng, m_softnessLimLin, m_softnessOrthoAng, m_softnessOrthoLin, and SIMD_INFINITY.
bool btSliderConstraint::getPoweredAngMotor () [inline]
Definition at line 234 of file btSliderConstraint.h.
References m_poweredAngMotor.
Referenced by getInfo1(), and getInfo2NonVirtual().
bool btSliderConstraint::getPoweredLinMotor () [inline]
Definition at line 228 of file btSliderConstraint.h.
References m_poweredLinMotor.
Referenced by getInfo1(), and getInfo2NonVirtual().
btScalar btSliderConstraint::getRestitutionDirAng () [inline]
Definition at line 195 of file btSliderConstraint.h.
References m_restitutionDirAng.
btScalar btSliderConstraint::getRestitutionDirLin () [inline]
Definition at line 192 of file btSliderConstraint.h.
References m_restitutionDirLin.
btScalar btSliderConstraint::getRestitutionLimAng () [inline]
Definition at line 201 of file btSliderConstraint.h.
References m_restitutionLimAng.
btScalar btSliderConstraint::getRestitutionLimLin () [inline]
Definition at line 198 of file btSliderConstraint.h.
References m_restitutionLimLin.
btScalar btSliderConstraint::getRestitutionOrthoAng () [inline]
Definition at line 207 of file btSliderConstraint.h.
References m_restitutionOrthoAng.
btScalar btSliderConstraint::getRestitutionOrthoLin () [inline]
Definition at line 204 of file btSliderConstraint.h.
References m_restitutionOrthoLin.
const btRigidBody& btSliderConstraint::getRigidBodyA () const [inline]
Reimplemented from btTypedConstraint.
Definition at line 174 of file btSliderConstraint.h.
References btTypedConstraint::m_rbA.
const btRigidBody& btSliderConstraint::getRigidBodyB () const [inline]
Reimplemented from btTypedConstraint.
Definition at line 175 of file btSliderConstraint.h.
References btTypedConstraint::m_rbB.
btScalar btSliderConstraint::getSoftnessDirAng () [inline]
Definition at line 194 of file btSliderConstraint.h.
References m_softnessDirAng.
btScalar btSliderConstraint::getSoftnessDirLin () [inline]
Definition at line 191 of file btSliderConstraint.h.
References m_softnessDirLin.
btScalar btSliderConstraint::getSoftnessLimAng () [inline]
Definition at line 200 of file btSliderConstraint.h.
References m_softnessLimAng.
Referenced by getInfo2NonVirtual().
btScalar btSliderConstraint::getSoftnessLimLin () [inline]
Definition at line 197 of file btSliderConstraint.h.
References m_softnessLimLin.
Referenced by getInfo2NonVirtual().
btScalar btSliderConstraint::getSoftnessOrthoAng () [inline]
Definition at line 206 of file btSliderConstraint.h.
References m_softnessOrthoAng.
btScalar btSliderConstraint::getSoftnessOrthoLin () [inline]
Definition at line 203 of file btSliderConstraint.h.
References m_softnessOrthoLin.
bool btSliderConstraint::getSolveAngLimit () [inline]
Definition at line 245 of file btSliderConstraint.h.
References m_solveAngLim.
Referenced by getInfo1(), and getInfo2NonVirtual().
bool btSliderConstraint::getSolveLinLimit () [inline]
Definition at line 243 of file btSliderConstraint.h.
References m_solveLinLim.
Referenced by getInfo1(), and getInfo2NonVirtual().
btScalar btSliderConstraint::getTargetAngMotorVelocity () [inline]
Definition at line 236 of file btSliderConstraint.h.
References m_targetAngMotorVelocity.
Referenced by getInfo2NonVirtual().
btScalar btSliderConstraint::getTargetLinMotorVelocity () [inline]
Definition at line 230 of file btSliderConstraint.h.
References m_targetLinMotorVelocity.
Referenced by getInfo2NonVirtual().
btScalar btSliderConstraint::getUpperAngLimit () [inline]
Definition at line 188 of file btSliderConstraint.h.
References m_upperAngLimit.
Referenced by btDiscreteDynamicsWorld::debugDrawConstraint(), and getInfo2NonVirtual().
btScalar btSliderConstraint::getUpperLinLimit () [inline]
Definition at line 184 of file btSliderConstraint.h.
References m_upperLinLimit.
Referenced by btDiscreteDynamicsWorld::debugDrawConstraint(), and getInfo2NonVirtual().
bool btSliderConstraint::getUseFrameOffset () [inline]
Definition at line 255 of file btSliderConstraint.h.
References m_useOffsetForConstraintFrame.
bool btSliderConstraint::getUseLinearReferenceFrameA () [inline]
Definition at line 190 of file btSliderConstraint.h.
References m_useLinearReferenceFrameA.
Referenced by btDiscreteDynamicsWorld::debugDrawConstraint().
void btSliderConstraint::initParams () [protected]
Definition at line 30 of file btSliderConstraint.cpp.
References calculateTransforms(), btRigidBody::getCenterOfMassTransform(), m_accumulatedAngMotorImpulse, m_accumulatedLinMotorImpulse, m_cfmDirAng, m_cfmDirLin, m_cfmLimAng, m_cfmLimLin, m_cfmOrthoAng, m_cfmOrthoLin, m_dampingDirAng, m_dampingDirLin, m_dampingLimAng, m_dampingLimLin, m_dampingOrthoAng, m_dampingOrthoLin, m_flags, m_lowerAngLimit, m_lowerLinLimit, m_maxAngMotorForce, m_maxLinMotorForce, m_poweredAngMotor, m_poweredLinMotor, btTypedConstraint::m_rbA, btTypedConstraint::m_rbB, m_restitutionDirAng, m_restitutionDirLin, m_restitutionLimAng, m_restitutionLimLin, m_restitutionOrthoAng, m_restitutionOrthoLin, m_softnessDirAng, m_softnessDirLin, m_softnessLimAng, m_softnessLimLin, m_softnessOrthoAng, m_softnessOrthoLin, m_targetAngMotorVelocity, m_targetLinMotorVelocity, m_upperAngLimit, m_upperLinLimit, m_useOffsetForConstraintFrame, SLIDER_CONSTRAINT_DEF_CFM, SLIDER_CONSTRAINT_DEF_DAMPING, SLIDER_CONSTRAINT_DEF_RESTITUTION, SLIDER_CONSTRAINT_DEF_SOFTNESS, and USE_OFFSET_FOR_CONSTANT_FRAME.
Referenced by btSliderConstraint().
SIMD_FORCE_INLINE const char * btSliderConstraint::serialize (void * dataBuffer, btSerializer * serializer) const [virtual]
fills the dataBuffer and returns the struct name (and 0 on failure)
Reimplemented from btTypedConstraint.
Definition at line 306 of file btSliderConstraint.h.
References btSliderConstraintData::m_angularLowerLimit, btSliderConstraintData::m_angularUpperLimit, m_frameInA, m_frameInB, btSliderConstraintData::m_linearLowerLimit, btSliderConstraintData::m_linearUpperLimit, m_lowerAngLimit, m_lowerLinLimit, btSliderConstraintData::m_rbAFrame, btSliderConstraintData::m_rbBFrame, btSliderConstraintData::m_typeConstraintData, m_upperAngLimit, m_upperLinLimit, btSliderConstraintData::m_useLinearReferenceFrameA, m_useLinearReferenceFrameA, m_useOffsetForConstraintFrame, btSliderConstraintData::m_useOffsetForConstraintFrame, and btTransform::serializeFloat().
void btSliderConstraint::setDampingDirAng (btScalar dampingDirAng) [inline]
Definition at line 214 of file btSliderConstraint.h.
References m_dampingDirAng.
void btSliderConstraint::setDampingDirLin (btScalar dampingDirLin) [inline]
Definition at line 211 of file btSliderConstraint.h.
References m_dampingDirLin.
void btSliderConstraint::setDampingLimAng (btScalar dampingLimAng) [inline]
Definition at line 220 of file btSliderConstraint.h.
References m_dampingLimAng.
void btSliderConstraint::setDampingLimLin (btScalar dampingLimLin) [inline]
Definition at line 217 of file btSliderConstraint.h.
References m_dampingLimLin.
void btSliderConstraint::setDampingOrthoAng (btScalar dampingOrthoAng) [inline]
Definition at line 226 of file btSliderConstraint.h.
References m_dampingOrthoAng.
void btSliderConstraint::setDampingOrthoLin (btScalar dampingOrthoLin) [inline]
Definition at line 223 of file btSliderConstraint.h.
References m_dampingOrthoLin.
void btSliderConstraint::setFrames (const btTransform & frameA, const btTransform & frameB) [inline]
Definition at line 258 of file btSliderConstraint.h.
References btTypedConstraint::buildJacobian(), calculateTransforms(), btRigidBody::getCenterOfMassTransform(), m_frameInA, m_frameInB, btTypedConstraint::m_rbA, and btTypedConstraint::m_rbB.
void btSliderConstraint::setLowerAngLimit (btScalar lowerLimit) [inline]
Definition at line 187 of file btSliderConstraint.h.
References btNormalizeAngle(), and m_lowerAngLimit.
void btSliderConstraint::setLowerLinLimit (btScalar lowerLimit) [inline]
Definition at line 183 of file btSliderConstraint.h.
References m_lowerLinLimit.
void btSliderConstraint::setMaxAngMotorForce (btScalar maxAngMotorForce) [inline]
Definition at line 237 of file btSliderConstraint.h.
References m_maxAngMotorForce.
void btSliderConstraint::setMaxLinMotorForce (btScalar maxLinMotorForce) [inline]
Definition at line 231 of file btSliderConstraint.h.
References m_maxLinMotorForce.
void btSliderConstraint::setParam (int num, btScalar value, int axis = -1) [virtual]
override the default global value of a parameter (such as ERP or CFM), optionally provide the axis (0..5). If no axis is provided, it uses the default axis for this constraint.
Implements btTypedConstraint.
Definition at line 703 of file btSliderConstraint.cpp.
References BT_CONSTRAINT_CFM, BT_CONSTRAINT_STOP_CFM, BT_CONSTRAINT_STOP_ERP, BT_SLIDER_FLAGS_CFM_DIRANG, BT_SLIDER_FLAGS_CFM_DIRLIN, BT_SLIDER_FLAGS_CFM_LIMANG, BT_SLIDER_FLAGS_CFM_LIMLIN, BT_SLIDER_FLAGS_CFM_ORTANG, BT_SLIDER_FLAGS_CFM_ORTLIN, BT_SLIDER_FLAGS_ERP_LIMANG, BT_SLIDER_FLAGS_ERP_LIMLIN, BT_SLIDER_FLAGS_ERP_ORTANG, BT_SLIDER_FLAGS_ERP_ORTLIN, btAssertConstrParams, m_cfmDirAng, m_cfmDirLin, m_cfmLimAng, m_cfmLimLin, m_cfmOrthoAng, m_cfmOrthoLin, m_flags, m_softnessLimAng, m_softnessLimLin, m_softnessOrthoAng, and m_softnessOrthoLin.
void btSliderConstraint::setPoweredAngMotor (bool onOff) [inline]
Definition at line 233 of file btSliderConstraint.h.
References m_poweredAngMotor.
void btSliderConstraint::setPoweredLinMotor (bool onOff) [inline]
Definition at line 227 of file btSliderConstraint.h.
References m_poweredLinMotor.
void btSliderConstraint::setRestitutionDirAng (btScalar restitutionDirAng) [inline]
Definition at line 213 of file btSliderConstraint.h.
References m_restitutionDirAng.
void btSliderConstraint::setRestitutionDirLin (btScalar restitutionDirLin) [inline]
Definition at line 210 of file btSliderConstraint.h.
References m_restitutionDirLin.
void btSliderConstraint::setRestitutionLimAng (btScalar restitutionLimAng) [inline]
Definition at line 219 of file btSliderConstraint.h.
References m_restitutionLimAng.
void btSliderConstraint::setRestitutionLimLin (btScalar restitutionLimLin) [inline]
Definition at line 216 of file btSliderConstraint.h.
References m_restitutionLimLin.
void btSliderConstraint::setRestitutionOrthoAng (btScalar restitutionOrthoAng) [inline]
Definition at line 225 of file btSliderConstraint.h.
References m_restitutionOrthoAng.
void btSliderConstraint::setRestitutionOrthoLin (btScalar restitutionOrthoLin) [inline]
Definition at line 222 of file btSliderConstraint.h.
References m_restitutionOrthoLin.
void btSliderConstraint::setSoftnessDirAng (btScalar softnessDirAng) [inline]
Definition at line 212 of file btSliderConstraint.h.
References m_softnessDirAng.
void btSliderConstraint::setSoftnessDirLin (btScalar softnessDirLin) [inline]
Definition at line 209 of file btSliderConstraint.h.
References m_softnessDirLin.
void btSliderConstraint::setSoftnessLimAng (btScalar softnessLimAng) [inline]
Definition at line 218 of file btSliderConstraint.h.
References m_softnessLimAng.
void btSliderConstraint::setSoftnessLimLin (btScalar softnessLimLin) [inline]
Definition at line 215 of file btSliderConstraint.h.
References m_softnessLimLin.
void btSliderConstraint::setSoftnessOrthoAng (btScalar softnessOrthoAng) [inline]
Definition at line 224 of file btSliderConstraint.h.
References m_softnessOrthoAng.
void btSliderConstraint::setSoftnessOrthoLin (btScalar softnessOrthoLin) [inline]
Definition at line 221 of file btSliderConstraint.h.
References m_softnessOrthoLin.
void btSliderConstraint::setTargetAngMotorVelocity (btScalar targetAngMotorVelocity) [inline]
Definition at line 235 of file btSliderConstraint.h.
References m_targetAngMotorVelocity.
void btSliderConstraint::setTargetLinMotorVelocity (btScalar targetLinMotorVelocity) [inline]
Definition at line 229 of file btSliderConstraint.h.
References m_targetLinMotorVelocity.
void btSliderConstraint::setUpperAngLimit (btScalar upperLimit) [inline]
Definition at line 189 of file btSliderConstraint.h.
References btNormalizeAngle(), and m_upperAngLimit.
void btSliderConstraint::setUpperLinLimit (btScalar upperLimit) [inline]
Definition at line 185 of file btSliderConstraint.h.
References m_upperLinLimit.
void btSliderConstraint::setUseFrameOffset (bool frameOffsetOnOff) [inline]
Definition at line 256 of file btSliderConstraint.h.
References m_useOffsetForConstraintFrame.
void btSliderConstraint::testAngLimits (void)
Definition at line 224 of file btSliderConstraint.cpp.
References btAdjustAngleToLimits(), btAtan2(), btTransform::getBasis(), btMatrix3x3::getColumn(), m_angDepth, m_angPos, m_calculatedTransformA, m_calculatedTransformB, m_lowerAngLimit, m_solveAngLim, m_upperAngLimit, and rot.
Referenced by getInfo1().
void btSliderConstraint::testLinLimits (void)
Definition at line 195 of file btSliderConstraint.cpp.
References m_depth, m_linPos, m_lowerLinLimit, m_solveLinLim, and m_upperLinLimit.
Referenced by getInfo1().
Member Data Documentation
btScalar btSliderConstraint::m_accumulatedAngMotorImpulse [protected]
Definition at line 153 of file btSliderConstraint.h.
Referenced by initParams().
btScalar btSliderConstraint::m_accumulatedLinMotorImpulse [protected]
Definition at line 148 of file btSliderConstraint.h.
Referenced by initParams().
btScalar btSliderConstraint::m_angDepth [protected]
Definition at line 142 of file btSliderConstraint.h.
Referenced by getAngDepth(), and testAngLimits().
btScalar btSliderConstraint::m_angPos [protected]
Definition at line 140 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), and testAngLimits().
btTransform btSliderConstraint::m_calculatedTransformA [protected]
Definition at line 127 of file btSliderConstraint.h.
Referenced by calculateTransforms(), getCalculatedTransformA(), and testAngLimits().
btTransform btSliderConstraint::m_calculatedTransformB [protected]
Definition at line 128 of file btSliderConstraint.h.
Referenced by calculateTransforms(), getCalculatedTransformB(), and testAngLimits().
btScalar btSliderConstraint::m_cfmDirAng [protected]
Definition at line 93 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getParam(), initParams(), and setParam().
btScalar btSliderConstraint::m_cfmDirLin [protected]
Definition at line 88 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getParam(), initParams(), and setParam().
btScalar btSliderConstraint::m_cfmLimAng [protected]
Definition at line 103 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getParam(), initParams(), and setParam().
btScalar btSliderConstraint::m_cfmLimLin [protected]
Definition at line 98 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getParam(), initParams(), and setParam().
btScalar btSliderConstraint::m_cfmOrthoAng [protected]
Definition at line 113 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getParam(), initParams(), and setParam().
btScalar btSliderConstraint::m_cfmOrthoLin [protected]
Definition at line 108 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getParam(), initParams(), and setParam().
btScalar btSliderConstraint::m_dampingDirAng [protected]
Definition at line 92 of file btSliderConstraint.h.
Referenced by getDampingDirAng(), initParams(), and setDampingDirAng().
btScalar btSliderConstraint::m_dampingDirLin [protected]
Definition at line 87 of file btSliderConstraint.h.
Referenced by getDampingDirLin(), initParams(), and setDampingDirLin().
btScalar btSliderConstraint::m_dampingLimAng [protected]
Definition at line 102 of file btSliderConstraint.h.
Referenced by getDampingLimAng(), initParams(), and setDampingLimAng().
btScalar btSliderConstraint::m_dampingLimLin [protected]
Definition at line 97 of file btSliderConstraint.h.
Referenced by getDampingLimLin(), initParams(), and setDampingLimLin().
btScalar btSliderConstraint::m_dampingOrthoAng [protected]
Definition at line 112 of file btSliderConstraint.h.
Referenced by getDampingOrthoAng(), initParams(), and setDampingOrthoAng().
btScalar btSliderConstraint::m_dampingOrthoLin [protected]
Definition at line 107 of file btSliderConstraint.h.
Referenced by getDampingOrthoLin(), initParams(), and setDampingOrthoLin().
btVector3 btSliderConstraint::m_delta [protected]
Definition at line 134 of file btSliderConstraint.h.
Referenced by calculateTransforms().
btVector3 btSliderConstraint::m_depth [protected]
Definition at line 135 of file btSliderConstraint.h.
Referenced by calculateTransforms(), getInfo2NonVirtual(), getLinDepth(), and testLinLimits().
int btSliderConstraint::m_flags [protected]
Definition at line 119 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getParam(), initParams(), and setParam().
btTransform btSliderConstraint::m_frameInA [protected]
Definition at line 69 of file btSliderConstraint.h.
Referenced by btSliderConstraint(), calculateTransforms(), getFrameOffsetA(), serialize(), and setFrames().
btTransform btSliderConstraint::m_frameInB [protected]
Definition at line 70 of file btSliderConstraint.h.
Referenced by btSliderConstraint(), calculateTransforms(), getAncorInB(), getFrameOffsetB(), serialize(), and setFrames().
btJacobianEntry btSliderConstraint::m_jacAng[3] [protected]
Definition at line 124 of file btSliderConstraint.h.
btJacobianEntry btSliderConstraint::m_jacLin[3] [protected]
Definition at line 121 of file btSliderConstraint.h.
btScalar btSliderConstraint::m_jacLinDiagABInv[3] [protected]
Definition at line 122 of file btSliderConstraint.h.
btScalar btSliderConstraint::m_kAngle [protected]
Definition at line 143 of file btSliderConstraint.h.
btScalar btSliderConstraint::m_linPos [protected]
Definition at line 139 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getLinearPos(), and testLinLimits().
btScalar btSliderConstraint::m_lowerAngLimit [protected]
Definition at line 77 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getLowerAngLimit(), initParams(), serialize(), setLowerAngLimit(), and testAngLimits().
btScalar btSliderConstraint::m_lowerLinLimit [protected]
Definition at line 74 of file btSliderConstraint.h.
Referenced by getAncorInA(), getInfo2NonVirtual(), getLowerLinLimit(), initParams(), serialize(), setLowerLinLimit(), and testLinLimits().
btScalar btSliderConstraint::m_maxAngMotorForce [protected]
Definition at line 152 of file btSliderConstraint.h.
Referenced by getMaxAngMotorForce(), initParams(), and setMaxAngMotorForce().
btScalar btSliderConstraint::m_maxLinMotorForce [protected]
Definition at line 147 of file btSliderConstraint.h.
Referenced by getMaxLinMotorForce(), initParams(), and setMaxLinMotorForce().
bool btSliderConstraint::m_poweredAngMotor [protected]
Definition at line 150 of file btSliderConstraint.h.
Referenced by getPoweredAngMotor(), initParams(), and setPoweredAngMotor().
bool btSliderConstraint::m_poweredLinMotor [protected]
Definition at line 145 of file btSliderConstraint.h.
Referenced by getPoweredLinMotor(), initParams(), and setPoweredLinMotor().
btVector3 btSliderConstraint::m_projPivotInW [protected]
Definition at line 133 of file btSliderConstraint.h.
Referenced by calculateTransforms().
btVector3 btSliderConstraint::m_realPivotAInW [protected]
Definition at line 131 of file btSliderConstraint.h.
Referenced by calculateTransforms(), and getAncorInA().
btVector3 btSliderConstraint::m_realPivotBInW [protected]
Definition at line 132 of file btSliderConstraint.h.
Referenced by calculateTransforms().
btVector3 btSliderConstraint::m_relPosA [protected]
Definition at line 136 of file btSliderConstraint.h.
btVector3 btSliderConstraint::m_relPosB [protected]
Definition at line 137 of file btSliderConstraint.h.
btScalar btSliderConstraint::m_restitutionDirAng [protected]
Definition at line 91 of file btSliderConstraint.h.
Referenced by getRestitutionDirAng(), initParams(), and setRestitutionDirAng().
btScalar btSliderConstraint::m_restitutionDirLin [protected]
Definition at line 86 of file btSliderConstraint.h.
Referenced by getRestitutionDirLin(), initParams(), and setRestitutionDirLin().
btScalar btSliderConstraint::m_restitutionLimAng [protected]
Definition at line 101 of file btSliderConstraint.h.
Referenced by getRestitutionLimAng(), initParams(), and setRestitutionLimAng().
btScalar btSliderConstraint::m_restitutionLimLin [protected]
Definition at line 96 of file btSliderConstraint.h.
Referenced by getRestitutionLimLin(), initParams(), and setRestitutionLimLin().
btScalar btSliderConstraint::m_restitutionOrthoAng [protected]
Definition at line 111 of file btSliderConstraint.h.
Referenced by getRestitutionOrthoAng(), initParams(), and setRestitutionOrthoAng().
btScalar btSliderConstraint::m_restitutionOrthoLin [protected]
Definition at line 106 of file btSliderConstraint.h.
Referenced by getRestitutionOrthoLin(), initParams(), and setRestitutionOrthoLin().
btVector3 btSliderConstraint::m_sliderAxis [protected]
Definition at line 130 of file btSliderConstraint.h.
Referenced by calculateTransforms(), and getAncorInA().
btScalar btSliderConstraint::m_softnessDirAng [protected]
Definition at line 90 of file btSliderConstraint.h.
Referenced by getSoftnessDirAng(), initParams(), and setSoftnessDirAng().
btScalar btSliderConstraint::m_softnessDirLin [protected]
Definition at line 85 of file btSliderConstraint.h.
Referenced by getSoftnessDirLin(), initParams(), and setSoftnessDirLin().
btScalar btSliderConstraint::m_softnessLimAng [protected]
Definition at line 100 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getParam(), getSoftnessLimAng(), initParams(), setParam(), and setSoftnessLimAng().
btScalar btSliderConstraint::m_softnessLimLin [protected]
Definition at line 95 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getParam(), getSoftnessLimLin(), initParams(), setParam(), and setSoftnessLimLin().
btScalar btSliderConstraint::m_softnessOrthoAng [protected]
Definition at line 110 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getParam(), getSoftnessOrthoAng(), initParams(), setParam(), and setSoftnessOrthoAng().
btScalar btSliderConstraint::m_softnessOrthoLin [protected]
Definition at line 105 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getParam(), getSoftnessOrthoLin(), initParams(), setParam(), and setSoftnessOrthoLin().
bool btSliderConstraint::m_solveAngLim [protected]
Definition at line 117 of file btSliderConstraint.h.
Referenced by getSolveAngLimit(), and testAngLimits().
bool btSliderConstraint::m_solveLinLim [protected]
Definition at line 116 of file btSliderConstraint.h.
Referenced by getSolveLinLimit(), and testLinLimits().
btScalar btSliderConstraint::m_targetAngMotorVelocity [protected]
Definition at line 151 of file btSliderConstraint.h.
Referenced by getTargetAngMotorVelocity(), initParams(), and setTargetAngMotorVelocity().
btScalar btSliderConstraint::m_targetLinMotorVelocity [protected]
Definition at line 146 of file btSliderConstraint.h.
Referenced by getTargetLinMotorVelocity(), initParams(), and setTargetLinMotorVelocity().
btScalar btSliderConstraint::m_timeStep [protected]
Definition at line 126 of file btSliderConstraint.h.
btScalar btSliderConstraint::m_upperAngLimit [protected]
Definition at line 78 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getUpperAngLimit(), initParams(), serialize(), setUpperAngLimit(), and testAngLimits().
btScalar btSliderConstraint::m_upperLinLimit [protected]
Definition at line 75 of file btSliderConstraint.h.
Referenced by getAncorInA(), getInfo2NonVirtual(), getUpperLinLimit(), initParams(), serialize(), setUpperLinLimit(), and testLinLimits().
bool btSliderConstraint::m_useLinearReferenceFrameA [protected]
Definition at line 72 of file btSliderConstraint.h.
Referenced by calculateTransforms(), getInfo2NonVirtual(), getUseLinearReferenceFrameA(), and serialize().
bool btSliderConstraint::m_useOffsetForConstraintFrame [protected]
Definition at line 68 of file btSliderConstraint.h.
Referenced by getInfo2NonVirtual(), getUseFrameOffset(), initParams(), serialize(), and setUseFrameOffset().
bool btSliderConstraint::m_useSolveConstraintObsolete [protected]
for backwards compatibility during the transition to 'getInfo/getInfo2'
Definition at line 67 of file btSliderConstraint.h.
Referenced by calculateTransforms(), getInfo1(), and getInfo2NonVirtual().
The documentation for this class was generated from the following files:
btSliderConstraint.h
btSliderConstraint.cpp