Blender: node_shader_add_shader.c File Reference
node_shader_add_shader.c File Reference
#include "../node_shader_util.h"
Functions
static int node_shader_gpu_add_shader (GPUMaterial *mat, bNode *UNUSED(node), GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_add_shader (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_add_shader_in []
static bNodeSocketTemplate sh_node_add_shader_out []
Function Documentation
static int node_shader_gpu_add_shader (GPUMaterial * mat, bNode * UNUSEDnode, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 43 of file node_shader_add_shader.c.
References GPU_stack_link().
Referenced by register_node_type_sh_add_shader().
void register_node_type_sh_add_shader (bNodeTreeType * ttype)
Definition at line 49 of file node_shader_add_shader.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_shader_gpu_add_shader(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_ADD_SHADER.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_add_shader_in[] [static]
Initial value:
 {
    {   SOCK_SHADER, 1, "Shader"},
    {   SOCK_SHADER, 1, "Shader"},
    {   -1, 0, ""   }
}
Definition at line 32 of file node_shader_add_shader.c.
bNodeSocketTemplate sh_node_add_shader_out[] [static]
Initial value:
 {
    {   SOCK_SHADER, 0, "Shader"},
    {   -1, 0, ""   }
}
Definition at line 38 of file node_shader_add_shader.c.