Blender: AUD_I3DDevice Class Reference
AUD_I3DDevice Class Reference
#include <AUD_I3DDevice.h>
Public Member Functions
virtual AUD_Vector3 getListenerLocation () const =0
virtual void setListenerLocation (const AUD_Vector3 &location)=0
virtual AUD_Vector3 getListenerVelocity () const =0
virtual void setListenerVelocity (const AUD_Vector3 &velocity)=0
virtual AUD_Quaternion getListenerOrientation () const =0
virtual void setListenerOrientation (const AUD_Quaternion &orientation)=0
virtual float getSpeedOfSound () const =0
virtual void setSpeedOfSound (float speed)=0
virtual float getDopplerFactor () const =0
virtual void setDopplerFactor (float factor)=0
virtual AUD_DistanceModel getDistanceModel () const =0
virtual void setDistanceModel (AUD_DistanceModel model)=0
Detailed Description
This class represents an output device for 3D sound.
Definition at line 39 of file AUD_I3DDevice.h.
Member Function Documentation
virtual AUD_DistanceModel AUD_I3DDevice::getDistanceModel () const [pure virtual]
Retrieves the distance model.
Returns:
The distance model.
Implemented in AUD_SoftwareDevice, and AUD_OpenALDevice.
Referenced by Device_get_distance_model().
virtual float AUD_I3DDevice::getDopplerFactor () const [pure virtual]
Retrieves the doppler factor. This value is a scaling factor for the velocity vectors of sources and listener which is used while calculating the doppler effect.
Returns:
The doppler factor.
Implemented in AUD_SoftwareDevice, and AUD_OpenALDevice.
Referenced by Device_get_doppler_factor().
virtual AUD_Vector3 AUD_I3DDevice::getListenerLocation () const [pure virtual]
Retrieves the listener location.
Returns:
The listener location.
Implemented in AUD_SoftwareDevice, and AUD_OpenALDevice.
Referenced by Device_get_listener_location().
virtual AUD_Quaternion AUD_I3DDevice::getListenerOrientation () const [pure virtual]
Retrieves the listener orientation.
Returns:
The listener orientation as quaternion.
Implemented in AUD_SoftwareDevice, and AUD_OpenALDevice.
Referenced by Device_get_listener_orientation().
virtual AUD_Vector3 AUD_I3DDevice::getListenerVelocity () const [pure virtual]
Retrieves the listener velocity.
Returns:
The listener velocity.
Implemented in AUD_SoftwareDevice, and AUD_OpenALDevice.
Referenced by Device_get_listener_velocity().
virtual float AUD_I3DDevice::getSpeedOfSound () const [pure virtual]
Retrieves the speed of sound. This value is needed for doppler effect calculation.
Returns:
The speed of sound.
Implemented in AUD_SoftwareDevice, and AUD_OpenALDevice.
Referenced by Device_get_speed_of_sound().
virtual void AUD_I3DDevice::setDistanceModel (AUD_DistanceModel model) [pure virtual]
Sets the distance model.
Parameters:
model distance model.
Implemented in AUD_SoftwareDevice, and AUD_OpenALDevice.
Referenced by AUD_setDistanceModel(), Device_set_distance_model(), and StartKetsjiShell().
virtual void AUD_I3DDevice::setDopplerFactor (float factor) [pure virtual]
Sets the doppler factor. This value is a scaling factor for the velocity vectors of sources and listener which is used while calculating the doppler effect.
Parameters:
factor The new doppler factor.
Implemented in AUD_SoftwareDevice, and AUD_OpenALDevice.
Referenced by AUD_setDopplerFactor(), Device_set_doppler_factor(), and StartKetsjiShell().
virtual void AUD_I3DDevice::setListenerLocation (const AUD_Vector3 & location) [pure virtual]
Sets the listener location.
Parameters:
location The new location.
Implemented in AUD_SoftwareDevice, and AUD_OpenALDevice.
Referenced by AUD_setListenerLocation(), and Device_set_listener_location().
virtual void AUD_I3DDevice::setListenerOrientation (const AUD_Quaternion & orientation) [pure virtual]
Sets the listener orientation.
Parameters:
orientation The new orientation as quaternion.
Implemented in AUD_SoftwareDevice, and AUD_OpenALDevice.
Referenced by AUD_setListenerOrientation(), and Device_set_listener_orientation().
virtual void AUD_I3DDevice::setListenerVelocity (const AUD_Vector3 & velocity) [pure virtual]
Sets the listener velocity.
Parameters:
velocity The new velocity.
Implemented in AUD_SoftwareDevice, and AUD_OpenALDevice.
Referenced by AUD_setListenerVelocity(), and Device_set_listener_velocity().
virtual void AUD_I3DDevice::setSpeedOfSound (float speed) [pure virtual]
Sets the speed of sound. This value is needed for doppler effect calculation.
Parameters:
speed The new speed of sound.
Implemented in AUD_SoftwareDevice, and AUD_OpenALDevice.
Referenced by AUD_setSpeedOfSound(), Device_set_speed_of_sound(), and StartKetsjiShell().
The documentation for this class was generated from the following file:
AUD_I3DDevice.h