Blender: bmesh_polygon.c File Reference
bmesh_polygon.c File Reference
BMesh
#include "BLI_math.h"
#include "BLI_array.h"
#include "MEM_guardedalloc.h"
#include "bmesh.h"
#include "intern/bmesh_private.h"
Defines
#define GETMIN2_AXIS(a, b, ma, mb, axis)
#define GETMIN2(a, b, ma, mb)
#define EPS (FLT_EPSILON * 15)
Functions
static short testedgesidef (const float v1[2], const float v2[2], const float v3[2])
TEST EDGE SIDE and POINT IN TRIANGLE.
static void calc_poly_normal (float normal[3], float verts[][3], int nverts)
COMPUTE POLY NORMAL.
static void bm_face_calc_poly_normal (BMFace *f)
COMPUTE POLY NORMAL (BMFace)
static void bm_face_calc_poly_normal_vertex_cos (BMFace *f, float n[3], float const (*vertexCos)[3])
COMPUTE POLY NORMAL (BMFace)
float BM_face_calc_area (BMFace *f)
float BM_face_calc_perimeter (BMFace *f)
void BM_face_calc_center_bounds (BMFace *f, float r_cent[3])
void BM_face_calc_center_mean (BMFace *f, float r_cent[3])
void calc_poly_plane (float(*verts)[3], const int nverts)
static void shrink_edgef (float v1[3], float v2[3], const float fac)
BM LEGAL EDGES.
void poly_rotate_plane (const float normal[3], float(*verts)[3], const int nverts)
POLY ROTATE PLANE.
void BM_edge_normals_update (BMEdge *e)
void BM_vert_normal_update (BMVert *v)
void BM_vert_normal_update_all (BMVert *v)
void BM_face_normal_update (BMFace *f)
BMESH UPDATE FACE NORMAL.
void BM_face_normal_update_vcos (BMesh *bm, BMFace *f, float no[3], float const (*vertexCos)[3])
void BM_face_normal_flip (BMesh *bm, BMFace *f)
Face Flip Normal.
static int linecrossesf (const float v1[2], const float v2[2], const float v3[2], const float v4[2])
int BM_face_point_inside_test (BMFace *f, const float co[3])
static int bm_face_goodline (float const (*projectverts)[3], BMFace *f, int v1i, int v2i, int v3i, int UNUSED(nvert))
static BMLoop * find_ear (BMFace *f, float(*verts)[3], const int nvert, const int use_beauty)
Find Ear.
void BM_face_triangulate (BMesh *bm, BMFace *f, float(*projectverts)[3], const short newedge_oflag, const short newface_oflag, BMFace **newfaces, const short use_beauty)
BMESH TRIANGULATE FACE.
void BM_face_legal_splits (BMesh *bm, BMFace *f, BMLoop *(*loops)[2], int len)
Detailed Description
This file contains code for dealing with polygons (normal/area calculation, tessellation, etc)
BMESH_TODO:
Add in Tessellator frontend that creates BMTriangles from copied faces
Add in Function that checks for and flags degenerate faces.
Definition in file bmesh_polygon.c.
Define Documentation
#define EPS (FLT_EPSILON * 15)
#define GETMIN2 (a, b, ma, mb)
Value:
{                                  \
        GETMIN2_AXIS(a, b, ma, mb, 0); \
        GETMIN2_AXIS(a, b, ma, mb, 1); \
    } (void)0
Referenced by linecrossesf().
#define GETMIN2_AXIS (a, b, ma, mb, axis)
Value:
{                                      \
        ma[axis] = MIN2(a[axis], b[axis]); \
        mb[axis] = MAX2(a[axis], b[axis]); \
    } (void)0
Function Documentation
void BM_edge_normals_update (BMEdge * e)
updates face and vertex normals incident on an edge
Definition at line 335 of file bmesh_polygon.c.
References BM_face_normal_update(), BM_FACES_OF_EDGE, BM_ITER_ELEM, BM_vert_normal_update(), BMEdge::v1, and BMEdge::v2.
Referenced by bmo_dissolve_limit_exec(), and bpy_bmedge_normal_update().
float BM_face_calc_area (BMFace * f)
get the area of the face
Definition at line 156 of file bmesh_polygon.c.
References area_poly_v3(), area_quad_v3(), area_tri_v3(), BLI_array_fixedstack_declare, BLI_array_fixedstack_free, BM_ITER_ELEM_INDEX, BM_LOOPS_OF_FACE, BM_NGON_STACK_SIZE, calc_poly_normal(), BMVert::co, copy_v3_v3(), i, BMFace::len, and BMLoop::v.
Referenced by bpy_bmface_calc_area(), and draw_uvs_stretch().
void BM_face_calc_center_bounds (BMFace * f, float r_cent[3])
computes center of face in 3d. uses center of bounding box.
Definition at line 206 of file bmesh_polygon.c.
References BM_FACE_FIRST_LOOP, BMVert::co, DO_MINMAX, INIT_MINMAX, max, mid_v3_v3v3(), min, BMLoop::next, and BMLoop::v.
Referenced by BM_editselection_center(), bmo_righthandfaces_exec(), bpy_bmface_calc_center_bounds(), and draw_em_measure_stats().
void BM_face_calc_center_mean (BMFace * f, float r_cent[3])
computes the center of a face, using the mean average
Definition at line 225 of file bmesh_polygon.c.
References add_v3_v3(), BM_FACE_FIRST_LOOP, BMVert::co, BMFace::len, mul_v3_fl(), BMLoop::next, BMLoop::v, and zero_v3().
Referenced by bmo_similarfaces_exec(), bpy_bmface_calc_center_mean(), draw_em_indices(), get_face_center(), and ngon_fake_area().
float BM_face_calc_perimeter (BMFace * f)
compute the perimeter of an ngon
Definition at line 190 of file bmesh_polygon.c.
References BM_FACE_FIRST_LOOP, BMVert::co, BMLoop::f, len_v3v3(), BMLoop::next, and BMLoop::v.
Referenced by bmo_similarfaces_exec(), and bpy_bmface_calc_perimeter().
static void bm_face_calc_poly_normal (BMFace * f) [static]
COMPUTE POLY NORMAL (BMFace)
Same as calc_poly_normal but operates directly on a bmesh face.
Definition at line 100 of file bmesh_polygon.c.
References add_newell_cross_v3_v3v3(), BM_FACE_FIRST_LOOP, BMVert::co, BMLoop::next, BMFace::no, normalize_v3_v3(), BMLoop::prev, UNLIKELY, and BMLoop::v.
Referenced by BM_face_normal_update().
static void bm_face_calc_poly_normal_vertex_cos (BMFace * f, float n[3], float const (*) vertexCos[3]) [static]
COMPUTE POLY NORMAL (BMFace)
Same as calc_poly_normal and bm_face_calc_poly_normal but takes an array of vertex locations.
Definition at line 129 of file bmesh_polygon.c.
References add_newell_cross_v3_v3v3(), BM_elem_index_get, BM_FACE_FIRST_LOOP, BMLoop::f, BMLoop::next, normalize_v3(), BMLoop::prev, UNLIKELY, BMLoop::v, and zero_v3().
Referenced by BM_face_normal_update_vcos().
static int bm_face_goodline (float const (*) projectverts[3], BMFace * f, int v1i, int v2i, int v3i, int UNUSEDnvert) [static]
Definition at line 614 of file bmesh_polygon.c.
References BM_elem_index_get, BM_FACE_FIRST_LOOP, copy_v3_v3(), FALSE, i, isect_point_tri_v2(), BMLoop::next, testedgesidef(), TRUE, and BMLoop::v.
Referenced by find_ear().
void BM_face_legal_splits (BMesh * bm, BMFace * f, BMLoop *(*) loops[2], int len)
each pair of loops defines a new edge, a split. this function goes through and sets pairs that are geometrically invalid to null. a split is invalid, if it forms a concave angle or it intersects other edges in the face, or it intersects another split. in the case of intersecting splits, only the first of the set of intersecting splits survives
Definition at line 849 of file bmesh_polygon.c.
References BLI_array_fixedstack_declare, BLI_array_fixedstack_free, BM_elem_index_set, BM_FACE_FIRST_LOOP, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BM_NGON_STACK_SIZE, calc_poly_normal(), BMVert::co, copy_v3_v3(), BMLoop::f, i, len(), BMFace::len, linecrossesf(), MAX2, mid_v3_v3v3(), BMLoop::next, NULL, poly_rotate_plane(), shrink_edgef(), and BMLoop::v.
Referenced by bmo_connectverts_exec().
void BM_face_normal_flip (BMesh * bm, BMFace * f)
Face Flip Normal.
Reverses the winding of a face.
Note:
This updates the calculated normal.
Definition at line 490 of file bmesh_polygon.c.
References bmesh_loop_reverse(), negate_v3(), and BMFace::no.
Referenced by bm_rationalize_normals(), bmo_extrude_face_region_exec(), bmo_reversefaces_exec(), bmo_righthandfaces_exec(), and bpy_bm_utils_face_flip().
void BM_face_normal_update (BMFace * f)
BMESH UPDATE FACE NORMAL.
Updates the stored normal for the given face. Requires that a buffer of sufficient length to store projected coordinates for all of the face's vertices is passed in as well.
Definition at line 403 of file bmesh_polygon.c.
References bm_face_calc_poly_normal(), BM_FACE_FIRST_LOOP, BMVert::co, BMFace::len, BMLoop::next, BMFace::no, normal_quad_v3(), normal_tri_v3(), BMLoop::v, and zero_v3().
Referenced by BM_edge_normals_update(), BM_face_point_inside_test(), BM_mesh_normals_update(), BM_vert_normal_update_all(), bmo_dissolve_limit_exec(), and bpy_bmface_normal_update().
void BM_face_normal_update_vcos (BMesh * bm, BMFace * f, float no[3], float const (*) vertexCos[3])
Definition at line 441 of file bmesh_polygon.c.
References BLI_assert, BM_elem_index_get, bm_face_calc_poly_normal_vertex_cos(), BM_FACE_FIRST_LOOP, BM_VERT, BMesh::elem_index_dirty, BMFace::len, BMLoop::next, normal_quad_v3(), normal_tri_v3(), and zero_v3().
Referenced by getEditDerivedBMesh().
int BM_face_point_inside_test (BMFace * f, const float co[3])
BM POINT IN FACE
Projects co onto face f, and returns true if it is inside the face bounds.
Note:
this uses a best-axis projection test, instead of projecting co directly into f's orientation space, so there might be accuracy issues.
Definition at line 567 of file bmesh_polygon.c.
References axis_dominant_v3(), BM_FACE_FIRST_LOOP, BM_face_normal_update(), BMVert::co, dot_v3v3(), BMLoop::f, FLT_MAX, BMFace::len, linecrossesf(), mul_v2_fl(), BMLoop::next, BMFace::no, BMLoop::prev, and BMLoop::v.
Referenced by knife_edge_in_face().
void BM_face_triangulate (BMesh * bm, BMFace * f, float(*) projectverts[3], const short newedge_oflag, const short newface_oflag, BMFace ** newfaces, const short use_beauty)
BMESH TRIANGULATE FACE.
Triangulates a face using a simple 'ear clipping' algorithm that tries to favor non-skinny triangles (angles less than 90 degrees).
If the triangulator has bits left over (or cannot triangulate at all) it uses a simple fan triangulation,
newfaces, if non-null, must be an array of BMFace pointers, with a length equal to f->len. it will be filled with the new triangles, and will be NULL-terminated.
Note:
newedgeflag sets a flag layer flag, obviously not the header flag.
bmesh_face_normal_update(bm, f, f->no, projectverts);
Definition at line 746 of file bmesh_polygon.c.
References BM_elem_index_set, BM_FACE_FIRST_LOOP, BM_face_split(), BM_VERT, BMO_elem_flag_enable, calc_poly_normal(), BMVert::co, copy_v3_v3(), BMLoop::e, BMesh::elem_index_dirty, BMLoop::f, find_ear(), i, BMFace::len, BMLoop::next, BMFace::no, NULL, poly_rotate_plane(), BMLoop::prev, TRUE, UNLIKELY, and BMLoop::v.
Referenced by bmo_triangulate_exec().
void BM_vert_normal_update (BMVert * v)
update a vert normal (but not the faces incident on it)
Definition at line 351 of file bmesh_polygon.c.
References BM_ITER_ELEM, BM_LOOPS_OF_VERT, BMVert::co, dot_v3v3(), BMLoop::f, len(), madd_v3_v3fl(), BMLoop::next, BMFace::no, BMVert::no, normalize_v3(), BMLoop::prev, saacos(), sub_v3_v3v3(), BMLoop::v, and zero_v3().
Referenced by BM_edge_normals_update(), BM_vert_normal_update_all(), bpy_bmvert_normal_update(), and calc_solidify_normals().
void BM_vert_normal_update_all (BMVert * v)
Definition at line 381 of file bmesh_polygon.c.
References BM_face_normal_update(), BM_FACES_OF_VERT, BM_ITER_ELEM, and BM_vert_normal_update().
Referenced by alter_co(), and mdisp_in_mdispquad().
static void calc_poly_normal (float normal[3], float verts[][3], int nverts) [static]
COMPUTE POLY NORMAL.
Computes the normal of a planar polygon See Graphics Gems for computing newell normal.
Definition at line 78 of file bmesh_polygon.c.
References add_newell_cross_v3_v3v3(), i, normalize_v3_v3(), and UNLIKELY.
Referenced by BM_face_calc_area(), BM_face_legal_splits(), and BM_face_triangulate().
void calc_poly_plane (float(*) verts[3], const int nverts)
COMPUTE POLY PLANE
Projects a set polygon's vertices to a plane defined by the average of its edges cross products
Definition at line 248 of file bmesh_polygon.c.
References add_v3_v3(), dot_v3v3(), i, madd_v3_v3fl(), norm(), normal_tri_v3(), normalize_v3(), UNLIKELY, and zero_v3().
static BMLoop* find_ear (BMFace * f, float(*) verts[3], const int nvert, const int use_beauty) [static]
Find Ear.
Used by tessellator to find the next triangle to 'clip off' of a polygon while tessellating.
Parameters:
use_beauty Currently only applies to quads, can be extended later on.
Definition at line 662 of file bmesh_polygon.c.
References ABS, angle(), angle_v3v3v3(), BM_edge_exists(), BM_elem_index_get, BM_FACE_FIRST_LOOP, bm_face_goodline(), BMVert::co, FALSE, BMVert::head, i, BMFace::len, len_squared_v3v3(), BMLoop::next, NULL, BMLoop::prev, TRUE, and BMLoop::v.
Referenced by BM_face_triangulate().
static int linecrossesf (const float v1[2], const float v2[2], const float v3[2], const float v4[2]) [static]
Definition at line 498 of file bmesh_polygon.c.
References ABS, EPS, FALSE, GETMIN2, testedgesidef(), and TRUE.
Referenced by BM_face_legal_splits(), and BM_face_point_inside_test().
void poly_rotate_plane (const float normal[3], float(*) verts[3], const int nverts)
POLY ROTATE PLANE.
Rotates a polygon so that it's normal is pointing towards the mesh Z axis
Definition at line 311 of file bmesh_polygon.c.
References angle(), axis_angle_to_quat(), cross_v3_v3v3(), dot_v3v3(), i, mul_m3_v3(), quat_to_mat3(), and saacos().
Referenced by BM_face_legal_splits(), BM_face_triangulate(), and quad_co().
static void shrink_edgef (float v1[3], float v2[3], const float fac) [static]
BM LEGAL EDGES.
takes in a face and a list of edges, and sets to NULL any edge in the list that bridges a concave region of the face or intersects any of the faces's edges.
Definition at line 288 of file bmesh_polygon.c.
References add_v3_v3v3(), mid_v3_v3v3(), mul_v3_fl(), and sub_v3_v3v3().
Referenced by BM_face_legal_splits().
static short testedgesidef (const float v1[2], const float v2[2], const float v3[2]) [static]
TEST EDGE SIDE and POINT IN TRIANGLE.
Point in triangle tests stolen from scanfill.c. Used for tessellator
Definition at line 53 of file bmesh_polygon.c.
References FALSE, and TRUE.
Referenced by bm_face_goodline(), and linecrossesf().