Blender: MT_Point2.h File Reference
MT_Point2.h File Reference
moto
#include "MT_Vector2.h"
Classes
class MT_Point2
Functions
MT_Point2 operator+ (const MT_Point2 &p, const MT_Vector2 &v)
MT_Point2 operator- (const MT_Point2 &p, const MT_Vector2 &v)
MT_Vector2 operator- (const MT_Point2 &p1, const MT_Point2 &p2)
MT_Scalar MT_distance (const MT_Point2 &p1, const MT_Point2 &p2)
MT_Scalar MT_distance2 (const MT_Point2 &p1, const MT_Point2 &p2)
MT_Point2 MT_lerp (const MT_Point2 &p1, const MT_Point2 &p2, MT_Scalar t)
Detailed Description
Definition in file MT_Point2.h.
Function Documentation
MT_Scalar MT_distance (const MT_Point2 & p1, const MT_Point2 & p2)
Definition at line 43 of file MT_Point2.inl.
References MT_Point2::distance().
MT_Scalar MT_distance2 (const MT_Point2 & p1, const MT_Point2 & p2)
Definition at line 47 of file MT_Point2.inl.
References MT_Point2::distance2().
MT_Point2 MT_lerp (const MT_Point2 & p1, const MT_Point2 & p2, MT_Scalar t)
Definition at line 51 of file MT_Point2.inl.
References MT_Point2::lerp().
MT_Point2 operator+ (const MT_Point2 & p, const MT_Vector2 & v)
Definition at line 31 of file MT_Point2.inl.
MT_Vector2 operator- (const MT_Point2 & p1, const MT_Point2 & p2)
Definition at line 39 of file MT_Point2.inl.
MT_Point2 operator- (const MT_Point2 & p, const MT_Vector2 & v)
Definition at line 35 of file MT_Point2.inl.