Blender: KDL::ChainJntToJacSolver Class Reference
KDL::ChainJntToJacSolver Class Reference
Class to calculate the jacobian of a general KDL::Chain, it is used by other solvers. It should not be used outside of KDL.
#include <chainjnttojacsolver.hpp>
Public Member Functions
ChainJntToJacSolver (const Chain &chain)
~ChainJntToJacSolver ()
int JntToJac (const JntArray &q_in, Jacobian &jac)
Detailed Description
Class to calculate the jacobian of a general KDL::Chain, it is used by other solvers. It should not be used outside of KDL.
Definition at line 40 of file chainjnttojacsolver.hpp.
Constructor & Destructor Documentation
KDL::ChainJntToJacSolver::ChainJntToJacSolver (const Chain & chain)
Definition at line 29 of file chainjnttojacsolver.cpp.
KDL::ChainJntToJacSolver::~ChainJntToJacSolver ()
Definition at line 34 of file chainjnttojacsolver.cpp.
Member Function Documentation
int KDL::ChainJntToJacSolver::JntToJac (const JntArray & q_in, Jacobian & jac)
Calculate the jacobian expressed in the base frame of the chain, with reference point at the end effector of the *chain. The alghoritm is similar to the one used in KDL::ChainFkSolverVel_recursive
Parameters:
q_in input joint positions
jac output jacobian
Returns:
always returns 0
Definition at line 38 of file chainjnttojacsolver.cpp.
References assert, KDL::changeBase(), KDL::Jacobian::columns(), KDL::Segment::getFrameToTip(), KDL::Segment::getJoint(), KDL::Joint::getNDof(), KDL::Chain::getNrOfJoints(), KDL::Chain::getNrOfSegments(), KDL::Chain::getSegment(), i, KDL::Frame::Identity(), KDL::Frame::M, KDL::Frame::p, KDL::Joint::pose(), KDL::Twist::RefPoint(), KDL::JntArray::rows(), KDL::SetToZero(), KDL::Segment::twist(), and KDL::Jacobian::twists.
Referenced by iTaSC::Distance::updateJacobian().
The documentation for this class was generated from the following files:
chainjnttojacsolver.hpp
chainjnttojacsolver.cpp