Blender: rna_render.c File Reference
rna_render.c File Reference
RNA
#include <stdlib.h>
#include "DNA_scene_types.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "RE_engine.h"
#include "RE_pipeline.h"
#include "BKE_utildefines.h"
Functions
static void rna_def_render_engine (BlenderRNA *brna)
static void rna_def_render_result (BlenderRNA *brna)
static void rna_def_render_layer (BlenderRNA *brna)
static void rna_def_render_pass (BlenderRNA *brna)
void RNA_def_render (BlenderRNA *brna)
Detailed Description
Definition in file rna_render.c.
Function Documentation
void RNA_def_render (BlenderRNA * brna)
Definition at line 529 of file rna_render.c.
References rna_def_render_engine(), rna_def_render_layer(), rna_def_render_pass(), and rna_def_render_result().
static void rna_def_render_engine (BlenderRNA * brna) [static]
Definition at line 267 of file rna_render.c.
References FUNC_REGISTER_OPTIONAL, NULL, PROP_BOOLEAN, PROP_NEVER_CLAMP, PROP_NONE, PROP_POINTER, PROP_REGISTER, PROP_REGISTER_OPTIONAL, PROP_REQUIRED, PROP_STRING, PROP_TRANSLATE, RE_ENGINE_ANIMATION, RE_ENGINE_PREVIEW, RE_USE_POSTPROCESS, RE_USE_PREVIEW, RE_USE_SHADING_NODES, RNA_def_boolean(), RNA_def_enum_flag(), RNA_def_float(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_refine_func(), RNA_def_struct_register_funcs(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), RNA_define_verify_sdna(), and wm_report_items.
Referenced by RNA_def_render().
static void rna_def_render_layer (BlenderRNA * brna) [static]
Definition at line 424 of file rna_render.c.
References FUNC_USE_REPORTS, NULL, PROP_COLLECTION, PROP_DYNAMIC, PROP_FLOAT, PROP_NONE, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_property(), RNA_def_property_collection_funcs(), RNA_def_property_dynamic_array_funcs(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_multi_array(), RNA_def_property_struct_type(), rna_def_render_layer_common(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_ui_text(), and RNA_define_verify_sdna().
Referenced by RNA_def_render().
static void rna_def_render_pass (BlenderRNA * brna) [static]
Definition at line 463 of file rna_render.c.
References NULL, PROP_DYNAMIC, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_dynamic_array_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_int_sdna(), RNA_def_property_multi_array(), RNA_def_property_string_sdna(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_ui_text(), RNA_define_verify_sdna(), SCE_PASS_AO, SCE_PASS_COMBINED, SCE_PASS_DIFFUSE, SCE_PASS_DIFFUSE_COLOR, SCE_PASS_DIFFUSE_DIRECT, SCE_PASS_DIFFUSE_INDIRECT, SCE_PASS_EMIT, SCE_PASS_ENVIRONMENT, SCE_PASS_GLOSSY_COLOR, SCE_PASS_GLOSSY_DIRECT, SCE_PASS_GLOSSY_INDIRECT, SCE_PASS_INDEXMA, SCE_PASS_INDEXOB, SCE_PASS_MIST, SCE_PASS_NORMAL, SCE_PASS_REFLECT, SCE_PASS_REFRACT, SCE_PASS_RGBA, SCE_PASS_SHADOW, SCE_PASS_SPEC, SCE_PASS_TRANSM_COLOR, SCE_PASS_TRANSM_DIRECT, SCE_PASS_TRANSM_INDIRECT, SCE_PASS_UV, SCE_PASS_VECTOR, and SCE_PASS_Z.
Referenced by RNA_def_render().
static void rna_def_render_result (BlenderRNA * brna) [static]
Definition at line 388 of file rna_render.c.
References FILE_MAX, FUNC_USE_REPORTS, NULL, PROP_COLLECTION, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_ui_description(), RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_struct_type(), RNA_def_string_file_name(), RNA_def_struct(), RNA_def_struct_ui_text(), and RNA_define_verify_sdna().
Referenced by RNA_def_render().