Blender: GHOST_DisplayManagerWin32 Class Reference
GHOST_DisplayManagerWin32 Class Reference
#include <GHOST_DisplayManagerWin32.h>
Public Member Functions
GHOST_DisplayManagerWin32 (void)
virtual GHOST_TSuccess getNumDisplays (GHOST_TUns8 &numDisplays) const
virtual GHOST_TSuccess getNumDisplaySettings (GHOST_TUns8 display, GHOST_TInt32 &numSettings) const
virtual GHOST_TSuccess getDisplaySetting (GHOST_TUns8 display, GHOST_TInt32 index, GHOST_DisplaySetting &setting) const
virtual GHOST_TSuccess getCurrentDisplaySetting (GHOST_TUns8 display, GHOST_DisplaySetting &setting) const
virtual GHOST_TSuccess setCurrentDisplaySetting (GHOST_TUns8 display, const GHOST_DisplaySetting &setting)
Detailed Description
Manages system displays (WIN32 implementation).
Author:
Maarten Gribnau
Date:
September 21, 2001
Definition at line 48 of file GHOST_DisplayManagerWin32.h.
Constructor & Destructor Documentation
GHOST_DisplayManagerWin32::GHOST_DisplayManagerWin32 (void)
Constructor.
Definition at line 48 of file GHOST_DisplayManagerWin32.cpp.
Member Function Documentation
GHOST_TSuccess GHOST_DisplayManagerWin32::getCurrentDisplaySetting (GHOST_TUns8 display, GHOST_DisplaySetting & setting) const [virtual]
Returns the current setting for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
setting The current setting of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 113 of file GHOST_DisplayManagerWin32.cpp.
References getDisplaySetting(), GHOST_ASSERT, and GHOST_DisplayManager::kMainDisplay.
GHOST_TSuccess GHOST_DisplayManagerWin32::getDisplaySetting (GHOST_TUns8 display, GHOST_TInt32 index, GHOST_DisplaySetting & setting) const [virtual]
Returns the current setting for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
index The setting index to be returned.
setting The setting of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 80 of file GHOST_DisplayManagerWin32.cpp.
References GHOST_DisplaySetting::bpp, GHOST_DisplaySetting::frequency, GHOST_ASSERT, GHOST_kFailure, GHOST_kSuccess, GHOST_DisplayManager::kMainDisplay, NULL, GHOST_DisplaySetting::xPixels, and GHOST_DisplaySetting::yPixels.
Referenced by getCurrentDisplaySetting().
GHOST_TSuccess GHOST_DisplayManagerWin32::getNumDisplays (GHOST_TUns8 & numDisplays) const [virtual]
Returns the number of display devices on this system.
Parameters:
numDisplays The number of displays on this system.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 53 of file GHOST_DisplayManagerWin32.cpp.
References GHOST_kFailure, and GHOST_kSuccess.
GHOST_TSuccess GHOST_DisplayManagerWin32::getNumDisplaySettings (GHOST_TUns8 display, GHOST_TInt32 & numSettings) const [virtual]
Returns the number of display settings for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
setting The number of settings of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 68 of file GHOST_DisplayManagerWin32.cpp.
References GHOST_ASSERT, GHOST_kSuccess, GHOST_DisplayManager::kMainDisplay, and NULL.
GHOST_TSuccess GHOST_DisplayManagerWin32::setCurrentDisplaySetting (GHOST_TUns8 display, const GHOST_DisplaySetting & setting) [virtual]
Changes the current setting for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
setting The current setting of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 120 of file GHOST_DisplayManagerWin32.cpp.
References GHOST_DisplaySetting::bpp, GHOST_DisplayManager::findMatch(), GHOST_DisplaySetting::frequency, GHOST_ASSERT, GHOST_kFailure, GHOST_kSuccess, i, GHOST_DisplayManager::kMainDisplay, LONG, NULL, GHOST_DisplaySetting::xPixels, and GHOST_DisplaySetting::yPixels.
The documentation for this class was generated from the following files:
GHOST_DisplayManagerWin32.h
GHOST_DisplayManagerWin32.cpp