Blender: MOD_uvproject.c File Reference
MOD_uvproject.c File Reference
modifiers
#include "DNA_meshdata_types.h"
#include "DNA_camera_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_math.h"
#include "BLI_string.h"
#include "BLI_uvproject.h"
#include "BLI_utildefines.h"
#include "BKE_camera.h"
#include "BKE_mesh.h"
#include "BKE_DerivedMesh.h"
#include "MOD_modifiertypes.h"
#include "MOD_util.h"
#include "MEM_guardedalloc.h"
#include "depsgraph_private.h"
Classes
struct Projector
Typedefs
typedef struct Projector Projector
Functions
static void initData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static CustomDataMask requiredDataMask (Object *UNUSED(ob), ModifierData *UNUSED(md))
static void foreachObjectLink (ModifierData *md, Object *ob, ObjectWalkFunc walk, void *userData)
static void foreachIDLink (ModifierData *md, Object *ob, IDWalkFunc walk, void *userData)
static void updateDepgraph (ModifierData *md, DagForest *forest, struct Scene *UNUSED(scene), Object *UNUSED(ob), DagNode *obNode)
static DerivedMesh * uvprojectModifier_do (UVProjectModifierData *umd, Object *ob, DerivedMesh *dm)
static DerivedMesh * applyModifier (ModifierData *md, Object *ob, DerivedMesh *derivedData, int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
static DerivedMesh * applyModifierEM (ModifierData *md, Object *ob, struct BMEditMesh *UNUSED(editData), DerivedMesh *derivedData)
Variables
ModifierTypeInfo modifierType_UVProject
Detailed Description
Definition in file MOD_uvproject.c.
Typedef Documentation
typedef struct Projector Projector
Function Documentation
static DerivedMesh* applyModifier (ModifierData * md, Object * ob, DerivedMesh * derivedData, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 391 of file MOD_uvproject.c.
References uvprojectModifier_do().
Referenced by applyModifierEM().
static DerivedMesh* applyModifierEM (ModifierData * md, Object * ob, struct BMEditMesh * UNUSEDeditData, DerivedMesh * derivedData) [static]
Definition at line 404 of file MOD_uvproject.c.
References applyModifier().
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 73 of file MOD_uvproject.c.
References UVProjectModifierData::aspectx, UVProjectModifierData::aspecty, BLI_strncpy(), UVProjectModifierData::flags, i, UVProjectModifierData::image, MOD_UVPROJECT_MAXPROJECTORS, UVProjectModifierData::num_projectors, UVProjectModifierData::projectors, UVProjectModifierData::scalex, UVProjectModifierData::scaley, and UVProjectModifierData::uvlayer_name.
static void foreachIDLink (ModifierData * md, Object * ob, IDWalkFunc walk, void * userData) [static]
Definition at line 111 of file MOD_uvproject.c.
References foreachObjectLink(), and UVProjectModifierData::image.
static void foreachObjectLink (ModifierData * md, Object * ob, ObjectWalkFunc walk, void * userData) [static]
Definition at line 101 of file MOD_uvproject.c.
References i, MOD_UVPROJECT_MAXPROJECTORS, and UVProjectModifierData::projectors.
Referenced by foreachIDLink().
static void initData (ModifierData * md) [static]
Definition at line 59 of file MOD_uvproject.c.
References UVProjectModifierData::aspectx, UVProjectModifierData::aspecty, UVProjectModifierData::flags, i, UVProjectModifierData::image, MOD_UVPROJECT_MAXPROJECTORS, NULL, UVProjectModifierData::num_projectors, UVProjectModifierData::projectors, UVProjectModifierData::scalex, and UVProjectModifierData::scaley.
static CustomDataMask requiredDataMask (Object * UNUSEDob, ModifierData * UNUSEDmd) [static]
Definition at line 91 of file MOD_uvproject.c.
References CD_MASK_MTFACE.
static void updateDepgraph (ModifierData * md, DagForest * forest, struct Scene * UNUSEDscene, Object * UNUSEDob, DagNode * obNode) [static]
Definition at line 122 of file MOD_uvproject.c.
References dag_add_relation(), dag_get_node(), DAG_RL_DATA_DATA, DAG_RL_OB_DATA, i, UVProjectModifierData::num_projectors, and UVProjectModifierData::projectors.
static DerivedMesh* uvprojectModifier_do (UVProjectModifierData * umd, Object * ob, DerivedMesh * dm) [static]
Definition at line 147 of file MOD_uvproject.c.
References UVProjectModifierData::aspectx, UVProjectModifierData::aspecty, CAM_PANORAMA, CAM_PERSP, camera_sensor_fit(), CAMERA_SENSOR_FIT_HOR, camera_sensor_size(), CD_MLOOPUV, CD_MTEXPOLY, Camera::clipend, Camera::clipsta, co, copy_m4_m4(), copy_v2_v2(), copy_v3_v3(), CustomData_duplicate_referenced_layer_named(), CustomData_has_layer(), CustomData_validate_layer_name(), Object::data, DerivedMesh::dirty, DM_DIRTY_TESS_CDLAYERS, dot_v3v3(), Camera::flag, UVProjectModifierData::flags, DerivedMesh::getLoopArray, DerivedMesh::getNumLoops, DerivedMesh::getNumPolys, DerivedMesh::getNumVerts, DerivedMesh::getPolyArray, DerivedMesh::getVertCos, i, if(), UVProjectModifierData::image, invert_m4_m4(), Camera::lens, DerivedMesh::loopData, MAX_CUSTOMDATA_LAYER_NAME, MEM_callocN(), MEM_freeN(), mesh_calc_poly_normal_coords(), MOD_UVPROJECT_MAXPROJECTORS, MOD_UVPROJECT_OVERRIDEIMAGE, mt, mul_m4_v3(), mul_mat3_m4_fl(), mul_mat3_m4_v3(), mul_project_m4_v3(), mult_m4_m4m4(), Projector::normal, NULL, UVProjectModifierData::num_projectors, Projector::ob, OB_CAMERA, Object::obmat, Camera::ortho_scale, orthographic_m4(), perspective_m4(), DerivedMesh::polyData, project_camera_info(), project_camera_info_scale(), project_from_camera(), UVProjectModifierData::projectors, Projector::projmat, UVProjectModifierData::scalex, UVProjectModifierData::scaley, Camera::sensor_fit, Camera::sensor_x, Camera::sensor_y, Camera::shiftx, Camera::shifty, MTexPoly::tpage, Camera::type, Object::type, Projector::uci, unit_m4(), UVProjectModifierData::uvlayer_name, and MLoop::v.
Referenced by applyModifier().
Variable Documentation
ModifierTypeInfo modifierType_UVProject
Initial value:
 {
                  "UVProject",
            "UVProjectModifierData",
            sizeof(UVProjectModifierData),
                  eModifierTypeType_NonGeometrical,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_SupportsMapping
                            | eModifierTypeFlag_SupportsEditmode
                            | eModifierTypeFlag_EnableInEditmode,
              copyData,
           NULL,
        NULL,
         NULL,
      NULL,
         applyModifier,
       applyModifierEM,
              initData,
      requiredDataMask,
              NULL,
            NULL,
        updateDepgraph,
         NULL,
        NULL,
     foreachObjectLink,
         foreachIDLink,
        NULL,
}
Definition at line 412 of file MOD_uvproject.c.