Blender: WTURBULENCE Class Reference
WTURBULENCE Class Reference
#include <WTURBULENCE.h>
Public Member Functions
WTURBULENCE (int xResSm, int yResSm, int zResSm, int amplify, int noisetype)
virtual ~WTURBULENCE ()
destructor
void setNoise (int type)
void initBlenderRNA (float *strength)
void stepTurbulenceReadable (float dt, float *xvel, float *yvel, float *zvel, unsigned char *obstacles)
void stepTurbulenceFull (float dt, float *xvel, float *yvel, float *zvel, unsigned char *obstacles)
void advectTextureCoordinates (float dtOrg, float *xvel, float *yvel, float *zvel, float *tempBig1, float *tempBig2)
void resetTextureCoordinates (float *_eigMin, float *_eigMax)
void computeEnergy (float *energy, float *xvel, float *yvel, float *zvel, unsigned char *obstacles)
Vec3 WVelocity (Vec3 p)
Vec3 WVelocityWithJacobian (Vec3 p, float *xUnwarped, float *yUnwarped, float *zUnwarped)
float * getDensityBig ()
float * getArrayTcU ()
float * getArrayTcV ()
float * getArrayTcW ()
Vec3Int getResSm ()
Vec3Int getResBig ()
int getOctaves ()
void computeEigenvalues (float *_eigMin, float *_eigMax)
void decomposeEnergy (float *energy, float *_highFreqEnergy)
Public Attributes
float * _strength
int _amplify
int _octaves
float _cullingThreshold
int _xResBig
int _yResBig
int _zResBig
Vec3Int _resBig
Vec3 _invResBig
int _totalCellsBig
int _slabSizeBig
int _xResSm
int _yResSm
int _zResSm
Vec3Int _resSm
Vec3 _invResSm
int _totalCellsSm
int _slabSizeSm
float * _densityBig
float * _densityBigOld
float * _tcU
float * _tcV
float * _tcW
float * _tcTemp
float * _noiseTile
int _totalStepsBig
Detailed Description
Main WTURBULENCE class, stores large density array etc.
Definition at line 35 of file WTURBULENCE.h.
Constructor & Destructor Documentation
WTURBULENCE::WTURBULENCE (int xResSm, int yResSm, int zResSm, int amplify, int noisetype)
Definition at line 54 of file WTURBULENCE.cpp.
References _amplify, _cullingThreshold, _densityBig, _densityBigOld, _invResBig, _invResSm, _noiseTile, _octaves, _resBig, _resSm, _slabSizeBig, _slabSizeSm, _tcTemp, _tcU, _tcV, _tcW, _totalCellsBig, _totalCellsSm, _totalStepsBig, _xResBig, _xResSm, _yResBig, _yResSm, _zResBig, _zResSm, i, log(), noiseTileSize, and setNoise().
WTURBULENCE::~WTURBULENCE () [virtual]
destructor
Definition at line 134 of file WTURBULENCE.cpp.
References _densityBig, _densityBigOld, _noiseTile, _tcTemp, _tcU, _tcV, and _tcW.
Member Function Documentation
void WTURBULENCE::advectTextureCoordinates (float dtOrg, float * xvel, float * yvel, float * zvel, float * tempBig1, float * tempBig2)
Definition at line 288 of file WTURBULENCE.cpp.
References _resSm, _tcTemp, _tcU, _tcV, _tcW, FLUID_3D::advectFieldMacCormack1(), FLUID_3D::advectFieldMacCormack2(), FLUID_3D::copyBorderX(), FLUID_3D::copyBorderY(), FLUID_3D::copyBorderZ(), NULL, and SWAP_POINTERS().
Referenced by stepTurbulenceFull().
void WTURBULENCE::computeEigenvalues (float * _eigMin, float * _eigMax)
Definition at line 322 of file WTURBULENCE.cpp.
References _resSm, _slabSizeSm, _tcU, _tcV, _tcW, _xResSm, _yResSm, _zResSm, computeEigenvalues3x3(), computeLU(), isNonsingular(), MAX, MAX3V(), MIN, MIN3V(), minDx(), minDy(), and minDz().
void WTURBULENCE::computeEnergy (float * energy, float * xvel, float * yvel, float * zvel, unsigned char * obstacles)
Definition at line 434 of file WTURBULENCE.cpp.
References _resSm, _slabSizeSm, _totalCellsSm, _xResSm, _yResSm, _zResSm, FLUID_3D::copyBorderX(), FLUID_3D::copyBorderY(), FLUID_3D::copyBorderZ(), MARCHED, RETIRED, and sum().
Referenced by stepTurbulenceFull().
void WTURBULENCE::decomposeEnergy (float * energy, float * _highFreqEnergy)
Definition at line 398 of file WTURBULENCE.cpp.
References _tcTemp, _xResSm, _yResSm, _zResSm, downsampleXNeumann(), downsampleYNeumann(), downsampleZNeumann(), upsampleXNeumann(), upsampleYNeumann(), and upsampleZNeumann().
Referenced by stepTurbulenceFull().
float* WTURBULENCE::getArrayTcU () [inline]
Definition at line 66 of file WTURBULENCE.h.
float* WTURBULENCE::getArrayTcV () [inline]
Definition at line 67 of file WTURBULENCE.h.
float* WTURBULENCE::getArrayTcW () [inline]
Definition at line 68 of file WTURBULENCE.h.
float* WTURBULENCE::getDensityBig () [inline]
Definition at line 65 of file WTURBULENCE.h.
Referenced by smoke_dissolve_wavelet(), and smoke_turbulence_get_density().
int WTURBULENCE::getOctaves () [inline]
Definition at line 72 of file WTURBULENCE.h.
Vec3Int WTURBULENCE::getResBig () [inline]
Definition at line 71 of file WTURBULENCE.h.
Referenced by smoke_dissolve_wavelet(), and smoke_turbulence_get_res().
Vec3Int WTURBULENCE::getResSm () [inline]
Definition at line 70 of file WTURBULENCE.h.
void WTURBULENCE::initBlenderRNA (float * strength)
Definition at line 175 of file WTURBULENCE.cpp.
References _strength.
Referenced by smoke_initWaveletBlenderRNA().
void WTURBULENCE::resetTextureCoordinates (float * _eigMin, float * _eigMax)
Definition at line 367 of file WTURBULENCE.cpp.
References _resSm, _slabSizeSm, _tcU, _tcV, _tcW, _xResSm, _yResSm, and _zResSm.
Referenced by stepTurbulenceFull().
void WTURBULENCE::setNoise (int type)
Definition at line 153 of file WTURBULENCE.cpp.
References _noiseTile, and generateTile_WAVELET().
Referenced by smoke_turbulence_set_noise(), and WTURBULENCE().
void WTURBULENCE::stepTurbulenceFull (float dt, float * xvel, float * yvel, float * zvel, unsigned char * obstacles)
Definition at line 750 of file WTURBULENCE.cpp.
References _amplify, _cullingThreshold, _densityBig, _densityBigOld, _octaves, _resBig, _resSm, _slabSizeBig, _slabSizeSm, _strength, _tcTemp, _tcU, _tcV, _tcW, _totalCellsBig, _totalCellsSm, _totalStepsBig, _xResBig, _xResSm, _yResSm, _zResBig, _zResSm, FLUID_3D::advectFieldMacCormack1(), FLUID_3D::advectFieldMacCormack2(), advectTextureCoordinates(), computeEigenvalues3x3(), computeEnergy(), computeLU(), decomposeEnergy(), fabs(), i, isNonsingular(), INTERPOLATE::lerp3d(), INTERPOLATE::lerp3dToFloat(), INTERPOLATE::lerp3dVec(), MAX3V(), MIN3V(), minDx(), minDy(), minDz(), NULL, persistence, resetTextureCoordinates(), FLUID_3D::setNeumannX(), FLUID_3D::setNeumannY(), FLUID_3D::setNeumannZ(), FLUID_3D::setZeroBorder(), FLUID_3D::setZeroX(), FLUID_3D::setZeroY(), FLUID_3D::setZeroZ(), solveLU3x3(), sqrt(), sqrtf, SWAP_POINTERS(), and WVelocityWithJacobian().
Referenced by smoke_turbulence_step().
void WTURBULENCE::stepTurbulenceReadable (float dt, float * xvel, float * yvel, float * zvel, unsigned char * obstacles)
Vec3 WTURBULENCE::WVelocity (Vec3 p)
Definition at line 515 of file WTURBULENCE.cpp.
References _noiseTile, NOISE_TILE_SIZE, WNoiseDx(), WNoiseDy(), and WNoiseDz().
Vec3 WTURBULENCE::WVelocityWithJacobian (Vec3 p, float * xUnwarped, float * yUnwarped, float * zUnwarped)
Definition at line 541 of file WTURBULENCE.cpp.
References _noiseTile, NOISE_TILE_SIZE, WNoiseDx(), WNoiseDy(), and WNoiseDz().
Referenced by stepTurbulenceFull().
Member Data Documentation
int WTURBULENCE::_amplify
Definition at line 80 of file WTURBULENCE.h.
Referenced by stepTurbulenceFull(), and WTURBULENCE().
float WTURBULENCE::_cullingThreshold
Definition at line 84 of file WTURBULENCE.h.
Referenced by stepTurbulenceFull(), and WTURBULENCE().
float* WTURBULENCE::_densityBig
Definition at line 112 of file WTURBULENCE.h.
Referenced by smoke_turbulence_export(), stepTurbulenceFull(), WTURBULENCE(), and ~WTURBULENCE().
float* WTURBULENCE::_densityBigOld
Definition at line 113 of file WTURBULENCE.h.
Referenced by smoke_turbulence_export(), stepTurbulenceFull(), WTURBULENCE(), and ~WTURBULENCE().
Vec3 WTURBULENCE::_invResBig
Definition at line 100 of file WTURBULENCE.h.
Referenced by WTURBULENCE().
Vec3 WTURBULENCE::_invResSm
Definition at line 108 of file WTURBULENCE.h.
Referenced by WTURBULENCE().
float* WTURBULENCE::_noiseTile
Definition at line 122 of file WTURBULENCE.h.
Referenced by setNoise(), WTURBULENCE(), WVelocity(), WVelocityWithJacobian(), and ~WTURBULENCE().
int WTURBULENCE::_octaves
Definition at line 81 of file WTURBULENCE.h.
Referenced by stepTurbulenceFull(), and WTURBULENCE().
Vec3Int WTURBULENCE::_resBig
Definition at line 99 of file WTURBULENCE.h.
Referenced by stepTurbulenceFull(), and WTURBULENCE().
Vec3Int WTURBULENCE::_resSm
Definition at line 107 of file WTURBULENCE.h.
Referenced by advectTextureCoordinates(), computeEigenvalues(), computeEnergy(), resetTextureCoordinates(), stepTurbulenceFull(), and WTURBULENCE().
int WTURBULENCE::_slabSizeBig
Definition at line 102 of file WTURBULENCE.h.
Referenced by stepTurbulenceFull(), and WTURBULENCE().
int WTURBULENCE::_slabSizeSm
Definition at line 110 of file WTURBULENCE.h.
Referenced by computeEigenvalues(), computeEnergy(), resetTextureCoordinates(), stepTurbulenceFull(), and WTURBULENCE().
float* WTURBULENCE::_strength
Definition at line 75 of file WTURBULENCE.h.
Referenced by initBlenderRNA(), and stepTurbulenceFull().
float* WTURBULENCE::_tcTemp
Definition at line 119 of file WTURBULENCE.h.
Referenced by advectTextureCoordinates(), decomposeEnergy(), stepTurbulenceFull(), WTURBULENCE(), and ~WTURBULENCE().
float* WTURBULENCE::_tcU
Definition at line 116 of file WTURBULENCE.h.
Referenced by advectTextureCoordinates(), computeEigenvalues(), resetTextureCoordinates(), smoke_turbulence_export(), stepTurbulenceFull(), WTURBULENCE(), and ~WTURBULENCE().
float* WTURBULENCE::_tcV
Definition at line 117 of file WTURBULENCE.h.
Referenced by advectTextureCoordinates(), computeEigenvalues(), resetTextureCoordinates(), smoke_turbulence_export(), stepTurbulenceFull(), WTURBULENCE(), and ~WTURBULENCE().
float* WTURBULENCE::_tcW
Definition at line 118 of file WTURBULENCE.h.
Referenced by advectTextureCoordinates(), computeEigenvalues(), resetTextureCoordinates(), smoke_turbulence_export(), stepTurbulenceFull(), WTURBULENCE(), and ~WTURBULENCE().
int WTURBULENCE::_totalCellsBig
Definition at line 101 of file WTURBULENCE.h.
Referenced by stepTurbulenceFull(), and WTURBULENCE().
int WTURBULENCE::_totalCellsSm
Definition at line 109 of file WTURBULENCE.h.
Referenced by computeEnergy(), stepTurbulenceFull(), and WTURBULENCE().
int WTURBULENCE::_totalStepsBig
Definition at line 126 of file WTURBULENCE.h.
Referenced by stepTurbulenceFull(), and WTURBULENCE().
int WTURBULENCE::_xResBig
Definition at line 96 of file WTURBULENCE.h.
Referenced by stepTurbulenceFull(), and WTURBULENCE().
int WTURBULENCE::_xResSm
Definition at line 104 of file WTURBULENCE.h.
Referenced by computeEigenvalues(), computeEnergy(), decomposeEnergy(), resetTextureCoordinates(), stepTurbulenceFull(), and WTURBULENCE().
int WTURBULENCE::_yResBig
Definition at line 97 of file WTURBULENCE.h.
Referenced by WTURBULENCE().
int WTURBULENCE::_yResSm
Definition at line 105 of file WTURBULENCE.h.
Referenced by computeEigenvalues(), computeEnergy(), decomposeEnergy(), resetTextureCoordinates(), stepTurbulenceFull(), and WTURBULENCE().
int WTURBULENCE::_zResBig
Definition at line 98 of file WTURBULENCE.h.
Referenced by stepTurbulenceFull(), and WTURBULENCE().
int WTURBULENCE::_zResSm
Definition at line 106 of file WTURBULENCE.h.
Referenced by computeEigenvalues(), computeEnergy(), decomposeEnergy(), resetTextureCoordinates(), stepTurbulenceFull(), and WTURBULENCE().
The documentation for this class was generated from the following files:
WTURBULENCE.h
WTURBULENCE.cpp