Blender: BLI_jitter.h File Reference
BLI_jitter.h File Reference
blenlib
Functions
void BLI_initjit (float *jitarr, int num)
void BLI_jitterate1 (float *jit1, float *jit2, int num, float rad1)
void BLI_jitterate2 (float *jit1, float *jit2, int num, float rad2)
Detailed Description
Definition in file BLI_jitter.h.
Function Documentation
void BLI_initjit (float * jitarr, int num)
Definition at line 142 of file jitter.c.
References BLI_drand(), BLI_jitterate1(), BLI_jitterate2(), BLI_srand(), floorf, i, MEM_freeN(), MEM_mallocN(), and sqrtf.
Referenced by give_jitter_tab(), init_render_jit(), RE_zbuf_accumulate_vecblur(), and screen_opengl_render_apply().
void BLI_jitterate1 (float * jit1, float * jit2, int num, float rad1)
Definition at line 44 of file jitter.c.
References fabsf, floorf, i, len(), and sqrt().
Referenced by BLI_initjit(), and init_mv_jit().
void BLI_jitterate2 (float * jit1, float * jit2, int num, float rad2)
Definition at line 102 of file jitter.c.
References fabsf, floorf, and i.
Referenced by BLI_initjit(), and init_mv_jit().