Blender: screen_edit.c File Reference
screen_edit.c File Reference
screen
#include <string.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "DNA_scene_types.h"
#include "DNA_userdef_types.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_node.h"
#include "BKE_screen.h"
#include "BKE_scene.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_image.h"
#include "ED_object.h"
#include "ED_screen.h"
#include "ED_screen_types.h"
#include "ED_fileselect.h"
#include "ED_clip.h"
#include "ED_render.h"
#include "UI_interface.h"
#include "wm_subwindow.h"
#include "screen_intern.h"
Defines
#define SCR_BACK 0.55
#define SCR_ROUND 12
Functions
static ScrVert * screen_addvert (bScreen *sc, short x, short y)
static void sortscrvert (ScrVert **v1, ScrVert **v2)
static ScrEdge * screen_addedge (bScreen *sc, ScrVert *v1, ScrVert *v2)
ScrEdge * screen_findedge (bScreen *sc, ScrVert *v1, ScrVert *v2)
void removedouble_scrverts (bScreen *sc)
void removenotused_scrverts (bScreen *sc)
void removedouble_scredges (bScreen *sc)
void removenotused_scredges (bScreen *sc)
int scredge_is_horizontal (ScrEdge *se)
ScrEdge * screen_find_active_scredge (bScreen *sc, int mx, int my)
static ScrArea * screen_addarea (bScreen *sc, ScrVert *v1, ScrVert *v2, ScrVert *v3, ScrVert *v4, short headertype, short spacetype)
static void screen_delarea (bContext *C, bScreen *sc, ScrArea *sa)
static short testsplitpoint (ScrArea *sa, char dir, float fac)
ScrArea * area_split (bScreen *sc, ScrArea *sa, char dir, float fac, int merge)
bScreen * ED_screen_add (wmWindow *win, Scene *scene, const char *name)
static void screen_copy (bScreen *to, bScreen *from)
int area_getorientation (ScrArea *sa, ScrArea *sb)
int screen_area_join (bContext *C, bScreen *scr, ScrArea *sa1, ScrArea *sa2)
void select_connected_scredge (bScreen *sc, ScrEdge *edge)
static void screen_test_scale (bScreen *sc, int winsizex, int winsizey)
static void draw_horizontal_join_shape (ScrArea *sa, char dir)
static void draw_vertical_join_shape (ScrArea *sa, char dir)
static void draw_join_shape (ScrArea *sa, char dir)
static void scrarea_draw_shape_dark (ScrArea *sa, char dir)
static void scrarea_draw_shape_light (ScrArea *sa, char UNUSED(dir))
static void drawscredge_area_draw (int sizex, int sizey, short x1, short y1, short x2, short y2, short a)
static void drawscredge_area (ScrArea *sa, int sizex, int sizey, int center)
bScreen * ED_screen_duplicate (wmWindow *win, bScreen *sc)
static void region_cursor_set (wmWindow *win, int swinid)
void ED_screen_do_listen (bContext *C, wmNotifier *note)
void ED_screen_draw (wmWindow *win)
static void screen_refresh_headersizes (void)
void ED_screen_refresh (wmWindowManager *wm, wmWindow *win)
void ED_screens_initialize (wmWindowManager *wm)
void ED_region_exit (bContext *C, ARegion *ar)
void ED_area_exit (bContext *C, ScrArea *sa)
void ED_screen_exit (bContext *C, wmWindow *window, bScreen *screen)
static void screen_cursor_set (wmWindow *win, wmEvent *event)
void ED_screen_set_subwinactive (bContext *C, wmEvent *event)
int ED_screen_area_active (const bContext *C)
void ED_screen_set (bContext *C, bScreen *sc)
static int ed_screen_used (wmWindowManager *wm, bScreen *sc)
void ED_screen_delete (bContext *C, bScreen *sc)
void ED_screen_set_scene (bContext *C, bScreen *screen, Scene *scene)
void ED_screen_delete_scene (bContext *C, Scene *scene)
ScrArea * ED_screen_full_newspace (bContext *C, ScrArea *sa, int type)
void ED_screen_full_prevspace (bContext *C, ScrArea *sa)
void ED_screen_full_restore (bContext *C, ScrArea *sa)
ScrArea * ED_screen_full_toggle (bContext *C, wmWindow *win, ScrArea *sa)
void ED_refresh_viewport_fps (bContext *C)
void ED_screen_animation_timer (bContext *C, int redraws, int refresh, int sync, int enable)
static ARegion * time_top_left_3dwindow (bScreen *screen)
void ED_screen_animation_timer_update (bScreen *screen, int redraws, int refresh)
void ED_update_for_newframe (Main *bmain, Scene *scene, bScreen *screen, int UNUSED(mute))
Detailed Description
Definition in file screen_edit.c.
Define Documentation
#define SCR_BACK 0.55
Definition at line 704 of file screen_edit.c.
#define SCR_ROUND 12
Definition at line 705 of file screen_edit.c.
Function Documentation
int area_getorientation (ScrArea * sa, ScrArea * sb)
Definition at line 494 of file screen_edit.c.
References NULL, ScrArea::v1, ScrArea::v2, ScrArea::v3, and ScrArea::v4.
Referenced by area_join_modal(), ED_screen_draw(), and screen_area_join().
ScrArea* area_split (bScreen * sc, ScrArea * sa, char dir, float fac, int merge)
Definition at line 353 of file screen_edit.c.
References area_copy_data(), ScrArea::headertype, NULL, removedouble_scredges(), removedouble_scrverts(), removenotused_scredges(), screen_addarea(), screen_addedge(), screen_addvert(), ScrArea::spacetype, split(), testsplitpoint(), ScrArea::v1, ScrArea::v2, ScrArea::v3, ScrArea::v4, ScrVert::vec, vec2s::x, and vec2s::y.
Referenced by area_split_apply(), and ED_screen_full_toggle().
static void draw_horizontal_join_shape (ScrArea * sa, char dir) [static]
Definition at line 709 of file screen_edit.c.
References i, ScrArea::v1, ScrArea::v2, ScrArea::v3, ScrArea::v4, ScrVert::vec, vec2s::x, vec2f::x, vec2s::y, and vec2f::y.
Referenced by draw_join_shape().
static void draw_join_shape (ScrArea * sa, char dir) [static]
Definition at line 853 of file screen_edit.c.
References draw_horizontal_join_shape(), and draw_vertical_join_shape().
Referenced by scrarea_draw_shape_dark().
static void draw_vertical_join_shape (ScrArea * sa, char dir) [static]
Definition at line 781 of file screen_edit.c.
References i, ScrArea::v1, ScrArea::v2, ScrArea::v3, ScrArea::v4, ScrVert::vec, vec2s::x, vec2f::x, vec2s::y, and vec2f::y.
Referenced by draw_join_shape().
static void drawscredge_area (ScrArea * sa, int sizex, int sizey, int center) [static]
screen edges drawing
Definition at line 904 of file screen_edit.c.
References cpack, drawscredge_area_draw(), ScrArea::v1, ScrArea::v3, ScrVert::vec, vec2s::x, and vec2s::y.
Referenced by ED_screen_draw().
static void drawscredge_area_draw (int sizex, int sizey, short x1, short y1, short x2, short y2, short a) [static]
Definition at line 883 of file screen_edit.c.
References sdrawline().
Referenced by drawscredge_area().
void ED_area_exit (bContext * C, ScrArea * sa)
Definition at line 1146 of file screen_edit.c.
References CTX_wm_area(), CTX_wm_area_set(), ED_fileselect_exit(), ED_region_exit(), ED_render_engine_area_exit(), ListBase::first, ScrArea::handlers, ARegion::next, ScrArea::regionbase, SPACE_FILE, SPACE_VIEW3D, ScrArea::spacedata, SpaceLink::spacetype, ScrArea::spacetype, and WM_event_remove_handlers().
Referenced by ED_area_newspace(), ED_area_swapspace(), ED_screen_exit(), and screen_delarea().
void ED_refresh_viewport_fps (bContext * C)
Definition at line 1711 of file screen_edit.c.
References bScreen::animtimer, CTX_data_scene(), CTX_wm_screen(), Scene::fps_info, ScreenFrameRateInfo::lredrawtime, wmTimer::ltime, MEM_callocN(), MEM_freeN(), NULL, ScreenFrameRateInfo::redrawtime, and USER_SHOW_FPS.
Referenced by screen_animation_step().
void ED_region_exit (bContext * C, ARegion * ar)
Definition at line 1129 of file screen_edit.c.
References CTX_wm_region(), CTX_wm_region_set(), CTX_wm_window(), ARegion::handlers, ARegion::headerstr, MEM_freeN(), NULL, ARegion::swinid, WM_event_remove_handlers(), and wm_subwindow_close().
Referenced by ED_area_exit(), ED_screen_exit(), region_quadview_exec(), and ui_remove_temporary_region().
bScreen* ED_screen_add (wmWindow * win, Scene * scene, const char * name)
Definition at line 417 of file screen_edit.c.
References alloc_libblock(), bScreen::do_refresh, G, HEADERDOWN, ID_SCR, bScreen::redraws_flag, bScreen::scene, screen_addarea(), screen_addedge(), screen_addvert(), wmWindow::sizex, wmWindow::sizey, SPACE_EMPTY, TIME_ALL_3D_WIN, TIME_ALL_ANIM_WIN, wmWindow::winid, and bScreen::winid.
Referenced by area_dupli_invoke(), ED_screen_duplicate(), ED_screen_full_toggle(), and WM_window_open_temp().
void ED_screen_animation_timer (bContext * C, int redraws, int refresh, int sync, int enable)
Definition at line 1739 of file screen_edit.c.
References ANIMPLAY_FLAG_NO_SYNC, ANIMPLAY_FLAG_REVERSE, ANIMPLAY_FLAG_SYNC, bScreen::animtimer, ScreenAnimData::ar, RenderData::cfra, CTX_data_scene(), CTX_wm_manager(), CTX_wm_region(), CTX_wm_screen(), CTX_wm_window(), wmTimer::customdata, ScreenAnimData::flag, FPS, MEM_callocN(), NC_SCREEN, ND_ANIMPLAY, NULL, Scene::r, ScreenAnimData::redraws, ScreenAnimData::refresh, ScreenAnimData::sfra, RenderData::sfra, TIMER0, WM_event_add_notifier(), WM_event_add_timer(), and WM_event_remove_timer().
Referenced by ED_screen_animation_play().
void ED_screen_animation_timer_update (bScreen * screen, int redraws, int refresh)
Definition at line 1800 of file screen_edit.c.
References bScreen::animtimer, ScreenAnimData::ar, wmTimer::customdata, NULL, ScreenAnimData::redraws, ScreenAnimData::refresh, TIME_REGION, and time_top_left_3dwindow().
int ED_screen_area_active (const bContext * C)
Definition at line 1300 of file screen_edit.c.
References AZONE_REGION, CTX_wm_area(), CTX_wm_screen(), CTX_wm_window(), wmWindow::eventstate, ListBase::first, is_in_area_actionzone(), ARegion::next, ScrArea::regionbase, bScreen::subwinactive, ARegion::swinid, AZone::type, wmEvent::x, and wmEvent::y.
void ED_screen_delete (bContext * C, bScreen * sc)
Definition at line 1395 of file screen_edit.c.
References CTX_data_main(), CTX_wm_manager(), CTX_wm_window(), ED_screen_set(), ed_screen_used(), free_libblock(), bScreen::full, bScreen::id, ID::next, ID::prev, Main::screen, wmWindow::screen, and SCREENFULL.
Referenced by wm_event_do_notifiers().
void ED_screen_delete_scene (bContext * C, Scene * scene)
Definition at line 1509 of file screen_edit.c.
References CTX_data_main(), CTX_wm_screen(), ED_screen_set_scene(), Scene::id, ID::next, ID::prev, and unlink_scene().
Referenced by scene_delete_exec().
void ED_screen_do_listen (bContext * C, wmNotifier * note)
Definition at line 961 of file screen_edit.c.
References wmNotifier::action, wmNotifier::category, CTX_wm_window(), wmNotifier::data, bScreen::do_draw, bScreen::do_refresh, NA_EDITED, NC_SCENE, NC_SCREEN, NC_WINDOW, NC_WM, ND_FILEREAD, ND_MODE, ND_SUBWINACTIVE, region_cursor_set(), wmWindow::screen, wmNotifier::swinid, and uiFreeActiveButtons().
Referenced by wm_event_do_notifiers().
void ED_screen_draw (wmWindow * win)
Definition at line 988 of file screen_edit.c.
References AREA_FLAG_DRAWJOINFROM, AREA_FLAG_DRAWJOINTO, AREA_FLAG_DRAWSPLIT_H, AREA_FLAG_DRAWSPLIT_V, area_getorientation(), bScreen::areabase, bScreen::do_draw, drawscredge_area(), wmWindow::eventstate, ListBase::first, ScrArea::flag, bScreen::mainwin, ScrArea::next, NULL, scrarea_draw_shape_dark(), scrarea_draw_shape_light(), wmWindow::screen, sdrawline(), wmWindow::sizex, wmWindow::sizey, ScrArea::totrct, wmSubWindowSet(), wmEvent::x, rcti::xmax, rcti::xmin, wmEvent::y, rcti::ymax, and rcti::ymin.
Referenced by wm_method_draw_full(), wm_method_draw_overlap_all(), and wm_method_draw_triple().
bScreen* ED_screen_duplicate (wmWindow * win, bScreen * sc)
Definition at line 928 of file screen_edit.c.
References ED_screen_add(), bScreen::full, bScreen::id, ID::name, NULL, bScreen::scene, screen_copy(), and SCREENNORMAL.
Referenced by screen_new_exec(), wm_window_copy(), and wm_window_match_do().
void ED_screen_exit (bContext * C, wmWindow * window, bScreen * screen)
Definition at line 1169 of file screen_edit.c.
References bScreen::animtimer, bScreen::areabase, CTX_wm_manager(), CTX_wm_window(), CTX_wm_window_set(), ED_area_exit(), ED_region_exit(), ListBase::first, bScreen::mainwin, ScrArea::next, ARegion::next, NULL, bScreen::regionbase, wmWindow::screen, bScreen::subwinactive, bScreen::temp, bScreen::winid, WM_event_remove_timer(), and wm_subwindow_close().
Referenced by ED_screen_set(), WM_exit_ext(), wm_window_close(), and wm_window_match_init().
ScrArea* ED_screen_full_newspace (bContext * C, ScrArea * sa, int type)
Definition at line 1526 of file screen_edit.c.
References AREA_TEMP_INFO, bScreen::areabase, CTX_wm_screen(), CTX_wm_window(), ED_area_newspace(), ED_screen_full_toggle(), ListBase::first, ScrArea::flag, ScrArea::full, ScrArea::next, and NULL.
Referenced by render_view_open(), and wm_handler_fileselect_call().
void ED_screen_full_prevspace (bContext * C, ScrArea * sa)
Definition at line 1556 of file screen_edit.c.
References CTX_wm_window(), ED_area_prevspace(), ED_screen_full_toggle(), and ScrArea::full.
Referenced by ED_screen_full_restore(), render_view_cancel_exec(), render_view_show_invoke(), and wm_handler_fileselect_call().
void ED_screen_full_restore (bContext * C, ScrArea * sa)
Definition at line 1567 of file screen_edit.c.
References CTX_wm_window(), ED_screen_full_prevspace(), ED_screen_full_toggle(), ListBase::first, SpaceImage::flag, SpaceLink::next, SI_FULLWINDOW, SI_PREVSPACE, SPACE_FILE, SPACE_IMAGE, ScrArea::spacedata, and SpaceLink::spacetype.
Referenced by fullscreen_back_exec(), and screen_set_exec().
ScrArea* ED_screen_full_toggle (bContext * C, wmWindow * win, ScrArea * sa) [read]
Definition at line 1610 of file screen_edit.c.
References bScreen::animtimer, area_copy_data(), area_split(), AREA_TEMP_INFO, bScreen::areabase, BLI_snprintf(), CTX_data_main(), CTX_wm_area_set(), ED_area_headerprint(), ED_area_newspace(), ED_screen_add(), ED_screen_set(), ListBase::first, ScrArea::flag, free_libblock(), free_screen(), bScreen::full, ScrArea::full, G, G_DEBUG, bScreen::id, ListBase::last, MAX_ID_NAME, ID::name, ScrArea::next, ARegion::next, NULL, ScrArea::prev, ScrArea::regionbase, bScreen::scene, wmWindow::screen, SCREENFULL, SPACE_INFO, ARegion::uiblocks, and uiFreeBlocks().
Referenced by ED_screen_full_newspace(), ED_screen_full_prevspace(), ED_screen_full_restore(), render_view_cancel_exec(), screen_full_area_exec(), and WM_init_game().
void ED_screen_refresh (wmWindowManager * wm, wmWindow * win)
Definition at line 1071 of file screen_edit.c.
References bScreen::animtimer, bScreen::areabase, bScreen::context, bScreen::do_refresh, ED_area_initialize(), ed_screen_context(), ListBase::first, G, G_DEBUG_EVENTS, bScreen::mainwin, ScrArea::next, wmWindow::screen, screen_refresh_headersizes(), screen_test_scale(), wmWindow::sizex, wmWindow::sizey, WM_event_timer_sleep(), wm_subwindow_open(), wm_subwindow_position(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ED_screen_set(), ED_screens_initialize(), wm_debug_menu_exec(), and wm_draw_update().
void ED_screen_set (bContext * C, bScreen * sc)
Definition at line 1322 of file screen_edit.c.
References bScreen::animtimer, bScreen::areabase, CTX_data_main(), CTX_wm_manager(), CTX_wm_screen(), CTX_wm_window(), CTX_wm_window_set(), ED_screen_exit(), ED_screen_refresh(), ListBase::first, ScrArea::full, bScreen::full, bScreen::id, wmWindow::modalhandlers, NC_SCREEN, NC_WINDOW, ND_SCREENSET, ScrArea::next, ID::next, NULL, wmWindow::screen, wmWindow::winid, bScreen::winid, WM_event_add_mousemove(), WM_event_add_notifier(), WM_event_remove_area_handler(), and WM_event_timer_sleep().
Referenced by ED_screen_delete(), ED_screen_full_toggle(), screen_set_exec(), wm_event_do_notifiers(), and WM_window_open_temp().
void ED_screen_set_scene (bContext * C, bScreen * screen, Scene * scene)
Definition at line 1433 of file screen_edit.c.
References bScreen::areabase, BKE_screen_view3d_sync(), View3D::camera, CTX_data_main(), CTX_data_scene_set(), CTX_wm_manager(), ED_object_exit_editmode(), ED_render_engine_changed(), ed_screen_used(), ED_update_for_newframe(), EM_DO_UNDO, EM_FREEDATA, ListBase::first, bScreen::id, NC_WINDOW, ScrArea::next, SpaceLink::next, ARegion::next, ID::next, NULL, object_in_scene(), RegionView3D::persp, View3D::regionbase, ARegion::regiondata, ARegion::regiontype, RGN_TYPE_WINDOW, RV3D_CAMOB, RV3D_PERSP, bScreen::scene, scene_find_camera(), set_scene_bg(), SPACE_VIEW3D, ScrArea::spacedata, SpaceLink::spacetype, USER_SCENEGLOBAL, and WM_event_add_notifier().
Referenced by do_outliner_item_activate(), ED_screen_delete_scene(), outliner_do_object_operation(), outliner_object_operation_exec(), scene_new_exec(), and tree_element_active_world().
void ED_screen_set_subwinactive (bContext * C, wmEvent * event)
Definition at line 1246 of file screen_edit.c.
References bScreen::areabase, BLI_in_rcti(), CTX_wm_window(), ED_region_tag_redraw(), ListBase::first, is_in_area_actionzone(), bScreen::mainwin, NC_SCREEN, ND_SUBWINACTIVE, ARegion::next, ScrArea::next, NULL, region_cursor_set(), ScrArea::regionbase, ARegion::regiontype, RGN_TYPE_HEADER, wmWindow::screen, screen_cursor_set(), bScreen::subwinactive, ARegion::swinid, ScrArea::totrct, ARegion::winrct, WM_event_add_notifier(), wmEvent::x, rcti::xmax, rcti::xmin, wmEvent::y, rcti::ymax, and rcti::ymin.
Referenced by wm_event_do_handlers().
static int ed_screen_used (wmWindowManager * wm, bScreen * sc) [static]
Definition at line 1383 of file screen_edit.c.
References ListBase::first, wmWindow::next, wmWindow::screen, and wmWindowManager::windows.
Referenced by ED_screen_delete(), and ED_screen_set_scene().
void ED_screens_initialize (wmWindowManager * wm)
Definition at line 1113 of file screen_edit.c.
References ED_screen_refresh(), ListBase::first, G, wmWindow::next, NULL, wmWindow::screen, and wmWindowManager::windows.
Referenced by WM_check(), and wm_window_match_do().
void ED_update_for_newframe (Main * bmain, Scene * scene, bScreen * screen, int UNUSEDmute)
Definition at line 1816 of file screen_edit.c.
References BKE_screen_view3d_scene_sync(), BKE_screen_visible_layers(), Scene::camera, RenderData::cfra, ED_clip_update_frame(), ED_image_update_frame(), ListBase::first, Tex::id, bScreen::id, ID::next, Tex::nodetree, Scene::nodetree, ntreeCompositTagAnimated(), ntreeTexTagAnimated(), Scene::r, scene_camera_switch_find(), scene_update_for_newframe(), Main::screen, Main::tex, Tex::use_nodes, and Scene::use_nodes.
static void region_cursor_set (wmWindow * win, int swinid) [static]
Definition at line 943 of file screen_edit.c.
References bScreen::areabase, ARegionType::cursor, CURSOR_STD, ListBase::first, ScrArea::next, ARegion::next, ScrArea::regionbase, wmWindow::screen, ARegion::swinid, ARegion::type, and WM_cursor_set().
Referenced by ED_screen_do_listen(), and ED_screen_set_subwinactive().
void removedouble_scredges (bScreen * sc)
Definition at line 200 of file screen_edit.c.
References BLI_remlink(), bScreen::edgebase, ListBase::first, MEM_freeN(), ScrEdge::next, ScrEdge::v1, and ScrEdge::v2.
Referenced by area_join_exit(), area_move_exit(), area_split(), and area_split_exit().
void removedouble_scrverts (bScreen * sc)
Definition at line 120 of file screen_edit.c.
References bScreen::areabase, BLI_remlink(), bScreen::edgebase, ListBase::first, MEM_freeN(), ScrVert::newv, ScrVert::next, ScrArea::next, ScrEdge::next, NULL, sortscrvert(), ScrArea::v1, ScrEdge::v1, ScrArea::v2, ScrEdge::v2, ScrArea::v3, ScrArea::v4, ScrVert::vec, bScreen::vertbase, vec2s::x, and vec2s::y.
Referenced by area_move_exit(), area_split(), area_split_exit(), and screen_area_join().
void removenotused_scredges (bScreen * sc)
Definition at line 220 of file screen_edit.c.
References bScreen::areabase, BLI_remlink(), bScreen::edgebase, ListBase::first, ScrEdge::flag, MEM_freeN(), ScrArea::next, ScrEdge::next, NULL, screen_findedge(), ScrArea::v1, ScrArea::v2, ScrArea::v3, and ScrArea::v4.
Referenced by area_join_exit(), and area_split().
void removenotused_scrverts (bScreen * sc)
Definition at line 174 of file screen_edit.c.
References BLI_remlink(), bScreen::edgebase, ListBase::first, ScrVert::flag, MEM_freeN(), ScrVert::next, ScrEdge::next, ScrEdge::v1, ScrEdge::v2, and bScreen::vertbase.
Referenced by area_join_exit().
static void scrarea_draw_shape_dark (ScrArea * sa, char dir) [static]
Definition at line 862 of file screen_edit.c.
References draw_join_shape().
Referenced by ED_screen_draw().
static void scrarea_draw_shape_light (ScrArea * sa, char UNUSEDdir) [static]
Definition at line 872 of file screen_edit.c.
References ScrArea::v1, ScrArea::v3, ScrVert::vec, vec2s::x, and vec2s::y.
Referenced by ED_screen_draw().
int scredge_is_horizontal (ScrEdge * se)
Definition at line 256 of file screen_edit.c.
References ScrEdge::v1, ScrEdge::v2, ScrVert::vec, and vec2s::y.
Referenced by area_move_init(), area_split_invoke(), screen_cursor_set(), and screen_find_active_scredge().
static ScrArea* screen_addarea (bScreen * sc, ScrVert * v1, ScrVert * v2, ScrVert * v3, ScrVert * v4, short headertype, short spacetype) [static]
Definition at line 290 of file screen_edit.c.
References bScreen::areabase, BLI_addtail(), ScrArea::butspacetype, ScrArea::headertype, MEM_callocN(), ScrArea::spacetype, ScrArea::v1, ScrArea::v2, ScrArea::v3, and ScrArea::v4.
Referenced by area_split(), and ED_screen_add().
static ScrEdge* screen_addedge (bScreen * sc, ScrVert * v1, ScrVert * v2) [static]
Definition at line 95 of file screen_edit.c.
References BLI_addtail(), bScreen::edgebase, MEM_callocN(), sortscrvert(), ScrArea::v1, ScrEdge::v1, ScrArea::v2, and ScrEdge::v2.
Referenced by area_split(), ED_screen_add(), and screen_area_join().
static ScrVert* screen_addvert (bScreen * sc, short x, short y) [static]
Definition at line 74 of file screen_edit.c.
References BLI_addtail(), MEM_callocN(), ScrVert::vec, bScreen::vertbase, vec2s::x, and vec2s::y.
Referenced by area_split(), and ED_screen_add().
int screen_area_join (bContext * C, bScreen * scr, ScrArea * sa1, ScrArea * sa2)
Definition at line 529 of file screen_edit.c.
References AREA_FLAG_DRAWJOINFROM, AREA_FLAG_DRAWJOINTO, area_getorientation(), ScrArea::flag, removedouble_scrverts(), screen_addedge(), screen_delarea(), ScrArea::v1, ScrArea::v2, ScrArea::v3, and ScrArea::v4.
Referenced by area_join_apply(), and area_split_cancel().
static void screen_copy (bScreen * to, bScreen * from) [static]
Definition at line 444 of file screen_edit.c.
References ScrArea::actionzones, area_copy_data(), bScreen::areabase, BLI_duplicatelist(), bScreen::edgebase, ListBase::first, free_screen(), ScrArea::handlers, ListBase::last, ScrVert::newv, ScrArea::next, ScrEdge::next, ScrVert::next, NULL, ScrArea::regionbase, bScreen::regionbase, sortscrvert(), ScrArea::spacedata, ScrArea::v1, ScrEdge::v1, ScrArea::v2, ScrEdge::v2, ScrArea::v3, ScrArea::v4, and bScreen::vertbase.
Referenced by ED_screen_duplicate().
static void screen_cursor_set (wmWindow * win, wmEvent * event) [static]
Definition at line 1210 of file screen_edit.c.
References AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, bScreen::areabase, AZONE_AREA, AZONE_REGION, CURSOR_EDIT, CURSOR_STD, CURSOR_X_MOVE, CURSOR_Y_MOVE, AZone::edge, ListBase::first, is_in_area_actionzone(), ScrArea::next, NULL, scredge_is_horizontal(), wmWindow::screen, screen_find_active_scredge(), AZone::type, WM_cursor_set(), wmEvent::x, and wmEvent::y.
Referenced by ED_screen_set_subwinactive().
static void screen_delarea (bContext * C, bScreen * sc, ScrArea * sa) [static]
Definition at line 305 of file screen_edit.c.
References bScreen::areabase, BKE_screen_area_free(), BLI_remlink(), ED_area_exit(), and MEM_freeN().
Referenced by screen_area_join().
ScrEdge* screen_find_active_scredge (bScreen * sc, int mx, int my)
Definition at line 261 of file screen_edit.c.
References abs(), bScreen::edgebase, ListBase::first, max, MAX2, min, MIN2, ScrEdge::next, NULL, scredge_is_horizontal(), ScrEdge::v1, ScrEdge::v2, ScrVert::vec, vec2s::x, and vec2s::y.
Referenced by area_move_init(), area_split_invoke(), screen_area_options_invoke(), and screen_cursor_set().
ScrEdge* screen_findedge (bScreen * sc, ScrVert * v1, ScrVert * v2)
Definition at line 108 of file screen_edit.c.
References bScreen::edgebase, ListBase::first, ScrEdge::next, NULL, sortscrvert(), ScrEdge::v1, and ScrEdge::v2.
Referenced by area_findsharededge(), removenotused_scredges(), and screen_test_scale().
static void screen_refresh_headersizes (void) [static]
Definition at line 1058 of file screen_edit.c.
References BKE_regiontype_from_id(), BKE_spacetypes_list(), ED_area_headersize(), ListBase::first, SpaceType::next, ARegionType::prefsizey, and RGN_TYPE_HEADER.
Referenced by ED_screen_refresh().
static void screen_test_scale (bScreen * sc, int winsizex, int winsizey) [static]
Definition at line 617 of file screen_edit.c.
References bScreen::areabase, AREAGRID, CLAMP(), ED_area_headersize(), ListBase::first, ScrVert::flag, max, MAX2, min, MIN2, ScrArea::next, ScrVert::next, NULL, screen_findedge(), select_connected_scredge(), ScrArea::v1, ScrArea::v2, ScrArea::v3, ScrArea::v4, ScrVert::vec, bScreen::vertbase, vec2s::x, and vec2s::y.
Referenced by ED_screen_refresh().
void select_connected_scredge (bScreen * sc, ScrEdge * edge)
Definition at line 574 of file screen_edit.c.
References bScreen::edgebase, ListBase::first, ScrVert::flag, ScrVert::next, ScrEdge::next, ScrEdge::v1, ScrEdge::v2, ScrVert::vec, bScreen::vertbase, vec2s::x, and vec2s::y.
Referenced by area_move_init(), and screen_test_scale().
static void sortscrvert (ScrVert ** v1, ScrVert ** v2) [static]
Definition at line 84 of file screen_edit.c.
References ScrArea::v1, and ScrArea::v2.
Referenced by removedouble_scrverts(), screen_addedge(), screen_copy(), and screen_findedge().
static short testsplitpoint (ScrArea * sa, char dir, float fac) [static]
Definition at line 318 of file screen_edit.c.
References AREAGRID, AREAMINX, AREAMINY, CLAMP(), ScrArea::v1, ScrArea::v2, ScrArea::v4, ScrVert::vec, vec2s::x, and vec2s::y.
Referenced by area_split().
static ARegion* time_top_left_3dwindow (bScreen * screen) [static]
Definition at line 1777 of file screen_edit.c.
References bScreen::areabase, ListBase::first, min, ARegion::next, ScrArea::next, NULL, ScrArea::regionbase, ARegion::regiontype, RGN_TYPE_WINDOW, SPACE_VIEW3D, ScrArea::spacetype, ARegion::winrct, rcti::xmin, and rcti::ymin.
Referenced by ED_screen_animation_timer_update().