Blender: BIF_retarget.h File Reference
BIF_retarget.h File Reference
armature
#include "DNA_listBase.h"
#include "BLI_graph.h"
#include "BLI_ghash.h"
#include "BLI_threads.h"
#include "reeb.h"
Classes
struct RigGraph
struct RigNode
struct RigArc
struct RigEdge
struct RigControl
Defines
#define USE_THREADS
#define RIG_FREE_BONELIST 1
#define RIG_CTRL_HEAD_DONE 1
#define RIG_CTRL_TAIL_DONE 2
#define RIG_CTRL_PARENT_DEFORM 4
#define RIG_CTRL_FIT_ROOT 8
#define RIG_CTRL_FIT_BONE 16
#define RIG_CTRL_DONE (RIG_CTRL_HEAD_DONE|RIG_CTRL_TAIL_DONE)
Typedefs
typedef struct RigGraph RigGraph
typedef struct RigNode RigNode
typedef struct RigArc RigArc
typedef struct RigEdge RigEdge
typedef struct RigControl RigControl
Enumerations
enum LinkTailMode { TL_NONE = 0, TL_TAIL, TL_HEAD }
Functions
void BIF_retargetArc (struct bContext *C, ReebArc *earc, RigGraph *template_rigg)
RigGraph * RIG_graphFromArmature (const struct bContext *C, struct Object *ob, struct bArmature *arm)
int RIG_nbJoints (RigGraph *rg)
const char * RIG_nameBone (RigGraph *rg, int arc_index, int bone_index)
void RIG_freeRigGraph (BGraph *rg)
void BIF_retargetArmature (bContext *C)
void BIF_adjustRetarget (bContext *C)
void RIG_printArc (struct RigGraph *rg, struct RigArc *arc)
void RIG_printGraph (struct RigGraph *rg)
void RIG_printArcBones (struct RigArc *arc)
Detailed Description
Definition in file BIF_retarget.h.
Define Documentation
#define RIG_CTRL_DONE (RIG_CTRL_HEAD_DONE|RIG_CTRL_TAIL_DONE)
Definition at line 135 of file BIF_retarget.h.
Referenced by finalizeControl().
#define RIG_CTRL_FIT_BONE 16
Definition at line 133 of file BIF_retarget.h.
Referenced by RIG_parentControl(), and RIG_reconnectControlBones().
#define RIG_CTRL_FIT_ROOT 8
Definition at line 132 of file BIF_retarget.h.
Referenced by RIG_parentControl().
#define RIG_CTRL_HEAD_DONE 1
Definition at line 129 of file BIF_retarget.h.
Referenced by repositionControl().
#define RIG_CTRL_PARENT_DEFORM 4
Definition at line 131 of file BIF_retarget.h.
#define RIG_CTRL_TAIL_DONE 2
Definition at line 130 of file BIF_retarget.h.
Referenced by repositionControl(), and repositionTailControl().
#define RIG_FREE_BONELIST 1
Definition at line 126 of file BIF_retarget.h.
Referenced by armatureSelectedToGraph(), RIG_freeRigGraph(), and RIG_graphFromArmature().
#define USE_THREADS
Definition at line 49 of file BIF_retarget.h.
Typedef Documentation
typedef struct RigArc RigArc
typedef struct RigControl RigControl
typedef struct RigEdge RigEdge
typedef struct RigGraph RigGraph
typedef struct RigNode RigNode
Enumeration Type Documentation
enum LinkTailMode
Enumerator:
TL_NONE
TL_TAIL
TL_HEAD
Definition at line 138 of file BIF_retarget.h.
Function Documentation
void BIF_adjustRetarget (bContext * C)
Definition at line 2945 of file editarmature_retarget.c.
References adjustGraphs().
void BIF_retargetArc (struct bContext * C, ReebArc * earc, RigGraph * template_rigg)
Definition at line 2892 of file editarmature_retarget.c.
References RigGraph::arcs, armatureSelectedToGraph(), cloneRigGraph(), CTX_data_edit_object(), CTX_data_scene(), Object::data, ED_armature_validate_active(), bArmature::edbo, finishRetarget(), ListBase::first, RigArc::head, ReebArc::head, RigArc::link_mesh, RigNode::link_mesh, NULL, RigGraph::ob, retargetArctoArc(), RIG_freeRigGraph(), ToolSettings::skgen_num_string, ToolSettings::skgen_side_string, RigArc::tail, ReebArc::tail, and Scene::toolsettings.
Referenced by sk_retargetStroke().
void BIF_retargetArmature (bContext * C)
Definition at line 2814 of file editarmature_retarget.c.
References BIF_freeRetarget(), BIF_ReebGraphMultiFromEditMesh(), CTX_DATA_BEGIN, CTX_DATA_END, Object::data, ED_undo_push(), Object::id, RigGraph::link_mesh, ID::name, OB_ARMATURE, PIL_check_seconds_timer(), retargetGraphs(), RIG_graphFromArmature(), and Object::type.
void RIG_freeRigGraph (BGraph * rg)
Definition at line 267 of file editarmature_retarget.c.
References BGraph::arcs, BLI_destroy_worker(), BLI_freelistN(), BLI_freeNode(), BLI_ghash_free(), RigGraph::bones_map, RigGraph::controls, RigGraph::controls_map, RigGraph::editbones, ListBase::first, RigGraph::flag, RigGraph::link_mesh, MEM_freeN(), BArc::next, BNode::next, BGraph::nodes, NULL, REEB_freeGraph(), RIG_FREE_BONELIST, RIG_freeRigArc(), and RigGraph::worker.
Referenced by BIF_freeRetarget(), BIF_freeTemplates(), BIF_retargetArc(), BIF_setTemplate(), and sk_makeTemplateGraph().
RigGraph* RIG_graphFromArmature (const struct bContext * C, struct Object * ob, struct bArmature * arm)
Referenced by BIF_retargetArmature(), and sk_makeTemplateGraph().
const char* RIG_nameBone (RigGraph * rg, int arc_index, int bone_index)
Definition at line 2760 of file editarmature_retarget.c.
References RigGraph::arcs, BLI_countlist(), BLI_findlink(), RigEdge::bone, RigArc::edges, EditBone::name, and NULL.
Referenced by BIF_nameBoneTemplate().
int RIG_nbJoints (RigGraph * rg)
Definition at line 2790 of file editarmature_retarget.c.
References RigGraph::arcs, BLI_countlist(), RigArc::edges, ListBase::first, RigArc::next, and RigGraph::nodes.
Referenced by BIF_nbJointsTemplate().
void RIG_printArc (struct RigGraph * rg, struct RigArc * arc)
Definition at line 1485 of file editarmature_retarget.c.
References RigEdge::angle, RigEdge::bone, RigArc::edges, ListBase::first, RigArc::head, RigEdge::length, M_PI, EditBone::name, RigEdge::next, RIG_printLinkedCtrl(), RIG_printNode(), RigArc::symmetry_flag, RigArc::symmetry_group, RigArc::symmetry_level, RigArc::tail, and RigEdge::tail.
Referenced by RIG_printGraph().
void RIG_printArcBones (struct RigArc * arc)
Definition at line 1434 of file editarmature_retarget.c.
References RigEdge::bone, RigArc::edges, ListBase::first, EditBone::name, and RigEdge::next.
void RIG_printGraph (struct RigGraph * rg)
Definition at line 1507 of file editarmature_retarget.c.
References RigGraph::arcs, ListBase::first, RigGraph::head, RigArc::next, RIG_printArc(), and RIG_printNode().