Blender: InstanceWriter Class Reference
InstanceWriter Class Reference
#include <InstanceWriter.h>
Protected Member Functions
void add_material_bindings (COLLADASW::BindMaterial &bind_material, Object *ob)
Detailed Description
Definition at line 35 of file InstanceWriter.h.
Member Function Documentation
void InstanceWriter::add_material_bindings (COLLADASW::BindMaterial & bind_material, Object * ob) [protected]
Definition at line 44 of file InstanceWriter.cpp.
References bc_CustomData_get_layer_name(), CD_MTFACE, CustomData_number_of_layers(), Object::data, get_material_id(), give_current_material(), id_name(), Object::totcol, and translate_id().
Referenced by ArmatureExporter::add_instance_controller().
The documentation for this class was generated from the following files:
InstanceWriter.h
InstanceWriter.cpp