Blender: KDL::VectorVel Class Reference
KDL::VectorVel Class Reference
#include <framevel.hpp>
Public Member Functions
VectorVel ()
VectorVel (const Vector &_p, const Vector &_v)
VectorVel (const Vector &_p)
Vector value () const
Vector deriv () const
IMETHOD VectorVel & operator= (const VectorVel &arg)
IMETHOD VectorVel & operator= (const Vector &arg)
IMETHOD VectorVel & operator+= (const VectorVel &arg)
IMETHOD VectorVel & operator-= (const VectorVel &arg)
IMETHOD void ReverseSign ()
IMETHOD doubleVel Norm () const
Static Public Member Functions
static IMETHOD VectorVel Zero ()
Public Attributes
Vector p
Vector v
Friends
IMETHOD friend VectorVel operator+ (const VectorVel &r1, const VectorVel &r2)
IMETHOD friend VectorVel operator- (const VectorVel &r1, const VectorVel &r2)
IMETHOD friend VectorVel operator+ (const Vector &r1, const VectorVel &r2)
IMETHOD friend VectorVel operator- (const Vector &r1, const VectorVel &r2)
IMETHOD friend VectorVel operator+ (const VectorVel &r1, const Vector &r2)
IMETHOD friend VectorVel operator- (const VectorVel &r1, const Vector &r2)
IMETHOD friend VectorVel operator* (const VectorVel &r1, const VectorVel &r2)
IMETHOD friend VectorVel operator* (const VectorVel &r1, const Vector &r2)
IMETHOD friend VectorVel operator* (const Vector &r1, const VectorVel &r2)
IMETHOD friend VectorVel operator* (const VectorVel &r1, double r2)
IMETHOD friend VectorVel operator* (double r1, const VectorVel &r2)
IMETHOD friend VectorVel operator* (const doubleVel &r1, const VectorVel &r2)
IMETHOD friend VectorVel operator* (const VectorVel &r2, const doubleVel &r1)
IMETHOD friend VectorVel operator* (const Rotation &R, const VectorVel &x)
IMETHOD friend VectorVel operator/ (const VectorVel &r1, double r2)
IMETHOD friend VectorVel operator/ (const VectorVel &r2, const doubleVel &r1)
IMETHOD friend void SetToZero (VectorVel &v)
IMETHOD friend bool Equal (const VectorVel &r1, const VectorVel &r2, double eps=epsilon)
IMETHOD friend bool Equal (const Vector &r1, const VectorVel &r2, double eps=epsilon)
IMETHOD friend bool Equal (const VectorVel &r1, const Vector &r2, double eps=epsilon)
IMETHOD friend VectorVel operator- (const VectorVel &r)
IMETHOD friend doubleVel dot (const VectorVel &lhs, const VectorVel &rhs)
IMETHOD friend doubleVel dot (const VectorVel &lhs, const Vector &rhs)
IMETHOD friend doubleVel dot (const Vector &lhs, const VectorVel &rhs)
Detailed Description
Definition at line 69 of file framevel.hpp.
Constructor & Destructor Documentation
KDL::VectorVel::VectorVel () [inline]
Definition at line 79 of file framevel.hpp.
KDL::VectorVel::VectorVel (const Vector & _p, const Vector & _v) [inline]
Definition at line 80 of file framevel.hpp.
KDL::VectorVel::VectorVel (const Vector & _p) [inline, explicit]
Definition at line 81 of file framevel.hpp.
Member Function Documentation
Vector KDL::VectorVel::deriv () const [inline]
Definition at line 84 of file framevel.hpp.
References v.
Referenced by KDL::FrameVel::deriv(), and KDL::TwistVel::deriv().
doubleVel VectorVel::Norm () const
Definition at line 128 of file frameacc.inl.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, dot(), p, and KDL::Rall2d< T, V, S >::t.
VectorVel & KDL::VectorVel::operator+= (const VectorVel & arg)
Definition at line 300 of file framevel.hpp.
VectorVel & KDL::VectorVel::operator-= (const VectorVel & arg)
Definition at line 305 of file framevel.hpp.
VectorVel & VectorVel::operator= (const Vector & arg)
Definition at line 295 of file framevel.hpp.
VectorVel & VectorVel::operator= (const VectorVel & arg)
Definition at line 290 of file framevel.hpp.
void KDL::VectorVel::ReverseSign ()
Definition at line 314 of file framevel.hpp.
Vector KDL::VectorVel::value () const [inline]
Definition at line 83 of file framevel.hpp.
References p.
Referenced by KDL::operator*(), and KDL::FrameVel::value().
VectorVel KDL::VectorVel::Zero () [static]
Definition at line 311 of file framevel.hpp.
Friends And Related Function Documentation
IMETHOD friend doubleVel dot (const VectorVel & lhs, const VectorVel & rhs) [friend]
Definition at line 357 of file framevel.hpp.
IMETHOD friend doubleVel dot (const VectorVel & lhs, const Vector & rhs) [friend]
Definition at line 360 of file framevel.hpp.
IMETHOD friend doubleVel dot (const Vector & lhs, const VectorVel & rhs) [friend]
Definition at line 363 of file framevel.hpp.
IMETHOD friend bool Equal (const VectorVel & r1, const VectorVel & r2, double eps = epsilon) [friend]
Definition at line 323 of file framevel.hpp.
IMETHOD friend bool Equal (const Vector & r1, const VectorVel & r2, double eps = epsilon) [friend]
Definition at line 326 of file framevel.hpp.
IMETHOD friend bool Equal (const VectorVel & r1, const Vector & r2, double eps = epsilon) [friend]
Definition at line 329 of file framevel.hpp.
IMETHOD friend VectorVel operator* (const VectorVel & r1, const VectorVel & r2) [friend]
Definition at line 245 of file framevel.hpp.
IMETHOD friend VectorVel operator* (const VectorVel & r1, const Vector & r2) [friend]
Definition at line 249 of file framevel.hpp.
IMETHOD friend VectorVel operator* (const Vector & r1, const VectorVel & r2) [friend]
Definition at line 253 of file framevel.hpp.
IMETHOD friend VectorVel operator* (const VectorVel & r1, double r2) [friend]
Definition at line 264 of file framevel.hpp.
IMETHOD friend VectorVel operator* (double r1, const VectorVel & r2) [friend]
Definition at line 260 of file framevel.hpp.
IMETHOD friend VectorVel operator* (const doubleVel & r1, const VectorVel & r2) [friend]
Definition at line 270 of file framevel.hpp.
IMETHOD friend VectorVel operator* (const VectorVel & r2, const doubleVel & r1) [friend]
Definition at line 274 of file framevel.hpp.
IMETHOD friend VectorVel operator* (const Rotation & R, const VectorVel & x) [friend]
Definition at line 286 of file framevel.hpp.
IMETHOD friend VectorVel operator+ (const VectorVel & r1, const Vector & r2) [friend]
Definition at line 218 of file framevel.hpp.
IMETHOD friend VectorVel operator+ (const Vector & r1, const VectorVel & r2) [friend]
Definition at line 226 of file framevel.hpp.
IMETHOD friend VectorVel operator+ (const VectorVel & r1, const VectorVel & r2) [friend]
Definition at line 210 of file framevel.hpp.
IMETHOD friend VectorVel operator- (const Vector & r1, const VectorVel & r2) [friend]
Definition at line 230 of file framevel.hpp.
IMETHOD friend VectorVel operator- (const VectorVel & r1, const VectorVel & r2) [friend]
Definition at line 214 of file framevel.hpp.
IMETHOD friend VectorVel operator- (const VectorVel & r) [friend]
Definition at line 235 of file framevel.hpp.
IMETHOD friend VectorVel operator- (const VectorVel & r1, const Vector & r2) [friend]
Definition at line 222 of file framevel.hpp.
IMETHOD friend VectorVel operator/ (const VectorVel & r1, double r2) [friend]
Definition at line 278 of file framevel.hpp.
IMETHOD friend VectorVel operator/ (const VectorVel & r2, const doubleVel & r1) [friend]
Definition at line 282 of file framevel.hpp.
IMETHOD friend void SetToZero (VectorVel & v) [friend]
Definition at line 239 of file framevel.hpp.
Member Data Documentation
Vector KDL::VectorVel::p
Definition at line 76 of file framevel.hpp.
Referenced by KDL::addDelta(), KDL::diff(), KDL::posrandom(), KDL::random(), and value().
Vector KDL::VectorVel::v
Definition at line 77 of file framevel.hpp.
Referenced by KDL::addDelta(), deriv(), KDL::diff(), and KDL::posrandom().
The documentation for this class was generated from the following files:
framevel.hpp
frameacc.inl
framevel.inl