Blender: WindowData.c File Reference
WindowData.c File Reference
#include <stdlib.h>
#include "MEM_guardedalloc.h"
#include "GHOST_C-api.h"
#include "WindowData.h"
Classes
struct _WindowData
Functions
WindowData * windowdata_new (void *data, WindowDataHandler handler)
void windowdata_handle (WindowData *wb, GHOST_EventHandle evt)
void windowdata_free (WindowData *wb)
Function Documentation
void windowdata_free (WindowData * wb)
Definition at line 53 of file WindowData.c.
References MEM_freeN().
Referenced by extrawindow_free(), loggerwindow_free(), and mainwindow_free().
void windowdata_handle (WindowData * wb, GHOST_EventHandle evt)
Definition at line 49 of file WindowData.c.
References _WindowData::data, and _WindowData::handler.
Referenced by multitest_event_handler().
WindowData* windowdata_new (void * data, WindowDataHandler handler)
Definition at line 41 of file WindowData.c.
References data, _WindowData::data, _WindowData::handler, and MEM_mallocN().
Referenced by extrawindow_new(), loggerwindow_new(), and mainwindow_new().