Blender: bmesh_interp.c File Reference
bmesh_interp.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "BKE_customdata.h"
#include "BKE_multires.h"
#include "BLI_array.h"
#include "BLI_math.h"
#include "bmesh.h"
#include "intern/bmesh_private.h"
Functions
void BM_data_interp_from_verts (BMesh *bm, BMVert *v1, BMVert *v2, BMVert *v, const float fac)
Data, Interp From Verts.
static void UNUSED_FUNCTION() BM_Data_Vert_Average (BMesh *UNUSED(bm), BMFace *UNUSED(f))
Data Vert Average.
void BM_data_interp_face_vert_edge (BMesh *bm, BMVert *v1, BMVert *UNUSED(v2), BMVert *v, BMEdge *e1, const float fac)
Data Face-Vert Edge Interp.
void BM_face_interp_from_face (BMesh *bm, BMFace *target, BMFace *source)
Data Interp From Face.
static int compute_mdisp_quad (BMLoop *l, float v1[3], float v2[3], float v3[3], float v4[3], float e1[3], float e2[3])
Multires Interpolation.
static float quad_coord (float aa[3], float bb[3], float cc[3], float dd[3], int a1, int a2)
static int quad_co (float *x, float *y, float v1[3], float v2[3], float v3[3], float v4[3], float p[3], float n[3])
static void mdisp_axis_from_quad (float v1[3], float v2[3], float UNUSED(v3[3]), float v4[3], float axis_x[3], float axis_y[3])
static int mdisp_in_mdispquad (BMLoop *l, BMLoop *tl, float p[3], float *x, float *y, int res, float axis_x[3], float axis_y[3])
static float bm_loop_flip_equotion (float mat[2][2], float b[2], float target_axis_x[3], float target_axis_y[3], float coord[3], int i, int j)
static void bm_loop_flip_disp (float source_axis_x[3], float source_axis_y[3], float target_axis_x[3], float target_axis_y[3], float disp[3])
static void bm_loop_interp_mdisps (BMesh *bm, BMLoop *target, BMFace *source)
void BM_face_multires_bounds_smooth (BMesh *bm, BMFace *f)
void BM_loop_interp_multires (BMesh *bm, BMLoop *target, BMFace *source)
void BM_loop_interp_from_face (BMesh *bm, BMLoop *target, BMFace *source, int do_vertex, int do_multires)
void BM_vert_interp_from_face (BMesh *bm, BMVert *v, BMFace *source)
static void update_data_blocks (BMesh *bm, CustomData *olddata, CustomData *data)
void BM_data_layer_add (BMesh *bm, CustomData *data, int type)
void BM_data_layer_add_named (BMesh *bm, CustomData *data, int type, const char *name)
void BM_data_layer_free (BMesh *bm, CustomData *data, int type)
void BM_data_layer_free_n (BMesh *bm, CustomData *data, int type, int n)
float BM_elem_float_data_get (CustomData *cd, void *element, int type)
void BM_elem_float_data_set (CustomData *cd, void *element, int type, const float val)
Detailed Description
Functions for interpolating data across the surface of a mesh.
Definition in file bmesh_interp.c.
Function Documentation
void BM_data_interp_face_vert_edge (BMesh * bm, BMVert * v1, BMVert * UNUSEDv2, BMVert * v, BMEdge * e1, const float fac)
Data Face-Vert Edge Interp.
Walks around the faces of an edge and interpolates the per-face-edge data between two sources to a target.
Definition at line 105 of file bmesh_interp.c.
References CustomData_bmesh_interp(), BMHeader::data, BMLoop::head, BMEdge::l, BMesh::ldata, BMLoop::next, NULL, BMLoop::prev, BMLoop::radial_next, and BMLoop::v.
Referenced by BM_edge_split().
void BM_data_interp_from_verts (BMesh * bm, BMVert * v1, BMVert * v2, BMVert * v, const float fac)
Data, Interp From Verts.
Interpolates per-vertex data from two sources to a target.
Definition at line 53 of file bmesh_interp.c.
References CustomData_bmesh_copy_data(), CustomData_bmesh_free_block(), CustomData_bmesh_interp(), BMHeader::data, BMVert::head, NULL, and BMesh::vdata.
Referenced by BM_edge_split(), BM_vert_collapse_faces(), and bpy_bmvert_copy_from_vert_interp().
void BM_data_layer_add (BMesh * bm, CustomData * data, int type)
Definition at line 792 of file bmesh_interp.c.
References CD_DEFAULT, CustomData_add_layer(), data, CustomData::layers, MEM_dupallocN(), MEM_freeN(), NULL, CustomData::pool, and update_data_blocks().
Referenced by bmo_edgebisect_exec(), bmo_esubd_exec(), BPy_BMEdge_CreatePyObject(), BPy_BMesh_CreatePyObject(), BPy_BMFace_CreatePyObject(), bpy_bmlayercollection_new(), BPy_BMLoop_CreatePyObject(), BPy_BMVert_CreatePyObject(), DM_to_bmesh_ex(), ED_uvedit_assign_image(), ED_uvedit_ensure_uvs(), edbm_bevel_exec(), and vgroup_assign_verts().
void BM_data_layer_add_named (BMesh * bm, CustomData * data, int type, const char * name)
Definition at line 808 of file bmesh_interp.c.
References CD_DEFAULT, CustomData_add_layer_named(), data, CustomData::layers, MEM_dupallocN(), MEM_freeN(), NULL, CustomData::pool, and update_data_blocks().
Referenced by bpy_bmlayercollection_new(), ED_mesh_color_add(), ED_mesh_uv_texture_add(), and EDBM_verts_mirror_cache_begin().
void BM_data_layer_free (BMesh * bm, CustomData * data, int type)
Definition at line 824 of file bmesh_interp.c.
References CustomData_free_layer_active(), data, CustomData::layers, MEM_dupallocN(), MEM_freeN(), NULL, CustomData::pool, and update_data_blocks().
Referenced by bpy_bmesh_dealloc(), delete_customdata_layer(), and multires_customdata_delete().
void BM_data_layer_free_n (BMesh * bm, CustomData * data, int type, int n)
Definition at line 840 of file bmesh_interp.c.
References CustomData_free_layer(), CustomData_get_layer_index_n(), data, CustomData::layers, MEM_dupallocN(), MEM_freeN(), NULL, CustomData::pool, and update_data_blocks().
Referenced by bmo_edgebisect_exec(), bmo_esubd_exec(), bpy_bmlayercollection_remove(), and edbm_bevel_exec().
static void UNUSED_FUNCTION() BM_Data_Vert_Average (BMesh * UNUSEDbm, BMFace * UNUSEDf) [static]
Data Vert Average.
Sets all the customdata (e.g. vert, loop) associated with a vert to the average of the face regions surrounding it.
Definition at line 94 of file bmesh_interp.c.
float BM_elem_float_data_get (CustomData * cd, void * element, int type)
Definition at line 856 of file bmesh_interp.c.
References CustomData_bmesh_get(), and data.
Referenced by bevel_init_edges(), bevel_init_verts(), bmvert_to_mvert(), CDDM_from_BMEditMesh(), edgetag_context_check(), emDM_copyEdgeArray(), emDM_copyVertArray(), and emDM_getEdge().
void BM_elem_float_data_set (CustomData * cd, void * element, int type, const float val)
Definition at line 862 of file bmesh_interp.c.
References CustomData_bmesh_get(), and data.
Referenced by BM_mesh_bm_from_me(), and DM_to_bmesh_ex().
void BM_face_interp_from_face (BMesh * bm, BMFace * target, BMFace * source)
Data Interp From Face.
projects target onto source, and pulls interpolated customdata from source.
Note:
Only handles loop customdata. multires is handled.
Definition at line 150 of file bmesh_interp.c.
References BLI_array_fixedstack_declare, BLI_array_fixedstack_free, BM_elem_attrs_copy(), BM_FACE_FIRST_LOOP, BM_NGON_STACK_SIZE, BMVert::co, copy_v3_v3(), cos(), CustomData_bmesh_interp(), BMHeader::data, BMLoop::head, i, interp_weights_poly_v3(), BMesh::ldata, BMFace::len, BMLoop::next, NULL, and BMLoop::v.
Referenced by bpy_bmface_copy_from_face_interp().
void BM_face_multires_bounds_smooth (BMesh * bm, BMFace * f)
smoothes boundaries between multires grids, including some borders in adjacent faces
Definition at line 484 of file bmesh_interp.c.
References add_v3_v3v3(), BM_ITER_ELEM, BM_LOOPS_OF_FACE, CD_MDISPS, co, copy_v3_v3(), CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, MDisps::disps, BMLoop::head, BMesh::ldata, mul_v3_fl(), BMLoop::next, BMLoop::prev, BMLoop::radial_next, sqrt(), MDisps::totdisp, and BMLoop::v.
Referenced by BM_edge_split(), and BM_face_split().
static void bm_loop_flip_disp (float source_axis_x[3], float source_axis_y[3], float target_axis_x[3], float target_axis_y[3], float disp[3]) [static]
Definition at line 377 of file bmesh_interp.c.
References add_v3_v3v3(), bm_loop_flip_equotion(), cross_v3_v3v3(), fabsf, mul_v3_v3fl(), project_v3_v3v3(), and sub_v3_v3v3().
Referenced by bm_loop_interp_mdisps().
static float bm_loop_flip_equotion (float mat[2][2], float b[2], float target_axis_x[3], float target_axis_y[3], float coord[3], int i, int j) [static]
Definition at line 364 of file bmesh_interp.c.
References i.
Referenced by bm_loop_flip_disp().
void BM_loop_interp_from_face (BMesh * bm, BMLoop * target, BMFace * source, int do_vertex, int do_multires)
projects a single loop, target, onto source for customdata interpolation. multires is handled. if do_vertex is true, target's vert data will also get interpolated.
Definition at line 598 of file bmesh_interp.c.
References add_v3_v3(), axis_dominant_v3(), BLI_array_fixedstack_declare, BLI_array_fixedstack_free, BM_elem_attrs_copy(), BM_FACE_FIRST_LOOP, bm_loop_interp_mdisps(), BM_NGON_STACK_SIZE, CD_MDISPS, co, BMVert::co, copy_v3_v3(), cos(), CustomData_bmesh_interp(), CustomData_has_layer(), BMHeader::data, BMLoop::f, BMVert::head, BMLoop::head, i, interp_weights_poly_v3(), BMesh::ldata, BMFace::len, mul_v3_fl(), BMLoop::next, BMFace::no, NULL, sub_v3_v3v3(), BMLoop::v, and BMesh::vdata.
Referenced by BM_face_split(), BM_face_split_n(), bmo_bevel_exec(), bpy_bmloop_copy_from_face_interp(), and projectSVData().
static void bm_loop_interp_mdisps (BMesh * bm, BMLoop * target, BMFace * source) [static]
Definition at line 405 of file bmesh_interp.c.
References add_v3_v3(), BM_FACE_FIRST_LOOP, bm_loop_flip_disp(), CD_MDISPS, co, compute_mdisp_quad(), copy_v3_v3(), CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, MDisps::disps, BMLoop::f, BMLoop::head, BMesh::ldata, BMFace::len, MDisps::level, mdisp_axis_from_quad(), mdisp_in_mdispquad(), MEM_callocN(), mul_v3_fl(), BMLoop::next, old_mdisps_bilinear(), sqrt(), sub_v3_v3v3(), and MDisps::totdisp.
Referenced by BM_loop_interp_from_face(), and BM_loop_interp_multires().
void BM_loop_interp_multires (BMesh * bm, BMLoop * target, BMFace * source)
project the multires grid in target onto source's set of multires grids
Definition at line 589 of file bmesh_interp.c.
References bm_loop_interp_mdisps().
Referenced by BM_edge_split(), BM_faces_join(), bmo_bevel_exec(), and projectSVData().
void BM_vert_interp_from_face (BMesh * bm, BMVert * v, BMFace * source)
Definition at line 676 of file bmesh_interp.c.
References add_v3_v3(), BLI_array_fixedstack_declare, BLI_array_fixedstack_free, BM_FACE_FIRST_LOOP, BM_NGON_STACK_SIZE, BMVert::co, copy_v3_v3(), cos(), CustomData_bmesh_interp(), BMHeader::data, BMVert::head, i, interp_weights_poly_v3(), BMFace::len, mul_v3_fl(), BMLoop::next, NULL, sub_v3_v3v3(), BMLoop::v, and BMesh::vdata.
Referenced by bpy_bmvert_copy_from_face_interp().
static int compute_mdisp_quad (BMLoop * l, float v1[3], float v2[3], float v3[3], float v4[3], float e1[3], float e2[3]) [static]
Multires Interpolation.
mdisps is a grid of displacements, ordered thus:
v1/center----v4/next -> x | | | | v2/prev------v3/cur | V y
Definition at line 198 of file bmesh_interp.c.
References add_v3_v3v3(), BM_FACE_FIRST_LOOP, BMVert::co, copy_v3_v3(), BMLoop::f, BMFace::len, mul_v3_fl(), BMLoop::next, p, BMLoop::prev, sub_v3_v3v3(), and BMLoop::v.
Referenced by bm_loop_interp_mdisps(), and mdisp_in_mdispquad().
static void mdisp_axis_from_quad (float v1[3], float v2[3], float UNUSEDv3[3], float v4[3], float axis_x[3], float axis_y[3]) [static]
Definition at line 318 of file bmesh_interp.c.
References normalize_v3(), and sub_v3_v3v3().
Referenced by bm_loop_interp_mdisps(), and mdisp_in_mdispquad().
static int mdisp_in_mdispquad (BMLoop * l, BMLoop * tl, float p[3], float * x, float * y, int res, float axis_x[3], float axis_y[3]) [static]
Definition at line 330 of file bmesh_interp.c.
References add_v3_v3(), BM_vert_normal_update_all(), cent_quad_v3(), compute_mdisp_quad(), len_v3(), mdisp_axis_from_quad(), mul_v3_fl(), BMVert::no, quad_co(), sub_v3_v3(), and BMLoop::v.
Referenced by bm_loop_interp_mdisps().
static int quad_co (float * x, float * y, float v1[3], float v2[3], float v3[3], float v4[3], float p[3], float n[3]) [static]
Definition at line 270 of file bmesh_interp.c.
References copy_v3_v3(), dot_v3v3(), i, isect_point_quad_v2(), normal_quad_v3(), poly_rotate_plane(), quad_coord(), and sub_v3_v3().
Referenced by mdisp_in_mdispquad().
static float quad_coord (float aa[3], float bb[3], float cc[3], float dd[3], int a1, int a2) [static]
Definition at line 232 of file bmesh_interp.c.
References CLAMP(), fabsf, i, isnan(), MIN2, and sqrt().
Referenced by quad_co().
static void update_data_blocks (BMesh * bm, CustomData * olddata, CustomData * data) [static]
Definition at line 718 of file bmesh_interp.c.
References BLI_assert, BLI_mempool_destroy(), BM_EDGE, BM_EDGES_OF_MESH, BM_FACE, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOP, BM_LOOPS_OF_FACE, BM_VERT, BM_VERTS_OF_MESH, CustomData_bmesh_copy_data(), CustomData_bmesh_free_block(), CustomData_bmesh_init_pool(), CustomData_bmesh_set_default(), BMHeader::data, BMesh::edata, BMEdge::head, BMVert::head, BMFace::head, BMLoop::head, BMesh::ldata, NULL, BMesh::pdata, CustomData::pool, BMesh::totedge, BMesh::totface, BMesh::totloop, BMesh::totvert, and BMesh::vdata.
Referenced by BM_data_layer_add(), BM_data_layer_add_named(), BM_data_layer_free(), and BM_data_layer_free_n().