Blender: BlockDXT.h File Reference
BlockDXT.h File Reference
DDS
#include <Common.h>
#include <Color.h>
#include <ColorBlock.h>
#include <Stream.h>
Classes
struct BlockDXT1
DXT1 block.
struct AlphaBlockDXT3
DXT3 alpha block with explicit alpha.
struct BlockDXT3
DXT3 block.
struct AlphaBlockDXT5
DXT5 alpha block.
struct BlockDXT5
DXT5 block.
struct BlockATI1
ATI1 block.
struct BlockATI2
ATI2 block.
struct BlockCTX1
CTX1 block.
Functions
void mem_read (Stream &mem, BlockDXT1 &block)
void mem_read (Stream &mem, AlphaBlockDXT3 &block)
void mem_read (Stream &mem, BlockDXT3 &block)
void mem_read (Stream &mem, AlphaBlockDXT5 &block)
void mem_read (Stream &mem, BlockDXT5 &block)
void mem_read (Stream &mem, BlockATI1 &block)
void mem_read (Stream &mem, BlockATI2 &block)
void mem_read (Stream &mem, BlockCTX1 &block)
Detailed Description
Definition in file BlockDXT.h.
Function Documentation
void mem_read (Stream & mem, BlockDXT1 & block)
Definition at line 620 of file BlockDXT.cpp.
References BlockDXT1::col0, BlockDXT1::col1, BlockDXT1::indices, mem_read(), and Color16::u.
Referenced by DirectDrawSurface::DirectDrawSurface(), and mem_read().
void mem_read (Stream & mem, BlockCTX1 & block)
Definition at line 660 of file BlockDXT.cpp.
References BlockCTX1::col0, BlockCTX1::col1, BlockCTX1::indices, and mem_read().
void mem_read (Stream & mem, BlockATI2 & block)
Definition at line 654 of file BlockDXT.cpp.
References mem_read(), BlockATI2::x, and BlockATI2::y.
void mem_read (Stream & mem, BlockATI1 & block)
Definition at line 649 of file BlockDXT.cpp.
References BlockATI1::alpha, and mem_read().
void mem_read (Stream & mem, BlockDXT5 & block)
Definition at line 643 of file BlockDXT.cpp.
References BlockDXT5::alpha, BlockDXT5::color, and mem_read().
void mem_read (Stream & mem, AlphaBlockDXT5 & block)
Definition at line 638 of file BlockDXT.cpp.
References mem_read(), and AlphaBlockDXT5::u.
void mem_read (Stream & mem, BlockDXT3 & block)
Definition at line 632 of file BlockDXT.cpp.
References BlockDXT3::alpha, BlockDXT3::color, and mem_read().
void mem_read (Stream & mem, AlphaBlockDXT3 & block)
Definition at line 627 of file BlockDXT.cpp.
References i, mem_read(), and AlphaBlockDXT3::row.