Blender: node_composite_mapValue.c File Reference
node_composite_mapValue.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_map_value (bNode *node, float *out, float *src)
static void node_composit_exec_map_value (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_map_value (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_map_value (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_map_value_in []
static bNodeSocketTemplate cmp_node_map_value_out []
Detailed Description
Definition in file node_composite_mapValue.c.
Function Documentation
static void do_map_value (bNode * node, float * out, float * src) [static]
Definition at line 45 of file node_composite_mapValue.c.
References TexMapping::flag, if(), TexMapping::loc, TexMapping::max, TexMapping::min, TexMapping::size, bNode::storage, TEXMAP_CLIP_MAX, and TEXMAP_CLIP_MIN.
Referenced by node_composit_exec_map_value().
static void node_composit_exec_map_value (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 58 of file node_composite_mapValue.c.
References alloc_compbuf(), CB_VAL, composit1_pixel_processor(), bNodeStack::data, data, do_map_value(), NULL, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_map_value().
static void node_composit_init_map_value (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 80 of file node_composite_mapValue.c.
References add_tex_mapping(), and bNode::storage.
Referenced by register_node_type_cmp_map_value().
void register_node_type_cmp_map_value (bNodeTreeType * ttype)
Definition at line 85 of file node_composite_mapValue.c.
References CMP_NODE_MAP_VALUE, NODE_CLASS_OP_VECTOR, node_composit_exec_map_value(), node_composit_init_map_value(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_map_value_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Value",         1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_composite_mapValue.c.
bNodeSocketTemplate cmp_node_map_value_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "Value"},
    {   -1, 0, ""   }
}
Definition at line 40 of file node_composite_mapValue.c.