Blender: rna_sequencer.c File Reference
rna_sequencer.c File Reference
RNA
#include <stdlib.h>
#include <limits.h>
#include "RNA_access.h"
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_anim_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_sequence_types.h"
#include "DNA_movieclip_types.h"
#include "BKE_animsys.h"
#include "BKE_global.h"
#include "BKE_sequencer.h"
#include "BKE_sound.h"
#include "MEM_guardedalloc.h"
#include "WM_types.h"
#include "BLI_math.h"
Functions
static void rna_def_strip_element (BlenderRNA *brna)
static void rna_def_strip_crop (BlenderRNA *brna)
static void rna_def_strip_transform (BlenderRNA *brna)
static void rna_def_strip_proxy (BlenderRNA *brna)
static void rna_def_strip_color_balance (BlenderRNA *brna)
static void rna_def_sequence (BlenderRNA *brna)
static void rna_def_editor (BlenderRNA *brna)
static void rna_def_filter_video (StructRNA *srna)
static void rna_def_proxy (StructRNA *srna)
static void rna_def_input (StructRNA *srna)
static void rna_def_image (BlenderRNA *brna)
static void rna_def_meta (BlenderRNA *brna)
static void rna_def_scene (BlenderRNA *brna)
static void rna_def_movie (BlenderRNA *brna)
static void rna_def_movieclip (BlenderRNA *brna)
static void rna_def_sound (BlenderRNA *brna)
static void rna_def_effect (BlenderRNA *brna)
static void rna_def_multicam (BlenderRNA *brna)
static void rna_def_adjustment (BlenderRNA *brna)
static void rna_def_plugin (BlenderRNA *brna)
static void rna_def_wipe (BlenderRNA *brna)
static void rna_def_glow (BlenderRNA *brna)
static void rna_def_transform (BlenderRNA *brna)
static void rna_def_solid_color (BlenderRNA *brna)
static void rna_def_speed_control (BlenderRNA *brna)
void RNA_def_sequencer (BlenderRNA *brna)
Detailed Description
Definition in file rna_sequencer.c.
Function Documentation
static void rna_def_adjustment (BlenderRNA * brna) [static]
Definition at line 1576 of file rna_sequencer.c.
References rna_def_filter_video(), rna_def_input(), rna_def_proxy(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_editor (BlenderRNA * brna) [static]
Definition at line 1181 of file rna_sequencer.c.
References NC_SPACE, ND_SPACE_SEQUENCER, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), SEQ_EDIT_OVERLAY_ABS, and SEQ_EDIT_OVERLAY_SHOW.
Referenced by RNA_def_sequencer().
static void rna_def_effect (BlenderRNA * brna) [static]
Definition at line 1542 of file rna_sequencer.c.
References rna_def_filter_video(), rna_def_proxy(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_filter_video (StructRNA * srna) [static]
Definition at line 1234 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), SEQ_FILTERY, SEQ_FLIPX, SEQ_FLIPY, SEQ_MAKE_FLOAT, SEQ_MAKE_PREMUL, SEQ_REVERSE_FRAMES, SEQ_USE_COLOR_BALANCE, SEQ_USE_CROP, and SEQ_USE_TRANSFORM.
Referenced by rna_def_adjustment(), rna_def_effect(), rna_def_image(), rna_def_meta(), rna_def_movie(), rna_def_movieclip(), rna_def_multicam(), and rna_def_scene().
static void rna_def_glow (BlenderRNA * brna) [static]
Definition at line 1667 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_image (BlenderRNA * brna) [static]
Definition at line 1361 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_COLLECTION, PROP_DIRPATH, PROP_NONE, PROP_STRING, rna_def_filter_video(), rna_def_input(), RNA_def_property(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), rna_def_proxy(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_input (StructRNA * srna) [static]
Definition at line 1341 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_ANIMATABLE, PROP_INT, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_adjustment(), rna_def_image(), rna_def_meta(), rna_def_movie(), rna_def_movieclip(), rna_def_multicam(), rna_def_scene(), and rna_def_sound().
static void rna_def_meta (BlenderRNA * brna) [static]
Definition at line 1388 of file rna_sequencer.c.
References NULL, PROP_COLLECTION, PROP_NONE, rna_def_filter_video(), rna_def_input(), RNA_def_property(), RNA_def_property_collection_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), rna_def_proxy(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_movie (BlenderRNA * brna) [static]
Definition at line 1432 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_COLLECTION, PROP_FILEPATH, PROP_INT, PROP_NONE, PROP_STRING, rna_def_filter_video(), rna_def_input(), RNA_def_property(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), rna_def_proxy(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_movieclip (BlenderRNA * brna) [static]
Definition at line 1473 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_BOOLEAN, PROP_NONE, rna_def_filter_video(), rna_def_input(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SEQ_MOVIECLIP_RENDER_STABILIZED, and SEQ_MOVIECLIP_RENDER_UNDISTORTED.
Referenced by RNA_def_sequencer().
static void rna_def_multicam (BlenderRNA * brna) [static]
Definition at line 1555 of file rna_sequencer.c.
References MAXSEQ, NC_SCENE, ND_SEQUENCER, NULL, PROP_INT, PROP_UNSIGNED, rna_def_filter_video(), rna_def_input(), RNA_def_property(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), rna_def_proxy(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_plugin (BlenderRNA * brna) [static]
Definition at line 1591 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_EDITABLE, PROP_FILENAME, PROP_STRING, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_proxy (StructRNA * srna) [static]
Definition at line 1317 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_BOOLEAN, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), SEQ_USE_PROXY, SEQ_USE_PROXY_CUSTOM_DIR, and SEQ_USE_PROXY_CUSTOM_FILE.
Referenced by rna_def_adjustment(), rna_def_effect(), rna_def_image(), rna_def_meta(), rna_def_movie(), rna_def_multicam(), and rna_def_scene().
static void rna_def_scene (BlenderRNA * brna) [static]
Definition at line 1407 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_EDITABLE, PROP_NONE, PROP_POINTER, rna_def_filter_video(), rna_def_input(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_ui_text(), RNA_def_property_update(), rna_def_proxy(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_sequence (BlenderRNA * brna) [static]
Definition at line 950 of file rna_sequencer.c.
References MAXFRAME, MAXSEQ, NA_SELECTED, NC_SCENE, ND_SEQUENCER, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_TIME, PROP_UNSIGNED, RNA_api_sequence_strip(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_editable_func(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_refine_func(), RNA_def_struct_ui_text(), SELECT, SEQ_ADD, SEQ_ADJUSTMENT, SEQ_ALPHAOVER, SEQ_ALPHAUNDER, SEQ_AUDIO_DRAW_WAVEFORM, SEQ_BLEND_REPLACE, SEQ_COLOR, SEQ_CROSS, SEQ_GAMCROSS, SEQ_GLOW, SEQ_IMAGE, SEQ_LEFTSEL, SEQ_LOCK, SEQ_META, SEQ_MOVIE, SEQ_MOVIECLIP, SEQ_MUL, SEQ_MULTICAM, SEQ_MUTE, SEQ_OVERDROP, SEQ_PLUGIN, SEQ_RIGHTSEL, SEQ_SCENE, SEQ_SOUND, SEQ_SPEED, SEQ_SUB, SEQ_TRANSFORM, SEQ_USE_EFFECT_DEFAULT_FADE, and SEQ_WIPE.
Referenced by RNA_def_sequencer().
void RNA_def_sequencer (BlenderRNA * brna)
Definition at line 1831 of file rna_sequencer.c.
References rna_def_adjustment(), rna_def_editor(), rna_def_effect(), rna_def_glow(), rna_def_image(), rna_def_meta(), rna_def_movie(), rna_def_movieclip(), rna_def_multicam(), rna_def_plugin(), rna_def_scene(), rna_def_sequence(), rna_def_solid_color(), rna_def_sound(), rna_def_speed_control(), rna_def_strip_color_balance(), rna_def_strip_crop(), rna_def_strip_element(), rna_def_strip_proxy(), rna_def_strip_transform(), rna_def_transform(), and rna_def_wipe().
static void rna_def_solid_color (BlenderRNA * brna) [static]
Definition at line 1784 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_COLOR, PROP_FLOAT, RNA_def_property(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_sound (BlenderRNA * brna) [static]
Definition at line 1497 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_FILEPATH, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, rna_def_input(), RNA_def_property(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_speed_control (BlenderRNA * brna) [static]
Definition at line 1799 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_float_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), SEQ_SPEED_BLEND, SEQ_SPEED_COMPRESS_IPO_Y, and SEQ_SPEED_INTEGRATE.
Referenced by RNA_def_sequencer().
static void rna_def_strip_color_balance (BlenderRNA * brna) [static]
Definition at line 897 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_BOOLEAN, PROP_COLOR, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SEQ_COLOR_BALANCE_INVERSE_GAIN, SEQ_COLOR_BALANCE_INVERSE_GAMMA, and SEQ_COLOR_BALANCE_INVERSE_LIFT.
Referenced by RNA_def_sequencer().
static void rna_def_strip_crop (BlenderRNA * brna) [static]
Definition at line 760 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_INT, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_int_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_strip_element (BlenderRNA * brna) [static]
Definition at line 735 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_EDITABLE, PROP_FILENAME, PROP_INT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_int_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_strip_proxy (BlenderRNA * brna) [static]
Definition at line 821 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_BOOLEAN, PROP_DIRPATH, PROP_ENUM, PROP_FILEPATH, PROP_INT, PROP_NONE, PROP_STRING, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_sdna(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SEQ_PROXY_IMAGE_SIZE_100, SEQ_PROXY_IMAGE_SIZE_25, SEQ_PROXY_IMAGE_SIZE_50, SEQ_PROXY_IMAGE_SIZE_75, SEQ_PROXY_TC_FREE_RUN, SEQ_PROXY_TC_INTERP_REC_DATE_FREE_RUN, SEQ_PROXY_TC_NONE, SEQ_PROXY_TC_RECORD_RUN, and SEQ_PROXY_TC_RECORD_RUN_NO_GAPS.
Referenced by RNA_def_sequencer().
static void rna_def_strip_transform (BlenderRNA * brna) [static]
Definition at line 796 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_int_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_transform (BlenderRNA * brna) [static]
Definition at line 1712 of file rna_sequencer.c.
References NC_SCENE, ND_SEQUENCER, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().
static void rna_def_wipe (BlenderRNA * brna) [static]
Definition at line 1610 of file rna_sequencer.c.
References DEG2RAD, NC_SCENE, ND_SEQUENCER, NULL, PROP_ANGLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sequencer().