Blender: NOD_composite.h File Reference
NOD_composite.h File Reference
nodes
#include "BKE_node.h"
Functions
void register_node_type_cmp_group (struct bNodeTreeType *ttype)
void register_node_type_cmp_forloop (struct bNodeTreeType *ttype)
void register_node_type_cmp_whileloop (struct bNodeTreeType *ttype)
void register_node_type_cmp_rlayers (struct bNodeTreeType *ttype)
void register_node_type_cmp_image (struct bNodeTreeType *ttype)
void register_node_type_cmp_texture (struct bNodeTreeType *ttype)
void register_node_type_cmp_value (struct bNodeTreeType *ttype)
void register_node_type_cmp_rgb (struct bNodeTreeType *ttype)
void register_node_type_cmp_curve_time (struct bNodeTreeType *ttype)
void register_node_type_cmp_movieclip (struct bNodeTreeType *ttype)
void register_node_type_cmp_composite (struct bNodeTreeType *ttype)
void register_node_type_cmp_viewer (struct bNodeTreeType *ttype)
void register_node_type_cmp_splitviewer (struct bNodeTreeType *ttype)
void register_node_type_cmp_output_file (struct bNodeTreeType *ttype)
void register_node_type_cmp_view_levels (struct bNodeTreeType *ttype)
void register_node_type_cmp_curve_rgb (struct bNodeTreeType *ttype)
void register_node_type_cmp_mix_rgb (struct bNodeTreeType *ttype)
void register_node_type_cmp_hue_sat (struct bNodeTreeType *ttype)
void register_node_type_cmp_brightcontrast (struct bNodeTreeType *ttype)
void register_node_type_cmp_gamma (struct bNodeTreeType *ttype)
void register_node_type_cmp_invert (struct bNodeTreeType *ttype)
void register_node_type_cmp_alphaover (struct bNodeTreeType *ttype)
void register_node_type_cmp_zcombine (struct bNodeTreeType *ttype)
void register_node_type_cmp_colorbalance (struct bNodeTreeType *ttype)
void register_node_type_cmp_huecorrect (struct bNodeTreeType *ttype)
void register_node_type_cmp_normal (struct bNodeTreeType *ttype)
void register_node_type_cmp_curve_vec (struct bNodeTreeType *ttype)
void register_node_type_cmp_map_value (struct bNodeTreeType *ttype)
void register_node_type_cmp_normalize (struct bNodeTreeType *ttype)
void register_node_type_cmp_filter (struct bNodeTreeType *ttype)
void register_node_type_cmp_blur (struct bNodeTreeType *ttype)
void register_node_type_cmp_dblur (struct bNodeTreeType *ttype)
void register_node_type_cmp_bilateralblur (struct bNodeTreeType *ttype)
void register_node_type_cmp_vecblur (struct bNodeTreeType *ttype)
void register_node_type_cmp_dilateerode (struct bNodeTreeType *ttype)
void register_node_type_cmp_defocus (struct bNodeTreeType *ttype)
void register_node_type_cmp_valtorgb (struct bNodeTreeType *ttype)
void register_node_type_cmp_rgbtobw (struct bNodeTreeType *ttype)
void register_node_type_cmp_setalpha (struct bNodeTreeType *ttype)
void register_node_type_cmp_idmask (struct bNodeTreeType *ttype)
void register_node_type_cmp_math (struct bNodeTreeType *ttype)
void register_node_type_cmp_seprgba (struct bNodeTreeType *ttype)
void register_node_type_cmp_combrgba (struct bNodeTreeType *ttype)
void register_node_type_cmp_sephsva (struct bNodeTreeType *ttype)
void register_node_type_cmp_combhsva (struct bNodeTreeType *ttype)
void register_node_type_cmp_sepyuva (struct bNodeTreeType *ttype)
void register_node_type_cmp_combyuva (struct bNodeTreeType *ttype)
void register_node_type_cmp_sepycca (struct bNodeTreeType *ttype)
void register_node_type_cmp_combycca (struct bNodeTreeType *ttype)
void register_node_type_cmp_premulkey (struct bNodeTreeType *ttype)
void register_node_type_cmp_diff_matte (struct bNodeTreeType *ttype)
void register_node_type_cmp_distance_matte (struct bNodeTreeType *ttype)
void register_node_type_cmp_chroma_matte (struct bNodeTreeType *ttype)
void register_node_type_cmp_color_matte (struct bNodeTreeType *ttype)
void register_node_type_cmp_channel_matte (struct bNodeTreeType *ttype)
void register_node_type_cmp_color_spill (struct bNodeTreeType *ttype)
void register_node_type_cmp_luma_matte (struct bNodeTreeType *ttype)
void register_node_type_cmp_doubleedgemask (struct bNodeTreeType *ttype)
void register_node_type_cmp_translate (struct bNodeTreeType *ttype)
void register_node_type_cmp_rotate (struct bNodeTreeType *ttype)
void register_node_type_cmp_scale (struct bNodeTreeType *ttype)
void register_node_type_cmp_flip (struct bNodeTreeType *ttype)
void register_node_type_cmp_crop (struct bNodeTreeType *ttype)
void register_node_type_cmp_displace (struct bNodeTreeType *ttype)
void register_node_type_cmp_mapuv (struct bNodeTreeType *ttype)
void register_node_type_cmp_transform (struct bNodeTreeType *ttype)
void register_node_type_cmp_stabilize2d (struct bNodeTreeType *ttype)
void register_node_type_cmp_moviedistortion (struct bNodeTreeType *ttype)
void register_node_type_cmp_glare (struct bNodeTreeType *ttype)
void register_node_type_cmp_tonemap (struct bNodeTreeType *ttype)
void register_node_type_cmp_lensdist (struct bNodeTreeType *ttype)
Variables
bNodeTreeType ntreeType_Composite
Detailed Description
Definition in file NOD_composite.h.
Function Documentation
void register_node_type_cmp_alphaover (struct bNodeTreeType * ttype)
Definition at line 147 of file node_composite_alphaOver.c.
References CMP_NODE_ALPHAOVER, node_alphaover_init(), NODE_CLASS_OP_COLOR, node_composit_exec_alphaover(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_bilateralblur (struct bNodeTreeType * ttype)
Definition at line 265 of file node_composite_bilateralblur.c.
References CMP_NODE_BILATERALBLUR, NODE_CLASS_OP_FILTER, node_composit_exec_bilateralblur(), node_composit_init_bilateralblur(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_blur (struct bNodeTreeType * ttype)
Definition at line 725 of file node_composite_blur.c.
References CMP_NODE_BLUR, NODE_CLASS_OP_FILTER, node_composit_exec_blur(), node_composit_init_blur(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_brightcontrast (struct bNodeTreeType * ttype)
Definition at line 95 of file node_composite_brightness.c.
References CMP_NODE_BRIGHTCONTRAST, NODE_CLASS_OP_COLOR, node_composit_exec_brightcontrast(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_channel_matte (struct bNodeTreeType * ttype)
Definition at line 203 of file node_composite_channelMatte.c.
References CMP_NODE_CHANNEL_MATTE, NODE_CLASS_MATTE, node_composit_exec_channel_matte(), node_composit_init_channel_matte(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_chroma_matte (struct bNodeTreeType * ttype)
Definition at line 190 of file node_composite_chromaMatte.c.
References CMP_NODE_CHROMA_MATTE, NODE_CLASS_MATTE, node_composit_exec_chroma_matte(), node_composit_init_chroma_matte(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_color_matte (struct bNodeTreeType * ttype)
Definition at line 126 of file node_composite_colorMatte.c.
References CMP_NODE_COLOR_MATTE, NODE_CLASS_MATTE, node_composit_exec_color_matte(), node_composit_init_color_matte(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_color_spill (struct bNodeTreeType * ttype)
Definition at line 333 of file node_composite_colorSpill.c.
References CMP_NODE_COLOR_SPILL, NODE_CLASS_MATTE, node_composit_exec_color_spill(), node_composit_init_color_spill(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_colorbalance (struct bNodeTreeType * ttype)
Definition at line 186 of file node_composite_colorbalance.c.
References CMP_NODE_COLORBALANCE, NODE_CLASS_OP_COLOR, node_composit_exec_colorbalance(), node_composit_init_colorbalance(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_combhsva (struct bNodeTreeType * ttype)
Definition at line 171 of file node_composite_sepcombHSVA.c.
References CMP_NODE_COMBHSVA, NODE_CLASS_CONVERTOR, node_composit_exec_combhsva(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_combrgba (struct bNodeTreeType * ttype)
Definition at line 148 of file node_composite_sepcombRGBA.c.
References CMP_NODE_COMBRGBA, NODE_CLASS_CONVERTOR, node_composit_exec_combrgba(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_combycca (struct bNodeTreeType * ttype)
Definition at line 298 of file node_composite_sepcombYCCA.c.
References CMP_NODE_COMBYCCA, NODE_CLASS_CONVERTOR, node_composit_exec_combycca(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_combyuva (struct bNodeTreeType * ttype)
Definition at line 173 of file node_composite_sepcombYUVA.c.
References CMP_NODE_COMBYUVA, NODE_CLASS_CONVERTOR, node_composit_exec_combyuva(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_composite (struct bNodeTreeType * ttype)
Definition at line 100 of file node_composite_composite.c.
References CMP_NODE_COMPOSITE, NODE_CLASS_OUTPUT, node_composit_exec_composite(), NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
void register_node_type_cmp_crop (struct bNodeTreeType * ttype)
Definition at line 114 of file node_composite_crop.c.
References CMP_NODE_CROP, NODE_CLASS_DISTORT, node_composit_exec_crop(), node_composit_init_crop(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_curve_rgb (struct bNodeTreeType * ttype)
Definition at line 192 of file node_composite_curves.c.
References CMP_NODE_CURVE_RGB, NODE_CLASS_OP_COLOR, node_composit_exec_curve_rgb(), node_composit_init_curve_rgb(), node_copy_curves(), node_free_curves(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_curve_time (struct bNodeTreeType * ttype)
Definition at line 65 of file node_composite_curves.c.
References CMP_NODE_TIME, NODE_CLASS_INPUT, node_composit_exec_curves_time(), node_composit_init_curves_time(), node_copy_curves(), node_free_curves(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
void register_node_type_cmp_curve_vec (struct bNodeTreeType * ttype)
Definition at line 105 of file node_composite_curves.c.
References CMP_NODE_CURVE_VEC, NODE_CLASS_OP_VECTOR, node_composit_exec_curve_vec(), node_composit_init_curve_vec(), node_copy_curves(), node_free_curves(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_dblur (struct bNodeTreeType * ttype)
Definition at line 133 of file node_composite_directionalblur.c.
References CMP_NODE_DBLUR, NODE_CLASS_OP_FILTER, node_composit_exec_dblur(), node_composit_init_dblur(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_defocus (struct bNodeTreeType * ttype)
Definition at line 878 of file node_composite_defocus.c.
References CMP_NODE_DEFOCUS, NODE_CLASS_OP_FILTER, node_composit_exec_defocus(), node_composit_init_defocus(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_diff_matte (struct bNodeTreeType * ttype)
Definition at line 134 of file node_composite_diffMatte.c.
References CMP_NODE_DIFF_MATTE, NODE_CLASS_MATTE, node_composit_exec_diff_matte(), node_composit_init_diff_matte(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_dilateerode (struct bNodeTreeType * ttype)
Definition at line 150 of file node_composite_dilate.c.
References CMP_NODE_DILATEERODE, NODE_CLASS_OP_FILTER, node_composit_exec_dilateerode(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_displace (struct bNodeTreeType * ttype)
Definition at line 185 of file node_composite_displace.c.
References CMP_NODE_DISPLACE, NODE_CLASS_DISTORT, node_composit_exec_displace(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_distance_matte (struct bNodeTreeType * ttype)
Definition at line 131 of file node_composite_distanceMatte.c.
References CMP_NODE_DIST_MATTE, NODE_CLASS_MATTE, node_composit_exec_distance_matte(), node_composit_init_distance_matte(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_doubleedgemask (struct bNodeTreeType * ttype)
Definition at line 1274 of file node_composite_doubleEdgeMask.c.
References CMP_NODE_DOUBLEEDGEMASK, NODE_CLASS_MATTE, node_composit_exec_doubleedgemask(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_filter (struct bNodeTreeType * ttype)
Definition at line 223 of file node_composite_filter.c.
References CMP_NODE_FILTER, NODE_CLASS_OP_FILTER, node_composit_exec_filter(), node_filter_label(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_label(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_flip (struct bNodeTreeType * ttype)
Definition at line 91 of file node_composite_flip.c.
References CMP_NODE_FLIP, NODE_CLASS_DISTORT, node_composit_exec_flip(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_forloop (struct bNodeTreeType * ttype)
void register_node_type_cmp_gamma (struct bNodeTreeType * ttype)
Definition at line 78 of file node_composite_gamma.c.
References CMP_NODE_GAMMA, NODE_CLASS_OP_COLOR, node_composit_exec_gamma(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_glare (struct bNodeTreeType * ttype)
Definition at line 493 of file node_composite_glare.c.
References CMP_NODE_GLARE, NODE_CLASS_OP_FILTER, node_composit_exec_glare(), node_composit_init_glare(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_group (struct bNodeTreeType * ttype)
Definition at line 216 of file node_composite_common.c.
References group_execute(), group_freeexec(), group_initexec(), NODE_CLASS_GROUP, NODE_CONST_OUTPUT, NODE_GROUP, node_group_edit_clear(), node_group_edit_get(), node_group_edit_set(), node_group_init(), node_group_label(), node_group_template(), node_group_valid(), node_group_verify(), NODE_OPTIONS, node_type_base(), node_type_exec_new(), node_type_group_edit(), node_type_init(), node_type_label(), node_type_size(), node_type_socket_templates(), node_type_template(), node_type_update(), node_type_valid(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
void register_node_type_cmp_hue_sat (struct bNodeTreeType * ttype)
Definition at line 105 of file node_composite_hueSatVal.c.
References CMP_NODE_HUE_SAT, NODE_CLASS_OP_COLOR, node_composit_exec_hue_sat(), node_composit_init_hue_sat(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_huecorrect (struct bNodeTreeType * ttype)
Definition at line 154 of file node_composite_huecorrect.c.
References CMP_NODE_HUECORRECT, NODE_CLASS_OP_COLOR, node_composit_exec_huecorrect(), node_composit_init_huecorrect(), node_copy_curves(), node_free_curves(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_idmask (struct bNodeTreeType * ttype)
Definition at line 110 of file node_composite_idMask.c.
References CMP_NODE_ID_MASK, NODE_CLASS_CONVERTOR, node_composit_exec_idmask(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_image (struct bNodeTreeType * ttype)
Definition at line 520 of file node_composite_image.c.
References CMP_NODE_IMAGE, cmp_node_image_update(), NODE_CLASS_INPUT, node_composit_exec_image(), node_composit_init_image(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_storage(), node_type_update(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
void register_node_type_cmp_invert (struct bNodeTreeType * ttype)
Definition at line 124 of file node_composite_invert.c.
References CMP_NODE_INVERT, NODE_CLASS_OP_COLOR, node_composit_exec_invert(), node_composit_init_invert(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_lensdist (struct bNodeTreeType * ttype)
Definition at line 193 of file node_composite_lensdist.c.
References CMP_NODE_LENSDIST, NODE_CLASS_DISTORT, node_composit_exec_lensdist(), node_composit_init_lensdist(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_luma_matte (struct bNodeTreeType * ttype)
Definition at line 107 of file node_composite_lummaMatte.c.
References CMP_NODE_LUMA_MATTE, NODE_CLASS_MATTE, node_composit_exec_luma_matte(), node_composit_init_luma_matte(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_map_value (struct bNodeTreeType * ttype)
Definition at line 85 of file node_composite_mapValue.c.
References CMP_NODE_MAP_VALUE, NODE_CLASS_OP_VECTOR, node_composit_exec_map_value(), node_composit_init_map_value(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_mapuv (struct bNodeTreeType * ttype)
Definition at line 165 of file node_composite_mapUV.c.
References CMP_NODE_MAP_UV, NODE_CLASS_DISTORT, node_composit_exec_mapuv(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_math (struct bNodeTreeType * ttype)
Definition at line 199 of file node_composite_math.c.
References CMP_NODE_MATH, NODE_CLASS_CONVERTOR, node_composit_exec_math(), node_math_label(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_label(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_mix_rgb (struct bNodeTreeType * ttype)
Definition at line 85 of file node_composite_mixrgb.c.
References CMP_NODE_MIX_RGB, node_blend_label(), NODE_CLASS_OP_COLOR, node_composit_exec_mix_rgb(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_label(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_movieclip (struct bNodeTreeType * ttype)
Definition at line 148 of file node_composite_movieclip.c.
References CMP_NODE_MOVIECLIP, init(), NODE_CLASS_INPUT, node_composit_exec_movieclip(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
void register_node_type_cmp_moviedistortion (struct bNodeTreeType * ttype)
Definition at line 130 of file node_composite_moviedistortion.c.
References CMP_NODE_MOVIEDISTORTION, exec(), label(), NODE_CLASS_DISTORT, NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_label(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, storage_copy(), and storage_free().
Referenced by registerCompositNodes().
void register_node_type_cmp_normal (struct bNodeTreeType * ttype)
Definition at line 94 of file node_composite_normal.c.
References CMP_NODE_NORMAL, init(), NODE_CLASS_OP_VECTOR, node_composit_exec_normal(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_normalize (struct bNodeTreeType * ttype)
Definition at line 105 of file node_composite_normalize.c.
References CMP_NODE_NORMALIZE, NODE_CLASS_OP_VECTOR, node_composit_exec_normalize(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_output_file (struct bNodeTreeType * ttype)
Definition at line 325 of file node_composite_outputFile.c.
References CMP_NODE_OUTPUT_FILE, copy_output_file(), exec_output_file(), free_output_file(), init_output_file(), NODE_CLASS_OUTPUT, NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), node_type_update(), nodeRegisterType(), NULL, and update_output_file().
Referenced by registerCompositNodes().
void register_node_type_cmp_premulkey (struct bNodeTreeType * ttype)
Definition at line 64 of file node_composite_premulkey.c.
References CMP_NODE_PREMULKEY, NODE_CLASS_CONVERTOR, node_composit_exec_premulkey(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_rgb (struct bNodeTreeType * ttype)
Definition at line 61 of file node_composite_rgb.c.
References CMP_NODE_RGB, NODE_CLASS_INPUT, node_composit_exec_rgb(), node_composit_init_rgb(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
void register_node_type_cmp_rgbtobw (struct bNodeTreeType * ttype)
Definition at line 140 of file node_composite_valToRgb.c.
References CMP_NODE_RGBTOBW, NODE_CLASS_CONVERTOR, node_composit_exec_rgbtobw(), node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_rlayers (struct bNodeTreeType * ttype)
Definition at line 671 of file node_composite_image.c.
References CMP_NODE_R_LAYERS, NODE_CLASS_INPUT, node_composit_exec_rlayers(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
void register_node_type_cmp_rotate (struct bNodeTreeType * ttype)
Definition at line 129 of file node_composite_rotate.c.
References CMP_NODE_ROTATE, NODE_CLASS_DISTORT, node_composit_exec_rotate(), node_composit_init_rotate(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_scale (struct bNodeTreeType * ttype)
Definition at line 133 of file node_composite_scale.c.
References CMP_NODE_SCALE, NODE_CLASS_DISTORT, node_composit_exec_scale(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_sephsva (struct bNodeTreeType * ttype)
Definition at line 102 of file node_composite_sepcombHSVA.c.
References CMP_NODE_SEPHSVA, NODE_CLASS_CONVERTOR, node_composit_exec_sephsva(), node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_seprgba (struct bNodeTreeType * ttype)
Definition at line 80 of file node_composite_sepcombRGBA.c.
References CMP_NODE_SEPRGBA, NODE_CLASS_CONVERTOR, node_composit_exec_seprgba(), node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_sepycca (struct bNodeTreeType * ttype)
Definition at line 151 of file node_composite_sepcombYCCA.c.
References CMP_NODE_SEPYCCA, NODE_CLASS_CONVERTOR, node_composit_exec_sepycca(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_sepyuva (struct bNodeTreeType * ttype)
Definition at line 102 of file node_composite_sepcombYUVA.c.
References CMP_NODE_SEPYUVA, NODE_CLASS_CONVERTOR, node_composit_exec_sepyuva(), node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_setalpha (struct bNodeTreeType * ttype)
Definition at line 76 of file node_composite_setalpha.c.
References CMP_NODE_SETALPHA, NODE_CLASS_CONVERTOR, node_composit_exec_setalpha(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_splitviewer (struct bNodeTreeType * ttype)
Definition at line 152 of file node_composite_splitViewer.c.
References CMP_NODE_SPLITVIEWER, NODE_CLASS_OUTPUT, node_composit_exec_splitviewer(), node_composit_init_splitviewer(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
void register_node_type_cmp_stabilize2d (struct bNodeTreeType * ttype)
Definition at line 69 of file node_composite_stabilize2d.c.
References CMP_NODE_STABILIZE2D, NODE_CLASS_DISTORT, node_composit_exec_stabilize2d(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_texture (struct bNodeTreeType * ttype)
Definition at line 145 of file node_composite_texture.c.
References CMP_NODE_TEXTURE, NODE_CLASS_INPUT, node_composit_exec_texture(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_tonemap (struct bNodeTreeType * ttype)
Definition at line 165 of file node_composite_tonemap.c.
References CMP_NODE_TONEMAP, NODE_CLASS_OP_COLOR, node_composit_exec_tonemap(), node_composit_init_tonemap(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_transform (struct bNodeTreeType * ttype)
Definition at line 130 of file node_composite_transform.c.
References CMP_NODE_TRANSFORM, NODE_CLASS_DISTORT, node_composit_exec_transform(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_translate (struct bNodeTreeType * ttype)
Definition at line 62 of file node_composite_translate.c.
References CMP_NODE_TRANSLATE, NODE_CLASS_DISTORT, node_composit_exec_translate(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_valtorgb (struct bNodeTreeType * ttype)
Definition at line 86 of file node_composite_valToRgb.c.
References CMP_NODE_VALTORGB, NODE_CLASS_CONVERTOR, node_composit_exec_valtorgb(), node_composit_init_valtorgb(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_value (struct bNodeTreeType * ttype)
Definition at line 60 of file node_composite_value.c.
References CMP_NODE_VALUE, NODE_CLASS_INPUT, node_composit_exec_value(), node_composit_init_value(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
void register_node_type_cmp_vecblur (struct bNodeTreeType * ttype)
Definition at line 97 of file node_composite_vecBlur.c.
References CMP_NODE_VECBLUR, NODE_CLASS_OP_FILTER, node_composit_exec_vecblur(), node_composit_init_vecblur(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_view_levels (struct bNodeTreeType * ttype)
Definition at line 323 of file node_composite_levels.c.
References CMP_NODE_VIEW_LEVELS, NODE_CLASS_OUTPUT, node_composit_exec_view_levels(), node_composit_init_view_levels(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
void register_node_type_cmp_viewer (struct bNodeTreeType * ttype)
Definition at line 134 of file node_composite_viewer.c.
References CMP_NODE_VIEWER, NODE_CLASS_OUTPUT, node_composit_exec_viewer(), node_composit_init_viewer(), node_copy_standard_storage(), node_free_standard_storage(), NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
void register_node_type_cmp_whileloop (struct bNodeTreeType * ttype)
void register_node_type_cmp_zcombine (struct bNodeTreeType * ttype)
Definition at line 225 of file node_composite_zcombine.c.
References CMP_NODE_ZCOMBINE, NODE_CLASS_OP_COLOR, node_composit_exec_zcombine(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeTreeType ntreeType_Composite
Definition at line 237 of file node_composite_tree.c.
Referenced by ntreeGetType().