Blender: node_composite_normal.c File Reference
node_composite_normal.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_normal (bNode *node, float *out, float *in)
static void node_composit_exec_normal (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void init (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_normal (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_normal_in []
static bNodeSocketTemplate cmp_node_normal_out []
Detailed Description
Definition in file node_composite_normal.c.
Function Documentation
static void do_normal (bNode * node, float * out, float * in) [static]
Definition at line 48 of file node_composite_normal.c.
References bNodeSocket::default_value, dot_v3v3(), ListBase::first, and bNode::outputs.
Referenced by node_composit_exec_normal().
static void init (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 84 of file node_composite_normal.c.
References bNodeSocket::default_value, ListBase::first, and bNode::outputs.
static void node_composit_exec_normal (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 58 of file node_composite_normal.c.
References alloc_compbuf(), CB_VAL, CB_VEC3, composit1_pixel_processor(), copy_v3_v3(), bNodeStack::data, data, bNodeSocket::default_value, do_normal(), dot_v3v3(), ListBase::first, NULL, bNode::outputs, bNodeStack::vec, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_normal().
void register_node_type_cmp_normal (bNodeTreeType * ttype)
Definition at line 94 of file node_composite_normal.c.
References CMP_NODE_NORMAL, init(), NODE_CLASS_OP_VECTOR, node_composit_exec_normal(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_normal_in[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 1, "Normal",   0.0f, 0.0f, 0.0f, 1.0f, -1.0f, 1.0f, PROP_DIRECTION},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_composite_normal.c.
bNodeSocketTemplate cmp_node_normal_out[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 0, "Normal"},
    {   SOCK_FLOAT, 0, "Dot"},
    {   -1, 0, ""   }
}
Definition at line 42 of file node_composite_normal.c.