Blender: bvh_sort.cpp File Reference
bvh_sort.cpp File Reference
#include "bvh_build.h"
#include "bvh_sort.h"
#include "util_algorithm.h"
#include "util_debug.h"
Classes
struct BVHReferenceCompare
Functions
void bvh_reference_sort (int start, int end, BVHBuild::Reference *data, int dim)
Function Documentation
void bvh_reference_sort (int start, int end, BVHBuild::Reference * data, int dim)
Definition at line 51 of file bvh_sort.cpp.
References sort().
Referenced by BVHBuild::do_object_split(), and BVHBuild::find_object_split().