Blender: renderpipeline.h File Reference
renderpipeline.h File Reference
Rendering
Functions
struct RenderLayer * render_get_active_layer (struct Render *re, struct RenderResult *rr)
float panorama_pixel_rot (struct Render *re)
Detailed Description
Definition in file renderpipeline.h.
Function Documentation
float panorama_pixel_rot (struct Render * re)
Definition at line 668 of file pipeline.c.
References KDL::atan(), Render::clipsta, Render::disprect, Render::partx, Render::viewplane, Render::winx, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, and Render::xparts.
Referenced by find_next_pano_slice(), and initparts().
struct RenderLayer* render_get_active_layer (struct Render * re, struct RenderResult * rr) [read]
Definition at line 214 of file pipeline.c.
References RenderData::actlay, BLI_findlink(), ListBase::first, RenderResult::layers, and Render::r.
Referenced by do_merge_fullsample(), do_render_blur_3d(), do_render_composite_fields_blur_3d(), do_render_fields_3d(), do_render_fields_blur_3d(), RE_AcquireResultImage(), zbufshade_sss_tile(), zbufshade_tile(), and zbufshadeDA_tile().