Blender: bmo_edgesplit.c File Reference
bmo_edgesplit.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "bmesh.h"
#include "intern/bmesh_operators_private.h"
Enumerations
enum { EDGE_SEAM = 1 }
enum { VERT_SEAM = 2 }
Functions
static void bm_edgesplit_validate_seams (BMesh *bm, BMOperator *op)
void bmo_edgesplit_exec (BMesh *bm, BMOperator *op)
Detailed Description
Definition in file bmo_edgesplit.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
EDGE_SEAM
Definition at line 35 of file bmo_edgesplit.c.
anonymous enum
Enumerator:
VERT_SEAM
Definition at line 39 of file bmo_edgesplit.c.
Function Documentation
static void bm_edgesplit_validate_seams (BMesh * bm, BMOperator * op) [static]
Remove the EDGE_SEAM flag for edges we cant split
un-tag edges not connected to other tagged edges, unless they are on a boundary
Definition at line 49 of file bmo_edgesplit.c.
References BM_EDGE, BM_edge_is_boundary(), BM_EDGES_OF_MESH, BM_elem_flag_disable, BM_elem_index_get, BM_ELEM_INTERNAL_TAG, BM_ITER_MESH, BM_mesh_elem_index_ensure(), BM_VERT, BMO_elem_flag_disable, BMO_ITER, EDGE_SEAM, BMEdge::l, MEM_callocN(), MEM_freeN(), NULL, BMesh::totvert, BMEdge::v1, and BMEdge::v2.
Referenced by bmo_edgesplit_exec().
void bmo_edgesplit_exec (BMesh * bm, BMOperator * op)
Definition at line 103 of file bmo_edgesplit.c.
References BM_EDGE, BM_edge_is_boundary(), bm_edgesplit_validate_seams(), BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_INTERNAL_TAG, BM_ELEM_TAG, BM_VERT, bmesh_edge_separate(), bmesh_vert_separate(), BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_hflag(), EDGE_SEAM, FALSE, BMEdge::l, NULL, UNLIKELY, BMEdge::v1, BMEdge::v2, and VERT_SEAM.