Blender: iTaSC::Solver Class Reference
iTaSC::Solver Class Reference
#include <Solver.hpp>
Public Types
enum SolverParam { DLS_QMAX = 0, DLS_LAMBDA_MAX, DLS_EPSILON }
Public Member Functions
virtual ~Solver ()
virtual bool init (unsigned int nq, unsigned int nc, const std::vector< bool > &gc)=0
virtual bool solve (const e_matrix &A, const e_vector &Wy, const e_vector &ydot, const e_matrix &Wq, e_vector &qdot, e_scalar &nlcoef)=0
virtual void setParam (SolverParam param, double value)=0
Detailed Description
Definition at line 16 of file Solver.hpp.
Member Enumeration Documentation
enum iTaSC::Solver::SolverParam
Enumerator:
DLS_QMAX
DLS_LAMBDA_MAX
DLS_EPSILON
Definition at line 18 of file Solver.hpp.
Constructor & Destructor Documentation
virtual iTaSC::Solver::~Solver () [inline, virtual]
Definition at line 23 of file Solver.hpp.
Member Function Documentation
virtual bool iTaSC::Solver::init (unsigned int nq, unsigned int nc, const std::vector< bool > & gc) [pure virtual]
Implemented in iTaSC::WDLSSolver, and iTaSC::WSDLSSolver.
Referenced by iTaSC::Scene::initialize().
virtual void iTaSC::Solver::setParam (SolverParam param, double value) [pure virtual]
Implemented in iTaSC::WDLSSolver, and iTaSC::WSDLSSolver.
Referenced by execute_scene().
virtual bool iTaSC::Solver::solve (const e_matrix & A, const e_vector & Wy, const e_vector & ydot, const e_matrix & Wq, e_vector & qdot, e_scalar & nlcoef) [pure virtual]
Implemented in iTaSC::WDLSSolver, and iTaSC::WSDLSSolver.
Referenced by iTaSC::Scene::update().
The documentation for this class was generated from the following file:
Solver.hpp