Blender: ED_particle.h File Reference
ED_particle.h File Reference
Editors
Functions
void PE_free_ptcache_edit (struct PTCacheEdit *edit)
int PE_start_edit (struct PTCacheEdit *edit)
struct PTCacheEdit * PE_get_current (struct Scene *scene, struct Object *ob)
struct PTCacheEdit * PE_create_current (struct Scene *scene, struct Object *ob)
void PE_current_changed (struct Scene *scene, struct Object *ob)
int PE_minmax (struct Scene *scene, float min[3], float max[3])
struct ParticleEditSettings * PE_settings (struct Scene *scene)
void PE_hide_keys_time (struct Scene *scene, struct PTCacheEdit *edit, float cfra)
void PE_update_object (struct Scene *scene, struct Object *ob, int useflag)
int PE_mouse_particles (struct bContext *C, const int mval[2], int extend)
int PE_border_select (struct bContext *C, struct rcti *rect, int select, int extend)
int PE_circle_select (struct bContext *C, int selecting, const int mval[2], float rad)
int PE_lasso_select (struct bContext *C, int mcords[][2], short moves, short extend, short select)
void PE_deselect_all_visible (struct PTCacheEdit *edit)
void PE_undo_push (struct Scene *scene, const char *str)
void PE_undo_step (struct Scene *scene, int step)
void PE_undo (struct Scene *scene)
void PE_redo (struct Scene *scene)
int PE_undo_valid (struct Scene *scene)
void PE_undo_number (struct Scene *scene, int nr)
const char * PE_undo_get_name (struct Scene *scene, int nr, int *active)
Detailed Description
Definition in file ED_particle.h.
Function Documentation
int PE_border_select (struct bContext * C, struct rcti * rect, int select, int extend)
Definition at line 1551 of file particle_edit.c.
References CTX_data_active_object(), CTX_data_scene(), data, for_mouse_hit_keys(), NA_SELECTED, NC_OBJECT, ND_PARTICLE, OPERATOR_CANCELLED, OPERATOR_FINISHED, PE_deselect_all_visible(), PE_get_current(), PE_set_view3d_data(), PE_start_edit(), PE_update_selection(), PEData::rect, PEData::select, select_key(), and WM_event_add_notifier().
Referenced by view3d_borderselect_exec().
int PE_circle_select (struct bContext * C, int selecting, const int mval[2], float rad)
Definition at line 1578 of file particle_edit.c.
References CTX_data_active_object(), CTX_data_scene(), data, for_mouse_hit_keys(), PEData::mval, NA_SELECTED, NC_OBJECT, ND_PARTICLE, OPERATOR_FINISHED, PE_get_current(), PE_set_view3d_data(), PE_start_edit(), PE_update_selection(), PEData::rad, PEData::select, select_key(), and WM_event_add_notifier().
Referenced by view3d_circle_select_exec().
struct PTCacheEdit* PE_create_current (struct Scene * scene, struct Object * ob) [read]
Definition at line 288 of file particle_edit.c.
References pe_get_current().
Referenced by draw_object(), particle_edit_toggle_exec(), and PE_current_changed().
void PE_current_changed (struct Scene * scene, struct Object * ob)
Definition at line 293 of file particle_edit.c.
References Object::mode, OB_MODE_PARTICLE_EDIT, and PE_create_current().
void PE_deselect_all_visible (struct PTCacheEdit * edit)
Definition at line 1539 of file particle_edit.c.
References KEY_K, LOOP_SELECTED_KEYS, LOOP_VISIBLE_POINTS, PEK_SELECT, PEP_EDIT_RECALC, and POINT_P.
Referenced by PE_border_select(), and PE_lasso_select().
void PE_free_ptcache_edit (struct PTCacheEdit * edit)
Definition at line 138 of file particle_edit.c.
References BLI_kdtree_free(), PTCacheEdit::emitter_cosnos, PTCacheEdit::emitter_field, LOOP_POINTS, MEM_freeN(), PTCacheEdit::mirror_cache, POINT_P, PTCacheEdit::points, PTCacheEdit::psys, psys_free_path_cache(), and PTCacheUndo_clear().
Referenced by clear_edited_exec(), PE_create_particle_edit(), and ptcache_free_bake_exec().
struct PTCacheEdit* PE_get_current (struct Scene * scene, struct Object * ob) [read]
Definition at line 283 of file particle_edit.c.
References pe_get_current().
Referenced by brush_edit_init(), calc_manipulator_stats(), createTransData(), createTransParticleVerts(), flushTransParticles(), hide_exec(), mirror_exec(), PE_border_select(), PE_circle_select(), PE_hair_poll(), PE_lasso_select(), PE_minmax(), PE_mirror_x(), PE_mouse_particles(), PE_poll(), pe_select_all_exec(), PE_set_data(), PE_undo_get_name(), PE_undo_number(), PE_undo_push(), PE_undo_step(), PE_undo_valid(), PE_update_object(), PE_update_selection(), recalcData_view3d(), rekey_particle_to_time(), remove_doubles_exec(), reveal_exec(), special_aftertrans_update(), and weight_set_exec().
void PE_hide_keys_time (struct Scene * scene, struct PTCacheEdit * edit, float cfra)
Definition at line 299 of file particle_edit.c.
References fabs(), ParticleEditSettings::fade_frames, ParticleEditSettings::flag, KEY_K, LOOP_KEYS, LOOP_POINTS, PE_FADE_TIME, PE_settings(), PEK_HIDE, POINT_P, SCE_SELECT_POINT, and ParticleEditSettings::selectmode.
Referenced by draw_ptcache_edit(), and PE_update_object().
int PE_lasso_select (struct bContext * C, int mcords[][2], short moves, short extend, short select)
Definition at line 1603 of file particle_edit.c.
References co, copy_v3_v3(), CTX_data_active_object(), CTX_data_scene(), CTX_wm_region(), data, ParticleSystemModifierData::dm, ParticleSystem::flag, ParticleSettings::from, IS_CLIPPED, KEY_K, key_test_depth(), lasso_inside(), LOOP_KEYS, LOOP_VISIBLE_POINTS, MAT4_UNITY, mul_m4_v3(), NA_SELECTED, NC_OBJECT, ND_PARTICLE, OPERATOR_CANCELLED, OPERATOR_FINISHED, p, ParticleSystem::part, ParticleSystem::particles, PE_deselect_all_visible(), PE_get_current(), PE_set_view3d_data(), PE_settings(), PE_start_edit(), PE_update_selection(), PEK_SELECT, PEP_EDIT_RECALC, POINT_P, project_int(), PTCacheEdit::psys, psys_get_modifier(), PSYS_GLOBAL_HAIR, psys_mat_hair_to_global(), SCE_SELECT_END, SCE_SELECT_POINT, ParticleEditSettings::selectmode, and WM_event_add_notifier().
Referenced by view3d_lasso_select().
int PE_minmax (struct Scene * scene, float min[3], float max[3])
Definition at line 4032 of file particle_edit.c.
References co, copy_v3_v3(), ParticleSystemModifierData::dm, DO_MINMAX, ParticleSettings::from, KEY_K, LOOP_SELECTED_KEYS, LOOP_VISIBLE_POINTS, minmax_object(), mul_m4_v3(), NULL, OBACT, p, ParticleSystem::part, ParticleSystem::particles, PE_get_current(), POINT_P, PTCacheEdit::psys, psys_get_modifier(), psys_mat_hair_to_global(), and unit_m4().
Referenced by viewselected_exec().
int PE_mouse_particles (struct bContext * C, const int mval[2], int extend)
Definition at line 1379 of file particle_edit.c.
References CTX_data_active_object(), CTX_data_scene(), data, for_mouse_hit_keys(), KEY_K, LOOP_SELECTED_KEYS, LOOP_VISIBLE_POINTS, PEData::mval, NA_SELECTED, NC_OBJECT, ND_PARTICLE, PEData::ob, OPERATOR_CANCELLED, OPERATOR_FINISHED, PE_get_current(), PE_set_view3d_data(), PE_start_edit(), PE_update_selection(), PEK_SELECT, PEP_EDIT_RECALC, POINT_P, PEData::rad, toggle_key_select(), and WM_event_add_notifier().
Referenced by view3d_select_invoke().
void PE_redo (struct Scene * scene)
Definition at line 3991 of file particle_edit.c.
References PE_undo_step().
Referenced by ed_undo_step().
struct ParticleEditSettings* PE_settings (struct Scene * scene) [read]
Definition at line 189 of file particle_edit.c.
References NULL, ToolSettings::particle, and Scene::toolsettings.
Referenced by brush_add(), brush_comb(), brush_cut(), brush_drawcursor(), brush_edit_apply(), brush_edit_init(), brush_puff(), count_selected_keys(), createTransParticleVerts(), disconnect_hair(), draw_new_particle_system(), draw_ptcache_edit(), for_mouse_hit_keys(), foreach_mouse_hit_key(), foreach_mouse_hit_point(), PE_apply_lengths(), pe_deflect_emitter(), pe_get_current(), PE_hide_keys_time(), pe_iterate_lengths(), PE_lasso_select(), PE_update_object(), toggle_particle_cursor(), and weight_set_exec().
int PE_start_edit (struct PTCacheEdit * edit)
Definition at line 177 of file particle_edit.c.
References PTCacheEdit::edited, ParticleSystem::flag, PTCacheEdit::psys, and PSYS_EDITED.
Referenced by brush_edit_apply(), createTransData(), PE_border_select(), PE_circle_select(), PE_lasso_select(), and PE_mouse_particles().
void PE_undo (struct Scene * scene)
Definition at line 3986 of file particle_edit.c.
References PE_undo_step().
Referenced by ed_undo_step().
const char* PE_undo_get_name (struct Scene * scene, int nr, int * active)
Definition at line 4012 of file particle_edit.c.
References BLI_findlink(), PTCacheEdit::curundo, PTCacheUndo::name, NULL, OBACT, PE_get_current(), and PTCacheEdit::undo.
Referenced by rna_undo_itemf().
void PE_undo_number (struct Scene * scene, int nr)
Definition at line 3996 of file particle_edit.c.
References PTCacheEdit::curundo, ListBase::first, PTCacheUndo::next, OBACT, PE_get_current(), PE_undo_step(), and PTCacheEdit::undo.
Referenced by undo_history_exec().
void PE_undo_push (struct Scene * scene, const char * str)
Definition at line 3887 of file particle_edit.c.
References BLI_addtail(), BLI_remlink(), BLI_strncpy(), PTCacheEdit::curundo, ListBase::first, free_PTCacheUndo(), ListBase::last, make_PTCacheUndo(), MEM_callocN(), MEM_freeN(), PTCacheUndo::name, OBACT, PE_get_current(), PTCacheUndo::prev, and PTCacheEdit::undo.
Referenced by ED_undo_push(), and PE_create_particle_edit().
void PE_undo_step (struct Scene * scene, int step)
Definition at line 3929 of file particle_edit.c.
References PTCacheEdit::curundo, DAG_id_tag_update(), G, G_DEBUG, get_PTCacheUndo(), PTCacheUndo::name, PTCacheUndo::next, NULL, OB_RECALC_DATA, OBACT, PE_get_current(), and PTCacheUndo::prev.
Referenced by PE_redo(), PE_undo(), and PE_undo_number().
int PE_undo_valid (struct Scene * scene)
Definition at line 3961 of file particle_edit.c.
References ListBase::first, ListBase::last, OBACT, PE_get_current(), and PTCacheEdit::undo.
Referenced by ED_undo_valid().
void PE_update_object (struct Scene * scene, struct Object * ob, int useflag)
Definition at line 1216 of file particle_edit.c.
References CFRA, ParticleSystem::flag, ParticleEditSettings::flag, LOOP_POINTS, PE_apply_lengths(), PE_apply_mirror(), PE_AUTO_VELOCITY, pe_deflect_emitter(), PE_get_current(), PE_hide_keys_time(), pe_iterate_lengths(), PE_settings(), pe_x_mirror(), PEP_EDIT_RECALC, POINT_P, PTCacheEdit::psys, psys_cache_edit_paths(), PSYS_HAIR_UPDATED, update_velocities(), and update_world_cos().
Referenced by brush_edit_apply(), connect_hair(), disconnect_hair(), draw_update_ptcache_edit(), flushTransParticles(), PE_create_particle_edit(), rekey_exec(), and subdivide_exec().