Blender: rna_dynamicpaint.c File Reference
rna_dynamicpaint.c File Reference
RNA
#include <stdlib.h>
#include <limits.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "BKE_modifier.h"
#include "BKE_dynamicpaint.h"
#include "DNA_dynamicpaint_types.h"
#include "DNA_modifier_types.h"
#include "DNA_object_force.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "WM_types.h"
Functions
static void rna_def_canvas_surfaces (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_canvas_surface (BlenderRNA *brna)
static void rna_def_dynamic_paint_canvas_settings (BlenderRNA *brna)
static void rna_def_dynamic_paint_brush_settings (BlenderRNA *brna)
void RNA_def_dynamic_paint (BlenderRNA *brna)
Variables
EnumPropertyItem prop_dynamicpaint_type_items []
Detailed Description
Definition in file rna_dynamicpaint.c.
Function Documentation
static void rna_def_canvas_surface (BlenderRNA * brna) [static]
Definition at line 301 of file rna_dynamicpaint.c.
References MOD_DPAINT_ACTIVE, MOD_DPAINT_ANTIALIAS, MOD_DPAINT_DISP_DEPTH, MOD_DPAINT_DISP_DISPLACE, MOD_DPAINT_DISP_INCREMENTAL, MOD_DPAINT_DISSOLVE, MOD_DPAINT_DISSOLVE_LOG, MOD_DPAINT_DRY_LOG, MOD_DPAINT_EFFECT_DO_DRIP, MOD_DPAINT_EFFECT_DO_SHRINK, MOD_DPAINT_EFFECT_DO_SPREAD, MOD_DPAINT_IMGFORMAT_OPENEXR, MOD_DPAINT_IMGFORMAT_PNG, MOD_DPAINT_INITIAL_COLOR, MOD_DPAINT_INITIAL_NONE, MOD_DPAINT_INITIAL_TEXTURE, MOD_DPAINT_INITIAL_VERTEXCOLOR, MOD_DPAINT_MULALPHA, MOD_DPAINT_OUT1, MOD_DPAINT_OUT2, MOD_DPAINT_PREVIEW, MOD_DPAINT_SURFACE_F_IMAGESEQ, MOD_DPAINT_SURFACE_F_VERTEX, MOD_DPAINT_SURFACE_PREV_PAINT, MOD_DPAINT_SURFACE_PREV_WETMAP, MOD_DPAINT_SURFACE_T_PAINT, MOD_DPAINT_USE_DRYING, MOD_DPAINT_WAVE_OPEN_BORDERS, NC_MATERIAL, NC_OBJECT, ND_MODIFIER, ND_SHADING_DRAW, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLOR_GAMMA, PROP_DIRPATH, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REQUIRED, PROP_STRING, RNA_def_boolean(), RNA_def_function(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_dynamic_paint().
static void rna_def_canvas_surfaces (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 277 of file rna_dynamicpaint.c.
References NC_OBJECT, ND_DRAW, NULL, PROP_ANIMATABLE, PROP_INT, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_int_funcs(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_dynamic_paint_canvas_settings().
void RNA_def_dynamic_paint (BlenderRNA * brna)
Definition at line 957 of file rna_dynamicpaint.c.
References rna_def_canvas_surface(), rna_def_dynamic_paint_brush_settings(), and rna_def_dynamic_paint_canvas_settings().
static void rna_def_dynamic_paint_brush_settings (BlenderRNA * brna) [static]
Definition at line 723 of file rna_dynamicpaint.c.
References MOD_DPAINT_ABS_ALPHA, MOD_DPAINT_COL_DIST, MOD_DPAINT_COL_POINT, MOD_DPAINT_COL_PSYS, MOD_DPAINT_COL_VOLDIST, MOD_DPAINT_COL_VOLUME, MOD_DPAINT_DO_SMUDGE, MOD_DPAINT_ERASE, MOD_DPAINT_INVERSE_PROX, MOD_DPAINT_NEGATE_VOLUME, MOD_DPAINT_PART_RAD, MOD_DPAINT_PRFALL_CONSTANT, MOD_DPAINT_PRFALL_RAMP, MOD_DPAINT_PRFALL_SMOOTH, MOD_DPAINT_PROX_PROJECT, MOD_DPAINT_RAMP_ALPHA, MOD_DPAINT_RAY_BRUSH_AVG, MOD_DPAINT_RAY_CANVAS, MOD_DPAINT_RAY_ZPLUS, MOD_DPAINT_USE_MATERIAL, MOD_DPAINT_VELOCITY_ALPHA, MOD_DPAINT_VELOCITY_COLOR, MOD_DPAINT_VELOCITY_DEPTH, MOD_DPAINT_WAVEB_CHANGE, MOD_DPAINT_WAVEB_DEPTH, MOD_DPAINT_WAVEB_FORCE, MOD_DPAINT_WAVEB_REFLECT, NC_OBJECT, ND_MODIFIER, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLOR_GAMMA, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_dynamic_paint().
static void rna_def_dynamic_paint_canvas_settings (BlenderRNA * brna) [static]
Definition at line 701 of file rna_dynamicpaint.c.
References NULL, PROP_COLLECTION, PROP_NONE, rna_def_canvas_surfaces(), RNA_def_property(), RNA_def_property_collection_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_dynamic_paint().
Variable Documentation
EnumPropertyItem prop_dynamicpaint_type_items[]
Initial value:
 {
        {MOD_DYNAMICPAINT_TYPE_CANVAS, "CANVAS", 0, "Canvas", ""},
        {MOD_DYNAMICPAINT_TYPE_BRUSH, "BRUSH", 0, "Brush", ""},
        {0, NULL, 0, NULL, NULL}}
Definition at line 46 of file rna_dynamicpaint.c.
Referenced by DPAINT_OT_type_toggle(), and rna_def_modifier_dynamic_paint().