Blender: BKE_smoke.h File Reference
BKE_smoke.h File Reference
blenkernel
Typedefs
typedef float(* bresenham_callback)(float *result, float *input, int res[3], int *pixel, float *tRay, float correct)
Functions
void smokeModifier_do (struct SmokeModifierData *smd, struct Scene *scene, struct Object *ob, struct DerivedMesh *dm)
void smokeModifier_free (struct SmokeModifierData *smd)
void smokeModifier_reset (struct SmokeModifierData *smd)
void smokeModifier_reset_turbulence (struct SmokeModifierData *smd)
void smokeModifier_createType (struct SmokeModifierData *smd)
void smokeModifier_copy (struct SmokeModifierData *smd, struct SmokeModifierData *tsmd)
long long smoke_get_mem_req (int xres, int yres, int zres, int amplify)
Detailed Description
Author:
Daniel Genrich
Definition in file BKE_smoke.h.
Typedef Documentation
typedef float(* bresenham_callback)(float *result, float *input, int res[3], int *pixel, float *tRay, float correct)
Definition at line 36 of file BKE_smoke.h.
Function Documentation
long long smoke_get_mem_req (int xres, int yres, int zres, int amplify)
void smokeModifier_copy (struct SmokeModifierData * smd, struct SmokeModifierData * tsmd)
Definition at line 795 of file smoke.c.
References SmokeDomainSettings::alpha, SmokeDomainSettings::amplify, SmokeDomainSettings::beta, SmokeDomainSettings::border_collisions, SmokeModifierData::coll, SmokeDomainSettings::coll_group, SmokeFlowSettings::density, SmokeDomainSettings::diss_speed, SmokeModifierData::domain, SmokeDomainSettings::effector_weights, SmokeFlowSettings::flags, SmokeDomainSettings::flags, SmokeModifierData::flow, SmokeDomainSettings::fluid_group, SmokeDomainSettings::maxres, MEM_dupallocN(), MEM_freeN(), SmokeDomainSettings::noise, SmokeDomainSettings::omega, SmokeFlowSettings::psys, smokeModifier_createType(), SmokeDomainSettings::strength, SmokeFlowSettings::temp, SmokeModifierData::time, SmokeDomainSettings::time_scale, SmokeFlowSettings::type, SmokeModifierData::type, SmokeFlowSettings::vel_multi, SmokeDomainSettings::viewsettings, and SmokeDomainSettings::vorticity.
Referenced by copyData().
void smokeModifier_createType (struct SmokeModifierData * smd)
Definition at line 715 of file smoke.c.
References SmokeDomainSettings::alpha, SmokeDomainSettings::amplify, SmokeDomainSettings::beta, BKE_add_effector_weights(), BKE_ptcache_add(), SmokeDomainSettings::border_collisions, SmokeCollSettings::bvhtree, SmokeModifierData::coll, SmokeDomainSettings::coll_group, SmokeFlowSettings::density, SmokeDomainSettings::diss_speed, SmokeModifierData::domain, SmokeDomainSettings::eff_group, SmokeDomainSettings::effector_weights, ListBase::first, PointCache::flag, SmokeFlowSettings::flags, SmokeDomainSettings::flags, SmokeModifierData::flow, SmokeDomainSettings::fluid, SmokeDomainSettings::fluid_group, ListBase::last, SmokeDomainSettings::maxres, MEM_callocN(), MOD_SMOKE_DISSOLVE_LOG, MOD_SMOKE_FLOW_ABSOLUTE, MOD_SMOKE_HIGH_SMOOTH, MOD_SMOKE_NOISEWAVE, MOD_SMOKE_TYPE_COLL, MOD_SMOKE_TYPE_DOMAIN, MOD_SMOKE_TYPE_FLOW, MOD_SMOKE_VIEW_SHOWBIG, SmokeDomainSettings::noise, NULL, SmokeCollSettings::numpoints, SmokeDomainSettings::omega, SmokeDomainSettings::point_cache, SmokeCollSettings::points, SmokeFlowSettings::psys, PTCACHE_DISK_CACHE, SmokeDomainSettings::ptcaches, SmokeCollSettings::smd, SmokeFlowSettings::smd, SmokeDomainSettings::smd, smokeModifier_freeCollision(), smokeModifier_freeDomain(), smokeModifier_freeFlow(), PointCache::step, SmokeDomainSettings::strength, SmokeFlowSettings::temp, SmokeDomainSettings::time_scale, SmokeModifierData::type, SmokeFlowSettings::vel_multi, SmokeDomainSettings::viewsettings, SmokeDomainSettings::vorticity, and SmokeDomainSettings::wt.
Referenced by smokeModifier_copy().
void smokeModifier_do (struct SmokeModifierData * smd, struct Scene * scene, struct Object * ob, struct DerivedMesh * dm)
Referenced by deformVerts().
void smokeModifier_free (struct SmokeModifierData * smd)
Definition at line 705 of file smoke.c.
References smokeModifier_freeCollision(), smokeModifier_freeDomain(), and smokeModifier_freeFlow().
Referenced by freeData().
void smokeModifier_reset (struct SmokeModifierData * smd)
Definition at line 648 of file smoke.c.
References BLI_bvhtree_free(), SmokeCollSettings::bvhtree, SmokeModifierData::coll, SmokeModifierData::domain, SmokeModifierData::flow, SmokeDomainSettings::fluid, MEM_freeN(), NULL, SmokeCollSettings::points, SmokeDomainSettings::shadow, smoke_free(), smokeModifier_reset_turbulence(), and SmokeModifierData::time.
Referenced by BKE_ptcache_id_reset().
void smokeModifier_reset_turbulence (struct SmokeModifierData * smd)
Definition at line 639 of file smoke.c.
References SmokeModifierData::domain, NULL, smoke_turbulence_free(), and SmokeDomainSettings::wt.
Referenced by BKE_ptcache_id_reset(), and smokeModifier_reset().