Blender: rna_ui.c File Reference
rna_ui.c File Reference
RNA
#include <stdlib.h>
#include "DNA_screen_types.h"
#include "RNA_define.h"
#include "rna_internal.h"
#include "RNA_enum_types.h"
#include "UI_interface.h"
#include "WM_types.h"
Functions
static void rna_def_ui_layout (BlenderRNA *brna)
static void rna_def_panel (BlenderRNA *brna)
static void rna_def_header (BlenderRNA *brna)
static void rna_def_menu (BlenderRNA *brna)
void RNA_def_ui (BlenderRNA *brna)
Variables
EnumPropertyItem operator_context_items []
Detailed Description
Definition in file rna_ui.c.
Function Documentation
static void rna_def_header (BlenderRNA * brna) [static]
Definition at line 738 of file rna_ui.c.
References FUNC_REGISTER, NULL, PROP_ENUM, PROP_NEVER_CLAMP, PROP_NONE, PROP_POINTER, PROP_REGISTER, PROP_REQUIRED, PROP_STRING, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_refine_func(), RNA_def_struct_register_funcs(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), RNA_define_verify_sdna(), and space_type_items.
Referenced by RNA_def_ui().
static void rna_def_menu (BlenderRNA * brna) [static]
Definition at line 784 of file rna_ui.c.
References FUNC_NO_SELF, FUNC_REGISTER, FUNC_REGISTER_OPTIONAL, NULL, PROP_NEVER_CLAMP, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REGISTER, PROP_REGISTER_OPTIONAL, PROP_REQUIRED, PROP_STRING, PROP_TRANSLATE, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_refine_func(), RNA_def_struct_register_funcs(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), RNA_define_verify_sdna(), and RNA_DYN_DESCR_MAX.
Referenced by RNA_def_ui().
static void rna_def_panel (BlenderRNA * brna) [static]
Definition at line 642 of file rna_ui.c.
References FUNC_NO_SELF, FUNC_REGISTER, FUNC_REGISTER_OPTIONAL, NULL, PNL_DEFAULT_CLOSED, PNL_NO_HEADER, PROP_ENUM, PROP_ENUM_FLAG, PROP_NEVER_CLAMP, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REGISTER, PROP_REGISTER_OPTIONAL, PROP_REQUIRED, PROP_STRING, region_type_items, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_refine_func(), RNA_def_struct_register_funcs(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and space_type_items.
Referenced by RNA_def_ui().
void RNA_def_ui (BlenderRNA * brna)
Definition at line 848 of file rna_ui.c.
References rna_def_header(), rna_def_menu(), rna_def_panel(), and rna_def_ui_layout().
static void rna_def_ui_layout (BlenderRNA * brna) [static]
Definition at line 591 of file rna_ui.c.
References NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_UNSIGNED, RNA_api_ui_layout(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_float_funcs(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), UI_LAYOUT_ALIGN_CENTER, UI_LAYOUT_ALIGN_EXPAND, UI_LAYOUT_ALIGN_LEFT, and UI_LAYOUT_ALIGN_RIGHT.
Referenced by RNA_def_ui().
Variable Documentation
EnumPropertyItem operator_context_items[]
Initial value:
 {
    {WM_OP_INVOKE_DEFAULT, "INVOKE_DEFAULT", 0, "Invoke Default", ""},
    {WM_OP_INVOKE_REGION_WIN, "INVOKE_REGION_WIN", 0, "Invoke Region Window", ""},
    {WM_OP_INVOKE_REGION_CHANNELS, "INVOKE_REGION_CHANNELS", 0, "Invoke Region Channels", ""},
    {WM_OP_INVOKE_REGION_PREVIEW, "INVOKE_REGION_PREVIEW", 0, "Invoke Region Preview", ""},
    {WM_OP_INVOKE_AREA, "INVOKE_AREA", 0, "Invoke Area", ""},
    {WM_OP_INVOKE_SCREEN, "INVOKE_SCREEN", 0, "Invoke Screen", ""},
    {WM_OP_EXEC_DEFAULT, "EXEC_DEFAULT", 0, "Exec Default", ""},
    {WM_OP_EXEC_REGION_WIN, "EXEC_REGION_WIN", 0, "Exec Region Window", ""},
    {WM_OP_EXEC_REGION_CHANNELS, "EXEC_REGION_CHANNELS", 0, "Exec Region Channels", ""},
    {WM_OP_EXEC_REGION_PREVIEW, "EXEC_REGION_PREVIEW", 0, "Exec Region Preview", ""},
    {WM_OP_EXEC_AREA, "EXEC_AREA", 0, "Exec Area", ""},
    {WM_OP_EXEC_SCREEN, "EXEC_SCREEN", 0, "Exec Screen", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 42 of file rna_ui.c.
Referenced by pyop_call(), and pyop_poll().