Blender: BLI_memarena.c File Reference
BLI_memarena.c File Reference
blenlib
#include "MEM_guardedalloc.h"
#include "BLI_memarena.h"
#include "BLI_linklist.h"
Classes
class MemArena
Defines
#define PADUP(num, amt) ((num + (amt - 1)) &~ (amt-1))
Functions
MemArena * BLI_memarena_new (int bufsize, const char *name)
void BLI_memarena_use_calloc (MemArena *ma)
void BLI_memarena_use_malloc (MemArena *ma)
void BLI_memarena_use_align (struct MemArena *ma, int align)
void BLI_memarena_free (MemArena *ma)
void * BLI_memarena_alloc (MemArena *ma, int size)
Detailed Description
Definition in file BLI_memarena.c.
Define Documentation
#define PADUP (num, amt) ((num + (amt - 1)) &~ (amt-1))
Definition at line 82 of file BLI_memarena.c.
Referenced by BLI_memarena_alloc().
Function Documentation
void* BLI_memarena_alloc (MemArena * ma, int size)
Definition at line 84 of file BLI_memarena.c.
References MemArena::align, BLI_linklist_prepend(), MemArena::bufs, MemArena::bufsize, MemArena::curbuf, MemArena::cursize, MEM_callocN(), MEM_mallocN(), MemArena::name, PADUP, size(), and MemArena::use_calloc.
Referenced by arena_alloc(), arena_realloc(), BLI_heap_insert(), BLI_linklist_prepend_arena(), BME_assign_transdata(), BME_new_transdata_float(), BMO_op_vinitf(), bmo_slot_buffer_alloc(), BMO_slot_buffer_append(), BMO_slot_copy(), BMO_slot_map_insert(), BMO_slot_mat_set(), BuildBinaryVBVH< Node >::create_node(), create_octree_node(), find_hole_chains(), imb_global_cache_get_tile(), imb_thread_cache_init(), isb_add_shadfac(), isb_alloc_sample_transp(), isb_bsp_split(), isb_bsp_split_init(), knife_empty_list(), meshdeform_matrix_solve(), meshdeform_ray_tree_intersect(), occ_build_recursive(), occ_tree_build(), p_face_add(), p_node_new(), p_vert_add(), p_vert_copy(), project_paint_begin(), project_paint_end(), project_paint_op(), project_paint_uvpixel_init(), scatter_tree_build(), set_dupli_tex_mat(), strand_shade_refcount(), sum_or_add_vertex_tangent(), vpaint_build_poly_facemap(), and zbuffer_strands_abuf().
void BLI_memarena_free (MemArena * ma)
Definition at line 75 of file BLI_memarena.c.
References BLI_linklist_free(), MemArena::bufs, and MEM_freeN().
Referenced by arena_release(), BLI_heap_free(), BME_free_transdata(), BMO_op_finish(), bvh_done< VBVHTree >(), bvh_free(), calc_vertexnormals(), cloth_bvh_objcollisions_nearcheck(), DM_add_tangent_layer(), do_projectpaint_thread(), harmonic_coordinates_bind(), imb_tile_cache_exit(), ISB_free(), isb_make_buffer(), isb_make_buffer_transp(), knifetool_exit(), occ_free_tree(), p_smooth(), param_delete(), project_paint_end(), RE_Database_Free(), scatter_tree_free(), strand_shade_cache_free(), vpaint_stroke_done(), and zbuffer_strands_abuf().
MemArena* BLI_memarena_new (int bufsize, const char * name) [read]
Definition at line 49 of file BLI_memarena.c.
References MemArena::align, MemArena::bufsize, MEM_callocN(), and MemArena::name.
Referenced by _getSubSurf(), BLI_heap_new(), BME_init_transdata(), BMO_op_init(), bvh_done< VBVHTree >(), calc_vertexnormals(), cloth_bvh_objcollisions_nearcheck(), database_fromscene_vectors(), DM_add_tangent_layer(), do_projectpaint_thread(), harmonic_coordinates_bind(), IMB_tile_cache_params(), isb_make_buffer(), isb_make_buffer_transp(), knifetool_init(), occ_tree_build(), p_smooth(), param_construct_begin(), project_paint_begin(), RE_Database_Baking(), RE_Database_FromScene(), scatter_tree_build(), strand_shade_cache_create(), vpaint_build_poly_facemap(), and zbuffer_strands_abuf().
void BLI_memarena_use_align (struct MemArena * ma, int align)
Definition at line 69 of file BLI_memarena.c.
References MemArena::align.
void BLI_memarena_use_calloc (MemArena * ma)
Definition at line 59 of file BLI_memarena.c.
References MemArena::use_calloc.
Referenced by BME_init_transdata(), BMO_op_init(), calc_vertexnormals(), DM_add_tangent_layer(), harmonic_coordinates_bind(), IMB_tile_cache_params(), isb_make_buffer(), isb_make_buffer_transp(), occ_tree_build(), scatter_tree_build(), and vpaint_build_poly_facemap().
void BLI_memarena_use_malloc (MemArena * ma)
Definition at line 64 of file BLI_memarena.c.
References MemArena::use_calloc.
Referenced by bvh_done< VBVHTree >().