Blender: KX_ConvertActuators.cpp File Reference
KX_ConvertActuators.cpp File Reference
Converter
#include <math.h>
#include "MEM_guardedalloc.h"
#include "KX_BlenderSceneConverter.h"
#include "KX_ConvertActuators.h"
#include "SCA_PropertyActuator.h"
#include "SCA_LogicManager.h"
#include "SCA_RandomActuator.h"
#include "SCA_2DFilterActuator.h"
#include "KX_SceneActuator.h"
#include "KX_IpoActuator.h"
#include "KX_SoundActuator.h"
#include "KX_ObjectActuator.h"
#include "KX_TrackToActuator.h"
#include "KX_ConstraintActuator.h"
#include "KX_CameraActuator.h"
#include "KX_GameActuator.h"
#include "KX_StateActuator.h"
#include "KX_VisibilityActuator.h"
#include "KX_SCA_AddObjectActuator.h"
#include "KX_SCA_EndObjectActuator.h"
#include "KX_SCA_ReplaceMeshActuator.h"
#include "KX_ParentActuator.h"
#include "KX_SCA_DynamicActuator.h"
#include "KX_SteeringActuator.h"
#include "KX_Scene.h"
#include "KX_KetsjiEngine.h"
#include "IntValue.h"
#include "KX_GameObject.h"
#include "BKE_text.h"
#include "BLI_blenlib.h"
#include "BLI_math_base.h"
#include "KX_NetworkMessageActuator.h"
#include "DNA_object_types.h"
#include "DNA_sound_types.h"
#include "DNA_scene_types.h"
#include "DNA_actuator_types.h"
#include "DNA_packedFile_types.h"
#include "BL_ActionActuator.h"
#include "BL_ShapeActionActuator.h"
#include "BL_ArmatureActuator.h"
#include "RNA_access.h"
#include "BL_Action.h"
#include "BL_BlenderDataConversion.h"
Defines
#define FILE_MAX 1024
#define KX_BLENDERTRUNC(x) ((x < 0.0001 && x > -0.0001) ? 0.0 : x)
Functions
void BL_ConvertActuators (const char *maggiename, struct Object *blenderobject, KX_GameObject *gameobj, SCA_LogicManager *logicmgr, KX_Scene *scene, KX_KetsjiEngine *ketsjiEngine, int activeLayerBitInfo, bool isInActiveLayer, RAS_IRenderTools *rendertools, KX_BlenderSceneConverter *converter)
Detailed Description
Definition in file KX_ConvertActuators.cpp.
Define Documentation
#define FILE_MAX 1024
Definition at line 86 of file KX_ConvertActuators.cpp.
#define KX_BLENDERTRUNC (x) ((x < 0.0001 && x > -0.0001) ? 0.0 : x)
KX_BLENDERTRUNC needed to round 'almost' zero values to zero, else velocities etc. are incorrectly set
Definition at line 112 of file KX_ConvertActuators.cpp.
Referenced by BL_ConvertActuators().
Function Documentation
void BL_ConvertActuators (const char * maggiename, struct Object * blenderobject, KX_GameObject * gameobj, SCA_LogicManager * logicmgr, KX_Scene * scene, KX_KetsjiEngine * ketsjiEngine, int activeLayerBitInfo, bool isInActiveLayer, RAS_IRenderTools * rendertools, KX_BlenderSceneConverter * converter)
Definition at line 114 of file KX_ConvertActuators.cpp.
References bSteeringActuator::acceleration, bActionActuator::act, ACT_2DFILTER, ACT_2DFILTER_BLUR, ACT_2DFILTER_CUSTOMFILTER, ACT_2DFILTER_DILATION, ACT_2DFILTER_DISABLED, ACT_2DFILTER_ENABLED, ACT_2DFILTER_EROSION, ACT_2DFILTER_GRAYSCALE, ACT_2DFILTER_INVERT, ACT_2DFILTER_LAPLACIAN, ACT_2DFILTER_MOTIONBLUR, ACT_2DFILTER_NOFILTER, ACT_2DFILTER_PREWITT, ACT_2DFILTER_SEPIA, ACT_2DFILTER_SHARPEN, ACT_2DFILTER_SOBEL, ACT_ACTION, ACT_ADD_LIN_VEL, ACT_ANG_VEL_LOCAL, ACT_ARMATURE, ACT_CAMERA, ACT_CONST_DIRNX, ACT_CONST_DIRNY, ACT_CONST_DIRNZ, ACT_CONST_DIRPX, ACT_CONST_DIRPY, ACT_CONST_DIRPZ, ACT_CONST_LOCX, ACT_CONST_LOCY, ACT_CONST_LOCZ, ACT_CONST_ROTX, ACT_CONST_ROTY, ACT_CONST_ROTZ, ACT_CONST_TYPE_DIST, ACT_CONST_TYPE_FH, ACT_CONST_TYPE_ORI, ACT_CONSTRAINT, ACT_DLOC_LOCAL, ACT_DROT_LOCAL, ACT_EDIT_OBJECT, ACT_EDOB_ADD_OBJECT, ACT_EDOB_DYNAMICS, ACT_EDOB_END_OBJECT, ACT_EDOB_LOCAL_ANGV, ACT_EDOB_LOCAL_LINV, ACT_EDOB_REPLACE_MESH, ACT_EDOB_REPLACE_MESH_NOGFX, ACT_EDOB_REPLACE_MESH_PHYS, ACT_EDOB_TRACK_TO, ACT_FORCE_LOCAL, ACT_GAME, ACT_GAME_LOAD, ACT_GAME_LOADCFG, ACT_GAME_QUIT, ACT_GAME_RESTART, ACT_GAME_SAVECFG, ACT_GAME_START, ACT_GROUP, ACT_IPO, ACT_IPOADD, ACT_IPOCHILD, BL_Action::ACT_IPOFLAG_ADD, BL_Action::ACT_IPOFLAG_CHILD, BL_Action::ACT_IPOFLAG_FORCE, BL_Action::ACT_IPOFLAG_LOCAL, ACT_IPOFORCE, ACT_IPOLOCAL, ACT_LAMP, ACT_LIN_VEL_LOCAL, ACT_MATERIAL, ACT_MESSAGE, ACT_OBJECT, ACT_OBJECT_SERVO, ACT_PARENT, ACT_PARENT_COMPOUND, ACT_PARENT_GHOST, ACT_PARENT_REMOVE, ACT_PARENT_SET, ACT_PROPERTY, ACT_RANDOM, ACT_RANDOM_BOOL_BERNOUILLI, ACT_RANDOM_BOOL_CONST, ACT_RANDOM_BOOL_UNIFORM, ACT_RANDOM_FLOAT_CONST, ACT_RANDOM_FLOAT_NEGATIVE_EXPONENTIAL, ACT_RANDOM_FLOAT_NORMAL, ACT_RANDOM_FLOAT_UNIFORM, ACT_RANDOM_INT_CONST, ACT_RANDOM_INT_POISSON, ACT_RANDOM_INT_UNIFORM, ACT_SCENE, ACT_SCENE_ADD_BACK, ACT_SCENE_ADD_FRONT, ACT_SCENE_CAMERA, ACT_SCENE_REMOVE, ACT_SCENE_RESTART, ACT_SCENE_RESUME, ACT_SCENE_SET, ACT_SCENE_SUSPEND, ACT_SHAPEACTION, ACT_SND_3D_SOUND, ACT_SND_LOOP_BIDIRECTIONAL_SOUND, ACT_SND_LOOP_BIDIRECTIONAL_STOP_SOUND, ACT_SND_LOOP_END_SOUND, ACT_SND_LOOP_STOP_SOUND, ACT_SND_PLAY_END_SOUND, ACT_SND_PLAY_STOP_SOUND, ACT_SOUND, ACT_STATE, ACT_STEERING, ACT_STEERING_AUTOMATICFACING, ACT_STEERING_ENABLEVISUALIZATION, ACT_STEERING_FLEE, ACT_STEERING_NORMALUP, ACT_STEERING_PATHFOLLOWING, ACT_STEERING_SEEK, ACT_STEERING_SELFTERMINATED, ACT_TORQUE_LOCAL, ACT_VISIBILITY, ACT_VISIBILITY_INVISIBLE, ACT_VISIBILITY_OCCLUSION, ACT_VISIBILITY_RECURSIVE, Object::actuators, SCA_IObject::AddActuator(), KX_LocalFlags::AddOrSetLinV, KX_LocalFlags::AngularVelocity, bObjectActuator::angularvelocity, bEditObjectActuator::angVelocity, AUD_CHANNELS_MONO, AUD_FORMAT_INVALID, AUD_RATE_INVALID, bCameraActuator::axis, BL_ConvertMesh(), bActionActuator::blendin, bMessageActuator::body, bMessageActuator::bodyType, bSceneActuator::camera, AUD_DeviceSpecs::channels, KX_3DSoundSettings::cone_inner_angle, Sound3D::cone_inner_angle, Sound3D::cone_outer_angle, KX_3DSoundSettings::cone_outer_angle, Sound3D::cone_outer_gain, KX_3DSoundSettings::cone_outer_gain, bArmatureActuator::constraint, bConstraintActuator::damp, bObjectActuator::damping, bCameraActuator::damping, bActuator::data, bSteeringActuator::dist, bRandomActuator::distribution, bObjectActuator::dloc, KX_LocalFlags::DLoc, KX_LocalFlags::DRot, bObjectActuator::drot, bEditObjectActuator::dyn_operation, bIpoActuator::end, bActionActuator::end, bActionActuator::end_reset, KDL::exp(), bSteeringActuator::facingaxis, bGameActuator::filename, KX_BlenderSceneConverter::FindGameObject(), ListBase::first, bObjectActuator::flag, bEditObjectActuator::flag, bTwoDFilterActuator::flag, bVisibilityActuator::flag, bSteeringActuator::flag, bConstraintActuator::flag, bIpoActuator::flag, bSoundActuator::flag, bActionActuator::flag, bParentActuator::flag, bTwoDFilterActuator::float_arg, bRandomActuator::float_arg_1, bRandomActuator::float_arg_2, KX_LocalFlags::Force, bObjectActuator::forceloc, bObjectActuator::forcerot, AUD_DeviceSpecs::format, bActionActuator::frameProp, bIpoActuator::frameProp, KX_GameObject::GetName(), KX_Scene::GetNetworkScene(), KX_Scene::GetObstacleSimulation(), KX_KetsjiEngine::GetRasterizer(), KX_KetsjiEngine::GetRealTime(), CIntValue::GetText(), MT_Tuple3::getValue(), bCameraActuator::height, Scene::id, Object::id, if(), bArmatureActuator::influence, bTwoDFilterActuator::int_arg, bRandomActuator::int_arg_1, bRandomActuator::int_arg_2, KX_ConstraintActuator::KX_ACT_CONSTRAINT_DIRNX, KX_ConstraintActuator::KX_ACT_CONSTRAINT_DIRNY, KX_ConstraintActuator::KX_ACT_CONSTRAINT_DIRNZ, KX_ConstraintActuator::KX_ACT_CONSTRAINT_DIRPX, KX_ConstraintActuator::KX_ACT_CONSTRAINT_DIRPY, KX_ConstraintActuator::KX_ACT_CONSTRAINT_DIRPZ, KX_ConstraintActuator::KX_ACT_CONSTRAINT_FHNX, KX_ConstraintActuator::KX_ACT_CONSTRAINT_FHNY, KX_ConstraintActuator::KX_ACT_CONSTRAINT_FHNZ, KX_ConstraintActuator::KX_ACT_CONSTRAINT_FHPX, KX_ConstraintActuator::KX_ACT_CONSTRAINT_FHPY, KX_ConstraintActuator::KX_ACT_CONSTRAINT_FHPZ, KX_ConstraintActuator::KX_ACT_CONSTRAINT_LOCX, KX_ConstraintActuator::KX_ACT_CONSTRAINT_LOCY, KX_ConstraintActuator::KX_ACT_CONSTRAINT_LOCZ, KX_ConstraintActuator::KX_ACT_CONSTRAINT_NODEF, KX_ConstraintActuator::KX_ACT_CONSTRAINT_ORIX, KX_ConstraintActuator::KX_ACT_CONSTRAINT_ORIY, KX_ConstraintActuator::KX_ACT_CONSTRAINT_ORIZ, KX_ConstraintActuator::KX_ACT_CONSTRAINT_ROTX, KX_ConstraintActuator::KX_ACT_CONSTRAINT_ROTY, KX_ConstraintActuator::KX_ACT_CONSTRAINT_ROTZ, KX_BLENDERTRUNC, KX_GameActuator::KX_GAME_LOAD, KX_GameActuator::KX_GAME_LOADCFG, KX_GameActuator::KX_GAME_NODEF, KX_GameActuator::KX_GAME_QUIT, KX_GameActuator::KX_GAME_RESTART, KX_GameActuator::KX_GAME_SAVECFG, KX_GameActuator::KX_GAME_START, KX_ParentActuator::KX_PARENT_NODEF, KX_ParentActuator::KX_PARENT_REMOVE, KX_ParentActuator::KX_PARENT_SET, SCA_RandomActuator::KX_RANDOMACT_BOOL_BERNOUILLI, SCA_RandomActuator::KX_RANDOMACT_BOOL_CONST, SCA_RandomActuator::KX_RANDOMACT_BOOL_UNIFORM, SCA_RandomActuator::KX_RANDOMACT_FLOAT_CONST, SCA_RandomActuator::KX_RANDOMACT_FLOAT_NEGATIVE_EXPONENTIAL, SCA_RandomActuator::KX_RANDOMACT_FLOAT_NORMAL, SCA_RandomActuator::KX_RANDOMACT_FLOAT_UNIFORM, SCA_RandomActuator::KX_RANDOMACT_INT_CONST, SCA_RandomActuator::KX_RANDOMACT_INT_POISSON, SCA_RandomActuator::KX_RANDOMACT_INT_UNIFORM, SCA_RandomActuator::KX_RANDOMACT_NODEF, KX_SceneActuator::KX_SCENE_ADD_BACK_SCENE, KX_SceneActuator::KX_SCENE_ADD_FRONT_SCENE, KX_SceneActuator::KX_SCENE_NODEF, KX_SceneActuator::KX_SCENE_REMOVE_SCENE, KX_SceneActuator::KX_SCENE_RESTART, KX_SceneActuator::KX_SCENE_RESUME, KX_SceneActuator::KX_SCENE_SET_CAMERA, KX_SceneActuator::KX_SCENE_SET_SCENE, KX_SceneActuator::KX_SCENE_SUSPEND, KX_SoundActuator::KX_SOUNDACT_LOOPBIDIRECTIONAL, KX_SoundActuator::KX_SOUNDACT_LOOPBIDIRECTIONAL_STOP, KX_SoundActuator::KX_SOUNDACT_LOOPEND, KX_SoundActuator::KX_SOUNDACT_LOOPSTOP, KX_SoundActuator::KX_SOUNDACT_NODEF, KX_SoundActuator::KX_SOUNDACT_PLAYEND, KX_SoundActuator::KX_SOUNDACT_PLAYSTOP, KX_SteeringActuator::KX_STEERING_FLEE, KX_SteeringActuator::KX_STEERING_NODEF, KX_SteeringActuator::KX_STEERING_PATHFOLLOWING, KX_SteeringActuator::KX_STEERING_SEEK, Object::lay, bActionActuator::layer, bActionActuator::layer_weight, bObjectActuator::linearvelocity, KX_LocalFlags::LinearVelocity, bEditObjectActuator::linVelocity, bGameActuator::loadaniname, bEditObjectActuator::localflag, M_LN2, bStateActuator::mask, bEditObjectActuator::mass, bConstraintActuator::matprop, max, bCameraActuator::max, Sound3D::max_distance, KX_3DSoundSettings::max_distance, Sound3D::max_gain, KX_3DSoundSettings::max_gain, bConstraintActuator::maxloc, bConstraintActuator::maxrot, bEditObjectActuator::me, MEM_freeN(), bCameraActuator::min, min, Sound3D::min_gain, KX_3DSoundSettings::min_gain, bConstraintActuator::minloc, bConstraintActuator::minrot, bConstraintActuator::mode, MT_2_PI(), MT_RADS_PER_DEG(), bPropertyActuator::name, bIpoActuator::name, bActuator::name, bActionActuator::name, ID::name, bSteeringActuator::navmesh, bActuator::next, NULL, bPropertyActuator::ob, bCameraActuator::ob, bParentActuator::ob, bEditObjectActuator::ob, OB_BODY_TYPE_NAVMESH, OB_MESH, bSoundActuator::pitch, bSound::playback_handle, bArmatureActuator::posechannel, bActionActuator::priority, bRandomActuator::propname, STR_String::Ptr(), RAS_2DFilterManager::RAS_2DFILTER_BLUR, RAS_2DFilterManager::RAS_2DFILTER_CUSTOMFILTER, RAS_2DFilterManager::RAS_2DFILTER_DILATION, RAS_2DFilterManager::RAS_2DFILTER_DISABLED, RAS_2DFilterManager::RAS_2DFILTER_ENABLED, RAS_2DFilterManager::RAS_2DFILTER_EROSION, RAS_2DFilterManager::RAS_2DFILTER_GRAYSCALE, RAS_2DFilterManager::RAS_2DFILTER_INVERT, RAS_2DFilterManager::RAS_2DFILTER_LAPLACIAN, RAS_2DFilterManager::RAS_2DFILTER_MOTIONBLUR, RAS_2DFilterManager::RAS_2DFILTER_NOFILTER, RAS_2DFilterManager::RAS_2DFILTER_PREWITT, RAS_2DFilterManager::RAS_2DFILTER_SEPIA, RAS_2DFilterManager::RAS_2DFILTER_SHARPEN, RAS_2DFilterManager::RAS_2DFILTER_SOBEL, AUD_DeviceSpecs::rate, bObjectActuator::reference, Sound3D::reference_distance, KX_3DSoundSettings::reference_distance, KX_BlenderSceneConverter::RegisterGameActuator(), CValue::Release(), SCA_IObject::ReserveActuator(), RNA_enum_get(), RNA_GameObjectSettings, RNA_pointer_create(), KX_3DSoundSettings::rolloff_factor, Sound3D::rolloff_factor, bConstraintActuator::rotdamp, bSceneActuator::scene, bRandomActuator::seed, KX_LocalFlags::ServoControl, SCA_ILogicBrick::SetExecutePriority(), SCA_ILogicBrick::SetName(), bSoundActuator::sound, bSoundActuator::sound3D, bActionActuator::sta, bIpoActuator::sta, bActionActuator::stridelength, bMessageActuator::subject, bArmatureActuator::subtarget, bSteeringActuator::target, bArmatureActuator::target, bTwoDFilterActuator::text, bEditObjectActuator::time, bConstraintActuator::time, bMessageActuator::toPropName, KX_LocalFlags::Torque, Object::trackflag, bSteeringActuator::turnspeed, txt_to_buf(), bEditObjectActuator::type, bSceneActuator::type, bActionActuator::type, bSoundActuator::type, bStateActuator::type, bObjectActuator::type, Object::type, bParentActuator::type, bActuator::type, bConstraintActuator::type, bGameActuator::type, bTwoDFilterActuator::type, bSteeringActuator::type, bIpoActuator::type, bPropertyActuator::type, bArmatureActuator::type, bSteeringActuator::updateTime, Object::upflag, bPropertyActuator::value, bSteeringActuator::velocity, bSoundActuator::volume, and bArmatureActuator::weight.
Referenced by BL_ConvertBlenderObjects().