Blender: drawvolume.c File Reference
drawvolume.c File Reference
3D view
#include <string.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_view3d_types.h"
#include "BLI_utildefines.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_edgehash.h"
#include "BLI_rand.h"
#include "BKE_curve.h"
#include "BKE_constraint.h"
#include "BKE_DerivedMesh.h"
#include "BKE_deform.h"
#include "BKE_displist.h"
#include "BKE_effect.h"
#include "BKE_font.h"
#include "BKE_global.h"
#include "BKE_image.h"
#include "BKE_key.h"
#include "BKE_lattice.h"
#include "BKE_mesh.h"
#include "BKE_material.h"
#include "BKE_mball.h"
#include "BKE_modifier.h"
#include "BKE_object.h"
#include "BKE_paint.h"
#include "BKE_particle.h"
#include "BKE_property.h"
#include "BKE_smoke.h"
#include "smoke_API.h"
#include "BIF_gl.h"
#include "GPU_extensions.h"
#include "ED_mesh.h"
#include "BLF_api.h"
#include "view3d_intern.h"
#include <sys/time.h>
Functions
static void tstart (void)
static void tend (void)
static int intersect_edges (float *points, float a, float b, float c, float d, float edges[12][2][3])
static int convex (float *p0, float *up, float *a, float *b)
void draw_volume (ARegion *ar, GPUTexture *tex, float *min, float *max, int res[3], float dx, GPUTexture *tex_shadow)
Variables
static struct timeval _tstart _tend
static struct timezone tz
Detailed Description
Definition in file drawvolume.c.
Function Documentation
static int convex (float * p0, float * up, float * a, float * b) [static]
Definition at line 150 of file drawvolume.c.
References cross_v3_v3v3(), dot_v3v3(), and sub_v3_v3v3().
Referenced by draw_volume().
void draw_volume (ARegion * ar, GPUTexture * tex, float * min, float * max, int res[3], float dx, GPUTexture * tex_shadow)
Definition at line 160 of file drawvolume.c.
References ABS, add_v3_v3v3(), convex(), copy_v3_v3(), dot_v3v3(), glLoadMatrixf, GPU_non_power_of_two_support(), GPU_texture_bind(), GPU_texture_unbind(), i, intersect_edges(), MEM_callocN(), MEM_freeN(), mul_v3_fl(), normalize_v3(), NULL, power_of_2_max_i(), ARegion::regiondata, size(), strlen(), sub_v3_v3v3(), tend(), tstart(), RegionView3D::viewinv, and RegionView3D::viewmat.
Referenced by draw_object().
static int intersect_edges (float * points, float a, float b, float c, float d, float edges[12][2][3]) [static]
Definition at line 131 of file drawvolume.c.
References i.
Referenced by draw_volume().
static void tend (void) [static]
Definition at line 114 of file drawvolume.c.
References _tend, and tz.
static void tstart (void) [static]
Definition at line 110 of file drawvolume.c.
References tz.
Variable Documentation
struct timeval _tstart _tend [static]
Definition at line 108 of file drawvolume.c.
Referenced by tend().
struct timezone tz [static]
Definition at line 109 of file drawvolume.c.
Referenced by tend(), and tstart().