Blender: btGEN_Link Class Reference
btGEN_Link Class Reference
#include <btList.h>
Public Member Functions
btGEN_Link ()
btGEN_Link (btGEN_Link *next, btGEN_Link *prev)
btGEN_Link * getNext () const
btGEN_Link * getPrev () const
bool isHead () const
bool isTail () const
void insertBefore (btGEN_Link *link)
void insertAfter (btGEN_Link *link)
void remove ()
Detailed Description
Definition at line 20 of file btList.h.
Constructor & Destructor Documentation
btGEN_Link::btGEN_Link () [inline]
Definition at line 22 of file btList.h.
btGEN_Link::btGEN_Link (btGEN_Link * next, btGEN_Link * prev) [inline]
Definition at line 23 of file btList.h.
Member Function Documentation
btGEN_Link* btGEN_Link::getNext () const [inline]
Definition at line 25 of file btList.h.
Referenced by btGEN_List::getHead().
btGEN_Link* btGEN_Link::getPrev () const [inline]
Definition at line 26 of file btList.h.
Referenced by btGEN_List::getTail().
void btGEN_Link::insertAfter (btGEN_Link * link) [inline]
Definition at line 38 of file btList.h.
References link().
Referenced by btGEN_List::addHead().
void btGEN_Link::insertBefore (btGEN_Link * link) [inline]
Definition at line 31 of file btList.h.
References link().
Referenced by btGEN_List::addTail().
bool btGEN_Link::isHead () const [inline]
Definition at line 28 of file btList.h.
bool btGEN_Link::isTail () const [inline]
Definition at line 29 of file btList.h.
void btGEN_Link::remove () [inline]
Definition at line 45 of file btList.h.
The documentation for this class was generated from the following file:
btList.h