Blender: TNT::Fortran_Array3D< T > Class Template Reference
TNT::Fortran_Array3D< T > Class Template Reference
#include <tnt_fortran_array3d.h>
Public Types
typedef T value_type
Public Member Functions
Fortran_Array3D ()
Fortran_Array3D (int m, int n, int k)
Fortran_Array3D (int m, int n, int k, T *a)
Fortran_Array3D (int m, int n, int k, const T &a)
Fortran_Array3D (const Fortran_Array3D &A)
Fortran_Array3D & operator= (const T &a)
Fortran_Array3D & operator= (const Fortran_Array3D &A)
Fortran_Array3D & ref (const Fortran_Array3D &A)
Fortran_Array3D copy () const
Fortran_Array3D & inject (const Fortran_Array3D &A)
T & operator() (int i, int j, int k)
const T & operator() (int i, int j, int k) const
int dim1 () const
int dim2 () const
int dim3 () const
int ref_count () const
~Fortran_Array3D ()
Detailed Description
template<class T>
class TNT::Fortran_Array3D< T >
Definition at line 39 of file tnt_fortran_array3d.h.
Member Typedef Documentation
template<class T> typedef T TNT::Fortran_Array3D< T >::value_type
Definition at line 54 of file tnt_fortran_array3d.h.
Constructor & Destructor Documentation
template<class T > TNT::Fortran_Array3D< T >::Fortran_Array3D ()
Definition at line 78 of file tnt_fortran_array3d.h.
template<class T > TNT::Fortran_Array3D< T >::Fortran_Array3D (int m, int n, int k)
Definition at line 88 of file tnt_fortran_array3d.h.
template<class T > TNT::Fortran_Array3D< T >::Fortran_Array3D (int m, int n, int k, T * a)
Definition at line 102 of file tnt_fortran_array3d.h.
template<class T > TNT::Fortran_Array3D< T >::Fortran_Array3D (int m, int n, int k, const T & a)
Definition at line 94 of file tnt_fortran_array3d.h.
References p, and T.
template<class T > TNT::Fortran_Array3D< T >::Fortran_Array3D (const Fortran_Array3D< T > & A) [inline]
Definition at line 82 of file tnt_fortran_array3d.h.
template<class T > TNT::Fortran_Array3D< T >::~Fortran_Array3D ()
Definition at line 217 of file tnt_fortran_array3d.h.
Member Function Documentation
template<class T > Fortran_Array3D< T > TNT::Fortran_Array3D< T >::copy () const
Definition at line 152 of file tnt_fortran_array3d.h.
References B, and TNT::Fortran_Array3D< T >::inject().
template<class T > int TNT::Fortran_Array3D< T >::dim1 () const [inline]
Definition at line 201 of file tnt_fortran_array3d.h.
Referenced by TNT::operator*(), TNT::operator*=(), TNT::operator+(), TNT::operator+=(), TNT::operator-(), TNT::operator-=(), TNT::operator/(), and TNT::operator/=().
template<class T > int TNT::Fortran_Array3D< T >::dim2 () const [inline]
Definition at line 204 of file tnt_fortran_array3d.h.
Referenced by TNT::operator*(), TNT::operator*=(), TNT::operator+(), TNT::operator+=(), TNT::operator-(), TNT::operator-=(), TNT::operator/(), and TNT::operator/=().
template<class T > int TNT::Fortran_Array3D< T >::dim3 () const [inline]
Definition at line 207 of file tnt_fortran_array3d.h.
Referenced by TNT::operator*(), TNT::operator*=(), TNT::operator+(), TNT::operator+=(), TNT::operator-(), TNT::operator-=(), TNT::operator/(), and TNT::operator/=().
template<class T > Fortran_Array3D< T > & TNT::Fortran_Array3D< T >::inject (const Fortran_Array3D< T > & A)
Definition at line 163 of file tnt_fortran_array3d.h.
References p, and T.
Referenced by TNT::Fortran_Array3D< T >::copy().
template<class T > const T & TNT::Fortran_Array3D< T >::operator() (int i, int j, int k) const [inline]
Definition at line 125 of file tnt_fortran_array3d.h.
References assert.
template<class T > T & TNT::Fortran_Array3D< T >::operator() (int i, int j, int k) [inline]
Definition at line 109 of file tnt_fortran_array3d.h.
References assert.
template<class T > Fortran_Array3D< T > & TNT::Fortran_Array3D< T >::operator= (const T & a) [inline]
Definition at line 141 of file tnt_fortran_array3d.h.
References p, and T.
template<class T > Fortran_Array3D< T > & TNT::Fortran_Array3D< T >::operator= (const Fortran_Array3D< T > & A) [inline]
Definition at line 195 of file tnt_fortran_array3d.h.
template<class T > Fortran_Array3D< T > & TNT::Fortran_Array3D< T >::ref (const Fortran_Array3D< T > & A) [inline]
Definition at line 180 of file tnt_fortran_array3d.h.
template<class T > int TNT::Fortran_Array3D< T >::ref_count () const [inline]
Definition at line 211 of file tnt_fortran_array3d.h.
The documentation for this class was generated from the following file:
tnt_fortran_array3d.h