Blender: MT_CmMatrix4x4 Class Reference
MT_CmMatrix4x4 Class Reference
#include <MT_CmMatrix4x4.h>
Public Member Functions
MT_CmMatrix4x4 (const float value[4][4])
MT_CmMatrix4x4 ()
MT_CmMatrix4x4 (const double value[16])
MT_CmMatrix4x4 (const MT_CmMatrix4x4 &other)
MT_CmMatrix4x4 (const MT_Point3 &orig, const MT_Vector3 &dir, const MT_Vector3 up)
void Identity ()
void SetMatrix (const MT_CmMatrix4x4 &other)
double * getPointer ()
const double * getPointer () const
void setElem (int pos, double newvalue)
MT_Vector3 GetRight () const
MT_Vector3 GetUp () const
MT_Vector3 GetDir () const
MT_Point3 GetPos () const
void SetPos (const MT_Vector3 &v)
double & operator() (int row, int col)
Static Public Member Functions
static MT_CmMatrix4x4 Perspective (MT_Scalar inLeft, MT_Scalar inRight, MT_Scalar inBottom, MT_Scalar inTop, MT_Scalar inNear, MT_Scalar inFar)
Protected Attributes
union {
double m_V [4][4]
double m_Vflat [16]
};
Detailed Description
Definition at line 52 of file MT_CmMatrix4x4.h.
Constructor & Destructor Documentation
MT_CmMatrix4x4::MT_CmMatrix4x4 (const float value[4][4])
Definition at line 45 of file MT_CmMatrix4x4.cpp.
References i, and m_V.
MT_CmMatrix4x4::MT_CmMatrix4x4 ()
Definition at line 38 of file MT_CmMatrix4x4.cpp.
References Identity().
MT_CmMatrix4x4::MT_CmMatrix4x4 (const double value[16])
Definition at line 56 of file MT_CmMatrix4x4.cpp.
References i, and m_Vflat.
MT_CmMatrix4x4::MT_CmMatrix4x4 (const MT_CmMatrix4x4 & other)
Definition at line 64 of file MT_CmMatrix4x4.cpp.
References SetMatrix().
MT_CmMatrix4x4::MT_CmMatrix4x4 (const MT_Point3 & orig, const MT_Vector3 & dir, const MT_Vector3 up)
Definition at line 71 of file MT_CmMatrix4x4.cpp.
References MT_Vector3::cross(), m_V, MT_Vector3::normalized(), MT_Tuple3::x(), MT_Tuple3::y(), and MT_Tuple3::z().
Member Function Documentation
MT_Vector3 MT_CmMatrix4x4::GetDir () const
Definition at line 118 of file MT_CmMatrix4x4.cpp.
References m_V.
double * MT_CmMatrix4x4::getPointer ()
Definition at line 151 of file MT_CmMatrix4x4.cpp.
References m_V.
Referenced by KX_GameObject::AddMeshUser(), KX_GameObject::GetOpenGLMatrix(), KX_KetsjiEngine::PostProcessScene(), DbvtCullingCallback::Process(), and KX_LightObject::Update().
const double * MT_CmMatrix4x4::getPointer () const
Definition at line 158 of file MT_CmMatrix4x4.cpp.
References m_V.
MT_Point3 MT_CmMatrix4x4::GetPos () const
Definition at line 125 of file MT_CmMatrix4x4.cpp.
References m_V.
MT_Vector3 MT_CmMatrix4x4::GetRight () const
Definition at line 104 of file MT_CmMatrix4x4.cpp.
References m_V.
MT_Vector3 MT_CmMatrix4x4::GetUp () const
Definition at line 111 of file MT_CmMatrix4x4.cpp.
References m_V.
void MT_CmMatrix4x4::Identity ()
Definition at line 132 of file MT_CmMatrix4x4.cpp.
References i, and m_V.
Referenced by MT_CmMatrix4x4().
double& MT_CmMatrix4x4::operator() (int row, int col) [inline]
Definition at line 126 of file MT_CmMatrix4x4.h.
References m_V.
MT_CmMatrix4x4 MT_CmMatrix4x4::Perspective (MT_Scalar inLeft, MT_Scalar inRight, MT_Scalar inBottom, MT_Scalar inTop, MT_Scalar inNear, MT_Scalar inFar) [static]
Definition at line 170 of file MT_CmMatrix4x4.cpp.
void MT_CmMatrix4x4::setElem (int pos, double newvalue)
Definition at line 165 of file MT_CmMatrix4x4.cpp.
References m_Vflat.
void MT_CmMatrix4x4::SetMatrix (const MT_CmMatrix4x4 & other)
Definition at line 143 of file MT_CmMatrix4x4.cpp.
References i, and m_Vflat.
Referenced by MT_CmMatrix4x4().
void MT_CmMatrix4x4::SetPos (const MT_Vector3 & v)
Member Data Documentation
union { ... } [protected]
double MT_CmMatrix4x4::m_V[4][4]
Definition at line 142 of file MT_CmMatrix4x4.h.
Referenced by GetDir(), getPointer(), GetPos(), GetRight(), GetUp(), Identity(), MT_CmMatrix4x4(), and operator()().
double MT_CmMatrix4x4::m_Vflat[16]
Definition at line 143 of file MT_CmMatrix4x4.h.
Referenced by MT_CmMatrix4x4(), setElem(), and SetMatrix().
The documentation for this class was generated from the following files:
MT_CmMatrix4x4.h
MT_CmMatrix4x4.cpp