Blender: util_view.cpp File Reference
util_view.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "util_opengl.h"
#include "util_time.h"
#include "util_view.h"
#include <GL/glut.h>
Classes
struct View
Functions
static void view_display_text (int x, int y, const char *text)
void view_display_info (const char *info)
static void view_display ()
static void view_reshape (int width, int height)
static void view_keyboard (unsigned char key, int x, int y)
void view_idle ()
void view_main_loop (const char *title, int width, int height, ViewInitFunc initf, ViewExitFunc exitf, ViewResizeFunc resize, ViewDisplayFunc display, ViewKeyboardFunc keyboard)
void view_redraw ()
Variables
CCL_NAMESPACE_BEGIN struct View V
Function Documentation
static void view_display () [static]
Definition at line 79 of file util_view.cpp.
References View::display, View::exitf, View::first_display, View::height, View::initf, V, and View::width.
Referenced by view_main_loop().
void view_display_info (const char * info)
Definition at line 62 of file util_view.cpp.
References View::height, V, view_display_text(), and View::width.
Referenced by display_info().
static void view_display_text (int x, int y, const char * text) [static]
Definition at line 52 of file util_view.cpp.
Referenced by view_display_info().
void view_idle ()
Definition at line 139 of file util_view.cpp.
References View::redraw, time_sleep(), and V.
Referenced by view_main_loop().
static void view_keyboard (unsigned char key, int x, int y) [static]
Definition at line 126 of file util_view.cpp.
References View::exitf, View::keyboard, and V.
Referenced by view_main_loop().
void view_main_loop (const char * title, int width, int height, ViewInitFunc initf, ViewExitFunc exitf, ViewResizeFunc resize, ViewDisplayFunc display, ViewKeyboardFunc keyboard)
Definition at line 149 of file util_view.cpp.
References display(), View::display, View::exitf, View::first_display, View::height, View::initf, initf, keyboard(), View::keyboard, View::redraw, View::resize, resize(), V, view_display(), view_idle(), view_keyboard(), view_reshape(), and View::width.
Referenced by main().
void view_redraw ()
Definition at line 189 of file util_view.cpp.
References View::redraw, and V.
Referenced by session_init().
static void view_reshape (int width, int height) [static]
Definition at line 106 of file util_view.cpp.
References View::height, View::resize, V, and View::width.
Referenced by view_main_loop().
Variable Documentation
CCL_NAMESPACE_BEGIN struct View V
Referenced by JAMA::Eigenvalue< Real >::Eigenvalue(), GregoryTrianglePatch::eval(), GregoryQuadPatch::eval(), ewa_eval(), KDL::Frame::Frame(), KDL::Frame2::Frame2(), JAMA::Eigenvalue< Real >::getV(), pseudoinverse_m4_m4(), KDL::svd_eigen_HH(), view_display(), view_display_info(), view_idle(), view_keyboard(), view_main_loop(), view_redraw(), and view_reshape().