Blender: editaction_gpencil.c File Reference
editaction_gpencil.c File Reference
gpencil
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stddef.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "DNA_gpencil_types.h"
#include "DNA_scene_types.h"
#include "BKE_fcurve.h"
#include "BKE_gpencil.h"
#include "ED_anim_api.h"
#include "ED_gpencil.h"
#include "ED_keyframes_edit.h"
#include "gpencil_intern.h"
Functions
short gplayer_frames_looper (bGPDlayer *gpl, Scene *scene, short(*gpf_cb)(bGPDframe *, Scene *))
void gplayer_make_cfra_list (bGPDlayer *gpl, ListBase *elems, short onlysel)
short is_gplayer_frame_selected (bGPDlayer *gpl)
static void gpframe_select (bGPDframe *gpf, short select_mode)
void select_gpencil_frames (bGPDlayer *gpl, short select_mode)
void set_gplayer_frame_selection (bGPDlayer *gpl, short mode)
void select_gpencil_frame (bGPDlayer *gpl, int selx, short select_mode)
void borderselect_gplayer_frames (bGPDlayer *gpl, float min, float max, short select_mode)
void delete_gplayer_frames (bGPDlayer *gpl)
void duplicate_gplayer_frames (bGPDlayer *gpl)
Detailed Description
Definition in file editaction_gpencil.c.
Function Documentation
void borderselect_gplayer_frames (bGPDlayer * gpl, float min, float max, short select_mode)
Definition at line 196 of file editaction_gpencil.c.
References ListBase::first, bGPDframe::framenum, bGPDlayer::frames, gpframe_select(), IN_RANGE, bGPDframe::next, and NULL.
Referenced by actkeys_select_leftright(), borderselect_action(), and markers_selectkeys_between().
void delete_gplayer_frames (bGPDlayer * gpl)
Definition at line 214 of file editaction_gpencil.c.
References ListBase::first, bGPDframe::flag, bGPDlayer::frames, GP_FRAME_SELECT, gpencil_layer_delframe(), bGPDframe::next, and NULL.
Referenced by delete_action_keys().
void duplicate_gplayer_frames (bGPDlayer * gpl)
Definition at line 232 of file editaction_gpencil.c.
References BLI_insertlinkafter(), ListBase::first, bGPDframe::flag, bGPDlayer::frames, GP_FRAME_SELECT, gpencil_frame_duplicate(), bGPDframe::next, and NULL.
Referenced by duplicate_action_keys().
static void gpframe_select (bGPDframe * gpf, short select_mode) [static]
Definition at line 133 of file editaction_gpencil.c.
References bGPDframe::flag, GP_FRAME_SELECT, NULL, SELECT_ADD, SELECT_INVERT, and SELECT_SUBTRACT.
Referenced by borderselect_gplayer_frames(), select_gpencil_frame(), and select_gpencil_frames().
short gplayer_frames_looper (bGPDlayer * gpl, Scene * scene, short(*)(bGPDframe *, Scene *) gpf_cb)
Definition at line 65 of file editaction_gpencil.c.
References ListBase::first, bGPDlayer::frames, bGPDframe::next, and NULL.
void gplayer_make_cfra_list (bGPDlayer * gpl, ListBase * elems, short onlysel)
Definition at line 88 of file editaction_gpencil.c.
References BLI_addtail(), CfraElem::cfra, ELEM, ListBase::first, bGPDframe::flag, bGPDframe::framenum, bGPDlayer::frames, GP_FRAME_SELECT, MEM_callocN(), bGPDframe::next, NULL, and CfraElem::sel.
Referenced by columnselect_action_keys().
short is_gplayer_frame_selected (bGPDlayer * gpl)
Definition at line 114 of file editaction_gpencil.c.
References ListBase::first, bGPDframe::flag, bGPDlayer::frames, GP_FRAME_SELECT, bGPDframe::next, and NULL.
Referenced by deselect_action_keys().
void select_gpencil_frame (bGPDlayer * gpl, int selx, short select_mode)
Definition at line 178 of file editaction_gpencil.c.
References ListBase::first, bGPDframe::framenum, bGPDlayer::frames, gpframe_select(), bGPDframe::next, and NULL.
Referenced by actkeys_mselect_column(), actkeys_mselect_single(), and columnselect_action_keys().
void select_gpencil_frames (bGPDlayer * gpl, short select_mode)
Definition at line 152 of file editaction_gpencil.c.
References ListBase::first, bGPDlayer::frames, gpframe_select(), bGPDframe::next, and NULL.
Referenced by set_gplayer_frame_selection().
void set_gplayer_frame_selection (bGPDlayer * gpl, short mode)
Definition at line 167 of file editaction_gpencil.c.
References NULL, and select_gpencil_frames().
Referenced by deselect_action_keys().