Blender: RAS_Polygon Class Reference
RAS_Polygon Class Reference
#include <RAS_Polygon.h>
Public Types
enum { VISIBLE = 1, COLLIDER = 2, TWOSIDE = 4 }
Public Member Functions
RAS_Polygon (RAS_MaterialBucket *bucket, RAS_DisplayArray *darray, int numvert)
virtual ~RAS_Polygon ()
int VertexCount ()
RAS_TexVert * GetVertex (int i)
void SetVertexOffset (int i, unsigned short offset)
int GetVertexOffset (int i)
int GetVertexOffsetAbs (RAS_MeshObject *mesh, int i)
bool IsVisible ()
void SetVisible (bool visible)
bool IsCollider ()
void SetCollider (bool collider)
bool IsTwoside ()
void SetTwoside (bool twoside)
RAS_MaterialBucket * GetMaterial ()
RAS_DisplayArray * GetDisplayArray ()
Detailed Description
Definition at line 47 of file RAS_Polygon.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
VISIBLE
COLLIDER
TWOSIDE
Definition at line 64 of file RAS_Polygon.h.
Constructor & Destructor Documentation
RAS_Polygon::RAS_Polygon (RAS_MaterialBucket * bucket, RAS_DisplayArray * darray, int numvert)
Definition at line 40 of file RAS_Polygon.cpp.
virtual RAS_Polygon::~RAS_Polygon () [inline, virtual]
Definition at line 71 of file RAS_Polygon.h.
Member Function Documentation
RAS_DisplayArray * RAS_Polygon::GetDisplayArray ()
Definition at line 135 of file RAS_Polygon.cpp.
Referenced by GetVertexOffsetAbs().
RAS_MaterialBucket * RAS_Polygon::GetMaterial ()
Definition at line 130 of file RAS_Polygon.cpp.
Referenced by RAS_MeshObject::AddVertex(), and ImageRender::ImageRender().
RAS_TexVert * RAS_Polygon::GetVertex (int i)
Definition at line 61 of file RAS_Polygon.cpp.
References i, and RAS_DisplayArray::m_vertex.
Referenced by KX_NavMeshObject::BuildVertIndArrays(), ImageRender::ImageRender(), DbvtCullingCallback::Process(), and CcdShapeConstructionInfo::UpdateMesh().
int RAS_Polygon::GetVertexOffset (int i)
Definition at line 66 of file RAS_Polygon.cpp.
References i.
int RAS_Polygon::GetVertexOffsetAbs (RAS_MeshObject * mesh, int i)
Definition at line 71 of file RAS_Polygon.cpp.
References GetDisplayArray(), RAS_MeshObject::GetPolygon(), i, and RAS_DisplayArray::m_vertex.
bool RAS_Polygon::IsCollider ()
Definition at line 108 of file RAS_Polygon.cpp.
References COLLIDER.
Referenced by CcdShapeConstructionInfo::SetMesh(), and CcdShapeConstructionInfo::UpdateMesh().
bool RAS_Polygon::IsTwoside ()
Definition at line 119 of file RAS_Polygon.cpp.
References TWOSIDE.
Referenced by DbvtCullingCallback::Process().
bool RAS_Polygon::IsVisible ()
Definition at line 97 of file RAS_Polygon.cpp.
References VISIBLE.
Referenced by RAS_MeshObject::AddVertex().
void RAS_Polygon::SetCollider (bool collider)
Definition at line 113 of file RAS_Polygon.cpp.
References COLLIDER.
Referenced by BL_ConvertMesh().
void RAS_Polygon::SetTwoside (bool twoside)
Definition at line 124 of file RAS_Polygon.cpp.
References TWOSIDE.
Referenced by BL_ConvertMesh().
void RAS_Polygon::SetVertexOffset (int i, unsigned short offset)
Definition at line 56 of file RAS_Polygon.cpp.
References i.
Referenced by RAS_MeshObject::AddVertex().
void RAS_Polygon::SetVisible (bool visible)
Definition at line 102 of file RAS_Polygon.cpp.
References VISIBLE.
Referenced by BL_ConvertMesh().
int RAS_Polygon::VertexCount ()
Definition at line 51 of file RAS_Polygon.cpp.
Referenced by KX_NavMeshObject::BuildVertIndArrays(), ImageRender::ImageRender(), DbvtCullingCallback::Process(), and CcdShapeConstructionInfo::UpdateMesh().
The documentation for this class was generated from the following files:
RAS_Polygon.h
RAS_Polygon.cpp