Blender: btGImpactMassUtil.h File Reference
btGImpactMassUtil.h File Reference
#include "LinearMath/btTransform.h"
Functions
SIMD_FORCE_INLINE btVector3 gim_inertia_add_transformed (const btVector3 &source_inertia, const btVector3 &added_inertia, const btTransform &transform)
SIMD_FORCE_INLINE btVector3 gim_get_point_inertia (const btVector3 &point, btScalar mass)
Detailed Description
Author:
Francisco Leon Najera
Definition in file btGImpactMassUtil.h.
Function Documentation
SIMD_FORCE_INLINE btVector3 gim_get_point_inertia (const btVector3 & point, btScalar mass)
Definition at line 51 of file btGImpactMassUtil.h.
Referenced by btGImpactMeshShapePart::calculateLocalInertia().
SIMD_FORCE_INLINE btVector3 gim_inertia_add_transformed (const btVector3 & source_inertia, const btVector3 & added_inertia, const btTransform & transform)
Definition at line 32 of file btGImpactMassUtil.h.
References btTransform::getBasis(), btTransform::getOrigin(), btMatrix3x3::scaled(), and btMatrix3x3::transpose().
Referenced by btGImpactCompoundShape::calculateLocalInertia().