Blender: SG_Tree Class Reference
SG_Tree Class Reference
#include <SG_Tree.h>
Classes
struct greater
Public Member Functions
SG_Tree ()
SG_Tree (SG_Tree *left, SG_Tree *right)
SG_Tree (SG_Node *client)
~SG_Tree ()
MT_Scalar volume () const
void dump () const
SG_Tree * Left () const
SG_Tree * Right () const
SG_Node * Client () const
SG_Tree * Find (SG_Node *node)
void get (MT_Point3 *box) const
const SG_BBox & BBox () const
bool inside (const MT_Point3 &point) const
void SetLeft (SG_Tree *left)
void SetRight (SG_Tree *right)
MT_Point3 Center () const
MT_Scalar Radius ()
Detailed Description
SG_Tree. Holds a binary tree of SG_Nodes.
Definition at line 47 of file SG_Tree.h.
Constructor & Destructor Documentation
SG_Tree::SG_Tree ()
Definition at line 40 of file SG_Tree.cpp.
SG_Tree::SG_Tree (SG_Tree * left, SG_Tree * right)
Definition at line 44 of file SG_Tree.cpp.
References length().
SG_Tree::SG_Tree (SG_Node * client)
Definition at line 63 of file SG_Tree.cpp.
References SG_Spatial::BBox(), SG_Spatial::GetWorldTransform(), and length().
SG_Tree::~SG_Tree ()
Definition at line 73 of file SG_Tree.cpp.
Member Function Documentation
const SG_BBox & SG_Tree::BBox () const
Get the tree node's bounding box.
Definition at line 149 of file SG_Tree.cpp.
Referenced by SG_TreeFactory::MakeTreeDown().
MT_Point3 SG_Tree::Center () const [inline]
Definition at line 102 of file SG_Tree.h.
Referenced by KX_Scene::MarkVisible().
SG_Node * SG_Tree::Client () const
Definition at line 104 of file SG_Tree.cpp.
Referenced by KX_Scene::MarkSubTreeVisible(), and KX_Scene::MarkVisible().
void SG_Tree::dump () const
Prints the tree (for debugging.)
Definition at line 82 of file SG_Tree.cpp.
References dump().
Referenced by dump().
SG_Tree * SG_Tree::Find (SG_Node * node)
Definition at line 109 of file SG_Tree.cpp.
References SG_Spatial::BBox(), Find(), left(), NULL, and swap().
Referenced by Find().
void SG_Tree::get (MT_Point3 * box) const
Definition at line 137 of file SG_Tree.cpp.
References SG_BBox::get(), and MT_Transform::setIdentity().
Referenced by KX_Scene::MarkVisible().
bool SG_Tree::inside (const MT_Point3 & point) const
Test if the given bounding box is inside this bounding box.
Definition at line 144 of file SG_Tree.cpp.
References SG_BBox::inside().
Referenced by KX_Scene::MarkVisible().
SG_Tree * SG_Tree::Left () const
Returns the left node.
Definition at line 94 of file SG_Tree.cpp.
Referenced by KX_Scene::MarkSubTreeVisible(), and KX_Scene::MarkVisible().
MT_Scalar SG_Tree::Radius () [inline]
Definition at line 103 of file SG_Tree.h.
Referenced by KX_Scene::MarkVisible().
SG_Tree * SG_Tree::Right () const
Definition at line 99 of file SG_Tree.cpp.
Referenced by KX_Scene::MarkSubTreeVisible(), and KX_Scene::MarkVisible().
void SG_Tree::SetLeft (SG_Tree * left)
Definition at line 154 of file SG_Tree.cpp.
References left(), and length().
Referenced by SG_TreeFactory::MakeTreeDown().
void SG_Tree::SetRight (SG_Tree * right)
Definition at line 162 of file SG_Tree.cpp.
References length().
Referenced by SG_TreeFactory::MakeTreeDown().
MT_Scalar SG_Tree::volume () const
Computes the volume of the bounding box.
Definition at line 77 of file SG_Tree.cpp.
References SG_BBox::volume().
Referenced by SG_Tree::greater::operator()().
The documentation for this class was generated from the following files:
SG_Tree.h
SG_Tree.cpp