Blender: rna_animation_api.c File Reference
rna_animation_api.c File Reference
RNA
#include <stdlib.h>
#include <stdio.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "DNA_anim_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
Functions
void RNA_api_keyingset (StructRNA *srna)
Detailed Description
Definition in file rna_animation_api.c.
Function Documentation
void RNA_api_keyingset (StructRNA * srna)
Definition at line 70 of file rna_animation_api.c.
References FUNC_USE_CONTEXT, FUNC_USE_REPORTS, RNA_def_function(), RNA_def_function_flag(), and RNA_def_function_ui_description().
Referenced by rna_def_keyingset().