Blender: sequencer_scopes.c File Reference
sequencer_scopes.c File Reference
sequencer
#include <math.h>
#include <string.h>
#include "BLI_math_color.h"
#include "BLI_utildefines.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "sequencer_intern.h"
Functions
static void rgb_to_yuv_normalized (const float rgb[3], float yuv[3])
static void scope_put_pixel (unsigned char *table, unsigned char *pos)
static void scope_put_pixel_single (unsigned char *table, unsigned char *pos, int col)
static void wform_put_line (int w, unsigned char *last_pos, unsigned char *new_pos)
static void wform_put_line_single (int w, unsigned char *last_pos, unsigned char *new_pos, int col)
static void wform_put_border (unsigned char *tgt, int w, int h)
static void wform_put_gridrow (unsigned char *tgt, float perc, int w, int h)
static void wform_put_grid (unsigned char *tgt, int w, int h)
static ImBuf * make_waveform_view_from_ibuf_byte (ImBuf *ibuf)
static ImBuf * make_waveform_view_from_ibuf_float (ImBuf *ibuf)
ImBuf * make_waveform_view_from_ibuf (ImBuf *ibuf)
static ImBuf * make_sep_waveform_view_from_ibuf_byte (ImBuf *ibuf)
static ImBuf * make_sep_waveform_view_from_ibuf_float (ImBuf *ibuf)
ImBuf * make_sep_waveform_view_from_ibuf (ImBuf *ibuf)
static void draw_zebra_byte (ImBuf *src, ImBuf *ibuf, float perc)
static void draw_zebra_float (ImBuf *src, ImBuf *ibuf, float perc)
ImBuf * make_zebra_view_from_ibuf (ImBuf *src, float perc)
static void draw_histogram_marker (ImBuf *ibuf, int x)
static void draw_histogram_bar (ImBuf *ibuf, int x, float val, int col)
static ImBuf * make_histogram_view_from_ibuf_byte (ImBuf *ibuf)
static int get_bin_float (float f)
static ImBuf * make_histogram_view_from_ibuf_float (ImBuf *ibuf)
ImBuf * make_histogram_view_from_ibuf (ImBuf *ibuf)
static void vectorscope_put_cross (unsigned char r, unsigned char g, unsigned char b, char *tgt, int w, int h, int size)
static ImBuf * make_vectorscope_view_from_ibuf_byte (ImBuf *ibuf)
static ImBuf * make_vectorscope_view_from_ibuf_float (ImBuf *ibuf)
ImBuf * make_vectorscope_view_from_ibuf (ImBuf *ibuf)
Detailed Description
Definition in file sequencer_scopes.c.
Function Documentation
static void draw_histogram_bar (ImBuf * ibuf, int x, float val, int col) [static]
Definition at line 450 of file sequencer_scopes.c.
References i, p, ImBuf::rect, ImBuf::x, and ImBuf::y.
Referenced by make_histogram_view_from_ibuf_byte(), and make_histogram_view_from_ibuf_float().
static void draw_histogram_marker (ImBuf * ibuf, int x) [static]
Definition at line 436 of file sequencer_scopes.c.
References i, p, ImBuf::rect, ImBuf::x, and ImBuf::y.
Referenced by make_histogram_view_from_ibuf_float().
static void draw_zebra_byte (ImBuf * src, ImBuf * ibuf, float perc) [static]
Definition at line 361 of file sequencer_scopes.c.
References g, p, ImBuf::rect, ImBuf::x, and ImBuf::y.
Referenced by make_zebra_view_from_ibuf().
static void draw_zebra_float (ImBuf * src, ImBuf * ibuf, float perc) [static]
Definition at line 392 of file sequencer_scopes.c.
References FTOCHAR, g, p, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by make_zebra_view_from_ibuf().
static int get_bin_float (float f) [static]
Definition at line 507 of file sequencer_scopes.c.
ImBuf* make_histogram_view_from_ibuf (ImBuf * ibuf) [read]
Definition at line 560 of file sequencer_scopes.c.
References make_histogram_view_from_ibuf_byte(), make_histogram_view_from_ibuf_float(), and ImBuf::rect_float.
Referenced by draw_image_seq().
static ImBuf* make_histogram_view_from_ibuf_byte (ImBuf * ibuf) [static]
Definition at line 464 of file sequencer_scopes.c.
References draw_histogram_bar(), IB_rect, IMB_allocImBuf(), ImBuf::rect, wform_put_border(), ImBuf::x, and ImBuf::y.
Referenced by make_histogram_view_from_ibuf().
static ImBuf* make_histogram_view_from_ibuf_float (ImBuf * ibuf) [static]
Definition at line 519 of file sequencer_scopes.c.
References draw_histogram_bar(), draw_histogram_marker(), get_bin_float(), IB_rect, IMB_allocImBuf(), ImBuf::rect, ImBuf::rect_float, wform_put_border(), ImBuf::x, and ImBuf::y.
Referenced by make_histogram_view_from_ibuf().
ImBuf* make_sep_waveform_view_from_ibuf (ImBuf * ibuf) [read]
Definition at line 351 of file sequencer_scopes.c.
References make_sep_waveform_view_from_ibuf_byte(), make_sep_waveform_view_from_ibuf_float(), and ImBuf::rect_float.
Referenced by draw_image_seq().
static ImBuf* make_sep_waveform_view_from_ibuf_byte (ImBuf * ibuf) [static]
Definition at line 250 of file sequencer_scopes.c.
References IB_rect, IMB_allocImBuf(), NULL, p, pow(), ImBuf::rect, scope_put_pixel_single(), wform_put_border(), wform_put_grid(), wform_put_line_single(), ImBuf::x, and ImBuf::y.
Referenced by make_sep_waveform_view_from_ibuf().
static ImBuf* make_sep_waveform_view_from_ibuf_float (ImBuf * ibuf) [static]
Definition at line 299 of file sequencer_scopes.c.
References CLAMP(), IB_rect, IMB_allocImBuf(), NULL, p, pow(), ImBuf::rect, ImBuf::rect_float, scope_put_pixel_single(), wform_put_border(), wform_put_grid(), wform_put_line_single(), ImBuf::x, and ImBuf::y.
Referenced by make_sep_waveform_view_from_ibuf().
ImBuf* make_vectorscope_view_from_ibuf (ImBuf * ibuf) [read]
Definition at line 696 of file sequencer_scopes.c.
References make_vectorscope_view_from_ibuf_byte(), make_vectorscope_view_from_ibuf_float(), and ImBuf::rect_float.
Referenced by draw_image_seq().
static ImBuf* make_vectorscope_view_from_ibuf_byte (ImBuf * ibuf) [static]
Definition at line 599 of file sequencer_scopes.c.
References IB_rect, IMB_allocImBuf(), p, pow(), ImBuf::rect, rgb_to_yuv_normalized(), scope_put_pixel(), vectorscope_put_cross(), ImBuf::x, and ImBuf::y.
Referenced by make_vectorscope_view_from_ibuf().
static ImBuf* make_vectorscope_view_from_ibuf_float (ImBuf * ibuf) [static]
Definition at line 646 of file sequencer_scopes.c.
References CLAMP(), IB_rect, IMB_allocImBuf(), p, pow(), ImBuf::rect, ImBuf::rect_float, rgb_to_yuv_normalized(), scope_put_pixel(), vectorscope_put_cross(), ImBuf::x, and ImBuf::y.
Referenced by make_vectorscope_view_from_ibuf().
ImBuf* make_waveform_view_from_ibuf (ImBuf * ibuf) [read]
Definition at line 239 of file sequencer_scopes.c.
References make_waveform_view_from_ibuf_byte(), make_waveform_view_from_ibuf_float(), and ImBuf::rect_float.
Referenced by draw_image_seq().
static ImBuf* make_waveform_view_from_ibuf_byte (ImBuf * ibuf) [static]
Definition at line 150 of file sequencer_scopes.c.
References IB_rect, IMB_allocImBuf(), NULL, p, pow(), ImBuf::rect, rgb_to_luma_byte(), scope_put_pixel(), wform_put_border(), wform_put_grid(), wform_put_line(), ImBuf::x, and ImBuf::y.
Referenced by make_waveform_view_from_ibuf().
static ImBuf* make_waveform_view_from_ibuf_float (ImBuf * ibuf) [static]
Definition at line 193 of file sequencer_scopes.c.
References CLAMP(), IB_rect, IMB_allocImBuf(), NULL, p, pow(), ImBuf::rect, ImBuf::rect_float, rgb_to_luma(), scope_put_pixel(), wform_put_border(), wform_put_grid(), wform_put_line(), ImBuf::x, and ImBuf::y.
Referenced by make_waveform_view_from_ibuf().
ImBuf* make_zebra_view_from_ibuf (ImBuf * src, float perc) [read]
Definition at line 423 of file sequencer_scopes.c.
References draw_zebra_byte(), draw_zebra_float(), IB_rect, IMB_allocImBuf(), ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by draw_image_seq().
static void rgb_to_yuv_normalized (const float rgb[3], float yuv[3]) [static]
Definition at line 42 of file sequencer_scopes.c.
Referenced by make_vectorscope_view_from_ibuf_byte(), make_vectorscope_view_from_ibuf_float(), and vectorscope_put_cross().
static void scope_put_pixel (unsigned char * table, unsigned char * pos) [static]
Definition at line 56 of file sequencer_scopes.c.
Referenced by make_vectorscope_view_from_ibuf_byte(), make_vectorscope_view_from_ibuf_float(), make_waveform_view_from_ibuf_byte(), and make_waveform_view_from_ibuf_float().
static void scope_put_pixel_single (unsigned char * table, unsigned char * pos, int col) [static]
Definition at line 63 of file sequencer_scopes.c.
Referenced by make_sep_waveform_view_from_ibuf_byte(), and make_sep_waveform_view_from_ibuf_float().
static void vectorscope_put_cross (unsigned char r, unsigned char g, unsigned char b, char * tgt, int w, int h, int size) [static]
Definition at line 570 of file sequencer_scopes.c.
References g, p, rgb_to_yuv_normalized(), size(), ImBuf::x, and ImBuf::y.
Referenced by make_vectorscope_view_from_ibuf_byte(), and make_vectorscope_view_from_ibuf_float().
static void wform_put_border (unsigned char * tgt, int w, int h) [static]
Definition at line 107 of file sequencer_scopes.c.
References p, ImBuf::x, and ImBuf::y.
Referenced by make_histogram_view_from_ibuf_byte(), make_histogram_view_from_ibuf_float(), make_sep_waveform_view_from_ibuf_byte(), make_sep_waveform_view_from_ibuf_float(), make_waveform_view_from_ibuf_byte(), and make_waveform_view_from_ibuf_float().
static void wform_put_grid (unsigned char * tgt, int w, int h) [static]
Definition at line 143 of file sequencer_scopes.c.
References wform_put_gridrow().
Referenced by make_sep_waveform_view_from_ibuf_byte(), make_sep_waveform_view_from_ibuf_float(), make_waveform_view_from_ibuf_byte(), and make_waveform_view_from_ibuf_float().
static void wform_put_gridrow (unsigned char * tgt, float perc, int w, int h) [static]
Definition at line 130 of file sequencer_scopes.c.
References i.
Referenced by wform_put_grid().
static void wform_put_line (int w, unsigned char * last_pos, unsigned char * new_pos) [static]
Definition at line 71 of file sequencer_scopes.c.
Referenced by make_waveform_view_from_ibuf_byte(), and make_waveform_view_from_ibuf_float().
static void wform_put_line_single (int w, unsigned char * last_pos, unsigned char * new_pos, int col) [static]
Definition at line 89 of file sequencer_scopes.c.
Referenced by make_sep_waveform_view_from_ibuf_byte(), and make_sep_waveform_view_from_ibuf_float().