Blender: nla_channels.c File Reference
nla_channels.c File Reference
NLA editor
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "DNA_anim_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BKE_animsys.h"
#include "BKE_nla.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_screen.h"
#include "ED_anim_api.h"
#include "ED_keyframes_edit.h"
#include "ED_screen.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_view2d.h"
#include "nla_intern.h"
Functions
static int mouse_nla_channels (bAnimContext *ac, float x, int channel_index, short selectmode)
static int nlachannels_mouseclick_invoke (bContext *C, wmOperator *op, wmEvent *event)
void NLA_OT_channels_click (wmOperatorType *ot)
static int nlaedit_add_tracks_exec (bContext *C, wmOperator *op)
void NLA_OT_tracks_add (wmOperatorType *ot)
static int nlaedit_delete_tracks_exec (bContext *C, wmOperator *UNUSED(op))
void NLA_OT_delete_tracks (wmOperatorType *ot)
Detailed Description
Definition in file nla_channels.c.
Function Documentation
static int mouse_nla_channels (bAnimContext * ac, float x, int channel_index, short selectmode) [static]
Definition at line 77 of file nla_channels.c.
References ACHANNEL_SETFLAG_CLEAR, bAnimListElem::adt, Object::adt, Scene::adt, ADT_NLA_EDIT_NOMAP, ADT_UI_ACTIVE, ADT_UI_SELECTED, ANIM_animdata_filter(), ANIM_deselect_anim_channels(), ANIM_set_active_channel(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, ANIMTYPE_DSARM, ANIMTYPE_DSCAM, ANIMTYPE_DSCUR, ANIMTYPE_DSLAM, ANIMTYPE_DSLAT, ANIMTYPE_DSMAT, ANIMTYPE_DSMBALL, ANIMTYPE_DSMESH, ANIMTYPE_DSNTREE, ANIMTYPE_DSPART, ANIMTYPE_DSSKEY, ANIMTYPE_DSSPK, ANIMTYPE_DSTEX, ANIMTYPE_DSWOR, ANIMTYPE_FILLACTD, ANIMTYPE_NLAACTION, ANIMTYPE_NLATRACK, ANIMTYPE_OBJECT, ANIMTYPE_SCENE, bAnimContext::ar, BKE_animdata_from_id(), BKE_nla_action_pushdown(), BKE_nlatrack_solo_toggle(), BLI_findlink(), BLI_freelistN(), View2D::cur, bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, ELEM, filter(), NlaTrack::flag, AnimData::flag, Object::flag, Base::flag, Scene::flag, G, G_DEBUG, GS, bAnimListElem::id, ID_MA, ID_PA, if(), NA_EDITED, NA_SELECTED, ID::name, ND_ANIMCHAN, ND_NLA_ACTCHANGE, Base::next, NLACHANNEL_BUTTON_WIDTH, nlaedit_is_tweakmode_on(), NLATRACK_MUTED, NLATRACK_PROTECTED, NLATRACK_SELECTED, NULL, Base::object, SCE_DS_SELECTED, SELECT, SELECT_INVERT, bDopeSheet::source, bAnimListElem::type, ARegion::v2d, and rctf::xmax.
Referenced by nlachannels_mouseclick_invoke().
void NLA_OT_channels_click (wmOperatorType * ot)
Definition at line 344 of file nla_channels.c.
References wmOperatorType::description, ED_operator_nla_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, nlachannels_mouseclick_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by nla_operatortypes().
void NLA_OT_delete_tracks (wmOperatorType * ot)
Definition at line 482 of file nla_channels.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_delete_tracks_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by nla_operatortypes().
void NLA_OT_tracks_add (wmOperatorType * ot)
Definition at line 418 of file nla_channels.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nlaedit_add_tracks_exec(), nlaop_poll_tweakmode_off(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by nla_operatortypes().
static int nlachannels_mouseclick_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 301 of file nla_channels.c.
References ANIM_animdata_get_context(), bAnimContext::ar, if(), mouse_nla_channels(), wmEvent::mval, NC_ANIMATION, NLACHANNEL_HEIGHT_HALF, NLACHANNEL_NAMEWIDTH, NLACHANNEL_STEP, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), SELECT_INVERT, SELECT_REPLACE, bAnimContext::sl, UI_view2d_listview_view_to_cell(), UI_view2d_region_to_view(), ARegion::v2d, and WM_event_add_notifier().
Referenced by NLA_OT_channels_click().
static int nlaedit_add_tracks_exec (bContext * C, wmOperator * op) [static]
Definition at line 368 of file nla_channels.c.
References add_nlatrack(), bAnimListElem::adt, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_SEL, ANIMTYPE_NLATRACK, BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, if(), NA_EDITED, NC_ANIMATION, ND_NLA, bAnimListElem::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), bAnimListElem::type, and WM_event_add_notifier().
Referenced by NLA_OT_tracks_add().
static int nlaedit_delete_tracks_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 439 of file nla_channels.c.
References bAnimListElem::adt, ADT_NLA_SOLO_TRACK, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_SEL, ANIMTYPE_NLATRACK, BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, NlaTrack::flag, free_nlatrack(), if(), NA_EDITED, NC_ANIMATION, ND_NLA, bAnimListElem::next, NLATRACK_SOLO, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, bAnimListElem::type, and WM_event_add_notifier().
Referenced by NLA_OT_delete_tracks().