Blender: ntlBlenderDumper Class Reference
ntlBlenderDumper Class Reference
#include <ntl_blenderdumper.h>
Public Member Functions
ntlBlenderDumper ()
ntlBlenderDumper (string filename, bool commandlineMode)
virtual ~ntlBlenderDumper (void)
virtual int renderScene (void)
Detailed Description
Definition at line 15 of file ntl_blenderdumper.h.
Constructor & Destructor Documentation
ntlBlenderDumper::ntlBlenderDumper ()
Constructor
Definition at line 29 of file ntl_blenderdumper.cpp.
ntlBlenderDumper::ntlBlenderDumper (string filename, bool commandlineMode)
Definition at line 33 of file ntl_blenderdumper.cpp.
ntlBlenderDumper::~ntlBlenderDumper (void) [virtual]
Destructor
Definition at line 44 of file ntl_blenderdumper.cpp.
References debMsgStd, and DM_NOTIFY.
Member Function Documentation
int ntlBlenderDumper::renderScene (void) [virtual]
render scene (a single pictures)
Reimplemented from ntlWorld.
Definition at line 56 of file ntl_blenderdumper.cpp.
References debMsgStd, debugOut, ntlMatrix4x4< Scalar >::decompose(), DM_MSG, DM_NOTIFY, DUMP_FULLGEOMETRY, errFatal, errMsg, GEOCLASSTID_OBJECT, GEOCLASSTID_SHADER, ntlRenderGlobals::getAniCount(), LbmSolverInterface::getDomainTrafo(), LbmSolverInterface::getDumpVelocities(), ntlScene::getGeoClasses(), ntlGeometryShader::getObjectsBegin(), ntlGeometryShader::getObjectsEnd(), ntlGeometryShader::getOutFilename(), ntlRenderGlobals::getOutFilename(), ntlRenderGlobals::getSimScene(), SimulationObject::getSolver(), getTime(), getTimeString(), LbmSolverInterface::getVelocityAt(), glob_mpactive, glob_mpindex, i, ntlMatrix4x4< Scalar >::initId(), ntlMatrix4x4< Scalar >::initRotationXYZ(), ntlWorld::mpGlob, ntlWorld::mSimulationTime, normalize(), ntlGeometryShader::notifyShaderOfDump(), ntlRenderGlobals::setAniCount(), SIMWORLD_INITERROR, and snprintf.
The documentation for this class was generated from the following files:
ntl_blenderdumper.h
ntl_blenderdumper.cpp