Blender: gim_bitset Class Reference
gim_bitset Class Reference
#include <gim_bitset.h>
Public Member Functions
gim_bitset ()
gim_bitset (GUINT bits_count)
~gim_bitset ()
bool resize (GUINT newsize)
GUINT size ()
void set_all ()
void clear_all ()
void set (GUINT bit_index)
char get (GUINT bit_index)
Return 0 or 1.
void clear (GUINT bit_index)
Public Attributes
gim_array< GUINT > m_container
Detailed Description
Definition at line 41 of file gim_bitset.h.
Constructor & Destructor Documentation
gim_bitset::gim_bitset () [inline]
Definition at line 46 of file gim_bitset.h.
gim_bitset::gim_bitset (GUINT bits_count) [inline]
Definition at line 51 of file gim_bitset.h.
References resize().
gim_bitset::~gim_bitset () [inline]
Definition at line 56 of file gim_bitset.h.
Member Function Documentation
void gim_bitset::clear (GUINT bit_index) [inline]
Definition at line 113 of file gim_bitset.h.
References GUINT_BIT_COUNT, GUINT_EXPONENT, and m_container.
void gim_bitset::clear_all () [inline]
Definition at line 84 of file gim_bitset.h.
References GUINT, i, m_container, and gim_array< T >::size().
char gim_bitset::get (GUINT bit_index) [inline]
Return 0 or 1.
Definition at line 102 of file gim_bitset.h.
References GUINT_BIT_COUNT, GUINT_EXPONENT, m_container, and size().
bool gim_bitset::resize (GUINT newsize) [inline]
Definition at line 60 of file gim_bitset.h.
References GUINT, GUINT_BIT_COUNT, m_container, gim_array< T >::resize(), and gim_array< T >::size().
Referenced by gim_bitset(), and set().
void gim_bitset::set (GUINT bit_index) [inline]
Definition at line 92 of file gim_bitset.h.
References GUINT_BIT_COUNT, GUINT_EXPONENT, m_container, resize(), and size().
void gim_bitset::set_all () [inline]
Definition at line 76 of file gim_bitset.h.
References GUINT, i, m_container, and gim_array< T >::size().
GUINT gim_bitset::size () [inline]
Definition at line 71 of file gim_bitset.h.
References GUINT_BIT_COUNT, m_container, and gim_array< T >::size().
Referenced by get(), and set().
Member Data Documentation
gim_array<GUINT> gim_bitset::m_container
Definition at line 44 of file gim_bitset.h.
Referenced by clear(), clear_all(), get(), resize(), set(), set_all(), and size().
The documentation for this class was generated from the following file:
gim_bitset.h