Blender: GEN_List Class Reference
GEN_List Class Reference
#include <GEN_List.h>
Public Member Functions
GEN_List ()
GEN_Link * getHead () const
GEN_Link * getTail () const
void addHead (GEN_Link *link)
void addTail (GEN_Link *link)
Detailed Description
Definition at line 71 of file GEN_List.h.
Constructor & Destructor Documentation
GEN_List::GEN_List () [inline]
Definition at line 73 of file GEN_List.h.
Member Function Documentation
void GEN_List::addHead (GEN_Link * link) [inline]
Definition at line 78 of file GEN_List.h.
References GEN_Link::insertAfter().
void GEN_List::addTail (GEN_Link * link) [inline]
Definition at line 79 of file GEN_List.h.
References GEN_Link::insertBefore().
GEN_Link* GEN_List::getHead () const [inline]
Definition at line 75 of file GEN_List.h.
References GEN_Link::getNext().
GEN_Link* GEN_List::getTail () const [inline]
Definition at line 76 of file GEN_List.h.
References GEN_Link::getPrev().
The documentation for this class was generated from the following file:
GEN_List.h