Blender: outliner_ops.c File Reference
outliner_ops.c File Reference
outliner space
#include "DNA_space_types.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "BLI_utildefines.h"
#include "outliner_intern.h"
Functions
void outliner_operatortypes (void)
void outliner_keymap (wmKeyConfig *keyconf)
Detailed Description
Definition in file outliner_ops.c.
Function Documentation
void outliner_keymap (wmKeyConfig * keyconf)
Definition at line 81 of file outliner_ops.c.
References AKEY, BKEY, DKEY, FALSE, HOMEKEY, IKEY, KKEY, KM_ALT, KM_CLICK, KM_CTRL, KM_DBL_CLICK, KM_PRESS, KM_SHIFT, LEFTMOUSE, PADMINUS, PADPERIOD, PADPLUSKEY, PAGEDOWNKEY, PAGEUPKEY, PERIODKEY, wmKeyMapItem::ptr, RETKEY, RIGHTMOUSE, RKEY, RNA_boolean_set(), SKEY, SPACE_OUTLINER, TRUE, VKEY, WM_keymap_add_item(), WM_keymap_find(), and WM_keymap_verify_item().
Referenced by ED_spacetype_outliner().
void outliner_operatortypes (void)
Definition at line 45 of file outliner_ops.c.
References OUTLINER_OT_action_set(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_drivers_add_selected(), OUTLINER_OT_drivers_delete_selected(), OUTLINER_OT_expanded_toggle(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_item_activate(), OUTLINER_OT_item_openclose(), OUTLINER_OT_item_rename(), OUTLINER_OT_keyingset_add_selected(), OUTLINER_OT_keyingset_remove_selected(), OUTLINER_OT_object_operation(), OUTLINER_OT_operation(), OUTLINER_OT_parent_clear(), OUTLINER_OT_parent_drop(), OUTLINER_OT_renderability_toggle(), OUTLINER_OT_scroll_page(), OUTLINER_OT_select_border(), OUTLINER_OT_selectability_toggle(), OUTLINER_OT_selected_toggle(), OUTLINER_OT_show_active(), OUTLINER_OT_show_hierarchy(), OUTLINER_OT_show_one_level(), OUTLINER_OT_visibility_toggle(), and WM_operatortype_append().
Referenced by ED_spacetype_outliner().