Blender: rna_nodetree.c File Reference
rna_nodetree.c File Reference
RNA
#include <stdlib.h>
#include <string.h>
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "rna_internal_types.h"
#include "BLI_listbase.h"
#include "DNA_material_types.h"
#include "DNA_mesh_types.h"
#include "DNA_node_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_texture_types.h"
#include "BKE_animsys.h"
#include "BKE_main.h"
#include "BKE_node.h"
#include "BKE_image.h"
#include "BKE_texture.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "WM_types.h"
#include "MEM_guardedalloc.h"
#include "rna_nodetree_types.h"
Classes
struct NodeInfo
Defines
#define NODE_DEFINE_SUBTYPES_INT
#define NODE_DEFINE_SUBTYPES_FLOAT
#define NODE_DEFINE_SUBTYPES_VECTOR
#define NODE_DEFINE_SUBTYPES
#define MaxNodes 50000
#define DefNode(Category, ID, DefFunc, EnumName, StructName, UIName, UIDesc) reg_node(ID, Category_##Category, EnumName, STRINGIFY_ARG(Category##StructName), #Category, UIName, UIDesc);
#define SUBTYPE(socktype, stypename, id, idname) { PROP_##id, #socktype "_" #id, 0, #idname, ""},
#define SUBTYPE(socktype, stypename, id, idname) if (subtype == (PROP_##id)) propsubtype = PROP_##id;
#define SUBTYPE(socktype, stypename, id, idname)
#define DefNode(Category, ID, DefFunc, EnumName, StructName, UIName, UIDesc) define_specific_node(brna, ID, DefFunc);
Typedefs
typedef struct NodeInfo NodeInfo
Enumerations
enum {
Category_GroupNode, Category_LoopNode, Category_LayoutNode, Category_ShaderNode,
Category_CompositorNode, Category_TextureNode
}
Functions
static void reg_node (int ID, int category, const char *enum_name, const char *struct_name, const char *base_name, const char *ui_name, const char *ui_desc)
static StructRNA * def_node (BlenderRNA *brna, int node_id)
static void alloc_node_type_items (EnumPropertyItem *items, int category)
static void def_group (StructRNA *srna)
static void def_forloop (StructRNA *srna)
static void def_whileloop (StructRNA *srna)
static void def_frame (StructRNA *srna)
static void def_math (StructRNA *srna)
static void def_vector_math (StructRNA *srna)
static void def_rgb_curve (StructRNA *srna)
static void def_vector_curve (StructRNA *srna)
static void def_time (StructRNA *srna)
static void def_colorramp (StructRNA *srna)
static void def_mix_rgb (StructRNA *srna)
static void def_texture (StructRNA *srna)
static void def_sh_material (StructRNA *srna)
static void def_sh_mapping (StructRNA *srna)
static void def_sh_geometry (StructRNA *srna)
static void def_sh_attribute (StructRNA *srna)
static void def_sh_tex (StructRNA *srna)
static void def_sh_tex_sky (StructRNA *srna)
static void def_sh_tex_environment (StructRNA *srna)
static void def_sh_tex_image (StructRNA *srna)
static void def_sh_tex_gradient (StructRNA *srna)
static void def_sh_tex_noise (StructRNA *srna)
static void def_sh_tex_checker (StructRNA *srna)
static void def_sh_tex_magic (StructRNA *srna)
static void def_sh_tex_musgrave (StructRNA *srna)
static void def_sh_tex_voronoi (StructRNA *srna)
static void def_sh_tex_wave (StructRNA *srna)
static void def_glossy (StructRNA *srna)
static void def_cmp_alpha_over (StructRNA *srna)
static void def_cmp_hue_saturation (StructRNA *srna)
static void def_cmp_blur (StructRNA *srna)
static void def_cmp_filter (StructRNA *srna)
static void def_cmp_map_value (StructRNA *srna)
static void def_cmp_vector_blur (StructRNA *srna)
static void def_cmp_levels (StructRNA *srna)
static void def_cmp_image (StructRNA *srna)
static void def_cmp_render_layers (StructRNA *srna)
static void rna_def_cmp_output_file_socket (BlenderRNA *brna)
static void def_cmp_output_file (StructRNA *srna)
static void def_cmp_dilate_erode (StructRNA *srna)
static void def_cmp_scale (StructRNA *srna)
static void def_cmp_rotate (StructRNA *srna)
static void def_cmp_diff_matte (StructRNA *srna)
static void def_cmp_color_matte (StructRNA *srna)
static void def_cmp_distance_matte (StructRNA *srna)
static void def_cmp_color_spill (StructRNA *srna)
static void def_cmp_luma_matte (StructRNA *srna)
static void def_cmp_chroma_matte (StructRNA *srna)
static void def_cmp_channel_matte (StructRNA *srna)
static void def_cmp_flip (StructRNA *srna)
static void def_cmp_splitviewer (StructRNA *srna)
static void def_cmp_id_mask (StructRNA *srna)
static void def_cmp_double_edge_mask (StructRNA *srna)
static void def_cmp_map_uv (StructRNA *srna)
static void def_cmp_defocus (StructRNA *srna)
static void def_cmp_invert (StructRNA *srna)
static void def_cmp_crop (StructRNA *srna)
static void def_cmp_dblur (StructRNA *srna)
static void def_cmp_bilateral_blur (StructRNA *srna)
static void def_cmp_premul_key (StructRNA *srna)
static void def_cmp_glare (StructRNA *srna)
static void def_cmp_tonemap (StructRNA *srna)
static void def_cmp_lensdist (StructRNA *srna)
static void def_cmp_colorbalance (StructRNA *srna)
static void def_cmp_huecorrect (StructRNA *srna)
static void def_cmp_zcombine (StructRNA *srna)
static void def_cmp_ycc (StructRNA *srna)
static void def_cmp_movieclip (StructRNA *srna)
static void def_cmp_stabilize2d (StructRNA *srna)
static void def_cmp_moviedistortion (StructRNA *srna)
static void dev_cmd_transform (StructRNA *srna)
static void def_tex_output (StructRNA *srna)
static void def_tex_image (StructRNA *srna)
static void def_tex_bricks (StructRNA *srna)
static void rna_def_shader_node (BlenderRNA *brna)
static void rna_def_compositor_node (BlenderRNA *brna)
static void rna_def_texture_node (BlenderRNA *brna)
static void rna_def_nodetree_link_api (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_composite_nodetree_api (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_shader_nodetree_api (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_texture_nodetree_api (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_node_socket (BlenderRNA *brna)
static void rna_def_node_socket_subtype (BlenderRNA *brna, int type, int subtype, const char *name, const char *ui_name)
static void rna_def_node (BlenderRNA *brna)
static void rna_def_node_link (BlenderRNA *brna)
static void rna_def_group_sockets_api (BlenderRNA *brna, PropertyRNA *cprop, int in_out)
static void rna_def_nodetree (BlenderRNA *brna)
static void rna_def_composite_nodetree (BlenderRNA *brna)
static void rna_def_shader_nodetree (BlenderRNA *brna)
static void rna_def_texture_nodetree (BlenderRNA *brna)
static void define_specific_node (BlenderRNA *brna, int id, void(*func)(StructRNA *))
Variables
EnumPropertyItem nodetree_type_items []
EnumPropertyItem node_socket_type_items []
EnumPropertyItem node_math_items []
EnumPropertyItem node_vec_math_items []
EnumPropertyItem node_filter_items []
EnumPropertyItem prop_noise_basis_items []
EnumPropertyItem prop_noise_type_items []
static EnumPropertyItem prop_image_layer_items []
static EnumPropertyItem prop_scene_layer_items []
static EnumPropertyItem prop_tri_channel_items []
static EnumPropertyItem node_flip_items []
static EnumPropertyItem node_ycc_items []
static EnumPropertyItem node_glossy_items []
static NodeInfo nodes [MaxNodes]
static EnumPropertyItem shader_node_type_items [MaxNodes]
static EnumPropertyItem compositor_node_type_items [MaxNodes]
static EnumPropertyItem texture_node_type_items [MaxNodes]
Detailed Description
Definition in file rna_nodetree.c.
Define Documentation
#define DefNode (Category, ID, DefFunc, EnumName, StructName, UIName, UIDesc) reg_node(ID, Category_##Category, EnumName, STRINGIFY_ARG(Category##StructName), #Category, UIName, UIDesc);
#define DefNode (Category, ID, DefFunc, EnumName, StructName, UIName, UIDesc) define_specific_node(brna, ID, DefFunc);
#define MaxNodes 50000
Definition at line 872 of file rna_nodetree.c.
Referenced by alloc_node_type_items().
#define NODE_DEFINE_SUBTYPES
Value:
NODE_DEFINE_SUBTYPES_INT \
NODE_DEFINE_SUBTYPES_FLOAT \
NODE_DEFINE_SUBTYPES_VECTOR
Definition at line 170 of file rna_nodetree.c.
Referenced by rna_def_node_socket_subtype().
#define NODE_DEFINE_SUBTYPES_FLOAT
Value:
SUBTYPE(FLOAT, Float, NONE, None) \
SUBTYPE(FLOAT, Float, UNSIGNED, Unsigned) \
SUBTYPE(FLOAT, Float, PERCENTAGE, Percentage) \
SUBTYPE(FLOAT, Float, FACTOR, Factor) \
SUBTYPE(FLOAT, Float, ANGLE, Angle) \
SUBTYPE(FLOAT, Float, TIME, Time) \
SUBTYPE(FLOAT, Float, DISTANCE, Distance)
Definition at line 152 of file rna_nodetree.c.
#define NODE_DEFINE_SUBTYPES_INT
Value:
SUBTYPE(INT, Int, NONE, None) \
SUBTYPE(INT, Int, UNSIGNED, Unsigned)
Definition at line 148 of file rna_nodetree.c.
#define NODE_DEFINE_SUBTYPES_VECTOR
Value:
SUBTYPE(VECTOR, Vector, NONE, None) \
SUBTYPE(VECTOR, Vector, TRANSLATION, Translation) \
SUBTYPE(VECTOR, Vector, DIRECTION, Direction) \
SUBTYPE(VECTOR, Vector, VELOCITY, Velocity) \
SUBTYPE(VECTOR, Vector, ACCELERATION, Acceleration) \
SUBTYPE(VECTOR, Vector, EULER, Euler) \
SUBTYPE(VECTOR, Vector, XYZ, XYZ)
Definition at line 161 of file rna_nodetree.c.
#define SUBTYPE (socktype, stypename, id, idname) { PROP_##id, #socktype "_" #id, 0, #idname, ""},
#define SUBTYPE (socktype, stypename, id, idname) if (subtype == (PROP_##id)) propsubtype = PROP_##id;
#define SUBTYPE (socktype, stypename, id, idname)
Value:
rna_def_node_socket_subtype(brna, SOCK_##socktype, PROP_##id, "NodeSocket"#stypename#idname, \
                                #idname" "#stypename" Node Socket");
Typedef Documentation
typedef struct NodeInfo NodeInfo
Enumeration Type Documentation
anonymous enum
Enumerator:
Category_GroupNode
Category_LoopNode
Category_LayoutNode
Category_ShaderNode
Category_CompositorNode
Category_TextureNode
Definition at line 874 of file rna_nodetree.c.
Function Documentation
static void alloc_node_type_items (EnumPropertyItem * items, int category) [static]
Definition at line 939 of file rna_nodetree.c.
References NodeInfo::category, NodeInfo::defined, EnumPropertyItem::description, NodeInfo::enum_name, i, NodeInfo::icon, EnumPropertyItem::icon, EnumPropertyItem::identifier, MaxNodes, EnumPropertyItem::name, NODE_DYNAMIC, NODE_GROUP, NodeInfo::ui_desc, NodeInfo::ui_name, and EnumPropertyItem::value.
Referenced by rna_def_compositor_node(), rna_def_shader_node(), and rna_def_texture_node().
static void def_cmp_alpha_over (StructRNA * srna) [static]
Definition at line 1470 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_bilateral_blur (StructRNA * srna) [static]
Definition at line 2450 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_blur (StructRNA * srna) [static]
Definition at line 1514 of file rna_nodetree.c.
References CMP_NODE_BLUR_ASPECT_NONE, CMP_NODE_BLUR_ASPECT_X, CMP_NODE_BLUR_ASPECT_Y, NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_PERCENTAGE, R_FILTER_BOX, R_FILTER_CATROM, R_FILTER_CUBIC, R_FILTER_FAST_GAUSS, R_FILTER_GAUSS, R_FILTER_MITCH, R_FILTER_QUAD, R_FILTER_TENT, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_channel_matte (StructRNA * srna) [static]
Definition at line 2084 of file rna_nodetree.c.
References CMP_NODE_CHANNEL_MATTE_CS_HSV, CMP_NODE_CHANNEL_MATTE_CS_RGB, CMP_NODE_CHANNEL_MATTE_CS_YCC, CMP_NODE_CHANNEL_MATTE_CS_YUV, NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_chroma_matte (StructRNA * srna) [static]
Definition at line 2045 of file rna_nodetree.c.
References DEG2RADF, NA_EDITED, NC_NODE, NULL, PROP_ANGLE, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_color_matte (StructRNA * srna) [static]
Definition at line 1907 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_color_spill (StructRNA * srna) [static]
Definition at line 1953 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_colorbalance (StructRNA * srna) [static]
Definition at line 2671 of file rna_nodetree.c.
References FLT_MAX, NA_EDITED, NC_NODE, NULL, PROP_COLOR_GAMMA, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_array_default(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_crop (StructRNA * srna) [static]
Definition at line 2331 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_dblur (StructRNA * srna) [static]
Definition at line 2396 of file rna_nodetree.c.
References DEG2RADF, NA_EDITED, NC_NODE, NULL, PROP_ANGLE, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_defocus (StructRNA * srna) [static]
Definition at line 2233 of file rna_nodetree.c.
References DEG2RADF, NA_EDITED, NC_NODE, NULL, PROP_ANGLE, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_diff_matte (StructRNA * srna) [static]
Definition at line 1886 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_dilate_erode (StructRNA * srna) [static]
Definition at line 1840 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_distance_matte (StructRNA * srna) [static]
Definition at line 1932 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_double_edge_mask (StructRNA * srna) [static]
Definition at line 2192 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_filter (StructRNA * srna) [static]
Definition at line 1596 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_flip (StructRNA * srna) [static]
Definition at line 2143 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_glare (StructRNA * srna) [static]
Definition at line 2492 of file rna_nodetree.c.
References DEG2RADF, NA_EDITED, NC_NODE, NULL, PROP_ANGLE, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_hue_saturation (StructRNA * srna) [static]
Definition at line 1489 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_huecorrect (StructRNA * srna) [static]
Definition at line 2740 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_id_mask (StructRNA * srna) [static]
Definition at line 2176 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_image (StructRNA * srna) [static]
Definition at line 1710 of file rna_nodetree.c.
References IMA_ANIM_ALWAYS, IMA_SRC_FILE, IMA_SRC_GENERATED, IMA_SRC_MOVIE, IMA_SRC_SEQUENCE, MAXFRAMEF, MINAFRAMEF, NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_invert (StructRNA * srna) [static]
Definition at line 2316 of file rna_nodetree.c.
References CMP_CHAN_A, CMP_CHAN_RGB, NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_lensdist (StructRNA * srna) [static]
Definition at line 2647 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_levels (StructRNA * srna) [static]
Definition at line 1691 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_luma_matte (StructRNA * srna) [static]
Definition at line 2024 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_map_uv (StructRNA * srna) [static]
Definition at line 2222 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_FACTOR, PROP_INT, RNA_def_property(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_map_value (StructRNA * srna) [static]
Definition at line 1607 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct_sdna_from(), TEXMAP_CLIP_MAX, and TEXMAP_CLIP_MIN.
static void def_cmp_movieclip (StructRNA * srna) [static]
Definition at line 2772 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_EDITABLE, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_moviedistortion (StructRNA * srna) [static]
Definition at line 2810 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_output_file (StructRNA * srna) [static]
Definition at line 1814 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_EDITABLE, PROP_FILEPATH, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_premul_key (StructRNA * srna) [static]
Definition at line 2475 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_render_layers (StructRNA * srna) [static]
Definition at line 1772 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_EDITABLE, PROP_ENUM, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_rotate (StructRNA * srna) [static]
Definition at line 1869 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_scale (StructRNA * srna) [static]
Definition at line 1851 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_splitviewer (StructRNA * srna) [static]
Definition at line 2154 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_FACTOR, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_stabilize2d (StructRNA * srna) [static]
Definition at line 2786 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_tonemap (StructRNA * srna) [static]
Definition at line 2586 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_vector_blur (StructRNA * srna) [static]
Definition at line 1652 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_cmp_ycc (StructRNA * srna) [static]
Definition at line 2761 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_cmp_zcombine (StructRNA * srna) [static]
Definition at line 2751 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_colorramp (StructRNA * srna) [static]
Definition at line 1101 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_forloop (StructRNA * srna) [static]
Definition at line 1000 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_EDITABLE, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_frame (StructRNA * srna) [static]
Definition at line 1030 of file rna_nodetree.c.
static void def_glossy (StructRNA * srna) [static]
Definition at line 1457 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_group (StructRNA * srna) [static]
Definition at line 988 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_EDITABLE, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_math (StructRNA * srna) [static]
Definition at line 1036 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_mix_rgb (StructRNA * srna) [static]
Definition at line 1112 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_NONE, ramp_blend_items, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static StructRNA* def_node (BlenderRNA * brna, int node_id) [static]
Definition at line 927 of file rna_nodetree.c.
References NodeInfo::base_name, RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), NodeInfo::struct_name, NodeInfo::ui_desc, and NodeInfo::ui_name.
Referenced by define_specific_node().
static void def_rgb_curve (StructRNA * srna) [static]
Definition at line 1058 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_sh_attribute (StructRNA * srna) [static]
Definition at line 1235 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_sh_geometry (StructRNA * srna) [static]
Definition at line 1218 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_sh_mapping (StructRNA * srna) [static]
Definition at line 1175 of file rna_nodetree.c.
References NULL, PROP_BOOLEAN, PROP_EULER, PROP_FLOAT, PROP_NONE, PROP_TRANSLATION, PROP_XYZ, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct_sdna_from(), TEXMAP_CLIP_MAX, and TEXMAP_CLIP_MIN.
static void def_sh_material (StructRNA * srna) [static]
Definition at line 1148 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), SH_NODE_MAT_DIFF, SH_NODE_MAT_NEG, and SH_NODE_MAT_SPEC.
static void def_sh_tex (StructRNA * srna) [static]
Definition at line 1247 of file rna_nodetree.c.
References NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), and RNA_def_property_ui_text().
Referenced by def_sh_tex_checker(), def_sh_tex_environment(), def_sh_tex_gradient(), def_sh_tex_image(), def_sh_tex_magic(), def_sh_tex_musgrave(), def_sh_tex_noise(), def_sh_tex_sky(), def_sh_tex_voronoi(), and def_sh_tex_wave().
static void def_sh_tex_checker (StructRNA * srna) [static]
Definition at line 1377 of file rna_nodetree.c.
References def_sh_tex(), and RNA_def_struct_sdna_from().
static void def_sh_tex_environment (StructRNA * srna) [static]
Definition at line 1278 of file rna_nodetree.c.
References def_sh_tex(), NA_EDITED, NC_NODE, NULL, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct_sdna_from(), SHD_COLORSPACE_COLOR, SHD_COLORSPACE_NONE, SHD_PROJ_EQUIRECTANGULAR, and SHD_PROJ_MIRROR_BALL.
static void def_sh_tex_gradient (StructRNA * srna) [static]
Definition at line 1347 of file rna_nodetree.c.
References def_sh_tex(), NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct_sdna_from(), SHD_BLEND_DIAGONAL, SHD_BLEND_EASING, SHD_BLEND_LINEAR, SHD_BLEND_QUADRATIC, SHD_BLEND_QUADRATIC_SPHERE, SHD_BLEND_RADIAL, and SHD_BLEND_SPHERICAL.
static void def_sh_tex_image (StructRNA * srna) [static]
Definition at line 1319 of file rna_nodetree.c.
References def_sh_tex(), NA_EDITED, NC_NODE, NULL, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct_sdna_from(), SHD_COLORSPACE_COLOR, and SHD_COLORSPACE_NONE.
static void def_sh_tex_magic (StructRNA * srna) [static]
Definition at line 1383 of file rna_nodetree.c.
References def_sh_tex(), NULL, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_sh_tex_musgrave (StructRNA * srna) [static]
Definition at line 1397 of file rna_nodetree.c.
References def_sh_tex(), NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct_sdna_from(), SHD_MUSGRAVE_FBM, SHD_MUSGRAVE_HETERO_TERRAIN, SHD_MUSGRAVE_HYBRID_MULTIFRACTAL, SHD_MUSGRAVE_MULTIFRACTAL, and SHD_MUSGRAVE_RIDGED_MULTIFRACTAL.
static void def_sh_tex_noise (StructRNA * srna) [static]
Definition at line 1371 of file rna_nodetree.c.
References def_sh_tex(), and RNA_def_struct_sdna_from().
static void def_sh_tex_sky (StructRNA * srna) [static]
Definition at line 1262 of file rna_nodetree.c.
References def_sh_tex(), NA_EDITED, NC_NODE, PROP_DIRECTION, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_sh_tex_voronoi (StructRNA * srna) [static]
Definition at line 1419 of file rna_nodetree.c.
References def_sh_tex(), NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct_sdna_from(), SHD_VORONOI_CELLS, and SHD_VORONOI_INTENSITY.
static void def_sh_tex_wave (StructRNA * srna) [static]
Definition at line 1438 of file rna_nodetree.c.
References def_sh_tex(), NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct_sdna_from(), SHD_WAVE_BANDS, and SHD_WAVE_RINGS.
static void def_tex_bricks (StructRNA * srna) [static]
Definition at line 2886 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_tex_image (StructRNA * srna) [static]
Definition at line 2865 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_EDITABLE, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_tex_output (StructRNA * srna) [static]
Definition at line 2853 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), and RNA_def_struct_sdna_from().
static void def_texture (StructRNA * srna) [static]
Definition at line 1128 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_time (StructRNA * srna) [static]
Definition at line 1080 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_vector_curve (StructRNA * srna) [static]
Definition at line 1069 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_vector_math (StructRNA * srna) [static]
Definition at line 1047 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void def_whileloop (StructRNA * srna) [static]
Definition at line 1012 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void define_specific_node (BlenderRNA * brna, int id, void(*)(StructRNA *) func) [static]
Definition at line 3449 of file rna_nodetree.c.
References def_node().
static void dev_cmd_transform (StructRNA * srna) [static]
Definition at line 2833 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
static void reg_node (int ID, int category, const char * enum_name, const char * struct_name, const char * base_name, const char * ui_name, const char * ui_desc) [static]
Definition at line 898 of file rna_nodetree.c.
References NodeInfo::base_name, NodeInfo::category, NodeInfo::defined, NodeInfo::enum_name, NodeInfo::struct_name, NodeInfo::ui_desc, and NodeInfo::ui_name.
static void rna_def_cmp_output_file_socket (BlenderRNA * brna) [static]
Definition at line 1792 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
static void rna_def_composite_nodetree (BlenderRNA * brna) [static]
Definition at line 3391 of file rna_nodetree.c.
References NULL, PROP_COLLECTION, PROP_NONE, rna_def_composite_nodetree_api(), RNA_def_property(), RNA_def_property_collection_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
static void rna_def_composite_nodetree_api (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 3005 of file rna_nodetree.c.
References FUNC_USE_CONTEXT, FUNC_USE_REPORTS, NULL, PROP_REQUIRED, RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_composite_nodetree().
static void rna_def_compositor_node (BlenderRNA * brna) [static]
Definition at line 2936 of file rna_nodetree.c.
References alloc_node_type_items(), Category_CompositorNode, PROP_EDITABLE, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
static void rna_def_group_sockets_api (BlenderRNA * brna, PropertyRNA * cprop, int in_out) [static]
Definition at line 3310 of file rna_nodetree.c.
References FUNC_USE_REPORTS, MAX_NAME, NULL, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SOCK_FLOAT, SOCK_IN, and TRUE.
Referenced by rna_def_nodetree().
static void rna_def_node (BlenderRNA * brna) [static]
Definition at line 3227 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NODE_ACTIVE_TEXTURE, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
static void rna_def_node_link (BlenderRNA * brna) [static]
Definition at line 3279 of file rna_nodetree.c.
References NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
static void rna_def_node_socket (BlenderRNA * brna) [static]
Definition at line 3098 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_default(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and SOCK_COLLAPSED.
static void rna_def_node_socket_subtype (BlenderRNA * brna, int type, int subtype, const char * name, const char * ui_name) [static]
Definition at line 3136 of file rna_nodetree.c.
References NA_EDITED, NC_NODE, NODE_DEFINE_SUBTYPES, NULL, PROP_BOOLEAN, PROP_COLOR, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), SOCK_BOOLEAN, SOCK_FLOAT, SOCK_INT, SOCK_RGBA, and SOCK_VECTOR.
static void rna_def_nodetree (BlenderRNA * brna) [static]
Definition at line 3342 of file rna_nodetree.c.
References NC_NODE, NULL, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, rna_def_animdata_common(), rna_def_group_sockets_api(), rna_def_nodetree_link_api(), RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), SOCK_IN, and SOCK_OUT.
static void rna_def_nodetree_link_api (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2973 of file rna_nodetree.c.
References FUNC_USE_REPORTS, NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_nodetree().
static void rna_def_shader_node (BlenderRNA * brna) [static]
Definition at line 2918 of file rna_nodetree.c.
References alloc_node_type_items(), Category_ShaderNode, PROP_EDITABLE, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
static void rna_def_shader_nodetree (BlenderRNA * brna) [static]
Definition at line 3410 of file rna_nodetree.c.
References NULL, PROP_COLLECTION, PROP_NONE, RNA_def_property(), RNA_def_property_collection_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), rna_def_shader_nodetree_api(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
static void rna_def_shader_nodetree_api (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 3036 of file rna_nodetree.c.
References FUNC_USE_CONTEXT, FUNC_USE_REPORTS, NULL, PROP_REQUIRED, RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_shader_nodetree().
static void rna_def_texture_node (BlenderRNA * brna) [static]
Definition at line 2954 of file rna_nodetree.c.
References alloc_node_type_items(), Category_TextureNode, PROP_EDITABLE, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
static void rna_def_texture_nodetree (BlenderRNA * brna) [static]
Definition at line 3430 of file rna_nodetree.c.
References NULL, PROP_COLLECTION, PROP_NONE, RNA_def_property(), RNA_def_property_collection_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and rna_def_texture_nodetree_api().
static void rna_def_texture_nodetree_api (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 3067 of file rna_nodetree.c.
References FUNC_USE_CONTEXT, FUNC_USE_REPORTS, NULL, PROP_REQUIRED, RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_texture_nodetree().
Variable Documentation
EnumPropertyItem compositor_node_type_items[MaxNodes] [static]
Definition at line 2935 of file rna_nodetree.c.
EnumPropertyItem node_filter_items[]
Initial value:
 {
    {0, "SOFTEN",  0, "Soften",  ""},
    {1, "SHARPEN", 0, "Sharpen", ""},
    {2, "LAPLACE", 0, "Laplace", ""},
    {3, "SOBEL",   0, "Sobel",   ""},
    {4, "PREWITT", 0, "Prewitt", ""},
    {5, "KIRSCH",  0, "Kirsch",  ""},
    {6, "SHADOW",  0, "Shadow",  ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 107 of file rna_nodetree.c.
Referenced by node_filter_label().
EnumPropertyItem node_flip_items[] [static]
Initial value:
 {
{0, "X",  0, "Flip X",     ""},
{1, "Y",  0, "Flip Y",     ""},
{2, "XY", 0, "Flip X & Y", ""},
{0, NULL, 0, NULL, NULL}}
Definition at line 854 of file rna_nodetree.c.
EnumPropertyItem node_glossy_items[] [static]
Initial value:
 {
{SHD_GLOSSY_SHARP,    "SHARP",    0, "Sharp",    ""},
{SHD_GLOSSY_BECKMANN, "BECKMANN", 0, "Beckmann", ""},
{SHD_GLOSSY_GGX,      "GGX",      0, "GGX",      ""},
{0, NULL, 0, NULL, NULL}}
Definition at line 866 of file rna_nodetree.c.
EnumPropertyItem node_math_items[]
Initial value:
 {
    { 0, "ADD",          0, "Add",          ""},
    { 1, "SUBTRACT",     0, "Subtract",     ""},
    { 2, "MULTIPLY",     0, "Multiply",     ""},
    { 3, "DIVIDE",       0, "Divide",       ""},
    { 4, "SINE",         0, "Sine",         ""},
    { 5, "COSINE",       0, "Cosine",       ""},
    { 6, "TANGENT",      0, "Tangent",      ""},
    { 7, "ARCSINE",      0, "Arcsine",      ""},
    { 8, "ARCCOSINE",    0, "Arccosine",    ""},
    { 9, "ARCTANGENT",   0, "Arctangent",   ""},
    {10, "POWER",        0, "Power",        ""},
    {11, "LOGARITHM",    0, "Logarithm",    ""},
    {12, "MINIMUM",      0, "Minimum",      ""},
    {13, "MAXIMUM",      0, "Maximum",      ""},
    {14, "ROUND",        0, "Round",        ""},
    {15, "LESS_THAN",    0, "Less Than",    ""},
    {16, "GREATER_THAN", 0, "Greater Than", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 78 of file rna_nodetree.c.
Referenced by node_math_label().
EnumPropertyItem node_socket_type_items[]
Initial value:
 {
    {SOCK_FLOAT,   "VALUE",     0,    "Value",     ""},
    {SOCK_VECTOR,  "VECTOR",    0,    "Vector",    ""},
    {SOCK_RGBA,    "RGBA",      0,    "RGBA",      ""},
    {SOCK_SHADER,  "SHADER",    0,    "Shader",    ""},
    {SOCK_BOOLEAN, "BOOLEAN",   0,    "Boolean",   ""},
    {SOCK_MESH,    "MESH",      0,    "Mesh",      ""},
    {SOCK_INT,     "INT",       0,    "Int",       ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 68 of file rna_nodetree.c.
Referenced by NODE_OT_group_socket_add().
EnumPropertyItem node_vec_math_items[]
Initial value:
 {
    {0, "ADD",           0, "Add",           ""},
    {1, "SUBTRACT",      0, "Subtract",      ""},
    {2, "AVERAGE",       0, "Average",       ""},
    {3, "DOT_PRODUCT",   0, "Dot Product",   ""},
    {4, "CROSS_PRODUCT", 0, "Cross Product", ""},
    {5, "NORMALIZE",     0, "Normalize",     ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 98 of file rna_nodetree.c.
Referenced by node_vect_math_label().
EnumPropertyItem node_ycc_items[] [static]
Initial value:
 {
{ 0, "ITUBT601", 0, "ITU 601",  ""},
{ 1, "ITUBT709", 0, "ITU 709",  ""},
{ 2, "JFIF",     0, "Jpeg",     ""},
{0, NULL, 0, NULL, NULL}}
Definition at line 860 of file rna_nodetree.c.
NodeInfo nodes[MaxNodes] [static]
Definition at line 896 of file rna_nodetree.c.
Referenced by BLI_pbvh_draw(), BLI_pbvh_update(), btMultiSapBroadphase::buildTree(), do_brush_action(), findClosestNode(), hide_show_exec(), IsoSurface::initializeIsosurface(), kdtree_balance(), object_sculpt_modifiers_changed(), p_smooth(), QBVH::pack_nodes(), IsoSurface::resetAll(), sculpt_combine_proxies(), sculpt_flush_stroke_deform(), sculpt_restore_mesh(), btDbvt::write(), and DocumentImporter::writeLibraryNodes().
EnumPropertyItem nodetree_type_items[]
Initial value:
 {
    {NTREE_SHADER,      "SHADER",       ICON_MATERIAL,      "Shader",       "Shader nodes"  },
    {NTREE_TEXTURE,     "TEXTURE",      ICON_TEXTURE,       "Texture",      "Texture nodes"     },
    {NTREE_COMPOSIT,    "COMPOSITING",  ICON_RENDERLAYERS,  "Compositing",  "Compositing nodes" },
    {0, NULL, 0, NULL, NULL}
}
Definition at line 60 of file rna_nodetree.c.
Referenced by NODE_OT_new_node_tree(), and rna_def_space_node().
EnumPropertyItem prop_image_layer_items[] [static]
Initial value:
 {
{ 0, "PLACEHOLDER",          0, "Placeholder",          ""},
{0, NULL, 0, NULL, NULL}}
Definition at line 840 of file rna_nodetree.c.
EnumPropertyItem prop_noise_basis_items[]
Initial value:
 {
    {SHD_NOISE_PERLIN, "PERLIN", 0, "Perlin", ""},
    {SHD_NOISE_VORONOI_F1, "VORONOI_F1", 0, "Voronoi F1", ""},
    {SHD_NOISE_VORONOI_F2, "VORONOI_F2", 0, "Voronoi F2", ""},
    {SHD_NOISE_VORONOI_F3, "VORONOI_F3", 0, "Voronoi F3", ""},
    {SHD_NOISE_VORONOI_F4, "VORONOI_F4", 0, "Voronoi F4", ""},
    {SHD_NOISE_VORONOI_F2_F1, "VORONOI_F2_F1", 0, "Voronoi F2-F1", ""},
    {SHD_NOISE_VORONOI_CRACKLE, "VORONOI_CRACKLE", 0, "Voronoi Crackle", ""},
    {SHD_NOISE_CELL_NOISE, "CELL_NOISE", 0, "Cell Noise", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 117 of file rna_nodetree.c.
EnumPropertyItem prop_noise_type_items[]
Initial value:
 {
    {SHD_NOISE_SOFT, "SOFT", 0, "Soft", ""},
    {SHD_NOISE_HARD, "HARD", 0, "Hard", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 128 of file rna_nodetree.c.
Referenced by rna_def_smoke_domain_settings().
EnumPropertyItem prop_scene_layer_items[] [static]
Initial value:
 {
{ 0, "PLACEHOLDER",          0, "Placeholder",          ""},
{0, NULL, 0, NULL, NULL}}
Definition at line 844 of file rna_nodetree.c.
EnumPropertyItem prop_tri_channel_items[] [static]
Initial value:
 {
{ 1, "R", 0, "R", ""},
{ 2, "G", 0, "G", ""},
{ 3, "B", 0, "B", ""},
{0, NULL, 0, NULL, NULL}}
Definition at line 848 of file rna_nodetree.c.
EnumPropertyItem shader_node_type_items[MaxNodes] [static]
Definition at line 2917 of file rna_nodetree.c.
EnumPropertyItem texture_node_type_items[MaxNodes] [static]
Definition at line 2953 of file rna_nodetree.c.