Blender: KX_ListSlot Class Reference
KX_ListSlot Class Reference
#include <RAS_MaterialBucket.h>
Public Member Functions
KX_ListSlot ()
virtual ~KX_ListSlot ()
virtual int Release ()
virtual KX_ListSlot * AddRef ()
virtual void SetModified (bool mod)=0
Protected Attributes
int m_refcount
Detailed Description
Definition at line 52 of file RAS_MaterialBucket.h.
Constructor & Destructor Documentation
KX_ListSlot::KX_ListSlot () [inline]
Definition at line 57 of file RAS_MaterialBucket.h.
virtual KX_ListSlot::~KX_ListSlot () [inline, virtual]
Definition at line 58 of file RAS_MaterialBucket.h.
Member Function Documentation
virtual KX_ListSlot* KX_ListSlot::AddRef () [inline, virtual]
Definition at line 65 of file RAS_MaterialBucket.h.
virtual int KX_ListSlot::Release () [inline, virtual]
Reimplemented in RAS_ListSlot.
Definition at line 59 of file RAS_MaterialBucket.h.
Referenced by RAS_MeshSlot::Join(), RAS_MeshSlot::Split(), and RAS_MeshSlot::~RAS_MeshSlot().
virtual void KX_ListSlot::SetModified (bool mod) [pure virtual]
Implemented in RAS_ListSlot.
Referenced by RAS_MaterialBucket::RenderMeshSlot().
Member Data Documentation
int KX_ListSlot::m_refcount [protected]
Definition at line 55 of file RAS_MaterialBucket.h.
Referenced by RAS_ListSlot::Release().
The documentation for this class was generated from the following file:
RAS_MaterialBucket.h