Blender: GregoryQuadPatch Class Reference
GregoryQuadPatch Class Reference
#include <subd_patch.h>
Public Member Functions
void eval (float3 *P, float3 *dPdu, float3 *dPdv, float u, float v)
bool is_triangle ()
BoundBox bound ()
Public Attributes
float3 hull [20]
Detailed Description
Definition at line 87 of file subd_patch.h.
Member Function Documentation
BoundBox GregoryQuadPatch::bound () [virtual]
Implements Patch.
Definition at line 206 of file subd_patch.cpp.
References BoundBox::grow(), hull, and i.
void GregoryQuadPatch::eval (float3 * P, float3 * dPdu, float3 * dPdv, float u, float v) [virtual]
Implements Patch.
Definition at line 171 of file subd_patch.cpp.
References decasteljau_bicubic(), hull, no_zero_div(), and V.
bool GregoryQuadPatch::is_triangle () [inline, virtual]
Implements Patch.
Definition at line 92 of file subd_patch.h.
Member Data Documentation
float3 GregoryQuadPatch::hull[20]
Definition at line 89 of file subd_patch.h.
Referenced by bound(), eval(), and SubdAccBuilder::run().
The documentation for this class was generated from the following files:
subd_patch.h
subd_patch.cpp