Blender: CTR_TaggedIndex< tag_shift, index_mask > Class Template Reference
CTR_TaggedIndex< tag_shift, index_mask > Class Template Reference
#include <CTR_TaggedIndex.h>
Classes
struct greater
Public Member Functions
CTR_TaggedIndex ()
CTR_TaggedIndex (const int val)
CTR_TaggedIndex (const unsigned int val)
CTR_TaggedIndex (const long int val)
CTR_TaggedIndex (const long unsigned int val)
CTR_TaggedIndex (const CTR_TaggedIndex &my_index)
bool operator== (const CTR_TaggedIndex &rhs) const
operator unsigned int () const
operator unsigned long int () const
operator int () const
operator long int () const
bool IsEmpty () const
void Invalidate ()
unsigned int Tag () const
void SetTag (unsigned int tag)
void EmptyTag ()
bool IsEmptyTag () const
Static Public Member Functions
static CTR_TaggedIndex Empty ()
Detailed Description
template<int tag_shift, int index_mask>
class CTR_TaggedIndex< tag_shift, index_mask >
Definition at line 64 of file CTR_TaggedIndex.h.
Constructor & Destructor Documentation
template<int tag_shift, int index_mask> CTR_TaggedIndex< tag_shift, index_mask >::CTR_TaggedIndex () [inline]
Definition at line 66 of file CTR_TaggedIndex.h.
Referenced by CTR_TaggedIndex< 24, 0x00ffffff >::Empty().
template<int tag_shift, int index_mask> CTR_TaggedIndex< tag_shift, index_mask >::CTR_TaggedIndex (const int val) [inline]
Definition at line 72 of file CTR_TaggedIndex.h.
template<int tag_shift, int index_mask> CTR_TaggedIndex< tag_shift, index_mask >::CTR_TaggedIndex (const unsigned int val) [inline]
Definition at line 78 of file CTR_TaggedIndex.h.
template<int tag_shift, int index_mask> CTR_TaggedIndex< tag_shift, index_mask >::CTR_TaggedIndex (const long int val) [inline]
Definition at line 84 of file CTR_TaggedIndex.h.
template<int tag_shift, int index_mask> CTR_TaggedIndex< tag_shift, index_mask >::CTR_TaggedIndex (const long unsigned int val) [inline]
Definition at line 92 of file CTR_TaggedIndex.h.
template<int tag_shift, int index_mask> CTR_TaggedIndex< tag_shift, index_mask >::CTR_TaggedIndex (const CTR_TaggedIndex< tag_shift, index_mask > & my_index) [inline]
Definition at line 111 of file CTR_TaggedIndex.h.
Member Function Documentation
template<int tag_shift, int index_mask> static CTR_TaggedIndex CTR_TaggedIndex< tag_shift, index_mask >::Empty () [inline, static]
Definition at line 157 of file CTR_TaggedIndex.h.
Referenced by CTR_TaggedIndex< 24, 0x00ffffff >::IsEmptyTag().
template<int tag_shift, int index_mask> void CTR_TaggedIndex< tag_shift, index_mask >::EmptyTag () [inline]
Definition at line 183 of file CTR_TaggedIndex.h.
template<int tag_shift, int index_mask> void CTR_TaggedIndex< tag_shift, index_mask >::Invalidate () [inline]
Definition at line 163 of file CTR_TaggedIndex.h.
template<int tag_shift, int index_mask> bool CTR_TaggedIndex< tag_shift, index_mask >::IsEmpty () const [inline]
Definition at line 149 of file CTR_TaggedIndex.h.
template<int tag_shift, int index_mask> bool CTR_TaggedIndex< tag_shift, index_mask >::IsEmptyTag () const [inline]
Definition at line 189 of file CTR_TaggedIndex.h.
template<int tag_shift, int index_mask> CTR_TaggedIndex< tag_shift, index_mask >::operator int () const [inline]
Definition at line 134 of file CTR_TaggedIndex.h.
template<int tag_shift, int index_mask> CTR_TaggedIndex< tag_shift, index_mask >::operator long int () const [inline]
Definition at line 138 of file CTR_TaggedIndex.h.
template<int tag_shift, int index_mask> CTR_TaggedIndex< tag_shift, index_mask >::operator unsigned int () const [inline]
Definition at line 126 of file CTR_TaggedIndex.h.
template<int tag_shift, int index_mask> CTR_TaggedIndex< tag_shift, index_mask >::operator unsigned long int () const [inline]
Definition at line 130 of file CTR_TaggedIndex.h.
template<int tag_shift, int index_mask> bool CTR_TaggedIndex< tag_shift, index_mask >::operator== (const CTR_TaggedIndex< tag_shift, index_mask > & rhs) const [inline]
Definition at line 119 of file CTR_TaggedIndex.h.
template<int tag_shift, int index_mask> void CTR_TaggedIndex< tag_shift, index_mask >::SetTag (unsigned int tag) [inline]
Definition at line 176 of file CTR_TaggedIndex.h.
Referenced by LOD_Edge::SetOpenTag(), BSP_MEdge::SetOpenTag(), LOD_TriFace::SetOpenTag(), LOD_TriFace::SetSelectTag(), LOD_Edge::SetSelectTag(), and BSP_MEdge::SetSelectTag().
template<int tag_shift, int index_mask> unsigned int CTR_TaggedIndex< tag_shift, index_mask >::Tag () const [inline]
Definition at line 170 of file CTR_TaggedIndex.h.
Referenced by CTR_TaggedIndex< 24, 0x00ffffff >::IsEmptyTag(), LOD_Edge::OpenTag(), LOD_TriFace::OpenTag(), and BSP_MEdge::OpenTag().
The documentation for this class was generated from the following file:
CTR_TaggedIndex.h