Blender: CcdShapeConstructionInfo Class Reference
CcdShapeConstructionInfo Class Reference
#include <CcdPhysicsController.h>
Classes
struct UVco
Public Member Functions
CcdShapeConstructionInfo ()
~CcdShapeConstructionInfo ()
CcdShapeConstructionInfo * AddRef ()
int Release ()
bool IsUnused (void)
void AddShape (CcdShapeConstructionInfo *shapeInfo)
btTriangleMeshShape * GetMeshShape (void)
CcdShapeConstructionInfo * GetChildShape (int i)
int FindChildShape (CcdShapeConstructionInfo *shapeInfo, void *userData)
bool RemoveChildShape (int i)
bool SetMesh (class RAS_MeshObject *mesh, struct DerivedMesh *dm, bool polytope)
RAS_MeshObject * GetMesh (void)
bool UpdateMesh (class KX_GameObject *gameobj, class RAS_MeshObject *mesh)
bool SetProxy (CcdShapeConstructionInfo *shapeInfo)
CcdShapeConstructionInfo * GetProxy (void)
btCollisionShape * CreateBulletShape (btScalar margin, bool useGimpact=false, bool useBvh=true)
void setVertexWeldingThreshold1 (float threshold)
Static Public Member Functions
static CcdShapeConstructionInfo * FindMesh (class RAS_MeshObject *mesh, struct DerivedMesh *dm, bool polytope)
Public Attributes
PHY_ShapeType m_shapeType
btScalar m_radius
btScalar m_height
btVector3 m_halfExtend
btTransform m_childTrans
btVector3 m_childScale
void * m_userData
btAlignedObjectArray< btScalar > m_vertexArray
std::vector< int > m_polygonIndexArray
std::vector< int > m_triFaceArray
std::vector< UVco > m_triFaceUVcoArray
Protected Attributes
int m_refCount
RAS_MeshObject * m_meshObject
btBvhTriangleMeshShape * m_unscaledShape
std::vector
< CcdShapeConstructionInfo * > m_shapeArray
bool m_forceReInstance
float m_weldingThreshold1
CcdShapeConstructionInfo * m_shapeProxy
Static Protected Attributes
static std::map
< RAS_MeshObject
*, CcdShapeConstructionInfo * > m_meshShapeMap
Detailed Description
Definition at line 61 of file CcdPhysicsController.h.
Constructor & Destructor Documentation
CcdShapeConstructionInfo::CcdShapeConstructionInfo () [inline]
Definition at line 71 of file CcdPhysicsController.h.
References m_childTrans, and btTransform::setIdentity().
CcdShapeConstructionInfo::~CcdShapeConstructionInfo ()
Definition at line 2171 of file CcdPhysicsController.cpp.
References btAlignedObjectArray< T >::clear(), DeleteBulletShape(), m_meshObject, m_meshShapeMap, m_shapeArray, m_shapeProxy, m_shapeType, m_unscaledShape, m_vertexArray, NULL, PHY_SHAPE_MESH, PHY_SHAPE_PROXY, and Release().
Member Function Documentation
CcdShapeConstructionInfo* CcdShapeConstructionInfo::AddRef () [inline]
Definition at line 90 of file CcdPhysicsController.h.
References m_refCount.
Referenced by AddShape(), CcdPhysicsController::CcdPhysicsController(), and CcdPhysicsController::PostProcessReplica().
void CcdShapeConstructionInfo::AddShape (CcdShapeConstructionInfo * shapeInfo)
Definition at line 2165 of file CcdPhysicsController.cpp.
References AddRef(), and m_shapeArray.
btCollisionShape * CcdShapeConstructionInfo::CreateBulletShape (btScalar margin, bool useGimpact = false, bool useBvh = true)
enable welding, only for the objects that need it (such as soft bodies)
Definition at line 2020 of file CcdPhysicsController.cpp.
References btTriangleMesh::addTriangle(), CreateBulletShape(), DeleteBulletShape(), i, m_forceReInstance, m_halfExtend, m_height, m_polygonIndexArray, m_radius, m_shapeArray, m_shapeProxy, m_shapeType, m_triFaceArray, m_unscaledShape, m_vertexArray, btTriangleMesh::m_weldingThreshold, m_weldingThreshold1, NULL, PHY_SHAPE_BOX, PHY_SHAPE_CAPSULE, PHY_SHAPE_COMPOUND, PHY_SHAPE_CONE, PHY_SHAPE_CYLINDER, PHY_SHAPE_MESH, PHY_SHAPE_POLYTOPE, PHY_SHAPE_PROXY, PHY_SHAPE_SPHERE, btCollisionShape::setLocalScaling(), btGImpactMeshShape::setMargin(), btCollisionShape::setMargin(), btAlignedObjectArray< T >::size(), and btGImpactShapeInterface::updateBound().
Referenced by CreateBulletShape(), CcdPhysicsController::GetReplica(), and CcdPhysicsController::PostProcessReplica().
int CcdShapeConstructionInfo::FindChildShape (CcdShapeConstructionInfo * shapeInfo, void * userData) [inline]
Definition at line 122 of file CcdPhysicsController.h.
References i, m_shapeArray, m_shapeProxy, m_shapeType, m_userData, NULL, and PHY_SHAPE_PROXY.
CcdShapeConstructionInfo * CcdShapeConstructionInfo::FindMesh (class RAS_MeshObject * mesh, struct DerivedMesh * dm, bool polytope) [static]
Definition at line 1399 of file CcdPhysicsController.cpp.
References m_meshShapeMap, and NULL.
CcdShapeConstructionInfo* CcdShapeConstructionInfo::GetChildShape (int i) [inline]
Definition at line 115 of file CcdPhysicsController.h.
References m_shapeArray, and NULL.
Referenced by CcdPhysicsEnvironment::rayTest().
RAS_MeshObject* CcdShapeConstructionInfo::GetMesh (void) [inline]
Definition at line 150 of file CcdPhysicsController.h.
References m_meshObject.
Referenced by CcdPhysicsEnvironment::rayTest().
btTriangleMeshShape* CcdShapeConstructionInfo::GetMeshShape (void) [inline]
Definition at line 111 of file CcdPhysicsController.h.
References m_unscaledShape.
Referenced by GetHitTriangle().
CcdShapeConstructionInfo* CcdShapeConstructionInfo::GetProxy (void) [inline]
Definition at line 159 of file CcdPhysicsController.h.
References m_shapeProxy.
bool CcdShapeConstructionInfo::IsUnused (void) [inline]
Definition at line 104 of file CcdPhysicsController.h.
References m_meshObject, m_shapeArray, m_shapeProxy, and NULL.
Referenced by SetMesh(), and SetProxy().
int CcdShapeConstructionInfo::Release () [inline]
Definition at line 96 of file CcdPhysicsController.h.
References m_refCount.
Referenced by CcdPhysicsController::~CcdPhysicsController(), and ~CcdShapeConstructionInfo().
bool CcdShapeConstructionInfo::RemoveChildShape (int i) [inline]
Definition at line 138 of file CcdPhysicsController.h.
References m_shapeArray.
bool CcdShapeConstructionInfo::SetMesh (class RAS_MeshObject * mesh, struct DerivedMesh * dm, bool polytope)
Definition at line 1411 of file CcdPhysicsController.cpp.
References assert, CD_MTFACE, CD_ORIGINDEX, CDDM_from_mesh(), btAlignedObjectArray< T >::clear(), MVert::co, DM_ensure_tessface(), RAS_MeshObject::GetMesh(), DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, RAS_MeshObject::GetPolygon(), DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVertArray, RAS_MeshObject::HasColliderPolygon(), RAS_Polygon::IsCollider(), IsUnused(), m_meshObject, m_meshShapeMap, m_polygonIndexArray, m_shapeType, m_triFaceArray, m_triFaceUVcoArray, m_vertexArray, NULL, PHY_SHAPE_MESH, PHY_SHAPE_NONE, PHY_SHAPE_POLYTOPE, DerivedMesh::release, btAlignedObjectArray< T >::resize(), btAlignedObjectArray< T >::size(), MTFace::uv, CcdShapeConstructionInfo::UVco::uv, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
bool CcdShapeConstructionInfo::SetProxy (CcdShapeConstructionInfo * shapeInfo)
Definition at line 2009 of file CcdPhysicsController.cpp.
References assert, IsUnused(), m_shapeProxy, m_shapeType, NULL, and PHY_SHAPE_PROXY.
void CcdShapeConstructionInfo::setVertexWeldingThreshold1 (float threshold) [inline]
Definition at line 187 of file CcdPhysicsController.h.
References m_weldingThreshold1.
bool CcdShapeConstructionInfo::UpdateMesh (class KX_GameObject * gameobj, class RAS_MeshObject * mesh)
Definition at line 1688 of file CcdPhysicsController.cpp.
References CD_MTFACE, CD_ORIGINDEX, MVert::co, CustomData_has_layer(), DerivedMesh::faceData, KX_GameObject::GetDeformer(), KX_GameObject::GetMesh(), KX_GameObject::GetMeshCount(), DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, RAS_TexVert::getOrigIndex(), RAS_Deformer::GetPhysicsMesh(), RAS_MeshObject::GetPolygon(), RAS_Deformer::GetRasMesh(), DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceDataArray, RAS_Deformer::GetTransVerts(), DerivedMesh::getVertArray, RAS_Polygon::GetVertex(), RAS_MeshObject::GetVertexLocation(), i, RAS_Polygon::IsCollider(), m_forceReInstance, m_meshObject, m_polygonIndexArray, m_shapeType, RAS_MeshObject::m_sharedvertex_map, m_triFaceArray, m_triFaceUVcoArray, m_unscaledShape, m_vertexArray, DerivedMesh::needsFree, NULL, RAS_MeshObject::NumPolygons(), p, PHY_SHAPE_MESH, DerivedMesh::release, btAlignedObjectArray< T >::resize(), btAlignedObjectArray< T >::size(), TF_DYNAMIC, CcdShapeConstructionInfo::UVco::uv, MFace::v1, MFace::v4, and RAS_Polygon::VertexCount().
Member Data Documentation
btVector3 CcdShapeConstructionInfo::m_childScale
Definition at line 172 of file CcdPhysicsController.h.
btTransform CcdShapeConstructionInfo::m_childTrans
Definition at line 171 of file CcdPhysicsController.h.
Referenced by CcdShapeConstructionInfo().
bool CcdShapeConstructionInfo::m_forceReInstance [protected]
Definition at line 199 of file CcdPhysicsController.h.
Referenced by CreateBulletShape(), and UpdateMesh().
btVector3 CcdShapeConstructionInfo::m_halfExtend
Definition at line 170 of file CcdPhysicsController.h.
Referenced by CreateBulletShape().
btScalar CcdShapeConstructionInfo::m_height
Definition at line 169 of file CcdPhysicsController.h.
Referenced by CreateBulletShape().
RAS_MeshObject* CcdShapeConstructionInfo::m_meshObject [protected]
Definition at line 195 of file CcdPhysicsController.h.
Referenced by GetMesh(), IsUnused(), SetMesh(), UpdateMesh(), and ~CcdShapeConstructionInfo().
std::map< RAS_MeshObject *, CcdShapeConstructionInfo * > CcdShapeConstructionInfo::m_meshShapeMap [static, protected]
Definition at line 192 of file CcdPhysicsController.h.
Referenced by FindMesh(), SetMesh(), and ~CcdShapeConstructionInfo().
std::vector<int> CcdShapeConstructionInfo::m_polygonIndexArray
Definition at line 177 of file CcdPhysicsController.h.
Referenced by CreateBulletShape(), CcdPhysicsEnvironment::rayTest(), SetMesh(), and UpdateMesh().
btScalar CcdShapeConstructionInfo::m_radius
Definition at line 168 of file CcdPhysicsController.h.
Referenced by CreateBulletShape().
int CcdShapeConstructionInfo::m_refCount [protected]
Definition at line 193 of file CcdPhysicsController.h.
Referenced by AddRef(), and Release().
std::vector<CcdShapeConstructionInfo*> CcdShapeConstructionInfo::m_shapeArray [protected]
Definition at line 198 of file CcdPhysicsController.h.
Referenced by AddShape(), CreateBulletShape(), FindChildShape(), GetChildShape(), IsUnused(), RemoveChildShape(), and ~CcdShapeConstructionInfo().
CcdShapeConstructionInfo* CcdShapeConstructionInfo::m_shapeProxy [protected]
Definition at line 201 of file CcdPhysicsController.h.
Referenced by CreateBulletShape(), FindChildShape(), GetProxy(), IsUnused(), SetProxy(), and ~CcdShapeConstructionInfo().
PHY_ShapeType CcdShapeConstructionInfo::m_shapeType
Definition at line 167 of file CcdPhysicsController.h.
Referenced by CreateBulletShape(), FindChildShape(), SetMesh(), SetProxy(), UpdateMesh(), and ~CcdShapeConstructionInfo().
std::vector<int> CcdShapeConstructionInfo::m_triFaceArray
Definition at line 181 of file CcdPhysicsController.h.
Referenced by CreateBulletShape(), SetMesh(), and UpdateMesh().
std::vector<UVco> CcdShapeConstructionInfo::m_triFaceUVcoArray
Definition at line 184 of file CcdPhysicsController.h.
Referenced by CcdPhysicsEnvironment::rayTest(), SetMesh(), and UpdateMesh().
btBvhTriangleMeshShape* CcdShapeConstructionInfo::m_unscaledShape [protected]
Definition at line 196 of file CcdPhysicsController.h.
Referenced by CreateBulletShape(), GetMeshShape(), UpdateMesh(), and ~CcdShapeConstructionInfo().
void* CcdShapeConstructionInfo::m_userData
Definition at line 173 of file CcdPhysicsController.h.
Referenced by FindChildShape().
btAlignedObjectArray<btScalar> CcdShapeConstructionInfo::m_vertexArray
Definition at line 174 of file CcdPhysicsController.h.
Referenced by CreateBulletShape(), SetMesh(), UpdateMesh(), and ~CcdShapeConstructionInfo().
float CcdShapeConstructionInfo::m_weldingThreshold1 [protected]
Definition at line 200 of file CcdPhysicsController.h.
Referenced by CreateBulletShape(), and setVertexWeldingThreshold1().
The documentation for this class was generated from the following files:
CcdPhysicsController.h
CcdPhysicsController.cpp