Blender: BsdfNode Class Reference
BsdfNode Class Reference
#include <nodes.h>
Public Member Functions
void compile (SVMCompiler &compiler, ShaderInput *param1, ShaderInput *param2)
Public Attributes
ClosureType closure
Detailed Description
Definition at line 178 of file nodes.h.
Member Function Documentation
void BsdfNode::compile (SVMCompiler & compiler, ShaderInput * param1, ShaderInput * param2)
Definition at line 1048 of file nodes.cpp.
References __float_as_int(), SVMCompiler::add_node(), closure, SVMCompiler::closure_mix_weight_offset(), SVMCompiler::encode_uchar4(), ShaderNode::input(), ShaderInput::link, NODE_CLOSURE_BSDF, NODE_CLOSURE_SET_WEIGHT, NODE_CLOSURE_WEIGHT, SVMCompiler::stack_assign(), ShaderInput::stack_offset, SVM_STACK_INVALID, ShaderInput::value, and float3::x.
Referenced by SVMCompiler::compile().
Member Data Documentation
ClosureType BsdfNode::closure
Definition at line 184 of file nodes.h.
Referenced by compile().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp