Blender: MT_Transform Class Reference
MT_Transform Class Reference
#include <MT_Transform.h>
Public Member Functions
MT_Transform ()
MT_Transform (const float *m)
MT_Transform (const double *m)
MT_Transform (const MT_Point3 &p, const MT_Quaternion &q)
MT_Transform (const MT_Point3 &p, const MT_Matrix3x3 &m)
MT_Point3 operator() (const MT_Point3 &p) const
MT_Vector3 operator() (const MT_Vector3 &p) const
MT_Point3 operator* (const MT_Point3 &p) const
MT_Vector3 operator* (const MT_Vector3 &p) const
MT_Matrix3x3 & getBasis ()
const MT_Matrix3x3 & getBasis () const
MT_Point3 & getOrigin ()
const MT_Point3 & getOrigin () const
MT_Quaternion getRotation () const
void setValue (const float *m)
void setValue (const double *m)
void setOrigin (const MT_Point3 &origin)
void setBasis (const MT_Matrix3x3 &basis)
void setRotation (const MT_Quaternion &q)
void getValue (float *m) const
void getValue (double *m) const
void setIdentity ()
MT_Transform & operator*= (const MT_Transform &t)
void translate (const MT_Vector3 &v)
void rotate (const MT_Quaternion &q)
void scale (MT_Scalar x, MT_Scalar y, MT_Scalar z)
void invert (const MT_Transform &t)
void mult (const MT_Transform &t1, const MT_Transform &t2)
void multInverseLeft (const MT_Transform &t1, const MT_Transform &t2)
Static Public Member Functions
static MT_Transform Identity ()
Friends
MT_Transform operator* (const MT_Transform &t1, const MT_Transform &t2)
Detailed Description
Definition at line 60 of file MT_Transform.h.
Constructor & Destructor Documentation
MT_Transform::MT_Transform () [inline]
Definition at line 62 of file MT_Transform.h.
MT_Transform::MT_Transform (const float * m) [inline]
Definition at line 63 of file MT_Transform.h.
References setValue().
MT_Transform::MT_Transform (const double * m) [inline]
Definition at line 64 of file MT_Transform.h.
References setValue().
MT_Transform::MT_Transform (const MT_Point3 & p, const MT_Quaternion & q) [inline]
Definition at line 65 of file MT_Transform.h.
References setOrigin(), and setRotation().
MT_Transform::MT_Transform (const MT_Point3 & p, const MT_Matrix3x3 & m) [inline]
Definition at line 72 of file MT_Transform.h.
References setBasis(), and setOrigin().
Member Function Documentation
MT_Matrix3x3& MT_Transform::getBasis () [inline]
Definition at line 108 of file MT_Transform.h.
Referenced by IK_QRevoluteSegment::Axis(), IK_QTranslateSegment::Axis(), IK_QSphericalSegment::Axis(), IK_QSwingSegment::Axis(), IK_QElbowSegment::Axis(), KX_LightObject::BindShadowBuffer(), IK_QOrientationTask::ComputeJacobian(), MT_Matrix4x4::MT_Matrix4x4(), IK_QJacobianSolver::Solve(), RAS_MeshObject::SortPolygons(), KX_RadarSensor::SynchronizeTransform(), and IK_QSegment::UpdateTransform().
const MT_Matrix3x3& MT_Transform::getBasis () const [inline]
Definition at line 109 of file MT_Transform.h.
MT_Point3& MT_Transform::getOrigin () [inline]
Definition at line 110 of file MT_Transform.h.
Referenced by KX_LightObject::BindShadowBuffer(), IK_QSegment::GlobalEnd(), MT_Matrix4x4::MT_Matrix4x4(), IK_QSegment::Scale(), KX_RadarSensor::SynchronizeTransform(), and IK_QSegment::UpdateTransform().
const MT_Point3& MT_Transform::getOrigin () const [inline]
Definition at line 111 of file MT_Transform.h.
MT_Quaternion MT_Transform::getRotation () const [inline]
Definition at line 112 of file MT_Transform.h.
References MT_Matrix3x3::getRotation().
void MT_Transform::getValue (float * m) const
Definition at line 68 of file MT_Transform.cpp.
References MT_Tuple3::getValue(), and MT_Matrix3x3::getValue().
Referenced by KX_BlenderRenderTools::applyLights(), GPC_RenderTools::applyLights(), and KX_GameObject::GetOpenGLMatrix().
void MT_Transform::getValue (double * m) const
Definition at line 74 of file MT_Transform.cpp.
References MT_Tuple3::getValue(), and MT_Matrix3x3::getValue().
RotationVel RotationVel::Identity () [inline, static]
Definition at line 79 of file MT_Transform.h.
References setIdentity().
Referenced by BL_ConvertBlenderObjects().
void MT_Transform::invert (const MT_Transform & t)
Definition at line 108 of file MT_Transform.cpp.
References MT_Matrix3x3::inverse(), MT_dot(), MT_Tuple3::setValue(), and MT_Matrix3x3::transposed().
Referenced by KX_LightObject::BindShadowBuffer(), KX_Camera::GetWorldToCamera(), KX_KetsjiEngine::PostProcessScene(), and KX_NavMeshObject::TransformToLocalCoords().
void MT_Transform::mult (const MT_Transform & t1, const MT_Transform & t2)
Definition at line 118 of file MT_Transform.cpp.
void MT_Transform::multInverseLeft (const MT_Transform & t1, const MT_Transform & t2)
Definition at line 124 of file MT_Transform.cpp.
References MT_Matrix3x3::inverse(), and MT_multTransposeLeft().
MT_Point3 MT_Transform::operator() (const MT_Point3 & p) const [inline]
Definition at line 87 of file MT_Transform.h.
References MT_dot().
MT_Vector3 MT_Transform::operator() (const MT_Vector3 & p) const [inline]
Definition at line 93 of file MT_Transform.h.
References MT_dot().
MT_Point3 MT_Transform::operator* (const MT_Point3 & p) const [inline]
Definition at line 99 of file MT_Transform.h.
References p.
MT_Vector3 MT_Transform::operator* (const MT_Vector3 & p) const [inline]
Definition at line 103 of file MT_Transform.h.
References p.
MT_Transform & MT_Transform::operator*= (const MT_Transform & t)
Definition at line 80 of file MT_Transform.cpp.
void MT_Transform::rotate (const MT_Quaternion & q)
Definition at line 92 of file MT_Transform.cpp.
Referenced by KX_RadarSensor::SynchronizeTransform().
void MT_Transform::scale (MT_Scalar x, MT_Scalar y, MT_Scalar z)
Definition at line 97 of file MT_Transform.cpp.
References MT_Matrix3x3::scale().
Referenced by KX_GameObject::GetOpenGLMatrix().
void MT_Transform::setBasis (const MT_Matrix3x3 & basis) [inline]
Definition at line 122 of file MT_Transform.h.
Referenced by KX_GameObject::GetOpenGLMatrix(), MT_Transform(), KX_RadarSensor::SynchronizeTransform(), and IK_QSegment::UpdateTransform().
void MT_Transform::setIdentity ()
Definition at line 102 of file MT_Transform.cpp.
References MT_Matrix3x3::setIdentity(), and MT_Tuple3::setValue().
Referenced by SG_Tree::get(), Identity(), IK_QJacobianSolver::IK_QJacobianSolver(), and RAS_OpenGLRasterizer::SetViewMatrix().
void MT_Transform::setOrigin (const MT_Point3 & origin) [inline]
Definition at line 117 of file MT_Transform.h.
Referenced by KX_GameObject::GetOpenGLMatrix(), MT_Transform(), KX_RadarSensor::SynchronizeTransform(), and IK_QSegment::UpdateTransform().
void MT_Transform::setRotation (const MT_Quaternion & q) [inline]
Definition at line 127 of file MT_Transform.h.
References MT_Matrix3x3::setRotation().
Referenced by MT_Transform().
void MT_Transform::setValue (const float * m)
Definition at line 56 of file MT_Transform.cpp.
References MT_Matrix3x3::setValue(), and MT_Tuple3::setValue().
Referenced by MT_Transform().
void MT_Transform::setValue (const double * m)
Definition at line 62 of file MT_Transform.cpp.
References MT_Matrix3x3::setValue(), and MT_Tuple3::setValue().
void MT_Transform::translate (const MT_Vector3 & v)
Translate the origin of the transform according to the vector.
Parameters:
v The vector to translate over. The vector is specified in the coordinate system of the transform itself.
Definition at line 87 of file MT_Transform.cpp.
Referenced by RAS_OpenGLRasterizer::SetViewMatrix(), KX_RadarSensor::SynchronizeTransform(), and IK_QSegment::UpdateTransform().
Friends And Related Function Documentation
MT_Transform operator* (const MT_Transform & t1, const MT_Transform & t2) [friend]
Definition at line 183 of file MT_Transform.h.
The documentation for this class was generated from the following files:
MT_Transform.h
frameacc.inl
frames.inl
framevel.inl
MT_Transform.cpp