Blender: bmo_primitive.c File Reference
bmo_primitive.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "bmesh.h"
#include "intern/bmesh_private.h"
#include "intern/bmesh_operators_private.h"
Defines
#define VERT_MARK 1
#define EDGE_ORIG 1
#define EDGE_MARK 2
#define FACE_MARK 1
#define FACE_NEW 2
Functions
void bmo_create_grid_exec (BMesh *bm, BMOperator *op)
void bmo_create_uvsphere_exec (BMesh *bm, BMOperator *op)
void bmo_create_icosphere_exec (BMesh *bm, BMOperator *op)
void bmo_create_monkey_exec (BMesh *bm, BMOperator *op)
void bmo_create_circle_exec (BMesh *bm, BMOperator *op)
void bmo_create_cone_exec (BMesh *bm, BMOperator *op)
void bmo_create_cube_exec (BMesh *bm, BMOperator *op)
Variables
static float icovert [12][3]
static short icoface [20][3]
static int monkeyo = 4
static int monkeynv = 271
static int monkeynf = 250
static signed char monkeyv [271][3]
static signed char monkeyf [250][4]
Detailed Description
Definition in file bmo_primitive.c.
Define Documentation
#define EDGE_MARK 2
Definition at line 223 of file bmo_primitive.c.
Referenced by bmo_create_icosphere_exec().
#define EDGE_ORIG 1
Definition at line 222 of file bmo_primitive.c.
Referenced by bmo_create_grid_exec(), and bmo_create_uvsphere_exec().
#define FACE_MARK 1
Definition at line 225 of file bmo_primitive.c.
Referenced by bmo_create_icosphere_exec().
#define FACE_NEW 2
Definition at line 226 of file bmo_primitive.c.
Referenced by bmo_create_circle_exec(), and bmo_create_cone_exec().
#define VERT_MARK 1
Definition at line 220 of file bmo_primitive.c.
Referenced by bmo_create_circle_exec(), bmo_create_cone_exec(), bmo_create_cube_exec(), bmo_create_grid_exec(), bmo_create_icosphere_exec(), bmo_create_monkey_exec(), and bmo_create_uvsphere_exec().
Function Documentation
void bmo_create_circle_exec (BMesh * bm, BMOperator * op)
Definition at line 500 of file bmo_primitive.c.
References BM_edge_create(), BM_face_create_quad_tri(), BM_VERT, BM_vert_create(), BMO_elem_flag_enable, BMO_op_callf(), BMO_slot_bool_get(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), BMO_slot_mat4_get(), cosf, FACE_NEW, FALSE, M_PI, mul_m4_v3(), NULL, sinf, and VERT_MARK.
void bmo_create_cone_exec (BMesh * bm, BMOperator * op)
Definition at line 571 of file bmo_primitive.c.
References BM_face_create_quad_tri(), BM_VERT, BM_vert_create(), BMO_elem_flag_enable, BMO_op_callf(), BMO_slot_bool_get(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), BMO_slot_mat4_get(), cosf, FACE_NEW, FALSE, M_PI, mul_m4_v3(), NULL, sinf, and VERT_MARK.
void bmo_create_cube_exec (BMesh * bm, BMOperator * op)
Definition at line 667 of file bmo_primitive.c.
References BM_face_create_quad_tri(), BM_VERT, BM_vert_create(), BMO_elem_flag_enable, BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_mat4_get(), FALSE, mul_m4_v3(), NULL, and VERT_MARK.
void bmo_create_grid_exec (BMesh * bm, BMOperator * op)
Definition at line 228 of file bmo_primitive.c.
References BM_edge_create(), BM_VERT, BM_vert_create(), BMO_elem_flag_enable, BMO_op_callf(), BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), BMO_slot_mat4_get(), EDGE_ORIG, mul_m4_v3(), mul_mat3_m4_v3(), NULL, TRUE, and VERT_MARK.
void bmo_create_icosphere_exec (BMesh * bm, BMOperator * op)
Definition at line 380 of file bmo_primitive.c.
References BM_EDGE, BM_face_create_quad_tri(), BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_VERT, BM_vert_create(), BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), BMO_slot_mat4_get(), BMVert::co, BMLoop::e, EDGE_MARK, FACE_MARK, FALSE, icoface, icovert, mul_m4_v3(), NULL, TRUE, and VERT_MARK.
void bmo_create_monkey_exec (BMesh * bm, BMOperator * op)
Definition at line 452 of file bmo_primitive.c.
References BM_face_create_quad_tri(), BM_VERT, BM_vert_create(), BMO_elem_flag_enable, BMO_slot_buffer_from_enabled_flag(), BMO_slot_mat4_get(), co, BMVert::co, fabsf, FALSE, i, MEM_freeN(), MEM_mallocN(), monkeyf, monkeynf, monkeynv, monkeyo, monkeyv, mul_m4_v3(), NULL, and VERT_MARK.
void bmo_create_uvsphere_exec (BMesh * bm, BMOperator * op)
Definition at line 291 of file bmo_primitive.c.
References BM_edge_create(), BM_ITER_MESH, BM_VERT, BM_vert_create(), BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_op_callf(), BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), BMO_slot_mat4_get(), BMVert::co, cosf, EDGE_ORIG, FALSE, len(), len_v3v3(), M_PI, MIN2, mul_m4_v3(), mul_v3_m3v3(), NULL, quat_to_mat3(), sinf, and VERT_MARK.
Variable Documentation
short icoface[20][3] [static]
Initial value:
 {
    {0,1,2},
    {1,0,5},
    {0,2,3},
    {0,3,4},
    {0,4,5},
    {1,5,10},
    {2,1,6},
    {3,2,7},
    {4,3,8},
    {5,4,9},
    {1,10,6},
    {2,6,7},
    {3,7,8},
    {4,8,9},
    {5,9,10},
    {6,10,11},
    {7,6,11},
    {8,7,11},
    {9,8,11},
    {10,9,11}
}
Definition at line 53 of file bmo_primitive.c.
Referenced by bmo_create_icosphere_exec().
float icovert[12][3] [static]
Initial value:
 {
    {0.0f,0.0f,-200.0f},
    {144.72f, -105.144f,-89.443f},
    {-55.277f, -170.128,-89.443f},
    {-178.885f,0.0f,-89.443f},
    {-55.277f,170.128f,-89.443f},
    {144.72f,105.144f,-89.443f},
    {55.277f,-170.128f,89.443f},
    {-144.72f,-105.144f,89.443f},
    {-144.72f,105.144f,89.443f},
    {55.277f,170.128f,89.443f},
    {178.885f,0.0f,89.443f},
    {0.0f,0.0f,200.0f}
}
Definition at line 38 of file bmo_primitive.c.
Referenced by bmo_create_icosphere_exec().
signed char monkeyf[250][4] [static]
Definition at line 154 of file bmo_primitive.c.
Referenced by bmo_create_monkey_exec().
int monkeynf = 250 [static]
Definition at line 82 of file bmo_primitive.c.
Referenced by bmo_create_monkey_exec().
int monkeynv = 271 [static]
Definition at line 81 of file bmo_primitive.c.
Referenced by bmo_create_monkey_exec().
int monkeyo = 4 [static]
Definition at line 80 of file bmo_primitive.c.
Referenced by bmo_create_monkey_exec().
signed char monkeyv[271][3] [static]
Definition at line 83 of file bmo_primitive.c.
Referenced by bmo_create_monkey_exec().