Blender: bpy.h File Reference
bpy.h File Reference
Python RNA and Operators
Functions
void BPy_init_modules (void)
void BPY_atexit_register (void)
void BPY_atexit_unregister (void)
Variables
PyObject * bpy_package_py
Detailed Description
Definition in file bpy.h.
Function Documentation
void BPY_atexit_register (void)
Definition at line 81 of file bpy_interface_atexit.c.
References atexit_func_call(), BLI_assert, and NULL.
Referenced by BPY_python_start().
void BPY_atexit_unregister (void)
Definition at line 90 of file bpy_interface_atexit.c.
References atexit_func_call(), BLI_assert, and NULL.
Referenced by BPY_python_end().
void BPy_init_modules (void)
Definition at line 238 of file bpy.c.
References BLENDER_SYSTEM_SCRIPTS, BLI_get_folder(), BPY_app_struct(), bpy_context_module, BPy_GetContext(), bpy_import_test(), bpy_lib_init(), BPY_operator_module(), bpy_package_py, BPY_rna_init(), BPY_rna_module(), BPY_rna_props(), BPY_rna_types(), IDProp_Init_Types(), meth_bpy_register_class, meth_bpy_unregister_class, mod(), NULL, pyrna_struct_CreatePyObject(), pyrna_struct_meta_idprop_Type, RNA_Context, and RNA_pointer_create().
Referenced by BPY_python_start().
Variable Documentation
PyObject* bpy_package_py
Definition at line 61 of file bpy.c.
Referenced by BPy_init_modules().