Blender: AUD_EffectFactory Class Reference
AUD_EffectFactory Class Reference
#include <AUD_EffectFactory.h>
Public Member Functions
AUD_EffectFactory (AUD_Reference< AUD_IFactory > factory)
virtual ~AUD_EffectFactory ()
AUD_Reference< AUD_IFactory > getFactory () const
Protected Member Functions
AUD_Reference< AUD_IReader > getReader () const
Protected Attributes
AUD_Reference< AUD_IFactory > m_factory
Detailed Description
This factory is a base class for all effect factories that take one other factory as input.
Definition at line 39 of file AUD_EffectFactory.h.
Constructor & Destructor Documentation
AUD_EffectFactory::AUD_EffectFactory (AUD_Reference< AUD_IFactory > factory)
Creates a new factory.
Parameters:
factory The input factory.
Definition at line 33 of file AUD_EffectFactory.cpp.
References m_factory.
AUD_EffectFactory::~AUD_EffectFactory () [virtual]
Destroys the factory.
Definition at line 38 of file AUD_EffectFactory.cpp.
Member Function Documentation
AUD_Reference< AUD_IFactory > AUD_EffectFactory::getFactory () const
Returns the saved factory.
Returns:
The factory or NULL if there has no factory been saved.
Definition at line 42 of file AUD_EffectFactory.cpp.
References m_factory.
AUD_Reference<AUD_IReader> AUD_EffectFactory::getReader () const [inline, protected]
Returns the reader created out of the factory. This method can be used for the createReader function of the implementing classes.
Returns:
The reader created out of the factory.
Definition at line 58 of file AUD_EffectFactory.h.
References m_factory.
Referenced by AUD_SumFactory::createReader(), AUD_EnvelopeFactory::createReader(), AUD_DynamicIIRFilterFactory::createReader(), AUD_FaderFactory::createReader(), AUD_LoopFactory::createReader(), AUD_RectifyFactory::createReader(), AUD_SquareFactory::createReader(), AUD_ReverseFactory::createReader(), AUD_DelayFactory::createReader(), AUD_PingPongFactory::createReader(), AUD_IIRFilterFactory::createReader(), AUD_VolumeFactory::createReader(), AUD_BandPassFactory::createReader(), AUD_AccumulatorFactory::createReader(), AUD_PitchFactory::createReader(), and AUD_LimiterFactory::createReader().
Member Data Documentation
AUD_Reference<AUD_IFactory> AUD_EffectFactory::m_factory [protected]
If there is no reader it is created out of this factory.
Definition at line 50 of file AUD_EffectFactory.h.
Referenced by AUD_EffectFactory(), AUD_PingPongFactory::createReader(), getFactory(), and getReader().
The documentation for this class was generated from the following files:
AUD_EffectFactory.h
AUD_EffectFactory.cpp