Blender: space_outliner.c File Reference
space_outliner.c File Reference
outliner space
#include <string.h>
#include <stdio.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "ED_space_api.h"
#include "ED_screen.h"
#include "WM_api.h"
#include "WM_types.h"
#include "BIF_gl.h"
#include "RNA_access.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "outliner_intern.h"
Functions
static void outliner_main_area_init (wmWindowManager *wm, ARegion *ar)
static int outliner_parent_drop_poll (bContext *C, wmDrag *drag, wmEvent *event)
static void outliner_parent_drop_copy (wmDrag *drag, wmDropBox *drop)
static int outliner_parent_clear_poll (bContext *C, wmDrag *drag, wmEvent *event)
static void outliner_parent_clear_copy (wmDrag *drag, wmDropBox *drop)
static void outliner_dropboxes (void)
static void outliner_main_area_draw (const bContext *C, ARegion *ar)
static void outliner_main_area_free (ARegion *UNUSED(ar))
static void outliner_main_area_listener (ARegion *ar, wmNotifier *wmn)
static void outliner_header_area_init (wmWindowManager *UNUSED(wm), ARegion *ar)
static void outliner_header_area_draw (const bContext *C, ARegion *ar)
static void outliner_header_area_free (ARegion *UNUSED(ar))
static void outliner_header_area_listener (ARegion *ar, wmNotifier *wmn)
static SpaceLink * outliner_new (const bContext *UNUSED(C))
static void outliner_free (SpaceLink *sl)
static void outliner_init (wmWindowManager *UNUSED(wm), ScrArea *UNUSED(sa))
static SpaceLink * outliner_duplicate (SpaceLink *sl)
void ED_spacetype_outliner (void)
Detailed Description
Definition in file space_outliner.c.
Function Documentation
void ED_spacetype_outliner (void)
Definition at line 377 of file space_outliner.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::dropboxes, SpaceType::duplicate, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, ARegionType::free, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, outliner_dropboxes(), outliner_duplicate(), outliner_free(), outliner_header_area_draw(), outliner_header_area_free(), outliner_header_area_init(), outliner_header_area_listener(), outliner_init(), outliner_keymap(), outliner_main_area_draw(), outliner_main_area_free(), outliner_main_area_init(), outliner_main_area_listener(), outliner_new(), outliner_operatortypes(), ARegionType::prefsizey, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_OUTLINER, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
static void outliner_dropboxes (void) [static]
Definition at line 148 of file space_outliner.c.
References outliner_parent_clear_copy(), outliner_parent_clear_poll(), outliner_parent_drop_copy(), outliner_parent_drop_poll(), RGN_TYPE_WINDOW, SPACE_OUTLINER, WM_dropbox_add(), and WM_dropboxmap_find().
Referenced by ED_spacetype_outliner().
static SpaceLink* outliner_duplicate (SpaceLink * sl) [static]
Definition at line 365 of file space_outliner.c.
References ListBase::first, ListBase::last, MEM_dupallocN(), NULL, SpaceOops::tree, and SpaceOops::treestore.
Referenced by ED_spacetype_outliner().
static void outliner_free (SpaceLink * sl) [static]
Definition at line 347 of file space_outliner.c.
References TreeStore::data, MEM_freeN(), outliner_free_tree(), SpaceOops::tree, and SpaceOops::treestore.
Referenced by ED_spacetype_outliner().
static void outliner_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 290 of file space_outliner.c.
References ED_region_header().
Referenced by ED_spacetype_outliner().
static void outliner_header_area_free (ARegion * UNUSEDar) [static]
Definition at line 295 of file space_outliner.c.
Referenced by ED_spacetype_outliner().
static void outliner_header_area_init (wmWindowManager * UNUSEDwm, ARegion * ar) [static]
Definition at line 285 of file space_outliner.c.
References ED_region_header_init().
Referenced by ED_spacetype_outliner().
static void outliner_header_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 299 of file space_outliner.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NC_SCENE, NC_SPACE, ND_KEYINGSET, and ND_SPACE_OUTLINER.
Referenced by ED_spacetype_outliner().
static void outliner_init (wmWindowManager * UNUSEDwm, ScrArea * UNUSEDsa) [static]
Definition at line 360 of file space_outliner.c.
Referenced by ED_spacetype_outliner().
static void outliner_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 156 of file space_outliner.c.
References draw_outliner(), TH_BACK, UI_ThemeClearColor(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_view_restore(), ARegion::v2d, and V2D_ARG_DUMMY.
Referenced by ED_spacetype_outliner().
static void outliner_main_area_free (ARegion * UNUSEDar) [static]
Definition at line 177 of file space_outliner.c.
Referenced by ED_spacetype_outliner().
static void outliner_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 61 of file space_outliner.c.
References wmWindowManager::defaultconf, ARegion::handlers, NULL, RGN_TYPE_WINDOW, SPACE_OUTLINER, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_LIST, ARegion::winrct, ARegion::winx, ARegion::winy, WM_dropboxmap_find(), WM_event_add_dropbox_handler(), WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_outliner().
static void outliner_main_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 182 of file space_outliner.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NA_ADDED, NA_REMOVED, NA_RENAME, NA_SELECTED, NC_ANIMATION, NC_GEOM, NC_GROUP, NC_ID, NC_LAMP, NC_MATERIAL, NC_OBJECT, NC_SCENE, NC_SPACE, NC_TEXTURE, ND_ANIMCHAN, ND_BONE_ACTIVE, ND_BONE_SELECT, ND_CONSTRAINT, ND_DATA, ND_DRAW, ND_FRAME, ND_KEYFRAME, ND_KEYINGSET, ND_LAYER, ND_LIGHTING_DRAW, ND_MODE, ND_MODIFIER, ND_NLA_ACTCHANGE, ND_OB_ACTIVE, ND_OB_RENDER, ND_OB_SELECT, ND_OB_SHADING, ND_OB_VISIBLE, ND_PARENT, ND_RENDER_OPTIONS, ND_SHADING, ND_SHADING_DRAW, ND_SPACE_OUTLINER, ND_TRANSFORM, and ND_WORLD.
Referenced by ED_spacetype_outliner().
static SpaceLink* outliner_new (const bContext * UNUSEDC) [static]
Definition at line 316 of file space_outliner.c.
References View2D::align, ARegion::alignment, BLI_addtail(), View2D::keeptot, View2D::keepzoom, View2D::maxzoom, MEM_callocN(), View2D::minzoom, SpaceOops::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, View2D::scroll, SPACE_OUTLINER, SpaceOops::spacetype, ARegion::v2d, V2D_ALIGN_NO_NEG_X, V2D_ALIGN_NO_POS_Y, V2D_KEEPASPECT, V2D_KEEPTOT_STRICT, V2D_LIMITZOOM, V2D_LOCKZOOM_X, V2D_LOCKZOOM_Y, V2D_SCROLL_BOTTOM_O, and V2D_SCROLL_RIGHT.
Referenced by ED_spacetype_outliner().
static void outliner_parent_clear_copy (wmDrag * drag, wmDropBox * drop) [static]
Definition at line 136 of file space_outliner.c.
References ID::name, wmDrag::poin, wmDropBox::ptr, RNA_enum_set(), and RNA_string_set().
Referenced by outliner_dropboxes().
static int outliner_parent_clear_poll (bContext * C, wmDrag * drag, wmEvent * event) [static]
Definition at line 108 of file space_outliner.c.
References CTX_wm_region(), CTX_wm_space_outliner(), ListBase::first, TreeElement::flag, GS, ID_OB, if(), ListBase::last, wmEvent::mval, ID::name, TreeElement::next, NULL, outliner_dropzone_parent_clear(), wmDrag::poin, TreeElement::subtree, TE_LAZY_CLOSED, SpaceOops::tree, wmDrag::type, UI_view2d_region_to_view(), ARegion::v2d, WM_DRAG_ID, and TreeElement::ys.
Referenced by outliner_dropboxes().
static void outliner_parent_drop_copy (wmDrag * drag, wmDropBox * drop) [static]
Definition at line 101 of file space_outliner.c.
References ID::name, wmDrag::poin, wmDropBox::ptr, and RNA_string_set().
Referenced by outliner_dropboxes().
static int outliner_parent_drop_poll (bContext * C, wmDrag * drag, wmEvent * event) [static]
Definition at line 78 of file space_outliner.c.
References CTX_wm_region(), CTX_wm_space_outliner(), ListBase::first, GS, ID_OB, if(), wmEvent::mval, ID::name, TreeElement::next, NULL, outliner_dropzone_parent(), wmDrag::poin, SpaceOops::tree, wmDrag::type, UI_view2d_region_to_view(), ARegion::v2d, and WM_DRAG_ID.
Referenced by outliner_dropboxes().