Blender: MOD_collision.c File Reference
MOD_collision.c File Reference
modifiers
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "DNA_meshdata_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_collision.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_global.h"
#include "BKE_modifier.h"
#include "BKE_object.h"
#include "BKE_pointcache.h"
#include "BKE_scene.h"
#include "MOD_util.h"
Functions
static void initData (ModifierData *md)
static void freeData (ModifierData *md)
static int dependsOnTime (ModifierData *UNUSED(md))
static void deformVerts (ModifierData *md, Object *ob, DerivedMesh *derivedData, float(*vertexCos)[3], int UNUSED(numVerts), int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
Variables
ModifierTypeInfo modifierType_Collision
Detailed Description
Definition in file MOD_collision.c.
Function Documentation
static void deformVerts (ModifierData * md, Object * ob, DerivedMesh * derivedData, float(*) vertexCos[3], int UNUSEDnumVerts, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 108 of file MOD_collision.c.
References BKE_curframe(), BKE_ptcache_get_continue_physics(), BLI_bvhtree_free(), BLI_bvhtree_getepsilon(), bvhtree_build_from_mvert(), bvhtree_update_from_mvert(), CDDM_apply_vert_coords(), CDDM_calc_normals(), CDDM_copy(), CDDM_from_mesh(), Object::data, DM_ensure_tessface(), DerivedMesh::dupTessFaceArray, DerivedMesh::dupVertArray, freeData(), G, DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, DerivedMesh::getVertArray, i, MEM_dupallocN(), mul_m4_v3(), NULL, CollisionModifierData::numverts, OB_MESH, Object::obmat, Object::pd, PartDeflect::pdef_sboft, DerivedMesh::release, ModifierData::scene, CollisionModifierData::time_xnew, Object::type, and CollisionModifierData::x.
static int dependsOnTime (ModifierData * UNUSEDmd) [static]
Definition at line 103 of file MOD_collision.c.
static void freeData (ModifierData * md) [static]
Definition at line 70 of file MOD_collision.c.
References BLI_bvhtree_free(), CollisionModifierData::bvhtree, CollisionModifierData::current_v, CollisionModifierData::current_x, CollisionModifierData::current_xnew, MEM_freeN(), CollisionModifierData::mfaces, NULL, CollisionModifierData::numverts, CollisionModifierData::time_x, CollisionModifierData::time_xnew, CollisionModifierData::x, and CollisionModifierData::xnew.
Referenced by deformVerts().
static void initData (ModifierData * md) [static]
Definition at line 56 of file MOD_collision.c.
References CollisionModifierData::bvhtree, CollisionModifierData::current_v, CollisionModifierData::current_x, CollisionModifierData::current_xnew, NULL, CollisionModifierData::numverts, CollisionModifierData::time_x, CollisionModifierData::time_xnew, CollisionModifierData::x, and CollisionModifierData::xnew.
Variable Documentation
ModifierTypeInfo modifierType_Collision
Initial value:
 {
                  "Collision",
            "CollisionModifierData",
            sizeof(CollisionModifierData),
                  eModifierTypeType_OnlyDeform,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_Single,
              NULL,
           deformVerts,
        NULL,
         NULL,
      NULL,
         NULL,
       NULL,
              initData,
      NULL,
              freeData,
            NULL,
        NULL,
         dependsOnTime,
        NULL,
     NULL,
         NULL,
        NULL,
}
Definition at line 236 of file MOD_collision.c.