Blender: ED_info.h File Reference
ED_info.h File Reference
Editors
Functions
void ED_info_stats_clear (struct Scene *scene)
const char * ED_info_stats_string (struct Scene *scene)
Detailed Description
Definition in file ED_info.h.
Function Documentation
void ED_info_stats_clear (struct Scene * scene)
Definition at line 397 of file info_stats.c.
References MEM_freeN(), NULL, and Scene::stats.
Referenced by wm_event_do_notifiers().
const char* ED_info_stats_string (struct Scene * scene)
Definition at line 405 of file info_stats.c.
References SceneStats::infostr, Scene::stats, stats_string(), and stats_update().