Blender: KX_ConvertControllers.h File Reference
KX_ConvertControllers.h File Reference
Converter
#include "KX_Python.h"
Functions
void BL_ConvertControllers (struct Object *blenderobject, class KX_GameObject *gameobj, class SCA_LogicManager *logicmgr, int activeLayerBitInfo, bool isInActiveLayer, class KX_BlenderSceneConverter *converter)
Detailed Description
Definition in file KX_ConvertControllers.h.
Function Documentation
void BL_ConvertControllers (struct Object * blenderobject, class KX_GameObject * gameobj, class SCA_LogicManager * logicmgr, int activeLayerBitInfo, bool isInActiveLayer, class KX_BlenderSceneConverter * converter)
Definition at line 91 of file KX_ConvertControllers.cpp.
References SCA_IObject::AddController(), SCA_PythonController::Compile(), CONT_EXPRESSION, CONT_LOGIC_AND, CONT_LOGIC_NAND, CONT_LOGIC_NOR, CONT_LOGIC_OR, CONT_LOGIC_XNOR, CONT_LOGIC_XOR, CONT_PRIO, CONT_PY_DEBUG, CONT_PYTHON, Object::controllers, bController::data, ListBase::first, bPythonCont::flag, bController::flag, CIntValue::GetText(), Text::id, Object::id, LinkControllerToActuators(), MEM_freeN(), bPythonCont::mode, bPythonCont::module, ID::name, bController::name, bController::next, NULL, KX_BlenderSceneConverter::RegisterGameController(), CValue::Release(), SCA_IObject::ReserveController(), SCA_PythonController::SCA_PYEXEC_SCRIPT, SCA_IController::SetBookmark(), SCA_ILogicBrick::SetExecutePriority(), SCA_ILogicBrick::SetName(), SCA_IController::SetState(), bController::state_mask, bExpressionCont::str, bPythonCont::text, txt_to_buf(), and bController::type.
Referenced by BL_ConvertBlenderObjects().