Blender: BKE_customdata_file.h File Reference
BKE_customdata_file.h File Reference
blenkernel
Defines
#define CDF_TYPE_IMAGE 0
#define CDF_TYPE_MESH 1
#define CDF_LAYER_NAME_MAX 64
Typedefs
typedef struct CDataFile CDataFile
typedef struct CDataFileLayer CDataFileLayer
Functions
CDataFile * cdf_create (int type)
void cdf_free (CDataFile *cdf)
int cdf_read_open (CDataFile *cdf, const char *filename)
int cdf_read_layer (CDataFile *cdf, CDataFileLayer *blay)
int cdf_read_data (CDataFile *cdf, unsigned int size, void *data)
void cdf_read_close (CDataFile *cdf)
int cdf_write_open (CDataFile *cdf, const char *filename)
int cdf_write_layer (CDataFile *cdf, CDataFileLayer *blay)
int cdf_write_data (CDataFile *cdf, unsigned int size, void *data)
void cdf_write_close (CDataFile *cdf)
void cdf_remove (const char *filename)
CDataFileLayer * cdf_layer_find (CDataFile *cdf, int type, const char *name)
CDataFileLayer * cdf_layer_add (CDataFile *cdf, int type, const char *name, size_t datasize)
Detailed Description
Definition in file BKE_customdata_file.h.
Define Documentation
#define CDF_LAYER_NAME_MAX 64
Definition at line 31 of file BKE_customdata_file.h.
Referenced by cdf_layer_add().
#define CDF_TYPE_IMAGE 0
Definition at line 28 of file BKE_customdata_file.h.
Referenced by cdf_read_header(), cdf_write_header(), and cdf_write_open().
#define CDF_TYPE_MESH 1
Definition at line 29 of file BKE_customdata_file.h.
Referenced by cdf_read_header(), cdf_write_header(), cdf_write_open(), CustomData_external_read(), and CustomData_external_write().
Typedef Documentation
typedef struct CDataFile CDataFile
Definition at line 33 of file BKE_customdata_file.h.
typedef struct CDataFileLayer CDataFileLayer
Definition at line 34 of file BKE_customdata_file.h.
Function Documentation
CDataFile* cdf_create (int type)
Definition at line 122 of file customdata_file.c.
References MEM_callocN(), and CDataFile::type.
Referenced by CustomData_external_read(), and CustomData_external_write().
void cdf_free (CDataFile * cdf)
Definition at line 131 of file customdata_file.c.
References cdf_read_close(), cdf_write_close(), CDataFile::layer, and MEM_freeN().
Referenced by CustomData_external_read(), and CustomData_external_write().
CDataFileLayer* cdf_layer_add (CDataFile * cdf, int type, const char * name, size_t datasize)
Definition at line 433 of file customdata_file.c.
References BLI_strncpy(), CDF_DATA_FLOAT, CDF_LAYER_NAME_MAX, CDataFileLayer::datasize, CDataFileLayer::datatype, CDataFile::layer, MEM_callocN(), CDataFileLayer::name, CDataFileLayer::structbytes, CDataFile::totlayer, and CDataFileLayer::type.
Referenced by CustomData_external_write().
CDataFileLayer* cdf_layer_find (CDataFile * cdf, int type, const char * name)
Definition at line 418 of file customdata_file.c.
References CDataFile::layer, CDataFileLayer::name, NULL, CDataFile::totlayer, and CDataFileLayer::type.
Referenced by CustomData_external_read(), and CustomData_external_write().
void cdf_read_close (CDataFile * cdf)
Definition at line 339 of file customdata_file.c.
References NULL, and CDataFile::readf.
Referenced by cdf_free(), cdf_read_open(), and CustomData_external_read().
int cdf_read_data (CDataFile * cdf, unsigned int size, void * data)
Definition at line 318 of file customdata_file.c.
References data, CDataFile::readf, SWITCH_INT, and CDataFile::switchendian.
Referenced by layerRead_mdisps().
int cdf_read_layer (CDataFile * cdf, CDataFileLayer * blay)
Definition at line 301 of file customdata_file.c.
References CDataFile::dataoffset, CDataFileLayer::datasize, fseek, CDataFile::layer, CDataFile::readf, and CDataFile::totlayer.
Referenced by CustomData_external_read().
int cdf_read_open (CDataFile * cdf, const char * filename)
Definition at line 278 of file customdata_file.c.
References BLI_fopen(), cdf_read_close(), cdf_read_header(), CDataFile::header, CDataFile::readf, CDataFileHeader::type, and CDataFile::type.
Referenced by CustomData_external_read().
void cdf_remove (const char * filename)
Definition at line 411 of file customdata_file.c.
References BLI_delete().
Referenced by CustomData_external_remove().
void cdf_write_close (CDataFile * cdf)
Definition at line 403 of file customdata_file.c.
References NULL, and CDataFile::writef.
Referenced by cdf_free(), and CustomData_external_write().
int cdf_write_data (CDataFile * cdf, unsigned int size, void * data)
Definition at line 394 of file customdata_file.c.
References CDataFile::writef.
Referenced by layerWrite_mdisps().
int cdf_write_layer (CDataFile * cdf, CDataFileLayer * blay)
Referenced by CustomData_external_write().
int cdf_write_open (CDataFile * cdf, const char * filename)
Definition at line 347 of file customdata_file.c.
References BLI_fopen(), CDataFile::btype, cdf_endian(), CDF_SUBVERSION, CDF_TILE_SIZE, CDF_TYPE_IMAGE, CDF_TYPE_MESH, CDF_VERSION, cdf_write_header(), CDataFileHeader::endian, CDataFile::header, CDataFileHeader::ID, CDataFile::image, CDataFile::mesh, CDataFileHeader::structbytes, CDataFileImageHeader::structbytes, CDataFileMeshHeader::structbytes, CDataFileHeader::subversion, CDataFileImageHeader::tile_size, CDataFile::totlayer, CDataFileHeader::totlayer, CDataFileHeader::type, CDataFile::type, CDataFileHeader::version, and CDataFile::writef.
Referenced by CustomData_external_write().