Blender: writeimage.c File Reference
writeimage.c File Reference
IMage Buffer
#include <stdio.h>
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_filetype.h"
#include "imbuf.h"
Functions
short IMB_saveiff (struct ImBuf *ibuf, const char *name, int flags)
Detailed Description
Definition in file writeimage.c.
Function Documentation
short IMB_saveiff (struct ImBuf * ibuf, const char * filepath, int flags)
Attention:
Defined in writeimage.c
Definition at line 43 of file writeimage.c.
References FALSE, ImFileType::flag, ImBuf::flags, ImFileType::ftype, IM_FTYPE_FLOAT, IMB_FILE_TYPES, IMB_rect_from_float(), ImFileType::is_a, NULL, ImBuf::rect, ImBuf::rect_float, and ImFileType::save.
Referenced by BKE_image_memorypack(), BKE_write_ibuf(), BL_MakeScreenShot(), dynamicPaint_outputSurfaceImage(), image_save_sequence_exec(), IMB_thumb_create(), movieclip_build_proxy_ibuf(), saveiff(), and seq_proxy_build_frame().