Blender: armature_ops.c File Reference
armature_ops.c File Reference
armature
#include <stdlib.h>
#include <math.h>
#include "BLO_sys_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_armature.h"
#include "ED_screen.h"
#include "ED_transform.h"
#include "armature_intern.h"
Functions
void ED_operatortypes_armature (void)
void ED_operatormacros_armature (void)
void ED_keymap_armature (wmKeyConfig *keyconf)
Detailed Description
Definition in file armature_ops.c.
Function Documentation
void ED_keymap_armature (wmKeyConfig * keyconf)
Definition at line 202 of file armature_ops.c.
References ACCENTGRAVEKEY, AKEY, BONE_SELECT_CHILD, BONE_SELECT_PARENT, CKEY, DELKEY, DKEY, ED_operator_editarmature(), ED_operator_posemode(), EKEY, ESCKEY, FALSE, FKEY, GKEY, HKEY, IKEY, KM_ALT, KM_ANY, KM_CLICK, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTBRACKETKEY, LEFTMOUSE, LKEY, MKEY, MOUSEMOVE, NKEY, PKEY, wmKeyMap::poll, wmKeyMapItem::ptr, RIGHTBRACKETKEY, RIGHTMOUSE, RKEY, RNA_boolean_set(), RNA_enum_set(), SEL_INVERT, SEL_TOGGLE, SKEY, TFM_BONE_ROLL, TFM_BONESIZE, TRUE, VKEY, WKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), WM_keymap_verify_item(), and XKEY.
Referenced by ED_spacetypes_keymap().
void ED_operatormacros_armature (void)
Definition at line 168 of file armature_ops.c.
References wmOperatorType::description, FALSE, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorTypeMacro::ptr, RNA_boolean_set(), RNA_enum_set(), TRUE, WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().
void ED_operatortypes_armature (void)
Definition at line 55 of file armature_ops.c.
References ARMATURE_OT_align(), ARMATURE_OT_armature_layers(), ARMATURE_OT_autoside_names(), ARMATURE_OT_bone_layers(), ARMATURE_OT_bone_primitive_add(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_click_extrude(), ARMATURE_OT_delete(), ARMATURE_OT_duplicate(), ARMATURE_OT_extrude(), ARMATURE_OT_fill(), ARMATURE_OT_flip_names(), ARMATURE_OT_hide(), ARMATURE_OT_layers_show_all(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), ARMATURE_OT_parent_set(), ARMATURE_OT_reveal(), ARMATURE_OT_select_all(), ARMATURE_OT_select_hierarchy(), ARMATURE_OT_select_inverse(), ARMATURE_OT_select_linked(), ARMATURE_OT_separate(), ARMATURE_OT_subdivide(), ARMATURE_OT_switch_direction(), POSE_OT_armature_apply(), POSE_OT_armature_layers(), POSE_OT_autoside_names(), POSE_OT_bone_layers(), POSE_OT_breakdown(), POSE_OT_copy(), POSE_OT_flip_names(), POSE_OT_group_add(), POSE_OT_group_assign(), POSE_OT_group_deselect(), POSE_OT_group_move(), POSE_OT_group_remove(), POSE_OT_group_select(), POSE_OT_group_sort(), POSE_OT_group_unassign(), POSE_OT_hide(), POSE_OT_loc_clear(), POSE_OT_paste(), POSE_OT_paths_calculate(), POSE_OT_paths_clear(), POSE_OT_propagate(), POSE_OT_push(), POSE_OT_quaternions_flip(), POSE_OT_relax(), POSE_OT_reveal(), POSE_OT_rot_clear(), POSE_OT_rotation_mode_set(), POSE_OT_scale_clear(), POSE_OT_select_all(), POSE_OT_select_constraint_target(), POSE_OT_select_flip_active(), POSE_OT_select_grouped(), POSE_OT_select_hierarchy(), POSE_OT_select_linked(), POSE_OT_select_parent(), POSE_OT_transforms_clear(), POSE_OT_user_transforms_clear(), POSE_OT_visual_transform_apply(), POSELIB_OT_action_sanitise(), POSELIB_OT_apply_pose(), POSELIB_OT_browse_interactive(), POSELIB_OT_new(), POSELIB_OT_pose_add(), POSELIB_OT_pose_remove(), POSELIB_OT_pose_rename(), POSELIB_OT_unlink(), SKETCH_OT_cancel_stroke(), SKETCH_OT_convert(), SKETCH_OT_delete(), SKETCH_OT_draw_preview(), SKETCH_OT_draw_stroke(), SKETCH_OT_finish_stroke(), SKETCH_OT_gesture(), SKETCH_OT_select(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().