Blender: kernel_displace.h File Reference
kernel_displace.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void kernel_shader_evaluate (KernelGlobals *kg, uint4 *input, float4 *output, ShaderEvalType type, int i)
Function Documentation
CCL_NAMESPACE_BEGIN __device void kernel_shader_evaluate (KernelGlobals * kg, uint4 * input, float4 * output, ShaderEvalType type, int i)
Definition at line 21 of file kernel_displace.h.
References __int_as_float(), Ray::D, Ray::dD, Ray::dP, differential3::dx, differential3::dy, equirectangular_to_direction(), i, make_float3(), make_float4(), P(), Ray::P, ShaderData::P, shader_eval_background(), SHADER_EVAL_DISPLACE, shader_eval_displacement(), shader_setup_from_background(), shader_setup_from_displace(), Ray::t, uint4::w, float3::x, uint4::x, float3::y, uint4::y, float3::z, and uint4::z.
Referenced by kernel_cpu_shader().