Blender: memtest.c File Reference
memtest.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "MEM_guardedalloc.h"
Defines
#define NUM_BLOCKS 10
Functions
static void mem_error_cb (const char *errorStr)
int main (int argc, char *argv[])
Define Documentation
#define NUM_BLOCKS 10
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) 2001-2002 by NaN Holding BV. All rights reserved.
The Original Code is: all of this file.
Contributor(s): none yet.
***** END GPL LICENSE BLOCK *****
Copyright (C) 2001 NaN Technologies B.V. Simple test of memory.
Definition at line 37 of file memtest.c.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 50 of file memtest.c.
References i, MEM_callocN(), MEM_check_memory_integrity(), mem_error_cb(), MEM_freeN(), MEM_printmemlist(), MEM_set_error_callback(), NULL, NUM_BLOCKS, p, and verbose.
static void mem_error_cb (const char * errorStr) [static]
Definition at line 44 of file memtest.c.
Referenced by main().