Blender: bmesh_iterators_inline.h File Reference
bmesh_iterators_inline.h File Reference
BMesh
Functions
BLI_INLINE void * BM_iter_step (BMIter *iter)
Iterator Step.
BLI_INLINE int BM_iter_init (BMIter *iter, BMesh *bm, const char itype, void *data)
Iterator Init.
BLI_INLINE void * BM_iter_new (BMIter *iter, BMesh *bm, const char itype, void *data)
Iterator New.
Detailed Description
BMesh inline iterator functions.
Definition in file bmesh_iterators_inline.h.
Function Documentation
BLI_INLINE int BM_iter_init (BMIter * iter, BMesh * bm, const char itype, void * data)
Iterator Init.
Takes a bmesh iterator structure and fills it with the appropriate function pointers based upon its type.
Definition at line 53 of file bmesh_iterators_inline.h.
References BMIter::begin, BLI_assert, BMIter::bm, BM_EDGES_OF_FACE, BM_EDGES_OF_MESH, BM_EDGES_OF_VERT, BM_FACES_OF_EDGE, BM_FACES_OF_MESH, BM_FACES_OF_VERT, BM_LOOPS_OF_EDGE, BM_LOOPS_OF_FACE, BM_LOOPS_OF_LOOP, BM_LOOPS_OF_VERT, BM_VERTS_OF_EDGE, BM_VERTS_OF_FACE, BM_VERTS_OF_MESH, bmiter__edge_of_face_begin(), bmiter__edge_of_face_step(), bmiter__edge_of_mesh_begin(), bmiter__edge_of_mesh_step(), bmiter__edge_of_vert_begin(), bmiter__edge_of_vert_step(), bmiter__face_of_edge_begin(), bmiter__face_of_edge_step(), bmiter__face_of_mesh_begin(), bmiter__face_of_mesh_step(), bmiter__face_of_vert_begin(), bmiter__face_of_vert_step(), bmiter__loop_of_face_begin(), bmiter__loop_of_face_step(), bmiter__loop_of_vert_begin(), bmiter__loop_of_vert_step(), bmiter__loops_of_edge_begin(), bmiter__loops_of_edge_step(), bmiter__loops_of_loop_begin(), bmiter__loops_of_loop_step(), bmiter__vert_of_edge_begin(), bmiter__vert_of_edge_step(), bmiter__vert_of_face_begin(), bmiter__vert_of_face_step(), bmiter__vert_of_mesh_begin(), bmiter__vert_of_mesh_step(), data, BMIter::edata, FALSE, BMIter::itype, BMIter::ldata, NULL, BMIter::pdata, BMIter::step, TRUE, UNLIKELY, and BMIter::vdata.
Referenced by BM_iter_new(), bpy_bmelemseq_iter(), and bpy_bmelemseq_subscript_slice().
BLI_INLINE void* BM_iter_new (BMIter * iter, BMesh * bm, const char itype, void * data)
Iterator New.
Takes a bmesh iterator structure and fills it with the appropriate function pointers based upon its type and then calls BMeshIter_step() to return the first element of the iterator.
Definition at line 190 of file bmesh_iterators_inline.h.
References BM_iter_init(), BM_iter_step(), LIKELY, and NULL.
Referenced by BM_edge_select_set(), BM_face_legal_splits(), BM_iter_as_array(), BM_iter_at_index(), BM_mesh_bm_to_me(), BM_mesh_copy(), BM_mesh_elem_hflag_disable_test(), BM_mesh_elem_hflag_enable_test(), bm_mesh_flag_count(), BMEdit_RecalcTessellation_intern(), bmo_connectverts_exec(), bmo_dissolve_verts_exec(), bmo_esubd_exec(), bmo_extrude_face_indiv_exec(), bmo_mirror_exec(), BMO_remove_tagged_context(), bmo_split_exec(), bmw_IslandWalker_step(), CDDM_from_BMEditMesh(), check_hole_in_region(), connect_smallest_face(), copy_edge(), copy_face(), createTransEditVerts(), DM_to_bmesh_ex(), draw_em_measure_stats(), edbm_backbuf_check_and_select_edges(), edbm_backbuf_check_and_select_faces(), edbm_backbuf_check_and_select_verts(), edbm_extrude_edge(), EDBM_index_arrays_init(), edbm_knife_cut_exec(), edbm_loop_multiselect_exec(), edbm_screw_exec(), edbm_select_by_number_vertices_exec(), edbm_select_loose_verts_exec(), EDBM_selectmode_convert(), EDBM_selectmode_set(), EDBM_stats_update(), editbmesh_get_vertex_cos(), emDM__calcFaceCent(), emDM_copyEdgeArray(), emDM_copyVertArray(), emDM_drawMappedEdges(), emDM_drawMappedEdgesInterp(), emDM_foreachMappedEdge(), emDM_foreachMappedFaceCenter(), emDM_foreachMappedVert(), emDM_getMinMax(), get_editbmesh_orco_verts(), get_weights_array(), getEditDerivedBMesh(), recount_totsels(), rotsys_make_consistent(), snapDerivedMesh(), test_extra_verts(), uv_faces_do_sticky(), and vgroup_copy_active_to_sel_single().
BLI_INLINE void* BM_iter_step (BMIter * iter)
Iterator Step.
Calls an iterators step fucntion to return the next element.
Definition at line 40 of file bmesh_iterators_inline.h.
References BMIter::step.
Referenced by BM_edge_select_set(), BM_face_legal_splits(), BM_iter_as_array(), BM_iter_at_index(), BM_iter_new(), BM_mesh_bm_to_me(), BM_mesh_copy(), BM_mesh_elem_hflag_disable_test(), BM_mesh_elem_hflag_enable_test(), bm_mesh_flag_count(), BMEdit_RecalcTessellation_intern(), bmo_connectverts_exec(), bmo_dissolve_verts_exec(), bmo_esubd_exec(), bmo_extrude_face_indiv_exec(), bmo_mirror_exec(), BMO_remove_tagged_context(), bmo_split_exec(), bmw_IslandWalker_step(), bpy_bmelemseq_subscript_slice(), bpy_bmiter_next(), CDDM_from_BMEditMesh(), check_hole_in_region(), connect_smallest_face(), copy_edge(), copy_face(), createTransEditVerts(), DM_to_bmesh_ex(), draw_em_measure_stats(), edbm_backbuf_check_and_select_edges(), edbm_backbuf_check_and_select_faces(), edbm_backbuf_check_and_select_verts(), edbm_extrude_edge(), EDBM_index_arrays_init(), edbm_knife_cut_exec(), edbm_loop_multiselect_exec(), edbm_screw_exec(), edbm_select_by_number_vertices_exec(), edbm_select_loose_verts_exec(), EDBM_selectmode_convert(), EDBM_selectmode_set(), EDBM_stats_update(), editbmesh_get_vertex_cos(), emDM__calcFaceCent(), emDM_copyEdgeArray(), emDM_copyVertArray(), emDM_drawMappedEdges(), emDM_drawMappedEdgesInterp(), emDM_foreachMappedEdge(), emDM_foreachMappedFaceCenter(), emDM_foreachMappedVert(), emDM_getMinMax(), get_editbmesh_orco_verts(), get_weights_array(), getEditDerivedBMesh(), recount_totsels(), rotsys_make_consistent(), snapDerivedMesh(), test_extra_verts(), uv_faces_do_sticky(), and vgroup_copy_active_to_sel_single().