Blender: PyTypeList Class Reference
PyTypeList Class Reference
class to store list of python types
#include <PyTypeList.h>
Public Member Functions
~PyTypeList ()
destructor
bool in (PyTypeObject *type)
check, if type is in list
void add (PyTypeObject *type, const char *name)
add type to list
bool ready (void)
prepare types
void reg (PyObject *module)
register types to module
Protected Attributes
std::auto_ptr< PyTypeListType > m_list
pointer to list of types
Detailed Description
class to store list of python types
Definition at line 45 of file PyTypeList.h.
Constructor & Destructor Documentation
PyTypeList::~PyTypeList ()
destructor
Definition at line 35 of file PyTypeList.cpp.
References m_list, and NULL.
Member Function Documentation
void PyTypeList::add (PyTypeObject * type, const char * name)
add type to list
Definition at line 57 of file PyTypeList.cpp.
References in(), m_list, and NULL.
Referenced by registerAllTypes().
bool PyTypeList::in (PyTypeObject * type)
check, if type is in list
Definition at line 44 of file PyTypeList.cpp.
References m_list, and NULL.
Referenced by add(), Filter_setPrevious(), Image_setFilter(), Image_setSource(), imageToArray(), and Texture_setSource().
bool PyTypeList::ready (void)
prepare types
Definition at line 68 of file PyTypeList.cpp.
References m_list, and NULL.
Referenced by initVideoTexture().
void PyTypeList::reg (PyObject * module)
register types to module
Definition at line 81 of file PyTypeList.cpp.
References m_list, and NULL.
Referenced by initVideoTexture().
Member Data Documentation
std::auto_ptr<PyTypeListType> PyTypeList::m_list [protected]
pointer to list of types
Definition at line 65 of file PyTypeList.h.
Referenced by add(), in(), ready(), reg(), and ~PyTypeList().
The documentation for this class was generated from the following files:
PyTypeList.h
PyTypeList.cpp