Blender: BKE_softbody.h File Reference
BKE_softbody.h File Reference
blenkernel
Classes
struct BodyPoint
Typedefs
typedef struct BodyPoint BodyPoint
Functions
struct SoftBody * sbNew (struct Scene *scene)
void sbFree (struct SoftBody *sb)
void sbFreeSimulation (struct SoftBody *sb)
void sbObjectStep (struct Scene *scene, struct Object *ob, float framnr, float(*vertexCos)[3], int numVerts)
void sbObjectToSoftbody (struct Object *ob)
void sbSetInterruptCallBack (int(*f)(void))
void SB_estimate_transform (Object *ob, float lloc[3], float lrot[3][3], float lscale[3][3])
Detailed Description
Definition in file BKE_softbody.h.
Typedef Documentation
typedef struct BodyPoint BodyPoint
Function Documentation
void SB_estimate_transform (Object * ob, float lloc[3], float lrot[3][3], float lscale[3][3])
Definition at line 3816 of file softbody.c.
References SoftBody::bpoint, copy_m3_m3(), copy_v3_v3(), ReferenceState::ivert, SoftBody::lcom, SoftBody::lrot, SoftBody::lscale, MEM_callocN(), MEM_freeN(), NULL, BodyPoint::pos, ReferenceVert::pos, SBScratch::Ref, SoftBody::scratch, Object::soft, SoftBody::totpoint, and vcloud_estimate_transform().
Referenced by softbody_reset(), and softbody_to_object().
void sbFree (struct SoftBody * sb)
Definition at line 3737 of file softbody.c.
References BKE_ptcache_free_list(), SoftBody::effector_weights, free_softbody_intern(), MEM_freeN(), NULL, SoftBody::pointcache, and SoftBody::ptcaches.
Referenced by copy_attr(), free_object(), object_free_softbody(), and object_modifier_remove().
void sbFreeSimulation (struct SoftBody * sb)
Definition at line 3747 of file softbody.c.
References free_softbody_intern().
Referenced by BKE_ptcache_id_reset().
struct SoftBody* sbNew (struct Scene * scene) [read]
Definition at line 3684 of file softbody.c.
References SoftBody::balldamp, SoftBody::ballstiff, BKE_add_effector_weights(), BKE_ptcache_add(), SoftBody::choke, SoftBody::colball, SoftBody::defgoal, SoftBody::effector_weights, RenderData::efra, SoftBody::efra, SoftBody::goalfrict, SoftBody::goalspring, SoftBody::grav, SoftBody::infrict, SoftBody::inpush, SoftBody::inspring, SoftBody::interval, SoftBody::last_frame, SoftBody::maxgoal, SoftBody::maxloops, SoftBody::mediafrict, MEM_callocN(), MINFRAME, SoftBody::mingoal, SoftBody::minloops, SoftBody::nodemass, NULL, SoftBody::physics_speed, SoftBody::pointcache, SoftBody::ptcaches, Scene::r, SoftBody::rklimit, sb_new_scratch(), SoftBody::sbc_mode, SBSO_OLDERR, RenderData::sfra, SoftBody::sfra, SoftBody::shearstiff, and SoftBody::solverflags.
Referenced by ED_object_modifier_add(), and renew_softbody().
void sbObjectStep (struct Scene * scene, struct Object * ob, float framnr, float(*) vertexCos[3], int numVerts)
Definition at line 4047 of file softbody.c.
References BKE_ptcache_get_continue_physics(), BKE_ptcache_id_from_softbody(), BKE_ptcache_id_reset(), BKE_ptcache_id_time(), BKE_ptcache_invalidate(), BKE_ptcache_read(), BKE_ptcache_validate(), BKE_ptcache_write(), SoftBody::bpoint, SoftBody::bspring, curve_surf_to_softbody(), PointCache::flag, PointCache::last_exact, SoftBody::last_frame, lattice_to_softbody(), SoftBody::local, mesh_to_softbody(), NULL, OB_CURVE, OB_LATTICE, OB_MESH, OB_SB_EDGES, OB_SURF, object_has_edges(), SoftBody::pointcache, PTCACHE_BAKED, PTCACHE_OUTDATED, PTCACHE_READ_EXACT, PTCACHE_READ_INTERPOLATED, PTCACHE_READ_OLD, PTCACHE_REDO_NEEDED, PTCACHE_RESET_OUTDATED, Scene::r, renew_softbody(), PointCache::simframe, Object::soft, softbody_reset(), softbody_step(), softbody_to_object(), softbody_update_positions(), Object::softflag, RenderData::subframe, SoftBody::totpoint, and Object::type.
Referenced by deformVerts().
void sbObjectToSoftbody (struct Object * ob)
Definition at line 3753 of file softbody.c.
References free_softbody_intern(), and Object::soft.
void sbSetInterruptCallBack (int(*)(void) f)
Definition at line 3774 of file softbody.c.
References SB_localInterruptCallBack.