Blender: envmap.h File Reference
envmap.h File Reference
Rendering
Functions
void make_envmaps (struct Render *re)
int envmaptex (struct Tex *tex, float *texvec, float *dxt, float *dyt, int osatex, struct TexResult *texres)
Detailed Description
Definition in file envmap.h.
Function Documentation
int envmaptex (struct Tex * tex, float * texvec, float * dxt, float * dyt, int osatex, struct TexResult * texres)
Definition at line 674 of file envmap.c.
References add_v3_v3(), BKE_image_get_ibuf(), copy_v3_v3(), EnvMap::cube, Tex::env, ENV_LOAD, envcube_isect(), envmap_split_ima(), EnvMap::ima, Tex::ima, imagewrap(), imagewraposa(), mul_m3_v3(), mul_mat3_m4_v3(), TexResult::nor, NULL, EnvMap::obimat, EnvMap::object, Image::ok, EnvMap::ok, R, set_dxtdyt(), EnvMap::stype, sub_v3_v3(), TexResult::ta, TexResult::talpha, TexResult::tb, TexResult::tg, TexResult::tin, TexResult::tr, and Render::viewinv.
Referenced by multitex().
void make_envmaps (struct Render * re)
Definition at line 507 of file envmap.c.
References BKE_free_envmapdata(), copy_m3_m4(), copy_m4_m4(), Render::dch, EnvMap::depth, Render::dih, Render::display_clear, Render::display_init, Tex::env, ENV_LOAD, ENV_NORMAL, ListBase::first, Render::i, Tex::id, RenderStats::infostr, invert_m4_m4(), EnvMap::lastsize, Object::lay, Render::lay, Render::main, RenderData::mode, mult_m4_m4m4(), ID::next, normalize_m4(), EnvMap::obimat, EnvMap::object, Object::obmat, EnvMap::ok, Render::r, R_ENVMAP, R_OSA, R_RAYTRACE, EnvMap::recalc, render_envmap(), Render::result, Render::sdh, RenderData::size, Render::stats_draw, EnvMap::stype, Main::tex, TEX_ENVMAP, trace, Tex::type, ID::us, and Render::viewmat.
Referenced by RE_Database_FromScene().