Blender: ObjectManager Class Reference
ObjectManager Class Reference
#include <object.h>
Public Member Functions
ObjectManager ()
~ObjectManager ()
void device_update (Device *device, DeviceScene *dscene, Scene *scene, Progress &progress)
void device_update_transforms (Device *device, DeviceScene *dscene, Scene *scene, Progress &progress)
void device_free (Device *device, DeviceScene *dscene)
void tag_update (Scene *scene)
void apply_static_transforms (Scene *scene, Progress &progress)
Public Attributes
bool need_update
Detailed Description
Definition at line 59 of file object.h.
Constructor & Destructor Documentation
ObjectManager::ObjectManager ()
Definition at line 111 of file object.cpp.
References need_update.
ObjectManager::~ObjectManager ()
Definition at line 116 of file object.cpp.
Member Function Documentation
void ObjectManager::apply_static_transforms (Scene * scene, Progress & progress)
Definition at line 220 of file object.cpp.
References Progress::get_cancel(), Object::mesh, Scene::objects, and Mesh::transform_applied.
Referenced by device_update().
void ObjectManager::device_free (Device * device, DeviceScene * dscene)
Definition at line 214 of file object.cpp.
References device_vector< T >::clear(), DeviceScene::objects, and Device::tex_free().
Referenced by device_update(), and Scene::~Scene().
void ObjectManager::device_update (Device * device, DeviceScene * dscene, Scene * scene, Progress & progress)
Definition at line 186 of file object.cpp.
References apply_static_transforms(), SceneParams::BVH_STATIC, SceneParams::bvh_type, device_free(), device_update_transforms(), Progress::get_cancel(), need_update, Scene::objects, Scene::params, and Progress::set_status().
Referenced by Scene::device_update().
void ObjectManager::device_update_transforms (Device * device, DeviceScene * dscene, Scene * scene, Progress & progress)
Definition at line 120 of file object.cpp.
References Progress::get_cancel(), i, make_float4(), Object::mesh, OBJECT_SIZE, Scene::objects, DeviceScene::objects, Object::pass_id, device_vector< T >::resize(), Device::tex_alloc(), Object::tfm, transform_inverse(), transform_point(), transform_transpose(), transform_uniform_scale(), triangle_area(), Mesh::triangles, Mesh::Triangle::v, and Mesh::verts.
Referenced by device_update().
void ObjectManager::tag_update (Scene * scene)
Definition at line 252 of file object.cpp.
References Scene::light_manager, Scene::mesh_manager, need_update, LightManager::need_update, and MeshManager::need_update.
Member Data Documentation
bool ObjectManager::need_update
Definition at line 61 of file object.h.
Referenced by device_update(), Scene::need_reset(), ObjectManager(), MeshManager::tag_update(), Object::tag_update(), Mesh::tag_update(), and tag_update().
The documentation for this class was generated from the following files:
object.h
object.cpp