Blender: node_texture_at.c File Reference
node_texture_at.c File Reference
texnodes
#include "node_texture_util.h"
#include "NOD_texture.h"
Functions
static void colorfn (float *out, TexParams *p, bNode *UNUSED(node), bNodeStack **in, short thread)
static void exec (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_tex_at (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate inputs []
static bNodeSocketTemplate outputs []
Detailed Description
Definition in file node_texture_at.c.
Function Documentation
static void colorfn (float * out, TexParams * p, bNode * UNUSEDnode, bNodeStack ** in, short thread) [static]
Definition at line 46 of file node_texture_at.c.
References TexParams::co, p, tex_input_rgba(), and tex_input_vec().
Referenced by exec().
static void exec (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 56 of file node_texture_at.c.
References colorfn(), and tex_output().
Referenced by register_node_type_tex_at().
void register_node_type_tex_at (bNodeTreeType * ttype)
Definition at line 61 of file node_texture_at.c.
References exec(), NODE_CLASS_DISTORT, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_AT.
Referenced by registerTextureNodes().
Variable Documentation
bNodeSocketTemplate inputs[] [static]
Initial value:
 {
    { SOCK_RGBA,   1, "Texture",     0.0f, 0.0f, 0.0f, 1.0f },
    { SOCK_VECTOR, 1, "Coordinates", 0.0f, 0.0f, 0.0f, 0.0f, -1.0f, 1.0f, PROP_NONE },
    { -1, 0, "" }
}
Definition at line 36 of file node_texture_at.c.
Referenced by GPU_nodes_extract_dynamic_inputs(), GPU_pass_bind(), GPU_pass_unbind(), GPU_pass_update_uniforms(), and node_type_socket_templates().
bNodeSocketTemplate outputs[] [static]
Initial value:
 {
    { SOCK_RGBA,   0, "Texture" },
    { -1, 0, "" }
}
Definition at line 41 of file node_texture_at.c.
Referenced by node_type_socket_templates().