Blender: btConnectivityProcessor Struct Reference
btConnectivityProcessor Struct Reference
Public Member Functions
virtual void processTriangle (btVector3 *triangle, int partId, int triangleIndex)
Public Attributes
int m_partIdA
int m_triangleIndexA
btVector3 * m_triangleVerticesA
btTriangleInfoMap * m_triangleInfoMap
Detailed Description
Definition at line 52 of file btInternalEdgeUtility.cpp.
Member Function Documentation
virtual void btConnectivityProcessor::processTriangle (btVector3 * triangle, int partId, int triangleIndex) [inline, virtual]
skip degenerate triangles
skip degenerate triangles
degenerate case
degenerate case
Todo:
: check if we need some epsilon, due to floating point imprecision
Implements btTriangleCallback.
Definition at line 60 of file btInternalEdgeUtility.cpp.
References btGetAngle(), btGetHash(), cross(), btHashMap< Key, Value >::find(), hash, i, btHashMap< Key, Value >::insert(), length(), btTriangleInfo::m_edgeV0V1Angle, btTriangleInfo::m_edgeV1V2Angle, btTriangleInfo::m_edgeV2V0Angle, btTriangleInfoMap::m_equalVertexThreshold, btTriangleInfo::m_flags, m_partIdA, m_triangleIndexA, m_triangleInfoMap, m_triangleVerticesA, quatRotate(), SIMD_PI, TRI_INFO_V0V1_CONVEX, TRI_INFO_V0V1_SWAP_NORMALB, TRI_INFO_V1V2_CONVEX, TRI_INFO_V1V2_SWAP_NORMALB, TRI_INFO_V2V0_CONVEX, and TRI_INFO_V2V0_SWAP_NORMALB.
Member Data Documentation
int btConnectivityProcessor::m_partIdA
Definition at line 54 of file btInternalEdgeUtility.cpp.
Referenced by btGenerateInternalEdgeInfo(), and processTriangle().
int btConnectivityProcessor::m_triangleIndexA
Definition at line 55 of file btInternalEdgeUtility.cpp.
Referenced by btGenerateInternalEdgeInfo(), and processTriangle().
btTriangleInfoMap* btConnectivityProcessor::m_triangleInfoMap
Definition at line 57 of file btInternalEdgeUtility.cpp.
Referenced by btGenerateInternalEdgeInfo(), and processTriangle().
btVector3* btConnectivityProcessor::m_triangleVerticesA
Definition at line 56 of file btInternalEdgeUtility.cpp.
Referenced by btGenerateInternalEdgeInfo(), and processTriangle().
The documentation for this struct was generated from the following file:
btInternalEdgeUtility.cpp