Blender: openexr_multi.h File Reference
openexr_multi.h File Reference
OpenEXR
Defines
#define EXR_LAY_MAXNAME 19
#define EXR_PASS_MAXNAME 11
#define EXR_TOT_MAXNAME 32
#define EXR_PASS_MAXCHAN 8
Functions
void * IMB_exr_get_handle (void)
void IMB_exr_add_channel (void *handle, const char *layname, const char *passname, int xstride, int ystride, float *rect)
int IMB_exr_begin_read (void *handle, const char *filename, int *width, int *height)
int IMB_exr_begin_write (void *handle, const char *filename, int width, int height, int compress)
void IMB_exrtile_begin_write (void *handle, const char *filename, int mipmap, int width, int height, int tilex, int tiley)
void IMB_exr_set_channel (void *handle, const char *layname, const char *passname, int xstride, int ystride, float *rect)
void IMB_exr_read_channels (void *handle)
void IMB_exr_write_channels (void *handle)
void IMB_exrtile_write_channels (void *handle, int partx, int party, int level)
void IMB_exrtile_clear_channels (void *handle)
void IMB_exr_multilayer_convert (void *handle, void *base, void *(*addlayer)(void *base, char *str), void(*addpass)(void *base, void *lay, char *str, float *rect, int totchan, char *chan_id))
void IMB_exr_close (void *handle)
Detailed Description
Definition in file openexr_multi.h.
Define Documentation
#define EXR_LAY_MAXNAME 19
Definition at line 40 of file openexr_multi.h.
Referenced by exec_output_file_multilayer(), IMB_exr_add_channel(), imb_exr_get_layer(), imb_exr_get_pass(), IMB_exr_set_channel(), imb_exr_split_channel_name(), and ml_addlayer_cb().
#define EXR_PASS_MAXCHAN 8
Definition at line 43 of file openexr_multi.h.
Referenced by imb_exr_begin_read_mem().
#define EXR_PASS_MAXNAME 11
Definition at line 41 of file openexr_multi.h.
Referenced by exec_output_file_multilayer(), IMB_exr_add_channel(), IMB_exr_set_channel(), imb_exr_split_channel_name(), make_pass_name(), and ml_addpass_cb().
#define EXR_TOT_MAXNAME 32
Definition at line 42 of file openexr_multi.h.
Referenced by IMB_exr_add_channel(), imb_exr_begin_read_mem(), and IMB_exr_set_channel().
Function Documentation
void IMB_exr_add_channel (void * handle, const char * layname, const char * passname, int xstride, int ystride, float * rect)
Definition at line 449 of file openexr_api.cpp.
References BLI_addtail(), BLI_strncpy(), ExrHandle::channels, data, EXR_LAY_MAXNAME, EXR_PASS_MAXNAME, EXR_TOT_MAXNAME, MEM_callocN(), ExrChannel::name, ExrChannel::rect, ExrChannel::xstride, and ExrChannel::ystride.
Referenced by exec_output_file_multilayer(), IMB_exr_begin_read(), imb_exr_begin_read_mem(), RE_WriteRenderResult(), render_layer_add_pass(), and render_result_new().
int IMB_exr_begin_read (void * handle, const char * filename, int * width, int * height)
Definition at line 530 of file openexr_api.cpp.
References BLI_exists(), BLI_file_size(), data, ExrHandle::height, i, ExrHandle::ifile, IMB_exr_add_channel(), NULL, and ExrHandle::width.
Referenced by render_result_exr_file_read_path().
int IMB_exr_begin_write (void * handle, const char * filename, int width, int height, int compress)
Definition at line 475 of file openexr_api.cpp.
References ExrHandle::channels, data, ListBase::first, ExrHandle::height, ExrChannel::name, ExrChannel::next, NULL, ExrHandle::ofile, openexr_header_compression(), and ExrHandle::width.
Referenced by exec_output_file_multilayer(), and RE_WriteRenderResult().
void IMB_exr_close (void * handle)
Definition at line 698 of file openexr_api.cpp.
References BLI_freelistN(), BLI_remlink(), ExrHandle::channels, data, exrhandles, ListBase::first, ExrHandle::ifile, ExrHandle::layers, MEM_freeN(), ExrPass::next, ExrLayer::next, NULL, ExrHandle::ofile, ExrLayer::passes, ExrPass::rect, and ExrHandle::tofile.
Referenced by exec_output_file_multilayer(), image_create_multilayer(), imb_exr_begin_read_mem(), RE_WriteRenderResult(), render_result_exr_file_end(), and render_result_exr_file_read_path().
void* IMB_exr_get_handle (void)
Definition at line 440 of file openexr_api.cpp.
References BLI_addtail(), data, exrhandles, MEM_callocN(), and NULL.
Referenced by exec_output_file_multilayer(), imb_exr_begin_read_mem(), RE_WriteRenderResult(), render_result_exr_file_read_path(), and render_result_new().
void IMB_exr_multilayer_convert (void * handle, void * base, void *(*)(void *base, char *str) addlayer, void(*)(void *base, void *lay, char *str, float *rect, int totchan, char *chan_id) addpass)
Definition at line 672 of file openexr_api.cpp.
References ExrPass::chan_id, data, ListBase::first, ExrHandle::layers, ExrPass::name, ExrLayer::name, ExrPass::next, ExrLayer::next, NULL, ExrLayer::passes, ExrPass::rect, and ExrPass::totchan.
Referenced by render_result_new_from_exr().
void IMB_exr_read_channels (void * handle)
Definition at line 638 of file openexr_api.cpp.
References ExrHandle::channels, data, ListBase::first, ExrHandle::height, ExrHandle::ifile, ExrChannel::name, ExrChannel::next, ExrChannel::rect, ExrHandle::width, ExrChannel::xstride, and ExrChannel::ystride.
Referenced by imb_load_openexr(), and render_result_exr_file_read_path().
void IMB_exr_set_channel (void * handle, const char * layname, const char * passname, int xstride, int ystride, float * rect)
Definition at line 553 of file openexr_api.cpp.
References BLI_findstring(), BLI_strncpy(), ExrHandle::channels, data, EXR_LAY_MAXNAME, EXR_PASS_MAXNAME, EXR_TOT_MAXNAME, ExrLayer::name, ExrChannel::rect, ExrChannel::xstride, and ExrChannel::ystride.
Referenced by render_result_exr_file_read_path(), and save_render_result_tile().
void IMB_exr_write_channels (void * handle)
Definition at line 610 of file openexr_api.cpp.
References ExrHandle::channels, data, ListBase::first, ExrHandle::height, ExrChannel::name, ExrChannel::next, ExrHandle::ofile, ExrChannel::rect, ExrHandle::width, ExrChannel::xstride, and ExrChannel::ystride.
Referenced by exec_output_file_multilayer(), and RE_WriteRenderResult().
void IMB_exrtile_begin_write (void * handle, const char * filename, int mipmap, int width, int height, int tilex, int tiley)
Definition at line 505 of file openexr_api.cpp.
References ExrHandle::channels, data, ListBase::first, ExrHandle::height, ExrHandle::mipmap, ExrChannel::name, ExrChannel::next, ExrHandle::tilex, ExrHandle::tiley, ExrHandle::tofile, and ExrHandle::width.
Referenced by render_result_exr_file_begin().
void IMB_exrtile_clear_channels (void * handle)
Definition at line 580 of file openexr_api.cpp.
References BLI_freelistN(), ExrHandle::channels, and data.
Referenced by save_empty_result_tiles().
void IMB_exrtile_write_channels (void * handle, int partx, int party, int level)
Definition at line 586 of file openexr_api.cpp.
References ExrHandle::channels, data, ListBase::first, ExrChannel::name, ExrChannel::next, ExrChannel::rect, ExrHandle::tilex, ExrHandle::tiley, ExrHandle::tofile, ExrChannel::xstride, and ExrChannel::ystride.
Referenced by save_empty_result_tiles(), and save_render_result_tile().