Blender: bmesh_py_types_meshdata.h File Reference
bmesh_py_types_meshdata.h File Reference
Classes
struct BPy_BMGenericMeshData
Defines
#define BPy_BMLoopUV_Check(v) (Py_TYPE(v) == &BPy_BMLoopUV_Type)
Typedefs
typedef struct
BPy_BMGenericMeshData BPy_BMGenericMeshData
Functions
int BPy_BMLoopUV_AssignPyObject (struct MLoopUV *data, PyObject *value)
PyObject * BPy_BMLoopUV_CreatePyObject (struct MLoopUV *data)
int BPy_BMLoopColor_AssignPyObject (struct MLoopCol *data, PyObject *value)
PyObject * BPy_BMLoopColor_CreatePyObject (struct MLoopCol *data)
int BPy_BMDeformVert_AssignPyObject (struct MDeformVert *dvert, PyObject *value)
PyObject * BPy_BMDeformVert_CreatePyObject (struct MDeformVert *dvert)
void BPy_BM_init_types_meshdata (void)
Variables
PyTypeObject BPy_BMLoopUV_Type
PyTypeObject BPy_BMDeformVert_Type
Detailed Description
Definition in file bmesh_py_types_meshdata.h.
Define Documentation
#define BPy_BMLoopUV_Check (v) (Py_TYPE(v) == &BPy_BMLoopUV_Type)
Definition at line 36 of file bmesh_py_types_meshdata.h.
Typedef Documentation
typedef struct BPy_BMGenericMeshData BPy_BMGenericMeshData
Function Documentation
void BPy_BM_init_types_meshdata (void)
Definition at line 597 of file bmesh_py_types_meshdata.c.
References bm_init_types_bmdvert(), bm_init_types_bmloopcol(), and bm_init_types_bmloopuv().
Referenced by BPyInit_bmesh().
int BPy_BMDeformVert_AssignPyObject (struct MDeformVert * dvert, PyObject * value)
Definition at line 571 of file bmesh_py_types_meshdata.c.
References BPy_BMDeformVert_Check, defvert_copy(), LIKELY, and UNLIKELY.
Referenced by BPy_BMLayerItem_SetItem().
PyObject* BPy_BMDeformVert_CreatePyObject (struct MDeformVert * dvert)
Definition at line 586 of file bmesh_py_types_meshdata.c.
Referenced by BPy_BMLayerItem_GetItem().
int BPy_BMLoopColor_AssignPyObject (struct MLoopCol * data, PyObject * value)
Definition at line 235 of file bmesh_py_types_meshdata.c.
References mathutils_array_parse(), and mloopcol_from_float().
Referenced by BPy_BMLayerItem_SetItem().
PyObject* BPy_BMLoopColor_CreatePyObject (struct MLoopCol * data)
Definition at line 247 of file bmesh_py_types_meshdata.c.
References Color_CreatePyObject_cb(), and NULL.
Referenced by BPy_BMLayerItem_GetItem().
int BPy_BMLoopUV_AssignPyObject (struct MLoopUV * data, PyObject * value)
Definition at line 138 of file bmesh_py_types_meshdata.c.
References BPy_BMLoopUV_Check, and UNLIKELY.
Referenced by BPy_BMLayerItem_SetItem().
PyObject* BPy_BMLoopUV_CreatePyObject (struct MLoopUV * data)
Definition at line 150 of file bmesh_py_types_meshdata.c.
Referenced by BPy_BMLayerItem_GetItem().
Variable Documentation
PyTypeObject BPy_BMDeformVert_Type
Definition at line 551 of file bmesh_py_types_meshdata.c.
Referenced by BPyInit_bmesh_types().
PyTypeObject BPy_BMLoopUV_Type
Definition at line 121 of file bmesh_py_types_meshdata.c.
Referenced by BPyInit_bmesh_types().