Blender: Exception Class Reference
Exception Class Reference
#include <Exception.h>
Public Member Functions
Exception ()
virtual ~Exception () throw ()
Exception (const Exception &xpt)
Exception & operator= (const Exception &xpt)
virtual const char * what (void)
Exception (ExceptionID &expID, RESULT rslt, const char *fil, int lin)
void setFileLine (const char *fil, int lin)
std::string & getDesc (void) throw ()
virtual void report (void)
ExceptionID * getID (void) throw ()
Static Public Attributes
static std::string m_lastError
last exception description
static const char * m_logFile = NULL
log file name
Protected Member Functions
virtual void setXptDesc (void)
void copy (const Exception &xpt)
Protected Attributes
ExceptionID * m_expID
RESULT m_hRslt
std::string m_desc
std::string m_fileName
int m_line
Detailed Description
Definition at line 149 of file Exception.h.
Constructor & Destructor Documentation
Exception::Exception ()
Definition at line 70 of file Exception.cpp.
References ErrNotFound, m_expID, m_hRslt, m_line, and S_OK.
Exception::~Exception () throw () [virtual]
Definition at line 80 of file Exception.cpp.
Exception::Exception (const Exception & xpt)
Definition at line 84 of file Exception.cpp.
References copy().
Exception::Exception (ExceptionID & expID, RESULT rslt, const char * fil, int lin)
Definition at line 104 of file Exception.cpp.
References setFileLine().
Member Function Documentation
void Exception::copy (const Exception & xpt) [protected]
Definition at line 190 of file Exception.cpp.
References m_desc, m_expID, m_fileName, m_hRslt, and m_line.
Referenced by Exception(), and operator=().
std::string& Exception::getDesc (void) throw () [inline]
Definition at line 169 of file Exception.h.
References m_desc.
ExceptionID* Exception::getID (void) throw () [inline]
Definition at line 175 of file Exception.h.
References m_expID.
Exception & Exception::operator= (const Exception & xpt)
Definition at line 89 of file Exception.cpp.
References copy().
void Exception::report (void) [virtual]
Definition at line 122 of file Exception.cpp.
References logf, m_desc, m_fileName, m_line, m_logFile, NULL, setXptDesc(), and what().
Referenced by Image_getbuffer(), Image_getImage(), ImageMirror_init(), ImageRender_init(), ImageViewport_setCaptureSize(), ImageViewport_setWhole(), load(), and Texture_init().
void Exception::setFileLine (const char * fil, int lin)
Definition at line 114 of file Exception.cpp.
References m_fileName, m_line, and NULL.
Referenced by Exception().
void Exception::setXptDesc (void) [protected, virtual]
Definition at line 141 of file Exception.cpp.
References hex, m_desc, ExpDesc::m_expDescs, m_expID, m_hRslt, and m_lastError.
Referenced by report(), and what().
const char * Exception::what (void) [virtual]
Definition at line 94 of file Exception.cpp.
References m_desc, and setXptDesc().
Referenced by report().
Member Data Documentation
std::string Exception::m_desc [protected]
Definition at line 190 of file Exception.h.
Referenced by copy(), getDesc(), report(), setXptDesc(), and what().
ExceptionID* Exception::m_expID [protected]
Definition at line 185 of file Exception.h.
Referenced by copy(), Exception(), getID(), and setXptDesc().
std::string Exception::m_fileName [protected]
Definition at line 199 of file Exception.h.
Referenced by copy(), report(), and setFileLine().
RESULT Exception::m_hRslt [protected]
Definition at line 187 of file Exception.h.
Referenced by copy(), Exception(), and setXptDesc().
std::string Exception::m_lastError [static]
last exception description
Definition at line 178 of file Exception.h.
Referenced by getLastError(), initVideoTexture(), and setXptDesc().
int Exception::m_line [protected]
Definition at line 201 of file Exception.h.
Referenced by copy(), Exception(), report(), and setFileLine().
const char * Exception::m_logFile = NULL [static]
log file name
Definition at line 181 of file Exception.h.
Referenced by report(), and setLogFile().
The documentation for this class was generated from the following files:
Exception.h
Exception.cpp