Blender: node_shader_tex_wave.c File Reference
node_shader_tex_wave.c File Reference
#include "../node_shader_util.h"
Functions
static void node_shader_init_tex_wave (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static int node_shader_gpu_tex_wave (GPUMaterial *mat, bNode *node, GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_tex_wave (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_tex_wave_in []
static bNodeSocketTemplate sh_node_tex_wave_out []
Function Documentation
static int node_shader_gpu_tex_wave (GPUMaterial * mat, bNode * node, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 57 of file node_shader_tex_wave.c.
References CD_ORCO, GPU_attribute(), GPU_stack_link(), link(), GPUNodeStack::link, and node_shader_gpu_tex_mapping().
Referenced by register_node_type_sh_tex_wave().
static void node_shader_init_tex_wave (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 47 of file node_shader_tex_wave.c.
References NodeTexWave::base, NodeTexBase::color_mapping, default_color_mapping(), default_tex_mapping(), MEM_callocN(), SHD_WAVE_BANDS, bNode::storage, NodeTexBase::tex_mapping, and NodeTexWave::wave_type.
Referenced by register_node_type_sh_tex_wave().
void register_node_type_sh_tex_wave (bNodeTreeType * ttype)
Definition at line 68 of file node_shader_tex_wave.c.
References NODE_CLASS_TEXTURE, node_copy_standard_storage(), node_free_standard_storage(), NODE_NEW_SHADING, NODE_OPTIONS, node_shader_gpu_tex_wave(), node_shader_init_tex_wave(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_WAVE.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_tex_wave_in[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 1, "Vector",       0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_NONE, SOCK_HIDE_VALUE},
    {   SOCK_FLOAT, 1, "Scale",         5.0f, 0.0f, 0.0f, 0.0f, -1000.0f, 1000.0f},
    {   SOCK_FLOAT, 1, "Distortion",    0.0f, 0.0f, 0.0f, 0.0f, -1000.0f, 1000.0f},
    {   SOCK_FLOAT, 1, "Detail",        2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 16.0f},
    {   SOCK_FLOAT, 1, "Detail Scale",  1.0f, 0.0f, 0.0f, 0.0f, -1000.0f, 1000.0f},
    {   -1, 0, ""   }
}
Definition at line 32 of file node_shader_tex_wave.c.
bNodeSocketTemplate sh_node_tex_wave_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Color",      0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_FLOAT, 0, "Fac",       0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 41 of file node_shader_tex_wave.c.