Blender: MaterialsExporter Class Reference
MaterialsExporter Class Reference
#include <MaterialExporter.h>
Public Member Functions
MaterialsExporter (COLLADASW::StreamWriter *sw, const ExportSettings *export_settings)
void exportMaterials (Scene *sce)
void operator() (Material *ma, Object *ob)
Detailed Description
Definition at line 47 of file MaterialExporter.h.
Constructor & Destructor Documentation
MaterialsExporter::MaterialsExporter (COLLADASW::StreamWriter * sw, const ExportSettings * export_settings)
Definition at line 34 of file MaterialExporter.cpp.
Member Function Documentation
void MaterialsExporter::exportMaterials (Scene * sce)
Definition at line 36 of file MaterialExporter.cpp.
References MaterialFunctor::forEachMaterialInScene(), and ExportSettings::selected.
Referenced by DocumentExporter::exportCurrentScene().
void MaterialsExporter::operator() (Material * ma, Object * ob)
Definition at line 70 of file MaterialExporter.cpp.
References get_material_id(), id_name(), and translate_id().
The documentation for this class was generated from the following files:
MaterialExporter.h
MaterialExporter.cpp