Blender: KX_MouseFocusSensor Class Reference
KX_MouseFocusSensor Class Reference
#include <KX_MouseFocusSensor.h>
Public Member Functions
KX_MouseFocusSensor (class SCA_MouseManager *eventmgr, int startx, int starty, short int mousemode, int focusmode, bool bTouchPulse, KX_Scene *kxscene, KX_KetsjiEngine *kxengine, SCA_IObject *gameobj)
virtual ~KX_MouseFocusSensor ()
virtual CValue * GetReplica ()
virtual void Replace_IScene (SCA_IScene *val)
virtual bool Evaluate ()
virtual void Init ()
virtual bool IsPositiveTrigger ()
bool RayHit (KX_ClientObjectInfo *client, KX_RayCast *result, void *const data)
bool NeedRayCast (KX_ClientObjectInfo *client)
const MT_Point3 & RaySource () const
const MT_Point3 & RayTarget () const
const MT_Point3 & HitPosition () const
const MT_Vector3 & HitNormal () const
const MT_Vector2 & HitUV () const
Public Attributes
SCA_IObject * m_hitObject
void * m_hitObject_Last
Detailed Description
The mouse focus sensor extends the basic SCA_MouseSensor. It has been placed in KX because it needs access to the rasterizer and SuMO.
extend the valid modes?
Definition at line 47 of file KX_MouseFocusSensor.h.
Constructor & Destructor Documentation
KX_MouseFocusSensor::KX_MouseFocusSensor (class SCA_MouseManager * eventmgr, int startx, int starty, short int mousemode, int focusmode, bool bTouchPulse, KX_Scene * kxscene, KX_KetsjiEngine * kxengine, SCA_IObject * gameobj)
Definition at line 62 of file KX_MouseFocusSensor.cpp.
References Init().
Referenced by GetReplica().
virtual KX_MouseFocusSensor::~KX_MouseFocusSensor () [inline, virtual]
Definition at line 64 of file KX_MouseFocusSensor.h.
Member Function Documentation
bool KX_MouseFocusSensor::Evaluate () [virtual]
Attention:
Overrides default evaluate.
Reimplemented from SCA_MouseSensor.
Definition at line 94 of file KX_MouseFocusSensor.cpp.
References m_hitObject, m_hitObject_Last, SCA_ISensor::m_level, and SCA_ISensor::m_reset.
virtual CValue* KX_MouseFocusSensor::GetReplica (void) [inline, virtual]
Reimplemented from SCA_MouseSensor.
Definition at line 65 of file KX_MouseFocusSensor.h.
References KX_MouseFocusSensor(), and CValue::ProcessReplica().
const MT_Vector3 & KX_MouseFocusSensor::HitNormal () const
Definition at line 339 of file KX_MouseFocusSensor.cpp.
const MT_Point3 & KX_MouseFocusSensor::HitPosition () const
Definition at line 334 of file KX_MouseFocusSensor.cpp.
const MT_Vector2 & KX_MouseFocusSensor::HitUV () const
Definition at line 344 of file KX_MouseFocusSensor.cpp.
void KX_MouseFocusSensor::Init (void) [virtual]
Reimplemented from SCA_MouseSensor.
Definition at line 80 of file KX_MouseFocusSensor.cpp.
References m_hitObject, m_hitObject_Last, SCA_ISensor::m_invert, SCA_ISensor::m_reset, NULL, and MT_Tuple3::setValue().
Referenced by KX_MouseFocusSensor().
virtual bool KX_MouseFocusSensor::IsPositiveTrigger () [inline, virtual]
Reimplemented from SCA_MouseSensor.
Definition at line 84 of file KX_MouseFocusSensor.h.
References SCA_ISensor::m_invert.
bool KX_MouseFocusSensor::NeedRayCast (KX_ClientObjectInfo * client) [inline]
Definition at line 91 of file KX_MouseFocusSensor.h.
bool KX_MouseFocusSensor::RayHit (KX_ClientObjectInfo * client, KX_RayCast * result, void *const data)
Definition at line 140 of file KX_MouseFocusSensor.cpp.
References SCA_ILogicBrick::GetParent(), KX_ClientObjectInfo::m_gameobject, KX_RayCast::m_hitNormal, m_hitObject, KX_RayCast::m_hitPoint, and KX_RayCast::m_hitUV.
const MT_Point3 & KX_MouseFocusSensor::RaySource () const
Definition at line 324 of file KX_MouseFocusSensor.cpp.
const MT_Point3 & KX_MouseFocusSensor::RayTarget () const
Definition at line 329 of file KX_MouseFocusSensor.cpp.
virtual void KX_MouseFocusSensor::Replace_IScene (SCA_IScene * val) [inline, virtual]
Reimplemented from SCA_ILogicBrick.
Definition at line 72 of file KX_MouseFocusSensor.h.
Member Data Documentation
SCA_IObject* KX_MouseFocusSensor::m_hitObject
Definition at line 117 of file KX_MouseFocusSensor.h.
Referenced by Evaluate(), Init(), and RayHit().
void* KX_MouseFocusSensor::m_hitObject_Last
Definition at line 118 of file KX_MouseFocusSensor.h.
Referenced by Evaluate(), and Init().
The documentation for this class was generated from the following files:
KX_MouseFocusSensor.h
KX_MouseFocusSensor.cpp