Blender: ntlRenderGlobals Class Reference
ntlRenderGlobals Class Reference
Class that handles global rendering parameters.
#include <ntl_world.h>
Public Member Functions
ntlRenderGlobals ()
Standard constructor.
~ntlRenderGlobals ()
Destructor.
ntlScene * getRenderScene (void)
Returns the renderscene manager (scene changes for each frame)
void setRenderScene (ntlScene *set)
Set the renderscene manager.
ntlScene * getSimScene (void)
Returns the simulation scene manager (static scene with sim objects)
void setSimScene (ntlScene *set)
Set the simulation scene manager.
vector< ntlLightObject * > * getLightList (void)
Returns the light object list.
void setLightList (vector< ntlLightObject * > *set)
Set the light list.
vector< ntlMaterial * > * getMaterials (void)
Returns the property object list.
void setMaterials (vector< ntlMaterial * > *set)
Set the property list.
vector< SimulationObject * > * getSims (void)
Returns the list of simulations.
void setSims (vector< SimulationObject * > *set)
Set the pointer to the list of simulations.
void setResX (unsigned int set)
Set the x resolution.
void setResY (unsigned int set)
Set the y resolution.
void setAADepth (int set)
Set the anti-aliasing depth.
void setMaxColVal (unsigned int set)
Set the max color value.
void setRayMaxDepth (unsigned int set)
Set the maximum ray recursion.
void setEye (ntlVec3Gfx set)
Set the eye point.
void setLookat (ntlVec3Gfx set)
Set the look at vector.
void setUpVec (ntlVec3Gfx set)
Set the up vector.
void setAspect (float set)
Set the image aspect.
void setFovy (float set)
Set the field of view.
void setBackgroundCol (ntlColor set)
Set the background color.
void setAmbientLight (ntlColor set)
Set the ambient lighting color.
void setDebugOut (int set)
Set the debug output var.
void setAniStart (int set)
Set the animation start time.
void setAniFrames (int set)
Set the animation number of frames.
void setAniCount (int set)
Set the animation.
void setCounterRays (int set)
Set the ray counter.
void setCounterShades (int set)
Set the ray shades counter.
void setCounterSceneInter (int set)
Set the scenen intersection counter.
void setFrameSkip (int set)
Set if existing frames should be skipped.
void setOutFilename (string set)
Set the outfilename.
void setTreeMaxDepth (int set)
get Maximum depth for BSP tree
void setTreeMaxTriangles (int set)
get Maxmimum nr of triangles per BSP tree node
void setTestSphereEnabled (bool set)
set the enable flag of the test sphere
void setTestSphereCenter (ntlVec3Gfx set)
set the center of the test sphere
void setTestSphereRadius (gfxReal set)
set the radius of the test sphere
void setTestSphereMaterialName (char *set)
set the material name of the test sphere
void setDebugPixel (int setx, int sety)
set debugging pixel coordinates
void setTestMode (bool set)
set test mode flag
void setSingleFrameMode (bool set)
set single frame mode flag
void setSingleFrameFilename (string set)
set single frame mode filename
unsigned int getResX (void)
Return the x resolution.
unsigned int getResY (void)
Return the y resolution.
int getAADepth (void)
Return the anti-aliasing depth.
unsigned int getMaxColVal (void)
Return the max color value for ppm.
unsigned int getRayMaxDepth (void)
Return the maximum ray recursion.
ntlVec3Gfx getEye (void)
Return the eye point.
ntlVec3Gfx getLookat (void)
Return the look at vector.
ntlVec3Gfx getUpVec (void)
Return the up vector.
float getAspect (void)
Return the image aspect.
float getFovy (void)
Return the field of view.
ntlColor getBackgroundCol (void)
Return the background color.
ntlColor getAmbientLight (void)
Return the ambient color.
int getDebugOut (void)
Return the debug mode setting.
int getAniStart (void)
Return the animation start time.
int getAniFrames (void)
Return the animation frame number.
int getAniCount (void)
Return the animation counter.
int getCounterRays (void)
Return the ray counter.
int getCounterShades (void)
Return the ray shades counter.
int getCounterSceneInter (void)
Return the scene intersection counter.
int getFrameSkip (void)
Check if existing frames should be skipped.
string getOutFilename (void)
Return the outfilename.
int getTreeMaxDepth (void)
get Maximum depth for BSP tree
int getTreeMaxTriangles (void)
get Maxmimum nr of triangles per BSP tree node
AttributeList * getOpenGlAttributes (void)
get open gl attribute list
AttributeList * getBlenderAttributes (void)
get blender output attribute list
bool getTestSphereEnabled (void)
is the test sphere enabled?
ntlVec3Gfx getTestSphereCenter (void)
get the center of the test sphere
gfxReal getTestSphereRadius (void)
get the radius of the test sphere
char * getTestSphereMaterialName (void)
get the materialname of the test sphere
int getDebugPixelX (void)
get the debug pixel coordinate
int getDebugPixelY (void)
get the debug pixel coordinate
bool getTestMode (void)
get test mode flag
bool getSingleFrameMode ()
set single frame mode flag
string getSingleFrameFilename ()
set single frame mode filename
Detailed Description
Class that handles global rendering parameters.
Definition at line 122 of file ntl_world.h.
Constructor & Destructor Documentation
ntlRenderGlobals::ntlRenderGlobals ()
Standard constructor.
Definition at line 876 of file ntl_world.cpp.
ntlRenderGlobals::~ntlRenderGlobals ()
Destructor.
Definition at line 905 of file ntl_world.cpp.
Member Function Documentation
int ntlRenderGlobals::getAADepth (void) [inline]
Return the anti-aliasing depth.
Definition at line 228 of file ntl_world.h.
Referenced by ntlWorld::renderScene().
ntlColor ntlRenderGlobals::getAmbientLight (void) [inline]
Return the ambient color.
Definition at line 246 of file ntl_world.h.
Referenced by ntlRay::shade().
int ntlRenderGlobals::getAniCount (void) [inline]
Return the animation counter.
Definition at line 255 of file ntl_world.h.
Referenced by ntlBlenderDumper::renderScene(), and ntlWorld::renderScene().
int ntlRenderGlobals::getAniFrames (void) [inline]
Return the animation frame number.
Definition at line 253 of file ntl_world.h.
Referenced by ntlWorld::addDomain(), ntlWorld::renderAnimation(), and ntlWorld::renderScene().
int ntlRenderGlobals::getAniStart (void) [inline]
Return the animation start time.
Definition at line 251 of file ntl_world.h.
float ntlRenderGlobals::getAspect (void) [inline]
Return the image aspect.
Definition at line 240 of file ntl_world.h.
Referenced by ntlWorld::renderScene().
ntlColor ntlRenderGlobals::getBackgroundCol (void) [inline]
Return the background color.
Definition at line 244 of file ntl_world.h.
Referenced by ntlRay::shade().
AttributeList* ntlRenderGlobals::getBlenderAttributes (void) [inline]
get blender output attribute list
Definition at line 277 of file ntl_world.h.
int ntlRenderGlobals::getCounterRays (void) [inline]
Return the ray counter.
Definition at line 257 of file ntl_world.h.
Referenced by ntlRay::ntlRay().
int ntlRenderGlobals::getCounterSceneInter (void) [inline]
Return the scene intersection counter.
Definition at line 261 of file ntl_world.h.
Referenced by ntlScene::intersectScene(), and ntlWorld::renderScene().
int ntlRenderGlobals::getCounterShades (void) [inline]
Return the ray shades counter.
Definition at line 259 of file ntl_world.h.
Referenced by ntlWorld::renderScene(), and ntlRay::shade().
int ntlRenderGlobals::getDebugOut (void) [inline]
Return the debug mode setting.
Definition at line 248 of file ntl_world.h.
Referenced by ntlLightObject::getShadedColor(), ntlLightObject::illuminatePoint(), ntlWorld::renderScene(), and ntlRay::shade().
int ntlRenderGlobals::getDebugPixelX (void) [inline]
get the debug pixel coordinate
Definition at line 288 of file ntl_world.h.
Referenced by ntlWorld::renderScene().
int ntlRenderGlobals::getDebugPixelY (void) [inline]
get the debug pixel coordinate
Definition at line 290 of file ntl_world.h.
Referenced by ntlWorld::renderScene().
ntlVec3Gfx ntlRenderGlobals::getEye (void) [inline]
Return the eye point.
Definition at line 234 of file ntl_world.h.
Referenced by ntlWorld::renderScene().
float ntlRenderGlobals::getFovy (void) [inline]
Return the field of view.
Definition at line 242 of file ntl_world.h.
Referenced by ntlWorld::renderScene().
int ntlRenderGlobals::getFrameSkip (void) [inline]
Check if existing frames should be skipped.
Definition at line 263 of file ntl_world.h.
Referenced by ntlWorld::renderScene().
vector<ntlLightObject*>* ntlRenderGlobals::getLightList (void) [inline]
Returns the light object list.
Definition at line 141 of file ntl_world.h.
Referenced by ntlRay::shade(), and ntlScene::~ntlScene().
ntlVec3Gfx ntlRenderGlobals::getLookat (void) [inline]
Return the look at vector.
Definition at line 236 of file ntl_world.h.
Referenced by ntlWorld::renderScene().
vector<ntlMaterial*>* ntlRenderGlobals::getMaterials (void) [inline]
Returns the property object list.
Definition at line 146 of file ntl_world.h.
Referenced by ntlScene::buildScene(), ntlGeometryObjModel::initialize(), ntlGeometryObject::initialize(), SimulationObject::initializeLbmSimulation(), and ntlScene::~ntlScene().
unsigned int ntlRenderGlobals::getMaxColVal (void) [inline]
Return the max color value for ppm.
Definition at line 230 of file ntl_world.h.
AttributeList* ntlRenderGlobals::getOpenGlAttributes (void) [inline]
get open gl attribute list
Definition at line 275 of file ntl_world.h.
string ntlRenderGlobals::getOutFilename (void) [inline]
Return the outfilename.
Definition at line 267 of file ntl_world.h.
Referenced by ntlBlenderDumper::renderScene(), and ntlWorld::renderScene().
unsigned int ntlRenderGlobals::getRayMaxDepth (void) [inline]
Return the maximum ray recursion.
Definition at line 232 of file ntl_world.h.
ntlScene* ntlRenderGlobals::getRenderScene (void) [inline]
Returns the renderscene manager (scene changes for each frame)
Definition at line 131 of file ntl_world.h.
Referenced by ntlWorld::addDomain(), elbeemAddMesh(), ntlWorld::finishWorldInit(), ntlLightObject::illuminatePoint(), ntlWorld::renderScene(), ntlRay::shade(), and ntlWorld::~ntlWorld().
unsigned int ntlRenderGlobals::getResX (void) [inline]
Return the x resolution.
Definition at line 224 of file ntl_world.h.
Referenced by ntlScene::buildScene(), and ntlWorld::renderScene().
unsigned int ntlRenderGlobals::getResY (void) [inline]
Return the y resolution.
Definition at line 226 of file ntl_world.h.
Referenced by ntlScene::buildScene(), and ntlWorld::renderScene().
vector<SimulationObject*>* ntlRenderGlobals::getSims (void) [inline]
Returns the list of simulations.
Definition at line 151 of file ntl_world.h.
Referenced by ntlWorld::addDomain().
ntlScene* ntlRenderGlobals::getSimScene (void) [inline]
Returns the simulation scene manager (static scene with sim objects)
Definition at line 136 of file ntl_world.h.
Referenced by ntlWorld::addDomain(), elbeemAddMesh(), ntlWorld::finishWorldInit(), SimulationObject::initGeoTree(), LbmSolverInterface::initGeoTree(), ntlBlenderDumper::renderScene(), and ntlWorld::~ntlWorld().
string ntlRenderGlobals::getSingleFrameFilename () [inline]
set single frame mode filename
Definition at line 296 of file ntl_world.h.
Referenced by ntlWorld::renderScene().
bool ntlRenderGlobals::getSingleFrameMode () [inline]
set single frame mode flag
Definition at line 294 of file ntl_world.h.
Referenced by ntlWorld::finishWorldInit(), and ntlWorld::renderScene().
bool ntlRenderGlobals::getTestMode (void) [inline]
get test mode flag
Definition at line 292 of file ntl_world.h.
Referenced by ntlScene::buildScene().
ntlVec3Gfx ntlRenderGlobals::getTestSphereCenter (void) [inline]
get the center of the test sphere
Definition at line 282 of file ntl_world.h.
bool ntlRenderGlobals::getTestSphereEnabled (void) [inline]
is the test sphere enabled?
Definition at line 280 of file ntl_world.h.
char* ntlRenderGlobals::getTestSphereMaterialName (void) [inline]
get the materialname of the test sphere
Definition at line 286 of file ntl_world.h.
gfxReal ntlRenderGlobals::getTestSphereRadius (void) [inline]
get the radius of the test sphere
Definition at line 284 of file ntl_world.h.
int ntlRenderGlobals::getTreeMaxDepth (void) [inline]
get Maximum depth for BSP tree
Definition at line 270 of file ntl_world.h.
Referenced by ntlScene::prepareScene().
int ntlRenderGlobals::getTreeMaxTriangles (void) [inline]
get Maxmimum nr of triangles per BSP tree node
Definition at line 272 of file ntl_world.h.
Referenced by ntlScene::prepareScene().
ntlVec3Gfx ntlRenderGlobals::getUpVec (void) [inline]
Return the up vector.
Definition at line 238 of file ntl_world.h.
Referenced by ntlWorld::renderScene().
void ntlRenderGlobals::setAADepth (int set) [inline]
Set the anti-aliasing depth.
Definition at line 160 of file ntl_world.h.
void ntlRenderGlobals::setAmbientLight (ntlColor set) [inline]
Set the ambient lighting color.
Definition at line 178 of file ntl_world.h.
void ntlRenderGlobals::setAniCount (int set) [inline]
Set the animation.
Definition at line 187 of file ntl_world.h.
Referenced by ntlBlenderDumper::renderScene(), and ntlWorld::renderScene().
void ntlRenderGlobals::setAniFrames (int set) [inline]
Set the animation number of frames.
Definition at line 185 of file ntl_world.h.
Referenced by ntlWorld::addDomain().
void ntlRenderGlobals::setAniStart (int set) [inline]
Set the animation start time.
Definition at line 183 of file ntl_world.h.
void ntlRenderGlobals::setAspect (float set) [inline]
Set the image aspect.
Definition at line 172 of file ntl_world.h.
void ntlRenderGlobals::setBackgroundCol (ntlColor set) [inline]
Set the background color.
Definition at line 176 of file ntl_world.h.
void ntlRenderGlobals::setCounterRays (int set) [inline]
Set the ray counter.
Definition at line 189 of file ntl_world.h.
Referenced by ntlRay::ntlRay().
void ntlRenderGlobals::setCounterSceneInter (int set) [inline]
Set the scenen intersection counter.
Definition at line 193 of file ntl_world.h.
Referenced by ntlScene::intersectScene(), and ntlWorld::renderScene().
void ntlRenderGlobals::setCounterShades (int set) [inline]
Set the ray shades counter.
Definition at line 191 of file ntl_world.h.
Referenced by ntlWorld::renderScene(), and ntlRay::shade().
void ntlRenderGlobals::setDebugOut (int set) [inline]
Set the debug output var.
Definition at line 180 of file ntl_world.h.
Referenced by ntlWorld::renderScene().
void ntlRenderGlobals::setDebugPixel (int setx, int sety) [inline]
set debugging pixel coordinates
Definition at line 214 of file ntl_world.h.
void ntlRenderGlobals::setEye (ntlVec3Gfx set) [inline]
Set the eye point.
Definition at line 166 of file ntl_world.h.
void ntlRenderGlobals::setFovy (float set) [inline]
Set the field of view.
Definition at line 174 of file ntl_world.h.
void ntlRenderGlobals::setFrameSkip (int set) [inline]
Set if existing frames should be skipped.
Definition at line 195 of file ntl_world.h.
void ntlRenderGlobals::setLightList (vector< ntlLightObject * > * set) [inline]
Set the light list.
Definition at line 143 of file ntl_world.h.
Referenced by ntlWorld::initDefaults().
void ntlRenderGlobals::setLookat (ntlVec3Gfx set) [inline]
Set the look at vector.
Definition at line 168 of file ntl_world.h.
void ntlRenderGlobals::setMaterials (vector< ntlMaterial * > * set) [inline]
Set the property list.
Definition at line 148 of file ntl_world.h.
Referenced by ntlWorld::initDefaults().
void ntlRenderGlobals::setMaxColVal (unsigned int set) [inline]
Set the max color value.
Definition at line 162 of file ntl_world.h.
void ntlRenderGlobals::setOutFilename (string set) [inline]
Set the outfilename.
Definition at line 198 of file ntl_world.h.
Referenced by ntlWorld::addDomain().
void ntlRenderGlobals::setRayMaxDepth (unsigned int set) [inline]
Set the maximum ray recursion.
Definition at line 164 of file ntl_world.h.
void ntlRenderGlobals::setRenderScene (ntlScene * set) [inline]
Set the renderscene manager.
Definition at line 133 of file ntl_world.h.
Referenced by ntlWorld::initDefaults().
void ntlRenderGlobals::setResX (unsigned int set) [inline]
Set the x resolution.
Definition at line 156 of file ntl_world.h.
Referenced by ntlScene::buildScene().
void ntlRenderGlobals::setResY (unsigned int set) [inline]
Set the y resolution.
Definition at line 158 of file ntl_world.h.
Referenced by ntlScene::buildScene().
void ntlRenderGlobals::setSims (vector< SimulationObject * > * set) [inline]
Set the pointer to the list of simulations.
Definition at line 153 of file ntl_world.h.
Referenced by ntlWorld::initDefaults().
void ntlRenderGlobals::setSimScene (ntlScene * set) [inline]
Set the simulation scene manager.
Definition at line 138 of file ntl_world.h.
Referenced by ntlWorld::initDefaults().
void ntlRenderGlobals::setSingleFrameFilename (string set) [inline]
set single frame mode filename
Definition at line 220 of file ntl_world.h.
Referenced by ntlWorld::setSingleFrameOut().
void ntlRenderGlobals::setSingleFrameMode (bool set) [inline]
set single frame mode flag
Definition at line 218 of file ntl_world.h.
Referenced by ntlWorld::setSingleFrameOut().
void ntlRenderGlobals::setTestMode (bool set) [inline]
set test mode flag
Definition at line 216 of file ntl_world.h.
void ntlRenderGlobals::setTestSphereCenter (ntlVec3Gfx set) [inline]
set the center of the test sphere
Definition at line 208 of file ntl_world.h.
void ntlRenderGlobals::setTestSphereEnabled (bool set) [inline]
set the enable flag of the test sphere
Definition at line 206 of file ntl_world.h.
void ntlRenderGlobals::setTestSphereMaterialName (char * set) [inline]
set the material name of the test sphere
Definition at line 212 of file ntl_world.h.
void ntlRenderGlobals::setTestSphereRadius (gfxReal set) [inline]
set the radius of the test sphere
Definition at line 210 of file ntl_world.h.
void ntlRenderGlobals::setTreeMaxDepth (int set) [inline]
get Maximum depth for BSP tree
Definition at line 201 of file ntl_world.h.
void ntlRenderGlobals::setTreeMaxTriangles (int set) [inline]
get Maxmimum nr of triangles per BSP tree node
Definition at line 203 of file ntl_world.h.
void ntlRenderGlobals::setUpVec (ntlVec3Gfx set) [inline]
Set the up vector.
Definition at line 170 of file ntl_world.h.
The documentation for this class was generated from the following files:
ntl_world.h
ntl_world.cpp