Blender: paint_stroke.c File Reference
paint_stroke.c File Reference
sculpt and paint
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_brush_types.h"
#include "RNA_access.h"
#include "BKE_context.h"
#include "BKE_paint.h"
#include "BKE_brush.h"
#include "WM_api.h"
#include "WM_types.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "ED_screen.h"
#include "ED_view3d.h"
#include "paint_intern.h"
#include <float.h>
#include <math.h>
Classes
struct PaintStroke
Typedefs
typedef struct PaintStroke PaintStroke
Functions
static void paint_draw_smooth_stroke (bContext *C, int x, int y, void *customdata)
static float event_tablet_data (wmEvent *event, int *pen_flip)
static void paint_brush_stroke_add_step (bContext *C, wmOperator *op, wmEvent *event, float mouse_in[2])
static int paint_smooth_stroke (PaintStroke *stroke, float output[2], wmEvent *event)
static int paint_space_stroke (bContext *C, wmOperator *op, wmEvent *event, const float final_mouse[2])
PaintStroke * paint_stroke_new (bContext *C, StrokeGetLocation get_location, StrokeTestStart test_start, StrokeUpdateStep update_step, StrokeDone done, int event_type)
void paint_stroke_free (PaintStroke *stroke)
int paint_space_stroke_enabled (Brush *br)
int paint_stroke_modal (bContext *C, wmOperator *op, wmEvent *event)
int paint_stroke_exec (bContext *C, wmOperator *op)
int paint_stroke_cancel (bContext *C, wmOperator *op)
ViewContext * paint_stroke_view_context (PaintStroke *stroke)
void * paint_stroke_mode_data (struct PaintStroke *stroke)
void paint_stroke_set_mode_data (PaintStroke *stroke, void *mode_data)
int paint_poll (bContext *C)
Detailed Description
Definition in file paint_stroke.c.
Typedef Documentation
typedef struct PaintStroke PaintStroke
Function Documentation
static float event_tablet_data (wmEvent * event, int * pen_flip) [static]
Definition at line 110 of file paint_stroke.c.
References wmTabletData::Active, wmEvent::custom, EVT_DATA_TABLET, EVT_TABLET_ERASER, EVT_TABLET_NONE, and wmTabletData::Pressure.
Referenced by paint_brush_stroke_add_step(), and paint_space_stroke().
static void paint_brush_stroke_add_step (bContext * C, wmOperator * op, wmEvent * event, float mouse_in[2]) [static]
Definition at line 129 of file paint_stroke.c.
References add_v2_v2v2(), brush_jitter_pos(), BRUSH_JITTER_PRESSURE, copy_v2_v2(), CTX_data_scene(), wmOperator::customdata, event_tablet_data(), Brush::flag, PaintStroke::get_location, PaintStroke::last_mouse_position, mul_v2_fl(), ViewContext::obact, paint_brush(), paint_get_active(), wmOperator::ptr, RNA_boolean_set(), RNA_collection_add(), RNA_float_set(), RNA_float_set_array(), Object::sculpt, sub_v2_v2v2(), PaintStroke::update_step, PaintStroke::vc, and zero_v3().
Referenced by paint_space_stroke(), and paint_stroke_modal().
static void paint_draw_smooth_stroke (bContext * C, int x, int y, void * customdata) [static]
Definition at line 89 of file paint_stroke.c.
References BRUSH_SMOOTH_STROKE, CTX_data_scene(), CTX_wm_region(), Brush::flag, PaintStroke::last_mouse_position, paint_brush(), paint_get_active(), sdrawline(), ARegion::winrct, rcti::xmin, and rcti::ymin.
Referenced by paint_stroke_modal().
int paint_poll (bContext * C)
Definition at line 421 of file paint_stroke.c.
References CTX_data_active_object(), CTX_data_scene(), CTX_wm_area(), CTX_wm_region(), p, paint_brush(), paint_get_active(), ARegion::regiontype, RGN_TYPE_WINDOW, SPACE_VIEW3D, and ScrArea::spacetype.
Referenced by paint_stroke_modal(), and sculpt_poll().
static int paint_smooth_stroke (PaintStroke * stroke, float output[2], wmEvent * event) [static]
Definition at line 185 of file paint_stroke.c.
References PaintStroke::brush, BRUSH_ANCHORED, BRUSH_RESTORE_MESH, BRUSH_SMOOTH_STROKE, ELEM4, Brush::flag, PaintStroke::last_mouse_position, Brush::sculpt_tool, SCULPT_TOOL_GRAB, SCULPT_TOOL_ROTATE, SCULPT_TOOL_SNAKE_HOOK, SCULPT_TOOL_THUMB, Brush::smooth_stroke_factor, and Brush::smooth_stroke_radius.
Referenced by paint_stroke_modal().
static int paint_space_stroke (bContext * C, wmOperator * op, wmEvent * event, const float final_mouse[2]) [static]
Definition at line 212 of file paint_stroke.c.
References add_v2_v2(), PaintStroke::brush, brush_size(), brush_use_size_pressure(), copy_v2_v2(), CTX_data_scene(), wmOperator::customdata, event_tablet_data(), i, PaintStroke::last_mouse_position, len_v2(), length(), mul_v2_fl(), NULL, paint_brush_stroke_add_step(), paint_space_stroke_enabled(), Brush::spacing, and sub_v2_v2v2().
Referenced by paint_stroke_modal().
int paint_space_stroke_enabled (Brush * br)
Definition at line 285 of file paint_stroke.c.
References BRUSH_ANCHORED, BRUSH_SPACE, ELEM4, Brush::flag, Brush::sculpt_tool, SCULPT_TOOL_GRAB, SCULPT_TOOL_ROTATE, SCULPT_TOOL_SNAKE_HOOK, and SCULPT_TOOL_THUMB.
Referenced by paint_space_stroke(), paint_stroke_modal(), and sculpt_update_cache_variants().
int paint_stroke_cancel (bContext * C, wmOperator * op)
Definition at line 393 of file paint_stroke.c.
References wmOperator::customdata, PaintStroke::done, MEM_freeN(), NULL, and OPERATOR_CANCELLED.
Referenced by sculpt_brush_stroke_cancel(), vpaint_cancel(), and wpaint_cancel().
int paint_stroke_exec (bContext * C, wmOperator * op)
Definition at line 369 of file paint_stroke.c.
References wmOperator::customdata, PaintStroke::done, MEM_freeN(), NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_BEGIN, RNA_END, PaintStroke::stroke_started, PaintStroke::test_start, and PaintStroke::update_step.
Referenced by sculpt_brush_stroke_exec().
void paint_stroke_free (PaintStroke * stroke)
Definition at line 279 of file paint_stroke.c.
References MEM_freeN().
Referenced by sculpt_brush_stroke_invoke().
int paint_stroke_modal (bContext * C, wmOperator * op, wmEvent * event)
Definition at line 292 of file paint_stroke.c.
References PaintStroke::brush, BRUSH_AIRBRUSH, BRUSH_ANCHORED, BRUSH_SMOOTH_STROKE, CTX_wm_manager(), CTX_wm_window(), wmEvent::customdata, wmOperator::customdata, PaintStroke::done, ELEM, PaintStroke::event_type, Brush::flag, INBETWEEN_MOUSEMOVE, KM_RELEASE, PaintStroke::last_mouse_position, MEM_freeN(), MOUSEMOVE, NDOF_MOTION, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, paint_brush_stroke_add_step(), paint_draw_smooth_stroke(), paint_poll(), paint_smooth_stroke(), paint_space_stroke(), paint_space_stroke_enabled(), Brush::rate, PaintStroke::smooth_stroke_cursor, PaintStroke::stroke_started, PaintStroke::test_start, TIMER, PaintStroke::timer, wmEvent::type, wmEvent::val, WM_event_add_timer(), WM_event_remove_timer(), WM_paint_cursor_activate(), and WM_paint_cursor_end().
Referenced by PAINT_OT_vertex_paint(), PAINT_OT_weight_paint(), and SCULPT_OT_brush_stroke().
void* paint_stroke_mode_data (struct PaintStroke * stroke)
Definition at line 411 of file paint_stroke.c.
References PaintStroke::mode_data.
Referenced by vpaint_stroke_done(), vpaint_stroke_update_step(), wpaint_stroke_done(), and wpaint_stroke_update_step().
PaintStroke* paint_stroke_new (bContext * C, StrokeGetLocation get_location, StrokeTestStart test_start, StrokeUpdateStep update_step, StrokeDone done, int event_type) [read]
Definition at line 258 of file paint_stroke.c.
References ViewContext::ar, PaintStroke::brush, CTX_data_scene(), PaintStroke::done, PaintStroke::event_type, PaintStroke::get_location, PaintStroke::mats, MEM_callocN(), ViewContext::obact, paint_brush(), paint_get_active(), ViewContext::rv3d, PaintStroke::test_start, PaintStroke::update_step, PaintStroke::vc, view3d_get_transformation(), and view3d_set_viewcontext().
Referenced by sculpt_brush_stroke_exec(), sculpt_brush_stroke_invoke(), vpaint_invoke(), and wpaint_invoke().
void paint_stroke_set_mode_data (PaintStroke * stroke, void * mode_data)
Definition at line 416 of file paint_stroke.c.
References PaintStroke::mode_data.
Referenced by vpaint_stroke_test_start(), and wpaint_stroke_test_start().
ViewContext* paint_stroke_view_context (PaintStroke * stroke) [read]
Definition at line 406 of file paint_stroke.c.
References PaintStroke::vc.
Referenced by sculpt_update_cache_invariants(), and sculpt_update_cache_variants().