Blender: AUD_AnimateableProperty Class Reference
AUD_AnimateableProperty Class Reference
#include <AUD_AnimateableProperty.h>
Public Member Functions
AUD_AnimateableProperty (int count=1)
~AUD_AnimateableProperty ()
void lock ()
void unlock ()
void write (const float *data)
void write (const float *data, int position, int count)
void read (float position, float *out)
bool isAnimated () const
Detailed Description
This class saves animation data for float properties.
Definition at line 40 of file AUD_AnimateableProperty.h.
Constructor & Destructor Documentation
AUD_AnimateableProperty::AUD_AnimateableProperty (int count = 1)
Creates a new animateable property.
Parameters:
count The count of floats for a single property.
Definition at line 35 of file AUD_AnimateableProperty.cpp.
References AUD_Buffer::getBuffer().
AUD_AnimateableProperty::~AUD_AnimateableProperty ()
Destroys the animateable property.
Definition at line 49 of file AUD_AnimateableProperty.cpp.
Member Function Documentation
bool AUD_AnimateableProperty::isAnimated () const
Returns whether the property is animated.
Returns:
Whether the property is animated.
Definition at line 154 of file AUD_AnimateableProperty.cpp.
void AUD_AnimateableProperty::lock ()
Locks the property.
Definition at line 54 of file AUD_AnimateableProperty.cpp.
Referenced by read(), and write().
void AUD_AnimateableProperty::read (float position, float * out)
Reads the properties value.
Parameters:
position The position in the animation in frames.
[out] out Where to write the value to.
Definition at line 94 of file AUD_AnimateableProperty.cpp.
References AUD_Buffer::getBuffer(), AUD_Buffer::getSize(), i, lock(), and unlock().
void AUD_AnimateableProperty::unlock ()
Unlocks the previously locked property.
Definition at line 59 of file AUD_AnimateableProperty.cpp.
Referenced by read(), and write().
void AUD_AnimateableProperty::write (const float * data)
Writes the properties value and marks it non-animated.
Parameters:
data The new value.
Definition at line 64 of file AUD_AnimateableProperty.cpp.
References AUD_Buffer::getBuffer(), lock(), and unlock().
Referenced by AUD_SequencerEntry::AUD_SequencerEntry(), AUD_SequencerFactory::AUD_SequencerFactory(), AUD_setSequenceAnimData(), and AUD_setSequencerAnimData().
void AUD_AnimateableProperty::write (const float * data, int position, int count)
Writes the properties value and marks it animated.
Parameters:
data The new value.
position The position in the animation in frames.
count The count of frames to write.
Definition at line 74 of file AUD_AnimateableProperty.cpp.
References AUD_Buffer::assureSize(), AUD_Buffer::getBuffer(), AUD_Buffer::getSize(), i, lock(), and unlock().
The documentation for this class was generated from the following files:
AUD_AnimateableProperty.h
AUD_AnimateableProperty.cpp