Blender: node_composite_brightness.c File Reference
node_composite_brightness.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_brightnesscontrast (bNode *UNUSED(node), float *out, float *in, float *in_brightness, float *in_contrast)
static void node_composit_exec_brightcontrast (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_brightcontrast (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_brightcontrast_in []
static bNodeSocketTemplate cmp_node_brightcontrast_out []
Detailed Description
Definition in file node_composite_brightness.c.
Function Documentation
static void do_brightnesscontrast (bNode * UNUSEDnode, float * out, float * in, float * in_brightness, float * in_contrast) [static]
Definition at line 50 of file node_composite_brightness.c.
References i.
Referenced by node_composit_exec_brightcontrast().
static void node_composit_exec_brightcontrast (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 80 of file node_composite_brightness.c.
References CB_RGBA, CB_VAL, composit3_pixel_processor(), bNodeStack::data, data, do_brightnesscontrast(), dupalloc_compbuf(), free_compbuf(), and typecheck_compbuf().
Referenced by register_node_type_cmp_brightcontrast().
void register_node_type_cmp_brightcontrast (bNodeTreeType * ttype)
Definition at line 95 of file node_composite_brightness.c.
References CMP_NODE_BRIGHTCONTRAST, NODE_CLASS_OP_COLOR, node_composit_exec_brightcontrast(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_brightcontrast_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   SOCK_FLOAT, 1, "Bright",        0.0f, 0.0f, 0.0f, 0.0f, -100.0f, 100.0f, PROP_NONE},
    {   SOCK_FLOAT, 1, "Contrast",      0.0f, 0.0f, 0.0f, 0.0f, -100.0f, 100.0f, PROP_NONE},
    {   -1, 0, ""   }
}
Definition at line 39 of file node_composite_brightness.c.
bNodeSocketTemplate cmp_node_brightcontrast_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 45 of file node_composite_brightness.c.