Blender: iksolver_plugin.h File Reference
iksolver_plugin.h File Reference
ikplugin
#include "ikplugin_api.h"
Functions
void iksolver_initialize_tree (struct Scene *scene, struct Object *ob, float ctime)
void iksolver_execute_tree (struct Scene *scene, struct Object *ob, struct bPoseChannel *pchan, float ctime)
Detailed Description
Definition in file iksolver_plugin.h.
Function Documentation
void iksolver_execute_tree (struct Scene * scene, struct Object * ob, struct bPoseChannel * pchan, float ctime)
Definition at line 525 of file iksolver_plugin.c.
References PoseTree::basis_change, BLI_remlink(), CONSTRAINT_TYPE_KINEMATIC, execute_posetree(), ListBase::first, bPoseChannel::flag, free_posetree(), bPoseChannel::iktree, make_dmats(), PoseTree::pchan, POSE_CHAIN, POSE_DONE, PoseTree::totchannel, PoseTree::type, where_is_ik_bone(), and where_is_pose_bone().
void iksolver_initialize_tree (struct Scene * scene, struct Object * ob, float ctime)