Blender: rna_color.c File Reference
rna_color.c File Reference
RNA
#include <stdlib.h>
#include <stdio.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_color_types.h"
#include "DNA_texture_types.h"
Functions
static void rna_def_curvemappoint (BlenderRNA *brna)
static void rna_def_curvemap (BlenderRNA *brna)
static void rna_def_curvemapping (BlenderRNA *brna)
static void rna_def_color_ramp_element (BlenderRNA *brna)
static void rna_def_color_ramp_element_api (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_color_ramp (BlenderRNA *brna)
static void rna_def_histogram (BlenderRNA *brna)
static void rna_def_scopes (BlenderRNA *brna)
void RNA_def_color (BlenderRNA *brna)
Detailed Description
Definition in file rna_color.c.
Function Documentation
void RNA_def_color (BlenderRNA * brna)
Definition at line 607 of file rna_color.c.
References rna_def_color_ramp(), rna_def_color_ramp_element(), rna_def_curvemap(), rna_def_curvemapping(), rna_def_curvemappoint(), rna_def_histogram(), and rna_def_scopes().
static void rna_def_color_ramp (BlenderRNA * brna) [static]
Definition at line 480 of file rna_color.c.
References FLT_MAX, NULL, PROP_COLLECTION, PROP_COLOR, PROP_EDITABLE, PROP_ENUM, PROP_INT, PROP_NONE, PROP_REQUIRED, PROP_THICK_WRAP, rna_def_color_ramp_element_api(), RNA_def_float(), RNA_def_float_color(), RNA_def_function(), RNA_def_function_output(), RNA_def_function_ui_description(), RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_color().
static void rna_def_color_ramp_element (BlenderRNA * brna) [static]
Definition at line 428 of file rna_color.c.
References NULL, PROP_COLOR, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_color().
static void rna_def_color_ramp_element_api (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 451 of file rna_color.c.
References FUNC_USE_REPORTS, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_float(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_color_ramp().
static void rna_def_curvemap (BlenderRNA * brna) [static]
Definition at line 342 of file rna_color.c.
References CUMA_EXTEND_EXTRAPOLATE, NULL, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_color().
static void rna_def_curvemapping (BlenderRNA * brna) [static]
Definition at line 369 of file rna_color.c.
References CUMA_DO_CLIP, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_COLOR, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_color().
static void rna_def_curvemappoint (BlenderRNA * brna) [static]
Definition at line 310 of file rna_color.c.
References CUMA_SELECT, CUMA_VECTOR, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_color().
static void rna_def_histogram (BlenderRNA * brna) [static]
Definition at line 533 of file rna_color.c.
References HISTO_MODE_B, HISTO_MODE_G, HISTO_MODE_LUMA, HISTO_MODE_R, HISTO_MODE_RGB, NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_color().
static void rna_def_scopes (BlenderRNA * brna) [static]
Definition at line 556 of file rna_color.c.
References NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_PERCENTAGE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_text(), SCOPES_WAVEFRM_LUMA, SCOPES_WAVEFRM_RGB, SCOPES_WAVEFRM_YCC_601, SCOPES_WAVEFRM_YCC_709, and SCOPES_WAVEFRM_YCC_JPEG.
Referenced by RNA_def_color().