Blender: ntl_vector3dim.h File Reference
ntl_vector3dim.h File Reference
elbeem
#include <iostream>
#include <map>
#include <vector>
#include <string>
#include <sstream>
#include <math.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <float.h>
Classes
class ntlVector3Dim< Scalar >
Defines
#define __FLT_MAX__ 3.402823466e+38f
#define __DBL_MAX__ 1.7976931348623158e+308
#define M_PI 3.1415926536
#define M_E 2.7182818284
#define GFX_PRECISION 1
#define GFX_REAL_MAX __FLT_MAX__
#define VECTOR_EPSILON (1e-5f)
#define HAVE_GFXTYPES
#define VECTOR_TYPE ntlVector3Dim<Scalar>
Typedefs
typedef ntlVector3Dim< double > ntlVec3d
typedef ntlVector3Dim< float > ntlVec3f
typedef ntlVector3Dim< int > ntlVec3i
typedef ntlVec3f ntlColor
typedef float gfxReal
typedef double gfxDouble
typedef ntlVector3Dim< gfxReal > ntlVec3Gfx
Functions
template<class T >
T ABS (T a)
template<class Scalar >
std::ostream & operator<< (std::ostream &os, const ntlVector3Dim< Scalar > &i)
template<class Scalar >
std::istream & operator>> (std::istream &is, ntlVector3Dim< Scalar > &i)
template<class Scalar >
Scalar dot (const ntlVector3Dim< Scalar > &t, const ntlVector3Dim< Scalar > &v)
template<class Scalar >
ntlVector3Dim< Scalar > cross (const ntlVector3Dim< Scalar > &t, const ntlVector3Dim< Scalar > &v)
template<class T >
ntlVec3d vec2D (T v)
template<class T >
ntlVec3f vec2F (T v)
template<class T >
ntlColor vec2Col (T v)
template<class T >
ntlVec3Gfx vec2G (T v)
gfxReal getVecEpsilon ()
template<class Scalar >
Scalar norm (const VECTOR_TYPE &v)
template<class Scalar >
Scalar normNoSqrt (const VECTOR_TYPE &v)
template<class Scalar >
VECTOR_TYPE getNormalized (const VECTOR_TYPE &v)
template<class Scalar >
Scalar normalize (VECTOR_TYPE &v)
template<class Scalar >
VECTOR_TYPE reflectVector (const VECTOR_TYPE &t, const VECTOR_TYPE &n)
template<class Scalar >
VECTOR_TYPE refractVector (const VECTOR_TYPE &t, const VECTOR_TYPE &normal, Scalar nt, Scalar nair, int &refRefl)
template<class Scalar >
bool equal (const VECTOR_TYPE &v, const VECTOR_TYPE &c)
template<class Scalar >
void rgbToHsv (VECTOR_TYPE &V)
template<class Scalar >
void hsvToRgb (VECTOR_TYPE &V)
Variables
const char * globVecFormatStr
global string for formatting vector output in utilities.cpp
Detailed Description
Definition in file ntl_vector3dim.h.
Define Documentation
#define __DBL_MAX__ 1.7976931348623158e+308
Definition at line 99 of file ntl_vector3dim.h.
#define __FLT_MAX__ 3.402823466e+38f
Definition at line 92 of file ntl_vector3dim.h.
#define GFX_PRECISION 1
Definition at line 833 of file ntl_vector3dim.h.
#define GFX_REAL_MAX __FLT_MAX__
Definition at line 840 of file ntl_vector3dim.h.
Referenced by ntlTree::intersect(), ntlRay::intersectBackAABB(), ntlRay::intersectCompleteAABB(), ntlRay::intersectFrontAABB(), ntlRay::intersectTriangle(), ntlRay::intersectTriangleBack(), ntlRay::intersectTriangleFront(), ntlRay::intersectTriangleX(), ntlTree::intersectX(), and ntlRay::shade().
#define HAVE_GFXTYPES
Definition at line 868 of file ntl_vector3dim.h.
#define M_E 2.7182818284
Definition at line 105 of file ntl_vector3dim.h.
#define M_PI 3.1415926536
Definition at line 104 of file ntl_vector3dim.h.
#define VECTOR_EPSILON (1e-5f)
Definition at line 845 of file ntl_vector3dim.h.
Referenced by ntlMatrix4x4< Scalar >::decompose(), equal(), getNormalized(), getVecEpsilon(), norm(), and normalize().
#define VECTOR_TYPE ntlVector3Dim<Scalar>
Definition at line 877 of file ntl_vector3dim.h.
Referenced by getNormalized(), and reflectVector().
Typedef Documentation
typedef double gfxDouble
Definition at line 857 of file ntl_vector3dim.h.
typedef float gfxReal
Definition at line 839 of file ntl_vector3dim.h.
typedef ntlVec3f ntlColor
Definition at line 804 of file ntl_vector3dim.h.
typedef ntlVector3Dim<double> ntlVec3d
Definition at line 795 of file ntl_vector3dim.h.
typedef ntlVector3Dim<float> ntlVec3f
Definition at line 798 of file ntl_vector3dim.h.
typedef ntlVector3Dim<gfxReal> ntlVec3Gfx
Definition at line 860 of file ntl_vector3dim.h.
typedef ntlVector3Dim<int> ntlVec3i
Definition at line 801 of file ntl_vector3dim.h.
Function Documentation
template<class T > T ABS (T a) [inline]
Definition at line 33 of file ntl_vector3dim.h.
template<class Scalar > ntlVector3Dim<Scalar> cross (const ntlVector3Dim< Scalar > & t, const ntlVector3Dim< Scalar > & v) [inline]
Definition at line 695 of file ntl_vector3dim.h.
template<class Scalar > Scalar dot (const ntlVector3Dim< Scalar > & t, const ntlVector3Dim< Scalar > & v) [inline]
Definition at line 684 of file ntl_vector3dim.h.
template<class Scalar > bool equal (const VECTOR_TYPE & v, const VECTOR_TYPE & c) [inline]
Definition at line 1005 of file ntl_vector3dim.h.
References ABS, and VECTOR_EPSILON.
Referenced by LbmSolverInterface::addCellToMarkedList(), ntlTree::ntlTree(), ntlWorld::renderScene(), and ntlRay::shade().
template<class Scalar > VECTOR_TYPE getNormalized (const VECTOR_TYPE & v) [inline]
Definition at line 907 of file ntl_vector3dim.h.
References fabs(), sqrt(), VECTOR_EPSILON, and VECTOR_TYPE.
Referenced by ntlVector3Dim< Scalar >::getOrthogonalntlVector3Dim(), LbmFsgrSolver::initializeSolverGrids(), ntlGeometryObject::initMovingPoints(), ntlGeometryObject::initMovingPointsAnim(), LbmFsgrSolver::LbmFsgrSolver(), ntlWorld::renderScene(), and ntlRay::shade().
gfxReal getVecEpsilon () [inline]
Definition at line 866 of file ntl_vector3dim.h.
References VECTOR_EPSILON.
Referenced by ControlParticles::checkPointInside(), LbmSolverInterface::geoInitCheckPointInside(), ntlTree::intersect(), ntlRay::intersectBackAABB(), ntlRay::intersectCompleteAABB(), ntlRay::intersectFrontAABB(), ntlTree::intersectX(), ntlTree::ntlTree(), and ntlRay::shade().
template<class Scalar > void hsvToRgb (VECTOR_TYPE & V) [inline]
Definition at line 1057 of file ntl_vector3dim.h.
References g, and p.
template<class Scalar > Scalar norm (const VECTOR_TYPE & v) [inline]
Definition at line 885 of file ntl_vector3dim.h.
References fabs(), sqrt(), and VECTOR_EPSILON.
Referenced by LbmFsgrSolver::adaptTimestep(), add_node(), LbmFsgrSolver::advanceParticles(), axisProjection(), BL_SkinDeformer::BGEDeformVerts(), btShapeHull::buildHull(), ntlScene::buildScene(), C_Matrix_OrthoProjection(), C_Matrix_Scale(), calc_poly_plane(), btMinkowskiPenetrationDepthSolver::calcPenDepth(), ntlGeometryObject::calcTriangleDivs(), ntlGeometryObjModel::calcTriangleDivs(), Parametrizer::calculateAllMissingValues(), btConeTwistConstraint::computeConeLimitInfo(), IsoSurface::computeNormals(), MeanValueMeshCoords::computeWeights(), ntlMatrix4x4< Scalar >::decompose(), DM_calc_auto_bump_scale(), eff_calc_visibility(), Eigenhqr2(), LbmFsgrSolver::fineAdvance(), RAS_OpenGLRasterizer::FlushDebugShapes(), GetNormal(), btConeTwistConstraint::GetPointForAngle(), KDL::Rotation::GetXZRot(), ControlParticles::initFromMVCMesh(), LbmFsgrSolver::initGeometryFlags(), LbmFsgrSolver::initializeSolverGrids(), LbmFsgrSolver::initLevelOmegas(), LbmFsgrSolver::LbmFsgrSolver(), M_Noise_random_unit_vector(), LbmFsgrSolver::mainLoop(), minimize(), normalize(), ntlTriangle::ntlTriangle(), p_abf_compute_gradient(), p_chart_abf_solve(), planeProjection(), AUD_LowpassFactory::recalculateCoefficients(), AUD_HighpassFactory::recalculateCoefficients(), AUD_ButterworthFactory::recalculateCoefficients(), ntlWorld::renderScene(), IsoSurface::smoothNormals(), IsoSurface::smoothSurface(), iTaSC::WSDLSSolver::solve(), iTaSC::WDLSSolver::solve(), btSoftColliders::ClusterBase::SolveContact(), traceray(), IsoSurface::triangulate(), iTaSC::Armature::updateJoint(), and view3d_align_axis_to_vector().
template<class Scalar > Scalar normalize (VECTOR_TYPE & v) [inline]
Definition at line 927 of file ntl_vector3dim.h.
References fabs(), norm(), sqrt(), and VECTOR_EPSILON.
template<class Scalar > Scalar normNoSqrt (const VECTOR_TYPE & v) [inline]
Definition at line 896 of file ntl_vector3dim.h.
Referenced by LbmFsgrSolver::advanceParticles(), ntlGeometryObject::calcTriangleDivs(), ntlGeometryObjModel::calcTriangleDivs(), channelFindMaxVd(), channelFindMaxVf(), IsoSurface::computeNormals(), IsoSurface::diffuseVertexField(), LbmSolverInterface::getGeoMaxMovementVelocity(), LbmFsgrSolver::handleObstacleParticle(), LbmFsgrSolver::initMovingObstacles(), ntlGeometryObject::initMovingPoints(), IsoSurface::smoothNormals(), and IsoSurface::smoothSurface().
template<class Scalar > std::ostream& operator<< (std::ostream & os, const ntlVector3Dim< Scalar > & i)
Definition at line 223 of file ntl_vector3dim.h.
References globVecFormatStr, i, and snprintf.
template<class Scalar > std::istream& operator>> (std::istream & is, ntlVector3Dim< Scalar > & i)
Definition at line 240 of file ntl_vector3dim.h.
template<class Scalar > VECTOR_TYPE reflectVector (const VECTOR_TYPE & t, const VECTOR_TYPE & n) [inline]
Definition at line 955 of file ntl_vector3dim.h.
References dot(), and VECTOR_TYPE.
Referenced by ntlRay::shade().
template<class Scalar > VECTOR_TYPE refractVector (const VECTOR_TYPE & t, const VECTOR_TYPE & normal, Scalar nt, Scalar nair, int & refRefl) [inline]
Definition at line 968 of file ntl_vector3dim.h.
References dot(), and sqrt().
Referenced by ntlRay::shade().
template<class Scalar > void rgbToHsv (VECTOR_TYPE & V) [inline]
Definition at line 1017 of file ntl_vector3dim.h.
template<class T > ntlColor vec2Col (T v) [inline]
Definition at line 809 of file ntl_vector3dim.h.
template<class T > ntlVec3d vec2D (T v) [inline]
Definition at line 807 of file ntl_vector3dim.h.
Referenced by MeanValueMeshCoords::computeWeights(), and ntlGeometryObject::initialize().
template<class T > ntlVec3f vec2F (T v) [inline]
Definition at line 808 of file ntl_vector3dim.h.
template<class T > ntlVec3Gfx vec2G (T v) [inline]
Definition at line 862 of file ntl_vector3dim.h.
Referenced by LbmFsgrSolver::advanceParticles(), LbmFsgrSolver::cpDebugDisplay(), LbmFsgrSolver::debugDisplayNode(), LbmFsgrSolver::handleObstacleParticle(), LbmFsgrSolver::initGeometryFlags(), ntlGeometryObject::initialize(), and LbmFsgrSolver::initializeSolverMemory().
Variable Documentation
const char* globVecFormatStr
global string for formatting vector output in utilities.cpp
Definition at line 82 of file utilities.cpp.
Referenced by BasicVector::operator<<(), and operator<<().