Blender: bNodeType Struct Reference
bNodeType Struct Reference
#include <BKE_node.h>
Public Attributes
void * next
void * prev
short needs_free
int type
char name [64]
float width
float minwidth
float maxwidth
float height
float minheight
float maxheight
short nclass
short flag
short compatibility
bNodeSocketTemplate * inputs
bNodeSocketTemplate * outputs
char storagename [64]
void(* drawfunc)(const struct bContext *C, struct ARegion *ar, struct SpaceNode *snode, struct bNodeTree *ntree, struct bNode *node)
Main draw function for the node.
void(* drawupdatefunc)(const struct bContext *C, struct bNodeTree *ntree, struct bNode *node)
Updates the node geometry attributes according to internal state before actual drawing.
void(* uifunc)(struct uiLayout *, struct bContext *C, struct PointerRNA *ptr)
Draw the option buttons on the node.
void(* uifuncbut)(struct uiLayout *, struct bContext *C, struct PointerRNA *ptr)
Additional parameters in the side panel.
const char *(* labelfunc)(struct bNode *)
Optional custom label function for the node header.
int(* resize_area_func)(struct bNode *node, int x, int y)
Optional custom resize handle polling.
void(* updatefunc)(struct bNodeTree *ntree, struct bNode *node)
Called when the node is updated in the editor.
void(* verifyfunc)(struct bNodeTree *ntree, struct bNode *node, struct ID *id)
Check and update if internal ID data has changed.
void(* initfunc)(struct bNodeTree *ntree, struct bNode *node, struct bNodeTemplate *ntemp)
Initialize a new node instance of this type after creation.
void(* freestoragefunc)(struct bNode *node)
Free the custom storage data.
void(* copystoragefunc)(struct bNode *node, struct bNode *target)
Make a copy of the custom storage data.
struct bNodeTemplate(* templatefunc)(struct bNode *)
Create a template from an existing node.
int(* validfunc)(struct bNodeTree *ntree, struct bNodeTemplate *ntemp)
void(* inittreefunc)(struct bNodeTree *ntree)
Initialize a node tree associated to this node type.
void(* updatetreefunc)(struct bNodeTree *ntree)
Update a node tree associated to this node type.
struct bNodeTree *(* group_edit_get)(struct bNode *node)
struct bNodeTree *(* group_edit_set)(struct bNode *node, int edit)
void(* group_edit_clear)(struct bNode *node)
ListBase(* internal_connect)(struct bNodeTree *, struct bNode *node)
void *(* initexecfunc)(struct bNode *node)
void(* freeexecfunc)(struct bNode *node, void *nodedata)
void(* execfunc)(void *data, struct bNode *, struct bNodeStack **, struct bNodeStack **)
void(* newexecfunc)(void *data, int thread, struct bNode *, void *nodedata, struct bNodeStack **, struct bNodeStack **)
int(* gpufunc)(struct GPUMaterial *mat, struct bNode *node, struct GPUNodeStack *in, struct GPUNodeStack *out)
int(* gpuextfunc)(struct GPUMaterial *mat, struct bNode *node, void *nodedata, struct GPUNodeStack *in, struct GPUNodeStack *out)
Detailed Description
Defines a node type. Initial attributes and constants for a node as well as callback functions implementing the node behavior.
Definition at line 125 of file BKE_node.h.
Member Data Documentation
short bNodeType::compatibility
Definition at line 133 of file BKE_node.h.
Referenced by node_add_menu(), node_type_compatibility(), and ui_node_menu_column().
void(* bNodeType::copystoragefunc)(struct bNode *node, struct bNode *target)
Make a copy of the custom storage data.
Definition at line 163 of file BKE_node.h.
Referenced by node_type_storage(), and nodeCopyNode().
void(* bNodeType::drawfunc)(const struct bContext *C, struct ARegion *ar, struct SpaceNode *snode, struct bNodeTree *ntree, struct bNode *node)
Main draw function for the node.
Definition at line 141 of file BKE_node.h.
Referenced by ED_init_node_butfuncs(), node_common_set_butfunc(), and node_draw().
void(* bNodeType::drawupdatefunc)(const struct bContext *C, struct bNodeTree *ntree, struct bNode *node)
Updates the node geometry attributes according to internal state before actual drawing.
Definition at line 143 of file BKE_node.h.
Referenced by ED_init_node_butfuncs(), node_common_set_butfunc(), and node_update().
void(* bNodeType::execfunc)(void *data, struct bNode *, struct bNodeStack **, struct bNodeStack **)
Definition at line 191 of file BKE_node.h.
Referenced by exec_composite_node(), node_type_exec(), ntreeExecNodes(), ntreeExecThreadNodes(), and setExecutableNodes().
short bNodeType::flag
Definition at line 133 of file BKE_node.h.
Referenced by draw_group_socket(), node_draw_basis(), node_flag_toggle_exec(), node_socket_add_replace(), node_type_base(), nodeAddNode(), ntreeClearPreview(), ntreeInitPreview(), and ui_node_sock_name().
void(* bNodeType::freeexecfunc)(struct bNode *node, void *nodedata)
Definition at line 190 of file BKE_node.h.
Referenced by node_type_exec_new(), and ntree_exec_end().
void(* bNodeType::freestoragefunc)(struct bNode *node)
Free the custom storage data.
Definition at line 161 of file BKE_node.h.
Referenced by node_type_storage(), and nodeFreeNode().
int(* bNodeType::gpuextfunc)(struct GPUMaterial *mat, struct bNode *node, void *nodedata, struct GPUNodeStack *in, struct GPUNodeStack *out)
Definition at line 199 of file BKE_node.h.
Referenced by node_type_gpu_ext(), and ntreeExecGPUNodes().
int(* bNodeType::gpufunc)(struct GPUMaterial *mat, struct bNode *node, struct GPUNodeStack *in, struct GPUNodeStack *out)
Definition at line 197 of file BKE_node.h.
Referenced by node_type_gpu(), and ntreeExecGPUNodes().
void(* bNodeType::group_edit_clear)(struct bNode *node)
Definition at line 181 of file BKE_node.h.
Referenced by node_type_group_edit(), and nodeGroupEditClear().
struct bNodeTree*(* bNodeType::group_edit_get)(struct bNode *node) [read]
Definition at line 179 of file BKE_node.h.
Referenced by node_type_group_edit(), nodeGroupEditGet(), and nodeGroupEditSet().
struct bNodeTree*(* bNodeType::group_edit_set)(struct bNode *node, int edit) [read]
Definition at line 180 of file BKE_node.h.
Referenced by node_type_group_edit(), and nodeGroupEditSet().
float bNodeType::height
Definition at line 132 of file BKE_node.h.
Referenced by node_type_base(), and nodeAddNode().
void*(* bNodeType::initexecfunc)(struct bNode *node)
Definition at line 189 of file BKE_node.h.
Referenced by node_type_exec_new(), and ntree_exec_begin().
void(* bNodeType::initfunc)(struct bNodeTree *ntree, struct bNode *node, struct bNodeTemplate *ntemp)
Initialize a new node instance of this type after creation.
Definition at line 159 of file BKE_node.h.
Referenced by node_type_init(), and nodeAddNode().
void(* bNodeType::inittreefunc)(struct bNodeTree *ntree)
Initialize a node tree associated to this node type.
Definition at line 173 of file BKE_node.h.
Referenced by node_type_tree(), and ntreeAddTree().
bNodeSocketTemplate* bNodeType::inputs
Definition at line 136 of file BKE_node.h.
Referenced by free_dynamic_typeinfo(), node_add_sockets_from_type(), node_type_socket_templates(), and node_verify_socket_templates().
ListBase(* bNodeType::internal_connect)(struct bNodeTree *, struct bNode *node)
Definition at line 186 of file BKE_node.h.
Referenced by node_draw_mute_line(), node_mute_exec(), node_type_base(), node_type_internal_connect(), and nodeInternalRelink().
const char*(* bNodeType::labelfunc)(struct bNode *)
Optional custom label function for the node header.
Definition at line 149 of file BKE_node.h.
Referenced by node_type_label(), and nodeLabel().
float bNodeType::maxheight
Definition at line 132 of file BKE_node.h.
Referenced by node_resize_modal(), and node_type_base().
float bNodeType::maxwidth
Definition at line 131 of file BKE_node.h.
Referenced by node_resize_modal(), node_type_base(), and node_type_size().
float bNodeType::minheight
Definition at line 132 of file BKE_node.h.
Referenced by node_resize_modal(), and node_type_base().
float bNodeType::minwidth
Definition at line 131 of file BKE_node.h.
Referenced by node_resize_modal(), node_type_base(), and node_type_size().
char bNodeType::name[64]
Definition at line 130 of file BKE_node.h.
Referenced by free_dynamic_typeinfo(), node_add_menu(), node_type_base(), nodeLabel(), nodeMakeDynamicType(), ui_node_menu_column(), and ui_node_sock_name().
short bNodeType::nclass
Definition at line 133 of file BKE_node.h.
Referenced by buttons_texture_users_find_nodetree(), node_add_menu(), node_get_colorid(), node_socket_add_replace(), node_type_base(), nodeSetActive(), ntreeExecGPUNodes(), ntreeSetOutput(), and ui_node_menu_column().
short bNodeType::needs_free
Definition at line 127 of file BKE_node.h.
Referenced by free_typeinfos(), and register_node_type_frame().
void(* bNodeType::newexecfunc)(void *data, int thread, struct bNode *, void *nodedata, struct bNodeStack **, struct bNodeStack **)
Definition at line 195 of file BKE_node.h.
Referenced by exec_composite_node(), node_type_exec_new(), ntreeExecNodes(), and ntreeExecThreadNodes().
void* bNodeType::next
Definition at line 126 of file BKE_node.h.
Referenced by ED_init_node_butfuncs(), free_typeinfos(), is_nodetype_registered(), node_add_menu(), node_get_type(), node_tree_has_type(), nodeMakeDynamicType(), and ui_node_menu_column().
bNodeSocketTemplate * bNodeType::outputs
Definition at line 136 of file BKE_node.h.
Referenced by free_dynamic_typeinfo(), node_add_sockets_from_type(), node_type_socket_templates(), node_verify_socket_templates(), and ui_node_menu_column().
void * bNodeType::prev
Definition at line 126 of file BKE_node.h.
int(* bNodeType::resize_area_func)(struct bNode *node, int x, int y)
Optional custom resize handle polling.
Definition at line 151 of file BKE_node.h.
Referenced by ED_init_node_butfuncs(), and node_resize_invoke().
char bNodeType::storagename[64]
Definition at line 138 of file BKE_node.h.
Referenced by node_type_storage(), and write_nodetree().
struct bNodeTemplate(* bNodeType::templatefunc)(struct bNode *) [read]
Create a template from an existing node.
Definition at line 166 of file BKE_node.h.
Referenced by node_type_template().
int bNodeType::type
Definition at line 129 of file BKE_node.h.
Referenced by free_dynamic_typeinfo(), free_typeinfos(), is_nodetype_registered(), node_add_menu(), node_common_set_butfunc(), node_composit_set_butfunc(), node_get_type(), node_shader_set_butfunc(), node_texture_set_butfunc(), node_tree_has_type(), node_type_base(), nodeAddNode(), nodeMakeDynamicType(), nodeRegisterType(), and ui_node_menu_column().
void(* bNodeType::uifunc)(struct uiLayout *, struct bContext *C, struct PointerRNA *ptr)
Draw the option buttons on the node.
Definition at line 145 of file BKE_node.h.
Referenced by ED_init_node_butfuncs(), node_common_set_butfunc(), node_composit_set_butfunc(), node_shader_set_butfunc(), node_texture_set_butfunc(), node_update_basis(), ui_node_draw_input(), and ui_node_draw_node().
void(* bNodeType::uifuncbut)(struct uiLayout *, struct bContext *C, struct PointerRNA *ptr)
Additional parameters in the side panel.
Definition at line 147 of file BKE_node.h.
Referenced by ED_init_node_butfuncs(), node_composit_set_butfunc(), node_shader_set_butfunc(), and node_texture_set_butfunc().
void(* bNodeType::updatefunc)(struct bNodeTree *ntree, struct bNode *node)
Called when the node is updated in the editor.
Definition at line 154 of file BKE_node.h.
Referenced by node_type_update(), nodeUpdate(), nodeUpdateID(), ntreeUpdateTree(), and update_node().
void(* bNodeType::updatetreefunc)(struct bNodeTree *ntree)
Update a node tree associated to this node type.
Definition at line 175 of file BKE_node.h.
Referenced by node_type_tree(), and ntreeUpdateTree().
int(* bNodeType::validfunc)(struct bNodeTree *ntree, struct bNodeTemplate *ntemp)
If a node can be made from the template in the given node tree.
Note:
Node groups can not be created inside their own node tree.
Definition at line 170 of file BKE_node.h.
Referenced by node_type_valid(), and nodeValid().
void(* bNodeType::verifyfunc)(struct bNodeTree *ntree, struct bNode *node, struct ID *id)
Check and update if internal ID data has changed.
Definition at line 156 of file BKE_node.h.
Referenced by node_type_update(), and ntree_verify_nodes_cb().
float bNodeType::width
Definition at line 131 of file BKE_node.h.
Referenced by node_socket_add_replace(), node_type_base(), node_type_size(), and nodeAddNode().
The documentation for this struct was generated from the following file:
BKE_node.h