Blender: ED_text.h File Reference
ED_text.h File Reference
Editors
Functions
void ED_text_undo_step (struct bContext *C, int step)
Detailed Description
Definition in file ED_text.h.
Function Documentation
void ED_text_undo_step (struct bContext * C, int step)
Definition at line 3293 of file text_ops.c.
References CTX_data_edit_text(), CTX_wm_space_text(), NA_EDITED, NC_TEXT, text_drawcache_tag_update(), text_update_cursor_moved(), text_update_edited(), txt_do_redo(), txt_do_undo(), and WM_event_add_notifier().
Referenced by ed_undo_step().