Blender: BLF_api.h File Reference
BLF_api.h File Reference
blenfont
Defines
#define BLF_ROTATION (1<<0)
#define BLF_CLIPPING (1<<1)
#define BLF_SHADOW (1<<2)
#define BLF_KERNING_DEFAULT (1<<3)
#define BLF_MATRIX (1<<4)
#define BLF_ASPECT (1<<5)
#define BLF_DRAW_STR_DUMMY_MAX 1024
Functions
int BLF_init (int points, int dpi)
void BLF_exit (void)
void BLF_cache_clear (void)
int BLF_load (const char *name)
int BLF_load_mem (const char *name, unsigned char *mem, int mem_size)
int BLF_load_unique (const char *name)
int BLF_load_mem_unique (const char *name, unsigned char *mem, int mem_size)
void BLF_unload (const char *name)
void BLF_metrics_attach (int fontid, unsigned char *mem, int mem_size)
void BLF_aspect (int fontid, float x, float y, float z)
void BLF_position (int fontid, float x, float y, float z)
void BLF_size (int fontid, int size, int dpi)
void BLF_matrix (int fontid, const double m[16])
void BLF_draw_default (float x, float y, float z, const char *str, size_t len)
void BLF_draw_default_ascii (float x, float y, float z, const char *str, size_t len)
void BLF_draw (int fontid, const char *str, size_t len)
void BLF_draw_ascii (int fontid, const char *str, size_t len)
void BLF_boundbox (int fontid, const char *str, struct rctf *box)
float BLF_width (int fontid, const char *str)
float BLF_height (int fontid, const char *str)
float BLF_height_max (int fontid)
float BLF_width_max (int fontid)
float BLF_descender (int fontid)
float BLF_ascender (int fontid)
void BLF_width_and_height (int fontid, const char *str, float *width, float *height)
float BLF_fixed_width (int fontid)
float BLF_width_default (const char *str)
float BLF_height_default (const char *str)
void BLF_rotation_default (float angle)
void BLF_enable_default (int option)
void BLF_disable_default (int option)
void BLF_rotation (int fontid, float angle)
void BLF_clipping (int fontid, float xmin, float ymin, float xmax, float ymax)
void BLF_clipping_default (float xmin, float ymin, float xmax, float ymax)
void BLF_blur (int fontid, int size)
void BLF_enable (int fontid, int option)
void BLF_disable (int fontid, int option)
void BLF_shadow (int fontid, int level, float r, float g, float b, float a)
void BLF_shadow_offset (int fontid, int x, int y)
void BLF_buffer (int fontid, float *fbuf, unsigned char *cbuf, int w, int h, int nch)
void BLF_buffer_col (int fontid, float r, float g, float b, float a)
void BLF_draw_buffer (int fontid, const char *str)
void BLF_dir_add (const char *path)
void BLF_dir_rem (const char *path)
char ** BLF_dir_get (int *ndir)
void BLF_dir_free (char **dirs, int count)
Variables
int blf_mono_font
int blf_mono_font_render
Detailed Description
Definition in file BLF_api.h.
Define Documentation
#define BLF_ASPECT (1<<5)
Definition at line 182 of file BLF_api.h.
Referenced by BL_print_game_line(), blf_draw__start(), blf_font_height(), blf_font_width(), blf_font_width_and_height(), BLF_position(), and GPC_RenderTools::RenderText3D().
#define BLF_CLIPPING (1<<1)
Definition at line 178 of file BLF_api.h.
Referenced by blf_glyph_render(), BPyInit_blf(), UI_view2d_text_cache_draw(), uiStyleFontDrawExt(), and uiStyleFontDrawRotated().
#define BLF_DRAW_STR_DUMMY_MAX 1024
Definition at line 184 of file BLF_api.h.
Referenced by ED_region_do_draw(), ED_region_info_draw(), text_font_draw(), UI_DrawString(), UI_view2d_text_cache_draw(), uiStyleFontDrawExt(), and uiStyleFontDrawRotated().
#define BLF_KERNING_DEFAULT (1<<3)
Definition at line 180 of file BLF_api.h.
Referenced by BPyInit_blf(), UI_DrawString(), UI_GetStringWidth(), ui_text_label_rightclip(), ui_text_leftclip(), ui_textedit_set_cursor_pos(), uiStyleFontDrawExt(), uiStyleFontDrawRotated(), and widget_draw_text().
#define BLF_MATRIX (1<<4)
Definition at line 181 of file BLF_api.h.
Referenced by BL_print_game_line(), blf_draw__start(), and GPC_RenderTools::RenderText3D().
#define BLF_ROTATION (1<<0)
Definition at line 177 of file BLF_api.h.
Referenced by blf_draw__start(), BPyInit_blf(), UI_view2d_scrollers_draw(), and uiStyleFontDrawRotated().
#define BLF_SHADOW (1<<2)
Definition at line 179 of file BLF_api.h.
Referenced by blf_glyph_render(), BPyInit_blf(), uiStyleFontDrawExt(), and uiStyleFontDrawRotated().
Function Documentation
float BLF_ascender (int fontid)
Definition at line 667 of file blf.c.
References GlyphCacheBLF::ascender, BLF_get(), and FontBLF::glyph_cache.
Referenced by uiStyleFontDrawExt(), and uiStyleFontDrawRotated().
void BLF_aspect (int fontid, float x, float y, float z)
Definition at line 349 of file blf.c.
References FontBLF::aspect, and BLF_get().
Referenced by BL_print_game_line(), py_blf_aspect(), and GPC_RenderTools::RenderText3D().
void BLF_blur (int fontid, int size)
Definition at line 427 of file blf.c.
References BLF_get(), FontBLF::blur, and size().
Referenced by py_blf_blur().
void BLF_boundbox (int fontid, const char * str, struct rctf * box)
Definition at line 569 of file blf.c.
References blf_font_boundbox(), and BLF_get().
void BLF_buffer (int fontid, float * fbuf, unsigned char * cbuf, int w, int h, int nch)
Definition at line 749 of file blf.c.
References FontBLF::b_cbuf, FontBLF::b_fbuf, FontBLF::bch, FontBLF::bh, BLF_get(), and FontBLF::bw.
Referenced by BKE_stamp_buf(), and checker_board_text().
void BLF_buffer_col (int fontid, float r, float g, float b, float a)
Definition at line 762 of file blf.c.
References FontBLF::b_col, BLF_get(), and g.
Referenced by BKE_stamp_buf(), and checker_board_text().
void BLF_cache_clear (void)
Definition at line 108 of file blf.c.
References blf_glyph_cache_clear(), BLF_MAX_FONT, and i.
void BLF_clipping (int fontid, float xmin, float ymin, float xmax, float ymax)
Definition at line 702 of file blf.c.
References BLF_get(), FontBLF::clip_rec, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by py_blf_clipping(), uiStyleFontDrawExt(), and uiStyleFontDrawRotated().
void BLF_clipping_default (float xmin, float ymin, float xmax, float ymax)
Definition at line 714 of file blf.c.
References BLF_get(), FontBLF::clip_rec, global_font_default, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by UI_view2d_text_cache_draw().
float BLF_descender (int fontid)
Definition at line 656 of file blf.c.
References BLF_get(), GlyphCacheBLF::descender, and FontBLF::glyph_cache.
Referenced by BKE_stamp_buf().
void BLF_dir_add (const char * path)
Definition at line 69 of file blf_dir.c.
References blf_dir_find(), BLI_addhead(), BLI_strdup(), MEM_callocN(), and DirBLF::path.
void BLF_dir_free (char ** dirs, int count)
Definition at line 117 of file blf_dir.c.
References i, and MEM_freeN().
char** BLF_dir_get (int * ndir)
Definition at line 94 of file blf_dir.c.
References BLI_countlist(), BLI_strdup(), ListBase::first, i, MEM_callocN(), DirBLF::next, NULL, p, and DirBLF::path.
void BLF_dir_rem (const char * path)
Definition at line 82 of file blf_dir.c.
References blf_dir_find(), BLI_remlink(), MEM_freeN(), and DirBLF::path.
void BLF_disable (int fontid, int option)
Definition at line 322 of file blf.c.
References BLF_get(), and FontBLF::flags.
Referenced by BL_print_game_line(), py_blf_disable(), GPC_RenderTools::RenderText3D(), UI_DrawString(), UI_GetStringWidth(), ui_text_label_rightclip(), ui_text_leftclip(), ui_textedit_set_cursor_pos(), uiStyleFontDrawExt(), uiStyleFontDrawRotated(), and widget_draw_text().
void BLF_disable_default (int option)
Definition at line 340 of file blf.c.
References BLF_get(), FontBLF::flags, and global_font_default.
Referenced by UI_view2d_scrollers_draw(), and UI_view2d_text_cache_draw().
void BLF_draw (int fontid, const char * str, size_t len)
Definition at line 545 of file blf.c.
References blf_draw__end(), blf_draw__start(), blf_font_draw(), BLF_get(), and FontBLF::glyph_cache.
Referenced by BL_print_game_line(), BLF_draw_default(), clip_draw_curfra_label(), console_draw_string(), draw_marker_texts(), ED_region_info_draw(), loggerwindow_do_draw(), py_blf_draw(), GPC_RenderTools::RenderText3D(), text_font_draw(), text_font_draw_character(), text_font_draw_character_utf8(), UI_DrawString(), uiStyleFontDrawExt(), uiStyleFontDrawRotated(), and widget_draw_text().
void BLF_draw_ascii (int fontid, const char * str, size_t len)
Definition at line 557 of file blf.c.
References blf_draw__end(), blf_draw__start(), blf_font_draw_ascii(), BLF_get(), and FontBLF::glyph_cache.
Referenced by BLF_draw_default_ascii(), and ED_image_draw_info().
void BLF_draw_buffer (int fontid, const char * str)
Definition at line 774 of file blf.c.
References FontBLF::b_cbuf, FontBLF::b_fbuf, blf_font_buffer(), BLF_get(), and FontBLF::glyph_cache.
Referenced by BKE_stamp_buf(), and checker_board_text().
void BLF_draw_default (float x, float y, float z, const char * str, size_t len)
Definition at line 436 of file blf.c.
References BLF_draw(), BLF_position(), blf_search(), BLF_size(), global_font_default, global_font_dpi, and global_font_points.
Referenced by BL_print_gamedebug_line(), BL_print_gamedebug_line_padded(), draw_selected_name(), drawviewborder(), ED_region_do_draw(), GPC_RenderTools::RenderText2D(), UI_view2d_text_cache_draw(), and view3d_cached_text_draw_end().
void BLF_draw_default_ascii (float x, float y, float z, const char * str, size_t len)
Definition at line 455 of file blf.c.
References BLF_draw_ascii(), BLF_position(), blf_search(), BLF_size(), global_font_default, global_font_dpi, and global_font_points.
Referenced by draw_view_axis(), draw_viewport_fps(), draw_viewport_name(), scroll_printstr(), view3d_cached_text_draw_end(), and view3d_main_area_draw_info().
void BLF_enable (int fontid, int option)
Definition at line 313 of file blf.c.
References BLF_get(), and FontBLF::flags.
Referenced by BL_print_game_line(), py_blf_enable(), GPC_RenderTools::RenderText3D(), UI_DrawString(), UI_GetStringWidth(), ui_text_label_rightclip(), ui_text_leftclip(), ui_textedit_set_cursor_pos(), uiStyleFontDrawExt(), uiStyleFontDrawRotated(), and widget_draw_text().
void BLF_enable_default (int option)
Definition at line 331 of file blf.c.
References BLF_get(), FontBLF::flags, and global_font_default.
Referenced by UI_view2d_scrollers_draw(), and UI_view2d_text_cache_draw().
void BLF_exit (void)
Definition at line 92 of file blf.c.
References blf_font_exit(), blf_font_free(), BLF_MAX_FONT, i, and NULL.
Referenced by main(), and WM_exit_ext().
float BLF_fixed_width (int fontid)
Definition at line 598 of file blf.c.
References blf_font_fixed_width(), BLF_get(), and FontBLF::glyph_cache.
Referenced by draw_text_main(), text_update_character_width(), and textview_draw().
float BLF_height (int fontid, const char * str)
Definition at line 623 of file blf.c.
References blf_font_height(), BLF_get(), and FontBLF::glyph_cache.
Referenced by BLF_height_default(), file_font_pointsize(), and loggerwindow_new().
float BLF_height_default (const char * str)
Definition at line 678 of file blf.c.
References BLF_height(), blf_search(), BLF_size(), global_font_default, global_font_dpi, and global_font_points.
Referenced by UI_view2d_text_cache_draw().
float BLF_height_max (int fontid)
Definition at line 634 of file blf.c.
References BLF_get(), FontBLF::glyph_cache, and GlyphCacheBLF::max_glyph_height.
Referenced by BKE_stamp_buf(), draw_marker_texts(), and ui_tooltip_create().
int BLF_init (int points, int dpi)
Definition at line 80 of file blf.c.
References blf_font_init(), BLF_MAX_FONT, global_font_dpi, global_font_points, i, and NULL.
Referenced by main(), and WM_init().
int BLF_load (const char * name)
Definition at line 145 of file blf.c.
References blf_dir_search(), blf_font_new(), blf_search(), blf_search_available(), i, and MEM_freeN().
Referenced by GetFontId(), py_blf_load(), and uiStyleInit().
int BLF_load_mem (const char * name, unsigned char * mem, int mem_size)
Definition at line 230 of file blf.c.
References blf_font_new_from_mem(), blf_search(), blf_search_available(), and i.
Referenced by GetFontId(), loggerwindow_new(), main(), and uiStyleInit().
int BLF_load_mem_unique (const char * name, unsigned char * mem, int mem_size)
Definition at line 265 of file blf.c.
References blf_font_new_from_mem(), blf_search_available(), and i.
Referenced by uiStyleInit().
int BLF_load_unique (const char * name)
Definition at line 185 of file blf.c.
References blf_dir_search(), blf_font_new(), blf_search_available(), i, and MEM_freeN().
void BLF_matrix (int fontid, const double m[16])
Definition at line 360 of file blf.c.
References BLF_get(), and FontBLF::m.
Referenced by BL_print_game_line(), and GPC_RenderTools::RenderText3D().
void BLF_metrics_attach (int fontid, unsigned char * mem, int mem_size)
Definition at line 221 of file blf.c.
References blf_font_attach_from_mem(), and BLF_get().
void BLF_position (int fontid, float x, float y, float z)
Definition at line 369 of file blf.c.
References FontBLF::aspect, BLF_ASPECT, BLF_get(), FontBLF::flags, floorf, and FontBLF::pos.
Referenced by BKE_stamp_buf(), BL_print_game_line(), BLF_draw_default(), BLF_draw_default_ascii(), checker_board_text(), clip_draw_curfra_label(), console_draw_string(), draw_marker_texts(), ED_image_draw_info(), ED_region_info_draw(), loggerwindow_do_draw(), py_blf_position(), GPC_RenderTools::RenderText3D(), text_font_draw(), text_font_draw_character(), text_font_draw_character_utf8(), UI_DrawString(), uiStyleFontDrawExt(), uiStyleFontDrawRotated(), and widget_draw_text().
void BLF_rotation (int fontid, float angle)
Definition at line 693 of file blf.c.
References angle(), FontBLF::angle, and BLF_get().
Referenced by py_blf_rotation(), and uiStyleFontDrawRotated().
void BLF_rotation_default (float angle)
Definition at line 473 of file blf.c.
References angle(), FontBLF::angle, BLF_get(), and global_font_default.
Referenced by UI_view2d_scrollers_draw().
void BLF_shadow (int fontid, int level, float r, float g, float b, float a)
Definition at line 726 of file blf.c.
References BLF_get(), g, FontBLF::shadow, and FontBLF::shadow_col.
Referenced by py_blf_shadow(), uiStyleFontDrawExt(), and uiStyleFontDrawRotated().
void BLF_shadow_offset (int fontid, int x, int y)
Definition at line 739 of file blf.c.
References BLF_get(), FontBLF::shadow_x, and FontBLF::shadow_y.
Referenced by py_blf_shadow_offset(), uiStyleFontDrawExt(), and uiStyleFontDrawRotated().
void BLF_size (int fontid, int size, int dpi)
Definition at line 418 of file blf.c.
References blf_font_size(), and BLF_get().
Referenced by BKE_stamp_buf(), BL_print_game_line(), BLF_draw_default(), BLF_draw_default_ascii(), BLF_height_default(), BLF_width_default(), checker_board_text(), clip_draw_curfra_label(), console_font_begin(), draw_marker_texts(), ED_image_draw_info(), ED_region_info_draw(), loggerwindow_new(), py_blf_size(), GPC_RenderTools::RenderText3D(), text_font_begin(), uiStyleFontSet(), uiStyleInit(), and wm_block_create_splash().
void BLF_unload (const char * name)
Definition at line 298 of file blf.c.
References blf_font_free(), BLF_MAX_FONT, i, FontBLF::name, and NULL.
Referenced by py_blf_unload(), and uiStyleInit().
float BLF_width (int fontid, const char * str)
Definition at line 587 of file blf.c.
References blf_font_width(), BLF_get(), and FontBLF::glyph_cache.
Referenced by BLF_width_default(), draw_suggestion_list(), ED_image_draw_info(), ED_region_info_draw(), file_string_width(), text_font_draw(), ui_draw_menu_item(), UI_GetStringWidth(), ui_text_bounds_block(), ui_text_label_rightclip(), ui_text_leftclip(), ui_textedit_set_cursor_pos(), ui_tooltip_create(), uiStyleFontDrawExt(), uiStyleFontDrawRotated(), uiTemplateReportsBanner(), widget_draw_text(), and wm_block_create_splash().
void BLF_width_and_height (int fontid, const char * str, float * width, float * height)
Definition at line 578 of file blf.c.
References blf_font_width_and_height(), BLF_get(), and FontBLF::glyph_cache.
Referenced by BKE_stamp_buf(), clip_draw_curfra_label(), py_blf_dimensions(), and ui_draw_preview_item().
float BLF_width_default (const char * str)
Definition at line 609 of file blf.c.
References blf_search(), BLF_size(), BLF_width(), global_font_default, global_font_dpi, and global_font_points.
float BLF_width_max (int fontid)
Definition at line 645 of file blf.c.
References BLF_get(), FontBLF::glyph_cache, and GlyphCacheBLF::max_glyph_width.
Referenced by BKE_stamp_buf().
Variable Documentation
int blf_mono_font
Definition at line 70 of file blf.c.
Referenced by checker_board_text(), console_draw_string(), console_font_begin(), ED_image_draw_info(), textview_draw(), and uiStyleInit().
int blf_mono_font_render
Definition at line 71 of file blf.c.
Referenced by BKE_stamp_buf(), and uiStyleInit().