Blender: gammaCorrectionTables.h File Reference
gammaCorrectionTables.h File Reference
Rendering
Functions
void makeGammaTables (float gamma)
float gammaCorrect (float col)
float invGammaCorrect (float col)
Detailed Description
Definition in file gammaCorrectionTables.h.
Function Documentation
float gammaCorrect (float col)
Apply gamma correction on col
Definition at line 65 of file gammaCorrectionTables.c.
References abs(), color_domain_table, gamfactor_table, gamma_range_table, i, inv_color_step, pow(), RE_GAMMA_TABLE_SIZE, and valid_gamma.
float invGammaCorrect (float col)
Apply inverse gamma correction on col
Definition at line 85 of file gammaCorrectionTables.c.
References abs(), color_domain_table, i, inv_color_step, inv_gamfactor_table, inv_gamma_range_table, pow(), RE_GAMMA_TABLE_SIZE, and valid_inv_gamma.
void makeGammaTables (float gamma)
Initialize the gamma lookup tables
Definition at line 103 of file gammaCorrectionTables.c.
References color_domain_table, color_step, gamfactor_table, gamma_range_table, i, inv_color_step, inv_gamfactor_table, inv_gamma_range_table, pow(), RE_GAMMA_TABLE_SIZE, valid_gamma, and valid_inv_gamma.