Blender: svm_brightness.h File Reference
svm_brightness.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void svm_node_brightness (ShaderData *sd, float *stack, uint in_color, uint out_color, uint node)
Function Documentation
CCL_NAMESPACE_BEGIN __device void svm_node_brightness (ShaderData * sd, float * stack, uint in_color, uint out_color, uint node)
Definition at line 21 of file svm_brightness.h.
References decode_node_uchar4(), max, NULL, stack_load_float(), stack_load_float3(), stack_store_float3(), stack_valid(), float3::x, float3::y, and float3::z.
Referenced by svm_eval_nodes().