Blender: KDL::Rotation2 Class Reference
KDL::Rotation2 Class Reference
#include <frames.hpp>
Public Member Functions
Rotation2 ()
Default constructor does NOT initialise to Zero().
Rotation2 (double angle_rad)
Rotation2 (double ca, double sa)
Rotation2 & operator= (const Rotation2 &arg)
Vector2 operator* (const Vector2 &v) const
double operator() (int i, int j) const
Access to elements 0..1,0..1, bounds are checked when NDEBUG is not set.
void SetInverse ()
Rotation2 Inverse () const
Vector2 Inverse (const Vector2 &v) const
void SetIdentity ()
void SetRot (double angle)
The SetRot.. functions set the value of *this to the appropriate rotation matrix.
double GetRot () const
Gets the angle (in radians)
Static Public Member Functions
static Rotation2 Identity ()
static Rotation2 Rot (double angle)
The Rot... static functions give the value of the appropriate rotation matrix bac.
Friends
Rotation2 operator* (const Rotation2 &lhs, const Rotation2 &rhs)
bool Equal (const Rotation2 &a, const Rotation2 &b, double eps=epsilon)
Detailed Description
A 2D Rotation class, for conventions see Rotation. For further documentation of the methods see Rotation class.
Definition at line 987 of file frames.hpp.
Constructor & Destructor Documentation
KDL::Rotation2::Rotation2 () [inline]
Default constructor does NOT initialise to Zero().
c,s represent cos(angle), sin(angle), this also represents first col. of rot matrix from outside, this class behaves as if it would store the complete 2x2 matrix.
Definition at line 994 of file frames.hpp.
Referenced by KDL::RotationVel::Rot().
KDL::Rotation2::Rotation2 (double angle_rad) [inline, explicit]
Definition at line 996 of file frames.hpp.
KDL::Rotation2::Rotation2 (double ca, double sa) [inline]
Definition at line 998 of file frames.hpp.
Member Function Documentation
IMETHOD double Rotation2::GetRot () const [inline]
Gets the angle (in radians)
Definition at line 932 of file frames.inl.
References KDL::atan2().
Referenced by KDL::operator<<().
static Rotation2 KDL::Rotation2::Identity () [inline, static]
Rotation2 KDL::Rotation2::Inverse () const [inline]
Vector2 KDL::Rotation2::Inverse (const Vector2 & v) const [inline]
double KDL::Rotation2::operator() (int i, int j) const [inline]
Access to elements 0..1,0..1, bounds are checked when NDEBUG is not set.
Vector2 KDL::Rotation2::operator* (const Vector2 & v) const [inline]
Rotation2& KDL::Rotation2::operator= (const Rotation2 & arg) [inline]
static Rotation2 KDL::Rotation2::Rot (double angle) [inline, static]
The Rot... static functions give the value of the appropriate rotation matrix bac.
Referenced by KDL::operator>>().
void KDL::Rotation2::SetIdentity () [inline]
void KDL::Rotation2::SetInverse () [inline]
IMETHOD void Rotation2::SetRot (double angle) [inline]
The SetRot.. functions set the value of *this to the appropriate rotation matrix.
Definition at line 924 of file frames.inl.
References KDL::cos(), and KDL::sin().
Friends And Related Function Documentation
bool Equal (const Rotation2 & a, const Rotation2 & b, double eps = epsilon) [friend]
do not use operator == because the definition of Equal(.,.) is slightly different. It compares whether the 2 arguments are equal in an eps-interval
Rotation2 operator* (const Rotation2 & lhs, const Rotation2 & rhs) [friend]
The documentation for this class was generated from the following files:
frames.hpp
frames.inl