Blender: SCA_TimeEventManager Class Reference
SCA_TimeEventManager Class Reference
#include <SCA_TimeEventManager.h>
Public Member Functions
SCA_TimeEventManager (class SCA_LogicManager *logicmgr)
virtual ~SCA_TimeEventManager ()
virtual void NextFrame (double curtime, double fixedtime)
virtual void RegisterSensor (class SCA_ISensor *sensor)
virtual void RemoveSensor (class SCA_ISensor *sensor)
void AddTimeProperty (CValue *timeval)
void RemoveTimeProperty (CValue *timeval)
vector< CValue * > GetTimeValues ()
Detailed Description
Definition at line 41 of file SCA_TimeEventManager.h.
Constructor & Destructor Documentation
SCA_TimeEventManager::SCA_TimeEventManager (class SCA_LogicManager * logicmgr)
Definition at line 44 of file SCA_TimeEventManager.cpp.
SCA_TimeEventManager::~SCA_TimeEventManager () [virtual]
Definition at line 51 of file SCA_TimeEventManager.cpp.
Member Function Documentation
void SCA_TimeEventManager::AddTimeProperty (CValue * timeval)
Definition at line 95 of file SCA_TimeEventManager.cpp.
References CValue::AddRef().
Referenced by KX_Scene::AddNodeReplicaObject(), BL_ConvertProperties(), BL_ConvertTextProperty(), and KX_Scene::MergeScene().
vector< CValue * > SCA_TimeEventManager::GetTimeValues ()
Definition at line 117 of file SCA_TimeEventManager.cpp.
Referenced by KX_Scene::MergeScene().
void SCA_TimeEventManager::NextFrame (double curtime, double fixedtime) [virtual]
Reimplemented from SCA_EventManager.
Definition at line 74 of file SCA_TimeEventManager.cpp.
References CValue::Release(), and CFloatValue::SetFloat().
void SCA_TimeEventManager::RegisterSensor (class SCA_ISensor * sensor) [virtual]
Reimplemented from SCA_EventManager.
Definition at line 62 of file SCA_TimeEventManager.cpp.
void SCA_TimeEventManager::RemoveSensor (class SCA_ISensor * sensor) [virtual]
Reimplemented from SCA_EventManager.
Definition at line 67 of file SCA_TimeEventManager.cpp.
void SCA_TimeEventManager::RemoveTimeProperty (CValue * timeval)
Definition at line 103 of file SCA_TimeEventManager.cpp.
References CValue::Release().
Referenced by KX_Scene::NewRemoveObject().
The documentation for this class was generated from the following files:
SCA_TimeEventManager.h
SCA_TimeEventManager.cpp