Blender: MOD_modifiertypes.h File Reference
MOD_modifiertypes.h File Reference
modifiers
#include "BKE_modifier.h"
Functions
void modifier_type_init (ModifierTypeInfo *types[])
Variables
ModifierTypeInfo modifierType_None
ModifierTypeInfo modifierType_Subsurf
ModifierTypeInfo modifierType_Lattice
ModifierTypeInfo modifierType_Curve
ModifierTypeInfo modifierType_Build
ModifierTypeInfo modifierType_Mirror
ModifierTypeInfo modifierType_Decimate
ModifierTypeInfo modifierType_Wave
ModifierTypeInfo modifierType_Armature
ModifierTypeInfo modifierType_Hook
ModifierTypeInfo modifierType_Softbody
ModifierTypeInfo modifierType_Boolean
ModifierTypeInfo modifierType_Array
ModifierTypeInfo modifierType_EdgeSplit
ModifierTypeInfo modifierType_Displace
ModifierTypeInfo modifierType_UVProject
ModifierTypeInfo modifierType_Smooth
ModifierTypeInfo modifierType_Cast
ModifierTypeInfo modifierType_MeshDeform
ModifierTypeInfo modifierType_ParticleSystem
ModifierTypeInfo modifierType_ParticleInstance
ModifierTypeInfo modifierType_Explode
ModifierTypeInfo modifierType_Cloth
ModifierTypeInfo modifierType_Collision
ModifierTypeInfo modifierType_Bevel
ModifierTypeInfo modifierType_Shrinkwrap
ModifierTypeInfo modifierType_Fluidsim
ModifierTypeInfo modifierType_Mask
ModifierTypeInfo modifierType_SimpleDeform
ModifierTypeInfo modifierType_Multires
ModifierTypeInfo modifierType_Surface
ModifierTypeInfo modifierType_Smoke
ModifierTypeInfo modifierType_ShapeKey
ModifierTypeInfo modifierType_Solidify
ModifierTypeInfo modifierType_Screw
ModifierTypeInfo modifierType_Ocean
ModifierTypeInfo modifierType_Warp
ModifierTypeInfo modifierType_NavMesh
ModifierTypeInfo modifierType_WeightVGEdit
ModifierTypeInfo modifierType_WeightVGMix
ModifierTypeInfo modifierType_WeightVGProximity
ModifierTypeInfo modifierType_DynamicPaint
ModifierTypeInfo modifierType_Remesh
Detailed Description
Definition in file MOD_modifiertypes.h.
Function Documentation
void modifier_type_init (ModifierTypeInfo * types[])
Definition at line 233 of file MOD_util.c.
References Bevel(), INIT_TYPE, Mask, Mirror(), None, and Warp().
Referenced by modifierType_getInfo().
Variable Documentation
ModifierTypeInfo modifierType_Armature
Definition at line 191 of file MOD_armature.c.
ModifierTypeInfo modifierType_Array
Definition at line 568 of file MOD_array.c.
ModifierTypeInfo modifierType_Bevel
Definition at line 209 of file MOD_bevel.c.
ModifierTypeInfo modifierType_Boolean
Definition at line 184 of file MOD_boolean.c.
ModifierTypeInfo modifierType_Build
Definition at line 299 of file MOD_build.c.
ModifierTypeInfo modifierType_Cast
Definition at line 617 of file MOD_cast.c.
ModifierTypeInfo modifierType_Cloth
Definition at line 204 of file MOD_cloth.c.
ModifierTypeInfo modifierType_Collision
Definition at line 236 of file MOD_collision.c.
ModifierTypeInfo modifierType_Curve
Definition at line 142 of file MOD_curve.c.
ModifierTypeInfo modifierType_Decimate
Definition at line 206 of file MOD_decimate.c.
ModifierTypeInfo modifierType_Displace
Definition at line 267 of file MOD_displace.c.
ModifierTypeInfo modifierType_DynamicPaint
Definition at line 165 of file MOD_dynamicpaint.c.
ModifierTypeInfo modifierType_EdgeSplit
Definition at line 166 of file MOD_edgesplit.c.
ModifierTypeInfo modifierType_Explode
Definition at line 1041 of file MOD_explode.c.
ModifierTypeInfo modifierType_Fluidsim
Definition at line 132 of file MOD_fluidsim.c.
ModifierTypeInfo modifierType_Hook
Definition at line 279 of file MOD_hook.c.
ModifierTypeInfo modifierType_Lattice
Definition at line 139 of file MOD_lattice.c.
ModifierTypeInfo modifierType_Mask
Definition at line 410 of file MOD_mask.c.
ModifierTypeInfo modifierType_MeshDeform
Definition at line 434 of file MOD_meshdeform.c.
ModifierTypeInfo modifierType_Mirror
Definition at line 346 of file MOD_mirror.c.
ModifierTypeInfo modifierType_Multires
Definition at line 123 of file MOD_multires.c.
ModifierTypeInfo modifierType_NavMesh
ModifierTypeInfo modifierType_None
Definition at line 51 of file MOD_none.c.
ModifierTypeInfo modifierType_Ocean
Definition at line 559 of file MOD_ocean.c.
ModifierTypeInfo modifierType_ParticleInstance
Definition at line 335 of file MOD_particleinstance.c.
ModifierTypeInfo modifierType_ParticleSystem
Definition at line 216 of file MOD_particlesystem.c.
ModifierTypeInfo modifierType_Remesh
Definition at line 209 of file MOD_remesh.c.
ModifierTypeInfo modifierType_Screw
Definition at line 948 of file MOD_screw.c.
ModifierTypeInfo modifierType_ShapeKey
Definition at line 126 of file MOD_shapekey.c.
ModifierTypeInfo modifierType_Shrinkwrap
Definition at line 163 of file MOD_shrinkwrap.c.
ModifierTypeInfo modifierType_SimpleDeform
Definition at line 349 of file MOD_simpledeform.c.
ModifierTypeInfo modifierType_Smoke
Definition at line 173 of file MOD_smoke.c.
ModifierTypeInfo modifierType_Smooth
Definition at line 242 of file MOD_smooth.c.
ModifierTypeInfo modifierType_Softbody
Definition at line 63 of file MOD_softbody.c.
ModifierTypeInfo modifierType_Solidify
Definition at line 737 of file MOD_solidify.c.
ModifierTypeInfo modifierType_Subsurf
Definition at line 126 of file MOD_subsurf.c.
ModifierTypeInfo modifierType_Surface
Definition at line 166 of file MOD_surface.c.
ModifierTypeInfo modifierType_UVProject
Definition at line 412 of file MOD_uvproject.c.
ModifierTypeInfo modifierType_Warp
Definition at line 354 of file MOD_warp.c.
ModifierTypeInfo modifierType_Wave
Definition at line 368 of file MOD_wave.c.
ModifierTypeInfo modifierType_WeightVGEdit
Definition at line 277 of file MOD_weightvgedit.c.
ModifierTypeInfo modifierType_WeightVGMix
Definition at line 409 of file MOD_weightvgmix.c.
ModifierTypeInfo modifierType_WeightVGProximity
Definition at line 544 of file MOD_weightvgproximity.c.