Blender: node_shader_sepcombRGB.c File Reference
node_shader_sepcombRGB.c File Reference
shdnodes
#include "node_shader_util.h"
Functions
static void node_shader_exec_seprgb (void *UNUSED(data), bNode *UNUSED(node), bNodeStack **in, bNodeStack **out)
static int gpu_shader_seprgb (GPUMaterial *mat, bNode *UNUSED(node), GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_seprgb (bNodeTreeType *ttype)
static void node_shader_exec_combrgb (void *UNUSED(data), bNode *UNUSED(node), bNodeStack **in, bNodeStack **out)
static int gpu_shader_combrgb (GPUMaterial *mat, bNode *UNUSED(node), GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_combrgb (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_seprgb_in []
static bNodeSocketTemplate sh_node_seprgb_out []
static bNodeSocketTemplate sh_node_combrgb_in []
static bNodeSocketTemplate sh_node_combrgb_out []
Detailed Description
Definition in file node_shader_sepcombRGB.c.
Function Documentation
static int gpu_shader_combrgb (GPUMaterial * mat, bNode * UNUSEDnode, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 94 of file node_shader_sepcombRGB.c.
References GPU_stack_link().
Referenced by register_node_type_sh_combrgb().
static int gpu_shader_seprgb (GPUMaterial * mat, bNode * UNUSEDnode, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 54 of file node_shader_sepcombRGB.c.
References GPU_stack_link().
Referenced by register_node_type_sh_seprgb().
static void node_shader_exec_combrgb (void * UNUSEDdata, bNode * UNUSEDnode, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 87 of file node_shader_sepcombRGB.c.
References bNodeStack::vec.
Referenced by register_node_type_sh_combrgb().
static void node_shader_exec_seprgb (void * UNUSEDdata, bNode * UNUSEDnode, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 47 of file node_shader_sepcombRGB.c.
References bNodeStack::vec.
Referenced by register_node_type_sh_seprgb().
void register_node_type_sh_combrgb (bNodeTreeType * ttype)
Definition at line 99 of file node_shader_sepcombRGB.c.
References gpu_shader_combrgb(), NODE_CLASS_CONVERTOR, NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_combrgb(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_COMBRGB.
Referenced by registerShaderNodes().
void register_node_type_sh_seprgb (bNodeTreeType * ttype)
Definition at line 59 of file node_shader_sepcombRGB.c.
References gpu_shader_seprgb(), NODE_CLASS_CONVERTOR, NODE_NEW_SHADING, NODE_OLD_SHADING, node_shader_exec_seprgb(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_SEPRGB.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_combrgb_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "R",         0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_UNSIGNED},
    {   SOCK_FLOAT, 1, "G",         0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_UNSIGNED},
    {   SOCK_FLOAT, 1, "B",         0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_UNSIGNED},
    {   -1, 0, ""   }
}
Definition at line 76 of file node_shader_sepcombRGB.c.
bNodeSocketTemplate sh_node_combrgb_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 82 of file node_shader_sepcombRGB.c.
bNodeSocketTemplate sh_node_seprgb_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          0.8f, 0.8f, 0.8f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_shader_sepcombRGB.c.
bNodeSocketTemplate sh_node_seprgb_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "R"},
    {   SOCK_FLOAT, 0, "G"},
    {   SOCK_FLOAT, 0, "B"},
    {   -1, 0, ""   }
}
Definition at line 40 of file node_shader_sepcombRGB.c.