Blender: rna_action.c File Reference
rna_action.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_anim_types.h"
#include "DNA_action_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BKE_action.h"
#include "WM_types.h"
Functions
static void rna_def_dopesheet (BlenderRNA *brna)
static void rna_def_action_group (BlenderRNA *brna)
static void rna_def_action_groups (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_action_fcurves (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_action_pose_markers (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_action (BlenderRNA *brna)
void RNA_def_action (BlenderRNA *brna)
Detailed Description
Definition in file rna_action.c.
Function Documentation
static void rna_def_action (BlenderRNA * brna) [static]
Definition at line 590 of file rna_action.c.
References id_type_items, NULL, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_NONE, RNA_api_action(), rna_def_action_fcurves(), rna_def_action_groups(), rna_def_action_pose_markers(), RNA_def_float_vector(), RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_action().
void RNA_def_action (BlenderRNA * brna)
Definition at line 640 of file rna_action.c.
References rna_def_action(), rna_def_action_group(), and rna_def_dopesheet().
static void rna_def_action_fcurves (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 518 of file rna_action.c.
References FUNC_USE_REPORTS, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_action().
static void rna_def_action_group (BlenderRNA * brna) [static]
Definition at line 438 of file rna_action.c.
References AGRP_EXPANDED, AGRP_PROTECTED, AGRP_SELECTED, NA_EDITED, NA_SELECTED, NC_ANIMATION, ND_ANIMCHAN, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_INT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_int_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_action().
static void rna_def_action_groups (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 490 of file rna_action.c.
References FUNC_USE_REPORTS, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_action().
static void rna_def_action_pose_markers (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 549 of file rna_action.c.
References FUNC_USE_REPORTS, NULL, PROP_EDITABLE, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_action().
static void rna_def_dopesheet (BlenderRNA * brna) [static]
Definition at line 252 of file rna_action.c.
References ADS_FILTER_BY_FCU_NAME, ADS_FILTER_INCL_HIDDEN, ADS_FILTER_NLA_NOACT, ADS_FILTER_NOARM, ADS_FILTER_NOCAM, ADS_FILTER_NOCUR, ADS_FILTER_NOLAM, ADS_FILTER_NOLAT, ADS_FILTER_NOMAT, ADS_FILTER_NOMBA, ADS_FILTER_NOMESH, ADS_FILTER_NONTREE, ADS_FILTER_NOOBJ, ADS_FILTER_NOPART, ADS_FILTER_NOSCE, ADS_FILTER_NOSHAPEKEYS, ADS_FILTER_NOSPK, ADS_FILTER_NOTEX, ADS_FILTER_NOWOR, ADS_FILTER_ONLYOBGROUP, ADS_FILTER_ONLYSEL, ADS_FILTER_SUMMARY, ADS_FLAG_SHOW_DBFILTERS, ADS_FLAG_SUMMARY_COLLAPSED, NA_EDITED, NC_ANIMATION, ND_ANIMCHAN, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_action().