Blender: Patch Class Reference
Patch Class Reference
#include <subd_patch.h>
Public Member Functions
virtual ~Patch ()
virtual void eval (float3 *P, float3 *dPdu, float3 *dPdv, float u, float v)=0
virtual bool is_triangle ()=0
virtual BoundBox bound ()=0
Detailed Description
Definition at line 31 of file subd_patch.h.
Constructor & Destructor Documentation
virtual Patch::~Patch () [inline, virtual]
Definition at line 33 of file subd_patch.h.
Member Function Documentation
virtual BoundBox Patch::bound () [pure virtual]
Implemented in LinearQuadPatch, LinearTrianglePatch, BicubicPatch, BicubicTangentPatch, GregoryQuadPatch, and GregoryTrianglePatch.
virtual void Patch::eval (float3 * P, float3 * dPdu, float3 * dPdv, float u, float v) [pure virtual]
Implemented in LinearQuadPatch, LinearTrianglePatch, BicubicPatch, BicubicTangentPatch, GregoryQuadPatch, and GregoryTrianglePatch.
Referenced by EdgeDice::add_vert(), QuadDice::eval_projected(), and DiagSplit::project().
virtual bool Patch::is_triangle () [pure virtual]
Implemented in LinearQuadPatch, LinearTrianglePatch, BicubicPatch, BicubicTangentPatch, GregoryQuadPatch, and GregoryTrianglePatch.
Referenced by QuadDice::add_corners(), and SubdMesh::tessellate().
The documentation for this class was generated from the following file:
subd_patch.h