Blender: CBoolValue Class Reference
CBoolValue Class Reference
#include <BoolValue.h>
Public Member Functions
CBoolValue ()
CBoolValue (bool inBool)
CBoolValue (bool innie, const char *name, AllocationTYPE alloctype=CValue::HEAPVALUE)
virtual const STR_String & GetText ()
virtual double GetNumber ()
bool GetBool ()
virtual void SetValue (CValue *newval)
virtual CValue * Calc (VALUE_OPERATOR op, CValue *val)
virtual CValue * CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue *val)
void Configure (CValue *menuvalue)
virtual CValue * GetReplica ()
Static Public Attributes
static const STR_String sTrueString = "TRUE"
static const STR_String sFalseString = "FALSE"
Detailed Description
Smart Boolean Value class. Is used by parser when an expression tree is build containing booleans.
Definition at line 29 of file BoolValue.h.
Constructor & Destructor Documentation
CBoolValue::CBoolValue ()
Definition at line 31 of file BoolValue.cpp.
References trace.
Referenced by Calc(), CalcFinal(), and GetReplica().
CBoolValue::CBoolValue (bool inBool)
Definition at line 42 of file BoolValue.cpp.
CBoolValue::CBoolValue (bool innie, const char * name, AllocationTYPE alloctype = CValue::HEAPVALUE)
Definition at line 49 of file BoolValue.cpp.
References CValue::DisableRefCount(), CPropValue::SetName(), and CValue::STACKVALUE.
Member Function Documentation
CValue * CBoolValue::Calc (VALUE_OPERATOR op, CValue * val) [virtual]
Implements CValue.
Definition at line 68 of file BoolValue.cpp.
References CValue::CalcFinal(), CBoolValue(), GetText(), CValue::op2str(), VALUE_BOOL_TYPE, VALUE_NEG_OPERATOR, VALUE_NOT_OPERATOR, and VALUE_POS_OPERATOR.
CValue * CBoolValue::CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue * val) [virtual]
Implements CValue.
Definition at line 98 of file BoolValue.cpp.
References CBoolValue(), GetBool(), CValue::GetText(), GetText(), CValue::op2str(), VALUE_ADD_OPERATOR, VALUE_AND_OPERATOR, VALUE_BOOL_TYPE, VALUE_EMPTY_TYPE, VALUE_EQL_OPERATOR, VALUE_NEQ_OPERATOR, VALUE_NOT_OPERATOR, VALUE_OR_OPERATOR, and VALUE_STRING_TYPE.
void CBoolValue::Configure (CValue * menuvalue)
bool CBoolValue::GetBool ()
Definition at line 174 of file BoolValue.cpp.
Referenced by CalcFinal().
double CBoolValue::GetNumber () [virtual]
Implements CValue.
Definition at line 185 of file BoolValue.cpp.
CValue * CBoolValue::GetReplica (void) [virtual]
Implements CValue.
Definition at line 199 of file BoolValue.cpp.
References CBoolValue(), and CValue::ProcessReplica().
const STR_String & CBoolValue::GetText () [virtual]
Implements CValue.
Definition at line 192 of file BoolValue.cpp.
References sFalseString, and sTrueString.
Referenced by Calc(), and CalcFinal().
void CBoolValue::SetValue (CValue * newval) [virtual]
Sets the value to this cvalue.
Attention:
this particular function should never be called. Why not abstract?
Reimplemented from CValue.
Definition at line 60 of file BoolValue.cpp.
References CValue::GetNumber(), and CValue::SetModified().
Member Data Documentation
const STR_String CBoolValue::sFalseString = "FALSE" [static]
Definition at line 36 of file BoolValue.h.
Referenced by CIfExpr::Calculate(), SCA_PropertySensor::CheckPropertyCondition(), and GetText().
const STR_String CBoolValue::sTrueString = "TRUE" [static]
Definition at line 35 of file BoolValue.h.
Referenced by CIfExpr::Calculate(), CListValue::CheckEqual(), SCA_PropertySensor::CheckPropertyCondition(), and GetText().
The documentation for this class was generated from the following files:
BoolValue.h
BoolValue.cpp