Blender: COperator1Expr Class Reference
COperator1Expr Class Reference
#include <Operator1Expr.h>
Public Member Functions
virtual bool MergeExpression (CExpression *otherexpr)
virtual void BroadcastOperators (VALUE_OPERATOR op)
virtual unsigned char GetExpressionID ()
CExpression * CheckLink (std::vector< CBrokenLinkInfo * > &brokenlinks)
virtual bool NeedsRecalculated ()
void ClearModified ()
virtual CValue * Calculate ()
COperator1Expr (VALUE_OPERATOR op, CExpression *lhs)
COperator1Expr ()
virtual ~COperator1Expr ()
Detailed Description
Definition at line 24 of file Operator1Expr.h.
Constructor & Destructor Documentation
COperator1Expr::COperator1Expr (VALUE_OPERATOR op, CExpression * lhs)
Definition at line 34 of file Operator1Expr.cpp.
COperator1Expr::COperator1Expr ()
Definition at line 25 of file Operator1Expr.cpp.
References NULL.
COperator1Expr::~COperator1Expr () [virtual]
Definition at line 44 of file Operator1Expr.cpp.
References CExpression::Release().
Member Function Documentation
void COperator1Expr::BroadcastOperators (VALUE_OPERATOR op) [virtual]
Implements CExpression.
Definition at line 135 of file Operator1Expr.cpp.
References CExpression::BroadcastOperators().
CValue * COperator1Expr::Calculate () [virtual]
Implements CExpression.
Definition at line 53 of file Operator1Expr.cpp.
References CValue::Calc(), CExpression::Calculate(), and CValue::Release().
CExpression * COperator1Expr::CheckLink (std::vector< CBrokenLinkInfo * > & brokenlinks) [virtual]
Implements CExpression.
Definition at line 106 of file Operator1Expr.cpp.
References CExpression::AddRef(), CExpression::CheckLink(), and CExpression::Release().
void COperator1Expr::ClearModified () [inline, virtual]
Implements CExpression.
Definition at line 38 of file Operator1Expr.h.
References CExpression::ClearModified().
virtual unsigned char COperator1Expr::GetExpressionID () [inline, virtual]
Implements CExpression.
Definition at line 34 of file Operator1Expr.h.
References CExpression::COPERATOR1EXPRESSIONID.
bool COperator1Expr::MergeExpression (CExpression * otherexpr) [virtual]
Implements CExpression.
Definition at line 144 of file Operator1Expr.cpp.
References assertd, and CExpression::MergeExpression().
bool COperator1Expr::NeedsRecalculated () [virtual]
Implements CExpression.
Definition at line 101 of file Operator1Expr.cpp.
References CExpression::NeedsRecalculated().
The documentation for this class was generated from the following files:
Operator1Expr.h
Operator1Expr.cpp