Blender: node_shader_math.c File Reference
node_shader_math.c File Reference
shdnodes
#include "node_shader_util.h"
Functions
static void node_shader_exec_math (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static int gpu_shader_math (GPUMaterial *mat, bNode *node, GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_math (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_math_in []
static bNodeSocketTemplate sh_node_math_out []
Detailed Description
Definition in file node_shader_math.c.
Function Documentation
static int gpu_shader_math (GPUMaterial * mat, bNode * node, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 199 of file node_shader_math.c.
References bNode::custom1, GPU_socket(), GPU_stack_link(), names, and NULL.
Referenced by register_node_type_sh_math().
static void node_shader_exec_math (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 48 of file node_shader_math.c.
References acos(), KDL::asin(), KDL::atan(), cos(), bNode::custom1, log(), pow(), sin(), KDL::tan(), and bNodeStack::vec.
Referenced by register_node_type_sh_math().
void register_node_type_sh_math (bNodeTreeType * ttype)
Definition at line 239 of file node_shader_math.c.
References gpu_shader_math(), NODE_CLASS_CONVERTOR, node_math_label(), NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_math(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_label(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_MATH.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_math_in[] [static]
Initial value:
 {
    { SOCK_FLOAT, 1, "Value", 0.5f, 0.5f, 0.5f, 1.0f, -10000.0f, 10000.0f, PROP_NONE},
    { SOCK_FLOAT, 1, "Value", 0.5f, 0.5f, 0.5f, 1.0f, -10000.0f, 10000.0f, PROP_NONE},
    { -1, 0, "" }
}
Definition at line 37 of file node_shader_math.c.
bNodeSocketTemplate sh_node_math_out[] [static]
Initial value:
 {
    { SOCK_FLOAT, 0, "Value"},
    { -1, 0, "" }
}
Definition at line 43 of file node_shader_math.c.