Blender: RAS_ListRasterizer Class Reference
RAS_ListRasterizer Class Reference
#include <RAS_ListRasterizer.h>
Public Member Functions
void RemoveListSlot (RAS_ListSlot *list)
RAS_ListRasterizer (RAS_ICanvas *canvas, bool useVertexArrays=false, bool lock=false)
virtual ~RAS_ListRasterizer ()
virtual void IndexPrimitives (class RAS_MeshSlot &ms)
virtual void IndexPrimitivesMulti (class RAS_MeshSlot &ms)
virtual bool Init ()
virtual void Exit ()
virtual void SetDrawingMode (int drawingmode)
virtual bool QueryLists ()
Detailed Description
Definition at line 52 of file RAS_ListRasterizer.h.
Constructor & Destructor Documentation
RAS_ListRasterizer::RAS_ListRasterizer (RAS_ICanvas * canvas, bool useVertexArrays = false, bool lock = false)
Definition at line 109 of file RAS_ListRasterizer.cpp.
RAS_ListRasterizer::~RAS_ListRasterizer () [virtual]
Definition at line 118 of file RAS_ListRasterizer.cpp.
Member Function Documentation
void RAS_ListRasterizer::Exit () [virtual]
Exit cleans up the renderer.
Reimplemented from RAS_VAOpenGLRasterizer.
Definition at line 302 of file RAS_ListRasterizer.cpp.
void RAS_ListRasterizer::IndexPrimitives (class RAS_MeshSlot & ms) [virtual]
IndexPrimitives: Renders primitives from mesh slot.
Reimplemented from RAS_VAOpenGLRasterizer.
Definition at line 227 of file RAS_ListRasterizer.cpp.
References RAS_ListSlot::DrawList(), RAS_ListSlot::End(), RAS_ListSlot::EndList(), RAS_MeshSlot::m_bDisplayList, RAS_MeshSlot::m_DisplayList, and RAS_MeshSlot::m_pDerivedMesh.
void RAS_ListRasterizer::IndexPrimitivesMulti (class RAS_MeshSlot & ms) [virtual]
Reimplemented from RAS_VAOpenGLRasterizer.
Definition at line 254 of file RAS_ListRasterizer.cpp.
References RAS_ListSlot::DrawList(), RAS_ListSlot::End(), RAS_ListSlot::EndList(), RAS_MeshSlot::m_bDisplayList, RAS_MeshSlot::m_DisplayList, and RAS_MeshSlot::m_pDerivedMesh.
bool RAS_ListRasterizer::Init () [virtual]
Init initializes the renderer.
Reimplemented from RAS_VAOpenGLRasterizer.
Definition at line 284 of file RAS_ListRasterizer.cpp.
virtual bool RAS_ListRasterizer::QueryLists () [inline, virtual]
Reimplemented from RAS_IRasterizer.
Definition at line 75 of file RAS_ListRasterizer.h.
void RAS_ListRasterizer::RemoveListSlot (RAS_ListSlot * list)
Definition at line 123 of file RAS_ListRasterizer.cpp.
References i, LIST_DERIVEDMESH, and NULL.
Referenced by RAS_ListSlot::Release().
void RAS_ListRasterizer::SetDrawingMode (int drawingmode) [virtual]
Parameters:
drawingmode = KX_BOUNDINGBOX, KX_WIREFRAME, KX_SOLID, KX_SHADED or KX_TEXTURED.
Reimplemented from RAS_VAOpenGLRasterizer.
Definition at line 293 of file RAS_ListRasterizer.cpp.
The documentation for this class was generated from the following files:
RAS_ListRasterizer.h
RAS_ListRasterizer.cpp