Blender: DNA_genfile.h File Reference
DNA_genfile.h File Reference
sDNA
blenloader genfile private function prototypes
Defines
#define SDNA_TYPE_VOID 9
Typedefs
typedef enum eSDNA_Type eSDNA_Type
Enumerations
enum eSDNA_Type {
SDNA_TYPE_CHAR = 0, SDNA_TYPE_UCHAR = 1, SDNA_TYPE_SHORT = 2, SDNA_TYPE_USHORT = 3,
SDNA_TYPE_INT = 4, SDNA_TYPE_LONG = 5, SDNA_TYPE_ULONG = 6, SDNA_TYPE_FLOAT = 7,
SDNA_TYPE_DOUBLE = 8, SDNA_TYPE_INT64 = 10, SDNA_TYPE_UINT64 = 11
}
Functions
struct SDNA * DNA_sdna_from_data (void *data, int datalen, int do_endian_swap)
void DNA_sdna_free (struct SDNA *sdna)
int DNA_struct_find_nr (struct SDNA *sdna, const char *str)
void DNA_struct_switch_endian (struct SDNA *oldsdna, int oldSDNAnr, char *data)
char * DNA_struct_get_compareflags (struct SDNA *sdna, struct SDNA *newsdna)
void * DNA_struct_reconstruct (struct SDNA *newsdna, struct SDNA *oldsdna, char *compflags, int oldSDNAnr, int blocks, void *data)
int DNA_elem_array_size (const char *astr, int len)
int DNA_elem_offset (struct SDNA *sdna, const char *stype, const char *vartype, const char *name)
int DNA_elem_type_size (const eSDNA_Type elem_nr)
Variables
unsigned char DNAstr []
int DNAlen
Detailed Description
blenloader genfile private function prototypes
Definition in file DNA_genfile.h.
Define Documentation
#define SDNA_TYPE_VOID 9
Definition at line 57 of file DNA_genfile.h.
Referenced by init_structDNA().
Typedef Documentation
typedef enum eSDNA_Type eSDNA_Type
Enumeration Type Documentation
enum eSDNA_Type
Enumerator:
SDNA_TYPE_CHAR
SDNA_TYPE_UCHAR
SDNA_TYPE_SHORT
SDNA_TYPE_USHORT
SDNA_TYPE_INT
SDNA_TYPE_LONG
SDNA_TYPE_ULONG
SDNA_TYPE_FLOAT
SDNA_TYPE_DOUBLE
SDNA_TYPE_INT64
SDNA_TYPE_UINT64
Definition at line 41 of file DNA_genfile.h.
Function Documentation
int DNA_elem_array_size (const char * astr, int len)
Definition at line 174 of file dna_genfile.c.
References len(), mul(), NULL, and str.
Referenced by cast_elem(), cast_pointer(), DNA_struct_switch_endian(), elementsize(), reconstruct_elem(), reconstruct_struct(), and rna_find_sdna_member().
int DNA_elem_offset (struct SDNA * sdna, const char * stype, const char * vartype, const char * name)
Definition at line 1155 of file dna_genfile.c.
References DNA_struct_find_nr(), find_elem(), NULL, and SDNA::structs.
Referenced by read_file_dna().
int DNA_elem_type_size (const eSDNA_Type elem_nr)
Definition at line 1164 of file dna_genfile.c.
References SDNA_TYPE_CHAR, SDNA_TYPE_DOUBLE, SDNA_TYPE_FLOAT, SDNA_TYPE_INT, SDNA_TYPE_INT64, SDNA_TYPE_LONG, SDNA_TYPE_SHORT, SDNA_TYPE_UCHAR, SDNA_TYPE_UINT64, SDNA_TYPE_ULONG, and SDNA_TYPE_USHORT.
Referenced by cast_elem().
void DNA_sdna_free (struct SDNA * sdna)
Definition at line 198 of file dna_genfile.c.
References BLI_ghash_free(), SDNA::data, MEM_freeN(), SDNA::names, NULL, SDNA::structs, SDNA::structs_map, and SDNA::types.
Referenced by blo_freefiledata(), RNA_define_free(), and writedata_free().
struct SDNA* DNA_sdna_from_data (void * data, int datalen, int do_endian_swap) [read]
Definition at line 511 of file dna_genfile.c.
References SDNA::data, SDNA::datalen, init_structDNA(), SDNA::lastfind, and MEM_mallocN().
Referenced by filedata_new(), read_file_dna(), RNA_create(), and writedata_new().
int DNA_struct_find_nr (struct SDNA * sdna, const char * str)
Definition at line 283 of file dna_genfile.c.
References BLI_ghash_lookup(), SDNA::lastfind, SDNA::nr_structs, NULL, SDNA::structs, SDNA::structs_map, and SDNA::types.
Referenced by BLO_blendhandle_get_previews(), DNA_elem_offset(), DNA_struct_reconstruct(), DNA_struct_switch_endian(), reconstruct_struct(), RNA_def_struct_sdna(), RNA_def_struct_sdna_from(), rna_find_sdna_member(), and writestruct().
char* DNA_struct_get_compareflags (struct SDNA * sdna, struct SDNA * newsdna)
Definition at line 570 of file dna_genfile.c.
References findstruct_name(), ispointer(), MEM_callocN(), SDNA::names, SDNA::nr_structs, NULL, SDNA::pointerlen, recurs_test_compflags(), SDNA::structs, SDNA::typelens, and SDNA::types.
Referenced by read_file_dna().
void* DNA_struct_reconstruct (struct SDNA * newsdna, struct SDNA * oldsdna, char * compflags, int oldSDNAnr, int blocks, void * data)
Definition at line 1122 of file dna_genfile.c.
References data, DNA_struct_find_nr(), MEM_callocN(), NULL, reconstruct_struct(), SDNA::structs, SDNA::typelens, and SDNA::types.
Referenced by read_struct().
void DNA_struct_switch_endian (struct SDNA * oldsdna, int oldSDNAnr, char * data)
Definition at line 997 of file dna_genfile.c.
References data, DNA_elem_array_size(), DNA_struct_find_nr(), DNA_struct_switch_endian(), elementsize(), find_elem(), ispointer(), mul(), SDNA::names, NULL, SDNA::pointerlen, SDNA_TYPE_FLOAT, SDNA_TYPE_INT, SDNA_TYPE_INT64, SDNA_TYPE_LONG, SDNA_TYPE_SHORT, SDNA_TYPE_UINT64, SDNA_TYPE_ULONG, SDNA_TYPE_USHORT, strlen(), SDNA::structs, and SDNA::types.
Referenced by DNA_struct_switch_endian(), and switch_endian_structs().
Variable Documentation
int DNAlen
Referenced by filedata_new(), RNA_create(), and writedata_new().
unsigned char DNAstr[]
Referenced by filedata_new(), RNA_create(), and writedata_new().