Blender: bmesh_py_utils.c File Reference
bmesh_py_utils.c File Reference
#include <Python.h>
#include "BLI_utildefines.h"
#include "MEM_guardedalloc.h"
#include "../mathutils/mathutils.h"
#include "bmesh.h"
#include "bmesh_py_types.h"
#include "bmesh_py_utils.h"
Functions
PyDoc_STRVAR (bpy_bm_utils_vert_collapse_edge_doc,".. method:: vert_collapse_edge(vert, edge)\n""\n"" Collapse a vertex into an edge.\n""\n"" :arg vert: The vert that will be collapsed.\n"" :type vert: :class:`bmesh.types.BMVert`\n"" :arg edge: The edge to collapse into.\n"" :type edge: :class:`bmesh.types.BMEdge`\n"" :return: The resulting edge from the collapse operation.\n"" :rtype: :class:`bmesh.types.BMEdge`\n")
static PyObject * bpy_bm_utils_vert_collapse_edge (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (bpy_bm_utils_vert_collapse_faces_doc,".. method:: vert_collapse_faces(vert, edge, fac, join_faces)\n""\n"" Split an edge, return the newly created data.\n""\n"" :arg vert: The vert that will be collapsed.\n"" :type vert: :class:`bmesh.types.BMVert`\n"" :arg edge: The edge to collapse into.\n"" :type edge: :class:`bmesh.types.BMEdge`\n"" :arg fac: The factor to use when merging customdata [0 - 1].\n"" :type fac: float\n"" :return: The resulting edge from the collapse operation.\n"" :rtype: :class:`bmesh.types.BMEdge`\n")
static PyObject * bpy_bm_utils_vert_collapse_faces (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (bpy_bm_utils_vert_dissolve_doc,".. method:: vert_dissolve(vert)\n""\n"" Dissolve this vertex (will be removed).\n""\n"" :arg vert: The vert to be dissolved.\n"" :type vert: :class:`bmesh.types.BMVert`\n"" :return: True when the vertex dissolve is successful.\n"" :rtype: boolean\n")
static PyObject * bpy_bm_utils_vert_dissolve (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (bpy_bm_utils_vert_separate_doc,".. method:: vert_separate(vert, edges)\n""\n"" Separate this vertex at every edge.\n""\n"" :arg vert: The vert to be separated.\n"" :type vert: :class:`bmesh.types.BMVert`\n"" :arg edges: The edges to separated.\n"" :type edges: :class:`bmesh.types.BMEdge`\n"" :return: The newly separated verts (including the vertex passed).\n"" :rtype: tuple of :class:`bmesh.types.BMVert`\n")
static PyObject * bpy_bm_utils_vert_separate (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (bpy_bm_utils_edge_split_doc,".. method:: edge_split(edge, vert, fac)\n""\n"" Split an edge, return the newly created data.\n""\n"" :arg edge: The edge to split.\n"" :type edge: :class:`bmesh.types.BMEdge`\n"" :arg vert: One of the verts on the edge, defines the split direction.\n"" :type vert: :class:`bmesh.types.BMVert`\n"" :arg fac: The point on the edge where the new vert will be created [0 - 1].\n"" :type fac: float\n"" :return: The newly created (edge, vert) pair.\n"" :rtype: tuple\n")
static PyObject * bpy_bm_utils_edge_split (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (bpy_bm_utils_edge_rotate_doc,".. method:: edge_rotate(edge, ccw=False)\n""\n"" Rotate the edge and return the newly created edge.\n"" If rotating the edge fails, None will be returned.\n""\n"" :arg edge: The edge to rotate.\n"" :type edge: :class:`bmesh.types.BMEdge`\n"" :arg ccw: When True the edge will be rotated counter clockwise.\n"" :type ccw: boolean\n"" :return: The newly rotated edge.\n"" :rtype: :class:`bmesh.types.BMEdge`\n")
static PyObject * bpy_bm_utils_edge_rotate (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (bpy_bm_utils_face_split_doc,".. method:: face_split(face, vert_a, vert_b, coords=(), use_exist=True, example=None)\n""\n"" Split an edge, return the newly created data.\n""\n"" :arg face: The face to cut.\n"" :type face: :class:`bmesh.types.BMFace`\n"" :arg vert_a: First vertex to cut in the face (face must contain the vert).\n"" :type vert_a: :class:`bmesh.types.BMVert`\n"" :arg vert_b: Second vertex to cut in the face (face must contain the vert).\n"" :type vert_b: :class:`bmesh.types.BMVert`\n"" :arg coords: Optional argument to define points inbetween *vert_a* and *vert_b*.\n"" :type coords: sequence of float triplets\n"" :arg use_exist: .Use an existing edge if it exists (Only used when *coords* argument is empty or omitted)\n"" :type use_exist: boolean\n"" :arg example: Newly created edge will copy settings from this one.\n"" :type example: :class:`bmesh.types.BMEdge`\n"" :return: The newly created face or None on failure.\n"" :rtype: (:class:`bmesh.types.BMFace`, :class:`bmesh.types.BMLoop`) pair\n")
static PyObject * bpy_bm_utils_face_split (PyObject *UNUSED(self), PyObject *args, PyObject *kw)
PyDoc_STRVAR (bpy_bm_utils_face_join_doc,".. method:: face_join(faces, remove=True)\n""\n"" Joins a sequence of faces.\n""\n"" :arg faces: Sequence of faces.\n"" :type faces: :class:`bmesh.types.BMFace`\n"" :arg remove: Remove the edges and vertices between the faces.\n"" :type remove: boolean\n"" :return: The newly created face or None on failure.\n"" :rtype: :class:`bmesh.types.BMFace`\n")
static PyObject * bpy_bm_utils_face_join (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (bpy_bm_utils_face_vert_separate_doc,".. method:: face_vert_separate(face, vert)\n""\n"" Rip a vertex in a face away and add a new vertex.\n""\n"" :arg face: The face to separate.\n"" :type face: :class:`bmesh.types.BMFace`\n"" :arg vert: A vertex in the face to separate.\n"" :type vert: :class:`bmesh.types.BMVert`\n"" :return vert: The newly created vertex or None of failure.\n"" :rtype vert: :class:`bmesh.types.BMVert`\n""\n"" .. note::\n""\n"" This is the same as loop_separate, and has only been added for convenience.\n")
static PyObject * bpy_bm_utils_face_vert_separate (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (bpy_bm_utils_face_flip_doc,".. method:: face_flip(faces)\n""\n"" Flip the faces direction.\n""\n"" :arg face: Face to flip.\n"" :type face: :class:`bmesh.types.BMFace`\n")
static PyObject * bpy_bm_utils_face_flip (PyObject *UNUSED(self), BPy_BMFace *value)
PyDoc_STRVAR (bpy_bm_utils_loop_separate_doc,".. method:: loop_separate(loop)\n""\n"" Rip a vertex in a face away and add a new vertex.\n""\n"" :arg loop: The to separate.\n"" :type loop: :class:`bmesh.types.BMFace`\n"" :return vert: The newly created vertex or None of failure.\n"" :rtype vert: :class:`bmesh.types.BMVert`\n")
static PyObject * bpy_bm_utils_loop_separate (PyObject *UNUSED(self), BPy_BMLoop *value)
PyDoc_STRVAR (BPy_BM_doc,"This module provides access to blenders bmesh data structures.")
PyObject * BPyInit_bmesh_utils (void)
Variables
static struct PyMethodDef BPy_BM_utils_methods []
static struct PyModuleDef BPy_BM_types_module_def
Function Documentation
static PyObject* bpy_bm_utils_edge_rotate (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 340 of file bmesh_py_utils.c.
References BPy_BMEdge::bm, BM_edge_rotate(), BPY_BM_CHECK_OBJ, BPy_BMEdge_CreatePyObject(), BPy_BMEdge_Type, BPy_BMEdge::e, FALSE, and NULL.
static PyObject* bpy_bm_utils_edge_split (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 279 of file bmesh_py_utils.c.
References BPy_BMEdge::bm, BM_edge_split(), BPY_BM_CHECK_OBJ, BPy_BMEdge_CreatePyObject(), BPy_BMEdge_Type, BPy_BMVert_CreatePyObject(), BPy_BMVert_Type, CLAMPIS, BPy_BMEdge::e, NULL, BPy_BMVert::v, BMEdge::v1, and BMEdge::v2.
static PyObject* bpy_bm_utils_face_flip (PyObject * UNUSEDself, BPy_BMFace * value) [static]
Definition at line 599 of file bmesh_py_utils.c.
References BPy_BMFace::bm, BM_face_normal_flip(), BPY_BM_CHECK_OBJ, BPy_BMFace_Check, BPy_BMFace::f, and NULL.
static PyObject* bpy_bm_utils_face_join (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 493 of file bmesh_py_utils.c.
References BM_FACE, BM_faces_join(), BPy_BMElem_PySeq_As_Array(), BPy_BMFace_CreatePyObject(), NULL, and TRUE.
static PyObject* bpy_bm_utils_face_split (PyObject * UNUSEDself, PyObject * args, PyObject * kw) [static]
Definition at line 390 of file bmesh_py_utils.c.
References BPy_BMFace::bm, BM_face_split(), BM_face_split_n(), BM_vert_in_face(), BPY_BM_CHECK_OBJ, BPy_BMEdge_Type, BPy_BMFace_CreatePyObject(), BPy_BMFace_Type, BPy_BMLoop_CreatePyObject(), BPy_BMVert_Type, BPy_BMEdge::e, BPy_BMFace::f, FALSE, mathutils_array_parse_alloc_v(), NULL, TRUE, and BPy_BMVert::v.
static PyObject* bpy_bm_utils_face_vert_separate (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 545 of file bmesh_py_utils.c.
References BPy_BMVert::bm, BPy_BMFace::bm, BM_face_loop_separate(), BM_face_vert_share_loop(), BPY_BM_CHECK_OBJ, BPy_BMFace_Type, BPy_BMVert_CreatePyObject(), BPy_BMVert_Type, BPy_BMFace::f, NULL, BPy_BMVert::v, and BMLoop::v.
static PyObject* bpy_bm_utils_loop_separate (PyObject * UNUSEDself, BPy_BMLoop * value) [static]
Definition at line 627 of file bmesh_py_utils.c.
References BPy_BMLoop::bm, BM_face_loop_separate(), BPY_BM_CHECK_OBJ, BPy_BMLoop_Check, BPy_BMVert_CreatePyObject(), BPy_BMLoop::l, NULL, and BMLoop::v.
static PyObject* bpy_bm_utils_vert_collapse_edge (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 60 of file bmesh_py_utils.c.
References BPy_BMEdge::bm, BM_vert_collapse_edge(), BM_vert_edge_count(), BPY_BM_CHECK_OBJ, BPy_BMEdge_CreatePyObject(), BPy_BMEdge_Type, BPy_BMVert_Type, BPy_BMEdge::e, NULL, TRUE, BPy_BMVert::v, BMEdge::v1, and BMEdge::v2.
static PyObject* bpy_bm_utils_vert_collapse_faces (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 122 of file bmesh_py_utils.c.
References BPy_BMEdge::bm, BM_vert_collapse_faces(), BM_vert_edge_count(), BPY_BM_CHECK_OBJ, BPy_BMEdge_CreatePyObject(), BPy_BMEdge_Type, BPy_BMVert_Type, CLAMPIS, BPy_BMEdge::e, NULL, TRUE, BPy_BMVert::v, BMEdge::v1, and BMEdge::v2.
static PyObject* bpy_bm_utils_vert_dissolve (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 184 of file bmesh_py_utils.c.
References BPy_BMVert::bm, BM_vert_dissolve(), BPY_BM_CHECK_OBJ, BPy_BMVert_Type, NULL, and BPy_BMVert::v.
static PyObject* bpy_bm_utils_vert_separate (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 215 of file bmesh_py_utils.c.
References BPy_BMVert::bm, BM_EDGE, BM_vert_separate(), BPY_BM_CHECK_OBJ, BPy_BMElem_Array_As_Tuple(), BPy_BMElem_PySeq_As_Array(), BPy_BMVert_Type, MEM_freeN(), NULL, TRUE, and BPy_BMVert::v.
PyObject* BPyInit_bmesh_utils (void)
Definition at line 686 of file bmesh_py_utils.c.
Referenced by BPyInit_bmesh().
PyDoc_STRVAR (bpy_bm_utils_face_split_doc , ".. method:: face_split(face, vert_a, vert_b, coords=(), use_exist=True, example=None)\n""\n"" Split an edge, return the newly created data.\n""\n"":arg face:The face to cut.\n"":type face::class:`bmesh.types.BMFace`\n"":arg vert_a:First vertex to cut in the face(face must contain the vert).\n"":type vert_a::class:`bmesh.types.BMVert`\n"":arg vert_b:Second vertex to cut in the face(face must contain the vert).\n"":type vert_b::class:`bmesh.types.BMVert`\n"":arg coords:Optional argument to define points inbetween *vert_a *and *vert_b *.\n"":type coords:sequence of float triplets\n"":arg use_exist:.Use an existing edge if it exists(Only used when *coords *argument is empty or omitted)\n"":type use_exist:boolean\n"":arg example:Newly created edge will copy settings from this one.\n"":type example::class:`bmesh.types.BMEdge`\n"":return:The newly created face or None on failure.\n"":rtype:(:class:`bmesh.types.BMFace`,:class:`bmesh.types.BMLoop`) pair\n")
PyDoc_STRVAR (bpy_bm_utils_loop_separate_doc , ".. method:: loop_separate(loop)\n""\n"" Rip a vertex in a face away and add a new vertex.\n""\n"" :arg loop: The to separate.\n"" :type loop: :class:`bmesh.types.BMFace`\n"" :return vert: The newly created vertex or None of failure.\n"" :rtype vert: :class:`bmesh.types.BMVert`\n")
PyDoc_STRVAR (BPy_BM_doc , "This module provides access to blenders bmesh data structures.")
PyDoc_STRVAR (bpy_bm_utils_vert_dissolve_doc , ".. method:: vert_dissolve(vert)\n""\n"" Dissolve this vertex (will be removed).\n""\n"" :arg vert: The vert to be dissolved.\n"" :type vert: :class:`bmesh.types.BMVert`\n"" :return: True when the vertex dissolve is successful.\n"" :rtype: boolean\n")
PyDoc_STRVAR (bpy_bm_utils_edge_rotate_doc , ".. method:: edge_rotate(edge, ccw=False)\n""\n"" Rotate the edge and return the newly created edge.\n"" If rotating the edge fails, None will be returned.\n""\n"":arg edge:The edge to rotate.\n"":type edge::class:`bmesh.types.BMEdge`\n"":arg ccw:When True the edge will be rotated counter clockwise.\n"":type ccw:boolean\n"":return:The newly rotated edge.\n"":rtype::class:`bmesh.types.BMEdge`\n")
PyDoc_STRVAR (bpy_bm_utils_face_flip_doc , ".. method:: face_flip(faces)\n""\n"" Flip the faces direction.\n""\n"" :arg face: Face to flip.\n"" :type face: :class:`bmesh.types.BMFace`\n")
PyDoc_STRVAR (bpy_bm_utils_vert_collapse_faces_doc , ".. method:: vert_collapse_faces(vert, edge, fac, join_faces)\n""\n"" Split an edge, return the newly created data.\n""\n"":arg vert:The vert that will be collapsed.\n"":type vert::class:`bmesh.types.BMVert`\n"":arg edge:The edge to collapse into.\n"":type edge::class:`bmesh.types.BMEdge`\n"":arg fac:The factor to use when merging customdata.\n"":type fac:float\n"":return:The resulting edge from the collapse operation.\n"":rtype::class:`bmesh.types.BMEdge`\n" [0-1])
PyDoc_STRVAR (bpy_bm_utils_vert_collapse_edge_doc , ".. method:: vert_collapse_edge(vert, edge)\n""\n"" Collapse a vertex into an edge.\n""\n"" :arg vert: The vert that will be collapsed.\n"" :type vert: :class:`bmesh.types.BMVert`\n"" :arg edge: The edge to collapse into.\n"" :type edge: :class:`bmesh.types.BMEdge`\n"" :return: The resulting edge from the collapse operation.\n"" :rtype: :class:`bmesh.types.BMEdge`\n")
PyDoc_STRVAR (bpy_bm_utils_edge_split_doc , ".. method:: edge_split(edge, vert, fac)\n""\n"" Split an edge, return the newly created data.\n""\n"":arg edge:The edge to split.\n"":type edge::class:`bmesh.types.BMEdge`\n"":arg vert:One of the verts on the edge, defines the split direction.\n"":type vert::class:`bmesh.types.BMVert`\n"":arg fac:The point on the edge where the new vert will be created.\n"":type fac:float\n"":return:The newly created(edge, vert) pair.\n"":rtype:tuple\n" [0-1])
PyDoc_STRVAR (bpy_bm_utils_face_vert_separate_doc , ".. method:: face_vert_separate(face, vert)\n""\n"" Rip a vertex in a face away and add a new vertex.\n""\n"" :arg face: The face to separate.\n"" :type face: :class:`bmesh.types.BMFace`\n"" :arg vert: A vertex in the face to separate.\n"" :type vert: :class:`bmesh.types.BMVert`\n"" :return vert: The newly created vertex or None of failure.\n"" :rtype vert: :class:`bmesh.types.BMVert`\n""\n"" .. note::\n""\n"" This is the same as loop_separate, and has only been added for convenience.\n")
PyDoc_STRVAR (bpy_bm_utils_vert_separate_doc , ".. method:: vert_separate(vert, edges)\n""\n"" Separate this vertex at every edge.\n""\n"" :arg vert: The vert to be separated.\n"" :type vert: :class:`bmesh.types.BMVert`\n"" :arg edges: The edges to separated.\n"" :type edges: :class:`bmesh.types.BMEdge`\n"" :return: The newly separated verts (including the vertex passed).\n"" :rtype: tuple of :class:`bmesh.types.BMVert`\n")
PyDoc_STRVAR (bpy_bm_utils_face_join_doc , ".. method:: face_join(faces, remove=True)\n""\n"" Joins a sequence of faces.\n""\n"" :arg faces: Sequence of faces.\n"" :type faces: :class:`bmesh.types.BMFace`\n"" :arg remove: Remove the edges and vertices between the faces.\n"" :type remove: boolean\n"" :return: The newly created face or None on failure.\n"" :rtype: :class:`bmesh.types.BMFace`\n")
Variable Documentation
struct PyModuleDef BPy_BM_types_module_def [static]
Initial value:
 {
    PyModuleDef_HEAD_INIT,
    "bmesh.utils",
    BPy_BM_doc,
    0,
    BPy_BM_utils_methods,
    NULL,
    NULL,
    NULL,
    NULL,
}
Definition at line 673 of file bmesh_py_utils.c.
struct PyMethodDef BPy_BM_utils_methods[] [static]
Initial value:
 {
    {"vert_collapse_edge",  (PyCFunction)bpy_bm_utils_vert_collapse_edge,  METH_VARARGS, bpy_bm_utils_vert_collapse_edge_doc},
    {"vert_collapse_faces", (PyCFunction)bpy_bm_utils_vert_collapse_faces, METH_VARARGS, bpy_bm_utils_vert_collapse_faces_doc},
    {"vert_dissolve",       (PyCFunction)bpy_bm_utils_vert_dissolve,       METH_VARARGS, bpy_bm_utils_vert_dissolve_doc},
    {"vert_separate",       (PyCFunction)bpy_bm_utils_vert_separate,       METH_VARARGS, bpy_bm_utils_vert_separate_doc},
    {"edge_split",          (PyCFunction)bpy_bm_utils_edge_split,          METH_VARARGS, bpy_bm_utils_edge_split_doc},
    {"edge_rotate",         (PyCFunction)bpy_bm_utils_edge_rotate,         METH_VARARGS, bpy_bm_utils_edge_rotate_doc},
    {"face_split",          (PyCFunction)bpy_bm_utils_face_split,          METH_VARARGS | METH_KEYWORDS, bpy_bm_utils_face_split_doc},
    {"face_join",           (PyCFunction)bpy_bm_utils_face_join,           METH_VARARGS, bpy_bm_utils_face_join_doc},
    {"face_vert_separate",  (PyCFunction)bpy_bm_utils_face_vert_separate,  METH_VARARGS, bpy_bm_utils_face_vert_separate_doc},
    {"face_flip",           (PyCFunction)bpy_bm_utils_face_flip,           METH_O,       bpy_bm_utils_face_flip_doc},
    {"loop_separate",       (PyCFunction)bpy_bm_utils_loop_separate,       METH_O,       bpy_bm_utils_loop_separate_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 654 of file bmesh_py_utils.c.