Blender: btConeShape Class Reference
btConeShape Class Reference
The btConeShape implements a cone shape primitive, centered around the origin and aligned with the Y axis. The btConeShapeX is aligned around the X axis and btConeShapeZ around the Z axis.
#include <btConeShape.h>
Public Member Functions
btConeShape (btScalar radius, btScalar height)
virtual btVector3 localGetSupportingVertex (const btVector3 &vec) const
virtual btVector3 localGetSupportingVertexWithoutMargin (const btVector3 &vec) const
virtual void batchedUnitVectorGetSupportingVertexWithoutMargin (const btVector3 *vectors, btVector3 *supportVerticesOut, int numVectors) const
btScalar getRadius () const
btScalar getHeight () const
virtual void calculateLocalInertia (btScalar mass, btVector3 &inertia) const
virtual const char * getName () const
void setConeUpIndex (int upIndex)
choose upAxis index
int getConeUpIndex () const
virtual void setLocalScaling (const btVector3 &scaling)
Detailed Description
The btConeShape implements a cone shape primitive, centered around the origin and aligned with the Y axis. The btConeShapeX is aligned around the X axis and btConeShapeZ around the Z axis.
Definition at line 23 of file btConeShape.h.
Constructor & Destructor Documentation
btConeShape::btConeShape (btScalar radius, btScalar height)
Definition at line 20 of file btConeShape.cpp.
References btSqrt(), CONE_SHAPE_PROXYTYPE, and setConeUpIndex().
Member Function Documentation
void btConeShape::batchedUnitVectorGetSupportingVertexWithoutMargin (const btVector3 * vectors, btVector3 * supportVerticesOut, int numVectors) const [virtual]
Definition at line 107 of file btConeShape.cpp.
References i.
virtual void btConeShape::calculateLocalInertia (btScalar mass, btVector3 & inertia) const [inline, virtual]
Definition at line 45 of file btConeShape.h.
References btConvexInternalShape::getAabb(), btConvexInternalShape::getMargin(), and btTransform::setIdentity().
int btConeShape::getConeUpIndex () const [inline]
Definition at line 80 of file btConeShape.h.
Referenced by btCollisionWorld::debugDrawObject().
btScalar btConeShape::getHeight () const [inline]
Definition at line 42 of file btConeShape.h.
Referenced by btCollisionWorld::debugDrawObject().
virtual const char* btConeShape::getName (void) const [inline, virtual]
Definition at line 72 of file btConeShape.h.
btScalar btConeShape::getRadius () const [inline]
Definition at line 41 of file btConeShape.h.
Referenced by btCollisionWorld::debugDrawObject().
btVector3 btConeShape::localGetSupportingVertex (const btVector3 & vec) const [virtual]
Reimplemented from btConvexInternalShape.
Definition at line 117 of file btConeShape.cpp.
References btConvexInternalShape::getMargin(), and SIMD_EPSILON.
btVector3 btConeShape::localGetSupportingVertexWithoutMargin (const btVector3 & vec) const [virtual]
Definition at line 102 of file btConeShape.cpp.
void btConeShape::setConeUpIndex (int upIndex)
choose upAxis index
Definition at line 43 of file btConeShape.cpp.
References btAssert.
Referenced by btConeShape(), btConeShapeX::btConeShapeX(), and btConeShapeZ::btConeShapeZ().
void btConeShape::setLocalScaling (const btVector3 & scaling) [virtual]
Reimplemented from btConvexInternalShape.
Definition at line 134 of file btConeShape.cpp.
References btSqrt(), and btConvexInternalShape::m_localScaling.
The documentation for this class was generated from the following files:
btConeShape.h
btConeShape.cpp