Blender: wmOperatorType Struct Reference
wmOperatorType Struct Reference
#include <WM_types.h>
Public Attributes
const char * name
const char * idname
const char * description
int(* exec)(struct bContext *, struct wmOperator *)
int(* check)(struct bContext *, struct wmOperator *)
int(* invoke)(struct bContext *, struct wmOperator *, struct wmEvent *)
int(* cancel)(struct bContext *, struct wmOperator *)
int(* modal)(struct bContext *, struct wmOperator *, struct wmEvent *)
int(* poll)(struct bContext *)
void(* ui)(struct bContext *, struct wmOperator *)
struct StructRNA * srna
struct IDProperty * last_properties
PropertyRNA * prop
ListBase macro
struct wmKeyMap * modalkeymap
void * pyop_data
int(* pyop_poll)(struct bContext *, struct wmOperatorType *ot)
ExtensionRNA ext
short flag
Detailed Description
Definition at line 431 of file WM_types.h.
Member Data Documentation
int(* wmOperatorType::cancel)(struct bContext *, struct wmOperator *)
Definition at line 453 of file WM_types.h.
Referenced by ACTION_OT_select_border(), ANIM_OT_channels_select_border(), ANIM_OT_previewrange_set(), BUTTONS_OT_directory_browse(), BUTTONS_OT_file_browse(), CLIP_OT_open(), CLIP_OT_view_pan(), CLIP_OT_view_zoom(), CONSOLE_OT_select_set(), FILE_OT_select_border(), FONT_OT_open(), GPENCIL_OT_draw(), GRAPH_OT_select_border(), IMAGE_OT_curves_point_set(), IMAGE_OT_open(), IMAGE_OT_record_composite(), IMAGE_OT_sample(), IMAGE_OT_sample_line(), IMAGE_OT_save_as(), IMAGE_OT_view_pan(), IMAGE_OT_view_zoom(), INFO_OT_select_border(), LOGIC_OT_links_cut(), MARKER_OT_duplicate(), MARKER_OT_move(), MARKER_OT_select_border(), MESH_OT_knife_tool(), MESH_OT_loopcut(), MESH_OT_vert_slide(), NLA_OT_select_border(), NODE_OT_backimage_move(), NODE_OT_backimage_sample(), NODE_OT_link(), NODE_OT_links_cut(), NODE_OT_resize(), NODE_OT_select_border(), OUTLINER_OT_select_border(), PAINT_OT_grab_clone(), PAINT_OT_image_paint(), PAINT_OT_vertex_paint(), PAINT_OT_weight_paint(), PARTICLE_OT_brush_edit(), POSE_OT_breakdown(), POSE_OT_push(), POSE_OT_relax(), POSELIB_OT_browse_interactive(), RENDER_OT_opengl(), SCREEN_OT_actionzone(), SCREEN_OT_area_join(), SCREEN_OT_area_move(), SCREEN_OT_area_split(), SCREEN_OT_area_swap(), SCREEN_OT_region_scale(), SCREEN_OT_screenshot(), SCULPT_OT_brush_stroke(), SEQUENCER_OT_select_border(), SEQUENCER_OT_view_ghost_border(), sketch_draw_modal(), SKETCH_OT_draw_stroke(), SKETCH_OT_gesture(), SOUND_OT_open(), SOUND_OT_open_mono(), TEXT_OT_open(), TEXT_OT_scroll(), TEXT_OT_scroll_bar(), TEXT_OT_selection_set(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), TRANSFORM_OT_warp(), UI_OT_eyedropper(), UV_OT_circle_select(), UV_OT_minimize_stretch(), UV_OT_select_border(), UV_OT_stitch(), VIEW2D_OT_pan(), VIEW2D_OT_scroller_activate(), VIEW2D_OT_zoom(), VIEW2D_OT_zoom_border(), VIEW3D_OT_clip_border(), VIEW3D_OT_dolly(), VIEW3D_OT_fly(), VIEW3D_OT_move(), VIEW3D_OT_render_border(), VIEW3D_OT_rotate(), VIEW3D_OT_select_border(), VIEW3D_OT_select_circle(), VIEW3D_OT_select_lasso(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), WM_event_remove_handlers(), wm_handler_fileselect_call(), wm_macro_cancel(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), and WM_OT_radial_control().
int(* wmOperatorType::check)(struct bContext *, struct wmOperator *)
Definition at line 446 of file WM_types.h.
Referenced by dialog_check_cb(), ED_undo_operator_repeat(), file_draw_check_cb(), IMAGE_OT_save_as(), SCREEN_OT_screenshot(), WM_event_add_fileselect(), WM_OT_save_as_mainfile(), and WM_OT_save_mainfile().
const char* wmOperatorType::description
Definition at line 434 of file WM_types.h.
Referenced by ACTION_OT_clean(), ACTION_OT_clickselect(), ACTION_OT_copy(), ACTION_OT_delete(), ACTION_OT_duplicate(), ACTION_OT_extrapolation_type(), ACTION_OT_frame_jump(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_markers_make_local(), ACTION_OT_mirror(), ACTION_OT_new(), ACTION_OT_paste(), ACTION_OT_previewrange_set(), ACTION_OT_sample(), ACTION_OT_select_all_toggle(), ACTION_OT_select_border(), ACTION_OT_select_column(), ACTION_OT_select_leftright(), ACTION_OT_select_less(), ACTION_OT_select_linked(), ACTION_OT_select_more(), ACTION_OT_snap(), ACTION_OT_view_all(), ACTION_OT_view_selected(), ANIM_OT_change_frame(), ANIM_OT_channels_click(), ANIM_OT_channels_collapse(), ANIM_OT_channels_delete(), ANIM_OT_channels_editable_toggle(), ANIM_OT_channels_expand(), ANIM_OT_channels_fcurves_enable(), ANIM_OT_channels_move(), ANIM_OT_channels_rename(), ANIM_OT_channels_select_all_toggle(), ANIM_OT_channels_select_border(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), ANIM_OT_channels_setting_toggle(), ANIM_OT_channels_visibility_set(), ANIM_OT_channels_visibility_toggle(), ANIM_OT_copy_driver_button(), ANIM_OT_driver_button_add(), ANIM_OT_driver_button_remove(), ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_delete_v3d(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_add(), ANIM_OT_keying_set_path_add(), ANIM_OT_keying_set_path_remove(), ANIM_OT_keying_set_remove(), ANIM_OT_paste_driver_button(), ANIM_OT_previewrange_clear(), ANIM_OT_previewrange_set(), ARMATURE_OT_align(), ARMATURE_OT_armature_layers(), ARMATURE_OT_autoside_names(), ARMATURE_OT_bone_layers(), ARMATURE_OT_bone_primitive_add(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_click_extrude(), ARMATURE_OT_delete(), ARMATURE_OT_duplicate(), ARMATURE_OT_extrude(), ARMATURE_OT_fill(), ARMATURE_OT_flip_names(), ARMATURE_OT_hide(), ARMATURE_OT_layers_show_all(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), ARMATURE_OT_parent_set(), ARMATURE_OT_reveal(), ARMATURE_OT_select_all(), ARMATURE_OT_select_hierarchy(), ARMATURE_OT_select_inverse(), ARMATURE_OT_select_linked(), ARMATURE_OT_separate(), ARMATURE_OT_subdivide(), ARMATURE_OT_switch_direction(), BOID_OT_rule_add(), BOID_OT_rule_move_down(), BOID_OT_rule_move_up(), BOID_OT_state_add(), BOID_OT_state_move_down(), BOID_OT_state_move_up(), BPy_BoolProperty(), BPy_BoolVectorProperty(), BPy_CollectionProperty(), BPy_EnumProperty(), BPy_FloatProperty(), BPy_FloatVectorProperty(), BPy_IntProperty(), BPy_IntVectorProperty(), BPy_PointerProperty(), BPy_StringProperty(), BRUSH_OT_add(), BRUSH_OT_curve_preset(), BRUSH_OT_reset(), BRUSH_OT_scale_size(), BRUSH_OT_uv_sculpt_tool_set(), BUTTONS_OT_directory_browse(), BUTTONS_OT_file_browse(), BUTTONS_OT_toolbox(), CLIP_OT_add_marker(), CLIP_OT_change_frame(), CLIP_OT_clean_tracks(), CLIP_OT_clear_solution(), CLIP_OT_clear_track_path(), CLIP_OT_copy_tracks(), CLIP_OT_delete_marker(), CLIP_OT_delete_track(), CLIP_OT_detect_features(), CLIP_OT_disable_markers(), CLIP_OT_frame_jump(), CLIP_OT_graph_center_current_frame(), CLIP_OT_graph_delete_curve(), CLIP_OT_graph_delete_knot(), CLIP_OT_graph_disable_markers(), CLIP_OT_graph_select(), CLIP_OT_graph_select_all_markers(), CLIP_OT_graph_select_border(), CLIP_OT_graph_view_all(), CLIP_OT_hide_tracks(), CLIP_OT_hide_tracks_clear(), CLIP_OT_join_tracks(), CLIP_OT_lock_tracks(), CLIP_OT_mode_set(), CLIP_OT_open(), CLIP_OT_paste_tracks(), CLIP_OT_properties(), CLIP_OT_rebuild_proxy(), CLIP_OT_reload(), CLIP_OT_select(), CLIP_OT_select_all(), CLIP_OT_select_border(), CLIP_OT_select_circle(), CLIP_OT_select_grouped(), CLIP_OT_set_axis(), CLIP_OT_set_center_principal(), CLIP_OT_set_origin(), CLIP_OT_set_plane(), CLIP_OT_set_scale(), CLIP_OT_set_solution_scale(), CLIP_OT_slide_marker(), CLIP_OT_solve_camera(), CLIP_OT_stabilize_2d_add(), CLIP_OT_stabilize_2d_remove(), CLIP_OT_stabilize_2d_select(), CLIP_OT_stabilize_2d_set_rotation(), CLIP_OT_tools(), CLIP_OT_track_copy_color(), CLIP_OT_track_markers(), CLIP_OT_tracking_object_new(), CLIP_OT_tracking_object_remove(), CONSOLE_OT_clear(), CONSOLE_OT_copy(), CONSOLE_OT_delete(), CONSOLE_OT_history_append(), CONSOLE_OT_history_cycle(), CONSOLE_OT_insert(), CONSOLE_OT_move(), CONSOLE_OT_paste(), CONSOLE_OT_scrollback_append(), CONSOLE_OT_select_set(), CONSTRAINT_OT_childof_clear_inverse(), CONSTRAINT_OT_childof_set_inverse(), CONSTRAINT_OT_delete(), CONSTRAINT_OT_limitdistance_reset(), CONSTRAINT_OT_move_down(), CONSTRAINT_OT_move_up(), CONSTRAINT_OT_objectsolver_clear_inverse(), CONSTRAINT_OT_objectsolver_set_inverse(), CONSTRAINT_OT_stretchto_reset(), CURVE_OT_cyclic_toggle(), CURVE_OT_delete(), CURVE_OT_duplicate(), CURVE_OT_extrude(), CURVE_OT_handle_type_set(), CURVE_OT_primitive_bezier_circle_add(), CURVE_OT_primitive_bezier_curve_add(), CURVE_OT_primitive_nurbs_circle_add(), CURVE_OT_primitive_nurbs_curve_add(), CURVE_OT_primitive_nurbs_path_add(), CURVE_OT_radius_set(), CURVE_OT_select_nth(), CURVE_OT_smooth(), CURVE_OT_smooth_radius(), CURVE_OT_spline_type_set(), CURVE_OT_spline_weight_set(), CURVE_OT_subdivide(), CURVE_OT_switch_direction(), DPAINT_OT_bake(), DPAINT_OT_output_toggle(), DPAINT_OT_surface_slot_add(), DPAINT_OT_surface_slot_remove(), DPAINT_OT_type_toggle(), ED_operatormacros_action(), ED_operatormacros_armature(), ED_operatormacros_clip(), ED_operatormacros_curve(), ED_operatormacros_graph(), ED_operatormacros_mesh(), ED_operatormacros_node(), ED_operatormacros_object(), ED_OT_redo(), ED_OT_undo(), ED_OT_undo_history(), ED_OT_undo_push(), FILE_OT_bookmark_add(), FILE_OT_bookmark_toggle(), FILE_OT_cancel(), FILE_OT_delete(), FILE_OT_delete_bookmark(), FILE_OT_directory(), FILE_OT_directory_new(), FILE_OT_execute(), FILE_OT_filenum(), FILE_OT_hidedot(), FILE_OT_highlight(), FILE_OT_next(), FILE_OT_parent(), FILE_OT_previous(), FILE_OT_refresh(), FILE_OT_rename(), FILE_OT_select(), FILE_OT_select_all_toggle(), FILE_OT_select_bookmark(), FILE_OT_select_border(), FILE_OT_smoothscroll(), FONT_OT_case_set(), FONT_OT_case_toggle(), FONT_OT_change_character(), FONT_OT_change_spacing(), FONT_OT_delete(), FONT_OT_file_paste(), FONT_OT_insert_lorem(), FONT_OT_line_break(), FONT_OT_move(), FONT_OT_move_select(), FONT_OT_style_set(), FONT_OT_style_toggle(), FONT_OT_text_copy(), FONT_OT_text_cut(), FONT_OT_text_insert(), FONT_OT_text_paste(), FONT_OT_textbox_add(), FONT_OT_textbox_remove(), FONT_OT_unlink(), GPENCIL_OT_active_frame_delete(), GPENCIL_OT_convert(), GPENCIL_OT_data_add(), GPENCIL_OT_data_unlink(), GPENCIL_OT_draw(), GPENCIL_OT_layer_add(), GRAPH_OT_bake(), GRAPH_OT_clean(), GRAPH_OT_click_insert(), GRAPH_OT_clickselect(), GRAPH_OT_copy(), GRAPH_OT_cursor_set(), GRAPH_OT_delete(), GRAPH_OT_duplicate(), GRAPH_OT_euler_filter(), GRAPH_OT_extrapolation_type(), GRAPH_OT_fmodifier_add(), GRAPH_OT_fmodifier_copy(), GRAPH_OT_fmodifier_paste(), GRAPH_OT_frame_jump(), GRAPH_OT_ghost_curves_clear(), GRAPH_OT_ghost_curves_create(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_paste(), GRAPH_OT_previewrange_set(), GRAPH_OT_properties(), GRAPH_OT_sample(), GRAPH_OT_select_all_toggle(), GRAPH_OT_select_border(), GRAPH_OT_select_column(), GRAPH_OT_select_leftright(), GRAPH_OT_select_less(), GRAPH_OT_select_linked(), GRAPH_OT_select_more(), GRAPH_OT_smooth(), GRAPH_OT_snap(), GRAPH_OT_sound_bake(), GRAPH_OT_view_all(), GRAPH_OT_view_selected(), GROUP_OT_create(), GROUP_OT_objects_add_active(), GROUP_OT_objects_remove(), GROUP_OT_objects_remove_active(), IMAGE_OT_new(), IMAGE_OT_open(), IMAGE_OT_pack(), IMAGE_OT_properties(), IMAGE_OT_scopes(), IMAGE_OT_unpack(), INFO_OT_report_copy(), INFO_OT_report_delete(), INFO_OT_report_replay(), INFO_OT_select_all_toggle(), INFO_OT_select_border(), INFO_OT_select_pick(), LATTICE_OT_make_regular(), LATTICE_OT_select_all(), LOGIC_OT_actuator_add(), LOGIC_OT_actuator_move(), LOGIC_OT_actuator_remove(), LOGIC_OT_controller_add(), LOGIC_OT_controller_move(), LOGIC_OT_controller_remove(), LOGIC_OT_links_cut(), LOGIC_OT_properties(), LOGIC_OT_sensor_add(), LOGIC_OT_sensor_move(), LOGIC_OT_sensor_remove(), LOGIC_OT_texface_convert(), macro_wrapper(), MARKER_OT_add(), MARKER_OT_delete(), MARKER_OT_duplicate(), MARKER_OT_make_links_scene(), MARKER_OT_move(), MARKER_OT_rename(), MARKER_OT_select(), MARKER_OT_select_all(), MARKER_OT_select_border(), MATERIAL_OT_copy(), MATERIAL_OT_new(), MATERIAL_OT_paste(), MBALL_OT_delete_metaelems(), MBALL_OT_duplicate_metaelems(), MBALL_OT_hide_metaelems(), MBALL_OT_reveal_metaelems(), MBALL_OT_select_all(), MBALL_OT_select_random_metaelems(), MESH_OT_bevel(), MESH_OT_blend_from_shape(), MESH_OT_bridge_edge_loops(), MESH_OT_colors_reverse(), MESH_OT_colors_rotate(), MESH_OT_delete(), MESH_OT_dissolve(), MESH_OT_dissolve_limited(), MESH_OT_drop_named_image(), MESH_OT_dupli_extrude_cursor(), MESH_OT_duplicate(), MESH_OT_edge_collapse(), MESH_OT_edge_collapse_loop(), MESH_OT_edge_face_add(), MESH_OT_edge_rotate(), MESH_OT_edgering_select(), MESH_OT_edges_select_sharp(), MESH_OT_extrude_edges_indiv(), MESH_OT_extrude_faces_indiv(), MESH_OT_extrude_region(), MESH_OT_extrude_repeat(), MESH_OT_extrude_verts_indiv(), MESH_OT_faces_select_linked_flat(), MESH_OT_faces_shade_flat(), MESH_OT_faces_shade_smooth(), MESH_OT_fill(), MESH_OT_flip_normals(), MESH_OT_hide(), MESH_OT_inset(), MESH_OT_knife_cut(), MESH_OT_knife_tool(), MESH_OT_loop_multi_select(), MESH_OT_loop_select(), MESH_OT_loop_to_region(), MESH_OT_loopcut(), MESH_OT_mark_seam(), MESH_OT_mark_sharp(), MESH_OT_merge(), MESH_OT_navmesh_clear(), MESH_OT_navmesh_face_add(), MESH_OT_navmesh_face_copy(), MESH_OT_navmesh_make(), MESH_OT_navmesh_reset(), MESH_OT_noise(), MESH_OT_normals_make_consistent(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cube_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_monkey_add(), MESH_OT_primitive_plane_add(), MESH_OT_primitive_uv_sphere_add(), MESH_OT_quads_convert_to_tris(), MESH_OT_region_to_loop(), MESH_OT_remove_doubles(), MESH_OT_reveal(), MESH_OT_rip(), MESH_OT_screw(), MESH_OT_select_all(), MESH_OT_select_axis(), MESH_OT_select_by_number_vertices(), MESH_OT_select_interior_faces(), MESH_OT_select_less(), MESH_OT_select_linked(), MESH_OT_select_linked_pick(), MESH_OT_select_loose_verts(), MESH_OT_select_mirror(), MESH_OT_select_more(), MESH_OT_select_next_loop(), MESH_OT_select_non_manifold(), MESH_OT_select_nth(), MESH_OT_select_random(), MESH_OT_select_shortest_path(), MESH_OT_select_similar(), MESH_OT_select_vertex_path(), MESH_OT_separate(), MESH_OT_shape_propagate_to_all(), MESH_OT_solidify(), MESH_OT_sort_faces(), MESH_OT_spin(), MESH_OT_split(), MESH_OT_sticky_add(), MESH_OT_sticky_remove(), MESH_OT_subdivide(), MESH_OT_tris_convert_to_quads(), MESH_OT_uv_texture_add(), MESH_OT_uv_texture_remove(), MESH_OT_uvs_reverse(), MESH_OT_uvs_rotate(), MESH_OT_vert_connect(), MESH_OT_vert_slide(), MESH_OT_vertex_color_add(), MESH_OT_vertex_color_remove(), MESH_OT_vertices_randomize(), MESH_OT_vertices_smooth(), MESH_OT_vertices_sort(), NLA_OT_action_sync_length(), NLA_OT_actionclip_add(), NLA_OT_apply_scale(), NLA_OT_bake(), NLA_OT_channels_click(), NLA_OT_clear_scale(), NLA_OT_click_select(), NLA_OT_delete(), NLA_OT_delete_tracks(), NLA_OT_duplicate(), NLA_OT_fmodifier_add(), NLA_OT_fmodifier_copy(), NLA_OT_fmodifier_paste(), NLA_OT_meta_add(), NLA_OT_meta_remove(), NLA_OT_move_down(), NLA_OT_move_up(), NLA_OT_mute_toggle(), NLA_OT_properties(), NLA_OT_select_all_toggle(), NLA_OT_select_border(), NLA_OT_select_leftright(), NLA_OT_snap(), NLA_OT_soundclip_add(), NLA_OT_split(), NLA_OT_swap(), NLA_OT_tracks_add(), NLA_OT_transition_add(), NLA_OT_tweakmode_enter(), NLA_OT_tweakmode_exit(), NLA_OT_view_all(), NLA_OT_view_selected(), NODE_OT_add_file(), NODE_OT_backimage_move(), NODE_OT_delete(), NODE_OT_delete_reconnect(), NODE_OT_duplicate(), NODE_OT_group_edit(), NODE_OT_group_make(), NODE_OT_group_socket_add(), NODE_OT_group_socket_move_down(), NODE_OT_group_socket_move_up(), NODE_OT_group_socket_remove(), NODE_OT_group_ungroup(), NODE_OT_hide_socket_toggle(), NODE_OT_hide_toggle(), NODE_OT_link_make(), NODE_OT_link_viewer(), NODE_OT_mute_toggle(), NODE_OT_options_toggle(), NODE_OT_output_file_add_socket(), NODE_OT_output_file_remove_active_socket(), NODE_OT_preview_toggle(), NODE_OT_properties(), NODE_OT_select(), NODE_OT_select_all(), NODE_OT_select_border(), NODE_OT_select_linked_from(), NODE_OT_select_linked_to(), NODE_OT_select_same_type(), NODE_OT_select_same_type_next(), NODE_OT_select_same_type_prev(), NODE_OT_show_cyclic_dependencies(), NODE_OT_view_all(), OBJECT_OT_add(), OBJECT_OT_add_named(), OBJECT_OT_armature_add(), OBJECT_OT_bake_image(), OBJECT_OT_camera_add(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_constraints_clear(), OBJECT_OT_constraints_copy(), OBJECT_OT_convert(), OBJECT_OT_delete(), OBJECT_OT_drop_named_material(), OBJECT_OT_duplicate(), OBJECT_OT_duplicates_make_real(), OBJECT_OT_editmode_toggle(), OBJECT_OT_effector_add(), OBJECT_OT_explode_refresh(), OBJECT_OT_forcefield_toggle(), OBJECT_OT_game_physics_copy(), OBJECT_OT_game_property_new(), OBJECT_OT_game_property_remove(), OBJECT_OT_group_add(), OBJECT_OT_group_instance_add(), OBJECT_OT_group_link(), OBJECT_OT_hide_render_clear(), OBJECT_OT_hide_render_set(), OBJECT_OT_hide_view_clear(), OBJECT_OT_hide_view_set(), OBJECT_OT_hook_add_newobj(), OBJECT_OT_hook_add_selobj(), OBJECT_OT_hook_assign(), OBJECT_OT_hook_recenter(), OBJECT_OT_hook_remove(), OBJECT_OT_hook_reset(), OBJECT_OT_hook_select(), OBJECT_OT_join(), OBJECT_OT_join_shapes(), OBJECT_OT_lamp_add(), OBJECT_OT_location_clear(), OBJECT_OT_logic_bricks_copy(), OBJECT_OT_make_links_data(), OBJECT_OT_make_links_scene(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_material_slot_add(), OBJECT_OT_material_slot_assign(), OBJECT_OT_material_slot_copy(), OBJECT_OT_material_slot_deselect(), OBJECT_OT_material_slot_remove(), OBJECT_OT_material_slot_select(), OBJECT_OT_meshdeform_bind(), OBJECT_OT_metaball_add(), OBJECT_OT_mode_set(), OBJECT_OT_modifier_add(), OBJECT_OT_modifier_apply(), OBJECT_OT_modifier_convert(), OBJECT_OT_modifier_copy(), OBJECT_OT_modifier_move_down(), OBJECT_OT_modifier_move_up(), OBJECT_OT_modifier_remove(), OBJECT_OT_move_to_layer(), OBJECT_OT_multires_base_apply(), OBJECT_OT_multires_external_pack(), OBJECT_OT_multires_external_save(), OBJECT_OT_multires_higher_levels_delete(), OBJECT_OT_multires_reshape(), OBJECT_OT_multires_subdivide(), OBJECT_OT_ocean_bake(), OBJECT_OT_origin_clear(), OBJECT_OT_origin_set(), OBJECT_OT_parent_clear(), OBJECT_OT_parent_no_inverse_set(), OBJECT_OT_parent_set(), OBJECT_OT_particle_system_add(), OBJECT_OT_particle_system_remove(), OBJECT_OT_paths_calculate(), OBJECT_OT_paths_clear(), OBJECT_OT_posemode_toggle(), OBJECT_OT_proxy_make(), OBJECT_OT_rotation_clear(), OBJECT_OT_scale_clear(), OBJECT_OT_select_all(), OBJECT_OT_select_by_layer(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_select_mirror(), OBJECT_OT_select_random(), OBJECT_OT_select_same_group(), OBJECT_OT_shade_flat(), OBJECT_OT_shade_smooth(), OBJECT_OT_shape_key_add(), OBJECT_OT_shape_key_clear(), OBJECT_OT_shape_key_remove(), OBJECT_OT_shape_key_retime(), OBJECT_OT_slow_parent_clear(), OBJECT_OT_slow_parent_set(), OBJECT_OT_speaker_add(), OBJECT_OT_text_add(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), OBJECT_OT_transform_apply(), OBJECT_OT_vertex_group_blend(), OBJECT_OT_vertex_group_clean(), OBJECT_OT_vertex_group_copy_to_linked(), OBJECT_OT_vertex_group_copy_to_selected(), OBJECT_OT_vertex_group_fix(), OBJECT_OT_vertex_group_mirror(), OBJECT_OT_vertex_group_set_active(), OBJECT_OT_vertex_group_sort(), OBJECT_OT_vertex_parent_set(), OBJECT_OT_visual_transform_apply(), OUTLINER_OT_action_set(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_drivers_add_selected(), OUTLINER_OT_drivers_delete_selected(), OUTLINER_OT_expanded_toggle(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_item_activate(), OUTLINER_OT_item_openclose(), OUTLINER_OT_item_rename(), OUTLINER_OT_keyingset_add_selected(), OUTLINER_OT_keyingset_remove_selected(), OUTLINER_OT_object_operation(), OUTLINER_OT_operation(), OUTLINER_OT_parent_clear(), OUTLINER_OT_parent_drop(), OUTLINER_OT_renderability_toggle(), OUTLINER_OT_scroll_page(), OUTLINER_OT_select_border(), OUTLINER_OT_selectability_toggle(), OUTLINER_OT_selected_toggle(), OUTLINER_OT_show_active(), OUTLINER_OT_show_hierarchy(), OUTLINER_OT_show_one_level(), OUTLINER_OT_visibility_toggle(), PAINT_OT_brush_select(), PAINT_OT_face_select_all(), PAINT_OT_face_select_hide(), PAINT_OT_face_select_inverse(), PAINT_OT_face_select_linked(), PAINT_OT_face_select_linked_pick(), PAINT_OT_face_select_reveal(), PAINT_OT_image_from_view(), PAINT_OT_project_image(), PAINT_OT_vert_select_all(), PAINT_OT_vert_select_inverse(), PARTICLE_OT_connect_hair(), PARTICLE_OT_disconnect_hair(), PARTICLE_OT_dupliob_copy(), PARTICLE_OT_dupliob_move_down(), PARTICLE_OT_dupliob_move_up(), PARTICLE_OT_dupliob_remove(), PARTICLE_OT_new(), PARTICLE_OT_new_target(), PARTICLE_OT_target_move_down(), PARTICLE_OT_target_move_up(), PARTICLE_OT_target_remove(), POSE_OT_armature_apply(), POSE_OT_armature_layers(), POSE_OT_autoside_names(), POSE_OT_bone_layers(), POSE_OT_breakdown(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_constraints_clear(), POSE_OT_constraints_copy(), POSE_OT_copy(), POSE_OT_flip_names(), POSE_OT_group_add(), POSE_OT_group_assign(), POSE_OT_group_deselect(), POSE_OT_group_move(), POSE_OT_group_remove(), POSE_OT_group_select(), POSE_OT_group_sort(), POSE_OT_group_unassign(), POSE_OT_hide(), POSE_OT_ik_add(), POSE_OT_ik_clear(), POSE_OT_loc_clear(), POSE_OT_paste(), POSE_OT_paths_calculate(), POSE_OT_paths_clear(), POSE_OT_propagate(), POSE_OT_push(), POSE_OT_quaternions_flip(), POSE_OT_relax(), POSE_OT_reveal(), POSE_OT_rot_clear(), POSE_OT_rotation_mode_set(), POSE_OT_scale_clear(), POSE_OT_select_all(), POSE_OT_select_constraint_target(), POSE_OT_select_flip_active(), POSE_OT_select_grouped(), POSE_OT_select_hierarchy(), POSE_OT_select_linked(), POSE_OT_select_parent(), POSE_OT_transforms_clear(), POSE_OT_user_transforms_clear(), POSE_OT_visual_transform_apply(), POSELIB_OT_action_sanitise(), POSELIB_OT_apply_pose(), POSELIB_OT_browse_interactive(), POSELIB_OT_new(), POSELIB_OT_pose_add(), POSELIB_OT_pose_remove(), POSELIB_OT_pose_rename(), POSELIB_OT_unlink(), PTCACHE_OT_add(), PTCACHE_OT_bake(), PTCACHE_OT_bake_all(), PTCACHE_OT_bake_from_cache(), PTCACHE_OT_free_bake(), PTCACHE_OT_remove(), RENDER_OT_opengl(), RENDER_OT_render(), RENDER_OT_view_cancel(), RENDER_OT_view_show(), SCENE_OT_delete(), SCENE_OT_new(), SCENE_OT_render_layer_add(), SCENE_OT_render_layer_remove(), SCREEN_OT_actionzone(), SCREEN_OT_animation_cancel(), SCREEN_OT_animation_play(), SCREEN_OT_animation_step(), SCREEN_OT_area_dupli(), SCREEN_OT_area_join(), SCREEN_OT_area_move(), SCREEN_OT_area_options(), SCREEN_OT_area_split(), SCREEN_OT_area_swap(), SCREEN_OT_back_to_previous(), SCREEN_OT_delete(), SCREEN_OT_frame_jump(), SCREEN_OT_header_toolbox(), SCREEN_OT_keyframe_jump(), SCREEN_OT_new(), SCREEN_OT_redo_last(), SCREEN_OT_region_quadview(), SCREEN_OT_region_scale(), SCREEN_OT_repeat_history(), SCREEN_OT_repeat_last(), SCREEN_OT_screen_full_area(), SCREEN_OT_screen_set(), SCREEN_OT_spacedata_cleanup(), SCREEN_OT_userpref_show(), SCRIPT_OT_python_file_run(), SCRIPT_OT_reload(), SCULPT_OT_uv_sculpt_stroke(), SEQUENCER_OT_change_effect_input(), SEQUENCER_OT_change_effect_type(), SEQUENCER_OT_change_path(), SEQUENCER_OT_copy(), SEQUENCER_OT_cut(), SEQUENCER_OT_delete(), SEQUENCER_OT_duplicate(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_images_separate(), SEQUENCER_OT_lock(), SEQUENCER_OT_meta_make(), SEQUENCER_OT_meta_separate(), SEQUENCER_OT_meta_toggle(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_mute(), SEQUENCER_OT_next_edit(), SEQUENCER_OT_offset_clear(), SEQUENCER_OT_paste(), SEQUENCER_OT_previous_edit(), SEQUENCER_OT_properties(), SEQUENCER_OT_reassign_inputs(), SEQUENCER_OT_rebuild_proxy(), SEQUENCER_OT_refresh_all(), SEQUENCER_OT_reload(), SEQUENCER_OT_rendersize(), SEQUENCER_OT_scene_strip_add(), SEQUENCER_OT_select(), SEQUENCER_OT_select_active_side(), SEQUENCER_OT_select_all(), SEQUENCER_OT_select_border(), SEQUENCER_OT_select_grouped(), SEQUENCER_OT_select_handles(), SEQUENCER_OT_select_inverse(), SEQUENCER_OT_select_less(), SEQUENCER_OT_select_linked(), SEQUENCER_OT_select_linked_pick(), SEQUENCER_OT_select_more(), SEQUENCER_OT_snap(), SEQUENCER_OT_sound_strip_add(), SEQUENCER_OT_swap(), SEQUENCER_OT_swap_data(), SEQUENCER_OT_swap_inputs(), SEQUENCER_OT_unlock(), SEQUENCER_OT_unmute(), SEQUENCER_OT_view_all(), SEQUENCER_OT_view_all_preview(), SEQUENCER_OT_view_ghost_border(), SEQUENCER_OT_view_selected(), SEQUENCER_OT_view_toggle(), SEQUENCER_OT_view_zoom_ratio(), SOUND_OT_bake_animation(), SOUND_OT_mixdown(), SOUND_OT_open(), SOUND_OT_open_mono(), SOUND_OT_pack(), SOUND_OT_unpack(), SOUND_OT_update_animation_flags(), SURFACE_OT_primitive_nurbs_surface_circle_add(), SURFACE_OT_primitive_nurbs_surface_curve_add(), SURFACE_OT_primitive_nurbs_surface_cylinder_add(), SURFACE_OT_primitive_nurbs_surface_sphere_add(), SURFACE_OT_primitive_nurbs_surface_surface_add(), SURFACE_OT_primitive_nurbs_surface_torus_add(), TEXT_OT_comment(), TEXT_OT_convert_whitespace(), TEXT_OT_copy(), TEXT_OT_cursor_set(), TEXT_OT_cut(), TEXT_OT_delete(), TEXT_OT_find(), TEXT_OT_find_set_selected(), TEXT_OT_indent(), TEXT_OT_insert(), TEXT_OT_jump(), TEXT_OT_line_break(), TEXT_OT_line_number(), TEXT_OT_make_internal(), TEXT_OT_mark_all(), TEXT_OT_markers_clear(), TEXT_OT_move(), TEXT_OT_move_select(), TEXT_OT_new(), TEXT_OT_next_marker(), TEXT_OT_open(), TEXT_OT_overwrite_toggle(), TEXT_OT_paste(), TEXT_OT_previous_marker(), TEXT_OT_properties(), TEXT_OT_refresh_pyconstraints(), TEXT_OT_reload(), TEXT_OT_replace(), TEXT_OT_replace_set_selected(), TEXT_OT_resolve_conflict(), TEXT_OT_run_script(), TEXT_OT_save(), TEXT_OT_save_as(), TEXT_OT_scroll(), TEXT_OT_scroll_bar(), TEXT_OT_select_all(), TEXT_OT_select_line(), TEXT_OT_select_word(), TEXT_OT_selection_set(), TEXT_OT_to_3d_object(), TEXT_OT_uncomment(), TEXT_OT_unindent(), TEXT_OT_unlink(), TEXTURE_OT_envmap_clear(), TEXTURE_OT_envmap_clear_all(), TEXTURE_OT_envmap_save(), TEXTURE_OT_new(), TEXTURE_OT_slot_copy(), TEXTURE_OT_slot_move(), TEXTURE_OT_slot_paste(), TIME_OT_end_frame_set(), TIME_OT_start_frame_set(), TIME_OT_view_all(), TRANSFORM_OT_create_orientation(), TRANSFORM_OT_delete_orientation(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_select_orientation(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_snap_type(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), TRANSFORM_OT_warp(), ui_but_menu(), ui_def_but_operator_text(), UI_OT_copy_data_path_button(), UI_OT_copy_to_selected_button(), UI_OT_eyedropper(), UI_OT_reports_to_textblock(), UI_OT_reset_default_button(), UI_OT_reset_default_theme(), UV_OT_align(), UV_OT_circle_select(), UV_OT_cursor_set(), UV_OT_hide(), UV_OT_mark_seam(), UV_OT_minimize_stretch(), UV_OT_pin(), UV_OT_reveal(), UV_OT_seams_from_islands(), UV_OT_select(), UV_OT_select_all(), UV_OT_select_border(), UV_OT_select_linked(), UV_OT_select_linked_pick(), UV_OT_select_loop(), UV_OT_select_pinned(), UV_OT_snap_cursor(), UV_OT_snap_selected(), UV_OT_stitch(), UV_OT_tile_set(), UV_OT_unlink_selected(), UV_OT_unwrap(), UV_OT_weld(), VIEW2D_OT_pan(), VIEW2D_OT_reset(), VIEW2D_OT_scroll_down(), VIEW2D_OT_scroll_left(), VIEW2D_OT_scroll_right(), VIEW2D_OT_scroll_up(), VIEW2D_OT_scroller_activate(), VIEW2D_OT_zoom(), VIEW2D_OT_zoom_border(), VIEW2D_OT_zoom_in(), VIEW2D_OT_zoom_out(), VIEW3D_OT_background_image_add(), VIEW3D_OT_background_image_remove(), VIEW3D_OT_camera_to_view(), VIEW3D_OT_camera_to_view_selected(), VIEW3D_OT_clip_border(), VIEW3D_OT_cursor3d(), VIEW3D_OT_dolly(), VIEW3D_OT_enable_manipulator(), VIEW3D_OT_fly(), VIEW3D_OT_game_start(), VIEW3D_OT_layers(), VIEW3D_OT_localview(), VIEW3D_OT_manipulator(), VIEW3D_OT_move(), VIEW3D_OT_ndof_orbit(), VIEW3D_OT_ndof_pan(), VIEW3D_OT_object_as_camera(), VIEW3D_OT_properties(), VIEW3D_OT_render_border(), VIEW3D_OT_rotate(), VIEW3D_OT_select(), VIEW3D_OT_select_border(), VIEW3D_OT_select_circle(), VIEW3D_OT_select_lasso(), VIEW3D_OT_select_menu(), VIEW3D_OT_smoothview(), VIEW3D_OT_snap_cursor_to_active(), VIEW3D_OT_snap_cursor_to_center(), VIEW3D_OT_snap_cursor_to_grid(), VIEW3D_OT_snap_cursor_to_selected(), VIEW3D_OT_snap_selected_to_cursor(), VIEW3D_OT_snap_selected_to_grid(), VIEW3D_OT_toolshelf(), VIEW3D_OT_view_all(), VIEW3D_OT_view_center_camera(), VIEW3D_OT_view_center_cursor(), VIEW3D_OT_view_orbit(), VIEW3D_OT_view_pan(), VIEW3D_OT_view_persportho(), VIEW3D_OT_view_selected(), VIEW3D_OT_viewnumpad(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), VIEW3D_OT_zoom_camera_1_to_1(), WM_operatortype_append(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), WM_operatortype_append_ptr(), WM_operatortype_macro_define(), WM_OT_debug_menu(), WM_OT_dependency_relations(), WM_OT_link_append(), WM_OT_memory_statistics(), WM_OT_ndof_sensitivity_change(), WM_OT_open_mainfile(), WM_OT_quit_blender(), WM_OT_read_factory_settings(), WM_OT_read_homefile(), WM_OT_recover_auto_save(), WM_OT_recover_last_session(), WM_OT_redraw_timer(), WM_OT_save_as_mainfile(), WM_OT_save_homefile(), WM_OT_save_mainfile(), WM_OT_splash(), WM_OT_window_duplicate(), WM_OT_window_fullscreen_toggle(), and WORLD_OT_new().
int(* wmOperatorType::exec)(struct bContext *, struct wmOperator *)
Definition at line 440 of file WM_types.h.
Referenced by ACTION_OT_clean(), ACTION_OT_copy(), ACTION_OT_delete(), ACTION_OT_duplicate(), ACTION_OT_extrapolation_type(), ACTION_OT_frame_jump(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_markers_make_local(), ACTION_OT_mirror(), ACTION_OT_new(), ACTION_OT_paste(), ACTION_OT_previewrange_set(), ACTION_OT_sample(), ACTION_OT_select_all_toggle(), ACTION_OT_select_border(), ACTION_OT_select_column(), ACTION_OT_select_leftright(), ACTION_OT_select_less(), ACTION_OT_select_linked(), ACTION_OT_select_more(), ACTION_OT_snap(), ACTION_OT_view_all(), ACTION_OT_view_selected(), ANIM_OT_change_frame(), ANIM_OT_channels_collapse(), ANIM_OT_channels_delete(), ANIM_OT_channels_editable_toggle(), ANIM_OT_channels_expand(), ANIM_OT_channels_fcurves_enable(), ANIM_OT_channels_move(), ANIM_OT_channels_select_all_toggle(), ANIM_OT_channels_select_border(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), ANIM_OT_channels_setting_toggle(), ANIM_OT_channels_visibility_set(), ANIM_OT_channels_visibility_toggle(), ANIM_OT_copy_driver_button(), ANIM_OT_driver_button_add(), ANIM_OT_driver_button_remove(), ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_delete_button(), ANIM_OT_keyframe_delete_v3d(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_button(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_active_set(), ANIM_OT_keying_set_add(), ANIM_OT_keying_set_path_add(), ANIM_OT_keying_set_path_remove(), ANIM_OT_keying_set_remove(), ANIM_OT_keyingset_button_add(), ANIM_OT_keyingset_button_remove(), ANIM_OT_paste_driver_button(), ANIM_OT_previewrange_clear(), ANIM_OT_previewrange_set(), ARMATURE_OT_align(), ARMATURE_OT_armature_layers(), ARMATURE_OT_autoside_names(), ARMATURE_OT_bone_layers(), ARMATURE_OT_bone_primitive_add(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_click_extrude(), ARMATURE_OT_delete(), ARMATURE_OT_duplicate(), ARMATURE_OT_extrude(), ARMATURE_OT_fill(), ARMATURE_OT_flip_names(), ARMATURE_OT_hide(), ARMATURE_OT_layers_show_all(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), ARMATURE_OT_parent_set(), ARMATURE_OT_reveal(), ARMATURE_OT_select_all(), ARMATURE_OT_select_hierarchy(), ARMATURE_OT_select_inverse(), ARMATURE_OT_select_linked(), ARMATURE_OT_separate(), ARMATURE_OT_subdivide(), ARMATURE_OT_switch_direction(), BOID_OT_rule_add(), BOID_OT_rule_del(), BOID_OT_rule_move_down(), BOID_OT_rule_move_up(), BOID_OT_state_add(), BOID_OT_state_del(), BOID_OT_state_move_down(), BOID_OT_state_move_up(), border_apply(), BRUSH_OT_add(), BRUSH_OT_curve_preset(), BRUSH_OT_reset(), BRUSH_OT_scale_size(), BRUSH_OT_uv_sculpt_tool_set(), BUTTONS_OT_directory_browse(), BUTTONS_OT_file_browse(), CLIP_OT_add_marker(), CLIP_OT_change_frame(), CLIP_OT_clean_tracks(), CLIP_OT_clear_solution(), CLIP_OT_clear_track_path(), CLIP_OT_copy_tracks(), CLIP_OT_delete_marker(), CLIP_OT_delete_track(), CLIP_OT_detect_features(), CLIP_OT_disable_markers(), CLIP_OT_frame_jump(), CLIP_OT_graph_center_current_frame(), CLIP_OT_graph_delete_curve(), CLIP_OT_graph_delete_knot(), CLIP_OT_graph_disable_markers(), CLIP_OT_graph_select(), CLIP_OT_graph_select_all_markers(), CLIP_OT_graph_select_border(), CLIP_OT_graph_view_all(), CLIP_OT_hide_tracks(), CLIP_OT_hide_tracks_clear(), CLIP_OT_join_tracks(), CLIP_OT_lock_tracks(), CLIP_OT_mode_set(), CLIP_OT_open(), CLIP_OT_paste_tracks(), CLIP_OT_properties(), CLIP_OT_rebuild_proxy(), CLIP_OT_reload(), CLIP_OT_select(), CLIP_OT_select_all(), CLIP_OT_select_border(), CLIP_OT_select_circle(), CLIP_OT_select_grouped(), CLIP_OT_set_axis(), CLIP_OT_set_center_principal(), CLIP_OT_set_origin(), CLIP_OT_set_plane(), CLIP_OT_set_scale(), CLIP_OT_set_solution_scale(), CLIP_OT_solve_camera(), CLIP_OT_stabilize_2d_add(), CLIP_OT_stabilize_2d_remove(), CLIP_OT_stabilize_2d_select(), CLIP_OT_stabilize_2d_set_rotation(), CLIP_OT_tools(), CLIP_OT_track_copy_color(), CLIP_OT_track_markers(), CLIP_OT_tracking_object_new(), CLIP_OT_tracking_object_remove(), CLIP_OT_view_all(), CLIP_OT_view_pan(), CLIP_OT_view_selected(), CLIP_OT_view_zoom(), CLIP_OT_view_zoom_in(), CLIP_OT_view_zoom_out(), CLIP_OT_view_zoom_ratio(), CONSOLE_OT_clear(), CONSOLE_OT_copy(), CONSOLE_OT_delete(), CONSOLE_OT_history_append(), CONSOLE_OT_history_cycle(), CONSOLE_OT_insert(), CONSOLE_OT_move(), CONSOLE_OT_paste(), CONSOLE_OT_scrollback_append(), CONSTRAINT_OT_childof_clear_inverse(), CONSTRAINT_OT_childof_set_inverse(), CONSTRAINT_OT_delete(), CONSTRAINT_OT_limitdistance_reset(), CONSTRAINT_OT_move_down(), CONSTRAINT_OT_move_up(), CONSTRAINT_OT_objectsolver_clear_inverse(), CONSTRAINT_OT_objectsolver_set_inverse(), CONSTRAINT_OT_stretchto_reset(), CURVE_OT_cyclic_toggle(), CURVE_OT_de_select_first(), CURVE_OT_de_select_last(), CURVE_OT_delete(), CURVE_OT_duplicate(), CURVE_OT_extrude(), CURVE_OT_handle_type_set(), CURVE_OT_hide(), CURVE_OT_make_segment(), CURVE_OT_primitive_bezier_circle_add(), CURVE_OT_primitive_bezier_curve_add(), CURVE_OT_primitive_nurbs_circle_add(), CURVE_OT_primitive_nurbs_curve_add(), CURVE_OT_primitive_nurbs_path_add(), CURVE_OT_radius_set(), CURVE_OT_reveal(), CURVE_OT_select_all(), CURVE_OT_select_less(), CURVE_OT_select_linked(), CURVE_OT_select_more(), CURVE_OT_select_next(), CURVE_OT_select_nth(), CURVE_OT_select_previous(), CURVE_OT_select_random(), CURVE_OT_select_row(), CURVE_OT_separate(), CURVE_OT_shade_flat(), CURVE_OT_shade_smooth(), CURVE_OT_smooth(), CURVE_OT_smooth_radius(), CURVE_OT_spin(), CURVE_OT_spline_type_set(), CURVE_OT_spline_weight_set(), CURVE_OT_subdivide(), CURVE_OT_switch_direction(), CURVE_OT_tilt_clear(), CURVE_OT_vertex_add(), DPAINT_OT_bake(), DPAINT_OT_output_toggle(), DPAINT_OT_surface_slot_add(), DPAINT_OT_surface_slot_remove(), DPAINT_OT_type_toggle(), ed_markers_opwrap_invoke_custom(), ED_object_add_generic_invoke(), ED_OT_redo(), ED_OT_undo(), ED_OT_undo_history(), ED_OT_undo_push(), FILE_OT_bookmark_add(), FILE_OT_bookmark_toggle(), FILE_OT_cancel(), FILE_OT_delete(), FILE_OT_delete_bookmark(), FILE_OT_directory(), FILE_OT_directory_new(), FILE_OT_execute(), FILE_OT_filenum(), FILE_OT_find_missing_files(), FILE_OT_hidedot(), FILE_OT_make_paths_absolute(), FILE_OT_make_paths_relative(), FILE_OT_next(), FILE_OT_pack_all(), FILE_OT_parent(), FILE_OT_previous(), FILE_OT_refresh(), FILE_OT_rename(), FILE_OT_report_missing_files(), FILE_OT_select_all_toggle(), FILE_OT_select_bookmark(), FILE_OT_select_border(), FILE_OT_unpack_all(), FONT_OT_case_set(), FONT_OT_case_toggle(), FONT_OT_change_character(), FONT_OT_change_spacing(), FONT_OT_delete(), FONT_OT_file_paste(), FONT_OT_insert_lorem(), FONT_OT_line_break(), FONT_OT_move(), FONT_OT_move_select(), FONT_OT_open(), FONT_OT_style_set(), FONT_OT_style_toggle(), FONT_OT_text_copy(), FONT_OT_text_cut(), FONT_OT_text_insert(), FONT_OT_text_paste(), FONT_OT_textbox_add(), FONT_OT_textbox_remove(), FONT_OT_unlink(), gesture_circle_apply(), gesture_lasso_apply(), GPENCIL_OT_active_frame_delete(), GPENCIL_OT_convert(), GPENCIL_OT_data_add(), GPENCIL_OT_data_unlink(), GPENCIL_OT_draw(), GPENCIL_OT_layer_add(), GRAPH_OT_bake(), GRAPH_OT_clean(), GRAPH_OT_click_insert(), GRAPH_OT_copy(), GRAPH_OT_cursor_set(), GRAPH_OT_delete(), GRAPH_OT_duplicate(), GRAPH_OT_euler_filter(), GRAPH_OT_extrapolation_type(), GRAPH_OT_fmodifier_add(), GRAPH_OT_fmodifier_copy(), GRAPH_OT_fmodifier_paste(), GRAPH_OT_frame_jump(), GRAPH_OT_ghost_curves_clear(), GRAPH_OT_ghost_curves_create(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_paste(), GRAPH_OT_previewrange_set(), GRAPH_OT_properties(), GRAPH_OT_sample(), GRAPH_OT_select_all_toggle(), GRAPH_OT_select_border(), GRAPH_OT_select_column(), GRAPH_OT_select_leftright(), GRAPH_OT_select_less(), GRAPH_OT_select_linked(), GRAPH_OT_select_more(), GRAPH_OT_smooth(), GRAPH_OT_snap(), GRAPH_OT_sound_bake(), GRAPH_OT_view_all(), GRAPH_OT_view_selected(), GROUP_OT_create(), GROUP_OT_objects_add_active(), GROUP_OT_objects_remove(), GROUP_OT_objects_remove_active(), hide_show_invoke(), IMAGE_OT_cycle_render_slot(), IMAGE_OT_invert(), IMAGE_OT_new(), IMAGE_OT_open(), IMAGE_OT_pack(), IMAGE_OT_properties(), IMAGE_OT_record_composite(), IMAGE_OT_reload(), IMAGE_OT_replace(), IMAGE_OT_sample_line(), IMAGE_OT_save(), IMAGE_OT_save_as(), IMAGE_OT_save_sequence(), IMAGE_OT_scopes(), IMAGE_OT_unpack(), IMAGE_OT_view_all(), IMAGE_OT_view_pan(), IMAGE_OT_view_selected(), IMAGE_OT_view_zoom(), IMAGE_OT_view_zoom_in(), IMAGE_OT_view_zoom_out(), IMAGE_OT_view_zoom_ratio(), INFO_OT_report_copy(), INFO_OT_report_delete(), INFO_OT_report_replay(), INFO_OT_select_all_toggle(), INFO_OT_select_border(), INFO_OT_select_pick(), insert_key_menu_invoke(), LATTICE_OT_make_regular(), LATTICE_OT_select_all(), LOGIC_OT_actuator_add(), LOGIC_OT_actuator_move(), LOGIC_OT_actuator_remove(), LOGIC_OT_controller_add(), LOGIC_OT_controller_move(), LOGIC_OT_controller_remove(), LOGIC_OT_links_cut(), LOGIC_OT_properties(), LOGIC_OT_sensor_add(), LOGIC_OT_sensor_move(), LOGIC_OT_sensor_remove(), LOGIC_OT_texface_convert(), MARKER_OT_add(), MARKER_OT_delete(), MARKER_OT_duplicate(), MARKER_OT_make_links_scene(), MARKER_OT_move(), MARKER_OT_rename(), MARKER_OT_select_all(), MARKER_OT_select_border(), MATERIAL_OT_copy(), MATERIAL_OT_new(), MATERIAL_OT_paste(), MBALL_OT_delete_metaelems(), MBALL_OT_duplicate_metaelems(), MBALL_OT_hide_metaelems(), MBALL_OT_reveal_metaelems(), MBALL_OT_select_all(), MBALL_OT_select_random_metaelems(), MESH_OT_beautify_fill(), MESH_OT_bevel(), MESH_OT_blend_from_shape(), MESH_OT_bridge_edge_loops(), MESH_OT_colors_reverse(), MESH_OT_colors_rotate(), MESH_OT_delete(), MESH_OT_dissolve(), MESH_OT_dissolve_limited(), MESH_OT_duplicate(), MESH_OT_edge_collapse(), MESH_OT_edge_collapse_loop(), MESH_OT_edge_face_add(), MESH_OT_edge_rotate(), MESH_OT_edge_split(), MESH_OT_edges_select_sharp(), MESH_OT_extrude_edges_indiv(), MESH_OT_extrude_faces_indiv(), MESH_OT_extrude_region(), MESH_OT_extrude_repeat(), MESH_OT_extrude_verts_indiv(), MESH_OT_faces_select_linked_flat(), MESH_OT_faces_shade_flat(), MESH_OT_faces_shade_smooth(), MESH_OT_fill(), MESH_OT_flip_normals(), MESH_OT_hide(), MESH_OT_inset(), MESH_OT_knife_cut(), MESH_OT_loop_multi_select(), MESH_OT_loop_to_region(), MESH_OT_mark_seam(), MESH_OT_mark_sharp(), MESH_OT_merge(), MESH_OT_navmesh_clear(), MESH_OT_navmesh_face_add(), MESH_OT_navmesh_face_copy(), MESH_OT_navmesh_make(), MESH_OT_navmesh_reset(), MESH_OT_noise(), MESH_OT_normals_make_consistent(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cube_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_monkey_add(), MESH_OT_primitive_plane_add(), MESH_OT_primitive_uv_sphere_add(), MESH_OT_quads_convert_to_tris(), MESH_OT_region_to_loop(), MESH_OT_remove_doubles(), MESH_OT_reveal(), MESH_OT_screw(), MESH_OT_select_all(), MESH_OT_select_axis(), MESH_OT_select_by_number_vertices(), MESH_OT_select_interior_faces(), MESH_OT_select_less(), MESH_OT_select_linked(), MESH_OT_select_loose_verts(), MESH_OT_select_mirror(), MESH_OT_select_more(), MESH_OT_select_next_loop(), MESH_OT_select_non_manifold(), MESH_OT_select_nth(), MESH_OT_select_random(), MESH_OT_select_similar(), MESH_OT_select_vertex_path(), MESH_OT_separate(), MESH_OT_shape_propagate_to_all(), MESH_OT_solidify(), MESH_OT_sort_faces(), MESH_OT_spin(), MESH_OT_split(), MESH_OT_sticky_add(), MESH_OT_sticky_remove(), MESH_OT_subdivide(), MESH_OT_tris_convert_to_quads(), MESH_OT_uv_texture_add(), MESH_OT_uv_texture_remove(), MESH_OT_uvs_reverse(), MESH_OT_uvs_rotate(), MESH_OT_vert_connect(), MESH_OT_vertex_color_add(), MESH_OT_vertex_color_remove(), MESH_OT_vertices_randomize(), MESH_OT_vertices_smooth(), MESH_OT_vertices_sort(), NLA_OT_action_sync_length(), NLA_OT_actionclip_add(), NLA_OT_apply_scale(), NLA_OT_bake(), NLA_OT_clear_scale(), NLA_OT_delete(), NLA_OT_delete_tracks(), NLA_OT_duplicate(), NLA_OT_fmodifier_add(), NLA_OT_fmodifier_copy(), NLA_OT_fmodifier_paste(), NLA_OT_meta_add(), NLA_OT_meta_remove(), NLA_OT_move_down(), NLA_OT_move_up(), NLA_OT_mute_toggle(), NLA_OT_properties(), NLA_OT_select_all_toggle(), NLA_OT_select_border(), NLA_OT_select_leftright(), NLA_OT_snap(), NLA_OT_soundclip_add(), NLA_OT_split(), NLA_OT_swap(), NLA_OT_tracks_add(), NLA_OT_transition_add(), NLA_OT_tweakmode_enter(), NLA_OT_tweakmode_exit(), NLA_OT_view_all(), NLA_OT_view_selected(), NODE_OT_add_file(), NODE_OT_backimage_zoom(), NODE_OT_delete(), NODE_OT_delete_reconnect(), NODE_OT_duplicate(), NODE_OT_group_edit(), NODE_OT_group_make(), NODE_OT_group_socket_add(), NODE_OT_group_socket_move_down(), NODE_OT_group_socket_move_up(), NODE_OT_group_socket_remove(), NODE_OT_group_ungroup(), NODE_OT_hide_socket_toggle(), NODE_OT_hide_toggle(), NODE_OT_link_make(), NODE_OT_link_viewer(), NODE_OT_links_cut(), NODE_OT_links_detach(), NODE_OT_mute_toggle(), NODE_OT_new_node_tree(), NODE_OT_options_toggle(), NODE_OT_output_file_add_socket(), NODE_OT_output_file_remove_active_socket(), NODE_OT_preview_toggle(), NODE_OT_properties(), NODE_OT_read_fullsamplelayers(), NODE_OT_read_renderlayers(), NODE_OT_render_changed(), NODE_OT_select_all(), NODE_OT_select_border(), NODE_OT_select_linked_from(), NODE_OT_select_linked_to(), NODE_OT_select_same_type(), NODE_OT_select_same_type_next(), NODE_OT_select_same_type_prev(), NODE_OT_show_cyclic_dependencies(), NODE_OT_view_all(), OBJECT_OT_add(), OBJECT_OT_add_named(), OBJECT_OT_armature_add(), OBJECT_OT_bake_image(), OBJECT_OT_camera_add(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_constraints_clear(), OBJECT_OT_constraints_copy(), OBJECT_OT_convert(), OBJECT_OT_delete(), OBJECT_OT_duplicate(), OBJECT_OT_duplicates_make_real(), OBJECT_OT_editmode_toggle(), OBJECT_OT_effector_add(), OBJECT_OT_explode_refresh(), OBJECT_OT_forcefield_toggle(), OBJECT_OT_game_physics_copy(), OBJECT_OT_game_property_clear(), OBJECT_OT_game_property_copy(), OBJECT_OT_game_property_new(), OBJECT_OT_game_property_remove(), OBJECT_OT_group_add(), OBJECT_OT_group_instance_add(), OBJECT_OT_group_link(), OBJECT_OT_group_remove(), OBJECT_OT_hide_render_clear(), OBJECT_OT_hide_render_set(), OBJECT_OT_hide_view_clear(), OBJECT_OT_hide_view_set(), OBJECT_OT_hook_add_newobj(), OBJECT_OT_hook_add_selobj(), OBJECT_OT_hook_assign(), OBJECT_OT_hook_recenter(), OBJECT_OT_hook_remove(), OBJECT_OT_hook_reset(), OBJECT_OT_hook_select(), OBJECT_OT_join(), OBJECT_OT_join_shapes(), OBJECT_OT_lamp_add(), OBJECT_OT_location_clear(), OBJECT_OT_logic_bricks_copy(), OBJECT_OT_make_links_data(), OBJECT_OT_make_links_scene(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_material_slot_add(), OBJECT_OT_material_slot_assign(), OBJECT_OT_material_slot_copy(), OBJECT_OT_material_slot_deselect(), OBJECT_OT_material_slot_remove(), OBJECT_OT_material_slot_select(), OBJECT_OT_meshdeform_bind(), OBJECT_OT_metaball_add(), OBJECT_OT_mode_set(), OBJECT_OT_modifier_add(), OBJECT_OT_modifier_apply(), OBJECT_OT_modifier_convert(), OBJECT_OT_modifier_copy(), OBJECT_OT_modifier_move_down(), OBJECT_OT_modifier_move_up(), OBJECT_OT_modifier_remove(), OBJECT_OT_move_to_layer(), OBJECT_OT_multires_base_apply(), OBJECT_OT_multires_external_pack(), OBJECT_OT_multires_external_save(), OBJECT_OT_multires_higher_levels_delete(), OBJECT_OT_multires_reshape(), OBJECT_OT_multires_subdivide(), OBJECT_OT_ocean_bake(), OBJECT_OT_origin_clear(), OBJECT_OT_origin_set(), OBJECT_OT_parent_clear(), OBJECT_OT_parent_no_inverse_set(), OBJECT_OT_parent_set(), OBJECT_OT_particle_system_add(), OBJECT_OT_particle_system_remove(), OBJECT_OT_paths_calculate(), OBJECT_OT_paths_clear(), OBJECT_OT_posemode_toggle(), OBJECT_OT_proxy_make(), OBJECT_OT_rotation_clear(), OBJECT_OT_scale_clear(), OBJECT_OT_select_all(), OBJECT_OT_select_by_layer(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_select_mirror(), OBJECT_OT_select_random(), OBJECT_OT_select_same_group(), OBJECT_OT_shade_flat(), OBJECT_OT_shade_smooth(), OBJECT_OT_shape_key_add(), OBJECT_OT_shape_key_clear(), OBJECT_OT_shape_key_mirror(), OBJECT_OT_shape_key_move(), OBJECT_OT_shape_key_remove(), OBJECT_OT_shape_key_retime(), OBJECT_OT_slow_parent_clear(), OBJECT_OT_slow_parent_set(), OBJECT_OT_speaker_add(), OBJECT_OT_text_add(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), OBJECT_OT_transform_apply(), OBJECT_OT_vertex_group_add(), OBJECT_OT_vertex_group_assign(), OBJECT_OT_vertex_group_blend(), OBJECT_OT_vertex_group_clean(), OBJECT_OT_vertex_group_copy(), OBJECT_OT_vertex_group_copy_to_linked(), OBJECT_OT_vertex_group_copy_to_selected(), OBJECT_OT_vertex_group_deselect(), OBJECT_OT_vertex_group_fix(), OBJECT_OT_vertex_group_invert(), OBJECT_OT_vertex_group_levels(), OBJECT_OT_vertex_group_lock(), OBJECT_OT_vertex_group_mirror(), OBJECT_OT_vertex_group_move(), OBJECT_OT_vertex_group_normalize(), OBJECT_OT_vertex_group_normalize_all(), OBJECT_OT_vertex_group_remove(), OBJECT_OT_vertex_group_remove_from(), OBJECT_OT_vertex_group_select(), OBJECT_OT_vertex_group_set_active(), OBJECT_OT_vertex_group_sort(), OBJECT_OT_vertex_parent_set(), OBJECT_OT_visual_transform_apply(), OUTLINER_OT_action_set(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_drivers_add_selected(), OUTLINER_OT_drivers_delete_selected(), OUTLINER_OT_expanded_toggle(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_keyingset_add_selected(), OUTLINER_OT_keyingset_remove_selected(), OUTLINER_OT_object_operation(), OUTLINER_OT_parent_drop(), OUTLINER_OT_renderability_toggle(), OUTLINER_OT_scroll_page(), OUTLINER_OT_select_border(), OUTLINER_OT_selectability_toggle(), OUTLINER_OT_selected_toggle(), OUTLINER_OT_show_active(), OUTLINER_OT_show_hierarchy(), OUTLINER_OT_show_one_level(), OUTLINER_OT_visibility_toggle(), PAINT_OT_brush_select(), PAINT_OT_clone_cursor_set(), PAINT_OT_face_select_all(), PAINT_OT_face_select_hide(), PAINT_OT_face_select_inverse(), PAINT_OT_face_select_linked(), PAINT_OT_face_select_reveal(), PAINT_OT_grab_clone(), PAINT_OT_hide_show(), PAINT_OT_image_from_view(), PAINT_OT_image_paint(), PAINT_OT_project_image(), PAINT_OT_sample_color(), PAINT_OT_texture_paint_toggle(), PAINT_OT_vert_select_all(), PAINT_OT_vert_select_inverse(), PAINT_OT_vertex_color_set(), PAINT_OT_vertex_paint_toggle(), PAINT_OT_weight_from_bones(), PAINT_OT_weight_paint_toggle(), PAINT_OT_weight_sample_group(), PAINT_OT_weight_set(), PARTICLE_OT_brush_edit(), PARTICLE_OT_connect_hair(), PARTICLE_OT_delete(), PARTICLE_OT_disconnect_hair(), PARTICLE_OT_dupliob_copy(), PARTICLE_OT_dupliob_move_down(), PARTICLE_OT_dupliob_move_up(), PARTICLE_OT_dupliob_remove(), PARTICLE_OT_edited_clear(), PARTICLE_OT_hide(), PARTICLE_OT_mirror(), PARTICLE_OT_new(), PARTICLE_OT_new_target(), PARTICLE_OT_particle_edit_toggle(), PARTICLE_OT_rekey(), PARTICLE_OT_remove_doubles(), PARTICLE_OT_reveal(), PARTICLE_OT_select_all(), PARTICLE_OT_select_less(), PARTICLE_OT_select_linked(), PARTICLE_OT_select_more(), PARTICLE_OT_select_roots(), PARTICLE_OT_select_tips(), PARTICLE_OT_subdivide(), PARTICLE_OT_target_move_down(), PARTICLE_OT_target_move_up(), PARTICLE_OT_target_remove(), PARTICLE_OT_weight_set(), pose_groups_menu_invoke(), POSE_OT_armature_apply(), POSE_OT_armature_layers(), POSE_OT_autoside_names(), POSE_OT_bone_layers(), POSE_OT_breakdown(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_constraints_clear(), POSE_OT_constraints_copy(), POSE_OT_copy(), POSE_OT_flip_names(), POSE_OT_group_add(), POSE_OT_group_assign(), POSE_OT_group_deselect(), POSE_OT_group_move(), POSE_OT_group_remove(), POSE_OT_group_select(), POSE_OT_group_sort(), POSE_OT_group_unassign(), POSE_OT_hide(), POSE_OT_ik_add(), POSE_OT_ik_clear(), POSE_OT_loc_clear(), POSE_OT_paste(), POSE_OT_paths_calculate(), POSE_OT_paths_clear(), POSE_OT_propagate(), POSE_OT_push(), POSE_OT_quaternions_flip(), POSE_OT_relax(), POSE_OT_reveal(), POSE_OT_rot_clear(), POSE_OT_rotation_mode_set(), POSE_OT_scale_clear(), POSE_OT_select_all(), POSE_OT_select_constraint_target(), POSE_OT_select_flip_active(), POSE_OT_select_grouped(), POSE_OT_select_hierarchy(), POSE_OT_select_linked(), POSE_OT_select_parent(), POSE_OT_transforms_clear(), POSE_OT_user_transforms_clear(), POSE_OT_visual_transform_apply(), POSELIB_OT_action_sanitise(), POSELIB_OT_apply_pose(), POSELIB_OT_browse_interactive(), POSELIB_OT_new(), POSELIB_OT_pose_add(), POSELIB_OT_pose_remove(), POSELIB_OT_pose_rename(), POSELIB_OT_unlink(), PTCACHE_OT_add(), PTCACHE_OT_bake(), PTCACHE_OT_bake_all(), PTCACHE_OT_bake_from_cache(), PTCACHE_OT_free_bake(), PTCACHE_OT_free_bake_all(), PTCACHE_OT_remove(), RENDER_OT_opengl(), RENDER_OT_render(), RENDER_OT_view_cancel(), SCENE_OT_delete(), SCENE_OT_new(), SCENE_OT_render_layer_add(), SCENE_OT_render_layer_remove(), SCREEN_OT_animation_cancel(), SCREEN_OT_animation_play(), SCREEN_OT_area_join(), SCREEN_OT_area_move(), SCREEN_OT_area_split(), SCREEN_OT_back_to_previous(), SCREEN_OT_delete(), SCREEN_OT_frame_jump(), SCREEN_OT_frame_offset(), SCREEN_OT_header_flip(), SCREEN_OT_keyframe_jump(), SCREEN_OT_new(), SCREEN_OT_region_flip(), SCREEN_OT_region_quadview(), SCREEN_OT_repeat_history(), SCREEN_OT_repeat_last(), SCREEN_OT_screen_full_area(), SCREEN_OT_screen_set(), SCREEN_OT_screencast(), SCREEN_OT_screenshot(), SCREEN_OT_spacedata_cleanup(), SCRIPT_OT_python_file_run(), SCRIPT_OT_reload(), SCULPT_OT_brush_stroke(), SCULPT_OT_sculptmode_toggle(), SCULPT_OT_set_persistent_base(), SEQUENCER_OT_change_effect_input(), SEQUENCER_OT_change_effect_type(), SEQUENCER_OT_change_path(), SEQUENCER_OT_copy(), SEQUENCER_OT_cut(), SEQUENCER_OT_delete(), SEQUENCER_OT_duplicate(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_images_separate(), SEQUENCER_OT_lock(), SEQUENCER_OT_meta_make(), SEQUENCER_OT_meta_separate(), SEQUENCER_OT_meta_toggle(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_mute(), SEQUENCER_OT_next_edit(), SEQUENCER_OT_offset_clear(), SEQUENCER_OT_paste(), SEQUENCER_OT_previous_edit(), SEQUENCER_OT_properties(), SEQUENCER_OT_reassign_inputs(), SEQUENCER_OT_rebuild_proxy(), SEQUENCER_OT_refresh_all(), SEQUENCER_OT_reload(), SEQUENCER_OT_rendersize(), SEQUENCER_OT_scene_strip_add(), SEQUENCER_OT_select_active_side(), SEQUENCER_OT_select_all(), SEQUENCER_OT_select_border(), SEQUENCER_OT_select_grouped(), SEQUENCER_OT_select_handles(), SEQUENCER_OT_select_inverse(), SEQUENCER_OT_select_less(), SEQUENCER_OT_select_linked(), SEQUENCER_OT_select_more(), SEQUENCER_OT_snap(), SEQUENCER_OT_sound_strip_add(), SEQUENCER_OT_swap(), SEQUENCER_OT_swap_data(), SEQUENCER_OT_swap_inputs(), SEQUENCER_OT_unlock(), SEQUENCER_OT_unmute(), SEQUENCER_OT_view_all(), SEQUENCER_OT_view_all_preview(), SEQUENCER_OT_view_ghost_border(), SEQUENCER_OT_view_selected(), SEQUENCER_OT_view_toggle(), SEQUENCER_OT_view_zoom_ratio(), SOUND_OT_bake_animation(), SOUND_OT_mixdown(), SOUND_OT_open(), SOUND_OT_open_mono(), SOUND_OT_pack(), SOUND_OT_unpack(), SOUND_OT_update_animation_flags(), straightline_apply(), SURFACE_OT_primitive_nurbs_surface_circle_add(), SURFACE_OT_primitive_nurbs_surface_curve_add(), SURFACE_OT_primitive_nurbs_surface_cylinder_add(), SURFACE_OT_primitive_nurbs_surface_sphere_add(), SURFACE_OT_primitive_nurbs_surface_surface_add(), SURFACE_OT_primitive_nurbs_surface_torus_add(), TEXT_OT_comment(), TEXT_OT_convert_whitespace(), TEXT_OT_copy(), TEXT_OT_cursor_set(), TEXT_OT_cut(), TEXT_OT_delete(), TEXT_OT_find(), TEXT_OT_find_set_selected(), TEXT_OT_indent(), TEXT_OT_insert(), TEXT_OT_jump(), TEXT_OT_line_break(), TEXT_OT_make_internal(), TEXT_OT_mark_all(), TEXT_OT_markers_clear(), TEXT_OT_move(), TEXT_OT_move_select(), TEXT_OT_new(), TEXT_OT_next_marker(), TEXT_OT_open(), TEXT_OT_overwrite_toggle(), TEXT_OT_paste(), TEXT_OT_previous_marker(), TEXT_OT_properties(), TEXT_OT_refresh_pyconstraints(), TEXT_OT_reload(), TEXT_OT_replace(), TEXT_OT_replace_set_selected(), TEXT_OT_resolve_conflict(), TEXT_OT_run_script(), TEXT_OT_save(), TEXT_OT_save_as(), TEXT_OT_scroll(), TEXT_OT_select_all(), TEXT_OT_select_line(), TEXT_OT_select_word(), TEXT_OT_to_3d_object(), TEXT_OT_uncomment(), TEXT_OT_unindent(), TEXT_OT_unlink(), TEXTURE_OT_envmap_clear(), TEXTURE_OT_envmap_clear_all(), TEXTURE_OT_envmap_save(), TEXTURE_OT_new(), TEXTURE_OT_slot_copy(), TEXTURE_OT_slot_move(), TEXTURE_OT_slot_paste(), TIME_OT_end_frame_set(), TIME_OT_start_frame_set(), TIME_OT_view_all(), TRANSFORM_OT_create_orientation(), TRANSFORM_OT_delete_orientation(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_select_orientation(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_snap_type(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), TRANSFORM_OT_warp(), UI_OT_copy_data_path_button(), UI_OT_copy_to_selected_button(), UI_OT_eyedropper(), UI_OT_reports_to_textblock(), UI_OT_reset_default_button(), UI_OT_reset_default_theme(), UV_OT_align(), UV_OT_average_islands_scale(), UV_OT_circle_select(), UV_OT_cube_project(), UV_OT_cursor_set(), UV_OT_cylinder_project(), UV_OT_from_view(), UV_OT_hide(), UV_OT_mark_seam(), UV_OT_minimize_stretch(), UV_OT_pack_islands(), UV_OT_pin(), UV_OT_reset(), UV_OT_reveal(), UV_OT_seams_from_islands(), UV_OT_select(), UV_OT_select_all(), UV_OT_select_border(), UV_OT_select_linked(), UV_OT_select_linked_pick(), UV_OT_select_loop(), UV_OT_select_pinned(), UV_OT_snap_cursor(), UV_OT_snap_selected(), UV_OT_sphere_project(), UV_OT_stitch(), UV_OT_tile_set(), UV_OT_unlink_selected(), UV_OT_unwrap(), UV_OT_weld(), VIEW2D_OT_pan(), VIEW2D_OT_reset(), VIEW2D_OT_scroll_down(), VIEW2D_OT_scroll_left(), VIEW2D_OT_scroll_right(), VIEW2D_OT_scroll_up(), VIEW2D_OT_zoom(), VIEW2D_OT_zoom_border(), VIEW3D_OT_background_image_add(), VIEW3D_OT_background_image_remove(), VIEW3D_OT_camera_to_view(), VIEW3D_OT_camera_to_view_selected(), VIEW3D_OT_clip_border(), VIEW3D_OT_dolly(), VIEW3D_OT_game_start(), VIEW3D_OT_layers(), VIEW3D_OT_localview(), VIEW3D_OT_object_as_camera(), VIEW3D_OT_properties(), VIEW3D_OT_render_border(), VIEW3D_OT_select_border(), VIEW3D_OT_select_circle(), VIEW3D_OT_select_lasso(), VIEW3D_OT_select_menu(), VIEW3D_OT_snap_cursor_to_active(), VIEW3D_OT_snap_cursor_to_center(), VIEW3D_OT_snap_cursor_to_grid(), VIEW3D_OT_snap_cursor_to_selected(), VIEW3D_OT_snap_selected_to_cursor(), VIEW3D_OT_snap_selected_to_grid(), VIEW3D_OT_toolshelf(), VIEW3D_OT_view_all(), VIEW3D_OT_view_center_camera(), VIEW3D_OT_view_center_cursor(), VIEW3D_OT_view_orbit(), VIEW3D_OT_view_pan(), VIEW3D_OT_view_persportho(), VIEW3D_OT_view_selected(), VIEW3D_OT_viewnumpad(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), VIEW3D_OT_zoom_camera_1_to_1(), wm_handler_fileselect_call(), wm_macro_exec(), wm_macro_invoke_internal(), WM_menu_invoke(), WM_operator_call_py(), wm_operator_exec(), wm_operator_exec_notest(), wm_operator_invoke(), WM_operator_repeat_check(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), WM_OT_call_menu(), WM_OT_debug_menu(), WM_OT_dependency_relations(), WM_OT_link_append(), WM_OT_memory_statistics(), WM_OT_ndof_sensitivity_change(), WM_OT_open_mainfile(), WM_OT_quit_blender(), WM_OT_read_factory_settings(), WM_OT_read_homefile(), WM_OT_recover_auto_save(), WM_OT_recover_last_session(), WM_OT_redraw_timer(), WM_OT_save_as_mainfile(), WM_OT_save_homefile(), WM_OT_save_mainfile(), WM_OT_search_menu(), WM_OT_window_duplicate(), WM_OT_window_fullscreen_toggle(), and WORLD_OT_new().
ExtensionRNA wmOperatorType::ext
Definition at line 485 of file WM_types.h.
Referenced by macro_wrapper(), operator_properties_init(), and operatortype_ghash_free_cb().
short wmOperatorType::flag
Definition at line 488 of file WM_types.h.
Referenced by ACTION_OT_clean(), ACTION_OT_clickselect(), ACTION_OT_copy(), ACTION_OT_delete(), ACTION_OT_duplicate(), ACTION_OT_extrapolation_type(), ACTION_OT_frame_jump(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_markers_make_local(), ACTION_OT_mirror(), ACTION_OT_new(), ACTION_OT_paste(), ACTION_OT_previewrange_set(), ACTION_OT_sample(), ACTION_OT_select_all_toggle(), ACTION_OT_select_border(), ACTION_OT_select_column(), ACTION_OT_select_leftright(), ACTION_OT_select_less(), ACTION_OT_select_linked(), ACTION_OT_select_more(), ACTION_OT_snap(), ACTION_OT_view_all(), ACTION_OT_view_selected(), ANIM_OT_change_frame(), ANIM_OT_channels_click(), ANIM_OT_channels_collapse(), ANIM_OT_channels_delete(), ANIM_OT_channels_editable_toggle(), ANIM_OT_channels_expand(), ANIM_OT_channels_fcurves_enable(), ANIM_OT_channels_move(), ANIM_OT_channels_select_all_toggle(), ANIM_OT_channels_select_border(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), ANIM_OT_channels_setting_toggle(), ANIM_OT_channels_visibility_set(), ANIM_OT_channels_visibility_toggle(), ANIM_OT_copy_driver_button(), ANIM_OT_driver_button_add(), ANIM_OT_driver_button_remove(), ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_delete_button(), ANIM_OT_keyframe_delete_v3d(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_button(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_active_set(), ANIM_OT_keyingset_button_add(), ANIM_OT_keyingset_button_remove(), ANIM_OT_paste_driver_button(), ANIM_OT_previewrange_clear(), ANIM_OT_previewrange_set(), ARMATURE_OT_align(), ARMATURE_OT_armature_layers(), ARMATURE_OT_autoside_names(), ARMATURE_OT_bone_layers(), ARMATURE_OT_bone_primitive_add(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_click_extrude(), ARMATURE_OT_delete(), ARMATURE_OT_duplicate(), ARMATURE_OT_extrude(), ARMATURE_OT_fill(), ARMATURE_OT_flip_names(), ARMATURE_OT_hide(), ARMATURE_OT_layers_show_all(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), ARMATURE_OT_parent_set(), ARMATURE_OT_reveal(), ARMATURE_OT_select_all(), ARMATURE_OT_select_hierarchy(), ARMATURE_OT_select_inverse(), ARMATURE_OT_select_linked(), ARMATURE_OT_separate(), ARMATURE_OT_subdivide(), ARMATURE_OT_switch_direction(), BOID_OT_rule_add(), BOID_OT_rule_del(), BOID_OT_rule_move_down(), BOID_OT_rule_move_up(), BOID_OT_state_add(), BOID_OT_state_del(), BOID_OT_state_move_down(), BOID_OT_state_move_up(), BRUSH_OT_add(), BRUSH_OT_reset(), BRUSH_OT_scale_size(), BRUSH_OT_uv_sculpt_tool_set(), CLIP_OT_add_marker(), CLIP_OT_change_frame(), CLIP_OT_clean_tracks(), CLIP_OT_clear_solution(), CLIP_OT_clear_track_path(), CLIP_OT_copy_tracks(), CLIP_OT_delete_marker(), CLIP_OT_delete_track(), CLIP_OT_detect_features(), CLIP_OT_disable_markers(), CLIP_OT_frame_jump(), CLIP_OT_graph_delete_curve(), CLIP_OT_graph_delete_knot(), CLIP_OT_graph_disable_markers(), CLIP_OT_graph_select(), CLIP_OT_graph_select_all_markers(), CLIP_OT_graph_select_border(), CLIP_OT_hide_tracks(), CLIP_OT_hide_tracks_clear(), CLIP_OT_join_tracks(), CLIP_OT_lock_tracks(), CLIP_OT_open(), CLIP_OT_paste_tracks(), CLIP_OT_rebuild_proxy(), CLIP_OT_select(), CLIP_OT_select_all(), CLIP_OT_select_border(), CLIP_OT_select_circle(), CLIP_OT_select_grouped(), CLIP_OT_set_axis(), CLIP_OT_set_center_principal(), CLIP_OT_set_origin(), CLIP_OT_set_plane(), CLIP_OT_set_scale(), CLIP_OT_set_solution_scale(), CLIP_OT_slide_marker(), CLIP_OT_solve_camera(), CLIP_OT_stabilize_2d_add(), CLIP_OT_stabilize_2d_remove(), CLIP_OT_stabilize_2d_select(), CLIP_OT_stabilize_2d_set_rotation(), CLIP_OT_track_copy_color(), CLIP_OT_track_markers(), CLIP_OT_tracking_object_new(), CLIP_OT_tracking_object_remove(), CLIP_OT_view_pan(), CLIP_OT_view_zoom(), clip_panel_operator_redo_operator(), CONSTRAINT_OT_childof_clear_inverse(), CONSTRAINT_OT_childof_set_inverse(), CONSTRAINT_OT_delete(), CONSTRAINT_OT_limitdistance_reset(), CONSTRAINT_OT_move_down(), CONSTRAINT_OT_move_up(), CONSTRAINT_OT_objectsolver_clear_inverse(), CONSTRAINT_OT_objectsolver_set_inverse(), CONSTRAINT_OT_stretchto_reset(), CURVE_OT_cyclic_toggle(), CURVE_OT_de_select_first(), CURVE_OT_de_select_last(), CURVE_OT_delete(), CURVE_OT_duplicate(), CURVE_OT_extrude(), CURVE_OT_handle_type_set(), CURVE_OT_hide(), CURVE_OT_make_segment(), CURVE_OT_primitive_bezier_circle_add(), CURVE_OT_primitive_bezier_curve_add(), CURVE_OT_primitive_nurbs_circle_add(), CURVE_OT_primitive_nurbs_curve_add(), CURVE_OT_primitive_nurbs_path_add(), CURVE_OT_radius_set(), CURVE_OT_reveal(), CURVE_OT_select_all(), CURVE_OT_select_less(), CURVE_OT_select_linked(), CURVE_OT_select_linked_pick(), CURVE_OT_select_more(), CURVE_OT_select_next(), CURVE_OT_select_nth(), CURVE_OT_select_previous(), CURVE_OT_select_random(), CURVE_OT_select_row(), CURVE_OT_separate(), CURVE_OT_shade_flat(), CURVE_OT_shade_smooth(), CURVE_OT_smooth(), CURVE_OT_smooth_radius(), CURVE_OT_spin(), CURVE_OT_spline_type_set(), CURVE_OT_spline_weight_set(), CURVE_OT_subdivide(), CURVE_OT_switch_direction(), CURVE_OT_tilt_clear(), CURVE_OT_vertex_add(), DPAINT_OT_output_toggle(), DPAINT_OT_surface_slot_add(), DPAINT_OT_surface_slot_remove(), DPAINT_OT_type_toggle(), ED_OT_undo_push(), FILE_OT_find_missing_files(), FILE_OT_make_paths_absolute(), FILE_OT_make_paths_relative(), FILE_OT_pack_all(), FILE_OT_report_missing_files(), FILE_OT_unpack_all(), FONT_OT_case_set(), FONT_OT_case_toggle(), FONT_OT_change_character(), FONT_OT_change_spacing(), FONT_OT_delete(), FONT_OT_file_paste(), FONT_OT_insert_lorem(), FONT_OT_line_break(), FONT_OT_move(), FONT_OT_move_select(), FONT_OT_open(), FONT_OT_style_set(), FONT_OT_style_toggle(), FONT_OT_text_cut(), FONT_OT_text_insert(), FONT_OT_text_paste(), FONT_OT_textbox_add(), FONT_OT_textbox_remove(), GPENCIL_OT_active_frame_delete(), GPENCIL_OT_convert(), GPENCIL_OT_data_add(), GPENCIL_OT_data_unlink(), GPENCIL_OT_draw(), GPENCIL_OT_layer_add(), GRAPH_OT_bake(), GRAPH_OT_clean(), GRAPH_OT_click_insert(), GRAPH_OT_copy(), GRAPH_OT_cursor_set(), GRAPH_OT_delete(), GRAPH_OT_duplicate(), GRAPH_OT_euler_filter(), GRAPH_OT_extrapolation_type(), GRAPH_OT_fmodifier_add(), GRAPH_OT_fmodifier_copy(), GRAPH_OT_fmodifier_paste(), GRAPH_OT_frame_jump(), GRAPH_OT_ghost_curves_clear(), GRAPH_OT_ghost_curves_create(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_paste(), GRAPH_OT_previewrange_set(), GRAPH_OT_properties(), GRAPH_OT_sample(), GRAPH_OT_select_all_toggle(), GRAPH_OT_select_border(), GRAPH_OT_select_column(), GRAPH_OT_select_leftright(), GRAPH_OT_select_less(), GRAPH_OT_select_linked(), GRAPH_OT_select_more(), GRAPH_OT_smooth(), GRAPH_OT_snap(), GRAPH_OT_sound_bake(), GRAPH_OT_view_all(), GRAPH_OT_view_selected(), GROUP_OT_create(), GROUP_OT_objects_add_active(), GROUP_OT_objects_remove(), GROUP_OT_objects_remove_active(), IMAGE_OT_curves_point_set(), IMAGE_OT_cycle_render_slot(), IMAGE_OT_invert(), IMAGE_OT_new(), IMAGE_OT_open(), IMAGE_OT_pack(), IMAGE_OT_properties(), IMAGE_OT_reload(), IMAGE_OT_replace(), IMAGE_OT_sample(), IMAGE_OT_sample_line(), IMAGE_OT_save(), IMAGE_OT_save_as(), IMAGE_OT_save_sequence(), IMAGE_OT_scopes(), IMAGE_OT_unpack(), IMAGE_OT_view_pan(), IMAGE_OT_view_zoom(), INFO_OT_reports_display_update(), LATTICE_OT_make_regular(), LATTICE_OT_select_all(), LOGIC_OT_actuator_add(), LOGIC_OT_actuator_move(), LOGIC_OT_actuator_remove(), LOGIC_OT_controller_add(), LOGIC_OT_controller_move(), LOGIC_OT_controller_remove(), LOGIC_OT_links_cut(), LOGIC_OT_properties(), LOGIC_OT_sensor_add(), LOGIC_OT_sensor_move(), LOGIC_OT_sensor_remove(), LOGIC_OT_texface_convert(), macro_wrapper(), MARKER_OT_add(), MARKER_OT_delete(), MARKER_OT_duplicate(), MARKER_OT_make_links_scene(), MARKER_OT_move(), MARKER_OT_rename(), MARKER_OT_select(), MARKER_OT_select_all(), MARKER_OT_select_border(), MATERIAL_OT_copy(), MATERIAL_OT_new(), MATERIAL_OT_paste(), MBALL_OT_delete_metaelems(), MBALL_OT_duplicate_metaelems(), MBALL_OT_hide_metaelems(), MBALL_OT_reveal_metaelems(), MBALL_OT_select_all(), MBALL_OT_select_random_metaelems(), MESH_OT_beautify_fill(), MESH_OT_bevel(), MESH_OT_blend_from_shape(), MESH_OT_bridge_edge_loops(), MESH_OT_colors_reverse(), MESH_OT_colors_rotate(), MESH_OT_delete(), MESH_OT_dissolve(), MESH_OT_dissolve_limited(), MESH_OT_drop_named_image(), MESH_OT_dupli_extrude_cursor(), MESH_OT_edge_collapse(), MESH_OT_edge_collapse_loop(), MESH_OT_edge_face_add(), MESH_OT_edge_rotate(), MESH_OT_edge_split(), MESH_OT_edgering_select(), MESH_OT_edges_select_sharp(), MESH_OT_extrude_edges_indiv(), MESH_OT_extrude_faces_indiv(), MESH_OT_extrude_region(), MESH_OT_extrude_repeat(), MESH_OT_extrude_verts_indiv(), MESH_OT_faces_select_linked_flat(), MESH_OT_faces_shade_flat(), MESH_OT_faces_shade_smooth(), MESH_OT_fill(), MESH_OT_flip_normals(), MESH_OT_hide(), MESH_OT_inset(), MESH_OT_knife_cut(), MESH_OT_knife_tool(), MESH_OT_loop_multi_select(), MESH_OT_loop_select(), MESH_OT_loop_to_region(), MESH_OT_loopcut(), MESH_OT_mark_seam(), MESH_OT_mark_sharp(), MESH_OT_merge(), MESH_OT_navmesh_clear(), MESH_OT_navmesh_face_add(), MESH_OT_navmesh_face_copy(), MESH_OT_navmesh_make(), MESH_OT_navmesh_reset(), MESH_OT_noise(), MESH_OT_normals_make_consistent(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cube_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_monkey_add(), MESH_OT_primitive_plane_add(), MESH_OT_primitive_uv_sphere_add(), MESH_OT_quads_convert_to_tris(), MESH_OT_region_to_loop(), MESH_OT_remove_doubles(), MESH_OT_reveal(), MESH_OT_rip(), MESH_OT_screw(), MESH_OT_select_all(), MESH_OT_select_axis(), MESH_OT_select_by_number_vertices(), MESH_OT_select_interior_faces(), MESH_OT_select_less(), MESH_OT_select_linked(), MESH_OT_select_linked_pick(), MESH_OT_select_loose_verts(), MESH_OT_select_mirror(), MESH_OT_select_more(), MESH_OT_select_next_loop(), MESH_OT_select_non_manifold(), MESH_OT_select_nth(), MESH_OT_select_random(), MESH_OT_select_shortest_path(), MESH_OT_select_similar(), MESH_OT_select_vertex_path(), MESH_OT_separate(), MESH_OT_shape_propagate_to_all(), MESH_OT_solidify(), MESH_OT_sort_faces(), MESH_OT_spin(), MESH_OT_split(), MESH_OT_sticky_add(), MESH_OT_sticky_remove(), MESH_OT_subdivide(), MESH_OT_tris_convert_to_quads(), MESH_OT_uv_texture_add(), MESH_OT_uv_texture_remove(), MESH_OT_uvs_reverse(), MESH_OT_uvs_rotate(), MESH_OT_vert_connect(), MESH_OT_vert_slide(), MESH_OT_vertex_color_add(), MESH_OT_vertex_color_remove(), MESH_OT_vertices_randomize(), MESH_OT_vertices_smooth(), MESH_OT_vertices_sort(), NLA_OT_action_sync_length(), NLA_OT_actionclip_add(), NLA_OT_apply_scale(), NLA_OT_bake(), NLA_OT_channels_click(), NLA_OT_clear_scale(), NLA_OT_click_select(), NLA_OT_delete(), NLA_OT_delete_tracks(), NLA_OT_duplicate(), NLA_OT_fmodifier_add(), NLA_OT_fmodifier_copy(), NLA_OT_fmodifier_paste(), NLA_OT_meta_add(), NLA_OT_meta_remove(), NLA_OT_move_down(), NLA_OT_move_up(), NLA_OT_mute_toggle(), NLA_OT_properties(), NLA_OT_select_all_toggle(), NLA_OT_select_border(), NLA_OT_select_leftright(), NLA_OT_snap(), NLA_OT_soundclip_add(), NLA_OT_split(), NLA_OT_swap(), NLA_OT_tracks_add(), NLA_OT_transition_add(), NLA_OT_tweakmode_enter(), NLA_OT_tweakmode_exit(), NLA_OT_view_all(), NLA_OT_view_selected(), NODE_OT_add_file(), NODE_OT_backimage_move(), NODE_OT_backimage_sample(), NODE_OT_backimage_zoom(), NODE_OT_delete(), NODE_OT_delete_reconnect(), NODE_OT_duplicate(), NODE_OT_group_edit(), NODE_OT_group_make(), NODE_OT_group_socket_add(), NODE_OT_group_socket_move_down(), NODE_OT_group_socket_move_up(), NODE_OT_group_socket_remove(), NODE_OT_group_ungroup(), NODE_OT_hide_socket_toggle(), NODE_OT_hide_toggle(), NODE_OT_link(), NODE_OT_link_make(), NODE_OT_link_viewer(), NODE_OT_links_cut(), NODE_OT_links_detach(), NODE_OT_mute_toggle(), NODE_OT_new_node_tree(), NODE_OT_options_toggle(), NODE_OT_output_file_add_socket(), NODE_OT_output_file_remove_active_socket(), NODE_OT_preview_toggle(), NODE_OT_properties(), NODE_OT_read_fullsamplelayers(), NODE_OT_read_renderlayers(), NODE_OT_render_changed(), NODE_OT_resize(), NODE_OT_select(), NODE_OT_select_all(), NODE_OT_select_border(), NODE_OT_select_linked_from(), NODE_OT_select_linked_to(), NODE_OT_select_same_type(), NODE_OT_select_same_type_next(), NODE_OT_select_same_type_prev(), NODE_OT_show_cyclic_dependencies(), NODE_OT_view_all(), OBJECT_OT_add(), OBJECT_OT_add_named(), OBJECT_OT_armature_add(), OBJECT_OT_camera_add(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_constraints_copy(), OBJECT_OT_convert(), OBJECT_OT_delete(), OBJECT_OT_drop_named_material(), OBJECT_OT_duplicate(), OBJECT_OT_duplicates_make_real(), OBJECT_OT_editmode_toggle(), OBJECT_OT_effector_add(), OBJECT_OT_explode_refresh(), OBJECT_OT_forcefield_toggle(), OBJECT_OT_game_physics_copy(), OBJECT_OT_game_property_clear(), OBJECT_OT_game_property_copy(), OBJECT_OT_game_property_new(), OBJECT_OT_game_property_remove(), OBJECT_OT_group_add(), OBJECT_OT_group_instance_add(), OBJECT_OT_group_link(), OBJECT_OT_group_remove(), OBJECT_OT_hide_render_clear(), OBJECT_OT_hide_render_set(), OBJECT_OT_hide_view_clear(), OBJECT_OT_hide_view_set(), OBJECT_OT_hook_add_newobj(), OBJECT_OT_hook_add_selobj(), OBJECT_OT_hook_assign(), OBJECT_OT_hook_recenter(), OBJECT_OT_hook_remove(), OBJECT_OT_hook_reset(), OBJECT_OT_hook_select(), OBJECT_OT_join(), OBJECT_OT_join_shapes(), OBJECT_OT_lamp_add(), OBJECT_OT_location_clear(), OBJECT_OT_logic_bricks_copy(), OBJECT_OT_make_links_data(), OBJECT_OT_make_links_scene(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_material_slot_add(), OBJECT_OT_material_slot_assign(), OBJECT_OT_material_slot_copy(), OBJECT_OT_material_slot_deselect(), OBJECT_OT_material_slot_remove(), OBJECT_OT_material_slot_select(), OBJECT_OT_meshdeform_bind(), OBJECT_OT_metaball_add(), OBJECT_OT_mode_set(), OBJECT_OT_modifier_add(), OBJECT_OT_modifier_apply(), OBJECT_OT_modifier_convert(), OBJECT_OT_modifier_copy(), OBJECT_OT_modifier_move_down(), OBJECT_OT_modifier_move_up(), OBJECT_OT_modifier_remove(), OBJECT_OT_move_to_layer(), OBJECT_OT_multires_base_apply(), OBJECT_OT_multires_external_pack(), OBJECT_OT_multires_external_save(), OBJECT_OT_multires_higher_levels_delete(), OBJECT_OT_multires_reshape(), OBJECT_OT_multires_subdivide(), OBJECT_OT_ocean_bake(), OBJECT_OT_origin_clear(), OBJECT_OT_origin_set(), OBJECT_OT_parent_clear(), OBJECT_OT_parent_no_inverse_set(), OBJECT_OT_parent_set(), OBJECT_OT_particle_system_add(), OBJECT_OT_particle_system_remove(), OBJECT_OT_paths_calculate(), OBJECT_OT_paths_clear(), OBJECT_OT_posemode_toggle(), OBJECT_OT_proxy_make(), OBJECT_OT_rotation_clear(), OBJECT_OT_scale_clear(), OBJECT_OT_select_all(), OBJECT_OT_select_by_layer(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_select_mirror(), OBJECT_OT_select_random(), OBJECT_OT_select_same_group(), OBJECT_OT_shade_flat(), OBJECT_OT_shade_smooth(), OBJECT_OT_shape_key_add(), OBJECT_OT_shape_key_clear(), OBJECT_OT_shape_key_mirror(), OBJECT_OT_shape_key_move(), OBJECT_OT_shape_key_remove(), OBJECT_OT_shape_key_retime(), OBJECT_OT_slow_parent_clear(), OBJECT_OT_slow_parent_set(), OBJECT_OT_speaker_add(), OBJECT_OT_text_add(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), OBJECT_OT_transform_apply(), OBJECT_OT_vertex_group_add(), OBJECT_OT_vertex_group_assign(), OBJECT_OT_vertex_group_blend(), OBJECT_OT_vertex_group_clean(), OBJECT_OT_vertex_group_copy(), OBJECT_OT_vertex_group_copy_to_linked(), OBJECT_OT_vertex_group_copy_to_selected(), OBJECT_OT_vertex_group_deselect(), OBJECT_OT_vertex_group_fix(), OBJECT_OT_vertex_group_invert(), OBJECT_OT_vertex_group_levels(), OBJECT_OT_vertex_group_lock(), OBJECT_OT_vertex_group_mirror(), OBJECT_OT_vertex_group_move(), OBJECT_OT_vertex_group_normalize(), OBJECT_OT_vertex_group_normalize_all(), OBJECT_OT_vertex_group_remove(), OBJECT_OT_vertex_group_remove_from(), OBJECT_OT_vertex_group_select(), OBJECT_OT_vertex_group_set_active(), OBJECT_OT_vertex_group_sort(), OBJECT_OT_vertex_parent_set(), OBJECT_OT_visual_transform_apply(), operator_search_cb(), OUTLINER_OT_action_set(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_drivers_add_selected(), OUTLINER_OT_drivers_delete_selected(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_keyingset_add_selected(), OUTLINER_OT_keyingset_remove_selected(), OUTLINER_OT_object_operation(), OUTLINER_OT_parent_clear(), OUTLINER_OT_parent_drop(), OUTLINER_OT_renderability_toggle(), OUTLINER_OT_select_border(), OUTLINER_OT_selectability_toggle(), OUTLINER_OT_visibility_toggle(), PAINT_OT_brush_select(), PAINT_OT_clone_cursor_set(), PAINT_OT_face_select_all(), PAINT_OT_face_select_hide(), PAINT_OT_face_select_inverse(), PAINT_OT_face_select_linked(), PAINT_OT_face_select_linked_pick(), PAINT_OT_face_select_reveal(), PAINT_OT_grab_clone(), PAINT_OT_hide_show(), PAINT_OT_image_from_view(), PAINT_OT_image_paint(), PAINT_OT_project_image(), PAINT_OT_sample_color(), PAINT_OT_texture_paint_toggle(), PAINT_OT_vert_select_all(), PAINT_OT_vert_select_inverse(), PAINT_OT_vertex_color_set(), PAINT_OT_vertex_paint(), PAINT_OT_vertex_paint_toggle(), PAINT_OT_weight_from_bones(), PAINT_OT_weight_paint(), PAINT_OT_weight_paint_toggle(), PAINT_OT_weight_sample(), PAINT_OT_weight_sample_group(), PAINT_OT_weight_set(), PARTICLE_OT_brush_edit(), PARTICLE_OT_connect_hair(), PARTICLE_OT_delete(), PARTICLE_OT_disconnect_hair(), PARTICLE_OT_dupliob_copy(), PARTICLE_OT_dupliob_move_down(), PARTICLE_OT_dupliob_move_up(), PARTICLE_OT_dupliob_remove(), PARTICLE_OT_edited_clear(), PARTICLE_OT_hide(), PARTICLE_OT_mirror(), PARTICLE_OT_new(), PARTICLE_OT_new_target(), PARTICLE_OT_particle_edit_toggle(), PARTICLE_OT_rekey(), PARTICLE_OT_remove_doubles(), PARTICLE_OT_reveal(), PARTICLE_OT_select_all(), PARTICLE_OT_select_less(), PARTICLE_OT_select_linked(), PARTICLE_OT_select_more(), PARTICLE_OT_select_roots(), PARTICLE_OT_select_tips(), PARTICLE_OT_subdivide(), PARTICLE_OT_target_move_down(), PARTICLE_OT_target_move_up(), PARTICLE_OT_target_remove(), PARTICLE_OT_weight_set(), POSE_OT_armature_apply(), POSE_OT_armature_layers(), POSE_OT_autoside_names(), POSE_OT_bone_layers(), POSE_OT_breakdown(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_constraints_copy(), POSE_OT_copy(), POSE_OT_flip_names(), POSE_OT_group_add(), POSE_OT_group_assign(), POSE_OT_group_deselect(), POSE_OT_group_move(), POSE_OT_group_remove(), POSE_OT_group_select(), POSE_OT_group_sort(), POSE_OT_group_unassign(), POSE_OT_hide(), POSE_OT_ik_add(), POSE_OT_ik_clear(), POSE_OT_loc_clear(), POSE_OT_paste(), POSE_OT_paths_calculate(), POSE_OT_paths_clear(), POSE_OT_propagate(), POSE_OT_push(), POSE_OT_quaternions_flip(), POSE_OT_relax(), POSE_OT_reveal(), POSE_OT_rot_clear(), POSE_OT_rotation_mode_set(), POSE_OT_scale_clear(), POSE_OT_select_all(), POSE_OT_select_constraint_target(), POSE_OT_select_flip_active(), POSE_OT_select_grouped(), POSE_OT_select_hierarchy(), POSE_OT_select_linked(), POSE_OT_select_parent(), POSE_OT_transforms_clear(), POSE_OT_user_transforms_clear(), POSE_OT_visual_transform_apply(), POSELIB_OT_action_sanitise(), POSELIB_OT_apply_pose(), POSELIB_OT_browse_interactive(), POSELIB_OT_new(), POSELIB_OT_pose_add(), POSELIB_OT_pose_remove(), POSELIB_OT_pose_rename(), POSELIB_OT_unlink(), PTCACHE_OT_add(), PTCACHE_OT_bake(), PTCACHE_OT_bake_all(), PTCACHE_OT_bake_from_cache(), PTCACHE_OT_free_bake(), PTCACHE_OT_free_bake_all(), PTCACHE_OT_remove(), SCENE_OT_delete(), SCENE_OT_new(), SCENE_OT_render_layer_add(), SCENE_OT_render_layer_remove(), SCREEN_OT_actionzone(), SCREEN_OT_area_join(), SCREEN_OT_area_move(), SCREEN_OT_area_split(), SCREEN_OT_area_swap(), SCREEN_OT_delete(), SCREEN_OT_frame_jump(), SCREEN_OT_frame_offset(), SCREEN_OT_header_flip(), SCREEN_OT_keyframe_jump(), SCREEN_OT_new(), SCREEN_OT_region_flip(), SCREEN_OT_region_quadview(), SCREEN_OT_region_scale(), SCREEN_OT_screen_full_area(), SCREEN_OT_screencast(), SCREEN_OT_screenshot(), SCRIPT_OT_python_file_run(), SCULPT_OT_brush_stroke(), SCULPT_OT_sculptmode_toggle(), SCULPT_OT_set_persistent_base(), SCULPT_OT_uv_sculpt_stroke(), SEQUENCER_OT_change_effect_input(), SEQUENCER_OT_change_effect_type(), SEQUENCER_OT_change_path(), SEQUENCER_OT_copy(), SEQUENCER_OT_cut(), SEQUENCER_OT_delete(), SEQUENCER_OT_duplicate(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_images_separate(), SEQUENCER_OT_lock(), SEQUENCER_OT_meta_make(), SEQUENCER_OT_meta_separate(), SEQUENCER_OT_meta_toggle(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_mute(), SEQUENCER_OT_next_edit(), SEQUENCER_OT_offset_clear(), SEQUENCER_OT_paste(), SEQUENCER_OT_previous_edit(), SEQUENCER_OT_properties(), SEQUENCER_OT_reassign_inputs(), SEQUENCER_OT_rebuild_proxy(), SEQUENCER_OT_reload(), SEQUENCER_OT_rendersize(), SEQUENCER_OT_scene_strip_add(), SEQUENCER_OT_select(), SEQUENCER_OT_select_active_side(), SEQUENCER_OT_select_all(), SEQUENCER_OT_select_border(), SEQUENCER_OT_select_grouped(), SEQUENCER_OT_select_handles(), SEQUENCER_OT_select_inverse(), SEQUENCER_OT_select_less(), SEQUENCER_OT_select_linked(), SEQUENCER_OT_select_linked_pick(), SEQUENCER_OT_select_more(), SEQUENCER_OT_snap(), SEQUENCER_OT_sound_strip_add(), SEQUENCER_OT_swap(), SEQUENCER_OT_swap_data(), SEQUENCER_OT_swap_inputs(), SEQUENCER_OT_unlock(), SEQUENCER_OT_unmute(), SEQUENCER_OT_view_all(), SEQUENCER_OT_view_all_preview(), SEQUENCER_OT_view_ghost_border(), SEQUENCER_OT_view_selected(), SEQUENCER_OT_view_toggle(), SKETCH_OT_convert(), SKETCH_OT_draw_stroke(), SKETCH_OT_gesture(), SOUND_OT_bake_animation(), SOUND_OT_mixdown(), SOUND_OT_open(), SOUND_OT_open_mono(), SOUND_OT_pack(), SOUND_OT_unpack(), SOUND_OT_update_animation_flags(), SURFACE_OT_primitive_nurbs_surface_circle_add(), SURFACE_OT_primitive_nurbs_surface_curve_add(), SURFACE_OT_primitive_nurbs_surface_cylinder_add(), SURFACE_OT_primitive_nurbs_surface_sphere_add(), SURFACE_OT_primitive_nurbs_surface_surface_add(), SURFACE_OT_primitive_nurbs_surface_torus_add(), TEXT_OT_make_internal(), TEXT_OT_new(), TEXT_OT_open(), TEXT_OT_run_script(), TEXT_OT_scroll(), TEXT_OT_scroll_bar(), TEXT_OT_to_3d_object(), TEXT_OT_unlink(), TEXTURE_OT_envmap_clear(), TEXTURE_OT_envmap_clear_all(), TEXTURE_OT_envmap_save(), TEXTURE_OT_new(), TEXTURE_OT_slot_copy(), TEXTURE_OT_slot_move(), TEXTURE_OT_slot_paste(), TIME_OT_end_frame_set(), TIME_OT_start_frame_set(), TIME_OT_view_all(), TRANSFORM_OT_create_orientation(), TRANSFORM_OT_delete_orientation(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_select_orientation(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_snap_type(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), TRANSFORM_OT_warp(), UI_OT_copy_data_path_button(), UI_OT_copy_to_selected_button(), UI_OT_eyedropper(), UI_OT_reset_default_button(), UI_OT_reset_default_theme(), uiLayoutOperatorButs(), UV_OT_align(), UV_OT_average_islands_scale(), UV_OT_circle_select(), UV_OT_cube_project(), UV_OT_cursor_set(), UV_OT_cylinder_project(), UV_OT_from_view(), UV_OT_hide(), UV_OT_mark_seam(), UV_OT_minimize_stretch(), UV_OT_pack_islands(), UV_OT_pin(), UV_OT_reset(), UV_OT_reveal(), UV_OT_seams_from_islands(), UV_OT_select(), UV_OT_select_all(), UV_OT_select_border(), UV_OT_select_linked(), UV_OT_select_linked_pick(), UV_OT_select_loop(), UV_OT_select_pinned(), UV_OT_snap_cursor(), UV_OT_snap_selected(), UV_OT_sphere_project(), UV_OT_stitch(), UV_OT_tile_set(), UV_OT_unlink_selected(), UV_OT_unwrap(), UV_OT_weld(), VIEW2D_OT_pan(), VIEW2D_OT_scroller_activate(), VIEW3D_OT_background_image_add(), VIEW3D_OT_background_image_remove(), VIEW3D_OT_camera_to_view(), VIEW3D_OT_camera_to_view_selected(), VIEW3D_OT_clip_border(), VIEW3D_OT_dolly(), VIEW3D_OT_fly(), VIEW3D_OT_layers(), VIEW3D_OT_localview(), VIEW3D_OT_move(), VIEW3D_OT_ndof_orbit(), VIEW3D_OT_ndof_pan(), VIEW3D_OT_object_as_camera(), VIEW3D_OT_properties(), VIEW3D_OT_render_border(), VIEW3D_OT_rotate(), VIEW3D_OT_select(), VIEW3D_OT_select_border(), VIEW3D_OT_select_circle(), VIEW3D_OT_select_lasso(), VIEW3D_OT_select_menu(), VIEW3D_OT_snap_cursor_to_active(), VIEW3D_OT_snap_cursor_to_center(), VIEW3D_OT_snap_cursor_to_grid(), VIEW3D_OT_snap_cursor_to_selected(), VIEW3D_OT_snap_selected_to_cursor(), VIEW3D_OT_snap_selected_to_grid(), VIEW3D_OT_toolshelf(), VIEW3D_OT_view_all(), VIEW3D_OT_view_center_camera(), VIEW3D_OT_view_center_cursor(), VIEW3D_OT_view_orbit(), VIEW3D_OT_view_pan(), VIEW3D_OT_view_persportho(), VIEW3D_OT_view_selected(), VIEW3D_OT_viewnumpad(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), VIEW3D_OT_zoom_camera_1_to_1(), view3d_panel_operator_redo_operator(), wm_block_create_redo(), WM_event_remove_handlers(), wm_handler_fileselect_call(), wm_handler_operator_call(), wm_macro_modal(), WM_operator_call_py(), wm_operator_exec(), wm_operator_finished(), wm_operator_invoke(), WM_operator_last_redo(), WM_operator_props_popup(), WM_operator_redo_popup(), wm_operator_register_check(), wm_operator_reports(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), WM_OT_call_menu(), WM_OT_link_append(), WM_OT_radial_control(), and WORLD_OT_new().
const char* wmOperatorType::idname
Definition at line 433 of file WM_types.h.
Referenced by ACTION_OT_clean(), ACTION_OT_clickselect(), ACTION_OT_copy(), ACTION_OT_delete(), ACTION_OT_duplicate(), ACTION_OT_extrapolation_type(), ACTION_OT_frame_jump(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_markers_make_local(), ACTION_OT_mirror(), ACTION_OT_new(), ACTION_OT_paste(), ACTION_OT_previewrange_set(), ACTION_OT_sample(), ACTION_OT_select_all_toggle(), ACTION_OT_select_border(), ACTION_OT_select_column(), ACTION_OT_select_leftright(), ACTION_OT_select_less(), ACTION_OT_select_linked(), ACTION_OT_select_more(), ACTION_OT_snap(), ACTION_OT_view_all(), ACTION_OT_view_selected(), ANIM_OT_change_frame(), ANIM_OT_channels_click(), ANIM_OT_channels_collapse(), ANIM_OT_channels_delete(), ANIM_OT_channels_editable_toggle(), ANIM_OT_channels_expand(), ANIM_OT_channels_fcurves_enable(), ANIM_OT_channels_move(), ANIM_OT_channels_rename(), ANIM_OT_channels_select_all_toggle(), ANIM_OT_channels_select_border(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), ANIM_OT_channels_setting_toggle(), ANIM_OT_channels_visibility_set(), ANIM_OT_channels_visibility_toggle(), ANIM_OT_copy_driver_button(), ANIM_OT_driver_button_add(), ANIM_OT_driver_button_remove(), ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_delete_button(), ANIM_OT_keyframe_delete_v3d(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_button(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_active_set(), ANIM_OT_keying_set_add(), ANIM_OT_keying_set_path_add(), ANIM_OT_keying_set_path_remove(), ANIM_OT_keying_set_remove(), ANIM_OT_keyingset_button_add(), ANIM_OT_keyingset_button_remove(), ANIM_OT_paste_driver_button(), ANIM_OT_previewrange_clear(), ANIM_OT_previewrange_set(), ARMATURE_OT_align(), ARMATURE_OT_armature_layers(), ARMATURE_OT_autoside_names(), ARMATURE_OT_bone_layers(), ARMATURE_OT_bone_primitive_add(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_click_extrude(), ARMATURE_OT_delete(), ARMATURE_OT_duplicate(), ARMATURE_OT_extrude(), ARMATURE_OT_fill(), ARMATURE_OT_flip_names(), ARMATURE_OT_hide(), ARMATURE_OT_layers_show_all(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), ARMATURE_OT_parent_set(), ARMATURE_OT_reveal(), ARMATURE_OT_select_all(), ARMATURE_OT_select_hierarchy(), ARMATURE_OT_select_inverse(), ARMATURE_OT_select_linked(), ARMATURE_OT_separate(), ARMATURE_OT_subdivide(), ARMATURE_OT_switch_direction(), BOID_OT_rule_add(), BOID_OT_rule_del(), BOID_OT_rule_move_down(), BOID_OT_rule_move_up(), BOID_OT_state_add(), BOID_OT_state_del(), BOID_OT_state_move_down(), BOID_OT_state_move_up(), BRUSH_OT_add(), BRUSH_OT_curve_preset(), BRUSH_OT_reset(), BRUSH_OT_scale_size(), BRUSH_OT_uv_sculpt_tool_set(), but_shortcut_name_func(), BUTTONS_OT_directory_browse(), BUTTONS_OT_file_browse(), BUTTONS_OT_toolbox(), CLIP_OT_add_marker(), CLIP_OT_change_frame(), CLIP_OT_clean_tracks(), CLIP_OT_clear_solution(), CLIP_OT_clear_track_path(), CLIP_OT_copy_tracks(), CLIP_OT_delete_marker(), CLIP_OT_delete_track(), CLIP_OT_detect_features(), CLIP_OT_disable_markers(), CLIP_OT_frame_jump(), CLIP_OT_graph_center_current_frame(), CLIP_OT_graph_delete_curve(), CLIP_OT_graph_delete_knot(), CLIP_OT_graph_disable_markers(), CLIP_OT_graph_select(), CLIP_OT_graph_select_all_markers(), CLIP_OT_graph_select_border(), CLIP_OT_graph_view_all(), CLIP_OT_hide_tracks(), CLIP_OT_hide_tracks_clear(), CLIP_OT_join_tracks(), CLIP_OT_lock_tracks(), CLIP_OT_mode_set(), CLIP_OT_open(), CLIP_OT_paste_tracks(), CLIP_OT_properties(), CLIP_OT_rebuild_proxy(), CLIP_OT_reload(), CLIP_OT_select(), CLIP_OT_select_all(), CLIP_OT_select_border(), CLIP_OT_select_circle(), CLIP_OT_select_grouped(), CLIP_OT_set_axis(), CLIP_OT_set_center_principal(), CLIP_OT_set_origin(), CLIP_OT_set_plane(), CLIP_OT_set_scale(), CLIP_OT_set_solution_scale(), CLIP_OT_slide_marker(), CLIP_OT_solve_camera(), CLIP_OT_stabilize_2d_add(), CLIP_OT_stabilize_2d_remove(), CLIP_OT_stabilize_2d_select(), CLIP_OT_stabilize_2d_set_rotation(), CLIP_OT_tools(), CLIP_OT_track_copy_color(), CLIP_OT_track_markers(), CLIP_OT_tracking_object_new(), CLIP_OT_tracking_object_remove(), CLIP_OT_view_all(), CLIP_OT_view_pan(), CLIP_OT_view_selected(), CLIP_OT_view_zoom(), CLIP_OT_view_zoom_in(), CLIP_OT_view_zoom_out(), CLIP_OT_view_zoom_ratio(), CONSOLE_OT_clear(), CONSOLE_OT_copy(), CONSOLE_OT_delete(), CONSOLE_OT_history_append(), CONSOLE_OT_history_cycle(), CONSOLE_OT_insert(), CONSOLE_OT_move(), CONSOLE_OT_paste(), CONSOLE_OT_scrollback_append(), CONSOLE_OT_select_set(), CONSTRAINT_OT_childof_clear_inverse(), CONSTRAINT_OT_childof_set_inverse(), CONSTRAINT_OT_delete(), CONSTRAINT_OT_limitdistance_reset(), CONSTRAINT_OT_move_down(), CONSTRAINT_OT_move_up(), CONSTRAINT_OT_objectsolver_clear_inverse(), CONSTRAINT_OT_objectsolver_set_inverse(), CONSTRAINT_OT_stretchto_reset(), CURVE_OT_cyclic_toggle(), CURVE_OT_de_select_first(), CURVE_OT_de_select_last(), CURVE_OT_delete(), CURVE_OT_duplicate(), CURVE_OT_extrude(), CURVE_OT_handle_type_set(), CURVE_OT_hide(), CURVE_OT_make_segment(), CURVE_OT_primitive_bezier_circle_add(), CURVE_OT_primitive_bezier_curve_add(), CURVE_OT_primitive_nurbs_circle_add(), CURVE_OT_primitive_nurbs_curve_add(), CURVE_OT_primitive_nurbs_path_add(), CURVE_OT_radius_set(), CURVE_OT_reveal(), CURVE_OT_select_all(), CURVE_OT_select_less(), CURVE_OT_select_linked(), CURVE_OT_select_linked_pick(), CURVE_OT_select_more(), CURVE_OT_select_next(), CURVE_OT_select_nth(), CURVE_OT_select_previous(), CURVE_OT_select_random(), CURVE_OT_select_row(), CURVE_OT_separate(), CURVE_OT_shade_flat(), CURVE_OT_shade_smooth(), CURVE_OT_smooth(), CURVE_OT_smooth_radius(), CURVE_OT_spin(), CURVE_OT_spline_type_set(), CURVE_OT_spline_weight_set(), CURVE_OT_subdivide(), CURVE_OT_switch_direction(), CURVE_OT_tilt_clear(), CURVE_OT_vertex_add(), delete_invoke(), DPAINT_OT_bake(), DPAINT_OT_output_toggle(), DPAINT_OT_surface_slot_add(), DPAINT_OT_surface_slot_remove(), DPAINT_OT_type_toggle(), ED_OT_redo(), ED_OT_undo(), ED_OT_undo_history(), ED_OT_undo_push(), FILE_OT_bookmark_add(), FILE_OT_bookmark_toggle(), FILE_OT_cancel(), FILE_OT_delete(), FILE_OT_delete_bookmark(), FILE_OT_directory(), FILE_OT_directory_new(), FILE_OT_execute(), FILE_OT_filenum(), FILE_OT_find_missing_files(), FILE_OT_hidedot(), FILE_OT_highlight(), FILE_OT_make_paths_absolute(), FILE_OT_make_paths_relative(), FILE_OT_next(), FILE_OT_pack_all(), FILE_OT_parent(), FILE_OT_previous(), FILE_OT_refresh(), FILE_OT_rename(), FILE_OT_report_missing_files(), FILE_OT_select(), FILE_OT_select_all_toggle(), FILE_OT_select_bookmark(), FILE_OT_select_border(), FILE_OT_smoothscroll(), FILE_OT_unpack_all(), FONT_OT_case_set(), FONT_OT_case_toggle(), FONT_OT_change_character(), FONT_OT_change_spacing(), FONT_OT_delete(), FONT_OT_file_paste(), FONT_OT_insert_lorem(), FONT_OT_line_break(), FONT_OT_move(), FONT_OT_move_select(), FONT_OT_open(), FONT_OT_style_set(), FONT_OT_style_toggle(), FONT_OT_text_copy(), FONT_OT_text_cut(), FONT_OT_text_insert(), FONT_OT_text_paste(), FONT_OT_textbox_add(), FONT_OT_textbox_remove(), FONT_OT_unlink(), GPENCIL_OT_active_frame_delete(), GPENCIL_OT_convert(), GPENCIL_OT_data_add(), GPENCIL_OT_data_unlink(), GPENCIL_OT_draw(), GPENCIL_OT_layer_add(), GRAPH_OT_bake(), GRAPH_OT_clean(), GRAPH_OT_click_insert(), GRAPH_OT_clickselect(), GRAPH_OT_copy(), GRAPH_OT_cursor_set(), GRAPH_OT_delete(), GRAPH_OT_duplicate(), GRAPH_OT_euler_filter(), GRAPH_OT_extrapolation_type(), GRAPH_OT_fmodifier_add(), GRAPH_OT_fmodifier_copy(), GRAPH_OT_fmodifier_paste(), GRAPH_OT_frame_jump(), GRAPH_OT_ghost_curves_clear(), GRAPH_OT_ghost_curves_create(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_paste(), GRAPH_OT_previewrange_set(), GRAPH_OT_properties(), GRAPH_OT_sample(), GRAPH_OT_select_all_toggle(), GRAPH_OT_select_border(), GRAPH_OT_select_column(), GRAPH_OT_select_leftright(), GRAPH_OT_select_less(), GRAPH_OT_select_linked(), GRAPH_OT_select_more(), GRAPH_OT_smooth(), GRAPH_OT_snap(), GRAPH_OT_sound_bake(), GRAPH_OT_view_all(), GRAPH_OT_view_selected(), GROUP_OT_create(), GROUP_OT_objects_add_active(), GROUP_OT_objects_remove(), GROUP_OT_objects_remove_active(), IMAGE_OT_curves_point_set(), IMAGE_OT_cycle_render_slot(), IMAGE_OT_invert(), IMAGE_OT_new(), IMAGE_OT_open(), IMAGE_OT_pack(), IMAGE_OT_properties(), IMAGE_OT_record_composite(), IMAGE_OT_reload(), IMAGE_OT_replace(), IMAGE_OT_sample(), IMAGE_OT_sample_line(), IMAGE_OT_save(), IMAGE_OT_save_as(), IMAGE_OT_save_sequence(), IMAGE_OT_scopes(), IMAGE_OT_unpack(), IMAGE_OT_view_all(), IMAGE_OT_view_ndof(), IMAGE_OT_view_pan(), IMAGE_OT_view_selected(), IMAGE_OT_view_zoom(), IMAGE_OT_view_zoom_in(), IMAGE_OT_view_zoom_out(), IMAGE_OT_view_zoom_ratio(), INFO_OT_report_copy(), INFO_OT_report_delete(), INFO_OT_report_replay(), INFO_OT_reports_display_update(), INFO_OT_select_all_toggle(), INFO_OT_select_border(), INFO_OT_select_pick(), LATTICE_OT_make_regular(), LATTICE_OT_select_all(), LOGIC_OT_actuator_add(), LOGIC_OT_actuator_move(), LOGIC_OT_actuator_remove(), LOGIC_OT_controller_add(), LOGIC_OT_controller_move(), LOGIC_OT_controller_remove(), LOGIC_OT_links_cut(), LOGIC_OT_properties(), LOGIC_OT_sensor_add(), LOGIC_OT_sensor_move(), LOGIC_OT_sensor_remove(), LOGIC_OT_texface_convert(), macro_wrapper(), MARKER_OT_add(), MARKER_OT_delete(), MARKER_OT_duplicate(), MARKER_OT_make_links_scene(), MARKER_OT_move(), MARKER_OT_rename(), MARKER_OT_select(), MARKER_OT_select_all(), MARKER_OT_select_border(), MATERIAL_OT_copy(), MATERIAL_OT_new(), MATERIAL_OT_paste(), MBALL_OT_delete_metaelems(), MBALL_OT_duplicate_metaelems(), MBALL_OT_hide_metaelems(), MBALL_OT_reveal_metaelems(), MBALL_OT_select_all(), MBALL_OT_select_random_metaelems(), menu_add_shortcut(), menu_change_shortcut(), MESH_OT_beautify_fill(), MESH_OT_bevel(), MESH_OT_blend_from_shape(), MESH_OT_bridge_edge_loops(), MESH_OT_colors_reverse(), MESH_OT_colors_rotate(), MESH_OT_delete(), MESH_OT_dissolve(), MESH_OT_dissolve_limited(), MESH_OT_drop_named_image(), MESH_OT_dupli_extrude_cursor(), MESH_OT_duplicate(), MESH_OT_edge_collapse(), MESH_OT_edge_collapse_loop(), MESH_OT_edge_face_add(), MESH_OT_edge_rotate(), MESH_OT_edge_split(), MESH_OT_edgering_select(), MESH_OT_edges_select_sharp(), MESH_OT_extrude_edges_indiv(), MESH_OT_extrude_faces_indiv(), MESH_OT_extrude_region(), MESH_OT_extrude_repeat(), MESH_OT_extrude_verts_indiv(), MESH_OT_faces_select_linked_flat(), MESH_OT_faces_shade_flat(), MESH_OT_faces_shade_smooth(), MESH_OT_fill(), MESH_OT_flip_normals(), MESH_OT_hide(), MESH_OT_inset(), MESH_OT_knife_cut(), MESH_OT_knife_tool(), MESH_OT_loop_multi_select(), MESH_OT_loop_select(), MESH_OT_loop_to_region(), MESH_OT_loopcut(), MESH_OT_mark_seam(), MESH_OT_mark_sharp(), MESH_OT_merge(), MESH_OT_navmesh_clear(), MESH_OT_navmesh_face_add(), MESH_OT_navmesh_face_copy(), MESH_OT_navmesh_make(), MESH_OT_navmesh_reset(), MESH_OT_noise(), MESH_OT_normals_make_consistent(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cube_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_monkey_add(), MESH_OT_primitive_plane_add(), MESH_OT_primitive_uv_sphere_add(), MESH_OT_quads_convert_to_tris(), MESH_OT_region_to_loop(), MESH_OT_remove_doubles(), MESH_OT_reveal(), MESH_OT_rip(), MESH_OT_screw(), MESH_OT_select_all(), MESH_OT_select_axis(), MESH_OT_select_by_number_vertices(), MESH_OT_select_interior_faces(), MESH_OT_select_less(), MESH_OT_select_linked(), MESH_OT_select_linked_pick(), MESH_OT_select_loose_verts(), MESH_OT_select_mirror(), MESH_OT_select_more(), MESH_OT_select_next_loop(), MESH_OT_select_non_manifold(), MESH_OT_select_nth(), MESH_OT_select_random(), MESH_OT_select_shortest_path(), MESH_OT_select_similar(), MESH_OT_select_vertex_path(), MESH_OT_separate(), MESH_OT_shape_propagate_to_all(), MESH_OT_solidify(), MESH_OT_sort_faces(), MESH_OT_spin(), MESH_OT_split(), MESH_OT_sticky_add(), MESH_OT_sticky_remove(), MESH_OT_subdivide(), MESH_OT_tris_convert_to_quads(), MESH_OT_uv_texture_add(), MESH_OT_uv_texture_remove(), MESH_OT_uvs_reverse(), MESH_OT_uvs_rotate(), MESH_OT_vert_connect(), MESH_OT_vert_slide(), MESH_OT_vertex_color_add(), MESH_OT_vertex_color_remove(), MESH_OT_vertices_randomize(), MESH_OT_vertices_smooth(), MESH_OT_vertices_sort(), NLA_OT_action_sync_length(), NLA_OT_actionclip_add(), NLA_OT_apply_scale(), NLA_OT_bake(), NLA_OT_channels_click(), NLA_OT_clear_scale(), NLA_OT_click_select(), NLA_OT_delete(), NLA_OT_delete_tracks(), NLA_OT_duplicate(), NLA_OT_fmodifier_add(), NLA_OT_fmodifier_copy(), NLA_OT_fmodifier_paste(), NLA_OT_meta_add(), NLA_OT_meta_remove(), NLA_OT_move_down(), NLA_OT_move_up(), NLA_OT_mute_toggle(), NLA_OT_properties(), NLA_OT_select_all_toggle(), NLA_OT_select_border(), NLA_OT_select_leftright(), NLA_OT_snap(), NLA_OT_soundclip_add(), NLA_OT_split(), NLA_OT_swap(), NLA_OT_tracks_add(), NLA_OT_transition_add(), NLA_OT_tweakmode_enter(), NLA_OT_tweakmode_exit(), NLA_OT_view_all(), NLA_OT_view_selected(), node_group_edit_invoke(), NODE_OT_add_file(), NODE_OT_backimage_move(), NODE_OT_backimage_sample(), NODE_OT_backimage_zoom(), NODE_OT_delete(), NODE_OT_delete_reconnect(), NODE_OT_duplicate(), NODE_OT_group_edit(), NODE_OT_group_make(), NODE_OT_group_socket_add(), NODE_OT_group_socket_move_down(), NODE_OT_group_socket_move_up(), NODE_OT_group_socket_remove(), NODE_OT_group_ungroup(), NODE_OT_hide_socket_toggle(), NODE_OT_hide_toggle(), NODE_OT_link(), NODE_OT_link_make(), NODE_OT_link_viewer(), NODE_OT_links_cut(), NODE_OT_links_detach(), NODE_OT_mute_toggle(), NODE_OT_new_node_tree(), NODE_OT_options_toggle(), NODE_OT_output_file_add_socket(), NODE_OT_output_file_remove_active_socket(), NODE_OT_preview_toggle(), NODE_OT_properties(), NODE_OT_read_fullsamplelayers(), NODE_OT_read_renderlayers(), NODE_OT_render_changed(), NODE_OT_resize(), NODE_OT_select(), NODE_OT_select_all(), NODE_OT_select_border(), NODE_OT_select_linked_from(), NODE_OT_select_linked_to(), NODE_OT_select_same_type(), NODE_OT_select_same_type_next(), NODE_OT_select_same_type_prev(), NODE_OT_show_cyclic_dependencies(), NODE_OT_view_all(), object_metaball_add_invoke(), OBJECT_OT_add(), OBJECT_OT_add_named(), OBJECT_OT_armature_add(), OBJECT_OT_bake_image(), OBJECT_OT_camera_add(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_constraints_clear(), OBJECT_OT_constraints_copy(), OBJECT_OT_convert(), OBJECT_OT_delete(), OBJECT_OT_drop_named_material(), OBJECT_OT_duplicate(), OBJECT_OT_duplicates_make_real(), OBJECT_OT_editmode_toggle(), OBJECT_OT_effector_add(), OBJECT_OT_explode_refresh(), OBJECT_OT_forcefield_toggle(), OBJECT_OT_game_physics_copy(), OBJECT_OT_game_property_clear(), OBJECT_OT_game_property_copy(), OBJECT_OT_game_property_new(), OBJECT_OT_game_property_remove(), OBJECT_OT_group_add(), OBJECT_OT_group_instance_add(), OBJECT_OT_group_link(), OBJECT_OT_group_remove(), OBJECT_OT_hide_render_clear(), OBJECT_OT_hide_render_set(), OBJECT_OT_hide_view_clear(), OBJECT_OT_hide_view_set(), OBJECT_OT_hook_add_newobj(), OBJECT_OT_hook_add_selobj(), OBJECT_OT_hook_assign(), OBJECT_OT_hook_recenter(), OBJECT_OT_hook_remove(), OBJECT_OT_hook_reset(), OBJECT_OT_hook_select(), OBJECT_OT_join(), OBJECT_OT_join_shapes(), OBJECT_OT_lamp_add(), OBJECT_OT_location_clear(), OBJECT_OT_logic_bricks_copy(), OBJECT_OT_make_links_data(), OBJECT_OT_make_links_scene(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_material_slot_add(), OBJECT_OT_material_slot_assign(), OBJECT_OT_material_slot_copy(), OBJECT_OT_material_slot_deselect(), OBJECT_OT_material_slot_remove(), OBJECT_OT_material_slot_select(), OBJECT_OT_meshdeform_bind(), OBJECT_OT_metaball_add(), OBJECT_OT_mode_set(), OBJECT_OT_modifier_add(), OBJECT_OT_modifier_apply(), OBJECT_OT_modifier_convert(), OBJECT_OT_modifier_copy(), OBJECT_OT_modifier_move_down(), OBJECT_OT_modifier_move_up(), OBJECT_OT_modifier_remove(), OBJECT_OT_move_to_layer(), OBJECT_OT_multires_base_apply(), OBJECT_OT_multires_external_pack(), OBJECT_OT_multires_external_save(), OBJECT_OT_multires_higher_levels_delete(), OBJECT_OT_multires_reshape(), OBJECT_OT_multires_subdivide(), OBJECT_OT_ocean_bake(), OBJECT_OT_origin_clear(), OBJECT_OT_origin_set(), OBJECT_OT_parent_clear(), OBJECT_OT_parent_no_inverse_set(), OBJECT_OT_parent_set(), OBJECT_OT_particle_system_add(), OBJECT_OT_particle_system_remove(), OBJECT_OT_paths_calculate(), OBJECT_OT_paths_clear(), OBJECT_OT_posemode_toggle(), OBJECT_OT_proxy_make(), OBJECT_OT_rotation_clear(), OBJECT_OT_scale_clear(), OBJECT_OT_select_all(), OBJECT_OT_select_by_layer(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_select_mirror(), OBJECT_OT_select_random(), OBJECT_OT_select_same_group(), OBJECT_OT_shade_flat(), OBJECT_OT_shade_smooth(), OBJECT_OT_shape_key_add(), OBJECT_OT_shape_key_clear(), OBJECT_OT_shape_key_mirror(), OBJECT_OT_shape_key_move(), OBJECT_OT_shape_key_remove(), OBJECT_OT_shape_key_retime(), OBJECT_OT_slow_parent_clear(), OBJECT_OT_slow_parent_set(), OBJECT_OT_speaker_add(), OBJECT_OT_text_add(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), OBJECT_OT_transform_apply(), OBJECT_OT_vertex_group_add(), OBJECT_OT_vertex_group_assign(), OBJECT_OT_vertex_group_blend(), OBJECT_OT_vertex_group_clean(), OBJECT_OT_vertex_group_copy(), OBJECT_OT_vertex_group_copy_to_linked(), OBJECT_OT_vertex_group_copy_to_selected(), OBJECT_OT_vertex_group_deselect(), OBJECT_OT_vertex_group_fix(), OBJECT_OT_vertex_group_invert(), OBJECT_OT_vertex_group_levels(), OBJECT_OT_vertex_group_lock(), OBJECT_OT_vertex_group_mirror(), OBJECT_OT_vertex_group_move(), OBJECT_OT_vertex_group_normalize(), OBJECT_OT_vertex_group_normalize_all(), OBJECT_OT_vertex_group_remove(), OBJECT_OT_vertex_group_remove_from(), OBJECT_OT_vertex_group_select(), OBJECT_OT_vertex_group_set_active(), OBJECT_OT_vertex_group_sort(), OBJECT_OT_vertex_parent_set(), OBJECT_OT_visual_transform_apply(), operator_call_cb(), operator_enum_call_cb(), operator_enum_search_cb(), operator_properties_init(), operator_search_cb(), operatortype_ghash_free_cb(), OUTLINER_OT_action_set(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_drivers_add_selected(), OUTLINER_OT_drivers_delete_selected(), OUTLINER_OT_expanded_toggle(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_item_activate(), OUTLINER_OT_item_openclose(), OUTLINER_OT_item_rename(), OUTLINER_OT_keyingset_add_selected(), OUTLINER_OT_keyingset_remove_selected(), OUTLINER_OT_object_operation(), OUTLINER_OT_operation(), OUTLINER_OT_parent_clear(), OUTLINER_OT_parent_drop(), OUTLINER_OT_renderability_toggle(), OUTLINER_OT_scroll_page(), OUTLINER_OT_select_border(), OUTLINER_OT_selectability_toggle(), OUTLINER_OT_selected_toggle(), OUTLINER_OT_show_active(), OUTLINER_OT_show_hierarchy(), OUTLINER_OT_show_one_level(), OUTLINER_OT_visibility_toggle(), PAINT_OT_brush_select(), PAINT_OT_clone_cursor_set(), PAINT_OT_face_select_all(), PAINT_OT_face_select_hide(), PAINT_OT_face_select_inverse(), PAINT_OT_face_select_linked(), PAINT_OT_face_select_linked_pick(), PAINT_OT_face_select_reveal(), PAINT_OT_grab_clone(), PAINT_OT_hide_show(), PAINT_OT_image_from_view(), PAINT_OT_image_paint(), PAINT_OT_project_image(), PAINT_OT_sample_color(), PAINT_OT_texture_paint_toggle(), PAINT_OT_vert_select_all(), PAINT_OT_vert_select_inverse(), PAINT_OT_vertex_color_set(), PAINT_OT_vertex_paint(), PAINT_OT_vertex_paint_toggle(), PAINT_OT_weight_from_bones(), PAINT_OT_weight_paint(), PAINT_OT_weight_paint_toggle(), PAINT_OT_weight_sample(), PAINT_OT_weight_sample_group(), PAINT_OT_weight_set(), PARTICLE_OT_brush_edit(), PARTICLE_OT_connect_hair(), PARTICLE_OT_delete(), PARTICLE_OT_disconnect_hair(), PARTICLE_OT_dupliob_copy(), PARTICLE_OT_dupliob_move_down(), PARTICLE_OT_dupliob_move_up(), PARTICLE_OT_dupliob_remove(), PARTICLE_OT_edited_clear(), PARTICLE_OT_hide(), PARTICLE_OT_mirror(), PARTICLE_OT_new(), PARTICLE_OT_new_target(), PARTICLE_OT_particle_edit_toggle(), PARTICLE_OT_rekey(), PARTICLE_OT_remove_doubles(), PARTICLE_OT_reveal(), PARTICLE_OT_select_all(), PARTICLE_OT_select_less(), PARTICLE_OT_select_linked(), PARTICLE_OT_select_more(), PARTICLE_OT_select_roots(), PARTICLE_OT_select_tips(), PARTICLE_OT_subdivide(), PARTICLE_OT_target_move_down(), PARTICLE_OT_target_move_up(), PARTICLE_OT_target_remove(), PARTICLE_OT_weight_set(), POSE_OT_armature_apply(), POSE_OT_armature_layers(), POSE_OT_autoside_names(), POSE_OT_bone_layers(), POSE_OT_breakdown(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_constraints_clear(), POSE_OT_constraints_copy(), POSE_OT_copy(), POSE_OT_flip_names(), POSE_OT_group_add(), POSE_OT_group_assign(), POSE_OT_group_deselect(), POSE_OT_group_move(), POSE_OT_group_remove(), POSE_OT_group_select(), POSE_OT_group_sort(), POSE_OT_group_unassign(), POSE_OT_hide(), POSE_OT_ik_add(), POSE_OT_ik_clear(), POSE_OT_loc_clear(), POSE_OT_paste(), POSE_OT_paths_calculate(), POSE_OT_paths_clear(), POSE_OT_propagate(), POSE_OT_push(), POSE_OT_quaternions_flip(), POSE_OT_relax(), POSE_OT_reveal(), POSE_OT_rot_clear(), POSE_OT_rotation_mode_set(), POSE_OT_scale_clear(), POSE_OT_select_all(), POSE_OT_select_constraint_target(), POSE_OT_select_flip_active(), POSE_OT_select_grouped(), POSE_OT_select_hierarchy(), POSE_OT_select_linked(), POSE_OT_select_parent(), POSE_OT_transforms_clear(), POSE_OT_user_transforms_clear(), POSE_OT_visual_transform_apply(), POSELIB_OT_action_sanitise(), POSELIB_OT_apply_pose(), POSELIB_OT_browse_interactive(), POSELIB_OT_new(), POSELIB_OT_pose_add(), POSELIB_OT_pose_remove(), POSELIB_OT_pose_rename(), POSELIB_OT_unlink(), PTCACHE_OT_add(), PTCACHE_OT_bake(), PTCACHE_OT_bake_all(), PTCACHE_OT_bake_from_cache(), PTCACHE_OT_free_bake(), PTCACHE_OT_free_bake_all(), PTCACHE_OT_remove(), pyop_dir(), remove_shortcut_func(), RENDER_OT_opengl(), RENDER_OT_render(), RENDER_OT_view_cancel(), RENDER_OT_view_show(), repeat_history_invoke(), SCENE_OT_delete(), SCENE_OT_new(), SCENE_OT_render_layer_add(), SCENE_OT_render_layer_remove(), SCREEN_OT_actionzone(), SCREEN_OT_animation_cancel(), SCREEN_OT_animation_play(), SCREEN_OT_animation_step(), SCREEN_OT_area_dupli(), SCREEN_OT_area_join(), SCREEN_OT_area_move(), SCREEN_OT_area_options(), SCREEN_OT_area_split(), SCREEN_OT_area_swap(), SCREEN_OT_back_to_previous(), SCREEN_OT_delete(), SCREEN_OT_frame_jump(), SCREEN_OT_frame_offset(), SCREEN_OT_header_flip(), SCREEN_OT_header_toolbox(), SCREEN_OT_keyframe_jump(), SCREEN_OT_new(), SCREEN_OT_redo_last(), SCREEN_OT_region_flip(), SCREEN_OT_region_quadview(), SCREEN_OT_region_scale(), SCREEN_OT_repeat_history(), SCREEN_OT_repeat_last(), SCREEN_OT_screen_full_area(), SCREEN_OT_screen_set(), SCREEN_OT_screencast(), SCREEN_OT_screenshot(), SCREEN_OT_spacedata_cleanup(), SCREEN_OT_userpref_show(), SCRIPT_OT_python_file_run(), SCRIPT_OT_reload(), SCULPT_OT_brush_stroke(), SCULPT_OT_sculptmode_toggle(), SCULPT_OT_set_persistent_base(), SCULPT_OT_uv_sculpt_stroke(), SEQUENCER_OT_change_effect_input(), SEQUENCER_OT_change_effect_type(), SEQUENCER_OT_change_path(), SEQUENCER_OT_copy(), SEQUENCER_OT_cut(), SEQUENCER_OT_delete(), SEQUENCER_OT_duplicate(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_images_separate(), SEQUENCER_OT_lock(), SEQUENCER_OT_meta_make(), SEQUENCER_OT_meta_separate(), SEQUENCER_OT_meta_toggle(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_mute(), SEQUENCER_OT_next_edit(), SEQUENCER_OT_offset_clear(), SEQUENCER_OT_paste(), SEQUENCER_OT_previous_edit(), SEQUENCER_OT_properties(), SEQUENCER_OT_reassign_inputs(), SEQUENCER_OT_rebuild_proxy(), SEQUENCER_OT_refresh_all(), SEQUENCER_OT_reload(), SEQUENCER_OT_rendersize(), SEQUENCER_OT_scene_strip_add(), SEQUENCER_OT_select(), SEQUENCER_OT_select_active_side(), SEQUENCER_OT_select_all(), SEQUENCER_OT_select_border(), SEQUENCER_OT_select_grouped(), SEQUENCER_OT_select_handles(), SEQUENCER_OT_select_inverse(), SEQUENCER_OT_select_less(), SEQUENCER_OT_select_linked(), SEQUENCER_OT_select_linked_pick(), SEQUENCER_OT_select_more(), SEQUENCER_OT_snap(), SEQUENCER_OT_sound_strip_add(), SEQUENCER_OT_swap(), SEQUENCER_OT_swap_data(), SEQUENCER_OT_swap_inputs(), SEQUENCER_OT_unlock(), SEQUENCER_OT_unmute(), SEQUENCER_OT_view_all(), SEQUENCER_OT_view_all_preview(), SEQUENCER_OT_view_ghost_border(), SEQUENCER_OT_view_selected(), SEQUENCER_OT_view_toggle(), SEQUENCER_OT_view_zoom_ratio(), SKETCH_OT_cancel_stroke(), SKETCH_OT_convert(), SKETCH_OT_delete(), SKETCH_OT_draw_preview(), SKETCH_OT_draw_stroke(), SKETCH_OT_finish_stroke(), SKETCH_OT_gesture(), SKETCH_OT_select(), SOUND_OT_bake_animation(), SOUND_OT_mixdown(), SOUND_OT_open(), SOUND_OT_open_mono(), SOUND_OT_pack(), SOUND_OT_unpack(), SOUND_OT_update_animation_flags(), SURFACE_OT_primitive_nurbs_surface_circle_add(), SURFACE_OT_primitive_nurbs_surface_curve_add(), SURFACE_OT_primitive_nurbs_surface_cylinder_add(), SURFACE_OT_primitive_nurbs_surface_sphere_add(), SURFACE_OT_primitive_nurbs_surface_surface_add(), SURFACE_OT_primitive_nurbs_surface_torus_add(), TEXT_OT_comment(), TEXT_OT_convert_whitespace(), TEXT_OT_copy(), TEXT_OT_cursor_set(), TEXT_OT_cut(), TEXT_OT_delete(), TEXT_OT_find(), TEXT_OT_find_set_selected(), TEXT_OT_indent(), TEXT_OT_insert(), TEXT_OT_jump(), TEXT_OT_line_break(), TEXT_OT_line_number(), TEXT_OT_make_internal(), TEXT_OT_mark_all(), TEXT_OT_markers_clear(), TEXT_OT_move(), TEXT_OT_move_select(), TEXT_OT_new(), TEXT_OT_next_marker(), TEXT_OT_open(), TEXT_OT_overwrite_toggle(), TEXT_OT_paste(), TEXT_OT_previous_marker(), TEXT_OT_properties(), TEXT_OT_refresh_pyconstraints(), TEXT_OT_reload(), TEXT_OT_replace(), TEXT_OT_replace_set_selected(), TEXT_OT_resolve_conflict(), TEXT_OT_run_script(), TEXT_OT_save(), TEXT_OT_save_as(), TEXT_OT_scroll(), TEXT_OT_scroll_bar(), TEXT_OT_select_all(), TEXT_OT_select_line(), TEXT_OT_select_word(), TEXT_OT_selection_set(), TEXT_OT_to_3d_object(), TEXT_OT_uncomment(), TEXT_OT_unindent(), TEXT_OT_unlink(), TEXTURE_OT_envmap_clear(), TEXTURE_OT_envmap_clear_all(), TEXTURE_OT_envmap_save(), TEXTURE_OT_new(), TEXTURE_OT_slot_copy(), TEXTURE_OT_slot_move(), TEXTURE_OT_slot_paste(), TIME_OT_end_frame_set(), TIME_OT_start_frame_set(), TIME_OT_view_all(), toggle_cyclic_invoke(), TRANSFORM_OT_create_orientation(), TRANSFORM_OT_delete_orientation(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_select_orientation(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_snap_type(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), TRANSFORM_OT_warp(), transformops_data(), ui_apply_but_funcs_after(), ui_but_menu(), ui_handler_popup(), ui_menu_block_set_keymaps(), UI_OT_copy_data_path_button(), UI_OT_copy_to_selected_button(), UI_OT_eyedropper(), UI_OT_reports_to_textblock(), UI_OT_reset_default_button(), UI_OT_reset_default_theme(), ui_tooltip_create(), uiLayoutOperatorButs(), undo_history_invoke(), UV_OT_align(), UV_OT_average_islands_scale(), UV_OT_circle_select(), UV_OT_cube_project(), UV_OT_cursor_set(), UV_OT_cylinder_project(), UV_OT_from_view(), UV_OT_hide(), UV_OT_mark_seam(), UV_OT_minimize_stretch(), UV_OT_pack_islands(), UV_OT_pin(), UV_OT_reset(), UV_OT_reveal(), UV_OT_seams_from_islands(), UV_OT_select(), UV_OT_select_all(), UV_OT_select_border(), UV_OT_select_linked(), UV_OT_select_linked_pick(), UV_OT_select_loop(), UV_OT_select_pinned(), UV_OT_snap_cursor(), UV_OT_snap_selected(), UV_OT_sphere_project(), UV_OT_stitch(), UV_OT_tile_set(), UV_OT_unlink_selected(), UV_OT_unwrap(), UV_OT_weld(), VIEW2D_OT_pan(), VIEW2D_OT_reset(), VIEW2D_OT_scroll_down(), VIEW2D_OT_scroll_left(), VIEW2D_OT_scroll_right(), VIEW2D_OT_scroll_up(), VIEW2D_OT_scroller_activate(), VIEW2D_OT_zoom(), VIEW2D_OT_zoom_border(), VIEW2D_OT_zoom_in(), VIEW2D_OT_zoom_out(), VIEW3D_OT_background_image_add(), VIEW3D_OT_background_image_remove(), VIEW3D_OT_camera_to_view(), VIEW3D_OT_camera_to_view_selected(), VIEW3D_OT_clip_border(), VIEW3D_OT_cursor3d(), VIEW3D_OT_dolly(), VIEW3D_OT_enable_manipulator(), VIEW3D_OT_fly(), VIEW3D_OT_game_start(), VIEW3D_OT_layers(), VIEW3D_OT_localview(), VIEW3D_OT_manipulator(), VIEW3D_OT_move(), VIEW3D_OT_ndof_orbit(), VIEW3D_OT_ndof_pan(), VIEW3D_OT_object_as_camera(), VIEW3D_OT_properties(), VIEW3D_OT_render_border(), VIEW3D_OT_rotate(), VIEW3D_OT_select(), VIEW3D_OT_select_border(), VIEW3D_OT_select_circle(), VIEW3D_OT_select_lasso(), VIEW3D_OT_select_menu(), VIEW3D_OT_smoothview(), VIEW3D_OT_snap_cursor_to_active(), VIEW3D_OT_snap_cursor_to_center(), VIEW3D_OT_snap_cursor_to_grid(), VIEW3D_OT_snap_cursor_to_selected(), VIEW3D_OT_snap_selected_to_cursor(), VIEW3D_OT_snap_selected_to_grid(), VIEW3D_OT_toolshelf(), VIEW3D_OT_view_all(), VIEW3D_OT_view_center_camera(), VIEW3D_OT_view_center_cursor(), VIEW3D_OT_view_orbit(), VIEW3D_OT_view_pan(), VIEW3D_OT_view_persportho(), VIEW3D_OT_view_selected(), VIEW3D_OT_viewnumpad(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), VIEW3D_OT_zoom_camera_1_to_1(), wm_handler_op_context(), wm_handlers_do(), WM_menu_invoke(), wm_operator_create(), wm_operator_invoke(), WM_operator_props_popup(), WM_operator_pystring(), WM_operator_redo_popup(), WM_operatortype_append(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), WM_operatortype_append_ptr(), WM_operatortype_macro_define(), WM_operatortype_remove(), WM_OT_call_menu(), WM_OT_debug_menu(), WM_OT_dependency_relations(), WM_OT_link_append(), WM_OT_memory_statistics(), WM_OT_ndof_sensitivity_change(), WM_OT_open_mainfile(), WM_OT_quit_blender(), WM_OT_radial_control(), WM_OT_read_factory_settings(), WM_OT_read_homefile(), WM_OT_recover_auto_save(), WM_OT_recover_last_session(), WM_OT_redraw_timer(), WM_OT_save_as_mainfile(), WM_OT_save_homefile(), WM_OT_save_mainfile(), WM_OT_search_menu(), WM_OT_splash(), WM_OT_window_duplicate(), WM_OT_window_fullscreen_toggle(), WM_read_homefile_exec(), and WORLD_OT_new().
int(* wmOperatorType::invoke)(struct bContext *, struct wmOperator *, struct wmEvent *)
Definition at line 452 of file WM_types.h.
Referenced by ACTION_OT_clickselect(), ACTION_OT_delete(), ACTION_OT_duplicate(), ACTION_OT_extrapolation_type(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_mirror(), ACTION_OT_select_border(), ACTION_OT_select_leftright(), ACTION_OT_snap(), ANIM_OT_change_frame(), ANIM_OT_channels_click(), ANIM_OT_channels_rename(), ANIM_OT_channels_select_border(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), ANIM_OT_channels_setting_toggle(), ANIM_OT_keyframe_delete_v3d(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_active_set(), ANIM_OT_previewrange_set(), ARMATURE_OT_align(), ARMATURE_OT_armature_layers(), ARMATURE_OT_autoside_names(), ARMATURE_OT_bone_layers(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_click_extrude(), ARMATURE_OT_delete(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), ARMATURE_OT_parent_set(), ARMATURE_OT_select_linked(), ARMATURE_OT_separate(), BOID_OT_rule_add(), BUTTONS_OT_directory_browse(), BUTTONS_OT_file_browse(), BUTTONS_OT_toolbox(), CLIP_OT_add_marker(), CLIP_OT_change_frame(), CLIP_OT_clean_tracks(), CLIP_OT_delete_marker(), CLIP_OT_delete_track(), CLIP_OT_graph_delete_curve(), CLIP_OT_graph_select(), CLIP_OT_graph_select_border(), CLIP_OT_open(), CLIP_OT_select(), CLIP_OT_select_border(), CLIP_OT_select_circle(), CLIP_OT_set_scale(), CLIP_OT_set_solution_scale(), CLIP_OT_slide_marker(), CLIP_OT_solve_camera(), CLIP_OT_track_markers(), CLIP_OT_view_pan(), CLIP_OT_view_zoom(), CLIP_OT_view_zoom_in(), CLIP_OT_view_zoom_out(), CONSOLE_OT_insert(), CONSOLE_OT_select_set(), CONSTRAINT_OT_childof_clear_inverse(), CONSTRAINT_OT_childof_set_inverse(), CONSTRAINT_OT_limitdistance_reset(), CONSTRAINT_OT_move_down(), CONSTRAINT_OT_move_up(), CONSTRAINT_OT_objectsolver_clear_inverse(), CONSTRAINT_OT_objectsolver_set_inverse(), CONSTRAINT_OT_stretchto_reset(), CURVE_OT_cyclic_toggle(), CURVE_OT_delete(), CURVE_OT_handle_type_set(), CURVE_OT_primitive_bezier_circle_add(), CURVE_OT_primitive_bezier_curve_add(), CURVE_OT_primitive_nurbs_circle_add(), CURVE_OT_primitive_nurbs_curve_add(), CURVE_OT_primitive_nurbs_path_add(), CURVE_OT_radius_set(), CURVE_OT_select_linked(), CURVE_OT_select_linked_pick(), CURVE_OT_spin(), CURVE_OT_spline_type_set(), CURVE_OT_spline_weight_set(), CURVE_OT_vertex_add(), ED_OT_undo_history(), FILE_OT_delete(), FILE_OT_directory(), FILE_OT_directory_new(), FILE_OT_find_missing_files(), FILE_OT_highlight(), FILE_OT_pack_all(), FILE_OT_select(), FILE_OT_select_border(), FILE_OT_smoothscroll(), FILE_OT_unpack_all(), FONT_OT_file_paste(), FONT_OT_open(), FONT_OT_text_insert(), GPENCIL_OT_convert(), GPENCIL_OT_draw(), GRAPH_OT_bake(), GRAPH_OT_click_insert(), GRAPH_OT_clickselect(), GRAPH_OT_cursor_set(), GRAPH_OT_delete(), GRAPH_OT_duplicate(), GRAPH_OT_extrapolation_type(), GRAPH_OT_fmodifier_add(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_select_border(), GRAPH_OT_select_leftright(), GRAPH_OT_snap(), GRAPH_OT_sound_bake(), IMAGE_OT_curves_point_set(), IMAGE_OT_new(), IMAGE_OT_open(), IMAGE_OT_pack(), IMAGE_OT_record_composite(), IMAGE_OT_replace(), IMAGE_OT_sample(), IMAGE_OT_sample_line(), IMAGE_OT_save_as(), IMAGE_OT_unpack(), IMAGE_OT_view_ndof(), IMAGE_OT_view_pan(), IMAGE_OT_view_zoom(), IMAGE_OT_view_zoom_in(), IMAGE_OT_view_zoom_out(), INFO_OT_reports_display_update(), INFO_OT_select_border(), INFO_OT_select_pick(), LOGIC_OT_actuator_add(), LOGIC_OT_actuator_move(), LOGIC_OT_actuator_remove(), LOGIC_OT_controller_add(), LOGIC_OT_controller_move(), LOGIC_OT_controller_remove(), LOGIC_OT_links_cut(), LOGIC_OT_sensor_add(), LOGIC_OT_sensor_move(), LOGIC_OT_sensor_remove(), LOGIC_OT_texface_convert(), MARKER_OT_add(), MARKER_OT_delete(), MARKER_OT_duplicate(), MARKER_OT_make_links_scene(), MARKER_OT_move(), MARKER_OT_rename(), MARKER_OT_select(), MARKER_OT_select_all(), MARKER_OT_select_border(), MBALL_OT_duplicate_metaelems(), MBALL_OT_select_random_metaelems(), MESH_OT_blend_from_shape(), MESH_OT_delete(), MESH_OT_drop_named_image(), MESH_OT_dupli_extrude_cursor(), MESH_OT_duplicate(), MESH_OT_edgering_select(), MESH_OT_knife_cut(), MESH_OT_knife_tool(), MESH_OT_loop_select(), MESH_OT_loopcut(), MESH_OT_merge(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cube_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_monkey_add(), MESH_OT_primitive_plane_add(), MESH_OT_primitive_uv_sphere_add(), MESH_OT_rip(), MESH_OT_screw(), MESH_OT_select_linked_pick(), MESH_OT_select_shortest_path(), MESH_OT_select_similar(), MESH_OT_separate(), MESH_OT_sort_faces(), MESH_OT_spin(), MESH_OT_vert_slide(), NLA_OT_actionclip_add(), NLA_OT_channels_click(), NLA_OT_click_select(), NLA_OT_duplicate(), NLA_OT_fmodifier_add(), NLA_OT_select_border(), NLA_OT_select_leftright(), NLA_OT_snap(), NODE_OT_add_file(), NODE_OT_backimage_move(), NODE_OT_backimage_sample(), NODE_OT_group_edit(), NODE_OT_link(), NODE_OT_links_cut(), NODE_OT_resize(), NODE_OT_select(), NODE_OT_select_border(), OBJECT_OT_add(), OBJECT_OT_armature_add(), OBJECT_OT_bake_image(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_convert(), OBJECT_OT_delete(), OBJECT_OT_drop_named_material(), OBJECT_OT_effector_add(), OBJECT_OT_explode_refresh(), OBJECT_OT_group_instance_add(), OBJECT_OT_group_link(), OBJECT_OT_hook_remove(), OBJECT_OT_lamp_add(), OBJECT_OT_make_links_scene(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_meshdeform_bind(), OBJECT_OT_metaball_add(), OBJECT_OT_modifier_add(), OBJECT_OT_modifier_apply(), OBJECT_OT_modifier_convert(), OBJECT_OT_modifier_copy(), OBJECT_OT_modifier_move_down(), OBJECT_OT_modifier_move_up(), OBJECT_OT_modifier_remove(), OBJECT_OT_move_to_layer(), OBJECT_OT_multires_base_apply(), OBJECT_OT_multires_external_save(), OBJECT_OT_multires_higher_levels_delete(), OBJECT_OT_multires_reshape(), OBJECT_OT_multires_subdivide(), OBJECT_OT_ocean_bake(), OBJECT_OT_origin_set(), OBJECT_OT_parent_clear(), OBJECT_OT_parent_no_inverse_set(), OBJECT_OT_parent_set(), OBJECT_OT_proxy_make(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_slow_parent_clear(), OBJECT_OT_slow_parent_set(), OBJECT_OT_text_add(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), OBJECT_OT_vertex_group_set_active(), OBJECT_OT_vertex_parent_set(), OUTLINER_OT_action_set(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_item_activate(), OUTLINER_OT_item_openclose(), OUTLINER_OT_item_rename(), OUTLINER_OT_object_operation(), OUTLINER_OT_operation(), OUTLINER_OT_parent_clear(), OUTLINER_OT_parent_drop(), OUTLINER_OT_select_border(), PAINT_OT_clone_cursor_set(), PAINT_OT_face_select_linked_pick(), PAINT_OT_grab_clone(), PAINT_OT_hide_show(), PAINT_OT_image_paint(), PAINT_OT_project_image(), PAINT_OT_sample_color(), PAINT_OT_vertex_paint(), PAINT_OT_weight_from_bones(), PAINT_OT_weight_paint(), PAINT_OT_weight_sample(), PAINT_OT_weight_sample_group(), PARTICLE_OT_brush_edit(), PARTICLE_OT_delete(), PARTICLE_OT_rekey(), PARTICLE_OT_select_linked(), POSE_OT_armature_layers(), POSE_OT_autoside_names(), POSE_OT_bone_layers(), POSE_OT_breakdown(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_group_assign(), POSE_OT_ik_add(), POSE_OT_push(), POSE_OT_relax(), POSE_OT_rotation_mode_set(), POSE_OT_select_grouped(), POSE_OT_select_linked(), POSELIB_OT_browse_interactive(), POSELIB_OT_pose_add(), POSELIB_OT_pose_remove(), POSELIB_OT_pose_rename(), RENDER_OT_opengl(), RENDER_OT_render(), RENDER_OT_view_show(), SCENE_OT_new(), SCREEN_OT_actionzone(), SCREEN_OT_animation_step(), SCREEN_OT_area_dupli(), SCREEN_OT_area_join(), SCREEN_OT_area_move(), SCREEN_OT_area_options(), SCREEN_OT_area_split(), SCREEN_OT_area_swap(), SCREEN_OT_header_toolbox(), SCREEN_OT_redo_last(), SCREEN_OT_region_scale(), SCREEN_OT_repeat_history(), SCREEN_OT_screencast(), SCREEN_OT_screenshot(), SCREEN_OT_userpref_show(), SCULPT_OT_brush_stroke(), SCULPT_OT_uv_sculpt_stroke(), SEQUENCER_OT_change_path(), SEQUENCER_OT_cut(), SEQUENCER_OT_delete(), SEQUENCER_OT_duplicate(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_meta_make(), SEQUENCER_OT_meta_separate(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_scene_strip_add(), SEQUENCER_OT_select(), SEQUENCER_OT_select_border(), SEQUENCER_OT_select_grouped(), SEQUENCER_OT_select_linked_pick(), SEQUENCER_OT_snap(), SEQUENCER_OT_sound_strip_add(), SEQUENCER_OT_view_ghost_border(), SKETCH_OT_cancel_stroke(), SKETCH_OT_convert(), SKETCH_OT_delete(), SKETCH_OT_draw_preview(), SKETCH_OT_draw_stroke(), SKETCH_OT_finish_stroke(), SKETCH_OT_gesture(), SKETCH_OT_select(), SOUND_OT_mixdown(), SOUND_OT_open(), SOUND_OT_open_mono(), SOUND_OT_unpack(), SURFACE_OT_primitive_nurbs_surface_circle_add(), SURFACE_OT_primitive_nurbs_surface_curve_add(), SURFACE_OT_primitive_nurbs_surface_cylinder_add(), SURFACE_OT_primitive_nurbs_surface_sphere_add(), SURFACE_OT_primitive_nurbs_surface_surface_add(), SURFACE_OT_primitive_nurbs_surface_torus_add(), TEXT_OT_cursor_set(), TEXT_OT_insert(), TEXT_OT_jump(), TEXT_OT_line_number(), TEXT_OT_open(), TEXT_OT_reload(), TEXT_OT_resolve_conflict(), TEXT_OT_save_as(), TEXT_OT_scroll(), TEXT_OT_scroll_bar(), TEXT_OT_selection_set(), TEXT_OT_unlink(), TEXTURE_OT_envmap_save(), TRANSFORM_OT_create_orientation(), TRANSFORM_OT_delete_orientation(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_select_orientation(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_snap_type(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), TRANSFORM_OT_warp(), UI_OT_eyedropper(), UV_OT_circle_select(), UV_OT_cursor_set(), UV_OT_minimize_stretch(), UV_OT_select(), UV_OT_select_border(), UV_OT_select_linked_pick(), UV_OT_select_loop(), UV_OT_stitch(), UV_OT_tile_set(), VIEW2D_OT_pan(), VIEW2D_OT_scroller_activate(), VIEW2D_OT_zoom(), VIEW2D_OT_zoom_border(), VIEW2D_OT_zoom_in(), VIEW2D_OT_zoom_out(), VIEW3D_OT_background_image_add(), VIEW3D_OT_clip_border(), VIEW3D_OT_cursor3d(), VIEW3D_OT_dolly(), VIEW3D_OT_enable_manipulator(), VIEW3D_OT_fly(), VIEW3D_OT_layers(), VIEW3D_OT_manipulator(), VIEW3D_OT_move(), VIEW3D_OT_ndof_orbit(), VIEW3D_OT_ndof_pan(), VIEW3D_OT_render_border(), VIEW3D_OT_rotate(), VIEW3D_OT_select(), VIEW3D_OT_select_border(), VIEW3D_OT_select_circle(), VIEW3D_OT_select_lasso(), VIEW3D_OT_select_menu(), VIEW3D_OT_smoothview(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), wm_macro_invoke_internal(), wm_operator_invoke(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), WM_OT_debug_menu(), WM_OT_link_append(), WM_OT_open_mainfile(), WM_OT_quit_blender(), WM_OT_radial_control(), WM_OT_read_factory_settings(), WM_OT_read_homefile(), WM_OT_recover_auto_save(), WM_OT_redraw_timer(), WM_OT_save_as_mainfile(), WM_OT_save_homefile(), WM_OT_save_mainfile(), WM_OT_search_menu(), and WM_OT_splash().
struct IDProperty* wmOperatorType::last_properties
Definition at line 467 of file WM_types.h.
Referenced by operatortype_ghash_free_cb(), and WM_operatortype_remove().
ListBase wmOperatorType::macro
Definition at line 474 of file WM_types.h.
Referenced by operatortype_ghash_free_cb(), wm_operator_create(), WM_operator_poll(), wm_operatortype_free_macro(), WM_operatortype_macro_define(), and WM_operatortype_remove().
int(* wmOperatorType::modal)(struct bContext *, struct wmOperator *, struct wmEvent *)
Definition at line 454 of file WM_types.h.
Referenced by ACTION_OT_select_border(), ANIM_OT_change_frame(), ANIM_OT_channels_select_border(), ANIM_OT_previewrange_set(), CLIP_OT_change_frame(), CLIP_OT_graph_select_border(), CLIP_OT_select_border(), CLIP_OT_select_circle(), CLIP_OT_slide_marker(), CLIP_OT_solve_camera(), CLIP_OT_track_markers(), CLIP_OT_view_pan(), CLIP_OT_view_zoom(), CONSOLE_OT_select_set(), edbm_vertex_slide_exec(), FILE_OT_select_border(), GPENCIL_OT_draw(), GRAPH_OT_cursor_set(), GRAPH_OT_select_border(), IMAGE_OT_curves_point_set(), IMAGE_OT_record_composite(), IMAGE_OT_sample(), IMAGE_OT_sample_line(), IMAGE_OT_view_pan(), IMAGE_OT_view_zoom(), INFO_OT_select_border(), LOGIC_OT_links_cut(), MARKER_OT_duplicate(), MARKER_OT_move(), MARKER_OT_select_border(), MESH_OT_knife_cut(), MESH_OT_knife_tool(), MESH_OT_loopcut(), MESH_OT_vert_slide(), NLA_OT_select_border(), NODE_OT_backimage_move(), NODE_OT_backimage_sample(), NODE_OT_link(), NODE_OT_links_cut(), NODE_OT_resize(), NODE_OT_select_border(), OBJECT_OT_bake_image(), OUTLINER_OT_select_border(), PAINT_OT_grab_clone(), PAINT_OT_hide_show(), PAINT_OT_image_paint(), PAINT_OT_sample_color(), PAINT_OT_vertex_paint(), PAINT_OT_weight_paint(), PARTICLE_OT_brush_edit(), POSE_OT_breakdown(), POSE_OT_push(), POSE_OT_relax(), POSELIB_OT_browse_interactive(), RENDER_OT_opengl(), RENDER_OT_render(), SCREEN_OT_actionzone(), SCREEN_OT_area_join(), SCREEN_OT_area_move(), SCREEN_OT_area_split(), SCREEN_OT_area_swap(), SCREEN_OT_region_scale(), sculpt_brush_stroke_invoke(), SCULPT_OT_brush_stroke(), SCULPT_OT_uv_sculpt_stroke(), SEQUENCER_OT_select_border(), SEQUENCER_OT_view_ghost_border(), SKETCH_OT_draw_stroke(), SKETCH_OT_gesture(), TEXT_OT_scroll(), TEXT_OT_scroll_bar(), TEXT_OT_selection_set(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), TRANSFORM_OT_warp(), UI_OT_eyedropper(), UV_OT_circle_select(), UV_OT_minimize_stretch(), UV_OT_select_border(), UV_OT_stitch(), VIEW2D_OT_pan(), VIEW2D_OT_scroller_activate(), VIEW2D_OT_zoom(), VIEW2D_OT_zoom_border(), VIEW3D_OT_clip_border(), VIEW3D_OT_dolly(), VIEW3D_OT_fly(), VIEW3D_OT_move(), VIEW3D_OT_render_border(), VIEW3D_OT_rotate(), VIEW3D_OT_select_border(), VIEW3D_OT_select_circle(), VIEW3D_OT_select_lasso(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), vpaint_invoke(), wm_handler_operator_call(), wm_macro_modal(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), WM_OT_radial_control(), and wpaint_invoke().
struct wmKeyMap* wmOperatorType::modalkeymap
Definition at line 477 of file WM_types.h.
Referenced by initTransform(), wm_event_modalkeymap(), and WM_modalkeymap_assign().
const char* wmOperatorType::name
Definition at line 432 of file WM_types.h.
Referenced by ACTION_OT_clean(), ACTION_OT_clickselect(), ACTION_OT_copy(), ACTION_OT_delete(), ACTION_OT_duplicate(), ACTION_OT_extrapolation_type(), ACTION_OT_frame_jump(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_markers_make_local(), ACTION_OT_mirror(), ACTION_OT_new(), ACTION_OT_paste(), ACTION_OT_previewrange_set(), ACTION_OT_sample(), ACTION_OT_select_all_toggle(), ACTION_OT_select_border(), ACTION_OT_select_column(), ACTION_OT_select_leftright(), ACTION_OT_select_less(), ACTION_OT_select_linked(), ACTION_OT_select_more(), ACTION_OT_snap(), ACTION_OT_view_all(), ACTION_OT_view_selected(), ANIM_OT_change_frame(), ANIM_OT_channels_click(), ANIM_OT_channels_collapse(), ANIM_OT_channels_delete(), ANIM_OT_channels_editable_toggle(), ANIM_OT_channels_expand(), ANIM_OT_channels_fcurves_enable(), ANIM_OT_channels_move(), ANIM_OT_channels_rename(), ANIM_OT_channels_select_all_toggle(), ANIM_OT_channels_select_border(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), ANIM_OT_channels_setting_toggle(), ANIM_OT_channels_visibility_set(), ANIM_OT_channels_visibility_toggle(), ANIM_OT_copy_driver_button(), ANIM_OT_driver_button_add(), ANIM_OT_driver_button_remove(), ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_delete_button(), ANIM_OT_keyframe_delete_v3d(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_button(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_active_set(), ANIM_OT_keying_set_add(), ANIM_OT_keying_set_path_add(), ANIM_OT_keying_set_path_remove(), ANIM_OT_keying_set_remove(), ANIM_OT_keyingset_button_add(), ANIM_OT_keyingset_button_remove(), ANIM_OT_paste_driver_button(), ANIM_OT_previewrange_clear(), ANIM_OT_previewrange_set(), ARMATURE_OT_align(), ARMATURE_OT_armature_layers(), ARMATURE_OT_autoside_names(), ARMATURE_OT_bone_layers(), ARMATURE_OT_bone_primitive_add(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_click_extrude(), ARMATURE_OT_delete(), ARMATURE_OT_duplicate(), ARMATURE_OT_extrude(), ARMATURE_OT_fill(), ARMATURE_OT_flip_names(), ARMATURE_OT_hide(), ARMATURE_OT_layers_show_all(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), ARMATURE_OT_parent_set(), ARMATURE_OT_reveal(), ARMATURE_OT_select_all(), ARMATURE_OT_select_hierarchy(), ARMATURE_OT_select_inverse(), ARMATURE_OT_select_linked(), ARMATURE_OT_separate(), ARMATURE_OT_subdivide(), ARMATURE_OT_switch_direction(), BOID_OT_rule_add(), BOID_OT_rule_del(), BOID_OT_rule_move_down(), BOID_OT_rule_move_up(), BOID_OT_state_add(), BOID_OT_state_del(), BOID_OT_state_move_down(), BOID_OT_state_move_up(), BPy_BoolProperty(), BPy_BoolVectorProperty(), BPy_CollectionProperty(), BPy_EnumProperty(), BPy_FloatProperty(), BPy_FloatVectorProperty(), BPy_IntProperty(), BPy_IntVectorProperty(), BPy_PointerProperty(), BPy_StringProperty(), BRUSH_OT_add(), BRUSH_OT_curve_preset(), BRUSH_OT_reset(), BRUSH_OT_scale_size(), BRUSH_OT_uv_sculpt_tool_set(), BUTTONS_OT_directory_browse(), BUTTONS_OT_file_browse(), BUTTONS_OT_toolbox(), CLIP_OT_add_marker(), CLIP_OT_change_frame(), CLIP_OT_clean_tracks(), CLIP_OT_clear_solution(), CLIP_OT_clear_track_path(), CLIP_OT_copy_tracks(), CLIP_OT_delete_marker(), CLIP_OT_delete_track(), CLIP_OT_detect_features(), CLIP_OT_disable_markers(), CLIP_OT_frame_jump(), CLIP_OT_graph_center_current_frame(), CLIP_OT_graph_delete_curve(), CLIP_OT_graph_delete_knot(), CLIP_OT_graph_disable_markers(), CLIP_OT_graph_select(), CLIP_OT_graph_select_all_markers(), CLIP_OT_graph_select_border(), CLIP_OT_graph_view_all(), CLIP_OT_hide_tracks(), CLIP_OT_hide_tracks_clear(), CLIP_OT_join_tracks(), CLIP_OT_lock_tracks(), CLIP_OT_mode_set(), CLIP_OT_open(), CLIP_OT_paste_tracks(), CLIP_OT_properties(), CLIP_OT_rebuild_proxy(), CLIP_OT_reload(), CLIP_OT_select(), CLIP_OT_select_all(), CLIP_OT_select_border(), CLIP_OT_select_circle(), CLIP_OT_select_grouped(), CLIP_OT_set_axis(), CLIP_OT_set_center_principal(), CLIP_OT_set_origin(), CLIP_OT_set_plane(), CLIP_OT_set_scale(), CLIP_OT_set_solution_scale(), CLIP_OT_slide_marker(), CLIP_OT_solve_camera(), CLIP_OT_stabilize_2d_add(), CLIP_OT_stabilize_2d_remove(), CLIP_OT_stabilize_2d_select(), CLIP_OT_stabilize_2d_set_rotation(), CLIP_OT_tools(), CLIP_OT_track_copy_color(), CLIP_OT_track_markers(), CLIP_OT_tracking_object_new(), CLIP_OT_tracking_object_remove(), CLIP_OT_view_all(), CLIP_OT_view_pan(), CLIP_OT_view_selected(), CLIP_OT_view_zoom(), CLIP_OT_view_zoom_in(), CLIP_OT_view_zoom_out(), CLIP_OT_view_zoom_ratio(), clip_panel_operator_redo(), clip_panel_operator_redo_header(), clip_panel_operator_redo_operator(), CONSOLE_OT_clear(), CONSOLE_OT_copy(), CONSOLE_OT_delete(), CONSOLE_OT_history_append(), CONSOLE_OT_history_cycle(), CONSOLE_OT_insert(), CONSOLE_OT_move(), CONSOLE_OT_paste(), CONSOLE_OT_scrollback_append(), CONSOLE_OT_select_set(), CONSTRAINT_OT_childof_clear_inverse(), CONSTRAINT_OT_childof_set_inverse(), CONSTRAINT_OT_delete(), CONSTRAINT_OT_limitdistance_reset(), CONSTRAINT_OT_move_down(), CONSTRAINT_OT_move_up(), CONSTRAINT_OT_objectsolver_clear_inverse(), CONSTRAINT_OT_objectsolver_set_inverse(), CONSTRAINT_OT_stretchto_reset(), CURVE_OT_cyclic_toggle(), CURVE_OT_de_select_first(), CURVE_OT_de_select_last(), CURVE_OT_delete(), CURVE_OT_duplicate(), CURVE_OT_extrude(), CURVE_OT_handle_type_set(), CURVE_OT_hide(), CURVE_OT_make_segment(), CURVE_OT_primitive_bezier_circle_add(), CURVE_OT_primitive_bezier_curve_add(), CURVE_OT_primitive_nurbs_circle_add(), CURVE_OT_primitive_nurbs_curve_add(), CURVE_OT_primitive_nurbs_path_add(), CURVE_OT_radius_set(), CURVE_OT_reveal(), CURVE_OT_select_all(), CURVE_OT_select_less(), CURVE_OT_select_linked(), CURVE_OT_select_linked_pick(), CURVE_OT_select_more(), CURVE_OT_select_next(), CURVE_OT_select_nth(), CURVE_OT_select_previous(), CURVE_OT_select_random(), CURVE_OT_select_row(), CURVE_OT_separate(), CURVE_OT_shade_flat(), CURVE_OT_shade_smooth(), CURVE_OT_smooth(), CURVE_OT_smooth_radius(), CURVE_OT_spin(), CURVE_OT_spline_type_set(), CURVE_OT_spline_weight_set(), CURVE_OT_subdivide(), CURVE_OT_switch_direction(), CURVE_OT_tilt_clear(), CURVE_OT_vertex_add(), DPAINT_OT_bake(), DPAINT_OT_output_toggle(), DPAINT_OT_surface_slot_add(), DPAINT_OT_surface_slot_remove(), DPAINT_OT_type_toggle(), ED_OT_redo(), ED_OT_undo(), ED_OT_undo_history(), ED_OT_undo_push(), ED_undo_operator_repeat(), ED_undo_pop_op(), ED_undo_push_op(), FILE_OT_bookmark_add(), FILE_OT_bookmark_toggle(), FILE_OT_cancel(), FILE_OT_delete(), FILE_OT_delete_bookmark(), FILE_OT_directory(), FILE_OT_directory_new(), FILE_OT_execute(), FILE_OT_filenum(), FILE_OT_find_missing_files(), FILE_OT_hidedot(), FILE_OT_highlight(), FILE_OT_make_paths_absolute(), FILE_OT_make_paths_relative(), FILE_OT_next(), FILE_OT_pack_all(), FILE_OT_parent(), FILE_OT_previous(), FILE_OT_refresh(), FILE_OT_rename(), FILE_OT_report_missing_files(), FILE_OT_select(), FILE_OT_select_all_toggle(), FILE_OT_select_bookmark(), FILE_OT_select_border(), FILE_OT_smoothscroll(), FILE_OT_unpack_all(), file_panel_operator_header(), FONT_OT_case_set(), FONT_OT_case_toggle(), FONT_OT_change_character(), FONT_OT_change_spacing(), FONT_OT_delete(), FONT_OT_file_paste(), FONT_OT_insert_lorem(), FONT_OT_line_break(), FONT_OT_move(), FONT_OT_move_select(), FONT_OT_open(), FONT_OT_style_set(), FONT_OT_style_toggle(), FONT_OT_text_copy(), FONT_OT_text_cut(), FONT_OT_text_insert(), FONT_OT_text_paste(), FONT_OT_textbox_add(), FONT_OT_textbox_remove(), FONT_OT_unlink(), GPENCIL_OT_active_frame_delete(), GPENCIL_OT_convert(), GPENCIL_OT_data_add(), GPENCIL_OT_data_unlink(), GPENCIL_OT_draw(), GPENCIL_OT_layer_add(), GRAPH_OT_bake(), GRAPH_OT_clean(), GRAPH_OT_click_insert(), GRAPH_OT_clickselect(), GRAPH_OT_copy(), GRAPH_OT_cursor_set(), GRAPH_OT_delete(), GRAPH_OT_duplicate(), GRAPH_OT_euler_filter(), GRAPH_OT_extrapolation_type(), GRAPH_OT_fmodifier_add(), GRAPH_OT_fmodifier_copy(), GRAPH_OT_fmodifier_paste(), GRAPH_OT_frame_jump(), GRAPH_OT_ghost_curves_clear(), GRAPH_OT_ghost_curves_create(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_paste(), GRAPH_OT_previewrange_set(), GRAPH_OT_properties(), GRAPH_OT_sample(), GRAPH_OT_select_all_toggle(), GRAPH_OT_select_border(), GRAPH_OT_select_column(), GRAPH_OT_select_leftright(), GRAPH_OT_select_less(), GRAPH_OT_select_linked(), GRAPH_OT_select_more(), GRAPH_OT_smooth(), GRAPH_OT_snap(), GRAPH_OT_sound_bake(), GRAPH_OT_view_all(), GRAPH_OT_view_selected(), GROUP_OT_create(), GROUP_OT_objects_add_active(), GROUP_OT_objects_remove(), GROUP_OT_objects_remove_active(), IMAGE_OT_curves_point_set(), IMAGE_OT_cycle_render_slot(), IMAGE_OT_invert(), IMAGE_OT_new(), IMAGE_OT_open(), IMAGE_OT_pack(), IMAGE_OT_properties(), IMAGE_OT_record_composite(), IMAGE_OT_reload(), IMAGE_OT_replace(), IMAGE_OT_sample(), IMAGE_OT_sample_line(), IMAGE_OT_save(), IMAGE_OT_save_as(), IMAGE_OT_save_sequence(), IMAGE_OT_scopes(), IMAGE_OT_unpack(), IMAGE_OT_view_all(), IMAGE_OT_view_ndof(), IMAGE_OT_view_pan(), IMAGE_OT_view_selected(), IMAGE_OT_view_zoom(), IMAGE_OT_view_zoom_in(), IMAGE_OT_view_zoom_out(), IMAGE_OT_view_zoom_ratio(), INFO_OT_report_copy(), INFO_OT_report_delete(), INFO_OT_report_replay(), INFO_OT_reports_display_update(), INFO_OT_select_all_toggle(), INFO_OT_select_border(), INFO_OT_select_pick(), insert_key_menu_invoke(), keyingset_active_menu_invoke(), LATTICE_OT_make_regular(), LATTICE_OT_select_all(), LOGIC_OT_actuator_add(), LOGIC_OT_actuator_move(), LOGIC_OT_actuator_remove(), LOGIC_OT_controller_add(), LOGIC_OT_controller_move(), LOGIC_OT_controller_remove(), LOGIC_OT_links_cut(), LOGIC_OT_properties(), LOGIC_OT_sensor_add(), LOGIC_OT_sensor_move(), LOGIC_OT_sensor_remove(), LOGIC_OT_texface_convert(), macro_wrapper(), make_proxy_invoke(), MARKER_OT_add(), MARKER_OT_delete(), MARKER_OT_duplicate(), MARKER_OT_make_links_scene(), MARKER_OT_move(), MARKER_OT_rename(), MARKER_OT_select(), MARKER_OT_select_all(), MARKER_OT_select_border(), MATERIAL_OT_copy(), MATERIAL_OT_new(), MATERIAL_OT_paste(), MBALL_OT_delete_metaelems(), MBALL_OT_duplicate_metaelems(), MBALL_OT_hide_metaelems(), MBALL_OT_reveal_metaelems(), MBALL_OT_select_all(), MBALL_OT_select_random_metaelems(), MESH_OT_beautify_fill(), MESH_OT_bevel(), MESH_OT_blend_from_shape(), MESH_OT_bridge_edge_loops(), MESH_OT_colors_reverse(), MESH_OT_colors_rotate(), MESH_OT_delete(), MESH_OT_dissolve(), MESH_OT_dissolve_limited(), MESH_OT_drop_named_image(), MESH_OT_dupli_extrude_cursor(), MESH_OT_duplicate(), MESH_OT_edge_collapse(), MESH_OT_edge_collapse_loop(), MESH_OT_edge_face_add(), MESH_OT_edge_rotate(), MESH_OT_edge_split(), MESH_OT_edgering_select(), MESH_OT_edges_select_sharp(), MESH_OT_extrude_edges_indiv(), MESH_OT_extrude_faces_indiv(), MESH_OT_extrude_region(), MESH_OT_extrude_repeat(), MESH_OT_extrude_verts_indiv(), MESH_OT_faces_select_linked_flat(), MESH_OT_faces_shade_flat(), MESH_OT_faces_shade_smooth(), MESH_OT_fill(), MESH_OT_flip_normals(), MESH_OT_hide(), MESH_OT_inset(), MESH_OT_knife_cut(), MESH_OT_knife_tool(), MESH_OT_loop_multi_select(), MESH_OT_loop_select(), MESH_OT_loop_to_region(), MESH_OT_loopcut(), MESH_OT_mark_seam(), MESH_OT_mark_sharp(), MESH_OT_merge(), MESH_OT_navmesh_clear(), MESH_OT_navmesh_face_add(), MESH_OT_navmesh_face_copy(), MESH_OT_navmesh_make(), MESH_OT_navmesh_reset(), MESH_OT_noise(), MESH_OT_normals_make_consistent(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cube_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_monkey_add(), MESH_OT_primitive_plane_add(), MESH_OT_primitive_uv_sphere_add(), MESH_OT_quads_convert_to_tris(), MESH_OT_region_to_loop(), MESH_OT_remove_doubles(), MESH_OT_reveal(), MESH_OT_rip(), MESH_OT_screw(), MESH_OT_select_all(), MESH_OT_select_axis(), MESH_OT_select_by_number_vertices(), MESH_OT_select_interior_faces(), MESH_OT_select_less(), MESH_OT_select_linked(), MESH_OT_select_linked_pick(), MESH_OT_select_loose_verts(), MESH_OT_select_mirror(), MESH_OT_select_more(), MESH_OT_select_next_loop(), MESH_OT_select_non_manifold(), MESH_OT_select_nth(), MESH_OT_select_random(), MESH_OT_select_shortest_path(), MESH_OT_select_similar(), MESH_OT_select_vertex_path(), MESH_OT_separate(), MESH_OT_shape_propagate_to_all(), MESH_OT_solidify(), MESH_OT_sort_faces(), MESH_OT_spin(), MESH_OT_split(), MESH_OT_sticky_add(), MESH_OT_sticky_remove(), MESH_OT_subdivide(), MESH_OT_tris_convert_to_quads(), MESH_OT_uv_texture_add(), MESH_OT_uv_texture_remove(), MESH_OT_uvs_reverse(), MESH_OT_uvs_rotate(), MESH_OT_vert_connect(), MESH_OT_vert_slide(), MESH_OT_vertex_color_add(), MESH_OT_vertex_color_remove(), MESH_OT_vertices_randomize(), MESH_OT_vertices_smooth(), MESH_OT_vertices_sort(), NLA_OT_action_sync_length(), NLA_OT_actionclip_add(), NLA_OT_apply_scale(), NLA_OT_bake(), NLA_OT_channels_click(), NLA_OT_clear_scale(), NLA_OT_click_select(), NLA_OT_delete(), NLA_OT_delete_tracks(), NLA_OT_duplicate(), NLA_OT_fmodifier_add(), NLA_OT_fmodifier_copy(), NLA_OT_fmodifier_paste(), NLA_OT_meta_add(), NLA_OT_meta_remove(), NLA_OT_move_down(), NLA_OT_move_up(), NLA_OT_mute_toggle(), NLA_OT_properties(), NLA_OT_select_all_toggle(), NLA_OT_select_border(), NLA_OT_select_leftright(), NLA_OT_snap(), NLA_OT_soundclip_add(), NLA_OT_split(), NLA_OT_swap(), NLA_OT_tracks_add(), NLA_OT_transition_add(), NLA_OT_tweakmode_enter(), NLA_OT_tweakmode_exit(), NLA_OT_view_all(), NLA_OT_view_selected(), NODE_OT_add_file(), NODE_OT_backimage_move(), NODE_OT_backimage_sample(), NODE_OT_backimage_zoom(), NODE_OT_delete(), NODE_OT_delete_reconnect(), NODE_OT_duplicate(), NODE_OT_group_edit(), NODE_OT_group_make(), NODE_OT_group_socket_add(), NODE_OT_group_socket_move_down(), NODE_OT_group_socket_move_up(), NODE_OT_group_socket_remove(), NODE_OT_group_ungroup(), NODE_OT_hide_socket_toggle(), NODE_OT_hide_toggle(), NODE_OT_link(), NODE_OT_link_make(), NODE_OT_link_viewer(), NODE_OT_links_cut(), NODE_OT_links_detach(), NODE_OT_mute_toggle(), NODE_OT_new_node_tree(), NODE_OT_options_toggle(), NODE_OT_output_file_add_socket(), NODE_OT_output_file_remove_active_socket(), NODE_OT_preview_toggle(), NODE_OT_properties(), NODE_OT_read_fullsamplelayers(), NODE_OT_read_renderlayers(), NODE_OT_render_changed(), NODE_OT_resize(), NODE_OT_select(), NODE_OT_select_all(), NODE_OT_select_border(), NODE_OT_select_linked_from(), NODE_OT_select_linked_to(), NODE_OT_select_same_type(), NODE_OT_select_same_type_next(), NODE_OT_select_same_type_prev(), NODE_OT_show_cyclic_dependencies(), NODE_OT_view_all(), object_metaball_add_invoke(), OBJECT_OT_add(), OBJECT_OT_add_named(), OBJECT_OT_armature_add(), OBJECT_OT_bake_image(), OBJECT_OT_camera_add(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_constraints_clear(), OBJECT_OT_constraints_copy(), OBJECT_OT_convert(), OBJECT_OT_delete(), OBJECT_OT_drop_named_material(), OBJECT_OT_duplicate(), OBJECT_OT_duplicates_make_real(), OBJECT_OT_editmode_toggle(), OBJECT_OT_effector_add(), OBJECT_OT_explode_refresh(), OBJECT_OT_forcefield_toggle(), OBJECT_OT_game_physics_copy(), OBJECT_OT_game_property_clear(), OBJECT_OT_game_property_copy(), OBJECT_OT_game_property_new(), OBJECT_OT_game_property_remove(), OBJECT_OT_group_add(), OBJECT_OT_group_instance_add(), OBJECT_OT_group_link(), OBJECT_OT_group_remove(), OBJECT_OT_hide_render_clear(), OBJECT_OT_hide_render_set(), OBJECT_OT_hide_view_clear(), OBJECT_OT_hide_view_set(), OBJECT_OT_hook_add_newobj(), OBJECT_OT_hook_add_selobj(), OBJECT_OT_hook_assign(), OBJECT_OT_hook_recenter(), OBJECT_OT_hook_remove(), OBJECT_OT_hook_reset(), OBJECT_OT_hook_select(), OBJECT_OT_join(), OBJECT_OT_join_shapes(), OBJECT_OT_lamp_add(), OBJECT_OT_location_clear(), OBJECT_OT_logic_bricks_copy(), OBJECT_OT_make_links_data(), OBJECT_OT_make_links_scene(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_material_slot_add(), OBJECT_OT_material_slot_assign(), OBJECT_OT_material_slot_copy(), OBJECT_OT_material_slot_deselect(), OBJECT_OT_material_slot_remove(), OBJECT_OT_material_slot_select(), OBJECT_OT_meshdeform_bind(), OBJECT_OT_metaball_add(), OBJECT_OT_mode_set(), OBJECT_OT_modifier_add(), OBJECT_OT_modifier_apply(), OBJECT_OT_modifier_convert(), OBJECT_OT_modifier_copy(), OBJECT_OT_modifier_move_down(), OBJECT_OT_modifier_move_up(), OBJECT_OT_modifier_remove(), OBJECT_OT_move_to_layer(), OBJECT_OT_multires_base_apply(), OBJECT_OT_multires_external_pack(), OBJECT_OT_multires_external_save(), OBJECT_OT_multires_higher_levels_delete(), OBJECT_OT_multires_reshape(), OBJECT_OT_multires_subdivide(), OBJECT_OT_ocean_bake(), OBJECT_OT_origin_clear(), OBJECT_OT_origin_set(), OBJECT_OT_parent_clear(), OBJECT_OT_parent_no_inverse_set(), OBJECT_OT_parent_set(), OBJECT_OT_particle_system_add(), OBJECT_OT_particle_system_remove(), OBJECT_OT_paths_calculate(), OBJECT_OT_paths_clear(), OBJECT_OT_posemode_toggle(), OBJECT_OT_proxy_make(), OBJECT_OT_rotation_clear(), OBJECT_OT_scale_clear(), OBJECT_OT_select_all(), OBJECT_OT_select_by_layer(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_select_mirror(), OBJECT_OT_select_random(), OBJECT_OT_select_same_group(), OBJECT_OT_shade_flat(), OBJECT_OT_shade_smooth(), OBJECT_OT_shape_key_add(), OBJECT_OT_shape_key_clear(), OBJECT_OT_shape_key_mirror(), OBJECT_OT_shape_key_move(), OBJECT_OT_shape_key_remove(), OBJECT_OT_shape_key_retime(), OBJECT_OT_slow_parent_clear(), OBJECT_OT_slow_parent_set(), OBJECT_OT_speaker_add(), OBJECT_OT_text_add(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), OBJECT_OT_transform_apply(), OBJECT_OT_vertex_group_add(), OBJECT_OT_vertex_group_assign(), OBJECT_OT_vertex_group_blend(), OBJECT_OT_vertex_group_clean(), OBJECT_OT_vertex_group_copy(), OBJECT_OT_vertex_group_copy_to_linked(), OBJECT_OT_vertex_group_copy_to_selected(), OBJECT_OT_vertex_group_deselect(), OBJECT_OT_vertex_group_fix(), OBJECT_OT_vertex_group_invert(), OBJECT_OT_vertex_group_levels(), OBJECT_OT_vertex_group_lock(), OBJECT_OT_vertex_group_mirror(), OBJECT_OT_vertex_group_move(), OBJECT_OT_vertex_group_normalize(), OBJECT_OT_vertex_group_normalize_all(), OBJECT_OT_vertex_group_remove(), OBJECT_OT_vertex_group_remove_from(), OBJECT_OT_vertex_group_select(), OBJECT_OT_vertex_group_set_active(), OBJECT_OT_vertex_group_sort(), OBJECT_OT_vertex_parent_set(), OBJECT_OT_visual_transform_apply(), operator_search_cb(), OUTLINER_OT_action_set(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_drivers_add_selected(), OUTLINER_OT_drivers_delete_selected(), OUTLINER_OT_expanded_toggle(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_item_activate(), OUTLINER_OT_item_openclose(), OUTLINER_OT_item_rename(), OUTLINER_OT_keyingset_add_selected(), OUTLINER_OT_keyingset_remove_selected(), OUTLINER_OT_object_operation(), OUTLINER_OT_operation(), OUTLINER_OT_parent_clear(), OUTLINER_OT_parent_drop(), OUTLINER_OT_renderability_toggle(), OUTLINER_OT_scroll_page(), OUTLINER_OT_select_border(), OUTLINER_OT_selectability_toggle(), OUTLINER_OT_selected_toggle(), OUTLINER_OT_show_active(), OUTLINER_OT_show_hierarchy(), OUTLINER_OT_show_one_level(), OUTLINER_OT_visibility_toggle(), PAINT_OT_brush_select(), PAINT_OT_clone_cursor_set(), PAINT_OT_face_select_all(), PAINT_OT_face_select_hide(), PAINT_OT_face_select_inverse(), PAINT_OT_face_select_linked(), PAINT_OT_face_select_linked_pick(), PAINT_OT_face_select_reveal(), PAINT_OT_grab_clone(), PAINT_OT_hide_show(), PAINT_OT_image_from_view(), PAINT_OT_image_paint(), PAINT_OT_project_image(), PAINT_OT_sample_color(), PAINT_OT_texture_paint_toggle(), PAINT_OT_vert_select_all(), PAINT_OT_vert_select_inverse(), PAINT_OT_vertex_color_set(), PAINT_OT_vertex_paint(), PAINT_OT_vertex_paint_toggle(), PAINT_OT_weight_from_bones(), PAINT_OT_weight_paint(), PAINT_OT_weight_paint_toggle(), PAINT_OT_weight_sample(), PAINT_OT_weight_sample_group(), PAINT_OT_weight_set(), PARTICLE_OT_brush_edit(), PARTICLE_OT_connect_hair(), PARTICLE_OT_delete(), PARTICLE_OT_disconnect_hair(), PARTICLE_OT_dupliob_copy(), PARTICLE_OT_dupliob_move_down(), PARTICLE_OT_dupliob_move_up(), PARTICLE_OT_dupliob_remove(), PARTICLE_OT_edited_clear(), PARTICLE_OT_hide(), PARTICLE_OT_mirror(), PARTICLE_OT_new(), PARTICLE_OT_new_target(), PARTICLE_OT_particle_edit_toggle(), PARTICLE_OT_rekey(), PARTICLE_OT_remove_doubles(), PARTICLE_OT_reveal(), PARTICLE_OT_select_all(), PARTICLE_OT_select_less(), PARTICLE_OT_select_linked(), PARTICLE_OT_select_more(), PARTICLE_OT_select_roots(), PARTICLE_OT_select_tips(), PARTICLE_OT_subdivide(), PARTICLE_OT_target_move_down(), PARTICLE_OT_target_move_up(), PARTICLE_OT_target_remove(), PARTICLE_OT_weight_set(), pose_groups_menu_invoke(), POSE_OT_armature_apply(), POSE_OT_armature_layers(), POSE_OT_autoside_names(), POSE_OT_bone_layers(), POSE_OT_breakdown(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_constraints_clear(), POSE_OT_constraints_copy(), POSE_OT_copy(), POSE_OT_flip_names(), POSE_OT_group_add(), POSE_OT_group_assign(), POSE_OT_group_deselect(), POSE_OT_group_move(), POSE_OT_group_remove(), POSE_OT_group_select(), POSE_OT_group_sort(), POSE_OT_group_unassign(), POSE_OT_hide(), POSE_OT_ik_add(), POSE_OT_ik_clear(), POSE_OT_loc_clear(), POSE_OT_paste(), POSE_OT_paths_calculate(), POSE_OT_paths_clear(), POSE_OT_propagate(), POSE_OT_push(), POSE_OT_quaternions_flip(), POSE_OT_relax(), POSE_OT_reveal(), POSE_OT_rot_clear(), POSE_OT_rotation_mode_set(), POSE_OT_scale_clear(), POSE_OT_select_all(), POSE_OT_select_constraint_target(), POSE_OT_select_flip_active(), POSE_OT_select_grouped(), POSE_OT_select_hierarchy(), POSE_OT_select_linked(), POSE_OT_select_parent(), POSE_OT_transforms_clear(), POSE_OT_user_transforms_clear(), POSE_OT_visual_transform_apply(), poselib_add_menu_invoke(), POSELIB_OT_action_sanitise(), POSELIB_OT_apply_pose(), POSELIB_OT_browse_interactive(), POSELIB_OT_new(), POSELIB_OT_pose_add(), POSELIB_OT_pose_remove(), POSELIB_OT_pose_rename(), POSELIB_OT_unlink(), PTCACHE_OT_add(), PTCACHE_OT_bake(), PTCACHE_OT_bake_all(), PTCACHE_OT_bake_from_cache(), PTCACHE_OT_free_bake(), PTCACHE_OT_free_bake_all(), PTCACHE_OT_remove(), RENDER_OT_opengl(), RENDER_OT_render(), RENDER_OT_view_cancel(), RENDER_OT_view_show(), repeat_history_invoke(), SCENE_OT_delete(), SCENE_OT_new(), SCENE_OT_render_layer_add(), SCENE_OT_render_layer_remove(), screen_area_options_invoke(), SCREEN_OT_actionzone(), SCREEN_OT_animation_cancel(), SCREEN_OT_animation_play(), SCREEN_OT_animation_step(), SCREEN_OT_area_dupli(), SCREEN_OT_area_join(), SCREEN_OT_area_move(), SCREEN_OT_area_options(), SCREEN_OT_area_split(), SCREEN_OT_area_swap(), SCREEN_OT_back_to_previous(), SCREEN_OT_delete(), SCREEN_OT_frame_jump(), SCREEN_OT_frame_offset(), SCREEN_OT_header_flip(), SCREEN_OT_header_toolbox(), SCREEN_OT_keyframe_jump(), SCREEN_OT_new(), SCREEN_OT_redo_last(), SCREEN_OT_region_flip(), SCREEN_OT_region_quadview(), SCREEN_OT_region_scale(), SCREEN_OT_repeat_history(), SCREEN_OT_repeat_last(), SCREEN_OT_screen_full_area(), SCREEN_OT_screen_set(), SCREEN_OT_screencast(), SCREEN_OT_screenshot(), SCREEN_OT_spacedata_cleanup(), SCREEN_OT_userpref_show(), SCRIPT_OT_python_file_run(), SCRIPT_OT_reload(), SCULPT_OT_brush_stroke(), SCULPT_OT_sculptmode_toggle(), SCULPT_OT_set_persistent_base(), SCULPT_OT_uv_sculpt_stroke(), SEQUENCER_OT_change_effect_input(), SEQUENCER_OT_change_effect_type(), SEQUENCER_OT_change_path(), SEQUENCER_OT_copy(), SEQUENCER_OT_cut(), SEQUENCER_OT_delete(), SEQUENCER_OT_duplicate(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_images_separate(), SEQUENCER_OT_lock(), SEQUENCER_OT_meta_make(), SEQUENCER_OT_meta_separate(), SEQUENCER_OT_meta_toggle(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_mute(), SEQUENCER_OT_next_edit(), SEQUENCER_OT_offset_clear(), SEQUENCER_OT_paste(), SEQUENCER_OT_previous_edit(), SEQUENCER_OT_properties(), SEQUENCER_OT_reassign_inputs(), SEQUENCER_OT_rebuild_proxy(), SEQUENCER_OT_refresh_all(), SEQUENCER_OT_reload(), SEQUENCER_OT_rendersize(), SEQUENCER_OT_scene_strip_add(), SEQUENCER_OT_select(), SEQUENCER_OT_select_active_side(), SEQUENCER_OT_select_all(), SEQUENCER_OT_select_border(), SEQUENCER_OT_select_grouped(), SEQUENCER_OT_select_handles(), SEQUENCER_OT_select_inverse(), SEQUENCER_OT_select_less(), SEQUENCER_OT_select_linked(), SEQUENCER_OT_select_linked_pick(), SEQUENCER_OT_select_more(), SEQUENCER_OT_snap(), SEQUENCER_OT_sound_strip_add(), SEQUENCER_OT_swap(), SEQUENCER_OT_swap_data(), SEQUENCER_OT_swap_inputs(), SEQUENCER_OT_unlock(), SEQUENCER_OT_unmute(), SEQUENCER_OT_view_all(), SEQUENCER_OT_view_all_preview(), SEQUENCER_OT_view_ghost_border(), SEQUENCER_OT_view_selected(), SEQUENCER_OT_view_toggle(), SEQUENCER_OT_view_zoom_ratio(), SKETCH_OT_cancel_stroke(), SKETCH_OT_convert(), SKETCH_OT_delete(), SKETCH_OT_draw_preview(), SKETCH_OT_draw_stroke(), SKETCH_OT_finish_stroke(), SKETCH_OT_gesture(), SKETCH_OT_select(), SOUND_OT_bake_animation(), SOUND_OT_mixdown(), SOUND_OT_open(), SOUND_OT_open_mono(), SOUND_OT_pack(), SOUND_OT_unpack(), SOUND_OT_update_animation_flags(), SURFACE_OT_primitive_nurbs_surface_circle_add(), SURFACE_OT_primitive_nurbs_surface_curve_add(), SURFACE_OT_primitive_nurbs_surface_cylinder_add(), SURFACE_OT_primitive_nurbs_surface_sphere_add(), SURFACE_OT_primitive_nurbs_surface_surface_add(), SURFACE_OT_primitive_nurbs_surface_torus_add(), TEXT_OT_comment(), TEXT_OT_convert_whitespace(), TEXT_OT_copy(), TEXT_OT_cursor_set(), TEXT_OT_cut(), TEXT_OT_delete(), TEXT_OT_find(), TEXT_OT_find_set_selected(), TEXT_OT_indent(), TEXT_OT_insert(), TEXT_OT_jump(), TEXT_OT_line_break(), TEXT_OT_line_number(), TEXT_OT_make_internal(), TEXT_OT_mark_all(), TEXT_OT_markers_clear(), TEXT_OT_move(), TEXT_OT_move_select(), TEXT_OT_new(), TEXT_OT_next_marker(), TEXT_OT_open(), TEXT_OT_overwrite_toggle(), TEXT_OT_paste(), TEXT_OT_previous_marker(), TEXT_OT_properties(), TEXT_OT_refresh_pyconstraints(), TEXT_OT_reload(), TEXT_OT_replace(), TEXT_OT_replace_set_selected(), TEXT_OT_resolve_conflict(), TEXT_OT_run_script(), TEXT_OT_save(), TEXT_OT_save_as(), TEXT_OT_scroll(), TEXT_OT_scroll_bar(), TEXT_OT_select_all(), TEXT_OT_select_line(), TEXT_OT_select_word(), TEXT_OT_selection_set(), TEXT_OT_to_3d_object(), TEXT_OT_uncomment(), TEXT_OT_unindent(), TEXT_OT_unlink(), TEXTURE_OT_envmap_clear(), TEXTURE_OT_envmap_clear_all(), TEXTURE_OT_envmap_save(), TEXTURE_OT_new(), TEXTURE_OT_slot_copy(), TEXTURE_OT_slot_move(), TEXTURE_OT_slot_paste(), texture_paint_camera_project_exec(), texture_paint_init(), TIME_OT_end_frame_set(), TIME_OT_start_frame_set(), TIME_OT_view_all(), TRANSFORM_OT_create_orientation(), TRANSFORM_OT_delete_orientation(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_select_orientation(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_snap_type(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), TRANSFORM_OT_warp(), ui_but_menu(), ui_def_but_operator_text(), UI_OT_copy_data_path_button(), UI_OT_copy_to_selected_button(), UI_OT_eyedropper(), UI_OT_reports_to_textblock(), UI_OT_reset_default_button(), UI_OT_reset_default_theme(), UV_OT_align(), UV_OT_average_islands_scale(), UV_OT_circle_select(), UV_OT_cube_project(), UV_OT_cursor_set(), UV_OT_cylinder_project(), UV_OT_from_view(), UV_OT_hide(), UV_OT_mark_seam(), UV_OT_minimize_stretch(), UV_OT_pack_islands(), UV_OT_pin(), UV_OT_reset(), UV_OT_reveal(), UV_OT_seams_from_islands(), UV_OT_select(), UV_OT_select_all(), UV_OT_select_border(), UV_OT_select_linked(), UV_OT_select_linked_pick(), UV_OT_select_loop(), UV_OT_select_pinned(), UV_OT_snap_cursor(), UV_OT_snap_selected(), UV_OT_sphere_project(), UV_OT_stitch(), UV_OT_tile_set(), UV_OT_unlink_selected(), UV_OT_unwrap(), UV_OT_weld(), VIEW2D_OT_pan(), VIEW2D_OT_reset(), VIEW2D_OT_scroll_down(), VIEW2D_OT_scroll_left(), VIEW2D_OT_scroll_right(), VIEW2D_OT_scroll_up(), VIEW2D_OT_scroller_activate(), VIEW2D_OT_zoom(), VIEW2D_OT_zoom_border(), VIEW2D_OT_zoom_in(), VIEW2D_OT_zoom_out(), VIEW3D_OT_background_image_add(), VIEW3D_OT_background_image_remove(), VIEW3D_OT_camera_to_view(), VIEW3D_OT_camera_to_view_selected(), VIEW3D_OT_clip_border(), VIEW3D_OT_cursor3d(), VIEW3D_OT_dolly(), VIEW3D_OT_enable_manipulator(), VIEW3D_OT_fly(), VIEW3D_OT_game_start(), VIEW3D_OT_layers(), VIEW3D_OT_localview(), VIEW3D_OT_manipulator(), VIEW3D_OT_move(), VIEW3D_OT_ndof_orbit(), VIEW3D_OT_ndof_pan(), VIEW3D_OT_object_as_camera(), VIEW3D_OT_properties(), VIEW3D_OT_render_border(), VIEW3D_OT_rotate(), VIEW3D_OT_select(), VIEW3D_OT_select_border(), VIEW3D_OT_select_circle(), VIEW3D_OT_select_lasso(), VIEW3D_OT_select_menu(), VIEW3D_OT_smoothview(), VIEW3D_OT_snap_cursor_to_active(), VIEW3D_OT_snap_cursor_to_center(), VIEW3D_OT_snap_cursor_to_grid(), VIEW3D_OT_snap_cursor_to_selected(), VIEW3D_OT_snap_selected_to_cursor(), VIEW3D_OT_snap_selected_to_grid(), VIEW3D_OT_toolshelf(), VIEW3D_OT_view_all(), VIEW3D_OT_view_center_camera(), VIEW3D_OT_view_center_cursor(), VIEW3D_OT_view_orbit(), VIEW3D_OT_view_pan(), VIEW3D_OT_view_persportho(), VIEW3D_OT_view_selected(), VIEW3D_OT_viewnumpad(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), VIEW3D_OT_zoom_camera_1_to_1(), view3d_panel_operator_redo(), view3d_panel_operator_redo_header(), view3d_panel_operator_redo_operator(), wm_block_create_redo(), WM_operator_call_py(), WM_operatortype_append(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), WM_operatortype_append_ptr(), WM_operatortype_macro_define(), WM_OT_call_menu(), WM_OT_debug_menu(), WM_OT_dependency_relations(), WM_OT_link_append(), WM_OT_memory_statistics(), WM_OT_ndof_sensitivity_change(), WM_OT_open_mainfile(), WM_OT_quit_blender(), WM_OT_radial_control(), WM_OT_read_factory_settings(), WM_OT_read_homefile(), WM_OT_recover_auto_save(), WM_OT_recover_last_session(), WM_OT_redraw_timer(), WM_OT_save_as_mainfile(), WM_OT_save_homefile(), WM_OT_save_mainfile(), WM_OT_search_menu(), WM_OT_splash(), WM_OT_window_duplicate(), WM_OT_window_fullscreen_toggle(), and WORLD_OT_new().
int(* wmOperatorType::poll)(struct bContext *)
Definition at line 458 of file WM_types.h.
Referenced by ACTION_OT_clean(), ACTION_OT_clickselect(), ACTION_OT_copy(), ACTION_OT_delete(), ACTION_OT_duplicate(), ACTION_OT_extrapolation_type(), ACTION_OT_frame_jump(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_markers_make_local(), ACTION_OT_mirror(), ACTION_OT_paste(), ACTION_OT_previewrange_set(), ACTION_OT_sample(), ACTION_OT_select_all_toggle(), ACTION_OT_select_border(), ACTION_OT_select_column(), ACTION_OT_select_leftright(), ACTION_OT_select_less(), ACTION_OT_select_linked(), ACTION_OT_select_more(), ACTION_OT_snap(), ACTION_OT_view_all(), ACTION_OT_view_selected(), ANIM_OT_change_frame(), ANIM_OT_channels_click(), ANIM_OT_channels_collapse(), ANIM_OT_channels_delete(), ANIM_OT_channels_editable_toggle(), ANIM_OT_channels_expand(), ANIM_OT_channels_fcurves_enable(), ANIM_OT_channels_move(), ANIM_OT_channels_rename(), ANIM_OT_channels_select_all_toggle(), ANIM_OT_channels_select_border(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), ANIM_OT_channels_setting_toggle(), ANIM_OT_channels_visibility_set(), ANIM_OT_channels_visibility_toggle(), ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_delete_button(), ANIM_OT_keyframe_delete_v3d(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_button(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_active_set(), ANIM_OT_keying_set_add(), ANIM_OT_keying_set_path_add(), ANIM_OT_keying_set_path_remove(), ANIM_OT_keying_set_remove(), ANIM_OT_previewrange_clear(), ANIM_OT_previewrange_set(), ARMATURE_OT_align(), ARMATURE_OT_armature_layers(), ARMATURE_OT_autoside_names(), ARMATURE_OT_bone_layers(), ARMATURE_OT_bone_primitive_add(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_click_extrude(), ARMATURE_OT_delete(), ARMATURE_OT_duplicate(), ARMATURE_OT_extrude(), ARMATURE_OT_fill(), ARMATURE_OT_flip_names(), ARMATURE_OT_hide(), ARMATURE_OT_layers_show_all(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), ARMATURE_OT_parent_set(), ARMATURE_OT_reveal(), ARMATURE_OT_select_all(), ARMATURE_OT_select_hierarchy(), ARMATURE_OT_select_inverse(), ARMATURE_OT_select_linked(), ARMATURE_OT_separate(), ARMATURE_OT_subdivide(), ARMATURE_OT_switch_direction(), BRUSH_OT_curve_preset(), BRUSH_OT_uv_sculpt_tool_set(), BUTTONS_OT_toolbox(), CLIP_OT_add_marker(), CLIP_OT_change_frame(), CLIP_OT_clean_tracks(), CLIP_OT_clear_solution(), CLIP_OT_clear_track_path(), CLIP_OT_copy_tracks(), CLIP_OT_delete_marker(), CLIP_OT_delete_track(), CLIP_OT_detect_features(), CLIP_OT_disable_markers(), CLIP_OT_frame_jump(), CLIP_OT_graph_center_current_frame(), CLIP_OT_graph_delete_curve(), CLIP_OT_graph_delete_knot(), CLIP_OT_graph_disable_markers(), CLIP_OT_graph_select(), CLIP_OT_graph_select_all_markers(), CLIP_OT_graph_select_border(), CLIP_OT_graph_view_all(), CLIP_OT_hide_tracks(), CLIP_OT_hide_tracks_clear(), CLIP_OT_join_tracks(), CLIP_OT_lock_tracks(), CLIP_OT_mode_set(), CLIP_OT_paste_tracks(), CLIP_OT_properties(), CLIP_OT_rebuild_proxy(), CLIP_OT_select(), CLIP_OT_select_all(), CLIP_OT_select_border(), CLIP_OT_select_circle(), CLIP_OT_select_grouped(), CLIP_OT_set_axis(), CLIP_OT_set_center_principal(), CLIP_OT_set_origin(), CLIP_OT_set_plane(), CLIP_OT_set_scale(), CLIP_OT_set_solution_scale(), CLIP_OT_slide_marker(), CLIP_OT_solve_camera(), CLIP_OT_stabilize_2d_add(), CLIP_OT_stabilize_2d_remove(), CLIP_OT_stabilize_2d_select(), CLIP_OT_stabilize_2d_set_rotation(), CLIP_OT_tools(), CLIP_OT_track_copy_color(), CLIP_OT_track_markers(), CLIP_OT_tracking_object_new(), CLIP_OT_tracking_object_remove(), CLIP_OT_view_all(), CLIP_OT_view_pan(), CLIP_OT_view_selected(), CLIP_OT_view_zoom(), CLIP_OT_view_zoom_in(), CLIP_OT_view_zoom_out(), CLIP_OT_view_zoom_ratio(), CONSOLE_OT_clear(), CONSOLE_OT_copy(), CONSOLE_OT_delete(), CONSOLE_OT_history_append(), CONSOLE_OT_history_cycle(), CONSOLE_OT_insert(), CONSOLE_OT_move(), CONSOLE_OT_paste(), CONSOLE_OT_scrollback_append(), CONSOLE_OT_select_set(), CONSTRAINT_OT_childof_clear_inverse(), CONSTRAINT_OT_childof_set_inverse(), CONSTRAINT_OT_delete(), CONSTRAINT_OT_limitdistance_reset(), CONSTRAINT_OT_move_down(), CONSTRAINT_OT_move_up(), CONSTRAINT_OT_objectsolver_clear_inverse(), CONSTRAINT_OT_objectsolver_set_inverse(), CONSTRAINT_OT_stretchto_reset(), CURVE_OT_cyclic_toggle(), CURVE_OT_de_select_first(), CURVE_OT_de_select_last(), CURVE_OT_delete(), CURVE_OT_duplicate(), CURVE_OT_extrude(), CURVE_OT_handle_type_set(), CURVE_OT_hide(), CURVE_OT_make_segment(), CURVE_OT_primitive_bezier_circle_add(), CURVE_OT_primitive_bezier_curve_add(), CURVE_OT_primitive_nurbs_circle_add(), CURVE_OT_primitive_nurbs_curve_add(), CURVE_OT_primitive_nurbs_path_add(), CURVE_OT_radius_set(), CURVE_OT_reveal(), CURVE_OT_select_all(), CURVE_OT_select_less(), CURVE_OT_select_linked(), CURVE_OT_select_linked_pick(), CURVE_OT_select_more(), CURVE_OT_select_next(), CURVE_OT_select_nth(), CURVE_OT_select_previous(), CURVE_OT_select_random(), CURVE_OT_select_row(), CURVE_OT_separate(), CURVE_OT_shade_flat(), CURVE_OT_shade_smooth(), CURVE_OT_smooth(), CURVE_OT_smooth_radius(), CURVE_OT_spin(), CURVE_OT_spline_type_set(), CURVE_OT_spline_weight_set(), CURVE_OT_subdivide(), CURVE_OT_switch_direction(), CURVE_OT_tilt_clear(), CURVE_OT_vertex_add(), DPAINT_OT_bake(), DPAINT_OT_output_toggle(), DPAINT_OT_surface_slot_add(), DPAINT_OT_surface_slot_remove(), DPAINT_OT_type_toggle(), ED_OT_redo(), ED_OT_undo(), ED_OT_undo_history(), FILE_OT_bookmark_add(), FILE_OT_bookmark_toggle(), FILE_OT_cancel(), FILE_OT_delete(), FILE_OT_delete_bookmark(), FILE_OT_directory(), FILE_OT_directory_new(), FILE_OT_execute(), FILE_OT_filenum(), FILE_OT_hidedot(), FILE_OT_highlight(), FILE_OT_next(), FILE_OT_parent(), FILE_OT_previous(), FILE_OT_refresh(), FILE_OT_rename(), FILE_OT_select(), FILE_OT_select_all_toggle(), FILE_OT_select_bookmark(), FILE_OT_select_border(), FILE_OT_smoothscroll(), FONT_OT_case_set(), FONT_OT_case_toggle(), FONT_OT_change_character(), FONT_OT_change_spacing(), FONT_OT_delete(), FONT_OT_file_paste(), FONT_OT_insert_lorem(), FONT_OT_line_break(), FONT_OT_move(), FONT_OT_move_select(), FONT_OT_style_set(), FONT_OT_style_toggle(), FONT_OT_text_copy(), FONT_OT_text_cut(), FONT_OT_text_insert(), FONT_OT_text_paste(), FONT_OT_textbox_add(), FONT_OT_textbox_remove(), GPENCIL_OT_active_frame_delete(), GPENCIL_OT_convert(), GPENCIL_OT_data_add(), GPENCIL_OT_data_unlink(), GPENCIL_OT_draw(), GPENCIL_OT_layer_add(), GRAPH_OT_bake(), GRAPH_OT_clean(), GRAPH_OT_click_insert(), GRAPH_OT_clickselect(), GRAPH_OT_copy(), GRAPH_OT_cursor_set(), GRAPH_OT_delete(), GRAPH_OT_duplicate(), GRAPH_OT_euler_filter(), GRAPH_OT_extrapolation_type(), GRAPH_OT_fmodifier_add(), GRAPH_OT_fmodifier_copy(), GRAPH_OT_fmodifier_paste(), GRAPH_OT_frame_jump(), GRAPH_OT_ghost_curves_clear(), GRAPH_OT_ghost_curves_create(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_paste(), GRAPH_OT_previewrange_set(), GRAPH_OT_properties(), GRAPH_OT_sample(), GRAPH_OT_select_all_toggle(), GRAPH_OT_select_border(), GRAPH_OT_select_column(), GRAPH_OT_select_leftright(), GRAPH_OT_select_less(), GRAPH_OT_select_linked(), GRAPH_OT_select_more(), GRAPH_OT_smooth(), GRAPH_OT_snap(), GRAPH_OT_sound_bake(), GRAPH_OT_view_all(), GRAPH_OT_view_selected(), GROUP_OT_create(), GROUP_OT_objects_add_active(), GROUP_OT_objects_remove(), GROUP_OT_objects_remove_active(), IMAGE_OT_curves_point_set(), IMAGE_OT_cycle_render_slot(), IMAGE_OT_invert(), IMAGE_OT_properties(), IMAGE_OT_record_composite(), IMAGE_OT_replace(), IMAGE_OT_sample(), IMAGE_OT_sample_line(), IMAGE_OT_save(), IMAGE_OT_save_as(), IMAGE_OT_save_sequence(), IMAGE_OT_scopes(), IMAGE_OT_view_all(), IMAGE_OT_view_pan(), IMAGE_OT_view_selected(), IMAGE_OT_view_zoom(), IMAGE_OT_view_zoom_in(), IMAGE_OT_view_zoom_out(), IMAGE_OT_view_zoom_ratio(), INFO_OT_report_copy(), INFO_OT_report_delete(), INFO_OT_report_replay(), INFO_OT_select_all_toggle(), INFO_OT_select_border(), INFO_OT_select_pick(), LATTICE_OT_make_regular(), LATTICE_OT_select_all(), LOGIC_OT_actuator_add(), LOGIC_OT_actuator_move(), LOGIC_OT_actuator_remove(), LOGIC_OT_controller_add(), LOGIC_OT_controller_move(), LOGIC_OT_controller_remove(), LOGIC_OT_links_cut(), LOGIC_OT_properties(), LOGIC_OT_sensor_add(), LOGIC_OT_sensor_move(), LOGIC_OT_sensor_remove(), MARKER_OT_add(), MARKER_OT_delete(), MARKER_OT_duplicate(), MARKER_OT_make_links_scene(), MARKER_OT_move(), MARKER_OT_rename(), MARKER_OT_select(), MARKER_OT_select_all(), MARKER_OT_select_border(), MBALL_OT_delete_metaelems(), MBALL_OT_duplicate_metaelems(), MBALL_OT_hide_metaelems(), MBALL_OT_reveal_metaelems(), MBALL_OT_select_all(), MBALL_OT_select_random_metaelems(), MESH_OT_beautify_fill(), MESH_OT_bevel(), MESH_OT_blend_from_shape(), MESH_OT_bridge_edge_loops(), MESH_OT_colors_reverse(), MESH_OT_colors_rotate(), MESH_OT_delete(), MESH_OT_dissolve(), MESH_OT_dissolve_limited(), MESH_OT_drop_named_image(), MESH_OT_dupli_extrude_cursor(), MESH_OT_duplicate(), MESH_OT_edge_collapse(), MESH_OT_edge_collapse_loop(), MESH_OT_edge_face_add(), MESH_OT_edge_rotate(), MESH_OT_edge_split(), MESH_OT_edgering_select(), MESH_OT_edges_select_sharp(), MESH_OT_extrude_edges_indiv(), MESH_OT_extrude_faces_indiv(), MESH_OT_extrude_region(), MESH_OT_extrude_repeat(), MESH_OT_extrude_verts_indiv(), MESH_OT_faces_select_linked_flat(), MESH_OT_faces_shade_flat(), MESH_OT_faces_shade_smooth(), MESH_OT_fill(), MESH_OT_flip_normals(), MESH_OT_hide(), MESH_OT_inset(), MESH_OT_knife_cut(), MESH_OT_knife_tool(), MESH_OT_loop_multi_select(), MESH_OT_loop_select(), MESH_OT_loop_to_region(), MESH_OT_loopcut(), MESH_OT_mark_seam(), MESH_OT_mark_sharp(), MESH_OT_merge(), MESH_OT_navmesh_clear(), MESH_OT_navmesh_face_add(), MESH_OT_navmesh_face_copy(), MESH_OT_navmesh_reset(), MESH_OT_noise(), MESH_OT_normals_make_consistent(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cube_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_monkey_add(), MESH_OT_primitive_plane_add(), MESH_OT_primitive_uv_sphere_add(), MESH_OT_quads_convert_to_tris(), MESH_OT_region_to_loop(), MESH_OT_remove_doubles(), MESH_OT_reveal(), MESH_OT_rip(), MESH_OT_screw(), MESH_OT_select_all(), MESH_OT_select_axis(), MESH_OT_select_by_number_vertices(), MESH_OT_select_interior_faces(), MESH_OT_select_less(), MESH_OT_select_linked(), MESH_OT_select_linked_pick(), MESH_OT_select_loose_verts(), MESH_OT_select_mirror(), MESH_OT_select_more(), MESH_OT_select_next_loop(), MESH_OT_select_non_manifold(), MESH_OT_select_nth(), MESH_OT_select_random(), MESH_OT_select_shortest_path(), MESH_OT_select_similar(), MESH_OT_select_vertex_path(), MESH_OT_separate(), MESH_OT_shape_propagate_to_all(), MESH_OT_solidify(), MESH_OT_sort_faces(), MESH_OT_spin(), MESH_OT_split(), MESH_OT_sticky_add(), MESH_OT_sticky_remove(), MESH_OT_subdivide(), MESH_OT_tris_convert_to_quads(), MESH_OT_uv_texture_add(), MESH_OT_uv_texture_remove(), MESH_OT_uvs_reverse(), MESH_OT_uvs_rotate(), MESH_OT_vert_connect(), MESH_OT_vert_slide(), MESH_OT_vertex_color_add(), MESH_OT_vertex_color_remove(), MESH_OT_vertices_randomize(), MESH_OT_vertices_smooth(), MESH_OT_vertices_sort(), NLA_OT_action_sync_length(), NLA_OT_actionclip_add(), NLA_OT_apply_scale(), NLA_OT_bake(), NLA_OT_channels_click(), NLA_OT_clear_scale(), NLA_OT_click_select(), NLA_OT_delete(), NLA_OT_delete_tracks(), NLA_OT_duplicate(), NLA_OT_fmodifier_add(), NLA_OT_fmodifier_copy(), NLA_OT_fmodifier_paste(), NLA_OT_meta_add(), NLA_OT_meta_remove(), NLA_OT_move_down(), NLA_OT_move_up(), NLA_OT_mute_toggle(), NLA_OT_properties(), NLA_OT_select_all_toggle(), NLA_OT_select_border(), NLA_OT_select_leftright(), NLA_OT_snap(), NLA_OT_soundclip_add(), NLA_OT_split(), NLA_OT_swap(), NLA_OT_tracks_add(), NLA_OT_transition_add(), NLA_OT_tweakmode_enter(), NLA_OT_tweakmode_exit(), NLA_OT_view_all(), NLA_OT_view_selected(), NODE_OT_add_file(), NODE_OT_backimage_move(), NODE_OT_backimage_sample(), NODE_OT_backimage_zoom(), NODE_OT_delete(), NODE_OT_delete_reconnect(), NODE_OT_duplicate(), NODE_OT_group_edit(), NODE_OT_group_make(), NODE_OT_group_socket_add(), NODE_OT_group_socket_move_down(), NODE_OT_group_socket_move_up(), NODE_OT_group_socket_remove(), NODE_OT_group_ungroup(), NODE_OT_hide_socket_toggle(), NODE_OT_hide_toggle(), NODE_OT_link(), NODE_OT_link_make(), NODE_OT_link_viewer(), NODE_OT_links_cut(), NODE_OT_links_detach(), NODE_OT_mute_toggle(), NODE_OT_new_node_tree(), NODE_OT_options_toggle(), NODE_OT_output_file_add_socket(), NODE_OT_output_file_remove_active_socket(), NODE_OT_preview_toggle(), NODE_OT_properties(), NODE_OT_read_fullsamplelayers(), NODE_OT_read_renderlayers(), NODE_OT_render_changed(), NODE_OT_resize(), NODE_OT_select(), NODE_OT_select_all(), NODE_OT_select_border(), NODE_OT_select_linked_from(), NODE_OT_select_linked_to(), NODE_OT_select_same_type(), NODE_OT_select_same_type_next(), NODE_OT_select_same_type_prev(), NODE_OT_show_cyclic_dependencies(), NODE_OT_view_all(), OBJECT_OT_add(), OBJECT_OT_add_named(), OBJECT_OT_armature_add(), OBJECT_OT_camera_add(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_constraints_clear(), OBJECT_OT_constraints_copy(), OBJECT_OT_convert(), OBJECT_OT_delete(), OBJECT_OT_drop_named_material(), OBJECT_OT_duplicate(), OBJECT_OT_duplicates_make_real(), OBJECT_OT_editmode_toggle(), OBJECT_OT_effector_add(), OBJECT_OT_explode_refresh(), OBJECT_OT_forcefield_toggle(), OBJECT_OT_game_physics_copy(), OBJECT_OT_game_property_clear(), OBJECT_OT_game_property_copy(), OBJECT_OT_game_property_new(), OBJECT_OT_game_property_remove(), OBJECT_OT_group_instance_add(), OBJECT_OT_hide_render_clear(), OBJECT_OT_hide_render_set(), OBJECT_OT_hide_view_clear(), OBJECT_OT_hide_view_set(), OBJECT_OT_hook_add_newobj(), OBJECT_OT_hook_add_selobj(), OBJECT_OT_hook_assign(), OBJECT_OT_hook_recenter(), OBJECT_OT_hook_remove(), OBJECT_OT_hook_reset(), OBJECT_OT_hook_select(), OBJECT_OT_join(), OBJECT_OT_join_shapes(), OBJECT_OT_lamp_add(), OBJECT_OT_location_clear(), OBJECT_OT_logic_bricks_copy(), OBJECT_OT_make_links_data(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_material_slot_add(), OBJECT_OT_material_slot_assign(), OBJECT_OT_material_slot_remove(), OBJECT_OT_meshdeform_bind(), OBJECT_OT_metaball_add(), OBJECT_OT_mode_set(), OBJECT_OT_modifier_add(), OBJECT_OT_modifier_apply(), OBJECT_OT_modifier_convert(), OBJECT_OT_modifier_copy(), OBJECT_OT_modifier_move_down(), OBJECT_OT_modifier_move_up(), OBJECT_OT_modifier_remove(), OBJECT_OT_move_to_layer(), OBJECT_OT_multires_base_apply(), OBJECT_OT_multires_external_pack(), OBJECT_OT_multires_external_save(), OBJECT_OT_multires_higher_levels_delete(), OBJECT_OT_multires_reshape(), OBJECT_OT_multires_subdivide(), OBJECT_OT_ocean_bake(), OBJECT_OT_origin_clear(), OBJECT_OT_origin_set(), OBJECT_OT_parent_clear(), OBJECT_OT_parent_no_inverse_set(), OBJECT_OT_parent_set(), OBJECT_OT_particle_system_add(), OBJECT_OT_particle_system_remove(), OBJECT_OT_paths_calculate(), OBJECT_OT_paths_clear(), OBJECT_OT_posemode_toggle(), OBJECT_OT_proxy_make(), OBJECT_OT_rotation_clear(), OBJECT_OT_scale_clear(), OBJECT_OT_select_all(), OBJECT_OT_select_by_layer(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_select_mirror(), OBJECT_OT_select_random(), OBJECT_OT_select_same_group(), OBJECT_OT_shade_flat(), OBJECT_OT_shade_smooth(), OBJECT_OT_shape_key_add(), OBJECT_OT_shape_key_clear(), OBJECT_OT_shape_key_mirror(), OBJECT_OT_shape_key_move(), OBJECT_OT_shape_key_remove(), OBJECT_OT_shape_key_retime(), OBJECT_OT_slow_parent_clear(), OBJECT_OT_slow_parent_set(), OBJECT_OT_speaker_add(), OBJECT_OT_text_add(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), OBJECT_OT_transform_apply(), OBJECT_OT_vertex_group_add(), OBJECT_OT_vertex_group_assign(), OBJECT_OT_vertex_group_blend(), OBJECT_OT_vertex_group_clean(), OBJECT_OT_vertex_group_copy(), OBJECT_OT_vertex_group_copy_to_linked(), OBJECT_OT_vertex_group_copy_to_selected(), OBJECT_OT_vertex_group_deselect(), OBJECT_OT_vertex_group_fix(), OBJECT_OT_vertex_group_invert(), OBJECT_OT_vertex_group_levels(), OBJECT_OT_vertex_group_lock(), OBJECT_OT_vertex_group_mirror(), OBJECT_OT_vertex_group_move(), OBJECT_OT_vertex_group_normalize(), OBJECT_OT_vertex_group_normalize_all(), OBJECT_OT_vertex_group_remove(), OBJECT_OT_vertex_group_remove_from(), OBJECT_OT_vertex_group_select(), OBJECT_OT_vertex_group_set_active(), OBJECT_OT_vertex_group_sort(), OBJECT_OT_vertex_parent_set(), OBJECT_OT_visual_transform_apply(), OUTLINER_OT_action_set(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_drivers_add_selected(), OUTLINER_OT_drivers_delete_selected(), OUTLINER_OT_expanded_toggle(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_item_activate(), OUTLINER_OT_item_openclose(), OUTLINER_OT_item_rename(), OUTLINER_OT_keyingset_add_selected(), OUTLINER_OT_keyingset_remove_selected(), OUTLINER_OT_object_operation(), OUTLINER_OT_operation(), OUTLINER_OT_parent_clear(), OUTLINER_OT_parent_drop(), OUTLINER_OT_renderability_toggle(), OUTLINER_OT_scroll_page(), OUTLINER_OT_select_border(), OUTLINER_OT_selectability_toggle(), OUTLINER_OT_selected_toggle(), OUTLINER_OT_show_active(), OUTLINER_OT_show_hierarchy(), OUTLINER_OT_show_one_level(), OUTLINER_OT_visibility_toggle(), PAINT_OT_clone_cursor_set(), PAINT_OT_face_select_all(), PAINT_OT_face_select_hide(), PAINT_OT_face_select_inverse(), PAINT_OT_face_select_linked(), PAINT_OT_face_select_linked_pick(), PAINT_OT_face_select_reveal(), PAINT_OT_grab_clone(), PAINT_OT_hide_show(), PAINT_OT_image_from_view(), PAINT_OT_image_paint(), PAINT_OT_sample_color(), PAINT_OT_texture_paint_toggle(), PAINT_OT_vert_select_all(), PAINT_OT_vert_select_inverse(), PAINT_OT_vertex_color_set(), PAINT_OT_vertex_paint(), PAINT_OT_vertex_paint_toggle(), PAINT_OT_weight_from_bones(), PAINT_OT_weight_paint(), PAINT_OT_weight_paint_toggle(), PAINT_OT_weight_sample(), PAINT_OT_weight_sample_group(), PAINT_OT_weight_set(), PARTICLE_OT_brush_edit(), PARTICLE_OT_delete(), PARTICLE_OT_edited_clear(), PARTICLE_OT_hide(), PARTICLE_OT_mirror(), PARTICLE_OT_new(), PARTICLE_OT_particle_edit_toggle(), PARTICLE_OT_rekey(), PARTICLE_OT_remove_doubles(), PARTICLE_OT_reveal(), PARTICLE_OT_select_all(), PARTICLE_OT_select_less(), PARTICLE_OT_select_linked(), PARTICLE_OT_select_more(), PARTICLE_OT_select_roots(), PARTICLE_OT_select_tips(), PARTICLE_OT_subdivide(), PARTICLE_OT_weight_set(), POSE_OT_armature_apply(), POSE_OT_armature_layers(), POSE_OT_autoside_names(), POSE_OT_bone_layers(), POSE_OT_breakdown(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_constraints_clear(), POSE_OT_constraints_copy(), POSE_OT_copy(), POSE_OT_flip_names(), POSE_OT_group_add(), POSE_OT_group_assign(), POSE_OT_group_deselect(), POSE_OT_group_move(), POSE_OT_group_remove(), POSE_OT_group_select(), POSE_OT_group_sort(), POSE_OT_group_unassign(), POSE_OT_hide(), POSE_OT_ik_add(), POSE_OT_ik_clear(), POSE_OT_loc_clear(), POSE_OT_paste(), POSE_OT_paths_calculate(), POSE_OT_paths_clear(), POSE_OT_propagate(), POSE_OT_push(), POSE_OT_quaternions_flip(), POSE_OT_relax(), POSE_OT_reveal(), POSE_OT_rot_clear(), POSE_OT_rotation_mode_set(), POSE_OT_scale_clear(), POSE_OT_select_all(), POSE_OT_select_constraint_target(), POSE_OT_select_flip_active(), POSE_OT_select_grouped(), POSE_OT_select_hierarchy(), POSE_OT_select_linked(), POSE_OT_select_parent(), POSE_OT_transforms_clear(), POSE_OT_user_transforms_clear(), POSE_OT_visual_transform_apply(), POSELIB_OT_action_sanitise(), POSELIB_OT_apply_pose(), POSELIB_OT_browse_interactive(), POSELIB_OT_new(), POSELIB_OT_pose_add(), POSELIB_OT_pose_remove(), POSELIB_OT_pose_rename(), POSELIB_OT_unlink(), PTCACHE_OT_add(), PTCACHE_OT_bake(), PTCACHE_OT_bake_all(), PTCACHE_OT_bake_from_cache(), PTCACHE_OT_free_bake(), PTCACHE_OT_free_bake_all(), PTCACHE_OT_remove(), radial_control_invoke(), RENDER_OT_opengl(), RENDER_OT_view_cancel(), RENDER_OT_view_show(), SCREEN_OT_actionzone(), SCREEN_OT_animation_cancel(), SCREEN_OT_animation_play(), SCREEN_OT_animation_step(), SCREEN_OT_area_dupli(), SCREEN_OT_area_join(), SCREEN_OT_area_move(), SCREEN_OT_area_options(), SCREEN_OT_area_split(), SCREEN_OT_area_swap(), SCREEN_OT_back_to_previous(), SCREEN_OT_frame_jump(), SCREEN_OT_frame_offset(), SCREEN_OT_header_flip(), SCREEN_OT_keyframe_jump(), SCREEN_OT_new(), SCREEN_OT_redo_last(), SCREEN_OT_region_flip(), SCREEN_OT_region_quadview(), SCREEN_OT_region_scale(), SCREEN_OT_repeat_history(), SCREEN_OT_repeat_last(), SCREEN_OT_screen_full_area(), SCREEN_OT_screen_set(), SCREEN_OT_screencast(), SCREEN_OT_screenshot(), SCREEN_OT_spacedata_cleanup(), SCREEN_OT_userpref_show(), SCRIPT_OT_python_file_run(), SCULPT_OT_brush_stroke(), SCULPT_OT_sculptmode_toggle(), SCULPT_OT_set_persistent_base(), SCULPT_OT_uv_sculpt_stroke(), SEQUENCER_OT_change_effect_input(), SEQUENCER_OT_change_effect_type(), SEQUENCER_OT_change_path(), SEQUENCER_OT_copy(), SEQUENCER_OT_cut(), SEQUENCER_OT_delete(), SEQUENCER_OT_duplicate(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_images_separate(), SEQUENCER_OT_lock(), SEQUENCER_OT_meta_make(), SEQUENCER_OT_meta_separate(), SEQUENCER_OT_meta_toggle(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_mute(), SEQUENCER_OT_next_edit(), SEQUENCER_OT_offset_clear(), SEQUENCER_OT_paste(), SEQUENCER_OT_previous_edit(), SEQUENCER_OT_properties(), SEQUENCER_OT_reassign_inputs(), SEQUENCER_OT_rebuild_proxy(), SEQUENCER_OT_refresh_all(), SEQUENCER_OT_reload(), SEQUENCER_OT_rendersize(), SEQUENCER_OT_scene_strip_add(), SEQUENCER_OT_select(), SEQUENCER_OT_select_active_side(), SEQUENCER_OT_select_all(), SEQUENCER_OT_select_border(), SEQUENCER_OT_select_grouped(), SEQUENCER_OT_select_handles(), SEQUENCER_OT_select_inverse(), SEQUENCER_OT_select_less(), SEQUENCER_OT_select_linked(), SEQUENCER_OT_select_linked_pick(), SEQUENCER_OT_select_more(), SEQUENCER_OT_snap(), SEQUENCER_OT_sound_strip_add(), SEQUENCER_OT_swap(), SEQUENCER_OT_swap_data(), SEQUENCER_OT_swap_inputs(), SEQUENCER_OT_unlock(), SEQUENCER_OT_unmute(), SEQUENCER_OT_view_all(), SEQUENCER_OT_view_all_preview(), SEQUENCER_OT_view_ghost_border(), SEQUENCER_OT_view_selected(), SEQUENCER_OT_view_toggle(), SEQUENCER_OT_view_zoom_ratio(), SKETCH_OT_cancel_stroke(), SKETCH_OT_convert(), SKETCH_OT_delete(), SKETCH_OT_draw_preview(), SKETCH_OT_draw_stroke(), SKETCH_OT_finish_stroke(), SKETCH_OT_gesture(), SKETCH_OT_select(), SOUND_OT_pack(), SOUND_OT_unpack(), SURFACE_OT_primitive_nurbs_surface_circle_add(), SURFACE_OT_primitive_nurbs_surface_curve_add(), SURFACE_OT_primitive_nurbs_surface_cylinder_add(), SURFACE_OT_primitive_nurbs_surface_sphere_add(), SURFACE_OT_primitive_nurbs_surface_surface_add(), SURFACE_OT_primitive_nurbs_surface_torus_add(), TEXT_OT_comment(), TEXT_OT_convert_whitespace(), TEXT_OT_copy(), TEXT_OT_cursor_set(), TEXT_OT_cut(), TEXT_OT_delete(), TEXT_OT_find(), TEXT_OT_find_set_selected(), TEXT_OT_indent(), TEXT_OT_insert(), TEXT_OT_jump(), TEXT_OT_line_break(), TEXT_OT_line_number(), TEXT_OT_make_internal(), TEXT_OT_mark_all(), TEXT_OT_markers_clear(), TEXT_OT_move(), TEXT_OT_move_select(), TEXT_OT_new(), TEXT_OT_next_marker(), TEXT_OT_open(), TEXT_OT_overwrite_toggle(), TEXT_OT_paste(), TEXT_OT_previous_marker(), TEXT_OT_properties(), TEXT_OT_refresh_pyconstraints(), TEXT_OT_reload(), TEXT_OT_replace(), TEXT_OT_replace_set_selected(), TEXT_OT_resolve_conflict(), TEXT_OT_run_script(), TEXT_OT_save(), TEXT_OT_save_as(), TEXT_OT_scroll(), TEXT_OT_scroll_bar(), TEXT_OT_select_all(), TEXT_OT_select_line(), TEXT_OT_select_word(), TEXT_OT_selection_set(), TEXT_OT_to_3d_object(), TEXT_OT_uncomment(), TEXT_OT_unindent(), TEXT_OT_unlink(), TEXTURE_OT_envmap_clear(), TEXTURE_OT_envmap_clear_all(), TEXTURE_OT_envmap_save(), TEXTURE_OT_slot_copy(), TIME_OT_end_frame_set(), TIME_OT_start_frame_set(), TIME_OT_view_all(), TRANSFORM_OT_create_orientation(), TRANSFORM_OT_delete_orientation(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_select_orientation(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_snap_type(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), TRANSFORM_OT_warp(), UI_OT_copy_to_selected_button(), UI_OT_eyedropper(), UI_OT_reports_to_textblock(), UI_OT_reset_default_button(), UV_OT_align(), UV_OT_average_islands_scale(), UV_OT_circle_select(), UV_OT_cube_project(), UV_OT_cursor_set(), UV_OT_cylinder_project(), UV_OT_from_view(), UV_OT_hide(), UV_OT_mark_seam(), UV_OT_minimize_stretch(), UV_OT_pack_islands(), UV_OT_pin(), UV_OT_reset(), UV_OT_reveal(), UV_OT_seams_from_islands(), UV_OT_select(), UV_OT_select_all(), UV_OT_select_border(), UV_OT_select_linked(), UV_OT_select_linked_pick(), UV_OT_select_loop(), UV_OT_select_pinned(), UV_OT_snap_cursor(), UV_OT_snap_selected(), UV_OT_sphere_project(), UV_OT_stitch(), UV_OT_tile_set(), UV_OT_unlink_selected(), UV_OT_unwrap(), UV_OT_weld(), VIEW2D_OT_reset(), VIEW2D_OT_scroller_activate(), VIEW2D_OT_zoom(), VIEW2D_OT_zoom_border(), VIEW2D_OT_zoom_in(), VIEW2D_OT_zoom_out(), VIEW3D_OT_background_image_add(), VIEW3D_OT_background_image_remove(), VIEW3D_OT_camera_to_view(), VIEW3D_OT_camera_to_view_selected(), VIEW3D_OT_clip_border(), VIEW3D_OT_cursor3d(), VIEW3D_OT_dolly(), VIEW3D_OT_enable_manipulator(), VIEW3D_OT_fly(), VIEW3D_OT_game_start(), VIEW3D_OT_layers(), VIEW3D_OT_localview(), VIEW3D_OT_manipulator(), VIEW3D_OT_move(), VIEW3D_OT_ndof_orbit(), VIEW3D_OT_ndof_pan(), VIEW3D_OT_object_as_camera(), VIEW3D_OT_properties(), VIEW3D_OT_render_border(), VIEW3D_OT_rotate(), VIEW3D_OT_select(), VIEW3D_OT_select_border(), VIEW3D_OT_select_circle(), VIEW3D_OT_select_lasso(), VIEW3D_OT_smoothview(), VIEW3D_OT_snap_cursor_to_active(), VIEW3D_OT_snap_cursor_to_center(), VIEW3D_OT_snap_cursor_to_grid(), VIEW3D_OT_snap_cursor_to_selected(), VIEW3D_OT_snap_selected_to_cursor(), VIEW3D_OT_snap_selected_to_grid(), VIEW3D_OT_toolshelf(), VIEW3D_OT_view_all(), VIEW3D_OT_view_center_camera(), VIEW3D_OT_view_center_cursor(), VIEW3D_OT_view_orbit(), VIEW3D_OT_view_pan(), VIEW3D_OT_view_persportho(), VIEW3D_OT_view_selected(), VIEW3D_OT_viewnumpad(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), VIEW3D_OT_zoom_camera_1_to_1(), WM_operator_poll(), WM_operator_redo_popup(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), WM_OT_call_menu(), WM_OT_debug_menu(), WM_OT_link_append(), WM_OT_quit_blender(), WM_OT_recover_auto_save(), WM_OT_recover_last_session(), WM_OT_redraw_timer(), WM_OT_save_homefile(), WM_OT_search_menu(), WM_OT_splash(), WM_OT_window_duplicate(), and WM_OT_window_fullscreen_toggle().
PropertyRNA* wmOperatorType::prop
Definition at line 471 of file WM_types.h.
Referenced by ACTION_OT_clean(), ACTION_OT_extrapolation_type(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_mirror(), ACTION_OT_select_all_toggle(), ACTION_OT_select_border(), ACTION_OT_select_column(), ACTION_OT_select_leftright(), ACTION_OT_snap(), ANIM_OT_channels_collapse(), ANIM_OT_channels_expand(), ANIM_OT_channels_move(), ANIM_OT_channels_select_all_toggle(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), ANIM_OT_channels_setting_toggle(), ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_menu(), ARMATURE_OT_autoside_names(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_layers_show_all(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), BOID_OT_rule_add(), BPy_BoolProperty(), BPy_BoolVectorProperty(), BPy_CollectionProperty(), BPy_EnumProperty(), BPy_FloatProperty(), BPy_FloatVectorProperty(), BPy_IntProperty(), BPy_IntVectorProperty(), BPy_PointerProperty(), BPy_StringProperty(), BRUSH_OT_uv_sculpt_tool_set(), CURVE_OT_handle_type_set(), CURVE_OT_spline_type_set(), DPAINT_OT_output_toggle(), DPAINT_OT_type_toggle(), GPENCIL_OT_convert(), GRAPH_OT_clean(), GRAPH_OT_extrapolation_type(), GRAPH_OT_fmodifier_add(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_select_all_toggle(), GRAPH_OT_select_border(), GRAPH_OT_select_column(), GRAPH_OT_select_leftright(), GRAPH_OT_snap(), LOGIC_OT_actuator_add(), LOGIC_OT_controller_add(), LOGIC_OT_sensor_add(), MARKER_OT_make_links_scene(), MARKER_OT_rename(), MESH_OT_delete(), MESH_OT_merge(), MESH_OT_select_similar(), MESH_OT_separate(), MESH_OT_sort_faces(), MESH_OT_vertices_randomize(), NLA_OT_action_sync_length(), NLA_OT_actionclip_add(), NLA_OT_fmodifier_add(), NLA_OT_select_leftright(), NLA_OT_snap(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_convert(), OBJECT_OT_effector_add(), OBJECT_OT_game_property_copy(), OBJECT_OT_group_instance_add(), OBJECT_OT_group_link(), OBJECT_OT_hook_remove(), OBJECT_OT_lamp_add(), OBJECT_OT_make_links_data(), OBJECT_OT_make_links_scene(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_modifier_add(), OBJECT_OT_origin_set(), OBJECT_OT_parent_clear(), OBJECT_OT_proxy_make(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), OBJECT_OT_vertex_group_set_active(), operator_enum_call_cb(), operator_enum_search_cb(), operator_wrapper(), OUTLINER_OT_action_set(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_object_operation(), PAINT_OT_project_image(), PAINT_OT_weight_from_bones(), PAINT_OT_weight_sample_group(), PARTICLE_OT_delete(), POSE_OT_autoside_names(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_propagate(), POSE_OT_rotation_mode_set(), POSE_OT_select_grouped(), POSE_OT_select_hierarchy(), POSELIB_OT_apply_pose(), POSELIB_OT_browse_interactive(), POSELIB_OT_pose_remove(), POSELIB_OT_pose_rename(), SCENE_OT_new(), SEQUENCER_OT_change_effect_input(), SEQUENCER_OT_change_effect_type(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_scene_strip_add(), SEQUENCER_OT_select_grouped(), TRANSFORM_OT_snap_type(), uiLayoutOperatorButs(), VIEW3D_OT_select_menu(), WM_menu_invoke(), and WM_OT_redraw_timer().
void* wmOperatorType::pyop_data
Definition at line 481 of file WM_types.h.
int(* wmOperatorType::pyop_poll)(struct bContext *, struct wmOperatorType *ot)
Definition at line 482 of file WM_types.h.
Referenced by macro_wrapper(), and WM_operator_poll().
struct StructRNA* wmOperatorType::srna
Definition at line 464 of file WM_types.h.
Referenced by ACTION_OT_clean(), ACTION_OT_clickselect(), ACTION_OT_extrapolation_type(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_mirror(), ACTION_OT_paste(), ACTION_OT_select_all_toggle(), ACTION_OT_select_border(), ACTION_OT_select_column(), ACTION_OT_select_leftright(), ACTION_OT_snap(), ANIM_OT_change_frame(), ANIM_OT_channels_click(), ANIM_OT_channels_collapse(), ANIM_OT_channels_editable_toggle(), ANIM_OT_channels_expand(), ANIM_OT_channels_move(), ANIM_OT_channels_select_all_toggle(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), ANIM_OT_channels_setting_toggle(), ANIM_OT_driver_button_add(), ANIM_OT_driver_button_remove(), ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_delete_button(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_button(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_active_set(), ANIM_OT_keyingset_button_add(), ANIM_OT_previewrange_set(), ARMATURE_OT_armature_layers(), ARMATURE_OT_autoside_names(), ARMATURE_OT_bone_layers(), ARMATURE_OT_bone_primitive_add(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_extrude(), ARMATURE_OT_hide(), ARMATURE_OT_layers_show_all(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), ARMATURE_OT_parent_set(), ARMATURE_OT_select_hierarchy(), ARMATURE_OT_select_linked(), ARMATURE_OT_subdivide(), BOID_OT_rule_add(), BPy_BoolProperty(), BPy_BoolVectorProperty(), BPy_CollectionProperty(), BPy_EnumProperty(), BPy_FloatProperty(), BPy_FloatVectorProperty(), BPy_IntProperty(), BPy_IntVectorProperty(), BPy_PointerProperty(), BPy_RemoveProperty(), BPy_StringProperty(), BRUSH_OT_curve_preset(), BRUSH_OT_scale_size(), BRUSH_OT_uv_sculpt_tool_set(), CLIP_OT_add_marker(), CLIP_OT_change_frame(), CLIP_OT_clean_tracks(), CLIP_OT_clear_track_path(), CLIP_OT_detect_features(), CLIP_OT_disable_markers(), CLIP_OT_frame_jump(), CLIP_OT_graph_disable_markers(), CLIP_OT_graph_select(), CLIP_OT_hide_tracks(), CLIP_OT_lock_tracks(), CLIP_OT_mode_set(), CLIP_OT_select(), CLIP_OT_select_circle(), CLIP_OT_select_grouped(), CLIP_OT_set_axis(), CLIP_OT_set_origin(), CLIP_OT_set_plane(), CLIP_OT_set_scale(), CLIP_OT_set_solution_scale(), CLIP_OT_slide_marker(), CLIP_OT_track_markers(), CLIP_OT_view_all(), CLIP_OT_view_pan(), CLIP_OT_view_zoom(), CLIP_OT_view_zoom_in(), CLIP_OT_view_zoom_out(), CLIP_OT_view_zoom_ratio(), CONSOLE_OT_clear(), CONSOLE_OT_delete(), CONSOLE_OT_history_append(), CONSOLE_OT_history_cycle(), CONSOLE_OT_insert(), CONSOLE_OT_move(), CONSOLE_OT_scrollback_append(), CURVE_OT_cyclic_toggle(), CURVE_OT_delete(), CURVE_OT_extrude(), CURVE_OT_handle_type_set(), CURVE_OT_hide(), CURVE_OT_radius_set(), CURVE_OT_select_linked_pick(), CURVE_OT_select_nth(), CURVE_OT_select_random(), CURVE_OT_spin(), CURVE_OT_spline_type_set(), CURVE_OT_spline_weight_set(), CURVE_OT_subdivide(), CURVE_OT_vertex_add(), DPAINT_OT_output_toggle(), DPAINT_OT_type_toggle(), dropbox_active(), ED_fileselect_set_params(), ED_object_add_generic_props(), ED_operatormacros_object(), ED_OT_undo_history(), ED_OT_undo_push(), edit_actuator_properties(), edit_constraint_properties(), edit_controller_properties(), edit_modifier_properties(), edit_sensor_properties(), FILE_OT_delete_bookmark(), FILE_OT_directory_new(), FILE_OT_execute(), FILE_OT_filenum(), FILE_OT_select(), FILE_OT_select_bookmark(), FILE_OT_unpack_all(), FONT_OT_case_set(), FONT_OT_change_character(), FONT_OT_change_spacing(), FONT_OT_delete(), FONT_OT_line_break(), FONT_OT_move(), FONT_OT_move_select(), FONT_OT_style_set(), FONT_OT_style_toggle(), FONT_OT_text_insert(), FONT_OT_textbox_remove(), GPENCIL_OT_convert(), GPENCIL_OT_draw(), GRAPH_OT_clean(), GRAPH_OT_click_insert(), GRAPH_OT_clickselect(), GRAPH_OT_cursor_set(), GRAPH_OT_duplicate(), GRAPH_OT_extrapolation_type(), GRAPH_OT_fmodifier_add(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_paste(), GRAPH_OT_select_all_toggle(), GRAPH_OT_select_border(), GRAPH_OT_select_column(), GRAPH_OT_select_leftright(), GRAPH_OT_snap(), GRAPH_OT_sound_bake(), GROUP_OT_create(), IMAGE_OT_curves_point_set(), IMAGE_OT_cycle_render_slot(), IMAGE_OT_invert(), IMAGE_OT_new(), IMAGE_OT_pack(), IMAGE_OT_save_as(), IMAGE_OT_unpack(), IMAGE_OT_view_pan(), IMAGE_OT_view_zoom(), IMAGE_OT_view_zoom_in(), IMAGE_OT_view_zoom_out(), IMAGE_OT_view_zoom_ratio(), image_save_as_draw(), INFO_OT_select_pick(), LOGIC_OT_actuator_add(), LOGIC_OT_actuator_move(), LOGIC_OT_controller_add(), LOGIC_OT_controller_move(), LOGIC_OT_links_cut(), LOGIC_OT_sensor_add(), LOGIC_OT_sensor_move(), MARKER_OT_duplicate(), MARKER_OT_make_links_scene(), MARKER_OT_move(), MARKER_OT_rename(), MARKER_OT_select(), MBALL_OT_duplicate_metaelems(), MBALL_OT_hide_metaelems(), MBALL_OT_select_random_metaelems(), MESH_OT_bevel(), MESH_OT_blend_from_shape(), MESH_OT_bridge_edge_loops(), MESH_OT_colors_rotate(), MESH_OT_delete(), MESH_OT_dissolve(), MESH_OT_dissolve_limited(), MESH_OT_drop_named_image(), MESH_OT_dupli_extrude_cursor(), MESH_OT_duplicate(), MESH_OT_edge_rotate(), MESH_OT_edgering_select(), MESH_OT_edges_select_sharp(), MESH_OT_extrude_edges_indiv(), MESH_OT_extrude_faces_indiv(), MESH_OT_extrude_region(), MESH_OT_extrude_repeat(), MESH_OT_extrude_verts_indiv(), MESH_OT_faces_select_linked_flat(), MESH_OT_hide(), MESH_OT_inset(), MESH_OT_knife_cut(), MESH_OT_knife_tool(), MESH_OT_loop_multi_select(), MESH_OT_loop_select(), MESH_OT_loop_to_region(), MESH_OT_loopcut(), MESH_OT_mark_seam(), MESH_OT_mark_sharp(), MESH_OT_merge(), MESH_OT_noise(), MESH_OT_normals_make_consistent(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_uv_sphere_add(), MESH_OT_quads_convert_to_tris(), MESH_OT_remove_doubles(), MESH_OT_rip(), MESH_OT_screw(), MESH_OT_select_axis(), MESH_OT_select_by_number_vertices(), MESH_OT_select_linked(), MESH_OT_select_linked_pick(), MESH_OT_select_mirror(), MESH_OT_select_nth(), MESH_OT_select_random(), MESH_OT_select_shortest_path(), MESH_OT_select_similar(), MESH_OT_select_vertex_path(), MESH_OT_separate(), MESH_OT_solidify(), MESH_OT_sort_faces(), MESH_OT_spin(), MESH_OT_subdivide(), MESH_OT_tris_convert_to_quads(), MESH_OT_uvs_rotate(), MESH_OT_vert_slide(), MESH_OT_vertices_randomize(), MESH_OT_vertices_smooth(), NLA_OT_action_sync_length(), NLA_OT_actionclip_add(), NLA_OT_channels_click(), NLA_OT_click_select(), NLA_OT_duplicate(), NLA_OT_fmodifier_add(), NLA_OT_select_all_toggle(), NLA_OT_select_border(), NLA_OT_select_leftright(), NLA_OT_snap(), NLA_OT_tracks_add(), NODE_OT_add_file(), NODE_OT_backimage_zoom(), NODE_OT_duplicate(), NODE_OT_group_socket_add(), NODE_OT_group_socket_move_down(), NODE_OT_group_socket_move_up(), NODE_OT_group_socket_remove(), NODE_OT_link_make(), NODE_OT_links_cut(), NODE_OT_new_node_tree(), NODE_OT_output_file_add_socket(), NODE_OT_select(), NODE_OT_select_border(), OBJECT_OT_add(), OBJECT_OT_add_named(), OBJECT_OT_camera_add(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_convert(), OBJECT_OT_delete(), OBJECT_OT_drop_named_material(), OBJECT_OT_duplicate(), OBJECT_OT_duplicates_make_real(), OBJECT_OT_effector_add(), OBJECT_OT_game_property_copy(), OBJECT_OT_game_property_new(), OBJECT_OT_game_property_remove(), OBJECT_OT_group_instance_add(), OBJECT_OT_group_link(), OBJECT_OT_hide_render_set(), OBJECT_OT_hide_view_set(), OBJECT_OT_hook_assign(), OBJECT_OT_hook_recenter(), OBJECT_OT_hook_remove(), OBJECT_OT_hook_reset(), OBJECT_OT_hook_select(), OBJECT_OT_lamp_add(), OBJECT_OT_make_links_data(), OBJECT_OT_make_links_scene(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_metaball_add(), OBJECT_OT_mode_set(), OBJECT_OT_modifier_add(), OBJECT_OT_modifier_apply(), OBJECT_OT_move_to_layer(), OBJECT_OT_ocean_bake(), OBJECT_OT_origin_set(), OBJECT_OT_parent_clear(), OBJECT_OT_parent_set(), OBJECT_OT_proxy_make(), OBJECT_OT_select_by_layer(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_select_mirror(), OBJECT_OT_select_random(), OBJECT_OT_select_same_group(), OBJECT_OT_shape_key_add(), OBJECT_OT_shape_key_move(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), OBJECT_OT_transform_apply(), OBJECT_OT_vertex_group_assign(), OBJECT_OT_vertex_group_blend(), OBJECT_OT_vertex_group_clean(), OBJECT_OT_vertex_group_fix(), OBJECT_OT_vertex_group_invert(), OBJECT_OT_vertex_group_levels(), OBJECT_OT_vertex_group_mirror(), OBJECT_OT_vertex_group_move(), OBJECT_OT_vertex_group_normalize_all(), OBJECT_OT_vertex_group_remove(), OBJECT_OT_vertex_group_remove_from(), OBJECT_OT_vertex_group_set_active(), operator_enum_search_cb(), operator_properties_init(), operator_wrapper(), OUTLINER_OT_action_set(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_item_activate(), OUTLINER_OT_item_openclose(), OUTLINER_OT_object_operation(), OUTLINER_OT_parent_clear(), OUTLINER_OT_parent_drop(), OUTLINER_OT_scroll_page(), OUTLINER_OT_show_one_level(), PAINT_OT_brush_select(), PAINT_OT_clone_cursor_set(), PAINT_OT_face_select_hide(), PAINT_OT_face_select_linked_pick(), PAINT_OT_face_select_reveal(), PAINT_OT_grab_clone(), PAINT_OT_hide_show(), PAINT_OT_image_from_view(), PAINT_OT_image_paint(), PAINT_OT_project_image(), PAINT_OT_sample_color(), PAINT_OT_vertex_paint(), PAINT_OT_weight_from_bones(), PAINT_OT_weight_paint(), PAINT_OT_weight_sample_group(), PARTICLE_OT_brush_edit(), PARTICLE_OT_connect_hair(), PARTICLE_OT_delete(), PARTICLE_OT_disconnect_hair(), PARTICLE_OT_hide(), PARTICLE_OT_rekey(), PARTICLE_OT_remove_doubles(), PARTICLE_OT_select_linked(), PARTICLE_OT_weight_set(), pointer_type_from_py(), POSE_OT_armature_layers(), POSE_OT_autoside_names(), POSE_OT_bone_layers(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_group_assign(), POSE_OT_group_move(), POSE_OT_hide(), POSE_OT_ik_add(), POSE_OT_paste(), POSE_OT_propagate(), POSE_OT_rotation_mode_set(), POSE_OT_select_grouped(), POSE_OT_select_hierarchy(), POSE_OT_select_linked(), pose_slide_opdef_properties(), POSELIB_OT_apply_pose(), POSELIB_OT_browse_interactive(), POSELIB_OT_pose_add(), POSELIB_OT_pose_remove(), POSELIB_OT_pose_rename(), PTCACHE_OT_bake(), PTCACHE_OT_bake_all(), pyop_as_string(), RENDER_OT_opengl(), RENDER_OT_render(), SCENE_OT_new(), SCREEN_OT_actionzone(), SCREEN_OT_animation_cancel(), SCREEN_OT_animation_play(), SCREEN_OT_area_join(), SCREEN_OT_area_move(), SCREEN_OT_area_split(), SCREEN_OT_frame_jump(), SCREEN_OT_frame_offset(), SCREEN_OT_keyframe_jump(), SCREEN_OT_repeat_history(), SCREEN_OT_screen_set(), SCREEN_OT_screencast(), SCREEN_OT_screenshot(), screenshot_draw(), SCRIPT_OT_python_file_run(), SCULPT_OT_brush_stroke(), SCULPT_OT_uv_sculpt_stroke(), sequencer_generic_props__internal(), SEQUENCER_OT_change_effect_input(), SEQUENCER_OT_change_effect_type(), SEQUENCER_OT_cut(), SEQUENCER_OT_duplicate(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_images_separate(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_mute(), SEQUENCER_OT_reload(), SEQUENCER_OT_scene_strip_add(), SEQUENCER_OT_select(), SEQUENCER_OT_select_active_side(), SEQUENCER_OT_select_grouped(), SEQUENCER_OT_select_handles(), SEQUENCER_OT_select_linked_pick(), SEQUENCER_OT_snap(), SEQUENCER_OT_sound_strip_add(), SEQUENCER_OT_swap(), SEQUENCER_OT_unmute(), SEQUENCER_OT_view_zoom_ratio(), SKETCH_OT_draw_preview(), SKETCH_OT_draw_stroke(), SKETCH_OT_gesture(), SOUND_OT_mixdown(), SOUND_OT_open(), SOUND_OT_open_mono(), SOUND_OT_unpack(), TEXT_OT_convert_whitespace(), TEXT_OT_cursor_set(), TEXT_OT_delete(), TEXT_OT_insert(), TEXT_OT_jump(), TEXT_OT_move(), TEXT_OT_move_select(), TEXT_OT_open(), TEXT_OT_paste(), TEXT_OT_resolve_conflict(), TEXT_OT_scroll(), TEXT_OT_scroll_bar(), TEXT_OT_selection_set(), TEXT_OT_to_3d_object(), TEXTURE_OT_envmap_save(), TEXTURE_OT_slot_move(), TRANSFORM_OT_create_orientation(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_select_orientation(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_snap_type(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), TRANSFORM_OT_warp(), Transform_Properties(), ui_def_but_operator_ptr(), UI_OT_copy_to_selected_button(), UI_OT_reset_default_button(), uiItemFullO_ptr(), uiItemMenuEnumO(), uiItemsFullEnumO(), uiLayoutOperatorButs(), undo_history_invoke(), uv_map_clip_correct_properties(), UV_OT_align(), UV_OT_circle_select(), UV_OT_cube_project(), UV_OT_cursor_set(), UV_OT_from_view(), UV_OT_hide(), UV_OT_minimize_stretch(), UV_OT_pack_islands(), UV_OT_pin(), UV_OT_seams_from_islands(), UV_OT_select(), UV_OT_select_border(), UV_OT_select_linked(), UV_OT_select_linked_pick(), UV_OT_select_loop(), UV_OT_snap_cursor(), UV_OT_snap_selected(), UV_OT_stitch(), UV_OT_tile_set(), UV_OT_unwrap(), uv_transform_properties(), VIEW2D_OT_pan(), VIEW2D_OT_scroll_down(), VIEW2D_OT_scroll_left(), VIEW2D_OT_scroll_right(), VIEW2D_OT_scroll_up(), VIEW2D_OT_zoom(), VIEW2D_OT_zoom_border(), VIEW2D_OT_zoom_in(), VIEW2D_OT_zoom_out(), VIEW3D_OT_background_image_add(), VIEW3D_OT_background_image_remove(), VIEW3D_OT_clip_border(), VIEW3D_OT_dolly(), VIEW3D_OT_enable_manipulator(), VIEW3D_OT_layers(), VIEW3D_OT_render_border(), VIEW3D_OT_select(), VIEW3D_OT_select_circle(), VIEW3D_OT_select_lasso(), VIEW3D_OT_select_menu(), VIEW3D_OT_view_all(), VIEW3D_OT_view_orbit(), VIEW3D_OT_view_pan(), VIEW3D_OT_viewnumpad(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), wm_block_create_redo(), wm_enum_search_menu(), WM_menu_invoke(), wm_operator_create(), WM_operator_properties_create_ptr(), WM_operator_properties_filesel(), WM_operator_properties_gesture_border(), WM_operator_properties_gesture_straightline(), WM_operator_properties_reset(), WM_operator_properties_select_all(), WM_operatortype_append(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), WM_operatortype_append_ptr(), WM_operatortype_macro_define(), WM_operatortype_remove(), WM_OT_call_menu(), WM_OT_debug_menu(), WM_OT_link_append(), WM_OT_ndof_sensitivity_change(), WM_OT_open_mainfile(), WM_OT_radial_control(), WM_OT_redraw_timer(), WM_OT_save_as_mainfile(), and WM_OT_save_mainfile().
void(* wmOperatorType::ui)(struct bContext *, struct wmOperator *)
Definition at line 461 of file WM_types.h.
Referenced by IMAGE_OT_save_as(), macro_wrapper(), SCREEN_OT_screenshot(), SOUND_OT_mixdown(), and uiLayoutOperatorButs().
The documentation for this struct was generated from the following file:
WM_types.h