Blender: MT_Vector2.h File Reference
MT_Vector2.h File Reference
moto
#include <MT_assert.h>
#include "MT_Tuple2.h"
Classes
class MT_Vector2
Functions
MT_Vector2 operator+ (const MT_Vector2 &v1, const MT_Vector2 &v2)
MT_Vector2 operator- (const MT_Vector2 &v1, const MT_Vector2 &v2)
MT_Vector2 operator- (const MT_Vector2 &v)
MT_Vector2 operator* (const MT_Vector2 &v, MT_Scalar s)
MT_Vector2 operator* (MT_Scalar s, const MT_Vector2 &v)
MT_Vector2 operator/ (const MT_Vector2 &v, MT_Scalar s)
MT_Scalar MT_dot (const MT_Vector2 &v1, const MT_Vector2 &v2)
MT_Scalar MT_length2 (const MT_Vector2 &v)
MT_Scalar MT_length (const MT_Vector2 &v)
bool MT_fuzzyZero (const MT_Vector2 &v)
bool MT_fuzzyEqual (const MT_Vector2 &v1, const MT_Vector2 &v2)
MT_Scalar MT_angle (const MT_Vector2 &v1, const MT_Vector2 &v2)
MT_Vector2 MT_cross (const MT_Vector2 &v1, const MT_Vector2 &v2)
MT_Scalar MT_triple (const MT_Vector2 &v1, const MT_Vector2 &v2, const MT_Vector2 &v3)
Detailed Description
Definition in file MT_Vector2.h.
Function Documentation
MT_Scalar MT_angle (const MT_Vector2 & v1, const MT_Vector2 & v2)
Definition at line 89 of file MT_Vector2.inl.
References MT_Vector2::angle().
MT_Vector2 MT_cross (const MT_Vector2 & v1, const MT_Vector2 & v2)
Referenced by RAS_OpenGLRasterizer::FlushDebugShapes().
MT_Scalar MT_dot (const MT_Vector2 & v1, const MT_Vector2 & v2)
Definition at line 77 of file MT_Vector2.inl.
References MT_Vector2::dot().
Referenced by RAS_MeshObject::polygonSlot::get(), MT_Matrix3x3::inverse(), MT_Transform::invert(), MT_Vector4::length2(), MT_Transform::operator()(), operator*(), RAS_BucketManager::sortedmeshslot::set(), sweepCircleCircle(), and sweepCircleSegment().
bool MT_fuzzyEqual (const MT_Vector2 & v1, const MT_Vector2 & v2)
Definition at line 85 of file MT_Vector2.inl.
References MT_fuzzyZero().
Referenced by RAS_TexVert::closeTo().
bool MT_fuzzyZero (const MT_Vector2 & v)
Definition at line 84 of file MT_Vector2.inl.
References MT_Vector2::fuzzyZero().
MT_Scalar MT_length (const MT_Vector2 & v)
Definition at line 82 of file MT_Vector2.inl.
References MT_Vector2::length().
MT_Scalar MT_length2 (const MT_Vector2 & v)
Definition at line 81 of file MT_Vector2.inl.
References MT_Vector2::length2().
MT_Scalar MT_triple (const MT_Vector2 & v1, const MT_Vector2 & v2, const MT_Vector2 & v3)
Referenced by MT_Matrix3x3::determinant().
MT_Vector2 operator* (MT_Scalar s, const MT_Vector2 & v)
Definition at line 39 of file MT_Vector2.inl.
MT_Vector2 operator* (const MT_Vector2 & v, MT_Scalar s)
Definition at line 35 of file MT_Vector2.inl.
MT_Vector2 operator+ (const MT_Vector2 & v1, const MT_Vector2 & v2)
Definition at line 23 of file MT_Vector2.inl.
MT_Vector2 operator- (const MT_Vector2 & v1, const MT_Vector2 & v2)
Definition at line 27 of file MT_Vector2.inl.
MT_Vector2 operator- (const MT_Vector2 & v)
Definition at line 31 of file MT_Vector2.inl.
MT_Vector2 operator/ (const MT_Vector2 & v, MT_Scalar s)
Definition at line 41 of file MT_Vector2.inl.
References MT_assert, and MT_fuzzyZero().