Blender: KX_Scene.cpp File Reference
KX_Scene.cpp File Reference
Ketsji
#include "KX_Scene.h"
#include "KX_PythonInit.h"
#include "MT_assert.h"
#include "KX_KetsjiEngine.h"
#include "KX_BlenderMaterial.h"
#include "RAS_IPolygonMaterial.h"
#include "ListValue.h"
#include "SCA_LogicManager.h"
#include "SCA_TimeEventManager.h"
#include "KX_TouchEventManager.h"
#include "SCA_KeyboardManager.h"
#include "SCA_MouseManager.h"
#include "SCA_ActuatorEventManager.h"
#include "SCA_BasicEventManager.h"
#include "KX_Camera.h"
#include "SCA_JoystickManager.h"
#include "RAS_MeshObject.h"
#include "RAS_IRasterizer.h"
#include "RAS_BucketManager.h"
#include "FloatValue.h"
#include "SCA_IController.h"
#include "SCA_IActuator.h"
#include "SG_Node.h"
#include "BL_System.h"
#include "SG_Controller.h"
#include "SG_IObject.h"
#include "SG_Tree.h"
#include "DNA_group_types.h"
#include "DNA_scene_types.h"
#include "KX_SG_NodeRelationships.h"
#include "KX_NetworkEventManager.h"
#include "NG_NetworkScene.h"
#include "PHY_IPhysicsEnvironment.h"
#include "KX_IPhysicsController.h"
#include "PHY_IGraphicController.h"
#include "KX_BlenderSceneConverter.h"
#include "KX_MotionState.h"
#include "BL_ModifierDeformer.h"
#include "BL_ShapeDeformer.h"
#include "BL_DeformableGameObject.h"
#include "KX_ObstacleSimulation.h"
#include "KX_Light.h"
#include <stdio.h>
Functions
void * KX_SceneReplicationFunc (SG_IObject *node, void *gameobj, void *scene)
void * KX_SceneDestructionFunc (SG_IObject *node, void *gameobj, void *scene)
static void MergeScene_LogicBrick (SCA_ILogicBrick *brick, KX_Scene *to)
static void MergeScene_GameObject (KX_GameObject *gameobj, KX_Scene *to, KX_Scene *from)
Variables
bool gUseVisibilityTemp
Detailed Description
Definition in file KX_Scene.cpp.
Function Documentation
void* KX_SceneDestructionFunc (SG_IObject * node, void * gameobj, void * scene)
Definition at line 111 of file KX_Scene.cpp.
References NULL.
void* KX_SceneReplicationFunc (SG_IObject * node, void * gameobj, void * scene)
Definition at line 101 of file KX_Scene.cpp.
References CValue::Release().
static void MergeScene_GameObject (KX_GameObject * gameobj, KX_Scene * to, KX_Scene * from) [static]
Definition at line 1750 of file KX_Scene.cpp.
References SCA_IObject::GetActuators(), KX_GameObject::GetBlenderObject(), SCA_IObject::GetControllers(), SCA_IObject::GetGameObjectType(), KX_GameObject::GetGraphicController(), SCA_IController::GetLinkedActuators(), SCA_IController::GetLinkedSensors(), KX_Scene::GetLogicManager(), KX_GameObject::GetMesh(), KX_GameObject::GetMeshCount(), KX_GameObject::GetName(), RAS_MeshObject::GetName(), KX_Scene::GetPhysicsEnvironment(), SCA_IObject::GetSensors(), SG_Node::GetSGChildren(), SG_IObject::GetSGClientInfo(), SG_IObject::GetSGControllerList(), KX_GameObject::GetSGNode(), i, MergeScene_LogicBrick(), SCA_IObject::OBJ_LIGHT, SCA_LogicManager::RegisterGameMeshName(), SCA_LogicManager::RegisterGameObj(), SCA_LogicManager::RegisterGameObjectName(), CcdPhysicsController::SetPhysicsEnvironment(), PHY_IController::SetPhysicsEnvironment(), and SG_IObject::SetSGClientInfo().
Referenced by KX_Scene::MergeScene().
static void MergeScene_LogicBrick (SCA_ILogicBrick * brick, KX_Scene * to) [static]
Definition at line 1723 of file KX_Scene.cpp.
References KX_Scene::GetLogicManager(), KX_Scene::GetNetworkScene(), KX_TouchSensor::GetPhysicsController(), KX_Scene::GetPhysicsEnvironment(), SCA_ISensor::Replace_EventManager(), SCA_ILogicBrick::Replace_IScene(), SCA_ILogicBrick::Replace_NetworkScene(), and PHY_IController::SetPhysicsEnvironment().
Referenced by MergeScene_GameObject().
Variable Documentation
bool gUseVisibilityTemp