Blender: btGenericPoolAllocator.h File Reference
btGenericPoolAllocator.h File Reference
#include <limits.h>
#include <stdio.h>
#include <string.h>
#include "LinearMath/btAlignedAllocator.h"
Classes
class btGenericMemoryPool
Generic Pool class.
class btGenericPoolAllocator
Generic Allocator with pools.
Defines
#define BT_UINT_MAX UINT_MAX
#define BT_DEFAULT_MAX_POOLS 16
Functions
void * btPoolAlloc (size_t size)
void * btPoolRealloc (void *ptr, size_t oldsize, size_t newsize)
void btPoolFree (void *ptr)
Detailed Description
Author:
Francisco Leon Najera. email projectileman@yahoo.com
General purpose allocator class
Definition in file btGenericPoolAllocator.h.
Define Documentation
#define BT_DEFAULT_MAX_POOLS 16
Definition at line 30 of file btGenericPoolAllocator.h.
Referenced by btGenericPoolAllocator::push_new_pool().
#define BT_UINT_MAX UINT_MAX
Definition at line 29 of file btGenericPoolAllocator.h.
Referenced by btGenericMemoryPool::allocate(), btGenericMemoryPool::allocate_from_free_nodes(), and btGenericMemoryPool::allocate_from_pool().
Function Documentation
void* btPoolAlloc (size_t size)
Definition at line 266 of file btGenericPoolAllocator.cpp.
References btGenericPoolAllocator::allocate().
Referenced by btPoolRealloc().
void btPoolFree (void * ptr)
Definition at line 280 of file btGenericPoolAllocator.cpp.
References btGenericPoolAllocator::freeMemory().
Referenced by btPoolRealloc().
void* btPoolRealloc (void * ptr, size_t oldsize, size_t newsize)
Definition at line 271 of file btGenericPoolAllocator.cpp.
References btPoolAlloc(), and btPoolFree().