Blender: rna_smoke.c File Reference
rna_smoke.c File Reference
RNA
#include <stdlib.h>
#include <limits.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "BKE_modifier.h"
#include "BKE_smoke.h"
#include "DNA_modifier_types.h"
#include "DNA_object_force.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_smoke_types.h"
#include "WM_types.h"
Functions
static void rna_def_smoke_domain_settings (BlenderRNA *brna)
static void rna_def_smoke_flow_settings (BlenderRNA *brna)
static void rna_def_smoke_coll_settings (BlenderRNA *brna)
void RNA_def_smoke (BlenderRNA *brna)
Detailed Description
Definition in file rna_smoke.c.
Function Documentation
void RNA_def_smoke (BlenderRNA * brna)
Definition at line 347 of file rna_smoke.c.
References rna_def_smoke_coll_settings(), rna_def_smoke_domain_settings(), and rna_def_smoke_flow_settings().
static void rna_def_smoke_coll_settings (BlenderRNA * brna) [static]
Definition at line 337 of file rna_smoke.c.
References NULL, RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_smoke().
static void rna_def_smoke_domain_settings (BlenderRNA * brna) [static]
Definition at line 115 of file rna_smoke.c.
References MOD_SMOKE_DISSOLVE, MOD_SMOKE_DISSOLVE_LOG, MOD_SMOKE_HIGH_SMOOTH, MOD_SMOKE_HIGHRES, MOD_SMOKE_NOISEFFT, MOD_SMOKE_NOISEWAVE, MOD_SMOKE_VIEW_SHOWBIG, NC_OBJECT, ND_DRAW, ND_MODIFIER, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NEVER_NULL, prop_noise_type_items, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SM_BORDER_CLOSED, SM_BORDER_OPEN, SM_BORDER_VERTICAL, SM_CACHE_HEAVY, and SM_CACHE_LIGHT.
Referenced by RNA_def_smoke().
static void rna_def_smoke_flow_settings (BlenderRNA * brna) [static]
Definition at line 283 of file rna_smoke.c.
References MOD_SMOKE_FLOW_ABSOLUTE, MOD_SMOKE_FLOW_INITVELOCITY, MOD_SMOKE_FLOW_TYPE_OUTFLOW, NC_OBJECT, ND_MODIFIER, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_smoke().