Blender: node_composite_diffMatte.c File Reference
node_composite_diffMatte.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_diff_matte (bNode *node, float *outColor, float *inColor1, float *inColor2)
static void node_composit_exec_diff_matte (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_diff_matte (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_diff_matte (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_diff_matte_in []
static bNodeSocketTemplate cmp_node_diff_matte_out []
Detailed Description
Definition in file node_composite_diffMatte.c.
Function Documentation
static void do_diff_matte (bNode * node, float * outColor, float * inColor1, float * inColor2) [static]
Definition at line 48 of file node_composite_diffMatte.c.
References copy_v3_v3(), fabs(), bNode::storage, NodeChroma::t1, and NodeChroma::t2.
Referenced by node_composit_exec_diff_matte().
static void node_composit_exec_diff_matte (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 87 of file node_composite_diffMatte.c.
References CB_RGBA, CHAN_A, composit2_pixel_processor(), bNodeStack::data, do_diff_matte(), dupalloc_compbuf(), free_compbuf(), generate_preview(), NULL, typecheck_compbuf(), and valbuf_from_rgbabuf().
Referenced by register_node_type_cmp_diff_matte().
static void node_composit_init_diff_matte (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 126 of file node_composite_diffMatte.c.
References MEM_callocN(), bNode::storage, NodeChroma::t1, and NodeChroma::t2.
Referenced by register_node_type_cmp_diff_matte().
void register_node_type_cmp_diff_matte (bNodeTreeType * ttype)
Definition at line 134 of file node_composite_diffMatte.c.
References CMP_NODE_DIFF_MATTE, NODE_CLASS_MATTE, node_composit_exec_diff_matte(), node_composit_init_diff_matte(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_diff_matte_in[] [static]
Initial value:
{
    {SOCK_RGBA,1,"Image 1", 1.0f, 1.0f, 1.0f, 1.0f},
    {SOCK_RGBA,1,"Image 2", 1.0f, 1.0f, 1.0f, 1.0f},
    {-1,0,""}
}
Definition at line 36 of file node_composite_diffMatte.c.
bNodeSocketTemplate cmp_node_diff_matte_out[] [static]
Initial value:
{
    {SOCK_RGBA,0,"Image"},
    {SOCK_FLOAT,0,"Matte"},
    {-1,0,""}
}
Definition at line 42 of file node_composite_diffMatte.c.