Blender: btGeneric6DofConstraint.cpp File Reference
btGeneric6DofConstraint.cpp File Reference
#include "btGeneric6DofConstraint.h"
#include "BulletDynamics/Dynamics/btRigidBody.h"
#include "LinearMath/btTransformUtil.h"
#include <new>
Defines
#define D6_USE_OBSOLETE_METHOD false
#define D6_USE_FRAME_OFFSET true
#define GENERIC_D6_DISABLE_WARMSTARTING 1
Functions
btScalar btGetMatrixElem (const btMatrix3x3 &mat, int index)
bool matrixToEulerXYZ (const btMatrix3x3 &mat, btVector3 &xyz)
MatrixToEulerXYZ from http://www.geometrictools.com/LibFoundation/Mathematics/Wm4Matrix3.inl.html.
Define Documentation
#define D6_USE_FRAME_OFFSET true
Definition at line 31 of file btGeneric6DofConstraint.cpp.
#define D6_USE_OBSOLETE_METHOD false
Definition at line 30 of file btGeneric6DofConstraint.cpp.
#define GENERIC_D6_DISABLE_WARMSTARTING 1
Definition at line 68 of file btGeneric6DofConstraint.cpp.
Function Documentation
btScalar btGetMatrixElem (const btMatrix3x3 & mat, int index)
Definition at line 73 of file btGeneric6DofConstraint.cpp.
References i.
Referenced by matrixToEulerXYZ().
bool matrixToEulerXYZ (const btMatrix3x3 & mat, btVector3 & xyz)
MatrixToEulerXYZ from http://www.geometrictools.com/LibFoundation/Mathematics/Wm4Matrix3.inl.html.
Definition at line 84 of file btGeneric6DofConstraint.cpp.
References btAsin(), btAtan2(), btGetMatrixElem(), and SIMD_HALF_PI.
Referenced by btGeneric6DofConstraint::calculateAngleInfo().