Blender: btGImpactCompoundShape::CompoundPrimitiveManager Class Reference
btGImpactCompoundShape::CompoundPrimitiveManager Class Reference
compound primitive manager
#include <btGImpactShape.h>
Public Member Functions
virtual ~CompoundPrimitiveManager ()
CompoundPrimitiveManager (const CompoundPrimitiveManager &compound)
CompoundPrimitiveManager (btGImpactCompoundShape *compoundShape)
CompoundPrimitiveManager ()
virtual bool is_trimesh () const
determines if this manager consist on only triangles, which special case will be optimized
virtual int get_primitive_count () const
virtual void get_primitive_box (int prim_index, btAABB &primbox) const
virtual void get_primitive_triangle (int prim_index, btPrimitiveTriangle &triangle) const
retrieves only the points of the triangle, and the collision margin
Public Attributes
btGImpactCompoundShape * m_compoundShape
Detailed Description
compound primitive manager
Definition at line 304 of file btGImpactShape.h.
Constructor & Destructor Documentation
virtual btGImpactCompoundShape::CompoundPrimitiveManager::~CompoundPrimitiveManager () [inline, virtual]
Definition at line 307 of file btGImpactShape.h.
btGImpactCompoundShape::CompoundPrimitiveManager::CompoundPrimitiveManager (const CompoundPrimitiveManager & compound) [inline]
Definition at line 311 of file btGImpactShape.h.
References m_compoundShape.
btGImpactCompoundShape::CompoundPrimitiveManager::CompoundPrimitiveManager (btGImpactCompoundShape * compoundShape) [inline]
Definition at line 317 of file btGImpactShape.h.
References m_compoundShape.
btGImpactCompoundShape::CompoundPrimitiveManager::CompoundPrimitiveManager () [inline]
Definition at line 322 of file btGImpactShape.h.
References m_compoundShape, and NULL.
Member Function Documentation
virtual void btGImpactCompoundShape::CompoundPrimitiveManager::get_primitive_box (int prim_index, btAABB & primbox) const [inline, virtual]
Implements btPrimitiveManagerBase.
Definition at line 337 of file btGImpactShape.h.
References btGImpactCompoundShape::childrenHasTransform(), btCollisionShape::getAabb(), btGImpactCompoundShape::getChildShape(), btGImpactCompoundShape::getChildTransform(), m_compoundShape, and btTransform::setIdentity().
virtual int btGImpactCompoundShape::CompoundPrimitiveManager::get_primitive_count () const [inline, virtual]
Implements btPrimitiveManagerBase.
Definition at line 332 of file btGImpactShape.h.
References btGImpactCompoundShape::getNumChildShapes(), and m_compoundShape.
virtual void btGImpactCompoundShape::CompoundPrimitiveManager::get_primitive_triangle (int prim_index, btPrimitiveTriangle & triangle) const [inline, virtual]
retrieves only the points of the triangle, and the collision margin
Implements btPrimitiveManagerBase.
Definition at line 352 of file btGImpactShape.h.
References btAssert.
virtual bool btGImpactCompoundShape::CompoundPrimitiveManager::is_trimesh () const [inline, virtual]
determines if this manager consist on only triangles, which special case will be optimized
Implements btPrimitiveManagerBase.
Definition at line 327 of file btGImpactShape.h.
Member Data Documentation
btGImpactCompoundShape* btGImpactCompoundShape::CompoundPrimitiveManager::m_compoundShape
Definition at line 308 of file btGImpactShape.h.
Referenced by btGImpactCompoundShape::btGImpactCompoundShape(), CompoundPrimitiveManager(), get_primitive_box(), and get_primitive_count().
The documentation for this class was generated from the following file:
btGImpactShape.h