Blender: node_shader_output.c File Reference
node_shader_output.c File Reference
shdnodes
#include "node_shader_util.h"
Functions
static void node_shader_exec_output (void *data, bNode *node, bNodeStack **in, bNodeStack **UNUSED(out))
static int gpu_shader_output (GPUMaterial *mat, bNode *UNUSED(node), GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_output (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_output_in []
Detailed Description
Definition in file node_shader_output.c.
Function Documentation
static int gpu_shader_output (GPUMaterial * mat, bNode * UNUSEDnode, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 68 of file node_shader_output.c.
References GPU_material_enable_alpha(), GPU_material_output_link(), and GPU_stack_link().
Referenced by register_node_type_sh_output().
static void node_shader_exec_output (void * data, bNode * node, bNodeStack ** in, bNodeStack ** UNUSEDout) [static]
Definition at line 42 of file node_shader_output.c.
References ShadeResult::alpha, ShadeResult::combined, copy_v4_v4(), ShadeInput::do_manage, ShadeInput::do_preview, bNode::flag, bNode::lasty, NODE_DO_OUTPUT, nodeAddToPreview(), nodestack_get_vec(), SOCK_FLOAT, SOCK_VECTOR, ShadeInput::xs, and ShadeInput::ys.
Referenced by register_node_type_sh_output().
void register_node_type_sh_output (bNodeTreeType * ttype)
Definition at line 83 of file node_shader_output.c.
References gpu_shader_output(), NODE_CLASS_OUTPUT, NODE_OLD_SHADING, NODE_PREVIEW, node_shader_exec_output(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), NULL, and SH_NODE_OUTPUT.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_output_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Color",      0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_FLOAT, 1, "Alpha",     1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_FACTOR},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_shader_output.c.