Blender: BLI_noise.h File Reference
BLI_noise.h File Reference
blenlib
Functions
float BLI_hnoise (float noisesize, float x, float y, float z)
float BLI_hnoisep (float noisesize, float x, float y, float z)
float BLI_turbulence (float noisesize, float x, float y, float z, int nr)
float BLI_turbulence1 (float noisesize, float x, float y, float z, int nr)
float BLI_gNoise (float noisesize, float x, float y, float z, int hard, int noisebasis)
float BLI_gTurbulence (float noisesize, float x, float y, float z, int oct, int hard, int noisebasis)
float mg_fBm (float x, float y, float z, float H, float lacunarity, float octaves, int noisebasis)
float mg_MultiFractal (float x, float y, float z, float H, float lacunarity, float octaves, int noisebasis)
float mg_VLNoise (float x, float y, float z, float distortion, int nbas1, int nbas2)
float mg_HeteroTerrain (float x, float y, float z, float H, float lacunarity, float octaves, float offset, int noisebasis)
float mg_HybridMultiFractal (float x, float y, float z, float H, float lacunarity, float octaves, float offset, float gain, int noisebasis)
float mg_RidgedMultiFractal (float x, float y, float z, float H, float lacunarity, float octaves, float offset, float gain, int noisebasis)
void voronoi (float x, float y, float z, float *da, float *pa, float me, int dtype)
float cellNoise (float x, float y, float z)
void cellNoiseV (float x, float y, float z, float *ca)
Detailed Description
Definition in file BLI_noise.h.
Function Documentation
float BLI_gNoise (float noisesize, float x, float y, float z, int hard, int noisebasis)
Definition at line 1319 of file noise.c.
References cellNoiseU(), fabsf, newPerlinU(), orgBlenderNoise(), orgPerlinNoiseU(), voronoi_Cr(), voronoi_F1(), voronoi_F1F2(), voronoi_F2(), voronoi_F3(), and voronoi_F4().
Referenced by M_Noise_noise(), noise_vector(), stucci(), turb(), and wood_int().
float BLI_gTurbulence (float noisesize, float x, float y, float z, int oct, int hard, int noisebasis)
Definition at line 1373 of file noise.c.
References cellNoiseU(), fabsf, i, newPerlinU(), orgBlenderNoise(), orgPerlinNoiseU(), sum(), voronoi_Cr(), voronoi_F1(), voronoi_F1F2(), voronoi_F2(), voronoi_F3(), and voronoi_F4().
Referenced by alter_co(), clouds(), do_physical_effector(), do_rough(), marble_int(), and pointdensitytex().
float BLI_hnoise (float noisesize, float x, float y, float z)
Definition at line 346 of file noise.c.
References orgBlenderNoise().
Referenced by BLI_turbulence(), BLI_turbulence1(), edbm_noise_exec(), and hnoise().
float BLI_hnoisep (float noisesize, float x, float y, float z)
Definition at line 1039 of file noise.c.
References noise3_perlin().
Referenced by hnoisep().
float BLI_turbulence (float noisesize, float x, float y, float z, int nr)
Definition at line 357 of file noise.c.
References BLI_hnoise(), and div.
Referenced by fcm_noise_evaluate(), and turbulence().
float BLI_turbulence1 (float noisesize, float x, float y, float z, int nr)
Definition at line 374 of file noise.c.
References BLI_hnoise(), div, and fabsf.
Referenced by turbulence1().
float cellNoise (float x, float y, float z)
Definition at line 1296 of file noise.c.
References cellNoiseU().
Referenced by M_Noise_cell(), mg_fBm(), mg_HeteroTerrain(), mg_HybridMultiFractal(), mg_MultiFractal(), mg_RidgedMultiFractal(), and mg_VLNoise().
void cellNoiseV (float x, float y, float z, float * ca)
Definition at line 1302 of file noise.c.
References HASHPNT.
Referenced by M_Noise_cell_vector(), and voronoiTex().
float mg_fBm (float x, float y, float z, float H, float lacunarity, float octaves, int noisebasis)
Definition at line 1449 of file noise.c.
References cellNoise(), floorf, i, newPerlin(), orgBlenderNoiseS(), orgPerlinNoise(), powf, voronoi_CrS(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2S(), voronoi_F3S(), and voronoi_F4S().
Referenced by M_Noise_fractal(), and mg_mFractalOrfBmTex().
float mg_HeteroTerrain (float x, float y, float z, float H, float lacunarity, float octaves, float offset, int noisebasis)
Definition at line 1583 of file noise.c.
References cellNoise(), floorf, i, newPerlin(), orgBlenderNoiseS(), orgPerlinNoise(), powf, voronoi_CrS(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2S(), voronoi_F3S(), and voronoi_F4S().
Referenced by M_Noise_hetero_terrain(), and mg_HTerrainTex().
float mg_HybridMultiFractal (float x, float y, float z, float H, float lacunarity, float octaves, float offset, float gain, int noisebasis)
Definition at line 1656 of file noise.c.
References cellNoise(), floorf, i, newPerlin(), orgBlenderNoiseS(), orgPerlinNoise(), powf, voronoi_CrS(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2S(), voronoi_F3S(), and voronoi_F4S().
Referenced by M_Noise_hybrid_multi_fractal(), and mg_ridgedOrHybridMFTex().
float mg_MultiFractal (float x, float y, float z, float H, float lacunarity, float octaves, int noisebasis)
Definition at line 1519 of file noise.c.
References cellNoise(), floorf, i, newPerlin(), orgBlenderNoiseS(), orgPerlinNoise(), powf, voronoi_CrS(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2S(), voronoi_F3S(), and voronoi_F4S().
Referenced by M_Noise_multi_fractal(), and mg_mFractalOrfBmTex().
float mg_RidgedMultiFractal (float x, float y, float z, float H, float lacunarity, float octaves, float offset, float gain, int noisebasis)
Definition at line 1731 of file noise.c.
References cellNoise(), fabsf, i, newPerlin(), orgBlenderNoiseS(), orgPerlinNoise(), powf, voronoi_CrS(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2S(), voronoi_F3S(), and voronoi_F4S().
Referenced by M_Noise_ridged_multi_fractal(), and mg_ridgedOrHybridMFTex().
float mg_VLNoise (float x, float y, float z, float distortion, int nbas1, int nbas2)
Definition at line 1797 of file noise.c.
References cellNoise(), newPerlin(), orgBlenderNoiseS(), orgPerlinNoise(), voronoi_CrS(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2S(), voronoi_F3S(), and voronoi_F4S().
Referenced by M_Noise_variable_lacunarity(), and mg_distNoiseTex().
void voronoi (float x, float y, float z, float * da, float * pa, float me, int dtype)
Definition at line 1116 of file noise.c.
References dist_Chebychev(), dist_Manhattan(), dist_Minkovsky(), dist_Minkovsky4(), dist_MinkovskyH(), dist_Real(), dist_Squared(), HASHPNT, and p.
Referenced by add_node(), M_Noise_voronoi(), svm_voronoi(), voronoi_F1(), voronoi_F1F2(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2(), voronoi_F2S(), voronoi_F3(), voronoi_F3S(), voronoi_F4(), voronoi_F4S(), voronoi_Fn(), voronoi_FnFn(), voronoiTex(), and xml_read_shader_graph().