Blender: curve_intern.h File Reference
curve_intern.h File Reference
curve
Enumerations
enum {
DEL_ALL, DEL_NEXT_CHAR, DEL_PREV_CHAR, DEL_SELECTION,
DEL_NEXT_SEL, DEL_PREV_SEL
}
enum { CASE_LOWER, CASE_UPPER }
enum {
LINE_BEGIN, LINE_END, PREV_CHAR, NEXT_CHAR,
PREV_WORD, NEXT_WORD, PREV_LINE, NEXT_LINE,
PREV_PAGE, NEXT_PAGE
}
Functions
void FONT_OT_text_insert (struct wmOperatorType *ot)
void FONT_OT_line_break (struct wmOperatorType *ot)
void FONT_OT_insert_lorem (struct wmOperatorType *ot)
void FONT_OT_case_toggle (struct wmOperatorType *ot)
void FONT_OT_case_set (struct wmOperatorType *ot)
void FONT_OT_style_toggle (struct wmOperatorType *ot)
void FONT_OT_style_set (struct wmOperatorType *ot)
void FONT_OT_text_copy (struct wmOperatorType *ot)
void FONT_OT_text_cut (struct wmOperatorType *ot)
void FONT_OT_text_paste (struct wmOperatorType *ot)
void FONT_OT_file_paste (struct wmOperatorType *ot)
void FONT_OT_move (struct wmOperatorType *ot)
void FONT_OT_move_select (struct wmOperatorType *ot)
void FONT_OT_delete (struct wmOperatorType *ot)
void FONT_OT_change_character (struct wmOperatorType *ot)
void FONT_OT_change_spacing (struct wmOperatorType *ot)
void FONT_OT_open (struct wmOperatorType *ot)
void FONT_OT_unlink (struct wmOperatorType *ot)
void FONT_OT_textbox_add (struct wmOperatorType *ot)
void FONT_OT_textbox_remove (struct wmOperatorType *ot)
void CURVE_OT_hide (struct wmOperatorType *ot)
void CURVE_OT_reveal (struct wmOperatorType *ot)
void CURVE_OT_separate (struct wmOperatorType *ot)
void CURVE_OT_duplicate (struct wmOperatorType *ot)
void CURVE_OT_delete (struct wmOperatorType *ot)
void CURVE_OT_spline_type_set (struct wmOperatorType *ot)
void CURVE_OT_radius_set (struct wmOperatorType *ot)
void CURVE_OT_spline_weight_set (struct wmOperatorType *ot)
void CURVE_OT_handle_type_set (struct wmOperatorType *ot)
void CURVE_OT_shade_smooth (struct wmOperatorType *ot)
void CURVE_OT_shade_flat (struct wmOperatorType *ot)
void CURVE_OT_tilt_clear (struct wmOperatorType *ot)
void CURVE_OT_smooth (struct wmOperatorType *ot)
void CURVE_OT_smooth_radius (struct wmOperatorType *ot)
void CURVE_OT_primitive_bezier_curve_add (struct wmOperatorType *ot)
void CURVE_OT_primitive_bezier_circle_add (struct wmOperatorType *ot)
void CURVE_OT_primitive_nurbs_curve_add (struct wmOperatorType *ot)
void CURVE_OT_primitive_nurbs_circle_add (struct wmOperatorType *ot)
void CURVE_OT_primitive_nurbs_path_add (struct wmOperatorType *ot)
void SURFACE_OT_primitive_nurbs_surface_curve_add (struct wmOperatorType *ot)
void SURFACE_OT_primitive_nurbs_surface_circle_add (struct wmOperatorType *ot)
void SURFACE_OT_primitive_nurbs_surface_surface_add (struct wmOperatorType *ot)
void SURFACE_OT_primitive_nurbs_surface_cylinder_add (struct wmOperatorType *ot)
void SURFACE_OT_primitive_nurbs_surface_sphere_add (struct wmOperatorType *ot)
void SURFACE_OT_primitive_nurbs_surface_torus_add (struct wmOperatorType *ot)
void CURVE_OT_de_select_first (struct wmOperatorType *ot)
void CURVE_OT_de_select_last (struct wmOperatorType *ot)
void CURVE_OT_select_all (struct wmOperatorType *ot)
void CURVE_OT_select_linked (struct wmOperatorType *ot)
void CURVE_OT_select_linked_pick (struct wmOperatorType *ot)
void CURVE_OT_select_row (struct wmOperatorType *ot)
void CURVE_OT_select_next (struct wmOperatorType *ot)
void CURVE_OT_select_previous (struct wmOperatorType *ot)
void CURVE_OT_select_more (struct wmOperatorType *ot)
void CURVE_OT_select_less (struct wmOperatorType *ot)
void CURVE_OT_select_random (struct wmOperatorType *ot)
void CURVE_OT_select_nth (struct wmOperatorType *ot)
void CURVE_OT_switch_direction (struct wmOperatorType *ot)
void CURVE_OT_subdivide (struct wmOperatorType *ot)
void CURVE_OT_make_segment (struct wmOperatorType *ot)
void CURVE_OT_spin (struct wmOperatorType *ot)
void CURVE_OT_vertex_add (struct wmOperatorType *ot)
void CURVE_OT_extrude (struct wmOperatorType *ot)
void CURVE_OT_cyclic_toggle (struct wmOperatorType *ot)
Variables
const char ED_lorem []
Detailed Description
Definition in file curve_intern.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
DEL_ALL
DEL_NEXT_CHAR
DEL_PREV_CHAR
DEL_SELECTION
DEL_NEXT_SEL
DEL_PREV_SEL
Definition at line 42 of file curve_intern.h.
anonymous enum
Enumerator:
CASE_LOWER
CASE_UPPER
Definition at line 43 of file curve_intern.h.
anonymous enum
Enumerator:
LINE_BEGIN
LINE_END
PREV_CHAR
NEXT_CHAR
PREV_WORD
NEXT_WORD
PREV_LINE
NEXT_LINE
PREV_PAGE
NEXT_PAGE
Definition at line 44 of file curve_intern.h.
Function Documentation
void CURVE_OT_cyclic_toggle (struct wmOperatorType * ot)
Definition at line 4856 of file editcurve.c.
References wmOperatorType::description, direction_items, ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, toggle_cyclic_exec(), and toggle_cyclic_invoke().
Referenced by ED_operatortypes_curve().
void CURVE_OT_de_select_first (struct wmOperatorType * ot)
Definition at line 2530 of file editcurve.c.
References de_select_first_exec(), ED_operator_editcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_curve().
void CURVE_OT_de_select_last (struct wmOperatorType * ot)
Definition at line 2554 of file editcurve.c.
References de_select_last_exec(), ED_operator_editcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_curve().
void CURVE_OT_delete (struct wmOperatorType * ot)
Definition at line 5976 of file editcurve.c.
References delete_exec(), delete_invoke(), wmOperatorType::description, ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void CURVE_OT_duplicate (struct wmOperatorType * ot)
Definition at line 5606 of file editcurve.c.
References wmOperatorType::description, duplicate_exec(), ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_curve().
void CURVE_OT_extrude (struct wmOperatorType * ot)
Definition at line 4733 of file editcurve.c.
References wmOperatorType::description, ED_operator_editsurfcurve(), wmOperatorType::exec, extrude_exec(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, TFM_TRANSLATION, and transform_mode_types.
Referenced by ED_operatortypes_curve().
void CURVE_OT_handle_type_set (struct wmOperatorType * ot)
Definition at line 3570 of file editcurve.c.
References wmOperatorType::description, ED_operator_editcurve(), wmOperatorType::exec, wmOperatorType::flag, HD_AUTO, HD_VECT, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), set_handle_type_exec(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_curve().
void CURVE_OT_hide (struct wmOperatorType * ot)
Definition at line 2709 of file editcurve.c.
References ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, hide_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void CURVE_OT_make_segment (struct wmOperatorType * ot)
Definition at line 4116 of file editcurve.c.
References ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, make_segment_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_curve().
void CURVE_OT_primitive_bezier_circle_add (struct wmOperatorType * ot)
Definition at line 6648 of file editcurve.c.
References add_primitive_bezier_circle_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_curve().
void CURVE_OT_primitive_bezier_curve_add (struct wmOperatorType * ot)
Definition at line 6625 of file editcurve.c.
References add_primitive_bezier_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_curve().
void CURVE_OT_primitive_nurbs_circle_add (struct wmOperatorType * ot)
Definition at line 6694 of file editcurve.c.
References add_primitive_nurbs_circle_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_curve().
void CURVE_OT_primitive_nurbs_curve_add (struct wmOperatorType * ot)
Definition at line 6671 of file editcurve.c.
References add_primitive_nurbs_curve_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_curve().
void CURVE_OT_primitive_nurbs_path_add (struct wmOperatorType * ot)
Definition at line 6717 of file editcurve.c.
References add_primitive_curve_path_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_curve().
void CURVE_OT_radius_set (struct wmOperatorType * ot)
Definition at line 2126 of file editcurve.c.
References wmOperatorType::description, ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), set_radius_exec(), wmOperatorType::srna, and WM_operator_props_popup().
Referenced by ED_operatortypes_curve().
void CURVE_OT_reveal (struct wmOperatorType * ot)
Definition at line 2769 of file editcurve.c.
References ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and reveal_exec().
Referenced by ED_operatortypes_curve().
void CURVE_OT_select_all (struct wmOperatorType * ot)
Definition at line 2635 of file editcurve.c.
References de_select_all_exec(), ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_properties_select_all().
Referenced by ED_operatortypes_curve().
void CURVE_OT_select_less (struct wmOperatorType * ot)
Definition at line 5378 of file editcurve.c.
References ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and select_less_exec().
Referenced by ED_operatortypes_curve().
void CURVE_OT_select_linked (struct wmOperatorType * ot)
Definition at line 4938 of file editcurve.c.
References ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, select_linked_exec(), and select_linked_invoke().
Referenced by ED_operatortypes_curve().
void CURVE_OT_select_linked_pick (struct wmOperatorType * ot)
Definition at line 4998 of file editcurve.c.
References ED_operator_editsurfcurve_region_view3d(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), select_linked_pick_invoke(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void CURVE_OT_select_more (struct wmOperatorType * ot)
Definition at line 5217 of file editcurve.c.
References ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and select_more_exec().
Referenced by ED_operatortypes_curve().
void CURVE_OT_select_next (struct wmOperatorType * ot)
Definition at line 5103 of file editcurve.c.
References ED_operator_editcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and select_next_exec().
Referenced by ED_operatortypes_curve().
void CURVE_OT_select_nth (struct wmOperatorType * ot)
Definition at line 5577 of file editcurve.c.
References wmOperatorType::description, ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), select_nth_exec(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void CURVE_OT_select_previous (struct wmOperatorType * ot)
Definition at line 5130 of file editcurve.c.
References ED_operator_editcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and select_previous_exec().
Referenced by ED_operatortypes_curve().
void CURVE_OT_select_random (struct wmOperatorType * ot)
Definition at line 5441 of file editcurve.c.
References ED_operator_editsurfcurve(), wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_percentage(), select_random_exec(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void CURVE_OT_select_row (struct wmOperatorType * ot)
Definition at line 5076 of file editcurve.c.
References ED_operator_editsurf(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and select_row_exec().
Referenced by ED_operatortypes_curve().
void CURVE_OT_separate (struct wmOperatorType * ot)
Definition at line 1414 of file editcurve.c.
References ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and separate_exec().
Referenced by ED_operatortypes_curve().
void CURVE_OT_shade_flat (struct wmOperatorType * ot)
Definition at line 6040 of file editcurve.c.
References ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and shade_smooth_exec().
Referenced by ED_operatortypes_curve().
void CURVE_OT_shade_smooth (struct wmOperatorType * ot)
Definition at line 6026 of file editcurve.c.
References ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and shade_smooth_exec().
Referenced by ED_operatortypes_curve().
void CURVE_OT_smooth (struct wmOperatorType * ot)
Definition at line 2203 of file editcurve.c.
References wmOperatorType::description, ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and smooth_exec().
Referenced by ED_operatortypes_curve().
void CURVE_OT_smooth_radius (struct wmOperatorType * ot)
Definition at line 2378 of file editcurve.c.
References wmOperatorType::description, ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and smooth_radius_exec().
Referenced by ED_operatortypes_curve().
void CURVE_OT_spin (struct wmOperatorType * ot)
Definition at line 4351 of file editcurve.c.
References ED_operator_editsurf(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_vector(), RNA_def_float_vector_xyz(), spin_exec(), spin_invoke(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void CURVE_OT_spline_type_set (struct wmOperatorType * ot)
Definition at line 3528 of file editcurve.c.
References CU_BEZIER, CU_NURBS, CU_POLY, wmOperatorType::description, ED_operator_editcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), set_spline_type_exec(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_curve().
void CURVE_OT_spline_weight_set (struct wmOperatorType * ot)
Definition at line 2074 of file editcurve.c.
References wmOperatorType::description, ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_factor(), set_goal_weight_exec(), wmOperatorType::srna, and WM_operator_props_popup().
Referenced by ED_operatortypes_curve().
void CURVE_OT_subdivide (struct wmOperatorType * ot)
Definition at line 3203 of file editcurve.c.
References wmOperatorType::description, ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_int(), RNA_def_property_flag(), wmOperatorType::srna, and subdivide_exec().
Referenced by ED_operatortypes_curve().
void CURVE_OT_switch_direction (struct wmOperatorType * ot)
Definition at line 2026 of file editcurve.c.
References wmOperatorType::description, ED_operator_editsurfcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and switch_direction_exec().
Referenced by ED_operatortypes_curve().
void CURVE_OT_tilt_clear (struct wmOperatorType * ot)
Definition at line 6911 of file editcurve.c.
References clear_tilt_exec(), ED_operator_editcurve(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_curve().
void CURVE_OT_vertex_add (struct wmOperatorType * ot)
Definition at line 4685 of file editcurve.c.
References add_vertex_exec(), add_vertex_invoke(), ED_operator_editcurve(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_vector_xyz(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void FONT_OT_case_set (struct wmOperatorType * ot)
Definition at line 1544 of file editfont.c.
References CASE_LOWER, wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), set_case_exec(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void FONT_OT_case_toggle (struct wmOperatorType * ot)
Definition at line 1587 of file editfont.c.
References wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and toggle_case_exec().
Referenced by ED_operatortypes_curve().
void FONT_OT_change_character (struct wmOperatorType * ot)
Definition at line 1032 of file editfont.c.
References change_character_exec(), wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void FONT_OT_change_spacing (struct wmOperatorType * ot)
Definition at line 987 of file editfont.c.
References change_spacing_exec(), wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void FONT_OT_delete (struct wmOperatorType * ot)
Definition at line 1165 of file editfont.c.
References DEL_ALL, delete_exec(), wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void FONT_OT_file_paste (struct wmOperatorType * ot)
Definition at line 409 of file editfont.c.
References wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, paste_file_exec(), paste_file_invoke(), wmOperatorType::poll, TEXTFILE, WM_FILESEL_FILEPATH, and WM_operator_properties_filesel().
Referenced by ED_operatortypes_curve().
void FONT_OT_insert_lorem (struct wmOperatorType * ot)
Definition at line 321 of file editfont.c.
References wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, insert_lorem_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_curve().
void FONT_OT_line_break (struct wmOperatorType * ot)
Definition at line 1075 of file editfont.c.
References wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, line_break_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void FONT_OT_move (struct wmOperatorType * ot)
Definition at line 918 of file editfont.c.
References wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, LINE_BEGIN, move_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void FONT_OT_move_select (struct wmOperatorType * ot)
Definition at line 945 of file editfont.c.
References wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, LINE_BEGIN, move_select_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void FONT_OT_open (struct wmOperatorType * ot)
Definition at line 1685 of file editfont.c.
References wmOperatorType::cancel, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, font_open_cancel(), font_open_exec(), FTFONTFILE, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, open_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, WM_FILESEL_FILEPATH, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by ED_operatortypes_curve().
void FONT_OT_style_set (struct wmOperatorType * ot)
Definition at line 611 of file editfont.c.
References CU_CHINFO_BOLD, wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_enum(), set_style_exec(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void FONT_OT_style_toggle (struct wmOperatorType * ot)
Definition at line 649 of file editfont.c.
References CU_CHINFO_BOLD, wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, and toggle_style_exec().
Referenced by ED_operatortypes_curve().
void FONT_OT_text_copy (struct wmOperatorType * ot)
Definition at line 692 of file editfont.c.
References copy_text_exec(), wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by ED_operatortypes_curve().
void FONT_OT_text_cut (struct wmOperatorType * ot)
Definition at line 723 of file editfont.c.
References cut_text_exec(), wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_curve().
void FONT_OT_text_insert (struct wmOperatorType * ot)
Definition at line 1326 of file editfont.c.
References wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, insert_text_exec(), insert_text_invoke(), wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_curve().
void FONT_OT_text_paste (struct wmOperatorType * ot)
Definition at line 781 of file editfont.c.
References wmOperatorType::description, ED_operator_editfont(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, paste_text_exec(), and wmOperatorType::poll.
Referenced by ED_operatortypes_curve().
void FONT_OT_textbox_add (struct wmOperatorType * ot)
Definition at line 1365 of file editfont.c.
References wmOperatorType::description, ED_operator_object_active_editable_font(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and textbox_add_exec().
Referenced by ED_operatortypes_curve().
void FONT_OT_textbox_remove (struct wmOperatorType * ot)
Definition at line 1408 of file editfont.c.
References wmOperatorType::description, ED_operator_object_active_editable_font(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, and textbox_remove_exec().
Referenced by ED_operatortypes_curve().
void FONT_OT_unlink (struct wmOperatorType * ot)
Definition at line 1728 of file editfont.c.
References wmOperatorType::description, wmOperatorType::exec, font_unlink_exec(), wmOperatorType::idname, and wmOperatorType::name.
Referenced by ED_operatortypes_curve().
void SURFACE_OT_primitive_nurbs_surface_circle_add (struct wmOperatorType * ot)
Definition at line 6764 of file editcurve.c.
References add_primitive_nurbs_surface_circle_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_curve().
void SURFACE_OT_primitive_nurbs_surface_curve_add (struct wmOperatorType * ot)
Definition at line 6741 of file editcurve.c.
References add_primitive_nurbs_surface_curve_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_curve().
void SURFACE_OT_primitive_nurbs_surface_cylinder_add (struct wmOperatorType * ot)
Definition at line 6810 of file editcurve.c.
References add_primitive_nurbs_surface_cylinder_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_curve().
void SURFACE_OT_primitive_nurbs_surface_sphere_add (struct wmOperatorType * ot)
Definition at line 6833 of file editcurve.c.
References add_primitive_nurbs_surface_sphere_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_curve().
void SURFACE_OT_primitive_nurbs_surface_surface_add (struct wmOperatorType * ot)
Definition at line 6787 of file editcurve.c.
References add_primitive_nurbs_surface_surface_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_curve().
void SURFACE_OT_primitive_nurbs_surface_torus_add (struct wmOperatorType * ot)
Definition at line 6856 of file editcurve.c.
References add_primitive_nurbs_surface_torus_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_curve().
Variable Documentation
const char ED_lorem[]
Definition at line 28 of file lorem.c.
Referenced by insert_lorem_exec().