Blender: iTaSC::SceneLock Class Reference
iTaSC::SceneLock Class Reference
Public Member Functions
SceneLock (Scene *scene)
virtual ~SceneLock ()
void setRange (Range &range)
virtual void lockJoint (unsigned int q_nr, unsigned int ndof)
virtual void lockJoint (unsigned int q_nr, unsigned int ndof, double *qdot)
Detailed Description
Definition at line 18 of file Scene.cpp.
Constructor & Destructor Documentation
iTaSC::SceneLock::SceneLock (Scene * scene) [inline]
Definition at line 24 of file Scene.cpp.
virtual iTaSC::SceneLock::~SceneLock () [inline, virtual]
Definition at line 26 of file Scene.cpp.
Member Function Documentation
virtual void iTaSC::SceneLock::lockJoint (unsigned int q_nr, unsigned int ndof) [inline, virtual]
Implements iTaSC::ControlledObject::JointLockCallback.
Definition at line 33 of file Scene.cpp.
References iTaSC::project(), and iTaSC::Range::start.
virtual void iTaSC::SceneLock::lockJoint (unsigned int q_nr, unsigned int ndof, double * qdot) [inline, virtual]
Implements iTaSC::ControlledObject::JointLockCallback.
Definition at line 39 of file Scene.cpp.
References i, iTaSC::project(), and iTaSC::Range::start.
void iTaSC::SceneLock::setRange (Range & range) [inline]
Definition at line 28 of file Scene.cpp.
Referenced by iTaSC::Scene::update().
The documentation for this class was generated from the following file:
Scene.cpp