Blender: collada_internal.h File Reference
collada_internal.h File Reference
COLLADA
#include <string>
#include <vector>
#include <map>
#include "COLLADAFWFileInfo.h"
#include "Math/COLLADABUMathMatrix4.h"
#include "DNA_armature_types.h"
#include "DNA_material_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_math.h"
Classes
class UnitConverter
class TransformBase
Functions
void clear_global_id_map ()
std::string translate_id (const std::string &id)
std::string id_name (void *id)
std::string get_geometry_id (Object *ob)
std::string get_light_id (Object *ob)
std::string get_joint_id (Bone *bone, Object *ob_arm)
std::string get_camera_id (Object *ob)
std::string get_material_id (Material *mat)
bool has_object_type (Scene *sce, short obtype)
Detailed Description
Definition in file collada_internal.h.
Function Documentation
void clear_global_id_map ()
Definition at line 193 of file collada_internal.cpp.
References global_id_map.
Referenced by DocumentExporter::exportCurrentScene().
std::string get_camera_id (Object * ob)
Definition at line 269 of file collada_internal.cpp.
References id_name(), and translate_id().
Referenced by AnimationExporter::dae_animation(), and CamerasExporter::operator()().
std::string get_geometry_id (Object * ob)
Definition at line 254 of file collada_internal.cpp.
References Object::data, id_name(), and translate_id().
Referenced by GeometryExporter::operator()().
std::string get_joint_id (Bone * bone, Object * ob_arm)
Definition at line 264 of file collada_internal.cpp.
References Bone::name, and translate_id().
Referenced by ArmatureExporter::add_instance_controller().
std::string get_light_id (Object * ob)
Definition at line 259 of file collada_internal.cpp.
References id_name(), and translate_id().
Referenced by AnimationExporter::dae_animation(), and LightsExporter::operator()().
std::string get_material_id (Material * mat)
Definition at line 274 of file collada_internal.cpp.
References id_name(), and translate_id().
Referenced by InstanceWriter::add_material_bindings(), and MaterialsExporter::operator()().
bool has_object_type (Scene * sce, short obtype)
Definition at line 279 of file collada_internal.cpp.
References Scene::base, Object::data, ListBase::first, Base::next, Base::object, and Object::type.
Referenced by DocumentExporter::exportCurrentScene().
std::string id_name (void * id)
Definition at line 249 of file collada_internal.cpp.
Referenced by InstanceWriter::add_material_bindings(), GeometryExporter::createPolylist(), EffectsExporter::createTexture(), AnimationExporter::dae_animation(), AnimationExporter::dae_baked_animation(), DocumentExporter::exportCurrentScene(), SceneExporter::exportScene(), get_camera_id(), get_geometry_id(), get_light_id(), get_material_id(), AnimationExporter::getObjectBoneName(), ForEachMaterialFunctor< Functor >::operator()(), MaterialsExporter::operator()(), LightsExporter::operator()(), ImagesExporter::operator()(), GeometryExporter::operator()(), EffectsExporter::operator()(), CamerasExporter::operator()(), and AnimationExporter::sample_and_write_bone_animation().
std::string translate_id (const std::string & id)
Look at documentation of translate_map
Definition at line 199 of file collada_internal.cpp.
References PixelFormat::convert(), global_id_map, i, Scene::id, size(), translate_name_map, and translate_start_name_map.
Referenced by InstanceWriter::add_material_bindings(), GeometryExporter::createPolylist(), EffectsExporter::createTexture(), AnimationExporter::dae_animation(), AnimationExporter::dae_baked_animation(), AnimationExporter::dae_bone_animation(), DocumentExporter::exportCurrentScene(), SceneExporter::exportScene(), get_camera_id(), get_geometry_id(), get_joint_id(), get_light_id(), get_material_id(), ForEachMaterialFunctor< Functor >::operator()(), MaterialsExporter::operator()(), ImagesExporter::operator()(), and EffectsExporter::operator()().