Blender: bmesh_py_types_customdata.c File Reference
bmesh_py_types_customdata.c File Reference
#include <Python.h>
#include "BLI_string.h"
#include "BLI_math_vector.h"
#include "bmesh.h"
#include "bmesh_py_types.h"
#include "bmesh_py_types_customdata.h"
#include "bmesh_py_types_meshdata.h"
#include "../mathutils/mathutils.h"
#include "BKE_customdata.h"
#include "DNA_meshdata_types.h"
Functions
static CustomData * bpy_bm_customdata_get (BMesh *bm, char htype)
static CustomDataLayer * bpy_bmlayeritem_get (BPy_BMLayerItem *self)
PyDoc_STRVAR (bpy_bmlayeraccess_collection__float_doc,"Generic float custom-data layer.\n\ntype: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__int_doc,"Generic int custom-data layer.\n\ntype: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__string_doc,"Generic string custom-data layer (exposed as bytes, 255 max length).\n\ntype: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__deform_doc,"Vertex deform weight :class:`BMDeformVert` (TODO).\n\ntype: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__shape_doc,"Vertex shapekey absolute location (as a 3D Vector).\n\n:type: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__bevel_weight_doc,"Bevel weight float in [0 - 1].\n\n:type: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__crease_doc,"Edge crease for subsurf - float in [0 - 1].\n\n:type: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__tex_doc,"Accessor for :class:`BMTexPoly` layer (TODO).\n\ntype: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__uv_doc,"Accessor for :class:`BMLoopUV` UV (as a 2D Vector).\n\ntype: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__color_doc,"Accessor for vertex color layer.\n\ntype: :class:`BMLayerCollection`")
static PyObject * bpy_bmlayeraccess_collection_get (BPy_BMLayerAccess *self, void *flag)
PyDoc_STRVAR (bpy_bmlayercollection_active_doc,"This meshes vert sequence (read-only).\n\n:type: :class:`BMVertSeq`")
static PyObject * bpy_bmlayercollection_active_get (BPy_BMLayerItem *self, void *UNUSED(flag))
PyDoc_STRVAR (bpy_bmlayercollection_name_doc,"The layers unique name (read-only).\n\n:type: string")
static PyObject * bpy_bmlayeritem_name_get (BPy_BMLayerItem *self, void *UNUSED(flag))
PyDoc_STRVAR (bpy_bmlayercollection_new_doc,".. method:: new(name)\n""\n"" Create a new layer\n""\n"" :arg name: Optional name argument (will be made unique).\n"" :type name: string\n"" :return: The newly created layer.\n"" :rtype: :class:`BMLayerItem`\n")
static PyObject * bpy_bmlayercollection_new (BPy_BMLayerCollection *self, PyObject *args)
PyDoc_STRVAR (bpy_bmlayercollection_remove_doc,".. method:: remove(layer)\n""\n"" Remove a layer\n""\n"" :arg layer: The layer to remove.\n"" :type layer: :class:`BMLayerItem`\n")
static PyObject * bpy_bmlayercollection_remove (BPy_BMLayerCollection *self, BPy_BMLayerItem *value)
PyDoc_STRVAR (bpy_bmlayercollection_keys_doc,".. method:: keys()\n""\n"" Return the identifiers of collection members\n"" (matching pythons dict.keys() functionality).\n""\n"" :return: the identifiers for each member of this collection.\n"" :rtype: list of strings\n")
static PyObject * bpy_bmlayercollection_keys (BPy_BMLayerCollection *self)
PyDoc_STRVAR (bpy_bmlayercollection_values_doc,".. method:: items()\n""\n"" Return the identifiers of collection members\n"" (matching pythons dict.items() functionality).\n""\n"" :return: (key, value) pairs for each member of this collection.\n"" :rtype: list of tuples\n")
static PyObject * bpy_bmlayercollection_values (BPy_BMLayerCollection *self)
PyDoc_STRVAR (bpy_bmlayercollection_items_doc,".. method:: values()\n""\n"" Return the values of collection\n"" (matching pythons dict.values() functionality).\n""\n"" :return: the members of this collection.\n"" :rtype: list\n")
static PyObject * bpy_bmlayercollection_items (BPy_BMLayerCollection *self)
PyDoc_STRVAR (bpy_bmlayercollection_get_doc,".. method:: get(key, default=None)\n""\n"" Returns the value of the layer matching the key or default\n"" when not found (matches pythons dictionary function of the same name).\n""\n"" :arg key: The key associated with the layer.\n"" :type key: string\n"" :arg default: Optional argument for the value to return if\n"" *key* is not found.\n"" :type default: Undefined\n")
static PyObject * bpy_bmlayercollection_get (BPy_BMLayerCollection *self, PyObject *args)
static Py_ssize_t bpy_bmlayercollection_length (BPy_BMLayerCollection *self)
static PyObject * bpy_bmlayercollection_subscript_str (BPy_BMLayerCollection *self, const char *keyname)
static PyObject * bpy_bmlayercollection_subscript_int (BPy_BMLayerCollection *self, int keynum)
static PyObject * bpy_bmlayercollection_subscript_slice (BPy_BMLayerCollection *self, Py_ssize_t start, Py_ssize_t stop)
static PyObject * bpy_bmlayercollection_subscript (BPy_BMLayerCollection *self, PyObject *key)
static int bpy_bmlayercollection_contains (BPy_BMLayerCollection *self, PyObject *value)
static PyObject * bpy_bmlayercollection_iter (BPy_BMLayerCollection *self)
PyDoc_STRVAR (bpy_bmlayeraccess_type_doc,"Exposes custom-data layer attributes.")
PyDoc_STRVAR (bpy_bmlayercollection_type_doc,"Gives access to a collection of custom-data layers of the same type and behaves like python dictionaries, ""except for the ability to do list like index access.")
PyDoc_STRVAR (bpy_bmlayeritem_type_doc,"Exposes a single custom data layer, ""their main purpose is for use as item accessors to custom-data when used with vert/edge/face/loop data.")
PyObject * BPy_BMLayerAccess_CreatePyObject (BMesh *bm, const char htype)
PyObject * BPy_BMLayerCollection_CreatePyObject (BMesh *bm, const char htype, int type)
PyObject * BPy_BMLayerItem_CreatePyObject (BMesh *bm, const char htype, int type, int index)
void BPy_BM_init_types_customdata (void)
static void * bpy_bmlayeritem_ptr_get (BPy_BMElem *py_ele, BPy_BMLayerItem *py_layer)
PyObject * BPy_BMLayerItem_GetItem (BPy_BMElem *py_ele, BPy_BMLayerItem *py_layer)
BMElem.__getitem__()
int BPy_BMLayerItem_SetItem (BPy_BMElem *py_ele, BPy_BMLayerItem *py_layer, PyObject *py_value)
Variables
static PyGetSetDef bpy_bmlayeraccess_vert_getseters []
static PyGetSetDef bpy_bmlayeraccess_edge_getseters []
static PyGetSetDef bpy_bmlayeraccess_face_getseters []
static PyGetSetDef bpy_bmlayeraccess_loop_getseters []
static PyGetSetDef bpy_bmlayercollection_getseters []
static PyGetSetDef bpy_bmlayeritem_getseters []
static struct PyMethodDef bpy_bmelemseq_methods []
static PySequenceMethods bpy_bmlayercollection_as_sequence
static PyMappingMethods bpy_bmlayercollection_as_mapping
PyTypeObject BPy_BMLayerAccessVert_Type = {{{0}}}
PyTypeObject BPy_BMLayerAccessEdge_Type = {{{0}}}
PyTypeObject BPy_BMLayerAccessFace_Type = {{{0}}}
PyTypeObject BPy_BMLayerAccessLoop_Type = {{{0}}}
PyTypeObject BPy_BMLayerCollection_Type = {{{0}}}
PyTypeObject BPy_BMLayerItem_Type = {{{0}}}
Detailed Description
This file defines the types for 'BMesh.verts/edges/faces/loops.layers' customdata layer access.
Definition in file bmesh_py_types_customdata.c.
Function Documentation
static CustomData* bpy_bm_customdata_get (BMesh * bm, char htype) [static]
Definition at line 50 of file bmesh_py_types_customdata.c.
References BLI_assert, BM_EDGE, BM_FACE, BM_LOOP, BM_VERT, BMesh::edata, BMesh::ldata, NULL, BMesh::pdata, and BMesh::vdata.
Referenced by bpy_bmlayercollection_active_get(), bpy_bmlayercollection_contains(), bpy_bmlayercollection_get(), bpy_bmlayercollection_items(), bpy_bmlayercollection_keys(), bpy_bmlayercollection_length(), bpy_bmlayercollection_new(), bpy_bmlayercollection_remove(), bpy_bmlayercollection_subscript_str(), bpy_bmlayercollection_values(), bpy_bmlayeritem_get(), and bpy_bmlayeritem_ptr_get().
void BPy_BM_init_types_customdata (void)
Definition at line 725 of file bmesh_py_types_customdata.c.
References bpy_bmelemseq_methods, bpy_bmlayeraccess_edge_getseters, bpy_bmlayeraccess_face_getseters, bpy_bmlayeraccess_loop_getseters, bpy_bmlayeraccess_vert_getseters, bpy_bmlayercollection_as_mapping, bpy_bmlayercollection_as_sequence, bpy_bmlayercollection_getseters, bpy_bmlayercollection_iter(), bpy_bmlayeritem_getseters, and NULL.
Referenced by BPyInit_bmesh().
static PyObject* bpy_bmlayeraccess_collection_get (BPy_BMLayerAccess * self, void * flag) [static]
Definition at line 116 of file bmesh_py_types_customdata.c.
References BPY_BM_CHECK_OBJ, BPy_BMLayerCollection_CreatePyObject(), and GET_INT_FROM_POINTER.
PyObject* BPy_BMLayerAccess_CreatePyObject (BMesh * bm, const char htype)
Definition at line 681 of file bmesh_py_types_customdata.c.
References BLI_assert, BM_EDGE, BM_FACE, BM_LOOP, BM_VERT, BPy_BMLayerAccessEdge_Type, BPy_BMLayerAccessFace_Type, BPy_BMLayerAccessLoop_Type, BPy_BMLayerAccessVert_Type, and NULL.
Referenced by bpy_bmelemseq_layers_get().
static PyObject* bpy_bmlayercollection_active_get (BPy_BMLayerItem * self, void * UNUSEDflag) [static]
Definition at line 129 of file bmesh_py_types_customdata.c.
References BPY_BM_CHECK_OBJ, bpy_bm_customdata_get(), BPy_BMLayerItem_CreatePyObject(), CustomData_get_active_layer_index(), CustomData_get_layer_index(), and data.
static int bpy_bmlayercollection_contains (BPy_BMLayerCollection * self, PyObject * value) [static]
Definition at line 598 of file bmesh_py_types_customdata.c.
References BPY_BM_CHECK_INT, bpy_bm_customdata_get(), CustomData_get_named_layer_index(), data, and NULL.
PyObject* BPy_BMLayerCollection_CreatePyObject (BMesh * bm, const char htype, int type)
Definition at line 705 of file bmesh_py_types_customdata.c.
Referenced by bpy_bmlayeraccess_collection_get().
static PyObject* bpy_bmlayercollection_get (BPy_BMLayerCollection * self, PyObject * args) [static]
Definition at line 428 of file bmesh_py_types_customdata.c.
References BPY_BM_CHECK_OBJ, bpy_bm_customdata_get(), BPy_BMLayerItem_CreatePyObject(), CustomData_get_layer_index(), CustomData_get_named_layer_index(), data, and NULL.
static PyObject* bpy_bmlayercollection_items (BPy_BMLayerCollection * self) [static]
Definition at line 390 of file bmesh_py_types_customdata.c.
References BPY_BM_CHECK_OBJ, bpy_bm_customdata_get(), BPy_BMLayerItem_CreatePyObject(), CustomData_get_layer_index(), CustomData_number_of_layers(), and data.
static PyObject* bpy_bmlayercollection_iter (BPy_BMLayerCollection * self) [static]
Definition at line 640 of file bmesh_py_types_customdata.c.
References BPY_BM_CHECK_OBJ, bpy_bmlayercollection_subscript_slice(), and NULL.
Referenced by BPy_BM_init_types_customdata().
static PyObject* bpy_bmlayercollection_keys (BPy_BMLayerCollection * self) [static]
Definition at line 318 of file bmesh_py_types_customdata.c.
References BPY_BM_CHECK_OBJ, bpy_bm_customdata_get(), CustomData_get_layer_index(), CustomData_number_of_layers(), data, CustomData::layers, and CustomDataLayer::name.
static Py_ssize_t bpy_bmlayercollection_length (BPy_BMLayerCollection * self) [static]
Definition at line 470 of file bmesh_py_types_customdata.c.
References BPY_BM_CHECK_INT, bpy_bm_customdata_get(), CustomData_number_of_layers(), and data.
Referenced by bpy_bmlayercollection_subscript(), bpy_bmlayercollection_subscript_int(), and bpy_bmlayercollection_subscript_slice().
static PyObject* bpy_bmlayercollection_new (BPy_BMLayerCollection * self, PyObject * args) [static]
Definition at line 244 of file bmesh_py_types_customdata.c.
References BLI_assert, BM_data_layer_add(), BM_data_layer_add_named(), BPY_BM_CHECK_OBJ, bpy_bm_customdata_get(), BPy_BMLayerItem_CreatePyObject(), CustomData_number_of_layers(), data, and NULL.
static PyObject* bpy_bmlayercollection_remove (BPy_BMLayerCollection * self, BPy_BMLayerItem * value) [static]
Definition at line 279 of file bmesh_py_types_customdata.c.
References BPy_BMLayerItem::bm, BM_data_layer_free_n(), BPY_BM_CHECK_OBJ, bpy_bm_customdata_get(), BPy_BMLayerItem_Check, data, BPy_BMLayerItem::htype, BPy_BMLayerItem::index, NULL, and BPy_BMLayerItem::type.
static PyObject* bpy_bmlayercollection_subscript (BPy_BMLayerCollection * self, PyObject * key) [static]
Definition at line 542 of file bmesh_py_types_customdata.c.
References bpy_bmlayercollection_length(), bpy_bmlayercollection_subscript_int(), bpy_bmlayercollection_subscript_slice(), bpy_bmlayercollection_subscript_str(), i, len(), NULL, and step().
static PyObject* bpy_bmlayercollection_subscript_int (BPy_BMLayerCollection * self, int keynum) [static]
Definition at line 502 of file bmesh_py_types_customdata.c.
References BPY_BM_CHECK_OBJ, bpy_bmlayercollection_length(), BPy_BMLayerItem_CreatePyObject(), len(), and NULL.
Referenced by bpy_bmlayercollection_subscript().
static PyObject* bpy_bmlayercollection_subscript_slice (BPy_BMLayerCollection * self, Py_ssize_t start, Py_ssize_t stop) [static]
Definition at line 521 of file bmesh_py_types_customdata.c.
References BPY_BM_CHECK_OBJ, bpy_bmlayercollection_length(), BPy_BMLayerItem_CreatePyObject(), and len().
Referenced by bpy_bmlayercollection_iter(), and bpy_bmlayercollection_subscript().
static PyObject* bpy_bmlayercollection_subscript_str (BPy_BMLayerCollection * self, const char * keyname) [static]
Definition at line 481 of file bmesh_py_types_customdata.c.
References BPY_BM_CHECK_OBJ, bpy_bm_customdata_get(), BPy_BMLayerItem_CreatePyObject(), CustomData_get_layer_index(), CustomData_get_named_layer_index(), data, and NULL.
Referenced by bpy_bmlayercollection_subscript().
static PyObject* bpy_bmlayercollection_values (BPy_BMLayerCollection * self) [static]
Definition at line 353 of file bmesh_py_types_customdata.c.
References BPY_BM_CHECK_OBJ, bpy_bm_customdata_get(), BPy_BMLayerItem_CreatePyObject(), CustomData_get_layer_index(), CustomData_number_of_layers(), data, CustomData::layers, and CustomDataLayer::name.
PyObject* BPy_BMLayerItem_CreatePyObject (BMesh * bm, const char htype, int type, int index)
Definition at line 714 of file bmesh_py_types_customdata.c.
Referenced by bpy_bmlayercollection_active_get(), bpy_bmlayercollection_get(), bpy_bmlayercollection_items(), bpy_bmlayercollection_new(), bpy_bmlayercollection_subscript_int(), bpy_bmlayercollection_subscript_slice(), bpy_bmlayercollection_subscript_str(), and bpy_bmlayercollection_values().
static CustomDataLayer* bpy_bmlayeritem_get (BPy_BMLayerItem * self) [static]
Definition at line 63 of file bmesh_py_types_customdata.c.
References bpy_bm_customdata_get(), CustomData_get_layer_index_n(), data, CustomData::layers, and NULL.
Referenced by bpy_bmlayeritem_name_get().
PyObject* BPy_BMLayerItem_GetItem (BPy_BMElem * py_ele, BPy_BMLayerItem * py_layer)
BMElem.__getitem__()
assume all error checks are done, eg:
uv = vert[uv_layer]
Definition at line 853 of file bmesh_py_types_customdata.c.
References BLI_strnlen(), BPy_BMDeformVert_CreatePyObject(), bpy_bmlayeritem_ptr_get(), BPy_BMLoopColor_CreatePyObject(), BPy_BMLoopUV_CreatePyObject(), CD_BWEIGHT, CD_CREASE, CD_MDEFORMVERT, CD_MLOOPCOL, CD_MLOOPUV, CD_MTEXPOLY, CD_PROP_FLT, CD_PROP_INT, CD_PROP_STR, CD_SHAPEKEY, NULL, Py_WRAP, MStringProperty::s, BPy_BMLayerItem::type, UNLIKELY, and Vector_CreatePyObject().
Referenced by bpy_bmelem_subscript().
static PyObject* bpy_bmlayeritem_name_get (BPy_BMLayerItem * self, void * UNUSEDflag) [static]
Definition at line 151 of file bmesh_py_types_customdata.c.
References BPY_BM_CHECK_OBJ, bpy_bmlayeritem_get(), CustomDataLayer::name, and NULL.
static void* bpy_bmlayeritem_ptr_get (BPy_BMElem * py_ele, BPy_BMLayerItem * py_layer) [static]
helper function for get/set, NULL return means the error is set
Definition at line 804 of file bmesh_py_types_customdata.c.
References BPy_BMLayerItem::bm, BPy_BMElem::bm, bpy_bm_customdata_get(), BPy_BMElem_StringFromHType_ex(), BPy_BMLayerItem_Check, CustomData_bmesh_get_n(), data, BMHeader::data, BPy_BMElem::ele, BMElem::head, BMHeader::htype, BPy_BMLayerItem::htype, BPy_BMLayerItem::index, NULL, BPy_BMLayerItem::type, and UNLIKELY.
Referenced by BPy_BMLayerItem_GetItem(), and BPy_BMLayerItem_SetItem().
int BPy_BMLayerItem_SetItem (BPy_BMElem * py_ele, BPy_BMLayerItem * py_layer, PyObject * py_value)
Definition at line 926 of file bmesh_py_types_customdata.c.
References BLI_strncpy(), BPy_BMDeformVert_AssignPyObject(), bpy_bmlayeritem_ptr_get(), BPy_BMLoopColor_AssignPyObject(), BPy_BMLoopUV_AssignPyObject(), CD_BWEIGHT, CD_CREASE, CD_MDEFORMVERT, CD_MLOOPCOL, CD_MLOOPUV, CD_MTEXPOLY, CD_PROP_FLT, CD_PROP_INT, CD_PROP_STR, CD_SHAPEKEY, CLAMPIS, copy_v3_v3(), mathutils_array_parse(), NULL, MStringProperty::s, BPy_BMLayerItem::type, and UNLIKELY.
Referenced by bpy_bmelem_ass_subscript().
PyDoc_STRVAR (bpy_bmlayeraccess_type_doc , "Exposes custom-data layer attributes.")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__tex_doc , "Accessor for :class:`BMTexPoly` layer (TODO).\n\ntype: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayercollection_keys_doc , ".. method:: keys()\n""\n"" Return the identifiers of collection members\n"" (matching pythons dict.keys() functionality).\n""\n"" :return: the identifiers for each member of this collection.\n"" :rtype: list of strings\n")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__crease_doc , "Edge crease for subsurf - float in .\n\n:type: :class:`BMLayerCollection`" [0-1])
PyDoc_STRVAR (bpy_bmlayeraccess_collection__string_doc , "Generic string custom-data layer (exposed as bytes, 255 max length).\n\ntype: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__bevel_weight_doc , "Bevel weight float in .\n\n:type: :class:`BMLayerCollection`" [0-1])
PyDoc_STRVAR (bpy_bmlayeraccess_collection__int_doc , "Generic int custom-data layer.\n\ntype: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayeritem_type_doc , "Exposes a single custom data layer, ""their main purpose is for use as item accessors to custom-data when used with vert/edge/face/loop data.")
PyDoc_STRVAR (bpy_bmlayercollection_new_doc , ".. method:: new(name)\n""\n"" Create a new layer\n""\n"" :arg name: Optional name argument (will be made unique).\n"" :type name: string\n"" :return: The newly created layer.\n"" :rtype: :class:`BMLayerItem`\n")
PyDoc_STRVAR (bpy_bmlayercollection_remove_doc , ".. method:: remove(layer)\n""\n"" Remove a layer\n""\n"" :arg layer: The layer to remove.\n"" :type layer: :class:`BMLayerItem`\n")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__float_doc , "Generic float custom-data layer.\n\ntype: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__deform_doc , "Vertex deform weight :class:`BMDeformVert` (TODO).\n\ntype: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayercollection_type_doc , "Gives access to a collection of custom-data layers of the same type and behaves like python dictionaries, ""except for the ability to do list like index access.")
PyDoc_STRVAR (bpy_bmlayercollection_get_doc , ".. method:: get(key, default=None)\n""\n"" Returns the value of the layer matching the key or default\n"" when not found (matches pythons dictionary function of the same name).\n""\n"" :arg key: The key associated with the layer.\n"" :type key: string\n"" :arg default: Optional argument for the value to return if\n"" *key* is not found.\n"" :type default: Undefined\n")
PyDoc_STRVAR (bpy_bmlayercollection_name_doc , "The layers unique name (read-only).\n\n:type: string")
PyDoc_STRVAR (bpy_bmlayercollection_active_doc , "This meshes vert sequence (read-only).\n\n:type: :class:`BMVertSeq`")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__shape_doc , "Vertex shapekey absolute location (as a 3D Vector).\n\n:type: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__color_doc , "Accessor for vertex color layer.\n\ntype: :class:`BMLayerCollection`")
PyDoc_STRVAR (bpy_bmlayercollection_items_doc , ".. method:: values()\n""\n"" Return the values of collection\n"" (matching pythons dict.values() functionality).\n""\n"" :return: the members of this collection.\n"" :rtype: list\n")
PyDoc_STRVAR (bpy_bmlayercollection_values_doc , ".. method:: items()\n""\n"" Return the identifiers of collection members\n"" (matching pythons dict.items() functionality).\n""\n"" :return: (key, value) pairs for each member of this collection.\n"" :rtype: list of tuples\n")
PyDoc_STRVAR (bpy_bmlayeraccess_collection__uv_doc , "Accessor for :class:`BMLoopUV` UV (as a 2D Vector).\n\ntype: :class:`BMLayerCollection`")
Variable Documentation
struct PyMethodDef bpy_bmelemseq_methods[] [static]
Initial value:
 {
    {"new",     (PyCFunction)bpy_bmlayercollection_new,      METH_VARARGS, bpy_bmlayercollection_new_doc},
    {"remove",  (PyCFunction)bpy_bmlayercollection_remove,   METH_O,       bpy_bmlayercollection_remove_doc},
    {"keys",    (PyCFunction)bpy_bmlayercollection_keys,     METH_NOARGS,  bpy_bmlayercollection_keys_doc},
    {"values",  (PyCFunction)bpy_bmlayercollection_values,   METH_NOARGS,  bpy_bmlayercollection_values_doc},
    {"items",   (PyCFunction)bpy_bmlayercollection_items,    METH_NOARGS,  bpy_bmlayercollection_items_doc},
    {"get",     (PyCFunction)bpy_bmlayercollection_get,      METH_VARARGS, bpy_bmlayercollection_get_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 454 of file bmesh_py_types_customdata.c.
Referenced by BPy_BM_init_types_customdata().
PyGetSetDef bpy_bmlayeraccess_edge_getseters[] [static]
Initial value:
 {
    {(char *)"float",  (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__float_doc, (void *)CD_PROP_FLT},
    {(char *)"int",    (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__int_doc, (void *)CD_PROP_INT},
    {(char *)"string", (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__string_doc, (void *)CD_PROP_STR},
    {(char *)"bevel_weight", (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__bevel_weight_doc, (void *)CD_BWEIGHT},
    {(char *)"crease",       (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__crease_doc, (void *)CD_CREASE},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 179 of file bmesh_py_types_customdata.c.
Referenced by BPy_BM_init_types_customdata().
PyGetSetDef bpy_bmlayeraccess_face_getseters[] [static]
Initial value:
 {
    {(char *)"float",  (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__float_doc, (void *)CD_PROP_FLT},
    {(char *)"int",    (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__int_doc, (void *)CD_PROP_INT},
    {(char *)"string", (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__string_doc, (void *)CD_PROP_STR},
    {(char *)"tex",   (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__tex_doc, (void *)CD_MTEXPOLY},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 190 of file bmesh_py_types_customdata.c.
Referenced by BPy_BM_init_types_customdata().
PyGetSetDef bpy_bmlayeraccess_loop_getseters[] [static]
Initial value:
 {
    {(char *)"float",  (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__float_doc, (void *)CD_PROP_FLT},
    {(char *)"int",    (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__int_doc, (void *)CD_PROP_INT},
    {(char *)"string", (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__string_doc, (void *)CD_PROP_STR},
    {(char *)"uv",    (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__uv_doc, (void *)CD_MLOOPUV},
    {(char *)"color", (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__color_doc, (void *)CD_MLOOPCOL},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 200 of file bmesh_py_types_customdata.c.
Referenced by BPy_BM_init_types_customdata().
PyGetSetDef bpy_bmlayeraccess_vert_getseters[] [static]
Initial value:
 {
    {(char *)"deform", (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__deform_doc, (void *)CD_MDEFORMVERT},
    {(char *)"float",  (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__float_doc, (void *)CD_PROP_FLT},
    {(char *)"int",    (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__int_doc, (void *)CD_PROP_INT},
    {(char *)"string", (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__string_doc, (void *)CD_PROP_STR},
    {(char *)"shape",        (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__shape_doc, (void *)CD_SHAPEKEY},
    {(char *)"bevel_weight", (getter)bpy_bmlayeraccess_collection_get, (setter)NULL, (char *)bpy_bmlayeraccess_collection__bevel_weight_doc, (void *)CD_BWEIGHT},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 166 of file bmesh_py_types_customdata.c.
Referenced by BPy_BM_init_types_customdata().
PyTypeObject BPy_BMLayerAccessEdge_Type = {{{0}}}
Definition at line 674 of file bmesh_py_types_customdata.c.
Referenced by BPy_BMLayerAccess_CreatePyObject(), and BPyInit_bmesh_types().
PyTypeObject BPy_BMLayerAccessFace_Type = {{{0}}}
Definition at line 675 of file bmesh_py_types_customdata.c.
Referenced by BPy_BMLayerAccess_CreatePyObject(), and BPyInit_bmesh_types().
PyTypeObject BPy_BMLayerAccessLoop_Type = {{{0}}}
Definition at line 676 of file bmesh_py_types_customdata.c.
Referenced by BPy_BMLayerAccess_CreatePyObject(), and BPyInit_bmesh_types().
PyTypeObject BPy_BMLayerAccessVert_Type = {{{0}}}
Definition at line 673 of file bmesh_py_types_customdata.c.
Referenced by BPy_BMLayerAccess_CreatePyObject(), and BPyInit_bmesh_types().
PyMappingMethods bpy_bmlayercollection_as_mapping [static]
Initial value:
 {
    (lenfunc)bpy_bmlayercollection_length,
    (binaryfunc)bpy_bmlayercollection_subscript,
    (objobjargproc)NULL,
}
Definition at line 631 of file bmesh_py_types_customdata.c.
Referenced by BPy_BM_init_types_customdata().
PySequenceMethods bpy_bmlayercollection_as_sequence [static]
Initial value:
 {
    (lenfunc)bpy_bmlayercollection_length,
    NULL,
    NULL,
    (ssizeargfunc)bpy_bmlayercollection_subscript_int,
    NULL,
    (ssizeobjargproc)NULL,
    NULL,
    (objobjproc)bpy_bmlayercollection_contains,
    (binaryfunc) NULL,
    (ssizeargfunc) NULL,
}
Definition at line 618 of file bmesh_py_types_customdata.c.
Referenced by BPy_BM_init_types_customdata().
PyGetSetDef bpy_bmlayercollection_getseters[] [static]
Initial value:
 {
    {(char *)"active", (getter)bpy_bmlayercollection_active_get, (setter)NULL, (char *)bpy_bmlayercollection_active_doc, NULL},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 212 of file bmesh_py_types_customdata.c.
Referenced by BPy_BM_init_types_customdata().
PyTypeObject BPy_BMLayerCollection_Type = {{{0}}}
Definition at line 677 of file bmesh_py_types_customdata.c.
Referenced by BPyInit_bmesh_types().
PyGetSetDef bpy_bmlayeritem_getseters[] [static]
Initial value:
 {
    {(char *)"name", (getter)bpy_bmlayeritem_name_get, (setter)NULL, (char *)bpy_bmlayercollection_name_doc, NULL},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 219 of file bmesh_py_types_customdata.c.
Referenced by BPy_BM_init_types_customdata().
PyTypeObject BPy_BMLayerItem_Type = {{{0}}}
Definition at line 678 of file bmesh_py_types_customdata.c.
Referenced by BPyInit_bmesh_types().