Blender: drawanimviz.c File Reference
drawanimviz.c File Reference
3D view
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "BLO_sys_types.h"
#include "DNA_anim_types.h"
#include "DNA_armature_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_view3d_types.h"
#include "DNA_object_types.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_dlrbTree.h"
#include "BKE_animsys.h"
#include "BKE_action.h"
#include "BIF_gl.h"
#include "ED_armature.h"
#include "ED_keyframes_draw.h"
#include "BLF_api.h"
#include "UI_resources.h"
#include "view3d_intern.h"
Defines
#define SET_INTENSITY(A, B, C, min, max) (((1.0f - ((C - B) / (C - A))) * (max - min)) + min)
Functions
void draw_motion_paths_init (View3D *v3d, ARegion *ar)
void draw_motion_path_instance (Scene *scene, Object *ob, bPoseChannel *pchan, bAnimVizSettings *avs, bMotionPath *mpath)
void draw_motion_paths_cleanup (View3D *v3d)
Detailed Description
Definition in file drawanimviz.c.
Define Documentation
#define SET_INTENSITY (A, B, C, min, max) (((1.0f - ((C - B) / (C - A))) * (max - min)) + min)
Referenced by draw_motion_path_instance().
Function Documentation
void draw_motion_path_instance (Scene * scene, Object * ob, bPoseChannel * pchan, bAnimVizSettings * avs, bMotionPath * mpath)
Definition at line 85 of file drawanimviz.c.
References AnimData::action, action_groups_find_named(), action_to_keylist(), agroup_to_keylist(), BKE_animdata_from_id(), BLI_dlrbTree_free(), BLI_dlrbTree_init(), BLI_dlrbTree_linkedlist_sync(), BLI_dlrbTree_search_exact(), bPoseChannel::bone, BONE_SELECTED, CFRA, co, bMotionPathVert::co, compare_ak_cfraPtr(), bMotionPath::end_frame, equals_v3v3(), Object::flag, Bone::flag, i, Object::id, Object::imat, invert_m4_m4(), len(), bMotionPath::length, MOTIONPATH_TYPE_ACFRA, MOTIONPATH_VIEW_FNUMS, MOTIONPATH_VIEW_KFACT, MOTIONPATH_VIEW_KFNOS, MOTIONPATH_VIEW_KFRAS, mul_v3_m4v3(), bPoseChannel::name, NULL, Object::obmat, bAnimVizSettings::path_ac, bAnimVizSettings::path_bc, bAnimVizSettings::path_step, bAnimVizSettings::path_type, bAnimVizSettings::path_viewflag, bMotionPath::points, SELECT, SET_INTENSITY, bMotionPath::start_frame, TH_BACK, TH_BONE_POSE, TH_CFRAME, TH_TEXT_HI, TH_VERTEX_SELECT, TH_WIRE, UI_GetThemeColor3ubv(), UI_ThemeColor(), UI_ThemeColorBlend(), UI_ThemeColorBlendShade(), V3D_CACHE_TEXT_ASCII, V3D_CACHE_TEXT_WORLDSPACE, and view3d_cached_text_draw_add().
Referenced by draw_object(), and draw_pose_paths().
void draw_motion_paths_cleanup (View3D * v3d)
Definition at line 312 of file drawanimviz.c.
References View3D::zbuf.
Referenced by draw_object(), and draw_pose_paths().
void draw_motion_paths_init (View3D * v3d, ARegion * ar)
Definition at line 71 of file drawanimviz.c.
References glLoadMatrixf, ARegion::regiondata, RegionView3D::viewmat, and View3D::zbuf.
Referenced by draw_object(), and draw_pose_paths().