Blender: cycles_xml.h File Reference
cycles_xml.h File Reference
Functions
void xml_read_file (Scene *scene, const char *filepath)
Function Documentation
void xml_read_file (Scene * scene, const char * filepath)
Definition at line 933 of file cycles_xml.cpp.
References XMLReadState::base, SceneParams::BVH_STATIC, SceneParams::bvh_type, Scene::default_surface, XMLReadState::dicing_rate, Scene::params, path_dirname(), path_filename(), XMLReadState::scene, XMLReadState::shader, XMLReadState::smooth, state, XMLReadState::tfm, transform_identity(), and xml_read_include().
Referenced by scene_init().