Blender: BKE_writeframeserver.h File Reference
BKE_writeframeserver.h File Reference
blenkernel
Functions
int start_frameserver (struct Scene *scene, struct RenderData *rd, int rectx, int recty, struct ReportList *reports)
void end_frameserver (void)
int append_frameserver (struct RenderData *rd, int start_frame, int frame, int *pixels, int rectx, int recty, struct ReportList *reports)
int frameserver_loop (struct RenderData *rd, struct ReportList *reports)
Detailed Description
Definition in file BKE_writeframeserver.h.
Function Documentation
int append_frameserver (struct RenderData * rd, int start_frame, int frame, int * pixels, int rectx, int recty, struct ReportList * reports)
Referenced by BKE_get_movie_handle().
void end_frameserver (void)
Referenced by BKE_get_movie_handle().
int frameserver_loop (struct RenderData * rd, struct ReportList * reports)
Referenced by BKE_get_movie_handle().
int start_frameserver (struct Scene * scene, struct RenderData * rd, int rectx, int recty, struct ReportList * reports)
Referenced by BKE_get_movie_handle().