Blender: SubdFace Class Reference
SubdFace Class Reference
#include <subd_face.h>
Classes
class EdgeIterator
Public Member Functions
SubdFace (int id_)
bool contains (SubdEdge *e)
int num_edges ()
bool is_boundary ()
EdgeIterator edges ()
EdgeIterator edges (SubdEdge *edge)
Public Attributes
int id
SubdEdge * edge
Detailed Description
Definition at line 39 of file subd_face.h.
Constructor & Destructor Documentation
SubdFace::SubdFace (int id_) [inline]
Definition at line 45 of file subd_face.h.
References edge, and NULL.
Member Function Documentation
bool SubdFace::contains (SubdEdge * e) [inline]
Definition at line 51 of file subd_face.h.
References edges(), and SubdFace::EdgeIterator::isDone().
EdgeIterator SubdFace::edges (SubdEdge * edge) [inline]
Definition at line 103 of file subd_face.h.
EdgeIterator SubdFace::edges () [inline]
Definition at line 102 of file subd_face.h.
References edge.
Referenced by SubdAccBuilder::computeInteriorStencil(), contains(), SubdFaceRing::is_boundary(), is_boundary(), SubdFaceRing::is_regular(), and num_edges().
bool SubdFace::is_boundary () [inline]
Definition at line 70 of file subd_face.h.
References edge, edges(), SubdEdge::face, SubdFace::EdgeIterator::isDone(), NULL, and SubdEdge::pair.
int SubdFace::num_edges () [inline]
Definition at line 60 of file subd_face.h.
References edges(), and SubdFace::EdgeIterator::isDone().
Referenced by SubdFaceRing::is_quad(), SubdFaceRing::is_triangle(), SubdAccBuilder::run(), SubdLinearBuilder::run(), and SubdFaceRing::SubdFaceRing().
Member Data Documentation
SubdEdge* SubdFace::edge
Definition at line 43 of file subd_face.h.
Referenced by SubdMesh::add_face(), edges(), is_boundary(), SubdLinearBuilder::run(), SubdAccBuilder::run(), and SubdFace().
int SubdFace::id
Definition at line 42 of file subd_face.h.
The documentation for this class was generated from the following file:
subd_face.h