Blender: sequencer_select.c File Reference
sequencer_select.c File Reference
sequencer
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "DNA_scene_types.h"
#include "BKE_context.h"
#include "BKE_report.h"
#include "BKE_sequencer.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_define.h"
#include "ED_types.h"
#include "ED_screen.h"
#include "UI_view2d.h"
#include "sequencer_intern.h"
Defines
#define SEQ_IS_SOUND(_seq) ((_seq->type & SEQ_SOUND) && !(_seq->type & SEQ_EFFECT))
#define SEQ_IS_EFFECT(_seq) (_seq->type & SEQ_EFFECT)
#define SEQ_USE_DATA(_seq) (ELEM(_seq->type, SEQ_SCENE, SEQ_MOVIECLIP) || SEQ_HAS_PATH(_seq))
Functions
static void * find_nearest_marker (int UNUSED(d1), int UNUSED(d2))
static void select_surrounding_handles (Scene *scene, Sequence *test)
static void select_active_side (ListBase *seqbase, int sel_side, int channel, int frame)
static void select_linked_time (ListBase *seqbase, Sequence *seq_link)
static void UNUSED_FUNCTION() select_single_seq (Scene *scene, Sequence *seq, int deselect_all)
static int sequencer_de_select_all_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_select_all (struct wmOperatorType *ot)
static int sequencer_select_inverse_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_select_inverse (struct wmOperatorType *ot)
static int sequencer_select_invoke (bContext *C, wmOperator *op, wmEvent *event)
void SEQUENCER_OT_select (wmOperatorType *ot)
static int select_more_less_seq__internal (Scene *scene, int sel, int linked)
static int sequencer_select_more_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_select_more (wmOperatorType *ot)
static int sequencer_select_less_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_select_less (wmOperatorType *ot)
static int sequencer_select_linked_pick_invoke (bContext *C, wmOperator *op, wmEvent *event)
void SEQUENCER_OT_select_linked_pick (wmOperatorType *ot)
static int sequencer_select_linked_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_select_linked (wmOperatorType *ot)
static int sequencer_select_handles_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_select_handles (wmOperatorType *ot)
static int sequencer_select_active_side_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_select_active_side (wmOperatorType *ot)
static int sequencer_borderselect_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_select_border (wmOperatorType *ot)
static short select_grouped_type (Editing *ed, Sequence *actseq)
static short select_grouped_type_basic (Editing *ed, Sequence *actseq)
static short select_grouped_type_effect (Editing *ed, Sequence *actseq)
static short select_grouped_data (Editing *ed, Sequence *actseq)
static short select_grouped_effect (Editing *ed, Sequence *actseq)
static short select_grouped_time_overlap (Editing *ed, Sequence *actseq)
static short select_grouped_effect_link (Editing *ed, Sequence *actseq)
static int sequencer_select_grouped_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_select_grouped (wmOperatorType *ot)
Variables
static EnumPropertyItem sequencer_prop_select_grouped_types []
Detailed Description
Definition in file sequencer_select.c.
Define Documentation
#define SEQ_IS_EFFECT (_seq) (_seq->type & SEQ_EFFECT)
Definition at line 934 of file sequencer_select.c.
Referenced by select_grouped_effect_link(), and select_grouped_type_effect().
#define SEQ_IS_SOUND (_seq) ((_seq->type & SEQ_SOUND) && !(_seq->type & SEQ_EFFECT))
Definition at line 932 of file sequencer_select.c.
Referenced by select_grouped_effect_link(), and select_grouped_type_basic().
#define SEQ_USE_DATA (_seq) (ELEM(_seq->type, SEQ_SCENE, SEQ_MOVIECLIP) || SEQ_HAS_PATH(_seq))
Definition at line 936 of file sequencer_select.c.
Referenced by select_grouped_data().
Function Documentation
static void* find_nearest_marker (int UNUSEDd1, int UNUSEDd2) [static]
Definition at line 66 of file sequencer_select.c.
References NULL.
Referenced by sequencer_select_invoke().
static void select_active_side (ListBase * seqbase, int sel_side, int channel, int frame) [static]
Definition at line 91 of file sequencer_select.c.
References ListBase::first, Sequence::flag, Sequence::machine, Sequence::next, SELECT, SEQ_LEFTSEL, SEQ_RIGHTSEL, SEQ_SIDE_BOTH, SEQ_SIDE_LEFT, SEQ_SIDE_RIGHT, and Sequence::startdisp.
Referenced by sequencer_select_active_side_exec(), and sequencer_select_invoke().
static short select_grouped_data (Editing * ed, Sequence * actseq) [static]
Definition at line 988 of file sequencer_select.c.
References Sequence::clip, Strip::dir, FALSE, Sequence::flag, NULL, Sequence::scene, SELECT, SEQ_END, SEQ_HAS_PATH, SEQ_MOVIECLIP, SEQ_SCENE, SEQ_USE_DATA, SEQP_BEGIN, Sequence::strip, TRUE, and Sequence::type.
Referenced by sequencer_select_grouped_exec().
static short select_grouped_effect (Editing * ed, Sequence * actseq) [static]
Definition at line 1030 of file sequencer_select.c.
References ELEM3, FALSE, Sequence::flag, i, SELECT, Sequence::seq1, Sequence::seq2, Sequence::seq3, SEQ_EFFECT_MAX, SEQ_END, SEQP_BEGIN, TRUE, and Sequence::type.
Referenced by sequencer_select_grouped_exec().
static short select_grouped_effect_link (Editing * ed, Sequence * actseq) [static]
Definition at line 1076 of file sequencer_select.c.
References Sequence::enddisp, FALSE, Sequence::flag, Sequence::machine, NULL, SELECT, SeqIterator::seq, Sequence::seq1, Sequence::seq2, Sequence::seq3, seq_begin(), seq_end(), SEQ_END, SEQ_IS_EFFECT, SEQ_IS_SOUND, SEQ_META, seq_next(), SEQP_BEGIN, SET_INT_IN_POINTER, Sequence::startdisp, Sequence::tmp, TRUE, Sequence::type, and SeqIterator::valid.
Referenced by sequencer_select_grouped_exec().
static short select_grouped_time_overlap (Editing * ed, Sequence * actseq) [static]
Definition at line 1060 of file sequencer_select.c.
References Sequence::enddisp, FALSE, Sequence::flag, SELECT, SEQ_END, SEQP_BEGIN, Sequence::startdisp, and TRUE.
Referenced by sequencer_select_grouped_exec().
static short select_grouped_type (Editing * ed, Sequence * actseq) [static]
Definition at line 938 of file sequencer_select.c.
References FALSE, Sequence::flag, SELECT, SEQ_END, SEQP_BEGIN, TRUE, and Sequence::type.
Referenced by sequencer_select_grouped_exec().
static short select_grouped_type_basic (Editing * ed, Sequence * actseq) [static]
Definition at line 954 of file sequencer_select.c.
References FALSE, Sequence::flag, SELECT, SEQ_END, SEQ_IS_SOUND, SEQP_BEGIN, and TRUE.
Referenced by sequencer_select_grouped_exec().
static short select_grouped_type_effect (Editing * ed, Sequence * actseq) [static]
Definition at line 971 of file sequencer_select.c.
References FALSE, Sequence::flag, SELECT, SEQ_END, SEQ_IS_EFFECT, SEQP_BEGIN, and TRUE.
Referenced by sequencer_select_grouped_exec().
static void select_linked_time (ListBase * seqbase, Sequence * seq_link) [static]
Definition at line 119 of file sequencer_select.c.
References Sequence::enddisp, ListBase::first, Sequence::flag, Sequence::machine, Sequence::next, recurs_sel_seq(), SELECT, SEQ_LEFTSEL, SEQ_RIGHTSEL, and Sequence::startdisp.
Referenced by sequencer_select_invoke().
static int select_more_less_seq__internal (Scene * scene, int sel, int linked) [static]
Definition at line 558 of file sequencer_select.c.
References FALSE, find_neighboring_sequence(), ListBase::first, Sequence::flag, Sequence::next, NULL, recurs_sel_seq(), SELECT, seq_give_editing(), SEQ_SIDE_LEFT, SEQ_SIDE_RIGHT, Editing::seqbasep, and Sequence::tmp.
Referenced by sequencer_select_less_exec(), sequencer_select_linked_exec(), sequencer_select_linked_pick_invoke(), and sequencer_select_more_exec().
static void UNUSED_FUNCTION() select_single_seq (Scene * scene, Sequence * seq, int deselect_all) [static]
Definition at line 165 of file sequencer_select.c.
References Editing::act_imagedir, Editing::act_sounddir, BLI_strncpy(), deselect_all_seq(), FALSE, FILE_MAXDIR, recurs_sel_seq(), SELECT, seq_active_set(), seq_give_editing(), SEQ_IMAGE, SEQ_MOVIE, and SEQ_SOUND.
static void select_surrounding_handles (Scene * scene, Sequence * test) [static]
Definition at line 71 of file sequencer_select.c.
References find_neighboring_sequence(), Sequence::flag, recurs_sel_seq(), SELECT, SEQ_LEFTSEL, SEQ_RIGHTSEL, SEQ_SIDE_LEFT, and SEQ_SIDE_RIGHT.
Referenced by sequencer_select_invoke().
static int sequencer_borderselect_exec (bContext * C, wmOperator * op) [static]
Definition at line 846 of file sequencer_select.c.
References BLI_isect_rctf(), CTX_data_scene(), FALSE, ListBase::first, Sequence::flag, GESTURE_MODAL_SELECT, NA_SELECTED, NC_SCENE, ND_SEQUENCER, Sequence::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, ImBuf::rect, recurs_sel_seq(), RNA_boolean_get(), RNA_int_get(), SELECT, SEQ_ALLSEL, seq_give_editing(), seq_rectf(), Editing::seqbasep, UI_view2d_fromcontext(), UI_view2d_region_to_view(), WM_event_add_notifier(), rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, rctf::ymax, rcti::ymax, rctf::ymin, and rcti::ymin.
Referenced by SEQUENCER_OT_select_border().
static int sequencer_de_select_all_exec (bContext * C, wmOperator * op) [static]
Definition at line 218 of file sequencer_select.c.
References CTX_data_scene(), FALSE, ListBase::first, Sequence::flag, NA_SELECTED, NC_SCENE, ND_SEQUENCER, Sequence::next, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, SELECT, SEQ_ALLSEL, seq_give_editing(), SEQ_LEFTSEL, SEQ_RIGHTSEL, Editing::seqbasep, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_select_all().
void SEQUENCER_OT_select (wmOperatorType * ot)
Definition at line 532 of file sequencer_select.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), sequencer_select_invoke(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_active_side (wmOperatorType * ot)
Definition at line 826 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, prop_side_types, RNA_def_enum(), SEQ_SIDE_BOTH, sequencer_edit_poll(), sequencer_select_active_side_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_all (struct wmOperatorType * ot)
Definition at line 262 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_de_select_all_exec(), sequencer_edit_poll(), and WM_operator_properties_select_all().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_border (wmOperatorType * ot)
Definition at line 895 of file sequencer_select.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_borderselect_exec(), TRUE, WM_border_select_cancel(), WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_grouped (wmOperatorType * ot)
Definition at line 1179 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), sequencer_edit_poll(), sequencer_select_grouped_exec(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_handles (wmOperatorType * ot)
Definition at line 789 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, prop_side_types, RNA_def_enum(), SEQ_SIDE_BOTH, sequencer_edit_poll(), sequencer_select_handles_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_inverse (struct wmOperatorType * ot)
Definition at line 302 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_select_inverse_exec().
void SEQUENCER_OT_select_less (wmOperatorType * ot)
Definition at line 654 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_select_less_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_linked (wmOperatorType * ot)
Definition at line 739 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_select_linked_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_linked_pick (wmOperatorType * ot)
Definition at line 704 of file sequencer_select.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), sequencer_select_linked_pick_invoke(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_select_more (wmOperatorType * ot)
Definition at line 623 of file sequencer_select.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_select_more_exec().
Referenced by sequencer_operatortypes().
static int sequencer_select_active_side_exec (bContext * C, wmOperator * op) [static]
Definition at line 808 of file sequencer_select.c.
References CTX_data_scene(), Sequence::flag, Sequence::machine, NA_SELECTED, NC_SCENE, ND_SEQUENCER, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), SELECT, select_active_side(), seq_active_get(), seq_give_editing(), Editing::seqbasep, Sequence::startdisp, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_select_active_side().
static int sequencer_select_grouped_exec (bContext * C, wmOperator * op) [static]
Definition at line 1140 of file sequencer_select.c.
References BKE_report(), CTX_data_scene(), Sequence::flag, NA_SELECTED, NC_SCENE, ND_SEQUENCER, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_enum_get(), RPT_ERROR, SELECT, select_grouped_data(), select_grouped_effect(), select_grouped_effect_link(), select_grouped_time_overlap(), select_grouped_type(), select_grouped_type_basic(), select_grouped_type_effect(), seq_active_get(), SEQ_END, seq_give_editing(), SEQP_BEGIN, TRUE, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_select_grouped().
static int sequencer_select_handles_exec (bContext * C, wmOperator * op) [static]
Definition at line 758 of file sequencer_select.c.
References CTX_data_scene(), ListBase::first, Sequence::flag, NA_SELECTED, NC_SCENE, ND_SEQUENCER, Sequence::next, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), SELECT, seq_give_editing(), SEQ_LEFTSEL, SEQ_RIGHTSEL, SEQ_SIDE_BOTH, SEQ_SIDE_LEFT, SEQ_SIDE_RIGHT, Editing::seqbasep, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_select_handles().
static int sequencer_select_inverse_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 281 of file sequencer_select.c.
References CTX_data_scene(), FALSE, ListBase::first, Sequence::flag, NA_SELECTED, NC_SCENE, ND_SEQUENCER, Sequence::next, OPERATOR_FINISHED, SELECT, SEQ_ALLSEL, seq_give_editing(), SEQ_LEFTSEL, SEQ_RIGHTSEL, Editing::seqbasep, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_select_inverse().
static int sequencer_select_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 317 of file sequencer_select.c.
References abs(), Editing::act_imagedir, Editing::act_seq, Editing::act_sounddir, BLI_strncpy(), CFRA, CTX_data_scene(), CTX_wm_space_seq(), deselect_all_seq(), Strip::dir, ELEM, Sequence::enddisp, FALSE, FILE_MAXDIR, find_nearest_marker(), find_nearest_seq(), find_neighboring_sequence(), ListBase::first, SpaceSeq::flag, Sequence::flag, TimeMarker::flag, TimeMarker::frame, Sequence::machine, Scene::markers, wmEvent::mval, NA_SELECTED, NC_SCENE, ND_SEQUENCER, TimeMarker::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, recurs_sel_seq(), RNA_boolean_get(), SCE_MARKERS, SELECT, select_active_side(), select_linked_time(), select_surrounding_handles(), seq_active_set(), SEQ_ALLSEL, SEQ_END, seq_give_editing(), SEQ_IMAGE, SEQ_LEFTSEL, SEQ_MARKER_TRANS, SEQ_MOVIE, SEQ_RIGHTSEL, SEQ_SIDE_LEFT, SEQ_SIDE_NONE, SEQ_SIDE_RIGHT, SEQ_SOUND, Editing::seqbasep, SEQP_BEGIN, Sequence::startdisp, Sequence::strip, Sequence::type, UI_view2d_fromcontext(), UI_view2d_region_to_view(), WM_event_add_notifier(), and ImBuf::x.
Referenced by SEQUENCER_OT_select().
static int sequencer_select_less_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 642 of file sequencer_select.c.
References CTX_data_scene(), NA_SELECTED, NC_SCENE, ND_SEQUENCER, OPERATOR_CANCELLED, OPERATOR_FINISHED, select_more_less_seq__internal(), and WM_event_add_notifier().
Referenced by SEQUENCER_OT_select_less().
static int sequencer_select_linked_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 724 of file sequencer_select.c.
References CTX_data_scene(), NA_SELECTED, NC_SCENE, ND_SEQUENCER, OPERATOR_FINISHED, select_more_less_seq__internal(), and WM_event_add_notifier().
Referenced by SEQUENCER_OT_select_linked().
static int sequencer_select_linked_pick_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 673 of file sequencer_select.c.
References CTX_data_scene(), deselect_all_seq(), find_nearest_seq(), Sequence::flag, wmEvent::mval, NA_SELECTED, NC_SCENE, ND_SEQUENCER, OPERATOR_FINISHED, wmOperator::ptr, recurs_sel_seq(), RNA_boolean_get(), SELECT, select_more_less_seq__internal(), UI_view2d_fromcontext(), and WM_event_add_notifier().
Referenced by SEQUENCER_OT_select_linked_pick().
static int sequencer_select_more_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 611 of file sequencer_select.c.
References CTX_data_scene(), NA_SELECTED, NC_SCENE, ND_SEQUENCER, OPERATOR_CANCELLED, OPERATOR_FINISHED, select_more_less_seq__internal(), and WM_event_add_notifier().
Referenced by SEQUENCER_OT_select_more().
Variable Documentation
EnumPropertyItem sequencer_prop_select_grouped_types[] [static]
Initial value:
 {
    {1, "TYPE", 0, "Type", "Shared strip type"},
    {2, "TYPE_BASIC", 0, "Global Type", "All strips of same basic type (Graphical or Sound)"},
    {3, "TYPE_EFFECT", 0, "Effect Type",
     "Shared strip effect type (if active strip is not an effect one, select all non-effect strips)"},
    {4, "DATA", 0, "Data", "Shared data (scene, image, sound, etc.)"},
    {5, "EFFECT", 0, "Effect", "Shared effects"},
    {6, "EFFECT_LINK", 0, "Effect/Linked",
     "Other strips affected by the active one (sharing some time, and below or effect-assigned)"},
    {7, "OVERLAP", 0, "Overlap", "Overlapping time"},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 919 of file sequencer_select.c.