Blender: btTriangleBuffer Class Reference
btTriangleBuffer Class Reference
#include <btTriangleBuffer.h>
Public Member Functions
virtual void processTriangle (btVector3 *triangle, int partId, int triangleIndex)
int getNumTriangles () const
const btTriangle & getTriangle (int index) const
void clearBuffer ()
Detailed Description
The btTriangleBuffer callback can be useful to collect and store overlapping triangles between AABB and concave objects that support 'processAllTriangles' Example usage of this class: btTriangleBuffer triBuf; concaveShape->processAllTriangles(&triBuf,aabbMin, aabbMax); for (int i=0;i<triBuf.getNumTriangles();i++) { const btTriangle& tri = triBuf.getTriangle(i); do something useful here with the triangle }
Definition at line 40 of file btTriangleBuffer.h.
Member Function Documentation
void btTriangleBuffer::clearBuffer () [inline]
Definition at line 60 of file btTriangleBuffer.h.
References btAlignedObjectArray< T >::clear().
int btTriangleBuffer::getNumTriangles () const [inline]
Definition at line 50 of file btTriangleBuffer.h.
References btAlignedObjectArray< T >::size().
const btTriangle& btTriangleBuffer::getTriangle (int index) const [inline]
Definition at line 55 of file btTriangleBuffer.h.
void btTriangleBuffer::processTriangle (btVector3 * triangle, int partId, int triangleIndex) [virtual]
Implements btTriangleCallback.
Definition at line 24 of file btTriangleBuffer.cpp.
References btTriangle::m_partId, btTriangle::m_triangleIndex, btTriangle::m_vertex0, btTriangle::m_vertex1, btTriangle::m_vertex2, and btAlignedObjectArray< T >::push_back().
The documentation for this class was generated from the following files:
btTriangleBuffer.h
btTriangleBuffer.cpp