Blender: Exception.cpp File Reference
Exception.cpp File Reference
BGE Video Texture
#include <sstream>
#include <fstream>
#include <PyObjectPlus.h>
#include "Exception.h"
Functions
void registerAllExceptions (void)
Variables
ExceptionID ErrGeneral
ExceptionID ErrNotFound
ExpDesc errGenerDesc (ErrGeneral,"General Error")
ExpDesc errNFoundDesc (ErrNotFound,"Error description not found")
Detailed Description
Definition in file Exception.cpp.
Function Documentation
void registerAllExceptions (void)
Definition at line 202 of file Exception.cpp.
References CameraInvalidDesc, errGenerDesc, errNFoundDesc, ImageHasExportsDesc, ImageSizesNotMatchDesc, InvalidColorChannelDesc, MaterialNotAvailDesc, MirrorHorizontalDesc, MirrorInvalidDesc, MirrorNormalInvalidDesc, MirrorSizeInvalidDesc, MirrorTooSmallDesc, ObserverInvalidDesc, ExpDesc::registerDesc(), SceneInvalidDesc, SourceVideoCreationDesc, and SourceVideoEmptyDesc.
Referenced by initVideoTexture().
Variable Documentation
ExceptionID ErrGeneral
Definition at line 36 of file Exception.cpp.
ExpDesc errGenerDesc(ErrGeneral,"General Error")
Referenced by registerAllExceptions().
ExpDesc errNFoundDesc(ErrNotFound,"Error description not found")
Referenced by registerAllExceptions().
ExceptionID ErrNotFound
Definition at line 36 of file Exception.cpp.
Referenced by Exception::Exception().