Blender: math_geom_inline.c File Reference
math_geom_inline.c File Reference
blenlib
#include "BLI_math.h"
Defines
#define __MATH_GEOM_INLINE_C__
Functions
MINLINE void zero_sh (float r[9])
MINLINE void copy_sh_sh (float r[9], const float a[9])
MINLINE void mul_sh_fl (float r[9], const float f)
MINLINE void add_sh_shsh (float r[9], const float a[9], const float b[9])
MINLINE float dot_shsh (float a[9], float b[9])
MINLINE float diffuse_shv3 (float sh[9], const float v[3])
MINLINE void vec_fac_to_sh (float r[9], const float v[3], const float f)
MINLINE float eval_shv3 (float sh[9], const float v[3])
MINLINE void madd_sh_shfl (float r[9], const float sh[9], const float f)
Detailed Description
Definition in file math_geom_inline.c.
Define Documentation
#define __MATH_GEOM_INLINE_C__
Definition at line 34 of file math_geom_inline.c.
Function Documentation
MINLINE void add_sh_shsh (float r[9], const float a[9], const float b[9])
Definition at line 56 of file math_geom_inline.c.
References i.
Referenced by madd_sh_shfl().
MINLINE void copy_sh_sh (float r[9], const float a[9])
Definition at line 43 of file math_geom_inline.c.
Referenced by madd_sh_shfl(), and vec_fac_to_sh().
MINLINE float diffuse_shv3 (float sh[9], const float v[3])
Definition at line 75 of file math_geom_inline.c.
References sum().
MINLINE float dot_shsh (float a[9], float b[9])
Definition at line 64 of file math_geom_inline.c.
References i.
Referenced by eval_shv3().
MINLINE float eval_shv3 (float sh[9], const float v[3])
Definition at line 123 of file math_geom_inline.c.
References dot_shsh(), and vec_fac_to_sh().
MINLINE void madd_sh_shfl (float r[9], const float sh[9], const float f)
Definition at line 131 of file math_geom_inline.c.
References add_sh_shsh(), copy_sh_sh(), and mul_sh_fl().
MINLINE void mul_sh_fl (float r[9], const float f)
Definition at line 48 of file math_geom_inline.c.
References i.
Referenced by madd_sh_shfl(), and vec_fac_to_sh().
MINLINE void vec_fac_to_sh (float r[9], const float v[3], const float f)
Definition at line 97 of file math_geom_inline.c.
References copy_sh_sh(), and mul_sh_fl().
Referenced by eval_shv3().
MINLINE void zero_sh (float r[9])
Definition at line 38 of file math_geom_inline.c.