Blender: rna_fluidsim.c File Reference
rna_fluidsim.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_object_fluidsim.h"
#include "WM_api.h"
#include "WM_types.h"
Functions
static void rna_def_fluidsim_slip (StructRNA *srna)
static void rna_def_fluid_mesh_vertices (BlenderRNA *brna)
static void rna_def_fluidsim_domain (BlenderRNA *brna)
static void rna_def_fluidsim_volume (StructRNA *srna)
static void rna_def_fluidsim_active (StructRNA *srna)
static void rna_def_fluidsim_fluid (BlenderRNA *brna)
static void rna_def_fluidsim_obstacle (BlenderRNA *brna)
static void rna_def_fluidsim_inflow (BlenderRNA *brna)
static void rna_def_fluidsim_outflow (BlenderRNA *brna)
static void rna_def_fluidsim_particle (BlenderRNA *brna)
static void rna_def_fluidsim_control (BlenderRNA *brna)
void RNA_def_fluidsim (BlenderRNA *brna)
Detailed Description
Definition in file rna_fluidsim.c.
Function Documentation
static void rna_def_fluid_mesh_vertices (BlenderRNA * brna) [static]
Definition at line 243 of file rna_fluidsim.c.
References NULL, PROP_EDITABLE, PROP_FLOAT, PROP_VELOCITY, RNA_def_property(), RNA_def_property_array(), RNA_def_property_clear_flag(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by rna_def_fluidsim_domain().
void RNA_def_fluidsim (BlenderRNA * brna)
Definition at line 660 of file rna_fluidsim.c.
References NULL, OB_FLUIDSIM_CONTROL, OB_FLUIDSIM_DOMAIN, OB_FLUIDSIM_ENABLE, OB_FLUIDSIM_FLUID, OB_FLUIDSIM_INFLOW, OB_FLUIDSIM_OBSTACLE, OB_FLUIDSIM_OUTFLOW, OB_FLUIDSIM_PARTICLE, PROP_ANIMATABLE, PROP_ENUM, PROP_NONE, rna_def_fluidsim_control(), rna_def_fluidsim_domain(), rna_def_fluidsim_fluid(), rna_def_fluidsim_inflow(), rna_def_fluidsim_obstacle(), rna_def_fluidsim_outflow(), rna_def_fluidsim_particle(), RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
static void rna_def_fluidsim_active (StructRNA * srna) [static]
Definition at line 465 of file rna_fluidsim.c.
References NULL, OB_FLUIDSIM_ACTIVE, PROP_BOOLEAN, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), and RNA_def_property_ui_text().
Referenced by rna_def_fluidsim_control(), rna_def_fluidsim_fluid(), rna_def_fluidsim_inflow(), rna_def_fluidsim_obstacle(), and rna_def_fluidsim_outflow().
static void rna_def_fluidsim_control (BlenderRNA * brna) [static]
Definition at line 601 of file rna_fluidsim.c.
References NULL, OB_FLUIDSIM_REVERSE, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, PROP_TIME, rna_def_fluidsim_active(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fluidsim().
static void rna_def_fluidsim_domain (BlenderRNA * brna) [static]
Definition at line 261 of file rna_fluidsim.c.
References FILE_MAX, NC_OBJECT, NULL, OB_FLUIDSIM_OVERRIDE_TIME, OB_FLUIDSIM_REVERSE, OB_FSDOM_FINAL, OB_FSDOM_GEOM, OB_FSDOM_PREVIEW, OB_FSSG_NOOBS, PROP_ACCELERATION, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_FILEPATH, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_STRING, PROP_TIME, rna_def_fluid_mesh_vertices(), rna_def_fluidsim_slip(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fluidsim().
static void rna_def_fluidsim_fluid (BlenderRNA * brna) [static]
Definition at line 474 of file rna_fluidsim.c.
References NULL, PROP_FLOAT, PROP_VELOCITY, rna_def_fluidsim_active(), rna_def_fluidsim_volume(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fluidsim().
static void rna_def_fluidsim_inflow (BlenderRNA * brna) [static]
Definition at line 518 of file rna_fluidsim.c.
References NULL, OB_FSINFLOW_LOCALCOORD, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, PROP_VELOCITY, rna_def_fluidsim_active(), rna_def_fluidsim_volume(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fluidsim().
static void rna_def_fluidsim_obstacle (BlenderRNA * brna) [static]
Definition at line 494 of file rna_fluidsim.c.
References NULL, PROP_ANIMATABLE, PROP_FLOAT, PROP_NONE, rna_def_fluidsim_active(), rna_def_fluidsim_slip(), rna_def_fluidsim_volume(), RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fluidsim().
static void rna_def_fluidsim_outflow (BlenderRNA * brna) [static]
Definition at line 544 of file rna_fluidsim.c.
References rna_def_fluidsim_active(), rna_def_fluidsim_volume(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fluidsim().
static void rna_def_fluidsim_particle (BlenderRNA * brna) [static]
Definition at line 557 of file rna_fluidsim.c.
References FILE_MAX, NULL, OB_FSPART_DROP, OB_FSPART_FLOAT, OB_FSPART_TRACER, PROP_BOOLEAN, PROP_FILEPATH, PROP_FLOAT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_string_maxlength(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fluidsim().
static void rna_def_fluidsim_slip (StructRNA * srna) [static]
Definition at line 216 of file rna_fluidsim.c.
References NULL, OB_FSBND_FREESLIP, OB_FSBND_NOSLIP, OB_FSBND_PARTSLIP, PROP_ANIMATABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_float_sdna(), RNA_def_property_range(), and RNA_def_property_ui_text().
Referenced by rna_def_fluidsim_domain(), and rna_def_fluidsim_obstacle().
static void rna_def_fluidsim_volume (StructRNA * srna) [static]
Definition at line 441 of file rna_fluidsim.c.
References NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), and RNA_def_property_ui_text().
Referenced by rna_def_fluidsim_fluid(), rna_def_fluidsim_inflow(), rna_def_fluidsim_obstacle(), and rna_def_fluidsim_outflow().