Blender: bpy_rna_callback.h File Reference
bpy_rna_callback.h File Reference
Python RNA and Operators
Functions
PyObject * pyrna_callback_add (BPy_StructRNA *self, PyObject *args)
PyObject * pyrna_callback_remove (BPy_StructRNA *self, PyObject *args)
Detailed Description
Definition in file bpy_rna_callback.h.
Function Documentation
PyObject* pyrna_callback_add (BPy_StructRNA * self, PyObject * args)
Definition at line 74 of file bpy_rna_callback.c.
References cb_region_draw(), ED_region_draw_cb_activate(), NULL, pyrna_enum_value_from_id(), REGION_DRAW_POST_PIXEL, REGION_DRAW_POST_VIEW, REGION_DRAW_PRE_VIEW, RNA_CAPSULE_ID, RNA_Region, and RNA_struct_is_a().
PyObject* pyrna_callback_remove (BPy_StructRNA * self, PyObject * args)
Definition at line 117 of file bpy_rna_callback.c.
References ED_region_draw_cb_customdata(), ED_region_draw_cb_exit(), NULL, RNA_CAPSULE_ID, RNA_CAPSULE_ID_INVALID, RNA_Region, and RNA_struct_is_a().