Blender: ImagesExporter Class Reference
ImagesExporter Class Reference
#include <ImageExporter.h>
Public Member Functions
ImagesExporter (COLLADASW::StreamWriter *sw, const ExportSettings *export_settings)
void exportImages (Scene *sce)
void operator() (Material *ma, Object *ob)
Detailed Description
Definition at line 43 of file ImageExporter.h.
Constructor & Destructor Documentation
ImagesExporter::ImagesExporter (COLLADASW::StreamWriter * sw, const ExportSettings * export_settings)
Definition at line 44 of file ImageExporter.cpp.
Member Function Documentation
void ImagesExporter::exportImages (Scene * sce)
Definition at line 72 of file ImageExporter.cpp.
References MaterialFunctor::forEachMaterialInScene(), and ExportSettings::selected.
Referenced by DocumentExporter::exportCurrentScene().
void ImagesExporter::operator() (Material * ma, Object * ob)
Definition at line 83 of file ImageExporter.cpp.
References abs(), BKE_rebase_path(), BLI_copy(), BLI_make_existing_file(), BLI_path_abs(), BLI_split_dir_part(), BLI_strncpy(), FILE_MAX, ExportSettings::filepath, find(), G, id_name(), Tex::ima, MAX_MTEX, Material::mtex, Image::name, ImBuf::name, MTex::tex, and translate_id().
The documentation for this class was generated from the following files:
ImageExporter.h
ImageExporter.cpp