Blender: ED_transform.h File Reference
ED_transform.h File Reference
Editors
Classes
struct DepthPeel
Defines
#define CTX_NONE 0
#define CTX_TEXTURE 1
#define CTX_EDGE 2
#define CTX_NO_PET 4
#define CTX_TWEAK 8
#define CTX_NO_MIRROR 16
#define CTX_AUTOCONFIRM 32
#define CTX_BMESH 64
#define CTX_NDOF 128
#define CTX_MOVIECLIP 256
#define P_MIRROR (1 << 0)
#define P_PROPORTIONAL (1 << 1)
#define P_AXIS (1 << 2)
#define P_SNAP (1 << 3)
#define P_GEO_SNAP (P_SNAP|(1 << 4))
#define P_ALIGN_SNAP (P_GEO_SNAP|(1 << 5))
#define P_CONSTRAINT (1 << 6)
#define P_OPTIONS (1 << 7)
#define P_CORRECT_UV (1 << 8)
#define SNAP_MIN_DISTANCE 30
Typedefs
typedef struct DepthPeel DepthPeel
typedef enum SnapMode SnapMode
Enumerations
enum {
TFM_INIT = -1, TFM_DUMMY, TFM_TRANSLATION, TFM_ROTATION,
TFM_RESIZE, TFM_TOSPHERE, TFM_SHEAR, TFM_WARP,
TFM_SHRINKFATTEN, TFM_TILT, TFM_TRACKBALL, TFM_PUSHPULL,
TFM_CREASE, TFM_MIRROR, TFM_BONESIZE, TFM_BONE_ENVELOPE,
TFM_CURVE_SHRINKFATTEN, TFM_BONE_ROLL, TFM_TIME_TRANSLATE, TFM_TIME_SLIDE,
TFM_TIME_SCALE, TFM_TIME_EXTEND, TFM_TIME_DUPLICATE, TFM_BAKE_TIME,
TFM_BEVEL, TFM_BWEIGHT, TFM_ALIGN, TFM_EDGE_SLIDE,
TFM_SEQ_SLIDE
}
enum SnapMode { SNAP_ALL = 0, SNAP_NOT_SELECTED = 1, SNAP_NOT_OBEDIT = 2 }
Functions
void transform_keymap_for_space (struct wmKeyConfig *keyconf, struct wmKeyMap *keymap, int spaceid)
void transform_operatortypes (void)
int calculateTransformCenter (struct bContext *C, int centerMode, float *vec)
int BIF_snappingSupported (struct Object *obedit)
void BIF_clearTransformOrientation (struct bContext *C)
void BIF_removeTransformOrientation (struct bContext *C, struct TransformOrientation *ts)
void BIF_removeTransformOrientationIndex (struct bContext *C, int index)
void BIF_createTransformOrientation (struct bContext *C, struct ReportList *reports, char *name, int use, int overwrite)
void BIF_selectTransformOrientation (struct bContext *C, struct TransformOrientation *ts)
void BIF_selectTransformOrientationValue (struct bContext *C, int orientation)
void ED_getTransformOrientationMatrix (const struct bContext *C, float orientation_mat[][3], int activeOnly)
struct EnumPropertyItem * BIF_enumTransformOrientation (struct bContext *C)
const char * BIF_menustringTransformOrientation (const struct bContext *C, const char *title)
int BIF_countTransformOrientation (const struct bContext *C)
void BIF_TransformSetUndo (const char *str)
void BIF_selectOrientation (void)
void Transform_Properties (struct wmOperatorType *ot, int flags)
int BIF_do_manipulator (struct bContext *C, struct wmEvent *event, struct wmOperator *op)
void BIF_draw_manipulator (const struct bContext *C)
int peelObjectsTransForm (struct TransInfo *t, struct ListBase *depth_peels, const float mval[2], SnapMode mode)
int peelObjectsContext (struct bContext *C, struct ListBase *depth_peels, const float mval[2], SnapMode mode)
int snapObjectsTransform (struct TransInfo *t, const float mval[2], int *r_dist, float r_loc[3], float r_no[3], SnapMode mode)
int snapObjectsContext (struct bContext *C, const float mval[2], int *r_dist, float r_loc[3], float r_no[3], SnapMode mode)
Variables
enum { ... } TfmMode
Detailed Description
Definition in file ED_transform.h.
Define Documentation
#define CTX_AUTOCONFIRM 32
Definition at line 94 of file ED_transform.h.
Referenced by special_aftertrans_update(), transform_exec(), and transformApply().
#define CTX_BMESH 64
Definition at line 95 of file ED_transform.h.
Referenced by createTransData().
#define CTX_EDGE 2
Definition at line 90 of file ED_transform.h.
Referenced by createTransData(), and initTransInfo().
#define CTX_MOVIECLIP 256
Definition at line 97 of file ED_transform.h.
Referenced by initTransform(), and transformEvent().
#define CTX_NDOF 128
Definition at line 96 of file ED_transform.h.
#define CTX_NO_MIRROR 16
Definition at line 93 of file ED_transform.h.
Referenced by recalcData_view3d().
#define CTX_NO_PET 4
Definition at line 91 of file ED_transform.h.
Referenced by initTransInfo().
#define CTX_NONE 0
Definition at line 88 of file ED_transform.h.
Referenced by calculateTransformCenter().
#define CTX_TEXTURE 1
Definition at line 89 of file ED_transform.h.
Referenced by createTransData(), initTransform(), and transformEvent().
#define CTX_TWEAK 8
Definition at line 92 of file ED_transform.h.
#define P_ALIGN_SNAP (P_GEO_SNAP|(1 << 5))
Definition at line 141 of file ED_transform.h.
Referenced by TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), and Transform_Properties().
#define P_AXIS (1 << 2)
Definition at line 138 of file ED_transform.h.
Referenced by TRANSFORM_OT_rotate(), TRANSFORM_OT_transform(), and Transform_Properties().
#define P_CONSTRAINT (1 << 6)
Definition at line 142 of file ED_transform.h.
Referenced by TRANSFORM_OT_mirror(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_tilt(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), Transform_Properties(), and VIEW3D_OT_manipulator().
#define P_CORRECT_UV (1 << 8)
Definition at line 144 of file ED_transform.h.
Referenced by TRANSFORM_OT_edge_slide(), and Transform_Properties().
#define P_GEO_SNAP (P_SNAP|(1 << 4))
Definition at line 140 of file ED_transform.h.
Referenced by TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), and Transform_Properties().
#define P_MIRROR (1 << 0)
Definition at line 136 of file ED_transform.h.
Referenced by TRANSFORM_OT_edge_slide(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), TRANSFORM_OT_warp(), and Transform_Properties().
#define P_OPTIONS (1 << 7)
Definition at line 143 of file ED_transform.h.
Referenced by TRANSFORM_OT_resize(), TRANSFORM_OT_translate(), and Transform_Properties().
#define P_PROPORTIONAL (1 << 1)
Definition at line 137 of file ED_transform.h.
Referenced by MESH_OT_rip(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), TRANSFORM_OT_warp(), and Transform_Properties().
#define P_SNAP (1 << 3)
Definition at line 139 of file ED_transform.h.
Referenced by TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_warp(), and Transform_Properties().
#define SNAP_MIN_DISTANCE 30
Definition at line 176 of file ED_transform.h.
Referenced by CalcSnapGeometry(), sk_getStrokeSnapPoint(), and sk_updateOverdraw().
Typedef Documentation
typedef struct DepthPeel DepthPeel
typedef enum SnapMode SnapMode
Enumeration Type Documentation
anonymous enum
Enumerator:
TFM_INIT
TFM_DUMMY
TFM_TRANSLATION
TFM_ROTATION
TFM_RESIZE
TFM_TOSPHERE
TFM_SHEAR
TFM_WARP
TFM_SHRINKFATTEN
TFM_TILT
TFM_TRACKBALL
TFM_PUSHPULL
TFM_CREASE
TFM_MIRROR
TFM_BONESIZE
TFM_BONE_ENVELOPE
TFM_CURVE_SHRINKFATTEN
TFM_BONE_ROLL
TFM_TIME_TRANSLATE
TFM_TIME_SLIDE
TFM_TIME_SCALE
TFM_TIME_EXTEND
TFM_TIME_DUPLICATE
TFM_BAKE_TIME
TFM_BEVEL
TFM_BWEIGHT
TFM_ALIGN
TFM_EDGE_SLIDE
TFM_SEQ_SLIDE
Definition at line 55 of file ED_transform.h.
enum SnapMode
Enumerator:
SNAP_ALL
SNAP_NOT_SELECTED
SNAP_NOT_OBEDIT
Definition at line 169 of file ED_transform.h.
Function Documentation
void BIF_clearTransformOrientation (struct bContext * C)
Definition at line 69 of file transform_orientations.c.
References BLI_freelistN(), CTX_data_scene(), CTX_wm_view3d(), Scene::transform_spaces, View3D::twmode, V3D_MANIP_CUSTOM, and V3D_MANIP_GLOBAL.
int BIF_countTransformOrientation (const struct bContext * C)
Referenced by BIF_menustringTransformOrientation(), initTransInfo(), and uiTemplateHeader3D().
void BIF_createTransformOrientation (struct bContext * C, struct ReportList * reports, char * name, int use, int overwrite)
Definition at line 105 of file transform_orientations.c.
References BIF_selectTransformOrientation(), createBoneSpace(), createMeshSpace(), createObjectSpace(), CTX_data_active_object(), CTX_data_edit_object(), Object::mode, NULL, OB_ARMATURE, OB_MESH, OB_MODE_POSE, and Object::type.
Referenced by create_orientation_exec().
int BIF_do_manipulator (struct bContext * C, struct wmEvent * event, struct wmOperator * op)
Definition at line 1618 of file transform_manipulator.c.
References CTX_wm_area(), CTX_wm_region(), ListBase::first, MAN_ROT_C, MAN_ROT_T, MAN_ROT_X, MAN_ROT_Y, MAN_ROT_Z, MAN_SCALE_C, MAN_SCALE_X, MAN_SCALE_Y, MAN_SCALE_Z, MAN_TRANS_C, MAN_TRANS_X, MAN_TRANS_Y, MAN_TRANS_Z, manipulator_selectbuf(), wmEvent::mval, wmOperator::ptr, RNA_boolean_set_array(), RNA_enum_set(), ScrArea::spacedata, View3D::twflag, View3D::twmode, V3D_DRAW_MANIPULATOR, V3D_USE_MANIPULATOR, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by manipulator_invoke().
void BIF_draw_manipulator (const struct bContext * C)
Referenced by view3d_main_area_draw_objects().
struct EnumPropertyItem* BIF_enumTransformOrientation (struct bContext * C) [read]
Definition at line 365 of file transform_orientations.c.
References CTX_data_scene(), ListBase::first, i, EnumPropertyItem::identifier, TransformOrientation::name, EnumPropertyItem::name, TransformOrientation::next, NULL, RNA_enum_item_add(), RNA_enum_item_add_separator(), RNA_enum_item_end(), Scene::transform_spaces, V3D_MANIP_CUSTOM, V3D_MANIP_GLOBAL, V3D_MANIP_LOCAL, V3D_MANIP_NORMAL, V3D_MANIP_VIEW, and EnumPropertyItem::value.
const char* BIF_menustringTransformOrientation (const struct bContext * C, const char * title)
Referenced by BIF_selectOrientation(), and uiTemplateHeader3D().
void BIF_removeTransformOrientation (struct bContext * C, struct TransformOrientation * ts)
Definition at line 291 of file transform_orientations.c.
References BLI_freelinkN(), CTX_data_scene(), CTX_wm_view3d(), ListBase::first, i, TransformOrientation::next, Scene::transform_spaces, View3D::twmode, V3D_MANIP_CUSTOM, and V3D_MANIP_GLOBAL.
void BIF_removeTransformOrientationIndex (struct bContext * C, int index)
Definition at line 319 of file transform_orientations.c.
References BLI_findlink(), BLI_freelinkN(), CTX_data_scene(), CTX_wm_view3d(), Scene::transform_spaces, View3D::twmode, V3D_MANIP_CUSTOM, and V3D_MANIP_GLOBAL.
Referenced by delete_orientation_exec().
void BIF_selectOrientation (void)
Definition at line 388 of file transform.c.
References BIF_menustringTransformOrientation(), G, MEM_freeN(), and pupmenu().
Referenced by transformEvent().
void BIF_selectTransformOrientation (struct bContext * C, struct TransformOrientation * ts)
Definition at line 343 of file transform_orientations.c.
References CTX_data_scene(), CTX_wm_view3d(), ListBase::first, i, TransformOrientation::next, Scene::transform_spaces, View3D::twmode, and V3D_MANIP_CUSTOM.
Referenced by BIF_createTransformOrientation().
void BIF_selectTransformOrientationValue (struct bContext * C, int orientation)
Definition at line 358 of file transform_orientations.c.
References CTX_wm_view3d(), and View3D::twmode.
Referenced by select_orientation_exec().
int BIF_snappingSupported (struct Object * obedit)
Referenced by handleSnapping().
void BIF_TransformSetUndo (const char * str)
int calculateTransformCenter (struct bContext * C, int centerMode, float * vec)
Definition at line 1111 of file transform.c.
References TransInfo::around, calculateCenter(), TransCon::center, TransInfo::con, copy_v3_v3(), createTransData(), CTX_NONE, initTransInfo(), MEM_callocN(), MEM_freeN(), TransInfo::mode, NULL, TransInfo::options, postTrans(), special_aftertrans_update(), TransInfo::state, TFM_DUMMY, TransInfo::total, and TRANS_RUNNING.
Referenced by viewops_data_create().
void ED_getTransformOrientationMatrix (const struct bContext * C, float orientation_mat[][3], int activeOnly)
Referenced by axis_set_view(), calc_manipulator_stats(), and initTransformOrientation().
int peelObjectsContext (struct bContext * C, struct ListBase * depth_peels, const float mval[2], SnapMode mode)
Definition at line 1948 of file transform_snap.c.
References CTX_data_edit_object(), CTX_data_scene(), CTX_wm_area(), CTX_wm_region(), ListBase::first, peelObjects(), and ScrArea::spacedata.
Referenced by sk_getStrokeSnapPoint().
int peelObjectsTransForm (struct TransInfo * t, struct ListBase * depth_peels, const float mval[2], SnapMode mode)
Definition at line 1943 of file transform_snap.c.
References TransInfo::ar, TransInfo::obedit, peelObjects(), TransInfo::scene, and TransInfo::view.
Referenced by CalcSnapGeometry().
int snapObjectsContext (struct bContext * C, const float mval[2], int * r_dist, float r_loc[3], float r_no[3], SnapMode mode)
Definition at line 1698 of file transform_snap.c.
References CTX_data_edit_object(), CTX_data_scene(), CTX_wm_area(), CTX_wm_region(), ListBase::first, snapObjects(), and ScrArea::spacedata.
Referenced by EMBM_project_snap_verts(), and sk_getStrokeSnapPoint().
int snapObjectsTransform (struct TransInfo * t, const float mval[2], int * r_dist, float r_loc[3], float r_no[3], SnapMode mode)
Definition at line 1693 of file transform_snap.c.
References TransInfo::ar, TransInfo::obedit, TransInfo::scene, snapObjects(), and TransInfo::view.
Referenced by applyProject(), and CalcSnapGeometry().
void transform_keymap_for_space (struct wmKeyConfig * keyconf, struct wmKeyMap * keymap, int spaceid)
Definition at line 844 of file transform_ops.c.
References DKEY, EKEY, EVT_TWEAK_A, EVT_TWEAK_S, GKEY, TransformModeItem::idname, KM_ALT, KM_ANY, KM_CTRL, KM_PRESS, KM_SHIFT, MKEY, OP_MIRROR, OP_RESIZE, OP_ROTATION, OP_SEQ_SLIDE, OP_SHEAR, OP_TOSPHERE, OP_TRANSLATION, OP_WARP, wmKeyMapItem::ptr, RKEY, RNA_boolean_set(), RNA_enum_set(), RNA_string_set(), SKEY, SPACE_ACTION, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_SEQ, SPACE_VIEW3D, SPACEKEY, TABKEY, TFM_TIME_EXTEND, TFM_TIME_SCALE, TFM_TIME_SLIDE, TFM_TIME_TRANSLATE, TFM_TRANSLATION, TKEY, transform_modal_keymap(), TRUE, WKEY, WM_keymap_add_item(), and WM_modalkeymap_assign().
Referenced by action_keymap_keyframes(), clip_keymap(), ED_keymap_uvedit(), graphedit_keymap_keyframes(), nla_keymap_main(), node_keymap(), sequencer_keymap(), and view3d_keymap().
void transform_operatortypes (void)
Definition at line 826 of file transform_ops.c.
References TransformModeItem::idname, TransformModeItem::opfunc, TRANSFORM_OT_create_orientation(), TRANSFORM_OT_delete_orientation(), TRANSFORM_OT_select_orientation(), TRANSFORM_OT_snap_type(), TRANSFORM_OT_transform(), and WM_operatortype_append().
Referenced by view3d_operatortypes().
void Transform_Properties (struct wmOperatorType * ot, int flags)
Definition at line 444 of file transform_ops.c.
References FLT_MAX, NULL, P_ALIGN_SNAP, P_AXIS, P_CONSTRAINT, P_CORRECT_UV, P_GEO_SNAP, P_MIRROR, P_OPTIONS, P_PROPORTIONAL, P_SNAP, PROP_DIRECTION, PROP_ENUM, PROP_FLOAT, PROP_HIDDEN, PROP_NONE, proportional_editing_items, proportional_falloff_items, RNA_def_boolean(), RNA_def_boolean_vector(), RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_float(), RNA_def_float_vector(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_flag(), RNA_def_property_ui_text(), rna_TransformOrientation_itemf(), snap_target_items, and wmOperatorType::srna.
Referenced by MESH_OT_rip(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), TRANSFORM_OT_warp(), and VIEW3D_OT_manipulator().
Variable Documentation
enum { ... } TfmMode