Blender: mmap_win.h File Reference
mmap_win.h File Reference
Guarded memory (de)allocation
#include "MEM_sys_types.h"
Defines
#define PROT_NONE 0
#define PROT_READ 1
#define PROT_WRITE 2
#define PROT_EXEC 4
#define MAP_FILE 0
#define MAP_SHARED 1
#define MAP_PRIVATE 2
#define MAP_TYPE 0xF
#define MAP_FIXED 0x10
#define MAP_ANONYMOUS 0x20
#define MAP_ANON MAP_ANONYMOUS
#define MAP_FAILED ((void *)-1)
Functions
void * mmap (void *start, size_t len, int prot, int flags, int fd, off_t offset)
intptr_t munmap (void *ptr, intptr_t size)
Detailed Description
Author:
Andrea Weikert
Definition in file mmap_win.h.
Define Documentation
#define MAP_ANON MAP_ANONYMOUS
Definition at line 47 of file mmap_win.h.
Referenced by MEM_mapallocN().
#define MAP_ANONYMOUS 0x20
Definition at line 46 of file mmap_win.h.
#define MAP_FAILED ((void *)-1)
Definition at line 49 of file mmap_win.h.
#define MAP_FILE 0
Definition at line 41 of file mmap_win.h.
#define MAP_FIXED 0x10
Definition at line 45 of file mmap_win.h.
#define MAP_PRIVATE 2
Definition at line 43 of file mmap_win.h.
#define MAP_SHARED 1
Definition at line 42 of file mmap_win.h.
Referenced by IMB_loadifffile(), imb_loadtilefile(), and MEM_mapallocN().
#define MAP_TYPE 0xF
Definition at line 44 of file mmap_win.h.
#define PROT_EXEC 4
Definition at line 39 of file mmap_win.h.
#define PROT_NONE 0
Definition at line 36 of file mmap_win.h.
#define PROT_READ 1
Definition at line 37 of file mmap_win.h.
Referenced by IMB_loadifffile(), imb_loadtilefile(), and MEM_mapallocN().
#define PROT_WRITE 2
Definition at line 38 of file mmap_win.h.
Referenced by MEM_mapallocN().
Function Documentation
void* mmap (void * start, size_t len, int prot, int flags, int fd, off_t offset)
Referenced by IMB_loadifffile(), imb_loadtilefile(), and MEM_mapallocN().
intptr_t munmap (void * ptr, intptr_t size)
Referenced by IMB_loadifffile(), imb_loadtilefile(), and rem_memblock().