Blender: ImageMix.cpp File Reference
ImageMix.cpp File Reference
BGE Video Texture
#include <PyObjectPlus.h>
#include <structmember.h>
#include "ImageMix.h"
#include "ImageBase.h"
#include "Exception.h"
Functions
ImageSourceMix * getImageSourceMix (ImageSource *src)
ImageMix * getImageMix (PyImage *self)
PyObject * getWeight (PyImage *self, PyObject *args)
PyObject * setWeight (PyImage *self, PyObject *args)
Variables
ExceptionID ImageSizesNotMatch
ExpDesc ImageSizesNotMatchDesc (ImageSizesNotMatch,"Image sizes of sources are different")
static PyMethodDef imageMixMethods []
static PyGetSetDef imageMixGetSets []
PyTypeObject ImageMixType
Detailed Description
Definition in file ImageMix.cpp.
Function Documentation
ImageMix* getImageMix (PyImage * self) [inline]
Definition at line 104 of file ImageMix.cpp.
Referenced by getWeight(), and setWeight().
ImageSourceMix* getImageSourceMix (ImageSource * src) [inline]
Definition at line 41 of file ImageMix.cpp.
Referenced by ImageMix::calcImage(), ImageMix::getWeight(), and ImageMix::setWeight().
PyObject* getWeight (PyImage * self, PyObject * args)
Definition at line 111 of file ImageMix.cpp.
References getImageMix(), ImageMix::getWeight(), and NULL.
PyObject* setWeight (PyImage * self, PyObject * args)
Definition at line 128 of file ImageMix.cpp.
References getImageMix(), and NULL.
Variable Documentation
PyGetSetDef imageMixGetSets[] [static]
Initial value:
{
    {(char*)"valid", (getter)Image_valid, NULL, (char*)"bool to tell if an image is available", NULL},
    {(char*)"image", (getter)Image_getImage, NULL, (char*)"image data", NULL},
    {(char*)"size", (getter)Image_getSize, NULL, (char*)"image size", NULL},
    {(char*)"scale", (getter)Image_getScale, (setter)Image_setScale, (char*)"fast scale of image (near neighbor)", NULL},
    {(char*)"flip", (getter)Image_getFlip, (setter)Image_setFlip, (char*)"flip image vertically", NULL},
    {(char*)"filter", (getter)Image_getFilter, (setter)Image_setFilter, (char*)"pixel filter", NULL},
    {NULL}
}
Definition at line 160 of file ImageMix.cpp.
PyMethodDef imageMixMethods[] [static]
Initial value:
{
    {"getSource", (PyCFunction)Image_getSource, METH_VARARGS, "get image source"},
    {"setSource", (PyCFunction)Image_setSource, METH_VARARGS, "set image source"},
    {"getWeight", (PyCFunction)getWeight, METH_VARARGS, "get image source weight"},
    {"setWeight", (PyCFunction)setWeight, METH_VARARGS, "set image source weight"},
    {"refresh", (PyCFunction)Image_refresh, METH_NOARGS, "Refresh image - invalidate its current content"},
    {NULL}
}
Definition at line 149 of file ImageMix.cpp.
PyTypeObject ImageMixType
Definition at line 173 of file ImageMix.cpp.
Referenced by registerAllTypes().
ExceptionID ImageSizesNotMatch
Definition at line 66 of file ImageMix.cpp.
ExpDesc ImageSizesNotMatchDesc(ImageSizesNotMatch,"Image sizes of sources are different")
Referenced by registerAllExceptions().