Blender: subsurf_ccg.c File Reference
subsurf_ccg.c File Reference
blenkernel
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <float.h>
#include "MEM_guardedalloc.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_modifier_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_utildefines.h"
#include "BLI_bitmap.h"
#include "BLI_blenlib.h"
#include "BLI_edgehash.h"
#include "BLI_math.h"
#include "BLI_memarena.h"
#include "BLI_pbvh.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_global.h"
#include "BKE_mesh.h"
#include "BKE_modifier.h"
#include "BKE_multires.h"
#include "BKE_paint.h"
#include "BKE_scene.h"
#include "BKE_subsurf.h"
#include "BKE_tessmesh.h"
#include "PIL_time.h"
#include "BLI_array.h"
#include "GL/glew.h"
#include "GPU_draw.h"
#include "GPU_extensions.h"
#include "GPU_material.h"
#include "CCGSubSurf.h"
Classes
struct FaceVertWeightEntry
struct WeightTable
Defines
#define PASSATTRIB(dx, dy, vert)
#define PASSATTRIB(dx, dy, vert)
Typedefs
typedef struct FaceVertWeightEntry FaceVertWeightEntry
typedef struct WeightTable WeightTable
Enumerations
enum CCGFlags { CCG_USE_AGING = 1, CCG_USE_ARENA = 2, CCG_CALC_NORMALS = 4 }
Functions
static CCGDerivedMesh * getCCGDerivedMesh (CCGSubSurf *ss, int drawInteriorEdges, int useSubsurfUv, DerivedMesh *dm)
static int ccgDM_use_grid_pbvh (CCGDerivedMesh *ccgdm)
static void * arena_alloc (CCGAllocatorHDL a, int numBytes)
static void * arena_realloc (CCGAllocatorHDL a, void *ptr, int newSize, int oldSize)
static void arena_free (CCGAllocatorHDL UNUSED(a), void *UNUSED(ptr))
static void arena_release (CCGAllocatorHDL a)
static CCGSubSurf * _getSubSurf (CCGSubSurf *prevSS, int subdivLevels, CCGFlags flags)
static int getEdgeIndex (CCGSubSurf *ss, CCGEdge *e, int x, int edgeSize)
static int getFaceIndex (CCGSubSurf *ss, CCGFace *f, int S, int x, int y, int edgeSize, int gridSize)
static void get_face_uv_map_vert (UvVertMap *vmap, struct MPoly *mpoly, struct MLoop *ml, int fi, CCGVertHDL *fverts)
static int ss_sync_from_uv (CCGSubSurf *ss, CCGSubSurf *origss, DerivedMesh *dm, MLoopUV *mloopuv)
static void set_subsurf_uv (CCGSubSurf *ss, DerivedMesh *dm, DerivedMesh *result, int n)
static float * get_ss_weights (WeightTable *wtable, int gridCuts, int faceLen)
static void free_ss_weights (WeightTable *wtable)
static void ss_sync_from_derivedmesh (CCGSubSurf *ss, DerivedMesh *dm, float(*vertexCos)[3], int useFlatSubdiv)
static int ccgDM_getVertMapIndex (CCGSubSurf *ss, CCGVert *v)
static int ccgDM_getEdgeMapIndex (CCGSubSurf *ss, CCGEdge *e)
static int ccgDM_getFaceMapIndex (CCGSubSurf *ss, CCGFace *f)
static void ccgDM_getMinMax (DerivedMesh *dm, float min_r[3], float max_r[3])
static int ccgDM_getNumVerts (DerivedMesh *dm)
static int ccgDM_getNumEdges (DerivedMesh *dm)
static int ccgDM_getNumTessFaces (DerivedMesh *dm)
static int ccgDM_getNumLoops (DerivedMesh *dm)
static void ccgDM_getFinalVert (DerivedMesh *dm, int vertNum, MVert *mv)
static void ccgDM_getFinalVertCo (DerivedMesh *dm, int vertNum, float co_r[3])
static void ccgDM_getFinalVertNo (DerivedMesh *dm, int vertNum, float no_r[3])
static void ccgDM_getFinalEdge (DerivedMesh *dm, int edgeNum, MEdge *med)
static void ccgDM_getFinalFace (DerivedMesh *dm, int faceNum, MFace *mf)
void subsurf_copy_grid_hidden (DerivedMesh *dm, const MPoly *mpoly, MVert *mvert, const MDisps *mdisps)
static void ccgDM_copyFinalVertArray (DerivedMesh *dm, MVert *mvert)
static void ccgDM_copyFinalEdgeArray (DerivedMesh *dm, MEdge *medge)
static void ccgDM_copyFinalFaceArray (DerivedMesh *dm, MFace *mface)
static void ccgDM_copyFinalLoopArray (DerivedMesh *dm, MLoop *mloop)
static void ccgDM_copyFinalPolyArray (DerivedMesh *dm, MPoly *mpoly)
static void ccgdm_getVertCos (DerivedMesh *dm, float(*cos)[3])
static void ccgDM_foreachMappedVert (DerivedMesh *dm, void(*func)(void *userData, int index, const float co[3], const float no_f[3], const short no_s[3]), void *userData)
static void ccgDM_foreachMappedEdge (DerivedMesh *dm, void(*func)(void *userData, int index, const float v0co[3], const float v1co[3]), void *userData)
static void ccgDM_drawVerts (DerivedMesh *dm)
static void ccgdm_pbvh_update (CCGDerivedMesh *ccgdm)
static void ccgDM_drawEdges (DerivedMesh *dm, int drawLooseEdges, int drawAllEdges)
static void ccgDM_drawLooseEdges (DerivedMesh *dm)
static void ccgDM_glNormalFast (float *a, float *b, float *c, float *d)
static void ccgDM_drawFacesSolid (DerivedMesh *dm, float(*partial_redraw_planes)[4], int fast, DMSetMaterial setMaterial)
static void ccgDM_drawMappedFacesGLSL (DerivedMesh *dm, DMSetMaterial setMaterial, DMSetDrawOptions setDrawOptions, void *userData)
static void ccgDM_drawFacesGLSL (DerivedMesh *dm, DMSetMaterial setMaterial)
static void ccgDM_drawMappedFacesMat (DerivedMesh *dm, void(*setMaterial)(void *userData, int, void *attribs), int(*setFace)(void *userData, int index), void *userData)
static void ccgDM_drawFacesTex_common (DerivedMesh *dm, DMSetDrawOptionsTex drawParams, DMSetDrawOptions drawParamsMapped, DMCompareDrawOptions compareDrawOptions, void *userData)
static void ccgDM_drawFacesTex (DerivedMesh *dm, DMSetDrawOptionsTex setDrawOptions, DMCompareDrawOptions compareDrawOptions, void *userData)
static void ccgDM_drawMappedFacesTex (DerivedMesh *dm, DMSetDrawOptions setDrawOptions, DMCompareDrawOptions compareDrawOptions, void *userData)
static void ccgDM_drawUVEdges (DerivedMesh *dm)
static void ccgDM_drawMappedFaces (DerivedMesh *dm, DMSetDrawOptions setDrawOptions, DMSetMaterial setMaterial, DMCompareDrawOptions compareDrawOptions, void *userData, DMDrawFlag flag)
static void ccgDM_drawMappedEdges (DerivedMesh *dm, DMSetDrawOptions setDrawOptions, void *userData)
static void ccgDM_drawMappedEdgesInterp (DerivedMesh *dm, DMSetDrawOptions setDrawOptions, DMSetDrawInterpOptions setDrawInterpOptions, void *userData)
static void ccgDM_foreachMappedFaceCenter (DerivedMesh *dm, void(*func)(void *userData, int index, const float co[3], const float no[3]), void *userData)
static void ccgDM_release (DerivedMesh *dm)
static void ccg_loops_to_corners (CustomData *fdata, CustomData *ldata, CustomData *pdata, int loopstart, int findex, int polyindex, const int numTex, const int numCol, const int hasPCol, const int hasOrigSpace)
static void * ccgDM_get_vert_data_layer (DerivedMesh *dm, int type)
static void * ccgDM_get_edge_data_layer (DerivedMesh *dm, int type)
static void * ccgDM_get_tessface_data_layer (DerivedMesh *dm, int type)
static void * ccgDM_get_vert_data (DerivedMesh *dm, int index, int type)
static void * ccgDM_get_edge_data (DerivedMesh *dm, int index, int type)
static void * ccgDM_get_tessface_data (DerivedMesh *dm, int index, int type)
static int ccgDM_getNumGrids (DerivedMesh *dm)
static int ccgDM_getGridSize (DerivedMesh *dm)
static int ccgdm_adjacent_grid (int *gridOffset, CCGFace *f, int S, int offset)
static void ccgdm_create_grids (DerivedMesh *dm)
static DMGridData ** ccgDM_getGridData (DerivedMesh *dm)
static DMGridAdjacency * ccgDM_getGridAdjacency (DerivedMesh *dm)
static int * ccgDM_getGridOffset (DerivedMesh *dm)
static DMFlagMat * ccgDM_getGridFlagMats (DerivedMesh *dm)
static BLI_bitmap * ccgDM_getGridHidden (DerivedMesh *dm)
static const MeshElemMap * ccgDM_getPolyMap (Object *ob, DerivedMesh *dm)
static struct PBVH * ccgDM_getPBVH (Object *ob, DerivedMesh *dm)
static void ccgDM_recalcTessellation (DerivedMesh *UNUSED(dm))
static void ccgDM_calcNormals (DerivedMesh *UNUSED(dm))
struct DerivedMesh * subsurf_make_derived_from_derived (struct DerivedMesh *dm, struct SubsurfModifierData *smd, int useRenderParams, float(*vertCos)[3], int isFinalCalc, int forEditMode, int inEditMode)
void subsurf_calculate_limit_positions (Mesh *me, float(*positions_r)[3])
Variables
GLubyte stipple_quarttone [128]
Detailed Description
Definition in file subsurf_ccg.c.
Define Documentation
#define PASSATTRIB (dx, dy, vert)
Value:
{                                              \
    if (attribs.totorco) {                                                      \
        index = getFaceIndex(ss, f, S, x + dx, y + dy, edgeSize, gridSize);     \
        glVertexAttrib3fvARB(attribs.orco.glIndex, attribs.orco.array[index]);  \
    }                                                                           \
    for (b = 0; b < attribs.tottface; b++) {                                    \
        MTFace *tf = &attribs.tface[b].array[a];                                \
        glVertexAttrib2fvARB(attribs.tface[b].glIndex, tf->uv[vert]);           \
    }                                                                           \
    for (b = 0; b < attribs.totmcol; b++) {                                     \
        MCol *cp = &attribs.mcol[b].array[a * 4 + vert];                        \
        GLubyte col[4];                                                         \
        col[0] = cp->b; col[1] = cp->g; col[2] = cp->r; col[3] = cp->a;         \
        glVertexAttrib4ubvARB(attribs.mcol[b].glIndex, col);                    \
    }                                                                           \
    if (attribs.tottang) {                                                      \
        float *tang = attribs.tang.array[a * 4 + vert];                         \
        glVertexAttrib4fvARB(attribs.tang.glIndex, tang);                       \
    }                                                                           \
}
#define PASSATTRIB (dx, dy, vert)
Value:
{                                              \
    if (attribs.totorco) {                                                      \
        index = getFaceIndex(ss, f, S, x + dx, y + dy, edgeSize, gridSize);     \
        if (attribs.orco.glTexco)                                               \
            glTexCoord3fv(attribs.orco.array[index]);                           \
        else                                                                    \
            glVertexAttrib3fvARB(attribs.orco.glIndex, attribs.orco.array[index]);  \
    }                                                                           \
    for (b = 0; b < attribs.tottface; b++) {                                    \
        MTFace *tf = &attribs.tface[b].array[a];                                \
        if (attribs.tface[b].glTexco)                                           \
            glTexCoord2fv(tf->uv[vert]);                                        \
        else                                                                    \
            glVertexAttrib2fvARB(attribs.tface[b].glIndex, tf->uv[vert]);       \
    }                                                                           \
    for (b = 0; b < attribs.totmcol; b++) {                                     \
        MCol *cp = &attribs.mcol[b].array[a * 4 + vert];                        \
        GLubyte col[4];                                                         \
        col[0] = cp->b; col[1] = cp->g; col[2] = cp->r; col[3] = cp->a;         \
        glVertexAttrib4ubvARB(attribs.mcol[b].glIndex, col);                    \
    }                                                                           \
    if (attribs.tottang) {                                                      \
        float *tang = attribs.tang.array[a * 4 + vert];                         \
        glVertexAttrib4fvARB(attribs.tang.glIndex, tang);                       \
    }                                                                           \
}
Typedef Documentation
typedef struct FaceVertWeightEntry FaceVertWeightEntry
typedef struct WeightTable WeightTable
Enumeration Type Documentation
enum CCGFlags
Enumerator:
CCG_USE_AGING
CCG_USE_ARENA
CCG_CALC_NORMALS
Definition at line 110 of file subsurf_ccg.c.
Function Documentation
static CCGSubSurf* _getSubSurf (CCGSubSurf * prevSS, int subdivLevels, CCGFlags flags) [static]
Definition at line 116 of file subsurf_ccg.c.
References CCGAllocatorIFC::alloc, arena_alloc(), arena_free(), arena_realloc(), arena_release(), BLI_memarena_new(), CCG_CALC_NORMALS, CCG_USE_AGING, CCG_USE_ARENA, ccgSubSurf_free(), ccgSubSurf_getUseAgeCounts(), ccgSubSurf_new(), ccgSubSurf_setCalcVertexNormals(), ccgSubSurf_setSubdivisionLevels(), ccgSubSurf_setUseAgeCounts(), CCGMeshIFC::edgeUserSize, CCGMeshIFC::faceUserSize, CCGAllocatorIFC::free, MAX2, NULL, CCGAllocatorIFC::realloc, CCGAllocatorIFC::release, CCGMeshIFC::vertDataSize, and CCGMeshIFC::vertUserSize.
Referenced by set_subsurf_uv(), subsurf_calculate_limit_positions(), and subsurf_make_derived_from_derived().
static void* arena_alloc (CCGAllocatorHDL a, int numBytes) [static]
Definition at line 86 of file subsurf_ccg.c.
References BLI_memarena_alloc().
Referenced by _getSubSurf().
static void arena_free (CCGAllocatorHDL UNUSEDa, void * UNUSEDptr) [static]
Definition at line 100 of file subsurf_ccg.c.
Referenced by _getSubSurf().
static void* arena_realloc (CCGAllocatorHDL a, void * ptr, int newSize, int oldSize) [static]
Definition at line 91 of file subsurf_ccg.c.
References BLI_memarena_alloc().
Referenced by _getSubSurf().
static void arena_release (CCGAllocatorHDL a) [static]
Definition at line 105 of file subsurf_ccg.c.
References BLI_memarena_free().
Referenced by _getSubSurf().
static void ccg_loops_to_corners (CustomData * fdata, CustomData * ldata, CustomData * pdata, int loopstart, int findex, int polyindex, const int numTex, const int numCol, const int hasPCol, const int hasOrigSpace) [static]
Definition at line 2465 of file subsurf_ccg.c.
References CD_MCOL, CD_MLOOPCOL, CD_MLOOPUV, CD_MTEXPOLY, CD_MTFACE, CD_ORIGSPACE, CD_ORIGSPACE_MLOOP, CD_PREVIEW_MCOL, CD_PREVIEW_MLOOPCOL, copy_v2_v2(), CustomData_get(), CustomData_get_n(), i, ME_MTEXFACE_CPY, MESH_MLOOPCOL_TO_MCOL, OrigSpaceLoop::uv, OrigSpaceFace::uv, MLoopUV::uv, and MTFace::uv.
Referenced by getCCGDerivedMesh().
static int ccgdm_adjacent_grid (int * gridOffset, CCGFace * f, int S, int offset) [static]
Definition at line 2682 of file subsurf_ccg.c.
References ccgSubSurf_getEdgeFace(), ccgSubSurf_getEdgeNumFaces(), ccgSubSurf_getFaceEdge(), ccgSubSurf_getFaceFaceHandle(), ccgSubSurf_getFaceNumVerts(), GET_INT_FROM_POINTER, and i.
Referenced by ccgdm_create_grids().
static void ccgDM_calcNormals (DerivedMesh * UNUSEDdm) [static]
Definition at line 2912 of file subsurf_ccg.c.
Referenced by getCCGDerivedMesh().
static void ccgDM_copyFinalEdgeArray (DerivedMesh * dm, MEdge * medge) [static]
Definition at line 1083 of file subsurf_ccg.c.
References ccgSubSurf_getEdgeEdgeHandle(), ccgSubSurf_getEdgeNumFaces(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumEdges(), ccgSubSurf_getNumFaces(), CCGDerivedMesh::drawInteriorEdges, CCGDerivedMesh::edge, CCGDerivedMesh::edgeFlags, CCGDerivedMesh::edgeMap, CCGDerivedMesh::face, CCGDerivedMesh::faceMap, MEdge::flag, GET_INT_FROM_POINTER, getEdgeIndex(), getFaceIndex(), i, ME_EDGEDRAW, ME_EDGERENDER, ME_LOOSEEDGE, ME_SEAM, ME_SHARP, CCGDerivedMesh::ss, MEdge::v1, and MEdge::v2.
Referenced by getCCGDerivedMesh().
static void ccgDM_copyFinalFaceArray (DerivedMesh * dm, MFace * mface) [static]
Definition at line 1165 of file subsurf_ccg.c.
References ccgSubSurf_getEdgeSize(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumFaces(), CCGDerivedMesh::face, CCGDerivedMesh::faceFlags, CCGDerivedMesh::faceMap, MFace::flag, getFaceIndex(), i, MFace::mat_nr, ME_SMOOTH, CCGDerivedMesh::ss, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by getCCGDerivedMesh().
static void ccgDM_copyFinalLoopArray (DerivedMesh * dm, MLoop * mloop) [static]
Definition at line 1206 of file subsurf_ccg.c.
References BLI_edgehash_insert(), BLI_edgehash_lookup(), BLI_edgehash_new(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumFaces(), CCGDerivedMesh::dm, MLoop::e, CCGDerivedMesh::ehash, CCGDerivedMesh::face, CCGDerivedMesh::faceMap, GET_INT_FROM_POINTER, DerivedMesh::getEdgeArray, getFaceIndex(), i, DerivedMesh::numEdgeData, SET_INT_IN_POINTER, CCGDerivedMesh::ss, MLoop::v, MEdge::v1, and MEdge::v2.
Referenced by getCCGDerivedMesh().
static void ccgDM_copyFinalPolyArray (DerivedMesh * dm, MPoly * mpoly) [static]
Definition at line 1273 of file subsurf_ccg.c.
References ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumFaces(), CCGDerivedMesh::face, CCGDerivedMesh::faceFlags, CCGDerivedMesh::faceMap, MPoly::flag, i, MPoly::loopstart, MPoly::mat_nr, ME_SMOOTH, CCGDerivedMesh::ss, and MPoly::totloop.
Referenced by getCCGDerivedMesh().
static void ccgDM_copyFinalVertArray (DerivedMesh * dm, MVert * mvert) [static]
Definition at line 1015 of file subsurf_ccg.c.
References ccgSubSurf_getEdgeData(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getFaceCenterData(), ccgSubSurf_getFaceGridData(), ccgSubSurf_getFaceGridEdgeData(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumEdges(), ccgSubSurf_getNumFaces(), ccgSubSurf_getNumVerts(), ccgSubSurf_getVertData(), DMGridData::co, co, copy_v3_v3(), CCGDerivedMesh::edge, CCGDerivedMesh::edgeMap, CCGDerivedMesh::face, CCGDerivedMesh::faceMap, i, DMGridData::no, normal_float_to_short_v3(), CCGDerivedMesh::ss, CCGDerivedMesh::vert, and CCGDerivedMesh::vertMap.
Referenced by getCCGDerivedMesh().
static void ccgdm_create_grids (DerivedMesh * dm) [static]
Definition at line 2716 of file subsurf_ccg.c.
References ccgdm_adjacent_grid(), ccgDM_getNumGrids(), ccgSubSurf_getFaceGridDataArray(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getNumFaces(), CCGDerivedMesh::face, CCGDerivedMesh::faceFlags, CCGDerivedMesh::faceMap, CCGDerivedMesh::gridAdjacency, CCGDerivedMesh::gridData, CCGDerivedMesh::gridFaces, CCGDerivedMesh::gridFlagMats, CCGDerivedMesh::gridHidden, CCGDerivedMesh::gridOffset, DMGridAdjacency::index, MEM_callocN(), MEM_mallocN(), DMGridAdjacency::rotation, and CCGDerivedMesh::ss.
Referenced by ccgDM_getGridAdjacency(), ccgDM_getGridData(), ccgDM_getGridFlagMats(), ccgDM_getGridHidden(), ccgDM_getGridOffset(), and ccgDM_getPBVH().
static void ccgDM_drawEdges (DerivedMesh * dm, int drawLooseEdges, int drawAllEdges) [static]
Definition at line 1499 of file subsurf_ccg.c.
References ccgdm_pbvh_update(), ccgSubSurf_getEdgeAge(), ccgSubSurf_getEdgeDataArray(), ccgSubSurf_getEdgeNumFaces(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getFaceGridDataArray(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumEdges(), ccgSubSurf_getNumFaces(), ccgSubSurf_getUseAgeCounts(), co, CCGDerivedMesh::drawInteriorEdges, CCGDerivedMesh::edge, CCGDerivedMesh::edgeFlags, CCGDerivedMesh::edgeMap, CCGDerivedMesh::face, CCGDerivedMesh::faceMap, G, G_BACKBUFSEL, i, ME_EDGEDRAW, NULL, and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static void ccgDM_drawFacesGLSL (DerivedMesh * dm, DMSetMaterial setMaterial) [static]
Definition at line 1841 of file subsurf_ccg.c.
References DerivedMesh::drawMappedFacesGLSL, and NULL.
Referenced by getCCGDerivedMesh().
static void ccgDM_drawFacesSolid (DerivedMesh * dm, float(*) partial_redraw_planes[4], int fast, DMSetMaterial setMaterial) [static]
Definition at line 1607 of file subsurf_ccg.c.
References BLI_pbvh_draw(), ccgDM_glNormalFast(), ccgdm_pbvh_update(), ccgSubSurf_getFaceFaceHandle(), ccgSubSurf_getFaceGridDataArray(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumFaces(), co, DMGridData::co, CCGDerivedMesh::face, CCGDerivedMesh::faceFlags, CCGDerivedMesh::faceMap, DMFlagMat::flag, GET_INT_FROM_POINTER, i, DMFlagMat::mat_nr, ME_SMOOTH, CCGDerivedMesh::mmd, CCGDerivedMesh::multires, DMGridData::no, NULL, DerivedMesh::numTessFaceData, CCGDerivedMesh::pbvh, CCGDerivedMesh::ss, and step().
Referenced by getCCGDerivedMesh().
static void ccgDM_drawFacesTex (DerivedMesh * dm, DMSetDrawOptionsTex setDrawOptions, DMCompareDrawOptions compareDrawOptions, void * userData) [static]
Definition at line 2142 of file subsurf_ccg.c.
References ccgDM_drawFacesTex_common(), and NULL.
Referenced by getCCGDerivedMesh().
static void ccgDM_drawFacesTex_common (DerivedMesh * dm, DMSetDrawOptionsTex drawParams, DMSetDrawOptions drawParamsMapped, DMCompareDrawOptions compareDrawOptions, void * userData) [static]
Definition at line 1993 of file subsurf_ccg.c.
References ccgDM_getFaceMapIndex(), ccgDM_glNormalFast(), ccgdm_pbvh_update(), ccgSubSurf_getFaceFaceHandle(), ccgSubSurf_getFaceGridDataArray(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumFaces(), CD_MCOL, CD_MTFACE, CD_PREVIEW_MCOL, CD_TEXTURE_MCOL, co, DMGridData::co, DM_DRAW_OPTION_NO_MCOL, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, DM_get_tessface_data_layer(), CCGDerivedMesh::face, CCGDerivedMesh::faceFlags, CCGDerivedMesh::faceMap, DMFlagMat::flag, GET_INT_FROM_POINTER, DerivedMesh::getTessFaceDataArray, GPU_enable_material(), i, DMFlagMat::mat_nr, ME_SMOOTH, DMGridData::no, NULL, ORIGINDEX_NONE, CCGDerivedMesh::ss, and MTFace::uv.
Referenced by ccgDM_drawFacesTex(), and ccgDM_drawMappedFacesTex().
static void ccgDM_drawLooseEdges (DerivedMesh * dm) [static]
Definition at line 1570 of file subsurf_ccg.c.
References ccgSubSurf_getEdgeDataArray(), ccgSubSurf_getEdgeNumFaces(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getNumEdges(), co, CCGDerivedMesh::edge, CCGDerivedMesh::edgeMap, i, and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static void ccgDM_drawMappedEdges (DerivedMesh * dm, DMSetDrawOptions setDrawOptions, void * userData) [static]
Definition at line 2322 of file subsurf_ccg.c.
References ccgDM_getEdgeMapIndex(), ccgEdgeIterator_free(), ccgEdgeIterator_getCurrent(), ccgEdgeIterator_isStopped(), ccgEdgeIterator_next(), ccgSubSurf_getEdgeAge(), ccgSubSurf_getEdgeDataArray(), ccgSubSurf_getEdgeIterator(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getUseAgeCounts(), co, DM_DRAW_OPTION_SKIP, G, G_BACKBUFSEL, i, NULL, and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static void ccgDM_drawMappedEdgesInterp (DerivedMesh * dm, DMSetDrawOptions setDrawOptions, DMSetDrawInterpOptions setDrawInterpOptions, void * userData) [static]
Definition at line 2356 of file subsurf_ccg.c.
References ccgDM_getEdgeMapIndex(), ccgEdgeIterator_free(), ccgEdgeIterator_getCurrent(), ccgEdgeIterator_isStopped(), ccgEdgeIterator_next(), ccgSubSurf_getEdgeAge(), ccgSubSurf_getEdgeDataArray(), ccgSubSurf_getEdgeIterator(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getUseAgeCounts(), co, DM_DRAW_OPTION_SKIP, G, G_BACKBUFSEL, i, NULL, and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static void ccgDM_drawMappedFaces (DerivedMesh * dm, DMSetDrawOptions setDrawOptions, DMSetMaterial setMaterial, DMCompareDrawOptions compareDrawOptions, void * userData, DMDrawFlag flag) [static]
Definition at line 2192 of file subsurf_ccg.c.
References ccgDM_getFaceMapIndex(), ccgDM_glNormalFast(), ccgSubSurf_getFaceFaceHandle(), ccgSubSurf_getFaceGridDataArray(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumFaces(), CD_MCOL, CD_PREVIEW_MCOL, co, DMGridData::co, DM_DRAW_ALWAYS_SMOOTH, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, DM_DRAW_OPTION_STIPPLE, DM_DRAW_USE_COLORS, CCGDerivedMesh::face, CCGDerivedMesh::faceFlags, CCGDerivedMesh::faceMap, DMFlagMat::flag, GET_INT_FROM_POINTER, DerivedMesh::getTessFaceDataArray, i, ME_SMOOTH, DMGridData::no, NULL, ORIGINDEX_NONE, CCGDerivedMesh::ss, and stipple_quarttone.
Referenced by getCCGDerivedMesh().
static void ccgDM_drawMappedFacesGLSL (DerivedMesh * dm, DMSetMaterial setMaterial, DMSetDrawOptions setDrawOptions, void * userData) [static]
Definition at line 1697 of file subsurf_ccg.c.
References ccgDM_getFaceMapIndex(), ccgDM_glNormalFast(), ccgdm_pbvh_update(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getFaceFaceHandle(), ccgSubSurf_getFaceGridDataArray(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumFaces(), co, DMGridData::co, DM_DRAW_OPTION_SKIP, DM_vertex_attributes_from_gpu(), CCGDerivedMesh::face, CCGDerivedMesh::faceFlags, CCGDerivedMesh::faceMap, DMFlagMat::flag, GET_INT_FROM_POINTER, i, DMFlagMat::mat_nr, ME_SMOOTH, DMGridData::no, NULL, ORIGINDEX_NONE, PASSATTRIB, and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static void ccgDM_drawMappedFacesMat (DerivedMesh * dm, void(*)(void *userData, int, void *attribs) setMaterial, int(*)(void *userData, int index) setFace, void * userData) [static]
Definition at line 1847 of file subsurf_ccg.c.
References ccgDM_getFaceMapIndex(), ccgDM_glNormalFast(), ccgdm_pbvh_update(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getFaceFaceHandle(), ccgSubSurf_getFaceGridDataArray(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumFaces(), co, DMGridData::co, DM_vertex_attributes_from_gpu(), CCGDerivedMesh::face, CCGDerivedMesh::faceFlags, CCGDerivedMesh::faceMap, DMFlagMat::flag, GET_INT_FROM_POINTER, i, DMFlagMat::mat_nr, ME_SMOOTH, DMGridData::no, NULL, ORIGINDEX_NONE, PASSATTRIB, and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static void ccgDM_drawMappedFacesTex (DerivedMesh * dm, DMSetDrawOptions setDrawOptions, DMCompareDrawOptions compareDrawOptions, void * userData) [static]
Definition at line 2150 of file subsurf_ccg.c.
References ccgDM_drawFacesTex_common(), and NULL.
Referenced by getCCGDerivedMesh().
static void ccgDM_drawUVEdges (DerivedMesh * dm) [static]
Definition at line 2158 of file subsurf_ccg.c.
References CD_MTFACE, DM_get_tessface_data_layer(), DerivedMesh::getTessFaceArray, i, ME_HIDE, DerivedMesh::numTessFaceData, and MTFace::uv.
Referenced by getCCGDerivedMesh().
static void ccgDM_drawVerts (DerivedMesh * dm) [static]
Definition at line 1438 of file subsurf_ccg.c.
References ccgEdgeIterator_free(), ccgEdgeIterator_getCurrent(), ccgEdgeIterator_isStopped(), ccgEdgeIterator_next(), ccgFaceIterator_free(), ccgFaceIterator_getCurrent(), ccgFaceIterator_isStopped(), ccgFaceIterator_next(), ccgSubSurf_getEdgeData(), ccgSubSurf_getEdgeIterator(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getFaceCenterData(), ccgSubSurf_getFaceGridData(), ccgSubSurf_getFaceGridEdgeData(), ccgSubSurf_getFaceIterator(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getVertData(), ccgSubSurf_getVertIterator(), ccgVertIterator_free(), ccgVertIterator_getCurrent(), ccgVertIterator_isStopped(), ccgVertIterator_next(), and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static void ccgDM_foreachMappedEdge (DerivedMesh * dm, void(*)(void *userData, int index, const float v0co[3], const float v1co[3]) func, void * userData) [static]
Definition at line 1414 of file subsurf_ccg.c.
References ccgDM_getEdgeMapIndex(), ccgEdgeIterator_free(), ccgEdgeIterator_getCurrent(), ccgEdgeIterator_isStopped(), ccgEdgeIterator_next(), ccgSubSurf_getEdgeDataArray(), ccgSubSurf_getEdgeIterator(), ccgSubSurf_getEdgeSize(), co, i, and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static void ccgDM_foreachMappedFaceCenter (DerivedMesh * dm, void(*)(void *userData, int index, const float co[3], const float no[3]) func, void * userData) [static]
Definition at line 2392 of file subsurf_ccg.c.
References ccgDM_getFaceMapIndex(), ccgFaceIterator_free(), ccgFaceIterator_getCurrent(), ccgFaceIterator_isStopped(), ccgFaceIterator_next(), ccgSubSurf_getFaceGridData(), ccgSubSurf_getFaceIterator(), DMGridData::co, DMGridData::no, and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static void ccgDM_foreachMappedVert (DerivedMesh * dm, void(*)(void *userData, int index, const float co[3], const float no_f[3], const short no_s[3]) func, void * userData) [static]
Definition at line 1394 of file subsurf_ccg.c.
References ccgDM_getVertMapIndex(), ccgSubSurf_getVertData(), ccgSubSurf_getVertIterator(), ccgVertIterator_free(), ccgVertIterator_getCurrent(), ccgVertIterator_isStopped(), ccgVertIterator_next(), DMGridData::co, DMGridData::no, NULL, and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static void* ccgDM_get_edge_data (DerivedMesh * dm, int index, int type) [static]
Definition at line 2640 of file subsurf_ccg.c.
References ccgDM_get_edge_data_layer(), CD_ORIGINDEX, and DM_get_edge_data().
Referenced by getCCGDerivedMesh().
static void* ccgDM_get_edge_data_layer (DerivedMesh * dm, int type) [static]
Definition at line 2553 of file subsurf_ccg.c.
References ccgDM_getEdgeMapIndex(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getNumEdges(), CD_CALLOC, CD_ORIGINDEX, DM_add_edge_layer(), DM_get_edge_data_layer(), CCGDerivedMesh::edge, CCGDerivedMesh::edgeMap, i, NULL, DerivedMesh::numEdgeData, ORIGINDEX_NONE, and CCGDerivedMesh::ss.
Referenced by ccgDM_get_edge_data(), and getCCGDerivedMesh().
static void* ccgDM_get_tessface_data (DerivedMesh * dm, int index, int type) [static]
Definition at line 2650 of file subsurf_ccg.c.
References ccgDM_get_tessface_data_layer(), CD_ORIGINDEX, and DM_get_tessface_data().
Referenced by getCCGDerivedMesh().
static void* ccgDM_get_tessface_data_layer (DerivedMesh * dm, int type) [static]
Definition at line 2594 of file subsurf_ccg.c.
References ccgDM_getFaceMapIndex(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumFaces(), CD_CALLOC, CD_ORIGINDEX, DM_add_tessface_layer(), DM_get_tessface_data_layer(), CCGDerivedMesh::face, CCGDerivedMesh::faceMap, i, NULL, and CCGDerivedMesh::ss.
Referenced by ccgDM_get_tessface_data(), and getCCGDerivedMesh().
static void* ccgDM_get_vert_data (DerivedMesh * dm, int index, int type) [static]
Definition at line 2630 of file subsurf_ccg.c.
References ccgDM_get_vert_data_layer(), CD_ORIGINDEX, and DM_get_vert_data().
Referenced by getCCGDerivedMesh().
static void* ccgDM_get_vert_data_layer (DerivedMesh * dm, int type) [static]
Definition at line 2517 of file subsurf_ccg.c.
References ccgDM_getVertMapIndex(), ccgSubSurf_getNumVerts(), CD_CALLOC, CD_ORIGINDEX, DM_add_vert_layer(), DM_get_vert_data_layer(), NULL, DerivedMesh::numVertData, ORIGINDEX_NONE, CCGDerivedMesh::ss, CCGDerivedMesh::vert, and CCGDerivedMesh::vertMap.
Referenced by ccgDM_get_vert_data(), and getCCGDerivedMesh().
static int ccgDM_getEdgeMapIndex (CCGSubSurf * ss, CCGEdge * e) [static]
Definition at line 626 of file subsurf_ccg.c.
References ccgSubSurf_getEdgeUserData().
Referenced by ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_foreachMappedEdge(), ccgDM_get_edge_data_layer(), and getCCGDerivedMesh().
static int ccgDM_getFaceMapIndex (CCGSubSurf * ss, CCGFace * f) [static]
Definition at line 631 of file subsurf_ccg.c.
References ccgSubSurf_getFaceUserData().
Referenced by ccgDM_drawFacesTex_common(), ccgDM_drawMappedFaces(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgDM_foreachMappedFaceCenter(), and ccgDM_get_tessface_data_layer().
static void ccgDM_getFinalEdge (DerivedMesh * dm, int edgeNum, MEdge * med) [static]
Definition at line 815 of file subsurf_ccg.c.
References ccgSubSurf_getEdgeNumFaces(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumFaces(), CCGDerivedMesh::edge, CCGDerivedMesh::edgeFlags, CCGDerivedMesh::edgeMap, fabsf, CCGDerivedMesh::face, CCGDerivedMesh::faceMap, MEdge::flag, getEdgeIndex(), getFaceIndex(), i, if(), ME_EDGEDRAW, ME_EDGERENDER, ME_LOOSEEDGE, ME_SEAM, ME_SHARP, NULL, CCGDerivedMesh::ss, CCGDerivedMesh::startEdge, MEdge::v1, and MEdge::v2.
Referenced by getCCGDerivedMesh().
static void ccgDM_getFinalFace (DerivedMesh * dm, int faceNum, MFace * mf) [static]
Definition at line 933 of file subsurf_ccg.c.
References ccgSubSurf_getEdgeSize(), ccgSubSurf_getGridSize(), CCGDerivedMesh::dm, CCGDerivedMesh::face, CCGDerivedMesh::faceFlags, CCGDerivedMesh::faceMap, DMFlagMat::flag, MFace::flag, getFaceIndex(), i, DMFlagMat::mat_nr, MFace::mat_nr, ME_SMOOTH, DerivedMesh::numTessFaceData, CCGDerivedMesh::reverseFaceMap, CCGDerivedMesh::ss, CCGDerivedMesh::startFace, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by getCCGDerivedMesh().
static void ccgDM_getFinalVert (DerivedMesh * dm, int vertNum, MVert * mv) [static]
Definition at line 711 of file subsurf_ccg.c.
References ccgSubSurf_getEdgeData(), ccgSubSurf_getFaceCenterData(), ccgSubSurf_getFaceGridData(), ccgSubSurf_getFaceGridEdgeData(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumEdges(), ccgSubSurf_getNumFaces(), ccgSubSurf_getVertData(), DMGridData::co, MVert::co, copy_v3_v3(), CCGDerivedMesh::edge, CCGDerivedMesh::edgeMap, CCGDerivedMesh::face, CCGDerivedMesh::faceMap, i, DMGridData::no, MVert::no, normal_float_to_short_v3(), CCGDerivedMesh::ss, CCGDerivedMesh::startVert, CCGDerivedMesh::vert, and CCGDerivedMesh::vertMap.
Referenced by ccgDM_getFinalVertCo(), ccgDM_getFinalVertNo(), and getCCGDerivedMesh().
static void ccgDM_getFinalVertCo (DerivedMesh * dm, int vertNum, float co_r[3]) [static]
Definition at line 799 of file subsurf_ccg.c.
References ccgDM_getFinalVert(), MVert::co, and copy_v3_v3().
Referenced by getCCGDerivedMesh().
static void ccgDM_getFinalVertNo (DerivedMesh * dm, int vertNum, float no_r[3]) [static]
Definition at line 807 of file subsurf_ccg.c.
References ccgDM_getFinalVert(), MVert::no, and normal_short_to_float_v3().
Referenced by getCCGDerivedMesh().
static DMGridAdjacency* ccgDM_getGridAdjacency (DerivedMesh * dm) [static]
Definition at line 2793 of file subsurf_ccg.c.
References ccgdm_create_grids(), and CCGDerivedMesh::gridAdjacency.
Referenced by getCCGDerivedMesh().
static DMGridData** ccgDM_getGridData (DerivedMesh * dm) [static]
Definition at line 2785 of file subsurf_ccg.c.
References ccgdm_create_grids(), and CCGDerivedMesh::gridData.
Referenced by getCCGDerivedMesh().
static DMFlagMat* ccgDM_getGridFlagMats (DerivedMesh * dm) [static]
Definition at line 2809 of file subsurf_ccg.c.
References ccgdm_create_grids(), and CCGDerivedMesh::gridFlagMats.
Referenced by getCCGDerivedMesh().
static BLI_bitmap* ccgDM_getGridHidden (DerivedMesh * dm) [static]
Definition at line 2817 of file subsurf_ccg.c.
References ccgdm_create_grids(), and CCGDerivedMesh::gridHidden.
Referenced by getCCGDerivedMesh().
static int* ccgDM_getGridOffset (DerivedMesh * dm) [static]
Definition at line 2801 of file subsurf_ccg.c.
References ccgdm_create_grids(), and CCGDerivedMesh::gridOffset.
Referenced by getCCGDerivedMesh().
static int ccgDM_getGridSize (DerivedMesh * dm) [static]
Definition at line 2676 of file subsurf_ccg.c.
References ccgSubSurf_getGridSize(), and CCGDerivedMesh::ss.
Referenced by ccgDM_getPBVH(), and getCCGDerivedMesh().
static void ccgDM_getMinMax (DerivedMesh * dm, float min_r[3], float max_r[3]) [static]
Definition at line 636 of file subsurf_ccg.c.
References ccgEdgeIterator_free(), ccgEdgeIterator_getCurrent(), ccgEdgeIterator_isStopped(), ccgEdgeIterator_next(), ccgFaceIterator_free(), ccgFaceIterator_getCurrent(), ccgFaceIterator_isStopped(), ccgFaceIterator_next(), ccgSubSurf_getEdgeDataArray(), ccgSubSurf_getEdgeIterator(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getFaceGridDataArray(), ccgSubSurf_getFaceIterator(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumVerts(), ccgSubSurf_getVertData(), ccgSubSurf_getVertIterator(), ccgVertIterator_free(), ccgVertIterator_getCurrent(), ccgVertIterator_isStopped(), ccgVertIterator_next(), co, DO_MINMAX, i, and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static int ccgDM_getNumEdges (DerivedMesh * dm) [static]
Definition at line 689 of file subsurf_ccg.c.
References ccgSubSurf_getNumFinalEdges(), and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static int ccgDM_getNumGrids (DerivedMesh * dm) [static]
Definition at line 2660 of file subsurf_ccg.c.
References ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getNumFaces(), CCGDerivedMesh::face, CCGDerivedMesh::faceMap, and CCGDerivedMesh::ss.
Referenced by ccgdm_create_grids(), ccgDM_getPBVH(), and getCCGDerivedMesh().
static int ccgDM_getNumLoops (DerivedMesh * dm) [static]
Definition at line 703 of file subsurf_ccg.c.
References ccgSubSurf_getNumFinalFaces(), and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static int ccgDM_getNumTessFaces (DerivedMesh * dm) [static]
Definition at line 696 of file subsurf_ccg.c.
References ccgSubSurf_getNumFinalFaces(), and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static int ccgDM_getNumVerts (DerivedMesh * dm) [static]
Definition at line 682 of file subsurf_ccg.c.
References ccgSubSurf_getNumFinalVerts(), and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static struct PBVH* ccgDM_getPBVH (Object * ob, DerivedMesh * dm) [static, read]
Definition at line 2852 of file subsurf_ccg.c.
References BLI_assert, BLI_pbvh_build_grids(), BLI_pbvh_build_mesh(), BLI_pbvh_grids_update(), BLI_pbvh_new(), ccgdm_create_grids(), ccgDM_getGridSize(), ccgDM_getNumGrids(), ccgDM_use_grid_pbvh(), Object::data, CCGDerivedMesh::gridAdjacency, CCGDerivedMesh::gridData, CCGDerivedMesh::gridFaces, CCGDerivedMesh::gridFlagMats, CCGDerivedMesh::gridHidden, Mesh::mface, Mesh::mpoly, Mesh::mvert, NULL, OB_MESH, SculptSession::pbvh, CCGDerivedMesh::pbvh, Object::sculpt, Mesh::totface, Mesh::totvert, and Object::type.
Referenced by getCCGDerivedMesh().
static const MeshElemMap* ccgDM_getPolyMap (Object * ob, DerivedMesh * dm) [static]
Definition at line 2825 of file subsurf_ccg.c.
References create_vert_poly_map(), Object::data, Mesh::mloop, CCGDerivedMesh::mmd, Mesh::mpoly, CCGDerivedMesh::multires, OB_MESH, CCGDerivedMesh::pmap, CCGDerivedMesh::pmap_mem, Mesh::totloop, Mesh::totpoly, Mesh::totvert, and Object::type.
Referenced by getCCGDerivedMesh().
static void ccgdm_getVertCos (DerivedMesh * dm, float(*) cos[3]) [static]
Definition at line 1309 of file subsurf_ccg.c.
References ccgEdgeIterator_getCurrent(), ccgEdgeIterator_isStopped(), ccgEdgeIterator_next(), ccgFaceIterator_free(), ccgFaceIterator_getCurrent(), ccgFaceIterator_isStopped(), ccgFaceIterator_next(), ccgSubSurf_getEdgeData(), ccgSubSurf_getEdgeEdgeHandle(), ccgSubSurf_getEdgeIterator(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getFaceCenterData(), ccgSubSurf_getFaceFaceHandle(), ccgSubSurf_getFaceGridData(), ccgSubSurf_getFaceGridEdgeData(), ccgSubSurf_getFaceIterator(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumEdges(), ccgSubSurf_getNumFaces(), ccgSubSurf_getNumVerts(), ccgSubSurf_getVertData(), ccgSubSurf_getVertIterator(), ccgSubSurf_getVertVertHandle(), ccgVertIterator_free(), ccgVertIterator_getCurrent(), ccgVertIterator_isStopped(), ccgVertIterator_next(), copy_v3_v3(), cos(), GET_INT_FROM_POINTER, i, MEM_freeN(), MEM_mallocN(), and CCGDerivedMesh::ss.
Referenced by getCCGDerivedMesh().
static int ccgDM_getVertMapIndex (CCGSubSurf * ss, CCGVert * v) [static]
Definition at line 621 of file subsurf_ccg.c.
References ccgSubSurf_getVertUserData().
Referenced by ccgDM_foreachMappedVert(), ccgDM_get_vert_data_layer(), and getCCGDerivedMesh().
static void ccgDM_glNormalFast (float * a, float * b, float * c, float * d) [static]
Definition at line 1592 of file subsurf_ccg.c.
Referenced by ccgDM_drawFacesSolid(), ccgDM_drawFacesTex_common(), ccgDM_drawMappedFaces(), ccgDM_drawMappedFacesGLSL(), and ccgDM_drawMappedFacesMat().
static void ccgdm_pbvh_update (CCGDerivedMesh * ccgdm) [static]
Definition at line 1484 of file subsurf_ccg.c.
References BLI_pbvh_get_grid_updates(), ccgDM_use_grid_pbvh(), ccgSubSurf_updateFromFaces(), ccgSubSurf_updateNormals(), MEM_freeN(), CCGDerivedMesh::pbvh, and CCGDerivedMesh::ss.
Referenced by ccgDM_drawEdges(), ccgDM_drawFacesSolid(), ccgDM_drawFacesTex_common(), ccgDM_drawMappedFacesGLSL(), and ccgDM_drawMappedFacesMat().
static void ccgDM_recalcTessellation (DerivedMesh * UNUSEDdm) [static]
Definition at line 2907 of file subsurf_ccg.c.
Referenced by getCCGDerivedMesh().
static void ccgDM_release (DerivedMesh * dm) [static]
Definition at line 2416 of file subsurf_ccg.c.
References BLI_edgehash_free(), BLI_findindex(), ccgSubSurf_free(), DM_release(), CCGDerivedMesh::edgeFlags, CCGDerivedMesh::edgeMap, CCGDerivedMesh::ehash, CCGDerivedMesh::faceFlags, CCGDerivedMesh::faceMap, CCGDerivedMesh::freeSS, DerivedMesh::getNumGrids, CCGDerivedMesh::gridAdjacency, CCGDerivedMesh::gridData, CCGDerivedMesh::gridFaces, CCGDerivedMesh::gridFlagMats, CCGDerivedMesh::gridHidden, CCGDerivedMesh::gridOffset, i, if(), CCGDerivedMesh::local_mmd, MEM_freeN(), CCGDerivedMesh::mmd, CCGDerivedMesh::modified_flags, Object::modifiers, CCGDerivedMesh::multires, MULTIRES_COORDS_MODIFIED, MULTIRES_HIDDEN_MODIFIED, multires_modifier_update_hidden(), multires_modifier_update_mdisps(), NULL, CCGDerivedMesh::ob, CCGDerivedMesh::pmap, CCGDerivedMesh::pmap_mem, CCGDerivedMesh::reverseFaceMap, CCGDerivedMesh::ss, and CCGDerivedMesh::vertMap.
Referenced by getCCGDerivedMesh().
static int ccgDM_use_grid_pbvh (CCGDerivedMesh * ccgdm) [static]
Definition at line 2840 of file subsurf_ccg.c.
References CCGDerivedMesh::mmd, and CCGDerivedMesh::multires.
Referenced by ccgDM_getPBVH(), and ccgdm_pbvh_update().
static void free_ss_weights (WeightTable * wtable) [static]
Definition at line 514 of file subsurf_ccg.c.
References i, WeightTable::len, MEM_freeN(), FaceVertWeightEntry::valid, FaceVertWeightEntry::w, and WeightTable::weight_table.
Referenced by getCCGDerivedMesh().
static void get_face_uv_map_vert (UvVertMap * vmap, struct MPoly * mpoly, struct MLoop * ml, int fi, CCGVertHDL * fverts) [static]
Definition at line 241 of file subsurf_ccg.c.
References UvMapVert::f, get_uv_map_vert(), MPoly::loopstart, UvMapVert::next, SET_INT_IN_POINTER, UvMapVert::tfindex, and MPoly::totloop.
Referenced by ss_sync_from_uv().
static float* get_ss_weights (WeightTable * wtable, int gridCuts, int faceLen) [static]
Definition at line 463 of file subsurf_ccg.c.
References i, WeightTable::len, MEM_callocN(), MEM_freeN(), FaceVertWeightEntry::valid, FaceVertWeightEntry::w, and WeightTable::weight_table.
Referenced by getCCGDerivedMesh().
static CCGDerivedMesh * getCCGDerivedMesh (CCGSubSurf * ss, int drawInteriorEdges, int useSubsurfUv, DerivedMesh * dm) [static]
Definition at line 2917 of file subsurf_ccg.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, DerivedMesh::calcNormals, ccg_loops_to_corners(), ccgDM_calcNormals(), ccgDM_copyFinalEdgeArray(), ccgDM_copyFinalFaceArray(), ccgDM_copyFinalLoopArray(), ccgDM_copyFinalPolyArray(), ccgDM_copyFinalVertArray(), ccgDM_drawEdges(), ccgDM_drawFacesGLSL(), ccgDM_drawFacesSolid(), ccgDM_drawFacesTex(), ccgDM_drawLooseEdges(), ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_drawMappedFaces(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgDM_drawMappedFacesTex(), ccgDM_drawUVEdges(), ccgDM_drawVerts(), ccgDM_foreachMappedEdge(), ccgDM_foreachMappedFaceCenter(), ccgDM_foreachMappedVert(), ccgDM_get_edge_data(), ccgDM_get_edge_data_layer(), ccgDM_get_tessface_data(), ccgDM_get_tessface_data_layer(), ccgDM_get_vert_data(), ccgDM_get_vert_data_layer(), ccgDM_getEdgeMapIndex(), ccgDM_getFinalEdge(), ccgDM_getFinalFace(), ccgDM_getFinalVert(), ccgDM_getFinalVertCo(), ccgDM_getFinalVertNo(), ccgDM_getGridAdjacency(), ccgDM_getGridData(), ccgDM_getGridFlagMats(), ccgDM_getGridHidden(), ccgDM_getGridOffset(), ccgDM_getGridSize(), ccgDM_getMinMax(), ccgDM_getNumEdges(), ccgDM_getNumGrids(), ccgDM_getNumLoops(), ccgDM_getNumTessFaces(), ccgDM_getNumVerts(), ccgDM_getPBVH(), ccgDM_getPolyMap(), ccgdm_getVertCos(), ccgDM_getVertMapIndex(), ccgDM_recalcTessellation(), ccgDM_release(), ccgEdgeIterator_getCurrent(), ccgEdgeIterator_isStopped(), ccgEdgeIterator_next(), ccgFaceIterator_free(), ccgFaceIterator_getCurrent(), ccgFaceIterator_isStopped(), ccgFaceIterator_next(), ccgSubSurf_getEdgeEdgeHandle(), ccgSubSurf_getEdgeIterator(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getEdgeUserData(), ccgSubSurf_getEdgeVert0(), ccgSubSurf_getEdgeVert1(), ccgSubSurf_getFaceFaceHandle(), ccgSubSurf_getFaceIterator(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getFaceUserData(), ccgSubSurf_getFaceVert(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumEdges(), ccgSubSurf_getNumFaces(), ccgSubSurf_getNumFinalEdges(), ccgSubSurf_getNumFinalFaces(), ccgSubSurf_getNumFinalVerts(), ccgSubSurf_getNumVerts(), ccgSubSurf_getVertIterator(), ccgSubSurf_getVertUserData(), ccgSubSurf_getVertVertHandle(), ccgVertIterator_free(), ccgVertIterator_getCurrent(), ccgVertIterator_isStopped(), ccgVertIterator_next(), CD_CALLOC, CD_MCOL, CD_MLOOPCOL, CD_MLOOPUV, CD_MPOLY, CD_MTFACE, CD_NORMAL, CD_ORIGINDEX, CD_ORIGSPACE, CD_ORIGSPACE_MLOOP, CD_POLYINDEX, CD_PREVIEW_MCOL, CD_PREVIEW_MLOOPCOL, DerivedMesh::copyEdgeArray, DerivedMesh::copyLoopArray, DerivedMesh::copyPolyArray, DerivedMesh::copyTessFaceArray, DerivedMesh::copyVertArray, CustomData_add_layer(), CustomData_copy_data(), CustomData_free_layer_active(), CustomData_from_bmeshpoly(), CustomData_get_layer(), CustomData_has_layer(), CustomData_interp(), CustomData_number_of_layers(), DerivedMesh::dirty, CCGDerivedMesh::dm, DM_add_tessface_layer(), DM_copy_vert_data(), DM_DIRTY_TESS_CDLAYERS, DM_from_template(), DM_get_edge_data(), DM_get_poly_data_layer(), DM_get_tessface_data_layer(), DM_get_vert_data_layer(), DM_interp_vert_data(), DM_TYPE_CCGDM, DerivedMesh::drawEdges, DerivedMesh::drawFacesGLSL, DerivedMesh::drawFacesSolid, DerivedMesh::drawFacesTex, CCGDerivedMesh::drawInteriorEdges, DerivedMesh::drawLooseEdges, DerivedMesh::drawMappedEdges, DerivedMesh::drawMappedEdgesInterp, DerivedMesh::drawMappedFaces, DerivedMesh::drawMappedFacesGLSL, DerivedMesh::drawMappedFacesMat, DerivedMesh::drawMappedFacesTex, DerivedMesh::drawUVEdges, DerivedMesh::drawVerts, CCGDerivedMesh::edge, DerivedMesh::edgeData, CCGDerivedMesh::edgeFlags, CCGDerivedMesh::edgeMap, CCGDerivedMesh::face, DerivedMesh::faceData, CCGDerivedMesh::faceFlags, CCGDerivedMesh::faceMap, MEdge::flag, MPoly::flag, DMFlagMat::flag, DerivedMesh::foreachMappedEdge, DerivedMesh::foreachMappedFaceCenter, DerivedMesh::foreachMappedVert, free_ss_weights(), GET_INT_FROM_POINTER, get_ss_weights(), DerivedMesh::getEdge, DerivedMesh::getEdgeArray, DerivedMesh::getEdgeData, DerivedMesh::getEdgeDataArray, DerivedMesh::getGridAdjacency, DerivedMesh::getGridData, DerivedMesh::getGridFlagMats, DerivedMesh::getGridHidden, DerivedMesh::getGridOffset, DerivedMesh::getGridSize, DerivedMesh::getMinMax, DerivedMesh::getNumEdges, DerivedMesh::getNumGrids, DerivedMesh::getNumLoops, DerivedMesh::getNumPolys, DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, DerivedMesh::getPBVH, DerivedMesh::getPolyMap, DerivedMesh::getTessFace, DerivedMesh::getTessFaceData, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVert, DerivedMesh::getVertCo, DerivedMesh::getVertCos, DerivedMesh::getVertData, DerivedMesh::getVertDataArray, DerivedMesh::getVertNo, i, DerivedMesh::loopData, MPoly::mat_nr, DMFlagMat::mat_nr, MEM_callocN(), MEM_mallocN(), NULL, DerivedMesh::numEdgeData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, DerivedMesh::numVertData, ORIGINDEX_NONE, DerivedMesh::polyData, DerivedMesh::recalcTessellation, DerivedMesh::release, CCGDerivedMesh::reverseFaceMap, set_subsurf_uv(), CCGDerivedMesh::ss, CCGDerivedMesh::startEdge, CCGDerivedMesh::startFace, CCGDerivedMesh::startVert, PBVH::totvert, CCGDerivedMesh::useSubsurfUv, CCGDerivedMesh::vert, and CCGDerivedMesh::vertMap.
Referenced by subsurf_make_derived_from_derived().
static int getEdgeIndex (CCGSubSurf * ss, CCGEdge * e, int x, int edgeSize) [static]
Definition at line 176 of file subsurf_ccg.c.
References ccgSubSurf_getEdgeUserData(), ccgSubSurf_getEdgeVert0(), ccgSubSurf_getEdgeVert1(), and ccgSubSurf_getVertUserData().
Referenced by ccgDM_copyFinalEdgeArray(), and ccgDM_getFinalEdge().
static int getFaceIndex (CCGSubSurf * ss, CCGFace * f, int S, int x, int y, int edgeSize, int gridSize) [static]
Definition at line 195 of file subsurf_ccg.c.
References ccgSubSurf_getEdgeUserData(), ccgSubSurf_getEdgeVert0(), ccgSubSurf_getFaceEdge(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getFaceUserData(), ccgSubSurf_getFaceVert(), and ccgSubSurf_getVertUserData().
Referenced by ccgDM_copyFinalEdgeArray(), ccgDM_copyFinalFaceArray(), ccgDM_copyFinalLoopArray(), ccgDM_getFinalEdge(), ccgDM_getFinalFace(), and subsurf_copy_grid_hidden().
static void set_subsurf_uv (CCGSubSurf * ss, DerivedMesh * dm, DerivedMesh * result, int n) [static]
Definition at line 367 of file subsurf_ccg.c.
References _getSubSurf(), CCG_USE_ARENA, ccgFaceIterator_free(), ccgFaceIterator_getCurrent(), ccgFaceIterator_isStopped(), ccgFaceIterator_next(), ccgSubSurf_free(), ccgSubSurf_getFaceFaceHandle(), ccgSubSurf_getFaceGridDataArray(), ccgSubSurf_getFaceIterator(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumFaces(), ccgSubSurf_getSubdivisionLevels(), CD_MLOOPUV, CD_MTFACE, copy_v2_v2(), CustomData_get_layer_n(), DerivedMesh::faceData, faceMap, GET_INT_FROM_POINTER, DerivedMesh::loopData, MEM_freeN(), MEM_mallocN(), NULL, ss_sync_from_uv(), and MTFace::uv.
Referenced by getCCGDerivedMesh().
static void ss_sync_from_derivedmesh (CCGSubSurf * ss, DerivedMesh * dm, float(*) vertexCos[3], int useFlatSubdiv) [static]
Definition at line 527 of file subsurf_ccg.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, ccgSubSurf_getEdgeUserData(), ccgSubSurf_getFaceUserData(), ccgSubSurf_getSubdivisionLevels(), ccgSubSurf_getVertUserData(), ccgSubSurf_initFullSync(), ccgSubSurf_processSync(), ccgSubSurf_syncEdge(), ccgSubSurf_syncFace(), ccgSubSurf_syncVert(), CD_ORIGINDEX, MVert::co, MEdge::crease, DM_get_poly_data_layer(), eCCGError_InvalidValue, DerivedMesh::getEdgeArray, DerivedMesh::getEdgeDataArray, DerivedMesh::getLoopArray, DerivedMesh::getNumEdges, DerivedMesh::getNumVerts, DerivedMesh::getPolyArray, DerivedMesh::getVertArray, DerivedMesh::getVertDataArray, i, NULL, DerivedMesh::numPolyData, SET_INT_IN_POINTER, MEdge::v1, and MEdge::v2.
Referenced by subsurf_calculate_limit_positions(), and subsurf_make_derived_from_derived().
static int ss_sync_from_uv (CCGSubSurf * ss, CCGSubSurf * origss, DerivedMesh * dm, MLoopUV * mloopuv) [static]
Definition at line 258 of file subsurf_ccg.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BLI_edgehash_free(), BLI_edgehash_haskey(), BLI_edgehash_insert(), BLI_edgehash_new(), ccgSubSurf_getEdgeCrease(), ccgSubSurf_getFace(), ccgSubSurf_getFaceEdge(), ccgSubSurf_getSubdivisionLevels(), ccgSubSurf_initFullSync(), ccgSubSurf_processSync(), ccgSubSurf_syncEdge(), ccgSubSurf_syncFace(), ccgSubSurf_syncVert(), copy_v2_v2(), UvMapVert::f, MVert::flag, free_uv_vert_map(), get_face_uv_map_vert(), GET_INT_FROM_POINTER, get_uv_map_vert(), DerivedMesh::getLoopArray, DerivedMesh::getNumPolys, DerivedMesh::getNumVerts, DerivedMesh::getPolyArray, DerivedMesh::getVertArray, i, MPoly::loopstart, make_uv_vert_map(), ME_VERT_MERGED, UvMapVert::next, next, NULL, UvMapVert::separate, SET_INT_IN_POINTER, STD_UV_CONNECT_LIMIT, UvMapVert::tfindex, MPoly::totloop, and MLoop::v.
Referenced by set_subsurf_uv().
void subsurf_calculate_limit_positions (Mesh * me, float(*) positions_r[3])
Definition at line 3453 of file subsurf_ccg.c.
References _getSubSurf(), add_v3_v3(), add_v3_v3v3(), CCG_USE_ARENA, ccgSubSurf_free(), ccgSubSurf_getEdgeData(), ccgSubSurf_getFaceCenterData(), ccgSubSurf_getVertData(), ccgSubSurf_getVertEdge(), ccgSubSurf_getVertFace(), ccgSubSurf_getVertIterator(), ccgSubSurf_getVertNumEdges(), ccgSubSurf_getVertNumFaces(), ccgSubSurf_getVertVertHandle(), ccgVertIterator_free(), ccgVertIterator_getCurrent(), ccgVertIterator_isStopped(), ccgVertIterator_next(), CDDM_from_mesh(), co, GET_INT_FROM_POINTER, i, mul_v3_fl(), N, NULL, DerivedMesh::release, and ss_sync_from_derivedmesh().
Referenced by add_verts_to_dgroups().
void subsurf_copy_grid_hidden (DerivedMesh * dm, const MPoly * mpoly, MVert * mvert, const MDisps * mdisps)
Definition at line 979 of file subsurf_ccg.c.
References BLI_BITMAP_GET, ccg_factor(), ccg_gridsize(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumFaces(), ccgSubSurf_getSubdivisionLevels(), CCGDerivedMesh::face, CCGDerivedMesh::faceMap, getFaceIndex(), MDisps::hidden, i, MDisps::level, MPoly::loopstart, ME_HIDE, CCGDerivedMesh::ss, and MPoly::totloop.
struct DerivedMesh* subsurf_make_derived_from_derived (struct DerivedMesh * dm, struct SubsurfModifierData * smd, int useRenderParams, float(*) vertCos[3], int isFinalCalc, int forEditMode, int inEditMode) [read]
Definition at line 3363 of file subsurf_ccg.c.
References _getSubSurf(), CCG_CALC_NORMALS, CCG_USE_AGING, CCG_USE_ARENA, ccgSubSurf_free(), SubsurfModifierData::emCache, eSubsurfModifierFlag_ControlEdges, eSubsurfModifierFlag_DebugIncr, eSubsurfModifierFlag_Incremental, eSubsurfModifierFlag_SubsurfUv, SubsurfModifierData::flags, CCGDerivedMesh::freeSS, get_render_subsurf_level(), getCCGDerivedMesh(), SubsurfModifierData::levels, SubsurfModifierData::mCache, ME_SIMPLE_SUBSURF, SubsurfModifierData::modifier, NULL, Scene::r, SubsurfModifierData::renderLevels, ModifierData::scene, ss_sync_from_derivedmesh(), and SubsurfModifierData::subdivType.
Referenced by applyModifier(), applyModifierEM(), construct_param_handle_subsurfed(), init_heights_data(), shrinkwrapModifier_deform(), and subsurf_dm_create_local().
Variable Documentation
GLubyte stipple_quarttone[128]
Definition at line 83 of file glutil.c.