Blender: SCA_AlwaysSensor Class Reference
SCA_AlwaysSensor Class Reference
#include <SCA_AlwaysSensor.h>
Public Member Functions
SCA_AlwaysSensor (class SCA_EventManager *eventmgr, SCA_IObject *gameobj)
virtual ~SCA_AlwaysSensor ()
virtual CValue * GetReplica ()
virtual bool Evaluate ()
virtual bool IsPositiveTrigger ()
virtual void Init ()
Detailed Description
Definition at line 39 of file SCA_AlwaysSensor.h.
Constructor & Destructor Documentation
SCA_AlwaysSensor::SCA_AlwaysSensor (class SCA_EventManager * eventmgr, SCA_IObject * gameobj)
Definition at line 50 of file SCA_AlwaysSensor.cpp.
References Init().
Referenced by GetReplica().
SCA_AlwaysSensor::~SCA_AlwaysSensor () [virtual]
Definition at line 63 of file SCA_AlwaysSensor.cpp.
Member Function Documentation
bool SCA_AlwaysSensor::Evaluate () [virtual]
Implements SCA_ISensor.
Definition at line 88 of file SCA_AlwaysSensor.cpp.
CValue * SCA_AlwaysSensor::GetReplica (void) [virtual]
Implements SCA_ISensor.
Definition at line 70 of file SCA_AlwaysSensor.cpp.
References CValue::ProcessReplica(), and SCA_AlwaysSensor().
void SCA_AlwaysSensor::Init (void) [virtual]
Reimplemented from SCA_ISensor.
Definition at line 58 of file SCA_AlwaysSensor.cpp.
Referenced by SCA_AlwaysSensor().
bool SCA_AlwaysSensor::IsPositiveTrigger () [virtual]
Reimplemented from SCA_ISensor.
Definition at line 81 of file SCA_AlwaysSensor.cpp.
References SCA_ISensor::m_invert.
The documentation for this class was generated from the following files:
SCA_AlwaysSensor.h
SCA_AlwaysSensor.cpp