Blender: TNT::Fortran_Array1D< T > Class Template Reference
TNT::Fortran_Array1D< T > Class Template Reference
#include <tnt_fortran_array1d.h>
Public Types
typedef T value_type
Public Member Functions
Fortran_Array1D ()
Fortran_Array1D (int n)
Fortran_Array1D (int n, const T &a)
Fortran_Array1D (int n, T *a)
Fortran_Array1D (const Fortran_Array1D &A)
Fortran_Array1D & operator= (const T &a)
Fortran_Array1D & operator= (const Fortran_Array1D &A)
Fortran_Array1D & ref (const Fortran_Array1D &A)
Fortran_Array1D copy () const
Fortran_Array1D & inject (const Fortran_Array1D &A)
T & operator() (int i)
const T & operator() (int i) const
int dim1 () const
int dim () const
~Fortran_Array1D ()
int ref_count () const
Fortran_Array1D< T > subarray (int i0, int i1)
Detailed Description
template<class T>
class TNT::Fortran_Array1D< T >
Definition at line 42 of file tnt_fortran_array1d.h.
Member Typedef Documentation
template<class T> typedef T TNT::Fortran_Array1D< T >::value_type
Definition at line 61 of file tnt_fortran_array1d.h.
Constructor & Destructor Documentation
template<class T > TNT::Fortran_Array1D< T >::Fortran_Array1D ()
Definition at line 92 of file tnt_fortran_array1d.h.
template<class T > TNT::Fortran_Array1D< T >::Fortran_Array1D (int n) [explicit]
Definition at line 106 of file tnt_fortran_array1d.h.
template<class T > TNT::Fortran_Array1D< T >::Fortran_Array1D (int n, const T & a)
Definition at line 114 of file tnt_fortran_array1d.h.
template<class T > TNT::Fortran_Array1D< T >::Fortran_Array1D (int n, T * a)
Definition at line 124 of file tnt_fortran_array1d.h.
template<class T > TNT::Fortran_Array1D< T >::Fortran_Array1D (const Fortran_Array1D< T > & A) [inline]
Definition at line 95 of file tnt_fortran_array1d.h.
template<class T > TNT::Fortran_Array1D< T >::~Fortran_Array1D ()
Definition at line 210 of file tnt_fortran_array1d.h.
Member Function Documentation
template<class T > Fortran_Array1D< T > TNT::Fortran_Array1D< T >::copy () const
Definition at line 162 of file tnt_fortran_array1d.h.
References A.
template<class T > int TNT::Fortran_Array1D< T >::dim () const [inline]
Definition at line 207 of file tnt_fortran_array1d.h.
template<class T > int TNT::Fortran_Array1D< T >::dim1 () const [inline]
Definition at line 204 of file tnt_fortran_array1d.h.
Referenced by TNT::operator*(), TNT::operator*=(), TNT::operator+(), TNT::operator+=(), TNT::operator-(), TNT::operator-=(), TNT::operator/(), and TNT::operator/=().
template<class T > Fortran_Array1D< T > & TNT::Fortran_Array1D< T >::inject (const Fortran_Array1D< T > & A)
Definition at line 172 of file tnt_fortran_array1d.h.
template<class T > T & TNT::Fortran_Array1D< T >::operator() (int i) [inline]
Definition at line 132 of file tnt_fortran_array1d.h.
References assert.
template<class T > const T & TNT::Fortran_Array1D< T >::operator() (int i) const [inline]
Definition at line 142 of file tnt_fortran_array1d.h.
References assert.
template<class T > Fortran_Array1D< T > & TNT::Fortran_Array1D< T >::operator= (const Fortran_Array1D< T > & A) [inline]
Definition at line 198 of file tnt_fortran_array1d.h.
template<class T > Fortran_Array1D< T > & TNT::Fortran_Array1D< T >::operator= (const T & a) [inline]
Definition at line 155 of file tnt_fortran_array1d.h.
template<class T > Fortran_Array1D< T > & TNT::Fortran_Array1D< T >::ref (const Fortran_Array1D< T > & A) [inline]
Definition at line 185 of file tnt_fortran_array1d.h.
template<class T > int TNT::Fortran_Array1D< T >::ref_count () const [inline]
Definition at line 216 of file tnt_fortran_array1d.h.
template<class T > Fortran_Array1D< T > TNT::Fortran_Array1D< T >::subarray (int i0, int i1) [inline]
Definition at line 222 of file tnt_fortran_array1d.h.
References X.
The documentation for this class was generated from the following file:
tnt_fortran_array1d.h