Blender: texture_image< T > Struct Template Reference
texture_image< T > Struct Template Reference
#include <kernel_compat_cpu.h>
Public Member Functions
float4 read (float4 r)
float4 read (uchar4 r)
int wrap_periodic (int x, int width)
int wrap_clamp (int x, int width)
float frac (float x, int *ix)
float4 interp (float x, float y, bool periodic=true)
Public Attributes
T * data
int width
int height
Detailed Description
template<typename T>
struct texture_image< T >
Definition at line 75 of file kernel_compat_cpu.h.
Member Function Documentation
template<typename T > float texture_image< T >::frac (float x, int * ix) [inline]
Definition at line 100 of file kernel_compat_cpu.h.
References i.
Referenced by texture_image< T >::interp().
template<typename T > float4 texture_image< T >::interp (float x, float y, bool periodic = true) [inline]
Definition at line 107 of file kernel_compat_cpu.h.
References texture_image< T >::data, texture_image< T >::frac(), texture_image< T >::height, make_float4(), texture_image< T >::read(), texture_image< T >::width, texture_image< T >::wrap_clamp(), and texture_image< T >::wrap_periodic().
template<typename T > float4 texture_image< T >::read (uchar4 r) [inline]
Definition at line 81 of file kernel_compat_cpu.h.
References make_float4(), uchar4::w, uchar4::x, uchar4::y, and uchar4::z.
template<typename T > float4 texture_image< T >::read (float4 r) [inline]
Definition at line 76 of file kernel_compat_cpu.h.
Referenced by texture_image< T >::interp().
template<typename T > int texture_image< T >::wrap_clamp (int x, int width) [inline]
Definition at line 95 of file kernel_compat_cpu.h.
References clamp.
Referenced by texture_image< T >::interp().
template<typename T > int texture_image< T >::wrap_periodic (int x, int width) [inline]
Definition at line 87 of file kernel_compat_cpu.h.
References texture_image< T >::width.
Referenced by texture_image< T >::interp().
Member Data Documentation
template<typename T > T* texture_image< T >::data
Definition at line 139 of file kernel_compat_cpu.h.
Referenced by texture_image< T >::interp(), and kernel_tex_copy().
template<typename T > int texture_image< T >::height
Definition at line 140 of file kernel_compat_cpu.h.
Referenced by texture_image< T >::interp(), and kernel_tex_copy().
template<typename T > int texture_image< T >::width
Definition at line 140 of file kernel_compat_cpu.h.
Referenced by texture_image< T >::interp(), kernel_tex_copy(), and texture_image< T >::wrap_periodic().
The documentation for this struct was generated from the following file:
kernel_compat_cpu.h