Blender: space_info.c File Reference
space_info.c File Reference
info space
#include <string.h>
#include <stdio.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BLF_translation.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_screen.h"
#include "ED_space_api.h"
#include "ED_screen.h"
#include "BIF_gl.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_resources.h"
#include "UI_interface.h"
#include "UI_view2d.h"
#include "info_intern.h"
Functions
static SpaceLink * info_new (const bContext *UNUSED(C))
static void info_free (SpaceLink *UNUSED(sl))
static void info_init (struct wmWindowManager *UNUSED(wm), ScrArea *UNUSED(sa))
static SpaceLink * info_duplicate (SpaceLink *sl)
static void info_main_area_init (wmWindowManager *wm, ARegion *ar)
static void info_textview_update_rect (const bContext *C, ARegion *ar)
static void info_main_area_draw (const bContext *C, ARegion *ar)
static void info_operatortypes (void)
static void info_keymap (struct wmKeyConfig *keyconf)
static void info_header_area_init (wmWindowManager *UNUSED(wm), ARegion *ar)
static void info_header_area_draw (const bContext *C, ARegion *ar)
static void info_main_area_listener (ARegion *ar, wmNotifier *wmn)
static void info_header_listener (ARegion *ar, wmNotifier *wmn)
static void recent_files_menu_draw (const bContext *UNUSED(C), Menu *menu)
static void recent_files_menu_register (void)
void ED_spacetype_info (void)
Detailed Description
Definition in file space_info.c.
Function Documentation
void ED_spacetype_info (void)
Definition at line 298 of file space_info.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, info_duplicate(), info_free(), info_header_area_draw(), info_header_area_init(), info_header_listener(), info_init(), info_keymap(), info_main_area_draw(), info_main_area_init(), info_main_area_listener(), info_new(), info_operatortypes(), ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizey, recent_files_menu_register(), ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_INFO, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
static SpaceLink* info_duplicate (SpaceLink * sl) [static]
Definition at line 115 of file space_info.c.
References MEM_dupallocN().
Referenced by ED_spacetype_info().
static void info_free (SpaceLink * UNUSEDsl) [static]
Definition at line 102 of file space_info.c.
Referenced by ED_spacetype_info().
static void info_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 224 of file space_info.c.
References ED_region_header().
Referenced by ED_spacetype_info().
static void info_header_area_init (wmWindowManager * UNUSEDwm, ARegion * ar) [static]
Definition at line 219 of file space_info.c.
References ED_region_header_init().
Referenced by ED_spacetype_info().
static void info_header_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 244 of file space_info.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), ELEM, NA_RENAME, NC_ID, NC_SCENE, NC_SCREEN, NC_SPACE, NC_WM, ND_ANIMPLAY, ND_JOB, ND_RENDER_RESULT, ND_SCREENCAST, and ND_SPACE_INFO.
Referenced by ED_spacetype_info().
static void info_init (struct wmWindowManager * UNUSEDwm, ScrArea * UNUSEDsa) [static]
Definition at line 110 of file space_info.c.
Referenced by ED_spacetype_info().
static void info_keymap (struct wmKeyConfig * keyconf) [static]
Definition at line 197 of file space_info.c.
References AKEY, BKEY, CKEY, DELKEY, KM_ANY, KM_CTRL, KM_PRESS, RKEY, SELECTMOUSE, SPACE_INFO, TIMERREPORT, WM_keymap_add_item(), WM_keymap_find(), WM_keymap_verify_item(), and XKEY.
Referenced by ED_spacetype_info().
static void info_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 146 of file space_info.c.
References CTX_wm_reports(), CTX_wm_space_info(), info_textview_main(), info_textview_update_rect(), TH_BACK, UI_ThemeClearColor(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_view_ortho(), UI_view2d_view_restore(), ARegion::v2d, V2D_ARG_DUMMY, V2D_GRID_CLAMP, and ARegion::winy.
Referenced by ED_spacetype_info().
static void info_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 127 of file space_info.c.
References wmWindowManager::defaultconf, ARegion::handlers, SPACE_INFO, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_CUSTOM, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler(), and WM_keymap_find().
Referenced by ED_spacetype_info().
static void info_main_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 229 of file space_info.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NC_SPACE, and ND_SPACE_INFO_REPORT.
Referenced by ED_spacetype_info().
static SpaceLink* info_new (const bContext * UNUSEDC) [static]
Definition at line 64 of file space_info.c.
References View2D::align, ARegion::alignment, BLI_addtail(), INFO_RPT_OP, View2D::keepofs, View2D::keeptot, View2D::keepzoom, View2D::maxzoom, MEM_callocN(), View2D::minzoom, SpaceInfo::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SpaceInfo::rpt_mask, View2D::scroll, SPACE_INFO, SpaceInfo::spacetype, ARegion::v2d, V2D_ALIGN_NO_NEG_X, V2D_ALIGN_NO_NEG_Y, V2D_KEEPASPECT, V2D_KEEPTOT_BOUNDS, V2D_LIMITZOOM, V2D_LOCKOFS_X, V2D_LOCKZOOM_X, V2D_LOCKZOOM_Y, and V2D_SCROLL_RIGHT.
Referenced by ED_spacetype_info().
static void info_operatortypes (void) [static]
Definition at line 177 of file space_info.c.
References FILE_OT_find_missing_files(), FILE_OT_make_paths_absolute(), FILE_OT_make_paths_relative(), FILE_OT_pack_all(), FILE_OT_report_missing_files(), FILE_OT_unpack_all(), INFO_OT_report_copy(), INFO_OT_report_delete(), INFO_OT_report_replay(), INFO_OT_reports_display_update(), INFO_OT_select_all_toggle(), INFO_OT_select_border(), INFO_OT_select_pick(), and WM_operatortype_append().
Referenced by ED_spacetype_info().
static void info_textview_update_rect (const bContext * C, ARegion * ar) [static]
Definition at line 138 of file space_info.c.
References CTX_wm_reports(), CTX_wm_space_info(), info_textview_height(), UI_view2d_totRect_set(), ARegion::v2d, and ARegion::winx.
Referenced by info_main_area_draw().
static void recent_files_menu_draw (const bContext * UNUSEDC, Menu * menu) [static]
Definition at line 271 of file space_info.c.
References BLI_path_basename(), RecentFile::filepath, G, IFACE_, Menu::layout, RecentFile::next, uiItemL(), uiItemStringO(), uiLayoutSetOperatorContext(), and WM_OP_EXEC_REGION_WIN.
Referenced by recent_files_menu_register().
static void recent_files_menu_register (void) [static]
Definition at line 286 of file space_info.c.
References MenuType::draw, MenuType::idname, MenuType::label, MEM_callocN(), mt, N_, recent_files_menu_draw(), and WM_menutype_add().
Referenced by ED_spacetype_info().