Blender: SG_ParentRelation Class Reference
SG_ParentRelation Class Reference
#include <SG_ParentRelation.h>
Public Member Functions
virtual bool UpdateChildCoordinates (SG_Spatial *child, const SG_Spatial *parent, bool &parentUpdated)=0
virtual ~SG_ParentRelation ()
virtual SG_ParentRelation * NewCopy ()=0
virtual bool IsVertexRelation ()
virtual bool IsSlowRelation ()
Protected Member Functions
SG_ParentRelation ()
SG_ParentRelation (const SG_ParentRelation &)
Detailed Description
Definition at line 57 of file SG_ParentRelation.h.
Constructor & Destructor Documentation
virtual SG_ParentRelation::~SG_ParentRelation () [inline, virtual]
Definition at line 78 of file SG_ParentRelation.h.
SG_ParentRelation::SG_ParentRelation () [inline, protected]
Protected constructors this class is not meant to be instantiated.
Definition at line 121 of file SG_ParentRelation.h.
SG_ParentRelation::SG_ParentRelation (const SG_ParentRelation &) [protected]
Copy construction should not be implemented
Member Function Documentation
virtual bool SG_ParentRelation::IsSlowRelation () [inline, virtual]
Need this to see if we are able to adjust time-offset from the python api
Reimplemented in KX_SlowParentRelation.
Definition at line 110 of file SG_ParentRelation.h.
Referenced by SG_Node::IsSlowParent().
virtual bool SG_ParentRelation::IsVertexRelation () [inline, virtual]
Vertex Parent Relation are special: they don't propagate rotation
Reimplemented in KX_VertexParentRelation.
Definition at line 100 of file SG_ParentRelation.h.
Referenced by SG_Node::IsVertexParent().
virtual SG_ParentRelation* SG_ParentRelation::NewCopy () [pure virtual]
You must provide a way of duplicating an instance of an SG_ParentRelation. This should return a pointer to a new duplicate allocated on the heap. Responsibilty for deleting the duplicate resides with the caller of this method.
Implemented in KX_BoneParentRelation, KX_NormalParentRelation, KX_VertexParentRelation, and KX_SlowParentRelation.
Referenced by SG_Spatial::SG_Spatial().
virtual bool SG_ParentRelation::UpdateChildCoordinates (SG_Spatial * child, const SG_Spatial * parent, bool & parentUpdated) [pure virtual]
Update the childs local and global coordinates based upon the parents global coordinates. You must also handle the case when this node has no parent (parent == NULL). Usually you should just copy the local coordinates of the child to the world coordinates.
Implemented in KX_BoneParentRelation, KX_NormalParentRelation, KX_VertexParentRelation, and KX_SlowParentRelation.
Referenced by SG_Spatial::ComputeWorldTransforms().
The documentation for this class was generated from the following file:
SG_ParentRelation.h