Blender: info_report.c File Reference
info_report.c File Reference
info space
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_dynstr.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_screen.h"
#include "ED_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "info_intern.h"
Functions
int info_report_mask (SpaceInfo *UNUSED(sinfo))
static int report_replay_exec (bContext *C, wmOperator *UNUSED(op))
void INFO_OT_report_replay (wmOperatorType *ot)
static int select_report_pick_exec (bContext *C, wmOperator *op)
static int select_report_pick_invoke (bContext *C, wmOperator *op, wmEvent *event)
void INFO_OT_select_pick (wmOperatorType *ot)
static int report_select_all_toggle_exec (bContext *C, wmOperator *UNUSED(op))
void INFO_OT_select_all_toggle (wmOperatorType *ot)
static int borderselect_exec (bContext *C, wmOperator *op)
void INFO_OT_select_border (wmOperatorType *ot)
static int report_delete_exec (bContext *C, wmOperator *UNUSED(op))
void INFO_OT_report_delete (wmOperatorType *ot)
static int report_copy_exec (bContext *C, wmOperator *UNUSED(op))
void INFO_OT_report_copy (wmOperatorType *ot)
Detailed Description
Definition in file info_report.c.
Function Documentation
static int borderselect_exec (bContext * C, wmOperator * op) [static]
Definition at line 217 of file info_report.c.
References CTX_wm_area(), CTX_wm_region(), CTX_wm_reports(), CTX_wm_space_info(), ED_area_tag_redraw(), ListBase::first, Report::flag, GESTURE_MODAL_SELECT, info_report_mask(), info_text_pick(), ListBase::last, ReportList::list, Report::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Report::prev, wmOperator::ptr, RNA_boolean_get(), RNA_int_get(), SELECT, Report::type, UI_view2d_region_to_view(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by INFO_OT_select_border().
void INFO_OT_report_copy (wmOperatorType * ot)
Definition at line 399 of file info_report.c.
References wmOperatorType::description, ED_operator_info_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and report_copy_exec().
Referenced by info_operatortypes().
void INFO_OT_report_delete (wmOperatorType * ot)
Definition at line 354 of file info_report.c.
References wmOperatorType::description, ED_operator_info_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and report_delete_exec().
Referenced by info_operatortypes().
void INFO_OT_report_replay (wmOperatorType * ot)
Definition at line 95 of file info_report.c.
References wmOperatorType::description, ED_operator_info_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and report_replay_exec().
Referenced by info_operatortypes().
void INFO_OT_select_all_toggle (wmOperatorType * ot)
Definition at line 199 of file info_report.c.
References wmOperatorType::description, ED_operator_info_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and report_select_all_toggle_exec().
Referenced by info_operatortypes().
void INFO_OT_select_border (wmOperatorType * ot)
Definition at line 303 of file info_report.c.
References borderselect_exec(), wmOperatorType::cancel, wmOperatorType::description, ED_operator_info_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, wmOperatorType::poll, TRUE, WM_border_select_cancel(), WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by info_operatortypes().
void INFO_OT_select_pick (wmOperatorType * ot)
Definition at line 145 of file info_report.c.
References wmOperatorType::description, ED_operator_info_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), select_report_pick_exec(), select_report_pick_invoke(), and wmOperatorType::srna.
Referenced by info_operatortypes().
int info_report_mask (SpaceInfo * UNUSEDsinfo)
Definition at line 51 of file info_report.c.
References INFO_RPT_DEBUG, INFO_RPT_ERR, INFO_RPT_INFO, INFO_RPT_OP, INFO_RPT_WARN, RPT_DEBUG_ALL, RPT_ERROR_ALL, RPT_INFO_ALL, RPT_OPERATOR_ALL, and RPT_WARNING_ALL.
static int report_copy_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 372 of file info_report.c.
References BLI_dynstr_append(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), CTX_wm_reports(), CTX_wm_space_info(), ListBase::first, Report::flag, info_report_mask(), ReportList::list, MEM_freeN(), Report::message, Report::next, OPERATOR_FINISHED, SELECT, Report::type, and WM_clipboard_text_set().
Referenced by INFO_OT_report_copy().
static int report_delete_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 327 of file info_report.c.
References BLI_remlink(), CTX_wm_area(), CTX_wm_reports(), CTX_wm_space_info(), ED_area_tag_redraw(), ListBase::first, Report::flag, info_report_mask(), ReportList::list, MEM_freeN(), Report::message, Report::next, OPERATOR_FINISHED, SELECT, and Report::type.
Referenced by INFO_OT_report_delete().
static int report_replay_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 69 of file info_report.c.
References console_history_add_str(), CTX_wm_area(), ED_area_tag_redraw(), NULL, OPERATOR_FINISHED, RPT_OPERATOR_ALL, SELECT, WM_OP_EXEC_DEFAULT, and WM_operator_name_call().
Referenced by INFO_OT_report_replay().
static int report_select_all_toggle_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 166 of file info_report.c.
References CTX_wm_area(), CTX_wm_reports(), CTX_wm_space_info(), ED_area_tag_redraw(), Report::flag, info_report_mask(), ListBase::last, ReportList::list, OPERATOR_FINISHED, Report::prev, SELECT, and Report::type.
Referenced by INFO_OT_select_all_toggle().
static int select_report_pick_exec (bContext * C, wmOperator * op) [static]
Definition at line 112 of file info_report.c.
References BLI_findlink(), CTX_wm_area(), CTX_wm_reports(), ED_area_tag_redraw(), Report::flag, ReportList::list, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_int_get(), and SELECT.
Referenced by INFO_OT_select_pick(), and select_report_pick_invoke().
static int select_report_pick_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 127 of file info_report.c.
References BLI_findindex(), CTX_wm_region(), CTX_wm_reports(), CTX_wm_space_info(), CTX_wm_window(), info_text_pick(), ReportList::list, wmEvent::mval, wmOperator::ptr, RNA_int_set(), select_report_pick_exec(), ARegion::swinid, and wmSubWindowSet().
Referenced by INFO_OT_select_pick().