Blender: CVectorValue Class Reference
CVectorValue Class Reference
#include <VectorValue.h>
Public Member Functions
virtual void SetValue (CValue *newval)
void SetVector (double newvec[])
void Configure (CValue *menuvalue)
virtual double * GetVector3 (bool bGetTransformedVec=false)
virtual double GetNumber ()
CValue * Calc (VALUE_OPERATOR op, CValue *val)
CValue * CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue *val)
CVectorValue (double vec[], const char *name, AllocationTYPE alloctype=CValue::HEAPVALUE)
CVectorValue ()
CVectorValue (double vec[], AllocationTYPE alloctype=CValue::HEAPVALUE)
CVectorValue (float x, float y, float z, AllocationTYPE alloctype=CValue::HEAPVALUE)
virtual ~CVectorValue ()
void AddConfigurationData (CValue *menuvalue)
virtual CValue * GetReplica ()
virtual const STR_String & GetText ()
Protected Attributes
double m_vec [3]
double m_transformedvec [3]
Detailed Description
Definition at line 29 of file VectorValue.h.
Constructor & Destructor Documentation
CVectorValue::CVectorValue (double vec[], const char * name, AllocationTYPE alloctype = CValue::HEAPVALUE)
Definition at line 50 of file VectorValue.cpp.
References CValue::DisableRefCount(), KX_X, KX_Y, KX_Z, m_transformedvec, m_vec, CValue::SetCustomFlag1(), CPropValue::SetName(), and CValue::STACKVALUE.
CVectorValue::CVectorValue () [inline]
Definition at line 49 of file VectorValue.h.
Referenced by CalcFinal(), and GetReplica().
CVectorValue::CVectorValue (double vec[], AllocationTYPE alloctype = CValue::HEAPVALUE)
Definition at line 68 of file VectorValue.cpp.
References CValue::DisableRefCount(), KX_X, KX_Y, KX_Z, m_transformedvec, m_vec, CValue::SetCustomFlag1(), and CValue::STACKVALUE.
CVectorValue::CVectorValue (float x, float y, float z, AllocationTYPE alloctype = CValue::HEAPVALUE)
Definition at line 36 of file VectorValue.cpp.
References CValue::DisableRefCount(), KX_X, KX_Y, KX_Z, m_transformedvec, m_vec, CValue::SetCustomFlag1(), and CValue::STACKVALUE.
CVectorValue::~CVectorValue () [virtual]
Definition at line 85 of file VectorValue.cpp.
Member Function Documentation
void CVectorValue::AddConfigurationData (CValue * menuvalue)
CValue* CVectorValue::Calc (VALUE_OPERATOR op, CValue * val) [inline, virtual]
Implements CValue.
Definition at line 41 of file VectorValue.h.
References CValue::CalcFinal(), and VALUE_VECTOR_TYPE.
CValue * CVectorValue::CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue * val) [virtual]
pre: the type of val is dtype ret: a new object containing the result of applying operator op to val and this object
Implements CValue.
Definition at line 95 of file VectorValue.cpp.
References CVectorValue(), CPropValue::GetName(), GetText(), CValue::GetText(), GetVector3(), CValue::GetVector3(), CValue::HEAPVALUE, KX_X, KX_Y, KX_Z, NULL, CValue::op2str(), CValue::SetName(), VALUE_ADD_OPERATOR, VALUE_EMPTY_TYPE, VALUE_FLOAT_TYPE, VALUE_MUL_OPERATOR, and VALUE_VECTOR_TYPE.
void CVectorValue::Configure (CValue * menuvalue)
double CVectorValue::GetNumber () [virtual]
Implements CValue.
Definition at line 160 of file VectorValue.cpp.
References KX_X, and m_vec.
CValue * CVectorValue::GetReplica (void) [virtual]
Implements CValue.
Definition at line 206 of file VectorValue.cpp.
References CVectorValue(), and CValue::ProcessReplica().
const STR_String & CVectorValue::GetText () [virtual]
Implements CValue.
Definition at line 200 of file VectorValue.cpp.
References assertd, and gstrVectorStr.
Referenced by CalcFinal().
double * CVectorValue::GetVector3 (bool bGetTransformedVec = false) [virtual]
Reimplemented from CValue.
Definition at line 166 of file VectorValue.cpp.
References m_transformedvec, and m_vec.
Referenced by CalcFinal().
void CVectorValue::SetValue (CValue * newval) [virtual]
Sets the value to this cvalue.
Attention:
this particular function should never be called. Why not abstract?
Reimplemented from CValue.
Definition at line 188 of file VectorValue.cpp.
References KX_X, KX_Y, KX_Z, m_transformedvec, m_vec, and CValue::SetModified().
void CVectorValue::SetVector (double newvec[])
Definition at line 178 of file VectorValue.cpp.
References KX_X, KX_Y, KX_Z, m_transformedvec, m_vec, and CValue::SetModified().
Member Data Documentation
double CVectorValue::m_transformedvec[3] [protected]
Definition at line 85 of file VectorValue.h.
Referenced by CVectorValue(), GetVector3(), SetValue(), and SetVector().
double CVectorValue::m_vec[3] [protected]
Definition at line 84 of file VectorValue.h.
Referenced by CVectorValue(), GetNumber(), GetVector3(), SetValue(), and SetVector().
The documentation for this class was generated from the following files:
VectorValue.h
VectorValue.cpp