Blender: node_composite_huecorrect.c File Reference
node_composite_huecorrect.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_huecorrect (bNode *node, float *out, float *in)
static void do_huecorrect_fac (bNode *node, float *out, float *in, float *fac)
static void node_composit_exec_huecorrect (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_huecorrect (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_huecorrect (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_huecorrect_in []
static bNodeSocketTemplate cmp_node_huecorrect_out []
Detailed Description
Definition in file node_composite_huecorrect.c.
Function Documentation
static void do_huecorrect (bNode * node, float * out, float * in) [static]
Definition at line 46 of file node_composite_huecorrect.c.
References CLAMP(), curvemapping_evaluateF(), floorf, hsv_to_rgb(), rgb_to_hsv(), and bNode::storage.
Referenced by node_composit_exec_huecorrect().
static void do_huecorrect_fac (bNode * node, float * out, float * in, float * fac) [static]
Definition at line 73 of file node_composite_huecorrect.c.
References CLAMP(), curvemapping_evaluateF(), floorf, hsv_to_rgb(), rgb_to_hsv(), and bNode::storage.
Referenced by node_composit_exec_huecorrect().
static void node_composit_exec_huecorrect (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 104 of file node_composite_huecorrect.c.
References alloc_compbuf(), CB_RGBA, CB_VAL, composit1_pixel_processor(), composit2_pixel_processor(), data, bNodeStack::data, do_huecorrect(), do_huecorrect_fac(), NULL, pass_on_compbuf(), CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_huecorrect().
static void node_composit_init_huecorrect (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 138 of file node_composite_huecorrect.c.
References CurveMapping::clipr, CurveMapping::cm, CurveMapping::cur, CURVE_PRESET_MID9, curvemap_reset(), CURVEMAP_SLOPE_POSITIVE, curvemapping_add(), CurveMapping::preset, and bNode::storage.
Referenced by register_node_type_cmp_huecorrect().
void register_node_type_cmp_huecorrect (bNodeTreeType * ttype)
Definition at line 154 of file node_composite_huecorrect.c.
References CMP_NODE_HUECORRECT, NODE_CLASS_OP_COLOR, node_composit_exec_huecorrect(), node_composit_init_huecorrect(), node_copy_curves(), node_free_curves(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_huecorrect_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Fac",   1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_FACTOR},
    {   SOCK_RGBA, 1, "Image",  1.0f, 1.0f, 1.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 35 of file node_composite_huecorrect.c.
bNodeSocketTemplate cmp_node_huecorrect_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 41 of file node_composite_huecorrect.c.