Blender: wm_event_system.c File Reference
wm_event_system.c File Reference
windowmanager
#include <stdlib.h>
#include <string.h>
#include "DNA_listBase.h"
#include "DNA_screen_types.h"
#include "DNA_scene_types.h"
#include "DNA_windowmanager_types.h"
#include "DNA_userdef_types.h"
#include "MEM_guardedalloc.h"
#include "GHOST_C-api.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "BKE_blender.h"
#include "BKE_context.h"
#include "BKE_idprop.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "BKE_screen.h"
#include "BKE_sound.h"
#include "ED_fileselect.h"
#include "ED_info.h"
#include "ED_render.h"
#include "ED_screen.h"
#include "ED_view3d.h"
#include "ED_util.h"
#include "RNA_access.h"
#include "UI_interface.h"
#include "PIL_time.h"
#include "WM_api.h"
#include "WM_types.h"
#include "wm.h"
#include "wm_window.h"
#include "wm_event_system.h"
#include "wm_event_types.h"
#include "wm_draw.h"
#include "RNA_enum_types.h"
Functions
static int wm_operator_call_internal (bContext *C, wmOperatorType *ot, PointerRNA *properties, ReportList *reports, short context, short poll_only)
void wm_event_add (wmWindow *win, wmEvent *event_to_add)
void wm_event_free (wmEvent *event)
void wm_event_free_all (wmWindow *win)
static int wm_test_duplicate_notifier (wmWindowManager *wm, unsigned int type, void *reference)
void WM_event_add_notifier (const bContext *C, unsigned int type, void *reference)
void WM_main_add_notifier (unsigned int type, void *reference)
static wmNotifier * wm_notifier_next (wmWindowManager *wm)
void wm_event_do_notifiers (bContext *C)
static int wm_event_always_pass (wmEvent *event)
static int wm_handler_ui_call (bContext *C, wmEventHandler *handler, wmEvent *event, int always_pass)
static void wm_handler_ui_cancel (bContext *C)
int WM_operator_poll (bContext *C, wmOperatorType *ot)
int WM_operator_poll_context (bContext *C, wmOperatorType *ot, int context)
static void wm_operator_print (bContext *C, wmOperator *op)
void WM_event_print (wmEvent *event)
static void wm_operator_reports (bContext *C, wmOperator *op, int retval, int caller_owns_reports)
static int wm_operator_register_check (wmWindowManager *wm, wmOperatorType *ot)
static void wm_operator_finished (bContext *C, wmOperator *op, int repeat)
static int wm_operator_exec (bContext *C, wmOperator *op, int repeat)
static int wm_operator_exec_notest (bContext *C, wmOperator *op)
int WM_operator_call (bContext *C, wmOperator *op)
int WM_operator_call_notest (bContext *C, wmOperator *op)
int WM_operator_repeat (bContext *C, wmOperator *op)
int WM_operator_repeat_check (const bContext *UNUSED(C), wmOperator *op)
static wmOperator * wm_operator_create (wmWindowManager *wm, wmOperatorType *ot, PointerRNA *properties, ReportList *reports)
static void wm_region_mouse_co (bContext *C, wmEvent *event)
int WM_operator_last_properties_init (wmOperator *UNUSED(op))
int WM_operator_last_properties_store (wmOperator *UNUSED(op))
static int wm_operator_invoke (bContext *C, wmOperatorType *ot, wmEvent *event, PointerRNA *properties, ReportList *reports, short poll_only)
int WM_operator_name_call (bContext *C, const char *opstring, int context, PointerRNA *properties)
int WM_operator_call_py (bContext *C, wmOperatorType *ot, int context, PointerRNA *properties, ReportList *reports)
void wm_event_free_handler (wmEventHandler *handler)
static void wm_handler_op_context (bContext *C, wmEventHandler *handler)
void WM_event_remove_handlers (bContext *C, ListBase *handlers)
int WM_userdef_event_map (int kmitype)
static void wm_eventemulation (wmEvent *event)
static int wm_eventmatch (wmEvent *winevent, wmKeyMapItem *kmi)
static void wm_event_modalkeymap (const bContext *C, wmOperator *op, wmEvent *event)
static int wm_handler_operator_call (bContext *C, ListBase *handlers, wmEventHandler *handler, wmEvent *event, PointerRNA *properties)
static int wm_handler_fileselect_call (bContext *C, ListBase *handlers, wmEventHandler *handler, wmEvent *event)
static int handler_boundbox_test (wmEventHandler *handler, wmEvent *event)
static int wm_action_not_handled (int action)
static int wm_handlers_do (bContext *C, wmEvent *event, ListBase *handlers)
static int wm_event_inside_i (wmEvent *event, rcti *rect)
static ScrArea * area_event_inside (bContext *C, int x, int y)
static ARegion * region_event_inside (bContext *C, int x, int y)
static void wm_paintcursor_tag (bContext *C, wmPaintCursor *pc, ARegion *ar)
static void wm_paintcursor_test (bContext *C, wmEvent *event)
static void wm_event_drag_test (wmWindowManager *wm, wmWindow *win, wmEvent *event)
void wm_event_do_handlers (bContext *C)
void WM_event_fileselect_event (bContext *C, void *ophandle, int eventval)
void WM_event_add_fileselect (bContext *C, wmOperator *op)
wmEventHandler * WM_event_add_modal_handler (bContext *C, wmOperator *op)
wmEventHandler * WM_event_add_keymap_handler (ListBase *handlers, wmKeyMap *keymap)
wmEventHandler * WM_event_add_keymap_handler_priority (ListBase *handlers, wmKeyMap *keymap, int UNUSED(priority))
wmEventHandler * WM_event_add_keymap_handler_bb (ListBase *handlers, wmKeyMap *keymap, rcti *bblocal, rcti *bbwin)
void WM_event_remove_keymap_handler (ListBase *handlers, wmKeyMap *keymap)
wmEventHandler * WM_event_add_ui_handler (const bContext *C, ListBase *handlers, wmUIHandlerFunc func, wmUIHandlerRemoveFunc remove, void *userdata)
void WM_event_remove_ui_handler (ListBase *handlers, wmUIHandlerFunc func, wmUIHandlerRemoveFunc remove, void *userdata, int postpone)
wmEventHandler * WM_event_add_dropbox_handler (ListBase *handlers, ListBase *dropboxes)
void WM_event_remove_area_handler (ListBase *handlers, void *area)
void WM_event_add_mousemove (bContext *C)
int WM_modal_tweak_exit (wmEvent *evt, int tweak_event)
static int convert_key (GHOST_TKey key)
static void update_tablet_data (wmWindow *win, wmEvent *event)
static void attach_ndof_data (wmEvent *event, const GHOST_TEventNDOFMotionData *ghost)
static wmWindow * wm_event_cursor_other_windows (wmWindowManager *wm, wmWindow *win, wmEvent *evt)
void wm_event_add_ghostevent (wmWindowManager *wm, wmWindow *win, int type, int UNUSED(time), void *customdata)
Detailed Description
Definition in file wm_event_system.c.
Function Documentation
static ScrArea* area_event_inside (bContext * C, int x, int y) [static]
Definition at line 1834 of file wm_event_system.c.
References bScreen::areabase, BLI_in_rcti(), CTX_wm_screen(), ListBase::first, ScrArea::next, NULL, and ScrArea::totrct.
Referenced by wm_event_do_handlers(), and wm_paintcursor_test().
static void attach_ndof_data (wmEvent * event, const GHOST_TEventNDOFMotionData * ghost) [static]
Definition at line 2545 of file wm_event_system.c.
References wmEvent::custom, wmEvent::customdata, wmEvent::customdatafree, data, GHOST_TEventNDOFMotionData::dt, wmNDOFMotionData::dt, EVT_DATA_NDOF_MOTION, MEM_mallocN(), NDOF_ZOOM_UPDOWN, GHOST_TEventNDOFMotionData::progress, wmNDOFMotionData::progress, GHOST_TEventNDOFMotionData::rx, wmNDOFMotionData::rx, GHOST_TEventNDOFMotionData::ry, wmNDOFMotionData::ry, GHOST_TEventNDOFMotionData::rz, wmNDOFMotionData::rz, GHOST_TEventNDOFMotionData::tx, wmNDOFMotionData::tx, GHOST_TEventNDOFMotionData::ty, wmNDOFMotionData::ty, wmNDOFMotionData::tz, and GHOST_TEventNDOFMotionData::tz.
Referenced by wm_event_add_ghostevent().
static int convert_key (GHOST_TKey key) [static]
Definition at line 2439 of file wm_event_system.c.
References ACCENTGRAVEKEY, AKEY, BACKSLASHKEY, BACKSPACEKEY, CAPSLOCKKEY, COMMAKEY, DELKEY, DOWNARROWKEY, ENDKEY, EQUALKEY, ESCKEY, F1KEY, GHOST_kKey0, GHOST_kKey9, GHOST_kKeyA, GHOST_kKeyAccentGrave, GHOST_kKeyBackslash, GHOST_kKeyBackSpace, GHOST_kKeyCapsLock, GHOST_kKeyClear, GHOST_kKeyComma, GHOST_kKeyDelete, GHOST_kKeyDownArrow, GHOST_kKeyDownPage, GHOST_kKeyEnd, GHOST_kKeyEnter, GHOST_kKeyEqual, GHOST_kKeyEsc, GHOST_kKeyF1, GHOST_kKeyF19, GHOST_kKeyGrLess, GHOST_kKeyHome, GHOST_kKeyInsert, GHOST_kKeyLeftAlt, GHOST_kKeyLeftArrow, GHOST_kKeyLeftBracket, GHOST_kKeyLeftControl, GHOST_kKeyLeftShift, GHOST_kKeyLinefeed, GHOST_kKeyMediaFirst, GHOST_kKeyMediaLast, GHOST_kKeyMediaPlay, GHOST_kKeyMediaStop, GHOST_kKeyMinus, GHOST_kKeyNumLock, GHOST_kKeyNumpad0, GHOST_kKeyNumpad9, GHOST_kKeyNumpadAsterisk, GHOST_kKeyNumpadEnter, GHOST_kKeyNumpadMinus, GHOST_kKeyNumpadPeriod, GHOST_kKeyNumpadPlus, GHOST_kKeyNumpadSlash, GHOST_kKeyOS, GHOST_kKeyPause, GHOST_kKeyPeriod, GHOST_kKeyPrintScreen, GHOST_kKeyQuote, GHOST_kKeyRightAlt, GHOST_kKeyRightArrow, GHOST_kKeyRightBracket, GHOST_kKeyRightControl, GHOST_kKeyRightShift, GHOST_kKeyScrollLock, GHOST_kKeySemicolon, GHOST_kKeySlash, GHOST_kKeySpace, GHOST_kKeyTab, GHOST_kKeyUpArrow, GHOST_kKeyUpPage, GHOST_kKeyZ, GRLESSKEY, HOMEKEY, INSERTKEY, LEFTALTKEY, LEFTARROWKEY, LEFTBRACKETKEY, LEFTCTRLKEY, LEFTSHIFTKEY, LINEFEEDKEY, MEDIAFIRST, MEDIALAST, MEDIAPLAY, MEDIASTOP, MINUSKEY, OSKEY, PAD0, PADASTERKEY, PADENTER, PADMINUS, PADPERIOD, PADPLUSKEY, PADSLASHKEY, PAGEDOWNKEY, PAGEUPKEY, PAUSEKEY, PERIODKEY, QUOTEKEY, RETKEY, RIGHTALTKEY, RIGHTARROWKEY, RIGHTBRACKETKEY, RIGHTCTRLKEY, RIGHTSHIFTKEY, SEMICOLONKEY, SLASHKEY, SPACEKEY, TABKEY, UNKNOWNKEY, UPARROWKEY, and ZEROKEY.
Referenced by wm_event_add_ghostevent().
static int handler_boundbox_test (wmEventHandler * handler, wmEvent * event) [static]
Definition at line 1628 of file wm_event_system.c.
References wmEventHandler::bblocal, wmEventHandler::bbwin, BLI_in_rcti(), BLI_translate_rcti(), MOUSEMOVE, wmEvent::prevx, wmEvent::prevy, wmEvent::type, wmEvent::x, rcti::xmin, wmEvent::y, and rcti::ymin.
Referenced by wm_handlers_do().
static ARegion* region_event_inside (bContext * C, int x, int y) [static]
Definition at line 1846 of file wm_event_system.c.
References BLI_in_rcti(), CTX_wm_area(), CTX_wm_screen(), ListBase::first, ARegion::next, NULL, ScrArea::regionbase, and ARegion::winrct.
Referenced by wm_event_do_handlers(), and wm_paintcursor_test().
static void update_tablet_data (wmWindow * win, wmEvent * event) [static]
Definition at line 2525 of file wm_event_system.c.
References wmTabletData::Active, GHOST_TabletData::Active, wmEvent::custom, wmEvent::customdata, wmEvent::customdatafree, EVT_DATA_TABLET, GHOST_GetTabletData(), GHOST_kTabletModeNone, wmWindow::ghostwin, MEM_mallocN(), NULL, GHOST_TabletData::Pressure, wmTabletData::Pressure, GHOST_TabletData::Xtilt, wmTabletData::Xtilt, GHOST_TabletData::Ytilt, and wmTabletData::Ytilt.
Referenced by wm_event_add_ghostevent().
static int wm_action_not_handled (int action) [static]
Definition at line 1654 of file wm_event_system.c.
References WM_HANDLER_BREAK, WM_HANDLER_CONTINUE, and WM_HANDLER_MODAL.
Referenced by wm_event_do_handlers(), and wm_handlers_do().
void wm_event_add (wmWindow * win, wmEvent * event_to_add)
Definition at line 90 of file wm_event_system.c.
References BLI_addtail(), MEM_callocN(), and wmWindow::queue.
Referenced by actionzone_apply(), ghost_event_proc(), operator_search_menu(), tool_search_menu(), tweak_gesture_modal(), uiButSetFocusOnEnter(), wm_block_search_menu(), wm_enum_search_menu(), wm_event_add_ghostevent(), wm_event_do_handlers(), WM_event_fileselect_event(), and wm_window_timer().
wmEventHandler* WM_event_add_dropbox_handler (ListBase * handlers, ListBase * dropboxes) [read]
Definition at line 2352 of file wm_event_system.c.
References BLI_addhead(), wmEventHandler::dropboxes, dropboxes, ListBase::first, MEM_callocN(), and wmEventHandler::next.
Referenced by console_main_area_init(), image_init(), node_main_area_init(), outliner_main_area_init(), sequencer_main_area_init(), text_main_area_init(), view3d_main_area_init(), and wm_window_add_ghostwindows().
void WM_event_add_fileselect (bContext * C, wmOperator * op)
Definition at line 2188 of file wm_event_system.c.
References BLI_addhead(), BLI_remlink(), wmOperatorType::check, CTX_wm_area(), CTX_wm_region(), CTX_wm_screen(), CTX_wm_window(), EVT_FILESELECT_FULL_OPEN, EVT_FILESELECT_OPEN, wmEventHandler::filescreen, ListBase::first, MEM_callocN(), wmWindow::modalhandlers, wmEventHandler::next, wmEventHandler::op, wmEventHandler::op_area, wmEventHandler::op_region, wmOperator::type, wmEventHandler::type, WM_event_fileselect_event(), wm_event_free_handler(), WM_HANDLER_FILESELECT, and WM_operator_free().
Referenced by clip_filesel(), envmap_save_invoke(), file_browse_invoke(), find_missing_files_invoke(), image_filesel(), multires_external_save_invoke(), open_invoke(), paste_file_invoke(), screenshot_invoke(), sequencer_add_effect_strip_invoke(), sequencer_add_image_strip_invoke(), sequencer_add_movie_strip_invoke(), sequencer_add_sound_strip_invoke(), sequencer_change_path_invoke(), text_open_invoke(), text_save_as_invoke(), wm_link_append_invoke(), wm_open_mainfile_invoke(), WM_operator_filesel(), wm_recover_auto_save_invoke(), wm_save_as_mainfile_invoke(), and wm_save_mainfile_invoke().
void wm_event_add_ghostevent (wmWindowManager * wm, wmWindow * win, int type, int UNUSEDtime, void * customdata)
Definition at line 2628 of file wm_event_system.c.
References GHOST_TEventNDOFButtonData::action, wmWindow::active, wmEvent::alt, wmEvent::ascii, GHOST_TEventKeyData::ascii, attach_ndof_data(), BLI_str_utf8_size(), GHOST_TEventNDOFButtonData::button, GHOST_TEventButtonData::button, BUTTON4MOUSE, BUTTON5MOUSE, convert_key(), wmEvent::ctrl, GHOST_TEventTrackpadData::deltaX, GHOST_TEventTrackpadData::deltaY, ESCKEY, wmWindow::eventstate, EVT_DATA_TIMER, FALSE, G, GHOST_kButtonMaskButton4, GHOST_kButtonMaskButton5, GHOST_kButtonMaskLeft, GHOST_kButtonMaskRight, GHOST_kEventButtonDown, GHOST_kEventButtonUp, GHOST_kEventCursorMove, GHOST_kEventKeyDown, GHOST_kEventKeyUp, GHOST_kEventNDOFButton, GHOST_kEventNDOFMotion, GHOST_kEventTimer, GHOST_kEventTrackpad, GHOST_kEventUnknown, GHOST_kEventWheel, GHOST_kEventWindowDeactivate, GHOST_kNumEventTypes, GHOST_kPress, GHOST_kRelease, GHOST_kTrackpadEventMagnify, GHOST_kTrackpadEventRotate, GHOST_kTrackpadEventScroll, GHOST_ScreenToClient(), wmWindow::ghostwin, INBETWEEN_MOUSEMOVE, GHOST_TEventKeyData::key, wmEvent::keymodifier, KM_MOD_FIRST, KM_MOD_SECOND, KM_PRESS, KM_RELEASE, ListBase::last, LEFTALTKEY, LEFTCTRLKEY, LEFTMOUSE, LEFTSHIFTKEY, MIDDLEMOUSE, MOUSEMOVE, MOUSEPAN, MOUSEROTATE, MOUSEZOOM, NDOF_BUTTON_NONE, NDOF_MOTION, NULL, OSKEY, wmEvent::oskey, wmWindow::queue, RIGHTALTKEY, RIGHTCTRLKEY, RIGHTMOUSE, RIGHTSHIFTKEY, wmEvent::shift, wmWindow::sizey, GHOST_TEventTrackpadData::subtype, TIMER, wmEvent::type, UNKNOWNKEY, update_tablet_data(), GHOST_TEventKeyData::utf8_buf, wmEvent::utf8_buf, wmEvent::val, WHEELDOWNMOUSE, WHEELUPMOUSE, WINDEACTIVATE, wm_event_add(), wm_event_cursor_other_windows(), wm_get_cursor_position(), GHOST_TEventTrackpadData::x, wmEvent::x, GHOST_TEventCursorData::x, GHOST_TEventTrackpadData::y, wmEvent::y, GHOST_TEventCursorData::y, and GHOST_TEventWheelData::z.
Referenced by ghost_event_proc().
wmEventHandler* WM_event_add_keymap_handler (ListBase * handlers, wmKeyMap * keymap) [read]
Definition at line 2256 of file wm_event_system.c.
References BLI_addtail(), ListBase::first, wmEventHandler::keymap, MEM_callocN(), wmEventHandler::next, and NULL.
Referenced by buttons_main_area_init(), clip_properties_area_init(), ed_default_handlers(), ED_region_panels_init(), graph_channel_area_init(), graph_main_area_init(), image_buttons_area_init(), image_main_area_init(), image_scope_area_init(), info_main_area_init(), logic_buttons_area_init(), logic_main_area_init(), nla_main_area_init(), node_buttons_area_init(), node_main_area_init(), view3d_buttons_area_init(), view3d_header_area_init(), view3d_main_area_init(), view3d_tools_area_init(), WM_event_add_keymap_handler_bb(), and wm_window_add_ghostwindows().
wmEventHandler* WM_event_add_keymap_handler_bb (ListBase * handlers, wmKeyMap * keymap, rcti * bblocal, rcti * bbwin) [read]
Definition at line 2291 of file wm_event_system.c.
References wmEventHandler::bblocal, wmEventHandler::bbwin, and WM_event_add_keymap_handler().
Referenced by action_channel_area_init(), action_main_area_init(), clip_main_area_init(), clip_preview_area_init(), console_main_area_init(), ed_default_handlers(), file_channel_area_init(), file_header_area_init(), file_main_area_init(), file_ui_area_init(), graph_buttons_area_init(), graph_channel_area_init(), graph_main_area_init(), image_main_area_init(), nla_buttons_area_init(), nla_channel_area_init(), nla_main_area_init(), node_main_area_init(), outliner_main_area_init(), script_main_area_init(), sequencer_main_area_init(), sequencer_preview_area_init(), text_main_area_init(), and time_main_area_init().
wmEventHandler* WM_event_add_keymap_handler_priority (ListBase * handlers, wmKeyMap * keymap, int UNUSEDpriority)
Definition at line 2278 of file wm_event_system.c.
References BLI_addhead(), wmEventHandler::keymap, MEM_callocN(), and WM_event_remove_keymap_handler().
wmEventHandler* WM_event_add_modal_handler (bContext * C, wmOperator * op) [read]
Definition at line 2233 of file wm_event_system.c.
References BLI_addhead(), CTX_wm_area(), CTX_wm_region(), CTX_wm_window(), MEM_callocN(), wmWindow::modalhandlers, wmEventHandler::op, wmEventHandler::op_area, wmEventHandler::op_region, and wmOperator::opm.
Referenced by actionzone_invoke(), area_join_invoke(), area_move_invoke(), area_split_invoke(), area_swap_invoke(), brush_edit_invoke(), change_frame_invoke(), console_modal_select_invoke(), ed_marker_move_invoke(), eyedropper_invoke(), fly_invoke(), gpencil_draw_invoke(), grab_clone_invoke(), graphview_cursor_invoke(), image_record_composite_invoke(), image_sample_invoke(), image_view_pan_init(), image_view_zoom_init(), knifetool_invoke(), minimize_stretch_invoke(), multiresbake_image_exec(), node_link_invoke(), node_resize_invoke(), objects_bake_render_invoke(), paint_invoke(), pose_slide_invoke_common(), poselib_preview_invoke(), radial_control_invoke(), region_scale_invoke(), ringcut_invoke(), sample_color_invoke(), sample_invoke(), screen_opengl_render_invoke(), screen_render_invoke(), scroller_activate_invoke(), sculpt_brush_stroke_invoke(), sketch_draw_gesture(), sketch_draw_stroke(), slide_marker_invoke(), snode_bg_viewmove_invoke(), solve_camera_invoke(), stitch_invoke(), text_scroll_bar_invoke(), text_scroll_invoke(), text_set_selection_invoke(), track_markers_invoke(), transform_invoke(), uv_sculpt_stroke_invoke(), view_pan_init(), view_pan_invoke(), view_zoom_init(), view_zoomdrag_invoke(), viewdolly_invoke(), viewmove_invoke(), viewrotate_invoke(), viewzoom_invoke(), vpaint_invoke(), vtx_slide_init(), WM_border_select_invoke(), WM_gesture_circle_invoke(), WM_gesture_lasso_invoke(), WM_gesture_lines_invoke(), WM_gesture_straightline_invoke(), and wpaint_invoke().
void WM_event_add_mousemove (bContext * C)
Definition at line 2394 of file wm_event_system.c.
References wmWindow::addmousemove, and CTX_wm_window().
Referenced by button_activate_exit(), ED_area_newspace(), ED_area_swapspace(), ED_screen_set(), file_select_invoke(), ui_popup_menu_create(), uiPupBlockEx(), uiPupBlockO(), and uiPupMenuEnd().
void WM_event_add_notifier (const bContext * C, unsigned int type, void * reference)
Definition at line 136 of file wm_event_system.c.
References wmNotifier::action, BLI_addtail(), wmNotifier::category, CTX_wm_manager(), CTX_wm_region(), CTX_wm_window(), wmNotifier::data, MEM_callocN(), NOTE_ACTION, NOTE_CATEGORY, NOTE_DATA, NOTE_SUBTYPE, wmWindowManager::queue, wmNotifier::reference, wmNotifier::subtype, ARegion::swinid, wmNotifier::swinid, wmNotifier::window, and wmNotifier::wm.
Referenced by achannel_setting_flush_widget_cb(), achannel_setting_rename_done_cb(), achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), achannel_setting_widget_cb(), act_markers_make_local_exec(), act_new_exec(), actkeys_borderselect_exec(), actkeys_clean_exec(), actkeys_clickselect_invoke(), actkeys_columnselect_exec(), actkeys_delete_exec(), actkeys_deselectall_exec(), actkeys_duplicate_exec(), actkeys_expo_exec(), actkeys_framejump_exec(), actkeys_handletype_exec(), actkeys_insertkey_exec(), actkeys_ipo_exec(), actkeys_keytype_exec(), actkeys_mirror_exec(), actkeys_paste_exec(), actkeys_previewrange_exec(), actkeys_sample_exec(), actkeys_select_leftright_exec(), actkeys_select_less_exec(), actkeys_select_linked_exec(), actkeys_select_more_exec(), actkeys_snap_exec(), actuator_add_exec(), actuator_move_exec(), actuator_remove_exec(), add_default_keyingset_exec(), add_driver_button_exec(), add_keyingset_button_exec(), add_marker_exec(), add_named_exec(), animchannels_borderselect_exec(), animchannels_collapse_exec(), animchannels_delete_exec(), animchannels_deselectall_exec(), animchannels_enable_exec(), animchannels_expand_exec(), animchannels_mouseclick_invoke(), animchannels_rearrange_exec(), animchannels_setflag_exec(), animchannels_visibility_set_exec(), animchannels_visibility_toggle_exec(), apply_armature_pose2bones_exec(), apply_objects_internal(), area_dupli_invoke(), area_join_cancel(), area_join_modal(), area_move_apply_do(), area_split_apply(), area_split_exit(), area_swap_modal(), armature_align_bones_exec(), armature_autoside_names_exec(), armature_bone_layers_exec(), armature_bone_primitive_add_exec(), armature_calc_roll_exec(), armature_click_extrude_exec(), armature_de_select_all_exec(), armature_delete_selected_exec(), armature_duplicate_selected_exec(), armature_extrude_exec(), armature_fill_bones_exec(), armature_flip_names_exec(), armature_hide_exec(), armature_merge_exec(), armature_parent_clear_exec(), armature_parent_set_exec(), armature_reveal_exec(), armature_select_hierarchy_exec(), armature_select_inverse_exec(), armature_select_linked_invoke(), armature_subdivide_exec(), average_islands_scale_exec(), background_image_add_invoke(), background_image_remove_exec(), bake_image_exec(), bc_set_parent(), bookmark_select_exec(), border_select_exec(), border_select_graph_exec(), brush_edit_apply(), brush_uv_sculpt_tool_set_exec(), change_frame_apply(), childof_clear_inverse_exec(), childof_set_inverse_exec(), circle_select_exec(), clean_tracks_exec(), clear_edited_exec(), clear_solution_exec(), clear_tilt_exec(), clear_track_path_exec(), clip_delete_marker(), clip_delete_track(), connect_hair_exec(), constraint_add_exec(), constraint_delete_exec(), constraint_move_down_exec(), constraint_move_up_exec(), controller_add_exec(), controller_move_exec(), controller_remove_exec(), convert_exec(), copy_particle_dupliob_exec(), create_orientation_exec(), createRepresentation(), cube_project_exec(), curvesurf_prim_add(), cylinder_project_exec(), de_select_all_exec(), de_select_first_exec(), de_select_last_exec(), delete_exec(), delete_fmodifier_cb(), delete_key_button_exec(), delete_key_exec(), delete_key_v3d_exec(), delete_metaelems_exec(), delete_orientation_exec(), deleteflagNurb(), detect_features_exec(), disable_markers_exec(), disconnect_hair_exec(), do_constraint_panels(), do_graph_region_driver_buttons(), do_graph_region_modifier_buttons(), do_nla_region_buttons(), do_object_pose_box_select(), do_outliner_item_activate(), do_preview_buttons(), do_set_scale(), do_uvedit_vertex(), do_view3d_header_buttons(), do_view3d_region_buttons(), do_view3d_vgroup_buttons(), drop_named_image_invoke(), drop_named_material_invoke(), duplicate_exec(), duplicate_metaelems_exec(), dupliob_move_down_exec(), dupliob_move_up_exec(), ED_area_newspace(), ED_area_prevspace(), ED_armature_enter_posemode(), ED_armature_exit_posemode(), ED_base_object_activate(), ED_fileselect_clear(), ed_marker_add(), ed_marker_border_select_exec(), ed_marker_delete_exec(), ed_marker_move_cancel(), ed_marker_move_modal(), ed_marker_rename_exec(), ed_marker_select(), ed_marker_select_all_exec(), ED_mesh_color_add(), ED_mesh_color_remove(), ED_mesh_color_remove_named(), ED_mesh_update(), ED_mesh_uv_loop_reset_ex(), ED_mesh_uv_texture_add(), ED_mesh_uv_texture_remove(), ED_object_add_type(), ED_object_enter_editmode(), ED_object_exit_editmode(), ED_object_parent_clear(), ED_object_shape_key_add(), ED_object_shape_key_remove(), ED_screen_animation_timer(), ED_screen_set(), ED_screen_set_scene(), ED_screen_set_subwinactive(), ED_space_clip_set(), ED_text_undo_step(), ED_undo_gpencil_step(), ED_undo_push(), ed_undo_step(), edbm_extrude_edges_exec(), edbm_extrude_faces_exec(), edbm_extrude_verts_exec(), edbm_faces_select_interior_exec(), edbm_loop_multiselect_exec(), edbm_loop_to_region_exec(), edbm_region_to_loop_exec(), edbm_select_all_exec(), edbm_select_axis_exec(), edbm_select_by_number_vertices_exec(), edbm_select_less_exec(), edbm_select_linked_exec(), edbm_select_linked_flat_faces_exec(), edbm_select_linked_pick_invoke(), edbm_select_loose_verts_exec(), edbm_select_mirror_exec(), edbm_select_more_exec(), edbm_select_next_loop_exec(), edbm_select_non_manifold_exec(), edbm_select_random_exec(), edbm_select_sharp_edges_exec(), EDBM_selectmode_to_scene(), EDBM_update_generic(), enable_manipulator_invoke(), envmap_clear_all_exec(), envmap_clear_exec(), envmap_save_exec(), explode_refresh_exec(), extrude_exec(), file_border_select_exec(), file_border_select_modal(), file_delete_exec(), file_directory_exec(), file_directory_new_exec(), file_filename_exec(), file_hidedot_exec(), file_next_exec(), file_parent_exec(), file_previous_exec(), file_refresh_exec(), file_select_invoke(), fly_modal(), forcefield_toggle_exec(), frame_jump_exec(), frame_offset_exec(), game_property_clear_exec(), game_property_new(), game_property_remove(), ghost_event_proc(), gp_actframe_delete_exec(), gp_convert_layer_exec(), gp_data_add_exec(), gp_data_unlink_exec(), gp_layer_add_exec(), gp_ui_activelayer_cb(), gp_ui_dellayer_cb(), gpencil_draw_exec(), gpencil_draw_invoke(), gpencil_draw_modal(), graph_disable_markers_exec(), graph_fmodifier_add_exec(), graph_fmodifier_paste_exec(), graph_select_all_markers_exec(), graphkeys_bake_exec(), graphkeys_borderselect_exec(), graphkeys_clean_exec(), graphkeys_click_insert_exec(), graphkeys_clickselect_invoke(), graphkeys_columnselect_exec(), graphkeys_delete_exec(), graphkeys_deselectall_exec(), graphkeys_duplicate_exec(), graphkeys_euler_filter_exec(), graphkeys_expo_exec(), graphkeys_framejump_exec(), graphkeys_handletype_exec(), graphkeys_insertkey_exec(), graphkeys_ipo_exec(), graphkeys_mirror_exec(), graphkeys_paste_exec(), graphkeys_previewrange_exec(), graphkeys_sample_exec(), graphkeys_select_leftright_exec(), graphkeys_select_less_exec(), graphkeys_select_linked_exec(), graphkeys_select_more_exec(), graphkeys_smooth_exec(), graphkeys_snap_exec(), graphview_cursor_apply(), group_add_exec(), group_create_exec(), group_instance_add_exec(), group_link_exec(), group_move_exec(), group_objects_remove_exec(), group_remove_exec(), group_sort_exec(), handle_view3d_lock(), header_flip_exec(), hide_exec(), hide_metaelems_exec(), hide_tracks_clear_exec(), hide_tracks_exec(), image_cycle_render_slot_exec(), image_invert_exec(), image_multi_cb(), image_multi_declay_cb(), image_multi_decpass_cb(), image_multi_inclay_cb(), image_multi_incpass_cb(), image_open_exec(), image_pack_exec(), image_record_composite_exit(), image_reload_exec(), image_replace_exec(), image_unpack_exec(), insert_key_button_exec(), insert_key_exec(), insert_lorem_exec(), join_armature_exec(), join_curve_exec(), join_mesh_exec(), join_mesh_shapes_exec(), join_tracks_exec(), keyframe_jump_exec(), keyingset_active_menu_exec(), lattice_select_all_exec(), limitdistance_reset_exec(), SkinInfo::link_armature(), lock_tracks_exec(), logicbricks_copy_exec(), make_links_data_exec(), make_local_exec(), make_prim_finish(), make_proxy_exec(), make_regular_exec(), make_segment_exec(), make_single_user_exec(), mark_seam_exec(), marker_block_handler(), marker_update_cb(), material_slot_add_exec(), material_slot_assign_exec(), material_slot_copy_exec(), material_slot_de_select(), material_slot_remove_exec(), mball_select_all_exec(), merge_nurb(), mesh_sticky_add_exec(), mesh_sticky_remove_exec(), meshdeform_bind_exec(), minimize_stretch_exit(), minimize_stretch_iteration(), mirror_exec(), mode_set_exec(), modifier_add_exec(), modifier_apply_exec(), modifier_convert_exec(), modifier_copy_exec(), modifier_move_down_exec(), modifier_move_up_exec(), modifier_remove_exec(), modifiers_convertToReal(), modifiers_setOnCage(), mouse_armature(), mouse_lattice(), mouse_mball(), mouse_mesh(), mouse_mesh_loop(), mouse_nurb(), mouse_select(), mouse_weight_paint_vertex_select(), move_to_layer_exec(), multires_base_apply_exec(), multires_higher_levels_delete_exec(), multires_reshape_exec(), multires_subdivide_exec(), namebutton_cb(), navmesh_clear_exec(), navmesh_face_add_exec(), navmesh_face_copy_exec(), navmesh_reset_exec(), new_material_exec(), new_particle_settings_exec(), new_particle_target_exec(), new_texture_exec(), new_world_exec(), nla_fmodifier_add_exec(), nla_fmodifier_paste_exec(), nlachannels_mouseclick_invoke(), nlaedit_add_actionclip_exec(), nlaedit_add_meta_exec(), nlaedit_add_sound_exec(), nlaedit_add_tracks_exec(), nlaedit_add_transition_exec(), nlaedit_apply_scale_exec(), nlaedit_bake_exec(), nlaedit_borderselect_exec(), nlaedit_clear_scale_exec(), nlaedit_clickselect_invoke(), nlaedit_delete_exec(), nlaedit_delete_tracks_exec(), nlaedit_deselectall_exec(), nlaedit_disable_tweakmode_exec(), nlaedit_duplicate_exec(), nlaedit_enable_tweakmode_exec(), nlaedit_move_down_exec(), nlaedit_move_up_exec(), nlaedit_remove_meta_exec(), nlaedit_select_leftright_exec(), nlaedit_snap_exec(), nlaedit_split_exec(), nlaedit_swap_exec(), nlaedit_sync_actlen_exec(), nlaedit_toggle_mute_exec(), node_borderselect_exec(), node_group_edit_exec(), node_normal_cb(), node_read_fullsamplelayers_exec(), node_select_all_exec(), node_select_exec(), node_select_linked_from_exec(), node_select_linked_to_exec(), node_select_same_type_exec(), node_select_same_type_next_exec(), node_select_same_type_prev_exec(), node_select_single(), object_add_hook_newob_exec(), object_add_hook_selob_exec(), object_add_text_exec(), object_armature_add_exec(), object_calculate_paths_exec(), object_clear_paths_exec(), object_clear_transform_generic_exec(), object_constraint_copy_exec(), object_constraints_clear_exec(), object_delete_exec(), object_duplicates_make_real_exec(), object_hide_render_clear_exec(), object_hide_render_set_exec(), object_hide_view_clear_exec(), object_hide_view_set_exec(), object_hook_assign_exec(), object_hook_recenter_exec(), object_hook_remove_exec(), object_hook_reset_exec(), object_hook_select_exec(), object_metaball_add_exec(), object_origin_clear_exec(), object_origin_set_exec(), object_select_all_exec(), object_select_by_layer_exec(), object_select_by_type_exec(), object_select_grouped_exec(), object_select_linked_exec(), object_select_menu_exec(), object_select_mirror_exec(), object_select_random_exec(), object_select_same_group_exec(), object_shape_key_mirror(), object_slow_parent_clear_exec(), object_slow_parent_set_exec(), object_speaker_add_exec(), object_track_clear_exec(), objects_add_active_exec(), objects_bake_render_invoke(), objects_remove_active_exec(), objectsolver_clear_inverse_exec(), objectsolver_set_inverse_exec(), ocean_bake_exec(), open_exec(), outliner_action_set_exec(), outliner_animdata_operation_exec(), outliner_border_select_exec(), outliner_data_operation_exec(), outliner_drivers_addsel_exec(), outliner_drivers_deletesel_exec(), outliner_group_operation_exec(), outliner_id_operation_exec(), outliner_keyingset_additems_exec(), outliner_keyingset_removeitems_exec(), outliner_object_operation_exec(), outliner_toggle_renderability_exec(), outliner_toggle_selectability_exec(), outliner_toggle_selected_exec(), outliner_toggle_visibility_exec(), pack_islands_exec(), paint_redraw(), paintface_mouse_select(), parent_drop_exec(), parent_drop_invoke(), parent_noinv_set_exec(), parent_set_exec(), particle_edit_toggle_exec(), particle_system_add_exec(), particle_system_remove_exec(), paste_material_exec(), paste_mtex_exec(), paste_tracks_exec(), PE_border_select(), PE_circle_select(), PE_lasso_select(), PE_mouse_particles(), pe_select_all_exec(), pin_exec(), pose_armature_layers_exec(), pose_armature_layers_showall_exec(), pose_autoside_names_exec(), pose_bone_flip_active_exec(), pose_bone_layers_exec(), pose_bone_rotmode_exec(), pose_calculate_paths_exec(), pose_clear_paths_exec(), pose_clear_transform_generic_exec(), pose_clear_user_transforms_exec(), pose_constraint_copy_exec(), pose_constraints_clear_exec(), pose_de_select_all_exec(), pose_flip_names_exec(), pose_flip_quats_exec(), pose_group_add_exec(), pose_group_assign_exec(), pose_group_deselect_exec(), pose_group_remove_exec(), pose_group_select_exec(), pose_group_unassign_exec(), pose_hide_exec(), pose_ik_clear_exec(), pose_paste_exec(), pose_reveal_exec(), pose_select_connected_invoke(), pose_select_constraint_target_exec(), pose_select_grouped_exec(), pose_select_hierarchy_exec(), pose_select_parent_exec(), pose_visual_transform_apply_exec(), poseAnim_mapping_refresh(), poselib_keytag_pose(), poselib_new_exec(), poselib_preview_apply(), poselib_remove_exec(), poselib_rename_exec(), poselib_sanitise_exec(), poselib_unlink_exec(), previewrange_define_exec(), ptcache_add_new_exec(), ptcache_bake_all_exec(), ptcache_bake_exec(), ptcache_bake_from_cache_exec(), ptcache_free_bake_all_exec(), ptcache_free_bake_exec(), ptcache_remove_exec(), pyrna_struct_driver_add(), pyrna_struct_driver_remove(), radial_control_cancel(), region_flip_exec(), region_quadview_exec(), region_scale_modal(), rekey_exec(), reload_exec(), remove_active_keyingset_exec(), remove_doubles_exec(), remove_driver_button_exec(), remove_keyingset_button_exec(), remove_particle_dupliob_exec(), remove_particle_target_exec(), render_border_exec(), render_layer_add_exec(), render_layer_remove_exec(), reset_default_theme_exec(), reset_exec(), restrictbutton_bone_cb(), restrictbutton_ebone_cb(), restrictbutton_gr_restrict_render(), restrictbutton_gr_restrict_select(), restrictbutton_gr_restrict_view(), restrictbutton_modifier_cb(), restrictbutton_r_lay_cb(), restrictbutton_rend_cb(), restrictbutton_sel_cb(), restrictbutton_view_cb(), reveal_exec(), reveal_metaelems_exec(), ringsel_finish(), rule_add_exec(), rule_del_exec(), rule_move_down_exec(), rule_move_up_exec(), sample_color_exec(), save_image_doit(), scene_delete_exec(), scene_new_exec(), screen_animation_cancel_exec(), screen_delete_exec(), screen_new_exec(), screen_opengl_render_end(), screen_opengl_render_exec(), screen_opengl_render_modal(), screen_render_exec(), screen_render_invoke(), screencast_exec(), script_reload_exec(), sculpt_stroke_done(), sculpt_toggle_mode(), sculpt_undo_restore_coords(), select_all_exec(), select_groped_exec(), select_invoke(), select_less_exec(), select_linked_exec(), select_linked_internal(), select_linked_pick_invoke(), select_more_exec(), select_next_exec(), select_nth_exec(), select_orientation_exec(), select_pinned_exec(), select_previous_exec(), select_random_exec(), select_random_metaelems_exec(), select_roots_exec(), select_row_exec(), select_tips_exec(), sensor_add_exec(), sensor_move_exec(), sensor_remove_exec(), separate_armature_exec(), separate_exec(), sequencer_add_duplicate_exec(), sequencer_add_effect_strip_exec(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_borderselect_exec(), sequencer_change_effect_input_exec(), sequencer_change_effect_type_exec(), sequencer_change_path_exec(), sequencer_cut_exec(), sequencer_de_select_all_exec(), sequencer_delete_exec(), sequencer_lock_exec(), sequencer_meta_make_exec(), sequencer_meta_separate_exec(), sequencer_meta_toggle_exec(), sequencer_mute_exec(), sequencer_next_edit_exec(), sequencer_offset_clear_exec(), sequencer_paste_exec(), sequencer_previous_edit_exec(), sequencer_reassign_inputs_exec(), sequencer_refresh_all_exec(), sequencer_reload_exec(), sequencer_rendersize_exec(), sequencer_select_active_side_exec(), sequencer_select_grouped_exec(), sequencer_select_handles_exec(), sequencer_select_inverse_exec(), sequencer_select_invoke(), sequencer_select_less_exec(), sequencer_select_linked_exec(), sequencer_select_linked_pick_invoke(), sequencer_select_more_exec(), sequencer_separate_images_exec(), sequencer_snap_exec(), sequencer_swap_data_exec(), sequencer_swap_exec(), sequencer_swap_inputs_exec(), sequencer_unlock_exec(), sequencer_unmute_exec(), set_2d_cursor_exec(), set_3dcursor_invoke(), set_active_group_exec(), set_axis_exec(), set_center_principal_exec(), set_goal_weight_exec(), set_handle_type_exec(), set_origin_exec(), set_plane_exec(), set_radius_exec(), set_spline_type_exec(), set_style(), set_tile_exec(), set_vpaint(), set_wpaint(), shade_smooth_exec(), shape_key_clear_exec(), shape_key_move_exec(), shape_key_retime_exec(), sketch_delete(), slide_marker_invoke(), slide_marker_modal(), smooth_exec(), smooth_radius_exec(), snap_curs_to_active(), snap_curs_to_center(), snap_curs_to_grid(), snap_curs_to_sel(), snap_cursor_exec(), snap_sel_to_curs(), snap_sel_to_grid(), snap_selection_exec(), snap_type_exec(), snode_bg_viewmove_modal(), snode_notify(), solve_camera_invoke(), spacefunc(), special_aftertrans_update(), sphere_project_exec(), spin_exec(), stabilize_2d_add_exec(), stabilize_2d_remove_exec(), stabilize_2d_select_exec(), stabilize_2d_set_rotation_exec(), state_add_exec(), state_del_exec(), state_move_up_exec(), stitch_exit(), stitch_invoke(), stretchto_reset_exec(), subdivide_exec(), surface_slot_remove_exec(), switch_direction_exec(), target_move_down_exec(), target_move_up_exec(), template_id_cb(), text_clear_all_markers_exec(), text_comment_exec(), text_convert_whitespace_exec(), text_cursor_set_apply(), text_cursor_set_exec(), text_cursor_set_exit(), text_cut_exec(), text_delete_exec(), text_find_and_replace(), text_indent_exec(), text_insert_exec(), text_jump_exec(), text_line_break_exec(), text_line_number_invoke(), text_make_internal_exec(), text_move_cursor(), text_new_exec(), text_next_marker_exec(), text_open_exec(), text_paste_exec(), text_previous_marker_exec(), text_reload_exec(), text_run_script(), text_save_as_exec(), text_save_exec(), text_select_all_exec(), text_select_line_exec(), text_select_word_exec(), text_toggle_overwrite_exec(), text_uncomment_exec(), text_unindent_exec(), text_unlink_exec(), text_update_edited(), textbox_add_exec(), textbox_remove_exec(), texture_paint_camera_project_exec(), texture_paint_toggle_exec(), texture_slot_move(), time_set_efra_exec(), time_set_sfra_exec(), toggle_cyclic_exec(), track_copy_color_exec(), track_markers_exec(), track_set_exec(), tracking_object_new_exec(), tracking_object_remove_exec(), transform_exec(), tree_element_active_bone(), tree_element_active_constraint(), tree_element_active_defgroup(), tree_element_active_ebone__sel(), tree_element_active_material(), tree_element_active_modifier(), tree_element_active_posechannel(), tree_element_active_posegroup(), tree_element_active_psys(), tree_element_active_renderlayer(), tree_element_active_texture(), txt_add_object(), type_toggle_exec(), ui_but_anim_autokey(), ui_but_anim_expression_create(), ui_but_anim_expression_set(), ui_numedit_but_TRACKPREVIEW(), uiTemplateImage(), undo_history_exec(), unlink_selection_exec(), unwrap_exec(), update_reports_display_invoke(), uv_from_view_exec(), uv_sculpt_stroke_modal(), vertex_group_add_exec(), vertex_group_assign_exec(), vertex_group_blend_exec(), vertex_group_clean_exec(), vertex_group_copy_exec(), vertex_group_copy_to_linked_exec(), vertex_group_deselect_exec(), vertex_group_fix_exec(), vertex_group_invert_exec(), vertex_group_levels_exec(), vertex_group_mirror_exec(), vertex_group_normalize_all_exec(), vertex_group_normalize_exec(), vertex_group_remove_exec(), vertex_group_remove_from_exec(), vertex_group_select_exec(), vertex_group_sort_exec(), vertex_parent_set_exec(), vgroup_move_exec(), view3d_all_exec(), view3d_borderselect_exec(), view3d_camera_to_view_exec(), view3d_camera_to_view_selected_exec(), view3d_center_camera_exec(), view3d_circle_select_exec(), view3d_lasso_select(), view3d_setobjectascamera_exec(), view3d_smoothview_invoke(), view3d_zoom_1_to_1_camera_exec(), view_ghost_border_exec(), viewRedrawForce(), viewRedrawPost(), visual_transform_apply_exec(), weight_from_bones_exec(), weight_sample_group_exec(), weight_set_exec(), weld_align_uv(), wm_debug_menu_exec(), wm_event_do_handlers(), wm_event_do_notifiers(), wm_jobs_timer(), wm_link_append_exec(), wm_open_mainfile_exec(), wm_operator_register(), WM_read_file(), WM_read_homefile(), wm_recover_auto_save_exec(), wm_recover_last_session_exec(), wm_save_as_mainfile_exec(), wm_window_duplicate_exec(), and wpaint_stroke_test_start().
wmEventHandler* WM_event_add_ui_handler (const bContext * C, ListBase * handlers, wmUIHandlerFunc func, wmUIHandlerRemoveFunc remove, void * userdata)
Definition at line 2315 of file wm_event_system.c.
References BLI_addhead(), C, CTX_wm_area(), CTX_wm_menu(), CTX_wm_region(), MEM_callocN(), NULL, wmEventHandler::ui_area, wmEventHandler::ui_handle, wmEventHandler::ui_menu, wmEventHandler::ui_region, wmEventHandler::ui_remove, and wmEventHandler::ui_userdata.
Referenced by button_activate_state(), panel_activate_state(), UI_add_popup_handlers(), and UI_add_region_handlers().
static int wm_event_always_pass (wmEvent * event) [static]
Definition at line 321 of file wm_event_system.c.
References ISTIMER, wmEvent::type, and WINDEACTIVATE.
Referenced by wm_event_inside_i(), wm_handler_operator_call(), wm_handler_ui_call(), and wm_handlers_do().
static wmWindow* wm_event_cursor_other_windows (wmWindowManager * wm, wmWindow * win, wmEvent * evt) [static]
Definition at line 2587 of file wm_event_system.c.
References ListBase::first, ListBase::last, wmWindow::modalhandlers, wmEventHandler::next, wmWindow::next, NULL, wmEventHandler::op, wmWindow::posx, wmWindow::posy, wmWindow::sizex, wmWindow::sizey, wmEventHandler::ui_handle, wmWindowManager::windows, wmEvent::x, and wmEvent::y.
Referenced by wm_event_add_ghostevent().
void wm_event_do_handlers (bContext * C)
Definition at line 1938 of file wm_event_system.c.
References wmWindow::addmousemove, bScreen::animtimer, area_event_inside(), bScreen::areabase, BLI_in_rcti(), BLI_remlink(), RenderData::cfra, CTX_data_main(), CTX_data_scene_set(), CTX_wm_area_set(), CTX_wm_manager(), CTX_wm_region_set(), CTX_wm_screen_set(), CTX_wm_window(), CTX_wm_window_set(), ED_screen_animation_play(), ED_screen_set_subwinactive(), ED_update_for_newframe(), ELEM, wmWindow::eventstate, EVT_DROP, ListBase::first, FPS, G, G_DEBUG_EVENTS, ARegion::handlers, wmWindow::handlers, ScrArea::handlers, INBETWEEN_MOUSEMOVE, ISTIMER, KM_CLICK, KM_PRESS, KM_RELEASE, bScreen::mainwin, wmWindow::modalhandlers, MOUSEMOVE, NC_WINDOW, NDOF_MOTION, ScrArea::next, ARegion::next, wmWindow::next, NULL, PIL_check_seconds_timer(), wmEvent::prevclicktime, wmEvent::prevclickx, wmEvent::prevclicky, wmEvent::prevtype, wmEvent::prevval, wmEvent::prevx, wmEvent::prevy, wmWindow::queue, Scene::r, region_event_inside(), ScrArea::regionbase, bScreen::scene, wmWindow::screen, sound_scene_playing(), sound_sync_scene(), bScreen::subwinactive, ScrArea::totrct, TRUE, wmEvent::type, wmEvent::val, wmWindowManager::windows, ARegion::winrct, wm_action_not_handled(), wm_drags_check_ops(), wm_event_add(), WM_event_add_notifier(), wm_event_drag_test(), wm_event_free(), wm_event_free_all(), wm_event_inside_i(), wm_eventemulation(), WM_HANDLER_BREAK, WM_HANDLER_CONTINUE, wm_handlers_do(), WM_keyconfig_update(), wm_paintcursor_test(), wm_region_mouse_co(), wm_tweakevent_test(), wm_window_make_drawable(), wmEvent::x, and wmEvent::y.
Referenced by WM_main().
void wm_event_do_notifiers (bContext * C)
Definition at line 185 of file wm_event_system.c.
References bScreen::areabase, wmNotifier::category, CTX_data_main(), CTX_data_scene(), CTX_wm_area_set(), CTX_wm_manager(), CTX_wm_window_set(), Scene::customdata_mask, Scene::customdata_mask_modal, wmNotifier::data, ScrArea::do_refresh, ED_area_do_listen(), ED_area_do_refresh(), ED_info_stats_clear(), ED_region_do_listen(), ED_screen_delete(), ED_screen_do_listen(), ED_screen_set(), ED_update_for_newframe(), ED_view3d_screen_datamask(), ELEM, ELEM5, wmWindowManager::file_saved, ListBase::first, G, G_DEBUG_EVENTS, MEM_freeN(), NC_GEOM, NC_OBJECT, NC_SCENE, NC_SCREEN, NC_SPACE, NC_WM, ND_DATACHANGED, ND_FILEREAD, ND_FILESAVE, ND_FRAME, ND_SCREENBROWSE, ND_SCREENDELETE, ND_SPACE_INFO, wmNotifier::next, ScrArea::next, ARegion::next, next, wmWindow::next, NULL, wmWindowManager::queue, wmNotifier::reference, ScrArea::regionbase, bScreen::regionbase, bScreen::scene, scene_update_tagged(), wmWindow::screen, wmNotifier::window, wmWindowManager::windows, WM_event_add_notifier(), wm_notifier_next(), and wm_window_title().
Referenced by WM_main().
static void wm_event_drag_test (wmWindowManager * wm, wmWindow * win, wmEvent * event) [static]
Definition at line 1899 of file wm_event_system.c.
References BLI_freelistN(), wmEvent::customdata, wmEvent::customdatafree, bScreen::do_draw, bScreen::do_draw_drag, wmWindowManager::drags, wmWindow::drawmethod, ESCKEY, EVT_DATA_LISTBASE, EVT_DROP, ListBase::first, KM_RELEASE, LEFTMOUSE, MEM_freeN(), MOUSEMOVE, NULL, wmWindow::screen, wmEvent::type, USER_DRAW_OVERLAP, and wmEvent::val.
Referenced by wm_event_do_handlers().
void WM_event_fileselect_event (bContext * C, void * ophandle, int eventval)
Definition at line 2164 of file wm_event_system.c.
References CTX_wm_manager(), wmWindow::eventstate, EVT_FILESELECT, wmWindow::next, wmEvent::type, and wm_event_add().
Referenced by ED_fileselect_exit(), file_cancel_exec(), file_exec(), and WM_event_add_fileselect().
void wm_event_free (wmEvent * event)
Definition at line 98 of file wm_event_system.c.
References BLI_freelistN(), wmEvent::custom, wmEvent::customdata, wmEvent::customdatafree, EVT_DATA_LISTBASE, and MEM_freeN().
Referenced by StartKetsjiShell(), wm_event_do_handlers(), and wm_event_free_all().
void wm_event_free_all (wmWindow * win)
Definition at line 112 of file wm_event_system.c.
References BLI_remlink(), ListBase::first, wmWindow::queue, and wm_event_free().
Referenced by wm_event_do_handlers(), and wm_window_free().
void wm_event_free_handler (wmEventHandler * handler)
Definition at line 1129 of file wm_event_system.c.
References MEM_freeN().
Referenced by WM_event_add_fileselect(), WM_event_remove_area_handler(), WM_event_remove_handlers(), WM_event_remove_keymap_handler(), WM_event_remove_ui_handler(), wm_handler_fileselect_call(), wm_handler_operator_call(), wm_handlers_do(), and wm_macro_modal().
static int wm_event_inside_i (wmEvent * event, rcti * rect) [static]
Definition at line 1819 of file wm_event_system.c.
References BLI_in_rcti(), MOUSEMOVE, wmEvent::prevx, wmEvent::prevy, wmEvent::type, wm_event_always_pass(), wmEvent::x, and wmEvent::y.
Referenced by wm_event_do_handlers().
static void wm_event_modalkeymap (const bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1347 of file wm_event_system.c.
References CTX_wm_manager(), EVT_MODAL_MAP, ListBase::first, wmKeyMap::items, wmOperatorType::modalkeymap, wmKeyMapItem::next, wmOperator::opm, wmKeyMapItem::propvalue, wmKeyMapItem::type, wmOperator::type, wm_eventmatch(), and WM_keymap_active().
Referenced by wm_handler_operator_call().
void WM_event_print (wmEvent * event)
Definition at line 436 of file wm_event_system.c.
References wmEvent::alt, wmEvent::ascii, BLI_str_utf8_size(), wmEvent::ctrl, event_type_items, event_value_items, wmEvent::keymap_idname, wmEvent::keymodifier, wmEvent::oskey, RNA_enum_identifier(), wmEvent::shift, wmEvent::type, wmEvent::utf8_buf, wmEvent::val, wmEvent::x, and wmEvent::y.
void WM_event_remove_area_handler (ListBase * handlers, void * area)
Definition at line 2371 of file wm_event_system.c.
References BLI_remlink(), ListBase::first, wmEventHandler::next, wmEventHandler::type, wmEventHandler::ui_area, wm_event_free_handler(), and WM_HANDLER_FILESELECT.
Referenced by ED_screen_set().
void WM_event_remove_handlers (bContext * C, ListBase * handlers)
Definition at line 1169 of file wm_event_system.c.
References BLI_remlink(), wmOperatorType::cancel, CTX_wm_area(), CTX_wm_area_set(), CTX_wm_manager(), CTX_wm_menu(), CTX_wm_menu_set(), CTX_wm_region(), CTX_wm_region_set(), CTX_wm_window(), ListBase::first, wmOperatorType::flag, wmEventHandler::op, wmWindowManager::op_undo_depth, OPTYPE_UNDO, wmOperator::type, wmEventHandler::ui_area, wmEventHandler::ui_menu, wmEventHandler::ui_region, wmEventHandler::ui_remove, wmEventHandler::ui_userdata, WM_cursor_ungrab(), wm_event_free_handler(), wm_handler_op_context(), and WM_operator_free().
Referenced by clip_refresh(), ED_area_exit(), ED_region_exit(), ED_region_toggle_hidden(), sequencer_refresh(), WM_exit_ext(), wm_window_close(), wm_window_free(), and wm_window_match_init().
void WM_event_remove_keymap_handler (ListBase * handlers, wmKeyMap * keymap)
Definition at line 2302 of file wm_event_system.c.
References BLI_remlink(), ListBase::first, wmEventHandler::keymap, wmEventHandler::next, and wm_event_free_handler().
Referenced by WM_event_add_keymap_handler_priority().
void WM_event_remove_ui_handler (ListBase * handlers, wmUIHandlerFunc func, wmUIHandlerRemoveFunc remove, void * userdata, int postpone)
Definition at line 2332 of file wm_event_system.c.
References BLI_remlink(), ListBase::first, wmEventHandler::flag, wmEventHandler::next, wmEventHandler::ui_handle, wmEventHandler::ui_remove, wmEventHandler::ui_userdata, wm_event_free_handler(), and WM_HANDLER_DO_FREE.
Referenced by button_activate_state(), panel_activate_state(), UI_add_region_handlers(), and UI_remove_popup_handlers().
static void wm_eventemulation (wmEvent * event) [static]
Definition at line 1264 of file wm_event_system.c.
References wmEvent::alt, BACKSLASHKEY, EIGHTKEY, EQUALKEY, FIVEKEY, FOURKEY, KM_PRESS, LEFTMOUSE, MIDDLEMOUSE, MINUSKEY, NINEKEY, ONEKEY, wmEvent::oskey, PAD0, PAD1, PAD2, PAD3, PAD4, PAD5, PAD6, PAD7, PAD8, PAD9, PADMINUS, PADPLUSKEY, PADSLASHKEY, RIGHTMOUSE, SEVENKEY, SIXKEY, THREEKEY, TWOKEY, wmEvent::type, USER_NONUMPAD, USER_TWOBUTTONMOUSE, and ZEROKEY.
Referenced by wm_event_do_handlers().
static int wm_eventmatch (wmEvent * winevent, wmKeyMapItem * kmi) [static]
Definition at line 1308 of file wm_event_system.c.
References wmKeyMapItem::alt, wmEvent::alt, wmEvent::ascii, wmKeyMapItem::ctrl, wmEvent::ctrl, wmKeyMapItem::flag, ISTEXTINPUT, wmEvent::keymodifier, wmKeyMapItem::keymodifier, KM_ANY, KM_TEXTINPUT, KMI_INACTIVE, wmEvent::oskey, wmKeyMapItem::oskey, wmEvent::shift, wmKeyMapItem::shift, wmKeyMapItem::type, wmEvent::type, wmEvent::utf8_buf, wmKeyMapItem::val, wmEvent::val, and WM_userdef_event_map().
Referenced by wm_event_modalkeymap(), and wm_handlers_do().
static int wm_handler_fileselect_call (bContext * C, ListBase * handlers, wmEventHandler * handler, wmEvent * event) [static]
Definition at line 1464 of file wm_event_system.c.
References bScreen::areabase, BLI_movelisttolist(), BLI_remlink(), wmOperatorType::cancel, CTX_wm_area(), CTX_wm_area_set(), CTX_wm_manager(), CTX_wm_region(), CTX_wm_region_set(), CTX_wm_reports(), CTX_wm_screen(), CTX_wm_window(), CTX_wm_window_set(), wmEvent::customdata, ED_area_newspace(), ED_area_prevspace(), ED_fileselect_set_params(), ED_screen_full_newspace(), ED_screen_full_prevspace(), ED_undo_push_op(), EVT_FILESELECT, EVT_FILESELECT_CANCEL, EVT_FILESELECT_EXEC, EVT_FILESELECT_EXTERNAL_CANCEL, EVT_FILESELECT_FULL_OPEN, EVT_FILESELECT_OPEN, wmOperatorType::exec, wmEventHandler::filescreen, ListBase::first, wmOperatorType::flag, G, G_DEBUG_WM, ReportList::list, MEM_freeN(), NULL, SpaceFile::op, wmEventHandler::op, wmEventHandler::op_area, wmWindowManager::op_undo_depth, OPERATOR_FINISHED, OPTYPE_UNDO, ReportList::printlevel, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_string_get_alloc(), RNA_struct_find_property(), RPT_WARNING, SPACE_FILE, ScrArea::spacedata, wmOperator::type, wmEvent::type, uiPupMenuReports(), uiPupMenuSaveOver(), wmEvent::val, wm_event_free_handler(), WM_HANDLER_BREAK, WM_HANDLER_CONTINUE, wm_handler_op_context(), WM_operator_free(), WM_operator_last_properties_store(), and wm_operator_print().
Referenced by wm_handlers_do().
static void wm_handler_op_context (bContext * C, wmEventHandler * handler) [static]
Definition at line 1135 of file wm_event_system.c.
References bScreen::areabase, CTX_wm_area_set(), CTX_wm_region_set(), CTX_wm_screen(), ListBase::first, wmOperatorType::idname, ScrArea::next, ARegion::next, NULL, wmEventHandler::op, wmEventHandler::op_area, wmEventHandler::op_region, ScrArea::regionbase, and wmOperator::type.
Referenced by WM_event_remove_handlers(), wm_handler_fileselect_call(), and wm_handler_operator_call().
static int wm_handler_operator_call (bContext * C, ListBase * handlers, wmEventHandler * handler, wmEvent * event, PointerRNA * properties) [static]
Definition at line 1368 of file wm_event_system.c.
References BLI_remlink(), CTX_wm_area(), CTX_wm_area_set(), CTX_wm_manager(), CTX_wm_region(), CTX_wm_region_set(), CTX_wm_window(), FALSE, wmOperatorType::flag, wmEvent::keymap_idname, wmOperatorType::modal, NULL, wmEventHandler::op, wmWindowManager::op_undo_depth, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, OPERATOR_RETVAL_CHECK, OPERATOR_RUNNING_MODAL, OPTYPE_UNDO, wmOperator::type, WM_cursor_ungrab(), wm_event_always_pass(), wm_event_free_handler(), wm_event_modalkeymap(), WM_HANDLER_BREAK, WM_HANDLER_CONTINUE, WM_HANDLER_HANDLED, WM_HANDLER_MODAL, wm_handler_op_context(), wm_operator_finished(), WM_operator_free(), wm_operator_invoke(), wm_operator_reports(), WM_operatortype_find(), and wm_region_mouse_co().
Referenced by wm_handlers_do().
static int wm_handler_ui_call (bContext * C, wmEventHandler * handler, wmEvent * event, int always_pass) [static]
Definition at line 329 of file wm_event_system.c.
References CTX_wm_area(), CTX_wm_area_set(), CTX_wm_menu(), CTX_wm_menu_set(), CTX_wm_region(), CTX_wm_region_set(), ELEM, NULL, wmEvent::type, wmEventHandler::ui_area, wmEventHandler::ui_handle, wmEventHandler::ui_menu, wmEventHandler::ui_region, wmEventHandler::ui_userdata, WHEELDOWNMOUSE, WHEELUPMOUSE, wm_event_always_pass(), WM_HANDLER_BREAK, WM_HANDLER_CONTINUE, and WM_UI_HANDLER_BREAK.
Referenced by wm_handlers_do().
static void wm_handler_ui_cancel (bContext * C) [static]
Definition at line 377 of file wm_event_system.c.
References CTX_wm_region(), CTX_wm_window(), wmWindow::eventstate, EVT_BUT_CANCEL, ListBase::first, ARegion::handlers, wmEventHandler::next, wmEvent::type, wmEventHandler::ui_handle, and wmEventHandler::ui_userdata.
Referenced by wm_operator_invoke().
static int wm_handlers_do (bContext * C, wmEvent * event, ListBase * handlers) [static]
Definition at line 1659 of file wm_event_system.c.
References ABS, BLI_findindex(), BLI_freelistN(), BLI_remlink(), wmDropBox::copy, CTX_wm_manager(), CTX_wm_window(), wmEvent::custom, wmEvent::customdata, wmEventHandler::dropboxes, wmWindow::eventstate, EVT_DATA_LISTBASE, EVT_DROP, ListBase::first, wmEventHandler::flag, handler_boundbox_test(), wmOperatorType::idname, wmKeyMapItem::idname, wmKeyMap::items, wmEventHandler::keymap, KM_CLICK, KM_DBL_CLICK, KM_PRESS, KM_RELEASE, wmDropBox::next, wmKeyMapItem::next, wmEventHandler::next, NULL, wmDropBox::opcontext, wmDropBox::ot, PIL_check_seconds_timer(), wmDropBox::poll, wmKeyMap::poll, wmEvent::prevclicktime, wmEvent::prevclickx, wmEvent::prevclicky, wmEvent::prevtype, wmEvent::prevval, wmDropBox::ptr, wmKeyMapItem::ptr, wmEvent::type, wmEventHandler::type, wmEventHandler::ui_handle, wmEvent::val, wm_action_not_handled(), wm_cursor_arrow_move(), wm_event_always_pass(), wm_event_free_handler(), wm_eventmatch(), WM_HANDLER_BLOCKING, WM_HANDLER_BREAK, WM_HANDLER_CONTINUE, WM_HANDLER_DO_FREE, WM_HANDLER_FILESELECT, wm_handler_fileselect_call(), WM_HANDLER_MODAL, wm_handler_operator_call(), wm_handler_ui_call(), WM_keymap_active(), WM_operator_name_call(), wmEvent::x, and wmEvent::y.
Referenced by wm_event_do_handlers().
void WM_main_add_notifier (unsigned int type, void * reference)
Definition at line 156 of file wm_event_system.c.
References wmNotifier::action, BLI_addtail(), wmNotifier::category, wmNotifier::data, ListBase::first, G, MEM_callocN(), NOTE_ACTION, NOTE_CATEGORY, NOTE_DATA, NOTE_SUBTYPE, wmWindowManager::queue, wmNotifier::reference, wmNotifier::subtype, wmNotifier::wm, Main::wm, and wm_test_duplicate_notifier().
Referenced by ANIM_apply_keyingset(), armature_circle_select(), brush_generic_tool_set(), do_lasso_select_armature(), ED_node_changed_update(), ED_node_set_active(), ED_space_image_set(), ED_view3d_camera_lock_sync(), icon_preview_endjob(), make_paths_absolute_exec(), make_paths_relative_exec(), object_duplicates_make_real_exec(), pose_circle_select(), proxy_endjob(), render_endjob(), rna_property_update(), solve_camera_freejob(), track_markers_freejob(), viewRedrawPost(), weight_sample_invoke(), and WM_operator_stack_clear().
int WM_modal_tweak_exit (wmEvent * evt, int tweak_event)
Definition at line 2402 of file wm_event_system.c.
References ELEM3, EVT_TWEAK_L, EVT_TWEAK_M, EVT_TWEAK_R, KM_RELEASE, USER_RELEASECONFIRM, and wmEvent::val.
Referenced by ed_marker_move_modal().
static wmNotifier* wm_notifier_next (wmWindowManager * wm) [static]
Definition at line 176 of file wm_event_system.c.
References BLI_remlink(), ListBase::first, and wmWindowManager::queue.
Referenced by wm_event_do_notifiers().
int WM_operator_call (bContext * C, wmOperator * op)
Definition at line 621 of file wm_event_system.c.
References wm_operator_exec().
Referenced by dialog_exec_cb(), operator_cb(), and wm_operator_ui_popup_ok().
static int wm_operator_call_internal (bContext * C, wmOperatorType * ot, PointerRNA * properties, ReportList * reports, short context, short poll_only) [static]
Definition at line 955 of file wm_event_system.c.
References BKE_area_find_region_type(), CTX_wm_area(), CTX_wm_area_set(), CTX_wm_operator_poll_msg_set(), CTX_wm_region(), CTX_wm_region_set(), CTX_wm_window(), wmWindow::eventstate, NULL, ARegion::regiontype, RGN_TYPE_CHANNELS, RGN_TYPE_PREVIEW, RGN_TYPE_WINDOW, ARegion::type, WM_OP_EXEC_AREA, WM_OP_EXEC_DEFAULT, WM_OP_EXEC_REGION_CHANNELS, WM_OP_EXEC_REGION_PREVIEW, WM_OP_EXEC_REGION_WIN, WM_OP_EXEC_SCREEN, WM_OP_INVOKE_AREA, WM_OP_INVOKE_DEFAULT, WM_OP_INVOKE_REGION_CHANNELS, WM_OP_INVOKE_REGION_PREVIEW, WM_OP_INVOKE_REGION_WIN, WM_OP_INVOKE_SCREEN, and wm_operator_invoke().
Referenced by WM_operator_call_py(), WM_operator_name_call(), and WM_operator_poll_context().
int WM_operator_call_notest (bContext * C, wmOperator * op)
Definition at line 629 of file wm_event_system.c.
References wm_operator_exec_notest().
Referenced by wm_link_append_invoke(), and WM_operator_filesel().
int WM_operator_call_py (bContext * C, wmOperatorType * ot, int context, PointerRNA * properties, ReportList * reports)
Definition at line 1081 of file wm_event_system.c.
References CTX_wm_manager(), wmOperatorType::exec, FALSE, wmOperatorType::flag, ReportList::flag, wmOperatorType::name, wmWindowManager::op_undo_depth, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RETVAL_CHECK, OPERATOR_RUNNING_MODAL, OPTYPE_UNDO, RPT_FREE, wmOperator::type, wm_operator_call_internal(), wm_operator_create(), and wm_operator_register_check().
static wmOperator* wm_operator_create (wmWindowManager * wm, wmOperatorType * ot, PointerRNA * properties, ReportList * reports) [static]
Definition at line 648 of file wm_event_system.c.
References BKE_reports_init(), BLI_addtail(), BLI_strncpy(), PointerRNA::data, ListBase::first, wmWindowManager::id, wmOperatorTypeMacro::idname, wmOperator::idname, wmOperatorType::idname, IDP_CopyProperty(), IDP_GROUP, IDP_New(), IDP_ReplaceGroupInGroup(), wmOperator::macro, wmOperatorType::macro, MEM_callocN(), MEM_mallocN(), wmOperatorTypeMacro::next, NULL, OP_MAX_TYPENAME, wmOperator::opm, wmOperatorTypeMacro::properties, wmOperator::properties, wmOperatorTypeMacro::ptr, wmOperator::ptr, wmOperator::reports, RNA_pointer_create(), RNA_property_identifier(), RNA_property_pointer_get(), RNA_STRUCT_BEGIN, RNA_STRUCT_END, RPT_FREE, RPT_STORE, wmOperatorType::srna, wmOperator::type, WM_operator_properties_sanitize(), and WM_operatortype_find().
Referenced by WM_operator_call_py(), and wm_operator_invoke().
static int wm_operator_exec (bContext * C, wmOperator * op, int repeat) [static]
Definition at line 561 of file wm_event_system.c.
References CTX_wm_manager(), CTX_wm_operator_poll_msg_set(), wmOperatorType::exec, FALSE, wmOperatorType::flag, NULL, wmWindowManager::op_undo_depth, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_HANDLED, OPERATOR_RETVAL_CHECK, OPTYPE_UNDO, wmOperator::type, wm_operator_finished(), WM_operator_free(), WM_operator_last_properties_store(), WM_operator_poll(), and wm_operator_reports().
Referenced by WM_operator_call(), and WM_operator_repeat().
static int wm_operator_exec_notest (bContext * C, wmOperator * op) [static]
Definition at line 605 of file wm_event_system.c.
References wmOperatorType::exec, NULL, OPERATOR_CANCELLED, OPERATOR_RETVAL_CHECK, and wmOperator::type.
Referenced by WM_operator_call_notest().
static void wm_operator_finished (bContext * C, wmOperator * op, int repeat) [static]
Definition at line 533 of file wm_event_system.c.
References BKE_report(), CTX_wm_manager(), CTX_wm_reports(), wmOperator::customdata, ED_undo_push_op(), wmOperatorType::flag, G, G_DEBUG_WM, MEM_freeN(), NULL, wmWindowManager::op_undo_depth, OPTYPE_UNDO, wmOperator::ptr, RPT_OPERATOR, wmOperator::type, WM_operator_free(), WM_operator_pystring(), wm_operator_register(), and wm_operator_register_check().
Referenced by wm_handler_operator_call(), wm_operator_exec(), and wm_operator_invoke().
static int wm_operator_invoke (bContext * C, wmOperatorType * ot, wmEvent * event, PointerRNA * properties, ReportList * reports, short poll_only) [static]
Definition at line 823 of file wm_event_system.c.
References BLI_in_rcti(), bounds(), CTX_wm_area(), CTX_wm_manager(), CTX_wm_region(), CTX_wm_screen(), CTX_wm_window(), wmOperatorType::exec, FALSE, wmOperator::flag, wmOperatorType::flag, G, G_DEBUG_EVENTS, wmOperatorType::idname, wmOperatorType::invoke, MOUSEMOVE, NULL, OP_GRAB_POINTER, wmWindowManager::op_undo_depth, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_HANDLED, OPERATOR_PASS_THROUGH, OPERATOR_RETVAL_CHECK, OPERATOR_RUNNING_MODAL, wmOperator::opm, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, OPTYPE_UNDO, ARegion::regiontype, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, ScrArea::totrct, wmOperator::type, wmEvent::type, USER_CONTINUOUS_MOUSE, ARegion::winrct, WM_cursor_grab(), wm_handler_ui_cancel(), wm_operator_create(), wm_operator_finished(), WM_operator_free(), WM_operator_last_properties_init(), WM_operator_last_properties_store(), WM_operator_poll(), wm_operator_reports(), wm_region_mouse_co(), wmEvent::x, rcti::xmax, rcti::xmin, wmEvent::y, rcti::ymax, and rcti::ymin.
Referenced by wm_handler_operator_call(), and wm_operator_call_internal().
int WM_operator_last_properties_init (wmOperator * UNUSEDop)
Definition at line 811 of file wm_event_system.c.
References FALSE.
Referenced by wm_operator_invoke().
int WM_operator_last_properties_store (wmOperator * UNUSEDop)
Definition at line 816 of file wm_event_system.c.
References FALSE.
Referenced by wm_handler_fileselect_call(), wm_operator_exec(), and wm_operator_invoke().
int WM_operator_name_call (bContext * C, const char * opstring, int context, PointerRNA * properties)
Definition at line 1067 of file wm_event_system.c.
References FALSE, NULL, wm_operator_call_internal(), and WM_operatortype_find().
Referenced by BIF_do_manipulator(), console_main_area_draw(), console_paste_exec(), do_outliner_item_activate(), do_outliner_operation_event(), do_running_jobs(), do_view3d_header_buttons(), duplicate_metaelems_invoke(), ED_object_toggle_modes(), file_browse_invoke(), file_panel_cb(), file_smoothscroll_invoke(), ghost_event_proc(), mouse_nla_strips(), nlaedit_duplicate_invoke(), nlaedit_select_leftright(), node_render_changed_exec(), node_toggle_button_cb(), object_mode_set_exec(), object_mouse_select_menu(), operator_call_cb(), operator_enum_call_cb(), operator_name_cb(), outliner_animdata_operation_exec(), pyop_call(), report_replay_exec(), sequencer_add_duplicate_invoke(), ui_add_smart_controller(), ui_apply_but_funcs_after(), ui_but_anim_add_driver(), ui_but_anim_add_keyingset(), ui_but_anim_copy_driver(), ui_but_anim_delete_keyframe(), ui_but_anim_insert_keyframe(), ui_but_anim_paste_driver(), ui_but_anim_remove_driver(), ui_but_anim_remove_keyingset(), ui_handler_popup(), ui_set_but_default(), view_pan_modal(), viewdolly_modal(), viewmove_modal(), viewrotate_modal(), viewzoom_modal(), wm_handlers_do(), WM_init_game(), and WM_init_splash().
int WM_operator_poll (bContext * C, wmOperatorType * ot)
Definition at line 399 of file wm_event_system.c.
References ListBase::first, wmOperatorTypeMacro::idname, wmOperatorType::macro, wmOperatorTypeMacro::next, wmOperatorType::poll, wmOperatorType::pyop_poll, WM_operator_poll(), and WM_operatortype_find().
Referenced by clip_panel_operator_redo(), ED_undo_operator_repeat(), operator_search_cb(), view3d_panel_operator_redo(), wm_operator_exec(), wm_operator_invoke(), and WM_operator_poll().
int WM_operator_poll_context (bContext * C, wmOperatorType * ot, int context)
Definition at line 420 of file wm_event_system.c.
References NULL, TRUE, and wm_operator_call_internal().
Referenced by pyop_call(), pyop_poll(), ui_tooltip_create(), and uiEndBlock().
static void wm_operator_print (bContext * C, wmOperator * op) [static]
Definition at line 425 of file wm_event_system.c.
References MEM_freeN(), wmOperator::ptr, wmOperator::type, and WM_operator_pystring().
Referenced by wm_handler_fileselect_call(), and wm_operator_reports().
static int wm_operator_register_check (wmWindowManager * wm, wmOperatorType * ot) [static]
Definition at line 528 of file wm_event_system.c.
References wmOperatorType::flag, wmWindowManager::op_undo_depth, and OPTYPE_REGISTER.
Referenced by WM_operator_call_py(), and wm_operator_finished().
int WM_operator_repeat (bContext * C, wmOperator * op)
Definition at line 635 of file wm_event_system.c.
References wm_operator_exec().
Referenced by ED_undo_operator_repeat(), repeat_history_exec(), and repeat_last_exec().
int WM_operator_repeat_check (const bContext * UNUSEDC, wmOperator * op)
Definition at line 643 of file wm_event_system.c.
References wmOperatorType::exec, NULL, and wmOperator::type.
Referenced by ED_undo_operator_repeat(), and uiLayoutOperatorButs().
static void wm_operator_reports (bContext * C, wmOperator * op, int retval, int caller_owns_reports) [static]
Definition at line 464 of file wm_event_system.c.
References BKE_report(), BKE_reports_print(), BLI_movelisttolist(), CTX_wm_area(), CTX_wm_area_set(), CTX_wm_manager(), CTX_wm_region(), CTX_wm_region_set(), CTX_wm_reports(), CTX_wm_window(), CTX_wm_window_set(), wmTimer::customdata, FALSE, ListBase::first, ReportList::flag, wmOperatorType::flag, G, G_DEBUG_WM, ReportList::list, MEM_callocN(), MEM_freeN(), NULL, OPERATOR_FINISHED, OPTYPE_REGISTER, wmOperator::ptr, wmOperator::reports, ReportList::reporttimer, RPT_DEBUG, RPT_OP_HOLD, RPT_OPERATOR, TIMERREPORT, wmOperator::type, uiPupMenuReports(), WM_event_add_timer(), WM_event_remove_timer(), wm_operator_print(), and WM_operator_pystring().
Referenced by wm_handler_operator_call(), wm_operator_exec(), and wm_operator_invoke().
static void wm_paintcursor_tag (bContext * C, wmPaintCursor * pc, ARegion * ar) [static]
Definition at line 1859 of file wm_event_system.c.
References CTX_wm_window(), bScreen::do_draw_paintcursor, wmPaintCursor::next, NULL, wmPaintCursor::poll, wmWindow::screen, and wm_tag_redraw_overlay().
Referenced by wm_paintcursor_test().
static void wm_paintcursor_test (bContext * C, wmEvent * event) [static]
Definition at line 1874 of file wm_event_system.c.
References area_event_inside(), BLI_in_rcti(), CTX_wm_area(), CTX_wm_area_set(), CTX_wm_manager(), CTX_wm_region(), CTX_wm_region_set(), ListBase::first, NULL, wmWindowManager::paintcursors, wmEvent::prevx, wmEvent::prevy, region_event_inside(), ARegion::winrct, and wm_paintcursor_tag().
Referenced by wm_event_do_handlers().
static void wm_region_mouse_co (bContext * C, wmEvent * event) [static]
Definition at line 735 of file wm_event_system.c.
References CTX_wm_region(), ARegion::winrct, rcti::xmin, and rcti::ymin.
Referenced by wm_event_do_handlers(), wm_handler_operator_call(), and wm_operator_invoke().
static int wm_test_duplicate_notifier (wmWindowManager * wm, unsigned int type, void * reference) [static]
Definition at line 124 of file wm_event_system.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ListBase::first, wmNotifier::next, wmWindowManager::queue, wmNotifier::reference, and wmNotifier::subtype.
Referenced by WM_main_add_notifier().
int WM_userdef_event_map (int kmitype)
Definition at line 1221 of file wm_event_system.c.
References ACTIONMOUSE, EVT_TWEAK_A, EVT_TWEAK_L, EVT_TWEAK_R, EVT_TWEAK_S, LEFTMOUSE, RIGHTMOUSE, SELECTMOUSE, USER_LMOUSESELECT, USER_WHEELZOOMDIR, WHEELDOWNMOUSE, WHEELINMOUSE, WHEELOUTMOUSE, and WHEELUPMOUSE.
Referenced by wm_eventmatch(), and WM_keymap_item_compare().