Blender: mmd.c File Reference
mmd.c File Reference
opennl
Typedefs
typedef int shortint
Functions
int genmmd_ (int *, int *, int *, int *, int *, int *, int *, int *, int *, int *, int *, int *)
int mmdint_ (int *, int *, shortint *, shortint *, shortint *, shortint *, shortint *, shortint *, shortint *)
int mmdelm_ (int *, int *, shortint *, shortint *, shortint *, shortint *, shortint *, shortint *, shortint *, int *, int *)
int mmdupd_ (int *, int *, int *, shortint *, int *, int *, shortint *, shortint *, shortint *, shortint *, shortint *, shortint *, int *, int *)
int mmdnum_ (int *, shortint *, shortint *, shortint *)
Detailed Description
Definition in file mmd.c.
Typedef Documentation
typedef int shortint
Definition at line 5 of file mmd.c.
Function Documentation
int genmmd_ (int * neqns, int * xadj, int * adjncy, int * invp, int * perm, int * delta, int * dhead, int * qsize, int * llist, int * marker, int * maxint, int * nofsub)
Definition at line 67 of file mmd.c.
References i, mmdelm_(), mmdint_(), mmdnum_(), and mmdupd_().
Referenced by get_perm_c().
int mmdelm_ (int * mdnode, int * xadj, shortint * adjncy, shortint * dhead, shortint * dforw, shortint * dbakw, shortint * qsize, shortint * llist, shortint * marker, int * maxint, int * tag)
Definition at line 338 of file mmd.c.
References i, and link().
Referenced by genmmd_().
int mmdint_ (int * neqns, int * xadj, shortint * adjncy, shortint * dhead, shortint * dforw, shortint * dbakw, shortint * qsize, shortint * llist, shortint * marker)
Definition at line 254 of file mmd.c.
Referenced by genmmd_().
int mmdnum_ (int * neqns, shortint * perm, shortint * invp, shortint * qsize)
Definition at line 941 of file mmd.c.
Referenced by genmmd_().
int mmdupd_ (int * ehead, int * neqns, int * xadj, shortint * adjncy, int * delta, int * mdeg, shortint * dhead, shortint * dforw, shortint * dbakw, shortint * qsize, shortint * llist, shortint * marker, int * maxint, int * tag)
Definition at line 585 of file mmd.c.
References i, and link().
Referenced by genmmd_().