Blender: btSoftBodyRigidBodyCollisionConfiguration Class Reference
btSoftBodyRigidBodyCollisionConfiguration Class Reference
btSoftBodyRigidBodyCollisionConfiguration add softbody interaction on top of btDefaultCollisionConfiguration
#include <btSoftBodyRigidBodyCollisionConfiguration.h>
Public Member Functions
btSoftBodyRigidBodyCollisionConfiguration (const btDefaultCollisionConstructionInfo &constructionInfo=btDefaultCollisionConstructionInfo())
virtual ~btSoftBodyRigidBodyCollisionConfiguration ()
virtual
btCollisionAlgorithmCreateFunc * getCollisionAlgorithmCreateFunc (int proxyType0, int proxyType1)
creation of soft-soft and soft-rigid, and otherwise fallback to base class implementation
Detailed Description
btSoftBodyRigidBodyCollisionConfiguration add softbody interaction on top of btDefaultCollisionConfiguration
Definition at line 26 of file btSoftBodyRigidBodyCollisionConfiguration.h.
Constructor & Destructor Documentation
btSoftBodyRigidBodyCollisionConfiguration::btSoftBodyRigidBodyCollisionConfiguration (const btDefaultCollisionConstructionInfo & constructionInfo = btDefaultCollisionConstructionInfo())
calculate maximum element size, big enough to fit any collision algorithm in the memory pool
Definition at line 25 of file btSoftBodyRigidBodyCollisionConfiguration.cpp.
References btAlignedAlloc, btAlignedFree, btMax(), btPoolAllocator::getElementSize(), btDefaultCollisionConfiguration::m_collisionAlgorithmPool, btDefaultCollisionConstructionInfo::m_defaultMaxCollisionAlgorithmPoolSize, btDefaultCollisionConfiguration::m_ownsCollisionAlgorithmPool, btCollisionAlgorithmCreateFunc::m_swapped, and btPoolAllocator::~btPoolAllocator().
btSoftBodyRigidBodyCollisionConfiguration::~btSoftBodyRigidBodyCollisionConfiguration () [virtual]
Definition at line 75 of file btSoftBodyRigidBodyCollisionConfiguration.cpp.
References btAlignedFree, and btCollisionAlgorithmCreateFunc::~btCollisionAlgorithmCreateFunc().
Member Function Documentation
btCollisionAlgorithmCreateFunc * btSoftBodyRigidBodyCollisionConfiguration::getCollisionAlgorithmCreateFunc (int proxyType0, int proxyType1) [virtual]
creation of soft-soft and soft-rigid, and otherwise fallback to base class implementation
try to handle the softbody interactions first
softbody versus convex
convex versus soft body
softbody versus convex
convex versus soft body
fallback to the regular rigid collision shape
Reimplemented from btDefaultCollisionConfiguration.
Definition at line 96 of file btSoftBodyRigidBodyCollisionConfiguration.cpp.
References SOFTBODY_SHAPE_PROXYTYPE.
The documentation for this class was generated from the following files:
btSoftBodyRigidBodyCollisionConfiguration.h
btSoftBodyRigidBodyCollisionConfiguration.cpp