Blender: sequencer_edit.c File Reference
sequencer_edit.c File Reference
sequencer
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BLI_threads.h"
#include "DNA_scene_types.h"
#include "DNA_userdef_types.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_sequencer.h"
#include "BKE_report.h"
#include "BKE_sound.h"
#include "BKE_movieclip.h"
#include "IMB_imbuf.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "ED_screen.h"
#include "ED_transform.h"
#include "ED_sequencer.h"
#include "UI_view2d.h"
#include "sequencer_intern.h"
Classes
struct TransSeq
struct ProxyBuildJob
Typedefs
typedef struct TransSeq TransSeq
typedef struct ProxyBuildJob ProxyJob
Functions
static void proxy_freejob (void *pjv)
static void proxy_startjob (void *pjv, short *stop, short *do_update, float *progress)
static void proxy_endjob (void *pjv)
static void seq_proxy_build_job (const bContext *C)
void seq_rectf (Sequence *seq, rctf *rectf)
static void UNUSED_FUNCTION() change_plugin_seq (Scene *scene, char *str)
void boundbox_seq (Scene *scene, rctf *rect)
static int mouse_frame_side (View2D *v2d, short mouse_x, int frame)
Sequence * find_neighboring_sequence (Scene *scene, Sequence *test, int lr, int sel)
static Sequence * find_next_prev_sequence (Scene *scene, Sequence *test, int lr, int sel)
Sequence * find_nearest_seq (Scene *scene, View2D *v2d, int *hand, const int mval[2])
static int seq_is_parent (Sequence *par, Sequence *seq)
static int seq_is_predecessor (Sequence *pred, Sequence *seq)
void deselect_all_seq (Scene *scene)
void recurs_sel_seq (Sequence *seqm)
int seq_effect_find_selected (Scene *scene, Sequence *activeseq, int type, Sequence **selseq1, Sequence **selseq2, Sequence **selseq3, const char **error_str)
static Sequence * del_seq_find_replace_recurs (Scene *scene, Sequence *seq)
static void recurs_del_seq_flag (Scene *scene, ListBase *lb, short flag, short deleteall)
static Sequence * cut_seq_hard (Scene *scene, Sequence *seq, int cutframe)
static Sequence * cut_seq_soft (Scene *scene, Sequence *seq, int cutframe)
static int cut_seq_list (Scene *scene, ListBase *old, ListBase *new, int cutframe, Sequence *(*cut_seq)(Scene *, Sequence *, int))
static int insert_gap (Scene *scene, int gap, int cfra)
static void UNUSED_FUNCTION() touch_seq_files (Scene *scene)
static void UNUSED_FUNCTION() seq_remap_paths (Scene *scene)
static void UNUSED_FUNCTION() no_gaps (Scene *scene)
int sequencer_edit_poll (bContext *C)
int sequencer_strip_has_path_poll (bContext *C)
int sequencer_view_poll (bContext *C)
static int sequencer_snap_exec (bContext *C, wmOperator *op)
static int sequencer_snap_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void SEQUENCER_OT_snap (struct wmOperatorType *ot)
static int sequencer_mute_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_mute (struct wmOperatorType *ot)
static int sequencer_unmute_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_unmute (struct wmOperatorType *ot)
static int sequencer_lock_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_lock (struct wmOperatorType *ot)
static int sequencer_unlock_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_unlock (struct wmOperatorType *ot)
static int sequencer_reload_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_reload (struct wmOperatorType *ot)
static int sequencer_refresh_all_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_refresh_all (struct wmOperatorType *ot)
static int sequencer_reassign_inputs_exec (bContext *C, wmOperator *op)
static int sequencer_effect_poll (bContext *C)
void SEQUENCER_OT_reassign_inputs (struct wmOperatorType *ot)
static int sequencer_swap_inputs_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_swap_inputs (struct wmOperatorType *ot)
static int sequencer_cut_exec (bContext *C, wmOperator *op)
static int sequencer_cut_invoke (bContext *C, wmOperator *op, wmEvent *event)
void SEQUENCER_OT_cut (struct wmOperatorType *ot)
static int apply_unique_name_cb (Sequence *seq, void *arg_pt)
static int sequencer_add_duplicate_exec (bContext *C, wmOperator *UNUSED(op))
static int sequencer_add_duplicate_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void SEQUENCER_OT_duplicate (wmOperatorType *ot)
static int sequencer_delete_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_delete (wmOperatorType *ot)
static int sequencer_offset_clear_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_offset_clear (wmOperatorType *ot)
static int sequencer_separate_images_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_images_separate (wmOperatorType *ot)
static int sequencer_meta_toggle_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_meta_toggle (wmOperatorType *ot)
static int sequencer_meta_make_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_meta_make (wmOperatorType *ot)
static int seq_depends_on_meta (Sequence *seq, Sequence *seqm)
static int sequencer_meta_separate_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_meta_separate (wmOperatorType *ot)
static int sequencer_view_all_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_view_all (wmOperatorType *ot)
static int sequencer_view_all_preview_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_view_all_preview (wmOperatorType *ot)
static int sequencer_view_zoom_ratio_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_view_zoom_ratio (wmOperatorType *ot)
static int sequencer_view_toggle_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_view_toggle (wmOperatorType *ot)
static int sequencer_view_selected_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_view_selected (wmOperatorType *ot)
static int find_next_prev_edit (Scene *scene, int cfra, int side)
static int next_prev_edit_internal (Scene *scene, int side)
static int sequencer_next_edit_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_next_edit (wmOperatorType *ot)
static int sequencer_previous_edit_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_previous_edit (wmOperatorType *ot)
static void swap_sequence (Scene *scene, Sequence *seqa, Sequence *seqb)
static int sequencer_swap_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_swap (wmOperatorType *ot)
static int sequencer_rendersize_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_rendersize (wmOperatorType *ot)
static void seq_copy_del_sound (Scene *scene, Sequence *seq)
static int sequencer_copy_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_copy (wmOperatorType *ot)
static void seq_paste_add_sound (Scene *scene, Sequence *seq)
static int sequencer_paste_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_paste (wmOperatorType *ot)
static int sequencer_swap_data_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_swap_data (wmOperatorType *ot)
static int view_ghost_border_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_view_ghost_border (wmOperatorType *ot)
static int sequencer_rebuild_proxy_exec (bContext *C, wmOperator *UNUSED(op))
void SEQUENCER_OT_rebuild_proxy (wmOperatorType *ot)
static int sequencer_change_effect_input_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_change_effect_input (struct wmOperatorType *ot)
static int sequencer_change_effect_type_exec (bContext *C, wmOperator *op)
void SEQUENCER_OT_change_effect_type (struct wmOperatorType *ot)
static int sequencer_change_path_exec (bContext *C, wmOperator *op)
static int sequencer_change_path_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void SEQUENCER_OT_change_path (struct wmOperatorType *ot)
Variables
EnumPropertyItem sequencer_prop_effect_types []
EnumPropertyItem prop_side_types []
static EnumPropertyItem prop_side_lr_types []
static EnumPropertyItem prop_cut_types []
static EnumPropertyItem prop_change_effect_input_types []
Detailed Description
Definition in file sequencer_edit.c.
Typedef Documentation
typedef struct ProxyBuildJob ProxyJob
typedef struct TransSeq TransSeq
Function Documentation
static int apply_unique_name_cb (Sequence * seq, void * arg_pt) [static]
Definition at line 1553 of file sequencer_edit.c.
References Scene::ed, Sequence::name, seq_dupe_animdata(), Editing::seqbase, and seqbase_unique_name_recursive().
Referenced by sequencer_add_duplicate_exec(), sequencer_copy_exec(), and sequencer_paste_exec().
void boundbox_seq (Scene * scene, rctf * rect)
Definition at line 255 of file sequencer_edit.c.
References EFRA, Sequence::enddisp, FALSE, ListBase::first, Sequence::machine, max, min, Sequence::next, NULL, seq_give_editing(), Editing::seqbasep, Sequence::startdisp, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by draw_timeline_seq().
static void UNUSED_FUNCTION() change_plugin_seq (Scene * scene, char * str) [static]
Definition at line 234 of file sequencer_edit.c.
References FALSE, SeqEffectHandle::free, get_sequence_effect(), SeqEffectHandle::init_plugin, MAX3(), NULL, SeqIndexBuildContext::scene, seq_active_get(), seq_give_editing(), SEQ_PLUGIN, seq_test_overlap(), Editing::seqbasep, shuffle_seq(), and str.
static Sequence* cut_seq_hard (Scene * scene, Sequence * seq, int cutframe) [static]
Definition at line 616 of file sequencer_edit.c.
References Sequence::anim_endofs, TransSeq::anim_endofs, Sequence::anim_startofs, TransSeq::anim_startofs, calc_sequence(), Sequence::enddisp, TransSeq::enddisp, Sequence::endofs, TransSeq::endofs, Sequence::endstill, TransSeq::endstill, FALSE, Sequence::flag, Sequence::len, TransSeq::len, Sequence::machine, TransSeq::machine, NULL, reload_sequence_new_file(), SELECT, SEQ_DUPE_ANIM, SEQ_DUPE_UNIQUE_NAME, seq_dupli_recursive(), SEQ_META, Sequence::start, TransSeq::start, Sequence::startdisp, TransSeq::startdisp, Sequence::startofs, TransSeq::startofs, Sequence::startstill, TransSeq::startstill, TRUE, and Sequence::type.
Referenced by sequencer_cut_exec().
static int cut_seq_list (Scene * scene, ListBase * old, ListBase * new, int cutframe, Sequence *(*)(Scene *, Sequence *, int) cut_seq) [static]
Definition at line 803 of file sequencer_edit.c.
References BLI_addtail(), BLI_remlink(), Sequence::enddisp, FALSE, ListBase::first, Sequence::flag, Sequence::next, NULL, SELECT, Sequence::startdisp, Sequence::tmp, and TRUE.
Referenced by sequencer_cut_exec().
static Sequence* cut_seq_soft (Scene * scene, Sequence * seq, int cutframe) [static]
Definition at line 712 of file sequencer_edit.c.
References Sequence::anim_endofs, TransSeq::anim_endofs, Sequence::anim_startofs, TransSeq::anim_startofs, calc_sequence(), Sequence::enddisp, TransSeq::enddisp, Sequence::endofs, TransSeq::endofs, Sequence::endstill, TransSeq::endstill, FALSE, Sequence::flag, Sequence::len, TransSeq::len, Sequence::machine, TransSeq::machine, NULL, SELECT, SEQ_DUPE_ANIM, SEQ_DUPE_UNIQUE_NAME, seq_dupli_recursive(), SEQ_META, Sequence::start, TransSeq::start, Sequence::startdisp, TransSeq::startdisp, Sequence::startofs, TransSeq::startofs, Sequence::startstill, TransSeq::startstill, TRUE, and Sequence::type.
Referenced by sequencer_cut_exec().
static Sequence* del_seq_find_replace_recurs (Scene * scene, Sequence * seq) [static]
Definition at line 558 of file sequencer_edit.c.
References Sequence::flag, NULL, SELECT, Sequence::seq1, Sequence::seq2, Sequence::seq3, SEQ_EFFECT, Sequence::type, and update_changed_seq_and_deps().
Referenced by sequencer_delete_exec().
void deselect_all_seq (Scene * scene)
Definition at line 457 of file sequencer_edit.c.
References FALSE, Sequence::flag, NULL, SEQ_ALLSEL, SEQ_END, seq_give_editing(), and SEQP_BEGIN.
Referenced by select_single_seq(), sequencer_add_effect_strip_exec(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_paste_exec(), sequencer_select_invoke(), and sequencer_select_linked_pick_invoke().
Sequence* find_nearest_seq (Scene * scene, View2D * v2d, int * hand, const int mval[2]) [read]
Definition at line 382 of file sequencer_edit.c.
References abs(), CLAMP(), View2D::cur, Sequence::enddisp, FALSE, ListBase::first, Sequence::handsize, Sequence::machine, View2D::mask, Sequence::next, NULL, seq_give_editing(), SEQ_SIDE_LEFT, SEQ_SIDE_NONE, SEQ_SIDE_RIGHT, seq_tx_test(), Editing::seqbasep, Sequence::startdisp, UI_view2d_region_to_view(), rcti::xmax, rctf::xmax, rcti::xmin, and rctf::xmin.
Referenced by sequencer_select_invoke(), and sequencer_select_linked_pick_invoke().
Sequence* find_neighboring_sequence (Scene * scene, Sequence * test, int lr, int sel) [read]
Definition at line 301 of file sequencer_edit.c.
References Sequence::enddisp, FALSE, ListBase::first, Sequence::flag, Sequence::machine, Sequence::next, NULL, SELECT, seq_give_editing(), SEQ_SIDE_LEFT, SEQ_SIDE_RIGHT, Editing::seqbasep, and Sequence::startdisp.
Referenced by select_more_less_seq__internal(), select_surrounding_handles(), and sequencer_select_invoke().
static int find_next_prev_edit (Scene * scene, int cfra, int side) [static]
Definition at line 2299 of file sequencer_edit.c.
References Sequence::enddisp, FALSE, ListBase::first, MAXFRAME, Sequence::next, NULL, seq_give_editing(), SEQ_SIDE_LEFT, SEQ_SIDE_RIGHT, Editing::seqbasep, and Sequence::startdisp.
Referenced by next_prev_edit_internal().
static Sequence* find_next_prev_sequence (Scene * scene, Sequence * test, int lr, int sel) [static]
Definition at line 333 of file sequencer_edit.c.
References Sequence::depth, Sequence::enddisp, FALSE, ListBase::first, Sequence::flag, Sequence::machine, MAXFRAME, Sequence::next, NULL, SELECT, seq_give_editing(), SEQ_SIDE_LEFT, SEQ_SIDE_RIGHT, Editing::seqbasep, and Sequence::startdisp.
Referenced by sequencer_swap_exec().
static int insert_gap (Scene * scene, int gap, int cfra) [static]
Definition at line 839 of file sequencer_edit.c.
References calc_sequence(), FALSE, NULL, SEQ_END, seq_give_editing(), SEQP_BEGIN, Sequence::start, and Sequence::startdisp.
Referenced by no_gaps().
static int mouse_frame_side (View2D * v2d, short mouse_x, int frame) [static]
Definition at line 286 of file sequencer_edit.c.
References SEQ_SIDE_LEFT, SEQ_SIDE_RIGHT, and UI_view2d_region_to_view().
Referenced by sequencer_cut_invoke().
static int next_prev_edit_internal (Scene * scene, int side) [static]
Definition at line 2342 of file sequencer_edit.c.
References CFRA, and find_next_prev_edit().
Referenced by sequencer_next_edit_exec(), and sequencer_previous_edit_exec().
static void UNUSED_FUNCTION() no_gaps (Scene * scene) [static]
Definition at line 960 of file sequencer_edit.c.
References CFRA, EFRA, evaluate_seq_frame(), FALSE, insert_gap(), NULL, and seq_give_editing().
static void proxy_endjob (void * pjv) [static]
Definition at line 164 of file sequencer_edit.c.
References LinkData::data, FALSE, ListBase::first, free_imbuf_seq(), link(), NC_SCENE, ND_SEQUENCER, LinkData::next, ProxyBuildJob::queue, ProxyBuildJob::scene, seq_give_editing(), seq_proxy_rebuild_finish(), Editing::seqbase, ProxyBuildJob::stop, and WM_main_add_notifier().
Referenced by seq_proxy_build_job().
static void proxy_freejob (void * pjv) [static]
Definition at line 137 of file sequencer_edit.c.
References BLI_freelistN(), MEM_freeN(), and ProxyBuildJob::queue.
Referenced by seq_proxy_build_job().
static void proxy_startjob (void * pjv, short * stop, short * do_update, float * progress) [static]
Definition at line 147 of file sequencer_edit.c.
References LinkData::data, ListBase::first, link(), LinkData::next, ProxyBuildJob::queue, seq_proxy_rebuild(), and ProxyBuildJob::stop.
Referenced by seq_proxy_build_job().
static void recurs_del_seq_flag (Scene * scene, ListBase * lb, short flag, short deleteall) [static]
Definition at line 597 of file sequencer_edit.c.
References BLI_remlink(), ListBase::first, Sequence::flag, Sequence::next, NULL, seq_active_get(), seq_active_set(), seq_free_sequence(), SEQ_META, Sequence::seqbase, and Sequence::type.
Referenced by sequencer_delete_exec(), and sequencer_meta_separate_exec().
void recurs_sel_seq (Sequence * seqm)
Definition at line 473 of file sequencer_edit.c.
References ListBase::first, Sequence::flag, Sequence::next, recurs_sel_seq(), SELECT, SEQ_ALLSEL, SEQ_LEFTSEL, SEQ_RIGHTSEL, and Sequence::seqbase.
Referenced by recurs_sel_seq(), select_linked_time(), select_more_less_seq__internal(), select_single_seq(), select_surrounding_handles(), sequencer_borderselect_exec(), sequencer_meta_toggle_exec(), sequencer_select_invoke(), and sequencer_select_linked_pick_invoke().
static void seq_copy_del_sound (Scene * scene, Sequence * seq) [static]
Definition at line 2579 of file sequencer_edit.c.
References ListBase::first, Sequence::next, NULL, Sequence::scene_sound, SEQ_META, Sequence::seqbase, sound_remove_scene_sound(), and Sequence::type.
Referenced by sequencer_copy_exec().
static int seq_depends_on_meta (Sequence * seq, Sequence * seqm) [static]
Definition at line 1975 of file sequencer_edit.c.
References Sequence::seq1, Sequence::seq2, and Sequence::seq3.
Referenced by sequencer_meta_separate_exec().
int seq_effect_find_selected (Scene * scene, Sequence * activeseq, int type, Sequence ** selseq1, Sequence ** selseq2, Sequence ** selseq3, const char ** error_str)
Definition at line 490 of file sequencer_edit.c.
References FALSE, ListBase::first, get_sequence_effect_num_inputs(), NULL, SELECT, seq_active_get(), seq_give_editing(), SEQ_SOUND, and Editing::seqbasep.
Referenced by sequencer_add_effect_strip_exec(), and sequencer_reassign_inputs_exec().
static int seq_is_parent (Sequence * par, Sequence * seq) [static]
Definition at line 440 of file sequencer_edit.c.
References Sequence::seq1, Sequence::seq2, and Sequence::seq3.
Referenced by seq_is_predecessor(), and sequencer_swap_exec().
static int seq_is_predecessor (Sequence * pred, Sequence * seq) [static]
Definition at line 445 of file sequencer_edit.c.
References Sequence::seq1, Sequence::seq2, Sequence::seq3, and seq_is_parent().
Referenced by sequencer_reassign_inputs_exec().
static void seq_paste_add_sound (Scene * scene, Sequence * seq) [static]
Definition at line 2658 of file sequencer_edit.c.
References ListBase::first, Sequence::next, Sequence::scene_sound, SEQ_META, SEQ_SOUND, Sequence::seqbase, sound_add_scene_sound_defaults(), and Sequence::type.
Referenced by sequencer_paste_exec().
static void seq_proxy_build_job (const bContext * C) [static]
Definition at line 179 of file sequencer_edit.c.
References BLI_addtail(), BLI_genericNodeN(), CTX_data_main(), CTX_data_scene(), CTX_wm_area(), CTX_wm_manager(), CTX_wm_window(), ED_area_tag_redraw(), FALSE, Sequence::flag, G, link(), ProxyBuildJob::main, MEM_callocN(), NC_SCENE, ND_SEQUENCER, NULL, proxy_endjob(), proxy_freejob(), proxy_startjob(), ProxyBuildJob::queue, ProxyBuildJob::scene, SeqIndexBuildContext::scene, SELECT, SeqIndexBuildContext::seq, SEQ_END, seq_give_editing(), seq_proxy_rebuild_context(), SEQP_BEGIN, WM_JOB_PROGRESS, WM_jobs_callbacks(), WM_jobs_customdata(), WM_jobs_get(), WM_jobs_get_customdata(), WM_jobs_is_running(), WM_jobs_start(), and WM_jobs_timer().
Referenced by sequencer_rebuild_proxy_exec().
void seq_rectf (Sequence * seq, rctf * rectf)
Definition at line 224 of file sequencer_edit.c.
References Sequence::enddisp, Sequence::endstill, Sequence::len, Sequence::machine, SEQ_STRIP_OFSBOTTOM, SEQ_STRIP_OFSTOP, Sequence::start, Sequence::startdisp, Sequence::startstill, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by sequencer_borderselect_exec().
static void UNUSED_FUNCTION() seq_remap_paths (Scene * scene) [static]
Definition at line 918 of file sequencer_edit.c.
References BLI_snprintf(), BLI_strncpy(), Strip::dir, FALSE, FILE_MAX, Sequence::flag, NULL, SELECT, seq_active_get(), SEQ_END, seq_give_editing(), SEQP_BEGIN, Sequence::strip, and strlen().
static int sequencer_add_duplicate_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1565 of file sequencer_edit.c.
References apply_unique_name_cb(), BLI_movelisttolist(), CTX_data_scene(), FALSE, ListBase::first, NC_SCENE, ND_SEQUENCER, Sequence::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, SEQ_DUPE_CONTEXT, seq_give_editing(), seq_recursive_apply(), seqbase_dupli_recursive(), Editing::seqbasep, and WM_event_add_notifier().
Referenced by sequencer_add_duplicate_invoke(), and SEQUENCER_OT_duplicate().
static int sequencer_add_duplicate_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1592 of file sequencer_edit.c.
References OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_set(), sequencer_add_duplicate_exec(), TFM_TRANSLATION, WM_OP_INVOKE_REGION_WIN, and WM_operator_name_call().
Referenced by SEQUENCER_OT_duplicate().
static int sequencer_change_effect_input_exec (bContext * C, wmOperator * op) [static]
Definition at line 2870 of file sequencer_edit.c.
References BKE_report(), CTX_data_scene(), FALSE, free_imbuf_seq(), NC_SCENE, ND_SEQUENCER, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), RPT_ERROR, Sequence::seq1, Sequence::seq2, Sequence::seq3, seq_active_get(), seq_give_editing(), Editing::seqbase, SWAP, update_changed_seq_and_deps(), and WM_event_add_notifier().
Referenced by SEQUENCER_OT_change_effect_input().
static int sequencer_change_effect_type_exec (bContext * C, wmOperator * op) [static]
Definition at line 2928 of file sequencer_edit.c.
References BKE_report(), CTX_data_scene(), FALSE, SeqEffectHandle::free, free_imbuf_seq(), get_sequence_effect(), get_sequence_effect_num_inputs(), SeqEffectHandle::init, NC_SCENE, ND_SEQUENCER, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), RPT_ERROR, seq_active_get(), SEQ_EFFECT, seq_give_editing(), Editing::seqbase, Sequence::type, update_changed_seq_and_deps(), and WM_event_add_notifier().
Referenced by SEQUENCER_OT_change_effect_type().
static int sequencer_change_path_exec (bContext * C, wmOperator * op) [static]
Definition at line 2988 of file sequencer_edit.c.
References Sequence::anim_endofs, Sequence::anim_startofs, BLI_path_rel(), BLI_strncpy(), calc_sequence(), CTX_data_main(), CTX_data_scene(), Strip::dir, FALSE, FILE_MAX, free_imbuf_seq(), Scene::id, len(), MEM_callocN(), MEM_freeN(), StripElem::name, Main::name, NC_SCENE, ND_SEQUENCER, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, reload_sequence_new_file(), RNA_BEGIN, RNA_boolean_get(), RNA_END, RNA_pointer_create(), RNA_property_collection_length(), RNA_property_string_set(), RNA_property_update(), RNA_Sequence, RNA_string_get(), RNA_string_get_alloc(), RNA_struct_find_property(), seq_active_get(), seq_give_editing(), SEQ_IMAGE, Editing::seqbase, Sequence::strip, Strip::stripdata, TRUE, Sequence::type, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_change_path().
static int sequencer_change_path_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 3057 of file sequencer_edit.c.
References CTX_data_scene(), Strip::dir, FALSE, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_boolean_set(), RNA_string_set(), seq_active_get(), SEQ_IMAGE, Sequence::strip, Sequence::type, and WM_event_add_fileselect().
Referenced by SEQUENCER_OT_change_path().
static int sequencer_copy_exec (bContext * C, wmOperator * op) [static]
Definition at line 2594 of file sequencer_edit.c.
References apply_unique_name_cb(), BKE_report(), BLI_movelisttolist(), RenderData::cfra, CTX_data_scene(), FALSE, ListBase::first, ListBase::last, Sequence::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Sequence::prev, Scene::r, wmOperator::reports, RPT_ERROR, seq_copy_del_sound(), SEQ_DUPE_UNIQUE_NAME, seq_free_clipboard(), seq_give_editing(), seq_recursive_apply(), seqbase_clipboard, seqbase_clipboard_frame, seqbase_dupli_recursive(), seqbase_isolated_sel_check(), and Editing::seqbasep.
Referenced by SEQUENCER_OT_copy().
static int sequencer_cut_exec (bContext * C, wmOperator * op) [static]
Definition at line 1458 of file sequencer_edit.c.
References BLI_movelisttolist(), CTX_data_scene(), cut_seq_hard(), cut_seq_list(), cut_seq_soft(), Sequence::enddisp, FALSE, ListBase::first, Sequence::flag, ListBase::last, NC_SCENE, ND_SEQUENCER, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), RNA_int_get(), SEQ_ALLSEL, SEQ_CUT_HARD, SEQ_END, seq_give_editing(), SEQ_SIDE_BOTH, SEQ_SIDE_LEFT, Editing::seqbasep, SEQP_BEGIN, sort_seq(), Sequence::startdisp, and WM_event_add_notifier().
Referenced by sequencer_cut_invoke(), and SEQUENCER_OT_cut().
static int sequencer_cut_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1513 of file sequencer_edit.c.
References CFRA, CTX_data_scene(), ED_operator_sequencer_active(), mouse_frame_side(), wmEvent::mval, wmOperator::ptr, RNA_enum_set(), RNA_int_set(), SEQ_SIDE_BOTH, sequencer_cut_exec(), and UI_view2d_fromcontext().
Referenced by SEQUENCER_OT_cut().
static int sequencer_delete_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1622 of file sequencer_edit.c.
References calc_sequence(), CTX_data_scene(), del_seq_find_replace_recurs(), FALSE, ListBase::first, Sequence::flag, ListBase::last, Editing::metastack, NC_SCENE, ND_SEQUENCER, Sequence::next, OPERATOR_FINISHED, MetaStack::parseq, MetaStack::prev, recurs_del_seq_flag(), SELECT, seq_active_get(), SEQ_EFFECT, seq_give_editing(), Editing::seqbasep, TRUE, Sequence::type, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_delete().
int sequencer_edit_poll (bContext * C)
Definition at line 1001 of file sequencer_edit.c.
References CTX_data_scene(), FALSE, NULL, and seq_give_editing().
Referenced by SEQUENCER_OT_copy(), SEQUENCER_OT_cut(), SEQUENCER_OT_delete(), SEQUENCER_OT_images_separate(), SEQUENCER_OT_lock(), SEQUENCER_OT_meta_make(), SEQUENCER_OT_meta_separate(), SEQUENCER_OT_meta_toggle(), SEQUENCER_OT_mute(), SEQUENCER_OT_next_edit(), SEQUENCER_OT_offset_clear(), SEQUENCER_OT_previous_edit(), SEQUENCER_OT_refresh_all(), SEQUENCER_OT_reload(), SEQUENCER_OT_rendersize(), SEQUENCER_OT_select_active_side(), SEQUENCER_OT_select_all(), SEQUENCER_OT_select_grouped(), SEQUENCER_OT_select_handles(), SEQUENCER_OT_select_inverse(), SEQUENCER_OT_select_less(), SEQUENCER_OT_select_linked(), SEQUENCER_OT_select_more(), SEQUENCER_OT_snap(), SEQUENCER_OT_swap(), SEQUENCER_OT_unlock(), and SEQUENCER_OT_unmute().
static int sequencer_effect_poll (bContext * C) [static]
Definition at line 1384 of file sequencer_edit.c.
References CTX_data_scene(), FALSE, seq_active_get(), SEQ_EFFECT, seq_give_editing(), and Sequence::type.
Referenced by SEQUENCER_OT_change_effect_input(), SEQUENCER_OT_change_effect_type(), SEQUENCER_OT_reassign_inputs(), and SEQUENCER_OT_swap_inputs().
static int sequencer_lock_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1218 of file sequencer_edit.c.
References CTX_data_scene(), FALSE, ListBase::first, Sequence::flag, NC_SCENE, ND_SEQUENCER, Sequence::next, OPERATOR_FINISHED, SELECT, seq_give_editing(), SEQ_LOCK, Editing::seqbasep, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_lock().
static int sequencer_meta_make_exec (bContext * C, wmOperator * op) [static]
Definition at line 1909 of file sequencer_edit.c.
References alloc_sequence(), BKE_report(), BLI_addtail(), BLI_remlink(), calc_sequence(), CTX_data_scene(), Scene::ed, FALSE, ListBase::first, Sequence::flag, Sequence::machine, MAX2, MEM_callocN(), Sequence::name, NC_SCENE, ND_SEQUENCER, Sequence::next, next, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, SELECT, seq_active_get(), seq_active_set(), seq_give_editing(), SEQ_META, seq_test_overlap(), seq_update_muting(), Editing::seqbase, Sequence::seqbase, seqbase_isolated_sel_check(), seqbase_unique_name_recursive(), Editing::seqbasep, shuffle_seq(), Sequence::strip, Sequence::type, Strip::us, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_meta_make().
static int sequencer_meta_separate_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1985 of file sequencer_edit.c.
References BLI_movelisttolist(), BLI_remlink(), CTX_data_scene(), FALSE, ListBase::first, Sequence::flag, ListBase::last, NC_SCENE, ND_SEQUENCER, Sequence::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, recurs_del_seq_flag(), SELECT, seq_active_get(), seq_depends_on_meta(), SEQ_EFFECT, SEQ_FLAG_DELETE, seq_free_sequence(), seq_give_editing(), SEQ_META, SEQ_OVERLAP, seq_test_overlap(), seq_update_muting(), Sequence::seqbase, Editing::seqbasep, shuffle_seq(), sort_seq(), Sequence::type, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_meta_separate().
static int sequencer_meta_toggle_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1841 of file sequencer_edit.c.
References BLI_addtail(), BLI_remlink(), calc_sequence(), CTX_data_scene(), FALSE, ListBase::first, Sequence::flag, ListBase::last, MEM_freeN(), MEM_mallocN(), Editing::metastack, NC_SCENE, ND_SEQUENCER, Sequence::next, NULL, MetaStack::oldbasep, OPERATOR_CANCELLED, OPERATOR_FINISHED, MetaStack::parseq, recurs_sel_seq(), SELECT, seq_active_get(), seq_active_set(), seq_give_editing(), SEQ_META, seq_update_muting(), Sequence::seqbase, Editing::seqbasep, Sequence::type, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_meta_toggle().
static int sequencer_mute_exec (bContext * C, wmOperator * op) [static]
Definition at line 1124 of file sequencer_edit.c.
References CTX_data_scene(), FALSE, ListBase::first, Sequence::flag, NC_SCENE, ND_SEQUENCER, Sequence::next, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), SELECT, seq_give_editing(), SEQ_LOCK, SEQ_MUTE, seq_update_muting(), Editing::seqbasep, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_mute().
static int sequencer_next_edit_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2357 of file sequencer_edit.c.
References CTX_data_scene(), NC_SCENE, ND_FRAME, next_prev_edit_internal(), OPERATOR_CANCELLED, OPERATOR_FINISHED, SEQ_SIDE_RIGHT, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_next_edit().
static int sequencer_offset_clear_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1693 of file sequencer_edit.c.
References calc_sequence(), CTX_data_scene(), Sequence::endofs, Sequence::endstill, FALSE, ListBase::first, Sequence::flag, NC_SCENE, ND_SEQUENCER, Sequence::next, OPERATOR_FINISHED, SELECT, SEQ_EFFECT, seq_give_editing(), seq_test_overlap(), Editing::seqbasep, shuffle_seq(), Sequence::startofs, Sequence::startstill, Sequence::type, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_offset_clear().
void SEQUENCER_OT_change_effect_input (struct wmOperatorType * ot)
Definition at line 2911 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), sequencer_change_effect_input_exec(), sequencer_effect_poll(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_change_effect_type (struct wmOperatorType * ot)
Definition at line 2971 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), SEQ_CROSS, sequencer_change_effect_type_exec(), sequencer_effect_poll(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_change_path (struct wmOperatorType * ot)
Definition at line 3077 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, IMAGEFILE, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_change_path_exec(), sequencer_change_path_invoke(), sequencer_strip_has_path_poll(), WM_FILESEL_DIRECTORY, WM_FILESEL_FILEPATH, WM_FILESEL_FILES, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_copy (wmOperatorType * ot)
Definition at line 2641 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, sequencer_copy_exec(), and sequencer_edit_poll().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_cut (struct wmOperatorType * ot)
Definition at line 1532 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_int(), SEQ_CUT_SOFT, SEQ_SIDE_BOTH, sequencer_cut_exec(), sequencer_cut_invoke(), sequencer_edit_poll(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_delete (wmOperatorType * ot)
Definition at line 1674 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_delete_exec(), sequencer_edit_poll(), and WM_operator_confirm().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_duplicate (wmOperatorType * ot)
Definition at line 1602 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), sequencer_add_duplicate_exec(), sequencer_add_duplicate_invoke(), wmOperatorType::srna, TFM_TRANSLATION, and transform_mode_types.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_images_separate (wmOperatorType * ot)
Definition at line 1820 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), sequencer_edit_poll(), sequencer_separate_images_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_lock (struct wmOperatorType * ot)
Definition at line 1235 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_lock_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_meta_make (wmOperatorType * ot)
Definition at line 1958 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), sequencer_meta_make_exec(), and WM_operator_confirm().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_meta_separate (wmOperatorType * ot)
Definition at line 2029 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), sequencer_meta_separate_exec(), and WM_operator_confirm().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_meta_toggle (wmOperatorType * ot)
Definition at line 1892 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_meta_toggle_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_mute (struct wmOperatorType * ot)
Definition at line 1152 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), sequencer_edit_poll(), sequencer_mute_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_next_edit (wmOperatorType * ot)
Definition at line 2369 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_next_edit_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_offset_clear (wmOperatorType * ot)
Definition at line 1727 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_offset_clear_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_paste (wmOperatorType * ot)
Definition at line 2709 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and sequencer_paste_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_previous_edit (wmOperatorType * ot)
Definition at line 2399 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_previous_edit_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_reassign_inputs (struct wmOperatorType * ot)
Definition at line 1399 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_effect_poll(), and sequencer_reassign_inputs_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_rebuild_proxy (wmOperatorType * ot)
Definition at line 2846 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, and sequencer_rebuild_proxy_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_refresh_all (struct wmOperatorType * ot)
Definition at line 1342 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_refresh_all_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_reload (struct wmOperatorType * ot)
Definition at line 1308 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_boolean(), RNA_def_property_flag(), sequencer_edit_poll(), sequencer_reload_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_rendersize (wmOperatorType * ot)
Definition at line 2562 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_rendersize_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_snap (struct wmOperatorType * ot)
Definition at line 1105 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), sequencer_edit_poll(), sequencer_snap_exec(), sequencer_snap_invoke(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_swap (wmOperatorType * ot)
Definition at line 2503 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), SEQ_SIDE_RIGHT, sequencer_edit_poll(), sequencer_swap_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_swap_data (wmOperatorType * ot)
Definition at line 2760 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and sequencer_swap_data_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_swap_inputs (struct wmOperatorType * ot)
Definition at line 1435 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_effect_poll(), and sequencer_swap_inputs_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_unlock (struct wmOperatorType * ot)
Definition at line 1268 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sequencer_edit_poll(), and sequencer_unlock_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_unmute (struct wmOperatorType * ot)
Definition at line 1199 of file sequencer_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), sequencer_edit_poll(), sequencer_unmute_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_view_all (wmOperatorType * ot)
Definition at line 2062 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, and sequencer_view_all_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_view_all_preview (wmOperatorType * ot)
Definition at line 2128 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, and sequencer_view_all_preview_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_view_ghost_border (wmOperatorType * ot)
Definition at line 2817 of file sequencer_edit.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, wmOperatorType::poll, sequencer_view_poll(), view_ghost_border_exec(), WM_border_select_cancel(), WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_view_selected (wmOperatorType * ot)
Definition at line 2283 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, and sequencer_view_selected_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_view_toggle (wmOperatorType * ot)
Definition at line 2203 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, and sequencer_view_toggle_exec().
Referenced by sequencer_operatortypes().
void SEQUENCER_OT_view_zoom_ratio (wmOperatorType * ot)
Definition at line 2164 of file sequencer_edit.c.
References wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_float(), sequencer_view_zoom_ratio_exec(), and wmOperatorType::srna.
Referenced by sequencer_operatortypes().
static int sequencer_paste_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2671 of file sequencer_edit.c.
References apply_unique_name_cb(), BLI_movelisttolist(), RenderData::cfra, CTX_data_scene(), deselect_all_seq(), ListBase::first, NC_SCENE, ND_SEQUENCER, Sequence::next, NULL, OPERATOR_FINISHED, Scene::r, SEQ_DUPE_UNIQUE_NAME, seq_give_editing(), seq_paste_add_sound(), seq_recursive_apply(), seq_sound_init(), seq_translate(), seqbase_clipboard, seqbase_clipboard_frame, seqbase_dupli_recursive(), Editing::seqbasep, TRUE, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_paste().
static int sequencer_previous_edit_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2387 of file sequencer_edit.c.
References CTX_data_scene(), NC_SCENE, ND_FRAME, next_prev_edit_internal(), OPERATOR_CANCELLED, OPERATOR_FINISHED, SEQ_SIDE_LEFT, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_previous_edit().
static int sequencer_reassign_inputs_exec (bContext * C, wmOperator * op) [static]
Definition at line 1354 of file sequencer_edit.c.
References BKE_report(), CTX_data_scene(), NC_SCENE, ND_SEQUENCER, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, Sequence::seq1, Sequence::seq2, Sequence::seq3, seq_active_get(), seq_effect_find_selected(), seq_is_predecessor(), Sequence::type, update_changed_seq_and_deps(), and WM_event_add_notifier().
Referenced by SEQUENCER_OT_reassign_inputs().
static int sequencer_rebuild_proxy_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2839 of file sequencer_edit.c.
References OPERATOR_FINISHED, and seq_proxy_build_job().
Referenced by SEQUENCER_OT_rebuild_proxy().
static int sequencer_refresh_all_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1330 of file sequencer_edit.c.
References CTX_data_scene(), FALSE, free_imbuf_seq(), NC_SCENE, ND_SEQUENCER, OPERATOR_FINISHED, seq_give_editing(), Editing::seqbase, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_refresh_all().
static int sequencer_reload_exec (bContext * C, wmOperator * op) [static]
Definition at line 1284 of file sequencer_edit.c.
References CTX_data_scene(), FALSE, ListBase::first, Sequence::flag, NC_SCENE, ND_SEQUENCER, Sequence::next, OPERATOR_FINISHED, wmOperator::ptr, reload_sequence_new_file(), RNA_boolean_get(), SELECT, seq_give_editing(), seq_test_overlap(), Editing::seqbasep, shuffle_seq(), update_changed_seq_and_deps(), and WM_event_add_notifier().
Referenced by SEQUENCER_OT_reload().
static int sequencer_rendersize_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2521 of file sequencer_edit.c.
References RenderData::cfra, CTX_data_scene(), give_stripelem(), NC_SCENE, ND_RENDER_OPTIONS, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, StripElem::orig_height, StripElem::orig_width, Scene::r, seq_active_get(), SEQ_HD_SOUND, SEQ_IMAGE, SEQ_META, SEQ_MOVIE, SEQ_RAM_SOUND, SEQ_SCENE, Sequence::strip, Strip::stripdata, Sequence::type, WM_event_add_notifier(), RenderData::xsch, and RenderData::ysch.
Referenced by SEQUENCER_OT_rendersize().
static int sequencer_separate_images_exec (bContext * C, wmOperator * op) [static]
Definition at line 1745 of file sequencer_edit.c.
References BLI_addtail(), BLI_remlink(), BLI_strncpy(), calc_sequence(), CTX_data_scene(), Sequence::endstill, FALSE, ListBase::first, Sequence::flag, give_stripelem(), Sequence::len, StripElem::name, NC_SCENE, ND_SEQUENCER, Sequence::next, OPERATOR_FINISHED, wmOperator::ptr, RNA_int_get(), SELECT, SEQ_DUPE_UNIQUE_NAME, seq_dupli_recursive(), seq_free_sequence(), seq_give_editing(), SEQ_IMAGE, SEQ_OVERLAP, seq_test_overlap(), seq_tx_get_final_left(), seq_tx_get_final_right(), Editing::seqbasep, shuffle_seq(), sort_seq(), Sequence::start, step(), Sequence::strip, Strip::stripdata, Sequence::type, Strip::us, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_images_separate().
static int sequencer_snap_exec (bContext * C, wmOperator * op) [static]
Definition at line 1032 of file sequencer_edit.c.
References calc_sequence(), CTX_data_scene(), Sequence::depth, FALSE, ListBase::first, Sequence::flag, NC_SCENE, ND_SEQUENCER, Sequence::next, OPERATOR_FINISHED, wmOperator::ptr, RNA_int_get(), SELECT, Sequence::seq1, Sequence::seq2, Sequence::seq3, SEQ_EFFECT, seq_give_editing(), SEQ_LEFTSEL, SEQ_LOCK, SEQ_OVERLAP, SEQ_RIGHTSEL, seq_test_overlap(), seq_translate(), seq_tx_handle_xlimits(), seq_tx_set_final_left(), seq_tx_set_final_right(), seq_tx_test(), Editing::seqbasep, shuffle_seq(), sort_seq(), Sequence::start, Sequence::startofs, Sequence::startstill, Sequence::type, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_snap(), and sequencer_snap_invoke().
static int sequencer_snap_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1093 of file sequencer_edit.c.
References CFRA, CTX_data_scene(), wmOperator::ptr, RNA_int_set(), and sequencer_snap_exec().
Referenced by SEQUENCER_OT_snap().
int sequencer_strip_has_path_poll (bContext * C)
Definition at line 1014 of file sequencer_edit.c.
References Editing::act_seq, CTX_data_scene(), FALSE, NULL, seq_give_editing(), and SEQ_HAS_PATH.
Referenced by SEQUENCER_OT_change_path().
static int sequencer_swap_data_exec (bContext * C, wmOperator * op) [static]
Definition at line 2726 of file sequencer_edit.c.
References BKE_report(), calc_sequence(), CTX_data_scene(), NC_SCENE, ND_SEQUENCER, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, Sequence::scene_sound, seq_active_pair_get(), seq_swap(), Sequence::sound, sound_add_scene_sound_defaults(), sound_remove_scene_sound(), and WM_event_add_notifier().
Referenced by SEQUENCER_OT_swap_data().
static int sequencer_swap_exec (bContext * C, wmOperator * op) [static]
Definition at line 2445 of file sequencer_edit.c.
References calc_sequence(), CTX_data_scene(), Scene::ed, Sequence::effectdata, FALSE, find_next_prev_sequence(), ListBase::first, get_sequence_effect_num_inputs(), NC_SCENE, ND_SEQUENCER, Sequence::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), Sequence::seq1, Sequence::seq2, Sequence::seq3, seq_active_get(), SEQ_EFFECT, seq_give_editing(), seq_is_parent(), SEQ_SIDE_LEFT, SEQ_SIDE_RIGHT, seq_test_overlap(), Editing::seqbasep, shuffle_seq(), sort_seq(), swap_sequence(), Sequence::type, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_swap().
static int sequencer_swap_inputs_exec (bContext * C, wmOperator * op) [static]
Definition at line 1415 of file sequencer_edit.c.
References BKE_report(), CTX_data_scene(), NC_SCENE, ND_SEQUENCER, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, Sequence::seq1, Sequence::seq2, seq_active_get(), update_changed_seq_and_deps(), and WM_event_add_notifier().
Referenced by SEQUENCER_OT_swap_inputs().
static int sequencer_unlock_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1251 of file sequencer_edit.c.
References CTX_data_scene(), FALSE, ListBase::first, Sequence::flag, NC_SCENE, ND_SEQUENCER, Sequence::next, OPERATOR_FINISHED, SELECT, seq_give_editing(), SEQ_LOCK, Editing::seqbasep, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_unlock().
static int sequencer_unmute_exec (bContext * C, wmOperator * op) [static]
Definition at line 1171 of file sequencer_edit.c.
References CTX_data_scene(), FALSE, ListBase::first, Sequence::flag, NC_SCENE, ND_SEQUENCER, Sequence::next, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), SELECT, seq_give_editing(), SEQ_LOCK, SEQ_MUTE, seq_update_muting(), Editing::seqbasep, and WM_event_add_notifier().
Referenced by SEQUENCER_OT_unmute().
static int sequencer_view_all_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2046 of file sequencer_edit.c.
References CTX_wm_area(), CTX_wm_screen(), View2D::cur, ED_area_tag_redraw(), OPERATOR_FINISHED, View2D::tot, UI_view2d_curRect_validate(), UI_view2d_fromcontext(), UI_view2d_sync(), and V2D_LOCK_COPY.
Referenced by SEQUENCER_OT_view_all().
static int sequencer_view_all_preview_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2078 of file sequencer_edit.c.
References CTX_data_scene(), CTX_wm_area(), CTX_wm_region(), CTX_wm_screen(), View2D::cur, ED_area_tag_redraw(), ListBase::first, MIN2, OPERATOR_FINISHED, power_of_2(), Scene::r, seq_reset_imageofs(), RenderData::size, ScrArea::spacedata, View2D::tot, UI_view2d_curRect_validate(), UI_view2d_fromcontext(), UI_view2d_sync(), V2D_LOCK_COPY, ARegion::winx, ARegion::winy, RenderData::xasp, RenderData::xsch, RenderData::yasp, and RenderData::ysch.
Referenced by SEQUENCER_OT_view_all_preview().
int sequencer_view_poll (bContext * C)
Definition at line 1021 of file sequencer_edit.c.
References CTX_data_scene(), CTX_wm_space_seq(), FALSE, SpaceSeq::mainb, SEQ_DRAW_IMG_IMBUF, and seq_give_editing().
Referenced by SEQUENCER_OT_view_ghost_border().
static int sequencer_view_selected_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2220 of file sequencer_edit.c.
References CTX_data_scene(), CTX_wm_area(), CTX_wm_screen(), View2D::cur, ED_area_tag_redraw(), Sequence::enddisp, FALSE, ListBase::first, Sequence::flag, FPS, Sequence::machine, MAX2, MAXFRAME, MAXSEQ, MIN2, Sequence::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, SELECT, seq_give_editing(), Editing::seqbasep, Sequence::startdisp, UI_view2d_curRect_validate(), UI_view2d_fromcontext(), UI_view2d_sync(), V2D_LOCK_COPY, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by SEQUENCER_OT_view_selected().
static int sequencer_view_toggle_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2191 of file sequencer_edit.c.
References CTX_wm_area(), CTX_wm_space_data(), ED_area_tag_refresh(), OPERATOR_FINISHED, SEQ_VIEW_SEQUENCE, SEQ_VIEW_SEQUENCE_PREVIEW, and SpaceSeq::view.
Referenced by SEQUENCER_OT_view_toggle().
static int sequencer_view_zoom_ratio_exec (bContext * C, wmOperator * op) [static]
Definition at line 2144 of file sequencer_edit.c.
References BLI_resize_rctf(), CTX_data_scene(), CTX_wm_region(), View2D::cur, ED_region_tag_redraw(), View2D::mask, OPERATOR_FINISHED, wmOperator::ptr, Scene::r, RNA_float_get(), RenderData::size, UI_view2d_fromcontext(), rcti::xmax, rcti::xmin, RenderData::xsch, rcti::ymax, rcti::ymin, and RenderData::ysch.
Referenced by SEQUENCER_OT_view_zoom_ratio().
static void swap_sequence (Scene * scene, Sequence * seqa, Sequence * seqb) [static]
Definition at line 2416 of file sequencer_edit.c.
References calc_sequence(), Sequence::enddisp, Sequence::start, and Sequence::startdisp.
Referenced by sequencer_swap_exec().
static void UNUSED_FUNCTION() touch_seq_files (Scene * scene) [static]
Definition at line 861 of file sequencer_edit.c.
References BLI_file_touch(), BLI_make_file_string(), Strip::dir, FALSE, Sequence::flag, G, Sequence::name, StripElem::name, NULL, SELECT, SEQ_END, seq_give_editing(), SEQ_MOVIE, SEQP_BEGIN, str, Sequence::strip, Strip::stripdata, Sequence::type, and WM_cursor_wait().
static int view_ghost_border_exec (bContext * C, wmOperator * op) [static]
Definition at line 2778 of file sequencer_edit.c.
References ABS, CLAMP(), CTX_data_scene(), Scene::ed, FALSE, NC_SCENE, ND_SEQUENCER, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Editing::over_border, wmOperator::ptr, RNA_int_get(), seq_give_editing(), View2D::tot, UI_view2d_fromcontext(), UI_view2d_region_to_view(), WM_event_add_notifier(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by SEQUENCER_OT_view_ghost_border().
Variable Documentation
EnumPropertyItem prop_change_effect_input_types[] [static]
Initial value:
 {
    {0, "A_B", 0, "A -> B", ""},
    {1, "B_C", 0, "B -> C", ""},
    {2, "A_C", 0, "A -> C", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 2863 of file sequencer_edit.c.
EnumPropertyItem prop_cut_types[] [static]
Initial value:
 {
    {SEQ_CUT_SOFT, "SOFT", 0, "Soft", ""},
    {SEQ_CUT_HARD, "HARD", 0, "Hard", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 1452 of file sequencer_edit.c.
EnumPropertyItem prop_side_lr_types[] [static]
Initial value:
 {
    {SEQ_SIDE_LEFT, "LEFT", 0, "Left", ""},
    {SEQ_SIDE_RIGHT, "RIGHT", 0, "Right", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 110 of file sequencer_edit.c.
EnumPropertyItem prop_side_types[]
Initial value:
 {
    {SEQ_SIDE_LEFT, "LEFT", 0, "Left", ""},
    {SEQ_SIDE_RIGHT, "RIGHT", 0, "Right", ""},
    {SEQ_SIDE_BOTH, "BOTH", 0, "Both", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 103 of file sequencer_edit.c.
Referenced by SEQUENCER_OT_select_active_side(), and SEQUENCER_OT_select_handles().
EnumPropertyItem sequencer_prop_effect_types[]
Initial value:
 {
    {SEQ_CROSS, "CROSS", 0, "Crossfade", "Crossfade effect strip type"},
    {SEQ_ADD, "ADD", 0, "Add", "Add effect strip type"},
    {SEQ_SUB, "SUBTRACT", 0, "Subtract", "Subtract effect strip type"},
    {SEQ_ALPHAOVER, "ALPHA_OVER", 0, "Alpha Over", "Alpha Over effect strip type"},
    {SEQ_ALPHAUNDER, "ALPHA_UNDER", 0, "Alpha Under", "Alpha Under effect strip type"},
    {SEQ_GAMCROSS, "GAMMA_CROSS", 0, "Gamma Cross", "Gamma Cross effect strip type"},
    {SEQ_MUL, "MULTIPLY", 0, "Multiply", "Multiply effect strip type"},
    {SEQ_OVERDROP, "OVER_DROP", 0, "Alpha Over Drop", "Alpha Over Drop effect strip type"},
    {SEQ_PLUGIN, "PLUGIN", 0, "Plugin", "Plugin effect strip type"},
    {SEQ_WIPE, "WIPE", 0, "Wipe", "Wipe effect strip type"},
    {SEQ_GLOW, "GLOW", 0, "Glow", "Glow effect strip type"},
    {SEQ_TRANSFORM, "TRANSFORM", 0, "Transform", "Transform effect strip type"},
    {SEQ_COLOR, "COLOR", 0, "Color", "Color effect strip type"},
    {SEQ_SPEED, "SPEED", 0, "Speed", "Color effect strip type"},
    {SEQ_MULTICAM, "MULTICAM", 0, "Multicam Selector", ""},
    {SEQ_ADJUSTMENT, "ADJUSTMENT", 0, "Adjustment Layer", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 81 of file sequencer_edit.c.
Referenced by SEQUENCER_OT_effect_strip_add().