Blender: CIfExpr Class Reference
CIfExpr Class Reference
#include <IfExpr.h>
Public Member Functions
virtual bool MergeExpression (CExpression *otherexpr)
CIfExpr (CExpression *guard, CExpression *e1, CExpression *e2)
CIfExpr ()
virtual unsigned char GetExpressionID ()
virtual ~CIfExpr ()
virtual CValue * Calculate ()
virtual bool IsInside (float x, float y, float z, bool bBorderInclude=true)
virtual bool NeedsRecalculated ()
virtual CExpression * CheckLink (std::vector< CBrokenLinkInfo * > &brokenlinks)
virtual void ClearModified ()
virtual void BroadcastOperators (VALUE_OPERATOR op)
Detailed Description
Definition at line 28 of file IfExpr.h.
Constructor & Destructor Documentation
CIfExpr::CIfExpr (CExpression * guard, CExpression * e1, CExpression * e2)
Definition at line 38 of file IfExpr.cpp.
CIfExpr::CIfExpr ()
Definition at line 28 of file IfExpr.cpp.
CIfExpr::~CIfExpr () [virtual]
Definition at line 51 of file IfExpr.cpp.
References CExpression::Release().
Member Function Documentation
void CIfExpr::BroadcastOperators (VALUE_OPERATOR op) [virtual]
Implements CExpression.
Definition at line 134 of file IfExpr.cpp.
References assertd.
CValue * CIfExpr::Calculate () [virtual]
pre: ret: a new object containing the value of m_e1 if m_guard is a boolean TRUE a new object containing the value of m_e2 if m_guard is a boolean FALSE an new errorvalue if m_guard is not a boolean
Implements CExpression.
Definition at line 71 of file IfExpr.cpp.
References CExpression::Calculate(), CValue::GetText(), CValue::Release(), CBoolValue::sFalseString, and CBoolValue::sTrueString.
CExpression * CIfExpr::CheckLink (std::vector< CBrokenLinkInfo * > & brokenlinks) [virtual]
Implements CExpression.
Definition at line 119 of file IfExpr.cpp.
References assertd, and NULL.
void CIfExpr::ClearModified () [virtual]
Implements CExpression.
Definition at line 127 of file IfExpr.cpp.
References assertd.
unsigned char CIfExpr::GetExpressionID () [virtual]
Implements CExpression.
Definition at line 141 of file IfExpr.cpp.
References CExpression::CIFEXPRESSIONID.
bool CIfExpr::IsInside (float x, float y, float z, bool bBorderInclude = true) [virtual]
Definition at line 102 of file IfExpr.cpp.
References assertd.
bool CIfExpr::MergeExpression (CExpression * otherexpr) [virtual]
Implements CExpression.
Definition at line 94 of file IfExpr.cpp.
References assertd.
bool CIfExpr::NeedsRecalculated () [virtual]
Implements CExpression.
Definition at line 110 of file IfExpr.cpp.
References CExpression::NeedsRecalculated().
The documentation for this class was generated from the following files:
IfExpr.h
IfExpr.cpp