Blender: MOD_smooth.c File Reference
MOD_smooth.c File Reference
modifiers
#include "DNA_meshdata_types.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BLI_string.h"
#include "MEM_guardedalloc.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_particle.h"
#include "BKE_deform.h"
#include "MOD_modifiertypes.h"
#include "MOD_util.h"
Functions
static void initData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static int isDisabled (ModifierData *md, int UNUSED(useRenderParams))
static CustomDataMask requiredDataMask (Object *UNUSED(ob), ModifierData *md)
static void smoothModifier_do (SmoothModifierData *smd, Object *ob, DerivedMesh *dm, float(*vertexCos)[3], int numVerts)
static void deformVerts (ModifierData *md, Object *ob, DerivedMesh *derivedData, float(*vertexCos)[3], int numVerts, int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
static void deformVertsEM (ModifierData *md, Object *ob, struct BMEditMesh *editData, DerivedMesh *derivedData, float(*vertexCos)[3], int numVerts)
Variables
ModifierTypeInfo modifierType_Smooth
Detailed Description
Definition in file MOD_smooth.c.
Function Documentation
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 62 of file MOD_smooth.c.
References BLI_strncpy(), SmoothModifierData::defgrp_name, SmoothModifierData::fac, SmoothModifierData::flag, and SmoothModifierData::repeat.
static void deformVerts (ModifierData * md, Object * ob, DerivedMesh * derivedData, float(*) vertexCos[3], int numVerts, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 215 of file MOD_smooth.c.
References get_dm(), NULL, DerivedMesh::release, and smoothModifier_do().
static void deformVertsEM (ModifierData * md, Object * ob, struct BMEditMesh * editData, DerivedMesh * derivedData, float(*) vertexCos[3], int numVerts) [static]
Definition at line 228 of file MOD_smooth.c.
References get_dm(), NULL, DerivedMesh::release, and smoothModifier_do().
static void initData (ModifierData * md) [static]
Definition at line 52 of file MOD_smooth.c.
References SmoothModifierData::defgrp_name, SmoothModifierData::fac, SmoothModifierData::flag, MOD_SMOOTH_X, MOD_SMOOTH_Y, MOD_SMOOTH_Z, and SmoothModifierData::repeat.
static int isDisabled (ModifierData * md, int UNUSEDuseRenderParams) [static]
Definition at line 73 of file MOD_smooth.c.
References SmoothModifierData::fac, SmoothModifierData::flag, MOD_SMOOTH_X, MOD_SMOOTH_Y, and MOD_SMOOTH_Z.
static CustomDataMask requiredDataMask (Object * UNUSEDob, ModifierData * md) [static]
Definition at line 86 of file MOD_smooth.c.
References CD_MASK_MDEFORMVERT, and SmoothModifierData::defgrp_name.
static void smoothModifier_do (SmoothModifierData * smd, Object * ob, DerivedMesh * dm, float(*) vertexCos[3], int numVerts) [static]
Definition at line 97 of file MOD_smooth.c.
References add_v3_v3(), SmoothModifierData::defgrp_name, defvert_find_weight(), SmoothModifierData::fac, SmoothModifierData::flag, DerivedMesh::getEdgeArray, DerivedMesh::getNumEdges, i, MEM_callocN(), MEM_freeN(), mid_v3_v3v3(), MOD_SMOOTH_X, MOD_SMOOTH_Y, MOD_SMOOTH_Z, modifier_get_vgroup(), NULL, SmoothModifierData::repeat, MEdge::v1, and MEdge::v2.
Referenced by deformVerts(), and deformVertsEM().
Variable Documentation
ModifierTypeInfo modifierType_Smooth
Initial value:
 {
                  "Smooth",
            "SmoothModifierData",
            sizeof(SmoothModifierData),
                  eModifierTypeType_OnlyDeform,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_SupportsEditmode,
              copyData,
           deformVerts,
        NULL,
         deformVertsEM,
      NULL,
         NULL,
       NULL,
              initData,
      requiredDataMask,
              NULL,
            isDisabled,
        NULL,
         NULL,
        NULL,
     NULL,
         NULL,
        NULL,
}
Definition at line 242 of file MOD_smooth.c.