Blender: SubdLinearBuilder Class Reference
SubdLinearBuilder Class Reference
#include <subd_build.h>
Public Member Functions
SubdLinearBuilder ()
~SubdLinearBuilder ()
Patch * run (SubdFace *face)
Detailed Description
Definition at line 63 of file subd_build.h.
Constructor & Destructor Documentation
SubdLinearBuilder::SubdLinearBuilder ()
Definition at line 626 of file subd_build.cpp.
SubdLinearBuilder::~SubdLinearBuilder ()
Definition at line 630 of file subd_build.cpp.
Member Function Documentation
Patch * SubdLinearBuilder::run (SubdFace * face) [virtual]
Implements SubdBuilder.
Definition at line 634 of file subd_build.cpp.
References assert, SubdFace::edge, LinearQuadPatch::hull, LinearTrianglePatch::hull, i, SubdFace::EdgeIterator::isDone(), NULL, SubdFace::num_edges(), and swap().
The documentation for this class was generated from the following files:
subd_build.h
subd_build.cpp