Blender: KX_SceneActuator Class Reference
KX_SceneActuator Class Reference
#include <KX_SceneActuator.h>
Public Types
enum SCA_SceneActuatorMode {
KX_SCENE_NODEF = 0, KX_SCENE_RESTART, KX_SCENE_SET_SCENE, KX_SCENE_SET_CAMERA,
KX_SCENE_ADD_FRONT_SCENE, KX_SCENE_ADD_BACK_SCENE, KX_SCENE_REMOVE_SCENE, KX_SCENE_SUSPEND,
KX_SCENE_RESUME, KX_SCENE_MAX
}
Public Member Functions
KX_SceneActuator (SCA_IObject *gameobj, int mode, KX_Scene *scene, KX_KetsjiEngine *ketsjiEngine, const STR_String &nextSceneName, KX_Camera *camera)
virtual ~KX_SceneActuator ()
virtual CValue * GetReplica ()
virtual void ProcessReplica ()
virtual bool UnlinkObject (SCA_IObject *clientobj)
virtual void Relink (CTR_Map< CTR_HashedPtr, void * > *obj_map)
virtual bool Update ()
Detailed Description
Definition at line 39 of file KX_SceneActuator.h.
Member Enumeration Documentation
enum KX_SceneActuator::SCA_SceneActuatorMode
Enumerator:
KX_SCENE_NODEF
KX_SCENE_RESTART
KX_SCENE_SET_SCENE
KX_SCENE_SET_CAMERA
KX_SCENE_ADD_FRONT_SCENE
KX_SCENE_ADD_BACK_SCENE
KX_SCENE_REMOVE_SCENE
KX_SCENE_SUSPEND
KX_SCENE_RESUME
KX_SCENE_MAX
Definition at line 62 of file KX_SceneActuator.h.
Constructor & Destructor Documentation
KX_SceneActuator::KX_SceneActuator (SCA_IObject * gameobj, int mode, KX_Scene * scene, KX_KetsjiEngine * ketsjiEngine, const STR_String & nextSceneName, KX_Camera * camera)
Definition at line 47 of file KX_SceneActuator.cpp.
References Scene::camera, and SCA_IObject::RegisterActuator().
Referenced by GetReplica().
KX_SceneActuator::~KX_SceneActuator () [virtual]
Definition at line 66 of file KX_SceneActuator.cpp.
References SCA_IObject::UnregisterActuator().
Member Function Documentation
CValue * KX_SceneActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 74 of file KX_SceneActuator.cpp.
References KX_SceneActuator(), and ProcessReplica().
void KX_SceneActuator::ProcessReplica () [virtual]
Makes sure any internal data owned by this class is deep copied.
Reimplemented from SCA_IActuator.
Definition at line 81 of file KX_SceneActuator.cpp.
References SCA_IObject::RegisterActuator().
Referenced by GetReplica().
void KX_SceneActuator::Relink (CTR_Map< CTR_HashedPtr, void * > * obj_map) [virtual]
Reimplemented from SCA_ILogicBrick.
Definition at line 99 of file KX_SceneActuator.cpp.
References SCA_IObject::RegisterActuator(), and SCA_IObject::UnregisterActuator().
bool KX_SceneActuator::UnlinkObject (SCA_IObject * clientobj) [virtual]
UnlinkObject(...) Certain actuator use gameobject pointers (like TractTo actuator) This function can be called when an object is removed to make sure that the actuator will not use it anymore.
Reimplemented from SCA_IActuator.
Definition at line 88 of file KX_SceneActuator.cpp.
References NULL.
bool KX_SceneActuator::Update (void) [virtual]
Reimplemented from SCA_IActuator.
Definition at line 111 of file KX_SceneActuator.cpp.
References KX_KetsjiEngine::ConvertAndAddScene(), SCA_IObject::GetGameObjectType(), KX_Scene::GetName(), SCA_ILogicBrick::GetParent(), SCA_IActuator::IsNegativeEvent(), KX_SCENE_ADD_BACK_SCENE, KX_SCENE_ADD_FRONT_SCENE, KX_SCENE_REMOVE_SCENE, KX_SCENE_RESTART, KX_SCENE_RESUME, KX_SCENE_SET_CAMERA, KX_SCENE_SET_SCENE, KX_SCENE_SUSPEND, STR_String::Length(), SCA_IObject::OBJ_CAMERA, SCA_IActuator::RemoveAllEvents(), KX_KetsjiEngine::RemoveScene(), KX_KetsjiEngine::ReplaceScene(), KX_KetsjiEngine::ResumeScene(), KX_Scene::SetActiveCamera(), and KX_KetsjiEngine::SuspendScene().
The documentation for this class was generated from the following files:
KX_SceneActuator.h
KX_SceneActuator.cpp