Blender: BSP_TMesh Class Reference
BSP_TMesh Class Reference
#include <BSP_TMesh.h>
Public Member Functions
std::vector< BSP_TVertex > & VertexSet ()
std::vector< BSP_TFace > & FaceSet ()
void AddFace (int *verts, int num_verts)
void BuildNormal (BSP_TFace &f) const
Public Attributes
std::vector< BSP_TVertex > m_verts
std::vector< BSP_TFace > m_faces
MT_Vector3 m_min
MT_Vector3 m_max
Detailed Description
Definition at line 55 of file BSP_TMesh.h.
Member Function Documentation
void BSP_TMesh::AddFace (int * verts, int num_verts) [inline]
Definition at line 76 of file BSP_TMesh.h.
References BuildNormal(), i, m_faces, and BSP_TFace::m_verts.
void BSP_TMesh::BuildNormal (BSP_TFace & f) const [inline]
Definition at line 94 of file BSP_TMesh.h.
References MT_Vector3::cross(), BSP_TFace::m_normal, m_verts, BSP_TFace::m_verts, and MT_Vector3::safe_normalized().
Referenced by AddFace().
std::vector<BSP_TFace>& BSP_TMesh::FaceSet () [inline]
Definition at line 70 of file BSP_TMesh.h.
References m_faces.
Referenced by FaceIt_Construct(), FaceIt_Done(), and FaceIt_Reset().
std::vector<BSP_TVertex>& BSP_TMesh::VertexSet () [inline]
Definition at line 64 of file BSP_TMesh.h.
References m_verts.
Referenced by VertexIt_Construct(), VertexIt_Done(), and VertexIt_Reset().
Member Data Documentation
std::vector<BSP_TFace> BSP_TMesh::m_faces
Definition at line 59 of file BSP_TMesh.h.
Referenced by AddFace(), and FaceSet().
MT_Vector3 BSP_TMesh::m_max
Definition at line 61 of file BSP_TMesh.h.
MT_Vector3 BSP_TMesh::m_min
Definition at line 61 of file BSP_TMesh.h.
std::vector<BSP_TVertex> BSP_TMesh::m_verts
Definition at line 58 of file BSP_TMesh.h.
Referenced by BuildNormal(), and VertexSet().
The documentation for this class was generated from the following file:
BSP_TMesh.h