Blender: Application Class Reference
Application Class Reference
Public Member Functions
Application (GHOST_ISystem *system)
~Application (void)
virtual bool processEvent (GHOST_IEvent *event)
Public Attributes
GHOST_ISystem * m_system
GHOST_IWindow * m_mainWindow
GHOST_IWindow * m_secondaryWindow
GHOST_IWindow * m_fullScreenWindow
GHOST_ITimerTask * m_gearsTimer
GHOST_ITimerTask * m_testTimer
GHOST_TStandardCursor m_cursor
bool m_exitRequested
bool stereo
Detailed Description
Definition at line 401 of file GHOST_Test.cpp.
Constructor & Destructor Documentation
Application::Application (GHOST_ISystem * system)
Definition at line 419 of file GHOST_Test.cpp.
References GHOST_ISystem::createWindow(), gearsTimerProc(), GHOST_kDrawingContextTypeOpenGL, GHOST_kWindowStateNormal, GHOST_ISystem::installTimer(), m_gearsTimer, m_mainWindow, and m_secondaryWindow.
Application::~Application (void)
Definition at line 450 of file GHOST_Test.cpp.
References GHOST_ISystem::disposeWindow(), m_mainWindow, m_secondaryWindow, m_system, and GHOST_ISystem::validWindow().
Member Function Documentation
bool Application::processEvent (GHOST_IEvent * event) [virtual]
This method is called by the system when it has events to dispatch.
See also:
GHOST_ISystem::dispatchEvents
Parameters:
event The event that can be handled or ignored.
Returns:
Indication as to whether the event was handled.
Implements GHOST_IEventConsumer.
Definition at line 462 of file GHOST_Test.cpp.
References GHOST_ISystem::beginFullScreen(), GHOST_DisplaySetting::bpp, GHOST_ISystem::disposeWindow(), GHOST_ISystem::endFullScreen(), GHOST_DisplaySetting::frequency, GHOST_IWindow::getCursorVisibility(), GHOST_IEvent::getData(), GHOST_ISystem::getFullScreen(), GHOST_ISystem::getModifierKeyState(), GHOST_IWindow::getTitle(), GHOST_IEvent::getType(), GHOST_kEventKeyDown, GHOST_kEventKeyUp, GHOST_kEventWheel, GHOST_kEventWindowActivate, GHOST_kEventWindowClose, GHOST_kEventWindowDeactivate, GHOST_kEventWindowUpdate, GHOST_kKeyC, GHOST_kKeyE, GHOST_kKeyF, GHOST_kKeyH, GHOST_kKeyM, GHOST_kKeyQ, GHOST_kKeyS, GHOST_kKeyT, GHOST_kKeyW, GHOST_kModifierKeyLeftAlt, GHOST_kModifierKeyLeftControl, GHOST_kModifierKeyLeftShift, GHOST_kModifierKeyRightAlt, GHOST_kModifierKeyRightControl, GHOST_kModifierKeyRightShift, GHOST_kStandardCursorFirstCursor, GHOST_kStandardCursorNumCursors, GHOST_ISystem::installTimer(), GHOST_TEventKeyData::key, LEFT_EYE, m_cursor, m_exitRequested, m_fullScreenWindow, m_mainWindow, m_system, m_testTimer, GHOST_ISystem::removeTimer(), RenderCamera(), RenderScene(), RIGHT_EYE, GHOST_ISystem::setCursorPosition(), GHOST_IWindow::setCursorShape(), GHOST_IWindow::setCursorVisibility(), GHOST_IWindow::setTitle(), stereo, GHOST_IWindow::swapBuffers(), testTimerProc(), GHOST_ISystem::validWindow(), View(), view_rotz, GHOST_DisplaySetting::xPixels, GHOST_DisplaySetting::yPixels, and GHOST_TEventWheelData::z.
Member Data Documentation
GHOST_TStandardCursor Application::m_cursor
Definition at line 412 of file GHOST_Test.cpp.
Referenced by processEvent().
bool Application::m_exitRequested
Definition at line 413 of file GHOST_Test.cpp.
Referenced by main(), and processEvent().
GHOST_IWindow* Application::m_fullScreenWindow
Definition at line 410 of file GHOST_Test.cpp.
Referenced by gearsTimerProc(), and processEvent().
GHOST_ITimerTask* Application::m_gearsTimer
Definition at line 411 of file GHOST_Test.cpp.
Referenced by Application().
GHOST_IWindow* Application::m_mainWindow
Definition at line 408 of file GHOST_Test.cpp.
Referenced by Application(), processEvent(), and ~Application().
GHOST_IWindow* Application::m_secondaryWindow
Definition at line 409 of file GHOST_Test.cpp.
Referenced by Application(), and ~Application().
GHOST_ISystem* Application::m_system
Definition at line 407 of file GHOST_Test.cpp.
Referenced by processEvent(), and ~Application().
GHOST_ITimerTask * Application::m_testTimer
Definition at line 411 of file GHOST_Test.cpp.
Referenced by processEvent().
bool Application::stereo
Definition at line 415 of file GHOST_Test.cpp.
Referenced by processEvent().
The documentation for this class was generated from the following file:
GHOST_Test.cpp