Blender: SCA_2DFilterActuator Class Reference
SCA_2DFilterActuator Class Reference
#include <SCA_2DFilterActuator.h>
Public Member Functions
SCA_2DFilterActuator (class SCA_IObject *gameobj, RAS_2DFilterManager::RAS_2DFILTER_MODE type, short flag, float float_arg, int int_arg, RAS_IRasterizer *rasterizer, SCA_IScene *scene)
void SetShaderText (const char *text)
virtual ~SCA_2DFilterActuator ()
virtual bool Update ()
virtual CValue * GetReplica ()
Detailed Description
Definition at line 38 of file SCA_2DFilterActuator.h.
Constructor & Destructor Documentation
SCA_2DFilterActuator::SCA_2DFilterActuator (class SCA_IObject * gameobj, RAS_2DFilterManager::RAS_2DFILTER_MODE type, short flag, float float_arg, int int_arg, RAS_IRasterizer * rasterizer, SCA_IScene * scene)
Definition at line 41 of file SCA_2DFilterActuator.cpp.
References CValue::GetPropertyNames(), SCA_ILogicBrick::m_gameobj, and NULL.
Referenced by GetReplica().
SCA_2DFilterActuator::~SCA_2DFilterActuator () [virtual]
Definition at line 37 of file SCA_2DFilterActuator.cpp.
Member Function Documentation
CValue * SCA_2DFilterActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 65 of file SCA_2DFilterActuator.cpp.
References SCA_IActuator::ProcessReplica(), and SCA_2DFilterActuator().
void SCA_2DFilterActuator::SetShaderText (const char * text)
Definition at line 100 of file SCA_2DFilterActuator.cpp.
bool SCA_2DFilterActuator::Update (void) [virtual]
Reimplemented from SCA_IActuator.
Definition at line 73 of file SCA_2DFilterActuator.cpp.
References RAS_IRasterizer::DisableMotionBlur(), RAS_IRasterizer::EnableMotionBlur(), SCA_IActuator::IsNegativeEvent(), SCA_ILogicBrick::m_gameobj, RAS_2DFilterManager::RAS_2DFILTER_MOTIONBLUR, RAS_2DFilterManager::RAS_2DFILTER_NUMBER_OF_FILTERS, SCA_IActuator::RemoveAllEvents(), and SCA_IScene::Update2DFilter().
The documentation for this class was generated from the following files:
SCA_2DFilterActuator.h
SCA_2DFilterActuator.cpp