Blender: CcdPhysicsController.cpp File Reference
CcdPhysicsController.cpp File Reference
Bullet Physics
#include <stdint.h>
#include "CcdPhysicsController.h"
#include "btBulletDynamicsCommon.h"
#include "BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.h"
#include "BulletCollision/CollisionShapes/btTriangleIndexVertexArray.h"
#include "PHY_IMotionState.h"
#include "CcdPhysicsEnvironment.h"
#include "RAS_MeshObject.h"
#include "KX_GameObject.h"
#include "BulletSoftBody/btSoftBody.h"
#include "BulletSoftBody//btSoftBodyInternals.h"
#include "BulletSoftBody/btSoftBodyHelpers.h"
#include "LinearMath/btConvexHull.h"
#include "BulletCollision/Gimpact/btGImpactShape.h"
#include "BulletSoftBody/btSoftRigidDynamicsWorld.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "BKE_cdderivedmesh.h"
#include <cstdio>
Classes
class BlenderBulletMotionState
Functions
btVector3 startVel (0, 0, 0)
static void DeleteBulletShape (btCollisionShape *shape, bool free)
Variables
float gDeactivationTime
todo: fill all the empty CcdPhysicsController methods, hook them up to the btRigidBody class
bool gDisableDeactivation
float gLinearSleepingTreshold = 0.8f
float gAngularSleepingTreshold = 1.0f
Detailed Description
Definition in file CcdPhysicsController.cpp.
Function Documentation
static void DeleteBulletShape (btCollisionShape * shape, bool free) [static]
Definition at line 485 of file CcdPhysicsController.cpp.
References btTriangleMeshShape::getMeshInterface(), btCollisionShape::getShapeType(), and TRIANGLE_MESH_SHAPE_PROXYTYPE.
Referenced by CcdShapeConstructionInfo::CreateBulletShape(), CcdPhysicsController::DeleteControllerShape(), and CcdShapeConstructionInfo::~CcdShapeConstructionInfo().
btVector3 startVel (0 , 0 , 0)
Variable Documentation
float gAngularSleepingTreshold = 1.0f
Definition at line 63 of file CcdPhysicsController.cpp.
Referenced by CcdPhysicsEnvironment::setDeactivationAngularTreshold().
float gDeactivationTime
todo: fill all the empty CcdPhysicsController methods, hook them up to the btRigidBody class
Definition at line 25 of file btRigidBody.cpp.
Referenced by CcdPhysicsEnvironment::setDeactivationTime(), and btRigidBody::wantsSleeping().
bool gDisableDeactivation
Definition at line 26 of file btRigidBody.cpp.
Referenced by btDiscreteDynamicsWorld::stepSimulation(), and btRigidBody::wantsSleeping().
float gLinearSleepingTreshold = 0.8f
Definition at line 62 of file CcdPhysicsController.cpp.
Referenced by CcdPhysicsEnvironment::setDeactivationLinearTreshold().