Blender: bmesh_py_types.h File Reference
bmesh_py_types.h File Reference
Classes
struct BPy_BMGeneric
struct BPy_BMElem
struct BPy_BMesh
struct BPy_BMVert
struct BPy_BMEdge
struct BPy_BMFace
struct BPy_BMLoop
struct BPy_BMElemSeq
struct BPy_BMIter
Defines
#define BPy_BMesh_Check(v) (Py_TYPE(v) == &BPy_BMesh_Type)
#define BPy_BMVert_Check(v) (Py_TYPE(v) == &BPy_BMVert_Type)
#define BPy_BMEdge_Check(v) (Py_TYPE(v) == &BPy_BMEdge_Type)
#define BPy_BMFace_Check(v) (Py_TYPE(v) == &BPy_BMFace_Type)
#define BPy_BMLoop_Check(v) (Py_TYPE(v) == &BPy_BMLoop_Type)
#define BPy_BMElemSeq_Check(v) (Py_TYPE(v) == &BPy_BMElemSeq_Type)
#define BPy_BMVertSeq_Check(v) (Py_TYPE(v) == &BPy_BMVertSeq_Type)
#define BPy_BMEdgeSeq_Check(v) (Py_TYPE(v) == &BPy_BMEdgeSeq_Type)
#define BPy_BMFaceSeq_Check(v) (Py_TYPE(v) == &BPy_BMFaceSeq_Type)
#define BPy_BMLoopSeq_Check(v) (Py_TYPE(v) == &BPy_BMLoopSeq_Type)
#define BPy_BMIter_Check(v) (Py_TYPE(v) == &BPy_BMIter_Type)
#define BPY_BM_CHECK_OBJ(obj) if (UNLIKELY(bpy_bm_generic_valid_check((BPy_BMGeneric *)obj) == -1)) { return NULL; } (void)0
#define BPY_BM_CHECK_INT(obj) if (UNLIKELY(bpy_bm_generic_valid_check((BPy_BMGeneric *)obj) == -1)) { return -1; } (void)0
#define BPY_BM_IS_VALID(obj) (LIKELY((obj)->bm != NULL))
#define BM_ITER_BPY_BM_SEQ(ele, iter, bpy_bmelemseq)
Typedefs
typedef struct BPy_BMGeneric BPy_BMGeneric
typedef struct BPy_BMElem BPy_BMElem
typedef struct BPy_BMesh BPy_BMesh
typedef struct BPy_BMVert BPy_BMVert
typedef struct BPy_BMEdge BPy_BMEdge
typedef struct BPy_BMFace BPy_BMFace
typedef struct BPy_BMLoop BPy_BMLoop
typedef struct BPy_BMElemSeq BPy_BMElemSeq
typedef struct BPy_BMIter BPy_BMIter
Enumerations
enum { BPY_BMFLAG_NOP = 0, BPY_BMFLAG_IS_WRAPPED = 1 }
Functions
void BPy_BM_init_types (void)
PyObject * BPyInit_bmesh_types (void)
PyObject * BPy_BMesh_CreatePyObject (BMesh *bm, int flag)
PyObject * BPy_BMVert_CreatePyObject (BMesh *bm, BMVert *v)
PyObject * BPy_BMEdge_CreatePyObject (BMesh *bm, BMEdge *e)
PyObject * BPy_BMFace_CreatePyObject (BMesh *bm, BMFace *f)
PyObject * BPy_BMLoop_CreatePyObject (BMesh *bm, BMLoop *l)
PyObject * BPy_BMElemSeq_CreatePyObject (BMesh *bm, BPy_BMElem *py_ele, const char itype)
PyObject * BPy_BMVertSeq_CreatePyObject (BMesh *bm)
PyObject * BPy_BMEdgeSeq_CreatePyObject (BMesh *bm)
PyObject * BPy_BMFaceSeq_CreatePyObject (BMesh *bm)
PyObject * BPy_BMLoopSeq_CreatePyObject (BMesh *bm)
PyObject * BPy_BMIter_CreatePyObject (BMesh *bm)
PyObject * BPy_BMElem_CreatePyObject (BMesh *bm, BMHeader *ele)
int bpy_bm_generic_valid_check (BPy_BMGeneric *self)
void bpy_bm_generic_invalidate (BPy_BMGeneric *self)
void * BPy_BMElem_PySeq_As_Array (BMesh **r_bm, PyObject *seq, Py_ssize_t min, Py_ssize_t max, Py_ssize_t *r_size, const char htype, const char do_unique_check, const char do_bm_check, const char *error_prefix)
PyObject * BPy_BMElem_Array_As_Tuple (BMesh *bm, BMHeader **elem, Py_ssize_t elem_len)
int BPy_BMElem_CheckHType (PyTypeObject *type, const char htype)
char * BPy_BMElem_StringFromHType_ex (const char htype, char ret[32])
char * BPy_BMElem_StringFromHType (const char htype)
Variables
PyTypeObject BPy_BMesh_Type
PyTypeObject BPy_BMVert_Type
PyTypeObject BPy_BMEdge_Type
PyTypeObject BPy_BMFace_Type
PyTypeObject BPy_BMLoop_Type
PyTypeObject BPy_BMElemSeq_Type
PyTypeObject BPy_BMVertSeq_Type
PyTypeObject BPy_BMEdgeSeq_Type
PyTypeObject BPy_BMFaceSeq_Type
PyTypeObject BPy_BMLoopSeq_Type
PyTypeObject BPy_BMIter_Type
Detailed Description
Definition in file bmesh_py_types.h.
Define Documentation
#define BM_ITER_BPY_BM_SEQ (ele, iter, bpy_bmelemseq)
Value:
for (ele = BM_iter_new(iter,                                              \
                           (bpy_bmelemseq)->bm,                               \
                           (bpy_bmelemseq)->itype,                            \
                           (bpy_bmelemseq)->py_ele ?                          \
                               ((BPy_BMElem *)(bpy_bmelemseq)->py_ele)->ele : \
                               NULL                                           \
                           );                                                 \
         ele;                                                                 \
         ele = BM_iter_step(iter))
Definition at line 178 of file bmesh_py_types.h.
Referenced by bpy_bmelemseq_contains(), bpy_bmelemseq_index_update(), and bpy_bmelemseq_length().
#define BPY_BM_CHECK_INT (obj) if (UNLIKELY(bpy_bm_generic_valid_check((BPy_BMGeneric *)obj) == -1)) { return -1; } (void)0
Definition at line 174 of file bmesh_py_types.h.
Referenced by bpy_bm_elem_hflag_set(), bpy_bm_elem_index_set(), BPy_BMEditSel_Assign(), bpy_bmeditselseq_contains(), bpy_bmeditselseq_length(), bpy_bmelem_ass_subscript(), bpy_bmelemseq_contains(), bpy_bmelemseq_length(), bpy_bmesh_select_history_set(), bpy_bmesh_select_mode_set(), bpy_bmface_material_index_set(), bpy_bmface_normal_set(), bpy_bmlayercollection_contains(), bpy_bmlayercollection_length(), bpy_bmvert_co_set(), and bpy_bmvert_normal_set().
#define BPY_BM_CHECK_OBJ (obj) if (UNLIKELY(bpy_bm_generic_valid_check((BPy_BMGeneric *)obj) == -1)) { return NULL; } (void)0
Definition at line 173 of file bmesh_py_types.h.
Referenced by bpy_bm_elem_copy_from(), bpy_bm_elem_hflag_get(), bpy_bm_elem_hide_set(), bpy_bm_elem_index_get(), bpy_bm_elem_select_set(), bpy_bm_utils_edge_rotate(), bpy_bm_utils_edge_split(), bpy_bm_utils_face_flip(), bpy_bm_utils_face_split(), bpy_bm_utils_face_vert_separate(), bpy_bm_utils_loop_separate(), bpy_bm_utils_vert_collapse_edge(), bpy_bm_utils_vert_collapse_faces(), bpy_bm_utils_vert_dissolve(), bpy_bm_utils_vert_separate(), bpy_bmedge_calc_face_angle(), bpy_bmedge_calc_length(), bpy_bmedge_calc_tangent(), bpy_bmedge_is_boundary_get(), bpy_bmedge_is_manifold_get(), bpy_bmedge_is_wire_get(), bpy_bmedge_normal_update(), bpy_bmedge_other_vert(), bpy_bmedgeseq_get(), bpy_bmedgeseq_get__method(), bpy_bmedgeseq_new(), bpy_bmedgeseq_remove(), bpy_bmeditselseq_active_get(), bpy_bmeditselseq_add(), bpy_bmeditselseq_clear(), bpy_bmeditselseq_iter(), bpy_bmeditselseq_remove(), bpy_bmeditselseq_subscript_int(), bpy_bmeditselseq_subscript_slice(), bpy_bmeditselseq_validate(), bpy_bmelem_subscript(), bpy_bmelemseq_elem_get(), bpy_bmelemseq_index_update(), bpy_bmelemseq_iter(), bpy_bmelemseq_layers_get(), bpy_bmelemseq_subscript_int(), bpy_bmelemseq_subscript_slice(), bpy_bmesh_clear(), bpy_bmesh_copy(), bpy_bmesh_from_object(), bpy_bmesh_is_wrapped_get(), bpy_bmesh_normal_update(), bpy_bmesh_select_flush(), bpy_bmesh_select_flush_mode(), bpy_bmesh_select_history_get(), bpy_bmesh_select_mode_get(), bpy_bmesh_to_mesh(), bpy_bmesh_transform(), bpy_bmface_calc_area(), bpy_bmface_calc_center_bounds(), bpy_bmface_calc_center_mean(), bpy_bmface_calc_perimeter(), bpy_bmface_copy(), bpy_bmface_copy_from_face_interp(), bpy_bmface_material_index_get(), bpy_bmface_normal_get(), bpy_bmface_normal_update(), bpy_bmfaceseq_get(), bpy_bmfaceseq_get__method(), bpy_bmfaceseq_new(), bpy_bmfaceseq_remove(), bpy_bmlayeraccess_collection_get(), bpy_bmlayercollection_active_get(), bpy_bmlayercollection_get(), bpy_bmlayercollection_items(), bpy_bmlayercollection_iter(), bpy_bmlayercollection_keys(), bpy_bmlayercollection_new(), bpy_bmlayercollection_remove(), bpy_bmlayercollection_subscript_int(), bpy_bmlayercollection_subscript_slice(), bpy_bmlayercollection_subscript_str(), bpy_bmlayercollection_values(), bpy_bmlayeritem_name_get(), bpy_bmloop_calc_angle(), bpy_bmloop_calc_normal(), bpy_bmloop_calc_tangent(), bpy_bmloop_copy_from_face_interp(), bpy_bmloop_edge_get(), bpy_bmloop_face_get(), bpy_bmloop_link_loop_next_get(), bpy_bmloop_link_loop_prev_get(), bpy_bmloop_vert_get(), bpy_bmloopseq_get(), bpy_bmvert_calc_edge_angle(), bpy_bmvert_calc_shell_factor(), bpy_bmvert_co_get(), bpy_bmvert_copy_from_face_interp(), bpy_bmvert_copy_from_vert_interp(), bpy_bmvert_is_manifold_get(), bpy_bmvert_is_wire_get(), bpy_bmvert_normal_get(), bpy_bmvert_normal_update(), bpy_bmvertseq_get(), bpy_bmvertseq_new(), and bpy_bmvertseq_remove().
#define BPY_BM_IS_VALID (obj) (LIKELY((obj)->bm != NULL))
Definition at line 176 of file bmesh_py_types.h.
Referenced by bpy_bm_is_valid_get(), and BPy_BMElem_PySeq_As_Array().
#define BPy_BMEdge_Check (v) (Py_TYPE(v) == &BPy_BMEdge_Type)
Definition at line 49 of file bmesh_py_types.h.
Referenced by bpy_bmedgeseq_remove(), bpy_bmeditselseq_add(), and bpy_bmeditselseq_remove().
#define BPy_BMEdgeSeq_Check (v) (Py_TYPE(v) == &BPy_BMEdgeSeq_Type)
Definition at line 54 of file bmesh_py_types.h.
#define BPy_BMElemSeq_Check (v) (Py_TYPE(v) == &BPy_BMElemSeq_Type)
Definition at line 52 of file bmesh_py_types.h.
#define BPy_BMesh_Check (v) (Py_TYPE(v) == &BPy_BMesh_Type)
Definition at line 47 of file bmesh_py_types.h.
#define BPy_BMFace_Check (v) (Py_TYPE(v) == &BPy_BMFace_Type)
Definition at line 50 of file bmesh_py_types.h.
Referenced by bpy_bm_utils_face_flip(), bpy_bmeditselseq_add(), bpy_bmeditselseq_remove(), and bpy_bmfaceseq_remove().
#define BPy_BMFaceSeq_Check (v) (Py_TYPE(v) == &BPy_BMFaceSeq_Type)
Definition at line 55 of file bmesh_py_types.h.
#define BPy_BMIter_Check (v) (Py_TYPE(v) == &BPy_BMIter_Type)
Definition at line 57 of file bmesh_py_types.h.
#define BPy_BMLoop_Check (v) (Py_TYPE(v) == &BPy_BMLoop_Type)
Definition at line 51 of file bmesh_py_types.h.
Referenced by bpy_bm_utils_loop_separate().
#define BPy_BMLoopSeq_Check (v) (Py_TYPE(v) == &BPy_BMLoopSeq_Type)
Definition at line 56 of file bmesh_py_types.h.
#define BPy_BMVert_Check (v) (Py_TYPE(v) == &BPy_BMVert_Type)
Definition at line 48 of file bmesh_py_types.h.
Referenced by bpy_bmedge_other_vert(), bpy_bmeditselseq_add(), bpy_bmeditselseq_remove(), and bpy_bmvertseq_remove().
#define BPy_BMVertSeq_Check (v) (Py_TYPE(v) == &BPy_BMVertSeq_Type)
Definition at line 53 of file bmesh_py_types.h.
Typedef Documentation
typedef struct BPy_BMEdge BPy_BMEdge
typedef struct BPy_BMElem BPy_BMElem
typedef struct BPy_BMElemSeq BPy_BMElemSeq
typedef struct BPy_BMesh BPy_BMesh
typedef struct BPy_BMFace BPy_BMFace
typedef struct BPy_BMGeneric BPy_BMGeneric
typedef struct BPy_BMIter BPy_BMIter
typedef struct BPy_BMLoop BPy_BMLoop
typedef struct BPy_BMVert BPy_BMVert
Enumeration Type Documentation
anonymous enum
Enumerator:
BPY_BMFLAG_NOP
BPY_BMFLAG_IS_WRAPPED
Definition at line 140 of file bmesh_py_types.h.
Function Documentation
void bpy_bm_generic_invalidate (BPy_BMGeneric * self)
Definition at line 3128 of file bmesh_py_types.c.
References NULL.
int bpy_bm_generic_valid_check (BPy_BMGeneric * self)
Definition at line 3115 of file bmesh_py_types.c.
References LIKELY.
void BPy_BM_init_types (void)
Definition at line 2697 of file bmesh_py_types.c.
References bpy_bm_elem_as_mapping, bpy_bm_elem_hash(), bpy_bm_hash(), bpy_bmedge_dealloc(), bpy_bmedge_getseters, bpy_bmedge_methods, bpy_bmedge_repr(), bpy_bmedgeseq_getseters, bpy_bmedgeseq_methods, bpy_bmelemseq_as_mapping, bpy_bmelemseq_as_sequence, bpy_bmelemseq_dealloc(), bpy_bmelemseq_iter(), bpy_bmelemseq_methods, bpy_bmesh_dealloc(), bpy_bmesh_getseters, bpy_bmesh_methods, bpy_bmesh_repr(), bpy_bmface_dealloc(), bpy_bmface_getseters, bpy_bmface_methods, bpy_bmface_repr(), bpy_bmfaceseq_getseters, bpy_bmfaceseq_methods, bpy_bmiter_next(), bpy_bmloop_dealloc(), bpy_bmloop_getseters, bpy_bmloop_methods, bpy_bmloop_repr(), bpy_bmloopseq_getseters, bpy_bmloopseq_methods, bpy_bmvert_dealloc(), bpy_bmvert_getseters, bpy_bmvert_methods, bpy_bmvert_repr(), bpy_bmvertseq_getseters, bpy_bmvertseq_methods, and NULL.
Referenced by BPyInit_bmesh().
PyObject* BPy_BMEdge_CreatePyObject (BMesh * bm, BMEdge * e)
Definition at line 2965 of file bmesh_py_types.c.
References BLI_assert, BM_data_layer_add(), CD_BM_ELEM_PYPTR, CustomData_bmesh_get(), BMHeader::data, BMesh::edata, BMEdge::head, NULL, and UNLIKELY.
Referenced by bpy_bm_utils_edge_rotate(), bpy_bm_utils_edge_split(), bpy_bm_utils_vert_collapse_edge(), bpy_bm_utils_vert_collapse_faces(), bpy_bmedgeseq_get__method(), bpy_bmedgeseq_new(), BPy_BMElem_CreatePyObject(), and bpy_bmloop_edge_get().
PyObject* BPy_BMEdgeSeq_CreatePyObject (BMesh * bm)
Definition at line 3062 of file bmesh_py_types.c.
References BM_EDGES_OF_MESH, and NULL.
Referenced by bpy_bmedgeseq_get().
PyObject* BPy_BMElem_Array_As_Tuple (BMesh * bm, BMHeader ** elem, Py_ssize_t elem_len)
Definition at line 3238 of file bmesh_py_types.c.
References BPy_BMElem_CreatePyObject(), and i.
Referenced by bpy_bm_utils_vert_separate().
int BPy_BMElem_CheckHType (PyTypeObject * type, const char htype)
Definition at line 3249 of file bmesh_py_types.c.
References BM_EDGE, BM_FACE, BM_LOOP, and BM_VERT.
Referenced by BPy_BMElem_PySeq_As_Array().
PyObject* BPy_BMElem_CreatePyObject (BMesh * bm, BMHeader * ele)
Definition at line 3098 of file bmesh_py_types.c.
References BM_EDGE, BM_FACE, BM_LOOP, BM_VERT, BPy_BMEdge_CreatePyObject(), BPy_BMFace_CreatePyObject(), BPy_BMLoop_CreatePyObject(), BPy_BMVert_CreatePyObject(), BMHeader::htype, and NULL.
Referenced by bpy_bmeditseliter_next(), bpy_bmeditselseq_active_get(), bpy_bmeditselseq_subscript_int(), bpy_bmeditselseq_subscript_slice(), BPy_BMElem_Array_As_Tuple(), bpy_bmelemseq_subscript_int(), bpy_bmelemseq_subscript_slice(), and bpy_bmiter_next().
void* BPy_BMElem_PySeq_As_Array (BMesh ** r_bm, PyObject * seq, Py_ssize_t min, Py_ssize_t max, Py_ssize_t * r_size, const char htype, const char do_unique_check, const char do_bm_check, const char * error_prefix)
Definition at line 3138 of file bmesh_py_types.c.
References BPy_BMElem::bm, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_INTERNAL_TAG, BPY_BM_IS_VALID, BPy_BMElem_CheckHType(), BPy_BMElem_StringFromHType(), BPy_BMElem::ele, FALSE, i, NULL, TRUE, and UNLIKELY.
Referenced by bpy_bm_utils_face_join(), bpy_bm_utils_vert_separate(), bpy_bmedgeseq_get__method(), bpy_bmedgeseq_new(), BPy_BMEditSel_Assign(), bpy_bmfaceseq_get__method(), bpy_bmfaceseq_new(), and bpy_bmvert_copy_from_vert_interp().
char* BPy_BMElem_StringFromHType (const char htype)
Definition at line 3274 of file bmesh_py_types.c.
References BPy_BMElem_StringFromHType_ex().
Referenced by BPy_BMElem_PySeq_As_Array().
char* BPy_BMElem_StringFromHType_ex (const char htype, char ret[32])
Use for error strings only, not thread safe,
Returns:
a sting like '(BMVert/BMEdge/BMFace/BMLoop)'
Definition at line 3262 of file bmesh_py_types.c.
References BM_EDGE, BM_FACE, BM_LOOP, and BM_VERT.
Referenced by BPy_BMElem_StringFromHType(), and bpy_bmlayeritem_ptr_get().
PyObject* BPy_BMElemSeq_CreatePyObject (BMesh * bm, BPy_BMElem * py_ele, const char itype)
Definition at line 3043 of file bmesh_py_types.c.
Referenced by bpy_bmelemseq_elem_get().
PyObject* BPy_BMesh_CreatePyObject (BMesh * bm, int flag)
Definition at line 2913 of file bmesh_py_types.c.
References BM_data_layer_add(), CD_BM_ELEM_PYPTR, BMesh::edata, BMesh::ldata, BMesh::pdata, BMesh::py_handle, and BMesh::vdata.
Referenced by bpy_bm_from_edit_mesh(), bpy_bm_new(), and bpy_bmesh_copy().
PyObject* BPy_BMFace_CreatePyObject (BMesh * bm, BMFace * f)
Definition at line 2991 of file bmesh_py_types.c.
References BLI_assert, BM_data_layer_add(), CD_BM_ELEM_PYPTR, CustomData_bmesh_get(), BMHeader::data, BMFace::head, NULL, BMesh::pdata, and UNLIKELY.
Referenced by bpy_bm_utils_face_join(), bpy_bm_utils_face_split(), BPy_BMElem_CreatePyObject(), bpy_bmface_copy(), bpy_bmfaceseq_get__method(), bpy_bmfaceseq_new(), and bpy_bmloop_face_get().
PyObject* BPy_BMFaceSeq_CreatePyObject (BMesh * bm)
Definition at line 3071 of file bmesh_py_types.c.
References BM_FACES_OF_MESH, and NULL.
Referenced by bpy_bmfaceseq_get().
PyObject* BPy_BMIter_CreatePyObject (BMesh * bm)
Definition at line 3089 of file bmesh_py_types.c.
Referenced by bpy_bmelemseq_iter().
PyObject* BPy_BMLoop_CreatePyObject (BMesh * bm, BMLoop * l)
Definition at line 3017 of file bmesh_py_types.c.
References BLI_assert, BM_data_layer_add(), CD_BM_ELEM_PYPTR, CustomData_bmesh_get(), BMHeader::data, BMLoop::head, BMesh::ldata, NULL, and UNLIKELY.
Referenced by bpy_bm_utils_face_split(), BPy_BMElem_CreatePyObject(), bpy_bmloop_link_loop_next_get(), and bpy_bmloop_link_loop_prev_get().
PyObject* BPy_BMLoopSeq_CreatePyObject (BMesh * bm)
Definition at line 3080 of file bmesh_py_types.c.
References NULL.
Referenced by bpy_bmloopseq_get().
PyObject* BPy_BMVert_CreatePyObject (BMesh * bm, BMVert * v)
Definition at line 2939 of file bmesh_py_types.c.
References BLI_assert, BM_data_layer_add(), CD_BM_ELEM_PYPTR, CustomData_bmesh_get(), BMHeader::data, BMVert::head, NULL, UNLIKELY, and BMesh::vdata.
Referenced by bpy_bm_utils_edge_split(), bpy_bm_utils_face_vert_separate(), bpy_bm_utils_loop_separate(), bpy_bmedge_other_vert(), BPy_BMElem_CreatePyObject(), bpy_bmloop_vert_get(), and bpy_bmvertseq_new().
PyObject* BPy_BMVertSeq_CreatePyObject (BMesh * bm)
Definition at line 3053 of file bmesh_py_types.c.
References BM_VERTS_OF_MESH, and NULL.
Referenced by bpy_bmvertseq_get().
PyObject* BPyInit_bmesh_types (void)
Definition at line 2870 of file bmesh_py_types.c.
References BPy_BMDeformVert_Type, BPy_BMEditSelIter_Type, BPy_BMEditSelSeq_Type, BPy_BMLayerAccessEdge_Type, BPy_BMLayerAccessFace_Type, BPy_BMLayerAccessLoop_Type, BPy_BMLayerAccessVert_Type, BPy_BMLayerCollection_Type, BPy_BMLayerItem_Type, BPy_BMLoopUV_Type, and MODULE_TYPE_ADD.
Referenced by BPyInit_bmesh().
Variable Documentation
PyTypeObject BPy_BMEdge_Type
Definition at line 2685 of file bmesh_py_types.c.
Referenced by bpy_bm_itype_as_pytype(), bpy_bm_utils_edge_rotate(), bpy_bm_utils_edge_split(), bpy_bm_utils_face_split(), bpy_bm_utils_vert_collapse_edge(), bpy_bm_utils_vert_collapse_faces(), and bpy_bmedgeseq_new().
PyTypeObject BPy_BMEdgeSeq_Type
Definition at line 2690 of file bmesh_py_types.c.
PyTypeObject BPy_BMElemSeq_Type
Definition at line 2688 of file bmesh_py_types.c.
PyTypeObject BPy_BMesh_Type
Definition at line 2683 of file bmesh_py_types.c.
PyTypeObject BPy_BMFace_Type
Definition at line 2686 of file bmesh_py_types.c.
Referenced by bpy_bm_itype_as_pytype(), bpy_bm_utils_face_split(), bpy_bm_utils_face_vert_separate(), bpy_bmface_copy_from_face_interp(), bpy_bmfaceseq_new(), bpy_bmloop_copy_from_face_interp(), and bpy_bmvert_copy_from_face_interp().
PyTypeObject BPy_BMFaceSeq_Type
Definition at line 2691 of file bmesh_py_types.c.
PyTypeObject BPy_BMIter_Type
Definition at line 2693 of file bmesh_py_types.c.
PyTypeObject BPy_BMLoop_Type
Definition at line 2687 of file bmesh_py_types.c.
Referenced by bpy_bm_itype_as_pytype(), and bpy_bmedge_calc_tangent().
PyTypeObject BPy_BMLoopSeq_Type
Definition at line 2692 of file bmesh_py_types.c.
PyTypeObject BPy_BMVert_Type
Definition at line 2684 of file bmesh_py_types.c.
Referenced by bpy_bm_itype_as_pytype(), bpy_bm_utils_edge_split(), bpy_bm_utils_face_split(), bpy_bm_utils_face_vert_separate(), bpy_bm_utils_vert_collapse_edge(), bpy_bm_utils_vert_collapse_faces(), bpy_bm_utils_vert_dissolve(), bpy_bm_utils_vert_separate(), and bpy_bmvertseq_new().
PyTypeObject BPy_BMVertSeq_Type
Definition at line 2689 of file bmesh_py_types.c.