Blender: volume.h File Reference
volume.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void volume_isotropic_setup (ShaderData *sd, ShaderClosure *sc, float density)
__device float3 volume_isotropic_eval_phase (const ShaderData *sd, const ShaderClosure *sc, const float3 omega_in, const float3 omega_out)
__device void volume_transparent_setup (ShaderData *sd, ShaderClosure *sc, float density)
__device float3 volume_transparent_eval_phase (const ShaderData *sd, const ShaderClosure *sc, const float3 omega_in, const float3 omega_out)
__device float3 volume_eval_phase (const ShaderData *sd, const ShaderClosure *sc, const float3 omega_in, const float3 omega_out)
Function Documentation
float3 OSLShader::volume_eval_phase (const ShaderData * sd, const ShaderClosure * sc, const float3 omega_in, const float3 omega_out)
Definition at line 54 of file volume.h.
References CLOSURE_VOLUME_ISOTROPIC_ID, CLOSURE_VOLUME_TRANSPARENT_ID, make_float3(), ShaderClosure::type, volume_isotropic_eval_phase(), and volume_transparent_eval_phase().
Referenced by shader_volume_eval_phase().
__device float3 volume_isotropic_eval_phase (const ShaderData * sd, const ShaderClosure * sc, const float3 omega_in, const float3 omega_out)
Definition at line 33 of file volume.h.
References make_float3().
Referenced by volume_eval_phase().
CCL_NAMESPACE_BEGIN __device void volume_isotropic_setup (ShaderData * sd, ShaderClosure * sc, float density)
Definition at line 26 of file volume.h.
References CLOSURE_VOLUME_ISOTROPIC_ID, ShaderClosure::data0, ShaderData::flag, SD_VOLUME, and ShaderClosure::type.
Referenced by svm_node_closure_volume().
__device float3 volume_transparent_eval_phase (const ShaderData * sd, const ShaderClosure * sc, const float3 omega_in, const float3 omega_out)
Definition at line 47 of file volume.h.
References make_float3().
Referenced by volume_eval_phase().
__device void volume_transparent_setup (ShaderData * sd, ShaderClosure * sc, float density)
Definition at line 40 of file volume.h.
References CLOSURE_VOLUME_TRANSPARENT_ID, ShaderClosure::data0, ShaderData::flag, SD_VOLUME, and ShaderClosure::type.
Referenced by svm_node_closure_volume().