Blender: CCGSubSurf.h File Reference
CCGSubSurf.h File Reference
blenkernel
Classes
struct CCGMeshIFC
struct CCGAllocatorIFC
Defines
#define CCG_OMP_LIMIT 1000000
Typedefs
typedef void * CCGMeshHDL
typedef void * CCGVertHDL
typedef void * CCGEdgeHDL
typedef void * CCGFaceHDL
typedef struct CCGSubSurf CCGSubSurf
typedef struct CCGVert CCGVert
typedef struct CCGEdge CCGEdge
typedef struct CCGFace CCGFace
typedef struct CCGMeshIFC CCGMeshIFC
typedef void * CCGAllocatorHDL
typedef struct CCGAllocatorIFC CCGAllocatorIFC
typedef struct CCGVertIterator CCGVertIterator
typedef struct CCGEdgeIterator CCGEdgeIterator
typedef struct CCGFaceIterator CCGFaceIterator
Enumerations
enum CCGError { eCCGError_None = 0, eCCGError_InvalidSyncState, eCCGError_InvalidValue }
Functions
CCGSubSurf * ccgSubSurf_new (CCGMeshIFC *ifc, int subdivisionLevels, CCGAllocatorIFC *allocatorIFC, CCGAllocatorHDL allocator)
void ccgSubSurf_free (CCGSubSurf *ss)
CCGError ccgSubSurf_initFullSync (CCGSubSurf *ss)
CCGError ccgSubSurf_initPartialSync (CCGSubSurf *ss)
CCGError ccgSubSurf_syncVert (CCGSubSurf *ss, CCGVertHDL vHDL, const void *vertData, int seam, CCGVert **v_r)
CCGError ccgSubSurf_syncEdge (CCGSubSurf *ss, CCGEdgeHDL eHDL, CCGVertHDL e_vHDL0, CCGVertHDL e_vHDL1, float crease, CCGEdge **e_r)
CCGError ccgSubSurf_syncFace (CCGSubSurf *ss, CCGFaceHDL fHDL, int numVerts, CCGVertHDL *vHDLs, CCGFace **f_r)
CCGError ccgSubSurf_syncVertDel (CCGSubSurf *ss, CCGVertHDL vHDL)
CCGError ccgSubSurf_syncEdgeDel (CCGSubSurf *ss, CCGEdgeHDL eHDL)
CCGError ccgSubSurf_syncFaceDel (CCGSubSurf *ss, CCGFaceHDL fHDL)
CCGError ccgSubSurf_processSync (CCGSubSurf *ss)
CCGError ccgSubSurf_updateFromFaces (CCGSubSurf *ss, int lvl, CCGFace **faces, int numFaces)
CCGError ccgSubSurf_updateToFaces (CCGSubSurf *ss, int lvl, CCGFace **faces, int numFaces)
CCGError ccgSubSurf_updateNormals (CCGSubSurf *ss, CCGFace **faces, int numFaces)
CCGError ccgSubSurf_updateLevels (CCGSubSurf *ss, int lvl, CCGFace **faces, int numFaces)
CCGError ccgSubSurf_stitchFaces (CCGSubSurf *ss, int lvl, CCGFace **faces, int numFaces)
CCGError ccgSubSurf_setSubdivisionLevels (CCGSubSurf *ss, int subdivisionLevels)
CCGError ccgSubSurf_setAllowEdgeCreation (CCGSubSurf *ss, int allowEdgeCreation, float defaultCreaseValue, void *defaultUserData)
void ccgSubSurf_getAllowEdgeCreation (CCGSubSurf *ss, int *allowEdgeCreation_r, float *defaultCreaseValue_r, void *defaultUserData_r)
void ccgSubSurf_getUseAgeCounts (CCGSubSurf *ss, int *useAgeCounts_r, int *vertUserOffset_r, int *edgeUserOffset_r, int *faceUserOffset_r)
CCGError ccgSubSurf_setUseAgeCounts (CCGSubSurf *ss, int useAgeCounts, int vertUserOffset, int edgeUserOffset, int faceUserOffset)
CCGError ccgSubSurf_setCalcVertexNormals (CCGSubSurf *ss, int useVertNormals, int normalDataOffset)
int ccgSubSurf_getNumVerts (const CCGSubSurf *ss)
int ccgSubSurf_getNumEdges (const CCGSubSurf *ss)
int ccgSubSurf_getNumFaces (const CCGSubSurf *ss)
int ccgSubSurf_getSubdivisionLevels (const CCGSubSurf *ss)
int ccgSubSurf_getEdgeSize (const CCGSubSurf *ss)
int ccgSubSurf_getEdgeLevelSize (const CCGSubSurf *ss, int level)
int ccgSubSurf_getGridSize (const CCGSubSurf *ss)
int ccgSubSurf_getGridLevelSize (const CCGSubSurf *ss, int level)
CCGVert * ccgSubSurf_getVert (CCGSubSurf *ss, CCGVertHDL v)
CCGVertHDL ccgSubSurf_getVertVertHandle (CCGVert *v)
int ccgSubSurf_getVertNumFaces (CCGVert *v)
CCGFace * ccgSubSurf_getVertFace (CCGVert *v, int index)
int ccgSubSurf_getVertNumEdges (CCGVert *v)
CCGEdge * ccgSubSurf_getVertEdge (CCGVert *v, int index)
int ccgSubSurf_getVertAge (CCGSubSurf *ss, CCGVert *v)
void * ccgSubSurf_getVertUserData (CCGSubSurf *ss, CCGVert *v)
void * ccgSubSurf_getVertData (CCGSubSurf *ss, CCGVert *v)
void * ccgSubSurf_getVertLevelData (CCGSubSurf *ss, CCGVert *v, int level)
CCGEdge * ccgSubSurf_getEdge (CCGSubSurf *ss, CCGEdgeHDL e)
CCGEdgeHDL ccgSubSurf_getEdgeEdgeHandle (CCGEdge *e)
int ccgSubSurf_getEdgeNumFaces (CCGEdge *e)
CCGFace * ccgSubSurf_getEdgeFace (CCGEdge *e, int index)
CCGVert * ccgSubSurf_getEdgeVert0 (CCGEdge *e)
CCGVert * ccgSubSurf_getEdgeVert1 (CCGEdge *e)
float ccgSubSurf_getEdgeCrease (CCGEdge *e)
int ccgSubSurf_getEdgeAge (CCGSubSurf *ss, CCGEdge *e)
void * ccgSubSurf_getEdgeUserData (CCGSubSurf *ss, CCGEdge *e)
void * ccgSubSurf_getEdgeDataArray (CCGSubSurf *ss, CCGEdge *e)
void * ccgSubSurf_getEdgeData (CCGSubSurf *ss, CCGEdge *e, int x)
void * ccgSubSurf_getEdgeLevelData (CCGSubSurf *ss, CCGEdge *e, int x, int level)
CCGFace * ccgSubSurf_getFace (CCGSubSurf *ss, CCGFaceHDL f)
CCGFaceHDL ccgSubSurf_getFaceFaceHandle (CCGFace *f)
int ccgSubSurf_getFaceNumVerts (CCGFace *f)
CCGVert * ccgSubSurf_getFaceVert (CCGFace *f, int index)
CCGEdge * ccgSubSurf_getFaceEdge (CCGFace *f, int index)
int ccgSubSurf_getFaceEdgeIndex (CCGFace *f, CCGEdge *e)
int ccgSubSurf_getFaceAge (CCGSubSurf *ss, CCGFace *f)
void * ccgSubSurf_getFaceUserData (CCGSubSurf *ss, CCGFace *f)
void * ccgSubSurf_getFaceCenterData (CCGFace *f)
void * ccgSubSurf_getFaceGridEdgeDataArray (CCGSubSurf *ss, CCGFace *f, int gridIndex)
void * ccgSubSurf_getFaceGridEdgeData (CCGSubSurf *ss, CCGFace *f, int gridIndex, int x)
void * ccgSubSurf_getFaceGridDataArray (CCGSubSurf *ss, CCGFace *f, int gridIndex)
void * ccgSubSurf_getFaceGridData (CCGSubSurf *ss, CCGFace *f, int gridIndex, int x, int y)
int ccgSubSurf_getNumFinalVerts (const CCGSubSurf *ss)
int ccgSubSurf_getNumFinalEdges (const CCGSubSurf *ss)
int ccgSubSurf_getNumFinalFaces (const CCGSubSurf *ss)
CCGVertIterator * ccgSubSurf_getVertIterator (CCGSubSurf *ss)
CCGEdgeIterator * ccgSubSurf_getEdgeIterator (CCGSubSurf *ss)
CCGFaceIterator * ccgSubSurf_getFaceIterator (CCGSubSurf *ss)
CCGVert * ccgVertIterator_getCurrent (CCGVertIterator *vi)
int ccgVertIterator_isStopped (CCGVertIterator *vi)
void ccgVertIterator_next (CCGVertIterator *vi)
void ccgVertIterator_free (CCGVertIterator *vi)
CCGEdge * ccgEdgeIterator_getCurrent (CCGEdgeIterator *ei)
int ccgEdgeIterator_isStopped (CCGEdgeIterator *ei)
void ccgEdgeIterator_next (CCGEdgeIterator *ei)
void ccgEdgeIterator_free (CCGEdgeIterator *ei)
CCGFace * ccgFaceIterator_getCurrent (CCGFaceIterator *fi)
int ccgFaceIterator_isStopped (CCGFaceIterator *fi)
void ccgFaceIterator_next (CCGFaceIterator *fi)
void ccgFaceIterator_free (CCGFaceIterator *fi)
Detailed Description
Definition in file CCGSubSurf.h.
Define Documentation
#define CCG_OMP_LIMIT 1000000
Definition at line 44 of file CCGSubSurf.h.
Typedef Documentation
typedef void* CCGAllocatorHDL
Definition at line 24 of file CCGSubSurf.h.
typedef struct CCGAllocatorIFC CCGAllocatorIFC
typedef struct CCGEdge CCGEdge
Definition at line 13 of file CCGSubSurf.h.
typedef void* CCGEdgeHDL
Definition at line 8 of file CCGSubSurf.h.
typedef struct CCGEdgeIterator CCGEdgeIterator
Definition at line 140 of file CCGSubSurf.h.
typedef struct CCGFace CCGFace
Definition at line 14 of file CCGSubSurf.h.
typedef void* CCGFaceHDL
Definition at line 9 of file CCGSubSurf.h.
typedef struct CCGFaceIterator CCGFaceIterator
Definition at line 141 of file CCGSubSurf.h.
typedef void* CCGMeshHDL
Definition at line 6 of file CCGSubSurf.h.
typedef struct CCGMeshIFC CCGMeshIFC
typedef struct CCGSubSurf CCGSubSurf
Definition at line 11 of file CCGSubSurf.h.
typedef struct CCGVert CCGVert
Definition at line 12 of file CCGSubSurf.h.
typedef void* CCGVertHDL
Definition at line 7 of file CCGSubSurf.h.
typedef struct CCGVertIterator CCGVertIterator
Definition at line 139 of file CCGSubSurf.h.
Enumeration Type Documentation
enum CCGError
Enumerator:
eCCGError_None
eCCGError_InvalidSyncState
eCCGError_InvalidValue
Definition at line 35 of file CCGSubSurf.h.
Function Documentation
void ccgEdgeIterator_free (CCGEdgeIterator * ei)
Definition at line 3002 of file CCGSubSurf.c.
References _ehashIterator_free().
Referenced by ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_drawVerts(), ccgDM_foreachMappedEdge(), and ccgDM_getMinMax().
CCGEdge* ccgEdgeIterator_getCurrent (CCGEdgeIterator * ei)
Definition at line 2990 of file CCGSubSurf.c.
References _ehashIterator_getCurrent().
Referenced by ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_drawVerts(), ccgDM_foreachMappedEdge(), ccgDM_getMinMax(), ccgdm_getVertCos(), and getCCGDerivedMesh().
int ccgEdgeIterator_isStopped (CCGEdgeIterator * ei)
Definition at line 2994 of file CCGSubSurf.c.
References _ehashIterator_isStopped().
Referenced by ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_drawVerts(), ccgDM_foreachMappedEdge(), ccgDM_getMinMax(), ccgdm_getVertCos(), and getCCGDerivedMesh().
void ccgEdgeIterator_next (CCGEdgeIterator * ei)
Definition at line 2998 of file CCGSubSurf.c.
References _ehashIterator_next().
Referenced by ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_drawVerts(), ccgDM_foreachMappedEdge(), ccgDM_getMinMax(), ccgdm_getVertCos(), and getCCGDerivedMesh().
void ccgFaceIterator_free (CCGFaceIterator * fi)
Definition at line 3019 of file CCGSubSurf.c.
References _ehashIterator_free().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedFaceCenter(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and set_subsurf_uv().
CCGFace* ccgFaceIterator_getCurrent (CCGFaceIterator * fi)
Definition at line 3007 of file CCGSubSurf.c.
References _ehashIterator_getCurrent().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedFaceCenter(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and set_subsurf_uv().
int ccgFaceIterator_isStopped (CCGFaceIterator * fi)
Definition at line 3011 of file CCGSubSurf.c.
References _ehashIterator_isStopped().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedFaceCenter(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and set_subsurf_uv().
void ccgFaceIterator_next (CCGFaceIterator * fi)
Definition at line 3015 of file CCGSubSurf.c.
References _ehashIterator_next().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedFaceCenter(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and set_subsurf_uv().
void ccgSubSurf_free (CCGSubSurf * ss)
Definition at line 831 of file CCGSubSurf.c.
References _edge_free(), _ehash_free(), _face_free(), _vert_free(), CCGSubSurf::allocator, CCGSubSurf::allocatorIFC, CCGSUBSURF_free, CCGSubSurf::defaultEdgeUserData, CCGSubSurf::eMap, CCGSubSurf::fMap, MEM_freeN(), CCGSubSurf::oldEMap, CCGSubSurf::oldFMap, CCGSubSurf::oldVMap, CCGSubSurf::q, CCGSubSurf::r, CCGAllocatorIFC::release, CCGSubSurf::syncState, CCGSubSurf::tempEdges, CCGSubSurf::tempVerts, and CCGSubSurf::vMap.
Referenced by _getSubSurf(), ccgDM_release(), freeData(), set_subsurf_uv(), subsurf_calculate_limit_positions(), and subsurf_make_derived_from_derived().
void ccgSubSurf_getAllowEdgeCreation (CCGSubSurf * ss, int * allowEdgeCreation_r, float * defaultCreaseValue_r, void * defaultUserData_r)
Definition at line 879 of file CCGSubSurf.c.
References CCGSubSurf::allowEdgeCreation, CCGSubSurf::defaultCreaseValue, CCGSubSurf::defaultEdgeUserData, CCGMeshIFC::edgeUserSize, and CCGSubSurf::meshIFC.
CCGEdge* ccgSubSurf_getEdge (CCGSubSurf * ss, CCGEdgeHDL e)
Definition at line 2719 of file CCGSubSurf.c.
References _ehash_lookup(), and CCGSubSurf::eMap.
int ccgSubSurf_getEdgeAge (CCGSubSurf * ss, CCGEdge * e)
Definition at line 2825 of file CCGSubSurf.c.
References ccgSubSurf_getEdgeUserData(), CCGSubSurf::currentAge, CCGSubSurf::edgeUserAgeOffset, and CCGSubSurf::useAgeCounts.
Referenced by ccgDM_drawEdges(), ccgDM_drawMappedEdges(), and ccgDM_drawMappedEdgesInterp().
float ccgSubSurf_getEdgeCrease (CCGEdge * e)
Definition at line 2878 of file CCGSubSurf.c.
References CCGEdge::crease.
Referenced by ss_sync_from_uv().
void* ccgSubSurf_getEdgeData (CCGSubSurf * ss, CCGEdge * e, int x)
Definition at line 2865 of file CCGSubSurf.c.
References ccgSubSurf_getEdgeLevelData(), and CCGSubSurf::subdivLevels.
Referenced by ccgDM_copyFinalVertArray(), ccgDM_drawVerts(), ccgDM_getFinalVert(), ccgdm_getVertCos(), ccgSubSurf_getEdgeDataArray(), multires_mvert_to_ss(), and subsurf_calculate_limit_positions().
void* ccgSubSurf_getEdgeDataArray (CCGSubSurf * ss, CCGEdge * e)
Definition at line 2861 of file CCGSubSurf.c.
References ccgSubSurf_getEdgeData().
Referenced by ccgDM_drawEdges(), ccgDM_drawLooseEdges(), ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_foreachMappedEdge(), and ccgDM_getMinMax().
CCGEdgeHDL ccgSubSurf_getEdgeEdgeHandle (CCGEdge * e)
Definition at line 2821 of file CCGSubSurf.c.
References CCGEdge::eHDL.
Referenced by ccgDM_copyFinalEdgeArray(), ccgdm_getVertCos(), and getCCGDerivedMesh().
CCGFace* ccgSubSurf_getEdgeFace (CCGEdge * e, int index)
Definition at line 2844 of file CCGSubSurf.c.
References CCGEdge::faces, NULL, and CCGEdge::numFaces.
Referenced by ccgdm_adjacent_grid().
CCGEdgeIterator* ccgSubSurf_getEdgeIterator (CCGSubSurf * ss)
Definition at line 2964 of file CCGSubSurf.c.
References _ehashIterator_new(), and CCGSubSurf::eMap.
Referenced by ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_drawVerts(), ccgDM_foreachMappedEdge(), ccgDM_getMinMax(), ccgdm_getVertCos(), and getCCGDerivedMesh().
void* ccgSubSurf_getEdgeLevelData (CCGSubSurf * ss, CCGEdge * e, int x, int level)
Definition at line 2869 of file CCGSubSurf.c.
References _edge_getCo(), CCGSubSurf::meshIFC, NULL, CCGSubSurf::subdivLevels, and CCGMeshIFC::vertDataSize.
Referenced by ccgSubSurf_getEdgeData().
int ccgSubSurf_getEdgeLevelSize (const CCGSubSurf * ss, int level)
Definition at line 2736 of file CCGSubSurf.c.
References ccg_edgesize(), and CCGSubSurf::subdivLevels.
Referenced by ccgSubSurf_getEdgeSize().
int ccgSubSurf_getEdgeNumFaces (CCGEdge * e)
Definition at line 2840 of file CCGSubSurf.c.
References CCGEdge::numFaces.
Referenced by ccgdm_adjacent_grid(), ccgDM_copyFinalEdgeArray(), ccgDM_drawEdges(), ccgDM_drawLooseEdges(), and ccgDM_getFinalEdge().
int ccgSubSurf_getEdgeSize (const CCGSubSurf * ss)
Definition at line 2732 of file CCGSubSurf.c.
References ccgSubSurf_getEdgeLevelSize(), and CCGSubSurf::subdivLevels.
Referenced by ccgDM_copyFinalEdgeArray(), ccgDM_copyFinalFaceArray(), ccgDM_copyFinalLoopArray(), ccgDM_copyFinalVertArray(), ccgDM_drawEdges(), ccgDM_drawLooseEdges(), ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgDM_drawVerts(), ccgDM_foreachMappedEdge(), ccgDM_get_edge_data_layer(), ccgDM_getFinalEdge(), ccgDM_getFinalFace(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), multires_mvert_to_ss(), and subsurf_copy_grid_hidden().
void* ccgSubSurf_getEdgeUserData (CCGSubSurf * ss, CCGEdge * e)
Definition at line 2835 of file CCGSubSurf.c.
References ccg_edgebase(), EDGE_getLevelData(), CCGSubSurf::meshIFC, CCGSubSurf::subdivLevels, and CCGMeshIFC::vertDataSize.
Referenced by _edge_new(), ccgDM_getEdgeMapIndex(), ccgSubSurf__sync(), ccgSubSurf_getEdgeAge(), ccgSubSurf_syncFace(), getCCGDerivedMesh(), getEdgeIndex(), getFaceIndex(), and ss_sync_from_derivedmesh().
CCGVert* ccgSubSurf_getEdgeVert0 (CCGEdge * e)
Definition at line 2853 of file CCGSubSurf.c.
References CCGEdge::v0.
Referenced by getCCGDerivedMesh(), getEdgeIndex(), and getFaceIndex().
CCGVert* ccgSubSurf_getEdgeVert1 (CCGEdge * e)
Definition at line 2857 of file CCGSubSurf.c.
References CCGEdge::v1.
Referenced by getCCGDerivedMesh(), and getEdgeIndex().
CCGFace* ccgSubSurf_getFace (CCGSubSurf * ss, CCGFaceHDL f)
Definition at line 2723 of file CCGSubSurf.c.
References _ehash_lookup(), and CCGSubSurf::fMap.
Referenced by ss_sync_from_uv().
int ccgSubSurf_getFaceAge (CCGSubSurf * ss, CCGFace * f)
Definition at line 2889 of file CCGSubSurf.c.
References ccgSubSurf_getFaceUserData(), CCGSubSurf::currentAge, CCGSubSurf::faceUserAgeOffset, and CCGSubSurf::useAgeCounts.
void* ccgSubSurf_getFaceCenterData (CCGFace * f)
Definition at line 2937 of file CCGSubSurf.c.
References FACE_getCenterData().
Referenced by ccgDM_copyFinalVertArray(), ccgDM_drawVerts(), ccgDM_getFinalVert(), ccgdm_getVertCos(), multires_mvert_to_ss(), and subsurf_calculate_limit_positions().
CCGEdge* ccgSubSurf_getFaceEdge (CCGFace * f, int index)
Definition at line 2917 of file CCGSubSurf.c.
References FACE_getEdges(), NULL, and CCGFace::numVerts.
Referenced by ccgdm_adjacent_grid(), getFaceIndex(), and ss_sync_from_uv().
int ccgSubSurf_getFaceEdgeIndex (CCGFace * f, CCGEdge * e)
Definition at line 2926 of file CCGSubSurf.c.
References FACE_getEdges(), i, and CCGFace::numVerts.
CCGFaceHDL ccgSubSurf_getFaceFaceHandle (CCGFace * f)
Definition at line 2885 of file CCGSubSurf.c.
References CCGFace::fHDL.
Referenced by ccgdm_adjacent_grid(), ccgDM_drawFacesSolid(), ccgDM_drawFacesTex_common(), ccgDM_drawMappedFaces(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgdm_getVertCos(), getCCGDerivedMesh(), and set_subsurf_uv().
void* ccgSubSurf_getFaceGridData (CCGSubSurf * ss, CCGFace * f, int gridIndex, int x, int y)
Definition at line 2953 of file CCGSubSurf.c.
References _face_getIFCo(), CCGSubSurf::meshIFC, CCGSubSurf::subdivLevels, and CCGMeshIFC::vertDataSize.
Referenced by ccgDM_copyFinalVertArray(), ccgDM_drawVerts(), ccgDM_foreachMappedFaceCenter(), ccgDM_getFinalVert(), ccgdm_getVertCos(), ccgSubSurf_getFaceGridDataArray(), and multires_mvert_to_ss().
void* ccgSubSurf_getFaceGridDataArray (CCGSubSurf * ss, CCGFace * f, int gridIndex)
Definition at line 2949 of file CCGSubSurf.c.
References ccgSubSurf_getFaceGridData().
Referenced by ccgdm_create_grids(), ccgDM_drawEdges(), ccgDM_drawFacesSolid(), ccgDM_drawFacesTex_common(), ccgDM_drawMappedFaces(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgDM_getMinMax(), and set_subsurf_uv().
void* ccgSubSurf_getFaceGridEdgeData (CCGSubSurf * ss, CCGFace * f, int gridIndex, int x)
Definition at line 2945 of file CCGSubSurf.c.
References _face_getIECo(), CCGSubSurf::meshIFC, CCGSubSurf::subdivLevels, and CCGMeshIFC::vertDataSize.
Referenced by ccgDM_copyFinalVertArray(), ccgDM_drawVerts(), ccgDM_getFinalVert(), ccgdm_getVertCos(), ccgSubSurf_getFaceGridEdgeDataArray(), and multires_mvert_to_ss().
void* ccgSubSurf_getFaceGridEdgeDataArray (CCGSubSurf * ss, CCGFace * f, int gridIndex)
Definition at line 2941 of file CCGSubSurf.c.
References ccgSubSurf_getFaceGridEdgeData().
CCGFaceIterator* ccgSubSurf_getFaceIterator (CCGSubSurf * ss)
Definition at line 2968 of file CCGSubSurf.c.
References _ehashIterator_new(), and CCGSubSurf::fMap.
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedFaceCenter(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and set_subsurf_uv().
int ccgSubSurf_getFaceNumVerts (CCGFace * f)
Definition at line 2904 of file CCGSubSurf.c.
References CCGFace::numVerts.
Referenced by ccgdm_adjacent_grid(), ccgDM_copyFinalEdgeArray(), ccgDM_copyFinalFaceArray(), ccgDM_copyFinalLoopArray(), ccgDM_copyFinalPolyArray(), ccgDM_copyFinalVertArray(), ccgdm_create_grids(), ccgDM_drawEdges(), ccgDM_drawFacesSolid(), ccgDM_drawFacesTex_common(), ccgDM_drawMappedFaces(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgDM_drawVerts(), ccgDM_get_tessface_data_layer(), ccgDM_getFinalVert(), ccgDM_getMinMax(), ccgDM_getNumGrids(), ccgdm_getVertCos(), getCCGDerivedMesh(), getFaceIndex(), multires_mvert_to_ss(), and set_subsurf_uv().
void* ccgSubSurf_getFaceUserData (CCGSubSurf * ss, CCGFace * f)
Definition at line 2899 of file CCGSubSurf.c.
References ccg_gridsize(), FACE_getCenterData(), CCGSubSurf::meshIFC, CCGFace::numVerts, CCGSubSurf::subdivLevels, and CCGMeshIFC::vertDataSize.
Referenced by _face_new(), ccgDM_getFaceMapIndex(), ccgSubSurf__sync(), ccgSubSurf_getFaceAge(), getCCGDerivedMesh(), getFaceIndex(), and ss_sync_from_derivedmesh().
CCGVert* ccgSubSurf_getFaceVert (CCGFace * f, int index)
Definition at line 2908 of file CCGSubSurf.c.
References FACE_getVerts(), NULL, and CCGFace::numVerts.
Referenced by getCCGDerivedMesh(), and getFaceIndex().
int ccgSubSurf_getGridLevelSize (const CCGSubSurf * ss, int level)
Definition at line 2749 of file CCGSubSurf.c.
References ccg_gridsize(), and CCGSubSurf::subdivLevels.
Referenced by ccgSubSurf_getGridSize().
int ccgSubSurf_getGridSize (const CCGSubSurf * ss)
Definition at line 2745 of file CCGSubSurf.c.
References ccgSubSurf_getGridLevelSize(), and CCGSubSurf::subdivLevels.
Referenced by ccgDM_copyFinalEdgeArray(), ccgDM_copyFinalFaceArray(), ccgDM_copyFinalLoopArray(), ccgDM_copyFinalPolyArray(), ccgDM_copyFinalVertArray(), ccgDM_drawEdges(), ccgDM_drawFacesSolid(), ccgDM_drawFacesTex_common(), ccgDM_drawMappedFaces(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgDM_drawVerts(), ccgDM_get_tessface_data_layer(), ccgDM_getFinalEdge(), ccgDM_getFinalFace(), ccgDM_getFinalVert(), ccgDM_getGridSize(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), multires_mvert_to_ss(), set_subsurf_uv(), and subsurf_copy_grid_hidden().
int ccgSubSurf_getNumEdges (const CCGSubSurf * ss)
Definition at line 2706 of file CCGSubSurf.c.
References CCGSubSurf::eMap, and _EHash::numEntries.
Referenced by ccgDM_copyFinalEdgeArray(), ccgDM_copyFinalVertArray(), ccgDM_drawEdges(), ccgDM_drawLooseEdges(), ccgDM_get_edge_data_layer(), ccgDM_getFinalVert(), ccgdm_getVertCos(), getCCGDerivedMesh(), and multires_mvert_to_ss().
int ccgSubSurf_getNumFaces (const CCGSubSurf * ss)
Definition at line 2710 of file CCGSubSurf.c.
References CCGSubSurf::fMap, and _EHash::numEntries.
Referenced by ccgDM_copyFinalEdgeArray(), ccgDM_copyFinalFaceArray(), ccgDM_copyFinalLoopArray(), ccgDM_copyFinalPolyArray(), ccgDM_copyFinalVertArray(), ccgdm_create_grids(), ccgDM_drawEdges(), ccgDM_drawFacesSolid(), ccgDM_drawFacesTex_common(), ccgDM_drawMappedFaces(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgDM_get_tessface_data_layer(), ccgDM_getFinalEdge(), ccgDM_getFinalVert(), ccgDM_getNumGrids(), ccgdm_getVertCos(), getCCGDerivedMesh(), multires_mvert_to_ss(), set_subsurf_uv(), and subsurf_copy_grid_hidden().
int ccgSubSurf_getNumFinalEdges (const CCGSubSurf * ss)
Definition at line 3037 of file CCGSubSurf.c.
References ccg_edgesize(), ccg_gridsize(), CCGSubSurf::eMap, _EHash::numEntries, CCGSubSurf::numGrids, and CCGSubSurf::subdivLevels.
Referenced by ccgDM_getNumEdges(), and getCCGDerivedMesh().
int ccgSubSurf_getNumFinalFaces (const CCGSubSurf * ss)
Definition at line 3046 of file CCGSubSurf.c.
References ccg_gridsize(), CCGSubSurf::numGrids, and CCGSubSurf::subdivLevels.
Referenced by ccgDM_getNumLoops(), ccgDM_getNumTessFaces(), and getCCGDerivedMesh().
int ccgSubSurf_getNumFinalVerts (const CCGSubSurf * ss)
Definition at line 3026 of file CCGSubSurf.c.
References ccg_edgesize(), ccg_gridsize(), CCGSubSurf::eMap, CCGSubSurf::fMap, _EHash::numEntries, CCGSubSurf::numGrids, CCGSubSurf::subdivLevels, and CCGSubSurf::vMap.
Referenced by ccgDM_getNumVerts(), and getCCGDerivedMesh().
int ccgSubSurf_getNumVerts (const CCGSubSurf * ss)
Definition at line 2702 of file CCGSubSurf.c.
References _EHash::numEntries, and CCGSubSurf::vMap.
Referenced by ccgDM_copyFinalVertArray(), ccgDM_get_vert_data_layer(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and multires_mvert_to_ss().
int ccgSubSurf_getSubdivisionLevels (const CCGSubSurf * ss)
Definition at line 2728 of file CCGSubSurf.c.
References CCGSubSurf::subdivLevels.
Referenced by set_subsurf_uv(), ss_sync_from_derivedmesh(), ss_sync_from_uv(), and subsurf_copy_grid_hidden().
void ccgSubSurf_getUseAgeCounts (CCGSubSurf * ss, int * useAgeCounts_r, int * vertUserOffset_r, int * edgeUserOffset_r, int * faceUserOffset_r)
Definition at line 907 of file CCGSubSurf.c.
References CCGSubSurf::edgeUserAgeOffset, CCGSubSurf::faceUserAgeOffset, CCGSubSurf::useAgeCounts, and CCGSubSurf::vertUserAgeOffset.
Referenced by _getSubSurf(), ccgDM_drawEdges(), ccgDM_drawMappedEdges(), and ccgDM_drawMappedEdgesInterp().
CCGVert* ccgSubSurf_getVert (CCGSubSurf * ss, CCGVertHDL v)
Definition at line 2715 of file CCGSubSurf.c.
References _ehash_lookup(), and CCGSubSurf::vMap.
int ccgSubSurf_getVertAge (CCGSubSurf * ss, CCGVert * v)
Definition at line 2765 of file CCGSubSurf.c.
References ccgSubSurf_getVertUserData(), CCGSubSurf::currentAge, CCGSubSurf::useAgeCounts, and CCGSubSurf::vertUserAgeOffset.
void* ccgSubSurf_getVertData (CCGSubSurf * ss, CCGVert * v)
Definition at line 2805 of file CCGSubSurf.c.
References ccgSubSurf_getVertLevelData(), and CCGSubSurf::subdivLevels.
Referenced by ccgDM_copyFinalVertArray(), ccgDM_drawVerts(), ccgDM_foreachMappedVert(), ccgDM_getFinalVert(), ccgDM_getMinMax(), ccgdm_getVertCos(), multires_mvert_to_ss(), and subsurf_calculate_limit_positions().
CCGEdge* ccgSubSurf_getVertEdge (CCGVert * v, int index)
Definition at line 2796 of file CCGSubSurf.c.
References CCGVert::edges, NULL, and CCGVert::numEdges.
Referenced by subsurf_calculate_limit_positions().
CCGFace* ccgSubSurf_getVertFace (CCGVert * v, int index)
Definition at line 2783 of file CCGSubSurf.c.
References CCGVert::faces, NULL, and CCGVert::numFaces.
Referenced by subsurf_calculate_limit_positions().
CCGVertIterator* ccgSubSurf_getVertIterator (CCGSubSurf * ss)
Definition at line 2960 of file CCGSubSurf.c.
References _ehashIterator_new(), and CCGSubSurf::vMap.
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedVert(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and subsurf_calculate_limit_positions().
void* ccgSubSurf_getVertLevelData (CCGSubSurf * ss, CCGVert * v, int level)
Definition at line 2809 of file CCGSubSurf.c.
References _vert_getCo(), CCGSubSurf::meshIFC, NULL, CCGSubSurf::subdivLevels, and CCGMeshIFC::vertDataSize.
Referenced by ccgSubSurf_getVertData().
int ccgSubSurf_getVertNumEdges (CCGVert * v)
Definition at line 2792 of file CCGSubSurf.c.
References CCGVert::numEdges.
Referenced by subsurf_calculate_limit_positions().
int ccgSubSurf_getVertNumFaces (CCGVert * v)
Definition at line 2779 of file CCGSubSurf.c.
References CCGVert::numFaces.
Referenced by subsurf_calculate_limit_positions().
void* ccgSubSurf_getVertUserData (CCGSubSurf * ss, CCGVert * v)
Definition at line 2775 of file CCGSubSurf.c.
References CCGSubSurf::meshIFC, CCGSubSurf::subdivLevels, VERT_getLevelData(), and CCGMeshIFC::vertDataSize.
Referenced by _vert_new(), ccgDM_getVertMapIndex(), ccgSubSurf__sync(), ccgSubSurf_getVertAge(), getCCGDerivedMesh(), getEdgeIndex(), getFaceIndex(), and ss_sync_from_derivedmesh().
CCGVertHDL ccgSubSurf_getVertVertHandle (CCGVert * v)
Definition at line 2761 of file CCGSubSurf.c.
References CCGVert::vHDL.
Referenced by ccgdm_getVertCos(), getCCGDerivedMesh(), and subsurf_calculate_limit_positions().
CCGError ccgSubSurf_initFullSync (CCGSubSurf * ss)
Definition at line 961 of file CCGSubSurf.c.
References _ehash_new(), CCGSubSurf::allocator, CCGSubSurf::allocatorIFC, CCGSubSurf::currentAge, eCCGError_InvalidSyncState, eCCGError_None, CCGSubSurf::eMap, eSyncState_None, eSyncState_Vert, CCGSubSurf::fMap, CCGSubSurf::lenTempArrays, MEM_mallocN(), CCGSubSurf::numGrids, CCGSubSurf::oldEMap, CCGSubSurf::oldFMap, CCGSubSurf::oldVMap, CCGSubSurf::syncState, CCGSubSurf::tempEdges, CCGSubSurf::tempVerts, and CCGSubSurf::vMap.
Referenced by ss_sync_from_derivedmesh(), and ss_sync_from_uv().
CCGError ccgSubSurf_initPartialSync (CCGSubSurf * ss)
Definition at line 988 of file CCGSubSurf.c.
References CCGSubSurf::currentAge, eCCGError_InvalidSyncState, eCCGError_None, eSyncState_None, eSyncState_Partial, and CCGSubSurf::syncState.
CCGSubSurf* ccgSubSurf_new (CCGMeshIFC * ifc, int subdivisionLevels, CCGAllocatorIFC * allocatorIFC, CCGAllocatorHDL allocator)
Definition at line 781 of file CCGSubSurf.c.
References _ehash_new(), _getStandardAllocatorIFC(), CCGAllocatorIFC::alloc, CCGSubSurf::allocator, CCGSubSurf::allocatorIFC, CCGSubSurf::allowEdgeCreation, CCGSubSurf::calcVertNormals, CCGSUBSURF_alloc, CCGSubSurf::currentAge, CCGSubSurf::defaultCreaseValue, CCGSubSurf::defaultEdgeUserData, CCGSubSurf::edgeUserAgeOffset, CCGSubSurf::eMap, eSyncState_None, CCGSubSurf::faceUserAgeOffset, CCGSubSurf::fMap, CCGSubSurf::lenTempArrays, CCGSubSurf::meshIFC, CCGSubSurf::normalDataOffset, NULL, CCGSubSurf::numGrids, CCGSubSurf::oldEMap, CCGSubSurf::oldFMap, CCGSubSurf::oldVMap, CCGSubSurf::q, CCGSubSurf::r, CCGSubSurf::subdivLevels, CCGSubSurf::syncState, CCGSubSurf::tempEdges, CCGSubSurf::tempVerts, CCGSubSurf::useAgeCounts, CCGMeshIFC::vertDataSize, CCGSubSurf::vertUserAgeOffset, and CCGSubSurf::vMap.
Referenced by _getSubSurf().
CCGError ccgSubSurf_processSync (CCGSubSurf * ss)
Definition at line 1306 of file CCGSubSurf.c.
References _edge_unlinkMarkAndFree(), _ehash_free(), _face_unlinkMarkAndFree(), _vert_free(), ccgSubSurf__sync(), eCCGError_InvalidSyncState, eCCGError_None, eSyncState_None, eSyncState_Partial, CCGSubSurf::lenTempArrays, MEM_freeN(), NULL, CCGSubSurf::oldEMap, CCGSubSurf::oldFMap, CCGSubSurf::oldVMap, CCGSubSurf::syncState, CCGSubSurf::tempEdges, and CCGSubSurf::tempVerts.
Referenced by ss_sync_from_derivedmesh(), and ss_sync_from_uv().
CCGError ccgSubSurf_setAllowEdgeCreation (CCGSubSurf * ss, int allowEdgeCreation, float defaultCreaseValue, void * defaultUserData)
Definition at line 860 of file CCGSubSurf.c.
References CCGSubSurf::allowEdgeCreation, CCGSUBSURF_alloc, CCGSUBSURF_free, CCGSubSurf::defaultCreaseValue, CCGSubSurf::defaultEdgeUserData, eCCGError_None, CCGMeshIFC::edgeUserSize, and CCGSubSurf::meshIFC.
CCGError ccgSubSurf_setCalcVertexNormals (CCGSubSurf * ss, int useVertNormals, int normalDataOffset)
Definition at line 940 of file CCGSubSurf.c.
References CCGSubSurf::calcVertNormals, eCCGError_InvalidValue, eCCGError_None, CCGSubSurf::meshIFC, CCGSubSurf::normalDataOffset, and CCGMeshIFC::vertDataSize.
Referenced by _getSubSurf().
CCGError ccgSubSurf_setSubdivisionLevels (CCGSubSurf * ss, int subdivisionLevels)
Definition at line 888 of file CCGSubSurf.c.
References _edge_free(), _ehash_free(), _ehash_new(), _face_free(), _vert_free(), CCGSubSurf::allocator, CCGSubSurf::allocatorIFC, eCCGError_InvalidValue, eCCGError_None, CCGSubSurf::eMap, CCGSubSurf::fMap, CCGSubSurf::numGrids, CCGSubSurf::subdivLevels, and CCGSubSurf::vMap.
Referenced by _getSubSurf().
CCGError ccgSubSurf_setUseAgeCounts (CCGSubSurf * ss, int useAgeCounts, int vertUserOffset, int edgeUserOffset, int faceUserOffset)
Definition at line 916 of file CCGSubSurf.c.
References eCCGError_InvalidValue, eCCGError_None, CCGSubSurf::edgeUserAgeOffset, CCGMeshIFC::edgeUserSize, CCGSubSurf::faceUserAgeOffset, CCGMeshIFC::faceUserSize, CCGSubSurf::meshIFC, CCGSubSurf::useAgeCounts, CCGSubSurf::vertUserAgeOffset, and CCGMeshIFC::vertUserSize.
Referenced by _getSubSurf().
CCGError ccgSubSurf_stitchFaces (CCGSubSurf * ss, int lvl, CCGFace ** faces, int numFaces)
Definition at line 2497 of file CCGSubSurf.c.
References _edge_getCoVert(), ccg_edgesize(), ccg_gridsize(), ccgSubSurf__allFaces(), ccgSubSurf__effectedFaceNeighbours(), eCCGError_None, Edge_eEffected, EDGE_getCo, FACE_getCenterData(), FACE_getEdges(), FACE_getIECo, FACE_getIFCo, FACE_getVerts(), i, MEM_freeN(), CCGSubSurf::meshIFC, CCGVert::numFaces, CCGEdge::numFaces, CCGFace::numVerts, CCGSubSurf::subdivLevels, CCGEdge::v0, CCGEdge::v1, Vert_eEffected, VERT_getCo, VertDataAdd, VertDataCopy, VertDataMulN, CCGMeshIFC::vertDataSize, and VertDataZero.
Referenced by multires_stitch_grids(), and multiresModifier_disp_run().
CCGError ccgSubSurf_syncEdge (CCGSubSurf * ss, CCGEdgeHDL eHDL, CCGVertHDL e_vHDL0, CCGVertHDL e_vHDL1, float crease, CCGEdge ** e_r)
Definition at line 1126 of file CCGSubSurf.c.
References _edge_new(), _edge_unlinkMarkAndFree(), _ehash_insert(), _ehash_lookup(), _ehash_lookupWithPrev(), CCGEdge::crease, eCCGError_InvalidSyncState, eCCGError_None, CCGSubSurf::eMap, eSyncState_Edge, eSyncState_Partial, eSyncState_Vert, CCGEdge::next, NULL, CCGSubSurf::oldEMap, CCGSubSurf::syncState, CCGEdge::v0, CCGEdge::v1, Vert_eChanged, Vert_eEffected, CCGVert::vHDL, and CCGSubSurf::vMap.
Referenced by ss_sync_from_derivedmesh(), and ss_sync_from_uv().
CCGError ccgSubSurf_syncEdgeDel (CCGSubSurf * ss, CCGEdgeHDL eHDL)
Definition at line 1022 of file CCGSubSurf.c.
References _edge_unlinkMarkAndFree(), _ehash_lookupWithPrev(), eCCGError_InvalidSyncState, eCCGError_InvalidValue, eCCGError_None, CCGSubSurf::eMap, eSyncState_Partial, CCGEdge::next, CCGEdge::numFaces, and CCGSubSurf::syncState.
CCGError ccgSubSurf_syncFace (CCGSubSurf * ss, CCGFaceHDL fHDL, int numVerts, CCGVertHDL * vHDLs, CCGFace ** f_r)
Definition at line 1185 of file CCGSubSurf.c.
References _edge_new(), _ehash_insert(), _ehash_lookup(), _ehash_lookupWithPrev(), _face_new(), _face_unlinkMarkAndFree(), _vert_findEdgeTo(), CCGSubSurf::allowEdgeCreation, ccgSubSurf_getEdgeUserData(), CCGSubSurf::defaultCreaseValue, CCGSubSurf::defaultEdgeUserData, eCCGError_InvalidSyncState, eCCGError_InvalidValue, eCCGError_None, CCGMeshIFC::edgeUserSize, CCGSubSurf::eMap, eSyncState_Edge, eSyncState_Face, eSyncState_Partial, eSyncState_Vert, FACE_getEdges(), FACE_getVerts(), CCGVert::flags, CCGSubSurf::fMap, CCGSubSurf::lenTempArrays, MEM_reallocN(), CCGSubSurf::meshIFC, CCGFace::next, NULL, CCGSubSurf::numGrids, CCGFace::numVerts, CCGSubSurf::oldFMap, CCGSubSurf::syncState, CCGSubSurf::tempEdges, CCGSubSurf::tempVerts, Vert_eChanged, Vert_eEffected, and CCGSubSurf::vMap.
Referenced by ss_sync_from_derivedmesh(), and ss_sync_from_uv().
CCGError ccgSubSurf_syncFaceDel (CCGSubSurf * ss, CCGFaceHDL fHDL)
Definition at line 1043 of file CCGSubSurf.c.
References _ehash_lookupWithPrev(), _face_unlinkMarkAndFree(), eCCGError_InvalidSyncState, eCCGError_InvalidValue, eCCGError_None, eSyncState_Partial, CCGSubSurf::fMap, CCGFace::next, and CCGSubSurf::syncState.
CCGError ccgSubSurf_syncVert (CCGSubSurf * ss, CCGVertHDL vHDL, const void * vertData, int seam, CCGVert ** v_r)
Definition at line 1064 of file CCGSubSurf.c.
References _ehash_insert(), _ehash_lookupWithPrev(), _vert_getCo(), _vert_new(), eCCGError_InvalidSyncState, eCCGError_None, CCGVert::edges, eSyncState_Partial, eSyncState_Vert, FACE_getVerts(), CCGVert::faces, CCGVert::flags, i, CCGSubSurf::meshIFC, CCGVert::next, NULL, CCGVert::numEdges, CCGVert::numFaces, CCGFace::numVerts, CCGSubSurf::oldVMap, CCGSubSurf::syncState, CCGEdge::v0, CCGEdge::v1, Vert_eChanged, Vert_eEffected, Vert_eSeam, VertDataCopy, VertDataEqual(), CCGMeshIFC::vertDataSize, and CCGSubSurf::vMap.
Referenced by ss_sync_from_derivedmesh(), and ss_sync_from_uv().
CCGError ccgSubSurf_syncVertDel (CCGSubSurf * ss, CCGVertHDL vHDL)
Definition at line 1001 of file CCGSubSurf.c.
References _ehash_lookupWithPrev(), _vert_free(), eCCGError_InvalidSyncState, eCCGError_InvalidValue, eCCGError_None, eSyncState_Partial, CCGVert::next, CCGVert::numEdges, CCGVert::numFaces, CCGSubSurf::syncState, and CCGSubSurf::vMap.
CCGError ccgSubSurf_updateFromFaces (CCGSubSurf * ss, int lvl, CCGFace ** faces, int numFaces)
Definition at line 2415 of file CCGSubSurf.c.
References _edge_getCoVert(), ccg_gridsize(), ccgSubSurf__allFaces(), eCCGError_None, FACE_getCenterData(), FACE_getEdges(), FACE_getIECo, FACE_getIFCo, FACE_getVerts(), i, MEM_freeN(), CCGSubSurf::meshIFC, CCGFace::numVerts, CCGSubSurf::subdivLevels, VERT_getCo, VertDataCopy, and CCGMeshIFC::vertDataSize.
Referenced by ccgdm_pbvh_update(), multires_modifier_update_mdisps(), and multires_subdivide().
CCGError ccgSubSurf_updateLevels (CCGSubSurf * ss, int lvl, CCGFace ** faces, int numFaces)
Definition at line 2664 of file CCGSubSurf.c.
References ccgSubSurf__allFaces(), ccgSubSurf__calcSubdivLevel(), ccgSubSurf__effectedFaceNeighbours(), eCCGError_None, i, MEM_freeN(), and CCGSubSurf::subdivLevels.
Referenced by multires_modifier_update_mdisps(), and multires_subdivide().
CCGError ccgSubSurf_updateNormals (CCGSubSurf * ss, CCGFace ** faces, int numFaces)
Definition at line 2632 of file CCGSubSurf.c.
References CCGSubSurf::calcVertNormals, ccgSubSurf__allFaces(), ccgSubSurf__calcVertNormals(), ccgSubSurf__effectedFaceNeighbours(), eCCGError_None, i, and MEM_freeN().
Referenced by ccgdm_pbvh_update(), and multiresModifier_disp_run().
CCGError ccgSubSurf_updateToFaces (CCGSubSurf * ss, int lvl, CCGFace ** faces, int numFaces)
Definition at line 2454 of file CCGSubSurf.c.
References _edge_getCoVert(), ccg_gridsize(), ccgSubSurf__allFaces(), eCCGError_None, FACE_getCenterData(), FACE_getEdges(), FACE_getIECo, FACE_getIFCo, FACE_getVerts(), i, MEM_freeN(), CCGSubSurf::meshIFC, CCGFace::numVerts, CCGSubSurf::subdivLevels, VERT_getCo, VertDataCopy, and CCGMeshIFC::vertDataSize.
Referenced by multires_mvert_to_ss().
void ccgVertIterator_free (CCGVertIterator * vi)
Definition at line 2985 of file CCGSubSurf.c.
References _ehashIterator_free().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedVert(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and subsurf_calculate_limit_positions().
CCGVert* ccgVertIterator_getCurrent (CCGVertIterator * vi)
Definition at line 2973 of file CCGSubSurf.c.
References _ehashIterator_getCurrent().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedVert(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and subsurf_calculate_limit_positions().
int ccgVertIterator_isStopped (CCGVertIterator * vi)
Definition at line 2977 of file CCGSubSurf.c.
References _ehashIterator_isStopped().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedVert(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and subsurf_calculate_limit_positions().
void ccgVertIterator_next (CCGVertIterator * vi)
Definition at line 2981 of file CCGSubSurf.c.
References _ehashIterator_next().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedVert(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and subsurf_calculate_limit_positions().