Blender: GPG_Application.cpp File Reference
GPG_Application.cpp File Reference
Game Player
#include "GL/glew.h"
#include "GPU_extensions.h"
#include "GPG_Application.h"
#include "BL_BlenderDataConversion.h"
#include <iostream>
#include <MT_assert.h>
#include <stdlib.h>
#include "BLI_blenlib.h"
#include "BLO_readfile.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_sound.h"
#include "IMB_imbuf.h"
#include "DNA_scene_types.h"
#include "BL_System.h"
#include "KX_KetsjiEngine.h"
#include "CTR_Map.h"
#include "SCA_IActuator.h"
#include "RAS_MeshObject.h"
#include "RAS_OpenGLRasterizer.h"
#include "RAS_VAOpenGLRasterizer.h"
#include "RAS_ListRasterizer.h"
#include "RAS_GLExtensionManager.h"
#include "KX_PythonInit.h"
#include "KX_PyConstraintBinding.h"
#include "BL_Material.h"
#include "KX_BlenderSceneConverter.h"
#include "NG_LoopBackNetworkDeviceInterface.h"
#include "GPC_MouseDevice.h"
#include "GPC_RenderTools.h"
#include "GPG_Canvas.h"
#include "GPG_KeyboardDevice.h"
#include "GPG_System.h"
#include "STR_String.h"
#include "GHOST_ISystem.h"
#include "GHOST_IEvent.h"
#include "GHOST_IEventConsumer.h"
#include "GHOST_IWindow.h"
#include "GHOST_Rect.h"
Functions
static void frameTimerProc (GHOST_ITimerTask *task, GHOST_TUns64 time)
Variables
static GHOST_ISystem * fSystem = 0
static const int kTimerFreq = 10
Detailed Description
Definition in file GPG_Application.cpp.
Function Documentation
static void frameTimerProc (GHOST_ITimerTask * task, GHOST_TUns64 time) [static]
Definition at line 933 of file GPG_Application.cpp.
References GHOST_ITimerTask::getUserData(), GHOST_IWindow::invalidate(), and GHOST_ISystem::validWindow().
Referenced by GPG_Application::startEngine().
Variable Documentation
GHOST_ISystem* fSystem = 0 [static]
Definition at line 105 of file GPG_Application.cpp.
const int kTimerFreq = 10 [static]
Definition at line 106 of file GPG_Application.cpp.
Referenced by GPG_Application::startEngine().