Blender: DualConInputReader Class Reference
DualConInputReader Class Reference
Public Member Functions
DualConInputReader (const DualConInput *mesh, float _scale)
void reset ()
Reset file reading location.
Triangle * getNextTriangle ()
Get next triangle.
int getNextTriangle (int t[3])
int getNumTriangles ()
Get number of triangles.
int getNumVertices ()
For explicit vertex models.
float getBoundingBox (float origin[3])
Get bounding box.
void getNextVertex (float v[3])
void printInfo ()
int getMemory ()
Get storage size.
Detailed Description
Definition at line 48 of file dualcon_c_api.cpp.
Constructor & Destructor Documentation
DualConInputReader::DualConInputReader (const DualConInput * mesh, float _scale) [inline]
Definition at line 56 of file dualcon_c_api.cpp.
References reset().
Referenced by getMemory().
Member Function Documentation
float DualConInputReader::getBoundingBox (float origin[3]) [inline, virtual]
Get bounding box.
Implements ModelReader.
Definition at line 170 of file dualcon_c_api.cpp.
References veccopy().
int DualConInputReader::getMemory () [inline, virtual]
Get storage size.
Implements ModelReader.
Definition at line 184 of file dualcon_c_api.cpp.
References DualConInputReader().
Triangle* DualConInputReader::getNextTriangle () [inline, virtual]
Get next triangle.
Implements ModelReader.
Definition at line 95 of file dualcon_c_api.cpp.
References co, GET_CO, GET_FACE, i, isnan(), DualConInput::totface, veccopy(), and Triangle::vt.
int DualConInputReader::getNextTriangle (int t[3]) [inline, virtual]
Implements ModelReader.
Definition at line 133 of file dualcon_c_api.cpp.
References GET_FACE, and DualConInput::totface.
void DualConInputReader::getNextVertex (float v[3]) [inline, virtual]
Implements ModelReader.
Definition at line 177 of file dualcon_c_api.cpp.
int DualConInputReader::getNumTriangles () [inline, virtual]
Get number of triangles.
Implements ModelReader.
Definition at line 160 of file dualcon_c_api.cpp.
int DualConInputReader::getNumVertices () [inline, virtual]
For explicit vertex models.
Implements ModelReader.
Definition at line 165 of file dualcon_c_api.cpp.
References DualConInput::totco.
void DualConInputReader::printInfo () [inline, virtual]
Implements ModelReader.
Definition at line 183 of file dualcon_c_api.cpp.
void DualConInputReader::reset () [inline, virtual]
Reset file reading location.
Implements ModelReader.
Definition at line 62 of file dualcon_c_api.cpp.
References GET_FACE, i, DualConInput::max, DualConInput::min, DualConInput::totface, and veccopy().
Referenced by DualConInputReader().
The documentation for this class was generated from the following file:
dualcon_c_api.cpp