Blender: array< T > Class Template Reference
array< T > Class Template Reference
#include <util_vector.h>
Public Member Functions
array ()
array (size_t newsize)
array (const array &from)
array & operator= (const array &from)
array & operator= (const vector< T > &from)
~array ()
void resize (size_t newsize)
void clear ()
size_t size () const
T & operator[] (size_t i) const
Protected Attributes
T * data
size_t datasize
Detailed Description
template<typename T>
class array< T >
Definition at line 39 of file util_vector.h.
Constructor & Destructor Documentation
template<typename T> array< T >::array () [inline]
Definition at line 42 of file util_vector.h.
template<typename T> array< T >::array (size_t newsize) [inline]
Definition at line 48 of file util_vector.h.
template<typename T> array< T >::array (const array< T > & from) [inline]
Definition at line 60 of file util_vector.h.
template<typename T> array< T >::~array () [inline]
Definition at line 93 of file util_vector.h.
Member Function Documentation
template<typename T> void array< T >::clear () [inline]
Definition at line 113 of file util_vector.h.
Referenced by BVH::pack_instances(), QBVH::pack_nodes(), RegularBVH::pack_nodes(), BVH::pack_triangles(), and array< uint4 >::resize().
template<typename T> array& array< T >::operator= (const array< T > & from) [inline]
Definition at line 65 of file util_vector.h.
template<typename T> array& array< T >::operator= (const vector< T > & from) [inline]
Definition at line 80 of file util_vector.h.
template<typename T> T& array< T >::operator[] (size_t i) const [inline]
Definition at line 125 of file util_vector.h.
template<typename T> void array< T >::resize (size_t newsize) [inline]
Definition at line 98 of file util_vector.h.
Referenced by BVH::pack_instances(), QBVH::pack_nodes(), RegularBVH::pack_nodes(), BVH::pack_triangles(), and CacheData::read().
template<typename T> size_t array< T >::size () const [inline]
Definition at line 120 of file util_vector.h.
Referenced by CacheData::add(), MeshManager::device_update_bvh(), BVH::pack_instances(), and BVH::pack_triangles().
Member Data Documentation
template<typename T> T* array< T >::data [protected]
Definition at line 131 of file util_vector.h.
Referenced by array< uint4 >::array(), array< uint4 >::clear(), array< uint4 >::operator=(), array< uint4 >::operator[](), array< uint4 >::resize(), and array< uint4 >::~array().
template<typename T> size_t array< T >::datasize [protected]
Definition at line 132 of file util_vector.h.
Referenced by array< uint4 >::array(), array< uint4 >::clear(), array< uint4 >::operator=(), array< uint4 >::resize(), and array< uint4 >::size().
The documentation for this class was generated from the following file:
util_vector.h