Blender: KX_WorldInfo Class Reference
KX_WorldInfo Class Reference
#include <KX_WorldInfo.h>
Public Member Functions
KX_WorldInfo ()
virtual ~KX_WorldInfo ()
virtual bool hasWorld ()=0
virtual bool hasMist ()=0
virtual float getBackColorRed ()=0
virtual float getBackColorGreen ()=0
virtual float getBackColorBlue ()=0
virtual float getMistStart ()=0
virtual float getMistDistance ()=0
virtual float getMistColorRed ()=0
virtual float getMistColorGreen ()=0
virtual float getMistColorBlue ()=0
virtual float getAmbientColorRed ()=0
virtual float getAmbientColorGreen ()=0
virtual float getAmbientColorBlue ()=0
virtual void setBackColor (float, float, float)=0
virtual void setMistStart (float)=0
virtual void setMistDistance (float)=0
virtual void setMistColorRed (float)=0
virtual void setMistColorGreen (float)=0
virtual void setMistColorBlue (float)=0
Detailed Description
Definition at line 43 of file KX_WorldInfo.h.
Constructor & Destructor Documentation
KX_WorldInfo::KX_WorldInfo () [inline]
Definition at line 46 of file KX_WorldInfo.h.
KX_WorldInfo::~KX_WorldInfo () [virtual]
Definition at line 35 of file KX_WorldInfo.cpp.
Member Function Documentation
virtual float KX_WorldInfo::getAmbientColorBlue () [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_KetsjiEngine::SetWorldSettings().
virtual float KX_WorldInfo::getAmbientColorGreen () [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_KetsjiEngine::SetWorldSettings().
virtual float KX_WorldInfo::getAmbientColorRed () [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_KetsjiEngine::SetWorldSettings().
virtual float KX_WorldInfo::getBackColorBlue () [pure virtual]
Implemented in BlenderWorldInfo.
virtual float KX_WorldInfo::getBackColorGreen () [pure virtual]
Implemented in BlenderWorldInfo.
virtual float KX_WorldInfo::getBackColorRed () [pure virtual]
Implemented in BlenderWorldInfo.
virtual float KX_WorldInfo::getMistColorBlue () [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_KetsjiEngine::SetWorldSettings().
virtual float KX_WorldInfo::getMistColorGreen () [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_KetsjiEngine::SetWorldSettings().
virtual float KX_WorldInfo::getMistColorRed () [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_KetsjiEngine::SetWorldSettings().
virtual float KX_WorldInfo::getMistDistance () [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_KetsjiEngine::SetWorldSettings().
virtual float KX_WorldInfo::getMistStart () [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_KetsjiEngine::SetWorldSettings().
virtual bool KX_WorldInfo::hasMist () [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_KetsjiEngine::SetWorldSettings().
virtual bool KX_WorldInfo::hasWorld () [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_KetsjiEngine::SetWorldSettings().
virtual void KX_WorldInfo::setBackColor (float , float , float) [pure virtual]
Implemented in BlenderWorldInfo.
virtual void KX_WorldInfo::setMistColorBlue (float) [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_WorldIpoController::Update().
virtual void KX_WorldInfo::setMistColorGreen (float) [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_WorldIpoController::Update().
virtual void KX_WorldInfo::setMistColorRed (float) [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_WorldIpoController::Update().
virtual void KX_WorldInfo::setMistDistance (float) [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_WorldIpoController::Update().
virtual void KX_WorldInfo::setMistStart (float) [pure virtual]
Implemented in BlenderWorldInfo.
Referenced by KX_WorldIpoController::Update().
The documentation for this class was generated from the following files:
KX_WorldInfo.h
KX_WorldInfo.cpp