Blender: TNT::Vector< T > Class Template Reference
TNT::Vector< T > Class Template Reference
#include <vec.h>
Public Types
typedef Subscript size_type
typedef T value_type
typedef T element_type
typedef T * pointer
typedef T * iterator
typedef T & reference
typedef const T * const_iterator
typedef const T & const_reference
typedef Subscript size_type
typedef T value_type
typedef T element_type
typedef T * pointer
typedef T * iterator
typedef T & reference
typedef const T * const_iterator
typedef const T & const_reference
Public Member Functions
Subscript lbound () const
iterator begin ()
iterator end ()
const iterator begin () const
const iterator end () const
~Vector ()
Vector ()
Vector (const Vector< T > &A)
Vector (Subscript N, const T &value=T())
Vector (Subscript N, const T *v)
Vector< T > & newsize (Subscript N)
Vector< T > & operator= (const Vector< T > &A)
Vector< T > & operator= (const T &scalar)
Subscript dim () const
Subscript size () const
reference operator() (Subscript i)
const_reference operator() (Subscript i) const
reference operator[] (Subscript i)
const_reference operator[] (Subscript i) const
Subscript lbound () const
iterator begin ()
iterator end ()
iterator begin () const
iterator end () const
~Vector ()
Vector ()
Vector (const Vector< T > &A)
Vector (Subscript N, const T &value=T())
Vector (Subscript N, const T *v)
Vector (Subscript N, char *s)
Vector< T > & newsize (Subscript N)
Vector< T > & operator= (const Vector< T > &A)
Vector< T > & operator= (const T &scalar)
Subscript dim () const
Subscript size () const
reference operator() (Subscript i)
const_reference operator() (Subscript i) const
reference operator[] (Subscript i)
const_reference operator[] (Subscript i) const
Protected Member Functions
void initialize (Subscript N)
void copy (const T *v)
void set (const T &val)
void destroy ()
void initialize (Subscript N)
void copy (const T *v)
void set (const T &val)
void destroy ()
Protected Attributes
T * v_
T * vm1_
Subscript n_
Detailed Description
template<class T>
class TNT::Vector< T >
[Deprecatred] Value-based vector class from pre-1.0 TNT version. Kept here for backward compatiblity, but should use the newer TNT::Array1D classes instead.
Definition at line 44 of file vec.h.
Member Typedef Documentation
template<class T> typedef const T* TNT::Vector< T >::const_iterator
Definition at line 56 of file vec.h.
template<class T> typedef const T* TNT::Vector< T >::const_iterator
Definition at line 57 of file tnt_vec.h.
template<class T> typedef const T& TNT::Vector< T >::const_reference
Definition at line 57 of file vec.h.
template<class T> typedef const T& TNT::Vector< T >::const_reference
Definition at line 58 of file tnt_vec.h.
template<class T> typedef T TNT::Vector< T >::element_type
Definition at line 53 of file tnt_vec.h.
template<class T> typedef T TNT::Vector< T >::element_type
Definition at line 52 of file vec.h.
template<class T> typedef T* TNT::Vector< T >::iterator
Definition at line 54 of file vec.h.
template<class T> typedef T* TNT::Vector< T >::iterator
Definition at line 55 of file tnt_vec.h.
template<class T> typedef T* TNT::Vector< T >::pointer
Definition at line 54 of file tnt_vec.h.
template<class T> typedef T* TNT::Vector< T >::pointer
Definition at line 53 of file vec.h.
template<class T> typedef T& TNT::Vector< T >::reference
Definition at line 55 of file vec.h.
template<class T> typedef T& TNT::Vector< T >::reference
Definition at line 56 of file tnt_vec.h.
template<class T> typedef Subscript TNT::Vector< T >::size_type
Definition at line 51 of file tnt_vec.h.
template<class T> typedef Subscript TNT::Vector< T >::size_type
Definition at line 50 of file vec.h.
template<class T> typedef T TNT::Vector< T >::value_type
Definition at line 51 of file vec.h.
template<class T> typedef T TNT::Vector< T >::value_type
Definition at line 52 of file tnt_vec.h.
Constructor & Destructor Documentation
template<class T> TNT::Vector< T >::~Vector () [inline]
Definition at line 160 of file vec.h.
template<class T> TNT::Vector< T >::Vector () [inline]
Definition at line 167 of file vec.h.
template<class T> TNT::Vector< T >::Vector (const Vector< T > & A) [inline]
Definition at line 169 of file vec.h.
template<class T> TNT::Vector< T >::Vector (Subscript N, const T & value = T()) [inline]
Definition at line 175 of file vec.h.
template<class T> TNT::Vector< T >::Vector (Subscript N, const T * v) [inline]
Definition at line 181 of file vec.h.
template<class T> TNT::Vector< T >::~Vector () [inline]
Definition at line 161 of file tnt_vec.h.
template<class T> TNT::Vector< T >::Vector () [inline]
Definition at line 168 of file tnt_vec.h.
template<class T> TNT::Vector< T >::Vector (const Vector< T > & A) [inline]
Definition at line 170 of file tnt_vec.h.
template<class T> TNT::Vector< T >::Vector (Subscript N, const T & value = T()) [inline]
Definition at line 176 of file tnt_vec.h.
template<class T> TNT::Vector< T >::Vector (Subscript N, const T * v) [inline]
Definition at line 182 of file tnt_vec.h.
template<class T> TNT::Vector< T >::Vector (Subscript N, char * s) [inline]
Definition at line 188 of file tnt_vec.h.
Member Function Documentation
template<class T> iterator TNT::Vector< T >::begin () [inline]
Definition at line 153 of file vec.h.
Referenced by LOD_NdQuadric::Optimize(), and Upper_symmetric_eigenvalue_solve().
template<class T> const iterator TNT::Vector< T >::begin () const [inline]
Definition at line 155 of file vec.h.
template<class T> iterator TNT::Vector< T >::begin () [inline]
Definition at line 154 of file tnt_vec.h.
template<class T> iterator TNT::Vector< T >::begin () const [inline]
Definition at line 156 of file tnt_vec.h.
template<class T> void TNT::Vector< T >::copy (const T * v) [inline, protected]
Definition at line 82 of file tnt_vec.h.
template<class T> void TNT::Vector< T >::copy (const T * v) [inline, protected]
Definition at line 81 of file vec.h.
Referenced by TNT::Vector< Subscript >::operator=(), and TNT::Vector< Subscript >::Vector().
template<class T> void TNT::Vector< T >::destroy () [inline, protected]
Definition at line 136 of file vec.h.
Referenced by TNT::Vector< Subscript >::newsize(), TNT::Vector< Subscript >::operator=(), and TNT::Vector< Subscript >::~Vector().
template<class T> void TNT::Vector< T >::destroy () [inline, protected]
Definition at line 137 of file tnt_vec.h.
template<class T> Subscript TNT::Vector< T >::dim () const [inline]
Definition at line 227 of file vec.h.
Referenced by TNT::Matrix< MT_Scalar >::diagonal(), TNT::dot_prod(), TNT::matmult(), TNT::matmultdiag(), TNT::operator*(), TNT::operator+(), TNT::operator-(), TNT::QR_solve(), TNT::R_solve(), TNT::vectoradd(), TNT::vectorscale(), and TNT::vectorsub().
template<class T> Subscript TNT::Vector< T >::dim () const [inline]
Definition at line 239 of file tnt_vec.h.
template<class T> const iterator TNT::Vector< T >::end () const [inline]
Definition at line 156 of file vec.h.
template<class T> iterator TNT::Vector< T >::end () [inline]
Definition at line 155 of file tnt_vec.h.
template<class T> iterator TNT::Vector< T >::end () const [inline]
Definition at line 157 of file tnt_vec.h.
template<class T> iterator TNT::Vector< T >::end () [inline]
Definition at line 154 of file vec.h.
Referenced by LOD_NdQuadric::Optimize().
template<class T> void TNT::Vector< T >::initialize (Subscript N) [inline, protected]
Definition at line 70 of file tnt_vec.h.
template<class T> void TNT::Vector< T >::initialize (Subscript N) [inline, protected]
Definition at line 69 of file vec.h.
Referenced by TNT::Vector< Subscript >::newsize(), TNT::Vector< Subscript >::operator=(), and TNT::Vector< Subscript >::Vector().
template<class T> Subscript TNT::Vector< T >::lbound () const [inline]
Definition at line 60 of file tnt_vec.h.
template<class T> Subscript TNT::Vector< T >::lbound () const [inline]
Definition at line 59 of file vec.h.
Referenced by TNT::QR_factor(), TNT::QR_solve(), and TNT::R_solve().
template<class T> Vector<T>& TNT::Vector< T >::newsize (Subscript N) [inline]
Definition at line 190 of file vec.h.
Referenced by IK_QJacobian::ArmMatrices(), eigenvalue_solve(), TNT::operator>>(), and TNT::QR_factor().
template<class T> Vector<T>& TNT::Vector< T >::newsize (Subscript N) [inline]
Definition at line 202 of file tnt_vec.h.
template<class T> const_reference TNT::Vector< T >::operator() (Subscript i) const [inline]
Definition at line 247 of file vec.h.
template<class T> reference TNT::Vector< T >::operator() (Subscript i) [inline]
Definition at line 250 of file tnt_vec.h.
template<class T> const_reference TNT::Vector< T >::operator() (Subscript i) const [inline]
Definition at line 259 of file tnt_vec.h.
template<class T> reference TNT::Vector< T >::operator() (Subscript i) [inline]
Definition at line 238 of file vec.h.
template<class T> Vector<T>& TNT::Vector< T >::operator= (const T & scalar) [inline]
Definition at line 233 of file tnt_vec.h.
template<class T> Vector<T>& TNT::Vector< T >::operator= (const Vector< T > & A) [inline]
Definition at line 203 of file vec.h.
template<class T> Vector<T>& TNT::Vector< T >::operator= (const T & scalar) [inline]
Definition at line 221 of file vec.h.
template<class T> Vector<T>& TNT::Vector< T >::operator= (const Vector< T > & A) [inline]
Definition at line 215 of file tnt_vec.h.
template<class T> reference TNT::Vector< T >::operator[] (Subscript i) [inline]
Definition at line 256 of file vec.h.
template<class T> const_reference TNT::Vector< T >::operator[] (Subscript i) const [inline]
Definition at line 277 of file tnt_vec.h.
template<class T> reference TNT::Vector< T >::operator[] (Subscript i) [inline]
Definition at line 268 of file tnt_vec.h.
template<class T> const_reference TNT::Vector< T >::operator[] (Subscript i) const [inline]
Definition at line 265 of file vec.h.
template<class T> void TNT::Vector< T >::set (const T & val) [inline, protected]
Definition at line 108 of file tnt_vec.h.
template<class T> void TNT::Vector< T >::set (const T & val) [inline, protected]
Definition at line 107 of file vec.h.
template<class T> Subscript TNT::Vector< T >::size () const [inline]
Definition at line 232 of file vec.h.
Referenced by IK_QJacobian::AngleUpdateNorm(), IK_QJacobian::ComputeNullProjection(), TNT::operator>>(), TNT::QR_factor(), IK_QJacobian::Restrict(), and IK_QJacobian::SubTask().
template<class T> Subscript TNT::Vector< T >::size () const [inline]
Definition at line 244 of file tnt_vec.h.
Member Data Documentation
template<class T> Subscript TNT::Vector< T >::n_ [protected]
Definition at line 64 of file vec.h.
Referenced by TNT::Vector< Subscript >::copy(), TNT::Vector< Subscript >::dim(), TNT::Vector< Subscript >::end(), TNT::Vector< Subscript >::initialize(), TNT::Vector< Subscript >::newsize(), TNT::Vector< Subscript >::operator()(), TNT::Vector< Subscript >::operator=(), TNT::Vector< Subscript >::operator[](), TNT::Vector< Subscript >::set(), TNT::Vector< Subscript >::size(), and TNT::Vector< Subscript >::Vector().
template<class T> T * TNT::Vector< T >::v_ [protected]
Definition at line 62 of file vec.h.
Referenced by TNT::Vector< Subscript >::begin(), TNT::Vector< Subscript >::copy(), TNT::Vector< Subscript >::destroy(), TNT::Vector< Subscript >::end(), TNT::Vector< Subscript >::initialize(), TNT::Vector< Subscript >::operator=(), TNT::Vector< Subscript >::operator[](), TNT::Vector< Subscript >::set(), and TNT::Vector< Subscript >::Vector().
template<class T> T * TNT::Vector< T >::vm1_ [protected]
Definition at line 63 of file vec.h.
Referenced by TNT::Vector< Subscript >::destroy(), TNT::Vector< Subscript >::initialize(), and TNT::Vector< Subscript >::operator()().
The documentation for this class was generated from the following files:
vec.h
tnt_vec.h