Blender: cineon_dpx.c File Reference
cineon_dpx.c File Reference
Cineon
#include <stdio.h>
#include <string.h>
#include "logImageLib.h"
#include "cineonlib.h"
#include "dpxlib.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_filetype.h"
#include "BKE_global.h"
#include "MEM_guardedalloc.h"
Functions
static struct ImBuf * imb_load_dpx_cineon (unsigned char *mem, int use_cineon, int size, int flags)
static int imb_save_dpx_cineon (ImBuf *ibuf, const char *filename, int use_cineon, int flags)
int imb_savecineon (struct ImBuf *buf, const char *myfile, int flags)
int imb_is_cineon (unsigned char *buf)
ImBuf * imb_loadcineon (unsigned char *mem, size_t size, int flags)
int imb_save_dpx (struct ImBuf *buf, const char *myfile, int flags)
int imb_is_dpx (unsigned char *buf)
ImBuf * imb_loaddpx (unsigned char *mem, size_t size, int flags)
Detailed Description
Definition in file cineon_dpx.c.
Function Documentation
int imb_is_cineon (unsigned char * buf)
Definition at line 200 of file cineon_dpx.c.
References cineonIsMemFileCineon().
Referenced by imb_loadcineon().
int imb_is_dpx (unsigned char * buf)
Definition at line 217 of file cineon_dpx.c.
References dpxIsMemFileCineon().
Referenced by imb_loaddpx().
static struct ImBuf* imb_load_dpx_cineon (unsigned char * mem, int use_cineon, int size, int flags) [static, read]
Definition at line 66 of file cineon_dpx.c.
References ImBuf::depth, G, G_DEBUG, IB_rect, IB_rectfloat, IMB_allocImBuf(), IMB_rect_from_float(), logImageClose(), logImageGetRowBytes(), logImageGetSize(), logImageOpenFromMem(), logImageSetVerbose(), MEM_freeN(), MEM_mallocN(), NULL, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by imb_loadcineon(), and imb_loaddpx().
ImBuf* imb_loadcineon (unsigned char * mem, size_t size, int flags) [read]
Definition at line 205 of file cineon_dpx.c.
References imb_is_cineon(), imb_load_dpx_cineon(), and NULL.
ImBuf* imb_loaddpx (unsigned char * mem, size_t size, int flags) [read]
Definition at line 222 of file cineon_dpx.c.
References imb_is_dpx(), imb_load_dpx_cineon(), and NULL.
int imb_save_dpx (struct ImBuf * buf, const char * myfile, int flags)
Definition at line 212 of file cineon_dpx.c.
References imb_save_dpx_cineon().
static int imb_save_dpx_cineon (ImBuf * ibuf, const char * filename, int use_cineon, int flags) [static]
Definition at line 124 of file cineon_dpx.c.
References ImBuf::depth, LogImageByteConversionParameters::doLogarithm, G, G_DEBUG, i, IB_PROFILE_LINEAR_RGB, IB_PROFILE_NONE, IMB_float_profile_ensure(), logImageClose(), logImageCreate(), logImageGetByteConversionDefaults(), logImageSetByteConversion(), logImageSetRowBytes(), logImageSetVerbose(), MEM_freeN(), MEM_mallocN(), NULL, ImBuf::x, and ImBuf::y.
Referenced by imb_save_dpx(), and imb_savecineon().
int imb_savecineon (struct ImBuf * buf, const char * myfile, int flags)
Definition at line 194 of file cineon_dpx.c.
References imb_save_dpx_cineon().