Blender: RE_engine.h File Reference
RE_engine.h File Reference
Rendering
#include "DNA_listBase.h"
#include "RNA_types.h"
Classes
struct RenderEngineType
struct RenderEngine
Defines
#define RE_INTERNAL 1
#define RE_GAME 2
#define RE_USE_PREVIEW 4
#define RE_USE_POSTPROCESS 8
#define RE_USE_SHADING_NODES 16
#define RE_ENGINE_ANIMATION 1
#define RE_ENGINE_PREVIEW 2
#define RE_ENGINE_DO_DRAW 4
#define RE_ENGINE_DO_UPDATE 8
Typedefs
typedef struct RenderEngineType RenderEngineType
typedef struct RenderEngine RenderEngine
Functions
RenderEngine * RE_engine_create (RenderEngineType *type)
void RE_engine_free (RenderEngine *engine)
void RE_layer_load_from_file (struct RenderLayer *layer, struct ReportList *reports, const char *filename, int x, int y)
void RE_result_load_from_file (struct RenderResult *result, struct ReportList *reports, const char *filename)
struct RenderResult * RE_engine_begin_result (RenderEngine *engine, int x, int y, int w, int h)
void RE_engine_update_result (RenderEngine *engine, struct RenderResult *result)
void RE_engine_end_result (RenderEngine *engine, struct RenderResult *result)
int RE_engine_test_break (RenderEngine *engine)
void RE_engine_update_stats (RenderEngine *engine, const char *stats, const char *info)
void RE_engine_update_progress (RenderEngine *engine, float progress)
void RE_engine_report (RenderEngine *engine, int type, const char *msg)
int RE_engine_render (struct Render *re, int do_all)
int RE_engine_is_external (struct Render *re)
void RE_engines_init (void)
void RE_engines_exit (void)
RenderEngineType * RE_engines_find (const char *idname)
Variables
ListBase R_engines
Detailed Description
Definition in file RE_engine.h.
Define Documentation
#define RE_ENGINE_ANIMATION 1
Definition at line 57 of file RE_engine.h.
Referenced by RE_engine_render(), and rna_def_render_engine().
#define RE_ENGINE_DO_DRAW 4
Definition at line 59 of file RE_engine.h.
Referenced by wm_region_test_render_do_draw().
#define RE_ENGINE_DO_UPDATE 8
Definition at line 60 of file RE_engine.h.
Referenced by ED_render_scene_update().
#define RE_ENGINE_PREVIEW 2
Definition at line 58 of file RE_engine.h.
Referenced by RE_engine_render(), and rna_def_render_engine().
#define RE_GAME 2
Definition at line 51 of file RE_engine.h.
#define RE_INTERNAL 1
Definition at line 50 of file RE_engine.h.
Referenced by RE_engines_exit().
#define RE_USE_POSTPROCESS 8
Definition at line 53 of file RE_engine.h.
Referenced by RE_engine_render(), and rna_def_render_engine().
#define RE_USE_PREVIEW 4
Definition at line 52 of file RE_engine.h.
Referenced by RE_engine_render(), and rna_def_render_engine().
#define RE_USE_SHADING_NODES 16
Definition at line 54 of file RE_engine.h.
Referenced by rna_def_render_engine(), and scene_use_new_shading_nodes().
Typedef Documentation
typedef struct RenderEngine RenderEngine
typedef struct RenderEngineType RenderEngineType
Function Documentation
struct RenderResult* RE_engine_begin_result (RenderEngine * engine, int x, int y, int w, int h) [read]
Definition at line 151 of file external_engine.c.
Referenced by BlenderSession::render().
RenderEngine* RE_engine_create (RenderEngineType * type)
Definition at line 127 of file external_engine.c.
References MEM_callocN(), and RenderEngine::type.
Referenced by RE_engine_render(), and view3d_main_area_draw_engine().
void RE_engine_end_result (RenderEngine * engine, struct RenderResult * result)
Definition at line 195 of file external_engine.c.
Referenced by BlenderSession::render().
void RE_engine_free (RenderEngine * engine)
Definition at line 135 of file external_engine.c.
References BPY_DECREF(), MEM_freeN(), RenderEngine::py_instance, and RenderEngine::text.
Referenced by ED_render_engine_area_exit(), lib_link_screen_restore(), RE_engine_render(), and view3d_main_area_free().
int RE_engine_is_external (struct Render * re)
Definition at line 119 of file external_engine.c.
References RenderData::engine, Render::r, RE_engines_find(), and RenderEngineType::render.
Referenced by validate_render_settings().
int RE_engine_render (struct Render * re, int do_all)
Definition at line 274 of file external_engine.c.
References BKE_reports_contain(), BLI_rw_mutex_lock(), BLI_rw_mutex_unlock(), BLI_strncpy(), Render::camera_override, RenderEngine::camera_override, RenderStats::cfra, RenderData::cfra, Render::disprect, RenderData::engine, ListBase::first, RenderEngine::flag, RenderEngineType::flag, Render::flag, RenderEngine::fullresult, G, Render::i, Scene::id, Render::lay, Render::main, ID::name, NULL, Scene::r, Render::r, R_ANIMATION, R_NO_FRAME_UPDATE, R_PREVIEWBUTS, RenderEngine::re, RE_ENGINE_ANIMATION, RE_engine_create(), RE_engine_free(), RE_ENGINE_PREVIEW, RE_engines_find(), RE_USE_POSTPROCESS, RE_USE_PREVIEW, RenderEngineType::render, render_result_free(), render_result_free_list(), render_result_new(), Render::reports, Render::result, Render::resultmutex, RPT_ERROR, RenderData::scemode, Render::scene, scene_update_for_newframe(), RenderStats::scenename, THREAD_LOCK_WRITE, RenderStats::totface, RenderStats::tothalo, RenderStats::totlamp, RenderStats::totstrand, RenderStats::totvert, and RenderEngineType::update.
Referenced by do_render_3d(), and do_render_all_options().
void RE_engine_report (RenderEngine * engine, int type, const char * msg)
Definition at line 267 of file external_engine.c.
References BKE_report(), RenderEngine::re, and Render::reports.
int RE_engine_test_break (RenderEngine * engine)
Definition at line 218 of file external_engine.c.
Referenced by BlenderSession::test_cancel().
void RE_engine_update_progress (RenderEngine * engine, float progress)
Definition at line 257 of file external_engine.c.
Referenced by BlenderSession::update_status_progress().
void RE_engine_update_result (RenderEngine * engine, struct RenderResult * result)
Definition at line 185 of file external_engine.c.
Referenced by BlenderSession::write_render_result().
void RE_engine_update_stats (RenderEngine * engine, const char * stats, const char * info)
Definition at line 230 of file external_engine.c.
Referenced by BlenderSession::update_status_progress().
void RE_engines_exit (void)
Definition at line 90 of file external_engine.c.
References BLI_remlink(), ExtensionRNA::data, RenderEngineType::ext, ListBase::first, RenderEngineType::flag, ExtensionRNA::free, MEM_freeN(), RenderEngineType::next, next, and RE_INTERNAL.
Referenced by WM_exit_ext().
RenderEngineType* RE_engines_find (const char * idname)
Definition at line 108 of file external_engine.c.
References BLI_findstring(), and internal_render_type.
Referenced by RE_engine_is_external(), RE_engine_render(), scene_use_new_shading_nodes(), and view3d_main_area_draw_engine().
void RE_engines_init (void)
Definition at line 82 of file external_engine.c.
References BLI_addtail().
Referenced by main().
void RE_layer_load_from_file (struct RenderLayer * layer, struct ReportList * reports, const char * filename, int x, int y)
Definition at line 2358 of file pipeline.c.
References BKE_reportf(), IB_rect, IB_rectfloat, IMB_allocImBuf(), IMB_float_from_rect(), IMB_freeImBuf(), IMB_loadiffname(), IMB_rectcpy(), NULL, ImBuf::rect, ImBuf::rect_float, RenderLayer::rectf, RenderLayer::rectx, RenderLayer::recty, RPT_ERROR, ImBuf::x, and ImBuf::y.
void RE_result_load_from_file (struct RenderResult * result, struct ReportList * reports, const char * filename)
Definition at line 2399 of file pipeline.c.
References BKE_reportf(), render_result_exr_file_read_path(), and RPT_ERROR.
Variable Documentation
ListBase R_engines
Definition at line 80 of file external_engine.c.
Referenced by set_engine(), and WM_read_file().