Blender: text_python.c File Reference
text_python.c File Reference
text editor
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "DNA_text_types.h"
#include "BKE_suggestions.h"
#include "BKE_text.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "WM_types.h"
#include "text_intern.h"
Defines
#define L_MOUSE 0
#define M_MOUSE 0
#define R_MOUSE 0
#define LR_SHIFTKEY 0
#define LR_ALTKEY 0
#define LR_CTRLKEY 0
#define LR_OSKEY 0
Functions
int text_do_suggest_select (SpaceText *st, ARegion *ar)
void text_pop_suggest_list (void)
static void get_suggest_prefix (Text *text, int offset)
static void confirm_suggestion (Text *text, int skipleft)
static short UNUSED_FUNCTION() do_texttools (SpaceText *st, char ascii, unsigned short evnt, short val)
static short UNUSED_FUNCTION() do_textmarkers (SpaceText *st, char ascii, unsigned short evnt, short val)
Variables
static int doc_scroll = 0
Detailed Description
Definition in file text_python.c.
Define Documentation
#define L_MOUSE 0
Definition at line 183 of file text_python.c.
#define LR_ALTKEY 0
Definition at line 187 of file text_python.c.
Referenced by do_textmarkers(), view_editmove(), and viewnumpad_exec().
#define LR_CTRLKEY 0
Definition at line 188 of file text_python.c.
Referenced by do_textmarkers(), and view_editmove().
#define LR_OSKEY 0
Definition at line 189 of file text_python.c.
#define LR_SHIFTKEY 0
Definition at line 186 of file text_python.c.
Referenced by do_textmarkers(), and view_editmove().
#define M_MOUSE 0
Definition at line 184 of file text_python.c.
#define R_MOUSE 0
Definition at line 185 of file text_python.c.
Function Documentation
static void confirm_suggestion (Text * text, int skipleft) [static]
Definition at line 148 of file text_python.c.
References Text::curc, Text::curl, i, TextLine::line, SuggItem::name, text_check_identifier(), texttool_suggest_selected(), texttool_text_clear(), texttool_text_is_active(), txt_insert_buf(), txt_move_left(), and txt_move_right().
Referenced by do_texttools().
static short UNUSED_FUNCTION() do_textmarkers (SpaceText * st, char ascii, unsigned short evnt, short val) [static]
Definition at line 381 of file text_python.c.
References BACKSPACEKEY, BLI_freelinkN(), Text::curc, Text::curl, DELKEY, TextMarker::end, ESCKEY, ListBase::first, FKEY, TextMarker::flags, TextMarker::group, Text::id, ListBase::last, LEFTMOUSE, ID::lib, TextMarker::lineno, Text::lines, LR_ALTKEY, LR_CTRLKEY, LR_SHIFTKEY, Text::markers, TextMarker::next, NULL, TextMarker::prev, RETKEY, RIGHTMOUSE, Text::selc, Text::sell, TextMarker::start, TABKEY, text_update_line_edited(), TMARK_EDITALL, TMARK_TEMP, txt_add_char(), txt_backspace_char(), txt_clear_markers(), txt_delete_char(), txt_find_marker(), txt_get_span(), txt_move_to(), txt_next_marker(), txt_replace_char(), UKEY, and ZKEY.
static short UNUSED_FUNCTION() do_texttools (SpaceText * st, char ascii, unsigned short evnt, short val) [static]
Definition at line 194 of file text_python.c.
References BACKSPACEKEY, confirm_suggestion(), doc_scroll, DOWNARROWKEY, ESCKEY, get_suggest_prefix(), LEFTARROWKEY, LEFTMOUSE, LEFTSHIFTKEY, MIDDLEMOUSE, SuggItem::next, NULL, PAGEDOWNKEY, PAGEUPKEY, SuggItem::prev, RETKEY, RIGHTARROWKEY, RIGHTSHIFTKEY, SUGG_LIST_SIZE, text_check_whitespace(), text_do_suggest_select(), text_pop_suggest_list(), text_update_line_edited(), texttool_docs_clear(), texttool_docs_get(), texttool_suggest_clear(), texttool_suggest_first(), texttool_suggest_last(), texttool_suggest_select(), texttool_suggest_selected(), texttool_text_is_active(), TOOL_DOCUMENT, TOOL_SUGG_LIST, txt_add_char(), txt_replace_char(), UPARROWKEY, WHEELDOWNMOUSE, and WHEELUPMOUSE.
static void get_suggest_prefix (Text * text, int offset) [static]
Definition at line 125 of file text_python.c.
References BLI_strncpy(), Text::curc, Text::curl, i, len(), TextLine::line, text_check_identifier(), texttool_suggest_prefix(), and texttool_text_is_active().
Referenced by do_texttools().
int text_do_suggest_select (SpaceText * st, ARegion * ar)
Definition at line 50 of file text_python.c.
References Text::curc, Text::curl, SpaceText::cwidth, i, if(), SpaceText::left, SpaceText::lheight, SuggItem::next, TextLine::prev, SpaceText::showlinenrs, SUGG_LIST_SIZE, SUGG_LIST_WIDTH, SpaceText::text, text_update_character_width(), texttool_suggest_first(), texttool_suggest_last(), texttool_suggest_select(), texttool_suggest_top(), texttool_text_is_active(), TEXTXLOC, SpaceText::top, TXT_OFFSET, and ARegion::winy.
Referenced by do_texttools().
void text_pop_suggest_list (void)
Definition at line 105 of file text_python.c.
References i, SuggItem::next, SUGG_LIST_SIZE, texttool_suggest_first(), texttool_suggest_selected(), and texttool_suggest_top().
Referenced by do_texttools(), and draw_suggestion_list().
Variable Documentation
int doc_scroll = 0 [static]
Definition at line 192 of file text_python.c.
Referenced by do_texttools().