Blender: SCA_NANDController Class Reference
SCA_NANDController Class Reference
#include <SCA_NANDController.h>
Public Member Functions
SCA_NANDController (SCA_IObject *gameobj)
virtual ~SCA_NANDController ()
virtual CValue * GetReplica ()
virtual void Trigger (SCA_LogicManager *logicmgr)
Detailed Description
Definition at line 37 of file SCA_NANDController.h.
Constructor & Destructor Documentation
SCA_NANDController::SCA_NANDController (SCA_IObject * gameobj)
Definition at line 45 of file SCA_NANDController.cpp.
Referenced by GetReplica().
SCA_NANDController::~SCA_NANDController () [virtual]
Definition at line 53 of file SCA_NANDController.cpp.
Member Function Documentation
CValue * SCA_NANDController::GetReplica (void) [virtual]
Implements CValue.
Definition at line 85 of file SCA_NANDController.cpp.
References CValue::ProcessReplica(), and SCA_NANDController().
void SCA_NANDController::Trigger (SCA_LogicManager * logicmgr) [virtual]
Implements SCA_IController.
Definition at line 59 of file SCA_NANDController.cpp.
References SCA_LogicManager::AddActiveActuator(), SCA_ISensor::GetState(), i, SCA_IController::m_linkedactuators, and SCA_IController::m_linkedsensors.
The documentation for this class was generated from the following files:
SCA_NANDController.h
SCA_NANDController.cpp