Blender: gpencil_buttons.c File Reference
gpencil_buttons.c File Reference
gpencil
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stddef.h>
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLF_translation.h"
#include "DNA_gpencil_types.h"
#include "DNA_screen_types.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_gpencil.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "ED_gpencil.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "gpencil_intern.h"
Typedefs
typedef enum eGP_Stroke_Ops eGP_Stroke_Ops
Enumerations
enum eGP_Stroke_Ops { STROKE_OPTS_NORMAL = 0, STROKE_OPTS_V3D_OFF, STROKE_OPTS_V3D_ON }
Functions
static void gp_ui_activelayer_cb (bContext *C, void *gpd, void *gpl)
static void gp_ui_dellayer_cb (bContext *C, void *gpd, void *gpl)
static void gp_drawui_layer (uiLayout *layout, bGPdata *gpd, bGPDlayer *gpl, const short is_v3d)
static void draw_gpencil_panel (bContext *C, uiLayout *layout, bGPdata *gpd, PointerRNA *ctx_ptr)
void gpencil_panel_standard (const bContext *C, Panel *pa)
Detailed Description
Definition in file gpencil_buttons.c.
Typedef Documentation
typedef enum eGP_Stroke_Ops eGP_Stroke_Ops
Enumeration Type Documentation
enum eGP_Stroke_Ops
Enumerator:
STROKE_OPTS_NORMAL
STROKE_OPTS_V3D_OFF
STROKE_OPTS_V3D_ON
Definition at line 227 of file gpencil_buttons.c.
Function Documentation
static void draw_gpencil_panel (bContext * C, uiLayout * layout, bGPdata * gpd, PointerRNA * ctx_ptr) [static]
Definition at line 234 of file gpencil_buttons.c.
References CTX_wm_view3d(), ID::flag, GP_DATA_DEPTH_STROKE, GP_DATA_DEPTH_VIEW, gp_drawui_layer(), IFACE_, bGPDlayer::next, NULL, RNA_id_pointer_create(), STROKE_OPTS_NORMAL, STROKE_OPTS_V3D_OFF, STROKE_OPTS_V3D_ON, uiItemEnumR_string(), uiItemL(), uiItemO(), uiItemR(), uiLayoutColumn(), uiLayoutRow(), uiLayoutSetActive(), and uiTemplateID().
Referenced by gpencil_panel_standard().
static void gp_drawui_layer (uiLayout * layout, bGPdata * gpd, bGPDlayer * gpl, const short is_v3d) [static]
Definition at line 94 of file gpencil_buttons.c.
References BLI_snprintf(), BUT, bGPDlayer::flag, ID::flag, G, G_DEBUG, GP_LAYER_ACTIVE, GP_LAYER_FRAMELOCK, GP_LAYER_HIDE, GP_LAYER_LOCKED, gp_ui_activelayer_cb(), gp_ui_dellayer_cb(), IFACE_, bGPDlayer::info, NULL, RNA_GPencilLayer, RNA_pointer_create(), split(), TIP_, TOG, UI_EMBOSS, UI_EMBOSSN, UI_ITEM_R_SLIDER, UI_LAYOUT_ALIGN_EXPAND, UI_LAYOUT_ALIGN_RIGHT, UI_UNIT_X, UI_UNIT_Y, uiBlockSetEmboss(), uiBlockSetFunc(), uiButSetFunc(), uiDefIconBut(), uiDefIconButBitI(), uiItemL(), uiItemR(), uiLayoutBox(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), uiLayoutSetAlignment(), and uiLayoutSplit().
Referenced by draw_gpencil_panel().
static void gp_ui_activelayer_cb (bContext * C, void * gpd, void * gpl) [static]
Definition at line 72 of file gpencil_buttons.c.
References gpencil_layer_setactive(), NA_EDITED, NC_SCREEN, ND_GPENCIL, NULL, and WM_event_add_notifier().
Referenced by gp_drawui_layer().
static void gp_ui_dellayer_cb (bContext * C, void * gpd, void * gpl) [static]
Definition at line 81 of file gpencil_buttons.c.
References gpencil_layer_delactive(), gpencil_layer_setactive(), NA_EDITED, NC_SCREEN, ND_GPENCIL, NULL, and WM_event_add_notifier().
Referenced by gp_drawui_layer().
void gpencil_panel_standard (const bContext * C, Panel * pa)
Definition at line 296 of file gpencil_buttons.c.
References draw_gpencil_panel(), gpencil_data_get_pointers(), Panel::layout, and NULL.
Referenced by ED_clip_buttons_register(), image_buttons_register(), node_buttons_register(), and view3d_buttons_register().