Blender: TNT::Array3D< T > Class Template Reference
TNT::Array3D< T > Class Template Reference
#include <tnt_array3d.h>
Public Types
typedef T value_type
Public Member Functions
Array3D ()
Array3D (int m, int n, int g)
Array3D (int m, int n, int g, T val)
Array3D (int m, int n, int g, T *a)
operator T *** ()
operator const T *** ()
Array3D (const Array3D &A)
Array3D & operator= (const T &a)
Array3D & operator= (const Array3D &A)
Array3D & ref (const Array3D &A)
Array3D copy () const
Array3D & inject (const Array3D &A)
T ** operator[] (int i)
const T *const operator[] (int i) const
int dim1 () const
int dim2 () const
int dim3 () const
~Array3D ()
int ref_count ()
Array3D subarray (int i0, int i1, int j0, int j1, int k0, int k1)
Detailed Description
template<class T>
class TNT::Array3D< T >
Definition at line 41 of file tnt_array3d.h.
Member Typedef Documentation
template<class T> typedef T TNT::Array3D< T >::value_type
Definition at line 55 of file tnt_array3d.h.
Constructor & Destructor Documentation
template<class T > TNT::Array3D< T >::Array3D ()
Definition at line 86 of file tnt_array3d.h.
template<class T > TNT::Array3D< T >::Array3D (int m, int n, int g)
Definition at line 97 of file tnt_array3d.h.
References i, p, and T.
template<class T > TNT::Array3D< T >::Array3D (int m, int n, int g, T val)
Definition at line 118 of file tnt_array3d.h.
References i, p, and T.
template<class T > TNT::Array3D< T >::Array3D (int m, int n, int g, T * a)
Definition at line 139 of file tnt_array3d.h.
References i, p, and T.
template<class T > TNT::Array3D< T >::Array3D (const Array3D< T > & A) [inline]
Definition at line 89 of file tnt_array3d.h.
template<class T > TNT::Array3D< T >::~Array3D ()
Definition at line 247 of file tnt_array3d.h.
Member Function Documentation
template<class T > Array3D< T > TNT::Array3D< T >::copy () const
Definition at line 187 of file tnt_array3d.h.
References A, and i.
template<class T > int TNT::Array3D< T >::dim1 () const [inline]
Definition at line 236 of file tnt_array3d.h.
Referenced by TNT::operator*(), TNT::operator*=(), TNT::operator+(), TNT::operator+=(), TNT::operator-(), TNT::operator-=(), TNT::operator/(), and TNT::operator/=().
template<class T > int TNT::Array3D< T >::dim2 () const [inline]
Definition at line 239 of file tnt_array3d.h.
Referenced by TNT::operator*(), TNT::operator*=(), TNT::operator+(), TNT::operator+=(), TNT::operator-(), TNT::operator-=(), TNT::operator/(), and TNT::operator/=().
template<class T > int TNT::Array3D< T >::dim3 () const [inline]
Definition at line 242 of file tnt_array3d.h.
Referenced by TNT::operator*(), TNT::operator*=(), TNT::operator+(), TNT::operator+=(), TNT::operator-(), TNT::operator-=(), TNT::operator/(), and TNT::operator/=().
template<class T > Array3D< T > & TNT::Array3D< T >::inject (const Array3D< T > & A)
Definition at line 200 of file tnt_array3d.h.
References i.
template<class T > TNT::Array3D< T >::operator const T *** () [inline]
Definition at line 257 of file tnt_array3d.h.
template<class T > TNT::Array3D< T >::operator T *** () [inline]
Definition at line 250 of file tnt_array3d.h.
template<class T > Array3D< T > & TNT::Array3D< T >::operator= (const Array3D< T > & A) [inline]
Definition at line 229 of file tnt_array3d.h.
template<class T > Array3D< T > & TNT::Array3D< T >::operator= (const T & a) [inline]
Definition at line 176 of file tnt_array3d.h.
References i.
template<class T > T ** TNT::Array3D< T >::operator[] (int i) [inline]
Definition at line 160 of file tnt_array3d.h.
References assert, and i.
template<class T > const T *const TNT::Array3D< T >::operator[] (int i) const [inline]
Definition at line 172 of file tnt_array3d.h.
References i.
template<class T > Array3D< T > & TNT::Array3D< T >::ref (const Array3D< T > & A) [inline]
Definition at line 215 of file tnt_array3d.h.
template<class T> int TNT::Array3D< T >::ref_count () [inline]
Definition at line 80 of file tnt_array3d.h.
template<class T > Array3D< T > TNT::Array3D< T >::subarray (int i0, int i1, int j0, int j1, int k0, int k1)
Definition at line 264 of file tnt_array3d.h.
References A, i, p, and T.
The documentation for this class was generated from the following file:
tnt_array3d.h