Blender: outliner_intern.h File Reference
outliner_intern.h File Reference
outliner space
#include "RNA_types.h"
Classes
struct TreeElement
Defines
#define TE_ACTIVE 1
#define TE_ICONROW 2
#define TE_LAZY_CLOSED 4
#define TE_FREE_NAME 8
#define TSE_NLA 1
#define TSE_NLA_ACTION 2
#define TSE_DEFGROUP_BASE 3
#define TSE_DEFGROUP 4
#define TSE_BONE 5
#define TSE_EBONE 6
#define TSE_CONSTRAINT_BASE 7
#define TSE_CONSTRAINT 8
#define TSE_MODIFIER_BASE 9
#define TSE_MODIFIER 10
#define TSE_LINKED_OB 11
#define TSE_SCRIPT_BASE 12
#define TSE_POSE_BASE 13
#define TSE_POSE_CHANNEL 14
#define TSE_ANIM_DATA 15
#define TSE_DRIVER_BASE 16
#define TSE_DRIVER 17
#define TSE_PROXY 18
#define TSE_R_LAYER_BASE 19
#define TSE_R_LAYER 20
#define TSE_R_PASS 21
#define TSE_LINKED_MAT 22
#define TSE_LINKED_LAMP 23
#define TSE_POSEGRP_BASE 24
#define TSE_POSEGRP 25
#define TSE_SEQUENCE 26
#define TSE_SEQ_STRIP 27
#define TSE_SEQUENCE_DUP 28
#define TSE_LINKED_PSYS 29
#define TSE_RNA_STRUCT 30
#define TSE_RNA_PROPERTY 31
#define TSE_RNA_ARRAY_ELEM 32
#define TSE_NLA_TRACK 33
#define TSE_KEYMAP 34
#define TSE_KEYMAP_ITEM 35
#define OL_NAMEBUTTON 1
#define TREESTORE(a) ((a)?soops->treestore->data+(a)->store_index:NULL)
#define OL_Y_OFFSET 2
#define OL_TOG_RESTRICT_VIEWX (UI_UNIT_X*3)
#define OL_TOG_RESTRICT_SELECTX (UI_UNIT_X*2)
#define OL_TOG_RESTRICT_RENDERX UI_UNIT_X
#define OL_TOGW OL_TOG_RESTRICT_VIEWX
#define OL_RNA_COLX (UI_UNIT_X*15)
#define OL_RNA_COL_SIZEX (UI_UNIT_X*7.5f)
#define OL_RNA_COL_SPACEX (UI_UNIT_X*2.5f)
#define SEARCHING_OUTLINER(sov) (sov->search_flags & SO_SEARCH_RECURSIVE)
#define TSELEM_OPEN(telm, sv) ((telm->flag & TSE_CLOSED)==0 || (SEARCHING_OUTLINER(sv) && (telm->flag & TSE_CHILDSEARCH)))
Typedefs
typedef struct TreeElement TreeElement
Functions
void outliner_free_tree (ListBase *lb)
void outliner_cleanup_tree (struct SpaceOops *soops)
TreeElement * outliner_find_tse (struct SpaceOops *soops, TreeStoreElem *tse)
TreeElement * outliner_find_id (struct SpaceOops *soops, ListBase *lb, struct ID *id)
struct ID * outliner_search_back (SpaceOops *soops, TreeElement *te, short idcode)
void outliner_build_tree (struct Main *mainvar, struct Scene *scene, struct SpaceOops *soops)
void draw_outliner (const struct bContext *C)
void restrictbutton_gr_restrict_flag (void *poin, void *poin2, int flag)
int tree_element_type_active (struct bContext *C, struct Scene *scene, struct SpaceOops *soops, TreeElement *te, TreeStoreElem *tselem, int set)
int tree_element_active (struct bContext *C, struct Scene *scene, SpaceOops *soops, TreeElement *te, int set)
void outliner_do_object_operation (struct bContext *C, struct Scene *scene, struct SpaceOops *soops, struct ListBase *lb, void(*operation_cb)(struct bContext *C, struct Scene *scene, struct TreeElement *, struct TreeStoreElem *, TreeStoreElem *))
int common_restrict_check (struct bContext *C, struct Object *ob)
int outliner_has_one_flag (struct SpaceOops *soops, ListBase *lb, short flag, short curlevel)
void outliner_set_flag (struct SpaceOops *soops, ListBase *lb, short flag, short set)
void object_toggle_visibility_cb (struct bContext *C, struct Scene *scene, TreeElement *te, struct TreeStoreElem *tsep, struct TreeStoreElem *tselem)
void object_toggle_selectability_cb (struct bContext *C, struct Scene *scene, TreeElement *te, struct TreeStoreElem *tsep, struct TreeStoreElem *tselem)
void object_toggle_renderability_cb (struct bContext *C, struct Scene *scene, TreeElement *te, struct TreeStoreElem *tsep, struct TreeStoreElem *tselem)
void group_toggle_visibility_cb (struct bContext *C, struct Scene *scene, TreeElement *te, struct TreeStoreElem *tsep, struct TreeStoreElem *tselem)
void group_toggle_selectability_cb (struct bContext *C, struct Scene *scene, TreeElement *te, struct TreeStoreElem *tsep, struct TreeStoreElem *tselem)
void group_toggle_renderability_cb (struct bContext *C, struct Scene *scene, TreeElement *te, struct TreeStoreElem *tsep, struct TreeStoreElem *tselem)
void item_rename_cb (struct bContext *C, struct Scene *scene, TreeElement *te, struct TreeStoreElem *tsep, struct TreeStoreElem *tselem)
TreeElement * outliner_dropzone_parent (struct bContext *C, struct wmEvent *event, struct TreeElement *te, float *fmval)
int outliner_dropzone_parent_clear (struct bContext *C, struct wmEvent *event, struct TreeElement *te, float *fmval)
void OUTLINER_OT_item_activate (struct wmOperatorType *ot)
void OUTLINER_OT_item_openclose (struct wmOperatorType *ot)
void OUTLINER_OT_item_rename (struct wmOperatorType *ot)
void OUTLINER_OT_show_one_level (struct wmOperatorType *ot)
void OUTLINER_OT_show_active (struct wmOperatorType *ot)
void OUTLINER_OT_show_hierarchy (struct wmOperatorType *ot)
void OUTLINER_OT_select_border (struct wmOperatorType *ot)
void OUTLINER_OT_selected_toggle (struct wmOperatorType *ot)
void OUTLINER_OT_expanded_toggle (struct wmOperatorType *ot)
void OUTLINER_OT_scroll_page (struct wmOperatorType *ot)
void OUTLINER_OT_renderability_toggle (struct wmOperatorType *ot)
void OUTLINER_OT_selectability_toggle (struct wmOperatorType *ot)
void OUTLINER_OT_visibility_toggle (struct wmOperatorType *ot)
void OUTLINER_OT_keyingset_add_selected (struct wmOperatorType *ot)
void OUTLINER_OT_keyingset_remove_selected (struct wmOperatorType *ot)
void OUTLINER_OT_drivers_add_selected (struct wmOperatorType *ot)
void OUTLINER_OT_drivers_delete_selected (struct wmOperatorType *ot)
void OUTLINER_OT_parent_drop (struct wmOperatorType *ot)
void OUTLINER_OT_parent_clear (struct wmOperatorType *ot)
void OUTLINER_OT_operation (struct wmOperatorType *ot)
void OUTLINER_OT_object_operation (struct wmOperatorType *ot)
void OUTLINER_OT_group_operation (struct wmOperatorType *ot)
void OUTLINER_OT_id_operation (struct wmOperatorType *ot)
void OUTLINER_OT_data_operation (struct wmOperatorType *ot)
void OUTLINER_OT_animdata_operation (struct wmOperatorType *ot)
void OUTLINER_OT_action_set (struct wmOperatorType *ot)
void outliner_operatortypes (void)
void outliner_keymap (struct wmKeyConfig *keyconf)
Detailed Description
Definition in file outliner_intern.h.
Define Documentation
#define OL_NAMEBUTTON 1
Definition at line 108 of file outliner_intern.h.
Referenced by outliner_buttons().
#define OL_RNA_COL_SIZEX (UI_UNIT_X*7.5f)
Definition at line 125 of file outliner_intern.h.
Referenced by draw_outliner(), outliner_draw_rnabuts(), and outliner_draw_rnacols().
#define OL_RNA_COL_SPACEX (UI_UNIT_X*2.5f)
Definition at line 126 of file outliner_intern.h.
Referenced by draw_outliner().
#define OL_RNA_COLX (UI_UNIT_X*15)
Definition at line 124 of file outliner_intern.h.
Referenced by draw_outliner().
#define OL_TOG_RESTRICT_RENDERX UI_UNIT_X
Definition at line 120 of file outliner_intern.h.
Referenced by outliner_draw_restrictbuts(), and outliner_draw_restrictcols().
#define OL_TOG_RESTRICT_SELECTX (UI_UNIT_X*2)
Definition at line 119 of file outliner_intern.h.
Referenced by outliner_draw_restrictbuts(), and outliner_draw_restrictcols().
#define OL_TOG_RESTRICT_VIEWX (UI_UNIT_X*3)
Definition at line 118 of file outliner_intern.h.
Referenced by outliner_draw_restrictbuts(), outliner_draw_restrictcols(), and outliner_item_activate().
#define OL_TOGW OL_TOG_RESTRICT_VIEWX
Definition at line 122 of file outliner_intern.h.
Referenced by draw_outliner(), outliner_draw_restrictcols(), and outliner_draw_tree_element().
#define OL_Y_OFFSET 2
Definition at line 116 of file outliner_intern.h.
Referenced by draw_outliner(), outliner_back(), outliner_draw_restrictcols(), outliner_draw_tree(), and outliner_item_activate().
#define SEARCHING_OUTLINER (sov) (sov->search_flags & SO_SEARCH_RECURSIVE)
Definition at line 145 of file outliner_intern.h.
Referenced by outliner_add_element(), and outliner_draw_tree_element().
#define TE_ACTIVE 1
Definition at line 63 of file outliner_intern.h.
Referenced by outliner_draw_tree_element(), and tree_element_active_texture().
#define TE_FREE_NAME 8
Definition at line 66 of file outliner_intern.h.
Referenced by outliner_filter_tree(), and outliner_free_tree().
#define TE_ICONROW 2
Definition at line 64 of file outliner_intern.h.
Referenced by do_outliner_item_activate(), outliner_draw_iconrow(), and outliner_select().
#define TE_LAZY_CLOSED 4
Definition at line 65 of file outliner_intern.h.
Referenced by outliner_draw_tree_element(), and outliner_parent_clear_poll().
#define TREESTORE (a) ((a)?soops->treestore->data+(a)->store_index:NULL)
Definition at line 113 of file outliner_intern.h.
Referenced by do_outliner_drivers_editop(), do_outliner_item_activate(), do_outliner_item_openclose(), do_outliner_item_rename(), do_outliner_keyingset_editop(), do_outliner_operation_event(), outliner_add_element(), outliner_add_id_contents(), outliner_add_object_contents(), outliner_add_passes(), outliner_build_tree(), outliner_buttons(), outliner_do_data_operation(), outliner_do_id_set_operation(), outliner_do_libdata_operation(), outliner_do_object_operation(), outliner_draw_hierarchy(), outliner_draw_iconrow(), outliner_draw_keymapbuts(), outliner_draw_restrictbuts(), outliner_draw_rnabuts(), outliner_draw_selection(), outliner_draw_struct_marks(), outliner_draw_tree_element(), outliner_dropzone_parent(), outliner_dropzone_parent_clear(), outliner_filter_tree(), outliner_find_id(), outliner_has_one_flag(), outliner_height(), outliner_item_border_select(), outliner_make_hierarchy(), outliner_openclose_level(), outliner_rna_width(), outliner_search_back(), outliner_select(), outliner_set_flag(), outliner_sort(), set_operation_types(), subtree_has_objects(), tree_element_active_texture(), tree_element_active_world(), tree_element_set_active_object(), tree_element_show_hierarchy(), and tree_element_to_path().
#define TSE_ANIM_DATA 15
Definition at line 83 of file outliner_intern.h.
Referenced by actionset_id_cb(), do_item_rename(), do_outliner_operation_event(), outliner_action_set_exec(), outliner_add_element(), outliner_add_id_contents(), outliner_add_object_contents(), outliner_add_scene_contents(), outliner_animdata_operation_exec(), and tselem_draw_icon().
#define TSE_BONE 5
Definition at line 73 of file outliner_intern.h.
Referenced by namebutton_cb(), outliner_add_bone(), outliner_data_operation_exec(), tree_element_type_active(), and tselem_draw_icon().
#define TSE_CONSTRAINT 8
Definition at line 76 of file outliner_intern.h.
Referenced by outliner_add_object_contents(), and tree_element_type_active().
#define TSE_CONSTRAINT_BASE 7
Definition at line 75 of file outliner_intern.h.
Referenced by do_item_rename(), outliner_add_object_contents(), and tselem_draw_icon().
#define TSE_DEFGROUP 4
Definition at line 72 of file outliner_intern.h.
Referenced by namebutton_cb(), outliner_add_object_contents(), outliner_sort(), and tree_element_type_active().
#define TSE_DEFGROUP_BASE 3
Definition at line 71 of file outliner_intern.h.
Referenced by do_item_rename(), outliner_add_object_contents(), and tselem_draw_icon().
#define TSE_DRIVER 17
Definition at line 85 of file outliner_intern.h.
#define TSE_DRIVER_BASE 16
Definition at line 84 of file outliner_intern.h.
Referenced by do_outliner_operation_event(), outliner_add_element(), and tselem_draw_icon().
#define TSE_EBONE 6
Definition at line 74 of file outliner_intern.h.
Referenced by namebutton_cb(), outliner_add_id_contents(), outliner_buttons(), outliner_data_operation_exec(), outliner_draw_restrictbuts(), tree_element_type_active(), and tselem_draw_icon().
#define TSE_KEYMAP 34
Definition at line 104 of file outliner_intern.h.
Referenced by outliner_build_tree().
#define TSE_KEYMAP_ITEM 35
Definition at line 105 of file outliner_intern.h.
Referenced by outliner_draw_keymapbuts(), and tree_element_type_active().
#define TSE_LINKED_LAMP 23
Definition at line 93 of file outliner_intern.h.
Referenced by outliner_add_scene_contents(), and tselem_draw_icon().
#define TSE_LINKED_MAT 22
Definition at line 91 of file outliner_intern.h.
Referenced by outliner_add_scene_contents(), and tselem_draw_icon().
#define TSE_LINKED_OB 11
Definition at line 79 of file outliner_intern.h.
Referenced by outliner_add_element(), outliner_add_object_contents(), tree_element_type_active(), and tselem_draw_icon().
#define TSE_LINKED_PSYS 29
Definition at line 99 of file outliner_intern.h.
Referenced by outliner_add_object_contents(), tree_element_type_active(), and tselem_draw_icon().
#define TSE_MODIFIER 10
Definition at line 78 of file outliner_intern.h.
Referenced by outliner_add_object_contents(), outliner_buttons(), outliner_draw_restrictbuts(), tree_element_type_active(), and tselem_draw_icon().
#define TSE_MODIFIER_BASE 9
Definition at line 77 of file outliner_intern.h.
Referenced by do_item_rename(), outliner_add_object_contents(), and tselem_draw_icon().
#define TSE_NLA 1
Definition at line 69 of file outliner_intern.h.
Referenced by do_item_rename(), outliner_add_element(), and tselem_draw_icon().
#define TSE_NLA_ACTION 2
Definition at line 70 of file outliner_intern.h.
Referenced by namebutton_cb(), outliner_add_element(), and tselem_draw_icon().
#define TSE_NLA_TRACK 33
Definition at line 103 of file outliner_intern.h.
Referenced by outliner_add_element(), and tselem_draw_icon().
#define TSE_POSE_BASE 13
Definition at line 81 of file outliner_intern.h.
Referenced by do_item_rename(), outliner_add_object_contents(), outliner_buttons(), tree_element_type_active(), and tselem_draw_icon().
#define TSE_POSE_CHANNEL 14
Definition at line 82 of file outliner_intern.h.
Referenced by namebutton_cb(), outliner_add_object_contents(), outliner_data_operation_exec(), outliner_draw_restrictbuts(), tree_element_type_active(), and tselem_draw_icon().
#define TSE_POSEGRP 25
Definition at line 95 of file outliner_intern.h.
Referenced by namebutton_cb(), outliner_add_object_contents(), and tree_element_type_active().
#define TSE_POSEGRP_BASE 24
Definition at line 94 of file outliner_intern.h.
Referenced by do_item_rename(), outliner_add_object_contents(), and tselem_draw_icon().
#define TSE_PROXY 18
Definition at line 87 of file outliner_intern.h.
Referenced by outliner_add_object_contents(), and tselem_draw_icon().
#define TSE_R_LAYER 20
Definition at line 89 of file outliner_intern.h.
Referenced by do_outliner_operation_event(), namebutton_cb(), outliner_add_scene_contents(), outliner_draw_iconrow(), outliner_draw_restrictbuts(), outliner_draw_tree_element(), outliner_dropzone_parent_clear(), tree_element_type_active(), and tselem_draw_icon().
#define TSE_R_LAYER_BASE 19
Definition at line 88 of file outliner_intern.h.
Referenced by do_item_rename(), do_outliner_operation_event(), outliner_add_scene_contents(), outliner_dropzone_parent_clear(), and tselem_draw_icon().
#define TSE_R_PASS 21
Definition at line 90 of file outliner_intern.h.
Referenced by do_item_rename(), do_outliner_operation_event(), outliner_add_passes(), outliner_draw_restrictbuts(), and outliner_dropzone_parent_clear().
#define TSE_RNA_ARRAY_ELEM 32
Definition at line 102 of file outliner_intern.h.
Referenced by do_item_rename(), do_outliner_drivers_editop(), do_outliner_keyingset_editop(), outliner_add_element(), outliner_draw_rnabuts(), outliner_draw_tree_element(), and tree_element_to_path().
#define TSE_RNA_PROPERTY 31
Definition at line 101 of file outliner_intern.h.
Referenced by do_item_rename(), do_outliner_drivers_editop(), do_outliner_keyingset_editop(), outliner_add_element(), outliner_draw_rnabuts(), outliner_draw_tree_element(), and tree_element_to_path().
#define TSE_RNA_STRUCT 30
Definition at line 100 of file outliner_intern.h.
Referenced by do_item_rename(), outliner_add_element(), outliner_build_tree(), outliner_draw_struct_marks(), tree_element_to_path(), and tselem_draw_icon().
#define TSE_SCRIPT_BASE 12
Definition at line 80 of file outliner_intern.h.
Referenced by do_item_rename(), and tselem_draw_icon().
#define TSE_SEQ_STRIP 27
Definition at line 97 of file outliner_intern.h.
Referenced by do_item_rename(), do_outliner_item_activate(), outliner_add_element(), and tselem_draw_icon().
#define TSE_SEQUENCE 26
Definition at line 96 of file outliner_intern.h.
Referenced by do_item_rename(), do_outliner_item_activate(), outliner_add_element(), outliner_add_seq_dup(), outliner_build_tree(), outliner_data_operation_exec(), tree_element_type_active(), and tselem_draw_icon().
#define TSE_SEQUENCE_DUP 28
Definition at line 98 of file outliner_intern.h.
Referenced by do_item_rename(), do_outliner_item_activate(), outliner_add_element(), outliner_build_tree(), tree_element_type_active(), and tselem_draw_icon().
#define TSELEM_OPEN (telm, sv) ((telm->flag & TSE_CLOSED)==0 || (SEARCHING_OUTLINER(sv) && (telm->flag & TSE_CHILDSEARCH)))
Definition at line 148 of file outliner_intern.h.
Referenced by do_outliner_drivers_editop(), do_outliner_keyingset_editop(), outliner_buttons(), outliner_do_data_operation(), outliner_do_id_set_operation(), outliner_do_libdata_operation(), outliner_do_object_operation(), outliner_draw_hierarchy(), outliner_draw_keymapbuts(), outliner_draw_restrictbuts(), outliner_draw_rnabuts(), outliner_draw_selection(), outliner_draw_struct_marks(), outliner_draw_tree_element(), outliner_filter_tree(), outliner_height(), outliner_rna_width(), outliner_select(), set_operation_types(), and tree_element_show_hierarchy().
Typedef Documentation
typedef struct TreeElement TreeElement
Function Documentation
int common_restrict_check (struct bContext * C, struct Object * ob)
Definition at line 319 of file outliner_edit.c.
References CTX_data_edit_object(), OB_RESTRICT_SELECT, OB_RESTRICT_VIEW, and Object::restrictflag.
Referenced by object_toggle_visibility_cb(), restrictbutton_sel_cb(), and restrictbutton_view_cb().
void draw_outliner (const struct bContext * C)
void group_toggle_renderability_cb (struct bContext * C, struct Scene * scene, TreeElement * te, struct TreeStoreElem * tsep, struct TreeStoreElem * tselem)
void group_toggle_selectability_cb (struct bContext * C, struct Scene * scene, TreeElement * te, struct TreeStoreElem * tsep, struct TreeStoreElem * tselem)
void group_toggle_visibility_cb (struct bContext * C, struct Scene * scene, TreeElement * te, struct TreeStoreElem * tsep, struct TreeStoreElem * tselem)
void item_rename_cb (struct bContext * C, struct Scene * scene, TreeElement * te, struct TreeStoreElem * tsep, struct TreeStoreElem * tselem)
void object_toggle_renderability_cb (struct bContext * C, struct Scene * scene, TreeElement * te, struct TreeStoreElem * tsep, struct TreeStoreElem * tselem)
void object_toggle_selectability_cb (struct bContext * C, struct Scene * scene, TreeElement * te, struct TreeStoreElem * tsep, struct TreeStoreElem * tselem)
void object_toggle_visibility_cb (struct bContext * C, struct Scene * scene, TreeElement * te, struct TreeStoreElem * tsep, struct TreeStoreElem * tselem)
void outliner_build_tree (struct Main * mainvar, struct Scene * scene, struct SpaceOops * soops)
Definition at line 1382 of file outliner_tree.c.
References BASACT, Scene::base, BLI_addtail(), BLI_remlink(), wmWindowManager::defaultconf, FALSE, ListBase::first, Base::flag, TreeStoreElem::flag, Group::gobject, Main::group, Group::id, Scene::id, Library::id, Object::id, TreeStoreElem::id, if(), wmKeyConfig::keymaps, Base::lay, Scene::lay, Main::library, need_add_seq_dup(), ID::newid, GroupObject::next, wmKeyMap::next, Base::next, Sequence::next, TreeElement::next, ID::next, NULL, GroupObject::ob, OBACT, Main::object, Base::object, outliner_add_element(), outliner_add_scene_contents(), outliner_add_seq_dup(), outliner_filter_tree(), outliner_free_tree(), outliner_make_hierarchy(), outliner_sort(), outliner_storage_cleanup(), SpaceOops::outlinevis, Library::parent, RNA_main_pointer_create(), RNA_pointer_create(), RNA_UserPreferences, Main::scene, SpaceOops::search_flags, SpaceOops::search_string, SELECT, seq_give_editing(), Editing::seqbasep, SO_ALL_SCENES, SO_CUR_SCENE, SO_DATABLOCKS, SO_GROUPS, SO_KEYMAP, SO_LIBRARIES, SO_SAME_TYPE, SO_SEARCH_RECURSIVE, SO_SELECTED, SO_SEQUENCE, SO_TREESTORE_REDRAW, SO_USERDEF, SO_VISIBLE, SpaceOops::storeflag, TreeElement::subtree, SpaceOops::tree, SpaceOops::treestore, TREESTORE, TSE_CLOSED, TSE_KEYMAP, TSE_RNA_STRUCT, TSE_SEQUENCE, TSE_SEQUENCE_DUP, Object::type, and Main::wm.
Referenced by draw_outliner().
void outliner_cleanup_tree (struct SpaceOops * soops)
Definition at line 201 of file outliner_tree.c.
References outliner_free_tree(), outliner_storage_cleanup(), and SpaceOops::tree.
Referenced by outliner_object_operation_exec().
void outliner_do_object_operation (struct bContext * C, struct Scene * scene, struct SpaceOops * soops, struct ListBase * lb, void(*)(struct bContext *C, struct Scene *scene, struct TreeElement *, struct TreeStoreElem *, TreeStoreElem *) operation_cb)
Referenced by outliner_do_object_operation(), outliner_object_operation_exec(), outliner_toggle_renderability_exec(), outliner_toggle_selectability_exec(), and outliner_toggle_visibility_exec().
TreeElement* outliner_dropzone_parent (struct bContext * C, struct wmEvent * event, struct TreeElement * te, float * fmval)
Definition at line 1420 of file outliner_edit.c.
References CTX_wm_space_outliner(), ListBase::first, TreeStoreElem::flag, ID_OB, TreeElement::idcode, TreeElement::next, NULL, outliner_dropzone_parent(), TreeElement::subtree, TREESTORE, TSE_CLOSED, UI_UNIT_X, UI_UNIT_Y, TreeElement::xend, TreeElement::xs, and TreeElement::ys.
Referenced by outliner_dropzone_parent(), outliner_parent_drop_poll(), and parent_drop_invoke().
int outliner_dropzone_parent_clear (struct bContext * C, struct wmEvent * event, struct TreeElement * te, float * fmval)
Definition at line 1617 of file outliner_edit.c.
References CTX_wm_space_outliner(), ELEM3, ListBase::first, TreeStoreElem::flag, ID_OB, ID_SCE, TreeElement::idcode, TreeElement::next, outliner_dropzone_parent_clear(), TreeElement::subtree, TREESTORE, TSE_CLOSED, TSE_R_LAYER, TSE_R_LAYER_BASE, TSE_R_PASS, TreeStoreElem::type, UI_UNIT_X, UI_UNIT_Y, TreeElement::xend, TreeElement::xs, and TreeElement::ys.
Referenced by outliner_dropzone_parent_clear(), and outliner_parent_clear_poll().
TreeElement* outliner_find_id (struct SpaceOops * soops, ListBase * lb, struct ID * id)
Definition at line 245 of file outliner_tree.c.
References ListBase::first, TreeStoreElem::id, ID_GR, ID_OB, ID_SCE, TreeElement::idcode, TreeElement::next, NULL, outliner_find_id(), SpaceOops::outlinevis, SO_GROUPS, TreeElement::subtree, TREESTORE, and TreeStoreElem::type.
Referenced by outliner_find_id(), and outliner_show_active_exec().
TreeElement* outliner_find_tse (struct SpaceOops * soops, TreeStoreElem * tse)
Definition at line 221 of file outliner_tree.c.
References TreeStore::data, TreeStoreElem::id, TreeStoreElem::nr, NULL, outliner_find_tree_element(), SpaceOops::tree, SpaceOops::treestore, TreeStoreElem::type, and TreeStore::usedelem.
Referenced by namebutton_cb().
void outliner_free_tree (ListBase * lb)
Definition at line 188 of file outliner_tree.c.
References BLI_remlink(), ListBase::first, TreeElement::flag, MEM_freeN(), TreeElement::name, outliner_free_tree(), TreeElement::subtree, and TE_FREE_NAME.
Referenced by outliner_build_tree(), outliner_cleanup_tree(), outliner_filter_tree(), outliner_free(), and outliner_free_tree().
int outliner_has_one_flag (struct SpaceOops * soops, ListBase * lb, short flag, short curlevel)
Definition at line 285 of file outliner_edit.c.
References ListBase::first, TreeStoreElem::flag, TreeElement::next, outliner_has_one_flag(), TreeElement::subtree, and TREESTORE.
Referenced by do_outliner_item_activate(), do_outliner_item_openclose(), do_outliner_operation_event(), outliner_has_one_flag(), outliner_one_level_exec(), outliner_toggle_expanded_exec(), and outliner_toggle_selected_exec().
void outliner_keymap (struct wmKeyConfig * keyconf)
Definition at line 81 of file outliner_ops.c.
References AKEY, BKEY, DKEY, FALSE, HOMEKEY, IKEY, KKEY, KM_ALT, KM_CLICK, KM_CTRL, KM_DBL_CLICK, KM_PRESS, KM_SHIFT, LEFTMOUSE, PADMINUS, PADPERIOD, PADPLUSKEY, PAGEDOWNKEY, PAGEUPKEY, PERIODKEY, wmKeyMapItem::ptr, RETKEY, RIGHTMOUSE, RKEY, RNA_boolean_set(), SKEY, SPACE_OUTLINER, TRUE, VKEY, WM_keymap_add_item(), WM_keymap_find(), and WM_keymap_verify_item().
Referenced by ED_spacetype_outliner().
void outliner_operatortypes (void)
Definition at line 45 of file outliner_ops.c.
References OUTLINER_OT_action_set(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_drivers_add_selected(), OUTLINER_OT_drivers_delete_selected(), OUTLINER_OT_expanded_toggle(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_item_activate(), OUTLINER_OT_item_openclose(), OUTLINER_OT_item_rename(), OUTLINER_OT_keyingset_add_selected(), OUTLINER_OT_keyingset_remove_selected(), OUTLINER_OT_object_operation(), OUTLINER_OT_operation(), OUTLINER_OT_parent_clear(), OUTLINER_OT_parent_drop(), OUTLINER_OT_renderability_toggle(), OUTLINER_OT_scroll_page(), OUTLINER_OT_select_border(), OUTLINER_OT_selectability_toggle(), OUTLINER_OT_selected_toggle(), OUTLINER_OT_show_active(), OUTLINER_OT_show_hierarchy(), OUTLINER_OT_show_one_level(), OUTLINER_OT_visibility_toggle(), and WM_operatortype_append().
Referenced by ED_spacetype_outliner().
void OUTLINER_OT_action_set (struct wmOperatorType * ot)
Definition at line 941 of file outliner_tools.c.
References wmOperatorType::description, DummyRNA_NULL_items, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_action_set_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_action_itemf(), RNA_def_enum(), RNA_def_enum_funcs(), wmOperatorType::srna, and WM_enum_search_invoke().
Referenced by outliner_operatortypes().
void OUTLINER_OT_animdata_operation (struct wmOperatorType * ot)
Definition at line 1058 of file outliner_tools.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_animdata_operation_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by outliner_operatortypes().
void OUTLINER_OT_data_operation (struct wmOperatorType * ot)
Definition at line 1129 of file outliner_tools.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_data_operation_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by outliner_operatortypes().
void OUTLINER_OT_drivers_add_selected (struct wmOperatorType * ot)
Definition at line 1167 of file outliner_edit.c.
References wmOperatorType::description, ed_operator_outliner_datablocks_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_drivers_addsel_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_drivers_delete_selected (struct wmOperatorType * ot)
Definition at line 1202 of file outliner_edit.c.
References wmOperatorType::description, ed_operator_outliner_datablocks_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_drivers_deletesel_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_expanded_toggle (struct wmOperatorType * ot)
Definition at line 502 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, outliner_toggle_expanded_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_group_operation (struct wmOperatorType * ot)
Definition at line 670 of file outliner_tools.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_group_operation_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by outliner_operatortypes().
void OUTLINER_OT_id_operation (struct wmOperatorType * ot)
Definition at line 840 of file outliner_tools.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_id_operation_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by outliner_operatortypes().
void OUTLINER_OT_item_activate (struct wmOperatorType * ot)
Definition at line 832 of file outliner_select.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_item_activate(), wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by outliner_operatortypes().
void OUTLINER_OT_item_openclose (struct wmOperatorType * ot)
Definition at line 167 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_item_openclose(), wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by outliner_operatortypes().
void OUTLINER_OT_item_rename (struct wmOperatorType * ot)
Definition at line 253 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_item_rename(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_keyingset_add_selected (struct wmOperatorType * ot)
Definition at line 1341 of file outliner_edit.c.
References wmOperatorType::description, ed_operator_outliner_datablocks_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_keyingset_additems_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_keyingset_remove_selected (struct wmOperatorType * ot)
Definition at line 1378 of file outliner_edit.c.
References wmOperatorType::description, ed_operator_outliner_datablocks_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_keyingset_removeitems_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_object_operation (struct wmOperatorType * ot)
Definition at line 590 of file outliner_tools.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_object_operation_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by outliner_operatortypes().
void OUTLINER_OT_operation (struct wmOperatorType * ot)
Definition at line 1231 of file outliner_tools.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, outliner_operation(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_parent_clear (struct wmOperatorType * ot)
Definition at line 1673 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, parent_clear_invoke(), wmOperatorType::poll, prop_clear_parent_types, RNA_def_enum(), RNA_def_string(), and wmOperatorType::srna.
Referenced by outliner_operatortypes().
void OUTLINER_OT_parent_drop (struct wmOperatorType * ot)
Definition at line 1595 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, parent_drop_exec(), parent_drop_invoke(), wmOperatorType::poll, prop_make_parent_types, RNA_def_enum(), RNA_def_string(), and wmOperatorType::srna.
Referenced by outliner_operatortypes().
void OUTLINER_OT_renderability_toggle (struct wmOperatorType * ot)
Definition at line 468 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_toggle_renderability_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_scroll_page (struct wmOperatorType * ot)
Definition at line 625 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, outliner_scroll_page_exec(), wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by outliner_operatortypes().
void OUTLINER_OT_select_border (struct wmOperatorType * ot)
Definition at line 898 of file outliner_select.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_border_select_exec(), wmOperatorType::poll, WM_border_select_cancel(), WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by outliner_operatortypes().
void OUTLINER_OT_selectability_toggle (struct wmOperatorType * ot)
Definition at line 424 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active_no_editobject(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_toggle_selectability_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_selected_toggle (struct wmOperatorType * ot)
Definition at line 537 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, outliner_toggle_selected_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_show_active (struct wmOperatorType * ot)
Definition at line 592 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, outliner_show_active_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_show_hierarchy (struct wmOperatorType * ot)
Definition at line 897 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, outliner_show_hierarchy_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
void OUTLINER_OT_show_one_level (struct wmOperatorType * ot)
Definition at line 823 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, outliner_one_level_exec(), wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by outliner_operatortypes().
void OUTLINER_OT_visibility_toggle (struct wmOperatorType * ot)
Definition at line 378 of file outliner_edit.c.
References wmOperatorType::description, ED_operator_outliner_active_no_editobject(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, outliner_toggle_visibility_exec(), and wmOperatorType::poll.
Referenced by outliner_operatortypes().
struct ID* outliner_search_back (SpaceOops * soops, TreeElement * te, short idcode) [read]
Definition at line 265 of file outliner_tree.c.
References TreeStoreElem::id, TreeElement::idcode, NULL, TreeElement::parent, TREESTORE, and TreeStoreElem::type.
Referenced by outliner_do_object_operation(), tree_element_active_camera(), tree_element_active_lamp(), tree_element_active_material(), and tree_element_set_active_object().
void outliner_set_flag (struct SpaceOops * soops, ListBase * lb, short flag, short set)
Definition at line 301 of file outliner_edit.c.
References ListBase::first, TreeStoreElem::flag, TreeElement::next, outliner_set_flag(), TreeElement::subtree, and TREESTORE.
Referenced by do_outliner_item_activate(), do_outliner_item_openclose(), do_outliner_operation_event(), outliner_set_flag(), outliner_toggle_expanded_exec(), and outliner_toggle_selected_exec().
void restrictbutton_gr_restrict_flag (void * poin, void * poin2, int flag)
Definition at line 221 of file outliner_draw.c.
References BA_DESELECT, BA_SELECT, ED_base_object_select(), ListBase::first, Object::flag, Group::gobject, group_restrict_flag(), GroupObject::next, GroupObject::ob, OB_RESTRICT_VIEW, Scene::obedit, object_in_scene(), Object::restrictflag, and SELECT.
Referenced by group_toggle_renderability_cb(), group_toggle_selectability_cb(), group_toggle_visibility_cb(), restrictbutton_gr_restrict_render(), restrictbutton_gr_restrict_select(), and restrictbutton_gr_restrict_view().
int tree_element_active (struct bContext * C, struct Scene * scene, SpaceOops * soops, TreeElement * te, int set)
Definition at line 629 of file outliner_select.c.
References ID_CA, ID_LA, ID_MA, ID_TE, ID_TXT, ID_WO, TreeElement::idcode, tree_element_active_camera(), tree_element_active_lamp(), tree_element_active_material(), tree_element_active_text(), tree_element_active_texture(), and tree_element_active_world().
Referenced by do_outliner_item_activate(), namebutton_cb(), outliner_draw_iconrow(), and outliner_draw_tree_element().
int tree_element_type_active (struct bContext * C, struct Scene * scene, struct SpaceOops * soops, TreeElement * te, TreeStoreElem * tselem, int set)
Definition at line 653 of file outliner_select.c.
References TreeStoreElem::id, OBACT, tree_element_active_bone(), tree_element_active_constraint(), tree_element_active_defgroup(), tree_element_active_ebone(), tree_element_active_keymap_item(), tree_element_active_modifier(), tree_element_active_pose(), tree_element_active_posechannel(), tree_element_active_posegroup(), tree_element_active_psys(), tree_element_active_renderlayer(), tree_element_active_sequence(), tree_element_active_sequence_dup(), tree_element_set_active_object(), TSE_BONE, TSE_CONSTRAINT, TSE_DEFGROUP, TSE_EBONE, TSE_KEYMAP_ITEM, TSE_LINKED_OB, TSE_LINKED_PSYS, TSE_MODIFIER, TSE_POSE_BASE, TSE_POSE_CHANNEL, TSE_POSEGRP, TSE_R_LAYER, TSE_SEQUENCE, TSE_SEQUENCE_DUP, and TreeStoreElem::type.
Referenced by do_outliner_item_activate(), outliner_draw_iconrow(), and outliner_draw_tree_element().