Blender: svm_tex_coord.h File Reference
svm_tex_coord.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device float3 svm_background_offset (KernelGlobals *kg)
__device void svm_node_tex_coord (KernelGlobals *kg, ShaderData *sd, float *stack, uint type, uint out_offset)
__device void svm_node_tex_coord_bump_dx (KernelGlobals *kg, ShaderData *sd, float *stack, uint type, uint out_offset)
__device void svm_node_tex_coord_bump_dy (KernelGlobals *kg, ShaderData *sd, float *stack, uint type, uint out_offset)
Function Documentation
CCL_NAMESPACE_BEGIN __device float3 svm_background_offset (KernelGlobals * kg)
Definition at line 23 of file svm_tex_coord.h.
References kernel_data, make_float3(), float4::w, Transform::x, Transform::y, and Transform::z.
Referenced by svm_node_tex_coord(), svm_node_tex_coord_bump_dx(), and svm_node_tex_coord_bump_dy().
__device void svm_node_tex_coord (KernelGlobals * kg, ShaderData * sd, float * stack, uint type, uint out_offset)
Definition at line 29 of file svm_tex_coord.h.
References data, dot(), ShaderData::I, kernel_data, ShaderData::N, NODE_TEXCO_CAMERA, NODE_TEXCO_OBJECT, NODE_TEXCO_REFLECTION, NODE_TEXCO_WINDOW, ShaderData::object, object_fetch_transform(), OBJECT_INVERSE_TRANSFORM, ShaderData::P, stack_store_float3(), svm_background_offset(), transform_perspective(), and transform_point().
Referenced by svm_eval_nodes(), svm_node_tex_coord_bump_dx(), and svm_node_tex_coord_bump_dy().
__device void svm_node_tex_coord_bump_dx (KernelGlobals * kg, ShaderData * sd, float * stack, uint type, uint out_offset)
Definition at line 73 of file svm_tex_coord.h.
References data, dot(), ShaderData::dP, differential3::dx, ShaderData::I, kernel_data, ShaderData::N, NODE_TEXCO_CAMERA, NODE_TEXCO_OBJECT, NODE_TEXCO_REFLECTION, NODE_TEXCO_WINDOW, ShaderData::object, object_fetch_transform(), OBJECT_INVERSE_TRANSFORM, ShaderData::P, stack_store_float3(), svm_background_offset(), svm_node_tex_coord(), transform_perspective(), and transform_point().
Referenced by svm_eval_nodes().
__device void svm_node_tex_coord_bump_dy (KernelGlobals * kg, ShaderData * sd, float * stack, uint type, uint out_offset)
Definition at line 121 of file svm_tex_coord.h.
References data, dot(), ShaderData::dP, differential3::dy, ShaderData::I, kernel_data, ShaderData::N, NODE_TEXCO_CAMERA, NODE_TEXCO_OBJECT, NODE_TEXCO_REFLECTION, NODE_TEXCO_WINDOW, ShaderData::object, object_fetch_transform(), OBJECT_INVERSE_TRANSFORM, ShaderData::P, stack_store_float3(), svm_background_offset(), svm_node_tex_coord(), transform_perspective(), and transform_point().
Referenced by svm_eval_nodes().