Blender: MeshImporter Class Reference
MeshImporter Class Reference
#include <MeshImporter.h>
Classes
struct Primitive
Public Member Functions
MeshImporter (UnitConverter *unitconv, ArmatureImporter *arm, Scene *sce)
virtual Object * get_object_by_geom_uid (const COLLADAFW::UniqueId &geom_uid)
MTex * assign_textures_to_uvlayer (COLLADAFW::TextureCoordinateBinding &ctexture, Mesh *me, TexIndexTextureArrayMap &texindex_texarray_map, MTex *color_texture)
MTFace * assign_material_to_geom (COLLADAFW::MaterialBinding cmaterial, std::map< COLLADAFW::UniqueId, Material * > &uid_material_map, Object *ob, const COLLADAFW::UniqueId *geom_uid, MTex **color_texture, char *layername, MTFace *texture_face, std::map< Material *, TexIndexTextureArrayMap > &material_texture_mapping_map, short mat_index)
Object * create_mesh_object (COLLADAFW::Node *node, COLLADAFW::InstanceGeometry *geom, bool isController, std::map< COLLADAFW::UniqueId, Material * > &uid_material_map, std::map< Material *, TexIndexTextureArrayMap > &material_texture_mapping_map)
bool write_geometry (const COLLADAFW::Geometry *geom)
Detailed Description
Definition at line 73 of file MeshImporter.h.
Constructor & Destructor Documentation
MeshImporter::MeshImporter (UnitConverter * unitconv, ArmatureImporter * arm, Scene * sce)
Definition at line 728 of file MeshImporter.cpp.
Member Function Documentation
MTFace * MeshImporter::assign_material_to_geom (COLLADAFW::MaterialBinding cmaterial, std::map< COLLADAFW::UniqueId, Material * > & uid_material_map, Object * ob, const COLLADAFW::UniqueId * geom_uid, MTex ** color_texture, char * layername, MTFace * texture_face, std::map< Material *, TexIndexTextureArrayMap > & material_texture_mapping_map, short mat_index)
Definition at line 779 of file MeshImporter.cpp.
References assign_material(), assign_textures_to_uvlayer(), CD_MTFACE, CustomData_get_layer_named(), Object::data, Mesh::fdata, i, MTFace::mode, NULL, strlen(), TF_TEX, Object::totcol, and MTFace::tpage.
Referenced by create_mesh_object().
MTex * MeshImporter::assign_textures_to_uvlayer (COLLADAFW::TextureCoordinateBinding & ctexture, Mesh * me, TexIndexTextureArrayMap & texindex_texarray_map, MTex * color_texture)
Definition at line 737 of file MeshImporter.cpp.
References BLI_strncpy(), CD_MTFACE, CustomData_get_layer_index(), data, Mesh::fdata, CustomData::layers, MAP_COL, MTex::mapto, CustomDataLayer::name, NULL, and MTex::uvname.
Referenced by assign_material_to_geom().
Object * MeshImporter::create_mesh_object (COLLADAFW::Node * node, COLLADAFW::InstanceGeometry * geom, bool isController, std::map< COLLADAFW::UniqueId, Material * > & uid_material_map, std::map< Material *, TexIndexTextureArrayMap > & material_texture_mapping_map)
Definition at line 860 of file MeshImporter.cpp.
References add_object(), assign_material_to_geom(), Object::data, free_libblock(), G, ArmatureImporter::get_geometry_uid(), Object::id, length(), NULL, OB_MESH, rename_id(), set_mesh(), and Object::size.
Referenced by DocumentImporter::write_node().
Object * MeshImporter::get_object_by_geom_uid (const COLLADAFW::UniqueId & geom_uid) [virtual]
Implements MeshImporterBase.
Definition at line 730 of file MeshImporter.cpp.
References NULL.
bool MeshImporter::write_geometry (const COLLADAFW::Geometry * geom)
Definition at line 930 of file MeshImporter.cpp.
References add_mesh(), bc_geomTypeToStr(), bc_get_dae_name(), BKE_mesh_convert_mfaces_to_mpolys(), make_edges(), mesh_calc_normals_mapping(), Mesh::mloop, Mesh::mpoly, Mesh::mvert, NULL, Mesh::totloop, Mesh::totpoly, and Mesh::totvert.
Referenced by DocumentImporter::writeGeometry().
The documentation for this class was generated from the following files:
MeshImporter.h
MeshImporter.cpp