Blender: anim_filter.c File Reference
anim_filter.c File Reference
animation
#include <string.h>
#include "DNA_anim_types.h"
#include "DNA_armature_types.h"
#include "DNA_camera_types.h"
#include "DNA_lamp_types.h"
#include "DNA_lattice_types.h"
#include "DNA_key_types.h"
#include "DNA_material_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meta_types.h"
#include "DNA_node_types.h"
#include "DNA_particle_types.h"
#include "DNA_space_types.h"
#include "DNA_sequence_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_speaker_types.h"
#include "DNA_world_types.h"
#include "DNA_gpencil_types.h"
#include "DNA_object_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BLI_ghash.h"
#include "BKE_animsys.h"
#include "BKE_action.h"
#include "BKE_fcurve.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_group.h"
#include "BKE_key.h"
#include "BKE_main.h"
#include "BKE_material.h"
#include "BKE_node.h"
#include "BKE_sequencer.h"
#include "BKE_utildefines.h"
#include "ED_anim_api.h"
#include "ED_markers.h"
Defines
#define BEGIN_ANIMFILTER_SUBCHANNELS(expanded_check)
#define END_ANIMFILTER_SUBCHANNELS
#define ANIMDATA_HAS_KEYS(id) ((id)->adt && (id)->adt->action)
#define ANIMDATA_HAS_DRIVERS(id) ((id)->adt && (id)->adt->drivers.first)
#define ANIMDATA_HAS_NLA(id) ((id)->adt && (id)->adt->nla_tracks.first)
#define ANIMDATA_FILTER_CASES(id, adtOk, nlaOk, driversOk, keysOk)
#define ANIMCHANNEL_NEW_CHANNEL_FULL(channel_data, channel_type, owner_id, ale_statement)
#define ANIMCHANNEL_NEW_CHANNEL(channel_data, channel_type, owner_id) ANIMCHANNEL_NEW_CHANNEL_FULL(channel_data, channel_type, owner_id, {})
#define ANIMCHANNEL_ACTIVEOK(ale) (!(filter_mode & ANIMFILTER_ACTIVE) || !(ale->adt) || (ale->adt->flag & ADT_UI_ACTIVE))
#define ANIMCHANNEL_SELOK(test_func)
#define ANIMCHANNEL_SELEDITOK(test_func)
Functions
static Key * actedit_get_shapekeys (bAnimContext *ac)
static short actedit_get_context (bAnimContext *ac, SpaceAction *saction)
static short graphedit_get_context (bAnimContext *ac, SpaceIpo *sipo)
static short nlaedit_get_context (bAnimContext *ac, SpaceNla *snla)
short ANIM_animdata_context_getdata (bAnimContext *ac)
short ANIM_animdata_get_context (const bContext *C, bAnimContext *ac)
static bAnimListElem * make_new_animlistelem (void *data, short datatype, ID *owner_id)
static size_t skip_fcurve_selected_data (bDopeSheet *ads, FCurve *fcu, ID *owner_id, int filter_mode)
static short skip_fcurve_with_name (bDopeSheet *ads, FCurve *fcu, ID *owner_id)
static FCurve * animfilter_fcurve_next (bDopeSheet *ads, FCurve *first, bActionGroup *grp, int filter_mode, ID *owner_id)
static size_t animfilter_fcurves (ListBase *anim_data, bDopeSheet *ads, FCurve *first, bActionGroup *grp, int filter_mode, ID *owner_id)
static size_t animfilter_act_group (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, bAction *UNUSED(act), bActionGroup *agrp, int filter_mode, ID *owner_id)
static size_t animfilter_action (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, bAction *act, int filter_mode, ID *owner_id)
static size_t animfilter_nla (bAnimContext *UNUSED(ac), ListBase *anim_data, bDopeSheet *ads, AnimData *adt, int filter_mode, ID *owner_id)
static size_t animfilter_block_data (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, ID *id, int filter_mode)
static size_t animdata_filter_shapekey (bAnimContext *ac, ListBase *anim_data, Key *key, int filter_mode)
static size_t animdata_filter_gpencil_data (ListBase *anim_data, bGPdata *gpd, int filter_mode)
static size_t animdata_filter_gpencil (ListBase *anim_data, void *UNUSED(data), int filter_mode)
static size_t animdata_filter_ds_nodetree (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, ID *owner_id, bNodeTree *ntree, int filter_mode)
static size_t animdata_filter_ds_textures (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, ID *owner_id, int filter_mode)
static size_t animdata_filter_ds_materials (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, Object *ob, int filter_mode)
static size_t animdata_filter_ds_particles (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, Object *ob, int filter_mode)
static size_t animdata_filter_ds_obdata (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, Object *ob, int filter_mode)
static size_t animdata_filter_ds_keyanim (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, Object *ob, Key *key, int filter_mode)
static size_t animdata_filter_ds_obanim (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, Object *ob, int filter_mode)
static size_t animdata_filter_dopesheet_ob (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, Base *base, int filter_mode)
static size_t animdata_filter_ds_world (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, Scene *sce, World *wo, int filter_mode)
static size_t animdata_filter_ds_scene (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, Scene *sce, int filter_mode)
static size_t animdata_filter_dopesheet_scene (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, Scene *sce, int filter_mode)
static size_t animdata_filter_dopesheet (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, int filter_mode)
static short animdata_filter_dopesheet_summary (bAnimContext *ac, ListBase *anim_data, int filter_mode, size_t *items)
static size_t animdata_filter_animchan (bAnimContext *ac, ListBase *anim_data, bDopeSheet *ads, bAnimListElem *channel, int filter_mode)
static size_t animdata_filter_remove_invalid (ListBase *anim_data)
static size_t animdata_filter_remove_duplis (ListBase *anim_data)
size_t ANIM_animdata_filter (bAnimContext *ac, ListBase *anim_data, int filter_mode, void *data, short datatype)
Detailed Description
Definition in file anim_filter.c.
Define Documentation
#define ANIMCHANNEL_ACTIVEOK (ale) (!(filter_mode & ANIMFILTER_ACTIVE) || !(ale->adt) || (ale->adt->flag & ADT_UI_ACTIVE))
Definition at line 468 of file anim_filter.c.
Referenced by animdata_filter_dopesheet_ob(), animdata_filter_ds_keyanim(), animdata_filter_ds_materials(), animdata_filter_ds_nodetree(), animdata_filter_ds_obdata(), animdata_filter_ds_particles(), animdata_filter_ds_textures(), and animdata_filter_ds_world().
#define ANIMCHANNEL_NEW_CHANNEL (channel_data, channel_type, owner_id) ANIMCHANNEL_NEW_CHANNEL_FULL(channel_data, channel_type, owner_id, {})
Definition at line 462 of file anim_filter.c.
Referenced by animdata_filter_dopesheet_ob(), animdata_filter_dopesheet_scene(), animdata_filter_ds_keyanim(), animdata_filter_ds_materials(), animdata_filter_ds_nodetree(), animdata_filter_ds_obanim(), animdata_filter_ds_obdata(), animdata_filter_ds_particles(), animdata_filter_ds_scene(), animdata_filter_ds_textures(), animdata_filter_ds_world(), animdata_filter_gpencil(), animdata_filter_gpencil_data(), animdata_filter_shapekey(), animfilter_act_group(), animfilter_block_data(), and animfilter_fcurves().
#define ANIMCHANNEL_NEW_CHANNEL_FULL (channel_data, channel_type, owner_id, ale_statement)
Value:
if (filter_mode & ANIMFILTER_TMP_PEEK) \
        return 1; \
    else { \
        bAnimListElem *ale= make_new_animlistelem(channel_data, channel_type, (ID *)owner_id); \
        if (ale) {\
            BLI_addtail(anim_data, ale); \
            items++; \
            ale_statement \
        } \
    }
Definition at line 450 of file anim_filter.c.
Referenced by animfilter_nla().
#define ANIMCHANNEL_SELEDITOK (test_func)
Value:
(!(filter_mode & ANIMFILTER_SELEDIT) || \
          !(filter_mode & ANIMFILTER_FOREDIT) || \
          (test_func) )
Definition at line 485 of file anim_filter.c.
Referenced by animfilter_fcurve_next().
#define ANIMCHANNEL_SELOK (test_func)
Value:
(!(filter_mode & (ANIMFILTER_SEL|ANIMFILTER_UNSEL)) || \
          ((filter_mode & ANIMFILTER_SEL) && test_func) || \
          ((filter_mode & ANIMFILTER_UNSEL) && test_func==0) )
Definition at line 472 of file anim_filter.c.
Referenced by animdata_filter_dopesheet_ob(), animdata_filter_dopesheet_scene(), animdata_filter_gpencil_data(), animdata_filter_shapekey(), animfilter_act_group(), and animfilter_fcurve_next().
#define ANIMDATA_FILTER_CASES (id, adtOk, nlaOk, driversOk, keysOk)
Value:
{\
        if ((id)->adt) {\
            if (!(filter_mode & ANIMFILTER_CURVE_VISIBLE) || !((id)->adt->flag & ADT_CURVES_NOT_VISIBLE)) {\
                if (filter_mode & ANIMFILTER_ANIMDATA) {\
                    adtOk\
                }\
                else if (ads->filterflag & ADS_FILTER_ONLYNLA) {\
                    if (ANIMDATA_HAS_NLA(id)) {\
                        nlaOk\
                    }\
                    else if (!(ads->filterflag & ADS_FILTER_NLA_NOACT) && ANIMDATA_HAS_KEYS(id)) {\
                        nlaOk\
                    }\
                }\
                else if (ads->filterflag & ADS_FILTER_ONLYDRIVERS) {\
                    if (ANIMDATA_HAS_DRIVERS(id)) {\
                        driversOk\
                    }\
                }\
                else {\
                    if (ANIMDATA_HAS_KEYS(id)) {\
                        keysOk\
                    }\
                }\
            }\
        }\
    }
Definition at line 413 of file anim_filter.c.
Referenced by animdata_filter_ds_obanim(), animdata_filter_ds_scene(), and animfilter_block_data().
#define ANIMDATA_HAS_DRIVERS (id) ((id)->adt && (id)->adt->drivers.first)
Definition at line 380 of file anim_filter.c.
#define ANIMDATA_HAS_KEYS (id) ((id)->adt && (id)->adt->action)
Definition at line 377 of file anim_filter.c.
#define ANIMDATA_HAS_NLA (id) ((id)->adt && (id)->adt->nla_tracks.first)
Definition at line 383 of file anim_filter.c.
#define BEGIN_ANIMFILTER_SUBCHANNELS (expanded_check)
Value:
{ \
        int _filter = filter_mode; \
        short _doSubChannels = 0; \
        if (!(filter_mode & ANIMFILTER_LIST_VISIBLE) || (expanded_check)) \
            _doSubChannels=1; \
        else if (!(filter_mode & ANIMFILTER_LIST_CHANNELS)) \
            _doSubChannels=2; \
        else {\
            filter_mode |= ANIMFILTER_TMP_PEEK; \
        } \
          \
        { \
            (void) _doSubChannels; \
        }
Definition at line 354 of file anim_filter.c.
Referenced by animdata_filter_dopesheet_ob(), animdata_filter_dopesheet_scene(), animdata_filter_ds_keyanim(), animdata_filter_ds_materials(), animdata_filter_ds_nodetree(), animdata_filter_ds_obanim(), animdata_filter_ds_obdata(), animdata_filter_ds_particles(), animdata_filter_ds_scene(), animdata_filter_ds_textures(), animdata_filter_ds_world(), animdata_filter_gpencil(), and animfilter_act_group().
#define END_ANIMFILTER_SUBCHANNELS
Value:
filter_mode = _filter; \
    }
Definition at line 370 of file anim_filter.c.
Referenced by animdata_filter_dopesheet_ob(), animdata_filter_dopesheet_scene(), animdata_filter_ds_keyanim(), animdata_filter_ds_materials(), animdata_filter_ds_nodetree(), animdata_filter_ds_obanim(), animdata_filter_ds_obdata(), animdata_filter_ds_particles(), animdata_filter_ds_scene(), animdata_filter_ds_textures(), animdata_filter_ds_world(), animdata_filter_gpencil(), and animfilter_act_group().
Function Documentation
static short actedit_get_context (bAnimContext * ac, SpaceAction * saction) [static]
Definition at line 127 of file anim_filter.c.
References actedit_get_shapekeys(), AnimData::action, SpaceAction::action, SpaceAction::ads, bAnimContext::ads, Object::adt, ANIMCONT_ACTION, ANIMCONT_DOPESHEET, ANIMCONT_GPENCIL, ANIMCONT_NONE, ANIMCONT_SHAPEKEY, bAnimContext::data, bAnimContext::datatype, bAnimContext::mode, SpaceAction::mode, NULL, bAnimContext::obact, SACTCONT_ACTION, SACTCONT_DOPESHEET, SACTCONT_GPENCIL, SACTCONT_SHAPEKEY, bAnimContext::scene, and bDopeSheet::source.
Referenced by ANIM_animdata_context_getdata().
static Key* actedit_get_shapekeys (bAnimContext * ac) [static]
Definition at line 102 of file anim_filter.c.
References KEY_RELATIVE, NULL, ob_get_key(), OBACT, bAnimContext::scene, and Key::type.
Referenced by actedit_get_context().
short ANIM_animdata_context_getdata (bAnimContext * ac)
Definition at line 263 of file anim_filter.c.
References actedit_get_context(), bAnimContext::data, graphedit_get_context(), nlaedit_get_context(), bAnimContext::sl, SPACE_ACTION, SPACE_IPO, SPACE_NLA, and bAnimContext::spacetype.
Referenced by ANIM_animdata_get_context().
size_t ANIM_animdata_filter (bAnimContext * ac, ListBase * anim_data, int filter_mode, void * data, short datatype)
Definition at line 2208 of file anim_filter.c.
References bAnimContext::ads, SpaceAction::ads, ANIMCONT_ACTION, ANIMCONT_CHANNEL, ANIMCONT_DOPESHEET, ANIMCONT_DRIVERS, ANIMCONT_FCURVES, ANIMCONT_GPENCIL, ANIMCONT_NLA, ANIMCONT_SHAPEKEY, animdata_filter_animchan(), animdata_filter_dopesheet(), animdata_filter_dopesheet_summary(), animdata_filter_gpencil(), animdata_filter_remove_duplis(), animdata_filter_remove_invalid(), animdata_filter_shapekey(), animfilter_action(), ANIMFILTER_NODUPLIS, NULL, bAnimContext::obact, and bAnimContext::sl.
Referenced by achannel_setting_flush_widget_cb(), actkeys_framejump_exec(), actkeys_mselect_column(), actkeys_select_leftright(), actkeys_select_linked_exec(), ANIM_deselect_anim_channels(), ANIM_editkeyframes_refresh(), ANIM_set_active_channel(), ANIM_sync_animchannels_to_data(), animchannels_delete_exec(), animchannels_enable_exec(), animchannels_rearrange_exec(), animchannels_visibility_set_exec(), animchannels_visibility_toggle_exec(), bake_graph_curves(), borderselect_action(), borderselect_anim_channels(), borderselect_graphkeys(), borderselect_nla_strips(), clean_action_keys(), clean_graph_keys(), columnselect_action_keys(), columnselect_graph_keys(), copy_action_keys(), copy_graph_keys(), createTransActionData(), createTransNlaData(), delete_action_keys(), delete_graph_keys(), deselect_action_keys(), deselect_nla_strips(), draw_channel_names(), draw_channel_strips(), draw_nla_channel_list(), draw_nla_main_data(), duplicate_action_keys(), duplicate_graph_keys(), ED_nla_postop_refresh(), get_active_fcurve_channel(), get_graph_keyframe_extents(), get_keyframe_extents(), get_nearest_fcurve_verts_list(), get_nlastrip_extents(), graph_draw_channel_names(), graph_draw_curves(), graph_fmodifier_add_exec(), graph_fmodifier_paste_exec(), graph_refresh(), graphkeys_euler_filter_exec(), graphkeys_framejump_exec(), graphkeys_mselect_column(), graphkeys_select_leftright(), graphkeys_select_linked_exec(), graphkeys_smooth_exec(), graphop_editable_keyframes_poll(), graphop_selected_fcurve_poll(), graphop_visible_keyframes_poll(), insert_action_keys(), insert_graph_keys(), markers_selectkeys_between(), mirror_action_keys(), mirror_graph_keys(), mouse_action_keys(), mouse_anim_channels(), mouse_nla_channels(), mouse_nla_strips(), nla_fmodifier_add_exec(), nla_fmodifier_copy_exec(), nla_fmodifier_paste_exec(), nla_panel_context(), nlaedit_add_actionclip_exec(), nlaedit_add_meta_exec(), nlaedit_add_sound_exec(), nlaedit_add_tracks_exec(), nlaedit_add_transition_exec(), nlaedit_apply_scale_exec(), nlaedit_bake_exec(), nlaedit_clear_scale_exec(), nlaedit_delete_exec(), nlaedit_delete_tracks_exec(), nlaedit_disable_tweakmode_exec(), nlaedit_duplicate_exec(), nlaedit_enable_tweakmode_exec(), nlaedit_move_down_exec(), nlaedit_move_up_exec(), nlaedit_remove_meta_exec(), nlaedit_select_leftright(), nlaedit_snap_exec(), nlaedit_split_exec(), nlaedit_swap_exec(), nlaedit_sync_actlen_exec(), nlaedit_toggle_mute_exec(), ob_keyframes_loop(), ob_to_keylist(), paste_action_keys(), paste_graph_keys(), posttrans_action_clean(), rename_anim_channels(), sample_action_keys(), sample_graph_keys(), scene_keyframes_loop(), scene_to_keylist(), select_moreless_action_keys(), select_moreless_graph_keys(), setexpo_action_keys(), setexpo_graph_keys(), setflag_anim_channels(), sethandles_action_keys(), sethandles_graph_keys(), setipo_action_keys(), setipo_graph_keys(), setkeytype_action_keys(), snap_action_keys(), snap_graph_keys(), special_aftertrans_update(), summary_keyframes_loop(), and summary_to_keylist().
short ANIM_animdata_get_context (const bContext * C, bAnimContext * ac)
Definition at line 306 of file anim_filter.c.
References ANIM_animdata_context_getdata(), bAnimContext::ar, Scene::basact, CTX_data_scene(), CTX_wm_area(), CTX_wm_region(), CTX_wm_space_data(), ED_context_get_markers(), bAnimContext::markers, NULL, bAnimContext::obact, Base::object, ARegion::regiontype, bAnimContext::regiontype, bAnimContext::sa, bAnimContext::scene, bAnimContext::sl, ScrArea::spacetype, and bAnimContext::spacetype.
Referenced by achannel_setting_flush_widget_cb(), action_channel_area_draw(), action_main_area_draw(), actkeys_borderselect_exec(), actkeys_clean_exec(), actkeys_clickselect_invoke(), actkeys_columnselect_exec(), actkeys_copy_exec(), actkeys_delete_exec(), actkeys_deselectall_exec(), actkeys_duplicate_exec(), actkeys_expo_exec(), actkeys_framejump_exec(), actkeys_handletype_exec(), actkeys_insertkey_exec(), actkeys_ipo_exec(), actkeys_keytype_exec(), actkeys_mirror_exec(), actkeys_paste_exec(), actkeys_previewrange_exec(), actkeys_sample_exec(), actkeys_select_leftright_exec(), actkeys_select_leftright_invoke(), actkeys_select_less_exec(), actkeys_select_linked_exec(), actkeys_select_more_exec(), actkeys_snap_exec(), actkeys_viewall(), ANIM_sync_animchannels_to_data(), animchannels_borderselect_exec(), animchannels_collapse_exec(), animchannels_delete_exec(), animchannels_deselectall_exec(), animchannels_enable_exec(), animchannels_expand_exec(), animchannels_mouseclick_invoke(), animchannels_rearrange_exec(), animchannels_rename_invoke(), animchannels_setflag_exec(), animchannels_visibility_set_exec(), animchannels_visibility_toggle_exec(), createTransActionData(), createTransNlaData(), graph_channel_area_draw(), graph_fmodifier_add_exec(), graph_fmodifier_copy_exec(), graph_fmodifier_paste_exec(), graph_main_area_draw(), graph_panel_context(), graph_refresh(), graphkeys_bake_exec(), graphkeys_borderselect_exec(), graphkeys_clean_exec(), graphkeys_clear_ghostcurves_exec(), graphkeys_click_insert_exec(), graphkeys_click_insert_invoke(), graphkeys_clickselect_invoke(), graphkeys_columnselect_exec(), graphkeys_copy_exec(), graphkeys_create_ghostcurves_exec(), graphkeys_delete_exec(), graphkeys_deselectall_exec(), graphkeys_duplicate_exec(), graphkeys_euler_filter_exec(), graphkeys_expo_exec(), graphkeys_framejump_exec(), graphkeys_handletype_exec(), graphkeys_insertkey_exec(), graphkeys_ipo_exec(), graphkeys_mirror_exec(), graphkeys_paste_exec(), graphkeys_previewrange_exec(), graphkeys_sample_exec(), graphkeys_select_leftright_exec(), graphkeys_select_leftright_invoke(), graphkeys_select_less_exec(), graphkeys_select_linked_exec(), graphkeys_select_more_exec(), graphkeys_smooth_exec(), graphkeys_snap_exec(), graphkeys_sound_bake_invoke(), graphkeys_viewall(), graphop_active_fcurve_poll(), graphop_editable_keyframes_poll(), graphop_selected_fcurve_poll(), graphop_visible_keyframes_poll(), nla_channel_area_draw(), nla_fmodifier_add_exec(), nla_fmodifier_copy_exec(), nla_fmodifier_paste_exec(), nla_main_area_draw(), nla_panel_context(), nlachannels_mouseclick_invoke(), nlaedit_add_actionclip_exec(), nlaedit_add_meta_exec(), nlaedit_add_sound_exec(), nlaedit_add_tracks_exec(), nlaedit_add_transition_exec(), nlaedit_apply_scale_exec(), nlaedit_bake_exec(), nlaedit_borderselect_exec(), nlaedit_clear_scale_exec(), nlaedit_clickselect_invoke(), nlaedit_delete_exec(), nlaedit_delete_tracks_exec(), nlaedit_deselectall_exec(), nlaedit_disable_tweakmode_exec(), nlaedit_duplicate_exec(), nlaedit_enable_tweakmode_exec(), nlaedit_move_down_exec(), nlaedit_move_up_exec(), nlaedit_remove_meta_exec(), nlaedit_select_leftright_exec(), nlaedit_select_leftright_invoke(), nlaedit_snap_exec(), nlaedit_split_exec(), nlaedit_swap_exec(), nlaedit_sync_actlen_exec(), nlaedit_toggle_mute_exec(), nlaedit_viewall(), and special_aftertrans_update().
static size_t animdata_filter_animchan (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, bAnimListElem * channel, int filter_mode) [static]
Definition at line 2117 of file anim_filter.c.
References animdata_filter_dopesheet(), animdata_filter_dopesheet_ob(), animdata_filter_dopesheet_scene(), ANIMTYPE_OBJECT, ANIMTYPE_SCENE, ANIMTYPE_SUMMARY, bAnimListElem::data, and bAnimListElem::type.
Referenced by ANIM_animdata_filter().
static size_t animdata_filter_dopesheet (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, int filter_mode) [static]
Definition at line 1991 of file anim_filter.c.
References ADS_FILTER_INCL_HIDDEN, ADS_FILTER_ONLYOBGROUP, ADS_FILTER_ONLYSEL, ADS_FILTER_SELEDIT, Object::adt, ADT_CURVES_NOT_VISIBLE, animdata_filter_dopesheet_ob(), animdata_filter_dopesheet_scene(), ANIMFILTER_CURVE_VISIBLE, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_SELEDIT, Scene::base, bDopeSheet::filter_grp, bDopeSheet::filterflag, ListBase::first, AnimData::flag, G, G_DEBUG, GS, ID_SCE, if(), Object::lay, Scene::lay, ID::name, NULL, OB_RESTRICT_VIEW, object_in_group(), Object::restrictflag, SELECT, and bDopeSheet::source.
Referenced by ANIM_animdata_filter(), and animdata_filter_animchan().
static size_t animdata_filter_dopesheet_ob (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, Base * base, int filter_mode) [static]
Definition at line 1778 of file anim_filter.c.
References ADS_FILTER_NOMAT, ADS_FILTER_NOOBJ, ADS_FILTER_NOPART, ADS_FILTER_NOSHAPEKEYS, Key::adt, Object::adt, ANIMCHANNEL_ACTIVEOK, ANIMCHANNEL_NEW_CHANNEL, ANIMCHANNEL_SELOK, animdata_filter_ds_keyanim(), animdata_filter_ds_materials(), animdata_filter_ds_obanim(), animdata_filter_ds_obdata(), animdata_filter_ds_particles(), ANIMTYPE_OBJECT, BEGIN_ANIMFILTER_SUBCHANNELS, BLI_assert, BLI_movelisttolist(), Object::data, END_ANIMFILTER_SUBCHANNELS, EXPANDED_OBJC, bDopeSheet::filterflag, ListBase::first, Base::flag, ListBase::last, NULL, ob_get_key(), Base::object, Object::particlesystem, SELECT, and Object::totcol.
Referenced by animdata_filter_animchan(), and animdata_filter_dopesheet().
static size_t animdata_filter_dopesheet_scene (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, Scene * sce, int filter_mode) [static]
Definition at line 1938 of file anim_filter.c.
References ADS_FILTER_NONTREE, ADS_FILTER_NOSCE, ADS_FILTER_NOWOR, ANIMCHANNEL_NEW_CHANNEL, ANIMCHANNEL_SELOK, animdata_filter_ds_nodetree(), animdata_filter_ds_scene(), animdata_filter_ds_world(), ANIMTYPE_SCENE, BEGIN_ANIMFILTER_SUBCHANNELS, BLI_assert, BLI_movelisttolist(), END_ANIMFILTER_SUBCHANNELS, EXPANDED_SCEC, bDopeSheet::filterflag, ListBase::first, Scene::flag, ListBase::last, Scene::nodetree, NULL, SCE_DS_SELECTED, and Scene::world.
Referenced by animdata_filter_animchan(), and animdata_filter_dopesheet().
static short animdata_filter_dopesheet_summary (bAnimContext * ac, ListBase * anim_data, int filter_mode, size_t * items) [static]
Definition at line 2074 of file anim_filter.c.
References SpaceAction::ads, ADS_FILTER_SUMMARY, ADS_FLAG_SUMMARY_COLLAPSED, ANIMTYPE_SUMMARY, BLI_addtail(), bDopeSheet::filterflag, bDopeSheet::flag, make_new_animlistelem(), NULL, bAnimContext::sl, SPACE_ACTION, and bAnimContext::spacetype.
Referenced by ANIM_animdata_filter().
static size_t animdata_filter_ds_keyanim (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, Object * ob, Key * key, int filter_mode) [static]
Definition at line 1689 of file anim_filter.c.
References ANIMCHANNEL_ACTIVEOK, ANIMCHANNEL_NEW_CHANNEL, animfilter_block_data(), ANIMTYPE_DSSKEY, BEGIN_ANIMFILTER_SUBCHANNELS, BLI_assert, BLI_movelisttolist(), END_ANIMFILTER_SUBCHANNELS, FILTER_SKE_OBJD, ListBase::first, ListBase::last, and NULL.
Referenced by animdata_filter_dopesheet_ob().
static size_t animdata_filter_ds_materials (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, Object * ob, int filter_mode) [static]
Definition at line 1455 of file anim_filter.c.
References ADS_FILTER_NONTREE, ADS_FILTER_NOTEX, ANIMCHANNEL_ACTIVEOK, ANIMCHANNEL_NEW_CHANNEL, animdata_filter_ds_nodetree(), animdata_filter_ds_textures(), animfilter_block_data(), ANIMTYPE_DSMAT, BEGIN_ANIMFILTER_SUBCHANNELS, BLI_assert, BLI_movelisttolist(), END_ANIMFILTER_SUBCHANNELS, FILTER_MAT_OBJD, bDopeSheet::filterflag, ListBase::first, give_current_material(), ListBase::last, NULL, and Object::totcol.
Referenced by animdata_filter_dopesheet_ob().
static size_t animdata_filter_ds_nodetree (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, ID * owner_id, bNodeTree * ntree, int filter_mode) [static]
Definition at line 1335 of file anim_filter.c.
References ANIMCHANNEL_ACTIVEOK, ANIMCHANNEL_NEW_CHANNEL, animfilter_block_data(), ANIMTYPE_DSNTREE, BEGIN_ANIMFILTER_SUBCHANNELS, BLI_assert, BLI_movelisttolist(), END_ANIMFILTER_SUBCHANNELS, FILTER_NTREE_DATA, ListBase::first, ListBase::last, and NULL.
Referenced by animdata_filter_dopesheet_scene(), animdata_filter_ds_materials(), animdata_filter_ds_textures(), and animdata_filter_ds_world().
static size_t animdata_filter_ds_obanim (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, Object * ob, int filter_mode) [static]
Definition at line 1723 of file anim_filter.c.
References AnimData::action, Object::adt, ANIMCHANNEL_NEW_CHANNEL, ANIMDATA_FILTER_CASES, animfilter_block_data(), ANIMTYPE_FILLACTD, ANIMTYPE_FILLDRIVERS, ANIMTYPE_NONE, BEGIN_ANIMFILTER_SUBCHANNELS, BLI_assert, BLI_movelisttolist(), END_ANIMFILTER_SUBCHANNELS, EXPANDED_ACTC, EXPANDED_DRVD, ListBase::first, ListBase::last, and NULL.
Referenced by animdata_filter_dopesheet_ob().
static size_t animdata_filter_ds_obdata (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, Object * ob, int filter_mode) [static]
Definition at line 1549 of file anim_filter.c.
References ADS_FILTER_NOARM, ADS_FILTER_NOCAM, ADS_FILTER_NOCUR, ADS_FILTER_NOLAM, ADS_FILTER_NOLAT, ADS_FILTER_NOMBA, ADS_FILTER_NOMESH, ADS_FILTER_NOTEX, ANIMCHANNEL_ACTIVEOK, ANIMCHANNEL_NEW_CHANNEL, animdata_filter_ds_textures(), animfilter_block_data(), ANIMTYPE_DSARM, ANIMTYPE_DSCAM, ANIMTYPE_DSCUR, ANIMTYPE_DSLAM, ANIMTYPE_DSLAT, ANIMTYPE_DSMBALL, ANIMTYPE_DSMESH, ANIMTYPE_DSSPK, BEGIN_ANIMFILTER_SUBCHANNELS, BLI_assert, BLI_movelisttolist(), Object::data, END_ANIMFILTER_SUBCHANNELS, FILTER_ARM_OBJD, FILTER_CAM_OBJD, FILTER_CUR_OBJD, FILTER_LAM_OBJD, FILTER_LATTICE_OBJD, FILTER_MBALL_OBJD, FILTER_MESH_OBJD, FILTER_SPK_OBJD, bDopeSheet::filterflag, ListBase::first, if(), ListBase::last, NULL, OB_ARMATURE, OB_CAMERA, OB_CURVE, OB_FONT, OB_LAMP, OB_LATTICE, OB_MBALL, OB_MESH, OB_SPEAKER, OB_SURF, and Object::type.
Referenced by animdata_filter_dopesheet_ob().
static size_t animdata_filter_ds_particles (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, Object * ob, int filter_mode) [static]
Definition at line 1507 of file anim_filter.c.
References ParticleSettings::adt, ANIMCHANNEL_ACTIVEOK, ANIMCHANNEL_NEW_CHANNEL, animfilter_block_data(), ANIMTYPE_DSPART, BEGIN_ANIMFILTER_SUBCHANNELS, BLI_assert, BLI_movelisttolist(), ELEM, END_ANIMFILTER_SUBCHANNELS, FILTER_PART_OBJD, ListBase::first, ListBase::last, ParticleSystem::next, NULL, ParticleSystem::part, and Object::particlesystem.
Referenced by animdata_filter_dopesheet_ob().
static size_t animdata_filter_ds_scene (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, Scene * sce, int filter_mode) [static]
Definition at line 1884 of file anim_filter.c.
References AnimData::action, Scene::adt, ANIMCHANNEL_NEW_CHANNEL, ANIMDATA_FILTER_CASES, animfilter_block_data(), ANIMTYPE_FILLACTD, ANIMTYPE_FILLDRIVERS, ANIMTYPE_NONE, BEGIN_ANIMFILTER_SUBCHANNELS, BLI_assert, BLI_movelisttolist(), END_ANIMFILTER_SUBCHANNELS, EXPANDED_ACTC, EXPANDED_DRVD, ListBase::first, ListBase::last, and NULL.
Referenced by animdata_filter_dopesheet_scene().
static size_t animdata_filter_ds_textures (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, ID * owner_id, int filter_mode) [static]
Definition at line 1370 of file anim_filter.c.
References ADS_FILTER_NONTREE, ANIMCHANNEL_ACTIVEOK, ANIMCHANNEL_NEW_CHANNEL, animdata_filter_ds_nodetree(), animfilter_block_data(), ANIMTYPE_DSTEX, BEGIN_ANIMFILTER_SUBCHANNELS, BLI_assert, BLI_movelisttolist(), END_ANIMFILTER_SUBCHANNELS, FILTER_TEX_DATA, bDopeSheet::filterflag, ListBase::first, G, G_DEBUG, GS, ID_LA, ID_MA, ID_WO, ListBase::last, MAX_MTEX, Lamp::mtex, World::mtex, Material::mtex, ID::name, and NULL.
Referenced by animdata_filter_ds_materials(), animdata_filter_ds_obdata(), and animdata_filter_ds_world().
static size_t animdata_filter_ds_world (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, Scene * sce, World * wo, int filter_mode) [static]
Definition at line 1842 of file anim_filter.c.
References ADS_FILTER_NONTREE, ADS_FILTER_NOTEX, ANIMCHANNEL_ACTIVEOK, ANIMCHANNEL_NEW_CHANNEL, animdata_filter_ds_nodetree(), animdata_filter_ds_textures(), animfilter_block_data(), ANIMTYPE_DSWOR, BEGIN_ANIMFILTER_SUBCHANNELS, BLI_assert, BLI_movelisttolist(), END_ANIMFILTER_SUBCHANNELS, FILTER_WOR_SCED, bDopeSheet::filterflag, ListBase::first, ListBase::last, and NULL.
Referenced by animdata_filter_dopesheet_scene().
static size_t animdata_filter_gpencil (ListBase * anim_data, void * UNUSEDdata, int filter_mode) [static]
Definition at line 1292 of file anim_filter.c.
References ANIMCHANNEL_NEW_CHANNEL, animdata_filter_gpencil_data(), ANIMTYPE_GPDATABLOCK, BEGIN_ANIMFILTER_SUBCHANNELS, BLI_assert, BLI_movelisttolist(), END_ANIMFILTER_SUBCHANNELS, EXPANDED_GPD, ListBase::first, G, bGPdata::id, ID_REAL_USERS, ListBase::last, ID::next, and NULL.
Referenced by ANIM_animdata_filter().
static size_t animdata_filter_gpencil_data (ListBase * anim_data, bGPdata * gpd, int filter_mode) [static]
Definition at line 1267 of file anim_filter.c.
References ANIMCHANNEL_NEW_CHANNEL, ANIMCHANNEL_SELOK, ANIMFILTER_ACTIVE, ANIMTYPE_GPLAYER, EDITABLE_GPL, ListBase::first, bGPDlayer::flag, GP_LAYER_ACTIVE, bGPdata::layers, bGPDlayer::next, and SEL_GPL.
Referenced by animdata_filter_gpencil().
static size_t animdata_filter_remove_duplis (ListBase * anim_data) [static]
Definition at line 2162 of file anim_filter.c.
References BLI_freelinkN(), BLI_ghash_free(), BLI_ghash_haskey(), BLI_ghash_insert(), BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), bAnimListElem::data, ListBase::first, bAnimListElem::next, next, and NULL.
Referenced by ANIM_animdata_filter().
static size_t animdata_filter_remove_invalid (ListBase * anim_data) [static]
Definition at line 2143 of file anim_filter.c.
References ANIMTYPE_NONE, BLI_freelinkN(), ListBase::first, bAnimListElem::next, next, and bAnimListElem::type.
Referenced by ANIM_animdata_filter().
static size_t animdata_filter_shapekey (bAnimContext * ac, ListBase * anim_data, Key * key, int filter_mode) [static]
Definition at line 1224 of file anim_filter.c.
References AnimData::action, Key::adt, ANIMCHANNEL_NEW_CHANNEL, ANIMCHANNEL_SELOK, animfilter_action(), ANIMFILTER_ANIMDATA, ANIMTYPE_ANIMDATA, ANIMTYPE_SHAPEKEY, Key::block, EDITABLE_SHAPEKEY, ListBase::first, KeyBlock::next, NULL, and SEL_SHAPEKEY.
Referenced by ANIM_animdata_filter().
static size_t animfilter_act_group (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, bAction * UNUSEDact, bActionGroup * agrp, int filter_mode, ID * owner_id) [static]
Definition at line 1004 of file anim_filter.c.
References AGRP_ACTIVE, AGRP_NOTVISIBLE, ANIMCHANNEL_NEW_CHANNEL, ANIMCHANNEL_SELOK, ANIMFILTER_ACTGROUPED, ANIMFILTER_CURVE_VISIBLE, animfilter_fcurve_next(), animfilter_fcurves(), ANIMFILTER_FOREDIT, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, ANIMFILTER_SEL, ANIMFILTER_UNSEL, ANIMTYPE_GROUP, BEGIN_ANIMFILTER_SUBCHANNELS, BLI_assert, BLI_movelisttolist(), bActionGroup::channels, EDITABLE_AGRP, END_ANIMFILTER_SUBCHANNELS, EXPANDED_AGRP, ListBase::first, bActionGroup::flag, ListBase::last, NULL, and SEL_AGRP.
Referenced by animfilter_action().
static size_t animfilter_action (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, bAction * act, int filter_mode, ID * owner_id) [static]
Definition at line 1081 of file anim_filter.c.
References animfilter_act_group(), ANIMFILTER_ACTGROUPED, animfilter_fcurves(), ANIMFILTER_FOREDIT, bActionGroup::channels, bAction::curves, ListBase::first, bAction::groups, bAction::id, ListBase::last, ID::lib, FCurve::next, bActionGroup::next, and NULL.
Referenced by ANIM_animdata_filter(), animdata_filter_shapekey(), and animfilter_block_data().
static size_t animfilter_block_data (bAnimContext * ac, ListBase * anim_data, bDopeSheet * ads, ID * id, int filter_mode) [static]
Definition at line 1188 of file anim_filter.c.
References AnimData::action, ANIMCHANNEL_NEW_CHANNEL, ANIMDATA_FILTER_CASES, animfilter_action(), animfilter_fcurves(), animfilter_nla(), ANIMTYPE_ANIMDATA, BKE_animdata_from_id(), AnimData::drivers, ListBase::first, and NULL.
Referenced by animdata_filter_ds_keyanim(), animdata_filter_ds_materials(), animdata_filter_ds_nodetree(), animdata_filter_ds_obanim(), animdata_filter_ds_obdata(), animdata_filter_ds_particles(), animdata_filter_ds_scene(), animdata_filter_ds_textures(), and animdata_filter_ds_world().
static FCurve* animfilter_fcurve_next (bDopeSheet * ads, FCurve * first, bActionGroup * grp, int filter_mode, ID * owner_id) [static]
Definition at line 934 of file anim_filter.c.
References ADS_FILTER_BY_FCU_NAME, ADS_FILTER_ONLYSEL, ANIMCHANNEL_SELEDITOK, ANIMCHANNEL_SELOK, ANIMFILTER_ACTIVE, ANIMFILTER_CURVE_VISIBLE, ANIMFILTER_FOREDIT, EDITABLE_FCU, FCURVE_ACTIVE, FCURVE_VISIBLE, bDopeSheet::filterflag, FCurve::flag, FCurve::grp, FCurve::next, NULL, SEL_FCU, skip_fcurve_selected_data(), and skip_fcurve_with_name().
Referenced by animfilter_act_group(), and animfilter_fcurves().
static size_t animfilter_fcurves (ListBase * anim_data, bDopeSheet * ads, FCurve * first, bActionGroup * grp, int filter_mode, ID * owner_id) [static]
Definition at line 981 of file anim_filter.c.
References ANIMCHANNEL_NEW_CHANNEL, animfilter_fcurve_next(), ANIMTYPE_FCURVE, and FCurve::next.
Referenced by animfilter_act_group(), animfilter_action(), and animfilter_block_data().
static size_t animfilter_nla (bAnimContext * UNUSEDac, ListBase * anim_data, bDopeSheet * ads, AnimData * adt, int filter_mode, ID * owner_id) [static]
Definition at line 1123 of file anim_filter.c.
References AnimData::action, ADS_FILTER_NLA_NOACT, ANIMCHANNEL_NEW_CHANNEL_FULL, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_CHANNELS, ANIMTYPE_NLAACTION, bDopeSheet::filterflag, ListBase::last, next, AnimData::nla_tracks, and NULL.
Referenced by animfilter_block_data().
static short graphedit_get_context (bAnimContext * ac, SpaceIpo * sipo) [static]
Definition at line 188 of file anim_filter.c.
References SpaceIpo::ads, bAnimContext::ads, ADS_FILTER_ONLYDRIVERS, ADS_FILTER_SELEDIT, ANIMCONT_DRIVERS, ANIMCONT_FCURVES, ANIMCONT_NONE, bAnimContext::data, bAnimContext::datatype, bDopeSheet::filterflag, SpaceIpo::flag, MEM_callocN(), SpaceIpo::mode, bAnimContext::mode, NULL, bAnimContext::scene, SIPO_MODE_ANIMATION, SIPO_MODE_DRIVERS, SIPO_SELCUVERTSONLY, and bDopeSheet::source.
Referenced by ANIM_animdata_context_getdata().
static bAnimListElem* make_new_animlistelem (void * data, short datatype, ID * owner_id) [static]
Definition at line 495 of file anim_filter.c.
References AnimData::action, bAnimListElem::adt, Lamp::adt, Material::adt, Lattice::adt, Key::adt, World::adt, bNodeTree::adt, Mesh::adt, Camera::adt, Speaker::adt, Tex::adt, bArmature::adt, ParticleSettings::adt, Curve::adt, ALE_ACT, ALE_ALL, ALE_FCURVE, ALE_GPFRAME, ALE_GROUP, ALE_NLASTRIP, ALE_NONE, ALE_OB, ALE_SCE, ANIMTYPE_DSARM, ANIMTYPE_DSCAM, ANIMTYPE_DSCUR, ANIMTYPE_DSLAM, ANIMTYPE_DSLAT, ANIMTYPE_DSMAT, ANIMTYPE_DSMESH, ANIMTYPE_DSNTREE, ANIMTYPE_DSPART, ANIMTYPE_DSSKEY, ANIMTYPE_DSSPK, ANIMTYPE_DSTEX, ANIMTYPE_DSWOR, ANIMTYPE_FCURVE, ANIMTYPE_FILLACTD, ANIMTYPE_FILLDRIVERS, ANIMTYPE_GPLAYER, ANIMTYPE_GROUP, ANIMTYPE_NLAACTION, ANIMTYPE_NLATRACK, ANIMTYPE_OBJECT, ANIMTYPE_SCENE, ANIMTYPE_SHAPEKEY, ANIMTYPE_SUMMARY, BKE_animdata_from_id(), BLI_findindex(), Key::block, bAction::curves, data, bAnimListElem::data, bAnimListElem::datatype, FILTER_ARM_OBJD, FILTER_CAM_OBJD, FILTER_CUR_OBJD, FILTER_LAM_OBJD, FILTER_LATTICE_OBJD, FILTER_MAT_OBJD, FILTER_MESH_OBJD, FILTER_NTREE_DATA, FILTER_PART_OBJD, FILTER_SKE_OBJD, FILTER_SPK_OBJD, FILTER_TEX_DATA, FILTER_WOR_SCED, AnimData::flag, Object::flag, KeyBlock::flag, bAction::flag, bGPDlayer::flag, bAnimListElem::flag, Scene::flag, FCurve::flag, NlaTrack::flag, bActionGroup::flag, Object::id, bAnimListElem::id, if(), bAnimListElem::index, bAnimListElem::key_data, key_get_curValue_rnaPath(), list_find_fcurve(), MEM_callocN(), MEM_freeN(), NULL, Base::object, NlaTrack::strips, and bAnimListElem::type.
Referenced by animdata_filter_dopesheet_summary().
static short nlaedit_get_context (bAnimContext * ac, SpaceNla * snla) [static]
Definition at line 239 of file anim_filter.c.
References SpaceNla::ads, bAnimContext::ads, ADS_FILTER_ONLYNLA, ANIMCONT_NLA, bAnimContext::data, bAnimContext::datatype, bDopeSheet::filterflag, MEM_callocN(), NULL, bAnimContext::scene, and bDopeSheet::source.
Referenced by ANIM_animdata_context_getdata().
static size_t skip_fcurve_selected_data (bDopeSheet * ads, FCurve * fcu, ID * owner_id, int filter_mode) [static]
Definition at line 830 of file anim_filter.c.
References ADS_FILTER_INCL_HIDDEN, ANIMFILTER_DATA_VISIBLE, BLI_getQuotedStr(), bPoseChannel::bone, BONE_SELECTED, Object::data, FALSE, bDopeSheet::filterflag, Sequence::flag, bNode::flag, Bone::flag, get_pose_channel(), get_seq_by_name(), GS, ID_NT, ID_OB, ID_SCE, if(), Bone::layer, bArmature::layer, MEM_freeN(), ID::name, NODE_SELECT, nodeFindNodebyName(), NULL, Object::pose, FCurve::rna_path, SELECT, seq_give_editing(), and Editing::seqbasep.
Referenced by animfilter_fcurve_next().
static short skip_fcurve_with_name (bDopeSheet * ads, FCurve * fcu, ID * owner_id) [static]
Definition at line 905 of file anim_filter.c.
References ANIM_channel_get_typeinfo(), ANIMTYPE_FCURVE, BLI_strcasestr(), bAnimListElem::data, bAnimListElem::id, bAnimChannelType::name, NULL, bDopeSheet::searchstr, and bAnimListElem::type.
Referenced by animfilter_fcurve_next().