Blender: node_shader_bsdf_transparent.c File Reference
node_shader_bsdf_transparent.c File Reference
#include "../node_shader_util.h"
Functions
static int node_shader_gpu_bsdf_transparent (GPUMaterial *mat, bNode *UNUSED(node), GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_bsdf_transparent (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_bsdf_transparent_in []
static bNodeSocketTemplate sh_node_bsdf_transparent_out []
Function Documentation
static int node_shader_gpu_bsdf_transparent (GPUMaterial * mat, bNode * UNUSEDnode, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 42 of file node_shader_bsdf_transparent.c.
References GPU_stack_link().
Referenced by register_node_type_sh_bsdf_transparent().
void register_node_type_sh_bsdf_transparent (bNodeTreeType * ttype)
Definition at line 48 of file node_shader_bsdf_transparent.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_shader_gpu_bsdf_transparent(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_BSDF_TRANSPARENT.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_bsdf_transparent_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Color",      1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 32 of file node_shader_bsdf_transparent.c.
bNodeSocketTemplate sh_node_bsdf_transparent_out[] [static]
Initial value:
 {
    {   SOCK_SHADER, 0, "BSDF"},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_shader_bsdf_transparent.c.