Blender: BKE_sequencer.h File Reference
BKE_sequencer.h File Reference
blenkernel
Classes
struct SeqIterator
struct SeqRenderData
struct SeqEffectHandle
struct SeqLoadInfo
Defines
#define BUILD_SEQAR_COUNT_NOTHING 0
#define BUILD_SEQAR_COUNT_CURRENT 1
#define BUILD_SEQAR_COUNT_CHILDREN 2
#define EARLY_NO_INPUT -1
#define EARLY_DO_EFFECT 0
#define EARLY_USE_INPUT_1 1
#define EARLY_USE_INPUT_2 2
#define SEQP_BEGIN(ed, _seq)
#define SEQ_BEGIN(ed, _seq)
#define SEQ_END
#define SEQ_LOAD_REPLACE_SEL (1<<0)
#define SEQ_LOAD_FRAME_ADVANCE (1<<1)
#define SEQ_LOAD_MOVIE_SOUND (1<<2)
#define SEQ_LOAD_SOUND_CACHE (1<<3)
#define SEQ_DUPE_UNIQUE_NAME (1<<0)
#define SEQ_DUPE_CONTEXT (1<<1)
#define SEQ_DUPE_ANIM (1<<2)
#define SEQ_DUPE_ALL (1<<3)
Typedefs
typedef struct SeqIterator SeqIterator
typedef struct SeqRenderData SeqRenderData
typedef struct SeqLoadInfo SeqLoadInfo
typedef struct Sequence *(* SeqLoadFunc)(struct bContext *, ListBase *, struct SeqLoadInfo *)
typedef struct ImBuf *(* SequencerDrawView)(struct Scene *, struct Object *, int, int, unsigned int, int, int, char[256])
Enumerations
enum {
DO_SINGLE_WIPE, DO_DOUBLE_WIPE, DO_BOX_WIPE, DO_CROSS_WIPE,
DO_IRIS_WIPE, DO_CLOCK_WIPE
}
enum seq_stripelem_ibuf_t { SEQ_STRIPELEM_IBUF, SEQ_STRIPELEM_IBUF_COMP, SEQ_STRIPELEM_IBUF_STARTSTILL, SEQ_STRIPELEM_IBUF_ENDSTILL }
Functions
void seq_begin (struct Editing *ed, SeqIterator *iter, int use_pointer)
void seq_next (SeqIterator *iter)
void seq_end (SeqIterator *iter)
void seq_array (struct Editing *ed, struct Sequence ***seqarray, int *tot, int use_pointer)
SeqRenderData seq_new_render_data (struct Main *bmain, struct Scene *scene, int rectx, int recty, int preview_render_size)
int seq_cmp_render_data (const SeqRenderData *a, const SeqRenderData *b)
unsigned int seq_hash_render_data (const SeqRenderData *a)
struct ImBuf * give_ibuf_seq (SeqRenderData context, float cfra, int chanshown)
struct ImBuf * give_ibuf_seq_threaded (SeqRenderData context, float cfra, int chanshown)
struct ImBuf * give_ibuf_seq_direct (SeqRenderData context, float cfra, struct Sequence *seq)
struct ImBuf * give_ibuf_seqbase (SeqRenderData context, float cfra, int chan_shown, struct ListBase *seqbasep)
void give_ibuf_prefetch_request (SeqRenderData context, float cfra, int chan_shown)
int seqbase_recursive_apply (struct ListBase *seqbase, int(*apply_func)(struct Sequence *seq, void *), void *arg)
int seq_recursive_apply (struct Sequence *seq, int(*apply_func)(struct Sequence *, void *), void *arg)
void seq_free_sequence (struct Scene *scene, struct Sequence *seq)
void seq_free_sequence_recurse (struct Scene *scene, struct Sequence *seq)
void seq_free_strip (struct Strip *strip)
void seq_free_editing (struct Scene *scene)
void seq_free_clipboard (void)
struct Editing * seq_give_editing (struct Scene *scene, int alloc)
const char * give_seqname (struct Sequence *seq)
void calc_sequence (struct Scene *scene, struct Sequence *seq)
void calc_sequence_disp (struct Scene *scene, struct Sequence *seq)
void reload_sequence_new_file (struct Scene *scene, struct Sequence *seq, int lock_range)
void sort_seq (struct Scene *scene)
void build_seqar_cb (struct ListBase *seqbase, struct Sequence ***seqar, int *totseq, int(*test_func)(struct Sequence *seq))
int evaluate_seq_frame (struct Scene *scene, int cfra)
struct StripElem * give_stripelem (struct Sequence *seq, int cfra)
void printf_strip (struct Sequence *seq)
void update_changed_seq_and_deps (struct Scene *scene, struct Sequence *changed_seq, int len_change, int ibuf_change)
int input_have_to_preprocess (SeqRenderData context, struct Sequence *seq, float cfra)
struct SeqIndexBuildContext * seq_proxy_rebuild_context (struct Main *bmain, struct Scene *scene, struct Sequence *seq)
void seq_proxy_rebuild (struct SeqIndexBuildContext *context, short *stop, short *do_update, float *progress)
void seq_proxy_rebuild_finish (struct SeqIndexBuildContext *context, short stop)
void seq_stripelem_cache_destruct (void)
void seq_stripelem_cache_cleanup (void)
struct ImBuf * seq_stripelem_cache_get (SeqRenderData context, struct Sequence *seq, float cfra, seq_stripelem_ibuf_t type)
void seq_stripelem_cache_put (SeqRenderData context, struct Sequence *seq, float cfra, seq_stripelem_ibuf_t type, struct ImBuf *nval)
struct SeqEffectHandle get_sequence_blend (struct Sequence *seq)
void sequence_effect_speed_rebuild_map (struct Scene *scene, struct Sequence *seq, int force)
struct SeqEffectHandle get_sequence_effect (struct Sequence *seq)
int get_sequence_effect_num_inputs (int seq_type)
int seq_tx_get_start (struct Sequence *seq)
int seq_tx_get_end (struct Sequence *seq)
int seq_tx_get_final_left (struct Sequence *seq, int metaclip)
int seq_tx_get_final_right (struct Sequence *seq, int metaclip)
void seq_tx_set_final_left (struct Sequence *seq, int val)
void seq_tx_set_final_right (struct Sequence *seq, int val)
void seq_tx_handle_xlimits (struct Sequence *seq, int leftflag, int rightflag)
int seq_tx_test (struct Sequence *seq)
int seq_single_check (struct Sequence *seq)
void seq_single_fix (struct Sequence *seq)
int seq_test_overlap (struct ListBase *seqbasep, struct Sequence *test)
void seq_translate (struct Scene *scene, struct Sequence *seq, int delta)
void seq_sound_init (struct Scene *scene, struct Sequence *seq)
struct Sequence * seq_foreground_frame_get (struct Scene *scene, int frame)
struct ListBase * seq_seqbase (struct ListBase *seqbase, struct Sequence *seq)
struct Sequence * seq_metastrip (ListBase *seqbase, struct Sequence *meta, struct Sequence *seq)
void seq_offset_animdata (struct Scene *scene, struct Sequence *seq, int ofs)
void seq_dupe_animdata (struct Scene *scene, const char *name_src, const char *name_dst)
int shuffle_seq (struct ListBase *seqbasep, struct Sequence *test, struct Scene *evil_scene)
int shuffle_seq_time (ListBase *seqbasep, struct Scene *evil_scene)
int seqbase_isolated_sel_check (struct ListBase *seqbase)
void free_imbuf_seq (struct Scene *scene, struct ListBase *seqbasep, int check_mem_usage, int keep_file_handles)
struct Sequence * seq_dupli_recursive (struct Scene *scene, struct Scene *scene_to, struct Sequence *seq, int dupe_flag)
int seq_swap (struct Sequence *seq_a, struct Sequence *seq_b, const char **error_str)
void seq_update_sound_bounds_all (struct Scene *scene)
void seq_update_sound_bounds (struct Scene *scene, struct Sequence *seq)
void seq_update_muting (struct Editing *ed)
void seq_update_sound (struct Scene *scene, struct bSound *sound)
void seqbase_unique_name_recursive (ListBase *seqbasep, struct Sequence *seq)
void seqbase_dupli_recursive (struct Scene *scene, struct Scene *scene_to, ListBase *nseqbase, ListBase *seqbase, int dupe_flag)
void clear_scene_in_allseqs (struct Main *bmain, struct Scene *sce)
struct Sequence * get_seq_by_name (struct ListBase *seqbase, const char *name, int recursive)
struct Sequence * seq_active_get (struct Scene *scene)
void seq_active_set (struct Scene *scene, struct Sequence *seq)
int seq_active_pair_get (struct Scene *scene, struct Sequence **seq_act, struct Sequence **seq_other)
struct Sequence * alloc_sequence (ListBase *lb, int cfra, int machine)
void seq_load_apply (struct Scene *scene, struct Sequence *seq, struct SeqLoadInfo *seq_load)
struct Sequence * sequencer_add_image_strip (struct bContext *C, ListBase *seqbasep, struct SeqLoadInfo *seq_load)
struct Sequence * sequencer_add_sound_strip (struct bContext *C, ListBase *seqbasep, struct SeqLoadInfo *seq_load)
struct Sequence * sequencer_add_movie_strip (struct bContext *C, ListBase *seqbasep, struct SeqLoadInfo *seq_load)
Variables
SequencerDrawView sequencer_view3d_cb
ListBase seqbase_clipboard
int seqbase_clipboard_frame
Detailed Description
Definition in file BKE_sequencer.h.
Define Documentation
#define BUILD_SEQAR_COUNT_CHILDREN 2
Definition at line 47 of file BKE_sequencer.h.
Referenced by do_build_seqar_cb(), and do_seq_count_cb().
#define BUILD_SEQAR_COUNT_CURRENT 1
Definition at line 46 of file BKE_sequencer.h.
Referenced by do_build_seqar_cb(), and do_seq_count_cb().
#define BUILD_SEQAR_COUNT_NOTHING 0
Definition at line 45 of file BKE_sequencer.h.
#define EARLY_DO_EFFECT 0
Definition at line 50 of file BKE_sequencer.h.
Referenced by seq_get_early_out_for_blend_mode(), seq_render_effect_strip_impl(), and seq_render_strip_stack().
#define EARLY_NO_INPUT -1
Definition at line 49 of file BKE_sequencer.h.
Referenced by seq_get_early_out_for_blend_mode(), seq_render_effect_strip_impl(), and seq_render_strip_stack().
#define EARLY_USE_INPUT_1 1
Definition at line 51 of file BKE_sequencer.h.
Referenced by seq_get_early_out_for_blend_mode(), seq_render_effect_strip_impl(), and seq_render_strip_stack().
#define EARLY_USE_INPUT_2 2
Definition at line 52 of file BKE_sequencer.h.
Referenced by seq_get_early_out_for_blend_mode(), seq_render_effect_strip_impl(), and seq_render_strip_stack().
#define SEQ_BEGIN (ed, _seq)
Value:
{                                                                         \
        SeqIterator iter;                                                     \
        for (seq_begin(ed, &iter, 0); iter.valid; seq_next(&iter)) {          \
            _seq = iter.seq;
Definition at line 75 of file BKE_sequencer.h.
Referenced by bpath_traverse_id(), direct_link_scene(), do_versions(), do_versions_ipos_to_animato(), expand_scene(), lib_link_scene(), seq_free_editing(), sound_update_animation_flags_exec(), unlink_object(), and write_scenes().
#define SEQ_DUPE_ALL (1<<3)
Definition at line 328 of file BKE_sequencer.h.
Referenced by copy_scene(), and seqbase_dupli_recursive().
#define SEQ_DUPE_ANIM (1<<2)
Definition at line 327 of file BKE_sequencer.h.
Referenced by cut_seq_hard(), cut_seq_soft(), and seq_dupli().
#define SEQ_DUPE_CONTEXT (1<<1)
Definition at line 326 of file BKE_sequencer.h.
Referenced by seqbase_dupli_recursive(), and sequencer_add_duplicate_exec().
#define SEQ_DUPE_UNIQUE_NAME (1<<0)
Definition at line 325 of file BKE_sequencer.h.
Referenced by cut_seq_hard(), cut_seq_soft(), seq_dupli(), sequencer_copy_exec(), sequencer_paste_exec(), and sequencer_separate_images_exec().
#define SEQ_END
Value:
}                                                                     \
        seq_end(&iter);                                                       \
    }
Definition at line 81 of file BKE_sequencer.h.
Referenced by bpath_traverse_id(), deselect_all_seq(), direct_link_scene(), do_versions(), do_versions_ipos_to_animato(), expand_scene(), insert_gap(), lib_link_scene(), select_grouped_data(), select_grouped_effect(), select_grouped_effect_link(), select_grouped_time_overlap(), select_grouped_type(), select_grouped_type_basic(), select_grouped_type_effect(), seq_free_editing(), seq_proxy_build_job(), seq_remap_paths(), sequencer_cut_exec(), sequencer_select_grouped_exec(), sequencer_select_invoke(), sound_update_animation_flags_exec(), touch_seq_files(), unlink_object(), and write_scenes().
#define SEQ_LOAD_FRAME_ADVANCE (1<<1)
Definition at line 319 of file BKE_sequencer.h.
Referenced by seq_load_apply(), and seq_load_operator_info().
#define SEQ_LOAD_MOVIE_SOUND (1<<2)
Definition at line 320 of file BKE_sequencer.h.
Referenced by seq_load_operator_info(), and sequencer_add_movie_strip().
#define SEQ_LOAD_REPLACE_SEL (1<<0)
Definition at line 318 of file BKE_sequencer.h.
Referenced by seq_load_apply(), seq_load_operator_info(), sequencer_add_generic_strip_exec(), and sequencer_add_image_strip_exec().
#define SEQ_LOAD_SOUND_CACHE (1<<3)
Definition at line 321 of file BKE_sequencer.h.
Referenced by seq_load_apply(), and seq_load_operator_info().
#define SEQP_BEGIN (ed, _seq)
Value:
{                                                                             \
    SeqIterator iter;                                                         \
        for (seq_begin(ed, &iter, 1); iter.valid; seq_next(&iter)) {          \
            _seq = iter.seq;
Definition at line 69 of file BKE_sequencer.h.
Referenced by deselect_all_seq(), do_versions(), insert_gap(), select_grouped_data(), select_grouped_effect(), select_grouped_effect_link(), select_grouped_time_overlap(), select_grouped_type(), select_grouped_type_basic(), select_grouped_type_effect(), seq_proxy_build_job(), seq_remap_paths(), sequencer_cut_exec(), sequencer_select_grouped_exec(), sequencer_select_invoke(), and touch_seq_files().
Typedef Documentation
typedef struct SeqIterator SeqIterator
typedef struct Sequence*(* SeqLoadFunc)(struct bContext *, ListBase *, struct SeqLoadInfo *)
Definition at line 331 of file BKE_sequencer.h.
typedef struct SeqLoadInfo SeqLoadInfo
typedef struct SeqRenderData SeqRenderData
typedef struct ImBuf*(* SequencerDrawView)(struct Scene *, struct Object *, int, int, unsigned int, int, int, char[256])
Definition at line 342 of file BKE_sequencer.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
DO_SINGLE_WIPE
DO_DOUBLE_WIPE
DO_BOX_WIPE
DO_CROSS_WIPE
DO_IRIS_WIPE
DO_CLOCK_WIPE
Definition at line 104 of file BKE_sequencer.h.
enum seq_stripelem_ibuf_t
Enumerator:
SEQ_STRIPELEM_IBUF
SEQ_STRIPELEM_IBUF_COMP
SEQ_STRIPELEM_IBUF_STARTSTILL
SEQ_STRIPELEM_IBUF_ENDSTILL
Definition at line 214 of file BKE_sequencer.h.
Function Documentation
struct Sequence* alloc_sequence (ListBase * lb, int cfra, int machine) [read]
Definition at line 3718 of file sequencer.c.
References Sequence::blend_opacity, BLI_addtail(), PrefetchQueueElem::cfra, Sequence::flag, ID_SEQ, Sequence::machine, MEM_callocN(), Sequence::mul, Sequence::name, NULL, Sequence::pitch, Sequence::sat, Sequence::scene_sound, SELECT, Sequence::start, and Sequence::volume.
Referenced by sequencer_add_effect_strip_exec(), sequencer_add_image_strip(), sequencer_add_movie_strip(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), and sequencer_meta_make_exec().
void build_seqar_cb (struct ListBase * seqbase, struct Sequence *** seqar, int * totseq, int(*)(struct Sequence *seq) test_func)
void calc_sequence (struct Scene * scene, struct Sequence * seq)
Definition at line 567 of file sequencer.c.
References Sequence::anim_endofs, Sequence::anim_startofs, calc_sequence(), calc_sequence_disp(), Sequence::enddisp, Sequence::endofs, Sequence::endstill, ListBase::first, Sequence::flag, Sequence::len, max, MAX3(), MAXFRAME, min, MIN3, Sequence::next, NULL, Sequence::seq1, Sequence::seq2, Sequence::seq3, SEQ_EFFECT, SEQ_INVALID_EFFECT, SEQ_META, seq_update_sound_bounds_recursive(), Sequence::seqbase, Sequence::start, Sequence::startdisp, Sequence::startofs, Sequence::startstill, and Sequence::type.
Referenced by calc_sequence(), cut_seq_hard(), cut_seq_soft(), flushTransSeq(), freeSeqData(), insert_gap(), reload_sequence_new_file(), sequencer_add_effect_strip_exec(), sequencer_change_path_exec(), sequencer_delete_exec(), sequencer_meta_make_exec(), sequencer_meta_toggle_exec(), sequencer_offset_clear_exec(), sequencer_separate_images_exec(), sequencer_snap_exec(), sequencer_swap_data_exec(), sequencer_swap_exec(), shuffle_seq(), swap_sequence(), and update_changed_seq_recurs().
void calc_sequence_disp (struct Scene * scene, struct Sequence * seq)
Definition at line 544 of file sequencer.c.
References ELEM, Sequence::enddisp, Sequence::endofs, Sequence::endstill, Sequence::handsize, Sequence::len, SEQ_META, SEQ_SCENE, SEQ_SOUND, seq_update_sound_bounds(), seq_update_sound_bounds_recursive(), Sequence::start, Sequence::startdisp, Sequence::startofs, Sequence::startstill, and Sequence::type.
Referenced by calc_sequence(), flushTransSeq(), freeSeqData(), reload_sequence_new_file(), seq_translate(), sequencer_add_image_strip_exec(), sequencer_add_movie_strip(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), and shuffle_seq_time_offset().
void clear_scene_in_allseqs (struct Main * bmain, struct Scene * sce)
Definition at line 795 of file sequencer.c.
References clear_scene_in_allseqs_cb(), Scene::ed, ListBase::first, Scene::id, ID::next, Main::scene, Editing::seqbase, and seqbase_recursive_apply().
Referenced by unlink_scene().
int evaluate_seq_frame (struct Scene * scene, int cfra)
Definition at line 1062 of file sequencer.c.
References evaluate_seq_frame_gen(), FALSE, MAXSEQ, NULL, seq_give_editing(), and Editing::seqbasep.
Referenced by no_gaps().
void free_imbuf_seq (struct Scene * scene, struct ListBase * seqbasep, int check_mem_usage, int keep_file_handles)
Definition at line 2901 of file sequencer.c.
References FALSE, ListBase::first, free_anim_seq(), free_imbuf_seq(), max, MEM_CacheLimiter_get_maximum(), MEM_get_mapped_memory_in_use(), MEM_get_memory_in_use(), mem_in_use, mmap_in_use, Sequence::next, SEQ_META, SEQ_MOVIE, SEQ_SCENE, SEQ_SPEED, seq_stripelem_cache_cleanup(), Sequence::seqbase, sequence_effect_speed_rebuild_map(), Sequence::strip, and Sequence::type.
Referenced by do_render_seq(), free_imbuf_seq(), proxy_endjob(), sequencer_change_effect_input_exec(), sequencer_change_effect_type_exec(), sequencer_change_path_exec(), and sequencer_refresh_all_exec().
struct Sequence* get_seq_by_name (struct ListBase * seqbase, const char * name, int recursive) [read]
Definition at line 3628 of file sequencer.c.
References ListBase::first, get_seq_by_name(), Sequence::name, Sequence::next, NULL, and Sequence::seqbase.
Referenced by animchan_sync_fcurve(), get_seq_by_name(), and skip_fcurve_selected_data().
struct SeqEffectHandle get_sequence_blend (struct Sequence * seq) [read]
Definition at line 3401 of file seqeffects.c.
References Sequence::blend_mode, Sequence::flag, get_sequence_effect_impl(), SeqEffectHandle::load, NULL, and SEQ_EFFECT_NOT_LOADED.
Referenced by seq_get_early_out_for_blend_mode(), and seq_render_strip_stack().
struct SeqEffectHandle get_sequence_effect (struct Sequence * seq) [read]
Definition at line 3386 of file seqeffects.c.
References Sequence::flag, get_sequence_effect_impl(), SeqEffectHandle::load, NULL, SEQ_EFFECT, SEQ_EFFECT_NOT_LOADED, and Sequence::type.
Referenced by change_plugin_seq(), seq_dupli(), seq_free_sequence(), seq_render_effect_strip_impl(), sequence_effect_speed_rebuild_map(), sequencer_add_effect_strip_exec(), sequencer_change_effect_type_exec(), and store_icu_yrange_speed().
int get_sequence_effect_num_inputs (int seq_type)
Definition at line 3416 of file seqeffects.c.
References SeqEffectHandle::execute, get_sequence_effect_impl(), and SeqEffectHandle::num_inputs.
Referenced by draw_seq_handle(), seq_effect_find_selected(), seq_single_check(), seq_swap(), seq_tx_test(), sequencer_add_effect_strip_invoke(), sequencer_change_effect_type_exec(), and sequencer_swap_exec().
void give_ibuf_prefetch_request (SeqRenderData context, float cfra, int chan_shown)
Definition at line 2750 of file sequencer.c.
References BLI_addtail(), PrefetchQueueElem::cfra, PrefetchQueueElem::chanshown, MEM_callocN(), PrefetchQueueElem::monoton_cfra, SeqRenderData::preview_render_size, PrefetchQueueElem::preview_render_size, SeqRenderData::rectx, PrefetchQueueElem::rectx, SeqRenderData::recty, and PrefetchQueueElem::recty.
struct ImBuf* give_ibuf_seq (SeqRenderData context, float cfra, int chanshown) [read]
Definition at line 2517 of file sequencer.c.
References BLI_countlist(), BLI_findlink(), FALSE, MAX2, Editing::metastack, NULL, SeqRenderData::scene, seq_give_editing(), seq_render_strip_stack(), and Editing::seqbasep.
Referenced by do_render_seq(), draw_image_seq(), give_ibuf_seq_threaded(), and screen_opengl_render_apply().
struct ImBuf* give_ibuf_seq_direct (SeqRenderData context, float cfra, struct Sequence * seq) [read]
Definition at line 2543 of file sequencer.c.
References seq_render_strip().
Referenced by draw_image_seq().
struct ImBuf* give_ibuf_seq_threaded (SeqRenderData context, float cfra, int chanshown) [read]
Definition at line 2805 of file sequencer.c.
References PrefetchQueueElem::cfra, PrefetchQueueElem::chanshown, PrefetchThread::current, FALSE, ListBase::first, give_ibuf_seq(), PrefetchQueueElem::ibuf, PrefetchQueueElem::monoton_cfra, PrefetchThread::next, PrefetchQueueElem::next, NULL, PrefetchQueueElem::preview_render_size, SeqRenderData::preview_render_size, PrefetchQueueElem::rectx, SeqRenderData::rectx, PrefetchQueueElem::recty, SeqRenderData::recty, and TRUE.
Referenced by draw_image_seq().
struct ImBuf* give_ibuf_seqbase (SeqRenderData context, float cfra, int chan_shown, struct ListBase * seqbasep) [read]
Definition at line 2537 of file sequencer.c.
References seq_render_strip_stack().
Referenced by do_adjustment_impl(), and do_multicam().
const char* give_seqname (struct Sequence * seq)
Definition at line 899 of file sequencer.c.
References Strip::dir, PluginSeq::doit, Sequence::flag, give_seqname_by_type(), Sequence::plugin, PluginSeq::pname, SEQ_EFFECT, SEQ_EFFECT_NOT_LOADED, SEQ_PLUGIN, Sequence::strip, and Sequence::type.
Referenced by draw_seq_text(), and sequencer_add_effect_strip_exec().
struct StripElem* give_stripelem (struct Sequence * seq, int cfra) [read]
Definition at line 1025 of file sequencer.c.
References Sequence::anim_startofs, give_stripelem_index(), NULL, SEQ_IMAGE, Sequence::strip, Strip::stripdata, and Sequence::type.
Referenced by seq_proxy_get_fname(), seq_render_strip(), sequencer_rendersize_exec(), and sequencer_separate_images_exec().
int input_have_to_preprocess (SeqRenderData context, struct Sequence * seq, float cfra)
Referenced by do_adjustment(), do_multicam(), seq_render_effect_strip_impl(), and seq_render_strip().
void printf_strip (struct Sequence * seq)
Definition at line 98 of file sequencer.c.
References Sequence::enddisp, Sequence::endofs, Sequence::endstill, Sequence::len, Sequence::machine, Sequence::name, seq_tx_get_final_left(), seq_tx_get_final_right(), Sequence::start, Sequence::startdisp, Sequence::startofs, and Sequence::startstill.
void reload_sequence_new_file (struct Scene * scene, struct Sequence * seq, int lock_range)
Definition at line 641 of file sequencer.c.
References Sequence::anim, Sequence::anim_endofs, Sequence::anim_preseek, Sequence::anim_startofs, AUD_getInfo(), BKE_movieclip_get_duration(), BLI_join_dirfile(), BLI_path_abs(), calc_sequence(), calc_sequence_disp(), Sequence::clip, Strip::dir, RenderData::efra, ELEM6, Sequence::enddisp, FILE_MAX, Sequence::flag, FPS, free_proxy_seq(), G, IB_animdeinterlace, IB_rect, if(), IMB_anim_get_duration(), IMB_anim_get_preseek(), IMB_free_anim(), IMB_TC_RECORD_RUN, Sequence::len, AUD_SoundInfo::length, MEM_allocN_len(), StripElem::name, openanim(), bSound::playback_handle, Strip::proxy, Scene::r, Sequence::scene, SEQ_FILTERY, SEQ_IMAGE, SEQ_META, SEQ_MOVIE, SEQ_MOVIECLIP, SEQ_SCENE, seq_single_fix(), SEQ_SOUND, seq_tx_set_final_left(), seq_tx_set_final_right(), RenderData::sfra, Sequence::sound, Sequence::startdisp, str, Sequence::streamindex, Sequence::strip, Strip::stripdata, StripProxy::tc, and Sequence::type.
Referenced by cut_seq_hard(), sequencer_change_path_exec(), and sequencer_reload_exec().
struct Sequence* seq_active_get (struct Scene * scene) [read]
Definition at line 3645 of file sequencer.c.
References Editing::act_seq, FALSE, NULL, and seq_give_editing().
Referenced by change_plugin_seq(), draw_seq_strips(), recurs_del_seq_flag(), seq_active_pair_get(), seq_effect_find_selected(), seq_remap_paths(), seqbase_dupli_recursive(), sequencer_change_effect_input_exec(), sequencer_change_effect_type_exec(), sequencer_change_path_exec(), sequencer_change_path_invoke(), sequencer_delete_exec(), sequencer_effect_poll(), sequencer_generic_invoke_path__internal(), sequencer_meta_make_exec(), sequencer_meta_separate_exec(), sequencer_meta_toggle_exec(), sequencer_reassign_inputs_exec(), sequencer_rendersize_exec(), sequencer_select_active_side_exec(), sequencer_select_grouped_exec(), sequencer_swap_exec(), and sequencer_swap_inputs_exec().
int seq_active_pair_get (struct Scene * scene, struct Sequence ** seq_act, struct Sequence ** seq_other)
Definition at line 3660 of file sequencer.c.
References FALSE, ListBase::first, Sequence::flag, Sequence::next, NULL, SELECT, seq_active_get(), seq_give_editing(), and Editing::seqbasep.
Referenced by sequencer_swap_data_exec().
void seq_active_set (struct Scene * scene, struct Sequence * seq)
Definition at line 3652 of file sequencer.c.
References Editing::act_seq, FALSE, NULL, and seq_give_editing().
Referenced by recurs_del_seq_flag(), select_single_seq(), seq_load_apply(), seqbase_dupli_recursive(), sequencer_add_effect_strip_exec(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_meta_make_exec(), sequencer_meta_toggle_exec(), and sequencer_select_invoke().
void seq_array (struct Editing * ed, struct Sequence *** seqarray, int * tot, int use_pointer)
Definition at line 398 of file sequencer.c.
References MEM_mallocN(), NULL, seq_build_array(), seq_count(), Editing::seqbase, and Editing::seqbasep.
Referenced by seq_begin().
void seq_begin (struct Editing * ed, SeqIterator * iter, int use_pointer)
Definition at line 423 of file sequencer.c.
References SeqIterator::array, SeqIterator::cur, SeqIterator::seq, seq_array(), SeqIterator::tot, and SeqIterator::valid.
Referenced by select_grouped_effect_link().
int seq_cmp_render_data (const SeqRenderData * a, const SeqRenderData * b)
Definition at line 297 of file sequencer.c.
References SeqRenderData::bmain, SeqRenderData::motion_blur_samples, SeqRenderData::motion_blur_shutter, SeqRenderData::preview_render_size, SeqRenderData::rectx, SeqRenderData::recty, and SeqRenderData::scene.
Referenced by seqcache_hashcmp().
void seq_dupe_animdata (struct Scene * scene, const char * name_src, const char * name_dst)
Definition at line 3570 of file sequencer.c.
References AnimData::action, Scene::adt, BKE_animdata_fix_paths_rename(), BLI_addtail(), BLI_movelisttolist(), BLI_snprintf(), copy_fcurve(), bAction::curves, ListBase::first, Scene::id, ListBase::last, FCurve::next, NULL, FCurve::prev, FCurve::rna_path, and SEQ_NAME_MAXSTR.
Referenced by apply_unique_name_cb(), and seq_dupli().
struct Sequence* seq_dupli_recursive (struct Scene * scene, struct Scene * scene_to, struct Sequence * seq, int dupe_flag) [read]
Definition at line 3982 of file sequencer.c.
References BLI_addtail(), ListBase::first, Sequence::next, seq_dupli(), seq_dupli_recursive(), SEQ_META, Sequence::seqbase, and Sequence::type.
Referenced by cut_seq_hard(), cut_seq_soft(), seq_dupli_recursive(), seq_proxy_rebuild_context(), and sequencer_separate_images_exec().
void seq_end (SeqIterator * iter)
Definition at line 443 of file sequencer.c.
References SeqIterator::array, MEM_freeN(), and SeqIterator::valid.
Referenced by select_grouped_effect_link().
struct Sequence* seq_foreground_frame_get (struct Scene * scene, int frame) [read]
Definition at line 3237 of file sequencer.c.
References ELEM5, Sequence::enddisp, FALSE, ListBase::first, Sequence::flag, Sequence::machine, Sequence::next, NULL, SEQ_COLOR, seq_give_editing(), SEQ_IMAGE, SEQ_META, SEQ_MOVIE, SEQ_MUTE, SEQ_SCENE, Editing::seqbasep, Sequence::startdisp, and Sequence::type.
Referenced by stampdata().
void seq_free_clipboard (void)
Definition at line 242 of file sequencer.c.
References ListBase::first, ListBase::last, Sequence::next, NULL, and seq_free_clipboard_recursive().
Referenced by sequencer_copy_exec(), and WM_exit_ext().
void seq_free_editing (struct Scene * scene)
Definition at line 253 of file sequencer.c.
References BLI_remlink(), Scene::ed, ListBase::first, MEM_freeN(), Editing::metastack, NULL, SEQ_BEGIN, SEQ_END, and seq_free_sequence().
Referenced by free_scene().
void seq_free_sequence (struct Scene * scene, struct Sequence * seq)
Definition at line 175 of file sequencer.c.
References Editing::act_seq, Sequence::anim, Scene::ed, ELEM, SeqEffectHandle::free, get_sequence_effect(), IMB_free_anim(), MEM_freeN(), NULL, Sequence::scene_sound, SEQ_EFFECT, seq_free_animdata(), seq_free_strip(), SEQ_SCENE, SEQ_SOUND, Sequence::sound, sound_remove_scene_sound(), Sequence::strip, and Sequence::type.
Referenced by recurs_del_seq_flag(), seq_free_clipboard_recursive(), seq_free_editing(), seq_free_sequence_recurse(), sequencer_add_effect_strip_exec(), sequencer_meta_separate_exec(), and sequencer_separate_images_exec().
void seq_free_sequence_recurse (struct Scene * scene, struct Sequence * seq)
Definition at line 207 of file sequencer.c.
References ListBase::first, Sequence::next, seq_free_sequence(), seq_free_sequence_recurse(), and Sequence::seqbase.
Referenced by seq_free_sequence_recurse(), and seq_proxy_rebuild_finish().
void seq_free_strip (struct Strip * strip)
Definition at line 142 of file sequencer.c.
References StripProxy::anim, Strip::color_balance, Strip::crop, IMB_free_anim(), MEM_freeN(), Strip::proxy, Strip::stripdata, Strip::transform, and Strip::us.
Referenced by seq_free_sequence().
struct Editing* seq_give_editing (struct Scene * scene, int alloc) [read]
Definition at line 219 of file sequencer.c.
References Scene::ed, MEM_callocN(), NULL, Editing::seqbase, and Editing::seqbasep.
Referenced by animchan_sync_fcurve(), boundbox_seq(), change_plugin_seq(), createTransSeqData(), deselect_all_seq(), draw_timeline_seq(), ed_screen_context(), evaluate_seq_frame(), find_nearest_seq(), find_neighboring_sequence(), find_next_prev_edit(), find_next_prev_sequence(), flushTransSeq(), freeSeqData(), give_ibuf_seq(), insert_gap(), no_gaps(), outliner_build_tree(), proxy_endjob(), select_more_less_seq__internal(), select_single_seq(), seq_active_get(), seq_active_pair_get(), seq_active_set(), seq_effect_find_selected(), seq_foreground_frame_get(), seq_proxy_build_job(), seq_remap_paths(), sequencer_add_duplicate_exec(), sequencer_add_effect_strip_exec(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_borderselect_exec(), sequencer_change_effect_input_exec(), sequencer_change_effect_type_exec(), sequencer_change_path_exec(), sequencer_copy_exec(), sequencer_cut_exec(), sequencer_de_select_all_exec(), sequencer_delete_exec(), sequencer_edit_poll(), sequencer_effect_poll(), sequencer_lock_exec(), sequencer_meta_make_exec(), sequencer_meta_separate_exec(), sequencer_meta_toggle_exec(), sequencer_mute_exec(), sequencer_offset_clear_exec(), sequencer_paste_exec(), sequencer_refresh_all_exec(), sequencer_reload_exec(), sequencer_select_active_side_exec(), sequencer_select_grouped_exec(), sequencer_select_handles_exec(), sequencer_select_inverse_exec(), sequencer_select_invoke(), sequencer_separate_images_exec(), sequencer_snap_exec(), sequencer_strip_has_path_poll(), sequencer_swap_exec(), sequencer_unlock_exec(), sequencer_unmute_exec(), sequencer_view_poll(), sequencer_view_selected_exec(), skip_fcurve_selected_data(), sort_seq(), touch_seq_files(), tree_element_active_sequence_dup(), update_changed_seq_and_deps(), and view_ghost_border_exec().
unsigned int seq_hash_render_data (const SeqRenderData * a)
Definition at line 351 of file sequencer.c.
References SeqRenderData::bmain, SeqRenderData::motion_blur_samples, SeqRenderData::motion_blur_shutter, SeqRenderData::preview_render_size, SeqRenderData::rectx, SeqRenderData::recty, and SeqRenderData::scene.
Referenced by seqcache_hashhash().
void seq_load_apply (struct Scene * scene, struct Sequence * seq, struct SeqLoadInfo * seq_load)
Definition at line 3691 of file sequencer.c.
References BLI_strncpy(), Scene::ed, Sequence::enddisp, SeqLoadInfo::flag, SeqLoadInfo::name, Sequence::name, SELECT, seq_active_set(), SEQ_LOAD_FRAME_ADVANCE, SEQ_LOAD_REPLACE_SEL, SEQ_LOAD_SOUND_CACHE, Editing::seqbase, seqbase_unique_name_recursive(), Sequence::sound, sound_cache(), SeqLoadInfo::start_frame, Sequence::startdisp, SeqLoadInfo::tot_error, and SeqLoadInfo::tot_success.
Referenced by sequencer_add_image_strip(), and sequencer_add_movie_strip().
struct Sequence* seq_metastrip (ListBase * seqbase, struct Sequence * meta, struct Sequence * seq) [read]
Definition at line 3471 of file sequencer.c.
References ListBase::first, Sequence::next, NULL, seq_metastrip(), and Sequence::seqbase.
Referenced by do_adjustment_impl(), and seq_metastrip().
SeqRenderData seq_new_render_data (struct Main * bmain, struct Scene * scene, int rectx, int recty, int preview_render_size)
Definition at line 280 of file sequencer.c.
References SeqRenderData::bmain, SeqRenderData::motion_blur_samples, SeqRenderData::motion_blur_shutter, preview_render_size(), SeqRenderData::preview_render_size, SeqRenderData::rectx, SeqRenderData::recty, and SeqRenderData::scene.
Referenced by do_render_seq(), draw_image_seq(), screen_opengl_render_apply(), and seq_proxy_rebuild().
void seq_next (SeqIterator * iter)
Definition at line 435 of file sequencer.c.
References SeqIterator::array, SeqIterator::cur, SeqIterator::seq, SeqIterator::tot, and SeqIterator::valid.
Referenced by select_grouped_effect_link().
void seq_offset_animdata (struct Scene * scene, struct Sequence * seq, int ofs)
Definition at line 3547 of file sequencer.c.
References AnimData::action, Scene::adt, FCurve::bezt, BLI_snprintf(), bAction::curves, ListBase::first, i, Sequence::name, FCurve::next, NULL, FCurve::rna_path, SEQ_NAME_MAXSTR, str, FCurve::totvert, and BezTriple::vec.
Referenced by flushTransSeq(), and seq_translate().
void seq_proxy_rebuild (struct SeqIndexBuildContext * context, short * stop, short * do_update, float * progress)
Definition at line 1393 of file sequencer.c.
References SeqIndexBuildContext::bmain, Sequence::enddisp, Sequence::endstill, Sequence::flag, G, IMB_anim_index_rebuild(), IMB_PROXY_100, IMB_PROXY_25, IMB_PROXY_50, IMB_PROXY_75, SeqIndexBuildContext::index_context, Scene::r, SeqIndexBuildContext::scene, SeqIndexBuildContext::seq, SEQ_MOVIE, seq_new_render_data(), seq_proxy_build_frame(), SEQ_USE_PROXY, SEQ_USE_PROXY_CUSTOM_FILE, RenderData::size, SeqIndexBuildContext::size_flags, Sequence::startdisp, Sequence::startstill, Sequence::type, RenderData::xsch, and RenderData::ysch.
Referenced by proxy_startjob().
struct SeqIndexBuildContext* seq_proxy_rebuild_context (struct Main * bmain, struct Scene * scene, struct Sequence * seq) [read]
Definition at line 1355 of file sequencer.c.
References Sequence::anim, SeqIndexBuildContext::bmain, StripProxy::build_size_flags, StripProxy::build_tc_flags, Sequence::flag, IMB_anim_index_rebuild_context(), SeqIndexBuildContext::index_context, MEM_callocN(), NULL, SeqIndexBuildContext::orig_seq, Strip::proxy, StripProxy::quality, SeqIndexBuildContext::quality, SeqIndexBuildContext::scene, SeqIndexBuildContext::seq, seq_dupli_recursive(), SEQ_MOVIE, seq_open_anim_file(), SEQ_USE_PROXY, SeqIndexBuildContext::size_flags, Sequence::strip, SeqIndexBuildContext::tc_flags, and Sequence::type.
Referenced by seq_proxy_build_job().
void seq_proxy_rebuild_finish (struct SeqIndexBuildContext * context, short stop)
Definition at line 1449 of file sequencer.c.
References Sequence::anim, IMB_anim_index_rebuild_finish(), IMB_close_anim_proxies(), SeqIndexBuildContext::index_context, MEM_freeN(), SeqIndexBuildContext::orig_seq, SeqIndexBuildContext::scene, SeqIndexBuildContext::seq, and seq_free_sequence_recurse().
Referenced by proxy_endjob().
int seq_recursive_apply (struct Sequence * seq, int(*)(struct Sequence *, void *) apply_func, void * arg)
Referenced by seqbase_recursive_apply(), sequencer_add_duplicate_exec(), sequencer_copy_exec(), and sequencer_paste_exec().
struct ListBase* seq_seqbase (struct ListBase * seqbase, struct Sequence * seq) [read]
Definition at line 3454 of file sequencer.c.
References ListBase::first, Sequence::next, NULL, seq_seqbase(), and Sequence::seqbase.
Referenced by do_adjustment_impl(), do_multicam(), and seq_seqbase().
int seq_single_check (struct Sequence * seq)
Definition at line 3068 of file sequencer.c.
References get_sequence_effect_num_inputs(), Sequence::len, SEQ_EFFECT, SEQ_IMAGE, and Sequence::type.
Referenced by draw_seq_strip(), seq_single_fix(), and seq_tx_handle_xlimits().
void seq_single_fix (struct Sequence * seq)
Definition at line 3160 of file sequencer.c.
References left(), seq_single_check(), seq_tx_get_final_left(), seq_tx_get_final_right(), seq_tx_set_final_left(), seq_tx_set_final_right(), and Sequence::start.
Referenced by flushTransSeq(), and reload_sequence_new_file().
void seq_sound_init (struct Scene * scene, struct Sequence * seq)
Definition at line 3219 of file sequencer.c.
References ListBase::first, Sequence::next, Sequence::scene, Sequence::scene_sound, SEQ_META, seq_sound_init(), Sequence::seqbase, Sequence::sound, sound_add_scene_sound_defaults(), sound_scene_add_scene_sound_defaults(), and Sequence::type.
Referenced by seq_sound_init(), and sequencer_paste_exec().
void seq_stripelem_cache_cleanup (void)
Definition at line 98 of file seqcache.c.
References IMB_moviecache_create(), IMB_moviecache_free(), NULL, seqcache_hashcmp(), and seqcache_hashhash().
Referenced by free_imbuf_seq(), screen_render_exec(), and screen_render_invoke().
void seq_stripelem_cache_destruct (void)
Definition at line 92 of file seqcache.c.
References IMB_moviecache_free().
Referenced by free_blender().
struct ImBuf* seq_stripelem_cache_get (SeqRenderData context, struct Sequence * seq, float cfra, seq_stripelem_ibuf_t type) [read]
Definition at line 107 of file seqcache.c.
References seqCacheKey::cfra, seqCacheKey::context, IMB_moviecache_get(), NULL, seqCacheKey::seq, Sequence::start, and seqCacheKey::type.
Referenced by copy_from_ibuf_still(), seq_render_strip(), and seq_render_strip_stack().
void seq_stripelem_cache_put (SeqRenderData context, struct Sequence * seq, float cfra, seq_stripelem_ibuf_t type, struct ImBuf * nval)
Definition at line 126 of file seqcache.c.
References seqCacheKey::cfra, seqCacheKey::context, IMB_moviecache_create(), IMB_moviecache_put(), NULL, seqCacheKey::seq, seqcache_hashcmp(), seqcache_hashhash(), Sequence::start, and seqCacheKey::type.
Referenced by copy_to_ibuf_still(), seq_render_strip(), and seq_render_strip_stack().
int seq_swap (struct Sequence * seq_a, struct Sequence * seq_b, const char ** error_str)
Definition at line 3490 of file sequencer.c.
References Sequence::blend_mode, Sequence::blend_opacity, BLI_strncpy(), Sequence::enddisp, Sequence::endofs, Sequence::endstill, get_sequence_effect_num_inputs(), Sequence::len, Sequence::machine, Sequence::name, Sequence::next, Sequence::prev, SEQ_EFFECT, SEQ_SOUND, Sequence::start, Sequence::startdisp, Sequence::startofs, Sequence::startstill, SWAP, and Sequence::type.
Referenced by sequencer_swap_data_exec().
int seq_test_overlap (struct ListBase * seqbasep, struct Sequence * test)
Definition at line 3189 of file sequencer.c.
References ListBase::first, Sequence::next, and seq_overlap().
Referenced by change_plugin_seq(), flushTransSeq(), freeSeqData(), sequencer_add_effect_strip_exec(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_meta_make_exec(), sequencer_meta_separate_exec(), sequencer_offset_clear_exec(), sequencer_reload_exec(), sequencer_separate_images_exec(), sequencer_snap_exec(), sequencer_swap_exec(), and shuffle_seq().
void seq_translate (struct Scene * scene, struct Sequence * seq, int delta)
Definition at line 3204 of file sequencer.c.
References calc_sequence_disp(), ListBase::first, Sequence::next, SEQ_META, seq_offset_animdata(), seq_translate(), Sequence::seqbase, Sequence::start, and Sequence::type.
Referenced by seq_translate(), sequencer_paste_exec(), sequencer_snap_exec(), shuffle_seq(), and shuffle_seq_time().
int seq_tx_get_end (struct Sequence * seq)
Definition at line 3015 of file sequencer.c.
References Sequence::len, and Sequence::start.
Referenced by seq_tx_handle_xlimits().
int seq_tx_get_final_left (struct Sequence * seq, int metaclip)
Definition at line 3020 of file sequencer.c.
References MAX2, seq_tx_get_final_left(), Sequence::start, Sequence::startofs, Sequence::startstill, and Sequence::tmp.
Referenced by draw_seq_strip(), printf_strip(), seq_single_fix(), seq_tx_get_final_left(), seq_tx_handle_xlimits(), SeqToTransData(), SeqTransInfo(), and sequencer_separate_images_exec().
int seq_tx_get_final_right (struct Sequence * seq, int metaclip)
Definition at line 3031 of file sequencer.c.
References Sequence::endofs, Sequence::endstill, Sequence::len, MIN2, seq_tx_get_final_right(), Sequence::start, and Sequence::tmp.
Referenced by draw_seq_strip(), printf_strip(), seq_single_fix(), seq_tx_get_final_right(), seq_tx_handle_xlimits(), SeqToTransData(), SeqTransInfo(), and sequencer_separate_images_exec().
int seq_tx_get_start (struct Sequence * seq)
Definition at line 3011 of file sequencer.c.
References Sequence::start.
Referenced by seq_tx_handle_xlimits().
void seq_tx_handle_xlimits (struct Sequence * seq, int leftflag, int rightflag)
Definition at line 3117 of file sequencer.c.
References Sequence::endstill, seq_single_check(), SEQ_SOUND, seq_tx_get_end(), seq_tx_get_final_left(), seq_tx_get_final_right(), seq_tx_get_start(), seq_tx_set_final_left(), seq_tx_set_final_right(), Sequence::start, Sequence::startstill, and Sequence::type.
Referenced by flushTransSeq(), and sequencer_snap_exec().
void seq_tx_set_final_left (struct Sequence * seq, int val)
Definition at line 3042 of file sequencer.c.
References abs(), Sequence::startofs, and Sequence::startstill.
Referenced by flushTransSeq(), reload_sequence_new_file(), seq_single_fix(), seq_tx_handle_xlimits(), and sequencer_snap_exec().
void seq_tx_set_final_right (struct Sequence * seq, int val)
Definition at line 3054 of file sequencer.c.
References abs(), Sequence::endofs, Sequence::endstill, len(), and Sequence::start.
Referenced by flushTransSeq(), reload_sequence_new_file(), seq_single_fix(), seq_tx_handle_xlimits(), sequencer_add_effect_strip_exec(), and sequencer_snap_exec().
int seq_tx_test (struct Sequence * seq)
Definition at line 3178 of file sequencer.c.
References get_sequence_effect_num_inputs(), SEQ_EFFECT, and Sequence::type.
Referenced by find_nearest_seq(), flushTransSeq(), and sequencer_snap_exec().
void seq_update_muting (struct Editing * ed)
Definition at line 3417 of file sequencer.c.
References ListBase::last, Editing::metastack, NULL, MetaStack::parseq, seq_update_muting_recursive(), and Editing::seqbase.
Referenced by lib_link_scene(), sequencer_add_generic_strip_exec(), sequencer_meta_make_exec(), sequencer_meta_separate_exec(), sequencer_meta_toggle_exec(), sequencer_mute_exec(), and sequencer_unmute_exec().
void seq_update_sound (struct Scene * scene, struct bSound * sound)
Definition at line 3446 of file sequencer.c.
References Scene::ed, seq_update_sound_recursive(), and Editing::seqbase.
void seq_update_sound_bounds (struct Scene * scene, struct Sequence * seq)
Definition at line 3385 of file sequencer.c.
References sound_move_scene_sound_defaults().
Referenced by calc_sequence_disp(), and seq_update_sound_bounds_all().
void seq_update_sound_bounds_all (struct Scene * scene)
Definition at line 3367 of file sequencer.c.
References Scene::ed, ELEM, ListBase::first, Sequence::next, SEQ_META, SEQ_SCENE, SEQ_SOUND, seq_update_sound_bounds(), seq_update_sound_bounds_recursive(), Editing::seqbase, and Sequence::type.
Referenced by lib_link_scene().
void seqbase_dupli_recursive (struct Scene * scene, struct Scene * scene_to, ListBase * nseqbase, ListBase * seqbase, int dupe_flag)
Definition at line 3997 of file sequencer.c.
References BLI_addtail(), ListBase::first, Sequence::flag, Sequence::next, NULL, SELECT, seq_active_get(), seq_active_set(), SEQ_ALLSEL, SEQ_DUPE_ALL, SEQ_DUPE_CONTEXT, seq_dupli(), SEQ_LEFTSEL, SEQ_LOCK, SEQ_META, SEQ_RIGHTSEL, Sequence::seqbase, seqbase_dupli_recursive(), Sequence::tmp, and Sequence::type.
Referenced by copy_scene(), seqbase_dupli_recursive(), sequencer_add_duplicate_exec(), sequencer_copy_exec(), and sequencer_paste_exec().
int seqbase_isolated_sel_check (struct ListBase * seqbase)
Definition at line 3077 of file sequencer.c.
References FALSE, ListBase::first, Sequence::flag, Sequence::next, SELECT, Sequence::seq1, Sequence::seq2, Sequence::seq3, SEQ_EFFECT, TRUE, and Sequence::type.
Referenced by sequencer_copy_exec(), and sequencer_meta_make_exec().
int seqbase_recursive_apply (struct ListBase * seqbase, int(*)(struct Sequence *seq, void *) apply_func, void * arg)
Referenced by clear_scene_in_allseqs(), lib_link_clipboard_restore(), seq_recursive_apply(), and seqbase_unique_name_recursive().
void seqbase_unique_name_recursive (ListBase * seqbasep, struct Sequence * seq)
Definition at line 841 of file sequencer.c.
References BLI_strncpy(), SeqUniqueInfo::count, dot(), SeqUniqueInfo::match, Sequence::name, SeqUniqueInfo::name_dest, SeqUniqueInfo::name_src, SeqUniqueInfo::seq, seqbase_recursive_apply(), seqbase_unique_name(), and seqbase_unique_name_recursive_cb().
Referenced by apply_unique_name_cb(), do_versions_seq_unique_name_all_strips(), seq_dupli(), seq_load_apply(), sequencer_add_effect_strip_exec(), sequencer_add_movie_strip(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), and sequencer_meta_make_exec().
void sequence_effect_speed_rebuild_map (struct Scene * scene, struct Sequence * seq, int force)
Definition at line 3039 of file seqeffects.c.
References Sequence::effectdata, Sequence::enddisp, evaluate_fcurve(), FALSE, Sequence::flag, SpeedControlVars::flags, ImBuf::flags, SpeedControlVars::frameMap, get_sequence_effect(), SpeedControlVars::globalSpeed, Scene::id, id_data_find_fcurve(), SpeedControlVars::lastValidFrame, Sequence::len, SpeedControlVars::length, MEM_callocN(), MEM_freeN(), NULL, RNA_Sequence, Sequence::seq1, SEQ_SPEED_COMPRESS_IPO_Y, SEQ_SPEED_INTEGRATE, SEQ_USE_EFFECT_DEFAULT_FADE, Sequence::speed_fader, Sequence::start, and Sequence::startdisp.
Referenced by free_imbuf_seq(), seq_render_strip(), and update_changed_seq_recurs().
struct Sequence* sequencer_add_image_strip (struct bContext * C, ListBase * seqbasep, struct SeqLoadInfo * seq_load) [read]
Definition at line 3742 of file sequencer.c.
References alloc_sequence(), Sequence::blend_mode, BLI_strncpy(), SeqLoadInfo::channel, CTX_data_scene(), Strip::dir, SeqLoadInfo::len, Sequence::len, MEM_callocN(), SeqLoadInfo::path, SEQ_CROSS, SEQ_IMAGE, seq_load_apply(), SeqLoadInfo::start_frame, Sequence::strip, Strip::stripdata, Sequence::type, and Strip::us.
Referenced by sequencer_add_image_strip_exec().
struct Sequence* sequencer_add_movie_strip (struct bContext * C, ListBase * seqbasep, struct SeqLoadInfo * seq_load) [read]
Definition at line 3834 of file sequencer.c.
References alloc_sequence(), BLI_path_abs(), BLI_split_dirfile(), BLI_strncpy(), calc_sequence_disp(), SeqLoadInfo::channel, CTX_data_scene(), Strip::dir, Scene::ed, SeqLoadInfo::flag, G, IB_rect, IMB_anim_get_duration(), IMB_anim_get_preseek(), IMB_TC_RECORD_RUN, MEM_callocN(), SeqLoadInfo::name, StripElem::name, NULL, openanim(), SeqLoadInfo::path, SEQ_CROSS, seq_load_apply(), SEQ_LOAD_MOVIE_SOUND, SEQ_MOVIE, SEQ_NAME_MAXSTR, Editing::seqbase, seqbase_unique_name_recursive(), sequencer_add_sound_strip(), SeqLoadInfo::start_frame, Strip::stripdata, and Strip::us.
Referenced by sequencer_add_movie_strip_exec().
struct Sequence* sequencer_add_sound_strip (struct bContext * C, ListBase * seqbasep, struct SeqLoadInfo * seq_load) [read]
Definition at line 3825 of file sequencer.c.
References NULL.
Referenced by sequencer_add_movie_strip(), and sequencer_add_sound_strip_exec().
int shuffle_seq (struct ListBase * seqbasep, struct Sequence * test, struct Scene * evil_scene)
Definition at line 3260 of file sequencer.c.
References calc_sequence(), Sequence::enddisp, ListBase::first, Sequence::machine, MAX2, MAXSEQ, Sequence::next, seq_test_overlap(), seq_translate(), Sequence::start, and Sequence::startdisp.
Referenced by change_plugin_seq(), freeSeqData(), sequencer_add_effect_strip_exec(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_meta_make_exec(), sequencer_meta_separate_exec(), sequencer_offset_clear_exec(), sequencer_reload_exec(), sequencer_separate_images_exec(), sequencer_snap_exec(), and sequencer_swap_exec().
int shuffle_seq_time (ListBase * seqbasep, struct Scene * evil_scene)
Definition at line 3345 of file sequencer.c.
References ListBase::first, Sequence::flag, Sequence::next, SEQ_OVERLAP, seq_translate(), shuffle_seq_time_offset(), and Sequence::tmp.
Referenced by freeSeqData().
void sort_seq (struct Scene * scene)
Definition at line 743 of file sequencer.c.
References BLI_addtail(), BLI_insertlinkbefore(), BLI_movelisttolist(), BLI_remlink(), FALSE, ListBase::first, ListBase::last, Sequence::machine, Sequence::next, NULL, SEQ_EFFECT, seq_give_editing(), Editing::seqbasep, and Sequence::type.
Referenced by freeSeqData(), sequencer_add_effect_strip_exec(), sequencer_add_generic_strip_exec(), sequencer_add_image_strip_exec(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_cut_exec(), sequencer_meta_separate_exec(), sequencer_separate_images_exec(), sequencer_snap_exec(), and sequencer_swap_exec().
void update_changed_seq_and_deps (struct Scene * scene, struct Sequence * changed_seq, int len_change, int ibuf_change)
Definition at line 2994 of file sequencer.c.
References FALSE, ListBase::first, Sequence::next, NULL, seq_give_editing(), Editing::seqbase, and update_changed_seq_recurs().
Referenced by del_seq_find_replace_recurs(), sequencer_add_effect_strip_exec(), sequencer_change_effect_input_exec(), sequencer_change_effect_type_exec(), sequencer_reassign_inputs_exec(), sequencer_reload_exec(), and sequencer_swap_inputs_exec().
Variable Documentation
ListBase seqbase_clipboard
Definition at line 93 of file sequencer.c.
Referenced by lib_link_clipboard_restore(), sequencer_copy_exec(), and sequencer_paste_exec().
int seqbase_clipboard_frame
Definition at line 94 of file sequencer.c.
Referenced by sequencer_copy_exec(), and sequencer_paste_exec().
SequencerDrawView sequencer_view3d_cb
Definition at line 95 of file sequencer.c.
Referenced by ED_spacetype_sequencer(), and seq_render_scene_strip().