Blender: ImageViewport.h File Reference
ImageViewport.h File Reference
BGE Video Texture
#include "Common.h"
#include "ImageBase.h"
Classes
class ImageViewport
class for viewport access
Functions
PyObject * ImageViewport_getCaptureSize (PyImage *self, void *closure)
int ImageViewport_setCaptureSize (PyImage *self, PyObject *value, void *closure)
PyObject * ImageViewport_getWhole (PyImage *self, void *closure)
int ImageViewport_setWhole (PyImage *self, PyObject *value, void *closure)
PyObject * ImageViewport_getAlpha (PyImage *self, void *closure)
int ImageViewport_setAlpha (PyImage *self, PyObject *value, void *closure)
Detailed Description
Definition in file ImageViewport.h.
Function Documentation
PyObject* ImageViewport_getAlpha (PyImage * self, void * closure)
Definition at line 206 of file ImageViewport.cpp.
References getImageViewport(), and NULL.
PyObject* ImageViewport_getCaptureSize (PyImage * self, void * closure)
Definition at line 257 of file ImageViewport.cpp.
References getImageViewport().
PyObject* ImageViewport_getWhole (PyImage * self, void * closure)
Definition at line 176 of file ImageViewport.cpp.
References getImageViewport(), and NULL.
int ImageViewport_setAlpha (PyImage * self, PyObject * value, void * closure)
Definition at line 213 of file ImageViewport.cpp.
References getImageViewport(), NULL, and ImageViewport::setAlpha().
int ImageViewport_setCaptureSize (PyImage * self, PyObject * value, void * closure)
Definition at line 264 of file ImageViewport.cpp.
References KDL::exp(), getImageViewport(), NULL, Exception::report(), ImageViewport::setCaptureSize(), and size().
int ImageViewport_setWhole (PyImage * self, PyObject * value, void * closure)
Definition at line 183 of file ImageViewport.cpp.
References KDL::exp(), getImageViewport(), NULL, Exception::report(), and ImageViewport::setWhole().