Blender: btSoftClusterCollisionShape Class Reference
btSoftClusterCollisionShape Class Reference
#include <btSoftBodyInternals.h>
Public Member Functions
btSoftClusterCollisionShape (const btSoftBody::Cluster *cluster)
virtual btVector3 localGetSupportingVertex (const btVector3 &vec) const
virtual btVector3 localGetSupportingVertexWithoutMargin (const btVector3 &vec) const
virtual void batchedUnitVectorGetSupportingVertexWithoutMargin (const btVector3 *vectors, btVector3 *supportVerticesOut, int numVectors) const
virtual void calculateLocalInertia (btScalar mass, btVector3 &inertia) const
virtual void getAabb (const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const
getAabb's default implementation is brute force, expected derived classes to implement a fast dedicated version
virtual int getShapeType () const
virtual const char * getName () const
virtual void setMargin (btScalar margin)
virtual btScalar getMargin () const
Public Attributes
const btSoftBody::Cluster * m_cluster
Detailed Description
Definition at line 117 of file btSoftBodyInternals.h.
Constructor & Destructor Documentation
btSoftClusterCollisionShape::btSoftClusterCollisionShape (const btSoftBody::Cluster * cluster) [inline]
Definition at line 122 of file btSoftBodyInternals.h.
References btConcaveShape::setMargin().
Member Function Documentation
virtual void btSoftClusterCollisionShape::batchedUnitVectorGetSupportingVertexWithoutMargin (const btVector3 * vectors, btVector3 * supportVerticesOut, int numVectors) const [inline, virtual]
Definition at line 142 of file btSoftBodyInternals.h.
virtual void btSoftClusterCollisionShape::calculateLocalInertia (btScalar mass, btVector3 & inertia) const [inline, virtual]
Definition at line 146 of file btSoftBodyInternals.h.
virtual void btSoftClusterCollisionShape::getAabb (const btTransform & t, btVector3 & aabbMin, btVector3 & aabbMax) const [inline, virtual]
getAabb's default implementation is brute force, expected derived classes to implement a fast dedicated version
Reimplemented from btConvexInternalShape.
Definition at line 149 of file btSoftBodyInternals.h.
virtual btScalar btSoftClusterCollisionShape::getMargin () const [inline, virtual]
Reimplemented from btConvexInternalShape.
Definition at line 161 of file btSoftBodyInternals.h.
References btConcaveShape::getMargin().
virtual const char* btSoftClusterCollisionShape::getName (void) const [inline, virtual]
Definition at line 155 of file btSoftBodyInternals.h.
virtual int btSoftClusterCollisionShape::getShapeType () const [inline, virtual]
Definition at line 152 of file btSoftBodyInternals.h.
References SOFTBODY_SHAPE_PROXYTYPE.
virtual btVector3 btSoftClusterCollisionShape::localGetSupportingVertex (const btVector3 & vec) const [inline, virtual]
Reimplemented from btConvexInternalShape.
Definition at line 125 of file btSoftBodyInternals.h.
References btDot(), and i.
virtual btVector3 btSoftClusterCollisionShape::localGetSupportingVertexWithoutMargin (const btVector3 & vec) const [inline, virtual]
Definition at line 137 of file btSoftBodyInternals.h.
virtual void btSoftClusterCollisionShape::setMargin (btScalar margin) [inline, virtual]
Reimplemented from btConvexInternalShape.
Definition at line 157 of file btSoftBodyInternals.h.
References btConcaveShape::setMargin().
Member Data Documentation
const btSoftBody::Cluster* btSoftClusterCollisionShape::m_cluster
Definition at line 120 of file btSoftBodyInternals.h.
The documentation for this class was generated from the following file:
btSoftBodyInternals.h