Blender: rna_wm_api.c File Reference
rna_wm_api.c File Reference
RNA
#include <stdlib.h>
#include <stdio.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "DNA_windowmanager_types.h"
Defines
#define WM_GEN_INVOKE_EVENT (1<<0)
#define WM_GEN_INVOKE_SIZE (1<<1)
#define WM_GEN_INVOKE_RETURN (1<<2)
Functions
static void rna_generic_op_invoke (FunctionRNA *func, int flag)
void RNA_api_wm (StructRNA *srna)
void RNA_api_operator (StructRNA *srna)
void RNA_api_macro (StructRNA *srna)
void RNA_api_keyconfig (StructRNA *srna)
void RNA_api_keymap (StructRNA *srna)
void RNA_api_keymapitem (StructRNA *srna)
void RNA_api_keymapitems (StructRNA *srna)
void RNA_api_keymaps (StructRNA *srna)
void RNA_api_keyconfigs (StructRNA *srna)
Detailed Description
Definition in file rna_wm_api.c.
Define Documentation
#define WM_GEN_INVOKE_EVENT (1<<0)
Definition at line 167 of file rna_wm_api.c.
Referenced by RNA_api_wm(), and rna_generic_op_invoke().
#define WM_GEN_INVOKE_RETURN (1<<2)
Definition at line 169 of file rna_wm_api.c.
Referenced by RNA_api_wm(), and rna_generic_op_invoke().
#define WM_GEN_INVOKE_SIZE (1<<1)
Definition at line 168 of file rna_wm_api.c.
Referenced by RNA_api_wm(), and rna_generic_op_invoke().
Function Documentation
void RNA_api_keyconfig (StructRNA * srna)
Definition at line 372 of file rna_wm_api.c.
Referenced by rna_def_keyconfig().
void RNA_api_keyconfigs (StructRNA * srna)
Definition at line 489 of file rna_wm_api.c.
References PROP_REQUIRED, RNA_def_function(), RNA_def_function_return(), RNA_def_pointer(), RNA_def_property_flag(), and RNA_def_string().
Referenced by rna_def_wm_keyconfigs().
void RNA_api_keymap (StructRNA * srna)
Definition at line 378 of file rna_wm_api.c.
References FUNC_USE_CONTEXT, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_pointer(), and RNA_def_property_flag().
Referenced by rna_def_keyconfig().
void RNA_api_keymapitem (StructRNA * srna)
Definition at line 397 of file rna_wm_api.c.
References PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_return(), RNA_def_pointer(), and RNA_def_property_flag().
Referenced by rna_def_keyconfig().
void RNA_api_keymapitems (StructRNA * srna)
Definition at line 409 of file rna_wm_api.c.
References event_type_items, event_value_items, FUNC_USE_REPORTS, PROP_INT, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_ui_text(), and RNA_def_string().
Referenced by rna_def_keymap_items().
void RNA_api_keymaps (StructRNA * srna)
Definition at line 460 of file rna_wm_api.c.
References PROP_REQUIRED, region_type_items, RGN_TYPE_WINDOW, RNA_def_boolean(), RNA_def_enum(), RNA_def_function(), RNA_def_function_return(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_string(), SPACE_EMPTY, and space_type_items.
Referenced by rna_def_wm_keymaps().
void RNA_api_macro (StructRNA * srna)
Definition at line 341 of file rna_wm_api.c.
References FUNC_NO_SELF, FUNC_REGISTER_OPTIONAL, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum_flag(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_string(), and wm_report_items.
Referenced by rna_def_macro_operator().
void RNA_api_operator (StructRNA * srna)
Definition at line 253 of file rna_wm_api.c.
References FUNC_NO_SELF, FUNC_REGISTER_OPTIONAL, NULL, OPERATOR_CANCELLED, operator_return_items, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum_flag(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_string(), and wm_report_items.
Referenced by rna_def_operator().
void RNA_api_wm (StructRNA * srna)
Definition at line 195 of file rna_wm_api.c.
References FLT_MAX, FUNC_NO_SELF, FUNC_USE_CONTEXT, PROP_FLOAT, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_range(), RNA_def_property_ui_text(), rna_generic_op_invoke(), WM_GEN_INVOKE_EVENT, WM_GEN_INVOKE_RETURN, and WM_GEN_INVOKE_SIZE.
Referenced by rna_def_windowmanager().
static void rna_generic_op_invoke (FunctionRNA * func, int flag) [static]
Definition at line 171 of file rna_wm_api.c.
References FUNC_NO_SELF, FUNC_USE_CONTEXT, OPERATOR_CANCELLED, operator_return_items, PROP_REQUIRED, RNA_def_enum_flag(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_int(), RNA_def_pointer(), RNA_def_property_flag(), WM_GEN_INVOKE_EVENT, WM_GEN_INVOKE_RETURN, and WM_GEN_INVOKE_SIZE.
Referenced by RNA_api_wm().