Blender: VideoBase.h File Reference
VideoBase.h File Reference
BGE Video Texture
#include <PyObjectPlus.h>
#include "ImageBase.h"
#include "Exception.h"
Classes
class VideoBase
base class for video source
Enumerations
enum VideoFormat { None, RGB24, YV12, RGBA32 }
Functions
VideoBase * getVideo (PyImage *self)
template<class T >
void Video_init (PyImage *self)
void Video_open (VideoBase *self, char *file, short captureID)
PyObject * Video_play (PyImage *self)
PyObject * Video_pause (PyImage *self)
PyObject * Video_stop (PyImage *self)
PyObject * Video_refresh (PyImage *self)
PyObject * Video_getStatus (PyImage *self, void *closure)
PyObject * Video_getRange (PyImage *self, void *closure)
int Video_setRange (PyImage *self, PyObject *value, void *closure)
PyObject * Video_getRepeat (PyImage *self, void *closure)
int Video_setRepeat (PyImage *self, PyObject *value, void *closure)
PyObject * Video_getFrameRate (PyImage *self, void *closure)
int Video_setFrameRate (PyImage *self, PyObject *value, void *closure)
Variables
const int SourceError = -1
const int SourceEmpty = 0
const int SourceReady = 1
const int SourcePlaying = 2
const int SourceStopped = 3
ExceptionID SourceVideoCreation
Detailed Description
Definition in file VideoBase.h.
Enumeration Type Documentation
enum VideoFormat
Enumerator:
None
RGB24
YV12
RGBA32
Definition at line 46 of file VideoBase.h.
Function Documentation
VideoBase* getVideo (PyImage * self) [inline]
Definition at line 167 of file VideoBase.h.
Referenced by Video_getFrameRate(), Video_getRange(), Video_getRepeat(), Video_getStatus(), Video_pause(), Video_play(), Video_refresh(), Video_setFrameRate(), Video_setRange(), Video_setRepeat(), and Video_stop().
PyObject* Video_getFrameRate (PyImage * self, void * closure)
Definition at line 188 of file VideoBase.cpp.
References getVideo().
PyObject* Video_getRange (PyImage * self, void * closure)
Definition at line 144 of file VideoBase.cpp.
References getVideo().
PyObject* Video_getRepeat (PyImage * self, void * closure)
Definition at line 169 of file VideoBase.cpp.
References getVideo().
PyObject* Video_getStatus (PyImage * self, void * closure)
Definition at line 130 of file VideoBase.cpp.
References getVideo().
Referenced by Video_refresh().
template<class T > void Video_init (PyImage * self)
Definition at line 174 of file VideoBase.h.
References CHCKHRSLT, HRESULT, NULL, S_OK, and T.
void Video_open (VideoBase * self, char * file, short captureID)
Definition at line 105 of file VideoBase.cpp.
References NULL, S_OK, and THRWEXCP.
PyObject* Video_pause (PyImage * self)
Definition at line 123 of file VideoBase.cpp.
References getVideo().
PyObject* Video_play (PyImage * self)
Definition at line 119 of file VideoBase.cpp.
References getVideo().
PyObject* Video_refresh (PyImage * self)
Definition at line 136 of file VideoBase.cpp.
References getVideo(), NULL, ImageBase::refresh(), and Video_getStatus().
int Video_setFrameRate (PyImage * self, PyObject * value, void * closure)
Definition at line 192 of file VideoBase.cpp.
References getVideo(), NULL, and VideoBase::setFrameRate().
int Video_setRange (PyImage * self, PyObject * value, void * closure)
Definition at line 151 of file VideoBase.cpp.
References getVideo(), NULL, and VideoBase::setRange().
int Video_setRepeat (PyImage * self, PyObject * value, void * closure)
Definition at line 173 of file VideoBase.cpp.
References getVideo(), NULL, and VideoBase::setRepeat().
PyObject* Video_stop (PyImage * self)
Definition at line 126 of file VideoBase.cpp.
References getVideo().
Variable Documentation
const int SourceEmpty = 0
Definition at line 39 of file VideoBase.h.
Referenced by initVideoTexture().
const int SourceError = -1
Definition at line 38 of file VideoBase.h.
Referenced by initVideoTexture().
const int SourcePlaying = 2
Definition at line 41 of file VideoBase.h.
Referenced by initVideoTexture(), VideoBase::pause(), VideoBase::play(), and VideoBase::stop().
const int SourceReady = 1
Definition at line 40 of file VideoBase.h.
Referenced by initVideoTexture(), VideoBase::openCam(), VideoBase::openFile(), and VideoBase::play().
const int SourceStopped = 3
Definition at line 42 of file VideoBase.h.
Referenced by initVideoTexture(), VideoBase::pause(), VideoBase::play(), and VideoBase::stop().
ExceptionID SourceVideoCreation
Definition at line 100 of file VideoBase.cpp.