Blender: CStringValue Class Reference
CStringValue Class Reference
#include <StringValue.h>
Public Member Functions
CStringValue ()
Construction / destruction.
CStringValue (const char *txt, const char *name, AllocationTYPE alloctype=CValue::HEAPVALUE)
virtual ~CStringValue ()
virtual bool IsEqual (const STR_String &other)
CValue implementation.
virtual const STR_String & GetText ()
virtual double GetNumber ()
virtual CValue * Calc (VALUE_OPERATOR op, CValue *val)
virtual CValue * CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue *val)
virtual void SetValue (CValue *newval)
virtual CValue * GetReplica ()
Detailed Description
Definition at line 24 of file StringValue.h.
Constructor & Destructor Documentation
CStringValue::CStringValue ()
Construction / destruction.
pre: false effect: constructs a new CStringValue
Definition at line 31 of file StringValue.cpp.
Referenced by CalcFinal(), and GetReplica().
CStringValue::CStringValue (const char * txt, const char * name, AllocationTYPE alloctype = CValue::HEAPVALUE)
pre: effect: constructs a new CStringValue containing text txt
Definition at line 40 of file StringValue.cpp.
References CValue::DisableRefCount(), CPropValue::SetName(), and CValue::STACKVALUE.
virtual CStringValue::~CStringValue () [inline, virtual]
Definition at line 34 of file StringValue.h.
Member Function Documentation
CValue * CStringValue::Calc (VALUE_OPERATOR op, CValue * val) [virtual]
pre: ret: a new object containing the result of applying operator op to this object and val
Implements CValue.
Definition at line 60 of file StringValue.cpp.
References CValue::CalcFinal(), and VALUE_STRING_TYPE.
CValue * CStringValue::CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue * val) [virtual]
pre: the type of val is dtype ret: a new object containing the result of applying operator op to val and this object
Implements CValue.
Definition at line 71 of file StringValue.cpp.
References CStringValue(), GetText(), CValue::GetText(), CValue::op2str(), VALUE_ADD_OPERATOR, VALUE_EMPTY_TYPE, VALUE_EQL_OPERATOR, VALUE_ERROR_TYPE, VALUE_GEQ_OPERATOR, VALUE_GRE_OPERATOR, VALUE_LEQ_OPERATOR, VALUE_LES_OPERATOR, VALUE_NEQ_OPERATOR, and VALUE_STRING_TYPE.
double CStringValue::GetNumber () [virtual]
Implements CValue.
Definition at line 115 of file StringValue.cpp.
CValue * CStringValue::GetReplica (void) [virtual]
Implements CValue.
Definition at line 132 of file StringValue.cpp.
References CStringValue(), and CValue::ProcessReplica().
const STR_String & CStringValue::GetText () [virtual]
Implements CValue.
Definition at line 122 of file StringValue.cpp.
Referenced by CalcFinal().
bool CStringValue::IsEqual (const STR_String & other) [virtual]
CValue implementation.
Definition at line 127 of file StringValue.cpp.
virtual void CStringValue::SetValue (CValue * newval) [inline, virtual]
Sets the value to this cvalue.
Attention:
this particular function should never be called. Why not abstract?
Reimplemented from CValue.
Definition at line 42 of file StringValue.h.
References CValue::GetText(), and CValue::SetModified().
The documentation for this class was generated from the following files:
StringValue.h
StringValue.cpp