Blender: node_shader_squeeze.c File Reference
node_shader_squeeze.c File Reference
shdnodes
#include "node_shader_util.h"
Functions
static void node_shader_exec_squeeze (void *UNUSED(data), bNode *UNUSED(node), bNodeStack **in, bNodeStack **out)
static int gpu_shader_squeeze (GPUMaterial *mat, bNode *UNUSED(node), GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_squeeze (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_squeeze_in []
static bNodeSocketTemplate sh_node_squeeze_out []
Detailed Description
Definition in file node_shader_squeeze.c.
Function Documentation
static int gpu_shader_squeeze (GPUMaterial * mat, bNode * UNUSEDnode, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 60 of file node_shader_squeeze.c.
References GPU_stack_link().
Referenced by register_node_type_sh_squeeze().
static void node_shader_exec_squeeze (void * UNUSEDdata, bNode * UNUSEDnode, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 48 of file node_shader_squeeze.c.
References nodestack_get_vec(), pow(), SOCK_FLOAT, and bNodeStack::vec.
Referenced by register_node_type_sh_squeeze().
void register_node_type_sh_squeeze (bNodeTreeType * ttype)
Definition at line 65 of file node_shader_squeeze.c.
References gpu_shader_squeeze(), NODE_CLASS_CONVERTOR, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_squeeze(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_SQUEEZE.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_squeeze_in[] [static]
Initial value:
 {
    { SOCK_FLOAT, 1, "Value", 0.0f, 0.0f, 0.0f, 0.0f, -100.0f, 100.0f, PROP_NONE},
    { SOCK_FLOAT, 1, "Width", 1.0f, 0.0f, 0.0f, 0.0f, -100.0f, 100.0f, PROP_NONE},
    { SOCK_FLOAT, 1, "Center", 0.0f, 0.0f, 0.0f, 0.0f, -100.0f, 100.0f, PROP_NONE},
    { -1, 0, "" }
}
Definition at line 36 of file node_shader_squeeze.c.
bNodeSocketTemplate sh_node_squeeze_out[] [static]
Initial value:
 {
    { SOCK_FLOAT, 0, "Value"},
    { -1, 0, "" }
}
Definition at line 43 of file node_shader_squeeze.c.