Blender: node_composite_doubleEdgeMask.c File Reference
node_composite_doubleEdgeMask.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_adjacentKeepBorders (unsigned int t, unsigned int rw, unsigned int *limask, unsigned int *lomask, unsigned int *lres, float *res, unsigned int *rsize)
static void do_adjacentBleedBorders (unsigned int t, unsigned int rw, unsigned int *limask, unsigned int *lomask, unsigned int *lres, float *res, unsigned int *rsize)
static void do_allKeepBorders (unsigned int t, unsigned int rw, unsigned int *limask, unsigned int *lomask, unsigned int *lres, float *res, unsigned int *rsize)
static void do_allBleedBorders (unsigned int t, unsigned int rw, unsigned int *limask, unsigned int *lomask, unsigned int *lres, float *res, unsigned int *rsize)
static void do_allEdgeDetection (unsigned int t, unsigned int rw, unsigned int *limask, unsigned int *lomask, unsigned int *lres, float *res, unsigned int *rsize, unsigned int in_isz, unsigned int in_osz, unsigned int in_gsz)
static void do_adjacentEdgeDetection (unsigned int t, unsigned int rw, unsigned int *limask, unsigned int *lomask, unsigned int *lres, float *res, unsigned int *rsize, unsigned int in_isz, unsigned int in_osz, unsigned int in_gsz)
static void do_createEdgeLocationBuffer (unsigned int t, unsigned int rw, unsigned int *lres, float *res, unsigned short *gbuf, unsigned int *innerEdgeOffset, unsigned int *outerEdgeOffset, unsigned int isz, unsigned int gsz)
static void do_fillGradientBuffer (unsigned int rw, float *res, unsigned short *gbuf, unsigned int isz, unsigned int osz, unsigned int gsz, unsigned int innerEdgeOffset, unsigned int outerEdgeOffset)
static void node_composit_exec_doubleedgemask (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_doubleedgemask (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_doubleedgemask_in []
static bNodeSocketTemplate cmp_node_doubleedgemask_out []
Detailed Description
Definition in file node_composite_doubleEdgeMask.c.
Function Documentation
static void do_adjacentBleedBorders (unsigned int t, unsigned int rw, unsigned int * limask, unsigned int * lomask, unsigned int * lres, float * res, unsigned int * rsize) [static]
Definition at line 209 of file node_composite_doubleEdgeMask.c.
Referenced by node_composit_exec_doubleedgemask().
static void do_adjacentEdgeDetection (unsigned int t, unsigned int rw, unsigned int * limask, unsigned int * lomask, unsigned int * lres, float * res, unsigned int * rsize, unsigned int in_isz, unsigned int in_osz, unsigned int in_gsz) [static]
Definition at line 841 of file node_composite_doubleEdgeMask.c.
Referenced by node_composit_exec_doubleedgemask().
static void do_adjacentKeepBorders (unsigned int t, unsigned int rw, unsigned int * limask, unsigned int * lomask, unsigned int * lres, float * res, unsigned int * rsize) [static]
Definition at line 45 of file node_composite_doubleEdgeMask.c.
Referenced by node_composit_exec_doubleedgemask().
static void do_allBleedBorders (unsigned int t, unsigned int rw, unsigned int * limask, unsigned int * lomask, unsigned int * lres, float * res, unsigned int * rsize) [static]
Definition at line 576 of file node_composite_doubleEdgeMask.c.
Referenced by node_composit_exec_doubleedgemask().
static void do_allEdgeDetection (unsigned int t, unsigned int rw, unsigned int * limask, unsigned int * lomask, unsigned int * lres, float * res, unsigned int * rsize, unsigned int in_isz, unsigned int in_osz, unsigned int in_gsz) [static]
Definition at line 779 of file node_composite_doubleEdgeMask.c.
Referenced by node_composit_exec_doubleedgemask().
static void do_allKeepBorders (unsigned int t, unsigned int rw, unsigned int * limask, unsigned int * lomask, unsigned int * lres, float * res, unsigned int * rsize) [static]
Definition at line 420 of file node_composite_doubleEdgeMask.c.
Referenced by node_composit_exec_doubleedgemask().
static void do_createEdgeLocationBuffer (unsigned int t, unsigned int rw, unsigned int * lres, float * res, unsigned short * gbuf, unsigned int * innerEdgeOffset, unsigned int * outerEdgeOffset, unsigned int isz, unsigned int gsz) [static]
Definition at line 907 of file node_composite_doubleEdgeMask.c.
Referenced by node_composit_exec_doubleedgemask().
static void do_fillGradientBuffer (unsigned int rw, float * res, unsigned short * gbuf, unsigned int isz, unsigned int osz, unsigned int gsz, unsigned int innerEdgeOffset, unsigned int outerEdgeOffset) [static]
Definition at line 1018 of file node_composite_doubleEdgeMask.c.
Referenced by node_composit_exec_doubleedgemask().
static void node_composit_exec_doubleedgemask (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 1146 of file node_composite_doubleEdgeMask.c.
References alloc_compbuf(), CB_VAL, bNode::custom1, bNode::custom2, bNodeStack::data, data, do_adjacentBleedBorders(), do_adjacentEdgeDetection(), do_adjacentKeepBorders(), do_allBleedBorders(), do_allEdgeDetection(), do_allKeepBorders(), do_createEdgeLocationBuffer(), do_fillGradientBuffer(), MEM_freeN(), MEM_mallocN(), CompBuf::rect, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_doubleedgemask().
void register_node_type_cmp_doubleedgemask (bNodeTreeType * ttype)
Definition at line 1274 of file node_composite_doubleEdgeMask.c.
References CMP_NODE_DOUBLEEDGEMASK, NODE_CLASS_MATTE, node_composit_exec_doubleedgemask(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_doubleedgemask_in[] [static]
Initial value:
 {
    { SOCK_FLOAT, 1, "Inner Mask", 0.8f, 0.8f, 0.8f, 1.0f, 0.0f, 1.0f, PROP_NONE},
    { SOCK_FLOAT, 1, "Outer Mask", 0.8f, 0.8f, 0.8f, 1.0f, 0.0f, 1.0f, PROP_NONE},
    { -1, 0, "" }
}
Definition at line 35 of file node_composite_doubleEdgeMask.c.
bNodeSocketTemplate cmp_node_doubleedgemask_out[] [static]
Initial value:
 {
    { SOCK_FLOAT, 0, "Mask"},
    { -1, 0, "" }
}
Definition at line 40 of file node_composite_doubleEdgeMask.c.