Blender: bmesh_interp.h File Reference
bmesh_interp.h File Reference
BMesh
Functions
void BM_loop_interp_multires (BMesh *bm, BMLoop *target, BMFace *source)
void BM_vert_interp_from_face (BMesh *bm, BMVert *v, BMFace *source)
void BM_data_interp_from_verts (BMesh *bm, BMVert *v1, BMVert *v2, BMVert *v, const float fac)
Data, Interp From Verts.
void BM_data_interp_face_vert_edge (BMesh *bm, BMVert *v1, BMVert *v2, BMVert *v, BMEdge *e1, const float fac)
void BM_data_layer_add (BMesh *em, CustomData *data, int type)
void BM_data_layer_add_named (BMesh *bm, CustomData *data, int type, const char *name)
void BM_data_layer_free (BMesh *em, CustomData *data, int type)
void BM_data_layer_free_n (BMesh *bm, CustomData *data, int type, int n)
float BM_elem_float_data_get (CustomData *cd, void *element, int type)
void BM_elem_float_data_set (CustomData *cd, void *element, int type, const float val)
void BM_face_interp_from_face (BMesh *bm, BMFace *target, BMFace *source)
Data Interp From Face.
void BM_loop_interp_from_face (BMesh *bm, BMLoop *target, BMFace *source, int do_vertex, int do_multires)
void BM_face_multires_bounds_smooth (BMesh *bm, BMFace *f)
Detailed Description
Definition in file bmesh_interp.h.
Function Documentation
void BM_data_interp_face_vert_edge (BMesh * bm, BMVert * v1, BMVert * v2, BMVert * v, BMEdge * e1, const float fac)
void BM_data_interp_from_verts (BMesh * bm, BMVert * v1, BMVert * v2, BMVert * v, const float fac)
Data, Interp From Verts.
Interpolates per-vertex data from two sources to a target.
Definition at line 53 of file bmesh_interp.c.
References CustomData_bmesh_copy_data(), CustomData_bmesh_free_block(), CustomData_bmesh_interp(), BMHeader::data, BMVert::head, NULL, and BMesh::vdata.
Referenced by BM_edge_split(), BM_vert_collapse_faces(), and bpy_bmvert_copy_from_vert_interp().
void BM_data_layer_add (BMesh * em, CustomData * data, int type)
Definition at line 792 of file bmesh_interp.c.
References CD_DEFAULT, CustomData_add_layer(), data, CustomData::layers, MEM_dupallocN(), MEM_freeN(), NULL, CustomData::pool, and update_data_blocks().
Referenced by bmo_edgebisect_exec(), bmo_esubd_exec(), BPy_BMEdge_CreatePyObject(), BPy_BMesh_CreatePyObject(), BPy_BMFace_CreatePyObject(), bpy_bmlayercollection_new(), BPy_BMLoop_CreatePyObject(), BPy_BMVert_CreatePyObject(), DM_to_bmesh_ex(), ED_uvedit_assign_image(), ED_uvedit_ensure_uvs(), edbm_bevel_exec(), and vgroup_assign_verts().
void BM_data_layer_add_named (BMesh * bm, CustomData * data, int type, const char * name)
Definition at line 808 of file bmesh_interp.c.
References CD_DEFAULT, CustomData_add_layer_named(), data, CustomData::layers, MEM_dupallocN(), MEM_freeN(), NULL, CustomData::pool, and update_data_blocks().
Referenced by bpy_bmlayercollection_new(), ED_mesh_color_add(), ED_mesh_uv_texture_add(), and EDBM_verts_mirror_cache_begin().
void BM_data_layer_free (BMesh * em, CustomData * data, int type)
Definition at line 824 of file bmesh_interp.c.
References CustomData_free_layer_active(), data, CustomData::layers, MEM_dupallocN(), MEM_freeN(), NULL, CustomData::pool, and update_data_blocks().
Referenced by bpy_bmesh_dealloc(), delete_customdata_layer(), and multires_customdata_delete().
void BM_data_layer_free_n (BMesh * bm, CustomData * data, int type, int n)
Definition at line 840 of file bmesh_interp.c.
References CustomData_free_layer(), CustomData_get_layer_index_n(), data, CustomData::layers, MEM_dupallocN(), MEM_freeN(), NULL, CustomData::pool, and update_data_blocks().
Referenced by bmo_edgebisect_exec(), bmo_esubd_exec(), bpy_bmlayercollection_remove(), and edbm_bevel_exec().
float BM_elem_float_data_get (CustomData * cd, void * element, int type)
Definition at line 856 of file bmesh_interp.c.
References CustomData_bmesh_get(), and data.
Referenced by bevel_init_edges(), bevel_init_verts(), bmvert_to_mvert(), CDDM_from_BMEditMesh(), edgetag_context_check(), emDM_copyEdgeArray(), emDM_copyVertArray(), and emDM_getEdge().
void BM_elem_float_data_set (CustomData * cd, void * element, int type, const float val)
Definition at line 862 of file bmesh_interp.c.
References CustomData_bmesh_get(), and data.
Referenced by BM_mesh_bm_from_me(), and DM_to_bmesh_ex().
void BM_face_interp_from_face (BMesh * bm, BMFace * target, BMFace * source)
Data Interp From Face.
projects target onto source, and pulls interpolated customdata from source.
Note:
Only handles loop customdata. multires is handled.
Definition at line 150 of file bmesh_interp.c.
References BLI_array_fixedstack_declare, BLI_array_fixedstack_free, BM_elem_attrs_copy(), BM_FACE_FIRST_LOOP, BM_NGON_STACK_SIZE, BMVert::co, copy_v3_v3(), cos(), CustomData_bmesh_interp(), BMHeader::data, BMLoop::head, i, interp_weights_poly_v3(), BMesh::ldata, BMFace::len, BMLoop::next, NULL, and BMLoop::v.
Referenced by bpy_bmface_copy_from_face_interp().
void BM_face_multires_bounds_smooth (BMesh * bm, BMFace * f)
smoothes boundaries between multires grids, including some borders in adjacent faces
Definition at line 484 of file bmesh_interp.c.
References add_v3_v3v3(), BM_ITER_ELEM, BM_LOOPS_OF_FACE, CD_MDISPS, co, copy_v3_v3(), CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, MDisps::disps, BMLoop::head, BMesh::ldata, mul_v3_fl(), BMLoop::next, BMLoop::prev, BMLoop::radial_next, sqrt(), MDisps::totdisp, and BMLoop::v.
Referenced by BM_edge_split(), and BM_face_split().
void BM_loop_interp_from_face (BMesh * bm, BMLoop * target, BMFace * source, int do_vertex, int do_multires)
projects a single loop, target, onto source for customdata interpolation. multires is handled. if do_vertex is true, target's vert data will also get interpolated.
Definition at line 598 of file bmesh_interp.c.
References add_v3_v3(), axis_dominant_v3(), BLI_array_fixedstack_declare, BLI_array_fixedstack_free, BM_elem_attrs_copy(), BM_FACE_FIRST_LOOP, bm_loop_interp_mdisps(), BM_NGON_STACK_SIZE, CD_MDISPS, co, BMVert::co, copy_v3_v3(), cos(), CustomData_bmesh_interp(), CustomData_has_layer(), BMHeader::data, BMLoop::f, BMVert::head, BMLoop::head, i, interp_weights_poly_v3(), BMesh::ldata, BMFace::len, mul_v3_fl(), BMLoop::next, BMFace::no, NULL, sub_v3_v3v3(), BMLoop::v, and BMesh::vdata.
Referenced by BM_face_split(), BM_face_split_n(), bmo_bevel_exec(), bpy_bmloop_copy_from_face_interp(), and projectSVData().
void BM_loop_interp_multires (BMesh * bm, BMLoop * target, BMFace * source)
project the multires grid in target onto source's set of multires grids
Definition at line 589 of file bmesh_interp.c.
References bm_loop_interp_mdisps().
Referenced by BM_edge_split(), BM_faces_join(), bmo_bevel_exec(), and projectSVData().
void BM_vert_interp_from_face (BMesh * bm, BMVert * v, BMFace * source)
Definition at line 676 of file bmesh_interp.c.
References add_v3_v3(), BLI_array_fixedstack_declare, BLI_array_fixedstack_free, BM_FACE_FIRST_LOOP, BM_NGON_STACK_SIZE, BMVert::co, copy_v3_v3(), cos(), CustomData_bmesh_interp(), BMHeader::data, BMVert::head, i, interp_weights_poly_v3(), BMFace::len, mul_v3_fl(), BMLoop::next, NULL, sub_v3_v3v3(), BMLoop::v, and BMesh::vdata.
Referenced by bpy_bmvert_copy_from_face_interp().