Blender: ImageSourceMix Class Reference
ImageSourceMix Class Reference
class for source mixing
#include <ImageMix.h>
Public Member Functions
ImageSourceMix (const char *id)
constructor
virtual ~ImageSourceMix (void)
destructor
long long getOffset (void)
get offset
void setOffset (unsigned int *firstImg)
set offset
short getWeight (void)
get weight
void setWeight (short weight)
set weight
Protected Attributes
long long m_offset
buffer offset to the first source buffer
short m_weight
source weight
Detailed Description
class for source mixing
Definition at line 38 of file ImageMix.h.
Constructor & Destructor Documentation
ImageSourceMix::ImageSourceMix (const char * id) [inline]
constructor
Definition at line 42 of file ImageMix.h.
virtual ImageSourceMix::~ImageSourceMix (void) [inline, virtual]
destructor
Definition at line 44 of file ImageMix.h.
Member Function Documentation
long long ImageSourceMix::getOffset (void) [inline]
get offset
Definition at line 47 of file ImageMix.h.
References m_offset.
Referenced by FilterImageMix::filter().
short ImageSourceMix::getWeight (void) [inline]
get weight
Definition at line 52 of file ImageMix.h.
References m_weight.
Referenced by FilterImageMix::filter(), and ImageMix::getWeight().
void ImageSourceMix::setOffset (unsigned int * firstImg) [inline]
set offset
Definition at line 49 of file ImageMix.h.
References ImageSource::m_image, and m_offset.
Referenced by ImageMix::calcImage().
void ImageSourceMix::setWeight (short weight) [inline]
set weight
Definition at line 54 of file ImageMix.h.
References m_weight.
Referenced by ImageMix::setWeight().
Member Data Documentation
long long ImageSourceMix::m_offset [protected]
buffer offset to the first source buffer
Definition at line 58 of file ImageMix.h.
Referenced by getOffset(), and setOffset().
short ImageSourceMix::m_weight [protected]
source weight
Definition at line 60 of file ImageMix.h.
Referenced by getWeight(), and setWeight().
The documentation for this class was generated from the following file:
ImageMix.h