Blender: rna_movieclip.c File Reference
rna_movieclip.c File Reference
RNA
#include <stdlib.h>
#include <limits.h>
#include "MEM_guardedalloc.h"
#include "BKE_movieclip.h"
#include "BKE_tracking.h"
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_movieclip_types.h"
#include "DNA_scene_types.h"
#include "WM_types.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
Functions
static void rna_def_movieclip_proxy (BlenderRNA *brna)
static void rna_def_moviecliUser (BlenderRNA *brna)
static void rna_def_movieClipScopes (BlenderRNA *brna)
static void rna_def_movieclip (BlenderRNA *brna)
void RNA_def_movieclip (BlenderRNA *brna)
Detailed Description
Definition in file rna_movieclip.c.
Function Documentation
static void rna_def_movieclip (BlenderRNA * brna) [static]
Definition at line 218 of file rna_movieclip.c.
References MCLIP_SRC_MOVIE, MCLIP_SRC_SEQUENCE, MCLIP_USE_PROXY, MCLIP_USE_PROXY_CUSTOM_DIR, NC_MOVIECLIP, ND_DISPLAY, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FILEPATH, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_XYZ, RNA_def_int_vector(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_movieclip().
void RNA_def_movieclip (BlenderRNA * brna)
Definition at line 286 of file rna_movieclip.c.
References rna_def_movieclip(), rna_def_movieclip_proxy(), rna_def_movieClipScopes(), and rna_def_moviecliUser().
static void rna_def_movieclip_proxy (BlenderRNA * brna) [static]
Definition at line 71 of file rna_movieclip.c.
References IMB_TC_FREE_RUN, IMB_TC_INTERPOLATED_REC_DATE_FREE_RUN, IMB_TC_NONE, IMB_TC_RECORD_RUN, IMB_TC_RECORD_RUN_NO_GAPS, MCLIP_PROXY_SIZE_100, MCLIP_PROXY_SIZE_25, MCLIP_PROXY_SIZE_50, MCLIP_PROXY_SIZE_75, MCLIP_PROXY_UNDISTORTED_SIZE_100, MCLIP_PROXY_UNDISTORTED_SIZE_25, MCLIP_PROXY_UNDISTORTED_SIZE_50, MCLIP_PROXY_UNDISTORTED_SIZE_75, NC_MOVIECLIP, ND_DISPLAY, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_DIRPATH, PROP_ENUM, PROP_INT, PROP_NONE, PROP_STRING, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_movieclip().
static void rna_def_movieClipScopes (BlenderRNA * brna) [static]
Definition at line 209 of file rna_movieclip.c.
References NULL, RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_movieclip().
static void rna_def_moviecliUser (BlenderRNA * brna) [static]
Definition at line 171 of file rna_movieclip.c.
References MAXFRAME, MCLIP_PROXY_RENDER_SIZE_100, MCLIP_PROXY_RENDER_SIZE_25, MCLIP_PROXY_RENDER_SIZE_50, MCLIP_PROXY_RENDER_SIZE_75, MCLIP_PROXY_RENDER_SIZE_FULL, MCLIP_PROXY_RENDER_UNDISTORT, MINAFRAME, NC_MOVIECLIP, ND_DISPLAY, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_INT, PROP_NONE, PROP_TIME, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_movieclip().