Blender: BL_ArmatureActuator Class Reference
BL_ArmatureActuator Class Reference
#include <BL_ArmatureActuator.h>
Public Member Functions
BL_ArmatureActuator (SCA_IObject *gameobj, int type, const char *posechannel, const char *constraintname, KX_GameObject *targetobj, KX_GameObject *subtargetobj, float weight, float influence)
virtual ~BL_ArmatureActuator ()
virtual CValue * GetReplica ()
virtual void ProcessReplica ()
virtual bool UnlinkObject (SCA_IObject *clientobj)
virtual void Relink (CTR_Map< CTR_HashedPtr, void * > *obj_map)
virtual bool Update (double curtime, bool frame)
virtual void ReParent (SCA_IObject *parent)
Detailed Description
This class is the conversion of the Pose channel constraint. It makes a link between the pose constraint and the KX scene. The main purpose is to give access to the constraint target to link it to a game object. It also allows to activate/deactivate constraints during the game. Later it will also be possible to create constraint on the fly
Definition at line 47 of file BL_ArmatureActuator.h.
Constructor & Destructor Documentation
BL_ArmatureActuator::BL_ArmatureActuator (SCA_IObject * obj, int type, const char * posechannel, const char * constraintname, KX_GameObject * targetobj, KX_GameObject * subtargetobj, float weight, float influence)
This class is the conversion of the Pose channel constraint. It makes a link between the pose constraint and the KX scene. The main purpose is to give access to the constraint target to link it to a game object. It also allows to activate/deactivate constraints during the game. Later it will also be possible to create constraint on the fly
Definition at line 50 of file BL_ArmatureActuator.cpp.
References SCA_IObject::RegisterActuator().
Referenced by GetReplica().
BL_ArmatureActuator::~BL_ArmatureActuator () [virtual]
Definition at line 75 of file BL_ArmatureActuator.cpp.
References SCA_IObject::UnregisterActuator().
Member Function Documentation
virtual CValue* BL_ArmatureActuator::GetReplica (void) [inline, virtual]
Implements CValue.
Definition at line 62 of file BL_ArmatureActuator.h.
References BL_ArmatureActuator(), and ProcessReplica().
void BL_ArmatureActuator::ProcessReplica () [virtual]
Makes sure any internal data owned by this class is deep copied.
Reimplemented from SCA_IActuator.
Definition at line 83 of file BL_ArmatureActuator.cpp.
References SCA_IObject::RegisterActuator(), and SCA_IObject::UnregisterActuator().
Referenced by GetReplica().
void BL_ArmatureActuator::Relink (CTR_Map< CTR_HashedPtr, void * > * obj_map) [virtual]
Reimplemented from SCA_ILogicBrick.
Definition at line 118 of file BL_ArmatureActuator.cpp.
References SCA_IObject::RegisterActuator(), and SCA_IObject::UnregisterActuator().
void BL_ArmatureActuator::ReParent (SCA_IObject * parent) [virtual]
Reimplemented from SCA_ILogicBrick.
Definition at line 93 of file BL_ArmatureActuator.cpp.
bool BL_ArmatureActuator::UnlinkObject (SCA_IObject * clientobj) [virtual]
UnlinkObject(...) Certain actuator use gameobject pointers (like TractTo actuator) This function can be called when an object is removed to make sure that the actuator will not use it anymore.
Reimplemented from SCA_IActuator.
Definition at line 100 of file BL_ArmatureActuator.cpp.
References NULL.
bool BL_ArmatureActuator::Update (double curtime, bool frame) [virtual]
Update(...) Update the actuator based upon the events received since the last call to Update, the current time and deltatime the time elapsed in this frame ? It is the responsibility of concrete Actuators to clear their event's. This is usually done in the Update() method via a call to RemoveAllEvents()
Reimplemented from SCA_IActuator.
Definition at line 146 of file BL_ArmatureActuator.cpp.
References ACT_ARM_DISABLE, ACT_ARM_ENABLE, ACT_ARM_RUN, ACT_ARM_SETINFLUENCE, ACT_ARM_SETTARGET, ACT_ARM_SETWEIGHT, BL_ArmatureConstraint::ClrConstraintFlag(), CONSTRAINT_OFF, SCA_ILogicBrick::GetParent(), SCA_IActuator::IsNegativeEvent(), NULL, SCA_IActuator::RemoveAllEvents(), BL_ArmatureObject::SetActiveAction(), BL_ArmatureConstraint::SetConstraintFlag(), BL_ArmatureConstraint::SetInfluence(), BL_ArmatureConstraint::SetSubtarget(), BL_ArmatureConstraint::SetTarget(), and BL_ArmatureConstraint::SetWeight().
The documentation for this class was generated from the following files:
BL_ArmatureActuator.h
BL_ArmatureActuator.cpp