Blender: keyframing.c File Reference
keyframing.c File Reference
animation
#include <stdio.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_dynstr.h"
#include "BLI_utildefines.h"
#include "DNA_anim_types.h"
#include "DNA_armature_types.h"
#include "DNA_constraint_types.h"
#include "DNA_key_types.h"
#include "DNA_material_types.h"
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "BKE_animsys.h"
#include "BKE_action.h"
#include "BKE_armature.h"
#include "BKE_constraint.h"
#include "BKE_depsgraph.h"
#include "BKE_fcurve.h"
#include "BKE_main.h"
#include "BKE_nla.h"
#include "BKE_global.h"
#include "BKE_context.h"
#include "BKE_report.h"
#include "BKE_key.h"
#include "BKE_material.h"
#include "ED_anim_api.h"
#include "ED_keyframing.h"
#include "ED_keyframes_edit.h"
#include "ED_screen.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "anim_intern.h"
Enumerations
enum { KEYNEEDED_DONTADD = 0, KEYNEEDED_JUSTADD, KEYNEEDED_DELPREV, KEYNEEDED_DELNEXT }
enum { VISUALKEY_NONE = 0, VISUALKEY_LOC, VISUALKEY_ROT }
enum { COMMONKEY_MODE_INSERT = 0, COMMONKEY_MODE_DELETE }
Functions
short ANIM_get_keyframing_flags (Scene *scene, short incl_mode)
bAction * verify_adt_action (ID *id, short add)
FCurve * verify_fcurve (bAction *act, const char group[], const char rna_path[], const int array_index, short add)
int insert_bezt_fcurve (FCurve *fcu, BezTriple *bezt, short flag)
int insert_vert_fcurve (FCurve *fcu, float x, float y, short flag)
static short new_key_needed (FCurve *fcu, float cFrame, float nValue)
static float setting_get_rna_value (PointerRNA *ptr, PropertyRNA *prop, int index)
static short visualkey_can_use (PointerRNA *ptr, PropertyRNA *prop)
static float visualkey_get_value (PointerRNA *ptr, PropertyRNA *prop, int array_index)
short insert_keyframe_direct (ReportList *reports, PointerRNA ptr, PropertyRNA *prop, FCurve *fcu, float cfra, short flag)
short insert_keyframe (ReportList *reports, ID *id, bAction *act, const char group[], const char rna_path[], int array_index, float cfra, short flag)
short delete_keyframe (ReportList *reports, ID *id, bAction *act, const char group[], const char rna_path[], int array_index, float cfra, short UNUSED(flag))
static int modify_key_op_poll (bContext *C)
static int insert_key_exec (bContext *C, wmOperator *op)
void ANIM_OT_keyframe_insert (wmOperatorType *ot)
static int insert_key_menu_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void ANIM_OT_keyframe_insert_menu (wmOperatorType *ot)
static int delete_key_exec (bContext *C, wmOperator *op)
void ANIM_OT_keyframe_delete (wmOperatorType *ot)
static int delete_key_v3d_exec (bContext *C, wmOperator *op)
void ANIM_OT_keyframe_delete_v3d (wmOperatorType *ot)
static int insert_key_button_exec (bContext *C, wmOperator *op)
void ANIM_OT_keyframe_insert_button (wmOperatorType *ot)
static int delete_key_button_exec (bContext *C, wmOperator *op)
void ANIM_OT_keyframe_delete_button (wmOperatorType *ot)
int autokeyframe_cfra_can_key (Scene *scene, ID *id)
short fcurve_frame_has_keyframe (FCurve *fcu, float frame, short filter)
static short action_frame_has_keyframe (bAction *act, float frame, short filter)
static short object_frame_has_keyframe (Object *ob, float frame, short filter)
short id_frame_has_keyframe (ID *id, float frame, short filter)
int ED_autokeyframe_object (bContext *C, Scene *scene, Object *ob, KeyingSet *ks)
int ED_autokeyframe_pchan (bContext *C, Scene *scene, Object *ob, bPoseChannel *pchan, KeyingSet *ks)
Detailed Description
Definition in file keyframing.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
KEYNEEDED_DONTADD
KEYNEEDED_JUSTADD
KEYNEEDED_DELPREV
KEYNEEDED_DELNEXT
Definition at line 369 of file keyframing.c.
anonymous enum
Enumerator:
VISUALKEY_NONE
VISUALKEY_LOC
VISUALKEY_ROT
Definition at line 524 of file keyframing.c.
anonymous enum
Enumerator:
COMMONKEY_MODE_INSERT
COMMONKEY_MODE_DELETE
Definition at line 1067 of file keyframing.c.
Function Documentation
static short action_frame_has_keyframe (bAction * act, float frame, short filter) [static]
Definition at line 1622 of file keyframing.c.
References ACT_MUTED, ANIMFILTER_KEYS_MUTED, FCurve::bezt, bAction::curves, fcurve_frame_has_keyframe(), ListBase::first, bAction::flag, FCurve::next, NULL, and FCurve::totvert.
Referenced by id_frame_has_keyframe(), and object_frame_has_keyframe().
short ANIM_get_keyframing_flags (Scene * scene, short incl_mode)
Definition at line 89 of file keyframing.c.
References INSERTKEY_MATRIX, INSERTKEY_NEEDED, INSERTKEY_REPLACE, INSERTKEY_XYZ2RGB, IS_AUTOKEY_FLAG, and IS_AUTOKEY_MODE.
Referenced by achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), add_default_keyingset_exec(), add_keyingset_button_exec(), ANIM_apply_keyingset(), autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), insert_action_keys(), insert_graph_keys(), insert_key_button_exec(), and ui_but_anim_autokey().
void ANIM_OT_keyframe_delete (wmOperatorType * ot)
Definition at line 1312 of file keyframing.c.
References ANIM_keying_sets_enum_itemf(), delete_key_exec(), wmOperatorType::description, DummyRNA_DEFAULT_items, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, modify_key_op_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, PROP_HIDDEN, RNA_def_boolean(), RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_property_flag(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyframe_delete_button (wmOperatorType * ot)
Definition at line 1549 of file keyframing.c.
References delete_key_button_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, modify_key_op_poll(), wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyframe_delete_v3d (wmOperatorType * ot)
Definition at line 1387 of file keyframing.c.
References delete_key_v3d_exec(), wmOperatorType::description, ED_operator_areaactive(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyframe_insert (wmOperatorType * ot)
Definition at line 1156 of file keyframing.c.
References ANIM_keying_sets_enum_itemf(), wmOperatorType::description, DummyRNA_DEFAULT_items, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, insert_key_exec(), modify_key_op_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, PROP_HIDDEN, RNA_def_boolean(), RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_property_flag(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyframe_insert_button (wmOperatorType * ot)
Definition at line 1477 of file keyframing.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, insert_key_button_exec(), modify_key_op_poll(), wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
void ANIM_OT_keyframe_insert_menu (wmOperatorType * ot)
Definition at line 1217 of file keyframing.c.
References ANIM_keying_sets_enum_itemf(), wmOperatorType::description, DummyRNA_DEFAULT_items, ED_operator_areaactive(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, insert_key_exec(), insert_key_menu_invoke(), wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, PROP_HIDDEN, RNA_def_boolean(), RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_property_flag(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
int autokeyframe_cfra_can_key (Scene * scene, ID * id)
Definition at line 1569 of file keyframing.c.
References ANIMFILTER_KEYS_LOCAL, CFRA, id_frame_has_keyframe(), IS_AUTOKEY_MODE, and IS_AUTOKEY_ON.
Referenced by autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), ED_autokeyframe_object(), ED_autokeyframe_pchan(), move_camera(), pose_clear_transform_generic_exec(), poseAnim_mapping_autoKeyframe(), poselib_keytag_pose(), and ui_but_anim_autokey().
static int delete_key_button_exec (bContext * C, wmOperator * op) [static]
Definition at line 1496 of file keyframing.c.
References CFRA, CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), PointerRNA::data, delete_keyframe(), G, G_DEBUG, PointerRNA::id, length(), MEM_freeN(), NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_path_from_ID_to_property(), RNA_property_array_length(), uiContextActiveProperty(), uiContextAnimUpdate(), and WM_event_add_notifier().
Referenced by ANIM_OT_keyframe_delete_button().
static int delete_key_exec (bContext * C, wmOperator * op) [static]
Definition at line 1258 of file keyframing.c.
References Scene::active_keyingset, ANIM_apply_keyingset(), BKE_report(), BKE_reportf(), BLI_findlink(), builtin_keyingsets, CFRA, CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), G, G_DEBUG, Scene::keyingsets, MODIFYKEY_INVALID_CONTEXT, MODIFYKEY_MODE_DELETE, NA_EDITED, KeyingSet::name, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_enum_get(), RPT_ERROR, RPT_INFO, RPT_WARNING, and WM_event_add_notifier().
Referenced by ANIM_OT_keyframe_delete().
static int delete_key_v3d_exec (bContext * C, wmOperator * op) [static]
Definition at line 1349 of file keyframing.c.
References AnimData::action, FCurve::array_index, BKE_reportf(), CFRA, CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), bAction::curves, DAG_ids_flush_update(), delete_keyframe(), ListBase::first, ID::name, NC_OBJECT, ND_KEYS, FCurve::next, NULL, OB_RECALC_OB, OPERATOR_FINISHED, wmOperator::reports, FCurve::rna_path, RPT_INFO, and WM_event_add_notifier().
Referenced by ANIM_OT_keyframe_delete_v3d().
short delete_keyframe (ReportList * reports, ID * id, bAction * act, const char group[], const char rna_path[], int array_index, float cfra, short UNUSEDflag)
Definition at line 974 of file keyframing.c.
References AnimData::action, AGRP_PROTECTED, ANIM_fcurve_delete_from_animdata(), FCurve::bezt, binarysearch_bezt_index(), BKE_animdata_from_id(), BKE_nla_tweakedit_remap(), BKE_report(), BKE_reportf(), delete_fcurve_key(), ELEM, FCURVE_PROTECTED, bActionGroup::flag, FCurve::flag, FMI_TYPE_GENERATE_CURVE, G, G_DEBUG, FCurve::grp, i, list_has_suitable_fmodifier(), FCurve::modifiers, ID::name, NLATIME_CONVERT_UNMAP, NULL, RNA_id_pointer_create(), RNA_path_resolve(), RNA_property_array_length(), RPT_ERROR, FCurve::totvert, and verify_fcurve().
Referenced by ANIM_apply_keyingset(), delete_key_button_exec(), delete_key_v3d_exec(), and pyrna_struct_keyframe_delete().
int ED_autokeyframe_object (bContext * C, Scene * scene, Object * ob, KeyingSet * ks)
Definition at line 1742 of file keyframing.c.
References ANIM_apply_keyingset(), ANIM_relative_keyingset_add_source(), autokeyframe_cfra_can_key(), BLI_freelistN(), CFRA, FALSE, Object::id, MODIFYKEY_MODE_INSERT, NULL, and TRUE.
Referenced by object_clear_transform_generic_exec(), snap_sel_to_curs(), and snap_sel_to_grid().
int ED_autokeyframe_pchan (bContext * C, Scene * scene, Object * ob, bPoseChannel * pchan, KeyingSet * ks)
Definition at line 1764 of file keyframing.c.
References ANIM_apply_keyingset(), ANIM_relative_keyingset_add_source(), autokeyframe_cfra_can_key(), BLI_freelistN(), bPoseChannel::bone, BONE_UNKEYED, CFRA, FALSE, Bone::flag, Object::id, MODIFYKEY_MODE_INSERT, NULL, RNA_PoseBone, and TRUE.
Referenced by pose_flip_quats_exec(), pose_paste_exec(), snap_sel_to_curs(), and snap_sel_to_grid().
short fcurve_frame_has_keyframe (FCurve * fcu, float frame, short filter)
Definition at line 1595 of file keyframing.c.
References ANIMFILTER_KEYS_MUTED, FCurve::bezt, binarysearch_bezt_index(), ELEM, FCURVE_MUTED, FCurve::flag, i, NULL, FCurve::totvert, and tAnimCopybufItem::totvert.
Referenced by achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), action_frame_has_keyframe(), and ui_but_anim_flag().
short id_frame_has_keyframe (ID * id, float frame, short filter)
Definition at line 1708 of file keyframing.c.
References AnimData::action, action_frame_has_keyframe(), BKE_animdata_from_id(), GS, ID_OB, ID_SCE, ID::name, NULL, and object_frame_has_keyframe().
Referenced by autokeyframe_cfra_can_key(), draw_selected_name(), and object_frame_has_keyframe().
int insert_bezt_fcurve (FCurve * fcu, BezTriple * bezt, short flag)
Definition at line 217 of file keyframing.c.
References FCurve::bezt, binarysearch_bezt_index(), BezTriple::f1, BezTriple::f2, BezTriple::f3, FCurve::fpt, i, INSERTKEY_REPLACE, MEM_callocN(), MEM_freeN(), NULL, FCurve::totvert, tAnimCopybufItem::totvert, and BezTriple::vec.
Referenced by AnimationImporter::add_bezt(), insert_vert_fcurve(), and paste_animedit_keys_fcurve().
static int insert_key_button_exec (bContext * C, wmOperator * op) [static]
Definition at line 1407 of file keyframing.c.
References ANIM_get_keyframing_flags(), BKE_report(), CFRA, CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), PointerRNA::data, NlaStrip::fcurves, G, G_DEBUG, PointerRNA::id, insert_keyframe(), insert_keyframe_direct(), length(), list_find_fcurve(), MEM_freeN(), NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_NlaStrip, RNA_path_from_ID_to_property(), RNA_property_animateable(), RNA_property_array_length(), RNA_property_identifier(), RPT_WARNING, PointerRNA::type, uiContextActiveProperty(), uiContextAnimUpdate(), and WM_event_add_notifier().
Referenced by ANIM_OT_keyframe_insert_button().
static int insert_key_exec (bContext * C, wmOperator * op) [static]
Definition at line 1102 of file keyframing.c.
References Scene::active_keyingset, ANIM_apply_keyingset(), BKE_report(), BKE_reportf(), BLI_findlink(), builtin_keyingsets, CFRA, CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), G, G_DEBUG, Scene::keyingsets, MODIFYKEY_INVALID_CONTEXT, MODIFYKEY_MODE_INSERT, NA_EDITED, KeyingSet::name, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_enum_get(), RPT_ERROR, RPT_INFO, RPT_WARNING, and WM_event_add_notifier().
Referenced by ANIM_OT_keyframe_insert(), and ANIM_OT_keyframe_insert_menu().
static int insert_key_menu_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1191 of file keyframing.c.
References Scene::active_keyingset, CTX_data_scene(), wmOperatorType::exec, wmOperatorType::name, OPERATOR_CANCELLED, wmOperator::ptr, RNA_boolean_get(), RNA_boolean_set(), RNA_enum_set(), TRUE, wmOperator::type, uiItemsEnumO(), uiPupMenuBegin(), uiPupMenuEnd(), and uiPupMenuLayout().
Referenced by ANIM_OT_keyframe_insert_menu().
short insert_keyframe (ReportList * reports, ID * id, bAction * act, const char group[], const char rna_path[], int array_index, float cfra, short flag)
Definition at line 883 of file keyframing.c.
References BKE_animdata_from_id(), BKE_nla_tweakedit_remap(), BKE_reportf(), FCurve::color_mode, ELEM5, FCURVE_COLOR_AUTO_RGB, insert_keyframe_direct(), INSERTKEY_REPLACE, INSERTKEY_XYZ2RGB, ID::name, NLATIME_CONVERT_UNMAP, NULL, PROP_COLOR, PROP_COORDS, PROP_EULER, PROP_TRANSLATION, PROP_XYZ, RNA_id_pointer_create(), RNA_path_resolve(), RNA_property_array_length(), RNA_property_subtype(), RPT_ERROR, FCurve::totvert, verify_adt_action(), and verify_fcurve().
Referenced by ANIM_apply_keyingset(), autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), insert_action_keys(), insert_graph_keys(), insert_key_button_exec(), pyrna_struct_keyframe_insert(), ui_but_anim_autokey(), and KX_BlenderSceneConverter::WritePhysicsObjectToAnimationIpo().
short insert_keyframe_direct (ReportList * reports, PointerRNA ptr, PropertyRNA * prop, FCurve * fcu, float cfra, short flag)
Definition at line 762 of file keyframing.c.
References FCurve::array_index, BKE_report(), BKE_reportf(), PointerRNA::data, delete_fcurve_key(), FCURVE_DISCRETE_VALUES, FCURVE_INT_VALUES, fcurve_is_keyframable(), FCurve::flag, PointerRNA::id, insert_vert_fcurve(), INSERTKEY_MATRIX, INSERTKEY_NEEDED, KEYNEEDED_DELNEXT, KEYNEEDED_DELPREV, new_key_needed(), NULL, PROP_FLOAT, PROP_INT, FCurve::rna_path, RNA_path_resolve(), RNA_property_type(), RPT_ERROR, setting_get_rna_value(), FCurve::totvert, visualkey_can_use(), and visualkey_get_value().
Referenced by achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), insert_key_button_exec(), and insert_keyframe().
int insert_vert_fcurve (FCurve * fcu, float x, float y, short flag)
Definition at line 298 of file keyframing.c.
References FCurve::bezt, tAnimCopybufItem::bezt, BEZT_IPO_BEZ, BEZT_IPO_CONST, BEZT_IPO_LIN, calchandles_fcurve(), BezTriple::f1, BezTriple::f2, BezTriple::f3, FCURVE_DISCRETE_VALUES, FCURVE_INT_VALUES, FCurve::flag, BezTriple::h1, BezTriple::h2, insert_bezt_fcurve(), INSERTKEY_FAST, INSERTKEY_REPLACE, BezTriple::ipo, SELECT, tAnimCopybufItem::totvert, FCurve::totvert, and BezTriple::vec.
Referenced by clean_fcurve(), graphkeys_click_insert_exec(), insert_action_keys(), insert_graph_keys(), insert_keyframe_direct(), and sample_fcurve().
static int modify_key_op_poll (bContext * C) [static]
Definition at line 1076 of file keyframing.c.
References CTX_data_scene(), CTX_wm_area(), CTX_wm_space_outliner(), ELEM, ELEM3, ELEM4, NULL, SpaceOops::outlinevis, SO_GROUPS, SO_KEYMAP, SO_LIBRARIES, SO_SEQUENCE, SO_USERDEF, and SO_VERSE_SESSION.
Referenced by ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_delete_button(), ANIM_OT_keyframe_insert(), and ANIM_OT_keyframe_insert_button().
static short new_key_needed (FCurve * fcu, float cFrame, float nValue) [static]
Definition at line 382 of file keyframing.c.
References tAnimCopybufItem::bezt, FCurve::bezt, evaluate_fcurve(), i, IS_EQF, KEYNEEDED_DELNEXT, KEYNEEDED_DELPREV, KEYNEEDED_DONTADD, KEYNEEDED_JUSTADD, NULL, tAnimCopybufItem::prev, FCurve::totvert, and BezTriple::vec.
Referenced by insert_keyframe_direct().
static short object_frame_has_keyframe (Object * ob, float frame, short filter) [static]
Definition at line 1650 of file keyframing.c.
References Object::actcol, AnimData::action, action_frame_has_keyframe(), Object::adt, ANIMFILTER_KEYS_ACTIVE, ANIMFILTER_KEYS_LOCAL, ANIMFILTER_KEYS_NOMAT, ANIMFILTER_KEYS_NOSKEY, give_current_material(), id_frame_has_keyframe(), NULL, ob_get_key(), and Object::totcol.
Referenced by id_frame_has_keyframe().
static float setting_get_rna_value (PointerRNA * ptr, PropertyRNA * prop, int index) [static]
Definition at line 488 of file keyframing.c.
References PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, RNA_property_array_length(), RNA_property_boolean_get(), RNA_property_boolean_get_index(), RNA_property_enum_get(), RNA_property_float_get(), RNA_property_float_get_index(), RNA_property_int_get(), RNA_property_int_get_index(), and RNA_property_type().
Referenced by insert_keyframe_direct(), and visualkey_get_value().
bAction* verify_adt_action (ID * id, short add) [read]
Definition at line 124 of file keyframing.c.
References AnimData::action, add_empty_action(), BKE_animdata_from_id(), BKE_id_add_animdata(), BLI_snprintf(), ID::name, and NULL.
Referenced by achannel_setting_slider_shapekey_cb(), AnimationImporter::add_bone_animation_sampled(), AnimationImporter::apply_matrix_curves(), ED_object_parent_set(), insert_keyframe(), AnimationImporter::translate_animation_OLD(), and AnimationImporter::translate_Animations().
FCurve* verify_fcurve (bAction * act, const char group[], const char rna_path[], const int array_index, short add) [read]
Definition at line 153 of file keyframing.c.
References action_groups_add_channel(), action_groups_add_new(), action_groups_find_named(), tAnimCopybufItem::array_index, FCurve::array_index, BLI_addtail(), BLI_strdupn(), bAction::curves, ELEM, FCURVE_ACTIVE, FCURVE_SELECTED, FCURVE_VISIBLE, ListBase::first, FCurve::flag, tAnimCopybufItem::grp, list_find_fcurve(), MEM_callocN(), NULL, FCurve::rna_path, and strlen().
Referenced by achannel_setting_slider_shapekey_cb(), delete_keyframe(), ED_object_parent_set(), and insert_keyframe().
static short visualkey_can_use (PointerRNA * ptr, PropertyRNA * prop) [static]
Definition at line 537 of file keyframing.c.
References CONSTRAINT_DISABLE, CONSTRAINT_TYPE_CHILDOF, CONSTRAINT_TYPE_DISTLIMIT, CONSTRAINT_TYPE_FOLLOWPATH, CONSTRAINT_TYPE_KINEMATIC, CONSTRAINT_TYPE_LOCKTRACK, CONSTRAINT_TYPE_LOCLIKE, CONSTRAINT_TYPE_LOCLIMIT, CONSTRAINT_TYPE_MINMAX, CONSTRAINT_TYPE_ROTLIKE, CONSTRAINT_TYPE_ROTLIMIT, CONSTRAINT_TYPE_TRACKTO, CONSTRAINT_TYPE_TRANSFORM, CONSTRAINT_TYPE_TRANSLIKE, bPoseChannel::constraints, Object::constraints, PointerRNA::data, ELEM, ELEM3, bConstraint::enforce, FALSE, ListBase::first, bConstraint::flag, bConstraint::next, NULL, bPoseChannel::parent, Object::parent, RNA_Object, RNA_PoseBone, RNA_property_identifier(), bConstraint::type, PointerRNA::type, VISUALKEY_LOC, VISUALKEY_NONE, and VISUALKEY_ROT.
Referenced by insert_keyframe_direct().
static float visualkey_get_value (PointerRNA * ptr, PropertyRNA * prop, int array_index) [static]
Definition at line 657 of file keyframing.c.
References angle(), tAnimCopybufItem::array_index, BONE_CONNECTED, constraint_mat_convertspace(), CONSTRAINT_SPACE_LOCAL, CONSTRAINT_SPACE_POSE, copy_m3_m4(), copy_m4_m4(), PointerRNA::data, PointerRNA::id, if(), mat3_to_quat_is_ok(), mat4_to_axis_angle(), mat4_to_eulO(), NULL, Object::obmat, RNA_Object, RNA_PoseBone, RNA_property_identifier(), Object::rotmode, setting_get_rna_value(), and PointerRNA::type.
Referenced by insert_keyframe_direct().