Blender: anim_ops.c File Reference
anim_ops.c File Reference
animation
#include <stdlib.h>
#include <math.h>
#include "BLO_sys_types.h"
#include "BLI_utildefines.h"
#include "DNA_anim_types.h"
#include "DNA_scene_types.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_sound.h"
#include "UI_view2d.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_anim_api.h"
#include "ED_screen.h"
#include "anim_intern.h"
Functions
static int change_frame_poll (bContext *C)
static void change_frame_apply (bContext *C, wmOperator *op)
static int change_frame_exec (bContext *C, wmOperator *op)
static int frame_from_event (bContext *C, wmEvent *event)
static int change_frame_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int change_frame_modal (bContext *C, wmOperator *op, wmEvent *event)
static void ANIM_OT_change_frame (wmOperatorType *ot)
static int previewrange_define_exec (bContext *C, wmOperator *op)
static void ANIM_OT_previewrange_set (wmOperatorType *ot)
static int previewrange_clear_exec (bContext *C, wmOperator *UNUSED(op))
static void ANIM_OT_previewrange_clear (wmOperatorType *ot)
void ED_operatortypes_anim (void)
void ED_keymap_anim (wmKeyConfig *keyconf)
Detailed Description
Definition in file anim_ops.c.
Function Documentation
static void ANIM_OT_change_frame (wmOperatorType * ot) [static]
Definition at line 161 of file anim_ops.c.
References change_frame_exec(), change_frame_invoke(), change_frame_modal(), change_frame_poll(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MAXFRAME, MINAFRAME, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_anim().
static void ANIM_OT_previewrange_clear (wmOperatorType * ot) [static]
Definition at line 264 of file anim_ops.c.
References wmOperatorType::description, ED_operator_animview_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and previewrange_clear_exec().
Referenced by ED_operatortypes_anim().
static void ANIM_OT_previewrange_set (wmOperatorType * ot) [static]
Definition at line 216 of file anim_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_animview_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, previewrange_define_exec(), RNA_def_int(), wmOperatorType::srna, WM_border_select_cancel(), WM_border_select_invoke(), and WM_border_select_modal().
Referenced by ED_operatortypes_anim().
static void change_frame_apply (bContext * C, wmOperator * op) [static]
Definition at line 78 of file anim_ops.c.
References CFRA, CTX_data_main(), CTX_data_scene(), FRAMENUMBER_MIN_CLAMP, NC_SCENE, ND_FRAME, wmOperator::ptr, RNA_int_get(), sound_seek_scene(), SUBFRA, and WM_event_add_notifier().
Referenced by change_frame_exec(), change_frame_invoke(), and change_frame_modal().
static int change_frame_exec (bContext * C, wmOperator * op) [static]
Definition at line 96 of file anim_ops.c.
References change_frame_apply(), and OPERATOR_FINISHED.
Referenced by ANIM_OT_change_frame().
static int change_frame_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 119 of file anim_ops.c.
References change_frame_apply(), frame_from_event(), OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_int_set(), and WM_event_add_modal_handler().
Referenced by ANIM_OT_change_frame().
static int change_frame_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 136 of file anim_ops.c.
References change_frame_apply(), ESCKEY, frame_from_event(), KM_RELEASE, LEFTMOUSE, MOUSEMOVE, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RIGHTMOUSE, RNA_int_set(), wmEvent::type, and wmEvent::val.
Referenced by ANIM_OT_change_frame().
static int change_frame_poll (bContext * C) [static]
Definition at line 63 of file anim_ops.c.
References CTX_wm_area(), G, SPACE_IPO, and ScrArea::spacetype.
Referenced by ANIM_OT_change_frame().
void ED_keymap_anim (wmKeyConfig * keyconf)
Definition at line 316 of file anim_ops.c.
References ACTIONMOUSE, KM_ALT, KM_CTRL, KM_PRESS, PKEY, wmKeyMapItem::ptr, RNA_string_set(), TKEY, WM_keymap_add_item(), WM_keymap_find(), and WM_keymap_verify_item().
Referenced by ED_spacetypes_keymap().
void ED_operatortypes_anim (void)
Definition at line 282 of file anim_ops.c.
References ANIM_OT_change_frame(), ANIM_OT_copy_driver_button(), ANIM_OT_driver_button_add(), ANIM_OT_driver_button_remove(), ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_delete_button(), ANIM_OT_keyframe_delete_v3d(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_button(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_active_set(), ANIM_OT_keying_set_add(), ANIM_OT_keying_set_path_add(), ANIM_OT_keying_set_path_remove(), ANIM_OT_keying_set_remove(), ANIM_OT_keyingset_button_add(), ANIM_OT_keyingset_button_remove(), ANIM_OT_paste_driver_button(), ANIM_OT_previewrange_clear(), ANIM_OT_previewrange_set(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
static int frame_from_event (bContext * C, wmEvent * event) [static]
Definition at line 106 of file anim_ops.c.
References CTX_wm_region(), wmEvent::mval, NULL, UI_view2d_region_to_view(), and ARegion::v2d.
Referenced by change_frame_invoke(), and change_frame_modal().
static int previewrange_clear_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 245 of file anim_ops.c.
References CTX_data_scene(), CTX_wm_area(), ED_area_tag_redraw(), ELEM, RenderData::flag, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, RenderData::pefra, RenderData::psfra, Scene::r, and SCER_PRV_RANGE.
Referenced by ANIM_OT_previewrange_clear().
static int previewrange_define_exec (bContext * C, wmOperator * op) [static]
Definition at line 183 of file anim_ops.c.
References CTX_data_scene(), CTX_wm_region(), RenderData::flag, FRAMENUMBER_MIN_CLAMP, NC_SCENE, ND_FRAME, NULL, OPERATOR_FINISHED, RenderData::pefra, RenderData::psfra, wmOperator::ptr, Scene::r, RNA_int_get(), SCER_PRV_RANGE, UI_view2d_region_to_view(), ARegion::v2d, and WM_event_add_notifier().
Referenced by ANIM_OT_previewrange_set().