Blender: math_base_inline.c File Reference
math_base_inline.c File Reference
blenlib
#include <float.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "BLI_math.h"
Defines
#define __MATH_BASE_INLINE_C__
#define SMALL_NUMBER 1.e-8f
Functions
MINLINE float sqrt3f (float f)
MINLINE double sqrt3d (double d)
MINLINE float saacos (float fac)
MINLINE float saasin (float fac)
MINLINE float sasqrt (float fac)
MINLINE float saacosf (float fac)
MINLINE float saasinf (float fac)
MINLINE float sasqrtf (float fac)
MINLINE float interpf (float target, float origin, float fac)
MINLINE float shell_angle_to_dist (const float angle)
MINLINE float power_of_2 (float val)
MINLINE int is_power_of_2_i (int n)
MINLINE int power_of_2_max_i (int n)
MINLINE int power_of_2_min_i (int n)
MINLINE float minf (float a, float b)
MINLINE float maxf (float a, float b)
MINLINE float signf (float f)
Detailed Description
Definition in file math_base_inline.c.
Define Documentation
#define __MATH_BASE_INLINE_C__
Definition at line 39 of file math_base_inline.c.
#define SMALL_NUMBER 1.e-8f
Definition at line 42 of file math_base_inline.c.
Referenced by fcurve_eval_keyframes(), and shell_angle_to_dist().
Function Documentation
MINLINE float interpf (float target, float origin, float fac)
Definition at line 98 of file math_base_inline.c.
Referenced by evaluate_time_fmodifiers(), evaluate_value_fmodifiers(), fcurve_eval_samples(), update_reports_display_invoke(), and weight_set_exec().
MINLINE int is_power_of_2_i (int n)
Definition at line 118 of file math_base_inline.c.
Referenced by findBitIndex(), BL_Texture::GetPow2(), GPU_paint_update_image(), BL_Texture::InitCubeMap(), is_pow2_limit(), power_of_2_max_i(), power_of_2_min_i(), and split_width().
MINLINE float maxf (float a, float b)
Definition at line 147 of file math_base_inline.c.
Referenced by brush_edit_apply(), do_displace(), draw_bgpic(), heat_set_H(), isect_seg_seg_v2_point(), lamp_get_visibility(), render_lighting_halo(), and svd_m4().
MINLINE float minf (float a, float b)
Definition at line 142 of file math_base_inline.c.
Referenced by applyModifier(), bmo_dissolve_limit_exec(), calc_corner_co(), check_zone(), do_material_tex(), gjkepa2_impl::EPA::findbest(), isect_seg_seg_v2_point(), scanfill(), and svd_m4().
MINLINE float power_of_2 (float val)
Definition at line 113 of file math_base_inline.c.
References log(), M_LN2, and pow().
Referenced by ED_clip_view_selection(), image_view_all_exec(), sequencer_view_all_preview_exec(), and view_all_exec().
MINLINE int power_of_2_max_i (int n)
Definition at line 123 of file math_base_inline.c.
References is_power_of_2_i().
Referenced by checker_board_color_fill(), draw_volume(), GPU_texture_create_3D(), GPU_texture_create_nD(), and split_width().
MINLINE int power_of_2_min_i (int n)
Definition at line 134 of file math_base_inline.c.
References is_power_of_2_i().
Referenced by BL_Texture::GetPow2(), smaller_pow2_limit(), and split_width().
MINLINE float saacos (float fac)
Definition at line 58 of file math_base_inline.c.
References acos(), and M_PI.
Referenced by accumulate_vertex_normals(), accumulate_vertex_normals_poly(), add_render_lamp(), applyModifier(), applyTranslation(), basic_rotate(), Blinn_Spec(), BM_mesh_normals_update(), BM_vert_normal_update(), boid_body(), cache_key_incremental_rotation(), calc_bevel_sin_cos(), costAngle(), do_guides(), do_sky_tex(), draw_manipulator_rotate(), dvar_eval_rotDiff(), effector_falloff(), gpu_lamp_from_blender(), InputAngle(), lasso_inside(), makeshadowbuf(), map_to_sphere(), mat3_to_quat_is_ok(), mul_fac_qt_fl(), OrenNayar_Diff(), particle_billboard(), poly_rotate_plane(), psys_thread_create_path(), Quaternion_angle_get(), screen_aligned(), set_phong_threshold(), speedvector_project(), spotvolume(), Toon_Diff(), Toon_Spec(), tri_to_quat(), vec_to_quat(), Vector_angle(), and WardIso_Spec().
MINLINE float saacosf (float fac)
Definition at line 78 of file math_base_inline.c.
References acosf, and M_PI.
Referenced by ff_quad_form_factor(), and occ_quad_form_factor().
MINLINE float saasin (float fac)
Definition at line 65 of file math_base_inline.c.
References KDL::asin(), and M_PI.
Referenced by angle_normalized_v2v2(), and angle_normalized_v3v3().
MINLINE float saasinf (float fac)
Definition at line 85 of file math_base_inline.c.
References asinf, and M_PI.
MINLINE float sasqrt (float fac)
Definition at line 72 of file math_base_inline.c.
References sqrt().
Referenced by Blinn_Spec(), boid_body(), boid_brain(), CookTorr_Spec(), Phong_Spec(), shadeHaloFloat(), shrinkwrap_calc_nearest_surface_point(), shrinkwrap_calc_nearest_vertex(), Toon_Spec(), and WardIso_Spec().
MINLINE float sasqrtf (float fac)
Definition at line 92 of file math_base_inline.c.
References sqrtf.
MINLINE float shell_angle_to_dist (const float angle)
Definition at line 107 of file math_base_inline.c.
References cosf, fabsf, and SMALL_NUMBER.
Referenced by applyModifier(), BM_vert_calc_shell_factor(), bmo_inset_exec(), calc_corner_co(), solidify_add_thickness(), and uv_image_outset().
MINLINE float signf (float f)
Definition at line 152 of file math_base_inline.c.
MINLINE double sqrt3d (double d)
Definition at line 51 of file math_base_inline.c.
References KDL::exp(), and log().
Referenced by findzero().
MINLINE float sqrt3f (float f)
Definition at line 44 of file math_base_inline.c.
References KDL::exp(), and log().
Referenced by ui_numedit_but_HSVCIRCLE().