Blender: bmo_triangulate.c File Reference
bmo_triangulate.c File Reference
#include "MEM_guardedalloc.h"
#include "DNA_listBase.h"
#include "BLI_math.h"
#include "BLI_array.h"
#include "BLI_smallhash.h"
#include "BLI_scanfill.h"
#include "bmesh.h"
#include "intern/bmesh_private.h"
#include "intern/bmesh_operators_private.h"
Defines
#define EDGE_NEW 1
#define FACE_NEW 1
#define ELE_NEW 1
#define FACE_MARK 2
#define EDGE_MARK 4
Functions
void bmo_triangulate_exec (BMesh *bm, BMOperator *op)
void bmo_beautify_fill_exec (BMesh *bm, BMOperator *op)
void bmo_triangle_fill_exec (BMesh *bm, BMOperator *op)
Define Documentation
#define EDGE_MARK 4
Definition at line 45 of file bmo_triangulate.c.
Referenced by bmo_beautify_fill_exec(), and bmo_triangle_fill_exec().
#define EDGE_NEW 1
Definition at line 40 of file bmo_triangulate.c.
Referenced by bmo_triangulate_exec().
#define ELE_NEW 1
Definition at line 43 of file bmo_triangulate.c.
Referenced by bmo_beautify_fill_exec(), and bmo_triangle_fill_exec().
#define FACE_MARK 2
Definition at line 44 of file bmo_triangulate.c.
Referenced by bmo_beautify_fill_exec().
#define FACE_NEW 1
Definition at line 41 of file bmo_triangulate.c.
Referenced by bmo_triangulate_exec().
Function Documentation
void bmo_beautify_fill_exec (BMesh * bm, BMOperator * op)
Definition at line 82 of file bmo_triangulate.c.
References area_tri_v3(), BM_EDGE, BM_edge_is_manifold(), BM_edge_rotate(), BM_EDGEROT_CHECK_EXISTS, BM_EDGES_OF_MESH, BM_FACE, BM_ITER_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMVert::co, EDGE_MARK, ELE_NEW, BMLoop::f, FACE_MARK, FALSE, is_quad_convex_v3(), BMEdge::l, BMFace::len, len_v3v3(), BMLoop::next, BMLoop::prev, BMLoop::radial_next, and BMLoop::v.
void bmo_triangle_fill_exec (BMesh * bm, BMOperator * op)
Definition at line 158 of file bmo_triangulate.c.
References BLI_addfilledge(), BLI_addfillvert(), BLI_begin_edgefill(), BLI_edgefill(), BLI_end_edgefill(), BLI_smallhash_haskey(), BLI_smallhash_init(), BLI_smallhash_insert(), BLI_smallhash_lookup(), BLI_smallhash_release(), BM_EDGE, BM_FACE, BM_face_create_quad_tri(), BM_ITER_ELEM, BM_LOOPS_OF_FACE, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMVert::co, BMLoop::e, EDGE_MARK, ELE_NEW, FALSE, ScanFillContext::fillfacebase, ListBase::first, hash, ScanFillFace::next, NULL, ScanFillVert::p, ScanFillVert::tmp, TRUE, BMEdge::v1, ScanFillFace::v1, BMEdge::v2, ScanFillFace::v2, and ScanFillFace::v3.
void bmo_triangulate_exec (BMesh * bm, BMOperator * op)
Definition at line 47 of file bmo_triangulate.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BM_EDGE, BM_FACE, BM_face_triangulate(), BMO_iter_new(), BMO_iter_step(), BMO_slot_bool_get(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_map_ptr_insert(), EDGE_NEW, FACE_NEW, i, BMFace::len, and NULL.