Blender: FilterBase Class Reference
FilterBase Class Reference
base class for pixel filters
#include <FilterBase.h>
Public Member Functions
FilterBase (void)
constructor
virtual ~FilterBase (void)
destructor
virtual void release (void)
template<class SRC >
unsigned int convert (SRC src, short x, short y, short *size, unsigned int pixSize)
convert pixel
PyFilter * getPrevious (void)
get previous filter
void setPrevious (PyFilter *filt, bool useRefCnt=true)
set previous filter
FilterBase * findFirst (void)
find first filter in chain
unsigned int firstPixelSize (void)
get first filter's source pixel size
Protected Member Functions
virtual unsigned int filter (unsigned char *src, short x, short y, short *size, unsigned int pixSize, unsigned int val=0)
filter pixel, source byte buffer
virtual unsigned int filter (unsigned int *src, short x, short y, short *size, unsigned int pixSize, unsigned int val=0)
filter pixel, source int buffer
virtual unsigned int getPixelSize (void)
get source pixel size
template<class SRC >
unsigned int convertPrevious (SRC src, short x, short y, short *size, unsigned int pixSize)
get converted pixel from previous filters
Protected Attributes
PyFilter * m_previous
previous pixel filter
Detailed Description
base class for pixel filters
Definition at line 57 of file FilterBase.h.
Constructor & Destructor Documentation
FilterBase::FilterBase (void)
constructor
Definition at line 37 of file FilterBase.cpp.
FilterBase::~FilterBase (void) [virtual]
destructor
Definition at line 41 of file FilterBase.cpp.
References release().
Member Function Documentation
template<class SRC > unsigned int FilterBase::convert (SRC src, short x, short y, short * size, unsigned int pixSize) [inline]
convert pixel
Definition at line 68 of file FilterBase.h.
References convertPrevious(), and filter().
Referenced by convertPrevious().
template<class SRC > unsigned int FilterBase::convertPrevious (SRC src, short x, short y, short * size, unsigned int pixSize) [inline, protected]
get converted pixel from previous filters
Definition at line 103 of file FilterBase.h.
References convert(), PyFilter::m_filter, m_previous, and NULL.
Referenced by convert(), and FilterNormal::tFilter().
virtual unsigned int FilterBase::filter (unsigned int * src, short x, short y, short * size, unsigned int pixSize, unsigned int val = 0) [inline, protected, virtual]
filter pixel, source int buffer
Reimplemented in FilterBlueScreen, FilterGray, FilterColor, FilterLevel, FilterNormal, and FilterImageMix.
Definition at line 95 of file FilterBase.h.
virtual unsigned int FilterBase::filter (unsigned char * src, short x, short y, short * size, unsigned int pixSize, unsigned int val = 0) [inline, protected, virtual]
filter pixel, source byte buffer
Reimplemented in FilterBlueScreen, FilterGray, FilterColor, FilterLevel, FilterNormal, FilterRGB24, FilterRGBA32, FilterBGR24, and FilterYV12.
Definition at line 91 of file FilterBase.h.
Referenced by convert().
FilterBase * FilterBase::findFirst (void)
find first filter in chain
Definition at line 73 of file FilterBase.cpp.
References PyFilter::m_filter, m_previous, and NULL.
Referenced by ImageBase::filterImage(), and firstPixelSize().
unsigned int FilterBase::firstPixelSize (void) [inline]
get first filter's source pixel size
Definition at line 84 of file FilterBase.h.
References findFirst(), and getPixelSize().
Referenced by load().
virtual unsigned int FilterBase::getPixelSize (void) [inline, protected, virtual]
get source pixel size
Reimplemented in FilterRGB24, FilterRGBA32, FilterBGR24, and FilterYV12.
Definition at line 100 of file FilterBase.h.
Referenced by firstPixelSize().
PyFilter* FilterBase::getPrevious (void) [inline]
get previous filter
Definition at line 76 of file FilterBase.h.
References m_previous.
void FilterBase::release (void) [virtual]
Definition at line 49 of file FilterBase.cpp.
References NULL, and setPrevious().
Referenced by ~FilterBase().
void FilterBase::setPrevious (PyFilter * filt, bool useRefCnt = true)
set previous filter
Definition at line 57 of file FilterBase.cpp.
References m_previous, and NULL.
Referenced by ImageBase::filterImage(), and release().
Member Data Documentation
PyFilter* FilterBase::m_previous [protected]
previous pixel filter
Definition at line 88 of file FilterBase.h.
Referenced by convertPrevious(), findFirst(), getPrevious(), and setPrevious().
The documentation for this class was generated from the following files:
FilterBase.h
FilterBase.cpp