Blender: node_templates.c File Reference
node_templates.c File Reference
interface
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_node_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "BLI_listbase.h"
#include "BLI_string.h"
#include "BLI_utildefines.h"
#include "BLF_translation.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_node.h"
#include "BKE_scene.h"
#include "RNA_access.h"
#include "NOD_socket.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "../interface/interface_intern.h"
#include "ED_node.h"
#include "ED_util.h"
Classes
struct NodeLinkArg
Defines
#define UI_NODE_LINK_ADD 0
#define UI_NODE_LINK_DISCONNECT -1
#define UI_NODE_LINK_REMOVE -2
Typedefs
typedef struct NodeLinkArg NodeLinkArg
Functions
static void node_tag_recursive (bNode *node)
static void node_clear_recursive (bNode *node)
static void node_remove_linked (bNodeTree *ntree, bNode *rem_node)
static void node_socket_disconnect (Main *bmain, bNodeTree *ntree, bNode *node_to, bNodeSocket *sock_to)
static void node_socket_remove (Main *bmain, bNodeTree *ntree, bNode *node_to, bNodeSocket *sock_to)
static void node_socket_add_replace (Main *bmain, bNodeTree *ntree, bNode *node_to, bNodeSocket *sock_to, bNodeTemplate *ntemp, int sock_num)
static void ui_node_link (bContext *C, void *arg_p, void *event_p)
static void ui_node_sock_name (bNodeSocket *sock, char name[UI_MAX_NAME_STR])
static int ui_compatible_sockets (int typeA, int typeB)
static void ui_node_menu_column (NodeLinkArg *arg, int nclass, const char *cname)
static void node_menu_column_foreach_cb (void *calldata, int nclass, const char *name)
static void ui_template_node_link_menu (bContext *C, uiLayout *layout, void *but_p)
void uiTemplateNodeLink (uiLayout *layout, bNodeTree *ntree, bNode *node, bNodeSocket *sock)
static void ui_node_draw_input (uiLayout *layout, bContext *C, bNodeTree *ntree, bNode *node, bNodeSocket *input, int depth)
static void ui_node_draw_node (uiLayout *layout, bContext *C, bNodeTree *ntree, bNode *node, int depth)
void uiTemplateNodeView (uiLayout *layout, bContext *C, bNodeTree *ntree, bNode *node, bNodeSocket *input)
Detailed Description
Definition in file node_templates.c.
Define Documentation
#define UI_NODE_LINK_ADD 0
Definition at line 239 of file node_templates.c.
#define UI_NODE_LINK_DISCONNECT -1
Definition at line 240 of file node_templates.c.
Referenced by ui_node_link(), and ui_template_node_link_menu().
#define UI_NODE_LINK_REMOVE -2
Definition at line 241 of file node_templates.c.
Referenced by ui_node_link(), and ui_template_node_link_menu().
Typedef Documentation
typedef struct NodeLinkArg NodeLinkArg
Function Documentation
static void node_clear_recursive (bNode * node) [static]
Definition at line 80 of file node_templates.c.
References ListBase::first, bNode::flag, bNodeLink::fromnode, bNode::inputs, bNodeSocket::link, bNodeSocket::next, and NODE_TEST.
Referenced by node_remove_linked().
static void node_menu_column_foreach_cb (void * calldata, int nclass, const char * name) [static]
Definition at line 447 of file node_templates.c.
References ELEM, NODE_CLASS_GROUP, NODE_CLASS_LAYOUT, and ui_node_menu_column().
Referenced by ui_template_node_link_menu().
static void node_remove_linked (bNodeTree * ntree, bNode * rem_node) [static]
Definition at line 94 of file node_templates.c.
References ListBase::first, bNode::flag, bNodeLink::fromnode, bNode::id, bNode::inputs, bNodeSocket::link, bNodeSocket::next, bNode::next, next, node_clear_recursive(), node_tag_recursive(), NODE_TEST, nodeFreeNode(), bNodeTree::nodes, and ID::us.
Referenced by node_socket_add_replace(), and node_socket_remove().
static void node_socket_add_replace (Main * bmain, bNodeTree * ntree, bNode * node_to, bNodeSocket * sock_to, bNodeTemplate * ntemp, int sock_num) [static]
Definition at line 156 of file node_templates.c.
References BLI_findlink(), bNodeSocket::default_value, ED_node_generic_update(), ListBase::first, bNodeType::flag, bNodeLink::fromnode, bNodeLink::fromsock, bNodeTree::id, bNode::id, id_us_plus(), bNode::inputs, bNodeSocket::limit, link(), bNodeSocket::link, bNode::locx, bNode::locy, bNodeSocket::name, bNodeType::nclass, bNodeSocket::next, bNode::next, bNodeTemplate::ngroup, NODE_CLASS_TEXTURE, NODE_GROUP, NODE_OPTIONS, node_remove_linked(), node_socket_copy_default_value(), node_socket_free_default_value(), node_socket_make_default_value(), nodeAddLink(), nodeAddNode(), nodeCountSocketLinks(), nodeRemLink(), bNodeTree::nodes, nodeSetActive(), nodeUpdate(), ntreeUpdateTree(), NULL, bNode::outputs, bNode::storage, bNodeSocket::type, bNodeTemplate::type, bNode::type, bNode::typeinfo, and bNodeType::width.
Referenced by ui_node_link().
static void node_socket_disconnect (Main * bmain, bNodeTree * ntree, bNode * node_to, bNodeSocket * sock_to) [static]
Definition at line 128 of file node_templates.c.
References ED_node_generic_update(), bNodeSocket::link, nodeRemLink(), nodeUpdate(), and ntreeUpdateTree().
Referenced by ui_node_link().
static void node_socket_remove (Main * bmain, bNodeTree * ntree, bNode * node_to, bNodeSocket * sock_to) [static]
Definition at line 142 of file node_templates.c.
References ED_node_generic_update(), bNodeLink::fromnode, bNodeSocket::link, node_remove_linked(), nodeUpdate(), and ntreeUpdateTree().
Referenced by ui_node_link().
static void node_tag_recursive (bNode * node) [static]
Definition at line 66 of file node_templates.c.
References ListBase::first, bNode::flag, bNodeLink::fromnode, bNode::inputs, bNodeSocket::link, bNodeSocket::next, and NODE_TEST.
Referenced by node_remove_linked().
static int ui_compatible_sockets (int typeA, int typeB) [static]
Definition at line 310 of file node_templates.c.
Referenced by ui_node_menu_column().
static void ui_node_draw_input (uiLayout * layout, bContext * C, bNodeTree * ntree, bNode * node, bNodeSocket * input, int depth) [static]
Definition at line 556 of file node_templates.c.
References BLI_snprintf(), uiBlock::buttons, ListBase::first, uiBut::flag, bNode::flag, bNodeSocket::flag, bNodeLink::fromnode, bNodeTree::id, bNode::inputs, label(), ListBase::last, bNodeSocket::link, bNodeSocket::name, NODE_GROUP, NODE_TEST, NULL, RNA_NodeSocket, RNA_pointer_create(), SOCK_COLLAPSED, SOCK_HIDE_VALUE, SOCK_SHADER, SOCK_UNAVAIL, SOCK_VECTOR, split(), bNodeSocket::type, bNode::type, bNode::typeinfo, UI_EMBOSS, UI_EMBOSSN, UI_ITEM_R_ICON_ONLY, UI_MAX_NAME_STR, ui_node_draw_node(), UI_TEXT_LEFT, UI_UNIT_X, uiBlockSetEmboss(), bNodeType::uifunc, uiItemL(), uiItemR(), uiItemS(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), uiLayoutSplit(), uiTemplateNodeLink(), and uiBut::x2.
Referenced by ui_node_draw_node(), and uiTemplateNodeView().
static void ui_node_draw_node (uiLayout * layout, bContext * C, bNodeTree * ntree, bNode * node, int depth) [static]
Definition at line 534 of file node_templates.c.
References ListBase::first, bNodeTree::id, bNode::inputs, bNodeSocket::next, NODE_GROUP, RNA_Node, RNA_pointer_create(), split(), bNode::type, bNode::typeinfo, ui_node_draw_input(), bNodeType::uifunc, uiLayoutColumn(), and uiLayoutSplit().
Referenced by ui_node_draw_input(), and uiTemplateNodeView().
static void ui_node_link (bContext * C, void * arg_p, void * event_p) [static]
Definition at line 257 of file node_templates.c.
References NodeLinkArg::bmain, CTX_data_main(), CTX_data_scene(), ED_undo_push(), GET_INT_FROM_POINTER, bNodeTemplate::main, NodeLinkArg::ngroup, bNodeTemplate::ngroup, NodeLinkArg::node, node_socket_add_replace(), node_socket_disconnect(), node_socket_remove(), NodeLinkArg::ntree, NodeLinkArg::output, bNodeTemplate::scene, NodeLinkArg::sock, NodeLinkArg::type, bNodeTemplate::type, UI_NODE_LINK_DISCONNECT, and UI_NODE_LINK_REMOVE.
Referenced by ui_node_menu_column(), and ui_template_node_link_menu().
static void ui_node_menu_column (NodeLinkArg * arg, int nclass, const char * cname) [static]
Definition at line 315 of file node_templates.c.
References BLI_snprintf(), BLI_strncpy(), NodeLinkArg::bmain, BUT, uiBlock::buttons, bNodeType::compatibility, ListBase::first, uiBut::flag, i, bNodeTree::id, bNodeTree::inputs, ListBase::last, NodeLinkArg::layout, MEM_dupallocN(), bNodeSocket::name, bNodeType::name, ID::name, bNodeSocketTemplate::name, bNodeType::nclass, bNodeSocket::next, bNodeType::next, ID::next, NodeLinkArg::ngroup, NODE_CLASS_GROUP, NODE_GROUP, NODE_NEW_SHADING, NODE_OLD_SHADING, bNodeTreeType::node_types, Main::nodetree, NodeLinkArg::ntree, NTREE_SHADER, ntreeGetType(), NULL, NodeLinkArg::output, bNodeTree::outputs, bNodeType::outputs, NodeLinkArg::scene, scene_use_new_shading_nodes(), NodeLinkArg::sock, bNodeSocketTemplate::type, bNodeTree::type, bNodeSocket::type, NodeLinkArg::type, bNodeType::type, ui_compatible_sockets(), UI_MAX_NAME_STR, ui_node_link(), UI_TEXT_LEFT, UI_UNIT_X, UI_UNIT_Y, uiBlockSetCurLayout(), uiButSetNFunc(), uiDefBut(), uiItemL(), uiLayoutColumn(), and uiLayoutGetBlock().
Referenced by node_menu_column_foreach_cb(), and ui_template_node_link_menu().
static void ui_node_sock_name (bNodeSocket * sock, char name[UI_MAX_NAME_STR]) [static]
Definition at line 282 of file node_templates.c.
References BLI_snprintf(), BLI_strncpy(), ListBase::first, bNodeType::flag, bNodeLink::fromnode, bNodeLink::fromsock, bNode::id, bNode::inputs, ListBase::last, bNodeSocket::link, bNodeSocket::name, bNodeType::name, ID::name, NODE_GROUP, NODE_OPTIONS, NULL, bNode::outputs, SOCK_SHADER, bNodeSocket::type, bNode::type, bNode::typeinfo, and UI_MAX_NAME_STR.
Referenced by uiTemplateNodeLink().
static void ui_template_node_link_menu (bContext * C, uiLayout * layout, void * but_p) [static]
Definition at line 455 of file node_templates.c.
References NodeLinkArg::bmain, BUT, uiBlock::buttons, CTX_data_main(), CTX_data_scene(), uiBut::flag, uiBut::func_argN, IFACE_, ListBase::last, NodeLinkArg::layout, MEM_dupallocN(), NODE_CLASS_GROUP, node_menu_column_foreach_cb(), NodeLinkArg::ntree, ntreeGetType(), NULL, NodeLinkArg::scene, SET_INT_IN_POINTER, NodeLinkArg::sock, split(), bNodeTree::type, ui_node_link(), UI_NODE_LINK_DISCONNECT, UI_NODE_LINK_REMOVE, ui_node_menu_column(), UI_TEXT_LEFT, UI_UNIT_X, UI_UNIT_Y, uiBlockSetCurLayout(), uiButSetNFunc(), uiDefBut(), uiItemL(), uiLayoutColumn(), uiLayoutGetBlock(), and uiLayoutSplit().
Referenced by uiTemplateNodeLink().
void uiTemplateNodeLink (uiLayout * layout, bNodeTree * ntree, bNode * node, bNodeSocket * sock)
Definition at line 496 of file node_templates.c.
References bNode::flag, uiBut::flag, bNodeSocket::flag, bNodeLink::fromnode, uiBut::func_argN, bNodeSocket::link, MEM_callocN(), MENU, NodeLinkArg::node, NODE_ACTIVE_TEXTURE, NodeLinkArg::ntree, NULL, NodeLinkArg::output, uiBut::poin, NodeLinkArg::sock, SOCK_HIDE_VALUE, SOCK_SHADER, uiBut::type, bNodeSocket::type, NodeLinkArg::type, UI_BUT_NODE_ACTIVE, UI_BUT_NODE_LINK, UI_MAX_NAME_STR, ui_node_sock_name(), ui_template_node_link_menu(), UI_TEXT_LEFT, UI_UNIT_X, UI_UNIT_Y, uiBlockSetCurLayout(), uiDefIconMenuBut(), uiDefMenuBut(), and uiLayoutGetBlock().
Referenced by node_sockets_panel(), and ui_node_draw_input().
void uiTemplateNodeView (uiLayout * layout, bContext * C, bNodeTree * ntree, bNode * node, bNodeSocket * input)
Definition at line 650 of file node_templates.c.
References ListBase::first, bNode::flag, bNode::next, NODE_TEST, bNodeTree::nodes, ui_node_draw_input(), and ui_node_draw_node().