Blender: filelist.h File Reference
filelist.h File Reference
fileselector
Typedefs
typedef enum FileSelType FileSelType
typedef enum FileCheckType FileCheckType
Enumerations
enum FileSelType { FILE_SEL_REMOVE = 0, FILE_SEL_ADD = 1, FILE_SEL_TOGGLE = 2 }
enum FileCheckType { CHECK_DIRS = 1, CHECK_FILES = 2, CHECK_ALL = 3 }
Functions
struct FileList * filelist_new (short type)
void filelist_init_icons (void)
void filelist_free_icons (void)
int filelist_find (struct FileList *filelist, const char *file)
void filelist_free (struct FileList *filelist)
void filelist_sort (struct FileList *filelist, short sort)
int filelist_numfiles (struct FileList *filelist)
const char * filelist_dir (struct FileList *filelist)
void filelist_setdir (struct FileList *filelist, const char *dir)
struct direntry * filelist_file (struct FileList *filelist, int index)
void filelist_select (struct FileList *filelist, FileSelection *sel, FileSelType select, unsigned int flag, FileCheckType check)
void filelist_select_file (struct FileList *filelist, int index, FileSelType select, unsigned int flag, FileCheckType check)
int filelist_is_selected (struct FileList *filelist, int index, FileCheckType check)
void filelist_hidedot (struct FileList *filelist, short hide)
void filelist_setfilter (struct FileList *filelist, unsigned int filter)
void filelist_setfilter_types (struct FileList *filelist, const char *filter_glob)
void filelist_filter (struct FileList *filelist)
void filelist_imgsize (struct FileList *filelist, short w, short h)
struct ImBuf * filelist_getimage (struct FileList *filelist, int index)
struct ImBuf * filelist_geticon (struct FileList *filelist, int index)
short filelist_changed (struct FileList *filelist)
void filelist_readdir (struct FileList *filelist)
int filelist_empty (struct FileList *filelist)
void filelist_parent (struct FileList *filelist)
struct BlendHandle * filelist_lib (struct FileList *filelist)
int filelist_islibrary (struct FileList *filelist, char *dir, char *group)
void filelist_from_main (struct FileList *filelist)
void filelist_from_library (struct FileList *filelist)
void filelist_freelib (struct FileList *filelist)
void filelist_hideparent (struct FileList *filelist, short hide)
struct ListBase * folderlist_new (void)
void folderlist_free (struct ListBase *folderlist)
struct ListBase * folderlist_duplicate (ListBase *folderlist)
void folderlist_popdir (struct ListBase *folderlist, char *dir)
void folderlist_pushdir (struct ListBase *folderlist, const char *dir)
int folderlist_clear_next (struct SpaceFile *sfile)
void thumbnails_stop (struct FileList *filelist, const struct bContext *C)
void thumbnails_start (struct FileList *filelist, const struct bContext *C)
int thumbnails_running (struct FileList *filelist, const struct bContext *C)
Detailed Description
Definition in file filelist.h.
Typedef Documentation
typedef enum FileCheckType FileCheckType
typedef enum FileSelType FileSelType
Enumeration Type Documentation
enum FileCheckType
Enumerator:
CHECK_DIRS
CHECK_FILES
CHECK_ALL
Definition at line 56 of file filelist.h.
enum FileSelType
Enumerator:
FILE_SEL_REMOVE
FILE_SEL_ADD
FILE_SEL_TOGGLE
Definition at line 50 of file filelist.h.
Function Documentation
short filelist_changed (struct FileList * filelist)
Definition at line 612 of file filelist.c.
References FileList::changed.
const char* filelist_dir (struct FileList * filelist)
Definition at line 596 of file filelist.c.
References FileList::dir.
Referenced by file_change_dir(), and file_refresh().
int filelist_empty (struct FileList * filelist)
Definition at line 910 of file filelist.c.
References FileList::filelist, and NULL.
Referenced by file_main_area_draw(), and file_refresh().
struct direntry* filelist_file (struct FileList * filelist, int index) [read]
Definition at line 680 of file filelist.c.
References FileList::fidx, FileList::filelist, NULL, and FileList::numfiltered.
Referenced by autocomplete_file(), column_widths(), file_delete_exec(), file_delete_poll(), file_draw_list(), file_refresh(), file_rename_exec(), file_select_do(), file_select_match(), file_sfile_to_operator(), filelist_is_selected(), and filelist_select_file().
void filelist_filter (struct FileList * filelist)
Definition at line 352 of file filelist.c.
References FileList::dir, FileList::fidx, FileList::filelist, FileList::filter, FileList::filterf, FileList::hide_dot, i, MEM_callocN(), MEM_freeN(), NULL, FileList::numfiles, and FileList::numfiltered.
Referenced by file_refresh(), filelist_from_library(), filelist_from_main(), filelist_read_dir(), and filelist_sort().
int filelist_find (struct FileList * filelist, const char * file)
Definition at line 692 of file filelist.c.
References FileList::fidx, FileList::filelist, i, FileList::numfiles, FileList::numfiltered, and direntry::relname.
Referenced by file_refresh().
void filelist_free (struct FileList * filelist)
Definition at line 541 of file filelist.c.
References FileList::fidx, FileList::filelist, FileList::filter, FileList::filter_glob, FileList::hide_dot, i, direntry::image, IMB_freeImBuf(), MEM_freeN(), NULL, FileList::numfiles, FileList::numfiltered, direntry::path, direntry::relname, and direntry::string.
Referenced by ED_fileselect_clear(), and file_free().
void filelist_free_icons (void)
Definition at line 410 of file filelist.c.
References i, IMB_freeImBuf(), NULL, and SPECIAL_IMG_MAX.
Referenced by ED_file_exit().
void filelist_freelib (struct FileList * filelist)
Definition at line 579 of file filelist.c.
References BLO_blendhandle_close(), FileList::libfiledata, and NULL.
Referenced by ED_fileselect_clear(), and file_free().
void filelist_from_library (struct FileList * filelist)
Definition at line 1021 of file filelist.c.
References BKE_previewimg_freefunc(), BLI_linklist_free(), BLI_linklist_length(), BLI_strdup(), BLI_strncpy(), BLO_blendhandle_close(), BLO_blendhandle_from_file(), BLO_blendhandle_get_datablock_names(), BLO_blendhandle_get_linkable_groups(), BLO_blendhandle_get_previews(), FILE_MAX, FILE_SORT_ALPHA, FileList::filelist, filelist_filter(), filelist_islibrary(), filelist_sort(), FileList::filter, direntry::flags, G, GROUP_MAX, groupname_to_code(), PreviewImage::h, i, IB_rect, ICON_SIZE_PREVIEW, direntry::image, IMAGEFILE, IMB_allocImBuf(), FileList::libfiledata, names, LinkNode::next, NULL, FileList::numfiles, ImBuf::rect, PreviewImage::rect, direntry::relname, direntry::type, and PreviewImage::w.
Referenced by filelist_read_library().
void filelist_from_main (struct FileList * filelist)
Definition at line 1124 of file filelist.c.
References BLI_snprintf(), BLI_strdup(), compare_name(), FileList::dir, direntry::extra, FILE_MAX, FILE_SORT_ALPHA, FileList::filelist, filelist_filter(), filelist_sort(), files, FileList::filter, ListBase::first, ID::flag, direntry::flags, G, groupname_to_code(), FileList::hide_dot, FileList::hide_parent, ID_IM, ID_LA, ID_MA, ID_OB, ID_SCE, ID_TE, ID_WO, IMAGEFILE, ID::lib, LIB_FAKEUSER, MEM_mallocN(), Library::name, ID::name, direntry::nr, NULL, FileList::numfiles, direntry::poin, R_BG_RENDER, direntry::relname, SELECT, SELECTED_FILE, direntry::selflag, direntry::type, ID::us, and which_libbase().
Referenced by filelist_read_main().
struct ImBuf* filelist_geticon (struct FileList * filelist, int index) [read]
Definition at line 630 of file filelist.c.
References BLENDERFILE, FileList::fidx, FileList::filelist, direntry::flags, FTFONTFILE, IMAGEFILE, MOVIEFILE, MOVIEFILE_ICON, NULL, FileList::numfiltered, PYSCRIPTFILE, direntry::relname, SOUNDFILE, SPECIAL_IMG_BLENDFILE, SPECIAL_IMG_FOLDER, SPECIAL_IMG_FONTFILE, SPECIAL_IMG_LOADING, SPECIAL_IMG_MOVIEFILE, SPECIAL_IMG_PARENT, SPECIAL_IMG_PYTHONFILE, SPECIAL_IMG_REFRESH, SPECIAL_IMG_SOUNDFILE, SPECIAL_IMG_TEXTFILE, SPECIAL_IMG_UNKNOWNFILE, TEXTFILE, and direntry::type.
Referenced by file_draw_list().
struct ImBuf* filelist_getimage (struct FileList * filelist, int index) [read]
Definition at line 617 of file filelist.c.
References FileList::fidx, FileList::filelist, direntry::image, ImBuf::index, NULL, and FileList::numfiltered.
Referenced by file_draw_list().
void filelist_hidedot (struct FileList * filelist, short hide)
Definition at line 718 of file filelist.c.
References FileList::hide_dot.
Referenced by file_refresh().
void filelist_hideparent (struct FileList * filelist, short hide)
Definition at line 1119 of file filelist.c.
References FileList::hide_parent.
void filelist_imgsize (struct FileList * filelist, short w, short h)
Definition at line 606 of file filelist.c.
References FileList::prv_h, and FileList::prv_w.
void filelist_init_icons (void)
Definition at line 383 of file filelist.c.
References datatoc_prvicons, datatoc_prvicons_size, IB_rect, IMB_allocImBuf(), IMB_freeImBuf(), IMB_ibImageFromMemory(), NULL, ImBuf::rect, SPECIAL_IMG_COLS, SPECIAL_IMG_MAX, SPECIAL_IMG_ROWS, and SPECIAL_IMG_SIZE.
Referenced by ED_file_init().
int filelist_is_selected (struct FileList * filelist, int index, FileCheckType check)
Definition at line 966 of file filelist.c.
References CHECK_ALL, CHECK_DIRS, CHECK_FILES, filelist_file(), S_ISDIR, S_ISREG, SELECTED_FILE, direntry::selflag, and direntry::type.
Referenced by file_exec(), file_select(), file_select_all_exec(), file_selection_get(), file_sfile_to_operator(), and file_smoothscroll_invoke().
int filelist_islibrary (struct FileList * filelist, char * dir, char * group)
Definition at line 1003 of file filelist.c.
References BLO_is_a_library(), and FileList::dir.
Referenced by file_delete_poll(), file_rename_poll(), and filelist_from_library().
struct BlendHandle* filelist_lib (struct FileList * filelist) [read]
Definition at line 586 of file filelist.c.
References FileList::libfiledata.
Referenced by file_directory_poll().
struct FileList* filelist_new (short type) [read]
Definition at line 520 of file filelist.c.
References FILE_LOADLIB, FILE_MAIN, filelist_read_dir(), filelist_read_library(), filelist_read_main(), FileList::filterf, is_filtered_file(), is_filtered_lib(), is_filtered_main(), MEM_callocN(), p, and FileList::readf.
Referenced by file_duplicate(), and file_refresh().
int filelist_numfiles (struct FileList * filelist)
Definition at line 591 of file filelist.c.
References FileList::numfiltered.
Referenced by autocomplete_file(), column_widths(), ED_fileselect_init_layout(), file_deselect_all(), file_draw_list(), file_exec(), file_hilight_set(), file_rename_exec(), file_select_all_exec(), file_select_do(), file_select_match(), file_selection_get(), file_sfile_to_operator(), and file_smoothscroll_invoke().
void filelist_parent (struct FileList * filelist)
Definition at line 915 of file filelist.c.
References BLI_make_exist(), BLI_parent_dir(), FileList::dir, and filelist_readdir().
void filelist_readdir (struct FileList * filelist)
Definition at line 905 of file filelist.c.
References FileList::readf.
Referenced by file_refresh(), and filelist_parent().
void filelist_select (struct FileList * filelist, FileSelection * sel, FileSelType select, unsigned int flag, FileCheckType check)
Definition at line 955 of file filelist.c.
References filelist_select_file(), FileSelection::first, FileSelection::last, and FileList::numfiltered.
Referenced by file_border_select_modal(), file_deselect_all(), file_select(), and file_select_all_exec().
void filelist_select_file (struct FileList * filelist, int index, FileSelType select, unsigned int flag, FileCheckType check)
Definition at line 922 of file filelist.c.
References CHECK_ALL, CHECK_DIRS, CHECK_FILES, FILE_SEL_ADD, FILE_SEL_REMOVE, FILE_SEL_TOGGLE, filelist_file(), NULL, S_ISDIR, direntry::selflag, and direntry::type.
Referenced by file_rename_exec(), and filelist_select().
void filelist_setdir (struct FileList * filelist, const char * dir)
Definition at line 601 of file filelist.c.
References BLI_strncpy(), and FileList::dir.
Referenced by file_change_dir(), file_duplicate(), and file_refresh().
void filelist_setfilter (struct FileList * filelist, unsigned int filter)
Definition at line 723 of file filelist.c.
References FileList::filter, and filter().
Referenced by file_refresh().
void filelist_setfilter_types (struct FileList * filelist, const char * filter_glob)
Definition at line 728 of file filelist.c.
References BLI_strncpy(), and FileList::filter_glob.
Referenced by file_refresh().
void filelist_sort (struct FileList * filelist, short sort)
Definition at line 983 of file filelist.c.
References compare_date(), compare_extension(), compare_name(), compare_size(), FILE_SORT_ALPHA, FILE_SORT_EXTENSION, FILE_SORT_SIZE, FILE_SORT_TIME, FileList::filelist, filelist_filter(), and FileList::numfiles.
Referenced by file_refresh(), filelist_from_library(), and filelist_from_main().
int folderlist_clear_next (struct SpaceFile * sfile)
Definition at line 469 of file filelist.c.
References BLI_path_cmp, FileSelectParams::dir, FolderList::foldername, SpaceFile::folders_next, SpaceFile::folders_prev, ListBase::last, and SpaceFile::params.
Referenced by file_change_dir().
struct ListBase* folderlist_duplicate (ListBase * folderlist) [read]
Definition at line 497 of file filelist.c.
References BLI_duplicatelist(), ListBase::first, FolderList::foldername, MEM_callocN(), MEM_dupallocN(), FolderList::next, and NULL.
Referenced by file_duplicate().
void folderlist_free (struct ListBase * folderlist)
Definition at line 487 of file filelist.c.
References BLI_freelistN(), ListBase::first, FolderList::foldername, MEM_freeN(), and FolderList::next.
Referenced by ED_fileselect_exit(), file_change_dir(), and file_free().
struct ListBase* folderlist_new (void) [read]
Definition at line 420 of file filelist.c.
References MEM_callocN(), and p.
Referenced by ED_fileselect_set_params(), file_next_exec(), file_previous_exec(), and file_refresh().
void folderlist_popdir (struct ListBase * folderlist, char * dir)
Definition at line 426 of file filelist.c.
References BLI_freelinkN(), BLI_strncpy(), FILE_MAXDIR, FolderList::foldername, ListBase::last, and MEM_freeN().
Referenced by file_next_exec(), and file_previous_exec().
void folderlist_pushdir (struct ListBase * folderlist, const char * dir)
Definition at line 446 of file filelist.c.
References BLI_addtail(), BLI_path_cmp, BLI_strncpy(), FILE_MAXDIR, FolderList::foldername, ListBase::last, MEM_mallocN(), and strlen().
Referenced by ED_fileselect_set_params(), file_change_dir(), file_next_exec(), and file_previous_exec().
int thumbnails_running (struct FileList * filelist, const struct bContext * C)
Definition at line 1375 of file filelist.c.
References CTX_wm_manager(), and WM_jobs_test().
Referenced by file_refresh().
void thumbnails_start (struct FileList * filelist, const struct bContext * C)
Definition at line 1337 of file filelist.c.
References BKE_reports_init(), BLENDERFILE, BLI_addtail(), BLI_strncpy(), CTX_wm_manager(), CTX_wm_window(), FILE_MAX, ThumbnailJob::filelist, FileList::filelist, direntry::flags, FileImage::flags, direntry::image, IMAGEFILE, FileImage::index, ThumbnailJob::loadimages, MEM_callocN(), MOVIEFILE, NC_WINDOW, NULL, FileList::numfiles, FileImage::path, direntry::path, ThumbnailJob::reports, RPT_PRINT, thumbnails_free(), thumbnails_startjob(), thumbnails_update(), WM_jobs_callbacks(), WM_jobs_customdata(), WM_jobs_get(), WM_jobs_start(), and WM_jobs_timer().
Referenced by file_refresh().
void thumbnails_stop (struct FileList * filelist, const struct bContext * C)
Definition at line 1370 of file filelist.c.
References CTX_wm_manager(), NULL, and WM_jobs_kill().
Referenced by ED_fileselect_clear(), and file_refresh().