Blender: SCA_XNORController Class Reference
SCA_XNORController Class Reference
#include <SCA_XNORController.h>
Public Member Functions
SCA_XNORController (SCA_IObject *gameobj)
virtual ~SCA_XNORController ()
virtual CValue * GetReplica ()
virtual void Trigger (SCA_LogicManager *logicmgr)
Detailed Description
Definition at line 37 of file SCA_XNORController.h.
Constructor & Destructor Documentation
SCA_XNORController::SCA_XNORController (SCA_IObject * gameobj)
Definition at line 45 of file SCA_XNORController.cpp.
Referenced by GetReplica().
SCA_XNORController::~SCA_XNORController () [virtual]
Definition at line 53 of file SCA_XNORController.cpp.
Member Function Documentation
CValue * SCA_XNORController::GetReplica (void) [virtual]
Implements CValue.
Definition at line 89 of file SCA_XNORController.cpp.
References CValue::ProcessReplica(), and SCA_XNORController().
void SCA_XNORController::Trigger (SCA_LogicManager * logicmgr) [virtual]
Implements SCA_IController.
Definition at line 59 of file SCA_XNORController.cpp.
References SCA_LogicManager::AddActiveActuator(), SCA_ISensor::GetState(), i, SCA_IController::m_linkedactuators, and SCA_IController::m_linkedsensors.
The documentation for this class was generated from the following files:
SCA_XNORController.h
SCA_XNORController.cpp