Blender: ikplugin_api.c File Reference
ikplugin_api.c File Reference
ikplugin
#include "BIK_api.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BKE_armature.h"
#include "DNA_object_types.h"
#include "DNA_action_types.h"
#include "DNA_scene_types.h"
#include "DNA_constraint_types.h"
#include "DNA_armature_types.h"
#include "ikplugin_api.h"
#include "iksolver_plugin.h"
Functions
static IKPlugin * get_plugin (bPose *pose)
void BIK_initialize_tree (Scene *scene, Object *ob, float ctime)
void BIK_execute_tree (struct Scene *scene, Object *ob, bPoseChannel *pchan, float ctime)
void BIK_release_tree (struct Scene *scene, Object *ob, float ctime)
void BIK_clear_data (struct bPose *pose)
void BIK_clear_cache (struct bPose *pose)
void BIK_update_param (struct bPose *pose)
void BIK_test_constraint (struct Object *ob, struct bConstraint *cons)
Variables
static IKPlugin ikplugin_tab []
Detailed Description
Definition in file ikplugin_api.c.
Function Documentation
void BIK_clear_cache (struct bPose * pose)
Definition at line 122 of file ikplugin_api.c.
References IKPlugin::clear_cache, and get_plugin().
Referenced by BKE_ptcache_object_reset().
void BIK_clear_data (struct bPose * pose)
Definition at line 114 of file ikplugin_api.c.
References get_plugin(), and IKPlugin::remove_armature_func.
Referenced by constraint_delete_exec(), free_pose(), and game_free_pose().
void BIK_execute_tree (struct Scene * scene, Object * ob, bPoseChannel * pchan, float ctime)
Definition at line 98 of file ikplugin_api.c.
References IKPlugin::execute_tree_func, get_plugin(), and Object::pose.
Referenced by where_is_pose().
void BIK_initialize_tree (Scene * scene, Object * ob, float ctime)
Definition at line 90 of file ikplugin_api.c.
References get_plugin(), IKPlugin::initialize_tree_func, and Object::pose.
Referenced by where_is_pose().
void BIK_release_tree (struct Scene * scene, Object * ob, float ctime)
Definition at line 106 of file ikplugin_api.c.
References get_plugin(), Object::pose, and IKPlugin::release_tree_func.
Referenced by where_is_pose().
void BIK_test_constraint (struct Object * ob, struct bConstraint * cons)
Definition at line 138 of file ikplugin_api.c.
References get_plugin(), Object::pose, and IKPlugin::test_constraint.
Referenced by test_constraints().
void BIK_update_param (struct bPose * pose)
Definition at line 130 of file ikplugin_api.c.
References get_plugin(), and IKPlugin::update_param.
static IKPlugin* get_plugin (bPose * pose) [static]
Definition at line 79 of file ikplugin_api.c.
References bPose::iksolver, and NULL.
Referenced by BIK_clear_cache(), BIK_clear_data(), BIK_execute_tree(), BIK_initialize_tree(), BIK_release_tree(), BIK_test_constraint(), and BIK_update_param().
Variable Documentation
IKPlugin ikplugin_tab[] [static]
Initial value:
 {
    {
        iksolver_initialize_tree,
        iksolver_execute_tree,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
    }
}
Definition at line 54 of file ikplugin_api.c.