Blender: kernel.cpp File Reference
kernel.cpp File Reference
#include "kernel.h"
#include "kernel_compat_cpu.h"
#include "kernel_math.h"
#include "kernel_types.h"
#include "kernel_globals.h"
#include "kernel_film.h"
#include "kernel_path.h"
#include "kernel_displace.h"
#include "kernel_textures.h"
Defines
#define KERNEL_TEX(type, ttype, tname)
#define KERNEL_IMAGE_TEX(type, ttype, tname)
Functions
CCL_NAMESPACE_BEGIN KernelGlobals * kernel_globals_create ()
void kernel_globals_free (KernelGlobals *kg)
void kernel_const_copy (KernelGlobals *kg, const char *name, void *host, size_t size)
void kernel_tex_copy (KernelGlobals *kg, const char *name, device_ptr mem, size_t width, size_t height)
void kernel_cpu_path_trace (KernelGlobals *kg, float *buffer, unsigned int *rng_state, int sample, int x, int y, int offset, int stride)
void kernel_cpu_tonemap (KernelGlobals *kg, uchar4 *rgba, float *buffer, int sample, int resolution, int x, int y, int offset, int stride)
void kernel_cpu_shader (KernelGlobals *kg, uint4 *input, float4 *output, int type, int i)
Define Documentation
#define KERNEL_IMAGE_TEX (type, ttype, tname)
#define KERNEL_TEX (type, ttype, tname)
Value:
else if(strcmp(name, #tname) == 0) { \
        kg->tname.data = (type*)mem; \
        kg->tname.width = width; \
    }
Function Documentation
void kernel_const_copy (KernelGlobals * kg, const char * name, void * host, size_t size)
Definition at line 66 of file kernel.cpp.
References assert.
Referenced by CPUDevice::const_copy_to().
void kernel_cpu_path_trace (KernelGlobals * kg, float * buffer, unsigned int * rng_state, int sample, int x, int y, int offset, int stride)
Definition at line 221 of file kernel.cpp.
References kernel_path_trace().
Referenced by CPUDevice::thread_path_trace().
void kernel_cpu_shader (KernelGlobals * kg, uint4 * input, float4 * output, int type, int i)
Definition at line 235 of file kernel.cpp.
References kernel_shader_evaluate().
Referenced by CPUDevice::thread_shader().
void kernel_cpu_tonemap (KernelGlobals * kg, uchar4 * rgba, float * buffer, int sample, int resolution, int x, int y, int offset, int stride)
Definition at line 228 of file kernel.cpp.
References kernel_film_tonemap().
Referenced by CPUDevice::thread_tonemap().
CCL_NAMESPACE_BEGIN KernelGlobals* kernel_globals_create ()
Definition at line 34 of file kernel.cpp.
Referenced by CPUDevice::CPUDevice().
void kernel_globals_free (KernelGlobals * kg)
Definition at line 43 of file kernel.cpp.
Referenced by CPUDevice::~CPUDevice().
void kernel_tex_copy (KernelGlobals * kg, const char * name, device_ptr mem, size_t width, size_t height)
Definition at line 74 of file kernel.cpp.
References assert, texture_image< T >::data, texture_image< T >::height, NULL, strlen(), and texture_image< T >::width.
Referenced by CPUDevice::tex_alloc().