Blender: SG_IObject.h File Reference
SG_IObject.h File Reference
BGE SceneGraph
#include "SG_QList.h"
#include <vector>
Classes
struct SG_Callbacks
class SG_IObject
Typedefs
typedef std::vector
< SG_Controller * > SGControllerList
typedef void *(* SG_ReplicationNewCallback)(SG_IObject *sgobject, void *clientobj, void *clientinfo)
typedef void *(* SG_DestructionNewCallback)(SG_IObject *sgobject, void *clientobj, void *clientinfo)
typedef void(* SG_UpdateTransformCallback)(SG_IObject *sgobject, void *clientobj, void *clientinfo)
typedef bool(* SG_ScheduleUpdateCallback)(SG_IObject *sgobject, void *clientobj, void *clientinfo)
typedef bool(* SG_RescheduleUpdateCallback)(SG_IObject *sgobject, void *clientobj, void *clientinfo)
Enumerations
enum SG_Stage {
SG_STAGE_UNKNOWN = 0, SG_STAGE_NETWORK, SG_STAGE_NETWORK_UPDATE, SG_STAGE_PHYSICS1,
SG_STAGE_PHYSICS1_UPDATE, SG_STAGE_CONTROLLER, SG_STAGE_CONTROLLER_UPDATE, SG_STAGE_ACTUATOR,
SG_STAGE_ACTUATOR_UPDATE, SG_STAGE_ANIMATION_UPDATE, SG_STAGE_PHYSICS2, SG_STAGE_PHYSICS2_UPDATE,
SG_STAGE_SCENE, SG_STAGE_RENDER, SG_STAGE_CONVERTER, SG_STAGE_CULLING,
SG_STAGE_MAX
}
Functions
void SG_SetActiveStage (SG_Stage stage)
Variables
SG_Stage gSG_Stage
Detailed Description
Definition in file SG_IObject.h.
Typedef Documentation
typedef void*(* SG_DestructionNewCallback)(SG_IObject *sgobject, void *clientobj, void *clientinfo)
Definition at line 80 of file SG_IObject.h.
typedef void*(* SG_ReplicationNewCallback)(SG_IObject *sgobject, void *clientobj, void *clientinfo)
Definition at line 74 of file SG_IObject.h.
typedef bool(* SG_RescheduleUpdateCallback)(SG_IObject *sgobject, void *clientobj, void *clientinfo)
Definition at line 98 of file SG_IObject.h.
typedef bool(* SG_ScheduleUpdateCallback)(SG_IObject *sgobject, void *clientobj, void *clientinfo)
Definition at line 92 of file SG_IObject.h.
typedef void(* SG_UpdateTransformCallback)(SG_IObject *sgobject, void *clientobj, void *clientinfo)
Definition at line 86 of file SG_IObject.h.
typedef std::vector<SG_Controller*> SGControllerList
Definition at line 70 of file SG_IObject.h.
Enumeration Type Documentation
enum SG_Stage
Enumerator:
SG_STAGE_UNKNOWN
SG_STAGE_NETWORK
SG_STAGE_NETWORK_UPDATE
SG_STAGE_PHYSICS1
SG_STAGE_PHYSICS1_UPDATE
SG_STAGE_CONTROLLER
SG_STAGE_CONTROLLER_UPDATE
SG_STAGE_ACTUATOR
SG_STAGE_ACTUATOR_UPDATE
SG_STAGE_ANIMATION_UPDATE
SG_STAGE_PHYSICS2
SG_STAGE_PHYSICS2_UPDATE
SG_STAGE_SCENE
SG_STAGE_RENDER
SG_STAGE_CONVERTER
SG_STAGE_CULLING
SG_STAGE_MAX
Definition at line 39 of file SG_IObject.h.
Function Documentation
void SG_SetActiveStage (SG_Stage stage) [inline]
Definition at line 62 of file SG_IObject.h.
References gSG_Stage.
Referenced by KX_BlenderSceneConverter::ConvertScene(), KX_KetsjiEngine::NextFrame(), KX_KetsjiEngine::PostProcessScene(), and KX_KetsjiEngine::Render().
Variable Documentation
SG_Stage gSG_Stage
Definition at line 38 of file SG_IObject.cpp.
Referenced by SG_SetActiveStage().