Blender: DefaultMotionState Class Reference
DefaultMotionState Class Reference
DefaultMotionState implements standard motionstate, using btTransform.
#include <CcdPhysicsController.h>
Public Member Functions
DefaultMotionState ()
virtual ~DefaultMotionState ()
virtual void getWorldPosition (float &posX, float &posY, float &posZ)
virtual void getWorldScaling (float &scaleX, float &scaleY, float &scaleZ)
virtual void getWorldOrientation (float &quatIma0, float &quatIma1, float &quatIma2, float &quatReal)
virtual void setWorldPosition (float posX, float posY, float posZ)
virtual void setWorldOrientation (float quatIma0, float quatIma1, float quatIma2, float quatReal)
virtual void getWorldOrientation (float *ori)
virtual void setWorldOrientation (const float *ori)
virtual void calculateWorldTransformations ()
Public Attributes
btTransform m_worldTransform
btVector3 m_localScaling
Detailed Description
DefaultMotionState implements standard motionstate, using btTransform.
Definition at line 628 of file CcdPhysicsController.h.
Constructor & Destructor Documentation
DefaultMotionState::DefaultMotionState ()
A small utility class, DefaultMotionState
Definition at line 1335 of file CcdPhysicsController.cpp.
References m_localScaling, m_worldTransform, and btTransform::setIdentity().
DefaultMotionState::~DefaultMotionState () [virtual]
Definition at line 1342 of file CcdPhysicsController.cpp.
Member Function Documentation
void DefaultMotionState::calculateWorldTransformations () [virtual]
Implements PHY_IMotionState.
Definition at line 1391 of file CcdPhysicsController.cpp.
void DefaultMotionState::getWorldOrientation (float & quatIma0, float & quatIma1, float & quatIma2, float & quatReal) [virtual]
Implements PHY_IMotionState.
Definition at line 1361 of file CcdPhysicsController.cpp.
References btTransform::getRotation(), and m_worldTransform.
void DefaultMotionState::getWorldOrientation (float * ori) [virtual]
Implements PHY_IMotionState.
Definition at line 1370 of file CcdPhysicsController.cpp.
References btTransform::getBasis(), btMatrix3x3::getOpenGLSubMatrix(), and m_worldTransform.
void DefaultMotionState::getWorldPosition (float & posX, float & posY, float & posZ) [virtual]
Implements PHY_IMotionState.
Definition at line 1347 of file CcdPhysicsController.cpp.
References btTransform::getOrigin(), and m_worldTransform.
void DefaultMotionState::getWorldScaling (float & scaleX, float & scaleY, float & scaleZ) [virtual]
Implements PHY_IMotionState.
Definition at line 1354 of file CcdPhysicsController.cpp.
References m_localScaling.
void DefaultMotionState::setWorldOrientation (float quatIma0, float quatIma1, float quatIma2, float quatReal) [virtual]
Implements PHY_IMotionState.
Definition at line 1385 of file CcdPhysicsController.cpp.
References m_worldTransform, and btTransform::setRotation().
void DefaultMotionState::setWorldOrientation (const float * ori) [virtual]
Implements PHY_IMotionState.
Definition at line 1375 of file CcdPhysicsController.cpp.
References btTransform::getBasis(), m_worldTransform, and btMatrix3x3::setFromOpenGLSubMatrix().
void DefaultMotionState::setWorldPosition (float posX, float posY, float posZ) [virtual]
Implements PHY_IMotionState.
Definition at line 1379 of file CcdPhysicsController.cpp.
References m_worldTransform, and btTransform::setOrigin().
Member Data Documentation
btVector3 DefaultMotionState::m_localScaling
Definition at line 648 of file CcdPhysicsController.h.
Referenced by DefaultMotionState(), and getWorldScaling().
btTransform DefaultMotionState::m_worldTransform
Definition at line 647 of file CcdPhysicsController.h.
Referenced by CcdPhysicsEnvironment::CreateConeController(), CcdPhysicsEnvironment::CreateSphereController(), DefaultMotionState(), getWorldOrientation(), getWorldPosition(), setWorldOrientation(), and setWorldPosition().
The documentation for this class was generated from the following files:
CcdPhysicsController.h
CcdPhysicsController.cpp