Blender: iTaSC::Scene Class Reference
iTaSC::Scene Class Reference
#include <Scene.hpp>
Classes
struct ConstraintSet_struct
struct Object_struct
Public Types
enum SceneParam { MIN_TIMESTEP = 0, MAX_TIMESTEP, COUNT }
Public Member Functions
Scene ()
virtual ~Scene ()
bool addObject (const std::string &name, Object *object, UncontrolledObject *base=&Object::world, const std::string &baseFrame="")
bool addConstraintSet (const std::string &name, ConstraintSet *task, const std::string &object1, const std::string &object2, const std::string &ee1="", const std::string &ee2="")
bool addSolver (Solver *_solver)
bool addCache (Cache *_cache)
bool initialize ()
bool update (double timestamp, double timestep, unsigned int numsubstep=1, bool reiterate=false, bool cache=true, bool interpolate=true)
bool setParam (SceneParam paramId, double value)
Friends
class SceneLock
Detailed Description
Definition at line 23 of file Scene.hpp.
Member Enumeration Documentation
enum iTaSC::Scene::SceneParam
Enumerator:
MIN_TIMESTEP
MAX_TIMESTEP
COUNT
Definition at line 26 of file Scene.hpp.
Constructor & Destructor Documentation
Scene::Scene ()
Definition at line 52 of file Scene.cpp.
Scene::~Scene () [virtual]
Definition at line 62 of file Scene.cpp.
Member Function Documentation
bool Scene::addCache (Cache * _cache)
Definition at line 177 of file Scene.cpp.
References NULL.
bool Scene::addConstraintSet (const std::string & name, ConstraintSet * task, const std::string & object1, const std::string & object2, const std::string & ee1 = "", const std::string & ee2 = "")
Definition at line 146 of file Scene.cpp.
References iTaSC::ConstraintSet::getNrOfConstraints().
bool Scene::addObject (const std::string & name, Object * object, UncontrolledObject * base = &Object::world, const std::string & baseFrame = "")
Definition at line 91 of file Scene.cpp.
References iTaSC::Object::addEndEffector(), iTaSC::Object::Controlled, iTaSC::UncontrolledObject::getNrOfCoordinates(), iTaSC::Object::getNrOfCoordinates(), iTaSC::Object::getType(), iTaSC::Object::UnControlled, and iTaSC::Object::world.
bool Scene::addSolver (Solver * _solver)
Definition at line 168 of file Scene.cpp.
References NULL.
bool Scene::initialize (void)
Definition at line 186 of file Scene.cpp.
References e_zero_matrix, e_zero_vector, i, iTaSC::Solver::init(), NULL, and iTaSC::project().
bool Scene::setParam (SceneParam paramId, double value)
Definition at line 76 of file Scene.cpp.
References MAX_TIMESTEP, and MIN_TIMESTEP.
bool Scene::update (double timestamp, double timestep, unsigned int numsubstep = 1, bool reiterate = false, bool cache = true, bool interpolate = true)
Definition at line 259 of file Scene.cpp.
References iTaSC::Timestamp::cache, iTaSC::changeBase(), iTaSC::Object::Controlled, e_matrix, e_scalar, e_vector6, e_zero_vector, KDL::epsilon, i, iTaSC::Timestamp::interpolate, iTaSC::Timestamp::numstep, iTaSC::project(), iTaSC::Timestamp::realTimestamp, iTaSC::Timestamp::realTimestep, iTaSC::Timestamp::reiterate, iTaSC::setCacheTimestamp(), iTaSC::SceneLock::setRange(), iTaSC::Solver::solve(), iTaSC::Timestamp::substep, KDL::svd_eigen_HH(), iTaSC::Object::UnControlled, and iTaSC::Timestamp::update.
Referenced by execute_scene().
Friends And Related Function Documentation
friend class SceneLock [friend]
Definition at line 24 of file Scene.hpp.
The documentation for this class was generated from the following files:
Scene.hpp
Scene.cpp