Blender: BLI_bpath.h File Reference
BLI_bpath.h File Reference
blenlib
Defines
#define BPATH_TRAVERSE_ABS (1<<0)
#define BPATH_TRAVERSE_SKIP_LIBRARY (1<<2)
#define BPATH_TRAVERSE_SKIP_PACKED (1<<3)
#define BPATH_TRAVERSE_SKIP_MULTIFILE (1<<4)
Typedefs
typedef int(* BPathVisitor)(void *userdata, char *path_dst, const char *path_src)
Functions
void bpath_traverse_id (struct Main *bmain, struct ID *id, BPathVisitor visit_cb, const int flag, void *userdata)
void bpath_traverse_id_list (struct Main *bmain, struct ListBase *lb, BPathVisitor visit_cb, const int flag, void *userdata)
void bpath_traverse_main (struct Main *bmain, BPathVisitor visit_cb, const int flag, void *userdata)
int bpath_relocate_visitor (void *oldbasepath, char *path_dst, const char *path_src)
void checkMissingFiles (struct Main *bmain, struct ReportList *reports)
void makeFilesRelative (struct Main *bmain, const char *basedir, struct ReportList *reports)
void makeFilesAbsolute (struct Main *bmain, const char *basedir, struct ReportList *reports)
void findMissingFiles (struct Main *bmain, const char *searchpath, struct ReportList *reports)
Detailed Description
Attention:
Based on ghash, difference is ghash is not a fixed size, so for BPath we don't need to malloc
Definition in file BLI_bpath.h.
Define Documentation
#define BPATH_TRAVERSE_ABS (1<<0)
Definition at line 51 of file BLI_bpath.h.
Referenced by bpath_traverse_id(), bpy_blend_paths(), and checkMissingFiles().
#define BPATH_TRAVERSE_SKIP_LIBRARY (1<<2)
Definition at line 52 of file BLI_bpath.h.
Referenced by bpath_traverse_id(), and bpy_blend_paths().
#define BPATH_TRAVERSE_SKIP_MULTIFILE (1<<4)
Definition at line 54 of file BLI_bpath.h.
Referenced by BKE_id_lib_local_paths(), bpath_traverse_id(), and clean_paths().
#define BPATH_TRAVERSE_SKIP_PACKED (1<<3)
Definition at line 53 of file BLI_bpath.h.
Referenced by bpath_traverse_id(), and bpy_blend_paths().
Typedef Documentation
typedef int(* BPathVisitor)(void *userdata, char *path_dst, const char *path_src)
Definition at line 44 of file BLI_bpath.h.
Function Documentation
int bpath_relocate_visitor (void * oldbasepath, char * path_dst, const char * path_src)
Definition at line 596 of file bpath.c.
References BLI_cleanup_file(), BLI_path_abs(), BLI_path_rel(), BLI_strncpy(), FALSE, FILE_MAX, FILE_MAXDIR, FILE_MAXFILE, and TRUE.
Referenced by BKE_id_lib_local_paths().
void bpath_traverse_id (struct Main * bmain, struct ID * id, BPathVisitor visit_cb, const int flag, void * userdata)
Definition at line 381 of file bpath.c.
References BKE_library_filepath_set(), BPATH_TRAVERSE_ABS, BPATH_TRAVERSE_POINTCACHE, BPATH_TRAVERSE_SKIP_LIBRARY, BPATH_TRAVERSE_SKIP_MULTIFILE, BPATH_TRAVERSE_SKIP_PACKED, OceanModifierData::cachepath, Strip::dir, SmokeModifierData::domain, Scene::ed, ELEM, ELEM3, eModifierType_Cloth, eModifierType_Fluidsim, eModifierType_Ocean, eModifierType_Smoke, CustomData::external, Mesh::fdata, VoxelData::file_format, CustomDataExternal::filename, ListBase::first, Object::fluidsimSettings, FO_BUILTIN_NAME, FluidsimModifierData::fss, GS, i, Brush::icon_filepath, ID_BLEND_PATH, ID_BR, ID_IM, ID_LI, ID_MC, ID_ME, ID_OB, ID_SCE, ID_SO, ID_TE, ID_TXT, ID_VF, IMA_SRC_FILE, IMA_SRC_MOVIE, IMA_SRC_SEQUENCE, len(), MEM_allocN_len(), MIN2, MOD_SMOKE_TYPE_DOMAIN, Object::modifiers, Library::name, MovieClip::name, PluginSeq::name, bSound::name, StripElem::name, ID::name, Image::name, VFont::name, ModifierData::next, ParticleSystem::next, NULL, Image::packedfile, bSound::packedfile, VFont::packedfile, Object::particlesystem, Sequence::plugin, Tex::plugin, SoftBody::ptcaches, SmokeDomainSettings::ptcaches, ParticleSystem::ptcaches, ClothModifierData::ptcaches, rewrite_path_alloc(), rewrite_path_fixed(), rewrite_path_fixed_dirfile(), SEQ_BEGIN, SEQ_END, SEQ_HAS_PATH, SEQ_IMAGE, SEQ_MOVIE, SEQ_SOUND, Object::soft, Image::source, VoxelData::source_path, Sequence::strip, Strip::stripdata, FluidsimSettings::surfdataPath, TEX_VD_IS_SOURCE_PATH, TEX_VOXELDATA, ModifierData::type, SmokeModifierData::type, Tex::type, Sequence::type, and Tex::vd.
Referenced by BKE_id_lib_local_paths(), and bpath_traverse_id_list().
void bpath_traverse_id_list (struct Main * bmain, struct ListBase * lb, BPathVisitor visit_cb, const int flag, void * userdata)
Definition at line 577 of file bpath.c.
References bpath_traverse_id(), ListBase::first, and ID::next.
Referenced by bpath_traverse_main().
void bpath_traverse_main (struct Main * bmain, BPathVisitor visit_cb, const int flag, void * userdata)
Definition at line 585 of file bpath.c.
References bpath_traverse_id_list(), MAX_LIBARRAY, and set_listbasepointers().
Referenced by bpy_blend_paths(), checkMissingFiles(), clean_paths(), findMissingFiles(), makeFilesAbsolute(), and makeFilesRelative().
void checkMissingFiles (struct Main * bmain, struct ReportList * reports)
Definition at line 95 of file bpath.c.
References BPATH_TRAVERSE_ABS, bpath_traverse_main(), and checkMissingFiles_visit_cb().
Referenced by report_missing_files_exec().
void findMissingFiles (struct Main * bmain, const char * searchpath, struct ReportList * reports)
Definition at line 296 of file bpath.c.
References BLI_split_dir_part(), bpath_traverse_main(), findMissingFiles_visit_cb(), NULL, BPathFind_Data::reports, and BPathFind_Data::searchdir.
Referenced by find_missing_files_exec().
void makeFilesAbsolute (struct Main * bmain, const char * basedir, struct ReportList * reports)
Definition at line 175 of file bpath.c.
References BPathRemap_Data::basedir, BKE_reportf(), bpath_traverse_main(), data, makeFilesAbsolute_visit_cb(), NULL, BPathRemap_Data::reports, RPT_INFO, and RPT_WARNING.
Referenced by BLO_write_file(), and make_paths_absolute_exec().
void makeFilesRelative (struct Main * bmain, const char * basedir, struct ReportList * reports)
Definition at line 132 of file bpath.c.
References BPathRemap_Data::basedir, BKE_reportf(), bpath_traverse_main(), data, makeFilesRelative_visit_cb(), NULL, BPathRemap_Data::reports, RPT_INFO, and RPT_WARNING.
Referenced by BLO_write_file(), and make_paths_relative_exec().