Blender: KX_SCA_AddObjectActuator Class Reference
KX_SCA_AddObjectActuator Class Reference
#include <KX_SCA_AddObjectActuator.h>
Public Member Functions
KX_SCA_AddObjectActuator (SCA_IObject *gameobj, SCA_IObject *original, int time, SCA_IScene *scene, const float *linvel, bool linv_local, const float *angvel, bool angv_local)
~KX_SCA_AddObjectActuator (void)
CValue * GetReplica ()
virtual void ProcessReplica ()
virtual void Replace_IScene (SCA_IScene *val)
virtual bool UnlinkObject (SCA_IObject *clientobj)
virtual void Relink (CTR_Map< CTR_HashedPtr, void * > *obj_map)
virtual bool Update ()
SCA_IObject * GetLastCreatedObject () const
void InstantAddObject ()
Detailed Description
Definition at line 46 of file KX_SCA_AddObjectActuator.h.
Constructor & Destructor Documentation
KX_SCA_AddObjectActuator::KX_SCA_AddObjectActuator (SCA_IObject * gameobj, SCA_IObject * original, int time, SCA_IScene * scene, const float * linvel, bool linv_local, const float * angvel, bool angv_local)
This class also has the default constructors available. Use with care!
Definition at line 49 of file KX_SCA_AddObjectActuator.cpp.
References NULL, and SCA_IObject::RegisterActuator().
Referenced by GetReplica().
KX_SCA_AddObjectActuator::~KX_SCA_AddObjectActuator (void)
Definition at line 81 of file KX_SCA_AddObjectActuator.cpp.
References SCA_IObject::UnregisterActuator().
Member Function Documentation
SCA_IObject * KX_SCA_AddObjectActuator::GetLastCreatedObject () const
Definition at line 108 of file KX_SCA_AddObjectActuator.cpp.
CValue * KX_SCA_AddObjectActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 115 of file KX_SCA_AddObjectActuator.cpp.
References KX_SCA_AddObjectActuator(), NULL, and ProcessReplica().
void KX_SCA_AddObjectActuator::InstantAddObject ()
Definition at line 253 of file KX_SCA_AddObjectActuator.cpp.
References SCA_IScene::AddReplicaObject(), SCA_ILogicBrick::GetParent(), NULL, SCA_IObject::RegisterActuator(), CValue::Release(), KX_GameObject::ResolveCombinedVelocities(), KX_GameObject::setAngularVelocity(), KX_GameObject::setLinearVelocity(), and SCA_IObject::UnregisterActuator().
Referenced by Update().
void KX_SCA_AddObjectActuator::ProcessReplica () [virtual]
Makes sure any internal data owned by this class is deep copied.
Reimplemented from SCA_IActuator.
Definition at line 128 of file KX_SCA_AddObjectActuator.cpp.
References NULL, and SCA_IObject::RegisterActuator().
Referenced by GetReplica().
void KX_SCA_AddObjectActuator::Relink (CTR_Map< CTR_HashedPtr, void * > * obj_map) [virtual]
Reimplemented from SCA_ILogicBrick.
Definition at line 153 of file KX_SCA_AddObjectActuator.cpp.
References SCA_IObject::RegisterActuator(), and SCA_IObject::UnregisterActuator().
virtual void KX_SCA_AddObjectActuator::Replace_IScene (SCA_IScene * val) [inline, virtual]
Reimplemented from SCA_ILogicBrick.
Definition at line 101 of file KX_SCA_AddObjectActuator.h.
bool KX_SCA_AddObjectActuator::UnlinkObject (SCA_IObject * clientobj) [virtual]
UnlinkObject(...) Certain actuator use gameobject pointers (like TractTo actuator) This function can be called when an object is removed to make sure that the actuator will not use it anymore.
Reimplemented from SCA_IActuator.
Definition at line 136 of file KX_SCA_AddObjectActuator.cpp.
References NULL.
bool KX_SCA_AddObjectActuator::Update (void) [virtual]
Reimplemented from SCA_IActuator.
Definition at line 91 of file KX_SCA_AddObjectActuator.cpp.
References InstantAddObject(), SCA_IActuator::IsNegativeEvent(), and SCA_IActuator::RemoveAllEvents().
The documentation for this class was generated from the following files:
KX_SCA_AddObjectActuator.h
KX_SCA_AddObjectActuator.cpp