Blender: wm_event_system.h File Reference
wm_event_system.h File Reference
windowmanager
Classes
struct wmEventHandler
Defines
#define WM_HANDLER_CONTINUE 0
#define WM_HANDLER_BREAK 1
#define WM_HANDLER_HANDLED 2
#define WM_HANDLER_MODAL 4
#define WM_HANDLER_BLOCKING 1
#define WM_HANDLER_DO_FREE 2
Typedefs
typedef struct wmEventHandler wmEventHandler
Enumerations
enum { WM_HANDLER_DEFAULT, WM_HANDLER_FILESELECT }
Functions
void wm_event_free_all (wmWindow *win)
void wm_event_free (wmEvent *event)
void wm_event_free_handler (wmEventHandler *handler)
void wm_event_do_handlers (bContext *C)
void wm_event_add_ghostevent (wmWindowManager *wm, wmWindow *win, int type, int time, void *customdata)
void wm_event_do_notifiers (bContext *C)
void wm_dropbox_free (void)
void wm_drags_check_ops (bContext *C, wmEvent *event)
void wm_drags_draw (bContext *C, wmWindow *win, rcti *rect)
Detailed Description
Definition in file wm_event_system.h.
Define Documentation
#define WM_HANDLER_BLOCKING 1
Definition at line 78 of file wm_event_system.h.
Referenced by wm_handlers_do().
#define WM_HANDLER_BREAK 1
Definition at line 36 of file wm_event_system.h.
Referenced by wm_action_not_handled(), wm_event_do_handlers(), wm_handler_fileselect_call(), wm_handler_operator_call(), wm_handler_ui_call(), wm_handlers_do(), and wm_tweakevent_test().
#define WM_HANDLER_CONTINUE 0
Definition at line 35 of file wm_event_system.h.
Referenced by wm_action_not_handled(), wm_event_do_handlers(), wm_handler_fileselect_call(), wm_handler_operator_call(), wm_handler_ui_call(), and wm_handlers_do().
#define WM_HANDLER_DO_FREE 2
Definition at line 80 of file wm_event_system.h.
Referenced by WM_event_remove_ui_handler(), and wm_handlers_do().
#define WM_HANDLER_HANDLED 2
Definition at line 37 of file wm_event_system.h.
Referenced by wm_handler_operator_call().
#define WM_HANDLER_MODAL 4
Definition at line 38 of file wm_event_system.h.
Referenced by wm_action_not_handled(), wm_handler_operator_call(), and wm_handlers_do().
Typedef Documentation
typedef struct wmEventHandler wmEventHandler
Enumeration Type Documentation
anonymous enum
Enumerator:
WM_HANDLER_DEFAULT
WM_HANDLER_FILESELECT
Definition at line 85 of file wm_event_system.h.
Function Documentation
void wm_drags_check_ops (bContext * C, wmEvent * event)
Definition at line 245 of file wm_dragdrop.c.
References CTX_wm_manager(), wmWindowManager::drags, ListBase::first, wmDrag::next, and wm_drop_operator_options().
Referenced by wm_event_do_handlers().
void wm_drags_draw (bContext * C, wmWindow * win, rcti * rect)
Definition at line 300 of file wm_dragdrop.c.
References CTX_wm_manager(), drag_rect_minmax(), wmWindowManager::drags, wmWindow::eventstate, ListBase::first, glaDrawPixelsTexScaled(), wmDrag::icon, wmDrag::imb, wmDrag::next, wmDrag::opname, ImBuf::rect, wmDrag::scale, wmDrag::sx, wmDrag::sy, UI_DrawString(), UI_GetStringWidth(), UI_icon_draw_aspect(), wm_drag_name(), wm_drop_operator_draw(), ImBuf::x, wmEvent::x, rcti::xmax, rcti::xmin, ImBuf::y, wmEvent::y, rcti::ymax, and rcti::ymin.
Referenced by wm_method_draw_overlap_all(), and wm_method_draw_triple().
void wm_dropbox_free (void)
Definition at line 128 of file wm_dragdrop.c.
References BLI_freelistN(), wmDropBoxMap::dropboxes, ListBase::first, MEM_freeN(), wmDropBox::next, wmDropBoxMap::next, wmDropBox::ptr, and WM_operator_properties_free().
Referenced by WM_exit_ext().
void wm_event_add_ghostevent (wmWindowManager * wm, wmWindow * win, int type, int time, void * customdata)
void wm_event_do_handlers (bContext * C)
Definition at line 1938 of file wm_event_system.c.
References wmWindow::addmousemove, bScreen::animtimer, area_event_inside(), bScreen::areabase, BLI_in_rcti(), BLI_remlink(), RenderData::cfra, CTX_data_main(), CTX_data_scene_set(), CTX_wm_area_set(), CTX_wm_manager(), CTX_wm_region_set(), CTX_wm_screen_set(), CTX_wm_window(), CTX_wm_window_set(), ED_screen_animation_play(), ED_screen_set_subwinactive(), ED_update_for_newframe(), ELEM, wmWindow::eventstate, EVT_DROP, ListBase::first, FPS, G, G_DEBUG_EVENTS, wmWindow::handlers, ScrArea::handlers, ARegion::handlers, INBETWEEN_MOUSEMOVE, ISTIMER, KM_CLICK, KM_PRESS, KM_RELEASE, bScreen::mainwin, wmWindow::modalhandlers, MOUSEMOVE, NC_WINDOW, NDOF_MOTION, ARegion::next, ScrArea::next, wmWindow::next, NULL, PIL_check_seconds_timer(), wmEvent::prevclicktime, wmEvent::prevclickx, wmEvent::prevclicky, wmEvent::prevtype, wmEvent::prevval, wmEvent::prevx, wmEvent::prevy, wmWindow::queue, Scene::r, region_event_inside(), ScrArea::regionbase, bScreen::scene, wmWindow::screen, sound_scene_playing(), sound_sync_scene(), bScreen::subwinactive, ScrArea::totrct, TRUE, wmEvent::type, wmEvent::val, wmWindowManager::windows, ARegion::winrct, wm_action_not_handled(), wm_drags_check_ops(), wm_event_add(), WM_event_add_notifier(), wm_event_drag_test(), wm_event_free(), wm_event_free_all(), wm_event_inside_i(), wm_eventemulation(), WM_HANDLER_BREAK, WM_HANDLER_CONTINUE, wm_handlers_do(), WM_keyconfig_update(), wm_paintcursor_test(), wm_region_mouse_co(), wm_tweakevent_test(), wm_window_make_drawable(), wmEvent::x, and wmEvent::y.
Referenced by WM_main().
void wm_event_do_notifiers (bContext * C)
Definition at line 185 of file wm_event_system.c.
References bScreen::areabase, wmNotifier::category, CTX_data_main(), CTX_data_scene(), CTX_wm_area_set(), CTX_wm_manager(), CTX_wm_window_set(), Scene::customdata_mask, Scene::customdata_mask_modal, wmNotifier::data, ScrArea::do_refresh, ED_area_do_listen(), ED_area_do_refresh(), ED_info_stats_clear(), ED_region_do_listen(), ED_screen_delete(), ED_screen_do_listen(), ED_screen_set(), ED_update_for_newframe(), ED_view3d_screen_datamask(), ELEM, ELEM5, wmWindowManager::file_saved, ListBase::first, G, G_DEBUG_EVENTS, MEM_freeN(), NC_GEOM, NC_OBJECT, NC_SCENE, NC_SCREEN, NC_SPACE, NC_WM, ND_DATACHANGED, ND_FILEREAD, ND_FILESAVE, ND_FRAME, ND_SCREENBROWSE, ND_SCREENDELETE, ND_SPACE_INFO, ScrArea::next, ARegion::next, wmNotifier::next, wmWindow::next, next, NULL, wmWindowManager::queue, wmNotifier::reference, ScrArea::regionbase, bScreen::regionbase, bScreen::scene, scene_update_tagged(), wmWindow::screen, wmNotifier::window, wmWindowManager::windows, WM_event_add_notifier(), wm_notifier_next(), and wm_window_title().
Referenced by WM_main().
void wm_event_free (wmEvent * event)
Definition at line 98 of file wm_event_system.c.
References BLI_freelistN(), wmEvent::custom, wmEvent::customdata, wmEvent::customdatafree, EVT_DATA_LISTBASE, and MEM_freeN().
Referenced by StartKetsjiShell(), wm_event_do_handlers(), and wm_event_free_all().
void wm_event_free_all (wmWindow * win)
Definition at line 112 of file wm_event_system.c.
References BLI_remlink(), ListBase::first, wmWindow::queue, and wm_event_free().
Referenced by wm_event_do_handlers(), and wm_window_free().
void wm_event_free_handler (wmEventHandler * handler)
Definition at line 1129 of file wm_event_system.c.
References MEM_freeN().
Referenced by WM_event_add_fileselect(), WM_event_remove_area_handler(), WM_event_remove_handlers(), WM_event_remove_keymap_handler(), WM_event_remove_ui_handler(), wm_handler_fileselect_call(), wm_handler_operator_call(), wm_handlers_do(), and wm_macro_modal().