Blender: BL_ArmatureConstraint Class Reference
BL_ArmatureConstraint Class Reference
#include <BL_ArmatureConstraint.h>
Public Member Functions
BL_ArmatureConstraint (class BL_ArmatureObject *armature, struct bPoseChannel *posechannel, struct bConstraint *constraint, KX_GameObject *target, KX_GameObject *subtarget)
virtual ~BL_ArmatureConstraint ()
BL_ArmatureConstraint * GetReplica () const
void ReParent (BL_ArmatureObject *armature)
void Relink (CTR_Map< CTR_HashedPtr, void * > *map)
bool UnlinkObject (SCA_IObject *clientobj)
void UpdateTarget ()
void RestoreTarget ()
bool Match (const char *posechannel, const char *constraint)
const char * GetName ()
void SetConstraintFlag (int flag)
void ClrConstraintFlag (int flag)
void SetWeight (float weight)
void SetInfluence (float influence)
void SetTarget (KX_GameObject *target)
void SetSubtarget (KX_GameObject *subtarget)
Detailed Description
SG_DList : element of controlled constraint list head = BL_ArmatureObject::m_controlledConstraints SG_QList : not used
Definition at line 53 of file BL_ArmatureConstraint.h.
Constructor & Destructor Documentation
BL_ArmatureConstraint::BL_ArmatureConstraint (class BL_ArmatureObject * armature, struct bPoseChannel * posechannel, struct bConstraint * constraint, KX_GameObject * target, KX_GameObject * subtarget)
Definition at line 71 of file BL_ArmatureConstraint.cpp.
References BLI_snprintf(), copy_m4_m4(), KX_GameObject::GetBlenderObject(), bPoseChannel::name, bConstraint::name, NULL, OB_ARMATURE, Object::obmat, Object::pose, SCA_IObject::RegisterObject(), and Object::type.
Referenced by GetReplica().
BL_ArmatureConstraint::~BL_ArmatureConstraint () [virtual]
Definition at line 101 of file BL_ArmatureConstraint.cpp.
References SCA_IObject::UnregisterObject().
Member Function Documentation
void BL_ArmatureConstraint::ClrConstraintFlag (int flag) [inline]
Definition at line 95 of file BL_ArmatureConstraint.h.
References bConstraint::flag.
Referenced by BL_ArmatureActuator::Update().
const char* BL_ArmatureConstraint::GetName () [inline]
Definition at line 88 of file BL_ArmatureConstraint.h.
Referenced by BL_ArmatureObject::GetConstraint().
BL_ArmatureConstraint * BL_ArmatureConstraint::GetReplica (void) const
Definition at line 109 of file BL_ArmatureConstraint.cpp.
References BL_ArmatureConstraint(), and PyObjectPlus::ProcessReplica().
bool BL_ArmatureConstraint::Match (const char * posechannel, const char * constraint)
Definition at line 213 of file BL_ArmatureConstraint.cpp.
References bPoseChannel::name, and bConstraint::name.
Referenced by BL_ArmatureObject::GetConstraint().
void BL_ArmatureConstraint::Relink (CTR_Map< CTR_HashedPtr, void * > * map)
Definition at line 149 of file BL_ArmatureConstraint.cpp.
References SCA_IObject::RegisterObject(), and SCA_IObject::UnregisterObject().
void BL_ArmatureConstraint::ReParent (BL_ArmatureObject * armature)
Definition at line 116 of file BL_ArmatureConstraint.cpp.
References bPose::chanbase, bPoseChannel::constraints, ListBase::first, BL_ArmatureObject::GetOrigPose(), bPoseChannel::name, bConstraint::name, bPoseChannel::next, bConstraint::next, NULL, and SCA_IObject::RegisterObject().
void BL_ArmatureConstraint::RestoreTarget ()
Definition at line 197 of file BL_ArmatureConstraint.cpp.
References CONSTRAINT_OFF, copy_m4_m4(), bConstraint::flag, Object::obmat, and Object::pose.
void BL_ArmatureConstraint::SetConstraintFlag (int flag) [inline]
Definition at line 90 of file BL_ArmatureConstraint.h.
References bConstraint::flag, and bPose::flag.
Referenced by BL_ArmatureActuator::Update().
void BL_ArmatureConstraint::SetInfluence (float influence) [inline]
Definition at line 107 of file BL_ArmatureConstraint.h.
References bConstraint::enforce.
Referenced by BL_ArmatureActuator::Update().
void BL_ArmatureConstraint::SetSubtarget (KX_GameObject * subtarget)
Definition at line 231 of file BL_ArmatureConstraint.cpp.
References SCA_IObject::RegisterObject(), and SCA_IObject::UnregisterObject().
Referenced by BL_ArmatureActuator::Update().
void BL_ArmatureConstraint::SetTarget (KX_GameObject * target)
Definition at line 218 of file BL_ArmatureConstraint.cpp.
References SCA_IObject::RegisterObject(), and SCA_IObject::UnregisterObject().
Referenced by BL_ArmatureActuator::Update().
void BL_ArmatureConstraint::SetWeight (float weight) [inline]
Definition at line 100 of file BL_ArmatureConstraint.h.
References CONSTRAINT_TYPE_KINEMATIC, bConstraint::data, bConstraint::type, and bKinematicConstraint::weight.
Referenced by BL_ArmatureActuator::Update().
bool BL_ArmatureConstraint::UnlinkObject (SCA_IObject * clientobj)
Definition at line 165 of file BL_ArmatureConstraint.cpp.
References NULL.
void BL_ArmatureConstraint::UpdateTarget ()
Definition at line 179 of file BL_ArmatureConstraint.cpp.
References CONSTRAINT_OFF, bConstraint::flag, SCA_IObject::GetGameObjectType(), SCA_IObject::OBJ_ARMATURE, Object::pose, and KX_GameObject::UpdateBlenderObjectMatrix().
The documentation for this class was generated from the following files:
BL_ArmatureConstraint.h
BL_ArmatureConstraint.cpp