Blender: clip_graph_ops.c File Reference
clip_graph_ops.c File Reference
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "BLI_listbase.h"
#include "BLI_rect.h"
#include "BKE_context.h"
#include "BKE_movieclip.h"
#include "BKE_tracking.h"
#include "BKE_depsgraph.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_screen.h"
#include "ED_clip.h"
#include "UI_interface.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "UI_view2d.h"
#include "clip_intern.h"
Classes
struct SelectUserData
struct MouseSelectUserData
struct BorderSelectuserData
struct ViewAllUserData
Typedefs
typedef struct BorderSelectuserData BorderSelectuserData
Functions
static int ED_space_clip_graph_poll (bContext *C)
static void toggle_selection_cb (void *userdata, MovieTrackingMarker *marker)
static void find_nearest_tracking_segment_cb (void *userdata, MovieTrackingTrack *track, MovieTrackingMarker *marker, int coord, float val)
void find_nearest_tracking_segment_end_cb (void *userdata)
static void find_nearest_tracking_knot_cb (void *userdata, MovieTrackingTrack *track, MovieTrackingMarker *marker, int coord, float val)
static void mouse_select_init_data (MouseSelectUserData *userdata, float *co)
static int mouse_select_knot (bContext *C, float co[2], int extend)
static int mouse_select_curve (bContext *C, float co[2], int extend)
static int mouse_select (bContext *C, float co[2], int extend)
static int select_exec (bContext *C, wmOperator *op)
static int select_invoke (bContext *C, wmOperator *op, wmEvent *event)
void CLIP_OT_graph_select (wmOperatorType *ot)
static void border_select_cb (void *userdata, MovieTrackingTrack *UNUSED(track), MovieTrackingMarker *marker, int coord, float val)
static int border_select_graph_exec (bContext *C, wmOperator *op)
void CLIP_OT_graph_select_border (wmOperatorType *ot)
static int graph_select_all_markers_exec (bContext *C, wmOperator *op)
void CLIP_OT_graph_select_all_markers (wmOperatorType *ot)
static int delete_curve_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_graph_delete_curve (wmOperatorType *ot)
static int delete_knot_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_graph_delete_knot (wmOperatorType *ot)
static void view_all_cb (void *userdata, MovieTrackingTrack *UNUSED(track), MovieTrackingMarker *UNUSED(marker), int UNUSED(coord), float val)
static int view_all_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_graph_view_all (wmOperatorType *ot)
void ED_clip_graph_center_current_frame (Scene *scene, ARegion *ar)
static int center_current_frame_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_graph_center_current_frame (wmOperatorType *ot)
static int graph_disable_markers_exec (bContext *C, wmOperator *op)
void CLIP_OT_graph_disable_markers (wmOperatorType *ot)
Detailed Description
Definition in file clip_graph_ops.c.
Typedef Documentation
typedef struct BorderSelectuserData BorderSelectuserData
Function Documentation
static void border_select_cb (void * userdata, MovieTrackingTrack * UNUSEDtrack, MovieTrackingMarker * marker, int coord, float val) [static]
Definition at line 318 of file clip_graph_ops.c.
References BLI_in_rctf(), BorderSelectuserData::change, data, BorderSelectuserData::extend, MovieTrackingMarker::flag, MovieTrackingMarker::framenr, GESTURE_MODAL_SELECT, MARKER_GRAPH_SEL, MARKER_GRAPH_SEL_X, MARKER_GRAPH_SEL_Y, BorderSelectuserData::mode, BorderSelectuserData::rect, and TRUE.
Referenced by border_select_graph_exec().
static int border_select_graph_exec (bContext * C, wmOperator * op) [static]
Definition at line 343 of file clip_graph_ops.c.
References BKE_tracking_active_track(), border_select_cb(), BorderSelectuserData::change, clip_graph_tracking_values_iterate_track(), CTX_wm_region(), CTX_wm_space_clip(), ED_space_clip(), BorderSelectuserData::extend, FALSE, BorderSelectuserData::mode, NC_GEOM, ND_SELECT, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, BorderSelectuserData::rect, RNA_boolean_get(), RNA_int_get(), MovieClip::tracking, UI_view2d_region_to_view(), ARegion::v2d, WM_event_add_notifier(), rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by CLIP_OT_graph_select_border().
static int center_current_frame_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 619 of file clip_graph_ops.c.
References CTX_data_scene(), CTX_wm_region(), ED_clip_graph_center_current_frame(), ED_region_tag_redraw(), and OPERATOR_FINISHED.
Referenced by CLIP_OT_graph_center_current_frame().
void CLIP_OT_graph_center_current_frame (wmOperatorType * ot)
Definition at line 631 of file clip_graph_ops.c.
References center_current_frame_exec(), wmOperatorType::description, ED_space_clip_graph_poll(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by clip_operatortypes().
void CLIP_OT_graph_delete_curve (wmOperatorType * ot)
Definition at line 479 of file clip_graph_ops.c.
References delete_curve_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by clip_operatortypes().
void CLIP_OT_graph_delete_knot (wmOperatorType * ot)
Definition at line 521 of file clip_graph_ops.c.
References delete_knot_exec(), wmOperatorType::description, ED_space_clip_graph_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by clip_operatortypes().
void CLIP_OT_graph_disable_markers (wmOperatorType * ot)
Definition at line 678 of file clip_graph_ops.c.
References wmOperatorType::description, ED_space_clip_graph_poll(), wmOperatorType::exec, wmOperatorType::flag, graph_disable_markers_exec(), wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_graph_select (wmOperatorType * ot)
Definition at line 289 of file clip_graph_ops.c.
References wmOperatorType::description, ED_space_clip_graph_poll(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_vector(), select_exec(), select_invoke(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_graph_select_all_markers (wmOperatorType * ot)
Definition at line 446 of file clip_graph_ops.c.
References wmOperatorType::description, ED_space_clip_graph_poll(), wmOperatorType::exec, wmOperatorType::flag, graph_select_all_markers_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_properties_select_all().
Referenced by clip_operatortypes().
void CLIP_OT_graph_select_border (wmOperatorType * ot)
Definition at line 377 of file clip_graph_ops.c.
References border_select_graph_exec(), wmOperatorType::description, ED_space_clip_graph_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, TRUE, WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by clip_operatortypes().
void CLIP_OT_graph_view_all (wmOperatorType * ot)
Definition at line 595 of file clip_graph_ops.c.
References wmOperatorType::description, ED_space_clip_graph_poll(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and view_all_exec().
Referenced by clip_operatortypes().
static int delete_curve_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 465 of file clip_graph_ops.c.
References BKE_tracking_active_track(), BKE_tracking_get_tracks(), clip_delete_track(), CTX_wm_space_clip(), ED_space_clip(), OPERATOR_FINISHED, and MovieClip::tracking.
Referenced by CLIP_OT_graph_delete_curve().
static int delete_knot_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 497 of file clip_graph_ops.c.
References BKE_tracking_active_track(), BKE_tracking_get_tracks(), clip_delete_marker(), CTX_wm_space_clip(), ED_space_clip(), MovieTrackingMarker::flag, MARKER_GRAPH_SEL, MovieTrackingTrack::markers, OPERATOR_FINISHED, and MovieClip::tracking.
Referenced by CLIP_OT_graph_delete_knot().
void ED_clip_graph_center_current_frame (Scene * scene, ARegion * ar)
Definition at line 609 of file clip_graph_ops.c.
References CFRA, View2D::cur, ARegion::v2d, rctf::xmax, and rctf::xmin.
Referenced by center_current_frame_exec(), and clip_preview_area_draw().
static int ED_space_clip_graph_poll (bContext * C) [static]
Definition at line 64 of file clip_graph_ops.c.
References SpaceClip::clip, CTX_wm_region(), CTX_wm_space_clip(), ARegion::regiontype, and RGN_TYPE_PREVIEW.
Referenced by CLIP_OT_graph_center_current_frame(), CLIP_OT_graph_delete_knot(), CLIP_OT_graph_disable_markers(), CLIP_OT_graph_select(), CLIP_OT_graph_select_all_markers(), CLIP_OT_graph_select_border(), and CLIP_OT_graph_view_all().
static void find_nearest_tracking_knot_cb (void * userdata, MovieTrackingTrack * track, MovieTrackingMarker * marker, int coord, float val) [static]
Definition at line 141 of file clip_graph_ops.c.
References co, MouseSelectUserData::coord, copy_v2_v2(), data, MovieTrackingMarker::framenr, MouseSelectUserData::marker, MouseSelectUserData::min_co, MouseSelectUserData::min_dist, MouseSelectUserData::mouse_co, NULL, and MouseSelectUserData::track.
Referenced by mouse_select_knot().
static void find_nearest_tracking_segment_cb (void * userdata, MovieTrackingTrack * track, MovieTrackingMarker * marker, int coord, float val) [static]
Definition at line 113 of file clip_graph_ops.c.
References co, MouseSelectUserData::coord, copy_v2_v2(), data, dist_to_line_segment_v2(), MovieTrackingMarker::framenr, MouseSelectUserData::has_prev, MouseSelectUserData::min_co, MouseSelectUserData::min_dist, MouseSelectUserData::mouse_co, NULL, MouseSelectUserData::prev_co, MouseSelectUserData::track, and TRUE.
Referenced by mouse_select_curve().
void find_nearest_tracking_segment_end_cb (void * userdata)
Definition at line 134 of file clip_graph_ops.c.
References data, FALSE, and MouseSelectUserData::has_prev.
Referenced by mouse_select_curve().
static int graph_disable_markers_exec (bContext * C, wmOperator * op) [static]
Definition at line 645 of file clip_graph_ops.c.
References BKE_tracking_active_track(), CTX_wm_space_clip(), DAG_id_tag_update(), ED_space_clip(), MovieTrackingMarker::flag, MovieTrackingTrack::flag, MovieClip::id, MARKER_DISABLED, MARKER_GRAPH_SEL, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, NA_EVALUATED, NC_MOVIECLIP, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), TRACK_LOCKED, MovieClip::tracking, and WM_event_add_notifier().
Referenced by CLIP_OT_graph_disable_markers().
static int graph_select_all_markers_exec (bContext * C, wmOperator * op) [static]
Definition at line 399 of file clip_graph_ops.c.
References BKE_tracking_active_track(), CTX_wm_space_clip(), ED_space_clip(), MovieTrackingMarker::flag, MARKER_GRAPH_SEL, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, NC_GEOM, ND_SELECT, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, MovieClip::tracking, and WM_event_add_notifier().
Referenced by CLIP_OT_graph_select_all_markers().
static int mouse_select (bContext * C, float co[2], int extend) [static]
Definition at line 250 of file clip_graph_ops.c.
References FALSE, mouse_select_curve(), mouse_select_knot(), NC_GEOM, ND_SELECT, NULL, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by select_exec().
static int mouse_select_curve (bContext * C, float co[2], int extend) [static]
Definition at line 210 of file clip_graph_ops.c.
References MovieTracking::act_track, BKE_tracking_active_track(), BKE_tracking_get_marker(), clip_graph_tracking_iterate(), clip_graph_tracking_values_iterate(), clip_view_center_to_point(), CTX_wm_space_clip(), ED_space_clip(), FALSE, find_nearest_tracking_segment_cb(), find_nearest_tracking_segment_end_cb(), MovieClipUser::framenr, mouse_select_init_data(), NULL, MovieTrackingMarker::pos, SEL_DESELECT, toggle_selection_cb(), MouseSelectUserData::track, MovieClip::tracking, TRUE, and SpaceClip::user.
Referenced by mouse_select().
static void mouse_select_init_data (MouseSelectUserData * userdata, float * co) [static]
Definition at line 160 of file clip_graph_ops.c.
References copy_v2_v2(), FLT_MAX, MouseSelectUserData::min_dist, and MouseSelectUserData::mouse_co.
Referenced by mouse_select_curve(), and mouse_select_knot().
static int mouse_select_knot (bContext * C, float co[2], int extend) [static]
Definition at line 167 of file clip_graph_ops.c.
References abs(), BKE_tracking_active_track(), clip_graph_tracking_iterate(), clip_graph_tracking_values_iterate_track(), MouseSelectUserData::coord, CTX_wm_region(), CTX_wm_space_clip(), ED_space_clip(), FALSE, find_nearest_tracking_knot_cb(), MovieTrackingMarker::flag, MouseSelectUserData::marker, MARKER_GRAPH_SEL_X, MARKER_GRAPH_SEL_Y, MouseSelectUserData::min_co, mouse_select_init_data(), NULL, SEL_DESELECT, toggle_selection_cb(), MovieClip::tracking, TRUE, UI_view2d_view_to_region(), and ARegion::v2d.
Referenced by mouse_select().
static int select_exec (bContext * C, wmOperator * op) [static]
Definition at line 268 of file clip_graph_ops.c.
References co, mouse_select(), wmOperator::ptr, RNA_boolean_get(), and RNA_float_get_array().
Referenced by CLIP_OT_graph_select(), and select_invoke().
static int select_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 278 of file clip_graph_ops.c.
References co, CTX_wm_region(), wmEvent::mval, wmOperator::ptr, RNA_float_set_array(), select_exec(), UI_view2d_region_to_view(), and ARegion::v2d.
Referenced by CLIP_OT_graph_select().
static void toggle_selection_cb (void * userdata, MovieTrackingMarker * marker) [static]
Definition at line 81 of file clip_graph_ops.c.
References SelectUserData::action, data, MovieTrackingMarker::flag, MARKER_GRAPH_SEL, SEL_DESELECT, SEL_INVERT, and SEL_SELECT.
Referenced by mouse_select_curve(), and mouse_select_knot().
static void view_all_cb (void * userdata, MovieTrackingTrack * UNUSEDtrack, MovieTrackingMarker * UNUSEDmarker, int UNUSEDcoord, float val) [static]
Definition at line 542 of file clip_graph_ops.c.
References data, ViewAllUserData::max, min, and ViewAllUserData::min.
Referenced by view_all_exec().
static int view_all_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 554 of file clip_graph_ops.c.
References clip_graph_tracking_values_iterate(), CTX_data_scene(), CTX_wm_region(), CTX_wm_space_clip(), View2D::cur, ED_region_tag_redraw(), EFRA, FLT_MAX, ViewAllUserData::max, ViewAllUserData::min, NULL, OPERATOR_FINISHED, SFRA, ARegion::v2d, view_all_cb(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by CLIP_OT_graph_view_all().