Blender: screendump.c File Reference
screendump.c File Reference
screen
#include <string.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "DNA_userdef_types.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_image.h"
#include "BKE_report.h"
#include "BKE_writeavi.h"
#include "BIF_gl.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "UI_interface.h"
#include "WM_types.h"
#include "WM_api.h"
#include "PIL_time.h"
#include "ED_screen_types.h"
#include "screen_intern.h"
Classes
struct ScreenshotData
struct ScreenshotJob
Typedefs
typedef struct ScreenshotData ScreenshotData
typedef struct ScreenshotJob ScreenshotJob
Functions
static unsigned int * screenshot (bContext *C, int *dumpsx, int *dumpsy)
static int screenshot_data_create (bContext *C, wmOperator *op)
static void screenshot_data_free (wmOperator *op)
static void screenshot_crop (ImBuf *ibuf, rcti crop)
static int screenshot_exec (bContext *C, wmOperator *op)
static int screenshot_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int screenshot_check (bContext *UNUSED(C), wmOperator *op)
static int screenshot_cancel (bContext *UNUSED(C), wmOperator *op)
static int screenshot_draw_check_prop (PointerRNA *UNUSED(ptr), PropertyRNA *prop)
static void screenshot_draw (bContext *UNUSED(C), wmOperator *op)
void SCREEN_OT_screenshot (wmOperatorType *ot)
static void screenshot_freejob (void *sjv)
static void screenshot_updatejob (void *sjv)
static void screenshot_startjob (void *sjv, short *stop, short *do_update, float *UNUSED(progress))
static int screencast_exec (bContext *C, wmOperator *op)
void SCREEN_OT_screencast (wmOperatorType *ot)
Detailed Description
Definition in file screendump.c.
Typedef Documentation
typedef struct ScreenshotData ScreenshotData
typedef struct ScreenshotJob ScreenshotJob
Function Documentation
void SCREEN_OT_screencast (wmOperatorType * ot)
Definition at line 432 of file screendump.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, PROP_FILEPATH, PROP_STRING, RNA_def_boolean(), RNA_def_property(), screencast_exec(), wmOperatorType::srna, WM_operator_confirm(), and WM_operator_winactive().
Referenced by ED_operatortypes_screen().
void SCREEN_OT_screenshot (wmOperatorType * ot)
Definition at line 254 of file screendump.c.
References wmOperatorType::cancel, wmOperatorType::check, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_SAVE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, IMAGEFILE, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), screenshot_cancel(), screenshot_check(), screenshot_draw(), screenshot_exec(), screenshot_invoke(), wmOperatorType::srna, wmOperatorType::ui, WM_FILESEL_FILEPATH, WM_operator_properties_filesel(), and WM_operator_winactive().
Referenced by ED_operatortypes_screen().
static int screencast_exec (bContext * C, wmOperator * op) [static]
Definition at line 394 of file screendump.c.
References BKE_reports_init(), ScreenshotJob::bmain, CTX_data_main(), CTX_data_scene(), CTX_wm_area(), CTX_wm_manager(), CTX_wm_screen(), CTX_wm_window(), ScreenshotJob::dumpsx, ScreenshotJob::dumpsy, MEM_callocN(), NC_SCREEN, ND_SCREENCAST, NULL, OPERATOR_FINISHED, wmOperator::ptr, ScreenshotJob::reports, RNA_boolean_get(), RPT_PRINT, ScreenshotJob::scene, screenshot_freejob(), screenshot_startjob(), screenshot_updatejob(), wmWindow::sizex, wmWindow::sizey, ScrArea::totrct, WM_event_add_notifier(), WM_jobs_callbacks(), WM_jobs_customdata(), WM_jobs_get(), WM_jobs_start(), WM_jobs_timer(), ScreenshotJob::x, rcti::xmax, rcti::xmin, ScreenshotJob::y, rcti::ymax, and rcti::ymin.
Referenced by SCREEN_OT_screencast().
static unsigned int* screenshot (bContext * C, int * dumpsx, int * dumpsy) [static]
Definition at line 79 of file screendump.c.
References CTX_wm_window(), MEM_mallocN(), NULL, wmWindow::sizex, and wmWindow::sizey.
Referenced by screenshot_data_create().
static int screenshot_cancel (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 225 of file screendump.c.
References OPERATOR_CANCELLED, and screenshot_data_free().
Referenced by SCREEN_OT_screenshot().
static int screenshot_check (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 219 of file screendump.c.
References wmOperator::customdata, ScreenshotData::im_format, ImageFormatData::imtype, and WM_operator_filesel_ensure_ext_imtype().
Referenced by SCREEN_OT_screenshot().
static void screenshot_crop (ImBuf * ibuf, rcti crop) [static]
Definition at line 148 of file screendump.c.
References ImBuf::rect, ImBuf::x, rcti::xmax, rcti::xmin, ImBuf::y, rcti::ymax, and rcti::ymin.
Referenced by screenshot_exec().
static int screenshot_data_create (bContext * C, wmOperator * op) [static]
Definition at line 103 of file screendump.c.
References BKE_imformat_defaults(), ScreenshotData::crop, CTX_wm_area(), wmOperator::customdata, ScreenshotData::dumprect, ScreenshotData::dumpsx, ScreenshotData::dumpsy, FALSE, ScreenshotData::im_format, MEM_callocN(), NULL, screenshot(), ScrArea::totrct, TRUE, and WM_redraw_windows().
Referenced by screenshot_exec(), and screenshot_invoke().
static void screenshot_data_free (wmOperator * op) [static]
Definition at line 136 of file screendump.c.
References wmOperator::customdata, ScreenshotData::dumprect, MEM_freeN(), and NULL.
Referenced by screenshot_cancel(), and screenshot_exec().
static void screenshot_draw (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 238 of file screendump.c.
References wmOperator::customdata, ScreenshotData::im_format, wmOperator::layout, NULL, wmOperator::properties, RNA_ImageFormatSettings, RNA_pointer_create(), screenshot_draw_check_prop(), wmOperatorType::srna, wmOperator::type, uiDefAutoButsRNA(), and uiTemplateImageSettings().
Referenced by SCREEN_OT_screenshot().
static int screenshot_draw_check_prop (PointerRNA * UNUSEDptr, PropertyRNA * prop) [static]
Definition at line 231 of file screendump.c.
References RNA_property_identifier().
Referenced by screenshot_draw().
static int screenshot_exec (bContext * C, wmOperator * op) [static]
Definition at line 163 of file screendump.c.
References BKE_write_ibuf(), BLI_path_abs(), ScreenshotData::crop, wmOperator::customdata, ScreenshotData::dumprect, ScreenshotData::dumpsx, ScreenshotData::dumpsy, FILE_MAX, G, ScreenshotData::im_format, IMB_allocImBuf(), IMB_color_to_bw(), IMB_freeImBuf(), NULL, OPERATOR_FINISHED, ImageFormatData::planes, wmOperator::ptr, R_IMF_PLANES_BW, ImBuf::rect, RNA_boolean_get(), RNA_string_get(), screenshot_crop(), screenshot_data_create(), and screenshot_data_free().
Referenced by SCREEN_OT_screenshot(), and screenshot_invoke().
static void screenshot_freejob (void * sjv) [static]
Definition at line 285 of file screendump.c.
References ScreenshotJob::dumprect, and MEM_freeN().
Referenced by screencast_exec().
static int screenshot_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 203 of file screendump.c.
References G, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_string_set(), RNA_struct_property_is_set(), screenshot_data_create(), screenshot_exec(), and WM_event_add_fileselect().
Referenced by SCREEN_OT_screenshot().
static void screenshot_startjob (void * sjv, short * stop, short * do_update, float * UNUSEDprogress) [static]
Definition at line 313 of file screendump.c.
References bMovieHandle::append_movie, BKE_get_movie_handle(), BKE_imtype_is_movie(), BKE_makepicstring(), BKE_report(), BKE_reportf(), BKE_write_ibuf(), ScreenshotJob::bmain, RenderData::cfra, ScreenshotJob::do_update, ScreenshotJob::dumprect, ScreenshotJob::dumpsx, ScreenshotJob::dumpsy, bMovieHandle::end_movie, FILE_MAX, RenderData::frs_sec, RenderData::frs_sec_base, RenderData::im_format, IMB_allocImBuf(), IMB_freeImBuf(), ImageFormatData::imtype, MEM_freeN(), Main::name, NULL, RenderData::pic, PIL_sleep_ms(), ImageFormatData::planes, Scene::r, R_EXTENSION, ImBuf::rect, ScreenshotJob::reports, RPT_INFO, RenderData::scemode, ScreenshotJob::scene, RenderData::sfra, bMovieHandle::start_movie, ScreenshotJob::stop, and TRUE.
Referenced by screencast_exec().
static void screenshot_updatejob (void * sjv) [static]
Definition at line 297 of file screendump.c.
References ScreenshotJob::dumprect, ScreenshotJob::dumpsx, ScreenshotJob::dumpsy, MEM_mallocN(), NULL, ScreenshotJob::x, and ScreenshotJob::y.
Referenced by screencast_exec().