Blender: rna_vfont.c File Reference
rna_vfont.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_vfont_types.h"
Functions
void RNA_def_vfont (BlenderRNA *brna)
Detailed Description
Definition in file rna_vfont.c.
Function Documentation
void RNA_def_vfont (BlenderRNA * brna)
Definition at line 40 of file rna_vfont.c.
References NULL, PROP_EDITABLE, PROP_FILEPATH, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().