Blender: KX_CameraActuator.cpp File Reference
KX_CameraActuator.cpp File Reference
Ketsji
#include "KX_CameraActuator.h"
#include <iostream>
#include <math.h>
#include <float.h>
#include "KX_GameObject.h"
#include "PyObjectPlus.h"
Functions
static float Kx_Normalize (float *n)
static void Kx_Crossf (float *c, float *a, float *b)
static void Kx_VecUpMat3 (float vec[3], float mat[][3], short axis)
Detailed Description
Definition in file KX_CameraActuator.cpp.
Function Documentation
static void Kx_Crossf (float * c, float * a, float * b) [static]
Definition at line 137 of file KX_CameraActuator.cpp.
Referenced by Kx_VecUpMat3().
static float Kx_Normalize (float * n) [static]
Definition at line 118 of file KX_CameraActuator.cpp.
References sqrt().
Referenced by Kx_VecUpMat3().
static void Kx_VecUpMat3 (float vec[3], float mat[][3], short axis) [static]
Definition at line 145 of file KX_CameraActuator.cpp.
References Kx_Crossf(), and Kx_Normalize().
Referenced by KX_CameraActuator::Update().