Blender: CProfileIterator Class Reference
CProfileIterator Class Reference
An iterator to navigate through the tree.
#include <btQuickprof.h>
Public Member Functions
void First (void)
void Next (void)
bool Is_Done (void)
bool Is_Root (void)
void Enter_Child (int index)
void Enter_Largest_Child (void)
void Enter_Parent (void)
const char * Get_Current_Name (void)
int Get_Current_Total_Calls (void)
float Get_Current_Total_Time (void)
const char * Get_Current_Parent_Name (void)
int Get_Current_Parent_Total_Calls (void)
float Get_Current_Parent_Total_Time (void)
Protected Member Functions
CProfileIterator (CProfileNode *start)
Protected Attributes
CProfileNode * CurrentParent
CProfileNode * CurrentChild
Friends
class CProfileManager
Detailed Description
An iterator to navigate through the tree.
Definition at line 100 of file btQuickprof.h.
Constructor & Destructor Documentation
CProfileIterator::CProfileIterator (CProfileNode * start) [protected]
Definition at line 369 of file btQuickprof.cpp.
References CurrentChild, CurrentParent, and CProfileNode::Get_Child().
Member Function Documentation
void CProfileIterator::Enter_Child (int index)
Definition at line 394 of file btQuickprof.cpp.
References CurrentChild, CurrentParent, CProfileNode::Get_Child(), CProfileNode::Get_Sibling(), and NULL.
Referenced by CProfileManager::dumpRecursive().
void CProfileIterator::Enter_Largest_Child (void)
void CProfileIterator::Enter_Parent (void)
Definition at line 409 of file btQuickprof.cpp.
References CurrentChild, CurrentParent, CProfileNode::Get_Child(), CProfileNode::Get_Parent(), and NULL.
Referenced by CProfileManager::dumpRecursive().
void CProfileIterator::First (void)
Definition at line 376 of file btQuickprof.cpp.
References CurrentChild, CurrentParent, and CProfileNode::Get_Child().
Referenced by CProfileManager::dumpRecursive().
const char* CProfileIterator::Get_Current_Name (void) [inline]
Definition at line 114 of file btQuickprof.h.
References CurrentChild, and CProfileNode::Get_Name().
Referenced by CProfileManager::dumpRecursive().
const char* CProfileIterator::Get_Current_Parent_Name (void) [inline]
Definition at line 119 of file btQuickprof.h.
References CurrentParent, and CProfileNode::Get_Name().
Referenced by CProfileManager::dumpRecursive().
int CProfileIterator::Get_Current_Parent_Total_Calls (void) [inline]
Definition at line 120 of file btQuickprof.h.
References CurrentParent, and CProfileNode::Get_Total_Calls().
float CProfileIterator::Get_Current_Parent_Total_Time (void) [inline]
Definition at line 121 of file btQuickprof.h.
References CurrentParent, and CProfileNode::Get_Total_Time().
Referenced by CProfileManager::dumpRecursive().
int CProfileIterator::Get_Current_Total_Calls (void) [inline]
Definition at line 115 of file btQuickprof.h.
References CurrentChild, and CProfileNode::Get_Total_Calls().
Referenced by CProfileManager::dumpRecursive().
float CProfileIterator::Get_Current_Total_Time (void) [inline]
Definition at line 116 of file btQuickprof.h.
References CurrentChild, and CProfileNode::Get_Total_Time().
Referenced by CProfileManager::dumpRecursive().
bool CProfileIterator::Is_Done (void)
Definition at line 388 of file btQuickprof.cpp.
References CurrentChild, and NULL.
Referenced by CProfileManager::dumpRecursive().
bool CProfileIterator::Is_Root (void) [inline]
Definition at line 107 of file btQuickprof.h.
References CurrentParent, and CProfileNode::Get_Parent().
Referenced by CProfileManager::dumpRecursive().
void CProfileIterator::Next (void)
Definition at line 382 of file btQuickprof.cpp.
References CurrentChild, and CProfileNode::Get_Sibling().
Referenced by CProfileManager::dumpRecursive().
Friends And Related Function Documentation
friend class CProfileManager [friend]
Definition at line 129 of file btQuickprof.h.
Member Data Documentation
CProfileNode* CProfileIterator::CurrentChild [protected]
Definition at line 126 of file btQuickprof.h.
Referenced by CProfileIterator(), Enter_Child(), Enter_Parent(), First(), Get_Current_Name(), Get_Current_Total_Calls(), Get_Current_Total_Time(), Is_Done(), and Next().
CProfileNode* CProfileIterator::CurrentParent [protected]
Definition at line 125 of file btQuickprof.h.
Referenced by CProfileIterator(), Enter_Child(), Enter_Parent(), First(), Get_Current_Parent_Name(), Get_Current_Parent_Total_Calls(), Get_Current_Parent_Total_Time(), and Is_Root().
The documentation for this class was generated from the following files:
btQuickprof.h
btQuickprof.cpp