Blender: GHOST_WindowCarbon.cpp File Reference
GHOST_WindowCarbon.cpp File Reference
GHOST API
#include "GHOST_WindowCarbon.h"
#include "GHOST_Debug.h"
Defines
#define GCMAP(ghostCursor, carbonCursor) case ghostCursor: carbon_cursor = carbonCursor; break
Functions
static OSStatus myWEventHandlerProc (EventHandlerCallRef handler, EventRef event, void *userData)
static GHOST_TUns16 uns16ReverseBits (GHOST_TUns16 shrt)
Variables
static const GLint sPreferredFormatWindow [10]
static const GLint sPreferredFormatFullScreen [11]
WindowRef ugly_hack = NULL
const EventTypeSpec kWEvents []
Detailed Description
Definition in file GHOST_WindowCarbon.cpp.
Define Documentation
#define GCMAP (ghostCursor, carbonCursor) case ghostCursor: carbon_cursor = carbonCursor; break
Referenced by GHOST_WindowCarbon::loadCursor().
Function Documentation
static OSStatus myWEventHandlerProc (EventHandlerCallRef handler, EventRef event, void * userData) [static]
Definition at line 73 of file GHOST_WindowCarbon.cpp.
References err, GHOST_WindowCarbon::getMac_windowState(), NULL, and GHOST_WindowCarbon::setMac_windowState().
Referenced by GHOST_WindowCarbon::GHOST_WindowCarbon().
static GHOST_TUns16 uns16ReverseBits (GHOST_TUns16 shrt) [static]
Reverse the bits in a GHOST_TUns16
Definition at line 689 of file GHOST_WindowCarbon.cpp.
Referenced by GHOST_WindowCarbon::setWindowCustomCursorShape().
Variable Documentation
const EventTypeSpec kWEvents[]
Initial value:
 {
    { kEventClassWindow, kEventWindowZoom },
}
Definition at line 69 of file GHOST_WindowCarbon.cpp.
Referenced by GHOST_WindowCarbon::GHOST_WindowCarbon().
const GLint sPreferredFormatFullScreen[11] [static]
Initial value:
 {
AGL_RGBA,
AGL_DOUBLEBUFFER,
AGL_ACCELERATED,
AGL_FULLSCREEN,
AGL_DEPTH_SIZE,     32,
AGL_NONE,
}
Definition at line 56 of file GHOST_WindowCarbon.cpp.
Referenced by GHOST_WindowCarbon::installDrawingContext().
const GLint sPreferredFormatWindow[10] [static]
Initial value:
 {
AGL_RGBA,
AGL_DOUBLEBUFFER,
AGL_ACCELERATED,
AGL_DEPTH_SIZE,     32,
AGL_NONE,
}
Definition at line 48 of file GHOST_WindowCarbon.cpp.
Referenced by GHOST_WindowCarbon::installDrawingContext().
WindowRef ugly_hack = NULL
Definition at line 67 of file GHOST_WindowCarbon.cpp.
Referenced by GHOST_WindowCarbon::GHOST_WindowCarbon(), and GHOST_WindowCarbon::~GHOST_WindowCarbon().