Blender: btSoftSoftCollisionAlgorithm Class Reference
btSoftSoftCollisionAlgorithm Class Reference
collision detection between two btSoftBody shapes
#include <btSoftSoftCollisionAlgorithm.h>
Classes
struct CreateFunc
Public Member Functions
btSoftSoftCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo &ci)
virtual void processCollision (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
virtual btScalar calculateTimeOfImpact (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
virtual void getAllContactManifolds (btManifoldArray &manifoldArray)
btSoftSoftCollisionAlgorithm (btPersistentManifold *mf, const btCollisionAlgorithmConstructionInfo &ci, btCollisionObject *body0, btCollisionObject *body1)
virtual ~btSoftSoftCollisionAlgorithm ()
Detailed Description
collision detection between two btSoftBody shapes
Definition at line 28 of file btSoftSoftCollisionAlgorithm.h.
Constructor & Destructor Documentation
btSoftSoftCollisionAlgorithm::btSoftSoftCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo & ci) [inline]
Definition at line 38 of file btSoftSoftCollisionAlgorithm.h.
Referenced by btSoftSoftCollisionAlgorithm::CreateFunc::CreateCollisionAlgorithm().
btSoftSoftCollisionAlgorithm::btSoftSoftCollisionAlgorithm (btPersistentManifold * mf, const btCollisionAlgorithmConstructionInfo & ci, btCollisionObject * body0, btCollisionObject * body1)
Definition at line 25 of file btSoftSoftCollisionAlgorithm.cpp.
btSoftSoftCollisionAlgorithm::~btSoftSoftCollisionAlgorithm () [virtual]
Definition at line 32 of file btSoftSoftCollisionAlgorithm.cpp.
Member Function Documentation
btScalar btSoftSoftCollisionAlgorithm::calculateTimeOfImpact (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Implements btCollisionAlgorithm.
Definition at line 43 of file btSoftSoftCollisionAlgorithm.cpp.
virtual void btSoftSoftCollisionAlgorithm::getAllContactManifolds (btManifoldArray & manifoldArray) [inline, virtual]
Implements btCollisionAlgorithm.
Definition at line 45 of file btSoftSoftCollisionAlgorithm.h.
References btAlignedObjectArray< T >::push_back().
void btSoftSoftCollisionAlgorithm::processCollision (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Implements btCollisionAlgorithm.
Definition at line 36 of file btSoftSoftCollisionAlgorithm.cpp.
References btSoftBody::getSoftBodySolver(), and btSoftBodySolver::processCollision().
The documentation for this class was generated from the following files:
btSoftSoftCollisionAlgorithm.h
btSoftSoftCollisionAlgorithm.cpp