Blender: GPG_ghost.cpp File Reference
GPG_ghost.cpp File Reference
Game Player
#include <iostream>
#include <math.h>
#include "KX_KetsjiEngine.h"
#include "KX_PythonInit.h"
#include "MEM_guardedalloc.h"
#include "BKE_blender.h"
#include "BKE_global.h"
#include "BKE_icons.h"
#include "BKE_node.h"
#include "BKE_report.h"
#include "BKE_library.h"
#include "BLI_threads.h"
#include "BLI_blenlib.h"
#include "DNA_scene_types.h"
#include "DNA_userdef_types.h"
#include "BLO_readfile.h"
#include "BLO_runtime.h"
#include "IMB_imbuf.h"
#include "BKE_text.h"
#include "BKE_sound.h"
#include "BLF_api.h"
#include "BLF_translation.h"
#include "GPU_draw.h"
#include "BL_System.h"
#include "GPG_Application.h"
#include "GHOST_ISystem.h"
#include "RAS_IRasterizer.h"
#include "BKE_main.h"
#include "BKE_utildefines.h"
#include "RNA_define.h"
Functions
int GHOST_HACK_getFirstFile (char buf[])
static void mem_error_cb (const char *errorStr)
void usage (const char *program, bool isBlenderPlayer)
static void get_filename (int argc, char **argv, char *filename)
static BlendFileData * load_game_data (const char *progname, char *filename=NULL, char *relativename=NULL)
int main (int argc, char **argv)
Variables
int datatoc_bfont_ttf_size
char datatoc_bfont_ttf []
const int kMinWindowWidth = 100
const int kMinWindowHeight = 100
Detailed Description
Definition in file GPG_ghost.cpp.
Function Documentation
static void get_filename (int argc, char ** argv, char * filename) [static]
Definition at line 258 of file GPG_ghost.cpp.
References BLI_exists(), BLI_strncpy(), FILE_MAX, GHOST_HACK_getFirstFile(), NULL, and strlen().
Referenced by main().
int GHOST_HACK_getFirstFile (char buf[])
Referenced by get_filename(), and main().
static BlendFileData* load_game_data (const char * progname, char * filename = NULL, char * relativename = NULL) [static]
Definition at line 305 of file GPG_ghost.cpp.
References BKE_reports_clear(), BKE_reports_init(), BKE_reports_print(), BLENFILETYPE_RUNTIME, BLI_strncpy(), BLO_is_a_runtime(), BLO_read_from_file(), BLO_read_runtime(), BlendFileData::main, Main::name, NULL, RPT_ERROR, RPT_STORE, and BlendFileData::type.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 336 of file GPG_ghost.cpp.
References GameData::aasamples, add_text(), GHOST_ISystem::addEventConsumer(), GameDome::angle, assertd, BKE_icons_free(), BKE_icons_init(), BLF_exit(), BLF_init(), BLF_lang_encoding(), BLF_lang_init(), BLF_lang_set(), BLF_load_mem(), BLI_init_program_path(), BLI_init_temporary_dir(), BLI_path_abs(), BLI_path_cwd(), BLI_program_path(), BLI_strncpy(), BLI_threadapi_init(), BLO_blendfiledata_free(), BLO_is_a_runtime(), GHOST_ISystem::createSystem(), BlendFileData::curscene, datatoc_bfont_ttf, datatoc_bfont_ttf_size, GameData::depth, GHOST_ISystem::dispatchEvents(), GHOST_ISystem::disposeSystem(), GameData::dome, DOME_ENVMAP, DOME_FISHEYE, DOME_PANORAM_SPH, DOME_TRUNCATED_FRONT, DOME_TRUNCATED_REAR, error(), STR_String::Explode(), FILE_MAX, BlendFileData::fileflags, GameData::flag, free_main(), free_nodesystem(), GameData::freqplay, G, G_DEBUG, GAME_PLAYER_DESKTOP_RESOLUTION, GAME_PLAYER_FULLSCREEN, get_filename(), GPG_Application::getExitRequested(), GPG_Application::getExitString(), GPG_Application::getGlobalSettings(), GHOST_ISystem::getMainDisplayDimensions(), GHOST_ISystem::getSystem(), GHOST_kSuccess, GlobalSettings::glslflag, Scene::gm, GPU_set_anisotropic(), GPU_set_mipmap(), i, if(), IMB_exit(), IMB_init(), init_nodesystem(), initglobals(), kMinWindowHeight, kMinWindowWidth, KX_EXIT_REQUEST_NO_REQUEST, KX_EXIT_REQUEST_QUIT_GAME, KX_EXIT_REQUEST_RESTART_GAME, KX_EXIT_REQUEST_START_OTHER_GAME, load_game_data(), BlendFileData::main, GameData::matmode, GlobalSettings::matmode, mem_error_cb(), MEM_get_memory_blocks_in_use(), MEM_printmemlist(), MEM_set_error_callback(), MEM_set_memory_debug(), GameDome::mode, Main::name, NULL, GameData::playerflag, GHOST_ISystem::processEvents(), STR_String::Ptr(), RAS_IRasterizer::RAS_STEREO_ABOVEBELOW, RAS_IRasterizer::RAS_STEREO_ANAGLYPH, RAS_IRasterizer::RAS_STEREO_DOME, RAS_IRasterizer::RAS_STEREO_MAXSTEREO, RAS_IRasterizer::RAS_STEREO_NOSTEREO, RAS_IRasterizer::RAS_STEREO_QUADBUFFERED, RAS_IRasterizer::RAS_STEREO_SIDEBYSIDE, RAS_IRasterizer::RAS_STEREO_VINTERLACE, GHOST_ISystem::removeEventConsumer(), RNA_exit(), RNA_init(), GPG_Application::SetGameEngineData(), sound_init_once(), GPG_Application::startEmbeddedWindow(), GPG_Application::startFullScreen(), GPG_Application::StartGameEngine(), GPG_Application::startWindow(), STEREO_DOME, STEREO_ENABLED, STEREO_NOSTEREO, GameData::stereoflag, GameData::stereomode, GPG_Application::StopGameEngine(), SYS_DeleteSystem(), SYS_GetCommandLineInt(), SYS_GetSystem(), SYS_WriteCommandLineFloat(), SYS_WriteCommandLineInt(), SYS_WriteCommandLineString(), GameDome::tilt, GHOST_ISystem::toggleConsole(), totblock, usage(), USER_DISABLE_VBO, GameDome::warptext, GameData::xplay, and GameData::yplay.
static void mem_error_cb (const char * errorStr) [static]
Definition at line 114 of file GPG_ghost.cpp.
Referenced by main().
void usage (const char * program, bool isBlenderPlayer)
Definition at line 176 of file GPG_ghost.cpp.
Referenced by main().
Variable Documentation
char datatoc_bfont_ttf[]
Definition at line 7 of file bfont.ttf.c.
int datatoc_bfont_ttf_size
Definition at line 6 of file bfont.ttf.c.
const int kMinWindowHeight = 100
Definition at line 112 of file GPG_ghost.cpp.
Referenced by main().
const int kMinWindowWidth = 100
Definition at line 111 of file GPG_ghost.cpp.
Referenced by main().