Blender: emissive.h File Reference
emissive.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device float3 emissive_eval (const float3 Ng, const float3 I)
__device float emissive_pdf (const float3 Ng, const float3 I)
__device float3 svm_emissive_eval (ShaderData *sd, ShaderClosure *sc)
Function Documentation
CCL_NAMESPACE_BEGIN __device float3 emissive_eval (const float3 Ng, const float3 I)
Definition at line 37 of file emissive.h.
References dot(), fabsf, and make_float3().
Referenced by shader_emissive_eval(), and svm_emissive_eval().
__device float emissive_pdf (const float3 Ng, const float3 I)
Return the probability distribution function in the direction I, given the parameters and the light's surface normal. This MUST match the PDF computed by sample().
Definition at line 48 of file emissive.h.
References dot(), and fabsf.
__device float3 svm_emissive_eval (ShaderData * sd, ShaderClosure * sc)
Definition at line 54 of file emissive.h.
References emissive_eval(), ShaderData::I, and ShaderData::Ng.
Referenced by shader_emissive_eval().