Blender: DisplayBuffer Class Reference
DisplayBuffer Class Reference
#include <buffers.h>
Public Member Functions
DisplayBuffer (Device *device)
~DisplayBuffer ()
void reset (Device *device, BufferParams &params)
void write (Device *device, const string &filename)
void draw_set (int width, int height)
void draw (Device *device)
bool draw_ready ()
Public Attributes
BufferParams params
int draw_width
int draw_height
bool transparent
device_vector< uchar4 > rgba
thread_mutex mutex
Protected Member Functions
void device_free ()
Protected Attributes
Device * device
Detailed Description
Definition at line 96 of file buffers.h.
Constructor & Destructor Documentation
DisplayBuffer::DisplayBuffer (Device * device)
Definition at line 246 of file buffers.cpp.
References device, draw_height, draw_width, and transparent.
DisplayBuffer::~DisplayBuffer ()
Definition at line 254 of file buffers.cpp.
References device_free().
Member Function Documentation
void DisplayBuffer::device_free () [protected]
Definition at line 259 of file buffers.cpp.
References device_vector< T >::clear(), device, device_memory::device_pointer, Device::pixels_free(), and rgba.
Referenced by reset(), and ~DisplayBuffer().
void DisplayBuffer::draw (Device * device)
Definition at line 290 of file buffers.cpp.
References draw_height, Device::draw_pixels(), draw_width, BufferParams::height, params, rgba, transparent, and BufferParams::width.
Referenced by Session::draw_cpu(), and Session::draw_gpu().
bool DisplayBuffer::draw_ready ()
Definition at line 296 of file buffers.cpp.
References draw_height, and draw_width.
Referenced by Session::draw_cpu().
void DisplayBuffer::draw_set (int width, int height)
Definition at line 282 of file buffers.cpp.
References assert, draw_height, draw_width, BufferParams::height, params, and BufferParams::width.
Referenced by Session::tonemap().
void DisplayBuffer::reset (Device * device, BufferParams & params)
Definition at line 267 of file buffers.cpp.
References device_free(), draw_height, draw_width, BufferParams::height, params, Device::pixels_alloc(), device_vector< T >::resize(), rgba, and BufferParams::width.
Referenced by Session::reset_().
void DisplayBuffer::write (Device * device, const string & filename)
Definition at line 301 of file buffers.cpp.
References device_memory::data_pointer, draw_height, draw_width, Device::pixels_copy_from(), rgba, spec(), and uchar.
Referenced by Session::~Session().
Member Data Documentation
Device* DisplayBuffer::device [protected]
Definition at line 124 of file buffers.h.
Referenced by device_free(), and DisplayBuffer().
int DisplayBuffer::draw_height
Definition at line 103 of file buffers.h.
Referenced by DisplayBuffer(), draw(), draw_ready(), draw_set(), reset(), and write().
int DisplayBuffer::draw_width
Definition at line 103 of file buffers.h.
Referenced by DisplayBuffer(), draw(), draw_ready(), draw_set(), reset(), and write().
thread_mutex DisplayBuffer::mutex
Definition at line 109 of file buffers.h.
Referenced by Session::draw_cpu(), Session::draw_gpu(), Session::reset_gpu(), and Session::run_cpu().
BufferParams DisplayBuffer::params
Definition at line 99 of file buffers.h.
Referenced by draw(), Session::draw_cpu(), Session::draw_gpu(), draw_set(), and reset().
device_vector<uchar4> DisplayBuffer::rgba
Definition at line 107 of file buffers.h.
Referenced by device_free(), draw(), reset(), Session::tonemap(), and write().
bool DisplayBuffer::transparent
Definition at line 105 of file buffers.h.
Referenced by DisplayBuffer(), and draw().
The documentation for this class was generated from the following files:
buffers.h
buffers.cpp