Blender: KDL::TreeFkSolverPos_recursive Class Reference
KDL::TreeFkSolverPos_recursive Class Reference
#include <treefksolverpos_recursive.hpp>
Public Member Functions
TreeFkSolverPos_recursive (const Tree &tree)
~TreeFkSolverPos_recursive ()
virtual int JntToCart (const JntArray &q_in, Frame &p_out, const std::string &segmentName, const std::string &baseName)
Detailed Description
Implementation of a recursive forward position kinematics algorithm to calculate the position transformation from joint space to Cartesian space of a general kinematic tree (KDL::Tree).
Definition at line 37 of file treefksolverpos_recursive.hpp.
Constructor & Destructor Documentation
KDL::TreeFkSolverPos_recursive::TreeFkSolverPos_recursive (const Tree & tree)
Definition at line 31 of file treefksolverpos_recursive.cpp.
KDL::TreeFkSolverPos_recursive::~TreeFkSolverPos_recursive ()
Definition at line 68 of file treefksolverpos_recursive.cpp.
Member Function Documentation
int KDL::TreeFkSolverPos_recursive::JntToCart (const JntArray & q_in, Frame & p_out, const std::string & segmentName, const std::string & baseName) [virtual]
Calculate forward position kinematics for a KDL::Tree, from joint coordinates to cartesian pose.
Parameters:
q_in input joint coordinates
p_out reference to output cartesian pose
Returns:
if < 0 something went wrong
Implements KDL::TreeFkSolverPos.
Definition at line 36 of file treefksolverpos_recursive.cpp.
References KDL::Tree::getNrOfJoints(), KDL::Tree::getSegment(), KDL::Tree::getSegments(), and KDL::JntArray::rows().
Referenced by iTaSC::Armature::getRelativeFrame(), and iTaSC::Armature::updateJacobian().
The documentation for this class was generated from the following files:
treefksolverpos_recursive.hpp
treefksolverpos_recursive.cpp