Blender: KX_TrackToActuator.cpp File Reference
KX_TrackToActuator.cpp File Reference
Ketsji
#include "MT_Scalar.h"
#include "SCA_IActuator.h"
#include "KX_TrackToActuator.h"
#include "SCA_IScene.h"
#include "SCA_LogicManager.h"
#include <math.h>
#include <iostream>
#include "KX_GameObject.h"
#include "PyObjectPlus.h"
Functions
MT_Matrix3x3 EulToMat3 (float *eul)
void Mat3ToEulOld (MT_Matrix3x3 mat, float *eul)
void compatible_eulFast (float *eul, float *oldrot)
MT_Matrix3x3 matrix3x3_interpol (MT_Matrix3x3 oldmat, MT_Matrix3x3 mat, int m_time)
Detailed Description
Definition in file KX_TrackToActuator.cpp.
Function Documentation
void compatible_eulFast (float * eul, float * oldrot)
Definition at line 146 of file KX_TrackToActuator.cpp.
References fabs(), MT_2_PI(), and MT_PI().
Referenced by matrix3x3_interpol().
MT_Matrix3x3 EulToMat3 (float * eul)
Definition at line 94 of file KX_TrackToActuator.cpp.
References cos(), si, and sin().
Referenced by matrix3x3_interpol().
void Mat3ToEulOld (MT_Matrix3x3 mat, float * eul)
Definition at line 126 of file KX_TrackToActuator.cpp.
References KDL::atan2(), and sqrt().
Referenced by matrix3x3_interpol().
MT_Matrix3x3 matrix3x3_interpol (MT_Matrix3x3 oldmat, MT_Matrix3x3 mat, int m_time)
Definition at line 169 of file KX_TrackToActuator.cpp.
References compatible_eulFast(), EulToMat3(), and Mat3ToEulOld().
Referenced by KX_TrackToActuator::Update().