Blender: rna_scene_api.c File Reference
rna_scene_api.c File Reference
RNA
#include <stdlib.h>
#include <stdio.h>
#include "RNA_define.h"
#include "DNA_anim_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BKE_utildefines.h"
Functions
void RNA_api_scene (StructRNA *srna)
void RNA_api_scene_render (StructRNA *srna)
Detailed Description
Definition in file rna_scene_api.c.
Function Documentation
void RNA_api_scene (StructRNA * srna)
Definition at line 97 of file rna_scene_api.c.
References FILE_MAX, MAXFRAME, MINAFRAME, PROP_FILEPATH, PROP_REQUIRED, RNA_def_boolean(), RNA_def_float(), RNA_def_function(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_property_flag(), RNA_def_property_subtype(), and RNA_def_string().
Referenced by RNA_def_scene().
void RNA_api_scene_render (StructRNA * srna)
Definition at line 125 of file rna_scene_api.c.
References FILE_MAX, MAXFRAME, MINAFRAME, PROP_THICK_WRAP, RNA_def_function(), RNA_def_function_output(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_property_flag(), and RNA_def_string_file_path().
Referenced by rna_def_scene_render_data().