Blender: SphereTriangleDetector Struct Reference
SphereTriangleDetector Struct Reference
sphere-triangle to match the btDiscreteCollisionDetectorInterface
#include <SphereTriangleDetector.h>
Public Member Functions
virtual void getClosestPoints (const ClosestPointInput &input, Result &output, class btIDebugDraw *debugDraw, bool swapResults=false)
SphereTriangleDetector (btSphereShape *sphere, btTriangleShape *triangle, btScalar contactBreakingThreshold)
virtual ~SphereTriangleDetector ()
bool collide (const btVector3 &sphereCenter, btVector3 &point, btVector3 &resultNormal, btScalar &depth, btScalar &timeOfImpact, btScalar contactBreakingThreshold)
Detailed Description
sphere-triangle to match the btDiscreteCollisionDetectorInterface
Definition at line 29 of file SphereTriangleDetector.h.
Constructor & Destructor Documentation
SphereTriangleDetector::SphereTriangleDetector (btSphereShape * sphere, btTriangleShape * triangle, btScalar contactBreakingThreshold)
Definition at line 22 of file SphereTriangleDetector.cpp.
virtual SphereTriangleDetector::~SphereTriangleDetector () [inline, virtual]
Definition at line 35 of file SphereTriangleDetector.h.
Member Function Documentation
bool SphereTriangleDetector::collide (const btVector3 & sphereCenter, btVector3 & point, btVector3 & resultNormal, btScalar & depth, btScalar & timeOfImpact, btScalar contactBreakingThreshold)
Definition at line 94 of file SphereTriangleDetector.cpp.
References btSqrt(), cross(), distance(), i, SegmentSqrDistance(), and SIMD_EPSILON.
Referenced by getClosestPoints().
void SphereTriangleDetector::getClosestPoints (const ClosestPointInput & input, Result & output, class btIDebugDraw * debugDraw, bool swapResults = false) [virtual]
Implements btDiscreteCollisionDetectorInterface.
Definition at line 30 of file SphereTriangleDetector.cpp.
References btDiscreteCollisionDetectorInterface::Result::addContactPoint(), collide(), btTransform::getBasis(), btTransform::getOrigin(), btTransform::inverseTimes(), btDiscreteCollisionDetectorInterface::ClosestPointInput::m_transformA, and btDiscreteCollisionDetectorInterface::ClosestPointInput::m_transformB.
The documentation for this struct was generated from the following files:
SphereTriangleDetector.h
SphereTriangleDetector.cpp