Blender: AUD_LinearResampleReader Class Reference
AUD_LinearResampleReader Class Reference
#include <AUD_LinearResampleReader.h>
Public Member Functions
AUD_LinearResampleReader (AUD_Reference< AUD_IReader > reader, AUD_Specs specs)
virtual void seek (int position)
virtual int getLength () const
virtual int getPosition () const
virtual AUD_Specs getSpecs () const
virtual void read (int &length, bool &eos, sample_t *buffer)
Detailed Description
This resampling reader does simple first-order hold resampling.
Definition at line 39 of file AUD_LinearResampleReader.h.
Constructor & Destructor Documentation
AUD_LinearResampleReader::AUD_LinearResampleReader (AUD_Reference< AUD_IReader > reader, AUD_Specs specs)
Creates a resampling reader.
Parameters:
reader The reader to mix.
specs The target specification.
Definition at line 37 of file AUD_LinearResampleReader.cpp.
References AUD_SAMPLE_SIZE, AUD_Specs::channels, and AUD_Buffer::resize().
Member Function Documentation
int AUD_LinearResampleReader::getLength () const [virtual]
Returns an approximated length of the source in samples.
Returns:
The length as sample count. May be negative if unknown.
Reimplemented from AUD_EffectReader.
Definition at line 56 of file AUD_LinearResampleReader.cpp.
References AUD_ResampleReader::m_rate, and AUD_EffectReader::m_reader.
int AUD_LinearResampleReader::getPosition () const [virtual]
Returns the position of the source as a sample count value.
Returns:
The current position in the source. A negative value indicates that the position is unknown.
Warning:
The value returned doesn't always have to be correct for readers, especially after seeking.
Reimplemented from AUD_EffectReader.
Definition at line 61 of file AUD_LinearResampleReader.cpp.
References AUD_ResampleReader::m_rate, and AUD_EffectReader::m_reader.
AUD_Specs AUD_LinearResampleReader::getSpecs () const [virtual]
Returns the specification of the reader.
Returns:
The AUD_Specs structure.
Reimplemented from AUD_EffectReader.
Definition at line 67 of file AUD_LinearResampleReader.cpp.
References AUD_ResampleReader::m_rate, AUD_EffectReader::m_reader, and AUD_Specs::rate.
void AUD_LinearResampleReader::read (int & length, bool & eos, sample_t * buffer) [virtual]
Request to read the next length samples out of the source. The buffer supplied has the needed size.
Parameters:
[in,out] length The count of samples that should be read. Shall contain the real count of samples after reading, in case there were only fewer samples available. A smaller value also indicates the end of the reader.
[out] eos End of stream, whether the end is reached or not.
[in] buffer The pointer to the buffer to read into.
Reimplemented from AUD_EffectReader.
Definition at line 74 of file AUD_LinearResampleReader.cpp.
References AUD_Buffer::assureSize(), AUD_SAMPLE_SIZE, CC, AUD_Specs::channels, AUD_Buffer::getBuffer(), i, len(), length(), AUD_ResampleReader::m_rate, AUD_EffectReader::m_reader, AUD_Buffer::resize(), and size().
void AUD_LinearResampleReader::seek (int position) [virtual]
Seeks to a specific position in the source.
Parameters:
position The position to seek for measured in samples. To get from a given time to the samples you simply have to multiply the time value in seconds with the sample rate of the reader.
Warning:
This may work or not, depending on the actual reader.
Reimplemented from AUD_EffectReader.
Definition at line 48 of file AUD_LinearResampleReader.cpp.
References AUD_ResampleReader::m_rate, and AUD_EffectReader::m_reader.
The documentation for this class was generated from the following files:
AUD_LinearResampleReader.h
AUD_LinearResampleReader.cpp