Blender: IMB_imbuf.h File Reference
IMB_imbuf.h File Reference
IMage Buffer
Defines
#define FILTER_MASK_NULL 0
#define FILTER_MASK_MARGIN 1
#define FILTER_MASK_USED 2
Typedefs
typedef enum IMB_BlendMode IMB_BlendMode
typedef enum IMB_Timecode_Type IMB_Timecode_Type
typedef enum IMB_Proxy_Size IMB_Proxy_Size
Enumerations
enum IMB_BlendMode {
IMB_BLEND_MIX = 0, IMB_BLEND_ADD = 1, IMB_BLEND_SUB = 2, IMB_BLEND_MUL = 3,
IMB_BLEND_LIGHTEN = 4, IMB_BLEND_DARKEN = 5, IMB_BLEND_ERASE_ALPHA = 6, IMB_BLEND_ADD_ALPHA = 7,
IMB_BLEND_COPY = 1000, IMB_BLEND_COPY_RGB = 1001, IMB_BLEND_COPY_ALPHA = 1002
}
enum IMB_Timecode_Type {
IMB_TC_NONE = 0, IMB_TC_RECORD_RUN = 1, IMB_TC_FREE_RUN = 2, IMB_TC_INTERPOLATED_REC_DATE_FREE_RUN = 4,
IMB_TC_RECORD_RUN_NO_GAPS = 8, IMB_TC_MAX_SLOT = 4
}
enum IMB_Proxy_Size {
IMB_PROXY_NONE = 0, IMB_PROXY_25 = 1, IMB_PROXY_50 = 2, IMB_PROXY_75 = 4,
IMB_PROXY_100 = 8, IMB_PROXY_MAX_SLOT = 4
}
Functions
void IMB_init (void)
void IMB_exit (void)
struct ImBuf * IMB_ibImageFromMemory (unsigned char *mem, size_t size, int flags, const char *descr)
struct ImBuf * IMB_testiffname (const char *filepath, int flags)
struct ImBuf * IMB_loadiffname (const char *filepath, int flags)
void IMB_freeImBuf (struct ImBuf *ibuf)
struct ImBuf * IMB_allocImBuf (unsigned int x, unsigned int y, unsigned char d, unsigned int flags)
void IMB_refImBuf (struct ImBuf *ibuf)
struct ImBuf * IMB_makeSingleUser (struct ImBuf *ibuf)
struct ImBuf * IMB_dupImBuf (struct ImBuf *ibuf1)
short addzbufImBuf (struct ImBuf *ibuf)
short addzbuffloatImBuf (struct ImBuf *ibuf)
unsigned int IMB_blend_color (unsigned int src1, unsigned int src2, int fac, IMB_BlendMode mode)
void IMB_blend_color_float (float *dst, float *src1, float *src2, float fac, IMB_BlendMode mode)
void IMB_rectclip (struct ImBuf *dbuf, struct ImBuf *sbuf, int *destx, int *desty, int *srcx, int *srcy, int *width, int *height)
void IMB_rectcpy (struct ImBuf *drect, struct ImBuf *srect, int destx, int desty, int srcx, int srcy, int width, int height)
void IMB_rectblend (struct ImBuf *dbuf, struct ImBuf *sbuf, int destx, int desty, int srcx, int srcy, int width, int height, IMB_BlendMode mode)
void IMB_anim_set_index_dir (struct anim *anim, const char *dir)
int IMB_anim_index_get_frame_index (struct anim *anim, IMB_Timecode_Type tc, int position)
struct IndexBuildContext * IMB_anim_index_rebuild_context (struct anim *anim, IMB_Timecode_Type tcs_in_use, IMB_Proxy_Size proxy_sizes_in_use, int quality)
void IMB_anim_index_rebuild (struct IndexBuildContext *context, short *stop, short *do_update, float *progress)
void IMB_anim_index_rebuild_finish (struct IndexBuildContext *context, short stop)
int IMB_anim_get_duration (struct anim *anim, IMB_Timecode_Type tc)
int IMB_anim_get_fps (struct anim *anim, short *frs_sec, float *frs_sec_base)
struct anim * IMB_open_anim (const char *name, int ib_flags, int streamindex)
void IMB_close_anim (struct anim *anim)
void IMB_close_anim_proxies (struct anim *anim)
int ismovie (const char *filepath)
void IMB_anim_set_preseek (struct anim *anim, int preseek)
int IMB_anim_get_preseek (struct anim *anim)
struct ImBuf * IMB_anim_absolute (struct anim *anim, int position, IMB_Timecode_Type tc, IMB_Proxy_Size preview_size)
struct ImBuf * IMB_anim_previewframe (struct anim *anim)
void IMB_free_anim (struct anim *anim)
void IMB_filter (struct ImBuf *ibuf)
void IMB_filterN (struct ImBuf *out, struct ImBuf *in)
void IMB_mask_filter_extend (char *mask, int width, int height)
void IMB_mask_clear (struct ImBuf *ibuf, char *mask, int val)
void IMB_filter_extend (struct ImBuf *ibuf, char *mask, int filter)
void IMB_makemipmap (struct ImBuf *ibuf, int use_filter)
void IMB_remakemipmap (struct ImBuf *ibuf, int use_filter)
struct ImBuf * IMB_getmipmap (struct ImBuf *ibuf, int level)
void IMB_tile_cache_params (int totthread, int maxmem)
unsigned int * IMB_gettile (struct ImBuf *ibuf, int tx, int ty, int thread)
void IMB_tiles_to_rect (struct ImBuf *ibuf)
void IMB_filtery (struct ImBuf *ibuf)
struct ImBuf * IMB_onehalf (struct ImBuf *ibuf1)
struct ImBuf * IMB_scaleImBuf (struct ImBuf *ibuf, unsigned int newx, unsigned int newy)
struct ImBuf * IMB_scalefastImBuf (struct ImBuf *ibuf, unsigned int newx, unsigned int newy)
short IMB_saveiff (struct ImBuf *ibuf, const char *filepath, int flags)
int IMB_ispic (const char *name)
int IMB_isanim (const char *name)
int imb_get_anim_type (const char *name)
void IMB_de_interlace (struct ImBuf *ibuf)
void IMB_interlace (struct ImBuf *ibuf)
void IMB_rect_from_float (struct ImBuf *ibuf)
void IMB_partial_rect_from_float (struct ImBuf *ibuf, float *buffer, int x, int y, int w, int h)
void IMB_float_from_rect (struct ImBuf *ibuf)
void IMB_float_from_rect_simple (struct ImBuf *ibuf)
void IMB_convert_profile (struct ImBuf *ibuf, int profile)
float * IMB_float_profile_ensure (struct ImBuf *ibuf, int profile, int *alloc)
void IMB_color_to_bw (struct ImBuf *ibuf)
void IMB_saturation (struct ImBuf *ibuf, float sat)
void IMB_buffer_byte_from_float (unsigned char *rect_to, const float *rect_from, int channels_from, float dither, int profile_to, int profile_from, int predivide, int width, int height, int stride_to, int stride_from)
void IMB_buffer_float_from_byte (float *rect_to, const unsigned char *rect_from, int profile_to, int profile_from, int predivide, int width, int height, int stride_to, int stride_from)
void IMB_buffer_float_from_float (float *rect_to, const float *rect_from, int channels_from, int profile_to, int profile_from, int predivide, int width, int height, int stride_to, int stride_from)
void IMB_buffer_byte_from_byte (unsigned char *rect_to, const unsigned char *rect_from, int profile_to, int profile_from, int predivide, int width, int height, int stride_to, int stride_from)
void IMB_buffer_float_clamp (float *buf, int width, int height)
void IMB_convert_rgba_to_abgr (struct ImBuf *ibuf)
void bicubic_interpolation (struct ImBuf *in, struct ImBuf *out, float u, float v, int xout, int yout)
void neareast_interpolation (struct ImBuf *in, struct ImBuf *out, float u, float v, int xout, int yout)
void bilinear_interpolation (struct ImBuf *in, struct ImBuf *out, float u, float v, int xout, int yout)
void bicubic_interpolation_color (struct ImBuf *in, unsigned char *col, float *col_float, float u, float v)
void neareast_interpolation_color (struct ImBuf *in, unsigned char *col, float *col_float, float u, float v)
void bilinear_interpolation_color (struct ImBuf *in, unsigned char *col, float *col_float, float u, float v)
void bilinear_interpolation_color_wrap (struct ImBuf *in, unsigned char *col, float *col_float, float u, float v)
struct ImBuf * IMB_loadifffile (int file, int flags, const char *descr)
struct ImBuf * IMB_half_x (struct ImBuf *ibuf1)
struct ImBuf * IMB_double_fast_x (struct ImBuf *ibuf1)
struct ImBuf * IMB_double_x (struct ImBuf *ibuf1)
struct ImBuf * IMB_half_y (struct ImBuf *ibuf1)
struct ImBuf * IMB_double_fast_y (struct ImBuf *ibuf1)
struct ImBuf * IMB_double_y (struct ImBuf *ibuf1)
void IMB_flipx (struct ImBuf *ibuf)
void IMB_flipy (struct ImBuf *ibuf)
void IMB_premultiply_alpha (struct ImBuf *ibuf)
void IMB_freezbufImBuf (struct ImBuf *ibuf)
void IMB_freezbuffloatImBuf (struct ImBuf *ibuf)
void IMB_rectfill (struct ImBuf *drect, const float col[4])
void IMB_rectfill_area (struct ImBuf *ibuf, float *col, int x1, int y1, int x2, int y2)
void IMB_rectfill_alpha (struct ImBuf *ibuf, const float value)
void buf_rectfill_area (unsigned char *rect, float *rectf, int width, int height, const float col[4], int x1, int y1, int x2, int y2)
int IMB_metadata_change_field (struct ImBuf *img, const char *key, const char *field)
short imb_addrectImBuf (struct ImBuf *ibuf)
void imb_freerectImBuf (struct ImBuf *ibuf)
short imb_addrectfloatImBuf (struct ImBuf *ibuf)
void imb_freerectfloatImBuf (struct ImBuf *ibuf)
void imb_freemipmapImBuf (struct ImBuf *ibuf)
short imb_addtilesImBuf (struct ImBuf *ibuf)
void imb_freetilesImBuf (struct ImBuf *ibuf)
Detailed Description
Definition in file IMB_imbuf.h.
Define Documentation
#define FILTER_MASK_MARGIN 1
Definition at line 291 of file IMB_imbuf.h.
Referenced by IMB_filter_extend(), and IMB_mask_filter_extend().
#define FILTER_MASK_NULL 0
Attention:
Defined in filter.c
Definition at line 290 of file IMB_imbuf.h.
#define FILTER_MASK_USED 2
Definition at line 292 of file IMB_imbuf.h.
Referenced by apply_heights_data(), bake_displacement(), bake_shade(), and set_rast_triangle().
Typedef Documentation
typedef enum IMB_BlendMode IMB_BlendMode
Attention:
Defined in rectop.c
typedef enum IMB_Proxy_Size IMB_Proxy_Size
typedef enum IMB_Timecode_Type IMB_Timecode_Type
Attention:
Defined in indexer.c
Enumeration Type Documentation
enum IMB_BlendMode
Attention:
Defined in rectop.c
Enumerator:
IMB_BLEND_MIX
IMB_BLEND_ADD
IMB_BLEND_SUB
IMB_BLEND_MUL
IMB_BLEND_LIGHTEN
IMB_BLEND_DARKEN
IMB_BLEND_ERASE_ALPHA
IMB_BLEND_ADD_ALPHA
IMB_BLEND_COPY
IMB_BLEND_COPY_RGB
IMB_BLEND_COPY_ALPHA
Definition at line 154 of file IMB_imbuf.h.
enum IMB_Proxy_Size
Enumerator:
IMB_PROXY_NONE
IMB_PROXY_25
IMB_PROXY_50
IMB_PROXY_75
IMB_PROXY_100
IMB_PROXY_MAX_SLOT
Definition at line 203 of file IMB_imbuf.h.
enum IMB_Timecode_Type
Attention:
Defined in indexer.c
Enumerator:
IMB_TC_NONE
IMB_TC_RECORD_RUN
IMB_TC_FREE_RUN
IMB_TC_INTERPOLATED_REC_DATE_FREE_RUN
IMB_TC_RECORD_RUN_NO_GAPS
IMB_TC_MAX_SLOT
Definition at line 186 of file IMB_imbuf.h.
Function Documentation
short addzbuffloatImBuf (struct ImBuf * ibuf)
Definition at line 206 of file allocimbuf.c.
References FALSE, ImBuf::flags, IB_zbuffloat, IMB_freezbuffloatImBuf(), ImBuf::mall, MEM_mapallocN(), NULL, size(), TRUE, ImBuf::x, ImBuf::y, and ImBuf::zbuf_float.
Referenced by IMB_allocImBuf(), imb_load_openexr(), and seq_render_scene_strip().
short addzbufImBuf (struct ImBuf * ibuf)
Attention:
Defined in allocimbuf.c
Definition at line 188 of file allocimbuf.c.
References FALSE, ImBuf::flags, IB_zbuf, IMB_freezbufImBuf(), ImBuf::mall, MEM_mapallocN(), NULL, size(), TRUE, ImBuf::x, ImBuf::y, and ImBuf::zbuf.
Referenced by imb_addrectImBuf(), and IMB_allocImBuf().
void bicubic_interpolation (struct ImBuf * in, struct ImBuf * out, float u, float v, int xout, int yout)
Attention:
defined in imageprocess.c
Definition at line 231 of file imageprocess.c.
References bicubic_interpolation_color(), NULL, pixel_from_buffer(), ImBuf::rect, and ImBuf::rect_float.
Referenced by BKE_tracking_stabilize(), node_composit_exec_rotate(), node_composit_transform(), scale_trackpreview_ibuf(), and transform_image().
void bicubic_interpolation_color (struct ImBuf * in, unsigned char * col, float * col_float, float u, float v)
Definition at line 132 of file imageprocess.c.
References CLAMP(), i, P(), ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by bicubic_interpolation(), and do_projectpaint_thread().
void bilinear_interpolation (struct ImBuf * in, struct ImBuf * out, float u, float v, int xout, int yout)
Definition at line 383 of file imageprocess.c.
References bilinear_interpolation_color(), NULL, pixel_from_buffer(), ImBuf::rect, and ImBuf::rect_float.
Referenced by BKE_tracking_stabilize(), node_composit_exec_rotate(), node_composit_transform(), and transform_image().
void bilinear_interpolation_color (struct ImBuf * in, unsigned char * col, float * col_float, float u, float v)
Definition at line 246 of file imageprocess.c.
References floorf, if(), ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by bilinear_interpolation().
void bilinear_interpolation_color_wrap (struct ImBuf * in, unsigned char * col, float * col_float, float u, float v)
Definition at line 322 of file imageprocess.c.
References floorf, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by project_face_pixel(), and project_paint_PickColor().
void buf_rectfill_area (unsigned char * rect, float * rectf, int width, int height, const float col[4], int x1, int y1, int x2, int y2)
Definition at line 484 of file rectop.c.
References CLAMP(), fb(), FTOCHAR, i, and SWAP.
short imb_addrectfloatImBuf (struct ImBuf * ibuf)
Definition at line 284 of file allocimbuf.c.
References ImBuf::channels, FALSE, ImBuf::flags, IB_rectfloat, imb_freerectfloatImBuf(), ImBuf::mall, MEM_mapallocN(), NULL, ImBuf::rect_float, size(), TRUE, ImBuf::x, and ImBuf::y.
Referenced by color_balance_byte_float(), IMB_allocImBuf(), IMB_float_from_rect(), IMB_float_from_rect_simple(), imb_load_openexr(), node_composit_exec_splitviewer(), and node_composit_exec_viewer().
short imb_addrectImBuf (struct ImBuf * ibuf)
Definition at line 307 of file allocimbuf.c.
References addzbufImBuf(), FALSE, ImBuf::flags, IB_rect, ImBuf::mall, MEM_freeN(), MEM_mapallocN(), NULL, ImBuf::planes, ImBuf::rect, size(), TRUE, ImBuf::x, and ImBuf::y.
Referenced by curvemapping_do_ibuf(), do_plugin_effect(), image_buffer_rect_update(), IMB_allocImBuf(), imb_cocoaLoadImage(), imb_load_dds(), imb_loadpng(), imb_onehalf_no_alloc(), IMB_partial_rect_from_float(), and IMB_rect_from_float().
short imb_addtilesImBuf (struct ImBuf * ibuf)
Definition at line 331 of file allocimbuf.c.
References FALSE, IB_tiles, ImBuf::mall, MEM_callocN(), NULL, ImBuf::tiles, ImBuf::xtiles, and ImBuf::ytiles.
Referenced by imb_loadtiff().
struct ImBuf* IMB_allocImBuf (unsigned int x, unsigned int y, unsigned char d, unsigned int flags) [read]
Attention:
Defined in allocimbuf.c
Definition at line 342 of file allocimbuf.c.
References addzbuffloatImBuf(), addzbufImBuf(), ImBuf::channels, FALSE, ImBuf::ftype, IB_rect, IB_rectfloat, IB_zbuf, IB_zbuffloat, imb_addrectfloatImBuf(), imb_addrectImBuf(), IMB_freeImBuf(), MEM_callocN(), NULL, ImBuf::planes, ImBuf::ppm, TGA, ImBuf::x, and ImBuf::y.
Referenced by add_ibuf_size(), allocImBuf(), anim_getnew(), avi_fetchibuf(), BKE_image_acquire_ibuf(), BL_MakeScreenShot(), brush_imbuf_new(), brush_painter_fixed_tex_partial_update(), de_interlace_ng(), de_interlace_st(), do_displace(), do_mapuv(), do_paintface_box_select(), do_paintvert_box_select(), dynamicPaint_outputSurfaceImage(), ED_view3d_draw_offscreen_imbuf(), envmap_split_ima(), exec(), exec_output_file_singlelayer(), filelist_from_library(), filelist_init_icons(), get_area_imbuf(), GHOST_SystemCocoa::handleDraggingEvent(), ibJpegImageFromCinfo(), icon_draw_rect(), image_get_ibuf_multilayer(), image_get_render_result(), image_load_sequence_multilayer(), image_undo_push_tile(), image_undo_restore(), imapaint_lift_clone(), imb_bmp_decode(), imb_cocoaLoadImage(), IMB_de_interlace(), IMB_double_fast_x(), IMB_double_fast_y(), IMB_dupImBuf(), IMB_half_x(), IMB_half_y(), IMB_interlace(), imb_jp2_decode(), imb_load_dds(), imb_load_dpx_cineon(), imb_load_openexr(), imb_loadhdr(), imb_loadiris(), imb_loadpng(), imb_loadtarga(), imb_loadtiff(), IMB_makemipmap(), IMB_onehalf(), imb_read_tiff_pixels(), IMB_remakemipmap(), IMB_thumb_create(), input_preprocess(), loadblend_thumb(), make_histogram_view_from_ibuf_byte(), make_histogram_view_from_ibuf_float(), make_sep_waveform_view_from_ibuf_byte(), make_sep_waveform_view_from_ibuf_float(), make_vectorscope_view_from_ibuf_byte(), make_vectorscope_view_from_ibuf_float(), make_waveform_view_from_ibuf_byte(), make_waveform_view_from_ibuf_float(), make_zebra_view_from_ibuf(), my_envmap_split_ima(), node_composit_exec_rotate(), node_composit_exec_scale(), node_composit_transform(), ImageBuff::plot(), prepare_effect_imbufs(), RE_layer_load_from_file(), RE_WriteEnvmapResult(), render_envmap(), render_result_rect_to_ibuf(), save_jstjpeg(), scale_trackpreview_ibuf(), screen_opengl_render_anim_step(), screenshot_exec(), screenshot_startjob(), seq_render_effect_strip_impl(), seq_render_scene_strip(), seq_render_strip(), seq_render_strip_stack(), stabilize_alloc_ibuf(), and view3d_read_backbuf().
struct ImBuf* IMB_anim_absolute (struct anim * anim, int position, IMB_Timecode_Type tc, IMB_Proxy_Size preview_size) [read]
Attention:
Defined in anim_movie.c
Definition at line 1237 of file anim_movie.c.
References an_stringdec(), an_stringenc(), ANIM_AVI, ANIM_FFMPEG, anim_getnew(), ANIM_MOVIE, ANIM_QTIME, ANIM_REDCODE, ANIM_SEQUENCE, avi_fetchibuf(), BLI_snprintf(), anim::curposition, anim::curtype, anim::duration, anim::first, IB_animdeinterlace, anim::ib_flags, IB_PROFILE_SRGB, IB_rect, IMB_anim_absolute(), IMB_anim_index_get_frame_index(), IMB_anim_open_proxy(), IMB_convert_rgba_to_abgr(), IMB_filtery(), IMB_freeImBuf(), IMB_loadiffname(), IMB_PROXY_NONE, IMB_TC_NONE, movie_fetchibuf(), ImBuf::name, anim::name, NULL, ImBuf::profile, and qtime_fetchibuf().
Referenced by image_load_movie_file(), IMB_anim_absolute(), IMB_anim_previewframe(), IMB_thumb_create(), index_rebuild_fallback(), movieclip_load_movie_file(), openanim(), seq_proxy_fetch(), and seq_render_strip().
int IMB_anim_get_duration (struct anim * anim, IMB_Timecode_Type tc)
Return the length (in frames) of the given anim.
Definition at line 1330 of file anim_movie.c.
References anim::duration, IMB_anim_open_index(), IMB_indexer_get_duration(), and IMB_TC_NONE.
Referenced by image_info(), image_load_movie_file(), index_rebuild_fallback(), movieclip_calc_length(), movieclip_load_movie_file(), proxy_startjob(), reload_sequence_new_file(), sequencer_add_movie_strip(), and set_frames_cb().
int IMB_anim_get_fps (struct anim * anim, short * frs_sec, float * frs_sec_base)
Return the fps contained in movie files (function rval is FALSE, and frs_sec and frs_sec_base untouched if none available!)
Definition at line 1345 of file anim_movie.c.
References FALSE, anim::frs_sec, anim::frs_sec_base, and TRUE.
Referenced by alloc_proxy_output_avi().
int IMB_anim_get_preseek (struct anim * anim)
Definition at line 1361 of file anim_movie.c.
References anim::preseek.
Referenced by reload_sequence_new_file(), and sequencer_add_movie_strip().
int IMB_anim_index_get_frame_index (struct anim * anim, IMB_Timecode_Type tc, int position)
Definition at line 1253 of file indexer.c.
Referenced by IMB_anim_absolute(), and seq_proxy_fetch().
void IMB_anim_index_rebuild (struct IndexBuildContext * context, short * stop, short * do_update, float * progress)
Definition at line 1144 of file indexer.c.
References ANIM_FFMPEG, IndexBuildContext::anim_type, and index_rebuild_fallback().
Referenced by proxy_startjob(), and seq_proxy_rebuild().
struct IndexBuildContext* IMB_anim_index_rebuild_context (struct anim * anim, IMB_Timecode_Type tcs_in_use, IMB_Proxy_Size proxy_sizes_in_use, int quality) [read]
Definition at line 1122 of file indexer.c.
References ANIM_FFMPEG, IndexBuildContext::anim_type, anim::curtype, index_fallback_create_context(), and NULL.
Referenced by clip_rebuild_proxy_exec(), and seq_proxy_rebuild_context().
void IMB_anim_index_rebuild_finish (struct IndexBuildContext * context, short stop)
Definition at line 1159 of file indexer.c.
References ANIM_FFMPEG, IndexBuildContext::anim_type, and index_rebuild_fallback_finish().
Referenced by proxy_endjob(), and seq_proxy_rebuild_finish().
struct ImBuf* IMB_anim_previewframe (struct anim * anim) [read]
Attention:
Defined in anim_movie.c fetches a define previewframe, usually half way into the movie
Definition at line 1222 of file anim_movie.c.
References anim::duration, IMB_anim_absolute(), IMB_freeImBuf(), IMB_PROXY_NONE, IMB_TC_NONE, and NULL.
Referenced by IMB_thumb_create().
void IMB_anim_set_index_dir (struct anim * anim, const char * dir)
Definition at line 1197 of file indexer.c.
References BLI_strncpy(), IMB_free_indices(), and anim::index_dir.
Referenced by movieclip_open_anim_file(), and seq_open_anim_file().
void IMB_anim_set_preseek (struct anim * anim, int preseek)
Definition at line 1356 of file anim_movie.c.
References anim::preseek.
Referenced by seq_render_strip().
unsigned int IMB_blend_color (unsigned int src1, unsigned int src2, int fac, IMB_BlendMode mode)
Definition at line 119 of file rectop.c.
References blend_color_add(), blend_color_darken(), blend_color_lighten(), blend_color_mix(), blend_color_mul(), blend_color_sub(), IMB_BLEND_ADD, IMB_BLEND_DARKEN, IMB_BLEND_ERASE_ALPHA, IMB_BLEND_LIGHTEN, IMB_BLEND_MIX, IMB_BLEND_MUL, and IMB_BLEND_SUB.
Referenced by do_projectpaint_clone(), do_projectpaint_draw(), and IMB_rectblend().
void IMB_blend_color_float (float * dst, float * src1, float * src2, float fac, IMB_BlendMode mode)
Definition at line 228 of file rectop.c.
References blend_color_add_float(), blend_color_darken_float(), blend_color_lighten_float(), blend_color_mix_float(), blend_color_mul_float(), blend_color_sub_float(), IMB_BLEND_ADD, IMB_BLEND_DARKEN, IMB_BLEND_ERASE_ALPHA, IMB_BLEND_LIGHTEN, IMB_BLEND_MIX, IMB_BLEND_MUL, and IMB_BLEND_SUB.
Referenced by do_projectpaint_clone_f(), do_projectpaint_draw_f(), and IMB_rectblend().
void IMB_buffer_byte_from_byte (unsigned char * rect_to, const unsigned char * rect_from, int profile_to, int profile_from, int predivide, int width, int height, int stride_to, int stride_from)
Definition at line 468 of file divers.c.
References BLI_assert, IB_PROFILE_LINEAR_RGB, IB_PROFILE_NONE, IB_PROFILE_SRGB, linearrgb_to_srgb_predivide_v4(), linearrgb_to_srgb_v4(), rgba_float_to_uchar(), rgba_uchar_to_float(), srgb_to_linearrgb_predivide_v4(), and srgb_to_linearrgb_v4().
Referenced by IMB_convert_profile().
void IMB_buffer_byte_from_float (unsigned char * rect_to, const float * rect_from, int channels_from, float dither, int profile_to, int profile_from, int predivide, int width, int height, int stride_to, int stride_from)
Definition at line 190 of file divers.c.
References BLI_assert, BLI_init_srgb_conversion(), clear_dither_context(), create_dither_context(), dither_finish_row(), float_to_byte_dither_v4(), FTOCHAR, IB_PROFILE_LINEAR_RGB, IB_PROFILE_NONE, IB_PROFILE_SRGB, linearrgb_to_srgb_ushort4(), linearrgb_to_srgb_ushort4_predivide(), linearrgb_to_srgb_v3_v3(), rgb_float_to_uchar(), rgba_float_to_uchar(), srgb_to_linearrgb_predivide_v4(), srgb_to_linearrgb_v3_v3(), srgb_to_linearrgb_v4(), ushort_to_byte_dither_v4(), and ushort_to_byte_v4().
Referenced by ed_preview_draw_rect(), generate_preview(), image_buffer_rect_update(), IMB_partial_rect_from_float(), IMB_rect_from_float(), and render_result_rect_get_pixels().
void IMB_buffer_float_clamp (float * buf, int width, int height)
Definition at line 746 of file divers.c.
References i, and MIN2.
Referenced by GPU_verify_image().
void IMB_buffer_float_from_byte (float * rect_to, const unsigned char * rect_from, int profile_to, int profile_from, int predivide, int width, int height, int stride_to, int stride_from)
Definition at line 327 of file divers.c.
References BLI_assert, BLI_init_srgb_conversion(), IB_PROFILE_LINEAR_RGB, IB_PROFILE_NONE, IB_PROFILE_SRGB, linearrgb_to_srgb_predivide_v4(), linearrgb_to_srgb_v4(), rgba_uchar_to_float(), srgb_to_linearrgb_uchar4(), and srgb_to_linearrgb_uchar4_predivide().
Referenced by IMB_float_from_rect(), IMB_float_from_rect_simple(), and IMB_float_profile_ensure().
void IMB_buffer_float_from_float (float * rect_to, const float * rect_from, int channels_from, int profile_to, int profile_from, int predivide, int width, int height, int stride_to, int stride_from)
Definition at line 382 of file divers.c.
References BLI_assert, copy_v3_v3(), IB_PROFILE_LINEAR_RGB, IB_PROFILE_NONE, IB_PROFILE_SRGB, linearrgb_to_srgb_predivide_v4(), linearrgb_to_srgb_v3_v3(), linearrgb_to_srgb_v4(), srgb_to_linearrgb_predivide_v4(), srgb_to_linearrgb_v3_v3(), and srgb_to_linearrgb_v4().
Referenced by GPU_verify_image(), IMB_convert_profile(), IMB_float_profile_ensure(), IMB_partial_rect_from_float(), node_composit_get_float_buffer(), render_result_rect_from_ibuf(), and screen_opengl_render_apply().
void IMB_close_anim (struct anim * anim)
Definition at line 243 of file anim_movie.c.
References IMB_free_anim(), and NULL.
Referenced by IMB_free_indices().
void IMB_close_anim_proxies (struct anim * anim)
Definition at line 250 of file anim_movie.c.
References IMB_free_indices(), and NULL.
Referenced by proxy_endjob(), and seq_proxy_rebuild_finish().
void IMB_color_to_bw (struct ImBuf * ibuf)
Definition at line 729 of file divers.c.
References i, if(), ImBuf::rect, ImBuf::rect_float, rgb_to_grayscale(), rgb_to_grayscale_byte(), ImBuf::x, and ImBuf::y.
Referenced by render_result_rect_to_ibuf(), screen_opengl_render_anim_step(), screen_opengl_render_apply(), and screenshot_exec().
void IMB_convert_profile (struct ImBuf * ibuf, int profile)
Definition at line 635 of file divers.c.
References BLI_assert, ELEM, ImBuf::flags, IB_cm_predivide, IB_PROFILE_LINEAR_RGB, IB_PROFILE_NONE, IB_PROFILE_SRGB, IMB_buffer_byte_from_byte(), IMB_buffer_float_from_float(), ImBuf::profile, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by seq_render_scene_strip(), and seq_render_strip().
void IMB_convert_rgba_to_abgr (struct ImBuf * ibuf)
Change the ordering of the color bytes pointed to by rect from rgba to abgr. size * 4 color bytes are reordered.
Attention:
Defined in imageprocess.c
Definition at line 56 of file imageprocess.c.
References if(), ImBuf::rect, ImBuf::rect_float, size(), ImBuf::x, and ImBuf::y.
Referenced by do_paintface_box_select(), do_paintvert_box_select(), do_plugin_effect(), IMB_anim_absolute(), imb_cocoaLoadImage(), imb_loadiris(), imb_loadtarga(), imb_read_tiff_pixels(), imb_saveiris(), index_rebuild_fallback(), and view3d_read_backbuf().
void IMB_de_interlace (struct ImBuf * ibuf)
Attention:
Defined in divers.c
Definition at line 49 of file divers.c.
References ImBuf::flags, IB_fields, IB_rect, IMB_allocImBuf(), IMB_freeImBuf(), IMB_rectcpy(), NULL, ImBuf::rect, ImBuf::x, and ImBuf::y.
Referenced by de_interlace(), and IMB_loadiffname().
struct ImBuf* IMB_double_fast_x (struct ImBuf * ibuf1) [read]
Attention:
defined in scaling.c
Definition at line 119 of file scaling.c.
References ImBuf::flags, i, IMB_allocImBuf(), NULL, ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by double_fast_x(), and IMB_double_x().
struct ImBuf* IMB_double_fast_y (struct ImBuf * ibuf1) [read]
Attention:
defined in scaling.c
Definition at line 244 of file scaling.c.
References ImBuf::flags, IMB_allocImBuf(), NULL, ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by double_fast_y(), and IMB_double_y().
struct ImBuf* IMB_double_x (struct ImBuf * ibuf1) [read]
Attention:
defined in scaling.c
Definition at line 158 of file scaling.c.
References IMB_double_fast_x(), imb_filterx(), NULL, ImBuf::rect, and ImBuf::rect_float.
Referenced by double_x().
struct ImBuf* IMB_double_y (struct ImBuf * ibuf1) [read]
Attention:
defined in scaling.c
Definition at line 282 of file scaling.c.
References IMB_double_fast_y(), IMB_filtery(), NULL, and ImBuf::rect.
Referenced by double_y().
struct ImBuf* IMB_dupImBuf (struct ImBuf * ibuf1) [read]
Attention:
Defined in allocimbuf.c
Definition at line 388 of file allocimbuf.c.
References ImBuf::c_handle, ImBuf::channels, ImBuf::encodedbuffer, ImBuf::encodedbuffersize, ImBuf::encodedsize, FALSE, ImBuf::flags, IB_fields, IB_MIPMAP_LEVELS, IB_rect, IB_rectfloat, imb_addencodedbufferImBuf(), IMB_allocImBuf(), IMB_freeImBuf(), ImBuf::mall, ImBuf::metadata, ImBuf::mipmap, NULL, ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::refcounter, ImBuf::x, ImBuf::y, ImBuf::zbuf, and ImBuf::zbuf_float.
Referenced by BKE_tracking_distortion_exec(), copy_brush(), copy_from_ibuf_still(), copy_to_ibuf_still(), curvemapping_do_ibuf(), do_adjustment(), do_multicam(), do_plugin_effect(), dupImBuf(), envmap_split_ima(), icon_copy_rect(), IMB_half_x(), IMB_half_y(), IMB_makeSingleUser(), index_rebuild_fallback(), movieclip_build_proxy_ibuf(), node_composit_get_movieclip(), put_postprocessed_frame_to_cache(), render_result_rect_to_ibuf(), screen_opengl_render_anim_step(), seq_render_effect_strip_impl(), and seq_render_strip().
void IMB_exit (void)
Definition at line 38 of file module.c.
References imb_filetypes_exit(), and imb_tile_cache_exit().
Referenced by free_blender(), and main().
void IMB_filter (struct ImBuf * ibuf)
Definition at line 259 of file filter.c.
References imb_filterx(), and IMB_filtery().
void IMB_filter_extend (struct ImBuf * ibuf, char * mask, int filter)
Definition at line 360 of file filter.c.
References check_pixel_assigned(), filter(), filter_make_index(), FILTER_MASK_MARGIN, i, MEM_dupallocN(), MEM_freeN(), NULL, ImBuf::rect, ImBuf::rect_float, sqrt(), ImBuf::x, and ImBuf::y.
Referenced by RE_bake_ibuf_filter().
void IMB_filterN (struct ImBuf * out, struct ImBuf * in)
Definition at line 211 of file filter.c.
References ImBuf::rect, ImBuf::x, and ImBuf::y.
Referenced by IMB_makemipmap(), and IMB_remakemipmap().
void IMB_filtery (struct ImBuf * ibuf)
Attention:
Defined in filter.c
Definition at line 136 of file filter.c.
References filtcolum(), filtcolumf(), ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by avi_fetchibuf(), IMB_anim_absolute(), IMB_double_y(), IMB_filter(), and input_preprocess().
void IMB_flipx (struct ImBuf * ibuf)
Attention:
Defined in rotate.c
Definition at line 100 of file rotate.c.
References NULL, ImBuf::rect, ImBuf::rect_float, SWAP, ImBuf::x, and ImBuf::y.
Referenced by input_preprocess().
void IMB_flipy (struct ImBuf * ibuf)
Definition at line 47 of file rotate.c.
References MEM_freeN(), MEM_mallocN(), NULL, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by imb_load_dds(), imb_loadhdr(), imb_loadtarga(), index_rebuild_fallback(), and input_preprocess().
void IMB_float_from_rect (struct ImBuf * ibuf)
Definition at line 597 of file divers.c.
References ImBuf::flags, IB_cm_predivide, IB_PROFILE_LINEAR_RGB, IB_PROFILE_NONE, IB_PROFILE_SRGB, imb_addrectfloatImBuf(), IMB_buffer_float_from_byte(), NULL, ImBuf::profile, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by colorfn(), curvemapping_do_ibuf(), envmap_split_ima(), imapaint_canvas_set(), IMB_float_profile_ensure(), load_frame_image_sequence(), node_composit_get_image(), node_composit_get_movieclip(), RE_layer_load_from_file(), render_result_rect_to_ibuf(), and screen_opengl_render_apply().
void IMB_float_from_rect_simple (struct ImBuf * ibuf)
Definition at line 623 of file divers.c.
References ImBuf::flags, IB_cm_predivide, IB_PROFILE_SRGB, imb_addrectfloatImBuf(), IMB_buffer_float_from_byte(), NULL, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by do_plugin_effect(), input_preprocess(), and prepare_effect_imbufs().
float* IMB_float_profile_ensure (struct ImBuf * ibuf, int profile, int * alloc)
Definition at line 681 of file divers.c.
References ImBuf::flags, IB_cm_predivide, IB_PROFILE_LINEAR_RGB, IB_PROFILE_NONE, IB_PROFILE_SRGB, IMB_buffer_float_from_byte(), IMB_buffer_float_from_float(), IMB_float_from_rect(), MEM_mallocN(), NULL, ImBuf::profile, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by imb_save_dpx_cineon().
void IMB_free_anim (struct anim * anim)
Attention:
Defined in anim_movie.c
Definition at line 219 of file anim_movie.c.
References free_anim_avi(), free_anim_movie(), free_anim_quicktime(), IMB_free_indices(), MEM_freeN(), and NULL.
Referenced by free_anim_seq(), free_buffers(), free_proxy_seq(), image_free_buffers(), IMB_close_anim(), IMB_thumb_create(), openanim(), reload_sequence_new_file(), seq_free_sequence(), and seq_free_strip().
void IMB_freeImBuf (struct ImBuf * ibuf)
Attention:
Defined in allocimbuf.c
Definition at line 151 of file allocimbuf.c.
References freeencodedbufferImBuf(), imb_freerectfloatImBuf(), imb_freerectImBuf(), imb_freetilesImBuf(), IMB_freezbuffloatImBuf(), IMB_freezbufImBuf(), IMB_metadata_free(), MEM_freeN(), and ImBuf::refcounter.
Referenced by avi_fetchibuf(), BKE_free_envmapdata(), BKE_image_free_anim_ibufs(), BKE_movieclip_build_proxy_frame(), BKE_movieclip_get_size(), BKE_movieclip_get_stable_ibuf(), BKE_movieclip_has_frame(), BKE_movieclip_update_scopes(), BKE_tracking_free(), BKE_tracking_next(), BL_MakeScreenShot(), brush_painter_fixed_tex_partial_update(), brush_painter_free(), brush_painter_refresh_cache(), brush_painter_require_imbuf(), ImageBuff::clear(), clip_draw_grease_pencil(), clip_draw_main(), clip_free(), clip_main_area_draw(), copy_from_ibuf_still(), copy_to_ibuf_still(), curvemapping_do_ibuf(), de_interlace_ng(), de_interlace_st(), detect_features_exec(), do_adjustment(), do_displace(), do_mapuv(), do_multicam(), do_paintface_box_select(), do_paintvert_box_select(), do_plugin_effect(), do_render_seq(), do_write_image_or_movie(), draw_bgpic(), draw_image_seq(), dynamicPaint_outputSurfaceImage(), ED_space_clip_get_buffer(), ED_space_clip_get_stable_buffer(), ED_view3d_draw_offscreen(), EDBM_backbuf_border_init(), EDBM_backbuf_border_mask_init(), EDBM_backbuf_circle_init(), exec(), exec_output_file_singlelayer(), filelist_free(), filelist_free_icons(), filelist_init_icons(), free_brush(), free_buffers(), freeImBuf(), icon_copy_rect(), icon_draw_rect(), image_free_buffers(), image_load_image_file(), image_load_sequence_file(), image_remove_ibuf(), image_undo_restore(), imapaint_dirty_region(), imapaint_paint_op(), IMB_allocImBuf(), IMB_anim_absolute(), IMB_anim_previewframe(), IMB_de_interlace(), IMB_dupImBuf(), imb_freemipmapImBuf(), IMB_interlace(), imb_load_openexr(), imb_loadpng(), IMB_makemipmap(), IMB_makeSingleUser(), IMB_moviecache_destructor(), imb_read_tiff_pixels(), IMB_remakemipmap(), IMB_thumb_create(), IMB_thumb_manage(), index_rebuild_fallback(), init_iconfile_list(), init_internal_icons(), input_preprocess(), ImageBuff::load(), loadblend_thumb(), moviecache_valfree(), movieclip_build_proxy_ibuf(), movieclip_get_postprocessed_ibuf(), my_free_envmapdata(), node_composit_exec_rotate(), node_composit_exec_scale(), node_composit_get_movieclip(), node_composit_transform(), openanim(), ImageBuff::plot(), project_paint_end(), put_postprocessed_frame_to_cache(), put_stabilized_frame_to_cache(), RE_layer_load_from_file(), RE_WriteEnvmapResult(), render_result_rect_to_ibuf(), sample_backbuf_area(), save_jstjpeg(), screen_opengl_render_anim_step(), screen_opengl_render_apply(), screenshot_exec(), screenshot_startjob(), seq_proxy_build_frame(), seq_render_effect_strip_impl(), seq_render_strip(), seq_render_strip_stack(), stabilize_alloc_ibuf(), thumbnail_joblist_free(), ui_draw_but_TRACKPREVIEW(), ui_free_but(), view3d_read_backbuf(), view3d_sample_backbuf_rect(), WM_write_file(), GHOST_EventDragnDrop::~GHOST_EventDragnDrop(), and ImageBuff::~ImageBuff().
void imb_freemipmapImBuf (struct ImBuf * ibuf)
Definition at line 50 of file allocimbuf.c.
References IMB_freeImBuf(), ImBuf::mipmap, ImBuf::miptot, and NULL.
Referenced by finish_bake_internal(), finish_images(), imb_freerectfloatImBuf(), imb_freerectImBuf(), and IMB_makemipmap().
void imb_freerectfloatImBuf (struct ImBuf * ibuf)
Definition at line 64 of file allocimbuf.c.
References IB_rectfloat, imb_freemipmapImBuf(), ImBuf::mall, MEM_freeN(), NULL, and ImBuf::rect_float.
Referenced by do_plugin_effect(), get_undistorted_ibuf(), image_record_composite_apply(), imapaint_canvas_free(), imb_addrectfloatImBuf(), IMB_freeImBuf(), IMB_scalefastImBuf(), IMB_thumb_create(), node_composit_exec_splitviewer(), node_composit_exec_viewer(), q_scale_linear_interpolation(), save_image_doit(), scaledownx(), scaledowny(), scaleupx(), and scaleupy().
void imb_freerectImBuf (struct ImBuf * ibuf)
Definition at line 80 of file allocimbuf.c.
References IB_rect, imb_freemipmapImBuf(), ImBuf::mall, MEM_freeN(), NULL, and ImBuf::rect.
Referenced by get_next_bake_face(), image_get_render_result(), IMB_freeImBuf(), IMB_scalefastImBuf(), input_preprocess(), node_composit_exec_splitviewer(), node_composit_exec_viewer(), q_scale_linear_interpolation(), save_image_doit(), scaledownx(), scaledowny(), scaleupx(), scaleupy(), and seq_render_strip().
void imb_freetilesImBuf (struct ImBuf * ibuf)
Definition at line 93 of file allocimbuf.c.
References IB_tiles, imb_tile_cache_tile_free(), ImBuf::mall, MEM_freeN(), NULL, ImBuf::tiles, ImBuf::xtiles, and ImBuf::ytiles.
Referenced by IMB_freeImBuf().
void IMB_freezbuffloatImBuf (struct ImBuf * ibuf)
Definition at line 140 of file allocimbuf.c.
References IB_zbuffloat, ImBuf::mall, MEM_freeN(), NULL, and ImBuf::zbuf_float.
Referenced by addzbuffloatImBuf(), IMB_freeImBuf(), node_composit_exec_splitviewer(), node_composit_exec_viewer(), and save_image_doit().
void IMB_freezbufImBuf (struct ImBuf * ibuf)
Attention:
Defined in allocimbuf.c
Definition at line 129 of file allocimbuf.c.
References IB_zbuf, ImBuf::mall, MEM_freeN(), NULL, and ImBuf::zbuf.
Referenced by addzbufImBuf(), IMB_freeImBuf(), save_image_doit(), and scalefast_Z_ImBuf().
int imb_get_anim_type (const char * name)
Attention:
Defined in util.c
Definition at line 327 of file source/blender/imbuf/intern/util.c.
References ANIM_AVI, ANIM_FFMPEG, ANIM_MOVIE, ANIM_NONE, ANIM_QTIME, ANIM_REDCODE, ANIM_SEQUENCE, IMB_ispic(), isavi(), ismovie(), and UTIL_DEBUG.
Referenced by anim_getnew(), and IMB_isanim().
struct ImBuf* IMB_getmipmap (struct ImBuf * ibuf, int level) [read]
Definition at line 531 of file filter.c.
References CLAMP(), ImBuf::mipmap, and ImBuf::miptot.
Referenced by IMB_tiles_to_rect().
unsigned int* IMB_gettile (struct ImBuf * ibuf, int tx, int ty, int thread)
Definition at line 403 of file cache.c.
References imb_thread_cache_get_tile(), and ImGlobalTileCache::thread_cache.
struct ImBuf* IMB_half_x (struct ImBuf * ibuf1) [read]
Attention:
defined in scaling.c
Definition at line 53 of file scaling.c.
References ImBuf::flags, g, IMB_allocImBuf(), IMB_dupImBuf(), NULL, ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by half_x(), and IMB_onehalf().
struct ImBuf* IMB_half_y (struct ImBuf * ibuf1) [read]
Attention:
defined in scaling.c
Definition at line 172 of file scaling.c.
References ImBuf::flags, g, IMB_allocImBuf(), IMB_dupImBuf(), NULL, ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by half_y(), and IMB_onehalf().
struct ImBuf* IMB_ibImageFromMemory (unsigned char * mem, size_t size, int flags, const char * descr) [read]
Attention:
Defined in readimage.c
Definition at line 53 of file readimage.c.
References ImBuf::flags, IB_premul, IMB_FILE_TYPES, IMB_premultiply_alpha(), ImFileType::is_a, ImFileType::load, and NULL.
Referenced by avi_fetchibuf(), filelist_init_icons(), image_load_image_file(), IMB_loadifffile(), init_internal_icons(), and wm_block_create_splash().
void IMB_init (void)
Attention:
Defined in allocimbuf.c
Definition at line 32 of file module.c.
References imb_filetypes_init(), and imb_tile_cache_init().
Referenced by main().
void IMB_interlace (struct ImBuf * ibuf)
Definition at line 76 of file divers.c.
References ImBuf::flags, IB_fields, IB_rect, IMB_allocImBuf(), IMB_freeImBuf(), IMB_rectcpy(), NULL, ImBuf::rect, ImBuf::x, and ImBuf::y.
Referenced by interlace().
int IMB_isanim (const char * name)
Attention:
Defined in util.c
Definition at line 372 of file source/blender/imbuf/intern/util.c.
References ANIM_SEQUENCE, BLI_testextensie(), FALSE, G, imb_get_anim_type(), and USER_FILTERFILEEXTS.
int IMB_ispic (const char * name)
Attention:
Defined in util.c
Definition at line 183 of file source/blender/imbuf/intern/util.c.
References BLI_testextensie_array(), FALSE, G, imb_ext_image, imb_ext_image_qt, IMB_ispic_name(), and USER_FILTERFILEEXTS.
Referenced by imb_get_anim_type(), and ispic().
struct ImBuf* IMB_loadifffile (int file, int flags, const char * descr) [read]
Attention:
defined in readimage.c
Deprecated:
Only here for backwards compatibility of the
plugin system.
Definition at line 82 of file readimage.c.
References BLI_file_descriptor_size(), IMB_ibImageFromMemory(), MAP_SHARED, mmap(), munmap(), NULL, PROT_READ, and size().
Referenced by IMB_loadiffname(), IMB_testiffname(), and loadifffile().
struct ImBuf* IMB_loadiffname (const char * filepath, int flags) [read]
Attention:
Defined in readimage.c
Definition at line 121 of file readimage.c.
References BLI_open(), BLI_strncpy(), ImBuf::cachename, IB_fields, IB_FILENAME_SIZE, imb_cache_filename(), IMB_de_interlace(), IMB_loadifffile(), ImBuf::mipmap, ImBuf::miptot, ImBuf::name, NULL, and O_BINARY.
Referenced by anim_getnew(), get_brush_icon(), image_load_image_file(), image_load_sequence_file(), IMB_anim_absolute(), IMB_thumb_create(), IMB_thumb_manage(), IMB_thumb_read(), init_iconfile_list(), init_internal_icons(), loadiffname(), movieclip_load_sequence_file(), RE_layer_load_from_file(), seq_proxy_fetch(), and seq_render_strip().
void IMB_makemipmap (struct ImBuf * ibuf, int use_filter)
Definition at line 501 of file filter.c.
References IB_MIPMAP_LEVELS, IB_rect, IMB_allocImBuf(), IMB_filterN(), IMB_freeImBuf(), imb_freemipmapImBuf(), IMB_onehalf(), ImBuf::miplevel, ImBuf::mipmap, ImBuf::miptot, ImBuf::x, and ImBuf::y.
Referenced by draw_bgpic(), and image_mipmap_test().
struct ImBuf* IMB_makeSingleUser (struct ImBuf * ibuf) [read]
Definition at line 175 of file allocimbuf.c.
References IMB_dupImBuf(), IMB_freeImBuf(), and ImBuf::refcounter.
Referenced by image_load_movie_file(), and input_preprocess().
void IMB_mask_clear (struct ImBuf * ibuf, char * mask, int val)
Definition at line 305 of file filter.c.
References ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
void IMB_mask_filter_extend (char * mask, int width, int height)
Definition at line 265 of file filter.c.
References FILTER_MASK_MARGIN, MEM_dupallocN(), and MEM_freeN().
int IMB_metadata_change_field (struct ImBuf * img, const char * key, const char * field)
Definition at line 141 of file metadata.c.
References BLI_strdup(), IMB_metadata_add_field(), ImMetaData::key, MEM_freeN(), ImBuf::metadata, ImMetaData::next, p, and ImMetaData::value.
Referenced by BKE_stamp_info(), and IMB_thumb_create().
struct ImBuf* IMB_onehalf (struct ImBuf * ibuf1) [read]
Attention:
Defined in scaling.c
Definition at line 346 of file scaling.c.
References ImBuf::flags, IMB_allocImBuf(), IMB_half_x(), IMB_half_y(), imb_onehalf_no_alloc(), NULL, ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by IMB_makemipmap(), and onehalf().
struct anim* IMB_open_anim (const char * name, int ib_flags, int streamindex) [read]
Attention:
Defined in anim_movie.c
Definition at line 258 of file anim_movie.c.
References BLI_strncpy(), anim::ib_flags, MEM_callocN(), anim::name, NULL, and anim::streamindex.
Referenced by IMB_anim_open_proxy(), IMB_thumb_create(), and openanim().
void IMB_partial_rect_from_float (struct ImBuf * ibuf, float * buffer, int x, int y, int w, int h)
Definition at line 558 of file divers.c.
References BLI_assert, ImBuf::channels, ImBuf::dither, ELEM, ImBuf::flags, IB_cm_predivide, IB_PROFILE_LINEAR_RGB, IB_PROFILE_NONE, IB_PROFILE_SRGB, IB_RECT_INVALID, imb_addrectImBuf(), IMB_buffer_byte_from_float(), IMB_buffer_float_from_float(), NULL, ImBuf::profile, ImBuf::rect, ImBuf::rect_float, ImBuf::userflags, and ImBuf::x.
Referenced by GPU_paint_update_image().
void IMB_premultiply_alpha (struct ImBuf * ibuf)
Definition at line 589 of file filter.c.
References IMB_premultiply_rect(), IMB_premultiply_rect_float(), NULL, ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by IMB_ibImageFromMemory(), imb_read_tiff_pixels(), and input_preprocess().
void IMB_rect_from_float (struct ImBuf * ibuf)
Definition at line 527 of file divers.c.
References BLI_assert, ImBuf::channels, ImBuf::dither, ELEM, ImBuf::flags, IB_cm_predivide, IB_PROFILE_LINEAR_RGB, IB_PROFILE_NONE, IB_PROFILE_SRGB, IB_RECT_INVALID, imb_addrectImBuf(), IMB_buffer_byte_from_float(), NULL, ImBuf::profile, ImBuf::rect, ImBuf::rect_float, ImBuf::userflags, ImBuf::x, and ImBuf::y.
Referenced by BKE_movieclip_update_scopes(), curvemapping_do_ibuf(), do_plugin_effect(), draw_bgpic(), draw_empty_image(), draw_image_seq(), draw_nodespace_back_pix(), ED_view3d_draw_offscreen(), ED_view3d_draw_offscreen_imbuf(), get_undistorted_ibuf(), GPU_verify_image(), icon_copy_rect(), image_invert_exec(), image_verify_buffer_float(), imapaint_canvas_set(), imb_jp2_decode(), imb_load_dpx_cineon(), imb_loadhdr(), imb_loadiris(), IMB_saveiff(), IMB_thumb_create(), prepare_effect_imbufs(), RE_bake_shade_all_selected(), sample_apply(), and verify_buffer_float().
void IMB_rectblend (struct ImBuf * dbuf, struct ImBuf * sbuf, int destx, int desty, int srcx, int srcy, int width, int height, IMB_BlendMode mode)
Definition at line 324 of file rectop.c.
References ImBuf::channels, IMB_blend_color(), IMB_blend_color_float(), IMB_BLEND_COPY, IMB_BLEND_COPY_ALPHA, IMB_BLEND_COPY_RGB, IMB_rectclip(), NULL, ImBuf::rect, ImBuf::rect_float, and ImBuf::x.
Referenced by imapaint_lift_clone(), imapaint_lift_smear(), imapaint_paint_op(), IMB_rectcpy(), and ImageBuff::plot().
void IMB_rectclip (struct ImBuf * dbuf, struct ImBuf * sbuf, int * destx, int * desty, int * srcx, int * srcy, int * width, int * height)
Definition at line 269 of file rectop.c.
References NULL, ImBuf::x, and ImBuf::y.
Referenced by brush_painter_fixed_tex_partial_update(), imapaint_dirty_region(), imapaint_lift_clone(), imapaint_lift_soften(), imapaint_torus_split_region(), and IMB_rectblend().
void IMB_rectcpy (struct ImBuf * drect, struct ImBuf * srect, int destx, int desty, int srcx, int srcy, int width, int height)
Definition at line 317 of file rectop.c.
References IMB_BLEND_COPY, and IMB_rectblend().
void IMB_rectfill (struct ImBuf * drect, const float col[4])
Attention:
Defined in rectop.c
Definition at line 452 of file rectop.c.
References ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
void IMB_rectfill_alpha (struct ImBuf * ibuf, const float value)
Definition at line 576 of file rectop.c.
References i, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
void IMB_rectfill_area (struct ImBuf * ibuf, float * col, int x1, int y1, int x2, int y2)
Definition at line 569 of file rectop.c.
References buf_rectfill_area(), ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
void IMB_refImBuf (struct ImBuf * ibuf)
Increase reference count to imbuf (to delete an imbuf you have to call freeImBuf as many times as it is referenced)
Attention:
Defined in allocimbuf.c
Definition at line 170 of file allocimbuf.c.
References ImBuf::refcounter.
Referenced by avi_fetchibuf(), get_postprocessed_cached_frame(), get_stable_cached_frame(), IMB_moviecache_get(), IMB_moviecache_put(), put_postprocessed_frame_to_cache(), put_stabilized_frame_to_cache(), and seq_render_effect_strip_impl().
void IMB_remakemipmap (struct ImBuf * ibuf, int use_filter)
Definition at line 467 of file filter.c.
References IB_MIPMAP_LEVELS, IB_rect, IMB_allocImBuf(), IMB_filterN(), IMB_freeImBuf(), imb_onehalf_no_alloc(), ImBuf::miplevel, ImBuf::mipmap, ImBuf::miptot, ImBuf::x, and ImBuf::y.
Referenced by draw_bgpic(), and image_mipmap_test().
void IMB_saturation (struct ImBuf * ibuf, float sat)
Definition at line 756 of file divers.c.
References hsv_to_rgb(), i, if(), ImBuf::rect, ImBuf::rect_float, rgb_float_to_uchar(), rgb_to_hsv(), rgb_uchar_to_float(), ImBuf::x, and ImBuf::y.
Referenced by input_preprocess().
short IMB_saveiff (struct ImBuf * ibuf, const char * filepath, int flags)
Attention:
Defined in writeimage.c
Definition at line 43 of file writeimage.c.
References FALSE, ImFileType::flag, ImBuf::flags, ImFileType::ftype, IM_FTYPE_FLOAT, IMB_FILE_TYPES, IMB_rect_from_float(), ImFileType::is_a, NULL, ImBuf::rect, ImBuf::rect_float, and ImFileType::save.
Referenced by BKE_image_memorypack(), BKE_write_ibuf(), BL_MakeScreenShot(), dynamicPaint_outputSurfaceImage(), image_save_sequence_exec(), IMB_thumb_create(), movieclip_build_proxy_ibuf(), saveiff(), and seq_proxy_build_frame().
struct ImBuf* IMB_scalefastImBuf (struct ImBuf * ibuf, unsigned int newx, unsigned int newy) [read]
Attention:
Defined in scaling.c
Definition at line 1499 of file scaling.c.
References IB_rect, IB_rectfloat, imb_freerectfloatImBuf(), imb_freerectImBuf(), ImBuf::mall, MEM_freeN(), MEM_mallocN(), NULL, ImBuf::rect, ImBuf::rect_float, scalefast_Z_ImBuf(), ImBuf::x, and ImBuf::y.
Referenced by BKE_tracking_stabilize(), icon_copy_rect(), index_rebuild_fallback(), input_preprocess(), scalefastImBuf(), and seq_proxy_build_frame().
struct ImBuf* IMB_scaleImBuf (struct ImBuf * ibuf, unsigned int newx, unsigned int newy) [read]
Attention:
Defined in scaling.c
Definition at line 1470 of file scaling.c.
References NULL, q_scale_linear_interpolation(), ImBuf::rect, ImBuf::rect_float, scaledownx(), scaledowny(), scalefast_Z_ImBuf(), scaleupx(), scaleupy(), ImBuf::x, and ImBuf::y.
Referenced by blend_file_thumb(), get_undistorted_ibuf(), icon_draw_rect(), IMB_thumb_create(), input_preprocess(), movieclip_build_proxy_ibuf(), node_composit_exec_scale(), and scaleImBuf().
struct ImBuf* IMB_testiffname (const char * filepath, int flags) [read]
Attention:
Defined in readimage.c
Definition at line 147 of file readimage.c.
References BLI_open(), BLI_strncpy(), ImBuf::cachename, IB_FILENAME_SIZE, IB_multilayer, IB_test, imb_cache_filename(), IMB_loadifffile(), ImBuf::name, NULL, and O_BINARY.
Referenced by testiffname().
void IMB_tile_cache_params (int totthread, int maxmem)
Attention:
Defined in cache.c
Definition at line 241 of file cache.c.
References BLI_ghash_new(), BLI_memarena_new(), BLI_MEMARENA_STD_BUFSIZE, BLI_memarena_use_calloc(), BLI_mutex_init(), imb_global_tile_cmp(), imb_global_tile_hash(), imb_thread_cache_init(), imb_tile_cache_exit(), ImGlobalTileCache::maxmem, ImGlobalTileCache::memarena, ImGlobalTileCache::mutex, ImGlobalTileCache::thread_cache, ImGlobalTileCache::tilehash, and ImGlobalTileCache::totthread.
Referenced by imb_tile_cache_init().
void IMB_tiles_to_rect (struct ImBuf * ibuf)
Definition at line 408 of file cache.c.
References BLI_mutex_lock(), BLI_mutex_unlock(), ImBuf::flags, IB_rect, IMB_getmipmap(), imb_global_cache_get_tile(), ImBuf::mall, MEM_mapallocN(), ImBuf::miptot, ImGlobalTileCache::mutex, NULL, ImBuf::rect, ImGlobalTile::refcount, ImBuf::tiles, ImBuf::tilex, ImBuf::tiley, ImBuf::x, ImBuf::xtiles, ImBuf::y, and ImBuf::ytiles.
int ismovie (const char * filepath)
Attention:
Defined in anim_movie.c
Referenced by imb_get_anim_type().
void neareast_interpolation (struct ImBuf * in, struct ImBuf * out, float u, float v, int xout, int yout)
Definition at line 445 of file imageprocess.c.
References neareast_interpolation_color(), NULL, pixel_from_buffer(), ImBuf::rect, and ImBuf::rect_float.
Referenced by BKE_tracking_stabilize(), node_composit_exec_rotate(), node_composit_transform(), and transform_image().
void neareast_interpolation_color (struct ImBuf * in, unsigned char * col, float * col_float, float u, float v)
Definition at line 398 of file imageprocess.c.
References if(), ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by neareast_interpolation().