Blender: STR_HashedString.h File Reference
STR_HashedString.h File Reference
string
#include "STR_String.h"
Classes
class STR_HashedString
Enumerations
enum { GOLDEN_RATIO = 0x9e3779b9 }
Functions
static void STR_gHashMix (dword &a, dword &b, dword &c)
static dword STR_gHash (dword inDWord)
static dword STR_gHash (const void *in, int len, dword init_val)
Detailed Description
Definition in file STR_HashedString.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
GOLDEN_RATIO
Definition at line 83 of file STR_HashedString.h.
Function Documentation
static dword STR_gHash (dword inDWord) [inline, static]
Definition at line 71 of file STR_HashedString.h.
Referenced by STR_HashedString::hash().
static dword STR_gHash (const void * in, int len, dword init_val) [static]
Definition at line 88 of file STR_HashedString.h.
References GOLDEN_RATIO, len(), length(), and STR_gHashMix().
static void STR_gHashMix (dword & a, dword & b, dword & c) [inline, static]
Copyright (C) 2001 NaN Technologies B.V. This file was formerly known as: GEN_StdString.cpp.
Date:
November, 14, 2001
Definition at line 54 of file STR_HashedString.h.
Referenced by STR_gHash().