Blender: KX_BlenderGL.cpp File Reference
KX_BlenderGL.cpp File Reference
Blender Routines
#include "KX_BlenderGL.h"
#include <stdlib.h>
#include <string.h>
#include "GL/glew.h"
#include "MEM_guardedalloc.h"
#include "BL_Material.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_camera_types.h"
#include "DNA_world_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_image_types.h"
#include "DNA_view3d_types.h"
#include "DNA_material_types.h"
#include "DNA_windowmanager_types.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_bmfont.h"
#include "BKE_image.h"
#include "BLI_path_util.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "WM_api.h"
#include "WM_types.h"
#include "wm_event_system.h"
#include "wm_cursors.h"
#include "wm_window.h"
#include "BLF_api.h"
Defines
#define MAX_FILE_LENGTH 512
Functions
void BL_warp_pointer (wmWindow *win, int x, int y)
void BL_SwapBuffers (wmWindow *win)
void DisableForText ()
void BL_print_game_line (int fontid, const char *text, int size, int dpi, float *color, double *mat, float aspect)
void BL_print_gamedebug_line (const char *text, int xco, int yco, int width, int height)
void BL_print_gamedebug_line_padded (const char *text, int xco, int yco, int width, int height)
void BL_HideMouse (wmWindow *win)
void BL_WaitMouse (wmWindow *win)
void BL_NormalMouse (wmWindow *win)
static unsigned int * screenshot (ScrArea *curarea, int *dumpsx, int *dumpsy)
void BL_MakeScreenShot (ScrArea *curarea, const char *filename)
Detailed Description
Definition in file KX_BlenderGL.cpp.
Define Documentation
#define MAX_FILE_LENGTH 512
Definition at line 229 of file KX_BlenderGL.cpp.
Referenced by BL_MakeScreenShot().
Function Documentation
void BL_HideMouse (wmWindow * win)
Definition at line 213 of file KX_BlenderGL.cpp.
References CURSOR_NONE, and WM_cursor_set().
Referenced by KX_BlenderCanvas::SetMouseState().
void BL_MakeScreenShot (ScrArea * curarea, const char * filename)
Definition at line 255 of file KX_BlenderGL.cpp.
References BKE_add_image_extension(), BLI_path_abs(), ImBuf::ftype, G, IB_rect, IMB_allocImBuf(), IMB_freeImBuf(), IMB_saveiff(), MAX_FILE_LENGTH, MEM_freeN(), NULL, PNG, R_IMF_IMTYPE_PNG, ImBuf::rect, and screenshot().
Referenced by KX_BlenderCanvas::MakeScreenShot().
void BL_NormalMouse (wmWindow * win)
Definition at line 225 of file KX_BlenderGL.cpp.
References CURSOR_STD, and WM_cursor_set().
Referenced by KX_BlenderCanvas::SetMouseState().
void BL_print_game_line (int fontid, const char * text, int size, int dpi, float * color, double * mat, float aspect)
Definition at line 131 of file KX_BlenderGL.cpp.
References BLF_ASPECT, BLF_aspect(), BLF_disable(), BLF_draw(), BLF_enable(), BLF_matrix(), BLF_MATRIX, BLF_position(), BLF_size(), and DisableForText().
Referenced by KX_BlenderRenderTools::RenderText3D().
void BL_print_gamedebug_line (const char * text, int xco, int yco, int width, int height)
Definition at line 155 of file KX_BlenderGL.cpp.
References BLF_draw_default(), and DisableForText().
Referenced by KX_BlenderRenderTools::RenderText2D().
void BL_print_gamedebug_line_padded (const char * text, int xco, int yco, int width, int height)
Definition at line 182 of file KX_BlenderGL.cpp.
References BLF_draw_default(), and DisableForText().
Referenced by KX_BlenderRenderTools::RenderText2D().
void BL_SwapBuffers (wmWindow * win)
Definition at line 89 of file KX_BlenderGL.cpp.
References wm_window_swap_buffers().
Referenced by KX_BlenderCanvas::SwapBuffers().
void BL_WaitMouse (wmWindow * win)
Definition at line 219 of file KX_BlenderGL.cpp.
References CURSOR_WAIT, and WM_cursor_set().
Referenced by KX_BlenderCanvas::SetMouseState().
void BL_warp_pointer (wmWindow * win, int x, int y)
Definition at line 84 of file KX_BlenderGL.cpp.
References WM_cursor_warp().
Referenced by KX_BlenderCanvas::SetMousePosition().
void DisableForText ()
Definition at line 94 of file KX_BlenderGL.cpp.
References i, and MAXTEX.
Referenced by BL_print_game_line(), BL_print_gamedebug_line(), and BL_print_gamedebug_line_padded().
static unsigned int* screenshot (ScrArea * curarea, int * dumpsx, int * dumpsy) [static]
Definition at line 232 of file KX_BlenderGL.cpp.
References MEM_mallocN(), NULL, ScrArea::totrct, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by BL_MakeScreenShot().