Blender: node_shader_mix_shader.c File Reference
node_shader_mix_shader.c File Reference
#include "../node_shader_util.h"
Functions
static int node_shader_gpu_mix_shader (GPUMaterial *mat, bNode *UNUSED(node), GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_mix_shader (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_mix_shader_in []
static bNodeSocketTemplate sh_node_mix_shader_out []
Function Documentation
static int node_shader_gpu_mix_shader (GPUMaterial * mat, bNode * UNUSEDnode, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 44 of file node_shader_mix_shader.c.
References GPU_stack_link().
Referenced by register_node_type_sh_mix_shader().
void register_node_type_sh_mix_shader (bNodeTreeType * ttype)
Definition at line 50 of file node_shader_mix_shader.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_shader_gpu_mix_shader(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_MIX_SHADER.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_mix_shader_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT,  1, "Fac",      0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_SHADER, 1, "Shader"},
    {   SOCK_SHADER, 1, "Shader"},
    {   -1, 0, ""   }
}
Definition at line 32 of file node_shader_mix_shader.c.
bNodeSocketTemplate sh_node_mix_shader_out[] [static]
Initial value:
 {
    {   SOCK_SHADER, 0, "Shader"},
    {   -1, 0, ""   }
}
Definition at line 39 of file node_shader_mix_shader.c.