Blender: MOD_boolean_util.h File Reference
MOD_boolean_util.h File Reference
modifiers
Functions
int NewBooleanMesh (struct Scene *scene, struct Base *base, struct Base *base_select, int op)
struct DerivedMesh * NewBooleanDerivedMesh (struct DerivedMesh *dm, struct Object *ob, struct DerivedMesh *dm_select, struct Object *ob_select, int int_op_type)
Detailed Description
Definition in file MOD_boolean_util.h.
Function Documentation
struct DerivedMesh* NewBooleanDerivedMesh (struct DerivedMesh * dm, struct Object * ob, struct DerivedMesh * dm_select, struct Object * ob_select, int int_op_type) [read]
Definition at line 645 of file MOD_boolean_util.c.
References NewBooleanDerivedMesh_intern(), and NULL.
int NewBooleanMesh (struct Scene * scene, struct Base * base, struct Base * base_select, int op)
Definition at line 587 of file MOD_boolean_util.c.
References AddNewBlenderMesh(), assign_material(), CD_MASK_BAREMESH, DAG_id_tag_update(), Object::data, DM_to_mesh(), DerivedMesh::getNumTessFaces, Object::id, MEM_freeN(), MEM_mallocN(), mesh_create_derived_view(), mesh_get_derived_final(), NewBooleanDerivedMesh_intern(), NULL, OB_RECALC_DATA, Base::object, DerivedMesh::release, and Object::totcol.