Blender: node_fresnel.h File Reference
node_fresnel.h File Reference
Functions
float fresnel_dielectric (vector Incoming, normal Normal, float eta)
Function Documentation
float fresnel_dielectric (vector Incoming, normal Normal, float eta)
Definition at line 2 of file node_fresnel.h.
References A, B, dot(), fabs(), g, and sqrt().
Referenced by bsdf_microfacet_beckmann_sample(), bsdf_microfacet_ggx_sample(), bsdf_refraction_sample(), RefractionClosure::sample(), MicrofacetBeckmannClosure< Refractive >::sample(), and MicrofacetGGXClosure< Refractive >::sample().