Blender: MOD_dynamicpaint.c File Reference
MOD_dynamicpaint.c File Reference
modifiers
#include <stddef.h>
#include "DNA_dynamicpaint_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_dynamicpaint.h"
#include "BKE_modifier.h"
#include "depsgraph_private.h"
#include "MOD_util.h"
Functions
static void initData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static void freeData (ModifierData *md)
static CustomDataMask requiredDataMask (Object *UNUSED(ob), ModifierData *md)
static DerivedMesh * applyModifier (ModifierData *md, Object *ob, DerivedMesh *dm, int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
static void updateDepgraph (ModifierData *md, DagForest *forest, struct Scene *scene, Object *ob, DagNode *obNode)
static int dependsOnTime (ModifierData *UNUSED(md))
static void foreachIDLink (ModifierData *md, Object *ob, IDWalkFunc walk, void *userData)
static void foreachTexLink (ModifierData *UNUSED(md), Object *UNUSED(ob), TexWalkFunc UNUSED(walk), void *UNUSED(userData))
Variables
ModifierTypeInfo modifierType_DynamicPaint
Detailed Description
Definition in file MOD_dynamicpaint.c.
Function Documentation
static DerivedMesh* applyModifier (ModifierData * md, Object * ob, DerivedMesh * dm, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 104 of file MOD_dynamicpaint.c.
References dynamicPaint_Modifier_do(), and ModifierData::scene.
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 57 of file MOD_dynamicpaint.c.
References dynamicPaint_Modifier_copy().
static int dependsOnTime (ModifierData * UNUSEDmd) [static]
Definition at line 136 of file MOD_dynamicpaint.c.
static void foreachIDLink (ModifierData * md, Object * ob, IDWalkFunc walk, void * userData) [static]
Definition at line 141 of file MOD_dynamicpaint.c.
References DynamicPaintModifierData::brush, DynamicPaintSurface::brush_group, DynamicPaintModifierData::canvas, ListBase::first, DynamicPaintSurface::init_texture, DynamicPaintBrushSettings::mat, DynamicPaintSurface::next, and DynamicPaintCanvasSettings::surfaces.
static void foreachTexLink (ModifierData * UNUSEDmd, Object * UNUSEDob, TexWalkFunc UNUSEDwalk, void * UNUSEDuserData) [static]
Definition at line 159 of file MOD_dynamicpaint.c.
static void freeData (ModifierData * md) [static]
Definition at line 65 of file MOD_dynamicpaint.c.
References dynamicPaint_Modifier_free().
static void initData (ModifierData * md) [static]
Definition at line 48 of file MOD_dynamicpaint.c.
References DynamicPaintModifierData::brush, DynamicPaintModifierData::canvas, MOD_DYNAMICPAINT_TYPE_CANVAS, NULL, and DynamicPaintModifierData::type.
static CustomDataMask requiredDataMask (Object * UNUSEDob, ModifierData * md) [static]
Definition at line 71 of file MOD_dynamicpaint.c.
References DynamicPaintModifierData::brush, DynamicPaintModifierData::canvas, CD_MCOL, CD_MDEFORMVERT, CD_MTFACE, ListBase::first, DynamicPaintBrushSettings::flags, DynamicPaintSurface::format, DynamicPaintSurface::init_color_type, MOD_DPAINT_INITIAL_TEXTURE, MOD_DPAINT_INITIAL_VERTEXCOLOR, MOD_DPAINT_SURFACE_F_IMAGESEQ, MOD_DPAINT_SURFACE_T_PAINT, MOD_DPAINT_SURFACE_T_WEIGHT, MOD_DPAINT_USE_MATERIAL, DynamicPaintSurface::next, DynamicPaintCanvasSettings::surfaces, and DynamicPaintSurface::type.
static void updateDepgraph (ModifierData * md, DagForest * forest, struct Scene * scene, Object * ob, DagNode * obNode) [static]
Definition at line 114 of file MOD_dynamicpaint.c.
References Scene::base, DynamicPaintModifierData::brush, DynamicPaintModifierData::canvas, dag_add_relation(), dag_get_node(), DAG_RL_DATA_DATA, DAG_RL_OB_DATA, eModifierType_DynamicPaint, ListBase::first, modifiers_findByType(), Base::next, and Base::object.
Variable Documentation
ModifierTypeInfo modifierType_DynamicPaint
Initial value:
 {
                  "Dynamic Paint",
            "DynamicPaintModifierData",
            sizeof(DynamicPaintModifierData),
                  eModifierTypeType_Constructive,
                 eModifierTypeFlag_AcceptsMesh
                           |eModifierTypeFlag_UsesPointCache
                           |eModifierTypeFlag_Single
                           |eModifierTypeFlag_UsesPreview,
              copyData,
           NULL,
        NULL,
         NULL,
      NULL,
         applyModifier,
       NULL,
              initData,
      requiredDataMask,
              freeData,
            NULL,
        updateDepgraph,
         dependsOnTime,
      NULL,
     NULL,
         foreachIDLink,
        foreachTexLink,
}
Definition at line 165 of file MOD_dynamicpaint.c.