Blender: action_draw.c File Reference
action_draw.c File Reference
action space
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "DNA_anim_types.h"
#include "DNA_screen_types.h"
#include "BKE_action.h"
#include "BKE_context.h"
#include "BIF_gl.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "ED_anim_api.h"
#include "ED_keyframes_draw.h"
#include "action_intern.h"
Defines
#define EXTRA_SCROLL_PAD 100.0f
Functions
void draw_channel_names (bContext *C, bAnimContext *ac, ARegion *ar)
void draw_channel_strips (bAnimContext *ac, SpaceAction *saction, ARegion *ar)
Detailed Description
Definition in file action_draw.c.
Define Documentation
#define EXTRA_SCROLL_PAD 100.0f
Definition at line 156 of file action_draw.c.
Referenced by draw_channel_strips().
Function Documentation
void draw_channel_names (bContext * C, bAnimContext * ac, ARegion * ar)
Definition at line 70 of file action_draw.c.
References ACHANNEL_FIRST, ACHANNEL_HEIGHT, ACHANNEL_HEIGHT_HALF, ACHANNEL_STEP, ANIM_animdata_filter(), ANIM_channel_draw(), ANIM_channel_draw_widgets(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, BLI_freelistN(), View2D::cur, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, IN_RANGE, View2D::mask, bAnimListElem::next, NULL, bAnimContext::sa, View2D::tot, UI_EMBOSS, UI_view2d_sync(), uiBeginBlock(), uiDrawBlock(), uiEndBlock(), ARegion::v2d, V2D_LOCK_COPY, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by action_channel_area_draw().
void draw_channel_strips (bAnimContext * ac, SpaceAction * saction, ARegion * ar)
Definition at line 159 of file action_draw.c.
References ACHANNEL_HEIGHT, ACHANNEL_HEIGHT_HALF, ACHANNEL_SETTING_SELECT, ACHANNEL_STEP, SpaceAction::ads, ALE_ACT, ALE_ALL, ALE_FCURVE, ALE_GPFRAME, ALE_GROUP, ALE_NONE, ALE_OB, ALE_SCE, ANIM_animdata_filter(), ANIM_channel_get_typeinfo(), ANIM_channel_setting_get(), ANIM_nla_mapping_get(), ANIMCONT_ACTION, ANIMCONT_DOPESHEET, ANIMCONT_GPENCIL, ANIMCONT_SHAPEKEY, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, ANIMTYPE_DSSKEY, ANIMTYPE_DSWOR, ANIMTYPE_FILLACTD, ANIMTYPE_GROUP, ANIMTYPE_OBJECT, ANIMTYPE_SCENE, ANIMTYPE_SUMMARY, BLI_freelistN(), calc_action_range(), View2D::cur, bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, bAnimListElem::datatype, draw_action_channel(), draw_agroup_channel(), draw_fcurve_channel(), draw_gpl_channel(), draw_object_channel(), draw_scene_channel(), draw_summary_channel(), ELEM3, EXTRA_SCROLL_PAD, filter(), ListBase::first, SpaceAction::flag, bAnimChannelType::has_setting, IN_RANGE, bAnimListElem::key_data, bAnimListElem::next, NULL, SACTION_MOVING, TH_BACK, TH_DOPESHEET_CHANNELOB, TH_DOPESHEET_CHANNELSUBOB, TH_GROUP, TH_GROUP_ACTIVE, TH_HILITE, SpaceAction::timeslide, View2D::tot, bAnimListElem::type, UI_GetThemeColor3ubv(), ARegion::v2d, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by action_main_area_draw().