Blender: bmo_dupe.c File Reference
bmo_dupe.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "BLI_array.h"
#include "BLI_math.h"
#include "bmesh.h"
#include "intern/bmesh_operators_private.h"
Defines
#define DUPE_INPUT 1
#define DUPE_NEW 2
#define DUPE_DONE 4
#define DUPE_MAPPED 8
#define SPLIT_INPUT 1
#define DEL_INPUT 1
Functions
static BMVert * copy_vertex (BMesh *source_mesh, BMVert *source_vertex, BMesh *target_mesh, GHash *vhash)
static BMEdge * copy_edge (BMOperator *op, BMesh *source_mesh, BMEdge *source_edge, BMesh *target_mesh, GHash *vhash, GHash *ehash)
static BMFace * copy_face (BMOperator *op, BMesh *source_mesh, BMFace *source_face, BMesh *target_mesh, BMVert **vtar, BMEdge **edar, GHash *vhash, GHash *ehash)
static void copy_mesh (BMOperator *op, BMesh *source, BMesh *target)
void bmo_dupe_exec (BMesh *bm, BMOperator *op)
void bmo_split_exec (BMesh *bm, BMOperator *op)
void bmo_del_exec (BMesh *bm, BMOperator *op)
void bmo_spin_exec (BMesh *bm, BMOperator *op)
Detailed Description
Definition in file bmo_dupe.c.
Define Documentation
#define DEL_INPUT 1
Referenced by bmo_del_exec().
#define DUPE_DONE 4
Definition at line 39 of file bmo_dupe.c.
Referenced by copy_mesh().
#define DUPE_INPUT 1
Definition at line 37 of file bmo_dupe.c.
Referenced by bmo_dupe_exec(), copy_edge(), and copy_mesh().
#define DUPE_MAPPED 8
Definition at line 40 of file bmo_dupe.c.
#define DUPE_NEW 2
Definition at line 38 of file bmo_dupe.c.
Referenced by bmo_dupe_exec(), copy_edge(), copy_face(), and copy_vertex().
#define SPLIT_INPUT 1
Split Operator
Duplicates verts, edges and faces of a mesh but also deletes the originals.
INPUT SLOTS:
BMOP_DUPE_VINPUT: Buffer containing pointers to mesh vertices to be split BMOP_DUPE_EINPUT: Buffer containing pointers to mesh edges to be split BMOP_DUPE_FINPUT: Buffer containing pointers to mesh faces to be split
OUTPUT SLOTS:
BMOP_DUPE_VOUTPUT: Buffer containing pointers to the split mesh vertices BMOP_DUPE_EOUTPUT: Buffer containing pointers to the split mesh edges BMOP_DUPE_FOUTPUT: Buffer containing pointers to the split mesh faces
Definition at line 374 of file bmo_dupe.c.
Referenced by bmo_split_exec().
Function Documentation
void bmo_del_exec (BMesh * bm, BMOperator * op)
Definition at line 446 of file bmo_dupe.c.
References BM_ALL, BMO_remove_tagged_context(), BMO_slot_buffer_flag_enable(), BMO_slot_int_get(), and DEL_INPUT.
void bmo_dupe_exec (BMesh * bm, BMOperator * op)
Duplicate Operator
Duplicates verts, edges and faces of a mesh.
INPUT SLOTS:
BMOP_DUPE_VINPUT: Buffer containing pointers to mesh vertices to be duplicated BMOP_DUPE_EINPUT: Buffer containing pointers to mesh edges to be duplicated BMOP_DUPE_FINPUT: Buffer containing pointers to mesh faces to be duplicated
OUTPUT SLOTS:
BMOP_DUPE_VORIGINAL: Buffer containing pointers to the original mesh vertices BMOP_DUPE_EORIGINAL: Buffer containing pointers to the original mesh edges BMOP_DUPE_FORIGINAL: Buffer containing pointers to the original mesh faces BMOP_DUPE_VNEW: Buffer containing pointers to the new mesh vertices BMOP_DUPE_ENEW: Buffer containing pointers to the new mesh edges BMOP_DUPE_FNEW: Buffer containing pointers to the new mesh faces
Definition at line 317 of file bmo_dupe.c.
References BM_ALL, BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_copy(), BMO_slot_ptr_get(), copy_mesh(), DUPE_INPUT, and DUPE_NEW.
void bmo_spin_exec (BMesh * bm, BMOperator * op)
Spin Operator
Extrude or duplicate geometry a number of times, rotating and possibly translating after each step
Definition at line 467 of file bmo_dupe.c.
References axis_angle_to_mat3(), BMO_op_callf(), BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_bool_get(), BMO_slot_copy(), BMO_slot_float_get(), BMO_slot_int_get(), BMO_slot_vec_get(), DEG2RADF, is_zero_v3(), and normalize_v3().
void bmo_split_exec (BMesh * bm, BMOperator * op)
Definition at line 376 of file bmo_dupe.c.
References BM_ALL, BM_EDGES_OF_MESH, BM_EDGES_OF_VERT, BM_FACES_OF_EDGE, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_copy(), BMO_slot_int_set(), DEL_FACES, NULL, and SPLIT_INPUT.
static BMEdge* copy_edge (BMOperator * op, BMesh * source_mesh, BMEdge * source_edge, BMesh * target_mesh, GHash * vhash, GHash * ehash) [static]
COPY EDGE
Copy an existing edge from one bmesh to another.
Definition at line 71 of file bmo_dupe.c.
References BLI_ghash_insert(), BLI_ghash_lookup(), BM_edge_create(), BM_elem_attrs_copy(), BM_FACES_OF_EDGE, BM_iter_new(), BM_iter_step(), BMO_elem_flag_enable, BMO_elem_flag_test, BMO_slot_map_ptr_insert(), DUPE_INPUT, DUPE_NEW, FALSE, NULL, BMEdge::v1, and BMEdge::v2.
Referenced by copy_mesh().
static BMFace* copy_face (BMOperator * op, BMesh * source_mesh, BMFace * source_face, BMesh * target_mesh, BMVert ** vtar, BMEdge ** edar, GHash * vhash, GHash * ehash) [static]
COPY FACE
Copy an existing face from one bmesh to another.
Definition at line 127 of file bmo_dupe.c.
References BLI_ghash_lookup(), BM_elem_attrs_copy(), BM_face_create(), BM_ITER_ELEM, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BM_VERTS_OF_FACE, BMO_elem_flag_enable, BMO_slot_map_ptr_insert(), DUPE_NEW, BMLoop::e, FALSE, i, BMFace::len, NULL, and BMLoop::v.
Referenced by copy_mesh().
static void copy_mesh (BMOperator * op, BMesh * source, BMesh * target) [static]
COPY MESH
Internal Copy function.
Definition at line 184 of file bmo_dupe.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BLI_ghash_free(), BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BM_EDGES_OF_FACE, BM_EDGES_OF_MESH, BM_EDGES_OF_VERT, BM_FACES_OF_MESH, BM_FACES_OF_VERT, BM_ITER_ELEM, BM_ITER_MESH, BM_VERTS_OF_FACE, BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_slot_map_ptr_insert(), copy_edge(), copy_face(), copy_vertex(), DUPE_DONE, DUPE_INPUT, BMFace::len, NULL, BMEdge::v1, and BMEdge::v2.
static BMVert* copy_vertex (BMesh * source_mesh, BMVert * source_vertex, BMesh * target_mesh, GHash * vhash) [static]
COPY VERTEX
Copy an existing vertex from one bmesh to another.
Definition at line 47 of file bmo_dupe.c.
References BLI_ghash_insert(), BM_elem_attrs_copy(), BM_vert_create(), BMO_elem_flag_enable, BMVert::co, DUPE_NEW, and NULL.
Referenced by copy_mesh().