Blender: AUD_ConverterReader Class Reference
AUD_ConverterReader Class Reference
#include <AUD_ConverterReader.h>
Public Member Functions
AUD_ConverterReader (AUD_Reference< AUD_IReader > reader, AUD_DeviceSpecs specs)
virtual void read (int &length, bool &eos, sample_t *buffer)
Detailed Description
This class converts a sound source from one to another format.
Definition at line 40 of file AUD_ConverterReader.h.
Constructor & Destructor Documentation
AUD_ConverterReader::AUD_ConverterReader (AUD_Reference< AUD_IReader > reader, AUD_DeviceSpecs specs)
Creates a converter reader.
Parameters:
reader The reader to convert.
specs The target specification.
Definition at line 32 of file AUD_ConverterReader.cpp.
References AUD_convert_float_double(), AUD_convert_float_s16(), AUD_convert_float_s24_be(), AUD_convert_float_s24_le(), AUD_convert_float_s32(), AUD_convert_float_u8(), AUD_FORMAT_FLOAT32, AUD_FORMAT_FLOAT64, AUD_FORMAT_S16, AUD_FORMAT_S24, AUD_FORMAT_S32, and AUD_FORMAT_U8.
Member Function Documentation
void AUD_ConverterReader::read (int & length, bool & eos, sample_t * buffer) [virtual]
Request to read the next length samples out of the source. The buffer supplied has the needed size.
Parameters:
[in,out] length The count of samples that should be read. Shall contain the real count of samples after reading, in case there were only fewer samples available. A smaller value also indicates the end of the reader.
[out] eos End of stream, whether the end is reached or not.
[in] buffer The pointer to the buffer to read into.
Reimplemented from AUD_EffectReader.
Definition at line 66 of file AUD_ConverterReader.cpp.
References AUD_Buffer::assureSize(), AUD_SAMPLE_SIZE, AUD_Specs::channels, AUD_Buffer::getBuffer(), and AUD_EffectReader::m_reader.
The documentation for this class was generated from the following files:
AUD_ConverterReader.h
AUD_ConverterReader.cpp