Blender: BicubicTangentPatch Class Reference
BicubicTangentPatch Class Reference
#include <subd_patch.h>
Public Member Functions
void eval (float3 *P, float3 *dPdu, float3 *dPdv, float u, float v)
bool is_triangle ()
BoundBox bound ()
Public Attributes
float3 hull [16]
float3 utan [12]
float3 vtan [12]
Detailed Description
Definition at line 74 of file subd_patch.h.
Member Function Documentation
BoundBox BicubicTangentPatch::bound () [virtual]
Implements Patch.
Definition at line 153 of file subd_patch.cpp.
References BoundBox::grow(), hull, and i.
void BicubicTangentPatch::eval (float3 * P, float3 * dPdu, float3 * dPdv, float u, float v) [virtual]
Implements Patch.
Definition at line 145 of file subd_patch.cpp.
References decasteljau_bicubic(), decasteljau_tangent(), hull, NULL, utan, and vtan.
bool BicubicTangentPatch::is_triangle () [inline, virtual]
Implements Patch.
Definition at line 81 of file subd_patch.h.
Member Data Documentation
float3 BicubicTangentPatch::hull[16]
Definition at line 76 of file subd_patch.h.
Referenced by bound(), and eval().
float3 BicubicTangentPatch::utan[12]
Definition at line 77 of file subd_patch.h.
Referenced by eval().
float3 BicubicTangentPatch::vtan[12]
Definition at line 78 of file subd_patch.h.
Referenced by eval().
The documentation for this class was generated from the following files:
subd_patch.h
subd_patch.cpp