Blender: node_composite_idMask.c File Reference
node_composite_idMask.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_idmask (CompBuf *stackbuf, CompBuf *cbuf, float idnr)
static void do_idmask_fsa (CompBuf *stackbuf, CompBuf *cbuf, float idnr)
static void node_composit_exec_idmask (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_idmask (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_idmask_in []
static bNodeSocketTemplate cmp_node_idmask_out []
Detailed Description
Definition in file node_composite_idMask.c.
Function Documentation
static void do_idmask (CompBuf * stackbuf, CompBuf * cbuf, float idnr) [static]
Definition at line 48 of file node_composite_idMask.c.
References antialias_tagbuf(), MEM_freeN(), MEM_mapallocN(), CompBuf::rect, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_idmask().
static void do_idmask_fsa (CompBuf * stackbuf, CompBuf * cbuf, float idnr) [static]
Definition at line 70 of file node_composite_idMask.c.
References CompBuf::rect, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_idmask().
static void node_composit_exec_idmask (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 84 of file node_composite_idMask.c.
References alloc_compbuf(), CB_VAL, bNode::custom1, bNode::custom2, bNodeStack::data, data, do_idmask(), do_idmask_fsa(), R_FULL_SAMPLE, RenderData::scemode, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_idmask().
void register_node_type_cmp_idmask (bNodeTreeType * ttype)
Definition at line 110 of file node_composite_idMask.c.
References CMP_NODE_ID_MASK, NODE_CLASS_CONVERTOR, node_composit_exec_idmask(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_idmask_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "ID value",          1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
    {   -1, 0, ""   }
}
Definition at line 38 of file node_composite_idMask.c.
bNodeSocketTemplate cmp_node_idmask_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "Alpha"},
    {   -1, 0, ""   }
}
Definition at line 42 of file node_composite_idMask.c.