Blender: rna_sequencer_api.c File Reference
rna_sequencer_api.c File Reference
RNA
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "RNA_define.h"
#include "RNA_access.h"
#include "rna_internal.h"
#include "DNA_scene_types.h"
#include "DNA_sequence_types.h"
Functions
void RNA_api_sequence_strip (StructRNA *srna)
Detailed Description
Definition in file rna_sequencer_api.c.
Function Documentation
void RNA_api_sequence_strip (StructRNA * srna)
Definition at line 57 of file rna_sequencer_api.c.
References FUNC_USE_REPORTS, MAXFRAME, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), and RNA_def_property_flag().
Referenced by rna_def_sequence().