Blender: MT_Vector4.h File Reference
MT_Vector4.h File Reference
moto
#include <MT_assert.h>
#include "MT_Tuple4.h"
Classes
class MT_Vector4
Functions
MT_Vector4 operator+ (const MT_Vector4 &v1, const MT_Vector4 &v2)
MT_Vector4 operator- (const MT_Vector4 &v1, const MT_Vector4 &v2)
MT_Vector4 operator- (const MT_Vector4 &v)
MT_Vector4 operator* (const MT_Vector4 &v, MT_Scalar s)
MT_Vector4 operator* (MT_Scalar s, const MT_Vector4 &v)
MT_Vector4 operator/ (const MT_Vector4 &v, MT_Scalar s)
MT_Scalar MT_dot (const MT_Vector4 &v1, const MT_Vector4 &v2)
MT_Scalar MT_length2 (const MT_Vector4 &v)
MT_Scalar MT_length (const MT_Vector4 &v)
bool MT_fuzzyZero (const MT_Vector4 &v)
bool MT_fuzzyEqual (const MT_Vector4 &v1, const MT_Vector4 &v2)
Detailed Description
Definition in file MT_Vector4.h.
Function Documentation
MT_Scalar MT_dot (const MT_Vector4 & v1, const MT_Vector4 & v2)
Definition at line 70 of file MT_Vector4.inl.
References MT_Vector4::dot().
bool MT_fuzzyEqual (const MT_Vector4 & v1, const MT_Vector4 & v2)
Definition at line 78 of file MT_Vector4.inl.
References MT_fuzzyZero().
bool MT_fuzzyZero (const MT_Vector4 & v)
Definition at line 77 of file MT_Vector4.inl.
References MT_Vector4::fuzzyZero().
MT_Scalar MT_length (const MT_Vector4 & v)
Definition at line 75 of file MT_Vector4.inl.
References MT_Vector4::length().
MT_Scalar MT_length2 (const MT_Vector4 & v)
Definition at line 74 of file MT_Vector4.inl.
References MT_Vector4::length2().
MT_Vector4 operator* (MT_Scalar s, const MT_Vector4 & v)
Definition at line 39 of file MT_Vector4.inl.
MT_Vector4 operator* (const MT_Vector4 & v, MT_Scalar s)
Definition at line 35 of file MT_Vector4.inl.
MT_Vector4 operator+ (const MT_Vector4 & v1, const MT_Vector4 & v2)
Definition at line 23 of file MT_Vector4.inl.
MT_Vector4 operator- (const MT_Vector4 & v1, const MT_Vector4 & v2)
Definition at line 27 of file MT_Vector4.inl.
MT_Vector4 operator- (const MT_Vector4 & v)
Definition at line 31 of file MT_Vector4.inl.
MT_Vector4 operator/ (const MT_Vector4 & v, MT_Scalar s)
Definition at line 41 of file MT_Vector4.inl.
References MT_assert, and MT_fuzzyZero().