Blender: BLI_pbvh.h File Reference
BLI_pbvh.h File Reference
blenlib
A BVH for high poly meshes.
#include "BLI_bitmap.h"
Classes
struct PBVHProxyNode
struct PBVHVertexIter
Defines
#define PBVH_ITER_ALL 0
#define PBVH_ITER_UNIQUE 1
#define BLI_pbvh_vertex_iter_begin(bvh, node, vi, mode)
#define BLI_pbvh_vertex_iter_end
Typedefs
typedef struct PBVH PBVH
typedef struct PBVHNode PBVHNode
typedef int(* BLI_pbvh_SearchCallback)(PBVHNode *node, void *data)
typedef void(* BLI_pbvh_HitCallback)(PBVHNode *node, void *data)
typedef void(* BLI_pbvh_HitOccludedCallback)(PBVHNode *node, void *data, float *tmin)
typedef struct PBVHVertexIter PBVHVertexIter
Enumerations
enum PBVHType { PBVH_FACES, PBVH_GRIDS }
enum PBVHNodeFlags {
PBVH_Leaf = 1, PBVH_UpdateNormals = 2, PBVH_UpdateBB = 4, PBVH_UpdateOriginalBB = 8,
PBVH_UpdateDrawBuffers = 16, PBVH_UpdateRedraw = 32, PBVH_RebuildDrawBuffers = 64, PBVH_FullyHidden = 128
}
Functions
PBVH * BLI_pbvh_new (void)
void BLI_pbvh_build_mesh (PBVH *bvh, struct MFace *faces, struct MVert *verts, int totface, int totvert)
void BLI_pbvh_build_grids (PBVH *bvh, struct DMGridData **grids, struct DMGridAdjacency *gridadj, int totgrid, int gridsize, void **gridfaces, struct DMFlagMat *flagmats, unsigned int **grid_hidden)
void BLI_pbvh_free (PBVH *bvh)
void BLI_pbvh_search_callback (PBVH *bvh, BLI_pbvh_SearchCallback scb, void *search_data, BLI_pbvh_HitCallback hcb, void *hit_data)
void BLI_pbvh_search_gather (PBVH *bvh, BLI_pbvh_SearchCallback scb, void *search_data, PBVHNode ***array, int *tot)
void BLI_pbvh_raycast (PBVH *bvh, BLI_pbvh_HitOccludedCallback cb, void *data, float ray_start[3], float ray_normal[3], int original)
int BLI_pbvh_node_raycast (PBVH *bvh, PBVHNode *node, float(*origco)[3], float ray_start[3], float ray_normal[3], float *dist)
void BLI_pbvh_node_draw (PBVHNode *node, void *data)
void BLI_pbvh_draw (PBVH *bvh, float(*planes)[4], float(*face_nors)[3], int(*setMaterial)(int, void *attribs))
PBVHType BLI_pbvh_type (const PBVH *bvh)
unsigned int ** BLI_pbvh_grid_hidden (const PBVH *bvh)
void BLI_pbvh_node_mark_update (PBVHNode *node)
void BLI_pbvh_node_mark_rebuild_draw (PBVHNode *node)
void BLI_pbvh_node_fully_hidden_set (PBVHNode *node, int fully_hidden)
void BLI_pbvh_node_get_grids (PBVH *bvh, PBVHNode *node, int **grid_indices, int *totgrid, int *maxgrid, int *gridsize, struct DMGridData ***griddata, struct DMGridAdjacency **gridadj)
void BLI_pbvh_node_num_verts (PBVH *bvh, PBVHNode *node, int *uniquevert, int *totvert)
void BLI_pbvh_node_get_verts (PBVH *bvh, PBVHNode *node, int **vert_indices, struct MVert **verts)
void BLI_pbvh_node_get_BB (PBVHNode *node, float bb_min[3], float bb_max[3])
void BLI_pbvh_node_get_original_BB (PBVHNode *node, float bb_min[3], float bb_max[3])
float BLI_pbvh_node_get_tmin (PBVHNode *node)
int BLI_pbvh_node_planes_contain_AABB (PBVHNode *node, void *data)
int BLI_pbvh_node_planes_exclude_AABB (PBVHNode *node, void *data)
void BLI_pbvh_update (PBVH *bvh, int flags, float(*face_nors)[3])
void BLI_pbvh_redraw_BB (PBVH *bvh, float bb_min[3], float bb_max[3])
void BLI_pbvh_get_grid_updates (PBVH *bvh, int clear, void ***gridfaces, int *totface)
void BLI_pbvh_grids_update (PBVH *bvh, struct DMGridData **grids, struct DMGridAdjacency *gridadj, void **gridfaces)
float(* BLI_pbvh_get_vertCos (struct PBVH *pbvh))[3]
void BLI_pbvh_apply_vertCos (struct PBVH *pbvh, float(*vertCos)[3])
int BLI_pbvh_isDeformed (struct PBVH *pbvh)
void pbvh_vertex_iter_init (PBVH *bvh, PBVHNode *node, PBVHVertexIter *vi, int mode)
void BLI_pbvh_node_get_proxies (PBVHNode *node, PBVHProxyNode **proxies, int *proxy_count)
void BLI_pbvh_node_free_proxies (PBVHNode *node)
PBVHProxyNode * BLI_pbvh_node_add_proxy (PBVH *bvh, PBVHNode *node)
void BLI_pbvh_gather_proxies (PBVH *pbvh, PBVHNode ***nodes, int *totnode)
Detailed Description
A BVH for high poly meshes.
Definition in file BLI_pbvh.h.
Define Documentation
#define BLI_pbvh_vertex_iter_begin (bvh, node, vi, mode)
Definition at line 204 of file BLI_pbvh.h.
Referenced by calc_area_normal(), calc_area_normal_and_flatten_center(), calc_flatten_center(), do_clay_brush(), do_clay_strips_brush(), do_crease_brush(), do_draw_brush(), do_fill_brush(), do_flatten_brush(), do_grab_brush(), do_inflate_brush(), do_layer_brush(), do_mesh_smooth_brush(), do_nudge_brush(), do_pinch_brush(), do_rotate_brush(), do_scrape_brush(), do_snake_hook_brush(), do_thumb_brush(), sculpt_combine_proxies(), sculpt_flush_stroke_deform(), sculpt_restore_mesh(), sculpt_undo_store_coords(), and update_node_vb().
#define BLI_pbvh_vertex_iter_end
Value:
} \
        } \
    }
Definition at line 239 of file BLI_pbvh.h.
Referenced by calc_area_normal(), calc_area_normal_and_flatten_center(), calc_flatten_center(), do_clay_brush(), do_clay_strips_brush(), do_crease_brush(), do_draw_brush(), do_fill_brush(), do_flatten_brush(), do_grab_brush(), do_inflate_brush(), do_layer_brush(), do_mesh_smooth_brush(), do_nudge_brush(), do_pinch_brush(), do_rotate_brush(), do_scrape_brush(), do_snake_hook_brush(), do_thumb_brush(), sculpt_combine_proxies(), sculpt_flush_stroke_deform(), sculpt_restore_mesh(), sculpt_undo_store_coords(), and update_node_vb().
#define PBVH_ITER_ALL 0
Definition at line 164 of file BLI_pbvh.h.
Referenced by pbvh_vertex_iter_init(), sculpt_undo_store_coords(), and update_node_vb().
#define PBVH_ITER_UNIQUE 1
Definition at line 165 of file BLI_pbvh.h.
Referenced by calc_area_normal(), calc_area_normal_and_flatten_center(), calc_flatten_center(), do_clay_brush(), do_clay_strips_brush(), do_crease_brush(), do_draw_brush(), do_fill_brush(), do_flatten_brush(), do_grab_brush(), do_inflate_brush(), do_layer_brush(), do_mesh_smooth_brush(), do_nudge_brush(), do_pinch_brush(), do_rotate_brush(), do_scrape_brush(), do_snake_hook_brush(), do_thumb_brush(), pbvh_vertex_iter_init(), sculpt_combine_proxies(), sculpt_flush_stroke_deform(), and sculpt_restore_mesh().
Typedef Documentation
typedef void(* BLI_pbvh_HitCallback)(PBVHNode *node, void *data)
Definition at line 52 of file BLI_pbvh.h.
typedef void(* BLI_pbvh_HitOccludedCallback)(PBVHNode *node, void *data, float *tmin)
Definition at line 53 of file BLI_pbvh.h.
typedef int(* BLI_pbvh_SearchCallback)(PBVHNode *node, void *data)
Definition at line 50 of file BLI_pbvh.h.
typedef struct PBVH PBVH
Definition at line 40 of file BLI_pbvh.h.
typedef struct PBVHNode PBVHNode
Definition at line 41 of file BLI_pbvh.h.
typedef struct PBVHVertexIter PBVHVertexIter
Enumeration Type Documentation
enum PBVHNodeFlags
Enumerator:
PBVH_Leaf
PBVH_UpdateNormals
PBVH_UpdateBB
PBVH_UpdateOriginalBB
PBVH_UpdateDrawBuffers
PBVH_UpdateRedraw
PBVH_RebuildDrawBuffers
PBVH_FullyHidden
Definition at line 107 of file BLI_pbvh.h.
enum PBVHType
Enumerator:
PBVH_FACES
PBVH_GRIDS
Definition at line 95 of file BLI_pbvh.h.
Function Documentation
void BLI_pbvh_apply_vertCos (struct PBVH * pbvh, float(*) vertCos[3])
Definition at line 1718 of file pbvh.c.
References BLI_pbvh_node_mark_update(), BLI_pbvh_update(), MVert::co, copy_v3_v3(), PBVH::deformed, PBVH::faces, MVert::flag, ME_VERT_PBVH_UPDATE, MEM_dupallocN(), mesh_calc_normals_tessface(), PBVH::nodes, NULL, PBVH_UpdateBB, PBVH_UpdateOriginalBB, PBVH::totnode, PBVH::totprim, PBVH::totvert, and PBVH::verts.
Referenced by cdDM_getPBVH(), sculpt_undo_restore_coords(), and sculpt_update_mesh_elements().
void BLI_pbvh_build_grids (PBVH * bvh, struct DMGridData ** grids, struct DMGridAdjacency * gridadj, int totgrid, int gridsize, void ** gridfaces, struct DMFlagMat * flagmats, unsigned int ** grid_hidden)
Definition at line 645 of file pbvh.c.
References BB_expand(), BB_reset(), BBC_update_centroid(), co, PBVH::grid_flag_mats, PBVH::grid_hidden, PBVH::gridadj, PBVH::gridfaces, PBVH::grids, PBVH::gridsize, i, LEAF_LIMIT, PBVH::leaf_limit, MAX2, MEM_freeN(), MEM_mallocN(), NULL, pbvh_build(), PBVH_GRIDS, PBVH::totgrid, and PBVH::type.
Referenced by ccgDM_getPBVH().
void BLI_pbvh_build_mesh (PBVH * bvh, struct MFace * faces, struct MVert * verts, int totface, int totvert)
Definition at line 604 of file pbvh.c.
References BB_expand(), BB_reset(), BBC_update_centroid(), BLI_BITMAP_NEW, MVert::co, PBVH::faces, i, LEAF_LIMIT, PBVH::leaf_limit, MEM_freeN(), MEM_mallocN(), NULL, pbvh_build(), PBVH_FACES, PBVH::totvert, PBVH::type, MFace::v1, MFace::v4, PBVH::vert_bitmap, and PBVH::verts.
Referenced by ccgDM_getPBVH(), and cdDM_getPBVH().
void BLI_pbvh_draw (PBVH * bvh, float(*) planes[4], float(*) face_nors[3], int(*)(int, void *attribs) setMaterial)
Referenced by ccgDM_drawFacesSolid(), and cdDM_drawFacesSolid().
void BLI_pbvh_free (PBVH * bvh)
Definition at line 694 of file pbvh.c.
References PBVH::deformed, PBVHNode::draw_buffers, PBVHNode::face_vert_indices, PBVH::faces, PBVHNode::flag, GPU_free_buffers(), i, MEM_freeN(), PBVH::nodes, PBVH_Leaf, PBVH::prim_indices, PBVH::totnode, PBVHNode::vert_indices, and PBVH::verts.
Referenced by free_sculptsession(), multires_force_update(), and object_sculpt_modifiers_changed().
void BLI_pbvh_gather_proxies (PBVH * pbvh, PBVHNode *** nodes, int * totnode)
Definition at line 1806 of file pbvh.c.
References MEM_callocN(), MEM_freeN(), PBVH::nodes, NULL, and PBVH::totnode.
Referenced by sculpt_combine_proxies().
void BLI_pbvh_get_grid_updates (PBVH * bvh, int clear, void *** gridfaces, int * totface)
Definition at line 1251 of file pbvh.c.
References BLI_ghash_free(), BLI_ghash_insert(), BLI_ghash_lookup(), BLI_ghash_new(), BLI_ghash_size(), BLI_ghashIterator_free(), BLI_ghashIterator_getKey(), BLI_ghashIterator_isDone(), BLI_ghashIterator_new(), BLI_ghashIterator_step(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), PBVHNode::flag, PBVH::gridfaces, i, MEM_callocN(), NULL, pbvh_iter_begin(), pbvh_iter_end(), pbvh_iter_next(), PBVH_UpdateNormals, PBVHNode::prim_indices, and PBVHNode::totprim.
Referenced by ccgdm_pbvh_update(), and multires_stitch_grids().
float(* BLI_pbvh_get_vertCos (struct PBVH * pbvh))[3]
Definition at line 1698 of file pbvh.c.
References co, copy_v3_v3(), MEM_callocN(), and NULL.
Referenced by sculpt_update_keyblock().
unsigned int** BLI_pbvh_grid_hidden (const PBVH * bvh)
Definition at line 1310 of file pbvh.c.
References BLI_assert, PBVH::grid_hidden, PBVH_GRIDS, and PBVH::type.
Referenced by partialvis_update_grids(), and sculpt_undo_alloc_and_store_hidden().
void BLI_pbvh_grids_update (PBVH * bvh, struct DMGridData ** grids, struct DMGridAdjacency * gridadj, void ** gridfaces)
Definition at line 1691 of file pbvh.c.
References PBVH::gridadj, PBVH::gridfaces, and PBVH::grids.
Referenced by ccgDM_getPBVH().
int BLI_pbvh_isDeformed (struct PBVH * pbvh)
Definition at line 1755 of file pbvh.c.
References PBVH::deformed.
Referenced by sculpt_update_mesh_elements().
PBVH* BLI_pbvh_new (void)
Definition at line 687 of file pbvh.c.
References MEM_callocN().
Referenced by ccgDM_getPBVH(), and cdDM_getPBVH().
PBVHProxyNode* BLI_pbvh_node_add_proxy (PBVH * bvh, PBVHNode * node)
Definition at line 1761 of file pbvh.c.
References PBVHProxyNode::co, PBVH::grids, PBVH::gridsize, MEM_callocN(), MEM_mallocN(), MEM_reallocN(), PBVHNode::proxies, PBVHNode::proxy_count, PBVHNode::totprim, and PBVHNode::uniq_verts.
Referenced by do_clay_brush(), do_clay_strips_brush(), do_crease_brush(), do_draw_brush(), do_fill_brush(), do_flatten_brush(), do_grab_brush(), do_inflate_brush(), do_nudge_brush(), do_pinch_brush(), do_rotate_brush(), do_scrape_brush(), do_snake_hook_brush(), and do_thumb_brush().
void BLI_pbvh_node_draw (PBVHNode * node, void * data)
Definition at line 1589 of file pbvh.c.
References PBVHNode::draw_buffers, PBVHNode::flag, GPU_draw_buffers(), i, and PBVH_FullyHidden.
Referenced by BLI_pbvh_draw().
void BLI_pbvh_node_free_proxies (PBVHNode * node)
Definition at line 1788 of file pbvh.c.
References PBVHProxyNode::co, MEM_freeN(), p, PBVHNode::proxies, and PBVHNode::proxy_count.
Referenced by sculpt_combine_proxies().
void BLI_pbvh_node_fully_hidden_set (PBVHNode * node, int fully_hidden)
Definition at line 1328 of file pbvh.c.
References BLI_assert, PBVHNode::flag, PBVH_FullyHidden, and PBVH_Leaf.
Referenced by partialvis_update_grids(), partialvis_update_mesh(), and update_cb().
void BLI_pbvh_node_get_BB (PBVHNode * node, float bb_min[3], float bb_max[3])
Definition at line 1383 of file pbvh.c.
References BB::bmax, BB::bmin, copy_v3_v3(), and PBVHNode::vb.
Referenced by BLI_pbvh_node_planes_contain_AABB(), BLI_pbvh_node_planes_exclude_AABB(), ray_aabb_intersect(), and sculpt_search_sphere_cb().
void BLI_pbvh_node_get_grids (PBVH * bvh, PBVHNode * node, int ** grid_indices, int * totgrid, int * maxgrid, int * gridsize, struct DMGridData *** griddata, struct DMGridAdjacency ** gridadj)
Definition at line 1361 of file pbvh.c.
References PBVH::gridadj, PBVH::grids, PBVH::gridsize, NULL, PBVH_FACES, PBVH_GRIDS, PBVHNode::prim_indices, PBVH::totgrid, PBVHNode::totprim, and PBVH::type.
Referenced by do_multires_smooth_brush(), partialvis_update_grids(), pbvh_vertex_iter_init(), sculpt_undo_alloc_and_store_hidden(), sculpt_undo_alloc_node(), and sculpt_undo_push_node().
void BLI_pbvh_node_get_original_BB (PBVHNode * node, float bb_min[3], float bb_max[3])
Definition at line 1389 of file pbvh.c.
References BB::bmax, BB::bmin, copy_v3_v3(), and PBVHNode::orig_vb.
Referenced by ray_aabb_intersect(), and sculpt_search_sphere_cb().
void BLI_pbvh_node_get_proxies (PBVHNode * node, PBVHProxyNode ** proxies, int * proxy_count)
Definition at line 1395 of file pbvh.c.
References PBVHNode::proxies, and PBVHNode::proxy_count.
Referenced by sculpt_combine_proxies().
float BLI_pbvh_node_get_tmin (PBVHNode * node)
Definition at line 950 of file pbvh.c.
References PBVHNode::tmin.
Referenced by sculpt_raycast_cb().
void BLI_pbvh_node_get_verts (PBVH * bvh, PBVHNode * node, int ** vert_indices, struct MVert ** verts)
Definition at line 1338 of file pbvh.c.
References PBVHNode::vert_indices, and PBVH::verts.
Referenced by partialvis_update_mesh(), pbvh_vertex_iter_init(), sculpt_undo_push_node(), and sculpt_undo_store_hidden().
void BLI_pbvh_node_mark_rebuild_draw (PBVHNode * node)
Definition at line 1323 of file pbvh.c.
References PBVHNode::flag, PBVH_RebuildDrawBuffers, PBVH_UpdateDrawBuffers, and PBVH_UpdateRedraw.
Referenced by partialvis_update_grids(), partialvis_update_mesh(), and update_cb().
void BLI_pbvh_node_mark_update (PBVHNode * node)
Definition at line 1318 of file pbvh.c.
References PBVHNode::flag, PBVH_UpdateBB, PBVH_UpdateDrawBuffers, PBVH_UpdateNormals, PBVH_UpdateOriginalBB, and PBVH_UpdateRedraw.
Referenced by BLI_pbvh_apply_vertCos(), do_brush_action(), object_sculpt_modifiers_changed(), sculpt_restore_mesh(), and update_cb().
void BLI_pbvh_node_num_verts (PBVH * bvh, PBVHNode * node, int * uniquevert, int * totvert)
Definition at line 1344 of file pbvh.c.
References PBVHNode::face_verts, PBVH::gridsize, PBVH_FACES, PBVH_GRIDS, PBVHNode::totprim, PBVH::type, and PBVHNode::uniq_verts.
Referenced by partialvis_update_mesh(), pbvh_vertex_iter_init(), sculpt_undo_alloc_node(), sculpt_undo_push_node(), and sculpt_undo_store_hidden().
int BLI_pbvh_node_planes_contain_AABB (PBVHNode * node, void * data)
Definition at line 1652 of file pbvh.c.
References BLI_pbvh_node_get_BB(), ISECT_OUTSIDE, and test_planes_aabb().
Referenced by BLI_pbvh_draw(), and get_pbvh_nodes().
int BLI_pbvh_node_planes_exclude_AABB (PBVHNode * node, void * data)
Definition at line 1660 of file pbvh.c.
References BLI_pbvh_node_get_BB(), ISECT_INSIDE, and test_planes_aabb().
Referenced by get_pbvh_nodes().
int BLI_pbvh_node_raycast (PBVH * bvh, PBVHNode * node, float(*) origco[3], float ray_start[3], float ray_normal[3], float * dist)
Definition at line 1496 of file pbvh.c.
References co, MVert::co, PBVHNode::face_vert_indices, PBVH::faces, PBVHNode::flag, PBVH::grid_hidden, PBVH::grids, PBVH::gridsize, i, NULL, paint_is_face_hidden(), paint_is_grid_face_hidden(), PBVH_FACES, PBVH_FullyHidden, PBVH_GRIDS, PBVHNode::prim_indices, ray_face_intersection(), PBVHNode::totprim, PBVH::type, MFace::v1, MFace::v2, MFace::v3, MFace::v4, and PBVH::verts.
Referenced by sculpt_raycast_cb().
void BLI_pbvh_raycast (PBVH * bvh, BLI_pbvh_HitOccludedCallback cb, void * data, float ray_start[3], float ray_normal[3], int original)
Definition at line 1462 of file pbvh.c.
References BLI_pbvh_search_callback_occluded(), copy_v3_v3(), RaycastData::inv_dir, RaycastData::original, ray_aabb_intersect(), RaycastData::sign, and RaycastData::start.
Referenced by sculpt_stroke_get_location().
void BLI_pbvh_redraw_BB (PBVH * bvh, float bb_min[3], float bb_max[3])
Definition at line 1231 of file pbvh.c.
References BB_expand_with_bb(), BB_reset(), BB::bmax, BB::bmin, copy_v3_v3(), PBVHNode::flag, NULL, pbvh_iter_begin(), pbvh_iter_end(), pbvh_iter_next(), PBVH_UpdateRedraw, and PBVHNode::vb.
Referenced by sculpt_get_redraw_rect().
void BLI_pbvh_search_callback (PBVH * bvh, BLI_pbvh_SearchCallback scb, void * search_data, BLI_pbvh_HitCallback hcb, void * hit_data)
Definition at line 883 of file pbvh.c.
References PBVHNode::flag, pbvh_iter_begin(), pbvh_iter_end(), pbvh_iter_next(), and PBVH_Leaf.
Referenced by BLI_pbvh_draw(), and sculpt_undo_restore().
void BLI_pbvh_search_gather (PBVH * bvh, BLI_pbvh_SearchCallback scb, void * search_data, PBVHNode *** array, int * tot)
Definition at line 842 of file pbvh.c.
References MEM_callocN(), MEM_freeN(), NULL, pbvh_iter_begin(), pbvh_iter_end(), pbvh_iter_next(), and PBVH_Leaf.
Referenced by BLI_pbvh_draw(), BLI_pbvh_update(), do_brush_action(), get_pbvh_nodes(), object_sculpt_modifiers_changed(), sculpt_flush_stroke_deform(), and sculpt_restore_mesh().
PBVHType BLI_pbvh_type (const PBVH * bvh)
Definition at line 1305 of file pbvh.c.
References PBVH::type.
Referenced by hide_show_exec().
void BLI_pbvh_update (PBVH * bvh, int flags, float(*) face_nors[3])
Definition at line 1208 of file pbvh.c.
References BLI_pbvh_search_gather(), MEM_freeN(), PBVH::nodes, nodes, pbvh_flush_bb(), pbvh_update_BB_redraw(), pbvh_update_normals(), PBVH_UpdateBB, PBVH_UpdateNormals, PBVH_UpdateOriginalBB, PBVH_UpdateRedraw, SET_INT_IN_POINTER, and update_search_cb().
Referenced by BLI_pbvh_apply_vertCos(), cdDM_update_normals_from_pbvh(), sculpt_flush_update(), sculpt_get_redraw_planes(), sculpt_stroke_done(), and sculpt_undo_restore().
void pbvh_vertex_iter_init (PBVH * bvh, PBVHNode * node, PBVHVertexIter * vi, int mode)
Definition at line 1843 of file pbvh.c.
References BLI_pbvh_node_get_grids(), BLI_pbvh_node_get_verts(), BLI_pbvh_node_num_verts(), PBVHVertexIter::fno, PBVHVertexIter::gh, PBVHVertexIter::grid, PBVH::grid_hidden, PBVHVertexIter::grid_hidden, PBVHVertexIter::grid_indices, PBVHVertexIter::grids, PBVHVertexIter::gridsize, PBVHVertexIter::mvert, PBVHVertexIter::mverts, PBVHVertexIter::no, NULL, PBVH_ITER_ALL, PBVH_ITER_UNIQUE, PBVHVertexIter::totgrid, PBVHVertexIter::totvert, and PBVHVertexIter::vert_indices.