Blender: TNT Namespace Reference
TNT Namespace Reference
Classes
class Matrix
class Fortran_Sparse_Col_Matrix
class Fortran_Matrix
class Fortran_Sparse_Vector
class Index1D
class Region1D
class const_Region1D
class Region2D
class const_Region2D
class stopwatch
struct TNTException
class Transpose_View
class LowerTriangularView
class UnitLowerTriangularView
class UpperTriangularView
class UnitUpperTriangularView
class Vector
class Vector_Adaptor
class Array1D
class Array2D
class Array3D
class Fortran_Array1D
class Fortran_Array2D
class Fortran_Array3D
class i_refvec
class Sparse_Matrix_CompRow
class Stopwatch
Typedefs
typedef TNT_SUBSCRIPT_TYPE Subscript
Functions
template<class SPDMatrix , class SymmMatrix >
int Cholesky_upper_factorization (SPDMatrix &A, SymmMatrix &L)
template<class T >
std::ostream & operator<< (std::ostream &s, const Matrix< T > &A)
template<class T >
std::istream & operator>> (std::istream &s, Matrix< T > &A)
template<class T >
Matrix< T > operator+ (const Matrix< T > &A, const Matrix< T > &B)
template<class T >
Matrix< T > operator- (const Matrix< T > &A, const Matrix< T > &B)
template<class T >
Matrix< T > mult_element (const Matrix< T > &A, const Matrix< T > &B)
template<class T >
void transpose (const Matrix< T > &A, Matrix< T > &S)
template<class T >
void matmult (Matrix< T > &C, const Matrix< T > &A, const Matrix< T > &B)
template<class T >
void matmult (Vector< T > &y, const Matrix< T > &A, const Vector< T > &x)
template<class T >
void matmultdiag (Matrix< T > &C, const Matrix< T > &A, const Vector< T > &diag)
template<class T >
void matmultdiag (Matrix< T > &C, const Vector< T > &diag, const Matrix< T > &A)
template<class T >
ostream & operator<< (ostream &s, const Fortran_Sparse_Col_Matrix< T > &A)
template<class T >
std::ostream & operator<< (std::ostream &s, const Fortran_Matrix< T > &A)
template<class T >
std::istream & operator>> (std::istream &s, Fortran_Matrix< T > &A)
template<class T >
Fortran_Matrix< T > operator+ (const Fortran_Matrix< T > &A, const Fortran_Matrix< T > &B)
template<class T >
Fortran_Matrix< T > operator- (const Fortran_Matrix< T > &A, const Fortran_Matrix< T > &B)
template<class T >
Fortran_Matrix< T > mult_element (const Fortran_Matrix< T > &A, const Fortran_Matrix< T > &B)
template<class T >
Fortran_Matrix< T > transpose (const Fortran_Matrix< T > &A)
template<class T >
Fortran_Matrix< T > matmult (const Fortran_Matrix< T > &A, const Fortran_Matrix< T > &B)
template<class T >
Fortran_Matrix< T > operator* (const Fortran_Matrix< T > &A, const Fortran_Matrix< T > &B)
template<class T >
int matmult (Fortran_Matrix< T > &C, const Fortran_Matrix< T > &A, const Fortran_Matrix< T > &B)
template<class T >
Vector< T > matmult (const Fortran_Matrix< T > &A, const Vector< T > &x)
template<class T >
Vector< T > operator* (const Fortran_Matrix< T > &A, const Vector< T > &x)
template<class T >
Fortran_Matrix< T > operator* (const Fortran_Matrix< T > &A, const T &x)
template<class T >
ostream & operator<< (ostream &s, const Fortran_Sparse_Vector< T > &A)
template<class T >
istream & operator>> (istream &s, Fortran_Sparse_Vector< T > &A)
Index1D operator+ (const Index1D &D, Subscript i)
Index1D operator+ (Subscript i, const Index1D &D)
Index1D operator- (Index1D &D, Subscript i)
Index1D operator- (Subscript i, Index1D &D)
template<class MaTRiX , class VecToRSubscript >
int LU_factor (MaTRiX &A, VecToRSubscript &indx)
template<class MaTRiX , class VecToR , class VecToRSubscripts >
int LU_solve (const MaTRiX &A, const VecToRSubscripts &indx, VecToR &b)
template<class MaTRiX , class Vector >
int QR_factor (MaTRiX &A, Vector &C, Vector &D)
template<class MaTRiX , class Vector >
int R_solve (const MaTRiX &A, Vector &D, Vector &b)
template<class MaTRiX , class Vector >
int QR_solve (const MaTRiX &A, const Vector &c, Vector &d, Vector &b)
template<class Array1D >
std::ostream & operator<< (std::ostream &s, Region1D< Array1D > &A)
template<class Array1D >
std::ostream & operator<< (std::ostream &s, const_Region1D< Array1D > &A)
template<class Array2D >
std::ostream & operator<< (std::ostream &s, const const_Region2D< Array2D > &A)
template<class Array2D >
std::ostream & operator<< (std::ostream &s, const Region2D< Array2D > &A)
double seconds (void)
template<class MaTRiX , class VecToR >
void SVD (MaTRiX &A, MaTRiX &U, VecToR &s, MaTRiX &V, VecToR &work1, VecToR &work2, int maxiter=SVD_MAX_ITER)
double abs (double t)
double min (double a, double b)
double max (double a, double b)
float abs (float t)
float min (float a, float b)
int min (int a, int b)
int max (int a, int b)
float max (float a, float b)
double sign (double a)
double sign (double a, double b)
float sign (float a, float b)
float sign (float a)
float pythag (float a, float b)
double pythag (double a, double b)
template<class Matrix >
Transpose_View< Matrix > Transpose_view (const Matrix &A)
template<class Matrix , class T >
Vector< T > matmult (const Transpose_View< Matrix > &A, const Vector< T > &B)
template<class Matrix , class T >
Vector< T > operator* (const Transpose_View< Matrix > &A, const Vector< T > &B)
template<class Matrix >
std::ostream & operator<< (std::ostream &s, const Transpose_View< Matrix > &A)
template<class MaTRiX , class VecToR >
VecToR matmult (LowerTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX , class VecToR >
VecToR operator* (LowerTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX >
LowerTriangularView< MaTRiX > Lower_triangular_view (MaTRiX &A)
template<class MaTRiX >
UnitLowerTriangularView< MaTRiX > Unit_lower_triangular_view (MaTRiX &A)
template<class MaTRiX , class VecToR >
VecToR matmult (UnitLowerTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX , class VecToR >
VecToR operator* (UnitLowerTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX >
std::ostream & operator<< (std::ostream &s, const LowerTriangularView< MaTRiX > &A)
template<class MaTRiX >
std::ostream & operator<< (std::ostream &s, const UnitLowerTriangularView< MaTRiX > &A)
template<class MaTRiX , class VecToR >
VecToR matmult (UpperTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX , class VecToR >
VecToR operator* (UpperTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX >
UpperTriangularView< MaTRiX > Upper_triangular_view (MaTRiX &A)
template<class MaTRiX >
UnitUpperTriangularView< MaTRiX > Unit_upper_triangular_view (MaTRiX &A)
template<class MaTRiX , class VecToR >
VecToR matmult (UnitUpperTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX , class VecToR >
VecToR operator* (UnitUpperTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX >
std::ostream & operator<< (std::ostream &s, UpperTriangularView< MaTRiX > &A)
template<class MaTRiX >
std::ostream & operator<< (std::ostream &s, UnitUpperTriangularView< MaTRiX > &A)
template<class MaTriX , class VecToR >
VecToR Lower_triangular_solve (MaTriX &A, VecToR &b)
template<class MaTriX , class VecToR >
VecToR Unit_lower_triangular_solve (MaTriX &A, VecToR &b)
template<class MaTriX , class VecToR >
VecToR linear_solve (LowerTriangularView< MaTriX > &A, VecToR &b)
template<class MaTriX , class VecToR >
VecToR linear_solve (UnitLowerTriangularView< MaTriX > &A, VecToR &b)
template<class MaTriX , class VecToR >
VecToR Upper_triangular_solve (MaTriX &A, VecToR &b)
template<class MaTriX , class VecToR >
VecToR Unit_upper_triangular_solve (MaTriX &A, VecToR &b)
template<class MaTriX , class VecToR >
VecToR linear_solve (UpperTriangularView< MaTriX > &A, VecToR &b)
template<class MaTriX , class VecToR >
VecToR linear_solve (UnitUpperTriangularView< MaTriX > &A, VecToR &b)
template<class T >
std::ostream & operator<< (std::ostream &s, const Vector< T > &A)
template<class T >
std::istream & operator>> (std::istream &s, Vector< T > &A)
template<class T >
Vector< T > operator+ (const Vector< T > &A, const Vector< T > &B)
template<class T >
Vector< T > operator- (const Vector< T > &A, const Vector< T > &B)
template<class T >
Vector< T > operator* (const Vector< T > &A, const Vector< T > &B)
template<class T >
Vector< T > operator* (const Vector< T > &A, const T &B)
template<class T >
T dot_prod (const Vector< T > &A, const Vector< T > &B)
template<class T >
void vectoradd (Vector< T > &A, const Vector< T > &B)
template<class T >
void vectoradd (Vector< T > &C, const Vector< T > &A, const Vector< T > &B)
template<class T >
void vectorsub (Vector< T > &A, const Vector< T > &B)
template<class T >
void vectorsub (Vector< T > &C, const Vector< T > &A, const Vector< T > &B)
template<class T >
void vectorscale (Vector< T > &C, const Vector< T > &A, const T &B)
template<class T >
void vectorscale (Vector< T > &A, const T &B)
template<class BBVec >
std::ostream & operator<< (std::ostream &s, const Vector_Adaptor< BBVec > &A)
template<class BBVec >
std::istream & operator>> (std::istream &s, Vector_Adaptor< BBVec > &A)
template<class T >
std::ostream & operator<< (std::ostream &s, const Array1D< T > &A)
template<class T >
std::istream & operator>> (std::istream &s, Array1D< T > &A)
template<class T >
Array1D< T > operator+ (const Array1D< T > &A, const Array1D< T > &B)
template<class T >
Array1D< T > operator- (const Array1D< T > &A, const Array1D< T > &B)
template<class T >
Array1D< T > operator* (const Array1D< T > &A, const Array1D< T > &B)
template<class T >
Array1D< T > operator/ (const Array1D< T > &A, const Array1D< T > &B)
template<class T >
Array1D< T > & operator+= (Array1D< T > &A, const Array1D< T > &B)
template<class T >
Array1D< T > & operator-= (Array1D< T > &A, const Array1D< T > &B)
template<class T >
Array1D< T > & operator*= (Array1D< T > &A, const Array1D< T > &B)
template<class T >
Array1D< T > & operator/= (Array1D< T > &A, const Array1D< T > &B)
template<class T >
std::ostream & operator<< (std::ostream &s, const Array2D< T > &A)
template<class T >
std::istream & operator>> (std::istream &s, Array2D< T > &A)
template<class T >
Array2D< T > operator+ (const Array2D< T > &A, const Array2D< T > &B)
template<class T >
Array2D< T > operator- (const Array2D< T > &A, const Array2D< T > &B)
template<class T >
Array2D< T > operator* (const Array2D< T > &A, const Array2D< T > &B)
template<class T >
Array2D< T > operator/ (const Array2D< T > &A, const Array2D< T > &B)
template<class T >
Array2D< T > & operator+= (Array2D< T > &A, const Array2D< T > &B)
template<class T >
Array2D< T > & operator-= (Array2D< T > &A, const Array2D< T > &B)
template<class T >
Array2D< T > & operator*= (Array2D< T > &A, const Array2D< T > &B)
template<class T >
Array2D< T > & operator/= (Array2D< T > &A, const Array2D< T > &B)
template<class T >
Array2D< T > matmult (const Array2D< T > &A, const Array2D< T > &B)
template<class T >
std::ostream & operator<< (std::ostream &s, const Array3D< T > &A)
template<class T >
std::istream & operator>> (std::istream &s, Array3D< T > &A)
template<class T >
Array3D< T > operator+ (const Array3D< T > &A, const Array3D< T > &B)
template<class T >
Array3D< T > operator- (const Array3D< T > &A, const Array3D< T > &B)
template<class T >
Array3D< T > operator* (const Array3D< T > &A, const Array3D< T > &B)
template<class T >
Array3D< T > operator/ (const Array3D< T > &A, const Array3D< T > &B)
template<class T >
Array3D< T > & operator+= (Array3D< T > &A, const Array3D< T > &B)
template<class T >
Array3D< T > & operator-= (Array3D< T > &A, const Array3D< T > &B)
template<class T >
Array3D< T > & operator*= (Array3D< T > &A, const Array3D< T > &B)
template<class T >
Array3D< T > & operator/= (Array3D< T > &A, const Array3D< T > &B)
template<class T >
Matrix< T > transpose (const Matrix< T > &A)
template<class T >
Matrix< T > matmult (const Matrix< T > &A, const Matrix< T > &B)
template<class T >
Matrix< T > operator* (const Matrix< T > &A, const Matrix< T > &B)
template<class T >
Vector< T > matmult (const Matrix< T > &A, const Vector< T > &x)
template<class T >
Vector< T > operator* (const Matrix< T > &A, const Vector< T > &x)
template<class T >
std::ostream & operator<< (std::ostream &s, const Fortran_Array1D< T > &A)
template<class T >
std::istream & operator>> (std::istream &s, Fortran_Array1D< T > &A)
template<class T >
Fortran_Array1D< T > operator+ (const Fortran_Array1D< T > &A, const Fortran_Array1D< T > &B)
template<class T >
Fortran_Array1D< T > operator- (const Fortran_Array1D< T > &A, const Fortran_Array1D< T > &B)
template<class T >
Fortran_Array1D< T > operator* (const Fortran_Array1D< T > &A, const Fortran_Array1D< T > &B)
template<class T >
Fortran_Array1D< T > operator/ (const Fortran_Array1D< T > &A, const Fortran_Array1D< T > &B)
template<class T >
Fortran_Array1D< T > & operator+= (Fortran_Array1D< T > &A, const Fortran_Array1D< T > &B)
template<class T >
Fortran_Array1D< T > & operator-= (Fortran_Array1D< T > &A, const Fortran_Array1D< T > &B)
template<class T >
Fortran_Array1D< T > & operator*= (Fortran_Array1D< T > &A, const Fortran_Array1D< T > &B)
template<class T >
Fortran_Array1D< T > & operator/= (Fortran_Array1D< T > &A, const Fortran_Array1D< T > &B)
template<class T >
std::ostream & operator<< (std::ostream &s, const Fortran_Array2D< T > &A)
template<class T >
std::istream & operator>> (std::istream &s, Fortran_Array2D< T > &A)
template<class T >
Fortran_Array2D< T > operator+ (const Fortran_Array2D< T > &A, const Fortran_Array2D< T > &B)
template<class T >
Fortran_Array2D< T > operator- (const Fortran_Array2D< T > &A, const Fortran_Array2D< T > &B)
template<class T >
Fortran_Array2D< T > operator* (const Fortran_Array2D< T > &A, const Fortran_Array2D< T > &B)
template<class T >
Fortran_Array2D< T > operator/ (const Fortran_Array2D< T > &A, const Fortran_Array2D< T > &B)
template<class T >
Fortran_Array2D< T > & operator+= (Fortran_Array2D< T > &A, const Fortran_Array2D< T > &B)
template<class T >
Fortran_Array2D< T > & operator-= (Fortran_Array2D< T > &A, const Fortran_Array2D< T > &B)
template<class T >
Fortran_Array2D< T > & operator*= (Fortran_Array2D< T > &A, const Fortran_Array2D< T > &B)
template<class T >
Fortran_Array2D< T > & operator/= (Fortran_Array2D< T > &A, const Fortran_Array2D< T > &B)
template<class T >
std::ostream & operator<< (std::ostream &s, const Fortran_Array3D< T > &A)
template<class T >
std::istream & operator>> (std::istream &s, Fortran_Array3D< T > &A)
template<class T >
Fortran_Array3D< T > operator+ (const Fortran_Array3D< T > &A, const Fortran_Array3D< T > &B)
template<class T >
Fortran_Array3D< T > operator- (const Fortran_Array3D< T > &A, const Fortran_Array3D< T > &B)
template<class T >
Fortran_Array3D< T > operator* (const Fortran_Array3D< T > &A, const Fortran_Array3D< T > &B)
template<class T >
Fortran_Array3D< T > operator/ (const Fortran_Array3D< T > &A, const Fortran_Array3D< T > &B)
template<class T >
Fortran_Array3D< T > & operator+= (Fortran_Array3D< T > &A, const Fortran_Array3D< T > &B)
template<class T >
Fortran_Array3D< T > & operator-= (Fortran_Array3D< T > &A, const Fortran_Array3D< T > &B)
template<class T >
Fortran_Array3D< T > & operator*= (Fortran_Array3D< T > &A, const Fortran_Array3D< T > &B)
template<class T >
Fortran_Array3D< T > & operator/= (Fortran_Array3D< T > &A, const Fortran_Array3D< T > &B)
template<class Real >
Real hypot (const Real &a, const Real &b)
Typedef Documentation
typedef TNT_SUBSCRIPT_TYPE TNT::Subscript
Definition at line 51 of file subscript.h.
Function Documentation
double TNT::abs (double t) [inline]
Definition at line 49 of file tntmath.h.
Referenced by JAMA::LU< Real >::LU(), pythag(), sign(), and SVD().
float TNT::abs (float t) [inline]
Definition at line 64 of file tntmath.h.
template<class SPDMatrix , class SymmMatrix > int TNT::Cholesky_upper_factorization (SPDMatrix & A, SymmMatrix & L)
Definition at line 43 of file cholesky.h.
References assert, dot(), i, L, M, N, and sqrt().
template<class T > T TNT::dot_prod (const Vector< T > & A, const Vector< T > & B)
Definition at line 387 of file vec.h.
References assert, TNT::Vector< T >::dim(), i, N, sum(), and T.
Referenced by LOD_NdQuadric::Evaluate().
template<class Real > Real TNT::hypot (const Real & a, const Real & b)
Returns:
hypotenuse of real (non-complex) scalars a and b by avoiding underflow/overflow using (a * sqrt(1 + (b/a) * (b/a))), rather than sqrt(a*a + b*b).
Definition at line 23 of file tnt_math_utils.h.
References fabs(), and sqrt().
Referenced by SVD().
template<class MaTriX , class VecToR > VecToR TNT::linear_solve (LowerTriangularView< MaTriX > & A, VecToR & b)
Definition at line 97 of file trisolve.h.
References Lower_triangular_solve().
template<class MaTriX , class VecToR > VecToR TNT::linear_solve (UnitLowerTriangularView< MaTriX > & A, VecToR & b)
Definition at line 104 of file trisolve.h.
References Unit_lower_triangular_solve().
template<class MaTriX , class VecToR > VecToR TNT::linear_solve (UpperTriangularView< MaTriX > & A, VecToR & b)
Definition at line 171 of file trisolve.h.
References Upper_triangular_solve().
template<class MaTriX , class VecToR > VecToR TNT::linear_solve (UnitUpperTriangularView< MaTriX > & A, VecToR & b)
Definition at line 178 of file trisolve.h.
References Unit_upper_triangular_solve().
template<class MaTriX , class VecToR > VecToR TNT::Lower_triangular_solve (MaTriX & A, VecToR & b)
Definition at line 42 of file trisolve.h.
References assert, i, and N.
Referenced by linear_solve().
template<class MaTRiX > LowerTriangularView<MaTRiX> TNT::Lower_triangular_view (MaTRiX & A)
Definition at line 241 of file triang.h.
template<class MaTRiX , class VecToRSubscript > int TNT::LU_factor (MaTRiX & A, VecToRSubscript & indx)
Definition at line 88 of file lu.h.
References assert, fabs(), i, M, and N.
Referenced by LOD_NdQuadric::Optimize().
template<class MaTRiX , class VecToR , class VecToRSubscripts > int TNT::LU_solve (const MaTRiX & A, const VecToRSubscripts & indx, VecToR & b)
Definition at line 173 of file lu.h.
References assert, i, and sum().
Referenced by LOD_NdQuadric::Optimize().
template<class T > void TNT::matmult (Vector< T > & y, const Matrix< T > & A, const Vector< T > & x)
Definition at line 534 of file cmat.h.
References assert, TNT::Vector< T >::dim(), i, M, N, TNT::Matrix< T >::num_cols(), TNT::Matrix< T >::num_rows(), sum(), and T.
template<class MaTRiX , class VecToR > VecToR TNT::matmult (UnitLowerTriangularView< MaTRiX > & A, VecToR & x)
Definition at line 256 of file triang.h.
References assert, i, TNT::UnitLowerTriangularView< MaTRiX >::lbound(), M, N, TNT::UnitLowerTriangularView< MaTRiX >::num_cols(), TNT::UnitLowerTriangularView< MaTRiX >::num_rows(), and sum().
template<class T > Matrix<T> TNT::matmult (const Matrix< T > & A, const Matrix< T > & B) [inline]
Definition at line 475 of file tnt_cmat.h.
References assert, i, K, M, N, sum(), and T.
template<class T > Vector<T> TNT::matmult (const Matrix< T > & A, const Vector< T > & x)
Definition at line 548 of file tnt_cmat.h.
References assert, TNT::Vector< T >::dim(), i, M, N, sum(), and T.
template<class MaTRiX , class VecToR > VecToR TNT::matmult (UpperTriangularView< MaTRiX > & A, VecToR & x)
Definition at line 424 of file triang.h.
References assert, i, TNT::UpperTriangularView< MaTRiX >::lbound(), M, N, TNT::UpperTriangularView< MaTRiX >::num_cols(), TNT::UpperTriangularView< MaTRiX >::num_rows(), and sum().
template<class MaTRiX , class VecToR > VecToR TNT::matmult (UnitUpperTriangularView< MaTRiX > & A, VecToR & x)
Definition at line 554 of file triang.h.
References assert, i, TNT::UnitUpperTriangularView< MaTRiX >::lbound(), M, N, TNT::UnitUpperTriangularView< MaTRiX >::num_cols(), TNT::UnitUpperTriangularView< MaTRiX >::num_rows(), and sum().
template<class T > int TNT::matmult (Matrix< T > & C, const Matrix< T > & A, const Matrix< T > & B) [inline]
Definition at line 499 of file cmat.h.
References assert, i, K, M, N, TNT::Matrix< T >::newsize(), TNT::Matrix< T >::num_cols(), TNT::Matrix< T >::num_rows(), sum(), and T.
Referenced by IK_QJacobian::ComputeNullProjection(), LOD_NdQuadric::Evaluate(), operator*(), and IK_QJacobian::Restrict().
template<class T > Fortran_Matrix<T> TNT::matmult (const Fortran_Matrix< T > & A, const Fortran_Matrix< T > & B) [inline]
Definition at line 438 of file fmat.h.
References assert, B, i, K, M, N, TNT::Fortran_Matrix< T >::num_cols(), TNT::Fortran_Matrix< T >::num_rows(), sum(), and T.
template<class T > int TNT::matmult (Fortran_Matrix< T > & C, const Fortran_Matrix< T > & A, const Fortran_Matrix< T > & B) [inline]
Definition at line 474 of file fmat.h.
References assert, B, C, i, K, M, N, TNT::Fortran_Matrix< T >::newsize(), TNT::Fortran_Matrix< T >::num_cols(), TNT::Fortran_Matrix< T >::num_rows(), sum(), and T.
template<class T > Vector<T> TNT::matmult (const Fortran_Matrix< T > & A, const Vector< T > & x)
Definition at line 516 of file fmat.h.
References assert, TNT::Vector< T >::dim(), i, M, N, TNT::Fortran_Matrix< T >::num_cols(), TNT::Fortran_Matrix< T >::num_rows(), sum(), and T.
template<class T > Array2D<T> TNT::matmult (const Array2D< T > & A, const Array2D< T > & B)
Matrix Multiply: compute C = A*B, where C[i][j] is the dot-product of row i of A and column j of B.
Parameters:
A an (m x n) array
B an (n x k) array
Returns:
the (m x k) array A*B, or a null array (0x0) if the matrices are non-conformant (i.e. the number of columns of A are different than the number of rows of B.)
Definition at line 262 of file tnt_array2d_utils.h.
References C, TNT::Array2D< T >::dim1(), TNT::Array2D< T >::dim2(), i, K, M, N, sum(), and T.
template<class Matrix , class T > Vector<T> TNT::matmult (const Transpose_View< Matrix > & A, const Vector< T > & B)
Definition at line 105 of file transv.h.
References assert, B, TNT::Vector< T >::dim(), i, M, N, TNT::Transpose_View< Array2D >::num_cols(), TNT::Transpose_View< Array2D >::num_rows(), and T.
template<class MaTRiX , class VecToR > VecToR TNT::matmult (LowerTriangularView< MaTRiX > & A, VecToR & x)
Definition at line 126 of file triang.h.
References assert, i, TNT::LowerTriangularView< MaTRiX >::lbound(), M, N, TNT::LowerTriangularView< MaTRiX >::num_cols(), TNT::LowerTriangularView< MaTRiX >::num_rows(), and sum().
template<class T > void TNT::matmultdiag (Matrix< T > & C, const Matrix< T > & A, const Vector< T > & diag) [inline]
Definition at line 559 of file cmat.h.
References assert, TNT::Vector< T >::dim(), i, K, M, TNT::Matrix< T >::newsize(), TNT::Matrix< T >::num_cols(), TNT::Matrix< T >::num_rows(), and T.
template<class T > void TNT::matmultdiag (Matrix< T > & C, const Vector< T > & diag, const Matrix< T > & A) [inline]
Definition at line 586 of file cmat.h.
References assert, TNT::Vector< T >::dim(), i, K, M, TNT::Matrix< T >::newsize(), TNT::Matrix< T >::num_cols(), TNT::Matrix< T >::num_rows(), and T.
double TNT::max (double a, double b) [inline]
Definition at line 59 of file tntmath.h.
Referenced by SVD().
int TNT::max (int a, int b) [inline]
Definition at line 79 of file tntmath.h.
float TNT::max (float a, float b) [inline]
Definition at line 84 of file tntmath.h.
double TNT::min (double a, double b) [inline]
Definition at line 54 of file tntmath.h.
Referenced by JAMA::LU< Real >::LU(), and SVD().
float TNT::min (float a, float b) [inline]
Definition at line 69 of file tntmath.h.
int TNT::min (int a, int b) [inline]
Definition at line 74 of file tntmath.h.
template<class T > Fortran_Matrix<T> TNT::mult_element (const Fortran_Matrix< T > & A, const Fortran_Matrix< T > & B)
Definition at line 399 of file fmat.h.
References assert, B, i, M, N, TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
template<class T > Matrix< T > TNT::mult_element (const Matrix< T > & A, const Matrix< T > & B)
Definition at line 461 of file cmat.h.
References assert, i, M, N, TNT::Matrix< T >::num_cols(), and TNT::Matrix< T >::num_rows().
template<class MaTRiX , class VecToR > VecToR TNT::operator* (UnitLowerTriangularView< MaTRiX > & A, VecToR & x) [inline]
Definition at line 282 of file triang.h.
References matmult().
template<class T > Matrix<T> TNT::operator* (const Matrix< T > & A, const Matrix< T > & B) [inline]
Definition at line 504 of file tnt_cmat.h.
References matmult().
template<class T > Vector<T> TNT::operator* (const Matrix< T > & A, const Vector< T > & x) [inline]
Definition at line 575 of file tnt_cmat.h.
References matmult().
template<class MaTRiX , class VecToR > VecToR TNT::operator* (UpperTriangularView< MaTRiX > & A, VecToR & x) [inline]
Definition at line 450 of file triang.h.
References matmult().
template<class T > Fortran_Array1D<T> TNT::operator* (const Fortran_Array1D< T > & A, const Fortran_Array1D< T > & B)
Definition at line 126 of file tnt_fortran_array1d_utils.h.
References B, C, TNT::Fortran_Array1D< T >::dim1(), and i.
template<class MaTRiX , class VecToR > VecToR TNT::operator* (UnitUpperTriangularView< MaTRiX > & A, VecToR & x) [inline]
Definition at line 580 of file triang.h.
References matmult().
template<class T > Fortran_Array2D<T> TNT::operator* (const Fortran_Array2D< T > & A, const Fortran_Array2D< T > & B)
Definition at line 123 of file tnt_fortran_array2d_utils.h.
References B, C, TNT::Fortran_Array2D< T >::dim1(), TNT::Fortran_Array2D< T >::dim2(), and i.
template<class T > Fortran_Array3D<T> TNT::operator* (const Fortran_Array3D< T > & A, const Fortran_Array3D< T > & B)
Definition at line 127 of file tnt_fortran_array3d_utils.h.
References B, C, TNT::Fortran_Array3D< T >::dim1(), TNT::Fortran_Array3D< T >::dim2(), TNT::Fortran_Array3D< T >::dim3(), i, and p.
template<class T > Fortran_Matrix<T> TNT::operator* (const Fortran_Matrix< T > & A, const Fortran_Matrix< T > & B) [inline]
Definition at line 467 of file fmat.h.
References matmult().
template<class T > Vector< T > TNT::operator* (const Vector< T > & A, const Vector< T > & B)
Definition at line 354 of file vec.h.
References assert, TNT::Vector< T >::dim(), i, and N.
template<class T > Vector<T> TNT::operator* (const Vector< T > & A, const T & B)
Definition at line 371 of file vec.h.
References TNT::Vector< T >::dim(), i, and N.
template<class T > Vector<T> TNT::operator* (const Fortran_Matrix< T > & A, const Vector< T > & x) [inline]
Definition at line 542 of file fmat.h.
References matmult().
template<class T > Fortran_Matrix<T> TNT::operator* (const Fortran_Matrix< T > & A, const T & x) [inline]
Definition at line 548 of file fmat.h.
References TNT::Fortran_Matrix< T >::begin(), TNT::Fortran_Matrix< T >::end(), M, N, TNT::Fortran_Matrix< T >::num_cols(), TNT::Fortran_Matrix< T >::num_rows(), T, and tend().
template<class T > Array1D<T> TNT::operator* (const Array1D< T > & A, const Array1D< T > & B)
Definition at line 110 of file tnt_array1d_utils.h.
References C, TNT::Array1D< T >::dim1(), and i.
template<class T > Array2D<T> TNT::operator* (const Array2D< T > & A, const Array2D< T > & B)
Definition at line 122 of file tnt_array2d_utils.h.
References C, TNT::Array2D< T >::dim1(), TNT::Array2D< T >::dim2(), and i.
template<class Matrix , class T > Vector<T> TNT::operator* (const Transpose_View< Matrix > & A, const Vector< T > & B) [inline]
Definition at line 131 of file transv.h.
References matmult().
template<class MaTRiX , class VecToR > VecToR TNT::operator* (LowerTriangularView< MaTRiX > & A, VecToR & x) [inline]
Definition at line 152 of file triang.h.
References matmult().
template<class T > Array3D<T> TNT::operator* (const Array3D< T > & A, const Array3D< T > & B)
Definition at line 112 of file tnt_array3d_utils.h.
References C, TNT::Array3D< T >::dim1(), TNT::Array3D< T >::dim2(), TNT::Array3D< T >::dim3(), i, and p.
template<class T > Array3D<T>& TNT::operator*= (Array3D< T > & A, const Array3D< T > & B)
Definition at line 197 of file tnt_array3d_utils.h.
References TNT::Array3D< T >::dim1(), TNT::Array3D< T >::dim2(), TNT::Array3D< T >::dim3(), i, and p.
template<class T > Fortran_Array1D<T>& TNT::operator*= (Fortran_Array1D< T > & A, const Fortran_Array1D< T > & B)
Definition at line 210 of file tnt_fortran_array1d_utils.h.
References B, TNT::Fortran_Array1D< T >::dim1(), and i.
template<class T > Fortran_Array2D<T>& TNT::operator*= (Fortran_Array2D< T > & A, const Fortran_Array2D< T > & B)
Definition at line 204 of file tnt_fortran_array2d_utils.h.
References B, TNT::Fortran_Array2D< T >::dim1(), TNT::Fortran_Array2D< T >::dim2(), and i.
template<class T > Fortran_Array3D<T>& TNT::operator*= (Fortran_Array3D< T > & A, const Fortran_Array3D< T > & B)
Definition at line 213 of file tnt_fortran_array3d_utils.h.
References B, TNT::Fortran_Array3D< T >::dim1(), TNT::Fortran_Array3D< T >::dim2(), TNT::Fortran_Array3D< T >::dim3(), i, and p.
template<class T > Array1D<T>& TNT::operator*= (Array1D< T > & A, const Array1D< T > & B)
Definition at line 194 of file tnt_array1d_utils.h.
References TNT::Array1D< T >::dim1(), and i.
template<class T > Array2D<T>& TNT::operator*= (Array2D< T > & A, const Array2D< T > & B)
Definition at line 211 of file tnt_array2d_utils.h.
References TNT::Array2D< T >::dim1(), TNT::Array2D< T >::dim2(), and i.
template<class T > Fortran_Array1D<T> TNT::operator+ (const Fortran_Array1D< T > & A, const Fortran_Array1D< T > & B)
Definition at line 83 of file tnt_fortran_array1d_utils.h.
References B, C, TNT::Fortran_Array1D< T >::dim1(), and i.
template<class T > Fortran_Array2D<T> TNT::operator+ (const Fortran_Array2D< T > & A, const Fortran_Array2D< T > & B)
Definition at line 78 of file tnt_fortran_array2d_utils.h.
References B, C, TNT::Fortran_Array2D< T >::dim1(), TNT::Fortran_Array2D< T >::dim2(), and i.
template<class T > Matrix< T > TNT::operator+ (const Matrix< T > & A, const Matrix< T > & B)
Definition at line 421 of file cmat.h.
References assert, i, M, N, TNT::Matrix< T >::num_cols(), and TNT::Matrix< T >::num_rows().
template<class T > Fortran_Array3D<T> TNT::operator+ (const Fortran_Array3D< T > & A, const Fortran_Array3D< T > & B)
Definition at line 79 of file tnt_fortran_array3d_utils.h.
References B, C, TNT::Fortran_Array3D< T >::dim1(), TNT::Fortran_Array3D< T >::dim2(), TNT::Fortran_Array3D< T >::dim3(), i, and p.
template<class T > Vector< T > TNT::operator+ (const Vector< T > & A, const Vector< T > & B)
Definition at line 320 of file vec.h.
References assert, TNT::Vector< T >::dim(), i, and N.
template<class T > Array1D<T> TNT::operator+ (const Array1D< T > & A, const Array1D< T > & B)
Definition at line 67 of file tnt_array1d_utils.h.
References C, TNT::Array1D< T >::dim1(), and i.
Index1D TNT::operator+ (const Index1D & D, Subscript i) [inline]
Definition at line 62 of file index.h.
References TNT::Index1D::lbound(), and TNT::Index1D::ubound().
template<class T > Array2D<T> TNT::operator+ (const Array2D< T > & A, const Array2D< T > & B)
Definition at line 77 of file tnt_array2d_utils.h.
References C, TNT::Array2D< T >::dim1(), TNT::Array2D< T >::dim2(), and i.
Index1D TNT::operator+ (Subscript i, const Index1D & D) [inline]
Definition at line 67 of file index.h.
References TNT::Index1D::lbound(), and TNT::Index1D::ubound().
template<class T > Fortran_Matrix<T> TNT::operator+ (const Fortran_Matrix< T > & A, const Fortran_Matrix< T > & B)
Definition at line 355 of file fmat.h.
References assert, B, i, M, N, TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
template<class T > Array3D<T> TNT::operator+ (const Array3D< T > & A, const Array3D< T > & B)
Definition at line 62 of file tnt_array3d_utils.h.
References C, TNT::Array3D< T >::dim1(), TNT::Array3D< T >::dim2(), TNT::Array3D< T >::dim3(), i, and p.
template<class T > Fortran_Array1D<T>& TNT::operator+= (Fortran_Array1D< T > & A, const Fortran_Array1D< T > & B)
Definition at line 175 of file tnt_fortran_array1d_utils.h.
References B, TNT::Fortran_Array1D< T >::dim1(), and i.
template<class T > Fortran_Array2D<T>& TNT::operator+= (Fortran_Array2D< T > & A, const Fortran_Array2D< T > & B)
Definition at line 170 of file tnt_fortran_array2d_utils.h.
References B, TNT::Fortran_Array2D< T >::dim1(), TNT::Fortran_Array2D< T >::dim2(), and i.
template<class T > Fortran_Array3D<T>& TNT::operator+= (Fortran_Array3D< T > & A, const Fortran_Array3D< T > & B)
Definition at line 175 of file tnt_fortran_array3d_utils.h.
References B, TNT::Fortran_Array3D< T >::dim1(), TNT::Fortran_Array3D< T >::dim2(), TNT::Fortran_Array3D< T >::dim3(), i, and p.
template<class T > Array1D<T>& TNT::operator+= (Array1D< T > & A, const Array1D< T > & B)
Definition at line 159 of file tnt_array1d_utils.h.
References TNT::Array1D< T >::dim1(), and i.
template<class T > Array2D<T>& TNT::operator+= (Array2D< T > & A, const Array2D< T > & B)
Definition at line 173 of file tnt_array2d_utils.h.
References TNT::Array2D< T >::dim1(), TNT::Array2D< T >::dim2(), and i.
template<class T > Array3D<T>& TNT::operator+= (Array3D< T > & A, const Array3D< T > & B)
Definition at line 161 of file tnt_array3d_utils.h.
References TNT::Array3D< T >::dim1(), TNT::Array3D< T >::dim2(), TNT::Array3D< T >::dim3(), i, and p.
template<class T > Fortran_Array3D<T> TNT::operator- (const Fortran_Array3D< T > & A, const Fortran_Array3D< T > & B)
Definition at line 103 of file tnt_fortran_array3d_utils.h.
References B, C, TNT::Fortran_Array3D< T >::dim1(), TNT::Fortran_Array3D< T >::dim2(), TNT::Fortran_Array3D< T >::dim3(), i, and p.
template<class T > Fortran_Array1D<T> TNT::operator- (const Fortran_Array1D< T > & A, const Fortran_Array1D< T > & B)
Definition at line 105 of file tnt_fortran_array1d_utils.h.
References B, C, TNT::Fortran_Array1D< T >::dim1(), and i.
template<class T > Fortran_Array2D<T> TNT::operator- (const Fortran_Array2D< T > & A, const Fortran_Array2D< T > & B)
Definition at line 100 of file tnt_fortran_array2d_utils.h.
References B, C, TNT::Fortran_Array2D< T >::dim1(), TNT::Fortran_Array2D< T >::dim2(), and i.
template<class T > Matrix< T > TNT::operator- (const Matrix< T > & A, const Matrix< T > & B)
Definition at line 441 of file cmat.h.
References assert, i, M, N, TNT::Matrix< T >::num_cols(), and TNT::Matrix< T >::num_rows().
template<class T > Fortran_Matrix<T> TNT::operator- (const Fortran_Matrix< T > & A, const Fortran_Matrix< T > & B)
Definition at line 375 of file fmat.h.
References assert, B, i, M, N, TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
template<class T > Vector< T > TNT::operator- (const Vector< T > & A, const Vector< T > & B)
Definition at line 337 of file vec.h.
References assert, TNT::Vector< T >::dim(), i, and N.
template<class T > Array3D<T> TNT::operator- (const Array3D< T > & A, const Array3D< T > & B)
Definition at line 86 of file tnt_array3d_utils.h.
References C, TNT::Array3D< T >::dim1(), TNT::Array3D< T >::dim2(), TNT::Array3D< T >::dim3(), i, and p.
template<class T > Array1D<T> TNT::operator- (const Array1D< T > & A, const Array1D< T > & B)
Definition at line 89 of file tnt_array1d_utils.h.
References C, TNT::Array1D< T >::dim1(), and i.
template<class T > Array2D<T> TNT::operator- (const Array2D< T > & A, const Array2D< T > & B)
Definition at line 99 of file tnt_array2d_utils.h.
References C, TNT::Array2D< T >::dim1(), TNT::Array2D< T >::dim2(), and i.
Index1D TNT::operator- (Index1D & D, Subscript i) [inline]
Definition at line 74 of file index.h.
References i, TNT::Index1D::lbound(), and TNT::Index1D::ubound().
Index1D TNT::operator- (Subscript i, Index1D & D) [inline]
Definition at line 79 of file index.h.
References TNT::Index1D::lbound(), and TNT::Index1D::ubound().
template<class T > Fortran_Array2D<T>& TNT::operator-= (Fortran_Array2D< T > & A, const Fortran_Array2D< T > & B)
Definition at line 187 of file tnt_fortran_array2d_utils.h.
References B, TNT::Fortran_Array2D< T >::dim1(), TNT::Fortran_Array2D< T >::dim2(), and i.
template<class T > Array3D<T>& TNT::operator-= (Array3D< T > & A, const Array3D< T > & B)
Definition at line 179 of file tnt_array3d_utils.h.
References TNT::Array3D< T >::dim1(), TNT::Array3D< T >::dim2(), TNT::Array3D< T >::dim3(), i, and p.
template<class T > Fortran_Array3D<T>& TNT::operator-= (Fortran_Array3D< T > & A, const Fortran_Array3D< T > & B)
Definition at line 194 of file tnt_fortran_array3d_utils.h.
References B, TNT::Fortran_Array3D< T >::dim1(), TNT::Fortran_Array3D< T >::dim2(), TNT::Fortran_Array3D< T >::dim3(), i, and p.
template<class T > Fortran_Array1D<T>& TNT::operator-= (Fortran_Array1D< T > & A, const Fortran_Array1D< T > & B)
Definition at line 193 of file tnt_fortran_array1d_utils.h.
References B, TNT::Fortran_Array1D< T >::dim1(), and i.
template<class T > Array1D<T>& TNT::operator-= (Array1D< T > & A, const Array1D< T > & B)
Definition at line 177 of file tnt_array1d_utils.h.
References TNT::Array1D< T >::dim1(), and i.
Referenced by ATTRIBUTE_ALIGNED16().
template<class T > Array2D<T>& TNT::operator-= (Array2D< T > & A, const Array2D< T > & B)
Definition at line 192 of file tnt_array2d_utils.h.
References TNT::Array2D< T >::dim1(), TNT::Array2D< T >::dim2(), and i.
template<class T > Fortran_Array2D<T> TNT::operator/ (const Fortran_Array2D< T > & A, const Fortran_Array2D< T > & B)
Definition at line 146 of file tnt_fortran_array2d_utils.h.
References B, C, TNT::Fortran_Array2D< T >::dim1(), TNT::Fortran_Array2D< T >::dim2(), and i.
template<class T > Fortran_Array1D<T> TNT::operator/ (const Fortran_Array1D< T > & A, const Fortran_Array1D< T > & B)
Definition at line 147 of file tnt_fortran_array1d_utils.h.
References B, C, TNT::Fortran_Array1D< T >::dim1(), and i.
template<class T > Array3D<T> TNT::operator/ (const Array3D< T > & A, const Array3D< T > & B)
Definition at line 136 of file tnt_array3d_utils.h.
References C, TNT::Array3D< T >::dim1(), TNT::Array3D< T >::dim2(), TNT::Array3D< T >::dim3(), i, and p.
template<class T > Fortran_Array3D<T> TNT::operator/ (const Fortran_Array3D< T > & A, const Fortran_Array3D< T > & B)
Definition at line 151 of file tnt_fortran_array3d_utils.h.
References B, C, TNT::Fortran_Array3D< T >::dim1(), TNT::Fortran_Array3D< T >::dim2(), TNT::Fortran_Array3D< T >::dim3(), i, and p.
template<class T > Array1D<T> TNT::operator/ (const Array1D< T > & A, const Array1D< T > & B)
Definition at line 131 of file tnt_array1d_utils.h.
References C, TNT::Array1D< T >::dim1(), and i.
template<class T > Array2D<T> TNT::operator/ (const Array2D< T > & A, const Array2D< T > & B)
Definition at line 147 of file tnt_array2d_utils.h.
References C, TNT::Array2D< T >::dim1(), TNT::Array2D< T >::dim2(), and i.
template<class T > Array3D<T>& TNT::operator/= (Array3D< T > & A, const Array3D< T > & B)
Definition at line 216 of file tnt_array3d_utils.h.
References TNT::Array3D< T >::dim1(), TNT::Array3D< T >::dim2(), TNT::Array3D< T >::dim3(), i, and p.
template<class T > Fortran_Array1D<T>& TNT::operator/= (Fortran_Array1D< T > & A, const Fortran_Array1D< T > & B)
Definition at line 228 of file tnt_fortran_array1d_utils.h.
References B, TNT::Fortran_Array1D< T >::dim1(), and i.
template<class T > Fortran_Array2D<T>& TNT::operator/= (Fortran_Array2D< T > & A, const Fortran_Array2D< T > & B)
Definition at line 221 of file tnt_fortran_array2d_utils.h.
References B, TNT::Fortran_Array2D< T >::dim1(), TNT::Fortran_Array2D< T >::dim2(), and i.
template<class T > Fortran_Array3D<T>& TNT::operator/= (Fortran_Array3D< T > & A, const Fortran_Array3D< T > & B)
Definition at line 232 of file tnt_fortran_array3d_utils.h.
References B, TNT::Fortran_Array3D< T >::dim1(), TNT::Fortran_Array3D< T >::dim2(), TNT::Fortran_Array3D< T >::dim3(), i, and p.
template<class T > Array1D<T>& TNT::operator/= (Array1D< T > & A, const Array1D< T > & B)
Definition at line 212 of file tnt_array1d_utils.h.
References TNT::Array1D< T >::dim1(), and i.
template<class T > Array2D<T>& TNT::operator/= (Array2D< T > & A, const Array2D< T > & B)
Definition at line 232 of file tnt_array2d_utils.h.
References TNT::Array2D< T >::dim1(), TNT::Array2D< T >::dim2(), and i.
template<class T > std::ostream & TNT::operator<< (std::ostream & s, const Matrix< T > & A)
Definition at line 374 of file cmat.h.
References A, i, M, and N.
template<class MaTRiX > std::ostream& TNT::operator<< (std::ostream & s, const LowerTriangularView< MaTRiX > & A)
Definition at line 293 of file triang.h.
References A, i, M, and N.
template<class MaTRiX > std::ostream& TNT::operator<< (std::ostream & s, const UnitLowerTriangularView< MaTRiX > & A)
Definition at line 314 of file triang.h.
References i, M, N, TNT::UnitLowerTriangularView< MaTRiX >::num_cols(), and TNT::UnitLowerTriangularView< MaTRiX >::num_rows().
template<class T > std::ostream& TNT::operator<< (std::ostream & s, const Fortran_Array3D< T > & A)
Definition at line 35 of file tnt_fortran_array3d_utils.h.
References A, i, K, M, and N.
template<class Array1D > std::ostream& TNT::operator<< (std::ostream & s, const_Region1D< Array1D > & A)
Definition at line 361 of file region1d.h.
References A, i, and N.
template<class Matrix > std::ostream& TNT::operator<< (std::ostream & s, const Transpose_View< Matrix > & A)
Definition at line 138 of file transv.h.
References A, i, M, and N.
template<class Array1D > std::ostream& TNT::operator<< (std::ostream & s, Region1D< Array1D > & A)
Definition at line 235 of file region1d.h.
References A, i, N, and TNT_BASE_OFFSET.
template<class MaTRiX > std::ostream& TNT::operator<< (std::ostream & s, UpperTriangularView< MaTRiX > & A)
Definition at line 591 of file triang.h.
References i, M, N, TNT::UpperTriangularView< MaTRiX >::num_cols(), and TNT::UpperTriangularView< MaTRiX >::num_rows().
template<class T > std::ostream& TNT::operator<< (std::ostream & s, const Array2D< T > & A)
Definition at line 35 of file tnt_array2d_utils.h.
References A, i, M, and N.
template<class T > std::ostream& TNT::operator<< (std::ostream & s, const Fortran_Array2D< T > & A)
Definition at line 34 of file tnt_fortran_array2d_utils.h.
References A, i, M, and N.
template<class T > std::ostream & TNT::operator<< (std::ostream & s, const Vector< T > & A)
Definition at line 282 of file vec.h.
References A, i, and N.
template<class Array2D > std::ostream& TNT::operator<< (std::ostream & s, const Region2D< Array2D > & A)
Definition at line 446 of file region2d.h.
References A, and i.
template<class T > std::ostream& TNT::operator<< (std::ostream & s, const Fortran_Array1D< T > & A)
Write an array to a character outstream. Output format is one that can be read back in via the in-stream operator: one integer denoting the array dimension (n), followed by n elements, one per line.
Definition at line 40 of file tnt_fortran_array1d_utils.h.
References A, and N.
template<class Array2D > std::ostream& TNT::operator<< (std::ostream & s, const const_Region2D< Array2D > & A)
Definition at line 424 of file region2d.h.
References A, and i.
template<class BBVec > std::ostream& TNT::operator<< (std::ostream & s, const Vector_Adaptor< BBVec > & A)
Definition at line 256 of file vecadaptor.h.
References A, i, and M.
template<class T > ostream& TNT::operator<< (ostream & s, const Fortran_Sparse_Col_Matrix< T > & A)
Definition at line 141 of file fcscmat.h.
References A, i, M, and N.
template<class T > ostream& TNT::operator<< (ostream & s, const Fortran_Sparse_Vector< T > & A)
Definition at line 134 of file fspvec.h.
References A, and i.
template<class MaTRiX > std::ostream& TNT::operator<< (std::ostream & s, UnitUpperTriangularView< MaTRiX > & A)
Definition at line 613 of file triang.h.
References i, M, N, TNT::UnitUpperTriangularView< MaTRiX >::num_cols(), and TNT::UnitUpperTriangularView< MaTRiX >::num_rows().
template<class T > std::ostream& TNT::operator<< (std::ostream & s, const Fortran_Matrix< T > & A)
Definition at line 307 of file fmat.h.
References A, i, M, and N.
template<class T > std::ostream& TNT::operator<< (std::ostream & s, const Array3D< T > & A)
Definition at line 17 of file tnt_array3d_utils.h.
References A, i, K, M, and N.
template<class T > std::ostream& TNT::operator<< (std::ostream & s, const Array1D< T > & A)
Definition at line 34 of file tnt_array1d_utils.h.
References A, and N.
template<class T > std::istream& TNT::operator>> (std::istream & s, Fortran_Array2D< T > & A)
Definition at line 55 of file tnt_fortran_array2d_utils.h.
References B, i, M, and N.
template<class T > istream& TNT::operator>> (istream & s, Fortran_Sparse_Vector< T > & A)
Definition at line 150 of file fspvec.h.
References i, TNT::Fortran_Sparse_Vector< T >::index(), N, TNT::Fortran_Sparse_Vector< T >::newsize(), and TNT::Fortran_Sparse_Vector< T >::val().
template<class T > std::istream& TNT::operator>> (std::istream & s, Array2D< T > & A)
Definition at line 56 of file tnt_array2d_utils.h.
References B, i, M, and N.
template<class T > std::istream& TNT::operator>> (std::istream & s, Fortran_Array1D< T > & A)
Read an array from a character stream. Input format is one integer, denoting the dimension (n), followed by n whitespace-separated elments. Newlines are ignored
Note: the array being read into references new memory storage. If the intent is to fill an existing conformant array, use cin >> B; A.inject(B)); instead or read the elements in one-a-time by hand.
Parameters:
s the charater to read from (typically std::in)
A the array to read into.
Definition at line 69 of file tnt_fortran_array1d_utils.h.
References B, i, and N.
template<class T > std::istream& TNT::operator>> (std::istream & s, Fortran_Matrix< T > & A)
Definition at line 328 of file fmat.h.
References i, M, N, TNT::Fortran_Matrix< T >::newsize(), TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
template<class T > std::istream& TNT::operator>> (std::istream & s, Fortran_Array3D< T > & A)
Definition at line 59 of file tnt_fortran_array3d_utils.h.
References B, i, K, M, and N.
template<class T > std::istream& TNT::operator>> (std::istream & s, Array3D< T > & A)
Definition at line 41 of file tnt_array3d_utils.h.
References B, i, K, M, and N.
template<class T > std::istream & TNT::operator>> (std::istream & s, Vector< T > & A)
Definition at line 296 of file vec.h.
References i, N, TNT::Vector< T >::newsize(), and TNT::Vector< T >::size().
template<class T > std::istream & TNT::operator>> (std::istream & s, Matrix< T > & A)
Definition at line 395 of file cmat.h.
References i, M, N, TNT::Matrix< T >::newsize(), TNT::Matrix< T >::num_cols(), and TNT::Matrix< T >::num_rows().
template<class T > std::istream& TNT::operator>> (std::istream & s, Array1D< T > & A)
Definition at line 52 of file tnt_array1d_utils.h.
References B, i, and N.
template<class BBVec > std::istream& TNT::operator>> (std::istream & s, Vector_Adaptor< BBVec > & A)
Definition at line 267 of file vecadaptor.h.
References i, N, and TNT::Vector_Adaptor< BBVec >::resize().
double TNT::pythag (double a, double b) [inline]
Definition at line 128 of file tntmath.h.
References abs(), KDL::sqr(), and sqrt().
float TNT::pythag (float a, float b) [inline]
Definition at line 107 of file tntmath.h.
References abs(), KDL::sqr(), and sqrt().
template<class MaTRiX , class Vector > int TNT::QR_factor (MaTRiX & A, Vector & C, Vector & D)
Definition at line 89 of file qr.h.
References assert, C, D(), fabs(), i, TNT::Vector< T >::lbound(), M, N, TNT::Vector< T >::newsize(), sign(), TNT::Vector< T >::size(), sqrt(), and sum().
template<class MaTRiX , class Vector > int TNT::QR_solve (const MaTRiX & A, const Vector & c, Vector & d, Vector & b)
Definition at line 198 of file qr.h.
References assert, TNT::Vector< T >::dim(), i, TNT::Vector< T >::lbound(), N, R_solve(), and sum().
template<class MaTRiX , class Vector > int TNT::R_solve (const MaTRiX & A, Vector & D, Vector & b)
Definition at line 161 of file qr.h.
References assert, D(), TNT::Vector< T >::dim(), i, TNT::Vector< T >::lbound(), N, and sum().
Referenced by QR_solve().
static double TNT::seconds (void) [inline]
Definition at line 46 of file stopwatch.h.
Referenced by ANIM_timecode_string_from_frame(), TNT::stopwatch::read(), TNT::Stopwatch::resume(), TNT::Stopwatch::start(), TNT::stopwatch::start(), TNT::Stopwatch::stop(), and TNT::stopwatch::stop().
double TNT::sign (double a, double b) [inline]
Definition at line 94 of file tntmath.h.
References abs().
float TNT::sign (float a) [inline]
Definition at line 102 of file tntmath.h.
float TNT::sign (float a, float b) [inline]
Definition at line 98 of file tntmath.h.
References abs().
double TNT::sign (double a) [inline]
Definition at line 89 of file tntmath.h.
Referenced by dBoxBox2(), do_bake_shade(), flush_pixel(), intersectRectQuad2(), nonzero(), QR_factor(), KX_ConstraintActuator::Update(), iTaSC::Distance::updateControlOutput(), and wind_func().
template<class MaTRiX , class VecToR > void TNT::SVD (MaTRiX & A, MaTRiX & U, VecToR & s, MaTRiX & V, VecToR & work1, VecToR & work2, int maxiter = SVD_MAX_ITER)
Definition at line 26 of file svd.h.
References abs(), g, hypot(), i, max(), min(), p, pow(), pp, and sqrt().
Referenced by IK_QJacobian::Invert().
template<class T > Fortran_Matrix<T> TNT::transpose (const Fortran_Matrix< T > & A)
Definition at line 420 of file fmat.h.
References i, M, N, TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
template<class T > void TNT::transpose (const Matrix< T > & A, Matrix< T > & S)
Definition at line 481 of file cmat.h.
References assert, i, M, N, TNT::Matrix< T >::num_cols(), and TNT::Matrix< T >::num_rows().
template<class T > Matrix<T> TNT::transpose (const Matrix< T > & A)
Definition at line 457 of file tnt_cmat.h.
References i, M, and N.
template<class Matrix > Transpose_View<Matrix> TNT::Transpose_view (const Matrix & A)
Definition at line 99 of file transv.h.
template<class MaTriX , class VecToR > VecToR TNT::Unit_lower_triangular_solve (MaTriX & A, VecToR & b)
Definition at line 69 of file trisolve.h.
References assert, i, and N.
Referenced by linear_solve().
template<class MaTRiX > UnitLowerTriangularView<MaTRiX> TNT::Unit_lower_triangular_view (MaTRiX & A)
Definition at line 249 of file triang.h.
template<class MaTriX , class VecToR > VecToR TNT::Unit_upper_triangular_solve (MaTriX & A, VecToR & b)
Definition at line 143 of file trisolve.h.
References assert, i, and N.
Referenced by linear_solve().
template<class MaTRiX > UnitUpperTriangularView<MaTRiX> TNT::Unit_upper_triangular_view (MaTRiX & A)
Definition at line 547 of file triang.h.
template<class MaTriX , class VecToR > VecToR TNT::Upper_triangular_solve (MaTriX & A, VecToR & b)
Definition at line 115 of file trisolve.h.
References assert, i, and N.
Referenced by linear_solve().
template<class MaTRiX > UpperTriangularView<MaTRiX> TNT::Upper_triangular_view (MaTRiX & A)
Definition at line 539 of file triang.h.
template<class T > void TNT::vectoradd (Vector< T > & C, const Vector< T > & A, const Vector< T > & B)
Definition at line 421 of file vec.h.
References assert, TNT::Vector< T >::dim(), i, and N.
template<class T > void TNT::vectoradd (Vector< T > & A, const Vector< T > & B)
Definition at line 406 of file vec.h.
References assert, TNT::Vector< T >::dim(), i, and N.
Referenced by LOD_NdQuadric::operator+=().
template<class T > void TNT::vectorscale (Vector< T > & A, const T & B)
Definition at line 477 of file vec.h.
References TNT::Vector< T >::dim(), i, and N.
template<class T > void TNT::vectorscale (Vector< T > & C, const Vector< T > & A, const T & B)
Definition at line 464 of file vec.h.
References TNT::Vector< T >::dim(), i, and N.
Referenced by LOD_NdQuadric::operator*=().
template<class T > void TNT::vectorsub (Vector< T > & C, const Vector< T > & A, const Vector< T > & B)
Definition at line 450 of file vec.h.
References assert, TNT::Vector< T >::dim(), i, and N.
template<class T > void TNT::vectorsub (Vector< T > & A, const Vector< T > & B)
Definition at line 437 of file vec.h.
References assert, TNT::Vector< T >::dim(), i, and N.