Blender: node_edit.c File Reference
node_edit.c File Reference
node editor
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <errno.h>
#include "MEM_guardedalloc.h"
#include "DNA_ID.h"
#include "DNA_lamp_types.h"
#include "DNA_material_types.h"
#include "DNA_node_types.h"
#include "DNA_object_types.h"
#include "DNA_particle_types.h"
#include "DNA_scene_types.h"
#include "DNA_world_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_global.h"
#include "BKE_image.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_node.h"
#include "BKE_material.h"
#include "BKE_modifier.h"
#include "BKE_paint.h"
#include "BKE_scene.h"
#include "BKE_screen.h"
#include "BKE_texture.h"
#include "BKE_report.h"
#include "RE_pipeline.h"
#include "IMB_imbuf_types.h"
#include "ED_node.h"
#include "ED_image.h"
#include "ED_screen.h"
#include "ED_space_api.h"
#include "ED_render.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "IMB_imbuf.h"
#include "GPU_material.h"
#include "node_intern.h"
Classes
struct CompoJob
struct NodeViewMove
struct ImageSampleInfo
struct NodeSizeWidget
struct bNodeListItem
Defines
#define LINK_RESOL 12
Typedefs
typedef struct CompoJob CompoJob
typedef struct NodeViewMove NodeViewMove
typedef struct ImageSampleInfo ImageSampleInfo
typedef struct NodeSizeWidget NodeSizeWidget
typedef struct bNodeListItem bNodeListItem
Functions
static int compo_breakjob (void *cjv)
static void compo_redrawjob (void *cjv, char *UNUSED(str))
static void compo_freejob (void *cjv)
static void compo_initjob (void *cjv)
static void compo_updatejob (void *cjv)
static void compo_progressjob (void *cjv, float progress)
static void compo_startjob (void *cjv, short *stop, short *do_update, float *progress)
void snode_composite_job (const bContext *C, ScrArea *sa)
static int composite_node_active (bContext *C)
static bNode * editnode_get_active (bNodeTree *ntree)
void snode_dag_update (bContext *UNUSED(C), SpaceNode *snode)
void snode_notify (bContext *C, SpaceNode *snode)
bNode * node_tree_get_editgroup (bNodeTree *nodetree)
void ED_node_shader_default (Scene *scene, ID *id)
void ED_node_composit_default (Scene *sce)
void ED_node_texture_default (Tex *tx)
void node_tree_from_ID (ID *id, bNodeTree **ntree, bNodeTree **edittree, int *treetype)
void snode_set_context (SpaceNode *snode, Scene *scene)
static void snode_update (SpaceNode *snode, bNode *node)
static int has_nodetree (bNodeTree *ntree, bNodeTree *lookup)
void ED_node_set_active (Main *bmain, bNodeTree *ntree, bNode *node)
static int inside_rctf (rctf *bounds, rctf *rect)
static void node_frame_attach_nodes (bNodeTree *UNUSED(ntree), bNode *frame)
void ED_node_update_hierarchy (bContext *UNUSED(C), bNodeTree *ntree)
void snode_make_group_editable (SpaceNode *snode, bNode *gnode)
static int node_group_edit_exec (bContext *C, wmOperator *UNUSED(op))
static int node_group_edit_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void NODE_OT_group_edit (wmOperatorType *ot)
static int node_group_socket_add_exec (bContext *C, wmOperator *op)
void NODE_OT_group_socket_add (wmOperatorType *ot)
static int node_group_socket_remove_exec (bContext *C, wmOperator *op)
void NODE_OT_group_socket_remove (wmOperatorType *ot)
static int node_group_socket_move_up_exec (bContext *C, wmOperator *op)
void NODE_OT_group_socket_move_up (wmOperatorType *ot)
static int node_group_socket_move_down_exec (bContext *C, wmOperator *op)
void NODE_OT_group_socket_move_down (wmOperatorType *ot)
static int node_group_ungroup_exec (bContext *C, wmOperator *op)
void NODE_OT_group_ungroup (wmOperatorType *ot)
static bNode * visible_node (SpaceNode *snode, rctf *rct)
static int snode_bg_viewmove_modal (bContext *C, wmOperator *op, wmEvent *event)
static int snode_bg_viewmove_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int snode_bg_viewmove_cancel (bContext *UNUSED(C), wmOperator *op)
void NODE_OT_backimage_move (wmOperatorType *ot)
static int backimage_zoom (bContext *C, wmOperator *op)
void NODE_OT_backimage_zoom (wmOperatorType *ot)
static void sample_draw (const bContext *C, ARegion *ar, void *arg_info)
static void sample_apply (bContext *C, wmOperator *op, wmEvent *event)
static void sample_exit (bContext *C, wmOperator *op)
static int sample_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int sample_modal (bContext *C, wmOperator *op, wmEvent *event)
static int sample_cancel (bContext *C, wmOperator *op)
void NODE_OT_backimage_sample (wmOperatorType *ot)
static int node_resize_modal (bContext *C, wmOperator *op, wmEvent *event)
static int node_resize_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int node_resize_cancel (bContext *UNUSED(C), wmOperator *op)
void NODE_OT_resize (wmOperatorType *ot)
int node_has_hidden_sockets (bNode *node)
void node_set_hidden_sockets (SpaceNode *snode, bNode *node, int set)
static int node_link_viewer (const bContext *C, bNode *tonode)
static int node_active_link_viewer (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_link_viewer (wmOperatorType *ot)
static int UNUSED_FUNCTION() node_mouse_groupheader (SpaceNode *snode)
int node_find_indicated_socket (SpaceNode *snode, bNode **nodep, bNodeSocket **sockp, int in_out)
static int outside_group_rect (SpaceNode *snode)
static int sort_nodes_locx (void *a, void *b)
static int socket_is_available (bNodeTree *UNUSED(ntree), bNodeSocket *sock, int allow_used)
static bNodeSocket * best_socket_output (bNodeTree *ntree, bNode *node, bNodeSocket *sock_target, int allow_multiple)
static bNodeSocket * best_socket_input (bNodeTree *ntree, bNode *node, int num, int replace)
static int snode_autoconnect_input (SpaceNode *snode, bNode *node_fr, bNodeSocket *sock_fr, bNode *node_to, bNodeSocket *sock_to, int replace)
void snode_autoconnect (SpaceNode *snode, int allow_multiple, int replace)
bNode * node_add_node (SpaceNode *snode, Main *bmain, Scene *scene, bNodeTemplate *ntemp, float locx, float locy)
static int node_duplicate_exec (bContext *C, wmOperator *op)
void NODE_OT_duplicate (wmOperatorType *ot)
static void node_remove_extra_links (SpaceNode *snode, bNodeSocket *tsock, bNodeLink *link)
static int node_link_modal (bContext *C, wmOperator *op, wmEvent *event)
static int node_link_init (SpaceNode *snode, bNodeLinkDrag *nldrag)
static int node_link_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int node_link_cancel (bContext *C, wmOperator *op)
void NODE_OT_link (wmOperatorType *ot)
static int node_make_link_exec (bContext *C, wmOperator *op)
void NODE_OT_link_make (wmOperatorType *ot)
static int cut_links_intersect (bNodeLink *link, float mcoords[][2], int tot)
static int cut_links_exec (bContext *C, wmOperator *op)
void NODE_OT_links_cut (wmOperatorType *ot)
static int detach_links_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_links_detach (wmOperatorType *ot)
static bNodeSocket * socket_best_match (ListBase *sockets)
static SpaceNode * ed_node_link_conditions (ScrArea *sa, bNode **select)
void ED_node_link_insert (ScrArea *sa)
void ED_node_link_intersect_test (ScrArea *sa, int test)
static int node_read_renderlayers_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_read_renderlayers (wmOperatorType *ot)
static int node_read_fullsamplelayers_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_read_fullsamplelayers (wmOperatorType *ot)
int node_render_changed_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_render_changed (wmOperatorType *ot)
static int node_group_make_exec (bContext *C, wmOperator *op)
void NODE_OT_group_make (wmOperatorType *ot)
static void node_flag_toggle_exec (SpaceNode *snode, int toggle_flag)
static int node_hide_toggle_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_hide_toggle (wmOperatorType *ot)
static int node_preview_toggle_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_preview_toggle (wmOperatorType *ot)
static int node_options_toggle_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_options_toggle (wmOperatorType *ot)
static int node_socket_toggle_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_hide_socket_toggle (wmOperatorType *ot)
static int node_mute_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_mute_toggle (wmOperatorType *ot)
static int node_delete_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_delete (wmOperatorType *ot)
static int node_delete_reconnect_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_delete_reconnect (wmOperatorType *ot)
static int node_show_cycles_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_show_cyclic_dependencies (wmOperatorType *ot)
static int node_add_file_exec (bContext *C, wmOperator *op)
static int node_add_file_invoke (bContext *C, wmOperator *op, wmEvent *event)
void NODE_OT_add_file (wmOperatorType *ot)
static int new_node_tree_exec (bContext *C, wmOperator *op)
void NODE_OT_new_node_tree (wmOperatorType *ot)
static int node_output_file_add_socket_exec (bContext *C, wmOperator *op)
void NODE_OT_output_file_add_socket (wmOperatorType *ot)
static int node_output_file_remove_active_socket_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_output_file_remove_active_socket (wmOperatorType *ot)
Variables
static EnumPropertyItem socket_in_out_items []
Detailed Description
Definition in file node_edit.c.
Define Documentation
#define LINK_RESOL 12
Definition at line 2631 of file node_edit.c.
Referenced by cut_links_intersect().
Typedef Documentation
typedef struct bNodeListItem bNodeListItem
typedef struct CompoJob CompoJob
typedef struct ImageSampleInfo ImageSampleInfo
typedef struct NodeSizeWidget NodeSizeWidget
typedef struct NodeViewMove NodeViewMove
Function Documentation
static int backimage_zoom (bContext * C, wmOperator * op) [static]
Definition at line 1300 of file node_edit.c.
References CTX_wm_region(), CTX_wm_space_node(), ED_region_tag_redraw(), OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get(), and SpaceNode::zoom.
Referenced by NODE_OT_backimage_zoom().
static bNodeSocket* best_socket_input (bNodeTree * ntree, bNode * node, int num, int replace) [static]
Definition at line 1980 of file node_edit.c.
References ListBase::first, bNode::inputs, MAX2, bNodeSocket::next, NULL, socket_is_available(), and bNodeSocket::type.
Referenced by snode_autoconnect().
static bNodeSocket* best_socket_output (bNodeTree * ntree, bNode * node, bNodeSocket * sock_target, int allow_multiple) [static]
Definition at line 1938 of file node_edit.c.
References ListBase::first, bNodeSocket::flag, bNodeSocket::name, bNodeSocket::next, NULL, bNode::outputs, SELECT, socket_is_available(), and bNodeSocket::type.
Referenced by snode_autoconnect().
static int compo_breakjob (void * cjv) [static]
Definition at line 116 of file node_edit.c.
References CompoJob::stop.
Referenced by compo_startjob().
static void compo_freejob (void * cjv) [static]
Definition at line 131 of file node_edit.c.
References CompoJob::localtree, MEM_freeN(), CompoJob::ntree, and ntreeLocalMerge().
Referenced by snode_composite_job().
static void compo_initjob (void * cjv) [static]
Definition at line 143 of file node_edit.c.
References CompoJob::localtree, CompoJob::ntree, and ntreeLocalize().
Referenced by snode_composite_job().
static void compo_progressjob (void * cjv, float progress) [static]
Definition at line 158 of file node_edit.c.
References CompoJob::progress.
Referenced by compo_startjob().
static void compo_redrawjob (void * cjv, char * UNUSEDstr) [static]
Definition at line 124 of file node_edit.c.
References CompoJob::do_update.
Referenced by compo_startjob().
static void compo_startjob (void * cjv, short * stop, short * do_update, float * progress) [static]
Definition at line 167 of file node_edit.c.
References compo_breakjob(), compo_progressjob(), compo_redrawjob(), CompoJob::do_update, CompoJob::localtree, ntreeCompositExecTree(), NULL, bNodeTree::prh, bNodeTree::progress, CompoJob::progress, Scene::r, CompoJob::scene, bNodeTree::sdh, bNodeTree::stats_draw, CompoJob::stop, bNodeTree::tbh, bNodeTree::test_break, and Scene::use_nodes.
Referenced by snode_composite_job().
static void compo_updatejob (void * cjv) [static]
Definition at line 151 of file node_edit.c.
References CompoJob::localtree, CompoJob::ntree, and ntreeLocalSync().
Referenced by snode_composite_job().
static int composite_node_active (bContext * C) [static]
Definition at line 221 of file node_edit.c.
References CTX_wm_space_node(), ED_operator_node_active(), NTREE_COMPOSIT, and SpaceNode::treetype.
Referenced by NODE_OT_backimage_move(), NODE_OT_backimage_zoom(), NODE_OT_link_viewer(), NODE_OT_output_file_add_socket(), NODE_OT_output_file_remove_active_socket(), NODE_OT_read_fullsamplelayers(), NODE_OT_read_renderlayers(), and NODE_OT_render_changed().
static int cut_links_exec (bContext * C, wmOperator * op) [static]
Definition at line 2647 of file node_edit.c.
References CTX_wm_region(), CTX_wm_space_node(), cut_links_intersect(), ED_preview_kill_jobs(), SpaceNode::edittree, ListBase::first, i, link(), bNodeTree::links, bNodeLink::next, next, nodeRemLink(), ntreeUpdateTree(), OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_BEGIN, RNA_END, RNA_float_get_array(), snode_dag_update(), snode_notify(), snode_update(), bNodeLink::tonode, UI_view2d_region_to_view(), and ARegion::v2d.
Referenced by NODE_OT_links_cut().
static int cut_links_intersect (bNodeLink * link, float mcoords[][2], int tot) [static]
Definition at line 2632 of file node_edit.c.
References i, isect_line_line_v2(), LINK_RESOL, node_link_bezier_points(), and NULL.
Referenced by cut_links_exec(), and ED_node_link_intersect_test().
static int detach_links_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2714 of file node_edit.c.
References CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, ListBase::first, bNode::flag, bNode::next, nodeInternalRelink(), bNodeTree::nodes, ntreeUpdateTree(), OPERATOR_FINISHED, SELECT, snode_dag_update(), and snode_notify().
Referenced by NODE_OT_links_detach().
void ED_node_composit_default (Scene * sce)
Definition at line 365 of file node_edit.c.
References CMP_NODE_COMPOSITE, CMP_NODE_R_LAYERS, ListBase::first, G, G_DEBUG, Scene::id, bNode::id, id_us_plus(), bNode::inputs, bNode::locx, bNode::locy, nodeAddLink(), nodeAddNode(), nodeSetActive(), Scene::nodetree, NTREE_COMPOSIT, ntreeAddTree(), ntreeUpdateTree(), bNode::outputs, and bNodeTemplate::type.
static SpaceNode* ed_node_link_conditions (ScrArea * sa, bNode ** select) [static]
Definition at line 2783 of file node_edit.c.
References SpaceNode::edittree, ListBase::first, bNode::flag, bNodeLink::fromnode, link(), bNodeTree::links, bNode::next, bNodeLink::next, bNodeTree::nodes, NULL, SELECT, SPACE_NODE, ScrArea::spacedata, ScrArea::spacetype, and bNodeLink::tonode.
Referenced by ED_node_link_insert(), and ED_node_link_intersect_test().
void ED_node_link_insert (ScrArea * sa)
Definition at line 2818 of file node_edit.c.
References ED_node_changed_update(), ed_node_link_conditions(), SpaceNode::edittree, ListBase::first, bNodeLink::flag, SpaceNode::id, bNode::inputs, link(), bNodeTree::links, bNodeLink::next, NODE_LINKFLAG_HILITE, nodeAddLink(), ntreeUpdateTree(), NULL, bNode::outputs, snode_update(), socket_best_match(), bNodeLink::tonode, and bNodeLink::tosock.
Referenced by special_aftertrans_update().
void ED_node_link_intersect_test (ScrArea * sa, int test)
Definition at line 2849 of file node_edit.c.
References cut_links_intersect(), ed_node_link_conditions(), SpaceNode::edittree, ListBase::first, bNodeLink::flag, link(), bNodeTree::links, bNodeLink::next, NODE_LINKFLAG_HILITE, NULL, bNode::totr, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by flushTransNodes(), and special_aftertrans_update().
void ED_node_set_active (Main * bmain, bNodeTree * ntree, bNode * node)
Definition at line 603 of file node_edit.c.
References RenderData::actlay, BKE_image_verify_viewer(), CMP_NODE_COMPOSITE, CMP_NODE_R_LAYERS, CMP_NODE_SPLITVIEWER, CMP_NODE_VIEWER, bNode::custom1, ED_node_generic_update(), ELEM, ELEM3, ListBase::first, bNode::flag, GPU_material_free(), GS, has_nodetree(), Scene::id, Material::id, bNode::id, ID_LA, ID_MA, ID_TE, ID_WO, IMA_TYPE_COMPOSITE, Main::mat, ID::name, NC_IMAGE, NC_MATERIAL, ND_NODES, ID::next, bNode::next, NODE_ACTIVE_TEXTURE, NODE_DO_OUTPUT, NODE_GROUP, nodeClearActiveID(), bNodeTree::nodes, nodeSetActive(), Scene::nodetree, Material::nodetree, NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, NULL, Scene::r, Main::scene, SH_NODE_OUTPUT, bNodeTree::type, bNode::type, Scene::use_nodes, Material::use_nodes, and WM_main_add_notifier().
Referenced by node_add_node(), node_mouse_select(), node_select_single(), and template_texture_select().
void ED_node_shader_default (Scene * scene, ID * id)
Definition at line 276 of file node_edit.c.
References copy_v3_v3(), bNodeSocket::default_value, ListBase::first, GS, World::horr, ID_LA, ID_MA, ID_WO, bNode::inputs, LA_AREA, LA_LOCAL, LA_SPOT, ListBase::last, bNode::locx, bNode::locy, ID::name, nodeAddLink(), nodeAddNode(), nodeSetActive(), Lamp::nodetree, World::nodetree, Material::nodetree, NTREE_SHADER, ntreeAddTree(), ntreeUpdateTree(), bNode::outputs, Lamp::r, Material::r, scene_use_new_shading_nodes(), SH_NODE_BACKGROUND, SH_NODE_BSDF_DIFFUSE, SH_NODE_EMISSION, SH_NODE_MATERIAL, SH_NODE_OUTPUT, SH_NODE_OUTPUT_LAMP, SH_NODE_OUTPUT_MATERIAL, SH_NODE_OUTPUT_WORLD, bNodeTemplate::type, and Lamp::type.
Referenced by new_material_exec(), new_world_exec(), and object_lamp_add_exec().
void ED_node_texture_default (Tex * tx)
Definition at line 405 of file node_edit.c.
References ListBase::first, G, G_DEBUG, bNode::inputs, bNode::locx, bNode::locy, nodeAddLink(), nodeAddNode(), nodeSetActive(), Tex::nodetree, NTREE_TEXTURE, ntreeAddTree(), ntreeUpdateTree(), bNode::outputs, TEX_NODE_CHECKER, TEX_NODE_OUTPUT, and bNodeTemplate::type.
void ED_node_update_hierarchy (bContext * UNUSEDC, bNodeTree * ntree)
Definition at line 723 of file node_edit.c.
References bNode::flag, ListBase::last, NODE_FRAME, node_frame_attach_nodes(), NODE_SELECT, nodeDetachNode(), bNodeTree::nodes, bNode::parent, bNode::prev, and bNode::type.
static bNode* editnode_get_active (bNodeTree * ntree) [static]
Definition at line 232 of file node_edit.c.
References ListBase::first, bNode::id, bNode::next, nodeGetActive(), nodeGroupEditGet(), and bNodeTree::nodes.
Referenced by node_active_link_viewer(), node_resize_invoke(), and node_resize_modal().
static int has_nodetree (bNodeTree * ntree, bNodeTree * lookup) [static]
Definition at line 588 of file node_edit.c.
References ListBase::first, bNode::id, bNode::next, NODE_GROUP, bNodeTree::nodes, and bNode::type.
Referenced by ED_node_set_active().
static int inside_rctf (rctf * bounds, rctf * rect) [static]
Definition at line 696 of file node_edit.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by node_frame_attach_nodes().
static int new_node_tree_exec (bContext * C, wmOperator * op) [static]
Definition at line 3524 of file node_edit.c.
References CTX_data_scene(), CTX_wm_space_node(), ED_node_tree_update(), bNodeTree::id, MAX_ID_NAME, SpaceNode::nodetree, ntreeAddTree(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), RNA_id_pointer_create(), RNA_property_pointer_set(), RNA_property_update(), RNA_string_get(), RNA_struct_property_is_set(), SpaceNode::treetype, uiIDContextProperty(), and ID::us.
Referenced by NODE_OT_new_node_tree().
static int node_active_link_viewer (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1739 of file node_edit.c.
References CTX_wm_space_node(), ED_preview_kill_jobs(), editnode_get_active(), SpaceNode::edittree, node_link_viewer(), OPERATOR_CANCELLED, OPERATOR_FINISHED, and snode_notify().
Referenced by NODE_OT_link_viewer().
static int node_add_file_exec (bContext * C, wmOperator * op) [static]
Definition at line 3421 of file node_edit.c.
References BKE_add_image_file(), BKE_report(), BKE_reportf(), CMP_NODE_IMAGE, CTX_data_main(), CTX_data_scene(), CTX_wm_space_node(), ED_preview_kill_jobs(), FILE_MAX, find_id(), bNode::id, MAX_ID_NAME, SpaceNode::mx, SpaceNode::my, bNode::name, node_add_node(), node_deselect_all(), SpaceNode::nodetree, NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_string_get(), RNA_struct_property_is_set(), RPT_ERROR, RPT_WARNING, SH_NODE_TEX_IMAGE, snode_dag_update(), snode_notify(), TEX_NODE_IMAGE, bNodeTemplate::type, and bNodeTree::type.
Referenced by node_add_file_invoke(), and NODE_OT_add_file().
static int node_add_file_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 3488 of file node_edit.c.
References CTX_wm_region(), CTX_wm_space_node(), wmEvent::mval, SpaceNode::mx, SpaceNode::my, node_add_file_exec(), wmOperator::ptr, RNA_struct_property_is_set(), UI_view2d_region_to_view(), ARegion::v2d, and WM_operator_filesel().
Referenced by NODE_OT_add_file().
bNode* node_add_node (SpaceNode * snode, Main * bmain, Scene * scene, bNodeTemplate * ntemp, float locx, float locy)
Definition at line 2113 of file node_edit.c.
References Scene::clip, CMP_NODE_COMPOSITE, CMP_NODE_DEFOCUS, CMP_NODE_MOVIECLIP, CMP_NODE_MOVIEDISTORTION, CMP_NODE_OUTPUT_FILE, CMP_NODE_R_LAYERS, CMP_NODE_STABILIZE2D, ED_node_set_active(), SpaceNode::edittree, ELEM3, ELEM4, Scene::id, bNode::id, id_us_plus(), bNode::locx, bNode::locy, node_deselect_all(), node_select(), node_tree_get_editgroup(), nodeAddNode(), SpaceNode::nodetree, NTREE_COMPOSIT, NTREE_TEXTURE, ntreeCompositForceHidden(), ntreeTexCheckCyclics(), ntreeUpdateTree(), NULL, snode_update(), bNodeTree::type, and bNode::type.
Referenced by do_node_add(), node_add_file_exec(), and node_link_viewer().
static int node_delete_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3308 of file node_edit.c.
References CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, ListBase::first, bNode::flag, bNode::id, bNode::next, next, nodeFreeNode(), bNodeTree::nodes, ntreeUpdateTree(), OPERATOR_FINISHED, SELECT, snode_dag_update(), snode_notify(), and ID::us.
Referenced by NODE_OT_delete().
static int node_delete_reconnect_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3349 of file node_edit.c.
References CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, ListBase::first, bNode::flag, bNode::id, bNode::next, next, nodeFreeNode(), nodeInternalRelink(), bNodeTree::nodes, ntreeUpdateTree(), OPERATOR_FINISHED, SELECT, snode_dag_update(), snode_notify(), and ID::us.
Referenced by NODE_OT_delete_reconnect().
static int node_duplicate_exec (bContext * C, wmOperator * op) [static]
Definition at line 2162 of file node_edit.c.
References BLI_addtail(), CTX_wm_space_node(), ED_node_changed_update(), ED_preview_kill_jobs(), SpaceNode::edittree, ListBase::first, bNodeLink::flag, bNode::flag, bNodeLink::fromnode, bNodeLink::fromsock, SpaceNode::id, bNode::id, id_us_plus(), ListBase::last, link(), bNodeTree::links, MEM_callocN(), bNode::new_node, bNodeSocket::new_sock, bNodeLink::next, bNode::next, NODE_ACTIVE, node_deselect(), node_select(), NODE_SELECT, nodeCopyNode(), bNodeTree::nodes, ntreeUpdateTree(), OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), SELECT, snode_dag_update(), snode_notify(), bNodeLink::tonode, and bNodeLink::tosock.
Referenced by NODE_OT_duplicate().
int node_find_indicated_socket (SpaceNode * snode, bNode ** nodep, bNodeSocket ** sockp, int in_out)
Definition at line 1808 of file node_edit.c.
References BLI_in_rctf(), SpaceNode::edittree, ListBase::first, bNode::flag, bNodeTree::inputs, bNode::inputs, bNodeSocket::locx, bNodeSocket::locy, SpaceNode::mx, SpaceNode::my, bNodeSocket::next, bNode::next, NODE_HIDDEN, NODE_SOCKSIZE, bNodeTree::nodes, nodeSocketIsHidden(), NULL, bNode::outputs, bNodeTree::outputs, SOCK_IN, SOCK_OUT, visible_node(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by node_link_init(), node_link_modal(), and node_mouse_select().
static void node_flag_toggle_exec (SpaceNode * snode, int toggle_flag) [static]
Definition at line 3086 of file node_edit.c.
References SpaceNode::edittree, ListBase::first, bNode::flag, bNodeType::flag, bNode::next, NODE_OPTIONS, NODE_PREVIEW, bNodeTree::nodes, SELECT, and bNode::typeinfo.
Referenced by node_hide_toggle_exec(), node_options_toggle_exec(), and node_preview_toggle_exec().
static void node_frame_attach_nodes (bNodeTree * UNUSEDntree, bNode * frame) [static]
Definition at line 704 of file node_edit.c.
References bNode::flag, inside_rctf(), bNode::next, NODE_SELECT, nodeAttachNode(), nodeDetachNode(), NULL, bNode::parent, and bNode::totr.
Referenced by ED_node_update_hierarchy().
static int node_group_edit_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 839 of file node_edit.c.
References CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, NC_SCENE, ND_NODES, nodeGetActive(), SpaceNode::nodetree, NULL, OPERATOR_FINISHED, snode_make_group_editable(), and WM_event_add_notifier().
Referenced by node_group_edit_invoke(), and NODE_OT_group_edit().
static int node_group_edit_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 857 of file node_edit.c.
References CTX_wm_space_node(), SpaceNode::edittree, GS, bNode::id, ID_NT, wmOperatorType::idname, ID::lib, ID::name, node_group_edit_exec(), nodeGetActive(), SpaceNode::nodetree, OPERATOR_CANCELLED, wmOperator::type, and uiPupMenuOkee().
Referenced by NODE_OT_group_edit().
static int node_group_make_exec (bContext * C, wmOperator * op) [static]
Definition at line 3027 of file node_edit.c.
References BKE_report(), CMP_NODE_R_LAYERS, CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, ListBase::first, bNode::flag, bNode::next, node_group_make_from_selected(), bNodeTree::nodes, nodeSetActive(), SpaceNode::nodetree, NTREE_COMPOSIT, ntreeUpdateTree(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_WARNING, SELECT, snode_dag_update(), snode_notify(), SpaceNode::treetype, and bNode::type.
Referenced by NODE_OT_group_make().
static int node_group_socket_add_exec (bContext * C, wmOperator * op) [static]
Definition at line 892 of file node_edit.c.
References CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, MAX_NAME, node_group_add_socket(), ntreeUpdateTree(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), RNA_string_get(), RNA_struct_property_is_set(), snode_notify(), and SOCK_FLOAT.
Referenced by NODE_OT_group_socket_add().
static int node_group_socket_move_down_exec (bContext * C, wmOperator * op) [static]
Definition at line 1066 of file node_edit.c.
References BLI_findlink(), BLI_insertlinkafter(), BLI_remlink(), CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, bNodeTree::inputs, bNodeSocket::next, next, NTREE_UPDATE_GROUP_IN, NTREE_UPDATE_GROUP_OUT, ntreeUpdateTree(), OPERATOR_CANCELLED, OPERATOR_FINISHED, bNodeTree::outputs, wmOperator::ptr, RNA_enum_get(), RNA_int_get(), RNA_struct_property_is_set(), snode_notify(), SOCK_IN, SOCK_OUT, and bNodeTree::update.
Referenced by NODE_OT_group_socket_move_down().
static int node_group_socket_move_up_exec (bContext * C, wmOperator * op) [static]
Definition at line 996 of file node_edit.c.
References BLI_findlink(), BLI_insertlinkbefore(), BLI_remlink(), CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, bNodeTree::inputs, NTREE_UPDATE_GROUP_IN, NTREE_UPDATE_GROUP_OUT, ntreeUpdateTree(), OPERATOR_CANCELLED, OPERATOR_FINISHED, bNodeTree::outputs, bNodeSocket::prev, wmOperator::ptr, RNA_enum_get(), RNA_int_get(), RNA_struct_property_is_set(), snode_notify(), SOCK_IN, SOCK_OUT, and bNodeTree::update.
Referenced by NODE_OT_group_socket_move_up().
static int node_group_socket_remove_exec (bContext * C, wmOperator * op) [static]
Definition at line 945 of file node_edit.c.
References BLI_findlink(), CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, bNodeTree::inputs, node_group_remove_socket(), ntreeUpdateTree(), OPERATOR_CANCELLED, OPERATOR_FINISHED, bNodeTree::outputs, wmOperator::ptr, RNA_enum_get(), RNA_int_get(), RNA_struct_property_is_set(), snode_notify(), and SOCK_IN.
Referenced by NODE_OT_group_socket_remove().
static int node_group_ungroup_exec (bContext * C, wmOperator * op) [static]
Definition at line 1136 of file node_edit.c.
References BKE_report(), CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, NODE_GROUP, node_group_ungroup(), node_tree_get_editgroup(), nodeGetActive(), SpaceNode::nodetree, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_WARNING, snode_dag_update(), snode_make_group_editable(), snode_notify(), and bNode::type.
Referenced by NODE_OT_group_ungroup().
int node_has_hidden_sockets (bNode * node)
Definition at line 1610 of file node_edit.c.
References ListBase::first, bNodeSocket::flag, bNode::inputs, bNodeSocket::next, bNode::outputs, and SOCK_HIDDEN.
Referenced by node_socket_toggle_exec().
static int node_hide_toggle_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3125 of file node_edit.c.
References CTX_wm_space_node(), SpaceNode::edittree, node_flag_toggle_exec(), NODE_HIDDEN, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, and snode_notify().
Referenced by NODE_OT_hide_toggle().
static int node_link_cancel (bContext * C, wmOperator * op) [static]
Definition at line 2560 of file node_edit.c.
References BLI_remlink(), CTX_wm_space_node(), wmOperator::customdata, SpaceNode::edittree, bNodeLinkDrag::link, SpaceNode::linkdrag, MEM_freeN(), nodeRemLink(), and OPERATOR_CANCELLED.
Referenced by NODE_OT_link().
static int node_link_init (SpaceNode * snode, bNodeLinkDrag * nldrag) [static]
Definition at line 2458 of file node_edit.c.
References SpaceNode::edittree, ListBase::first, bNodeLink::fromnode, bNodeLink::fromsock, bNodeSocket::limit, link(), bNodeTree::links, bNodeLink::next, bNodeLinkDrag::node, node_deselect_all_input_sockets(), node_deselect_all_output_sockets(), node_find_indicated_socket(), node_socket_select(), nodeCountSocketLinks(), nodeRemLink(), snode_update(), bNodeLinkDrag::sock, SOCK_IN, SOCK_OUT, bNodeLink::tonode, and bNodeLink::tosock.
Referenced by node_link_invoke().
static int node_link_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2515 of file node_edit.c.
References BLI_addtail(), CTX_wm_region(), CTX_wm_space_node(), wmOperator::customdata, ED_preview_kill_jobs(), bNodeLink::fromnode, bNodeLink::fromsock, bNodeLinkDrag::in_out, bNodeLinkDrag::link, SpaceNode::linkdrag, MEM_callocN(), MEM_freeN(), wmEvent::mval, SpaceNode::mx, SpaceNode::my, bNodeLinkDrag::node, node_link_init(), NULL, OPERATOR_CANCELLED, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, bNodeLinkDrag::sock, SOCK_OUT, bNodeLink::tonode, bNodeLink::tosock, UI_view2d_region_to_view(), ARegion::v2d, and WM_event_add_modal_handler().
Referenced by NODE_OT_link().
static int node_link_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2305 of file node_edit.c.
References BLI_addtail(), BLI_remlink(), CTX_wm_region(), CTX_wm_space_node(), wmOperator::customdata, ED_region_tag_redraw(), SpaceNode::edittree, bNodeLink::fromnode, bNodeLink::fromsock, bNodeLinkDrag::in_out, LEFTMOUSE, bNodeSocket::limit, bNodeLinkDrag::link, link(), SpaceNode::linkdrag, bNodeTree::links, MEM_freeN(), MIDDLEMOUSE, MOUSEMOVE, wmEvent::mval, SpaceNode::mx, SpaceNode::my, bNodeLink::next, bNodeLinkDrag::node, node_deselect_all_input_sockets(), node_deselect_all_output_sockets(), node_find_indicated_socket(), node_group_expose_socket(), node_remove_extra_links(), node_socket_select(), nodeCountSocketLinks(), nodeFindLink(), nodeRemLink(), NTREE_UPDATE_GROUP_IN, NTREE_UPDATE_GROUP_OUT, NTREE_UPDATE_LINKS, ntreeUpdateTree(), NULL, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, outside_group_rect(), bNodeLink::prev, RIGHTMOUSE, snode_dag_update(), snode_notify(), snode_update(), bNodeLinkDrag::sock, SOCK_IN, SOCK_OUT, bNodeLink::tonode, bNodeLink::tosock, bNodeSocket::type, wmEvent::type, UI_view2d_region_to_view(), bNodeTree::update, and ARegion::v2d.
Referenced by NODE_OT_link().
static int node_link_viewer (const bContext * C, bNode * tonode) [static]
Definition at line 1646 of file node_edit.c.
References CMP_NODE_SPLITVIEWER, CMP_NODE_VIEWER, CTX_data_main(), CTX_data_scene(), CTX_wm_space_node(), SpaceNode::edittree, ELEM, ListBase::first, bNode::flag, bNodeLink::fromnode, bNodeLink::fromsock, bNode::inputs, link(), bNodeTree::links, bNodeSocket::locx, bNodeSocket::locy, bNodeSocket::next, bNodeLink::next, bNode::next, node_add_node(), NODE_DO_OUTPUT, nodeAddLink(), nodeRemLink(), bNodeTree::nodes, nodeSocketIsHidden(), ntreeUpdateTree(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, bNode::outputs, snode_update(), bNodeLink::tonode, bNodeLink::tosock, bNodeTemplate::type, and bNode::type.
Referenced by node_active_link_viewer().
static int node_make_link_exec (bContext * C, wmOperator * op) [static]
Definition at line 2592 of file node_edit.c.
References CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, node_deselect_all_input_sockets(), node_deselect_all_output_sockets(), ntreeUpdateTree(), OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), snode_autoconnect(), snode_dag_update(), and snode_notify().
Referenced by NODE_OT_link_make().
static int UNUSED_FUNCTION() node_mouse_groupheader (SpaceNode * snode) [static]
Definition at line 1779 of file node_edit.c.
References BLI_in_rctf(), NODE_DY, node_tree_get_editgroup(), NULL, snode_make_group_editable(), bNode::totr, and rctf::ymax.
static int node_mute_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3270 of file node_edit.c.
References CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, ListBase::first, bNode::flag, bNodeType::internal_connect, bNode::next, NODE_MUTED, bNodeTree::nodes, OPERATOR_FINISHED, SELECT, snode_dag_update(), snode_notify(), snode_update(), and bNode::typeinfo.
Referenced by NODE_OT_mute_toggle().
static int node_options_toggle_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3187 of file node_edit.c.
References CTX_wm_space_node(), SpaceNode::edittree, node_flag_toggle_exec(), NODE_OPTIONS, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, and snode_notify().
Referenced by NODE_OT_options_toggle().
void NODE_OT_add_file (wmOperatorType * ot)
Definition at line 3503 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, IMAGEFILE, wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::name, node_add_file_exec(), node_add_file_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string(), wmOperatorType::srna, WM_FILESEL_FILEPATH, and WM_operator_properties_filesel().
Referenced by node_operatortypes().
void NODE_OT_backimage_move (wmOperatorType * ot)
Definition at line 1283 of file node_edit.c.
References wmOperatorType::cancel, composite_node_active(), wmOperatorType::description, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, wmOperatorType::poll, snode_bg_viewmove_cancel(), snode_bg_viewmove_invoke(), and snode_bg_viewmove_modal().
Referenced by node_operatortypes().
void NODE_OT_backimage_sample (wmOperatorType * ot)
Definition at line 1480 of file node_edit.c.
References wmOperatorType::cancel, ED_operator_node_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, sample_cancel(), sample_invoke(), and sample_modal().
Referenced by node_operatortypes().
void NODE_OT_backimage_zoom (wmOperatorType * ot)
Definition at line 1313 of file node_edit.c.
References backimage_zoom(), composite_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, RNA_def_float(), and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_delete (wmOperatorType * ot)
Definition at line 3333 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_delete_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_delete_reconnect (wmOperatorType * ot)
Definition at line 3376 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_delete_reconnect_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_duplicate (wmOperatorType * ot)
Definition at line 2248 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_duplicate_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_group_edit (wmOperatorType * ot)
Definition at line 874 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, node_group_edit_exec(), node_group_edit_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_group_make (wmOperatorType * ot)
Definition at line 3069 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_group_make_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_group_socket_add (wmOperatorType * ot)
Definition at line 924 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAX_NAME, wmOperatorType::name, node_group_socket_add_exec(), node_socket_type_items, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_string(), SOCK_FLOAT, SOCK_IN, and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_group_socket_move_down (wmOperatorType * ot)
Definition at line 1116 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_group_socket_move_down_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_int(), SOCK_IN, and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_group_socket_move_up (wmOperatorType * ot)
Definition at line 1046 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_group_socket_move_up_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_int(), SOCK_IN, and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_group_socket_remove (wmOperatorType * ot)
Definition at line 976 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_group_socket_remove_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_int(), SOCK_IN, and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_group_ungroup (wmOperatorType * ot)
Definition at line 1167 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_group_ungroup_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_hide_socket_toggle (wmOperatorType * ot)
Definition at line 3253 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_socket_toggle_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_hide_toggle (wmOperatorType * ot)
Definition at line 3140 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_hide_toggle_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_link (wmOperatorType * ot)
Definition at line 2572 of file node_edit.c.
References wmOperatorType::cancel, ED_operator_node_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, node_link_cancel(), node_link_invoke(), node_link_modal(), OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_link_make (wmOperatorType * ot)
Definition at line 2612 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_make_link_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_link_viewer (wmOperatorType * ot)
Definition at line 1761 of file node_edit.c.
References composite_node_active(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_active_link_viewer(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_links_cut (wmOperatorType * ot)
Definition at line 2689 of file node_edit.c.
References BC_KNIFECURSOR, wmOperatorType::cancel, cut_links_exec(), ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_COLLECTION, PROP_NONE, RNA_def_int(), RNA_def_property(), RNA_def_property_struct_runtime(), RNA_OperatorMousePath, wmOperatorType::srna, WM_gesture_lines_cancel(), WM_gesture_lines_invoke(), and WM_gesture_lines_modal().
Referenced by node_operatortypes().
void NODE_OT_links_detach (wmOperatorType * ot)
Definition at line 2736 of file node_edit.c.
References detach_links_exec(), ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_mute_toggle (wmOperatorType * ot)
Definition at line 3291 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_mute_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_new_node_tree (wmOperatorType * ot)
Definition at line 3570 of file node_edit.c.
References ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAX_ID_NAME, wmOperatorType::name, new_node_tree_exec(), nodetree_type_items, NTREE_COMPOSIT, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_string(), and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_options_toggle (wmOperatorType * ot)
Definition at line 3202 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_options_toggle_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_output_file_add_socket (wmOperatorType * ot)
Definition at line 3608 of file node_edit.c.
References composite_node_active(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAX_NAME, wmOperatorType::name, node_output_file_add_socket_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string(), and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_output_file_remove_active_socket (wmOperatorType * ot)
Definition at line 3644 of file node_edit.c.
References composite_node_active(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_output_file_remove_active_socket_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_preview_toggle (wmOperatorType * ot)
Definition at line 3172 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_preview_toggle_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_read_fullsamplelayers (wmOperatorType * ot)
Definition at line 2962 of file node_edit.c.
References composite_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_read_fullsamplelayers_exec(), and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_read_renderlayers (wmOperatorType * ot)
Definition at line 2929 of file node_edit.c.
References composite_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_read_renderlayers_exec(), and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_render_changed (wmOperatorType * ot)
Definition at line 3010 of file node_edit.c.
References composite_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_render_changed_exec(), and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_resize (wmOperatorType * ot)
Definition at line 1591 of file node_edit.c.
References wmOperatorType::cancel, ED_operator_node_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, node_resize_cancel(), node_resize_invoke(), node_resize_modal(), OPTYPE_BLOCKING, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_show_cyclic_dependencies (wmOperatorType * ot)
Definition at line 3404 of file node_edit.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_show_cycles_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
static int node_output_file_add_socket_exec (bContext * C, wmOperator * op) [static]
Definition at line 3589 of file node_edit.c.
References CTX_data_scene(), CTX_wm_space_node(), SpaceNode::edittree, RenderData::im_format, MAX_NAME, nodeGetActive(), ntreeCompositOutputFileAddSocket(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, Scene::r, RNA_string_get(), and snode_notify().
Referenced by NODE_OT_output_file_add_socket().
static int node_output_file_remove_active_socket_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3627 of file node_edit.c.
References CTX_wm_space_node(), SpaceNode::edittree, nodeGetActive(), ntreeCompositOutputFileRemoveActiveSocket(), OPERATOR_CANCELLED, OPERATOR_FINISHED, and snode_notify().
Referenced by NODE_OT_output_file_remove_active_socket().
static int node_preview_toggle_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3155 of file node_edit.c.
References CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, node_flag_toggle_exec(), NODE_PREVIEW, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, and snode_notify().
Referenced by NODE_OT_preview_toggle().
static int node_read_fullsamplelayers_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2943 of file node_edit.c.
References CTX_data_main(), CTX_data_scene(), CTX_wm_space_node(), Scene::id, ID::name, NC_SCENE, ND_COMPO_RESULT, SpaceNode::nodetree, NULL, OPERATOR_FINISHED, RE_MergeFullSample(), RE_NewRender(), WM_cursor_wait(), and WM_event_add_notifier().
Referenced by NODE_OT_read_fullsamplelayers().
static int node_read_renderlayers_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2899 of file node_edit.c.
References CMP_NODE_R_LAYERS, CTX_data_main(), CTX_data_scene(), CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, ListBase::first, ID::flag, bNode::id, LIB_DOIT, bNode::next, bNodeTree::nodes, ntreeCompositTagRender(), OPERATOR_FINISHED, RE_ReadRenderResult(), Main::scene, snode_dag_update(), snode_notify(), and bNode::type.
Referenced by NODE_OT_read_renderlayers().
static void node_remove_extra_links (SpaceNode * snode, bNodeSocket * tsock, bNodeLink * link) [static]
Definition at line 2267 of file node_edit.c.
References SpaceNode::edittree, ListBase::first, bNodeSocket::flag, bNode::inputs, bNodeSocket::limit, bNodeTree::links, bNodeSocket::next, bNodeLink::next, nodeCountSocketLinks(), nodeRemLink(), NTREE_UPDATE_LINKS, SOCK_HIDDEN, bNodeLink::tonode, bNodeLink::tosock, bNodeSocket::type, and bNodeTree::update.
Referenced by node_link_modal().
int node_render_changed_exec (bContext * C, wmOperator * UNUSEDop)
Definition at line 2976 of file node_edit.c.
References BLI_findlink(), CTX_data_scene(), bNode::custom1, ListBase::first, Scene::id, bNode::id, RenderData::layers, ID::name, SceneRenderLayer::name, bNode::need_exec, bNode::next, bNodeTree::nodes, Scene::nodetree, OPERATOR_CANCELLED, OPERATOR_FINISHED, Scene::r, R_NO_FRAME_UPDATE, RNA_string_set(), RenderData::scemode, WM_OP_INVOKE_DEFAULT, WM_operator_name_call(), WM_operator_properties_create(), and WM_operator_properties_free().
Referenced by node_area_refresh(), and NODE_OT_render_changed().
static int node_resize_cancel (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 1583 of file node_edit.c.
References wmOperator::customdata, MEM_freeN(), NULL, and OPERATOR_CANCELLED.
Referenced by NODE_OT_resize().
static int node_resize_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1551 of file node_edit.c.
References CTX_wm_region(), CTX_wm_space_node(), wmOperator::customdata, editnode_get_active(), SpaceNode::edittree, bNode::height, MEM_callocN(), bNode::miniwidth, wmEvent::mval, SpaceNode::mx, NodeSizeWidget::mxstart, SpaceNode::my, NodeSizeWidget::mystart, NodeSizeWidget::oldheight, NodeSizeWidget::oldminiwidth, NodeSizeWidget::oldwidth, OPERATOR_CANCELLED, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, bNodeType::resize_area_func, bNode::typeinfo, UI_view2d_region_to_view(), ARegion::v2d, bNode::width, and WM_event_add_modal_handler().
Referenced by NODE_OT_resize().
static int node_resize_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1504 of file node_edit.c.
References CLAMP(), CTX_wm_region(), CTX_wm_space_node(), wmOperator::customdata, ED_node_update_hierarchy(), ED_region_tag_redraw(), editnode_get_active(), SpaceNode::edittree, bNode::flag, bNode::height, LEFTMOUSE, bNodeType::maxheight, bNodeType::maxwidth, MEM_freeN(), MIDDLEMOUSE, bNodeType::minheight, bNode::miniwidth, bNodeType::minwidth, MOUSEMOVE, wmEvent::mval, NodeSizeWidget::mxstart, NodeSizeWidget::mystart, NODE_HIDDEN, NULL, NodeSizeWidget::oldheight, NodeSizeWidget::oldminiwidth, NodeSizeWidget::oldwidth, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, RIGHTMOUSE, wmEvent::type, bNode::typeinfo, UI_DPI_FAC, UI_view2d_region_to_view(), ARegion::v2d, and bNode::width.
Referenced by NODE_OT_resize().
void node_set_hidden_sockets (SpaceNode * snode, bNode * node, int set)
Definition at line 1623 of file node_edit.c.
References SpaceNode::edittree, ListBase::first, bNodeSocket::flag, bNode::inputs, bNodeSocket::link, bNodeSocket::next, nodeCountSocketLinks(), NULL, bNode::outputs, and SOCK_HIDDEN.
Referenced by node_socket_toggle_exec().
static int node_show_cycles_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3393 of file node_edit.c.
References CTX_wm_space_node(), SpaceNode::nodetree, ntreeUpdateTree(), OPERATOR_FINISHED, and snode_notify().
Referenced by NODE_OT_show_cyclic_dependencies().
static int node_socket_toggle_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3217 of file node_edit.c.
References CTX_wm_space_node(), ED_preview_kill_jobs(), SpaceNode::edittree, ListBase::first, bNode::flag, bNode::next, node_has_hidden_sockets(), node_set_hidden_sockets(), bNodeTree::nodes, ntreeUpdateTree(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, SELECT, and snode_notify().
Referenced by NODE_OT_hide_socket_toggle().
void node_tree_from_ID (ID * id, bNodeTree ** ntree, bNodeTree ** edittree, int * treetype)
Definition at line 437 of file node_edit.c.
References GS, bNode::id, ID_LA, ID_MA, ID_NT, ID_SCE, ID_TE, ID_WO, ID::name, bNode::next, nodeGroupEditGet(), NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, NULL, and bNodeTree::type.
Referenced by ED_node_changed_update(), and snode_set_context().
bNode* node_tree_get_editgroup (bNodeTree * nodetree)
Definition at line 263 of file node_edit.c.
References ListBase::first, bNode::next, nodeGroupEditGet(), and bNodeTree::nodes.
Referenced by ED_node_changed_update(), node_add_node(), node_group_ungroup_exec(), node_mouse_groupheader(), outside_group_rect(), and snode_update().
static int outside_group_rect (SpaceNode * snode) [static]
Definition at line 1894 of file node_edit.c.
References SpaceNode::mx, SpaceNode::my, node_tree_get_editgroup(), SpaceNode::nodetree, bNode::totr, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by node_link_modal().
static void sample_apply (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1357 of file node_edit.c.
References BKE_image_acquire_ibuf(), BKE_image_release_ibuf(), BKE_image_verify_viewer(), ImBuf::channels, ImageSampleInfo::channels, CLAMP(), ImageSampleInfo::col, ImageSampleInfo::colf, ImageSampleInfo::color_manage, CTX_wm_area(), CTX_wm_region(), CTX_wm_space_node(), wmOperator::customdata, ImageSampleInfo::draw, ED_area_tag_redraw(), IB_PROFILE_LINEAR_RGB, IB_PROFILE_NONE, IMA_TYPE_COMPOSITE, IMB_rect_from_float(), wmEvent::mval, NULL, ImBuf::profile, ImBuf::rect, ImBuf::rect_float, ARegion::winx, ARegion::winy, ImageSampleInfo::x, ImBuf::x, SpaceNode::xof, ImageSampleInfo::y, ImBuf::y, SpaceNode::yof, and SpaceNode::zoom.
Referenced by sample_invoke(), and sample_modal().
static int sample_cancel (bContext * C, wmOperator * op) [static]
Definition at line 1474 of file node_edit.c.
References OPERATOR_CANCELLED, and sample_exit().
Referenced by NODE_OT_backimage_sample().
static void sample_draw (const bContext * C, ARegion * ar, void * arg_info) [static]
Definition at line 1346 of file node_edit.c.
References ImageSampleInfo::channels, ImageSampleInfo::col, ImageSampleInfo::colf, RenderData::color_mgt_flag, CTX_data_scene(), ED_image_draw_info(), NULL, Scene::r, R_COLOR_MANAGEMENT, ImageSampleInfo::x, and ImageSampleInfo::y.
Referenced by sample_invoke().
static void sample_exit (bContext * C, wmOperator * op) [static]
Definition at line 1429 of file node_edit.c.
References ImageSampleInfo::art, CTX_wm_area(), wmOperator::customdata, ImageSampleInfo::draw_handle, ED_area_tag_redraw(), ED_region_draw_cb_exit(), and MEM_freeN().
Referenced by sample_cancel(), and sample_modal().
static int sample_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1438 of file node_edit.c.
References ImageSampleInfo::art, CTX_wm_region(), CTX_wm_space_node(), wmOperator::customdata, ImageSampleInfo::draw_handle, ED_region_draw_cb_activate(), SpaceNode::flag, MEM_callocN(), NTREE_COMPOSIT, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, REGION_DRAW_POST_PIXEL, sample_apply(), sample_draw(), SNODE_BACKDRAW, SpaceNode::treetype, ARegion::type, and WM_event_add_modal_handler().
Referenced by NODE_OT_backimage_sample().
static int sample_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1459 of file node_edit.c.
References LEFTMOUSE, MOUSEMOVE, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, RIGHTMOUSE, sample_apply(), sample_exit(), and wmEvent::type.
Referenced by NODE_OT_backimage_sample().
void snode_autoconnect (SpaceNode * snode, int allow_multiple, int replace)
Definition at line 2033 of file node_edit.c.
References best_socket_input(), best_socket_output(), BLI_addtail(), BLI_countlist(), BLI_freelistN(), BLI_sortlist(), SpaceNode::edittree, ListBase::first, bNode::flag, bNodeSocket::flag, i, bNode::inputs, MEM_callocN(), MEM_freeN(), MEM_mallocN(), bNodeSocket::next, bNode::next, bNodeListItem::next, bNodeListItem::node, NODE_SELECT, bNodeTree::nodes, ntreeUpdateTree(), NULL, SELECT, snode_autoconnect_input(), socket_is_available(), and sort_nodes_locx().
Referenced by node_make_link_exec().
static int snode_autoconnect_input (SpaceNode * snode, bNode * node_fr, bNodeSocket * sock_fr, bNode * node_to, bNodeSocket * sock_to, int replace) [static]
Definition at line 2012 of file node_edit.c.
References SpaceNode::edittree, bNodeLink::flag, link(), NODE_LINK_VALID, nodeAddLink(), nodeRemLink(), nodeRemSocketLinks(), ntreeUpdateTree(), and snode_update().
Referenced by snode_autoconnect().
static int snode_bg_viewmove_cancel (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 1275 of file node_edit.c.
References wmOperator::customdata, MEM_freeN(), NULL, and OPERATOR_CANCELLED.
Referenced by NODE_OT_backimage_move().
static int snode_bg_viewmove_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1240 of file node_edit.c.
References BKE_image_acquire_ibuf(), BKE_image_release_ibuf(), BKE_image_verify_viewer(), CTX_wm_region(), wmOperator::customdata, IMA_TYPE_COMPOSITE, MEM_callocN(), NodeViewMove::mvalo, NULL, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, ARegion::winx, ARegion::winy, WM_event_add_modal_handler(), ImBuf::x, NodeViewMove::xmax, NodeViewMove::xmin, ImBuf::y, NodeViewMove::ymax, and NodeViewMove::ymin.
Referenced by NODE_OT_backimage_move().
static int snode_bg_viewmove_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1203 of file node_edit.c.
References CLAMP(), CTX_wm_region(), CTX_wm_space_node(), wmOperator::customdata, ED_region_tag_redraw(), LEFTMOUSE, MEM_freeN(), MIDDLEMOUSE, MOUSEMOVE, NodeViewMove::mvalo, NC_SPACE, ND_SPACE_NODE, NULL, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, RIGHTMOUSE, wmEvent::type, WM_event_add_notifier(), NodeViewMove::xmax, NodeViewMove::xmin, SpaceNode::xof, NodeViewMove::ymax, NodeViewMove::ymin, and SpaceNode::yof.
Referenced by NODE_OT_backimage_move().
void snode_composite_job (const bContext * C, ScrArea * sa)
Definition at line 196 of file node_edit.c.
References compo_freejob(), compo_initjob(), compo_startjob(), compo_updatejob(), CTX_data_scene(), CTX_wm_manager(), CTX_wm_window(), ListBase::first, MEM_callocN(), NC_SCENE, ND_COMPO_RESULT, SpaceNode::nodetree, CompoJob::ntree, NULL, CompoJob::scene, ScrArea::spacedata, WM_JOB_EXCL_RENDER, WM_JOB_PROGRESS, WM_jobs_callbacks(), WM_jobs_customdata(), WM_jobs_get(), WM_jobs_start(), and WM_jobs_timer().
Referenced by node_area_refresh().
void snode_dag_update (bContext * UNUSEDC, SpaceNode * snode)
Definition at line 246 of file node_edit.c.
References DAG_id_tag_update(), and SpaceNode::id.
Referenced by cut_links_exec(), detach_links_exec(), do_node_add(), node_add_file_exec(), node_delete_exec(), node_delete_reconnect_exec(), node_duplicate_exec(), node_group_make_exec(), node_group_ungroup_exec(), node_link_modal(), node_make_link_exec(), node_mute_exec(), and node_read_renderlayers_exec().
void snode_make_group_editable (SpaceNode * snode, bNode * gnode)
Definition at line 813 of file node_edit.c.
References SpaceNode::edittree, ListBase::first, bNode::next, node_deselect(), node_select(), nodeGetActive(), nodeGroupEditClear(), nodeGroupEditSet(), bNodeTree::nodes, SpaceNode::nodetree, and NULL.
Referenced by node_group_edit_exec(), node_group_ungroup_exec(), and node_mouse_groupheader().
void snode_notify (bContext * C, SpaceNode * snode)
Definition at line 251 of file node_edit.c.
References SpaceNode::id, NA_EDITED, NC_MATERIAL, NC_NODE, NC_SCENE, NC_TEXTURE, ND_NODES, NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, NULL, SpaceNode::treetype, and WM_event_add_notifier().
Referenced by cut_links_exec(), detach_links_exec(), do_node_add(), node_active_link_viewer(), node_add_file_exec(), node_delete_exec(), node_delete_reconnect_exec(), node_duplicate_exec(), node_group_make_exec(), node_group_socket_add_exec(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_socket_remove_exec(), node_group_ungroup_exec(), node_hide_toggle_exec(), node_link_modal(), node_make_link_exec(), node_mute_exec(), node_options_toggle_exec(), node_output_file_add_socket_exec(), node_output_file_remove_active_socket_exec(), node_preview_toggle_exec(), node_read_renderlayers_exec(), node_show_cycles_exec(), and node_socket_toggle_exec().
void snode_set_context (SpaceNode * snode, Scene * scene)
Definition at line 493 of file node_edit.c.
References Object::actcol, Object::data, SpaceNode::edittree, SpaceNode::from, give_current_brush_texture(), give_current_material(), give_current_object_texture(), give_current_world_texture(), bNodeTree::id, Tex::id, Scene::id, World::id, Material::id, Object::id, SpaceNode::id, ToolSettings::imapaint, Object::mode, node_tree_from_ID(), SpaceNode::nodetree, Scene::nodetree, NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, ntreeCompositForceHidden(), NULL, OB_LAMP, OB_MODE_SCULPT, OBACT, ImagePaintSettings::paint, Sculpt::paint, paint_brush(), ToolSettings::sculpt, SpaceNode::shaderfrom, SNODE_SHADER_OBJECT, SNODE_TEX_OBJECT, SNODE_TEX_WORLD, SpaceNode::texfrom, Scene::toolsettings, SpaceNode::treetype, bNodeTree::type, Object::type, and Scene::world.
Referenced by drawnodespace(), ED_node_tree_update(), node_area_refresh(), and node_header_area_draw().
static void snode_update (SpaceNode * snode, bNode * node) [static]
Definition at line 575 of file node_edit.c.
References SpaceNode::edittree, bNode::id, node_tree_get_editgroup(), SpaceNode::nodetree, nodeUpdate(), and nodeUpdateID().
Referenced by cut_links_exec(), ED_node_link_insert(), node_add_node(), node_link_init(), node_link_modal(), node_link_viewer(), node_mute_exec(), and snode_autoconnect_input().
static bNodeSocket* socket_best_match (ListBase * sockets) [static]
Definition at line 2751 of file node_edit.c.
References ListBase::first, bNodeSocket::flag, MAX2, bNodeSocket::next, nodeSocketIsHidden(), NULL, SOCK_HIDDEN, bNodeSocket::type, and bNode::type.
Referenced by ED_node_link_insert().
static int socket_is_available (bNodeTree * UNUSEDntree, bNodeSocket * sock, int allow_used) [static]
Definition at line 1927 of file node_edit.c.
References bNodeSocket::flag, nodeSocketIsHidden(), and SOCK_IN_USE.
Referenced by best_socket_input(), best_socket_output(), and snode_autoconnect().
static int sort_nodes_locx (void * a, void * b) [static]
Definition at line 1914 of file node_edit.c.
References bNode::locx, and bNodeListItem::node.
Referenced by snode_autoconnect().
static bNode* visible_node (SpaceNode * snode, rctf * rct) [static]
Definition at line 1185 of file node_edit.c.
References BLI_isect_rctf(), SpaceNode::edittree, ListBase::last, bNodeTree::nodes, NULL, bNode::prev, and bNode::totr.
Referenced by node_find_indicated_socket().
Variable Documentation
EnumPropertyItem socket_in_out_items[] [static]
Initial value:
 {
    { SOCK_IN, "SOCK_IN", 0, "Input", "" },
    { SOCK_OUT, "SOCK_OUT", 0, "Output", "" },
    { 0, NULL, 0, NULL, NULL },
}
Definition at line 98 of file node_edit.c.