Blender: openexr_api.cpp File Reference
openexr_api.cpp File Reference
OpenEXR
#include <stdlib.h>
#include <stdio.h>
#include <stddef.h>
#include <string>
#include <set>
#include <openexr_api.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math_color.h"
#include "BLI_threads.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_allocimbuf.h"
#include "IMB_metadata.h"
#include "openexr_multi.h"
#include <iostream>
#include <half.h>
#include <ImfVersion.h>
#include <ImathBox.h>
#include <ImfArray.h>
#include <ImfIO.h>
#include <ImfChannelList.h>
#include <ImfPixelType.h>
#include <ImfInputFile.h>
#include <ImfOutputFile.h>
#include <ImfCompression.h>
#include <ImfCompressionAttribute.h>
#include <ImfStringAttribute.h>
Classes
class Mem_IStream
struct _RGBAZ
struct ExrHandle
struct ExrChannel
struct ExrPass
struct ExrLayer
struct RGBA
Typedefs
typedef struct _RGBAZ RGBAZ
typedef struct ExrHandle ExrHandle
typedef struct ExrChannel ExrChannel
typedef struct ExrPass ExrPass
typedef struct ExrLayer ExrLayer
typedef struct RGBA RGBA
Functions
int imb_is_a_openexr (unsigned char *mem)
static void openexr_header_compression (Header *header, int compression)
static void openexr_header_metadata (Header *header, struct ImBuf *ibuf)
static int imb_save_openexr_half (struct ImBuf *ibuf, const char *name, int flags)
static int imb_save_openexr_float (struct ImBuf *ibuf, const char *name, int flags)
int imb_save_openexr (struct ImBuf *ibuf, const char *name, int flags)
void * IMB_exr_get_handle (void)
void IMB_exr_add_channel (void *handle, const char *layname, const char *passname, int xstride, int ystride, float *rect)
int IMB_exr_begin_write (void *handle, const char *filename, int width, int height, int compress)
void IMB_exrtile_begin_write (void *handle, const char *filename, int mipmap, int width, int height, int tilex, int tiley)
int IMB_exr_begin_read (void *handle, const char *filename, int *width, int *height)
void IMB_exr_set_channel (void *handle, const char *layname, const char *passname, int xstride, int ystride, float *rect)
void IMB_exrtile_clear_channels (void *handle)
void IMB_exrtile_write_channels (void *handle, int partx, int party, int level)
void IMB_exr_write_channels (void *handle)
void IMB_exr_read_channels (void *handle)
void IMB_exr_multilayer_convert (void *handle, void *base, void *(*addlayer)(void *base, char *str), void(*addpass)(void *base, void *lay, char *str, float *rect, int totchan, char *chan_id))
void IMB_exr_close (void *handle)
static int imb_exr_split_channel_name (ExrChannel *echan, char *layname, char *passname)
static ExrLayer * imb_exr_get_layer (ListBase *lb, char *layname)
static ExrPass * imb_exr_get_pass (ListBase *lb, char *passname)
static ExrHandle * imb_exr_begin_read_mem (InputFile *file, int width, int height)
static void exr_print_filecontents (InputFile *file)
static const char * exr_rgba_channelname (InputFile *file, const char *chan)
static int exr_has_zbuffer (InputFile *file)
static int exr_is_multilayer (InputFile *file)
struct ImBuf * imb_load_openexr (unsigned char *mem, size_t size, int flags)
void imb_initopenexr (void)
Variables
static ListBase exrhandles = {NULL, NULL}
Detailed Description
Definition in file openexr_api.cpp.
Typedef Documentation
typedef struct ExrChannel ExrChannel
typedef struct ExrHandle ExrHandle
typedef struct ExrLayer ExrLayer
typedef struct ExrPass ExrPass
typedef struct RGBA RGBA
typedef struct _RGBAZ RGBAZ
Definition at line 153 of file openexr_api.cpp.
Function Documentation
static int exr_has_zbuffer (InputFile * file) [static]
Definition at line 944 of file openexr_api.cpp.
References NULL.
Referenced by imb_load_openexr().
static int exr_is_multilayer (InputFile * file) [static]
Definition at line 949 of file openexr_api.cpp.
Referenced by imb_load_openexr().
static void exr_print_filecontents (InputFile * file) [static]
Definition at line 912 of file openexr_api.cpp.
References i.
Referenced by imb_load_openexr().
static const char* exr_rgba_channelname (InputFile * file, const char * chan) [static]
Definition at line 924 of file openexr_api.cpp.
References BLI_strcasecmp(), i, len(), str, and strlen().
Referenced by imb_load_openexr().
void IMB_exr_add_channel (void * handle, const char * layname, const char * passname, int xstride, int ystride, float * rect)
Definition at line 449 of file openexr_api.cpp.
Referenced by exec_output_file_multilayer(), IMB_exr_begin_read(), imb_exr_begin_read_mem(), RE_WriteRenderResult(), render_layer_add_pass(), and render_result_new().
int IMB_exr_begin_read (void * handle, const char * filename, int * width, int * height)
Definition at line 530 of file openexr_api.cpp.
Referenced by render_result_exr_file_read_path().
static ExrHandle* imb_exr_begin_read_mem (InputFile * file, int width, int height) [static]
Definition at line 801 of file openexr_api.cpp.
References ExrPass::chan, ExrChannel::chan_id, ExrPass::chan_id, ExrHandle::channels, data, EXR_PASS_MAXCHAN, EXR_TOT_MAXNAME, ListBase::first, ExrHandle::height, i, ExrHandle::ifile, IMB_exr_add_channel(), IMB_exr_close(), IMB_exr_get_handle(), imb_exr_get_layer(), imb_exr_get_pass(), imb_exr_split_channel_name(), ExrHandle::layers, MEM_mapallocN(), ExrChannel::name, ExrPass::next, ExrLayer::next, ExrChannel::next, NULL, ExrLayer::passes, ExrChannel::rect, ExrPass::rect, ExrPass::totchan, ExrHandle::width, ExrChannel::xstride, and ExrChannel::ystride.
Referenced by imb_load_openexr().
int IMB_exr_begin_write (void * handle, const char * filename, int width, int height, int compress)
Definition at line 475 of file openexr_api.cpp.
Referenced by exec_output_file_multilayer(), and RE_WriteRenderResult().
void IMB_exr_close (void * handle)
Definition at line 698 of file openexr_api.cpp.
Referenced by exec_output_file_multilayer(), image_create_multilayer(), imb_exr_begin_read_mem(), RE_WriteRenderResult(), render_result_exr_file_end(), and render_result_exr_file_read_path().
void* IMB_exr_get_handle (void)
Definition at line 440 of file openexr_api.cpp.
Referenced by exec_output_file_multilayer(), imb_exr_begin_read_mem(), RE_WriteRenderResult(), render_result_exr_file_read_path(), and render_result_new().
static ExrLayer* imb_exr_get_layer (ListBase * lb, char * layname) [static]
Definition at line 769 of file openexr_api.cpp.
References BLI_addtail(), BLI_findstring(), BLI_strncpy(), EXR_LAY_MAXNAME, MEM_callocN(), ExrLayer::name, and NULL.
Referenced by imb_exr_begin_read_mem().
static ExrPass* imb_exr_get_pass (ListBase * lb, char * passname) [static]
Definition at line 782 of file openexr_api.cpp.
References BLI_addhead(), BLI_addtail(), BLI_findstring(), BLI_strncpy(), EXR_LAY_MAXNAME, MEM_callocN(), ExrLayer::name, ExrPass::name, and NULL.
Referenced by imb_exr_begin_read_mem().
void IMB_exr_multilayer_convert (void * handle, void * base, void *(*)(void *base, char *str) addlayer, void(*)(void *base, void *lay, char *str, float *rect, int totchan, char *chan_id) addpass)
Definition at line 672 of file openexr_api.cpp.
Referenced by render_result_new_from_exr().
void IMB_exr_read_channels (void * handle)
Definition at line 638 of file openexr_api.cpp.
Referenced by imb_load_openexr(), and render_result_exr_file_read_path().
void IMB_exr_set_channel (void * handle, const char * layname, const char * passname, int xstride, int ystride, float * rect)
Definition at line 553 of file openexr_api.cpp.
Referenced by render_result_exr_file_read_path(), and save_render_result_tile().
static int imb_exr_split_channel_name (ExrChannel * echan, char * layname, char * passname) [static]
Definition at line 731 of file openexr_api.cpp.
References BLI_strncpy(), ExrChannel::chan_id, EXR_LAY_MAXNAME, EXR_PASS_MAXNAME, len(), ExrChannel::name, and strlen().
Referenced by imb_exr_begin_read_mem().
void IMB_exr_write_channels (void * handle)
Definition at line 610 of file openexr_api.cpp.
Referenced by exec_output_file_multilayer(), and RE_WriteRenderResult().
void IMB_exrtile_begin_write (void * handle, const char * filename, int mipmap, int width, int height, int tilex, int tiley)
Definition at line 505 of file openexr_api.cpp.
Referenced by render_result_exr_file_begin().
void IMB_exrtile_clear_channels (void * handle)
Definition at line 580 of file openexr_api.cpp.
Referenced by save_empty_result_tiles().
void IMB_exrtile_write_channels (void * handle, int partx, int party, int level)
Definition at line 586 of file openexr_api.cpp.
Referenced by save_empty_result_tiles(), and save_render_result_tile().
void imb_initopenexr (void)
Test presence of OpenEXR file.
Parameters:
mem pointer to loaded OpenEXR bitstream
Definition at line 1076 of file openexr_api.cpp.
References BLI_system_thread_count().
int imb_is_a_openexr (unsigned char * mem)
Definition at line 158 of file openexr_api.cpp.
Referenced by imb_load_openexr().
struct ImBuf* imb_load_openexr (unsigned char * mem, size_t size, int flags) [read]
Definition at line 963 of file openexr_api.cpp.
References addzbuffloatImBuf(), exr_has_zbuffer(), exr_is_multilayer(), exr_print_filecontents(), exr_rgba_channelname(), ImBuf::ftype, IB_multilayer, IB_PROFILE_LINEAR_RGB, IB_test, imb_addrectfloatImBuf(), IMB_allocImBuf(), imb_exr_begin_read_mem(), IMB_exr_read_channels(), IMB_freeImBuf(), imb_is_a_openexr(), NULL, OPENEXR, ImBuf::profile, ImBuf::rect_float, ImBuf::userdata, and ImBuf::zbuf_float.
int imb_save_openexr (struct ImBuf * ibuf, const char * name, int flags)
Definition at line 365 of file openexr_api.cpp.
References ImBuf::encodedsize, ImBuf::ftype, IB_mem, imb_addencodedbufferImBuf(), imb_save_openexr_float(), imb_save_openexr_half(), NULL, OPENEXR_HALF, and ImBuf::rect_float.
static int imb_save_openexr_float (struct ImBuf * ibuf, const char * name, int flags) [static]
Definition at line 306 of file openexr_api.cpp.
References ImBuf::channels, ImBuf::ftype, IB_zbuffloat, NULL, OPENEXR_COMPRESS, openexr_header_compression(), openexr_header_metadata(), ImBuf::planes, ImBuf::rect_float, ImBuf::x, ImBuf::y, and ImBuf::zbuf_float.
Referenced by imb_save_openexr().
static int imb_save_openexr_half (struct ImBuf * ibuf, const char * name, int flags) [static]
Definition at line 196 of file openexr_api.cpp.
References _RGBAZ::a, _RGBAZ::b, ImBuf::channels, ImBuf::ftype, _RGBAZ::g, g, i, IB_PROFILE_LINEAR_RGB, IB_zbuffloat, NULL, OPENEXR_COMPRESS, openexr_header_compression(), openexr_header_metadata(), ImBuf::planes, ImBuf::profile, _RGBAZ::r, ImBuf::rect, ImBuf::rect_float, srgb_to_linearrgb(), ImBuf::x, ImBuf::y, and ImBuf::zbuf_float.
Referenced by imb_save_openexr().
static void openexr_header_compression (Header * header, int compression) [static]
Definition at line 163 of file openexr_api.cpp.
Referenced by IMB_exr_begin_write(), imb_save_openexr_float(), and imb_save_openexr_half().
static void openexr_header_metadata (Header * header, struct ImBuf * ibuf) [static]
Definition at line 188 of file openexr_api.cpp.
References ImMetaData::key, ImBuf::metadata, ImMetaData::next, and ImMetaData::value.
Referenced by imb_save_openexr_float(), and imb_save_openexr_half().
Variable Documentation
ListBase exrhandles = {NULL, NULL} [static]
Definition at line 395 of file openexr_api.cpp.
Referenced by IMB_exr_close(), and IMB_exr_get_handle().