Blender: PBVHProxyNode Struct Reference
PBVHProxyNode Struct Reference
#include <BLI_pbvh.h>
Public Attributes
float(* co)[3]
Detailed Description
Definition at line 43 of file BLI_pbvh.h.
Member Data Documentation
float(* PBVHProxyNode::co)[3]
Definition at line 44 of file BLI_pbvh.h.
Referenced by BLI_pbvh_node_add_proxy(), BLI_pbvh_node_free_proxies(), do_clay_brush(), do_clay_strips_brush(), do_crease_brush(), do_draw_brush(), do_fill_brush(), do_flatten_brush(), do_grab_brush(), do_inflate_brush(), do_nudge_brush(), do_pinch_brush(), do_rotate_brush(), do_scrape_brush(), do_snake_hook_brush(), and do_thumb_brush().
The documentation for this struct was generated from the following file:
BLI_pbvh.h