Blender: btSoftRigidCollisionAlgorithm Class Reference
btSoftRigidCollisionAlgorithm Class Reference
btSoftRigidCollisionAlgorithm provides collision detection between btSoftBody and btRigidBody
#include <btSoftRigidCollisionAlgorithm.h>
Classes
struct CreateFunc
Public Member Functions
btSoftRigidCollisionAlgorithm (btPersistentManifold *mf, const btCollisionAlgorithmConstructionInfo &ci, btCollisionObject *col0, btCollisionObject *col1, bool isSwapped)
virtual ~btSoftRigidCollisionAlgorithm ()
virtual void processCollision (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
virtual btScalar calculateTimeOfImpact (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
virtual void getAllContactManifolds (btManifoldArray &manifoldArray)
Detailed Description
btSoftRigidCollisionAlgorithm provides collision detection between btSoftBody and btRigidBody
Definition at line 29 of file btSoftRigidCollisionAlgorithm.h.
Constructor & Destructor Documentation
btSoftRigidCollisionAlgorithm::btSoftRigidCollisionAlgorithm (btPersistentManifold * mf, const btCollisionAlgorithmConstructionInfo & ci, btCollisionObject * col0, btCollisionObject * col1, bool isSwapped)
TODO: include all the shapes that the softbody can collide with alternatively, implement special case collision algorithms (just like for rigid collision shapes)
Definition at line 29 of file btSoftRigidCollisionAlgorithm.cpp.
Referenced by btSoftRigidCollisionAlgorithm::CreateFunc::CreateCollisionAlgorithm().
btSoftRigidCollisionAlgorithm::~btSoftRigidCollisionAlgorithm () [virtual]
Definition at line 38 of file btSoftRigidCollisionAlgorithm.cpp.
Member Function Documentation
btScalar btSoftRigidCollisionAlgorithm::calculateTimeOfImpact (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Implements btCollisionAlgorithm.
Definition at line 72 of file btSoftRigidCollisionAlgorithm.cpp.
virtual void btSoftRigidCollisionAlgorithm::getAllContactManifolds (btManifoldArray & manifoldArray) [inline, virtual]
Implements btCollisionAlgorithm.
Definition at line 50 of file btSoftRigidCollisionAlgorithm.h.
void btSoftRigidCollisionAlgorithm::processCollision (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Implements btCollisionAlgorithm.
Definition at line 55 of file btSoftRigidCollisionAlgorithm.cpp.
References btAlignedObjectArray< T >::findLinearSearch(), btSoftBody::getSoftBodySolver(), btSoftBody::m_collisionDisabledObjects, btSoftBodySolver::processCollision(), and btAlignedObjectArray< T >::size().
The documentation for this class was generated from the following files:
btSoftRigidCollisionAlgorithm.h
btSoftRigidCollisionAlgorithm.cpp