Blender: HullLibrary Class Reference
HullLibrary Class Reference
#include <btConvexHull.h>
Public Member Functions
HullError CreateConvexHull (const HullDesc &desc, HullResult &result)
HullError ReleaseResult (HullResult &result)
Public Attributes
btAlignedObjectArray< int > m_vertexIndexMapping
Detailed Description
The HullLibrary class can create a convex hull from a collection of vertices, using the ComputeHull method. The btShapeHull class uses this HullLibrary to create a approximate convex mesh given a general (non-polyhedral) convex shape.
Definition at line 184 of file btConvexHull.h.
Member Function Documentation
HullError HullLibrary::CreateConvexHull (const HullDesc & desc, HullResult & result)
Definition at line 698 of file btConvexHull.cpp.
References HullDesc::HasHullFlag(), i, HullResult::m_Indices, PHullResult::m_Indices, HullResult::m_OutputVertices, PHullResult::mFaceCount, PHullResult::mIndexCount, HullDesc::mMaxVertices, HullDesc::mNormalEpsilon, HullResult::mNumFaces, HullResult::mNumIndices, HullResult::mNumOutputVertices, HullResult::mPolygons, PHullResult::mVcount, HullDesc::mVcount, HullDesc::mVertexStride, HullDesc::mVertices, PHullResult::mVertices, QE_FAIL, QE_OK, QF_REVERSE_ORDER, QF_TRIANGLES, ReleaseHull(), and btAlignedObjectArray< T >::resize().
Referenced by btShapeHull::buildHull(), btSoftBodyHelpers::CreateFromConvexHull(), CcdPhysicsController::CreateSoftbody(), and btSoftBodyHelpers::Draw().
HullError HullLibrary::ReleaseResult (HullResult & result)
Definition at line 823 of file btConvexHull.cpp.
References btAlignedObjectArray< T >::clear(), HullResult::m_Indices, HullResult::m_OutputVertices, HullResult::mNumIndices, HullResult::mNumOutputVertices, QE_OK, and btAlignedObjectArray< T >::size().
Referenced by btShapeHull::buildHull(), btSoftBodyHelpers::CreateFromConvexHull(), CcdPhysicsController::CreateSoftbody(), and btSoftBodyHelpers::Draw().
Member Data Documentation
btAlignedObjectArray<int> HullLibrary::m_vertexIndexMapping
Definition at line 191 of file btConvexHull.h.
The documentation for this class was generated from the following files:
btConvexHull.h
btConvexHull.cpp