Blender: tracking_ops.c File Reference
tracking_ops.c File Reference
#include "MEM_guardedalloc.h"
#include "DNA_camera_types.h"
#include "DNA_constraint_types.h"
#include "DNA_gpencil_types.h"
#include "DNA_movieclip_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "BLI_listbase.h"
#include "BLI_rect.h"
#include "BLI_blenlib.h"
#include "BKE_main.h"
#include "BKE_context.h"
#include "BKE_constraint.h"
#include "BKE_movieclip.h"
#include "BKE_tracking.h"
#include "BKE_global.h"
#include "BKE_depsgraph.h"
#include "BKE_object.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "BKE_library.h"
#include "BKE_sound.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_screen.h"
#include "ED_clip.h"
#include "ED_keyframing.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "UI_interface.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "PIL_time.h"
#include "UI_view2d.h"
#include "clip_intern.h"
Classes
struct SlideMarkerData
struct TrackMarkersJob
struct SolveCameraJob
Defines
#define SLIDE_ACTION_POS 0
#define SLIDE_ACTION_SIZE 1
#define SLIDE_ACTION_OFFSET 2
Typedefs
typedef struct TrackMarkersJob TrackMarkersJob
Functions
static int space_clip_frame_poll (bContext *C)
static void add_marker (SpaceClip *sc, float x, float y)
static int add_marker_exec (bContext *C, wmOperator *op)
static int add_marker_invoke (bContext *C, wmOperator *op, wmEvent *event)
void CLIP_OT_add_marker (wmOperatorType *ot)
static int delete_track_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_delete_track (wmOperatorType *ot)
static int delete_marker_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_delete_marker (wmOperatorType *ot)
static SlideMarkerData * create_slide_marker_data (SpaceClip *sc, MovieTrackingTrack *track, MovieTrackingMarker *marker, wmEvent *event, int area, int action, int width, int height)
static int mouse_on_corner (SpaceClip *sc, MovieTrackingTrack *track, MovieTrackingMarker *marker, int area, float co[2], int corner, int width, int height)
static int mouse_on_offset (SpaceClip *sc, MovieTrackingTrack *track, MovieTrackingMarker *marker, float co[2], int width, int height)
static void hide_cursor (bContext *C)
static void show_cursor (bContext *C)
static void * slide_marker_customdata (bContext *C, wmEvent *event)
static int slide_marker_invoke (bContext *C, wmOperator *op, wmEvent *event)
static void cancel_mouse_slide (SlideMarkerData *data)
static void free_slide_data (SlideMarkerData *data)
static int slide_marker_modal (bContext *C, wmOperator *op, wmEvent *event)
void CLIP_OT_slide_marker (wmOperatorType *ot)
static int mouse_on_side (float co[2], float x1, float y1, float x2, float y2, float epsx, float epsy)
static int mouse_on_rect (float co[2], float pos[2], float min[2], float max[2], float epsx, float epsy)
static int track_mouse_area (SpaceClip *sc, float co[2], MovieTrackingTrack *track)
static float dist_to_rect (float co[2], float pos[2], float min[2], float max[2])
static MovieTrackingTrack * find_nearest_track (SpaceClip *sc, ListBase *tracksbase, float co[2])
static int mouse_select (bContext *C, float co[2], int extend)
static int select_exec (bContext *C, wmOperator *op)
static int select_invoke (bContext *C, wmOperator *op, wmEvent *event)
void CLIP_OT_select (wmOperatorType *ot)
static int border_select_exec (bContext *C, wmOperator *op)
void CLIP_OT_select_border (wmOperatorType *ot)
static int marker_inside_ellipse (MovieTrackingMarker *marker, float offset[2], float ellipse[2])
static int circle_select_exec (bContext *C, wmOperator *op)
void CLIP_OT_select_circle (wmOperatorType *ot)
static int select_all_exec (bContext *C, wmOperator *op)
void CLIP_OT_select_all (wmOperatorType *ot)
static int select_groped_exec (bContext *C, wmOperator *op)
void CLIP_OT_select_grouped (wmOperatorType *ot)
static int track_markers_testbreak (void)
static int track_count_markers (SpaceClip *sc, MovieClip *clip)
static void clear_invisible_track_selection (SpaceClip *sc, MovieClip *clip)
static void track_init_markers (SpaceClip *sc, MovieClip *clip, int *frames_limit_r)
static int track_markers_check_direction (int backwards, int curfra, int efra)
static int track_markers_initjob (bContext *C, TrackMarkersJob *tmj, int backwards)
static void track_markers_startjob (void *tmv, short *stop, short *do_update, float *progress)
static void track_markers_updatejob (void *tmv)
static void track_markers_freejob (void *tmv)
static int track_markers_exec (bContext *C, wmOperator *op)
static int track_markers_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int track_markers_modal (bContext *C, wmOperator *UNUSED(op), wmEvent *event)
void CLIP_OT_track_markers (wmOperatorType *ot)
static int solve_camera_initjob (bContext *C, SolveCameraJob *scj, wmOperator *op, char *error_msg, int max_error)
static void solve_camera_updatejob (void *scv)
static void solve_camera_startjob (void *scv, short *stop, short *do_update, float *progress)
static void solve_camera_freejob (void *scv)
static int solve_camera_exec (bContext *C, wmOperator *op)
static int solve_camera_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int solve_camera_modal (bContext *C, wmOperator *UNUSED(op), wmEvent *event)
void CLIP_OT_solve_camera (wmOperatorType *ot)
static int clear_solution_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_clear_solution (wmOperatorType *ot)
static int clear_track_path_exec (bContext *C, wmOperator *op)
void CLIP_OT_clear_track_path (wmOperatorType *ot)
static int disable_markers_exec (bContext *C, wmOperator *op)
void CLIP_OT_disable_markers (wmOperatorType *ot)
static Object * get_camera_with_movieclip (Scene *scene, MovieClip *clip)
static Object * get_orientation_object (bContext *C)
static int set_orientation_poll (bContext *C)
static int count_selected_bundles (bContext *C)
static void object_solver_inverted_matrix (Scene *scene, Object *ob, float invmat[4][4])
static Object * object_solver_camera (Scene *scene, Object *ob)
static int set_origin_exec (bContext *C, wmOperator *op)
void CLIP_OT_set_origin (wmOperatorType *ot)
static void set_axis (Scene *scene, Object *ob, MovieClip *clip, MovieTrackingObject *tracking_object, MovieTrackingTrack *track, char axis)
static int set_plane_exec (bContext *C, wmOperator *op)
void CLIP_OT_set_plane (wmOperatorType *ot)
static int set_axis_exec (bContext *C, wmOperator *op)
void CLIP_OT_set_axis (wmOperatorType *ot)
static int do_set_scale (bContext *C, wmOperator *op, int scale_solution)
static int set_scale_exec (bContext *C, wmOperator *op)
static int set_scale_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void CLIP_OT_set_scale (wmOperatorType *ot)
static int set_solution_scale_poll (bContext *C)
static int set_solution_scale_exec (bContext *C, wmOperator *op)
static int set_solution_scale_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void CLIP_OT_set_solution_scale (wmOperatorType *ot)
static int set_center_principal_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_set_center_principal (wmOperatorType *ot)
static int hide_tracks_exec (bContext *C, wmOperator *op)
void CLIP_OT_hide_tracks (wmOperatorType *ot)
static int hide_tracks_clear_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_hide_tracks_clear (wmOperatorType *ot)
static bGPDlayer * detect_get_layer (MovieClip *clip)
static int detect_features_exec (bContext *C, wmOperator *op)
void CLIP_OT_detect_features (wmOperatorType *ot)
static int frame_jump_exec (bContext *C, wmOperator *op)
void CLIP_OT_frame_jump (wmOperatorType *ot)
static int join_tracks_exec (bContext *C, wmOperator *op)
void CLIP_OT_join_tracks (wmOperatorType *ot)
static int lock_tracks_exec (bContext *C, wmOperator *op)
void CLIP_OT_lock_tracks (wmOperatorType *ot)
static int track_copy_color_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_track_copy_color (wmOperatorType *ot)
static int stabilize_2d_add_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_stabilize_2d_add (wmOperatorType *ot)
static int stabilize_2d_remove_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_stabilize_2d_remove (wmOperatorType *ot)
static int stabilize_2d_select_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_stabilize_2d_select (wmOperatorType *ot)
static int stabilize_2d_set_rotation_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_stabilize_2d_set_rotation (wmOperatorType *ot)
static int is_track_clean (MovieTrackingTrack *track, int frames, int del)
static int clean_tracks_exec (bContext *C, wmOperator *op)
static int clean_tracks_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void CLIP_OT_clean_tracks (wmOperatorType *ot)
static int tracking_object_new_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_tracking_object_new (wmOperatorType *ot)
static int tracking_object_remove_exec (bContext *C, wmOperator *op)
void CLIP_OT_tracking_object_remove (wmOperatorType *ot)
static int copy_tracks_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_copy_tracks (wmOperatorType *ot)
static int paste_tracks_poll (bContext *C)
static int paste_tracks_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_paste_tracks (wmOperatorType *ot)
Detailed Description
Definition in file tracking_ops.c.
Define Documentation
#define SLIDE_ACTION_OFFSET 2
Definition at line 265 of file tracking_ops.c.
Referenced by cancel_mouse_slide(), create_slide_marker_data(), slide_marker_customdata(), and slide_marker_modal().
#define SLIDE_ACTION_POS 0
Definition at line 263 of file tracking_ops.c.
Referenced by slide_marker_customdata().
#define SLIDE_ACTION_SIZE 1
Definition at line 264 of file tracking_ops.c.
Referenced by cancel_mouse_slide(), create_slide_marker_data(), slide_marker_customdata(), and slide_marker_modal().
Typedef Documentation
typedef struct TrackMarkersJob TrackMarkersJob
Function Documentation
static void add_marker (SpaceClip * sc, float x, float y) [static]
Definition at line 97 of file tracking_ops.c.
References MovieTracking::act_track, BKE_tracking_add_track(), BKE_tracking_get_tracks(), BKE_tracking_select_track(), ED_space_clip(), ED_space_clip_size(), MovieClipUser::framenr, TRACK_AREA_ALL, MovieClip::tracking, and SpaceClip::user.
Referenced by add_marker_exec().
static int add_marker_exec (bContext * C, wmOperator * op) [static]
Definition at line 114 of file tracking_ops.c.
References add_marker(), CTX_wm_space_clip(), ED_space_clip(), ED_space_clip_size(), NA_EDITED, NC_MOVIECLIP, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get_array(), WM_event_add_notifier(), SpaceClip::xlockof, and SpaceClip::ylockof.
Referenced by add_marker_invoke(), and CLIP_OT_add_marker().
static int add_marker_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 138 of file tracking_ops.c.
References add_marker_exec(), co, ED_clip_mouse_pos(), wmOperator::ptr, and RNA_float_set_array().
Referenced by CLIP_OT_add_marker().
static int border_select_exec (bContext * C, wmOperator * op) [static]
Definition at line 874 of file tracking_ops.c.
References BKE_tracking_get_marker(), BKE_tracking_get_tracks(), BKE_tracking_track_flag(), BLI_in_rctf(), CTX_wm_space_clip(), ED_clip_point_stable_pos(), ED_space_clip(), FALSE, ListBase::first, MovieTrackingTrack::flag, MovieClipUser::framenr, GESTURE_MODAL_SELECT, MARKER_VISIBLE, NC_GEOM, ND_SELECT, MovieTrackingTrack::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, MovieTrackingMarker::pos, wmOperator::ptr, RNA_boolean_get(), RNA_int_get(), SELECT, TRACK_AREA_ALL, TRACK_HIDDEN, MovieClip::tracking, TRUE, SpaceClip::user, WM_event_add_notifier(), rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, rctf::ymax, rcti::ymax, rctf::ymin, and rcti::ymin.
Referenced by CLIP_OT_select_border().
static void cancel_mouse_slide (SlideMarkerData * data) [static]
Definition at line 490 of file tracking_ops.c.
References SlideMarkerData::action, SlideMarkerData::area, copy_v2_v2(), MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, SlideMarkerData::max, SlideMarkerData::min, SlideMarkerData::offset, MovieTrackingMarker::pos, SlideMarkerData::pos, SLIDE_ACTION_OFFSET, SLIDE_ACTION_SIZE, SlideMarkerData::smarkers, SlideMarkerData::smax, SlideMarkerData::smin, SlideMarkerData::soff, SlideMarkerData::spos, SlideMarkerData::track, and TRACK_AREA_POINT.
Referenced by slide_marker_modal().
static int circle_select_exec (bContext * C, wmOperator * op) [static]
Definition at line 959 of file tracking_ops.c.
References BKE_tracking_get_marker(), BKE_tracking_get_tracks(), BKE_tracking_track_flag(), CTX_wm_region(), CTX_wm_space_clip(), ED_clip_point_stable_pos(), ED_space_clip(), ED_space_clip_size(), ED_space_clip_zoom(), FALSE, ListBase::first, MovieTrackingTrack::flag, MovieClipUser::framenr, GESTURE_MODAL_SELECT, marker_inside_ellipse(), MARKER_VISIBLE, NC_GEOM, ND_SELECT, MovieTrackingTrack::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_int_get(), SELECT, TRACK_AREA_ALL, TRACK_HIDDEN, MovieClip::tracking, TRUE, SpaceClip::user, and WM_event_add_notifier().
Referenced by CLIP_OT_select_circle().
static int clean_tracks_exec (bContext * C, wmOperator * op) [static]
Definition at line 3424 of file tracking_ops.c.
References MovieTracking::act_track, BKE_tracking_active_track(), BKE_tracking_free_track(), BKE_tracking_get_tracks(), BKE_tracking_track_flag(), BLI_freelinkN(), CTX_wm_space_clip(), ED_space_clip(), MovieTrackingTrack::error, error(), ListBase::first, MovieTrackingTrack::flag, is_track_clean(), MovieTrackingTrack::markersnr, NC_MOVIECLIP, ND_SELECT, MovieTrackingTrack::next, next, NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), RNA_float_get(), RNA_int_get(), SELECT, TRACK_AREA_ALL, TRACK_HAS_BUNDLE, TRACK_HIDDEN, TRACK_LOCKED, MovieClip::tracking, TRACKING_CLEAN_DELETE_SEGMENT, TRACKING_CLEAN_DELETE_TRACK, TRACKING_CLEAN_SELECT, and WM_event_add_notifier().
Referenced by clean_tracks_invoke(), and CLIP_OT_clean_tracks().
static int clean_tracks_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 3480 of file tracking_ops.c.
References MovieTrackingSettings::clean_action, MovieTrackingSettings::clean_error, MovieTrackingSettings::clean_frames, clean_tracks_exec(), CTX_wm_space_clip(), ED_space_clip(), wmOperator::ptr, RNA_enum_set(), RNA_float_set(), RNA_int_set(), RNA_struct_property_is_set(), MovieTracking::settings, and MovieClip::tracking.
Referenced by CLIP_OT_clean_tracks().
static void clear_invisible_track_selection (SpaceClip * sc, MovieClip * clip) [static]
Definition at line 1253 of file tracking_ops.c.
References BKE_tracking_get_tracks(), BKE_tracking_track_flag(), ListBase::first, MovieTrackingTrack::flag, SpaceClip::flag, MovieTrackingTrack::next, SC_SHOW_MARKER_PATTERN, SC_SHOW_MARKER_SEARCH, SELECT, TRACK_AREA_PAT, TRACK_AREA_SEARCH, TRACK_HIDDEN, and MovieClip::tracking.
Referenced by copy_tracks_exec(), and track_init_markers().
static int clear_solution_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1811 of file tracking_ops.c.
References BKE_tracking_get_reconstruction(), BKE_tracking_get_tracks(), MovieTrackingReconstruction::cameras, MovieTrackingReconstruction::camnr, CTX_wm_space_clip(), DAG_id_tag_update(), ED_space_clip(), ListBase::first, MovieTrackingReconstruction::flag, MovieTrackingTrack::flag, MovieClip::id, MEM_freeN(), NA_EVALUATED, NC_MOVIECLIP, NC_SPACE, ND_SPACE_VIEW3D, MovieTrackingTrack::next, NULL, OPERATOR_FINISHED, TRACK_HAS_BUNDLE, MovieClip::tracking, TRACKING_RECONSTRUCTED, and WM_event_add_notifier().
Referenced by CLIP_OT_clear_solution().
static int clear_track_path_exec (bContext * C, wmOperator * op) [static]
Definition at line 1859 of file tracking_ops.c.
References BKE_tracking_active_track(), BKE_tracking_clear_path(), BKE_tracking_get_tracks(), CTX_wm_space_clip(), ED_space_clip(), ListBase::first, MovieClipUser::framenr, NA_EVALUATED, NC_MOVIECLIP, MovieTrackingTrack::next, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_enum_get(), TRACK_VIEW_SELECTED, MovieClip::tracking, SpaceClip::user, and WM_event_add_notifier().
Referenced by CLIP_OT_clear_track_path().
void CLIP_OT_add_marker (wmOperatorType * ot)
Definition at line 149 of file tracking_ops.c.
References add_marker_exec(), add_marker_invoke(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_vector(), space_clip_frame_poll(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_clean_tracks (wmOperatorType * ot)
Definition at line 3497 of file tracking_ops.c.
References clean_tracks_exec(), clean_tracks_invoke(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_float(), RNA_def_int(), wmOperatorType::srna, TRACKING_CLEAN_DELETE_SEGMENT, TRACKING_CLEAN_DELETE_TRACK, and TRACKING_CLEAN_SELECT.
Referenced by clip_operatortypes().
void CLIP_OT_clear_solution (wmOperatorType * ot)
Definition at line 1842 of file tracking_ops.c.
References clear_solution_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by clip_operatortypes().
void CLIP_OT_clear_track_path (wmOperatorType * ot)
Definition at line 1887 of file tracking_ops.c.
References clear_track_path_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_enum(), wmOperatorType::srna, TRACK_CLEAR_ALL, TRACK_CLEAR_REMAINED, and TRACK_CLEAR_UPTO.
Referenced by clip_operatortypes().
void CLIP_OT_copy_tracks (wmOperatorType * ot)
Definition at line 3611 of file tracking_ops.c.
References copy_tracks_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and wmOperatorType::poll.
Referenced by clip_operatortypes().
void CLIP_OT_delete_marker (wmOperatorType * ot)
Definition at line 245 of file tracking_ops.c.
References delete_marker_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by clip_operatortypes().
void CLIP_OT_delete_track (wmOperatorType * ot)
Definition at line 194 of file tracking_ops.c.
References delete_track_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by clip_operatortypes().
void CLIP_OT_detect_features (wmOperatorType * ot)
Definition at line 2866 of file tracking_ops.c.
References wmOperatorType::description, detect_features_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_int(), space_clip_frame_poll(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_disable_markers (wmOperatorType * ot)
Definition at line 1945 of file tracking_ops.c.
References wmOperatorType::description, disable_markers_exec(), ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_frame_jump (wmOperatorType * ot)
Definition at line 2960 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, frame_jump_exec(), wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), space_clip_frame_poll(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_hide_tracks (wmOperatorType * ot)
Definition at line 2752 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, hide_tracks_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_hide_tracks_clear (wmOperatorType * ot)
Definition at line 2791 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, hide_tracks_clear_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by clip_operatortypes().
void CLIP_OT_join_tracks (wmOperatorType * ot)
Definition at line 3025 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, join_tracks_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and space_clip_frame_poll().
Referenced by clip_operatortypes().
void CLIP_OT_lock_tracks (wmOperatorType * ot)
Definition at line 3068 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, lock_tracks_exec(), wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_paste_tracks (wmOperatorType * ot)
Definition at line 3651 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, paste_tracks_exec(), paste_tracks_poll(), and wmOperatorType::poll.
Referenced by clip_operatortypes().
void CLIP_OT_select (wmOperatorType * ot)
Definition at line 850 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_vector(), select_exec(), select_invoke(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_select_all (wmOperatorType * ot)
Definition at line 1103 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, select_all_exec(), and WM_operator_properties_select_all().
Referenced by clip_operatortypes().
void CLIP_OT_select_border (wmOperatorType * ot)
Definition at line 926 of file tracking_ops.c.
References border_select_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, TRUE, WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by clip_operatortypes().
void CLIP_OT_select_circle (wmOperatorType * ot)
Definition at line 1010 of file tracking_ops.c.
References circle_select_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, WM_gesture_circle_invoke(), and WM_gesture_circle_modal().
Referenced by clip_operatortypes().
void CLIP_OT_select_grouped (wmOperatorType * ot)
Definition at line 1183 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), select_groped_exec(), space_clip_frame_poll(), wmOperatorType::srna, and TRACK_CLEAR_REMAINED.
Referenced by clip_operatortypes().
void CLIP_OT_set_axis (wmOperatorType * ot)
Definition at line 2487 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), set_axis_exec(), set_orientation_poll(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_set_center_principal (wmOperatorType * ot)
Definition at line 2698 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and set_center_principal_exec().
Referenced by clip_operatortypes().
void CLIP_OT_set_origin (wmOperatorType * ot)
Definition at line 2172 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), set_orientation_poll(), set_origin_exec(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_set_plane (wmOperatorType * ot)
Definition at line 2415 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), set_orientation_poll(), set_plane_exec(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_set_scale (wmOperatorType * ot)
Definition at line 2605 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), set_orientation_poll(), set_scale_exec(), set_scale_invoke(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_set_solution_scale (wmOperatorType * ot)
Definition at line 2657 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), set_solution_scale_exec(), set_solution_scale_invoke(), set_solution_scale_poll(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_slide_marker (wmOperatorType * ot)
Definition at line 638 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_vector(), slide_marker_invoke(), slide_marker_modal(), space_clip_frame_poll(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_solve_camera (wmOperatorType * ot)
Definition at line 1792 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, solve_camera_exec(), solve_camera_invoke(), and solve_camera_modal().
Referenced by clip_operatortypes().
void CLIP_OT_stabilize_2d_add (wmOperatorType * ot)
Definition at line 3174 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and stabilize_2d_add_exec().
Referenced by clip_operatortypes().
void CLIP_OT_stabilize_2d_remove (wmOperatorType * ot)
Definition at line 3234 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and stabilize_2d_remove_exec().
Referenced by clip_operatortypes().
void CLIP_OT_stabilize_2d_select (wmOperatorType * ot)
Definition at line 3277 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and stabilize_2d_select_exec().
Referenced by clip_operatortypes().
void CLIP_OT_stabilize_2d_set_rotation (wmOperatorType * ot)
Definition at line 3314 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and stabilize_2d_set_rotation_exec().
Referenced by clip_operatortypes().
void CLIP_OT_track_copy_color (wmOperatorType * ot)
Definition at line 3125 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and track_copy_color_exec().
Referenced by clip_operatortypes().
void CLIP_OT_track_markers (wmOperatorType * ot)
Definition at line 1570 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), space_clip_frame_poll(), wmOperatorType::srna, track_markers_exec(), track_markers_invoke(), and track_markers_modal().
Referenced by clip_operatortypes().
void CLIP_OT_tracking_object_new (wmOperatorType * ot)
Definition at line 3542 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and tracking_object_new_exec().
Referenced by clip_operatortypes().
void CLIP_OT_tracking_object_remove (wmOperatorType * ot)
Definition at line 3580 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and tracking_object_remove_exec().
Referenced by clip_operatortypes().
static int copy_tracks_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3597 of file tracking_ops.c.
References BKE_tracking_active_object(), BKE_tracking_clipboard_copy_tracks(), clear_invisible_track_selection(), CTX_wm_space_clip(), ED_space_clip(), OPERATOR_FINISHED, and MovieClip::tracking.
Referenced by CLIP_OT_copy_tracks().
static int count_selected_bundles (bContext * C) [static]
Definition at line 2037 of file tracking_ops.c.
References BKE_tracking_get_tracks(), CTX_wm_space_clip(), ED_space_clip(), ListBase::first, MovieTrackingTrack::flag, MovieTrackingTrack::next, TRACK_HAS_BUNDLE, TRACK_VIEW_SELECTED, and MovieClip::tracking.
Referenced by do_set_scale(), set_axis_exec(), set_origin_exec(), and set_plane_exec().
static SlideMarkerData* create_slide_marker_data (SpaceClip * sc, MovieTrackingTrack * track, MovieTrackingMarker * marker, wmEvent * event, int area, int action, int width, int height) [static]
Definition at line 281 of file tracking_ops.c.
References SlideMarkerData::action, SlideMarkerData::area, BKE_tracking_ensure_marker(), copy_v2_v2(), data, MovieClipUser::framenr, SlideMarkerData::height, SlideMarkerData::lock, SlideMarkerData::marker, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, SlideMarkerData::max, MEM_callocN(), SlideMarkerData::min, SlideMarkerData::mval, MovieTrackingTrack::offset, SlideMarkerData::offset, MovieTrackingTrack::pat_max, MovieTrackingTrack::pat_min, MovieTrackingMarker::pos, SlideMarkerData::pos, MovieTrackingTrack::search_max, MovieTrackingTrack::search_min, SLIDE_ACTION_OFFSET, SLIDE_ACTION_SIZE, SlideMarkerData::smarkers, SlideMarkerData::smax, SlideMarkerData::smin, SlideMarkerData::soff, SlideMarkerData::spos, SlideMarkerData::track, TRACK_AREA_PAT, TRACK_AREA_POINT, TRACK_AREA_SEARCH, SpaceClip::user, and SlideMarkerData::width.
Referenced by slide_marker_customdata().
static int delete_marker_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 212 of file tracking_ops.c.
References BKE_tracking_exact_marker(), BKE_tracking_get_tracks(), clip_delete_marker(), CTX_wm_space_clip(), ED_space_clip(), ListBase::first, SpaceClip::flag, MovieClipUser::framenr, MovieTrackingTrack::markersnr, MovieTrackingTrack::next, next, OPERATOR_FINISHED, SC_LOCK_SELECTION, TRACK_VIEW_SELECTED, MovieClip::tracking, and SpaceClip::user.
Referenced by CLIP_OT_delete_marker().
static int delete_track_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 171 of file tracking_ops.c.
References BKE_tracking_get_tracks(), clip_delete_track(), CTX_wm_space_clip(), ED_space_clip(), ListBase::first, SpaceClip::flag, MovieTrackingTrack::next, next, OPERATOR_FINISHED, SC_LOCK_SELECTION, TRACK_VIEW_SELECTED, and MovieClip::tracking.
Referenced by CLIP_OT_delete_track().
static int detect_features_exec (bContext * C, wmOperator * op) [static]
Definition at line 2826 of file tracking_ops.c.
References BKE_movieclip_get_ibuf_flag(), BKE_tracking_detect_fast(), BKE_tracking_get_tracks(), CTX_wm_space_clip(), detect_get_layer(), ED_space_clip(), ListBase::first, MovieTrackingTrack::flag, MovieClip::flag, MovieClipUser::framenr, IMB_freeImBuf(), MCLIP_TIMECODE_FLAGS, MOVIECLIP_CACHE_SKIP, NA_EDITED, NC_MOVIECLIP, MovieTrackingTrack::next, NULL, OPERATOR_FINISHED, MovieTrackingTrack::pat_flag, wmOperator::ptr, RNA_enum_get(), RNA_int_get(), MovieTrackingTrack::search_flag, SELECT, MovieClip::tracking, SpaceClip::user, and WM_event_add_notifier().
Referenced by CLIP_OT_detect_features().
static bGPDlayer* detect_get_layer (MovieClip * clip) [static]
Definition at line 2808 of file tracking_ops.c.
References ListBase::first, bGPDlayer::flag, GP_LAYER_ACTIVE, MovieClip::gpd, bGPdata::layers, bGPDlayer::next, and NULL.
Referenced by detect_features_exec().
static int disable_markers_exec (bContext * C, wmOperator * op) [static]
Definition at line 1915 of file tracking_ops.c.
References BKE_tracking_ensure_marker(), BKE_tracking_get_tracks(), CTX_wm_space_clip(), DAG_id_tag_update(), ED_space_clip(), ListBase::first, MovieTrackingMarker::flag, MovieTrackingTrack::flag, MovieClipUser::framenr, MovieClip::id, MARKER_DISABLED, NA_EVALUATED, NC_MOVIECLIP, MovieTrackingTrack::next, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), TRACK_LOCKED, TRACK_VIEW_SELECTED, MovieClip::tracking, SpaceClip::user, and WM_event_add_notifier().
Referenced by CLIP_OT_disable_markers().
static float dist_to_rect (float co[2], float pos[2], float min[2], float max[2]) [static]
Definition at line 716 of file tracking_ops.c.
References dist_to_line_segment_v2(), MIN4, and p.
Referenced by find_nearest_track().
static int do_set_scale (bContext * C, wmOperator * op, int scale_solution) [static]
Definition at line 2513 of file tracking_ops.c.
References BKE_get_tracking_mat(), BKE_report(), BKE_tracking_active_object(), BKE_tracking_get_tracks(), MovieTrackingTrack::bundle_pos, count_selected_bundles(), CTX_data_scene(), CTX_wm_space_clip(), DAG_id_tag_update(), ED_space_clip(), ListBase::first, MovieTrackingObject::flag, get_camera_with_movieclip(), get_orientation_object(), Object::id, MovieClip::id, len_v3(), Object::loc, mul_v3_fl(), mul_v3_m4v3(), NA_EVALUATED, NC_MOVIECLIP, NC_OBJECT, ND_TRANSFORM, MovieTrackingTrack::next, NULL, OB_RECALC_OB, object_solver_camera(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_float_get(), RPT_ERROR, MovieTrackingObject::scale, Object::size, sub_v3_v3(), TRACK_VIEW_SELECTED, MovieClip::tracking, TRACKING_OBJECT_CAMERA, and WM_event_add_notifier().
Referenced by set_scale_exec(), and set_solution_scale_exec().
static MovieTrackingTrack* find_nearest_track (SpaceClip * sc, ListBase * tracksbase, float co[2]) [static]
Definition at line 731 of file tracking_ops.c.
References BKE_tracking_get_marker(), dist_to_rect(), ListBase::first, SpaceClip::flag, FLT_MAX, MovieClipUser::framenr, MARKER_VISIBLE, MIN3, MovieTrackingTrack::next, NULL, MovieTrackingMarker::pos, SC_SHOW_MARKER_PATTERN, SC_SHOW_MARKER_SEARCH, sqrtf, TRACK_HIDDEN, TRACK_VIEW_SELECTED, and SpaceClip::user.
Referenced by mouse_select().
static int frame_jump_exec (bContext * C, wmOperator * op) [static]
Definition at line 2896 of file tracking_ops.c.
References BKE_tracking_active_object(), BKE_tracking_active_track(), BKE_tracking_exact_marker(), BKE_tracking_get_reconstructed_camera(), CFRA, CTX_data_main(), CTX_data_scene(), CTX_wm_space_clip(), ED_space_clip(), EFRA, MovieTrackingReconstruction::flag, MovieTrackingMarker::flag, MovieClipUser::framenr, MARKER_DISABLED, NC_MOVIECLIP, NC_SCENE, ND_DISPLAY, ND_FRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, MovieTracking::reconstruction, RNA_enum_get(), SFRA, sound_seek_scene(), MovieClip::tracking, TRACKING_RECONSTRUCTED, SpaceClip::user, and WM_event_add_notifier().
Referenced by CLIP_OT_frame_jump().
static void free_slide_data (SlideMarkerData * data) [static]
Definition at line 515 of file tracking_ops.c.
References MEM_freeN(), and SlideMarkerData::smarkers.
Referenced by slide_marker_modal().
static Object* get_camera_with_movieclip (Scene * scene, MovieClip * clip) [static]
Definition at line 1972 of file tracking_ops.c.
References Scene::base, Scene::camera, ListBase::first, Base::next, OB_CAMERA, Base::object, object_get_movieclip(), and Object::type.
Referenced by do_set_scale(), get_orientation_object(), set_axis(), set_origin_exec(), and set_plane_exec().
static Object* get_orientation_object (bContext * C) [static]
Definition at line 1995 of file tracking_ops.c.
References BKE_tracking_active_object(), CTX_data_scene(), CTX_wm_space_clip(), ED_space_clip(), MovieTrackingObject::flag, get_camera_with_movieclip(), NULL, OBACT, Object::parent, MovieClip::tracking, and TRACKING_OBJECT_CAMERA.
Referenced by do_set_scale(), set_axis_exec(), set_origin_exec(), and set_plane_exec().
static void hide_cursor (bContext * C) [static]
Definition at line 399 of file tracking_ops.c.
References CTX_wm_window(), CURSOR_NONE, and WM_cursor_set().
Referenced by slide_marker_invoke().
static int hide_tracks_clear_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2772 of file tracking_ops.c.
References BKE_tracking_get_tracks(), CTX_wm_space_clip(), ED_space_clip(), ListBase::first, MovieTrackingTrack::flag, NC_MOVIECLIP, ND_DISPLAY, MovieTrackingTrack::next, NULL, OPERATOR_FINISHED, TRACK_HIDDEN, MovieClip::tracking, and WM_event_add_notifier().
Referenced by CLIP_OT_hide_tracks_clear().
static int hide_tracks_exec (bContext * C, wmOperator * op) [static]
Definition at line 2715 of file tracking_ops.c.
References MovieTracking::act_track, BKE_tracking_active_track(), BKE_tracking_get_tracks(), CTX_wm_space_clip(), ED_space_clip(), ListBase::first, SpaceClip::flag, MovieTrackingTrack::flag, NC_MOVIECLIP, ND_DISPLAY, MovieTrackingTrack::next, NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), SC_LOCK_SELECTION, TRACK_HIDDEN, TRACK_VIEW_SELECTED, MovieClip::tracking, and WM_event_add_notifier().
Referenced by CLIP_OT_hide_tracks().
static int is_track_clean (MovieTrackingTrack * track, int frames, int del) [static]
Definition at line 3331 of file tracking_ops.c.
References len(), MARKER_DISABLED, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, MEM_callocN(), MEM_freeN(), and NULL.
Referenced by clean_tracks_exec().
static int join_tracks_exec (bContext * C, wmOperator * op) [static]
Definition at line 2988 of file tracking_ops.c.
References BKE_report(), BKE_tracking_active_track(), BKE_tracking_free_track(), BKE_tracking_get_tracks(), BKE_tracking_join_tracks(), BLI_freelinkN(), CTX_wm_space_clip(), ED_space_clip(), ListBase::first, NA_EDITED, NC_MOVIECLIP, MovieTrackingTrack::next, next, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, MovieTrackingStabilization::rot_track, RPT_ERROR, MovieTracking::stabilization, TRACK_VIEW_SELECTED, MovieClip::tracking, and WM_event_add_notifier().
Referenced by CLIP_OT_join_tracks().
static int lock_tracks_exec (bContext * C, wmOperator * op) [static]
Definition at line 3042 of file tracking_ops.c.
References BKE_tracking_get_tracks(), CTX_wm_space_clip(), ED_space_clip(), ListBase::first, MovieTrackingTrack::flag, NA_EVALUATED, NC_MOVIECLIP, MovieTrackingTrack::next, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), TRACK_LOCKED, TRACK_VIEW_SELECTED, MovieClip::tracking, and WM_event_add_notifier().
Referenced by CLIP_OT_lock_tracks().
static int marker_inside_ellipse (MovieTrackingMarker * marker, float offset[2], float ellipse[2]) [static]
Definition at line 948 of file tracking_ops.c.
References MovieTrackingMarker::pos.
Referenced by circle_select_exec().
static int mouse_on_corner (SpaceClip * sc, MovieTrackingTrack * track, MovieTrackingMarker * marker, int area, float co[2], int corner, int width, int height) [static]
Definition at line 341 of file tracking_ops.c.
References copy_v2_v2(), max, min, MIN2, MovieTrackingTrack::pat_max, MovieTrackingTrack::pat_min, MovieTrackingMarker::pos, MovieTrackingTrack::search_max, MovieTrackingTrack::search_min, size(), TRACK_AREA_SEARCH, and SpaceClip::zoom.
Referenced by slide_marker_customdata().
static int mouse_on_offset (SpaceClip * sc, MovieTrackingTrack * track, MovieTrackingMarker * marker, float co[2], int width, int height) [static]
Definition at line 383 of file tracking_ops.c.
References add_v2_v2v2(), MIN2, MovieTrackingTrack::offset, MovieTrackingTrack::pat_max, MovieTrackingTrack::pat_min, MovieTrackingMarker::pos, and SpaceClip::zoom.
Referenced by slide_marker_customdata().
static int mouse_on_rect (float co[2], float pos[2], float min[2], float max[2], float epsx, float epsy) [static]
Definition at line 672 of file tracking_ops.c.
References mouse_on_side().
Referenced by track_mouse_area().
static int mouse_on_side (float co[2], float x1, float y1, float x2, float y2, float epsx, float epsy) [static]
Definition at line 660 of file tracking_ops.c.
References SWAP.
Referenced by mouse_on_rect().
static int mouse_select (bContext * C, float co[2], int extend) [static]
Definition at line 769 of file tracking_ops.c.
References MovieTracking::act_track, BKE_tracking_active_track(), BKE_tracking_deselect_track(), BKE_tracking_get_tracks(), BKE_tracking_select_track(), CTX_wm_space_clip(), ED_space_clip(), find_nearest_track(), NC_GEOM, ND_SELECT, NULL, OPERATOR_FINISHED, TRACK_AREA_ALL, TRACK_AREA_POINT, TRACK_AREA_SELECTED, track_mouse_area(), TRACK_VIEW_SELECTED, MovieClip::tracking, WM_event_add_notifier(), SpaceClip::xlockof, and SpaceClip::ylockof.
Referenced by select_exec().
static Object* object_solver_camera (Scene * scene, Object * ob) [static]
Definition at line 2088 of file tracking_ops.c.
References bObjectSolverConstraint::camera, Scene::camera, constraint_get_typeinfo(), CONSTRAINT_TYPE_OBJECTSOLVER, Object::constraints, data, bConstraint::data, ListBase::first, bConstraint::next, NULL, and bConstraintTypeInfo::type.
Referenced by do_set_scale().
static void object_solver_inverted_matrix (Scene * scene, Object * ob, float invmat[4][4]) [static]
Definition at line 2056 of file tracking_ops.c.
References Scene::camera, bObjectSolverConstraint::camera, constraint_get_typeinfo(), CONSTRAINT_TYPE_OBJECTSOLVER, Object::constraints, bConstraint::data, data, FALSE, ListBase::first, if(), invert_m4(), bObjectSolverConstraint::invmat, mult_m4_m4m4(), bConstraint::next, TRUE, bConstraintTypeInfo::type, unit_m4(), and where_is_object_mat().
Referenced by set_axis(), and set_origin_exec().
static int paste_tracks_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3637 of file tracking_ops.c.
References BKE_tracking_active_object(), BKE_tracking_clipboard_paste_tracks(), CTX_wm_space_clip(), ED_space_clip(), NA_EDITED, NC_MOVIECLIP, OPERATOR_FINISHED, MovieClip::tracking, and WM_event_add_notifier().
Referenced by CLIP_OT_paste_tracks().
static int paste_tracks_poll (bContext * C) [static]
Definition at line 3628 of file tracking_ops.c.
References BKE_tracking_clipboard_has_tracks(), and ED_space_clip_poll().
Referenced by CLIP_OT_paste_tracks().
static int select_all_exec (bContext * C, wmOperator * op) [static]
Definition at line 1035 of file tracking_ops.c.
References BKE_tracking_get_marker(), BKE_tracking_get_tracks(), CTX_wm_space_clip(), ED_space_clip(), FALSE, ListBase::first, SpaceClip::flag, MovieTrackingTrack::flag, MovieClipUser::framenr, MARKER_VISIBLE, NC_GEOM, ND_SELECT, MovieTrackingTrack::next, NULL, OPERATOR_FINISHED, MovieTrackingTrack::pat_flag, wmOperator::ptr, RNA_enum_get(), SC_LOCK_SELECTION, MovieTrackingTrack::search_flag, SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, SELECT, TRACK_HIDDEN, TRACK_VIEW_SELECTED, MovieClip::tracking, TRUE, SpaceClip::user, and WM_event_add_notifier().
Referenced by CLIP_OT_select_all().
static int select_exec (bContext * C, wmOperator * op) [static]
Definition at line 811 of file tracking_ops.c.
References co, mouse_select(), wmOperator::ptr, RNA_boolean_get(), and RNA_float_get_array().
Referenced by CLIP_OT_select(), and select_invoke().
static int select_groped_exec (bContext * C, wmOperator * op) [static]
Definition at line 1122 of file tracking_ops.c.
References BKE_tracking_active_track(), BKE_tracking_get_marker(), BKE_tracking_get_tracks(), MovieTrackingTrack::color, CTX_wm_space_clip(), ED_space_clip(), equals_v3v3(), FALSE, ListBase::first, SpaceClip::flag, MovieTrackingTrack::flag, MovieTrackingMarker::flag, MovieTrackingMarker::framenr, MovieClipUser::framenr, MARKER_DISABLED, MARKER_TRACKED, NC_MOVIECLIP, ND_DISPLAY, MovieTrackingTrack::next, OPERATOR_FINISHED, MovieTrackingTrack::pat_flag, wmOperator::ptr, RNA_enum_get(), SC_SHOW_MARKER_PATTERN, SC_SHOW_MARKER_SEARCH, MovieTrackingTrack::search_flag, SELECT, TRACK_CUSTOMCOLOR, TRACK_HAS_BUNDLE, TRACK_LOCKED, MovieClip::tracking, SpaceClip::user, and WM_event_add_notifier().
Referenced by CLIP_OT_select_grouped().
static int select_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 822 of file tracking_ops.c.
References MovieTracking::act_track, co, CTX_wm_space_clip(), ED_clip_mouse_pos(), ED_space_clip(), MEM_freeN(), NC_GEOM, ND_SELECT, NULL, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_boolean_get(), RNA_float_set_array(), select_exec(), slide_marker_customdata(), SlideMarkerData::track, MovieClip::tracking, and WM_event_add_notifier().
Referenced by CLIP_OT_select().
static void set_axis (Scene * scene, Object * ob, MovieClip * clip, MovieTrackingObject * tracking_object, MovieTrackingTrack * track, char axis) [static]
Definition at line 2192 of file tracking_ops.c.
References BKE_get_tracking_mat(), MovieTrackingTrack::bundle_pos, copy_v3_v3(), cross_v3_v3v3(), fabsf, FALSE, MovieTrackingObject::flag, get_camera_with_movieclip(), invert_m3(), invert_m4(), invert_m4_m4(), MovieReconstructContext::is_camera, len_v2(), mul_m4_m4m3(), mul_serie_m4(), mul_v3_m4v3(), mult_m4_m4m4(), normalize_v3(), NULL, object_apply_mat4(), object_rot_to_mat3(), object_solver_inverted_matrix(), object_to_mat4(), sub_v3_v3(), TRACKING_OBJECT_CAMERA, TRUE, and unit_m4().
Referenced by set_axis_exec(), and set_plane_exec().
static int set_axis_exec (bContext * C, wmOperator * op) [static]
Definition at line 2441 of file tracking_ops.c.
References BKE_report(), BKE_tracking_active_object(), BKE_tracking_object_tracks(), count_selected_bundles(), CTX_data_scene(), CTX_wm_space_clip(), DAG_id_tag_update(), ED_space_clip(), ListBase::first, get_orientation_object(), Object::id, MovieClip::id, NA_EVALUATED, NC_MOVIECLIP, NC_OBJECT, ND_TRANSFORM, MovieTrackingTrack::next, NULL, OB_RECALC_OB, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), RPT_ERROR, set_axis(), TRACK_VIEW_SELECTED, MovieClip::tracking, and WM_event_add_notifier().
Referenced by CLIP_OT_set_axis().
static int set_center_principal_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2679 of file tracking_ops.c.
References BKE_movieclip_get_size(), MovieTracking::camera, CTX_wm_space_clip(), ED_space_clip(), NA_EDITED, NC_MOVIECLIP, OPERATOR_CANCELLED, OPERATOR_FINISHED, MovieTrackingCamera::principal, MovieClip::tracking, SpaceClip::user, and WM_event_add_notifier().
Referenced by CLIP_OT_set_center_principal().
static int set_orientation_poll (bContext * C) [static]
Definition at line 2017 of file tracking_ops.c.
References BKE_tracking_active_object(), CTX_data_scene(), CTX_wm_space_clip(), ED_space_clip(), FALSE, MovieTrackingObject::flag, NULL, OBACT, space_clip_frame_poll(), MovieClip::tracking, TRACKING_OBJECT_CAMERA, and TRUE.
Referenced by CLIP_OT_set_axis(), CLIP_OT_set_origin(), CLIP_OT_set_plane(), and CLIP_OT_set_scale().
static int set_origin_exec (bContext * C, wmOperator * op) [static]
Definition at line 2108 of file tracking_ops.c.
References add_v3_v3(), BKE_get_tracking_mat(), BKE_report(), BKE_tracking_active_object(), BKE_tracking_object_tracks(), MovieTrackingTrack::bundle_pos, copy_v3_v3(), count_selected_bundles(), CTX_data_scene(), CTX_wm_space_clip(), DAG_id_tag_update(), ED_space_clip(), ListBase::first, MovieTrackingObject::flag, MovieTrackingTrack::flag, get_camera_with_movieclip(), get_orientation_object(), Object::id, MovieClip::id, Object::loc, mul_v3_fl(), mul_v3_m4v3(), NA_EVALUATED, NC_MOVIECLIP, NC_OBJECT, ND_TRANSFORM, MovieTrackingTrack::next, NULL, OB_RECALC_OB, object_solver_inverted_matrix(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, sub_v3_v3(), TRACK_HAS_BUNDLE, TRACK_VIEW_SELECTED, MovieClip::tracking, TRACKING_OBJECT_CAMERA, WM_event_add_notifier(), and zero_v3().
Referenced by CLIP_OT_set_origin().
static int set_plane_exec (bContext * C, wmOperator * op) [static]
Definition at line 2303 of file tracking_ops.c.
References BKE_get_tracking_mat(), BKE_report(), BKE_tracking_active_object(), BKE_tracking_active_track(), BKE_tracking_object_tracks(), MovieTrackingTrack::bundle_pos, copy_v3_v3(), count_selected_bundles(), cross_v3_v3v3(), CTX_data_scene(), CTX_wm_space_clip(), DAG_id_tag_update(), ED_space_clip(), ListBase::first, MovieTrackingObject::flag, MovieTrackingTrack::flag, get_camera_with_movieclip(), get_orientation_object(), Object::id, MovieClip::id, invert_m4(), Object::loc, mul_v3_m4v3(), mult_m4_m4m4(), NA_EVALUATED, NC_MOVIECLIP, NC_OBJECT, ND_TRANSFORM, MovieTrackingTrack::next, normalize_v3(), NULL, OB_RECALC_OB, object_apply_mat4(), object_to_mat4(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), rot, RPT_ERROR, set_axis(), sub_v3_v3(), TRACK_HAS_BUNDLE, TRACK_VIEW_SELECTED, MovieClip::tracking, TRACKING_OBJECT_CAMERA, unit_m4(), where_is_object(), and WM_event_add_notifier().
Referenced by CLIP_OT_set_plane().
static int set_scale_exec (bContext * C, wmOperator * op) [static]
Definition at line 2589 of file tracking_ops.c.
References do_set_scale().
Referenced by CLIP_OT_set_scale(), and set_scale_invoke().
static int set_scale_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 2594 of file tracking_ops.c.
References CTX_wm_space_clip(), MovieTrackingSettings::dist, ED_space_clip(), wmOperator::ptr, RNA_float_set(), RNA_struct_property_is_set(), set_scale_exec(), MovieTracking::settings, and MovieClip::tracking.
Referenced by CLIP_OT_set_scale().
static int set_solution_scale_exec (bContext * C, wmOperator * op) [static]
Definition at line 2641 of file tracking_ops.c.
References do_set_scale().
Referenced by CLIP_OT_set_solution_scale(), and set_solution_scale_invoke().
static int set_solution_scale_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 2646 of file tracking_ops.c.
References CTX_wm_space_clip(), ED_space_clip(), MovieTrackingSettings::object_distance, wmOperator::ptr, RNA_float_set(), RNA_struct_property_is_set(), set_solution_scale_exec(), MovieTracking::settings, and MovieClip::tracking.
Referenced by CLIP_OT_set_solution_scale().
static int set_solution_scale_poll (bContext * C) [static]
Definition at line 2627 of file tracking_ops.c.
References BKE_tracking_active_object(), CTX_wm_space_clip(), ED_space_clip(), MovieTrackingObject::flag, space_clip_frame_poll(), MovieClip::tracking, and TRACKING_OBJECT_CAMERA.
Referenced by CLIP_OT_set_solution_scale().
static void show_cursor (bContext * C) [static]
Definition at line 406 of file tracking_ops.c.
References CTX_wm_window(), CURSOR_STD, and WM_cursor_set().
Referenced by slide_marker_modal().
static void* slide_marker_customdata (bContext * C, wmEvent * event) [static]
Definition at line 413 of file tracking_ops.c.
References BKE_tracking_get_marker(), BKE_tracking_get_tracks(), co, create_slide_marker_data(), CTX_wm_space_clip(), ED_clip_mouse_pos(), ED_space_clip(), ED_space_clip_size(), ListBase::first, SpaceClip::flag, MovieTrackingMarker::flag, MovieTrackingTrack::flag, MovieClipUser::framenr, MARKER_DISABLED, mouse_on_corner(), mouse_on_offset(), MovieTrackingTrack::next, NULL, SC_SHOW_MARKER_PATTERN, SC_SHOW_MARKER_SEARCH, SLIDE_ACTION_OFFSET, SLIDE_ACTION_POS, SLIDE_ACTION_SIZE, TRACK_AREA_PAT, TRACK_AREA_POINT, TRACK_AREA_SEARCH, TRACK_LOCKED, TRACK_VIEW_SELECTED, MovieClip::tracking, and SpaceClip::user.
Referenced by select_invoke(), and slide_marker_invoke().
static int slide_marker_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 466 of file tracking_ops.c.
References MovieTracking::act_track, CTX_wm_space_clip(), wmOperator::customdata, ED_space_clip(), hide_cursor(), NC_GEOM, ND_SELECT, NULL, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, slide_marker_customdata(), SlideMarkerData::track, MovieClip::tracking, WM_event_add_modal_handler(), and WM_event_add_notifier().
Referenced by CLIP_OT_slide_marker().
static int slide_marker_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 523 of file tracking_ops.c.
References SlideMarkerData::accurate, SlideMarkerData::action, add_v2_v2v2(), SlideMarkerData::area, BKE_tracking_clamp_track(), cancel_mouse_slide(), CLAMP_PAT_DIM, CLAMP_SEARCH_DIM, CLAMP_SEARCH_POS, SpaceClip::clip, CTX_wm_space_clip(), wmOperator::customdata, DAG_id_tag_update(), data, ELEM, ESCKEY, MovieTrackingMarker::flag, free_slide_data(), SlideMarkerData::height, MovieClip::id, if(), KM_PRESS, KM_RELEASE, LEFTCTRLKEY, LEFTMOUSE, LEFTSHIFTKEY, SlideMarkerData::lock, SlideMarkerData::marker, MARKER_TRACKED, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, SlideMarkerData::max, SlideMarkerData::min, MOUSEMOVE, SlideMarkerData::mval, wmEvent::mval, NA_EDITED, NC_MOVIECLIP, NC_OBJECT, ND_TRANSFORM, NULL, SlideMarkerData::offset, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, MovieTrackingMarker::pos, SlideMarkerData::pos, RIGHTCTRLKEY, RIGHTSHIFTKEY, show_cursor(), SLIDE_ACTION_OFFSET, SLIDE_ACTION_SIZE, SlideMarkerData::smarkers, SlideMarkerData::smax, SlideMarkerData::smin, SlideMarkerData::soff, SlideMarkerData::spos, sub_v2_v2v2(), SlideMarkerData::track, TRACK_AREA_POINT, TRACK_AREA_SEARCH, wmEvent::type, wmEvent::val, SlideMarkerData::width, WM_event_add_notifier(), and SpaceClip::zoom.
Referenced by CLIP_OT_slide_marker().
static int solve_camera_exec (bContext * C, wmOperator * op) [static]
Definition at line 1705 of file tracking_ops.c.
References BKE_report(), MEM_callocN(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, solve_camera_freejob(), solve_camera_initjob(), and solve_camera_startjob().
Referenced by CLIP_OT_solve_camera().
static void solve_camera_freejob (void * scv) [static]
Definition at line 1650 of file tracking_ops.c.
References BKE_movieclip_get_size(), BKE_report(), BKE_reportf(), BKE_tracking_camera_to_blender(), BKE_tracking_finish_reconstruction(), BKE_tracking_reconstruction_context_free(), Scene::camera, Scene::clip, SolveCameraJob::clip, SolveCameraJob::context, DAG_id_tag_update(), Object::data, MovieTrackingReconstruction::error, MovieClip::id, id_us_min(), id_us_plus(), MEM_freeN(), NA_EVALUATED, NC_MOVIECLIP, NC_OBJECT, NC_SCENE, ND_TRANSFORM, NULL, MovieTracking::reconstruction, SolveCameraJob::reports, RPT_INFO, RPT_WARNING, SolveCameraJob::scene, MovieTracking::stats, MovieClip::tracking, SolveCameraJob::user, and WM_main_add_notifier().
Referenced by solve_camera_exec(), and solve_camera_invoke().
static int solve_camera_initjob (bContext * C, SolveCameraJob * scj, wmOperator * op, char * error_msg, int max_error) [static]
Definition at line 1605 of file tracking_ops.c.
References BKE_movieclip_get_size(), BKE_tracking_active_object(), BKE_tracking_can_reconstruct(), BKE_tracking_reconstruction_context_new(), SolveCameraJob::clip, SolveCameraJob::context, CTX_data_scene(), CTX_wm_space_clip(), ED_space_clip(), MovieTrackingSettings::keyframe1, MovieTrackingSettings::keyframe2, MEM_callocN(), wmOperator::reports, SolveCameraJob::reports, SolveCameraJob::scene, MovieTracking::settings, MovieTracking::stats, MovieClip::tracking, SolveCameraJob::user, and SpaceClip::user.
Referenced by solve_camera_exec(), and solve_camera_invoke().
static int solve_camera_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1727 of file tracking_ops.c.
References BKE_report(), BKE_tracking_get_reconstruction(), BLI_strncpy(), CTX_wm_area(), CTX_wm_manager(), CTX_wm_space_clip(), CTX_wm_window(), ED_space_clip(), MovieTrackingReconstruction::flag, G, MEM_callocN(), MovieTrackingStats::message, NA_EVALUATED, NC_MOVIECLIP, NULL, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, wmOperator::reports, RPT_ERROR, solve_camera_freejob(), solve_camera_initjob(), solve_camera_startjob(), solve_camera_updatejob(), MovieTracking::stats, MovieClip::tracking, TRACKING_RECONSTRUCTED, WM_cursor_wait(), WM_event_add_modal_handler(), WM_event_add_notifier(), WM_JOB_PROGRESS, WM_jobs_callbacks(), WM_jobs_customdata(), WM_jobs_get(), WM_jobs_start(), WM_jobs_test(), and WM_jobs_timer().
Referenced by CLIP_OT_solve_camera().
static int solve_camera_modal (bContext * C, wmOperator * UNUSEDop, wmEvent * event) [static]
Definition at line 1776 of file tracking_ops.c.
References CTX_wm_area(), CTX_wm_manager(), ESCKEY, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, wmEvent::type, and WM_jobs_test().
Referenced by CLIP_OT_solve_camera().
static void solve_camera_startjob (void * scv, short * stop, short * do_update, float * progress) [static]
Definition at line 1642 of file tracking_ops.c.
References BKE_tracking_solve_reconstruction(), SolveCameraJob::context, and SolveCameraJob::stats_message.
Referenced by solve_camera_exec(), and solve_camera_invoke().
static void solve_camera_updatejob (void * scv) [static]
Definition at line 1634 of file tracking_ops.c.
References BLI_strncpy(), SolveCameraJob::clip, MovieTrackingStats::message, MovieTracking::stats, SolveCameraJob::stats_message, and MovieClip::tracking.
Referenced by solve_camera_invoke().
static int space_clip_frame_poll (bContext * C) [static]
Definition at line 81 of file tracking_ops.c.
References BKE_movieclip_has_frame(), CTX_wm_space_clip(), ED_space_clip(), FALSE, and SpaceClip::user.
Referenced by CLIP_OT_add_marker(), CLIP_OT_detect_features(), CLIP_OT_frame_jump(), CLIP_OT_join_tracks(), CLIP_OT_select_grouped(), CLIP_OT_slide_marker(), CLIP_OT_track_markers(), set_orientation_poll(), and set_solution_scale_poll().
static int stabilize_2d_add_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3142 of file tracking_ops.c.
References BKE_tracking_get_tracks(), CTX_wm_space_clip(), DAG_id_tag_update(), ED_space_clip(), ListBase::first, MovieTrackingTrack::flag, MovieClip::id, NC_MOVIECLIP, ND_DISPLAY, MovieTrackingTrack::next, MovieTrackingStabilization::ok, OPERATOR_FINISHED, MovieTracking::stabilization, MovieTrackingStabilization::tot_track, TRACK_USE_2D_STAB, TRACK_VIEW_SELECTED, MovieClip::tracking, update(), and WM_event_add_notifier().
Referenced by CLIP_OT_stabilize_2d_add().
static int stabilize_2d_remove_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3191 of file tracking_ops.c.
References MovieTrackingStabilization::act_track, BKE_tracking_get_tracks(), CTX_wm_space_clip(), DAG_id_tag_update(), ED_space_clip(), ListBase::first, MovieTrackingTrack::flag, MovieClip::id, NC_MOVIECLIP, ND_DISPLAY, MovieTrackingTrack::next, MovieTrackingStabilization::ok, OPERATOR_FINISHED, MovieTracking::stabilization, MovieTrackingStabilization::tot_track, TRACK_USE_2D_STAB, MovieClip::tracking, update(), and WM_event_add_notifier().
Referenced by CLIP_OT_stabilize_2d_remove().
static int stabilize_2d_select_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3251 of file tracking_ops.c.
References BKE_tracking_get_tracks(), BKE_tracking_track_flag(), CTX_wm_space_clip(), ED_space_clip(), ListBase::first, MovieTrackingTrack::flag, NC_MOVIECLIP, ND_SELECT, MovieTrackingTrack::next, OPERATOR_FINISHED, SELECT, TRACK_AREA_ALL, TRACK_USE_2D_STAB, MovieClip::tracking, update(), and WM_event_add_notifier().
Referenced by CLIP_OT_stabilize_2d_select().
static int stabilize_2d_set_rotation_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3294 of file tracking_ops.c.
References BKE_tracking_active_track(), CTX_wm_space_clip(), DAG_id_tag_update(), ED_space_clip(), MovieClip::id, NC_MOVIECLIP, ND_DISPLAY, MovieTrackingStabilization::ok, OPERATOR_FINISHED, MovieTrackingStabilization::rot_track, MovieTracking::stabilization, MovieClip::tracking, and WM_event_add_notifier().
Referenced by CLIP_OT_stabilize_2d_set_rotation().
static int track_copy_color_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3095 of file tracking_ops.c.
References BKE_tracking_active_track(), BKE_tracking_get_tracks(), MovieTrackingTrack::color, copy_v3_v3(), CTX_wm_space_clip(), ED_space_clip(), ListBase::first, MovieTrackingTrack::flag, NC_MOVIECLIP, ND_DISPLAY, MovieTrackingTrack::next, OPERATOR_CANCELLED, OPERATOR_FINISHED, TRACK_CUSTOMCOLOR, TRACK_VIEW_SELECTED, MovieClip::tracking, and WM_event_add_notifier().
Referenced by CLIP_OT_track_copy_color().
static int track_count_markers (SpaceClip * sc, MovieClip * clip) [static]
Definition at line 1231 of file tracking_ops.c.
References BKE_tracking_get_marker(), BKE_tracking_get_tracks(), ListBase::first, MovieTrackingMarker::flag, MovieTrackingTrack::flag, MovieClipUser::framenr, MARKER_DISABLED, MovieTrackingTrack::next, TRACK_LOCKED, TRACK_VIEW_SELECTED, MovieClip::tracking, and SpaceClip::user.
Referenced by track_markers_exec(), and track_markers_invoke().
static void track_init_markers (SpaceClip * sc, MovieClip * clip, int * frames_limit_r) [static]
Definition at line 1276 of file tracking_ops.c.
References BKE_tracking_ensure_marker(), BKE_tracking_get_tracks(), clear_invisible_track_selection(), ListBase::first, MovieTrackingTrack::flag, MovieClipUser::framenr, MovieTrackingTrack::frames_limit, MIN2, MovieTrackingTrack::next, TRACK_HIDDEN, TRACK_LOCKED, TRACK_VIEW_SELECTED, MovieClip::tracking, and SpaceClip::user.
Referenced by track_markers_exec(), and track_markers_initjob().
static int track_markers_check_direction (int backwards, int curfra, int efra) [static]
Definition at line 1306 of file tracking_ops.c.
References FALSE, and TRUE.
Referenced by track_markers_exec(), and track_markers_initjob().
static int track_markers_exec (bContext * C, wmOperator * op) [static]
Definition at line 1442 of file tracking_ops.c.
References MovieTrackingContext::backwards, BKE_tracking_context_free(), BKE_tracking_context_new(), BKE_tracking_next(), BKE_tracking_sync(), RenderData::cfra, CTX_data_scene(), CTX_wm_space_clip(), ED_space_clip(), EFRA, MovieClipUser::framenr, MAX2, MIN2, NA_EVALUATED, NC_MOVIECLIP, NC_SCENE, ND_FRAME, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, Scene::r, RNA_boolean_get(), bScreen::scene, MovieTrackingContext::sequence, SFRA, track_count_markers(), track_init_markers(), track_markers_check_direction(), SpaceClip::user, and WM_event_add_notifier().
Referenced by CLIP_OT_track_markers(), and track_markers_invoke().
static void track_markers_freejob (void * tmv) [static]
Definition at line 1426 of file tracking_ops.c.
References BKE_tracking_context_free(), BKE_tracking_sync(), RenderData::cfra, TrackMarkersJob::clip, TrackMarkersJob::context, ED_update_for_newframe(), TrackMarkersJob::lastfra, TrackMarkersJob::main, MEM_freeN(), NC_SCENE, ND_FRAME, NULL, Scene::r, TrackMarkersJob::scene, TrackMarkersJob::screen, MovieClip::tracking_context, and WM_main_add_notifier().
Referenced by track_markers_invoke().
static int track_markers_initjob (bContext * C, TrackMarkersJob * tmj, int backwards) [static]
Definition at line 1320 of file tracking_ops.c.
References TrackMarkersJob::backwards, BKE_tracking_context_new(), TrackMarkersJob::clip, TrackMarkersJob::context, CTX_data_main(), CTX_data_scene(), CTX_wm_screen(), CTX_wm_space_clip(), TrackMarkersJob::delay, ED_space_clip(), EFRA, TrackMarkersJob::efra, MovieClipUser::framenr, RenderData::frs_sec, TrackMarkersJob::lastfra, TrackMarkersJob::main, MAX2, MIN2, Scene::r, TrackMarkersJob::scene, bScreen::scene, TrackMarkersJob::screen, MovieTracking::settings, SFRA, TrackMarkersJob::sfra, MovieTrackingSettings::speed, track_init_markers(), track_markers_check_direction(), MovieClip::tracking, MovieClip::tracking_context, TRACKING_SPEED_DOUBLE, TRACKING_SPEED_FASTEST, TRACKING_SPEED_HALF, TRACKING_SPEED_QUARTER, and SpaceClip::user.
Referenced by track_markers_invoke().
static int track_markers_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1499 of file tracking_ops.c.
References MovieTrackingContext::backwards, MovieTrackingContext::clip, CTX_wm_area(), CTX_wm_manager(), CTX_wm_space_clip(), CTX_wm_window(), TrackMarkersJob::delay, ED_space_clip(), G, MEM_callocN(), NA_EVALUATED, NC_MOVIECLIP, NULL, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_boolean_get(), MovieTrackingContext::sequence, track_count_markers(), track_markers_exec(), track_markers_freejob(), track_markers_initjob(), track_markers_startjob(), track_markers_updatejob(), MovieClip::tracking_context, WM_cursor_wait(), WM_event_add_modal_handler(), WM_JOB_PROGRESS, WM_jobs_callbacks(), WM_jobs_customdata(), WM_jobs_get(), WM_jobs_start(), WM_jobs_test(), and WM_jobs_timer().
Referenced by CLIP_OT_track_markers().
static int track_markers_modal (bContext * C, wmOperator * UNUSEDop, wmEvent * event) [static]
Definition at line 1554 of file tracking_ops.c.
References CTX_wm_area(), CTX_wm_manager(), ESCKEY, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, wmEvent::type, and WM_jobs_test().
Referenced by CLIP_OT_track_markers().
static void track_markers_startjob (void * tmv, short * stop, short * do_update, float * progress) [static]
Definition at line 1376 of file tracking_ops.c.
References TrackMarkersJob::backwards, BKE_tracking_next(), TrackMarkersJob::context, TrackMarkersJob::delay, TrackMarkersJob::efra, TrackMarkersJob::lastfra, PIL_check_seconds_timer(), PIL_sleep_ms(), TrackMarkersJob::sfra, track_markers_testbreak(), and TRUE.
Referenced by track_markers_invoke().
static int track_markers_testbreak (void) [static]
Definition at line 1226 of file tracking_ops.c.
References G.
Referenced by track_markers_startjob().
static void track_markers_updatejob (void * tmv) [static]
Definition at line 1419 of file tracking_ops.c.
References BKE_tracking_sync(), and TrackMarkersJob::context.
Referenced by track_markers_invoke().
static int track_mouse_area (SpaceClip * sc, float co[2], MovieTrackingTrack * track) [static]
Definition at line 680 of file tracking_ops.c.
References BKE_tracking_get_marker(), ED_space_clip_size(), fabsf, MovieTrackingMarker::flag, SpaceClip::flag, MovieClipUser::framenr, MARKER_DISABLED, MAX2, MIN4, mouse_on_rect(), MovieTrackingTrack::offset, MovieTrackingTrack::pat_max, MovieTrackingTrack::pat_min, MovieTrackingMarker::pos, SC_SHOW_MARKER_PATTERN, SC_SHOW_MARKER_SEARCH, MovieTrackingTrack::search_max, MovieTrackingTrack::search_min, TRACK_AREA_NONE, TRACK_AREA_PAT, TRACK_AREA_POINT, TRACK_AREA_SEARCH, and SpaceClip::user.
Referenced by mouse_select().
static int tracking_object_new_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3529 of file tracking_ops.c.
References BKE_tracking_new_object(), CTX_wm_space_clip(), ED_space_clip(), NA_EDITED, NC_MOVIECLIP, OPERATOR_FINISHED, MovieClip::tracking, and WM_event_add_notifier().
Referenced by CLIP_OT_tracking_object_new().
static int tracking_object_remove_exec (bContext * C, wmOperator * op) [static]
Definition at line 3559 of file tracking_ops.c.
References BKE_report(), BKE_tracking_active_object(), BKE_tracking_remove_object(), CTX_wm_space_clip(), ED_space_clip(), MovieTrackingObject::flag, NA_EDITED, NC_MOVIECLIP, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_WARNING, MovieClip::tracking, TRACKING_OBJECT_CAMERA, and WM_event_add_notifier().
Referenced by CLIP_OT_tracking_object_remove().