Blender: rna_screen.c File Reference
rna_screen.c File Reference
RNA
#include <stdlib.h>
#include <stddef.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_screen_types.h"
#include "DNA_scene_types.h"
#include "ED_screen.h"
#include "WM_api.h"
#include "WM_types.h"
Functions
static void rna_def_area_spaces (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_area (BlenderRNA *brna)
static void rna_def_region (BlenderRNA *brna)
static void rna_def_screen (BlenderRNA *brna)
void RNA_def_screen (BlenderRNA *brna)
Variables
EnumPropertyItem region_type_items []
Detailed Description
Definition in file rna_screen.c.
Function Documentation
static void rna_def_area (BlenderRNA * brna) [static]
Definition at line 139 of file rna_screen.c.
References HEADER_NO_PULLDOWN, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_CONTEXT_UPDATE, PROP_EDITABLE, PROP_ENUM, PROP_INT, PROP_NONE, PROP_UNSIGNED, rna_def_area_spaces(), RNA_def_function(), RNA_def_function_ui_description(), RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and space_type_items.
Referenced by RNA_def_screen().
static void rna_def_area_spaces (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 123 of file rna_screen.c.
References NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_pointer_sdna(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_area().
static void rna_def_region (BlenderRNA * brna) [static]
Definition at line 192 of file rna_screen.c.
References NULL, PROP_EDITABLE, PROP_ENUM, PROP_INT, PROP_NONE, PROP_UNSIGNED, RNA_def_function(), RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_screen().
static void rna_def_screen (BlenderRNA * brna) [static]
Definition at line 225 of file rna_screen.c.
References NC_SPACE, ND_SPACE_TIME, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_CONTEXT_UPDATE, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), TIME_ALL_3D_WIN, TIME_ALL_ANIM_WIN, TIME_ALL_BUTS_WIN, TIME_ALL_IMAGE_WIN, TIME_CLIPS, TIME_NODES, TIME_REGION, and TIME_SEQ.
Referenced by RNA_def_screen().
void RNA_def_screen (BlenderRNA * brna)
Definition at line 302 of file rna_screen.c.
References rna_def_area(), rna_def_region(), and rna_def_screen().
Variable Documentation
EnumPropertyItem region_type_items[]
Initial value:
 {
    {RGN_TYPE_WINDOW, "WINDOW", 0, "Window", ""},
    {RGN_TYPE_HEADER, "HEADER", 0, "Header", ""},
    {RGN_TYPE_CHANNELS, "CHANNELS", 0, "Channels", ""},
    {RGN_TYPE_TEMPORARY, "TEMPORARY", 0, "Temporary", ""},
    {RGN_TYPE_UI, "UI", 0, "UI", ""},
    {RGN_TYPE_TOOLS, "TOOLS", 0, "Tools", ""},
    {RGN_TYPE_TOOL_PROPS, "TOOL_PROPS", 0, "Tool Properties", ""},
    {RGN_TYPE_PREVIEW, "PREVIEW", 0, "Preview", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 39 of file rna_screen.c.
Referenced by RNA_api_keymaps(), rna_def_keyconfig(), and rna_def_panel().