Blender: WrapperVehicle Class Reference
WrapperVehicle Class Reference
Public Member Functions
WrapperVehicle (btRaycastVehicle *vehicle, PHY_IPhysicsController *chassis)
btRaycastVehicle * GetVehicle ()
PHY_IPhysicsController * GetChassis ()
virtual void AddWheel (PHY_IMotionState *motionState, PHY__Vector3 connectionPoint, PHY__Vector3 downDirection, PHY__Vector3 axleDirection, float suspensionRestLength, float wheelRadius, bool hasSteering)
void SyncWheels ()
virtual int GetNumWheels () const
virtual void GetWheelPosition (int wheelIndex, float &posX, float &posY, float &posZ) const
virtual void GetWheelOrientationQuaternion (int wheelIndex, float &quatX, float &quatY, float &quatZ, float &quatW) const
virtual float GetWheelRotation (int wheelIndex) const
virtual int GetUserConstraintId () const
virtual int GetUserConstraintType () const
virtual void SetSteeringValue (float steering, int wheelIndex)
virtual void ApplyEngineForce (float force, int wheelIndex)
virtual void ApplyBraking (float braking, int wheelIndex)
virtual void SetWheelFriction (float friction, int wheelIndex)
virtual void SetSuspensionStiffness (float suspensionStiffness, int wheelIndex)
virtual void SetSuspensionDamping (float suspensionDamping, int wheelIndex)
virtual void SetSuspensionCompression (float suspensionCompression, int wheelIndex)
virtual void SetRollInfluence (float rollInfluence, int wheelIndex)
virtual void SetCoordinateSystem (int rightIndex, int upIndex, int forwardIndex)
Detailed Description
Definition at line 73 of file CcdPhysicsEnvironment.cpp.
Constructor & Destructor Documentation
WrapperVehicle::WrapperVehicle (btRaycastVehicle * vehicle, PHY_IPhysicsController * chassis) [inline]
Definition at line 81 of file CcdPhysicsEnvironment.cpp.
Member Function Documentation
virtual void WrapperVehicle::AddWheel (PHY_IMotionState * motionState, PHY__Vector3 connectionPoint, PHY__Vector3 downDirection, PHY__Vector3 axleDirection, float suspensionRestLength, float wheelRadius, bool hasSteering) [inline, virtual]
Implements PHY_IVehicle.
Definition at line 97 of file CcdPhysicsEnvironment.cpp.
References btRaycastVehicle::addWheel(), and btWheelInfo::m_clientInfo.
virtual void WrapperVehicle::ApplyBraking (float braking, int wheelIndex) [inline, virtual]
Implements PHY_IVehicle.
Definition at line 201 of file CcdPhysicsEnvironment.cpp.
References btRaycastVehicle::getWheelInfo(), and btWheelInfo::m_brake.
virtual void WrapperVehicle::ApplyEngineForce (float force, int wheelIndex) [inline, virtual]
Implements PHY_IVehicle.
Definition at line 196 of file CcdPhysicsEnvironment.cpp.
References btRaycastVehicle::applyEngineForce().
PHY_IPhysicsController* WrapperVehicle::GetChassis () [inline]
Definition at line 92 of file CcdPhysicsEnvironment.cpp.
virtual int WrapperVehicle::GetNumWheels () const [inline, virtual]
Implements PHY_IVehicle.
Definition at line 137 of file CcdPhysicsEnvironment.cpp.
References btRaycastVehicle::getNumWheels().
Referenced by SyncWheels().
virtual int WrapperVehicle::GetUserConstraintId () const [inline, virtual]
Implements PHY_IVehicle.
Definition at line 181 of file CcdPhysicsEnvironment.cpp.
References btRaycastVehicle::getUserConstraintId().
virtual int WrapperVehicle::GetUserConstraintType () const [inline, virtual]
Implements PHY_IVehicle.
Definition at line 186 of file CcdPhysicsEnvironment.cpp.
References btRaycastVehicle::getUserConstraintType().
btRaycastVehicle* WrapperVehicle::GetVehicle () [inline]
Definition at line 87 of file CcdPhysicsEnvironment.cpp.
Referenced by CcdPhysicsEnvironment::getVehicleConstraint().
virtual void WrapperVehicle::GetWheelOrientationQuaternion (int wheelIndex, float & quatX, float & quatY, float & quatZ, float & quatW) const [inline, virtual]
Implements PHY_IVehicle.
Definition at line 149 of file CcdPhysicsEnvironment.cpp.
References btTransform::getRotation(), and btRaycastVehicle::getWheelTransformWS().
virtual void WrapperVehicle::GetWheelPosition (int wheelIndex, float & posX, float & posY, float & posZ) const [inline, virtual]
Implements PHY_IVehicle.
Definition at line 142 of file CcdPhysicsEnvironment.cpp.
References btTransform::getOrigin(), and btRaycastVehicle::getWheelTransformWS().
virtual float WrapperVehicle::GetWheelRotation (int wheelIndex) const [inline, virtual]
Implements PHY_IVehicle.
Definition at line 166 of file CcdPhysicsEnvironment.cpp.
References btRaycastVehicle::getWheelInfo(), and btWheelInfo::m_rotation.
virtual void WrapperVehicle::SetCoordinateSystem (int rightIndex, int upIndex, int forwardIndex) [inline, virtual]
Implements PHY_IVehicle.
Definition at line 259 of file CcdPhysicsEnvironment.cpp.
References btRaycastVehicle::setCoordinateSystem().
virtual void WrapperVehicle::SetRollInfluence (float rollInfluence, int wheelIndex) [inline, virtual]
Implements PHY_IVehicle.
Definition at line 250 of file CcdPhysicsEnvironment.cpp.
References btRaycastVehicle::getWheelInfo(), and btWheelInfo::m_rollInfluence.
virtual void WrapperVehicle::SetSteeringValue (float steering, int wheelIndex) [inline, virtual]
Implements PHY_IVehicle.
Definition at line 191 of file CcdPhysicsEnvironment.cpp.
References btRaycastVehicle::setSteeringValue().
virtual void WrapperVehicle::SetSuspensionCompression (float suspensionCompression, int wheelIndex) [inline, virtual]
Implements PHY_IVehicle.
Definition at line 239 of file CcdPhysicsEnvironment.cpp.
References btRaycastVehicle::getWheelInfo(), and btWheelInfo::m_wheelsDampingCompression.
virtual void WrapperVehicle::SetSuspensionDamping (float suspensionDamping, int wheelIndex) [inline, virtual]
Implements PHY_IVehicle.
Definition at line 230 of file CcdPhysicsEnvironment.cpp.
References btRaycastVehicle::getWheelInfo(), and btWheelInfo::m_wheelsDampingRelaxation.
virtual void WrapperVehicle::SetSuspensionStiffness (float suspensionStiffness, int wheelIndex) [inline, virtual]
Implements PHY_IVehicle.
Definition at line 220 of file CcdPhysicsEnvironment.cpp.
References btRaycastVehicle::getWheelInfo(), and btWheelInfo::m_suspensionStiffness.
virtual void WrapperVehicle::SetWheelFriction (float friction, int wheelIndex) [inline, virtual]
Implements PHY_IVehicle.
Definition at line 210 of file CcdPhysicsEnvironment.cpp.
References btRaycastVehicle::getWheelInfo(), and btWheelInfo::m_frictionSlip.
void WrapperVehicle::SyncWheels () [inline]
Definition at line 118 of file CcdPhysicsEnvironment.cpp.
References GetNumWheels(), btTransform::getOrigin(), btTransform::getRotation(), btRaycastVehicle::getWheelInfo(), i, btWheelInfo::m_clientInfo, btWheelInfo::m_worldTransform, PHY_IMotionState::setWorldOrientation(), PHY_IMotionState::setWorldPosition(), and btRaycastVehicle::updateWheelTransform().
Referenced by CcdPhysicsEnvironment::proceedDeltaTime().
The documentation for this class was generated from the following file:
CcdPhysicsEnvironment.cpp