Blender: ED_util.h File Reference
ED_util.h File Reference
Editors
Functions
void ED_editors_init (struct bContext *C)
void ED_editors_exit (struct bContext *C)
void ED_undo_push (struct bContext *C, const char *str)
void ED_undo_push_op (struct bContext *C, struct wmOperator *op)
void ED_undo_pop_op (struct bContext *C, struct wmOperator *op)
void ED_undo_pop (struct bContext *C)
void ED_undo_redo (struct bContext *C)
void ED_OT_undo (struct wmOperatorType *ot)
void ED_OT_undo_push (struct wmOperatorType *ot)
void ED_OT_redo (struct wmOperatorType *ot)
void ED_OT_undo_history (struct wmOperatorType *ot)
int ED_undo_operator_repeat (struct bContext *C, struct wmOperator *op)
void ED_undo_operator_repeat_cb (struct bContext *C, void *arg_op, void *arg_unused)
void ED_undo_operator_repeat_cb_evt (struct bContext *C, void *arg_op, int arg_unused)
int ED_undo_valid (const struct bContext *C, const char *undoname)
void undo_editmode_push (struct bContext *C, const char *name, void *(*getdata)(struct bContext *C), void(*freedata)(void *), void(*to_editmode)(void *, void *, void *), void *(*from_editmode)(void *, void *), int(*validate_undo)(void *, void *))
void undo_editmode_clear (void)
float * crazyspace_get_mapped_editverts (struct Scene *scene, struct Object *obedit)
void crazyspace_set_quats_editmesh (struct BMEditMesh *em, float *origcos, float *mappedcos, float *quats)
void crazyspace_set_quats_mesh (struct Mesh *me, float *origcos, float *mappedcos, float *quats)
int sculpt_get_first_deform_matrices (struct Scene *scene, struct Object *ob, float(**deformmats)[3][3], float(**deformcos)[3])
void crazyspace_build_sculpt (struct Scene *scene, struct Object *ob, float(**deformmats)[3][3], float(**deformcos)[3])
void apply_keyb_grid (int shift, int ctrl, float *val, float fac1, float fac2, float fac3, int invert)
int GetButStringLength (const char *str)
void unpack_menu (struct bContext *C, const char *opname, const char *id_name, const char *abs_name, const char *folder, struct PackedFile *pf)
Detailed Description
Definition in file ED_util.h.
Function Documentation
void apply_keyb_grid (int shift, int ctrl, float * val, float fac1, float fac2, float fac3, int invert)
Definition at line 135 of file ed_util.c.
References floorf.
Referenced by ed_marker_move_modal().
void crazyspace_build_sculpt (struct Scene * scene, struct Object * ob, float(**) deformmats[3][3], float(**) deformcos[3])
Definition at line 434 of file crazyspace.c.
References copy_m3_m3(), crazyspace_set_quats_mesh(), Object::data, ModifierTypeInfo::deformMatrices, ModifierTypeInfo::deformVerts, eModifierMode_Realtime, eModifierTypeType_OnlyDeform, i, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), MEM_mallocN(), mesh_getVertexCos(), modifier_isEnabled(), modifiers_getVirtualModifierList(), modifierType_getInfo(), mti, mul_m3_m3m3(), ModifierData::next, NULL, quat_to_mat3(), sculpt_get_first_deform_matrices(), Mesh::totvert, ModifierData::type, ModifierTypeInfo::type, and unit_m3().
Referenced by sculpt_update_mesh_elements().
float* crazyspace_get_mapped_editverts (struct Scene * scene, struct Object * obedit)
Definition at line 106 of file crazyspace.c.
References BMEditMesh::bm, CD_MASK_BAREMESH, Object::data, Mesh::edit_btmesh, editbmesh_get_derived_cage(), MappedUserData::flags, DerivedMesh::foreachMappedVert, make_vertexcos__mapFunc(), makeDerivedMesh(), MEM_callocN(), MEM_freeN(), modifiers_disable_subsurf_temporary(), DerivedMesh::release, BMesh::totvert, and MappedUserData::vertexcos.
Referenced by createTransEditVerts().
void crazyspace_set_quats_editmesh (struct BMEditMesh * em, float * origcos, float * mappedcos, float * quats)
Definition at line 141 of file crazyspace.c.
References BMEditMesh::bm, BM_edge_other_vert(), BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_index_get, BM_elem_index_set, BM_ELEM_SELECT, BM_face_other_edge_loop(), BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_VERT, BM_mesh_elem_index_ensure(), BM_VERT, BM_VERTS_OF_MESH, BMVert::co, BMLoop::e, BMesh::elem_index_dirty, BMLoop::f, if(), MEM_callocN(), MEM_freeN(), NULL, BMIter::p, set_crazy_vertex_quat(), BMesh::totvert, and BMLoop::v.
Referenced by createTransEditVerts().
void crazyspace_set_quats_mesh (struct Mesh * me, float * origcos, float * mappedcos, float * quats)
Definition at line 263 of file crazyspace.c.
References MVert::co, MVert::flag, i, if(), ME_VERT_TMP_TAG, Mesh::mface, Mesh::mvert, set_crazy_vertex_quat(), Mesh::totface, Mesh::totvert, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by crazyspace_build_sculpt().
void ED_editors_exit (struct bContext * C)
Definition at line 92 of file ed_util.c.
References CTX_data_main(), Object::data, ED_armature_edit_free(), ED_undo_paint_free(), EDBM_mesh_free(), Mesh::edit_btmesh, ListBase::first, Scene::id, MEM_freeN(), mesh_mirrtopo_table(), mesh_octree_table(), ID::next, NULL, OB_ARMATURE, OB_MESH, Scene::obedit, Main::scene, Object::type, and undo_editmode_clear().
Referenced by WM_exit_ext(), and wm_window_match_init().
void ED_editors_init (struct bContext * C)
Definition at line 68 of file ed_util.c.
References Scene::basact, CTX_data_main(), CTX_data_scene(), Object::data, data, ED_object_toggle_modes(), ListBase::first, Object::id, ID::lib, Object::mode, ID::next, NULL, OB_MODE_POSE, Main::object, and Base::object.
Referenced by WM_read_file(), and WM_read_homefile().
void ED_OT_redo (struct wmOperatorType * ot)
Definition at line 327 of file undo.c.
References wmOperatorType::description, ED_operator_screenactive(), ed_redo_exec(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by ED_operatortypes_screen().
void ED_OT_undo (struct wmOperatorType * ot)
Definition at line 300 of file undo.c.
References wmOperatorType::description, ED_operator_screenactive(), ed_undo_exec(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by ED_operatortypes_screen().
void ED_OT_undo_history (struct wmOperatorType * ot)
Definition at line 538 of file undo.c.
References wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, undo_history_exec(), and undo_history_invoke().
Referenced by ED_operatortypes_screen().
void ED_OT_undo_push (struct wmOperatorType * ot)
Definition at line 312 of file undo.c.
References wmOperatorType::description, ed_undo_push_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAXUNDONAME, wmOperatorType::name, OPTYPE_INTERNAL, RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_screen().
int ED_undo_operator_repeat (struct bContext * C, struct wmOperator * op)
Definition at line 341 of file undo.c.
References BKE_area_find_region_type(), wmOperatorType::check, CTX_data_scene(), CTX_wm_area(), CTX_wm_manager(), CTX_wm_region(), CTX_wm_region_set(), ED_undo_pop_op(), ED_undo_redo(), G, G_DEBUG, wmOperatorType::name, OPERATOR_FINISHED, RGN_TYPE_WINDOW, wmOperator::type, WM_jobs_test(), WM_operator_poll(), WM_operator_repeat(), and WM_operator_repeat_check().
Referenced by ED_undo_operator_repeat_cb(), ED_undo_operator_repeat_cb_evt(), and file_browse_exec().
void ED_undo_operator_repeat_cb (struct bContext * C, void * arg_op, void * arg_unused)
void ED_undo_operator_repeat_cb_evt (struct bContext * C, void * arg_op, int arg_unused)
Referenced by clip_panel_operator_redo(), view3d_panel_operator_redo(), and wm_block_create_redo().
void ED_undo_pop (struct bContext * C)
Definition at line 210 of file undo.c.
References ed_undo_step(), and NULL.
Referenced by redraw_timer_exec().
void ED_undo_pop_op (struct bContext * C, struct wmOperator * op)
Definition at line 225 of file undo.c.
References ed_undo_step(), wmOperatorType::name, and wmOperator::type.
Referenced by ED_undo_operator_repeat().
void ED_undo_push (struct bContext * C, const char * str)
Definition at line 81 of file undo.c.
References BKE_write_undo(), CTX_data_active_object(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_manager(), ELEM, wmWindowManager::file_saved, G, G_DEBUG, Object::mode, NC_WM, ND_DATACHANGED, NULL, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_PARTICLE_EDIT, OB_SURF, PE_undo_push(), Object::type, undo_push_armature(), undo_push_curve(), undo_push_font(), undo_push_lattice(), undo_push_mball(), undo_push_mesh(), USER_GLOBALUNDO, and WM_event_add_notifier().
Referenced by adjustGraphs(), BIF_retargetArmature(), colorband_add_cb(), colorband_del_cb(), colorband_flip_cb(), curvesurf_prim_add(), delete_fmodifier_cb(), do_logic_buts(), do_view3d_header_buttons(), ED_object_enter_editmode(), ED_object_exit_editmode(), ed_undo_push_exec(), ED_undo_push_op(), modifiers_convertToReal(), old_sca_move_actuator(), old_sca_move_controller(), old_sca_move_sensor(), outliner_action_set_exec(), outliner_animdata_operation_exec(), outliner_data_operation_exec(), outliner_group_operation_exec(), outliner_id_operation_exec(), outliner_item_activate(), outliner_object_operation_exec(), ui_apply_but_funcs_after(), and ui_node_link().
void ED_undo_push_op (struct bContext * C, struct wmOperator * op)
Definition at line 219 of file undo.c.
References ED_undo_push(), wmOperatorType::name, and wmOperator::type.
Referenced by wm_handler_fileselect_call(), wm_operator_finished(), and WM_operator_props_popup().
void ED_undo_redo (struct bContext * C)
Definition at line 214 of file undo.c.
References ed_undo_step(), and NULL.
Referenced by ED_undo_operator_repeat(), and redraw_timer_exec().
int ED_undo_valid (const struct bContext * C, const char * undoname)
Referenced by WM_operator_check_ui_enabled().
int GetButStringLength (const char * str)
int sculpt_get_first_deform_matrices (struct Scene * scene, struct Object * ob, float(**) deformmats[3][3], float(**) deformcos[3])
Definition at line 376 of file crazyspace.c.
References Object::data, ModifierTypeInfo::deformMatrices, eModifierMode_Realtime, eModifierTypeType_OnlyDeform, get_multires_modifier(), MEM_callocN(), mesh_create_derived(), mesh_getVertexCos(), modifier_isEnabled(), modifiers_getVirtualModifierList(), modifierType_getInfo(), mti, ModifierData::next, NULL, DerivedMesh::release, MultiresModifierData::sculptlvl, ModifierData::type, ModifierTypeInfo::type, and unit_m3().
Referenced by crazyspace_build_sculpt().
void undo_editmode_clear (void)
Definition at line 281 of file editmode_undo.c.
References BLI_freelistN(), ListBase::first, UndoElem::freedata, UndoElem::next, NULL, and UndoElem::undodata.
Referenced by ED_editors_exit(), and make_editNurb().
void undo_editmode_push (struct bContext * C, const char * name, void *(*)(struct bContext *C) getdata, void(*)(void *) freedata, void(*)(void *, void *, void *) to_editmode, void *(*)(void *, void *) from_editmode, int(*)(void *, void *) validate_undo)
Referenced by undo_push_armature(), undo_push_curve(), undo_push_font(), undo_push_lattice(), undo_push_mball(), and undo_push_mesh().
void unpack_menu (struct bContext * C, const char * opname, const char * id_name, const char * abs_name, const char * folder, struct PackedFile * pf)
Definition at line 163 of file ed_util.c.
References BLI_snprintf(), BLI_splitdirstring(), BLI_strncpy(), checkPackedFile(), FILE_MAX, FILE_MAXDIR, G, NULL, PF_DIFFERS, PF_EQUAL, PF_NOFILE, PF_REMOVE, PF_USE_LOCAL, PF_USE_ORIGINAL, PF_WRITE_LOCAL, PF_WRITE_ORIGINAL, RNA_enum_set(), RNA_string_set(), UI_ITEM_O_RETURN_PROPS, uiItemFullO_ptr(), uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), WM_OP_EXEC_DEFAULT, and WM_operatortype_find().
Referenced by image_unpack_invoke(), and sound_unpack_invoke().