Blender: frameacc.inl File Reference
frameacc.inl File Reference
Functions
VectorAcc operator+ (const VectorAcc &r1, const VectorAcc &r2)
VectorAcc operator- (const VectorAcc &r1, const VectorAcc &r2)
VectorAcc operator+ (const Vector &r1, const VectorAcc &r2)
VectorAcc operator- (const Vector &r1, const VectorAcc &r2)
VectorAcc operator+ (const VectorAcc &r1, const Vector &r2)
VectorAcc operator- (const VectorAcc &r1, const Vector &r2)
VectorAcc operator- (const VectorAcc &r)
VectorAcc operator* (const VectorAcc &r1, const VectorAcc &r2)
VectorAcc operator* (const VectorAcc &r1, const Vector &r2)
VectorAcc operator* (const Vector &r1, const VectorAcc &r2)
VectorAcc operator* (double r1, const VectorAcc &r2)
VectorAcc operator* (const VectorAcc &r1, double r2)
VectorAcc operator* (const doubleAcc &r1, const VectorAcc &r2)
VectorAcc operator* (const VectorAcc &r2, const doubleAcc &r1)
doubleAcc dot (const VectorAcc &lhs, const VectorAcc &rhs)
doubleAcc dot (const VectorAcc &lhs, const Vector &rhs)
doubleAcc dot (const Vector &lhs, const VectorAcc &rhs)
bool Equal (const VectorAcc &r1, const VectorAcc &r2, double eps)
bool Equal (const Vector &r1, const VectorAcc &r2, double eps)
bool Equal (const VectorAcc &r1, const Vector &r2, double eps)
VectorAcc operator/ (const VectorAcc &r1, double r2)
VectorAcc operator/ (const VectorAcc &r2, const doubleAcc &r1)
RotationAcc operator* (const RotationAcc &r1, const RotationAcc &r2)
RotationAcc operator* (const Rotation &r1, const RotationAcc &r2)
RotationAcc operator* (const RotationAcc &r1, const Rotation &r2)
VectorAcc operator* (const Rotation &R, const VectorAcc &x)
bool Equal (const RotationAcc &r1, const RotationAcc &r2, double eps)
bool Equal (const Rotation &r1, const RotationAcc &r2, double eps)
bool Equal (const RotationAcc &r1, const Rotation &r2, double eps)
FrameAcc operator* (const FrameAcc &lhs, const FrameAcc &rhs)
FrameAcc operator* (const FrameAcc &lhs, const Frame &rhs)
FrameAcc operator* (const Frame &lhs, const FrameAcc &rhs)
bool Equal (const FrameAcc &r1, const FrameAcc &r2, double eps)
bool Equal (const Frame &r1, const FrameAcc &r2, double eps)
bool Equal (const FrameAcc &r1, const Frame &r2, double eps)
TwistAcc operator* (const TwistAcc &lhs, double rhs)
TwistAcc operator* (double lhs, const TwistAcc &rhs)
TwistAcc operator/ (const TwistAcc &lhs, double rhs)
TwistAcc operator* (const TwistAcc &lhs, const doubleAcc &rhs)
TwistAcc operator* (const doubleAcc &lhs, const TwistAcc &rhs)
TwistAcc operator/ (const TwistAcc &lhs, const doubleAcc &rhs)
TwistAcc operator+ (const TwistAcc &lhs, const TwistAcc &rhs)
TwistAcc operator- (const TwistAcc &lhs, const TwistAcc &rhs)
TwistAcc operator- (const TwistAcc &arg)
bool Equal (const TwistAcc &a, const TwistAcc &b, double eps)
bool Equal (const Twist &a, const TwistAcc &b, double eps)
bool Equal (const TwistAcc &a, const Twist &b, double eps)
Function Documentation
doubleAcc dot (const VectorAcc & lhs, const VectorAcc & rhs)
Definition at line 136 of file frameacc.inl.
References dot().
doubleAcc dot (const VectorAcc & lhs, const Vector & rhs)
Definition at line 143 of file frameacc.inl.
References dot().
doubleAcc dot (const Vector & lhs, const VectorAcc & rhs)
Definition at line 150 of file frameacc.inl.
References dot().
bool Equal (const TwistAcc & a, const Twist & b, double eps)
Definition at line 593 of file frameacc.inl.
References KDL::Equal().
bool Equal (const FrameAcc & r1, const FrameAcc & r2, double eps)
Definition at line 392 of file frameacc.inl.
References KDL::Equal().
bool Equal (const Frame & r1, const FrameAcc & r2, double eps)
Definition at line 395 of file frameacc.inl.
References KDL::Equal().
bool Equal (const FrameAcc & r1, const Frame & r2, double eps)
Definition at line 398 of file frameacc.inl.
References KDL::Equal().
bool Equal (const VectorAcc & r1, const VectorAcc & r2, double eps)
Definition at line 158 of file frameacc.inl.
References KDL::Equal().
bool Equal (const Vector & r1, const VectorAcc & r2, double eps)
Definition at line 165 of file frameacc.inl.
References KDL::Equal().
bool Equal (const VectorAcc & r1, const Vector & r2, double eps)
Definition at line 172 of file frameacc.inl.
References KDL::Equal().
bool Equal (const TwistAcc & a, const TwistAcc & b, double eps)
Definition at line 585 of file frameacc.inl.
References KDL::Equal().
bool Equal (const Twist & a, const TwistAcc & b, double eps)
Definition at line 589 of file frameacc.inl.
References KDL::Equal().
bool Equal (const RotationAcc & r1, const RotationAcc & r2, double eps)
Definition at line 322 of file frameacc.inl.
References KDL::Equal().
bool Equal (const Rotation & r1, const RotationAcc & r2, double eps)
Definition at line 325 of file frameacc.inl.
References KDL::Equal().
bool Equal (const RotationAcc & r1, const Rotation & r2, double eps)
Definition at line 329 of file frameacc.inl.
References KDL::Equal().
VectorAcc operator* (const VectorAcc & r1, const Vector & r2)
Definition at line 58 of file frameacc.inl.
FrameAcc operator* (const Frame & lhs, const FrameAcc & rhs)
Definition at line 356 of file frameacc.inl.
FrameAcc operator* (const FrameAcc & lhs, const Frame & rhs)
Definition at line 352 of file frameacc.inl.
FrameAcc operator* (const FrameAcc & lhs, const FrameAcc & rhs)
Definition at line 348 of file frameacc.inl.
RotationAcc operator* (const RotationAcc & r1, const RotationAcc & r2)
Definition at line 191 of file frameacc.inl.
TwistAcc operator* (const TwistAcc & lhs, double rhs)
Definition at line 470 of file frameacc.inl.
VectorAcc operator* (const Rotation & R, const VectorAcc & x)
Definition at line 253 of file frameacc.inl.
TwistAcc operator* (double lhs, const TwistAcc & rhs)
Definition at line 475 of file frameacc.inl.
TwistAcc operator* (const TwistAcc & lhs, const doubleAcc & rhs)
Definition at line 486 of file frameacc.inl.
VectorAcc operator* (const Vector & r1, const VectorAcc & r2)
Definition at line 62 of file frameacc.inl.
TwistAcc operator* (const doubleAcc & lhs, const TwistAcc & rhs)
Definition at line 491 of file frameacc.inl.
VectorAcc operator* (double r1, const VectorAcc & r2)
Definition at line 69 of file frameacc.inl.
VectorAcc operator* (const VectorAcc & r1, const VectorAcc & r2)
Definition at line 51 of file frameacc.inl.
RotationAcc operator* (const Rotation & r1, const RotationAcc & r2)
Definition at line 198 of file frameacc.inl.
RotationAcc operator* (const RotationAcc & r1, const Rotation & r2)
Definition at line 202 of file frameacc.inl.
VectorAcc operator* (const doubleAcc & r1, const VectorAcc & r2)
Definition at line 77 of file frameacc.inl.
VectorAcc operator* (const VectorAcc & r1, double r2)
Definition at line 73 of file frameacc.inl.
VectorAcc operator* (const VectorAcc & r2, const doubleAcc & r1)
Definition at line 84 of file frameacc.inl.
VectorAcc operator+ (const Vector & r1, const VectorAcc & r2)
Definition at line 30 of file frameacc.inl.
VectorAcc operator+ (const VectorAcc & r1, const VectorAcc & r2)
Definition at line 23 of file frameacc.inl.
TwistAcc operator+ (const TwistAcc & lhs, const TwistAcc & rhs)
Definition at line 504 of file frameacc.inl.
VectorAcc operator+ (const VectorAcc & r1, const Vector & r2)
Definition at line 37 of file frameacc.inl.
VectorAcc operator- (const VectorAcc & r1, const Vector & r2)
Definition at line 41 of file frameacc.inl.
TwistAcc operator- (const TwistAcc & lhs, const TwistAcc & rhs)
Definition at line 509 of file frameacc.inl.
VectorAcc operator- (const VectorAcc & r)
Definition at line 46 of file frameacc.inl.
VectorAcc operator- (const VectorAcc & r1, const VectorAcc & r2)
Definition at line 27 of file frameacc.inl.
VectorAcc operator- (const Vector & r1, const VectorAcc & r2)
Definition at line 34 of file frameacc.inl.
TwistAcc operator- (const TwistAcc & arg)
Definition at line 515 of file frameacc.inl.
TwistAcc operator/ (const TwistAcc & lhs, double rhs)
Definition at line 480 of file frameacc.inl.
VectorAcc operator/ (const VectorAcc & r2, const doubleAcc & r1)
Definition at line 183 of file frameacc.inl.
VectorAcc operator/ (const VectorAcc & r1, double r2)
Definition at line 179 of file frameacc.inl.
TwistAcc operator/ (const TwistAcc & lhs, const doubleAcc & rhs)
Definition at line 496 of file frameacc.inl.