Blender: ChainDrawer Class Reference
ChainDrawer Class Reference
#include <ChainDrawer.h>
Public Member Functions
void SetMouseHandler (MyGlutMouseHandler *mouse_handler)
void SetKeyHandler (MyGlutKeyHandler *key_handler)
void SetChain (IK_Chain_ExternPtr *chains, int chain_num)
void Draw ()
~ChainDrawer ()
Static Public Member Functions
static ChainDrawer * New ()
Detailed Description
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) 2001-2002 by NaN Holding BV. All rights reserved.
The Original Code is: all of this file.
Contributor(s): none yet.
***** END GPL LICENSE BLOCK *****
Definition at line 40 of file ChainDrawer.h.
Constructor & Destructor Documentation
ChainDrawer::~ChainDrawer () [inline]
Definition at line 88 of file ChainDrawer.h.
Member Function Documentation
void ChainDrawer::Draw (void) [inline, virtual]
Implements GlutDrawer.
Definition at line 75 of file ChainDrawer.h.
References MyGlutMouseHandler::AngleX(), and MyGlutMouseHandler::AngleY().
static ChainDrawer* ChainDrawer::New () [inline, static]
Definition at line 45 of file ChainDrawer.h.
Referenced by main().
void ChainDrawer::SetChain (IK_Chain_ExternPtr * chains, int chain_num) [inline]
Definition at line 65 of file ChainDrawer.h.
void ChainDrawer::SetKeyHandler (MyGlutKeyHandler * key_handler) [inline]
Definition at line 58 of file ChainDrawer.h.
void ChainDrawer::SetMouseHandler (MyGlutMouseHandler * mouse_handler) [inline]
Definition at line 51 of file ChainDrawer.h.
The documentation for this class was generated from the following file:
ChainDrawer.h