Blender: btMatrix3x3.h File Reference
btMatrix3x3.h File Reference
#include "btVector3.h"
#include "btQuaternion.h"
Classes
class btMatrix3x3
The btMatrix3x3 class implements a 3x3 rotation matrix, to perform linear algebra in combination with btQuaternion, btTransform and btVector3. Make sure to only include a pure orthogonal matrix without scaling.
struct btMatrix3x3FloatData
for serialization
struct btMatrix3x3DoubleData
for serialization
Defines
#define btMatrix3x3Data btMatrix3x3FloatData
Functions
SIMD_FORCE_INLINE btMatrix3x3 operator* (const btMatrix3x3 &m, const btScalar &k)
SIMD_FORCE_INLINE btMatrix3x3 operator+ (const btMatrix3x3 &m1, const btMatrix3x3 &m2)
SIMD_FORCE_INLINE btMatrix3x3 operator- (const btMatrix3x3 &m1, const btMatrix3x3 &m2)
SIMD_FORCE_INLINE btVector3 operator* (const btMatrix3x3 &m, const btVector3 &v)
SIMD_FORCE_INLINE btVector3 operator* (const btVector3 &v, const btMatrix3x3 &m)
SIMD_FORCE_INLINE btMatrix3x3 operator* (const btMatrix3x3 &m1, const btMatrix3x3 &m2)
SIMD_FORCE_INLINE bool operator== (const btMatrix3x3 &m1, const btMatrix3x3 &m2)
Equality operator between two matrices It will test all elements are equal.
Define Documentation
#define btMatrix3x3Data btMatrix3x3FloatData
Definition at line 25 of file btMatrix3x3.h.
Function Documentation
SIMD_FORCE_INLINE btMatrix3x3 operator* (const btMatrix3x3 & m, const btScalar & k)
Definition at line 553 of file btMatrix3x3.h.
SIMD_FORCE_INLINE btVector3 operator* (const btMatrix3x3 & m, const btVector3 & v)
Definition at line 679 of file btMatrix3x3.h.
References dot().
SIMD_FORCE_INLINE btVector3 operator* (const btVector3 & v, const btMatrix3x3 & m)
Definition at line 686 of file btMatrix3x3.h.
References btMatrix3x3::tdotx(), btMatrix3x3::tdoty(), and btMatrix3x3::tdotz().
SIMD_FORCE_INLINE btMatrix3x3 operator* (const btMatrix3x3 & m1, const btMatrix3x3 & m2)
Definition at line 692 of file btMatrix3x3.h.
References btMatrix3x3::tdotx(), btMatrix3x3::tdoty(), and btMatrix3x3::tdotz().
SIMD_FORCE_INLINE btMatrix3x3 operator+ (const btMatrix3x3 & m1, const btMatrix3x3 & m2)
Definition at line 562 of file btMatrix3x3.h.
SIMD_FORCE_INLINE btMatrix3x3 operator- (const btMatrix3x3 & m1, const btMatrix3x3 & m2)
Definition at line 577 of file btMatrix3x3.h.
SIMD_FORCE_INLINE bool operator== (const btMatrix3x3 & m1, const btMatrix3x3 & m2)
Equality operator between two matrices It will test all elements are equal.
Definition at line 717 of file btMatrix3x3.h.