Blender: BlockDXT1 Struct Reference
BlockDXT1 Struct Reference
DXT1 block.
#include <BlockDXT.h>
Public Member Functions
bool isFourColorMode () const
Return true if the block uses four color mode, false otherwise.
uint evaluatePalette (Color32 color_array[4]) const
uint evaluatePaletteNV5x (Color32 color_array[4]) const
void evaluatePalette3 (Color32 color_array[4]) const
void evaluatePalette4 (Color32 color_array[4]) const
void decodeBlock (ColorBlock *block) const
void decodeBlockNV5x (ColorBlock *block) const
void setIndices (int *idx)
void flip4 ()
Flip DXT1 block vertically.
void flip2 ()
Flip half DXT1 block vertically.
Public Attributes
Color16 col0
Color16 col1
union {
uint8 row [4]
uint indices
};
Detailed Description
DXT1 block.
Definition at line 67 of file BlockDXT.h.
Member Function Documentation
void BlockDXT1::decodeBlock (ColorBlock * block) const
Definition at line 223 of file BlockDXT.cpp.
References ColorBlock::color(), evaluatePalette(), i, and row.
Referenced by BlockDXT5::decodeBlock(), and BlockDXT3::decodeBlock().
void BlockDXT1::decodeBlockNV5x (ColorBlock * block) const
Definition at line 238 of file BlockDXT.cpp.
References ColorBlock::color(), evaluatePaletteNV5x(), i, and row.
Referenced by BlockDXT3::decodeBlockNV5x(), and BlockDXT5::decodeBlockNV5x().
uint BlockDXT1::evaluatePalette (Color32 color_array[4]) const
Definition at line 67 of file BlockDXT.cpp.
References Color32::a, Color32::b, Color16::b, col0, col1, Color16::g, Color32::g, Color16::r, Color32::r, and Color16::u.
Referenced by decodeBlock().
void BlockDXT1::evaluatePalette3 (Color32 color_array[4]) const
Definition at line 172 of file BlockDXT.cpp.
References Color32::a, Color32::b, Color16::b, col0, col1, Color16::g, Color32::g, Color16::r, and Color32::r.
void BlockDXT1::evaluatePalette4 (Color32 color_array[4]) const
Definition at line 198 of file BlockDXT.cpp.
References Color32::a, Color32::b, Color16::b, col0, col1, Color16::g, Color32::g, Color16::r, and Color32::r.
uint BlockDXT1::evaluatePaletteNV5x (Color32 color_array[4]) const
Definition at line 125 of file BlockDXT.cpp.
References Color32::a, Color32::b, Color16::b, col0, col1, Color16::g, Color32::g, Color16::r, Color32::r, and Color16::u.
Referenced by decodeBlockNV5x().
void BlockDXT1::flip2 () [inline]
Flip half DXT1 block vertically.
Definition at line 270 of file BlockDXT.cpp.
References row, and swap().
Referenced by BlockDXT5::flip2(), and BlockDXT3::flip2().
void BlockDXT1::flip4 () [inline]
Flip DXT1 block vertically.
Definition at line 263 of file BlockDXT.cpp.
References row, and swap().
Referenced by BlockDXT5::flip4(), and BlockDXT3::flip4().
bool BlockDXT1::isFourColorMode () const [inline]
Return true if the block uses four color mode, false otherwise.
Definition at line 94 of file BlockDXT.h.
References col0, col1, and Color16::u.
void BlockDXT1::setIndices (int * idx)
Definition at line 253 of file BlockDXT.cpp.
References i, and indices.
Member Data Documentation
union { ... }
Color16 BlockDXT1::col0
Definition at line 69 of file BlockDXT.h.
Referenced by evaluatePalette(), evaluatePalette3(), evaluatePalette4(), evaluatePaletteNV5x(), isFourColorMode(), and mem_read().
Color16 BlockDXT1::col1
Definition at line 70 of file BlockDXT.h.
Referenced by evaluatePalette(), evaluatePalette3(), evaluatePalette4(), evaluatePaletteNV5x(), isFourColorMode(), and mem_read().
uint BlockDXT1::indices
Definition at line 73 of file BlockDXT.h.
Referenced by mem_read(), and setIndices().
uint8 BlockDXT1::row[4]
Definition at line 72 of file BlockDXT.h.
Referenced by decodeBlock(), decodeBlockNV5x(), flip2(), and flip4().
The documentation for this struct was generated from the following files:
BlockDXT.h
BlockDXT.cpp