Blender: KX_NavMeshObject.cpp File Reference
KX_NavMeshObject.cpp File Reference
#include "MEM_guardedalloc.h"
#include "BLI_math_vector.h"
#include "KX_NavMeshObject.h"
#include "RAS_MeshObject.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "BKE_scene.h"
#include "BKE_customdata.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_DerivedMesh.h"
#include "BKE_navmesh_conversion.h"
#include "KX_PythonInit.h"
#include "KX_PyMath.h"
#include "Value.h"
#include "Recast.h"
#include "DetourStatNavMeshBuilder.h"
#include "KX_ObstacleSimulation.h"
Functions
static void calcMeshBounds (const float *vert, int nverts, float *bmin, float *bmax)
void flipAxes (float *vec)
Variables
static const int MAX_PATH_LEN = 256
static const float polyPickExt [3] = {2, 4, 2}
Function Documentation
static void calcMeshBounds (const float * vert, int nverts, float * bmin, float * bmax) [static]
Definition at line 55 of file KX_NavMeshObject.cpp.
References i.
Referenced by KX_NavMeshObject::BuildNavMesh().
void flipAxes (float * vec) [inline]
Definition at line 72 of file KX_NavMeshObject.cpp.
References swap().
Referenced by KX_NavMeshObject::BuildNavMesh(), KX_NavMeshObject::DrawNavMesh(), KX_NavMeshObject::FindPath(), getNavmeshNormal(), and KX_NavMeshObject::Raycast().
Variable Documentation
const int MAX_PATH_LEN = 256 [static]
Definition at line 52 of file KX_NavMeshObject.cpp.
Referenced by KX_NavMeshObject::Raycast().
const float polyPickExt[3] = {2, 4, 2} [static]
Definition at line 53 of file KX_NavMeshObject.cpp.
Referenced by KX_NavMeshObject::FindPath(), getNavmeshNormal(), and KX_NavMeshObject::Raycast().