Blender: rna_tracking.c File Reference
rna_tracking.c File Reference
RNA
#include <stdlib.h>
#include <limits.h>
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BKE_movieclip.h"
#include "BKE_tracking.h"
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_movieclip_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "WM_types.h"
Functions
static void rna_def_trackingSettings (BlenderRNA *brna)
static void rna_def_trackingCamera (BlenderRNA *brna)
static void rna_def_trackingMarker (BlenderRNA *brna)
static void rna_def_trackingMarkers (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_trackingTrack (BlenderRNA *brna)
static void rna_def_trackingStabilization (BlenderRNA *brna)
static void rna_def_reconstructedCamera (BlenderRNA *brna)
static void rna_def_trackingReconstruction (BlenderRNA *brna)
static void rna_def_trackingTracks (BlenderRNA *brna)
static void rna_def_trackingObjectTracks (BlenderRNA *brna)
static void rna_def_trackingObject (BlenderRNA *brna)
static void rna_def_trackingObjects (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_tracking (BlenderRNA *brna)
void RNA_def_tracking (BlenderRNA *brna)
Variables
static EnumPropertyItem tracker_items []
static EnumPropertyItem pattern_match_items []
static int rna_matrix_dimsize_4x4 [] = {4, 4}
Detailed Description
Definition in file rna_tracking.c.
Function Documentation
static void rna_def_reconstructedCamera (BlenderRNA * brna) [static]
Definition at line 1185 of file rna_tracking.c.
References NULL, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_MATRIX, PROP_NONE, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_multi_array(), RNA_def_property_ui_text(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by rna_def_trackingReconstruction().
static void rna_def_tracking (BlenderRNA * brna) [static]
Definition at line 1372 of file rna_tracking.c.
References NC_MOVIECLIP, ND_DISPLAY, NULL, PROP_ANIMATABLE, PROP_COLLECTION, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_ui_text(), rna_def_trackingCamera(), rna_def_trackingObject(), rna_def_trackingObjects(), rna_def_trackingObjectTracks(), rna_def_trackingReconstruction(), rna_def_trackingSettings(), rna_def_trackingStabilization(), rna_def_trackingTrack(), and rna_def_trackingTracks().
Referenced by RNA_def_tracking().
void RNA_def_tracking (BlenderRNA * brna)
Definition at line 1434 of file rna_tracking.c.
References rna_def_tracking().
static void rna_def_trackingCamera (BlenderRNA * brna) [static]
Definition at line 706 of file rna_tracking.c.
References CAMERA_UNITS_MM, CAMERA_UNITS_PX, NA_EDITED, NC_MOVIECLIP, ND_DISPLAY, NULL, PROP_ANIMATABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_default(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), and RNA_def_struct_ui_text().
Referenced by rna_def_tracking().
static void rna_def_trackingMarker (BlenderRNA * brna) [static]
Definition at line 794 of file rna_tracking.c.
References FLT_MAX, MARKER_DISABLED, NA_EDITED, NC_MOVIECLIP, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_TRANSLATION, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_text(), and RNA_TRANSLATION_PREC_DEFAULT.
Referenced by rna_def_trackingTrack().
static void rna_def_trackingMarkers (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 824 of file rna_tracking.c.
References MAXFRAME, MINFRAME, NULL, PROP_REQUIRED, RNA_def_float_vector(), RNA_def_function(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_trackingTrack().
static void rna_def_trackingObject (BlenderRNA * brna) [static]
Definition at line 1292 of file rna_tracking.c.
References MAX_ID_NAME, NA_EDITED, NC_MOVIECLIP, ND_DISPLAY, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_float_default(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_srna(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_ui_text(), and TRACKING_OBJECT_CAMERA.
Referenced by rna_def_tracking().
static void rna_def_trackingObjects (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1339 of file rna_tracking.c.
References NULL, PROP_EDITABLE, PROP_NEVER_UNLINK, PROP_NONE, PROP_POINTER, PROP_REQUIRED, RNA_def_function(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_tracking().
static void rna_def_trackingObjectTracks (BlenderRNA * brna) [static]
Definition at line 1268 of file rna_tracking.c.
References FUNC_USE_SELF_ID, MAXFRAME, MINFRAME, NULL, PROP_EDITABLE, PROP_NEVER_UNLINK, PROP_NONE, PROP_POINTER, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_tracking().
static void rna_def_trackingReconstruction (BlenderRNA * brna) [static]
Definition at line 1214 of file rna_tracking.c.
References NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_float_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), rna_def_reconstructedCamera(), RNA_def_struct(), RNA_def_struct_ui_text(), and TRACKING_RECONSTRUCTED.
Referenced by rna_def_tracking().
static void rna_def_trackingSettings (BlenderRNA * brna) [static]
Definition at line 501 of file rna_tracking.c.
References FLT_MAX, NC_MOVIECLIP, ND_DISPLAY, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, REFINE_FOCAL_LENGTH, REFINE_PRINCIPAL_POINT, REFINE_RADIAL_DISTORTION_K1, REFINE_RADIAL_DISTORTION_K2, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_default(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_icon(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_text(), TRACK_DISABLE_BLUE, TRACK_DISABLE_GREEN, TRACK_DISABLE_RED, TRACKING_CLEAN_DELETE_SEGMENT, TRACKING_CLEAN_DELETE_TRACK, TRACKING_CLEAN_SELECT, TRACKING_SETTINGS_SHOW_DEFAULT_EXPANDED, TRACKING_SPEED_DOUBLE, TRACKING_SPEED_HALF, TRACKING_SPEED_QUARTER, and TRACKING_SPEED_REALTIME.
Referenced by rna_def_tracking().
static void rna_def_trackingStabilization (BlenderRNA * brna) [static]
Definition at line 1087 of file rna_tracking.c.
References NA_EDITED, NC_MOVIECLIP, ND_DISPLAY, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_ui_text(), TRACKING_2D_STABILIZATION, TRACKING_AUTOSCALE, TRACKING_FILTER_BICUBIC, TRACKING_FILTER_BILINEAR, TRACKING_FILTER_NEAREAST, and TRACKING_STABILIZE_ROTATION.
Referenced by rna_def_tracking().
static void rna_def_trackingTrack (BlenderRNA * brna) [static]
Definition at line 862 of file rna_tracking.c.
References FLT_MAX, MAX_ID_NAME, NA_EDITED, NC_MOVIECLIP, ND_DISPLAY, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_COLOR, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_STRING, PROP_TRANSLATION, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), rna_def_trackingMarker(), rna_def_trackingMarkers(), RNA_TRANSLATION_PREC_DEFAULT, SELECT, TRACK_CUSTOMCOLOR, TRACK_DISABLE_BLUE, TRACK_DISABLE_GREEN, TRACK_DISABLE_RED, TRACK_HAS_BUNDLE, TRACK_HIDDEN, TRACK_LOCKED, and TRACK_PREVIEW_GRAYSCALE.
Referenced by rna_def_tracking().
static void rna_def_trackingTracks (BlenderRNA * brna) [static]
Definition at line 1244 of file rna_tracking.c.
References FUNC_USE_SELF_ID, MAXFRAME, MINFRAME, NULL, PROP_EDITABLE, PROP_NEVER_UNLINK, PROP_NONE, PROP_POINTER, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_tracking().
Variable Documentation
EnumPropertyItem pattern_match_items[] [static]
Initial value:
 {
    {TRACK_MATCH_KEYFRAME, "KEYFRAME", 0, "Keyframe", "Track pattern from keyframe to next frame"},
    {TRACK_MATCH_PREVFRAME, "PREV_FRAME", 0, "Previous frame", "Track pattern from current frame to next frame"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 494 of file rna_tracking.c.
int rna_matrix_dimsize_4x4[] = {4, 4} [static]
Definition at line 499 of file rna_tracking.c.
EnumPropertyItem tracker_items[] [static]
Initial value:
 {
    {TRACKER_KLT, "KLT", 0, "KLT",
                  "KanadeLucasTomasi tracker which works with most of video clips, a bit slower than SAD"},
    {TRACKER_SAD, "SAD", 0, "SAD", "Sum of Absolute Differences tracker which can be used when KLT tracker fails"},
    {TRACKER_HYBRID, "Hybrid", 0, "Hybrid", "A hybrid tracker that uses SAD for rough tracking, KLT for refinement."},
    {0, NULL, 0, NULL, NULL}}
Definition at line 487 of file rna_tracking.c.