Blender: btConvexTriangleCallback Class Reference
btConvexTriangleCallback Class Reference
For each triangle in the concave mesh that overlaps with the AABB of a convex (m_convexProxy), processTriangle is called.
#include <btConvexConcaveCollisionAlgorithm.h>
Public Member Functions
btConvexTriangleCallback (btDispatcher *dispatcher, btCollisionObject *body0, btCollisionObject *body1, bool isSwapped)
void setTimeStepAndCounters (btScalar collisionMarginTriangle, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
virtual ~btConvexTriangleCallback ()
virtual void processTriangle (btVector3 *triangle, int partId, int triangleIndex)
void clearCache ()
SIMD_FORCE_INLINE const btVector3 & getAabbMin () const
SIMD_FORCE_INLINE const btVector3 & getAabbMax () const
Public Attributes
int m_triangleCount
btPersistentManifold * m_manifoldPtr
Detailed Description
For each triangle in the concave mesh that overlaps with the AABB of a convex (m_convexProxy), processTriangle is called.
Definition at line 29 of file btConvexConcaveCollisionAlgorithm.h.
Constructor & Destructor Documentation
btConvexTriangleCallback::btConvexTriangleCallback (btDispatcher * dispatcher, btCollisionObject * body0, btCollisionObject * body1, bool isSwapped)
Definition at line 49 of file btConvexConcaveCollisionAlgorithm.cpp.
References clearCache(), btDispatcher::getNewManifold(), and m_manifoldPtr.
btConvexTriangleCallback::~btConvexTriangleCallback () [virtual]
Definition at line 64 of file btConvexConcaveCollisionAlgorithm.cpp.
References clearCache(), m_manifoldPtr, and btDispatcher::releaseManifold().
Member Function Documentation
void btConvexTriangleCallback::clearCache ()
Definition at line 72 of file btConvexConcaveCollisionAlgorithm.cpp.
References btDispatcher::clearManifold(), and m_manifoldPtr.
Referenced by btConvexTriangleCallback(), btConvexConcaveCollisionAlgorithm::clearCache(), and ~btConvexTriangleCallback().
SIMD_FORCE_INLINE const btVector3& btConvexTriangleCallback::getAabbMax () const [inline]
Definition at line 62 of file btConvexConcaveCollisionAlgorithm.h.
Referenced by btConvexConcaveCollisionAlgorithm::processCollision().
SIMD_FORCE_INLINE const btVector3& btConvexTriangleCallback::getAabbMin () const [inline]
Definition at line 58 of file btConvexConcaveCollisionAlgorithm.h.
Referenced by btConvexConcaveCollisionAlgorithm::processCollision().
void btConvexTriangleCallback::processTriangle (btVector3 * triangle, int partId, int triangleIndex) [virtual]
debug drawing of the overlapping triangles
Implements btTriangleCallback.
Definition at line 79 of file btConvexConcaveCollisionAlgorithm.cpp.
References btIDebugDraw::DBG_DrawWireframe, btIDebugDraw::drawLine(), btDispatcher::findAlgorithm(), btDispatcher::freeCollisionAlgorithm(), btManifoldResult::getBody0Internal(), btIDebugDraw::getDebugMode(), btDispatcherInfo::m_debugDraw, btCollisionAlgorithmConstructionInfo::m_dispatcher1, m_manifoldPtr, btCollisionAlgorithm::processCollision(), btManifoldResult::setShapeIdentifiersA(), btManifoldResult::setShapeIdentifiersB(), and btCollisionAlgorithm::~btCollisionAlgorithm().
void btConvexTriangleCallback::setTimeStepAndCounters (btScalar collisionMarginTriangle, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut)
Definition at line 145 of file btConvexConcaveCollisionAlgorithm.cpp.
References btCollisionShape::getAabb().
Referenced by btConvexConcaveCollisionAlgorithm::processCollision().
Member Data Documentation
btPersistentManifold* btConvexTriangleCallback::m_manifoldPtr
Definition at line 46 of file btConvexConcaveCollisionAlgorithm.h.
Referenced by btConvexTriangleCallback(), clearCache(), btConvexConcaveCollisionAlgorithm::getAllContactManifolds(), btConvexConcaveCollisionAlgorithm::processCollision(), processTriangle(), and ~btConvexTriangleCallback().
int btConvexTriangleCallback::m_triangleCount
Definition at line 44 of file btConvexConcaveCollisionAlgorithm.h.
The documentation for this class was generated from the following files:
btConvexConcaveCollisionAlgorithm.h
btConvexConcaveCollisionAlgorithm.cpp