Blender: node_texture_curves.c File Reference
node_texture_curves.c File Reference
texnodes
#include "node_texture_util.h"
#include "NOD_texture.h"
Functions
static void time_colorfn (float *out, TexParams *p, bNode *node, bNodeStack **UNUSED(in), short UNUSED(thread))
static void time_exec (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
static void time_init (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_tex_curve_time (bNodeTreeType *ttype)
static void rgb_colorfn (float *out, TexParams *p, bNode *node, bNodeStack **in, short thread)
static void rgb_exec (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
static void rgb_init (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_tex_curve_rgb (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate time_outputs []
static bNodeSocketTemplate rgb_inputs []
static bNodeSocketTemplate rgb_outputs []
Detailed Description
Definition in file node_texture_curves.c.
Function Documentation
void register_node_type_tex_curve_rgb (bNodeTreeType * ttype)
Definition at line 113 of file node_texture_curves.c.
References NODE_CLASS_OP_COLOR, node_copy_curves(), node_free_curves(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), rgb_exec(), rgb_init(), and TEX_NODE_CURVE_RGB.
Referenced by registerTextureNodes().
void register_node_type_tex_curve_time (bNodeTreeType * ttype)
Definition at line 69 of file node_texture_curves.c.
References NODE_CLASS_INPUT, node_copy_curves(), node_free_curves(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, TEX_NODE_CURVE_TIME, time_exec(), and time_init().
Referenced by registerTextureNodes().
static void rgb_colorfn (float * out, TexParams * p, bNode * node, bNodeStack ** in, short thread) [static]
Definition at line 94 of file node_texture_curves.c.
References curvemapping_evaluateRGBF(), bNode::storage, and tex_input_rgba().
Referenced by rgb_exec().
static void rgb_exec (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 103 of file node_texture_curves.c.
References rgb_colorfn(), and tex_output().
Referenced by register_node_type_tex_curve_rgb().
static void rgb_init (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 108 of file node_texture_curves.c.
References curvemapping_add(), and bNode::storage.
Referenced by register_node_type_tex_curve_rgb().
static void time_colorfn (float * out, TexParams * p, bNode * node, bNodeStack ** UNUSEDin, short UNUSEDthread) [static]
Definition at line 44 of file node_texture_curves.c.
References TexParams::cfra, CLAMPIS, curvemapping_evaluateF(), bNode::custom1, bNode::custom2, and bNode::storage.
Referenced by time_exec().
static void time_exec (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 56 of file node_texture_curves.c.
References tex_output(), and time_colorfn().
Referenced by register_node_type_tex_curve_time().
static void time_init (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 62 of file node_texture_curves.c.
References curvemapping_add(), bNode::custom1, bNode::custom2, and bNode::storage.
Referenced by register_node_type_tex_curve_time().
Variable Documentation
bNodeSocketTemplate rgb_inputs[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Color",  0.0f, 0.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 84 of file node_texture_curves.c.
bNodeSocketTemplate rgb_outputs[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Color"},
    {   -1, 0, ""   }
}
Definition at line 89 of file node_texture_curves.c.
bNodeSocketTemplate time_outputs[] [static]
Initial value:
 {
    { SOCK_FLOAT, 0, "Value" },
    { -1, 0, "" }
}
Definition at line 39 of file node_texture_curves.c.