Blender: node_composite_channelMatte.c File Reference
node_composite_channelMatte.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_normalized_rgba_to_ycca2 (bNode *UNUSED(node), float *out, float *in)
static void do_normalized_ycca_to_rgba2 (bNode *UNUSED(node), float *out, float *in)
static void do_channel_matte (bNode *node, float *out, float *in)
static void node_composit_exec_channel_matte (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_channel_matte (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_channel_matte (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_channel_matte_in []
static bNodeSocketTemplate cmp_node_channel_matte_out []
Detailed Description
Definition in file node_composite_channelMatte.c.
Function Documentation
static void do_channel_matte (bNode * node, float * out, float * in) [static]
Definition at line 69 of file node_composite_channelMatte.c.
References NodeChroma::algorithm, NodeChroma::channel, bNode::custom2, MAX2, bNode::storage, NodeChroma::t1, and NodeChroma::t2.
Referenced by node_composit_exec_channel_matte().
static void do_normalized_rgba_to_ycca2 (bNode * UNUSEDnode, float * out, float * in) [static]
Definition at line 48 of file node_composite_channelMatte.c.
References BLI_YCC_ITU_BT601, and rgb_to_ycc().
Referenced by node_composit_exec_channel_matte().
static void do_normalized_ycca_to_rgba2 (bNode * UNUSEDnode, float * out, float * in) [static]
Definition at line 58 of file node_composite_channelMatte.c.
References BLI_YCC_ITU_BT601, and ycc_to_rgb().
Referenced by node_composit_exec_channel_matte().
static void node_composit_exec_channel_matte (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 128 of file node_composite_channelMatte.c.
References CB_RGBA, CHAN_A, CMP_NODE_CHANNEL_MATTE_CS_HSV, CMP_NODE_CHANNEL_MATTE_CS_RGB, CMP_NODE_CHANNEL_MATTE_CS_YCC, CMP_NODE_CHANNEL_MATTE_CS_YUV, composit1_pixel_processor(), bNode::custom1, bNodeStack::data, do_channel_matte(), do_hsva_to_rgba(), do_normalized_rgba_to_ycca2(), do_normalized_ycca_to_rgba2(), do_rgba_to_hsva(), do_rgba_to_yuva(), do_yuva_to_rgba(), dupalloc_compbuf(), free_compbuf(), generate_preview(), NULL, typecheck_compbuf(), and valbuf_from_rgbabuf().
Referenced by register_node_type_cmp_channel_matte().
static void node_composit_init_channel_matte (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 188 of file node_composite_channelMatte.c.
References NodeChroma::algorithm, NodeChroma::channel, bNode::custom1, bNode::custom2, NodeChroma::fsize, NodeChroma::fstrength, MEM_callocN(), bNode::storage, NodeChroma::t1, NodeChroma::t2, and NodeChroma::t3.
Referenced by register_node_type_cmp_channel_matte().
void register_node_type_cmp_channel_matte (bNodeTreeType * ttype)
Definition at line 203 of file node_composite_channelMatte.c.
References CMP_NODE_CHANNEL_MATTE, NODE_CLASS_MATTE, node_composit_exec_channel_matte(), node_composit_init_channel_matte(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_channel_matte_in[] [static]
Initial value:
{
    {SOCK_RGBA,1,"Image", 1.0f, 1.0f, 1.0f, 1.0f},
    {-1,0,""}
}
Definition at line 37 of file node_composite_channelMatte.c.
bNodeSocketTemplate cmp_node_channel_matte_out[] [static]
Initial value:
{
    {SOCK_RGBA,0,"Image"},
    {SOCK_FLOAT,0,"Matte"},
    {-1,0,""}
}
Definition at line 42 of file node_composite_channelMatte.c.