Blender: btDefaultVehicleRaycaster Class Reference
btDefaultVehicleRaycaster Class Reference
#include <btRaycastVehicle.h>
Public Member Functions
btDefaultVehicleRaycaster (btDynamicsWorld *world)
virtual void * castRay (const btVector3 &from, const btVector3 &to, btVehicleRaycasterResult &result)
Detailed Description
Definition at line 221 of file btRaycastVehicle.h.
Constructor & Destructor Documentation
btDefaultVehicleRaycaster::btDefaultVehicleRaycaster (btDynamicsWorld * world) [inline]
Definition at line 225 of file btRaycastVehicle.h.
Member Function Documentation
void * btDefaultVehicleRaycaster::castRay (const btVector3 & from, const btVector3 & to, btVehicleRaycasterResult & result) [virtual]
Implements btVehicleRaycaster.
Definition at line 748 of file btRaycastVehicle.cpp.
References btCollisionWorld::RayResultCallback::hasHit(), btCollisionWorld::RayResultCallback::m_closestHitFraction, btCollisionWorld::RayResultCallback::m_collisionObject, btVehicleRaycaster::btVehicleRaycasterResult::m_distFraction, btVehicleRaycaster::btVehicleRaycasterResult::m_hitNormalInWorld, btCollisionWorld::ClosestRayResultCallback::m_hitNormalWorld, btVehicleRaycaster::btVehicleRaycasterResult::m_hitPointInWorld, btCollisionWorld::ClosestRayResultCallback::m_hitPointWorld, btCollisionWorld::rayTest(), and btRigidBody::upcast().
The documentation for this class was generated from the following files:
btRaycastVehicle.h
btRaycastVehicle.cpp