Blender: node_composite_moviedistortion.c File Reference
node_composite_moviedistortion.c File Reference
cmpnodes
#include "BLF_translation.h"
#include "node_composite_util.h"
Functions
static void exec (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
static const char * label (bNode *node)
static void storage_free (bNode *node)
static void storage_copy (bNode *orig_node, bNode *new_node)
void register_node_type_cmp_moviedistortion (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_moviedistortion_in []
static bNodeSocketTemplate cmp_node_moviedistortion_out []
Detailed Description
Definition in file node_composite_moviedistortion.c.
Function Documentation
static void exec (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 50 of file node_composite_moviedistortion.c.
References alloc_compbuf(), BKE_movieclip_get_size(), BKE_movieclip_user_set_frame(), BKE_tracking_distortion_create(), BKE_tracking_distortion_exec(), CB_RGBA, RenderData::cfra, bNode::custom1, bNodeStack::data, data, free_compbuf(), IB_rectfloat, bNode::id, IMB_allocImBuf(), IMB_freeImBuf(), ImBuf::mall, CompBuf::malloc, NULL, pass_on_compbuf(), CompBuf::rect, ImBuf::rect_float, bNode::storage, MovieClip::tracking, and typecheck_compbuf().
Referenced by gpu_group_execute(), group_execute(), group_initexec(), ntree_exec_begin(), ntreeCompositBeginExecTree(), ntreeCompositExecTree(), ntreeGPUMaterialNodes(), ntreeShaderBeginExecTree(), ntreeShaderExecTree(), ntreeTexBeginExecTree(), ntreeTexExecTree(), and register_node_type_cmp_moviedistortion().
static const char* label (bNode * node) [static]
Definition at line 108 of file node_composite_moviedistortion.c.
References bNode::custom1, and IFACE_.
Referenced by BOP_createXS(), kernel_path_integrate(), register_node_type_cmp_moviedistortion(), shader_bsdf_sample(), svm_bsdf_sample(), and ui_node_draw_input().
void register_node_type_cmp_moviedistortion (bNodeTreeType * ttype)
Definition at line 130 of file node_composite_moviedistortion.c.
References CMP_NODE_MOVIEDISTORTION, exec(), label(), NODE_CLASS_DISTORT, NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_label(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, storage_copy(), and storage_free().
Referenced by registerCompositNodes().
static void storage_copy (bNode * orig_node, bNode * new_node) [static]
Definition at line 124 of file node_composite_moviedistortion.c.
References BKE_tracking_distortion_copy(), and bNode::storage.
Referenced by register_node_type_cmp_moviedistortion().
static void storage_free (bNode * node) [static]
Definition at line 116 of file node_composite_moviedistortion.c.
References BKE_tracking_distortion_destroy(), NULL, and bNode::storage.
Referenced by register_node_type_cmp_moviedistortion().
Variable Documentation
bNodeSocketTemplate cmp_node_moviedistortion_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          0.8f, 0.8f, 0.8f, 1.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 40 of file node_composite_moviedistortion.c.
bNodeSocketTemplate cmp_node_moviedistortion_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 45 of file node_composite_moviedistortion.c.