Blender: svm_gradient.h File Reference
svm_gradient.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device float svm_gradient (float3 p, NodeBlendType type)
__device void svm_node_tex_gradient (ShaderData *sd, float *stack, uint4 node)
Function Documentation
CCL_NAMESPACE_BEGIN __device float svm_gradient (float3 p, NodeBlendType type)
Definition at line 23 of file svm_gradient.h.
References KDL::atan2(), fmaxf, fminf, M_PI_F, NODE_BLEND_DIAGONAL, NODE_BLEND_EASING, NODE_BLEND_LINEAR, NODE_BLEND_QUADRATIC, NODE_BLEND_QUADRATIC_SPHERE, NODE_BLEND_RADIAL, NODE_BLEND_SPHERICAL, sqrtf, float3::x, float3::y, and float3::z.
Referenced by svm_node_tex_gradient().
__device void svm_node_tex_gradient (ShaderData * sd, float * stack, uint4 node)
Definition at line 62 of file svm_gradient.h.
References clamp, co, decode_node_uchar4(), make_float3(), stack_load_float3(), stack_store_float(), stack_store_float3(), stack_valid(), svm_gradient(), and uint4::y.
Referenced by svm_eval_nodes().