Blender: KX_BlenderRenderTools Class Reference
KX_BlenderRenderTools Class Reference
#include <KX_BlenderRenderTools.h>
Public Member Functions
KX_BlenderRenderTools ()
virtual ~KX_BlenderRenderTools ()
void EndFrame (RAS_IRasterizer *rasty)
void BeginFrame (RAS_IRasterizer *rasty)
void EnableOpenGLLights (RAS_IRasterizer *rasty)
void DisableOpenGLLights ()
void ProcessLighting (RAS_IRasterizer *rasty, bool uselights, const MT_Transform &viewmat)
void RenderText3D (int fontid, const char *text, int size, int dpi, float *color, double *mat, float aspect)
void RenderText2D (RAS_TEXT_RENDER_MODE mode, const char *text, int xco, int yco, int width, int height)
void RenderText (int mode, class RAS_IPolyMaterial *polymat, float v1[3], float v2[3], float v3[3], float v4[3], int glattrib)
void applyTransform (RAS_IRasterizer *rasty, double *oglmatrix, int objectdrawmode)
int applyLights (int objectlayer, const MT_Transform &viewmat)
void PushMatrix ()
void PopMatrix ()
bool RayHit (KX_ClientObjectInfo *client, class KX_RayCast *result, void *const data)
bool NeedRayCast (KX_ClientObjectInfo *)
virtual void MotionBlur (RAS_IRasterizer *rasterizer)
virtual void SetClientObject (RAS_IRasterizer *rasty, void *obj)
Detailed Description
Definition at line 56 of file KX_BlenderRenderTools.h.
Constructor & Destructor Documentation
KX_BlenderRenderTools::KX_BlenderRenderTools ()
Definition at line 59 of file KX_BlenderRenderTools.cpp.
KX_BlenderRenderTools::~KX_BlenderRenderTools () [virtual]
Definition at line 66 of file KX_BlenderRenderTools.cpp.
Member Function Documentation
int KX_BlenderRenderTools::applyLights (int objectlayer, const MT_Transform & viewmat)
Definition at line 345 of file KX_BlenderRenderTools.cpp.
References KX_LightObject::ApplyLight(), MT_Transform::getValue(), glLoadMatrixf, if(), RAS_IRenderTools::m_auxilaryClientInfo, RAS_LightObject::m_light, and RAS_IRenderTools::m_lights.
Referenced by ProcessLighting().
void KX_BlenderRenderTools::applyTransform (RAS_IRasterizer * rasty, double * oglmatrix, int objectdrawmode) [virtual]
Implements RAS_IRenderTools.
Definition at line 178 of file KX_BlenderRenderTools.cpp.
References RAS_IPolyMaterial::BILLBOARD_AXISALIGNED, RAS_IPolyMaterial::BILLBOARD_SCREENALIGNED, MT_Vector3::cross(), MT_Vector3::dot(), RAS_IRasterizer::GetCameraPosition(), SG_Spatial::GetLocalScale(), KX_GameObject::GetParent(), KX_GameObject::GetPhysicsController(), KX_Scene::GetPhysicsEnvironment(), KX_GameObject::GetSGNode(), left(), RAS_IRenderTools::m_auxilaryClientInfo, RAS_IRenderTools::m_clientobject, MT_Vector3::normalize(), MT_Vector3::normalized(), KX_RayCast::RayTest(), CValue::Release(), RAS_IPolyMaterial::SHADOW, and size().
void KX_BlenderRenderTools::BeginFrame (RAS_IRasterizer * rasty) [virtual]
Implements RAS_IRenderTools.
Definition at line 70 of file KX_BlenderRenderTools.cpp.
References DisableOpenGLLights(), RAS_IRenderTools::m_clientobject, and NULL.
void KX_BlenderRenderTools::DisableOpenGLLights ()
Definition at line 134 of file KX_BlenderRenderTools.cpp.
Referenced by BeginFrame(), and ProcessLighting().
void KX_BlenderRenderTools::EnableOpenGLLights (RAS_IRasterizer * rasty)
Definition at line 117 of file KX_BlenderRenderTools.cpp.
References RAS_IRasterizer::GetCameraOrtho().
Referenced by ProcessLighting().
void KX_BlenderRenderTools::EndFrame (RAS_IRasterizer * rasty) [virtual]
Implements RAS_IRenderTools.
Definition at line 79 of file KX_BlenderRenderTools.cpp.
void KX_BlenderRenderTools::MotionBlur (RAS_IRasterizer * rasterizer) [virtual]
Implements RAS_IRenderTools.
Definition at line 373 of file KX_BlenderRenderTools.cpp.
References RAS_IRasterizer::GetMotionBlurState(), RAS_IRasterizer::GetMotionBlurValue(), RAS_IRasterizer::SetMotionBlurState(), and state.
bool KX_BlenderRenderTools::NeedRayCast (KX_ClientObjectInfo *) [inline]
Definition at line 103 of file KX_BlenderRenderTools.h.
void KX_BlenderRenderTools::PopMatrix () [virtual]
Implements RAS_IRenderTools.
Definition at line 339 of file KX_BlenderRenderTools.cpp.
void KX_BlenderRenderTools::ProcessLighting (RAS_IRasterizer * rasty, bool uselights, const MT_Transform & viewmat) [virtual]
Implements RAS_IRenderTools.
Definition at line 89 of file KX_BlenderRenderTools.cpp.
References applyLights(), DisableOpenGLLights(), EnableOpenGLLights(), RAS_IRenderTools::m_auxilaryClientInfo, and RAS_IRenderTools::m_clientobject.
void KX_BlenderRenderTools::PushMatrix () [virtual]
Implements RAS_IRenderTools.
Definition at line 334 of file KX_BlenderRenderTools.cpp.
bool KX_BlenderRenderTools::RayHit (KX_ClientObjectInfo * client, class KX_RayCast * result, void *const data)
Definition at line 157 of file KX_BlenderRenderTools.cpp.
References MT_Vector3::cross(), left(), KX_RayCast::m_hitNormal, and KX_RayCast::m_hitPoint.
void KX_BlenderRenderTools::RenderText (int mode, class RAS_IPolyMaterial * polymat, float v1[3], float v2[3], float v3[3], float v4[3], int glattrib) [virtual]
Implements RAS_IRenderTools.
Definition at line 309 of file KX_BlenderRenderTools.cpp.
References RAS_IPolyMaterial::GetFlag(), KX_BlenderMaterial::GetMCol(), KX_PolygonMaterial::GetMCol(), KX_PolygonMaterial::GetMTFace(), KX_BlenderMaterial::GetMTFace(), GPU_render_text(), STR_String::Length(), RAS_IRenderTools::m_clientobject, and RAS_BLENDERMAT.
void KX_BlenderRenderTools::RenderText2D (RAS_TEXT_RENDER_MODE mode, const char * text, int xco, int yco, int width, int height) [virtual]
Renders 2D text string.
Parameters:
mode The type of text
text The string to render.
xco Position on the screen (origin in lower left corner).
yco Position on the screen (origin in lower left corner).
width Width of the canvas to draw to.
height Height of the canvas to draw to.
Implements RAS_IRenderTools.
Definition at line 293 of file KX_BlenderRenderTools.cpp.
References BL_print_gamedebug_line(), BL_print_gamedebug_line_padded(), and RAS_IRenderTools::RAS_TEXT_PADDED.
void KX_BlenderRenderTools::RenderText3D (int fontid, const char * text, int size, int dpi, float * color, double * mat, float aspect) [virtual]
Renders 3D text string using BFL.
Parameters:
fontid The id of the font.
text The string to render.
size The size of the text.
dpi The resolution of the text.
color The color of the object.
mat The Matrix of the text object.
aspect A scaling factor to compensate for the size.
Implements RAS_IRenderTools.
Definition at line 282 of file KX_BlenderRenderTools.cpp.
References BL_print_game_line().
void KX_BlenderRenderTools::SetClientObject (RAS_IRasterizer * rasty, void * obj) [virtual]
Reimplemented from RAS_IRenderTools.
Definition at line 146 of file KX_BlenderRenderTools.cpp.
References RAS_IRenderTools::m_clientobject, NULL, and RAS_IRasterizer::SetFrontFace().
The documentation for this class was generated from the following files:
KX_BlenderRenderTools.h
KX_BlenderRenderTools.cpp