Blender: ntlGeometryClass Class Reference
ntlGeometryClass Class Reference
#include <ntl_geometryclass.h>
Public Member Functions
ntlGeometryClass ()
Default constructor.
virtual ~ntlGeometryClass ()
Default destructor.
virtual int getTypeId ()=0
Return type id.
void setName (string set)
string getName (void)
void setVisible (int set)
int getVisible () const
void setAttributeList (AttributeList *set)
AttributeList * getAttributeList ()
void setSwsAttributeList (AttributeList *set)
AttributeList * getSwsAttributeList ()
virtual ntlVec3Gfx * getBBStart ()
virtual ntlVec3Gfx * getBBEnd ()
void setObjectId (int set)
int getObjectId () const
virtual void drawDebugDisplay ()
virtual void drawInteractiveDisplay ()
virtual void setMousePos (int, int, ntlVec3Gfx, ntlVec3Gfx)
virtual void setMouseClick ()
void setGeoInitId (int set)
int getGeoInitId () const
Protected Attributes
int mVisible
string mName
int mObjectId
AttributeList * mpAttrs
AttributeList * mpSwsAttrs
int mGeoInitId
Detailed Description
Definition at line 26 of file ntl_geometryclass.h.
Constructor & Destructor Documentation
ntlGeometryClass::ntlGeometryClass () [inline]
Default constructor.
Definition at line 32 of file ntl_geometryclass.h.
References mpAttrs, and mpSwsAttrs.
virtual ntlGeometryClass::~ntlGeometryClass () [inline, virtual]
Default destructor.
Definition at line 41 of file ntl_geometryclass.h.
References mpAttrs, and mpSwsAttrs.
Member Function Documentation
virtual void ntlGeometryClass::drawDebugDisplay () [inline, virtual]
GUI - this function is called for selected objects to display debugging information with OpenGL
Reimplemented in SimulationObject.
Definition at line 79 of file ntl_geometryclass.h.
virtual void ntlGeometryClass::drawInteractiveDisplay () [inline, virtual]
GUI - this function is called for selected objects to display interactive information with OpenGL
Reimplemented in SimulationObject.
Definition at line 81 of file ntl_geometryclass.h.
AttributeList* ntlGeometryClass::getAttributeList () [inline]
Returns the attribute list pointer
Definition at line 64 of file ntl_geometryclass.h.
References mpAttrs.
Referenced by ntlGeometryObjModel::initialize(), ntlGeometryObject::initialize(), and SimulationObject::initializeLbmSimulation().
virtual ntlVec3Gfx* ntlGeometryClass::getBBEnd () [inline, virtual]
Reimplemented in IsoSurface, and SimulationObject.
Definition at line 72 of file ntl_geometryclass.h.
References NULL.
virtual ntlVec3Gfx* ntlGeometryClass::getBBStart () [inline, virtual]
for easy GUI detection get start of axis aligned bounding box, return NULL of no BB
Reimplemented in IsoSurface, and SimulationObject.
Definition at line 71 of file ntl_geometryclass.h.
References NULL.
int ntlGeometryClass::getGeoInitId () const [inline]
Returns the geo init id
Definition at line 90 of file ntl_geometryclass.h.
References mGeoInitId.
Referenced by IsoSurface::getTriangles(), ControlParticles::initFromObject(), LbmFsgrSolver::initMovingObstacles(), ntlGeometryObject::sceneAddTriangle(), and ntlGeometryObject::sceneAddTriangleNoVert().
string ntlGeometryClass::getName (void) [inline]
Get the object name
Definition at line 52 of file ntl_geometryclass.h.
References mName.
Referenced by ntlGeometryObject::applyTransformation(), ntlScene::buildScene(), ParticleTracer::checkDumpTextPositions(), elbeemAddMesh(), ntlGeometryObject::initChannels(), LbmFsgrSolver::initGeometryFlags(), ntlGeometryObject::initialize(), SimulationObject::initializeLbmSimulation(), ntlGeometryObjModel::initModel(), LbmFsgrSolver::initMovingObstacles(), ntlGeometryObject::initMovingPoints(), ntlGeometryObject::initMovingPointsAnim(), ParticleTracer::notifyOfDump(), and ntlGeometryObject::notifyOfDump().
int ntlGeometryClass::getObjectId () const [inline]
Definition at line 76 of file ntl_geometryclass.h.
References mObjectId.
Referenced by ntlScene::buildScene().
AttributeList* ntlGeometryClass::getSwsAttributeList () [inline]
Definition at line 68 of file ntl_geometryclass.h.
References mpSwsAttrs.
Referenced by SimulationObject::initializeLbmSimulation().
virtual int ntlGeometryClass::getTypeId () [pure virtual]
Return type id.
Implemented in ntlGeometryObjModel, ntlGeometryObject, and ntlGeometryShader.
int ntlGeometryClass::getVisible () const [inline]
Returns the visibility attribute
Definition at line 59 of file ntl_geometryclass.h.
References mVisible.
Referenced by ntlWorld::advanceSims(), SimulationObject::drawDebugDisplay(), SimulationObject::drawInteractiveDisplay(), IsoSurface::getTriangles(), SimulationObject::initializeLbmSimulation(), ntlGeometryObject::sceneAddTriangle(), ntlGeometryObject::sceneAddTriangleNoVert(), and ntlWorld::singleStepSims().
void ntlGeometryClass::setAttributeList (AttributeList * set) [inline]
Sets the attribute list pointer
Definition at line 62 of file ntl_geometryclass.h.
References mpAttrs.
void ntlGeometryClass::setGeoInitId (int set) [inline]
Returns the geo init id
Definition at line 88 of file ntl_geometryclass.h.
References mGeoInitId.
Referenced by elbeemAddMesh(), and ControlParticles::initFromMVCMesh().
virtual void ntlGeometryClass::setMouseClick () [inline, virtual]
GUI - notify object that mouse was clicked at last pos
Reimplemented in SimulationObject.
Definition at line 85 of file ntl_geometryclass.h.
virtual void ntlGeometryClass::setMousePos (int , int , ntlVec3Gfx , ntlVec3Gfx) [inline, virtual]
GUI - handle mouse movement for selection
Reimplemented in SimulationObject.
Definition at line 83 of file ntl_geometryclass.h.
void ntlGeometryClass::setName (string set) [inline]
Set the object name
Definition at line 50 of file ntl_geometryclass.h.
References mName.
Referenced by ntlWorld::addDomain(), elbeemAddMesh(), SimulationObject::initializeLbmSimulation(), and LbmFsgrSolver::initializeSolverMemory().
void ntlGeometryClass::setObjectId (int set) [inline]
Set/get the object id
Definition at line 75 of file ntl_geometryclass.h.
References mObjectId.
Referenced by ntlScene::addGeoClass().
void ntlGeometryClass::setSwsAttributeList (AttributeList * set) [inline]
Get/Sets the attribute list pointer
Definition at line 67 of file ntl_geometryclass.h.
References mpSwsAttrs.
void ntlGeometryClass::setVisible (int set) [inline]
Sets the visibility attribute visibility can be determined at shader _and_ object level , hiding a shader means comepletely decativating it
Definition at line 57 of file ntl_geometryclass.h.
References mVisible.
Referenced by LbmFsgrSolver::initializeSolverMemory().
Member Data Documentation
int ntlGeometryClass::mGeoInitId [protected]
id of fluid init (is used in solver initialization), additional data stored only for objects
Definition at line 110 of file ntl_geometryclass.h.
Referenced by SimulationObject::copyElbeemSettings(), getGeoInitId(), SimulationObject::initGeoTree(), ntlGeometryObject::initialize(), SimulationObject::initializeLbmSimulation(), and setGeoInitId().
string ntlGeometryClass::mName [protected]
Name of this object
Definition at line 98 of file ntl_geometryclass.h.
Referenced by getName(), IsoSurface::getTriangles(), ntlGeometryObject::initialize(), ntlGeometryObject::sceneAddTriangle(), and setName().
int ntlGeometryClass::mObjectId [protected]
global scene object id
Definition at line 101 of file ntl_geometryclass.h.
Referenced by getObjectId(), ntlGeometryObject::sceneAddTriangle(), ntlGeometryObject::sceneAddTriangleNoVert(), and setObjectId().
AttributeList* ntlGeometryClass::mpAttrs [protected]
configuration attributes
Definition at line 104 of file ntl_geometryclass.h.
Referenced by getAttributeList(), ntlGeometryObjModel::initialize(), ntlGeometryObject::initialize(), SimulationObject::initializeLbmSimulation(), ntlGeometryClass(), ParticleTracer::parseAttrList(), setAttributeList(), and ~ntlGeometryClass().
AttributeList* ntlGeometryClass::mpSwsAttrs [protected]
sws configuration attributes
Definition at line 106 of file ntl_geometryclass.h.
Referenced by getSwsAttributeList(), ntlGeometryClass(), setSwsAttributeList(), and ~ntlGeometryClass().
int ntlGeometryClass::mVisible [protected]
Object visible on/off
Definition at line 95 of file ntl_geometryclass.h.
Referenced by getVisible(), ntlGeometryObject::initialize(), and setVisible().
The documentation for this class was generated from the following file:
ntl_geometryclass.h