Blender: ImageMix Class Reference
ImageMix Class Reference
class for image mixer
#include <ImageMix.h>
Public Member Functions
ImageMix (void)
constructor
virtual ~ImageMix (void)
destructor
short getWeight (const char *id)
get weight
bool setWeight (const char *id, short weight)
set weight
Protected Member Functions
virtual ImageSource * newSource (const char *id)
create new source
virtual void calcImage (unsigned int texId, double ts)
calculate image from sources and set its availability
Detailed Description
class for image mixer
Definition at line 65 of file ImageMix.h.
Constructor & Destructor Documentation
ImageMix::ImageMix (void) [inline]
constructor
Definition at line 69 of file ImageMix.h.
virtual ImageMix::~ImageMix (void) [inline, virtual]
destructor
Definition at line 72 of file ImageMix.h.
Member Function Documentation
void ImageMix::calcImage (unsigned int texId, double ts) [protected, virtual]
calculate image from sources and set its availability
Reimplemented from ImageBase.
Definition at line 71 of file ImageMix.cpp.
References ImageBase::checkSourceSizes(), ImageBase::filterImage(), getImageSourceMix(), ImageBase::getSize(), ImageBase::m_sources, NULL, S_OK, ImageSourceMix::setOffset(), and THRWEXCP.
short ImageMix::getWeight (const char * id)
get weight
Definition at line 46 of file ImageMix.cpp.
References ImageBase::findSource(), getImageSourceMix(), ImageSourceMix::getWeight(), and ImageBase::m_sources.
Referenced by getWeight().
virtual ImageSource* ImageMix::newSource (const char * id) [inline, protected, virtual]
create new source
Reimplemented from ImageBase.
Definition at line 82 of file ImageMix.h.
bool ImageMix::setWeight (const char * id, short weight)
set weight
Definition at line 55 of file ImageMix.cpp.
References ImageBase::findSource(), getImageSourceMix(), ImageBase::m_sources, and ImageSourceMix::setWeight().
The documentation for this class was generated from the following files:
ImageMix.h
ImageMix.cpp