Blender: node_composite_mapUV.c File Reference
node_composite_mapUV.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_mapuv (CompBuf *stackbuf, CompBuf *cbuf, CompBuf *uvbuf, float threshold)
static void node_composit_exec_mapuv (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_mapuv (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_mapuv_in []
static bNodeSocketTemplate cmp_node_mapuv_out []
Detailed Description
Definition in file node_composite_mapUV.c.
Function Documentation
static void do_mapuv (CompBuf * stackbuf, CompBuf * cbuf, CompBuf * uvbuf, float threshold) [static]
Definition at line 49 of file node_composite_mapUV.c.
References fabsf, ibuf_sample(), IMB_allocImBuf(), IMB_freeImBuf(), CompBuf::rect, ImBuf::rect_float, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_mapuv().
static void node_composit_exec_mapuv (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 140 of file node_composite_mapUV.c.
References alloc_compbuf(), CB_RGBA, CB_VEC3, bNode::custom1, bNodeStack::data, data, do_mapuv(), free_compbuf(), typecheck_compbuf(), CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_mapuv().
void register_node_type_cmp_mapuv (bNodeTreeType * ttype)
Definition at line 165 of file node_composite_mapUV.c.
References CMP_NODE_MAP_UV, NODE_CLASS_DISTORT, node_composit_exec_mapuv(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_mapuv_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   SOCK_VECTOR, 1, "UV",           1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_NONE},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_composite_mapUV.c.
bNodeSocketTemplate cmp_node_mapuv_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 42 of file node_composite_mapUV.c.