Blender: svm_geometry.h File Reference
svm_geometry.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void svm_node_geometry (ShaderData *sd, float *stack, uint type, uint out_offset)
__device void svm_node_geometry_bump_dx (ShaderData *sd, float *stack, uint type, uint out_offset)
__device void svm_node_geometry_bump_dy (ShaderData *sd, float *stack, uint type, uint out_offset)
Function Documentation
CCL_NAMESPACE_BEGIN __device void svm_node_geometry (ShaderData * sd, float * stack, uint type, uint out_offset)
Definition at line 23 of file svm_geometry.h.
References data, ShaderData::dPdu, ShaderData::I, make_float3(), ShaderData::N, ShaderData::Ng, NODE_GEOM_I, NODE_GEOM_N, NODE_GEOM_Ng, NODE_GEOM_P, NODE_GEOM_T, NODE_GEOM_uv, normalize(), ShaderData::P, stack_store_float3(), ShaderData::u, and ShaderData::v.
Referenced by svm_eval_nodes(), svm_node_geometry_bump_dx(), and svm_node_geometry_bump_dy().
__device void svm_node_geometry_bump_dx (ShaderData * sd, float * stack, uint type, uint out_offset)
Definition at line 43 of file svm_geometry.h.
References data, ShaderData::dP, ShaderData::du, ShaderData::dv, differential::dx, differential3::dx, make_float3(), NODE_GEOM_P, NODE_GEOM_uv, ShaderData::P, stack_store_float3(), svm_node_geometry(), ShaderData::u, and ShaderData::v.
Referenced by svm_eval_nodes().
__device void svm_node_geometry_bump_dy (ShaderData * sd, float * stack, uint type, uint out_offset)
Definition at line 60 of file svm_geometry.h.
References data, ShaderData::dP, ShaderData::du, ShaderData::dv, differential3::dy, differential::dy, make_float3(), NODE_GEOM_P, NODE_GEOM_uv, ShaderData::P, stack_store_float3(), svm_node_geometry(), ShaderData::u, and ShaderData::v.
Referenced by svm_eval_nodes().