Blender: ED_fileselect.h File Reference
ED_fileselect.h File Reference
Editors
Classes
struct FileLayout
struct FileSelection
Defines
#define FILE_LAYOUT_HOR 1
#define FILE_LAYOUT_VER 2
#define MAX_FILE_COLUMN 8
Typedefs
typedef enum FileListColumns FileListColumns
typedef struct FileLayout FileLayout
typedef struct FileSelection FileSelection
Enumerations
enum FileListColumns {
COLUMN_NAME = 0, COLUMN_DATE, COLUMN_TIME, COLUMN_SIZE,
COLUMN_MODE1, COLUMN_MODE2, COLUMN_MODE3, COLUMN_OWNER
}
Functions
struct FileSelectParams * ED_fileselect_get_params (struct SpaceFile *sfile)
short ED_fileselect_set_params (struct SpaceFile *sfile)
void ED_fileselect_reset_params (struct SpaceFile *sfile)
void ED_fileselect_init_layout (struct SpaceFile *sfile, struct ARegion *ar)
FileLayout * ED_fileselect_get_layout (struct SpaceFile *sfile, struct ARegion *ar)
int ED_fileselect_layout_numfiles (FileLayout *layout, struct ARegion *ar)
int ED_fileselect_layout_offset (FileLayout *layout, int x, int y)
FileSelection ED_fileselect_layout_offset_rect (FileLayout *layout, const struct rcti *rect)
void ED_fileselect_layout_tilepos (FileLayout *layout, int tile, int *x, int *y)
void ED_operatormacros_file (void)
void ED_fileselect_clear (struct bContext *C, struct SpaceFile *sfile)
void ED_fileselect_exit (struct bContext *C, struct SpaceFile *sfile)
int ED_file_extension_icon (const char *relname)
Detailed Description
Definition in file ED_fileselect.h.
Define Documentation
#define FILE_LAYOUT_HOR 1
Definition at line 39 of file ED_fileselect.h.
Referenced by ED_fileselect_init_layout(), ED_fileselect_layout_numfiles(), ED_fileselect_layout_offset(), ED_fileselect_layout_offset_rect(), ED_fileselect_layout_tilepos(), file_draw_list(), and file_smoothscroll_invoke().
#define FILE_LAYOUT_VER 2
Definition at line 40 of file ED_fileselect.h.
Referenced by ED_fileselect_init_layout(), and file_main_area_draw().
#define MAX_FILE_COLUMN 8
Definition at line 42 of file ED_fileselect.h.
Referenced by column_widths().
Typedef Documentation
typedef struct FileLayout FileLayout
typedef enum FileListColumns FileListColumns
typedef struct FileSelection FileSelection
Enumeration Type Documentation
enum FileListColumns
Enumerator:
COLUMN_NAME
COLUMN_DATE
COLUMN_TIME
COLUMN_SIZE
COLUMN_MODE1
COLUMN_MODE2
COLUMN_MODE3
COLUMN_OWNER
Definition at line 44 of file ED_fileselect.h.
Function Documentation
int ED_file_extension_icon (const char * relname)
Definition at line 804 of file filelist.c.
References BLENDERFILE, BLENDERFILE_BACKUP, BTXFILE, COLLADAFILE, file_extension_type(), FTFONTFILE, IMAGEFILE, MOVIEFILE, PYSCRIPTFILE, SOUNDFILE, and direntry::type.
Referenced by ghost_event_proc().
void ED_fileselect_clear (struct bContext * C, struct SpaceFile * sfile)
Definition at line 679 of file filesel.c.
References FileSelectParams::active_file, filelist_free(), filelist_freelib(), SpaceFile::files, NC_SPACE, ND_SPACE_FILE_LIST, NULL, SpaceFile::params, thumbnails_stop(), and WM_event_add_notifier().
Referenced by ED_fileselect_exit(), file_change_dir(), file_delete_exec(), file_directory_new_exec(), file_hidedot_exec(), file_refresh_exec(), and renamebutton_cb().
void ED_fileselect_exit (struct bContext * C, struct SpaceFile * sfile)
Definition at line 692 of file filesel.c.
References ED_fileselect_clear(), EVT_FILESELECT_EXTERNAL_CANCEL, SpaceFile::files, folderlist_free(), SpaceFile::folders_next, SpaceFile::folders_prev, MEM_freeN(), NULL, SpaceFile::op, and WM_event_fileselect_event().
Referenced by ED_area_exit().
FileLayout* ED_fileselect_get_layout (struct SpaceFile * sfile, struct ARegion * ar)
Definition at line 562 of file filesel.c.
References ED_fileselect_init_layout(), and SpaceFile::layout.
Referenced by file_draw_list(), and file_main_area_draw().
struct FileSelectParams* ED_fileselect_get_params (struct SpaceFile * sfile) [read]
Definition at line 89 of file filesel.c.
References ED_fileselect_set_params(), and SpaceFile::params.
Referenced by bookmark_add_exec(), ED_fileselect_init_layout(), file_border_select_modal(), file_draw_buttons(), file_draw_list(), file_hilight_set(), file_main_area_draw(), file_refresh(), and file_select_do().
void ED_fileselect_init_layout (struct SpaceFile * sfile, struct ARegion * ar)
Definition at line 475 of file filesel.c.
References COLUMN_DATE, COLUMN_MODE1, COLUMN_MODE2, COLUMN_MODE3, COLUMN_NAME, COLUMN_OWNER, COLUMN_SIZE, COLUMN_TIME, column_widths(), FileLayout::column_widths, FileLayout::columns, View2D::cur, FileLayout::dirty, FileSelectParams::display, ED_fileselect_get_params(), FALSE, file_font_pointsize(), FILE_IMGDISPLAY, FILE_LAYOUT_HOR, FILE_LAYOUT_VER, FILE_SHORTDISPLAY, filelist_numfiles(), SpaceFile::files, FileLayout::flag, FileLayout::height, ICON_DEFAULT_WIDTH_SCALE, SpaceFile::layout, MEM_callocN(), NULL, FileLayout::prv_border_x, FileLayout::prv_border_y, FileLayout::prv_h, FileLayout::prv_w, FileLayout::rows, FileLayout::textheight, FileLayout::tile_border_x, FileLayout::tile_border_y, FileLayout::tile_h, FileLayout::tile_w, TRUE, ARegion::v2d, FileLayout::width, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by ED_fileselect_get_layout(), and file_calc_previews().
int ED_fileselect_layout_numfiles (FileLayout * layout, struct ARegion * ar)
Definition at line 268 of file filesel.c.
References FileLayout::columns, View2D::cur, FILE_LAYOUT_HOR, FileLayout::flag, FileLayout::rows, FileLayout::tile_border_x, FileLayout::tile_border_y, FileLayout::tile_h, FileLayout::tile_w, ARegion::v2d, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by file_draw_list(), and file_smoothscroll_invoke().
int ED_fileselect_layout_offset (FileLayout * layout, int x, int y)
Definition at line 333 of file filesel.c.
References FileLayout::columns, FILE_LAYOUT_HOR, FileLayout::flag, NULL, FileLayout::rows, FileLayout::tile_border_x, FileLayout::tile_border_y, FileLayout::tile_h, and FileLayout::tile_w.
Referenced by file_draw_list(), file_hilight_set(), and file_smoothscroll_invoke().
FileSelection ED_fileselect_layout_offset_rect (FileLayout * layout, const struct rcti * rect)
Referenced by find_file_mouse_rect().
void ED_fileselect_layout_tilepos (FileLayout * layout, int tile, int * x, int * y)
Definition at line 354 of file filesel.c.
References FileLayout::columns, FILE_LAYOUT_HOR, FileLayout::flag, FileLayout::rows, FileLayout::tile_border_x, FileLayout::tile_border_y, FileLayout::tile_h, and FileLayout::tile_w.
Referenced by file_draw_list().
void ED_fileselect_reset_params (struct SpaceFile * sfile)
Definition at line 261 of file filesel.c.
References FILE_UNIX, FileSelectParams::flag, SpaceFile::params, FileSelectParams::title, and FileSelectParams::type.
short ED_fileselect_set_params (struct SpaceFile * sfile)
Definition at line 97 of file filesel.c.
References BLENDERFILE, BLI_cleanup_dir(), BLI_path_abs(), BLI_split_dirfile(), BLI_strncpy(), BTXFILE, COLLADAFILE, FileSelectParams::dir, FileLayout::dirty, FileSelectParams::display, FALSE, FileSelectParams::file, FILE_ACTIVELAY, FILE_AUTOSELECT, FILE_DEFAULTDISPLAY, FILE_DIRSEL_ONLY, FILE_FILTER, FILE_HIDE_DOT, FILE_IMGDISPLAY, FILE_LINK, FILE_LOADLIB, FILE_MAX, FILE_SHORTDISPLAY, FILE_SORT_ALPHA, FILE_SPECIAL, FILE_UNIX, FileSelectParams::filter, FileSelectParams::filter_glob, FileSelectParams::flag, FOLDERFILE, folderlist_new(), folderlist_pushdir(), SpaceFile::folders_prev, FTFONTFILE, G, IMAGEFILE, SpaceFile::layout, MEM_callocN(), MOVIEFILE, NULL, SpaceFile::op, OPERATORFILE, SpaceFile::params, wmOperator::ptr, PYSCRIPTFILE, RNA_boolean_get(), RNA_boolean_set(), RNA_enum_get(), RNA_int_get(), RNA_string_get(), RNA_struct_find_property(), RNA_struct_property_is_set(), RNA_struct_ui_name(), FileSelectParams::sort, SOUNDFILE, wmOperatorType::srna, TEXTFILE, FileSelectParams::title, TRUE, wmOperator::type, FileSelectParams::type, USER_FILTERFILEEXTS, USER_HIDE_DOT, USER_RELPATHS, and USER_SHOW_THUMBNAILS.
Referenced by ED_fileselect_get_params(), and wm_handler_fileselect_call().
void ED_operatormacros_file (void)
Definition at line 1444 of file file_ops.c.
Referenced by ED_spacetypes_init().