Blender: bmesh_queries.h File Reference
bmesh_queries.h File Reference
BMesh
Functions
int BM_vert_in_face (BMFace *f, BMVert *v)
int BM_verts_in_face (BMesh *bm, BMFace *f, BMVert **varr, int len)
int BM_edge_in_face (BMFace *f, BMEdge *e)
int BM_vert_in_edge (BMEdge *e, BMVert *v)
int BM_verts_in_edge (BMVert *v1, BMVert *v2, BMEdge *e)
float BM_edge_calc_length (BMEdge *e)
int BM_edge_face_pair (BMEdge *e, BMFace **r_fa, BMFace **r_fb)
int BM_edge_loop_pair (BMEdge *e, BMLoop **r_la, BMLoop **r_lb)
BMVert * BM_edge_other_vert (BMEdge *e, BMVert *v)
BMLoop * BM_face_other_edge_loop (BMFace *f, BMEdge *e, BMVert *v)
Other Loop in Face Sharing an Edge.
BMLoop * BM_face_other_vert_loop (BMFace *f, BMVert *v_prev, BMVert *v)
Other Loop in Face Sharing a Vertex.
BMLoop * BM_loop_other_vert_loop (BMLoop *l, BMVert *v)
Other Loop in Face Sharing a Vert.
int BM_vert_edge_count_nonwire (BMVert *v)
int BM_vert_edge_count (BMVert *v)
int BM_edge_face_count (BMEdge *e)
int BM_vert_face_count (BMVert *v)
BMEdge * BM_vert_other_disk_edge (BMVert *v, BMEdge *e)
int BM_vert_is_wire (BMVert *v)
int BM_edge_is_wire (BMEdge *e)
int BM_vert_is_manifold (BMVert *v)
int BM_edge_is_manifold (BMEdge *e)
int BM_edge_is_boundary (BMEdge *e)
float BM_loop_calc_face_angle (BMLoop *l)
void BM_loop_calc_face_normal (BMLoop *l, float r_normal[3])
BM_loop_calc_face_normal.
void BM_loop_calc_face_tangent (BMLoop *l, float r_tangent[3])
BM_loop_calc_face_tangent.
float BM_edge_calc_face_angle (BMEdge *e)
BMESH EDGE/FACE ANGLE.
void BM_edge_calc_face_tangent (BMEdge *e, BMLoop *e_loop, float r_tangent[3])
BMESH EDGE/FACE TANGENT.
float BM_vert_calc_edge_angle (BMVert *v)
BMESH VERT/EDGE ANGLE.
float BM_vert_calc_shell_factor (BMVert *v)
BMEdge * BM_edge_exists (BMVert *v1, BMVert *v2)
int BM_face_exists_overlap (BMesh *bm, BMVert **varr, int len, BMFace **r_existface)
int BM_face_exists (BMesh *bm, BMVert **varr, int len, BMFace **r_existface)
int BM_face_exists_multi (BMVert **varr, BMEdge **earr, int len)
int BM_face_exists_multi_edge (BMEdge **earr, int len)
int BM_face_share_edge_count (BMFace *f1, BMFace *f2)
int BM_edge_share_face_count (BMEdge *e1, BMEdge *e2)
int BM_edge_share_vert_count (BMEdge *e1, BMEdge *e2)
BMVert * BM_edge_share_vert (BMEdge *e1, BMEdge *e2)
BMLoop * BM_face_vert_share_loop (BMFace *f, BMVert *v)
Return the Loop Shared by Face and Vertex.
BMLoop * BM_face_edge_share_loop (BMFace *f, BMEdge *e)
Return the Loop Shared by Face and Edge.
void BM_edge_ordered_verts (BMEdge *edge, BMVert **r_v1, BMVert **r_v2)
void BM_edge_ordered_verts_ex (BMEdge *edge, BMVert **r_v1, BMVert **r_v2, BMLoop *edge_loop)
Detailed Description
Definition in file bmesh_queries.h.
Function Documentation
float BM_edge_calc_face_angle (BMEdge * e)
BMESH EDGE/FACE ANGLE.
Calculates the angle between two faces. Assumes the face normals are correct.
Returns:
angle in radians
Definition at line 844 of file bmesh_queries.c.
References angle_normalized_v3v3(), BM_edge_is_manifold(), DEG2RADF, BMLoop::f, BMEdge::l, BMFace::no, and BMLoop::radial_next.
Referenced by bm_vert_edge_face_angle(), bmo_dissolve_limit_exec(), bmo_similaredges_exec(), and bpy_bmedge_calc_face_angle().
void BM_edge_calc_face_tangent (BMEdge * e, BMLoop * e_loop, float r_tangent[3])
BMESH EDGE/FACE TANGENT.
Calculate the tangent at this loop corner or fallback to the face normal on straignt lines. This vector always points inward into the face.
BM_edge_calc_face_tangent
Parameters:
e
e_loop The loop to calculate the tangent at, used to get the face and winding direction.
Definition at line 868 of file bmesh_queries.c.
References BM_edge_ordered_verts_ex(), BMVert::co, cross_v3_v3v3(), BMLoop::f, BMFace::no, normalize_v3(), and sub_v3_v3v3().
Referenced by bmo_inset_exec(), and bpy_bmedge_calc_tangent().
float BM_edge_calc_length (BMEdge * e)
Returms edge length
Definition at line 355 of file bmesh_queries.c.
References BMVert::co, len_v3v3(), BMEdge::v1, and BMEdge::v2.
Referenced by bm_vert_avg_tag_dist(), bmo_inset_exec(), and edbm_rip_invoke__vert().
BMEdge* BM_edge_exists (BMVert * v1, BMVert * v2)
Returns the edge existing between v1 and v2, or NULL if there isn't one.
Note:
multiple edges may exist between any two vertices, and therefore this function only returns the first one found.
Definition at line 936 of file bmesh_queries.c.
References BM_EDGES_OF_VERT, BM_ITER_ELEM, NULL, BMEdge::v1, and BMEdge::v2.
Referenced by BM_edge_create(), BM_edge_rotate(), BM_edge_rotate_check_degenerate(), BM_face_create_ngon(), BM_face_other_vert_loop(), bmesh_jekv(), bmo_bevel_exec(), bmo_edgenet_fill_exec(), bmo_weldverts_exec(), bmw_LoopWalker_step(), bpy_bmedgeseq_get__method(), bpy_bmedgeseq_new(), find_ear(), and knife_make_chain_cut().
int BM_edge_face_count (BMEdge * e)
Returns the number of faces around this edge
Definition at line 433 of file bmesh_queries.c.
References BMEdge::l, and BMLoop::radial_next.
Referenced by BM_faces_join(), BM_vert_face_count(), bmo_bevel_exec(), bmo_similaredges_exec(), bmw_UVEdgeWalker_step(), EDBM_select_interior_faces(), and verg_radial().
int BM_edge_face_pair (BMEdge * e, BMFace ** r_fa, BMFace ** r_fb)
Utility function, since enough times we have an edge and want to access 2 connected faces.
Returns:
TRUE when only 2 faces are found.
Definition at line 366 of file bmesh_queries.c.
References BMLoop::f, FALSE, BMEdge::l, NULL, BMLoop::radial_next, and TRUE.
Referenced by BM_edge_calc_rotate(), BM_edge_rotate(), BM_edge_rotate_check(), bmo_dissolve_edgeloop_exec(), bmo_dissolve_edges_exec(), bmo_edgerotate_exec(), bmo_join_triangles_exec(), and edbm_edge_rotate_selected_exec().
int BM_edge_in_face (BMFace * f, BMEdge * e)
Returns whether or not a given edge is is part of a given face.
Definition at line 265 of file bmesh_queries.c.
References BM_FACE_FIRST_LOOP, BMLoop::e, FALSE, BMLoop::next, and TRUE.
Referenced by edge_ray_cast(), and edgering_find_order().
int BM_edge_is_boundary (BMEdge * e)
Tests whether or not an edge is on the boundary of a shell (has one face associated with it)
Definition at line 609 of file bmesh_queries.c.
References BMEdge::l, and BMLoop::radial_next.
Referenced by bm_edgesplit_validate_seams(), BME_bevel_initialize(), bmo_edgesplit_exec(), bmo_inset_exec(), bmw_FaceLoopWalker_edge_begins_loop(), bmw_LoopWalker_begin(), bmw_LoopWalker_step(), bpy_bmedge_is_boundary_get(), edbm_extrude_edge(), edbm_rip_invoke__vert(), and test_extra_verts().
int BM_edge_is_manifold (BMEdge * e)
Tests whether or not this edge is manifold. A manifold edge has exactly 2 faces attached to it.
Definition at line 584 of file bmesh_queries.c.
References BMEdge::l, and BMLoop::radial_next.
Referenced by BM_edge_calc_face_angle(), bm_vert_edge_face_angle(), BM_vert_other_disk_edge(), BME_Bevel_Dissolve_Disk(), BME_bevel_initialize(), bmesh_jfke(), bmo_beautify_fill_exec(), bmo_dissolve_limit_exec(), bmw_FaceLoopWalker_edge_begins_loop(), bmw_FaceLoopWalker_step(), bpy_bmedge_is_manifold_get(), createSlideVerts(), edbm_rip_invoke__edge(), edbm_rip_invoke__vert(), and edbm_select_non_manifold_exec().
int BM_edge_is_wire (BMEdge * e)
Tests whether or not the edge is part of a wire. (ie: has no faces attached to it)
Definition at line 507 of file bmesh_queries.c.
References FALSE, BMEdge::l, and TRUE.
Referenced by BM_edge_flag_to_mflag(), bmo_dissolve_limit_exec(), bmo_extrude_face_region_exec(), bmw_FaceLoopWalker_edge_begins_loop(), bpy_bmedge_is_wire_get(), edbm_rip_invoke__edge(), edbm_rip_invoke__vert(), and mesh_separate_selected().
int BM_edge_loop_pair (BMEdge * e, BMLoop ** r_la, BMLoop ** r_lb)
Utility function, since enough times we have an edge and want to access 2 connected loops.
Returns:
TRUE when only 2 faces are found.
Definition at line 391 of file bmesh_queries.c.
References FALSE, BMEdge::l, NULL, BMLoop::radial_next, and TRUE.
Referenced by edbm_ripsel_edge_mark_step(), and edbm_ripsel_looptag_helper().
void BM_edge_ordered_verts (BMEdge * edge, BMVert ** r_v1, BMVert ** r_v2)
Definition at line 759 of file bmesh_queries.c.
References BM_edge_ordered_verts_ex(), and BMEdge::l.
Referenced by BM_edge_calc_rotate(), BM_edge_rotate_check_degenerate(), BM_face_create_ngon_vcloud(), and vote_on_winding().
void BM_edge_ordered_verts_ex (BMEdge * edge, BMVert ** r_v1, BMVert ** r_v2, BMLoop * edge_loop)
Returns the verts of an edge as used in a face if used in a face at all, otherwise just assign as used in the edge.
Useful to get a deterministic winding order when calling BM_face_create_ngon() on an arbitrary array of verts, though be sure to pick an edge which has a face.
Note:
This is infact quite a simple check, mainly include this function so the intent is more obvious. We know these 2 verts will _always_ make up the loops edge
Definition at line 751 of file bmesh_queries.c.
References BLI_assert, BMLoop::e, BMLoop::next, and BMLoop::v.
Referenced by BM_edge_calc_face_tangent(), BM_edge_ordered_verts(), and bmo_inset_exec().
BMVert* BM_edge_other_vert (BMEdge * e, BMVert * v)
Given a edge and one of its vertices, returns the other vertex.
Definition at line 294 of file bmesh_queries.c.
References bmesh_edge_other_vert_get().
Referenced by BM_face_create_ngon(), BM_faces_join(), BM_loop_other_vert_loop(), bm_vert_avg_tag_dist(), BM_vert_calc_edge_angle(), BM_vert_collapse_edge(), BM_vert_collapse_faces(), BME_bevel_split_edge(), bmo_bevel_exec(), bmo_bridge_loops_exec(), bmo_extrude_face_indiv_exec(), bmo_inset_exec(), bmo_regionextend_extend(), bmo_vertex_slide_exec(), bmo_vertexsmooth_exec(), bmw_ConnectedVertexWalker_step(), bmw_IslandboundWalker_step(), bmw_LoopWalker_begin(), bmw_LoopWalker_step(), bpy_bmedge_other_vert(), calc_corner_co(), crazyspace_set_quats_editmesh(), createSlideVerts(), edbm_ripsel_edge_uid_step(), edbm_ripsel_looptag_helper(), edge_find_shortest_path(), editmesh_set_connectivity_distance(), get_next_loop(), init_rotsys(), rotsys_fill_faces(), rotsys_make_consistent(), vtx_slide_confirm(), vtx_slide_set_frame(), vtx_slide_update(), and weld_align_uv().
int BM_edge_share_face_count (BMEdge * e1, BMEdge * e2)
Test if e1 shares any faces with e2
Definition at line 649 of file bmesh_queries.c.
References bmesh_radial_face_find(), BMLoop::f, FALSE, BMEdge::l, BMLoop::radial_next, and TRUE.
Referenced by BM_disk_dissolve(), and edgering_sel().
BMVert* BM_edge_share_vert (BMEdge * e1, BMEdge * e2)
Return the shared vertex between the two edges or NULL
Definition at line 681 of file bmesh_queries.c.
References BM_vert_in_edge(), NULL, BMEdge::v1, and BMEdge::v2.
Referenced by BM_face_exists_multi_edge().
int BM_edge_share_vert_count (BMEdge * e1, BMEdge * e2)
Tests to see if e1 shares a vertex with e2
Definition at line 670 of file bmesh_queries.c.
References BMEdge::v1, and BMEdge::v2.
Referenced by bmo_edgenet_prepare(), and bmo_esubd_exec().
BMLoop* BM_face_edge_share_loop (BMFace * f, BMEdge * e)
Return the Loop Shared by Face and Edge.
Finds the loop used which uses e in face loop l
Note:
currenly this just uses simple loop in future may be speeded up using radial vars
Definition at line 725 of file bmesh_queries.c.
References BMLoop::f, BMEdge::l, NULL, and BMLoop::radial_next.
Referenced by bm_extrude_copy_face_loop_attributes(), and bmesh_jfke().
int BM_face_exists (BMesh * bm, BMVert ** varr, int len, BMFace ** r_existface)
Given a set of vertices (varr), find out if there is a face with exactly those vertices (and only those vertices).
Definition at line 989 of file bmesh_queries.c.
References BM_FACES_OF_VERT, BM_ITER_ELEM, BM_verts_in_face(), FALSE, i, len(), BMFace::len, NULL, and TRUE.
Referenced by BM_face_create(), BM_face_create_quad_tri_v(), bmo_bevel_exec(), bpy_bmfaceseq_get__method(), bpy_bmfaceseq_new(), and edge_find_shortest_path().
int BM_face_exists_multi (BMVert ** varr, BMEdge ** earr, int len)
Given a set of vertices and edges (varr, earr), find out if all those vertices are filled in by existing faces that _only_ use those vertices.
This is for use in cases where creating a face is possible but would result in many overlapping faces.
An example of how this is used: when 2 tri's are selected that share an edge, pressing Fkey would make a new overlapping quad (without a check like this)
earr and varr can be in any order, however they _must_ form a closed loop.
Definition at line 1026 of file bmesh_queries.c.
References BM_EDGES_OF_VERT, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_INTERNAL_TAG, BM_FACES_OF_EDGE, BM_ITER_ELEM, BM_VERTS_OF_FACE, FALSE, i, len(), TRUE, BMEdge::v1, and BMEdge::v2.
Referenced by BM_face_exists_multi_edge().
int BM_face_exists_multi_edge (BMEdge ** earr, int len)
Definition at line 1132 of file bmesh_queries.c.
References BLI_array_fixedstack_declare, BLI_array_fixedstack_free, BM_edge_share_vert(), BM_face_exists_multi(), BM_NGON_STACK_SIZE, BMESH_ASSERT, FALSE, i, len(), and TRUE.
Referenced by bmo_edgenet_fill_exec().
int BM_face_exists_overlap (BMesh * bm, BMVert ** varr, int len, BMFace ** r_overlapface)
Given a set of vertices varr, find out if all those vertices overlap an existing face.
Note:
Making a face here is valid but in some cases you wont want to make a face thats part of another.
Returns:
TRUE for overlap
Definition at line 959 of file bmesh_queries.c.
References BM_FACES_OF_VERT, BM_ITER_ELEM, BM_verts_in_face(), FALSE, i, len(), NULL, and TRUE.
BMLoop* BM_face_other_edge_loop (BMFace * f, BMEdge * e, BMVert * v)
Other Loop in Face Sharing an Edge.
Finds the other loop that shares v with e loop in f.
+----------+ | | | f | | | +----------+ <-- return the face loop of this vertex. v --> e ^ ^ <------- These vert args define direction in the face to check. The faces loop direction is ignored.
Definition at line 69 of file bmesh_queries.c.
References BMLoop::e, BMLoop::f, BMEdge::l, BMLoop::next, BMLoop::prev, BMLoop::radial_next, and BMLoop::v.
Referenced by bmw_IslandboundWalker_step(), bmw_LoopWalker_step(), crazyspace_set_quats_editmesh(), createSlideVerts(), edbm_rip_invoke__edge(), edbm_rip_invoke__vert(), edgering_find_order(), and get_next_loop().
BMLoop* BM_face_other_vert_loop (BMFace * f, BMVert * v_prev, BMVert * v)
Other Loop in Face Sharing a Vertex.
Finds the other loop in a face.
This function returns a loop in f that shares an edge with v The direction is defined by v_prev, where the return value is the loop of what would be 'v_next'
+----------+ <-- return the face loop of this vertex. | | | f | | | +----------+ v_prev --> v ^^^^^^ ^ <-- These vert args define direction in the face to check. The faces loop direction is ignored.
Note:
v_prev and v _implicitly_ define an edge.
Definition at line 109 of file bmesh_queries.c.
References BLI_assert, BM_edge_exists(), BM_ITER_ELEM, BM_LOOPS_OF_VERT, BMLoop::f, BMLoop::next, NULL, BMLoop::prev, and BMLoop::v.
Referenced by BM_edge_calc_rotate(), BM_edge_rotate_check(), BM_edge_rotate_check_degenerate(), BM_loop_other_vert_loop(), bmw_LoopWalker_step(), and edbm_rip_edge_side_measure().
int BM_face_share_edge_count (BMFace * f1, BMFace * f2)
Counts the number of edges two faces share (if any)
Definition at line 630 of file bmesh_queries.c.
References BM_FACE_FIRST_LOOP, bmesh_radial_face_find(), BMLoop::e, and BMLoop::next.
Referenced by bevel_init_edges(), and bmesh_jfke().
BMLoop* BM_face_vert_share_loop (BMFace * f, BMVert * v)
Return the Loop Shared by Face and Vertex.
Finds the loop used which uses v in face loop l
Note:
currenly this just uses simple loop in future may be speeded up using radial vars
Definition at line 702 of file bmesh_queries.c.
References BM_FACE_FIRST_LOOP, BMLoop::next, NULL, and BMLoop::v.
Referenced by bmesh_urmv(), and bpy_bm_utils_face_vert_separate().
float BM_loop_calc_face_angle (BMLoop * l)
Calculates the angle between the previous and next loops (angle at this loops face corner).
Returns:
angle in radians
Definition at line 770 of file bmesh_queries.c.
References angle_v3v3v3(), BMVert::co, BMLoop::next, BMLoop::prev, and BMLoop::v.
Referenced by BM_vert_calc_shell_factor(), BME_bevel_get_angle_vert(), and bpy_bmloop_calc_angle().
void BM_loop_calc_face_normal (BMLoop * l, float r_normal[3])
BM_loop_calc_face_normal.
Calculate the normal at this loop corner or fallback to the face normal on straignt lines.
Parameters:
bm The BMesh
l The loop to calculate the normal at
r_normal Resulting normal
Definition at line 786 of file bmesh_queries.c.
References BMVert::co, copy_v3_v3(), BMLoop::f, BMLoop::next, BMFace::no, normal_tri_v3(), BMLoop::prev, and BMLoop::v.
Referenced by BME_bevel_get_angle_vert(), and bpy_bmloop_calc_normal().
void BM_loop_calc_face_tangent (BMLoop * l, float r_tangent[3])
BM_loop_calc_face_tangent.
Calculate the tangent at this loop corner or fallback to the face normal on straignt lines. This vector always points inward into the face.
Parameters:
bm The BMesh
l The loop to calculate the tangent at
r_tangent Resulting tangent
Definition at line 810 of file bmesh_queries.c.
References add_v3_v3v3(), BMVert::co, compare_v3v3(), cross_v3_v3v3(), BMLoop::f, FALSE, BMLoop::next, BMFace::no, normalize_v3(), BMLoop::prev, sub_v3_v3v3(), and BMLoop::v.
Referenced by bpy_bmloop_calc_tangent(), and edbm_rip_invoke__vert().
BMLoop* BM_loop_other_vert_loop (BMLoop * l, BMVert * v)
Other Loop in Face Sharing a Vert.
Finds the other loop that shares v with e loop in f.
+----------+ <-- return the face loop of this vertex. | | | | | | +----------+ <-- This vertex defines the direction. l v ^ <------- This loop defines both the face to search and the edge, in combination with 'v' The faces loop direction is ignored.
Definition at line 158 of file bmesh_queries.c.
References BLI_assert, BM_edge_other_vert(), BM_face_other_vert_loop(), BMLoop::e, BMLoop::f, BMLoop::next, BMLoop::prev, and BMLoop::v.
Referenced by BM_vert_other_disk_edge(), and bmo_inset_exec().
float BM_vert_calc_edge_angle (BMVert * v)
BMESH VERT/EDGE ANGLE.
Calculates the angle a verts 2 edges.
Returns:
the angle in radians
Definition at line 888 of file bmesh_queries.c.
References angle_v3v3v3(), BM_edge_other_vert(), bmesh_disk_edge_next(), BMVert::co, DEG2RADF, BMVert::e, and M_PI.
Referenced by bm_vert_edge_face_angle(), and bpy_bmvert_calc_edge_angle().
float BM_vert_calc_shell_factor (BMVert * v)
Note:
this isn't optimal to run on an array of verts, see 'solidify_add_thickness' for a function which runs on an array.
Definition at line 914 of file bmesh_queries.c.
References angle_normalized_v3v3(), BM_ITER_ELEM, BM_loop_calc_face_angle(), BM_LOOPS_OF_VERT, BMLoop::f, BMFace::no, BMVert::no, and shell_angle_to_dist().
Referenced by bmo_inset_exec(), and bpy_bmvert_calc_shell_factor().
int BM_vert_edge_count (BMVert * v)
Returns the number of edges around this vertex.
Definition at line 413 of file bmesh_queries.c.
References bmesh_disk_count().
Referenced by BM_vert_dissolve(), BME_bevel_initialize(), bmo_dissolve_edgeloop_exec(), bmo_dissolve_edges_exec(), bmo_dissolve_faces_exec(), bmo_dissolve_limit_exec(), bmo_dissolve_verts_exec(), bpy_bm_utils_vert_collapse_edge(), bpy_bm_utils_vert_collapse_faces(), init_rotsys(), and mesh_separate_selected().
int BM_vert_edge_count_nonwire (BMVert * v)
Definition at line 418 of file bmesh_queries.c.
References BM_EDGES_OF_VERT, BM_ITER_ELEM, and BMEdge::l.
Referenced by bmw_LoopWalker_begin(), and bmw_LoopWalker_step().
int BM_vert_face_count (BMVert * v)
Returns the number of faces around this vert
Definition at line 454 of file bmesh_queries.c.
References BM_edge_face_count(), BM_ITER_ELEM, BM_LOOPS_OF_VERT, bmesh_disk_edge_next(), BMVert::e, BMEdge::l, and NULL.
Referenced by BM_vert_dissolve(), bmo_pointmerge_facedata_exec(), bmo_similarverts_exec(), and edbm_rip_invoke__vert().
int BM_vert_in_edge (BMEdge * e, BMVert * v)
Returns whether or not a given vertex is is part of a given edge.
Definition at line 48 of file bmesh_queries.c.
References bmesh_vert_in_edge().
Referenced by BM_edge_share_vert(), BM_edge_splice(), BM_face_create_ngon(), BM_vert_other_disk_edge(), BM_vert_separate(), bmesh_disk_validate(), bmesh_elem_check(), bmo_bevel_exec(), bmo_edgenet_prepare(), bmo_vertex_slide_exec(), edbm_rip_edge_side_measure(), and vtx_slide_find_edge().
int BM_vert_in_face (BMFace * f, BMVert * v)
Returns TRUE if the vertex is used in a given face.
Definition at line 196 of file bmesh_queries.c.
References FALSE, BMFace::l_first, BMLoop::next, TRUE, and BMLoop::v.
Referenced by bpy_bm_utils_face_split(), projectSVData(), and remdoubles_splitface().
int BM_vert_is_manifold (BMVert * v)
A vertex is non-manifold if it meets the following conditions: 1: Loose - (has no edges/faces incident upon it). 2: Joins two distinct regions - (two pyramids joined at the tip). 3: Is part of a an edge with more than 2 faces. 4: Is part of a wire edge.
Definition at line 519 of file bmesh_queries.c.
References bmesh_disk_edge_next(), bmesh_radial_length(), BMLoop::e, BMVert::e, FALSE, if(), BMEdge::l, len(), BMLoop::next, NULL, BMLoop::prev, BMLoop::radial_next, TRUE, and BMLoop::v.
Referenced by BM_disk_dissolve(), BM_vert_dissolve(), BME_bevel_initialize(), bmw_IslandboundWalker_step(), bpy_bmvert_is_manifold_get(), calc_solidify_normals(), and edbm_select_non_manifold_exec().
int BM_vert_is_wire (BMVert * v)
Tests whether or not the vertex is part of a wire edge. (ie: has no faces attached to it)
Definition at line 483 of file bmesh_queries.c.
References bmesh_disk_edge_next(), BMVert::e, FALSE, BMEdge::l, NULL, and TRUE.
Referenced by BME_bevel_initialize(), and bpy_bmvert_is_wire_get().
BMEdge* BM_vert_other_disk_edge (BMVert * v, BMEdge * e_first)
The function takes a vertex at the center of a fan and returns the opposite edge in the fan. All edges in the fan must be manifold, otherwise return NULL.
Note:
This could (probably) be done more effieiently.
Definition at line 305 of file bmesh_queries.c.
References BLI_assert, BM_edge_is_manifold(), BM_loop_other_vert_loop(), BM_vert_in_edge(), BMLoop::e, i, BMEdge::l, NULL, BMLoop::prev, and BMLoop::radial_next.
Referenced by edbm_rip_invoke__edge().
int BM_verts_in_edge (BMVert * v1, BMVert * v2, BMEdge * e)
Returns whether or not two vertices are in a given edge
Definition at line 285 of file bmesh_queries.c.
References bmesh_verts_in_edge().
int BM_verts_in_face (BMesh * bm, BMFace * f, BMVert ** varr, int len)
Compares the number of vertices in an array that appear in a given face
Definition at line 224 of file bmesh_queries.c.
References BM_OVERLAP, BMO_elem_flag_disable, BMO_elem_flag_enable, BMO_elem_flag_test, i, BMFace::l_first, len(), BMLoop::next, and BMLoop::v.
Referenced by BM_face_exists(), and BM_face_exists_overlap().