Blender: numinput.c File Reference
numinput.c File Reference
editor utilities
#include <math.h>
#include <stdio.h>
#include "BLI_utildefines.h"
#include "BLI_string.h"
#include "WM_types.h"
#include "ED_numinput.h"
Functions
void initNumInput (NumInput *n)
void outputNumInput (NumInput *n, char *str)
short hasNumInput (NumInput *n)
void applyNumInput (NumInput *n, float *vec)
char handleNumInput (NumInput *n, wmEvent *event)
Detailed Description
Definition in file numinput.c.
Function Documentation
void applyNumInput (NumInput * n, float * vec)
Definition at line 132 of file numinput.c.
References NumInput::ctrl, NumInput::flag, hasNumInput(), i, NumInput::idx, NumInput::idx_max, NumInput::inv, NUM_AFFECT_ALL, NUM_NO_ZERO, NUM_NULL_ONE, and NumInput::val.
Referenced by BakeTime(), Bevel(), BevelWeight(), BoneEnvelope(), BoneRoll(), BoneSize(), Crease(), CurveShrinkFatten(), ed_marker_move_modal(), EdgeSlide(), loopcut_modal(), postConstraintChecks(), PushPull(), Resize(), Rotation(), SeqSlide(), Shear(), ShrinkFatten(), Tilt(), TimeScale(), TimeSlide(), TimeTranslate(), ToSphere(), Trackball(), Translation(), and Warp().
char handleNumInput (NumInput * n, wmEvent * event)
Definition at line 162 of file numinput.c.
References ABS, wmEvent::alt, BACKSPACEKEY, NumInput::ctrl, EIGHTKEY, EVT_MODAL_MAP, fabsf, FIVEKEY, NumInput::flag, FOURKEY, NumInput::idx, NumInput::idx_max, NumInput::increment, NumInput::inv, MINUSKEY, NINEKEY, NUM_MODAL_INCREMENT_DOWN, NUM_MODAL_INCREMENT_UP, NUM_NO_FRACTION, NUM_NO_NEGATIVE, ONEKEY, PAD0, PAD1, PAD2, PAD3, PAD4, PAD5, PAD6, PAD7, PAD8, PAD9, PADMINUS, PADPERIOD, PADSLASHKEY, PERIODKEY, SEVENKEY, SIXKEY, SLASHKEY, TABKEY, THREEKEY, TWOKEY, wmEvent::type, NumInput::val, wmEvent::val, and ZEROKEY.
Referenced by ed_marker_move_modal(), loopcut_modal(), and transformEvent().
short hasNumInput (NumInput * n)
Definition at line 120 of file numinput.c.
References NumInput::ctrl, i, and NumInput::idx_max.
Referenced by applyAxisConstraintRot(), applyNumInput(), applyObjectConstraintRot(), BakeTime(), Bevel(), BevelWeight(), BoneEnvelope(), BoneRoll(), BoneSize(), Crease(), CurveShrinkFatten(), ed_marker_move_modal(), EdgeSlide(), headerBoneSize(), headerResize(), headerSeqSlide(), headerTimeScale(), headerTimeSlide(), headerTimeTranslate(), headerTranslation(), postConstraintChecks(), PushPull(), Resize(), Rotation(), Shear(), ShrinkFatten(), Tilt(), ToSphere(), Trackball(), Translation(), and Warp().
void initNumInput (NumInput * n)
Definition at line 47 of file numinput.c.
References NumInput::ctrl, NumInput::flag, NumInput::idx, NumInput::idx_max, NumInput::inv, and NumInput::val.
Referenced by ed_marker_move_init(), initTransInfo(), and ringsel_init().
void outputNumInput (NumInput * n, char * str)
Definition at line 64 of file numinput.c.
References BLI_snprintf(), NumInput::ctrl, NumInput::flag, i, NumInput::idx, NumInput::idx_max, NumInput::inv, NUM_AFFECT_ALL, and NumInput::val.
Referenced by BakeTime(), Bevel(), BevelWeight(), BoneEnvelope(), BoneRoll(), Crease(), CurveShrinkFatten(), ed_marker_move_modal(), EdgeSlide(), headerBoneSize(), headerResize(), headerSeqSlide(), headerTimeScale(), headerTimeSlide(), headerTimeTranslate(), headerTranslation(), PushPull(), Rotation(), Shear(), ShrinkFatten(), Tilt(), ToSphere(), Trackball(), and Warp().