Blender: SSSPoints Struct Reference
SSSPoints Struct Reference
Public Attributes
struct SSSPoints * next
struct SSSPoints * prev
float(* co)[3]
float(* color)[3]
float * area
int totpoint
Detailed Description
Definition at line 843 of file sss.c.
Member Data Documentation
float* SSSPoints::area
Definition at line 848 of file sss.c.
Referenced by sss_add_points(), and sss_create_tree_mat().
float(* SSSPoints::co)[3]
Definition at line 846 of file sss.c.
Referenced by sss_add_points(), and sss_create_tree_mat().
float(* SSSPoints::color)[3]
Definition at line 847 of file sss.c.
Referenced by sss_add_points(), and sss_create_tree_mat().
struct SSSPoints* SSSPoints::next
Definition at line 844 of file sss.c.
Referenced by sss_create_tree_mat().
struct SSSPoints * SSSPoints::prev
Definition at line 844 of file sss.c.
int SSSPoints::totpoint
Definition at line 849 of file sss.c.
Referenced by sss_add_points(), and sss_create_tree_mat().
The documentation for this struct was generated from the following file:
sss.c