Blender: AUD_SequencerHandle Class Reference
AUD_SequencerHandle Class Reference
#include <AUD_SequencerHandle.h>
Public Member Functions
AUD_SequencerHandle (AUD_Reference< AUD_SequencerEntry > entry, AUD_ReadDevice &device)
~AUD_SequencerHandle ()
int compare (AUD_Reference< AUD_SequencerEntry > entry) const
void stop ()
void update (float position, float frame, float fps)
void seek (float position)
Detailed Description
Represents a playing sequenced entry.
Definition at line 42 of file AUD_SequencerHandle.h.
Constructor & Destructor Documentation
AUD_SequencerHandle::AUD_SequencerHandle (AUD_Reference< AUD_SequencerEntry > entry, AUD_ReadDevice & device)
Creates a new sequenced handle.
Parameters:
entry The entry this handle plays.
device The read device to play on.
Definition at line 33 of file AUD_SequencerHandle.cpp.
References AUD_Reference< T >::isNull(), and AUD_SoftwareDevice::play().
AUD_SequencerHandle::~AUD_SequencerHandle ()
Destroys the handle.
Definition at line 47 of file AUD_SequencerHandle.cpp.
References stop().
Member Function Documentation
int AUD_SequencerHandle::compare (AUD_Reference< AUD_SequencerEntry > entry) const
Compares whether this handle is playing the same entry as supplied.
Parameters:
entry The entry to compare to.
Returns:
Whether the entries ID is smaller, equal or bigger.
Definition at line 52 of file AUD_SequencerHandle.cpp.
void AUD_SequencerHandle::seek (float position)
Seeks the handle to a specific time position.
Parameters:
position The time to seek to.
Definition at line 141 of file AUD_SequencerHandle.cpp.
References AUD_Reference< T >::isNull().
Referenced by update().
void AUD_SequencerHandle::stop (void)
Stops playing back the handle.
Definition at line 61 of file AUD_SequencerHandle.cpp.
References AUD_Reference< T >::isNull().
Referenced by ~AUD_SequencerHandle().
void AUD_SequencerHandle::update (float position, float frame, float fps)
Updates the handle for playback.
Parameters:
position The current time during playback.
frame The current frame during playback.
fps The animation frames per second.
Definition at line 67 of file AUD_SequencerHandle.cpp.
References AUD_Quaternion::get(), AUD_Reference< T >::get(), AUD_Reference< T >::isNull(), AUD_SoftwareDevice::play(), seek(), and AUD_SoftwareDevice::setPanning().
The documentation for this class was generated from the following files:
AUD_SequencerHandle.h
AUD_SequencerHandle.cpp