Blender: render_intern.h File Reference
render_intern.h File Reference
render
Functions
void OBJECT_OT_material_slot_add (struct wmOperatorType *ot)
void OBJECT_OT_material_slot_remove (struct wmOperatorType *ot)
void OBJECT_OT_material_slot_assign (struct wmOperatorType *ot)
void OBJECT_OT_material_slot_select (struct wmOperatorType *ot)
void OBJECT_OT_material_slot_deselect (struct wmOperatorType *ot)
void OBJECT_OT_material_slot_copy (struct wmOperatorType *ot)
void MATERIAL_OT_new (struct wmOperatorType *ot)
void TEXTURE_OT_new (struct wmOperatorType *ot)
void WORLD_OT_new (struct wmOperatorType *ot)
void MATERIAL_OT_copy (struct wmOperatorType *ot)
void MATERIAL_OT_paste (struct wmOperatorType *ot)
void SCENE_OT_render_layer_add (struct wmOperatorType *ot)
void SCENE_OT_render_layer_remove (struct wmOperatorType *ot)
void TEXTURE_OT_slot_copy (struct wmOperatorType *ot)
void TEXTURE_OT_slot_paste (struct wmOperatorType *ot)
void TEXTURE_OT_slot_move (struct wmOperatorType *ot)
void TEXTURE_OT_envmap_save (struct wmOperatorType *ot)
void TEXTURE_OT_envmap_clear (struct wmOperatorType *ot)
void TEXTURE_OT_envmap_clear_all (struct wmOperatorType *ot)
void RENDER_OT_render (struct wmOperatorType *ot)
void image_buffer_rect_update (struct Scene *scene, struct RenderResult *rr, struct ImBuf *ibuf, volatile struct rcti *renrect)
void render_view_open (struct bContext *C, int mx, int my)
void RENDER_OT_view_show (struct wmOperatorType *ot)
void RENDER_OT_view_cancel (struct wmOperatorType *ot)
void RENDER_OT_opengl (struct wmOperatorType *ot)
Detailed Description
Definition in file render_intern.h.
Function Documentation
void image_buffer_rect_update (struct Scene * scene, struct RenderResult * rr, struct ImBuf * ibuf, volatile struct rcti * renrect)
Referenced by image_rect_update(), and screen_opengl_render_apply().
void MATERIAL_OT_copy (struct wmOperatorType * ot)
Definition at line 839 of file render_shading.c.
References copy_material_exec(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, and OPTYPE_REGISTER.
Referenced by ED_operatortypes_render().
void MATERIAL_OT_new (struct wmOperatorType * ot)
Definition at line 403 of file render_shading.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, new_material_exec(), OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by ED_operatortypes_render().
void MATERIAL_OT_paste (struct wmOperatorType * ot)
Definition at line 867 of file render_shading.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and paste_material_exec().
Referenced by ED_operatortypes_render().
void OBJECT_OT_material_slot_add (struct wmOperatorType * ot)
Definition at line 108 of file render_shading.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, material_slot_add_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_render().
void OBJECT_OT_material_slot_assign (struct wmOperatorType * ot)
Definition at line 206 of file render_shading.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, material_slot_assign_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_render().
void OBJECT_OT_material_slot_copy (struct wmOperatorType * ot)
Definition at line 349 of file render_shading.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, material_slot_copy_exec(), wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by ED_operatortypes_render().
void OBJECT_OT_material_slot_deselect (struct wmOperatorType * ot)
Definition at line 309 of file render_shading.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, material_slot_deselect_exec(), wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by ED_operatortypes_render().
void OBJECT_OT_material_slot_remove (struct wmOperatorType * ot)
Definition at line 144 of file render_shading.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, material_slot_remove_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_render().
void OBJECT_OT_material_slot_select (struct wmOperatorType * ot)
Definition at line 290 of file render_shading.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, material_slot_select_exec(), wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by ED_operatortypes_render().
void RENDER_OT_opengl (struct wmOperatorType * ot)
Definition at line 671 of file render_opengl.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_boolean(), RNA_def_property_flag(), screen_opengl_render_cancel(), screen_opengl_render_exec(), screen_opengl_render_invoke(), screen_opengl_render_modal(), and wmOperatorType::srna.
Referenced by ED_operatortypes_render().
void RENDER_OT_render (struct wmOperatorType * ot)
Definition at line 600 of file render_internal.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::modal, wmOperatorType::name, RE_MAXNAME, RNA_def_boolean(), RNA_def_string(), screen_render_exec(), screen_render_invoke(), screen_render_modal(), and wmOperatorType::srna.
Referenced by ED_operatortypes_render().
void RENDER_OT_view_cancel (struct wmOperatorType * ot)
Definition at line 263 of file render_view.c.
References wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and render_view_cancel_exec().
Referenced by ED_operatortypes_render().
void RENDER_OT_view_show (struct wmOperatorType * ot)
Definition at line 330 of file render_view.c.
References wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and render_view_show_invoke().
Referenced by ED_operatortypes_render().
void render_view_open (struct bContext * C, int mx, int my)
Definition at line 132 of file render_view.c.
References biggest_non_image_area(), BKE_image_verify_viewer(), BKE_screen_find_big_area(), CTX_data_scene(), CTX_wm_area(), CTX_wm_screen(), CTX_wm_window(), RenderData::displaymode, ED_area_newspace(), ED_screen_full_newspace(), find_area_image_empty(), find_area_showing_r_result(), ListBase::first, SpaceImage::flag, ScrArea::full, IMA_TYPE_R_RESULT, SpaceImage::image, NULL, wmWindow::posx, wmWindow::posy, Scene::r, R_OUTPUT_NONE, R_OUTPUT_SCREEN, R_OUTPUT_WINDOW, SI_FULLWINDOW, SI_PREVSPACE, RenderData::size, SPACE_IMAGE, ScrArea::spacedata, ScrArea::spacetype, WM_window_open_temp(), wm_window_raise(), WM_WINDOW_RENDER, rcti::xmax, rcti::xmin, RenderData::xsch, rcti::ymax, rcti::ymin, and RenderData::ysch.
Referenced by render_view_show_invoke(), screen_opengl_render_invoke(), and screen_render_invoke().
void SCENE_OT_render_layer_add (struct wmOperatorType * ot)
Definition at line 531 of file render_shading.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and render_layer_add_exec().
Referenced by ED_operatortypes_render().
void SCENE_OT_render_layer_remove (struct wmOperatorType * ot)
Definition at line 558 of file render_shading.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and render_layer_remove_exec().
Referenced by ED_operatortypes_render().
void TEXTURE_OT_envmap_clear (struct wmOperatorType * ot)
Definition at line 780 of file render_shading.c.
References wmOperatorType::description, envmap_clear_exec(), envmap_clear_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_render().
void TEXTURE_OT_envmap_clear_all (struct wmOperatorType * ot)
Definition at line 809 of file render_shading.c.
References wmOperatorType::description, envmap_clear_all_exec(), envmap_clear_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_render().
void TEXTURE_OT_envmap_save (struct wmOperatorType * ot)
Definition at line 732 of file render_shading.c.
References default_envmap_layout, wmOperatorType::description, envmap_save_exec(), envmap_save_invoke(), envmap_save_poll(), wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_SAVE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, IMAGEFILE, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, PROP_HIDDEN, RNA_def_float_array(), RNA_def_property_flag(), wmOperatorType::srna, WM_FILESEL_FILEPATH, and WM_operator_properties_filesel().
Referenced by ED_operatortypes_render().
void TEXTURE_OT_new (struct wmOperatorType * ot)
Definition at line 449 of file render_shading.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, new_texture_exec(), OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by ED_operatortypes_render().
void TEXTURE_OT_slot_copy (struct wmOperatorType * ot)
Definition at line 984 of file render_shading.c.
References copy_mtex_exec(), copy_mtex_poll(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and wmOperatorType::poll.
Referenced by ED_operatortypes_render().
void TEXTURE_OT_slot_move (struct wmOperatorType * ot)
Definition at line 636 of file render_shading.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, RNA_def_enum(), wmOperatorType::srna, and texture_slot_move().
Referenced by ED_operatortypes_render().
void TEXTURE_OT_slot_paste (struct wmOperatorType * ot)
Definition at line 1029 of file render_shading.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and paste_mtex_exec().
Referenced by ED_operatortypes_render().
void WORLD_OT_new (struct wmOperatorType * ot)
Definition at line 503 of file render_shading.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, new_world_exec(), OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by ED_operatortypes_render().