Blender: node_composite_movieclip.c File Reference
node_composite_movieclip.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static CompBuf * node_composit_get_movieclip (RenderData *rd, MovieClip *clip, MovieClipUser *user)
static void node_composit_exec_movieclip (void *data, bNode *node, bNodeStack **UNUSED(in), bNodeStack **out)
static void init (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_movieclip (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_movieclip_out []
Detailed Description
Definition in file node_composite_movieclip.c.
Function Documentation
static void init (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 140 of file node_composite_movieclip.c.
References MovieClipUser::framenr, MEM_callocN(), and bNode::storage.
Referenced by btSymMatrix< T >::btSymMatrix(), Buffer_new(), Parametrizer::calculateAllMissingValues(), deformVerts(), STR_HashedString::hash(), load_tex(), main(), modifiers_getVirtualModifierList(), register_node_type_cmp_movieclip(), register_node_type_cmp_normal(), register_node_type_tex_bricks(), register_node_type_tex_image(), register_node_type_tex_output(), btSymMatrix< T >::resize(), UI_view2d_region_reinit(), and v3d_editvertex_buts().
static void node_composit_exec_movieclip (void * data, bNode * node, bNodeStack ** UNUSEDin, bNodeStack ** out) [static]
Definition at line 103 of file node_composite_movieclip.c.
References angle(), BKE_movieclip_user_set_frame(), BKE_tracking_stabilization_data(), RenderData::cfra, bNodeStack::data, data, MovieTrackingStabilization::flag, generate_preview(), bNode::id, node_composit_get_movieclip(), NULL, MovieTracking::stabilization, bNode::storage, MovieClip::tracking, TRACKING_2D_STABILIZATION, bNodeStack::vec, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_movieclip().
static CompBuf* node_composit_get_movieclip (RenderData * rd, MovieClip * clip, MovieClipUser * user) [static]
Definition at line 45 of file node_composite_movieclip.c.
References alloc_compbuf(), BKE_movieclip_get_ibuf(), ImBuf::channels, RenderData::disprect, FALSE, get_cropped_compbuf(), IB_RECT_INVALID, IMB_dupImBuf(), IMB_float_from_rect(), IMB_freeImBuf(), CompBuf::malloc, MEM_dupallocN(), MEM_freeN(), node_composit_get_float_buffer(), NULL, R_COMP_CROP, CompBuf::rect, ImBuf::rect, ImBuf::rect_float, RenderData::scemode, ImBuf::userflags, ImBuf::x, and ImBuf::y.
Referenced by node_composit_exec_movieclip().
void register_node_type_cmp_movieclip (bNodeTreeType * ttype)
Definition at line 148 of file node_composite_movieclip.c.
References CMP_NODE_MOVIECLIP, init(), NODE_CLASS_INPUT, node_composit_exec_movieclip(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_movieclip_out[] [static]
Initial value:
 {
    {   SOCK_RGBA,      0,  "Image"},
    {   SOCK_FLOAT,     1,  "Offset X"},
    {   SOCK_FLOAT,     1,  "Offset Y"},
    {   SOCK_FLOAT,     1,  "Scale"},
    {   SOCK_FLOAT,     1,  "Angle"},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_composite_movieclip.c.