Blender: RenderEngineType Struct Reference
RenderEngineType Struct Reference
#include <RE_engine.h>
Public Attributes
struct RenderEngineType * next
struct RenderEngineType * prev
char idname [64]
char name [64]
int flag
void(* update)(struct RenderEngine *engine, struct Main *bmain, struct Scene *scene)
void(* render)(struct RenderEngine *engine, struct Scene *scene)
void(* view_update)(struct RenderEngine *engine, const struct bContext *context)
void(* view_draw)(struct RenderEngine *engine, const struct bContext *context)
ExtensionRNA ext
Detailed Description
Definition at line 64 of file RE_engine.h.
Member Data Documentation
ExtensionRNA RenderEngineType::ext
Definition at line 79 of file RE_engine.h.
Referenced by RE_engines_exit().
int RenderEngineType::flag
Definition at line 70 of file RE_engine.h.
Referenced by RE_engine_render(), RE_engines_exit(), and scene_use_new_shading_nodes().
char RenderEngineType::idname[64]
Definition at line 68 of file RE_engine.h.
Referenced by set_engine().
char RenderEngineType::name[64]
Definition at line 69 of file RE_engine.h.
struct RenderEngineType* RenderEngineType::next
Definition at line 65 of file RE_engine.h.
Referenced by RE_engines_exit(), and set_engine().
struct RenderEngineType * RenderEngineType::prev
Definition at line 65 of file RE_engine.h.
void(* RenderEngineType::render)(struct RenderEngine *engine, struct Scene *scene)
Definition at line 73 of file RE_engine.h.
Referenced by RE_engine_is_external(), and RE_engine_render().
void(* RenderEngineType::update)(struct RenderEngine *engine, struct Main *bmain, struct Scene *scene)
Definition at line 72 of file RE_engine.h.
Referenced by RE_engine_render().
void(* RenderEngineType::view_draw)(struct RenderEngine *engine, const struct bContext *context)
Definition at line 76 of file RE_engine.h.
Referenced by view3d_main_area_draw_engine().
void(* RenderEngineType::view_update)(struct RenderEngine *engine, const struct bContext *context)
Definition at line 75 of file RE_engine.h.
Referenced by ED_render_scene_update(), and view3d_main_area_draw_engine().
The documentation for this struct was generated from the following file:
RE_engine.h