Blender: GHOST_WindowSDL.cpp File Reference
GHOST_WindowSDL.cpp File Reference
GHOST API
#include "GHOST_WindowSDL.h"
#include "SDL_mouse.h"
#include <assert.h>
Defines
#define sdl_std_cursor_WIDTH_xterm 9
#define sdl_std_cursor_HEIGHT_xterm 16
#define sdl_std_cursor_HOT_X_xterm -3
#define sdl_std_cursor_HOT_Y_xterm -7
#define sdl_std_cursor_WIDTH_watch 16
#define sdl_std_cursor_HEIGHT_watch 16
#define sdl_std_cursor_HOT_X_watch -15
#define sdl_std_cursor_HOT_Y_watch -7
#define sdl_std_cursor_WIDTH_umbrella 16
#define sdl_std_cursor_HEIGHT_umbrella 16
#define sdl_std_cursor_HOT_X_umbrella -7
#define sdl_std_cursor_HOT_Y_umbrella -12
#define sdl_std_cursor_WIDTH_top_side 15
#define sdl_std_cursor_HEIGHT_top_side 16
#define sdl_std_cursor_HOT_X_top_side -6
#define sdl_std_cursor_HOT_Y_top_side -14
#define sdl_std_cursor_WIDTH_top_right_corner 16
#define sdl_std_cursor_HEIGHT_top_right_corner 16
#define sdl_std_cursor_HOT_X_top_right_corner -13
#define sdl_std_cursor_HOT_Y_top_right_corner -14
#define sdl_std_cursor_WIDTH_top_left_corner 16
#define sdl_std_cursor_HEIGHT_top_left_corner 16
#define sdl_std_cursor_HOT_X_top_left_corner 0
#define sdl_std_cursor_HOT_Y_top_left_corner -14
#define sdl_std_cursor_WIDTH_spraycan 12
#define sdl_std_cursor_HEIGHT_spraycan 16
#define sdl_std_cursor_HOT_X_spraycan -9
#define sdl_std_cursor_HOT_Y_spraycan -14
#define sdl_std_cursor_WIDTH_sb_v_double_arrow 9
#define sdl_std_cursor_HEIGHT_sb_v_double_arrow 15
#define sdl_std_cursor_HOT_X_sb_v_double_arrow -3
#define sdl_std_cursor_HOT_Y_sb_v_double_arrow -8
#define sdl_std_cursor_WIDTH_sb_h_double_arrow 15
#define sdl_std_cursor_HEIGHT_sb_h_double_arrow 9
#define sdl_std_cursor_HOT_X_sb_h_double_arrow -7
#define sdl_std_cursor_HOT_Y_sb_h_double_arrow -4
#define sdl_std_cursor_WIDTH_right_side 16
#define sdl_std_cursor_HEIGHT_right_side 15
#define sdl_std_cursor_HOT_X_right_side -13
#define sdl_std_cursor_HOT_Y_right_side -7
#define sdl_std_cursor_WIDTH_right_ptr 10
#define sdl_std_cursor_HEIGHT_right_ptr 16
#define sdl_std_cursor_HOT_X_right_ptr -7
#define sdl_std_cursor_HOT_Y_right_ptr -14
#define sdl_std_cursor_WIDTH_question_arrow 11
#define sdl_std_cursor_HEIGHT_question_arrow 16
#define sdl_std_cursor_HOT_X_question_arrow -4
#define sdl_std_cursor_HOT_Y_question_arrow -8
#define sdl_std_cursor_WIDTH_pirate 16
#define sdl_std_cursor_HEIGHT_pirate 16
#define sdl_std_cursor_HOT_X_pirate -7
#define sdl_std_cursor_HOT_Y_pirate -4
#define sdl_std_cursor_WIDTH_left_side 16
#define sdl_std_cursor_HEIGHT_left_side 15
#define sdl_std_cursor_HOT_X_left_side 0
#define sdl_std_cursor_HOT_Y_left_side -7
#define sdl_std_cursor_WIDTH_left_ptr 10
#define sdl_std_cursor_HEIGHT_left_ptr 16
#define sdl_std_cursor_HOT_X_left_ptr -8
#define sdl_std_cursor_HOT_Y_left_ptr -14
#define sdl_std_cursor_WIDTH_exchange 16
#define sdl_std_cursor_HEIGHT_exchange 16
#define sdl_std_cursor_HOT_X_exchange -6
#define sdl_std_cursor_HOT_Y_exchange -8
#define sdl_std_cursor_WIDTH_crosshair 16
#define sdl_std_cursor_HEIGHT_crosshair 16
#define sdl_std_cursor_HOT_X_crosshair -7
#define sdl_std_cursor_HOT_Y_crosshair -8
#define sdl_std_cursor_WIDTH_bottom_side 15
#define sdl_std_cursor_HEIGHT_bottom_side 16
#define sdl_std_cursor_HOT_X_bottom_side -6
#define sdl_std_cursor_HOT_Y_bottom_side -1
#define sdl_std_cursor_WIDTH_bottom_right_corner 16
#define sdl_std_cursor_HEIGHT_bottom_right_corner 16
#define sdl_std_cursor_HOT_X_bottom_right_corner -13
#define sdl_std_cursor_HOT_Y_bottom_right_corner -1
#define sdl_std_cursor_WIDTH_bottom_left_corner 16
#define sdl_std_cursor_HEIGHT_bottom_left_corner 16
#define sdl_std_cursor_HOT_X_bottom_left_corner 0
#define sdl_std_cursor_HOT_Y_bottom_left_corner -1
#define sdl_std_cursor_WIDTH_arrow 16
#define sdl_std_cursor_HEIGHT_arrow 16
#define sdl_std_cursor_HOT_X_arrow -13
#define sdl_std_cursor_HOT_Y_arrow -14
#define DEF_CURSOR(name, ind)
Functions
static SDL_Cursor * sdl_ghost_CreateCursor (const Uint8 *data, const Uint8 *mask, int w, int h, int hot_x, int hot_y)
static void sdl_cursor_init (void)
Variables
static SDL_GLContext s_firstContext = NULL
static unsigned char sdl_std_cursor_mask_xterm [] = {0xef,0x01,0xff,0x01,0xff,0x01,0x7c,0x00,0x38,0x00,0x38,0x00,0x38,0x00,0x38,0x00,0x38,0x00,0x38,0x00,0x38,0x00,0x38,0x00,0x7c,0x00,0xff,0x01,0xff,0x01,0xef,0x01,}
static unsigned char sdl_std_cursor_xterm [] = {0x00,0x77,0x00,0x1c,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x1c,0x00,0x77,0x00,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_watch [] = {0xfc,0x0f,0xfc,0x0f,0xfc,0x0f,0xfe,0x1f,0xff,0x3f,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x3f,0xfe,0x1f,0xfc,0x0f,0xfc,0x0f,0xfc,0x0f,}
static unsigned char sdl_std_cursor_watch [] = {0xf8,0x07,0xf8,0x07,0xf8,0x07,0xfc,0x0f,0x86,0x18,0x83,0x30,0x81,0xe0,0xc1,0xe1,0xc1,0xe1,0x21,0xe0,0x13,0x30,0x06,0x18,0xfc,0x0f,0xf8,0x07,0xf8,0x07,0xf8,0x07,}
static unsigned char sdl_std_cursor_mask_umbrella [] = {0xe8,0x76,0xfb,0xdf,0xfd,0x3f,0xfe,0xff,0xff,0x3f,0xff,0xff,0xcf,0x79,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x07,0xc0,0x07,0xc0,0x07,0xc0,0x07,0x80,0x03,}
static unsigned char sdl_std_cursor_umbrella [] = {0x88,0x04,0x20,0x0a,0xc9,0x32,0xf2,0x09,0x4c,0x06,0x43,0x18,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x01,0x40,0x01,0x80,0x00,0x00,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_top_side [] = {0xff,0x7f,0xff,0x7f,0xff,0x7f,0xff,0x7f,0xc0,0x01,0xe0,0x03,0xf0,0x07,0xf8,0x0f,0xdc,0x1d,0xcc,0x19,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,}
static unsigned char sdl_std_cursor_top_side [] = {0xff,0x1f,0xff,0x1f,0x00,0x00,0x40,0x00,0xe0,0x00,0x50,0x01,0x48,0x02,0x44,0x04,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x00,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_top_right_corner [] = {0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x00,0xf0,0xfc,0xf7,0xfc,0xf7,0xfc,0xf7,0xc0,0xf7,0xe0,0xf7,0x70,0xf7,0x38,0xf7,0x1c,0xf7,0x0c,0xf7,0x00,0xf0,0x00,0xf0,}
static unsigned char sdl_std_cursor_top_right_corner [] = {0xff,0x3f,0xff,0x3f,0x00,0x30,0x00,0x30,0x00,0x30,0xfc,0x31,0x80,0x31,0x40,0x31,0x20,0x31,0x10,0x31,0x08,0x31,0x04,0x31,0x00,0x30,0x00,0x30,0x00,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_top_left_corner [] = {0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x0f,0x00,0xef,0x3f,0xef,0x3f,0xef,0x3f,0xef,0x03,0xef,0x07,0xef,0x0e,0xef,0x1c,0xef,0x38,0xef,0x30,0x0f,0x00,0x0f,0x00,}
static unsigned char sdl_std_cursor_top_left_corner [] = {0xff,0x3f,0xff,0x3f,0x03,0x00,0x03,0x00,0x03,0x00,0xe3,0x0f,0x63,0x00,0xa3,0x00,0x23,0x01,0x23,0x02,0x23,0x04,0x23,0x08,0x03,0x00,0x03,0x00,0x00,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_spraycan [] = {0x00,0x0c,0x18,0x0d,0x7c,0x0d,0x7c,0x0d,0x7e,0x0d,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,}
static unsigned char sdl_std_cursor_spraycan [] = {0x00,0x06,0x80,0x00,0x2c,0x06,0x9e,0x00,0x16,0x06,0x3f,0x00,0x21,0x00,0x27,0x00,0x25,0x00,0x27,0x00,0x25,0x00,0x27,0x00,0x27,0x00,0x21,0x00,0x21,0x00,0x3f,0x00,}
static unsigned char sdl_std_cursor_mask_sb_v_double_arrow [] = {0x38,0x00,0x7c,0x00,0xfe,0x00,0xff,0x01,0xff,0x01,0x7c,0x00,0x7c,0x00,0x7c,0x00,0x7c,0x00,0x7c,0x00,0xff,0x01,0xff,0x01,0xfe,0x00,0x7c,0x00,0x38,0x00,}
static unsigned char sdl_std_cursor_sb_v_double_arrow [] = {0x10,0x00,0x38,0x00,0x7c,0x00,0xfe,0x00,0x28,0x00,0x28,0x00,0x28,0x00,0x28,0x00,0x28,0x00,0x28,0x00,0x28,0x00,0xfe,0x00,0x7c,0x00,0x38,0x00,0x10,0x00,}
static unsigned char sdl_std_cursor_mask_sb_h_double_arrow [] = {0x18,0x0c,0x1c,0x1c,0xfe,0x3f,0xff,0x7f,0xff,0x7f,0xff,0x7f,0xfe,0x3f,0x1c,0x1c,0x18,0x0c,}
static unsigned char sdl_std_cursor_sb_h_double_arrow [] = {0x00,0x00,0x08,0x08,0x0c,0x18,0xfe,0x3f,0x0f,0x78,0xfe,0x3f,0x0c,0x18,0x08,0x08,0x00,0x00}
static unsigned char sdl_std_cursor_mask_right_side [] = {0x00,0xf0,0x00,0xf0,0xc0,0xf0,0xc0,0xf1,0x80,0xf3,0x00,0xf7,0xff,0xff,0xff,0xff,0xff,0xff,0x00,0xf7,0x80,0xf3,0xc0,0xf1,0xc0,0xf0,0x00,0xf0,0x00,0xf0,}
static unsigned char sdl_std_cursor_right_side [] = {0x00,0x30,0x00,0x30,0x40,0x30,0x80,0x30,0x00,0x31,0x00,0x32,0xff,0x37,0x00,0x32,0x00,0x31,0x80,0x30,0x40,0x30,0x00,0x30,0x00,0x30,0x00,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_right_ptr [] = {0x00,0x03,0x80,0x03,0xc0,0x03,0xe0,0x03,0xf0,0x03,0xf8,0x03,0xfc,0x03,0xfe,0x03,0xff,0x03,0xff,0x03,0xf8,0x03,0xbc,0x03,0x3c,0x03,0x1e,0x00,0x1e,0x00,0x0c,0x00,}
static unsigned char sdl_std_cursor_right_ptr [] = {0x00,0x80,0x00,0xc0,0x00,0xe0,0x00,0xf0,0x00,0xf8,0x00,0xfc,0x00,0xfe,0x00,0xff,0x00,0xf8,0x00,0xd8,0x00,0x8c,0x00,0x0c,0x00,0x06,0x00,0x06,0x00,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_question_arrow [] = {0xf8,0x00,0xfc,0x01,0xfe,0x03,0xff,0x07,0x8f,0x07,0x9f,0x07,0xde,0x07,0xfc,0x03,0xf8,0x01,0xf8,0x00,0xf8,0x00,0xfc,0x01,0xfe,0x03,0xfc,0x01,0xf8,0x00,0x70,0x00,}
static unsigned char sdl_std_cursor_question_arrow [] = {0x7c,0x00,0xfe,0x00,0xc7,0x01,0x83,0x01,0x87,0x01,0xc6,0x01,0xe0,0x00,0x78,0x00,0x38,0x00,0x28,0x00,0x28,0x00,0xee,0x00,0x6c,0x00,0x38,0x00,0x10,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_pirate [] = {0xf0,0x03,0xf8,0x07,0xfc,0x0f,0xfe,0x1f,0xfe,0x1f,0xfc,0x0f,0xf8,0x07,0xf1,0x83,0xf1,0xe3,0xf3,0xf3,0xef,0x39,0x1e,0x1e,0xe0,0x01,0xfe,0xc7,0xff,0xff,0x0f,0x7c,}
static unsigned char sdl_std_cursor_pirate [] = {0xe0,0x01,0xf0,0x03,0xf8,0x07,0xcc,0x0c,0xcc,0x0c,0xf8,0x07,0xf0,0x03,0xe0,0x01,0xe1,0x21,0xe1,0x61,0xc2,0x10,0x1c,0x0e,0xe0,0x01,0xf8,0x47,0x0f,0x7c,0x01,0x20,}
static unsigned char sdl_std_cursor_mask_left_side [] = {0x0f,0x00,0x0f,0x00,0x0f,0x03,0x8f,0x03,0xcf,0x01,0xef,0x00,0xff,0xff,0xff,0xff,0xff,0xff,0xef,0x00,0xcf,0x01,0x8f,0x03,0x0f,0x03,0x0f,0x00,0x0f,0x00,}
static unsigned char sdl_std_cursor_left_side [] = {0x03,0x00,0x03,0x00,0x83,0x00,0x43,0x00,0x23,0x00,0x13,0x00,0xfb,0x3f,0x13,0x00,0x23,0x00,0x43,0x00,0x83,0x00,0x03,0x00,0x03,0x00,0x00,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_left_ptr [] = {0x03,0x00,0x07,0x00,0x0f,0x00,0x1f,0x00,0x3f,0x00,0x7f,0x00,0xff,0x00,0xff,0x01,0xff,0x03,0xff,0x03,0x7f,0x00,0xf7,0x00,0xf3,0x00,0xe0,0x01,0xe0,0x01,0xc0,0x00,}
static unsigned char sdl_std_cursor_left_ptr [] = {0x00,0x00,0x02,0x00,0x06,0x00,0x0e,0x00,0x1e,0x00,0x3e,0x00,0x7e,0x00,0xfe,0x00,0xfe,0x00,0x3e,0x00,0x36,0x00,0x62,0x00,0x60,0x00,0xc0,0x00,0xc0,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_exchange [] = {0xe3,0x07,0xf7,0x0f,0xff,0x1f,0xff,0x3f,0x3f,0x38,0xff,0x30,0xff,0x00,0xff,0x00,0x00,0xff,0x00,0xff,0x0c,0xfe,0x1c,0xfc,0xfc,0xff,0xf8,0xff,0xf0,0xef,0xe0,0xc7,}
static unsigned char sdl_std_cursor_exchange [] = {0xf1,0x03,0xfb,0x07,0x1f,0x0c,0x09,0x08,0x19,0x00,0x3f,0x00,0x00,0x00,0x00,0x00,0x00,0x3f,0x00,0x26,0x04,0x24,0x0c,0x3e,0xf8,0x37,0xf0,0x23,0x00,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_crosshair [] = {0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xff,0xff,0xff,0xff,0xff,0xff,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,}
static unsigned char sdl_std_cursor_crosshair [] = {0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x7f,0xff,0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_bottom_side [] = {0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xcc,0x19,0xdc,0x1d,0xf8,0x0f,0xf0,0x07,0xe0,0x03,0xc0,0x01,0xff,0x7f,0xff,0x7f,0xff,0x7f,0xff,0x7f,}
static unsigned char sdl_std_cursor_bottom_side [] = {0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x44,0x04,0x48,0x02,0x50,0x01,0xe0,0x00,0x40,0x00,0x00,0x00,0xff,0x1f,0xff,0x1f,0x00,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_bottom_right_corner [] = {0x00,0xf0,0x00,0xf0,0x0c,0xf7,0x1c,0xf7,0x38,0xf7,0x70,0xf7,0xe0,0xf7,0xc0,0xf7,0xfc,0xf7,0xfc,0xf7,0xfc,0xf7,0x00,0xf0,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,}
static unsigned char sdl_std_cursor_bottom_right_corner [] = {0x00,0x30,0x00,0x30,0x04,0x31,0x08,0x31,0x10,0x31,0x20,0x31,0x40,0x31,0x80,0x31,0xfc,0x31,0x00,0x30,0x00,0x30,0x00,0x30,0xff,0x3f,0xff,0x3f,0x00,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_bottom_left_corner [] = {0x0f,0x00,0x0f,0x00,0xef,0x30,0xef,0x38,0xef,0x1c,0xef,0x0e,0xef,0x07,0xef,0x03,0xef,0x3f,0xef,0x3f,0xef,0x3f,0x0f,0x00,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,}
static unsigned char sdl_std_cursor_bottom_left_corner [] = {0x03,0x00,0x03,0x00,0x23,0x08,0x23,0x04,0x23,0x02,0x23,0x01,0xa3,0x00,0x63,0x00,0xe3,0x0f,0x03,0x00,0x03,0x00,0x03,0x00,0xff,0x3f,0xff,0x3f,0x00,0x00,0x00,0x00,}
static unsigned char sdl_std_cursor_mask_arrow [] = {0x00,0xe0,0x00,0xf8,0x00,0xfe,0x80,0x7f,0xe0,0x7f,0xf8,0x3f,0xfc,0x3f,0xfc,0x1f,0xe0,0x1f,0xf0,0x0f,0xf8,0x0f,0x7c,0x07,0x3e,0x07,0x1f,0x02,0x0e,0x00,0x04,0x00,}
static unsigned char sdl_std_cursor_arrow [] = {0x00,0x30,0x00,0x3c,0x00,0x1f,0xc0,0x1f,0xf0,0x0f,0xfc,0x0f,0xc0,0x07,0xe0,0x07,0x70,0x03,0x38,0x03,0x1c,0x01,0x0e,0x01,0x07,0x00,0x02,0x00,0x00,0x00,0x00,0x00,}
static SDL_Cursor * sdl_std_cursor_array [(int) GHOST_kStandardCursorNumCursors] = {0}
Detailed Description
Definition in file GHOST_WindowSDL.cpp.
Define Documentation
#define DEF_CURSOR (name, ind)
Value:
assert(\
        (\
        sdl_std_cursor_array[(int)ind]= \
                sdl_ghost_CreateCursor(sdl_std_cursor_##name, \
                sdl_std_cursor_mask_##name, \
                sdl_std_cursor_WIDTH_##name, \
                sdl_std_cursor_HEIGHT_##name, \
                (sdl_std_cursor_WIDTH_##name + (sdl_std_cursor_HOT_X_##name)) - 1, \
                (sdl_std_cursor_HEIGHT_##name + (sdl_std_cursor_HOT_Y_##name)) - 1) \
        ) != NULL) \
Referenced by sdl_cursor_init().
#define sdl_std_cursor_HEIGHT_arrow 16
Definition at line 452 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_bottom_left_corner 16
Definition at line 445 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_bottom_right_corner 16
Definition at line 438 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_bottom_side 16
Definition at line 431 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_crosshair 16
Definition at line 424 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_exchange 16
Definition at line 417 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_left_ptr 16
Definition at line 410 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_left_side 15
Definition at line 403 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_pirate 16
Definition at line 396 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_question_arrow 16
Definition at line 389 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_right_ptr 16
Definition at line 382 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_right_side 15
Definition at line 375 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_sb_h_double_arrow 9
Definition at line 368 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_sb_v_double_arrow 15
Definition at line 361 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_spraycan 16
Definition at line 354 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_top_left_corner 16
Definition at line 347 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_top_right_corner 16
Definition at line 340 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_top_side 16
Definition at line 333 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_umbrella 16
Definition at line 326 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_watch 16
Definition at line 319 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HEIGHT_xterm 16
Definition at line 312 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_arrow -13
Definition at line 453 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_bottom_left_corner 0
Definition at line 446 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_bottom_right_corner -13
Definition at line 439 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_bottom_side -6
Definition at line 432 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_crosshair -7
Definition at line 425 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_exchange -6
Definition at line 418 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_left_ptr -8
Definition at line 411 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_left_side 0
Definition at line 404 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_pirate -7
Definition at line 397 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_question_arrow -4
Definition at line 390 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_right_ptr -7
Definition at line 383 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_right_side -13
Definition at line 376 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_sb_h_double_arrow -7
Definition at line 369 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_sb_v_double_arrow -3
Definition at line 362 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_spraycan -9
Definition at line 355 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_top_left_corner 0
Definition at line 348 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_top_right_corner -13
Definition at line 341 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_top_side -6
Definition at line 334 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_umbrella -7
Definition at line 327 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_watch -15
Definition at line 320 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_X_xterm -3
Definition at line 313 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_arrow -14
Definition at line 454 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_bottom_left_corner -1
Definition at line 447 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_bottom_right_corner -1
Definition at line 440 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_bottom_side -1
Definition at line 433 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_crosshair -8
Definition at line 426 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_exchange -8
Definition at line 419 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_left_ptr -14
Definition at line 412 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_left_side -7
Definition at line 405 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_pirate -4
Definition at line 398 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_question_arrow -8
Definition at line 391 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_right_ptr -14
Definition at line 384 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_right_side -7
Definition at line 377 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_sb_h_double_arrow -4
Definition at line 370 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_sb_v_double_arrow -8
Definition at line 363 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_spraycan -14
Definition at line 356 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_top_left_corner -14
Definition at line 349 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_top_right_corner -14
Definition at line 342 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_top_side -14
Definition at line 335 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_umbrella -12
Definition at line 328 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_watch -7
Definition at line 321 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_HOT_Y_xterm -7
Definition at line 314 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_arrow 16
Definition at line 451 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_bottom_left_corner 16
Definition at line 444 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_bottom_right_corner 16
Definition at line 437 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_bottom_side 15
Definition at line 430 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_crosshair 16
Definition at line 423 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_exchange 16
Definition at line 416 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_left_ptr 10
Definition at line 409 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_left_side 16
Definition at line 402 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_pirate 16
Definition at line 395 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_question_arrow 11
Definition at line 388 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_right_ptr 10
Definition at line 381 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_right_side 16
Definition at line 374 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_sb_h_double_arrow 15
Definition at line 367 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_sb_v_double_arrow 9
Definition at line 360 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_spraycan 12
Definition at line 353 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_top_left_corner 16
Definition at line 346 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_top_right_corner 16
Definition at line 339 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_top_side 15
Definition at line 332 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_umbrella 16
Definition at line 325 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_watch 16
Definition at line 318 of file GHOST_WindowSDL.cpp.
#define sdl_std_cursor_WIDTH_xterm 9
Definition at line 311 of file GHOST_WindowSDL.cpp.
Function Documentation
static void sdl_cursor_init (void) [static]
Definition at line 521 of file GHOST_WindowSDL.cpp.
References DEF_CURSOR, GHOST_kStandardCursorBottomLeftCorner, GHOST_kStandardCursorBottomRightCorner, GHOST_kStandardCursorBottomSide, GHOST_kStandardCursorCopy, GHOST_kStandardCursorCrosshair, GHOST_kStandardCursorCycle, GHOST_kStandardCursorDefault, GHOST_kStandardCursorDestroy, GHOST_kStandardCursorHelp, GHOST_kStandardCursorInfo, GHOST_kStandardCursorLeftArrow, GHOST_kStandardCursorLeftRight, GHOST_kStandardCursorLeftSide, GHOST_kStandardCursorPencil, GHOST_kStandardCursorRightArrow, GHOST_kStandardCursorRightSide, GHOST_kStandardCursorSpray, GHOST_kStandardCursorText, GHOST_kStandardCursorTopLeftCorner, GHOST_kStandardCursorTopRightCorner, GHOST_kStandardCursorTopSide, GHOST_kStandardCursorUpDown, and GHOST_kStandardCursorWait.
Referenced by GHOST_WindowSDL::setWindowCursorShape().
static SDL_Cursor* sdl_ghost_CreateCursor (const Uint8 * data, const Uint8 * mask, int w, int h, int hot_x, int hot_y) [static]
Definition at line 463 of file GHOST_WindowSDL.cpp.
References NULL, and transparent().
Referenced by GHOST_WindowSDL::setWindowCustomCursorShape().
Variable Documentation
SDL_GLContext s_firstContext = NULL [static]
Definition at line 31 of file GHOST_WindowSDL.cpp.
Referenced by GHOST_WindowX11::installDrawingContext(), GHOST_WindowSDL::installDrawingContext(), GHOST_WindowSDL::~GHOST_WindowSDL(), and GHOST_WindowX11::~GHOST_WindowX11().
SDL_Cursor* sdl_std_cursor_array[(int) GHOST_kStandardCursorNumCursors] = {0} [static]
Definition at line 458 of file GHOST_WindowSDL.cpp.
Referenced by GHOST_WindowSDL::setWindowCursorShape().
unsigned char sdl_std_cursor_arrow[] = {0x00,0x30,0x00,0x3c,0x00,0x1f,0xc0,0x1f,0xf0,0x0f,0xfc,0x0f,0xc0,0x07,0xe0,0x07,0x70,0x03,0x38,0x03,0x1c,0x01,0x0e,0x01,0x07,0x00,0x02,0x00,0x00,0x00,0x00,0x00,} [static]
Definition at line 450 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_bottom_left_corner[] = {0x03,0x00,0x03,0x00,0x23,0x08,0x23,0x04,0x23,0x02,0x23,0x01,0xa3,0x00,0x63,0x00,0xe3,0x0f,0x03,0x00,0x03,0x00,0x03,0x00,0xff,0x3f,0xff,0x3f,0x00,0x00,0x00,0x00,} [static]
Definition at line 443 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_bottom_right_corner[] = {0x00,0x30,0x00,0x30,0x04,0x31,0x08,0x31,0x10,0x31,0x20,0x31,0x40,0x31,0x80,0x31,0xfc,0x31,0x00,0x30,0x00,0x30,0x00,0x30,0xff,0x3f,0xff,0x3f,0x00,0x00,0x00,0x00,} [static]
Definition at line 436 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_bottom_side[] = {0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x44,0x04,0x48,0x02,0x50,0x01,0xe0,0x00,0x40,0x00,0x00,0x00,0xff,0x1f,0xff,0x1f,0x00,0x00,0x00,0x00,} [static]
Definition at line 429 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_crosshair[] = {0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x7f,0xff,0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x00,0x00,} [static]
Definition at line 422 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_exchange[] = {0xf1,0x03,0xfb,0x07,0x1f,0x0c,0x09,0x08,0x19,0x00,0x3f,0x00,0x00,0x00,0x00,0x00,0x00,0x3f,0x00,0x26,0x04,0x24,0x0c,0x3e,0xf8,0x37,0xf0,0x23,0x00,0x00,0x00,0x00,} [static]
Definition at line 415 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_left_ptr[] = {0x00,0x00,0x02,0x00,0x06,0x00,0x0e,0x00,0x1e,0x00,0x3e,0x00,0x7e,0x00,0xfe,0x00,0xfe,0x00,0x3e,0x00,0x36,0x00,0x62,0x00,0x60,0x00,0xc0,0x00,0xc0,0x00,0x00,0x00,} [static]
Definition at line 408 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_left_side[] = {0x03,0x00,0x03,0x00,0x83,0x00,0x43,0x00,0x23,0x00,0x13,0x00,0xfb,0x3f,0x13,0x00,0x23,0x00,0x43,0x00,0x83,0x00,0x03,0x00,0x03,0x00,0x00,0x00,0x00,0x00,} [static]
Definition at line 401 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_arrow[] = {0x00,0xe0,0x00,0xf8,0x00,0xfe,0x80,0x7f,0xe0,0x7f,0xf8,0x3f,0xfc,0x3f,0xfc,0x1f,0xe0,0x1f,0xf0,0x0f,0xf8,0x0f,0x7c,0x07,0x3e,0x07,0x1f,0x02,0x0e,0x00,0x04,0x00,} [static]
Definition at line 449 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_bottom_left_corner[] = {0x0f,0x00,0x0f,0x00,0xef,0x30,0xef,0x38,0xef,0x1c,0xef,0x0e,0xef,0x07,0xef,0x03,0xef,0x3f,0xef,0x3f,0xef,0x3f,0x0f,0x00,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,} [static]
Definition at line 442 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_bottom_right_corner[] = {0x00,0xf0,0x00,0xf0,0x0c,0xf7,0x1c,0xf7,0x38,0xf7,0x70,0xf7,0xe0,0xf7,0xc0,0xf7,0xfc,0xf7,0xfc,0xf7,0xfc,0xf7,0x00,0xf0,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,} [static]
Definition at line 435 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_bottom_side[] = {0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xcc,0x19,0xdc,0x1d,0xf8,0x0f,0xf0,0x07,0xe0,0x03,0xc0,0x01,0xff,0x7f,0xff,0x7f,0xff,0x7f,0xff,0x7f,} [static]
Definition at line 428 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_crosshair[] = {0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xff,0xff,0xff,0xff,0xff,0xff,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,} [static]
Definition at line 421 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_exchange[] = {0xe3,0x07,0xf7,0x0f,0xff,0x1f,0xff,0x3f,0x3f,0x38,0xff,0x30,0xff,0x00,0xff,0x00,0x00,0xff,0x00,0xff,0x0c,0xfe,0x1c,0xfc,0xfc,0xff,0xf8,0xff,0xf0,0xef,0xe0,0xc7,} [static]
Definition at line 414 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_left_ptr[] = {0x03,0x00,0x07,0x00,0x0f,0x00,0x1f,0x00,0x3f,0x00,0x7f,0x00,0xff,0x00,0xff,0x01,0xff,0x03,0xff,0x03,0x7f,0x00,0xf7,0x00,0xf3,0x00,0xe0,0x01,0xe0,0x01,0xc0,0x00,} [static]
Definition at line 407 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_left_side[] = {0x0f,0x00,0x0f,0x00,0x0f,0x03,0x8f,0x03,0xcf,0x01,0xef,0x00,0xff,0xff,0xff,0xff,0xff,0xff,0xef,0x00,0xcf,0x01,0x8f,0x03,0x0f,0x03,0x0f,0x00,0x0f,0x00,} [static]
Definition at line 400 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_pirate[] = {0xf0,0x03,0xf8,0x07,0xfc,0x0f,0xfe,0x1f,0xfe,0x1f,0xfc,0x0f,0xf8,0x07,0xf1,0x83,0xf1,0xe3,0xf3,0xf3,0xef,0x39,0x1e,0x1e,0xe0,0x01,0xfe,0xc7,0xff,0xff,0x0f,0x7c,} [static]
Definition at line 393 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_question_arrow[] = {0xf8,0x00,0xfc,0x01,0xfe,0x03,0xff,0x07,0x8f,0x07,0x9f,0x07,0xde,0x07,0xfc,0x03,0xf8,0x01,0xf8,0x00,0xf8,0x00,0xfc,0x01,0xfe,0x03,0xfc,0x01,0xf8,0x00,0x70,0x00,} [static]
Definition at line 386 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_right_ptr[] = {0x00,0x03,0x80,0x03,0xc0,0x03,0xe0,0x03,0xf0,0x03,0xf8,0x03,0xfc,0x03,0xfe,0x03,0xff,0x03,0xff,0x03,0xf8,0x03,0xbc,0x03,0x3c,0x03,0x1e,0x00,0x1e,0x00,0x0c,0x00,} [static]
Definition at line 379 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_right_side[] = {0x00,0xf0,0x00,0xf0,0xc0,0xf0,0xc0,0xf1,0x80,0xf3,0x00,0xf7,0xff,0xff,0xff,0xff,0xff,0xff,0x00,0xf7,0x80,0xf3,0xc0,0xf1,0xc0,0xf0,0x00,0xf0,0x00,0xf0,} [static]
Definition at line 372 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_sb_h_double_arrow[] = {0x18,0x0c,0x1c,0x1c,0xfe,0x3f,0xff,0x7f,0xff,0x7f,0xff,0x7f,0xfe,0x3f,0x1c,0x1c,0x18,0x0c,} [static]
Definition at line 365 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_sb_v_double_arrow[] = {0x38,0x00,0x7c,0x00,0xfe,0x00,0xff,0x01,0xff,0x01,0x7c,0x00,0x7c,0x00,0x7c,0x00,0x7c,0x00,0x7c,0x00,0xff,0x01,0xff,0x01,0xfe,0x00,0x7c,0x00,0x38,0x00,} [static]
Definition at line 358 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_spraycan[] = {0x00,0x0c,0x18,0x0d,0x7c,0x0d,0x7c,0x0d,0x7e,0x0d,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,0xff,0x00,} [static]
Definition at line 351 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_top_left_corner[] = {0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x0f,0x00,0xef,0x3f,0xef,0x3f,0xef,0x3f,0xef,0x03,0xef,0x07,0xef,0x0e,0xef,0x1c,0xef,0x38,0xef,0x30,0x0f,0x00,0x0f,0x00,} [static]
Definition at line 344 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_top_right_corner[] = {0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x00,0xf0,0xfc,0xf7,0xfc,0xf7,0xfc,0xf7,0xc0,0xf7,0xe0,0xf7,0x70,0xf7,0x38,0xf7,0x1c,0xf7,0x0c,0xf7,0x00,0xf0,0x00,0xf0,} [static]
Definition at line 337 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_top_side[] = {0xff,0x7f,0xff,0x7f,0xff,0x7f,0xff,0x7f,0xc0,0x01,0xe0,0x03,0xf0,0x07,0xf8,0x0f,0xdc,0x1d,0xcc,0x19,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,} [static]
Definition at line 330 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_umbrella[] = {0xe8,0x76,0xfb,0xdf,0xfd,0x3f,0xfe,0xff,0xff,0x3f,0xff,0xff,0xcf,0x79,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x01,0xc0,0x07,0xc0,0x07,0xc0,0x07,0xc0,0x07,0x80,0x03,} [static]
Definition at line 323 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_watch[] = {0xfc,0x0f,0xfc,0x0f,0xfc,0x0f,0xfe,0x1f,0xff,0x3f,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x3f,0xfe,0x1f,0xfc,0x0f,0xfc,0x0f,0xfc,0x0f,} [static]
Definition at line 316 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_mask_xterm[] = {0xef,0x01,0xff,0x01,0xff,0x01,0x7c,0x00,0x38,0x00,0x38,0x00,0x38,0x00,0x38,0x00,0x38,0x00,0x38,0x00,0x38,0x00,0x38,0x00,0x7c,0x00,0xff,0x01,0xff,0x01,0xef,0x01,} [static]
Definition at line 309 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_pirate[] = {0xe0,0x01,0xf0,0x03,0xf8,0x07,0xcc,0x0c,0xcc,0x0c,0xf8,0x07,0xf0,0x03,0xe0,0x01,0xe1,0x21,0xe1,0x61,0xc2,0x10,0x1c,0x0e,0xe0,0x01,0xf8,0x47,0x0f,0x7c,0x01,0x20,} [static]
Definition at line 394 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_question_arrow[] = {0x7c,0x00,0xfe,0x00,0xc7,0x01,0x83,0x01,0x87,0x01,0xc6,0x01,0xe0,0x00,0x78,0x00,0x38,0x00,0x28,0x00,0x28,0x00,0xee,0x00,0x6c,0x00,0x38,0x00,0x10,0x00,0x00,0x00,} [static]
Definition at line 387 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_right_ptr[] = {0x00,0x80,0x00,0xc0,0x00,0xe0,0x00,0xf0,0x00,0xf8,0x00,0xfc,0x00,0xfe,0x00,0xff,0x00,0xf8,0x00,0xd8,0x00,0x8c,0x00,0x0c,0x00,0x06,0x00,0x06,0x00,0x00,0x00,0x00,} [static]
Definition at line 380 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_right_side[] = {0x00,0x30,0x00,0x30,0x40,0x30,0x80,0x30,0x00,0x31,0x00,0x32,0xff,0x37,0x00,0x32,0x00,0x31,0x80,0x30,0x40,0x30,0x00,0x30,0x00,0x30,0x00,0x00,0x00,0x00,} [static]
Definition at line 373 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_sb_h_double_arrow[] = {0x00,0x00,0x08,0x08,0x0c,0x18,0xfe,0x3f,0x0f,0x78,0xfe,0x3f,0x0c,0x18,0x08,0x08,0x00,0x00} [static]
Definition at line 366 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_sb_v_double_arrow[] = {0x10,0x00,0x38,0x00,0x7c,0x00,0xfe,0x00,0x28,0x00,0x28,0x00,0x28,0x00,0x28,0x00,0x28,0x00,0x28,0x00,0x28,0x00,0xfe,0x00,0x7c,0x00,0x38,0x00,0x10,0x00,} [static]
Definition at line 359 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_spraycan[] = {0x00,0x06,0x80,0x00,0x2c,0x06,0x9e,0x00,0x16,0x06,0x3f,0x00,0x21,0x00,0x27,0x00,0x25,0x00,0x27,0x00,0x25,0x00,0x27,0x00,0x27,0x00,0x21,0x00,0x21,0x00,0x3f,0x00,} [static]
Definition at line 352 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_top_left_corner[] = {0xff,0x3f,0xff,0x3f,0x03,0x00,0x03,0x00,0x03,0x00,0xe3,0x0f,0x63,0x00,0xa3,0x00,0x23,0x01,0x23,0x02,0x23,0x04,0x23,0x08,0x03,0x00,0x03,0x00,0x00,0x00,0x00,0x00,} [static]
Definition at line 345 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_top_right_corner[] = {0xff,0x3f,0xff,0x3f,0x00,0x30,0x00,0x30,0x00,0x30,0xfc,0x31,0x80,0x31,0x40,0x31,0x20,0x31,0x10,0x31,0x08,0x31,0x04,0x31,0x00,0x30,0x00,0x30,0x00,0x00,0x00,0x00,} [static]
Definition at line 338 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_top_side[] = {0xff,0x1f,0xff,0x1f,0x00,0x00,0x40,0x00,0xe0,0x00,0x50,0x01,0x48,0x02,0x44,0x04,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x00,0x00,0x00,0x00,} [static]
Definition at line 331 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_umbrella[] = {0x88,0x04,0x20,0x0a,0xc9,0x32,0xf2,0x09,0x4c,0x06,0x43,0x18,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x00,0x40,0x01,0x40,0x01,0x80,0x00,0x00,0x00,0x00,0x00,} [static]
Definition at line 324 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_watch[] = {0xf8,0x07,0xf8,0x07,0xf8,0x07,0xfc,0x0f,0x86,0x18,0x83,0x30,0x81,0xe0,0xc1,0xe1,0xc1,0xe1,0x21,0xe0,0x13,0x30,0x06,0x18,0xfc,0x0f,0xf8,0x07,0xf8,0x07,0xf8,0x07,} [static]
Definition at line 317 of file GHOST_WindowSDL.cpp.
unsigned char sdl_std_cursor_xterm[] = {0x00,0x77,0x00,0x1c,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x08,0x00,0x1c,0x00,0x77,0x00,0x00,0x00,0x00,} [static]
Definition at line 310 of file GHOST_WindowSDL.cpp.