Blender: SCA_XORController Class Reference
SCA_XORController Class Reference
#include <SCA_XORController.h>
Public Member Functions
SCA_XORController (SCA_IObject *gameobj)
virtual ~SCA_XORController ()
virtual CValue * GetReplica ()
virtual void Trigger (SCA_LogicManager *logicmgr)
Detailed Description
Definition at line 37 of file SCA_XORController.h.
Constructor & Destructor Documentation
SCA_XORController::SCA_XORController (SCA_IObject * gameobj)
Definition at line 45 of file SCA_XORController.cpp.
Referenced by GetReplica().
SCA_XORController::~SCA_XORController () [virtual]
Definition at line 53 of file SCA_XORController.cpp.
Member Function Documentation
CValue * SCA_XORController::GetReplica (void) [virtual]
Implements CValue.
Definition at line 89 of file SCA_XORController.cpp.
References CValue::ProcessReplica(), and SCA_XORController().
void SCA_XORController::Trigger (SCA_LogicManager * logicmgr) [virtual]
Implements SCA_IController.
Definition at line 59 of file SCA_XORController.cpp.
References SCA_LogicManager::AddActiveActuator(), SCA_ISensor::GetState(), i, SCA_IController::m_linkedactuators, and SCA_IController::m_linkedsensors.
The documentation for this class was generated from the following files:
SCA_XORController.h
SCA_XORController.cpp