Blender: sculpt_undo.c File Reference
sculpt_undo.c File Reference
sculpt and paint
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BLI_string.h"
#include "BLI_listbase.h"
#include "BLI_ghash.h"
#include "BLI_threads.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_mesh_types.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_modifier.h"
#include "BKE_multires.h"
#include "BKE_paint.h"
#include "BKE_key.h"
#include "BKE_mesh.h"
#include "BKE_subsurf.h"
#include "WM_api.h"
#include "WM_types.h"
#include "GPU_buffers.h"
#include "ED_sculpt.h"
#include "paint_intern.h"
#include "sculpt_intern.h"
Functions
static void update_cb (PBVHNode *node, void *rebuild)
static void sculpt_undo_restore_deformed (SculptSession *ss, SculptUndoNode *unode, int uindex, int oindex, float coord[3])
static int sculpt_undo_restore_coords (bContext *C, DerivedMesh *dm, SculptUndoNode *unode)
static int sculpt_undo_restore_hidden (bContext *C, DerivedMesh *dm, SculptUndoNode *unode)
static void sculpt_undo_restore (bContext *C, ListBase *lb)
static void sculpt_undo_free (ListBase *lb)
SculptUndoNode * sculpt_undo_get_node (PBVHNode *node)
static void sculpt_undo_alloc_and_store_hidden (PBVH *pbvh, SculptUndoNode *unode)
static SculptUndoNode * sculpt_undo_alloc_node (Object *ob, PBVHNode *node, SculptUndoType type)
static void sculpt_undo_store_coords (Object *ob, SculptUndoNode *unode)
static void sculpt_undo_store_hidden (Object *ob, SculptUndoNode *unode)
SculptUndoNode * sculpt_undo_push_node (Object *ob, PBVHNode *node, SculptUndoType type)
void sculpt_undo_push_begin (const char *name)
void sculpt_undo_push_end (void)
Detailed Description
Definition in file sculpt_undo.c.
Function Documentation
static void sculpt_undo_alloc_and_store_hidden (PBVH * pbvh, SculptUndoNode * unode) [static]
Definition at line 337 of file sculpt_undo.c.
References BLI_pbvh_grid_hidden(), BLI_pbvh_node_get_grids(), SculptUndoNode::grid_hidden, i, MEM_dupallocN(), MEM_mapallocN(), SculptUndoNode::node, NULL, and SculptUndoNode::totgrid.
Referenced by sculpt_undo_alloc_node().
static SculptUndoNode* sculpt_undo_alloc_node (Object * ob, PBVHNode * node, SculptUndoType type) [static]
Definition at line 360 of file sculpt_undo.c.
References BLI_addtail(), BLI_BITMAP_NEW, BLI_pbvh_node_get_grids(), BLI_pbvh_node_num_verts(), BLI_strncpy(), SculptUndoNode::co, SculptUndoNode::grids, SculptUndoNode::gridsize, Object::id, SculptUndoNode::idname, SculptUndoNode::index, SculptUndoNode::maxgrid, SculptUndoNode::maxvert, MEM_callocN(), MEM_mapallocN(), SculptSession::modifiers_active, ID::name, SculptUndoNode::no, SculptUndoNode::node, NULL, SculptUndoNode::orig_co, SculptSession::pbvh, Object::sculpt, sculpt_undo_alloc_and_store_hidden(), SCULPT_UNDO_COORDS, SCULPT_UNDO_HIDDEN, SculptUndoNode::totgrid, SculptSession::totvert, SculptUndoNode::totvert, SculptUndoNode::type, UNDO_PAINT_MESH, undo_paint_push_count_alloc(), undo_paint_push_get_list(), and SculptUndoNode::vert_hidden.
Referenced by sculpt_undo_push_node().
static void sculpt_undo_free (ListBase * lb) [static]
Definition at line 292 of file sculpt_undo.c.
References SculptUndoNode::co, ListBase::first, SculptUndoNode::grid_hidden, SculptUndoNode::grids, i, SculptUndoNode::index, SculptUndoNode::layer_disp, MEM_freeN(), SculptUndoNode::next, SculptUndoNode::no, SculptUndoNode::orig_co, SculptUndoNode::totgrid, and SculptUndoNode::vert_hidden.
Referenced by sculpt_undo_push_begin().
SculptUndoNode* sculpt_undo_get_node (PBVHNode * node)
Definition at line 322 of file sculpt_undo.c.
References ListBase::first, SculptUndoNode::next, SculptUndoNode::node, NULL, UNDO_PAINT_MESH, and undo_paint_push_get_list().
Referenced by sculpt_raycast_cb(), sculpt_restore_mesh(), and sculpt_undo_push_node().
void sculpt_undo_push_begin (const char * name)
Definition at line 505 of file sculpt_undo.c.
References sculpt_undo_free(), sculpt_undo_restore(), UNDO_PAINT_MESH, and undo_paint_push_begin().
Referenced by hide_show_exec(), and sculpt_stroke_test_start().
void sculpt_undo_push_end (void)
Definition at line 511 of file sculpt_undo.c.
References ListBase::first, SculptUndoNode::layer_disp, MEM_freeN(), SculptUndoNode::next, SculptUndoNode::no, NULL, UNDO_PAINT_MESH, undo_paint_push_end(), and undo_paint_push_get_list().
Referenced by hide_show_exec(), and sculpt_stroke_done().
SculptUndoNode* sculpt_undo_push_node (Object * ob, PBVHNode * node, SculptUndoType type)
Definition at line 456 of file sculpt_undo.c.
References BLI_lock_thread(), BLI_pbvh_node_get_grids(), BLI_pbvh_node_get_verts(), BLI_pbvh_node_num_verts(), BLI_strncpy(), BLI_unlock_thread(), SculptUndoNode::grids, SculptUndoNode::index, SculptSession::kb, LOCK_CUSTOM1, KeyBlock::name, NULL, SculptSession::pbvh, Object::sculpt, sculpt_undo_alloc_node(), SCULPT_UNDO_COORDS, sculpt_undo_get_node(), SCULPT_UNDO_HIDDEN, sculpt_undo_store_coords(), sculpt_undo_store_hidden(), SculptUndoNode::shapeName, SculptUndoNode::totgrid, and SculptUndoNode::totvert.
Referenced by calc_area_normal(), calc_area_normal_and_flatten_center(), calc_flatten_center(), do_brush_action(), do_grab_brush(), do_layer_brush(), do_rotate_brush(), do_thumb_brush(), partialvis_update_grids(), partialvis_update_mesh(), and sculpt_combine_proxies().
static void sculpt_undo_restore (bContext * C, ListBase * lb) [static]
Definition at line 214 of file sculpt_undo.c.
References BLI_pbvh_search_callback(), BLI_pbvh_update(), CTX_data_active_object(), CTX_data_scene(), CTX_data_tool_settings(), DAG_id_tag_update(), Object::data, Object::derivedFinal, ListBase::first, free_sculptsession_deformMats(), DerivedMesh::getGridData, DerivedMesh::getGridSize, DerivedMesh::getNumGrids, GPU_drawobject_free(), SculptUndoNode::gridsize, Object::id, SculptUndoNode::idname, SculptUndoNode::maxgrid, SculptUndoNode::maxvert, mesh_calc_normals_tessface(), mesh_get_derived_final(), Mesh::mface, SculptSession::modifiers_active, MULTIRES_COORDS_MODIFIED, MULTIRES_HIDDEN_MODIFIED, multires_mark_as_modified(), Mesh::mvert, ID::name, SculptUndoNode::next, NULL, OB_RECALC_DATA, SculptSession::pbvh, PBVH_UpdateBB, PBVH_UpdateOriginalBB, PBVH_UpdateRedraw, Object::sculpt, ToolSettings::sculpt, sculpt_multires_active(), SCULPT_UNDO_COORDS, SCULPT_UNDO_HIDDEN, sculpt_undo_restore_coords(), sculpt_undo_restore_hidden(), sculpt_update_mesh_elements(), Mesh::totface, Mesh::totvert, SculptSession::totvert, SculptUndoNode::type, update(), and update_cb().
Referenced by sculpt_undo_push_begin().
static int sculpt_undo_restore_coords (bContext * C, DerivedMesh * dm, SculptUndoNode * unode) [static]
Definition at line 90 of file sculpt_undo.c.
References BLI_findindex(), BLI_pbvh_apply_vertCos(), Key::block, co, SculptUndoNode::co, CTX_data_active_object(), CTX_data_scene(), CTX_data_tool_settings(), MVert::flag, DerivedMesh::getGridData, DerivedMesh::getGridSize, SculptUndoNode::grids, SculptUndoNode::gridsize, i, SculptUndoNode::index, SculptSession::kb, key_get_named_keyblock(), key_to_vertcos(), SculptUndoNode::maxgrid, SculptUndoNode::maxvert, ME_VERT_PBVH_UPDATE, MEM_freeN(), SculptSession::modifiers_active, SculptSession::mvert, KeyBlock::name, NC_OBJECT, ND_DATA, ob_get_key(), SculptUndoNode::orig_co, SculptSession::pbvh, Object::sculpt, ToolSettings::sculpt, sculpt_undo_restore_deformed(), sculpt_update_mesh_elements(), sculpt_vertcos_to_key(), SculptUndoNode::shapeName, Object::shapenr, swap_v3_v3(), SculptUndoNode::totgrid, SculptUndoNode::totvert, and WM_event_add_notifier().
Referenced by sculpt_undo_restore().
static void sculpt_undo_restore_deformed (SculptSession * ss, SculptUndoNode * unode, int uindex, int oindex, float coord[3]) [static]
Definition at line 79 of file sculpt_undo.c.
References SculptUndoNode::co, copy_v3_v3(), SculptSession::deform_cos, SculptUndoNode::orig_co, and swap_v3_v3().
Referenced by sculpt_undo_restore_coords().
static int sculpt_undo_restore_hidden (bContext * C, DerivedMesh * dm, SculptUndoNode * unode) [static]
Definition at line 176 of file sculpt_undo.c.
References BLI_BITMAP_GET, BLI_BITMAP_MODIFY, CTX_data_active_object(), MVert::flag, DerivedMesh::getGridData, DerivedMesh::getGridHidden, SculptUndoNode::grid_hidden, SculptUndoNode::grids, i, SculptUndoNode::index, SculptUndoNode::maxgrid, SculptUndoNode::maxvert, ME_HIDE, ME_VERT_PBVH_UPDATE, SculptSession::mvert, Object::sculpt, SWAP, SculptUndoNode::totgrid, SculptUndoNode::totvert, and SculptUndoNode::vert_hidden.
Referenced by sculpt_undo_restore().
static void sculpt_undo_store_coords (Object * ob, SculptUndoNode * unode) [static]
Definition at line 418 of file sculpt_undo.c.
References BLI_pbvh_vertex_iter_begin, BLI_pbvh_vertex_iter_end, PBVHVertexIter::co, SculptUndoNode::co, copy_v3_v3(), copy_v3_v3_short(), PBVHVertexIter::fno, PBVHVertexIter::i, SculptUndoNode::index, SculptSession::modifiers_active, SculptUndoNode::no, PBVHVertexIter::no, SculptUndoNode::node, normal_float_to_short_v3(), SculptUndoNode::orig_co, SculptSession::orig_cos, SculptSession::pbvh, PBVH_ITER_ALL, and Object::sculpt.
Referenced by sculpt_undo_push_node().
static void sculpt_undo_store_hidden (Object * ob, SculptUndoNode * unode) [static]
Definition at line 434 of file sculpt_undo.c.
References BLI_BITMAP_MODIFY, BLI_pbvh_node_get_verts(), BLI_pbvh_node_num_verts(), MVert::flag, SculptUndoNode::grids, i, ME_HIDE, SculptUndoNode::node, NULL, SculptSession::pbvh, Object::sculpt, and SculptUndoNode::vert_hidden.
Referenced by sculpt_undo_push_node().
static void update_cb (PBVHNode * node, void * rebuild) [static]
Definition at line 71 of file sculpt_undo.c.
References BLI_pbvh_node_fully_hidden_set(), BLI_pbvh_node_mark_rebuild_draw(), and BLI_pbvh_node_mark_update().
Referenced by BKE_bake_ocean(), BLI_dlrbTree_add(), BPy_BoolProperty(), BPy_BoolVectorProperty(), BPy_EnumProperty(), BPy_FloatProperty(), BPy_FloatVectorProperty(), BPy_IntProperty(), BPy_IntVectorProperty(), BPy_PointerProperty(), bpy_prop_callback_assign(), BPy_StringProperty(), and sculpt_undo_restore().