Blender: btHinge2Constraint Class Reference
btHinge2Constraint Class Reference
#include <btHinge2Constraint.h>
Public Member Functions
btHinge2Constraint (btRigidBody &rbA, btRigidBody &rbB, btVector3 &anchor, btVector3 &axis1, btVector3 &axis2)
const btVector3 & getAnchor ()
const btVector3 & getAnchor2 ()
const btVector3 & getAxis1 ()
const btVector3 & getAxis2 ()
btScalar getAngle1 ()
btScalar getAngle2 ()
void setUpperLimit (btScalar ang1max)
void setLowerLimit (btScalar ang1min)
Protected Attributes
btVector3 m_anchor
btVector3 m_axis1
btVector3 m_axis2
Detailed Description
Definition at line 32 of file btHinge2Constraint.h.
Constructor & Destructor Documentation
btHinge2Constraint::btHinge2Constraint (btRigidBody & rbA, btRigidBody & rbB, btVector3 & anchor, btVector3 & axis1, btVector3 & axis2)
Definition at line 27 of file btHinge2Constraint.cpp.
References btGeneric6DofSpringConstraint::enableSpring(), btTransform::getBasis(), btRigidBody::getCenterOfMassTransform(), btTransform::inverse(), btGeneric6DofConstraint::m_frameInA, btGeneric6DofConstraint::m_frameInB, btGeneric6DofConstraint::setAngularLowerLimit(), btGeneric6DofConstraint::setAngularUpperLimit(), btGeneric6DofSpringConstraint::setDamping(), btGeneric6DofSpringConstraint::setEquilibriumPoint(), btTransform::setIdentity(), btGeneric6DofConstraint::setLinearLowerLimit(), btGeneric6DofConstraint::setLinearUpperLimit(), btTransform::setOrigin(), btGeneric6DofSpringConstraint::setStiffness(), btMatrix3x3::setValue(), SIMD_HALF_PI, and SIMD_PI.
Member Function Documentation
const btVector3& btHinge2Constraint::getAnchor () [inline]
Definition at line 44 of file btHinge2Constraint.h.
References btTransform::getOrigin(), and btGeneric6DofConstraint::m_calculatedTransformA.
const btVector3& btHinge2Constraint::getAnchor2 () [inline]
Definition at line 45 of file btHinge2Constraint.h.
References btTransform::getOrigin(), and btGeneric6DofConstraint::m_calculatedTransformB.
btScalar btHinge2Constraint::getAngle1 () [inline]
Definition at line 48 of file btHinge2Constraint.h.
References btGeneric6DofConstraint::getAngle().
btScalar btHinge2Constraint::getAngle2 () [inline]
Definition at line 49 of file btHinge2Constraint.h.
References btGeneric6DofConstraint::getAngle().
const btVector3& btHinge2Constraint::getAxis1 () [inline]
Definition at line 46 of file btHinge2Constraint.h.
References m_axis1.
const btVector3& btHinge2Constraint::getAxis2 () [inline]
Definition at line 47 of file btHinge2Constraint.h.
References m_axis2.
void btHinge2Constraint::setLowerLimit (btScalar ang1min) [inline]
Definition at line 52 of file btHinge2Constraint.h.
References btGeneric6DofConstraint::setAngularLowerLimit().
void btHinge2Constraint::setUpperLimit (btScalar ang1max) [inline]
Definition at line 51 of file btHinge2Constraint.h.
References btGeneric6DofConstraint::setAngularUpperLimit().
Member Data Documentation
btVector3 btHinge2Constraint::m_anchor [protected]
Definition at line 35 of file btHinge2Constraint.h.
btVector3 btHinge2Constraint::m_axis1 [protected]
Definition at line 36 of file btHinge2Constraint.h.
Referenced by getAxis1().
btVector3 btHinge2Constraint::m_axis2 [protected]
Definition at line 37 of file btHinge2Constraint.h.
Referenced by getAxis2().
The documentation for this class was generated from the following files:
btHinge2Constraint.h
btHinge2Constraint.cpp