Blender: node_shader_camera.c File Reference
node_shader_camera.c File Reference
shdnodes
#include "node_shader_util.h"
Functions
static void node_shader_exec_camera (void *data, bNode *UNUSED(node), bNodeStack **UNUSED(in), bNodeStack **out)
static int gpu_shader_camera (GPUMaterial *mat, bNode *UNUSED(node), GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_camera (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_camera_out []
Detailed Description
Definition in file node_shader_camera.c.
Function Documentation
static int gpu_shader_camera (GPUMaterial * mat, bNode * UNUSEDnode, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 55 of file node_shader_camera.c.
References GPU_builtin(), GPU_stack_link(), and GPU_VIEW_POSITION.
Referenced by register_node_type_sh_camera().
static void node_shader_exec_camera (void * data, bNode * UNUSEDnode, bNodeStack ** UNUSEDin, bNodeStack ** out) [static]
Definition at line 44 of file node_shader_camera.c.
References ShadeInput::co, copy_v3_v3(), fabs(), normalize_v3(), and bNodeStack::vec.
Referenced by register_node_type_sh_camera().
void register_node_type_sh_camera (bNodeTreeType * ttype)
Definition at line 60 of file node_shader_camera.c.
References gpu_shader_camera(), NODE_CLASS_INPUT, NODE_NEW_SHADING, NODE_OLD_SHADING, node_shader_exec_camera(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_CAMERA.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_camera_out[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 0, "View Vector"},
    {   SOCK_FLOAT, 0, "View Z Depth"},
    {   SOCK_FLOAT, 0, "View Distance"},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_shader_camera.c.