Blender: node_composite_displace.c File Reference
node_composite_displace.c File Reference
cmpnodes
#include "node_composite_util.h"
Defines
#define DISPLACE_EPSILON 0.01f
Functions
static void do_displace (bNode *node, CompBuf *stackbuf, CompBuf *cbuf, CompBuf *vecbuf, float *UNUSED(veccol), CompBuf *xbuf, CompBuf *ybuf, float *xscale, float *yscale)
static void node_composit_exec_displace (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_displace (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_displace_in []
static bNodeSocketTemplate cmp_node_displace_out []
Detailed Description
Definition in file node_composite_displace.c.
Define Documentation
#define DISPLACE_EPSILON 0.01f
Definition at line 52 of file node_composite_displace.c.
Referenced by do_displace().
Function Documentation
static void do_displace (bNode * node, CompBuf * stackbuf, CompBuf * cbuf, CompBuf * vecbuf, float * UNUSEDveccol, CompBuf * xbuf, CompBuf * ybuf, float * xscale, float * yscale) [static]
Definition at line 54 of file node_composite_displace.c.
References CLAMP(), DISPLACE_EPSILON, bNode::exec, fabsf, ibuf_sample(), IMB_allocImBuf(), IMB_freeImBuf(), maxf(), NODE_BREAK, qd_getPixel(), qd_setPixel(), CompBuf::rect, ImBuf::rect_float, signf(), CompBuf::x, CompBuf::xof, CompBuf::y, and CompBuf::yof.
Referenced by node_composit_exec_displace().
static void node_composit_exec_displace (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 154 of file node_composite_displace.c.
References alloc_compbuf(), CB_RGBA, CB_VAL, CB_VEC3, bNodeStack::data, data, do_displace(), free_compbuf(), typecheck_compbuf(), CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_displace().
void register_node_type_cmp_displace (bNodeTreeType * ttype)
Definition at line 185 of file node_composite_displace.c.
References CMP_NODE_DISPLACE, NODE_CLASS_DISTORT, node_composit_exec_displace(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_displace_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   SOCK_VECTOR, 1, "Vector",           1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_TRANSLATION},
    {   SOCK_FLOAT, 1, "X Scale",               0.0f, 0.0f, 0.0f, 0.0f, -1000.0f, 1000.0f, PROP_FACTOR},
    {   SOCK_FLOAT, 1, "Y Scale",               0.0f, 0.0f, 0.0f, 0.0f, -1000.0f, 1000.0f, PROP_FACTOR},
    {   -1, 0, ""   }
}
Definition at line 38 of file node_composite_displace.c.
bNodeSocketTemplate cmp_node_displace_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 45 of file node_composite_displace.c.