Blender: node_composite_vecBlur.c File Reference
node_composite_vecBlur.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void node_composit_exec_vecblur (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_vecblur (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_vecblur (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_vecblur_in []
static bNodeSocketTemplate cmp_node_vecblur_out []
Detailed Description
Definition in file node_composite_vecBlur.c.
Function Documentation
static void node_composit_exec_vecblur (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 50 of file node_composite_vecBlur.c.
References CB_RGBA, CB_VAL, CB_VEC4, data, bNodeStack::data, dupalloc_compbuf(), free_compbuf(), NULL, RE_zbuf_accumulate_vecblur(), CompBuf::rect, bNode::storage, typecheck_compbuf(), CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_vecblur().
static void node_composit_init_vecblur (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 88 of file node_composite_vecBlur.c.
References NodeBlurData::fac, MEM_callocN(), NodeBlurData::samples, and bNode::storage.
Referenced by register_node_type_cmp_vecblur().
void register_node_type_cmp_vecblur (bNodeTreeType * ttype)
Definition at line 97 of file node_composite_vecBlur.c.
References CMP_NODE_VECBLUR, NODE_CLASS_OP_FILTER, node_composit_exec_vecblur(), node_composit_init_vecblur(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_vecblur_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   SOCK_FLOAT, 1, "Z",         0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_NONE},
    {   SOCK_VECTOR, 1, "Speed",            0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_VELOCITY},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_composite_vecBlur.c.
bNodeSocketTemplate cmp_node_vecblur_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 43 of file node_composite_vecBlur.c.