Blender: py_capi_utils.c File Reference
py_capi_utils.c File Reference
Python Generic
#include <Python.h>
#include <frameobject.h>
#include "py_capi_utils.h"
#include "BLI_string_utf8.h"
#include "BLI_dynstr.h"
#include "MEM_guardedalloc.h"
Functions
int PyC_AsArray (void *array, PyObject *value, const Py_ssize_t length, const PyTypeObject *type, const short is_double, const char *error_prefix)
void PyC_ObSpit (const char *name, PyObject *var)
void PyC_LineSpit (void)
void PyC_FileAndNum (const char **filename, int *lineno)
void PyC_FileAndNum_Safe (const char **filename, int *lineno)
PyObject * PyC_Object_GetAttrStringArgs (PyObject *o, Py_ssize_t n,...)
PyObject * PyC_Err_Format_Prefix (PyObject *exception_type_prefix, const char *format,...)
PyObject * PyC_ExceptionBuffer (void)
const char * PyC_UnicodeAsByte (PyObject *py_str, PyObject **coerce)
PyObject * PyC_UnicodeFromByteAndSize (const char *str, Py_ssize_t size)
PyObject * PyC_UnicodeFromByte (const char *str)
PyObject * PyC_DefaultNameSpace (const char *filename)
void PyC_MainModule_Backup (PyObject **main_mod)
void PyC_MainModule_Restore (PyObject *main_mod)
void PyC_SetHomePath (const char *py_path_bundle)
void PyC_RunQuicky (const char *filepath, int n,...)
void * PyC_RNA_AsPointer (PyObject *value, const char *type_name)
char * PyC_FlagSet_AsString (PyC_FlagSet *item)
int PyC_FlagSet_ValueFromID_int (PyC_FlagSet *item, const char *identifier, int *value)
int PyC_FlagSet_ValueFromID (PyC_FlagSet *item, const char *identifier, int *value, const char *error_prefix)
int PyC_FlagSet_ToBitfield (PyC_FlagSet *items, PyObject *value, int *r_value, const char *error_prefix)
PyObject * PyC_FlagSet_FromBitfield (PyC_FlagSet *items, int flag)
Detailed Description
Extend upon CPython's API, filling in some gaps, these functions use PyC_ prefix to distinguish them apart from CPython.
Note:
This module should only depend on CPython, however it currently uses BLI_string_utf8() for unicode conversion.
Definition in file py_capi_utils.c.
Function Documentation
int PyC_AsArray (void * array, PyObject * value, const Py_ssize_t length, const PyTypeObject * type, const short is_double, const char * error_prefix)
Definition at line 46 of file py_capi_utils.c.
References i, and length().
Referenced by BPy_BoolVectorProperty(), BPy_FloatVectorProperty(), BPy_IDArray_ass_slice(), and BPy_IntVectorProperty().
PyObject* PyC_DefaultNameSpace (const char * filename)
Definition at line 433 of file py_capi_utils.c.
References interp().
Referenced by BPY_button_exec(), BPY_string_exec(), PyC_RunQuicky(), and python_script_exec().
PyObject* PyC_Err_Format_Prefix (PyObject * exception_type_prefix, const char * format, ...)
Definition at line 235 of file py_capi_utils.c.
References NULL.
Referenced by bpy_class_call(), and pyrna_py_to_prop().
PyObject* PyC_ExceptionBuffer (void)
Definition at line 300 of file py_capi_utils.c.
References NULL.
Referenced by BPy_errors_to_report(), pointer_type_from_py(), and pyrna_py_to_prop().
void PyC_FileAndNum (const char ** filename, int * lineno)
Definition at line 155 of file py_capi_utils.c.
References mod(), and NULL.
Referenced by BPy_errors_to_report(), PyC_FileAndNum_Safe(), PyC_LineSpit(), and pyrna_func_call().
void PyC_FileAndNum_Safe (const char ** filename, int * lineno)
Definition at line 194 of file py_capi_utils.c.
References PyC_FileAndNum(), and PYC_INTERPRETER_ACTIVE.
char* PyC_FlagSet_AsString (PyC_FlagSet * item)
Definition at line 693 of file py_capi_utils.c.
References BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), and PyC_FlagSet::identifier.
Referenced by PyC_FlagSet_ValueFromID().
PyObject* PyC_FlagSet_FromBitfield (PyC_FlagSet * items, int flag)
Definition at line 768 of file py_capi_utils.c.
References PyC_FlagSet::identifier, NULL, and PyC_FlagSet::value.
Referenced by bpy_bmesh_select_mode_get().
int PyC_FlagSet_ToBitfield (PyC_FlagSet * items, PyObject * value, int * r_value, const char * error_prefix)
Definition at line 735 of file py_capi_utils.c.
References hash, NULL, and PyC_FlagSet_ValueFromID().
Referenced by bpy_bmesh_select_mode_set(), and bpy_bmesh_transform().
int PyC_FlagSet_ValueFromID (PyC_FlagSet * item, const char * identifier, int * value, const char * error_prefix)
Definition at line 720 of file py_capi_utils.c.
References MEM_freeN(), PyC_FlagSet_AsString(), and PyC_FlagSet_ValueFromID_int().
Referenced by PyC_FlagSet_ToBitfield().
int PyC_FlagSet_ValueFromID_int (PyC_FlagSet * item, const char * identifier, int * value)
Definition at line 708 of file py_capi_utils.c.
References PyC_FlagSet::identifier, and PyC_FlagSet::value.
Referenced by PyC_FlagSet_ValueFromID().
void PyC_LineSpit (void)
Definition at line 137 of file py_capi_utils.c.
References PyC_FileAndNum(), and PYC_INTERPRETER_ACTIVE.
Referenced by _RNA_warning().
void PyC_MainModule_Backup (PyObject ** main_mod)
Definition at line 450 of file py_capi_utils.c.
References interp().
Referenced by BPY_button_exec(), BPY_string_exec(), and python_script_exec().
void PyC_MainModule_Restore (PyObject * main_mod)
Definition at line 457 of file py_capi_utils.c.
References interp().
Referenced by BPY_string_exec(), and python_script_exec().
PyObject* PyC_Object_GetAttrStringArgs (PyObject * o, Py_ssize_t n, ...)
Definition at line 204 of file py_capi_utils.c.
References i.
void PyC_ObSpit (const char * name, PyObject * var)
Definition at line 117 of file py_capi_utils.c.
References NULL.
Referenced by bpy_class_free(), deferred_register_prop(), PyC_RunQuicky(), pyrna_srna_ExternalType(), and pyrna_subtype_set_rna().
void* PyC_RNA_AsPointer (PyObject * value, const char * type_name)
Definition at line 653 of file py_capi_utils.c.
References NULL.
Referenced by bpy_bm_from_edit_mesh(), bpy_bmesh_from_mesh(), bpy_bmesh_from_object(), bpy_bmesh_to_mesh(), and GPU_export_shader().
void PyC_RunQuicky (const char * filepath, int n, ...)
Definition at line 509 of file py_capi_utils.c.
References i, NULL, PyC_DefaultNameSpace(), and PyC_ObSpit().
void PyC_SetHomePath (const char * py_path_bundle)
Definition at line 465 of file py_capi_utils.c.
References BLI_setenv(), BLI_strncpy_wchar_from_utf8(), and NULL.
Referenced by BPY_python_start().
const char* PyC_UnicodeAsByte (PyObject * py_str, PyObject ** coerce)
Definition at line 373 of file py_capi_utils.c.
References NULL.
Referenced by BPy_IDProperty_Map_ValidateAndCreate(), and pyrna_py_to_prop().
PyObject* PyC_UnicodeFromByte (const char * str)
Definition at line 416 of file py_capi_utils.c.
References PyC_UnicodeFromByteAndSize(), and strlen().
Referenced by bpy_app_tempdir_get(), BPY_python_start(), and pyrna_param_to_py().
PyObject* PyC_UnicodeFromByteAndSize (const char * str, Py_ssize_t size)
Definition at line 400 of file py_capi_utils.c.
Referenced by idprop_py_from_idp_string(), PyC_UnicodeFromByte(), and pyrna_prop_to_py().