Blender: anim_ipo_utils.c File Reference
anim_ipo_utils.c File Reference
animation
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "DNA_anim_types.h"
#include "RNA_access.h"
#include "ED_anim_api.h"
Defines
#define HSV_BANDWIDTH 0.3f
Functions
int getname_anim_fcurve (char *name, ID *id, FCurve *fcu)
void getcolor_fcurve_rainbow (int cur, int tot, float *out)
Detailed Description
Definition in file anim_ipo_utils.c.
Define Documentation
#define HSV_BANDWIDTH 0.3f
Definition at line 190 of file anim_ipo_utils.c.
Referenced by getcolor_fcurve_rainbow().
Function Documentation
void getcolor_fcurve_rainbow (int cur, int tot, float * out)
Definition at line 194 of file anim_ipo_utils.c.
References HSV_BANDWIDTH, and hsv_to_rgb().
Referenced by graph_refresh().
int getname_anim_fcurve (char * name, ID * id, FCurve * fcu)
Definition at line 57 of file anim_ipo_utils.c.
References FCurve::array_index, BLI_getQuotedStr(), BLI_snprintf(), BLI_sprintfN(), PointerRNA::data, ELEM3, FCURVE_DISABLED, FCurve::flag, PointerRNA::id, MEM_freeN(), NULL, RNA_id_pointer_create(), FCurve::rna_path, RNA_path_resolve(), RNA_property_array_item_char(), RNA_property_array_length(), RNA_property_string_get_alloc(), RNA_property_ui_name(), RNA_struct_name_property(), RNA_struct_ui_icon(), RNA_struct_ui_name(), and PointerRNA::type.
Referenced by acf_fcurve_name(), and graph_panel_properties().