Blender: uvedit_buttons.c File Reference
uvedit_buttons.c File Reference
#include <string.h>
#include <stdio.h>
#include "MEM_guardedalloc.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_customdata.h"
#include "BKE_mesh.h"
#include "BKE_screen.h"
#include "BKE_tessmesh.h"
#include "ED_image.h"
#include "ED_uvedit.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "WM_api.h"
#include "WM_types.h"
Defines
#define B_UVEDIT_VERTEX 3
Functions
static int uvedit_center (Scene *scene, BMEditMesh *em, Image *ima, float center[2])
static void uvedit_translate (Scene *scene, BMEditMesh *em, Image *UNUSED(ima), float delta[2])
static void uvedit_vertex_buttons (const bContext *C, uiBlock *block)
static void do_uvedit_vertex (bContext *C, void *UNUSED(arg), int event)
static int image_panel_uv_poll (const bContext *C, PanelType *UNUSED(pt))
static void image_panel_uv (const bContext *C, Panel *pa)
void ED_uvedit_buttons_register (ARegionType *art)
Variables
static float uvedit_old_center [2]
Detailed Description
Definition in file uvedit_buttons.c.
Define Documentation
#define B_UVEDIT_VERTEX 3
Definition at line 61 of file uvedit_buttons.c.
Referenced by do_uvedit_vertex(), and uvedit_vertex_buttons().
Function Documentation
static void do_uvedit_vertex (bContext * C, void * UNUSEDarg, int event) [static]
Definition at line 156 of file uvedit_buttons.c.
References B_UVEDIT_VERTEX, BMEdit_FromObject(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_space_image(), ED_space_image_size(), SpaceImage::flag, SpaceImage::image, NC_IMAGE, SI_COORDFLOATS, uvedit_center(), uvedit_translate(), and WM_event_add_notifier().
Referenced by image_panel_uv().
void ED_uvedit_buttons_register (ARegionType * art)
Definition at line 206 of file uvedit_buttons.c.
References BLI_addtail(), PanelType::draw, PanelType::idname, image_panel_uv(), image_panel_uv_poll(), PanelType::label, MEM_callocN(), ARegionType::paneltypes, and PanelType::poll.
Referenced by ED_spacetype_image().
static void image_panel_uv (const bContext * C, Panel * pa) [static]
Definition at line 196 of file uvedit_buttons.c.
References do_uvedit_vertex(), Panel::layout, NULL, uiBlockSetHandleFunc(), uiLayoutAbsoluteBlock(), and uvedit_vertex_buttons().
Referenced by ED_uvedit_buttons_register().
static int image_panel_uv_poll (const bContext * C, PanelType * UNUSEDpt) [static]
Definition at line 190 of file uvedit_buttons.c.
References CTX_data_edit_object(), and ED_uvedit_test().
Referenced by ED_uvedit_buttons_register().
static int uvedit_center (Scene * scene, BMEditMesh * em, Image * ima, float center[2]) [static]
Definition at line 65 of file uvedit_buttons.c.
References add_v2_v2(), BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, BMLoop::head, BMFace::head, BMesh::ldata, BMesh::pdata, MLoopUV::uv, uvedit_face_visible_test(), uvedit_uv_select_test(), and zero_v2().
Referenced by do_uvedit_vertex(), and uvedit_vertex_buttons().
static void uvedit_translate (Scene * scene, BMEditMesh * em, Image * UNUSEDima, float delta[2]) [static]
Definition at line 97 of file uvedit_buttons.c.
References add_v2_v2(), BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::head, BMesh::ldata, MLoopUV::uv, and uvedit_uv_select_test().
Referenced by do_uvedit_vertex().
static void uvedit_vertex_buttons (const bContext * C, uiBlock * block) [static]
Definition at line 118 of file uvedit_buttons.c.
References B_UVEDIT_VERTEX, BMEdit_FromObject(), copy_v2_v2(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_space_image(), ED_space_image_size(), SpaceImage::flag, SpaceImage::image, NUM, SI_COORDFLOATS, step(), uiBlockBeginAlign(), uiBlockEndAlign(), uiDefButF(), and uvedit_center().
Referenced by image_panel_uv().
Variable Documentation
float uvedit_old_center[2] [static]
Definition at line 116 of file uvedit_buttons.c.