Blender: LbmControlData Class Reference
LbmControlData Class Reference
#include <solver_control.h>
Public Member Functions
LbmControlData ()
virtual ~LbmControlData ()
void parseControldataAttrList (AttributeList *attr)
Public Attributes
LbmFloat mSetForceStrength
std::vector< LbmControlSet * > mCons
int mCpUpdateInterval
string mCpOutfile
std::vector< std::vector
< ControlForces > > mCpForces
std::vector< ControlForces > mCpKernel
std::vector< ControlForces > mMdKernel
LbmFloat mDiffVelCon
LbmFloat mDebugCpscale
LbmFloat mDebugVelScale
LbmFloat mDebugCompavScale
LbmFloat mDebugAttScale
LbmFloat mDebugMaxdScale
LbmFloat mDebugAvgVelScale
Detailed Description
Definition at line 155 of file solver_control.h.
Constructor & Destructor Documentation
LbmControlData::LbmControlData ()
Definition at line 53 of file solver_control.cpp.
LbmControlData::~LbmControlData () [virtual]
Definition at line 69 of file solver_control.cpp.
References mCons.
Member Function Documentation
void LbmControlData::parseControldataAttrList (AttributeList * attr)
Definition at line 77 of file solver_control.cpp.
References debMsgStd, DM_NOTIFY, errMsg, AnimChannel< Scalar >::get(), ControlParticles::getCPSMvmWeightFac(), ControlParticles::getCPSTimeEnd(), ControlParticles::getCPSTimeStart(), ControlParticles::getCPSTimestep(), ControlParticles::getCPSWith(), ControlParticles::getInitMirror(), LbmControlSet::initCparts(), LbmControlSet::mcCpOffset, LbmControlSet::mcCpScale, LbmControlSet::mcForceAtt, LbmControlSet::mcForceMaxd, LbmControlSet::mcForceVel, mCons, LbmControlSet::mContrPartFile, LbmControlSet::mCparts, LbmControlSet::mCpmotion, LbmControlSet::mCpmotionFile, mCpOutfile, mCpUpdateInterval, LbmControlSet::mcRadiusAtt, LbmControlSet::mcRadiusMaxd, LbmControlSet::mcRadiusMind, LbmControlSet::mcRadiusVel, mDebugAttScale, mDebugAvgVelScale, mDebugCompavScale, mDebugCpscale, mDebugMaxdScale, mDebugVelScale, mDiffVelCon, mSetForceStrength, AttributeList::readChannelSinglePrecFloat(), AttributeList::readChannelVec3f(), AttributeList::readFloat(), AttributeList::readInt(), AttributeList::readString(), AttributeList::readVec3d(), ControlParticles::setCPSMvmWeightFac(), ControlParticles::setCPSTimeEnd(), ControlParticles::setCPSTimeStart(), ControlParticles::setCPSTimestep(), ControlParticles::setCPSWith(), ControlParticles::setDebugInit(), ControlParticles::setInfluenceAttraction(), ControlParticles::setInfluenceMaxdist(), ControlParticles::setInfluenceTangential(), ControlParticles::setInfluenceVelocity(), ControlParticles::setInitMirror(), ControlParticles::setInitTimeScale(), ControlParticles::setOffset(), ControlParticles::setRadiusAtt(), ControlParticles::setRadiusMaxd(), ControlParticles::setRadiusMinMaxd(), ControlParticles::setRadiusVel(), ControlParticles::setScale(), vec2L(), and vec2P().
Referenced by LbmFsgrSolver::parseAttrList().
Member Data Documentation
std::vector<LbmControlSet*> LbmControlData::mCons
Definition at line 169 of file solver_control.h.
Referenced by LbmFsgrSolver::cpDebugDisplay(), LbmFsgrSolver::handleCpdata(), LbmFsgrSolver::initCpdata(), parseControldataAttrList(), and ~LbmControlData().
std::vector< std::vector<ControlForces> > LbmControlData::mCpForces
Definition at line 175 of file solver_control.h.
Referenced by LbmFsgrSolver::handleCpdata(), and LbmFsgrSolver::initCpdata().
std::vector<ControlForces> LbmControlData::mCpKernel
Definition at line 176 of file solver_control.h.
Referenced by LbmFsgrSolver::handleCpdata().
string LbmControlData::mCpOutfile
Definition at line 173 of file solver_control.h.
Referenced by LbmFsgrSolver::initCpdata(), and parseControldataAttrList().
int LbmControlData::mCpUpdateInterval
Definition at line 171 of file solver_control.h.
Referenced by LbmFsgrSolver::handleCpdata(), and parseControldataAttrList().
LbmFloat LbmControlData::mDebugAttScale
Definition at line 182 of file solver_control.h.
Referenced by LbmFsgrSolver::cpDebugDisplay(), and parseControldataAttrList().
LbmFloat LbmControlData::mDebugAvgVelScale
Definition at line 182 of file solver_control.h.
Referenced by LbmFsgrSolver::cpDebugDisplay(), and parseControldataAttrList().
LbmFloat LbmControlData::mDebugCompavScale
Definition at line 182 of file solver_control.h.
Referenced by LbmFsgrSolver::cpDebugDisplay(), and parseControldataAttrList().
LbmFloat LbmControlData::mDebugCpscale
Definition at line 182 of file solver_control.h.
Referenced by LbmFsgrSolver::cpDebugDisplay(), and parseControldataAttrList().
LbmFloat LbmControlData::mDebugMaxdScale
Definition at line 182 of file solver_control.h.
Referenced by LbmFsgrSolver::cpDebugDisplay(), and parseControldataAttrList().
LbmFloat LbmControlData::mDebugVelScale
Definition at line 182 of file solver_control.h.
Referenced by LbmFsgrSolver::cpDebugDisplay(), and parseControldataAttrList().
LbmFloat LbmControlData::mDiffVelCon
Definition at line 179 of file solver_control.h.
Referenced by parseControldataAttrList().
std::vector<ControlForces> LbmControlData::mMdKernel
Definition at line 177 of file solver_control.h.
Referenced by LbmFsgrSolver::handleCpdata().
LbmFloat LbmControlData::mSetForceStrength
Definition at line 167 of file solver_control.h.
Referenced by LbmFsgrSolver::initCpdata(), and parseControldataAttrList().
The documentation for this class was generated from the following files:
solver_control.h
solver_control.cpp