Blender: KX_IpoConvert.h File Reference
KX_IpoConvert.h File Reference
Converter
Functions
class SG_Controller * BL_CreateIPO (struct bAction *action, class KX_GameObject *gameobj, class KX_BlenderSceneConverter *converter)
void BL_ConvertIpos (struct Object *blenderobject, class KX_GameObject *gameobj, class KX_BlenderSceneConverter *converter)
class SG_Controller * BL_CreateLampIPO (struct bAction *action, class KX_GameObject *lightobj, class KX_BlenderSceneConverter *converter)
void BL_ConvertLampIpos (struct Lamp *blenderlight, class KX_GameObject *lightobj, class KX_BlenderSceneConverter *converter)
void BL_ConvertWorldIpos (struct World *blenderworld, class KX_BlenderSceneConverter *converter)
class SG_Controller * BL_CreateCameraIPO (struct bAction *action, class KX_GameObject *cameraobj, class KX_BlenderSceneConverter *converter)
void BL_ConvertCameraIpos (struct Camera *blendercamera, class KX_GameObject *cameraobj, class KX_BlenderSceneConverter *converter)
void BL_ConvertMaterialIpos (struct Object *blenderobject, class KX_GameObject *materialobj, class KX_BlenderSceneConverter *converter)
Detailed Description
Definition in file KX_IpoConvert.h.
Function Documentation
void BL_ConvertCameraIpos (struct Camera * blendercamera, class KX_GameObject * cameraobj, class KX_BlenderSceneConverter * converter)
Definition at line 289 of file KX_IpoConvert.cpp.
References AnimData::action, SG_IObject::AddSGController(), Camera::adt, BL_CreateCameraIPO(), KX_GameObject::GetSGNode(), and SG_Controller::SetObject().
void BL_ConvertIpos (struct Object * blenderobject, class KX_GameObject * gameobj, class KX_BlenderSceneConverter * converter)
Definition at line 185 of file KX_IpoConvert.cpp.
References AnimData::action, SG_IObject::AddSGController(), Object::adt, BL_CreateIPO(), KX_GameObject::GetSGNode(), and SG_Controller::SetObject().
void BL_ConvertLampIpos (struct Lamp * blenderlight, class KX_GameObject * lightobj, class KX_BlenderSceneConverter * converter)
Definition at line 237 of file KX_IpoConvert.cpp.
References AnimData::action, SG_IObject::AddSGController(), Lamp::adt, BL_CreateLampIPO(), KX_GameObject::GetSGNode(), and SG_Controller::SetObject().
void BL_ConvertMaterialIpos (struct Object * blenderobject, class KX_GameObject * materialobj, class KX_BlenderSceneConverter * converter)
Definition at line 458 of file KX_IpoConvert.cpp.
References ConvertMaterialIpos(), give_current_material(), STR_HashedString::hash(), Material::id, ID::name, and Object::totcol.
Referenced by bl_ConvertBlenderObject_Single().
void BL_ConvertWorldIpos (struct World * blenderworld, class KX_BlenderSceneConverter * converter)
Definition at line 300 of file KX_IpoConvert.cpp.
References AnimData::action, KX_WorldIpoController::AddInterpolator(), World::adt, GetAdtList(), BL_InterpolatorList::GetScalarInterpolator(), World::horb, World::horg, World::horr, i, interp(), KX_WorldIpoController::m_mist_dist, KX_WorldIpoController::m_mist_rgb, KX_WorldIpoController::m_mist_start, World::mistdist, World::miststa, KX_WorldIpoController::SetModifyMistColor(), KX_WorldIpoController::SetModifyMistDist(), and KX_WorldIpoController::SetModifyMistStart().
class SG_Controller* BL_CreateCameraIPO (struct bAction * action, class KX_GameObject * cameraobj, class KX_BlenderSceneConverter * converter)
Definition at line 250 of file KX_IpoConvert.cpp.
References KX_CameraIpoSGController::AddInterpolator(), Camera::clipend, Camera::clipsta, Object::data, GetAdtList(), KX_GameObject::GetBlenderObject(), BL_InterpolatorList::GetScalarInterpolator(), interp(), Camera::lens, KX_CameraIpoSGController::m_clipend, KX_CameraIpoSGController::m_clipstart, KX_CameraIpoSGController::m_lens, KX_CameraIpoSGController::SetModifyClipEnd(), KX_CameraIpoSGController::SetModifyClipStart(), and KX_CameraIpoSGController::SetModifyLens().
Referenced by BL_ConvertCameraIpos(), and BL_Action::Play().
class SG_Controller* BL_CreateIPO (struct bAction * action, class KX_GameObject * gameobj, class KX_BlenderSceneConverter * converter)
Definition at line 87 of file KX_IpoConvert.cpp.
References KX_ObColorIpoSGController::AddInterpolator(), KX_IpoSGController::AddInterpolator(), SG_IObject::AddSGController(), GetAdtList(), KX_GameObject::GetBlenderObject(), KX_IPOTransform::GetDeltaEulerAngles(), KX_IPOTransform::GetDeltaPosition(), KX_IPOTransform::GetDeltaScaling(), KX_IPOTransform::GetEulerAngles(), KX_IpoSGController::GetIPOTransform(), KX_IPOTransform::GetPosition(), BL_InterpolatorList::GetScalarInterpolator(), KX_IPOTransform::GetScaling(), KX_GameObject::GetSGNode(), i, interp(), Object::loc, KX_ObColorIpoSGController::m_rgba, NULL, OB_DLOC_X, OB_DROT_X, OB_DSIZE_X, OB_LOC_X, OB_ROT_X, OB_SIZE_X, Object::rot, ROT_MODE_AXISANGLE, ROT_MODE_QUAT, Object::rotmode, KX_IPOTransform::SetEulerAngles(), KX_IpoSGController::SetGameObject(), KX_IpoSGController::SetIPOChannelActive(), SG_Controller::SetObject(), KX_IPOTransform::SetPosition(), KX_IPOTransform::SetScaling(), and Object::size.
Referenced by BL_ConvertIpos(), and BL_Action::Play().
class SG_Controller* BL_CreateLampIPO (struct bAction * action, class KX_GameObject * lightobj, class KX_BlenderSceneConverter * converter)
Definition at line 194 of file KX_IpoConvert.cpp.
References KX_LightIpoSGController::AddInterpolator(), Lamp::b, Object::data, Lamp::dist, Lamp::energy, Lamp::g, GetAdtList(), KX_GameObject::GetBlenderObject(), BL_InterpolatorList::GetScalarInterpolator(), i, interp(), KX_LightIpoSGController::m_col_rgb, KX_LightIpoSGController::m_dist, KX_LightIpoSGController::m_energy, Lamp::r, KX_LightIpoSGController::SetModifyColor(), KX_LightIpoSGController::SetModifyDist(), and KX_LightIpoSGController::SetModifyEnergy().
Referenced by BL_ConvertLampIpos(), and BL_Action::Play().