Blender: node_composite_scale.c File Reference
node_composite_scale.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void node_composit_exec_scale (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_scale (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_scale_in []
static bNodeSocketTemplate cmp_node_scale_out []
Detailed Description
Definition in file node_composite_scale.c.
Function Documentation
static void node_composit_exec_scale (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 50 of file node_composite_scale.c.
References alloc_compbuf(), CB_RGBA, CMP_SCALE_ABSOLUTE, CMP_SCALE_MAX, CMP_SCALE_RELATIVE, CMP_SCALE_RENDERPERCENT, CMP_SCALE_SCENEPERCENT, copy_v4_v4(), bNode::custom1, bNodeStack::data, data, dupalloc_compbuf(), free_compbuf(), IB_rectfloat, IMB_allocImBuf(), IMB_freeImBuf(), IMB_scaleImBuf(), ImBuf::mall, CompBuf::malloc, MAX2, MIN2, NULL, pass_on_compbuf(), CompBuf::rect, ImBuf::rect_float, RenderData::size, typecheck_compbuf(), CompBuf::x, CompBuf::xof, RenderData::xsch, CompBuf::y, CompBuf::yof, and RenderData::ysch.
Referenced by register_node_type_cmp_scale().
void register_node_type_cmp_scale (bNodeTreeType * ttype)
Definition at line 133 of file node_composite_scale.c.
References CMP_NODE_SCALE, NODE_CLASS_DISTORT, node_composit_exec_scale(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_scale_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   SOCK_FLOAT, 1, "X",             1.0f, 0.0f, 0.0f, 0.0f, 0.0001f, CMP_SCALE_MAX, PROP_FACTOR},
    {   SOCK_FLOAT, 1, "Y",             1.0f, 0.0f, 0.0f, 0.0f, 0.0001f, CMP_SCALE_MAX, PROP_FACTOR},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_composite_scale.c.
bNodeSocketTemplate cmp_node_scale_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 43 of file node_composite_scale.c.