Blender: MT_Tuple3 Class Reference
MT_Tuple3 Class Reference
#include <MT_Tuple3.h>
Public Member Functions
MT_Tuple3 ()
MT_Tuple3 (const float *v)
MT_Tuple3 (const double *v)
MT_Tuple3 (MT_Scalar xx, MT_Scalar yy, MT_Scalar zz)
MT_Scalar & operator[] (int i)
const MT_Scalar & operator[] (int i) const
MT_Scalar & x ()
const MT_Scalar & x () const
MT_Scalar & y ()
const MT_Scalar & y () const
MT_Scalar & z ()
const MT_Scalar & z () const
MT_Scalar * getValue ()
const MT_Scalar * getValue () const
void getValue (float *v) const
void getValue (double *v) const
void setValue (const float *v)
void setValue (const double *v)
void setValue (MT_Scalar xx, MT_Scalar yy, MT_Scalar zz)
Protected Attributes
MT_Scalar m_co [3]
Detailed Description
Definition at line 53 of file MT_Tuple3.h.
Constructor & Destructor Documentation
MT_Tuple3::MT_Tuple3 () [inline]
Definition at line 55 of file MT_Tuple3.h.
MT_Tuple3::MT_Tuple3 (const float * v) [inline]
Definition at line 56 of file MT_Tuple3.h.
References setValue().
MT_Tuple3::MT_Tuple3 (const double * v) [inline]
Definition at line 57 of file MT_Tuple3.h.
References setValue().
MT_Tuple3::MT_Tuple3 (MT_Scalar xx, MT_Scalar yy, MT_Scalar zz) [inline]
Definition at line 58 of file MT_Tuple3.h.
References setValue().
Member Function Documentation
MT_Scalar* MT_Tuple3::getValue () [inline]
Definition at line 72 of file MT_Tuple3.h.
References m_co.
Referenced by BL_ConvertActuators(), BSP_CSGMesh_VertexIt_Fill(), LOD_Vertex::CopyPosition(), KX_NavMeshObject::FindPath(), getNavmeshNormal(), MT_Transform::getValue(), MyGlutMouseHandler::Motion(), RAS_TexVert::RAS_TexVert(), KX_NavMeshObject::Raycast(), LOD_ExternVColorEditor::RemoveVertexColors(), LOD_ExternNormalEditor::RemoveVertexNormals(), LOD_ExternVColorEditor::SetColor(), RAS_TexVert::SetNormal(), RAS_TexVert::SetTangent(), BL_Shader::SetUniform(), RAS_TexVert::SetXYZ(), KX_GameObject::UpdateBlenderObjectMatrix(), LOD_ExternNormalEditor::UpdateVertexNormals(), VertexIt_Fill(), and KX_BlenderSceneConverter::WritePhysicsObjectToAnimationIpo().
const MT_Scalar* MT_Tuple3::getValue () const [inline]
Definition at line 73 of file MT_Tuple3.h.
References m_co.
void MT_Tuple3::getValue (float * v) const [inline]
Definition at line 75 of file MT_Tuple3.h.
References m_co.
void MT_Tuple3::getValue (double * v) const [inline]
Definition at line 81 of file MT_Tuple3.h.
References m_co.
const MT_Scalar& MT_Tuple3::operator[] (int i) const [inline]
Definition at line 61 of file MT_Tuple3.h.
References i, and m_co.
MT_Scalar& MT_Tuple3::operator[] (int i) [inline]
Definition at line 60 of file MT_Tuple3.h.
References i, and m_co.
void MT_Tuple3::setValue (MT_Scalar xx, MT_Scalar yy, MT_Scalar zz) [inline]
Definition at line 99 of file MT_Tuple3.h.
References m_co.
void MT_Tuple3::setValue (const float * v) [inline]
Definition at line 87 of file MT_Tuple3.h.
References m_co.
Referenced by KX_GameObject::AlignAxisToVect(), BL_ConvertMesh(), BOP_intersect(), BOP_intersectPlane(), BOP_Vertex::BOP_Vertex(), KX_IPOTransform::ClearDeltaStuff(), KX_NavMeshObject::DrawNavMesh(), KX_NavMeshObject::DrawPath(), KX_PositionInterpolator::Execute(), KX_ScalingInterpolator::Execute(), KX_Camera::ExtractFrustumSphere(), ImageRender::ImageRender(), KX_MouseFocusSensor::Init(), RAS_IPolyMaterial::Initialize(), MT_Transform::invert(), MT_Tuple3(), MT_Vector3::noiseGate(), KX_RayCast::reportHit(), MT_Transform::setIdentity(), MT_Transform::setValue(), KX_ObjectActuator::Update(), KX_SteeringActuator::Update(), KX_TrackToActuator::Update(), KX_BoneParentRelation::UpdateChildCoordinates(), and RAS_TexVert::xyz().
void MT_Tuple3::setValue (const double * v) [inline]
Definition at line 93 of file MT_Tuple3.h.
References m_co.
const MT_Scalar& MT_Tuple3::x () const [inline]
Definition at line 64 of file MT_Tuple3.h.
References m_co.
MT_Scalar& MT_Tuple3::x () [inline]
Definition at line 63 of file MT_Tuple3.h.
References m_co.
Referenced by KX_ObstacleSimulationTOI::AdjustObstacleVelocity(), BL_ConvertBlenderObjects(), BOP_4PointIntersect(), BOP_collinear(), BOP_comp(), BOP_exactComp(), BOP_intersect(), BOP_intersectPlane(), RAS_OpenGLRasterizer::DrawDebugCircle(), RAS_OpenGLRasterizer::FlushDebugShapes(), init(), MyGlutMouseHandler::Motion(), MT_CmMatrix4x4::MT_CmMatrix4x4(), MT_Plane3::MT_Plane3(), BSP_PlyLoader::NewMeshFromFile(), NewVertsFromFile(), processSamples(), RAS_CalcTexMatrix(), KX_RayCast::RayTest(), KX_GameObject::ResolveCombinedVelocities(), IK_QJacobian::SetBetas(), IK_QJacobian::SetDerivatives(), sweepCircleCircle(), sweepCircleSegment(), KX_ObjectActuator::Update(), IK_QSwingSegment::UpdateAngle(), IK_QSphericalSegment::UpdateAngle(), KX_ObstacleSimulation::UpdateObstacles(), and KX_BlenderSceneConverter::WritePhysicsObjectToAnimationIpo().
const MT_Scalar& MT_Tuple3::y () const [inline]
Definition at line 67 of file MT_Tuple3.h.
References m_co.
MT_Scalar& MT_Tuple3::y () [inline]
Definition at line 66 of file MT_Tuple3.h.
References m_co.
Referenced by KX_ObstacleSimulationTOI::AdjustObstacleVelocity(), BL_ConvertBlenderObjects(), BOP_4PointIntersect(), BOP_collinear(), BOP_comp(), BOP_exactComp(), BOP_intersect(), BOP_intersectPlane(), RAS_OpenGLRasterizer::DrawDebugCircle(), RAS_OpenGLRasterizer::FlushDebugShapes(), init(), MyGlutMouseHandler::Motion(), MT_CmMatrix4x4::MT_CmMatrix4x4(), MT_Plane3::MT_Plane3(), BSP_PlyLoader::NewMeshFromFile(), NewVertsFromFile(), processSamples(), RAS_CalcTexMatrix(), KX_RayCast::RayTest(), KX_GameObject::ResolveCombinedVelocities(), IK_QJacobian::SetBetas(), IK_QJacobian::SetDerivatives(), sweepCircleCircle(), sweepCircleSegment(), KX_ObjectActuator::Update(), IK_QSwingSegment::UpdateAngle(), IK_QSphericalSegment::UpdateAngle(), KX_ObstacleSimulation::UpdateObstacles(), and KX_BlenderSceneConverter::WritePhysicsObjectToAnimationIpo().
const MT_Scalar& MT_Tuple3::z () const [inline]
Definition at line 70 of file MT_Tuple3.h.
References m_co.
MT_Scalar& MT_Tuple3::z () [inline]
Definition at line 69 of file MT_Tuple3.h.
References m_co.
Referenced by BL_ConvertBlenderObjects(), BOP_4PointIntersect(), BOP_collinear(), BOP_comp(), BOP_exactComp(), BOP_intersect(), BOP_intersectPlane(), filterObstacle(), RAS_OpenGLRasterizer::FlushDebugShapes(), init(), MyGlutMouseHandler::Motion(), MT_CmMatrix4x4::MT_CmMatrix4x4(), MT_Plane3::MT_Plane3(), BSP_PlyLoader::NewMeshFromFile(), NewVertsFromFile(), MT_Vector3::random(), RAS_CalcTexMatrix(), KX_RayCast::RayTest(), KX_GameObject::ResolveCombinedVelocities(), IK_QJacobian::SetBetas(), IK_QJacobian::SetDerivatives(), KX_SteeringActuator::Update(), KX_ObjectActuator::Update(), IK_QSwingSegment::UpdateAngle(), IK_QSphericalSegment::UpdateAngle(), and KX_BlenderSceneConverter::WritePhysicsObjectToAnimationIpo().
Member Data Documentation
MT_Scalar MT_Tuple3::m_co[3] [protected]
Definition at line 104 of file MT_Tuple3.h.
Referenced by MT_Vector3::absolute(), MT_Vector3::cross(), MT_Vector3::dot(), getValue(), MT_Point3::lerp(), MT_Vector3::operator*=(), MT_Point3::operator+=(), MT_Vector3::operator+=(), MT_Point3::operator-=(), MT_Vector3::operator-=(), MT_Point3::operator=(), operator[](), MT_Vector3::scale(), MT_Vector3::scaled(), setValue(), MT_Vector3::triple(), x(), y(), and z().
The documentation for this class was generated from the following file:
MT_Tuple3.h