Blender: AUD_Quaternion Class Reference
AUD_Quaternion Class Reference
#include <AUD_3DMath.h>
Public Member Functions
AUD_Quaternion (float w=1, float x=0, float y=0, float z=0)
const float & w () const
const float & x () const
const float & y () const
const float & z () const
void get (float *destination) const
float * get ()
const float * get () const
AUD_Vector3 getLookAt () const
AUD_Vector3 getUp () const
Detailed Description
This class represents a quaternion used for 3D rotations.
Definition at line 209 of file AUD_3DMath.h.
Constructor & Destructor Documentation
AUD_Quaternion::AUD_Quaternion (float w = 1, float x = 0, float y = 0, float z = 0) [inline]
Creates a new quaternion.
Parameters:
w The w component.
x The x component.
y The y component.
z The z component.
Definition at line 235 of file AUD_3DMath.h.
Member Function Documentation
void AUD_Quaternion::get (float * destination) const [inline]
Retrieves the components of the vector.
Parameters:
destination Where the 4 float values should be saved to.
Definition at line 280 of file AUD_3DMath.h.
References m_v.
Referenced by AUD_SequencerEntry::AUD_SequencerEntry(), AUD_SequencerFactory::AUD_SequencerFactory(), AUD_SequencerReader::read(), and AUD_SequencerHandle::update().
float* AUD_Quaternion::get () [inline]
Retrieves the components of the vector.
Returns:
The components as float[4].
Definition at line 289 of file AUD_3DMath.h.
References m_v.
const float* AUD_Quaternion::get () const [inline]
Retrieves the components of the vector.
Returns:
The components as float[4].
Definition at line 298 of file AUD_3DMath.h.
References m_v.
AUD_Vector3 AUD_Quaternion::getLookAt () const [inline]
When the quaternion represents an orientation, this returns the negative z axis vector.
Returns:
The negative z axis vector.
Definition at line 308 of file AUD_3DMath.h.
References m_w, m_x, m_y, and m_z.
Referenced by AUD_SoftwareDevice::AUD_SoftwareHandle::update().
AUD_Vector3 AUD_Quaternion::getUp () const [inline]
When the quaternion represents an orientation, this returns the y axis vector.
Returns:
The y axis vector.
Definition at line 320 of file AUD_3DMath.h.
References m_w, m_x, m_y, and m_z.
Referenced by AUD_SoftwareDevice::AUD_SoftwareHandle::update().
const float& AUD_Quaternion::w () const [inline]
Retrieves the w component of the quarternion.
Returns:
The w component.
Definition at line 244 of file AUD_3DMath.h.
References m_w.
Referenced by Device_get_listener_orientation(), Handle_get_orientation(), and AUD_OpenALDevice::setListenerOrientation().
const float& AUD_Quaternion::x () const [inline]
Retrieves the x component of the quarternion.
Returns:
The x component.
Definition at line 253 of file AUD_3DMath.h.
References m_x.
Referenced by Device_get_listener_orientation(), Handle_get_orientation(), and AUD_OpenALDevice::setListenerOrientation().
const float& AUD_Quaternion::y () const [inline]
Retrieves the y component of the quarternion.
Returns:
The y component.
Definition at line 262 of file AUD_3DMath.h.
References m_y.
Referenced by Device_get_listener_orientation(), Handle_get_orientation(), and AUD_OpenALDevice::setListenerOrientation().
const float& AUD_Quaternion::z () const [inline]
Retrieves the z component of the quarternion.
Returns:
The z component.
Definition at line 271 of file AUD_3DMath.h.
References m_z.
Referenced by Device_get_listener_orientation(), Handle_get_orientation(), and AUD_OpenALDevice::setListenerOrientation().
Member Data Documentation
float AUD_Quaternion::m_v[4]
Definition at line 217 of file AUD_3DMath.h.
Referenced by get().
float AUD_Quaternion::m_w
Definition at line 220 of file AUD_3DMath.h.
Referenced by getLookAt(), getUp(), and w().
float AUD_Quaternion::m_x
Definition at line 221 of file AUD_3DMath.h.
Referenced by getLookAt(), getUp(), and x().
float AUD_Quaternion::m_y
Definition at line 222 of file AUD_3DMath.h.
Referenced by getLookAt(), getUp(), and y().
float AUD_Quaternion::m_z
Definition at line 223 of file AUD_3DMath.h.
Referenced by getLookAt(), getUp(), and z().
The documentation for this class was generated from the following file:
AUD_3DMath.h