Blender: file_panels.c File Reference
file_panels.c File Reference
fileselector
#include "BKE_context.h"
#include "BKE_screen.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BLF_translation.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "DNA_userdef_types.h"
#include "MEM_guardedalloc.h"
#include "RNA_access.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "WM_api.h"
#include "WM_types.h"
#include "file_intern.h"
#include "fsmenu.h"
#include <string.h>
Functions
static void file_panel_cb (bContext *C, void *arg_entry, void *UNUSED(arg_v))
static void file_panel_category (const bContext *C, Panel *pa, FSMenuCategory category, short *nr, int icon, int allow_delete, int reverse)
static void file_panel_system (const bContext *C, Panel *pa)
static void file_panel_bookmarks (const bContext *C, Panel *pa)
static void file_panel_recent (const bContext *C, Panel *pa)
static int file_panel_operator_poll (const bContext *C, PanelType *UNUSED(pt))
static void file_panel_operator_header (const bContext *C, Panel *pa)
static int file_panel_check_prop (PointerRNA *UNUSED(ptr), PropertyRNA *prop)
static void file_panel_operator (const bContext *C, Panel *pa)
void file_panels_register (ARegionType *art)
Detailed Description
Definition in file file_panels.c.
Function Documentation
static void file_panel_bookmarks (const bContext * C, Panel * pa) [static]
Definition at line 140 of file file_panels.c.
References SpaceFile::bookmarknr, CTX_wm_space_file(), file_panel_category(), FS_CATEGORY_BOOKMARKS, IFACE_, Panel::layout, NULL, uiItemL(), uiItemO(), and uiLayoutRow().
Referenced by file_panels_register().
static void file_panel_category (const bContext * C, Panel * pa, FSMenuCategory category, short * nr, int icon, int allow_delete, int reverse) [static]
Definition at line 70 of file file_panels.c.
References BLI_add_slash(), BLI_del_slash(), BLI_getlastdir(), BLI_path_cmp, BLI_strncpy(), CTX_wm_space_file(), FileSelectParams::dir, FILE_MAX, file_panel_cb(), fsmenu_can_save(), fsmenu_get(), fsmenu_get_entry(), fsmenu_get_nentries(), i, Panel::layout, LISTROW, NULL, SpaceFile::params, UI_EMBOSS, UI_EMBOSSN, UI_ICON_LEFT, UI_LAYOUT_ALIGN_LEFT, UI_TEXT_LEFT, UI_UNIT_X, UI_UNIT_Y, uiBlockSetEmboss(), uiButSetFlag(), uiButSetFunc(), uiDefIconTextButS(), uiItemIntO(), uiLayoutBox(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), and uiLayoutSetAlignment().
Referenced by file_panel_bookmarks(), file_panel_recent(), and file_panel_system().
static void file_panel_cb (bContext * C, void * arg_entry, void * UNUSEDarg_v) [static]
Definition at line 59 of file file_panels.c.
References RNA_string_set(), WM_OP_INVOKE_REGION_WIN, WM_operator_name_call(), WM_operator_properties_create(), and WM_operator_properties_free().
Referenced by file_panel_category().
static int file_panel_check_prop (PointerRNA * UNUSEDptr, PropertyRNA * prop) [static]
Definition at line 180 of file file_panels.c.
References RNA_property_identifier().
Referenced by file_panel_operator().
static void file_panel_operator (const bContext * C, Panel * pa) [static]
Definition at line 189 of file file_panels.c.
References CTX_wm_space_file(), file_draw_check_cb(), file_panel_check_prop(), Panel::layout, NULL, SpaceFile::op, UI_LAYOUT_OP_SHOW_EMPTY, uiBlockSetFunc(), uiLayoutGetBlock(), and uiLayoutOperatorButs().
Referenced by file_panels_register().
static void file_panel_operator_header (const bContext * C, Panel * pa) [static]
Definition at line 172 of file file_panels.c.
References BLI_strncpy(), CTX_wm_space_file(), Panel::drawname, wmOperatorType::name, SpaceFile::op, and wmOperator::type.
Referenced by file_panels_register().
static int file_panel_operator_poll (const bContext * C, PanelType * UNUSEDpt) [static]
Definition at line 166 of file file_panels.c.
References CTX_wm_space_file(), and SpaceFile::op.
Referenced by file_panels_register().
static void file_panel_recent (const bContext * C, Panel * pa) [static]
Definition at line 154 of file file_panels.c.
References CTX_wm_space_file(), file_panel_category(), FS_CATEGORY_RECENT, SpaceFile::recentnr, and USER_HIDE_RECENT.
Referenced by file_panels_register().
static void file_panel_system (const bContext * C, Panel * pa) [static]
Definition at line 132 of file file_panels.c.
References CTX_wm_space_file(), file_panel_category(), FS_CATEGORY_SYSTEM, and SpaceFile::systemnr.
Referenced by file_panels_register().
void file_panels_register (ARegionType * art)
Definition at line 202 of file file_panels.c.
References BLI_addtail(), PanelType::draw, PanelType::draw_header, file_panel_bookmarks(), file_panel_operator(), file_panel_operator_header(), file_panel_operator_poll(), file_panel_recent(), file_panel_system(), PanelType::idname, PanelType::label, MEM_callocN(), N_, ARegionType::paneltypes, and PanelType::poll.
Referenced by ED_spacetype_file().