Blender: KX_MaterialIpoController Class Reference
KX_MaterialIpoController Class Reference
#include <KX_MaterialIpoController.h>
Public Member Functions
KX_MaterialIpoController (dword matname_hash)
virtual ~KX_MaterialIpoController ()
virtual SG_Controller * GetReplica (class SG_Node *destnode)
virtual bool Update (double time)
virtual void SetSimulatedTime (double time)
void SetOption (int option, int value)
void AddInterpolator (KX_IInterpolator *interp)
Public Attributes
MT_Vector4 m_rgba
MT_Vector3 m_specrgb
MT_Scalar m_hard
MT_Scalar m_spec
MT_Scalar m_ref
MT_Scalar m_emit
MT_Scalar m_alpha
Detailed Description
Definition at line 17 of file KX_MaterialIpoController.h.
Constructor & Destructor Documentation
KX_MaterialIpoController::KX_MaterialIpoController (dword matname_hash) [inline]
Definition at line 35 of file KX_MaterialIpoController.h.
Referenced by GetReplica().
KX_MaterialIpoController::~KX_MaterialIpoController () [virtual]
Definition at line 91 of file KX_MaterialIpoController.cpp.
References i.
Member Function Documentation
void KX_MaterialIpoController::AddInterpolator (KX_IInterpolator * interp)
Definition at line 57 of file KX_MaterialIpoController.cpp.
Referenced by ConvertMaterialIpos(), and GetReplica().
SG_Controller * KX_MaterialIpoController::GetReplica (class SG_Node * destnode) [virtual]
Implements SG_Controller.
Definition at line 62 of file KX_MaterialIpoController.cpp.
References AddInterpolator(), SG_Controller::ClearObject(), i, KX_MaterialIpoController(), and KX_ScalarInterpolator::SetNewTarget().
void KX_MaterialIpoController::SetOption (int option, int value) [inline, virtual]
Hacky way of passing options to specific controllers
Parameters:
option An integer identifying the option.
value The value of this option.
Attention:
This has been placed here to give sca-elements
some control over the controllers. This is
necessary because the identity of the controller
is lost on the way here.
Implements SG_Controller.
Definition at line 49 of file KX_MaterialIpoController.h.
virtual void KX_MaterialIpoController::SetSimulatedTime (double time) [inline, virtual]
Implements SG_Controller.
Definition at line 43 of file KX_MaterialIpoController.h.
bool KX_MaterialIpoController::Update (double time) [virtual]
Implements SG_Controller.
Definition at line 11 of file KX_MaterialIpoController.cpp.
References SG_IObject::GetSGClientObject(), i, m_alpha, m_emit, m_hard, SG_Controller::m_pObject, m_ref, m_rgba, m_spec, m_specrgb, and KX_GameObject::UpdateMaterialData().
Member Data Documentation
MT_Scalar KX_MaterialIpoController::m_alpha
Definition at line 26 of file KX_MaterialIpoController.h.
Referenced by ConvertMaterialIpos(), and Update().
MT_Scalar KX_MaterialIpoController::m_emit
Definition at line 25 of file KX_MaterialIpoController.h.
Referenced by ConvertMaterialIpos(), and Update().
MT_Scalar KX_MaterialIpoController::m_hard
Definition at line 22 of file KX_MaterialIpoController.h.
Referenced by ConvertMaterialIpos(), and Update().
MT_Scalar KX_MaterialIpoController::m_ref
Definition at line 24 of file KX_MaterialIpoController.h.
Referenced by ConvertMaterialIpos(), and Update().
MT_Vector4 KX_MaterialIpoController::m_rgba
Definition at line 20 of file KX_MaterialIpoController.h.
Referenced by ConvertMaterialIpos(), and Update().
MT_Scalar KX_MaterialIpoController::m_spec
Definition at line 23 of file KX_MaterialIpoController.h.
Referenced by ConvertMaterialIpos(), and Update().
MT_Vector3 KX_MaterialIpoController::m_specrgb
Definition at line 21 of file KX_MaterialIpoController.h.
Referenced by ConvertMaterialIpos(), and Update().
The documentation for this class was generated from the following files:
KX_MaterialIpoController.h
KX_MaterialIpoController.cpp