Blender: BKE_cdderivedmesh.h File Reference
BKE_cdderivedmesh.h File Reference
blenkernel
#include "BKE_DerivedMesh.h"
Functions
struct DerivedMesh * CDDM_new (int numVerts, int numEdges, int numFaces, int numLoops, int numPolys)
int CDDM_Check (struct DerivedMesh *dm)
struct DerivedMesh * CDDM_from_mesh (struct Mesh *mesh, struct Object *ob)
DerivedMesh * CDDM_from_BMEditMesh (struct BMEditMesh *em, struct Mesh *me, int use_mdisps, int use_tessface)
DerivedMesh * CDDM_merge_verts (DerivedMesh *dm, const int *vtargetmap)
struct DerivedMesh * CDDM_from_curve (struct Object *ob)
DerivedMesh * CDDM_from_curve_customDB (struct Object *ob, struct ListBase *dispbase)
struct DerivedMesh * CDDM_copy (struct DerivedMesh *dm)
struct DerivedMesh * CDDM_copy_from_tessface (struct DerivedMesh *dm)
struct DerivedMesh * CDDM_from_template (struct DerivedMesh *source, int numVerts, int numEdges, int numFaces, int numLoops, int numPolys)
void CDDM_tessfaces_to_faces (struct DerivedMesh *dm)
void CDDM_apply_vert_coords (struct DerivedMesh *cddm, float(*vertCoords)[3])
void CDDM_apply_vert_normals (struct DerivedMesh *cddm, short(*vertNormals)[3])
void CDDM_calc_normals_mapping_ex (struct DerivedMesh *dm, const short only_face_normals)
void CDDM_calc_normals_mapping (struct DerivedMesh *dm)
void CDDM_calc_normals (struct DerivedMesh *dm)
void CDDM_calc_normals_tessface (struct DerivedMesh *dm)
void CDDM_calc_edges_tessface (struct DerivedMesh *dm)
void CDDM_calc_edges (struct DerivedMesh *dm)
void CDDM_recalc_tessellation (struct DerivedMesh *dm)
void CDDM_recalc_tessellation_ex (struct DerivedMesh *dm, const int do_face_nor_cpy)
void CDDM_lower_num_verts (struct DerivedMesh *dm, int numVerts)
void CDDM_lower_num_edges (struct DerivedMesh *dm, int numEdges)
void CDDM_lower_num_polys (struct DerivedMesh *dm, int numPolys)
void CDDM_lower_num_tessfaces (DerivedMesh *dm, int numTessFaces)
struct MVert * CDDM_get_vert (struct DerivedMesh *dm, int index)
struct MEdge * CDDM_get_edge (struct DerivedMesh *dm, int index)
struct MFace * CDDM_get_tessface (struct DerivedMesh *dm, int index)
struct MLoop * CDDM_get_loop (struct DerivedMesh *dm, int index)
struct MPoly * CDDM_get_poly (struct DerivedMesh *dm, int index)
struct MVert * CDDM_get_verts (struct DerivedMesh *dm)
struct MEdge * CDDM_get_edges (struct DerivedMesh *dm)
struct MFace * CDDM_get_tessfaces (struct DerivedMesh *dm)
struct MLoop * CDDM_get_loops (struct DerivedMesh *dm)
struct MPoly * CDDM_get_polys (struct DerivedMesh *dm)
void CDDM_set_mvert (struct DerivedMesh *dm, struct MVert *mvert)
void CDDM_set_medge (struct DerivedMesh *dm, struct MEdge *medge)
void CDDM_set_mface (struct DerivedMesh *dm, struct MFace *mface)
void CDDM_set_mloop (struct DerivedMesh *dm, struct MLoop *mloop)
void CDDM_set_mpoly (struct DerivedMesh *dm, struct MPoly *mpoly)
Detailed Description
CDDerivedMesh interface
CDDerivedMesh (CD = Custom Data) is a DerivedMesh backend which stores mesh elements (vertices, edges and faces) as layers of custom element data.
Definition in file BKE_cdderivedmesh.h.
Function Documentation
void CDDM_apply_vert_coords (struct DerivedMesh * cddm, float(*) vertCoords[3])
Definition at line 2051 of file cdderivedmesh.c.
References CD_MVERT, MVert::co, copy_v3_v3(), CustomData_duplicate_referenced_layer(), i, CDDerivedMesh::mvert, DerivedMesh::numVertData, and DerivedMesh::vertData.
Referenced by create_orco_dm(), curve_calc_modifiers_post(), deformVerts(), do_hair_dynamics(), editbmesh_calc_modifiers(), get_cddm(), get_dm(), mesh_calc_modifiers(), mesh_create_derived(), multires_apply_smat(), and multiresModifier_reshapeFromDeformMod().
void CDDM_apply_vert_normals (struct DerivedMesh * cddm, short(*) vertNormals[3])
Definition at line 2065 of file cdderivedmesh.c.
References CD_MVERT, copy_v3_v3_short(), CustomData_duplicate_referenced_layer(), i, CDDerivedMesh::mvert, MVert::no, DerivedMesh::numVertData, and DerivedMesh::vertData.
void CDDM_calc_edges (struct DerivedMesh * dm)
Definition at line 2417 of file cdderivedmesh.c.
References BLI_edgehash_free(), BLI_edgehash_haskey(), BLI_edgehash_insert(), BLI_edgehash_lookup(), BLI_edgehash_new(), BLI_edgehash_size(), BLI_edgehashIterator_free(), BLI_edgehashIterator_getKey(), BLI_edgehashIterator_getValue(), BLI_edgehashIterator_isDone(), BLI_edgehashIterator_new(), BLI_edgehashIterator_setValue(), BLI_edgehashIterator_step(), CD_CALLOC, CD_MEDGE, CD_ORIGINDEX, CustomData_add_layer(), CustomData_free(), CustomData_get_layer(), CDDerivedMesh::dm, DM_get_edge_data_layer(), MLoop::e, DerivedMesh::edgeData, GET_INT_FROM_POINTER, i, MPoly::loopstart, ME_EDGEDRAW, ME_EDGERENDER, ME_POLY_LOOP_NEXT, CDDerivedMesh::medge, CDDerivedMesh::mloop, CDDerivedMesh::mpoly, NULL, DerivedMesh::numEdgeData, DerivedMesh::numPolyData, ORIGINDEX_NONE, SET_INT_IN_POINTER, MPoly::totloop, MLoop::v, MEdge::v1, and MEdge::v2.
Referenced by CDDM_from_curve_customDB().
void CDDM_calc_edges_tessface (struct DerivedMesh * dm)
Definition at line 2359 of file cdderivedmesh.c.
References BLI_edgehash_free(), BLI_edgehash_haskey(), BLI_edgehash_insert(), BLI_edgehash_new(), BLI_edgehash_size(), BLI_edgehashIterator_free(), BLI_edgehashIterator_getKey(), BLI_edgehashIterator_isDone(), BLI_edgehashIterator_new(), BLI_edgehashIterator_step(), CD_CALLOC, CD_MEDGE, CD_ORIGINDEX, CustomData_add_layer(), CustomData_free(), CustomData_get_layer(), DerivedMesh::edgeData, i, ME_EDGEDRAW, ME_EDGERENDER, CDDerivedMesh::medge, CDDerivedMesh::mface, NULL, DerivedMesh::numEdgeData, DerivedMesh::numTessFaceData, ORIGINDEX_NONE, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by applyModifier(), CDDM_tessfaces_to_faces(), ConvertCSGDescriptorsToDerivedMesh(), cutEdges(), and explodeMesh().
void CDDM_calc_normals (struct DerivedMesh * dm)
Definition at line 2133 of file cdderivedmesh.c.
References CD_CALLOC, CD_MVERT, CD_NORMAL, CDDM_get_loops(), CDDM_get_polys(), CustomData_add_layer(), CustomData_duplicate_referenced_layer(), CustomData_get_layer(), mesh_calc_normals(), CDDerivedMesh::mvert, NULL, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numVertData, DerivedMesh::polyData, and DerivedMesh::vertData.
Referenced by applyModifier(), arrayModifier_doArray(), ConvertCSGDescriptorsToDerivedMesh(), create_orco_dm(), deformVerts(), dynamicPaint_Modifier_apply(), editbmesh_calc_modifiers(), explodeMesh(), get_cddm(), mesh_calc_modifiers(), and mesh_create_derived().
void CDDM_calc_normals_mapping (struct DerivedMesh * dm)
Definition at line 2124 of file cdderivedmesh.c.
References CD_MVERT, CDDM_calc_normals_mapping_ex(), CustomData_is_referenced_layer(), and DerivedMesh::vertData.
Referenced by cdDM_create(), and curve_calc_modifiers_post().
void CDDM_calc_normals_mapping_ex (struct DerivedMesh * dm, const short only_face_normals)
Definition at line 2079 of file cdderivedmesh.c.
References BLI_assert, CD_ASSIGN, CD_MVERT, CD_NORMAL, CD_POLYINDEX, CDDM_get_loops(), CDDM_get_polys(), CDDM_recalc_tessellation_ex(), CustomData_add_layer(), CustomData_duplicate_referenced_layer(), CustomData_free_layers(), CustomData_get_layer(), CustomData_has_layer(), DerivedMesh::faceData, FALSE, MEM_mallocN(), mesh_calc_normals_mapping_ex(), CDDerivedMesh::mface, CDDerivedMesh::mvert, NULL, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, DerivedMesh::numVertData, and DerivedMesh::vertData.
Referenced by CDDM_calc_normals_mapping(), and mesh_calc_modifiers().
void CDDM_calc_normals_tessface (struct DerivedMesh * dm)
Definition at line 2153 of file cdderivedmesh.c.
References CD_CALLOC, CD_MVERT, CD_NORMAL, CustomData_add_layer(), CustomData_duplicate_referenced_layer(), CustomData_get_layer(), DerivedMesh::faceData, mesh_calc_normals_tessface(), CDDerivedMesh::mface, CDDerivedMesh::mvert, NULL, DerivedMesh::numTessFaceData, DerivedMesh::numVertData, and DerivedMesh::vertData.
int CDDM_Check (struct DerivedMesh * dm)
Definition at line 1557 of file cdderivedmesh.c.
References cdDM_getMinMax(), and DerivedMesh::getMinMax.
struct DerivedMesh* CDDM_copy (struct DerivedMesh * dm) [read]
Definition at line 1999 of file cdderivedmesh.c.
References cddm_copy_ex().
Referenced by applyModifier(), canvas_copyDerivedMesh(), connect_hair(), curve_calc_modifiers_post(), deformVerts(), do_hair_dynamics(), dynamicPaint_brushMeshCalculateVelocity(), dynamicPaint_Modifier_apply(), dynamicPaint_paintMesh(), editbmesh_calc_modifiers(), get_cddm(), get_multires_dm(), mesh_calc_modifiers(), multires_modifier_update_mdisps(), multiresbake_create_loresdm(), multiresModifier_reshapeFromDeformMod(), and psys_render_set().
struct DerivedMesh* CDDM_copy_from_tessface (struct DerivedMesh * dm) [read]
Definition at line 2004 of file cdderivedmesh.c.
References cddm_copy_ex().
DerivedMesh* CDDM_from_BMEditMesh (struct BMEditMesh * em, struct Mesh * me, int use_mdisps, int use_tessface)
Referenced by applyModifier(), arrayModifier_doArray(), bm_mdisps_space_set(), construct_param_handle_subsurfed(), contarget_get_mesh_mat(), create_orco_dm(), deformMatricesEM(), deformVertsEM(), doEdgeSplit(), editbmesh_calc_modifiers(), and get_dm().
struct DerivedMesh* CDDM_from_curve (struct Object * ob) [read]
Definition at line 1706 of file cdderivedmesh.c.
References CDDM_from_curve_customDB(), and Object::disp.
Referenced by applyModifier(), and get_dm().
DerivedMesh* CDDM_from_curve_customDB (struct Object * ob, struct ListBase * dispbase)
Definition at line 1711 of file cdderivedmesh.c.
References CDDM_calc_edges(), CDDM_new(), DerivedMesh::deformedOnly, CDDerivedMesh::medge, MEM_freeN(), CDDerivedMesh::mloop, CDDerivedMesh::mpoly, CDDerivedMesh::mvert, nurbs_to_mdata_customdb(), and PBVH::totvert.
Referenced by CDDM_from_curve(), create_orco_dm(), and curve_calc_modifiers_post().
struct DerivedMesh* CDDM_from_mesh (struct Mesh * mesh, struct Object * ob) [read]
Referenced by applyModifier(), BL_ConvertMesh(), create_orco_dm(), deformMatrices(), deformVerts(), distribute_threads_init_data(), get_dm(), mesh_calc_modifiers(), mesh_create_derived(), multires_load_old(), multires_modifier_update_mdisps(), multires_subdivide(), multiresbake_create_hiresdm(), multiresbake_create_loresdm(), multiresModifier_base_apply(), CcdShapeConstructionInfo::SetMesh(), and subsurf_calculate_limit_positions().
struct DerivedMesh* CDDM_from_template (struct DerivedMesh * source, int numVerts, int numEdges, int numFaces, int numLoops, int numPolys) [read]
Definition at line 2011 of file cdderivedmesh.c.
References CD_CALLOC, CD_MEDGE, CD_MFACE, CD_MLOOP, CD_MPOLY, CD_MVERT, CD_ORIGINDEX, CD_POLYINDEX, cdDM_create(), CustomData_add_layer(), CustomData_get_layer(), CDDerivedMesh::dm, DM_from_template(), DM_TYPE_CDDM, DerivedMesh::edgeData, DerivedMesh::faceData, DerivedMesh::getEdgeDataArray, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVertDataArray, DerivedMesh::loopData, CDDerivedMesh::medge, CDDerivedMesh::mface, CDDerivedMesh::mloop, CDDerivedMesh::mpoly, CDDerivedMesh::mvert, NULL, DerivedMesh::polyData, and DerivedMesh::vertData.
Referenced by applyModifier(), CDDM_merge_verts(), cutEdges(), doMirrorOnAxis(), and explodeMesh().
struct MEdge* CDDM_get_edge (struct DerivedMesh * dm, int index) [read]
Definition at line 2531 of file cdderivedmesh.c.
Referenced by applyModifier().
struct MEdge* CDDM_get_edges (struct DerivedMesh * dm) [read]
Definition at line 2558 of file cdderivedmesh.c.
Referenced by applyModifier(), do_hair_dynamics(), and doMirrorOnAxis().
struct MLoop* CDDM_get_loop (struct DerivedMesh * dm, int index) [read]
Definition at line 2541 of file cdderivedmesh.c.
struct MLoop* CDDM_get_loops (struct DerivedMesh * dm) [read]
Definition at line 2568 of file cdderivedmesh.c.
Referenced by applyModifier(), CDDM_calc_normals(), CDDM_calc_normals_mapping_ex(), doMirrorOnAxis(), and dynamicPaint_Modifier_apply().
struct MPoly* CDDM_get_poly (struct DerivedMesh * dm, int index) [read]
Definition at line 2546 of file cdderivedmesh.c.
struct MPoly* CDDM_get_polys (struct DerivedMesh * dm) [read]
Definition at line 2573 of file cdderivedmesh.c.
Referenced by applyModifier(), CDDM_calc_normals(), CDDM_calc_normals_mapping_ex(), doMirrorOnAxis(), and dynamicPaint_Modifier_apply().
struct MFace* CDDM_get_tessface (struct DerivedMesh * dm, int index) [read]
Definition at line 2536 of file cdderivedmesh.c.
Referenced by closest_point_on_surface(), connect_hair(), ConvertCSGDescriptorsToDerivedMesh(), cutEdges(), explodeMesh(), get_dface(), and InterpCSGFace().
struct MFace* CDDM_get_tessfaces (struct DerivedMesh * dm) [read]
Definition at line 2563 of file cdderivedmesh.c.
struct MVert* CDDM_get_vert (struct DerivedMesh * dm, int index) [read]
Definition at line 2526 of file cdderivedmesh.c.
Referenced by applyModifier(), connect_hair(), ConvertCSGDescriptorsToDerivedMesh(), cutEdges(), deformVerts(), explodeMesh(), init_particle_interpolation(), and InterpCSGFace().
struct MVert* CDDM_get_verts (struct DerivedMesh * dm) [read]
Definition at line 2553 of file cdderivedmesh.c.
Referenced by applyModifier(), cdDM_foreachMappedVert(), cdDM_getVertCos(), displaceModifier_do(), do_hair_dynamics(), and doMirrorOnAxis().
void CDDM_lower_num_edges (struct DerivedMesh * dm, int numEdges)
Definition at line 2500 of file cdderivedmesh.c.
References CustomData_free_elem(), DerivedMesh::edgeData, and DerivedMesh::numEdgeData.
void CDDM_lower_num_polys (struct DerivedMesh * dm, int numPolys)
Definition at line 2516 of file cdderivedmesh.c.
References CustomData_free_elem(), DerivedMesh::numPolyData, and DerivedMesh::polyData.
void CDDM_lower_num_tessfaces (DerivedMesh * dm, int numTessFaces)
Definition at line 2508 of file cdderivedmesh.c.
References CustomData_free_elem(), DerivedMesh::faceData, and DerivedMesh::numTessFaceData.
void CDDM_lower_num_verts (struct DerivedMesh * dm, int numVerts)
Definition at line 2492 of file cdderivedmesh.c.
References CustomData_free_elem(), DerivedMesh::numVertData, and DerivedMesh::vertData.
DerivedMesh* CDDM_merge_verts (DerivedMesh * dm, const int * vtargetmap)
Definition at line 2185 of file cdderivedmesh.c.
References BLI_array_append, BLI_array_append_r, BLI_array_count, BLI_array_declare, BLI_array_free, BLI_edgehash_free(), BLI_edgehash_insert(), BLI_edgehash_lookup_p(), BLI_edgehash_new(), CDDM_from_template(), CustomData_copy_data(), CDDerivedMesh::dm, MLoop::e, DerivedMesh::edgeData, GET_INT_FROM_POINTER, i, LIKELY, DerivedMesh::loopData, MPoly::loopstart, CDDerivedMesh::medge, MEM_callocN(), MEM_freeN(), CDDerivedMesh::mloop, CDDerivedMesh::mpoly, CDDerivedMesh::mvert, DerivedMesh::needsFree, NULL, DerivedMesh::numEdgeData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numVertData, DerivedMesh::polyData, DerivedMesh::release, SET_INT_IN_POINTER, MPoly::totloop, UNLIKELY, MLoop::v, MEdge::v1, MEdge::v2, and DerivedMesh::vertData.
Referenced by doMirrorOnAxis().
struct DerivedMesh* CDDM_new (int numVerts, int numEdges, int numFaces, int numLoops, int numPolys) [read]
Definition at line 1630 of file cdderivedmesh.c.
References CD_CALLOC, CD_MEDGE, CD_MFACE, CD_MLOOP, CD_MPOLY, CD_MVERT, CD_ORIGINDEX, CD_POLYINDEX, cdDM_create(), CustomData_add_layer(), CustomData_get_layer(), CDDerivedMesh::dm, DM_init(), DM_TYPE_CDDM, DerivedMesh::edgeData, DerivedMesh::faceData, DerivedMesh::loopData, CDDerivedMesh::medge, CDDerivedMesh::mface, CDDerivedMesh::mloop, CDDerivedMesh::mpoly, CDDerivedMesh::mvert, NULL, DerivedMesh::polyData, and DerivedMesh::vertData.
Referenced by CDDM_from_BMEditMesh(), CDDM_from_curve_customDB(), ConvertCSGDescriptorsToDerivedMesh(), and do_hair_dynamics().
void CDDM_recalc_tessellation (struct DerivedMesh * dm)
Definition at line 1536 of file cdderivedmesh.c.
References CDDM_recalc_tessellation_ex(), and TRUE.
Referenced by cdDM_create().
void CDDM_recalc_tessellation_ex (struct DerivedMesh * dm, const int do_face_nor_cpy)
Definition at line 1515 of file cdderivedmesh.c.
References CD_MFACE, CD_ORIGINDEX, CD_POLYINDEX, CD_REFERENCE, CustomData_add_layer(), CustomData_bmesh_update_active_layers(), CustomData_get_layer(), DerivedMesh::faceData, DerivedMesh::loopData, mesh_recalcTessellation(), CDDerivedMesh::mface, CDDerivedMesh::mvert, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, and DerivedMesh::polyData.
Referenced by CDDM_calc_normals_mapping_ex(), and CDDM_recalc_tessellation().
void CDDM_set_medge (struct DerivedMesh * dm, struct MEdge * medge)
Definition at line 2680 of file cdderivedmesh.c.
References CD_ASSIGN, CD_MEDGE, CustomData_add_layer(), CustomData_has_layer(), DerivedMesh::edgeData, CDDerivedMesh::medge, and DerivedMesh::numEdgeData.
void CDDM_set_mface (struct DerivedMesh * dm, struct MFace * mface)
Definition at line 2690 of file cdderivedmesh.c.
References CD_ASSIGN, CD_MFACE, CustomData_add_layer(), CustomData_has_layer(), DerivedMesh::faceData, CDDerivedMesh::mface, and DerivedMesh::numTessFaceData.
void CDDM_set_mloop (struct DerivedMesh * dm, struct MLoop * mloop)
Definition at line 2700 of file cdderivedmesh.c.
References CD_ASSIGN, CD_MLOOP, CustomData_add_layer(), CustomData_has_layer(), DerivedMesh::loopData, CDDerivedMesh::mloop, and DerivedMesh::numLoopData.
void CDDM_set_mpoly (struct DerivedMesh * dm, struct MPoly * mpoly)
Definition at line 2710 of file cdderivedmesh.c.
References CD_ASSIGN, CD_MPOLY, CustomData_add_layer(), CustomData_has_layer(), CDDerivedMesh::mpoly, DerivedMesh::numPolyData, and DerivedMesh::polyData.
void CDDM_set_mvert (struct DerivedMesh * dm, struct MVert * mvert)
Definition at line 2670 of file cdderivedmesh.c.
References CD_ASSIGN, CD_MVERT, CustomData_add_layer(), CustomData_has_layer(), CDDerivedMesh::mvert, DerivedMesh::numVertData, and DerivedMesh::vertData.
void CDDM_tessfaces_to_faces (struct DerivedMesh * dm)
Definition at line 2578 of file cdderivedmesh.c.
References BLI_assert, BLI_edgehash_free(), BLI_edgehash_insert(), BLI_edgehash_lookup(), BLI_edgehash_new(), CD_ASSIGN, CD_DUPLICATE, CD_MASK_ORIGINDEX, CD_MLOOP, CD_MPOLY, CD_POLYINDEX, CDDM_calc_edges_tessface(), CustomData_add_layer(), CustomData_free(), CustomData_get_layer(), CustomData_merge(), CDDerivedMesh::dm, MLoop::e, DerivedMesh::faceData, GET_INT_FROM_POINTER, i, DerivedMesh::loopData, CDDerivedMesh::medge, MEM_callocN(), CDDerivedMesh::mface, CDDerivedMesh::mloop, CDDerivedMesh::mpoly, NULL, DerivedMesh::numEdgeData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, DerivedMesh::polyData, SET_INT_IN_POINTER, MLoop::v, MEdge::v1, MEdge::v2, and MFace::v4.
Referenced by applyModifier(), cddm_copy_ex(), ConvertCSGDescriptorsToDerivedMesh(), cutEdges(), and explodeMesh().