Blender: GPC_Engine Class Reference
GPC_Engine Class Reference
#include <GPC_Engine.h>
Public Member Functions
GPC_Engine (char *customLoadingAnimation, int foregroundColor, int backgroundColor, int frameRate)
virtual ~GPC_Engine ()
void StartLoadingAnimation ()
bool Start (const char *filename)
bool Start (unsigned char *blenderDataBuffer, unsigned int blenderDataBufferSize)
void Stop ()
virtual void Exit ()
bool Initialized (void)
bool Loading (void)
bool Running (void) const
virtual float DetermineProgress (void)
void UpdateLoadingAnimation (void)
Public Attributes
bool m_initialized
bool m_running
bool m_loading
bool m_customLoadingAnimation
float m_previousProgress
GPC_System * m_system
GPC_KeyboardDevice * m_keyboarddev
GPC_MouseDevice * m_mousedev
GPC_Canvas * m_canvas
RAS_IRenderTools * m_rendertools
KetsjiPortal * m_portal
KX_ISceneConverter * m_sceneconverter
NG_LoopBackNetworkDeviceInterface * m_networkdev
struct ScrArea * m_curarea
char * m_customLoadingAnimationURL
int m_foregroundColor
int m_backgroundColor
int m_frameRate
GPC_RawImage * m_BlenderLogo
GPC_Canvas::TBannerId m_BlenderLogoId
GPC_RawImage * m_Blender3DLogo
GPC_Canvas::TBannerId m_Blender3DLogoId
Detailed Description
Definition at line 48 of file GPC_Engine.h.
Constructor & Destructor Documentation
GPC_Engine::GPC_Engine (char * customLoadingAnimation, int foregroundColor, int backgroundColor, int frameRate)
Definition at line 69 of file GPC_Engine.cpp.
References GPC_RawImage::alignBottomRight, GPC_RawImage::alignTopLeft, GPC_RawImage::Load(), m_Blender3DLogo, m_BlenderLogo, and m_customLoadingAnimationURL.
GPC_Engine::~GPC_Engine () [virtual]
Definition at line 110 of file GPC_Engine.cpp.
References m_Blender3DLogo, m_BlenderLogo, m_canvas, m_keyboarddev, m_mousedev, m_networkdev, m_rendertools, and m_system.
Member Function Documentation
float GPC_Engine::DetermineProgress (void) [virtual]
Definition at line 229 of file GPC_Engine.cpp.
References m_previousProgress.
Referenced by UpdateLoadingAnimation().
void GPC_Engine::Exit () [virtual]
Definition at line 306 of file GPC_Engine.cpp.
References m_canvas, m_initialized, m_keyboarddev, m_mousedev, m_networkdev, m_rendertools, m_running, m_system, and Stop().
bool GPC_Engine::Initialized (void) [inline]
Definition at line 112 of file GPC_Engine.h.
References m_initialized.
bool GPC_Engine::Loading (void) [inline]
Definition at line 113 of file GPC_Engine.h.
References m_loading.
bool GPC_Engine::Running (void) const [inline]
Definition at line 114 of file GPC_Engine.h.
References m_running.
bool GPC_Engine::Start (const char * filename)
Definition at line 134 of file GPC_Engine.cpp.
References BKE_reports_clear(), BKE_reports_init(), BLENFILETYPE_PUB, BLO_read_from_file(), m_canvas, RPT_STORE, GPC_Canvas::SetBannerDisplayEnabled(), and BlendFileData::type.
Referenced by StartLoadingAnimation().
bool GPC_Engine::Start (unsigned char * blenderDataBuffer, unsigned int blenderDataBufferSize)
Definition at line 158 of file GPC_Engine.cpp.
References BKE_reports_clear(), BKE_reports_init(), BLENFILETYPE_PUB, BLO_read_from_memory(), m_canvas, RPT_STORE, GPC_Canvas::SetBannerDisplayEnabled(), and BlendFileData::type.
void GPC_Engine::StartLoadingAnimation ()
Definition at line 211 of file GPC_Engine.cpp.
References GetRawLoadingAnimation(), m_customLoadingAnimation, and Start().
void GPC_Engine::Stop ()
Definition at line 279 of file GPC_Engine.cpp.
References m_running, and m_sceneconverter.
Referenced by Exit().
void GPC_Engine::UpdateLoadingAnimation (void)
Definition at line 248 of file GPC_Engine.cpp.
References DetermineProgress(), STR_String::Format(), m_networkdev, m_previousProgress, NG_NetworkMessage::Release(), and NG_LoopBackNetworkDeviceInterface::SendNetworkMessage().
Member Data Documentation
int GPC_Engine::m_backgroundColor
Definition at line 86 of file GPC_Engine.h.
GPC_RawImage* GPC_Engine::m_Blender3DLogo
Definition at line 91 of file GPC_Engine.h.
Referenced by GPC_Engine(), and ~GPC_Engine().
GPC_Canvas::TBannerId GPC_Engine::m_Blender3DLogoId
Definition at line 92 of file GPC_Engine.h.
GPC_RawImage* GPC_Engine::m_BlenderLogo
Definition at line 89 of file GPC_Engine.h.
Referenced by GPC_Engine(), and ~GPC_Engine().
GPC_Canvas::TBannerId GPC_Engine::m_BlenderLogoId
Definition at line 90 of file GPC_Engine.h.
GPC_Canvas* GPC_Engine::m_canvas
The game engine's canvas abstraction.
Definition at line 72 of file GPC_Engine.h.
Referenced by Exit(), Start(), and ~GPC_Engine().
struct ScrArea* GPC_Engine::m_curarea
Definition at line 82 of file GPC_Engine.h.
bool GPC_Engine::m_customLoadingAnimation
Definition at line 60 of file GPC_Engine.h.
Referenced by StartLoadingAnimation().
char* GPC_Engine::m_customLoadingAnimationURL
Definition at line 84 of file GPC_Engine.h.
Referenced by GPC_Engine().
int GPC_Engine::m_foregroundColor
Definition at line 85 of file GPC_Engine.h.
int GPC_Engine::m_frameRate
Definition at line 87 of file GPC_Engine.h.
bool GPC_Engine::m_initialized
Engine construction state.
Definition at line 53 of file GPC_Engine.h.
Referenced by Exit(), and Initialized().
GPC_KeyboardDevice* GPC_Engine::m_keyboarddev
The game engine's keyboard abstraction.
Definition at line 68 of file GPC_Engine.h.
Referenced by Exit(), and ~GPC_Engine().
bool GPC_Engine::m_loading
loading state, ie a file is requested and is being loaded. Different from initialized and/or running
Definition at line 58 of file GPC_Engine.h.
Referenced by Loading().
GPC_MouseDevice* GPC_Engine::m_mousedev
The game engine's mouse abstraction.
Definition at line 70 of file GPC_Engine.h.
Referenced by Exit(), and ~GPC_Engine().
NG_LoopBackNetworkDeviceInterface* GPC_Engine::m_networkdev
Network interface.
Definition at line 80 of file GPC_Engine.h.
Referenced by Exit(), UpdateLoadingAnimation(), and ~GPC_Engine().
KetsjiPortal* GPC_Engine::m_portal
The portal used to start the engine.
Definition at line 76 of file GPC_Engine.h.
float GPC_Engine::m_previousProgress
Last file download progress measurement.
Definition at line 63 of file GPC_Engine.h.
Referenced by DetermineProgress(), and UpdateLoadingAnimation().
RAS_IRenderTools* GPC_Engine::m_rendertools
The game engine's platform dependent render tools.
Definition at line 74 of file GPC_Engine.h.
Referenced by Exit(), and ~GPC_Engine().
bool GPC_Engine::m_running
Engine state.
Definition at line 55 of file GPC_Engine.h.
Referenced by Exit(), Running(), and Stop().
KX_ISceneConverter* GPC_Engine::m_sceneconverter
Converts Blender data files.
Definition at line 78 of file GPC_Engine.h.
Referenced by Stop().
GPC_System* GPC_Engine::m_system
The game engine's system abstraction.
Definition at line 66 of file GPC_Engine.h.
Referenced by Exit(), and ~GPC_Engine().
The documentation for this class was generated from the following files:
GPC_Engine.h
GPC_Engine.cpp