Blender: buttons_header.c File Reference
buttons_header.c File Reference
buttons space
#include <string.h>
#include <stdio.h>
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BLF_translation.h"
#include "BKE_context.h"
#include "ED_screen.h"
#include "ED_types.h"
#include "DNA_object_types.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "buttons_intern.h"
Defines
#define B_CONTEXT_SWITCH 101
#define B_BUTSPREVIEW 102
#define BUT_UNIT_X (UI_UNIT_X+2)
#define BUTTON_HEADER_CTX(_ctx, _icon, _tip)
Functions
static void set_texture_context (bContext *C, SpaceButs *sbuts)
static void do_buttons_buttons (bContext *C, void *UNUSED(arg), int event)
void buttons_header_buttons (const bContext *C, ARegion *ar)
Detailed Description
Definition in file buttons_header.c.
Define Documentation
#define B_BUTSPREVIEW 102
Definition at line 55 of file buttons_header.c.
Referenced by do_buttons_buttons().
#define B_CONTEXT_SWITCH 101
Definition at line 54 of file buttons_header.c.
Referenced by do_buttons_buttons().
#define BUT_UNIT_X (UI_UNIT_X+2)
Definition at line 100 of file buttons_header.c.
Referenced by buttons_header_buttons().
#define BUTTON_HEADER_CTX (_ctx, _icon, _tip)
Value:
if (sbuts->pathflag & (1<<_ctx)) { \
        but = uiDefIconButS(block, ROW, B_CONTEXT_SWITCH, _icon, xco+=BUT_UNIT_X, yco, BUT_UNIT_X, UI_UNIT_Y, &(sbuts->mainb), 0.0, (float)_ctx, 0, 0, TIP_(_tip)); \
        uiButClearFlag(but, UI_BUT_UNDO); \
    } \
Referenced by buttons_header_buttons().
Function Documentation
void buttons_header_buttons (const bContext * C, ARegion * ar)
Definition at line 102 of file buttons_header.c.
References BCONTEXT_BONE, BCONTEXT_BONE_CONSTRAINT, BCONTEXT_CONSTRAINT, BCONTEXT_DATA, BCONTEXT_MATERIAL, BCONTEXT_MODIFIER, BCONTEXT_OBJECT, BCONTEXT_PARTICLE, BCONTEXT_PHYSICS, BCONTEXT_RENDER, BCONTEXT_SCENE, BCONTEXT_TEXTURE, BCONTEXT_WORLD, BUT_UNIT_X, BUTTON_HEADER_CTX, buttons_context_compute(), CTX_wm_space_buts(), SpaceButs::dataicon, do_buttons_buttons(), ED_area_header_switchbutton(), N_, NULL, View2D::tot, UI_EMBOSS, UI_UNIT_X, UI_view2d_totRect_set(), uiBeginBlock(), uiBlockBeginAlign(), uiBlockEndAlign(), uiBlockSetEmboss(), uiBlockSetHandleFunc(), uiDrawBlock(), uiEndBlock(), ARegion::v2d, rctf::ymax, and rctf::ymin.
Referenced by buttons_header_area_draw().
static void do_buttons_buttons (bContext * C, void * UNUSEDarg, int event) [static]
Definition at line 79 of file buttons_header.c.
References B_BUTSPREVIEW, B_CONTEXT_SWITCH, CTX_wm_area(), CTX_wm_space_buts(), ED_area_tag_redraw(), SpaceButs::mainb, SpaceButs::mainbuser, SpaceButs::preview, and set_texture_context().
Referenced by buttons_header_buttons().
static void set_texture_context (bContext * C, SpaceButs * sbuts) [static]
Definition at line 57 of file buttons_header.c.
References BCONTEXT_DATA, BCONTEXT_MATERIAL, BCONTEXT_PARTICLE, BCONTEXT_WORLD, CTX_data_active_object(), SpaceButs::mainb, OB_LAMP, SB_TEXC_MAT_OR_LAMP, SB_TEXC_PARTICLES, SB_TEXC_WORLD, SpaceButs::texture_context, and Object::type.
Referenced by do_buttons_buttons().