Blender: ED_node.h File Reference
ED_node.h File Reference
Editors
Functions
void ED_init_node_butfuncs (void)
void ED_node_tree_update (struct SpaceNode *snode, struct Scene *scene)
void ED_node_changed_update (struct ID *id, struct bNode *node)
void ED_node_generic_update (struct Main *bmain, struct bNodeTree *ntree, struct bNode *node)
void ED_node_shader_default (struct Scene *scene, struct ID *id)
void ED_node_composit_default (struct Scene *sce)
void ED_node_texture_default (struct Tex *tex)
void ED_node_link_intersect_test (struct ScrArea *sa, int test)
void ED_node_link_insert (struct ScrArea *sa)
void ED_node_update_hierarchy (struct bContext *C, struct bNodeTree *ntree)
void ED_node_set_active (struct Main *bmain, struct bNodeTree *ntree, struct bNode *node)
void ED_operatormacros_node (void)
Detailed Description
Definition in file ED_node.h.
Function Documentation
void ED_init_node_butfuncs (void)
Definition at line 2268 of file drawnode.c.
References bNodeSocketType::buttonfunc, bNodeType::drawfunc, bNodeType::drawupdatefunc, ListBase::first, i, bNodeType::next, node_common_set_butfunc(), node_composit_set_butfunc(), node_draw_default(), node_resize_area_default(), node_shader_set_butfunc(), node_socket_button_color(), node_socket_button_components(), node_socket_button_default(), node_socket_button_label(), node_texture_set_butfunc(), bNodeTreeType::node_types, node_update_default(), NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, ntreeGetSocketType(), ntreeGetType(), NULL, NUM_NTREE_TYPES, NUM_SOCKET_TYPES, bNodeType::resize_area_func, SOCK_BOOLEAN, SOCK_FLOAT, SOCK_INT, SOCK_RGBA, SOCK_SHADER, SOCK_VECTOR, bNodeSocketType::type, bNodeType::uifunc, and bNodeType::uifuncbut.
Referenced by WM_init().
void ED_node_changed_update (struct ID * id, struct bNode * node)
Definition at line 97 of file node_draw.c.
References DAG_id_tag_update(), GS, bNode::id, ID_LA, ID_MA, ID_WO, ID::name, NC_LAMP, NC_MATERIAL, NC_SCENE, NC_TEXTURE, NC_WORLD, ND_LIGHTING_DRAW, ND_NODES, ND_SHADING_DRAW, ND_WORLD_DRAW, node_tree_from_ID(), node_tree_get_editgroup(), nodeUpdate(), nodeUpdateID(), NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, and WM_main_add_notifier().
Referenced by do_node_internal_buttons(), ED_node_link_insert(), node_duplicate_exec(), node_generic_update_cb(), and texture_changed().
void ED_node_composit_default (struct Scene * sce)
Definition at line 365 of file node_edit.c.
References CMP_NODE_COMPOSITE, CMP_NODE_R_LAYERS, ListBase::first, G, G_DEBUG, Scene::id, bNode::id, id_us_plus(), bNode::inputs, bNode::locx, bNode::locy, nodeAddLink(), nodeAddNode(), nodeSetActive(), Scene::nodetree, NTREE_COMPOSIT, ntreeAddTree(), ntreeUpdateTree(), bNode::outputs, and bNodeTemplate::type.
void ED_node_generic_update (struct Main * bmain, struct bNodeTree * ntree, struct bNode * node)
Definition at line 157 of file node_draw.c.
References bNodeTreeType::foreach_nodetree, NodeUpdateCalldata::node, node_generic_update_cb(), NodeUpdateCalldata::ntree, NTREE_TEXTURE, ntreeGetType(), ntreeTexCheckCyclics(), and bNodeTree::type.
Referenced by ED_node_set_active(), ED_object_assign_active_image(), node_normal_cb(), node_socket_add_replace(), node_socket_disconnect(), and node_socket_remove().
void ED_node_link_insert (struct ScrArea * sa)
Definition at line 2818 of file node_edit.c.
References ED_node_changed_update(), ed_node_link_conditions(), SpaceNode::edittree, ListBase::first, bNodeLink::flag, SpaceNode::id, bNode::inputs, link(), bNodeTree::links, bNodeLink::next, NODE_LINKFLAG_HILITE, nodeAddLink(), ntreeUpdateTree(), NULL, bNode::outputs, snode_update(), socket_best_match(), bNodeLink::tonode, and bNodeLink::tosock.
Referenced by special_aftertrans_update().
void ED_node_link_intersect_test (struct ScrArea * sa, int test)
Definition at line 2849 of file node_edit.c.
References cut_links_intersect(), ed_node_link_conditions(), SpaceNode::edittree, ListBase::first, bNodeLink::flag, link(), bNodeTree::links, bNodeLink::next, NODE_LINKFLAG_HILITE, NULL, bNode::totr, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by flushTransNodes(), and special_aftertrans_update().
void ED_node_set_active (struct Main * bmain, struct bNodeTree * ntree, struct bNode * node)
Definition at line 603 of file node_edit.c.
References RenderData::actlay, BKE_image_verify_viewer(), CMP_NODE_COMPOSITE, CMP_NODE_R_LAYERS, CMP_NODE_SPLITVIEWER, CMP_NODE_VIEWER, bNode::custom1, ED_node_generic_update(), ELEM, ELEM3, ListBase::first, bNode::flag, GPU_material_free(), GS, has_nodetree(), Material::id, Scene::id, bNode::id, ID_LA, ID_MA, ID_TE, ID_WO, IMA_TYPE_COMPOSITE, Main::mat, ID::name, NC_IMAGE, NC_MATERIAL, ND_NODES, bNode::next, ID::next, NODE_ACTIVE_TEXTURE, NODE_DO_OUTPUT, NODE_GROUP, nodeClearActiveID(), bNodeTree::nodes, nodeSetActive(), Scene::nodetree, Material::nodetree, NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, NULL, Scene::r, Main::scene, SH_NODE_OUTPUT, bNodeTree::type, bNode::type, Scene::use_nodes, Material::use_nodes, and WM_main_add_notifier().
Referenced by node_add_node(), node_mouse_select(), node_select_single(), and template_texture_select().
void ED_node_shader_default (struct Scene * scene, struct ID * id)
Definition at line 276 of file node_edit.c.
References copy_v3_v3(), bNodeSocket::default_value, ListBase::first, GS, World::horr, ID_LA, ID_MA, ID_WO, bNode::inputs, LA_AREA, LA_LOCAL, LA_SPOT, ListBase::last, bNode::locx, bNode::locy, ID::name, nodeAddLink(), nodeAddNode(), nodeSetActive(), Lamp::nodetree, World::nodetree, Material::nodetree, NTREE_SHADER, ntreeAddTree(), ntreeUpdateTree(), bNode::outputs, Lamp::r, Material::r, scene_use_new_shading_nodes(), SH_NODE_BACKGROUND, SH_NODE_BSDF_DIFFUSE, SH_NODE_EMISSION, SH_NODE_MATERIAL, SH_NODE_OUTPUT, SH_NODE_OUTPUT_LAMP, SH_NODE_OUTPUT_MATERIAL, SH_NODE_OUTPUT_WORLD, bNodeTemplate::type, and Lamp::type.
Referenced by new_material_exec(), new_world_exec(), and object_lamp_add_exec().
void ED_node_texture_default (struct Tex * tex)
Definition at line 405 of file node_edit.c.
References ListBase::first, G, G_DEBUG, bNode::inputs, bNode::locx, bNode::locy, nodeAddLink(), nodeAddNode(), nodeSetActive(), Tex::nodetree, NTREE_TEXTURE, ntreeAddTree(), ntreeUpdateTree(), bNode::outputs, TEX_NODE_CHECKER, TEX_NODE_OUTPUT, and bNodeTemplate::type.
void ED_node_tree_update (struct SpaceNode * snode, struct Scene * scene)
Definition at line 89 of file node_draw.c.
References bNodeTree::id, SpaceNode::nodetree, snode_set_context(), and ID::us.
Referenced by new_node_tree_exec().
void ED_node_update_hierarchy (struct bContext * C, struct bNodeTree * ntree)
Referenced by node_resize_modal(), and special_aftertrans_update().
void ED_operatormacros_node (void)
Definition at line 108 of file node_ops.c.
References wmOperatorType::description, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorTypeMacro::ptr, RNA_boolean_set(), TRUE, WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().