Blender: GHOST_EventPrinter Class Reference
GHOST_EventPrinter Class Reference
#include <GHOST_EventPrinter.h>
Public Member Functions
virtual bool processEvent (GHOST_IEvent *event)
Protected Member Functions
void getKeyString (GHOST_TKey key, char str[32]) const
Detailed Description
An Event consumer that prints all the events to standard out. Really useful when debugging.
Definition at line 44 of file GHOST_EventPrinter.h.
Member Function Documentation
void GHOST_EventPrinter::getKeyString (GHOST_TKey key, char str[32]) const [protected]
Converts GHOST key code to a readable string.
Parameters:
key The GHOST key code to convert.
str The GHOST key code converted to a readable string.
Definition at line 186 of file GHOST_EventPrinter.cpp.
References GHOST_kKeyAccentGrave, GHOST_kKeyBackslash, GHOST_kKeyBackSpace, GHOST_kKeyCapsLock, GHOST_kKeyClear, GHOST_kKeyComma, GHOST_kKeyDelete, GHOST_kKeyDownArrow, GHOST_kKeyDownPage, GHOST_kKeyEnd, GHOST_kKeyEnter, GHOST_kKeyEsc, GHOST_kKeyF1, GHOST_kKeyF24, GHOST_kKeyGrLess, GHOST_kKeyHome, GHOST_kKeyInsert, GHOST_kKeyLeftAlt, GHOST_kKeyLeftArrow, GHOST_kKeyLeftControl, GHOST_kKeyLeftShift, GHOST_kKeyLinefeed, GHOST_kKeyMediaFirst, GHOST_kKeyMediaLast, GHOST_kKeyMediaPlay, GHOST_kKeyMediaStop, GHOST_kKeyNumLock, GHOST_kKeyNumpad0, GHOST_kKeyNumpad9, GHOST_kKeyNumpadAsterisk, GHOST_kKeyNumpadEnter, GHOST_kKeyNumpadMinus, GHOST_kKeyNumpadPeriod, GHOST_kKeyNumpadPlus, GHOST_kKeyNumpadSlash, GHOST_kKeyOS, GHOST_kKeyPause, GHOST_kKeyPrintScreen, GHOST_kKeyQuote, GHOST_kKeyRightAlt, GHOST_kKeyRightArrow, GHOST_kKeyRightBracket, GHOST_kKeyRightControl, GHOST_kKeyRightShift, GHOST_kKeyScrollLock, GHOST_kKeySpace, GHOST_kKeyTab, GHOST_kKeyUpArrow, GHOST_kKeyUpPage, and NULL.
Referenced by processEvent().
bool GHOST_EventPrinter::processEvent (GHOST_IEvent * event) [virtual]
Prints all the events received to std out.
Parameters:
event The event that can be handled or not.
Returns:
Indication as to whether the event was handled.
Implements GHOST_IEventConsumer.
Definition at line 41 of file GHOST_EventPrinter.cpp.
References GHOST_TEventButtonData::button, GHOST_TEventDragnDropData::data, GHOST_TEventDragnDropData::dataType, getKeyString(), GHOST_IEvent::getTime(), GHOST_IEvent::getType(), GHOST_ASSERT, GHOST_kDragnDropTypeFilenames, GHOST_kDragnDropTypeString, GHOST_kEventButtonDown, GHOST_kEventButtonUp, GHOST_kEventCursorMove, GHOST_kEventDraggingDropDone, GHOST_kEventDraggingEntered, GHOST_kEventDraggingExited, GHOST_kEventDraggingUpdated, GHOST_kEventKeyDown, GHOST_kEventKeyUp, GHOST_kEventOpenMainFile, GHOST_kEventQuit, GHOST_kEventUnknown, GHOST_kEventWheel, GHOST_kEventWindowActivate, GHOST_kEventWindowClose, GHOST_kEventWindowDeactivate, GHOST_kEventWindowSize, GHOST_kEventWindowUpdate, i, GHOST_TEventKeyData::key, str, GHOST_TEventCursorData::x, GHOST_TEventDragnDropData::x, GHOST_TEventCursorData::y, GHOST_TEventDragnDropData::y, and GHOST_TEventWheelData::z.
The documentation for this class was generated from the following files:
GHOST_EventPrinter.h
GHOST_EventPrinter.cpp