Blender: ArmatureImporter Class Reference
ArmatureImporter Class Reference
#include <ArmatureImporter.h>
Classes
struct LeafBone
Public Member Functions
ArmatureImporter (UnitConverter *conv, MeshImporterBase *mesh, AnimationImporterBase *anim, Scene *sce)
~ArmatureImporter ()
void add_joint (COLLADAFW::Node *node, bool root, Object *parent, Scene *sce)
void make_armatures (bContext *C)
bool write_skin_controller_data (const COLLADAFW::SkinControllerData *data)
bool write_controller (const COLLADAFW::Controller *controller)
COLLADAFW::UniqueId * get_geometry_uid (const COLLADAFW::UniqueId &controller_uid)
Object * get_armature_for_joint (COLLADAFW::Node *node)
void get_rna_path_for_joint (COLLADAFW::Node *node, char *joint_path, size_t count)
bool get_joint_bind_mat (float m[][4], COLLADAFW::Node *joint)
void set_tags_map (TagsMap &tags_map)
Detailed Description
Definition at line 55 of file ArmatureImporter.h.
Constructor & Destructor Documentation
ArmatureImporter::ArmatureImporter (UnitConverter * conv, MeshImporterBase * mesh, AnimationImporterBase * anim, Scene * sce)
Definition at line 52 of file ArmatureImporter.cpp.
ArmatureImporter::~ArmatureImporter ()
Definition at line 55 of file ArmatureImporter.cpp.
Member Function Documentation
void ArmatureImporter::add_joint (COLLADAFW::Node * node, bool root, Object * parent, Scene * sce)
Definition at line 615 of file ArmatureImporter.cpp.
Referenced by DocumentImporter::write_node().
Object * ArmatureImporter::get_armature_for_joint (COLLADAFW::Node * node)
Definition at line 758 of file ArmatureImporter.cpp.
References SkinInfo::get_armature(), NULL, and SkinInfo::uses_joint_or_descendant().
Referenced by AnimationImporter::translate_animation_OLD(), and AnimationImporter::translate_Animations().
COLLADAFW::UniqueId * ArmatureImporter::get_geometry_uid (const COLLADAFW::UniqueId & controller_uid)
Definition at line 750 of file ArmatureImporter.cpp.
References NULL.
Referenced by MeshImporter::create_mesh_object(), and make_armatures().
bool ArmatureImporter::get_joint_bind_mat (float m[][4], COLLADAFW::Node * joint)
Definition at line 787 of file ArmatureImporter.cpp.
References SkinInfo::get_joint_inv_bind_matrix(), and invert_m4().
Referenced by AnimationImporter::calc_joint_parent_mat_rest(), and AnimationImporter::get_joint_rest_mat().
void ArmatureImporter::get_rna_path_for_joint (COLLADAFW::Node * node, char * joint_path, size_t count)
Definition at line 781 of file ArmatureImporter.cpp.
References bc_get_joint_name(), and BLI_snprintf().
Referenced by AnimationImporter::add_bone_animation_sampled(), AnimationImporter::apply_matrix_curves(), AnimationImporter::translate_animation_OLD(), and AnimationImporter::translate_Animations().
void ArmatureImporter::make_armatures (bContext * C)
Definition at line 645 of file ArmatureImporter.cpp.
References bc_set_parent(), C, SkinInfo::free(), SkinInfo::get_armature(), SkinInfo::get_controller_uid(), get_geometry_uid(), MeshImporterBase::get_object_by_geom_uid(), SkinInfo::get_parent(), and SkinInfo::link_armature().
Referenced by DocumentImporter::finish().
void ArmatureImporter::set_tags_map (TagsMap & tags_map)
Definition at line 776 of file ArmatureImporter.cpp.
Referenced by DocumentImporter::finish().
bool ArmatureImporter::write_controller (const COLLADAFW::Controller * controller)
Definition at line 721 of file ArmatureImporter.cpp.
References co.
Referenced by DocumentImporter::writeController().
bool ArmatureImporter::write_skin_controller_data (const COLLADAFW::SkinControllerData * data)
Definition at line 696 of file ArmatureImporter.cpp.
References SkinInfo::add_joint(), SkinInfo::borrow_skin_controller_data(), and i.
Referenced by DocumentImporter::writeSkinControllerData().
The documentation for this class was generated from the following files:
ArmatureImporter.h
ArmatureImporter.cpp