Blender: rna_mesh.c File Reference
rna_mesh.c File Reference
RNA
#include <stdlib.h>
#include "MEM_guardedalloc.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_types.h"
#include "rna_internal.h"
#include "DNA_material_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "WM_types.h"
#include "BLI_array.h"
#include "BLI_math_base.h"
#include "BLI_math_rotation.h"
Functions
static void rna_def_mvert_group (BlenderRNA *brna)
static void rna_def_mvert (BlenderRNA *brna)
static void rna_def_medge (BlenderRNA *brna)
static void rna_def_mface (BlenderRNA *brna)
static void rna_def_mloop (BlenderRNA *brna)
static void rna_def_mpolygon (BlenderRNA *brna)
static void rna_def_mloopuv (BlenderRNA *brna)
static void rna_def_mtface (BlenderRNA *brna)
static void rna_def_mtexpoly (BlenderRNA *brna)
static void rna_def_msticky (BlenderRNA *brna)
static void rna_def_mcol (BlenderRNA *brna)
static void rna_def_mloopcol (BlenderRNA *brna)
static void rna_def_mproperties (BlenderRNA *brna)
void rna_def_texmat_common (StructRNA *srna, const char *texspace_editable)
static void rna_def_mesh_vertices (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_mesh_edges (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_mesh_tessfaces (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_mesh_loops (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_mesh_polygons (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_tessface_vertex_colors (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_loop_colors (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_uv_layers (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_polygon_int_layers (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_polygon_float_layers (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_polygon_string_layers (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_tessface_uv_textures (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_uv_textures (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_mesh (BlenderRNA *brna)
void RNA_def_mesh (BlenderRNA *brna)
Detailed Description
Definition in file rna_mesh.c.
Function Documentation
static void rna_def_loop_colors (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2254 of file rna_mesh.c.
References FUNC_USE_CONTEXT, NULL, PROP_EDITABLE, PROP_INT, PROP_POINTER, PROP_RNAPTR, PROP_UNSIGNED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_mesh().
static void rna_def_mcol (BlenderRNA * brna) [static]
Definition at line 1842 of file rna_mesh.c.
References NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_COLOR, PROP_FLOAT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_float_funcs(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_mesh().
static void rna_def_medge (BlenderRNA * brna) [static]
Definition at line 1385 of file rna_mesh.c.
References ME_HIDE, ME_LOOSEEDGE, ME_SEAM, ME_SHARP, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_float_funcs(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and SELECT.
Referenced by RNA_def_mesh().
static void rna_def_mesh (BlenderRNA * brna) [static]
Definition at line 2473 of file rna_mesh.c.
References DEG2RAD, ME_ALLEDGES, ME_AUTOSMOOTH, ME_AUTOSPACE, ME_DRAW_VNORMALS, ME_DRAWBWEIGHTS, ME_DRAWCREASES, ME_DRAWEDGES, ME_DRAWEXTRA_EDGELEN, ME_DRAWEXTRA_FACEANG, ME_DRAWEXTRA_FACEAREA, ME_DRAWEXTRA_INDICES, ME_DRAWFACES, ME_DRAWNORMALS, ME_DRAWSEAMS, ME_DRAWSHARP, ME_EDIT_MIRROR_TOPO, ME_EDIT_MIRROR_X, ME_EDIT_PAINT_MASK, ME_EDIT_VERT_SEL, ME_TWOSIDED, NC_OBJECT, NC_SPACE, ND_DRAW, ND_SPACE_VIEW3D, NULL, PROP_ANGLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_INT, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, RNA_api_mesh(), rna_def_animdata_common(), rna_def_loop_colors(), rna_def_mesh_edges(), rna_def_mesh_loops(), rna_def_mesh_polygons(), rna_def_mesh_tessfaces(), rna_def_mesh_vertices(), rna_def_polygon_float_layers(), rna_def_polygon_int_layers(), rna_def_polygon_string_layers(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), rna_def_tessface_uv_textures(), rna_def_tessface_vertex_colors(), rna_def_texmat_common(), rna_def_uv_layers(), and rna_def_uv_textures().
Referenced by RNA_def_mesh().
void RNA_def_mesh (BlenderRNA * brna)
Definition at line 2827 of file rna_mesh.c.
References rna_def_mcol(), rna_def_medge(), rna_def_mesh(), rna_def_mface(), rna_def_mloop(), rna_def_mloopcol(), rna_def_mloopuv(), rna_def_mpolygon(), rna_def_mproperties(), rna_def_msticky(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_mvert(), and rna_def_mvert_group().
static void rna_def_mesh_edges (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2121 of file rna_mesh.c.
References FUNC_USE_REPORTS, NULL, RNA_def_function(), RNA_def_function_flag(), RNA_def_int(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_mesh().
static void rna_def_mesh_loops (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2173 of file rna_mesh.c.
References FUNC_USE_REPORTS, NULL, RNA_def_function(), RNA_def_function_flag(), RNA_def_int(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_mesh().
static void rna_def_mesh_polygons (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2193 of file rna_mesh.c.
References FUNC_USE_REPORTS, NULL, PROP_INT, PROP_NONE, RNA_def_function(), RNA_def_function_flag(), RNA_def_int(), RNA_def_property(), RNA_def_property_int_sdna(), RNA_def_property_srna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_mesh().
static void rna_def_mesh_tessfaces (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2145 of file rna_mesh.c.
References FUNC_USE_REPORTS, NULL, PROP_INT, PROP_NONE, RNA_def_function(), RNA_def_function_flag(), RNA_def_int(), RNA_def_property(), RNA_def_property_int_sdna(), RNA_def_property_srna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_mesh().
static void rna_def_mesh_vertices (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2097 of file rna_mesh.c.
References FUNC_USE_REPORTS, NULL, RNA_def_function(), RNA_def_function_flag(), RNA_def_int(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_mesh().
static void rna_def_mface (BlenderRNA * brna) [static]
Definition at line 1442 of file rna_mesh.c.
References ME_FACE_SEL, ME_HIDE, ME_SMOOTH, NULL, PROP_BOOLEAN, PROP_DIRECTION, PROP_DYNAMIC, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_dynamic_array_funcs(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_mesh().
static void rna_def_mloop (BlenderRNA * brna) [static]
Definition at line 1507 of file rna_mesh.c.
References NULL, PROP_EDITABLE, PROP_INT, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_mesh().
static void rna_def_mloopcol (BlenderRNA * brna) [static]
Definition at line 1912 of file rna_mesh.c.
References NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_COLOR, PROP_FLOAT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_float_funcs(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_mesh().
static void rna_def_mloopuv (BlenderRNA * brna) [static]
Definition at line 1604 of file rna_mesh.c.
References MLOOPUV_EDGESEL, MLOOPUV_PINNED, MLOOPUV_VERTSEL, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_FLOAT, PROP_NONE, PROP_XYZ, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), and RNA_def_struct_sdna().
Referenced by RNA_def_mesh().
static void rna_def_mpolygon (BlenderRNA * brna) [static]
Definition at line 1532 of file rna_mesh.c.
References ME_FACE_SEL, ME_HIDE, ME_SMOOTH, NULL, PROP_BOOLEAN, PROP_DIRECTION, PROP_DYNAMIC, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_dynamic_array_funcs(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_mesh().
static void rna_def_mproperties (BlenderRNA * brna) [static]
Definition at line 1962 of file rna_mesh.c.
References NULL, PROP_BYTESTRING, PROP_COLLECTION, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_collection_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_mesh().
static void rna_def_msticky (BlenderRNA * brna) [static]
Definition at line 1827 of file rna_mesh.c.
References NULL, PROP_FLOAT, PROP_XYZ, RNA_def_property(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_mesh().
static void rna_def_mtexpoly (BlenderRNA * brna) [static]
Definition at line 1749 of file rna_mesh.c.
References NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_multi_array(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), TF_PIN1, and TF_SEL1.
Referenced by RNA_def_mesh().
static void rna_def_mtface (BlenderRNA * brna) [static]
Definition at line 1639 of file rna_mesh.c.
References NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_DYNAMIC, PROP_EDITABLE, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_dynamic_array_funcs(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_multi_array(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), TF_PIN1, and TF_SEL1.
Referenced by RNA_def_mesh().
static void rna_def_mvert (BlenderRNA * brna) [static]
Definition at line 1336 of file rna_mesh.c.
References ME_HIDE, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_DIRECTION, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_TRANSLATION, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_float_funcs(), RNA_def_property_int_funcs(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and SELECT.
Referenced by RNA_def_mesh().
static void rna_def_mvert_group (BlenderRNA * brna) [static]
Definition at line 1311 of file rna_mesh.c.
References NULL, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_mesh().
static void rna_def_polygon_float_layers (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2348 of file rna_mesh.c.
References FUNC_USE_CONTEXT, NULL, PROP_RNAPTR, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_mesh().
static void rna_def_polygon_int_layers (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2326 of file rna_mesh.c.
References FUNC_USE_CONTEXT, NULL, PROP_RNAPTR, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_mesh().
static void rna_def_polygon_string_layers (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2370 of file rna_mesh.c.
References FUNC_USE_CONTEXT, NULL, PROP_RNAPTR, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_mesh().
static void rna_def_tessface_uv_textures (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2392 of file rna_mesh.c.
References FUNC_USE_CONTEXT, FUNC_USE_REPORTS, NULL, PROP_INT, PROP_POINTER, PROP_RNAPTR, PROP_UNSIGNED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_mesh().
static void rna_def_tessface_vertex_colors (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2218 of file rna_mesh.c.
References FUNC_USE_CONTEXT, FUNC_USE_REPORTS, NULL, PROP_INT, PROP_POINTER, PROP_RNAPTR, PROP_UNSIGNED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_mesh().
void rna_def_texmat_common (StructRNA * srna, const char * texspace_editable)
Definition at line 2056 of file rna_mesh.c.
References ME_AUTOSPACE, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_FLOAT, PROP_NONE, PROP_TRANSLATION, PROP_XYZ, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_editable_func(), RNA_def_property_float_sdna(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_mesh().
static void rna_def_uv_layers (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2297 of file rna_mesh.c.
References NULL, PROP_EDITABLE, PROP_INT, PROP_POINTER, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_mesh().
static void rna_def_uv_textures (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2430 of file rna_mesh.c.
References FUNC_USE_CONTEXT, NULL, PROP_EDITABLE, PROP_INT, PROP_POINTER, PROP_RNAPTR, PROP_UNSIGNED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_mesh().