Blender: action_ops.c File Reference
action_ops.c File Reference
action space
#include <stdlib.h>
#include <math.h>
#include "DNA_space_types.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "ED_anim_api.h"
#include "ED_markers.h"
#include "ED_transform.h"
#include "action_intern.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
Functions
void action_operatortypes (void)
void ED_operatormacros_action (void)
static void action_keymap_keyframes (wmKeyConfig *keyconf, wmKeyMap *keymap)
void action_keymap (wmKeyConfig *keyconf)
Detailed Description
Definition in file action_ops.c.
Function Documentation
void action_keymap (wmKeyConfig * keyconf)
Definition at line 217 of file action_ops.c.
References action_keymap_keyframes(), SPACE_ACTION, and WM_keymap_find().
Referenced by ED_spacetype_action().
static void action_keymap_keyframes (wmKeyConfig * keyconf, wmKeyMap * keymap) [static]
Definition at line 108 of file action_ops.c.
References ACTKEYS_COLUMNSEL_CFRA, ACTKEYS_COLUMNSEL_KEYS, ACTKEYS_COLUMNSEL_MARKERS_BETWEEN, ACTKEYS_COLUMNSEL_MARKERS_COLUMN, ACTKEYS_LRSEL_LEFT, ACTKEYS_LRSEL_RIGHT, ACTKEYS_LRSEL_TEST, AKEY, BKEY, CKEY, DELKEY, DKEY, ED_marker_keymap_animedit_conflictfree(), EKEY, FALSE, HOMEKEY, IKEY, KKEY, KM_ALT, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTBRACKETKEY, LKEY, MKEY, OKEY, PADMINUS, PADPERIOD, PADPLUSKEY, PKEY, wmKeyMapItem::ptr, RIGHTBRACKETKEY, RKEY, RNA_boolean_set(), RNA_enum_set(), SELECTMOUSE, SKEY, SPACE_ACTION, TABKEY, TKEY, transform_keymap_for_space(), TRUE, VKEY, WM_keymap_add_item(), and XKEY.
Referenced by action_keymap().
void action_operatortypes (void)
Definition at line 54 of file action_ops.c.
References ACTION_OT_clean(), ACTION_OT_clickselect(), ACTION_OT_copy(), ACTION_OT_delete(), ACTION_OT_duplicate(), ACTION_OT_extrapolation_type(), ACTION_OT_frame_jump(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_markers_make_local(), ACTION_OT_mirror(), ACTION_OT_new(), ACTION_OT_paste(), ACTION_OT_previewrange_set(), ACTION_OT_sample(), ACTION_OT_select_all_toggle(), ACTION_OT_select_border(), ACTION_OT_select_column(), ACTION_OT_select_leftright(), ACTION_OT_select_less(), ACTION_OT_select_linked(), ACTION_OT_select_more(), ACTION_OT_snap(), ACTION_OT_view_all(), ACTION_OT_view_selected(), and WM_operatortype_append().
Referenced by ED_spacetype_action().
void ED_operatormacros_action (void)
Definition at line 91 of file action_ops.c.
References wmOperatorType::description, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorTypeMacro::ptr, RNA_enum_set(), TFM_TIME_DUPLICATE, WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().