Blender: FilterBlueScreen.cpp File Reference
FilterBlueScreen.cpp File Reference
BGE Video Texture
#include <PyObjectPlus.h>
#include <structmember.h>
#include "FilterBlueScreen.h"
#include "FilterBase.h"
#include "PyTypeList.h"
Functions
FilterBlueScreen * getFilter (PyFilter *self)
static PyObject * getColor (PyFilter *self, void *closure)
static int setColor (PyFilter *self, PyObject *value, void *closure)
static PyObject * getLimits (PyFilter *self, void *closure)
static int setLimits (PyFilter *self, PyObject *value, void *closure)
Variables
static PyGetSetDef filterBSGetSets []
PyTypeObject FilterBlueScreenType
Detailed Description
Definition in file FilterBlueScreen.cpp.
Function Documentation
static PyObject* getColor (PyFilter * self, void * closure) [static]
Definition at line 76 of file FilterBlueScreen.cpp.
References getFilter().
FilterBlueScreen* getFilter (PyFilter * self) [inline]
Definition at line 69 of file FilterBlueScreen.cpp.
Referenced by getColor(), getDepth(), getLimits(), setColor(), setDepth(), and setLimits().
static PyObject* getLimits (PyFilter * self, void * closure) [static]
Definition at line 103 of file FilterBlueScreen.cpp.
References getFilter().
static int setColor (PyFilter * self, PyObject * value, void * closure) [static]
Definition at line 83 of file FilterBlueScreen.cpp.
References getFilter(), NULL, and FilterBlueScreen::setColor().
static int setLimits (PyFilter * self, PyObject * value, void * closure) [static]
Definition at line 110 of file FilterBlueScreen.cpp.
References getFilter(), NULL, and FilterBlueScreen::setLimits().
Variable Documentation
PyTypeObject FilterBlueScreenType
Definition at line 139 of file FilterBlueScreen.cpp.
Referenced by registerAllTypes().
PyGetSetDef filterBSGetSets[] [static]
Initial value:
{
    {(char*)"color", (getter)getColor, (setter)setColor, (char*)"blue screen color", NULL},
    {(char*)"limits", (getter)getLimits, (setter)setLimits, (char*)"blue screen color limits", NULL},
    {(char*)"previous", (getter)Filter_getPrevious, (setter)Filter_setPrevious, (char*)"previous pixel filter", NULL},
    {NULL}
}
Definition at line 129 of file FilterBlueScreen.cpp.