Blender: ImageViewport.cpp File Reference
ImageViewport.cpp File Reference
BGE Video Texture
#include <PyObjectPlus.h>
#include <structmember.h>
#include "GL/glew.h"
#include "KX_PythonInit.h"
#include "Texture.h"
#include "ImageBase.h"
#include "FilterSource.h"
#include "ImageViewport.h"
Functions
ImageViewport * getImageViewport (PyImage *self)
PyObject * ImageViewport_getWhole (PyImage *self, void *closure)
int ImageViewport_setWhole (PyImage *self, PyObject *value, void *closure)
PyObject * ImageViewport_getAlpha (PyImage *self, void *closure)
int ImageViewport_setAlpha (PyImage *self, PyObject *value, void *closure)
static PyObject * ImageViewport_getPosition (PyImage *self, void *closure)
static int ImageViewport_setPosition (PyImage *self, PyObject *value, void *closure)
PyObject * ImageViewport_getCaptureSize (PyImage *self, void *closure)
int ImageViewport_setCaptureSize (PyImage *self, PyObject *value, void *closure)
Variables
static PyMethodDef imageViewportMethods []
static PyGetSetDef imageViewportGetSets []
PyTypeObject ImageViewportType
Detailed Description
Definition in file ImageViewport.cpp.
Function Documentation
ImageViewport* getImageViewport (PyImage * self) [inline]
Definition at line 168 of file ImageViewport.cpp.
Referenced by ImageViewport_getAlpha(), ImageViewport_getCaptureSize(), ImageViewport_getPosition(), ImageViewport_getWhole(), ImageViewport_setAlpha(), ImageViewport_setCaptureSize(), ImageViewport_setPosition(), and ImageViewport_setWhole().
PyObject* ImageViewport_getAlpha (PyImage * self, void * closure)
Definition at line 206 of file ImageViewport.cpp.
References getImageViewport(), and NULL.
PyObject* ImageViewport_getCaptureSize (PyImage * self, void * closure)
Definition at line 257 of file ImageViewport.cpp.
References getImageViewport().
static PyObject* ImageViewport_getPosition (PyImage * self, void * closure) [static]
Definition at line 229 of file ImageViewport.cpp.
References getImageViewport().
PyObject* ImageViewport_getWhole (PyImage * self, void * closure)
Definition at line 176 of file ImageViewport.cpp.
References getImageViewport(), and NULL.
int ImageViewport_setAlpha (PyImage * self, PyObject * value, void * closure)
Definition at line 213 of file ImageViewport.cpp.
References getImageViewport(), NULL, and ImageViewport::setAlpha().
int ImageViewport_setCaptureSize (PyImage * self, PyObject * value, void * closure)
Definition at line 264 of file ImageViewport.cpp.
References KDL::exp(), getImageViewport(), NULL, Exception::report(), ImageViewport::setCaptureSize(), and size().
static int ImageViewport_setPosition (PyImage * self, PyObject * value, void * closure) [static]
Definition at line 236 of file ImageViewport.cpp.
References getImageViewport(), NULL, and ImageViewport::setPosition().
int ImageViewport_setWhole (PyImage * self, PyObject * value, void * closure)
Definition at line 183 of file ImageViewport.cpp.
References KDL::exp(), getImageViewport(), NULL, Exception::report(), and ImageViewport::setWhole().
Variable Documentation
PyGetSetDef imageViewportGetSets[] [static]
Initial value:
{
    {(char*)"whole", (getter)ImageViewport_getWhole, (setter)ImageViewport_setWhole, (char*)"use whole viewport to capture", NULL},
    {(char*)"position", (getter)ImageViewport_getPosition, (setter)ImageViewport_setPosition, (char*)"upper left corner of captured area", NULL},
    {(char*)"capsize", (getter)ImageViewport_getCaptureSize, (setter)ImageViewport_setCaptureSize, (char*)"size of viewport area being captured", NULL},
    {(char*)"alpha", (getter)ImageViewport_getAlpha, (setter)ImageViewport_setAlpha, (char*)"use alpha in texture", NULL},
    {(char*)"valid", (getter)Image_valid, NULL, (char*)"bool to tell if an image is available", NULL},
    {(char*)"image", (getter)Image_getImage, NULL, (char*)"image data", NULL},
    {(char*)"size", (getter)Image_getSize, NULL, (char*)"image size", NULL},
    {(char*)"scale", (getter)Image_getScale, (setter)Image_setScale, (char*)"fast scale of image (near neighbor)", NULL},
    {(char*)"flip", (getter)Image_getFlip, (setter)Image_setFlip, (char*)"flip image vertically", NULL},
    {(char*)"filter", (getter)Image_getFilter, (setter)Image_setFilter, (char*)"pixel filter", NULL},
    {NULL}
}
Definition at line 301 of file ImageViewport.cpp.
PyMethodDef imageViewportMethods[] [static]
Initial value:
{
    {"refresh", (PyCFunction)Image_refresh, METH_NOARGS, "Refresh image - invalidate its current content"},
    {NULL}
}
Definition at line 295 of file ImageViewport.cpp.
PyTypeObject ImageViewportType
Definition at line 319 of file ImageViewport.cpp.
Referenced by registerAllTypes().