Blender: logImageLib.h File Reference
logImageLib.h File Reference
Cineon
Classes
struct LogImageByteConversionParameters
Defines
#define CINEON_FILE_MAGIC 0x802A5FD7
#define DPX_FILE_MAGIC 0x53445058
Typedefs
typedef struct _Log_Image_File_t_ LogImageFile
Functions
void logImageSetVerbose (int)
LogImageFile * logImageOpenFromMem (unsigned char *buffer, unsigned int size, int cineon)
LogImageFile * logImageOpen (const char *filename, int cineon)
int logImageGetSize (const LogImageFile *logImage, int *xsize, int *ysize, int *channels)
LogImageFile * logImageCreate (const char *filename, int cineon, int xsize, int ysize, int channels)
int logImageGetByteConversionDefaults (LogImageByteConversionParameters *params)
int logImageGetByteConversion (const LogImageFile *logImage, LogImageByteConversionParameters *params)
int logImageSetByteConversion (LogImageFile *logImage, const LogImageByteConversionParameters *params)
int logImageGetRowBytes (LogImageFile *logImage, unsigned short *row, int y)
int logImageSetRowBytes (LogImageFile *logImage, const unsigned short *row, int y)
void logImageClose (LogImageFile *logImage)
void logImageDump (const char *filename)
Detailed Description
Definition in file logImageLib.h.
Define Documentation
#define CINEON_FILE_MAGIC 0x802A5FD7
Definition at line 42 of file logImageLib.h.
Referenced by cineonIsMemFileCineon(), cineonOpen(), cineonOpenFromMem(), fillCineonFileInfo(), and logImageDump().
#define DPX_FILE_MAGIC 0x53445058
Definition at line 43 of file logImageLib.h.
Referenced by dpxIsMemFileCineon(), fillDpxFileInfo(), intern_dpxOpen(), and logImageDump().
Typedef Documentation
typedef struct _Log_Image_File_t_ LogImageFile
Definition at line 36 of file logImageLib.h.
Function Documentation
void logImageClose (LogImageFile * logImage)
Definition at line 150 of file logImageLib.c.
References _Log_Image_File_t_::close.
Referenced by imb_load_dpx_cineon(), and imb_save_dpx_cineon().
LogImageFile* logImageCreate (const char * filename, int cineon, int xsize, int ysize, int channels)
Definition at line 79 of file logImageLib.c.
References cineonCreate(), and dpxCreate().
Referenced by imb_save_dpx_cineon().
void logImageDump (const char * filename)
Definition at line 156 of file logImageLib.c.
References BLI_fopen(), CINEON_FILE_MAGIC, DPX_FILE_MAGIC, dpxDump(), and magic.
int logImageGetByteConversion (const LogImageFile * logImage, LogImageByteConversionParameters * params)
Definition at line 110 of file logImageLib.c.
References LogImageByteConversionParameters::blackPoint, LogImageByteConversionParameters::doLogarithm, LogImageByteConversionParameters::gamma, _Log_Image_File_t_::params, and LogImageByteConversionParameters::whitePoint.
int logImageGetByteConversionDefaults (LogImageByteConversionParameters * params)
Definition at line 100 of file logImageLib.c.
References LogImageByteConversionParameters::blackPoint, DEFAULT_BLACK_POINT, DEFAULT_GAMMA, DEFAULT_WHITE_POINT, LogImageByteConversionParameters::doLogarithm, LogImageByteConversionParameters::gamma, and LogImageByteConversionParameters::whitePoint.
Referenced by cineonCreate(), cineonOpen(), cineonOpenFromMem(), dpxCreate(), imb_save_dpx_cineon(), and intern_dpxOpen().
int logImageGetRowBytes (LogImageFile * logImage, unsigned short * row, int y)
Definition at line 138 of file logImageLib.c.
References _Log_Image_File_t_::getRow.
Referenced by imb_load_dpx_cineon().
int logImageGetSize (const LogImageFile * logImage, int * xsize, int * ysize, int * channels)
Definition at line 91 of file logImageLib.c.
References _Log_Image_File_t_::depth, _Log_Image_File_t_::height, and _Log_Image_File_t_::width.
Referenced by imb_load_dpx_cineon().
LogImageFile* logImageOpen (const char * filename, int cineon)
Definition at line 55 of file logImageLib.c.
References cineonOpen(), and dpxOpen().
LogImageFile* logImageOpenFromMem (unsigned char * buffer, unsigned int size, int cineon)
Definition at line 67 of file logImageLib.c.
References cineonOpenFromMem(), and dpxOpenFromMem().
Referenced by imb_load_dpx_cineon().
int logImageSetByteConversion (LogImageFile * logImage, const LogImageByteConversionParameters * params)
Definition at line 120 of file logImageLib.c.
References LogImageByteConversionParameters::blackPoint, LogImageByteConversionParameters::doLogarithm, LogImageByteConversionParameters::gamma, MAX_GAMMA, MIN_GAMMA, _Log_Image_File_t_::params, setupLut16(), and LogImageByteConversionParameters::whitePoint.
Referenced by imb_save_dpx_cineon().
int logImageSetRowBytes (LogImageFile * logImage, const unsigned short * row, int y)
Definition at line 144 of file logImageLib.c.
References _Log_Image_File_t_::setRow.
Referenced by imb_save_dpx_cineon().
void logImageSetVerbose (int)
Definition at line 48 of file logImageLib.c.
References cineonSetVerbose(), and dpxSetVerbose().
Referenced by imb_load_dpx_cineon(), and imb_save_dpx_cineon().