Blender: blender_mesh.cpp File Reference
blender_mesh.cpp File Reference
#include "mesh.h"
#include "object.h"
#include "scene.h"
#include "blender_sync.h"
#include "blender_util.h"
#include "subd_mesh.h"
#include "subd_patch.h"
#include "subd_split.h"
#include "util_foreach.h"
Functions
static CCL_NAMESPACE_BEGIN bool mesh_need_attribute (Scene *scene, Mesh *mesh, Attribute::Standard std)
static bool mesh_need_attribute (Scene *scene, Mesh *mesh, ustring name)
static void create_mesh (Scene *scene, Mesh *mesh, BL::Mesh b_mesh, const vector< uint > &used_shaders)
static void create_subd_mesh (Mesh *mesh, BL::Mesh b_mesh, PointerRNA *cmesh, const vector< uint > &used_shaders)
Function Documentation
static void create_mesh (Scene * scene, Mesh * mesh, BL::Mesh b_mesh, const vector< uint > & used_shaders) [static]
Definition at line 60 of file blender_mesh.cpp.
References AttributeSet::add(), Mesh::add_triangle(), Mesh::attributes, clamp, color_srgb_to_scene_linear(), Attribute::CORNER, Attribute::data_float3(), get_float3(), get_int4(), i, make_float3(), mesh_need_attribute(), N, size(), smooth(), Attribute::STD_GENERATED, Attribute::STD_NONE, Attribute::STD_UV, Attribute::STD_VERTEX_NORMAL, Mesh::verts, and float3::x.
static void create_subd_mesh (Mesh * mesh, BL::Mesh b_mesh, PointerRNA * cmesh, const vector< uint > & used_shaders) [static]
Definition at line 187 of file blender_mesh.cpp.
References SubdMesh::add_face(), SubdMesh::add_vert(), DiagSplit::camera, DiagSplit::dicing_rate, get_float3(), get_int4(), SubdMesh::link_boundary(), NULL, RNA_float_get(), and SubdMesh::tessellate().
static CCL_NAMESPACE_BEGIN bool mesh_need_attribute (Scene * scene, Mesh * mesh, Attribute::Standard std) [static]
Definition at line 36 of file blender_mesh.cpp.
References Scene::shaders, Attribute::STD_NONE, and Mesh::used_shaders.
Referenced by create_mesh().
static bool mesh_need_attribute (Scene * scene, Mesh * mesh, ustring name) [static]
Definition at line 48 of file blender_mesh.cpp.
References Scene::shaders, and Mesh::used_shaders.