Blender: ED_keyframing.h File Reference
ED_keyframing.h File Reference
Editors
#include "RNA_types.h"
Classes
struct KeyingSetInfo
Defines
#define IS_AUTOKEY_ON(scene) ((scene) ? (scene->toolsettings->autokey_mode & AUTOKEY_ON) : (U.autokey_mode & AUTOKEY_ON))
#define IS_AUTOKEY_MODE(scene, mode) ((scene) ? (scene->toolsettings->autokey_mode == AUTOKEY_MODE_##mode) : (U.autokey_mode == AUTOKEY_MODE_##mode))
#define IS_AUTOKEY_FLAG(scene, flag)
#define ANIM_KS_LOCATION_ID "Location"
#define ANIM_KS_ROTATION_ID "Rotation"
#define ANIM_KS_SCALING_ID "Scaling"
#define ANIM_KS_LOC_ROT_SCALE_ID "LocRotScale"
#define ANIM_KS_AVAILABLE_ID "Available"
#define ANIM_KS_WHOLE_CHARACTER_ID "WholeCharacter"
Typedefs
typedef int(* cbKeyingSet_Poll)(struct KeyingSetInfo *ksi, struct bContext *C)
typedef void(* cbKeyingSet_Iterator)(struct KeyingSetInfo *ksi, struct bContext *C, struct KeyingSet *ks)
typedef void(* cbKeyingSet_Generate)(struct KeyingSetInfo *ksi, struct bContext *C, struct KeyingSet *ks, struct PointerRNA *ptr)
typedef struct KeyingSetInfo KeyingSetInfo
typedef enum eModifyKey_Modes eModifyKey_Modes
typedef enum eModifyKey_Returns eModifyKey_Returns
typedef enum eCreateDriverFlags eCreateDriverFlags
typedef enum eAnimFilterFlags eAnimFilterFlags
Enumerations
enum eModifyKey_Modes { MODIFYKEY_MODE_INSERT = 0, MODIFYKEY_MODE_DELETE }
enum eModifyKey_Returns { MODIFYKEY_INVALID_CONTEXT = -1, MODIFYKEY_MISSING_TYPEINFO = -2 }
enum eCreateDriverFlags { CREATEDRIVER_WITH_DEFAULT_DVAR = (1<<0) }
enum eAnimFilterFlags {
ANIMFILTER_KEYS_LOCAL = (1<<0), ANIMFILTER_KEYS_MUTED = (1<<1), ANIMFILTER_KEYS_ACTIVE = (1<<2), ANIMFILTER_KEYS_NOMAT = (1<<9),
ANIMFILTER_KEYS_NOSKEY = (1<<10)
}
Functions
short ANIM_get_keyframing_flags (struct Scene *scene, short incl_mode)
struct bAction * verify_adt_action (struct ID *id, short add)
struct FCurve * verify_fcurve (struct bAction *act, const char group[], const char rna_path[], const int array_index, short add)
int insert_bezt_fcurve (struct FCurve *fcu, struct BezTriple *bezt, short flag)
int insert_vert_fcurve (struct FCurve *fcu, float x, float y, short flag)
short insert_keyframe_direct (struct ReportList *reports, struct PointerRNA ptr, struct PropertyRNA *prop, struct FCurve *fcu, float cfra, short flag)
short insert_keyframe (struct ReportList *reports, struct ID *id, struct bAction *act, const char group[], const char rna_path[], int array_index, float cfra, short flag)
short delete_keyframe (struct ReportList *reports, struct ID *id, struct bAction *act, const char group[], const char rna_path[], int array_index, float cfra, short flag)
void ANIM_relative_keyingset_add_source (ListBase *dsources, struct ID *id, struct StructRNA *srna, void *data)
short ANIM_validate_keyingset (struct bContext *C, ListBase *dsources, struct KeyingSet *ks)
int ANIM_apply_keyingset (struct bContext *C, ListBase *dsources, struct bAction *act, struct KeyingSet *ks, short mode, float cfra)
struct KeyingSet * ANIM_builtin_keyingset_get_named (struct KeyingSet *prevKS, const char name[])
KeyingSetInfo * ANIM_keyingset_info_find_named (const char name[])
void ANIM_keyingset_info_register (KeyingSetInfo *ksi)
void ANIM_keyingset_info_unregister (struct Main *bmain, KeyingSetInfo *ksi)
void ANIM_keyingset_infos_exit (void)
struct KeyingSet * ANIM_scene_get_active_keyingset (struct Scene *scene)
int ANIM_scene_get_keyingset_index (struct Scene *scene, struct KeyingSet *ks)
struct KeyingSet * ANIM_get_keyingset_for_autokeying (struct Scene *scene, const char *tranformKSName)
struct EnumPropertyItem * ANIM_keying_sets_enum_itemf (struct bContext *C, struct PointerRNA *ptr, struct PropertyRNA *prop, int *free)
short ANIM_keyingset_context_ok_poll (struct bContext *C, struct KeyingSet *ks)
struct FCurve * verify_driver_fcurve (struct ID *id, const char rna_path[], const int array_index, short add)
short ANIM_driver_can_paste (void)
short ANIM_add_driver (struct ReportList *reports, struct ID *id, const char rna_path[], int array_index, short flag, int type)
short ANIM_remove_driver (struct ReportList *reports, struct ID *id, const char rna_path[], int array_index, short flag)
short ANIM_copy_driver (struct ReportList *reports, struct ID *id, const char rna_path[], int array_index, short flag)
short ANIM_paste_driver (struct ReportList *reports, struct ID *id, const char rna_path[], int array_index, short flag)
int autokeyframe_cfra_can_key (struct Scene *scene, struct ID *id)
short fcurve_frame_has_keyframe (struct FCurve *fcu, float frame, short filter)
short id_frame_has_keyframe (struct ID *id, float frame, short filter)
int ED_autokeyframe_object (struct bContext *C, struct Scene *scene, struct Object *ob, struct KeyingSet *ks)
int ED_autokeyframe_pchan (struct bContext *C, struct Scene *scene, struct Object *ob, struct bPoseChannel *pchan, struct KeyingSet *ks)
Detailed Description
Definition in file ED_keyframing.h.
Define Documentation
#define ANIM_KS_AVAILABLE_ID "Available"
Definition at line 325 of file ED_keyframing.h.
Referenced by ANIM_get_keyingset_for_autokeying().
#define ANIM_KS_LOC_ROT_SCALE_ID "LocRotScale"
Definition at line 324 of file ED_keyframing.h.
Referenced by autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), pose_clear_transforms_exec(), pose_flip_quats_exec(), and pose_paste_exec().
#define ANIM_KS_LOCATION_ID "Location"
Definition at line 321 of file ED_keyframing.h.
Referenced by autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), move_camera(), object_location_clear_exec(), pose_clear_loc_exec(), snap_sel_to_curs(), and snap_sel_to_grid().
#define ANIM_KS_ROTATION_ID "Rotation"
Definition at line 322 of file ED_keyframing.h.
Referenced by autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), move_camera(), object_rotation_clear_exec(), and pose_clear_rot_exec().
#define ANIM_KS_SCALING_ID "Scaling"
Definition at line 323 of file ED_keyframing.h.
Referenced by autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), object_scale_clear_exec(), and pose_clear_scale_exec().
#define ANIM_KS_WHOLE_CHARACTER_ID "WholeCharacter"
Definition at line 326 of file ED_keyframing.h.
Referenced by poseAnim_mapping_autoKeyframe(), poselib_add_exec(), and poselib_keytag_pose().
#define IS_AUTOKEY_FLAG (scene, flag)
Value:
((scene)? \
        ((scene->toolsettings->autokey_flag & AUTOKEY_FLAG_##flag) || (U.autokey_flag & AUTOKEY_FLAG_##flag)) \
     : \
        (U.autokey_flag & AUTOKEY_FLAG_##flag))
Definition at line 275 of file ED_keyframing.h.
Referenced by add_keyingset_button_exec(), ANIM_get_keyframing_flags(), ANIM_get_keyingset_for_autokeying(), animrecord_check_state(), autokeyframe_ob_cb_func(), and autokeyframe_pose_cb_func().
#define IS_AUTOKEY_MODE (scene, mode) ((scene) ? (scene->toolsettings->autokey_mode == AUTOKEY_MODE_##mode) : (U.autokey_mode == AUTOKEY_MODE_##mode))
Definition at line 273 of file ED_keyframing.h.
Referenced by ANIM_get_keyframing_flags(), autokeyframe_cfra_can_key(), and poselib_preview_cleanup().
#define IS_AUTOKEY_ON (scene) ((scene) ? (scene->toolsettings->autokey_mode & AUTOKEY_ON) : (U.autokey_mode & AUTOKEY_ON))
Definition at line 271 of file ED_keyframing.h.
Referenced by autokeyframe_cfra_can_key(), recalcData_view3d(), viewRedrawForce(), and viewRedrawPost().
Typedef Documentation
typedef void(* cbKeyingSet_Generate)(struct KeyingSetInfo *ksi, struct bContext *C, struct KeyingSet *ks, struct PointerRNA *ptr)
Definition at line 127 of file ED_keyframing.h.
typedef void(* cbKeyingSet_Iterator)(struct KeyingSetInfo *ksi, struct bContext *C, struct KeyingSet *ks)
Definition at line 125 of file ED_keyframing.h.
typedef int(* cbKeyingSet_Poll)(struct KeyingSetInfo *ksi, struct bContext *C)
Definition at line 123 of file ED_keyframing.h.
typedef enum eAnimFilterFlags eAnimFilterFlags
typedef enum eCreateDriverFlags eCreateDriverFlags
typedef enum eModifyKey_Modes eModifyKey_Modes
typedef enum eModifyKey_Returns eModifyKey_Returns
typedef struct KeyingSetInfo KeyingSetInfo
Enumeration Type Documentation
enum eAnimFilterFlags
Enumerator:
ANIMFILTER_KEYS_LOCAL
ANIMFILTER_KEYS_MUTED
ANIMFILTER_KEYS_ACTIVE
ANIMFILTER_KEYS_NOMAT
ANIMFILTER_KEYS_NOSKEY
Definition at line 304 of file ED_keyframing.h.
enum eCreateDriverFlags
Enumerator:
CREATEDRIVER_WITH_DEFAULT_DVAR
Definition at line 222 of file ED_keyframing.h.
enum eModifyKey_Modes
Enumerator:
MODIFYKEY_MODE_INSERT
MODIFYKEY_MODE_DELETE
Definition at line 168 of file ED_keyframing.h.
enum eModifyKey_Returns
Enumerator:
MODIFYKEY_INVALID_CONTEXT
MODIFYKEY_MISSING_TYPEINFO
Definition at line 174 of file ED_keyframing.h.
Function Documentation
short ANIM_add_driver (struct ReportList * reports, struct ID * id, const char rna_path[], int array_index, short flag, int type)
Definition at line 138 of file drivers.c.
References BKE_reportf(), BLI_snprintf(), BLI_strncpy(), CREATEDRIVER_WITH_DEFAULT_DVAR, FCurve::driver, driver_add_new_variable(), driver_change_variable_type(), DRIVER_TYPE_PYTHON, DVAR_TYPE_TRANSFORM_CHAN, ChannelDriver::expression, ID::name, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, RNA_id_pointer_create(), RNA_path_resolve(), RNA_property_array_length(), RNA_property_boolean_get(), RNA_property_boolean_get_index(), RNA_property_float_get(), RNA_property_float_get_index(), RNA_property_int_get(), RNA_property_int_get_index(), RNA_property_type(), RPT_ERROR, ChannelDriver::type, and verify_driver_fcurve().
Referenced by add_driver_button_exec(), do_outliner_drivers_editop(), and pyrna_struct_driver_add().
int ANIM_apply_keyingset (struct bContext * C, ListBase * dsources, struct bAction * act, struct KeyingSet * ks, short mode, float cfra)
Definition at line 908 of file keyingsets.c.
References ANIM_get_keyframing_flags(), ANIM_validate_keyingset(), KS_Path::array_index, BKE_reportf(), CTX_data_scene(), CTX_wm_reports(), delete_keyframe(), ListBase::first, KS_Path::flag, KS_Path::group, KS_Path::groupmode, GS, i, KS_Path::id, ID_OB, insert_keyframe(), KS_Path::keyingflag, KeyingSet::keyingflag, KSP_FLAG_WHOLE_ARRAY, KSP_GROUP_KSNAME, KSP_GROUP_NONE, MODIFYKEY_MODE_DELETE, MODIFYKEY_MODE_INSERT, NA_EDITED, ID::name, KeyingSet::name, NC_ANIMATION, ND_KEYFRAME, KS_Path::next, NULL, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, KeyingSet::paths, tRKS_DSource::ptr, Object::recalc, RNA_id_pointer_create(), KS_Path::rna_path, RNA_path_resolve(), RNA_property_array_length(), RPT_WARNING, and WM_main_add_notifier().
Referenced by autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), delete_key_exec(), ED_autokeyframe_object(), ED_autokeyframe_pchan(), insert_key_exec(), move_camera(), pose_clear_transform_generic_exec(), poseAnim_mapping_autoKeyframe(), poselib_add_exec(), and poselib_keytag_pose().
struct KeyingSet* ANIM_builtin_keyingset_get_named (struct KeyingSet * prevKS, const char name[]) [read]
Definition at line 542 of file keyingsets.c.
References ListBase::first, KeyingSet::idname, KeyingSet::next, and NULL.
Referenced by ANIM_get_keyingset_for_autokeying(), autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), move_camera(), pose_flip_quats_exec(), and poselib_add_exec().
short ANIM_copy_driver (struct ReportList * reports, struct ID * id, const char rna_path[], int array_index, short flag)
short ANIM_driver_can_paste (void)
Definition at line 293 of file drivers.c.
References NULL.
Referenced by ui_but_menu().
short ANIM_get_keyframing_flags (struct Scene * scene, short incl_mode)
Definition at line 89 of file keyframing.c.
References INSERTKEY_MATRIX, INSERTKEY_NEEDED, INSERTKEY_REPLACE, INSERTKEY_XYZ2RGB, IS_AUTOKEY_FLAG, and IS_AUTOKEY_MODE.
Referenced by achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), add_default_keyingset_exec(), add_keyingset_button_exec(), ANIM_apply_keyingset(), autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), insert_action_keys(), insert_graph_keys(), insert_key_button_exec(), and ui_but_anim_autokey().
struct KeyingSet* ANIM_get_keyingset_for_autokeying (struct Scene * scene, const char * tranformKSName) [read]
Definition at line 695 of file keyingsets.c.
References Scene::active_keyingset, ANIM_builtin_keyingset_get_named(), ANIM_KS_AVAILABLE_ID, ANIM_scene_get_active_keyingset(), IS_AUTOKEY_FLAG, and NULL.
Referenced by object_clear_transform_generic_exec(), pose_clear_transform_generic_exec(), pose_paste_exec(), poseAnim_mapping_autoKeyframe(), poselib_keytag_pose(), snap_sel_to_curs(), and snap_sel_to_grid().
struct EnumPropertyItem* ANIM_keying_sets_enum_itemf (struct bContext * C, struct PointerRNA * ptr, struct PropertyRNA * prop, int * free) [read]
short ANIM_keyingset_context_ok_poll (struct bContext * C, struct KeyingSet * ks)
Definition at line 783 of file keyingsets.c.
References ANIM_keyingset_info_find_named(), KeyingSet::flag, KEYINGSET_ABSOLUTE, NULL, KeyingSetInfo::poll, and KeyingSet::typeinfo.
Referenced by ANIM_keying_sets_enum_itemf().
KeyingSetInfo* ANIM_keyingset_info_find_named (const char name[])
Definition at line 531 of file keyingsets.c.
References BLI_findstring(), and NULL.
Referenced by ANIM_keyingset_context_ok_poll(), and ANIM_validate_keyingset().
void ANIM_keyingset_info_register (KeyingSetInfo * ksi)
Definition at line 574 of file keyingsets.c.
References BKE_keyingset_add(), BLI_addtail(), BLI_strncpy(), KeyingSetInfo::description, KeyingSet::description, KeyingSetInfo::idname, KeyingSetInfo::keyingflag, KeyingSetInfo::name, and KeyingSet::typeinfo.
void ANIM_keyingset_info_unregister (struct Main * bmain, KeyingSetInfo * ksi)
Definition at line 594 of file keyingsets.c.
References BKE_keyingset_free(), BLI_freelinkN(), BLI_remlink(), BLI_remlink_safe(), ListBase::first, Scene::id, KeyingSetInfo::idname, Scene::keyingsets, MEM_freeN(), ID::next, KeyingSet::next, Main::scene, and KeyingSet::typeinfo.
void ANIM_keyingset_infos_exit (void)
Definition at line 623 of file keyingsets.c.
References BKE_keyingsets_free(), BLI_freelinkN(), ExtensionRNA::data, KeyingSetInfo::ext, ListBase::first, ExtensionRNA::free, KeyingSetInfo::next, and next.
Referenced by WM_exit_ext().
short ANIM_paste_driver (struct ReportList * reports, struct ID * id, const char rna_path[], int array_index, short flag)
void ANIM_relative_keyingset_add_source (ListBase * dsources, struct ID * id, struct StructRNA * srna, void * data)
Definition at line 827 of file keyingsets.c.
References BLI_addtail(), ELEM, MEM_callocN(), NULL, tRKS_DSource::ptr, RNA_id_pointer_create(), and RNA_pointer_create().
Referenced by autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), ED_autokeyframe_object(), ED_autokeyframe_pchan(), move_camera(), poseAnim_mapping_autoKeyframe(), and poselib_keytag_pose().
short ANIM_remove_driver (struct ReportList * reports, struct ID * id, const char rna_path[], int array_index, short flag)
struct KeyingSet* ANIM_scene_get_active_keyingset (struct Scene * scene) [read]
Definition at line 647 of file keyingsets.c.
References Scene::active_keyingset, BLI_findlink(), Scene::keyingsets, and NULL.
Referenced by ANIM_get_keyingset_for_autokeying(), autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), pose_select_same_keyingset(), and select_grouped_keyingset().
int ANIM_scene_get_keyingset_index (struct Scene * scene, struct KeyingSet * ks)
Definition at line 665 of file keyingsets.c.
References BLI_findindex(), Scene::keyingsets, and NULL.
short ANIM_validate_keyingset (struct bContext * C, ListBase * dsources, struct KeyingSet * ks)
Definition at line 860 of file keyingsets.c.
References ANIM_keyingset_info_find_named(), BKE_keyingset_free(), ListBase::first, KeyingSet::flag, KeyingSetInfo::iter, KEYINGSET_ABSOLUTE, MODIFYKEY_INVALID_CONTEXT, MODIFYKEY_MISSING_TYPEINFO, NULL, KeyingSet::paths, KeyingSetInfo::poll, RKS_ITER_overrides_list(), and KeyingSet::typeinfo.
Referenced by ANIM_apply_keyingset(), pose_select_same_keyingset(), and select_grouped_keyingset().
int autokeyframe_cfra_can_key (struct Scene * scene, struct ID * id)
Definition at line 1569 of file keyframing.c.
References ANIMFILTER_KEYS_LOCAL, CFRA, id_frame_has_keyframe(), IS_AUTOKEY_MODE, and IS_AUTOKEY_ON.
Referenced by autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), ED_autokeyframe_object(), ED_autokeyframe_pchan(), move_camera(), pose_clear_transform_generic_exec(), poseAnim_mapping_autoKeyframe(), poselib_keytag_pose(), and ui_but_anim_autokey().
short delete_keyframe (struct ReportList * reports, struct ID * id, struct bAction * act, const char group[], const char rna_path[], int array_index, float cfra, short flag)
int ED_autokeyframe_object (struct bContext * C, struct Scene * scene, struct Object * ob, struct KeyingSet * ks)
Definition at line 1742 of file keyframing.c.
References ANIM_apply_keyingset(), ANIM_relative_keyingset_add_source(), autokeyframe_cfra_can_key(), BLI_freelistN(), CFRA, FALSE, Object::id, MODIFYKEY_MODE_INSERT, NULL, and TRUE.
Referenced by object_clear_transform_generic_exec(), snap_sel_to_curs(), and snap_sel_to_grid().
int ED_autokeyframe_pchan (struct bContext * C, struct Scene * scene, struct Object * ob, struct bPoseChannel * pchan, struct KeyingSet * ks)
Definition at line 1764 of file keyframing.c.
References ANIM_apply_keyingset(), ANIM_relative_keyingset_add_source(), autokeyframe_cfra_can_key(), BLI_freelistN(), bPoseChannel::bone, BONE_UNKEYED, CFRA, FALSE, Bone::flag, Object::id, MODIFYKEY_MODE_INSERT, NULL, RNA_PoseBone, and TRUE.
Referenced by pose_flip_quats_exec(), pose_paste_exec(), snap_sel_to_curs(), and snap_sel_to_grid().
short fcurve_frame_has_keyframe (struct FCurve * fcu, float frame, short filter)
Definition at line 1595 of file keyframing.c.
References ANIMFILTER_KEYS_MUTED, FCurve::bezt, binarysearch_bezt_index(), ELEM, FCURVE_MUTED, FCurve::flag, i, NULL, FCurve::totvert, and tAnimCopybufItem::totvert.
Referenced by achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), action_frame_has_keyframe(), and ui_but_anim_flag().
short id_frame_has_keyframe (struct ID * id, float frame, short filter)
Definition at line 1708 of file keyframing.c.
References AnimData::action, action_frame_has_keyframe(), BKE_animdata_from_id(), GS, ID_OB, ID_SCE, ID::name, NULL, and object_frame_has_keyframe().
Referenced by autokeyframe_cfra_can_key(), draw_selected_name(), and object_frame_has_keyframe().
int insert_bezt_fcurve (struct FCurve * fcu, struct BezTriple * bezt, short flag)
Definition at line 217 of file keyframing.c.
References FCurve::bezt, binarysearch_bezt_index(), BezTriple::f1, BezTriple::f2, BezTriple::f3, FCurve::fpt, i, INSERTKEY_REPLACE, MEM_callocN(), MEM_freeN(), NULL, FCurve::totvert, tAnimCopybufItem::totvert, and BezTriple::vec.
Referenced by AnimationImporter::add_bezt(), insert_vert_fcurve(), and paste_animedit_keys_fcurve().
short insert_keyframe (struct ReportList * reports, struct ID * id, struct bAction * act, const char group[], const char rna_path[], int array_index, float cfra, short flag)
Definition at line 883 of file keyframing.c.
References BKE_animdata_from_id(), BKE_nla_tweakedit_remap(), BKE_reportf(), FCurve::color_mode, ELEM5, FCURVE_COLOR_AUTO_RGB, insert_keyframe_direct(), INSERTKEY_REPLACE, INSERTKEY_XYZ2RGB, ID::name, NLATIME_CONVERT_UNMAP, NULL, PROP_COLOR, PROP_COORDS, PROP_EULER, PROP_TRANSLATION, PROP_XYZ, RNA_id_pointer_create(), RNA_path_resolve(), RNA_property_array_length(), RNA_property_subtype(), RPT_ERROR, FCurve::totvert, verify_adt_action(), and verify_fcurve().
Referenced by ANIM_apply_keyingset(), autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), insert_action_keys(), insert_graph_keys(), insert_key_button_exec(), pyrna_struct_keyframe_insert(), ui_but_anim_autokey(), and KX_BlenderSceneConverter::WritePhysicsObjectToAnimationIpo().
short insert_keyframe_direct (struct ReportList * reports, struct PointerRNA ptr, struct PropertyRNA * prop, struct FCurve * fcu, float cfra, short flag)
Definition at line 762 of file keyframing.c.
References FCurve::array_index, BKE_report(), BKE_reportf(), PointerRNA::data, delete_fcurve_key(), FCURVE_DISCRETE_VALUES, FCURVE_INT_VALUES, fcurve_is_keyframable(), FCurve::flag, PointerRNA::id, insert_vert_fcurve(), INSERTKEY_MATRIX, INSERTKEY_NEEDED, KEYNEEDED_DELNEXT, KEYNEEDED_DELPREV, new_key_needed(), NULL, PROP_FLOAT, PROP_INT, FCurve::rna_path, RNA_path_resolve(), RNA_property_type(), RPT_ERROR, setting_get_rna_value(), FCurve::totvert, visualkey_can_use(), and visualkey_get_value().
Referenced by achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), insert_key_button_exec(), and insert_keyframe().
int insert_vert_fcurve (struct FCurve * fcu, float x, float y, short flag)
Definition at line 298 of file keyframing.c.
References FCurve::bezt, tAnimCopybufItem::bezt, BEZT_IPO_BEZ, BEZT_IPO_CONST, BEZT_IPO_LIN, calchandles_fcurve(), BezTriple::f1, BezTriple::f2, BezTriple::f3, FCURVE_DISCRETE_VALUES, FCURVE_INT_VALUES, FCurve::flag, BezTriple::h1, BezTriple::h2, insert_bezt_fcurve(), INSERTKEY_FAST, INSERTKEY_REPLACE, BezTriple::ipo, SELECT, tAnimCopybufItem::totvert, FCurve::totvert, and BezTriple::vec.
Referenced by clean_fcurve(), graphkeys_click_insert_exec(), insert_action_keys(), insert_graph_keys(), insert_keyframe_direct(), and sample_fcurve().
struct bAction* verify_adt_action (struct ID * id, short add) [read]
Definition at line 124 of file keyframing.c.
References AnimData::action, add_empty_action(), BKE_animdata_from_id(), BKE_id_add_animdata(), BLI_snprintf(), ID::name, and NULL.
Referenced by achannel_setting_slider_shapekey_cb(), AnimationImporter::add_bone_animation_sampled(), AnimationImporter::apply_matrix_curves(), ED_object_parent_set(), insert_keyframe(), AnimationImporter::translate_animation_OLD(), and AnimationImporter::translate_Animations().
struct FCurve* verify_driver_fcurve (struct ID * id, const char rna_path[], const int array_index, short add) [read]
Definition at line 81 of file drivers.c.
References add_fmodifier(), FCurve::array_index, BKE_animdata_from_id(), BKE_id_add_animdata(), BLI_addtail(), BLI_strdupn(), FCurve::driver, AnimData::drivers, ELEM, FCURVE_SELECTED, FCURVE_VISIBLE, FCurve::flag, FMODIFIER_TYPE_GENERATOR, list_find_fcurve(), MEM_callocN(), FCurve::modifiers, NULL, FCurve::rna_path, and strlen().
Referenced by ANIM_add_driver(), ANIM_copy_driver(), ANIM_paste_driver(), ANIM_remove_driver(), and ui_but_anim_expression_create().
struct FCurve* verify_fcurve (struct bAction * act, const char group[], const char rna_path[], const int array_index, short add) [read]
Definition at line 153 of file keyframing.c.
References action_groups_add_channel(), action_groups_add_new(), action_groups_find_named(), tAnimCopybufItem::array_index, FCurve::array_index, BLI_addtail(), BLI_strdupn(), bAction::curves, ELEM, FCURVE_ACTIVE, FCURVE_SELECTED, FCURVE_VISIBLE, ListBase::first, FCurve::flag, tAnimCopybufItem::grp, list_find_fcurve(), MEM_callocN(), NULL, FCurve::rna_path, and strlen().
Referenced by achannel_setting_slider_shapekey_cb(), delete_keyframe(), ED_object_parent_set(), and insert_keyframe().