Blender: GHOST_SystemCarbon.cpp File Reference
GHOST_SystemCarbon.cpp File Reference
GHOST API
#include <Carbon/Carbon.h>
#include <ApplicationServices/ApplicationServices.h>
#include "GHOST_SystemCarbon.h"
#include "GHOST_DisplayManagerCarbon.h"
#include "GHOST_EventKey.h"
#include "GHOST_EventButton.h"
#include "GHOST_EventCursor.h"
#include "GHOST_EventWheel.h"
#include "GHOST_TimerManager.h"
#include "GHOST_TimerTask.h"
#include "GHOST_WindowManager.h"
#include "GHOST_WindowCarbon.h"
#include "GHOST_NDOFManager.h"
#include "AssertMacros.h"
Defines
#define GHOST_KEY_SWITCH(mac, ghost) { case (mac): ghostKey = (ghost); break; }
#define FIRSTFILEBUFLG 512
Enumerations
enum { kEventClassBlender = 'blnd' }
enum { kEventBlenderNdofAxis = 1, kEventBlenderNdofButtons = 2 }
Functions
static GHOST_TButtonMask convertButton (EventMouseButton button)
static GHOST_TKey convertKey (int rawCode)
static unsigned char convertRomanToLatin (unsigned char ascii)
int GHOST_HACK_getFirstFile (char buf[FIRSTFILEBUFLG])
Variables
const EventTypeSpec kEvents []
static bool g_hasFirstFile = false
static char g_firstFileBuf [512]
Detailed Description
Definition in file GHOST_SystemCarbon.cpp.
Define Documentation
#define FIRSTFILEBUFLG 512
Definition at line 578 of file GHOST_SystemCarbon.cpp.
#define GHOST_KEY_SWITCH (mac, ghost) { case (mac): ghostKey = (ghost); break; }
Copyright (C) 2001 NaN Technologies B.V.
Author:
Maarten Gribnau
Date:
May 7, 2001
Definition at line 60 of file GHOST_SystemCarbon.cpp.
Enumeration Type Documentation
anonymous enum
Enumerator:
kEventClassBlender
Definition at line 63 of file GHOST_SystemCarbon.cpp.
anonymous enum
Enumerator:
kEventBlenderNdofAxis
kEventBlenderNdofButtons
Definition at line 67 of file GHOST_SystemCarbon.cpp.
Function Documentation
static GHOST_TButtonMask convertButton (EventMouseButton button) [static]
Definition at line 110 of file GHOST_SystemCarbon.cpp.
References GHOST_kButtonMaskLeft, GHOST_kButtonMaskMiddle, and GHOST_kButtonMaskRight.
Referenced by GHOST_SystemCarbon::handleMouseDown(), and GHOST_SystemCarbon::handleMouseEvent().
static GHOST_TKey convertKey (int rawCode) [static]
Definition at line 123 of file GHOST_SystemCarbon.cpp.
References GHOST_kKey0, GHOST_kKey1, GHOST_kKey2, GHOST_kKey3, GHOST_kKey4, GHOST_kKey5, GHOST_kKey6, GHOST_kKey7, GHOST_kKey8, GHOST_kKey9, GHOST_kKeyA, GHOST_kKeyAccentGrave, GHOST_kKeyBackslash, GHOST_kKeyBackSpace, GHOST_kKeyComma, GHOST_kKeyDelete, GHOST_kKeyDownArrow, GHOST_kKeyDownPage, GHOST_kKeyEnd, GHOST_kKeyEnter, GHOST_kKeyEqual, GHOST_kKeyEsc, GHOST_kKeyF1, GHOST_kKeyF10, GHOST_kKeyF11, GHOST_kKeyF12, GHOST_kKeyF2, GHOST_kKeyF3, GHOST_kKeyF4, GHOST_kKeyF5, GHOST_kKeyF6, GHOST_kKeyF7, GHOST_kKeyF8, GHOST_kKeyF9, GHOST_kKeyHome, GHOST_kKeyLeftArrow, GHOST_kKeyLeftBracket, GHOST_kKeyMinus, GHOST_kKeyNumpad0, GHOST_kKeyNumpad1, GHOST_kKeyNumpad2, GHOST_kKeyNumpad3, GHOST_kKeyNumpad4, GHOST_kKeyNumpad5, GHOST_kKeyNumpad6, GHOST_kKeyNumpad7, GHOST_kKeyNumpad8, GHOST_kKeyNumpad9, GHOST_kKeyNumpadAsterisk, GHOST_kKeyNumpadEnter, GHOST_kKeyNumpadMinus, GHOST_kKeyNumpadPeriod, GHOST_kKeyNumpadPlus, GHOST_kKeyNumpadSlash, GHOST_kKeyPeriod, GHOST_kKeyQuote, GHOST_kKeyRightArrow, GHOST_kKeyRightBracket, GHOST_kKeySemicolon, GHOST_kKeySlash, GHOST_kKeySpace, GHOST_kKeyTab, GHOST_kKeyUnknown, GHOST_kKeyUpArrow, and GHOST_kKeyUpPage.
Referenced by GHOST_SystemCarbon::handleKeyEvent().
static unsigned char convertRomanToLatin (unsigned char ascii) [static]
Definition at line 233 of file GHOST_SystemCarbon.cpp.
Referenced by GHOST_SystemCarbon::handleKeyEvent().
int GHOST_HACK_getFirstFile (char buf[FIRSTFILEBUFLG])
Definition at line 582 of file GHOST_SystemCarbon.cpp.
References g_firstFileBuf, and g_hasFirstFile.
Variable Documentation
char g_firstFileBuf[512] [static]
Definition at line 580 of file GHOST_SystemCarbon.cpp.
Referenced by GHOST_HACK_getFirstFile(), and GHOST_SystemCarbon::sAEHandlerOpenDocs().
bool g_hasFirstFile = false [static]
Definition at line 579 of file GHOST_SystemCarbon.cpp.
Referenced by GHOST_HACK_getFirstFile(), and GHOST_SystemCarbon::sAEHandlerOpenDocs().
const EventTypeSpec kEvents[]
Definition at line 72 of file GHOST_SystemCarbon.cpp.
Referenced by GHOST_SystemCarbon::init().