Blender: MOD_mirror.c File Reference
MOD_mirror.c File Reference
modifiers
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "BLI_math.h"
#include "BLI_array.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_mesh.h"
#include "BKE_modifier.h"
#include "BKE_deform.h"
#include "BKE_utildefines.h"
#include "BKE_tessmesh.h"
#include "MEM_guardedalloc.h"
#include "depsgraph_private.h"
Functions
static void initData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static void foreachObjectLink (ModifierData *md, Object *ob, void(*walk)(void *userData, Object *ob, Object **obpoin), void *userData)
static void updateDepgraph (ModifierData *md, DagForest *forest, struct Scene *UNUSED(scene), Object *UNUSED(ob), DagNode *obNode)
static DerivedMesh * doMirrorOnAxis (MirrorModifierData *mmd, Object *ob, DerivedMesh *dm, int axis)
static DerivedMesh * mirrorModifier__doMirror (MirrorModifierData *mmd, Object *ob, DerivedMesh *dm)
static DerivedMesh * applyModifier (ModifierData *md, Object *ob, DerivedMesh *derivedData, int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
static DerivedMesh * applyModifierEM (ModifierData *md, Object *ob, struct BMEditMesh *UNUSED(editData), DerivedMesh *derivedData)
Variables
ModifierTypeInfo modifierType_Mirror
Detailed Description
Definition in file MOD_mirror.c.
Function Documentation
static DerivedMesh* applyModifier (ModifierData * md, Object * ob, DerivedMesh * derivedData, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 322 of file MOD_mirror.c.
References CDDM_calc_normals(), and mirrorModifier__doMirror().
Referenced by applyModifierEM().
static DerivedMesh* applyModifierEM (ModifierData * md, Object * ob, struct BMEditMesh * UNUSEDeditData, DerivedMesh * derivedData) [static]
Definition at line 338 of file MOD_mirror.c.
References applyModifier().
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 61 of file MOD_mirror.c.
References MirrorModifierData::flag, MirrorModifierData::mirror_ob, and MirrorModifierData::tolerance.
static DerivedMesh* doMirrorOnAxis (MirrorModifierData * mmd, Object * ob, DerivedMesh * dm, int axis) [static]
Definition at line 95 of file MOD_mirror.c.
References CD_MDEFORMVERT, CD_MEDGE, CD_MLOOPUV, CD_MPOLY, CD_MVERT, CD_SHAPEKEY, CDDM_from_template(), CDDM_get_edges(), CDDM_get_loops(), CDDM_get_polys(), CDDM_get_verts(), CDDM_merge_verts(), MVert::co, DerivedMesh::copyEdgeArray, DerivedMesh::copyLoopArray, DerivedMesh::copyPolyArray, DerivedMesh::copyVertArray, cos(), CustomData_get_layer(), CustomData_get_layer_n(), CustomData_has_layer(), CustomData_number_of_layers(), defgroup_flip_map(), defvert_flip(), defvert_flip_merged(), DM_copy_edge_data(), DM_copy_loop_data(), DM_copy_poly_data(), DM_copy_vert_data(), Mesh::dvert, MLoop::e, DerivedMesh::edgeData, FALSE, MirrorModifierData::flag, DerivedMesh::getNumEdges, DerivedMesh::getNumLoops, DerivedMesh::getNumPolys, DerivedMesh::getNumVerts, i, invert_m4_m4(), len_squared_v3v3(), DerivedMesh::loopData, MPoly::loopstart, MEM_freeN(), MEM_mallocN(), MirrorModifierData::mirror_ob, MOD_MIR_MIRROR_U, MOD_MIR_MIRROR_V, MOD_MIR_NO_MERGE, MOD_MIR_VGROUP, mul_m4_v3(), mult_m4_m4m4(), NULL, DerivedMesh::numVertData, Object::obmat, DerivedMesh::polyData, MirrorModifierData::tolerance, MPoly::totloop, TRUE, unit_m4(), UNLIKELY, MLoopUV::uv, MLoop::v, MEdge::v1, MEdge::v2, and DerivedMesh::vertData.
Referenced by mirrorModifier__doMirror().
static void foreachObjectLink (ModifierData * md, Object * ob, void(*)(void *userData, Object *ob, Object **obpoin) walk, void * userData) [static]
Definition at line 71 of file MOD_mirror.c.
References MirrorModifierData::mirror_ob.
static void initData (ModifierData * md) [static]
Definition at line 52 of file MOD_mirror.c.
References MirrorModifierData::flag, MirrorModifierData::mirror_ob, MOD_MIR_AXIS_X, MOD_MIR_VGROUP, NULL, and MirrorModifierData::tolerance.
static DerivedMesh* mirrorModifier__doMirror (MirrorModifierData * mmd, Object * ob, DerivedMesh * dm) [static]
Definition at line 299 of file MOD_mirror.c.
References doMirrorOnAxis(), MirrorModifierData::flag, MOD_MIR_AXIS_X, MOD_MIR_AXIS_Y, MOD_MIR_AXIS_Z, and DerivedMesh::release.
Referenced by applyModifier().
static void updateDepgraph (ModifierData * md, DagForest * forest, struct Scene * UNUSEDscene, Object * UNUSEDob, DagNode * obNode) [static]
Definition at line 80 of file MOD_mirror.c.
References dag_add_relation(), dag_get_node(), DAG_RL_DATA_DATA, DAG_RL_OB_DATA, and MirrorModifierData::mirror_ob.
Variable Documentation
ModifierTypeInfo modifierType_Mirror
Initial value:
 {
                  "Mirror",
            "MirrorModifierData",
            sizeof(MirrorModifierData),
                  eModifierTypeType_Constructive,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_SupportsMapping
                            | eModifierTypeFlag_SupportsEditmode
                            | eModifierTypeFlag_EnableInEditmode
                            | eModifierTypeFlag_AcceptsCVs,
              copyData,
           NULL,
        NULL,
         NULL,
      NULL,
         applyModifier,
       applyModifierEM,
              initData,
      NULL,
              NULL,
            NULL,
        updateDepgraph,
         NULL,
        NULL,
     foreachObjectLink,
         NULL,
        NULL,
}
Definition at line 346 of file MOD_mirror.c.