Blender: editmesh_add.c File Reference
editmesh_add.c File Reference
mesh
#include "DNA_mesh_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "RNA_define.h"
#include "RNA_access.h"
#include "BLI_math.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_library.h"
#include "BKE_tessmesh.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_mesh.h"
#include "ED_screen.h"
#include "ED_object.h"
#include "mesh_intern.h"
Functions
static float new_primitive_matrix (bContext *C, float *loc, float *rot, float primmat[][4])
static void make_prim_init (bContext *C, const char *idname, float *dia, float mat[][4], int *state, float *loc, float *rot, unsigned int layer)
static void make_prim_finish (bContext *C, int *state, int enter_editmode)
static int add_primitive_plane_exec (bContext *C, wmOperator *op)
void MESH_OT_primitive_plane_add (wmOperatorType *ot)
static int add_primitive_cube_exec (bContext *C, wmOperator *op)
void MESH_OT_primitive_cube_add (wmOperatorType *ot)
static int add_primitive_circle_exec (bContext *C, wmOperator *op)
void MESH_OT_primitive_circle_add (wmOperatorType *ot)
static int add_primitive_cylinder_exec (bContext *C, wmOperator *op)
void MESH_OT_primitive_cylinder_add (wmOperatorType *ot)
static int add_primitive_cone_exec (bContext *C, wmOperator *op)
void MESH_OT_primitive_cone_add (wmOperatorType *ot)
static int add_primitive_grid_exec (bContext *C, wmOperator *op)
void MESH_OT_primitive_grid_add (wmOperatorType *ot)
static int add_primitive_monkey_exec (bContext *C, wmOperator *op)
void MESH_OT_primitive_monkey_add (wmOperatorType *ot)
static int add_primitive_uvsphere_exec (bContext *C, wmOperator *op)
void MESH_OT_primitive_uv_sphere_add (wmOperatorType *ot)
static int add_primitive_icosphere_exec (bContext *C, wmOperator *op)
void MESH_OT_primitive_ico_sphere_add (wmOperatorType *ot)
Variables
static const EnumPropertyItem fill_type_items []
Detailed Description
Definition in file editmesh_add.c.
Function Documentation
static int add_primitive_circle_exec (bContext * C, wmOperator * op) [static]
Definition at line 222 of file editmesh_add.c.
References CTX_data_edit_object(), Object::data, ED_object_add_generic_get_opts(), EDBM_op_call_and_selectf(), Mesh::edit_btmesh, make_prim_finish(), make_prim_init(), Main::mat, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), RNA_float_get(), RNA_int_get(), rot, and state.
Referenced by MESH_OT_primitive_circle_add().
static int add_primitive_cone_exec (bContext * C, wmOperator * op) [static]
Definition at line 346 of file editmesh_add.c.
References CTX_data_edit_object(), Object::data, ED_object_add_generic_get_opts(), EDBM_op_call_and_selectf(), Mesh::edit_btmesh, make_prim_finish(), make_prim_init(), Main::mat, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), RNA_float_get(), RNA_int_get(), rot, and state.
Referenced by MESH_OT_primitive_cone_add().
static int add_primitive_cube_exec (bContext * C, wmOperator * op) [static]
Definition at line 171 of file editmesh_add.c.
References CTX_data_edit_object(), Object::data, ED_object_add_generic_get_opts(), EDBM_op_call_and_selectf(), Mesh::edit_btmesh, make_prim_finish(), make_prim_init(), Main::mat, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, rot, and state.
Referenced by MESH_OT_primitive_cube_add().
static int add_primitive_cylinder_exec (bContext * C, wmOperator * op) [static]
Definition at line 281 of file editmesh_add.c.
References CTX_data_edit_object(), Object::data, ED_object_add_generic_get_opts(), EDBM_op_call_and_selectf(), Mesh::edit_btmesh, make_prim_finish(), make_prim_init(), Main::mat, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), RNA_float_get(), RNA_int_get(), rot, and state.
Referenced by MESH_OT_primitive_cylinder_add().
static int add_primitive_grid_exec (bContext * C, wmOperator * op) [static]
Definition at line 410 of file editmesh_add.c.
References CTX_data_edit_object(), Object::data, ED_object_add_generic_get_opts(), EDBM_op_call_and_selectf(), Mesh::edit_btmesh, make_prim_finish(), make_prim_init(), Main::mat, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get(), RNA_int_get(), rot, and state.
Referenced by MESH_OT_primitive_grid_add().
static int add_primitive_icosphere_exec (bContext * C, wmOperator * op) [static]
Definition at line 568 of file editmesh_add.c.
References CTX_data_edit_object(), Object::data, ED_object_add_generic_get_opts(), EDBM_op_call_and_selectf(), Mesh::edit_btmesh, make_prim_finish(), make_prim_init(), Main::mat, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get(), RNA_int_get(), rot, and state.
Referenced by MESH_OT_primitive_ico_sphere_add().
static int add_primitive_monkey_exec (bContext * C, wmOperator * op) [static]
Definition at line 466 of file editmesh_add.c.
References CTX_data_edit_object(), Object::data, ED_object_add_generic_get_opts(), EDBM_op_call_and_selectf(), Mesh::edit_btmesh, M_PI, make_prim_finish(), make_prim_init(), Main::mat, OPERATOR_CANCELLED, OPERATOR_FINISHED, rot, and state.
Referenced by MESH_OT_primitive_monkey_add().
static int add_primitive_plane_exec (bContext * C, wmOperator * op) [static]
Definition at line 125 of file editmesh_add.c.
References CTX_data_edit_object(), Object::data, ED_object_add_generic_get_opts(), EDBM_op_call_and_selectf(), Mesh::edit_btmesh, make_prim_finish(), make_prim_init(), Main::mat, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, rot, and state.
Referenced by MESH_OT_primitive_plane_add().
static int add_primitive_uvsphere_exec (bContext * C, wmOperator * op) [static]
Definition at line 512 of file editmesh_add.c.
References CTX_data_edit_object(), Object::data, ED_object_add_generic_get_opts(), EDBM_op_call_and_selectf(), Mesh::edit_btmesh, make_prim_finish(), make_prim_init(), Main::mat, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get(), RNA_int_get(), rot, and state.
Referenced by MESH_OT_primitive_uv_sphere_add().
static void make_prim_finish (bContext * C, int * state, int enter_editmode) [static]
Definition at line 107 of file editmesh_add.c.
References BMEdit_FromObject(), CTX_data_edit_object(), ED_object_exit_editmode(), EDBM_selectmode_flush_ex(), EDBM_update_generic(), EM_FREEDATA, NC_OBJECT, ND_DRAW, SCE_SELECT_VERTEX, TRUE, and WM_event_add_notifier().
Referenced by add_primitive_circle_exec(), add_primitive_cone_exec(), add_primitive_cube_exec(), add_primitive_cylinder_exec(), add_primitive_grid_exec(), add_primitive_icosphere_exec(), add_primitive_monkey_exec(), add_primitive_plane_exec(), and add_primitive_uvsphere_exec().
static void make_prim_init (bContext * C, const char * idname, float * dia, float mat[][4], int * state, float * loc, float * rot, unsigned int layer) [static]
Definition at line 86 of file editmesh_add.c.
References CTX_data_edit_object(), ED_object_add_type(), ED_object_enter_editmode(), EM_DO_UNDO, EM_IGNORE_LAYER, FALSE, new_primitive_matrix(), NULL, OB_MESH, rename_id(), and Object::type.
Referenced by add_primitive_circle_exec(), add_primitive_cone_exec(), add_primitive_cube_exec(), add_primitive_cylinder_exec(), add_primitive_grid_exec(), add_primitive_icosphere_exec(), add_primitive_monkey_exec(), add_primitive_plane_exec(), and add_primitive_uvsphere_exec().
void MESH_OT_primitive_circle_add (wmOperatorType * ot)
Definition at line 255 of file editmesh_add.c.
References add_primitive_circle_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_DISTANCE, RNA_def_enum(), RNA_def_float(), RNA_def_int(), RNA_def_property_subtype(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_cone_add (wmOperatorType * ot)
Definition at line 380 of file editmesh_add.c.
References add_primitive_cone_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_DISTANCE, RNA_def_enum(), RNA_def_float(), RNA_def_int(), RNA_def_property_subtype(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_cube_add (wmOperatorType * ot)
Definition at line 198 of file editmesh_add.c.
References add_primitive_cube_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_cylinder_add (wmOperatorType * ot)
Definition at line 318 of file editmesh_add.c.
References add_primitive_cylinder_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_DISTANCE, RNA_def_enum(), RNA_def_float(), RNA_def_int(), RNA_def_property_subtype(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_grid_add (wmOperatorType * ot)
Definition at line 440 of file editmesh_add.c.
References add_primitive_grid_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_DISTANCE, RNA_def_float(), RNA_def_int(), RNA_def_property_subtype(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_ico_sphere_add (wmOperatorType * ot)
Definition at line 599 of file editmesh_add.c.
References add_primitive_icosphere_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_DISTANCE, RNA_def_float(), RNA_def_int(), RNA_def_property_subtype(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_monkey_add (wmOperatorType * ot)
Definition at line 494 of file editmesh_add.c.
References add_primitive_monkey_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_plane_add (wmOperatorType * ot)
Definition at line 153 of file editmesh_add.c.
References add_primitive_plane_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_primitive_uv_sphere_add (wmOperatorType * ot)
Definition at line 542 of file editmesh_add.c.
References add_primitive_uvsphere_exec(), wmOperatorType::description, ED_object_add_generic_invoke(), ED_object_add_generic_props(), ED_operator_scene_editable(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_DISTANCE, RNA_def_float(), RNA_def_int(), RNA_def_property_subtype(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
static float new_primitive_matrix (bContext * C, float * loc, float * rot, float primmat[][4]) [static]
Definition at line 58 of file editmesh_add.c.
References copy_m3_m4(), copy_m4_m3(), copy_v3_v3(), CTX_data_edit_object(), CTX_wm_view3d(), eul_to_mat3(), View3D::grid, invert_m3(), invert_m3_m3(), Main::mat, mul_m3_m3m3(), mul_m3_v3(), Object::obmat, sub_v3_v3(), and unit_m4().
Referenced by make_prim_init().
Variable Documentation
const EnumPropertyItem fill_type_items[] [static]
Initial value:
 {
    {0, "NOTHING", 0, "Nothing", "Don't fill at all"},
    {1, "NGON", 0, "Ngon", "Use ngons"},
    {2, "TRIFAN", 0, "Triangle Fan", "Use triangle fans"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 216 of file editmesh_add.c.