Blender: ED_object.h File Reference
ED_object.h File Reference
Editors
Defines
#define EM_FREEDATA 1
#define EM_FREEUNDO 2
#define EM_WAITCURSOR 4
#define EM_DO_UNDO 8
#define EM_IGNORE_LAYER 16
Typedefs
typedef enum eParentType eParentType
Enumerations
enum eParentType {
PAR_OBJECT, PAR_ARMATURE, PAR_ARMATURE_NAME, PAR_ARMATURE_ENVELOPE,
PAR_ARMATURE_AUTO, PAR_BONE, PAR_CURVE, PAR_FOLLOW,
PAR_PATH_CONST, PAR_LATTICE, PAR_VERTEX, PAR_TRIA
}
enum { MODIFIER_APPLY_DATA = 1, MODIFIER_APPLY_SHAPE }
Functions
struct Object * ED_object_context (struct bContext *C)
struct Object * ED_object_active_context (struct bContext *C)
void ED_operatortypes_object (void)
void ED_operatormacros_object (void)
void ED_keymap_object (struct wmKeyConfig *keyconf)
int ED_object_parent_set (struct ReportList *reports, struct Main *bmain, struct Scene *scene, struct Object *ob, struct Object *par, int partype)
void ED_object_parent_clear (struct bContext *C, int type)
void ED_object_generic_keymap (struct wmKeyConfig *keyconf, struct wmKeyMap *keymap, int do_pet)
void ED_base_object_select (struct Base *base, short mode)
void ED_base_object_activate (struct bContext *C, struct Base *base)
void ED_base_object_free_and_unlink (struct Main *bmain, struct Scene *scene, struct Base *base)
struct Base * ED_object_add_duplicate (struct Main *bmain, struct Scene *scene, struct Base *base, int dupflag)
void ED_object_parent (struct Object *ob, struct Object *parent, int type, const char *substr)
void ED_object_toggle_modes (struct bContext *C, int mode)
void ED_object_exit_editmode (struct bContext *C, int flag)
void ED_object_enter_editmode (struct bContext *C, int flag)
void ED_object_location_from_view (struct bContext *C, float *loc)
void ED_object_rotation_from_view (struct bContext *C, float *rot)
void ED_object_base_init_transform (struct bContext *C, struct Base *base, float *loc, float *rot)
float ED_object_new_primitive_matrix (struct bContext *C, struct Object *editob, float *loc, float *rot, float primmat[][4])
void ED_object_add_generic_props (struct wmOperatorType *ot, int do_editmode)
int ED_object_add_generic_invoke (struct bContext *C, struct wmOperator *op, struct wmEvent *event)
int ED_object_add_generic_get_opts (struct bContext *C, struct wmOperator *op, float *loc, float *rot, int *enter_editmode, unsigned int *layer, int *is_view_aligned)
struct Object * ED_object_add_type (struct bContext *C, int type, float *loc, float *rot, int enter_editmode, unsigned int layer)
void ED_object_single_users (struct Main *bmain, struct Scene *scene, int full)
void ED_object_single_user (struct Scene *scene, struct Object *ob)
void ED_objects_clear_paths (struct bContext *C)
void ED_objects_recalculate_paths (struct bContext *C, struct Scene *scene)
struct ListBase * get_active_constraints (struct Object *ob)
struct ListBase * get_constraint_lb (struct Object *ob, struct bConstraint *con, struct bPoseChannel **pchan_r)
struct bConstraint * get_active_constraint (struct Object *ob)
void object_test_constraints (struct Object *ob)
void ED_object_constraint_set_active (struct Object *ob, struct bConstraint *con)
void ED_object_constraint_update (struct Object *ob)
void ED_object_constraint_dependency_update (struct Main *bmain, struct Scene *scene, struct Object *ob)
int mouse_lattice (struct bContext *C, const int mval[2], int extend)
void undo_push_lattice (struct bContext *C, const char *name)
void ED_setflagsLatt (struct Object *obedit, int flag)
struct ModifierData * ED_object_modifier_add (struct ReportList *reports, struct Main *bmain, struct Scene *scene, struct Object *ob, const char *name, int type)
int ED_object_modifier_remove (struct ReportList *reports, struct Main *bmain, struct Scene *scene, struct Object *ob, struct ModifierData *md)
void ED_object_modifier_clear (struct Main *bmain, struct Scene *scene, struct Object *ob)
int ED_object_modifier_move_down (struct ReportList *reports, struct Object *ob, struct ModifierData *md)
int ED_object_modifier_move_up (struct ReportList *reports, struct Object *ob, struct ModifierData *md)
int ED_object_modifier_convert (struct ReportList *reports, struct Main *bmain, struct Scene *scene, struct Object *ob, struct ModifierData *md)
int ED_object_modifier_apply (struct ReportList *reports, struct Scene *scene, struct Object *ob, struct ModifierData *md, int mode)
int ED_object_modifier_copy (struct ReportList *reports, struct Object *ob, struct ModifierData *md)
Variables
struct EnumPropertyItem prop_clear_parent_types []
struct EnumPropertyItem prop_make_parent_types []
Detailed Description
Definition in file ED_object.h.
Define Documentation
#define EM_DO_UNDO 8
Definition at line 118 of file ED_object.h.
Referenced by createRepresentation(), ED_object_add_type(), ED_object_enter_editmode(), ED_object_exit_editmode(), ED_screen_set_scene(), join_curve_exec(), join_mesh_exec(), make_prim_init(), object_delete_cb(), posemode_exec(), tree_element_active_pose(), and WM_write_file().
#define EM_FREEDATA 1
Definition at line 115 of file ED_object.h.
Referenced by createRepresentation(), curvesurf_prim_add(), ED_object_add_type(), ED_object_exit_editmode(), ED_screen_set_scene(), edbm_sort_faces_exec(), editmode_toggle_exec(), effector_add_type(), join_curve_exec(), join_mesh_exec(), make_prim_finish(), object_armature_add_exec(), object_delete_cb(), object_metaball_add_exec(), posemode_exec(), and tree_element_active_pose().
#define EM_FREEUNDO 2
Definition at line 116 of file ED_object.h.
Referenced by ED_object_add_type(), editmode_toggle_exec(), object_delete_cb(), and tree_element_active_pose().
#define EM_IGNORE_LAYER 16
Definition at line 119 of file ED_object.h.
Referenced by createRepresentation(), ED_object_add_type(), ED_object_enter_editmode(), and make_prim_init().
#define EM_WAITCURSOR 4
Definition at line 117 of file ED_object.h.
Referenced by ED_object_add_type(), ED_object_enter_editmode(), ED_object_exit_editmode(), editmode_toggle_exec(), join_curve_exec(), join_mesh_exec(), object_delete_cb(), and tree_element_active_pose().
Typedef Documentation
typedef enum eParentType eParentType
Enumeration Type Documentation
anonymous enum
Enumerator:
MODIFIER_APPLY_DATA
MODIFIER_APPLY_SHAPE
Definition at line 163 of file ED_object.h.
enum eParentType
Enumerator:
PAR_OBJECT
PAR_ARMATURE
PAR_ARMATURE_NAME
PAR_ARMATURE_ENVELOPE
PAR_ARMATURE_AUTO
PAR_BONE
PAR_CURVE
PAR_FOLLOW
PAR_PATH_CONST
PAR_LATTICE
PAR_VERTEX
PAR_TRIA
Definition at line 69 of file ED_object.h.
Function Documentation
void ED_base_object_activate (struct bContext * C, struct Base * base)
Definition at line 103 of file object_select.c.
References BASACT, CTX_data_scene(), NC_SCENE, ND_OB_ACTIVE, NULL, and WM_event_add_notifier().
Referenced by add_named_exec(), convert_exec(), duplicate_exec(), ed_marker_select(), ED_object_add_type(), mouse_select(), object_hide_view_set_exec(), object_select_menu_exec(), and select_grouped_parent().
void ED_base_object_free_and_unlink (struct Main * bmain, struct Scene * scene, struct Base * base)
Definition at line 890 of file object_add.c.
References Scene::basact, Scene::base, BLI_remlink(), DAG_id_type_tag(), free_libblock_us(), ID_OB, MEM_freeN(), NULL, Base::object, and Main::object.
Referenced by convert_exec(), join_armature_exec(), join_curve_exec(), join_mesh_exec(), object_delete_cb(), and object_delete_exec().
void ED_base_object_select (struct Base * base, short mode)
Definition at line 88 of file object_select.c.
References BA_DESELECT, BA_SELECT, Object::flag, Base::flag, OB_RESTRICT_SELECT, Base::object, Object::restrictflag, and SELECT.
Referenced by deselectall_except(), do_lasso_select_objects(), do_object_pose_box_select(), do_outliner_item_activate(), duplicate_exec(), ed_marker_select(), mesh_separate_selected(), mouse_select(), object_deselect_all_visible(), object_select_all_exec(), object_select_by_layer_exec(), object_select_by_type_exec(), object_select_grouped_exec(), object_select_linked_exec(), object_select_menu_exec(), object_select_mirror_exec(), object_select_random_exec(), object_select_same_group_exec(), object_toggle_visibility_cb(), parent_clear_invoke(), parent_drop_invoke(), restrictbutton_gr_restrict_flag(), restrictbutton_sel_cb(), restrictbutton_view_cb(), select_grouped_children(), select_grouped_color(), select_grouped_gameprops(), select_grouped_group(), select_grouped_index_object(), select_grouped_keyingset(), select_grouped_layer(), select_grouped_object_hooks(), select_grouped_parent(), select_grouped_siblings(), select_grouped_type(), separate_exec(), and view3d_circle_select_exec().
void ED_keymap_object (struct wmKeyConfig * keyconf)
Definition at line 260 of file object_ops.c.
References AKEY, CKEY, DELKEY, DKEY, ED_object_generic_keymap(), ED_operator_editlattice(), FALSE, GKEY, HKEY, i, IKEY, JKEY, KM_ALT, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTBRACKETKEY, LKEY, MKEY, OB_MODE_EDIT, OB_MODE_POSE, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, object_mode_poll(), OKEY, PKEY, wmKeyMap::poll, wmKeyMapItem::ptr, RIGHTBRACKETKEY, RKEY, RNA_boolean_set(), RNA_enum_set(), RNA_enum_set_identifier(), RNA_int_set(), SEL_INVERT, SEL_TOGGLE, SKEY, TABKEY, TKEY, TRUE, UKEY, VKEY, WKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), WM_keymap_verify_item(), XKEY, and ZEROKEY.
Referenced by ED_spacetypes_keymap().
struct Object* ED_object_active_context (struct bContext * C) [read]
Definition at line 121 of file object_edit.c.
References CTX_data_active_object(), ED_object_context(), and NULL.
Referenced by childof_clear_inverse_exec(), childof_set_inverse_exec(), constraint_move_down_exec(), constraint_move_up_exec(), ED_operator_object_active(), ED_operator_object_active_editable(), ED_operator_object_active_editable_font(), ED_operator_object_active_editable_mesh(), ED_operator_outliner_active_no_editobject(), edit_constraint_invoke_properties(), edit_constraint_poll_generic(), edit_modifier_poll_generic(), edit_object_property_get(), explode_refresh_exec(), game_physics_copy_exec(), game_property_copy_exec(), gameprops_itemf(), get_new_constraint_target(), limitdistance_reset_exec(), logicbricks_copy_exec(), make_links_data_exec(), make_proxy_exec(), make_proxy_invoke(), meshdeform_bind_exec(), modifier_add_exec(), modifier_add_itemf(), modifier_apply_exec(), modifier_convert_exec(), modifier_copy_exec(), modifier_move_down_exec(), modifier_move_up_exec(), modifier_remove_exec(), multires_base_apply_exec(), multires_external_pack_exec(), multires_external_save_exec(), multires_external_save_invoke(), multires_higher_levels_delete_exec(), multires_reshape_exec(), multires_subdivide_exec(), navmesh_clear_exec(), navmesh_obmode_data_poll(), navmesh_obmode_poll(), navmesh_reset_exec(), object_constraint_add_exec(), object_constraint_copy_exec(), objectsolver_clear_inverse_exec(), objectsolver_set_inverse_exec(), ocean_bake_exec(), parent_noinv_set_exec(), parent_set_exec(), parent_set_invoke(), pose_constraint_add_exec(), proxy_group_object_itemf(), stretchto_reset_exec(), and track_set_exec().
struct Base* ED_object_add_duplicate (struct Main * bmain, struct Scene * scene, struct Base * base, int dupflag) [read]
Definition at line 1844 of file object_add.c.
References clear_id_newpoins(), clear_sca_new_poins(), DAG_scene_sort(), Object::data, ED_render_id_flush_update(), NULL, Base::object, object_add_duplicate_internal(), object_relink(), and set_sca_new_poins_ob().
Referenced by mesh_separate_selected(), separate_armature_exec(), and separate_exec().
int ED_object_add_generic_get_opts (struct bContext * C, struct wmOperator * op, float * loc, float * rot, int * enter_editmode, unsigned int * layer, int * is_view_aligned)
Definition at line 252 of file object_add.c.
References BKE_report(), CTX_data_scene(), CTX_wm_view3d(), ED_object_rotation_from_view(), FALSE, View3D::lay, Scene::layact, View3D::localvd, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_boolean_get_array(), RNA_boolean_set(), RNA_float_get_array(), RNA_float_set_array(), RNA_struct_find_property(), RNA_struct_property_is_set(), RPT_ERROR, TRUE, and USER_ADD_VIEWALIGNED.
Referenced by add_primitive_circle_exec(), add_primitive_cone_exec(), add_primitive_cube_exec(), add_primitive_cylinder_exec(), add_primitive_grid_exec(), add_primitive_icosphere_exec(), add_primitive_monkey_exec(), add_primitive_plane_exec(), add_primitive_uvsphere_exec(), curvesurf_prim_add(), effector_add_type(), group_instance_add_exec(), object_add_exec(), object_add_text_exec(), object_armature_add_exec(), object_camera_add_exec(), object_lamp_add_exec(), object_metaball_add_exec(), and object_speaker_add_exec().
int ED_object_add_generic_invoke (struct bContext * C, struct wmOperator * op, struct wmEvent * event)
Referenced by CURVE_OT_primitive_bezier_circle_add(), CURVE_OT_primitive_bezier_curve_add(), CURVE_OT_primitive_nurbs_circle_add(), CURVE_OT_primitive_nurbs_curve_add(), CURVE_OT_primitive_nurbs_path_add(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cube_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_monkey_add(), MESH_OT_primitive_plane_add(), MESH_OT_primitive_uv_sphere_add(), OBJECT_OT_add(), OBJECT_OT_armature_add(), OBJECT_OT_text_add(), SURFACE_OT_primitive_nurbs_surface_circle_add(), SURFACE_OT_primitive_nurbs_surface_curve_add(), SURFACE_OT_primitive_nurbs_surface_cylinder_add(), SURFACE_OT_primitive_nurbs_surface_sphere_add(), SURFACE_OT_primitive_nurbs_surface_surface_add(), and SURFACE_OT_primitive_nurbs_surface_torus_add().
void ED_object_add_generic_props (struct wmOperatorType * ot, int do_editmode)
Definition at line 188 of file object_add.c.
References FLT_MAX, M_PI, NULL, PROP_HIDDEN, PROP_SKIP_SAVE, RNA_def_boolean(), RNA_def_boolean_layer_member(), RNA_def_float_rotation(), RNA_def_float_vector_xyz(), RNA_def_property_flag(), RNA_def_property_update_runtime(), wmOperatorType::srna, and view_align_update().
Referenced by CURVE_OT_primitive_bezier_circle_add(), CURVE_OT_primitive_bezier_curve_add(), CURVE_OT_primitive_nurbs_circle_add(), CURVE_OT_primitive_nurbs_curve_add(), CURVE_OT_primitive_nurbs_path_add(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cube_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_monkey_add(), MESH_OT_primitive_plane_add(), MESH_OT_primitive_uv_sphere_add(), OBJECT_OT_add(), OBJECT_OT_armature_add(), OBJECT_OT_camera_add(), OBJECT_OT_effector_add(), OBJECT_OT_group_instance_add(), OBJECT_OT_lamp_add(), OBJECT_OT_metaball_add(), OBJECT_OT_speaker_add(), OBJECT_OT_text_add(), SURFACE_OT_primitive_nurbs_surface_circle_add(), SURFACE_OT_primitive_nurbs_surface_curve_add(), SURFACE_OT_primitive_nurbs_surface_cylinder_add(), SURFACE_OT_primitive_nurbs_surface_sphere_add(), SURFACE_OT_primitive_nurbs_surface_surface_add(), and SURFACE_OT_primitive_nurbs_surface_torus_add().
struct Object* ED_object_add_type (struct bContext * C, int type, float * loc, float * rot, int enter_editmode, unsigned int layer) [read]
Definition at line 316 of file object_add.c.
References add_object(), BASACT, CTX_data_edit_object(), CTX_data_main(), CTX_data_scene(), DAG_id_type_tag(), DAG_scene_sort(), Object::data, ED_base_object_activate(), ED_object_base_init_transform(), ED_object_enter_editmode(), ED_object_exit_editmode(), ED_render_id_flush_update(), EM_DO_UNDO, EM_FREEDATA, EM_FREEUNDO, EM_IGNORE_LAYER, EM_WAITCURSOR, ID_OB, Object::lay, NC_SCENE, ND_LAYER_CONTENT, and WM_event_add_notifier().
Referenced by createRepresentation(), curvesurf_prim_add(), effector_add_type(), group_instance_add_exec(), make_prim_init(), object_add_exec(), object_add_text_exec(), object_armature_add_exec(), object_camera_add_exec(), object_lamp_add_exec(), object_metaball_add_exec(), and object_speaker_add_exec().
void ED_object_base_init_transform (struct bContext * C, struct Base * base, float * loc, float * rot)
Definition at line 137 of file object_add.c.
References copy_v3_v3(), CTX_data_scene(), Object::loc, Base::object, Object::rot, and where_is_object().
Referenced by ED_object_add_type(), and txt_add_object().
void ED_object_constraint_dependency_update (struct Main * bmain, struct Scene * scene, struct Object * ob)
Definition at line 988 of file object_constraint.c.
References DAG_scene_sort(), ED_object_constraint_update(), bPose::flag, Object::pose, and POSE_RECALC.
void ED_object_constraint_set_active (struct Object * ob, struct bConstraint * con)
Definition at line 965 of file object_constraint.c.
References CONSTRAINT_ACTIVE, constraints_set_active(), bConstraint::flag, get_constraint_lb(), and NULL.
Referenced by constraint_active_func().
void ED_object_constraint_update (struct Object * ob)
Definition at line 977 of file object_constraint.c.
References DAG_id_tag_update(), Object::id, OB_ARMATURE, OB_RECALC_DATA, OB_RECALC_OB, object_test_constraints(), Object::pose, Object::type, and update_pose_constraint_flags().
Referenced by constraint_delete_exec(), ED_object_constraint_dependency_update(), limitdistance_reset_exec(), and stretchto_reset_exec().
struct Object* ED_object_context (struct bContext * C) [read]
Definition at line 114 of file object_edit.c.
References CTX_data_pointer_get_type(), PointerRNA::data, and RNA_Object.
Referenced by connect_hair_exec(), disconnect_hair_exec(), dynamicPaint_initBake(), ED_object_active_context(), get_poselib_object(), group_add_exec(), group_link_exec(), group_move_exec(), group_remove_exec(), group_sort_exec(), layers_poll(), material_slot_add_exec(), material_slot_assign_exec(), material_slot_copy_exec(), material_slot_de_select(), material_slot_remove_exec(), mesh_sticky_add_exec(), mesh_sticky_remove_exec(), mesh_uv_texture_add_exec(), mesh_uv_texture_remove_exec(), mesh_vertex_color_add_exec(), mesh_vertex_color_remove_exec(), output_toggle_exec(), particle_system_add_exec(), particle_system_remove_exec(), pose_calculate_paths_exec(), pose_clear_paths_exec(), pose_de_select_all_exec(), pose_group_add_exec(), pose_group_assign_exec(), pose_group_deselect_exec(), pose_group_remove_exec(), pose_group_select_exec(), pose_group_unassign_exec(), pose_groups_menu_invoke(), set_active_group_exec(), shape_key_add_exec(), shape_key_clear_exec(), shape_key_mirror_exec(), shape_key_mode_poll(), shape_key_move_exec(), shape_key_poll(), shape_key_remove_exec(), shape_key_retime_exec(), surface_slot_add_exec(), surface_slot_remove_exec(), type_toggle_exec(), vertex_group_add_exec(), vertex_group_assign_exec(), vertex_group_blend_exec(), vertex_group_blend_poll(), vertex_group_clean_exec(), vertex_group_copy_exec(), vertex_group_copy_to_linked_exec(), vertex_group_copy_to_selected_exec(), vertex_group_deselect_exec(), vertex_group_invert_exec(), vertex_group_levels_exec(), vertex_group_mirror_exec(), vertex_group_normalize_all_exec(), vertex_group_normalize_exec(), vertex_group_poll(), vertex_group_poll_edit(), vertex_group_poll_edit_or_wpaint_vert_select(), vertex_group_remove_exec(), vertex_group_remove_from_exec(), vertex_group_select_exec(), vertex_group_sort_exec(), vgroup_itemf(), and vgroup_move_exec().
void ED_object_enter_editmode (struct bContext * C, int flag)
Definition at line 397 of file object_edit.c.
References Scene::basact, BMEditMesh::bm, BM_mesh_select_mode_flush(), BMEdit_FromObject(), BMEdit_RecalcTessellation(), CTX_data_active_base(), CTX_data_scene(), CTX_data_tool_settings(), CTX_wm_area(), DAG_id_tag_update(), Object::data, ED_armature_to_edit(), ED_object_toggle_modes(), ED_undo_push(), EDBM_mesh_make(), EDBM_mesh_normals_update(), ELEM3, EM_DO_UNDO, EM_IGNORE_LAYER, EM_WAITCURSOR, error_libdata(), ListBase::first, Object::id, bArmature::id, Scene::id, Scene::lay, View3D::lay, Base::lay, ID::lib, LIKELY, make_editLatt(), make_editMball(), make_editNurb(), make_editText(), Object::mode, NC_SCENE, ND_MODE, NS_EDITMODE_ARMATURE, NS_EDITMODE_CURVE, NS_EDITMODE_LATTICE, NS_EDITMODE_MBALL, NS_EDITMODE_MESH, NS_EDITMODE_TEXT, NS_MODE_OBJECT, NULL, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_EDIT, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, OB_SURF, Scene::obedit, Base::object, object_data_is_libdata(), Object::restore_mode, SPACE_VIEW3D, ScrArea::spacedata, ScrArea::spacetype, Object::type, waitcursor(), and WM_event_add_notifier().
Referenced by createRepresentation(), ED_object_add_type(), edbm_sort_faces_exec(), editmode_toggle_exec(), effector_add_type(), join_curve_exec(), join_mesh_exec(), make_prim_init(), and object_armature_add_exec().
void ED_object_exit_editmode (struct bContext * C, int flag)
Definition at line 309 of file object_edit.c.
References BKE_ptcache_ids_from_object(), BKE_ptcache_object_reset(), BLI_freelistN(), BMEditMesh::bm, PTCacheID::cache, CTX_data_edit_object(), CTX_data_scene(), DAG_id_tag_update(), Object::data, ED_armature_edit_free(), ED_armature_from_edit(), ED_undo_push(), EDBM_mesh_free(), EDBM_mesh_load(), Mesh::edit_btmesh, ELEM, EM_DO_UNDO, EM_FREEDATA, EM_WAITCURSOR, error(), ListBase::first, PointCache::flag, free_editLatt(), free_editMball(), free_editNurb(), free_editText(), Object::id, load_editLatt(), load_editMball(), load_editNurb(), load_editText(), MEM_freeN(), MESH_MAX_VERTS, mesh_mirrtopo_table(), mesh_octree_table(), Object::mode, NC_SCENE, ND_MODE, PTCacheID::next, NS_MODE_OBJECT, NULL, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_EDIT, OB_MODE_WEIGHT_PAINT, OB_RECALC_DATA, OB_RECALC_OB, OB_SURF, Scene::obedit, PTCACHE_OUTDATED, PTCACHE_RESET_OUTDATED, PTCACHE_TYPE_PARTICLES, Object::restore_mode, BMesh::totvert, PTCacheID::type, Object::type, waitcursor(), and WM_event_add_notifier().
Referenced by createRepresentation(), curvesurf_prim_add(), ED_object_add_type(), ED_screen_set_scene(), edbm_sort_faces_exec(), editmode_toggle_exec(), effector_add_type(), init_bake_internal(), join_curve_exec(), join_mesh_exec(), make_prim_finish(), object_armature_add_exec(), object_delete_cb(), object_metaball_add_exec(), posemode_exec(), screen_render_invoke(), tree_element_active_pose(), and WM_write_file().
void ED_object_generic_keymap (struct wmKeyConfig * keyconf, struct wmKeyMap * keymap, int do_pet)
Referenced by ED_keymap_curve(), ED_keymap_mesh(), ED_keymap_metaball(), ED_keymap_object(), ED_keymap_uvedit(), and keymap_particle().
void ED_object_location_from_view (struct bContext * C, float * loc)
Definition at line 112 of file object_add.c.
References copy_v3_v3(), CTX_data_scene(), CTX_wm_view3d(), and give_cursor().
Referenced by add_named_exec(), and object_add_generic_invoke_options().
struct ModifierData* ED_object_modifier_add (struct ReportList * reports, struct Main * bmain, struct Scene * scene, struct Object * ob, const char * name, int type) [read]
Definition at line 88 of file object_modifier.c.
References BKE_report(), BKE_reportf(), BLI_addtail(), BLI_insertlinkbefore(), BLI_strncpy(), DAG_id_tag_update(), DAG_scene_sort(), PartDeflect::deflect, ELEM5, eModifierType_Collision, eModifierType_Multires, eModifierType_ParticleSystem, eModifierType_Softbody, eModifierType_Surface, eModifierTypeFlag_RequiresOriginalData, eModifierTypeFlag_Single, eModifierTypeType_OnlyDeform, ListBase::first, ModifierTypeInfo::flags, Object::id, modifier_new(), modifier_unique_name(), Object::modifiers, modifiers_findByType(), modifierType_getInfo(), mti, multiresModifier_set_levels_from_disps(), ID::name, ModifierData::next, NULL, OB_CURVE, OB_FONT, OB_LATTICE, OB_MESH, OB_RECALC_DATA, OB_SB_EDGES, OB_SB_GOAL, OB_SURF, object_add_collision_fields(), object_add_particle_system(), Object::pd, RPT_WARNING, sbNew(), Object::soft, Object::softflag, ModifierTypeInfo::type, ModifierData::type, and Object::type.
Referenced by ED_object_parent_set(), SkinInfo::link_armature(), and modifier_add_exec().
int ED_object_modifier_apply (struct ReportList * reports, struct Scene * scene, struct Object * ob, struct ModifierData * md, int mode)
Definition at line 577 of file object_modifier.c.
References BKE_report(), BLI_remlink(), Object::data, eModifierMode_Realtime, ListBase::first, ModifierData::mode, modifier_apply_obdata(), modifier_apply_shape(), MODIFIER_APPLY_SHAPE, modifier_free(), Object::modifiers, Scene::obedit, RPT_ERROR, and RPT_INFO.
Referenced by modifier_apply_exec().
void ED_object_modifier_clear (struct Main * bmain, struct Scene * scene, struct Object * ob)
Definition at line 252 of file object_modifier.c.
References DAG_id_tag_update(), DAG_scene_sort(), ListBase::first, Object::id, Object::modifiers, ModifierData::next, OB_RECALC_DATA, and object_modifier_remove().
int ED_object_modifier_convert (struct ReportList * reports, struct Main * bmain, struct Scene * scene, struct Object * ob, struct ModifierData * md)
Referenced by modifier_convert_exec().
int ED_object_modifier_copy (struct ReportList * reports, struct Object * ob, struct ModifierData * md)
Referenced by modifier_copy_exec().
int ED_object_modifier_move_down (struct ReportList * reports, struct Object * ob, struct ModifierData * md)
Definition at line 298 of file object_modifier.c.
References BKE_report(), BLI_insertlink(), BLI_remlink(), eModifierTypeFlag_RequiresOriginalData, eModifierTypeType_OnlyDeform, ModifierTypeInfo::flags, Object::modifiers, modifierType_getInfo(), mti, ModifierData::next, RPT_WARNING, ModifierData::type, and ModifierTypeInfo::type.
Referenced by modifier_move_down_exec().
int ED_object_modifier_move_up (struct ReportList * reports, struct Object * ob, struct ModifierData * md)
Definition at line 277 of file object_modifier.c.
References BKE_report(), BLI_insertlink(), BLI_remlink(), eModifierTypeFlag_RequiresOriginalData, eModifierTypeType_OnlyDeform, ModifierTypeInfo::flags, Object::modifiers, modifierType_getInfo(), mti, ModifierData::prev, RPT_WARNING, ModifierData::type, and ModifierTypeInfo::type.
Referenced by modifier_move_up_exec().
int ED_object_modifier_remove (struct ReportList * reports, struct Main * bmain, struct Scene * scene, struct Object * ob, struct ModifierData * md)
Definition at line 231 of file object_modifier.c.
References BKE_reportf(), DAG_id_tag_update(), DAG_scene_sort(), Object::id, ModifierData::name, ID::name, OB_RECALC_DATA, object_modifier_remove(), and RPT_ERROR.
Referenced by modifier_remove_exec().
float ED_object_new_primitive_matrix (struct bContext * C, struct Object * editob, float * loc, float * rot, float primmat[][4])
Definition at line 155 of file object_add.c.
References copy_m3_m4(), copy_m4_m3(), copy_v3_v3(), CTX_wm_view3d(), eul_to_mat3(), View3D::grid, invert_m3(), invert_m3_m3(), mul_m3_m3m3(), mul_m3_v3(), Object::obmat, sub_v3_v3v3(), and unit_m4().
Referenced by curvesurf_prim_add(), effector_add_type(), and object_metaball_add_exec().
void ED_object_parent (struct Object * ob, struct Object * parent, int type, const char * substr)
Definition at line 485 of file object_relations.c.
References BKE_object_parent_loop_check(), BLI_strncpy(), NULL, Object::parent, PAROBJECT, Object::parsubstr, PARTYPE, and Object::partype.
void ED_object_parent_clear (struct bContext * C, int type)
Definition at line 426 of file object_relations.c.
References CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), DAG_scene_sort(), FALSE, NC_OBJECT, ND_PARENT, ND_TRANSFORM, NULL, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, object_apply_mat4(), TRUE, unit_m4(), and WM_event_add_notifier().
Referenced by parent_clear_exec(), and parent_clear_invoke().
int ED_object_parent_set (struct ReportList * reports, struct Main * bmain, struct Scene * scene, struct Object * ob, struct Object * par, int partype)
Definition at line 519 of file object_relations.c.
References add_fmodifier(), add_ob_constraint(), ARM_GROUPS_AUTO, ARM_GROUPS_ENVELOPE, ARM_GROUPS_NAME, FCurve::bezt, BKE_object_parent_loop_check(), BKE_report(), BLI_strncpy(), RenderData::cfra, CONSTRAINT_OBTYPE_OBJECT, CONSTRAINT_TYPE_FOLLOWPATH, create_vgroups_from_armature(), CU_FOLLOW, CU_PATH, Object::data, data, bConstraint::data, ED_object_modifier_add(), ELEM, ELEM4, ELEM5, eModifierType_Armature, eModifierType_Curve, eModifierType_Lattice, ListBase::first, Curve::flag, FMODIFIER_TYPE_GENERATOR, FCurve::fpt, get_active_posechannel(), get_constraint_target_matrix(), Curve::id, invert_m4_m4(), Object::loc, makeDispListCurveTypes(), FCurve::modifiers, bPoseChannel::name, NULL, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MESH, OB_RECALC_DATA, OB_RECALC_OB, OB_SURF, Object::obmat, PAR_ARMATURE, PAR_ARMATURE_AUTO, PAR_ARMATURE_ENVELOPE, PAR_ARMATURE_NAME, PAR_BONE, PAR_CURVE, PAR_FOLLOW, PAR_LATTICE, PAR_OBJECT, PAR_PATH_CONST, PARBONE, Object::parent, Object::parentinv, PAROBJECT, Object::parsubstr, Object::partype, Scene::r, Object::recalc, RPT_ERROR, sub_v3_v3v3(), bFollowPathConstraint::tar, Object::type, verify_adt_action(), verify_fcurve(), what_does_parent(), and WM_cursor_wait().
Referenced by parent_drop_exec(), parent_drop_invoke(), and parent_set_exec().
void ED_object_rotation_from_view (struct bContext * C, float * rot)
Definition at line 123 of file object_add.c.
References copy_qt_qt(), CTX_wm_region_view3d(), quat_to_eul(), RegionView3D::viewquat, and zero_v3().
Referenced by ED_object_add_generic_get_opts().
void ED_object_single_user (struct Scene * scene, struct Object * ob)
Definition at line 1412 of file object_relations.c.
References FIRSTBASE, Base::flag, Base::next, NULL, OB_DONE, Base::object, and single_object_users().
Referenced by template_id_cb().
void ED_object_single_users (struct Main * bmain, struct Scene * scene, int full)
Definition at line 1679 of file object_relations.c.
References clear_id_newpoins(), NULL, single_mat_users_expand(), single_obdata_users(), single_object_action_users(), single_object_users(), and single_tex_users_expand().
Referenced by scene_new_exec().
void ED_object_toggle_modes (struct bContext * C, int mode)
Definition at line 1485 of file object_edit.c.
References NULL, OB_MODE_EDIT, OB_MODE_PARTICLE_EDIT, OB_MODE_POSE, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, WM_OP_EXEC_REGION_WIN, and WM_operator_name_call().
Referenced by delete_customdata_layer(), ED_editors_init(), and ED_object_enter_editmode().
void ED_objects_clear_paths (struct bContext * C)
Definition at line 1167 of file object_edit.c.
References animviz_free_motionpath(), CTX_DATA_BEGIN, CTX_DATA_END, MOTIONPATH_BAKE_HAS_PATHS, and NULL.
Referenced by object_clear_paths_exec().
void ED_objects_recalculate_paths (struct bContext * C, struct Scene * scene)
Definition at line 1106 of file object_edit.c.
References animviz_calc_motionpaths(), animviz_get_object_motionpaths(), ANIMVIZ_RECALC_PATHS, BLI_freelistN(), CTX_DATA_BEGIN, CTX_DATA_END, and NULL.
Referenced by object_calculate_paths_exec(), and special_aftertrans_update().
void ED_operatormacros_object (void)
Definition at line 220 of file object_ops.c.
References wmOperatorType::description, MAX_ID_NAME, OPTYPE_REGISTER, OPTYPE_UNDO, PROP_EDIT_OFF, wmOperatorTypeMacro::ptr, RNA_boolean_set(), RNA_def_string(), RNA_enum_set(), wmOperatorType::srna, TRUE, WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().
void ED_operatortypes_object (void)
Definition at line 59 of file object_ops.c.
References CONSTRAINT_OT_childof_clear_inverse(), CONSTRAINT_OT_childof_set_inverse(), CONSTRAINT_OT_delete(), CONSTRAINT_OT_limitdistance_reset(), CONSTRAINT_OT_move_down(), CONSTRAINT_OT_move_up(), CONSTRAINT_OT_objectsolver_clear_inverse(), CONSTRAINT_OT_objectsolver_set_inverse(), CONSTRAINT_OT_stretchto_reset(), GROUP_OT_create(), GROUP_OT_objects_add_active(), GROUP_OT_objects_remove(), GROUP_OT_objects_remove_active(), LATTICE_OT_make_regular(), LATTICE_OT_select_all(), OBJECT_OT_add(), OBJECT_OT_add_named(), OBJECT_OT_armature_add(), OBJECT_OT_bake_image(), OBJECT_OT_camera_add(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_constraints_clear(), OBJECT_OT_constraints_copy(), OBJECT_OT_convert(), OBJECT_OT_delete(), OBJECT_OT_drop_named_material(), OBJECT_OT_duplicate(), OBJECT_OT_duplicates_make_real(), OBJECT_OT_editmode_toggle(), OBJECT_OT_effector_add(), OBJECT_OT_explode_refresh(), OBJECT_OT_forcefield_toggle(), OBJECT_OT_game_physics_copy(), OBJECT_OT_game_property_clear(), OBJECT_OT_game_property_copy(), OBJECT_OT_game_property_new(), OBJECT_OT_game_property_remove(), OBJECT_OT_group_add(), OBJECT_OT_group_instance_add(), OBJECT_OT_group_link(), OBJECT_OT_group_remove(), OBJECT_OT_hide_render_clear(), OBJECT_OT_hide_render_set(), OBJECT_OT_hide_view_clear(), OBJECT_OT_hide_view_set(), OBJECT_OT_hook_add_newobj(), OBJECT_OT_hook_add_selobj(), OBJECT_OT_hook_assign(), OBJECT_OT_hook_recenter(), OBJECT_OT_hook_remove(), OBJECT_OT_hook_reset(), OBJECT_OT_hook_select(), OBJECT_OT_join(), OBJECT_OT_join_shapes(), OBJECT_OT_lamp_add(), OBJECT_OT_location_clear(), OBJECT_OT_logic_bricks_copy(), OBJECT_OT_make_links_data(), OBJECT_OT_make_links_scene(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_meshdeform_bind(), OBJECT_OT_metaball_add(), OBJECT_OT_mode_set(), OBJECT_OT_modifier_add(), OBJECT_OT_modifier_apply(), OBJECT_OT_modifier_convert(), OBJECT_OT_modifier_copy(), OBJECT_OT_modifier_move_down(), OBJECT_OT_modifier_move_up(), OBJECT_OT_modifier_remove(), OBJECT_OT_move_to_layer(), OBJECT_OT_multires_base_apply(), OBJECT_OT_multires_external_pack(), OBJECT_OT_multires_external_save(), OBJECT_OT_multires_higher_levels_delete(), OBJECT_OT_multires_reshape(), OBJECT_OT_multires_subdivide(), OBJECT_OT_ocean_bake(), OBJECT_OT_origin_clear(), OBJECT_OT_origin_set(), OBJECT_OT_parent_clear(), OBJECT_OT_parent_no_inverse_set(), OBJECT_OT_parent_set(), OBJECT_OT_paths_calculate(), OBJECT_OT_paths_clear(), OBJECT_OT_posemode_toggle(), OBJECT_OT_proxy_make(), OBJECT_OT_rotation_clear(), OBJECT_OT_scale_clear(), OBJECT_OT_select_all(), OBJECT_OT_select_by_layer(), OBJECT_OT_select_by_type(), OBJECT_OT_select_grouped(), OBJECT_OT_select_linked(), OBJECT_OT_select_mirror(), OBJECT_OT_select_random(), OBJECT_OT_select_same_group(), OBJECT_OT_shade_flat(), OBJECT_OT_shade_smooth(), OBJECT_OT_shape_key_add(), OBJECT_OT_shape_key_clear(), OBJECT_OT_shape_key_mirror(), OBJECT_OT_shape_key_move(), OBJECT_OT_shape_key_remove(), OBJECT_OT_shape_key_retime(), OBJECT_OT_slow_parent_clear(), OBJECT_OT_slow_parent_set(), OBJECT_OT_speaker_add(), OBJECT_OT_text_add(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), OBJECT_OT_transform_apply(), OBJECT_OT_vertex_group_add(), OBJECT_OT_vertex_group_assign(), OBJECT_OT_vertex_group_blend(), OBJECT_OT_vertex_group_clean(), OBJECT_OT_vertex_group_copy(), OBJECT_OT_vertex_group_copy_to_linked(), OBJECT_OT_vertex_group_copy_to_selected(), OBJECT_OT_vertex_group_deselect(), OBJECT_OT_vertex_group_fix(), OBJECT_OT_vertex_group_invert(), OBJECT_OT_vertex_group_levels(), OBJECT_OT_vertex_group_lock(), OBJECT_OT_vertex_group_mirror(), OBJECT_OT_vertex_group_move(), OBJECT_OT_vertex_group_normalize(), OBJECT_OT_vertex_group_normalize_all(), OBJECT_OT_vertex_group_remove(), OBJECT_OT_vertex_group_remove_from(), OBJECT_OT_vertex_group_select(), OBJECT_OT_vertex_group_set_active(), OBJECT_OT_vertex_group_sort(), OBJECT_OT_vertex_parent_set(), OBJECT_OT_visual_transform_apply(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_constraints_clear(), POSE_OT_constraints_copy(), POSE_OT_ik_add(), POSE_OT_ik_clear(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
void ED_setflagsLatt (struct Object * obedit, int flag)
Definition at line 172 of file object_lattice.c.
References Object::data, Lattice::def, Lattice::editlatt, BPoint::f1, BPoint::hide, EditLatt::latt, Lattice::pntsu, Lattice::pntsv, and Lattice::pntsw.
Referenced by do_lasso_select_lattice(), do_lattice_box_select(), lattice_select_all_exec(), and mouse_lattice().
struct bConstraint* get_active_constraint (struct Object * ob) [read]
Definition at line 139 of file object_constraint.c.
References constraints_get_active(), and get_active_constraints().
struct ListBase* get_active_constraints (struct Object * ob) [read]
Definition at line 84 of file object_constraint.c.
References Object::constraints, bPoseChannel::constraints, get_active_posechannel(), Object::mode, NULL, and OB_MODE_POSE.
Referenced by edit_constraint_property_get(), get_active_constraint(), pose_constraint_add_exec(), and pose_ik_add_exec().
struct ListBase* get_constraint_lb (struct Object * ob, struct bConstraint * con, struct bPoseChannel ** pchan_r) [read]
Definition at line 103 of file object_constraint.c.
References BLI_findindex(), bPose::chanbase, bPoseChannel::constraints, Object::constraints, ELEM, ListBase::first, bPoseChannel::next, NULL, and Object::pose.
Referenced by constraint_delete_exec(), constraint_move_down_exec(), constraint_move_up_exec(), ED_object_constraint_set_active(), and edit_constraint_invoke_properties().
int mouse_lattice (struct bContext * C, const int mval[2], int extend)
Definition at line 338 of file object_lattice.c.
References Object::data, ED_setflagsLatt(), BPoint::f1, findnearestLattvert(), NC_GEOM, ND_SELECT, NULL, ViewContext::obedit, SELECT, view3d_set_viewcontext(), and WM_event_add_notifier().
Referenced by view3d_select_invoke().
void object_test_constraints (struct Object * ob)
Definition at line 499 of file object_constraint.c.
References bPose::chanbase, bPoseChannel::constraints, Object::constraints, ListBase::first, bPoseChannel::next, NULL, OB_ARMATURE, Object::pose, test_constraints(), and Object::type.
Referenced by constraint_add_exec(), and ED_object_constraint_update().
void undo_push_lattice (struct bContext * C, const char * name)
Definition at line 422 of file object_lattice.c.
References editLatt_to_undoLatt(), free_undoLatt(), get_editlatt(), undo_editmode_push(), undoLatt_to_editLatt(), and validate_undoLatt().
Referenced by ED_undo_push().
Variable Documentation
struct EnumPropertyItem prop_clear_parent_types[]
Definition at line 419 of file object_relations.c.
Referenced by OUTLINER_OT_parent_clear().
struct EnumPropertyItem prop_make_parent_types[]
Definition at line 503 of file object_relations.c.
Referenced by OUTLINER_OT_parent_drop().