Blender: transform.h File Reference
transform.h File Reference
transform
#include "ED_transform.h"
#include "ED_numinput.h"
#include "DNA_listBase.h"
#include "BLI_smallhash.h"
#include "BKE_tessmesh.h"
Classes
struct TransSnapPoint
struct TransSnap
struct TransCon
struct TransDataExtension
struct TransData2D
struct TransDataCurveHandleFlags
struct TransDataSeq
struct TransDataNla
struct TransDataSlideVert
struct SlideData
struct TransData
struct MouseInput
struct TransInfo
Defines
#define TRANS_STARTING 0
#define TRANS_RUNNING 1
#define TRANS_CONFIRM 2
#define TRANS_CANCEL 3
#define TREDRAW_NOTHING 0
#define TREDRAW_HARD 1
#define TREDRAW_SOFT 2
#define T_OBJECT (1 << 0)
#define T_EDIT (1 << 1)
#define T_POSE (1 << 2)
#define T_TEXTURE (1 << 3)
#define T_CAMERA (1 << 4)
#define T_POINTS (1 << 6)
#define T_USES_MANIPULATOR (1 << 7)
#define T_ALL_RESTRICTIONS ((1 << 8)|(1 << 9)|(1 << 10))
#define T_NO_CONSTRAINT (1 << 8)
#define T_NULL_ONE (1 << 9)
#define T_NO_ZERO (1 << 10)
#define T_PROP_EDIT (1 << 11)
#define T_PROP_CONNECTED (1 << 12)
#define T_V3D_ALIGN (1 << 14)
#define T_2D_EDIT (1 << 15)
#define T_CLIP_UV (1 << 16)
#define T_FREE_CUSTOMDATA (1 << 17)
#define T_AUTOIK (1 << 18)
#define T_MIRROR (1 << 19)
#define T_AUTOVALUES (1 << 20)
#define T_MODAL (1 << 21)
#define T_NO_PROJECT (1 << 22)
#define T_RELEASE_CONFIRM (1 << 23)
#define T_ALT_TRANSFORM (1 << 24)
#define MOD_CONSTRAINT_SELECT 0x01
#define MOD_PRECISION 0x02
#define MOD_SNAP 0x04
#define MOD_SNAP_INVERT 0x08
#define MOD_CONSTRAINT_PLANE 0x10
#define HLP_NONE 0
#define HLP_SPRING 1
#define HLP_ANGLE 2
#define HLP_HARROW 3
#define HLP_VARROW 4
#define HLP_TRACKBALL 5
#define CON_APPLY 1
#define CON_AXIS0 2
#define CON_AXIS1 4
#define CON_AXIS2 8
#define CON_SELECT 16
#define CON_NOFLIP 32
#define CON_USER 64
#define TD_SELECTED 1
#define TD_ACTIVE (1 << 1)
#define TD_NOACTION (1 << 2)
#define TD_USEQUAT (1 << 3)
#define TD_NOTCONNECTED (1 << 4)
#define TD_SINGLESIZE (1 << 5)
#define TD_NOCENTER (1 << 9)
#define TD_NO_EXT (1 << 10)
#define TD_SKIP (1 << 11)
#define TD_BEZTRIPLE (1 << 12)
#define TD_NO_LOC (1 << 13)
#define TD_NOTIMESNAP (1 << 14)
#define TD_INTVALUES (1 << 15)
#define TD_MIRROR_EDGE (1 << 16)
#define TD_MOVEHANDLE1 (1 << 17)
#define TD_MOVEHANDLE2 (1 << 18)
#define TD_PBONE_LOCAL_MTX_P (1 << 19)
#define TD_PBONE_LOCAL_MTX_C (1 << 20)
#define SNAP_FORCED 1
#define TARGET_INIT 2
#define POINT_INIT 4
#define MULTI_POINTS 8
#define DRAWLIGHT 1
#define ORIENTATION_NONE 0
#define ORIENTATION_NORMAL 1
#define ORIENTATION_VERT 2
#define ORIENTATION_EDGE 3
#define ORIENTATION_FACE 4
Typedefs
typedef struct TransSnapPoint TransSnapPoint
typedef struct TransSnap TransSnap
typedef struct TransCon TransCon
typedef struct TransDataExtension TransDataExtension
typedef struct TransData2D TransData2D
typedef struct
TransDataCurveHandleFlags TransDataCurveHandleFlags
typedef struct TransDataSeq TransDataSeq
typedef struct TransDataNla TransDataNla
typedef struct TransDataSlideVert TransDataSlideVert
typedef struct SlideData SlideData
typedef struct TransData TransData
typedef struct MouseInput MouseInput
typedef struct TransInfo TransInfo
Enumerations
enum GearsType { NO_GEARS = 0, BIG_GEARS = 1, SMALL_GEARS = 2 }
enum MouseInputMode {
INPUT_NONE, INPUT_VECTOR, INPUT_SPRING, INPUT_SPRING_FLIP,
INPUT_ANGLE, INPUT_TRACKBALL, INPUT_HORIZONTAL_RATIO, INPUT_HORIZONTAL_ABSOLUTE,
INPUT_VERTICAL_RATIO, INPUT_VERTICAL_ABSOLUTE, INPUT_CUSTOM_RATIO
}
Functions
void TRANSFORM_OT_transform (struct wmOperatorType *ot)
int initTransform (struct bContext *C, struct TransInfo *t, struct wmOperator *op, struct wmEvent *event, int mode)
void saveTransform (struct bContext *C, struct TransInfo *t, struct wmOperator *op)
int transformEvent (TransInfo *t, struct wmEvent *event)
void transformApply (struct bContext *C, TransInfo *t)
int transformEnd (struct bContext *C, TransInfo *t)
void setTransformViewMatrices (TransInfo *t)
void convertViewVec (TransInfo *t, float r_vec[3], int dx, int dy)
void projectIntView (TransInfo *t, const float vec[3], int adr[2])
void projectFloatView (TransInfo *t, const float vec[3], float adr[2])
void applyAspectRatio (TransInfo *t, float *vec)
void removeAspectRatio (TransInfo *t, float *vec)
void initWarp (TransInfo *t)
int handleEventWarp (TransInfo *t, struct wmEvent *event)
int Warp (TransInfo *t, const int mval[2])
void initShear (TransInfo *t)
int handleEventShear (TransInfo *t, struct wmEvent *event)
int Shear (TransInfo *t, const int mval[2])
void initResize (TransInfo *t)
int Resize (TransInfo *t, const int mval[2])
void initTranslation (TransInfo *t)
int Translation (TransInfo *t, const int mval[2])
void initToSphere (TransInfo *t)
int ToSphere (TransInfo *t, const int mval[2])
void initRotation (TransInfo *t)
int Rotation (TransInfo *t, const int mval[2])
void initShrinkFatten (TransInfo *t)
int ShrinkFatten (TransInfo *t, const int mval[2])
void initTilt (TransInfo *t)
int Tilt (TransInfo *t, const int mval[2])
void initCurveShrinkFatten (TransInfo *t)
int CurveShrinkFatten (TransInfo *t, const int mval[2])
void initTrackball (TransInfo *t)
int Trackball (TransInfo *t, const int mval[2])
void initPushPull (TransInfo *t)
int PushPull (TransInfo *t, const int mval[2])
void initBevel (TransInfo *t)
int handleEventBevel (TransInfo *t, struct wmEvent *event)
int Bevel (TransInfo *t, const int mval[2])
void initBevelWeight (TransInfo *t)
int BevelWeight (TransInfo *t, const int mval[2])
void initCrease (TransInfo *t)
int Crease (TransInfo *t, const int mval[2])
void initBoneSize (TransInfo *t)
int BoneSize (TransInfo *t, const int mval[2])
void initBoneEnvelope (TransInfo *t)
int BoneEnvelope (TransInfo *t, const int mval[2])
void initBoneRoll (TransInfo *t)
int BoneRoll (TransInfo *t, const int mval[2])
void initEdgeSlide (TransInfo *t)
int EdgeSlide (TransInfo *t, const int mval[2])
void initTimeTranslate (TransInfo *t)
int TimeTranslate (TransInfo *t, const int mval[2])
void initTimeSlide (TransInfo *t)
int TimeSlide (TransInfo *t, const int mval[2])
void initTimeScale (TransInfo *t)
int TimeScale (TransInfo *t, const int mval[2])
void initBakeTime (TransInfo *t)
int BakeTime (TransInfo *t, const int mval[2])
void initMirror (TransInfo *t)
int Mirror (TransInfo *t, const int mval[2])
void initAlign (TransInfo *t)
int Align (TransInfo *t, const int mval[2])
void initSeqSlide (TransInfo *t)
int SeqSlide (TransInfo *t, const int mval[2])
void drawPropCircle (const struct bContext *C, TransInfo *t)
struct wmKeyMap * transform_modal_keymap (struct wmKeyConfig *keyconf)
void flushTransGPactionData (TransInfo *t)
void flushTransGraphData (TransInfo *t)
void remake_graph_transdata (TransInfo *t, struct ListBase *anim_data)
void flushTransUVs (TransInfo *t)
void flushTransParticles (TransInfo *t)
int clipUVTransform (TransInfo *t, float *vec, int resize)
void flushTransNodes (TransInfo *t)
void flushTransSeq (TransInfo *t)
void flushTransTracking (TransInfo *t)
int gimbal_axis (struct Object *ob, float gmat[][3])
int calc_manipulator_stats (const struct bContext *C)
void createTransData (struct bContext *C, TransInfo *t)
void sort_trans_data_dist (TransInfo *t)
void special_aftertrans_update (struct bContext *C, TransInfo *t)
void transform_autoik_update (TransInfo *t, short mode)
int count_set_pose_transflags (int *out_mode, short around, struct Object *ob)
void autokeyframe_ob_cb_func (struct bContext *C, struct Scene *scene, struct View3D *v3d, struct Object *ob, int tmode)
void autokeyframe_pose_cb_func (struct bContext *C, struct Scene *scene, struct View3D *v3d, struct Object *ob, int tmode, short targetless_ik)
void drawConstraint (TransInfo *t)
void getConstraintMatrix (TransInfo *t)
void setConstraint (TransInfo *t, float space[3][3], int mode, const char text[])
void setLocalConstraint (TransInfo *t, int mode, const char text[])
void setUserConstraint (TransInfo *t, short orientation, int mode, const char text[])
void constraintNumInput (TransInfo *t, float vec[3])
int isLockConstraint (TransInfo *t)
int getConstraintSpaceDimension (TransInfo *t)
char constraintModeToChar (TransInfo *t)
void startConstraint (TransInfo *t)
void stopConstraint (TransInfo *t)
void initSelectConstraint (TransInfo *t, float mtx[3][3])
void selectConstraint (TransInfo *t)
void postSelectConstraint (TransInfo *t)
void setNearestAxis (TransInfo *t)
void snapGrid (TransInfo *t, float *val)
void snapGridAction (TransInfo *t, float *val, GearsType action)
int activeSnap (TransInfo *t)
int validSnap (TransInfo *t)
void initSnapping (struct TransInfo *t, struct wmOperator *op)
void applyProject (TransInfo *t)
void applySnapping (TransInfo *t, float *vec)
void resetSnapping (TransInfo *t)
int handleSnapping (TransInfo *t, struct wmEvent *event)
void drawSnapping (const struct bContext *C, TransInfo *t)
int usingSnappingNormal (TransInfo *t)
int validSnappingNormal (TransInfo *t)
void getSnapPoint (TransInfo *t, float vec[3])
void addSnapPoint (TransInfo *t)
int updateSelectedSnapPoint (TransInfo *t)
void removeSnapPoint (TransInfo *t)
void initMouseInput (TransInfo *t, MouseInput *mi, int center[2], int mval[2])
void initMouseInputMode (TransInfo *t, MouseInput *mi, MouseInputMode mode)
int handleMouseInput (struct TransInfo *t, struct MouseInput *mi, struct wmEvent *event)
void applyMouseInput (struct TransInfo *t, struct MouseInput *mi, const int mval[2], float output[3])
void setCustomPoints (TransInfo *t, MouseInput *mi, int start[2], int end[2])
void setInputPostFct (MouseInput *mi, void(*post)(struct TransInfo *, float[3]))
int initTransInfo (struct bContext *C, TransInfo *t, struct wmOperator *op, struct wmEvent *event)
void postTrans (struct bContext *C, TransInfo *t)
void resetTransRestrictions (TransInfo *t)
void drawLine (TransInfo *t, float *center, float *dir, char axis, short options)
void applyTransObjects (TransInfo *t)
void restoreTransObjects (TransInfo *t)
void recalcData (TransInfo *t)
void calculateCenter (TransInfo *t)
void calculateCenter2D (TransInfo *t)
void calculateCenterBound (TransInfo *t)
void calculateCenterMedian (TransInfo *t)
void calculateCenterCursor (TransInfo *t)
void calculateCenterCursor2D (TransInfo *t)
void calculatePropRatio (TransInfo *t)
void getViewVector (TransInfo *t, float coord[3], float vec[3])
void initTransformOrientation (struct bContext *C, TransInfo *t)
struct TransformOrientation * createObjectSpace (struct bContext *C, struct ReportList *reports, char *name, int overwrite)
struct TransformOrientation * createMeshSpace (struct bContext *C, struct ReportList *reports, char *name, int overwrite)
struct TransformOrientation * createBoneSpace (struct bContext *C, struct ReportList *reports, char *name, int overwrite)
int createSpaceNormal (float mat[3][3], float normal[3])
int createSpaceNormalTangent (float mat[3][3], float normal[3], float tangent[3])
struct TransformOrientation * addMatrixSpace (struct bContext *C, float mat[3][3], char name[], int overwrite)
void applyTransformOrientation (const struct bContext *C, float mat[3][3], char *name)
int getTransformOrientation (const struct bContext *C, float normal[3], float plane[3], int activeOnly)
void freeSlideTempFaces (SlideData *sld)
void freeSlideVerts (TransInfo *t)
void projectSVData (TransInfo *t, int final)
Detailed Description
Definition in file transform.h.
Define Documentation
#define CON_APPLY 1
Definition at line 403 of file transform.h.
Referenced by applyAxisConstraintRot(), applyAxisConstraintSize(), applyAxisConstraintVec(), applyObjectConstraintRot(), applyObjectConstraintSize(), applyObjectConstraintVec(), constraintAutoValues(), constraintModeToChar(), constraintNumInput(), constraintSizeLim(), drawConstraint(), ElementResize(), headerBoneSize(), headerResize(), headerTranslation(), initSelectConstraint(), initTransform(), Mirror(), postInputRotation(), PushPull(), ResizeBetween(), Rotation(), RotationBetween(), saveTransform(), SeqSlide(), startConstraint(), stopConstraint(), transformEvent(), and Translation().
#define CON_AXIS0 2
Definition at line 404 of file transform.h.
Referenced by applyAxisConstraintRot(), applyAxisConstraintSize(), applyAxisConstraintVec(), applyObjectConstraintRot(), applyObjectConstraintSize(), applyObjectConstraintVec(), constraintAutoValues(), constraintModeToChar(), constraintNumInput(), drawConstraint(), drawObjectConstraint(), getConstraintMatrix(), getConstraintSpaceDimension(), initTransform(), isLockConstraint(), postConstraintChecks(), postSelectConstraint(), saveTransform(), setNearestAxis(), setNearestAxis2d(), setNearestAxis3d(), and transformEvent().
#define CON_AXIS1 4
Definition at line 405 of file transform.h.
Referenced by applyAxisConstraintRot(), applyAxisConstraintSize(), applyAxisConstraintVec(), applyObjectConstraintRot(), applyObjectConstraintSize(), applyObjectConstraintVec(), constraintAutoValues(), constraintModeToChar(), constraintNumInput(), drawConstraint(), drawObjectConstraint(), getConstraintMatrix(), getConstraintSpaceDimension(), initTransform(), isLockConstraint(), postConstraintChecks(), postSelectConstraint(), saveTransform(), setNearestAxis(), setNearestAxis2d(), setNearestAxis3d(), and transformEvent().
#define CON_AXIS2 8
Definition at line 406 of file transform.h.
Referenced by applyAxisConstraintRot(), applyAxisConstraintSize(), applyAxisConstraintVec(), applyObjectConstraintRot(), applyObjectConstraintSize(), applyObjectConstraintVec(), constraintAutoValues(), constraintModeToChar(), constraintNumInput(), drawConstraint(), drawObjectConstraint(), getConstraintMatrix(), getConstraintSpaceDimension(), initTransform(), isLockConstraint(), postConstraintChecks(), postSelectConstraint(), saveTransform(), setNearestAxis(), setNearestAxis3d(), and transformEvent().
#define CON_NOFLIP 32
Definition at line 408 of file transform.h.
Referenced by applyAxisConstraintRot(), and applyObjectConstraintRot().
#define CON_SELECT 16
Definition at line 407 of file transform.h.
Referenced by drawConstraint(), initSelectConstraint(), postSelectConstraint(), selectConstraint(), stopConstraint(), and transformEvent().
#define CON_USER 64
Definition at line 409 of file transform.h.
Referenced by setUserConstraint().
#define DRAWLIGHT 1
Definition at line 652 of file transform.h.
Referenced by drawConstraint(), drawLine(), and drawObjectConstraint().
#define HLP_ANGLE 2
Definition at line 397 of file transform.h.
Referenced by drawHelpline(), and initMouseInputMode().
#define HLP_HARROW 3
Definition at line 398 of file transform.h.
Referenced by drawHelpline(), and initMouseInputMode().
#define HLP_NONE 0
Definition at line 395 of file transform.h.
Referenced by drawHelpline(), initMouseInputMode(), and initTransInfo().
#define HLP_SPRING 1
Definition at line 396 of file transform.h.
Referenced by drawHelpline(), and initMouseInputMode().
#define HLP_TRACKBALL 5
Definition at line 400 of file transform.h.
Referenced by drawHelpline(), and initMouseInputMode().
#define HLP_VARROW 4
Definition at line 399 of file transform.h.
Referenced by drawHelpline(), and initMouseInputMode().
#define MOD_CONSTRAINT_PLANE 0x10
Definition at line 389 of file transform.h.
Referenced by setNearestAxis3d(), and transformEvent().
#define MOD_CONSTRAINT_SELECT 0x01
Definition at line 385 of file transform.h.
Referenced by transformEvent().
#define MOD_PRECISION 0x02
Definition at line 386 of file transform.h.
Referenced by handleMouseInput(), and snapGrid().
#define MOD_SNAP 0x04
Definition at line 387 of file transform.h.
Referenced by activeSnap(), initSnapping(), saveTransform(), and transformEvent().
#define MOD_SNAP_INVERT 0x08
Definition at line 388 of file transform.h.
Referenced by activeSnap(), getAnimEdit_SnapMode(), initTransform(), and transformEvent().
#define MULTI_POINTS 8
Definition at line 436 of file transform.h.
Referenced by addSnapPoint(), removeSnapPoint(), updateSelectedSnapPoint(), and validSnap().
#define ORIENTATION_EDGE 3
Definition at line 687 of file transform.h.
Referenced by createMeshSpace(), ED_getTransformOrientationMatrix(), and getTransformOrientation().
#define ORIENTATION_FACE 4
Definition at line 688 of file transform.h.
Referenced by createMeshSpace(), ED_getTransformOrientationMatrix(), and getTransformOrientation().
#define ORIENTATION_NONE 0
Definition at line 684 of file transform.h.
Referenced by ED_getTransformOrientationMatrix(), and getTransformOrientation().
#define ORIENTATION_NORMAL 1
Definition at line 685 of file transform.h.
Referenced by ED_getTransformOrientationMatrix(), and getTransformOrientation().
#define ORIENTATION_VERT 2
Definition at line 686 of file transform.h.
Referenced by createMeshSpace(), ED_getTransformOrientationMatrix(), and getTransformOrientation().
#define POINT_INIT 4
Definition at line 435 of file transform.h.
Referenced by addSnapPoint(), CalcSnapGeometry(), drawSnapping(), getSnapPoint(), initSnapping(), TargetSnapClosest(), and validSnap().
#define SNAP_FORCED 1
Definition at line 433 of file transform.h.
Referenced by applySnapping(), initSnapping(), and postConstraintChecks().
#define T_2D_EDIT (1 << 15)
Definition at line 362 of file transform.h.
Referenced by createTransData(), headerResize(), headerTranslation(), initRotation(), initTranslation(), Mirror(), transformEvent(), and view_editmove().
#define T_ALL_RESTRICTIONS ((1 << 8)|(1 << 9)|(1 << 10))
Definition at line 352 of file transform.h.
Referenced by resetTransRestrictions().
#define T_ALT_TRANSFORM (1 << 24)
Definition at line 382 of file transform.h.
Referenced by flushTransTracking(), and transformEvent().
#define T_AUTOIK (1 << 18)
Definition at line 367 of file transform.h.
Referenced by createTransPose(), headerTranslation(), recalcData_view3d(), special_aftertrans_update(), and transformEvent().
#define T_AUTOVALUES (1 << 20)
Definition at line 371 of file transform.h.
Referenced by initTransform(), postConstraintChecks(), Resize(), and saveTransform().
#define T_CAMERA (1 << 4)
Definition at line 345 of file transform.h.
Referenced by createTransData(), initSnappingMode(), and transformEvent().
#define T_CLIP_UV (1 << 16)
Definition at line 363 of file transform.h.
Referenced by createTransUVs(), Resize(), and Translation().
#define T_EDIT (1 << 1)
Definition at line 342 of file transform.h.
Referenced by applyProject(), calculateCenter(), calculateCenter2D(), calculateCenterCursor(), createTransData(), drawHelpline(), ElementResize(), ResizeBetween(), RotationBetween(), setLocalConstraint(), TargetSnapActive(), TargetSnapCenter(), TargetSnapClosest(), TargetSnapMedian(), and Warp().
#define T_FREE_CUSTOMDATA (1 << 17)
Definition at line 365 of file transform.h.
Referenced by createTransNlaData(), createTransSeqData(), freeSeqData(), initTimeSlide(), and postTrans().
#define T_MIRROR (1 << 19)
Definition at line 369 of file transform.h.
Referenced by calculatePropRatio(), createTransEditVerts(), initTransInfo(), recalcData_view3d(), and saveTransform().
#define T_MODAL (1 << 21)
Definition at line 374 of file transform.h.
Referenced by initSnapping(), initTransInfo(), postTrans(), and saveTransform().
#define T_NO_CONSTRAINT (1 << 8)
Definition at line 353 of file transform.h.
Referenced by drawConstraint(), initAlign(), initBevel(), initBevelWeight(), initBoneEnvelope(), initBoneRoll(), initCrease(), initCurveShrinkFatten(), initEdgeSlide(), initRotation(), initShear(), initShrinkFatten(), initTilt(), initToSphere(), initTrackball(), initWarp(), and transformEvent().
#define T_NO_PROJECT (1 << 22)
Definition at line 377 of file transform.h.
Referenced by applyProject(), initBevelWeight(), initBoneEnvelope(), initBoneRoll(), initCrease(), initEdgeSlide(), and initTilt().
#define T_NO_ZERO (1 << 10)
Definition at line 355 of file transform.h.
Referenced by initCurveShrinkFatten(), initMirror(), and initResize().
#define T_NULL_ONE (1 << 9)
Definition at line 354 of file transform.h.
Referenced by constraintAutoValues(), constraintNumInput(), initMirror(), initResize(), initTimeScale(), and postConstraintChecks().
#define T_OBJECT (1 << 0)
Definition at line 341 of file transform.h.
Referenced by Align(), applyProject(), calculateCenter(), createTransData(), ElementResize(), ElementRotation(), and TargetSnapClosest().
#define T_POINTS (1 << 6)
Definition at line 347 of file transform.h.
Referenced by createTransData(), ElementResize(), and ElementRotation().
#define T_POSE (1 << 2)
Definition at line 343 of file transform.h.
Referenced by Align(), applyProject(), calculateCenter(), calculateCenter2D(), calculateCenterCursor(), createTransData(), createTransPose(), drawHelpline(), ElementResize(), ElementRotation(), recalcData_view3d(), ResizeBetween(), RotationBetween(), special_aftertrans_update(), TargetSnapActive(), TargetSnapCenter(), TargetSnapClosest(), TargetSnapMedian(), and viewRedrawForce().
#define T_PROP_CONNECTED (1 << 12)
Definition at line 358 of file transform.h.
Referenced by calculatePropRatio(), createTransEditVerts(), headerResize(), headerTranslation(), initTransInfo(), qsort_trans_data(), Rotation(), saveTransform(), Trackball(), and transformEvent().
#define T_PROP_EDIT (1 << 11)
Definition at line 357 of file transform.h.
Referenced by applyRotation(), applyTrackball(), calculatePropRatio(), createTransCurveVerts(), createTransData(), createTransEdge(), createTransEditVerts(), createTransLatticeVerts(), createTransMBallVerts(), createTransObject(), createTransParticleVerts(), createTransUVs(), drawPropCircle(), flushTransParticles(), headerResize(), headerTranslation(), initSnappingMode(), initTransInfo(), Rotation(), saveTransform(), Trackball(), and transformEvent().
#define T_RELEASE_CONFIRM (1 << 23)
Definition at line 379 of file transform.h.
Referenced by initTransInfo(), and transformEvent().
#define T_TEXTURE (1 << 3)
Definition at line 344 of file transform.h.
Referenced by createTransData(), and ElementResize().
#define T_USES_MANIPULATOR (1 << 7)
Definition at line 349 of file transform.h.
Referenced by BoneSize(), drawConstraint(), drawHelpline(), and Resize().
#define T_V3D_ALIGN (1 << 14)
Definition at line 360 of file transform.h.
Referenced by ElementResize(), ElementRotation(), and initTransInfo().
#define TARGET_INIT 2
Definition at line 434 of file transform.h.
Referenced by TargetSnapActive(), TargetSnapCenter(), TargetSnapClosest(), TargetSnapMedian(), and validSnap().
#define TD_ACTIVE (1 << 1)
Definition at line 413 of file transform.h.
Referenced by createTransEditVerts(), ObjectToTransData(), and TargetSnapActive().
#define TD_BEZTRIPLE (1 << 12)
Definition at line 422 of file transform.h.
Referenced by beztmap_to_data(), initTransDataCurveHandles(), postTrans(), and restoreElement().
#define TD_INTVALUES (1 << 15)
Definition at line 425 of file transform.h.
Referenced by bezt_to_transdata(), and flushTransGraphData().
#define TD_MIRROR_EDGE (1 << 16)
Definition at line 426 of file transform.h.
Referenced by createTransEditVerts(), and editbmesh_apply_to_mirror().
#define TD_MOVEHANDLE1 (1 << 17)
Definition at line 427 of file transform.h.
Referenced by ActionFCurveToTransData(), bezt_to_transdata(), doAnimEdit_SnapFrame(), and flushTransGraphData().
#define TD_MOVEHANDLE2 (1 << 18)
Definition at line 428 of file transform.h.
Referenced by ActionFCurveToTransData(), bezt_to_transdata(), doAnimEdit_SnapFrame(), and flushTransGraphData().
#define TD_NO_EXT (1 << 10)
Definition at line 420 of file transform.h.
Referenced by createTransParticleVerts(), and restoreElement().
#define TD_NO_LOC (1 << 13)
Definition at line 423 of file transform.h.
Referenced by add_pose_transdata(), createTransObject(), and ElementRotation().
#define TD_NOACTION (1 << 2)
Definition at line 414 of file transform.h.
Referenced by Align(), applyProject(), applyRotation(), applySeqSlide(), applyTrackball(), applyTranslation(), BakeTime(), BevelWeight(), BoneEnvelope(), BoneRoll(), BoneSize(), calculatePropRatio(), clipMirrorModifier(), Crease(), CurveShrinkFatten(), editbmesh_apply_to_mirror(), Mirror(), PushPull(), recalcData_view3d(), Resize(), Shear(), ShrinkFatten(), special_aftertrans_update(), Tilt(), ToSphere(), and Warp().
#define TD_NOCENTER (1 << 9)
Definition at line 419 of file transform.h.
Referenced by add_pose_transdata(), calculateCenterBound(), calculateCenterMedian(), and createTransObject().
#define TD_NOTCONNECTED (1 << 4)
Definition at line 416 of file transform.h.
Referenced by calc_distanceCurveVerts(), calculatePropRatio(), and createTransEditVerts().
#define TD_NOTIMESNAP (1 << 14)
Definition at line 424 of file transform.h.
Referenced by bezt_to_transdata(), and flushTransGraphData().
#define TD_PBONE_LOCAL_MTX_C (1 << 20)
Definition at line 430 of file transform.h.
Referenced by add_pose_transdata(), and ElementRotation().
#define TD_PBONE_LOCAL_MTX_P (1 << 19)
Definition at line 429 of file transform.h.
Referenced by add_pose_transdata(), and ElementRotation().
#define TD_SELECTED 1
Definition at line 412 of file transform.h.
Referenced by add_pose_transdata(), bezt_to_transdata(), calc_distanceCurveVerts(), calculateCenterBound(), calculateCenterMedian(), calculatePropRatio(), createTransArmatureVerts(), createTransCurveVerts(), createTransEdge(), createTransEditVerts(), createTransLatticeVerts(), createTransMBallVerts(), createTransNlaData(), createTransObject(), createTransParticleVerts(), createTransTexspace(), markerToTransCurveDataInit(), markerToTransDataInit(), NodeToTransData(), SeqToTransData(), set_prop_dist(), sort_trans_data(), sort_trans_data_dist(), TargetSnapActive(), TargetSnapClosest(), TargetSnapMedian(), and UVsToTransData().
#define TD_SINGLESIZE (1 << 5)
Definition at line 417 of file transform.h.
Referenced by constraintSizeLim(), createTransMBallVerts(), and ElementResize().
#define TD_SKIP (1 << 11)
Definition at line 421 of file transform.h.
Referenced by Align(), applyProject(), applyRotation(), applySeqSlide(), applyTrackball(), applyTranslation(), BakeTime(), BoneEnvelope(), BoneRoll(), BoneSize(), calculatePropRatio(), clipMirrorModifier(), Crease(), createTransObject(), createTransParticleVerts(), CurveShrinkFatten(), editbmesh_apply_to_mirror(), Mirror(), NodeToTransData(), PushPull(), recalcData_view3d(), Resize(), Shear(), ShrinkFatten(), special_aftertrans_update(), Tilt(), ToSphere(), and Warp().
#define TD_USEQUAT (1 << 3)
Definition at line 415 of file transform.h.
Referenced by createTransMBallVerts(), and ElementRotation().
#define TRANS_CANCEL 3
Definition at line 332 of file transform.h.
Referenced by EdgeSlide(), flushTransTracking(), flushTransUVs(), freeSeqData(), handleEventBevel(), initEdgeSlide(), initTimeScale(), initTimeSlide(), initTimeTranslate(), initTransform(), initTranslation(), postTrans(), recalcData_nla(), recalcData_view3d(), special_aftertrans_update(), transform_cancel(), transformEnd(), and transformEvent().
#define TRANS_CONFIRM 2
Definition at line 331 of file transform.h.
Referenced by transformApply(), and transformEvent().
#define TRANS_RUNNING 1
Definition at line 330 of file transform.h.
Referenced by calculateTransformCenter(), transformEnd(), and transformEvent().
#define TRANS_STARTING 0
Definition at line 329 of file transform.h.
Referenced by initTransform(), transformEnd(), and transformEvent().
#define TREDRAW_HARD 1
Definition at line 336 of file transform.h.
Referenced by drawTransformApply(), handleMouseInput(), special_aftertrans_update(), transformApply(), and transformEvent().
#define TREDRAW_NOTHING 0
Definition at line 335 of file transform.h.
Referenced by handleMouseInput(), and transformApply().
#define TREDRAW_SOFT 2
Definition at line 337 of file transform.h.
Referenced by drawTransformApply(), and transformApply().
Typedef Documentation
typedef struct MouseInput MouseInput
typedef struct SlideData SlideData
typedef struct TransCon TransCon
typedef struct TransData TransData
typedef struct TransData2D TransData2D
typedef struct TransDataCurveHandleFlags TransDataCurveHandleFlags
typedef struct TransDataExtension TransDataExtension
typedef struct TransDataNla TransDataNla
typedef struct TransDataSeq TransDataSeq
typedef struct TransDataSlideVert TransDataSlideVert
typedef struct TransInfo TransInfo
typedef struct TransSnap TransSnap
typedef struct TransSnapPoint TransSnapPoint
Enumeration Type Documentation
enum GearsType
Enumerator:
NO_GEARS
BIG_GEARS
SMALL_GEARS
Definition at line 593 of file transform.h.
enum MouseInputMode
Enumerator:
INPUT_NONE
INPUT_VECTOR
INPUT_SPRING
INPUT_SPRING_FLIP
INPUT_ANGLE
INPUT_TRACKBALL
INPUT_HORIZONTAL_RATIO
INPUT_HORIZONTAL_ABSOLUTE
INPUT_VERTICAL_RATIO
INPUT_VERTICAL_ABSOLUTE
INPUT_CUSTOM_RATIO
Definition at line 621 of file transform.h.
Function Documentation
int activeSnap (TransInfo * t)
Definition at line 136 of file transform_snap.c.
References MOD_SNAP, MOD_SNAP_INVERT, and TransInfo::modifiers.
Referenced by applyAxisConstraintVec(), applyProject(), applySnapping(), drawSnapping(), and snapGrid().
struct TransformOrientation* addMatrixSpace (struct bContext * C, float mat[3][3], char name[], int overwrite) [read]
Definition at line 266 of file transform_orientations.c.
References BLI_addtail(), copy_m3_m3(), CTX_data_scene(), findOrientationName(), TransformOrientation::mat, MEM_callocN(), TransformOrientation::name, NULL, Scene::transform_spaces, and uniqueOrientationName().
Referenced by createBoneSpace(), createMeshSpace(), and createObjectSpace().
void addSnapPoint (TransInfo * t)
Definition at line 550 of file transform_snap.c.
References BLI_addtail(), TransSnapPoint::co, copy_v3_v3(), MEM_callocN(), MULTI_POINTS, p, POINT_INIT, TransSnap::points, TransSnap::selectedPoint, TransSnap::snapPoint, TransSnap::status, and TransInfo::tsnap.
Referenced by transformEvent().
int Align (TransInfo * t, const int mval[2])
void applyAspectRatio (TransInfo * t, float * vec)
Definition at line 259 of file transform.c.
References ED_space_image_size(), ED_space_image_uv_aspect(), ListBase::first, SpaceImage::flag, TransInfo::mode, TransInfo::sa, SI_COORDFLOATS, SPACE_IMAGE, ScrArea::spacedata, TransInfo::spacetype, and TFM_TRANSLATION.
Referenced by headerTranslation().
void applyMouseInput (struct TransInfo * t, struct MouseInput * mi, const int mval[2], float output[3])
Definition at line 379 of file transform_input.c.
References MouseInput::apply, NULL, and MouseInput::post.
Referenced by initMouseInputMode(), and transformEvent().
void applyProject (TransInfo * t)
Definition at line 259 of file transform_snap.c.
References activeSnap(), add_v3_v3(), TransInfo::ar, copy_v3_v3(), TransInfo::data, TransData::flag, TransInfo::flag, i, invert_m4_m4(), TransData::loc, TransSnap::modeSelect, mul_m3_v3(), mul_m4_v3(), TransData::ob, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, TransInfo::obedit, object_handle_update(), Object::obmat, TransInfo::poseobj, TransSnap::project, project_float(), Object::recalc, TransInfo::scene, TransData::smtx, snapObjectsTransform(), sub_v3_v3v3(), T_EDIT, T_NO_PROJECT, T_OBJECT, T_POSE, TD_NOACTION, TD_SKIP, TransInfo::total, and TransInfo::tsnap.
Referenced by recalcData_view3d().
void applySnapping (TransInfo * t, float * vec)
Definition at line 317 of file transform_snap.c.
References activeSnap(), TransSnap::applySnap, TransSnap::calcSnap, TransSnap::last, TransSnap::mode, PIL_check_seconds_timer(), TransSnap::project, SCE_SNAP_MODE_INCREMENT, SNAP_FORCED, TransSnap::status, TransSnap::targetSnap, TransInfo::tsnap, and validSnap().
Referenced by Resize(), Rotation(), and Translation().
void applyTransformOrientation (const struct bContext * C, float mat[3][3], char * name)
Referenced by calc_manipulator_stats(), and initTransformOrientation().
void applyTransObjects (TransInfo * t)
Definition at line 1291 of file transform_generics.c.
References copy_v3_v3(), data, TransInfo::data, TransData::ext, TransData::iloc, TransDataExtension::irot, TransDataExtension::isize, TransData::loc, recalcData(), TransDataExtension::rot, TransDataExtension::size, and TransInfo::total.
void autokeyframe_ob_cb_func (struct bContext * C, struct Scene * scene, struct View3D * v3d, struct Object * ob, int tmode)
Definition at line 4632 of file transform_conversions.c.
References AnimData::action, Object::adt, ANIM_apply_keyingset(), ANIM_builtin_keyingset_get_named(), ANIM_get_keyframing_flags(), ANIM_KS_LOC_ROT_SCALE_ID, ANIM_KS_LOCATION_ID, ANIM_KS_ROTATION_ID, ANIM_KS_SCALING_ID, ANIM_relative_keyingset_add_source(), ANIM_scene_get_active_keyingset(), View3D::around, FCurve::array_index, autokeyframe_cfra_can_key(), BLI_freelistN(), CFRA, CTX_wm_reports(), bAction::curves, FCURVE_SELECTED, ListBase::first, View3D::flag, FCurve::flag, FCurve::grp, Object::id, insert_keyframe(), IS_AUTOKEY_FLAG, MODIFYKEY_MODE_INSERT, bActionGroup::name, FCurve::next, NULL, OBACT, FCurve::rna_path, TFM_RESIZE, TFM_ROTATION, TFM_TRANSLATION, V3D_ACTIVE, V3D_ALIGN, and V3D_CURSOR.
Referenced by recalcData_view3d(), and special_aftertrans_update().
void autokeyframe_pose_cb_func (struct bContext * C, struct Scene * scene, struct View3D * v3d, struct Object * ob, int tmode, short targetless_ik)
Definition at line 4730 of file transform_conversions.c.
References AnimData::action, Object::adt, ANIM_apply_keyingset(), ANIM_builtin_keyingset_get_named(), ANIM_get_keyframing_flags(), ANIM_KS_LOC_ROT_SCALE_ID, ANIM_KS_LOCATION_ID, ANIM_KS_ROTATION_ID, ANIM_KS_SCALING_ID, ANIM_relative_keyingset_add_source(), ANIM_scene_get_active_keyingset(), View3D::around, FCurve::array_index, autokeyframe_cfra_can_key(), bPose::avs, BLI_freelistN(), BLI_getQuotedStr(), BONE_TRANSFORM, BONE_UNKEYED, CFRA, CTX_wm_reports(), bAction::curves, ED_pose_recalculate_paths(), ELEM, ListBase::first, View3D::flag, FCurve::grp, Object::id, if(), insert_keyframe(), INSERTKEY_MATRIX, IS_AUTOKEY_FLAG, MEM_freeN(), MODIFYKEY_MODE_INSERT, MOTIONPATH_BAKE_HAS_PATHS, bActionGroup::name, FCurve::next, NULL, bAnimVizSettings::path_bakeflag, Object::pose, FCurve::rna_path, RNA_PoseBone, TFM_RESIZE, TFM_ROTATION, TFM_TRANSLATION, V3D_ACTIVE, V3D_ALIGN, and V3D_CURSOR.
Referenced by recalcData_view3d(), and special_aftertrans_update().
int BakeTime (TransInfo * t, const int mval[2])
Definition at line 5086 of file transform.c.
References applyNumInput(), TransInfo::center2d, TransInfo::data, ED_area_headerprint(), TransData::ext, TransData::factor, TransData::flag, hasNumInput(), i, TransData::ival, TransInfo::mouse, TransInfo::num, outputNumInput(), MouseInput::precision, MouseInput::precision_mval, TransInfo::proptext, TransDataExtension::quat, recalcData(), TransInfo::sa, TransDataExtension::size, snapGrid(), str, TD_NOACTION, TD_SKIP, TransInfo::total, and TransData::val.
Referenced by initBakeTime().
int Bevel (TransInfo * t, const int mval[2])
int BevelWeight (TransInfo * t, const int mval[2])
int BoneEnvelope (TransInfo * t, const int mval[2])
int BoneRoll (TransInfo * t, const int mval[2])
int BoneSize (TransInfo * t, const int mval[2])
Definition at line 4194 of file transform.c.
References applyNumInput(), TransCon::applySize, TransInfo::con, constraintNumInput(), copy_m3_m3(), TransInfo::data, ED_area_headerprint(), ElementBoneSize(), TransData::flag, TransInfo::flag, hasNumInput(), headerBoneSize(), i, TransInfo::imval, TransInfo::mat, TransCon::mode, NULL, TransInfo::num, recalcData(), TransInfo::sa, size(), size_to_mat3(), snapGrid(), str, T_USES_MANIPULATOR, TD_NOACTION, TD_SKIP, TransInfo::total, and TransInfo::values.
Referenced by initBoneSize().
int calc_manipulator_stats (const struct bContext * C)
Referenced by BIF_draw_manipulator(), and transformEvent().
void calculateCenter (TransInfo * t)
Definition at line 1494 of file transform_generics.c.
References TransInfo::ar, TransInfo::around, BMEditMesh::bm, BM_editselection_center(), BM_select_history_active_get(), BMEdit_FromObject(), calculateCenter2D(), calculateCenterBound(), calculateCenterCursor(), calculateCenterCursor2D(), calculateCenterCursorGraph2D(), calculateCenterMedian(), View3D::camera, TransCon::center, TransInfo::center, TransInfo::center2d, TransInfo::con, copy_v3_v3(), Object::data, ED_curve_actSelection(), ELEM, TransInfo::flag, if(), initgrabz(), TransInfo::mode, mul_m4_v3(), normalize_v3(), OB_CURVE, OB_MESH, OB_SURF, OBACT, TransInfo::obedit, Object::obmat, RegionView3D::persp, TransInfo::poseobj, projectIntView(), ARegion::regiondata, ARegion::regiontype, RGN_TYPE_WINDOW, RV3D_CAMOB, TransInfo::scene, SPACE_IMAGE, SPACE_IPO, SPACE_VIEW3D, TransInfo::spacetype, T_EDIT, T_OBJECT, T_POSE, TFM_TRANSLATION, Object::type, V3D_ACTIVE, V3D_CENTER, V3D_CENTROID, V3D_CURSOR, V3D_LOCAL, TransInfo::view, and TransInfo::viewinv.
Referenced by calculateTransformCenter(), and initTransform().
void calculateCenter2D (TransInfo * t)
Definition at line 1367 of file transform_generics.c.
References TransInfo::center, TransInfo::center2d, copy_v3_v3(), TransInfo::flag, mul_m4_v3(), TransInfo::obedit, Object::obmat, TransInfo::poseobj, projectIntView(), T_EDIT, and T_POSE.
Referenced by calculateCenter(), calculateCenterBound(), calculateCenterCursor(), calculateCenterCursor2D(), calculateCenterCursorGraph2D(), calculateCenterMedian(), and setTransformViewMatrices().
void calculateCenterBound (TransInfo * t)
Definition at line 1464 of file transform_generics.c.
References add_v3_v3v3(), calculateCenter2D(), TransInfo::center, TransData::center, copy_v3_v3(), TransInfo::data, TransData::flag, i, max, min, minmax_v3v3_v3(), mul_v3_fl(), TD_NOCENTER, TD_SELECTED, and TransInfo::total.
Referenced by calculateCenter().
void calculateCenterCursor (TransInfo * t)
Definition at line 1382 of file transform_generics.c.
References calculateCenter2D(), TransInfo::center, copy_m3_m4(), copy_v3_v3(), TransInfo::flag, give_cursor(), invert_m3_m3(), mul_m3_v3(), TransInfo::obedit, Object::obmat, TransInfo::poseobj, TransInfo::scene, sub_v3_v3v3(), T_EDIT, T_POSE, and TransInfo::view.
Referenced by calculateCenter().
void calculateCenterCursor2D (TransInfo * t)
Definition at line 1403 of file transform_generics.c.
References calculateCenter2D(), TransInfo::center, SpaceImage::cursor, ED_space_image_uv_aspect(), ListBase::first, NULL, TransInfo::sa, SPACE_IMAGE, ScrArea::spacedata, and TransInfo::spacetype.
Referenced by calculateCenter().
void calculateCenterMedian (TransInfo * t)
Definition at line 1435 of file transform_generics.c.
References add_v3_v3(), calculateCenter2D(), TransInfo::center, TransData::center, copy_v3_v3(), TransInfo::data, TransData::flag, i, mul_v3_fl(), TD_NOCENTER, TD_SELECTED, and TransInfo::total.
Referenced by calculateCenter().
void calculatePropRatio (TransInfo * t)
Definition at line 1611 of file transform_generics.c.
References BLI_frand(), BLI_rand(), BLI_srand(), TransInfo::data, TransData::dist, TransData::factor, TransData::flag, TransInfo::flag, i, TransData::loc, TransInfo::mirror, PROP_CONST, PROP_LIN, TransInfo::prop_mode, PROP_RANDOM, PROP_ROOT, PROP_SHARP, TransInfo::prop_size, PROP_SMOOTH, PROP_SPHERE, TransInfo::proptext, TransData::rdist, restoreElement(), sqrt(), T_MIRROR, T_PROP_CONNECTED, T_PROP_EDIT, TD_NOACTION, TD_NOTCONNECTED, TD_SELECTED, TD_SKIP, and TransInfo::total.
Referenced by initTransform(), and transformEvent().
int clipUVTransform (TransInfo * t, float * vec, int resize)
Definition at line 2529 of file transform_conversions.c.
References TransInfo::center, TransInfo::data, DO_MINMAX2, ED_space_image_uv_aspect(), ListBase::first, TransData::loc, max, min, TransInfo::sa, and ScrArea::spacedata.
Referenced by Resize(), and Translation().
char constraintModeToChar (TransInfo * t)
Definition at line 978 of file transform_constraints.c.
References TransInfo::con, CON_APPLY, CON_AXIS0, CON_AXIS1, CON_AXIS2, and TransCon::mode.
Referenced by transformEvent().
void constraintNumInput (TransInfo * t, float vec[3])
Definition at line 95 of file transform_constraints.c.
References TransInfo::con, CON_APPLY, CON_AXIS0, CON_AXIS1, CON_AXIS2, TransInfo::flag, getConstraintSpaceDimension(), TransCon::mode, and T_NULL_ONE.
Referenced by BoneSize(), postConstraintChecks(), and Resize().
void convertViewVec (TransInfo * t, float r_vec[3], int dx, int dy)
Definition at line 139 of file transform.c.
References TransInfo::ar, convertViewVec2D(), View2D::cur, ED_space_image_uv_aspect(), ED_view3d_win_to_delta(), ELEM, ListBase::first, View2D::mask, ARegion::regiontype, RGN_TYPE_WINDOW, TransInfo::sa, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_SEQ, SPACE_VIEW3D, ScrArea::spacedata, TransInfo::spacetype, ARegion::v2d, TransInfo::view, rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, rctf::ymax, rcti::ymax, rctf::ymin, rcti::ymin, and zero_v3().
Referenced by drawConstraint(), and InputVector().
int count_set_pose_transflags (int * out_mode, short around, struct Object * ob)
Definition at line 734 of file transform_conversions.c.
References bPoseChannel::bone, bone_children_clear_transflag(), BONE_CONNECTED, BONE_HINGE_CHILD_TRANSFORM, BONE_SELECTED, BONE_TRANSFORM, BONE_TRANSFORM_CHILD, bPose::chanbase, Bone::childbase, Object::data, ListBase::first, Bone::flag, has_targetless_ik(), bPoseChannel::next, NULL, OB_LOCK_LOC, bPoseChannel::parent, PBONE_VISIBLE, Object::pose, bPoseChannel::protectflag, TFM_BONESIZE, TFM_ROTATION, and TFM_TRANSLATION.
Referenced by calc_manipulator_stats(), createTransPose(), and special_aftertrans_update().
int Crease (TransInfo * t, const int mval[2])
struct TransformOrientation* createBoneSpace (struct bContext * C, struct ReportList * reports, char * name, int overwrite) [read]
Definition at line 152 of file transform_orientations.c.
References addMatrixSpace(), BKE_reports_prepend(), createSpaceNormalTangent(), getTransformOrientation(), and NULL.
Referenced by BIF_createTransformOrientation().
struct TransformOrientation* createMeshSpace (struct bContext * C, struct ReportList * reports, char * name, int overwrite) [read]
Definition at line 171 of file transform_orientations.c.
References addMatrixSpace(), BKE_reports_prepend(), createSpaceNormal(), createSpaceNormalTangent(), getTransformOrientation(), NULL, ORIENTATION_EDGE, ORIENTATION_FACE, and ORIENTATION_VERT.
Referenced by BIF_createTransformOrientation().
struct TransformOrientation* createObjectSpace (struct bContext * C, struct ReportList * reports, char * name, int overwrite) [read]
Referenced by BIF_createTransformOrientation().
int createSpaceNormal (float mat[3][3], float normal[3])
Definition at line 219 of file transform_orientations.c.
References copy_v3_v3(), cross_v3_v3v3(), dot_v3v3(), normalize_m3(), and normalize_v3().
Referenced by createMeshSpace(), and ED_getTransformOrientationMatrix().
int createSpaceNormalTangent (float mat[3][3], float normal[3], float tangent[3])
Definition at line 242 of file transform_orientations.c.
References copy_v3_v3(), cross_v3_v3v3(), normalize_m3(), and normalize_v3().
Referenced by createBoneSpace(), createMeshSpace(), and ED_getTransformOrientationMatrix().
void createTransData (struct bContext * C, TransInfo * t)
Definition at line 5875 of file transform_conversions.c.
References TransInfo::ar, BASE_VISIBLE, View3D::camera, createTransActionData(), createTransArmatureVerts(), createTransCurveVerts(), createTransEdge(), createTransEditVerts(), createTransGraphEditData(), createTransLatticeVerts(), createTransMBallVerts(), createTransNlaData(), createTransNodeData(), createTransObject(), createTransParticleVerts(), createTransPose(), createTransSeqData(), createTransTexspace(), createTransTrackingData(), createTransUVs(), CTX_BMESH, CTX_EDGE, CTX_TEXTURE, CTX_wm_region_view3d(), TransInfo::data, ELEM, TransInfo::ext, NumInput::flag, TransInfo::flag, Object::mode, TransInfo::mode, modifiers_isDeformedByArmature(), NULL, TransInfo::num, NUM_NO_FRACTION, OB_ARMATURE, OB_CURVE, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_PARTICLE_EDIT, OB_MODE_POSE, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_WEIGHT_PAINT, OB_SURF, OBACT, TransInfo::obedit, object_in_scene(), TransInfo::options, PE_get_current(), PE_start_edit(), RegionView3D::persp, TransInfo::poseobj, ARegion::regiontype, RGN_TYPE_WINDOW, RV3D_CAMOB, TransInfo::scene, set_prop_dist(), sort_trans_data(), sort_trans_data_dist(), SPACE_ACTION, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_SEQ, SPACE_VIEW3D, TransInfo::spacetype, T_2D_EDIT, T_CAMERA, T_EDIT, T_OBJECT, T_POINTS, T_POSE, T_PROP_EDIT, T_TEXTURE, TFM_BONESIZE, Object::type, and TransInfo::view.
Referenced by calculateTransformCenter(), and initTransform().
int CurveShrinkFatten (TransInfo * t, const int mval[2])
void drawConstraint (TransInfo * t)
Definition at line 644 of file transform_constraints.c.
References add_v3_v3(), TransCon::center, TransInfo::con, CON_APPLY, CON_AXIS0, CON_AXIS1, CON_AXIS2, CON_SELECT, convertViewVec(), TransCon::drawExtra, DRAWLIGHT, drawLine(), ELEM, TransInfo::flag, TransCon::imval, TransCon::mode, TransCon::mtx, TransInfo::mval, setlinestyle(), SPACE_IMAGE, SPACE_VIEW3D, TransInfo::spacetype, T_NO_CONSTRAINT, and T_USES_MANIPULATOR.
Referenced by drawTransformView().
void drawLine (TransInfo * t, float * center, float * dir, char axis, short options)
Definition at line 913 of file transform_generics.c.
References add_v3_v3v3(), copy_v3_v3(), DRAWLIGHT, View3D::far, mul_v3_fl(), setlinestyle(), SPACE_VIEW3D, TransInfo::spacetype, sub_v3_v3v3(), TH_GRID, UI_GetThemeColor3ubv(), UI_make_axis_color(), and TransInfo::view.
Referenced by drawConstraint(), and drawObjectConstraint().
void drawPropCircle (const struct bContext * C, TransInfo * t)
Definition at line 708 of file transform_constraints.c.
References TransInfo::center, copy_m4_m4(), copy_v3_v3(), CTX_wm_region_view3d(), drawcircball(), ED_space_image_uv_aspect(), ListBase::first, TransInfo::flag, invert_m4_m4(), mul_m4_v3(), NULL, TransInfo::obedit, Object::obmat, TransInfo::prop_size, TransInfo::sa, set_inverted_drawing(), SPACE_IMAGE, SPACE_VIEW3D, ScrArea::spacedata, TransInfo::spacetype, T_PROP_EDIT, TH_GRID, UI_ThemeColor(), unit_m4(), and RegionView3D::viewmat.
Referenced by drawTransformView().
void drawSnapping (const struct bContext * C, TransInfo * t)
Definition at line 141 of file transform_snap.c.
References activeSnap(), TransSnapPoint::co, cpack, CTX_wm_region_view3d(), CTX_wm_view3d(), drawcircball(), ED_space_image_aspect(), ED_view3d_pixel_size(), fdrawline(), ListBase::first, G, invert_m4_m4(), TransSnapPoint::next, p, POINT_INIT, TransSnap::points, TransInfo::sa, TransSnap::selectedPoint, setlinestyle(), size(), TransSnap::snapNormal, TransSnap::snapPoint, SPACE_IMAGE, SPACE_VIEW3D, ScrArea::spacedata, TransInfo::spacetype, TransSnap::status, TH_ACTIVE, TH_SELECT, TH_TRANSFORM, TH_VERTEX_SIZE, TransInfo::tsnap, UI_GetThemeColor3ubv(), UI_GetThemeValuef(), usingSnappingNormal(), validSnap(), validSnappingNormal(), RegionView3D::viewmat, and View3D::zbuf.
Referenced by drawTransformView().
int EdgeSlide (TransInfo * t, const int mval[2])
void flushTransGPactionData (TransInfo * t)
Definition at line 3084 of file transform_conversions.c.
References TransInfo::customData, i, TransInfo::mode, tGPFtransdata::sdata, TFM_TIME_SLIDE, TransInfo::total, and tGPFtransdata::val.
void flushTransGraphData (TransInfo * t)
Definition at line 3790 of file transform_conversions.c.
References SpaceIpo::autosnap, BKE_nla_tweakedit_remap(), TransInfo::data, TransInfo::data2d, ED_markers_find_nearest_marker_time(), ListBase::first, SpaceIpo::flag, floorf, FPS, if(), Scene::markers, NLATIME_CONVERT_UNMAP, TransInfo::sa, SACTSNAP_FRAME, SACTSNAP_MARKER, TransInfo::scene, SIPO_DRAWTIME, ScrArea::spacedata, TD_INTVALUES, TD_MOVEHANDLE1, TD_MOVEHANDLE2, and TD_NOTIMESNAP.
void flushTransNodes (TransInfo * t)
Definition at line 2269 of file transform_conversions.c.
References TransInfo::data2d, ED_node_link_intersect_test(), TransData2D::loc, TransData2D::loc2d, TransInfo::sa, and TransInfo::total.
Referenced by recalcData().
void flushTransParticles (TransInfo * t)
Definition at line 1819 of file transform_conversions.c.
References co, PTCacheEditKey::co, compare_v3v3(), copy_v3_v3(), TransInfo::data, ParticleSystemModifierData::dm, PTCacheEditPoint::flag, ParticleSystem::flag, TransInfo::flag, ParticleSettings::from, i, invert_m4_m4(), PTCacheEditPoint::keys, TransformOrientation::mat, mul_m4_v3(), NULL, OBACT, ParticleSystem::part, ParticleSystem::particles, PE_get_current(), PE_update_object(), PEP_EDIT_RECALC, PEP_TRANSFORM, PTCacheEdit::points, PTCacheEdit::psys, psys_get_modifier(), PSYS_GLOBAL_HAIR, psys_mat_hair_to_global(), TransInfo::scene, T_PROP_EDIT, and PTCacheEditKey::world_co.
Referenced by recalcData_view3d().
void flushTransSeq (TransInfo * t)
Definition at line 2294 of file transform_conversions.c.
References calc_sequence(), calc_sequence_disp(), CLAMP(), TransInfo::data, TransInfo::data2d, Sequence::depth, ELEM, TransData::extra, FALSE, ListBase::first, Sequence::flag, TransDataSeq::flag, if(), TransData2D::loc, Sequence::machine, MAXSEQ, TransInfo::mode, Sequence::next, NULL, TransInfo::scene, TransDataSeq::sel_flag, SELECT, TransDataSeq::seq, Sequence::seq1, Sequence::seq2, Sequence::seq3, seq_give_editing(), SEQ_LEFTSEL, SEQ_META, seq_offset_animdata(), SEQ_OVERLAP, SEQ_RIGHTSEL, seq_single_fix(), seq_test_overlap(), seq_tx_handle_xlimits(), seq_tx_set_final_left(), seq_tx_set_final_right(), seq_tx_test(), Editing::seqbasep, Sequence::start, TransDataSeq::start_offset, TFM_SEQ_SLIDE, TFM_TIME_TRANSLATE, and Sequence::type.
Referenced by recalcData().
void flushTransTracking (TransInfo * t)
Definition at line 5826 of file transform_conversions.c.
References add_v2_v2v2(), TransDataTracking::area, cancelTransTracking(), TransDataTracking::coord, copy_v2_v2(), TransInfo::customData, TransInfo::data, TransInfo::data2d, TransInfo::flag, TransData2D::loc, TransData2D::loc2d, TransDataTracking::markers, TransDataTracking::markersnr, MEM_callocN(), TransDataTracking::mode, negate_v2_v2(), MovieTrackingMarker::pos, TransDataTracking::prev_pos, TransDataTracking::relative, TransDataTracking::scale, TransDataTracking::smarkers, TransDataTracking::soffset, TransDataTracking::srelative, TransInfo::state, sub_v2_v2(), sub_v2_v2v2(), T_ALT_TRANSFORM, TRACK_AREA_POINT, TRANS_CANCEL, transDataTracking_ModeCurves, and transDataTracking_ModeTracks.
Referenced by recalcData_clip().
void flushTransUVs (TransInfo * t)
Definition at line 2505 of file transform_conversions.c.
References TransInfo::data2d, ED_space_image_size(), ED_space_image_uv_aspect(), ListBase::first, SpaceImage::flag, TransData2D::loc, TransData2D::loc2d, TransInfo::sa, SI_PIXELSNAP, ScrArea::spacedata, TransInfo::state, and TRANS_CANCEL.
Referenced by recalcData_image().
void freeSlideTempFaces (SlideData * sld)
Definition at line 4844 of file transform.c.
References BLI_smallhash_iternew(), BLI_smallhash_iternext(), BLI_smallhash_release(), BMEditMesh::bm, BM_face_verts_kill(), SlideData::em, FALSE, NULL, SlideData::origfaces, and SlideData::origfaces_init.
Referenced by freeSlideVerts(), and special_aftertrans_update().
void freeSlideVerts (TransInfo * t)
Definition at line 4862 of file transform.c.
References BLI_ghash_lookup(), BLI_smallhash_release(), BMEditMesh::bm, bmesh_edit_end(), BMO_OP_FLAG_UNTAN_MULTIRES, TransInfo::customData, TransDataSlideVert::down, SlideData::em, freeSlideTempFaces(), LinkNode::link, ME_DRAWEXTRA_EDGELEN, MEM_freeN(), LinkNode::next, NULL, recalcData(), SELECT, SlideData::sv, TransDataSlideVert::up, and SlideData::vhash.
Referenced by initEdgeSlide().
void getConstraintMatrix (TransInfo * t)
Definition at line 800 of file transform_constraints.c.
References TransInfo::con, CON_AXIS0, CON_AXIS1, CON_AXIS2, TransCon::imtx, invert_m3_m3(), TransformOrientation::mat, TransCon::mode, TransCon::mtx, mul_m3_m3m3(), TransCon::pmtx, and unit_m3().
Referenced by setConstraint(), setLocalConstraint(), and setNearestAxis().
int getConstraintSpaceDimension (TransInfo * t)
Definition at line 1023 of file transform_constraints.c.
References TransInfo::con, CON_AXIS0, CON_AXIS1, CON_AXIS2, and TransCon::mode.
Referenced by applyAxisConstraintVec(), applyObjectConstraintVec(), constraintNumInput(), and startConstraint().
void getSnapPoint (TransInfo * t, float vec[3])
Definition at line 617 of file transform_snap.c.
References add_v3_v3(), TransSnapPoint::co, copy_v3_v3(), ListBase::first, mul_v3_fl(), TransSnapPoint::next, p, POINT_INIT, TransSnap::points, TransSnap::snapPoint, TransSnap::status, and TransInfo::tsnap.
Referenced by ApplySnapResize(), ApplySnapRotation(), and ApplySnapTranslation().
int getTransformOrientation (const struct bContext * C, float normal[3], float plane[3], int activeOnly)
Referenced by createBoneSpace(), createMeshSpace(), and ED_getTransformOrientationMatrix().
void getViewVector (TransInfo * t, float coord[3], float vec[3])
Definition at line 112 of file transform_generics.c.
References copy_v3_v3(), mul_m4_v4(), normalize_v3(), TransInfo::persp, RV3D_ORTHO, sub_v3_v3v3(), TransInfo::viewinv, and TransInfo::viewmat.
Referenced by axisProjection(), and planeProjection().
int gimbal_axis (struct Object * ob, float gmat[][3])
Definition at line 202 of file transform_manipulator.c.
References axis_angle_to_gimbal_axis(), bPoseChannel::bone, Bone::bone_mat, copy_m3_m4(), bPoseChannel::eul, eulO_to_gimbal_axis(), get_active_posechannel(), Object::mode, mul_m3_m3m3(), normalize_m3(), OB_MODE_POSE, Object::obmat, bPoseChannel::parent, Object::parent, bPoseChannel::pose_mat, Object::rot, ROT_MODE_AXISANGLE, bPoseChannel::rotAngle, Object::rotAngle, Object::rotAxis, bPoseChannel::rotAxis, Object::rotmode, bPoseChannel::rotmode, and test_rotmode_euler().
Referenced by calc_manipulator_stats(), and initTransformOrientation().
int handleEventBevel (TransInfo * t, struct wmEvent * event)
Definition at line 3900 of file transform.c.
References BME_BEVEL_VERT, G, KM_PRESS, MIDDLEMOUSE, TransInfo::state, TRANS_CANCEL, wmEvent::type, and wmEvent::val.
Referenced by initBevel().
int handleEventShear (TransInfo * t, struct wmEvent * event)
Definition at line 2464 of file transform.c.
References TransInfo::customData, initMouseInputMode(), INPUT_HORIZONTAL_ABSOLUTE, INPUT_VERTICAL_ABSOLUTE, KM_PRESS, MIDDLEMOUSE, TransInfo::mouse, NULL, wmEvent::type, and wmEvent::val.
Referenced by initShear().
int handleEventWarp (TransInfo * t, struct wmEvent * event)
Definition at line 2323 of file transform.c.
References TransInfo::customData, KM_PRESS, MIDDLEMOUSE, NULL, wmEvent::type, and wmEvent::val.
Referenced by initWarp().
int handleMouseInput (struct TransInfo * t, struct MouseInput * mi, struct wmEvent * event)
Definition at line 390 of file transform_input.c.
References copy_v2_v2_int(), KM_PRESS, LEFTSHIFTKEY, MOD_PRECISION, TransInfo::modifiers, wmEvent::mval, MouseInput::precision, MouseInput::precision_mval, RIGHTSHIFTKEY, TREDRAW_HARD, TREDRAW_NOTHING, wmEvent::type, and wmEvent::val.
Referenced by transformEvent().
int handleSnapping (TransInfo * t, struct wmEvent * event)
Definition at line 238 of file transform_snap.c.
References BIF_snappingSupported(), initSnapping(), MOUSEMOVE, NULL, TransInfo::obedit, SCE_SNAP, TransInfo::settings, wmEvent::shift, ToolSettings::snap_flag, TABKEY, wmEvent::type, and updateSelectedSnapPoint().
Referenced by transformEvent().
void initAlign (TransInfo * t)
Definition at line 5228 of file transform.c.
References Align(), TransInfo::flag, initMouseInputMode(), INPUT_NONE, TransInfo::mouse, T_NO_CONSTRAINT, and TransInfo::transform.
Referenced by initTransform().
void initBakeTime (TransInfo * t)
Definition at line 5072 of file transform.c.
References BakeTime(), NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_NONE, TransInfo::mouse, TransInfo::num, TransInfo::snap, and TransInfo::transform.
Referenced by initTransform().
void initBevel (TransInfo * t)
Definition at line 3868 of file transform.c.
References Bevel(), NumInput::flag, TransInfo::flag, G, TransInfo::handleEvent, handleEventBevel(), NumInput::idx_max, TransInfo::idx_max, TransInfo::imval, NumInput::increment, initMouseInputMode(), INPUT_HORIZONTAL_ABSOLUTE, TransInfo::mode, TransInfo::mouse, TransInfo::num, NUM_NO_NEGATIVE, TransInfo::snap, T_NO_CONSTRAINT, TFM_BEVEL, and TransInfo::transform.
Referenced by initTransform().
void initBevelWeight (TransInfo * t)
Definition at line 3983 of file transform.c.
References BevelWeight(), TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_SPRING, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::snap, T_NO_CONSTRAINT, T_NO_PROJECT, TFM_BWEIGHT, and TransInfo::transform.
Referenced by initTransform().
void initBoneEnvelope (TransInfo * t)
Definition at line 4250 of file transform.c.
References BoneEnvelope(), TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_SPRING, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::snap, T_NO_CONSTRAINT, T_NO_PROJECT, TFM_BONE_ENVELOPE, and TransInfo::transform.
Referenced by initTransform().
void initBoneRoll (TransInfo * t)
Definition at line 5007 of file transform.c.
References BoneRoll(), TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_ANGLE, M_PI, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::snap, T_NO_CONSTRAINT, T_NO_PROJECT, TFM_BONE_ROLL, and TransInfo::transform.
Referenced by initTransform().
void initBoneSize (TransInfo * t)
Definition at line 4132 of file transform.c.
References BoneSize(), NumInput::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_SPRING_FLIP, TransInfo::mode, TransInfo::mouse, TransInfo::num, NUM_AFFECT_ALL, NUM_NULL_ONE, TransInfo::snap, TFM_BONESIZE, and TransInfo::transform.
Referenced by initTransform().
void initCrease (TransInfo * t)
Definition at line 4056 of file transform.c.
References Crease(), TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_SPRING, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::snap, T_NO_CONSTRAINT, T_NO_PROJECT, TFM_CREASE, and TransInfo::transform.
Referenced by initTransform().
void initCurveShrinkFatten (TransInfo * t)
Definition at line 3715 of file transform.c.
References CurveShrinkFatten(), NumInput::flag, TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_SPRING, TransInfo::mode, TransInfo::mouse, TransInfo::num, NUM_NO_ZERO, TransInfo::snap, T_NO_CONSTRAINT, T_NO_ZERO, TFM_CURVE_SHRINKFATTEN, and TransInfo::transform.
Referenced by initTransform().
void initEdgeSlide (TransInfo * t)
Definition at line 4899 of file transform.c.
References createSlideVerts(), TransInfo::customData, TransInfo::customFree, EdgeSlide(), SlideData::end, TransInfo::flag, freeSlideVerts(), NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_CUSTOM_RATIO, TransInfo::mode, TransInfo::mouse, TransInfo::num, setCustomPoints(), TransInfo::snap, SlideData::start, TransInfo::state, T_NO_CONSTRAINT, T_NO_PROJECT, TFM_EDGE_SLIDE, TRANS_CANCEL, and TransInfo::transform.
Referenced by initTransform().
void initMirror (TransInfo * t)
Definition at line 5150 of file transform.c.
References TransInfo::flag, initMouseInputMode(), INPUT_NONE, Mirror(), TransInfo::mouse, TransInfo::obedit, T_NO_ZERO, T_NULL_ONE, and TransInfo::transform.
Referenced by initTransform().
void initMouseInput (TransInfo * t, MouseInput * mi, int center[2], int mval[2])
Referenced by initTimeScale(), and initTransform().
void initMouseInputMode (TransInfo * t, MouseInput * mi, MouseInputMode mode)
Definition at line 304 of file transform_input.c.
References MouseInput::apply, applyMouseInput(), calcSpringFactor(), MouseInput::center, MouseInput::data, MouseInput::factor, TransInfo::helpline, HLP_ANGLE, HLP_HARROW, HLP_NONE, HLP_SPRING, HLP_TRACKBALL, HLP_VARROW, MouseInput::imval, INPUT_ANGLE, INPUT_CUSTOM_RATIO, INPUT_HORIZONTAL_ABSOLUTE, INPUT_HORIZONTAL_RATIO, INPUT_NONE, INPUT_SPRING, INPUT_SPRING_FLIP, INPUT_TRACKBALL, INPUT_VECTOR, INPUT_VERTICAL_ABSOLUTE, INPUT_VERTICAL_RATIO, InputAngle(), InputCustomRatio(), InputHorizontalAbsolute(), InputHorizontalRatio(), InputSpring(), InputSpringFlip(), InputTrackBall(), InputVector(), InputVerticalAbsolute(), InputVerticalRatio(), MEM_callocN(), MEM_freeN(), NULL, and TransInfo::values.
Referenced by handleEventShear(), initAlign(), initBakeTime(), initBevel(), initBevelWeight(), initBoneEnvelope(), initBoneRoll(), initBoneSize(), initCrease(), initCurveShrinkFatten(), initEdgeSlide(), initMirror(), initPushPull(), initResize(), initRotation(), initSeqSlide(), initShear(), initShrinkFatten(), initTilt(), initTimeScale(), initTimeSlide(), initTimeTranslate(), initToSphere(), initTrackball(), initTranslation(), and initWarp().
void initPushPull (TransInfo * t)
Definition at line 3783 of file transform.c.
References NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_VERTICAL_ABSOLUTE, TransInfo::mode, TransInfo::mouse, TransInfo::num, PushPull(), TransInfo::snap, TFM_PUSHPULL, and TransInfo::transform.
Referenced by initTransform().
void initResize (TransInfo * t)
Definition at line 2568 of file transform.c.
References NumInput::flag, TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_SPRING_FLIP, TransInfo::mode, TransInfo::mouse, TransInfo::num, NUM_AFFECT_ALL, NUM_NO_ZERO, NUM_NULL_ONE, TransInfo::obedit, Resize(), TransInfo::snap, T_NO_ZERO, T_NULL_ONE, TFM_RESIZE, and TransInfo::transform.
Referenced by initShrinkFatten(), initTransform(), and transformEvent().
void initRotation (TransInfo * t)
Definition at line 2925 of file transform.c.
References TransInfo::axis, TransInfo::axis_orig, copy_v3_v3(), TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_ANGLE, M_PI, TransInfo::mode, TransInfo::mouse, negate_v3_v3(), normalize_v3(), TransInfo::num, postInputRotation(), Rotation(), setInputPostFct(), TransInfo::snap, T_2D_EDIT, T_NO_CONSTRAINT, TFM_ROTATION, TransInfo::transform, and TransInfo::viewinv.
Referenced by initTransform(), and transformEvent().
void initSelectConstraint (TransInfo * t, float mtx[3][3])
Definition at line 830 of file transform_constraints.c.
References applyAxisConstraintRot(), applyAxisConstraintSize(), applyAxisConstraintVec(), TransCon::applyRot, TransCon::applySize, TransCon::applyVec, TransInfo::con, CON_APPLY, CON_SELECT, copy_m3_m3(), TransCon::drawExtra, TransCon::mode, TransCon::mtx, NULL, and setNearestAxis().
Referenced by transformEvent().
void initSeqSlide (TransInfo * t)
Definition at line 5285 of file transform.c.
References NumInput::flag, RenderData::frs_sec, RenderData::frs_sec_base, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_VECTOR, TransInfo::mouse, TransInfo::num, Scene::r, TransInfo::scene, SeqSlide(), TransInfo::snap, and TransInfo::transform.
Referenced by initTransform().
void initShear (TransInfo * t)
Definition at line 2444 of file transform.c.
References TransInfo::flag, TransInfo::handleEvent, handleEventShear(), NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_HORIZONTAL_ABSOLUTE, TransInfo::mode, TransInfo::mouse, TransInfo::num, postInputShear(), setInputPostFct(), Shear(), TransInfo::snap, T_NO_CONSTRAINT, TFM_SHEAR, and TransInfo::transform.
Referenced by initTransform().
void initShrinkFatten (TransInfo * t)
Definition at line 3568 of file transform.c.
References TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), initResize(), INPUT_VERTICAL_ABSOLUTE, TransInfo::mode, TransInfo::mouse, NULL, TransInfo::num, OB_MESH, TransInfo::obedit, ShrinkFatten(), TransInfo::snap, T_NO_CONSTRAINT, TFM_SHRINKFATTEN, TransInfo::transform, and Object::type.
Referenced by initTransform().
void initSnapping (struct TransInfo * t, struct wmOperator * op)
Definition at line 434 of file transform_snap.c.
References TransSnap::align, ELEM, TransInfo::flag, initSnappingMode(), MOD_SNAP, TransInfo::modifiers, normalize_v3(), TransSnap::peel, POINT_INIT, TransSnap::project, wmOperator::ptr, resetSnapping(), RNA_boolean_get(), RNA_enum_get(), RNA_float_get_array(), RNA_struct_find_property(), RNA_struct_property_is_set(), SCE_SNAP, SCE_SNAP_NO_SELF, SCE_SNAP_PROJECT, SCE_SNAP_ROTATE, TransInfo::settings, ToolSettings::snap_flag, SNAP_FORCED, TransSnap::snap_self, ToolSettings::snap_target, TransSnap::snapNormal, TransSnap::snapPoint, SPACE_IMAGE, SPACE_VIEW3D, TransInfo::spacetype, TransSnap::status, T_MODAL, TransSnap::target, and TransInfo::tsnap.
Referenced by handleSnapping(), initTransform(), and transformEvent().
void initTilt (TransInfo * t)
Definition at line 3646 of file transform.c.
References TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_ANGLE, M_PI, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::snap, T_NO_CONSTRAINT, T_NO_PROJECT, TFM_TILT, Tilt(), and TransInfo::transform.
Referenced by initTransform().
void initTimeScale (TransInfo * t)
Definition at line 5802 of file transform.c.
References TransInfo::center, RenderData::cfra, ELEM, NumInput::flag, TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, TransInfo::imval, NumInput::increment, initMouseInput(), initMouseInputMode(), INPUT_SPRING_FLIP, TransInfo::mode, TransInfo::mouse, TransInfo::num, NUM_NULL_ONE, projectIntView(), Scene::r, TransInfo::scene, TransInfo::snap, SPACE_ACTION, SPACE_NLA, TransInfo::spacetype, TransInfo::state, T_NULL_ONE, TFM_TIME_SCALE, TimeScale(), TRANS_CANCEL, and TransInfo::transform.
Referenced by initTransform().
void initTimeSlide (TransInfo * t)
Definition at line 5668 of file transform.c.
References ListBase::first, SpaceAction::flag, NumInput::flag, TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_NONE, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::sa, SACTION_MOVING, TransInfo::snap, SPACE_ACTION, ScrArea::spacedata, TransInfo::spacetype, TransInfo::state, T_FREE_CUSTOMDATA, TFM_TIME_SLIDE, TimeSlide(), TRANS_CANCEL, and TransInfo::transform.
Referenced by initTransform().
void initTimeTranslate (TransInfo * t)
Definition at line 5521 of file transform.c.
References ELEM, NumInput::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_NONE, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::snap, SPACE_ACTION, SPACE_SEQ, TransInfo::spacetype, TransInfo::state, TFM_TIME_TRANSLATE, TimeTranslate(), TRANS_CANCEL, and TransInfo::transform.
Referenced by initTransform().
void initToSphere (TransInfo * t)
Definition at line 2824 of file transform.c.
References TransInfo::center, TransInfo::data, TransInfo::flag, NumInput::flag, i, NumInput::idx_max, TransInfo::idx_max, TransData::iloc, NumInput::increment, initMouseInputMode(), INPUT_HORIZONTAL_RATIO, len_v3v3(), TransInfo::mode, TransInfo::mouse, TransInfo::num, NUM_NO_NEGATIVE, NUM_NULL_ONE, TransInfo::snap, T_NO_CONSTRAINT, TFM_TOSPHERE, ToSphere(), TransInfo::total, TransInfo::transform, and TransInfo::val.
Referenced by initTransform().
void initTrackball (TransInfo * t)
Definition at line 3250 of file transform.c.
References TransInfo::flag, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_TRACKBALL, M_PI, TransInfo::mode, TransInfo::mouse, TransInfo::num, TransInfo::snap, T_NO_CONSTRAINT, TFM_TRACKBALL, Trackball(), and TransInfo::transform.
Referenced by initTransform(), and transformEvent().
int initTransform (struct bContext * C, struct TransInfo * t, struct wmOperator * op, struct wmEvent * event, int mode)
Definition at line 1519 of file transform.c.
References wmEvent::alt, TransInfo::ar, ARM_ENVELOPE, TransInfo::auto_values, TransInfo::axis, TransInfo::axis_orig, C, calculateCenter(), calculatePropRatio(), TransInfo::center2d, TransInfo::con, CON_APPLY, CON_AXIS0, CON_AXIS1, CON_AXIS2, TransInfo::context, copy_v3_v3(), copy_v4_v4(), createTransData(), wmEvent::ctrl, CTX_MOVIECLIP, CTX_TEXTURE, CTX_wm_manager(), TransInfo::current_orientation, Object::data, TransInfo::draw_handle_apply, TransInfo::draw_handle_cursor, TransInfo::draw_handle_view, drawHelpline(), drawTransformApply(), drawTransformView(), bArmature::drawtype, ED_region_draw_cb_activate(), ELEM, EVT_TWEAK_L, EVT_TWEAK_R, ListBase::first, TransInfo::flag, helpline_poll(), TransInfo::imval, initAlign(), initBakeTime(), initBevel(), initBevelWeight(), initBoneEnvelope(), initBoneRoll(), initBoneSize(), initCrease(), initCurveShrinkFatten(), initEdgeSlide(), initMirror(), initMouseInput(), initPushPull(), initResize(), initRotation(), initSeqSlide(), initShear(), initShrinkFatten(), initSnapping(), initTilt(), initTimeScale(), initTimeSlide(), initTimeTranslate(), initToSphere(), initTrackball(), initTransformOrientation(), initTransInfo(), initTranslation(), initWarp(), wmKeyMap::items, KM_PRESS, TransInfo::launch_event, LEFTALTKEY, LEFTCTRLKEY, LEFTMOUSE, LEFTSHIFTKEY, MOD_SNAP_INVERT, wmOperatorType::modalkeymap, TransCon::mode, TransInfo::mode, TransInfo::modifiers, TransInfo::mouse, wmKeyMapItem::next, normalize_v3(), NULL, TransInfo::options, options, wmEvent::oskey, OSKEY, TransInfo::poseobj, postTrans(), wmKeyMapItem::propvalue, wmOperator::ptr, REGION_DRAW_POST_VIEW, REGION_DRAW_PRE_VIEW, RIGHTALTKEY, RIGHTCTRLKEY, RIGHTMOUSE, RIGHTSHIFTKEY, RNA_float_get(), RNA_float_get_array(), RNA_property_array_check(), RNA_property_boolean_get(), RNA_property_boolean_get_array(), RNA_property_float_get_array(), RNA_property_is_set(), RNA_struct_find_property(), setUserConstraint(), wmEvent::shift, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_VIEW3D, TransInfo::spacemtx, TransInfo::spacetype, TransInfo::state, T_AUTOVALUES, TFM_ALIGN, TFM_BAKE_TIME, TFM_BEVEL, TFM_BONE_ENVELOPE, TFM_BONE_ROLL, TFM_BONESIZE, TFM_BWEIGHT, TFM_CREASE, TFM_CURVE_SHRINKFATTEN, TFM_EDGE_SLIDE, TFM_MIRROR, TFM_MODAL_SNAP_INV_ON, TFM_PUSHPULL, TFM_RESIZE, TFM_ROTATION, TFM_SEQ_SLIDE, TFM_SHEAR, TFM_SHRINKFATTEN, TFM_TILT, TFM_TIME_DUPLICATE, TFM_TIME_EXTEND, TFM_TIME_SCALE, TFM_TIME_SLIDE, TFM_TIME_TRANSLATE, TFM_TOSPHERE, TFM_TRACKBALL, TFM_TRANSLATION, TFM_WARP, TransInfo::total, TRANS_CANCEL, TRANS_STARTING, wmKeyMapItem::type, wmOperator::type, ARegion::type, unit_m3(), wmKeyMapItem::val, TransInfo::values, WM_keymap_active(), and WM_paint_cursor_activate().
Referenced by transformops_data().
void initTransformOrientation (struct bContext * C, TransInfo * t)
Definition at line 490 of file transform_orientations.c.
References applyTransformOrientation(), TransInfo::ar, View3D::around, copy_m3_m3(), copy_m3_m4(), CTX_data_active_object(), CTX_wm_view3d(), TransInfo::current_orientation, ED_getTransformOrientationMatrix(), gimbal_axis(), Object::mode, normalize_m3(), OB_MODE_POSE, Object::obmat, ARegion::regiondata, ARegion::regiontype, RGN_TYPE_WINDOW, TransInfo::spacemtx, TransInfo::spacename, unit_m3(), V3D_ACTIVE, V3D_MANIP_GIMBAL, V3D_MANIP_GLOBAL, V3D_MANIP_LOCAL, V3D_MANIP_NORMAL, V3D_MANIP_VIEW, and RegionView3D::viewinv.
Referenced by initTransform().
int initTransInfo (struct bContext * C, TransInfo * t, struct wmOperator * op, struct wmEvent * event)
Definition at line 958 of file transform_generics.c.
References bScreen::animtimer, TransInfo::animtimer, TransInfo::ar, SpaceIpo::around, SpaceImage::around, View3D::around, TransInfo::around, BIF_countTransformOrientation(), TransInfo::center, TransInfo::con, copy_v2_v2_int(), CTX_data_edit_object(), CTX_data_scene(), CTX_data_tool_settings(), CTX_EDGE, CTX_NO_PET, CTX_wm_area(), CTX_wm_region(), CTX_wm_screen(), TransInfo::current_orientation, Object::data, TransInfo::data, ELEM3, TransInfo::event_type, TransInfo::ext, ListBase::first, View3D::flag, TransInfo::flag, TransInfo::handleEvent, TransInfo::helpline, HLP_NONE, TransCon::imval, TransInfo::imval, initNumInput(), TransInfo::mat, ME_EDIT_MIRROR_X, TransInfo::mirror, TransInfo::mode, TransInfo::mval, wmEvent::mval, NULL, TransInfo::num, OB_MESH, TransInfo::obedit, TransInfo::options, PROP_EDIT_CONNECTED, PROP_EDIT_OFF, PROP_EDIT_ON, ToolSettings::prop_mode, TransInfo::prop_mode, TransInfo::prop_size, ToolSettings::proportional, ToolSettings::proportional_objects, ToolSettings::proportional_size, wmOperator::ptr, TransInfo::redraw, RNA_boolean_get(), RNA_boolean_set(), RNA_enum_get(), RNA_float_get(), RNA_struct_find_property(), RNA_struct_property_is_set(), TransInfo::sa, SCE_SELECT_FACE, TransInfo::scene, ToolSettings::selectmode, TransInfo::settings, setTransformViewMatrices(), SPACE_EMPTY, SPACE_IMAGE, SPACE_IPO, SPACE_NODE, SPACE_VIEW3D, ScrArea::spacedata, ScrArea::spacetype, TransInfo::spacetype, T_MIRROR, T_MODAL, T_PROP_CONNECTED, T_PROP_EDIT, T_RELEASE_CONFIRM, T_V3D_ALIGN, TFM_CREASE, TFM_RESIZE, TFM_ROTATION, TFM_TRACKBALL, TransInfo::total, TransInfo::transform, View3D::twmode, View3D::twtype, TransInfo::twtype, Object::type, unit_m3(), USER_RELEASECONFIRM, ToolSettings::uvcalc_flag, UVCALC_TRANSFORM_CORRECT, ARegion::v2d, V3D_ALIGN, V3D_CENTER, V3D_LOCAL, V3D_MANIP_CUSTOM, V3D_MANIP_GLOBAL, TransInfo::val, TransInfo::vec, and TransInfo::view.
Referenced by calculateTransformCenter(), and initTransform().
void initTranslation (TransInfo * t)
Definition at line 3354 of file transform.c.
References TransInfo::ar, ELEM, NumInput::flag, TransInfo::flag, RegionView3D::gridview, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_VECTOR, TransInfo::mode, TransInfo::mouse, TransInfo::num, ARegion::regiondata, TransInfo::snap, SPACE_ACTION, SPACE_CLIP, SPACE_IMAGE, SPACE_VIEW3D, TransInfo::spacetype, TransInfo::state, T_2D_EDIT, TFM_TRANSLATION, TRANS_CANCEL, TransInfo::transform, and Translation().
Referenced by initTransform(), and transformEvent().
void initWarp (TransInfo * t)
Definition at line 2280 of file transform.c.
References TransInfo::center, TransData::center, copy_v3_v3(), TransInfo::data, TransInfo::flag, TransInfo::handleEvent, handleEventWarp(), i, NumInput::idx_max, TransInfo::idx_max, NumInput::increment, initMouseInputMode(), INPUT_HORIZONTAL_RATIO, M_PI, max, mid_v3_v3v3(), min, minmax_v3v3_v3(), TransInfo::mode, TransInfo::mouse, TransData::mtx, mul_m3_v3(), mul_m4_v3(), TransInfo::num, postInputWarp(), setInputPostFct(), TransInfo::snap, sub_v3_v3(), T_NO_CONSTRAINT, TFM_WARP, TransInfo::total, TransInfo::transform, TransInfo::val, TransInfo::viewmat, and Warp().
Referenced by initTransform().
int isLockConstraint (TransInfo * t)
Definition at line 999 of file transform_constraints.c.
References TransInfo::con, CON_AXIS0, CON_AXIS1, CON_AXIS2, and TransCon::mode.
Referenced by PushPull().
int Mirror (TransInfo * t, const int mval[2])
void postSelectConstraint (TransInfo * t)
Definition at line 851 of file transform_constraints.c.
References TransInfo::con, CON_AXIS0, CON_AXIS1, CON_AXIS2, CON_SELECT, TransCon::mode, TransInfo::redraw, setNearestAxis(), and startConstraint().
Referenced by transformEvent().
void postTrans (struct bContext * C, TransInfo * t)
Definition at line 1231 of file transform_generics.c.
References TransInfo::ar, BLI_freelistN(), CTX_wm_manager(), TransInfo::customData, TransInfo::customFree, MouseInput::data, TransInfo::data, TransInfo::data2d, TransInfo::draw_handle_apply, TransInfo::draw_handle_cursor, TransInfo::draw_handle_pixel, TransInfo::draw_handle_view, ED_region_draw_cb_exit(), ED_uvedit_live_unwrap_end(), TransInfo::ext, ListBase::first, SpaceImage::flag, TransData::flag, TransInfo::flag, TransData::hdata, MEM_freeN(), TransInfo::mouse, NULL, TransSnap::points, TransInfo::sa, SI_LIVE_UNWRAP, SPACE_IMAGE, SPACE_VIEW3D, ScrArea::spacedata, TransInfo::spacetype, TransInfo::state, T_FREE_CUSTOMDATA, T_MODAL, TD_BEZTRIPLE, TRANS_CANCEL, TransInfo::tsnap, TransInfo::twtype, View3D::twtype, ARegion::type, and WM_paint_cursor_end().
Referenced by calculateTransformCenter(), initTransform(), and transformEnd().
void projectFloatView (TransInfo * t, const float vec[3], float adr[2])
Definition at line 232 of file transform.c.
References TransInfo::ar, project_float_noclip(), projectIntView(), ARegion::regiontype, RGN_TYPE_WINDOW, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_VIEW3D, TransInfo::spacetype, and zero_v2().
Referenced by drawHelpline().
void projectIntView (TransInfo * t, const float vec[3], int adr[2])
Definition at line 179 of file transform.c.
References TransInfo::ar, ED_space_image_uv_aspect(), ELEM, ListBase::first, SpaceAction::flag, project_int_noclip(), ARegion::regiontype, RGN_TYPE_WINDOW, TransInfo::sa, SACTION_DRAWTIME, SPACE_ACTION, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_SEQ, SPACE_VIEW3D, ScrArea::spacedata, TransInfo::spacetype, UI_view2d_to_region_no_clip(), and TransInfo::view.
Referenced by calculateCenter(), calculateCenter2D(), initTimeScale(), projectFloatView(), and setNearestAxis3d().
void projectSVData (TransInfo * t, int final)
Definition at line 4698 of file transform.c.
References BLI_assert, BLI_smallhash_haskey(), BLI_smallhash_init(), BLI_smallhash_insert(), BLI_smallhash_lookup(), BLI_smallhash_release(), BMEditMesh::bm, BM_EDGES_OF_VERT, BM_elem_attrs_copy(), BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_hide_set, BM_ELEM_SELECT, BM_face_select_set(), BM_FACES_OF_VERT, BM_ITER_ELEM, BM_loop_interp_from_face(), BM_loop_interp_multires(), BM_LOOPS_OF_FACE, BM_vert_in_face(), TransInfo::customData, TransDataSlideVert::down, BMLoop::e, SlideData::em, BMLoop::f, FALSE, i, BMEdge::l, NULL, SlideData::origfaces, SlideData::perc, BMLoop::prev, BMLoop::radial_next, TransInfo::settings, BMesh::shapenr, SlideData::sv, TransDataSlideVert::up, ToolSettings::uvcalc_flag, UVCALC_TRANSFORM_CORRECT, BMLoop::v, and TransDataSlideVert::v.
Referenced by doEdgeSlide(), and special_aftertrans_update().
int PushPull (TransInfo * t, const int mval[2])
void recalcData (TransInfo * t)
Definition at line 885 of file transform_generics.c.
References flushTransNodes(), flushTransSeq(), recalcData_actedit(), recalcData_clip(), recalcData_graphedit(), recalcData_image(), recalcData_nla(), recalcData_view3d(), SPACE_ACTION, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_SEQ, SPACE_VIEW3D, and TransInfo::spacetype.
Referenced by Align(), applyTransObjects(), BakeTime(), Bevel(), BevelWeight(), BoneEnvelope(), BoneRoll(), BoneSize(), Crease(), CurveShrinkFatten(), EdgeSlide(), freeSlideVerts(), Mirror(), PushPull(), Resize(), restoreTransObjects(), Rotation(), SeqSlide(), Shear(), ShrinkFatten(), Tilt(), TimeScale(), TimeSlide(), TimeTranslate(), ToSphere(), Trackball(), Translation(), and Warp().
void remake_graph_transdata (TransInfo * t, struct ListBase * anim_data)
Definition at line 3756 of file transform_conversions.c.
References FCurve::bezt, bezt_to_beztmaps(), beztmap_to_data(), ListBase::first, SpaceIpo::flag, if(), bAnimListElem::key_data, MEM_freeN(), bAnimListElem::next, TransInfo::sa, SIPO_NOHANDLES, sort_time_beztmaps(), sort_time_fcurve(), ScrArea::spacedata, testhandles_fcurve(), and FCurve::totvert.
void removeAspectRatio (TransInfo * t, float * vec)
Definition at line 279 of file transform.c.
References ED_space_image_size(), ED_space_image_uv_aspect(), ListBase::first, SpaceImage::flag, TransInfo::mode, TransInfo::sa, SI_COORDFLOATS, SPACE_IMAGE, ScrArea::spacedata, TransInfo::spacetype, and TFM_TRANSLATION.
Referenced by postConstraintChecks(), and Translation().
void removeSnapPoint (TransInfo * t)
Definition at line 599 of file transform_snap.c.
References BLI_freelinkN(), ListBase::first, MULTI_POINTS, NULL, TransSnap::points, TransSnap::selectedPoint, TransSnap::status, TransInfo::tsnap, and updateSelectedSnapPoint().
Referenced by transformEvent().
void resetSnapping (TransInfo * t)
Definition at line 348 of file transform_snap.c.
References TransSnap::align, TransSnap::applySnap, TransSnap::last, TransSnap::mode, TransSnap::modeSelect, NULL, TransSnap::project, TransSnap::snapNormal, TransSnap::status, TransSnap::target, and TransInfo::tsnap.
Referenced by initSnapping().
void resetTransRestrictions (TransInfo * t)
Definition at line 952 of file transform_generics.c.
References TransInfo::flag, and T_ALL_RESTRICTIONS.
Referenced by transformEvent().
int Resize (TransInfo * t, const int mval[2])
Definition at line 2749 of file transform.c.
References applyNumInput(), TransCon::applySize, applySnapping(), TransInfo::auto_values, clipUVTransform(), TransInfo::con, constraintNumInput(), copy_m3_m3(), copy_v3_v3(), TransInfo::data, ED_area_headerprint(), ElementResize(), TransData::flag, TransInfo::flag, hasNumInput(), headerResize(), i, TransInfo::imval, TransInfo::mat, TransCon::mode, NULL, TransInfo::num, recalcData(), TransInfo::sa, size(), size_to_mat3(), snapGrid(), str, T_AUTOVALUES, T_CLIP_UV, T_USES_MANIPULATOR, TD_NOACTION, TD_SKIP, and TransInfo::values.
Referenced by initResize().
void restoreTransObjects (TransInfo * t)
Definition at line 1342 of file transform_generics.c.
References data, TransInfo::data, TransInfo::data2d, TransData2D::h1, TransData2D::h2, TransData2D::ih1, TransData2D::ih2, TransInfo::mat, recalcData(), restoreElement(), TransInfo::total, and unit_m3().
Referenced by transformEnd(), and transformEvent().
int Rotation (TransInfo * t, const int mval[2])
void saveTransform (struct bContext * C, struct TransInfo * t, struct wmOperator * op)
Definition at line 1397 of file transform.c.
References TransInfo::auto_values, TransInfo::axis, TransInfo::con, CON_APPLY, CON_AXIS0, CON_AXIS1, CON_AXIS2, CTX_data_tool_settings(), TransInfo::current_orientation, TransInfo::flag, if(), MOD_SNAP, TransCon::mode, TransInfo::mode, TransInfo::modifiers, TransInfo::obedit, TransCon::orientation, PROP_EDIT_CONNECTED, PROP_EDIT_OFF, PROP_EDIT_ON, TransInfo::prop_mode, ToolSettings::prop_mode, TransInfo::prop_size, ToolSettings::proportional, ToolSettings::proportional_objects, ToolSettings::proportional_size, wmOperator::ptr, RNA_enum_set(), RNA_float_set(), RNA_property_array_check(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_enum_set(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_is_set(), RNA_struct_find_property(), SCE_SNAP, ToolSettings::snap_flag, SPACE_VIEW3D, TransInfo::spacetype, T_AUTOVALUES, T_MIRROR, T_MODAL, T_PROP_CONNECTED, T_PROP_EDIT, View3D::twmode, TransInfo::values, and TransInfo::view.
Referenced by transformops_exit().
void selectConstraint (TransInfo * t)
Definition at line 843 of file transform_constraints.c.
References TransInfo::con, CON_SELECT, TransCon::mode, setNearestAxis(), and startConstraint().
Referenced by transformApply().
int SeqSlide (TransInfo * t, const int mval[2])
void setConstraint (TransInfo * t, float space[3][3], int mode, const char text[])
Definition at line 552 of file transform_constraints.c.
References applyAxisConstraintRot(), applyAxisConstraintSize(), applyAxisConstraintVec(), TransCon::applyRot, TransCon::applySize, TransCon::applyVec, BLI_strncpy(), TransInfo::con, copy_m3_m3(), TransCon::drawExtra, getConstraintMatrix(), TransCon::mode, TransCon::mtx, NULL, TransInfo::redraw, startConstraint(), and TransCon::text.
Referenced by setLocalConstraint(), and setUserConstraint().
void setCustomPoints (TransInfo * t, MouseInput * mi, int start[2], int end[2])
Referenced by initEdgeSlide().
void setInputPostFct (MouseInput * mi, void(*)(struct TransInfo *, float[3]) post)
Definition at line 374 of file transform_input.c.
References MouseInput::post, and post.
Referenced by initRotation(), initShear(), and initWarp().
void setLocalConstraint (TransInfo * t, int mode, const char text[])
Definition at line 568 of file transform_constraints.c.
References applyObjectConstraintRot(), applyObjectConstraintSize(), applyObjectConstraintVec(), TransCon::applyRot, TransCon::applySize, TransCon::applyVec, TransData::axismtx, BLI_strncpy(), TransInfo::con, copy_m3_m3(), copy_m3_m4(), TransInfo::data, TransCon::drawExtra, drawObjectConstraint(), TransInfo::flag, getConstraintMatrix(), TransCon::mode, TransCon::mtx, normalize_m3(), Scene::obedit, Object::obmat, TransInfo::redraw, TransInfo::scene, setConstraint(), startConstraint(), T_EDIT, TransCon::text, and TransInfo::total.
Referenced by setUserConstraint(), and transformEvent().
void setNearestAxis (TransInfo * t)
Definition at line 956 of file transform_constraints.c.
References TransInfo::con, CON_AXIS0, CON_AXIS1, CON_AXIS2, getConstraintMatrix(), TransCon::mode, setNearestAxis2d(), setNearestAxis3d(), SPACE_VIEW3D, and TransInfo::spacetype.
Referenced by initSelectConstraint(), postSelectConstraint(), and selectConstraint().
void setTransformViewMatrices (TransInfo * t)
Definition at line 105 of file transform.c.
References TransInfo::ar, calculateCenter2D(), copy_m4_m4(), RegionView3D::persinv, TransInfo::persinv, RegionView3D::persmat, TransInfo::persmat, RegionView3D::persp, TransInfo::persp, ARegion::regiondata, ARegion::regiontype, RGN_TYPE_WINDOW, RV3D_ORTHO, SPACE_VIEW3D, TransInfo::spacetype, unit_m4(), RegionView3D::viewinv, TransInfo::viewinv, RegionView3D::viewmat, and TransInfo::viewmat.
Referenced by initTransInfo(), and view_editmove().
void setUserConstraint (TransInfo * t, short orientation, int mode, const char text[])
Definition at line 603 of file transform_constraints.c.
References BLI_snprintf(), TransInfo::con, CON_USER, MAT3_UNITY, TransCon::mode, TransCon::orientation, setConstraint(), setLocalConstraint(), TransInfo::spacemtx, TransInfo::spacename, V3D_MANIP_GIMBAL, V3D_MANIP_GLOBAL, V3D_MANIP_LOCAL, V3D_MANIP_NORMAL, and V3D_MANIP_VIEW.
Referenced by initTransform(), and transformEvent().
int Shear (TransInfo * t, const int mval[2])
int ShrinkFatten (TransInfo * t, const int mval[2])
void snapGrid (TransInfo * t, float * val)
Definition at line 1973 of file transform_snap.c.
References activeSnap(), BIG_GEARS, MOD_PRECISION, TransSnap::mode, TransInfo::modifiers, NO_GEARS, SCE_SNAP_MODE_INCREMENT, SMALL_GEARS, snapGridAction(), and TransInfo::tsnap.
Referenced by BakeTime(), Bevel(), BevelWeight(), BoneEnvelope(), BoneRoll(), BoneSize(), Crease(), CurveShrinkFatten(), EdgeSlide(), postConstraintChecks(), PushPull(), Resize(), Rotation(), SeqSlide(), Shear(), ShrinkFatten(), Tilt(), ToSphere(), Trackball(), Translation(), and Warp().
void snapGridAction (TransInfo * t, float * val, GearsType action)
Definition at line 1961 of file transform_snap.c.
References applyGrid(), BIG_GEARS, TransInfo::idx_max, NO_GEARS, SMALL_GEARS, and TransInfo::snap.
Referenced by CalcSnapGrid(), and snapGrid().
void sort_trans_data_dist (TransInfo * t)
Definition at line 172 of file transform_conversions.c.
References TransInfo::data, TransData::flag, i, qsort_trans_data(), TD_SELECTED, and TransInfo::total.
Referenced by createTransData(), and transformEvent().
void special_aftertrans_update (struct bContext * C, TransInfo * t)
Definition at line 4867 of file transform_conversions.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIM_editkeyframes_refresh(), ANIM_nla_mapping_apply_fcurve(), ANIM_nla_mapping_get(), ANIMCONT_ACTION, ANIMCONT_DOPESHEET, ANIMCONT_GPENCIL, ANIMCONT_SHAPEKEY, ANIMFILTER_CURVE_VISIBLE, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, apply_targetless_ik(), ARM_DELAYDEFORM, TransInfo::around, autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), Object::avs, Scene::basact, BKE_nlastrips_clear_metas(), BKE_nlatrack_sort_strips(), BKE_ptcache_ids_from_object(), BKE_ptcache_object_reset(), BLI_freelistN(), BMEdit_FromObject(), PTCacheID::cache, bPose::chanbase, clear_trans_object_base_flags(), CONSTRAINT_IK_AUTO, count_set_pose_transflags(), CTX_AUTOCONFIRM, TransInfo::customData, DAG_id_tag_update(), TransInfo::data, data, Object::data, bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, ED_context_get_markers(), ED_markers_post_apply_transform(), ED_nla_postop_refresh(), ED_node_link_insert(), ED_node_link_intersect_test(), ED_node_update_hierarchy(), ED_objects_recalculate_paths(), ED_space_clip(), EDBM_automerge(), SpaceNode::edittree, ELEM, FALSE, filter(), ListBase::first, PointCache::flag, TransData::flag, bArmature::flag, bKinematicConstraint::flag, TransInfo::flag, SpaceIpo::flag, SpaceAction::flag, SpaceSeq::flag, TransInfo::frame_side, freeSlideTempFaces(), G, has_targetless_ik(), i, bGPdata::id, Object::id, MovieClip::id, ID_REAL_USERS, if(), bAnimListElem::key_data, Scene::markers, MAX_DUPLI_RECUR, mesh_octree_table(), Object::mode, TransInfo::mode, MOTIONPATH_BAKE_HAS_PATHS, NC_SCENE, ND_NODES, PTCacheID::next, bPoseChannel::next, ID::next, bAnimListElem::next, Scene::nodetree, nodeUpdateID(), NULL, TransData::ob, ob_get_key(), OB_MESH, OB_MODE_PARTICLE_EDIT, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, TransInfo::obedit, Base::object, TransInfo::options, bAnimVizSettings::path_bakeflag, PE_get_current(), SlideData::perc, Object::pose, pose_grab_with_ik_clear(), TransInfo::poseobj, posttrans_action_clean(), posttrans_fcurve_clean(), posttrans_gpd_clean(), projectSVData(), PTCACHE_OUTDATED, PTCACHE_RESET_OUTDATED, PTCACHE_TYPE_PARTICLES, Object::recalc, TransInfo::redraw, TransInfo::sa, SACTION_MARKERS_MOVE, SACTION_MOVING, SACTION_NOTRANSKEYCULL, TransInfo::scene, SEQ_MARKER_TRANS, SIPO_NOHANDLES, SIPO_NOTRANSKEYCULL, SPACE_ACTION, SPACE_CLIP, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_SEQ, SPACE_VIEW3D, ScrArea::spacedata, TransInfo::spacetype, TransInfo::state, NlaTrack::strips, T_AUTOIK, T_POSE, TD_NOACTION, TD_SKIP, TFM_DUMMY, TFM_EDGE_SLIDE, TFM_SEQ_SLIDE, TFM_TIME_DUPLICATE, TFM_TIME_EXTEND, TFM_TIME_SCALE, TFM_TIME_TRANSLATE, TFM_TRANSLATION, TransInfo::total, TRANS_CANCEL, transformApply(), TREDRAW_HARD, TRUE, PTCacheID::type, Object::type, TransInfo::values, TransInfo::view, where_is_pose(), and WM_event_add_notifier().
Referenced by calculateTransformCenter(), and transformEnd().
void startConstraint (TransInfo * t)
Definition at line 786 of file transform_constraints.c.
References TransInfo::con, CON_APPLY, getConstraintSpaceDimension(), NumInput::idx_max, TransInfo::idx_max, MIN2, TransCon::mode, TransInfo::num, and TransCon::text.
Referenced by postSelectConstraint(), selectConstraint(), setConstraint(), setLocalConstraint(), and btDiscreteDynamicsWorld::solveConstraints().
void stopConstraint (TransInfo * t)
Definition at line 793 of file transform_constraints.c.
References TransInfo::con, CON_APPLY, CON_SELECT, NumInput::idx_max, TransInfo::idx_max, TransCon::mode, TransInfo::num, and TransCon::text.
Referenced by transformEvent().
int Tilt (TransInfo * t, const int mval[2])
int TimeScale (TransInfo * t, const int mval[2])
int TimeSlide (TransInfo * t, const int mval[2])
Definition at line 5769 of file transform.c.
References applyNumInput(), applyTimeSlide(), TransInfo::customData, ED_area_headerprint(), headerTimeSlide(), TransInfo::imval, TransInfo::num, recalcData(), TransInfo::sa, str, UI_view2d_region_to_view(), TransInfo::values, TransInfo::vec, and TransInfo::view.
Referenced by initTimeSlide().
int TimeTranslate (TransInfo * t, const int mval[2])
Definition at line 5638 of file transform.c.
References applyNumInput(), applyTimeTranslate(), ED_area_headerprint(), headerTimeTranslate(), TransInfo::imval, TransInfo::num, recalcData(), TransInfo::sa, str, UI_view2d_region_to_view(), TransInfo::values, TransInfo::vec, and TransInfo::view.
Referenced by initTimeTranslate().
int ToSphere (TransInfo * t, const int mval[2])
int Trackball (TransInfo * t, const int mval[2])
void transform_autoik_update (TransInfo * t, short mode)
Definition at line 829 of file transform_conversions.c.
References ToolSettings::autoik_chainlen, bPose::chanbase, ELEM, ListBase::first, bPoseChannel::next, NULL, pchan_autoik_adjust(), Object::pose, TransInfo::poseobj, and TransInfo::settings.
Referenced by createTransPose(), and transformEvent().
struct wmKeyMap* transform_modal_keymap (struct wmKeyConfig * keyconf) [read]
Definition at line 511 of file transform.c.
References AKEY, ESCKEY, GKEY, KM_ALT, KM_ANY, KM_PRESS, KM_RELEASE, KM_SHIFT, LEFTCTRLKEY, LEFTMOUSE, wmKeyMap::modal_items, NULL, NUM_MODAL_INCREMENT_DOWN, NUM_MODAL_INCREMENT_UP, PADENTER, PAGEDOWNKEY, PAGEUPKEY, RETKEY, RIGHTCTRLKEY, RKEY, SKEY, TABKEY, TFM_MODAL_ADD_SNAP, TFM_MODAL_AUTOIK_LEN_DEC, TFM_MODAL_AUTOIK_LEN_INC, TFM_MODAL_AXIS_X, TFM_MODAL_AXIS_Y, TFM_MODAL_AXIS_Z, TFM_MODAL_CANCEL, TFM_MODAL_CONFIRM, TFM_MODAL_CONS_OFF, TFM_MODAL_PLANE_X, TFM_MODAL_PLANE_Y, TFM_MODAL_PLANE_Z, TFM_MODAL_PROPSIZE_DOWN, TFM_MODAL_PROPSIZE_UP, TFM_MODAL_REMOVE_SNAP, TFM_MODAL_RESIZE, TFM_MODAL_ROTATE, TFM_MODAL_SNAP_INV_OFF, TFM_MODAL_SNAP_INV_ON, TFM_MODAL_SNAP_TOGGLE, TFM_MODAL_TRANSLATE, WHEELDOWNMOUSE, WHEELUPMOUSE, WM_modalkeymap_add(), WM_modalkeymap_add_item(), and WM_modalkeymap_get().
Referenced by transform_keymap_for_space().
void TRANSFORM_OT_transform (struct wmOperatorType * ot)
Definition at line 801 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_ALIGN_SNAP, P_AXIS, P_CONSTRAINT, P_MIRROR, P_PROPORTIONAL, wmOperatorType::poll, PROP_HIDDEN, RNA_def_enum(), RNA_def_float_vector(), RNA_def_property_flag(), wmOperatorType::srna, TFM_TRANSLATION, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), and Transform_Properties().
Referenced by transform_operatortypes().
void transformApply (struct bContext * C, TransInfo * t)
Definition at line 1796 of file transform.c.
References BKE_ptcache_get_continue_physics(), C, TransInfo::context, CTX_AUTOCONFIRM, TransInfo::draw_handle_apply, TransInfo::mval, NULL, TransInfo::options, TransInfo::redraw, selectConstraint(), TransInfo::state, TRANS_CONFIRM, TransInfo::transform, TREDRAW_HARD, TREDRAW_NOTHING, TREDRAW_SOFT, and viewRedrawForce().
Referenced by drawTransformApply(), special_aftertrans_update(), transform_exec(), and transform_modal().
int transformEnd (struct bContext * C, TransInfo * t)
Definition at line 1839 of file transform.c.
References C, TransInfo::context, doEdgeSlide(), TransInfo::mode, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, postTrans(), restoreTransObjects(), special_aftertrans_update(), TransInfo::state, TFM_EDGE_SLIDE, TRANS_CANCEL, TRANS_RUNNING, TRANS_STARTING, TransInfo::undostr, viewRedrawForce(), and viewRedrawPost().
Referenced by transform_cancel(), transform_exec(), and transform_modal().
int transformEvent (TransInfo * t, struct wmEvent * event)
Definition at line 581 of file transform.c.
References addSnapPoint(), wmEvent::alt, applyMouseInput(), BIF_selectOrientation(), calc_manipulator_stats(), calculatePropRatio(), CKEY, TransInfo::con, CON_APPLY, CON_AXIS0, CON_AXIS1, CON_AXIS2, CON_SELECT, constraintModeToChar(), copy_m3_m4(), copy_v2_v2_int(), CTX_MOVIECLIP, CTX_TEXTURE, TransInfo::current_orientation, ELEM3, ELEM4, ESCKEY, EVT_MODAL_MAP, TransInfo::flag, G, GKEY, TransInfo::handleEvent, handleMouseInput(), handleNumInput(), handleSnapping(), initResize(), initRotation(), initSelectConstraint(), initSnapping(), initTrackball(), initTranslation(), KM_PRESS, KM_RELEASE, TransInfo::launch_event, LEFTMOUSE, LEFTSHIFTKEY, MAT3_UNITY, MIDDLEMOUSE, MIN2, MOD_CONSTRAINT_PLANE, MOD_CONSTRAINT_SELECT, MOD_SNAP, MOD_SNAP_INVERT, TransInfo::mode, TransCon::mode, TransInfo::modifiers, TransInfo::mouse, MOUSEMOVE, wmEvent::mval, TransInfo::mval, NULL, TransInfo::num, OKEY, OPERATOR_PASS_THROUGH, TransInfo::options, TransCon::orientation, PADENTER, PADMINUS, PADPLUSKEY, PAGEDOWNKEY, PAGEUPKEY, TransInfo::persp, postSelectConstraint(), TransInfo::prop_mode, PROP_MODE_MAX, TransInfo::prop_size, TransInfo::redraw, removeSnapPoint(), resetTransRestrictions(), restoreTransObjects(), RETKEY, RIGHTMOUSE, RIGHTSHIFTKEY, RKEY, RV3D_ORTHO, setLocalConstraint(), setUserConstraint(), wmEvent::shift, SKEY, sort_trans_data_dist(), SPACE_VIEW3D, SPACEKEY, TransInfo::spacemtx, TransInfo::spacename, TransInfo::spacetype, TransInfo::state, stopConstraint(), T_2D_EDIT, T_ALT_TRANSFORM, T_AUTOIK, T_CAMERA, T_NO_CONSTRAINT, T_PROP_CONNECTED, T_PROP_EDIT, T_RELEASE_CONFIRM, TFM_MODAL_ADD_SNAP, TFM_MODAL_AUTOIK_LEN_DEC, TFM_MODAL_AUTOIK_LEN_INC, TFM_MODAL_AXIS_X, TFM_MODAL_AXIS_Y, TFM_MODAL_AXIS_Z, TFM_MODAL_CANCEL, TFM_MODAL_CONFIRM, TFM_MODAL_CONS_OFF, TFM_MODAL_PLANE_X, TFM_MODAL_PLANE_Y, TFM_MODAL_PLANE_Z, TFM_MODAL_PROPSIZE_DOWN, TFM_MODAL_PROPSIZE_UP, TFM_MODAL_REMOVE_SNAP, TFM_MODAL_RESIZE, TFM_MODAL_ROTATE, TFM_MODAL_SNAP_INV_OFF, TFM_MODAL_SNAP_INV_ON, TFM_MODAL_SNAP_TOGGLE, TFM_MODAL_TRANSLATE, TFM_RESIZE, TFM_ROTATION, TFM_TRACKBALL, TFM_TRANSLATION, TRANS_CANCEL, TRANS_CONFIRM, TRANS_RUNNING, TRANS_STARTING, transform_autoik_update(), TREDRAW_HARD, wmEvent::type, V3D_MANIP_GLOBAL, V3D_MANIP_LOCAL, wmEvent::val, TransInfo::values, TransInfo::view, view_editmove(), WHEELDOWNMOUSE, WHEELUPMOUSE, XKEY, YKEY, and ZKEY.
Referenced by transform_modal().
int Translation (TransInfo * t, const int mval[2])
int updateSelectedSnapPoint (TransInfo * t)
Definition at line 565 of file transform_snap.c.
References TransInfo::ar, TransSnapPoint::co, ListBase::first, MULTI_POINTS, TransInfo::mval, TransSnapPoint::next, NULL, p, TransSnap::points, project_int(), TransSnap::selectedPoint, TransSnap::status, and TransInfo::tsnap.
Referenced by handleSnapping(), and removeSnapPoint().
int usingSnappingNormal (TransInfo * t)
Definition at line 364 of file transform_snap.c.
References TransSnap::align, and TransInfo::tsnap.
Referenced by applyTranslation(), and drawSnapping().
int validSnap (TransInfo * t)
Definition at line 130 of file transform_snap.c.
References MULTI_POINTS, POINT_INIT, TransSnap::status, TARGET_INIT, and TransInfo::tsnap.
Referenced by applySnapping(), drawSnapping(), and validSnappingNormal().
int validSnappingNormal (TransInfo * t)
Definition at line 369 of file transform_snap.c.
References dot_v3v3(), TransSnap::snapNormal, TransInfo::tsnap, and validSnap().
Referenced by applyTranslation(), and drawSnapping().
int Warp (TransInfo * t, const int mval[2])