Blender: clip_intern.h File Reference
clip_intern.h File Reference
Functions
void ED_clip_buttons_register (struct ARegionType *art)
void clip_draw_main (struct SpaceClip *sc, struct ARegion *ar, struct Scene *scene)
void clip_draw_grease_pencil (struct bContext *C, int onlyv2d)
void clip_draw_curfra_label (struct SpaceClip *sc, float x, float y)
void clip_draw_graph (struct SpaceClip *sc, struct ARegion *ar, struct Scene *scene)
void ED_clip_graph_center_current_frame (struct Scene *scene, struct ARegion *ar)
void CLIP_OT_graph_select (struct wmOperatorType *ot)
void CLIP_OT_graph_select_border (struct wmOperatorType *ot)
void CLIP_OT_graph_select_all_markers (struct wmOperatorType *ot)
void CLIP_OT_graph_delete_curve (struct wmOperatorType *ot)
void CLIP_OT_graph_delete_knot (struct wmOperatorType *ot)
void CLIP_OT_graph_view_all (struct wmOperatorType *ot)
void CLIP_OT_graph_center_current_frame (struct wmOperatorType *ot)
void CLIP_OT_graph_disable_markers (struct wmOperatorType *ot)
void CLIP_OT_open (struct wmOperatorType *ot)
void CLIP_OT_reload (struct wmOperatorType *ot)
void CLIP_OT_view_pan (struct wmOperatorType *ot)
void CLIP_OT_view_zoom (wmOperatorType *ot)
void CLIP_OT_view_zoom_in (struct wmOperatorType *ot)
void CLIP_OT_view_zoom_out (struct wmOperatorType *ot)
void CLIP_OT_view_zoom_ratio (struct wmOperatorType *ot)
void CLIP_OT_view_all (struct wmOperatorType *ot)
void CLIP_OT_view_selected (struct wmOperatorType *ot)
void CLIP_OT_change_frame (wmOperatorType *ot)
void CLIP_OT_rebuild_proxy (struct wmOperatorType *ot)
void CLIP_OT_mode_set (struct wmOperatorType *ot)
void CLIP_OT_tools (struct wmOperatorType *ot)
void CLIP_OT_properties (struct wmOperatorType *ot)
void ED_clip_tool_props_register (struct ARegionType *art)
void clip_graph_tracking_values_iterate_track (struct SpaceClip *sc, struct MovieTrackingTrack *track, void *userdata, void(*func)(void *userdata, struct MovieTrackingTrack *track, struct MovieTrackingMarker *marker, int coord, float val), void(*segment_start)(void *userdata, struct MovieTrackingTrack *track, int coord), void(*segment_end)(void *userdata))
void clip_graph_tracking_values_iterate (struct SpaceClip *sc, void *userdata, void(*func)(void *userdata, struct MovieTrackingTrack *track, struct MovieTrackingMarker *marker, int coord, float val), void(*segment_start)(void *userdata, struct MovieTrackingTrack *track, int coord), void(*segment_end)(void *userdata))
void clip_graph_tracking_iterate (struct SpaceClip *sc, void *userdata, void(*func)(void *userdata, struct MovieTrackingMarker *marker))
void clip_delete_track (struct bContext *C, struct MovieClip *clip, struct ListBase *tracksbase, struct MovieTrackingTrack *track)
void clip_delete_marker (struct bContext *C, struct MovieClip *clip, struct ListBase *tracksbase, struct MovieTrackingTrack *track, struct MovieTrackingMarker *marker)
void clip_view_center_to_point (struct SpaceClip *sc, float x, float y)
void CLIP_OT_select (struct wmOperatorType *ot)
void CLIP_OT_select_all (struct wmOperatorType *ot)
void CLIP_OT_select_border (struct wmOperatorType *ot)
void CLIP_OT_select_circle (struct wmOperatorType *ot)
void CLIP_OT_select_grouped (struct wmOperatorType *ot)
void CLIP_OT_add_marker (struct wmOperatorType *ot)
void CLIP_OT_delete_track (struct wmOperatorType *ot)
void CLIP_OT_delete_marker (struct wmOperatorType *ot)
void CLIP_OT_track_markers (struct wmOperatorType *ot)
void CLIP_OT_solve_camera (struct wmOperatorType *ot)
void CLIP_OT_clear_solution (struct wmOperatorType *ot)
void CLIP_OT_clear_track_path (struct wmOperatorType *ot)
void CLIP_OT_join_tracks (struct wmOperatorType *ot)
void CLIP_OT_disable_markers (struct wmOperatorType *ot)
void CLIP_OT_hide_tracks (struct wmOperatorType *ot)
void CLIP_OT_hide_tracks_clear (struct wmOperatorType *ot)
void CLIP_OT_lock_tracks (struct wmOperatorType *ot)
void CLIP_OT_set_origin (struct wmOperatorType *ot)
void CLIP_OT_set_plane (struct wmOperatorType *ot)
void CLIP_OT_set_axis (struct wmOperatorType *ot)
void CLIP_OT_set_scale (struct wmOperatorType *ot)
void CLIP_OT_set_solution_scale (struct wmOperatorType *ot)
void CLIP_OT_set_center_principal (struct wmOperatorType *ot)
void CLIP_OT_slide_marker (struct wmOperatorType *ot)
void CLIP_OT_frame_jump (struct wmOperatorType *ot)
void CLIP_OT_track_copy_color (struct wmOperatorType *ot)
void CLIP_OT_detect_features (struct wmOperatorType *ot)
void CLIP_OT_stabilize_2d_add (struct wmOperatorType *ot)
void CLIP_OT_stabilize_2d_remove (struct wmOperatorType *ot)
void CLIP_OT_stabilize_2d_select (struct wmOperatorType *ot)
void CLIP_OT_stabilize_2d_set_rotation (struct wmOperatorType *ot)
void CLIP_OT_clean_tracks (struct wmOperatorType *ot)
void CLIP_OT_tracking_object_new (struct wmOperatorType *ot)
void CLIP_OT_tracking_object_remove (struct wmOperatorType *ot)
void CLIP_OT_copy_tracks (struct wmOperatorType *ot)
void CLIP_OT_paste_tracks (struct wmOperatorType *ot)
Detailed Description
Definition in file clip_intern.h.
Function Documentation
void clip_delete_marker (struct bContext * C, struct MovieClip * clip, struct ListBase * tracksbase, struct MovieTrackingTrack * track, struct MovieTrackingMarker * marker)
Definition at line 200 of file clip_utils.c.
References BKE_tracking_delete_marker(), clip_delete_track(), MovieTrackingMarker::framenr, MovieTrackingTrack::markersnr, NA_EDITED, NC_MOVIECLIP, and WM_event_add_notifier().
Referenced by delete_knot_exec(), and delete_marker_exec().
void clip_delete_track (struct bContext * C, struct MovieClip * clip, struct ListBase * tracksbase, struct MovieTrackingTrack * track)
Definition at line 163 of file clip_utils.c.
References MovieTracking::act_track, BKE_tracking_active_track(), BKE_tracking_free_track(), BLI_freelinkN(), DAG_id_tag_update(), FALSE, MovieTrackingTrack::flag, MovieClip::id, NA_EDITED, NC_MOVIECLIP, NC_SPACE, ND_DISPLAY, ND_SPACE_VIEW3D, NULL, MovieTrackingStabilization::ok, MovieTrackingStabilization::rot_track, MovieTracking::stabilization, TRACK_HAS_BUNDLE, MovieClip::tracking, TRUE, and WM_event_add_notifier().
Referenced by clip_delete_marker(), delete_curve_exec(), and delete_track_exec().
void clip_draw_curfra_label (struct SpaceClip * sc, float x, float y)
Definition at line 74 of file clip_draw.c.
References BLF_draw(), BLF_position(), BLF_size(), BLF_width_and_height(), BLI_snprintf(), MovieClipUser::framenr, TH_TEXT, UI_GetStyle(), UI_ThemeColor(), uiFontStyle::uifont_id, SpaceClip::user, and uiStyle::widget.
Referenced by draw_graph_cfra(), and draw_movieclip_cache().
void clip_draw_graph (struct SpaceClip * sc, struct ARegion * ar, struct Scene * scene)
Definition at line 262 of file clip_graph_draw.c.
References draw_frame_curves(), draw_graph_cfra(), draw_graph_sfra_efra(), draw_tracks_curves(), ED_space_clip(), SpaceClip::flag, SC_SHOW_GRAPH_FRAMES, SC_SHOW_GRAPH_TRACKS, UI_view2d_grid_calc(), UI_view2d_grid_draw(), UI_view2d_grid_free(), ARegion::v2d, V2D_GRID_NOCLAMP, V2D_GRIDLINES_ALL, V2D_UNIT_FRAMESCALE, V2D_UNIT_VALUES, ARegion::winx, and ARegion::winy.
Referenced by clip_preview_area_draw().
void clip_draw_grease_pencil (struct bContext * C, int onlyv2d)
Definition at line 1393 of file clip_draw.c.
References CTX_wm_space_clip(), draw_gpencil_2dimage(), draw_gpencil_view2d(), ED_space_clip(), ED_space_clip_get_buffer(), SpaceClip::flag, glMultMatrixf, IMB_freeImBuf(), SpaceClip::mode, SC_MANUAL_CALIBRATION, SC_MODE_DISTORTION, and SpaceClip::unistabmat.
Referenced by clip_main_area_draw().
void clip_draw_main (struct SpaceClip * sc, struct ARegion * ar, struct Scene * scene)
Definition at line 1333 of file clip_draw.c.
References SpaceClip::angle, BKE_tracking_stabdata_to_mat4(), MovieTracking::camera, copy_v2_v2(), draw_distortion(), draw_movieclip_buffer(), draw_movieclip_cache(), draw_movieclip_notes(), draw_tracking_tracks(), ED_space_clip(), ED_space_clip_get_buffer(), ED_space_clip_get_stable_buffer(), ED_space_clip_size(), ED_space_clip_zoom(), SpaceClip::flag, IMB_freeImBuf(), invert_m4_m4(), SpaceClip::loc, mul_serie_m4(), mul_v2_v2fl(), NULL, MovieTrackingCamera::pixel_aspect, SC_SHOW_STABLE, SpaceClip::scale, SpaceClip::stabmat, MovieClip::tracking, SpaceClip::unistabmat, unit_m4(), ImBuf::x, and zero_v2().
Referenced by clip_main_area_draw().
void clip_graph_tracking_iterate (struct SpaceClip * sc, void * userdata, void(*)(void *userdata, struct MovieTrackingMarker *marker) func)
Referenced by mouse_select_curve(), and mouse_select_knot().
void clip_graph_tracking_values_iterate (struct SpaceClip * sc, void * userdata, void(*)(void *userdata, struct MovieTrackingTrack *track, struct MovieTrackingMarker *marker, int coord, float val) func, void(*)(void *userdata, struct MovieTrackingTrack *track, int coord) segment_start, void(*)(void *userdata) segment_end)
Referenced by draw_tracks_curves(), mouse_select_curve(), and view_all_exec().
void clip_graph_tracking_values_iterate_track (struct SpaceClip * sc, struct MovieTrackingTrack * track, void * userdata, void(*)(void *userdata, struct MovieTrackingTrack *track, struct MovieTrackingMarker *marker, int coord, float val) func, void(*)(void *userdata, struct MovieTrackingTrack *track, int coord) segment_start, void(*)(void *userdata) segment_end)
Referenced by border_select_graph_exec(), clip_graph_tracking_values_iterate(), and mouse_select_knot().
void CLIP_OT_add_marker (struct wmOperatorType * ot)
Definition at line 149 of file tracking_ops.c.
References add_marker_exec(), add_marker_invoke(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_vector(), space_clip_frame_poll(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_change_frame (wmOperatorType * ot)
Definition at line 848 of file clip_ops.c.
References change_frame_exec(), change_frame_invoke(), change_frame_modal(), change_frame_poll(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MAXFRAME, MINAFRAME, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_clean_tracks (struct wmOperatorType * ot)
Definition at line 3497 of file tracking_ops.c.
References clean_tracks_exec(), clean_tracks_invoke(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_float(), RNA_def_int(), wmOperatorType::srna, TRACKING_CLEAN_DELETE_SEGMENT, TRACKING_CLEAN_DELETE_TRACK, and TRACKING_CLEAN_SELECT.
Referenced by clip_operatortypes().
void CLIP_OT_clear_solution (struct wmOperatorType * ot)
Definition at line 1842 of file tracking_ops.c.
References clear_solution_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by clip_operatortypes().
void CLIP_OT_clear_track_path (struct wmOperatorType * ot)
Definition at line 1887 of file tracking_ops.c.
References clear_track_path_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_enum(), wmOperatorType::srna, TRACK_CLEAR_ALL, TRACK_CLEAR_REMAINED, and TRACK_CLEAR_UPTO.
Referenced by clip_operatortypes().
void CLIP_OT_copy_tracks (struct wmOperatorType * ot)
Definition at line 3611 of file tracking_ops.c.
References copy_tracks_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and wmOperatorType::poll.
Referenced by clip_operatortypes().
void CLIP_OT_delete_marker (struct wmOperatorType * ot)
Definition at line 245 of file tracking_ops.c.
References delete_marker_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by clip_operatortypes().
void CLIP_OT_delete_track (struct wmOperatorType * ot)
Definition at line 194 of file tracking_ops.c.
References delete_track_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by clip_operatortypes().
void CLIP_OT_detect_features (struct wmOperatorType * ot)
Definition at line 2866 of file tracking_ops.c.
References wmOperatorType::description, detect_features_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_int(), space_clip_frame_poll(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_disable_markers (struct wmOperatorType * ot)
Definition at line 1945 of file tracking_ops.c.
References wmOperatorType::description, disable_markers_exec(), ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_frame_jump (struct wmOperatorType * ot)
Definition at line 2960 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, frame_jump_exec(), wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), space_clip_frame_poll(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_graph_center_current_frame (struct wmOperatorType * ot)
Definition at line 631 of file clip_graph_ops.c.
References center_current_frame_exec(), wmOperatorType::description, ED_space_clip_graph_poll(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by clip_operatortypes().
void CLIP_OT_graph_delete_curve (struct wmOperatorType * ot)
Definition at line 479 of file clip_graph_ops.c.
References delete_curve_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by clip_operatortypes().
void CLIP_OT_graph_delete_knot (struct wmOperatorType * ot)
Definition at line 521 of file clip_graph_ops.c.
References delete_knot_exec(), wmOperatorType::description, ED_space_clip_graph_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by clip_operatortypes().
void CLIP_OT_graph_disable_markers (struct wmOperatorType * ot)
Definition at line 678 of file clip_graph_ops.c.
References wmOperatorType::description, ED_space_clip_graph_poll(), wmOperatorType::exec, wmOperatorType::flag, graph_disable_markers_exec(), wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_graph_select (struct wmOperatorType * ot)
Definition at line 289 of file clip_graph_ops.c.
References wmOperatorType::description, ED_space_clip_graph_poll(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_vector(), select_exec(), select_invoke(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_graph_select_all_markers (struct wmOperatorType * ot)
Definition at line 446 of file clip_graph_ops.c.
References wmOperatorType::description, ED_space_clip_graph_poll(), wmOperatorType::exec, wmOperatorType::flag, graph_select_all_markers_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_properties_select_all().
Referenced by clip_operatortypes().
void CLIP_OT_graph_select_border (struct wmOperatorType * ot)
Definition at line 377 of file clip_graph_ops.c.
References border_select_graph_exec(), wmOperatorType::description, ED_space_clip_graph_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, TRUE, WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by clip_operatortypes().
void CLIP_OT_graph_view_all (struct wmOperatorType * ot)
Definition at line 595 of file clip_graph_ops.c.
References wmOperatorType::description, ED_space_clip_graph_poll(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and view_all_exec().
Referenced by clip_operatortypes().
void CLIP_OT_hide_tracks (struct wmOperatorType * ot)
Definition at line 2752 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, hide_tracks_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_hide_tracks_clear (struct wmOperatorType * ot)
Definition at line 2791 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, hide_tracks_clear_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by clip_operatortypes().
void CLIP_OT_join_tracks (struct wmOperatorType * ot)
Definition at line 3025 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, join_tracks_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and space_clip_frame_poll().
Referenced by clip_operatortypes().
void CLIP_OT_lock_tracks (struct wmOperatorType * ot)
Definition at line 3068 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, lock_tracks_exec(), wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_mode_set (struct wmOperatorType * ot)
Definition at line 1057 of file clip_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::idname, mode_set_exec(), wmOperatorType::name, NULL, wmOperatorType::poll, RNA_def_boolean(), RNA_def_enum(), SC_MODE_DISTORTION, SC_MODE_RECONSTRUCTION, SC_MODE_TRACKING, and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_open (struct wmOperatorType * ot)
Definition at line 222 of file clip_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, IMAGEFILE, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, open_cancel(), open_exec(), open_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, WM_FILESEL_FILEPATH, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by clip_operatortypes().
void CLIP_OT_paste_tracks (struct wmOperatorType * ot)
Definition at line 3651 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, paste_tracks_exec(), paste_tracks_poll(), and wmOperatorType::poll.
Referenced by clip_operatortypes().
void CLIP_OT_properties (struct wmOperatorType * ot)
Definition at line 101 of file clip_toolbar.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, properties_exec(), and properties_poll().
Referenced by clip_operatortypes().
void CLIP_OT_rebuild_proxy (struct wmOperatorType * ot)
Definition at line 1021 of file clip_ops.c.
References clip_rebuild_proxy_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and wmOperatorType::poll.
Referenced by clip_operatortypes().
void CLIP_OT_reload (struct wmOperatorType * ot)
Definition at line 257 of file clip_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and reload_exec().
Referenced by clip_operatortypes().
void CLIP_OT_select (struct wmOperatorType * ot)
Definition at line 850 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_vector(), select_exec(), select_invoke(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_select_all (struct wmOperatorType * ot)
Definition at line 1103 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, select_all_exec(), and WM_operator_properties_select_all().
Referenced by clip_operatortypes().
void CLIP_OT_select_border (struct wmOperatorType * ot)
Definition at line 926 of file tracking_ops.c.
References border_select_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, TRUE, WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by clip_operatortypes().
void CLIP_OT_select_circle (struct wmOperatorType * ot)
Definition at line 1010 of file tracking_ops.c.
References circle_select_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, WM_gesture_circle_invoke(), and WM_gesture_circle_modal().
Referenced by clip_operatortypes().
void CLIP_OT_select_grouped (struct wmOperatorType * ot)
Definition at line 1183 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), select_groped_exec(), space_clip_frame_poll(), wmOperatorType::srna, and TRACK_CLEAR_REMAINED.
Referenced by clip_operatortypes().
void CLIP_OT_set_axis (struct wmOperatorType * ot)
Definition at line 2487 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), set_axis_exec(), set_orientation_poll(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_set_center_principal (struct wmOperatorType * ot)
Definition at line 2698 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and set_center_principal_exec().
Referenced by clip_operatortypes().
void CLIP_OT_set_origin (struct wmOperatorType * ot)
Definition at line 2172 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), set_orientation_poll(), set_origin_exec(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_set_plane (struct wmOperatorType * ot)
Definition at line 2415 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), set_orientation_poll(), set_plane_exec(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_set_scale (struct wmOperatorType * ot)
Definition at line 2605 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), set_orientation_poll(), set_scale_exec(), set_scale_invoke(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_set_solution_scale (struct wmOperatorType * ot)
Definition at line 2657 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), set_solution_scale_exec(), set_solution_scale_invoke(), set_solution_scale_poll(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_slide_marker (struct wmOperatorType * ot)
Definition at line 638 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_vector(), slide_marker_invoke(), slide_marker_modal(), space_clip_frame_poll(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_solve_camera (struct wmOperatorType * ot)
Definition at line 1792 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, solve_camera_exec(), solve_camera_invoke(), and solve_camera_modal().
Referenced by clip_operatortypes().
void CLIP_OT_stabilize_2d_add (struct wmOperatorType * ot)
Definition at line 3174 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and stabilize_2d_add_exec().
Referenced by clip_operatortypes().
void CLIP_OT_stabilize_2d_remove (struct wmOperatorType * ot)
Definition at line 3234 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and stabilize_2d_remove_exec().
Referenced by clip_operatortypes().
void CLIP_OT_stabilize_2d_select (struct wmOperatorType * ot)
Definition at line 3277 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and stabilize_2d_select_exec().
Referenced by clip_operatortypes().
void CLIP_OT_stabilize_2d_set_rotation (struct wmOperatorType * ot)
Definition at line 3314 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and stabilize_2d_set_rotation_exec().
Referenced by clip_operatortypes().
void CLIP_OT_tools (struct wmOperatorType * ot)
Definition at line 176 of file clip_toolbar.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, tools_exec(), and tools_poll().
Referenced by clip_operatortypes().
void CLIP_OT_track_copy_color (struct wmOperatorType * ot)
Definition at line 3125 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and track_copy_color_exec().
Referenced by clip_operatortypes().
void CLIP_OT_track_markers (struct wmOperatorType * ot)
Definition at line 1570 of file tracking_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), space_clip_frame_poll(), wmOperatorType::srna, track_markers_exec(), track_markers_invoke(), and track_markers_modal().
Referenced by clip_operatortypes().
void CLIP_OT_tracking_object_new (struct wmOperatorType * ot)
Definition at line 3542 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and tracking_object_new_exec().
Referenced by clip_operatortypes().
void CLIP_OT_tracking_object_remove (struct wmOperatorType * ot)
Definition at line 3580 of file tracking_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and tracking_object_remove_exec().
Referenced by clip_operatortypes().
void CLIP_OT_view_all (struct wmOperatorType * ot)
Definition at line 713 of file clip_ops.c.
References ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, and view_all_exec().
Referenced by clip_operatortypes().
void CLIP_OT_view_pan (struct wmOperatorType * ot)
Definition at line 399 of file clip_ops.c.
References wmOperatorType::cancel, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OPTYPE_BLOCKING, wmOperatorType::poll, RNA_def_float_vector(), wmOperatorType::srna, view_pan_cancel(), view_pan_exec(), view_pan_invoke(), and view_pan_modal().
Referenced by clip_operatortypes().
void CLIP_OT_view_selected (struct wmOperatorType * ot)
Definition at line 743 of file clip_ops.c.
References ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and view_selected_exec().
Referenced by clip_operatortypes().
void CLIP_OT_view_zoom (wmOperatorType * ot)
Definition at line 525 of file clip_ops.c.
References wmOperatorType::cancel, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, wmOperatorType::poll, RNA_def_float(), wmOperatorType::srna, view_zoom_cancel(), view_zoom_exec(), view_zoom_invoke(), and view_zoom_modal().
Referenced by clip_operatortypes().
void CLIP_OT_view_zoom_in (struct wmOperatorType * ot)
Definition at line 573 of file clip_ops.c.
References ED_space_clip_poll(), wmOperatorType::exec, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, wmOperatorType::poll, RNA_def_float_vector(), wmOperatorType::srna, view_zoom_in_exec(), and view_zoom_in_invoke().
Referenced by clip_operatortypes().
void CLIP_OT_view_zoom_out (struct wmOperatorType * ot)
Definition at line 613 of file clip_ops.c.
References ED_space_clip_poll(), wmOperatorType::exec, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, wmOperatorType::poll, RNA_def_float_vector(), wmOperatorType::srna, view_zoom_out_exec(), and view_zoom_out_invoke().
Referenced by clip_operatortypes().
void CLIP_OT_view_zoom_ratio (struct wmOperatorType * ot)
Definition at line 646 of file clip_ops.c.
References ED_space_clip_poll(), wmOperatorType::exec, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_float(), wmOperatorType::srna, and view_zoom_ratio_exec().
Referenced by clip_operatortypes().
void clip_view_center_to_point (struct SpaceClip * sc, float x, float y)
Definition at line 212 of file clip_utils.c.
References ED_space_clip_aspect(), ED_space_clip_size(), SpaceClip::xof, and SpaceClip::yof.
Referenced by ED_clip_view_selection(), and mouse_select_curve().
void ED_clip_buttons_register (struct ARegionType * art)
Definition at line 66 of file clip_buttons.c.
References BLI_addtail(), PanelType::draw, PanelType::flag, gpencil_panel_standard(), PanelType::idname, PanelType::label, MEM_callocN(), ARegionType::paneltypes, and PNL_DEFAULT_CLOSED.
Referenced by ED_spacetype_clip().
void ED_clip_graph_center_current_frame (struct Scene * scene, struct ARegion * ar)
Definition at line 609 of file clip_graph_ops.c.
References CFRA, View2D::cur, ARegion::v2d, rctf::xmax, and rctf::xmin.
Referenced by center_current_frame_exec(), and clip_preview_area_draw().
void ED_clip_tool_props_register (struct ARegionType * art)
Definition at line 241 of file clip_toolbar.c.
References BLI_addtail(), clip_panel_operator_redo(), clip_panel_operator_redo_header(), PanelType::draw, PanelType::draw_header, PanelType::idname, PanelType::label, MEM_callocN(), and ARegionType::paneltypes.
Referenced by ED_spacetype_clip().