Blender: seqeffects.c File Reference
seqeffects.c File Reference
blenkernel
#include <string.h>
#include <math.h>
#include <stdlib.h>
#include "MEM_guardedalloc.h"
#include "BLI_dynlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BLI_string.h"
#include "DNA_scene_types.h"
#include "DNA_sequence_types.h"
#include "DNA_anim_types.h"
#include "BKE_fcurve.h"
#include "BKE_main.h"
#include "BKE_plugin_types.h"
#include "BKE_sequencer.h"
#include "BKE_texture.h"
#include "BKE_utildefines.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "RNA_access.h"
Classes
struct WipeZone
Defines
#define INT 96
#define FLO 128
#define RE_GAMMA_TABLE_SIZE 400
#define XOFF 8
#define YOFF 8
Typedefs
typedef struct WipeZone WipeZone
Enumerations
enum { GlowR = 0, GlowG = 1, GlowB = 2, GlowA = 3 }
Functions
static void error (const char *UNUSED(error),...)
static struct ImBuf * prepare_effect_imbufs (SeqRenderData context, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
static void open_plugin_seq (PluginSeq *pis, const char *seqname)
static PluginSeq * add_plugin_seq (const char *str, const char *seqname)
static void free_plugin_seq (PluginSeq *pis)
static void init_plugin (Sequence *seq, const char *fname)
static int num_inputs_plugin (void)
static void load_plugin (Sequence *seq)
static void copy_plugin (Sequence *dst, Sequence *src)
static ImBuf * IMB_cast_away_list (ImBuf *i)
static struct ImBuf * do_plugin_effect (SeqRenderData context, Sequence *seq, float cfra, float facf0, float facf1, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
static int do_plugin_early_out (struct Sequence *UNUSED(seq), float UNUSED(facf0), float UNUSED(facf1))
static void free_plugin (struct Sequence *seq)
static void init_alpha_over_or_under (Sequence *seq)
static void do_alphaover_effect_byte (float facf0, float facf1, int x, int y, char *rect1, char *rect2, char *out)
static void do_alphaover_effect_float (float facf0, float facf1, int x, int y, float *rect1, float *rect2, float *out)
static struct ImBuf * do_alphaover_effect (SeqRenderData context, Sequence *UNUSED(seq), float UNUSED(cfra), float facf0, float facf1, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
static void do_alphaunder_effect_byte (float facf0, float facf1, int x, int y, char *rect1, char *rect2, char *out)
static void do_alphaunder_effect_float (float facf0, float facf1, int x, int y, float *rect1, float *rect2, float *out)
static struct ImBuf * do_alphaunder_effect (SeqRenderData context, Sequence *UNUSED(seq), float UNUSED(cfra), float facf0, float facf1, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
static void do_cross_effect_byte (float facf0, float facf1, int x, int y, char *rect1, char *rect2, char *out)
static void do_cross_effect_float (float facf0, float facf1, int x, int y, float *rect1, float *rect2, float *out)
static struct ImBuf * do_cross_effect (SeqRenderData context, Sequence *UNUSED(seq), float UNUSED(cfra), float facf0, float facf1, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
static void makeGammaTables (float gamma)
static float gammaCorrect (float c)
static float invGammaCorrect (float col)
static void gamtabs (float gamma)
static void build_gammatabs (void)
static void init_gammacross (Sequence *UNUSED(seq))
static void load_gammacross (Sequence *UNUSED(seq))
static void free_gammacross (Sequence *UNUSED(seq))
static void do_gammacross_effect_byte (float facf0, float UNUSED(facf1), int x, int y, unsigned char *rect1, unsigned char *rect2, unsigned char *out)
static void do_gammacross_effect_float (float facf0, float UNUSED(facf1), int x, int y, float *rect1, float *rect2, float *out)
static struct ImBuf * do_gammacross_effect (SeqRenderData context, Sequence *UNUSED(seq), float UNUSED(cfra), float facf0, float facf1, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
static void do_add_effect_byte (float facf0, float facf1, int x, int y, unsigned char *rect1, unsigned char *rect2, unsigned char *out)
static void do_add_effect_float (float facf0, float facf1, int x, int y, float *rect1, float *rect2, float *out)
static struct ImBuf * do_add_effect (SeqRenderData context, Sequence *UNUSED(seq), float UNUSED(cfra), float facf0, float facf1, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
static void do_sub_effect_byte (float facf0, float facf1, int x, int y, char *rect1, char *rect2, char *out)
static void do_sub_effect_float (float facf0, float facf1, int x, int y, float *rect1, float *rect2, float *out)
static struct ImBuf * do_sub_effect (SeqRenderData context, Sequence *UNUSED(seq), float UNUSED(cfra), float facf0, float facf1, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
static void do_drop_effect_byte (float facf0, float facf1, int x, int y, char *rect2i, char *rect1i, char *outi)
static void do_drop_effect_float (float facf0, float facf1, int x, int y, float *rect2i, float *rect1i, float *outi)
static void do_mul_effect_byte (float facf0, float facf1, int x, int y, unsigned char *rect1, unsigned char *rect2, unsigned char *out)
static void do_mul_effect_float (float facf0, float facf1, int x, int y, float *rect1, float *rect2, float *out)
static struct ImBuf * do_mul_effect (SeqRenderData context, Sequence *UNUSED(seq), float UNUSED(cfra), float facf0, float facf1, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
static void precalc_wipe_zone (WipeZone *wipezone, WipeVars *wipe, int xo, int yo)
static float in_band (float width, float dist, int side, int dir)
static float check_zone (WipeZone *wipezone, int x, int y, Sequence *seq, float facf0)
static void init_wipe_effect (Sequence *seq)
static int num_inputs_wipe (void)
static void free_wipe_effect (Sequence *seq)
static void copy_wipe_effect (Sequence *dst, Sequence *src)
static void do_wipe_effect_byte (Sequence *seq, float facf0, float UNUSED(facf1), int x, int y, unsigned char *rect1, unsigned char *rect2, unsigned char *out)
static void do_wipe_effect_float (Sequence *seq, float facf0, float UNUSED(facf1), int x, int y, float *rect1, float *rect2, float *out)
static struct ImBuf * do_wipe_effect (SeqRenderData context, Sequence *seq, float UNUSED(cfra), float facf0, float facf1, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
static void init_transform_effect (Sequence *seq)
static int num_inputs_transform (void)
static void free_transform_effect (Sequence *seq)
static void copy_transform_effect (Sequence *dst, Sequence *src)
static void transform_image (int x, int y, struct ImBuf *ibuf1, struct ImBuf *out, float scale_x, float scale_y, float translate_x, float translate_y, float rotate, int interpolation)
static void do_transform (Scene *scene, Sequence *seq, float UNUSED(facf0), int x, int y, struct ImBuf *ibuf1, struct ImBuf *out)
static struct ImBuf * do_transform_effect (SeqRenderData context, Sequence *seq, float UNUSED(cfra), float facf0, float UNUSED(facf1), struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
static void RVBlurBitmap2_byte (unsigned char *map, int width, int height, float blur, int quality)
static void RVBlurBitmap2_float (float *map, int width, int height, float blur, int quality)
static void RVAddBitmaps_byte (unsigned char *a, unsigned char *b, unsigned char *c, int width, int height)
static void RVAddBitmaps_float (float *a, float *b, float *c, int width, int height)
static void RVIsolateHighlights_byte (unsigned char *in, unsigned char *out, int width, int height, int threshold, float boost, float clamp)
static void RVIsolateHighlights_float (float *in, float *out, int width, int height, float threshold, float boost, float clamp)
static void init_glow_effect (Sequence *seq)
static int num_inputs_glow (void)
static void free_glow_effect (Sequence *seq)
static void copy_glow_effect (Sequence *dst, Sequence *src)
static void do_glow_effect_byte (Sequence *seq, int render_size, float facf0, float UNUSED(facf1), int x, int y, char *rect1, char *UNUSED(rect2), char *out)
static void do_glow_effect_float (Sequence *seq, int render_size, float facf0, float UNUSED(facf1), int x, int y, float *rect1, float *UNUSED(rect2), float *out)
static struct ImBuf * do_glow_effect (SeqRenderData context, Sequence *seq, float UNUSED(cfra), float facf0, float facf1, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
static void init_solid_color (Sequence *seq)
static int num_inputs_color (void)
static void free_solid_color (Sequence *seq)
static void copy_solid_color (Sequence *dst, Sequence *src)
static int early_out_color (struct Sequence *UNUSED(seq), float UNUSED(facf0), float UNUSED(facf1))
static struct ImBuf * do_solid_color (SeqRenderData context, Sequence *seq, float UNUSED(cfra), float facf0, float facf1, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
static int num_inputs_multicam (void)
static int early_out_multicam (struct Sequence *UNUSED(seq), float UNUSED(facf0), float UNUSED(facf1))
static struct ImBuf * do_multicam (SeqRenderData context, Sequence *seq, float cfra, float UNUSED(facf0), float UNUSED(facf1), struct ImBuf *UNUSED(ibuf1), struct ImBuf *UNUSED(ibuf2), struct ImBuf *UNUSED(ibuf3))
static int num_inputs_adjustment (void)
static int early_out_adjustment (struct Sequence *UNUSED(seq), float UNUSED(facf0), float UNUSED(facf1))
static struct ImBuf * do_adjustment_impl (SeqRenderData context, Sequence *seq, float cfra)
static struct ImBuf * do_adjustment (SeqRenderData context, Sequence *seq, float cfra, float UNUSED(facf0), float UNUSED(facf1), struct ImBuf *UNUSED(ibuf1), struct ImBuf *UNUSED(ibuf2), struct ImBuf *UNUSED(ibuf3))
static void init_speed_effect (Sequence *seq)
static void load_speed_effect (Sequence *seq)
static int num_inputs_speed (void)
static void free_speed_effect (Sequence *seq)
static void copy_speed_effect (Sequence *dst, Sequence *src)
static int early_out_speed (struct Sequence *UNUSED(seq), float UNUSED(facf0), float UNUSED(facf1))
static void store_icu_yrange_speed (struct Sequence *seq, short UNUSED(adrcode), float *ymin, float *ymax)
void sequence_effect_speed_rebuild_map (Scene *scene, Sequence *seq, int force)
static void init_noop (struct Sequence *UNUSED(seq))
static void load_noop (struct Sequence *UNUSED(seq))
static void init_plugin_noop (struct Sequence *UNUSED(seq), const char *UNUSED(fname))
static void free_noop (struct Sequence *UNUSED(seq))
static int num_inputs_default (void)
static int early_out_noop (struct Sequence *UNUSED(seq), float UNUSED(facf0), float UNUSED(facf1))
static int early_out_fade (struct Sequence *UNUSED(seq), float facf0, float facf1)
static int early_out_mul_input2 (struct Sequence *UNUSED(seq), float facf0, float facf1)
static void store_icu_yrange_noop (struct Sequence *UNUSED(seq), short UNUSED(adrcode), float *UNUSED(ymin), float *UNUSED(ymax))
static void get_default_fac_noop (struct Sequence *UNUSED(seq), float UNUSED(cfra), float *facf0, float *facf1)
static void get_default_fac_fade (struct Sequence *seq, float cfra, float *facf0, float *facf1)
static struct ImBuf * do_overdrop_effect (SeqRenderData context, Sequence *UNUSED(seq), float UNUSED(cfra), float facf0, float facf1, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
static struct SeqEffectHandle get_sequence_effect_impl (int seq_type)
struct SeqEffectHandle get_sequence_effect (Sequence *seq)
struct SeqEffectHandle get_sequence_blend (Sequence *seq)
int get_sequence_effect_num_inputs (int seq_type)
Variables
static unsigned short gamtab [65536]
static unsigned short igamtab1 [256]
static int gamma_tabs_init = FALSE
static float gamma_range_table [RE_GAMMA_TABLE_SIZE+1]
static float gamfactor_table [RE_GAMMA_TABLE_SIZE]
static float inv_gamma_range_table [RE_GAMMA_TABLE_SIZE+1]
static float inv_gamfactor_table [RE_GAMMA_TABLE_SIZE]
static float color_domain_table [RE_GAMMA_TABLE_SIZE+1]
static float color_step
static float inv_color_step
static float valid_gamma
static float valid_inv_gamma
Detailed Description
Definition in file seqeffects.c.
Define Documentation
#define FLO 128
Definition at line 64 of file seqeffects.c.
Referenced by add_plugin_seq(), ui_block_func_ICONROW(), ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), ui_get_but_val(), ui_get_but_vectorf(), ui_is_but_float(), ui_set_but_val(), ui_set_but_vectorf(), uiDefButBitF(), uiDefButF(), uiDefIconButBitF(), uiDefIconButF(), uiDefIconTextButBitF(), and uiDefIconTextButF().
#define INT 96
Definition at line 63 of file seqeffects.c.
Referenced by add_plugin_seq(), OSLRenderServices::get_pointcloud_attr_query(), getTime(), ui_apply_but_TOG(), ui_get_but_val(), ui_set_but_val(), uiDefButBitI(), uiDefButI(), uiDefIconButBitI(), uiDefIconButI(), uiDefIconTextButBitI(), uiDefIconTextButI(), and widget_draw_text_icon().
#define RE_GAMMA_TABLE_SIZE 400
Definition at line 883 of file seqeffects.c.
Referenced by gammaCorrect(), invGammaCorrect(), and makeGammaTables().
#define XOFF 8
Definition at line 1382 of file seqeffects.c.
Referenced by do_drop_effect_byte(), and do_drop_effect_float().
#define YOFF 8
Definition at line 1383 of file seqeffects.c.
Referenced by do_drop_effect_byte(), and do_drop_effect_float().
Typedef Documentation
typedef struct WipeZone WipeZone
Enumeration Type Documentation
anonymous enum
Enumerator:
GlowR
GlowG
GlowB
GlowA
Definition at line 69 of file seqeffects.c.
Function Documentation
static PluginSeq* add_plugin_seq (const char * str, const char * seqname) [static]
Definition at line 200 of file seqeffects.c.
References BLI_strncpy(), PluginSeq::data, VarStruct::def, PluginSeq::doit, error(), FILE_MAX, FLO, PluginSeq::handle, INT, MEM_callocN(), MEM_freeN(), PluginSeq::name, NULL, open_plugin_seq(), VarStruct::type, PluginSeq::vars, and PluginSeq::varstr.
Referenced by init_plugin().
static void build_gammatabs (void) [static]
Definition at line 997 of file seqeffects.c.
References FALSE, gamtabs(), makeGammaTables(), and TRUE.
Referenced by do_gammacross_effect().
static float check_zone (WipeZone * wipezone, int x, int y, Sequence * seq, float facf0) [static]
Definition at line 1636 of file seqeffects.c.
References abs(), WipeZone::angle, angle(), KDL::asin(), DO_BOX_WIPE, DO_CLOCK_WIPE, DO_DOUBLE_WIPE, DO_IRIS_WIPE, DO_SINGLE_WIPE, WipeVars::edgeWidth, Sequence::effectdata, fabs(), fabsf, WipeZone::flip, WipeVars::forward, if(), in_band(), invert(), M_PI, minf(), WipeZone::pythangle, sqrt(), WipeZone::width, WipeVars::wipetype, WipeZone::xo, and WipeZone::yo.
Referenced by do_wipe_effect_byte(), and do_wipe_effect_float().
static void copy_glow_effect (Sequence * dst, Sequence * src) [static]
Definition at line 2647 of file seqeffects.c.
References Sequence::effectdata, and MEM_dupallocN().
Referenced by get_sequence_effect_impl().
static void copy_plugin (Sequence * dst, Sequence * src) [static]
Definition at line 269 of file seqeffects.c.
References MEM_dupallocN(), Sequence::name, open_plugin_seq(), and Sequence::plugin.
Referenced by get_sequence_effect_impl().
static void copy_solid_color (Sequence * dst, Sequence * src) [static]
Definition at line 2735 of file seqeffects.c.
References Sequence::effectdata, and MEM_dupallocN().
Referenced by get_sequence_effect_impl().
static void copy_speed_effect (Sequence * dst, Sequence * src) [static]
Definition at line 3001 of file seqeffects.c.
References Sequence::effectdata, SpeedControlVars::frameMap, SpeedControlVars::length, MEM_dupallocN(), and NULL.
Referenced by get_sequence_effect_impl().
static void copy_transform_effect (Sequence * dst, Sequence * src) [static]
Definition at line 2075 of file seqeffects.c.
References Sequence::effectdata, and MEM_dupallocN().
Referenced by get_sequence_effect_impl().
static void copy_wipe_effect (Sequence * dst, Sequence * src) [static]
Definition at line 1889 of file seqeffects.c.
References Sequence::effectdata, and MEM_dupallocN().
Referenced by get_sequence_effect_impl().
static struct ImBuf* do_add_effect (SeqRenderData context, Sequence * UNUSEDseq, float UNUSEDcfra, float facf0, float facf1, struct ImBuf * ibuf1, struct ImBuf * ibuf2, struct ImBuf * ibuf3) [static, read]
Definition at line 1237 of file seqeffects.c.
References do_add_effect_byte(), do_add_effect_float(), prepare_effect_imbufs(), ImBuf::rect, ImBuf::rect_float, SeqRenderData::rectx, and SeqRenderData::recty.
Referenced by get_sequence_effect_impl().
static void do_add_effect_byte (float facf0, float facf1, int x, int y, unsigned char * rect1, unsigned char * rect2, unsigned char * out) [static]
Definition at line 1148 of file seqeffects.c.
References ImBuf::x.
Referenced by do_add_effect().
static void do_add_effect_float (float facf0, float facf1, int x, int y, float * rect1, float * rect2, float * out) [static]
Definition at line 1200 of file seqeffects.c.
References ImBuf::x.
Referenced by do_add_effect().
static struct ImBuf* do_adjustment (SeqRenderData context, Sequence * seq, float cfra, float UNUSEDfacf0, float UNUSEDfacf1, struct ImBuf * UNUSEDibuf1, struct ImBuf * UNUSEDibuf2, struct ImBuf * UNUSEDibuf3) [static, read]
Definition at line 2933 of file seqeffects.c.
References do_adjustment_impl(), Scene::ed, i, IMB_dupImBuf(), IMB_freeImBuf(), input_have_to_preprocess(), NULL, and SeqRenderData::scene.
Referenced by get_sequence_effect_impl().
static struct ImBuf* do_adjustment_impl (SeqRenderData context, Sequence * seq, float cfra) [static, read]
Definition at line 2899 of file seqeffects.c.
References Scene::ed, give_ibuf_seqbase(), i, Sequence::machine, NULL, SeqRenderData::scene, seq_metastrip(), seq_seqbase(), and Editing::seqbase.
Referenced by do_adjustment().
static struct ImBuf* do_alphaover_effect (SeqRenderData context, Sequence * UNUSEDseq, float UNUSEDcfra, float facf0, float facf1, struct ImBuf * ibuf1, struct ImBuf * ibuf2, struct ImBuf * ibuf3) [static, read]
Definition at line 545 of file seqeffects.c.
References do_alphaover_effect_byte(), do_alphaover_effect_float(), prepare_effect_imbufs(), ImBuf::rect, ImBuf::rect_float, SeqRenderData::rectx, and SeqRenderData::recty.
Referenced by get_sequence_effect_impl().
static void do_alphaover_effect_byte (float facf0, float facf1, int x, int y, char * rect1, char * rect2, char * out) [static]
Definition at line 413 of file seqeffects.c.
References ImBuf::x.
Referenced by do_alphaover_effect(), and do_overdrop_effect().
static void do_alphaover_effect_float (float facf0, float facf1, int x, int y, float * rect1, float * rect2, float * out) [static]
Definition at line 479 of file seqeffects.c.
References ImBuf::x.
Referenced by do_alphaover_effect(), and do_overdrop_effect().
static struct ImBuf* do_alphaunder_effect (SeqRenderData context, Sequence * UNUSEDseq, float UNUSEDcfra, float facf0, float facf1, struct ImBuf * ibuf1, struct ImBuf * ibuf2, struct ImBuf * ibuf3) [static, read]
Definition at line 723 of file seqeffects.c.
References do_alphaunder_effect_byte(), do_alphaunder_effect_float(), prepare_effect_imbufs(), ImBuf::rect, ImBuf::rect_float, SeqRenderData::rectx, and SeqRenderData::recty.
Referenced by get_sequence_effect_impl().
static void do_alphaunder_effect_byte (float facf0, float facf1, int x, int y, char * rect1, char * rect2, char * out) [static]
Definition at line 573 of file seqeffects.c.
References ImBuf::x.
Referenced by do_alphaunder_effect().
static void do_alphaunder_effect_float (float facf0, float facf1, int x, int y, float * rect1, float * rect2, float * out) [static]
Definition at line 642 of file seqeffects.c.
References ImBuf::x.
Referenced by do_alphaunder_effect().
static struct ImBuf* do_cross_effect (SeqRenderData context, Sequence * UNUSEDseq, float UNUSEDcfra, float facf0, float facf1, struct ImBuf * ibuf1, struct ImBuf * ibuf2, struct ImBuf * ibuf3) [static, read]
Definition at line 849 of file seqeffects.c.
References do_cross_effect_byte(), do_cross_effect_float(), prepare_effect_imbufs(), ImBuf::rect, ImBuf::rect_float, SeqRenderData::rectx, and SeqRenderData::recty.
Referenced by get_sequence_effect_impl().
static void do_cross_effect_byte (float facf0, float facf1, int x, int y, char * rect1, char * rect2, char * out) [static]
Definition at line 752 of file seqeffects.c.
References ImBuf::x.
Referenced by do_cross_effect().
static void do_cross_effect_float (float facf0, float facf1, int x, int y, float * rect1, float * rect2, float * out) [static]
Definition at line 800 of file seqeffects.c.
References ImBuf::x.
Referenced by do_cross_effect().
static void do_drop_effect_byte (float facf0, float facf1, int x, int y, char * rect2i, char * rect1i, char * outi) [static]
Definition at line 1385 of file seqeffects.c.
References MAX2, ImBuf::x, XOFF, ImBuf::y, and YOFF.
Referenced by do_overdrop_effect().
static void do_drop_effect_float (float facf0, float facf1, int x, int y, float * rect2i, float * rect1i, float * outi) [static]
Definition at line 1425 of file seqeffects.c.
References MAX2, ImBuf::x, XOFF, ImBuf::y, and YOFF.
Referenced by do_overdrop_effect().
static struct ImBuf* do_gammacross_effect (SeqRenderData context, Sequence * UNUSEDseq, float UNUSEDcfra, float facf0, float facf1, struct ImBuf * ibuf1, struct ImBuf * ibuf2, struct ImBuf * ibuf3) [static, read]
Definition at line 1117 of file seqeffects.c.
References build_gammatabs(), do_gammacross_effect_byte(), do_gammacross_effect_float(), prepare_effect_imbufs(), ImBuf::rect, ImBuf::rect_float, SeqRenderData::rectx, and SeqRenderData::recty.
Referenced by get_sequence_effect_impl().
static void do_gammacross_effect_byte (float facf0, float UNUSEDfacf1, int x, int y, unsigned char * rect1, unsigned char * rect2, unsigned char * out) [static]
Definition at line 1018 of file seqeffects.c.
References MOST_SIG_BYTE, and ImBuf::x.
Referenced by do_gammacross_effect().
static void do_gammacross_effect_float (float facf0, float UNUSEDfacf1, int x, int y, float * rect1, float * rect2, float * out) [static]
Definition at line 1074 of file seqeffects.c.
References gammaCorrect(), invGammaCorrect(), and ImBuf::x.
Referenced by do_gammacross_effect().
static struct ImBuf* do_glow_effect (SeqRenderData context, Sequence * seq, float UNUSEDcfra, float facf0, float facf1, struct ImBuf * ibuf1, struct ImBuf * ibuf2, struct ImBuf * ibuf3) [static, read]
Definition at line 2681 of file seqeffects.c.
References do_glow_effect_byte(), do_glow_effect_float(), prepare_effect_imbufs(), Scene::r, ImBuf::rect, ImBuf::rect_float, SeqRenderData::rectx, SeqRenderData::recty, SeqRenderData::scene, and RenderData::xsch.
Referenced by get_sequence_effect_impl().
static void do_glow_effect_byte (Sequence * seq, int render_size, float facf0, float UNUSEDfacf1, int x, int y, char * rect1, char * UNUSEDrect2, char * out) [static]
Definition at line 2653 of file seqeffects.c.
References GlowVars::bNoComp, GlowVars::dDist, GlowVars::dQuality, Sequence::effectdata, GlowVars::fBoost, GlowVars::fClamp, GlowVars::fMini, RVAddBitmaps_byte(), RVBlurBitmap2_byte(), and RVIsolateHighlights_byte().
Referenced by do_glow_effect().
static void do_glow_effect_float (Sequence * seq, int render_size, float facf0, float UNUSEDfacf1, int x, int y, float * rect1, float * UNUSEDrect2, float * out) [static]
Definition at line 2667 of file seqeffects.c.
References GlowVars::bNoComp, GlowVars::dDist, GlowVars::dQuality, Sequence::effectdata, GlowVars::fBoost, GlowVars::fClamp, GlowVars::fMini, RVAddBitmaps_float(), RVBlurBitmap2_float(), and RVIsolateHighlights_float().
Referenced by do_glow_effect().
static struct ImBuf* do_mul_effect (SeqRenderData context, Sequence * UNUSEDseq, float UNUSEDcfra, float facf0, float facf1, struct ImBuf * ibuf1, struct ImBuf * ibuf2, struct ImBuf * ibuf3) [static, read]
Definition at line 1568 of file seqeffects.c.
References do_mul_effect_byte(), do_mul_effect_float(), prepare_effect_imbufs(), ImBuf::rect, ImBuf::rect_float, SeqRenderData::rectx, and SeqRenderData::recty.
Referenced by get_sequence_effect_impl().
static void do_mul_effect_byte (float facf0, float facf1, int x, int y, unsigned char * rect1, unsigned char * rect2, unsigned char * out) [static]
Definition at line 1470 of file seqeffects.c.
References ImBuf::x.
Referenced by do_mul_effect().
static void do_mul_effect_float (float facf0, float facf1, int x, int y, float * rect1, float * rect2, float * out) [static]
Definition at line 1519 of file seqeffects.c.
References ImBuf::x.
Referenced by do_mul_effect().
static struct ImBuf* do_multicam (SeqRenderData context, Sequence * seq, float cfra, float UNUSEDfacf0, float UNUSEDfacf1, struct ImBuf * UNUSEDibuf1, struct ImBuf * UNUSEDibuf2, struct ImBuf * UNUSEDibuf3) [static, read]
Definition at line 2844 of file seqeffects.c.
References Scene::ed, give_ibuf_seqbase(), i, IMB_dupImBuf(), IMB_freeImBuf(), input_have_to_preprocess(), Sequence::machine, Sequence::multicam_source, NULL, SeqRenderData::scene, seq_seqbase(), and Editing::seqbase.
Referenced by get_sequence_effect_impl().
static struct ImBuf* do_overdrop_effect (SeqRenderData context, Sequence * UNUSEDseq, float UNUSEDcfra, float facf0, float facf1, struct ImBuf * ibuf1, struct ImBuf * ibuf2, struct ImBuf * ibuf3) [static, read]
Definition at line 3229 of file seqeffects.c.
References do_alphaover_effect_byte(), do_alphaover_effect_float(), do_drop_effect_byte(), do_drop_effect_float(), prepare_effect_imbufs(), ImBuf::rect, ImBuf::rect_float, SeqRenderData::rectx, and SeqRenderData::recty.
Referenced by get_sequence_effect_impl().
static int do_plugin_early_out (struct Sequence * UNUSEDseq, float UNUSEDfacf0, float UNUSEDfacf1) [static]
Definition at line 388 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static struct ImBuf* do_plugin_effect (SeqRenderData context, Sequence * seq, float cfra, float facf0, float facf1, struct ImBuf * ibuf1, struct ImBuf * ibuf2, struct ImBuf * ibuf3) [static, read]
Definition at line 285 of file seqeffects.c.
References BLI_dynlib_find_symbol(), PluginSeq::cfra, PluginSeq::current_private_data, PluginSeq::data, PluginSeq::doit, ImBuf::flags, PluginSeq::handle, IB_rectfloat, imb_addrectImBuf(), IMB_cast_away_list(), IMB_convert_rgba_to_abgr(), IMB_dupImBuf(), IMB_float_from_rect_simple(), IMB_freeImBuf(), imb_freerectfloatImBuf(), IMB_rect_from_float(), PluginSeq::instance_private_data, Sequence::name, NULL, Sequence::plugin, prepare_effect_imbufs(), ImBuf::rect, ImBuf::rect_float, SeqRenderData::rectx, SeqRenderData::recty, PluginSeq::version, ImBuf::x, and ImBuf::y.
Referenced by get_sequence_effect_impl().
static struct ImBuf* do_solid_color (SeqRenderData context, Sequence * seq, float UNUSEDcfra, float facf0, float facf1, struct ImBuf * ibuf1, struct ImBuf * ibuf2, struct ImBuf * ibuf3) [static, read]
Definition at line 2746 of file seqeffects.c.
References SolidColorVars::col, Sequence::effectdata, if(), prepare_effect_imbufs(), ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by get_sequence_effect_impl().
static struct ImBuf* do_sub_effect (SeqRenderData context, Sequence * UNUSEDseq, float UNUSEDcfra, float facf0, float facf1, struct ImBuf * ibuf1, struct ImBuf * ibuf2, struct ImBuf * ibuf3) [static, read]
Definition at line 1354 of file seqeffects.c.
References do_sub_effect_byte(), do_sub_effect_float(), prepare_effect_imbufs(), ImBuf::rect, ImBuf::rect_float, SeqRenderData::rectx, and SeqRenderData::recty.
Referenced by get_sequence_effect_impl().
static void do_sub_effect_byte (float facf0, float facf1, int x, int y, char * rect1, char * rect2, char * out) [static]
Definition at line 1265 of file seqeffects.c.
References ImBuf::x.
Referenced by do_sub_effect().
static void do_sub_effect_float (float facf0, float facf1, int x, int y, float * rect1, float * rect2, float * out) [static]
Definition at line 1317 of file seqeffects.c.
References ImBuf::x.
Referenced by do_sub_effect().
static void do_transform (Scene * scene, Sequence * seq, float UNUSEDfacf0, int x, int y, struct ImBuf * ibuf1, struct ImBuf * out) [static]
Definition at line 2130 of file seqeffects.c.
References DEG2RADF, Sequence::effectdata, if(), TransformVars::interpolation, TransformVars::percent, Scene::r, TransformVars::rotIni, TransformVars::ScalexIni, TransformVars::ScaleyIni, RenderData::size, transform(), transform_image(), TransformVars::uniform_scale, TransformVars::xIni, and TransformVars::yIni.
Referenced by do_transform_effect().
static struct ImBuf* do_transform_effect (SeqRenderData context, Sequence * seq, float UNUSEDcfra, float facf0, float UNUSEDfacf1, struct ImBuf * ibuf1, struct ImBuf * ibuf2, struct ImBuf * ibuf3) [static, read]
Definition at line 2164 of file seqeffects.c.
References do_transform(), prepare_effect_imbufs(), SeqRenderData::rectx, SeqRenderData::recty, and SeqRenderData::scene.
Referenced by get_sequence_effect_impl().
static struct ImBuf* do_wipe_effect (SeqRenderData context, Sequence * seq, float UNUSEDcfra, float facf0, float facf1, struct ImBuf * ibuf1, struct ImBuf * ibuf2, struct ImBuf * ibuf3) [static, read]
Definition at line 2016 of file seqeffects.c.
References do_wipe_effect_byte(), do_wipe_effect_float(), prepare_effect_imbufs(), ImBuf::rect, ImBuf::rect_float, SeqRenderData::rectx, and SeqRenderData::recty.
Referenced by get_sequence_effect_impl().
static void do_wipe_effect_byte (Sequence * seq, float facf0, float UNUSEDfacf1, int x, int y, unsigned char * rect1, unsigned char * rect2, unsigned char * out) [static]
Definition at line 1894 of file seqeffects.c.
References check_zone(), Sequence::effectdata, NULL, and precalc_wipe_zone().
Referenced by do_wipe_effect().
static void do_wipe_effect_float (Sequence * seq, float facf0, float UNUSEDfacf1, int x, int y, float * rect1, float * rect2, float * out) [static]
Definition at line 1955 of file seqeffects.c.
References check_zone(), Sequence::effectdata, NULL, and precalc_wipe_zone().
Referenced by do_wipe_effect().
static int early_out_adjustment (struct Sequence * UNUSEDseq, float UNUSEDfacf0, float UNUSEDfacf1) [static]
Definition at line 2894 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static int early_out_color (struct Sequence * UNUSEDseq, float UNUSEDfacf0, float UNUSEDfacf1) [static]
Definition at line 2740 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static int early_out_fade (struct Sequence * UNUSEDseq, float facf0, float facf1) [static]
Definition at line 3187 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static int early_out_mul_input2 (struct Sequence * UNUSEDseq, float facf0, float facf1) [static]
Definition at line 3199 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static int early_out_multicam (struct Sequence * UNUSEDseq, float UNUSEDfacf0, float UNUSEDfacf1) [static]
Definition at line 2839 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static int early_out_noop (struct Sequence * UNUSEDseq, float UNUSEDfacf0, float UNUSEDfacf1) [static]
Definition at line 3181 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static int early_out_speed (struct Sequence * UNUSEDseq, float UNUSEDfacf0, float UNUSEDfacf1) [static]
Definition at line 3010 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static void error (const char * UNUSEDerror, ...) [static]
Definition at line 61 of file seqeffects.c.
Referenced by add_plugin_seq(), add_verts_to_dgroups(), AUD_SRCResampleReader::AUD_SRCResampleReader(), AVI_print_error(), BKE_ptcache_write(), BKE_tracking_solve_reconstruction(), BM_faces_join(), BMO_op_vinitf(), BPy_IDProperty_Map_ValidateAndCreate(), clean_tracks_exec(), clErrorString(), clLibraryInit(), copypose_error(), count_flagged_radial(), dynamicPaint_createUVSurface(), filtcolum(), filtrow(), get_render_aosss_error(), Image_getbuffer(), main(), MEM_freeN(), node_dynamic_update_cb(), occ_lookup(), open_plugin_seq(), plot_line_v2v2i(), pose_proxy_synchronize(), ptcache_basic_header_read(), ptcache_disk_frame_to_mem(), ptcache_file_header_begin_read(), ptcache_mem_frame_to_disk(), ptcache_read_stream(), ptcache_write(), ptcache_write_stream(), AUD_SRCResampleReader::read(), rna_def_function(), RNA_def_property(), RNA_def_struct(), scatter_tree_new(), surfaceGenerateGrid(), transformc(), UI_ThemeGetColorPtr(), and iTaSC::Distance::updateControlOutput().
static void free_gammacross (Sequence * UNUSEDseq) [static]
Definition at line 1014 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static void free_glow_effect (Sequence * seq) [static]
Definition at line 2641 of file seqeffects.c.
References Sequence::effectdata, MEM_freeN(), and NULL.
Referenced by get_sequence_effect_impl().
static void free_noop (struct Sequence * UNUSEDseq) [static]
Definition at line 3171 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static void free_plugin (struct Sequence * seq) [static]
Definition at line 394 of file seqeffects.c.
References free_plugin_seq(), NULL, and Sequence::plugin.
Referenced by get_sequence_effect_impl().
static void free_plugin_seq (PluginSeq * pis) [static]
Definition at line 230 of file seqeffects.c.
References BLI_dynlib_find_symbol(), PluginSeq::handle, PluginSeq::instance_private_data, MEM_freeN(), and NULL.
Referenced by free_plugin().
static void free_solid_color (Sequence * seq) [static]
Definition at line 2729 of file seqeffects.c.
References Sequence::effectdata, MEM_freeN(), and NULL.
Referenced by get_sequence_effect_impl().
static void free_speed_effect (Sequence * seq) [static]
Definition at line 2993 of file seqeffects.c.
References Sequence::effectdata, SpeedControlVars::frameMap, if(), MEM_freeN(), and NULL.
Referenced by get_sequence_effect_impl().
static void free_transform_effect (Sequence * seq) [static]
Definition at line 2069 of file seqeffects.c.
References Sequence::effectdata, MEM_freeN(), and NULL.
Referenced by get_sequence_effect_impl().
static void free_wipe_effect (Sequence * seq) [static]
Definition at line 1883 of file seqeffects.c.
References Sequence::effectdata, MEM_freeN(), and NULL.
Referenced by get_sequence_effect_impl().
static float gammaCorrect (float c) [static]
Definition at line 934 of file seqeffects.c.
References abs(), i, pow(), and RE_GAMMA_TABLE_SIZE.
Referenced by do_gammacross_effect_float().
static void gamtabs (float gamma) [static]
Definition at line 970 of file seqeffects.c.
References pow(), and sqrt().
Referenced by build_gammatabs().
static void get_default_fac_fade (struct Sequence * seq, float cfra, float * facf0, float * facf1) [static]
Definition at line 3220 of file seqeffects.c.
References Sequence::len, and Sequence::startdisp.
Referenced by get_sequence_effect_impl().
static void get_default_fac_noop (struct Sequence * UNUSEDseq, float UNUSEDcfra, float * facf0, float * facf1) [static]
Definition at line 3214 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
struct SeqEffectHandle get_sequence_blend (Sequence * seq) [read]
Definition at line 3401 of file seqeffects.c.
References Sequence::blend_mode, Sequence::flag, get_sequence_effect_impl(), SeqEffectHandle::load, NULL, and SEQ_EFFECT_NOT_LOADED.
Referenced by seq_get_early_out_for_blend_mode(), and seq_render_strip_stack().
struct SeqEffectHandle get_sequence_effect (Sequence * seq) [read]
Definition at line 3386 of file seqeffects.c.
References Sequence::flag, get_sequence_effect_impl(), SeqEffectHandle::load, NULL, SEQ_EFFECT, SEQ_EFFECT_NOT_LOADED, and Sequence::type.
Referenced by change_plugin_seq(), seq_dupli(), seq_free_sequence(), seq_render_effect_strip_impl(), sequence_effect_speed_rebuild_map(), sequencer_add_effect_strip_exec(), sequencer_change_effect_type_exec(), and store_icu_yrange_speed().
static struct SeqEffectHandle get_sequence_effect_impl (int seq_type) [static, read]
Definition at line 3266 of file seqeffects.c.
References SeqEffectHandle::copy, copy_glow_effect(), copy_plugin(), copy_solid_color(), copy_speed_effect(), copy_transform_effect(), copy_wipe_effect(), do_add_effect(), do_adjustment(), do_alphaover_effect(), do_alphaunder_effect(), do_cross_effect(), do_gammacross_effect(), do_glow_effect(), do_mul_effect(), do_multicam(), do_overdrop_effect(), do_plugin_early_out(), do_plugin_effect(), do_solid_color(), do_sub_effect(), do_transform_effect(), do_wipe_effect(), SeqEffectHandle::early_out, early_out_adjustment(), early_out_color(), early_out_fade(), early_out_mul_input2(), early_out_multicam(), early_out_noop(), early_out_speed(), SeqEffectHandle::execute, SeqEffectHandle::free, free_gammacross(), free_glow_effect(), free_noop(), free_plugin(), free_solid_color(), free_speed_effect(), free_transform_effect(), free_wipe_effect(), SeqEffectHandle::get_default_fac, get_default_fac_fade(), get_default_fac_noop(), SeqEffectHandle::init, init_alpha_over_or_under(), init_gammacross(), init_glow_effect(), init_noop(), SeqEffectHandle::init_plugin, init_plugin_noop(), init_solid_color(), init_speed_effect(), init_transform_effect(), init_wipe_effect(), SeqEffectHandle::load, load_gammacross(), load_noop(), load_plugin(), load_speed_effect(), NULL, SeqEffectHandle::num_inputs, num_inputs_adjustment(), num_inputs_color(), num_inputs_default(), num_inputs_glow(), num_inputs_multicam(), num_inputs_plugin(), num_inputs_speed(), num_inputs_transform(), num_inputs_wipe(), SEQ_ADD, SEQ_ADJUSTMENT, SEQ_ALPHAOVER, SEQ_ALPHAUNDER, SEQ_COLOR, SEQ_CROSS, SEQ_GAMCROSS, SEQ_GLOW, SEQ_MUL, SEQ_MULTICAM, SEQ_OVERDROP, SEQ_PLUGIN, SEQ_SPEED, SEQ_SUB, SEQ_TRANSFORM, SEQ_WIPE, SeqEffectHandle::store_icu_yrange, store_icu_yrange_noop(), and store_icu_yrange_speed().
Referenced by get_sequence_blend(), get_sequence_effect(), and get_sequence_effect_num_inputs().
int get_sequence_effect_num_inputs (int seq_type)
Definition at line 3416 of file seqeffects.c.
References SeqEffectHandle::execute, get_sequence_effect_impl(), and SeqEffectHandle::num_inputs.
Referenced by draw_seq_handle(), seq_effect_find_selected(), seq_single_check(), seq_swap(), seq_tx_test(), sequencer_add_effect_strip_invoke(), sequencer_change_effect_type_exec(), and sequencer_swap_exec().
static ImBuf* IMB_cast_away_list (ImBuf * i) [static]
Definition at line 277 of file seqeffects.c.
References NULL.
Referenced by do_plugin_effect().
static float in_band (float width, float dist, int side, int dir) [static]
Definition at line 1615 of file seqeffects.c.
Referenced by check_zone().
static void init_alpha_over_or_under (Sequence * seq) [static]
Definition at line 404 of file seqeffects.c.
References Sequence::seq1, and Sequence::seq2.
Referenced by get_sequence_effect_impl().
static void init_gammacross (Sequence * UNUSEDseq) [static]
Definition at line 1006 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static void init_glow_effect (Sequence * seq) [static]
Definition at line 2620 of file seqeffects.c.
References GlowVars::bNoComp, GlowVars::dDist, GlowVars::dQuality, Sequence::effectdata, GlowVars::fBoost, GlowVars::fClamp, GlowVars::fMini, MEM_callocN(), and MEM_freeN().
Referenced by get_sequence_effect_impl().
static void init_noop (struct Sequence * UNUSEDseq) [static]
Definition at line 3156 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static void init_plugin (Sequence * seq, const char * fname) [static]
Definition at line 249 of file seqeffects.c.
References add_plugin_seq(), Sequence::name, and Sequence::plugin.
static void init_plugin_noop (struct Sequence * UNUSEDseq, const char * UNUSEDfname) [static]
Definition at line 3166 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static void init_solid_color (Sequence * seq) [static]
Definition at line 2713 of file seqeffects.c.
References SolidColorVars::col, Sequence::effectdata, MEM_callocN(), and MEM_freeN().
Referenced by get_sequence_effect_impl().
static void init_speed_effect (Sequence * seq) [static]
Definition at line 2965 of file seqeffects.c.
References Sequence::effectdata, SpeedControlVars::flags, SpeedControlVars::frameMap, SpeedControlVars::globalSpeed, SpeedControlVars::length, MEM_callocN(), MEM_freeN(), NULL, and SEQ_SPEED_INTEGRATE.
Referenced by get_sequence_effect_impl().
static void init_transform_effect (Sequence * seq) [static]
Definition at line 2042 of file seqeffects.c.
References Sequence::effectdata, TransformVars::interpolation, MEM_callocN(), MEM_freeN(), TransformVars::percent, TransformVars::rotIni, TransformVars::ScalexIni, TransformVars::ScaleyIni, transform(), TransformVars::uniform_scale, TransformVars::xIni, and TransformVars::yIni.
Referenced by get_sequence_effect_impl().
static void init_wipe_effect (Sequence * seq) [static]
Definition at line 1872 of file seqeffects.c.
References Sequence::effectdata, MEM_callocN(), and MEM_freeN().
Referenced by get_sequence_effect_impl().
static float invGammaCorrect (float col) [static]
Definition at line 954 of file seqeffects.c.
References abs(), i, pow(), and RE_GAMMA_TABLE_SIZE.
Referenced by do_gammacross_effect_float().
static void load_gammacross (Sequence * UNUSEDseq) [static]
Definition at line 1010 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static void load_noop (struct Sequence * UNUSEDseq) [static]
Definition at line 3161 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static void load_plugin (Sequence * seq) [static]
Definition at line 262 of file seqeffects.c.
References Sequence::name, open_plugin_seq(), and Sequence::plugin.
Referenced by get_sequence_effect_impl().
static void load_speed_effect (Sequence * seq) [static]
Definition at line 2980 of file seqeffects.c.
References Sequence::effectdata, SpeedControlVars::frameMap, SpeedControlVars::length, and NULL.
Referenced by get_sequence_effect_impl().
static void makeGammaTables (float gamma) [static]
Definition at line 895 of file seqeffects.c.
References color_step, i, pow(), and RE_GAMMA_TABLE_SIZE.
Referenced by build_gammatabs().
static int num_inputs_adjustment (void) [static]
Definition at line 2889 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static int num_inputs_color (void) [static]
Definition at line 2724 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static int num_inputs_default (void) [static]
Definition at line 3176 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static int num_inputs_glow (void) [static]
Definition at line 2636 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static int num_inputs_multicam (void) [static]
Definition at line 2834 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static int num_inputs_plugin (void) [static]
Definition at line 257 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static int num_inputs_speed (void) [static]
Definition at line 2988 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static int num_inputs_transform (void) [static]
Definition at line 2064 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static int num_inputs_wipe (void) [static]
Definition at line 1878 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static void open_plugin_seq (PluginSeq * pis, const char * seqname) [static]
Definition at line 127 of file seqeffects.c.
References BLI_dynlib_find_symbol(), BLI_dynlib_get_error_as_string(), BLI_dynlib_open(), BLI_strncpy(), _PluginInfo::cfra, PluginSeq::cfra, PluginSeq::current_private_data, PluginSeq::doit, error(), PluginSeq::handle, _PluginInfo::init, PluginSeq::instance_private_data, MEM_freeN(), MEM_mallocN(), _PluginInfo::name, PluginSeq::name, NULL, _PluginInfo::nvars, PluginSeq::pname, _PluginInfo::seq_doit, SEQ_NAME_MAXSTR, test_dlerr(), PluginSeq::vars, _PluginInfo::varstr, PluginSeq::varstr, and PluginSeq::version.
Referenced by add_plugin_seq(), copy_plugin(), and load_plugin().
static void precalc_wipe_zone (WipeZone * wipezone, WipeVars * wipe, int xo, int yo) [static]
Definition at line 1604 of file seqeffects.c.
References WipeZone::angle, WipeVars::angle, DEG2RADF, WipeVars::edgeWidth, fabsf, WipeZone::flip, WipeZone::pythangle, sqrtf, tanf, WipeZone::width, WipeZone::xo, and WipeZone::yo.
Referenced by do_wipe_effect_byte(), and do_wipe_effect_float().
static struct ImBuf* prepare_effect_imbufs (SeqRenderData context, struct ImBuf * ibuf1, struct ImBuf * ibuf2, struct ImBuf * ibuf3) [static, read]
Definition at line 76 of file seqeffects.c.
References IB_rect, IB_rectfloat, IMB_allocImBuf(), IMB_float_from_rect_simple(), IMB_rect_from_float(), ImBuf::rect, ImBuf::rect_float, SeqRenderData::rectx, SeqRenderData::recty, ImBuf::x, and ImBuf::y.
Referenced by do_add_effect(), do_alphaover_effect(), do_alphaunder_effect(), do_cross_effect(), do_gammacross_effect(), do_glow_effect(), do_mul_effect(), do_overdrop_effect(), do_plugin_effect(), do_solid_color(), do_sub_effect(), do_transform_effect(), and do_wipe_effect().
static void RVAddBitmaps_byte (unsigned char * a, unsigned char * b, unsigned char * c, int width, int height) [static]
Definition at line 2527 of file seqeffects.c.
References GlowA, GlowB, GlowG, GlowR, ImBuf::index, MIN2, ImBuf::x, and ImBuf::y.
Referenced by do_glow_effect_byte().
static void RVAddBitmaps_float (float * a, float * b, float * c, int width, int height) [static]
Definition at line 2542 of file seqeffects.c.
References GlowA, GlowB, GlowG, GlowR, ImBuf::index, MIN2, ImBuf::x, and ImBuf::y.
Referenced by do_glow_effect_float().
static void RVBlurBitmap2_byte (unsigned char * map, int width, int height, float blur, int quality) [static]
Definition at line 2183 of file seqeffects.c.
References KDL::exp(), filter(), GlowB, GlowG, GlowR, i, ImBuf::index, M_PI, MEM_freeN(), MEM_mallocN(), NULL, swap(), ImBuf::x, ImBuf::y, and zero_v3().
Referenced by do_glow_effect_byte().
static void RVBlurBitmap2_float (float * map, int width, int height, float blur, int quality) [static]
Definition at line 2352 of file seqeffects.c.
References KDL::exp(), filter(), GlowB, GlowG, GlowR, i, ImBuf::index, M_PI, MEM_freeN(), MEM_mallocN(), NULL, swap(), ImBuf::x, ImBuf::y, and zero_v3().
Referenced by do_glow_effect_float().
static void RVIsolateHighlights_byte (unsigned char * in, unsigned char * out, int width, int height, int threshold, float boost, float clamp) [static]
Definition at line 2560 of file seqeffects.c.
References GlowA, GlowB, GlowG, GlowR, ImBuf::index, MIN2, ImBuf::x, and ImBuf::y.
Referenced by do_glow_effect_byte().
static void RVIsolateHighlights_float (float * in, float * out, int width, int height, float threshold, float boost, float clamp) [static]
Definition at line 2590 of file seqeffects.c.
References GlowA, GlowB, GlowG, GlowR, ImBuf::index, MIN2, ImBuf::x, and ImBuf::y.
Referenced by do_glow_effect_float().
void sequence_effect_speed_rebuild_map (Scene * scene, Sequence * seq, int force)
Definition at line 3039 of file seqeffects.c.
References Sequence::effectdata, Sequence::enddisp, evaluate_fcurve(), FALSE, Sequence::flag, SpeedControlVars::flags, ImBuf::flags, SpeedControlVars::frameMap, get_sequence_effect(), SpeedControlVars::globalSpeed, Scene::id, id_data_find_fcurve(), SpeedControlVars::lastValidFrame, Sequence::len, SpeedControlVars::length, MEM_callocN(), MEM_freeN(), NULL, RNA_Sequence, Sequence::seq1, SEQ_SPEED_COMPRESS_IPO_Y, SEQ_SPEED_INTEGRATE, SEQ_USE_EFFECT_DEFAULT_FADE, Sequence::speed_fader, Sequence::start, and Sequence::startdisp.
Referenced by free_imbuf_seq(), seq_render_strip(), and update_changed_seq_recurs().
static void store_icu_yrange_noop (struct Sequence * UNUSEDseq, short UNUSEDadrcode, float * UNUSEDymin, float * UNUSEDymax) [static]
Definition at line 3208 of file seqeffects.c.
Referenced by get_sequence_effect_impl().
static void store_icu_yrange_speed (struct Sequence * seq, short UNUSEDadrcode, float * ymin, float * ymax) [static]
Definition at line 3016 of file seqeffects.c.
References Sequence::effectdata, SpeedControlVars::flags, get_sequence_effect(), Sequence::len, SEQ_SPEED_COMPRESS_IPO_Y, and SEQ_SPEED_INTEGRATE.
Referenced by get_sequence_effect_impl().
static void transform_image (int x, int y, struct ImBuf * ibuf1, struct ImBuf * out, float scale_x, float scale_y, float translate_x, float translate_y, float rotate, int interpolation) [static]
Definition at line 2080 of file seqeffects.c.
References bicubic_interpolation(), bilinear_interpolation(), cos(), neareast_interpolation(), sin(), ImBuf::x, and ImBuf::y.
Referenced by do_transform().
Variable Documentation
float color_domain_table[RE_GAMMA_TABLE_SIZE+1] [static]
Definition at line 889 of file seqeffects.c.
float color_step [static]
Definition at line 890 of file seqeffects.c.
Referenced by makeGammaTables().
float gamfactor_table[RE_GAMMA_TABLE_SIZE] [static]
Definition at line 886 of file seqeffects.c.
float gamma_range_table[RE_GAMMA_TABLE_SIZE+1] [static]
Definition at line 885 of file seqeffects.c.
int gamma_tabs_init = FALSE [static]
Definition at line 881 of file seqeffects.c.
unsigned short gamtab[65536] [static]
Definition at line 879 of file seqeffects.c.
unsigned short igamtab1[256] [static]
Definition at line 880 of file seqeffects.c.
float inv_color_step [static]
Definition at line 891 of file seqeffects.c.
float inv_gamfactor_table[RE_GAMMA_TABLE_SIZE] [static]
Definition at line 888 of file seqeffects.c.
float inv_gamma_range_table[RE_GAMMA_TABLE_SIZE+1] [static]
Definition at line 887 of file seqeffects.c.
float valid_gamma [static]
Definition at line 892 of file seqeffects.c.
float valid_inv_gamma [static]
Definition at line 893 of file seqeffects.c.