Blender: world.c File Reference
world.c File Reference
blenkernel
#include <string.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "DNA_world_types.h"
#include "DNA_scene_types.h"
#include "DNA_texture_types.h"
#include "BLI_listbase.h"
#include "BLI_utildefines.h"
#include "BLI_bpath.h"
#include "BKE_animsys.h"
#include "BKE_global.h"
#include "BKE_icons.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_node.h"
#include "BKE_world.h"
Functions
void free_world (World *wrld)
World * add_world (const char *name)
World * copy_world (World *wrld)
World * localize_world (World *wrld)
void make_local_world (World *wrld)
Detailed Description
Definition in file world.c.
Function Documentation
World* add_world (const char * name) [read]
Definition at line 79 of file world.c.
References alloc_libblock(), World::ao_approx_error, World::ao_env_energy, World::ao_indirect_bounces, World::ao_indirect_energy, World::ao_samp_method, World::aobias, World::aodist, World::aoenergy, World::aosamp, World::exp, World::exposure, G, World::horb, World::horg, World::horr, ID_WO, World::mistdist, World::miststa, NULL, World::preview, World::range, World::skytype, World::stardist, World::starsize, WO_AOSAMP_HAMMERSLEY, Main::world, World::zenb, World::zeng, and World::zenr.
Referenced by new_world_exec().
World* copy_world (World * wrld) [read]
Definition at line 116 of file world.c.
References BKE_previewimg_copy(), copy_libblock(), World::id, id_us_plus(), MAX_MTEX, MEM_mallocN(), World::mtex, World::nodetree, ntreeCopyTree(), World::preview, and MTex::tex.
Referenced by copy_scene(), id_copy(), make_local_world(), and new_world_exec().
void free_world (World * wrld)
Definition at line 54 of file world.c.
References BKE_free_animdata(), BKE_icon_delete(), BKE_previewimg_free(), ID::icon_id, Tex::id, MAX_MTEX, MEM_freeN(), World::mtex, ntreeFreeTree(), World::preview, MTex::tex, and ID::us.
Referenced by free_libblock(), and shader_preview_free().
World* localize_world (World * wrld) [read]
Definition at line 140 of file world.c.
References BLI_remlink(), copy_libblock(), G, World::id, id_us_plus(), MAX_MTEX, MEM_mallocN(), World::mtex, World::nodetree, ntreeLocalize(), NULL, World::preview, and MTex::tex.
Referenced by preview_prepare_scene().
void make_local_world (World * wrld)
Definition at line 165 of file world.c.
References BKE_id_lib_local_paths(), copy_world(), ELEM, FALSE, ListBase::first, G, Scene::id, World::id, id_clear_lib_data(), ID::lib, ID::next, NULL, Main::scene, TRUE, ID::us, and Scene::world.
Referenced by id_make_local().