Blender: btPoolAllocator Class Reference
btPoolAllocator Class Reference
The btPoolAllocator class allows to efficiently allocate a large pool of objects, instead of dynamically allocating them separately.
#include <btPoolAllocator.h>
Public Member Functions
btPoolAllocator (int elemSize, int maxElements)
~btPoolAllocator ()
int getFreeCount () const
int getUsedCount () const
void * allocate (int size)
bool validPtr (void *ptr)
void freeMemory (void *ptr)
int getElementSize () const
unsigned char * getPoolAddress ()
const unsigned char * getPoolAddress () const
Detailed Description
The btPoolAllocator class allows to efficiently allocate a large pool of objects, instead of dynamically allocating them separately.
Definition at line 23 of file btPoolAllocator.h.
Constructor & Destructor Documentation
btPoolAllocator::btPoolAllocator (int elemSize, int maxElements) [inline]
Definition at line 33 of file btPoolAllocator.h.
References btAlignedAlloc, and p.
btPoolAllocator::~btPoolAllocator () [inline]
Definition at line 50 of file btPoolAllocator.h.
References btAlignedFree.
Referenced by btSoftBodyRigidBodyCollisionConfiguration::btSoftBodyRigidBodyCollisionConfiguration(), and btDefaultCollisionConfiguration::~btDefaultCollisionConfiguration().
Member Function Documentation
void* btPoolAllocator::allocate (int size) [inline]
Definition at line 65 of file btPoolAllocator.h.
References btAssert.
Referenced by btCollisionDispatcher::allocateCollisionAlgorithm(), and btCollisionDispatcher::getNewManifold().
void btPoolAllocator::freeMemory (void * ptr) [inline]
Definition at line 88 of file btPoolAllocator.h.
References btAssert.
Referenced by btCollisionDispatcher::freeCollisionAlgorithm(), and btCollisionDispatcher::releaseManifold().
int btPoolAllocator::getElementSize () const [inline]
Definition at line 99 of file btPoolAllocator.h.
Referenced by btSoftBodyRigidBodyCollisionConfiguration::btSoftBodyRigidBodyCollisionConfiguration().
int btPoolAllocator::getFreeCount () const [inline]
Definition at line 55 of file btPoolAllocator.h.
Referenced by btCollisionDispatcher::allocateCollisionAlgorithm(), and btCollisionDispatcher::getNewManifold().
const unsigned char* btPoolAllocator::getPoolAddress () const [inline]
Definition at line 109 of file btPoolAllocator.h.
unsigned char* btPoolAllocator::getPoolAddress () [inline]
Definition at line 104 of file btPoolAllocator.h.
int btPoolAllocator::getUsedCount () const [inline]
Definition at line 60 of file btPoolAllocator.h.
bool btPoolAllocator::validPtr (void * ptr) [inline]
Definition at line 77 of file btPoolAllocator.h.
Referenced by btCollisionDispatcher::freeCollisionAlgorithm(), and btCollisionDispatcher::releaseManifold().
The documentation for this class was generated from the following file:
btPoolAllocator.h