Blender: Util.c File Reference
Util.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <stdio.h>
#include "MEM_guardedalloc.h"
#include "Util.h"
Functions
void * memdbl (void *mem, int *size_pr, int item_size)
char * string_dup (char *str)
void fatal (char *fmt,...)
Function Documentation
void fatal (char * fmt, ...)
Definition at line 59 of file Util.c.
Referenced by multitest_event_handler(), and multitestapp_new().
void* memdbl (void * mem, int * size_pr, int item_size)
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) 2001-2002 by NaN Holding BV. All rights reserved.
The Original Code is: all of this file.
Contributor(s): none yet.
***** END GPL LICENSE BLOCK *****
Definition at line 38 of file Util.c.
References MEM_freeN(), and MEM_mallocN().
Referenced by loggerwindow_log().
char* string_dup (char * str)
Definition at line 50 of file Util.c.
References len(), MEM_mallocN(), and strlen().
Referenced by loggerwindow_log().