Blender: GHOST_NDOFManager Class Reference
GHOST_NDOFManager Class Reference
#include <GHOST_NDOFManager.h>
Public Member Functions
GHOST_NDOFManager (GHOST_System &)
virtual ~GHOST_NDOFManager ()
virtual bool available ()=0
bool setDevice (unsigned short vendor_id, unsigned short product_id)
void setDeadZone (float)
void updateTranslation (short t[3], GHOST_TUns64 time)
void updateRotation (short r[3], GHOST_TUns64 time)
void updateButton (int button_number, bool press, GHOST_TUns64 time)
void updateButtons (int button_bits, GHOST_TUns64 time)
bool sendMotionEvent ()
Protected Attributes
GHOST_System & m_system
Detailed Description
Definition at line 105 of file GHOST_NDOFManager.h.
Constructor & Destructor Documentation
GHOST_NDOFManager::GHOST_NDOFManager (GHOST_System & sys)
Definition at line 192 of file GHOST_NDOFManager.cpp.
virtual GHOST_NDOFManager::~GHOST_NDOFManager () [inline, virtual]
Definition at line 110 of file GHOST_NDOFManager.h.
Member Function Documentation
virtual bool GHOST_NDOFManager::available () [pure virtual]
bool GHOST_NDOFManager::sendMotionEvent ()
Definition at line 425 of file GHOST_NDOFManager.cpp.
References GHOST_TEventNDOFMotionData::dt, GHOST_WindowManager::getActiveWindow(), GHOST_System::getWindowManager(), GHOST_kFinished, GHOST_kFinishing, GHOST_kInProgress, GHOST_kNotStarted, GHOST_kStarting, m_system, nearHomePosition(), NULL, GHOST_TEventNDOFMotionData::progress, GHOST_System::pushEvent(), GHOST_TEventNDOFMotionData::rx, GHOST_TEventNDOFMotionData::ry, GHOST_TEventNDOFMotionData::rz, GHOST_TEventNDOFMotionData::tx, GHOST_TEventNDOFMotionData::ty, and GHOST_TEventNDOFMotionData::tz.
void GHOST_NDOFManager::setDeadZone (float dz)
Definition at line 391 of file GHOST_NDOFManager.cpp.
References GHOST_PRINTF.
bool GHOST_NDOFManager::setDevice (unsigned short vendor_id, unsigned short product_id)
Definition at line 211 of file GHOST_NDOFManager.cpp.
References Generic_HID_map, genericButtonCount, Modern3Dx_HID_map, NDOF_Spaceball5000, NDOF_SpaceExplorer, NDOF_SpaceMousePro, NDOF_SpaceNavigator, NDOF_SpacePilot, NDOF_SpacePilotPro, NDOF_SpaceTraveler, NDOF_UnknownDevice, SpaceExplorer_HID_map, and SpacePilot_HID_map.
void GHOST_NDOFManager::updateButton (int button_number, bool press, GHOST_TUns64 time)
Definition at line 342 of file GHOST_NDOFManager.cpp.
References GHOST_WindowManager::getActiveWindow(), GHOST_System::getWindowManager(), GHOST_kKeyEsc, GHOST_kKeyLeftAlt, GHOST_kKeyLeftControl, GHOST_kKeyLeftShift, m_system, NDOF_BUTTON_ALT, NDOF_BUTTON_CTRL, NDOF_BUTTON_ESC, NDOF_BUTTON_NONE, and NDOF_BUTTON_SHIFT.
Referenced by updateButtons().
void GHOST_NDOFManager::updateButtons (int button_bits, GHOST_TUns64 time)
Definition at line 375 of file GHOST_NDOFManager.cpp.
References KDL::diff(), and updateButton().
void GHOST_NDOFManager::updateRotation (short r[3], GHOST_TUns64 time)
Definition at line 305 of file GHOST_NDOFManager.cpp.
void GHOST_NDOFManager::updateTranslation (short t[3], GHOST_TUns64 time)
Definition at line 298 of file GHOST_NDOFManager.cpp.
Member Data Documentation
GHOST_System& GHOST_NDOFManager::m_system [protected]
Definition at line 149 of file GHOST_NDOFManager.h.
Referenced by sendMotionEvent(), and updateButton().
The documentation for this class was generated from the following files:
GHOST_NDOFManager.h
GHOST_NDOFManager.cpp