Blender: DirectDrawSurface.h File Reference
DirectDrawSurface.h File Reference
DDS
#include <Common.h>
#include <Stream.h>
#include <ColorBlock.h>
#include <Image.h>
Classes
struct DDSPixelFormat
struct DDSCaps
struct DDSHeader10
DDS file header for DX10.
struct DDSHeader
DDS file header.
class DirectDrawSurface
DirectDraw Surface. (DDS)
Functions
void mem_read (Stream &mem, DDSPixelFormat &pf)
void mem_read (Stream &mem, DDSCaps &caps)
void mem_read (Stream &mem, DDSHeader &header)
void mem_read (Stream &mem, DDSHeader10 &header)
Detailed Description
Definition in file DirectDrawSurface.h.
Function Documentation
void mem_read (Stream & mem, DDSPixelFormat & pf)
Definition at line 447 of file DirectDrawSurface.cpp.
References DDSPixelFormat::amask, DDSPixelFormat::bitcount, DDSPixelFormat::bmask, DDSPixelFormat::flags, DDSPixelFormat::fourcc, DDSPixelFormat::gmask, mem_read(), DDSPixelFormat::rmask, and DDSPixelFormat::size.
void mem_read (Stream & mem, DDSHeader10 & header)
Definition at line 467 of file DirectDrawSurface.cpp.
References DDSHeader10::arraySize, DDSHeader10::dxgiFormat, mem_read(), DDSHeader10::miscFlag, DDSHeader10::reserved, and DDSHeader10::resourceDimension.
void mem_read (Stream & mem, DDSHeader & header)
Definition at line 476 of file DirectDrawSurface.cpp.
References DDSHeader::caps, DDSHeader::depth, DDSHeader::flags, DDSHeader::fourcc, DDSHeader::hasDX10Header(), DDSHeader::header10, DDSHeader::height, i, mem_read(), DDSHeader::mipmapcount, DDSHeader::notused, DDSHeader::pf, DDSHeader::pitch, DDSHeader::reserved, DDSHeader::size, and DDSHeader::width.
void mem_read (Stream & mem, DDSCaps & caps)
Definition at line 459 of file DirectDrawSurface.cpp.
References DDSCaps::caps1, DDSCaps::caps2, DDSCaps::caps3, DDSCaps::caps4, and mem_read().