Blender: gjkepa2_impl::MinkowskiDiff Struct Reference
gjkepa2_impl::MinkowskiDiff Struct Reference
Public Member Functions
MinkowskiDiff ()
void EnableMargin (bool enable)
btVector3 Support0 (const btVector3 &d) const
btVector3 Support1 (const btVector3 &d) const
btVector3 Support (const btVector3 &d) const
btVector3 Support (const btVector3 &d, U index) const
Public Attributes
const btConvexShape * m_shapes [2]
btMatrix3x3 m_toshape1
btTransform m_toshape0
btVector3(btConvexShape::* Ls)(const btVector3 &) const
Detailed Description
Definition at line 66 of file btGjkEpa2.cpp.
Constructor & Destructor Documentation
gjkepa2_impl::MinkowskiDiff::MinkowskiDiff () [inline]
Definition at line 78 of file btGjkEpa2.cpp.
Member Function Documentation
void gjkepa2_impl::MinkowskiDiff::EnableMargin (bool enable) [inline]
Definition at line 108 of file btGjkEpa2.cpp.
References Ls.
Referenced by gjkepa2_impl::Initialize().
btVector3 gjkepa2_impl::MinkowskiDiff::Support (const btVector3 & d, U index) const [inline]
Definition at line 129 of file btGjkEpa2.cpp.
References Support0(), and Support1().
btVector3 gjkepa2_impl::MinkowskiDiff::Support (const btVector3 & d) const [inline]
Definition at line 125 of file btGjkEpa2.cpp.
References Support0(), and Support1().
Referenced by btGjkEpaSolver2::Distance(), gjkepa2_impl::GJK::getsupport(), btGjkEpaSolver2::Penetration(), and btGjkEpaSolver2::SignedDistance().
btVector3 gjkepa2_impl::MinkowskiDiff::Support0 (const btVector3 & d) const [inline]
Definition at line 115 of file btGjkEpa2.cpp.
References Ls, and m_shapes.
Referenced by Support().
btVector3 gjkepa2_impl::MinkowskiDiff::Support1 (const btVector3 & d) const [inline]
Definition at line 119 of file btGjkEpa2.cpp.
References Ls, m_shapes, m_toshape0, and m_toshape1.
Referenced by Support().
Member Data Documentation
btVector3(btConvexShape::* gjkepa2_impl::MinkowskiDiff::Ls)(const btVector3 &) const
Definition at line 74 of file btGjkEpa2.cpp.
Referenced by EnableMargin(), Support0(), and Support1().
const btConvexShape* gjkepa2_impl::MinkowskiDiff::m_shapes[2]
Definition at line 68 of file btGjkEpa2.cpp.
Referenced by gjkepa2_impl::Initialize(), Support0(), and Support1().
btTransform gjkepa2_impl::MinkowskiDiff::m_toshape0
Definition at line 70 of file btGjkEpa2.cpp.
Referenced by gjkepa2_impl::Initialize(), and Support1().
btMatrix3x3 gjkepa2_impl::MinkowskiDiff::m_toshape1
Definition at line 69 of file btGjkEpa2.cpp.
Referenced by gjkepa2_impl::Initialize(), and Support1().
The documentation for this struct was generated from the following file:
btGjkEpa2.cpp