Blender: GHOST_WindowWin32 Class Reference
GHOST_WindowWin32 Class Reference
#include <GHOST_WindowWin32.h>
Public Member Functions
GHOST_WindowWin32 (GHOST_SystemWin32 *system, const STR_String &title, GHOST_TInt32 left, GHOST_TInt32 top, GHOST_TUns32 width, GHOST_TUns32 height, GHOST_TWindowState state, GHOST_TDrawingContextType type=GHOST_kDrawingContextTypeNone, const bool stereoVisual=false, const GHOST_TUns16 numOfAASamples=0, GHOST_TEmbedderWindowID parentWindowHwnd=0, GHOST_TSuccess msEnabled=GHOST_kFailure, int msPixelFormat=0)
virtual ~GHOST_WindowWin32 ()
GHOST_Window * getNextWindow ()
virtual bool getValid () const
virtual HWND getHWND () const
virtual void setTitle (const STR_String &title)
virtual void getTitle (STR_String &title) const
virtual void getWindowBounds (GHOST_Rect &bounds) const
virtual void getClientBounds (GHOST_Rect &bounds) const
virtual GHOST_TSuccess setClientWidth (GHOST_TUns32 width)
virtual GHOST_TSuccess setClientHeight (GHOST_TUns32 height)
virtual GHOST_TSuccess setClientSize (GHOST_TUns32 width, GHOST_TUns32 height)
virtual GHOST_TWindowState getState () const
virtual void screenToClient (GHOST_TInt32 inX, GHOST_TInt32 inY, GHOST_TInt32 &outX, GHOST_TInt32 &outY) const
virtual void clientToScreen (GHOST_TInt32 inX, GHOST_TInt32 inY, GHOST_TInt32 &outX, GHOST_TInt32 &outY) const
virtual GHOST_TSuccess setState (GHOST_TWindowState state)
virtual GHOST_TSuccess setOrder (GHOST_TWindowOrder order)
virtual GHOST_TSuccess swapBuffers ()
virtual GHOST_TSuccess activateDrawingContext ()
virtual GHOST_TSuccess invalidate ()
virtual GHOST_TSuccess setProgressBar (float progress)
virtual GHOST_TSuccess endProgressBar ()
void registerMouseClickEvent (int press)
void lostMouseCapture ()
void loadCursor (bool visible, GHOST_TStandardCursor cursorShape) const
const GHOST_TabletData * GetTabletData ()
void processWin32TabletInitEvent ()
void processWin32TabletEvent (WPARAM wParam, LPARAM lParam)
Static Public Member Functions
static wchar_t * getWindowClassName ()
Protected Member Functions
GHOST_TSuccess initMultisample (PIXELFORMATDESCRIPTOR pfd)
virtual GHOST_TSuccess installDrawingContext (GHOST_TDrawingContextType type)
virtual GHOST_TSuccess removeDrawingContext ()
virtual GHOST_TSuccess setWindowCursorVisibility (bool visible)
virtual GHOST_TSuccess setWindowCursorGrab (GHOST_TGrabCursorMode mode)
virtual GHOST_TSuccess setWindowCursorShape (GHOST_TStandardCursor shape)
virtual GHOST_TSuccess setWindowCustomCursorShape (GHOST_TUns8 bitmap[16][2], GHOST_TUns8 mask[16][2], int hotX, int hotY)
virtual GHOST_TSuccess setWindowCustomCursorShape (GHOST_TUns8 *bitmap, GHOST_TUns8 *mask, int sizex, int sizey, int hotX, int hotY, int fg_color, int bg_color)
Protected Attributes
GHOST_SystemWin32 * m_system
GHOST_DropTargetWin32 * m_dropTarget
HWND m_hWnd
HDC m_hDC
HGLRC m_hGlRc
bool m_hasMouseCaptured
bool m_hasGrabMouse
int m_nPressedButtons
HCURSOR m_customCursor
ITaskbarList3 * m_Bar
HMODULE m_wintab
GHOST_TabletData * m_tabletData
HCTX m_tablet
LONG m_maxPressure
LONG m_maxAzimuth
LONG m_maxAltitude
GHOST_TUns16 m_multisample
GHOST_TSuccess m_multisampleEnabled
int m_msPixelFormat
const STR_String & m_title
GHOST_TInt32 m_left
GHOST_TInt32 m_top
GHOST_TUns32 m_width
GHOST_TUns32 m_height
GHOST_TWindowState m_normal_state
bool m_stereo
GHOST_Window * m_nextWindow
GHOST_TEmbedderWindowID m_parentWindowHwnd
Static Protected Attributes
static HGLRC s_firsthGLRc = NULL
static HDC s_firstHDC = NULL
static wchar_t * s_windowClassName = "GHOST_WindowClass"
static const int s_maxTitleLength = 128
Detailed Description
GHOST window on M$ Windows OSs.
Author:
Maarten Gribnau
Date:
May 10, 2001
Definition at line 67 of file GHOST_WindowWin32.h.
Constructor & Destructor Documentation
GHOST_WindowWin32::GHOST_WindowWin32 (GHOST_SystemWin32 * system, const STR_String & title, GHOST_TInt32 left, GHOST_TInt32 top, GHOST_TUns32 width, GHOST_TUns32 height, GHOST_TWindowState state, GHOST_TDrawingContextType type = GHOST_kDrawingContextTypeNone, const bool stereoVisual = false, const GHOST_TUns16 numOfAASamples = 0, GHOST_TEmbedderWindowID parentWindowHwnd = 0, GHOST_TSuccess msEnabled = GHOST_kFailure, int msPixelFormat = 0)
Constructor. Creates a new window and opens it. To check if the window was created properly, use the getValid() method.
Parameters:
title The text shown in the title bar of the window.
left The coordinate of the left edge of the window.
top The coordinate of the top edge of the window.
width The width the window.
height The height the window.
state The state the window is initially opened with.
type The type of drawing context installed in this window.
stereoVisual Stereo visual for quad buffered stereo.
numOfAASamples Number of samples used for AA (zero if no AA)
Definition at line 124 of file GHOST_WindowWin32.cpp.
References GHOST_TabletData::Active, alloc_utf16_from_8(), BOOL, CLSID_TaskbarList, GHOST_kTabletModeNone, GHOST_kWindowStateFullScreen, GHOST_kWindowStateMaximized, GHOST_kWindowStateMinimized, GHOST_kWindowStateNormal, IID_ITaskbarList, left(), LPVOID, m_Bar, m_dropTarget, m_hDC, m_hWnd, m_maxAltitude, m_maxAzimuth, m_maxPressure, m_parentWindowHwnd, m_system, m_tablet, m_tabletData, m_wintab, NULL, PACKETDATA, PACKETMODE, s_firstHDC, s_windowClassName, GHOST_Window::setDrawingContextType(), and TRUE.
Referenced by installDrawingContext().
GHOST_WindowWin32::~GHOST_WindowWin32 () [virtual]
Destructor. Closes the window and disposes resources allocated.
Definition at line 387 of file GHOST_WindowWin32.cpp.
References GHOST_kDrawingContextTypeNone, GHOST_kFailure, m_Bar, m_customCursor, m_dropTarget, m_hDC, m_hWnd, m_multisample, m_multisampleEnabled, m_tablet, m_tabletData, m_wintab, NULL, GHOST_DropTargetWin32::Release(), s_firstHDC, GHOST_Window::setDrawingContextType(), and TBPF_NOPROGRESS.
Member Function Documentation
GHOST_TSuccess GHOST_WindowWin32::activateDrawingContext () [virtual]
Activates the drawing context of this window.
Returns:
Indication of success.
Implements GHOST_IWindow.
Definition at line 664 of file GHOST_WindowWin32.cpp.
References GHOST_kDrawingContextTypeOpenGL, GHOST_kFailure, GHOST_kSuccess, GHOST_Window::m_drawingContextType, m_hDC, m_hGlRc, and TRUE.
void GHOST_WindowWin32::clientToScreen (GHOST_TInt32 inX, GHOST_TInt32 inY, GHOST_TInt32 & outX, GHOST_TInt32 & outY) const [virtual]
Converts a point in screen coordinates to client rectangle coordinates
Parameters:
inX The x-coordinate in the client rectangle.
inY The y-coordinate in the client rectangle.
outX The x-coordinate on the screen.
outY The y-coordinate on the screen.
Implements GHOST_IWindow.
Definition at line 598 of file GHOST_WindowWin32.cpp.
References m_hWnd, and point::x.
GHOST_TSuccess GHOST_WindowWin32::endProgressBar () [virtual]
Hides the progress bar in the icon
Reimplemented from GHOST_Window.
Definition at line 1269 of file GHOST_WindowWin32.cpp.
References GHOST_kFailure, GHOST_kSuccess, m_Bar, m_hWnd, S_OK, and TBPF_NOPROGRESS.
void GHOST_WindowWin32::getClientBounds (GHOST_Rect & bounds) const [virtual]
Returns the client rectangle dimensions. The left and top members of the rectangle are always zero.
Parameters:
bounds The bounding rectangle of the cleient area of the window.
Implements GHOST_IWindow.
Definition at line 468 of file GHOST_WindowWin32.cpp.
References getState(), GHOST_kWindowStateEmbedded, GHOST_kWindowStateMaximized, GHOST_Rect::m_b, m_hWnd, GHOST_Rect::m_l, GHOST_Rect::m_r, GHOST_Rect::m_t, and state.
Referenced by GHOST_SystemWin32::processCursorEvent(), setClientHeight(), setClientSize(), and setClientWidth().
HWND GHOST_WindowWin32::getHWND () const [virtual]
Access to the handle of the window.
Returns:
The handle of the window.
Definition at line 435 of file GHOST_WindowWin32.cpp.
References m_hWnd.
Referenced by GHOST_DropTargetWin32::GHOST_DropTargetWin32(), and initMultisample().
GHOST_Window * GHOST_WindowWin32::getNextWindow ()
Returns the window to replace this one if it's getting replaced
Returns:
The window replacing this one.
Definition at line 425 of file GHOST_WindowWin32.cpp.
References m_nextWindow.
Referenced by GHOST_SystemWin32::createWindow().
GHOST_TWindowState GHOST_WindowWin32::getState () const [virtual]
Returns the state of the window (normal, minimized, maximized).
Returns:
The state of the window.
Implements GHOST_IWindow.
Definition at line 560 of file GHOST_WindowWin32.cpp.
References GHOST_kWindowStateEmbedded, GHOST_kWindowStateFullScreen, GHOST_kWindowStateMaximized, GHOST_kWindowStateMinimized, GHOST_kWindowStateNormal, m_hWnd, m_parentWindowHwnd, and state.
Referenced by getClientBounds(), installDrawingContext(), and setState().
const GHOST_TabletData* GHOST_WindowWin32::GetTabletData () [inline, virtual]
Returns the tablet data (pressure etc).
Returns:
The tablet data (pressure etc).
Implements GHOST_IWindow.
Definition at line 267 of file GHOST_WindowWin32.h.
References m_tabletData.
void GHOST_WindowWin32::getTitle (STR_String & title) const [virtual]
Returns the title displayed in the title bar.
Parameters:
title The title displayed in the title bar.
Implements GHOST_IWindow.
Definition at line 448 of file GHOST_WindowWin32.cpp.
References m_hWnd, and s_maxTitleLength.
bool GHOST_WindowWin32::getValid () const [virtual]
Returns indication as to whether the window is valid.
Returns:
The validity of the window.
Implements GHOST_IWindow.
Definition at line 430 of file GHOST_WindowWin32.cpp.
References m_hWnd.
Referenced by GHOST_SystemWin32::createWindow().
void GHOST_WindowWin32::getWindowBounds (GHOST_Rect & bounds) const [virtual]
Returns the window rectangle dimensions. The dimensions are given in screen coordinates that are relative to the upper-left corner of the screen.
Parameters:
bounds The bounding rectangle of the window.
Implements GHOST_IWindow.
Definition at line 457 of file GHOST_WindowWin32.cpp.
References GHOST_Rect::m_b, m_hWnd, GHOST_Rect::m_l, GHOST_Rect::m_r, and GHOST_Rect::m_t.
Referenced by setClientHeight(), setClientSize(), and setClientWidth().
static wchar_t* GHOST_WindowWin32::getWindowClassName () [inline, static]
Returns the name of the window class.
Returns:
The name of the window class.
Definition at line 239 of file GHOST_WindowWin32.h.
References s_windowClassName.
GHOST_TSuccess GHOST_WindowWin32::initMultisample (PIXELFORMATDESCRIPTOR pfd) [protected]
Definition at line 694 of file GHOST_WindowWin32.cpp.
References FALSE, getHWND(), GHOST_kFailure, GHOST_kSuccess, GHOST_PRINT, GHOST_PRINTF, m_msPixelFormat, m_multisample, m_multisampleEnabled, UINT, and WGL_SAMPLES_ARB.
Referenced by installDrawingContext().
GHOST_TSuccess GHOST_WindowWin32::installDrawingContext (GHOST_TDrawingContextType type) [protected, virtual]
Tries to install a rendering context in this window.
Parameters:
type The type of rendering context installed.
Returns:
Indication of success.
Implements GHOST_Window.
Definition at line 747 of file GHOST_WindowWin32.cpp.
References EnumPixelFormats(), FALSE, getState(), GHOST_ISystem::getSystem(), GHOST_kDrawingContextTypeNone, GHOST_kDrawingContextTypeOpenGL, GHOST_kFailure, GHOST_kSuccess, GHOST_WindowWin32(), initMultisample(), is_crappy_intel_card(), GHOST_Window::m_drawingContextType, m_hDC, m_height, m_hGlRc, m_left, m_msPixelFormat, m_multisample, m_multisampleEnabled, m_nextWindow, m_parentWindowHwnd, m_stereo, GHOST_Window::m_stereoVisual, m_title, m_top, m_width, NULL, removeDrawingContext(), s_firsthGLRc, sPreferredFormat, and TRUE.
GHOST_TSuccess GHOST_WindowWin32::invalidate (void) [virtual]
Invalidates the contents of this window.
Implements GHOST_IWindow.
Definition at line 682 of file GHOST_WindowWin32.cpp.
References FALSE, GHOST_kFailure, GHOST_kSuccess, and m_hWnd.
void GHOST_WindowWin32::loadCursor (bool visible, GHOST_TStandardCursor cursorShape) const
Loads the windows equivalent of a standard GHOST cursor.
Parameters:
visible Flag for cursor visibility.
cursorShape The cursor shape.
Definition at line 979 of file GHOST_WindowWin32.cpp.
References FALSE, GHOST_kStandardCursorBottomLeftCorner, GHOST_kStandardCursorBottomRightCorner, GHOST_kStandardCursorBottomSide, GHOST_kStandardCursorCopy, GHOST_kStandardCursorCrosshair, GHOST_kStandardCursorCustom, GHOST_kStandardCursorCycle, GHOST_kStandardCursorDefault, GHOST_kStandardCursorDestroy, GHOST_kStandardCursorHelp, GHOST_kStandardCursorInfo, GHOST_kStandardCursorLeftArrow, GHOST_kStandardCursorLeftRight, GHOST_kStandardCursorLeftSide, GHOST_kStandardCursorPencil, GHOST_kStandardCursorRightArrow, GHOST_kStandardCursorSpray, GHOST_kStandardCursorText, GHOST_kStandardCursorTopLeftCorner, GHOST_kStandardCursorTopRightCorner, GHOST_kStandardCursorTopSide, GHOST_kStandardCursorUpDown, GHOST_kStandardCursorWait, m_customCursor, and TRUE.
Referenced by GHOST_SystemWin32::s_wndProc(), setWindowCursorShape(), setWindowCursorVisibility(), and setWindowCustomCursorShape().
void GHOST_WindowWin32::lostMouseCapture ()
Inform the window that it has lost mouse capture, called in response to native window system messages.
Definition at line 945 of file GHOST_WindowWin32.cpp.
References m_hasGrabMouse, m_hasMouseCaptured, and m_nPressedButtons.
Referenced by GHOST_SystemWin32::s_wndProc().
void GHOST_WindowWin32::processWin32TabletEvent (WPARAM wParam, LPARAM lParam)
Definition at line 1118 of file GHOST_WindowWin32.cpp.
References GHOST_TabletData::Active, cos(), fabs(), GHOST_kTabletModeEraser, GHOST_kTabletModeNone, GHOST_kTabletModeStylus, HCTX(), m_maxAltitude, m_maxAzimuth, m_maxPressure, M_PI, m_tabletData, m_wintab, GHOST_TabletData::Pressure, sin(), GHOST_TabletData::Xtilt, and GHOST_TabletData::Ytilt.
void GHOST_WindowWin32::processWin32TabletInitEvent ()
Definition at line 1085 of file GHOST_WindowWin32.cpp.
References GHOST_TabletData::Active, BOOL, GHOST_kTabletModeNone, m_maxAltitude, m_maxAzimuth, m_maxPressure, m_tabletData, and m_wintab.
void GHOST_WindowWin32::registerMouseClickEvent (int press)
Register a mouse click event (should be called for any real button press, controls mouse capturing).
Parameters:
press 0 - mouse pressed 1 - mouse released 2 - operator grab 3 - operator ungrab
Definition at line 954 of file GHOST_WindowWin32.cpp.
References m_hasGrabMouse, m_hasMouseCaptured, m_hWnd, and m_nPressedButtons.
Referenced by GHOST_SystemWin32::s_wndProc(), and setWindowCursorGrab().
GHOST_TSuccess GHOST_WindowWin32::removeDrawingContext () [protected, virtual]
Removes the current drawing context.
Returns:
Indication of success.
Implements GHOST_Window.
Definition at line 921 of file GHOST_WindowWin32.cpp.
References GHOST_kDrawingContextTypeNone, GHOST_kDrawingContextTypeOpenGL, GHOST_kFailure, GHOST_kSuccess, GHOST_Window::m_drawingContextType, m_hGlRc, s_firsthGLRc, and TRUE.
Referenced by installDrawingContext().
void GHOST_WindowWin32::screenToClient (GHOST_TInt32 inX, GHOST_TInt32 inY, GHOST_TInt32 & outX, GHOST_TInt32 & outY) const [virtual]
Converts a point in screen coordinates to client rectangle coordinates
Parameters:
inX The x-coordinate on the screen.
inY The y-coordinate on the screen.
outX The x-coordinate in the client rectangle.
outY The y-coordinate in the client rectangle.
Implements GHOST_IWindow.
Definition at line 589 of file GHOST_WindowWin32.cpp.
References m_hWnd, and point::x.
GHOST_TSuccess GHOST_WindowWin32::setClientHeight (GHOST_TUns32 height) [virtual]
Resizes client rectangle height.
Parameters:
height The new height of the client area of the window.
Implements GHOST_IWindow.
Definition at line 522 of file GHOST_WindowWin32.cpp.
References getClientBounds(), GHOST_Rect::getHeight(), GHOST_Rect::getWidth(), getWindowBounds(), GHOST_kFailure, GHOST_kSuccess, and m_hWnd.
GHOST_TSuccess GHOST_WindowWin32::setClientSize (GHOST_TUns32 width, GHOST_TUns32 height) [virtual]
Resizes client rectangle.
Parameters:
width The new width of the client area of the window.
height The new height of the client area of the window.
Implements GHOST_IWindow.
Definition at line 541 of file GHOST_WindowWin32.cpp.
References getClientBounds(), GHOST_Rect::getHeight(), GHOST_Rect::getWidth(), getWindowBounds(), GHOST_kFailure, GHOST_kSuccess, and m_hWnd.
GHOST_TSuccess GHOST_WindowWin32::setClientWidth (GHOST_TUns32 width) [virtual]
Resizes client rectangle width.
Parameters:
width The new width of the client area of the window.
Implements GHOST_IWindow.
Definition at line 503 of file GHOST_WindowWin32.cpp.
References getClientBounds(), GHOST_Rect::getHeight(), GHOST_Rect::getWidth(), getWindowBounds(), GHOST_kFailure, GHOST_kSuccess, and m_hWnd.
GHOST_TSuccess GHOST_WindowWin32::setOrder (GHOST_TWindowOrder order) [virtual]
Sets the order of the window (bottom, top).
Parameters:
order The order of the window.
Returns:
Indication of success.
Implements GHOST_IWindow.
Definition at line 646 of file GHOST_WindowWin32.cpp.
References GHOST_kFailure, GHOST_kSuccess, GHOST_kWindowOrderTop, m_hWnd, and TRUE.
GHOST_TSuccess GHOST_WindowWin32::setProgressBar (float progress) [virtual]
Sets the progress bar value displayed in the window/application icon
Parameters:
progress The progress %
Reimplemented from GHOST_Window.
Definition at line 1260 of file GHOST_WindowWin32.cpp.
References GHOST_kFailure, GHOST_kSuccess, m_Bar, m_hWnd, and S_OK.
GHOST_TSuccess GHOST_WindowWin32::setState (GHOST_TWindowState state) [virtual]
Sets the state of the window (normal, minimized, maximized).
Parameters:
state The state of the window.
Returns:
Indication of success.
Implements GHOST_IWindow.
Definition at line 607 of file GHOST_WindowWin32.cpp.
References getState(), GHOST_kFailure, GHOST_kSuccess, GHOST_kWindowStateEmbedded, GHOST_kWindowStateFullScreen, GHOST_kWindowStateMaximized, GHOST_kWindowStateMinimized, GHOST_kWindowStateNormal, m_hWnd, m_normal_state, and TRUE.
void GHOST_WindowWin32::setTitle (const STR_String & title) [virtual]
Sets the title displayed in the title bar.
Parameters:
title The title to display in the title bar.
Implements GHOST_IWindow.
Definition at line 440 of file GHOST_WindowWin32.cpp.
References alloc_utf16_from_8(), and m_hWnd.
GHOST_TSuccess GHOST_WindowWin32::setWindowCursorGrab (GHOST_TGrabCursorMode mode) [protected, virtual]
Sets the cursor grab on the window using native window system calls. Using registerMouseClickEvent.
Parameters:
mode GHOST_TGrabCursorMode.
Reimplemented from GHOST_Window.
Definition at line 1036 of file GHOST_WindowWin32.cpp.
References GHOST_SystemWin32::getCursorPosition(), GHOST_kGrabDisable, GHOST_kGrabHide, GHOST_kGrabNormal, GHOST_kSuccess, GHOST_Window::m_cursorGrab, GHOST_Window::m_cursorGrabBounds, GHOST_Window::m_cursorGrabInitPos, GHOST_Rect::m_l, GHOST_Rect::m_r, m_system, registerMouseClickEvent(), GHOST_Window::setCursorGrabAccum(), GHOST_SystemWin32::setCursorPosition(), and setWindowCursorVisibility().
GHOST_TSuccess GHOST_WindowWin32::setWindowCursorShape (GHOST_TStandardCursor shape) [protected, virtual]
Sets the cursor shape on the window using native window system calls.
Implements GHOST_Window.
Definition at line 1071 of file GHOST_WindowWin32.cpp.
References GHOST_Window::getCursorVisibility(), GHOST_kSuccess, loadCursor(), m_customCursor, m_hWnd, and NULL.
GHOST_TSuccess GHOST_WindowWin32::setWindowCursorVisibility (bool visible) [protected, virtual]
Sets the cursor visibility on the window using native window system calls.
Implements GHOST_Window.
Definition at line 1027 of file GHOST_WindowWin32.cpp.
References GHOST_Window::getCursorShape(), GHOST_kSuccess, loadCursor(), and m_hWnd.
Referenced by setWindowCursorGrab().
GHOST_TSuccess GHOST_WindowWin32::setWindowCustomCursorShape (GHOST_TUns8 bitmap[16][2], GHOST_TUns8 mask[16][2], int hotX, int hotY) [protected, virtual]
Sets the cursor shape on the window using native window system calls.
Implements GHOST_Window.
Definition at line 1206 of file GHOST_WindowWin32.cpp.
GHOST_TSuccess GHOST_WindowWin32::setWindowCustomCursorShape (GHOST_TUns8 * bitmap, GHOST_TUns8 * mask, int sizex, int sizey, int hotX, int hotY, int fg_color, int bg_color) [protected, virtual]
Implements GHOST_Window.
Definition at line 1214 of file GHOST_WindowWin32.cpp.
References GHOST_Window::getCursorVisibility(), GHOST_kFailure, GHOST_kStandardCursorCustom, GHOST_kSuccess, loadCursor(), m_customCursor, m_hWnd, NULL, and uns8ReverseBits().
GHOST_TSuccess GHOST_WindowWin32::swapBuffers () [virtual]
Swaps front and back buffers of a window.
Returns:
Indication of success.
Implements GHOST_IWindow.
Definition at line 653 of file GHOST_WindowWin32.cpp.
References GHOST_kFailure, GHOST_kSuccess, is_crappy_intel_card(), m_hDC, and TRUE.
Member Data Documentation
ITaskbarList3* GHOST_WindowWin32::m_Bar [protected]
ITaskbarList3 structure for progress bar
Definition at line 352 of file GHOST_WindowWin32.h.
Referenced by endProgressBar(), GHOST_WindowWin32(), setProgressBar(), and ~GHOST_WindowWin32().
HCURSOR GHOST_WindowWin32::m_customCursor [protected]
HCURSOR structure of the custom cursor
Definition at line 349 of file GHOST_WindowWin32.h.
Referenced by loadCursor(), setWindowCursorShape(), setWindowCustomCursorShape(), and ~GHOST_WindowWin32().
GHOST_DropTargetWin32* GHOST_WindowWin32::m_dropTarget [protected]
Pointer to COM IDropTarget implementor
Definition at line 330 of file GHOST_WindowWin32.h.
Referenced by GHOST_WindowWin32(), and ~GHOST_WindowWin32().
bool GHOST_WindowWin32::m_hasGrabMouse [protected]
Flag if an operator grabs the mouse with WM_cursor_grab/ungrab() Multiple grabs must be realesed with a single ungrab
Definition at line 345 of file GHOST_WindowWin32.h.
Referenced by lostMouseCapture(), and registerMouseClickEvent().
bool GHOST_WindowWin32::m_hasMouseCaptured [protected]
Flag for if window has captured the mouse
Definition at line 342 of file GHOST_WindowWin32.h.
Referenced by lostMouseCapture(), and registerMouseClickEvent().
HDC GHOST_WindowWin32::m_hDC [protected]
Device context handle.
Definition at line 334 of file GHOST_WindowWin32.h.
Referenced by activateDrawingContext(), GHOST_WindowWin32(), installDrawingContext(), swapBuffers(), and ~GHOST_WindowWin32().
GHOST_TUns32 GHOST_WindowWin32::m_height [protected]
Definition at line 382 of file GHOST_WindowWin32.h.
Referenced by installDrawingContext().
HGLRC GHOST_WindowWin32::m_hGlRc [protected]
OpenGL rendering context.
Definition at line 336 of file GHOST_WindowWin32.h.
Referenced by activateDrawingContext(), installDrawingContext(), and removeDrawingContext().
HWND GHOST_WindowWin32::m_hWnd [protected]
Window handle.
Definition at line 332 of file GHOST_WindowWin32.h.
Referenced by clientToScreen(), endProgressBar(), getClientBounds(), getHWND(), getState(), getTitle(), getValid(), getWindowBounds(), GHOST_WindowWin32(), invalidate(), registerMouseClickEvent(), screenToClient(), setClientHeight(), setClientSize(), setClientWidth(), setOrder(), setProgressBar(), setState(), setTitle(), setWindowCursorShape(), setWindowCursorVisibility(), setWindowCustomCursorShape(), and ~GHOST_WindowWin32().
GHOST_TInt32 GHOST_WindowWin32::m_left [protected]
Definition at line 379 of file GHOST_WindowWin32.h.
Referenced by installDrawingContext().
LONG GHOST_WindowWin32::m_maxAltitude [protected]
Definition at line 366 of file GHOST_WindowWin32.h.
Referenced by GHOST_WindowWin32(), processWin32TabletEvent(), and processWin32TabletInitEvent().
LONG GHOST_WindowWin32::m_maxAzimuth [protected]
Definition at line 366 of file GHOST_WindowWin32.h.
Referenced by GHOST_WindowWin32(), processWin32TabletEvent(), and processWin32TabletInitEvent().
LONG GHOST_WindowWin32::m_maxPressure [protected]
Definition at line 365 of file GHOST_WindowWin32.h.
Referenced by GHOST_WindowWin32(), processWin32TabletEvent(), and processWin32TabletInitEvent().
int GHOST_WindowWin32::m_msPixelFormat [protected]
The pixelFormat to use for multisample
Definition at line 375 of file GHOST_WindowWin32.h.
Referenced by initMultisample(), and installDrawingContext().
GHOST_TUns16 GHOST_WindowWin32::m_multisample [protected]
Preferred number of samples
Definition at line 369 of file GHOST_WindowWin32.h.
Referenced by initMultisample(), installDrawingContext(), and ~GHOST_WindowWin32().
GHOST_TSuccess GHOST_WindowWin32::m_multisampleEnabled [protected]
Check if multisample is supported
Definition at line 372 of file GHOST_WindowWin32.h.
Referenced by initMultisample(), installDrawingContext(), and ~GHOST_WindowWin32().
GHOST_Window* GHOST_WindowWin32::m_nextWindow [protected]
The GHOST_System passes this to wm if this window is being replaced
Definition at line 387 of file GHOST_WindowWin32.h.
Referenced by getNextWindow(), and installDrawingContext().
GHOST_TWindowState GHOST_WindowWin32::m_normal_state [protected]
Definition at line 383 of file GHOST_WindowWin32.h.
Referenced by setState().
int GHOST_WindowWin32::m_nPressedButtons [protected]
Count of number of pressed buttons
Definition at line 347 of file GHOST_WindowWin32.h.
Referenced by lostMouseCapture(), and registerMouseClickEvent().
GHOST_TEmbedderWindowID GHOST_WindowWin32::m_parentWindowHwnd [protected]
Hwnd to parent window
Definition at line 390 of file GHOST_WindowWin32.h.
Referenced by getState(), GHOST_WindowWin32(), and installDrawingContext().
bool GHOST_WindowWin32::m_stereo [protected]
Definition at line 384 of file GHOST_WindowWin32.h.
Referenced by installDrawingContext().
GHOST_SystemWin32* GHOST_WindowWin32::m_system [protected]
Pointer to system
Definition at line 328 of file GHOST_WindowWin32.h.
Referenced by GHOST_WindowWin32(), and setWindowCursorGrab().
HCTX GHOST_WindowWin32::m_tablet [protected]
Stores the Tablet context if detected Tablet features using WinTab.dll
Definition at line 364 of file GHOST_WindowWin32.h.
Referenced by GHOST_WindowWin32(), and ~GHOST_WindowWin32().
GHOST_TabletData* GHOST_WindowWin32::m_tabletData [protected]
Tablet data for GHOST
Definition at line 361 of file GHOST_WindowWin32.h.
Referenced by GetTabletData(), GHOST_WindowWin32(), processWin32TabletEvent(), processWin32TabletInitEvent(), and ~GHOST_WindowWin32().
const STR_String& GHOST_WindowWin32::m_title [protected]
We need to following to recreate the window
Definition at line 378 of file GHOST_WindowWin32.h.
Referenced by installDrawingContext().
GHOST_TInt32 GHOST_WindowWin32::m_top [protected]
Definition at line 380 of file GHOST_WindowWin32.h.
Referenced by installDrawingContext().
GHOST_TUns32 GHOST_WindowWin32::m_width [protected]
Definition at line 381 of file GHOST_WindowWin32.h.
Referenced by installDrawingContext().
HMODULE GHOST_WindowWin32::m_wintab [protected]
WinTab dll handle
Definition at line 358 of file GHOST_WindowWin32.h.
Referenced by GHOST_WindowWin32(), processWin32TabletEvent(), processWin32TabletInitEvent(), and ~GHOST_WindowWin32().
HDC GHOST_WindowWin32::s_firstHDC = NULL [static, protected]
The first created device context handle.
Definition at line 340 of file GHOST_WindowWin32.h.
Referenced by GHOST_WindowWin32(), and ~GHOST_WindowWin32().
HGLRC GHOST_WindowWin32::s_firsthGLRc = NULL [static, protected]
The first created OpenGL context (for sharing display lists)
Definition at line 338 of file GHOST_WindowWin32.h.
Referenced by installDrawingContext(), and removeDrawingContext().
const int GHOST_WindowWin32::s_maxTitleLength = 128 [static, protected]
Definition at line 355 of file GHOST_WindowWin32.h.
Referenced by getTitle().
wchar_t * GHOST_WindowWin32::s_windowClassName = "GHOST_WindowClass" [static, protected]
Definition at line 354 of file GHOST_WindowWin32.h.
Referenced by getWindowClassName(), and GHOST_WindowWin32().
The documentation for this class was generated from the following files:
GHOST_WindowWin32.h
GHOST_WindowWin32.cpp