Blender: btGEN_List Class Reference
btGEN_List Class Reference
#include <btList.h>
Public Member Functions
btGEN_List ()
btGEN_Link * getHead () const
btGEN_Link * getTail () const
void addHead (btGEN_Link *link)
void addTail (btGEN_Link *link)
Detailed Description
Definition at line 55 of file btList.h.
Constructor & Destructor Documentation
btGEN_List::btGEN_List () [inline]
Definition at line 57 of file btList.h.
Member Function Documentation
void btGEN_List::addHead (btGEN_Link * link) [inline]
Definition at line 62 of file btList.h.
References btGEN_Link::insertAfter().
void btGEN_List::addTail (btGEN_Link * link) [inline]
Definition at line 63 of file btList.h.
References btGEN_Link::insertBefore().
btGEN_Link* btGEN_List::getHead () const [inline]
Definition at line 59 of file btList.h.
References btGEN_Link::getNext().
btGEN_Link* btGEN_List::getTail () const [inline]
Definition at line 60 of file btList.h.
References btGEN_Link::getPrev().
The documentation for this class was generated from the following file:
btList.h