Blender: render_update.c File Reference
render_update.c File Reference
render
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_lamp_types.h"
#include "DNA_material_types.h"
#include "DNA_node_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "DNA_view3d_types.h"
#include "DNA_world_types.h"
#include "BLI_threads.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_icons.h"
#include "BKE_image.h"
#include "BKE_main.h"
#include "BKE_material.h"
#include "BKE_node.h"
#include "BKE_scene.h"
#include "BKE_texture.h"
#include "BKE_world.h"
#include "GPU_material.h"
#include "RE_engine.h"
#include "ED_node.h"
#include "ED_render.h"
#include "render_intern.h"
Functions
void ED_render_scene_update (Main *bmain, Scene *scene, int updated)
void ED_render_engine_area_exit (ScrArea *sa)
void ED_render_engine_changed (Main *bmain)
static int mtex_use_tex (MTex **mtex, int tot, Tex *tex)
static int nodes_use_tex (bNodeTree *ntree, Tex *tex)
static int nodes_use_material (bNodeTree *ntree, Material *ma)
static void material_changed (Main *bmain, Material *ma)
static void texture_changed (Main *bmain, Tex *tex)
static void lamp_changed (Main *bmain, Lamp *la)
static void world_changed (Main *bmain, World *wo)
static void image_changed (Main *bmain, Image *ima)
static void scene_changed (Main *bmain, Scene *UNUSED(scene))
void ED_render_id_flush_update (Main *bmain, ID *id)
Detailed Description
Definition in file render_update.c.
Function Documentation
void ED_render_engine_area_exit (ScrArea * sa)
Definition at line 119 of file render_update.c.
References ListBase::first, ARegion::next, NULL, RE_engine_free(), ScrArea::regionbase, ARegion::regiondata, ARegion::regiontype, RegionView3D::render_engine, RGN_TYPE_WINDOW, SPACE_VIEW3D, and ScrArea::spacetype.
Referenced by ED_area_exit(), and ED_render_engine_changed().
void ED_render_engine_changed (Main * bmain)
Definition at line 142 of file render_update.c.
References bScreen::areabase, ED_render_engine_area_exit(), ListBase::first, bScreen::id, ScrArea::next, ID::next, and Main::screen.
Referenced by ED_screen_set_scene().
void ED_render_id_flush_update (Main * bmain, ID * id)
Definition at line 348 of file render_update.c.
References GS, ID_IM, ID_LA, ID_MA, ID_SCE, ID_TE, ID_WO, image_changed(), lamp_changed(), material_changed(), ID::name, scene_changed(), texture_changed(), and world_changed().
Referenced by ED_object_add_duplicate(), ED_object_add_type(), and WM_init().
void ED_render_scene_update (Main * bmain, Scene * scene, int updated)
Definition at line 69 of file render_update.c.
References bScreen::areabase, BLI_thread_is_main(), C, CTX_create(), CTX_data_main_set(), CTX_data_scene_set(), CTX_free(), CTX_wm_area_set(), CTX_wm_manager_set(), CTX_wm_region_set(), CTX_wm_screen_set(), ListBase::first, RenderEngine::flag, bScreen::id, ARegion::next, ScrArea::next, ID::next, RE_ENGINE_DO_UPDATE, ScrArea::regionbase, ARegion::regiondata, ARegion::regiontype, RegionView3D::render_engine, RGN_TYPE_WINDOW, Main::screen, SPACE_VIEW3D, ScrArea::spacetype, RenderEngine::type, RenderEngineType::view_update, and Main::wm.
Referenced by WM_init().
static void image_changed (Main * bmain, Image * ima) [static]
Definition at line 320 of file render_update.c.
References BKE_icon_changed(), BKE_icon_getid(), ListBase::first, Tex::id, Image::id, Tex::ima, ID::next, Main::tex, MTex::tex, and texture_changed().
Referenced by ED_render_id_flush_update().
static void lamp_changed (Main * bmain, Lamp * la) [static]
Definition at line 289 of file render_update.c.
References BKE_icon_changed(), BKE_icon_getid(), Object::data, ListBase::first, GPU_lamp_free(), GPU_material_free(), Object::gpulamp, Material::gpumaterial, Material::id, Object::id, Lamp::id, Main::mat, ID::next, and Main::object.
Referenced by ED_render_id_flush_update().
static void material_changed (Main * bmain, Material * ma) [static]
Definition at line 214 of file render_update.c.
References BKE_icon_changed(), BKE_icon_getid(), ListBase::first, GPU_material_free(), Material::gpumaterial, Material::id, Main::mat, ID::next, nodes_use_material(), Material::nodetree, and Material::use_nodes.
Referenced by ED_render_id_flush_update().
static int mtex_use_tex (MTex ** mtex, int tot, Tex * tex) [static]
Definition at line 158 of file render_update.c.
Referenced by nodes_use_tex(), and texture_changed().
static int nodes_use_material (bNodeTree * ntree, Material * ma) [static]
Definition at line 195 of file render_update.c.
References ListBase::first, bNode::id, bNode::next, NODE_GROUP, bNodeTree::nodes, and bNode::type.
Referenced by material_changed().
static int nodes_use_tex (bNodeTree * ntree, Tex * tex) [static]
Definition at line 172 of file render_update.c.
References ListBase::first, GS, bNode::id, ID_MA, MAX_MTEX, mtex_use_tex(), ID::name, bNode::next, NODE_GROUP, bNodeTree::nodes, and bNode::type.
Referenced by texture_changed().
static void scene_changed (Main * bmain, Scene * UNUSEDscene) [static]
Definition at line 333 of file render_update.c.
References ListBase::first, GPU_lamp_free(), GPU_material_free(), Object::gpulamp, Material::gpumaterial, Material::id, Object::id, Main::mat, ID::next, and Main::object.
Referenced by ED_render_id_flush_update().
static void texture_changed (Main * bmain, Tex * tex) [static]
Definition at line 237 of file render_update.c.
References BKE_icon_changed(), BKE_icon_getid(), ED_node_changed_update(), ListBase::first, GPU_material_free(), Material::gpumaterial, bNode::id, Scene::id, World::id, Lamp::id, Material::id, Tex::id, Main::lamp, Main::mat, MAX_MTEX, World::mtex, Lamp::mtex, Material::mtex, mtex_use_tex(), bNode::next, ID::next, bNodeTree::nodes, nodes_use_tex(), Scene::nodetree, World::nodetree, Lamp::nodetree, Material::nodetree, Main::scene, Scene::use_nodes, Material::use_nodes, and Main::world.
Referenced by ED_render_id_flush_update(), and image_changed().
static void world_changed (Main * bmain, World * wo) [static]
Definition at line 307 of file render_update.c.
References BKE_icon_changed(), BKE_icon_getid(), ListBase::first, GPU_material_free(), Material::gpumaterial, Material::id, World::id, Main::mat, and ID::next.
Referenced by ED_render_id_flush_update().