Blender: MD5Hash Class Reference
MD5Hash Class Reference
#include <util_md5.h>
Public Member Functions
MD5Hash ()
~MD5Hash ()
void append (const uint8_t *data, int size)
bool append_file (const string &filepath)
string get_hex ()
Protected Member Functions
void process (const uint8_t *data)
void finish (uint8_t digest[16])
Protected Attributes
uint32_t count [2]
uint32_t abcd [4]
uint8_t buf [64]
Detailed Description
Definition at line 38 of file util_md5.h.
Constructor & Destructor Documentation
MD5Hash::MD5Hash ()
Definition at line 262 of file util_md5.cpp.
References abcd, count, and T_MASK.
MD5Hash::~MD5Hash ()
Definition at line 271 of file util_md5.cpp.
Member Function Documentation
void MD5Hash::append (const uint8_t * data, int size)
Definition at line 275 of file util_md5.cpp.
References buf, copy(), count, data, left(), p, and process().
Referenced by append_file(), finish(), CacheData::get_filename(), and path_files_md5_hash_recursive().
bool MD5Hash::append_file (const string & filepath)
Definition at line 312 of file util_md5.cpp.
References append().
Referenced by path_files_md5_hash_recursive().
void MD5Hash::finish (uint8_t digest[16]) [protected]
Definition at line 337 of file util_md5.cpp.
References abcd, append(), count, data, and i.
Referenced by get_hex().
string MD5Hash::get_hex ()
Definition at line 361 of file util_md5.cpp.
References buf, finish(), and i.
Referenced by CacheData::get_filename(), and path_files_md5_hash().
void MD5Hash::process (const uint8_t * data) [protected]
Definition at line 99 of file util_md5.cpp.
References abcd, data, i, SET, T1, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T2, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T3, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T4, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49, T5, T50, T51, T52, T53, T54, T55, T56, T57, T58, T59, T6, T60, T61, T62, T63, T64, T7, T8, T9, and X.
Referenced by append().
Member Data Documentation
uint32_t MD5Hash::abcd[4] [protected]
Definition at line 52 of file util_md5.h.
Referenced by finish(), MD5Hash(), and process().
uint8_t MD5Hash::buf[64] [protected]
Definition at line 53 of file util_md5.h.
Referenced by append(), and get_hex().
uint32_t MD5Hash::count[2] [protected]
Definition at line 51 of file util_md5.h.
Referenced by append(), finish(), and MD5Hash().
The documentation for this class was generated from the following files:
util_md5.h
util_md5.cpp