Blender: util.c File Reference
util.c File Reference
opennl
#include <math.h>
#include "ssp_defs.h"
#include "util.h"
Defines
#define NBUCKS 10
Functions
flops_t LUFactFlops (SuperLUStat_t *stat)
flops_t LUSolveFlops (SuperLUStat_t *stat)
float SpaSize (int n, int np, float sum_npw)
float DenseSize (int n, float sum_nw)
void superlu_abort_and_exit (char *msg)
void set_default_options (superlu_options_t *options)
void Destroy_SuperMatrix_Store (SuperMatrix *A)
void Destroy_CompCol_Matrix (SuperMatrix *A)
void Destroy_CompRow_Matrix (SuperMatrix *A)
void Destroy_SuperNode_Matrix (SuperMatrix *A)
void Destroy_CompCol_Permuted (SuperMatrix *A)
void Destroy_Dense_Matrix (SuperMatrix *A)
void resetrep_col (const int nseg, const int *segrep, int *repfnz)
void countnz (const int n, int *xprune, int *nnzL, int *nnzU, GlobalLU_t *Glu)
void fixupL (const int n, const int *perm_r, GlobalLU_t *Glu)
void print_panel_seg (int n, int w, int jcol, int nseg, int *segrep, int *repfnz)
void StatInit (SuperLUStat_t *stat)
void StatPrint (SuperLUStat_t *stat)
void StatFree (SuperLUStat_t *stat)
void ifill (int *a, int alen, int ival)
void super_stats (int nsuper, int *xsup)
void check_repfnz (int n, int w, int jcol, int *repfnz)
void PrintSumm (char *type, int nfail, int nrun, int nerrs)
int print_int_vec (char *what, int n, int *vec)
Variables
static int max_sup_size
Detailed Description
Definition in file intern/opennl/superlu/util.c.
Define Documentation
#define NBUCKS 10
Definition at line 309 of file intern/opennl/superlu/util.c.
Referenced by super_stats().
Function Documentation
void check_repfnz (int n, int w, int jcol, int * repfnz)
Definition at line 365 of file intern/opennl/superlu/util.c.
References ABORT, and EMPTY.
void countnz (const int n, int * xprune, int * nnzL, int * nnzU, GlobalLU_t * Glu)
Definition at line 136 of file intern/opennl/superlu/util.c.
References i, GlobalLU_t::supno, GlobalLU_t::xlsub, GlobalLU_t::xsup, and GlobalLU_t::xusub.
Referenced by sgstrf().
float DenseSize (int n, float sum_nw)
Definition at line 355 of file intern/opennl/superlu/util.c.
void Destroy_CompCol_Matrix (SuperMatrix * A)
Definition at line 69 of file intern/opennl/superlu/util.c.
References SuperMatrix::Store, and SUPERLU_FREE.
Referenced by __nlFree_SUPERLU().
void Destroy_CompCol_Permuted (SuperMatrix * A)
Definition at line 100 of file intern/opennl/superlu/util.c.
References SuperMatrix::Store, and SUPERLU_FREE.
Referenced by __nlFactorize_SUPERLU(), and sgssv().
void Destroy_CompRow_Matrix (SuperMatrix * A)
Definition at line 78 of file intern/opennl/superlu/util.c.
References SuperMatrix::Store, and SUPERLU_FREE.
void Destroy_Dense_Matrix (SuperMatrix * A)
Definition at line 109 of file intern/opennl/superlu/util.c.
References DNformat::nzval, SuperMatrix::Store, and SUPERLU_FREE.
void Destroy_SuperMatrix_Store (SuperMatrix * A)
Definition at line 63 of file intern/opennl/superlu/util.c.
References SuperMatrix::Store, and SUPERLU_FREE.
Referenced by __nlFactorize_SUPERLU(), __nlInvert_SUPERLU(), and sgssv().
void Destroy_SuperNode_Matrix (SuperMatrix * A)
Definition at line 87 of file intern/opennl/superlu/util.c.
References SuperMatrix::Store, and SUPERLU_FREE.
Referenced by __nlFree_SUPERLU().
void fixupL (const int n, const int * perm_r, GlobalLU_t * Glu)
Definition at line 178 of file intern/opennl/superlu/util.c.
References i, GlobalLU_t::lsub, GlobalLU_t::supno, GlobalLU_t::xlsub, and GlobalLU_t::xsup.
Referenced by sgstrf().
void ifill (int * a, int alen, int ival)
Definition at line 298 of file intern/opennl/superlu/util.c.
References i.
Referenced by heap_relax_snode(), relax_snode(), SetIWork(), sgstrf(), and super_stats().
flops_t LUFactFlops (SuperLUStat_t * stat)
Definition at line 280 of file intern/opennl/superlu/util.c.
References FACT, and SuperLUStat_t::ops.
flops_t LUSolveFlops (SuperLUStat_t * stat)
Definition at line 286 of file intern/opennl/superlu/util.c.
References SuperLUStat_t::ops, and SOLVE.
int print_int_vec (char * what, int n, int * vec)
Definition at line 394 of file intern/opennl/superlu/util.c.
References i.
Referenced by sp_preorder().
void print_panel_seg (int n, int w, int jcol, int nseg, int * segrep, int * repfnz)
Definition at line 214 of file intern/opennl/superlu/util.c.
void PrintSumm (char * type, int nfail, int nrun, int nerrs)
Definition at line 381 of file intern/opennl/superlu/util.c.
void resetrep_col (const int nseg, const int * segrep, int * repfnz)
Definition at line 120 of file intern/opennl/superlu/util.c.
References EMPTY, and i.
Referenced by sgstrf().
void set_default_options (superlu_options_t * options)
Definition at line 47 of file intern/opennl/superlu/util.c.
References COLAMD, superlu_options_t::ColPerm, superlu_options_t::ConditionNumber, superlu_options_t::DiagPivotThresh, DOFACT, superlu_options_t::Equil, superlu_options_t::Fact, superlu_options_t::IterRefine, NO, NOREFINE, NOTRANS, superlu_options_t::PivotGrowth, superlu_options_t::PrintStat, superlu_options_t::SymmetricMode, superlu_options_t::Trans, and YES.
Referenced by __nlFactorize_SUPERLU().
float SpaSize (int n, int np, float sum_npw)
Definition at line 350 of file intern/opennl/superlu/util.c.
void StatFree (SuperLUStat_t * stat)
Definition at line 271 of file intern/opennl/superlu/util.c.
References SuperLUStat_t::ops, SuperLUStat_t::panel_histo, SUPERLU_FREE, and SuperLUStat_t::utime.
Referenced by __nlFree_SUPERLU().
void StatInit (SuperLUStat_t * stat)
Definition at line 230 of file intern/opennl/superlu/util.c.
References ABORT, i, intCalloc(), NPHASES, SuperLUStat_t::ops, SuperLUStat_t::panel_histo, sp_ienv(), SUPERLU_MALLOC, SUPERLU_MAX, and SuperLUStat_t::utime.
Referenced by __nlFactorize_SUPERLU().
void StatPrint (SuperLUStat_t * stat)
Definition at line 250 of file intern/opennl/superlu/util.c.
References FACT, SuperLUStat_t::ops, SOLVE, and SuperLUStat_t::utime.
void super_stats (int nsuper, int * xsup)
Definition at line 312 of file intern/opennl/superlu/util.c.
References i, ifill(), max_sup_size, and NBUCKS.
void superlu_abort_and_exit (char * msg)
Definition at line 38 of file intern/opennl/superlu/util.c.
Variable Documentation
int max_sup_size [static]
Definition at line 310 of file intern/opennl/superlu/util.c.
Referenced by super_stats().