Blender: sgssv.c File Reference
sgssv.c File Reference
opennl
#include "ssp_defs.h"
Functions
void sgssv (superlu_options_t *options, SuperMatrix *A, int *perm_c, int *perm_r, SuperMatrix *L, SuperMatrix *U, SuperMatrix *B, SuperLUStat_t *stat, int *info)
Detailed Description
Definition in file sgssv.c.
Function Documentation
void sgssv (superlu_options_t * options, SuperMatrix * A, int * perm_c, int * perm_r, SuperMatrix * L, SuperMatrix * U, SuperMatrix * B, SuperLUStat_t * stat, int * info)
Definition at line 16 of file sgssv.c.
References NRformat::colind, superlu_options_t::ColPerm, COLPERM, Destroy_CompCol_Permuted(), Destroy_SuperMatrix_Store(), DOFACT, SuperMatrix::Dtype, ETREE, FACT, superlu_options_t::Fact, get_perm_c(), i, intMalloc(), DNformat::lda, SuperMatrix::Mtype, MY_PERMC, SuperMatrix::ncol, NRformat::nnz, NOTRANS, SuperMatrix::nrow, NULL, NRformat::nzval, NRformat::rowptr, sCreate_CompCol_Matrix(), sgstrf(), sgstrs(), SLU_DN, SLU_GE, SLU_NC, SLU_NR, SLU_S, SOLVE, sp_ienv(), sp_preorder(), SuperMatrix::Store, SuperMatrix::Stype, SUPERLU_FREE, SUPERLU_MALLOC, SUPERLU_MAX, SuperLU_timer_(), TRANS, SuperLUStat_t::utime, and xerbla_().