Blender: node_shader_mixRgb.c File Reference
node_shader_mixRgb.c File Reference
shdnodes
#include "node_shader_util.h"
Functions
static void node_shader_exec_mix_rgb (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static int gpu_shader_mix_rgb (GPUMaterial *mat, bNode *node, GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_mix_rgb (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_mix_rgb_in []
static bNodeSocketTemplate sh_node_mix_rgb_out []
Detailed Description
Definition in file node_shader_mixRgb.c.
Function Documentation
static int gpu_shader_mix_rgb (GPUMaterial * mat, bNode * node, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 65 of file node_shader_mixRgb.c.
References bNode::custom1, GPU_stack_link(), and names.
Referenced by register_node_type_sh_mix_rgb().
static void node_shader_exec_mix_rgb (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 47 of file node_shader_mixRgb.c.
References CLAMP(), copy_v3_v3(), bNode::custom1, nodestack_get_vec(), ramp_blend(), SOCK_FLOAT, and SOCK_VECTOR.
Referenced by register_node_type_sh_mix_rgb().
void register_node_type_sh_mix_rgb (bNodeTreeType * ttype)
Definition at line 76 of file node_shader_mixRgb.c.
References gpu_shader_mix_rgb(), node_blend_label(), NODE_CLASS_OP_COLOR, NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_mix_rgb(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_label(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_MIX_RGB.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_mix_rgb_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Fac",           0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_FACTOR},
    {   SOCK_RGBA, 1, "Color1",         0.5f, 0.5f, 0.5f, 1.0f},
    {   SOCK_RGBA, 1, "Color2",         0.5f, 0.5f, 0.5f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_shader_mixRgb.c.
bNodeSocketTemplate sh_node_mix_rgb_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Color"},
    {   -1, 0, ""   }
}
Definition at line 42 of file node_shader_mixRgb.c.