Blender: BKE_icons.h File Reference
BKE_icons.h File Reference
blenkernel
Classes
struct Icon
Typedefs
typedef void(* DrawInfoFreeFP)(void *drawinfo)
typedef struct Icon Icon
Functions
void BKE_icons_init (int first_dyn_id)
int BKE_icon_getid (struct ID *id)
struct Icon * BKE_icon_get (int icon_id)
void BKE_icon_set (int icon_id, struct Icon *icon)
void BKE_icon_delete (struct ID *id)
void BKE_icon_changed (int icon_id)
void BKE_icons_free (void)
void BKE_previewimg_freefunc (void *link)
void BKE_previewimg_free (struct PreviewImage **prv)
void BKE_previewimg_free_id (struct ID *id)
struct PreviewImage * BKE_previewimg_create (void)
struct PreviewImage * BKE_previewimg_copy (struct PreviewImage *prv)
struct PreviewImage * BKE_previewimg_get (struct ID *id)
Detailed Description
Definition in file BKE_icons.h.
Typedef Documentation
typedef void(* DrawInfoFreeFP)(void *drawinfo)
Definition at line 39 of file BKE_icons.h.
typedef struct Icon Icon
Definition at line 49 of file BKE_icons.h.
Function Documentation
void BKE_icon_changed (int icon_id)
Definition at line 241 of file icons.c.
References BKE_previewimg_get(), BLI_ghash_lookup(), PreviewImage::changed, PreviewImage::changed_timestamp, G, i, NULL, NUM_ICON_SIZES, Icon::obj, and SET_INT_IN_POINTER.
Referenced by get_brush_icon(), image_changed(), image_initialize_after_load(), lamp_changed(), material_changed(), texture_changed(), and world_changed().
void BKE_icon_delete (struct ID * id)
Definition at line 322 of file icons.c.
References BLI_ghash_remove(), icon_free(), ID::icon_id, NULL, and SET_INT_IN_POINTER.
Referenced by free_image(), free_lamp(), free_material(), free_texture(), and free_world().
struct Icon* BKE_icon_get (int icon_id) [read]
Definition at line 294 of file icons.c.
References BLI_ghash_lookup(), NULL, and SET_INT_IN_POINTER.
Referenced by icon_draw_size(), UI_icon_get_height(), and UI_icon_get_width().
int BKE_icon_getid (struct ID * id)
Definition at line 263 of file icons.c.
References BLI_ghash_insert(), Icon::drawinfo, Icon::drawinfo_free, G, get_next_free_id(), GS, ID::icon_id, MEM_callocN(), ID::name, NULL, Icon::obj, SET_INT_IN_POINTER, and Icon::type.
Referenced by get_brush_icon(), IDnames_to_dyn_pupstring(), image_changed(), image_initialize_after_load(), lamp_changed(), material_changed(), texture_changed(), ui_id_brush_get_icon(), ui_id_icon_get(), and world_changed().
void BKE_icon_set (int icon_id, struct Icon * icon)
Definition at line 308 of file icons.c.
References BLI_ghash_insert(), BLI_ghash_lookup(), NULL, and SET_INT_IN_POINTER.
Referenced by def_internal_icon(), and def_internal_vicon().
void BKE_icons_free (void)
Definition at line 111 of file icons.c.
References BLI_ghash_free(), icon_free(), and NULL.
Referenced by main(), and UI_icons_free().
void BKE_icons_init (int first_dyn_id)
Definition at line 102 of file icons.c.
References BLI_ghash_new(), BLI_ghashutil_intcmp(), BLI_ghashutil_inthash(), gFirstIconId, and gNextIconId.
Referenced by main(), and UI_icons_init().
struct PreviewImage* BKE_previewimg_copy (struct PreviewImage * prv) [read]
Definition at line 156 of file icons.c.
References i, MEM_dupallocN(), NULL, NUM_ICON_SIZES, and PreviewImage::rect.
Referenced by copy_lamp(), copy_material(), copy_texture(), and copy_world().
struct PreviewImage* BKE_previewimg_create (void) [read]
Definition at line 118 of file icons.c.
References PreviewImage::changed, PreviewImage::changed_timestamp, i, MEM_callocN(), NULL, and NUM_ICON_SIZES.
Referenced by BKE_previewimg_get().
void BKE_previewimg_free (struct PreviewImage ** prv)
Definition at line 148 of file icons.c.
References BKE_previewimg_freefunc(), and NULL.
Referenced by BKE_previewimg_free_id(), free_brush(), free_image(), free_lamp(), free_material(), free_texture(), and free_world().
void BKE_previewimg_free_id (struct ID * id)
Definition at line 175 of file icons.c.
References BKE_previewimg_free(), GS, ID_BR, ID_IM, ID_LA, ID_MA, ID_TE, ID_WO, ID::name, Brush::preview, Image::preview, Lamp::preview, World::preview, Tex::preview, and Material::preview.
void BKE_previewimg_freefunc (void * link)
Definition at line 132 of file icons.c.
References i, MEM_freeN(), NULL, NUM_ICON_SIZES, and PreviewImage::rect.
Referenced by BKE_previewimg_free(), and filelist_from_library().
struct PreviewImage* BKE_previewimg_get (struct ID * id) [read]
Definition at line 203 of file icons.c.
References BKE_previewimg_create(), GS, ID_BR, ID_IM, ID_LA, ID_MA, ID_TE, ID_WO, ID::name, NULL, Brush::preview, Image::preview, Lamp::preview, World::preview, Tex::preview, and Material::preview.
Referenced by BKE_icon_changed(), icon_draw_size(), ui_id_brush_render(), and ui_id_icon_render().