Blender: blender_util.h File Reference
blender_util.h File Reference
#include "util_map.h"
#include "util_path.h"
#include "util_set.h"
#include "util_transform.h"
#include "util_types.h"
#include "util_vector.h"
Classes
class id_map< K, T >
struct ObjectKey
Functions
ID * rna_Object_to_mesh (void *_self, void *reports, void *scene, int apply_modifiers, int settings)
void rna_Main_meshes_remove (void *bmain, void *reports, void *mesh)
void rna_Object_create_duplilist (void *ob, void *reports, void *sce)
void rna_Object_free_duplilist (void *ob, void *reports)
void rna_RenderLayer_rect_set (PointerRNA *ptr, const float *values)
void rna_RenderPass_rect_set (PointerRNA *ptr, const float *values)
struct RenderResult * RE_engine_begin_result (struct RenderEngine *engine, int x, int y, int w, int h)
void RE_engine_update_result (struct RenderEngine *engine, struct RenderResult *result)
void RE_engine_end_result (struct RenderEngine *engine, struct RenderResult *result)
int RE_engine_test_break (struct RenderEngine *engine)
void RE_engine_update_stats (struct RenderEngine *engine, const char *stats, const char *info)
void RE_engine_update_progress (struct RenderEngine *engine, float progress)
void engine_tag_redraw (void *engine)
void engine_tag_update (void *engine)
int rna_Object_is_modified (void *ob, void *scene, int settings)
void BLI_timestr (double _time, char *str)
void rna_ColorRamp_eval (void *coba, float position, float color[4])
static CCL_NAMESPACE_BEGIN BL::Mesh object_to_mesh (BL::Object self, BL::Scene scene, bool apply_modifiers, bool render)
static void colorramp_to_array (BL::ColorRamp ramp, float4 *data, int size)
static void object_remove_mesh (BL::BlendData data, BL::Mesh mesh)
static void object_create_duplilist (BL::Object self, BL::Scene scene)
static void object_free_duplilist (BL::Object self)
static bool object_is_modified (BL::Object self, BL::Scene scene, bool preview)
static Transform get_transform (BL::Array< float, 16 > array)
static float2 get_float2 (BL::Array< float, 2 > array)
static float3 get_float3 (BL::Array< float, 2 > array)
static float3 get_float3 (BL::Array< float, 3 > array)
static float3 get_float3 (BL::Array< float, 4 > array)
static int4 get_int4 (BL::Array< int, 4 > array)
static uint get_layer (BL::Array< int, 20 > array)
static bool get_boolean (PointerRNA &ptr, const char *name)
static float get_float (PointerRNA &ptr, const char *name)
static int get_int (PointerRNA &ptr, const char *name)
static int get_enum (PointerRNA &ptr, const char *name)
static string get_enum_identifier (PointerRNA &ptr, const char *name)
static string blender_absolute_path (BL::BlendData b_data, BL::ID b_id, const string &path)
Function Documentation
static string blender_absolute_path (BL::BlendData b_data, BL::ID b_id, const string & path) [inline, static]
Definition at line 187 of file blender_util.h.
References dirname(), path_dirname(), and path_join().
Referenced by add_node().
void BLI_timestr (double _time, char * str)
Definition at line 385 of file string.c.
References min.
static void colorramp_to_array (BL::ColorRamp ramp, float4 * data, int size) [inline, static]
Definition at line 67 of file blender_util.h.
References i, make_float4(), rna_ColorRamp_eval(), and size().
Referenced by add_node().
void engine_tag_redraw (void * engine)
Referenced by BlenderSession::tag_redraw().
void engine_tag_update (void * engine)
Referenced by BlenderSession::tag_update().
static bool get_boolean (PointerRNA & ptr, const char * name) [inline, static]
Definition at line 154 of file blender_util.h.
References RNA_boolean_get().
Referenced by BlenderSync::get_session_pause(), and object_ray_visibility().
static int get_enum (PointerRNA & ptr, const char * name) [inline, static]
Definition at line 169 of file blender_util.h.
References RNA_enum_get().
static string get_enum_identifier (PointerRNA & ptr, const char * name) [inline, static]
Definition at line 174 of file blender_util.h.
References NULL, RNA_property_enum_get(), RNA_property_enum_identifier(), and RNA_struct_find_property().
static float get_float (PointerRNA & ptr, const char * name) [inline, static]
Definition at line 159 of file blender_util.h.
References RNA_float_get().
Referenced by BlenderSync::get_session_params().
static float2 get_float2 (BL::Array< float, 2 > array) [inline, static]
Definition at line 111 of file blender_util.h.
References make_float2().
Referenced by BlenderSync::sync_view().
static float3 get_float3 (BL::Array< float, 2 > array) [inline, static]
Definition at line 116 of file blender_util.h.
References make_float3().
Referenced by add_node(), create_mesh(), create_subd_mesh(), get_node_output_rgba(), get_tex_mapping(), and set_default_value().
static float3 get_float3 (BL::Array< float, 3 > array) [inline, static]
Definition at line 121 of file blender_util.h.
References make_float3().
static float3 get_float3 (BL::Array< float, 4 > array) [inline, static]
Definition at line 126 of file blender_util.h.
References make_float3().
static int get_int (PointerRNA & ptr, const char * name) [inline, static]
Definition at line 164 of file blender_util.h.
References RNA_int_get().
Referenced by BlenderSync::get_session_params().
static int4 get_int4 (BL::Array< int, 4 > array) [inline, static]
Definition at line 131 of file blender_util.h.
References make_int4().
Referenced by create_mesh(), and create_subd_mesh().
static uint get_layer (BL::Array< int, 20 > array) [inline, static]
Definition at line 136 of file blender_util.h.
References i.
static Transform get_transform (BL::Array< float, 16 > array) [inline, static]
Definition at line 99 of file blender_util.h.
References transform_transpose().
Referenced by blender_camera_focal_distance(), BlenderSync::sync_camera(), and BlenderSync::sync_view().
static void object_create_duplilist (BL::Object self, BL::Scene scene) [inline, static]
Definition at line 82 of file blender_util.h.
References NULL, and rna_Object_create_duplilist().
static void object_free_duplilist (BL::Object self) [inline, static]
Definition at line 87 of file blender_util.h.
References NULL, and rna_Object_free_duplilist().
static bool object_is_modified (BL::Object self, BL::Scene scene, bool preview) [inline, static]
Definition at line 92 of file blender_util.h.
References rna_Object_is_modified().
static void object_remove_mesh (BL::BlendData data, BL::Mesh mesh) [inline, static]
Definition at line 77 of file blender_util.h.
References NULL, and rna_Main_meshes_remove().
static CCL_NAMESPACE_BEGIN BL::Mesh object_to_mesh (BL::Object self, BL::Scene scene, bool apply_modifiers, bool render) [inline, static]
Definition at line 59 of file blender_util.h.
References data, NULL, RNA_id_pointer_create(), and rna_Object_to_mesh().
struct RenderResult* RE_engine_begin_result (struct RenderEngine * engine, int x, int y, int w, int h) [read]
Definition at line 151 of file external_engine.c.
References BLI_addtail(), CLAMP(), Render::disprect, RenderEngine::fullresult, RenderEngine::re, RenderResult::rectx, RenderResult::recty, render_result_new(), Render::result, RR_USE_MEM, RenderResult::tilerect, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
void RE_engine_end_result (struct RenderEngine * engine, struct RenderResult * result)
Definition at line 195 of file external_engine.c.
References Render::ddh, Render::display_draw, ListBase::first, RenderEngine::fullresult, RenderResult::layers, NULL, Render::r, R_PREVIEWBUTS, RenderEngine::re, render_result_free_list(), render_result_merge(), RenderResult::renlay, Render::result, RenderData::scemode, Render::tbh, and Render::test_break.
int RE_engine_test_break (struct RenderEngine * engine)
Definition at line 218 of file external_engine.c.
References RenderEngine::re, Render::tbh, and Render::test_break.
void RE_engine_update_progress (struct RenderEngine * engine, float progress)
Definition at line 257 of file external_engine.c.
References CLAMP(), Render::prh, Render::progress, and RenderEngine::re.
void RE_engine_update_result (struct RenderEngine * engine, struct RenderResult * result)
Definition at line 185 of file external_engine.c.
References Render::ddh, Render::display_draw, ListBase::first, RenderResult::layers, NULL, RenderEngine::re, and RenderResult::renlay.
void RE_engine_update_stats (struct RenderEngine * engine, const char * stats, const char * info)
Definition at line 230 of file external_engine.c.
References BLI_sprintfN(), BLI_strdup(), Render::i, RenderStats::infostr, MEM_freeN(), NULL, RenderEngine::re, Render::sdh, Render::stats_draw, RenderStats::statstr, and RenderEngine::text.
void rna_ColorRamp_eval (void * coba, float position, float color[4])
Referenced by colorramp_to_array().
void rna_Main_meshes_remove (void * bmain, void * reports, void * mesh)
Referenced by object_remove_mesh().
void rna_Object_create_duplilist (void * ob, void * reports, void * sce)
Referenced by object_create_duplilist().
void rna_Object_free_duplilist (void * ob, void * reports)
Referenced by object_free_duplilist().
int rna_Object_is_modified (void * ob, void * scene, int settings)
Referenced by object_is_modified().
ID* rna_Object_to_mesh (void * _self, void * reports, void * scene, int apply_modifiers, int settings)
Referenced by object_to_mesh().
void rna_RenderLayer_rect_set (PointerRNA * ptr, const float * values)
Referenced by BlenderSession::write_render_result().
void rna_RenderPass_rect_set (PointerRNA * ptr, const float * values)
Referenced by BlenderSession::write_render_result().