Blender: node_common.h File Reference
node_common.h File Reference
nodes
#include "DNA_listBase.h"
Functions
struct bNodeSocket * node_group_add_extern_socket (struct bNodeTree *ntree, ListBase *lb, int in_out, struct bNodeSocket *gsock)
void node_group_init (struct bNodeTree *ntree, struct bNode *node, struct bNodeTemplate *ntemp)
void node_forloop_init (struct bNodeTree *ntree, struct bNode *node, struct bNodeTemplate *ntemp)
void node_whileloop_init (struct bNodeTree *ntree, struct bNode *node, struct bNodeTemplate *ntemp)
void node_forloop_init_tree (struct bNodeTree *ntree)
void node_whileloop_init_tree (struct bNodeTree *ntree)
const char * node_group_label (struct bNode *node)
struct bNodeTemplate node_group_template (struct bNode *node)
struct bNodeTemplate node_forloop_template (struct bNode *node)
struct bNodeTemplate node_whileloop_template (struct bNode *node)
int node_group_valid (struct bNodeTree *ntree, struct bNodeTemplate *ntemp)
void node_group_verify (struct bNodeTree *ntree, struct bNode *node, struct ID *id)
struct bNodeTree * node_group_edit_get (struct bNode *node)
struct bNodeTree * node_group_edit_set (struct bNode *node, int edit)
void node_group_edit_clear (bNode *node)
void node_loop_update_tree (struct bNodeTree *ngroup)
Detailed Description
Definition in file node_common.h.
Function Documentation
void node_forloop_init (struct bNodeTree * ntree, struct bNode * node, struct bNodeTemplate * ntemp)
Definition at line 664 of file node_common.c.
References bNodeSocket::default_value, ListBase::first, bNode::id, bNodeTree::inputs, bNode::inputs, bNodeSocket::next, bNodeTemplate::ngroup, node_group_add_extern_socket(), node_socket_set_default_value_float(), nodeAddSocket(), bNode::outputs, bNodeTree::outputs, PROP_UNSIGNED, SOCK_FLOAT, SOCK_IN, and SOCK_OUT.
void node_forloop_init_tree (struct bNodeTree * ntree)
Definition at line 685 of file node_common.c.
References bNodeSocket::flag, node_group_add_socket(), SOCK_FLOAT, SOCK_IN, and SOCK_INTERNAL.
struct bNodeTemplate node_forloop_template (struct bNode * node) [read]
Definition at line 656 of file node_common.c.
References bNode::id, bNodeTemplate::ngroup, NODE_FORLOOP, and bNodeTemplate::type.
struct bNodeSocket* node_group_add_extern_socket (struct bNodeTree * ntree, ListBase * lb, int in_out, struct bNodeSocket * gsock) [read]
void node_group_edit_clear (bNode * node)
Definition at line 631 of file node_common.c.
References ListBase::first, bNode::flag, bNode::id, if(), NODE_GROUP_EDIT, nodeGroupEditClear(), and bNodeTree::nodes.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
struct bNodeTree* node_group_edit_get (struct bNode * node) [read]
Definition at line 605 of file node_common.c.
References bNode::flag, bNode::id, NODE_GROUP_EDIT, and NULL.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
struct bNodeTree* node_group_edit_set (struct bNode * node, int edit) [read]
Definition at line 613 of file node_common.c.
References bNode::flag, bNode::id, bNodeTree::id, if(), ID::lib, NODE_GROUP_EDIT, ntreeMakeLocal(), and NULL.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
void node_group_init (struct bNodeTree * ntree, struct bNode * node, struct bNodeTemplate * ntemp)
Definition at line 522 of file node_common.c.
References ListBase::first, bNode::id, if(), bNodeTree::inputs, bNode::inputs, bNodeSocket::next, bNodeTemplate::ngroup, node_group_add_extern_socket(), bNode::outputs, bNodeTree::outputs, SOCK_IN, and SOCK_OUT.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
const char* node_group_label (struct bNode * node)
Definition at line 490 of file node_common.c.
References bNode::id, IFACE_, and ID::name.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
struct bNodeTemplate node_group_template (struct bNode * node) [read]
Definition at line 514 of file node_common.c.
References bNode::id, bNodeTemplate::ngroup, NODE_GROUP, and bNodeTemplate::type.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
int node_group_valid (struct bNodeTree * ntree, struct bNodeTemplate * ntemp)
Definition at line 495 of file node_common.c.
References ListBase::first, bNode::next, bNodeTemplate::ngroup, nodeMakeTemplate(), bNodeTree::nodes, and nodeValid().
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
void node_group_verify (struct bNodeTree * ntree, struct bNode * node, struct ID * id)
Definition at line 595 of file node_common.c.
References group_verify_socket_list(), bNode::id, bNodeTree::inputs, bNode::inputs, bNodeTemplate::ngroup, bNode::outputs, bNodeTree::outputs, SOCK_IN, and SOCK_OUT.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
void node_loop_update_tree (struct bNodeTree * ngroup)
Definition at line 762 of file node_common.c.
References loop_sync(), NTREE_UPDATE_GROUP_IN, NTREE_UPDATE_GROUP_OUT, SOCK_IN, SOCK_OUT, and bNodeTree::update.
void node_whileloop_init (struct bNodeTree * ntree, struct bNode * node, struct bNodeTemplate * ntemp)
Definition at line 771 of file node_common.c.
References bNode::custom1, bNodeSocket::default_value, ListBase::first, bNode::id, bNodeTree::inputs, bNode::inputs, bNodeSocket::next, bNodeTemplate::ngroup, node_group_add_extern_socket(), node_socket_set_default_value_float(), nodeAddSocket(), bNode::outputs, bNodeTree::outputs, PROP_NONE, SOCK_FLOAT, SOCK_IN, and SOCK_OUT.
void node_whileloop_init_tree (struct bNodeTree * ntree)
Definition at line 795 of file node_common.c.
References bNodeSocket::flag, node_group_add_socket(), SOCK_FLOAT, SOCK_INTERNAL, and SOCK_OUT.
struct bNodeTemplate node_whileloop_template (struct bNode * node) [read]
Definition at line 802 of file node_common.c.
References bNode::id, bNodeTemplate::ngroup, NODE_WHILELOOP, and bNodeTemplate::type.