Blender: btClock Class Reference
btClock Class Reference
The btClock is a portable basic clock that measures accurate time in seconds, use for profiling.
#include <btQuickprof.h>
Public Member Functions
btClock ()
The btClock is a portable basic clock that measures accurate time in seconds, use for profiling.
btClock (const btClock &other)
btClock & operator= (const btClock &other)
~btClock ()
void reset ()
Resets the initial reference time.
unsigned long int getTimeMilliseconds ()
unsigned long int getTimeMicroseconds ()
Detailed Description
The btClock is a portable basic clock that measures accurate time in seconds, use for profiling.
Definition at line 35 of file btQuickprof.h.
Constructor & Destructor Documentation
btClock::btClock ()
The btClock is a portable basic clock that measures accurate time in seconds, use for profiling.
Definition at line 76 of file btQuickprof.cpp.
References reset().
btClock::btClock (const btClock & other)
Definition at line 90 of file btQuickprof.cpp.
btClock::~btClock ()
Definition at line 85 of file btQuickprof.cpp.
Member Function Documentation
unsigned long int btClock::getTimeMicroseconds ()
Returns the time in us since the last call to reset or since the Clock was created.
Definition at line 182 of file btQuickprof.cpp.
References btClockData::mStartTime, and mymin.
Referenced by Profile_Get_Ticks().
unsigned long int btClock::getTimeMilliseconds ()
Returns the time in ms since the last call to reset or since the btClock was created.
Definition at line 126 of file btQuickprof.cpp.
References btClockData::mStartTime, and mymin.
btClock & btClock::operator= (const btClock & other)
Definition at line 96 of file btQuickprof.cpp.
void btClock::reset ()
Resets the initial reference time.
Definition at line 104 of file btQuickprof.cpp.
References btClockData::mStartTime.
Referenced by btClock(), and CProfileManager::Reset().
The documentation for this class was generated from the following files:
btQuickprof.h
btQuickprof.cpp