Blender: gpencil_undo.c File Reference
gpencil_undo.c File Reference
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_gpencil_types.h"
#include "DNA_listBase.h"
#include "DNA_windowmanager_types.h"
#include "BKE_context.h"
#include "BKE_gpencil.h"
#include "BLI_listbase.h"
#include "ED_gpencil.h"
#include "WM_api.h"
#include "WM_types.h"
#include "gpencil_intern.h"
Classes
struct bGPundonode
Defines
#define MAXUNDONAME 64
Typedefs
typedef struct bGPundonode bGPundonode
Functions
int ED_gpencil_session_active (void)
int ED_undo_gpencil_step (bContext *C, int step, const char *name)
void gpencil_undo_init (bGPdata *gpd)
void gpencil_undo_push (bGPdata *gpd)
void gpencil_undo_finish (void)
Variables
static ListBase undo_nodes = {NULL, NULL}
static bGPundonode * cur_node = NULL
Define Documentation
#define MAXUNDONAME 64
Definition at line 49 of file gpencil_undo.c.
Typedef Documentation
typedef struct bGPundonode bGPundonode
Function Documentation
int ED_gpencil_session_active (void)
Definition at line 61 of file gpencil_undo.c.
References ListBase::first, and NULL.
Referenced by ed_undo_step(), gp_draw_data(), gp_session_initdata(), and gpencil_draw_poll().
int ED_undo_gpencil_step (bContext * C, int step, const char * name)
Definition at line 66 of file gpencil_undo.c.
References BLI_addtail(), ListBase::first, free_gpencil_layers(), bGPundonode::gpd, gpencil_data_get_pointers(), gpencil_layer_duplicate(), ListBase::last, bGPdata::layers, NA_EDITED, bGPundonode::name, NC_SCREEN, ND_GPENCIL, bGPDlayer::next, bGPundonode::next, NULL, OPERATOR_FINISHED, bGPundonode::prev, and WM_event_add_notifier().
Referenced by ed_undo_step().
void gpencil_undo_finish (void)
Definition at line 152 of file gpencil_undo.c.
References BLI_freelistN(), ListBase::first, free_gpencil_data(), bGPundonode::gpd, MEM_freeN(), bGPundonode::next, and NULL.
Referenced by gpencil_draw_exit().
void gpencil_undo_init (bGPdata * gpd)
Definition at line 116 of file gpencil_undo.c.
References gpencil_undo_push().
Referenced by gp_session_initdata().
void gpencil_undo_push (bGPdata * gpd)
Definition at line 121 of file gpencil_undo.c.
References BLI_addtail(), BLI_freelinkN(), free_gpencil_data(), bGPundonode::gpd, gpencil_data_duplicate(), MEM_callocN(), MEM_freeN(), and bGPundonode::next.
Referenced by gpencil_stroke_end(), and gpencil_undo_init().
Variable Documentation
bGPundonode* cur_node = NULL [static]
Definition at line 59 of file gpencil_undo.c.
ListBase undo_nodes = {NULL, NULL} [static]
Definition at line 58 of file gpencil_undo.c.