Blender: node_composite_normalize.c File Reference
node_composite_normalize.c File Reference
cmpnodes
#include "node_composite_util.h"
Defines
#define BLENDER_ZMAX 10000.0f
Functions
static void do_normalize (bNode *UNUSED(node), float *out, float *src, float *min, float *mult)
static void node_composit_exec_normalize (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_normalize (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_normalize_in []
static bNodeSocketTemplate cmp_node_normalize_out []
Detailed Description
Definition in file node_composite_normalize.c.
Define Documentation
#define BLENDER_ZMAX 10000.0f
Definition at line 62 of file node_composite_normalize.c.
Referenced by node_composit_exec_normalize().
Function Documentation
static void do_normalize (bNode * UNUSEDnode, float * out, float * src, float * min, float * mult) [static]
Definition at line 46 of file node_composite_normalize.c.
Referenced by node_composit_exec_normalize().
static void node_composit_exec_normalize (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 64 of file node_composite_normalize.c.
References alloc_compbuf(), BLENDER_ZMAX, CB_VAL, composit3_pixel_processor(), copy_v4_v4(), bNodeStack::data, data, do_normalize(), max, min, NULL, CompBuf::rect, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_normalize().
void register_node_type_cmp_normalize (bNodeTreeType * ttype)
Definition at line 105 of file node_composite_normalize.c.
References CMP_NODE_NORMALIZE, NODE_CLASS_OP_VECTOR, node_composit_exec_normalize(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_normalize_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Value",         1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_composite_normalize.c.
bNodeSocketTemplate cmp_node_normalize_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "Value"},
    {   -1, 0, ""   }
}
Definition at line 41 of file node_composite_normalize.c.