Blender: bmesh_structure.c File Reference
bmesh_structure.c File Reference
BMesh
#include "BLI_utildefines.h"
#include "bmesh.h"
#include "intern/bmesh_private.h"
Functions
int bmesh_vert_in_edge (BMEdge *e, BMVert *v)
int bmesh_verts_in_edge (BMVert *v1, BMVert *v2, BMEdge *e)
BMVert * bmesh_edge_other_vert_get (BMEdge *e, BMVert *v)
int bmesh_edge_swapverts (BMEdge *e, BMVert *orig, BMVert *newv)
int bmesh_disk_edge_append (BMEdge *e, BMVert *v)
void bmesh_disk_edge_remove (BMEdge *e, BMVert *v)
BMEdge * bmesh_disk_edge_next (BMEdge *e, BMVert *v)
Next Disk Edge.
BMEdge * bmesh_disk_edge_prev (BMEdge *e, BMVert *v)
BMEdge * bmesh_disk_edge_exists (BMVert *v1, BMVert *v2)
int bmesh_disk_count (BMVert *v)
int bmesh_disk_validate (int len, BMEdge *e, BMVert *v)
int bmesh_disk_facevert_count (BMVert *v)
DISK COUNT FACE VERT.
BMEdge * bmesh_disk_faceedge_find_first (BMEdge *e, BMVert *v)
FIND FIRST FACE EDGE.
BMEdge * bmesh_disk_faceedge_find_next (BMEdge *e, BMVert *v)
int bmesh_radial_validate (int radlen, BMLoop *l)
void bmesh_radial_loop_remove (BMLoop *l, BMEdge *e)
BMESH RADIAL REMOVE LOOP.
BMLoop * bmesh_radial_faceloop_find_first (BMLoop *l, BMVert *v)
BME RADIAL FIND FIRST FACE VERT.
BMLoop * bmesh_radial_faceloop_find_next (BMLoop *l, BMVert *v)
int bmesh_radial_length (BMLoop *l)
void bmesh_radial_append (BMEdge *e, BMLoop *l)
int bmesh_radial_face_find (BMEdge *e, BMFace *f)
int bmesh_radial_facevert_count (BMLoop *l, BMVert *v)
RADIAL COUNT FACE VERT.
int bmesh_loop_validate (BMFace *f)
Detailed Description
Low level routines for manipulating the BM structure.
Definition in file bmesh_structure.c.
Function Documentation
int bmesh_disk_count (BMVert * v)
Definition at line 245 of file bmesh_structure.c.
References bmesh_disk_edge_next(), and BMVert::e.
Referenced by BM_vert_collapse_faces(), BM_vert_edge_count(), bmesh_disk_validate(), bmesh_elem_check(), bmesh_jekv(), bmesh_semv(), bmesh_urmv_loop(), and BMO_vert_edge_flags_count().
int bmesh_disk_edge_append (BMEdge * e, BMVert * v)
BMesh Cycles
(this is somewhat outdate, though bits of its API are still used) - joeedh
Cycles are circular doubly linked lists that form the basis of adjacency information in the BME modeler. Full adjacency relations can be derived from examining these cycles very quickly. Although each cycle is a double circular linked list, each one is considered to have a 'base' or 'head', and care must be taken by Euler code when modifying the contents of a cycle.
The contents of this file are split into two parts. First there are the bmesh_cycle family of functions which are generic circular double linked list procedures. The second part contains higher level procedures for supporting modification of specific cycle types.
The three cycles explicitly stored in the BM data structure are as follows:
1: The Disk Cycle - A circle of edges around a vertex Base: vertex->edge pointer.
This cycle is the most complicated in terms of its structure. Each bmesh_Edge contains two bmesh_CycleNode structures to keep track of that edges membership in the disk cycle of each of its vertices. However for any given vertex it may be the first in some edges in its disk cycle and the second for others. The bmesh_disk_XXX family of functions contain some nice utilities for navigating disk cycles in a way that hides this detail from the tool writer.
Note that the disk cycle is completely independent from face data. One advantage of this is that wire edges are fully integrated into the topology database. Another is that the the disk cycle has no problems dealing with non-manifold conditions involving faces.
Functions relating to this cycle:
bmesh_disk_edge_append
bmesh_disk_edge_remove
bmesh_disk_edge_next
bmesh_disk_edge_prev
bmesh_disk_facevert_count
bmesh_disk_faceedge_find_first
bmesh_disk_faceedge_find_next
2: The Radial Cycle - A circle of face edges (bmesh_Loop) around an edge Base: edge->l->radial structure.
The radial cycle is similar to the radial cycle in the radial edge data structure.* Unlike the radial edge however, the radial cycle does not require a large amount of memory to store non-manifold conditions since BM does not keep track of region/shell information.
Functions relating to this cycle:
bmesh_radial_append
bmesh_radial_loop_remove
bmesh_radial_face_find
bmesh_radial_facevert_count
bmesh_radial_faceloop_find_first
bmesh_radial_faceloop_find_next
bmesh_radial_validate
3: The Loop Cycle - A circle of face edges around a polygon. Base: polygon->lbase.
The loop cycle keeps track of a faces vertices and edges. It should be noted that the direction of a loop cycle is either CW or CCW depending on the face normal, and is not oriented to the faces editedges.
Functions relating to this cycle:
bmesh_cycle_XXX family of functions.
Note:
the order of elements in all cycles except the loop cycle is undefined. This leads to slightly increased seek time for deriving some adjacency relations, however the advantage is that no intrinsic properties of the data structures are dependent upon the cycle order and all non-manifold conditions are represented trivially.
Definition at line 156 of file bmesh_structure.c.
References BM_DISK_EDGE_LINK_GET, BMVert::e, BMDiskLink::next, NULL, BMDiskLink::prev, and TRUE.
Referenced by BM_edge_create(), BM_vert_splice(), bmesh_jekv(), bmesh_semv(), and bmesh_vert_separate().
BMEdge* bmesh_disk_edge_exists (BMVert * v1, BMVert * v2)
Definition at line 228 of file bmesh_structure.c.
References bmesh_disk_edge_next(), bmesh_verts_in_edge(), BMVert::e, and NULL.
BMEdge* bmesh_disk_edge_next (BMEdge * e, BMVert * v)
Next Disk Edge.
Find the next edge in a disk cycle
Returns:
Pointer to the next edge in the disk cycle for the vertex v.
Definition at line 210 of file bmesh_structure.c.
References BMDiskLink::next, NULL, BMEdge::v1, BMEdge::v1_disk_link, BMEdge::v2, and BMEdge::v2_disk_link.
Referenced by BM_disk_dissolve(), BM_face_create_ngon(), BM_vert_calc_edge_angle(), BM_vert_collapse_edge(), BM_vert_collapse_faces(), BM_vert_face_count(), BM_vert_is_manifold(), BM_vert_is_wire(), BM_vert_kill(), BME_Bevel_Dissolve_Disk(), BME_bevel_mesh(), BME_bevel_split_edge(), bmesh_disk_count(), bmesh_disk_edge_exists(), bmesh_disk_faceedge_find_first(), bmesh_disk_faceedge_find_next(), bmesh_disk_facevert_count(), bmesh_disk_validate(), bmesh_jekv(), bmesh_urmv_loop(), bmiter__edge_of_vert_step(), BMO_vert_edge_flags_count(), count_flagged_disk(), and disk_is_flagged().
BMEdge* bmesh_disk_edge_prev (BMEdge * e, BMVert * v)
Definition at line 219 of file bmesh_structure.c.
References NULL, BMDiskLink::prev, BMEdge::v1, BMEdge::v1_disk_link, BMEdge::v2, and BMEdge::v2_disk_link.
Referenced by bmesh_disk_validate().
void bmesh_disk_edge_remove (BMEdge * e, BMVert * v)
Definition at line 182 of file bmesh_structure.c.
References BM_DISK_EDGE_LINK_GET, BMVert::e, BMDiskLink::next, NULL, and BMDiskLink::prev.
Referenced by BM_edge_kill(), BM_vert_splice(), bmesh_jekv(), bmesh_jfke(), bmesh_semv(), and bmesh_vert_separate().
BMEdge* bmesh_disk_faceedge_find_first (BMEdge * e, BMVert * v)
FIND FIRST FACE EDGE.
Finds the first edge in a vertices Disk cycle that has one of this vert's loops attached to it.
Definition at line 327 of file bmesh_structure.c.
References bmesh_disk_edge_next(), bmesh_radial_facevert_count(), BMEdge::l, and NULL.
Referenced by bmiter__face_of_vert_begin(), and bmiter__loop_of_vert_begin().
BMEdge* bmesh_disk_faceedge_find_next (BMEdge * e, BMVert * v)
Definition at line 340 of file bmesh_structure.c.
References bmesh_disk_edge_next(), bmesh_radial_facevert_count(), BMEdge::l, and NULL.
Referenced by bmiter__face_of_vert_step(), and bmiter__loop_of_vert_step().
int bmesh_disk_facevert_count (BMVert * v)
DISK COUNT FACE VERT.
Counts the number of loop users for this vertex. Note that this is equivalent to counting the number of faces incident upon this vertex
Definition at line 298 of file bmesh_structure.c.
References bmesh_disk_edge_next(), bmesh_radial_facevert_count(), BMVert::e, and BMEdge::l.
Referenced by bmiter__face_of_vert_begin(), and bmiter__loop_of_vert_begin().
int bmesh_disk_validate (int len, BMEdge * e, BMVert * v)
Definition at line 271 of file bmesh_structure.c.
References BM_vert_in_edge(), bmesh_disk_count(), bmesh_disk_edge_next(), bmesh_disk_edge_prev(), FALSE, and TRUE.
Referenced by bmesh_jekv(), and bmesh_semv().
BMVert* bmesh_edge_other_vert_get (BMEdge * e, BMVert * v)
Definition at line 55 of file bmesh_structure.c.
References NULL, BMEdge::v1, and BMEdge::v2.
Referenced by BM_edge_other_vert(), BM_edge_split(), BM_vert_collapse_edge(), BM_vert_collapse_faces(), bmesh_jekv(), and bmesh_semv().
int bmesh_edge_swapverts (BMEdge * e, BMVert * orig, BMVert * newv)
Definition at line 66 of file bmesh_structure.c.
References FALSE, BMDiskLink::next, NULL, BMDiskLink::prev, TRUE, BMEdge::v1, BMEdge::v1_disk_link, BMEdge::v2, and BMEdge::v2_disk_link.
Referenced by BM_vert_splice(), bmesh_jekv(), bmesh_semv(), and bmesh_vert_separate().
int bmesh_loop_validate (BMFace * f)
Definition at line 536 of file bmesh_structure.c.
References BM_FACE_FIRST_LOOP, BMLoop::f, FALSE, i, len(), BMFace::len, BMLoop::next, next, NULL, BMLoop::prev, and TRUE.
Referenced by bmesh_jekv(), and bmesh_jfke().
void bmesh_radial_append (BMEdge * e, BMLoop * l)
Definition at line 478 of file bmesh_structure.c.
References BMESH_ASSERT, BMLoop::e, BMEdge::l, NULL, BMLoop::radial_next, BMLoop::radial_prev, and UNLIKELY.
Referenced by BM_edge_splice(), bm_face_boundary_add(), BM_face_create(), bm_loop_reverse_loop(), bmesh_edge_separate(), bmesh_semv(), and bmesh_sfme().
int bmesh_radial_face_find (BMEdge * e, BMFace * f)
Definition at line 502 of file bmesh_structure.c.
References bmesh_radial_length(), BMLoop::f, FALSE, i, BMEdge::l, len(), and TRUE.
Referenced by BM_edge_share_face_count(), BM_face_share_edge_count(), and bmesh_jfke().
BMLoop* bmesh_radial_faceloop_find_first (BMLoop * l, BMVert * v)
BME RADIAL FIND FIRST FACE VERT.
Finds the first loop of v around radial cycle
Definition at line 429 of file bmesh_structure.c.
References NULL, BMLoop::radial_next, and BMLoop::v.
Referenced by bmiter__face_of_vert_begin(), bmiter__face_of_vert_step(), bmiter__loop_of_vert_begin(), and bmiter__loop_of_vert_step().
BMLoop* bmesh_radial_faceloop_find_next (BMLoop * l, BMVert * v)
Definition at line 441 of file bmesh_structure.c.
References BMLoop::radial_next, and BMLoop::v.
Referenced by bmiter__face_of_vert_step(), and bmiter__loop_of_vert_step().
int bmesh_radial_facevert_count (BMLoop * l, BMVert * v)
RADIAL COUNT FACE VERT.
Returns the number of times a vertex appears in a radial cycle
Definition at line 521 of file bmesh_structure.c.
References BMLoop::radial_next, and BMLoop::v.
Referenced by bmesh_disk_faceedge_find_first(), bmesh_disk_faceedge_find_next(), and bmesh_disk_facevert_count().
int bmesh_radial_length (BMLoop * l)
Definition at line 453 of file bmesh_structure.c.
References BM_LOOP_RADIAL_MAX, BMESH_ASSERT, i, BMLoop::radial_next, and UNLIKELY.
Referenced by BM_disk_dissolve(), BM_edge_splice(), BM_vert_is_manifold(), bmesh_edge_separate(), bmesh_elem_check(), bmesh_jekv(), bmesh_radial_face_find(), bmesh_radial_validate(), bmesh_semv(), and disk_is_flagged().
void bmesh_radial_loop_remove (BMLoop * l, BMEdge * e)
BMESH RADIAL REMOVE LOOP.
Removes a loop from an radial cycle. If edge e is non-NULL it should contain the radial cycle, and it will also get updated (in the case that the edge's link into the radial cycle was the loop which is being removed from the cycle).
Definition at line 391 of file bmesh_structure.c.
References BMESH_ASSERT, BMLoop::e, BMEdge::l, NULL, BMLoop::radial_next, BMLoop::radial_prev, and UNLIKELY.
Referenced by BM_edge_splice(), BM_face_kill(), bm_loop_reverse_loop(), bmesh_edge_separate(), and bmesh_semv().
int bmesh_radial_validate (int radlen, BMLoop * l)
Definition at line 353 of file bmesh_structure.c.
References BM_LOOP_RADIAL_MAX, BMESH_ASSERT, bmesh_radial_length(), BMLoop::e, FALSE, i, BMLoop::radial_next, TRUE, UNLIKELY, BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by bmesh_elem_check(), bmesh_jekv(), and bmesh_semv().
int bmesh_vert_in_edge (BMEdge * e, BMVert * v)
MISC utility functions.
Definition at line 43 of file bmesh_structure.c.
References FALSE, TRUE, BMEdge::v1, and BMEdge::v2.
Referenced by BM_vert_in_edge(), bmesh_jekv(), and bmesh_semv().
int bmesh_verts_in_edge (BMVert * v1, BMVert * v2, BMEdge * e)
Definition at line 48 of file bmesh_structure.c.
References FALSE, TRUE, BMEdge::v1, and BMEdge::v2.
Referenced by bm_loop_reverse_loop(), BM_mesh_copy(), BM_verts_in_edge(), bmesh_disk_edge_exists(), bmesh_jekv(), and bmesh_semv().