Blender: rct.c File Reference
rct.c File Reference
blenlib
#include <stdio.h>
#include <math.h>
#include "DNA_vec_types.h"
#include "BLI_rect.h"
Functions
int BLI_rcti_is_empty (rcti *rect)
int BLI_rctf_is_empty (rctf *rect)
int BLI_in_rcti (rcti *rect, int x, int y)
int BLI_in_rctf (rctf *rect, float x, float y)
static int isect_segments (const int v1[2], const int v2[2], const int v3[2], const int v4[2])
int BLI_segment_in_rcti (rcti *rect, int s1[2], int s2[2])
void BLI_union_rctf (rctf *rct1, rctf *rct2)
void BLI_union_rcti (rcti *rct1, rcti *rct2)
void BLI_init_rctf (rctf *rect, float xmin, float xmax, float ymin, float ymax)
void BLI_init_rcti (rcti *rect, int xmin, int xmax, int ymin, int ymax)
void BLI_translate_rcti (rcti *rect, int x, int y)
void BLI_translate_rctf (rctf *rect, float x, float y)
void BLI_resize_rcti (rcti *rect, int x, int y)
void BLI_resize_rctf (rctf *rect, float x, float y)
int BLI_isect_rctf (rctf *src1, rctf *src2, rctf *dest)
int BLI_isect_rcti (rcti *src1, rcti *src2, rcti *dest)
void BLI_copy_rcti_rctf (rcti *tar, const rctf *src)
void print_rctf (const char *str, rctf *rect)
void print_rcti (const char *str, rcti *rect)
Detailed Description
A minimalist lib for functions doing stuff with rectangle structs.
Definition in file rct.c.
Function Documentation
void BLI_copy_rcti_rctf (rcti * tar, const rctf * src)
Definition at line 270 of file rct.c.
References rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, rctf::ymax, rcti::ymax, rctf::ymin, and rcti::ymin.
int BLI_in_rctf (rctf * rect, float x, float y)
Definition at line 60 of file rct.c.
References rctf::xmax, and rctf::ymax.
Referenced by blf_glyph_render(), border_select_cb(), border_select_exec(), draw_marker_areas(), draw_marker_outline(), isb_bsp_face_inside(), line_clip_rect2f(), node_find_indicated_socket(), node_mouse_groupheader(), node_resize_area_default(), node_under_mouse(), project_bucket_clip_face(), project_bucket_face_isect(), project_bucket_isect_circle(), and ui_handle_menu_event().
int BLI_in_rcti (rcti * rect, int x, int y)
Definition at line 51 of file rct.c.
References rcti::xmax, and rcti::ymax.
Referenced by actionzone_area_poll(), area_event_inside(), BLI_segment_in_rcti(), do_lasso_select_mesh__doSelectFace(), do_lasso_select_mesh__doSelectVert(), do_lattice_box_select__doSelect(), do_mesh_box_select__doSelectFace(), do_mesh_box_select__doSelectVert(), do_nurbs_box_select__doSelect(), ED_area_overdraw_flush(), ED_screen_set_subwinactive(), edge_fully_inside_rect(), file_hilight_set(), file_select_invoke(), gp_stroke_eraser_dostroke(), handler_boundbox_test(), is_in_area_actionzone(), region_event_inside(), screen_areahascursor(), ui_but_mouse_inside_icon(), ui_do_drag(), ui_mouse_inside_region(), ui_searchbox_event(), ui_searchbox_inside(), wm_event_do_handlers(), wm_event_inside_i(), wm_operator_invoke(), and wm_paintcursor_test().
void BLI_init_rctf (rctf * rect, float xmin, float xmax, float ymin, float ymax)
Definition at line 134 of file rct.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by add_scene(), curvemapping_add(), draw_marker_areas(), and draw_marker_outline().
void BLI_init_rcti (rcti * rect, int xmin, int xmax, int ymin, int ymax)
Definition at line 154 of file rct.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by area_azone_initialize(), find_file_mouse_rect(), mixed_bones_object_selectbuffer(), region_azone_edge(), region_azone_icon(), region_azone_tab(), region_azone_tab_plus(), region_azone_tria(), and region_rect_recursive().
int BLI_isect_rctf (rctf * src1, rctf * src2, rctf * dest)
Definition at line 210 of file rct.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by isb_bsp_face_inside(), node_borderselect_exec(), sequencer_borderselect_exec(), and visible_node().
int BLI_isect_rcti (rcti * src1, rcti * src2, rcti * dest)
Definition at line 240 of file rct.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by file_border_select_exec(), file_border_select_modal(), game_engine_exec(), region_scissor_winrct(), ui_draw_but_CURVE(), view3d_update_depths_rect(), wm_flush_regions_down(), and wm_flush_regions_up().
int BLI_rctf_is_empty (rctf * rect)
Definition at line 46 of file rct.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by node_draw_basis().
int BLI_rcti_is_empty (struct rcti * rect)
Determine if a rect is empty. An empty rect is one with a zero (or negative) width or height.
Returns:
True if rect is empty.
Definition at line 41 of file rct.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by sculpt_get_redraw_rect().
void BLI_resize_rctf (rctf * rect, float x, float y)
Definition at line 200 of file rct.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by sequencer_view_zoom_ratio_exec().
void BLI_resize_rcti (rcti * rect, int x, int y)
Definition at line 190 of file rct.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
int BLI_segment_in_rcti (rcti * rect, int s1[2], int s2[2])
Definition at line 83 of file rct.c.
References BLI_in_rcti(), isect_segments(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by mesh_foreachScreenEdge__mapFunc().
void BLI_translate_rctf (rctf * rect, float x, float y)
Definition at line 181 of file rct.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
void BLI_translate_rcti (rcti * rect, int x, int y)
Definition at line 174 of file rct.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by area_dupli_invoke(), and handler_boundbox_test().
void BLI_union_rctf (rctf * rct1, rctf * rct2)
Definition at line 118 of file rct.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by node_update_group(), and snode_home().
void BLI_union_rcti (rcti * rct1, rcti * rct2)
Definition at line 126 of file rct.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by sculpt_get_redraw_rect().
static int isect_segments (const int v1[2], const int v2[2], const int v3[2], const int v4[2]) [static]
Definition at line 70 of file rct.c.
References div.
Referenced by BLI_segment_in_rcti().
void print_rctf (const char * str, rctf * rect)
Definition at line 278 of file rct.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
void print_rcti (const char * str, rcti * rect)
Definition at line 284 of file rct.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.