Blender: fmodifier_ui.c File Reference
fmodifier_ui.c File Reference
animation
#include <string.h>
#include "DNA_anim_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLF_translation.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_fcurve.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "ED_anim_api.h"
#include "ED_util.h"
Defines
#define UI_FLT_MAX 10000.0f
#define B_REDR 1
#define B_FMODIFIER_REDRAW 20
#define DRAW_BACKDROP(height)
#define BINARYSEARCH_FRAMEEQ_THRESH 0.0001f
Functions
static void validate_fmodifier_cb (bContext *UNUSED(C), void *fcm_v, void *UNUSED(arg))
static void delete_fmodifier_cb (bContext *C, void *fmods_v, void *fcm_v)
static void draw_modifier__generator (uiLayout *layout, ID *id, FModifier *fcm, short width)
static void draw_modifier__fn_generator (uiLayout *layout, ID *id, FModifier *fcm, short UNUSED(width))
static void draw_modifier__cycles (uiLayout *layout, ID *id, FModifier *fcm, short UNUSED(width))
static void draw_modifier__noise (uiLayout *layout, ID *id, FModifier *fcm, short UNUSED(width))
static int binarysearch_fcm_envelopedata_index (FCM_EnvelopeData array[], float frame, int arraylen, short *exists)
static void fmod_envelope_addpoint_cb (bContext *C, void *fcm_dv, void *UNUSED(arg))
static void fmod_envelope_deletepoint_cb (bContext *UNUSED(C), void *fcm_dv, void *ind_v)
static void draw_modifier__envelope (uiLayout *layout, ID *id, FModifier *fcm, short UNUSED(width))
static void draw_modifier__limits (uiLayout *layout, ID *id, FModifier *fcm, short UNUSED(width))
static void draw_modifier__stepped (uiLayout *layout, ID *id, FModifier *fcm, short UNUSED(width))
void ANIM_uiTemplate_fmodifier_draw (uiLayout *layout, ID *id, ListBase *modifiers, FModifier *fcm)
void free_fmodifiers_copybuf (void)
short ANIM_fmodifiers_copy_to_buf (ListBase *modifiers, short active)
short ANIM_fmodifiers_paste_from_buf (ListBase *modifiers, short replace)
Variables
static ListBase fmodifier_copypaste_buf = {NULL, NULL}
Detailed Description
Definition in file fmodifier_ui.c.
Define Documentation
#define B_FMODIFIER_REDRAW 20
Definition at line 75 of file fmodifier_ui.c.
Referenced by draw_modifier__envelope(), and draw_modifier__generator().
#define B_REDR 1
Definition at line 74 of file fmodifier_ui.c.
Referenced by ANIM_uiTemplate_fmodifier_draw(), change_ipo_actuator(), check_armature_actuator(), check_armature_sensor(), check_controller_state_mask(), check_state_mask(), do_view3d_header_buttons(), do_view3d_region_buttons(), draw_actuatorbuttons(), draw_controllerbuttons(), draw_sensorbuttons(), graph_panel_key_properties(), logic_buttons(), logic_buttons_new(), and v3d_editvertex_buts().
#define BINARYSEARCH_FRAMEEQ_THRESH 0.0001f
Definition at line 326 of file fmodifier_ui.c.
Referenced by binarysearch_fcm_envelopedata_index().
#define DRAW_BACKDROP (height)
Value:
{ \
        uiDefBut(block, ROUNDBOX, B_REDR, "", -3, yco-height, width+3, height-1, NULL, 5.0, 0.0, 12.0, (float)rb_col, ""); \
    }
Definition at line 79 of file fmodifier_ui.c.
#define UI_FLT_MAX 10000.0f
Definition at line 72 of file fmodifier_ui.c.
Referenced by draw_modifier__envelope(), and draw_modifier__generator().
Function Documentation
short ANIM_fmodifiers_copy_to_buf (ListBase * modifiers, short active)
Definition at line 782 of file fmodifier_ui.c.
References BLI_addtail(), copy_fmodifier(), copy_fmodifiers(), ELEM, find_active_fmodifier(), ListBase::first, and NULL.
Referenced by graph_fmodifier_copy_exec(), and nla_fmodifier_copy_exec().
short ANIM_fmodifiers_paste_from_buf (ListBase * modifiers, short replace)
Definition at line 811 of file fmodifier_ui.c.
References BLI_addtail(), copy_fmodifier(), ListBase::first, FModifier::flag, FMODIFIER_FLAG_ACTIVE, free_fmodifiers(), FModifier::next, and NULL.
Referenced by graph_fmodifier_paste_exec(), and nla_fmodifier_paste_exec().
void ANIM_uiTemplate_fmodifier_draw (uiLayout * layout, ID * id, ListBase * modifiers, FModifier * fcm)
Definition at line 628 of file fmodifier_ui.c.
References B_REDR, BUT, delete_fmodifier_cb(), draw_modifier__cycles(), draw_modifier__envelope(), draw_modifier__fn_generator(), draw_modifier__generator(), draw_modifier__limits(), draw_modifier__noise(), draw_modifier__stepped(), FModifier::flag, FMODIFIER_FLAG_EXPANDED, FMODIFIER_FLAG_RANGERESTRICT, FMODIFIER_FLAG_USEINFLUENCE, fmodifier_get_typeinfo(), FMODIFIER_TYPE_CYCLES, FMODIFIER_TYPE_ENVELOPE, FMODIFIER_TYPE_FN_GENERATOR, FMODIFIER_TYPE_GENERATOR, FMODIFIER_TYPE_LIMITS, FMODIFIER_TYPE_NOISE, FMODIFIER_TYPE_STEPPED, IFACE_, FModifierTypeInfo::name, NULL, RNA_FModifier, RNA_pointer_create(), TIP_, FModifier::type, UI_EMBOSS, UI_EMBOSSN, UI_ITEM_R_ICON_ONLY, UI_LAYOUT_ALIGN_LEFT, UI_LAYOUT_ALIGN_RIGHT, UI_UNIT_X, UI_UNIT_Y, uiBlockSetEmboss(), uiButSetFunc(), uiDefIconBut(), uiItemL(), uiItemR(), uiLayoutBox(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), and uiLayoutSetAlignment().
Referenced by graph_panel_modifiers(), and nla_panel_modifiers().
static int binarysearch_fcm_envelopedata_index (FCM_EnvelopeData array[], float frame, int arraylen, short * exists) [static]
Definition at line 331 of file fmodifier_ui.c.
References BINARYSEARCH_FRAMEEQ_THRESH, IS_EQT, NULL, and FCM_EnvelopeData::time.
Referenced by fmod_envelope_addpoint_cb().
static void delete_fmodifier_cb (bContext * C, void * fmods_v, void * fcm_v) [static]
Definition at line 96 of file fmodifier_ui.c.
References ED_undo_push(), NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, remove_fmodifier(), and WM_event_add_notifier().
Referenced by ANIM_uiTemplate_fmodifier_draw().
static void draw_modifier__cycles (uiLayout * layout, ID * id, FModifier * fcm, short UNUSEDwidth) [static]
Definition at line 270 of file fmodifier_ui.c.
References IFACE_, NULL, RNA_FModifierCycles, RNA_pointer_create(), split(), uiItemL(), uiItemR(), uiLayoutColumn(), and uiLayoutSplit().
Referenced by ANIM_uiTemplate_fmodifier_draw().
static void draw_modifier__envelope (uiLayout * layout, ID * id, FModifier * fcm, short UNUSEDwidth) [static]
Definition at line 488 of file fmodifier_ui.c.
References B_FMODIFIER_REDRAW, BUT, FModifier::data, FMod_Envelope::data, fmod_envelope_addpoint_cb(), fmod_envelope_deletepoint_cb(), i, IFACE_, LABEL, MAXFRAMEF, NULL, NUM, RNA_FModifierEnvelope, RNA_pointer_create(), SET_INT_IN_POINTER, TIP_, UI_FLT_MAX, uiBlockBeginAlign(), uiButSetFunc(), uiDefBut(), uiDefButF(), uiDefIconBut(), uiItemL(), uiItemR(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), and validate_fmodifier_cb().
Referenced by ANIM_uiTemplate_fmodifier_draw().
static void draw_modifier__fn_generator (uiLayout * layout, ID * id, FModifier * fcm, short UNUSEDwidth) [static]
Definition at line 247 of file fmodifier_ui.c.
References NULL, RNA_FModifierFunctionGenerator, RNA_pointer_create(), UI_ITEM_R_TOGGLE, uiItemR(), and uiLayoutColumn().
Referenced by ANIM_uiTemplate_fmodifier_draw().
static void draw_modifier__generator (uiLayout * layout, ID * id, FModifier * fcm, short width) [static]
Definition at line 114 of file fmodifier_ui.c.
References FMod_Generator::arraysize, B_FMODIFIER_REDRAW, FMod_Generator::coefficients, FModifier::data, data, FCM_GENERATOR_POLYNOMIAL, FCM_GENERATOR_POLYNOMIAL_FACTORISED, i, IFACE_, LABEL, MENU, FMod_Generator::mode, NULL, NUM, FMod_Generator::poly_order, RNA_FModifierFunctionGenerator, RNA_pointer_create(), TIP_, TOG, UI_FLT_MAX, UI_UNIT_Y, uiBlockBeginAlign(), uiBlockEndAlign(), uiButSetFunc(), uiDefBut(), uiDefButF(), uiDefButI(), uiDefButR(), uiLayoutGetBlock(), uiLayoutRow(), and validate_fmodifier_cb().
Referenced by ANIM_uiTemplate_fmodifier_draw().
static void draw_modifier__limits (uiLayout * layout, ID * id, FModifier * fcm, short UNUSEDwidth) [static]
Definition at line 548 of file fmodifier_ui.c.
References NULL, RNA_FModifierLimits, RNA_pointer_create(), split(), uiItemR(), uiLayoutColumn(), and uiLayoutSplit().
Referenced by ANIM_uiTemplate_fmodifier_draw().
static void draw_modifier__noise (uiLayout * layout, ID * id, FModifier * fcm, short UNUSEDwidth) [static]
Definition at line 299 of file fmodifier_ui.c.
References NULL, RNA_FModifierNoise, RNA_pointer_create(), split(), uiItemR(), uiLayoutColumn(), and uiLayoutSplit().
Referenced by ANIM_uiTemplate_fmodifier_draw().
static void draw_modifier__stepped (uiLayout * layout, ID * id, FModifier * fcm, short UNUSEDwidth) [static]
Definition at line 596 of file fmodifier_ui.c.
References NULL, RNA_boolean_get(), RNA_FModifierStepped, RNA_pointer_create(), uiItemR(), uiLayoutColumn(), and uiLayoutSetActive().
Referenced by ANIM_uiTemplate_fmodifier_draw().
static void fmod_envelope_addpoint_cb (bContext * C, void * fcm_dv, void * UNUSEDarg) [static]
Definition at line 406 of file fmodifier_ui.c.
References binarysearch_fcm_envelopedata_index(), RenderData::cfra, CTX_data_scene(), FMod_Envelope::data, FCM_EnvelopeData::f1, FCM_EnvelopeData::f2, i, if(), FCM_EnvelopeData::max, MEM_callocN(), MEM_freeN(), FCM_EnvelopeData::min, Scene::r, FCM_EnvelopeData::time, and FMod_Envelope::totvert.
Referenced by draw_modifier__envelope().
static void fmod_envelope_deletepoint_cb (bContext * UNUSEDC, void * fcm_dv, void * ind_v) [static]
Definition at line 458 of file fmodifier_ui.c.
References FMod_Envelope::data, GET_INT_FROM_POINTER, MEM_callocN(), MEM_freeN(), NULL, and FMod_Envelope::totvert.
Referenced by draw_modifier__envelope().
void free_fmodifiers_copybuf (void)
Definition at line 772 of file fmodifier_ui.c.
References free_fmodifiers().
Referenced by graph_fmodifier_copy_exec(), nla_fmodifier_copy_exec(), and WM_exit_ext().
static void validate_fmodifier_cb (bContext * UNUSEDC, void * fcm_v, void * UNUSEDarg) [static]
Definition at line 85 of file fmodifier_ui.c.
References fmodifier_get_typeinfo(), and FModifierTypeInfo::verify_data.
Referenced by draw_modifier__envelope(), and draw_modifier__generator().
Variable Documentation
ListBase fmodifier_copypaste_buf = {NULL, NULL} [static]
Definition at line 767 of file fmodifier_ui.c.