Blender: BKE_customdata.h File Reference
BKE_customdata.h File Reference
blenkernel
CustomData interface, see also DNA_customdata_types.h.
#include "../blenloader/BLO_sys_types.h"
Classes
struct CDBlockBytes
Defines
#define ORIGINDEX_NONE -1
#define CD_ASSIGN 0
#define CD_CALLOC 1
#define CD_DEFAULT 2
#define CD_REFERENCE 3
#define CD_DUPLICATE 4
#define CD_TYPE_AS_MASK(_type) (CustomDataMask)((CustomDataMask)1 << (CustomDataMask)(_type))
Typedefs
typedef uint64_t CustomDataMask
Functions
int CustomData_layer_has_math (struct CustomData *data, int layer_n)
void CustomData_data_copy_value (int type, void *source, void *dest)
int CustomData_data_equals (int type, void *data1, void *data2)
void CustomData_data_initminmax (int type, void *min, void *max)
void CustomData_data_dominmax (int type, void *data, void *min, void *max)
void CustomData_data_multiply (int type, void *data, float fac)
void CustomData_data_add (int type, void *data1, void *data2)
void CustomData_copy (const struct CustomData *source, struct CustomData *dest, CustomDataMask mask, int alloctype, int totelem)
void CustomData_update_typemap (struct CustomData *data)
void CustomData_merge (const struct CustomData *source, struct CustomData *dest, CustomDataMask mask, int alloctype, int totelem)
void CustomData_bmesh_merge (struct CustomData *source, struct CustomData *dest, CustomDataMask mask, int alloctype, struct BMesh *bm, const char htype)
void CustomData_free (struct CustomData *data, int totelem)
void CustomData_free_temporary (struct CustomData *data, int totelem)
void * CustomData_add_layer (struct CustomData *data, int type, int alloctype, void *layer, int totelem)
void * CustomData_add_layer_named (struct CustomData *data, int type, int alloctype, void *layer, int totelem, const char *name)
int CustomData_free_layer (struct CustomData *data, int type, int totelem, int index)
int CustomData_free_layer_active (struct CustomData *data, int type, int totelem)
void CustomData_free_layers (struct CustomData *data, int type, int totelem)
int CustomData_has_layer (const struct CustomData *data, int type)
int CustomData_number_of_layers (const struct CustomData *data, int type)
void * CustomData_duplicate_referenced_layer (struct CustomData *data, const int type, const int totelem)
void * CustomData_duplicate_referenced_layer_named (struct CustomData *data, const int type, const char *name, const int totelem)
int CustomData_is_referenced_layer (struct CustomData *data, int type)
void CustomData_set_only_copy (const struct CustomData *data, CustomDataMask mask)
void CustomData_copy_data (const struct CustomData *source, struct CustomData *dest, int source_index, int dest_index, int count)
void CustomData_copy_elements (int type, void *source, void *dest, int count)
void CustomData_bmesh_copy_data (const struct CustomData *source, struct CustomData *dest, void *src_block, void **dest_block)
void CustomData_free_elem (struct CustomData *data, int index, int count)
void CustomData_interp (const struct CustomData *source, struct CustomData *dest, int *src_indices, float *weights, float *sub_weights, int count, int dest_index)
void CustomData_bmesh_interp (struct CustomData *data, void **src_blocks, float *weights, float *sub_weights, int count, void *dest_block)
void CustomData_swap (struct CustomData *data, int index, const int *corner_indices)
void * CustomData_get (const struct CustomData *data, int index, int type)
void * CustomData_get_n (const struct CustomData *data, int type, int index, int n)
void * CustomData_bmesh_get (const struct CustomData *data, void *block, int type)
void * CustomData_bmesh_get_n (const struct CustomData *data, void *block, int type, int n)
void * CustomData_bmesh_get_layer_n (const struct CustomData *data, void *block, int n)
int CustomData_set_layer_name (const struct CustomData *data, int type, int n, const char *name)
void * CustomData_get_layer (const struct CustomData *data, int type)
void * CustomData_get_layer_n (const struct CustomData *data, int type, int n)
void * CustomData_get_layer_named (const struct CustomData *data, int type, const char *name)
int CustomData_get_layer_index (const struct CustomData *data, int type)
int CustomData_get_layer_index_n (const struct CustomData *data, int type, int n)
int CustomData_get_named_layer_index (const struct CustomData *data, int type, const char *name)
int CustomData_get_active_layer_index (const struct CustomData *data, int type)
int CustomData_get_render_layer_index (const struct CustomData *data, int type)
int CustomData_get_clone_layer_index (const struct CustomData *data, int type)
int CustomData_get_stencil_layer_index (const struct CustomData *data, int type)
int CustomData_get_active_layer (const struct CustomData *data, int type)
int CustomData_get_render_layer (const struct CustomData *data, int type)
int CustomData_get_clone_layer (const struct CustomData *data, int type)
int CustomData_get_stencil_layer (const struct CustomData *data, int type)
void CustomData_set (const struct CustomData *data, int index, int type, void *source)
void CustomData_bmesh_set (const struct CustomData *data, void *block, int type, void *source)
void CustomData_bmesh_set_n (struct CustomData *data, void *block, int type, int n, void *source)
void CustomData_bmesh_set_layer_n (struct CustomData *data, void *block, int n, void *source)
void * CustomData_set_layer (const struct CustomData *data, int type, void *ptr)
void * CustomData_set_layer_n (const struct CustomData *data, int type, int n, void *ptr)
void CustomData_set_layer_active (struct CustomData *data, int type, int n)
void CustomData_set_layer_render (struct CustomData *data, int type, int n)
void CustomData_set_layer_clone (struct CustomData *data, int type, int n)
void CustomData_set_layer_stencil (struct CustomData *data, int type, int n)
void CustomData_set_layer_active_index (struct CustomData *data, int type, int n)
void CustomData_set_layer_render_index (struct CustomData *data, int type, int n)
void CustomData_set_layer_clone_index (struct CustomData *data, int type, int n)
void CustomData_set_layer_stencil_index (struct CustomData *data, int type, int n)
void CustomData_set_layer_flag (struct CustomData *data, int type, int flag)
void CustomData_bmesh_set_default (struct CustomData *data, void **block)
void CustomData_bmesh_free_block (struct CustomData *data, void **block)
void CustomData_to_bmesh_block (const struct CustomData *source, struct CustomData *dest, int src_index, void **dest_block)
void CustomData_from_bmesh_block (const struct CustomData *source, struct CustomData *dest, void *src_block, int dest_index)
void CustomData_file_write_info (int type, const char **structname, int *structnum)
int CustomData_sizeof (int type)
const char * CustomData_layertype_name (int type)
void CustomData_set_layer_unique_name (struct CustomData *data, int index)
void CustomData_validate_layer_name (const struct CustomData *data, int type, char *name, char *outname)
int CustomData_verify_versions (struct CustomData *data, int index)
void CustomData_to_bmeshpoly (struct CustomData *fdata, struct CustomData *pdata, struct CustomData *ldata, int totloop, int totpoly)
void CustomData_from_bmeshpoly (struct CustomData *fdata, struct CustomData *pdata, struct CustomData *ldata, int total)
void CustomData_bmesh_update_active_layers (struct CustomData *fdata, struct CustomData *pdata, struct CustomData *ldata)
void CustomData_bmesh_init_pool (struct CustomData *data, int totelem, const char htype)
void CustomData_external_add (struct CustomData *data, struct ID *id, int type, int totelem, const char *filename)
void CustomData_external_remove (struct CustomData *data, struct ID *id, int type, int totelem)
int CustomData_external_test (struct CustomData *data, int type)
void CustomData_external_write (struct CustomData *data, struct ID *id, CustomDataMask mask, int totelem, int free)
void CustomData_external_read (struct CustomData *data, struct ID *id, CustomDataMask mask, int totelem)
void CustomData_external_reload (struct CustomData *data, struct ID *id, CustomDataMask mask, int totelem)
Variables
const CustomDataMask CD_MASK_BAREMESH
const CustomDataMask CD_MASK_MESH
const CustomDataMask CD_MASK_EDITMESH
const CustomDataMask CD_MASK_DERIVEDMESH
const CustomDataMask CD_MASK_BMESH
const CustomDataMask CD_MASK_FACECORNERS
Detailed Description
CustomData interface, see also DNA_customdata_types.h.
Author:
Ben Batt
Definition in file BKE_customdata.h.
Define Documentation
#define CD_ASSIGN 0
Definition at line 67 of file BKE_customdata.h.
Referenced by add_orco_dm(), add_shapekey_layers(), add_tface_color_layer(), BKE_mesh_convert_mfaces_to_mpolys(), BM_mesh_bm_from_me(), BM_mesh_bm_to_me(), CDDM_calc_normals_mapping_ex(), cddm_copy_ex(), CDDM_set_medge(), CDDM_set_mface(), CDDM_set_mloop(), CDDM_set_mpoly(), CDDM_set_mvert(), CDDM_tessfaces_to_faces(), customData_add_layer__internal(), CustomData_merge(), customdata_version_242(), distribute_threads_init_data(), DM_DupPolys(), DM_to_mesh(), DM_update_weight_mcol(), get_dm(), make_edges(), mesh_recalcTessellation(), and nurbs_to_mesh().
#define CD_CALLOC 1
Definition at line 68 of file BKE_customdata.h.
Referenced by add_orco_dm(), applyModifier(), BKE_mesh_calc_edges(), BKE_mesh_ensure_navmesh(), BM_mesh_bm_from_me(), BM_mesh_bm_to_me(), BM_mesh_copy(), ccgDM_get_edge_data_layer(), ccgDM_get_tessface_data_layer(), ccgDM_get_vert_data_layer(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), CDDM_calc_normals(), CDDM_calc_normals_tessface(), CDDM_from_BMEditMesh(), CDDM_from_template(), CDDM_new(), createRepresentation(), CustomData_from_bmeshpoly(), CustomData_to_bmeshpoly(), customdata_version_242(), DM_add_tangent_layer(), dm_calc_normal(), DM_from_template(), dm_getEdgeArray(), dm_getLoopArray(), dm_getPolyArray(), dm_getTessFaceArray(), dm_getVertArray(), DM_to_bmesh_ex(), DM_update_weight_mcol(), do_hair_dynamics(), dynamicPaint_Modifier_apply(), ED_mesh_update(), ED_object_modifier_convert(), ED_vgroup_data_create(), editbmesh_calc_modifiers(), emDM_getTessFaceDataArray(), getCCGDerivedMesh(), getEditDerivedBMesh(), join_mesh_exec(), mball_to_mesh(), mesh_add_edges(), mesh_add_loops(), mesh_add_polys(), mesh_add_tessfaces(), mesh_add_verts(), mesh_calc_modifiers(), mesh_recalcTessellation(), mesh_separate_selected(), multires_load_old(), multires_load_old_250(), multires_mdisps_initialize_hidden(), and RE_make_sticky().
#define CD_DEFAULT 2
Definition at line 69 of file BKE_customdata.h.
Referenced by BM_data_layer_add(), BM_data_layer_add_named(), ConvertCSGDescriptorsToDerivedMesh(), customData_add_layer__internal(), ED_mesh_color_add(), ED_mesh_uv_texture_add(), join_mesh_exec(), make_vertexcol(), mesh_add_edges(), mesh_add_loops(), mesh_add_polys(), mesh_add_tessfaces(), mesh_add_verts(), multiresModifier_disp_run(), and texture_paint_toggle_exec().
#define CD_DUPLICATE 4
Definition at line 71 of file BKE_customdata.h.
Referenced by CDDM_tessfaces_to_faces(), copy_mesh(), customData_add_layer__internal(), CustomData_merge(), DM_DupPolys(), DM_to_mesh(), ED_mesh_color_add(), and ED_mesh_uv_texture_add().
#define CD_REFERENCE 3
Definition at line 70 of file BKE_customdata.h.
Referenced by BKE_mesh_ensure_navmesh(), CDDM_from_mesh(), CDDM_recalc_tessellation_ex(), customData_add_layer__internal(), CustomData_merge(), and multires_load_old().
#define CD_TYPE_AS_MASK (_type) (CustomDataMask)((CustomDataMask)1 << (CustomDataMask)(_type))
Definition at line 74 of file BKE_customdata.h.
Referenced by CustomData_external_read(), CustomData_external_reload(), CustomData_external_remove(), CustomData_external_write(), CustomData_merge(), CustomData_set_only_copy(), and mesh_validate_customdata().
#define ORIGINDEX_NONE -1
Definition at line 60 of file BKE_customdata.h.
Referenced by applyModifier(), BM_mesh_bm_to_me(), bm_to_mesh_vertex_map(), ccgDM_drawFacesTex_common(), ccgDM_drawMappedFaces(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgDM_get_edge_data_layer(), ccgDM_get_vert_data_layer(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), cdDM_drawFacesTex_common(), cdDM_drawMappedEdges(), cdDM_drawMappedFaces(), cdDM_drawMappedFacesGLSL(), cdDM_drawMappedFacesMat(), cdDM_foreachMappedEdge(), cdDM_foreachMappedFaceCenter(), cdDM_foreachMappedVert(), ConvertCSGDescriptorsToDerivedMesh(), getCCGDerivedMesh(), paintvert_flush_flags(), snapDerivedMesh(), texface_from_original_index(), and vpaint_build_poly_facemap().
Typedef Documentation
typedef uint64_t CustomDataMask
Definition at line 46 of file BKE_customdata.h.
Function Documentation
void* CustomData_add_layer (struct CustomData * data, int type, int alloctype, void * layer, int totelem)
Definition at line 1575 of file customdata.c.
References customData_add_layer__internal(), CustomData_update_typemap(), CustomDataLayer::data, LayerTypeInfo::defaultname, layerType_getInfo(), and NULL.
Referenced by add_tface_color_layer(), applyModifier(), BKE_mesh_calc_edges(), BKE_mesh_convert_mfaces_to_mpolys(), BM_data_layer_add(), BM_mesh_bm_from_me(), BM_mesh_bm_to_me(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), CDDM_calc_normals(), CDDM_calc_normals_mapping_ex(), CDDM_calc_normals_tessface(), cddm_copy_ex(), CDDM_from_mesh(), CDDM_from_template(), CDDM_new(), CDDM_recalc_tessellation_ex(), CDDM_set_medge(), CDDM_set_mface(), CDDM_set_mloop(), CDDM_set_mpoly(), CDDM_set_mvert(), CDDM_tessfaces_to_faces(), customdata_version_242(), DM_add_edge_layer(), DM_add_loop_layer(), DM_add_poly_layer(), DM_add_tessface_layer(), DM_add_vert_layer(), dm_calc_normal(), DM_DupPolys(), dm_getEdgeArray(), dm_getLoopArray(), dm_getPolyArray(), dm_getTessFaceArray(), dm_getVertArray(), DM_to_mesh(), DM_update_weight_mcol(), dynamicPaint_Modifier_apply(), ED_mesh_update(), ED_object_modifier_convert(), ED_vgroup_data_create(), getCCGDerivedMesh(), join_mesh_exec(), make_edges(), make_vertexcol(), mball_to_mesh(), mesh_add_edges(), mesh_add_loops(), mesh_add_polys(), mesh_add_tessfaces(), mesh_add_verts(), mesh_recalcTessellation(), multires_load_old(), multires_load_old_250(), multires_mdisps_initialize_hidden(), multiresModifier_disp_run(), nurbs_to_mesh(), RE_make_sticky(), and texture_paint_toggle_exec().
void* CustomData_add_layer_named (struct CustomData * data, int type, int alloctype, void * layer, int totelem, const char * name)
Definition at line 1592 of file customdata.c.
References customData_add_layer__internal(), CustomData_update_typemap(), CustomDataLayer::data, and NULL.
Referenced by add_shapekey_layers(), applyModifier(), BKE_mesh_ensure_navmesh(), BM_data_layer_add_named(), BM_mesh_bm_from_me(), createRepresentation(), CustomData_from_bmeshpoly(), CustomData_to_bmeshpoly(), dynamicPaint_Modifier_apply(), ED_mesh_color_add(), and ED_mesh_uv_texture_add().
void CustomData_bmesh_copy_data (const struct CustomData * source, struct CustomData * dest, void * src_block, void ** dest_block)
Referenced by BM_data_interp_from_verts(), bm_edge_attrs_copy(), bm_face_attrs_copy(), bm_loop_attrs_copy(), bm_loop_create(), bm_vert_attrs_copy(), bmo_pointmerge_facedata_exec(), CustomData_bmesh_merge(), and update_data_blocks().
void CustomData_bmesh_free_block (struct CustomData * data, void ** block)
Definition at line 2221 of file customdata.c.
References BLI_mempool_free(), CD_FLAG_NOFREE, CustomDataLayer::flag, LayerTypeInfo::free, i, CustomData::layers, layerType_getInfo(), NULL, CustomDataLayer::offset, CustomData::pool, LayerTypeInfo::size, CustomData::totlayer, CustomData::totsize, and CustomDataLayer::type.
Referenced by BM_data_interp_from_verts(), bm_edge_attrs_copy(), bm_face_attrs_copy(), bm_kill_only_edge(), bm_kill_only_face(), bm_kill_only_loop(), bm_kill_only_vert(), bm_loop_attrs_copy(), BM_mesh_data_free(), bm_vert_attrs_copy(), CustomData_bmesh_alloc_block(), CustomData_bmesh_merge(), and update_data_blocks().
void* CustomData_bmesh_get (const struct CustomData * data, void * block, int type)
Referenced by act_vert_def(), BM_elem_float_data_get(), BM_elem_float_data_set(), bm_face_is_all_uv_sel(), BM_face_multires_bounds_smooth(), bm_loop_interp_mdisps(), bm_loop_reverse_loop(), bm_mdisps_space_set(), BM_mesh_bm_from_me(), BM_mesh_bm_to_me(), bm_to_mesh_vertex_map(), bmdm_get_tri_tex(), bmo_face_reversecolors_exec(), bmo_face_reverseuvs_exec(), bmo_face_rotateuvs_exec(), bmo_rotatecolors_exec(), bmo_similaredges_exec(), bmo_similarfaces_exec(), bmo_similarverts_exec(), border_select_exec(), BPy_BMEdge_CreatePyObject(), bpy_bmedge_dealloc(), BPy_BMFace_CreatePyObject(), bpy_bmface_dealloc(), BPy_BMLoop_CreatePyObject(), bpy_bmloop_dealloc(), BPy_BMVert_CreatePyObject(), bpy_bmvert_dealloc(), CDDM_from_BMEditMesh(), circle_select_exec(), compareFaceAttribs(), construct_param_handle(), construct_param_handle_subsurfed(), correct_uv_aspect(), createRepresentation(), createTransEdge(), createTransEditVerts(), createTransUVs(), cube_project_exec(), CustomData_bmesh_set(), cylinder_project_exec(), DM_to_bmesh_ex(), draw_dm_bweights__mapFunc(), draw_dm_bweights__setDrawOptions(), draw_dm_creases__setDrawOptions(), draw_em_tf_mapped__set_draw(), draw_uvs(), draw_uvs_shadow(), draw_uvs_stretch(), ED_uvedit_assign_image(), ED_uvedit_median(), ED_uvedit_minmax(), ED_uvedit_nearest_uv(), ED_vgroup_give_parray(), ED_vgroup_mirror(), EDBM_mtexpoly_active_get(), EDBM_uv_element_map_create(), EDBM_uv_vert_map_create(), edgetag_context_set(), editvert_mirror_update(), emDM_drawFacesTex_common(), emDM_drawUVEdges(), emDM_getTessFaceDataArray(), find_nearest_uv_face(), findFreeNavPolyIndex(), get_vert_def_nr(), get_weights_array(), getEditDerivedBMesh(), give_parvert(), HC_relaxation_iteration_uv(), hide_exec(), laplacian_relaxation_iteration_uv(), loops_to_customdata_corners(), mouse_select(), navmesh_face_add_exec(), navmesh_face_copy_exec(), nearest_uv_between(), pin_exec(), poly_uv_center(), return_editmesh_vgroup(), reveal_exec(), select_all_perform(), select_edgeloop(), select_linked(), select_pinned_exec(), snap_uvs_to_adjacent_unselected(), snap_uvs_to_cursor(), snap_uvs_to_pixels(), sphere_project_exec(), stitch_calculate_edge_normal(), stitch_calculate_island_snapping(), stitch_check_uvs_stitchable(), stitch_island_calculate_edge_rotation(), stitch_process_data(), texface_from_original_index(), unlink_selection_exec(), uv_find_nearest_edge(), uv_find_nearest_vert(), uv_from_view_exec(), uv_map_clip_correct(), uv_map_mirror(), uv_sculpt_stroke_apply(), uv_sculpt_stroke_init(), uv_sel_co_from_eve(), uvedit_center(), uvedit_edge_select_disable(), uvedit_edge_select_enable(), uvedit_edge_select_test(), uvedit_face_select_disable(), uvedit_face_select_enable(), uvedit_face_select_test(), uvedit_have_selection(), uvedit_set_tile(), uvedit_translate(), uvedit_uv_select_disable(), uvedit_uv_select_enable(), uvedit_uv_select_test(), v3d_editvertex_buts(), vgroup_active_remove_verts(), vgroup_assign_verts(), vgroup_blend(), vgroup_copy_active_to_sel(), vgroup_copy_active_to_sel_single(), vgroup_delete_edit_mode(), vgroup_do_remap(), vgroup_select_verts(), and weld_align_uv().
void* CustomData_bmesh_get_layer_n (const struct CustomData * data, void * block, int n)
Referenced by bmo_collapsecon_do_layer(), bmo_pointmerge_facedata_exec(), bmo_vert_average_facedata_exec(), bmw_UVEdgeWalker_step(), CustomData_bmesh_set_layer_n(), EDBM_verts_mirror_cache_begin(), EDBM_verts_mirror_cache_clear(), and EDBM_verts_mirror_get().
void* CustomData_bmesh_get_n (const struct CustomData * data, void * block, int type, int n)
Referenced by alter_co(), BM_mesh_bm_from_me(), BM_mesh_bm_to_me(), bmo_bevel_exec(), bmo_esubd_exec(), bmo_mirror_exec(), bpy_bmlayeritem_ptr_get(), CustomData_bmesh_set_n(), ED_mesh_uv_loop_reset_ex(), edbm_bevel_exec(), edbm_blend_from_shape_exec(), editmesh_face_copy_customdata(), editmesh_loop_copy_customdata(), loops_to_customdata_corners(), and shape_propagate().
void CustomData_bmesh_init_pool (struct CustomData * data, int totelem, const char htype)
Definition at line 2136 of file customdata.c.
References BLI_assert, BLI_mempool_create(), BLI_MEMPOOL_SYSMALLOC, BM_EDGE, BM_FACE, BM_LOOP, bm_mesh_chunksize_default, BM_VERT, NULL, CustomData::pool, BMAllocTemplate::totedge, BMAllocTemplate::totface, CustomData::totlayer, BMAllocTemplate::totloop, CustomData::totsize, and BMAllocTemplate::totvert.
Referenced by BM_mesh_bm_from_me(), BM_mesh_copy(), createRepresentation(), CustomData_bmesh_merge(), mesh_separate_selected(), and update_data_blocks().
void CustomData_bmesh_interp (struct CustomData * data, void ** src_blocks, float * weights, float * sub_weights, int count, void * dest_block)
Definition at line 2442 of file customdata.c.
References i, LayerTypeInfo::interp, CustomData::layers, layerType_getInfo(), MEM_callocN(), MEM_freeN(), CustomDataLayer::offset, SOURCE_BUF_SIZE, CustomData::totlayer, and CustomDataLayer::type.
Referenced by BM_data_interp_face_vert_edge(), BM_data_interp_from_verts(), BM_face_interp_from_face(), BM_loop_interp_from_face(), BM_vert_collapse_faces(), and BM_vert_interp_from_face().
void CustomData_bmesh_merge (struct CustomData * source, struct CustomData * dest, CustomDataMask mask, int alloctype, struct BMesh * bm, const char htype)
Definition at line 2160 of file customdata.c.
References BLI_assert, BLI_mempool_destroy(), BM_EDGE, BM_EDGES_OF_MESH, BM_FACE, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOP, BM_LOOPS_OF_FACE, BM_VERT, BM_VERTS_OF_MESH, CustomData_bmesh_copy_data(), CustomData_bmesh_free_block(), CustomData_bmesh_init_pool(), CustomData_merge(), BMHeader::data, BMLoop::head, CustomData::layers, MEM_dupallocN(), MEM_freeN(), NULL, and CustomData::pool.
Referenced by DM_to_bmesh_ex().
void CustomData_bmesh_set (const struct CustomData * data, void * block, int type, void * source)
void CustomData_bmesh_set_default (struct CustomData * data, void ** block)
Definition at line 2472 of file customdata.c.
References CustomData_bmesh_alloc_block(), i, CustomData::layers, layerType_getInfo(), CustomDataLayer::offset, LayerTypeInfo::set_default, LayerTypeInfo::size, CustomData::totlayer, and CustomDataLayer::type.
Referenced by BM_edge_create(), bm_face_create__internal(), bm_loop_create(), BM_vert_create(), and update_data_blocks().
void CustomData_bmesh_set_layer_n (struct CustomData * data, void * block, int n, void * source)
Definition at line 2429 of file customdata.c.
References LayerTypeInfo::copy, CustomData_bmesh_get_layer_n(), CustomData::layers, layerType_getInfo(), LayerTypeInfo::size, and CustomDataLayer::type.
void CustomData_bmesh_set_n (struct CustomData * data, void * block, int type, int n, void * source)
Definition at line 2416 of file customdata.c.
References LayerTypeInfo::copy, CustomData_bmesh_get_n(), layerType_getInfo(), and LayerTypeInfo::size.
Referenced by editmesh_face_copy_customdata(), and editmesh_loop_copy_customdata().
void CustomData_bmesh_update_active_layers (struct CustomData * fdata, struct CustomData * pdata, struct CustomData * ldata)
Definition at line 2099 of file customdata.c.
References CD_MCOL, CD_MLOOPCOL, CD_MLOOPUV, CD_MTEXPOLY, CD_MTFACE, CustomData_get_active_layer(), CustomData_get_clone_layer(), CustomData_get_render_layer(), CustomData_get_stencil_layer(), CustomData_has_layer(), CustomData_set_layer_active(), CustomData_set_layer_clone(), CustomData_set_layer_render(), and CustomData_set_layer_stencil().
Referenced by CDDM_recalc_tessellation_ex(), CustomData_from_bmeshpoly(), and mesh_update_linked_customdata().
void CustomData_copy (const struct CustomData * source, struct CustomData * dest, CustomDataMask mask, int alloctype, int totelem)
Definition at line 1208 of file customdata.c.
References CustomData_merge(), CustomData::external, and MEM_dupallocN().
Referenced by BM_mesh_bm_from_me(), BM_mesh_bm_to_me(), BM_mesh_copy(), copy_mesh(), DM_DupPolys(), DM_from_template(), DM_to_mesh(), mesh_add_edges(), mesh_add_loops(), mesh_add_polys(), mesh_add_tessfaces(), mesh_add_verts(), and mesh_separate_selected().
void CustomData_copy_data (const struct CustomData * source, struct CustomData * dest, int source_index, int dest_index, int count)
Referenced by applyModifier(), cddm_copy_ex(), CDDM_merge_verts(), ConvertCSGDescriptorsToDerivedMesh(), DM_copy_edge_data(), DM_copy_loop_data(), DM_copy_poly_data(), DM_copy_tessface_data(), DM_copy_vert_data(), getCCGDerivedMesh(), join_mesh_exec(), mesh_add_edges(), mesh_add_loops(), mesh_add_polys(), mesh_add_tessfaces(), mesh_add_verts(), mesh_strip_loose_edges(), mesh_strip_loose_faces(), and mesh_strip_loose_polysloops().
void CustomData_copy_elements (int type, void * source, void * dest, int count)
Definition at line 1788 of file customdata.c.
References LayerTypeInfo::copy, layerType_getInfo(), and LayerTypeInfo::size.
void CustomData_data_add (int type, void * data1, void * data2)
Definition at line 2395 of file customdata.c.
References LayerTypeInfo::add, and layerType_getInfo().
Referenced by bmo_collapsecon_do_layer(), bmo_pointmerge_facedata_exec(), and bmo_vert_average_facedata_exec().
void CustomData_data_copy_value (int type, void * source, void * dest)
Definition at line 2347 of file customdata.c.
References LayerTypeInfo::copyvalue, layerType_getInfo(), and LayerTypeInfo::size.
Referenced by bmo_collapsecon_do_layer(), and bmo_vert_average_facedata_exec().
void CustomData_data_dominmax (int type, void * data, void * min, void * max)
Definition at line 2377 of file customdata.c.
References LayerTypeInfo::dominmax, and layerType_getInfo().
Referenced by bmo_collapsecon_do_layer(), and bmo_vert_average_facedata_exec().
int CustomData_data_equals (int type, void * data1, void * data2)
Definition at line 2359 of file customdata.c.
References LayerTypeInfo::equal, layerType_getInfo(), and LayerTypeInfo::size.
Referenced by bmw_UVEdgeWalker_step().
void CustomData_data_initminmax (int type, void * min, void * max)
Definition at line 2368 of file customdata.c.
References LayerTypeInfo::initminmax, and layerType_getInfo().
Referenced by bmo_collapsecon_do_layer(), and bmo_vert_average_facedata_exec().
void CustomData_data_multiply (int type, void * data, float fac)
Definition at line 2386 of file customdata.c.
References layerType_getInfo(), and LayerTypeInfo::multiply.
Referenced by bmo_collapsecon_do_layer(), bmo_pointmerge_facedata_exec(), and bmo_vert_average_facedata_exec().
void* CustomData_duplicate_referenced_layer (struct CustomData * data, const int type, const int totelem)
Definition at line 1674 of file customdata.c.
References CD_FLAG_NOFREE, LayerTypeInfo::copy, CustomData_get_active_layer_index(), CustomDataLayer::data, CustomDataLayer::flag, CustomData::layers, layerType_getInfo(), MEM_dupallocN(), MEM_mallocN(), NULL, LayerTypeInfo::size, and CustomDataLayer::type.
Referenced by applyModifier(), CDDM_apply_vert_coords(), CDDM_apply_vert_normals(), CDDM_calc_normals(), CDDM_calc_normals_mapping_ex(), CDDM_calc_normals_tessface(), and dm_calc_normal().
void* CustomData_duplicate_referenced_layer_named (struct CustomData * data, const int type, const char * name, const int totelem)
Definition at line 1706 of file customdata.c.
References CD_FLAG_NOFREE, LayerTypeInfo::copy, CustomData_get_named_layer_index(), CustomDataLayer::data, CustomDataLayer::flag, CustomData::layers, layerType_getInfo(), MEM_dupallocN(), MEM_mallocN(), NULL, LayerTypeInfo::size, and CustomDataLayer::type.
Referenced by uvprojectModifier_do().
void CustomData_external_add (struct CustomData * data, struct ID * id, int type, int totelem, const char * filename)
Referenced by bm_corners_to_loops(), and multires_external_save_exec().
void CustomData_external_read (struct CustomData * data, struct ID * id, CustomDataMask mask, int totelem)
Definition at line 2726 of file customdata.c.
References CD_FLAG_EXTERNAL, CD_FLAG_IN_MEMORY, CD_TYPE_AS_MASK, cdf_create(), cdf_free(), cdf_layer_find(), cdf_read_close(), cdf_read_layer(), cdf_read_open(), CDF_TYPE_MESH, customdata_external_filename(), CustomDataLayer::data, CustomData::external, FILE_MAX, CustomDataLayer::flag, i, CustomData::layers, layerType_getInfo(), layerType_getName(), CustomDataLayer::name, LayerTypeInfo::read, CustomData::totlayer, CustomDataLayer::type, and update().
Referenced by BKE_mesh_convert_mfaces_to_mpolys(), CustomData_external_remove(), CustomData_external_write(), multires_apply_smat(), multires_del_higher(), multires_dm_create_from_derived(), multires_modifier_update_mdisps(), multires_topology_changed(), and multiresModifier_del_levels().
void CustomData_external_reload (struct CustomData * data, struct ID * id, CustomDataMask mask, int totelem)
Referenced by multires_force_external_reload().
void CustomData_external_remove (struct CustomData * data, struct ID * id, int type, int totelem)
Definition at line 2900 of file customdata.c.
References CD_FLAG_EXTERNAL, CD_FLAG_IN_MEMORY, CD_TYPE_AS_MASK, cdf_remove(), customdata_external_filename(), CustomData_external_free(), CustomData_external_read(), CustomData_get_active_layer_index(), CustomData::external, CustomDataLayer::flag, i, CustomData::layers, CustomData::totlayer, and CustomDataLayer::type.
Referenced by multires_customdata_delete(), and multires_external_pack_exec().
int CustomData_external_test (struct CustomData * data, int type)
Definition at line 2936 of file customdata.c.
References CD_FLAG_EXTERNAL, CustomData_get_active_layer_index(), CustomDataLayer::flag, and CustomData::layers.
Referenced by bm_corners_to_loops(), multires_external_pack_exec(), multires_external_save_exec(), and multires_external_save_invoke().
void CustomData_external_write (struct CustomData * data, struct ID * id, CustomDataMask mask, int totelem, int free)
Definition at line 2785 of file customdata.c.
References CD_FLAG_EXTERNAL, CD_FLAG_IN_MEMORY, CD_TYPE_AS_MASK, cdf_create(), cdf_free(), cdf_layer_add(), cdf_layer_find(), CDF_TYPE_MESH, cdf_write_close(), cdf_write_layer(), cdf_write_open(), customdata_external_filename(), CustomData_external_read(), CustomDataLayer::data, CustomData::external, FILE_MAX, LayerTypeInfo::filesize, CustomDataLayer::flag, LayerTypeInfo::free, i, CustomData::layers, layerType_getInfo(), CustomDataLayer::name, LayerTypeInfo::size, CustomData::totlayer, CustomDataLayer::type, update(), and LayerTypeInfo::write.
Referenced by multires_external_save_exec(), and write_customdata().
void CustomData_file_write_info (int type, const char ** structname, int * structnum)
Definition at line 2581 of file customdata.c.
References layerType_getInfo(), LayerTypeInfo::structname, and LayerTypeInfo::structnum.
Referenced by dm_debug_info_layers(), and write_customdata().
void CustomData_free (struct CustomData * data, int totelem)
Definition at line 1242 of file customdata.c.
References CustomData_external_free(), customData_free_layer__internal(), i, CustomData::layers, MEM_freeN(), and CustomData::totlayer.
Referenced by BKE_mesh_calc_edges(), BKE_mesh_convert_mfaces_to_mpolys(), BM_mesh_bm_from_me(), BM_mesh_bm_to_me(), BM_mesh_data_free(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), CDDM_tessfaces_to_faces(), ConvertCSGDescriptorsToDerivedMesh(), direct_link_mesh(), DM_DupPolys(), DM_release(), DM_to_mesh(), free_mesh(), join_mesh_exec(), mesh_add_edges(), mesh_add_loops(), mesh_add_polys(), mesh_add_tessfaces(), mesh_add_verts(), mesh_recalcTessellation(), mesh_tessface_clear_intern(), multires_free(), and write_meshs().
void CustomData_free_elem (struct CustomData * data, int index, int count)
Definition at line 1857 of file customdata.c.
References CD_FLAG_NOFREE, CustomDataLayer::data, CustomDataLayer::flag, LayerTypeInfo::free, i, CustomData::layers, layerType_getInfo(), LayerTypeInfo::size, CustomData::totlayer, and CustomDataLayer::type.
Referenced by CDDM_lower_num_edges(), CDDM_lower_num_polys(), CDDM_lower_num_tessfaces(), CDDM_lower_num_verts(), DM_free_edge_data(), DM_free_loop_data(), DM_free_poly_data(), DM_free_tessface_data(), DM_free_vert_data(), mesh_remove_edges(), mesh_remove_faces(), mesh_remove_verts(), mesh_strip_loose_edges(), mesh_strip_loose_faces(), and mesh_strip_loose_polysloops().
int CustomData_free_layer (struct CustomData * data, int type, int totelem, int index)
Definition at line 1608 of file customdata.c.
References CustomDataLayer::active, CustomDataLayer::active_clone, CustomDataLayer::active_mask, CustomDataLayer::active_rnd, customData_free_layer__internal(), CustomData_get_layer_index(), CUSTOMDATA_GROW, customData_resize(), customData_update_offsets(), CustomData_update_typemap(), i, if(), CustomData::layers, CustomData::maxlayer, CustomData::totlayer, and CustomDataLayer::type.
Referenced by BM_data_layer_free_n(), CustomData_free_layer_active(), and mesh_validate_customdata().
int CustomData_free_layer_active (struct CustomData * data, int type, int totelem)
Definition at line 1643 of file customdata.c.
References CustomData_free_layer(), and CustomData_get_active_layer_index().
Referenced by BM_data_layer_free(), CustomData_free_layers(), delete_customdata_layer(), getCCGDerivedMesh(), mesh_sticky_remove_exec(), multires_customdata_delete(), RE_make_sticky(), vgroup_delete_all(), and vgroup_delete_edit_mode().
void CustomData_free_layers (struct CustomData * data, int type, int totelem)
Definition at line 1652 of file customdata.c.
References CustomData_free_layer_active(), and CustomData_has_layer().
Referenced by CDDM_calc_normals_mapping_ex(), multires_load_old(), navmesh_clear_exec(), and navmesh_reset_exec().
void CustomData_free_temporary (struct CustomData * data, int totelem)
Definition at line 1753 of file customdata.c.
References CD_FLAG_TEMPORARY, customData_free_layer__internal(), CUSTOMDATA_GROW, customData_resize(), customData_update_offsets(), CustomDataLayer::flag, i, CustomData::layers, CustomData::maxlayer, and CustomData::totlayer.
Referenced by DM_release().
void CustomData_from_bmesh_block (const struct CustomData * source, struct CustomData * dest, void * src_block, int dest_index)
Referenced by BM_mesh_bm_to_me(), and CDDM_from_BMEditMesh().
void CustomData_from_bmeshpoly (struct CustomData * fdata, struct CustomData * pdata, struct CustomData * ldata, int total)
Definition at line 2076 of file customdata.c.
References CD_CALLOC, CD_MCOL, CD_MLOOPCOL, CD_MTEXPOLY, CD_MTFACE, CD_ORIGSPACE, CD_ORIGSPACE_MLOOP, CD_PREVIEW_MCOL, CD_PREVIEW_MLOOPCOL, CustomData_add_layer_named(), CustomData_bmesh_update_active_layers(), i, CustomData::layers, CustomDataLayer::name, NULL, CustomData::totlayer, and CustomDataLayer::type.
Referenced by CDDM_from_BMEditMesh(), DM_update_tessface_data(), getCCGDerivedMesh(), mesh_ensure_tessellation_customdata(), and mesh_recalcTessellation().
void* CustomData_get (const struct CustomData * data, int index, int type)
Referenced by bm_corners_to_loops(), ccg_loops_to_corners(), CustomData_set(), direct_link_mesh(), DM_get_edge_data(), DM_get_tessface_data(), DM_get_vert_data(), join_mesh_exec(), loops_to_customdata_corners(), and mesh_loops_to_mface_corners().
int CustomData_get_active_layer (const struct CustomData * data, int type)
Referenced by BMEdit_UpdateLinkedCustomData(), CustomData_bmesh_update_active_layers(), editmesh_face_copy_customdata(), and editmesh_loop_copy_customdata().
int CustomData_get_active_layer_index (const struct CustomData * data, int type)
Referenced by bc_CustomData_get_active_layer_name(), bpy_bmlayercollection_active_get(), convert_tfacematerial(), GeometryExporter::createVertexColorSource(), CustomData_bmesh_get(), CustomData_duplicate_referenced_layer(), CustomData_external_add(), CustomData_external_remove(), CustomData_external_test(), CustomData_free_layer_active(), CustomData_get(), CustomData_get_layer(), CustomData_is_referenced_layer(), CustomData_set_layer(), CustomData_validate_layer_name(), delete_customdata_layer(), DM_vertex_attributes_from_gpu(), do_version_tface(), ED_mesh_color_remove(), ED_mesh_uv_loop_reset(), ED_mesh_uv_texture_remove(), RE_inithalo_particle(), RE_sample_material_color(), and render_new_particle_system().
int CustomData_get_clone_layer (const struct CustomData * data, int type)
Referenced by BMEdit_UpdateLinkedCustomData(), CustomData_bmesh_update_active_layers(), and project_paint_begin().
int CustomData_get_clone_layer_index (const struct CustomData * data, int type)
Referenced by delete_customdata_layer().
void* CustomData_get_layer (const struct CustomData * data, int type)
Referenced by apply_heights_callback(), apply_tangmat_callback(), applyModifier(), BKE_mesh_calc_edges(), BKE_mesh_ensure_navmesh(), bm_mdisps_space_set(), buildRawVertIndicesData(), KX_NavMeshObject::BuildVertIndArrays(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), CDDM_calc_normals(), CDDM_calc_normals_mapping_ex(), CDDM_calc_normals_tessface(), cddm_copy_ex(), cdDM_drawFacesSolid(), cdDM_foreachMappedFaceCenter(), CDDM_from_BMEditMesh(), CDDM_from_mesh(), CDDM_from_template(), CDDM_new(), CDDM_recalc_tessellation_ex(), CDDM_tessfaces_to_faces(), cdDM_update_normals_from_pbvh(), count_images(), dm_calc_normal(), DM_get_edge_data_layer(), DM_get_loop_data_layer(), DM_get_poly_data_layer(), DM_get_tessface_data_layer(), DM_get_vert_data_layer(), dm_getEdgeArray(), dm_getLoopArray(), dm_getPolyArray(), dm_getTessFaceArray(), dm_getVertArray(), DM_init_origspace(), DM_to_mesh(), DM_update_tessface_data(), DM_update_weight_mcol(), doMirrorOnAxis(), dynamicPaint_Modifier_apply(), ED_mesh_update(), ED_operator_uvmap_mesh(), get_levels_from_disps(), get_particle_uv(), getCCGDerivedMesh(), mesh_recalcTessellation(), mesh_update_customdata_pointers(), multires_apply_smat(), multires_del_higher(), multires_load_old_250(), multires_load_old_vcols(), multires_modifier_update_hidden(), multires_modifier_update_mdisps(), multires_output_hidden_to_ccgdm(), multires_set_space(), multires_set_tot_mdisps(), multires_subdivide(), multires_topology_changed(), multiresbake_startjob(), multiresModifier_del_levels(), multiresModifier_disp_run(), multiresModifier_set_levels_from_disps(), paintface_flush_flags(), psys_get_dupli_texture(), psys_particle_on_dm(), sculpt_multires_active(), vertex_paint_use_fast_update_check(), vertex_paint_use_tessface_check(), and vpaint_build_poly_facemap().
int CustomData_get_layer_index (const struct CustomData * data, int type)
Referenced by MeshImporter::assign_textures_to_uvlayer(), bc_CustomData_get_layer_name(), bpy_bmlayercollection_active_get(), bpy_bmlayercollection_get(), bpy_bmlayercollection_items(), bpy_bmlayercollection_keys(), bpy_bmlayercollection_subscript_str(), bpy_bmlayercollection_values(), customData_add_layer__internal(), CustomData_bmesh_get_n(), CustomData_free_layer(), CustomData_get_layer_index_n(), CustomData_has_layer(), delete_customdata_layer(), DM_add_tangent_layer(), DM_vertex_attributes_from_gpu(), do_multires_bake(), emDM_getTessFaceDataArray(), init_render_mesh(), RE_inithalo_particle(), RE_sample_material_color(), and render_new_particle_system().
int CustomData_get_layer_index_n (const struct CustomData * data, int type, int n)
Definition at line 1284 of file customdata.c.
References CustomData_get_layer_index(), i, CustomData::layers, and CustomDataLayer::type.
Referenced by add_shapekey_layers(), BM_data_layer_free_n(), BM_mesh_bm_from_me(), bpy_bmlayeritem_get(), CustomData_get_layer_n(), CustomData_set_layer_n(), CustomData_set_layer_name(), and shapekey_layers_to_keyblocks().
void* CustomData_get_layer_n (const struct CustomData * data, int type, int n)
Referenced by GeometryExporter::createTexcoordsSource(), doMirrorOnAxis(), ED_mesh_uv_loop_reset_ex(), get_particle_uvco_mcol(), project_paint_begin(), remap_uvs_15(), remap_uvs_19_21_22(), remap_uvs_23(), remap_uvs_3_6_9_12(), remap_uvs_5_10(), remap_uvs_7_11_13_14(), set_subsurf_uv(), and shapekey_layers_to_keyblocks().
void* CustomData_get_layer_named (const struct CustomData * data, int type, const char * name)
Definition at line 1997 of file customdata.c.
References CustomData_get_named_layer_index(), CustomDataLayer::data, CustomData::layers, and NULL.
Referenced by MeshImporter::assign_material_to_geom(), dynamicPaint_createUVSurface(), dynamicPaint_findNeighbourPixel(), dynamicPaint_Modifier_apply(), dynamicPaint_setInitialColor(), EDBM_verts_mirror_cache_begin(), explodeMesh(), get_particle_uv(), and get_texture_coords().
void* CustomData_get_n (const struct CustomData * data, int type, int index, int n)
Referenced by bm_corners_to_loops(), ccg_loops_to_corners(), loops_to_customdata_corners(), and mesh_loops_to_mface_corners().
int CustomData_get_named_layer_index (const struct CustomData * data, int type, const char * name)
Referenced by bpy_bmlayercollection_contains(), bpy_bmlayercollection_get(), bpy_bmlayercollection_subscript_str(), CustomData_duplicate_referenced_layer_named(), CustomData_get_layer_named(), CustomData_validate_layer_name(), DM_vertex_attributes_from_gpu(), dynamicPaint_outputLayerExists(), ED_mesh_color_remove_named(), EDBM_verts_mirror_cache_begin(), RE_inithalo_particle(), and render_new_particle_system().
int CustomData_get_render_layer (const struct CustomData * data, int type)
Referenced by BMEdit_UpdateLinkedCustomData(), and CustomData_bmesh_update_active_layers().
int CustomData_get_render_layer_index (const struct CustomData * data, int type)
Referenced by delete_customdata_layer().
int CustomData_get_stencil_layer (const struct CustomData * data, int type)
Referenced by BMEdit_UpdateLinkedCustomData(), CustomData_bmesh_update_active_layers(), and project_paint_begin().
int CustomData_get_stencil_layer_index (const struct CustomData * data, int type)
Referenced by delete_customdata_layer().
int CustomData_has_layer (const struct CustomData * data, int type)
Referenced by applyModifier(), BKE_mesh_ensure_navmesh(), bm_corners_to_loops(), BM_edge_split(), BM_face_multires_bounds_smooth(), BM_face_split(), BM_faces_join(), BM_loop_interp_from_face(), bm_loop_interp_mdisps(), bm_loop_reverse_loop(), bm_mdisps_space_set(), BM_mesh_bm_from_me(), bm_to_mesh_vertex_map(), BMEdit_UpdateLinkedCustomData(), bmesh_edit_begin(), bmesh_edit_end(), bmo_bevel_exec(), bmo_face_reversecolors_exec(), bmo_face_reverseuvs_exec(), bmo_face_rotateuvs_exec(), bmo_rotatecolors_exec(), bmo_similaredges_exec(), bmo_similarfaces_exec(), bmo_similarverts_exec(), bmvert_to_mvert(), CDDM_calc_normals_mapping_ex(), CDDM_from_BMEditMesh(), CDDM_from_mesh(), CDDM_set_medge(), CDDM_set_mface(), CDDM_set_mloop(), CDDM_set_mpoly(), CDDM_set_mvert(), GeometryExporter::createVertexColorSource(), customData_add_layer__internal(), CustomData_bmesh_update_active_layers(), CustomData_free_layers(), delete_customdata_layer(), DM_DupPolys(), DM_ensure_tessface(), DM_to_bmesh_ex(), DM_to_mesh(), DM_update_tessface_data(), doMirrorOnAxis(), draw_em_fancy(), draw_mesh_textured_old(), draw_uvs_dm_shadow(), ED_mesh_uv_loop_reset_ex(), ED_uvedit_assign_image(), ED_uvedit_ensure_uvs(), ED_uvedit_live_unwrap(), ED_vgroup_give_parray(), ED_vgroup_mirror(), EDBM_mtexpoly_check(), EDBM_vert_color_check(), editbmesh_calc_modifiers(), emDM_copyEdgeArray(), emDM_copyVertArray(), emDM_drawFacesTex_common(), emDM_getEdge(), get_texture_coords(), getCCGDerivedMesh(), getEditDerivedBMesh(), loops_to_customdata_corners(), mesh_add_edges(), mesh_add_loops(), mesh_add_polys(), mesh_add_tessfaces(), mesh_add_verts(), mesh_calc_modifiers(), mesh_recalcTessellation(), multiresModifier_disp_run(), navmesh_face_add_exec(), navmesh_face_copy_exec(), navmesh_obmode_data_poll(), GeometryExporter::operator()(), project_paint_begin(), RE_set_customdata_names(), shape_itemf(), shape_propagate(), texture_paint_init(), CcdShapeConstructionInfo::UpdateMesh(), uvprojectModifier_do(), and vgroup_assign_verts().
void CustomData_interp (const struct CustomData * source, struct CustomData * dest, int * src_indices, float * weights, float * sub_weights, int count, int dest_index)
Referenced by DM_interp_edge_data(), DM_interp_loop_data(), DM_interp_poly_data(), DM_interp_tessface_data(), DM_interp_vert_data(), getCCGDerivedMesh(), and InterpCSGFace().
int CustomData_is_referenced_layer (struct CustomData * data, int type)
Definition at line 1739 of file customdata.c.
References CD_FLAG_NOFREE, CustomData_get_active_layer_index(), CustomDataLayer::flag, and CustomData::layers.
Referenced by CDDM_calc_normals_mapping().
int CustomData_layer_has_math (struct CustomData * data, int layer_n)
Checks if the layer at physical offset layer_n (in data->layers) support math the below operations.
Definition at line 2335 of file customdata.c.
References LayerTypeInfo::add, LayerTypeInfo::dominmax, LayerTypeInfo::equal, LayerTypeInfo::initminmax, CustomData::layers, layerType_getInfo(), LayerTypeInfo::multiply, and CustomDataLayer::type.
Referenced by bmo_collapse_uvs_exec(), bmo_pointmerge_facedata_exec(), and bmo_vert_average_facedata_exec().
const char* CustomData_layertype_name (int type)
Definition at line 2596 of file customdata.c.
References layerType_getName().
Referenced by dm_debug_info_layers().
void CustomData_merge (const struct CustomData * source, struct CustomData * dest, CustomDataMask mask, int alloctype, int totelem)
Definition at line 1146 of file customdata.c.
References CustomDataLayer::active, CustomDataLayer::active_clone, CustomDataLayer::active_mask, CustomDataLayer::active_rnd, CD_ASSIGN, CD_DUPLICATE, CD_FLAG_EXTERNAL, CD_FLAG_IN_MEMORY, CD_FLAG_NOCOPY, CD_FLAG_NOFREE, CD_REFERENCE, CD_TYPE_AS_MASK, customData_add_layer__internal(), CustomData_number_of_layers(), CustomData_update_typemap(), data, CustomDataLayer::data, CustomDataLayer::flag, i, CustomData::layers, CustomDataLayer::name, NULL, CustomData::totlayer, CustomDataLayer::type, and CustomDataLayer::uid.
Referenced by CDDM_from_BMEditMesh(), CDDM_from_mesh(), CDDM_tessfaces_to_faces(), ConvertCSGDescriptorsToDerivedMesh(), CustomData_bmesh_merge(), CustomData_copy(), and join_mesh_exec().
int CustomData_number_of_layers (const struct CustomData * data, int type)
Referenced by InstanceWriter::add_material_bindings(), alter_co(), BKE_mesh_convert_mfaces_to_mpolys(), BM_mesh_bm_from_me(), bmo_edgebisect_exec(), bmo_esubd_exec(), bmo_mirror_exec(), bpy_bmlayercollection_items(), bpy_bmlayercollection_keys(), bpy_bmlayercollection_length(), bpy_bmlayercollection_new(), bpy_bmlayercollection_values(), CDDM_from_BMEditMesh(), GeometryExporter::createPolylist(), GeometryExporter::createTexcoordsSource(), CustomData_merge(), cutEdges(), DM_update_tessface_data(), doMirrorOnAxis(), ED_mesh_color_add(), ED_mesh_uv_texture_add(), edbm_bevel_exec(), edbm_blend_from_shape_exec(), getActiveUVLayerName(), getCCGDerivedMesh(), mesh_ensure_tessellation_customdata(), mesh_recalcTessellation(), RE_sample_material_color(), RE_set_customdata_names(), render_new_particle_system(), shape_propagate(), and shapekey_layers_to_keyblocks().
void CustomData_set (const struct CustomData * data, int index, int type, void * source)
Referenced by DM_set_edge_data(), DM_set_tessface_data(), and DM_set_vert_data().
void* CustomData_set_layer (const struct CustomData * data, int type, void * ptr)
Referenced by BM_mesh_bm_to_me().
void CustomData_set_layer_active (struct CustomData * data, int type, int n)
Definition at line 1395 of file customdata.c.
References CustomDataLayer::active, i, CustomData::layers, CustomData::totlayer, and CustomDataLayer::type.
Referenced by BMEdit_UpdateLinkedCustomData(), CustomData_bmesh_update_active_layers(), delete_customdata_layer(), ED_mesh_color_add(), and ED_mesh_uv_texture_add().
void CustomData_set_layer_active_index (struct CustomData * data, int type, int n)
Definition at line 1432 of file customdata.c.
References CustomDataLayer::active, i, CustomData::layers, CustomData::totlayer, and CustomDataLayer::type.
void CustomData_set_layer_clone (struct CustomData * data, int type, int n)
Definition at line 1413 of file customdata.c.
References CustomDataLayer::active_clone, i, CustomData::layers, CustomData::totlayer, and CustomDataLayer::type.
Referenced by BMEdit_UpdateLinkedCustomData(), CustomData_bmesh_update_active_layers(), and delete_customdata_layer().
void CustomData_set_layer_clone_index (struct CustomData * data, int type, int n)
Definition at line 1450 of file customdata.c.
References CustomDataLayer::active_clone, i, CustomData::layers, CustomData::totlayer, and CustomDataLayer::type.
void CustomData_set_layer_flag (struct CustomData * data, int type, int flag)
Definition at line 1468 of file customdata.c.
References CustomDataLayer::flag, i, CustomData::layers, CustomData::totlayer, and CustomDataLayer::type.
Referenced by dm_getEdgeArray(), dm_getLoopArray(), dm_getPolyArray(), dm_getTessFaceArray(), and dm_getVertArray().
void* CustomData_set_layer_n (const struct CustomData * data, int type, int n, void * ptr)
Definition at line 2032 of file customdata.c.
References CustomData_get_layer_index_n(), CustomDataLayer::data, CustomData::layers, and NULL.
int CustomData_set_layer_name (const struct CustomData * data, int type, int n, const char * name)
Referenced by BM_mesh_bm_from_me().
void CustomData_set_layer_render (struct CustomData * data, int type, int n)
Definition at line 1404 of file customdata.c.
References CustomDataLayer::active_rnd, i, CustomData::layers, CustomData::totlayer, and CustomDataLayer::type.
Referenced by BMEdit_UpdateLinkedCustomData(), CustomData_bmesh_update_active_layers(), and delete_customdata_layer().
void CustomData_set_layer_render_index (struct CustomData * data, int type, int n)
Definition at line 1441 of file customdata.c.
References CustomDataLayer::active_rnd, i, CustomData::layers, CustomData::totlayer, and CustomDataLayer::type.
void CustomData_set_layer_stencil (struct CustomData * data, int type, int n)
Definition at line 1422 of file customdata.c.
References CustomDataLayer::active_mask, i, CustomData::layers, CustomData::totlayer, and CustomDataLayer::type.
Referenced by BMEdit_UpdateLinkedCustomData(), CustomData_bmesh_update_active_layers(), and delete_customdata_layer().
void CustomData_set_layer_stencil_index (struct CustomData * data, int type, int n)
Definition at line 1459 of file customdata.c.
References CustomDataLayer::active_mask, i, CustomData::layers, CustomData::totlayer, and CustomDataLayer::type.
void CustomData_set_layer_unique_name (struct CustomData * data, int index)
Definition at line 2638 of file customdata.c.
References BLI_uniquename_cb(), customdata_unique_check(), data, LayerTypeInfo::defaultname, CustomData::layers, layerType_getInfo(), CustomDataLayer::name, and CustomDataLayer::type.
Referenced by customData_add_layer__internal().
void CustomData_set_only_copy (const struct CustomData * data, CustomDataMask mask)
Definition at line 1778 of file customdata.c.
References CD_FLAG_NOCOPY, CD_TYPE_AS_MASK, CustomDataLayer::flag, i, CustomData::layers, CustomData::totlayer, and CustomDataLayer::type.
Referenced by DM_set_only_copy().
int CustomData_sizeof (int type)
Definition at line 2589 of file customdata.c.
References layerType_getInfo(), and LayerTypeInfo::size.
Referenced by dm_debug_info_layers(), edbm_sort_faces_exec(), and emDM_getTessFaceDataArray().
void CustomData_swap (struct CustomData * data, int index, const int * corner_indices)
Definition at line 1935 of file customdata.c.
References CustomDataLayer::data, i, CustomData::layers, layerType_getInfo(), LayerTypeInfo::size, LayerTypeInfo::swap, CustomData::totlayer, and CustomDataLayer::type.
Referenced by DM_swap_tessface_data(), and test_index_face().
void CustomData_to_bmesh_block (const struct CustomData * source, struct CustomData * dest, int src_index, void ** dest_block)
Referenced by BM_mesh_bm_from_me(), and DM_to_bmesh_ex().
void CustomData_to_bmeshpoly (struct CustomData * fdata, struct CustomData * pdata, struct CustomData * ldata, int totloop, int totpoly)
Definition at line 2058 of file customdata.c.
References CD_CALLOC, CD_MCOL, CD_MDISPS, CD_MLOOPCOL, CD_MLOOPUV, CD_MTEXPOLY, CD_MTFACE, CustomData_add_layer_named(), i, CustomData::layers, CustomDataLayer::name, NULL, CustomData::totlayer, and CustomDataLayer::type.
Referenced by BKE_mesh_convert_mfaces_to_mpolys().
void CustomData_update_typemap (struct CustomData * data)
Definition at line 1127 of file customdata.c.
References BLI_assert, CD_NUMTYPES, i, CustomData::layers, CustomData::totlayer, CustomDataLayer::type, and CustomData::typemap.
Referenced by CustomData_add_layer(), CustomData_add_layer_named(), CustomData_free_layer(), CustomData_merge(), customData_update_offsets(), and direct_link_customdata().
void CustomData_validate_layer_name (const struct CustomData * data, int type, char * name, char * outname)
Referenced by dynamicPaint_createUVSurface(), dynamicPaint_setInitialColor(), get_texture_coords(), and uvprojectModifier_do().
int CustomData_verify_versions (struct CustomData * data, int index)
Definition at line 2673 of file customdata.c.
References CD_NUMTYPES, LayerTypeInfo::defaultname, i, CustomData::layers, layerType_getInfo(), CustomData::totlayer, and CustomDataLayer::type.
Referenced by direct_link_customdata().
Variable Documentation
const CustomDataMask CD_MASK_BAREMESH
Definition at line 1080 of file customdata.c.
Referenced by add_verts_to_dgroups(), brush_add(), connect_hair(), crazyspace_get_mapped_editverts(), dm_deform_recalc(), draw_mesh_text(), draw_object_backbufsel(), draw_object_mesh_instance(), draw_uvs(), dupli_render_particle_set(), ED_view3d_screen_datamask(), face_duplilist(), facesel_face_pick(), get_multires_dm(), hide_show_exec(), imapaint_pick_uv(), init_render_mesh(), init_render_object_data(), initElbeemMesh(), join_mesh_shapes_exec(), mesh_deform_bind(), mesh_foreachScreenEdge(), mesh_foreachScreenFace(), mesh_foreachScreenVert(), mesh_get_mapped_verts_nors(), multires_apply_smat(), multires_modifier_update_mdisps(), multires_subdivide(), multiresModifier_base_apply(), multiresModifier_reshape(), NewBooleanMesh(), object_handle_update(), GeometryExporter::operator()(), peelObjects(), pointdensity_cache_object(), pointdensity_cache_psys(), sculpt_update_mesh_elements(), snapObject(), vertex_duplilist(), vertex_parent_set_exec(), vgroup_fix(), and weight_sample_invoke().
const CustomDataMask CD_MASK_BMESH
Definition at line 1100 of file customdata.c.
Referenced by BM_mesh_bm_from_me(), BM_mesh_copy(), and mesh_separate_selected().
const CustomDataMask CD_MASK_DERIVEDMESH
Definition at line 1093 of file customdata.c.
Referenced by BMBVH_NewBVH(), CDDM_from_BMEditMesh(), ConvertCSGDescriptorsToDerivedMesh(), DM_DupPolys(), DM_from_template(), DM_to_bmesh_ex(), and knifetool_init().
const CustomDataMask CD_MASK_EDITMESH
Definition at line 1088 of file customdata.c.
const CustomDataMask CD_MASK_FACECORNERS
Definition at line 1103 of file customdata.c.
const CustomDataMask CD_MASK_MESH
Definition at line 1082 of file customdata.c.
Referenced by arrayModifier_doArray(), BM_mesh_bm_to_me(), KX_NavMeshObject::BuildVertIndArrays(), CDDM_from_mesh(), convert_exec(), copy_mesh(), createVertsTrisData(), DM_to_mesh(), BL_ModifierDeformer::GetPhysicsMesh(), join_mesh_exec(), mesh_add_edges(), mesh_add_loops(), mesh_add_polys(), mesh_add_tessfaces(), mesh_add_verts(), mesh_to_curve(), mesh_validate_customdata(), multires_external_save_exec(), BL_ModifierDeformer::Update(), and write_customdata().