Blender: LOD_NdQuadricEditor Class Reference
LOD_NdQuadricEditor Class Reference
#include <LOD_NdQuadricEditor.h>
Public Member Functions
void Remove (const std::vector< LOD_VertexInd > &sorted_vertices)
std::vector< LOD_NdQuadric > & Quadrics () const
bool BuildQuadrics (const LOD_ExternNormalEditor &normal_editor, bool preserve_boundaries)
void InitializeHeapKeys (const LOD_ExternVColorEditor &color_editor)
void ComputeEdgeCosts (const std::vector< LOD_EdgeInd > &edges, const LOD_ExternVColorEditor &color_editor)
void TargetVertex (const LOD_Edge &e, TNT::Vector< MT_Scalar > &result, const LOD_ExternVColorEditor &color_editor) const
~LOD_NdQuadricEditor ()
Static Public Member Functions
static LOD_NdQuadricEditor * New (LOD_ManMesh2 &mesh)
Detailed Description
Definition at line 45 of file LOD_NdQuadricEditor.h.
Constructor & Destructor Documentation
LOD_NdQuadricEditor::~LOD_NdQuadricEditor () [inline]
Definition at line 102 of file LOD_NdQuadricEditor.h.
Member Function Documentation
bool LOD_NdQuadricEditor::BuildQuadrics (const LOD_ExternNormalEditor & normal_editor, bool preserve_boundaries)
Definition at line 100 of file LOD_NdQuadricEditor.cpp.
References MT_Vector3::cross(), MT_Vector3::dot(), LOD_ManMesh2::EdgeSet(), CTR_TaggedIndex< 24, 0x00ffffff >::Empty(), LOD_ManMesh2::FaceSet(), MT_Vector3::fuzzyZero(), MT_Vector3::length(), MT_Vector3::normalize(), LOD_ExternNormalEditor::Normals(), NULL, and LOD_ManMesh2::VertexSet().
void LOD_NdQuadricEditor::ComputeEdgeCosts (const std::vector< LOD_EdgeInd > & edges, const LOD_ExternVColorEditor & color_editor)
void LOD_NdQuadricEditor::InitializeHeapKeys (const LOD_ExternVColorEditor & color_editor)
Definition at line 193 of file LOD_NdQuadricEditor.cpp.
References LOD_ManMesh2::EdgeSet(), LOD_NdQuadric::Evaluate(), CTR_UHeapable::HeapKey(), LOD_ExternVColorEditor::IndexColor(), LOD_Edge::m_verts, and TargetVertex().
LOD_NdQuadricEditor * LOD_NdQuadricEditor::New (LOD_ManMesh2 & mesh) [static]
Definition at line 54 of file LOD_NdQuadricEditor.cpp.
References NULL.
Referenced by LOD_NdQSDecimator::New().
std::vector<LOD_NdQuadric>& LOD_NdQuadricEditor::Quadrics () const [inline]
Definition at line 68 of file LOD_NdQuadricEditor.h.
void LOD_NdQuadricEditor::Remove (const std::vector< LOD_VertexInd > & sorted_vertices)
Definition at line 73 of file LOD_NdQuadricEditor.cpp.
void LOD_NdQuadricEditor::TargetVertex (const LOD_Edge & e, TNT::Vector< MT_Scalar > & result, const LOD_ExternVColorEditor & color_editor) const
Definition at line 237 of file LOD_NdQuadricEditor.cpp.
References LOD_ExternVColorEditor::IndexColor(), LOD_Edge::m_verts, LOD_NdQuadric::Optimize(), and LOD_ManMesh2::VertexSet().
Referenced by LOD_QuadricEditor::ComputeEdgeCosts(), and InitializeHeapKeys().
The documentation for this class was generated from the following files:
LOD_NdQuadricEditor.h
LOD_NdQuadricEditor.cpp