Blender: BL_ActionManager Class Reference
BL_ActionManager Class Reference
#include <BL_ActionManager.h>
Public Member Functions
BL_ActionManager (class KX_GameObject *obj)
~BL_ActionManager ()
bool PlayAction (const char *name, float start, float end, short layer=0, short priority=0, float blendin=0.f, short play_mode=0, float layer_weight=0.f, short ipo_flags=0, float playback_speed=1.f)
float GetActionFrame (short layer)
void SetActionFrame (short layer, float frame)
struct bAction * GetCurrentAction (short layer)
void SetPlayMode (short layer, short mode)
void SetTimes (short layer, float start, float end)
void StopAction (short layer)
bool IsActionDone (short layer)
void Update (float)
Detailed Description
BL_ActionManager is responsible for handling a KX_GameObject's actions.
Definition at line 37 of file BL_ActionManager.h.
Constructor & Destructor Documentation
BL_ActionManager::BL_ActionManager (class KX_GameObject * obj)
Definition at line 29 of file BL_ActionManager.cpp.
References i, and MAX_ACTION_LAYERS.
BL_ActionManager::~BL_ActionManager ()
Definition at line 35 of file BL_ActionManager.cpp.
References i, and MAX_ACTION_LAYERS.
Member Function Documentation
float BL_ActionManager::GetActionFrame (short layer)
Gets the current frame of an action
Definition at line 41 of file BL_ActionManager.cpp.
References BL_Action::GetFrame().
Referenced by KX_GameObject::GetActionFrame().
struct bAction * BL_ActionManager::GetCurrentAction (short layer) [read]
Gets the currently running action on the given layer
Definition at line 53 of file BL_ActionManager.cpp.
References BL_Action::GetAction().
Referenced by KX_GameObject::GetCurrentAction().
bool BL_ActionManager::IsActionDone (short layer)
Check if an action has finished playing
Definition at line 92 of file BL_ActionManager.cpp.
References BL_Action::IsDone().
Referenced by KX_GameObject::IsActionDone().
bool BL_ActionManager::PlayAction (const char * name, float start, float end, short layer = 0, short priority = 0, float blendin = 0.f, short play_mode = 0, float layer_weight = 0.f, short ipo_flags = 0, float playback_speed = 1.f)
Definition at line 70 of file BL_ActionManager.cpp.
References BL_Action::Play().
Referenced by KX_GameObject::PlayAction().
void BL_ActionManager::SetActionFrame (short layer, float frame)
Sets the current frame of an action
Definition at line 48 of file BL_ActionManager.cpp.
References BL_Action::SetFrame().
Referenced by KX_GameObject::SetActionFrame().
void BL_ActionManager::SetPlayMode (short layer, short mode)
Sets play mode of the action on the given layer
Definition at line 60 of file BL_ActionManager.cpp.
References BL_Action::SetPlayMode().
Referenced by KX_GameObject::SetPlayMode().
void BL_ActionManager::SetTimes (short layer, float start, float end)
Sets the start and end times of the action on the given layer
Definition at line 65 of file BL_ActionManager.cpp.
References BL_Action::SetTimes().
Referenced by KX_GameObject::SetTimes().
void BL_ActionManager::StopAction (short layer)
Stop playing the action on the given layer
Definition at line 87 of file BL_ActionManager.cpp.
References BL_Action::Stop().
Referenced by KX_GameObject::StopAction().
void BL_ActionManager::Update (float curtime)
Update any running actions
Definition at line 99 of file BL_ActionManager.cpp.
References i, MAX_ACTION_LAYERS, and BL_Action::Update().
Referenced by KX_GameObject::UpdateActionManager().
The documentation for this class was generated from the following files:
BL_ActionManager.h
BL_ActionManager.cpp