Blender: RE_pipeline.h File Reference
RE_pipeline.h File Reference
Rendering
#include "DNA_listBase.h"
#include "DNA_vec_types.h"
Classes
struct RenderPass
struct RenderLayer
struct RenderResult
struct RenderStats
Defines
#define RE_MAXNAME 32
#define RE_BAKE_LIGHT 0
#define RE_BAKE_ALL 1
#define RE_BAKE_AO 2
#define RE_BAKE_NORMALS 3
#define RE_BAKE_TEXTURE 4
#define RE_BAKE_DISPLACEMENT 5
#define RE_BAKE_SHADOW 6
#define RE_BAKE_SPEC_COLOR 7
#define RE_BAKE_SPEC_INTENSITY 8
#define RE_BAKE_MIRROR_COLOR 9
#define RE_BAKE_MIRROR_INTENSITY 10
#define RE_BAKE_ALPHA 11
#define RE_BAKE_EMIT 12
Typedefs
typedef struct Render Render
typedef struct RenderPass RenderPass
typedef struct RenderLayer RenderLayer
typedef struct RenderResult RenderResult
typedef struct RenderStats RenderStats
Functions
struct Render * RE_NewRender (const char *name)
struct Render * RE_GetRender (const char *name)
int RE_RenderInProgress (struct Render *re)
void RE_InitRenderCB (struct Render *re)
void RE_FreeRender (struct Render *re)
void RE_FreeAllRender (void)
void RE_FreeAllRenderResults (void)
void RE_FreeRenderResult (struct RenderResult *rr)
struct RenderResult * RE_AcquireResultRead (struct Render *re)
struct RenderResult * RE_AcquireResultWrite (struct Render *re)
void RE_ReleaseResult (struct Render *re)
void RE_AcquireResultImage (struct Render *re, struct RenderResult *rr)
void RE_ReleaseResultImage (struct Render *re)
void RE_SwapResult (struct Render *re, struct RenderResult **rr)
struct RenderStats * RE_GetStats (struct Render *re)
void RE_ResultGet32 (struct Render *re, unsigned int *rect)
struct RenderLayer * RE_GetRenderLayer (struct RenderResult *rr, const char *name)
float * RE_RenderLayerGetPass (struct RenderLayer *rl, int passtype)
void RE_InitState (struct Render *re, struct Render *source, struct RenderData *rd, struct SceneRenderLayer *srl, int winx, int winy, rcti *disprect)
struct Object * RE_GetCamera (struct Render *re)
void RE_SetCamera (struct Render *re, struct Object *camera)
void RE_SetEnvmapCamera (struct Render *re, struct Object *cam_ob, float viewscale, float clipsta, float clipend)
void RE_SetWindow (struct Render *re, rctf *viewplane, float clipsta, float clipend)
void RE_SetOrtho (struct Render *re, rctf *viewplane, float clipsta, float clipend)
void RE_SetPixelSize (struct Render *re, float pixsize)
void RE_SetView (struct Render *re, float mat[][4])
void RE_Database_FromScene (struct Render *re, struct Main *bmain, struct Scene *scene, unsigned int lay, int use_camera_view)
void RE_Database_Free (struct Render *re)
void RE_DataBase_ApplyWindow (struct Render *re)
void RE_set_max_threads (int threads)
void RE_init_threadcount (Render *re)
void RE_TileProcessor (struct Render *re)
void RE_BlenderFrame (struct Render *re, struct Main *bmain, struct Scene *scene, struct SceneRenderLayer *srl, struct Object *camera_override, unsigned int lay, int frame, const short write_still)
void RE_BlenderAnim (struct Render *re, struct Main *bmain, struct Scene *scene, struct Object *camera_override, unsigned int lay, int sfra, int efra, int tfra)
void RE_SetReports (struct Render *re, struct ReportList *reports)
void RE_PreviewRender (struct Render *re, struct Main *bmain, struct Scene *scene)
int RE_ReadRenderResult (struct Scene *scene, struct Scene *scenode)
int RE_WriteRenderResult (struct ReportList *reports, RenderResult *rr, const char *filename, int compress)
struct RenderResult * RE_MultilayerConvert (void *exrhandle, int rectx, int recty)
int RE_WriteEnvmapResult (struct ReportList *reports, struct Scene *scene, struct EnvMap *env, const char *relpath, const char imtype, float layout[12])
void RE_MergeFullSample (struct Render *re, struct Main *bmain, struct Scene *sce, struct bNodeTree *ntree)
void RE_make_stars (struct Render *re, struct Scene *scenev3d, void(*initfunc)(void), void(*vertexfunc)(float *), void(*termfunc)(void))
void RE_display_init_cb (struct Render *re, void *handle, void(*f)(void *handle, RenderResult *rr))
void RE_display_clear_cb (struct Render *re, void *handle, void(*f)(void *handle, RenderResult *rr))
void RE_display_draw_cb (struct Render *re, void *handle, void(*f)(void *handle, RenderResult *rr, volatile struct rcti *rect))
void RE_stats_draw_cb (struct Render *re, void *handle, void(*f)(void *handle, RenderStats *rs))
void RE_progress_cb (struct Render *re, void *handle, void(*f)(void *handle, float))
void RE_draw_lock_cb (struct Render *re, void *handle, void(*f)(void *handle, int))
void RE_test_break_cb (struct Render *re, void *handle, int(*f)(void *handle))
float RE_filter_value (int type, float x)
void RE_zbuf_accumulate_vecblur (struct NodeBlurData *nbd, int xsize, int ysize, float *newrect, float *imgrect, float *vecbufrect, float *zbufrect)
int RE_seq_render_active (struct Scene *scene, struct RenderData *rd)
void RE_Database_Baking (struct Render *re, struct Main *bmain, struct Scene *scene, unsigned int lay, const int type, struct Object *actob)
void RE_DataBase_GetView (struct Render *re, float mat[][4])
void RE_GetCameraWindow (struct Render *re, struct Object *camera, int frame, float mat[][4])
struct Scene * RE_GetScene (struct Render *re)
int RE_is_rendering_allowed (struct Scene *scene, struct Object *camera_override, struct ReportList *reports)
Variables
const float default_envmap_layout []
Detailed Description
Definition in file RE_pipeline.h.
Define Documentation
#define RE_BAKE_ALL 1
Definition at line 256 of file RE_pipeline.h.
Referenced by bake_shade(), RE_Database_Baking(), and rna_def_scene_render_data().
#define RE_BAKE_ALPHA 11
Definition at line 266 of file RE_pipeline.h.
Referenced by bake_shade(), and rna_def_scene_render_data().
#define RE_BAKE_AO 2
Definition at line 257 of file RE_pipeline.h.
Referenced by bake_shade(), finish_bake_internal(), init_bake_internal(), RE_Database_Baking(), rna_def_scene_render_data(), and test_bake_internal().
#define RE_BAKE_DISPLACEMENT 5
Definition at line 260 of file RE_pipeline.h.
Referenced by bake_images(), do_bake_shade(), is_multires_bake(), RE_Database_Baking(), and rna_def_scene_render_data().
#define RE_BAKE_EMIT 12
Definition at line 267 of file RE_pipeline.h.
Referenced by bake_shade(), and rna_def_scene_render_data().
#define RE_BAKE_LIGHT 0
Definition at line 255 of file RE_pipeline.h.
Referenced by bake_shade(), and RE_Database_Baking().
#define RE_BAKE_MIRROR_COLOR 9
Definition at line 264 of file RE_pipeline.h.
Referenced by bake_shade(), and rna_def_scene_render_data().
#define RE_BAKE_MIRROR_INTENSITY 10
Definition at line 265 of file RE_pipeline.h.
Referenced by bake_shade(), and rna_def_scene_render_data().
#define RE_BAKE_NORMALS 3
Definition at line 258 of file RE_pipeline.h.
Referenced by bake_images(), bake_shade(), do_bake_shade(), is_multires_bake(), RE_Database_Baking(), and rna_def_scene_render_data().
#define RE_BAKE_SHADOW 6
Definition at line 261 of file RE_pipeline.h.
Referenced by bake_shade(), RE_bake_shade_all_selected(), RE_Database_Baking(), and rna_def_scene_render_data().
#define RE_BAKE_SPEC_COLOR 7
Definition at line 262 of file RE_pipeline.h.
Referenced by bake_shade(), and rna_def_scene_render_data().
#define RE_BAKE_SPEC_INTENSITY 8
Definition at line 263 of file RE_pipeline.h.
Referenced by bake_shade(), and rna_def_scene_render_data().
#define RE_BAKE_TEXTURE 4
Definition at line 259 of file RE_pipeline.h.
Referenced by bake_shade(), RE_Database_Baking(), and rna_def_scene_render_data().
#define RE_MAXNAME 32
Definition at line 55 of file RE_pipeline.h.
Referenced by RE_GetRender(), RE_GetRenderLayer(), RE_NewRender(), RENDER_OT_render(), and screen_render_scene_layer_set().
Typedef Documentation
typedef struct Render Render
Definition at line 58 of file RE_pipeline.h.
typedef struct RenderLayer RenderLayer
typedef struct RenderPass RenderPass
typedef struct RenderResult RenderResult
typedef struct RenderStats RenderStats
Function Documentation
void RE_AcquireResultImage (struct Render * re, struct RenderResult * rr)
Definition at line 295 of file pipeline.c.
References BLI_rw_mutex_lock(), RenderResult::have_combined, RenderResult::layers, NULL, RE_RenderLayerGetPass(), RenderResult::rect32, RenderLayer::rectf, RenderResult::rectf, RenderResult::rectx, RenderResult::recty, RenderResult::rectz, render_get_active_layer(), Render::result, Render::resultmutex, SCE_PASS_Z, and THREAD_LOCK_READ.
Referenced by do_merge_fullsample(), do_write_image_or_movie(), ed_preview_draw_rect(), image_get_render_result(), RE_ResultGet32(), renderresult_stampinfo(), and seq_render_scene_strip().
struct RenderResult* RE_AcquireResultRead (struct Render * re) [read]
Definition at line 251 of file pipeline.c.
References BLI_rw_mutex_lock(), NULL, Render::result, Render::resultmutex, and THREAD_LOCK_READ.
Referenced by BKE_image_acquire_renderresult(), image_renderinfo_cb(), node_composit_exec_rlayers(), screen_opengl_render_apply(), uiTemplateImage(), and uiTemplateImageLayers().
struct RenderResult* RE_AcquireResultWrite (struct Render * re) [read]
Definition at line 261 of file pipeline.c.
References BLI_rw_mutex_lock(), NULL, Render::result, Render::resultmutex, and THREAD_LOCK_WRITE.
Referenced by node_composit_exec_composite(), and screen_opengl_render_init().
void RE_BlenderAnim (struct Render * re, struct Main * bmain, struct Scene * scene, struct Object * camera_override, unsigned int lay, int sfra, int efra, int tfra)
Definition at line 2130 of file pipeline.c.
References BKE_get_movie_handle(), BKE_imtype_is_movie(), BKE_makepicstring(), BKE_report(), BLI_CB_EVT_RENDER_CANCEL, BLI_CB_EVT_RENDER_COMPLETE, BLI_CB_EVT_RENDER_POST, BLI_CB_EVT_RENDER_PRE, BLI_delete(), BLI_exec_cb(), BLI_exists(), BLI_file_size(), BLI_file_touch(), BLI_make_existing_file(), RenderData::cfra, do_render_all_options(), do_write_image_or_movie(), bMovieHandle::end_movie, FILE_MAX, Render::flag, G, bMovieHandle::get_next_frame, if(), RenderData::im_format, ImageFormatData::imtype, Render::lay, Render::main, RenderData::mode, ImBuf::name, Main::name, NULL, RenderData::pic, Scene::r, Render::r, R_ANIMATION, R_EXTENSION, R_NO_OVERWRITE, R_TOUCH, Render::rectx, Render::recty, render_initialize_from_main(), Render::reports, RPT_INFO, RenderData::scemode, scene_update_for_newframe(), RenderData::sfra, bMovieHandle::start_movie, Render::tbh, Render::test_break, and TRUE.
Referenced by render_animation(), render_frame(), render_startjob(), and screen_render_exec().
void RE_BlenderFrame (struct Render * re, struct Main * bmain, struct Scene * scene, struct SceneRenderLayer * srl, struct Object * camera_override, unsigned int lay, int frame, const short write_still)
Definition at line 2012 of file pipeline.c.
References BKE_imtype_is_movie(), BKE_makepicstring(), BLI_CB_EVT_RENDER_CANCEL, BLI_CB_EVT_RENDER_COMPLETE, BLI_CB_EVT_RENDER_POST, BLI_CB_EVT_RENDER_PRE, BLI_exec_cb(), RenderData::cfra, do_render_all_options(), do_write_image_or_movie(), FALSE, FILE_MAX, G, Render::main, MEM_reset_peak_memory(), ImBuf::name, Main::name, NULL, Scene::r, R_EXTENSION, and render_initialize_from_main().
Referenced by render_startjob(), screen_render_exec(), and seq_render_scene_strip().
void RE_DataBase_ApplyWindow (struct Render * re)
Definition at line 5175 of file convertblender.c.
References project_renderdata(), and projectverto().
void RE_Database_Baking (struct Render * re, struct Main * bmain, struct Scene * scene, unsigned int lay, const int type, struct Object * actob)
Definition at line 5705 of file convertblender.c.
References World::ambr, World::ao_gather_method, World::ao_samp_method, RenderData::bake_normal_space, BLI_memarena_new(), BLI_MEMARENA_STD_BUFSIZE, copy_m3_m4(), copy_v3_v3(), database_init_objects(), ELEM3, ELEM4, Render::excludeob, ListBase::first, Render::flag, Render::imat, init_ao_sphere(), init_render_materials(), init_render_qmcsampler(), init_render_textures(), init_render_world(), invert_m4_m4(), Render::lampren, ListBase::last, Render::lay, Render::lights, Render::main, make_occ_tree(), make_pointdensities(), make_voxeldata(), makeraytree(), Render::memArena, RenderData::mode, World::mode, normalize_m4(), NULL, Object::obmat, Scene::r, Render::r, R_BAKE_SPACE_TANGENT, R_BAKE_TRACE, R_BAKING, R_NEED_TANGENT, R_RAYTRACE, R_SHADOW, RE_BAKE_ALL, RE_BAKE_AO, RE_BAKE_DISPLACEMENT, RE_BAKE_LIGHT, RE_BAKE_NORMALS, RE_BAKE_SHADOW, RE_BAKE_TEXTURE, RE_GetCamera(), RE_init_threadcount(), RE_SetView(), Render::scene, set_material_lightgroups(), set_node_shader_lamp_loop(), shade_material_loop(), Render::tbh, Render::test_break, threaded_makeshadowbufs(), Render::tothalo, Render::totlamp, Render::totstrand, Render::totvert, Render::totvlak, unit_m4(), Render::viewinv, Render::winmat, Render::winx, Render::winy, WO_AMB_OCC, WO_AOGATHER_APPROX, WO_AOSAMP_CONSTANT, WO_ENV_LIGHT, WO_INDIRECT_LIGHT, and Render::wrld.
Referenced by bake_image_exec(), and bake_startjob().
void RE_Database_Free (struct Render * re)
Definition at line 4648 of file convertblender.c.
References World::aosphere, World::aotables, Render::bakebuf, BKE_image_free_all_textures(), BKE_image_print_memlist(), BLI_freelistN(), BLI_memarena_free(), RenderStats::convertdone, LampRen::curfalloff, curvemapping_free(), end_render_materials(), end_render_textures(), ListBase::first, free_camera_inside_volumes(), free_mesh_orco_hash(), free_occ(), free_pointdensities(), free_render_qmcsampler(), free_renderdata_tables(), free_sss(), free_strand_surface(), free_volume_precache(), freeraytree(), freeshadowbuf(), G, G_DEBUG, Render::i, LampRen::jitter, Render::lampren, Render::lights, Render::main, MEM_freeN(), MEM_printmemlist_stats(), Render::memArena, RenderData::mode, LampRen::next, NULL, Scene::r, Render::r, R_FREE_IMAGE, R_PREVIEWBUTS, R_RAYTRACE, RenderData::scemode, Render::scene, LampRen::shadsamp, LampRen::sunsky, Render::tothalo, Render::totlamp, Render::totstrand, Render::totvert, Render::totvlak, Scene::world, and Render::wrld.
Referenced by do_render_3d(), finish_bake_internal(), RE_Database_FromScene(), and RE_Database_FromScene_Vectors().
void RE_Database_FromScene (struct Render * re, struct Main * bmain, struct Scene * scene, unsigned int lay, int use_camera_view)
Definition at line 5025 of file convertblender.c.
References World::ambr, World::ao_gather_method, World::ao_samp_method, BLI_memarena_new(), BLI_MEMARENA_STD_BUFSIZE, BLI_strncpy(), RenderData::cfra, RenderStats::cfra, RenderStats::convertdone, copy_v3_v3(), database_init_objects(), ListBase::first, Render::i, Scene::id, RenderStats::infostr, init_ao_sphere(), init_camera_inside_volumes(), init_render_materials(), init_render_qmcsampler(), init_render_textures(), init_render_world(), invert_m4_m4(), Render::lampren, ListBase::last, Render::lay, Render::lights, Render::main, make_envmaps(), make_occ_tree(), make_pointdensities(), make_sss_tree(), make_voxeldata(), makeraytree(), Render::memArena, World::mode, RenderData::mode, ID::name, normalize_m4(), NULL, OB_RECALC_OB, Object::obmat, RenderStats::partsdone, project_renderdata(), projectverto(), Scene::r, Render::r, R_NO_FRAME_UPDATE, R_PANORAMA, R_PREVIEWBUTS, R_RAYTRACE, R_SHADOW, R_SSS, RE_Database_Free(), RE_GetCamera(), RE_make_stars(), RE_SetCamera(), RE_SetView(), Object::recalc, RenderData::scemode, Render::scene, scene_update_for_newframe(), RenderStats::scenename, Render::sdh, Scene::set, set_material_lightgroups(), set_node_shader_lamp_loop(), set_renderlayer_lightgroups(), shade_material_loop(), slurph_opt, sort_halos(), Render::stats_draw, Render::tbh, Render::test_break, threaded_makeshadowbufs(), RenderStats::totface, RenderStats::tothalo, Render::tothalo, RenderStats::totlamp, Render::totlamp, RenderStats::totstrand, Render::totstrand, RenderStats::totvert, Render::totvert, Render::totvlak, volume_precache(), WO_AMB_OCC, WO_AOGATHER_APPROX, WO_AOSAMP_CONSTANT, WO_ENV_LIGHT, WO_INDIRECT_LIGHT, WO_STARS, and Render::wrld.
Referenced by do_render_3d(), and RE_Database_FromScene_Vectors().
void RE_DataBase_GetView (struct Render * re, float mat[][4])
Definition at line 5180 of file convertblender.c.
References copy_m4_m4(), and Render::viewmat.
void RE_display_clear_cb (struct Render * re, void * handle, void(*)(void *handle, RenderResult *rr) f)
Definition at line 573 of file pipeline.c.
References Render::dch, and Render::display_clear.
void RE_display_draw_cb (struct Render * re, void * handle, void(*)(void *handle, RenderResult *rr, volatile struct rcti *rect) f)
Referenced by screen_render_invoke(), and shader_preview_render().
void RE_display_init_cb (struct Render * re, void * handle, void(*)(void *handle, RenderResult *rr) f)
Definition at line 568 of file pipeline.c.
References Render::dih, and Render::display_init.
void RE_draw_lock_cb (struct Render * re, void * handle, void(*)(void *handle, int) f)
Referenced by screen_render_invoke().
float RE_filter_value (int type, float x)
Definition at line 164 of file initrender.c.
References ABS, expf, filt_catrom(), filt_cubic(), filt_mitchell(), filt_quadratic(), R_FILTER_BOX, R_FILTER_CATROM, R_FILTER_CUBIC, R_FILTER_GAUSS, R_FILTER_MITCH, R_FILTER_QUAD, and R_FILTER_TENT.
Referenced by bokeh_single_image(), make_gausstab(), and make_jitter_weight_tab().
void RE_FreeAllRender (void)
Definition at line 406 of file pipeline.c.
References RE_FreeRender(), and RenderGlobal.
Referenced by WM_exit_ext().
void RE_FreeAllRenderResults (void)
Definition at line 414 of file pipeline.c.
References Render::next, NULL, Render::pushedresult, render_result_free(), RenderGlobal, and Render::result.
Referenced by setup_app_data().
void RE_FreeRender (struct Render * re)
Definition at line 391 of file pipeline.c.
References BLI_remlink(), BLI_rw_mutex_end(), free_renderdata_tables(), free_sample_tables(), MEM_freeN(), Render::pushedresult, render_result_free(), RenderGlobal, Render::result, and Render::resultmutex.
Referenced by envmap_free_render_copy(), and RE_FreeAllRender().
void RE_FreeRenderResult (struct RenderResult * rr)
Definition at line 182 of file pipeline.c.
References render_result_free().
Referenced by BKE_image_backup_render(), free_image(), image_free_buffers(), image_load_sequence_multilayer(), render_result_exr_file_read(), render_result_single_layer_begin(), render_result_single_layer_end(), and sss_create_tree_mat().
struct Object* RE_GetCamera (struct Render * re) [read]
Definition at line 449 of file initrender.c.
References Scene::camera, Render::camera_override, and Render::scene.
Referenced by database_fromscene_vectors(), do_render_fields_3d(), do_render_fields_blur_3d(), do_write_image_or_movie(), RE_Database_Baking(), RE_Database_FromScene(), RE_make_stars(), RE_PreviewRender(), render_new_particle_system(), renderresult_stampinfo(), and tag_scenes_for_render().
void RE_GetCameraWindow (struct Render * re, struct Object * camera, int frame, float mat[][4])
Definition at line 520 of file initrender.c.
References RenderData::cfra, copy_m4_m4(), Render::r, RE_SetCamera(), and Render::winmat.
Referenced by screen_opengl_render_apply().
struct Render* RE_GetRender (const char * name) [read]
Definition at line 238 of file pipeline.c.
References Render::name, Render::next, RE_MAXNAME, and RenderGlobal.
Referenced by BKE_image_acquire_renderresult(), BKE_image_backup_render(), BKE_image_release_renderresult(), ed_preview_draw_rect(), image_get_render_result(), node_composit_exec_composite(), node_composit_exec_rlayers(), RE_NewRender(), RE_ReadRenderResult(), seq_render_scene_strip(), shader_preview_render(), stampdata(), uiTemplateImage(), and uiTemplateImageLayers().
struct RenderLayer* RE_GetRenderLayer (struct RenderResult * rr, const char * name) [read]
Definition at line 197 of file pipeline.c.
References ListBase::first, RenderResult::layers, RenderLayer::name, RenderLayer::next, NULL, and RE_MAXNAME.
Referenced by node_composit_exec_rlayers(), and render_result_single_layer_end().
struct Scene* RE_GetScene (struct Render * re) [read]
Definition at line 287 of file pipeline.c.
References NULL, and Render::scene.
struct RenderStats* RE_GetStats (struct Render * re) [read]
Definition at line 344 of file pipeline.c.
References Render::i.
Referenced by stampdata().
void RE_init_threadcount (Render * re)
Definition at line 2346 of file pipeline.c.
References BLENDER_MAX_THREADS, BLI_system_thread_count(), MIN2, RenderData::mode, Render::r, R_FIXED_THREADS, RenderGlobal, and RenderData::threads.
Referenced by RE_Database_Baking(), and RE_InitState().
void RE_InitRenderCB (struct Render * re)
Definition at line 374 of file pipeline.c.
References Render::dch, Render::ddh, default_break(), Render::dih, Render::display_clear, Render::display_draw, Render::display_init, float_nothing(), G, NULL, Render::prh, Render::progress, result_nothing(), result_rcti_nothing(), Render::sdh, stats_background(), Render::stats_draw, stats_nothing(), Render::tbh, and Render::test_break.
Referenced by RE_NewRender(), and render_endjob().
void RE_InitState (struct Render * re, struct Render * source, struct RenderData * rd, struct SceneRenderLayer * srl, int winx, int winy, rcti * disprect)
Definition at line 432 of file pipeline.c.
References RenderData::actlay, BKE_imtype_is_movie(), BKE_report(), BLI_findindex(), BLI_rw_mutex_lock(), BLI_rw_mutex_unlock(), Render::clipcrop, Render::disprect, Render::field_offs, Render::i, RenderData::im_format, ImageFormatData::imtype, RenderData::layers, make_sample_tables(), Render::mblur_offs, MEM_callocN(), RenderData::mode, NULL, Render::ok, RenderData::osa, Render::osa, PIL_check_seconds_timer(), Render::r, R_BORDER, R_EXR_TILE_FILE, R_FULL_SAMPLE, R_OSA, R_PREVIEWBUTS, R_SINGLE_LAYER, RE_init_threadcount(), RenderResult::rectx, Render::rectx, RenderResult::recty, Render::recty, render_result_free(), Render::reports, Render::result, Render::resultmutex, RPT_ERROR, RenderData::scemode, RenderStats::starttime, THREAD_LOCK_WRITE, TRUE, Render::winx, Render::winy, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by envmap_render_copy(), RE_make_sticky(), RE_PreviewRender(), RE_ReadRenderResult(), render_initialize_from_main(), render_scene(), and screen_opengl_render_init().
int RE_is_rendering_allowed (struct Scene * scene, struct Object * camera_override, struct ReportList * reports)
Definition at line 1806 of file pipeline.c.
References RenderData::actlay, BKE_report(), BLI_file_is_writable(), BLI_findlink(), RenderData::border, Scene::camera, check_valid_camera(), CMP_NODE_COMPOSITE, composite_needs_render(), FILE_MAX, ListBase::first, RenderData::layers, SceneRenderLayer::layflag, RenderData::mode, bNode::next, SceneRenderLayer::next, bNodeTree::nodes, Scene::nodetree, NULL, object_camera_mode(), Scene::r, R_BORDER, R_DOCOMP, R_EDGE, R_EXR_TILE_FILE, R_FULL_SAMPLE, R_ORTHO, R_PANORAMA, R_SINGLE_LAYER, render_result_exr_file_path(), RPT_ERROR, SCE_LAY_DISABLE, RenderData::scemode, str, bNode::type, Scene::use_nodes, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by screen_render_invoke().
void RE_make_stars (struct Render * re, struct Scene * scenev3d, void(*)(void) initfunc, void(*)(float *) vertexfunc, void(*)(void) termfunc)
Definition at line 157 of file convertblender.c.
References HaloRen::add, HaloRen::alfa, HaloRen::b, BLI_drand(), BLI_srand(), Scene::camera, Camera::clipend, Object::data, Render::flag, HaloRen::g, HA_ONLYSKY, HaloRen::hard, hash, initstar(), invert_m4_m4(), HaloRen::lay, mul_m4_v3(), NULL, OB_CAMERA, HaloRen::r, R_HALO, RE_addRenderObject(), RE_GetCamera(), Render::scene, sqrt(), World::starcolnoise, World::stardist, World::starmindist, World::starsize, Render::tbh, Render::test_break, Render::tothalo, ObjectRen::tothalo, Object::type, HaloRen::type, tz, unit_m4(), Render::viewmat, Scene::world, and Render::wrld.
Referenced by RE_Database_FromScene(), and view3d_main_area_draw_objects().
void RE_MergeFullSample (struct Render * re, struct Main * bmain, struct Scene * sce, struct bNodeTree * ntree)
Definition at line 1489 of file pipeline.c.
References CMP_NODE_R_LAYERS, Render::dch, Render::dih, Render::display_clear, Render::display_init, do_merge_fullsample(), ListBase::first, ID::flag, G, Scene::id, bNode::id, if(), LIB_DOIT, Render::main, RenderData::mode, bNode::next, ID::next, bNodeTree::nodes, NULL, Scene::r, R_OSA, RE_ReadRenderResult(), Render::result, Main::scene, Render::scene, and bNode::type.
Referenced by node_read_fullsamplelayers_exec().
struct RenderResult* RE_MultilayerConvert (void * exrhandle, int rectx, int recty) [read]
Definition at line 209 of file pipeline.c.
References render_result_new_from_exr().
Referenced by image_create_multilayer().
struct Render* RE_NewRender (const char * name) [read]
Definition at line 349 of file pipeline.c.
References BLI_addtail(), BLI_rw_mutex_init(), BLI_strncpy(), MEM_callocN(), Render::name, NULL, RE_GetRender(), RE_InitRenderCB(), RE_MAXNAME, RenderGlobal, Render::resultmutex, and Render::ycor.
Referenced by envmap_render_copy(), init_bake_internal(), node_read_fullsamplelayers_exec(), RE_make_sticky(), RE_ReadRenderResult(), render_animation(), render_frame(), render_scene(), screen_opengl_render_init(), screen_render_exec(), screen_render_invoke(), seq_render_scene_strip(), and shader_preview_render().
void RE_PreviewRender (struct Render * re, struct Main * bmain, struct Scene * scene)
Definition at line 2269 of file pipeline.c.
References do_render_3d(), Scene::lay, Render::lay, Render::main, NULL, Scene::r, RE_GetCamera(), RE_InitState(), RE_SetCamera(), Render::scene, RenderData::size, RenderData::xsch, and RenderData::ysch.
Referenced by shader_preview_render().
void RE_progress_cb (struct Render * re, void * handle, void(*)(void *handle, float) f)
Definition at line 588 of file pipeline.c.
References Render::prh, and Render::progress.
Referenced by screen_render_invoke().
int RE_ReadRenderResult (struct Scene * scene, struct Scene * scenode)
Definition at line 2292 of file pipeline.c.
References BLI_rw_mutex_lock(), BLI_rw_mutex_unlock(), RenderData::border, Scene::id, RenderData::mode, ID::name, NULL, Scene::r, R_BORDER, RE_GetRender(), RE_InitState(), RE_NewRender(), render_result_exr_file_read(), Render::resultmutex, Render::scene, RenderData::size, THREAD_LOCK_WRITE, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, RenderData::xsch, rcti::ymax, rctf::ymax, rcti::ymin, rctf::ymin, and RenderData::ysch.
Referenced by node_read_renderlayers_exec(), and RE_MergeFullSample().
void RE_ReleaseResult (struct Render * re)
Definition at line 280 of file pipeline.c.
References BLI_rw_mutex_unlock(), and Render::resultmutex.
Referenced by BKE_image_release_renderresult(), image_renderinfo_cb(), node_composit_exec_composite(), node_composit_exec_rlayers(), screen_opengl_render_apply(), screen_opengl_render_init(), uiTemplateImage(), and uiTemplateImageLayers().
void RE_ReleaseResultImage (struct Render * re)
Definition at line 328 of file pipeline.c.
References BLI_rw_mutex_unlock(), and Render::resultmutex.
Referenced by BKE_image_release_ibuf(), do_merge_fullsample(), do_write_image_or_movie(), ed_preview_draw_rect(), image_get_render_result(), RE_ResultGet32(), renderresult_stampinfo(), and seq_render_scene_strip().
int RE_RenderInProgress (struct Render * re)
float* RE_RenderLayerGetPass (struct RenderLayer * rl, int passtype)
Definition at line 187 of file pipeline.c.
References ListBase::first, RenderPass::next, NULL, RenderLayer::passes, RenderPass::passtype, and RenderPass::rect.
Referenced by atm_tile(), compbuf_from_pass(), RE_AcquireResultImage(), reset_sky_speed(), and reset_sky_speedvectors().
void RE_ResultGet32 (struct Render * re, unsigned int * rect)
Definition at line 335 of file pipeline.c.
References Render::r, RE_AcquireResultImage(), RE_ReleaseResultImage(), Render::rectx, Render::recty, and render_result_rect_get_pixels().
Referenced by do_write_image_or_movie(), and shader_preview_render().
int RE_seq_render_active (struct Scene * scene, struct RenderData * rd)
Definition at line 1625 of file pipeline.c.
References Scene::ed, ListBase::first, Sequence::next, R_DOSEQ, RenderData::scemode, SEQ_SOUND, Editing::seqbase, and Sequence::type.
Referenced by do_render_all_options(), and screen_render_invoke().
void RE_set_max_threads (int threads)
Definition at line 2333 of file pipeline.c.
References BLENDER_MAX_THREADS, BLI_system_thread_count(), RenderGlobal, and threads.
Referenced by set_threads().
void RE_SetCamera (struct Render * re, struct Object * camera)
Definition at line 494 of file initrender.c.
References camera_params_compute_matrix(), camera_params_compute_viewplane(), camera_params_from_object(), camera_params_init(), CameraParams::field_odd, CameraParams::field_second, Render::flag, RenderData::mode, Render::r, R_FIELDS, R_ODDFIELD, R_SEC_FIELD, re_camera_params_get(), CameraParams::use_fields, Render::winx, Render::winy, RenderData::xasp, and RenderData::yasp.
Referenced by do_render_fields_3d(), do_render_fields_blur_3d(), RE_Database_FromScene(), RE_GetCameraWindow(), RE_make_sticky(), and RE_PreviewRender().
void RE_SetEnvmapCamera (struct Render * re, struct Object * cam_ob, float viewscale, float clipsta, float clipend)
Definition at line 469 of file initrender.c.
References camera_params_compute_matrix(), camera_params_compute_viewplane(), camera_params_from_object(), camera_params_init(), CAMERA_SENSOR_FIT_AUTO, CameraParams::clipend, CameraParams::clipsta, CameraParams::lens, re_camera_params_get(), CameraParams::sensor_fit, CameraParams::sensor_x, CameraParams::sensor_y, Render::winx, and Render::winy.
Referenced by envmap_render_copy().
void RE_SetOrtho (struct Render * re, rctf * viewplane, float clipsta, float clipend)
Definition at line 548 of file pipeline.c.
References Render::clipend, Render::clipsta, RenderData::mode, orthographic_m4(), Render::r, R_ORTHO, Render::viewplane, Render::winmat, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
void RE_SetPixelSize (struct Render * re, float pixsize)
Definition at line 514 of file initrender.c.
References Render::viewdx, Render::viewdy, and Render::ycor.
void RE_SetReports (struct Render * re, struct ReportList * reports)
Definition at line 2006 of file pipeline.c.
References Render::reports.
Referenced by render_animation(), render_frame(), render_startjob(), and screen_render_exec().
void RE_SetView (struct Render * re, float mat[][4])
Definition at line 560 of file pipeline.c.
References copy_m4_m4(), invert_m4_m4(), Render::viewinv, and Render::viewmat.
Referenced by database_fromscene_vectors(), RE_Database_Baking(), RE_Database_FromScene(), and RE_make_sticky().
void RE_SetWindow (struct Render * re, rctf * viewplane, float clipsta, float clipend)
Definition at line 535 of file pipeline.c.
References Render::clipend, Render::clipsta, RenderData::mode, perspective_m4(), Render::r, R_ORTHO, Render::viewplane, Render::winmat, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by find_next_pano_slice().
void RE_stats_draw_cb (struct Render * re, void * handle, void(*)(void *handle, RenderStats *rs) f)
Definition at line 583 of file pipeline.c.
References Render::sdh, and Render::stats_draw.
Referenced by screen_render_invoke().
void RE_SwapResult (struct Render * re, struct RenderResult ** rr)
Definition at line 271 of file pipeline.c.
References Render::result, and SWAP.
Referenced by BKE_image_backup_render().
void RE_test_break_cb (struct Render * re, void * handle, int(*)(void *handle) f)
Definition at line 600 of file pipeline.c.
References Render::tbh, and Render::test_break.
Referenced by bake_image_exec(), bake_startjob(), screen_render_exec(), screen_render_invoke(), and shader_preview_render().
void RE_TileProcessor (struct Render * re)
Definition at line 906 of file pipeline.c.
References threaded_tile_processor().
Referenced by render_envmap(), and sss_create_tree_mat().
int RE_WriteEnvmapResult (struct ReportList * reports, struct Scene * scene, struct EnvMap * env, const char * relpath, const char imtype, float layout[12])
Definition at line 2409 of file pipeline.c.
References BKE_report(), BKE_write_ibuf(), BLI_path_abs(), BLI_strncpy(), RenderData::color_mgt_flag, EnvMap::cube, ENV_CUBE, ENV_PLANE, FALSE, FILE_MAX, G, i, IB_PROFILE_LINEAR_RGB, IB_rectfloat, RenderData::im_format, IMB_allocImBuf(), IMB_freeImBuf(), IMB_rectcpy(), ImageFormatData::imtype, MAX2, NULL, ImBuf::profile, Scene::r, R_COLOR_MANAGEMENT, RPT_ERROR, TRUE, EnvMap::type, and ImBuf::x.
Referenced by save_envmap().
int RE_WriteRenderResult (struct ReportList * reports, RenderResult * rr, const char * filename, int compress)
Definition at line 715 of file render_result.c.
References BKE_report(), BLI_make_existing_file(), RenderPass::channels, FALSE, ListBase::first, get_pass_name(), IMB_exr_add_channel(), IMB_exr_begin_write(), IMB_exr_close(), IMB_exr_get_handle(), IMB_exr_write_channels(), RenderResult::layers, make_pass_name(), RenderLayer::name, RenderPass::next, RenderLayer::next, RenderLayer::passes, RenderPass::passtype, RenderPass::rect, RenderLayer::rectf, RenderResult::rectf, RenderResult::rectx, RenderResult::recty, RPT_ERROR, SCE_PASS_COMBINED, and TRUE.
Referenced by do_write_image_or_movie(), and save_image_doit().
void RE_zbuf_accumulate_vecblur (struct NodeBlurData * nbd, int xsize, int ysize, float * newrect, float * imgrect, float * vecbufrect, float * zbufrect)
Definition at line 2872 of file zbuf.c.
References ABS, DrawBufPixel::alpha, antialias_tagbuf(), BLI_initjit(), DrawBufPixel::colpoin, NodeBlurData::curved, div, NodeBlurData::fac, jit, MAX2, NodeBlurData::maxspeed, MEM_freeN(), MEM_mapallocN(), NodeBlurData::minspeed, NULL, PASS_VECTOR_MAX, pow(), quad_bezier_2d(), ZSpan::rectp, ZSpan::rectz, NodeBlurData::samples, set_quad_bezier_ipo(), sqrt(), step(), SWAP, zbuf_alloc_span(), zbuf_fill_in_rgba(), zbuf_free_span(), ZSpan::zmulx, ZSpan::zmuly, ZSpan::zofsx, and ZSpan::zofsy.
Referenced by node_composit_exec_vecblur().
Variable Documentation
const float default_envmap_layout[]
Definition at line 2407 of file pipeline.c.
Referenced by save_envmap(), and TEXTURE_OT_envmap_save().