Blender: BKE_sca.h File Reference
BKE_sca.h File Reference
blenkernel
Functions
void link_logicbricks (void **poin, void ***ppoin, short *tot, short size)
void unlink_logicbricks (void **poin, void ***ppoin, short *tot)
void unlink_controller (struct bController *cont)
void unlink_controllers (struct ListBase *lb)
void free_controller (struct bController *cont)
void free_controllers (struct ListBase *lb)
void unlink_actuator (struct bActuator *act)
void unlink_actuators (struct ListBase *lb)
void free_actuator (struct bActuator *act)
void free_actuators (struct ListBase *lb)
void free_sensor (struct bSensor *sens)
void free_sensors (struct ListBase *lb)
struct bSensor * copy_sensor (struct bSensor *sens)
void copy_sensors (struct ListBase *lbn, struct ListBase *lbo)
void init_sensor (struct bSensor *sens)
struct bSensor * new_sensor (int type)
struct bController * copy_controller (struct bController *cont)
void copy_controllers (struct ListBase *lbn, struct ListBase *lbo)
void init_controller (struct bController *cont)
struct bController * new_controller (int type)
struct bActuator * copy_actuator (struct bActuator *act)
void copy_actuators (struct ListBase *lbn, struct ListBase *lbo)
void init_actuator (struct bActuator *act)
struct bActuator * new_actuator (int type)
void clear_sca_new_poins_ob (struct Object *ob)
void clear_sca_new_poins (void)
void set_sca_new_poins_ob (struct Object *ob)
void set_sca_new_poins (void)
void sca_remove_ob_poin (struct Object *obt, struct Object *ob)
void sca_move_sensor (struct bSensor *sens_to_move, struct Object *ob, int move_up)
void sca_move_controller (struct bController *cont_to_move, struct Object *ob, int move_up)
void sca_move_actuator (struct bActuator *act_to_move, struct Object *ob, int move_up)
Detailed Description
Definition in file BKE_sca.h.
Function Documentation
void clear_sca_new_poins (void)
Definition at line 533 of file sca.c.
References clear_sca_new_poins_ob(), G, Object::id, and ID::next.
Referenced by add_named_exec(), duplicate_exec(), ED_object_add_duplicate(), get_selected_and_linked_obs(), and single_object_users().
void clear_sca_new_poins_ob (struct Object * ob)
Definition at line 508 of file sca.c.
References ACT_NEW, Object::actuators, CONT_NEW, Object::controllers, ListBase::first, bActuator::flag, bController::flag, bSensor::flag, bActuator::mynew, bController::mynew, bActuator::next, bController::next, bSensor::next, NULL, SENS_NEW, and Object::sensors.
Referenced by clear_sca_new_poins(), copymenu_logicbricks(), and logicbricks_copy_exec().
struct bActuator* copy_actuator (struct bActuator * act) [read]
Definition at line 356 of file sca.c.
References ACT_NEW, ACT_SOUND, bActuator::data, bActuator::flag, id_us_plus(), if(), MEM_dupallocN(), bActuator::mynew, bSoundActuator::sound, and bActuator::type.
Referenced by copy_actuators().
void copy_actuators (struct ListBase * lbn, struct ListBase * lbo)
Definition at line 377 of file sca.c.
References BLI_addtail(), copy_actuator(), ListBase::first, ListBase::last, bActuator::next, and NULL.
Referenced by copy_object(), copymenu_logicbricks(), and logicbricks_copy_exec().
struct bController* copy_controller (struct bController * cont) [read]
Definition at line 238 of file sca.c.
References CONT_NEW, bController::data, bController::flag, bController::links, MEM_dupallocN(), bController::mynew, NULL, bController::slinks, and bController::totslinks.
Referenced by copy_controllers().
void copy_controllers (struct ListBase * lbn, struct ListBase * lbo)
Definition at line 255 of file sca.c.
References BLI_addtail(), copy_controller(), ListBase::first, ListBase::last, bController::next, and NULL.
Referenced by copy_object(), copymenu_logicbricks(), and logicbricks_copy_exec().
struct bSensor* copy_sensor (struct bSensor * sens) [read]
Definition at line 73 of file sca.c.
References bSensor::data, bSensor::flag, bSensor::links, MEM_dupallocN(), and SENS_NEW.
Referenced by copy_sensors().
void copy_sensors (struct ListBase * lbn, struct ListBase * lbo)
Definition at line 88 of file sca.c.
References BLI_addtail(), copy_sensor(), ListBase::first, ListBase::last, bSensor::next, and NULL.
Referenced by copy_object(), copymenu_logicbricks(), and logicbricks_copy_exec().
void free_actuator (struct bActuator * act)
Definition at line 328 of file sca.c.
References ACT_SOUND, bActuator::data, id_us_min(), if(), MEM_freeN(), bSoundActuator::sound, and bActuator::type.
Referenced by actuator_remove_exec(), do_logic_buts(), and free_actuators().
void free_actuators (struct ListBase * lb)
Definition at line 346 of file sca.c.
References BLI_remlink(), ListBase::first, and free_actuator().
Referenced by copymenu_logicbricks(), free_object(), and logicbricks_copy_exec().
void free_controller (struct bController * cont)
Definition at line 217 of file sca.c.
References bController::data, bController::links, and MEM_freeN().
Referenced by controller_remove_exec(), do_logic_buts(), and free_controllers().
void free_controllers (struct ListBase * lb)
Definition at line 227 of file sca.c.
References BLI_remlink(), ListBase::first, free_controller(), MEM_freeN(), and bController::slinks.
Referenced by copymenu_logicbricks(), free_object(), and logicbricks_copy_exec().
void free_sensor (struct bSensor * sens)
Definition at line 55 of file sca.c.
References bSensor::data, bSensor::links, and MEM_freeN().
Referenced by do_logic_buts(), free_sensors(), and sensor_remove_exec().
void free_sensors (struct ListBase * lb)
Definition at line 63 of file sca.c.
References BLI_remlink(), ListBase::first, and free_sensor().
Referenced by copymenu_logicbricks(), free_object(), and logicbricks_copy_exec().
void init_actuator (struct bActuator * act)
Definition at line 390 of file sca.c.
References bSteeringActuator::acceleration, ACT_2DFILTER, ACT_ACTION, ACT_ARMATURE, ACT_CAMERA, ACT_CONSTRAINT, ACT_EDIT_OBJECT, ACT_GAME, ACT_GROUP, ACT_IPO, ACT_MESSAGE, ACT_OBJECT, ACT_PARENT, ACT_PROPERTY, ACT_RANDOM, ACT_SCENE, ACT_SHAPEACTION, ACT_SOUND, ACT_STATE, ACT_STEERING, ACT_STEERING_AUTOMATICFACING, ACT_VISIBILITY, bCameraActuator::axis, Sound3D::cone_inner_angle, Sound3D::cone_outer_angle, bCameraActuator::damping, bActuator::data, bSteeringActuator::dist, bSteeringActuator::facingaxis, bSteeringActuator::flag, bObjectActuator::flag, bRandomActuator::float_arg_1, FLT_MAX, bArmatureActuator::influence, Sound3D::max_distance, Sound3D::max_gain, MEM_callocN(), MEM_freeN(), NULL, OB_POSX, Sound3D::reference_distance, Sound3D::rolloff_factor, bSoundActuator::sound3D, bSteeringActuator::turnspeed, bActuator::type, bSteeringActuator::velocity, and bSoundActuator::volume.
Referenced by do_logic_buts(), lib_link_object(), and new_actuator().
void init_controller (struct bController * cont)
Definition at line 268 of file sca.c.
References CONT_EXPRESSION, CONT_PYTHON, bController::data, MEM_callocN(), MEM_freeN(), NULL, and bController::type.
Referenced by do_logic_buts(), draw_controllerbuttons(), and new_controller().
void init_sensor (struct bSensor * sens)
Definition at line 101 of file sca.c.
References bJoystickSensor::axis, bSensor::data, bNearSensor::dist, bJoystickSensor::hat, bJoystickSensor::hatf, MEM_callocN(), MEM_freeN(), NULL, bSensor::pulse, bRaySensor::range, bNearSensor::resetdist, SENS_ACTUATOR, SENS_ALWAYS, SENS_ARMATURE, SENS_COLLISION, SENS_DELAY, SENS_JOY_HAT_UP, SENS_JOYSTICK, SENS_KEYBOARD, SENS_MESSAGE, SENS_MOUSE, SENS_NEAR, SENS_PROPERTY, SENS_RADAR, SENS_RANDOM, SENS_RAY, SENS_TOUCH, bMouseSensor::type, and bSensor::type.
Referenced by do_logic_buts(), and new_sensor().
void link_logicbricks (void ** poin, void *** ppoin, short * tot, short size)
Definition at line 827 of file sca.c.
References MEM_callocN(), MEM_freeN(), and NULL.
struct bActuator* new_actuator (int type) [read]
Definition at line 491 of file sca.c.
References ACT_SHOW, bActuator::flag, init_actuator(), MEM_callocN(), bActuator::name, and bActuator::type.
Referenced by actuator_add_exec(), and do_logic_buts().
struct bController* new_controller (int type) [read]
Definition at line 285 of file sca.c.
References CONT_SHOW, bController::flag, init_controller(), MEM_callocN(), bController::name, and bController::type.
Referenced by controller_add_exec(), and do_logic_buts().
struct bSensor* new_sensor (int type) [read]
Definition at line 174 of file sca.c.
References bSensor::flag, init_sensor(), MEM_callocN(), bSensor::name, SENS_SHOW, and bSensor::type.
Referenced by do_logic_buts(), and sensor_add_exec().
void sca_move_actuator (struct bActuator * act_to_move, struct Object * ob, int move_up)
Definition at line 786 of file sca.c.
References ACT_VISIBLE, Object::actuators, BLI_insertlink(), BLI_insertlinkbefore(), BLI_remlink(), ListBase::first, bActuator::flag, bActuator::next, and bActuator::prev.
Referenced by actuator_move_exec().
void sca_move_controller (struct bController * cont_to_move, struct Object * ob, int move_up)
Definition at line 743 of file sca.c.
References BLI_insertlink(), BLI_insertlinkbefore(), BLI_remlink(), Object::controllers, ListBase::first, bController::next, bController::prev, and bController::state_mask.
Referenced by controller_move_exec().
void sca_move_sensor (struct bSensor * sens_to_move, struct Object * ob, int move_up)
Definition at line 704 of file sca.c.
References BLI_insertlink(), BLI_insertlinkbefore(), BLI_remlink(), ListBase::first, bSensor::flag, bSensor::next, bSensor::prev, SENS_VISIBLE, and Object::sensors.
Referenced by sensor_move_exec().
void sca_remove_ob_poin (struct Object * obt, struct Object * ob)
Definition at line 632 of file sca.c.
References ACT_ARMATURE, ACT_CAMERA, ACT_EDIT_OBJECT, ACT_MESSAGE, ACT_OBJECT, ACT_PARENT, ACT_PROPERTY, ACT_SCENE, ACT_STEERING, Object::actuators, bSceneActuator::camera, bActuator::data, bSensor::data, ListBase::first, bMessageSensor::fromObject, bSteeringActuator::navmesh, bActuator::next, bSensor::next, NULL, bParentActuator::ob, bEditObjectActuator::ob, bPropertyActuator::ob, bCameraActuator::ob, bObjectActuator::reference, SENS_MESSAGE, Object::sensors, bArmatureActuator::subtarget, bSteeringActuator::target, bArmatureActuator::target, bMessageActuator::toObject, bActuator::type, and bSensor::type.
Referenced by unlink_object().
void set_sca_new_poins (void)
Definition at line 621 of file sca.c.
References G, Object::id, ID::next, and set_sca_new_poins_ob().
Referenced by copy_object_set_idnew(), and single_object_users().
void set_sca_new_poins_ob (struct Object * ob)
Definition at line 544 of file sca.c.
References ACT_ARMATURE, ACT_CAMERA, ACT_EDIT_OBJECT, ACT_MESSAGE, ACT_NEW, ACT_OBJECT, ACT_PARENT, ACT_PROPERTY, ACT_SCENE, ACT_STEERING, Object::actuators, bSceneActuator::camera, CONT_NEW, Object::controllers, bActuator::data, ListBase::first, bActuator::flag, bController::flag, bSensor::flag, ID_NEW, bController::links, bSensor::links, bActuator::mynew, bController::mynew, bSteeringActuator::navmesh, bActuator::next, bController::next, bSensor::next, bPropertyActuator::ob, bParentActuator::ob, bCameraActuator::ob, bEditObjectActuator::ob, bObjectActuator::reference, SENS_NEW, Object::sensors, bArmatureActuator::subtarget, bSteeringActuator::target, bArmatureActuator::target, bMessageActuator::toObject, bController::totlinks, bSensor::totlinks, and bActuator::type.
Referenced by copymenu_logicbricks(), ED_object_add_duplicate(), logicbricks_copy_exec(), and set_sca_new_poins().
void unlink_actuator (struct bActuator * act)
Definition at line 303 of file sca.c.
References Object::controllers, ListBase::first, G, Object::id, bController::links, ID::next, bController::next, bController::totlinks, and unlink_logicbricks().
Referenced by actuator_remove_exec(), do_logic_buts(), and unlink_actuators().
void unlink_actuators (struct ListBase * lb)
Definition at line 320 of file sca.c.
References ListBase::first, bActuator::next, and unlink_actuator().
Referenced by copymenu_logicbricks(), logicbricks_copy_exec(), and unlink_object().
void unlink_controller (struct bController * cont)
Definition at line 192 of file sca.c.
References ListBase::first, G, Object::id, bSensor::links, ID::next, bSensor::next, Object::sensors, bSensor::totlinks, and unlink_logicbricks().
Referenced by controller_remove_exec(), do_logic_buts(), and unlink_controllers().
void unlink_controllers (struct ListBase * lb)
Definition at line 209 of file sca.c.
References ListBase::first, bController::next, and unlink_controller().
Referenced by copymenu_logicbricks(), logicbricks_copy_exec(), and unlink_object().
void unlink_logicbricks (void ** poin, void *** ppoin, short * tot)
Definition at line 859 of file sca.c.
References MEM_freeN(), and NULL.
Referenced by unlink_actuator(), and unlink_controller().