Blender: SCA_DelaySensor Class Reference
SCA_DelaySensor Class Reference
#include <SCA_DelaySensor.h>
Public Member Functions
SCA_DelaySensor (class SCA_EventManager *eventmgr, SCA_IObject *gameobj, int delay, int duration, bool repeat)
virtual ~SCA_DelaySensor ()
virtual CValue * GetReplica ()
virtual bool Evaluate ()
virtual bool IsPositiveTrigger ()
virtual void Init ()
Detailed Description
Definition at line 39 of file SCA_DelaySensor.h.
Constructor & Destructor Documentation
SCA_DelaySensor::SCA_DelaySensor (class SCA_EventManager * eventmgr, SCA_IObject * gameobj, int delay, int duration, bool repeat)
Definition at line 52 of file SCA_DelaySensor.cpp.
References Init().
Referenced by GetReplica().
SCA_DelaySensor::~SCA_DelaySensor () [virtual]
Definition at line 72 of file SCA_DelaySensor.cpp.
Member Function Documentation
bool SCA_DelaySensor::Evaluate () [virtual]
Implements SCA_ISensor.
Definition at line 93 of file SCA_DelaySensor.cpp.
References SCA_ISensor::m_level, and SCA_ISensor::m_reset.
CValue * SCA_DelaySensor::GetReplica (void) [virtual]
Implements SCA_ISensor.
Definition at line 77 of file SCA_DelaySensor.cpp.
References CValue::ProcessReplica(), and SCA_DelaySensor().
void SCA_DelaySensor::Init (void) [virtual]
Reimplemented from SCA_ISensor.
Definition at line 65 of file SCA_DelaySensor.cpp.
References SCA_ISensor::m_reset.
Referenced by SCA_DelaySensor().
bool SCA_DelaySensor::IsPositiveTrigger () [virtual]
Reimplemented from SCA_ISensor.
Definition at line 88 of file SCA_DelaySensor.cpp.
References SCA_ISensor::m_invert.
The documentation for this class was generated from the following files:
SCA_DelaySensor.h
SCA_DelaySensor.cpp