Blender: util_color.h File Reference
util_color.h File Reference
#include "util_math.h"
#include "util_types.h"
Functions
CCL_NAMESPACE_BEGIN __device float color_srgb_to_scene_linear (float c)
__device float color_scene_linear_to_srgb (float c)
__device float3 color_srgb_to_scene_linear (float3 c)
__device float3 color_scene_linear_to_srgb (float3 c)
__device float linear_rgb_to_gray (float3 c)
Function Documentation
__device float color_scene_linear_to_srgb (float c)
Definition at line 35 of file util_color.h.
References pow().
__device float3 color_scene_linear_to_srgb (float3 c)
Definition at line 53 of file util_color.h.
References color_scene_linear_to_srgb(), make_float3(), float3::x, float3::y, and float3::z.
CCL_NAMESPACE_BEGIN __device float color_srgb_to_scene_linear (float c)
Definition at line 27 of file util_color.h.
References pow().
__device float3 color_srgb_to_scene_linear (float3 c)
Definition at line 45 of file util_color.h.
References color_srgb_to_scene_linear(), make_float3(), float3::x, float3::y, and float3::z.
__device float linear_rgb_to_gray (float3 c)
Definition at line 63 of file util_color.h.
References float3::x, float3::y, and float3::z.
Referenced by svm_node_convert().