Blender: WTURBULENCE.cpp File Reference
WTURBULENCE.cpp File Reference
smoke
#include "WTURBULENCE.h"
#include "INTERPOLATE.h"
#include "IMAGE.h"
#include <MERSENNETWISTER.h>
#include "WAVELET_NOISE.h"
#include "FFT_NOISE.h"
#include "EIGENVALUE_HELPER.h"
#include "LU_HELPER.h"
#include "SPHERE.h"
#include <zlib.h>
#include <math.h>
#include "FLUID_3D.h"
Functions
static float minDx (int x, int y, int z, float *input, Vec3Int res)
static float minDy (int x, int y, int z, float *input, Vec3Int res)
static float minDz (int x, int y, int z, float *input, Vec3Int res)
Variables
static const float persistence = 0.56123f
Detailed Description
Definition in file WTURBULENCE.cpp.
Function Documentation
static float minDx (int x, int y, int z, float * input, Vec3Int res) [static]
Definition at line 186 of file WTURBULENCE.cpp.
References fabs(), FLT_MAX, and left().
Referenced by WTURBULENCE::computeEigenvalues(), and WTURBULENCE::stepTurbulenceFull().
static float minDy (int x, int y, int z, float * input, Vec3Int res) [static]
Definition at line 221 of file WTURBULENCE.cpp.
References fabs(), and FLT_MAX.
Referenced by WTURBULENCE::computeEigenvalues(), and WTURBULENCE::stepTurbulenceFull().
static float minDz (int x, int y, int z, float * input, Vec3Int res) [static]
Definition at line 255 of file WTURBULENCE.cpp.
References fabs(), and FLT_MAX.
Referenced by WTURBULENCE::computeEigenvalues(), and WTURBULENCE::stepTurbulenceFull().
Variable Documentation
const float persistence = 0.56123f [static]
Definition at line 49 of file WTURBULENCE.cpp.
Referenced by WTURBULENCE::stepTurbulenceFull().