Blender: GPU_buffers.h File Reference
GPU_buffers.h File Reference
GPU
Classes
struct GPUBuffer
struct GPUBufferMaterial
struct GPUDrawObject
struct GPUAttrib
Defines
#define DEBUG_VBO(X)
Typedefs
typedef struct GPUBuffer GPUBuffer
typedef struct GPUBufferMaterial GPUBufferMaterial
typedef struct GPUDrawObject GPUDrawObject
typedef struct GPUAttrib GPUAttrib
typedef struct GPU_Buffers GPU_Buffers
Functions
void GPU_global_buffer_pool_free (void)
GPUBuffer * GPU_buffer_alloc (int size)
void GPU_buffer_free (GPUBuffer *buffer)
GPUDrawObject * GPU_drawobject_new (struct DerivedMesh *dm)
void GPU_drawobject_free (struct DerivedMesh *dm)
void GPU_vertex_setup (struct DerivedMesh *dm)
void GPU_normal_setup (struct DerivedMesh *dm)
void GPU_uv_setup (struct DerivedMesh *dm)
void GPU_color_setup (struct DerivedMesh *dm)
void GPU_edge_setup (struct DerivedMesh *dm)
void GPU_uvedge_setup (struct DerivedMesh *dm)
int GPU_attrib_element_size (GPUAttrib data[], int numdata)
void GPU_interleaved_attrib_setup (GPUBuffer *buffer, GPUAttrib data[], int numdata)
void * GPU_buffer_lock (GPUBuffer *buffer)
void * GPU_buffer_lock_stream (GPUBuffer *buffer)
void GPU_buffer_unlock (GPUBuffer *buffer)
void GPU_color3_upload (struct DerivedMesh *dm, unsigned char *data)
void GPU_color_switch (int mode)
void GPU_buffer_draw_elements (GPUBuffer *elements, unsigned int mode, int start, int count)
void GPU_buffer_unbind (void)
int GPU_buffer_legacy (struct DerivedMesh *dm)
GPU_Buffers * GPU_build_mesh_buffers (int(*face_vert_indices)[4], struct MFace *mface, struct MVert *mvert, int *face_indices, int totface)
void GPU_update_mesh_buffers (GPU_Buffers *buffers, struct MVert *mvert, int *vert_indices, int totvert)
GPU_Buffers * GPU_build_grid_buffers (int *grid_indices, int totgrid, unsigned int **grid_hidden, int gridsize)
void GPU_update_grid_buffers (GPU_Buffers *buffers, struct DMGridData **grids, const struct DMFlagMat *grid_flag_mats, int *grid_indices, int totgrid, int gridsize)
void GPU_draw_buffers (GPU_Buffers *buffers, DMSetMaterial setMaterial)
void GPU_free_buffers (GPU_Buffers *buffers)
Detailed Description
Definition in file GPU_buffers.h.
Define Documentation
#define DEBUG_VBO (X)
Definition at line 39 of file GPU_buffers.h.
Referenced by cdDM_drawEdges(), cdDM_drawFacesSolid(), cdDM_drawFacesTex_common(), cdDM_drawLooseEdges(), cdDM_drawMappedFaces(), and cdDM_drawMappedFacesGLSL().
Typedef Documentation
typedef struct GPU_Buffers GPU_Buffers
Definition at line 160 of file GPU_buffers.h.
typedef struct GPUAttrib GPUAttrib
typedef struct GPUBuffer GPUBuffer
typedef struct GPUBufferMaterial GPUBufferMaterial
typedef struct GPUDrawObject GPUDrawObject
Function Documentation
int GPU_attrib_element_size (GPUAttrib data[], int numdata)
Definition at line 1078 of file gpu_buffers.c.
References elementsize(), GPU_typesize(), i, and GPUAttrib::size.
Referenced by cdDM_drawMappedFacesGLSL(), and GPU_interleaved_attrib_setup().
GPUBuffer* GPU_buffer_alloc (int size)
Definition at line 188 of file gpu_buffers.c.
References GPUBufferPool::buffers, gpu_buffer_pool_delete_last(), gpu_buffer_pool_remove_index(), gpu_get_global_buffer_pool(), i, GPUBuffer::id, MEM_callocN(), MEM_mallocN(), NULL, GPUBuffer::pointer, GPUBuffer::size, size(), GPUBufferPool::totbuf, and useVBOs.
Referenced by cdDM_drawMappedFacesGLSL(), and gpu_buffer_setup().
void GPU_buffer_draw_elements (GPUBuffer * elements, unsigned int mode, int start, int count)
Definition at line 1253 of file gpu_buffers.c.
References GPUBuffer::pointer, and useVBOs.
Referenced by cdDM_drawEdges(), and cdDM_drawLooseEdges().
void GPU_buffer_free (GPUBuffer * buffer)
Definition at line 265 of file gpu_buffers.c.
References BLI_thread_is_main(), GPUBufferPool::buffers, gpu_buffer_pool_delete_last(), gpu_get_global_buffer_pool(), i, MAX_FREE_GPU_BUFFERS, GPUBufferPool::maxsize, MEM_reallocN(), and GPUBufferPool::totbuf.
Referenced by cdDM_drawMappedFacesGLSL(), gpu_buffer_setup(), GPU_color3_upload(), and GPU_drawobject_free().
int GPU_buffer_legacy (struct DerivedMesh * dm)
Definition at line 1193 of file gpu_buffers.c.
References DerivedMesh::drawObject, GPU_drawobject_new(), GPUDrawObject::legacy, and USER_DISABLE_VBO.
Referenced by cdDM_drawEdges(), cdDM_drawFacesSolid(), cdDM_drawFacesTex_common(), cdDM_drawLooseEdges(), cdDM_drawMappedFaces(), cdDM_drawMappedFacesGLSL(), cdDM_drawUVEdges(), cdDM_drawVerts(), and draw_mesh_textured_old().
void* GPU_buffer_lock (GPUBuffer * buffer)
Definition at line 1204 of file gpu_buffers.c.
References GPUBuffer::id, GPUBuffer::pointer, and useVBOs.
void* GPU_buffer_lock_stream (GPUBuffer * buffer)
Definition at line 1221 of file gpu_buffers.c.
References GPUBuffer::id, GPUBuffer::pointer, GPUBuffer::size, and useVBOs.
Referenced by cdDM_drawMappedFacesGLSL().
void GPU_buffer_unbind (void)
Definition at line 1130 of file gpu_buffers.c.
References GLStates, GPU_BUFFER_COLOR_STATE, GPU_BUFFER_ELEMENT_STATE, GPU_BUFFER_NORMAL_STATE, GPU_BUFFER_TEXCOORD_STATE, GPU_BUFFER_VERTEX_STATE, i, MAX_GPU_ATTRIB_DATA, and useVBOs.
Referenced by cdDM_drawEdges(), cdDM_drawFacesSolid(), cdDM_drawFacesTex_common(), cdDM_drawLooseEdges(), cdDM_drawMappedFaces(), cdDM_drawMappedFacesGLSL(), cdDM_drawUVEdges(), and cdDM_drawVerts().
void GPU_buffer_unlock (GPUBuffer * buffer)
Definition at line 1240 of file gpu_buffers.c.
References useVBOs.
Referenced by cdDM_drawMappedFacesGLSL().
GPU_Buffers* GPU_build_grid_buffers (int * grid_indices, int totgrid, unsigned int ** grid_hidden, int gridsize)
Definition at line 1594 of file gpu_buffers.c.
References FILL_QUAD_BUFFER, gpu_count_grid_quads(), gpu_get_grid_buffer(), GPU_Buffers::grid_hidden, GPU_Buffers::gridsize, GPU_Buffers::has_hidden, GPU_Buffers::index_buf, GPU_Buffers::index_type, MEM_callocN(), GPU_Buffers::tot_quad, GPU_Buffers::totgrid, USER_DISABLE_VBO, and GPU_Buffers::vert_buf.
Referenced by build_grids_leaf_node(), and pbvh_update_draw_buffers().
GPU_Buffers* GPU_build_mesh_buffers (int(*) face_vert_indices[4], struct MFace * mface, struct MVert * mvert, int * face_indices, int totface)
Definition at line 1330 of file gpu_buffers.c.
References GPU_Buffers::face_indices, i, GPU_Buffers::index_buf, GPU_Buffers::index_type, MEM_callocN(), GPU_Buffers::mface, NULL, paint_is_face_hidden(), GPU_Buffers::tot_tri, GPU_Buffers::totface, USER_DISABLE_VBO, MFace::v4, and GPU_Buffers::vert_buf.
Referenced by build_mesh_leaf_node(), and pbvh_update_draw_buffers().
void GPU_color3_upload (struct DerivedMesh * dm, unsigned char * data)
Definition at line 1166 of file gpu_buffers.c.
References GPUDrawObject::colors, DerivedMesh::drawObject, GPU_buffer_copy_color3(), GPU_buffer_free(), gpu_buffer_setup(), GPU_drawobject_new(), and GPUDrawObject::tot_triangle_point.
Referenced by cdDM_drawFacesTex_common().
void GPU_color_setup (struct DerivedMesh * dm)
Definition at line 1001 of file gpu_buffers.c.
References GPUDrawObject::colors, DerivedMesh::drawObject, GLStates, GPU_BUFFER_COLOR, GPU_BUFFER_COLOR_STATE, gpu_buffer_setup_common(), GPUBuffer::id, GPUBuffer::pointer, and useVBOs.
Referenced by cdDM_drawFacesTex_common(), and cdDM_drawMappedFaces().
void GPU_color_switch (int mode)
Definition at line 1177 of file gpu_buffers.c.
References GLStates, and GPU_BUFFER_COLOR_STATE.
Referenced by cdDM_drawFacesTex_common().
void GPU_draw_buffers (GPU_Buffers * buffers, DMSetMaterial setMaterial)
Definition at line 1771 of file gpu_buffers.c.
References co, GPU_Buffers::face_indices, DMFlagMat::flag, MFace::flag, gpu_draw_buffers_legacy_grids(), gpu_draw_buffers_legacy_mesh(), GPU_Buffers::grid_flag_mats, GPU_Buffers::grid_indices, GPU_Buffers::gridsize, GPU_Buffers::has_hidden, i, GPU_Buffers::index_buf, GPU_Buffers::index_type, DMFlagMat::mat_nr, MFace::mat_nr, ME_SMOOTH, GPU_Buffers::mface, NULL, smooth(), GPU_Buffers::tot_quad, GPU_Buffers::tot_tri, GPU_Buffers::totface, GPU_Buffers::totgrid, and GPU_Buffers::vert_buf.
Referenced by BLI_pbvh_node_draw().
void GPU_drawobject_free (struct DerivedMesh * dm)
Definition at line 448 of file gpu_buffers.c.
References GPUDrawObject::colors, DerivedMesh::drawObject, GPUDrawObject::edges, GPU_buffer_free(), GPUDrawObject::materials, MEM_freeN(), GPUDrawObject::normals, NULL, GPUDrawObject::points, GPUDrawObject::triangle_to_mface, GPUDrawObject::uv, GPUDrawObject::uvedges, GPUDrawObject::vert_points, and GPUDrawObject::vert_points_mem.
Referenced by DM_release(), sculpt_flush_update(), and sculpt_undo_restore().
GPUDrawObject* GPU_drawobject_new (struct DerivedMesh * dm)
Definition at line 394 of file gpu_buffers.c.
References DerivedMesh::getNumEdges, DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, DerivedMesh::getTessFaceArray, gpu_drawobject_init_vert_points(), i, GPUBufferMaterial::mat_nr, GPUDrawObject::materials, MAX_MATERIALS, MEM_callocN(), MEM_mallocN(), GPUBufferMaterial::start, GPUDrawObject::tot_triangle_point, GPUDrawObject::totedge, GPUDrawObject::totmaterial, GPUBufferMaterial::totpoint, GPUDrawObject::totvert, and GPUDrawObject::triangle_to_mface.
Referenced by GPU_buffer_legacy(), gpu_buffer_setup_common(), and GPU_color3_upload().
void GPU_edge_setup (struct DerivedMesh * dm)
Definition at line 1018 of file gpu_buffers.c.
References DerivedMesh::drawObject, GPUDrawObject::edges, GLStates, GPU_BUFFER_EDGE, GPU_BUFFER_ELEMENT_STATE, gpu_buffer_setup_common(), GPU_BUFFER_VERTEX, GPU_BUFFER_VERTEX_STATE, GPUBuffer::id, GPUBuffer::pointer, GPUDrawObject::points, and useVBOs.
Referenced by cdDM_drawEdges(), and cdDM_drawLooseEdges().
void GPU_free_buffers (GPU_Buffers * buffers)
Definition at line 1833 of file gpu_buffers.c.
References GPU_Buffers::has_hidden, GPU_Buffers::index_buf, MEM_freeN(), GPU_Buffers::tot_tri, and GPU_Buffers::vert_buf.
Referenced by BLI_pbvh_free(), and pbvh_update_draw_buffers().
void GPU_global_buffer_pool_free (void)
Definition at line 180 of file gpu_buffers.c.
References gpu_buffer_pool_free(), and NULL.
Referenced by WM_exit_ext().
void GPU_interleaved_attrib_setup (GPUBuffer * buffer, GPUAttrib data[], int numdata)
Definition at line 1090 of file gpu_buffers.c.
References elementsize(), GPU_attrib_element_size(), GPU_typesize(), i, GPUBuffer::id, GPUAttrib::index, MAX_GPU_ATTRIB_DATA, GPUBuffer::pointer, GPUAttrib::size, size(), GPUAttrib::type, and useVBOs.
Referenced by cdDM_drawMappedFacesGLSL().
void GPU_normal_setup (struct DerivedMesh * dm)
Definition at line 967 of file gpu_buffers.c.
References DerivedMesh::drawObject, GLStates, GPU_BUFFER_NORMAL, GPU_BUFFER_NORMAL_STATE, gpu_buffer_setup_common(), GPUBuffer::id, GPUDrawObject::normals, GPUBuffer::pointer, and useVBOs.
Referenced by cdDM_drawFacesSolid(), cdDM_drawFacesTex_common(), cdDM_drawMappedFaces(), and cdDM_drawMappedFacesGLSL().
void GPU_update_grid_buffers (GPU_Buffers * buffers, struct DMGridData ** grids, const struct DMFlagMat * grid_flag_mats, int * grid_indices, int totgrid, int gridsize)
Referenced by pbvh_update_draw_buffers().
void GPU_update_mesh_buffers (GPU_Buffers * buffers, struct MVert * mvert, int * vert_indices, int totvert)
Definition at line 1294 of file gpu_buffers.c.
References MVert::co, VertexBufferFormat::co, copy_v3_v3(), i, GPU_Buffers::mvert, MVert::no, VertexBufferFormat::no, NULL, and GPU_Buffers::vert_buf.
Referenced by pbvh_update_draw_buffers().
void GPU_uv_setup (struct DerivedMesh * dm)
Definition at line 984 of file gpu_buffers.c.
References DerivedMesh::drawObject, GLStates, gpu_buffer_setup_common(), GPU_BUFFER_TEXCOORD_STATE, GPU_BUFFER_UV, GPUBuffer::id, GPUBuffer::pointer, useVBOs, and GPUDrawObject::uv.
Referenced by cdDM_drawFacesTex_common().
void GPU_uvedge_setup (struct DerivedMesh * dm)
Definition at line 1043 of file gpu_buffers.c.
References DerivedMesh::drawObject, GLStates, gpu_buffer_setup_common(), GPU_BUFFER_UVEDGE, GPU_BUFFER_VERTEX_STATE, GPUBuffer::id, GPUBuffer::pointer, useVBOs, and GPUDrawObject::uvedges.
Referenced by cdDM_drawUVEdges().
void GPU_vertex_setup (struct DerivedMesh * dm)
Definition at line 950 of file gpu_buffers.c.
References DerivedMesh::drawObject, GLStates, gpu_buffer_setup_common(), GPU_BUFFER_VERTEX, GPU_BUFFER_VERTEX_STATE, GPUBuffer::id, GPUBuffer::pointer, GPUDrawObject::points, and useVBOs.
Referenced by cdDM_drawFacesSolid(), cdDM_drawFacesTex_common(), cdDM_drawMappedFaces(), cdDM_drawMappedFacesGLSL(), and cdDM_drawVerts().