Blender: bmo_extrude.c File Reference
bmo_extrude.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_array.h"
#include "bmesh.h"
#include "intern/bmesh_operators_private.h"
Defines
#define VERT_MARK 1
#define EDGE_MARK 1
#define FACE_MARK 1
#define VERT_NONMAN 2
#define EDGE_NONMAN 2
Enumerations
enum { EXT_INPUT = 1, EXT_KEEP = 2, EXT_DEL = 4 }
Functions
void bmo_extrude_face_indiv_exec (BMesh *bm, BMOperator *op)
static void bm_extrude_copy_face_loop_attributes (BMesh *bm, BMFace *f, BMEdge *e_a, BMEdge *e_b)
Copy the loop pair from an adjacent face to both sides of this quad.
void bmo_extrude_edge_only_exec (BMesh *bm, BMOperator *op)
void bmo_extrude_vert_indiv_exec (BMesh *bm, BMOperator *op)
void bmo_extrude_face_region_exec (BMesh *bm, BMOperator *op)
static void calc_solidify_normals (BMesh *bm)
static void solidify_add_thickness (BMesh *bm, const float dist)
void bmo_solidify_face_region_exec (BMesh *bm, BMOperator *op)
Detailed Description
Definition in file bmo_extrude.c.
Define Documentation
#define EDGE_MARK 1
Definition at line 43 of file bmo_extrude.c.
Referenced by calc_solidify_normals().
#define EDGE_NONMAN 2
Definition at line 46 of file bmo_extrude.c.
Referenced by calc_solidify_normals().
#define FACE_MARK 1
Definition at line 44 of file bmo_extrude.c.
Referenced by bmo_solidify_face_region_exec(), calc_solidify_normals(), and solidify_add_thickness().
#define VERT_MARK 1
Definition at line 42 of file bmo_extrude.c.
Referenced by calc_solidify_normals().
#define VERT_NONMAN 2
Definition at line 45 of file bmo_extrude.c.
Referenced by calc_solidify_normals().
Enumeration Type Documentation
anonymous enum
Enumerator:
EXT_INPUT
EXT_KEEP
EXT_DEL
Definition at line 36 of file bmo_extrude.c.
Function Documentation
static void bm_extrude_copy_face_loop_attributes (BMesh * bm, BMFace * f, BMEdge * e_a, BMEdge * e_b) [static]
Copy the loop pair from an adjacent face to both sides of this quad.
The face is assumed to be a quad, created by extruding. This function won't crash if its not but won't work right either. e_b is the new edge.
Note:
this function could be exposed as an api call if other areas need it, so far only extrude does.
Definition at line 131 of file bmo_extrude.c.
References BLI_assert, BM_elem_attrs_copy(), BM_elem_flag_disable, BM_ELEM_HIDDEN, BM_face_edge_share_loop(), BMLoop::f, BMLoop::next, and BMLoop::radial_next.
Referenced by bmo_extrude_edge_only_exec(), and bmo_extrude_face_region_exec().
void bmo_extrude_edge_only_exec (BMesh * bm, BMOperator * op)
Definition at line 170 of file bmo_extrude.c.
References BM_ALL, BM_EDGE, bm_extrude_copy_face_loop_attributes(), BM_face_create_quad_tri(), BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_iter_map_value(), BMO_iter_new(), BMO_iter_step(), BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_from_enabled_flag(), EXT_INPUT, EXT_KEEP, FALSE, BMEdge::l, NULL, BMLoop::v, BMEdge::v1, and BMEdge::v2.
void bmo_extrude_face_indiv_exec (BMesh * bm, BMOperator * op)
Definition at line 48 of file bmo_extrude.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BM_edge_create(), BM_edge_other_vert(), BM_elem_attrs_copy(), BM_FACE, BM_face_create_ngon(), BM_face_create_quad_tri(), BM_FACE_FIRST_LOOP, BM_ITER_ELEM, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BM_vert_create(), BMERR_MESH_ERROR, BMO_elem_flag_enable, BMO_error_raise(), BMO_ITER, BMO_op_callf(), BMO_slot_buffer_from_enabled_flag(), BMVert::co, DEL_ONLYFACES, BMLoop::e, EXT_DEL, EXT_KEEP, FALSE, i, BMFace::len, BMLoop::next, NULL, and BMLoop::v.
void bmo_extrude_face_region_exec (BMesh * bm, BMOperator * op)
Definition at line 241 of file bmo_extrude.c.
References BMesh::act_face, BM_EDGE, BM_edge_create(), BM_edge_is_wire(), BM_edge_kill(), BM_EDGES_OF_MESH, BM_EDGES_OF_VERT, bm_extrude_copy_face_loop_attributes(), BM_FACE, BM_face_create_quad_tri_v(), BM_face_normal_flip(), BM_FACES_OF_EDGE, BM_FACES_OF_MESH, BM_FACES_OF_VERT, BM_ITER_ELEM, BM_ITER_MESH, BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_iter_map_value(), BMO_iter_new(), BMO_iter_step(), BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_op_initf(), BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_copy(), BMO_slot_map_contains(), BMO_slot_map_ptr_get(), DEL_ONLYTAGGED, BMVert::e, EXT_DEL, EXT_INPUT, FALSE, BMEdge::l, NULL, TRUE, BMLoop::v, BMEdge::v1, and BMEdge::v2.
void bmo_extrude_vert_indiv_exec (BMesh * bm, BMOperator * op)
Definition at line 222 of file bmo_extrude.c.
References BM_EDGE, BM_edge_create(), BM_VERT, BM_vert_create(), BMO_elem_flag_enable, BMO_iter_new(), BMO_iter_step(), BMO_slot_buffer_from_enabled_flag(), BMVert::co, EXT_KEEP, FALSE, and NULL.
void bmo_solidify_face_region_exec (BMesh * bm, BMOperator * op)
Definition at line 610 of file bmo_extrude.c.
References BM_FACE, BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_op_initf(), BMO_slot_buffer_flag_enable(), BMO_slot_copy(), BMO_slot_float_get(), calc_solidify_normals(), FACE_MARK, solidify_add_thickness(), and TRUE.
static void calc_solidify_normals (BMesh * bm) [static]
Definition at line 406 of file bmo_extrude.c.
References add_v3_v3(), add_v3_v3v3(), angle(), angle_normalized_v3v3(), BLI_assert, BM_EDGE, BM_EDGES_OF_FACE, BM_EDGES_OF_MESH, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_elem_index_get, BM_ELEM_TAG, BM_FACES_OF_EDGE, BM_FACES_OF_MESH, BM_FACES_OF_VERT, BM_ITER_ELEM, BM_ITER_MESH, BM_mesh_elem_index_ensure(), BM_vert_is_manifold(), BM_vert_normal_update(), BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, copy_v3_v3(), EDGE_MARK, EDGE_NONMAN, FACE_MARK, i, M_PI, MEM_callocN(), MEM_freeN(), mul_v3_fl(), BMFace::no, BMVert::no, normalize_v3(), NULL, BMesh::totedge, BMEdge::v1, BMEdge::v2, VERT_MARK, VERT_NONMAN, and zero_v3().
Referenced by bmo_solidify_face_region_exec().
static void solidify_add_thickness (BMesh * bm, const float dist) [static]
Definition at line 552 of file bmo_extrude.c.
References angle_normalized_v3v3(), angle_poly_v3(), BLI_array_empty, BLI_array_free, BLI_array_growitems, BLI_array_staticdeclare, BM_elem_index_get, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_ELEM_INDEX, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_index_ensure(), BM_NGON_STACK_SIZE, BM_VERT, BM_VERTS_OF_MESH, BMO_elem_flag_test, BMVert::co, FACE_MARK, i, BMFace::len, madd_v3_v3fl(), MEM_callocN(), MEM_freeN(), BMFace::no, BMVert::no, NULL, shell_angle_to_dist(), BMesh::totvert, and BMLoop::v.
Referenced by bmo_solidify_face_region_exec().