Blender: btGjkEpaPenetrationDepthSolver Class Reference
btGjkEpaPenetrationDepthSolver Class Reference
#include <btGjkEpaPenetrationDepthSolver.h>
Public Member Functions
btGjkEpaPenetrationDepthSolver ()
bool calcPenDepth (btSimplexSolverInterface &simplexSolver, const btConvexShape *pConvexA, const btConvexShape *pConvexB, const btTransform &transformA, const btTransform &transformB, btVector3 &v, btVector3 &wWitnessOnA, btVector3 &wWitnessOnB, class btIDebugDraw *debugDraw, btStackAlloc *stackAlloc)
Detailed Description
EpaPenetrationDepthSolver uses the Expanding Polytope Algorithm to calculate the penetration depth between two convex shapes.
Definition at line 24 of file btGjkEpaPenetrationDepthSolver.h.
Constructor & Destructor Documentation
btGjkEpaPenetrationDepthSolver::btGjkEpaPenetrationDepthSolver () [inline]
Definition at line 28 of file btGjkEpaPenetrationDepthSolver.h.
Member Function Documentation
bool btGjkEpaPenetrationDepthSolver::calcPenDepth (btSimplexSolverInterface & simplexSolver, const btConvexShape * pConvexA, const btConvexShape * pConvexB, const btTransform & transformA, const btTransform & transformB, btVector3 & v, btVector3 & wWitnessOnA, btVector3 & wWitnessOnB, class btIDebugDraw * debugDraw, btStackAlloc * stackAlloc) [virtual]
Implements btConvexPenetrationDepthSolver.
Definition at line 24 of file btGjkEpaPenetrationDepthSolver.cpp.
References btGjkEpaSolver2::Distance(), btTransform::getOrigin(), btGjkEpaSolver2::Penetration(), and btGjkEpaSolver2::sResults::witnesses.
The documentation for this class was generated from the following files:
btGjkEpaPenetrationDepthSolver.h
btGjkEpaPenetrationDepthSolver.cpp