Blender: GPU_material.h File Reference
GPU_material.h File Reference
GPU
#include "DNA_listBase.h"
Classes
struct GPUNodeStack
struct GPUShadeInput
struct GPUShadeResult
struct GPUInputUniform
struct GPUInputAttribute
struct GPUShaderExport
Typedefs
typedef struct GPUNode GPUNode
typedef struct GPUNodeLink GPUNodeLink
typedef struct GPUMaterial GPUMaterial
typedef struct GPULamp GPULamp
typedef enum GPUType GPUType
typedef enum GPUBuiltin GPUBuiltin
typedef enum GPUBlendMode GPUBlendMode
typedef struct GPUNodeStack GPUNodeStack
typedef struct GPUShadeInput GPUShadeInput
typedef struct GPUShadeResult GPUShadeResult
typedef enum GPUDynamicType GPUDynamicType
typedef enum GPUDataType GPUDataType
typedef struct GPUInputUniform GPUInputUniform
typedef struct GPUInputAttribute GPUInputAttribute
typedef struct GPUShaderExport GPUShaderExport
Enumerations
enum GPUType {
GPU_NONE = 0, GPU_FLOAT = 1, GPU_VEC2 = 2, GPU_VEC3 = 3,
GPU_VEC4 = 4, GPU_MAT3 = 9, GPU_MAT4 = 16, GPU_TEX2D = 1002,
GPU_SHADOW2D = 1003, GPU_ATTRIB = 3001
}
enum GPUBuiltin {
GPU_VIEW_MATRIX = 1, GPU_OBJECT_MATRIX = 2, GPU_INVERSE_VIEW_MATRIX = 4, GPU_INVERSE_OBJECT_MATRIX = 8,
GPU_VIEW_POSITION = 16, GPU_VIEW_NORMAL = 32, GPU_OBCOLOR = 64, GPU_AUTO_BUMPSCALE = 128
}
enum GPUBlendMode {
GPU_BLEND_SOLID = 0, GPU_BLEND_ADD = 1, GPU_BLEND_ALPHA = 2, GPU_BLEND_CLIP = 4,
GPU_BLEND_ALPHA_SORT = 8
}
enum GPUDynamicType {
GPU_DYNAMIC_NONE = 0, GPU_DYNAMIC_OBJECT_VIEWMAT = 1, GPU_DYNAMIC_OBJECT_MAT = 2, GPU_DYNAMIC_OBJECT_VIEWIMAT = 3,
GPU_DYNAMIC_OBJECT_IMAT = 4, GPU_DYNAMIC_OBJECT_COLOR = 5, GPU_DYNAMIC_OBJECT_AUTOBUMPSCALE = 15, GPU_DYNAMIC_LAMP_FIRST = 6,
GPU_DYNAMIC_LAMP_DYNVEC = 6, GPU_DYNAMIC_LAMP_DYNCO = 7, GPU_DYNAMIC_LAMP_DYNIMAT = 8, GPU_DYNAMIC_LAMP_DYNPERSMAT = 9,
GPU_DYNAMIC_LAMP_DYNENERGY = 10, GPU_DYNAMIC_LAMP_DYNCOL = 11, GPU_DYNAMIC_LAMP_LAST = 11, GPU_DYNAMIC_SAMPLER_2DBUFFER = 12,
GPU_DYNAMIC_SAMPLER_2DIMAGE = 13, GPU_DYNAMIC_SAMPLER_2DSHADOW = 14
}
enum GPUDataType {
GPU_DATA_NONE = 0, GPU_DATA_1I = 1, GPU_DATA_1F = 2, GPU_DATA_2F = 3,
GPU_DATA_3F = 4, GPU_DATA_4F = 5, GPU_DATA_9F = 6, GPU_DATA_16F = 7,
GPU_DATA_4UB = 8
}
Functions
GPUNodeLink * GPU_attribute (int type, const char *name)
GPUNodeLink * GPU_uniform (float *num)
GPUNodeLink * GPU_dynamic_uniform (float *num, int dynamictype, void *data)
GPUNodeLink * GPU_image (struct Image *ima, struct ImageUser *iuser)
GPUNodeLink * GPU_texture (int size, float *pixels)
GPUNodeLink * GPU_dynamic_texture (struct GPUTexture *tex, int dynamictype, void *data)
GPUNodeLink * GPU_socket (GPUNodeStack *sock)
GPUNodeLink * GPU_builtin (GPUBuiltin builtin)
int GPU_link (GPUMaterial *mat, const char *name,...)
int GPU_stack_link (GPUMaterial *mat, const char *name, GPUNodeStack *in, GPUNodeStack *out,...)
void GPU_material_output_link (GPUMaterial *material, GPUNodeLink *link)
void GPU_material_enable_alpha (GPUMaterial *material)
GPUBlendMode GPU_material_alpha_blend (GPUMaterial *material, float obcol[4])
GPUMaterial * GPU_material_from_blender (struct Scene *scene, struct Material *ma)
void GPU_material_free (struct Material *ma)
void GPU_materials_free (void)
void GPU_material_bind (GPUMaterial *material, int oblay, int viewlay, double time, int mipmap)
void GPU_material_bind_uniforms (GPUMaterial *material, float obmat[][4], float viewmat[][4], float viewinv[][4], float obcol[4], float autobumpscale)
void GPU_material_unbind (GPUMaterial *material)
int GPU_material_bound (GPUMaterial *material)
void GPU_material_vertex_attributes (GPUMaterial *material, struct GPUVertexAttribs *attrib)
void GPU_shadeinput_set (GPUMaterial *mat, struct Material *ma, GPUShadeInput *shi)
void GPU_shaderesult_set (GPUShadeInput *shi, GPUShadeResult *shr)
GPUShaderExport * GPU_shader_export (struct Scene *scene, struct Material *ma)
void GPU_free_shader_export (GPUShaderExport *shader)
GPULamp * GPU_lamp_from_blender (struct Scene *scene, struct Object *ob, struct Object *par)
void GPU_lamp_free (struct Object *ob)
int GPU_lamp_has_shadow_buffer (GPULamp *lamp)
void GPU_lamp_shadow_buffer_bind (GPULamp *lamp, float viewmat[][4], int *winsize, float winmat[][4])
void GPU_lamp_shadow_buffer_unbind (GPULamp *lamp)
void GPU_lamp_update (GPULamp *lamp, int lay, int hide, float obmat[][4])
void GPU_lamp_update_colors (GPULamp *lamp, float r, float g, float b, float energy)
int GPU_lamp_shadow_layer (GPULamp *lamp)
Detailed Description
Definition in file GPU_material.h.
Typedef Documentation
typedef enum GPUBlendMode GPUBlendMode
typedef enum GPUBuiltin GPUBuiltin
typedef enum GPUDataType GPUDataType
typedef enum GPUDynamicType GPUDynamicType
typedef struct GPUInputAttribute GPUInputAttribute
typedef struct GPUInputUniform GPUInputUniform
typedef struct GPULamp GPULamp
Definition at line 61 of file GPU_material.h.
typedef struct GPUMaterial GPUMaterial
Definition at line 60 of file GPU_material.h.
typedef struct GPUNode GPUNode
Definition at line 58 of file GPU_material.h.
typedef struct GPUNodeLink GPUNodeLink
Definition at line 59 of file GPU_material.h.
typedef struct GPUNodeStack GPUNodeStack
typedef struct GPUShadeInput GPUShadeInput
typedef struct GPUShadeResult GPUShadeResult
typedef struct GPUShaderExport GPUShaderExport
typedef enum GPUType GPUType
Enumeration Type Documentation
enum GPUBlendMode
Enumerator:
GPU_BLEND_SOLID
GPU_BLEND_ADD
GPU_BLEND_ALPHA
GPU_BLEND_CLIP
GPU_BLEND_ALPHA_SORT
Definition at line 89 of file GPU_material.h.
enum GPUBuiltin
Enumerator:
GPU_VIEW_MATRIX
GPU_OBJECT_MATRIX
GPU_INVERSE_VIEW_MATRIX
GPU_INVERSE_OBJECT_MATRIX
GPU_VIEW_POSITION
GPU_VIEW_NORMAL
GPU_OBCOLOR
GPU_AUTO_BUMPSCALE
Definition at line 78 of file GPU_material.h.
enum GPUDataType
Enumerator:
GPU_DATA_NONE
GPU_DATA_1I
GPU_DATA_1F
GPU_DATA_2F
GPU_DATA_3F
GPU_DATA_4F
GPU_DATA_9F
GPU_DATA_16F
GPU_DATA_4UB
Definition at line 178 of file GPU_material.h.
enum GPUDynamicType
Enumerator:
GPU_DYNAMIC_NONE
GPU_DYNAMIC_OBJECT_VIEWMAT
GPU_DYNAMIC_OBJECT_MAT
GPU_DYNAMIC_OBJECT_VIEWIMAT
GPU_DYNAMIC_OBJECT_IMAT
GPU_DYNAMIC_OBJECT_COLOR
GPU_DYNAMIC_OBJECT_AUTOBUMPSCALE
GPU_DYNAMIC_LAMP_FIRST
GPU_DYNAMIC_LAMP_DYNVEC
GPU_DYNAMIC_LAMP_DYNCO
GPU_DYNAMIC_LAMP_DYNIMAT
GPU_DYNAMIC_LAMP_DYNPERSMAT
GPU_DYNAMIC_LAMP_DYNENERGY
GPU_DYNAMIC_LAMP_DYNCOL
GPU_DYNAMIC_LAMP_LAST
GPU_DYNAMIC_SAMPLER_2DBUFFER
GPU_DYNAMIC_SAMPLER_2DIMAGE
GPU_DYNAMIC_SAMPLER_2DSHADOW
Definition at line 157 of file GPU_material.h.
enum GPUType
Enumerator:
GPU_NONE
GPU_FLOAT
GPU_VEC2
GPU_VEC3
GPU_VEC4
GPU_MAT3
GPU_MAT4
GPU_TEX2D
GPU_SHADOW2D
GPU_ATTRIB
Definition at line 65 of file GPU_material.h.
Function Documentation
GPUNodeLink* GPU_attribute (int type, const char * name)
Definition at line 1072 of file gpu_codegen.c.
References GPUNodeLink::attribname, GPUNodeLink::attribtype, GPU_node_link_create(), and link().
Referenced by do_material_tex(), GPU_shadeinput_set(), gpu_shader_geom(), node_shader_gpu_tex_checker(), node_shader_gpu_tex_coord(), node_shader_gpu_tex_gradient(), node_shader_gpu_tex_image(), node_shader_gpu_tex_magic(), node_shader_gpu_tex_musgrave(), node_shader_gpu_tex_noise(), node_shader_gpu_tex_sky(), node_shader_gpu_tex_voronoi(), node_shader_gpu_tex_wave(), and shade_one_light().
GPUNodeLink* GPU_builtin (GPUBuiltin builtin)
Definition at line 1148 of file gpu_codegen.c.
References GPUNodeLink::builtin, GPU_node_link_create(), and link().
Referenced by do_material_tex(), GPU_shadeinput_set(), gpu_shader_camera(), gpu_shader_geom(), GPU_shaderesult_set(), lamp_get_visibility(), node_shader_gpu_bsdf_anisotropic(), node_shader_gpu_bsdf_diffuse(), node_shader_gpu_bsdf_glass(), node_shader_gpu_bsdf_glossy(), node_shader_gpu_bsdf_translucent(), node_shader_gpu_bsdf_velvet(), node_shader_gpu_emission(), node_shader_gpu_fresnel(), node_shader_gpu_geometry(), node_shader_gpu_tex_coord(), node_shader_gpu_tex_environment(), and shade_one_light().
GPUNodeLink* GPU_dynamic_texture (struct GPUTexture * tex, int dynamictype, void * data)
Definition at line 1127 of file gpu_codegen.c.
References data, GPUNodeLink::dynamic, GPUNodeLink::dynamictex, GPUNodeLink::dynamictype, GPU_node_link_create(), link(), and GPUNodeLink::ptr2.
Referenced by shade_one_light().
GPUNodeLink* GPU_dynamic_uniform (float * num, int dynamictype, void * data)
Definition at line 1092 of file gpu_codegen.c.
References data, GPUNodeLink::dynamic, GPUNodeLink::dynamictype, GPU_node_link_create(), link(), GPUNodeLink::ptr1, and GPUNodeLink::ptr2.
Referenced by lamp_get_visibility(), and shade_one_light().
void GPU_free_shader_export (GPUShaderExport * shader)
Definition at line 1880 of file gpu_material.c.
References GPUShaderExport::attributes, BLI_freelistN(), ListBase::first, GPUShaderExport::fragment, MEM_freeN(), GPUInputUniform::next, NULL, GPUInputUniform::texpixels, GPUShaderExport::uniforms, and GPUShaderExport::vertex.
Referenced by GPU_export_shader().
GPUNodeLink* GPU_image (struct Image * ima, struct ImageUser * iuser)
Definition at line 1105 of file gpu_codegen.c.
References GPU_node_link_create(), GPUNodeLink::image, link(), GPUNodeLink::ptr1, and GPUNodeLink::ptr2.
Referenced by do_material_tex(), gpu_shader_texture(), node_shader_gpu_tex_environment(), and node_shader_gpu_tex_image().
void GPU_lamp_free (struct Object * ob)
Definition at line 1633 of file gpu_material.c.
References BLI_freelinkN(), BLI_freelistN(), LinkData::data, ListBase::first, gpu_lamp_shadow_free(), GPU_material_free(), Object::gpulamp, Material::gpumaterial, link(), GPULamp::materials, MEM_freeN(), and LinkData::next.
Referenced by free_object(), GPU_materials_free(), lamp_changed(), and scene_changed().
GPULamp* GPU_lamp_from_blender (struct Scene * scene, struct Object * ob, struct Object * par)
Definition at line 1586 of file gpu_material.c.
References BLI_addtail(), Object::data, LinkData::data, GPULamp::fb, ListBase::first, GPU_framebuffer_create(), GPU_framebuffer_restore(), GPU_framebuffer_texture_attach(), gpu_lamp_from_blender(), gpu_lamp_shadow_free(), GPU_texture_create_depth(), Object::gpulamp, if(), LA_SHAD_BUF, LA_SPOT, link(), MEM_callocN(), Lamp::mode, LinkData::next, NULL, GPULamp::par, GPULamp::scene, GPULamp::size, GPULamp::tex, and Lamp::type.
Referenced by KX_LightObject::GetGPULamp(), gpu_render_lamp_update(), and material_lights().
int GPU_lamp_has_shadow_buffer (GPULamp * lamp)
Definition at line 1660 of file gpu_material.c.
References GPULamp::fb, GameData::flag, GAME_GLSL_NO_LIGHTS, GAME_GLSL_NO_SHADOWS, Scene::gm, GPULamp::scene, and GPULamp::tex.
Referenced by gpu_render_lamp_update(), KX_LightObject::HasShadowBuffer(), and shade_one_light().
void GPU_lamp_shadow_buffer_bind (GPULamp * lamp, float viewmat[][4], int * winsize, float winmat[][4])
Definition at line 1667 of file gpu_material.c.
References copy_m4_m4(), GPULamp::fb, GPU_framebuffer_texture_bind(), GPU_texture_opengl_height(), GPU_texture_opengl_width(), invert_m4_m4(), mult_m4_m4m4(), normalize_v3(), GPULamp::obmat, GPULamp::persmat, GPULamp::size, GPULamp::tex, unit_m4(), GPULamp::viewmat, and GPULamp::winmat.
Referenced by KX_LightObject::BindShadowBuffer(), and gpu_update_lamps_shadows().
void GPU_lamp_shadow_buffer_unbind (GPULamp * lamp)
Definition at line 1702 of file gpu_material.c.
References GPULamp::fb, GPU_framebuffer_restore(), GPU_framebuffer_texture_unbind(), and GPULamp::tex.
Referenced by gpu_update_lamps_shadows(), and KX_LightObject::UnbindShadowBuffer().
int GPU_lamp_shadow_layer (GPULamp * lamp)
Definition at line 1709 of file gpu_material.c.
References GPULamp::fb, LA_LAYER, LA_LAYER_SHADOW, GPULamp::lay, GPULamp::mode, and GPULamp::tex.
Referenced by KX_LightObject::GetShadowLayer(), and gpu_update_lamps_shadows().
void GPU_lamp_update (GPULamp * lamp, int lay, int hide, float obmat[][4])
Definition at line 1494 of file gpu_material.c.
References GPULamp::co, copy_m4_m4(), copy_v3_v3(), GPULamp::hide, GPULamp::imat, invert_m4_m4(), GPULamp::lay, normalize_m4(), GPULamp::obmat, and GPULamp::vec.
Referenced by gpu_lamp_from_blender(), gpu_render_lamp_update(), KX_LightObject::Update(), and KX_LightObject::~KX_LightObject().
void GPU_lamp_update_colors (GPULamp * lamp, float r, float g, float b, float energy)
Definition at line 1510 of file gpu_material.c.
References GPULamp::col, GPULamp::energy, LA_NEG, and GPULamp::mode.
Referenced by gpu_render_lamp_update(), and KX_LightObject::Update().
int GPU_link (GPUMaterial * mat, const char * name, ...)
Definition at line 1157 of file gpu_codegen.c.
References FUNCTION_QUAL_IN, GPU_lookup_function(), gpu_material_add_node(), GPU_node_begin(), GPU_node_end(), gpu_node_input_link(), GPU_node_output(), i, link(), GPUFunction::paramqual, GPUFunction::paramtype, and GPUFunction::totparam.
Referenced by add_to_diffuse(), do_colorband_blend(), do_material_tex(), do_specular_ramp(), GPU_material_from_blender(), GPU_shadeinput_set(), gpu_shader_material(), GPU_shaderesult_set(), lamp_get_visibility(), node_shader_gpu_tex_mapping(), ramp_blend(), ramp_diffuse_result(), ramp_spec_result(), shade_one_light(), texture_rgb_blend(), and texture_value_blend().
GPUBlendMode GPU_material_alpha_blend (GPUMaterial * material, float obcol[4])
Definition at line 362 of file gpu_material.c.
References GPUMaterial::alpha, GPU_BLEND_ALPHA, GPU_BLEND_SOLID, and GPUMaterial::obcolalpha.
Referenced by GPU_begin_object_materials(), and LOD_QuadricEditor::Update().
void GPU_material_bind (GPUMaterial * material, int oblay, int viewlay, double time, int mipmap)
Definition at line 252 of file gpu_material.c.
References GPUMaterial::bound, GPULamp::col, copy_v3_v3(), LinkData::data, GPULamp::dyncol, GPULamp::dynenergy, GPULamp::energy, ListBase::first, GPU_pass_bind(), GPULamp::hide, LA_LAYER, GPUMaterial::lamps, GPULamp::lay, GPULamp::mode, LinkData::next, and GPUMaterial::pass.
Referenced by GPU_enable_material(), and BL_BlenderShader::SetProg().
void GPU_material_bind_uniforms (GPUMaterial * material, float obmat[][4], float viewmat[][4], float viewinv[][4], float obcol[4], float autobumpscale)
Definition at line 277 of file gpu_material.c.
References GPUMaterial::builtins, CLAMP(), GPULamp::co, copy_v3_v3(), copy_v4_v4(), LinkData::data, DYN_LAMP_CO, DYN_LAMP_IMAT, DYN_LAMP_PERSMAT, DYN_LAMP_VEC, GPULamp::dynco, GPULamp::dynimat, GPULamp::dynpersmat, GPUMaterial::dynproperty, GPULamp::dynvec, ListBase::first, GPU_AUTO_BUMPSCALE, GPU_INVERSE_OBJECT_MATRIX, GPU_INVERSE_VIEW_MATRIX, GPU_OBCOLOR, GPU_OBJECT_MATRIX, GPU_pass_shader(), GPU_pass_update_uniforms(), GPU_shader_uniform_vector(), GPU_VIEW_MATRIX, GPULamp::imat, invert_m4_m4(), GPUMaterial::invobmatloc, GPUMaterial::invviewmatloc, GPUMaterial::lamps, mul_m4_v3(), mul_mat3_m4_v3(), mult_m4_m4m4(), negate_v3(), LinkData::next, normalize_v3(), GPUMaterial::obautobumpscaleloc, GPUMaterial::obcolloc, GPUMaterial::obmatloc, GPUMaterial::pass, GPULamp::persmat, GPULamp::vec, and GPUMaterial::viewmatloc.
Referenced by GPU_enable_material(), and LOD_QuadricEditor::Update().
int GPU_material_bound (GPUMaterial * material)
Definition at line 341 of file gpu_material.c.
References GPUMaterial::bound.
Referenced by LOD_QuadricEditor::Update().
void GPU_material_enable_alpha (GPUMaterial * material)
Definition at line 357 of file gpu_material.c.
References GPUMaterial::alpha.
Referenced by gpu_shader_output(), and GPU_shaderesult_set().
void GPU_material_free (struct Material * ma)
Definition at line 223 of file gpu_material.c.
References BLI_freelinkN(), BLI_freelistN(), LinkData::data, ListBase::first, GPU_pass_free(), Material::gpumaterial, GPUMaterial::lamps, link(), GPULamp::materials, MEM_freeN(), LinkData::next, next, and GPUMaterial::pass.
Referenced by ED_node_set_active(), free_material(), GPU_codegen_exit(), GPU_lamp_free(), GPU_materials_free(), lamp_changed(), material_changed(), paste_matcopybuf(), scene_changed(), texture_changed(), and world_changed().
GPUMaterial* GPU_material_from_blender (struct Scene * scene, struct Material * ma)
Definition at line 1433 of file gpu_material.c.
References BLI_addtail(), LinkData::data, ListBase::first, GameData::flag, GAME_GLSL_NO_NODES, Scene::gm, GPU_blender_material(), gpu_do_color_management(), GPU_link(), GPU_material_construct_begin(), GPU_material_construct_end(), GPU_material_output_link(), Material::gpumaterial, link(), MEM_callocN(), LinkData::next, Material::nodetree, ntreeGPUMaterialNodes(), GPUMaterial::outlink, GPUMaterial::scene, scene_use_new_shading_nodes(), and Material::use_nodes.
Referenced by GPU_begin_object_materials(), GPU_disable_material(), GPU_enable_material(), GPU_shader_export(), RAS_OpenGLRasterizer::IndexPrimitivesInternal(), and BL_BlenderShader::ReloadMaterial().
void GPU_material_output_link (GPUMaterial * material, GPUNodeLink * link)
Definition at line 351 of file gpu_material.c.
References link(), and GPUMaterial::outlink.
Referenced by GPU_material_from_blender(), gpu_shader_output(), and node_shader_gpu_output_material().
void GPU_material_unbind (GPUMaterial * material)
Definition at line 333 of file gpu_material.c.
References GPUMaterial::bound, GPU_pass_unbind(), and GPUMaterial::pass.
Referenced by GPU_disable_material(), GPU_enable_material(), BL_BlenderShader::SetProg(), and BL_BlenderShader::~BL_BlenderShader().
void GPU_material_vertex_attributes (GPUMaterial * material, struct GPUVertexAttribs * attrib)
Definition at line 346 of file gpu_material.c.
References GPUMaterial::attribs.
Referenced by BL_BlenderShader::GetAttribNum(), GPU_enable_material(), RAS_OpenGLRasterizer::IndexPrimitivesInternal(), and BL_BlenderShader::SetAttribs().
void GPU_materials_free (void)
Definition at line 1477 of file gpu_material.c.
References defmaterial, G, GPU_lamp_free(), GPU_material_free(), Material::id, Object::id, and ID::next.
void GPU_shadeinput_set (GPUMaterial * mat, struct Material * ma, GPUShadeInput * shi)
Definition at line 1294 of file gpu_material.c.
References Material::alpha, GPUShadeInput::alpha, GPUShadeInput::amb, Material::amb, CD_MCOL, GPUShadeInput::emit, Material::emit, GPU_attribute(), GPU_builtin(), gpu_do_color_management(), GPU_link(), GPU_uniform(), GPU_VIEW_NORMAL, GPU_VIEW_POSITION, GPUShadeInput::gpumat, Material::har, GPUShadeInput::har, GPUShadeInput::mat, Material::r, Material::ref, GPUShadeInput::ref, GPUShadeInput::refl, GPUShadeInput::rgb, GPUShadeInput::spec, Material::spec, Material::specr, GPUShadeInput::specrgb, GPUShadeInput::vcol, GPUShadeInput::view, and GPUShadeInput::vn.
Referenced by GPU_blender_material(), and gpu_shader_material().
GPUShaderExport* GPU_shader_export (struct Scene * scene, struct Material * ma)
Definition at line 1719 of file gpu_material.c.
References GPUVertexAttribs::attribid, GPUMaterial::attribs, GPUShaderExport::attributes, BLI_addtail(), BLI_snprintf(), BLI_strdup(), BLI_strncpy(), GPUMaterial::builtins, CD_MCOL, CD_MTFACE, CD_ORCO, CD_TANGENT, GPUInputUniform::datatype, GPUInputAttribute::datatype, GPUInput::dynamicdata, GPUInput::dynamictype, ListBase::first, GPUShaderExport::fragment, GPUPass::fragmentcode, GPUVertexAttribs::glindex, GPU_AUTO_BUMPSCALE, GPU_builtin_name(), GPU_DATA_16F, GPU_DATA_1F, GPU_DATA_1I, GPU_DATA_2F, GPU_DATA_3F, GPU_DATA_4F, GPU_DATA_4UB, GPU_DATA_9F, GPU_DATA_NONE, GPU_DYNAMIC_LAMP_FIRST, GPU_DYNAMIC_LAMP_LAST, GPU_DYNAMIC_NONE, GPU_DYNAMIC_OBJECT_AUTOBUMPSCALE, GPU_DYNAMIC_OBJECT_COLOR, GPU_DYNAMIC_OBJECT_IMAT, GPU_DYNAMIC_OBJECT_MAT, GPU_DYNAMIC_OBJECT_VIEWIMAT, GPU_DYNAMIC_OBJECT_VIEWMAT, GPU_DYNAMIC_SAMPLER_2DBUFFER, GPU_DYNAMIC_SAMPLER_2DIMAGE, GPU_DYNAMIC_SAMPLER_2DSHADOW, GPU_glsl_support(), GPU_INVERSE_OBJECT_MATRIX, GPU_INVERSE_VIEW_MATRIX, GPU_material_from_blender(), GPU_OBCOLOR, GPU_OBJECT_MATRIX, GPU_SHADOW2D, GPU_TEX2D, GPU_texture_opengl_bindcode(), GPU_texture_opengl_height(), GPU_texture_opengl_width(), GPU_VIEW_MATRIX, i, if(), GPUInput::ima, GPUInputUniform::image, GPUPass::inputs, GPUInputUniform::lamp, GPUVertexAttribs::layer, GPUPass::libcode, MEM_callocN(), MEM_freeN(), MEM_mallocN(), GPUInputAttribute::name, GPUVertexAttribs::name, GPUInput::next, NULL, GPUInputAttribute::number, GPUMaterial::pass, GPUInput::shadername, strlen(), GPUInput::tex, GPUInput::texid, GPUInputUniform::texnumber, GPUInputUniform::texpixels, GPUInputUniform::texsize, GPUInput::textype, GPUVertexAttribs::totlayer, GPUInput::type, GPUInputUniform::type, GPUVertexAttribs::type, GPUInputAttribute::type, GPUShaderExport::uniforms, GPUInputUniform::varname, GPUInputAttribute::varname, GPUShaderExport::vertex, and GPUPass::vertexcode.
Referenced by GPU_export_shader().
void GPU_shaderesult_set (GPUShadeInput * shi, GPUShadeResult * shr)
Definition at line 1319 of file gpu_material.c.
References Material::alpha, GPUShadeInput::alpha, GPUShadeResult::alpha, GPUShadeInput::amb, Material::amb, World::ambb, World::ambg, World::ambr, GPUShadeResult::combined, GPUShadeResult::diff, do_material_tex(), GPUShadeInput::emit, Material::emit, World::exp, GameData::flag, GAME_GLSL_NO_LIGHTS, Scene::gm, GPU_builtin(), GPU_link(), GPU_link_changed(), GPU_material_enable_alpha(), GPU_OBCOLOR, GPU_uniform(), GPU_VIEW_POSITION, GPUShadeInput::gpumat, World::horr, logf, MA_NOMIST, MA_OBCOLOR, MA_RAMP_COL, MA_RAMP_SPEC, MA_SHLESS, MA_TRANSP, MA_VERTEXCOL, MA_VERTEXCOLP, MA_ZTRANSP, GPUShadeInput::mat, material_lights(), World::misi, World::mistdist, World::miststa, World::mistype, World::mode, Material::mode, GPUMaterial::obcolalpha, powf, ramp_diffuse_result(), ramp_spec_result(), World::range, GPUShadeInput::rgb, GPUMaterial::scene, Material::shade_flag, GPUShadeInput::spec, Material::spec, GPUShadeResult::spec, GPUShadeInput::vcol, WO_MIST, and Scene::world.
Referenced by GPU_blender_material(), and gpu_shader_material().
GPUNodeLink* GPU_socket (GPUNodeStack * sock)
Definition at line 1139 of file gpu_codegen.c.
References GPU_node_link_create(), link(), and GPUNodeLink::socket.
Referenced by gpu_shader_math(), and gpu_shader_vect_math().
int GPU_stack_link (GPUMaterial * mat, const char * name, GPUNodeStack * in, GPUNodeStack * out, ...)
Definition at line 1193 of file gpu_codegen.c.
References FUNCTION_QUAL_IN, GPU_lookup_function(), gpu_material_add_node(), GPU_node_begin(), GPU_node_end(), gpu_node_input_link(), gpu_node_input_socket(), GPU_node_output(), GPU_NONE, i, link(), GPUFunction::paramqual, GPUFunction::paramtype, GPUNodeLink::socket, GPUFunction::totparam, and GPUNodeStack::type.
Referenced by gpu_shader_camera(), gpu_shader_combrgb(), gpu_shader_curve_rgb(), gpu_shader_curve_vec(), gpu_shader_geom(), gpu_shader_hue_sat(), gpu_shader_invert(), gpu_shader_mapping(), gpu_shader_math(), gpu_shader_mix_rgb(), gpu_shader_normal(), gpu_shader_output(), gpu_shader_rgb(), gpu_shader_rgbtobw(), gpu_shader_seprgb(), gpu_shader_squeeze(), gpu_shader_texture(), gpu_shader_valtorgb(), gpu_shader_value(), gpu_shader_vect_math(), node_shader_gpu_add_shader(), node_shader_gpu_bsdf_anisotropic(), node_shader_gpu_bsdf_diffuse(), node_shader_gpu_bsdf_glass(), node_shader_gpu_bsdf_glossy(), node_shader_gpu_bsdf_translucent(), node_shader_gpu_bsdf_transparent(), node_shader_gpu_bsdf_velvet(), node_shader_gpu_emission(), node_shader_gpu_fresnel(), node_shader_gpu_geometry(), node_shader_gpu_light_path(), node_shader_gpu_mix_shader(), node_shader_gpu_output_material(), node_shader_gpu_tex_checker(), node_shader_gpu_tex_coord(), node_shader_gpu_tex_environment(), node_shader_gpu_tex_gradient(), node_shader_gpu_tex_image(), node_shader_gpu_tex_magic(), node_shader_gpu_tex_musgrave(), node_shader_gpu_tex_noise(), node_shader_gpu_tex_sky(), node_shader_gpu_tex_voronoi(), and node_shader_gpu_tex_wave().
GPUNodeLink* GPU_texture (int size, float * pixels)
Definition at line 1116 of file gpu_codegen.c.
References GPU_node_link_create(), link(), GPUNodeLink::ptr1, size(), GPUNodeLink::texture, and GPUNodeLink::texturesize.
Referenced by do_colorband_blend(), gpu_shader_curve_rgb(), gpu_shader_curve_vec(), gpu_shader_valtorgb(), and lamp_get_visibility().
GPUNodeLink* GPU_uniform (float * num)
Definition at line 1082 of file gpu_codegen.c.
References GPU_node_link_create(), link(), NULL, GPUNodeLink::ptr1, and GPUNodeLink::ptr2.
Referenced by do_colorband_blend(), do_material_tex(), gpu_get_input_link(), GPU_shadeinput_set(), gpu_shader_mapping(), gpu_shader_normal(), gpu_shader_rgb(), gpu_shader_value(), GPU_shaderesult_set(), lamp_get_visibility(), node_shader_gpu_tex_environment(), node_shader_gpu_tex_image(), node_shader_gpu_tex_magic(), node_shader_gpu_tex_mapping(), and shade_one_light().