Blender: GlutMeshDrawer Class Reference
GlutMeshDrawer Class Reference
#include <GlutMeshDrawer.h>
Public Member Functions
void SetLODInfo (LOD_Decimation_InfoPtr info)
void SetMouseHandler (MyGlutMouseHandler *mouse_handler)
void Draw ()
~GlutMeshDrawer ()
Static Public Member Functions
static GlutMeshDrawer * New ()
Detailed Description
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) 2001-2002 by NaN Holding BV. All rights reserved.
The Original Code is: all of this file.
Contributor(s): none yet.
***** END GPL LICENSE BLOCK *****
Definition at line 53 of file GlutMeshDrawer.h.
Constructor & Destructor Documentation
GlutMeshDrawer::~GlutMeshDrawer () [inline]
Definition at line 93 of file GlutMeshDrawer.h.
Member Function Documentation
void GlutMeshDrawer::Draw (void) [inline, virtual]
Implements GlutDrawer.
Definition at line 82 of file GlutMeshDrawer.h.
References MyGlutMouseHandler::AngleX(), and MyGlutMouseHandler::AngleY().
static GlutMeshDrawer* GlutMeshDrawer::New () [inline, static]
Definition at line 58 of file GlutMeshDrawer.h.
Referenced by main().
void GlutMeshDrawer::SetLODInfo (LOD_Decimation_InfoPtr info) [inline]
Definition at line 66 of file GlutMeshDrawer.h.
void GlutMeshDrawer::SetMouseHandler (MyGlutMouseHandler * mouse_handler) [inline]
Definition at line 73 of file GlutMeshDrawer.h.
The documentation for this class was generated from the following file:
GlutMeshDrawer.h