Blender: LOD_Quadric Class Reference
LOD_Quadric Class Reference
#include <LOD_Quadric.h>
Public Member Functions
LOD_Quadric ()
LOD_Quadric (const MT_Vector3 &vec, const MT_Scalar &offset)
MT_Matrix3x3 Tensor () const
MT_Vector3 Vector () const
void Clear (MT_Scalar val=0.0)
LOD_Quadric & operator= (const LOD_Quadric &Q)
LOD_Quadric & operator+= (const LOD_Quadric &Q)
LOD_Quadric & operator*= (const MT_Scalar &s)
MT_Scalar Evaluate (const MT_Vector3 &v) const
bool Optimize (MT_Vector3 &v) const
Detailed Description
Definition at line 40 of file LOD_Quadric.h.
Constructor & Destructor Documentation
LOD_Quadric::LOD_Quadric () [inline]
Definition at line 52 of file LOD_Quadric.h.
References Clear().
LOD_Quadric::LOD_Quadric (const MT_Vector3 & vec, const MT_Scalar & offset) [inline]
Definition at line 57 of file LOD_Quadric.h.
Member Function Documentation
void LOD_Quadric::Clear (MT_Scalar val = 0.0) [inline]
Definition at line 97 of file LOD_Quadric.h.
Referenced by LOD_NdQuadric::Clear(), and LOD_Quadric().
MT_Scalar LOD_Quadric::Evaluate (const MT_Vector3 & v) const [inline]
Definition at line 139 of file LOD_Quadric.h.
Referenced by LOD_QuadricEditor::BuildQuadrics().
LOD_Quadric& LOD_Quadric::operator*= (const MT_Scalar & s) [inline]
Definition at line 127 of file LOD_Quadric.h.
LOD_Quadric& LOD_Quadric::operator+= (const LOD_Quadric & Q) [inline]
Definition at line 116 of file LOD_Quadric.h.
LOD_Quadric& LOD_Quadric::operator= (const LOD_Quadric & Q) [inline]
Definition at line 104 of file LOD_Quadric.h.
bool LOD_Quadric::Optimize (MT_Vector3 & v) const [inline]
Definition at line 151 of file LOD_Quadric.h.
References MT_Matrix3x3::determinant(), MT_Matrix3x3::inverse(), MT_fuzzyZero(), Tensor(), and Vector().
Referenced by LOD_QuadricEditor::TargetVertex().
MT_Matrix3x3 LOD_Quadric::Tensor () const [inline]
Definition at line 78 of file LOD_Quadric.h.
Referenced by Optimize(), and LOD_NdQuadric::Tensor().
MT_Vector3 LOD_Quadric::Vector () const [inline]
Definition at line 91 of file LOD_Quadric.h.
Referenced by Optimize(), and LOD_NdQuadric::Vector().
The documentation for this class was generated from the following file:
LOD_Quadric.h