Blender: util_view.h File Reference
util_view.h File Reference
Typedefs
typedef void(* ViewExitFunc)(void)
typedef void(* ViewResizeFunc)(int width, int height)
typedef void(* ViewDisplayFunc)(void)
typedef void(* ViewKeyboardFunc)(unsigned char key)
Functions
void view_main_loop (const char *title, int width, int height, ViewInitFunc initf, ViewExitFunc exitf, ViewResizeFunc resize, ViewDisplayFunc display, ViewKeyboardFunc keyboard)
void view_display_info (const char *info)
void view_redraw ()
Variables
CCL_NAMESPACE_BEGIN typedef void(* ViewInitFunc)(void)
Typedef Documentation
typedef void(* ViewDisplayFunc)(void)
Definition at line 30 of file util_view.h.
typedef void(* ViewExitFunc)(void)
Definition at line 28 of file util_view.h.
typedef void(* ViewKeyboardFunc)(unsigned char key)
Definition at line 31 of file util_view.h.
typedef void(* ViewResizeFunc)(int width, int height)
Definition at line 29 of file util_view.h.
Function Documentation
void view_display_info (const char * info)
Definition at line 62 of file util_view.cpp.
References View::height, V, view_display_text(), and View::width.
Referenced by display_info().
void view_main_loop (const char * title, int width, int height, ViewInitFunc initf, ViewExitFunc exitf, ViewResizeFunc resize, ViewDisplayFunc display, ViewKeyboardFunc keyboard)
Definition at line 149 of file util_view.cpp.
References display(), View::display, View::exitf, View::first_display, View::height, initf, View::initf, keyboard(), View::keyboard, View::redraw, resize(), View::resize, V, view_display(), view_idle(), view_keyboard(), view_reshape(), and View::width.
Referenced by main().
void view_redraw ()
Definition at line 189 of file util_view.cpp.
References View::redraw, and V.
Referenced by session_init().
Variable Documentation
CCL_NAMESPACE_BEGIN typedef void(* ViewInitFunc)(void)
Definition at line 27 of file util_view.h.