Blender: space_image.c File Reference
space_image.c File Reference
image and UV editor
#include <string.h>
#include <stdio.h>
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BKE_colortools.h"
#include "BKE_context.h"
#include "BKE_image.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_mesh.h"
#include "BKE_scene.h"
#include "BKE_screen.h"
#include "BKE_tessmesh.h"
#include "IMB_imbuf_types.h"
#include "ED_image.h"
#include "ED_mesh.h"
#include "ED_space_api.h"
#include "ED_screen.h"
#include "ED_uvedit.h"
#include "BIF_gl.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "image_intern.h"
Functions
Image * ED_space_image (SpaceImage *sima)
void ED_space_image_set (SpaceImage *sima, Scene *scene, Object *obedit, Image *ima)
ImBuf * ED_space_image_acquire_buffer (SpaceImage *sima, void **lock_r)
void ED_space_image_release_buffer (SpaceImage *sima, void *lock)
int ED_space_image_has_buffer (SpaceImage *sima)
void ED_image_size (Image *ima, int *width, int *height)
void ED_space_image_size (SpaceImage *sima, int *width, int *height)
void ED_image_aspect (Image *ima, float *aspx, float *aspy)
void ED_space_image_aspect (SpaceImage *sima, float *aspx, float *aspy)
void ED_space_image_zoom (SpaceImage *sima, ARegion *ar, float *zoomx, float *zoomy)
void ED_space_image_uv_aspect (SpaceImage *sima, float *aspx, float *aspy)
void ED_image_uv_aspect (Image *ima, float *aspx, float *aspy)
int ED_space_image_show_render (SpaceImage *sima)
int ED_space_image_show_paint (SpaceImage *sima)
int ED_space_image_show_uvedit (SpaceImage *sima, Object *obedit)
int ED_space_image_show_uvshadow (SpaceImage *sima, Object *obedit)
static void image_scopes_tag_refresh (ScrArea *sa)
ARegion * image_has_buttons_region (ScrArea *sa)
ARegion * image_has_scope_region (ScrArea *sa)
static SpaceLink * image_new (const bContext *UNUSED(C))
static void image_free (SpaceLink *sl)
static void image_init (struct wmWindowManager *UNUSED(wm), ScrArea *sa)
static SpaceLink * image_duplicate (SpaceLink *sl)
static void image_operatortypes (void)
static void image_keymap (struct wmKeyConfig *keyconf)
static int image_drop_poll (bContext *UNUSED(C), wmDrag *drag, wmEvent *UNUSED(event))
static void image_drop_copy (wmDrag *drag, wmDropBox *drop)
static void image_dropboxes (void)
static void image_refresh (const bContext *C, ScrArea *UNUSED(sa))
static void image_listener (ScrArea *sa, wmNotifier *wmn)
static int image_context (const bContext *C, const char *member, bContextDataResult *result)
static void image_main_area_set_view2d (SpaceImage *sima, ARegion *ar)
static void image_main_area_init (wmWindowManager *wm, ARegion *ar)
static void image_main_area_draw (const bContext *C, ARegion *ar)
static void image_main_area_listener (ARegion *ar, wmNotifier *wmn)
static void image_buttons_area_init (wmWindowManager *wm, ARegion *ar)
static void image_buttons_area_draw (const bContext *C, ARegion *ar)
static void image_buttons_area_listener (ARegion *ar, wmNotifier *wmn)
static void image_scope_area_init (wmWindowManager *wm, ARegion *ar)
static void image_scope_area_draw (const bContext *C, ARegion *ar)
static void image_scope_area_listener (ARegion *ar, wmNotifier *wmn)
static void image_header_area_init (wmWindowManager *UNUSED(wm), ARegion *ar)
static void image_header_area_draw (const bContext *C, ARegion *ar)
static void image_header_area_listener (ARegion *ar, wmNotifier *wmn)
void ED_spacetype_image (void)
Variables
const char * image_context_dir [] = {"edit_image", NULL}
Detailed Description
Definition in file space_image.c.
Function Documentation
void ED_image_aspect (Image * ima, float * aspx, float * aspy)
Definition at line 202 of file space_image.c.
References Image::aspx, Image::aspy, IMA_TYPE_COMPOSITE, IMA_TYPE_R_RESULT, NULL, and Image::type.
Referenced by draw_image_main(), ED_image_uv_aspect(), ED_space_image_aspect(), and image_view_selected_exec().
void ED_image_size (Image * ima, int * width, int * height)
Definition at line 148 of file space_image.c.
References BKE_image_acquire_ibuf(), BKE_image_release_ibuf(), NULL, ImBuf::x, and ImBuf::y.
Referenced by ED_image_uv_aspect().
void ED_image_uv_aspect (Image * ima, float * aspx, float * aspy)
Definition at line 249 of file space_image.c.
References ED_image_aspect(), and ED_image_size().
Referenced by construct_param_handle(), construct_param_handle_subsurfed(), and correct_uv_aspect().
Image* ED_space_image (SpaceImage * sima) [read]
Definition at line 80 of file space_image.c.
References SpaceImage::image.
Referenced by CalcSnapGeometry(), draw_image_main(), draw_uvs_texpaint(), ED_space_image_aspect(), image_context(), image_main_area_set_view2d(), image_refresh(), image_save_as_invoke(), image_view_selected_exec(), and save_image_doit().
ImBuf* ED_space_image_acquire_buffer (SpaceImage * sima, void ** lock_r) [read]
Definition at line 110 of file space_image.c.
References BKE_image_acquire_ibuf(), IMA_TYPE_R_RESULT, SpaceImage::image, SpaceImage::iuser, NULL, ImBuf::rect, ImBuf::rect_float, and Image::type.
Referenced by draw_image_grease_pencil(), draw_image_main(), ED_space_image_has_buffer(), ED_space_image_size(), image_panel_curves(), image_panel_poll(), image_sample_apply(), image_sample_line_exec(), image_scope_area_draw(), save_image_doit(), save_image_options_init(), and space_image_file_exists_poll().
void ED_space_image_aspect (SpaceImage * sima, float * aspx, float * aspy)
Definition at line 214 of file space_image.c.
References ED_image_aspect(), and ED_space_image().
Referenced by drawSnapping(), ED_space_image_uv_aspect(), image_view_all_exec(), and sima_zoom_set().
int ED_space_image_has_buffer (SpaceImage * sima)
Definition at line 135 of file space_image.c.
References ED_space_image_acquire_buffer(), ED_space_image_release_buffer(), and NULL.
Referenced by image_sample_invoke(), image_sample_line_invoke(), and space_image_buffer_exists_poll().
void ED_space_image_release_buffer (SpaceImage * sima, void * lock)
Definition at line 129 of file space_image.c.
References BKE_image_release_ibuf(), and SpaceImage::image.
Referenced by draw_image_grease_pencil(), draw_image_main(), ED_space_image_has_buffer(), ED_space_image_size(), image_panel_curves(), image_panel_poll(), image_sample_apply(), image_sample_line_exec(), image_scope_area_draw(), save_image_doit(), save_image_options_init(), and space_image_file_exists_poll().
void ED_space_image_set (SpaceImage * sima, Scene * scene, Object * obedit, Image * ima)
Definition at line 86 of file space_image.c.
References BKE_image_signal(), Object::data, ED_uvedit_assign_image(), SpaceImage::flag, G, Image::id, IMA_SIGNAL_USER_NEW_IMAGE, IMA_TYPE_COMPOSITE, IMA_TYPE_R_RESULT, SpaceImage::image, SpaceImage::iuser, NC_GEOM, NC_SPACE, ND_DATA, ND_SPACE_IMAGE, NULL, SI_DRAWTOOL, Image::type, ID::us, and WM_main_add_notifier().
Referenced by image_new_exec(), and image_open_exec().
int ED_space_image_show_paint (SpaceImage * sima)
Definition at line 265 of file space_image.c.
References ED_space_image_show_render(), SpaceImage::flag, and SI_DRAWTOOL.
Referenced by ED_space_image_show_uvedit(), and ED_space_image_show_uvshadow().
int ED_space_image_show_render (SpaceImage * sima)
Definition at line 260 of file space_image.c.
References ELEM, IMA_TYPE_COMPOSITE, IMA_TYPE_R_RESULT, SpaceImage::image, and Image::type.
Referenced by ED_space_image_show_paint(), ED_space_image_show_uvedit(), ED_space_image_show_uvshadow(), and image_listener().
int ED_space_image_show_uvedit (SpaceImage * sima, Object * obedit)
Definition at line 273 of file space_image.c.
References BMEdit_FromObject(), ED_space_image_show_paint(), ED_space_image_show_render(), EDBM_mtexpoly_check(), OB_MESH, and Object::type.
Referenced by createTransUVs(), draw_uvedit_main(), ED_operator_uvedit(), ED_operator_uvedit_can_uv_sculpt(), and space_image_image_sample_poll().
int ED_space_image_show_uvshadow (SpaceImage * sima, Object * obedit)
Definition at line 290 of file space_image.c.
References BMEdit_FromObject(), ED_space_image_show_paint(), ED_space_image_show_render(), EDBM_mtexpoly_check(), OB_MESH, and Object::type.
Referenced by draw_uvedit_main().
void ED_space_image_size (SpaceImage * sima, int * width, int * height)
Definition at line 169 of file space_image.c.
References RenderData::border, ED_space_image_acquire_buffer(), ED_space_image_release_buffer(), IMA_TYPE_R_RESULT, SpaceImage::image, SpaceImage::iuser, RenderData::mode, Scene::r, R_BORDER, R_CROP, ImageUser::scene, RenderData::size, Image::type, ImBuf::x, rctf::xmax, rctf::xmin, RenderData::xsch, ImBuf::y, rctf::ymax, rctf::ymin, and RenderData::ysch.
Referenced by applyAspectRatio(), circle_select_exec(), do_uvedit_vertex(), drawcursor_sima(), ED_space_image_uv_aspect(), ED_space_image_zoom(), flushTransUVs(), image_main_area_set_view2d(), image_view_all_exec(), image_view_selected_exec(), removeAspectRatio(), sima_zoom_set(), snap_cursor_to_pixels(), snap_uvs_to_pixels(), uv_sculpt_stroke_apply(), uv_sculpt_stroke_init(), uvedit_pixel_to_float(), and uvedit_vertex_buttons().
void ED_space_image_uv_aspect (SpaceImage * sima, float * aspx, float * aspy)
Definition at line 229 of file space_image.c.
References ED_space_image_aspect(), and ED_space_image_size().
Referenced by applyAspectRatio(), applyGrid(), CalcSnapGeometry(), calculateCenterCursor2D(), clipUVTransform(), convertViewVec(), draw_uvs_stretch(), drawPropCircle(), flushTransUVs(), projectIntView(), removeAspectRatio(), and UVsToTransData().
void ED_space_image_zoom (SpaceImage * sima, ARegion * ar, float * zoomx, float * zoomy)
Definition at line 219 of file space_image.c.
References View2D::cur, ED_space_image_size(), ARegion::v2d, ARegion::winrct, rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, rctf::ymax, rcti::ymax, rctf::ymin, and rcti::ymin.
Referenced by circle_select_exec(), draw_image_main(), drawcursor_sima(), get_imapaint_zoom(), uv_sculpt_stroke_apply(), and uv_sculpt_stroke_init().
void ED_spacetype_image (void)
Definition at line 981 of file space_image.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), SpaceType::context, ARegionType::draw, SpaceType::dropboxes, SpaceType::duplicate, ED_KEYMAP_FRAMES, ED_KEYMAP_GPENCIL, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, ED_uvedit_buttons_register(), SpaceType::free, HEADERY, image_buttons_area_draw(), image_buttons_area_init(), image_buttons_area_listener(), image_buttons_register(), image_context(), image_dropboxes(), image_duplicate(), image_free(), image_header_area_draw(), image_header_area_init(), image_header_area_listener(), image_init(), image_keymap(), image_listener(), image_main_area_draw(), image_main_area_init(), image_main_area_listener(), image_new(), image_operatortypes(), image_refresh(), image_scope_area_draw(), image_scope_area_init(), image_scope_area_listener(), ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_PREVIEW, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_IMAGE, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
static void image_buttons_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 866 of file space_image.c.
References ED_region_panels(), and NULL.
Referenced by ED_spacetype_image().
static void image_buttons_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 856 of file space_image.c.
References wmWindowManager::defaultconf, ED_region_panels_init(), ARegion::handlers, SPACE_IMAGE, WM_event_add_keymap_handler(), and WM_keymap_find().
Referenced by ED_spacetype_image().
static void image_buttons_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 871 of file space_image.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NA_EDITED, NC_BRUSH, NC_MATERIAL, NC_SCREEN, NC_TEXTURE, and ND_GPENCIL.
Referenced by ED_spacetype_image().
static int image_context (const bContext * C, const char * member, bContextDataResult * result) [static]
Definition at line 696 of file space_image.c.
References CTX_data_dir(), CTX_data_dir_set(), CTX_data_equals(), CTX_data_id_pointer_set(), CTX_wm_space_image(), and ED_space_image().
Referenced by ED_spacetype_image().
static void image_drop_copy (wmDrag * drag, wmDropBox * drop) [static]
Definition at line 565 of file space_image.c.
References wmDrag::path, wmDropBox::ptr, and RNA_string_set().
Referenced by image_dropboxes().
static int image_drop_poll (bContext * UNUSEDC, wmDrag * drag, wmEvent * UNUSEDevent) [static]
Definition at line 557 of file space_image.c.
References ELEM3, wmDrag::icon, wmDrag::type, and WM_DRAG_PATH.
Referenced by image_dropboxes().
static void image_dropboxes (void) [static]
Definition at line 572 of file space_image.c.
References image_drop_copy(), image_drop_poll(), SPACE_IMAGE, WM_dropbox_add(), and WM_dropboxmap_find().
Referenced by ED_spacetype_image().
static SpaceLink* image_duplicate (SpaceLink * sl) [static]
Definition at line 448 of file space_image.c.
References SpaceImage::cumap, curvemapping_copy(), MEM_dupallocN(), SpaceImage::scopes, and scopes_new().
Referenced by ED_spacetype_image().
static void image_free (SpaceLink * sl) [static]
Definition at line 428 of file space_image.c.
References SpaceImage::cumap, curvemapping_free(), SpaceImage::scopes, and scopes_free().
Referenced by ED_spacetype_image().
ARegion* image_has_buttons_region (ScrArea * sa) [read]
Definition at line 326 of file space_image.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_LEFT, RGN_FLAG_HIDDEN, RGN_TYPE_HEADER, and RGN_TYPE_UI.
Referenced by image_properties().
ARegion* image_has_scope_region (ScrArea * sa) [read]
Definition at line 350 of file space_image.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, image_scopes_tag_refresh(), MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_RIGHT, RGN_FLAG_HIDDEN, RGN_TYPE_PREVIEW, and RGN_TYPE_UI.
Referenced by image_scopes().
static void image_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 950 of file space_image.c.
References ED_region_header().
Referenced by ED_spacetype_image().
static void image_header_area_init (wmWindowManager * UNUSEDwm, ARegion * ar) [static]
Definition at line 945 of file space_image.c.
References ED_region_header_init().
Referenced by ED_spacetype_image().
static void image_header_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 955 of file space_image.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NC_GEOM, NC_SCENE, ND_DATA, ND_MODE, ND_SELECT, and ND_TOOLSETTINGS.
Referenced by ED_spacetype_image().
static void image_init (struct wmWindowManager * UNUSEDwm, ScrArea * sa) [static]
Definition at line 439 of file space_image.c.
References ScrArea::handlers, SPACE_IMAGE, WM_dropboxmap_find(), and WM_event_add_dropbox_handler().
Referenced by ED_spacetype_image().
static void image_keymap (struct wmKeyConfig * keyconf) [static]
Definition at line 496 of file space_image.c.
References ACTIONMOUSE, F3KEY, HOMEKEY, i, IMA_MAX_RENDER_SLOT, JKEY, KM_ALT, KM_CTRL, KM_PRESS, KM_SHIFT, MAX2, MIDDLEMOUSE, MOUSEPAN, MOUSEZOOM, NDOF_BUTTON_FIT, NDOF_MOTION, NKEY, OB_MODE_EDIT, OKEY, ONEKEY, PAD1, PAD2, PAD4, PAD8, PADMINUS, PADPERIOD, PADPLUSKEY, wmKeyMapItem::ptr, RKEY, RNA_boolean_set(), RNA_enum_set(), RNA_float_set(), RNA_int_set(), RNA_string_set(), SKEY, SPACE_IMAGE, TABKEY, TKEY, TRUE, WHEELINMOUSE, WHEELOUTMOUSE, WM_keymap_add_item(), and WM_keymap_find().
Referenced by ED_spacetype_image().
static void image_listener (ScrArea * sa, wmNotifier * wmn) [static]
Definition at line 633 of file space_image.c.
References wmNotifier::category, wmNotifier::data, ED_area_tag_redraw(), ED_area_tag_refresh(), ED_space_image_show_render(), ListBase::first, SpaceImage::flag, SpaceImage::image, image_scopes_tag_refresh(), SpaceImage::lock, Object::mode, NC_GEOM, NC_IMAGE, NC_OBJECT, NC_SCENE, NC_SPACE, ND_COMPO_RESULT, ND_DATA, ND_FRAME, ND_MODE, ND_MODIFIER, ND_RENDER_RESULT, ND_SELECT, ND_SPACE_IMAGE, ND_TRANSFORM, BMEditMesh::ob, OB_MODE_EDIT, wmNotifier::reference, SI_DRAWSHADOW, and ScrArea::spacedata.
Referenced by ED_spacetype_image().
static void image_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 792 of file space_image.c.
References CTX_data_active_object(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_space_image(), draw_image_grease_pencil(), draw_image_main(), draw_uvedit_main(), ED_region_draw_cb_draw(), image_main_area_set_view2d(), SpaceImage::iuser, Scene::r, R_COMP_CROP, REGION_DRAW_POST_VIEW, RenderData::scemode, ImageUser::scene, TH_BACK, UI_GetThemeColor3fv(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_view_ortho(), UI_view2d_view_restore(), ARegion::v2d, V2D_ARG_DUMMY, V2D_GRID_CLAMP, and V2D_UNIT_VALUES.
Referenced by ED_spacetype_image().
static void image_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 767 of file space_image.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, SPACE_IMAGE, ARegion::v2d, ARegion::winrct, WM_event_add_keymap_handler(), WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_image().
static void image_main_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 842 of file space_image.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NC_SCREEN, and ND_GPENCIL.
Referenced by ED_spacetype_image().
static void image_main_area_set_view2d (SpaceImage * sima, ARegion * ar) [static]
Definition at line 714 of file space_image.c.
References Image::aspx, Image::aspy, View2D::cur, ED_space_image(), ED_space_image_size(), View2D::mask, View2D::tot, ARegion::v2d, ARegion::winrct, rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, SpaceImage::xof, rctf::ymax, rcti::ymax, rctf::ymin, rcti::ymin, SpaceImage::yof, and SpaceImage::zoom.
Referenced by image_main_area_draw().
static SpaceLink* image_new (const bContext * UNUSEDC) [static]
Definition at line 378 of file space_image.c.
References ARegion::alignment, BLI_addtail(), ImageUser::fie_ima, ARegion::flag, ImageUser::frames, Histogram::height, SpaceImage::iuser, SpaceImage::lock, MEM_callocN(), ImageUser::ok, SpaceImage::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_ALIGN_LEFT, RGN_ALIGN_RIGHT, RGN_FLAG_HIDDEN, RGN_TYPE_HEADER, RGN_TYPE_PREVIEW, RGN_TYPE_UI, RGN_TYPE_WINDOW, SpaceImage::sample_line_hist, SpaceImage::scopes, scopes_new(), SPACE_IMAGE, SpaceImage::spacetype, and SpaceImage::zoom.
Referenced by ED_spacetype_image().
static void image_operatortypes (void) [static]
Definition at line 461 of file space_image.c.
References IMAGE_OT_curves_point_set(), IMAGE_OT_cycle_render_slot(), IMAGE_OT_invert(), IMAGE_OT_new(), IMAGE_OT_open(), IMAGE_OT_pack(), IMAGE_OT_properties(), IMAGE_OT_record_composite(), IMAGE_OT_reload(), IMAGE_OT_replace(), IMAGE_OT_sample(), IMAGE_OT_sample_line(), IMAGE_OT_save(), IMAGE_OT_save_as(), IMAGE_OT_save_sequence(), IMAGE_OT_scopes(), IMAGE_OT_unpack(), IMAGE_OT_view_all(), IMAGE_OT_view_ndof(), IMAGE_OT_view_pan(), IMAGE_OT_view_selected(), IMAGE_OT_view_zoom(), IMAGE_OT_view_zoom_in(), IMAGE_OT_view_zoom_out(), IMAGE_OT_view_zoom_ratio(), and WM_operatortype_append().
Referenced by ED_spacetype_image().
static void image_refresh (const bContext * C, ScrArea * UNUSEDsa) [static]
Definition at line 581 of file space_image.c.
References BKE_image_user_calc_frame(), BM_active_face_get(), RenderData::cfra, CTX_data_edit_object(), CTX_data_scene(), CTX_wm_space_image(), SpaceImage::curtile, Object::data, ED_object_get_active_image(), ED_space_image(), EDBM_mtexpoly_active_get(), EDBM_mtexpoly_check(), Mesh::edit_btmesh, SpaceImage::flag, ImageUser::flag, if(), IMA_ANIM_ALWAYS, IMA_SRC_VIEWER, SpaceImage::image, SpaceImage::iuser, BMFace::mat_nr, BMEditMesh::me, NULL, OB_MESH, SpaceImage::pin, Scene::r, scene_use_new_shading_nodes(), SI_EDITTILE, Image::source, MTexPoly::tile, MTexPoly::tpage, TRUE, and Object::type.
Referenced by ED_spacetype_image().
static void image_scope_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 905 of file space_image.c.
References RenderData::color_mgt_flag, CTX_data_scene(), CTX_wm_space_image(), ED_region_panels(), ED_space_image_acquire_buffer(), ED_space_image_release_buffer(), NULL, Scene::r, R_COLOR_MANAGEMENT, SpaceImage::scopes, and scopes_update().
Referenced by ED_spacetype_image().
static void image_scope_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 895 of file space_image.c.
References wmWindowManager::defaultconf, ED_region_panels_init(), ARegion::handlers, SPACE_IMAGE, WM_event_add_keymap_handler(), and WM_keymap_find().
Referenced by ED_spacetype_image().
static void image_scope_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 919 of file space_image.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NC_IMAGE, NC_NODE, NC_SCENE, ND_COMPO_RESULT, ND_MODE, and ND_RENDER_RESULT.
Referenced by ED_spacetype_image().
static void image_scopes_tag_refresh (ScrArea * sa) [static]
Definition at line 309 of file space_image.c.
References ListBase::first, Scopes::ok, ScrArea::regionbase, RGN_FLAG_HIDDEN, RGN_TYPE_PREVIEW, SpaceImage::scopes, and ScrArea::spacedata.
Referenced by image_has_scope_region(), and image_listener().
Variable Documentation
const char* image_context_dir[] = {"edit_image", NULL}
Definition at line 694 of file space_image.c.