Blender: LOD_ExternNormalEditor Class Reference
LOD_ExternNormalEditor Class Reference
#include <LOD_ExternNormalEditor.h>
Public Member Functions
void Remove (std::vector< LOD_FaceInd > &sorted_faces)
void Add ()
void Update (std::vector< LOD_FaceInd > &sorted_faces)
const std::vector< MT_Vector3 > & Normals () const
void RemoveVertexNormals (std::vector< LOD_VertexInd > &sorted_verts)
void UpdateVertexNormals (std::vector< LOD_VertexInd > &sorted_verts)
void BuildNormals ()
Static Public Member Functions
static LOD_ExternNormalEditor * New (LOD_Decimation_InfoPtr, LOD_ManMesh2 &mesh)
Detailed Description
Definition at line 41 of file LOD_ExternNormalEditor.h.
Member Function Documentation
void LOD_ExternNormalEditor::Add ()
Definition at line 106 of file LOD_ExternNormalEditor.cpp.
void LOD_ExternNormalEditor::BuildNormals ()
Definition at line 190 of file LOD_ExternNormalEditor.cpp.
References LOD_ManMesh2::FaceSet(), and MEM_SmartPtr< T >::Ref().
Referenced by LOD_PreprocessMesh().
LOD_ExternNormalEditor * LOD_ExternNormalEditor::New (LOD_Decimation_InfoPtr extern_info, LOD_ManMesh2 & mesh) [static]
Definition at line 51 of file LOD_ExternNormalEditor.cpp.
References LOD_ManMesh2::FaceSet(), NULL, and MEM_SmartPtr< T >::Release().
Referenced by LOD_DecimationClass::New().
const std::vector<MT_Vector3>& LOD_ExternNormalEditor::Normals () const [inline]
Definition at line 78 of file LOD_ExternNormalEditor.h.
References MEM_SmartPtr< T >::Ref().
Referenced by LOD_QuadricEditor::BuildQuadrics(), and LOD_NdQuadricEditor::BuildQuadrics().
void LOD_ExternNormalEditor::Remove (std::vector< LOD_FaceInd > & sorted_faces)
Definition at line 78 of file LOD_ExternNormalEditor.cpp.
References MEM_SmartPtr< T >::Ref().
void LOD_ExternNormalEditor::RemoveVertexNormals (std::vector< LOD_VertexInd > & sorted_verts)
Definition at line 137 of file LOD_ExternNormalEditor.cpp.
References MT_Tuple3::getValue(), LOD_Decimation_Info::vertex_normal_buffer, and LOD_Decimation_Info::vertex_num.
void LOD_ExternNormalEditor::Update (std::vector< LOD_FaceInd > & sorted_faces)
Definition at line 114 of file LOD_ExternNormalEditor.cpp.
References LOD_ManMesh2::FaceSet(), and MEM_SmartPtr< T >::Ref().
void LOD_ExternNormalEditor::UpdateVertexNormals (std::vector< LOD_VertexInd > & sorted_verts)
Definition at line 170 of file LOD_ExternNormalEditor.cpp.
References MT_Tuple3::getValue(), and LOD_Decimation_Info::vertex_normal_buffer.
The documentation for this class was generated from the following files:
LOD_ExternNormalEditor.h
LOD_ExternNormalEditor.cpp