Blender: LU_HELPER.h File Reference
LU_HELPER.h File Reference
smoke
#include <cmath>
#include <algorithm>
Classes
struct sLU
Functions
int isNonsingular (sLU LU_)
sLU computeLU (float a[3][3])
void solveLU3x3 (sLU &A, float x[3], float b[3])
Detailed Description
Definition in file LU_HELPER.h.
Function Documentation
sLU computeLU (float a[3][3])
Definition at line 15 of file LU_HELPER.cpp.
References abs(), i, min, p, sLU::piv, sLU::pivsign, and sLU::values.
Referenced by WTURBULENCE::computeEigenvalues(), and WTURBULENCE::stepTurbulenceFull().
int isNonsingular (sLU LU_)
Definition at line 7 of file LU_HELPER.cpp.
References sLU::values.
Referenced by WTURBULENCE::computeEigenvalues(), JAMA::LU< Real >::solve(), solveLU3x3(), and WTURBULENCE::stepTurbulenceFull().
void solveLU3x3 (sLU & A, float x[3], float b[3])
Definition at line 93 of file LU_HELPER.cpp.
References i, isNonsingular(), sLU::piv, and sLU::values.
Referenced by WTURBULENCE::stepTurbulenceFull().