Blender: svm_mapping.h File Reference
svm_mapping.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void svm_node_mapping (KernelGlobals *kg, ShaderData *sd, float *stack, uint vec_offset, uint out_offset, int *offset)
Function Documentation
CCL_NAMESPACE_BEGIN __device void svm_node_mapping (KernelGlobals * kg, ShaderData * sd, float * stack, uint vec_offset, uint out_offset, int * offset)
Definition at line 23 of file svm_mapping.h.
References read_node_float(), stack_load_float3(), stack_store_float3(), transform_point(), Transform::w, Transform::x, Transform::y, and Transform::z.
Referenced by svm_eval_nodes().