Blender: svm_bsdf.h File Reference
svm_bsdf.h File Reference
#include "bsdf_ashikhmin_velvet.h"
#include "bsdf_diffuse.h"
#include "bsdf_oren_nayar.h"
#include "bsdf_microfacet.h"
#include "bsdf_reflection.h"
#include "bsdf_refraction.h"
#include "bsdf_transparent.h"
#include "bsdf_ward.h"
#include "bsdf_westin.h"
Functions
CCL_NAMESPACE_BEGIN __device int svm_bsdf_sample (const ShaderData *sd, const ShaderClosure *sc, float randu, float randv, float3 *eval, float3 *omega_in, differential3 *domega_in, float *pdf)
__device float3 svm_bsdf_eval (const ShaderData *sd, const ShaderClosure *sc, const float3 omega_in, float *pdf)
__device void svm_bsdf_blur (ShaderClosure *sc, float roughness)
Function Documentation
__device void svm_bsdf_blur (ShaderClosure * sc, float roughness)
Definition at line 194 of file svm_bsdf.h.
References bsdf_ashikhmin_velvet_blur(), bsdf_diffuse_blur(), bsdf_microfacet_beckmann_blur(), bsdf_microfacet_ggx_blur(), bsdf_oren_nayar_blur(), bsdf_reflection_blur(), bsdf_refraction_blur(), bsdf_translucent_blur(), bsdf_transparent_blur(), bsdf_ward_blur(), bsdf_westin_backscatter_blur(), bsdf_westin_sheen_blur(), CLOSURE_BSDF_ASHIKHMIN_VELVET_ID, CLOSURE_BSDF_DIFFUSE_ID, CLOSURE_BSDF_MICROFACET_BECKMANN_ID, CLOSURE_BSDF_MICROFACET_BECKMANN_REFRACTION_ID, CLOSURE_BSDF_MICROFACET_GGX_ID, CLOSURE_BSDF_MICROFACET_GGX_REFRACTION_ID, CLOSURE_BSDF_OREN_NAYAR_ID, CLOSURE_BSDF_REFLECTION_ID, CLOSURE_BSDF_REFRACTION_ID, CLOSURE_BSDF_TRANSLUCENT_ID, CLOSURE_BSDF_TRANSPARENT_ID, CLOSURE_BSDF_WARD_ID, CLOSURE_BSDF_WESTIN_BACKSCATTER_ID, CLOSURE_BSDF_WESTIN_SHEEN_ID, and ShaderClosure::type.
Referenced by shader_bsdf_blur().
__device float3 svm_bsdf_eval (const ShaderData * sd, const ShaderClosure * sc, const float3 omega_in, float * pdf)
Definition at line 88 of file svm_bsdf.h.
References bsdf_ashikhmin_velvet_eval_reflect(), bsdf_ashikhmin_velvet_eval_transmit(), bsdf_diffuse_eval_reflect(), bsdf_diffuse_eval_transmit(), bsdf_microfacet_beckmann_eval_reflect(), bsdf_microfacet_beckmann_eval_transmit(), bsdf_microfacet_ggx_eval_reflect(), bsdf_microfacet_ggx_eval_transmit(), bsdf_oren_nayar_eval_reflect(), bsdf_oren_nayar_eval_transmit(), bsdf_reflection_eval_reflect(), bsdf_reflection_eval_transmit(), bsdf_refraction_eval_reflect(), bsdf_refraction_eval_transmit(), bsdf_translucent_eval_reflect(), bsdf_translucent_eval_transmit(), bsdf_transparent_eval_reflect(), bsdf_transparent_eval_transmit(), bsdf_ward_eval_reflect(), bsdf_ward_eval_transmit(), bsdf_westin_backscatter_eval_reflect(), bsdf_westin_backscatter_eval_transmit(), bsdf_westin_sheen_eval_reflect(), bsdf_westin_sheen_eval_transmit(), CLOSURE_BSDF_ASHIKHMIN_VELVET_ID, CLOSURE_BSDF_DIFFUSE_ID, CLOSURE_BSDF_MICROFACET_BECKMANN_ID, CLOSURE_BSDF_MICROFACET_BECKMANN_REFRACTION_ID, CLOSURE_BSDF_MICROFACET_GGX_ID, CLOSURE_BSDF_MICROFACET_GGX_REFRACTION_ID, CLOSURE_BSDF_OREN_NAYAR_ID, CLOSURE_BSDF_REFLECTION_ID, CLOSURE_BSDF_REFRACTION_ID, CLOSURE_BSDF_TRANSLUCENT_ID, CLOSURE_BSDF_TRANSPARENT_ID, CLOSURE_BSDF_WARD_ID, CLOSURE_BSDF_WESTIN_BACKSCATTER_ID, CLOSURE_BSDF_WESTIN_SHEEN_ID, dot(), ShaderData::I, make_float3(), ShaderData::Ng, and ShaderClosure::type.
Referenced by shader_bsdf_eval().
CCL_NAMESPACE_BEGIN __device int svm_bsdf_sample (const ShaderData * sd, const ShaderClosure * sc, float randu, float randv, float3 * eval, float3 * omega_in, differential3 * domega_in, float * pdf)
Definition at line 33 of file svm_bsdf.h.
References bsdf_ashikhmin_velvet_sample(), bsdf_diffuse_sample(), bsdf_microfacet_beckmann_sample(), bsdf_microfacet_ggx_sample(), bsdf_oren_nayar_sample(), bsdf_reflection_sample(), bsdf_refraction_sample(), bsdf_translucent_sample(), bsdf_transparent_sample(), bsdf_ward_sample(), bsdf_westin_backscatter_sample(), bsdf_westin_sheen_sample(), CLOSURE_BSDF_ASHIKHMIN_VELVET_ID, CLOSURE_BSDF_DIFFUSE_ID, CLOSURE_BSDF_MICROFACET_BECKMANN_ID, CLOSURE_BSDF_MICROFACET_BECKMANN_REFRACTION_ID, CLOSURE_BSDF_MICROFACET_GGX_ID, CLOSURE_BSDF_MICROFACET_GGX_REFRACTION_ID, CLOSURE_BSDF_OREN_NAYAR_ID, CLOSURE_BSDF_REFLECTION_ID, CLOSURE_BSDF_REFRACTION_ID, CLOSURE_BSDF_TRANSLUCENT_ID, CLOSURE_BSDF_TRANSPARENT_ID, CLOSURE_BSDF_WARD_ID, CLOSURE_BSDF_WESTIN_BACKSCATTER_ID, CLOSURE_BSDF_WESTIN_SHEEN_ID, differential3::dx, differential3::dy, label(), LABEL_NONE, and ShaderClosure::type.
Referenced by shader_bsdf_sample().