Blender: node_shader_hueSatVal.c File Reference
node_shader_hueSatVal.c File Reference
shdnodes
#include "node_shader_util.h"
Functions
static void do_hue_sat_fac (bNode *UNUSED(node), float *out, float *hue, float *sat, float *val, float *in, float *fac)
static void node_shader_exec_hue_sat (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static int gpu_shader_hue_sat (GPUMaterial *mat, bNode *UNUSED(node), GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_hue_sat (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_hue_sat_in []
static bNodeSocketTemplate sh_node_hue_sat_out []
Detailed Description
Definition in file node_shader_hueSatVal.c.
Function Documentation
static void do_hue_sat_fac (bNode * UNUSEDnode, float * out, float * hue, float * sat, float * val, float * in, float * fac) [static]
Definition at line 51 of file node_shader_hueSatVal.c.
References copy_v4_v4(), hsv_to_rgb(), and rgb_to_hsv().
Referenced by node_shader_exec_hue_sat().
static int gpu_shader_hue_sat (GPUMaterial * mat, bNode * UNUSEDnode, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 78 of file node_shader_hueSatVal.c.
References GPU_stack_link().
Referenced by register_node_type_sh_hue_sat().
static void node_shader_exec_hue_sat (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 72 of file node_shader_hueSatVal.c.
References do_hue_sat_fac().
Referenced by register_node_type_sh_hue_sat().
void register_node_type_sh_hue_sat (bNodeTreeType * ttype)
Definition at line 83 of file node_shader_hueSatVal.c.
References gpu_shader_hue_sat(), NODE_CLASS_OP_COLOR, NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_hue_sat(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_HUE_SAT.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_hue_sat_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Hue",           0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_NONE},
    {   SOCK_FLOAT, 1, "Saturation",        1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 2.0f, PROP_FACTOR},
    {   SOCK_FLOAT, 1, "Value",         1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 2.0f, PROP_FACTOR},
    {   SOCK_FLOAT, 1, "Fac",           1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_FACTOR},
    {   SOCK_RGBA, 1, "Color",          0.8f, 0.8f, 0.8f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_shader_hueSatVal.c.
bNodeSocketTemplate sh_node_hue_sat_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Color"},
    {   -1, 0, ""   }
}
Definition at line 45 of file node_shader_hueSatVal.c.