Blender: CProfileManager Class Reference
CProfileManager Class Reference
The Manager for the Profile system.
#include <btQuickprof.h>
Static Public Member Functions
static void Start_Profile (const char *name)
static void Stop_Profile (void)
static void CleanupMemory (void)
static void Reset (void)
static void Increment_Frame_Counter (void)
static int Get_Frame_Count_Since_Reset (void)
static float Get_Time_Since_Reset (void)
static CProfileIterator * Get_Iterator (void)
static void Release_Iterator (CProfileIterator *iterator)
static void dumpRecursive (CProfileIterator *profileIterator, int spacing)
static void dumpAll ()
Detailed Description
The Manager for the Profile system.
Definition at line 134 of file btQuickprof.h.
Member Function Documentation
static void CProfileManager::CleanupMemory (void) [inline, static]
Definition at line 139 of file btQuickprof.h.
References CProfileNode::CleanupMemory().
void CProfileManager::dumpAll () [static]
Definition at line 552 of file btQuickprof.cpp.
References dumpRecursive(), Get_Iterator(), and Release_Iterator().
void CProfileManager::dumpRecursive (CProfileIterator * profileIterator, int spacing) [static]
Definition at line 503 of file btQuickprof.cpp.
References CProfileIterator::Enter_Child(), CProfileIterator::Enter_Parent(), CProfileIterator::First(), CProfileIterator::Get_Current_Name(), CProfileIterator::Get_Current_Parent_Name(), CProfileIterator::Get_Current_Parent_Total_Time(), CProfileIterator::Get_Current_Total_Calls(), CProfileIterator::Get_Current_Total_Time(), Get_Frame_Count_Since_Reset(), Get_Time_Since_Reset(), i, CProfileIterator::Is_Done(), CProfileIterator::Is_Root(), CProfileIterator::Next(), and SIMD_EPSILON.
Referenced by dumpAll().
static int CProfileManager::Get_Frame_Count_Since_Reset (void) [inline, static]
Definition at line 146 of file btQuickprof.h.
Referenced by dumpRecursive().
static CProfileIterator* CProfileManager::Get_Iterator (void) [inline, static]
Definition at line 149 of file btQuickprof.h.
Referenced by dumpAll().
float CProfileManager::Get_Time_Since_Reset (void) [static]
Definition at line 493 of file btQuickprof.cpp.
References Profile_Get_Tick_Rate(), and Profile_Get_Ticks().
Referenced by dumpRecursive().
void CProfileManager::Increment_Frame_Counter (void) [static]
Definition at line 484 of file btQuickprof.cpp.
Referenced by btDiscreteDynamicsWorld::stepSimulation().
static void CProfileManager::Release_Iterator (CProfileIterator * iterator) [inline, static]
Definition at line 154 of file btQuickprof.h.
Referenced by dumpAll().
void CProfileManager::Reset (void) [static]
Definition at line 471 of file btQuickprof.cpp.
References CProfileNode::Call(), Profile_Get_Ticks(), btClock::reset(), and CProfileNode::Reset().
Referenced by btDiscreteDynamicsWorld::startProfiling().
void CProfileManager::Start_Profile (const char * name) [static]
Definition at line 443 of file btQuickprof.cpp.
References CProfileNode::Call(), CProfileNode::Get_Name(), and CProfileNode::Get_Sub_Node().
Referenced by CProfileSample::CProfileSample().
void CProfileManager::Stop_Profile (void) [static]
Definition at line 456 of file btQuickprof.cpp.
References CProfileNode::Get_Parent(), and CProfileNode::Return().
Referenced by CProfileSample::~CProfileSample().
The documentation for this class was generated from the following files:
btQuickprof.h
btQuickprof.cpp