Blender: KX_ConvertControllers.cpp File Reference
KX_ConvertControllers.cpp File Reference
Converter
#include "MEM_guardedalloc.h"
#include "KX_BlenderSceneConverter.h"
#include "KX_ConvertControllers.h"
#include "KX_Python.h"
#include "SCA_ANDController.h"
#include "SCA_ORController.h"
#include "SCA_NANDController.h"
#include "SCA_NORController.h"
#include "SCA_XORController.h"
#include "SCA_XNORController.h"
#include "SCA_PythonController.h"
#include "SCA_ExpressionController.h"
#include "SCA_LogicManager.h"
#include "KX_GameObject.h"
#include "IntValue.h"
#include "DNA_object_types.h"
#include "DNA_controller_types.h"
#include "DNA_text_types.h"
#include "BKE_text.h"
#include "BLI_blenlib.h"
Functions
static void LinkControllerToActuators (SCA_IController *game_controller, bController *bcontr, SCA_LogicManager *logicmgr, KX_BlenderSceneConverter *converter)
void BL_ConvertControllers (struct Object *blenderobject, class KX_GameObject *gameobj, SCA_LogicManager *logicmgr, int activeLayerBitInfo, bool isInActiveLayer, KX_BlenderSceneConverter *converter)
Detailed Description
Definition in file KX_ConvertControllers.cpp.
Function Documentation
void BL_ConvertControllers (struct Object * blenderobject, class KX_GameObject * gameobj, SCA_LogicManager * logicmgr, int activeLayerBitInfo, bool isInActiveLayer, KX_BlenderSceneConverter * converter)
Definition at line 91 of file KX_ConvertControllers.cpp.
References SCA_IObject::AddController(), SCA_PythonController::Compile(), CONT_EXPRESSION, CONT_LOGIC_AND, CONT_LOGIC_NAND, CONT_LOGIC_NOR, CONT_LOGIC_OR, CONT_LOGIC_XNOR, CONT_LOGIC_XOR, CONT_PRIO, CONT_PY_DEBUG, CONT_PYTHON, Object::controllers, bController::data, ListBase::first, bPythonCont::flag, bController::flag, CIntValue::GetText(), Text::id, Object::id, LinkControllerToActuators(), MEM_freeN(), bPythonCont::mode, bPythonCont::module, ID::name, bController::name, bController::next, NULL, KX_BlenderSceneConverter::RegisterGameController(), CValue::Release(), SCA_IObject::ReserveController(), SCA_PythonController::SCA_PYEXEC_SCRIPT, SCA_IController::SetBookmark(), SCA_ILogicBrick::SetExecutePriority(), SCA_ILogicBrick::SetName(), SCA_IController::SetState(), bController::state_mask, bExpressionCont::str, bPythonCont::text, txt_to_buf(), and bController::type.
Referenced by BL_ConvertBlenderObjects().
static void LinkControllerToActuators (SCA_IController * game_controller, bController * bcontr, SCA_LogicManager * logicmgr, KX_BlenderSceneConverter * converter) [static]
Definition at line 70 of file KX_ConvertControllers.cpp.
References KX_BlenderSceneConverter::FindGameActuator(), i, bController::links, SCA_LogicManager::RegisterToActuator(), SCA_IController::ReserveActuator(), and bController::totlinks.
Referenced by BL_ConvertControllers().