Blender: svm_sepcomb_rgb.h File Reference
svm_sepcomb_rgb.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void svm_node_combine_rgb (ShaderData *sd, float *stack, uint in_offset, uint color_index, uint out_offset)
__device void svm_node_separate_rgb (ShaderData *sd, float *stack, uint icolor_offset, uint color_index, uint out_offset)
Function Documentation
CCL_NAMESPACE_BEGIN __device void svm_node_combine_rgb (ShaderData * sd, float * stack, uint in_offset, uint color_index, uint out_offset)
Definition at line 21 of file svm_sepcomb_rgb.h.
References stack_load_float(), stack_store_float(), and stack_valid().
Referenced by svm_eval_nodes().
__device void svm_node_separate_rgb (ShaderData * sd, float * stack, uint icolor_offset, uint color_index, uint out_offset)
Definition at line 29 of file svm_sepcomb_rgb.h.
References stack_load_float3(), stack_store_float(), stack_valid(), float3::x, float3::y, and float3::z.
Referenced by svm_eval_nodes().