Blender: screen_context.c File Reference
screen_context.c File Reference
screen
#include <stdlib.h>
#include <string.h>
#include "DNA_object_types.h"
#include "DNA_armature_types.h"
#include "DNA_sequence_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "DNA_windowmanager_types.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_object.h"
#include "BKE_action.h"
#include "BKE_armature.h"
#include "BKE_sequencer.h"
#include "RNA_access.h"
#include "ED_object.h"
#include "ED_armature.h"
#include "WM_api.h"
#include "UI_interface.h"
#include "screen_intern.h"
Functions
int ed_screen_context (const bContext *C, const char *member, bContextDataResult *result)
Variables
const char * screen_context_dir []
Detailed Description
Definition in file screen_context.c.
Function Documentation
int ed_screen_context (const bContext * C, const char * member, bContextDataResult * result)
Definition at line 73 of file screen_context.c.
References bArmature::act_bone, bArmature::act_edbone, ARM_MIRROR_EDIT, BASACT, Scene::base, BONE_SELECTED, bPose::chanbase, CTX_data_active_base(), CTX_data_active_object(), CTX_data_dir(), CTX_data_dir_set(), CTX_data_edit_object(), CTX_data_equals(), CTX_data_id_list_add(), CTX_data_id_pointer_set(), CTX_data_list_add(), CTX_data_pointer_set(), CTX_DATA_TYPE_COLLECTION, CTX_data_type_set(), CTX_wm_screen(), CTX_wm_space_file(), Object::data, EBONE_EDITABLE, EBONE_VISIBLE, ED_armature_bone_get_mirrored(), bArmature::edbo, FALSE, ListBase::first, Base::flag, Sequence::flag, bArmature::flag, get_active_posechannel(), Scene::id, Object::id, bArmature::id, if(), Base::lay, Scene::lay, Object::mode, Base::next, Sequence::next, NULL, OB_ARMATURE, OB_MODE_PARTICLE_EDIT, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, OB_RESTRICT_SELECT, OB_RESTRICT_VIEW, OBACT, Scene::obedit, Base::object, object_is_libdata(), object_pose_armature_get(), SpaceFile::op, PBONE_VISIBLE, Object::pose, wmOperator::ptr, Object::restrictflag, RNA_Bone, RNA_EditBone, RNA_ObjectBase, RNA_Operator, RNA_PoseBone, RNA_Sequence, bScreen::scene, screen_context_dir, SELECT, seq_give_editing(), SEQ_LOCK, Editing::seqbasep, Object::type, uiContextActiveOperator(), and WM_operator_last_redo().
Referenced by ED_screen_refresh().
Variable Documentation
const char* screen_context_dir[]
Initial value:
 {
    "scene", "visible_objects", "visible_bases", "selectable_objects", "selectable_bases",
    "selected_objects", "selected_bases",
    "selected_editable_objects", "selected_editable_bases",
    "visible_bones", "editable_bones", "selected_bones", "selected_editable_bones",
    "visible_pose_bones", "selected_pose_bones", "active_bone", "active_pose_bone",
    "active_base", "active_object", "object", "edit_object",
    "sculpt_object", "vertex_paint_object", "weight_paint_object",
    "image_paint_object", "particle_edit_object",
    "sequences", "selected_sequences", "selected_editable_sequences",
    "active_operator",
    NULL}
Definition at line 60 of file screen_context.c.
Referenced by ed_screen_context().