Blender: gjkepa2_impl::EPA Struct Reference
gjkepa2_impl::EPA Struct Reference
Classes
struct eStatus
struct sFace
struct sHorizon
struct sList
Public Types
typedef GJK::sSV sSV
Public Member Functions
EPA ()
void Initialize ()
eStatus::_ Evaluate (GJK &gjk, const btVector3 &guess)
sFace * newface (sSV *a, sSV *b, sSV *c, bool forced)
sFace * findbest ()
bool expand (U pass, sSV *w, sFace *f, U e, sHorizon &horizon)
Static Public Member Functions
static void bind (sFace *fa, U ea, sFace *fb, U eb)
static void append (sList &list, sFace *face)
static void remove (sList &list, sFace *face)
Public Attributes
eStatus::_ m_status
GJK::sSimplex m_result
btVector3 m_normal
btScalar m_depth
sSV m_sv_store [EPA_MAX_VERTICES]
sFace m_fc_store [EPA_MAX_FACES]
U m_nextsv
sList m_hull
sList m_stock
Detailed Description
Definition at line 506 of file btGjkEpa2.cpp.
Member Typedef Documentation
typedef GJK::sSV gjkepa2_impl::EPA::sSV
Definition at line 509 of file btGjkEpa2.cpp.
Constructor & Destructor Documentation
gjkepa2_impl::EPA::EPA () [inline]
Definition at line 556 of file btGjkEpa2.cpp.
References Initialize().
Member Function Documentation
static void gjkepa2_impl::EPA::append (sList & list, sFace * face) [inline, static]
Definition at line 567 of file btGjkEpa2.cpp.
References gjkepa2_impl::EPA::sList::count, gjkepa2_impl::EPA::sFace::l, and gjkepa2_impl::EPA::sList::root.
Referenced by Evaluate(), expand(), Initialize(), and newface().
static void gjkepa2_impl::EPA::bind (sFace * fa, U ea, sFace * fb, U eb) [inline, static]
Definition at line 562 of file btGjkEpa2.cpp.
References gjkepa2_impl::EPA::sFace::e, gjkepa2_impl::EPA::sFace::f, and fb().
Referenced by Evaluate(), and expand().
eStatus::_ gjkepa2_impl::EPA::Evaluate (GJK & gjk, const btVector3 & guess) [inline]
Definition at line 595 of file btGjkEpa2.cpp.
References gjkepa2_impl::EPA::eStatus::AccuraryReached, append(), bind(), btCross(), btDot(), btSwap(), gjkepa2_impl::GJK::sSimplex::c, gjkepa2_impl::EPA::sFace::c, gjkepa2_impl::EPA::sHorizon::cf, gjkepa2_impl::EPA::sList::count, gjkepa2_impl::EPA::sFace::d, gjkepa2_impl::GJK::det(), gjkepa2_impl::EPA::sFace::e, gjkepa2_impl::GJK::EncloseOrigin(), EPA_ACCURACY, EPA_MAX_ITERATIONS, EPA_MAX_VERTICES, expand(), gjkepa2_impl::EPA::sFace::f, gjkepa2_impl::EPA::eStatus::FallBack, gjkepa2_impl::EPA::sHorizon::ff, findbest(), gjkepa2_impl::GJK::getsupport(), gjkepa2_impl::EPA::eStatus::InvalidHull, m_depth, m_hull, m_nextsv, m_normal, m_result, gjkepa2_impl::GJK::m_simplex, m_status, m_stock, m_sv_store, gjkepa2_impl::EPA::sFace::n, newface(), gjkepa2_impl::EPA::sHorizon::nf, gjkepa2_impl::EPA::eStatus::OutOfVertices, gjkepa2_impl::GJK::sSimplex::p, gjkepa2_impl::EPA::sFace::p, gjkepa2_impl::EPA::sFace::pass, gjkepa2_impl::GJK::sSimplex::rank, gjkepa2_impl::EPA::sList::root, sum(), gjkepa2_impl::EPA::eStatus::Valid, and gjkepa2_impl::GJK::sSV::w.
Referenced by btGjkEpaSolver2::Penetration().
bool gjkepa2_impl::EPA::expand (U pass, sSV * w, sFace * f, U e, sHorizon & horizon) [inline]
Definition at line 752 of file btGjkEpa2.cpp.
References append(), bind(), btDot(), gjkepa2_impl::EPA::sFace::c, gjkepa2_impl::EPA::sHorizon::cf, gjkepa2_impl::EPA::sFace::d, gjkepa2_impl::EPA::sFace::e, EPA_PLANE_EPS, gjkepa2_impl::EPA::sFace::f, gjkepa2_impl::EPA::sHorizon::ff, m_hull, m_stock, gjkepa2_impl::EPA::sFace::n, newface(), gjkepa2_impl::EPA::sHorizon::nf, gjkepa2_impl::EPA::sFace::pass, and gjkepa2_impl::GJK::sSV::w.
Referenced by Evaluate().
sFace* gjkepa2_impl::EPA::findbest () [inline]
Definition at line 735 of file btGjkEpa2.cpp.
References gjkepa2_impl::EPA::sFace::d, gjkepa2_impl::EPA::sFace::l, m_hull, minf(), gjkepa2_impl::EPA::sFace::p, and gjkepa2_impl::EPA::sList::root.
Referenced by Evaluate().
void gjkepa2_impl::EPA::Initialize (void) [inline]
Definition at line 584 of file btGjkEpa2.cpp.
References append(), EPA_MAX_FACES, gjkepa2_impl::EPA::eStatus::Failed, i, m_depth, m_fc_store, m_nextsv, m_normal, m_status, and m_stock.
Referenced by EPA().
sFace* gjkepa2_impl::EPA::newface (sSV * a, sSV * b, sSV * c, bool forced) [inline]
Definition at line 699 of file btGjkEpa2.cpp.
References append(), btCross(), btDot(), btMin(), gjkepa2_impl::EPA::sFace::c, gjkepa2_impl::EPA::sFace::d, gjkepa2_impl::EPA::eStatus::Degenerated, EPA_ACCURACY, EPA_INSIDE_EPS, EPA_PLANE_EPS, m_hull, m_status, m_stock, gjkepa2_impl::EPA::sFace::n, gjkepa2_impl::EPA::eStatus::NonConvex, gjkepa2_impl::EPA::eStatus::OutOfFaces, gjkepa2_impl::EPA::eStatus::OutOfVertices, gjkepa2_impl::EPA::sFace::p, gjkepa2_impl::EPA::sFace::pass, gjkepa2_impl::EPA::sList::root, and gjkepa2_impl::GJK::sSV::w.
Referenced by Evaluate(), and expand().
static void gjkepa2_impl::EPA::remove (sList & list, sFace * face) [inline, static]
Definition at line 575 of file btGjkEpa2.cpp.
Member Data Documentation
btScalar gjkepa2_impl::EPA::m_depth
Definition at line 549 of file btGjkEpa2.cpp.
Referenced by Evaluate(), Initialize(), and btGjkEpaSolver2::Penetration().
sFace gjkepa2_impl::EPA::m_fc_store[EPA_MAX_FACES]
Definition at line 551 of file btGjkEpa2.cpp.
Referenced by Initialize().
sList gjkepa2_impl::EPA::m_hull
Definition at line 553 of file btGjkEpa2.cpp.
Referenced by Evaluate(), expand(), findbest(), and newface().
U gjkepa2_impl::EPA::m_nextsv
Definition at line 552 of file btGjkEpa2.cpp.
Referenced by Evaluate(), and Initialize().
btVector3 gjkepa2_impl::EPA::m_normal
Definition at line 548 of file btGjkEpa2.cpp.
Referenced by Evaluate(), Initialize(), and btGjkEpaSolver2::Penetration().
GJK::sSimplex gjkepa2_impl::EPA::m_result
Definition at line 547 of file btGjkEpa2.cpp.
Referenced by Evaluate(), and btGjkEpaSolver2::Penetration().
eStatus::_ gjkepa2_impl::EPA::m_status
Definition at line 546 of file btGjkEpa2.cpp.
Referenced by Evaluate(), Initialize(), and newface().
sList gjkepa2_impl::EPA::m_stock
Definition at line 554 of file btGjkEpa2.cpp.
Referenced by Evaluate(), expand(), Initialize(), and newface().
sSV gjkepa2_impl::EPA::m_sv_store[EPA_MAX_VERTICES]
Definition at line 550 of file btGjkEpa2.cpp.
Referenced by Evaluate().
The documentation for this struct was generated from the following file:
btGjkEpa2.cpp