Blender: AUD_ConverterFunctions.h File Reference
AUD_ConverterFunctions.h File Reference
#include "AUD_Space.h"
#include <cstring>
#include <stdint.h>
Typedefs
typedef void(* AUD_convert_f)(data_t *target, data_t *source, int length)
Functions
template<class T >
void AUD_convert_copy (data_t *target, data_t *source, int length)
void AUD_convert_u8_s16 (data_t *target, data_t *source, int length)
void AUD_convert_u8_s24_be (data_t *target, data_t *source, int length)
void AUD_convert_u8_s24_le (data_t *target, data_t *source, int length)
void AUD_convert_u8_s32 (data_t *target, data_t *source, int length)
void AUD_convert_u8_float (data_t *target, data_t *source, int length)
void AUD_convert_u8_double (data_t *target, data_t *source, int length)
void AUD_convert_s16_u8 (data_t *target, data_t *source, int length)
void AUD_convert_s16_s24_be (data_t *target, data_t *source, int length)
void AUD_convert_s16_s24_le (data_t *target, data_t *source, int length)
void AUD_convert_s16_s32 (data_t *target, data_t *source, int length)
void AUD_convert_s16_float (data_t *target, data_t *source, int length)
void AUD_convert_s16_double (data_t *target, data_t *source, int length)
void AUD_convert_s24_u8_be (data_t *target, data_t *source, int length)
void AUD_convert_s24_u8_le (data_t *target, data_t *source, int length)
void AUD_convert_s24_s16_be (data_t *target, data_t *source, int length)
void AUD_convert_s24_s16_le (data_t *target, data_t *source, int length)
void AUD_convert_s24_s24 (data_t *target, data_t *source, int length)
void AUD_convert_s24_s32_be (data_t *target, data_t *source, int length)
void AUD_convert_s24_s32_le (data_t *target, data_t *source, int length)
void AUD_convert_s24_float_be (data_t *target, data_t *source, int length)
void AUD_convert_s24_float_le (data_t *target, data_t *source, int length)
void AUD_convert_s24_double_be (data_t *target, data_t *source, int length)
void AUD_convert_s24_double_le (data_t *target, data_t *source, int length)
void AUD_convert_s32_u8 (data_t *target, data_t *source, int length)
void AUD_convert_s32_s16 (data_t *target, data_t *source, int length)
void AUD_convert_s32_s24_be (data_t *target, data_t *source, int length)
void AUD_convert_s32_s24_le (data_t *target, data_t *source, int length)
void AUD_convert_s32_float (data_t *target, data_t *source, int length)
void AUD_convert_s32_double (data_t *target, data_t *source, int length)
void AUD_convert_float_u8 (data_t *target, data_t *source, int length)
void AUD_convert_float_s16 (data_t *target, data_t *source, int length)
void AUD_convert_float_s24_be (data_t *target, data_t *source, int length)
void AUD_convert_float_s24_le (data_t *target, data_t *source, int length)
void AUD_convert_float_s32 (data_t *target, data_t *source, int length)
void AUD_convert_float_double (data_t *target, data_t *source, int length)
void AUD_convert_double_u8 (data_t *target, data_t *source, int length)
void AUD_convert_double_s16 (data_t *target, data_t *source, int length)
void AUD_convert_double_s24_be (data_t *target, data_t *source, int length)
void AUD_convert_double_s24_le (data_t *target, data_t *source, int length)
void AUD_convert_double_s32 (data_t *target, data_t *source, int length)
void AUD_convert_double_float (data_t *target, data_t *source, int length)
Detailed Description
Definition in file AUD_ConverterFunctions.h.
Typedef Documentation
typedef void(* AUD_convert_f)(data_t *target, data_t *source, int length)
Definition at line 48 of file AUD_ConverterFunctions.h.
Function Documentation
template<class T > void AUD_convert_copy (data_t * target, data_t * source, int length)
Definition at line 51 of file AUD_ConverterFunctions.h.
References T.
void AUD_convert_double_float (data_t * target, data_t * source, int length)
Definition at line 466 of file AUD_ConverterFunctions.cpp.
References i, and length().
void AUD_convert_double_s16 (data_t * target, data_t * source, int length)
Definition at line 400 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S16_MAX, AUD_S16_MIN, i, and length().
void AUD_convert_double_s24_be (data_t * target, data_t * source, int length)
Definition at line 415 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S32_MAX, AUD_S32_MIN, i, and length().
void AUD_convert_double_s24_le (data_t * target, data_t * source, int length)
Definition at line 433 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S32_MAX, AUD_S32_MIN, i, and length().
void AUD_convert_double_s32 (data_t * target, data_t * source, int length)
Definition at line 451 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S32_MAX, AUD_S32_MIN, i, and length().
void AUD_convert_double_u8 (data_t * target, data_t * source, int length)
Definition at line 384 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, i, and length().
void AUD_convert_float_double (data_t * target, data_t * source, int length)
Definition at line 376 of file AUD_ConverterFunctions.cpp.
References i.
Referenced by AUD_ConverterReader::AUD_ConverterReader(), AUD_FFMPEGWriter::AUD_FFMPEGWriter(), and AUD_Mixer::AUD_Mixer().
void AUD_convert_float_s16 (data_t * target, data_t * source, int length)
Definition at line 310 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S16_MAX, AUD_S16_MIN, i, and length().
Referenced by AUD_ConverterReader::AUD_ConverterReader(), AUD_FFMPEGWriter::AUD_FFMPEGWriter(), and AUD_Mixer::AUD_Mixer().
void AUD_convert_float_s24_be (data_t * target, data_t * source, int length)
Definition at line 325 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S32_MAX, AUD_S32_MIN, i, and length().
Referenced by AUD_ConverterReader::AUD_ConverterReader(), and AUD_Mixer::AUD_Mixer().
void AUD_convert_float_s24_le (data_t * target, data_t * source, int length)
Definition at line 343 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S32_MAX, AUD_S32_MIN, i, and length().
Referenced by AUD_ConverterReader::AUD_ConverterReader(), and AUD_Mixer::AUD_Mixer().
void AUD_convert_float_s32 (data_t * target, data_t * source, int length)
Definition at line 361 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S32_MAX, AUD_S32_MIN, i, and length().
Referenced by AUD_ConverterReader::AUD_ConverterReader(), AUD_FFMPEGWriter::AUD_FFMPEGWriter(), and AUD_Mixer::AUD_Mixer().
void AUD_convert_float_u8 (data_t * target, data_t * source, int length)
Definition at line 294 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, i, and length().
Referenced by AUD_ConverterReader::AUD_ConverterReader(), AUD_FFMPEGWriter::AUD_FFMPEGWriter(), and AUD_Mixer::AUD_Mixer().
void AUD_convert_s16_double (data_t * target, data_t * source, int length)
Definition at line 140 of file AUD_ConverterFunctions.cpp.
References AUD_S16_FLT, and i.
void AUD_convert_s16_float (data_t * target, data_t * source, int length)
Definition at line 132 of file AUD_ConverterFunctions.cpp.
References AUD_S16_FLT, and i.
void AUD_convert_s16_s24_be (data_t * target, data_t * source, int length)
Definition at line 98 of file AUD_ConverterFunctions.cpp.
References i.
void AUD_convert_s16_s24_le (data_t * target, data_t * source, int length)
Definition at line 111 of file AUD_ConverterFunctions.cpp.
References i.
void AUD_convert_s16_s32 (data_t * target, data_t * source, int length)
Definition at line 124 of file AUD_ConverterFunctions.cpp.
References i.
void AUD_convert_s16_u8 (data_t * target, data_t * source, int length)
Definition at line 91 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, i, and length().
void AUD_convert_s24_double_be (data_t * target, data_t * source, int length)
Definition at line 215 of file AUD_ConverterFunctions.cpp.
References AUD_S32_FLT, and i.
void AUD_convert_s24_double_le (data_t * target, data_t * source, int length)
Definition at line 226 of file AUD_ConverterFunctions.cpp.
References AUD_S32_FLT, and i.
void AUD_convert_s24_float_be (data_t * target, data_t * source, int length)
Definition at line 193 of file AUD_ConverterFunctions.cpp.
References AUD_S32_FLT, and i.
void AUD_convert_s24_float_le (data_t * target, data_t * source, int length)
Definition at line 204 of file AUD_ConverterFunctions.cpp.
References AUD_S32_FLT, and i.
void AUD_convert_s24_s16_be (data_t * target, data_t * source, int length)
Definition at line 160 of file AUD_ConverterFunctions.cpp.
References i, and length().
void AUD_convert_s24_s16_le (data_t * target, data_t * source, int length)
Definition at line 167 of file AUD_ConverterFunctions.cpp.
References i, and length().
void AUD_convert_s24_s24 (data_t * target, data_t * source, int length)
Definition at line 174 of file AUD_ConverterFunctions.cpp.
void AUD_convert_s24_s32_be (data_t * target, data_t * source, int length)
Definition at line 179 of file AUD_ConverterFunctions.cpp.
References i.
void AUD_convert_s24_s32_le (data_t * target, data_t * source, int length)
Definition at line 186 of file AUD_ConverterFunctions.cpp.
References i.
void AUD_convert_s24_u8_be (data_t * target, data_t * source, int length)
Definition at line 148 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, i, and length().
void AUD_convert_s24_u8_le (data_t * target, data_t * source, int length)
Definition at line 154 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, i, and length().
void AUD_convert_s32_double (data_t * target, data_t * source, int length)
Definition at line 286 of file AUD_ConverterFunctions.cpp.
References AUD_S32_FLT, and i.
void AUD_convert_s32_float (data_t * target, data_t * source, int length)
Definition at line 278 of file AUD_ConverterFunctions.cpp.
References AUD_S32_FLT, i, and length().
void AUD_convert_s32_s16 (data_t * target, data_t * source, int length)
Definition at line 244 of file AUD_ConverterFunctions.cpp.
References i, and length().
void AUD_convert_s32_s24_be (data_t * target, data_t * source, int length)
Definition at line 252 of file AUD_ConverterFunctions.cpp.
References i, and length().
void AUD_convert_s32_s24_le (data_t * target, data_t * source, int length)
Definition at line 265 of file AUD_ConverterFunctions.cpp.
References i, and length().
void AUD_convert_s32_u8 (data_t * target, data_t * source, int length)
Definition at line 237 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, i, and length().
void AUD_convert_u8_double (data_t * target, data_t * source, int length)
Definition at line 84 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, and i.
void AUD_convert_u8_float (data_t * target, data_t * source, int length)
Definition at line 77 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, and i.
void AUD_convert_u8_s16 (data_t * target, data_t * source, int length)
Definition at line 43 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, and i.
void AUD_convert_u8_s24_be (data_t * target, data_t * source, int length)
Definition at line 50 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, and i.
void AUD_convert_u8_s24_le (data_t * target, data_t * source, int length)
Definition at line 60 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, and i.
void AUD_convert_u8_s32 (data_t * target, data_t * source, int length)
Definition at line 70 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, and i.