Blender: physics_pointcache.c File Reference
physics_pointcache.c File Reference
physics
#include <stdlib.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "DNA_scene_types.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_modifier.h"
#include "BKE_particle.h"
#include "BKE_pointcache.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "ED_particle.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "physics_intern.h"
Functions
static int cache_break_test (void *UNUSED(cbd))
static int ptcache_bake_all_poll (bContext *C)
static int ptcache_poll (bContext *C)
static void bake_console_progress (void *UNUSED(arg), int nr)
static void bake_console_progress_end (void *UNUSED(arg))
static int ptcache_bake_all_exec (bContext *C, wmOperator *op)
static int ptcache_free_bake_all_exec (bContext *C, wmOperator *UNUSED(op))
void PTCACHE_OT_bake_all (wmOperatorType *ot)
void PTCACHE_OT_free_bake_all (wmOperatorType *ot)
static int ptcache_bake_exec (bContext *C, wmOperator *op)
static int ptcache_free_bake_exec (bContext *C, wmOperator *UNUSED(op))
static int ptcache_bake_from_cache_exec (bContext *C, wmOperator *UNUSED(op))
void PTCACHE_OT_bake (wmOperatorType *ot)
void PTCACHE_OT_free_bake (wmOperatorType *ot)
void PTCACHE_OT_bake_from_cache (wmOperatorType *ot)
static int ptcache_add_new_exec (bContext *C, wmOperator *UNUSED(op))
static int ptcache_remove_exec (bContext *C, wmOperator *UNUSED(op))
void PTCACHE_OT_add (wmOperatorType *ot)
void PTCACHE_OT_remove (wmOperatorType *ot)
Detailed Description
Definition in file physics_pointcache.c.
Function Documentation
static void bake_console_progress (void * UNUSEDarg, int nr) [static]
Definition at line 82 of file physics_pointcache.c.
Referenced by ptcache_bake_all_exec(), and ptcache_bake_exec().
static void bake_console_progress_end (void * UNUSEDarg) [static]
Definition at line 88 of file physics_pointcache.c.
Referenced by ptcache_bake_all_exec(), and ptcache_bake_exec().
static int cache_break_test (void * UNUSEDcbd) [static]
Definition at line 62 of file physics_pointcache.c.
References G.
Referenced by ptcache_bake_all_exec(), and ptcache_bake_exec().
static int ptcache_add_new_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 314 of file physics_pointcache.c.
References BKE_ptcache_add(), BKE_ptcache_ids_from_object(), BLI_freelistN(), PTCacheID::cache, PTCacheID::cache_ptr, CTX_data_pointer_get_type(), CTX_data_scene(), PointerRNA::data, PTCacheID::default_step, ListBase::first, PointerRNA::id, MAX_DUPLI_RECUR, NC_OBJECT, NC_SCENE, ND_FRAME, ND_POINTCACHE, PTCacheID::next, OPERATOR_FINISHED, PTCacheID::ptcaches, RNA_PointCache, PointCache::step, and WM_event_add_notifier().
Referenced by PTCACHE_OT_add().
static int ptcache_bake_all_exec (bContext * C, wmOperator * op) [static]
Definition at line 93 of file physics_pointcache.c.
References PTCacheBaker::anim_init, PTCacheBaker::bake, bake_console_progress(), bake_console_progress_end(), BKE_ptcache_bake(), PTCacheBaker::break_data, PTCacheBaker::break_test, cache_break_test(), CTX_data_main(), CTX_data_scene(), CTX_wm_window(), G, PTCacheBaker::main, NC_OBJECT, NC_SCENE, ND_FRAME, ND_POINTCACHE, NULL, OPERATOR_FINISHED, PTCacheBaker::pid, PTCacheBaker::progressbar, PTCacheBaker::progresscontext, PTCacheBaker::progressend, wmOperator::ptr, PTCacheBaker::quick_step, PTCacheBaker::render, RNA_boolean_get(), PTCacheBaker::scene, WM_cursor_restore(), WM_event_add_notifier(), and WM_timecursor().
Referenced by PTCACHE_OT_bake_all().
static int ptcache_bake_all_poll (bContext * C) [static]
Definition at line 66 of file physics_pointcache.c.
References CTX_data_scene().
Referenced by PTCACHE_OT_bake_all(), and PTCACHE_OT_free_bake_all().
static int ptcache_bake_exec (bContext * C, wmOperator * op) [static]
Definition at line 184 of file physics_pointcache.c.
References PTCacheBaker::anim_init, PTCacheBaker::bake, bake_console_progress(), bake_console_progress_end(), BKE_ptcache_bake(), BKE_ptcache_ids_from_object(), BLI_freelistN(), PTCacheBaker::break_data, PTCacheBaker::break_test, PTCacheID::cache, cache_break_test(), CTX_data_main(), CTX_data_pointer_get_type(), CTX_data_scene(), CTX_wm_window(), PointerRNA::data, ListBase::first, G, PointerRNA::id, PTCacheBaker::main, MAX_DUPLI_RECUR, NC_OBJECT, NC_SCENE, ND_FRAME, ND_POINTCACHE, PTCacheID::next, NULL, OPERATOR_FINISHED, PTCacheBaker::pid, PTCacheBaker::progressbar, PTCacheBaker::progresscontext, PTCacheBaker::progressend, wmOperator::ptr, PTCacheBaker::quick_step, PTCacheBaker::render, RNA_boolean_get(), RNA_PointCache, PTCacheBaker::scene, WM_cursor_restore(), WM_event_add_notifier(), and WM_timecursor().
Referenced by PTCACHE_OT_bake().
static int ptcache_bake_from_cache_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 257 of file physics_pointcache.c.
References CTX_data_pointer_get_type(), PointerRNA::data, PointCache::flag, PointerRNA::id, NC_OBJECT, ND_POINTCACHE, OPERATOR_FINISHED, PTCACHE_BAKED, RNA_PointCache, and WM_event_add_notifier().
Referenced by PTCACHE_OT_bake_from_cache().
static int ptcache_free_bake_all_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 131 of file physics_pointcache.c.
References Scene::base, BKE_ptcache_ids_from_object(), BLI_freelistN(), PTCacheID::cache, CTX_data_scene(), ListBase::first, PointCache::flag, MAX_DUPLI_RECUR, NC_OBJECT, NC_SCENE, ND_FRAME, ND_POINTCACHE, PTCacheID::next, Base::next, Base::object, OPERATOR_FINISHED, PTCACHE_BAKED, and WM_event_add_notifier().
Referenced by PTCACHE_OT_free_bake_all().
static int ptcache_free_bake_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 237 of file physics_pointcache.c.
References CTX_data_pointer_get_type(), PointerRNA::data, PointCache::edit, PTCacheEdit::edited, PointCache::flag, PointerRNA::id, NC_OBJECT, ND_POINTCACHE, NULL, OPERATOR_FINISHED, PE_free_ptcache_edit(), PTCACHE_BAKED, RNA_PointCache, and WM_event_add_notifier().
Referenced by PTCACHE_OT_free_bake().
void PTCACHE_OT_add (wmOperatorType * ot)
Definition at line 371 of file physics_pointcache.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, ptcache_add_new_exec(), and ptcache_poll().
Referenced by operatortypes_pointcache().
void PTCACHE_OT_bake (wmOperatorType * ot)
Definition at line 269 of file physics_pointcache.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, ptcache_bake_exec(), ptcache_poll(), RNA_def_boolean(), and wmOperatorType::srna.
Referenced by operatortypes_pointcache().
void PTCACHE_OT_bake_all (wmOperatorType * ot)
Definition at line 155 of file physics_pointcache.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, ptcache_bake_all_exec(), ptcache_bake_all_poll(), RNA_def_boolean(), and wmOperatorType::srna.
Referenced by operatortypes_pointcache().
void PTCACHE_OT_bake_from_cache (wmOperatorType * ot)
Definition at line 299 of file physics_pointcache.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, ptcache_bake_from_cache_exec(), and ptcache_poll().
Referenced by operatortypes_pointcache().
void PTCACHE_OT_free_bake (wmOperatorType * ot)
Definition at line 285 of file physics_pointcache.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, ptcache_free_bake_exec(), and ptcache_poll().
Referenced by operatortypes_pointcache().
void PTCACHE_OT_free_bake_all (wmOperatorType * ot)
Definition at line 171 of file physics_pointcache.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, ptcache_bake_all_poll(), and ptcache_free_bake_all_exec().
Referenced by operatortypes_pointcache().
void PTCACHE_OT_remove (wmOperatorType * ot)
Definition at line 385 of file physics_pointcache.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, ptcache_poll(), and ptcache_remove_exec().
Referenced by operatortypes_pointcache().
static int ptcache_poll (bContext * C) [static]
Definition at line 76 of file physics_pointcache.c.
References CTX_data_pointer_get_type(), PointerRNA::data, PointerRNA::id, and RNA_PointCache.
Referenced by PTCACHE_OT_add(), PTCACHE_OT_bake(), PTCACHE_OT_bake_from_cache(), PTCACHE_OT_free_bake(), and PTCACHE_OT_remove().
static int ptcache_remove_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 341 of file physics_pointcache.c.
References BKE_ptcache_free(), BKE_ptcache_ids_from_object(), BLI_freelistN(), BLI_remlink(), PTCacheID::cache, PTCacheID::cache_ptr, CTX_data_pointer_get_type(), CTX_data_scene(), PointerRNA::data, ListBase::first, PointerRNA::id, ListBase::last, MAX_DUPLI_RECUR, NC_OBJECT, ND_POINTCACHE, PTCacheID::next, OPERATOR_FINISHED, PTCacheID::ptcaches, RNA_PointCache, and WM_event_add_notifier().
Referenced by PTCACHE_OT_remove().