Blender: mesh_data.c File Reference
mesh_data.c File Reference
mesh
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_material_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_view3d_types.h"
#include "BLI_utildefines.h"
#include "BLI_array.h"
#include "BLI_math.h"
#include "BLI_edgehash.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_displist.h"
#include "BKE_image.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_material.h"
#include "BKE_mesh.h"
#include "BKE_report.h"
#include "BKE_tessmesh.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_mesh.h"
#include "ED_object.h"
#include "ED_uvedit.h"
#include "ED_view3d.h"
#include "RE_render_ext.h"
#include "mesh_intern.h"
Defines
#define GET_CD_DATA(me, data) (me->edit_btmesh ? &me->edit_btmesh->bm->data : &me->data)
Functions
static void delete_customdata_layer (bContext *C, Object *ob, CustomDataLayer *layer)
static void editmesh_face_copy_customdata (BMEditMesh *em, int type, int index)
static void editmesh_loop_copy_customdata (BMEditMesh *em, int type, int index)
int ED_mesh_uv_loop_reset_ex (struct bContext *C, struct Mesh *me, const int layernum)
int ED_mesh_uv_loop_reset (struct bContext *C, struct Mesh *me)
int ED_mesh_uv_texture_add (bContext *C, Mesh *me, const char *name, int active_set)
int ED_mesh_uv_texture_remove (bContext *C, Object *ob, Mesh *me)
int ED_mesh_color_add (bContext *C, Scene *UNUSED(scene), Object *UNUSED(ob), Mesh *me, const char *name, int active_set)
int ED_mesh_color_remove (bContext *C, Object *ob, Mesh *me)
int ED_mesh_color_remove_named (bContext *C, Object *ob, Mesh *me, const char *name)
static int layers_poll (bContext *C)
static int mesh_uv_texture_add_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_uv_texture_add (wmOperatorType *ot)
static int drop_named_image_invoke (bContext *C, wmOperator *op, wmEvent *event)
void MESH_OT_drop_named_image (wmOperatorType *ot)
static int mesh_uv_texture_remove_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_uv_texture_remove (wmOperatorType *ot)
static int mesh_vertex_color_add_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_vertex_color_add (wmOperatorType *ot)
static int mesh_vertex_color_remove_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_vertex_color_remove (wmOperatorType *ot)
static int mesh_sticky_add_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_sticky_add (wmOperatorType *ot)
static int mesh_sticky_remove_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_sticky_remove (wmOperatorType *ot)
void ED_mesh_update (Mesh *mesh, bContext *C, int calc_edges, int calc_tessface)
static void mesh_add_verts (Mesh *mesh, int len)
void ED_mesh_transform (Mesh *me, float *mat)
static void mesh_add_edges (Mesh *mesh, int len)
static void mesh_add_tessfaces (Mesh *mesh, int len)
static void mesh_add_loops (Mesh *mesh, int len)
static void mesh_add_polys (Mesh *mesh, int len)
static void mesh_remove_verts (Mesh *mesh, int len)
static void mesh_remove_edges (Mesh *mesh, int len)
static void mesh_remove_faces (Mesh *mesh, int len)
void ED_mesh_tessfaces_add (Mesh *mesh, ReportList *reports, int count)
void ED_mesh_edges_add (Mesh *mesh, ReportList *reports, int count)
void ED_mesh_vertices_add (Mesh *mesh, ReportList *reports, int count)
void ED_mesh_faces_remove (Mesh *mesh, ReportList *reports, int count)
void ED_mesh_edges_remove (Mesh *mesh, ReportList *reports, int count)
void ED_mesh_vertices_remove (Mesh *mesh, ReportList *reports, int count)
void ED_mesh_loops_add (Mesh *mesh, ReportList *reports, int count)
void ED_mesh_polys_add (Mesh *mesh, ReportList *reports, int count)
void ED_mesh_calc_normals (Mesh *mesh)
void ED_mesh_calc_tessface (Mesh *mesh)
Detailed Description
Definition in file mesh_data.c.
Define Documentation
#define GET_CD_DATA (me, data) (me->edit_btmesh ? &me->edit_btmesh->bm->data : &me->data)
Definition at line 77 of file mesh_data.c.
Referenced by ED_mesh_color_remove(), ED_mesh_color_remove_named(), ED_mesh_uv_loop_reset(), and ED_mesh_uv_texture_remove().
Function Documentation
static void delete_customdata_layer (bContext * C, Object * ob, CustomDataLayer * layer) [static]
Definition at line 78 of file mesh_data.c.
References BMEditMesh::bm, BM_data_layer_free(), CD_MLOOPCOL, CD_MLOOPUV, CustomData_free_layer_active(), CustomData_get_active_layer_index(), CustomData_get_clone_layer_index(), CustomData_get_layer_index(), CustomData_get_render_layer_index(), CustomData_get_stencil_layer_index(), CustomData_has_layer(), CustomData_set_layer_active(), CustomData_set_layer_clone(), CustomData_set_layer_render(), CustomData_set_layer_stencil(), CustomDataLayer::data, data, Object::data, ED_object_toggle_modes(), Mesh::edit_btmesh, i, CustomData::layers, Mesh::ldata, BMesh::ldata, mesh_update_customdata_pointers(), Object::mode, OB_MODE_VERTEX_PAINT, BMesh::pdata, BMesh::totface, CustomData::totlayer, Mesh::totloop, BMesh::totloop, Mesh::totpoly, TRUE, and CustomDataLayer::type.
Referenced by ED_mesh_color_remove(), ED_mesh_color_remove_named(), and ED_mesh_uv_texture_remove().
static int drop_named_image_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 568 of file mesh_data.c.
References BKE_add_image_file(), BKE_report(), CTX_data_main(), CTX_data_scene(), CTX_wm_view3d(), DAG_id_tag_update(), Object::data, ED_uvedit_assign_image(), ED_view3d_give_base_under_cursor(), EDBM_mesh_free(), EDBM_mesh_load(), EDBM_mesh_make(), Mesh::edit_btmesh, FILE_MAX, find_id(), View3D::flag2, Mesh::id, MAX_ID_NAME, MEM_freeN(), wmEvent::mval, NC_GEOM, ND_DATA, NULL, OB_MESH, Base::object, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_string_get(), RNA_struct_property_is_set(), RPT_ERROR, Scene::toolsettings, Object::type, V3D_SOLID_TEX, and WM_event_add_notifier().
Referenced by MESH_OT_drop_named_image().
void ED_mesh_calc_normals (Mesh * mesh)
Definition at line 1170 of file mesh_data.c.
References FALSE, mesh_calc_normals(), mesh_calc_normals_mapping_ex(), Mesh::mloop, Mesh::mpoly, Mesh::mvert, NULL, Mesh::totloop, Mesh::totpoly, and Mesh::totvert.
void ED_mesh_calc_tessface (Mesh * mesh)
Definition at line 1183 of file mesh_data.c.
References BKE_mesh_tessface_calc(), BMEdit_RecalcTessellation(), and Mesh::edit_btmesh.
int ED_mesh_color_add (bContext * C, Scene * UNUSEDscene, Object * UNUSEDob, Mesh * me, const char * name, int active_set)
Definition at line 443 of file mesh_data.c.
References BMEditMesh::bm, BM_data_layer_add_named(), CD_DEFAULT, CD_DUPLICATE, CD_MCOL, CD_MLOOPCOL, CustomData_add_layer_named(), CustomData_number_of_layers(), CustomData_set_layer_active(), DAG_id_tag_update(), Mesh::edit_btmesh, editmesh_loop_copy_customdata(), Mesh::fdata, Mesh::id, Mesh::ldata, BMesh::ldata, MAX_MCOL, Mesh::mcol, mesh_update_customdata_pointers(), Mesh::mloopcol, NC_GEOM, ND_DATA, NULL, Mesh::totface, Mesh::totloop, TRUE, and WM_event_add_notifier().
int ED_mesh_color_remove (bContext * C, Object * ob, Mesh * me)
Definition at line 495 of file mesh_data.c.
References CD_MLOOPCOL, CustomData_get_active_layer_index(), DAG_id_tag_update(), delete_customdata_layer(), GET_CD_DATA, Mesh::id, if(), CustomData::layers, NC_GEOM, ND_DATA, NULL, and WM_event_add_notifier().
Referenced by mesh_vertex_color_remove_exec().
int ED_mesh_color_remove_named (bContext * C, Object * ob, Mesh * me, const char * name)
Definition at line 514 of file mesh_data.c.
References CD_MLOOPCOL, CustomData_get_named_layer_index(), DAG_id_tag_update(), delete_customdata_layer(), GET_CD_DATA, Mesh::id, if(), CustomData::layers, NC_GEOM, ND_DATA, NULL, and WM_event_add_notifier().
Referenced by output_toggle_exec().
void ED_mesh_edges_add (Mesh * mesh, ReportList * reports, int count)
Definition at line 1088 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_add_edges(), and RPT_ERROR.
void ED_mesh_edges_remove (Mesh * mesh, ReportList * reports, int count)
Definition at line 1122 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_remove_edges(), RPT_ERROR, and Mesh::totedge.
void ED_mesh_faces_remove (Mesh * mesh, ReportList * reports, int count)
Definition at line 1108 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_remove_faces(), RPT_ERROR, and Mesh::totface.
void ED_mesh_loops_add (Mesh * mesh, ReportList * reports, int count)
Definition at line 1150 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_add_loops(), and RPT_ERROR.
void ED_mesh_polys_add (Mesh * mesh, ReportList * reports, int count)
Definition at line 1160 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_add_polys(), and RPT_ERROR.
void ED_mesh_tessfaces_add (Mesh * mesh, ReportList * reports, int count)
Definition at line 1073 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_add_tessfaces(), Mesh::mpoly, and RPT_ERROR.
void ED_mesh_transform (Mesh * me, float * mat)
Definition at line 891 of file mesh_data.c.
References MVert::co, i, mul_m4_v3(), Mesh::mvert, and Mesh::totvert.
void ED_mesh_update (Mesh * mesh, bContext * C, int calc_edges, int calc_tessface)
Definition at line 808 of file mesh_data.c.
References BKE_mesh_calc_edges(), BKE_mesh_convert_mfaces_to_mpolys(), BKE_mesh_tessface_calc(), BKE_mesh_tessface_clear(), CD_CALLOC, CD_NORMAL, CD_POLYINDEX, CustomData_add_layer(), CustomData_get_layer(), DAG_id_tag_update(), FALSE, Mesh::fdata, Mesh::id, mesh_calc_normals(), mesh_calc_normals_mapping_ex(), Mesh::mface, Mesh::mloop, Mesh::mpoly, Mesh::mvert, NC_GEOM, ND_DATA, NULL, Mesh::totedge, Mesh::totface, Mesh::totloop, Mesh::totpoly, Mesh::totvert, TRUE, and WM_event_add_notifier().
int ED_mesh_uv_loop_reset (struct bContext * C, struct Mesh * me)
Definition at line 336 of file mesh_data.c.
References CD_MTEXPOLY, CustomData_get_active_layer_index(), ED_mesh_uv_loop_reset_ex(), and GET_CD_DATA.
Referenced by reset_exec().
int ED_mesh_uv_loop_reset_ex (struct bContext * C, struct Mesh * me, const int layernum)
Definition at line 228 of file mesh_data.c.
References BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_free, BLI_assert, BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, CD_MLOOPUV, cos(), CustomData_bmesh_get_n(), CustomData_get_layer_n(), CustomData_has_layer(), DAG_id_tag_update(), BMHeader::data, Mesh::edit_btmesh, BMLoop::head, i, Mesh::id, Mesh::ldata, BMesh::ldata, len(), BMFace::len, MPoly::loopstart, M_PI, Mesh::mpoly, NC_GEOM, ND_DATA, NULL, sin(), MPoly::totloop, Mesh::totpoly, MLoopUV::uv, and WM_event_add_notifier().
Referenced by ED_mesh_uv_loop_reset(), ED_mesh_uv_texture_add(), and ED_uvedit_ensure_uvs().
int ED_mesh_uv_texture_add (bContext * C, Mesh * me, const char * name, int active_set)
Definition at line 345 of file mesh_data.c.
References BMEditMesh::bm, BM_data_layer_add_named(), CD_DEFAULT, CD_DUPLICATE, CD_MLOOPUV, CD_MTEXPOLY, CD_MTFACE, CustomData_add_layer_named(), CustomData_number_of_layers(), CustomData_set_layer_active(), DAG_id_tag_update(), ED_mesh_uv_loop_reset_ex(), Mesh::edit_btmesh, editmesh_face_copy_customdata(), editmesh_loop_copy_customdata(), FALSE, Mesh::fdata, Mesh::id, Mesh::ldata, BMesh::ldata, MAX_MTFACE, mesh_update_customdata_pointers(), Mesh::mloopuv, Mesh::mtface, Mesh::mtpoly, NC_GEOM, ND_DATA, NULL, BMesh::pdata, Mesh::totface, Mesh::totloop, Mesh::totpoly, TRUE, and WM_event_add_notifier().
Referenced by mesh_uv_texture_add_exec().
int ED_mesh_uv_texture_remove (bContext * C, Object * ob, Mesh * me)
Definition at line 418 of file mesh_data.c.
References CD_MLOOPUV, CD_MTEXPOLY, CustomData_get_active_layer_index(), DAG_id_tag_update(), delete_customdata_layer(), GET_CD_DATA, Mesh::id, if(), CustomData::layers, NC_GEOM, ND_DATA, NULL, and WM_event_add_notifier().
Referenced by mesh_uv_texture_remove_exec().
void ED_mesh_vertices_add (Mesh * mesh, ReportList * reports, int count)
Definition at line 1098 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_add_verts(), and RPT_ERROR.
void ED_mesh_vertices_remove (Mesh * mesh, ReportList * reports, int count)
Definition at line 1136 of file mesh_data.c.
References BKE_report(), Mesh::edit_btmesh, mesh_remove_verts(), RPT_ERROR, and Mesh::totvert.
static void editmesh_face_copy_customdata (BMEditMesh * em, int type, int index) [static]
Definition at line 193 of file mesh_data.c.
References BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_MESH, CustomData_bmesh_get_n(), CustomData_bmesh_set_n(), CustomData_get_active_layer(), BMHeader::data, data, BMFace::head, and BMesh::pdata.
Referenced by ED_mesh_uv_texture_add().
static void editmesh_loop_copy_customdata (BMEditMesh * em, int type, int index) [static]
Definition at line 209 of file mesh_data.c.
References BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, CustomData_bmesh_get_n(), CustomData_bmesh_set_n(), CustomData_get_active_layer(), BMHeader::data, data, BMLoop::head, and BMesh::ldata.
Referenced by ED_mesh_color_add(), and ED_mesh_uv_texture_add().
static int layers_poll (bContext * C) [static]
Definition at line 535 of file mesh_data.c.
References Object::data, data, ED_object_context(), Object::id, ID::lib, NULL, OB_MESH, and Object::type.
Referenced by MESH_OT_drop_named_image(), MESH_OT_sticky_add(), MESH_OT_sticky_remove(), MESH_OT_uv_texture_add(), MESH_OT_uv_texture_remove(), MESH_OT_vertex_color_add(), and MESH_OT_vertex_color_remove().
static void mesh_add_edges (Mesh * mesh, int len) [static]
Definition at line 902 of file mesh_data.c.
References CD_CALLOC, CD_DEFAULT, CD_MASK_MESH, CD_MEDGE, CustomData_add_layer(), CustomData_copy(), CustomData_copy_data(), CustomData_free(), CustomData_has_layer(), FALSE, MEdge::flag, i, len(), ME_EDGEDRAW, ME_EDGERENDER, Mesh::medge, mesh_update_customdata_pointers(), NULL, SELECT, and Mesh::totedge.
Referenced by ED_mesh_edges_add().
static void mesh_add_loops (Mesh * mesh, int len) [static]
Definition at line 962 of file mesh_data.c.
References CD_CALLOC, CD_DEFAULT, CD_MASK_MESH, CD_MLOOP, CustomData_add_layer(), CustomData_copy(), CustomData_copy_data(), CustomData_free(), CustomData_has_layer(), Mesh::ldata, len(), mesh_update_customdata_pointers(), NULL, Mesh::totloop, and TRUE.
Referenced by ED_mesh_loops_add().
static void mesh_add_polys (Mesh * mesh, int len) [static]
Definition at line 986 of file mesh_data.c.
References CD_CALLOC, CD_DEFAULT, CD_MASK_MESH, CD_MPOLY, CustomData_add_layer(), CustomData_copy(), CustomData_copy_data(), CustomData_free(), CustomData_has_layer(), MPoly::flag, i, len(), ME_FACE_SEL, mesh_update_customdata_pointers(), Mesh::mpoly, NULL, Mesh::totpoly, and TRUE.
Referenced by ED_mesh_polys_add().
static void mesh_add_tessfaces (Mesh * mesh, int len) [static]
Definition at line 932 of file mesh_data.c.
References CD_CALLOC, CD_DEFAULT, CD_MASK_MESH, CD_MFACE, CustomData_add_layer(), CustomData_copy(), CustomData_copy_data(), CustomData_free(), CustomData_has_layer(), Mesh::fdata, MFace::flag, i, len(), ME_FACE_SEL, mesh_update_customdata_pointers(), Mesh::mface, NULL, Mesh::totface, and TRUE.
Referenced by ED_mesh_tessfaces_add().
static void mesh_add_verts (Mesh * mesh, int len) [static]
Definition at line 861 of file mesh_data.c.
References CD_CALLOC, CD_DEFAULT, CD_MASK_MESH, CD_MVERT, CustomData_add_layer(), CustomData_copy(), CustomData_copy_data(), CustomData_free(), CustomData_has_layer(), FALSE, MVert::flag, i, len(), mesh_update_customdata_pointers(), Mesh::mvert, NULL, SELECT, and Mesh::totvert.
Referenced by ED_mesh_vertices_add().
void MESH_OT_drop_named_image (wmOperatorType * ot)
Definition at line 636 of file mesh_data.c.
References wmOperatorType::description, drop_named_image_invoke(), FILE_MAX, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, layers_poll(), MAX_ID_NAME, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_sticky_add (wmOperatorType * ot)
Definition at line 759 of file mesh_data.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, layers_poll(), mesh_sticky_add_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_sticky_remove (wmOperatorType * ot)
Definition at line 791 of file mesh_data.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, layers_poll(), mesh_sticky_remove_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_uv_texture_add (wmOperatorType * ot)
Definition at line 553 of file mesh_data.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, layers_poll(), mesh_uv_texture_add_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_uv_texture_remove (wmOperatorType * ot)
Definition at line 666 of file mesh_data.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, layers_poll(), mesh_uv_texture_remove_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_vertex_color_add (wmOperatorType * ot)
Definition at line 695 of file mesh_data.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, layers_poll(), mesh_vertex_color_add_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_vertex_color_remove (wmOperatorType * ot)
Definition at line 721 of file mesh_data.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, layers_poll(), mesh_vertex_color_remove_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
static void mesh_remove_edges (Mesh * mesh, int len) [static]
Definition at line 1030 of file mesh_data.c.
References CustomData_free_elem(), len(), and Mesh::totedge.
Referenced by ED_mesh_edges_remove().
static void mesh_remove_faces (Mesh * mesh, int len) [static]
Definition at line 1043 of file mesh_data.c.
References CustomData_free_elem(), Mesh::fdata, len(), and Mesh::totface.
Referenced by ED_mesh_faces_remove().
static void mesh_remove_verts (Mesh * mesh, int len) [static]
Definition at line 1016 of file mesh_data.c.
References CustomData_free_elem(), len(), and Mesh::totvert.
Referenced by ED_mesh_vertices_remove().
static int mesh_sticky_add_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 738 of file mesh_data.c.
References CTX_data_scene(), CTX_wm_view3d(), DAG_id_tag_update(), Object::data, ED_object_context(), Mesh::id, Mesh::msticky, NC_GEOM, ND_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, RE_make_sticky(), and WM_event_add_notifier().
Referenced by MESH_OT_sticky_add().
static int mesh_sticky_remove_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 774 of file mesh_data.c.
References CD_MSTICKY, CustomData_free_layer_active(), DAG_id_tag_update(), Object::data, ED_object_context(), Mesh::id, Mesh::msticky, NC_GEOM, ND_DATA, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Mesh::totvert, and WM_event_add_notifier().
Referenced by MESH_OT_sticky_remove().
static int mesh_uv_texture_add_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 542 of file mesh_data.c.
References Object::data, ED_mesh_uv_texture_add(), ED_object_context(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_uv_texture_add().
static int mesh_uv_texture_remove_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 655 of file mesh_data.c.
References Object::data, ED_mesh_uv_texture_remove(), ED_object_context(), OPERATOR_CANCELLED, and OPERATOR_FINISHED.
Referenced by MESH_OT_uv_texture_remove().
static int mesh_vertex_color_add_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 683 of file mesh_data.c.
References CTX_data_scene(), Object::data, ED_mesh_color_add(), ED_object_context(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_vertex_color_add().
static int mesh_vertex_color_remove_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 710 of file mesh_data.c.
References Object::data, ED_mesh_color_remove(), ED_object_context(), OPERATOR_CANCELLED, and OPERATOR_FINISHED.
Referenced by MESH_OT_vertex_color_remove().