Blender: LOD_MeshBounds Class Reference
LOD_MeshBounds Class Reference
#include <LOD_MeshBounds.h>
Public Member Functions
void ComputeBounds (const LOD_ManMesh2 *mesh)
MT_Vector3 Min () const
MT_Vector3 Max () const
Static Public Member Functions
static LOD_MeshBounds * New ()
Detailed Description
Definition at line 43 of file LOD_MeshBounds.h.
Member Function Documentation
void LOD_MeshBounds::ComputeBounds (const LOD_ManMesh2 * mesh) [inline]
Definition at line 56 of file LOD_MeshBounds.h.
References MT_assert, NULL, size(), and LOD_ManMesh2::VertexSet().
MT_Vector3 LOD_MeshBounds::Max () const [inline]
Definition at line 85 of file LOD_MeshBounds.h.
MT_Vector3 LOD_MeshBounds::Min () const [inline]
Definition at line 79 of file LOD_MeshBounds.h.
static LOD_MeshBounds* LOD_MeshBounds::New () [inline, static]
Definition at line 48 of file LOD_MeshBounds.h.
References MEM_SmartPtr< T >::Release().
The documentation for this class was generated from the following file:
LOD_MeshBounds.h