Blender: MT_random.h File Reference
MT_random.h File Reference
moto
#include <limits.h>
Defines
#define MT_RAND_MAX UINT_MAX
Functions
void MT_srand (unsigned int)
unsigned int MT_rand ()
Detailed Description
Definition in file MT_random.h.
Define Documentation
#define MT_RAND_MAX UINT_MAX
Definition at line 38 of file MT_random.h.
Referenced by MT_random().
Function Documentation
unsigned int MT_rand ()
Definition at line 94 of file MT_random.cpp.
References LOWER_MASK, M, MATRIX_A, mt, MT_srand(), mti, N, TEMPERING_MASK_B, TEMPERING_MASK_C, TEMPERING_SHIFT_L, TEMPERING_SHIFT_S, TEMPERING_SHIFT_T, TEMPERING_SHIFT_U, and UPPER_MASK.
Referenced by MT_random().
void MT_srand (unsigned int)
Definition at line 83 of file MT_random.cpp.
References mt, mti, and N.
Referenced by MT_rand().