Blender: NG_NetworkDeviceInterface Class Reference
NG_NetworkDeviceInterface Class Reference
#include <NG_NetworkDeviceInterface.h>
Public Member Functions
NG_NetworkDeviceInterface ()
virtual ~NG_NetworkDeviceInterface ()
virtual void NextFrame ()=0
void Online (void)
void Offline (void)
bool IsOnline (void)
virtual bool Connect (char *address, unsigned int port, char *password, unsigned int localport, unsigned int timeout)=0
virtual bool Disconnect (void)=0
virtual void SendNetworkMessage (NG_NetworkMessage *msg)=0
virtual std::vector
< NG_NetworkMessage * > RetrieveNetworkMessages ()=0
Detailed Description
Definition at line 40 of file NG_NetworkDeviceInterface.h.
Constructor & Destructor Documentation
NG_NetworkDeviceInterface::NG_NetworkDeviceInterface () [inline]
Definition at line 46 of file NG_NetworkDeviceInterface.h.
virtual NG_NetworkDeviceInterface::~NG_NetworkDeviceInterface () [inline, virtual]
Definition at line 47 of file NG_NetworkDeviceInterface.h.
Member Function Documentation
virtual bool NG_NetworkDeviceInterface::Connect (char * address, unsigned int port, char * password, unsigned int localport, unsigned int timeout) [pure virtual]
Implemented in NG_LoopBackNetworkDeviceInterface.
virtual bool NG_NetworkDeviceInterface::Disconnect (void) [pure virtual]
Implemented in NG_LoopBackNetworkDeviceInterface.
Referenced by StartKetsjiShell().
bool NG_NetworkDeviceInterface::IsOnline (void) [inline]
Is the network connection established ?
Definition at line 62 of file NG_NetworkDeviceInterface.h.
Referenced by NG_NetworkScene::AddObject(), NG_NetworkScene::FindNetworkObject(), NG_NetworkScene::proceed(), and NG_NetworkScene::RemoveObject().
virtual void NG_NetworkDeviceInterface::NextFrame () [pure virtual]
Implemented in NG_LoopBackNetworkDeviceInterface.
Referenced by KX_KetsjiEngine::NextFrame().
void NG_NetworkDeviceInterface::Offline (void) [inline]
Mark network connection offline
Definition at line 58 of file NG_NetworkDeviceInterface.h.
void NG_NetworkDeviceInterface::Online (void) [inline]
Mark network connection online
Definition at line 54 of file NG_NetworkDeviceInterface.h.
virtual std::vector<NG_NetworkMessage*> NG_NetworkDeviceInterface::RetrieveNetworkMessages () [pure virtual]
read NG_NetworkMessage from library buffer, may be irrelevant for loopbackdevices
Implemented in NG_LoopBackNetworkDeviceInterface.
Referenced by NG_NetworkScene::proceed().
virtual void NG_NetworkDeviceInterface::SendNetworkMessage (NG_NetworkMessage * msg) [pure virtual]
Implemented in NG_LoopBackNetworkDeviceInterface.
Referenced by NG_NetworkScene::SendMessage().
The documentation for this class was generated from the following file:
NG_NetworkDeviceInterface.h