Blender: KDL::Jacobian Class Reference
KDL::Jacobian Class Reference
#include <jacobian.hpp>
Public Member Functions
Jacobian (unsigned int size, unsigned int nr=1)
Jacobian (const Jacobian &arg)
Jacobian & operator= (const Jacobian &arg)
bool operator== (const Jacobian &arg)
bool operator!= (const Jacobian &arg)
~Jacobian ()
double operator() (int i, int j) const
double & operator() (int i, int j)
unsigned int rows () const
unsigned int columns () const
Public Attributes
Twist * twists
Friends
class ChainJntToJacSolver
bool Equal (const Jacobian &a, const Jacobian &b, double eps=epsilon)
void SetToZero (Jacobian &jac)
void changeRefPoint (const Jacobian &src1, const Vector &base_AB, Jacobian &dest)
void changeBase (const Jacobian &src1, const Rotation &rot, Jacobian &dest)
void changeRefFrame (const Jacobian &src1, const Frame &frame, Jacobian &dest)
Detailed Description
Definition at line 32 of file jacobian.hpp.
Constructor & Destructor Documentation
KDL::Jacobian::Jacobian (unsigned int size, unsigned int nr = 1)
Definition at line 29 of file jacobian.cpp.
References twists.
KDL::Jacobian::Jacobian (const Jacobian & arg)
Definition at line 35 of file jacobian.cpp.
References i, and twists.
KDL::Jacobian::~Jacobian ()
Definition at line 54 of file jacobian.cpp.
References twists.
Member Function Documentation
unsigned int KDL::Jacobian::columns () const
Definition at line 76 of file jacobian.cpp.
Referenced by KDL::Equal(), KDL::ChainJntToJacSolver::JntToJac(), KDL::TreeJntToJacSolver::JntToJac(), KDL::MultiplyJacobian(), and KDL::operator<<().
bool KDL::Jacobian::operator!= (const Jacobian & arg)
Definition at line 116 of file jacobian.cpp.
References Equal.
double KDL::Jacobian::operator() (int i, int j) const
Definition at line 59 of file jacobian.cpp.
References assert, and twists.
double & KDL::Jacobian::operator() (int i, int j)
Definition at line 65 of file jacobian.cpp.
References assert, and twists.
Jacobian & KDL::Jacobian::operator= (const Jacobian & arg)
Definition at line 44 of file jacobian.cpp.
References assert, i, and twists.
bool KDL::Jacobian::operator== (const Jacobian & arg)
Definition at line 111 of file jacobian.cpp.
References Equal.
unsigned int KDL::Jacobian::rows () const
Definition at line 71 of file jacobian.cpp.
Referenced by KDL::Equal(), and KDL::operator<<().
Friends And Related Function Documentation
friend class ChainJntToJacSolver [friend]
Definition at line 34 of file jacobian.hpp.
void changeBase (const Jacobian & src1, const Rotation & rot, Jacobian & dest) [friend]
Definition at line 95 of file jacobian.cpp.
void changeRefFrame (const Jacobian & src1, const Frame & frame, Jacobian & dest) [friend]
Definition at line 103 of file jacobian.cpp.
void changeRefPoint (const Jacobian & src1, const Vector & base_AB, Jacobian & dest) [friend]
Definition at line 87 of file jacobian.cpp.
bool Equal (const Jacobian & a, const Jacobian & b, double eps = epsilon) [friend]
Definition at line 121 of file jacobian.cpp.
Referenced by operator!=(), and operator==().
void SetToZero (Jacobian & jac) [friend]
Definition at line 81 of file jacobian.cpp.
Member Data Documentation
Twist* KDL::Jacobian::twists
Definition at line 39 of file jacobian.hpp.
Referenced by KDL::changeBase(), KDL::changeRefFrame(), KDL::changeRefPoint(), KDL::Equal(), Jacobian(), KDL::ChainJntToJacSolver::JntToJac(), KDL::TreeJntToJacSolver::JntToJac(), operator()(), operator=(), KDL::SetToZero(), and ~Jacobian().
The documentation for this class was generated from the following files:
jacobian.hpp
jacobian.cpp