Blender: ARegionType Struct Reference
ARegionType Struct Reference
#include <BKE_screen.h>
Public Attributes
struct ARegionType * next
struct ARegionType * prev
int regionid
void(* init)(struct wmWindowManager *, struct ARegion *)
void(* draw)(const struct bContext *, struct ARegion *)
void(* listener)(struct ARegion *, struct wmNotifier *)
void(* free)(struct ARegion *)
void *(* duplicate)(void *)
void(* operatortypes)(void)
void(* keymap)(struct wmKeyConfig *)
void(* cursor)(struct wmWindow *, struct ScrArea *, struct ARegion *ar)
int(* context)(const struct bContext *, const char *, struct bContextDataResult *)
ListBase drawcalls
ListBase paneltypes
ListBase headertypes
int minsizex
int minsizey
int prefsizex
int prefsizey
int keymapflag
short do_lock
short lock
Detailed Description
Definition at line 111 of file BKE_screen.h.
Member Data Documentation
int(* ARegionType::context)(const struct bContext *, const char *, struct bContextDataResult *)
Definition at line 137 of file BKE_screen.h.
Referenced by CTX_data_dir_get(), and ctx_data_get().
void(* ARegionType::cursor)(struct wmWindow *, struct ScrArea *, struct ARegion *ar)
Definition at line 134 of file BKE_screen.h.
Referenced by ED_spacetype_text(), ED_spacetype_view3d(), and region_cursor_set().
short ARegionType::do_lock
Definition at line 155 of file BKE_screen.h.
Referenced by BKE_spacedata_draw_locks(), and ED_region_do_draw().
void(* ARegionType::draw)(const struct bContext *, struct ARegion *)
Definition at line 119 of file BKE_screen.h.
Referenced by ED_region_do_draw(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), ui_popup_block_create(), ui_searchbox_create(), and ui_tooltip_create().
ListBase ARegionType::drawcalls
Definition at line 140 of file BKE_screen.h.
Referenced by ED_region_draw_cb_activate(), ED_region_draw_cb_draw(), ED_region_draw_cb_exit(), and spacetype_free().
void*(* ARegionType::duplicate)(void *)
Definition at line 126 of file BKE_screen.h.
Referenced by BKE_area_region_copy(), and ED_spacetype_view3d().
void(* ARegionType::free)(struct ARegion *)
Definition at line 123 of file BKE_screen.h.
Referenced by BKE_area_region_free(), ED_spacetype_outliner(), ED_spacetype_view3d(), ui_searchbox_create(), and ui_tooltip_create().
ListBase ARegionType::headertypes
Definition at line 146 of file BKE_screen.h.
Referenced by ED_region_header(), and spacetype_free().
void(* ARegionType::init)(struct wmWindowManager *, struct ARegion *)
Definition at line 117 of file BKE_screen.h.
Referenced by ED_area_initialize(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), and ED_spacetype_view3d().
void(* ARegionType::keymap)(struct wmKeyConfig *)
Definition at line 132 of file BKE_screen.h.
Referenced by ED_spacetype_time(), and ED_spacetypes_keymap().
int ARegionType::keymapflag
Definition at line 153 of file BKE_screen.h.
Referenced by ED_area_initialize(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), and ED_spacetype_view3d().
void(* ARegionType::listener)(struct ARegion *, struct wmNotifier *)
Definition at line 121 of file BKE_screen.h.
Referenced by ED_region_do_listen(), ED_spacetype_action(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_time(), ED_spacetype_userpref(), and ED_spacetype_view3d().
short ARegionType::lock
Definition at line 155 of file BKE_screen.h.
Referenced by BKE_spacedata_draw_locks(), and ED_spacetype_view3d().
int ARegionType::minsizex
Definition at line 149 of file BKE_screen.h.
int ARegionType::minsizey
Definition at line 149 of file BKE_screen.h.
struct ARegionType* ARegionType::next
Definition at line 112 of file BKE_screen.h.
Referenced by BKE_regiontype_from_id(), BKE_spacedata_draw_locks(), ED_spacetypes_keymap(), and spacetype_free().
void(* ARegionType::operatortypes)(void)
Definition at line 130 of file BKE_screen.h.
ListBase ARegionType::paneltypes
Definition at line 143 of file BKE_screen.h.
Referenced by buttons_context_register(), ED_clip_buttons_register(), ED_clip_tool_props_register(), ED_region_panels(), ED_uvedit_buttons_register(), file_panels_register(), graph_buttons_register(), image_buttons_register(), nla_buttons_register(), node_buttons_register(), spacetype_free(), view3d_buttons_register(), view3d_tool_props_register(), and view3d_toolshelf_register().
int ARegionType::prefsizex
Definition at line 151 of file BKE_screen.h.
Referenced by ED_region_panels(), ED_spacetype_action(), ED_spacetype_clip(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_view3d(), region_rect_recursive(), and region_scale_invoke().
int ARegionType::prefsizey
Definition at line 151 of file BKE_screen.h.
Referenced by ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), region_rect_recursive(), region_scale_invoke(), and screen_refresh_headersizes().
struct ARegionType * ARegionType::prev
Definition at line 112 of file BKE_screen.h.
int ARegionType::regionid
Definition at line 114 of file BKE_screen.h.
Referenced by BKE_regiontype_from_id(), ED_region_do_draw(), ED_region_panels(), ED_region_set(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), and ED_spacetype_view3d().
The documentation for this struct was generated from the following file:
BKE_screen.h