Blender: KX_NetworkMessageActuator Class Reference
KX_NetworkMessageActuator Class Reference
#include <KX_NetworkMessageActuator.h>
Public Member Functions
KX_NetworkMessageActuator (SCA_IObject *gameobj, NG_NetworkScene *networkscene, const STR_String &toPropName, const STR_String &subject, int bodyType, const STR_String &body)
virtual ~KX_NetworkMessageActuator ()
virtual bool Update ()
virtual CValue * GetReplica ()
virtual void Replace_NetworkScene (NG_NetworkScene *val)
Detailed Description
Definition at line 40 of file KX_NetworkMessageActuator.h.
Constructor & Destructor Documentation
KX_NetworkMessageActuator::KX_NetworkMessageActuator (SCA_IObject * gameobj, NG_NetworkScene * networkscene, const STR_String & toPropName, const STR_String & subject, int bodyType, const STR_String & body)
Definition at line 39 of file KX_NetworkMessageActuator.cpp.
Referenced by GetReplica().
KX_NetworkMessageActuator::~KX_NetworkMessageActuator () [virtual]
Definition at line 55 of file KX_NetworkMessageActuator.cpp.
Member Function Documentation
CValue * KX_NetworkMessageActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 90 of file KX_NetworkMessageActuator.cpp.
References KX_NetworkMessageActuator(), and SCA_IActuator::ProcessReplica().
virtual void KX_NetworkMessageActuator::Replace_NetworkScene (NG_NetworkScene * val) [inline, virtual]
Reimplemented from SCA_ILogicBrick.
Definition at line 61 of file KX_NetworkMessageActuator.h.
bool KX_NetworkMessageActuator::Update (void) [virtual]
Reimplemented from SCA_IActuator.
Definition at line 60 of file KX_NetworkMessageActuator.cpp.
References SCA_ILogicBrick::GetName(), SCA_ILogicBrick::GetParent(), CValue::GetPropertyText(), SCA_IActuator::IsNegativeEvent(), SCA_IActuator::RemoveAllEvents(), and NG_NetworkScene::SendMessage().
The documentation for this class was generated from the following files:
KX_NetworkMessageActuator.h
KX_NetworkMessageActuator.cpp