Blender: rna_timeline.c File Reference
rna_timeline.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_scene_types.h"
#include "WM_types.h"
Functions
static void rna_def_timeline_marker (BlenderRNA *brna)
void RNA_def_timeline_marker (BlenderRNA *brna)
Detailed Description
Definition in file rna_timeline.c.
Function Documentation
static void rna_def_timeline_marker (BlenderRNA * brna) [static]
Definition at line 50 of file rna_timeline.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ID_SELF_CHECK, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_TIME, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_timeline_marker().
void RNA_def_timeline_marker (BlenderRNA * brna)
Definition at line 82 of file rna_timeline.c.
References rna_def_timeline_marker().