Blender: LOD_FaceNormalEditor Class Reference
LOD_FaceNormalEditor Class Reference
#include <LOD_FaceNormalEditor.h>
Public Member Functions
void Remove (std::vector< LOD_FaceInd > &sorted_faces)
void Add ()
void Update (std::vector< LOD_FaceInd > &sorted_faces)
void RemoveVertexNormals (std::vector< LOD_VertexInd > &sorted_verts)
void UpdateVertexNormals (std::vector< LOD_VertexInd > &sorted_verts)
const std::vector< MT_Vector3 > & Normals () const
const std::vector< MT_Vector3 > & VertexNormals () const
void BuildNormals ()
Static Public Member Functions
static LOD_FaceNormalEditor * New (LOD_ManMesh2 &mesh)
Detailed Description
Definition at line 41 of file LOD_FaceNormalEditor.h.
Member Function Documentation
void LOD_FaceNormalEditor::Add ()
Definition at line 110 of file LOD_FaceNormalEditor.cpp.
void LOD_FaceNormalEditor::BuildNormals ()
Definition at line 185 of file LOD_FaceNormalEditor.cpp.
References LOD_ManMesh2::FaceSet(), MEM_SmartPtr< T >::Ref(), and LOD_ManMesh2::VertexSet().
LOD_FaceNormalEditor * LOD_FaceNormalEditor::New (LOD_ManMesh2 & mesh) [static]
Definition at line 48 of file LOD_FaceNormalEditor.cpp.
References LOD_ManMesh2::FaceSet(), NULL, MEM_SmartPtr< T >::Release(), and LOD_ManMesh2::VertexSet().
const std::vector<MT_Vector3>& LOD_FaceNormalEditor::Normals () const [inline]
Definition at line 94 of file LOD_FaceNormalEditor.h.
References MEM_SmartPtr< T >::Ref().
void LOD_FaceNormalEditor::Remove (std::vector< LOD_FaceInd > & sorted_faces)
Definition at line 81 of file LOD_FaceNormalEditor.cpp.
References MEM_SmartPtr< T >::Ref().
void LOD_FaceNormalEditor::RemoveVertexNormals (std::vector< LOD_VertexInd > & sorted_verts)
Definition at line 140 of file LOD_FaceNormalEditor.cpp.
References MEM_SmartPtr< T >::Ref().
void LOD_FaceNormalEditor::Update (std::vector< LOD_FaceInd > & sorted_faces)
Definition at line 118 of file LOD_FaceNormalEditor.cpp.
References LOD_ManMesh2::FaceSet(), and MEM_SmartPtr< T >::Ref().
void LOD_FaceNormalEditor::UpdateVertexNormals (std::vector< LOD_VertexInd > & sorted_verts)
Definition at line 165 of file LOD_FaceNormalEditor.cpp.
References MEM_SmartPtr< T >::Ref().
const std::vector<MT_Vector3>& LOD_FaceNormalEditor::VertexNormals () const [inline]
Definition at line 102 of file LOD_FaceNormalEditor.h.
References MEM_SmartPtr< T >::Ref().
The documentation for this class was generated from the following files:
LOD_FaceNormalEditor.h
LOD_FaceNormalEditor.cpp