Blender: paint_cursor.c File Reference
paint_cursor.c File Reference
sculpt and paint
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "DNA_brush_types.h"
#include "DNA_color_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_userdef_types.h"
#include "BKE_brush.h"
#include "BKE_context.h"
#include "BKE_paint.h"
#include "WM_api.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "ED_view3d.h"
#include "paint_intern.h"
#include "sculpt_intern.h"
Classes
struct Snapshot
Typedefs
typedef struct Snapshot Snapshot
Functions
static int same_snap (Snapshot *snap, Brush *brush, ViewContext *vc)
static void make_snap (Snapshot *snap, Brush *brush, ViewContext *vc)
static int load_tex (Sculpt *sd, Brush *br, ViewContext *vc)
static int project_brush_radius (ViewContext *vc, float radius, const float location[3])
static int sculpt_get_brush_geometry (bContext *C, ViewContext *vc, int x, int y, int *pixel_radius, float location[3])
static void paint_draw_alpha_overlay (Sculpt *sd, Brush *brush, ViewContext *vc, int x, int y)
static void paint_cursor_on_hit (Sculpt *sd, Brush *brush, ViewContext *vc, const float location[3])
static void paint_draw_cursor (bContext *C, int x, int y, void *UNUSED(unused))
void paint_cursor_start (bContext *C, int(*poll)(bContext *C))
Detailed Description
Definition in file paint_cursor.c.
Typedef Documentation
typedef struct Snapshot Snapshot
Function Documentation
static int load_tex (Sculpt * sd, Brush * br, ViewContext * vc) [static]
Definition at line 118 of file paint_cursor.c.
References angle(), ViewContext::ar, atan2f, brush_curve_strength(), MTex::brush_map_mode, brush_size(), CurveMapping::changed_timestamp, PreviewImage::changed_timestamp, cosf, Brush::curve, i, init(), len(), make_snap(), MEM_freeN(), MEM_mallocN(), Brush::mtex, MTEX_MAP_MODE_FIXED, MTEX_MAP_MODE_TILED, NULL, MTex::ofs, paint_get_tex_pixel(), Tex::preview, MTex::rot, same_snap(), ViewContext::scene, sinf, MTex::size, size(), sqrtf, MTex::tex, Brush::texture_sample_bias, ARegion::winx, and ARegion::winy.
Referenced by paint_draw_alpha_overlay().
static void make_snap (Snapshot * snap, Brush * brush, ViewContext * vc) [static]
Definition at line 98 of file paint_cursor.c.
References ViewContext::ar, MTex::brush_map_mode, Snapshot::brush_map_mode, brush_size(), Snapshot::brush_size, copy_v3_v3(), Brush::mtex, MTex::ofs, Snapshot::ofs, MTex::rot, Snapshot::rot, ViewContext::scene, MTex::size, Snapshot::size, MTex::tex, ARegion::winx, Snapshot::winx, ARegion::winy, and Snapshot::winy.
Referenced by load_tex().
static void paint_cursor_on_hit (Sculpt * sd, Brush * brush, ViewContext * vc, const float location[3]) [static]
Definition at line 470 of file paint_cursor.c.
References Sculpt::anchored_size, BRUSH_ANCHORED, brush_set_unprojected_radius(), brush_size(), brush_use_locked_size(), brush_use_size_pressure(), Sculpt::draw_anchored, Sculpt::draw_pressure, Brush::flag, paint_calc_object_space_radius(), Sculpt::pressure_value, and ViewContext::scene.
Referenced by paint_draw_cursor().
void paint_cursor_start (bContext * C, int(*)(bContext *C) poll)
Definition at line 601 of file paint_cursor.c.
References CTX_data_scene(), CTX_wm_manager(), NULL, p, Paint::paint_cursor, paint_draw_cursor(), paint_get_active(), and WM_paint_cursor_activate().
Referenced by sculpt_toggle_mode(), set_vpaint(), and set_wpaint().
static void paint_draw_alpha_overlay (Sculpt * sd, Brush * brush, ViewContext * vc, int x, int y) [static]
Definition at line 372 of file paint_cursor.c.
References Sculpt::anchored_initial_mouse, Sculpt::anchored_size, ViewContext::ar, MTex::brush_map_mode, BRUSH_RAKE, brush_size(), BRUSH_TEXTURE_OVERLAY, brush_use_size_pressure(), Sculpt::draw_anchored, Sculpt::draw_pressure, ELEM, Brush::flag, Sculpt::last_angle, load_tex(), Brush::mtex, MTEX_MAP_MODE_FIXED, MTEX_MAP_MODE_TILED, Sculpt::pressure_value, RAD2DEGF, ViewContext::scene, Sculpt::special_rotation, Brush::texture_overlay_alpha, ARegion::winrct, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by paint_draw_cursor().
static void paint_draw_cursor (bContext * C, int x, int y, void * UNUSEDunused) [static]
Definition at line 500 of file paint_cursor.c.
References Brush::add_col, Sculpt::anchored_initial_mouse, Sculpt::anchored_size, ViewContext::ar, KDL::atan2(), BRUSH_DIR_IN, BRUSH_INVERTED, brush_set_size(), brush_size(), brush_use_locked_size(), CTX_data_scene(), CTX_data_tool_settings(), Sculpt::draw_anchored, ELEM5, Brush::flag, Paint::flags, glutil_draw_lined_arc(), Sculpt::last_angle, Sculpt::last_x, Sculpt::last_y, M_PI, ViewContext::obact, paint_brush(), paint_cursor_on_hit(), paint_draw_alpha_overlay(), paint_get_active(), PAINT_SHOW_BRUSH, ToolSettings::sculpt, Object::sculpt, sculpt_get_brush_geometry(), Brush::sculpt_tool, SCULPT_TOOL_CLAY, SCULPT_TOOL_CREASE, SCULPT_TOOL_DRAW, SCULPT_TOOL_INFLATE, SCULPT_TOOL_PINCH, Brush::sub_col, view3d_set_viewcontext(), ARegion::winrct, rcti::xmin, and rcti::ymin.
Referenced by paint_cursor_start().
static int project_brush_radius (ViewContext * vc, float radius, const float location[3]) [static]
Definition at line 289 of file paint_cursor.c.
References add_v3_v3v3(), ViewContext::ar, cross_v3_v3v3(), ED_view3d_global_to_vector(), fabsf, len_v2v2(), mul_v3_fl(), normalize_v3(), project_float(), and ViewContext::rv3d.
Referenced by sculpt_get_brush_geometry().
static int same_snap (Snapshot * snap, Brush * brush, ViewContext * vc) [static]
Definition at line 79 of file paint_cursor.c.
References ViewContext::ar, Snapshot::brush_map_mode, MTex::brush_map_mode, Snapshot::brush_size, brush_size(), equals_v3v3(), Brush::mtex, MTEX_MAP_MODE_FIXED, Snapshot::ofs, MTex::ofs, Snapshot::rot, MTex::rot, ViewContext::scene, Snapshot::size, MTex::size, MTex::tex, Snapshot::winx, ARegion::winx, Snapshot::winy, and ARegion::winy.
Referenced by load_tex().
static int sculpt_get_brush_geometry (bContext * C, ViewContext * vc, int x, int y, int * pixel_radius, float location[3]) [static]
Definition at line 331 of file paint_cursor.c.
References ViewContext::ar, brush_size(), brush_unprojected_radius(), CTX_data_scene(), CTX_data_tool_settings(), mul_m4_v3(), ViewContext::obact, Object::obmat, Sculpt::paint, paint_brush(), paint_get_active(), SculptSession::pbvh, project_brush_radius(), ToolSettings::sculpt, Object::sculpt, sculpt_stroke_get_location(), ARegion::winrct, rcti::xmin, and rcti::ymin.
Referenced by paint_draw_cursor().