Blender: rna_object.c File Reference
rna_object.c File Reference
RNA
#include <stdio.h>
#include <stdlib.h>
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_action_types.h"
#include "DNA_customdata_types.h"
#include "DNA_controller_types.h"
#include "DNA_group_types.h"
#include "DNA_material_types.h"
#include "DNA_mesh_types.h"
#include "DNA_object_force.h"
#include "DNA_object_types.h"
#include "DNA_property_types.h"
#include "DNA_scene_types.h"
#include "DNA_meta_types.h"
#include "BLI_utildefines.h"
#include "BKE_tessmesh.h"
#include "BKE_group.h"
#include "BLO_sys_types.h"
#include "ED_mesh.h"
#include "WM_api.h"
#include "WM_types.h"
Defines
#define OBTYPE_CU_CURVE {OB_CURVE, "CURVE", 0, "Curve", ""}
#define OBTYPE_CU_SURF {OB_SURF, "SURFACE", 0, "Surface", ""}
#define OBTYPE_CU_FONT {OB_FONT, "FONT", 0, "Font", ""}
Functions
static void rna_def_vertex_group (BlenderRNA *brna)
static void rna_def_material_slot (BlenderRNA *brna)
static void rna_def_object_game_settings (BlenderRNA *brna)
static void rna_def_object_constraints (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_object_modifiers (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_object_particle_systems (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_object_vertex_groups (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_object (BlenderRNA *brna)
static void rna_def_dupli_object (BlenderRNA *brna)
static void rna_def_object_base (BlenderRNA *brna)
void RNA_def_object (BlenderRNA *brna)
Variables
EnumPropertyItem object_mode_items []
static EnumPropertyItem parent_type_items []
static EnumPropertyItem collision_bounds_items []
EnumPropertyItem metaelem_type_items []
EnumPropertyItem object_type_items []
EnumPropertyItem object_type_curve_items []
static int rna_matrix_dimsize_4x4 [] = {4, 4}
Detailed Description
Definition in file rna_object.c.
Define Documentation
#define OBTYPE_CU_CURVE {OB_CURVE, "CURVE", 0, "Curve", ""}
Definition at line 102 of file rna_object.c.
#define OBTYPE_CU_FONT {OB_FONT, "FONT", 0, "Font", ""}
Definition at line 104 of file rna_object.c.
#define OBTYPE_CU_SURF {OB_SURF, "SURFACE", 0, "Surface", ""}
Definition at line 103 of file rna_object.c.
Function Documentation
static void rna_def_dupli_object (BlenderRNA * brna) [static]
Definition at line 2470 of file rna_object.c.
References NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_EDITABLE, PROP_FLOAT, PROP_MATRIX, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_float_sdna(), RNA_def_property_multi_array(), RNA_def_property_pointer_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_object().
static void rna_def_material_slot (BlenderRNA * brna) [static]
Definition at line 1372 of file rna_object.c.
References NC_OBJECT, ND_DRAW, NULL, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_object().
static void rna_def_object (BlenderRNA * brna) [static]
Definition at line 1823 of file rna_object.c.
References FLT_MAX, MAXFRAME, MAXFRAMEF, MINAFRAME, MINAFRAMEF, MINFRAME, NC_MATERIAL, NC_OBJECT, ND_DRAW, ND_SHADING, ND_TRANSFORM, NULL, OB_ARROWS, OB_AXIS, OB_BOUND_BOX, OB_BOUND_CONE, OB_BOUND_CYLINDER, OB_BOUND_SPHERE, OB_BOUNDBOX, OB_CIRCLE, OB_CUBE, OB_DRAWNAME, OB_DRAWTRANSP, OB_DRAWWIRE, OB_DRAWXRAY, OB_DUPLI, OB_DUPLIFACES, OB_DUPLIFACES_SCALE, OB_DUPLIFRAMES, OB_DUPLIGROUP, OB_DUPLINOSPEED, OB_DUPLIROT, OB_DUPLIVERTS, OB_EMPTY_CONE, OB_EMPTY_IMAGE, OB_EMPTY_SPHERE, OB_LOCK_LOCX, OB_LOCK_ROT4D, OB_LOCK_ROTW, OB_LOCK_ROTX, OB_LOCK_SCALEX, OB_NEGX, OB_NEGY, OB_NEGZ, OB_PLAINAXES, OB_POSX, OB_POSY, OB_POSZ, OB_RESTRICT_RENDER, OB_RESTRICT_SELECT, OB_RESTRICT_VIEW, OB_SHAPE_EDIT_MODE, OB_SHAPE_LOCK, OB_SINGLE_ARROW, OB_SOLID, OB_TEXSPACE, OB_TEXTURE, OB_WIRE, PARSLOW, PROP_ANIMATABLE, PROP_AXISANGLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_COLOR, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_EULER, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_INT, PROP_LAYER_MEMBER, PROP_LIB_EXCEPTION, PROP_MATRIX, PROP_NEVER_NULL, PROP_NEVER_UNLINK, PROP_NONE, PROP_POINTER, PROP_QUATERNION, PROP_STRING, PROP_TRANSLATION, PROP_UNIT_TIME, PROP_UNSIGNED, PROP_XYZ, PROP_XYZ_LENGTH, RNA_api_object(), rna_def_animdata_common(), rna_def_animviz_common(), rna_def_motionpath_common(), rna_def_object_constraints(), rna_def_object_modifiers(), rna_def_object_particle_systems(), rna_def_object_vertex_groups(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_editable_array_func(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_array_default(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_multi_array(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), RNA_TRANSLATION_PREC_DEFAULT, ROT_MODE_AXISANGLE, ROT_MODE_QUAT, ROT_MODE_XYZ, ROT_MODE_XZY, ROT_MODE_YXZ, ROT_MODE_YZX, ROT_MODE_ZXY, ROT_MODE_ZYX, SELECT, and STRUCT_ID_REFCOUNT.
Referenced by RNA_def_object().
void RNA_def_object (BlenderRNA * brna)
Definition at line 2535 of file rna_object.c.
References rna_def_dupli_object(), rna_def_material_slot(), rna_def_object(), rna_def_object_base(), rna_def_object_game_settings(), and rna_def_vertex_group().
static void rna_def_object_base (BlenderRNA * brna) [static]
Definition at line 2505 of file rna_object.c.
References BA_SELECT, NC_OBJECT, ND_DRAW, NULL, PROP_BOOLEAN, PROP_LAYER_MEMBER, PROP_NONE, PROP_POINTER, RNA_api_object_base(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_object().
static void rna_def_object_constraints (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1647 of file rna_object.c.
References constraint_type_items, FUNC_USE_REPORTS, NULL, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REQUIRED, RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_object().
static void rna_def_object_game_settings (BlenderRNA * brna) [static]
Definition at line 1410 of file rna_object.c.
References FLT_MAX, NC_LOGIC, NC_OBJECT, ND_DRAW, NULL, OB_ACTOR, OB_ALLSTATE, OB_ANISOTROPIC_FRICTION, OB_BODY_TYPE_DYNAMIC, OB_BODY_TYPE_NAVMESH, OB_BODY_TYPE_NO_COLLISION, OB_BODY_TYPE_OCCLUDER, OB_BODY_TYPE_RIGID, OB_BODY_TYPE_SENSOR, OB_BODY_TYPE_SOFT, OB_BODY_TYPE_STATIC, OB_BOUNDS, OB_CHILD, OB_COLLISION_RESPONSE, OB_DEBUGSTATE, OB_DO_FH, OB_GHOST, OB_HASOBSTACLE, OB_LOCK_RIGID_BODY_X_AXIS, OB_LOCK_RIGID_BODY_X_ROT_AXIS, OB_LOCK_RIGID_BODY_Y_AXIS, OB_LOCK_RIGID_BODY_Y_ROT_AXIS, OB_LOCK_RIGID_BODY_Z_AXIS, OB_LOCK_RIGID_BODY_Z_ROT_AXIS, OB_NEVER_DO_ACTIVITY_CULLING, OB_ROT_FH, OB_SHOWACT, OB_SHOWCONT, OB_SHOWSENS, OB_SHOWSTATE, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_LAYER_MEMBER, PROP_NONE, PROP_POINTER, PROP_UNIT_LENGTH, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_object().
static void rna_def_object_modifiers (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1692 of file rna_object.c.
References FUNC_USE_CONTEXT, FUNC_USE_REPORTS, modifier_type_items, NULL, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REQUIRED, RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_object().
static void rna_def_object_particle_systems (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1745 of file rna_object.c.
References NC_OBJECT, ND_DRAW, NULL, PROP_ANIMATABLE, PROP_INT, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_int_funcs(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_object().
static void rna_def_object_vertex_groups (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1776 of file rna_object.c.
References NC_GEOM, ND_DATA, NULL, PROP_ANIMATABLE, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REQUIRED, RNA_def_function(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_object().
static void rna_def_vertex_group (BlenderRNA * brna) [static]
Definition at line 1309 of file rna_object.c.
References FUNC_USE_REPORTS, FUNC_USE_SELF_ID, NA_RENAME, NC_GEOM, ND_DATA, NULL, PROP_BOOLEAN, PROP_DYNAMIC, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_REQUIRED, PROP_STRING, PROP_UNSIGNED, RNA_def_enum(), RNA_def_float(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_int_array(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_string_funcs(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), WEIGHT_ADD, WEIGHT_REPLACE, and WEIGHT_SUBTRACT.
Referenced by RNA_def_object().
Variable Documentation
EnumPropertyItem collision_bounds_items[] [static]
Initial value:
 {
    {OB_BOUND_BOX, "BOX", 0, "Box", ""},
    {OB_BOUND_SPHERE, "SPHERE", 0, "Sphere", ""},
    {OB_BOUND_CYLINDER, "CYLINDER", 0, "Cylinder", ""},
    {OB_BOUND_CONE, "CONE", 0, "Cone", ""},
    {OB_BOUND_CONVEX_HULL, "CONVEX_HULL", 0, "Convex Hull", ""},
    {OB_BOUND_TRIANGLE_MESH, "TRIANGLE_MESH", 0, "Triangle Mesh", ""},
    {OB_BOUND_CAPSULE, "CAPSULE", 0, "Capsule", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 82 of file rna_object.c.
EnumPropertyItem metaelem_type_items[]
Initial value:
 {
    {MB_BALL, "BALL", ICON_META_BALL, "Ball", ""},
    {MB_TUBE, "CAPSULE", ICON_META_CAPSULE, "Capsule", ""},
    {MB_PLANE, "PLANE", ICON_META_PLANE, "Plane", ""},
    {MB_ELIPSOID, "ELLIPSOID", ICON_META_ELLIPSOID, "Ellipsoid", ""},
    {MB_CUBE, "CUBE", ICON_META_CUBE, "Cube", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 93 of file rna_object.c.
Referenced by OBJECT_OT_metaball_add(), rna_def_metaball_elements(), and rna_def_metaelement().
EnumPropertyItem object_mode_items[]
Initial value:
 {
    {OB_MODE_OBJECT, "OBJECT", ICON_OBJECT_DATAMODE, "Object", ""},
    {OB_MODE_EDIT, "EDIT", ICON_EDITMODE_HLT, "Edit", ""},
    {OB_MODE_SCULPT, "SCULPT", ICON_SCULPTMODE_HLT, "Sculpt", ""},
    {OB_MODE_VERTEX_PAINT, "VERTEX_PAINT", ICON_VPAINT_HLT, "Vertex Paint", ""},
    {OB_MODE_WEIGHT_PAINT, "WEIGHT_PAINT", ICON_WPAINT_HLT, "Weight Paint", ""},
    {OB_MODE_TEXTURE_PAINT, "TEXTURE_PAINT", ICON_TPAINT_HLT, "Texture Paint", ""},
    {OB_MODE_PARTICLE_EDIT, "PARTICLE_EDIT", ICON_PARTICLEMODE, "Particle Edit", ""},
    {OB_MODE_POSE, "POSE", ICON_POSE_HLT, "Pose", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 60 of file rna_object.c.
Referenced by object_mode_icon(), object_mode_set_itemsf(), and OBJECT_OT_mode_set().
EnumPropertyItem object_type_curve_items[]
Initial value:
 {
    OBTYPE_CU_CURVE,
    OBTYPE_CU_SURF,
    OBTYPE_CU_FONT,
    {0, NULL, 0, NULL, NULL}}
Definition at line 122 of file rna_object.c.
Referenced by RNA_def_main_curves().
EnumPropertyItem object_type_items[]
Initial value:
 {
    {OB_MESH, "MESH", 0, "Mesh", ""},
    OBTYPE_CU_CURVE,
    OBTYPE_CU_SURF,
    {OB_MBALL, "META", 0, "Meta", ""},
    OBTYPE_CU_FONT,
    {0, "", 0, NULL, NULL},
    {OB_ARMATURE, "ARMATURE", 0, "Armature", ""},
    {OB_LATTICE, "LATTICE", 0, "Lattice", ""},
    {OB_EMPTY, "EMPTY", 0, "Empty", ""},
    {0, "", 0, NULL, NULL},
    {OB_CAMERA, "CAMERA", 0, "Camera", ""},
    {OB_LAMP, "LAMP", 0, "Lamp", ""},
    {OB_SPEAKER, "SPEAKER", 0, "Speaker", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 106 of file rna_object.c.
Referenced by OBJECT_OT_add(), and OBJECT_OT_select_by_type().
EnumPropertyItem parent_type_items[] [static]
Initial value:
 {
    {PAROBJECT, "OBJECT", 0, "Object", "The object is parented to an object"},
    {PARCURVE, "CURVE", 0, "Curve", "The object is parented to a curve"},
    {PARKEY, "KEY", 0, "Key", ""},
    {PARSKEL, "ARMATURE", 0, "Armature", ""},
    {PARSKEL, "LATTICE", 0, "Lattice", "The object is parented to a lattice"},
    {PARVERT1, "VERTEX", 0, "Vertex", "The object is parented to a vertex"},
    {PARVERT3, "VERTEX_3", 0, "3 Vertices", ""},
    {PARBONE, "BONE", 0, "Bone", "The object is parented to a bone"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 71 of file rna_object.c.
int rna_matrix_dimsize_4x4[] = {4, 4} [static]
Definition at line 1307 of file rna_object.c.