Blender: itasc_plugin.h File Reference
itasc_plugin.h File Reference
ikplugin
#include "ikplugin_api.h"
Functions
void itasc_initialize_tree (struct Scene *scene, struct Object *ob, float ctime)
void itasc_execute_tree (struct Scene *scene, struct Object *ob, struct bPoseChannel *pchan, float ctime)
void itasc_release_tree (struct Scene *scene, struct Object *ob, float ctime)
void itasc_clear_data (struct bPose *pose)
void itasc_clear_cache (struct bPose *pose)
void itasc_update_param (struct bPose *pose)
void itasc_test_constraint (struct Object *ob, struct bConstraint *cons)
Detailed Description
Definition in file itasc_plugin.h.
Function Documentation
void itasc_clear_cache (struct bPose * pose)
Definition at line 1768 of file itasc_plugin.cpp.
References IK_Data::first, bPose::ikdata, IK_Scene::next, and NULL.
void itasc_clear_data (struct bPose * pose)
Definition at line 1755 of file itasc_plugin.cpp.
References IK_Data::first, bPose::ikdata, MEM_freeN(), IK_Scene::next, and NULL.
Referenced by itasc_initialize_tree().
void itasc_execute_tree (struct Scene * scene, struct Object * ob, struct bPoseChannel * pchan, float ctime)
Definition at line 1726 of file itasc_plugin.cpp.
References bPose::ctime, DefIKParam, execute_scene(), IK_Data::first, bPose::flag, RenderData::frs_sec, RenderData::frs_sec_base, bPose::ikdata, bPose::ikparam, IK_Scene::next, Object::pose, POSE_GAME_ENGINE, and Scene::r.
void itasc_initialize_tree (struct Scene * scene, struct Object * ob, float ctime)
Definition at line 1701 of file itasc_plugin.cpp.
References bPose::chanbase, bPoseChannel::constflag, create_scene(), ListBase::first, bPose::flag, bPose::ikdata, init_scene(), initialize_scene(), itasc_clear_data(), itasc_update_param(), bPoseChannel::next, NULL, PCHAN_HAS_IK, Object::pose, and POSE_WAS_REBUILT.
void itasc_release_tree (struct Scene * scene, struct Object * ob, float ctime)
Definition at line 1750 of file itasc_plugin.cpp.
void itasc_test_constraint (struct Object * ob, struct bConstraint * cons)
Definition at line 1807 of file itasc_plugin.cpp.
References CONSTRAINT_IK_COPYPOSE, CONSTRAINT_IK_DISTANCE, CONSTRAINT_TYPE_KINEMATIC, data, bConstraint::data, if(), NULL, bConstraint::type, and bKinematicConstraint::type.
void itasc_update_param (struct bPose * pose)
Definition at line 1780 of file itasc_plugin.cpp.
References iTaSC::ACT_FEEDBACK, CONSTRAINT_ID_ALL, iTaSC::Solver::DLS_EPSILON, iTaSC::Solver::DLS_LAMBDA_MAX, iTaSC::Solver::DLS_QMAX, IK_Data::first, iTaSC::Armature::ID_JOINT, bPose::ikdata, bPose::ikparam, ITASC_SIMULATION, iTaSC::Scene::MAX_TIMESTEP, iTaSC::Scene::MIN_TIMESTEP, and IK_Scene::next.
Referenced by itasc_initialize_tree().