Blender: PanelType Struct Reference
PanelType Struct Reference
#include <BKE_screen.h>
Public Attributes
struct PanelType * next
struct PanelType * prev
char idname [BKE_ST_MAXNAME]
char label [BKE_ST_MAXNAME]
char context [BKE_ST_MAXNAME]
int space_type
int region_type
int flag
int(* poll)(const struct bContext *, struct PanelType *)
void(* draw_header)(const struct bContext *, struct Panel *)
void(* draw)(const struct bContext *, struct Panel *)
ExtensionRNA ext
Detailed Description
Definition at line 160 of file BKE_screen.h.
Member Data Documentation
char PanelType::context[BKE_ST_MAXNAME]
Definition at line 165 of file BKE_screen.h.
Referenced by ED_region_panels().
void(* PanelType::draw)(const struct bContext *, struct Panel *)
Definition at line 176 of file BKE_screen.h.
Referenced by buttons_context_register(), ED_clip_buttons_register(), ED_clip_tool_props_register(), ED_region_panels(), ED_uvedit_buttons_register(), file_panels_register(), graph_buttons_register(), image_buttons_register(), nla_buttons_register(), node_buttons_register(), view3d_buttons_register(), view3d_tool_props_register(), and view3d_toolshelf_register().
void(* PanelType::draw_header)(const struct bContext *, struct Panel *)
Definition at line 174 of file BKE_screen.h.
Referenced by ED_clip_tool_props_register(), ED_region_panels(), file_panels_register(), and view3d_tool_props_register().
ExtensionRNA PanelType::ext
Definition at line 179 of file BKE_screen.h.
Referenced by spacetype_free().
int PanelType::flag
Definition at line 169 of file BKE_screen.h.
Referenced by buttons_context_register(), ED_clip_buttons_register(), ED_region_panels(), find_highest_panel(), get_panel_header(), get_panel_size_y(), graph_buttons_register(), image_buttons_register(), nla_buttons_register(), node_buttons_register(), ui_draw_aligned_panel(), ui_handler_panel_region(), and uiBeginPanel().
char PanelType::idname[BKE_ST_MAXNAME]
Definition at line 163 of file BKE_screen.h.
Referenced by buttons_context_register(), ED_clip_buttons_register(), ED_clip_tool_props_register(), ED_region_panels(), ED_uvedit_buttons_register(), file_panels_register(), graph_buttons_register(), image_buttons_register(), nla_buttons_register(), node_buttons_register(), uiBeginPanel(), view3d_buttons_register(), view3d_tool_props_register(), and view3d_toolshelf_register().
char PanelType::label[BKE_ST_MAXNAME]
Definition at line 164 of file BKE_screen.h.
Referenced by buttons_context_register(), ED_clip_buttons_register(), ED_clip_tool_props_register(), ED_uvedit_buttons_register(), file_panels_register(), graph_buttons_register(), image_buttons_register(), nla_buttons_register(), node_buttons_register(), uiBeginPanel(), view3d_buttons_register(), view3d_tool_props_register(), and view3d_toolshelf_register().
struct PanelType* PanelType::next
Definition at line 161 of file BKE_screen.h.
Referenced by ED_region_panels(), and spacetype_free().
int(* PanelType::poll)(const struct bContext *, struct PanelType *)
Definition at line 172 of file BKE_screen.h.
Referenced by ED_region_panels(), ED_uvedit_buttons_register(), file_panels_register(), graph_buttons_register(), image_buttons_register(), nla_buttons_register(), node_buttons_register(), and view3d_buttons_register().
struct PanelType * PanelType::prev
Definition at line 161 of file BKE_screen.h.
int PanelType::region_type
Definition at line 167 of file BKE_screen.h.
int PanelType::space_type
Definition at line 166 of file BKE_screen.h.
The documentation for this struct was generated from the following file:
BKE_screen.h