Blender: rna_sensor.c File Reference
rna_sensor.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "RNA_access.h"
#include "rna_internal.h"
#include "DNA_constraint_types.h"
#include "DNA_object_types.h"
#include "DNA_sensor_types.h"
#include "WM_types.h"
Functions
static void rna_def_sensor (BlenderRNA *brna)
static void rna_def_always_sensor (BlenderRNA *brna)
static void rna_def_near_sensor (BlenderRNA *brna)
static void rna_def_mouse_sensor (BlenderRNA *brna)
static void rna_def_touch_sensor (BlenderRNA *brna)
static void rna_def_keyboard_sensor (BlenderRNA *brna)
static void rna_def_property_sensor (BlenderRNA *brna)
static void rna_def_armature_sensor (BlenderRNA *brna)
static void rna_def_actuator_sensor (BlenderRNA *brna)
static void rna_def_delay_sensor (BlenderRNA *brna)
static void rna_def_collision_sensor (BlenderRNA *brna)
static void rna_def_radar_sensor (BlenderRNA *brna)
static void rna_def_random_sensor (BlenderRNA *brna)
static void rna_def_ray_sensor (BlenderRNA *brna)
static void rna_def_message_sensor (BlenderRNA *brna)
static void rna_def_joystick_sensor (BlenderRNA *brna)
void RNA_def_sensor (BlenderRNA *brna)
Variables
EnumPropertyItem sensor_type_items []
Detailed Description
Definition in file rna_sensor.c.
Function Documentation
static void rna_def_actuator_sensor (BlenderRNA * brna) [static]
Definition at line 566 of file rna_sensor.c.
References NC_LOGIC, NULL, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sensor().
static void rna_def_always_sensor (BlenderRNA * brna) [static]
Definition at line 359 of file rna_sensor.c.
References RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sensor().
static void rna_def_armature_sensor (BlenderRNA * brna) [static]
Definition at line 528 of file rna_sensor.c.
References NC_LOGIC, NULL, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), SENS_ARM_LIN_ERROR_ABOVE, SENS_ARM_LIN_ERROR_BELOW, SENS_ARM_ROT_ERROR_ABOVE, SENS_ARM_ROT_ERROR_BELOW, and SENS_ARM_STATE_CHANGED.
Referenced by RNA_def_sensor().
static void rna_def_collision_sensor (BlenderRNA * brna) [static]
Definition at line 612 of file rna_sensor.c.
References NC_LOGIC, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), SENS_COLLISION_MATERIAL, and SENS_COLLISION_PULSE.
Referenced by RNA_def_sensor().
static void rna_def_delay_sensor (BlenderRNA * brna) [static]
Definition at line 582 of file rna_sensor.c.
References NC_LOGIC, NULL, PROP_BOOLEAN, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), and SENS_DELAY_REPEAT.
Referenced by RNA_def_sensor().
static void rna_def_joystick_sensor (BlenderRNA * brna) [static]
Definition at line 794 of file rna_sensor.c.
References event_type_items, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), SENS_JOY_ANY_EVENT, SENS_JOY_AXIS, SENS_JOY_AXIS_SINGLE, SENS_JOY_BUTTON, SENS_JOY_HAT, SENS_JOY_HAT_DOWN, SENS_JOY_HAT_DOWN_LEFT, SENS_JOY_HAT_DOWN_RIGHT, SENS_JOY_HAT_LEFT, SENS_JOY_HAT_RIGHT, SENS_JOY_HAT_UP, SENS_JOY_HAT_UP_LEFT, SENS_JOY_HAT_UP_RIGHT, SENS_JOY_MAXINDEX, SENS_JOY_NEG_X_AXIS, SENS_JOY_NEG_Y_AXIS, SENS_JOY_X_AXIS, and SENS_JOY_Y_AXIS.
Referenced by RNA_def_sensor().
static void rna_def_keyboard_sensor (BlenderRNA * brna) [static]
Definition at line 439 of file rna_sensor.c.
References event_type_items, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sensor().
static void rna_def_message_sensor (BlenderRNA * brna) [static]
Definition at line 778 of file rna_sensor.c.
References NC_LOGIC, NULL, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sensor().
static void rna_def_mouse_sensor (BlenderRNA * brna) [static]
Definition at line 393 of file rna_sensor.c.
References BL_SENS_MOUSE_LEFT_BUTTON, BL_SENS_MOUSE_MIDDLE_BUTTON, BL_SENS_MOUSE_MOUSEOVER, BL_SENS_MOUSE_MOUSEOVER_ANY, BL_SENS_MOUSE_MOVEMENT, BL_SENS_MOUSE_RIGHT_BUTTON, BL_SENS_MOUSE_WHEEL_DOWN, BL_SENS_MOUSE_WHEEL_UP, NC_LOGIC, NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sensor().
static void rna_def_near_sensor (BlenderRNA * brna) [static]
Definition at line 366 of file rna_sensor.c.
References NC_LOGIC, NULL, PROP_FLOAT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sensor().
static void rna_def_property_sensor (BlenderRNA * brna) [static]
Definition at line 485 of file rna_sensor.c.
References NC_LOGIC, NULL, PROP_ENUM, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), SENS_PROP_CHANGED, SENS_PROP_EQUAL, SENS_PROP_INTERVAL, and SENS_PROP_NEQUAL.
Referenced by RNA_def_sensor().
static void rna_def_radar_sensor (BlenderRNA * brna) [static]
Definition at line 655 of file rna_sensor.c.
References NC_LOGIC, NULL, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), SENS_RADAR_NEG_X_AXIS, SENS_RADAR_NEG_Y_AXIS, SENS_RADAR_NEG_Z_AXIS, SENS_RADAR_X_AXIS, SENS_RADAR_Y_AXIS, and SENS_RADAR_Z_AXIS.
Referenced by RNA_def_sensor().
static void rna_def_random_sensor (BlenderRNA * brna) [static]
Definition at line 696 of file rna_sensor.c.
References NC_LOGIC, NULL, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sensor().
static void rna_def_ray_sensor (BlenderRNA * brna) [static]
Definition at line 711 of file rna_sensor.c.
References NC_LOGIC, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), SENS_COLLISION_MATERIAL, SENS_COLLISION_PROPERTY, SENS_RAY_NEG_X_AXIS, SENS_RAY_NEG_Y_AXIS, SENS_RAY_NEG_Z_AXIS, SENS_RAY_X_AXIS, SENS_RAY_XRAY, SENS_RAY_Y_AXIS, and SENS_RAY_Z_AXIS.
Referenced by RNA_def_sensor().
void RNA_def_sensor (BlenderRNA * brna)
Definition at line 894 of file rna_sensor.c.
References rna_def_actuator_sensor(), rna_def_always_sensor(), rna_def_armature_sensor(), rna_def_collision_sensor(), rna_def_delay_sensor(), rna_def_joystick_sensor(), rna_def_keyboard_sensor(), rna_def_message_sensor(), rna_def_mouse_sensor(), rna_def_near_sensor(), rna_def_property_sensor(), rna_def_radar_sensor(), rna_def_random_sensor(), rna_def_ray_sensor(), rna_def_sensor(), and rna_def_touch_sensor().
static void rna_def_sensor (BlenderRNA * brna) [static]
Definition at line 277 of file rna_sensor.c.
References NC_LOGIC, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_INT, PROP_NONE, PROP_STRING, RNA_api_sensor(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SENS_NEG_PULSE_MODE, SENS_PIN, SENS_PULSE_REPEAT, and SENS_SHOW.
Referenced by RNA_def_sensor().
static void rna_def_touch_sensor (BlenderRNA * brna) [static]
Definition at line 420 of file rna_sensor.c.
References NC_LOGIC, NULL, PROP_EDITABLE, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_sensor().
Variable Documentation
EnumPropertyItem sensor_type_items[]
Initial value:
 {
    {SENS_ACTUATOR, "ACTUATOR", 0, "Actuator", ""},
    {SENS_ALWAYS, "ALWAYS", 0, "Always", ""},
    {SENS_ARMATURE, "ARMATURE", 0, "Armature", ""},
    {SENS_COLLISION, "COLLISION", 0, "Collision", ""},
    {SENS_DELAY, "DELAY", 0, "Delay", ""},
    {SENS_JOYSTICK, "JOYSTICK", 0, "Joystick", ""},
    {SENS_KEYBOARD, "KEYBOARD", 0, "Keyboard", ""},
    {SENS_MESSAGE, "MESSAGE", 0, "Message", ""},
    {SENS_MOUSE, "MOUSE", 0, "Mouse", ""},
    {SENS_NEAR, "NEAR", 0, "Near", ""},
    {SENS_PROPERTY, "PROPERTY", 0, "Property", ""},
    {SENS_RADAR, "RADAR", 0, "Radar", ""},
    {SENS_RANDOM, "RANDOM", 0, "Random", ""},
    {SENS_RAY, "RAY", 0, "Ray", ""},
    {SENS_TOUCH, "TOUCH", 0, "Touch", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 43 of file rna_sensor.c.