Blender: OSLRenderServices Class Reference
OSLRenderServices Class Reference
#include <osl_services.h>
Public Member Functions
OSLRenderServices ()
~OSLRenderServices ()
void thread_init (KernelGlobals *kernel_globals)
bool get_matrix (OSL::Matrix44 &result, OSL::TransformationPtr xform, float time)
bool get_inverse_matrix (OSL::Matrix44 &result, OSL::TransformationPtr xform, float time)
bool get_matrix (OSL::Matrix44 &result, ustring from, float time)
bool get_inverse_matrix (OSL::Matrix44 &result, ustring to, float time)
bool get_array_attribute (void *renderstate, bool derivatives, ustring object, TypeDesc type, ustring name, int index, void *val)
bool get_attribute (void *renderstate, bool derivatives, ustring object, TypeDesc type, ustring name, void *val)
bool get_userdata (bool derivatives, ustring name, TypeDesc type, void *renderstate, void *val)
bool has_userdata (ustring name, TypeDesc type, void *renderstate)
void * get_pointcloud_attr_query (ustring *attr_names, TypeDesc *attr_types, int nattrs)
int pointcloud (ustring filename, const OSL::Vec3 &center, float radius, int max_points, void *attr_query, void **attr_outdata)
Detailed Description
Definition at line 46 of file osl_services.h.
Constructor & Destructor Documentation
OSLRenderServices::OSLRenderServices ()
Definition at line 51 of file osl_services.cpp.
References NULL.
OSLRenderServices::~OSLRenderServices ()
Definition at line 56 of file osl_services.cpp.
Member Function Documentation
bool OSLRenderServices::get_array_attribute (void * renderstate, bool derivatives, ustring object, TypeDesc type, ustring name, int index, void * val)
Definition at line 163 of file osl_services.cpp.
bool OSLRenderServices::get_attribute (void * renderstate, bool derivatives, ustring object, TypeDesc type, ustring name, void * val)
Definition at line 233 of file osl_services.cpp.
References ATTR_ELEMENT_VALUE, Attribute, get_mesh_attribute(), get_mesh_attribute_convert(), get_object_attribute(), ShaderData::object, and ShaderData::prim.
bool OSLRenderServices::get_inverse_matrix (OSL::Matrix44 & result, ustring to, float time)
Definition at line 135 of file osl_services.cpp.
References kernel_data, TO_MATRIX44, and transform_transpose().
bool OSLRenderServices::get_inverse_matrix (OSL::Matrix44 & result, OSL::TransformationPtr xform, float time)
Definition at line 86 of file osl_services.cpp.
References ShaderData::object, object_fetch_transform(), OBJECT_INVERSE_TRANSFORM, TO_MATRIX44, and transform_transpose().
bool OSLRenderServices::get_matrix (OSL::Matrix44 & result, ustring from, float time)
Definition at line 107 of file osl_services.cpp.
References kernel_data, TO_MATRIX44, and transform_transpose().
bool OSLRenderServices::get_matrix (OSL::Matrix44 & result, OSL::TransformationPtr xform, float time)
Definition at line 65 of file osl_services.cpp.
References ShaderData::object, object_fetch_transform(), OBJECT_TRANSFORM, TO_MATRIX44, and transform_transpose().
void * OSLRenderServices::get_pointcloud_attr_query (ustring * attr_names, TypeDesc * attr_types, int nattrs)
Definition at line 296 of file osl_services.cpp.
References i, INT, min, and NULL.
bool OSLRenderServices::get_userdata (bool derivatives, ustring name, TypeDesc type, void * renderstate, void * val)
Definition at line 285 of file osl_services.cpp.
bool OSLRenderServices::has_userdata (ustring name, TypeDesc type, void * renderstate)
Definition at line 291 of file osl_services.cpp.
int OSLRenderServices::pointcloud (ustring filename, const OSL::Vec3 & center, float radius, int max_points, void * attr_query, void ** attr_outdata)
Definition at line 350 of file osl_services.cpp.
References i, indices, and sqrtf.
void OSLRenderServices::thread_init (KernelGlobals * kernel_globals)
Definition at line 60 of file osl_services.cpp.
The documentation for this class was generated from the following files:
osl_services.h
osl_services.cpp