Blender: MT_Vector3.inl File Reference
MT_Vector3.inl File Reference
#include "MT_Optimize.h"
Functions
GEN_INLINE MT_Vector3 operator+ (const MT_Vector3 &v1, const MT_Vector3 &v2)
GEN_INLINE MT_Vector3 operator- (const MT_Vector3 &v1, const MT_Vector3 &v2)
GEN_INLINE MT_Vector3 operator- (const MT_Vector3 &v)
GEN_INLINE MT_Vector3 operator* (const MT_Vector3 &v, MT_Scalar s)
GEN_INLINE MT_Vector3 operator* (MT_Scalar s, const MT_Vector3 &v)
GEN_INLINE MT_Vector3 operator/ (const MT_Vector3 &v, MT_Scalar s)
GEN_INLINE MT_Vector3 operator* (const MT_Vector3 &v1, const MT_Vector3 &v2)
GEN_INLINE MT_Scalar MT_dot (const MT_Vector3 &v1, const MT_Vector3 &v2)
GEN_INLINE MT_Scalar MT_length2 (const MT_Vector3 &v)
GEN_INLINE MT_Scalar MT_length (const MT_Vector3 &v)
GEN_INLINE bool MT_fuzzyZero (const MT_Vector3 &v)
GEN_INLINE bool MT_fuzzyEqual (const MT_Vector3 &v1, const MT_Vector3 &v2)
GEN_INLINE MT_Scalar MT_angle (const MT_Vector3 &v1, const MT_Vector3 &v2)
GEN_INLINE MT_Vector3 MT_cross (const MT_Vector3 &v1, const MT_Vector3 &v2)
GEN_INLINE MT_Scalar MT_triple (const MT_Vector3 &v1, const MT_Vector3 &v2, const MT_Vector3 &v3)
Function Documentation
GEN_INLINE MT_Scalar MT_angle (const MT_Vector3 & v1, const MT_Vector3 & v2)
Definition at line 130 of file MT_Vector3.inl.
References MT_Vector3::angle().
GEN_INLINE MT_Vector3 MT_cross (const MT_Vector3 & v1, const MT_Vector3 & v2)
Definition at line 131 of file MT_Vector3.inl.
References MT_Vector3::cross().
GEN_INLINE MT_Scalar MT_dot (const MT_Vector3 & v1, const MT_Vector3 & v2)
Definition at line 118 of file MT_Vector3.inl.
References MT_Vector3::dot().
GEN_INLINE bool MT_fuzzyEqual (const MT_Vector3 & v1, const MT_Vector3 & v2)
Definition at line 126 of file MT_Vector3.inl.
References MT_fuzzyZero().
GEN_INLINE bool MT_fuzzyZero (const MT_Vector3 & v)
Definition at line 125 of file MT_Vector3.inl.
References MT_Vector3::fuzzyZero().
GEN_INLINE MT_Scalar MT_length (const MT_Vector3 & v)
Definition at line 123 of file MT_Vector3.inl.
References MT_Vector3::length().
GEN_INLINE MT_Scalar MT_length2 (const MT_Vector3 & v)
Definition at line 122 of file MT_Vector3.inl.
References MT_Vector3::length2().
GEN_INLINE MT_Scalar MT_triple (const MT_Vector3 & v1, const MT_Vector3 & v2, const MT_Vector3 & v3)
Definition at line 132 of file MT_Vector3.inl.
References MT_Vector3::triple().
GEN_INLINE MT_Vector3 operator* (const MT_Vector3 & v, MT_Scalar s)
Definition at line 35 of file MT_Vector3.inl.
GEN_INLINE MT_Vector3 operator* (MT_Scalar s, const MT_Vector3 & v)
Definition at line 39 of file MT_Vector3.inl.
GEN_INLINE MT_Vector3 operator* (const MT_Vector3 & v1, const MT_Vector3 & v2)
Definition at line 46 of file MT_Vector3.inl.
GEN_INLINE MT_Vector3 operator+ (const MT_Vector3 & v1, const MT_Vector3 & v2)
Definition at line 23 of file MT_Vector3.inl.
GEN_INLINE MT_Vector3 operator- (const MT_Vector3 & v1, const MT_Vector3 & v2)
Definition at line 27 of file MT_Vector3.inl.
GEN_INLINE MT_Vector3 operator- (const MT_Vector3 & v)
Definition at line 31 of file MT_Vector3.inl.
GEN_INLINE MT_Vector3 operator/ (const MT_Vector3 & v, MT_Scalar s)
Definition at line 41 of file MT_Vector3.inl.
References MT_assert, and MT_fuzzyZero().