Blender: BKE_subsurf.h File Reference
BKE_subsurf.h File Reference
blenkernel
#include "BKE_DerivedMesh.h"
Classes
struct CCGDerivedMesh
Typedefs
typedef enum MultiresModifiedFlags MultiresModifiedFlags
typedef struct CCGDerivedMesh CCGDerivedMesh
Enumerations
enum MultiresModifiedFlags { MULTIRES_COORDS_MODIFIED = 1, MULTIRES_HIDDEN_MODIFIED = 2 }
Functions
struct DerivedMesh * subsurf_make_derived_from_derived (struct DerivedMesh *dm, struct SubsurfModifierData *smd, int useRenderParams, float(*vertCos)[3], int isFinalCalc, int forEditMode, int inEditMode)
void subsurf_calculate_limit_positions (struct Mesh *me, float(*positions_r)[3])
int ccg_gridsize (int level)
int ccg_factor (int low_level, int high_level)
void subsurf_copy_grid_hidden (struct DerivedMesh *dm, const struct MPoly *mpoly, struct MVert *mvert, const struct MDisps *mdisps)
Detailed Description
Definition in file BKE_subsurf.h.
Typedef Documentation
typedef struct CCGDerivedMesh CCGDerivedMesh
typedef enum MultiresModifiedFlags MultiresModifiedFlags
Enumeration Type Documentation
enum MultiresModifiedFlags
Enumerator:
MULTIRES_COORDS_MODIFIED
MULTIRES_HIDDEN_MODIFIED
Definition at line 79 of file BKE_subsurf.h.
Function Documentation
int ccg_factor (int low_level, int high_level)
Definition at line 242 of file CCGSubSurf.c.
References BLI_assert.
Referenced by multires_mdisps_downsample_hidden(), multires_mdisps_upsample_hidden(), and subsurf_copy_grid_hidden().
int ccg_gridsize (int level)
Definition at line 234 of file CCGSubSurf.c.
References BLI_assert.
Referenced by _face_getIECo(), _face_getIENo(), _face_getIFCo(), _face_getIFCoEdge(), _face_getIFNo(), _face_new(), ccgSubSurf__calcSubdivLevel(), ccgSubSurf__calcVertNormals(), ccgSubSurf_getFaceUserData(), ccgSubSurf_getGridLevelSize(), ccgSubSurf_getNumFinalEdges(), ccgSubSurf_getNumFinalFaces(), ccgSubSurf_getNumFinalVerts(), ccgSubSurf_stitchFaces(), ccgSubSurf_updateFromFaces(), ccgSubSurf_updateToFaces(), multires_mdisps_downsample_hidden(), multires_mdisps_initialize_hidden(), multires_mdisps_upsample_hidden(), and subsurf_copy_grid_hidden().
void subsurf_calculate_limit_positions (struct Mesh * me, float(*) positions_r[3])
Definition at line 3453 of file subsurf_ccg.c.
References _getSubSurf(), add_v3_v3(), add_v3_v3v3(), CCG_USE_ARENA, ccgSubSurf_free(), ccgSubSurf_getEdgeData(), ccgSubSurf_getFaceCenterData(), ccgSubSurf_getVertData(), ccgSubSurf_getVertEdge(), ccgSubSurf_getVertFace(), ccgSubSurf_getVertIterator(), ccgSubSurf_getVertNumEdges(), ccgSubSurf_getVertNumFaces(), ccgSubSurf_getVertVertHandle(), ccgVertIterator_free(), ccgVertIterator_getCurrent(), ccgVertIterator_isStopped(), ccgVertIterator_next(), CDDM_from_mesh(), co, GET_INT_FROM_POINTER, i, mul_v3_fl(), N, NULL, DerivedMesh::release, and ss_sync_from_derivedmesh().
Referenced by add_verts_to_dgroups().
void subsurf_copy_grid_hidden (struct DerivedMesh * dm, const struct MPoly * mpoly, struct MVert * mvert, const struct MDisps * mdisps)
Referenced by applyModifier().
struct DerivedMesh* subsurf_make_derived_from_derived (struct DerivedMesh * dm, struct SubsurfModifierData * smd, int useRenderParams, float(*) vertCos[3], int isFinalCalc, int forEditMode, int inEditMode) [read]
Definition at line 3363 of file subsurf_ccg.c.
References _getSubSurf(), CCG_CALC_NORMALS, CCG_USE_AGING, CCG_USE_ARENA, ccgSubSurf_free(), SubsurfModifierData::emCache, eSubsurfModifierFlag_ControlEdges, eSubsurfModifierFlag_DebugIncr, eSubsurfModifierFlag_Incremental, eSubsurfModifierFlag_SubsurfUv, SubsurfModifierData::flags, CCGDerivedMesh::freeSS, get_render_subsurf_level(), getCCGDerivedMesh(), SubsurfModifierData::levels, SubsurfModifierData::mCache, ME_SIMPLE_SUBSURF, SubsurfModifierData::modifier, NULL, Scene::r, SubsurfModifierData::renderLevels, ModifierData::scene, ss_sync_from_derivedmesh(), and SubsurfModifierData::subdivType.
Referenced by applyModifier(), applyModifierEM(), construct_param_handle_subsurfed(), init_heights_data(), shrinkwrapModifier_deform(), and subsurf_dm_create_local().