Blender: node_composite_value.c File Reference
node_composite_value.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void node_composit_init_value (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static void node_composit_exec_value (void *UNUSED(data), bNode *node, bNodeStack **UNUSED(in), bNodeStack **out)
void register_node_type_cmp_value (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_value_out []
Detailed Description
Definition in file node_composite_value.c.
Function Documentation
static void node_composit_exec_value (void * UNUSEDdata, bNode * node, bNodeStack ** UNUSEDin, bNodeStack ** out) [static]
Definition at line 52 of file node_composite_value.c.
References bNodeSocket::default_value, ListBase::first, bNode::outputs, and bNodeStack::vec.
Referenced by register_node_type_cmp_value().
static void node_composit_init_value (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 42 of file node_composite_value.c.
References bNodeSocket::default_value, ListBase::first, FLT_MAX, bNodeSocketValueFloat::max, bNodeSocketValueFloat::min, bNode::outputs, and bNodeSocketValueFloat::value.
Referenced by register_node_type_cmp_value().
void register_node_type_cmp_value (bNodeTreeType * ttype)
Definition at line 60 of file node_composite_value.c.
References CMP_NODE_VALUE, NODE_CLASS_INPUT, node_composit_exec_value(), node_composit_init_value(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_value_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "Value", 0.0f, 0.0f, 0.0f, 0.0f, -FLT_MAX, FLT_MAX},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_composite_value.c.