Blender: ShaderEnum Class Reference
ShaderEnum Class Reference
#include <graph.h>
Public Member Functions
bool empty () const
void insert (const char *x, int y)
bool exists (ustring x)
bool exists (int y)
int operator[] (const char *x)
int operator[] (ustring x)
ustring operator[] (int y)
Protected Attributes
map< ustring, int > left
map< int, ustring > right
Detailed Description
Definition at line 70 of file graph.h.
Member Function Documentation
bool ShaderEnum::empty () const [inline]
Definition at line 72 of file graph.h.
References left.
bool ShaderEnum::exists (int y) [inline]
Definition at line 79 of file graph.h.
References right.
bool ShaderEnum::exists (ustring x) [inline]
Definition at line 78 of file graph.h.
References left.
Referenced by xml_read_enum().
void ShaderEnum::insert (const char * x, int y) [inline]
Definition at line 73 of file graph.h.
References left, and right.
Referenced by color_space_init(), glass_distribution_init(), glossy_distribution_init(), gradient_type_init(), math_type_init(), mix_type_init(), musgrave_type_init(), projection_init(), vector_math_type_init(), voronoi_coloring_init(), and wave_type_init().
ustring ShaderEnum::operator[] (int y) [inline]
Definition at line 83 of file graph.h.
References right.
int ShaderEnum::operator[] (ustring x) [inline]
Definition at line 82 of file graph.h.
References left.
int ShaderEnum::operator[] (const char * x) [inline]
Definition at line 81 of file graph.h.
References left.
Member Data Documentation
map<ustring, int> ShaderEnum::left [protected]
Definition at line 86 of file graph.h.
Referenced by empty(), exists(), insert(), and operator[]().
map<int, ustring> ShaderEnum::right [protected]
Definition at line 87 of file graph.h.
Referenced by exists(), insert(), and operator[]().
The documentation for this class was generated from the following file:
graph.h