Blender: PHY_IPhysicsEnvironment Class Reference
PHY_IPhysicsEnvironment Class Reference
#include <PHY_IPhysicsEnvironment.h>
Public Member Functions
virtual ~PHY_IPhysicsEnvironment ()
virtual void beginFrame ()=0
virtual void endFrame ()=0
virtual bool proceedDeltaTime (double curTime, float timeStep, float interval)=0
Perform an integration step of duration 'timeStep'.
virtual void debugDrawWorld ()
draw debug lines (make sure to call this during the render phase, otherwise lines are not drawn properly)
virtual void setFixedTimeStep (bool useFixedTimeStep, float fixedTimeStep)=0
virtual float getFixedTimeStep ()=0
virtual void setDebugMode (int debugMode)
setDebugMode is used to support several ways of debug lines, contact point visualization
virtual void setNumIterations (int numIter)
setNumIterations set the number of iterations for iterative solvers
virtual void setNumTimeSubSteps (int numTimeSubSteps)
setNumTimeSubSteps set the number of divisions of the timestep. Tradeoff quality versus performance.
virtual void setDeactivationTime (float dTime)
setDeactivationTime sets the minimum time that an objects has to stay within the velocity tresholds until it gets fully deactivated
virtual void setDeactivationLinearTreshold (float linTresh)
setDeactivationLinearTreshold sets the linear velocity treshold, see setDeactivationTime
virtual void setDeactivationAngularTreshold (float angTresh)
setDeactivationAngularTreshold sets the angular velocity treshold, see setDeactivationTime
virtual void setContactBreakingTreshold (float contactBreakingTreshold)
setContactBreakingTreshold sets tresholds to do with contact point management
virtual void setCcdMode (int ccdMode)
continuous collision detection mode, very experimental for Bullet
virtual void setSolverSorConstant (float sor)
successive overrelaxation constant, in case PSOR is used, values in between 1 and 2 guarantee converging behavior
virtual void setSolverType (int solverType)
setSolverType, internal setting, chooses solvertype, PSOR, Dantzig, impulse based, penalty based
virtual void setSolverTau (float tau)
setTau sets the spring constant of a penalty based solver
virtual void setSolverDamping (float damping)
setDamping sets the damper constant of a penalty based solver
virtual void setLinearAirDamping (float damping)
linear air damping for rigidbodies
virtual void setUseEpa (bool epa)
penetrationdepth setting
virtual void setGravity (float x, float y, float z)=0
virtual int createConstraint (class PHY_IPhysicsController *ctrl, class PHY_IPhysicsController *ctrl2, PHY_ConstraintType type, float pivotX, float pivotY, float pivotZ, float axis0X, float axis0Y, float axis0Z, float axis1X=0, float axis1Y=0, float axis1Z=0, float axis2X=0, float axis2Y=0, float axis2Z=0, int flag=0)=0
virtual void removeConstraint (int constraintid)=0
virtual float getAppliedImpulse (int constraintid)
virtual PHY_IVehicle * getVehicleConstraint (int constraintId)=0
virtual PHY_IPhysicsController * rayTest (PHY_IRayCastFilterCallback &filterCallback, float fromX, float fromY, float fromZ, float toX, float toY, float toZ)=0
virtual bool cullingTest (PHY_CullingCallback callback, void *userData, PHY__Vector4 *planeNormals, int planeNumber, int occlusionRes)=0
virtual void addSensor (PHY_IPhysicsController *ctrl)=0
virtual void removeSensor (PHY_IPhysicsController *ctrl)=0
virtual void addTouchCallback (int response_class, PHY_ResponseCallback callback, void *user)=0
virtual bool requestCollisionCallback (PHY_IPhysicsController *ctrl)=0
virtual bool removeCollisionCallback (PHY_IPhysicsController *ctrl)=0
virtual PHY_IPhysicsController * CreateSphereController (float radius, const PHY__Vector3 &position)=0
virtual PHY_IPhysicsController * CreateConeController (float coneradius, float coneheight)=0
virtual void setConstraintParam (int constraintId, int param, float value, float value1)=0
virtual float getConstraintParam (int constraintId, int param)=0
virtual void exportFile (const char *filename)
Detailed Description
Physics Environment takes care of stepping the simulation and is a container for physics entities (rigidbodies,constraints, materials etc.) A derived class may be able to 'construct' entities by loading and/or converting
Definition at line 102 of file PHY_IPhysicsEnvironment.h.
Constructor & Destructor Documentation
PHY_IPhysicsEnvironment::~PHY_IPhysicsEnvironment () [virtual]
Physics Environment takes care of stepping the simulation and is a container for physics entities (rigidbodies,constraints, materials etc.) A derived class may be able to 'construct' entities by loading and/or converting
Definition at line 42 of file PHY_IPhysicsEnvironment.cpp.
Member Function Documentation
virtual void PHY_IPhysicsEnvironment::addSensor (PHY_IPhysicsController * ctrl) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by KX_TouchSensor::RegisterSumo().
virtual void PHY_IPhysicsEnvironment::addTouchCallback (int response_class, PHY_ResponseCallback callback, void * user) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by KX_TouchEventManager::KX_TouchEventManager().
virtual void PHY_IPhysicsEnvironment::beginFrame () [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by KX_KetsjiEngine::NextFrame().
virtual PHY_IPhysicsController* PHY_IPhysicsEnvironment::CreateConeController (float coneradius, float coneheight) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by BL_ConvertSensors().
virtual int PHY_IPhysicsEnvironment::createConstraint (class PHY_IPhysicsController * ctrl, class PHY_IPhysicsController * ctrl2, PHY_ConstraintType type, float pivotX, float pivotY, float pivotZ, float axis0X, float axis0Y, float axis0Z, float axis1X = 0, float axis1Y = 0, float axis1Z = 0, float axis2X = 0, float axis2Y = 0, float axis2Z = 0, int flag = 0) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by BL_ConvertBlenderObjects().
virtual PHY_IPhysicsController* PHY_IPhysicsEnvironment::CreateSphereController (float radius, const PHY__Vector3 & position) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by BL_ConvertSensors().
virtual bool PHY_IPhysicsEnvironment::cullingTest (PHY_CullingCallback callback, void * userData, PHY__Vector4 * planeNormals, int planeNumber, int occlusionRes) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by KX_Scene::CalculateVisibleMeshes().
virtual void PHY_IPhysicsEnvironment::debugDrawWorld () [inline, virtual]
draw debug lines (make sure to call this during the render phase, otherwise lines are not drawn properly)
Reimplemented in CcdPhysicsEnvironment.
Definition at line 111 of file PHY_IPhysicsEnvironment.h.
virtual void PHY_IPhysicsEnvironment::endFrame () [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by KX_KetsjiEngine::NextFrame().
virtual void PHY_IPhysicsEnvironment::exportFile (const char * filename) [inline, virtual]
Reimplemented in CcdPhysicsEnvironment.
Definition at line 181 of file PHY_IPhysicsEnvironment.h.
virtual float PHY_IPhysicsEnvironment::getAppliedImpulse (int constraintid) [inline, virtual]
Reimplemented in CcdPhysicsEnvironment.
Definition at line 154 of file PHY_IPhysicsEnvironment.h.
virtual float PHY_IPhysicsEnvironment::getConstraintParam (int constraintId, int param) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
virtual float PHY_IPhysicsEnvironment::getFixedTimeStep () [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
virtual PHY_IVehicle* PHY_IPhysicsEnvironment::getVehicleConstraint (int constraintId) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
virtual bool PHY_IPhysicsEnvironment::proceedDeltaTime (double curTime, float timeStep, float interval) [pure virtual]
Perform an integration step of duration 'timeStep'.
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by KX_KetsjiEngine::NextFrame().
virtual PHY_IPhysicsController* PHY_IPhysicsEnvironment::rayTest (PHY_IRayCastFilterCallback & filterCallback, float fromX, float fromY, float fromZ, float toX, float toY, float toZ) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by KX_RayCast::RayTest().
virtual bool PHY_IPhysicsEnvironment::removeCollisionCallback (PHY_IPhysicsController * ctrl) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by KX_TouchSensor::UnregisterSumo().
virtual void PHY_IPhysicsEnvironment::removeConstraint (int constraintid) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
virtual void PHY_IPhysicsEnvironment::removeSensor (PHY_IPhysicsController * ctrl) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by KX_TouchSensor::UnregisterSumo().
virtual bool PHY_IPhysicsEnvironment::requestCollisionCallback (PHY_IPhysicsController * ctrl) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by KX_TouchSensor::RegisterSumo().
virtual void PHY_IPhysicsEnvironment::setCcdMode (int ccdMode) [inline, virtual]
continuous collision detection mode, very experimental for Bullet
Reimplemented in CcdPhysicsEnvironment.
Definition at line 131 of file PHY_IPhysicsEnvironment.h.
virtual void PHY_IPhysicsEnvironment::setConstraintParam (int constraintId, int param, float value, float value1) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by BL_ConvertBlenderObjects().
virtual void PHY_IPhysicsEnvironment::setContactBreakingTreshold (float contactBreakingTreshold) [inline, virtual]
setContactBreakingTreshold sets tresholds to do with contact point management
Reimplemented in CcdPhysicsEnvironment.
Definition at line 129 of file PHY_IPhysicsEnvironment.h.
virtual void PHY_IPhysicsEnvironment::setDeactivationAngularTreshold (float angTresh) [inline, virtual]
setDeactivationAngularTreshold sets the angular velocity treshold, see setDeactivationTime
Reimplemented in CcdPhysicsEnvironment.
Definition at line 127 of file PHY_IPhysicsEnvironment.h.
virtual void PHY_IPhysicsEnvironment::setDeactivationLinearTreshold (float linTresh) [inline, virtual]
setDeactivationLinearTreshold sets the linear velocity treshold, see setDeactivationTime
Reimplemented in CcdPhysicsEnvironment.
Definition at line 125 of file PHY_IPhysicsEnvironment.h.
virtual void PHY_IPhysicsEnvironment::setDeactivationTime (float dTime) [inline, virtual]
setDeactivationTime sets the minimum time that an objects has to stay within the velocity tresholds until it gets fully deactivated
Reimplemented in CcdPhysicsEnvironment.
Definition at line 123 of file PHY_IPhysicsEnvironment.h.
virtual void PHY_IPhysicsEnvironment::setDebugMode (int debugMode) [inline, virtual]
setDebugMode is used to support several ways of debug lines, contact point visualization
Reimplemented in CcdPhysicsEnvironment.
Definition at line 117 of file PHY_IPhysicsEnvironment.h.
virtual void PHY_IPhysicsEnvironment::setFixedTimeStep (bool useFixedTimeStep, float fixedTimeStep) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
virtual void PHY_IPhysicsEnvironment::setGravity (float x, float y, float z) [pure virtual]
Implemented in CcdPhysicsEnvironment, and DummyPhysicsEnvironment.
Referenced by KX_Scene::SetGravity().
virtual void PHY_IPhysicsEnvironment::setLinearAirDamping (float damping) [inline, virtual]
linear air damping for rigidbodies
Reimplemented in CcdPhysicsEnvironment.
Definition at line 141 of file PHY_IPhysicsEnvironment.h.
virtual void PHY_IPhysicsEnvironment::setNumIterations (int numIter) [inline, virtual]
setNumIterations set the number of iterations for iterative solvers
Reimplemented in CcdPhysicsEnvironment.
Definition at line 119 of file PHY_IPhysicsEnvironment.h.
virtual void PHY_IPhysicsEnvironment::setNumTimeSubSteps (int numTimeSubSteps) [inline, virtual]
setNumTimeSubSteps set the number of divisions of the timestep. Tradeoff quality versus performance.
Reimplemented in CcdPhysicsEnvironment.
Definition at line 121 of file PHY_IPhysicsEnvironment.h.
Referenced by BL_ConvertBlenderObjects().
virtual void PHY_IPhysicsEnvironment::setSolverDamping (float damping) [inline, virtual]
setDamping sets the damper constant of a penalty based solver
Reimplemented in CcdPhysicsEnvironment.
Definition at line 139 of file PHY_IPhysicsEnvironment.h.
virtual void PHY_IPhysicsEnvironment::setSolverSorConstant (float sor) [inline, virtual]
successive overrelaxation constant, in case PSOR is used, values in between 1 and 2 guarantee converging behavior
Reimplemented in CcdPhysicsEnvironment.
Definition at line 133 of file PHY_IPhysicsEnvironment.h.
virtual void PHY_IPhysicsEnvironment::setSolverTau (float tau) [inline, virtual]
setTau sets the spring constant of a penalty based solver
Reimplemented in CcdPhysicsEnvironment.
Definition at line 137 of file PHY_IPhysicsEnvironment.h.
virtual void PHY_IPhysicsEnvironment::setSolverType (int solverType) [inline, virtual]
setSolverType, internal setting, chooses solvertype, PSOR, Dantzig, impulse based, penalty based
Reimplemented in CcdPhysicsEnvironment.
Definition at line 135 of file PHY_IPhysicsEnvironment.h.
virtual void PHY_IPhysicsEnvironment::setUseEpa (bool epa) [inline, virtual]
penetrationdepth setting
Reimplemented in CcdPhysicsEnvironment.
Definition at line 143 of file PHY_IPhysicsEnvironment.h.
The documentation for this class was generated from the following files:
PHY_IPhysicsEnvironment.h
PHY_IPhysicsEnvironment.cpp