Blender: SCA_MouseManager Class Reference
SCA_MouseManager Class Reference
#include <SCA_MouseManager.h>
Public Member Functions
SCA_MouseManager (class SCA_LogicManager *logicmgr, class SCA_IInputDevice *mousedev, class RAS_ICanvas *canvas)
virtual ~SCA_MouseManager ()
bool IsPressed (SCA_IInputDevice::KX_EnumInputs inputcode)
virtual void NextFrame ()
SCA_IInputDevice * GetInputDevice ()
Detailed Description
Definition at line 48 of file SCA_MouseManager.h.
Constructor & Destructor Documentation
SCA_MouseManager::SCA_MouseManager (class SCA_LogicManager * logicmgr, class SCA_IInputDevice * mousedev, class RAS_ICanvas * canvas)
Definition at line 50 of file SCA_MouseManager.cpp.
SCA_MouseManager::~SCA_MouseManager () [virtual]
Definition at line 63 of file SCA_MouseManager.cpp.
Member Function Documentation
SCA_IInputDevice * SCA_MouseManager::GetInputDevice ()
Definition at line 69 of file SCA_MouseManager.cpp.
bool SCA_MouseManager::IsPressed (SCA_IInputDevice::KX_EnumInputs inputcode)
Checks whether a mouse button is depressed. Ignores requests on non- mouse related events. Can also flag mouse movement.
Definition at line 105 of file SCA_MouseManager.cpp.
References SCA_IInputDevice::IsPressed().
void SCA_MouseManager::NextFrame () [virtual]
Reimplemented from SCA_EventManager.
Definition at line 76 of file SCA_MouseManager.cpp.
References SCA_ISensor::Activate(), SG_DList::iterator< T >::begin(), SG_DList::iterator< T >::end(), SCA_IInputDevice::GetEventValue(), RAS_ICanvas::GetMouseX(), RAS_ICanvas::GetMouseY(), SCA_ISensor::IsSuspended(), SCA_IInputDevice::KX_MOUSEX, SCA_IInputDevice::KX_MOUSEY, SCA_InputEvent::m_eventval, SCA_EventManager::m_logicmgr, SCA_EventManager::m_sensors, SCA_MouseSensor::setX(), and SCA_MouseSensor::setY().
The documentation for this class was generated from the following files:
SCA_MouseManager.h
SCA_MouseManager.cpp