Blender: BlockATI1 Struct Reference
BlockATI1 Struct Reference
ATI1 block.
#include <BlockDXT.h>
Public Member Functions
void decodeBlock (ColorBlock *block) const
Decode ATI1 block.
void flip4 ()
Flip ATI1 block vertically.
void flip2 ()
Flip half ATI1 block vertically.
Public Attributes
AlphaBlockDXT5 alpha
Detailed Description
ATI1 block.
Definition at line 224 of file BlockDXT.h.
Member Function Documentation
void BlockATI1::decodeBlock (ColorBlock * block) const
Decode ATI1 block.
Definition at line 491 of file BlockDXT.cpp.
References Color32::a, alpha, Color32::b, ColorBlock::color(), AlphaBlockDXT5::evaluatePalette(), Color32::g, i, AlphaBlockDXT5::indices(), and Color32::r.
void BlockATI1::flip2 ()
Flip half ATI1 block vertically.
Definition at line 513 of file BlockDXT.cpp.
References alpha, and AlphaBlockDXT5::flip2().
void BlockATI1::flip4 ()
Flip ATI1 block vertically.
Definition at line 507 of file BlockDXT.cpp.
References alpha, and AlphaBlockDXT5::flip4().
Member Data Documentation
AlphaBlockDXT5 BlockATI1::alpha
Definition at line 226 of file BlockDXT.h.
Referenced by decodeBlock(), flip2(), flip4(), and mem_read().
The documentation for this struct was generated from the following files:
BlockDXT.h
BlockDXT.cpp