Blender: rna_speaker.c File Reference
rna_speaker.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_speaker_types.h"
#include "DNA_sound_types.h"
Functions
static void rna_def_speaker (BlenderRNA *brna)
void RNA_def_speaker (BlenderRNA *brna)
Detailed Description
Definition in file rna_speaker.c.
Function Documentation
static void rna_def_speaker (BlenderRNA * brna) [static]
Definition at line 51 of file rna_speaker.c.
References FLT_MAX, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_EDITABLE, PROP_FLOAT, PROP_NONE, PROP_POINTER, rna_def_animdata_common(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), SPK_MUTED, and SPK_RELATIVE.
Referenced by RNA_def_speaker().
void RNA_def_speaker (BlenderRNA * brna)
Definition at line 169 of file rna_speaker.c.
References rna_def_speaker().