Blender: rna_fcurve.c File Reference
rna_fcurve.c File Reference
RNA
#include <stdlib.h>
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_anim_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BKE_action.h"
#include "WM_types.h"
#include "ED_keyframing.h"
#include "ED_keyframes_edit.h"
Functions
static void rna_def_fmodifier_generator (BlenderRNA *brna)
static void rna_def_fmodifier_function_generator (BlenderRNA *brna)
static void rna_def_fmodifier_envelope_ctrl (BlenderRNA *brna)
static void rna_def_fmodifier_envelope (BlenderRNA *brna)
static void rna_def_fmodifier_cycles (BlenderRNA *brna)
static void rna_def_fmodifier_python (BlenderRNA *brna)
static void rna_def_fmodifier_limits (BlenderRNA *brna)
static void rna_def_fmodifier_noise (BlenderRNA *brna)
static void rna_def_fmodifier_stepped (BlenderRNA *brna)
static void rna_def_fmodifier (BlenderRNA *brna)
static void rna_def_drivertarget (BlenderRNA *brna)
static void rna_def_drivervar (BlenderRNA *brna)
static void rna_def_channeldriver_variables (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_channeldriver (BlenderRNA *brna)
static void rna_def_fpoint (BlenderRNA *brna)
static void rna_def_fkeyframe (BlenderRNA *brna)
static void rna_def_fcurve_modifiers (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_fcurve_keyframe_points (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_fcurve (BlenderRNA *brna)
void RNA_def_fcurve (BlenderRNA *brna)
Variables
EnumPropertyItem fmodifier_type_items []
EnumPropertyItem beztriple_keyframe_type_items []
Detailed Description
Definition in file rna_fcurve.c.
Function Documentation
static void rna_def_channeldriver (BlenderRNA * brna) [static]
Definition at line 1262 of file rna_fcurve.c.
References DRIVER_FLAG_INVALID, DRIVER_FLAG_SHOWDEBUG, DRIVER_TYPE_AVERAGE, DRIVER_TYPE_MAX, DRIVER_TYPE_MIN, DRIVER_TYPE_PYTHON, DRIVER_TYPE_SUM, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_NONE, PROP_STRING, RNA_api_drivers(), rna_def_channeldriver_variables(), RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_sdna(), RNA_def_property_enum_items(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
static void rna_def_channeldriver_variables (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1232 of file rna_fcurve.c.
References FUNC_USE_REPORTS, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by rna_def_channeldriver().
static void rna_def_drivertarget (BlenderRNA * brna) [static]
Definition at line 1113 of file rna_fcurve.c.
References DTAR_FLAG_LOCAL_CONSTS, DTAR_FLAG_LOCALSPACE, DTAR_TRANSCHAN_LOCX, DTAR_TRANSCHAN_LOCY, DTAR_TRANSCHAN_LOCZ, DTAR_TRANSCHAN_ROTX, DTAR_TRANSCHAN_ROTY, DTAR_TRANSCHAN_ROTZ, DTAR_TRANSCHAN_SCALEX, DTAR_TRANSCHAN_SCALEY, DTAR_TRANSCHAN_SCALEZ, ID_OB, id_type_items, NULL, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_editable_func(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_default(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
static void rna_def_drivervar (BlenderRNA * brna) [static]
Definition at line 1188 of file rna_fcurve.c.
References DVAR_TYPE_LOC_DIFF, DVAR_TYPE_ROT_DIFF, DVAR_TYPE_SINGLE_PROP, DVAR_TYPE_TRANSFORM_CHAN, NULL, PROP_COLLECTION, PROP_ENUM, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_collection_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
static void rna_def_fcurve (BlenderRNA * brna) [static]
Definition at line 1502 of file rna_fcurve.c.
References FCURVE_COLOR_AUTO_RAINBOW, FCURVE_COLOR_AUTO_RGB, FCURVE_COLOR_CUSTOM, FCURVE_DISABLED, FCURVE_EXTRAPOLATE_CONSTANT, FCURVE_EXTRAPOLATE_LINEAR, FCURVE_MUTED, FCURVE_PROTECTED, FCURVE_SELECTED, FCURVE_VISIBLE, FLT_MAX, NA_EDITED, NA_SELECTED, NC_ANIMATION, NC_SPACE, ND_ANIMCHAN, ND_KEYFRAME, ND_KEYFRAME_PROP, ND_SPACE_GRAPH, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_COLOR, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_REQUIRED, PROP_STRING, PROP_THICK_WRAP, rna_def_fcurve_keyframe_points(), rna_def_fcurve_modifiers(), RNA_def_float(), RNA_def_float_vector(), RNA_def_function(), RNA_def_function_output(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
void RNA_def_fcurve (BlenderRNA * brna)
Definition at line 1637 of file rna_fcurve.c.
References rna_def_channeldriver(), rna_def_drivertarget(), rna_def_drivervar(), rna_def_fcurve(), rna_def_fkeyframe(), rna_def_fmodifier(), rna_def_fmodifier_cycles(), rna_def_fmodifier_envelope(), rna_def_fmodifier_envelope_ctrl(), rna_def_fmodifier_function_generator(), rna_def_fmodifier_generator(), rna_def_fmodifier_limits(), rna_def_fmodifier_noise(), rna_def_fmodifier_python(), rna_def_fmodifier_stepped(), and rna_def_fpoint().
static void rna_def_fcurve_keyframe_points (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1457 of file rna_fcurve.c.
References FLT_MAX, FUNC_USE_REPORTS, INSERTKEY_FAST, INSERTKEY_NEEDED, INSERTKEY_REPLACE, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum_flag(), RNA_def_float(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by rna_def_fcurve().
static void rna_def_fcurve_modifiers (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1415 of file rna_fcurve.c.
References FUNC_USE_REPORTS, NULL, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REQUIRED, RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by rna_def_fcurve().
static void rna_def_fkeyframe (BlenderRNA * brna) [static]
Definition at line 1343 of file rna_fcurve.c.
References beztriple_interpolation_mode_items, keyframe_handle_type_items, NA_EDITED, NA_SELECTED, NC_ANIMATION, ND_KEYFRAME, ND_KEYFRAME_PROP, NULL, PROP_BOOLEAN, PROP_COORDS, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_funcs(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
static void rna_def_fmodifier (BlenderRNA * brna) [static]
Definition at line 1011 of file rna_fcurve.c.
References FMODIFIER_FLAG_ACTIVE, FMODIFIER_FLAG_DISABLED, FMODIFIER_FLAG_EXPANDED, FMODIFIER_FLAG_MUTED, FMODIFIER_FLAG_RANGERESTRICT, FMODIFIER_FLAG_USEINFLUENCE, NC_ANIMATION, ND_KEYFRAME_PROP, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_float_default(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_refine_func(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
static void rna_def_fmodifier_cycles (BlenderRNA * brna) [static]
Definition at line 798 of file rna_fcurve.c.
References FCM_EXTRAPOLATE_CYCLIC, FCM_EXTRAPOLATE_CYCLIC_OFFSET, FCM_EXTRAPOLATE_MIRROR, FCM_EXTRAPOLATE_NONE, NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, PROP_ENUM, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
static void rna_def_fmodifier_envelope (BlenderRNA * brna) [static]
Definition at line 764 of file rna_fcurve.c.
References NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, PROP_COLLECTION, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_collection_sdna(), RNA_def_property_float_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
static void rna_def_fmodifier_envelope_ctrl (BlenderRNA * brna) [static]
Definition at line 731 of file rna_fcurve.c.
References NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, PROP_FLOAT, PROP_NONE, PROP_TIME, RNA_def_property(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
static void rna_def_fmodifier_function_generator (BlenderRNA * brna) [static]
Definition at line 679 of file rna_fcurve.c.
References FCM_GENERATOR_ADDITIVE, NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
static void rna_def_fmodifier_generator (BlenderRNA * brna) [static]
Definition at line 631 of file rna_fcurve.c.
References FCM_GENERATOR_ADDITIVE, FCM_GENERATOR_POLYNOMIAL, FCM_GENERATOR_POLYNOMIAL_FACTORISED, NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, PROP_BOOLEAN, PROP_DYNAMIC, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_dynamic_array_funcs(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
static void rna_def_fmodifier_limits (BlenderRNA * brna) [static]
Definition at line 858 of file rna_fcurve.c.
References FCM_LIMIT_XMAX, FCM_LIMIT_XMIN, FCM_LIMIT_YMAX, FCM_LIMIT_YMIN, NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
static void rna_def_fmodifier_noise (BlenderRNA * brna) [static]
Definition at line 914 of file rna_fcurve.c.
References FCM_NOISE_MODIF_ADD, FCM_NOISE_MODIF_MULTIPLY, FCM_NOISE_MODIF_REPLACE, FCM_NOISE_MODIF_SUBTRACT, NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
static void rna_def_fmodifier_python (BlenderRNA * brna) [static]
Definition at line 846 of file rna_fcurve.c.
References RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
static void rna_def_fmodifier_stepped (BlenderRNA * brna) [static]
Definition at line 961 of file rna_fcurve.c.
References FCM_STEPPED_NO_AFTER, FCM_STEPPED_NO_BEFORE, NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
static void rna_def_fpoint (BlenderRNA * brna) [static]
Definition at line 1316 of file rna_fcurve.c.
References NA_EDITED, NA_SELECTED, NC_ANIMATION, ND_KEYFRAME, NULL, PROP_BOOLEAN, PROP_COORDS, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_fcurve().
Variable Documentation
EnumPropertyItem beztriple_keyframe_type_items[]
Initial value:
 {
    {BEZT_KEYTYPE_KEYFRAME, "KEYFRAME", 0, "Keyframe", ""},
    {BEZT_KEYTYPE_BREAKDOWN, "BREAKDOWN", 0, "Breakdown", ""},
    {BEZT_KEYTYPE_EXTREME, "EXTREME", 0, "Extreme", ""},
    {BEZT_KEYTYPE_JITTER, "JITTER", 0, "Jitter", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 64 of file rna_fcurve.c.
Referenced by ACTION_OT_keyframe_type().
EnumPropertyItem fmodifier_type_items[]
Initial value:
 {
    {FMODIFIER_TYPE_NULL, "NULL", 0, "Invalid", ""},
    {FMODIFIER_TYPE_GENERATOR, "GENERATOR", 0, "Generator", ""},
    {FMODIFIER_TYPE_FN_GENERATOR, "FNGENERATOR", 0, "Built-In Function", ""},
    {FMODIFIER_TYPE_ENVELOPE, "ENVELOPE", 0, "Envelope", ""},
    {FMODIFIER_TYPE_CYCLES, "CYCLES", 0, "Cycles", ""},
    {FMODIFIER_TYPE_NOISE, "NOISE", 0, "Noise", ""},
    {FMODIFIER_TYPE_FILTER, "FILTER", 0, "Filter", ""},
    {FMODIFIER_TYPE_LIMITS, "LIMITS", 0, "Limits", ""},
    {FMODIFIER_TYPE_STEPPED, "STEPPED", 0, "Stepped Interpolation", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 51 of file rna_fcurve.c.
Referenced by GRAPH_OT_fmodifier_add(), and NLA_OT_fmodifier_add().