Blender: btMinkowskiSumShape Class Reference
btMinkowskiSumShape Class Reference
The btMinkowskiSumShape is only for advanced users. This shape represents implicit based minkowski sum of two convex implicit shapes.
#include <btMinkowskiSumShape.h>
Public Member Functions
btMinkowskiSumShape (const btConvexShape *shapeA, const btConvexShape *shapeB)
virtual btVector3 localGetSupportingVertexWithoutMargin (const btVector3 &vec) const
virtual void batchedUnitVectorGetSupportingVertexWithoutMargin (const btVector3 *vectors, btVector3 *supportVerticesOut, int numVectors) const
virtual void calculateLocalInertia (btScalar mass, btVector3 &inertia) const
void setTransformA (const btTransform &transA)
void setTransformB (const btTransform &transB)
const btTransform & getTransformA () const
const btTransform & GetTransformB () const
virtual btScalar getMargin () const
const btConvexShape * getShapeA () const
const btConvexShape * getShapeB () const
virtual const char * getName () const
Detailed Description
The btMinkowskiSumShape is only for advanced users. This shape represents implicit based minkowski sum of two convex implicit shapes.
Definition at line 23 of file btMinkowskiSumShape.h.
Constructor & Destructor Documentation
btMinkowskiSumShape::btMinkowskiSumShape (const btConvexShape * shapeA, const btConvexShape * shapeB)
Definition at line 20 of file btMinkowskiSumShape.cpp.
References MINKOWSKI_DIFFERENCE_SHAPE_PROXYTYPE, and btTransform::setIdentity().
Member Function Documentation
void btMinkowskiSumShape::batchedUnitVectorGetSupportingVertexWithoutMargin (const btVector3 * vectors, btVector3 * supportVerticesOut, int numVectors) const [virtual]
Todo:
: could make recursive use of batching. probably this shape is not used frequently.
Definition at line 37 of file btMinkowskiSumShape.cpp.
References i, and localGetSupportingVertexWithoutMargin().
void btMinkowskiSumShape::calculateLocalInertia (btScalar mass, btVector3 & inertia) const [virtual]
Definition at line 55 of file btMinkowskiSumShape.cpp.
References btAssert.
btScalar btMinkowskiSumShape::getMargin () const [virtual]
Reimplemented from btConvexInternalShape.
Definition at line 49 of file btMinkowskiSumShape.cpp.
virtual const char* btMinkowskiSumShape::getName (void) const [inline, virtual]
Definition at line 54 of file btMinkowskiSumShape.h.
const btConvexShape* btMinkowskiSumShape::getShapeA () const [inline]
Definition at line 51 of file btMinkowskiSumShape.h.
const btConvexShape* btMinkowskiSumShape::getShapeB () const [inline]
Definition at line 52 of file btMinkowskiSumShape.h.
const btTransform& btMinkowskiSumShape::getTransformA () const [inline]
Definition at line 45 of file btMinkowskiSumShape.h.
const btTransform& btMinkowskiSumShape::GetTransformB () const [inline]
Definition at line 46 of file btMinkowskiSumShape.h.
btVector3 btMinkowskiSumShape::localGetSupportingVertexWithoutMargin (const btVector3 & vec) const [virtual]
Definition at line 30 of file btMinkowskiSumShape.cpp.
References btTransform::getBasis().
Referenced by batchedUnitVectorGetSupportingVertexWithoutMargin().
void btMinkowskiSumShape::setTransformA (const btTransform & transA) [inline]
Definition at line 42 of file btMinkowskiSumShape.h.
void btMinkowskiSumShape::setTransformB (const btTransform & transB) [inline]
Definition at line 43 of file btMinkowskiSumShape.h.
The documentation for this class was generated from the following files:
btMinkowskiSumShape.h
btMinkowskiSumShape.cpp