Blender: BlenderWorldInfo Class Reference
BlenderWorldInfo Class Reference
#include <BlenderWorldInfo.h>
Public Member Functions
BlenderWorldInfo (struct Scene *blenderscene, struct World *blenderworld)
~BlenderWorldInfo ()
bool hasWorld ()
bool hasMist ()
float getBackColorRed ()
float getBackColorGreen ()
float getBackColorBlue ()
float getAmbientColorRed ()
float getAmbientColorGreen ()
float getAmbientColorBlue ()
float getMistStart ()
float getMistDistance ()
float getMistColorRed ()
float getMistColorGreen ()
float getMistColorBlue ()
void setBackColor (float r, float g, float b)
void setMistStart (float d)
void setMistDistance (float d)
void setMistColorRed (float d)
void setMistColorGreen (float d)
void setMistColorBlue (float d)
Detailed Description
Definition at line 38 of file BlenderWorldInfo.h.
Constructor & Destructor Documentation
BlenderWorldInfo::BlenderWorldInfo (struct Scene * blenderscene, struct World * blenderworld)
Definition at line 68 of file BlenderWorldInfo.cpp.
References World::ambr, RenderData::color_mgt_flag, copy_v3_v3(), World::horr, linearrgb_to_srgb_v3_v3(), World::mistdist, World::miststa, World::mode, Scene::r, R_COLOR_MANAGEMENT, WO_MIST, and zero_v3().
BlenderWorldInfo::~BlenderWorldInfo ()
Definition at line 107 of file BlenderWorldInfo.cpp.
Member Function Documentation
float BlenderWorldInfo::getAmbientColorBlue () [virtual]
Implements KX_WorldInfo.
Definition at line 157 of file BlenderWorldInfo.cpp.
float BlenderWorldInfo::getAmbientColorGreen () [virtual]
Implements KX_WorldInfo.
Definition at line 152 of file BlenderWorldInfo.cpp.
float BlenderWorldInfo::getAmbientColorRed () [virtual]
Implements KX_WorldInfo.
Definition at line 147 of file BlenderWorldInfo.cpp.
float BlenderWorldInfo::getBackColorBlue () [virtual]
Implements KX_WorldInfo.
Definition at line 141 of file BlenderWorldInfo.cpp.
float BlenderWorldInfo::getBackColorGreen () [virtual]
Implements KX_WorldInfo.
Definition at line 134 of file BlenderWorldInfo.cpp.
float BlenderWorldInfo::getBackColorRed () [virtual]
Implements KX_WorldInfo.
Definition at line 127 of file BlenderWorldInfo.cpp.
float BlenderWorldInfo::getMistColorBlue () [virtual]
Implements KX_WorldInfo.
Definition at line 190 of file BlenderWorldInfo.cpp.
float BlenderWorldInfo::getMistColorGreen () [virtual]
Implements KX_WorldInfo.
Definition at line 183 of file BlenderWorldInfo.cpp.
float BlenderWorldInfo::getMistColorRed () [virtual]
Implements KX_WorldInfo.
Definition at line 176 of file BlenderWorldInfo.cpp.
float BlenderWorldInfo::getMistDistance () [virtual]
Implements KX_WorldInfo.
Definition at line 169 of file BlenderWorldInfo.cpp.
float BlenderWorldInfo::getMistStart () [virtual]
Implements KX_WorldInfo.
Definition at line 162 of file BlenderWorldInfo.cpp.
bool BlenderWorldInfo::hasMist () [virtual]
Implements KX_WorldInfo.
Definition at line 120 of file BlenderWorldInfo.cpp.
bool BlenderWorldInfo::hasWorld () [virtual]
Implements KX_WorldInfo.
Definition at line 113 of file BlenderWorldInfo.cpp.
void BlenderWorldInfo::setBackColor (float r, float g, float b) [virtual]
Implements KX_WorldInfo.
Definition at line 195 of file BlenderWorldInfo.cpp.
References g.
void BlenderWorldInfo::setMistColorBlue (float d) [virtual]
Implements KX_WorldInfo.
Definition at line 235 of file BlenderWorldInfo.cpp.
void BlenderWorldInfo::setMistColorGreen (float d) [virtual]
Implements KX_WorldInfo.
Definition at line 227 of file BlenderWorldInfo.cpp.
void BlenderWorldInfo::setMistColorRed (float d) [virtual]
Implements KX_WorldInfo.
Definition at line 219 of file BlenderWorldInfo.cpp.
void BlenderWorldInfo::setMistDistance (float d) [virtual]
Implements KX_WorldInfo.
Definition at line 211 of file BlenderWorldInfo.cpp.
void BlenderWorldInfo::setMistStart (float d) [virtual]
Implements KX_WorldInfo.
Definition at line 203 of file BlenderWorldInfo.cpp.
The documentation for this class was generated from the following files:
BlenderWorldInfo.h
BlenderWorldInfo.cpp