Blender: GHOST_WindowNULL Class Reference
GHOST_WindowNULL Class Reference
#include <GHOST_WindowNULL.h>
Public Member Functions
const GHOST_TabletData * GetTabletData ()
GHOST_WindowNULL (GHOST_SystemNULL *system, const STR_String &title, GHOST_TInt32 left, GHOST_TInt32 top, GHOST_TUns32 width, GHOST_TUns32 height, GHOST_TWindowState state, const GHOST_TEmbedderWindowID parentWindow, GHOST_TDrawingContextType type, const bool stereoVisual, const GHOST_TUns16 numOfAASamples)
Protected Member Functions
GHOST_TSuccess installDrawingContext (GHOST_TDrawingContextType type)
GHOST_TSuccess removeDrawingContext ()
GHOST_TSuccess setWindowCursorGrab (GHOST_TGrabCursorMode mode)
GHOST_TSuccess setWindowCursorShape (GHOST_TStandardCursor shape)
GHOST_TSuccess setWindowCustomCursorShape (GHOST_TUns8 bitmap[16][2], GHOST_TUns8 mask[16][2], int hotX, int hotY)
GHOST_TSuccess setWindowCustomCursorShape (GHOST_TUns8 *bitmap, GHOST_TUns8 *mask, int sizex, int sizey, int hotX, int hotY, int fg_color, int bg_color)
bool getValid () const
void setTitle (const STR_String &title)
void getTitle (STR_String &title) const
void getWindowBounds (GHOST_Rect &bounds) const
void getClientBounds (GHOST_Rect &bounds) const
GHOST_TSuccess setClientWidth (GHOST_TUns32 width)
GHOST_TSuccess setClientHeight (GHOST_TUns32 height)
GHOST_TSuccess setClientSize (GHOST_TUns32 width, GHOST_TUns32 height)
void screenToClient (GHOST_TInt32 inX, GHOST_TInt32 inY, GHOST_TInt32 &outX, GHOST_TInt32 &outY) const
void clientToScreen (GHOST_TInt32 inX, GHOST_TInt32 inY, GHOST_TInt32 &outX, GHOST_TInt32 &outY) const
GHOST_TSuccess swapBuffers ()
GHOST_TSuccess activateDrawingContext ()
~GHOST_WindowNULL ()
GHOST_TSuccess setWindowCursorVisibility (bool visible)
GHOST_TSuccess setState (GHOST_TWindowState state)
GHOST_TWindowState getState () const
GHOST_TSuccess invalidate ()
GHOST_TSuccess setOrder (GHOST_TWindowOrder order)
Detailed Description
Definition at line 38 of file GHOST_WindowNULL.h.
Constructor & Destructor Documentation
GHOST_WindowNULL::GHOST_WindowNULL (GHOST_SystemNULL * system, const STR_String & title, GHOST_TInt32 left, GHOST_TInt32 top, GHOST_TUns32 width, GHOST_TUns32 height, GHOST_TWindowState state, const GHOST_TEmbedderWindowID parentWindow, GHOST_TDrawingContextType type, const bool stereoVisual, const GHOST_TUns16 numOfAASamples) [inline]
Definition at line 43 of file GHOST_WindowNULL.h.
References setTitle().
GHOST_WindowNULL::~GHOST_WindowNULL () [inline, protected]
Definition at line 82 of file GHOST_WindowNULL.h.
Member Function Documentation
GHOST_TSuccess GHOST_WindowNULL::activateDrawingContext () [inline, protected, virtual]
Activates the drawing context of this window.
Returns:
A boolean success indicator.
Implements GHOST_IWindow.
Definition at line 81 of file GHOST_WindowNULL.h.
References GHOST_kFailure.
void GHOST_WindowNULL::clientToScreen (GHOST_TInt32 inX, GHOST_TInt32 inY, GHOST_TInt32 & outX, GHOST_TInt32 & outY) const [inline, protected, virtual]
Converts a point in screen coordinates to client rectangle coordinates
Parameters:
inX The x-coordinate in the client rectangle.
inY The y-coordinate in the client rectangle.
outX The x-coordinate on the screen.
outY The y-coordinate on the screen.
Implements GHOST_IWindow.
Definition at line 79 of file GHOST_WindowNULL.h.
void GHOST_WindowNULL::getClientBounds (GHOST_Rect & bounds) const [inline, protected, virtual]
Returns the client rectangle dimensions. The left and top members of the rectangle are always zero.
Parameters:
bounds The bounding rectangle of the client area of the window.
Implements GHOST_IWindow.
Definition at line 74 of file GHOST_WindowNULL.h.
Referenced by getWindowBounds().
GHOST_TWindowState GHOST_WindowNULL::getState () const [inline, protected, virtual]
Returns the state of the window (normal, minimized, maximized).
Returns:
The state of the window.
Implements GHOST_IWindow.
Definition at line 85 of file GHOST_WindowNULL.h.
References GHOST_kWindowStateNormal.
const GHOST_TabletData* GHOST_WindowNULL::GetTabletData () [inline, virtual]
Returns the tablet data (pressure etc).
Returns:
The tablet data (pressure etc).
Implements GHOST_IWindow.
Definition at line 41 of file GHOST_WindowNULL.h.
References NULL.
void GHOST_WindowNULL::getTitle (STR_String & title) const [inline, protected, virtual]
Returns the title displayed in the title bar.
Parameters:
title The title displayed in the title bar.
Implements GHOST_IWindow.
Definition at line 72 of file GHOST_WindowNULL.h.
bool GHOST_WindowNULL::getValid () const [inline, protected, virtual]
Returns indication as to whether the window is valid.
Returns:
The validity of the window.
Implements GHOST_IWindow.
Definition at line 70 of file GHOST_WindowNULL.h.
void GHOST_WindowNULL::getWindowBounds (GHOST_Rect & bounds) const [inline, protected, virtual]
Returns the window rectangle dimensions. These are screen coordinates.
Parameters:
bounds The bounding rectangle of the window.
Implements GHOST_IWindow.
Definition at line 73 of file GHOST_WindowNULL.h.
References getClientBounds().
GHOST_TSuccess GHOST_WindowNULL::installDrawingContext (GHOST_TDrawingContextType type) [inline, protected, virtual]
Tries to install a rendering context in this window.
Parameters:
type The type of rendering context installed.
Returns:
Indication as to whether installation has succeeded.
Implements GHOST_Window.
Definition at line 63 of file GHOST_WindowNULL.h.
References GHOST_kSuccess.
GHOST_TSuccess GHOST_WindowNULL::invalidate () [inline, protected, virtual]
Invalidates the contents of this window.
Returns:
Indication of success.
Implements GHOST_IWindow.
Definition at line 86 of file GHOST_WindowNULL.h.
References GHOST_kSuccess.
GHOST_TSuccess GHOST_WindowNULL::removeDrawingContext () [inline, protected, virtual]
Removes the current drawing context.
Returns:
Indication as to whether removal has succeeded.
Implements GHOST_Window.
Definition at line 64 of file GHOST_WindowNULL.h.
References GHOST_kSuccess.
void GHOST_WindowNULL::screenToClient (GHOST_TInt32 inX, GHOST_TInt32 inY, GHOST_TInt32 & outX, GHOST_TInt32 & outY) const [inline, protected, virtual]
Converts a point in screen coordinates to client rectangle coordinates
Parameters:
inX The x-coordinate on the screen.
inY The y-coordinate on the screen.
outX The x-coordinate in the client rectangle.
outY The y-coordinate in the client rectangle.
Implements GHOST_IWindow.
Definition at line 78 of file GHOST_WindowNULL.h.
GHOST_TSuccess GHOST_WindowNULL::setClientHeight (GHOST_TUns32 height) [inline, protected, virtual]
Resizes client rectangle height.
Parameters:
height The new height of the client area of the window.
Implements GHOST_IWindow.
Definition at line 76 of file GHOST_WindowNULL.h.
References GHOST_kFailure.
GHOST_TSuccess GHOST_WindowNULL::setClientSize (GHOST_TUns32 width, GHOST_TUns32 height) [inline, protected, virtual]
Resizes client rectangle.
Parameters:
width The new width of the client area of the window.
height The new height of the client area of the window.
Implements GHOST_IWindow.
Definition at line 77 of file GHOST_WindowNULL.h.
References GHOST_kFailure.
GHOST_TSuccess GHOST_WindowNULL::setClientWidth (GHOST_TUns32 width) [inline, protected, virtual]
Resizes client rectangle width.
Parameters:
width The new width of the client area of the window.
Implements GHOST_IWindow.
Definition at line 75 of file GHOST_WindowNULL.h.
References GHOST_kFailure.
GHOST_TSuccess GHOST_WindowNULL::setOrder (GHOST_TWindowOrder order) [inline, protected, virtual]
Sets the order of the window (bottom, top).
Parameters:
order The order of the window.
Returns:
Indication of success.
Implements GHOST_IWindow.
Definition at line 87 of file GHOST_WindowNULL.h.
References GHOST_kSuccess.
GHOST_TSuccess GHOST_WindowNULL::setState (GHOST_TWindowState state) [inline, protected, virtual]
Sets the state of the window (normal, minimized, maximized).
Parameters:
state The state of the window.
Returns:
Indication of success.
Implements GHOST_IWindow.
Definition at line 84 of file GHOST_WindowNULL.h.
References GHOST_kSuccess.
void GHOST_WindowNULL::setTitle (const STR_String & title) [inline, protected, virtual]
Sets the title displayed in the title bar.
Parameters:
title The title to display in the title bar.
Implements GHOST_IWindow.
Definition at line 71 of file GHOST_WindowNULL.h.
Referenced by GHOST_WindowNULL().
GHOST_TSuccess GHOST_WindowNULL::setWindowCursorGrab (GHOST_TGrabCursorMode mode) [inline, protected, virtual]
Sets the cursor grab on the window using native window system calls.
Reimplemented from GHOST_Window.
Definition at line 65 of file GHOST_WindowNULL.h.
References GHOST_kSuccess.
GHOST_TSuccess GHOST_WindowNULL::setWindowCursorShape (GHOST_TStandardCursor shape) [inline, protected, virtual]
Sets the cursor shape on the window using native window system calls.
Implements GHOST_Window.
Definition at line 66 of file GHOST_WindowNULL.h.
References GHOST_kSuccess.
GHOST_TSuccess GHOST_WindowNULL::setWindowCursorVisibility (bool visible) [inline, protected, virtual]
Sets the cursor visibility on the window using native window system calls.
Implements GHOST_Window.
Definition at line 83 of file GHOST_WindowNULL.h.
References GHOST_kSuccess.
GHOST_TSuccess GHOST_WindowNULL::setWindowCustomCursorShape (GHOST_TUns8 bitmap[16][2], GHOST_TUns8 mask[16][2], int hotX, int hotY) [inline, protected, virtual]
Sets the cursor shape on the window using native window system calls.
Implements GHOST_Window.
Definition at line 67 of file GHOST_WindowNULL.h.
References GHOST_kSuccess.
GHOST_TSuccess GHOST_WindowNULL::setWindowCustomCursorShape (GHOST_TUns8 * bitmap, GHOST_TUns8 * mask, int sizex, int sizey, int hotX, int hotY, int fg_color, int bg_color) [inline, protected, virtual]
Implements GHOST_Window.
Definition at line 68 of file GHOST_WindowNULL.h.
References GHOST_kSuccess.
GHOST_TSuccess GHOST_WindowNULL::swapBuffers () [inline, protected, virtual]
Swaps front and back buffers of a window.
Returns:
A boolean success indicator.
Implements GHOST_IWindow.
Definition at line 80 of file GHOST_WindowNULL.h.
References GHOST_kFailure.
The documentation for this class was generated from the following file:
GHOST_WindowNULL.h