Blender: node_select.c File Reference
node_select.c File Reference
node editor
#include <stdio.h>
#include "BLI_listbase.h"
#include "DNA_node_types.h"
#include "DNA_scene_types.h"
#include "BKE_context.h"
#include "BKE_main.h"
#include "BLI_rect.h"
#include "BLI_utildefines.h"
#include "ED_node.h"
#include "ED_screen.h"
#include "ED_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_view2d.h"
#include "node_intern.h"
Functions
static bNode * node_under_mouse (bNodeTree *ntree, int mx, int my)
static int compare_nodes (bNode *a, bNode *b)
static void node_sort (bNodeTree *ntree)
void node_select (bNode *node)
void node_deselect (bNode *node)
static void node_toggle (bNode *node)
void node_socket_select (bNode *node, bNodeSocket *sock)
void node_socket_deselect (bNode *node, bNodeSocket *sock, int deselect_node)
static void node_socket_toggle (bNode *node, bNodeSocket *sock, int deselect_node)
void node_deselect_all (SpaceNode *snode)
void node_deselect_all_input_sockets (SpaceNode *snode, int deselect_nodes)
void node_deselect_all_output_sockets (SpaceNode *snode, int deselect_nodes)
int node_select_same_type (SpaceNode *snode)
int node_select_same_type_np (SpaceNode *snode, int dir)
void node_select_single (bContext *C, bNode *node)
static int node_mouse_select (Main *bmain, SpaceNode *snode, ARegion *ar, const int mval[2], short extend)
static int node_select_exec (bContext *C, wmOperator *op)
static int node_select_invoke (bContext *C, wmOperator *op, wmEvent *event)
void NODE_OT_select (wmOperatorType *ot)
static int node_borderselect_exec (bContext *C, wmOperator *op)
static int node_border_select_invoke (bContext *C, wmOperator *op, wmEvent *event)
void NODE_OT_select_border (wmOperatorType *ot)
static int node_select_all_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_select_all (wmOperatorType *ot)
static int node_select_linked_to_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_select_linked_to (wmOperatorType *ot)
static int node_select_linked_from_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_select_linked_from (wmOperatorType *ot)
static int node_select_same_type_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_select_same_type (wmOperatorType *ot)
static int node_select_same_type_next_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_select_same_type_next (wmOperatorType *ot)
static int node_select_same_type_prev_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_select_same_type_prev (wmOperatorType *ot)
Detailed Description
Definition in file node_select.c.
Function Documentation
static int compare_nodes (bNode * a, bNode * b) [static]
Definition at line 73 of file node_select.c.
References bNode::flag, NODE_ACTIVE, NODE_BACKGROUND, NODE_SELECT, and bNode::parent.
Referenced by node_sort().
static int node_border_select_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 583 of file node_select.c.
References CTX_wm_region(), CTX_wm_space_node(), SpaceNode::edittree, wmEvent::mval, node_under_mouse(), OPERATOR_CANCELLED, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_boolean_get(), UI_view2d_region_to_view(), ARegion::v2d, and WM_border_select_invoke().
Referenced by NODE_OT_select_border().
static int node_borderselect_exec (bContext * C, wmOperator * op) [static]
Definition at line 546 of file node_select.c.
References BLI_isect_rctf(), CTX_wm_region(), CTX_wm_space_node(), SpaceNode::edittree, ListBase::first, GESTURE_MODAL_SELECT, NA_SELECTED, NC_NODE, bNode::next, node_deselect(), node_select(), node_sort(), bNodeTree::nodes, NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_int_get(), bNode::totr, UI_view2d_region_to_view(), ARegion::v2d, WM_event_add_notifier(), rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, rctf::ymax, rcti::ymax, rctf::ymin, and rcti::ymin.
Referenced by NODE_OT_select_border().
void node_deselect (bNode * node)
Definition at line 181 of file node_select.c.
References ListBase::first, bNode::flag, bNodeSocket::flag, bNode::inputs, bNodeSocket::next, bNode::outputs, and SELECT.
Referenced by node_borderselect_exec(), node_deselect_all(), node_duplicate_exec(), node_mouse_select(), node_select_all_exec(), node_select_same_type(), node_select_same_type_np(), node_select_single(), node_toggle(), and snode_make_group_editable().
void node_deselect_all (SpaceNode * snode)
Definition at line 246 of file node_select.c.
References SpaceNode::edittree, ListBase::first, bNode::next, node_deselect(), and bNodeTree::nodes.
Referenced by node_add_file_exec(), and node_add_node().
void node_deselect_all_input_sockets (SpaceNode * snode, int deselect_nodes)
Definition at line 254 of file node_select.c.
References SpaceNode::edittree, ListBase::first, bNode::flag, bNodeSocket::flag, bNode::inputs, bNodeSocket::next, bNode::next, bNodeTree::nodes, bNode::outputs, bNodeTree::outputs, and SELECT.
Referenced by node_link_init(), node_link_modal(), and node_make_link_exec().
void node_deselect_all_output_sockets (SpaceNode * snode, int deselect_nodes)
Definition at line 288 of file node_select.c.
References SpaceNode::edittree, ListBase::first, bNode::flag, bNodeSocket::flag, bNodeTree::inputs, bNode::inputs, bNodeSocket::next, bNode::next, bNodeTree::nodes, bNode::outputs, and SELECT.
Referenced by node_link_init(), node_link_modal(), and node_make_link_exec().
static int node_mouse_select (Main * bmain, SpaceNode * snode, ARegion * ar, const int mval[2], short extend) [static]
Definition at line 417 of file node_select.c.
References ED_node_set_active(), SpaceNode::edittree, ListBase::first, bNodeSocket::flag, SpaceNode::mx, SpaceNode::my, bNodeSocket::next, bNode::next, node_deselect(), node_find_indicated_socket(), node_select(), node_socket_deselect(), node_socket_select(), node_socket_toggle(), node_sort(), node_toggle(), node_under_mouse(), bNodeTree::nodes, bNode::outputs, SELECT, SOCK_IN, SOCK_OUT, UI_view2d_region_to_view(), and ARegion::v2d.
Referenced by node_select_exec().
void NODE_OT_select (wmOperatorType * ot)
Definition at line 524 of file node_select.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, node_select_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_int(), and wmOperatorType::srna.
Referenced by node_operatortypes().
void NODE_OT_select_all (wmOperatorType * ot)
Definition at line 654 of file node_select.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_select_all_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_select_border (wmOperatorType * ot)
Definition at line 603 of file node_select.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, node_border_select_invoke(), node_borderselect_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, TRUE, WM_border_select_cancel(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by node_operatortypes().
void NODE_OT_select_linked_from (wmOperatorType * ot)
Definition at line 738 of file node_select.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_select_linked_from_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_select_linked_to (wmOperatorType * ot)
Definition at line 696 of file node_select.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_select_linked_to_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_select_same_type (wmOperatorType * ot)
Definition at line 767 of file node_select.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_select_same_type_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_select_same_type_next (wmOperatorType * ot)
Definition at line 797 of file node_select.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_select_same_type_next_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void NODE_OT_select_same_type_prev (wmOperatorType * ot)
Definition at line 824 of file node_select.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_select_same_type_prev_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
void node_select (bNode * node)
Definition at line 176 of file node_select.c.
References bNode::flag, and SELECT.
Referenced by node_add_node(), node_borderselect_exec(), node_duplicate_exec(), node_mouse_select(), node_select_all_exec(), node_select_linked_from_exec(), node_select_linked_to_exec(), node_select_same_type(), node_select_same_type_np(), node_select_single(), node_toggle(), and snode_make_group_editable().
static int node_select_all_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 628 of file node_select.c.
References CTX_wm_space_node(), SpaceNode::edittree, ListBase::first, bNode::flag, NA_SELECTED, NC_NODE, bNode::next, node_deselect(), node_select(), NODE_SELECT, node_sort(), bNodeTree::nodes, NULL, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by NODE_OT_select_all().
static int node_select_exec (bContext * C, wmOperator * op) [static]
Definition at line 487 of file node_select.c.
References CTX_data_main(), CTX_wm_region(), CTX_wm_space_node(), NA_SELECTED, NC_NODE, node_mouse_select(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_boolean_get(), RNA_int_get(), and WM_event_add_notifier().
Referenced by node_select_invoke().
static int node_select_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 515 of file node_select.c.
References wmEvent::mval, node_select_exec(), wmOperator::ptr, and RNA_int_set().
Referenced by NODE_OT_select().
static int node_select_linked_from_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 713 of file node_select.c.
References CTX_wm_space_node(), SpaceNode::edittree, ListBase::first, bNode::flag, bNodeLink::fromnode, link(), bNodeTree::links, NA_SELECTED, NC_NODE, bNodeLink::next, bNode::next, node_select(), NODE_SELECT, node_sort(), NODE_TEST, bNodeTree::nodes, NULL, OPERATOR_FINISHED, bNodeLink::tonode, and WM_event_add_notifier().
Referenced by NODE_OT_select_linked_from().
static int node_select_linked_to_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 671 of file node_select.c.
References CTX_wm_space_node(), SpaceNode::edittree, ListBase::first, bNode::flag, bNodeLink::fromnode, link(), bNodeTree::links, NA_SELECTED, NC_NODE, bNodeLink::next, bNode::next, node_select(), NODE_SELECT, node_sort(), NODE_TEST, bNodeTree::nodes, NULL, OPERATOR_FINISHED, bNodeLink::tonode, and WM_event_add_notifier().
Referenced by NODE_OT_select_linked_to().
int node_select_same_type (SpaceNode * snode)
Definition at line 323 of file node_select.c.
References SpaceNode::edittree, ListBase::first, bNode::flag, bNode::next, node_deselect(), node_select(), bNodeTree::nodes, p, SELECT, and bNode::type.
Referenced by node_select_same_type_exec().
static int node_select_same_type_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 755 of file node_select.c.
References CTX_wm_space_node(), SpaceNode::edittree, NA_SELECTED, NC_NODE, node_select_same_type(), node_sort(), NULL, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by NODE_OT_select_same_type().
static int node_select_same_type_next_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 784 of file node_select.c.
References CTX_wm_space_node(), SpaceNode::edittree, NA_SELECTED, NC_NODE, node_select_same_type_np(), node_sort(), NULL, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by NODE_OT_select_same_type_next().
int node_select_same_type_np (SpaceNode * snode, int dir)
Definition at line 357 of file node_select.c.
References SpaceNode::edittree, ListBase::first, bNode::flag, bNode::next, node_deselect(), node_select(), bNodeTree::nodes, p, bNode::prev, SELECT, and bNode::type.
Referenced by node_select_same_type_next_exec(), and node_select_same_type_prev_exec().
static int node_select_same_type_prev_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 812 of file node_select.c.
References CTX_wm_space_node(), SpaceNode::edittree, NA_SELECTED, NC_NODE, node_select_same_type_np(), node_sort(), NULL, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by NODE_OT_select_same_type_prev().
void node_select_single (bContext * C, bNode * node)
Definition at line 397 of file node_select.c.
References CTX_data_main(), CTX_wm_space_node(), ED_node_set_active(), SpaceNode::edittree, ListBase::first, NA_SELECTED, NC_NODE, bNode::next, node_deselect(), node_select(), node_sort(), bNodeTree::nodes, NULL, and WM_event_add_notifier().
Referenced by node_toggle_button_cb().
void node_socket_deselect (bNode * node, bNodeSocket * sock, int deselect_node)
Definition at line 211 of file node_select.c.
References ListBase::first, bNode::flag, bNodeSocket::flag, bNode::inputs, bNodeSocket::next, bNode::outputs, and SELECT.
Referenced by node_mouse_select(), and node_socket_toggle().
void node_socket_select (bNode * node, bNodeSocket * sock)
Definition at line 202 of file node_select.c.
References bNode::flag, bNodeSocket::flag, and SELECT.
Referenced by node_link_init(), node_link_modal(), node_mouse_select(), and node_socket_toggle().
static void node_socket_toggle (bNode * node, bNodeSocket * sock, int deselect_node) [static]
Definition at line 237 of file node_select.c.
References bNodeSocket::flag, node_socket_deselect(), node_socket_select(), and SELECT.
Referenced by node_mouse_select().
static void node_sort (bNodeTree * ntree) [static]
Definition at line 123 of file node_select.c.
References BLI_countlist(), BLI_insertlinkbefore(), BLI_remlink(), compare_nodes(), ListBase::first, bNode::next, bNodeTree::nodes, and NULL.
Referenced by node_borderselect_exec(), node_mouse_select(), node_select_all_exec(), node_select_linked_from_exec(), node_select_linked_to_exec(), node_select_same_type_exec(), node_select_same_type_next_exec(), node_select_same_type_prev_exec(), and node_select_single().
static void node_toggle (bNode * node) [static]
Definition at line 194 of file node_select.c.
References bNode::flag, node_deselect(), node_select(), and SELECT.
Referenced by node_mouse_select().
static bNode* node_under_mouse (bNodeTree * ntree, int mx, int my) [static]
Definition at line 61 of file node_select.c.
References BLI_in_rctf(), ListBase::last, bNodeTree::nodes, NULL, bNode::prev, and bNode::totr.
Referenced by node_border_select_invoke(), and node_mouse_select().