Blender: LaplacianSystem::HeatWeighting Struct Reference
LaplacianSystem::HeatWeighting Struct Reference
Public Attributes
MFace * mface
int totvert
int totface
float(* verts)[3]
float(* vnors)[3]
float(* root)[3]
float(* tip)[3]
float(* source)[3]
int numsource
float * H
float * p
float * mindist
BVHTree * bvhtree
MFace ** vface
Detailed Description
Definition at line 99 of file meshlaplacian.c.
Member Data Documentation
BVHTree* LaplacianSystem::HeatWeighting::bvhtree
Definition at line 115 of file meshlaplacian.c.
Referenced by heat_ray_source_visible(), heat_ray_tree_create(), and heat_system_free().
float* LaplacianSystem::HeatWeighting::H
Definition at line 111 of file meshlaplacian.c.
Referenced by heat_bone_weighting(), heat_laplacian_create(), heat_set_H(), heat_system_free(), and laplacian_system_construct_end().
MFace* LaplacianSystem::HeatWeighting::mface
Definition at line 100 of file meshlaplacian.c.
Referenced by bvh_callback(), heat_bone_weighting(), heat_laplacian_create(), and heat_ray_tree_create().
float* LaplacianSystem::HeatWeighting::mindist
Definition at line 113 of file meshlaplacian.c.
Referenced by heat_laplacian_create(), heat_set_H(), and heat_system_free().
int LaplacianSystem::HeatWeighting::numsource
Definition at line 109 of file meshlaplacian.c.
Referenced by heat_bone_weighting(), and heat_set_H().
float* LaplacianSystem::HeatWeighting::p
Definition at line 112 of file meshlaplacian.c.
Referenced by heat_bone_weighting(), heat_laplacian_create(), heat_set_H(), and heat_system_free().
float(* LaplacianSystem::HeatWeighting::root)[3]
Definition at line 106 of file meshlaplacian.c.
Referenced by heat_bone_weighting(), heat_ray_source_visible(), and heat_source_distance().
float(* LaplacianSystem::HeatWeighting::source)[3]
Definition at line 108 of file meshlaplacian.c.
Referenced by heat_ray_source_visible(), and heat_source_distance().
float(* LaplacianSystem::HeatWeighting::tip)[3]
Definition at line 107 of file meshlaplacian.c.
Referenced by heat_bone_weighting(), heat_ray_source_visible(), and heat_source_distance().
int LaplacianSystem::HeatWeighting::totface
Definition at line 102 of file meshlaplacian.c.
Referenced by heat_bone_weighting(), heat_laplacian_create(), and heat_ray_tree_create().
int LaplacianSystem::HeatWeighting::totvert
Definition at line 101 of file meshlaplacian.c.
Referenced by heat_bone_weighting(), heat_laplacian_create(), and heat_ray_tree_create().
float(* LaplacianSystem::HeatWeighting::verts)[3]
Definition at line 103 of file meshlaplacian.c.
Referenced by bvh_callback(), heat_bone_weighting(), heat_laplacian_create(), heat_ray_source_visible(), heat_ray_tree_create(), and heat_source_distance().
MFace** LaplacianSystem::HeatWeighting::vface
Definition at line 116 of file meshlaplacian.c.
Referenced by heat_ray_source_visible(), heat_ray_tree_create(), and heat_system_free().
float(* LaplacianSystem::HeatWeighting::vnors)[3]
Definition at line 104 of file meshlaplacian.c.
Referenced by heat_calc_vnormals(), heat_source_distance(), and heat_system_free().
The documentation for this struct was generated from the following file:
meshlaplacian.c