Blender: bmesh_walkers_impl.c File Reference
bmesh_walkers_impl.c File Reference
BMesh
#include "BLI_utildefines.h"
#include "BKE_customdata.h"
#include "bmesh.h"
#include "intern/bmesh_private.h"
#include "intern/bmesh_walkers_private.h"
Defines
#define EDGE_CHECK(e) (bmw_mask_check_edge(walker, e) && (BM_edge_is_boundary(e) || BM_edge_is_manifold(e)))
Functions
static int bmw_mask_check_vert (BMWalker *walker, BMVert *v)
static int bmw_mask_check_edge (BMWalker *walker, BMEdge *e)
static int bmw_mask_check_face (BMWalker *walker, BMFace *f)
static void bmw_ShellWalker_visitEdge (BMWalker *walker, BMEdge *e)
static void bmw_ShellWalker_begin (BMWalker *walker, void *data)
static void * bmw_ShellWalker_yield (BMWalker *walker)
static void * bmw_ShellWalker_step (BMWalker *walker)
static void bmw_ConnectedVertexWalker_visitVertex (BMWalker *walker, BMVert *v)
static void bmw_ConnectedVertexWalker_begin (BMWalker *walker, void *data)
static void * bmw_ConnectedVertexWalker_yield (BMWalker *walker)
static void * bmw_ConnectedVertexWalker_step (BMWalker *walker)
static void bmw_IslandboundWalker_begin (BMWalker *walker, void *data)
static void * bmw_IslandboundWalker_yield (BMWalker *walker)
static void * bmw_IslandboundWalker_step (BMWalker *walker)
static void bmw_IslandWalker_begin (BMWalker *walker, void *data)
static void * bmw_IslandWalker_yield (BMWalker *walker)
static void * bmw_IslandWalker_step (BMWalker *walker)
static void bmw_LoopWalker_begin (BMWalker *walker, void *data)
static void * bmw_LoopWalker_yield (BMWalker *walker)
static void * bmw_LoopWalker_step (BMWalker *walker)
static int bmw_FaceLoopWalker_include_face (BMWalker *walker, BMLoop *l)
static int bmw_FaceLoopWalker_edge_begins_loop (BMWalker *walker, BMEdge *e)
static void bmw_FaceLoopWalker_begin (BMWalker *walker, void *data)
static void * bmw_FaceLoopWalker_yield (BMWalker *walker)
static void * bmw_FaceLoopWalker_step (BMWalker *walker)
static void bmw_EdgeringWalker_begin (BMWalker *walker, void *data)
static void * bmw_EdgeringWalker_yield (BMWalker *walker)
static void * bmw_EdgeringWalker_step (BMWalker *walker)
static void bmw_UVEdgeWalker_begin (BMWalker *walker, void *data)
static void * bmw_UVEdgeWalker_yield (BMWalker *walker)
static void * bmw_UVEdgeWalker_step (BMWalker *walker)
Variables
static BMWalker bmw_ShellWalker_Type
static BMWalker bmw_IslandboundWalker_Type
static BMWalker bmw_IslandWalker_Type
static BMWalker bmw_LoopWalker_Type
static BMWalker bmw_FaceLoopWalker_Type
static BMWalker bmw_EdgeringWalker_Type
static BMWalker bmw_UVEdgeWalker_Type
static BMWalker bmw_ConnectedVertexWalker_Type
BMWalker * bm_walker_types []
const int bm_totwalkers = sizeof(bm_walker_types) / sizeof(*bm_walker_types)
Detailed Description
BMesh Walker Code.
Definition in file bmesh_walkers_impl.c.
Define Documentation
#define EDGE_CHECK (e) (bmw_mask_check_edge(walker, e) && (BM_edge_is_boundary(e) || BM_edge_is_manifold(e)))
Referenced by bmw_EdgeringWalker_step().
Function Documentation
static void bmw_ConnectedVertexWalker_begin (BMWalker * walker, void * data) [static]
Definition at line 229 of file bmesh_walkers_impl.c.
References bmw_ConnectedVertexWalker_visitVertex(), and data.
static void* bmw_ConnectedVertexWalker_step (BMWalker * walker) [static]
Definition at line 241 of file bmesh_walkers_impl.c.
References BLI_ghash_haskey(), BM_edge_other_vert(), BM_EDGES_OF_VERT, BM_ITER_ELEM, bmw_ConnectedVertexWalker_visitVertex(), BMW_current_state(), BMW_state_remove(), BMwConnectedVertexWalker::curvert, and BMWalker::visithash.
static void bmw_ConnectedVertexWalker_visitVertex (BMWalker * walker, BMVert * v) [static]
Connected Vertex Walker:
Similar to shell walker, but visits vertices instead of edges.
Definition at line 210 of file bmesh_walkers_impl.c.
References BLI_ghash_haskey(), BLI_ghash_insert(), bmw_mask_check_vert(), BMW_state_add(), BMwConnectedVertexWalker::curvert, NULL, and BMWalker::visithash.
Referenced by bmw_ConnectedVertexWalker_begin(), and bmw_ConnectedVertexWalker_step().
static void* bmw_ConnectedVertexWalker_yield (BMWalker * walker) [static]
Definition at line 235 of file bmesh_walkers_impl.c.
References BMW_current_state(), and BMwConnectedVertexWalker::curvert.
static void bmw_EdgeringWalker_begin (BMWalker * walker, void * data) [static]
Edge Ring Walker:
Starts at a tool-flagged edge and walks over the edge ring Conditions for starting and stepping the edge ring have been tuned in an attempt to match the edge rings built by EditMesh
Definition at line 780 of file bmesh_walkers_impl.c.
References BLI_ghash_free(), BLI_ghash_insert(), BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BMW_current_state(), BMW_state_add(), BMW_walk(), data, BMLoop::e, BMLoop::f, BMEdge::l, BMwEdgeringWalker::l, BMFace::len, NULL, BMLoop::radial_next, BMWalker::visithash, and BMwEdgeringWalker::wireedge.
static void* bmw_EdgeringWalker_step (BMWalker * walker) [static]
Definition at line 837 of file bmesh_walkers_impl.c.
References BLI_ghash_haskey(), BLI_ghash_insert(), BMW_current_state(), bmw_mask_check_face(), BMW_state_add(), BMW_state_remove(), BMLoop::e, EDGE_CHECK, BMLoop::f, i, BMwEdgeringWalker::l, len(), BMFace::len, BMLoop::next, NULL, BMLoop::radial_next, BMWalker::visithash, and BMwEdgeringWalker::wireedge.
static void* bmw_EdgeringWalker_yield (BMWalker * walker) [static]
Definition at line 821 of file bmesh_walkers_impl.c.
References BMW_current_state(), BMLoop::e, BMwEdgeringWalker::l, NULL, and BMwEdgeringWalker::wireedge.
static void bmw_FaceLoopWalker_begin (BMWalker * walker, void * data) [static]
Definition at line 684 of file bmesh_walkers_impl.c.
References BLI_ghash_free(), BLI_ghash_insert(), BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BMW_current_state(), bmw_FaceLoopWalker_edge_begins_loop(), BMW_state_add(), BMW_walk(), data, BMLoop::e, BMLoop::f, BMwFaceLoopWalker::l, BMEdge::l, BMwFaceLoopWalker::nocalc, NULL, BMWalker::secvisithash, and BMWalker::visithash.
static int bmw_FaceLoopWalker_edge_begins_loop (BMWalker * walker, BMEdge * e) [static]
Definition at line 661 of file bmesh_walkers_impl.c.
References BM_edge_is_boundary(), BM_edge_is_manifold(), BM_edge_is_wire(), bmw_FaceLoopWalker_include_face(), FALSE, BMEdge::l, and TRUE.
Referenced by bmw_FaceLoopWalker_begin().
static int bmw_FaceLoopWalker_include_face (BMWalker * walker, BMLoop * l) [static]
Face Loop Walker:
Starts at a tool-flagged face and walks over the face loop Conditions for starting and stepping the face loop have been tuned in an attempt to match the face loops built by EditMesh
Definition at line 641 of file bmesh_walkers_impl.c.
References BLI_ghash_haskey(), bmw_mask_check_face(), BMLoop::e, BMLoop::f, FALSE, BMFace::len, BMWalker::secvisithash, TRUE, and BMWalker::visithash.
Referenced by bmw_FaceLoopWalker_edge_begins_loop(), and bmw_FaceLoopWalker_step().
static void* bmw_FaceLoopWalker_step (BMWalker * walker) [static]
Definition at line 729 of file bmesh_walkers_impl.c.
References BLI_ghash_insert(), BM_edge_is_manifold(), BMW_current_state(), bmw_FaceLoopWalker_include_face(), BMW_state_add(), BMW_state_remove(), BMLoop::e, BMLoop::f, BMwFaceLoopWalker::l, BMFace::len, BMLoop::next, BMwFaceLoopWalker::nocalc, NULL, BMLoop::prev, BMLoop::radial_next, BMWalker::secvisithash, and BMWalker::visithash.
static void* bmw_FaceLoopWalker_yield (BMWalker * walker) [static]
Definition at line 718 of file bmesh_walkers_impl.c.
References BMW_current_state(), BMLoop::f, BMwFaceLoopWalker::l, and NULL.
static void bmw_IslandboundWalker_begin (BMWalker * walker, void * data) [static]
Island Boundary Walker:
Starts at a edge on the mesh and walks over the boundary of an island it belongs to.
Todo:
Add restriction flag/callback for wire edges.
Definition at line 269 of file bmesh_walkers_impl.c.
References BMwIslandboundWalker::base, BLI_ghash_insert(), BMW_state_add(), BMwIslandboundWalker::curloop, data, BMwIslandboundWalker::lastv, NULL, BMLoop::v, and BMWalker::visithash.
static void* bmw_IslandboundWalker_step (BMWalker * walker) [static]
Definition at line 290 of file bmesh_walkers_impl.c.
References BMwIslandboundWalker::base, BLI_ghash_haskey(), BLI_ghash_insert(), BMWalker::bm, BM_edge_other_vert(), BM_face_other_edge_loop(), BM_vert_is_manifold(), BMERR_WALKER_FAILED, BMO_error_raise(), BMW_current_state(), bmw_mask_check_face(), BMW_reset(), BMW_state_add(), BMW_state_remove(), BMwIslandboundWalker::curloop, BMLoop::e, BMLoop::f, BMwIslandboundWalker::lastv, NULL, BMLoop::radial_next, and BMWalker::visithash.
static void* bmw_IslandboundWalker_yield (BMWalker * walker) [static]
Definition at line 283 of file bmesh_walkers_impl.c.
References BMW_current_state(), and BMwIslandboundWalker::curloop.
static void bmw_IslandWalker_begin (BMWalker * walker, void * data) [static]
Island Walker:
Starts at a tool flagged-face and walks over the face region
Todo:
Add restriction flag/callback for wire edges.
Definition at line 362 of file bmesh_walkers_impl.c.
References BLI_ghash_insert(), bmw_mask_check_face(), BMW_state_add(), BMwIslandWalker::cur, data, NULL, and BMWalker::visithash.
static void* bmw_IslandWalker_step (BMWalker * walker) [static]
Definition at line 383 of file bmesh_walkers_impl.c.
References BLI_ghash_haskey(), BLI_ghash_insert(), BMWalker::bm, BM_FACES_OF_EDGE, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BMW_current_state(), bmw_mask_check_edge(), bmw_mask_check_face(), BMW_state_add(), BMW_state_remove(), BMwIslandWalker::cur, BMLoop::e, NULL, and BMWalker::visithash.
static void* bmw_IslandWalker_yield (BMWalker * walker) [static]
Definition at line 376 of file bmesh_walkers_impl.c.
References BMW_current_state(), and BMwIslandWalker::cur.
static void bmw_LoopWalker_begin (BMWalker * walker, void * data) [static]
Edge Loop Walker:
Starts at a tool-flagged edge and walks over the edge loop
Definition at line 427 of file bmesh_walkers_impl.c.
References BLI_ghash_free(), BLI_ghash_insert(), BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BM_edge_is_boundary(), BM_edge_other_vert(), BM_FACES_OF_EDGE, BM_ITER_ELEM, BM_vert_edge_count_nonwire(), BMW_current_state(), BMW_state_add(), BMW_walk(), BMwLoopWalker::cur, data, BMwLoopWalker::f_hub, FALSE, BMwLoopWalker::is_boundary, BMwLoopWalker::is_single, BMwLoopWalker::lastv, BMFace::len, NULL, BMwLoopWalker::start, BMwLoopWalker::startv, BMEdge::v1, BMEdge::v2, and BMWalker::visithash.
static void* bmw_LoopWalker_step (BMWalker * walker) [static]
Definition at line 496 of file bmesh_walkers_impl.c.
References BLI_ghash_haskey(), BLI_ghash_insert(), BM_edge_exists(), BM_edge_is_boundary(), BM_edge_other_vert(), BM_EDGES_OF_VERT, BM_face_other_edge_loop(), BM_face_other_vert_loop(), BM_ITER_ELEM, BM_vert_edge_count_nonwire(), BMW_current_state(), bmw_mask_check_edge(), BMW_state_add(), BMW_state_remove(), BMwLoopWalker::cur, BMLoop::e, BMLoop::f, BMwLoopWalker::f_hub, FALSE, i, BMwLoopWalker::is_boundary, BMwLoopWalker::is_single, BMEdge::l, BMwLoopWalker::lastv, NULL, BMLoop::radial_next, TRUE, BMLoop::v, BMEdge::v1, BMEdge::v2, and BMWalker::visithash.
static void* bmw_LoopWalker_yield (BMWalker * walker) [static]
Definition at line 489 of file bmesh_walkers_impl.c.
References BMW_current_state(), and BMwLoopWalker::cur.
static int bmw_mask_check_edge (BMWalker * walker, BMEdge * e) [static]
Definition at line 50 of file bmesh_walkers_impl.c.
References BMWalker::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BMO_elem_flag_test, BMW_FLAG_TEST_HIDDEN, FALSE, BMWalker::flag, BMWalker::mask_edge, and TRUE.
Referenced by bmw_IslandWalker_step(), bmw_LoopWalker_step(), bmw_ShellWalker_visitEdge(), and bmw_UVEdgeWalker_step().
static int bmw_mask_check_face (BMWalker * walker, BMFace * f) [static]
Definition at line 63 of file bmesh_walkers_impl.c.
References BMWalker::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BMO_elem_flag_test, BMW_FLAG_TEST_HIDDEN, FALSE, BMWalker::flag, BMWalker::mask_face, and TRUE.
Referenced by bmw_EdgeringWalker_step(), bmw_FaceLoopWalker_include_face(), bmw_IslandboundWalker_step(), bmw_IslandWalker_begin(), and bmw_IslandWalker_step().
static int bmw_mask_check_vert (BMWalker * walker, BMVert * v) [static]
Definition at line 37 of file bmesh_walkers_impl.c.
References BMWalker::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BMO_elem_flag_test, BMW_FLAG_TEST_HIDDEN, FALSE, BMWalker::flag, BMWalker::mask_vert, and TRUE.
Referenced by bmw_ConnectedVertexWalker_visitVertex().
static void bmw_ShellWalker_begin (BMWalker * walker, void * data) [static]
Definition at line 101 of file bmesh_walkers_impl.c.
References BM_EDGE, BM_EDGES_OF_VERT, BM_ITER_ELEM, BM_VERT, bmw_ShellWalker_visitEdge(), data, BMHeader::htype, NULL, and UNLIKELY.
static void* bmw_ShellWalker_step (BMWalker * walker) [static]
Definition at line 141 of file bmesh_walkers_impl.c.
References BM_EDGES_OF_VERT, BM_ITER_ELEM, BMW_current_state(), bmw_ShellWalker_visitEdge(), BMW_state_remove(), BMwShellWalker::curedge, i, BMEdge::v1, and BMEdge::v2.
static void bmw_ShellWalker_visitEdge (BMWalker * walker, BMEdge * e) [static]
Shell Walker:
Starts at a vertex on the mesh and walks over the 'shell' it belongs to via visiting connected edges.
Todo:
Add restriction flag/callback for wire edges.
Definition at line 84 of file bmesh_walkers_impl.c.
References BLI_ghash_haskey(), BLI_ghash_insert(), bmw_mask_check_edge(), BMW_state_add(), BMwShellWalker::curedge, NULL, and BMWalker::visithash.
Referenced by bmw_ShellWalker_begin(), and bmw_ShellWalker_step().
static void* bmw_ShellWalker_yield (BMWalker * walker) [static]
Definition at line 135 of file bmesh_walkers_impl.c.
References BMW_current_state(), and BMwShellWalker::curedge.
static void bmw_UVEdgeWalker_begin (BMWalker * walker, void * data) [static]
Definition at line 910 of file bmesh_walkers_impl.c.
References BLI_ghash_haskey(), BLI_ghash_insert(), BMW_state_add(), data, BMwUVEdgeWalker::l, NULL, and BMWalker::visithash.
static void* bmw_UVEdgeWalker_step (BMWalker * walker) [static]
Definition at line 934 of file bmesh_walkers_impl.c.
References BLI_ghash_haskey(), BLI_ghash_insert(), BMWalker::bm, BM_edge_face_count(), BM_ITER_ELEM, BM_LOOPS_OF_VERT, BMW_current_state(), bmw_mask_check_edge(), BMW_state_add(), BMW_state_remove(), CustomData_bmesh_get_layer_n(), CustomData_data_equals(), BMHeader::data, BMLoop::e, BMLoop::head, i, BMwUVEdgeWalker::l, BMWalker::layer, CustomData::layers, BMesh::ldata, BMLoop::next, NULL, BMLoop::radial_next, CustomDataLayer::type, BMLoop::v, and BMWalker::visithash.
static void* bmw_UVEdgeWalker_yield (BMWalker * walker) [static]
Definition at line 923 of file bmesh_walkers_impl.c.
References BMW_current_state(), BMwUVEdgeWalker::l, and NULL.
Variable Documentation
const int bm_totwalkers = sizeof(bm_walker_types) / sizeof(*bm_walker_types)
Definition at line 1075 of file bmesh_walkers_impl.c.
BMWalker* bm_walker_types[]
Initial value:
 {
    &bmw_ShellWalker_Type,
    &bmw_LoopWalker_Type,
    &bmw_FaceLoopWalker_Type,
    &bmw_EdgeringWalker_Type,
    &bmw_UVEdgeWalker_Type,
    &bmw_IslandboundWalker_Type,
    &bmw_IslandWalker_Type,
    &bmw_ConnectedVertexWalker_Type,
}
Definition at line 1064 of file bmesh_walkers_impl.c.
Referenced by BMW_init().
BMWalker bmw_ConnectedVertexWalker_Type [static]
Initial value:
 {
    bmw_ConnectedVertexWalker_begin,
    bmw_ConnectedVertexWalker_step,
    bmw_ConnectedVertexWalker_yield,
    sizeof(BMwConnectedVertexWalker),
    BMW_BREADTH_FIRST,
    BM_VERT,
}
Definition at line 1055 of file bmesh_walkers_impl.c.
BMWalker bmw_EdgeringWalker_Type [static]
Initial value:
 {
    bmw_EdgeringWalker_begin,
    bmw_EdgeringWalker_step,
    bmw_EdgeringWalker_yield,
    sizeof(BMwEdgeringWalker),
    BMW_DEPTH_FIRST,
    0,
}
Definition at line 1037 of file bmesh_walkers_impl.c.
BMWalker bmw_FaceLoopWalker_Type [static]
Initial value:
 {
    bmw_FaceLoopWalker_begin,
    bmw_FaceLoopWalker_step,
    bmw_FaceLoopWalker_yield,
    sizeof(BMwFaceLoopWalker),
    BMW_DEPTH_FIRST,
    0,
}
Definition at line 1028 of file bmesh_walkers_impl.c.
BMWalker bmw_IslandboundWalker_Type [static]
Initial value:
 {
    bmw_IslandboundWalker_begin,
    bmw_IslandboundWalker_step,
    bmw_IslandboundWalker_yield,
    sizeof(BMwIslandboundWalker),
    BMW_DEPTH_FIRST,
    BM_FACE,
}
Definition at line 1001 of file bmesh_walkers_impl.c.
BMWalker bmw_IslandWalker_Type [static]
Initial value:
 {
    bmw_IslandWalker_begin,
    bmw_IslandWalker_step,
    bmw_IslandWalker_yield,
    sizeof(BMwIslandWalker),
    BMW_BREADTH_FIRST,
    BM_EDGE | BM_FACE,
}
Definition at line 1010 of file bmesh_walkers_impl.c.
BMWalker bmw_LoopWalker_Type [static]
Initial value:
 {
    bmw_LoopWalker_begin,
    bmw_LoopWalker_step,
    bmw_LoopWalker_yield,
    sizeof(BMwLoopWalker),
    BMW_DEPTH_FIRST,
    0,
}
Definition at line 1019 of file bmesh_walkers_impl.c.
BMWalker bmw_ShellWalker_Type [static]
Initial value:
 {
    bmw_ShellWalker_begin,
    bmw_ShellWalker_step,
    bmw_ShellWalker_yield,
    sizeof(BMwShellWalker),
    BMW_BREADTH_FIRST,
    BM_EDGE,
}
Definition at line 992 of file bmesh_walkers_impl.c.
BMWalker bmw_UVEdgeWalker_Type [static]
Initial value:
 {
    bmw_UVEdgeWalker_begin,
    bmw_UVEdgeWalker_step,
    bmw_UVEdgeWalker_yield,
    sizeof(BMwUVEdgeWalker),
    BMW_DEPTH_FIRST,
    BM_EDGE,
}
Definition at line 1046 of file bmesh_walkers_impl.c.