Blender: PHY_IPhysicsController Class Reference
PHY_IPhysicsController Class Reference
#include <PHY_IPhysicsController.h>
Public Member Functions
virtual ~PHY_IPhysicsController ()
virtual bool SynchronizeMotionStates (float time)=0
virtual void WriteMotionStateToDynamics (bool nondynaonly)=0
virtual void WriteDynamicsToMotionState ()=0
virtual class PHY_IMotionState * GetMotionState ()=0
virtual void PostProcessReplica (class PHY_IMotionState *motionstate, class PHY_IPhysicsController *parentctrl)=0
virtual void RelativeTranslate (float dlocX, float dlocY, float dlocZ, bool local)=0
virtual void RelativeRotate (const float drot[12], bool local)=0
virtual void getOrientation (float &quatImag0, float &quatImag1, float &quatImag2, float &quatReal)=0
virtual void setOrientation (float quatImag0, float quatImag1, float quatImag2, float quatReal)=0
virtual void setPosition (float posX, float posY, float posZ)=0
virtual void getPosition (PHY__Vector3 &pos) const =0
virtual void setScaling (float scaleX, float scaleY, float scaleZ)=0
virtual void ApplyTorque (float torqueX, float torqueY, float torqueZ, bool local)=0
virtual void ApplyForce (float forceX, float forceY, float forceZ, bool local)=0
virtual void SetAngularVelocity (float ang_velX, float ang_velY, float ang_velZ, bool local)=0
virtual void SetLinearVelocity (float lin_velX, float lin_velY, float lin_velZ, bool local)=0
virtual void resolveCombinedVelocities (float linvelX, float linvelY, float linvelZ, float angVelX, float angVelY, float angVelZ)=0
virtual void applyImpulse (float attachX, float attachY, float attachZ, float impulseX, float impulseY, float impulseZ)=0
virtual void SetActive (bool active)=0
virtual void GetLinearVelocity (float &linvX, float &linvY, float &linvZ)=0
virtual void GetVelocity (const float posX, const float posY, const float posZ, float &linvX, float &linvY, float &linvZ)=0
virtual void getReactionForce (float &forceX, float &forceY, float &forceZ)=0
virtual void setRigidBody (bool rigid)=0
virtual PHY_IPhysicsController * GetReplica ()
virtual void calcXform ()=0
virtual void SetMargin (float margin)=0
virtual float GetMargin () const =0
virtual float GetRadius () const =0
virtual void SetRadius (float margin)=0
virtual float GetLinVelocityMin () const =0
virtual void SetLinVelocityMin (float val)=0
virtual float GetLinVelocityMax () const =0
virtual void SetLinVelocityMax (float val)=0
PHY__Vector3 GetWorldPosition (PHY__Vector3 &localpos)
Detailed Description
PHY_IPhysicsController is the abstract simplified Interface to a physical object. It contains the IMotionState and IDeformableMesh Interfaces.
Definition at line 44 of file PHY_IPhysicsController.h.
Constructor & Destructor Documentation
PHY_IPhysicsController::~PHY_IPhysicsController () [virtual]
Definition at line 34 of file PHY_IPhysicsController.cpp.
Member Function Documentation
virtual void PHY_IPhysicsController::ApplyForce (float forceX, float forceY, float forceZ, bool local) [pure virtual]
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::applyImpulse (float attachX, float attachY, float attachZ, float impulseX, float impulseY, float impulseZ) [pure virtual]
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::ApplyTorque (float torqueX, float torqueY, float torqueZ, bool local) [pure virtual]
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::calcXform () [pure virtual]
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::GetLinearVelocity (float & linvX, float & linvY, float & linvZ) [pure virtual]
Implemented in CcdPhysicsController.
virtual float PHY_IPhysicsController::GetLinVelocityMax () const [pure virtual]
Implemented in CcdPhysicsController.
virtual float PHY_IPhysicsController::GetLinVelocityMin () const [pure virtual]
Implemented in CcdPhysicsController.
virtual float PHY_IPhysicsController::GetMargin () const [pure virtual]
Implemented in CcdPhysicsController.
Referenced by KX_RayCast::RayTest().
virtual class PHY_IMotionState* PHY_IPhysicsController::GetMotionState () [pure virtual]
Implemented in CcdPhysicsController.
Referenced by KX_RadarSensor::SynchronizeTransform(), and KX_NearSensor::SynchronizeTransform().
virtual void PHY_IPhysicsController::getOrientation (float & quatImag0, float & quatImag1, float & quatImag2, float & quatReal) [pure virtual]
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::getPosition (PHY__Vector3 & pos) const [pure virtual]
Implemented in CcdPhysicsController.
virtual float PHY_IPhysicsController::GetRadius () const [pure virtual]
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::getReactionForce (float & forceX, float & forceY, float & forceZ) [pure virtual]
Implemented in CcdPhysicsController.
virtual PHY_IPhysicsController* PHY_IPhysicsController::GetReplica (void) [inline, virtual]
Reimplemented in CcdPhysicsController.
Definition at line 90 of file PHY_IPhysicsController.h.
Referenced by KX_NearSensor::ProcessReplica().
virtual void PHY_IPhysicsController::GetVelocity (const float posX, const float posY, const float posZ, float & linvX, float & linvY, float & linvZ) [pure virtual]
Implemented in CcdPhysicsController.
PHY__Vector3 PHY_IPhysicsController::GetWorldPosition (PHY__Vector3 & localpos)
virtual void PHY_IPhysicsController::PostProcessReplica (class PHY_IMotionState * motionstate, class PHY_IPhysicsController * parentctrl) [pure virtual]
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::RelativeRotate (const float drot[12], bool local) [pure virtual]
virtual void PHY_IPhysicsController::RelativeTranslate (float dlocX, float dlocY, float dlocZ, bool local) [pure virtual]
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::resolveCombinedVelocities (float linvelX, float linvelY, float linvelZ, float angVelX, float angVelY, float angVelZ) [pure virtual]
Implemented in KX_BulletPhysicsController, and CcdPhysicsController.
virtual void PHY_IPhysicsController::SetActive (bool active) [pure virtual]
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::SetAngularVelocity (float ang_velX, float ang_velY, float ang_velZ, bool local) [pure virtual]
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::SetLinearVelocity (float lin_velX, float lin_velY, float lin_velZ, bool local) [pure virtual]
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::SetLinVelocityMax (float val) [pure virtual]
Implemented in KX_BulletPhysicsController, and CcdPhysicsController.
virtual void PHY_IPhysicsController::SetLinVelocityMin (float val) [pure virtual]
Implemented in KX_BulletPhysicsController, and CcdPhysicsController.
virtual void PHY_IPhysicsController::SetMargin (float margin) [pure virtual]
Implemented in CcdPhysicsController.
Referenced by KX_NearSensor::KX_NearSensor(), and KX_NearSensor::ProcessReplica().
virtual void PHY_IPhysicsController::setOrientation (float quatImag0, float quatImag1, float quatImag2, float quatReal) [pure virtual]
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::setPosition (float posX, float posY, float posZ) [pure virtual]
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::SetRadius (float margin) [pure virtual]
Implemented in CcdPhysicsController.
Referenced by KX_NearSensor::SetPhysCtrlRadius().
virtual void PHY_IPhysicsController::setRigidBody (bool rigid) [pure virtual]
Implemented in KX_BulletPhysicsController, and CcdPhysicsController.
virtual void PHY_IPhysicsController::setScaling (float scaleX, float scaleY, float scaleZ) [pure virtual]
Implemented in CcdPhysicsController.
virtual bool PHY_IPhysicsController::SynchronizeMotionStates (float time) [pure virtual]
SynchronizeMotionStates ynchronizes dynas, kinematic and deformable entities (and do 'late binding')
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::WriteDynamicsToMotionState () [pure virtual]
Implemented in CcdPhysicsController.
virtual void PHY_IPhysicsController::WriteMotionStateToDynamics (bool nondynaonly) [pure virtual]
WriteMotionStateToDynamics ynchronizes dynas, kinematic and deformable entities (and do 'late binding')
Implemented in CcdPhysicsController.
Referenced by KX_RadarSensor::SynchronizeTransform(), and KX_NearSensor::SynchronizeTransform().
The documentation for this class was generated from the following files:
PHY_IPhysicsController.h
PHY_IPhysicsController.cpp