Blender: bmesh_py_api.h File Reference
bmesh_py_api.h File Reference
Functions
PyObject * BPyInit_bmesh (void)
Detailed Description
Definition in file bmesh_py_api.h.
Function Documentation
PyObject* BPyInit_bmesh (void)
Definition at line 128 of file bmesh_py_api.c.
References BPy_BM_init_types(), BPy_BM_init_types_customdata(), BPy_BM_init_types_meshdata(), BPy_BM_init_types_select(), BPyInit_bmesh_types(), BPyInit_bmesh_utils(), and mod().