Blender: btPersistentManifold.cpp File Reference
btPersistentManifold.cpp File Reference
#include "btPersistentManifold.h"
#include "LinearMath/btTransform.h"
Defines
#define KEEP_DEEPEST_POINT 1
Variables
btScalar gContactBreakingThreshold = btScalar(0.02)
maximum contact breaking and merging threshold
ContactDestroyedCallback gContactDestroyedCallback = 0
ContactProcessedCallback gContactProcessedCallback = 0
Define Documentation
#define KEEP_DEEPEST_POINT 1
Variable Documentation
btScalar gContactBreakingThreshold = btScalar(0.02)
maximum contact breaking and merging threshold
Definition at line 21 of file btPersistentManifold.cpp.
Referenced by btCollisionWorld::debugDrawWorld(), btCollisionDispatcher::getNewManifold(), btConvexConvexAlgorithm::processCollision(), btConvexPlaneCollisionAlgorithm::processCollision(), CcdPhysicsEnvironment::setContactBreakingTreshold(), and btCollisionWorld::updateSingleAabb().
ContactDestroyedCallback gContactDestroyedCallback = 0
Definition at line 22 of file btPersistentManifold.cpp.
ContactProcessedCallback gContactProcessedCallback = 0
Definition at line 23 of file btPersistentManifold.cpp.