Blender: attributes.h File Reference
attributes.h File Reference
elbeem
#include "utilities.h"
Classes
class AnimChannel< Scalar >
An animated attribute channel.
class ntlSetVec3f
class Attribute
class AttributeList
The list of configuration attributes.
Defines
#define DEBUG_PCHANNELS 0
output channel values? on=1/off=0
#define NTL_ATTRIBUTES_H
Functions
std::ostream & operator<< (std::ostream &os, const ntlSetVec3f &i)
ntlVec3f channelFindMaxVf (AnimChannel< ntlVec3f > channel)
ntlVec3d channelFindMaxVd (AnimChannel< ntlVec3d > channel)
int channelFindMaxi (AnimChannel< int > channel)
float channelFindMaxf (AnimChannel< float > channel)
double channelFindMaxd (AnimChannel< double > channel)
bool channelSimplifyVf (AnimChannel< ntlVec3f > &channel)
bool channelSimplifyVd (AnimChannel< ntlVec3d > &channel)
bool channelSimplifyi (AnimChannel< int > &channel)
bool channelSimplifyf (AnimChannel< float > &channel)
bool channelSimplifyd (AnimChannel< double > &channel)
Detailed Description
Definition in file attributes.h.
Define Documentation
#define DEBUG_PCHANNELS 0
output channel values? on=1/off=0
Definition at line 214 of file attributes.h.
#define NTL_ATTRIBUTES_H
Definition at line 221 of file attributes.h.
Function Documentation
double channelFindMaxd (AnimChannel< double > channel)
Definition at line 206 of file attributes.cpp.
References ABS, AnimChannel< Scalar >::accessValues(), and i.
float channelFindMaxf (AnimChannel< float > channel)
Definition at line 197 of file attributes.cpp.
References ABS, AnimChannel< Scalar >::accessValues(), and i.
int channelFindMaxi (AnimChannel< int > channel)
ntlVec3d channelFindMaxVd (AnimChannel< ntlVec3d > channel)
Definition at line 179 of file attributes.cpp.
References AnimChannel< Scalar >::accessValues(), i, and normNoSqrt().
ntlVec3f channelFindMaxVf (AnimChannel< ntlVec3f > channel)
Definition at line 170 of file attributes.cpp.
References AnimChannel< Scalar >::accessValues(), i, and normNoSqrt().
Referenced by ntlGeometryObject::initMovingPoints(), and ntlGeometryObject::initMovingPointsAnim().
bool channelSimplifyd (AnimChannel< double > & channel)
Definition at line 246 of file attributes.cpp.
bool channelSimplifyf (AnimChannel< float > & channel)
Definition at line 245 of file attributes.cpp.
bool channelSimplifyi (AnimChannel< int > & channel)
Definition at line 244 of file attributes.cpp.
bool channelSimplifyVd (AnimChannel< ntlVec3d > & channel)
Definition at line 275 of file attributes.cpp.
bool channelSimplifyVf (AnimChannel< ntlVec3f > & channel)
Definition at line 272 of file attributes.cpp.
std::ostream& operator<< (std::ostream & os, const ntlSetVec3f & i)
Definition at line 319 of file attributes.cpp.
References ntlSetVec3f::mVerts.