Blender: makesrna.c File Reference
makesrna.c File Reference
RNA
#include <float.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "MEM_guardedalloc.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_types.h"
#include "rna_internal.h"
#include <sys/stat.h>
Classes
struct RNAProcessItem
Defines
#define TMP_EXT ".tmp"
#define REN_IF_DIFF
Typedefs
typedef struct RNAProcessItem RNAProcessItem
Functions
static int file_older (const char *file1, const char *file2)
static int replace_if_different (char *tmpfile, const char *dep_files[])
static const char * rna_safe_id (const char *id)
static int cmp_struct (const void *a, const void *b)
static int cmp_property (const void *a, const void *b)
static int cmp_def_struct (const void *a, const void *b)
static int cmp_def_property (const void *a, const void *b)
static void rna_sortlist (ListBase *listbase, int(*cmp)(const void *, const void *))
static void rna_print_c_string (FILE *f, const char *str)
static void rna_print_data_get (FILE *f, PropertyDefRNA *dp)
static void rna_print_id_get (FILE *f, PropertyDefRNA *dp)
static char * rna_alloc_function_name (const char *structname, const char *propname, const char *type)
static StructRNA * rna_find_struct (const char *identifier)
static const char * rna_find_type (const char *type)
static const char * rna_find_dna_type (const char *type)
static const char * rna_type_type_name (PropertyRNA *prop)
static const char * rna_type_type (PropertyRNA *prop)
static const char * rna_type_struct (PropertyRNA *prop)
static const char * rna_parameter_type_name (PropertyRNA *parm)
static int rna_enum_bitmask (PropertyRNA *prop)
static int rna_color_quantize (PropertyRNA *prop, PropertyDefRNA *dp)
static const char * rna_function_string (void *func)
static void rna_float_print (FILE *f, float num)
static void rna_int_print (FILE *f, int num)
static char * rna_def_property_get_func (FILE *f, StructRNA *srna, PropertyRNA *prop, PropertyDefRNA *dp, const char *manualfunc)
static void rna_clamp_value_range (FILE *f, PropertyRNA *prop)
static void rna_clamp_value (FILE *f, PropertyRNA *prop, int array)
static char * rna_def_property_set_func (FILE *f, StructRNA *srna, PropertyRNA *prop, PropertyDefRNA *dp, const char *manualfunc)
static char * rna_def_property_length_func (FILE *f, StructRNA *srna, PropertyRNA *prop, PropertyDefRNA *dp, const char *manualfunc)
static char * rna_def_property_begin_func (FILE *f, StructRNA *srna, PropertyRNA *prop, PropertyDefRNA *dp, const char *manualfunc)
static char * rna_def_property_lookup_int_func (FILE *f, StructRNA *srna, PropertyRNA *prop, PropertyDefRNA *dp, const char *manualfunc, const char *nextfunc)
static char * rna_def_property_next_func (FILE *f, StructRNA *srna, PropertyRNA *prop, PropertyDefRNA *dp, const char *manualfunc)
static char * rna_def_property_end_func (FILE *f, StructRNA *srna, PropertyRNA *prop, PropertyDefRNA *dp, const char *manualfunc)
static void rna_set_raw_property (PropertyDefRNA *dp, PropertyRNA *prop)
static void rna_set_raw_offset (FILE *f, StructRNA *srna, PropertyRNA *prop)
static void rna_def_property_funcs (FILE *f, StructRNA *srna, PropertyDefRNA *dp)
static void rna_def_property_funcs_header (FILE *f, StructRNA *srna, PropertyDefRNA *dp)
static void rna_def_property_funcs_header_cpp (FILE *f, StructRNA *srna, PropertyDefRNA *dp)
static void rna_def_property_funcs_impl_cpp (FILE *f, StructRNA *srna, PropertyDefRNA *dp)
static void rna_def_function_funcs (FILE *f, StructDefRNA *dsrna, FunctionDefRNA *dfunc)
static void rna_auto_types (void)
static void rna_sort (BlenderRNA *brna)
static const char * rna_property_structname (PropertyType type)
static const char * rna_property_subtypename (PropertySubType type)
static const char * rna_property_subtype_unit (PropertySubType type)
static void rna_generate_prototypes (BlenderRNA *brna, FILE *f)
static void rna_generate_blender (BlenderRNA *brna, FILE *f)
static void rna_generate_property_prototypes (BlenderRNA *brna, StructRNA *srna, FILE *f)
static void rna_generate_parameter_prototypes (BlenderRNA *brna, StructRNA *srna, FunctionRNA *func, FILE *f)
static void rna_generate_function_prototypes (BlenderRNA *brna, StructRNA *srna, FILE *f)
static void rna_generate_static_parameter_prototypes (BlenderRNA *brna, StructRNA *srna, FunctionDefRNA *dfunc, FILE *f)
static void rna_generate_static_function_prototypes (BlenderRNA *brna, StructRNA *srna, FILE *f)
static void rna_generate_property (FILE *f, StructRNA *srna, const char *nest, PropertyRNA *prop)
static void rna_generate_struct (BlenderRNA *brna, StructRNA *srna, FILE *f)
static void rna_generate (BlenderRNA *brna, FILE *f, const char *filename, const char *api_filename)
static void rna_generate_header (BlenderRNA *brna, FILE *f)
static void rna_generate_header_cpp (BlenderRNA *brna, FILE *f)
static void make_bad_file (const char *file, int line)
static int rna_preprocess (const char *outfile)
static void mem_error_cb (const char *errorStr)
int main (int argc, char **argv)
Variables
static const char * makesrna_path = NULL
static RNAProcessItem PROCESS_ITEMS []
static const char * cpp_classes = "\n"
Detailed Description
Definition in file makesrna.c.
Define Documentation
#define REN_IF_DIFF
Value:
{                                                                         \
        FILE *file_test = fopen(orgfile, "rb");                               \
        if (file_test) {                                                      \
            fclose(file_test);                                                \
            if (fp_org) fclose(fp_org);                                       \
            if (fp_new) fclose(fp_new);                                       \
            if (remove(orgfile) != 0) {                                       \
                fprintf(stderr, "%s:%d, Remove Error (%s): \"%s\"\n",         \
                        __FILE__, __LINE__, strerror(errno), orgfile);        \
                return -1;                                                    \
            }                                                                 \
        }                                                                     \
    }                                                                         \
    if (rename(tmpfile, orgfile) != 0) {                                      \
        fprintf(stderr, "%s:%d, Rename Error (%s): \"%s\" -> \"%s\"\n",       \
                __FILE__, __LINE__, strerror(errno), tmpfile, orgfile);       \
        return -1;                                                            \
    }                                                                         \
    remove(tmpfile);                                                          \
    return 1                                                                  \
Referenced by replace_if_different().
#define TMP_EXT ".tmp"
Definition at line 55 of file makesrna.c.
Referenced by replace_if_different(), and rna_preprocess().
Typedef Documentation
typedef struct RNAProcessItem RNAProcessItem
Function Documentation
static int cmp_def_property (const void * a, const void * b) [static]
Definition at line 244 of file makesrna.c.
References cmp_property(), and PropertyDefRNA::prop.
Referenced by rna_sort().
static int cmp_def_struct (const void * a, const void * b) [static]
Definition at line 236 of file makesrna.c.
References cmp_struct(), and StructDefRNA::srna.
Referenced by rna_sort().
static int cmp_property (const void * a, const void * b) [static]
Definition at line 222 of file makesrna.c.
References PropertyRNA::identifier, and PropertyRNA::name.
Referenced by cmp_def_property(), and rna_sort().
static int cmp_struct (const void * a, const void * b) [static]
Definition at line 214 of file makesrna.c.
References StructRNA::identifier.
Referenced by cmp_def_struct(), and rna_sort().
static int file_older (const char * file1, const char * file2) [static]
Definition at line 60 of file makesrna.c.
Referenced by replace_if_different().
int main (int argc, char ** argv)
Definition at line 3111 of file makesrna.c.
References makesrna_path, mem_error_cb(), MEM_get_memory_blocks_in_use(), MEM_printmemlist(), MEM_set_error_callback(), rna_preprocess(), and totblock.
static void make_bad_file (const char * file, int line) [static]
Definition at line 2984 of file makesrna.c.
Referenced by rna_preprocess().
static void mem_error_cb (const char * errorStr) [static]
Definition at line 3105 of file makesrna.c.
Referenced by main().
static int replace_if_different (char * tmpfile, const char * dep_files[]) [static]
Definition at line 72 of file makesrna.c.
References file_older(), fseek, ftell, L, makesrna_path, MEM_freeN(), MEM_mallocN(), NULL, REN_IF_DIFF, strlen(), and TMP_EXT.
Referenced by rna_preprocess().
static char* rna_alloc_function_name (const char * structname, const char * propname, const char * type) [static]
Definition at line 318 of file makesrna.c.
References BlenderDefRNA::allocs, DefRNA, AllocDefRNA::mem, MEM_callocN(), rna_addtail(), snprintf, and strlen().
Referenced by rna_def_function_funcs(), rna_def_property_begin_func(), rna_def_property_end_func(), rna_def_property_funcs_header(), rna_def_property_get_func(), rna_def_property_length_func(), rna_def_property_lookup_int_func(), rna_def_property_next_func(), and rna_def_property_set_func().
static void rna_auto_types (void) [static]
Definition at line 1854 of file makesrna.c.
References StructDefRNA::cont, DefRNA, StructDefRNA::dnaname, PropertyDefRNA::dnastructname, PropertyDefRNA::dnatype, ListBase::first, PropertyRNA::flag, PointerPropertyRNA::get, CollectionPropertyRNA::get, if(), CollectionPropertyRNA::item_type, ContainerDefRNA::next, PropertyDefRNA::next, PropertyDefRNA::prop, PROP_COLLECTION, PROP_ID_REFCOUNT, PROP_POINTER, ContainerDefRNA::properties, PointerPropertyRNA::property, rna_find_struct(), rna_find_type(), STRUCT_ID_REFCOUNT, BlenderDefRNA::structs, PointerPropertyRNA::type, and PropertyRNA::type.
Referenced by rna_preprocess().
static void rna_clamp_value (FILE * f, PropertyRNA * prop, int array) [static]
Definition at line 714 of file makesrna.c.
References FLT_MAX, IntPropertyRNA::hardmax, FloatPropertyRNA::hardmax, FloatPropertyRNA::hardmin, IntPropertyRNA::hardmin, PROP_FLOAT, PROP_INT, FloatPropertyRNA::range, IntPropertyRNA::range, rna_float_print(), rna_int_print(), and PropertyRNA::type.
Referenced by rna_def_property_set_func().
static void rna_clamp_value_range (FILE * f, PropertyRNA * prop) [static]
Definition at line 693 of file makesrna.c.
References PROP_FLOAT, PROP_INT, FloatPropertyRNA::range, IntPropertyRNA::range, rna_function_string(), and PropertyRNA::type.
Referenced by rna_def_property_set_func().
static int rna_color_quantize (PropertyRNA * prop, PropertyDefRNA * dp) [static]
Definition at line 453 of file makesrna.c.
References PropertyDefRNA::dnatype, IS_DNATYPE_FLOAT_COMPAT, PROP_COLOR, PROP_COLOR_GAMMA, PROP_FLOAT, PropertyRNA::subtype, and PropertyRNA::type.
Referenced by rna_def_property_get_func(), and rna_def_property_set_func().
static void rna_def_function_funcs (FILE * f, StructDefRNA * dsrna, FunctionDefRNA * dfunc) [static]
Definition at line 1652 of file makesrna.c.
References PropertyRNA::arraydimension, FunctionRNA::c_ret, FunctionDefRNA::call, FunctionDefRNA::cont, StructDefRNA::dnaname, ListBase::first, PropertyRNA::flag, FunctionRNA::flag, FunctionDefRNA::func, FUNC_NO_SELF, FUNC_USE_CONTEXT, FUNC_USE_MAIN, FUNC_USE_REPORTS, FUNC_USE_SELF_ID, FunctionDefRNA::gencall, StructRNA::identifier, FunctionRNA::identifier, PropertyRNA::identifier, PropertyDefRNA::next, NULL, PropertyDefRNA::prop, PROP_DYNAMIC, PROP_OUTPUT, PROP_POINTER, PROP_RNAPTR, PROP_STRING, PROP_THICK_WRAP, ContainerDefRNA::properties, rna_alloc_function_name(), rna_find_parameter_def(), rna_parameter_size_alloc(), rna_parameter_type_name(), rna_type_struct(), StructDefRNA::srna, and PropertyRNA::type.
Referenced by rna_generate().
static char* rna_def_property_begin_func (FILE * f, StructRNA * srna, PropertyRNA * prop, PropertyDefRNA * dp, const char * manualfunc) [static]
Definition at line 1014 of file makesrna.c.
References DefRNA, PropertyDefRNA::dnalengthfixed, PropertyDefRNA::dnalengthname, PropertyDefRNA::dnaname, PropertyDefRNA::dnapointerlevel, PropertyDefRNA::dnastructname, BlenderDefRNA::error, PropertyRNA::flag, StructRNA::identifier, PropertyRNA::identifier, NULL, PROP_IDPROPERTY, rna_alloc_function_name(), rna_print_data_get(), and rna_safe_id().
Referenced by rna_def_property_funcs().
static char* rna_def_property_end_func (FILE * f, StructRNA * srna, PropertyRNA * prop, PropertyDefRNA * dp, const char * manualfunc) [static]
Definition at line 1207 of file makesrna.c.
References PropertyRNA::flag, StructRNA::identifier, PropertyRNA::identifier, NULL, PROP_IDPROPERTY, rna_alloc_function_name(), and rna_safe_id().
Referenced by rna_def_property_funcs().
static void rna_def_property_funcs (FILE * f, StructRNA * srna, PropertyDefRNA * dp) [static]
Definition at line 1262 of file makesrna.c.
References PropertyRNA::arraydimension, CollectionPropertyRNA::begin, PropertyDefRNA::booleanbit, DefRNA, PropertyDefRNA::dnalengthfixed, PropertyDefRNA::dnalengthname, PropertyDefRNA::dnatype, CollectionPropertyRNA::end, BlenderDefRNA::error, PropertyRNA::flag, IntPropertyRNA::get, PointerPropertyRNA::get, BoolPropertyRNA::get, CollectionPropertyRNA::get, EnumPropertyRNA::get, FloatPropertyRNA::get, StringPropertyRNA::get, BoolPropertyRNA::getarray, FloatPropertyRNA::getarray, IntPropertyRNA::getarray, StructRNA::identifier, PropertyRNA::identifier, if(), CollectionPropertyRNA::item_type, CollectionPropertyRNA::length, StringPropertyRNA::length, CollectionPropertyRNA::lookupint, CollectionPropertyRNA::next, PropertyDefRNA::prop, PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_FLOAT, PROP_IDPROPERTY, PROP_INT, PROP_POINTER, PROP_RAW_ARRAY, PROP_STRING, rna_def_property_begin_func(), rna_def_property_end_func(), rna_def_property_get_func(), rna_def_property_length_func(), rna_def_property_lookup_int_func(), rna_def_property_next_func(), rna_def_property_set_func(), rna_set_raw_property(), PointerPropertyRNA::set, BoolPropertyRNA::set, EnumPropertyRNA::set, FloatPropertyRNA::set, IntPropertyRNA::set, StringPropertyRNA::set, FloatPropertyRNA::setarray, IntPropertyRNA::setarray, BoolPropertyRNA::setarray, PointerPropertyRNA::type, and PropertyRNA::type.
Referenced by rna_generate().
static void rna_def_property_funcs_header (FILE * f, StructRNA * srna, PropertyDefRNA * dp) [static]
Definition at line 1399 of file makesrna.c.
References PropertyRNA::arraydimension, PropertyRNA::flag, i, StructRNA::identifier, PropertyRNA::identifier, EnumPropertyItem::identifier, EnumPropertyRNA::item, StringPropertyRNA::maxlength, PropertyDefRNA::prop, PROP_BOOLEAN, PROP_BUILTIN, PROP_COLLECTION, PROP_ENUM, PROP_FLOAT, PROP_IDPROPERTY, PROP_INT, PROP_POINTER, PROP_STRING, rna_alloc_function_name(), rna_safe_id(), PropertyRNA::totarraylength, EnumPropertyRNA::totitem, PropertyRNA::type, and EnumPropertyItem::value.
Referenced by rna_generate_header().
static void rna_def_property_funcs_header_cpp (FILE * f, StructRNA * srna, PropertyDefRNA * dp) [static]
Definition at line 1495 of file makesrna.c.
References PropertyRNA::arraydimension, PropertyRNA::description, PropertyRNA::flag, i, PropertyRNA::identifier, StructRNA::identifier, EnumPropertyItem::identifier, if(), EnumPropertyRNA::item, CollectionPropertyRNA::item_type, PropertyRNA::name, PropertyDefRNA::prop, PROP_BOOLEAN, PROP_BUILTIN, PROP_COLLECTION, PROP_ENUM, PROP_FLOAT, PROP_IDPROPERTY, PROP_INT, PROP_POINTER, PROP_STRING, rna_safe_id(), PropertyRNA::totarraylength, EnumPropertyRNA::totitem, PointerPropertyRNA::type, PropertyRNA::type, and EnumPropertyItem::value.
Referenced by rna_generate_header_cpp().
static void rna_def_property_funcs_impl_cpp (FILE * f, StructRNA * srna, PropertyDefRNA * dp) [static]
Definition at line 1580 of file makesrna.c.
References PropertyRNA::arraydimension, PropertyRNA::flag, StructRNA::identifier, PropertyRNA::identifier, if(), PropertyDefRNA::prop, PROP_BOOLEAN, PROP_BUILTIN, PROP_COLLECTION, PROP_ENUM, PROP_FLOAT, PROP_IDPROPERTY, PROP_INT, PROP_POINTER, PROP_STRING, rna_safe_id(), PropertyRNA::totarraylength, PointerPropertyRNA::type, and PropertyRNA::type.
Referenced by rna_generate_header_cpp().
static char* rna_def_property_get_func (FILE * f, StructRNA * srna, PropertyRNA * prop, PropertyDefRNA * dp, const char * manualfunc) [static]
Definition at line 480 of file makesrna.c.
References PropertyRNA::arraydimension, PropertyDefRNA::booleanbit, PropertyDefRNA::booleannegative, DefRNA, PropertyDefRNA::dnaarraylength, PropertyDefRNA::dnaname, PropertyDefRNA::dnapointerlevel, PropertyDefRNA::dnastructname, PropertyDefRNA::dnatype, PropertyDefRNA::enumbitflags, BlenderDefRNA::error, PropertyRNA::flag, StructRNA::identifier, PropertyRNA::identifier, IS_DNATYPE_FLOAT_COMPAT, IS_DNATYPE_INT_COMPAT, CollectionPropertyRNA::item_type, StringPropertyRNA::maxlength, MEM_freeN(), NULL, PROP_BOOLEAN, PROP_BYTESTRING, PROP_COLLECTION, PROP_COLOR_GAMMA, PROP_DIRPATH, PROP_DYNAMIC, PROP_ENUM, PROP_FILENAME, PROP_FILEPATH, PROP_FLOAT, PROP_IDPROPERTY, PROP_INT, PROP_NEVER_NULL, PROP_POINTER, PROP_STRING, rna_alloc_function_name(), rna_color_quantize(), rna_enum_bitmask(), rna_int_print(), rna_print_data_get(), RNA_property_typename(), rna_safe_id(), rna_type_type(), PropertyRNA::subtype, PropertyRNA::totarraylength, PointerPropertyRNA::type, and PropertyRNA::type.
Referenced by rna_def_property_funcs().
static char* rna_def_property_length_func (FILE * f, StructRNA * srna, PropertyRNA * prop, PropertyDefRNA * dp, const char * manualfunc) [static]
Definition at line 950 of file makesrna.c.
References DefRNA, PropertyDefRNA::dnalengthfixed, PropertyDefRNA::dnalengthname, PropertyDefRNA::dnaname, PropertyDefRNA::dnastructname, BlenderDefRNA::error, PropertyRNA::flag, StructRNA::identifier, PropertyRNA::identifier, NULL, PROP_COLLECTION, PROP_IDPROPERTY, PROP_NEVER_NULL, PROP_STRING, rna_alloc_function_name(), rna_print_data_get(), rna_safe_id(), and PropertyRNA::type.
Referenced by rna_def_property_funcs().
static char* rna_def_property_lookup_int_func (FILE * f, StructRNA * srna, PropertyRNA * prop, PropertyDefRNA * dp, const char * manualfunc, const char * nextfunc) [static]
Definition at line 1076 of file makesrna.c.
References PropertyDefRNA::dnalengthfixed, PropertyDefRNA::dnalengthname, PropertyDefRNA::dnaname, PropertyDefRNA::dnapointerlevel, PropertyDefRNA::dnastructname, PropertyRNA::flag, StructRNA::identifier, PropertyRNA::identifier, NULL, PROP_IDPROPERTY, rna_alloc_function_name(), rna_print_data_get(), and rna_safe_id().
Referenced by rna_def_property_funcs().
static char* rna_def_property_next_func (FILE * f, StructRNA * srna, PropertyRNA * prop, PropertyDefRNA * dp, const char * manualfunc) [static]
Definition at line 1180 of file makesrna.c.
References PropertyRNA::flag, StructRNA::identifier, PropertyRNA::identifier, NULL, PROP_IDPROPERTY, rna_alloc_function_name(), and rna_safe_id().
Referenced by rna_def_property_funcs().
static char* rna_def_property_set_func (FILE * f, StructRNA * srna, PropertyRNA * prop, PropertyDefRNA * dp, const char * manualfunc) [static]
Definition at line 755 of file makesrna.c.
References PropertyRNA::arraydimension, PropertyDefRNA::booleanbit, PropertyDefRNA::booleannegative, DefRNA, PropertyDefRNA::dnaarraylength, PropertyDefRNA::dnaname, PropertyDefRNA::dnastructname, PropertyDefRNA::dnatype, PropertyDefRNA::enumbitflags, BlenderDefRNA::error, PropertyRNA::flag, StructRNA::identifier, PropertyRNA::identifier, StringPropertyRNA::maxlength, MEM_freeN(), NULL, PropertyDefRNA::prop, PROP_BOOLEAN, PROP_BYTESTRING, PROP_DIRPATH, PROP_DYNAMIC, PROP_EDITABLE, PROP_ENUM, PROP_FILENAME, PROP_FILEPATH, PROP_ID_REFCOUNT, PROP_ID_SELF_CHECK, PROP_IDPROPERTY, PROP_NEVER_NULL, PROP_POINTER, PROP_STRING, rna_alloc_function_name(), rna_clamp_value(), rna_clamp_value_range(), rna_color_quantize(), rna_enum_bitmask(), rna_find_struct(), rna_int_print(), rna_print_data_get(), rna_print_id_get(), rna_safe_id(), rna_type_type(), STRUCT_ID, PropertyRNA::subtype, PropertyRNA::totarraylength, PointerPropertyRNA::type, and PropertyRNA::type.
Referenced by rna_def_property_funcs().
static int rna_enum_bitmask (PropertyRNA * prop) [static]
Definition at line 439 of file makesrna.c.
References EnumPropertyItem::identifier, EnumPropertyRNA::item, EnumPropertyRNA::totitem, and EnumPropertyItem::value.
Referenced by rna_def_property_get_func(), and rna_def_property_set_func().
static const char* rna_find_dna_type (const char * type) [static]
Definition at line 357 of file makesrna.c.
References StructDefRNA::cont, DefRNA, StructDefRNA::dnaname, ListBase::first, StructRNA::identifier, ContainerDefRNA::next, NULL, StructDefRNA::srna, and BlenderDefRNA::structs.
Referenced by rna_parameter_type_name().
static StructRNA* rna_find_struct (const char * identifier) [static]
Definition at line 335 of file makesrna.c.
References StructDefRNA::cont, DefRNA, ListBase::first, StructRNA::identifier, ContainerDefRNA::next, NULL, StructDefRNA::srna, and BlenderDefRNA::structs.
Referenced by rna_auto_types(), and rna_def_property_set_func().
static const char* rna_find_type (const char * type) [static]
Definition at line 346 of file makesrna.c.
References StructDefRNA::cont, DefRNA, StructDefRNA::dnaname, ListBase::first, StructRNA::identifier, ContainerDefRNA::next, NULL, StructDefRNA::srna, and BlenderDefRNA::structs.
Referenced by rna_auto_types().
static void rna_float_print (FILE * f, float num) [static]
Definition at line 465 of file makesrna.c.
References FLT_MAX.
Referenced by rna_clamp_value(), and rna_generate_property().
static const char* rna_function_string (void * func) [static]
Definition at line 460 of file makesrna.c.
Referenced by rna_clamp_value_range(), rna_generate_property(), and rna_generate_struct().
static void rna_generate (BlenderRNA * brna, FILE * f, const char * filename, const char * api_filename) [static]
Definition at line 2682 of file makesrna.c.
References StructDefRNA::cont, FunctionDefRNA::cont, DefRNA, StructDefRNA::filename, ListBase::first, StructDefRNA::functions, ContainerDefRNA::next, PropertyDefRNA::next, ContainerDefRNA::properties, rna_def_function_funcs(), rna_def_property_funcs(), rna_generate_blender(), rna_generate_function_prototypes(), rna_generate_property_prototypes(), rna_generate_prototypes(), rna_generate_static_function_prototypes(), rna_generate_struct(), StructDefRNA::srna, and BlenderDefRNA::structs.
Referenced by rna_preprocess().
static void rna_generate_blender (BlenderRNA * brna, FILE * f) [static]
Definition at line 1988 of file makesrna.c.
References ListBase::first, StructRNA::identifier, ListBase::last, and BlenderRNA::structs.
Referenced by rna_generate().
static void rna_generate_function_prototypes (BlenderRNA * brna, StructRNA * srna, FILE * f) [static]
Definition at line 2040 of file makesrna.c.
References StructRNA::base, FunctionRNA::cont, ListBase::first, StructRNA::functions, StructRNA::identifier, FunctionRNA::identifier, ContainerRNA::next, and rna_generate_parameter_prototypes().
Referenced by rna_generate().
static void rna_generate_header (BlenderRNA * brna, FILE * f) [static]
Definition at line 2758 of file makesrna.c.
References StructRNA::base, StructDefRNA::cont, DefRNA, ListBase::first, StructRNA::identifier, StructRNA::name, ContainerDefRNA::next, PropertyDefRNA::next, ContainerDefRNA::properties, rna_def_property_funcs_header(), StructDefRNA::srna, and BlenderDefRNA::structs.
Referenced by rna_preprocess().
static void rna_generate_header_cpp (BlenderRNA * brna, FILE * f) [static]
Definition at line 2926 of file makesrna.c.
References StructRNA::base, StructDefRNA::cont, DefRNA, ListBase::first, PropertyRNA::flag, StructRNA::identifier, PropertyRNA::identifier, StructRNA::name, ContainerDefRNA::next, PropertyDefRNA::next, PropertyDefRNA::prop, PROP_BUILTIN, PROP_COLLECTION, PROP_IDPROPERTY, ContainerDefRNA::properties, rna_def_property_funcs_header_cpp(), rna_def_property_funcs_impl_cpp(), StructDefRNA::srna, BlenderDefRNA::structs, and PropertyRNA::type.
Referenced by rna_preprocess().
static void rna_generate_parameter_prototypes (BlenderRNA * brna, StructRNA * srna, FunctionRNA * func, FILE * f) [static]
Definition at line 2028 of file makesrna.c.
References FunctionRNA::cont, ListBase::first, StructRNA::identifier, FunctionRNA::identifier, PropertyRNA::identifier, PropertyRNA::next, ContainerRNA::properties, rna_property_structname(), and PropertyRNA::type.
Referenced by rna_generate_function_prototypes().
static void rna_generate_property (FILE * f, StructRNA * srna, const char * nest, PropertyRNA * prop) [static]
Definition at line 2192 of file makesrna.c.
References PropertyRNA::arraydimension, PropertyRNA::arraylength, CollectionPropertyRNA::assignint, CollectionPropertyRNA::begin, BoolPropertyRNA::defaultarray, IntPropertyRNA::defaultarray, FloatPropertyRNA::defaultarray, FloatPropertyRNA::defaultvalue, EnumPropertyRNA::defaultvalue, IntPropertyRNA::defaultvalue, StringPropertyRNA::defaultvalue, BoolPropertyRNA::defaultvalue, DefRNA, PropertyRNA::description, EnumPropertyItem::description, PropertyRNA::editable, CollectionPropertyRNA::end, BlenderDefRNA::error, PropertyRNA::flag, IntPropertyRNA::get, PointerPropertyRNA::get, BoolPropertyRNA::get, CollectionPropertyRNA::get, EnumPropertyRNA::get, FloatPropertyRNA::get, StringPropertyRNA::get, BoolPropertyRNA::getarray, FloatPropertyRNA::getarray, IntPropertyRNA::getarray, PropertyRNA::getlength, IntPropertyRNA::hardmax, FloatPropertyRNA::hardmax, FloatPropertyRNA::hardmin, IntPropertyRNA::hardmin, i, PropertyRNA::icon, EnumPropertyItem::icon, StructRNA::identifier, PropertyRNA::identifier, EnumPropertyItem::identifier, EnumPropertyRNA::item, CollectionPropertyRNA::item_type, PropertyRNA::itemeditable, EnumPropertyRNA::itemf, len(), CollectionPropertyRNA::length, StringPropertyRNA::length, CollectionPropertyRNA::lookupint, CollectionPropertyRNA::lookupstring, PropertyRNA::magic, StringPropertyRNA::maxlength, MEM_freeN(), MEM_mallocN(), PropertyRNA::name, EnumPropertyItem::name, PropertyRNA::next, CollectionPropertyRNA::next, PropertyRNA::noteflag, NULL, PointerPropertyRNA::poll, FloatPropertyRNA::precision, PropertyRNA::prev, PROP_BOOLEAN, PROP_COLLECTION, PROP_CONTEXT_UPDATE, PROP_ENUM, PROP_ENUM_FLAG, PROP_EXPORT, PROP_FLOAT, PROP_INT, PROP_POINTER, PROP_RAW_ACCESS, PROP_STRING, FloatPropertyRNA::range, IntPropertyRNA::range, rna_float_print(), rna_function_string(), rna_int_print(), rna_print_c_string(), rna_property_structname(), rna_property_subtype_unit(), rna_property_subtypename(), RNA_property_typename(), rna_set_raw_offset(), PointerPropertyRNA::set, BoolPropertyRNA::set, EnumPropertyRNA::set, FloatPropertyRNA::set, IntPropertyRNA::set, StringPropertyRNA::set, FloatPropertyRNA::setarray, IntPropertyRNA::setarray, BoolPropertyRNA::setarray, IntPropertyRNA::softmax, FloatPropertyRNA::softmax, FloatPropertyRNA::softmin, IntPropertyRNA::softmin, PropertyRNA::srna, FloatPropertyRNA::step, IntPropertyRNA::step, strlen(), PropertyRNA::subtype, PropertyRNA::totarraylength, EnumPropertyRNA::totitem, PropertyRNA::translation_context, PointerPropertyRNA::type, PropertyRNA::type, PointerPropertyRNA::typef, PropertyRNA::update, and EnumPropertyItem::value.
Referenced by rna_generate_struct().
static void rna_generate_property_prototypes (BlenderRNA * brna, StructRNA * srna, FILE * f) [static]
Definition at line 2005 of file makesrna.c.
References StructRNA::base, StructRNA::cont, ListBase::first, PropertyRNA::flag, StructRNA::identifier, PropertyRNA::identifier, PropertyRNA::next, PROP_EXPORT, ContainerRNA::properties, rna_property_structname(), and PropertyRNA::type.
Referenced by rna_generate().
static void rna_generate_prototypes (BlenderRNA * brna, FILE * f) [static]
Definition at line 1979 of file makesrna.c.
References StructRNA::cont, ListBase::first, StructRNA::identifier, ContainerRNA::next, and BlenderRNA::structs.
Referenced by rna_generate().
static void rna_generate_static_function_prototypes (BlenderRNA * brna, StructRNA * srna, FILE * f) [static]
Definition at line 2170 of file makesrna.c.
References FunctionDefRNA::call, FunctionRNA::cont, ListBase::first, StructRNA::functions, ContainerRNA::next, rna_find_function_def(), and rna_generate_static_parameter_prototypes().
Referenced by rna_generate().
static void rna_generate_static_parameter_prototypes (BlenderRNA * brna, StructRNA * srna, FunctionDefRNA * dfunc, FILE * f) [static]
Definition at line 2067 of file makesrna.c.
References PropertyRNA::arraydimension, FunctionRNA::c_ret, FunctionDefRNA::call, FunctionDefRNA::cont, StructDefRNA::dnaname, ListBase::first, PropertyRNA::flag, FunctionRNA::flag, FunctionDefRNA::func, FUNC_NO_SELF, FUNC_USE_CONTEXT, FUNC_USE_MAIN, FUNC_USE_REPORTS, FUNC_USE_SELF_ID, StructRNA::identifier, PropertyRNA::identifier, PropertyDefRNA::next, PropertyDefRNA::prop, PROP_DYNAMIC, PROP_OUTPUT, PROP_POINTER, PROP_RNAPTR, PROP_STRING, PROP_THICK_WRAP, ContainerDefRNA::properties, rna_find_struct_def(), rna_parameter_type_name(), rna_type_struct(), PropertyRNA::totarraylength, and PropertyRNA::type.
Referenced by rna_generate_static_function_prototypes().
static void rna_generate_struct (BlenderRNA * brna, StructRNA * srna, FILE * f) [static]
Definition at line 2482 of file makesrna.c.
References StructRNA::base, FunctionRNA::c_ret, FunctionRNA::cont, StructRNA::cont, DefRNA, StructRNA::description, FunctionRNA::description, BlenderDefRNA::error, ListBase::first, FunctionRNA::flag, StructRNA::flag, StructRNA::functions, FunctionDefRNA::gencall, StructRNA::icon, FunctionRNA::identifier, StructRNA::identifier, PropertyRNA::identifier, StructRNA::idproperties, StructRNA::instance, StructRNA::iteratorproperty, ListBase::last, StructRNA::name, StructRNA::nameproperty, StructRNA::nested, PropertyRNA::next, ContainerRNA::next, NULL, StructRNA::path, ContainerRNA::prev, ContainerRNA::properties, StructRNA::refine, StructRNA::reg, rna_find_function_def(), rna_function_string(), rna_generate_property(), rna_print_c_string(), StructRNA::translation_context, and StructRNA::unreg.
Referenced by rna_generate().
static void rna_int_print (FILE * f, int num) [static]
Definition at line 473 of file makesrna.c.
Referenced by rna_clamp_value(), rna_def_property_get_func(), rna_def_property_set_func(), and rna_generate_property().
static const char* rna_parameter_type_name (PropertyRNA * parm) [static]
Definition at line 413 of file makesrna.c.
References PropertyRNA::flag, PROP_COLLECTION, PROP_POINTER, PROP_RNAPTR, rna_find_dna_type(), rna_type_type_name(), PointerPropertyRNA::type, and PropertyRNA::type.
Referenced by rna_def_function_funcs(), and rna_generate_static_parameter_prototypes().
static int rna_preprocess (const char * outfile) [static]
Definition at line 2991 of file makesrna.c.
References RNAProcessItem::api_filename, StructDefRNA::cont, RNAProcessItem::define, DefRNA, BlenderDefRNA::error, RNAProcessItem::filename, StructDefRNA::filename, ListBase::first, i, make_bad_file(), ContainerDefRNA::next, NULL, replace_if_different(), rna_auto_types(), RNA_create(), RNA_define_free(), RNA_free(), rna_generate(), rna_generate_header(), rna_generate_header_cpp(), rna_sort(), strlen(), BlenderDefRNA::structs, and TMP_EXT.
Referenced by main().
static void rna_print_c_string (FILE * f, const char * str) [static]
Definition at line 282 of file makesrna.c.
References i, and NULL.
Referenced by rna_generate_property(), and rna_generate_struct().
static void rna_print_data_get (FILE * f, PropertyDefRNA * dp) [static]
Definition at line 304 of file makesrna.c.
References PropertyDefRNA::dnastructfromname, PropertyDefRNA::dnastructfromprop, and PropertyDefRNA::dnastructname.
Referenced by rna_def_property_begin_func(), rna_def_property_get_func(), rna_def_property_length_func(), rna_def_property_lookup_int_func(), and rna_def_property_set_func().
static void rna_print_id_get (FILE * f, PropertyDefRNA * dp) [static]
Definition at line 313 of file makesrna.c.
Referenced by rna_def_property_set_func().
static const char* rna_property_structname (PropertyType type) [static]
Definition at line 1908 of file makesrna.c.
References PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_POINTER, and PROP_STRING.
Referenced by rna_generate_parameter_prototypes(), rna_generate_property(), and rna_generate_property_prototypes().
static const char* rna_property_subtype_unit (PropertySubType type) [static]
Definition at line 1963 of file makesrna.c.
References PROP_UNIT_ACCELERATION, PROP_UNIT_AREA, PROP_UNIT_LENGTH, PROP_UNIT_MASS, PROP_UNIT_NONE, PROP_UNIT_ROTATION, PROP_UNIT_TIME, PROP_UNIT_VELOCITY, PROP_UNIT_VOLUME, and RNA_SUBTYPE_UNIT.
Referenced by rna_generate_property().
static const char* rna_property_subtypename (PropertySubType type) [static]
Definition at line 1922 of file makesrna.c.
References PROP_ACCELERATION, PROP_ANGLE, PROP_AXISANGLE, PROP_BYTESTRING, PROP_COLOR, PROP_COLOR_GAMMA, PROP_COORDS, PROP_DIRECTION, PROP_DIRPATH, PROP_DISTANCE, PROP_EULER, PROP_FACTOR, PROP_FILENAME, PROP_FILEPATH, PROP_LAYER, PROP_LAYER_MEMBER, PROP_MATRIX, PROP_NONE, PROP_PERCENTAGE, PROP_QUATERNION, PROP_TIME, PROP_TRANSLATE, PROP_TRANSLATION, PROP_UNSIGNED, PROP_VELOCITY, PROP_XYZ, and RNA_SUBTYPE_UNIT.
Referenced by rna_generate_property().
static const char* rna_safe_id (const char * id) [static]
Definition at line 202 of file makesrna.c.
Referenced by rna_def_property_begin_func(), rna_def_property_end_func(), rna_def_property_funcs_header(), rna_def_property_funcs_header_cpp(), rna_def_property_funcs_impl_cpp(), rna_def_property_get_func(), rna_def_property_length_func(), rna_def_property_lookup_int_func(), rna_def_property_next_func(), and rna_def_property_set_func().
static void rna_set_raw_offset (FILE * f, StructRNA * srna, PropertyRNA * prop) [static]
Definition at line 1255 of file makesrna.c.
References PropertyDefRNA::dnaname, PropertyDefRNA::dnastructname, PropertyRNA::rawtype, and rna_find_struct_property_def().
Referenced by rna_generate_property().
static void rna_set_raw_property (PropertyDefRNA * dp, PropertyRNA * prop) [static]
Definition at line 1226 of file makesrna.c.
References PropertyDefRNA::dnaname, PropertyDefRNA::dnapointerlevel, PropertyDefRNA::dnastructname, PropertyDefRNA::dnatype, PropertyRNA::flag, PROP_RAW_ACCESS, PROP_RAW_CHAR, PROP_RAW_DOUBLE, PROP_RAW_FLOAT, PROP_RAW_INT, PROP_RAW_SHORT, and PropertyRNA::rawtype.
Referenced by rna_def_property_funcs().
static void rna_sort (BlenderRNA * brna) [static]
Definition at line 1893 of file makesrna.c.
References cmp_def_property(), cmp_def_struct(), cmp_property(), cmp_struct(), StructRNA::cont, StructDefRNA::cont, DefRNA, ListBase::first, ContainerDefRNA::next, ContainerRNA::next, ContainerRNA::properties, ContainerDefRNA::properties, rna_sortlist(), BlenderRNA::structs, and BlenderDefRNA::structs.
Referenced by rna_preprocess().
static void rna_sortlist (ListBase * listbase, int(*)(const void *, const void *) cmp) [static]
Definition at line 252 of file makesrna.c.
References ListBase::first, ListBase::last, link(), MEM_freeN(), MEM_mallocN(), Link::next, NULL, Link::prev, rna_addtail(), and size().
Referenced by rna_sort().
static const char* rna_type_struct (PropertyRNA * prop) [static]
Definition at line 401 of file makesrna.c.
References rna_type_type_name().
Referenced by rna_def_function_funcs(), and rna_generate_static_parameter_prototypes().
static const char* rna_type_type (PropertyRNA * prop) [static]
Definition at line 389 of file makesrna.c.
References rna_type_type_name().
Referenced by rna_def_property_get_func(), and rna_def_property_set_func().
static const char* rna_type_type_name (PropertyRNA * prop) [static]
Definition at line 368 of file makesrna.c.
References PropertyRNA::flag, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_STRING, PROP_THICK_WRAP, and PropertyRNA::type.
Referenced by rna_parameter_type_name(), rna_type_struct(), and rna_type_type().
Variable Documentation
const char* cpp_classes = "\n" [static]
Definition at line 2807 of file makesrna.c.
const char* makesrna_path = NULL [static]
Definition at line 70 of file makesrna.c.
Referenced by main(), and replace_if_different().
RNAProcessItem PROCESS_ITEMS[] [static]
Definition at line 2620 of file makesrna.c.