Blender: view3d_ops.c File Reference
view3d_ops.c File Reference
3D view
#include <stdlib.h>
#include <math.h>
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "DNA_view3d_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_transform.h"
#include "view3d_intern.h"
Functions
void view3d_operatortypes (void)
void view3d_keymap (wmKeyConfig *keyconf)
Detailed Description
Definition in file view3d_ops.c.
Function Documentation
void view3d_keymap (wmKeyConfig * keyconf)
Definition at line 110 of file view3d_ops.c.
References ACCENTGRAVEKEY, ACTIONMOUSE, BKEY, CKEY, COMMAKEY, EIGHTKEY, EQUALKEY, EVT_TWEAK_A, FALSE, FIVEKEY, FKEY, fly_modal_keymap(), FOURKEY, HOMEKEY, KM_ALT, KM_ANY, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTMOUSE, MIDDLEMOUSE, MINUSKEY, MOUSEPAN, MOUSEROTATE, MOUSEZOOM, NDOF_BUTTON_BACK, NDOF_BUTTON_BOTTOM, NDOF_BUTTON_FIT, NDOF_BUTTON_FRONT, NDOF_BUTTON_LEFT, NDOF_BUTTON_RIGHT, NDOF_BUTTON_TOP, NDOF_MOTION, NINEKEY, NKEY, ONEKEY, PAD0, PAD1, PAD2, PAD3, PAD4, PAD5, PAD6, PAD7, PAD8, PADENTER, PADMINUS, PADPERIOD, PADPLUSKEY, PADSLASHKEY, PERIODKEY, wmKeyMapItem::ptr, RNA_boolean_set(), RNA_enum_set(), RNA_int_set(), RNA_string_set(), RV3D_VIEW_BACK, RV3D_VIEW_BOTTOM, RV3D_VIEW_CAMERA, RV3D_VIEW_FRONT, RV3D_VIEW_LEFT, RV3D_VIEW_RIGHT, RV3D_VIEW_TOP, SELECTMOUSE, SEVENKEY, SIXKEY, SKEY, SPACE_VIEW3D, SPACEKEY, THREEKEY, TIMER1, TKEY, transform_keymap_for_space(), TRUE, TWOKEY, V3D_VIEW_PANDOWN, V3D_VIEW_PANLEFT, V3D_VIEW_PANRIGHT, V3D_VIEW_PANUP, V3D_VIEW_STEPDOWN, V3D_VIEW_STEPLEFT, V3D_VIEW_STEPRIGHT, V3D_VIEW_STEPUP, viewdolly_modal_keymap(), viewmove_modal_keymap(), viewrotate_modal_keymap(), viewzoom_modal_keymap(), WHEELDOWNMOUSE, WHEELINMOUSE, WHEELOUTMOUSE, WHEELUPMOUSE, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), WM_keymap_verify_item(), ZEROKEY, and ZKEY.
Referenced by ED_spacetype_view3d().
void view3d_operatortypes (void)
Definition at line 58 of file view3d_ops.c.
References transform_operatortypes(), VIEW3D_OT_background_image_add(), VIEW3D_OT_background_image_remove(), VIEW3D_OT_camera_to_view(), VIEW3D_OT_camera_to_view_selected(), VIEW3D_OT_clip_border(), VIEW3D_OT_cursor3d(), VIEW3D_OT_dolly(), VIEW3D_OT_enable_manipulator(), VIEW3D_OT_fly(), VIEW3D_OT_game_start(), VIEW3D_OT_layers(), VIEW3D_OT_localview(), VIEW3D_OT_manipulator(), VIEW3D_OT_move(), VIEW3D_OT_ndof_orbit(), VIEW3D_OT_ndof_pan(), VIEW3D_OT_object_as_camera(), VIEW3D_OT_properties(), VIEW3D_OT_render_border(), VIEW3D_OT_rotate(), VIEW3D_OT_select(), VIEW3D_OT_select_border(), VIEW3D_OT_select_circle(), VIEW3D_OT_select_lasso(), VIEW3D_OT_select_menu(), VIEW3D_OT_smoothview(), VIEW3D_OT_snap_cursor_to_active(), VIEW3D_OT_snap_cursor_to_center(), VIEW3D_OT_snap_cursor_to_grid(), VIEW3D_OT_snap_cursor_to_selected(), VIEW3D_OT_snap_selected_to_cursor(), VIEW3D_OT_snap_selected_to_grid(), VIEW3D_OT_toolshelf(), VIEW3D_OT_view_all(), VIEW3D_OT_view_center_camera(), VIEW3D_OT_view_center_cursor(), VIEW3D_OT_view_orbit(), VIEW3D_OT_view_pan(), VIEW3D_OT_view_persportho(), VIEW3D_OT_view_selected(), VIEW3D_OT_viewnumpad(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), VIEW3D_OT_zoom_camera_1_to_1(), and WM_operatortype_append().
Referenced by ED_spacetype_view3d().