Blender: node_shader_background.c File Reference
node_shader_background.c File Reference
#include "../node_shader_util.h"
Functions
void register_node_type_sh_background (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_background_in []
static bNodeSocketTemplate sh_node_background_out []
Function Documentation
void register_node_type_sh_background (bNodeTreeType * ttype)
Definition at line 44 of file node_shader_background.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_BACKGROUND.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_background_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Color",      0.8f, 0.8f, 0.8f, 1.0f, 0.0f, 1.0f},
    {   SOCK_FLOAT, 1, "Strength",  1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1000000.0f},
    {   -1, 0, ""   }
}
Definition at line 32 of file node_shader_background.c.
bNodeSocketTemplate sh_node_background_out[] [static]
Initial value:
 {
    {   SOCK_SHADER, 0, "Background"},
    {   -1, 0, ""   }
}
Definition at line 38 of file node_shader_background.c.