Blender: GEN_Map< Key, Value > Class Template Reference
GEN_Map< Key, Value > Class Template Reference
#include <GEN_Map.h>
Classes
struct Entry
Public Member Functions
GEN_Map (int num_buckets=100)
GEN_Map (const GEN_Map &map)
int size ()
Value * at (int index)
Key * getKey (int index)
void clear ()
~GEN_Map ()
void insert (const Key &key, const Value &value)
void remove (const Key &key)
Value * operator[] (Key key)
Detailed Description
template<class Key, class Value>
class GEN_Map< Key, Value >
Definition at line 37 of file GEN_Map.h.
Constructor & Destructor Documentation
template<class Key , class Value > GEN_Map< Key, Value >::GEN_Map (int num_buckets = 100) [inline]
Definition at line 51 of file GEN_Map.h.
References i.
template<class Key , class Value > GEN_Map< Key, Value >::GEN_Map (const GEN_Map< Key, Value > & map) [inline]
Definition at line 58 of file GEN_Map.h.
References i, and GEN_Map< Key, Value >::insert().
template<class Key , class Value > GEN_Map< Key, Value >::~GEN_Map () [inline]
Definition at line 134 of file GEN_Map.h.
References GEN_Map< Key, Value >::clear().
Member Function Documentation
template<class Key , class Value > Value* GEN_Map< Key, Value >::at (int index) [inline]
Definition at line 85 of file GEN_Map.h.
References i.
template<class Key , class Value > void GEN_Map< Key, Value >::clear () [inline]
Definition at line 121 of file GEN_Map.h.
References i.
Referenced by GEN_Map< Key, Value >::~GEN_Map().
template<class Key , class Value > Key* GEN_Map< Key, Value >::getKey (int index) [inline]
Definition at line 103 of file GEN_Map.h.
References i.
template<class Key , class Value > void GEN_Map< Key, Value >::insert (const Key & key, const Value & value) [inline]
Definition at line 139 of file GEN_Map.h.
Referenced by GEN_Map< Key, Value >::GEN_Map().
template<class Key , class Value > Value* GEN_Map< Key, Value >::operator[] (Key key) [inline]
Definition at line 167 of file GEN_Map.h.
template<class Key , class Value > void GEN_Map< Key, Value >::remove (const Key & key) [inline]
Definition at line 154 of file GEN_Map.h.
template<class Key , class Value > int GEN_Map< Key, Value >::size () [inline]
Definition at line 71 of file GEN_Map.h.
References i.
The documentation for this class was generated from the following file:
GEN_Map.h