Blender: glutil.c File Reference
glutil.c File Reference
screen
#include <stdio.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_vec_types.h"
#include "BLI_utildefines.h"
#include "BKE_colortools.h"
#include "BLI_math.h"
#include "BLI_threads.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
Defines
#define GL_CLAMP_TO_EDGE 0x812F
#define glToggle(mode, onoff) (((onoff)?glEnable:glDisable)(mode))
Functions
void fdrawbezier (float vec[4][3])
void fdrawline (float x1, float y1, float x2, float y2)
void fdrawbox (float x1, float y1, float x2, float y2)
void fdrawcheckerboard (float x1, float y1, float x2, float y2)
void sdrawline (short x1, short y1, short x2, short y2)
static void sdrawtripoints (short x1, short y1, short x2, short y2)
void sdrawtri (short x1, short y1, short x2, short y2)
void sdrawtrifill (short x1, short y1, short x2, short y2)
void sdrawbox (short x1, short y1, short x2, short y2)
void setlinestyle (int nr)
void set_inverted_drawing (int enable)
void sdrawXORline (int x0, int y0, int x1, int y1)
void sdrawXORline4 (int nr, int x0, int y0, int x1, int y1)
void fdrawXORellipse (float xofs, float yofs, float hw, float hh)
void fdrawXORcirc (float xofs, float yofs, float rad)
void glutil_draw_filled_arc (float start, float angle, float radius, int nsegments)
void glutil_draw_lined_arc (float start, float angle, float radius, int nsegments)
int glaGetOneInteger (int param)
float glaGetOneFloat (int param)
void glaRasterPosSafe2f (float x, float y, float known_good_x, float known_good_y)
static int get_cached_work_texture (int *w_r, int *h_r)
void glaDrawPixelsTexScaled (float x, float y, int img_w, int img_h, int format, void *rect, float scaleX, float scaleY)
void glaDrawPixelsTex (float x, float y, int img_w, int img_h, int format, void *rect)
void glaDrawPixelsSafe (float x, float y, int img_w, int img_h, int row_w, int format, int type, void *rect)
void glaDefine2DArea (rcti *screen_rect)
void bglBegin (int mode)
void bglVertex3fv (const float vec[3])
void bglVertex3f (float x, float y, float z)
void bglVertex2fv (const float vec[2])
void bglEnd (void)
void bgl_get_mats (bglMats *mats)
void bglPolygonOffset (float viewdist, float dist)
Variables
GLubyte stipple_halftone [128]
GLubyte stipple_quarttone [128]
GLubyte stipple_diag_stripes_pos [128]
GLubyte stipple_diag_stripes_neg [128]
static int curmode = 0
static int pointhack = 0
static GLubyte Squaredot [16]
Detailed Description
Definition in file glutil.c.
Define Documentation
#define GL_CLAMP_TO_EDGE 0x812F
Definition at line 49 of file glutil.c.
Referenced by KX_Dome::CreateGLImages(), glaDrawPixelsTexScaled(), GPU_texture_create_3D(), GPU_texture_create_nD(), gpu_verify_repeat(), and BL_Texture::InitCubeMap().
#define glToggle (mode, onoff) (((onoff)?glEnable:glDisable)(mode))
Definition at line 301 of file glutil.c.
Referenced by set_inverted_drawing().
Function Documentation
void bgl_get_mats (bglMats * mats)
Definition at line 874 of file glutil.c.
References bglMats::modelview, bglMats::projection, and bglMats::viewport.
Referenced by ED_view3d_autodist(), ED_view3d_autodist_simple(), knife_bgl_get_mats(), view3d_cached_text_draw_end(), and view3d_zoom_border_exec().
void bglBegin (int mode)
Definition at line 794 of file glutil.c.
Referenced by bbs_mesh_solid_EM(), bbs_mesh_verts(), bbs_obmode_mesh_verts(), draw_dm_bweights(), draw_dm_face_centers(), draw_dm_verts(), draw_dm_verts__mapFunc(), draw_fcurve_modifier_controls_envelope(), draw_fcurve_vertices_keyframes(), draw_hooks(), draw_object(), draw_uvs(), drawshadbuflimits(), lattice_draw_verts(), tekenvertsN(), ui_draw_but_CURVE(), and vtx_slide_draw().
void bglEnd (void)
Definition at line 866 of file glutil.c.
Referenced by bbs_mesh_solid_EM(), bbs_mesh_verts(), bbs_obmode_mesh_verts(), draw_dm_bweights(), draw_dm_face_centers(), draw_dm_verts(), draw_dm_verts__mapFunc(), draw_fcurve_modifier_controls_envelope(), draw_fcurve_vertices_keyframes(), draw_hooks(), draw_object(), draw_uvs(), drawshadbuflimits(), lattice_draw_verts(), tekenvertsN(), ui_draw_but_CURVE(), and vtx_slide_draw().
void bglPolygonOffset (float viewdist, float dist)
Definition at line 899 of file glutil.c.
References glLoadMatrixf, and offs.
Referenced by draw_ebones(), draw_em_fancy(), draw_mesh_face_select(), draw_mesh_fancy(), draw_object_backbufsel(), draw_pose_bones(), drawWireExtra(), and gp_draw_strokes().
void bglVertex2fv (const float vec[2])
Definition at line 852 of file glutil.c.
Referenced by draw_uvs(), and ui_draw_but_CURVE().
void bglVertex3f (float x, float y, float z)
Definition at line 839 of file glutil.c.
void bglVertex3fv (const float vec[3])
Definition at line 826 of file glutil.c.
Referenced by bbs_mesh_solid__drawCenter(), bbs_mesh_verts__mapFunc(), bbs_obmode_mesh_verts__mapFunc(), draw_dm_bweights__mapFunc(), draw_dm_face_centers__mapFunc(), draw_dm_verts__mapFunc(), draw_fcurve_vertices_keyframes(), draw_hooks(), draw_object(), drawshadbuflimits(), lattice_draw_verts(), tekenvertsN(), and vtx_slide_draw().
void fdrawbezier (float vec[4][3])
Definition at line 132 of file glutil.c.
References ABS, cpack, and UI_ThemeColorBlend().
void fdrawbox (float x1, float y1, float x2, float y2)
Definition at line 174 of file glutil.c.
Referenced by draw_seq_extensions(), drawlamp(), drawmeta_contents(), file_draw_preview(), node_draw_preview(), ui_draw_but_COLORBAND(), ui_draw_but_CURVE(), and ui_draw_but_HSVCUBE().
void fdrawcheckerboard (float x1, float y1, float x2, float y2)
Definition at line 194 of file glutil.c.
Referenced by draw_image_buffer(), and view3d_main_area_draw_engine().
void fdrawline (float x1, float y1, float x2, float y2)
Definition at line 162 of file glutil.c.
Referenced by ANIM_channel_draw(), area_draw_azone(), draw_graph_sfra_efra(), draw_nla_channel_list_gl(), draw_nla_main_data(), draw_scope_end(), draw_seq_extensions(), drawcursor_sima(), drawgrid(), drawSnapping(), nla_draw_strip(), node_draw_hidden(), node_scaling_widget(), outliner_draw_restrictcols(), outliner_draw_rnacols(), outliner_draw_struct_marks(), radial_control_paint_cursor(), seq_draw_sfra_efra(), time_draw_sfra_efra(), ui_draw_aligned_panel(), ui_draw_anti_x(), ui_draw_but_HISTOGRAM(), ui_draw_panel_dragwidget(), ui_draw_panel_scalewidget(), and uiEmboss().
void fdrawXORcirc (float xofs, float yofs, float rad)
Definition at line 380 of file glutil.c.
References glutil_draw_lined_arc(), M_PI, and set_inverted_drawing().
void fdrawXORellipse (float xofs, float yofs, float hw, float hh)
Definition at line 366 of file glutil.c.
References glutil_draw_lined_arc(), M_PI, and set_inverted_drawing().
static int get_cached_work_texture (int * w_r, int * h_r) [static]
Definition at line 452 of file glutil.c.
References glaGetOneInteger(), MEM_callocN(), and MEM_freeN().
Referenced by glaDrawPixelsTexScaled().
void glaDefine2DArea (struct rcti * screen_rect)
Define a 2D area (viewport, scissor, matrices) for OpenGL rendering. This routine sets up an OpenGL state appropriate for drawing using both vertice (glVertex, etc) and raster (glRasterPos, glRect) commands. All coordinates should be at integer positions. There is little to no reason to use glVertex2f etc. functions during 2D rendering, and thus no reason to +-0.5 the coordinates or perform other silly tricks.
Parameters:
screen_rect The screen rectangle to be defined for 2D drawing.
Definition at line 670 of file glutil.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by draw_nodespace_back_pix().
void glaDrawPixelsSafe (float x, float y, int img_w, int img_h, int row_w, int format, int type, void * rect)
Functions like a limited glDrawPixels, except ensures that the image is displayed onscreen even if the x and y coordinates for would be clipped. The routine respects the glPixelZoom values, pixel unpacking parameters are _not_ respected.
Attention:
This routine makes many assumptions: the rect data is expected to be in RGBA unsigned byte format, the coordinate (0.375, 0.375) is assumed to be within the view frustum, and the modelview and projection matrices are assumed to define a 1-to-1 mapping to screen space.
Furthermore, in the case of zoomed or unpixel aligned images extending outside the view frustum, but still within the window, some portion of the image may be visible left and/or below of the given x and y coordinates. It is recommended to use the glScissor functionality if images are to be drawn with an inset view matrix.
Definition at line 589 of file glutil.c.
References glaGetOneFloat(), glaGetOneInteger(), glaRasterPosSafe2f(), MAX2, and MIN2.
Referenced by draw_image_buffer(), draw_image_buffer_tiled(), draw_image_paint_helpers(), draw_movieclip_buffer(), draw_nodespace_back_pix(), ed_preview_draw_rect(), icon_draw_rect(), sima_draw_alpha_pixels(), sima_draw_alpha_pixelsf(), sima_draw_zbuf_pixels(), sima_draw_zbuffloat_pixels(), ui_draw_but_IMAGE(), and ui_draw_but_TRACKPREVIEW().
void glaDrawPixelsTex (float x, float y, int img_w, int img_h, int format, void * rect)
Functions like a limited glDrawPixels, but actually draws the image using textures, which can be tremendously faster on low-end cards, and also avoids problems with the raster position being clipped when offscreen. The routine respects the glPixelZoom values, pixel unpacking parameters are _not_ respected.
Attention:
This routine makes many assumptions: the rect data is expected to be in RGBA byte or float format, and the modelview and projection matrices are assumed to define a 1-to-1 mapping to screen space.
Definition at line 584 of file glutil.c.
References glaDrawPixelsTexScaled().
Referenced by draw_bgpic(), draw_empty_image(), ED_view3d_draw_offscreen(), and node_draw_preview().
void glaDrawPixelsTexScaled (float x, float y, int img_w, int img_h, int format, void * rect, float scaleX, float scaleY)
Definition at line 481 of file glutil.c.
References get_cached_work_texture(), GL_CLAMP_TO_EDGE, glaGetOneFloat(), and glaGetOneInteger().
Referenced by file_draw_preview(), glaDrawPixelsTex(), and wm_drags_draw().
float glaGetOneFloat (int param)
Routines a float value as obtained by glGetIntegerv. The param must cause only one value to be gotten from GL.
Definition at line 428 of file glutil.c.
Referenced by glaDrawPixelsSafe(), and glaDrawPixelsTexScaled().
int glaGetOneInteger (int param)
Routines an integer value as obtained by glGetIntegerv. The param must cause only one value to be gotten from GL.
Definition at line 421 of file glutil.c.
References i.
Referenced by draw_image_seq(), get_cached_work_texture(), glaDrawPixelsSafe(), and glaDrawPixelsTexScaled().
void glaRasterPosSafe2f (float x, float y, float known_good_x, float known_good_y)
Functions like glRasterPos2i, except ensures that the resulting raster position is valid. known_good_x and known_good_y should be coordinates of a point known to be within the current view frustum.
Attention:
This routine should be used when the distance of x and y away from the known good point is small (ie. for small icons and for bitmap characters), when drawing large+zoomed images it is possible for overflow to occur, the glaDrawPixelsSafe routine should be used instead.
Definition at line 435 of file glutil.c.
Referenced by glaDrawPixelsSafe().
void glutil_draw_filled_arc (float start, float angle, float radius, int nsegments)
Draw a filled arc with the given radius, starting at angle start and arcing through angle. The arc is centered at the origin and drawn in the XY plane.
Parameters:
start The initial angle (in radians).
angle The length of the arc (in radians).
radius The arc radius.
nsegments The number of segments to use in drawing the arc.
Definition at line 392 of file glutil.c.
References angle(), cosf, i, and sinf.
Referenced by radial_control_paint_tex(), ui_hsv_cursor(), and wm_gesture_draw_circle().
void glutil_draw_lined_arc (float start, float angle, float radius, int nsegments)
Draw a lined (non-looping) arc with the given radius, starting at angle start and arcing through angle. The arc is centered at the origin and drawn in the XY plane.
Parameters:
start The initial angle (in radians).
angle The length of the arc (in radians).
radius The arc radius.
nsegments The number of segments to use in drawing the arc.
Definition at line 407 of file glutil.c.
References angle(), cosf, i, and sinf.
Referenced by brush_drawcursor(), fdrawXORcirc(), fdrawXORellipse(), paint_draw_cursor(), radial_control_paint_cursor(), ui_draw_but_HSVCIRCLE(), ui_draw_but_NORMAL(), ui_hsv_cursor(), and wm_gesture_draw_circle().
void sdrawbox (short x1, short y1, short x2, short y2)
Definition at line 264 of file glutil.c.
Referenced by wm_gesture_draw_rect().
void sdrawline (short x1, short y1, short x2, short y2)
Definition at line 219 of file glutil.c.
Referenced by draw_dividers(), drawcursor(), drawscredge_area_draw(), ED_screen_draw(), paint_draw_smooth_stroke(), region_draw_azone_icon(), region_draw_emboss(), ui_draw_separator(), wm_gesture_draw_cross(), and wm_gesture_draw_line().
void sdrawtri (short x1, short y1, short x2, short y2)
Definition at line 250 of file glutil.c.
References sdrawtripoints().
void sdrawtrifill (short x1, short y1, short x2, short y2)
Definition at line 257 of file glutil.c.
References sdrawtripoints().
static void sdrawtripoints (short x1, short y1, short x2, short y2) [static]
Definition at line 239 of file glutil.c.
Referenced by sdrawtri(), and sdrawtrifill().
void sdrawXORline (int x0, int y0, int x1, int y1)
Definition at line 310 of file glutil.c.
References set_inverted_drawing().
void sdrawXORline4 (int nr, int x0, int y0, int x1, int y1)
Definition at line 324 of file glutil.c.
References set_inverted_drawing().
void set_inverted_drawing (int enable)
Definition at line 303 of file glutil.c.
References glToggle.
Referenced by draw_object(), draw_textcurs(), drawPropCircle(), fdrawXORcirc(), fdrawXORellipse(), sdrawXORline(), and sdrawXORline4().
void setlinestyle (int nr)
Definition at line 287 of file glutil.c.
Referenced by draw_ebones(), draw_fcurve_modifier_controls_envelope(), draw_forcefield(), draw_hooks(), draw_image_seq(), draw_marker(), draw_mesh_face_select(), draw_new_particle_system(), draw_object(), draw_pose_bones(), draw_uvs(), drawConstraint(), drawcursor(), drawcursor_sima(), drawgrid(), drawHelpline(), drawlamp(), drawLine(), drawRBpivot(), drawSnapping(), drawtexspace(), drawviewborder(), gp_draw_data(), gp_draw_stroke_buffer(), graph_draw_curves(), graph_draw_ghost_curves(), nla_draw_strip(), pchan_draw_IK_root_lines(), and ui_draw_but_COLORBAND().
Variable Documentation
int curmode = 0 [static]
Definition at line 787 of file glutil.c.
int pointhack = 0 [static]
Definition at line 788 of file glutil.c.
GLubyte Squaredot[16] [static]
Initial value:
 { 0xff,0xff,0xff,0xff,
                                 0xff,0xff,0xff,0xff,
                                 0xff,0xff,0xff,0xff,
                                 0xff,0xff,0xff,0xff}
Definition at line 789 of file glutil.c.
GLubyte stipple_diag_stripes_neg[128]
Initial value:
 {
    0xff, 0x00, 0xff, 0x00, 0xfe, 0x01, 0xfe, 0x01,
    0xfc, 0x03, 0xfc, 0x03, 0xf8, 0x07, 0xf8, 0x07,
    0xf0, 0x0f, 0xf0, 0x0f, 0xe0, 0x1f, 0xe0, 0x1f,
    0xc0, 0x3f, 0xc0, 0x3f, 0x80, 0x7f, 0x80, 0x7f,
    0x00, 0xff, 0x00, 0xff, 0x01, 0xfe, 0x01, 0xfe,
    0x03, 0xfc, 0x03, 0xfc, 0x07, 0xf8, 0x07, 0xf8,
    0x0f, 0xf0, 0x0f, 0xf0, 0x1f, 0xe0, 0x1f, 0xe0,
    0x3f, 0xc0, 0x3f, 0xc0, 0x7f, 0x80, 0x7f, 0x80,
    0xff, 0x00, 0xff, 0x00, 0xfe, 0x01, 0xfe, 0x01,
    0xfc, 0x03, 0xfc, 0x03, 0xf8, 0x07, 0xf8, 0x07,
    0xf0, 0x0f, 0xf0, 0x0f, 0xe0, 0x1f, 0xe0, 0x1f,
    0xc0, 0x3f, 0xc0, 0x3f, 0x80, 0x7f, 0x80, 0x7f,
    0x00, 0xff, 0x00, 0xff, 0x01, 0xfe, 0x01, 0xfe,
    0x03, 0xfc, 0x03, 0xfc, 0x07, 0xf8, 0x07, 0xf8,
    0x0f, 0xf0, 0x0f, 0xf0, 0x1f, 0xe0, 0x1f, 0xe0,
    0x3f, 0xc0, 0x3f, 0xc0, 0x7f, 0x80, 0x7f, 0x80}
Definition at line 113 of file glutil.c.
Referenced by draw_seq_strip().
GLubyte stipple_diag_stripes_pos[128]
Initial value:
 {
    0x00, 0xff, 0x00, 0xff, 0x01, 0xfe, 0x01, 0xfe,
    0x03, 0xfc, 0x03, 0xfc, 0x07, 0xf8, 0x07, 0xf8,
    0x0f, 0xf0, 0x0f, 0xf0, 0x1f, 0xe0, 0x1f, 0xe0,
    0x3f, 0xc0, 0x3f, 0xc0, 0x7f, 0x80, 0x7f, 0x80,
    0xff, 0x00, 0xff, 0x00, 0xfe, 0x01, 0xfe, 0x01,
    0xfc, 0x03, 0xfc, 0x03, 0xf8, 0x07, 0xf8, 0x07,
    0xf0, 0x0f, 0xf0, 0x0f, 0xe0, 0x1f, 0xe0, 0x1f,
    0xc0, 0x3f, 0xc0, 0x3f, 0x80, 0x7f, 0x80, 0x7f,
    0x00, 0xff, 0x00, 0xff, 0x01, 0xfe, 0x01, 0xfe,
    0x03, 0xfc, 0x03, 0xfc, 0x07, 0xf8, 0x07, 0xf8,
    0x0f, 0xf0, 0x0f, 0xf0, 0x1f, 0xe0, 0x1f, 0xe0,
    0x3f, 0xc0, 0x3f, 0xc0, 0x7f, 0x80, 0x7f, 0x80,
    0xff, 0x00, 0xff, 0x00, 0xfe, 0x01, 0xfe, 0x01,
    0xfc, 0x03, 0xfc, 0x03, 0xf8, 0x07, 0xf8, 0x07,
    0xf0, 0x0f, 0xf0, 0x0f, 0xe0, 0x1f, 0xe0, 0x1f,
    0xc0, 0x3f, 0xc0, 0x3f, 0x80, 0x7f, 0x80, 0x7f}
Definition at line 94 of file glutil.c.
Referenced by draw_seq_strip().
GLubyte stipple_halftone[128]
Initial value:
 {
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55,
    0xAA, 0xAA, 0xAA, 0xAA, 0x55, 0x55, 0x55, 0x55}
Definition at line 56 of file glutil.c.
Referenced by console_draw_sel(), draw_shadedstrip(), and drawmeta_stipple().
GLubyte stipple_quarttone[128]
Initial value:
 {
    136,136,136,136,0,0,0,0,34,34,34,34,0,0,0,0,
    136,136,136,136,0,0,0,0,34,34,34,34,0,0,0,0,
    136,136,136,136,0,0,0,0,34,34,34,34,0,0,0,0,
    136,136,136,136,0,0,0,0,34,34,34,34,0,0,0,0,
    136,136,136,136,0,0,0,0,34,34,34,34,0,0,0,0,
    136,136,136,136,0,0,0,0,34,34,34,34,0,0,0,0,
    136,136,136,136,0,0,0,0,34,34,34,34,0,0,0,0,
    136,136,136,136,0,0,0,0,34,34,34,34,0,0,0,0}
Definition at line 83 of file glutil.c.
Referenced by ccgDM_drawMappedFaces(), draw_uvs(), and emDM_drawMappedFaces().