Blender: GHOST_DisplayManagerCarbon Class Reference
GHOST_DisplayManagerCarbon Class Reference
#include <GHOST_DisplayManagerCarbon.h>
Public Member Functions
GHOST_DisplayManagerCarbon (void)
virtual GHOST_TSuccess getNumDisplays (GHOST_TUns8 &numDisplays) const
virtual GHOST_TSuccess getNumDisplaySettings (GHOST_TUns8 display, GHOST_TInt32 &numSettings) const
virtual GHOST_TSuccess getDisplaySetting (GHOST_TUns8 display, GHOST_TInt32 index, GHOST_DisplaySetting &setting) const
virtual GHOST_TSuccess getCurrentDisplaySetting (GHOST_TUns8 display, GHOST_DisplaySetting &setting) const
virtual GHOST_TSuccess setCurrentDisplaySetting (GHOST_TUns8 display, const GHOST_DisplaySetting &setting)
Protected Member Functions
long getValue (CFDictionaryRef values, CFStringRef key) const
Protected Attributes
CGDisplayCount m_numDisplays
CGDirectDisplayID * m_displayIDs
Detailed Description
Manages system displays (Mac OSX/Carbon implementation).
See also:
GHOST_DisplayManager
Author:
Maarten Gribnau
Date:
September 21, 2001
Definition at line 51 of file GHOST_DisplayManagerCarbon.h.
Constructor & Destructor Documentation
GHOST_DisplayManagerCarbon::GHOST_DisplayManagerCarbon (void)
Constructor.
Copyright (C) 2001 NaN Technologies B.V.
Author:
Maarten Gribnau
Date:
September 21, 2001
Definition at line 46 of file GHOST_DisplayManagerCarbon.cpp.
References GHOST_ASSERT, m_displayIDs, m_numDisplays, and NULL.
Member Function Documentation
GHOST_TSuccess GHOST_DisplayManagerCarbon::getCurrentDisplaySetting (GHOST_TUns8 display, GHOST_DisplaySetting & setting) const [virtual]
Returns the current setting for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
setting The current setting of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 106 of file GHOST_DisplayManagerCarbon.cpp.
References GHOST_DisplaySetting::bpp, display(), GHOST_DisplaySetting::frequency, getValue(), GHOST_ASSERT, GHOST_kSuccess, GHOST_DisplayManager::kMainDisplay, m_displayIDs, GHOST_DisplaySetting::xPixels, and GHOST_DisplaySetting::yPixels.
GHOST_TSuccess GHOST_DisplayManagerCarbon::getDisplaySetting (GHOST_TUns8 display, GHOST_TInt32 index, GHOST_DisplaySetting & setting) const [virtual]
Returns the current setting for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
index The setting index to be returned.
setting The setting of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 82 of file GHOST_DisplayManagerCarbon.cpp.
References GHOST_DisplaySetting::bpp, display(), GHOST_DisplaySetting::frequency, getValue(), GHOST_ASSERT, GHOST_kSuccess, GHOST_DisplayManager::kMainDisplay, m_displayIDs, GHOST_DisplaySetting::xPixels, and GHOST_DisplaySetting::yPixels.
GHOST_TSuccess GHOST_DisplayManagerCarbon::getNumDisplays (GHOST_TUns8 & numDisplays) const [virtual]
Returns the number of display devices on this system.
Parameters:
numDisplays The number of displays on this system.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 62 of file GHOST_DisplayManagerCarbon.cpp.
References GHOST_kSuccess, and m_numDisplays.
GHOST_TSuccess GHOST_DisplayManagerCarbon::getNumDisplaySettings (GHOST_TUns8 display, GHOST_TInt32 & numSettings) const [virtual]
Returns the number of display settings for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
setting The number of settings of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 69 of file GHOST_DisplayManagerCarbon.cpp.
References display(), GHOST_ASSERT, GHOST_kSuccess, GHOST_DisplayManager::kMainDisplay, and m_displayIDs.
long GHOST_DisplayManagerCarbon::getValue (CFDictionaryRef values, CFStringRef key) const [protected]
Returns a value from a dictionary.
Parameters:
values Dictionary to return value from.
key Key to return value for.
Returns:
The value for this key.
Definition at line 159 of file GHOST_DisplayManagerCarbon.cpp.
Referenced by getCurrentDisplaySetting(), getDisplaySetting(), and setCurrentDisplaySetting().
GHOST_TSuccess GHOST_DisplayManagerCarbon::setCurrentDisplaySetting (GHOST_TUns8 display, const GHOST_DisplaySetting & setting) [virtual]
Changes the current setting for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
setting The current setting of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 125 of file GHOST_DisplayManagerCarbon.cpp.
References GHOST_DisplaySetting::bpp, display(), err, GHOST_DisplaySetting::frequency, getValue(), GHOST_ASSERT, GHOST_kFailure, GHOST_kSuccess, GHOST_DisplayManager::kMainDisplay, m_displayIDs, NULL, GHOST_DisplaySetting::xPixels, and GHOST_DisplaySetting::yPixels.
Member Data Documentation
CGDirectDisplayID* GHOST_DisplayManagerCarbon::m_displayIDs [protected]
Cached display id's for each display.
Definition at line 111 of file GHOST_DisplayManagerCarbon.h.
Referenced by getCurrentDisplaySetting(), getDisplaySetting(), getNumDisplaySettings(), GHOST_DisplayManagerCarbon(), and setCurrentDisplaySetting().
CGDisplayCount GHOST_DisplayManagerCarbon::m_numDisplays [protected]
Cached number of displays.
Definition at line 109 of file GHOST_DisplayManagerCarbon.h.
Referenced by getNumDisplays(), and GHOST_DisplayManagerCarbon().
The documentation for this class was generated from the following files:
GHOST_DisplayManagerCarbon.h
GHOST_DisplayManagerCarbon.cpp