Blender: node_composite_transform.c File Reference
node_composite_transform.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
CompBuf * node_composit_transform (CompBuf *cbuf, float x, float y, float angle, float scale, int filter_type)
static void node_composit_exec_transform (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_transform (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_transform_in []
static bNodeSocketTemplate cmp_node_transform_out []
Detailed Description
Definition in file node_composite_transform.c.
Function Documentation
static void node_composit_exec_transform (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 114 of file node_composite_transform.c.
References CB_RGBA, bNode::custom1, bNodeStack::data, data, free_compbuf(), node_composit_transform(), and typecheck_compbuf().
Referenced by register_node_type_cmp_transform().
CompBuf* node_composit_transform (CompBuf * cbuf, float x, float y, float angle, float scale, int filter_type)
Definition at line 51 of file node_composite_transform.c.
References add_v2_v2(), alloc_compbuf(), bicubic_interpolation(), bilinear_interpolation(), CB_RGBA, i, IMB_allocImBuf(), IMB_freeImBuf(), invert_m4(), invert_m4_m4(), mul_serie_m4(), mul_v3_m4v3(), neareast_interpolation(), NULL, CompBuf::rect, ImBuf::rect_float, rotate_m4(), size_to_mat4(), unit_m4(), CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_stabilize2d(), and node_composit_exec_transform().
void register_node_type_cmp_transform (bNodeTreeType * ttype)
Definition at line 130 of file node_composite_transform.c.
References CMP_NODE_TRANSFORM, NODE_CLASS_DISTORT, node_composit_exec_transform(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_transform_in[] [static]
Initial value:
 {
    {   SOCK_RGBA,      1,  "Image",            0.8f, 0.8f, 0.8f, 1.0f, 0.0f, 1.0f},
    {   SOCK_FLOAT,     1,  "X",                0.0f, 0.0f, 0.0f, 0.0f, -10000.0f, 10000.0f},
    {   SOCK_FLOAT,     1,  "Y",                0.0f, 0.0f, 0.0f, 0.0f, -10000.0f, 10000.0f},
    {   SOCK_FLOAT,     1,  "Angle",            0.0f, 0.0f, 0.0f, 0.0f, -10000.0f, 10000.0f, PROP_ANGLE},
    {   SOCK_FLOAT,     1,  "Scale",            1.0f, 0.0f, 0.0f, 0.0f, 0.0001f, CMP_SCALE_MAX},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_composite_transform.c.
bNodeSocketTemplate cmp_node_transform_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 46 of file node_composite_transform.c.