Blender: BL_BlenderDataConversion.h File Reference
BL_BlenderDataConversion.h File Reference
Converter
#include "CTR_HashedPtr.h"
#include "STR_String.h"
#include "KX_Python.h"
#include "KX_PhysicsEngineEnums.h"
#include "SCA_IInputDevice.h"
Functions
class RAS_MeshObject * BL_ConvertMesh (struct Mesh *mesh, struct Object *lightobj, class KX_Scene *scene, class KX_BlenderSceneConverter *converter)
void BL_ConvertBlenderObjects (struct Main *maggie, class KX_Scene *kxscene, class KX_KetsjiEngine *ketsjiEngine, e_PhysicsEngine physics_engine, class RAS_IRenderTools *rendertools, class RAS_ICanvas *canvas, class KX_BlenderSceneConverter *sceneconverter, bool alwaysUseExpandFraming)
SCA_IInputDevice::KX_EnumInputs ConvertKeyCode (int key_code)
Detailed Description
Definition in file BL_BlenderDataConversion.h.
Function Documentation
void BL_ConvertBlenderObjects (struct Main * maggie, class KX_Scene * kxscene, class KX_KetsjiEngine * ketsjiEngine, e_PhysicsEngine physics_engine, class RAS_IRenderTools * rendertools, class RAS_ICanvas * canvas, class KX_BlenderSceneConverter * sceneconverter, bool alwaysUseExpandFraming)
Definition at line 2313 of file BL_BlenderDataConversion.cpp.
References Main::action, GameData::activityBoxRadius, CListValue::Add(), KX_ISceneConverter::addInitFromFrame, KX_ObstacleSimulation::AddObstacleForObj(), KX_ObstacleSimulation::AddObstaclesForNavMesh(), CValue::AddRef(), assert, bRigidBodyJointConstraint::axX, bRigidBodyJointConstraint::axY, bRigidBodyJointConstraint::axZ, SG_Spatial::BBox(), BL_ConvertActuators(), BL_CONVERTBLENDEROBJECT_SINGLE, BL_ConvertControllers(), BL_ConvertSensors(), BL_CreateGraphicObjectNew(), BL_CreatePhysicsObjectNew(), KX_NavMeshObject::BuildNavMesh(), Scene::camera, bRigidBodyJointConstraint::child, GameFraming::col, CONSTRAINT_OFF, CONSTRAINT_TYPE_RIGIDBODYJOINT, PHY_IPhysicsEnvironment::createConstraint(), Object::data, bConstraint::data, SG_Node::DisconnectFromParent(), distance(), Object::dup_group, KX_Scene::DupliGroupRecurse(), Mesh::dvert, RAS_FrameSettings::e_frame_bars, RAS_FrameSettings::e_frame_extend, RAS_FrameSettings::e_frame_scale, KX_BlenderSceneConverter::FindGameObject(), ListBase::first, bConstraint::flag, bRigidBodyJointConstraint::flag, GameData::framing, Object::gameflag, gameobject_from_blenderobject(), get_active_constraints2(), get_named_bone(), KX_Scene::GetActiveCamera(), KX_GameObject::GetBlenderObject(), KX_Scene::GetBlenderScene(), KX_Scene::GetBucketManager(), KX_Camera::GetCameraFar(), KX_Camera::GetCameraNear(), KX_GameObject::GetChildrenRecursive(), MT_Matrix3x3::getColumn(), CListValue::GetCount(), KX_Scene::GetDbvtCulling(), KX_GameObject::GetDeformer(), BL_DeformableGameObject::GetDeformer(), getGameOb(), SCA_IObject::GetGameObjectType(), RAS_ICanvas::GetHeight(), KX_Scene::GetInactiveList(), KX_GameObject::GetLayer(), KX_Scene::GetLogicManager(), KX_GameObject::GetMesh(), KX_GameObject::GetMeshCount(), SG_BBox::getmm(), KX_Scene::GetObjectList(), KX_Scene::GetObstacleSimulation(), KX_GameObject::GetOccluder(), KX_GameObject::GetPhysicsController(), KX_Scene::GetPhysicsEnvironment(), KX_Scene::GetRootParentList(), KX_GameObject::GetSGNode(), SG_Node::GetSGParent(), KX_Scene::GetTimeEventManager(), KX_IPhysicsController::GetUserData(), CListValue::GetValue(), RAS_ICanvas::GetWidth(), Scene::gm, Group::gobject, GameData::gravity, BL_ModifierDeformer::HasArmatureDeformer(), i, Object::id, bAction::id, MT_Transform::Identity(), if(), Object::init_state, KX_GameObject::IsDupliGroup(), KX_GameObject::IsDynamic(), Object::lay, Scene::lay, bRigidBodyJointConstraint::maxLimit, bRigidBodyJointConstraint::minLimit, GameData::mode, Main::name, ID::name, KX_BoneParentRelation::New(), KX_SlowParentRelation::New(), KX_VertexParentRelation::New(), GroupObject::next, bConstraint::next, ID::next, KX_GameObject::NodeUpdateGS(), NULL, GroupObject::ob, OB_ARMATURE, OB_CAMERA, OB_HASOBSTACLE, OB_MESH, OB_NAVMESH, SCA_IObject::OBJ_ARMATURE, Base::object, GameData::occlusionRes, RAS_BucketManager::OptimizeBuckets(), PARBONE, PARCURVE, Object::parent, PARKEY, PAROBJECT, PARSKEL, PARSLOW, Object::parsubstr, Object::partype, PARVERT1, PARVERT3, PHY_CONE_TWIST_CONSTRAINT, PHY_GENERIC_6DOF_CONSTRAINT, PHY_LINEHINGE_CONSTRAINT, GameData::physubstep, bRigidBodyJointConstraint::pivX, bRigidBodyJointConstraint::pivY, bRigidBodyJointConstraint::pivZ, Scene::r, SCA_LogicManager::RegisterActionName(), KX_BlenderSceneConverter::RegisterWorldInfo(), CValue::Release(), KX_Scene::RemoveObject(), CListValue::RemoveValue(), SCA_IObject::ResetState(), SCE_GAMEFRAMING_BARS, SCE_GAMEFRAMING_EXTEND, CListValue::SearchValue(), KX_Scene::SetActiveCamera(), KX_Scene::SetActivityCulling(), KX_Scene::SetActivityCullingRadius(), KX_GameObject::setAngularVelocity(), PHY_IPhysicsEnvironment::setConstraintParam(), KX_Scene::SetDbvtCulling(), KX_Scene::SetDbvtOcclusionRes(), SetDefaultLightMode(), KX_Scene::SetFramingType(), KX_Scene::SetGravity(), SCA_IObject::SetInitState(), KX_GameObject::setLinearVelocity(), SETLOOPER, PHY_IPhysicsEnvironment::setNumTimeSubSteps(), KX_GameObject::SetVisible(), KX_Scene::SetWorldInfo(), Object::sf, Object::state, bRigidBodyJointConstraint::tar, bConstraint::type, Object::type, bRigidBodyJointConstraint::type, GameFraming::type, KX_BlenderSceneConverter::UnregisterGameObject(), RAS_Deformer::UpdateBuckets(), WO_ACTIVITY_CULLING, WO_DBVT_CULLING, Scene::world, MT_Tuple3::x(), RenderData::xasp, RenderData::xsch, MT_Tuple3::y(), RenderData::yasp, RenderData::ysch, and MT_Tuple3::z().
Referenced by KX_BlenderSceneConverter::ConvertScene().
class RAS_MeshObject* BL_ConvertMesh (struct Mesh * mesh, struct Object * lightobj, class KX_Scene * scene, class KX_BlenderSceneConverter * converter)
Definition at line 906 of file BL_BlenderDataConversion.cpp.
References RAS_MeshObject::AddPolygon(), RAS_MeshObject::AddVertex(), Material::alpha, GameSettings::alpha_blend, assert, Material::b, BKE_image_has_alpha(), CD_MCOL, CD_MTFACE, CD_TANGENT, CDDM_from_mesh(), MVert::co, ConvertMaterial(), CustomDataLayer::data, default_light_mode, defmaterial, DM_add_tangent_layer(), DM_ensure_tessface(), ELEM3, Material::emit, RAS_MeshObject::EndConversion(), MTF_localLayer::face, DerivedMesh::faceData, KX_Scene::FindBucket(), KX_BlenderSceneConverter::FindGameMesh(), MFace::flag, GameSettings::flag, Material::g, Material::game, GEMAT_ADD, GEMAT_ALPHA, GEMAT_ALPHA_SORT, GEMAT_BACKCULL, GEMAT_INVISIBLE, GEMAT_NOPHYSICS, GEMAT_SOLID, GEMAT_TEXT, BL_Material::GetConversionRGB(), BL_Material::GetConversionUV(), BL_Material::GetConversionUV2(), RAS_MeshObject::GetFirstMaterial(), KX_BlenderSceneConverter::GetGLSLMaterials(), RAS_MeshObject::GetLastMaterial(), KX_BlenderSceneConverter::GetMaterials(), DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, RAS_MaterialBucket::GetPolyMaterial(), DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVertArray, give_current_material(), Material::har, i, Mesh::id, Image::id, KX_BlenderMaterial::Initialize(), KX_PolygonMaterial::Initialize(), KX_Mcol2uint_new(), KX_rgbaint2uint_new(), L, Object::lay, CustomData::layers, RAS_IPolyMaterial::m_diffuse, RAS_MeshObject::m_sharedvertex_map, RAS_IPolyMaterial::m_shininess, RAS_IPolyMaterial::m_specular, MA_FACETEXTURE, MA_SHLESS, Mesh::mat, MFace::mat_nr, MAX_MTFACE, ME_SMOOTH, Material::mode, MTF_localLayer::name, ID::name, CustomDataLayer::name, MVert::no, normal_quad_v3(), normal_short_to_float_v3(), normal_tri_v3(), NULL, Material::r, Material::ref, KX_BlenderSceneConverter::RegisterBlenderMaterial(), KX_BlenderSceneConverter::RegisterGameMesh(), KX_BlenderSceneConverter::RegisterPolyMaterial(), DerivedMesh::release, RAS_Polygon::SetCollider(), RAS_MeshObject::SetName(), RAS_Polygon::SetTwoside(), MT_Tuple3::setValue(), MT_Tuple2::setValue(), RAS_Polygon::SetVisible(), Material::spec, Material::specb, Material::specg, Material::specr, MTFace::tile, CustomData::totlayer, MTFace::tpage, CustomDataLayer::type, MTFace::uv, MFace::v1, MFace::v2, MFace::v3, MFace::v4, Image::xrep, and Image::yrep.
Referenced by BL_ConvertActuators(), KX_BlenderSceneConverter::ConvertMeshSpecial(), gameobject_from_blenderobject(), and KX_BlenderSceneConverter::LinkBlendFile().
SCA_IInputDevice::KX_EnumInputs ConvertKeyCode (int key_code)
Definition at line 2956 of file BL_BlenderDataConversion.cpp.
References gReverseKeyTranslateTable.
Referenced by BL_ConvertSensors(), GPG_Application::initEngine(), StartKetsjiShell(), and BL_BlenderInputDevice::ToNative().