Blender: KX_KetsjiEngine Class Reference
KX_KetsjiEngine Class Reference
#include <KX_KetsjiEngine.h>
Public Member Functions
KX_KetsjiEngine (class KX_ISystem *system)
virtual ~KX_KetsjiEngine ()
void SetWorldSettings (KX_WorldInfo *worldinfo)
void SetKeyboardDevice (SCA_IInputDevice *keyboarddevice)
void SetMouseDevice (SCA_IInputDevice *mousedevice)
void SetNetworkDevice (NG_NetworkDeviceInterface *networkdevice)
void SetCanvas (RAS_ICanvas *canvas)
void SetRenderTools (RAS_IRenderTools *rendertools)
void SetRasterizer (RAS_IRasterizer *rasterizer)
void SetSceneConverter (KX_ISceneConverter *sceneconverter)
void SetAnimRecordMode (bool animation_record, int startFrame)
RAS_IRasterizer * GetRasterizer ()
RAS_ICanvas * GetCanvas ()
RAS_IRenderTools * GetRenderTools ()
SCA_IInputDevice * GetKeyboardDevice ()
SCA_IInputDevice * GetMouseDevice ()
void InitDome (short res, short mode, short angle, float resbuf, short tilt, struct Text *text)
Dome functions.
void EndDome ()
void RenderDome ()
bool NextFrame ()
returns true if an update happened to indicate -> Render
void Render ()
void StartEngine (bool clearIpo)
void StopEngine ()
void Export (const STR_String &filename)
void RequestExit (int exitrequestmode)
void SetNameNextGame (const STR_String &nextgame)
int GetExitCode ()
const STR_String & GetExitString ()
KX_SceneList * CurrentScenes ()
KX_Scene * FindScene (const STR_String &scenename)
void AddScene (class KX_Scene *scene)
void ConvertAndAddScene (const STR_String &scenename, bool overlay)
void RemoveScene (const STR_String &scenename)
void ReplaceScene (const STR_String &oldscene, const STR_String &newscene)
void SuspendScene (const STR_String &scenename)
void ResumeScene (const STR_String &scenename)
void GetSceneViewport (KX_Scene *scene, KX_Camera *cam, RAS_Rect &area, RAS_Rect &viewport)
void SetDrawType (int drawingtype)
int GetDrawType ()
void SetCameraZoom (float camzoom)
void EnableCameraOverride (const STR_String &forscene)
void SetCameraOverrideUseOrtho (bool useOrtho)
void SetCameraOverrideProjectionMatrix (const MT_CmMatrix4x4 &mat)
void SetCameraOverrideViewMatrix (const MT_CmMatrix4x4 &mat)
void SetCameraOverrideClipping (float near, float far)
void SetCameraOverrideLens (float lens)
void SetUseFixedTime (bool bUseFixedTime)
bool GetUseFixedTime (void) const
double GetClockTime (void) const
double GetFrameTime (void) const
double GetRealTime (void) const
void SetTimingDisplay (bool frameRate, bool profile, bool properties)
void GetTimingDisplay (bool &frameRate, bool &profile, bool &properties) const
void SetHideCursor (bool hideCursor)
bool GetHideCursor (void) const
void SetUseOverrideFrameColor (bool overrideFrameColor)
bool GetUseOverrideFrameColor (void) const
void SetOverrideFrameColor (float r, float g, float b)
void GetOverrideFrameColor (float &r, float &g, float &b) const
KX_Scene * CreateScene (const STR_String &scenename)
KX_Scene * CreateScene (Scene *scene)
GlobalSettings * GetGlobalSettings (void)
void SetGlobalSettings (GlobalSettings *gs)
Static Public Member Functions
static double GetSuspendedDelta ()
static double GetTicRate ()
static void SetTicRate (double ticrate)
static int GetMaxLogicFrame ()
static void SetMaxLogicFrame (int frame)
static int GetMaxPhysicsFrame ()
static void SetMaxPhysicsFrame (int frame)
static bool GetRestrictAnimationFPS ()
static void SetRestrictAnimationFPS (bool bRestrictAnimFPS)
static double GetAnimFrameRate ()
static void SetAnimFrameRate (double framerate)
static double GetAverageFrameRate ()
static void SetExitKey (short key)
static short GetExitKey ()
Public Attributes
bool m_usedome
Protected Member Functions
void ProcessScheduledScenes (void)
void SceneListsChanged (void)
void RemoveScheduledScenes (void)
void AddScheduledScenes (void)
void ReplaceScheduledScenes (void)
void PostProcessScene (class KX_Scene *scene)
bool BeginFrame ()
void ClearFrame ()
void EndFrame ()
Detailed Description
KX_KetsjiEngine is the core game engine class.
Definition at line 71 of file KX_KetsjiEngine.h.
Constructor & Destructor Documentation
KX_KetsjiEngine::KX_KetsjiEngine (class KX_ISystem * system)
Constructor of the Ketsji Engine
Definition at line 119 of file KX_KetsjiEngine.cpp.
References KX_TimeCategoryLogger::AddCategory(), and i.
KX_KetsjiEngine::~KX_KetsjiEngine () [virtual]
Destructor of the Ketsji Engine, release all memory
Definition at line 194 of file KX_KetsjiEngine.cpp.
References m_usedome.
Member Function Documentation
void KX_KetsjiEngine::AddScene (class KX_Scene * scene)
Definition at line 1384 of file KX_KetsjiEngine.cpp.
References PostProcessScene(), and SceneListsChanged().
Referenced by GPG_Application::startEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::AddScheduledScenes (void) [protected]
Definition at line 1669 of file KX_KetsjiEngine.cpp.
References CreateScene(), and PostProcessScene().
Referenced by ProcessScheduledScenes().
bool KX_KetsjiEngine::BeginFrame () [protected]
Definition at line 482 of file KX_KetsjiEngine.cpp.
References RAS_ICanvas::BeginDraw(), RAS_IRenderTools::BeginFrame(), RAS_IRasterizer::BeginFrame(), ClearFrame(), KX_ISystem::GetTimeInSeconds(), and RAS_IRasterizer::SetRenderArea().
Referenced by Render(), and RenderDome().
void KX_KetsjiEngine::ClearFrame () [protected]
Definition at line 431 of file KX_KetsjiEngine.cpp.
References RAS_IRasterizer::ClearColorBuffer(), RAS_Rect::GetBottom(), KX_Scene::GetCameras(), RAS_IRasterizer::GetEye(), RAS_Rect::GetLeft(), RAS_Rect::GetRight(), GetSceneViewport(), RAS_Rect::GetTop(), KX_Scene::GetWorldInfo(), RAS_IRasterizer::InterlacedStereo(), RAS_IRasterizer::RAS_STEREO_RIGHTEYE, RAS_Rect::SetBottom(), RAS_Rect::SetLeft(), RAS_Rect::SetRight(), RAS_Rect::SetTop(), and RAS_ICanvas::SetViewPort().
Referenced by BeginFrame().
void KX_KetsjiEngine::ConvertAndAddScene (const STR_String & scenename, bool overlay)
Definition at line 1583 of file KX_KetsjiEngine.cpp.
References FindScene(), and STR_String::Ptr().
Referenced by KX_SceneActuator::Update().
KX_Scene * KX_KetsjiEngine::CreateScene (const STR_String & scenename)
Definition at line 1663 of file KX_KetsjiEngine.cpp.
References KX_ISceneConverter::GetBlenderSceneForName().
Referenced by AddScheduledScenes(), KX_BlenderSceneConverter::LinkBlendFile(), and ReplaceScheduledScenes().
KX_Scene * KX_KetsjiEngine::CreateScene (Scene * scene)
Definition at line 1647 of file KX_KetsjiEngine.cpp.
References KX_ISceneConverter::ConvertScene(), Scene::id, and ID::name.
KX_SceneList * KX_KetsjiEngine::CurrentScenes ()
Definition at line 1560 of file KX_KetsjiEngine.cpp.
Referenced by KX_BlenderSceneConverter::FreeBlendFile(), KX_BlenderSceneConverter::resetNoneDynamicObjectToIpo(), KX_BlenderSceneConverter::ResetPhysicsObjectsAnimationIpo(), KX_BlenderSceneConverter::TestHandlesPhysicsObjectToAnimationIpo(), and KX_BlenderSceneConverter::WritePhysicsObjectToAnimationIpo().
void KX_KetsjiEngine::EnableCameraOverride (const STR_String & forscene)
Definition at line 1060 of file KX_KetsjiEngine.cpp.
Referenced by StartKetsjiShell().
void KX_KetsjiEngine::EndDome ()
void KX_KetsjiEngine::EndFrame () [protected]
Definition at line 501 of file KX_KetsjiEngine.cpp.
References RAS_ICanvas::EndDraw(), RAS_IRenderTools::EndFrame(), RAS_IRasterizer::EndFrame(), KX_TimeCategoryLogger::GetAverage(), KX_ISystem::GetTimeInSeconds(), KX_TimeCategoryLogger::NextMeasurement(), KX_TimeCategoryLogger::StartLog(), and RAS_IRasterizer::SwapBuffers().
Referenced by Render(), and RenderDome().
void KX_KetsjiEngine::Export (const STR_String & filename)
KX_Scene * KX_KetsjiEngine::FindScene (const STR_String & scenename)
Definition at line 1567 of file KX_KetsjiEngine.cpp.
References NULL.
Referenced by ConvertAndAddScene(), RemoveScene(), ResumeScene(), and SuspendScene().
double KX_KetsjiEngine::GetAnimFrameRate () [static]
Gets the framerate for playing animations. (actions and ipos)
Definition at line 1831 of file KX_KetsjiEngine.cpp.
Referenced by BL_ActionActuator::ResetStartTime(), BL_ShapeActionActuator::SetLocalTime(), BL_ActionActuator::SetLocalTime(), BL_ShapeActionActuator::SetStartTime(), and BL_ShapeActionActuator::Update().
double KX_KetsjiEngine::GetAverageFrameRate () [static]
Gets the last estimated average framerate
Definition at line 1856 of file KX_KetsjiEngine.cpp.
RAS_ICanvas* KX_KetsjiEngine::GetCanvas () [inline]
Definition at line 231 of file KX_KetsjiEngine.h.
References KX_Dome::m_canvas.
Referenced by ImageRender::ImageRender(), and ImageViewport::ImageViewport().
double KX_KetsjiEngine::GetClockTime (void) const
Returns current render frame clock time
Definition at line 1836 of file KX_KetsjiEngine.cpp.
Referenced by ImageRender::Render(), and Texture_refresh().
int KX_KetsjiEngine::GetDrawType () [inline]
Definition at line 268 of file KX_KetsjiEngine.h.
References KX_Dome::m_drawingmode.
int KX_KetsjiEngine::GetExitCode ()
Definition at line 978 of file KX_KetsjiEngine.cpp.
References KX_EXIT_REQUEST_NO_SCENES_LEFT.
Referenced by GPG_Application::processEvent(), and StartKetsjiShell().
short KX_KetsjiEngine::GetExitKey () [static]
Definition at line 1866 of file KX_KetsjiEngine.cpp.
Referenced by KX_BlenderKeyboardDevice::ConvertBlenderEvent(), and GPG_Application::handleKey().
const STR_String & KX_KetsjiEngine::GetExitString ()
Definition at line 1000 of file KX_KetsjiEngine.cpp.
Referenced by GPG_Application::processEvent(), and StartKetsjiShell().
double KX_KetsjiEngine::GetFrameTime (void) const
Returns current logic frame clock time
Definition at line 1841 of file KX_KetsjiEngine.cpp.
Referenced by BL_Action::Play().
GlobalSettings * KX_KetsjiEngine::GetGlobalSettings (void)
Definition at line 1968 of file KX_KetsjiEngine.cpp.
Referenced by GPG_Application::getGlobalSettings(), and StartKetsjiShell().
bool KX_KetsjiEngine::GetHideCursor (void) const
Returns the current setting for cursor hiding.
Returns:
The current setting for cursor hiding.
Definition at line 1929 of file KX_KetsjiEngine.cpp.
SCA_IInputDevice* KX_KetsjiEngine::GetKeyboardDevice () [inline]
Definition at line 233 of file KX_KetsjiEngine.h.
int KX_KetsjiEngine::GetMaxLogicFrame () [static]
Gets the maximum number of logic frame before render frame
Definition at line 1801 of file KX_KetsjiEngine.cpp.
int KX_KetsjiEngine::GetMaxPhysicsFrame () [static]
Gets the maximum number of physics frame before render frame
Definition at line 1811 of file KX_KetsjiEngine.cpp.
SCA_IInputDevice* KX_KetsjiEngine::GetMouseDevice () [inline]
Definition at line 234 of file KX_KetsjiEngine.h.
void KX_KetsjiEngine::GetOverrideFrameColor (float & r, float & g, float & b) const
Returns the color used for framing bar color instead of the one in the Blender file's scenes.
Parameters:
r Red component of the override color.
g Green component of the override color.
b Blue component of the override color.
Definition at line 1955 of file KX_KetsjiEngine.cpp.
RAS_IRasterizer* KX_KetsjiEngine::GetRasterizer () [inline]
Definition at line 230 of file KX_KetsjiEngine.h.
References KX_Dome::m_rasterizer.
Referenced by BL_ConvertActuators(), and ImageRender::ImageRender().
double KX_KetsjiEngine::GetRealTime (void) const
Definition at line 1846 of file KX_KetsjiEngine.cpp.
References KX_ISystem::GetTimeInSeconds().
Referenced by BL_ConvertActuators(), and BL_ConvertSensors().
RAS_IRenderTools* KX_KetsjiEngine::GetRenderTools () [inline]
Definition at line 232 of file KX_KetsjiEngine.h.
References KX_Dome::m_rendertools.
Referenced by ImageRender::ImageRender().
bool KX_KetsjiEngine::GetRestrictAnimationFPS () [static]
Gets whether or not to lock animation updates to the animframerate
Definition at line 1821 of file KX_KetsjiEngine.cpp.
Referenced by NextFrame().
void KX_KetsjiEngine::GetSceneViewport (KX_Scene * scene, KX_Camera * cam, RAS_Rect & area, RAS_Rect & viewport)
Definition at line 1104 of file KX_KetsjiEngine.cpp.
References RAS_FramingManager::ComputeViewport(), RAS_FrameSettings::e_frame_bars, RAS_FrameSettings::e_frame_extend, RAS_FrameSettings::FrameType(), RAS_ICanvas::GetDisplayArea(), KX_Scene::GetFramingType(), RAS_ICanvas::GetHeight(), KX_Scene::GetName(), KX_Camera::GetViewport(), KX_Camera::GetViewportBottom(), KX_Camera::GetViewportLeft(), KX_Camera::GetViewportRight(), KX_Camera::GetViewportTop(), RAS_ICanvas::GetWidth(), RAS_Rect::SetBottom(), RAS_FrameSettings::SetFrameType(), RAS_Rect::SetLeft(), RAS_Rect::SetRight(), and RAS_Rect::SetTop().
Referenced by ClearFrame().
double KX_KetsjiEngine::GetSuspendedDelta () [static]
Returns the difference between the local time of the scene (when it was running and not suspended) and the "curtime"
Definition at line 1786 of file KX_KetsjiEngine.cpp.
Referenced by BL_Action::Update(), BL_ShapeActionActuator::Update(), and KX_IpoActuator::Update().
double KX_KetsjiEngine::GetTicRate () [static]
Gets the number of logic updates per second.
Definition at line 1791 of file KX_KetsjiEngine.cpp.
Referenced by KX_Scene::LogicBeginFrame().
void KX_KetsjiEngine::GetTimingDisplay (bool & frameRate, bool & profile, bool & properties) const
Returns status of timing information display.
Parameters:
frameRate Display for frame rate on or off.
profile Display for individual components on or off.
properties Display of scene object debug properties on or off.
Definition at line 1880 of file KX_KetsjiEngine.cpp.
bool KX_KetsjiEngine::GetUseFixedTime (void) const
Returns display of all frames.
Returns:
Current setting for display all frames.
Definition at line 1781 of file KX_KetsjiEngine.cpp.
bool KX_KetsjiEngine::GetUseOverrideFrameColor (void) const
Check if the frame color is being overridden.
Definition at line 1941 of file KX_KetsjiEngine.cpp.
void KX_KetsjiEngine::InitDome (short res, short mode, short angle, float resbuf, short tilt, struct Text * text)
Dome functions.
Definition at line 267 of file KX_KetsjiEngine.cpp.
References m_usedome.
Referenced by GPG_Application::startEngine(), and StartKetsjiShell().
bool KX_KetsjiEngine::NextFrame ()
returns true if an update happened to indicate -> Render
Definition at line 532 of file KX_KetsjiEngine.cpp.
References PHY_IPhysicsEnvironment::beginFrame(), PHY_IPhysicsEnvironment::endFrame(), KX_Scene::GetAnimationFPS(), KX_Scene::GetNetworkScene(), KX_Scene::GetPhysicsEnvironment(), GetRestrictAnimationFPS(), KX_Scene::getSuspendedDelta(), KX_Scene::getSuspendedTime(), KX_ISystem::GetTimeInSeconds(), KX_Scene::IsSuspended(), KX_GetActiveScene(), KX_SetActiveScene(), KX_Scene::LogicBeginFrame(), KX_Scene::LogicEndFrame(), KX_Scene::LogicUpdateFrame(), NG_NetworkDeviceInterface::NextFrame(), SCA_IInputDevice::NextFrame(), NG_NetworkScene::proceed(), PHY_IPhysicsEnvironment::proceedDeltaTime(), ProcessScheduledScenes(), KX_ISceneConverter::resetNoneDynamicObjectToIpo(), KX_Scene::setSuspendedDelta(), KX_Scene::setSuspendedTime(), SG_SetActiveStage(), SG_STAGE_ACTUATOR, SG_STAGE_ACTUATOR_UPDATE, SG_STAGE_ANIMATION_UPDATE, SG_STAGE_CONTROLLER, SG_STAGE_CONTROLLER_UPDATE, SG_STAGE_NETWORK, SG_STAGE_PHYSICS1, SG_STAGE_PHYSICS2, SG_STAGE_PHYSICS2_UPDATE, KX_TimeCategoryLogger::StartLog(), KX_Scene::UpdateAnimations(), KX_Scene::UpdateObjectActivity(), KX_Scene::UpdateParents(), and KX_ISceneConverter::WritePhysicsObjectToAnimationIpo().
Referenced by GPG_Application::processEvent(), and StartKetsjiShell().
void KX_KetsjiEngine::PostProcessScene (class KX_Scene * scene) [protected]
Definition at line 1393 of file KX_KetsjiEngine.cpp.
References CListValue::Add(), KX_Scene::AddCamera(), CValue::AddRef(), KX_Scene::GetActiveCamera(), KX_Scene::GetName(), KX_Scene::GetObjectList(), MT_CmMatrix4x4::getPointer(), KX_Scene::GetRootParentList(), MT_Transform::invert(), KX_Scene::m_callbacks, RAS_CameraData::m_clipend, RAS_CameraData::m_clipstart, RAS_CameraData::m_lens, RAS_CameraData::m_perspective, KX_GameObject::NodeSetLocalOrientation(), KX_GameObject::NodeSetLocalPosition(), KX_GameObject::NodeUpdateGS(), NULL, CValue::Release(), KX_Scene::SetActiveCamera(), KX_GameObject::SetName(), SG_SetActiveStage(), SG_STAGE_SCENE, and KX_Scene::UpdateParents().
Referenced by AddScene(), AddScheduledScenes(), and ReplaceScheduledScenes().
void KX_KetsjiEngine::ProcessScheduledScenes (void) [protected]
Processes all scheduled scene activity. At the end, if the scene lists have changed, SceneListsChanged(void) is called.
See also:
SceneListsChanged(void).
Definition at line 1889 of file KX_KetsjiEngine.cpp.
References AddScheduledScenes(), RemoveScheduledScenes(), ReplaceScheduledScenes(), and SceneListsChanged().
Referenced by NextFrame().
void KX_KetsjiEngine::RemoveScene (const STR_String & scenename)
Definition at line 1607 of file KX_KetsjiEngine.cpp.
References FindScene().
Referenced by KX_SceneActuator::Update().
void KX_KetsjiEngine::RemoveScheduledScenes (void) [protected]
Definition at line 1622 of file KX_KetsjiEngine.cpp.
References KX_Scene::GetName(), and KX_ISceneConverter::RemoveScene().
Referenced by ProcessScheduledScenes().
void KX_KetsjiEngine::Render ()
Definition at line 807 of file KX_KetsjiEngine.cpp.
References RAS_FrameSettings::BarBlue(), RAS_FrameSettings::BarGreen(), RAS_FrameSettings::BarRed(), RAS_ICanvas::BeginDraw(), BeginFrame(), RAS_ICanvas::ClearBuffer(), RAS_ICanvas::ClearColor(), RAS_IRasterizer::ClearDepthBuffer(), RAS_ICanvas::COLOR_BUFFER, RAS_ICanvas::DEPTH_BUFFER, EndFrame(), KX_Scene::GetActiveCamera(), KX_Scene::GetCameras(), KX_Scene::GetFramingType(), RAS_ICanvas::GetHeight(), KX_ISystem::GetTimeInSeconds(), KX_Camera::GetViewport(), RAS_ICanvas::GetWidth(), KX_Scene::GetWorldInfo(), KX_Scene::IsClearingZBuffer(), RAS_IRasterizer::KX_TEXTURED, m_usedome, RAS_ICanvas::MOUSE_INVISIBLE, RAS_IRasterizer::RAS_STEREO_LEFTEYE, RAS_IRasterizer::RAS_STEREO_RIGHTEYE, RenderDome(), RAS_IRenderTools::SetAuxilaryClientInfo(), RAS_IRasterizer::SetEye(), RAS_ICanvas::SetMouseState(), RAS_ICanvas::SetViewPort(), SetWorldSettings(), SG_SetActiveStage(), SG_STAGE_RENDER, KX_TimeCategoryLogger::StartLog(), and RAS_IRasterizer::Stereo().
Referenced by GPG_Application::processEvent(), and StartKetsjiShell().
void KX_KetsjiEngine::RenderDome (void)
Definition at line 273 of file KX_KetsjiEngine.cpp.
References RAS_FrameSettings::BarBlue(), RAS_FrameSettings::BarGreen(), RAS_FrameSettings::BarRed(), RAS_ICanvas::BeginDraw(), BeginFrame(), RAS_IRenderTools::BeginFrame(), KX_Dome::BindImages(), RAS_ICanvas::ClearBuffer(), RAS_ICanvas::ClearColor(), RAS_IRasterizer::ClearDepthBuffer(), RAS_ICanvas::COLOR_BUFFER, RAS_ICanvas::DEPTH_BUFFER, KX_Dome::Draw(), EndFrame(), RAS_ICanvas::EndFrame(), KX_Scene::GetActiveCamera(), KX_Scene::GetCameras(), KX_Scene::GetFramingType(), RAS_ICanvas::GetHeight(), KX_Dome::GetNumberRenders(), KX_ISystem::GetTimeInSeconds(), KX_Camera::GetViewport(), RAS_ICanvas::GetWidth(), KX_Scene::GetWorldInfo(), i, KX_Scene::IsClearingZBuffer(), RAS_IRenderTools::MotionBlur(), RAS_ICanvas::MOUSE_INVISIBLE, KX_Scene::Render2DFilters(), KX_Dome::RenderDomeFrame(), RAS_IRenderTools::SetAuxilaryClientInfo(), RAS_ICanvas::SetMouseState(), RAS_ICanvas::SetViewPort(), KX_Dome::SetViewPort(), SetWorldSettings(), and KX_TimeCategoryLogger::StartLog().
Referenced by Render().
void KX_KetsjiEngine::ReplaceScene (const STR_String & oldscene, const STR_String & newscene)
Definition at line 1705 of file KX_KetsjiEngine.cpp.
Referenced by KX_SceneActuator::Update().
void KX_KetsjiEngine::ReplaceScheduledScenes (void) [protected]
Definition at line 1714 of file KX_KetsjiEngine.cpp.
References CreateScene(), KX_Scene::GetName(), i, PostProcessScene(), and KX_ISceneConverter::RemoveScene().
Referenced by ProcessScheduledScenes().
void KX_KetsjiEngine::RequestExit (int exitrequestmode)
Definition at line 964 of file KX_KetsjiEngine.cpp.
Referenced by KX_GameActuator::Update().
void KX_KetsjiEngine::ResumeScene (const STR_String & scenename)
Definition at line 1756 of file KX_KetsjiEngine.cpp.
References FindScene(), and KX_Scene::Resume().
Referenced by KX_SceneActuator::Update().
void KX_KetsjiEngine::SceneListsChanged (void) [protected]
This method is invoked when the scene lists have changed.
Definition at line 1909 of file KX_KetsjiEngine.cpp.
References SCA_IScene::GetDebugProperties().
Referenced by AddScene(), and ProcessScheduledScenes().
void KX_KetsjiEngine::SetAnimFrameRate (double framerate) [static]
Sets the framerate for playing animations. (actions and ipos)
Definition at line 1851 of file KX_KetsjiEngine.cpp.
Referenced by GPG_Application::startEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::SetAnimRecordMode (bool animation_record, int startFrame)
Definition at line 1770 of file KX_KetsjiEngine.cpp.
Referenced by StartKetsjiShell().
void KX_KetsjiEngine::SetCameraOverrideClipping (float near, float far)
Definition at line 1093 of file KX_KetsjiEngine.cpp.
References far, and near.
Referenced by StartKetsjiShell().
void KX_KetsjiEngine::SetCameraOverrideLens (float lens)
Definition at line 1099 of file KX_KetsjiEngine.cpp.
Referenced by StartKetsjiShell().
void KX_KetsjiEngine::SetCameraOverrideProjectionMatrix (const MT_CmMatrix4x4 & mat)
Definition at line 1082 of file KX_KetsjiEngine.cpp.
Referenced by StartKetsjiShell().
void KX_KetsjiEngine::SetCameraOverrideUseOrtho (bool useOrtho)
Definition at line 1075 of file KX_KetsjiEngine.cpp.
Referenced by StartKetsjiShell().
void KX_KetsjiEngine::SetCameraOverrideViewMatrix (const MT_CmMatrix4x4 & mat)
Definition at line 1088 of file KX_KetsjiEngine.cpp.
Referenced by StartKetsjiShell().
void KX_KetsjiEngine::SetCameraZoom (float camzoom)
Definition at line 1068 of file KX_KetsjiEngine.cpp.
Referenced by StartKetsjiShell().
void KX_KetsjiEngine::SetCanvas (RAS_ICanvas * canvas)
Definition at line 226 of file KX_KetsjiEngine.cpp.
References MT_assert.
Referenced by GPG_Application::initEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::SetDrawType (int drawingtype)
Definition at line 1053 of file KX_KetsjiEngine.cpp.
Referenced by StartKetsjiShell().
void KX_KetsjiEngine::SetExitKey (short key) [static]
Definition at line 1861 of file KX_KetsjiEngine.cpp.
Referenced by GPG_Application::initEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::SetGlobalSettings (GlobalSettings * gs)
Definition at line 1962 of file KX_KetsjiEngine.cpp.
References GlobalSettings::glslflag, and GlobalSettings::matmode.
Referenced by GPG_Application::initEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::SetHideCursor (bool hideCursor)
Sets cursor hiding on every frame.
Parameters:
hideCursor Turns hiding on or off.
Definition at line 1923 of file KX_KetsjiEngine.cpp.
void KX_KetsjiEngine::SetKeyboardDevice (SCA_IInputDevice * keyboarddevice)
Definition at line 203 of file KX_KetsjiEngine.cpp.
References MT_assert.
Referenced by GPG_Application::initEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::SetMaxLogicFrame (int frame) [static]
Sets the maximum number of logic frame before render frame
Definition at line 1806 of file KX_KetsjiEngine.cpp.
void KX_KetsjiEngine::SetMaxPhysicsFrame (int frame) [static]
Sets the maximum number of physics frame before render frame
Definition at line 1816 of file KX_KetsjiEngine.cpp.
void KX_KetsjiEngine::SetMouseDevice (SCA_IInputDevice * mousedevice)
Definition at line 211 of file KX_KetsjiEngine.cpp.
References MT_assert.
Referenced by GPG_Application::initEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::SetNameNextGame (const STR_String & nextgame)
Definition at line 971 of file KX_KetsjiEngine.cpp.
Referenced by KX_GameActuator::Update().
void KX_KetsjiEngine::SetNetworkDevice (NG_NetworkDeviceInterface * networkdevice)
Definition at line 219 of file KX_KetsjiEngine.cpp.
References MT_assert.
Referenced by GPG_Application::initEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::SetOverrideFrameColor (float r, float g, float b)
Set the color used for framing bar color instead of the one in the Blender file's scenes.
Parameters:
r Red component of the override color.
g Green component of the override color.
b Blue component of the override color.
Definition at line 1947 of file KX_KetsjiEngine.cpp.
References g.
void KX_KetsjiEngine::SetRasterizer (RAS_IRasterizer * rasterizer)
Definition at line 242 of file KX_KetsjiEngine.cpp.
References MT_assert.
Referenced by GPG_Application::initEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::SetRenderTools (RAS_IRenderTools * rendertools)
Definition at line 234 of file KX_KetsjiEngine.cpp.
References MT_assert.
Referenced by GPG_Application::initEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::SetRestrictAnimationFPS (bool bRestrictAnimFPS) [static]
Sets whether or not to lock animation updates to the animframerate
Definition at line 1826 of file KX_KetsjiEngine.cpp.
Referenced by GPG_Application::initEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::SetSceneConverter (KX_ISceneConverter * sceneconverter)
Definition at line 261 of file KX_KetsjiEngine.cpp.
References MT_assert.
Referenced by GPG_Application::startEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::SetTicRate (double ticrate) [static]
Sets the number of logic updates per second.
Definition at line 1796 of file KX_KetsjiEngine.cpp.
void KX_KetsjiEngine::SetTimingDisplay (bool frameRate, bool profile, bool properties)
Activates or deactivates timing information display.
Parameters:
frameRate Display for frame rate on or off.
profile Display for individual components on or off.
properties Display of scene object debug properties on or off.
Definition at line 1871 of file KX_KetsjiEngine.cpp.
Referenced by GPG_Application::initEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::SetUseFixedTime (bool bUseFixedTime)
Sets display of all frames.
Parameters:
bUseFixedTime New setting for display all frames.
Definition at line 1764 of file KX_KetsjiEngine.cpp.
Referenced by GPG_Application::initEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::SetUseOverrideFrameColor (bool overrideFrameColor)
Enables/disables the use of the framing bar color of the Blender file's scenes.
Parameters:
overrideFrameColor The new setting.
Definition at line 1935 of file KX_KetsjiEngine.cpp.
void KX_KetsjiEngine::SetWorldSettings (KX_WorldInfo * worldinfo)
Definition at line 1024 of file KX_KetsjiEngine.cpp.
References KX_WorldInfo::getAmbientColorBlue(), KX_WorldInfo::getAmbientColorGreen(), KX_WorldInfo::getAmbientColorRed(), KX_WorldInfo::getMistColorBlue(), KX_WorldInfo::getMistColorGreen(), KX_WorldInfo::getMistColorRed(), KX_WorldInfo::getMistDistance(), KX_WorldInfo::getMistStart(), KX_WorldInfo::hasMist(), KX_WorldInfo::hasWorld(), RAS_IRasterizer::KX_SOLID, RAS_IRasterizer::SetAmbientColor(), and RAS_IRasterizer::SetFog().
Referenced by Render(), ImageRender::Render(), and RenderDome().
void KX_KetsjiEngine::StartEngine (bool clearIpo)
Ketsji Init(), Initializes data-structures and converts data from Blender into Ketsji native (realtime) format also sets up the graphics context
Definition at line 400 of file KX_KetsjiEngine.cpp.
References DEFAULT_LOGIC_TIC_RATE, KX_ISystem::GetTimeInSeconds(), Scene::gm, GameData::maxlogicstep, GameData::maxphystep, KX_ISceneConverter::ResetPhysicsObjectsAnimationIpo(), GameData::ticrate, and KX_ISceneConverter::WritePhysicsObjectToAnimationIpo().
Referenced by GPG_Application::startEngine(), and StartKetsjiShell().
void KX_KetsjiEngine::StopEngine ()
Definition at line 1358 of file KX_KetsjiEngine.cpp.
References RAS_IRasterizer::Exit(), KX_ISceneConverter::RemoveScene(), and KX_ISceneConverter::TestHandlesPhysicsObjectToAnimationIpo().
Referenced by StartKetsjiShell(), and GPG_Application::stopEngine().
void KX_KetsjiEngine::SuspendScene (const STR_String & scenename)
Definition at line 1748 of file KX_KetsjiEngine.cpp.
References FindScene(), and KX_Scene::Suspend().
Referenced by KX_SceneActuator::Update().
Member Data Documentation
bool KX_KetsjiEngine::m_usedome
Definition at line 240 of file KX_KetsjiEngine.h.
Referenced by InitDome(), Render(), and ~KX_KetsjiEngine().
The documentation for this class was generated from the following files:
KX_KetsjiEngine.h
KX_KetsjiEngine.cpp