Blender: modifiers_bmesh.c File Reference
modifiers_bmesh.c File Reference
blenkernel
#include "BLI_math.h"
#include "MEM_guardedalloc.h"
#include "DNA_object_types.h"
#include "BLI_array.h"
#include "BKE_DerivedMesh.h"
#include "BKE_bmesh.h"
#include "BKE_tessmesh.h"
Functions
void DM_to_bmesh_ex (DerivedMesh *dm, BMesh *bm)
BMEditMesh * DM_to_editbmesh (DerivedMesh *dm, BMEditMesh *existing, int do_tessellate)
BMesh * DM_to_bmesh (DerivedMesh *dm)
Detailed Description
Definition in file modifiers_bmesh.c.
Function Documentation
BMesh* DM_to_bmesh (DerivedMesh * dm) [read]
Definition at line 189 of file modifiers_bmesh.c.
References bm_mesh_allocsize_default, BM_mesh_create(), and DM_to_bmesh_ex().
void DM_to_bmesh_ex (DerivedMesh * dm, BMesh * bm)
Definition at line 44 of file modifiers_bmesh.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BM_data_layer_add(), BM_EDGE, BM_edge_create(), BM_edge_flag_from_mflag(), BM_elem_float_data_set(), BM_FACE, BM_face_create_ngon(), BM_face_flag_from_mflag(), BM_iter_new(), BM_iter_step(), BM_LOOP, BM_LOOPS_OF_FACE, BM_VERT, BM_vert_create(), BM_vert_flag_from_mflag(), MVert::bweight, MEdge::bweight, CD_BWEIGHT, CD_CALLOC, CD_CREASE, CD_MASK_DERIVEDMESH, CD_NORMAL, MVert::co, copy_v3_v3(), MEdge::crease, CustomData_bmesh_get(), CustomData_bmesh_merge(), CustomData_has_layer(), CustomData_to_bmesh_block(), BMHeader::data, DerivedMesh::dupEdgeArray, DerivedMesh::dupVertArray, MLoop::e, BMesh::edata, DerivedMesh::edgeData, FALSE, MEdge::flag, MVert::flag, MPoly::flag, DerivedMesh::getLoopArray, DerivedMesh::getNumEdges, DerivedMesh::getNumVerts, DerivedMesh::getPolyArray, BMEdge::head, BMVert::head, BMFace::head, BMLoop::head, BMHeader::hflag, i, BMesh::ldata, DerivedMesh::loopData, MPoly::loopstart, BMFace::mat_nr, MPoly::mat_nr, MEM_callocN(), MEM_freeN(), MVert::no, BMFace::no, BMVert::no, normal_short_to_float_v3(), NULL, DerivedMesh::numPolyData, BMesh::pdata, DerivedMesh::polyData, MPoly::totloop, MLoop::v, MEdge::v1, MEdge::v2, BMesh::vdata, and DerivedMesh::vertData.
Referenced by bm_merge_dm_transform(), bpy_bmesh_from_object(), DM_to_bmesh(), and DM_to_editbmesh().
BMEditMesh* DM_to_editbmesh (DerivedMesh * dm, BMEditMesh * existing, int do_tessellate) [read]
Definition at line 163 of file modifiers_bmesh.c.
References BMEditMesh::bm, bm_mesh_allocsize_default, BM_mesh_create(), BMEdit_Create(), BMEdit_RecalcTessellation(), and DM_to_bmesh_ex().
Referenced by applyModifier(), arrayModifier_doArray(), and doEdgeSplit().