Blender: btContactConstraint.cpp File Reference
btContactConstraint.cpp File Reference
#include "btContactConstraint.h"
#include "BulletDynamics/Dynamics/btRigidBody.h"
#include "LinearMath/btVector3.h"
#include "btJacobianEntry.h"
#include "btContactSolverInfo.h"
#include "LinearMath/btMinMax.h"
#include "BulletCollision/NarrowPhaseCollision/btManifoldPoint.h"
Defines
#define ASSERT2 btAssert
#define USE_INTERNAL_APPLY_IMPULSE 1
Functions
void resolveSingleBilateral (btRigidBody &body1, const btVector3 &pos1, btRigidBody &body2, const btVector3 &pos2, btScalar distance, const btVector3 &normal, btScalar &impulse, btScalar timeStep)
resolveSingleBilateral is an obsolete methods used for vehicle friction between two dynamic objects
Define Documentation
#define ASSERT2 btAssert
Definition at line 71 of file btContactConstraint.cpp.
Referenced by resolveSingleBilateral().
#define USE_INTERNAL_APPLY_IMPULSE 1
Definition at line 73 of file btContactConstraint.cpp.
Function Documentation
void resolveSingleBilateral (btRigidBody & body1, const btVector3 & pos1, btRigidBody & body2, const btVector3 & pos2, btScalar distance, const btVector3 & normal, btScalar & impulse, btScalar timeStep)
resolveSingleBilateral is an obsolete methods used for vehicle friction between two dynamic objects
Definition at line 77 of file btContactConstraint.cpp.
References ASSERT2, btFabs(), btRigidBody::getAngularVelocity(), btTransform::getBasis(), btRigidBody::getCenterOfMassPosition(), btRigidBody::getCenterOfMassTransform(), btRigidBody::getInvInertiaDiagLocal(), btRigidBody::getInvMass(), btRigidBody::getLinearVelocity(), btRigidBody::getVelocityInLocalPoint(), and btMatrix3x3::transpose().
Referenced by btRaycastVehicle::updateFriction().