Blender: kernel_film.h File Reference
kernel_film.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device float4 film_map (KernelGlobals *kg, float4 irradiance, int sample)
__device uchar4 film_float_to_byte (float4 color)
__device void kernel_film_tonemap (KernelGlobals *kg, __global uchar4 *rgba, __global float *buffer, int sample, int resolution, int x, int y, int offset, int stride)
Function Documentation
__device uchar4 film_float_to_byte (float4 color)
Definition at line 38 of file kernel_film.h.
References clamp, uchar, float4::w, uchar4::w, float4::x, uchar4::x, float4::y, uchar4::y, float4::z, and uchar4::z.
Referenced by kernel_film_tonemap().
CCL_NAMESPACE_BEGIN __device float4 film_map (KernelGlobals * kg, float4 irradiance, int sample)
Definition at line 21 of file kernel_film.h.
References clamp, color_scene_linear_to_srgb(), kernel_data, float4::w, float4::x, float4::y, and float4::z.
Referenced by kernel_film_tonemap().
__device void kernel_film_tonemap (KernelGlobals * kg, __global uchar4 * rgba, __global float * buffer, int sample, int resolution, int x, int y, int offset, int stride)
Definition at line 51 of file kernel_film.h.
References __global, film_float_to_byte(), film_map(), and kernel_data.
Referenced by kernel_cpu_tonemap().