Blender: SpaceType Struct Reference
SpaceType Struct Reference
#include <BKE_screen.h>
Public Attributes
struct SpaceType * next
struct SpaceType * prev
char name [BKE_ST_MAXNAME]
int spaceid
int iconid
struct SpaceLink *(* new)(const struct bContext *C)
void(* free)(struct SpaceLink *)
void(* init)(struct wmWindowManager *, struct ScrArea *)
void(* listener)(struct ScrArea *, struct wmNotifier *)
void(* refresh)(const struct bContext *, struct ScrArea *)
struct SpaceLink *(* duplicate)(struct SpaceLink *)
void(* operatortypes)(void)
void(* keymap)(struct wmKeyConfig *)
void(* dropboxes)(void)
int(* context)(const struct bContext *, const char *, struct bContextDataResult *)
ListBase regiontypes
ListBase toolshelf
int keymapflag
Detailed Description
Definition at line 63 of file BKE_screen.h.
Member Data Documentation
int(* SpaceType::context)(const struct bContext *, const char *, struct bContextDataResult *)
Definition at line 94 of file BKE_screen.h.
Referenced by CTX_data_dir_get(), ctx_data_get(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_image(), ED_spacetype_logic(), ED_spacetype_node(), ED_spacetype_text(), and ED_spacetype_view3d().
void(* SpaceType::dropboxes)(void)
Definition at line 91 of file BKE_screen.h.
Referenced by ED_spacetype_console(), ED_spacetype_image(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_view3d(), and ED_spacetypes_init().
struct SpaceLink*(* SpaceType::duplicate)(struct SpaceLink *) [read]
Definition at line 84 of file BKE_screen.h.
Referenced by BKE_spacedata_copylist(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), and ED_spacetype_xxx().
void(* SpaceType::free)(struct SpaceLink *)
Definition at line 73 of file BKE_screen.h.
Referenced by BKE_spacedata_freelist(), ED_area_newspace(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), and ED_spacetype_xxx().
int SpaceType::iconid
Definition at line 68 of file BKE_screen.h.
void(* SpaceType::init)(struct wmWindowManager *, struct ScrArea *)
Definition at line 76 of file BKE_screen.h.
Referenced by ED_area_initialize(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), and ED_spacetype_xxx().
void(* SpaceType::keymap)(struct wmKeyConfig *)
Definition at line 89 of file BKE_screen.h.
Referenced by ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), ED_spacetype_xxx(), and ED_spacetypes_keymap().
int SpaceType::keymapflag
Definition at line 105 of file BKE_screen.h.
Referenced by ED_area_initialize().
void(* SpaceType::listener)(struct ScrArea *, struct wmNotifier *)
Definition at line 78 of file BKE_screen.h.
Referenced by ED_area_do_listen(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_ipo(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_text(), ED_spacetype_time(), and ED_spacetype_view3d().
char SpaceType::name[BKE_ST_MAXNAME]
Definition at line 66 of file BKE_screen.h.
Referenced by BKE_regiontype_from_id(), BKE_spacetype_register(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), and ED_spacetype_view3d().
struct SpaceLink*(* SpaceType::new)(const struct bContext *C) [read]
Definition at line 71 of file BKE_screen.h.
Referenced by ED_area_newspace(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), and ED_spacetype_xxx().
struct SpaceType* SpaceType::next
Definition at line 64 of file BKE_screen.h.
Referenced by BKE_spacedata_draw_locks(), BKE_spacetype_from_id(), BKE_spacetypes_free(), ED_spacetypes_init(), ED_spacetypes_keymap(), and screen_refresh_headersizes().
void(* SpaceType::operatortypes)(void)
Definition at line 87 of file BKE_screen.h.
Referenced by ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), ED_spacetype_xxx(), and ED_spacetypes_init().
struct SpaceType * SpaceType::prev
Definition at line 64 of file BKE_screen.h.
void(* SpaceType::refresh)(const struct bContext *, struct ScrArea *)
Definition at line 81 of file BKE_screen.h.
Referenced by ED_area_do_refresh(), ED_spacetype_action(), ED_spacetype_clip(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_node(), ED_spacetype_sequencer(), and ED_spacetype_time().
ListBase SpaceType::regiontypes
Definition at line 97 of file BKE_screen.h.
Referenced by BKE_regiontype_from_id(), BKE_spacedata_draw_locks(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), ED_spacetypes_keymap(), and spacetype_free().
int SpaceType::spaceid
Definition at line 67 of file BKE_screen.h.
Referenced by BKE_regiontype_from_id(), BKE_spacetype_from_id(), BKE_spacetype_register(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), and ED_spacetype_xxx().
ListBase SpaceType::toolshelf
Definition at line 100 of file BKE_screen.h.
Referenced by spacetype_free(), and view3d_panel_tool_shelf().
The documentation for this struct was generated from the following file:
BKE_screen.h