Blender: BKE_ipo.h File Reference
BKE_ipo.h File Reference
blenkernel
Functions
void do_versions_ipos_to_animato (struct Main *main)
void free_ipo (struct Ipo *ipo)
Detailed Description
Since:
March 2001
Author:
nzc
Joshua Leung
Definition in file BKE_ipo.h.
Function Documentation
void do_versions_ipos_to_animato (struct Main * main)
Definition at line 1683 of file ipo.c.
References Main::action, AnimData::action, action_to_animato(), action_to_animdata(), add_empty_action(), IpoCurve::adrcode, BKE_animdata_from_id(), BKE_id_add_animdata(), BLI_freelinkN(), Ipo::blocktype, Main::camera, bAction::chanbase, bPose::chanbase, Object::constraints, bPoseChannel::constraints, Ipo::curve, Main::curve, bAction::curves, Scene::ed, ELEM, ListBase::first, ID::flag, Sequence::flag, free_fcurves(), G, G_DEBUG, bAction::groups, Curve::id, Lamp::id, Camera::id, Tex::id, World::id, Material::id, Key::id, Ipo::id, Object::id, ID_OB, ID_SCE, bAction::idroot, if(), Main::ipo, bConstraintChannel::ipo, ipo_to_animato(), ipo_to_animdata(), Main::key, Main::lamp, LIB_FAKEUSER, Main::mat, Sequence::name, bConstraintChannel::name, bConstraint::name, bPoseChannel::name, ID::name, bConstraintChannel::next, bConstraint::next, bPoseChannel::next, ID::next, nlastrips_to_animdata(), NULL, Main::object, Object::pose, Main::scene, SEQ_BEGIN, SEQ_COLOR, SEQ_END, SEQ_FAC1, SEQ_FAC_OPACITY, SEQ_FAC_SPEED, SEQ_IMAGE, SEQ_META, SEQ_MOVIE, SEQ_SCENE, SEQ_SPEED, SEQ_USE_EFFECT_DEFAULT_FADE, Editing::seqbasep, Main::tex, Sequence::type, ID::us, Main::versionfile, and Main::world.
Referenced by setup_app_data(), and StartKetsjiShell().
void free_ipo (struct Ipo * ipo)
Definition at line 84 of file ipo.c.
References IpoCurve::bezt, BLI_freelinkN(), IpoCurve::bp, Ipo::curve, IpoCurve::driver, ListBase::first, G, G_DEBUG, Ipo::id, MEM_freeN(), ID::name, and IpoCurve::next.
Referenced by free_libblock(), and join_mesh_exec().