Blender: StencilMask Class Reference
StencilMask Class Reference
#include <subd_stencil.h>
Public Member Functions
StencilMask ()
StencilMask (int size)
void resize (int size)
StencilMask & operator= (float value)
void operator+= (const StencilMask &mask)
void operator-= (const StencilMask &mask)
void operator*= (float scale)
void operator/= (float scale)
int size () const
float operator[] (int i) const
float & operator[] (int i)
float sum () const
bool is_normalized () const
void normalize ()
Detailed Description
Definition at line 34 of file subd_stencil.h.
Constructor & Destructor Documentation
CCL_NAMESPACE_BEGIN StencilMask::StencilMask ()
Definition at line 26 of file subd_stencil.cpp.
StencilMask::StencilMask (int size)
Definition at line 30 of file subd_stencil.cpp.
Member Function Documentation
bool StencilMask::is_normalized () const
Definition at line 92 of file subd_stencil.cpp.
References fabsf, and sum().
Referenced by SubdAccBuilder::computeCornerStencil(), and SubdAccBuilder::computeEdgeStencil().
void StencilMask::normalize ()
Definition at line 97 of file subd_stencil.cpp.
References sum().
Referenced by SubdAccBuilder::computeCornerStencil(), and SubdAccBuilder::computeInteriorStencil().
void StencilMask::operator*= (float scale)
Definition at line 68 of file subd_stencil.cpp.
References i, and size().
void StencilMask::operator+= (const StencilMask & mask)
Definition at line 50 of file subd_stencil.cpp.
References assert, i, and size().
void StencilMask::operator-= (const StencilMask & mask)
Definition at line 59 of file subd_stencil.cpp.
References assert, i, and size().
void StencilMask::operator/= (float scale)
Definition at line 76 of file subd_stencil.cpp.
StencilMask & StencilMask::operator= (float value)
Definition at line 41 of file subd_stencil.cpp.
References i, and size().
float& StencilMask::operator[] (int i) [inline]
Definition at line 52 of file subd_stencil.h.
References i.
float StencilMask::operator[] (int i) const [inline]
Definition at line 51 of file subd_stencil.h.
References i.
void StencilMask::resize (int size)
Definition at line 36 of file subd_stencil.cpp.
int StencilMask::size () const [inline]
Definition at line 49 of file subd_stencil.h.
Referenced by SubdAccBuilder::computeBoundaryTangentStencils(), operator*=(), operator+=(), operator-=(), operator=(), and sum().
float StencilMask::sum () const
Definition at line 81 of file subd_stencil.cpp.
References i, and size().
Referenced by is_normalized(), and normalize().
The documentation for this class was generated from the following files:
subd_stencil.h
subd_stencil.cpp