Blender: AUD_ConverterFunctions.cpp File Reference
AUD_ConverterFunctions.cpp File Reference
#include "AUD_ConverterFunctions.h"
#include "AUD_Buffer.h"
Defines
#define AUD_U8_0 0x80
#define AUD_S16_MAX ((int16_t)0x7FFF)
#define AUD_S16_MIN ((int16_t)0x8000)
#define AUD_S16_FLT 32767.0f
#define AUD_S32_MAX ((int32_t)0x7FFFFFFF)
#define AUD_S32_MIN ((int32_t)0x80000000)
#define AUD_S32_FLT 2147483647.0f
#define AUD_FLT_MAX 1.0f
#define AUD_FLT_MIN -1.0f
Functions
void AUD_convert_u8_s16 (data_t *target, data_t *source, int length)
void AUD_convert_u8_s24_be (data_t *target, data_t *source, int length)
void AUD_convert_u8_s24_le (data_t *target, data_t *source, int length)
void AUD_convert_u8_s32 (data_t *target, data_t *source, int length)
void AUD_convert_u8_float (data_t *target, data_t *source, int length)
void AUD_convert_u8_double (data_t *target, data_t *source, int length)
void AUD_convert_s16_u8 (data_t *target, data_t *source, int length)
void AUD_convert_s16_s24_be (data_t *target, data_t *source, int length)
void AUD_convert_s16_s24_le (data_t *target, data_t *source, int length)
void AUD_convert_s16_s32 (data_t *target, data_t *source, int length)
void AUD_convert_s16_float (data_t *target, data_t *source, int length)
void AUD_convert_s16_double (data_t *target, data_t *source, int length)
void AUD_convert_s24_u8_be (data_t *target, data_t *source, int length)
void AUD_convert_s24_u8_le (data_t *target, data_t *source, int length)
void AUD_convert_s24_s16_be (data_t *target, data_t *source, int length)
void AUD_convert_s24_s16_le (data_t *target, data_t *source, int length)
void AUD_convert_s24_s24 (data_t *target, data_t *source, int length)
void AUD_convert_s24_s32_be (data_t *target, data_t *source, int length)
void AUD_convert_s24_s32_le (data_t *target, data_t *source, int length)
void AUD_convert_s24_float_be (data_t *target, data_t *source, int length)
void AUD_convert_s24_float_le (data_t *target, data_t *source, int length)
void AUD_convert_s24_double_be (data_t *target, data_t *source, int length)
void AUD_convert_s24_double_le (data_t *target, data_t *source, int length)
void AUD_convert_s32_u8 (data_t *target, data_t *source, int length)
void AUD_convert_s32_s16 (data_t *target, data_t *source, int length)
void AUD_convert_s32_s24_be (data_t *target, data_t *source, int length)
void AUD_convert_s32_s24_le (data_t *target, data_t *source, int length)
void AUD_convert_s32_float (data_t *target, data_t *source, int length)
void AUD_convert_s32_double (data_t *target, data_t *source, int length)
void AUD_convert_float_u8 (data_t *target, data_t *source, int length)
void AUD_convert_float_s16 (data_t *target, data_t *source, int length)
void AUD_convert_float_s24_be (data_t *target, data_t *source, int length)
void AUD_convert_float_s24_le (data_t *target, data_t *source, int length)
void AUD_convert_float_s32 (data_t *target, data_t *source, int length)
void AUD_convert_float_double (data_t *target, data_t *source, int length)
void AUD_convert_double_u8 (data_t *target, data_t *source, int length)
void AUD_convert_double_s16 (data_t *target, data_t *source, int length)
void AUD_convert_double_s24_be (data_t *target, data_t *source, int length)
void AUD_convert_double_s24_le (data_t *target, data_t *source, int length)
void AUD_convert_double_s32 (data_t *target, data_t *source, int length)
void AUD_convert_double_float (data_t *target, data_t *source, int length)
Detailed Description
Definition in file AUD_ConverterFunctions.cpp.
Define Documentation
#define AUD_FLT_MAX 1.0f
Definition at line 40 of file AUD_ConverterFunctions.cpp.
Referenced by AUD_convert_double_s16(), AUD_convert_double_s24_be(), AUD_convert_double_s24_le(), AUD_convert_double_s32(), AUD_convert_double_u8(), AUD_convert_float_s16(), AUD_convert_float_s24_be(), AUD_convert_float_s24_le(), AUD_convert_float_s32(), and AUD_convert_float_u8().
#define AUD_FLT_MIN -1.0f
Definition at line 41 of file AUD_ConverterFunctions.cpp.
Referenced by AUD_convert_double_s16(), AUD_convert_double_s24_be(), AUD_convert_double_s24_le(), AUD_convert_double_s32(), AUD_convert_float_s16(), AUD_convert_float_s24_be(), AUD_convert_float_s24_le(), and AUD_convert_float_s32().
#define AUD_S16_FLT 32767.0f
Definition at line 36 of file AUD_ConverterFunctions.cpp.
Referenced by AUD_convert_s16_double(), and AUD_convert_s16_float().
#define AUD_S16_MAX ((int16_t)0x7FFF)
Definition at line 34 of file AUD_ConverterFunctions.cpp.
Referenced by AUD_convert_double_s16(), and AUD_convert_float_s16().
#define AUD_S16_MIN ((int16_t)0x8000)
Definition at line 35 of file AUD_ConverterFunctions.cpp.
Referenced by AUD_convert_double_s16(), and AUD_convert_float_s16().
#define AUD_S32_FLT 2147483647.0f
Definition at line 39 of file AUD_ConverterFunctions.cpp.
Referenced by AUD_convert_s24_double_be(), AUD_convert_s24_double_le(), AUD_convert_s24_float_be(), AUD_convert_s24_float_le(), AUD_convert_s32_double(), and AUD_convert_s32_float().
#define AUD_S32_MAX ((int32_t)0x7FFFFFFF)
Definition at line 37 of file AUD_ConverterFunctions.cpp.
Referenced by AUD_convert_double_s24_be(), AUD_convert_double_s24_le(), AUD_convert_double_s32(), AUD_convert_float_s24_be(), AUD_convert_float_s24_le(), and AUD_convert_float_s32().
#define AUD_S32_MIN ((int32_t)0x80000000)
Definition at line 38 of file AUD_ConverterFunctions.cpp.
Referenced by AUD_convert_double_s24_be(), AUD_convert_double_s24_le(), AUD_convert_double_s32(), AUD_convert_float_s24_be(), AUD_convert_float_s24_le(), and AUD_convert_float_s32().
#define AUD_U8_0 0x80
Definition at line 33 of file AUD_ConverterFunctions.cpp.
Referenced by AUD_convert_s16_u8(), AUD_convert_s24_u8_be(), AUD_convert_s24_u8_le(), AUD_convert_s32_u8(), AUD_convert_u8_double(), AUD_convert_u8_float(), AUD_convert_u8_s16(), AUD_convert_u8_s24_be(), AUD_convert_u8_s24_le(), and AUD_convert_u8_s32().
Function Documentation
void AUD_convert_double_float (data_t * target, data_t * source, int length)
Definition at line 466 of file AUD_ConverterFunctions.cpp.
References i, and length().
void AUD_convert_double_s16 (data_t * target, data_t * source, int length)
Definition at line 400 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S16_MAX, AUD_S16_MIN, i, and length().
void AUD_convert_double_s24_be (data_t * target, data_t * source, int length)
Definition at line 415 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S32_MAX, AUD_S32_MIN, i, and length().
void AUD_convert_double_s24_le (data_t * target, data_t * source, int length)
Definition at line 433 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S32_MAX, AUD_S32_MIN, i, and length().
void AUD_convert_double_s32 (data_t * target, data_t * source, int length)
Definition at line 451 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S32_MAX, AUD_S32_MIN, i, and length().
void AUD_convert_double_u8 (data_t * target, data_t * source, int length)
Definition at line 384 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, i, and length().
void AUD_convert_float_double (data_t * target, data_t * source, int length)
Definition at line 376 of file AUD_ConverterFunctions.cpp.
References i.
Referenced by AUD_ConverterReader::AUD_ConverterReader(), AUD_FFMPEGWriter::AUD_FFMPEGWriter(), and AUD_Mixer::AUD_Mixer().
void AUD_convert_float_s16 (data_t * target, data_t * source, int length)
Definition at line 310 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S16_MAX, AUD_S16_MIN, i, and length().
Referenced by AUD_ConverterReader::AUD_ConverterReader(), AUD_FFMPEGWriter::AUD_FFMPEGWriter(), and AUD_Mixer::AUD_Mixer().
void AUD_convert_float_s24_be (data_t * target, data_t * source, int length)
Definition at line 325 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S32_MAX, AUD_S32_MIN, i, and length().
Referenced by AUD_ConverterReader::AUD_ConverterReader(), and AUD_Mixer::AUD_Mixer().
void AUD_convert_float_s24_le (data_t * target, data_t * source, int length)
Definition at line 343 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S32_MAX, AUD_S32_MIN, i, and length().
Referenced by AUD_ConverterReader::AUD_ConverterReader(), and AUD_Mixer::AUD_Mixer().
void AUD_convert_float_s32 (data_t * target, data_t * source, int length)
Definition at line 361 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, AUD_FLT_MIN, AUD_S32_MAX, AUD_S32_MIN, i, and length().
Referenced by AUD_ConverterReader::AUD_ConverterReader(), AUD_FFMPEGWriter::AUD_FFMPEGWriter(), and AUD_Mixer::AUD_Mixer().
void AUD_convert_float_u8 (data_t * target, data_t * source, int length)
Definition at line 294 of file AUD_ConverterFunctions.cpp.
References AUD_FLT_MAX, i, and length().
Referenced by AUD_ConverterReader::AUD_ConverterReader(), AUD_FFMPEGWriter::AUD_FFMPEGWriter(), and AUD_Mixer::AUD_Mixer().
void AUD_convert_s16_double (data_t * target, data_t * source, int length)
Definition at line 140 of file AUD_ConverterFunctions.cpp.
References AUD_S16_FLT, and i.
void AUD_convert_s16_float (data_t * target, data_t * source, int length)
Definition at line 132 of file AUD_ConverterFunctions.cpp.
References AUD_S16_FLT, and i.
void AUD_convert_s16_s24_be (data_t * target, data_t * source, int length)
Definition at line 98 of file AUD_ConverterFunctions.cpp.
References i.
void AUD_convert_s16_s24_le (data_t * target, data_t * source, int length)
Definition at line 111 of file AUD_ConverterFunctions.cpp.
References i.
void AUD_convert_s16_s32 (data_t * target, data_t * source, int length)
Definition at line 124 of file AUD_ConverterFunctions.cpp.
References i.
void AUD_convert_s16_u8 (data_t * target, data_t * source, int length)
Definition at line 91 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, i, and length().
void AUD_convert_s24_double_be (data_t * target, data_t * source, int length)
Definition at line 215 of file AUD_ConverterFunctions.cpp.
References AUD_S32_FLT, and i.
void AUD_convert_s24_double_le (data_t * target, data_t * source, int length)
Definition at line 226 of file AUD_ConverterFunctions.cpp.
References AUD_S32_FLT, and i.
void AUD_convert_s24_float_be (data_t * target, data_t * source, int length)
Definition at line 193 of file AUD_ConverterFunctions.cpp.
References AUD_S32_FLT, and i.
void AUD_convert_s24_float_le (data_t * target, data_t * source, int length)
Definition at line 204 of file AUD_ConverterFunctions.cpp.
References AUD_S32_FLT, and i.
void AUD_convert_s24_s16_be (data_t * target, data_t * source, int length)
Definition at line 160 of file AUD_ConverterFunctions.cpp.
References i, and length().
void AUD_convert_s24_s16_le (data_t * target, data_t * source, int length)
Definition at line 167 of file AUD_ConverterFunctions.cpp.
References i, and length().
void AUD_convert_s24_s24 (data_t * target, data_t * source, int length)
Definition at line 174 of file AUD_ConverterFunctions.cpp.
void AUD_convert_s24_s32_be (data_t * target, data_t * source, int length)
Definition at line 179 of file AUD_ConverterFunctions.cpp.
References i.
void AUD_convert_s24_s32_le (data_t * target, data_t * source, int length)
Definition at line 186 of file AUD_ConverterFunctions.cpp.
References i.
void AUD_convert_s24_u8_be (data_t * target, data_t * source, int length)
Definition at line 148 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, i, and length().
void AUD_convert_s24_u8_le (data_t * target, data_t * source, int length)
Definition at line 154 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, i, and length().
void AUD_convert_s32_double (data_t * target, data_t * source, int length)
Definition at line 286 of file AUD_ConverterFunctions.cpp.
References AUD_S32_FLT, and i.
void AUD_convert_s32_float (data_t * target, data_t * source, int length)
Definition at line 278 of file AUD_ConverterFunctions.cpp.
References AUD_S32_FLT, i, and length().
void AUD_convert_s32_s16 (data_t * target, data_t * source, int length)
Definition at line 244 of file AUD_ConverterFunctions.cpp.
References i, and length().
void AUD_convert_s32_s24_be (data_t * target, data_t * source, int length)
Definition at line 252 of file AUD_ConverterFunctions.cpp.
References i, and length().
void AUD_convert_s32_s24_le (data_t * target, data_t * source, int length)
Definition at line 265 of file AUD_ConverterFunctions.cpp.
References i, and length().
void AUD_convert_s32_u8 (data_t * target, data_t * source, int length)
Definition at line 237 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, i, and length().
void AUD_convert_u8_double (data_t * target, data_t * source, int length)
Definition at line 84 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, and i.
void AUD_convert_u8_float (data_t * target, data_t * source, int length)
Definition at line 77 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, and i.
void AUD_convert_u8_s16 (data_t * target, data_t * source, int length)
Definition at line 43 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, and i.
void AUD_convert_u8_s24_be (data_t * target, data_t * source, int length)
Definition at line 50 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, and i.
void AUD_convert_u8_s24_le (data_t * target, data_t * source, int length)
Definition at line 60 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, and i.
void AUD_convert_u8_s32 (data_t * target, data_t * source, int length)
Definition at line 70 of file AUD_ConverterFunctions.cpp.
References AUD_U8_0, and i.