Blender: RAS_Rect Class Reference
RAS_Rect Class Reference
#include <RAS_Rect.h>
Public Member Functions
RAS_Rect ()
int GetWidth () const
int GetHeight () const
int GetLeft () const
int GetRight () const
int GetBottom () const
int GetTop () const
void SetLeft (int x1)
void SetBottom (int y1)
void SetRight (int x2)
void SetTop (int y2)
Public Attributes
int m_x1
int m_y1
int m_x2
int m_y2
Detailed Description
class.
RAS_Rect just encodes a simple rectangle.
Note:
Should be part of a generic library
Definition at line 44 of file RAS_Rect.h.
Constructor & Destructor Documentation
RAS_Rect::RAS_Rect () [inline]
Definition at line 51 of file RAS_Rect.h.
Member Function Documentation
int RAS_Rect::GetBottom () const [inline]
Definition at line 68 of file RAS_Rect.h.
References m_y1.
Referenced by KX_Dome::BindImages(), KX_KetsjiEngine::ClearFrame(), RAS_FramingManager::ComputeViewport(), KX_Dome::Draw(), ImageViewport::ImageViewport(), KX_BlenderCanvas::MakeScreenShot(), KX_BlenderCanvas::SetMousePosition(), and KX_BlenderCanvas::SetViewPort().
int RAS_Rect::GetHeight () const [inline]
Definition at line 56 of file RAS_Rect.h.
References m_y1, and m_y2.
Referenced by RAS_FramingManager::ComputeFrustum(), RAS_FramingManager::ComputeOrtho(), RAS_FramingManager::ComputeViewport(), KX_BlenderCanvas::GetHeight(), ImageViewport::ImageViewport(), KX_BlenderCanvas::SetMousePosition(), and KX_Dome::SetViewPort().
int RAS_Rect::GetLeft () const [inline]
Definition at line 60 of file RAS_Rect.h.
References m_x1.
Referenced by KX_Dome::BindImages(), KX_KetsjiEngine::ClearFrame(), RAS_FramingManager::ComputeViewport(), KX_Dome::Draw(), KX_BlenderCanvas::GetMouseX(), ImageViewport::ImageViewport(), KX_BlenderCanvas::MakeScreenShot(), KX_BlenderCanvas::SetMousePosition(), and KX_BlenderCanvas::SetViewPort().
int RAS_Rect::GetRight () const [inline]
Definition at line 64 of file RAS_Rect.h.
References m_x2.
Referenced by KX_KetsjiEngine::ClearFrame(), KX_Dome::DrawDomeFisheye(), KX_Dome::DrawDomeWarped(), KX_Dome::DrawEnvMap(), KX_Dome::DrawPanorama(), and KX_BlenderCanvas::MakeScreenShot().
int RAS_Rect::GetTop () const [inline]
Definition at line 72 of file RAS_Rect.h.
References m_y2.
Referenced by KX_KetsjiEngine::ClearFrame(), KX_Dome::DrawDomeFisheye(), KX_Dome::DrawDomeWarped(), KX_Dome::DrawEnvMap(), KX_Dome::DrawPanorama(), KX_BlenderCanvas::GetMouseY(), and KX_BlenderCanvas::MakeScreenShot().
int RAS_Rect::GetWidth () const [inline]
Definition at line 52 of file RAS_Rect.h.
References m_x1, and m_x2.
Referenced by RAS_FramingManager::ComputeFrustum(), RAS_FramingManager::ComputeOrtho(), RAS_FramingManager::ComputeViewport(), KX_BlenderCanvas::GetWidth(), ImageViewport::ImageViewport(), and KX_Dome::SetViewPort().
void RAS_Rect::SetBottom (int y1) [inline]
Definition at line 82 of file RAS_Rect.h.
References m_y1.
Referenced by KX_KetsjiEngine::ClearFrame(), RAS_FramingManager::ComputeViewport(), KX_KetsjiEngine::GetSceneViewport(), RAS_OpenGLRasterizer::SetRenderArea(), KX_Dome::SetViewPort(), KX_BlenderCanvas::SetViewPort(), and StartKetsjiShell().
void RAS_Rect::SetLeft (int x1) [inline]
Definition at line 77 of file RAS_Rect.h.
References m_x1.
Referenced by KX_KetsjiEngine::ClearFrame(), RAS_FramingManager::ComputeViewport(), KX_KetsjiEngine::GetSceneViewport(), RAS_OpenGLRasterizer::SetRenderArea(), KX_Dome::SetViewPort(), KX_BlenderCanvas::SetViewPort(), and StartKetsjiShell().
void RAS_Rect::SetRight (int x2) [inline]
Definition at line 87 of file RAS_Rect.h.
References m_x2.
Referenced by KX_KetsjiEngine::ClearFrame(), RAS_FramingManager::ComputeViewport(), KX_KetsjiEngine::GetSceneViewport(), RAS_OpenGLRasterizer::SetRenderArea(), KX_Dome::SetViewPort(), KX_BlenderCanvas::SetViewPort(), and StartKetsjiShell().
void RAS_Rect::SetTop (int y2) [inline]
Definition at line 92 of file RAS_Rect.h.
References m_y2.
Referenced by KX_KetsjiEngine::ClearFrame(), RAS_FramingManager::ComputeViewport(), KX_KetsjiEngine::GetSceneViewport(), RAS_OpenGLRasterizer::SetRenderArea(), KX_Dome::SetViewPort(), KX_BlenderCanvas::SetViewPort(), and StartKetsjiShell().
Member Data Documentation
int RAS_Rect::m_x1
Definition at line 47 of file RAS_Rect.h.
Referenced by GetLeft(), GetWidth(), GPC_Canvas::GPC_Canvas(), and SetLeft().
int RAS_Rect::m_x2
Definition at line 48 of file RAS_Rect.h.
Referenced by GetRight(), GetWidth(), GPC_Canvas::GPC_Canvas(), and SetRight().
int RAS_Rect::m_y1
Definition at line 47 of file RAS_Rect.h.
Referenced by GetBottom(), GetHeight(), GPC_Canvas::GPC_Canvas(), and SetBottom().
int RAS_Rect::m_y2
Definition at line 48 of file RAS_Rect.h.
Referenced by GetHeight(), GetTop(), GPC_Canvas::GPC_Canvas(), and SetTop().
The documentation for this class was generated from the following file:
RAS_Rect.h