Blender: KX_BlenderGL.h File Reference
KX_BlenderGL.h File Reference
Blender Routines
Functions
void BL_SwapBuffers (struct wmWindow *win)
void BL_warp_pointer (struct wmWindow *win, int x, int y)
void BL_MakeScreenShot (struct ScrArea *curarea, const char *filename)
void BL_HideMouse (struct wmWindow *win)
void BL_NormalMouse (struct wmWindow *win)
void BL_WaitMouse (struct wmWindow *win)
void BL_print_game_line (int fontid, const char *text, int size, int dpi, float *color, double *mat, float aspect)
void BL_print_gamedebug_line (const char *text, int xco, int yco, int width, int height)
void BL_print_gamedebug_line_padded (const char *text, int xco, int yco, int width, int height)
Detailed Description
Definition in file KX_BlenderGL.h.
Function Documentation
void BL_HideMouse (struct wmWindow * win)
Definition at line 213 of file KX_BlenderGL.cpp.
References CURSOR_NONE, and WM_cursor_set().
Referenced by KX_BlenderCanvas::SetMouseState().
void BL_MakeScreenShot (struct ScrArea * curarea, const char * filename)
Definition at line 255 of file KX_BlenderGL.cpp.
References BKE_add_image_extension(), BLI_path_abs(), ImBuf::ftype, G, IB_rect, IMB_allocImBuf(), IMB_freeImBuf(), IMB_saveiff(), MAX_FILE_LENGTH, MEM_freeN(), NULL, PNG, R_IMF_IMTYPE_PNG, ImBuf::rect, and screenshot().
Referenced by KX_BlenderCanvas::MakeScreenShot().
void BL_NormalMouse (struct wmWindow * win)
Definition at line 225 of file KX_BlenderGL.cpp.
References CURSOR_STD, and WM_cursor_set().
Referenced by KX_BlenderCanvas::SetMouseState().
void BL_print_game_line (int fontid, const char * text, int size, int dpi, float * color, double * mat, float aspect)
Definition at line 131 of file KX_BlenderGL.cpp.
References BLF_ASPECT, BLF_aspect(), BLF_disable(), BLF_draw(), BLF_enable(), BLF_matrix(), BLF_MATRIX, BLF_position(), BLF_size(), and DisableForText().
Referenced by KX_BlenderRenderTools::RenderText3D().
void BL_print_gamedebug_line (const char * text, int xco, int yco, int width, int height)
Definition at line 155 of file KX_BlenderGL.cpp.
References BLF_draw_default(), and DisableForText().
Referenced by KX_BlenderRenderTools::RenderText2D().
void BL_print_gamedebug_line_padded (const char * text, int xco, int yco, int width, int height)
Definition at line 182 of file KX_BlenderGL.cpp.
References BLF_draw_default(), and DisableForText().
Referenced by KX_BlenderRenderTools::RenderText2D().
void BL_SwapBuffers (struct wmWindow * win)
Definition at line 89 of file KX_BlenderGL.cpp.
References wm_window_swap_buffers().
Referenced by KX_BlenderCanvas::SwapBuffers().
void BL_WaitMouse (struct wmWindow * win)
Definition at line 219 of file KX_BlenderGL.cpp.
References CURSOR_WAIT, and WM_cursor_set().
Referenced by KX_BlenderCanvas::SetMouseState().
void BL_warp_pointer (struct wmWindow * win, int x, int y)
Definition at line 84 of file KX_BlenderGL.cpp.
References WM_cursor_warp().
Referenced by KX_BlenderCanvas::SetMousePosition().