Blender: openexr_stub.cpp File Reference
openexr_stub.cpp File Reference
OpenEXR
#include "openexr_api.h"
#include "openexr_multi.h"
Functions
void * IMB_exr_get_handle (void)
void IMB_exr_add_channel (void *handle, const char *layname, const char *channame, int xstride, int ystride, float *rect)
int IMB_exr_begin_read (void *handle, const char *filename, int *width, int *height)
int IMB_exr_begin_write (void *handle, const char *filename, int width, int height, int compress)
void IMB_exrtile_begin_write (void *handle, const char *filename, int mipmap, int width, int height, int tilex, int tiley)
void IMB_exr_set_channel (void *handle, const char *layname, const char *channame, int xstride, int ystride, float *rect)
void IMB_exr_read_channels (void *handle)
void IMB_exr_write_channels (void *handle)
void IMB_exrtile_write_channels (void *handle, int partx, int party, int level)
void IMB_exrtile_clear_channels (void *handle)
void IMB_exr_multilayer_convert (void *handle, void *base, void *(*addlayer)(void *base, char *str), void(*addpass)(void *base, void *lay, char *str, float *rect, int totchan, char *chan_id))
void IMB_exr_close (void *handle)
Detailed Description
Definition in file openexr_stub.cpp.
Function Documentation
void IMB_exr_add_channel (void * handle, const char * layname, const char * channame, int xstride, int ystride, float * rect)
Definition at line 37 of file openexr_stub.cpp.
References BLI_addtail(), BLI_strncpy(), ExrHandle::channels, data, EXR_LAY_MAXNAME, EXR_PASS_MAXNAME, EXR_TOT_MAXNAME, MEM_callocN(), ExrChannel::name, ExrChannel::rect, ExrChannel::xstride, and ExrChannel::ystride.
int IMB_exr_begin_read (void * handle, const char * filename, int * width, int * height)
Definition at line 39 of file openexr_stub.cpp.
References BLI_exists(), BLI_file_size(), data, ExrHandle::height, i, ExrHandle::ifile, IMB_exr_add_channel(), NULL, and ExrHandle::width.
int IMB_exr_begin_write (void * handle, const char * filename, int width, int height, int compress)
Definition at line 40 of file openexr_stub.cpp.
References ExrHandle::channels, data, ListBase::first, ExrHandle::height, ExrChannel::name, ExrChannel::next, NULL, ExrHandle::ofile, openexr_header_compression(), and ExrHandle::width.
void IMB_exr_close (void * handle)
Definition at line 57 of file openexr_stub.cpp.
References BLI_freelistN(), BLI_remlink(), ExrHandle::channels, data, exrhandles, ListBase::first, ExrHandle::ifile, ExrHandle::layers, MEM_freeN(), ExrLayer::next, ExrPass::next, NULL, ExrHandle::ofile, ExrLayer::passes, ExrPass::rect, and ExrHandle::tofile.
void* IMB_exr_get_handle (void)
Definition at line 36 of file openexr_stub.cpp.
References BLI_addtail(), data, exrhandles, MEM_callocN(), and NULL.
void IMB_exr_multilayer_convert (void * handle, void * base, void *(*)(void *base, char *str) addlayer, void(*)(void *base, void *lay, char *str, float *rect, int totchan, char *chan_id) addpass)
Definition at line 50 of file openexr_stub.cpp.
References ExrPass::chan_id, data, ListBase::first, ExrHandle::layers, ExrLayer::name, ExrPass::name, ExrLayer::next, ExrPass::next, NULL, ExrLayer::passes, ExrPass::rect, and ExrPass::totchan.
void IMB_exr_read_channels (void * handle)
Definition at line 45 of file openexr_stub.cpp.
References ExrHandle::channels, data, ListBase::first, ExrHandle::height, ExrHandle::ifile, ExrChannel::name, ExrChannel::next, ExrChannel::rect, ExrHandle::width, ExrChannel::xstride, and ExrChannel::ystride.
void IMB_exr_set_channel (void * handle, const char * layname, const char * channame, int xstride, int ystride, float * rect)
Definition at line 43 of file openexr_stub.cpp.
References BLI_findstring(), BLI_strncpy(), ExrHandle::channels, data, EXR_LAY_MAXNAME, EXR_PASS_MAXNAME, EXR_TOT_MAXNAME, ExrLayer::name, ExrChannel::rect, ExrChannel::xstride, and ExrChannel::ystride.
void IMB_exr_write_channels (void * handle)
Definition at line 46 of file openexr_stub.cpp.
References ExrHandle::channels, data, ListBase::first, ExrHandle::height, ExrChannel::name, ExrChannel::next, ExrHandle::ofile, ExrChannel::rect, ExrHandle::width, ExrChannel::xstride, and ExrChannel::ystride.
void IMB_exrtile_begin_write (void * handle, const char * filename, int mipmap, int width, int height, int tilex, int tiley)
Definition at line 41 of file openexr_stub.cpp.
References ExrHandle::channels, data, ListBase::first, ExrHandle::height, ExrHandle::mipmap, ExrChannel::name, ExrChannel::next, ExrHandle::tilex, ExrHandle::tiley, ExrHandle::tofile, and ExrHandle::width.
void IMB_exrtile_clear_channels (void * handle)
Definition at line 48 of file openexr_stub.cpp.
References BLI_freelistN(), ExrHandle::channels, and data.
void IMB_exrtile_write_channels (void * handle, int partx, int party, int level)
Definition at line 47 of file openexr_stub.cpp.
References ExrHandle::channels, data, ListBase::first, ExrChannel::name, ExrChannel::next, ExrChannel::rect, ExrHandle::tilex, ExrHandle::tiley, ExrHandle::tofile, ExrChannel::xstride, and ExrChannel::ystride.