Blender: BasicVector Namespace Reference
BasicVector Namespace Reference
Classes
class Vector3Dim
Typedefs
typedef Vector3Dim< int > Vec3Int
typedef Vector3Dim< Real > Vec3
Functions
template<class Scalar >
Scalar dot (const Vector3Dim< Scalar > &t, const Vector3Dim< Scalar > &v)
template<class Scalar >
Vector3Dim< Scalar > cross (const Vector3Dim< Scalar > &t, const Vector3Dim< Scalar > &v)
template<class Scalar >
Scalar norm (const VECTOR_TYPE &v)
Real normHelper (const Vector3Dim< Real > &v)
Real normHelper (const Real &v)
Real normHelper (const int &v)
template<class Scalar >
Scalar normNoSqrt (const VECTOR_TYPE &v)
template<class Scalar >
VECTOR_TYPE getNormalized (const VECTOR_TYPE &v)
template<class Scalar >
Scalar normalize (VECTOR_TYPE &v)
template<class Scalar >
VECTOR_TYPE reflectVector (const VECTOR_TYPE &t, const VECTOR_TYPE &n)
template<class Scalar >
VECTOR_TYPE refractVector (const VECTOR_TYPE &t, const VECTOR_TYPE &normal, Scalar nt, Scalar nair, int &refRefl)
template<class Scalar >
bool equal (const VECTOR_TYPE &v, const VECTOR_TYPE &c)
template<class Scalar >
void rgbToHsv (VECTOR_TYPE &V)
template<class Scalar >
void hsvToRgb (VECTOR_TYPE &V)
template<class Scalar >
std::ostream & operator<< (std::ostream &os, const BasicVector::Vector3Dim< Scalar > &i)
global string for formatting vector output in utilities.cpp
template<class Scalar >
std::istream & operator>> (std::istream &is, BasicVector::Vector3Dim< Scalar > &i)
Real getVecEpsilon ()
Typedef Documentation
typedef Vector3Dim<Real> BasicVector::Vec3
Definition at line 983 of file VEC3.h.
typedef Vector3Dim<int> BasicVector::Vec3Int
Definition at line 980 of file VEC3.h.
Function Documentation
template<class Scalar > Vector3Dim<Scalar> BasicVector::cross (const Vector3Dim< Scalar > & t, const Vector3Dim< Scalar > & v) [inline]
Definition at line 611 of file VEC3.h.
template<class Scalar > Scalar BasicVector::dot (const Vector3Dim< Scalar > & t, const Vector3Dim< Scalar > & v) [inline]
Definition at line 600 of file VEC3.h.
Referenced by BasicVector::Vector3Dim< Scalar >::projectNormalTo(), reflectVector(), and refractVector().
template<class Scalar > bool BasicVector::equal (const VECTOR_TYPE & v, const VECTOR_TYPE & c) [inline]
Definition at line 841 of file VEC3.h.
References ABS, and VECTOR_EPSILON.
template<class Scalar > VECTOR_TYPE BasicVector::getNormalized (const VECTOR_TYPE & v) [inline]
Definition at line 755 of file VEC3.h.
References fabs(), sqrt(), VECTOR_EPSILON, and VECTOR_TYPE.
Referenced by BasicVector::Vector3Dim< Scalar >::getOrthogonalntlVector3Dim().
Real BasicVector::getVecEpsilon () [inline]
Definition at line 977 of file VEC3.h.
References VECTOR_EPSILON.
template<class Scalar > void BasicVector::hsvToRgb (VECTOR_TYPE & V) [inline]
Definition at line 893 of file VEC3.h.
References g, and p.
template<class Scalar > Scalar BasicVector::norm (const VECTOR_TYPE & v) [inline]
Definition at line 722 of file VEC3.h.
References fabs(), sqrt(), and VECTOR_EPSILON.
Referenced by normalize(), and normHelper().
template<class Scalar > Scalar BasicVector::normalize (VECTOR_TYPE & v) [inline]
Definition at line 775 of file VEC3.h.
References fabs(), norm(), sqrt(), and VECTOR_EPSILON.
Real BasicVector::normHelper (const Vector3Dim< Real > & v) [inline]
Definition at line 729 of file VEC3.h.
References norm().
Real BasicVector::normHelper (const Real & v) [inline]
Definition at line 732 of file VEC3.h.
Real BasicVector::normHelper (const int & v) [inline]
Definition at line 735 of file VEC3.h.
template<class Scalar > Scalar BasicVector::normNoSqrt (const VECTOR_TYPE & v) [inline]
Definition at line 744 of file VEC3.h.
template<class Scalar > std::ostream& BasicVector::operator<< (std::ostream & os, const BasicVector::Vector3Dim< Scalar > & i)
global string for formatting vector output in utilities.cpp
Definition at line 942 of file VEC3.h.
References globVecFormatStr, i, and snprintf.
template<class Scalar > std::istream& BasicVector::operator>> (std::istream & is, BasicVector::Vector3Dim< Scalar > & i)
Definition at line 963 of file VEC3.h.
template<class Scalar > VECTOR_TYPE BasicVector::reflectVector (const VECTOR_TYPE & t, const VECTOR_TYPE & n) [inline]
Definition at line 803 of file VEC3.h.
References dot(), and VECTOR_TYPE.
template<class Scalar > VECTOR_TYPE BasicVector::refractVector (const VECTOR_TYPE & t, const VECTOR_TYPE & normal, Scalar nt, Scalar nair, int & refRefl) [inline]
Definition at line 816 of file VEC3.h.
References dot(), and sqrt().
template<class Scalar > void BasicVector::rgbToHsv (VECTOR_TYPE & V) [inline]
Definition at line 853 of file VEC3.h.