Blender: WindowData.h File Reference
WindowData.h File Reference
Typedefs
typedef void(* WindowDataHandler)(void *priv, GHOST_EventHandle evt)
typedef struct _WindowData WindowData
Functions
WindowData * windowdata_new (void *data, WindowDataHandler handler)
void windowdata_handle (WindowData *wb, GHOST_EventHandle evt)
void windowdata_free (WindowData *wb)
Typedef Documentation
typedef struct _WindowData WindowData
Definition at line 29 of file WindowData.h.
typedef void(* WindowDataHandler)(void *priv, GHOST_EventHandle evt)
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) 2001-2002 by NaN Holding BV. All rights reserved.
The Original Code is: all of this file.
Contributor(s): none yet.
***** END GPL LICENSE BLOCK *****
Definition at line 28 of file WindowData.h.
Function Documentation
void windowdata_free (WindowData * wb)
Definition at line 53 of file WindowData.c.
References MEM_freeN().
Referenced by extrawindow_free(), loggerwindow_free(), and mainwindow_free().
void windowdata_handle (WindowData * wb, GHOST_EventHandle evt)
Definition at line 49 of file WindowData.c.
References _WindowData::data, and _WindowData::handler.
Referenced by multitest_event_handler().
WindowData* windowdata_new (void * data, WindowDataHandler handler)
Definition at line 41 of file WindowData.c.
References data, _WindowData::data, _WindowData::handler, and MEM_mallocN().
Referenced by extrawindow_new(), loggerwindow_new(), and mainwindow_new().