Blender: KX_RaySensor Class Reference
KX_RaySensor Class Reference
#include <KX_RaySensor.h>
Public Types
enum RayAxis {
KX_RAY_AXIS_POS_Y = 0, KX_RAY_AXIS_POS_X, KX_RAY_AXIS_POS_Z, KX_RAY_AXIS_NEG_X,
KX_RAY_AXIS_NEG_Y, KX_RAY_AXIS_NEG_Z
}
Public Member Functions
KX_RaySensor (class SCA_EventManager *eventmgr, SCA_IObject *gameobj, const STR_String &propname, bool bFindMaterial, bool bXRay, double distance, int axis, class KX_Scene *ketsjiScene)
virtual ~KX_RaySensor ()
virtual CValue * GetReplica ()
virtual bool Evaluate ()
virtual bool IsPositiveTrigger ()
virtual void Init ()
bool RayHit (KX_ClientObjectInfo *client, KX_RayCast *result, void *const data)
bool NeedRayCast (KX_ClientObjectInfo *client)
virtual void Replace_IScene (SCA_IScene *val)
Detailed Description
Definition at line 44 of file KX_RaySensor.h.
Member Enumeration Documentation
enum KX_RaySensor::RayAxis
Enumerator:
KX_RAY_AXIS_POS_Y
KX_RAY_AXIS_POS_X
KX_RAY_AXIS_POS_Z
KX_RAY_AXIS_NEG_X
KX_RAY_AXIS_NEG_Y
KX_RAY_AXIS_NEG_Z
Definition at line 85 of file KX_RaySensor.h.
Constructor & Destructor Documentation
KX_RaySensor::KX_RaySensor (class SCA_EventManager * eventmgr, SCA_IObject * gameobj, const STR_String & propname, bool bFindMaterial, bool bXRay, double distance, int axis, class KX_Scene * ketsjiScene)
Definition at line 54 of file KX_RaySensor.cpp.
References Init().
Referenced by GetReplica().
KX_RaySensor::~KX_RaySensor () [virtual]
Definition at line 83 of file KX_RaySensor.cpp.
Member Function Documentation
bool KX_RaySensor::Evaluate () [virtual]
Implements SCA_ISensor.
Definition at line 183 of file KX_RaySensor.cpp.
References SCA_ILogicBrick::GetName(), KX_GameObject::GetParent(), SCA_ILogicBrick::GetParent(), KX_GameObject::GetPhysicsController(), KX_Scene::GetPhysicsEnvironment(), MT_Matrix3x3::inverse(), SCA_ISensor::m_level, SCA_ISensor::m_reset, KX_GameObject::NodeGetWorldOrientation(), KX_GameObject::NodeGetWorldPosition(), MT_Vector3::normalize(), NULL, KX_RayCast::RayTest(), CValue::Release(), SENS_RAY_NEG_X_AXIS, SENS_RAY_NEG_Y_AXIS, SENS_RAY_NEG_Z_AXIS, SENS_RAY_X_AXIS, SENS_RAY_Y_AXIS, and SENS_RAY_Z_AXIS.
CValue * KX_RaySensor::GetReplica (void) [virtual]
Implements SCA_ISensor.
Definition at line 90 of file KX_RaySensor.cpp.
References Init(), KX_RaySensor(), and SCA_ISensor::ProcessReplica().
void KX_RaySensor::Init (void) [virtual]
Reimplemented from SCA_ISensor.
Definition at line 75 of file KX_RaySensor.cpp.
References SCA_ISensor::m_invert, SCA_ISensor::m_reset, and NULL.
Referenced by GetReplica(), and KX_RaySensor().
bool KX_RaySensor::IsPositiveTrigger () [virtual]
Reimplemented from SCA_ISensor.
Definition at line 101 of file KX_RaySensor.cpp.
References SCA_ISensor::m_invert.
bool KX_RaySensor::NeedRayCast (KX_ClientObjectInfo * client)
Definition at line 156 of file KX_RaySensor.cpp.
References KX_ClientObjectInfo::ACTOR, CValue::GetProperty(), STR_String::Length(), KX_ClientObjectInfo::m_auxilary_info, KX_ClientObjectInfo::m_gameobject, KX_ClientObjectInfo::m_type, and NULL.
bool KX_RaySensor::RayHit (KX_ClientObjectInfo * client, KX_RayCast * result, void *const data)
Definition at line 111 of file KX_RaySensor.cpp.
References CValue::GetProperty(), STR_String::Length(), KX_ClientObjectInfo::m_auxilary_info, KX_ClientObjectInfo::m_gameobject, KX_RayCast::m_hitNormal, KX_RayCast::m_hitPoint, and NULL.
virtual void KX_RaySensor::Replace_IScene (SCA_IScene * val) [inline, virtual]
Reimplemented from SCA_ILogicBrick.
Definition at line 79 of file KX_RaySensor.h.
The documentation for this class was generated from the following files:
KX_RaySensor.h
KX_RaySensor.cpp