Blender: Progress Class Reference
Progress Class Reference
#include <util_progress.h>
Public Member Functions
Progress ()
Progress (Progress &progress)
Progress & operator= (Progress &progress)
void set_cancel (const string &cancel_message_)
bool get_cancel ()
string get_cancel_message ()
void set_cancel_callback (boost::function< void(void)> function)
void set_start_time (double start_time_)
void set_sample (int sample_, double sample_time_)
void get_sample (int &sample_, double &total_time_, double &sample_time_)
void set_status (const string &status_, const string &substatus_="")
void set_substatus (const string &substatus_)
void get_status (string &status_, string &substatus_)
void set_update ()
void set_update_callback (boost::function< void(void)> function)
Protected Attributes
thread_mutex progress_mutex
boost::function< void(void)> update_cb
boost::function< void(void)> cancel_cb
int sample
double start_time
double total_time
double sample_time
string status
string substatus
volatile bool cancel
string cancel_message
Detailed Description
Definition at line 35 of file util_progress.h.
Constructor & Destructor Documentation
Progress::Progress () [inline]
Definition at line 37 of file util_progress.h.
References cancel, cancel_cb, cancel_message, NULL, sample, sample_time, start_time, status, substatus, time_dt(), total_time, and update_cb.
Progress::Progress (Progress & progress) [inline]
Definition at line 51 of file util_progress.h.
Member Function Documentation
bool Progress::get_cancel () [inline]
Definition at line 74 of file util_progress.h.
References cancel, and cancel_cb.
Referenced by BVHBuild::add_references(), ObjectManager::apply_static_transforms(), BVH::build(), BVHBuild::build_node(), SVMShaderManager::device_update(), ObjectManager::device_update(), Scene::device_update(), ImageManager::device_update(), MeshManager::device_update(), LightManager::device_update(), MeshManager::device_update_attributes(), LightManager::device_update_background(), MeshManager::device_update_bvh(), LightManager::device_update_distribution(), MeshManager::device_update_mesh(), ObjectManager::device_update_transforms(), MeshManager::displace(), BVH::refit(), BlenderSession::render(), BVHBuild::run(), Session::run(), Session::run_cpu(), and Session::run_gpu().
string Progress::get_cancel_message () [inline]
Definition at line 82 of file util_progress.h.
References cancel_message, and progress_mutex.
Referenced by Session::run().
void Progress::get_sample (int & sample_, double & total_time_, double & sample_time_) [inline]
Definition at line 111 of file util_progress.h.
References progress_mutex, sample, sample_time, and total_time.
Referenced by display_info(), BlenderSession::get_progress(), operator=(), session_print_status(), and BlenderSession::write_render_result().
void Progress::get_status (string & status_, string & substatus_) [inline]
Definition at line 145 of file util_progress.h.
References progress_mutex, status, and substatus.
Referenced by display_info(), BlenderSession::get_status(), operator=(), and session_print_status().
Progress& Progress::operator= (Progress & progress) [inline]
Definition at line 56 of file util_progress.h.
References get_sample(), get_status(), progress_mutex, sample, sample_time, status, substatus, and total_time.
void Progress::set_cancel (const string & cancel_message_) [inline]
Definition at line 67 of file util_progress.h.
References cancel, cancel_message, and progress_mutex.
Referenced by keyboard(), Session::run_cpu(), Session::run_gpu(), BlenderSession::test_cancel(), and Session::~Session().
void Progress::set_cancel_callback (boost::function< void(void)> function) [inline]
Definition at line 88 of file util_progress.h.
References cancel_cb.
Referenced by BlenderSession::create_session().
void Progress::set_sample (int sample_, double sample_time_) [inline]
Definition at line 102 of file util_progress.h.
References progress_mutex, sample, sample_time, start_time, time_dt(), and total_time.
Referenced by Session::update_status_time().
void Progress::set_start_time (double start_time_) [inline]
Definition at line 95 of file util_progress.h.
References progress_mutex, and start_time.
Referenced by Session::reset_(), Session::run_cpu(), and Session::run_gpu().
void Progress::set_status (const string & status_, const string & substatus_ = "") [inline]
Definition at line 122 of file util_progress.h.
References progress_mutex, set_update(), start_time, status, substatus, time_dt(), and total_time.
Referenced by ObjectManager::device_update(), Scene::device_update(), ImageManager::device_update(), MeshManager::device_update(), MeshManager::device_update_attributes(), LightManager::device_update_background(), MeshManager::device_update_bvh(), LightManager::device_update_distribution(), MeshManager::device_update_mesh(), Session::run(), Session::run_cpu(), Session::run_gpu(), Session::update_scene(), Session::update_status_time(), and Session::~Session().
void Progress::set_substatus (const string & substatus_) [inline]
Definition at line 134 of file util_progress.h.
References progress_mutex, set_update(), start_time, substatus, time_dt(), and total_time.
Referenced by BVH::build(), Mesh::compute_bvh(), BVHBuild::progress_update(), and BVH::refit().
void Progress::set_update () [inline]
Definition at line 154 of file util_progress.h.
References update_cb.
Referenced by Session::run(), Session::run_cpu(), Session::run_gpu(), set_status(), and set_substatus().
void Progress::set_update_callback (boost::function< void(void)> function) [inline]
Definition at line 160 of file util_progress.h.
References update_cb.
Referenced by BlenderSession::create_session(), and session_init().
Member Data Documentation
volatile bool Progress::cancel [protected]
Definition at line 179 of file util_progress.h.
Referenced by get_cancel(), Progress(), and set_cancel().
boost::function<void(void)> Progress::cancel_cb [protected]
Definition at line 168 of file util_progress.h.
Referenced by get_cancel(), Progress(), and set_cancel_callback().
string Progress::cancel_message [protected]
Definition at line 180 of file util_progress.h.
Referenced by get_cancel_message(), Progress(), and set_cancel().
thread_mutex Progress::progress_mutex [protected]
Definition at line 166 of file util_progress.h.
Referenced by get_cancel_message(), get_sample(), get_status(), operator=(), set_cancel(), set_sample(), set_start_time(), set_status(), and set_substatus().
int Progress::sample [protected]
Definition at line 170 of file util_progress.h.
Referenced by get_sample(), operator=(), Progress(), and set_sample().
double Progress::sample_time [protected]
Definition at line 174 of file util_progress.h.
Referenced by get_sample(), operator=(), Progress(), and set_sample().
double Progress::start_time [protected]
Definition at line 172 of file util_progress.h.
Referenced by Progress(), set_sample(), set_start_time(), set_status(), and set_substatus().
string Progress::status [protected]
Definition at line 176 of file util_progress.h.
Referenced by get_status(), operator=(), Progress(), and set_status().
string Progress::substatus [protected]
Definition at line 177 of file util_progress.h.
Referenced by get_status(), operator=(), Progress(), set_status(), and set_substatus().
double Progress::total_time [protected]
Definition at line 173 of file util_progress.h.
Referenced by get_sample(), operator=(), Progress(), set_sample(), set_status(), and set_substatus().
boost::function<void(void)> Progress::update_cb [protected]
Definition at line 167 of file util_progress.h.
Referenced by Progress(), set_update(), and set_update_callback().
The documentation for this class was generated from the following file:
util_progress.h