Blender: BKE_DerivedMesh.h File Reference
BKE_DerivedMesh.h File Reference
#include "DNA_customdata_types.h"
#include "DNA_meshdata_types.h"
#include "BKE_customdata.h"
#include "BKE_bvhutils.h"
Classes
struct DMGridData
struct DMGridAdjacency
struct DMFlagMat
struct DerivedMesh
struct DMVertexAttribs
Defines
#define SUB_ELEMS_VERT 0
#define SUB_ELEMS_EDGE 2
#define SUB_ELEMS_FACE 50
Typedefs
typedef struct DMGridData DMGridData
typedef struct DMGridAdjacency DMGridAdjacency
typedef struct DMFlagMat DMFlagMat
typedef enum DerivedMeshType DerivedMeshType
typedef enum DMDrawOption DMDrawOption
typedef int(* DMSetMaterial)(int mat_nr, void *attribs)
typedef int(* DMCompareDrawOptions)(void *userData, int cur_index, int next_index)
typedef void(* DMSetDrawInterpOptions)(void *userData, int index, float t)
typedef DMDrawOption(* DMSetDrawOptions)(void *userData, int index)
typedef DMDrawOption(* DMSetDrawOptionsTex)(struct MTFace *tface, int has_vcol, int matnr)
typedef enum DMDrawFlag DMDrawFlag
typedef enum DMDirtyFlag DMDirtyFlag
typedef struct DerivedMesh DerivedMesh
typedef float EdgeVertWeight [SUB_ELEMS_EDGE][SUB_ELEMS_EDGE]
typedef float FaceVertWeight [SUB_ELEMS_FACE][SUB_ELEMS_FACE]
typedef struct DMVertexAttribs DMVertexAttribs
Enumerations
enum DerivedMeshType { DM_TYPE_CDDM, DM_TYPE_EDITBMESH, DM_TYPE_CCGDM }
enum DMDrawOption { DM_DRAW_OPTION_SKIP = 0, DM_DRAW_OPTION_NORMAL = 1, DM_DRAW_OPTION_NO_MCOL = 2, DM_DRAW_OPTION_STIPPLE = 3 }
enum DMDrawFlag { DM_DRAW_USE_COLORS = 1, DM_DRAW_ALWAYS_SMOOTH = 2 }
enum DMDirtyFlag { DM_DIRTY_TESS_CDLAYERS = 1 << 0 }
Functions
void DM_init_funcs (DerivedMesh *dm)
void DM_init (DerivedMesh *dm, DerivedMeshType type, int numVerts, int numEdges, int numFaces, int numLoops, int numPolys)
void DM_from_template (DerivedMesh *dm, DerivedMesh *source, DerivedMeshType type, int numVerts, int numEdges, int numFaces, int numLoops, int numPolys)
int DM_release (DerivedMesh *dm)
void DM_to_mesh (DerivedMesh *dm, struct Mesh *me, struct Object *ob)
struct BMEditMesh * DM_to_editbmesh (struct DerivedMesh *dm, struct BMEditMesh *existing, int do_tessellate)
void DM_to_bmesh_ex (struct DerivedMesh *dm, struct BMesh *bm)
struct BMesh * DM_to_bmesh (struct DerivedMesh *dm)
void DM_to_meshkey (DerivedMesh *dm, struct Mesh *me, struct KeyBlock *kb)
void DM_set_only_copy (DerivedMesh *dm, CustomDataMask mask)
void DM_add_vert_layer (struct DerivedMesh *dm, int type, int alloctype, void *layer)
void DM_add_edge_layer (struct DerivedMesh *dm, int type, int alloctype, void *layer)
void DM_add_tessface_layer (struct DerivedMesh *dm, int type, int alloctype, void *layer)
void DM_add_loop_layer (DerivedMesh *dm, int type, int alloctype, void *layer)
void DM_add_poly_layer (struct DerivedMesh *dm, int type, int alloctype, void *layer)
void * DM_get_vert_data (struct DerivedMesh *dm, int index, int type)
void * DM_get_edge_data (struct DerivedMesh *dm, int index, int type)
void * DM_get_tessface_data (struct DerivedMesh *dm, int index, int type)
void * DM_get_vert_data_layer (struct DerivedMesh *dm, int type)
void * DM_get_edge_data_layer (struct DerivedMesh *dm, int type)
void * DM_get_tessface_data_layer (struct DerivedMesh *dm, int type)
void * DM_get_poly_data_layer (struct DerivedMesh *dm, int type)
void * DM_get_loop_data_layer (struct DerivedMesh *dm, int type)
void DM_set_vert_data (struct DerivedMesh *dm, int index, int type, void *data)
void DM_set_edge_data (struct DerivedMesh *dm, int index, int type, void *data)
void DM_set_tessface_data (struct DerivedMesh *dm, int index, int type, void *data)
void DM_copy_vert_data (struct DerivedMesh *source, struct DerivedMesh *dest, int source_index, int dest_index, int count)
void DM_copy_edge_data (struct DerivedMesh *source, struct DerivedMesh *dest, int source_index, int dest_index, int count)
void DM_copy_tessface_data (struct DerivedMesh *source, struct DerivedMesh *dest, int source_index, int dest_index, int count)
void DM_copy_loop_data (struct DerivedMesh *source, struct DerivedMesh *dest, int source_index, int dest_index, int count)
void DM_copy_poly_data (struct DerivedMesh *source, struct DerivedMesh *dest, int source_index, int dest_index, int count)
void DM_free_vert_data (struct DerivedMesh *dm, int index, int count)
void DM_free_edge_data (struct DerivedMesh *dm, int index, int count)
void DM_free_tessface_data (struct DerivedMesh *dm, int index, int count)
void DM_free_loop_data (struct DerivedMesh *dm, int index, int count)
void DM_free_poly_data (struct DerivedMesh *dm, int index, int count)
void DM_DupPolys (DerivedMesh *source, DerivedMesh *target)
void DM_ensure_tessface (DerivedMesh *dm)
void DM_update_tessface_data (DerivedMesh *dm)
void DM_interp_vert_data (struct DerivedMesh *source, struct DerivedMesh *dest, int *src_indices, float *weights, int count, int dest_index)
void DM_interp_edge_data (struct DerivedMesh *source, struct DerivedMesh *dest, int *src_indices, float *weights, EdgeVertWeight *vert_weights, int count, int dest_index)
void DM_interp_tessface_data (struct DerivedMesh *source, struct DerivedMesh *dest, int *src_indices, float *weights, FaceVertWeight *vert_weights, int count, int dest_index)
void DM_swap_tessface_data (struct DerivedMesh *dm, int index, const int *corner_indices)
void DM_interp_loop_data (struct DerivedMesh *source, struct DerivedMesh *dest, int *src_indices, float *weights, int count, int dest_index)
void DM_interp_poly_data (struct DerivedMesh *source, struct DerivedMesh *dest, int *src_indices, float *weights, int count, int dest_index)
void vDM_ColorBand_store (struct ColorBand *coba)
float * mesh_get_mapped_verts_nors (struct Scene *scene, struct Object *ob)
DerivedMesh * mesh_get_derived_final (struct Scene *scene, struct Object *ob, CustomDataMask dataMask)
DerivedMesh * mesh_get_derived_deform (struct Scene *scene, struct Object *ob, CustomDataMask dataMask)
DerivedMesh * mesh_create_derived_for_modifier (struct Scene *scene, struct Object *ob, struct ModifierData *md, int build_shapekey_layers)
DerivedMesh * mesh_create_derived_render (struct Scene *scene, struct Object *ob, CustomDataMask dataMask)
DerivedMesh * getEditDerivedBMesh (struct BMEditMesh *em, struct Object *ob, float(*vertexCos)[3])
DerivedMesh * mesh_create_derived_index_render (struct Scene *scene, struct Object *ob, CustomDataMask dataMask, int index)
DerivedMesh * mesh_create_derived (struct Mesh *me, struct Object *ob, float(*vertCos)[3])
DerivedMesh * mesh_create_derived_view (struct Scene *scene, struct Object *ob, CustomDataMask dataMask)
DerivedMesh * mesh_create_derived_no_deform (struct Scene *scene, struct Object *ob, float(*vertCos)[3], CustomDataMask dataMask)
DerivedMesh * mesh_create_derived_no_deform_render (struct Scene *scene, struct Object *ob, float(*vertCos)[3], CustomDataMask dataMask)
DerivedMesh * mesh_create_derived_no_virtual (struct Scene *scene, struct Object *ob, float(*vertCos)[3], CustomDataMask dataMask)
DerivedMesh * mesh_create_derived_physics (struct Scene *scene, struct Object *ob, float(*vertCos)[3], CustomDataMask dataMask)
DerivedMesh * editbmesh_get_derived_base (struct Object *, struct BMEditMesh *em)
DerivedMesh * editbmesh_get_derived_cage (struct Scene *scene, struct Object *, struct BMEditMesh *em, CustomDataMask dataMask)
DerivedMesh * editbmesh_get_derived_cage_and_final (struct Scene *scene, struct Object *, struct BMEditMesh *em, DerivedMesh **final_r, CustomDataMask dataMask)
float(* editbmesh_get_vertex_cos (struct BMEditMesh *em, int *numVerts_r))[3]
int editbmesh_modifier_is_enabled (struct Scene *scene, struct ModifierData *md, DerivedMesh *dm)
void makeDerivedMesh (struct Scene *scene, struct Object *ob, struct BMEditMesh *em, CustomDataMask dataMask, int build_shapekey_layers)
int editbmesh_get_first_deform_matrices (struct Scene *, struct Object *, struct BMEditMesh *em, float(**deformmats)[3][3], float(**deformcos)[3])
void weight_to_rgb (float r_rgb[3], const float weight)
void DM_update_weight_mcol (struct Object *ob, struct DerivedMesh *dm, int const draw_flag, float *weights, int num, const int *indices)
void DM_vertex_attributes_from_gpu (DerivedMesh *dm, struct GPUVertexAttribs *gattribs, DMVertexAttribs *attribs)
void DM_add_tangent_layer (DerivedMesh *dm)
void DM_calc_auto_bump_scale (DerivedMesh *dm)
void DM_set_object_boundbox (struct Object *ob, DerivedMesh *dm)
void DM_init_origspace (DerivedMesh *dm)
char * DM_debug_info (DerivedMesh *dm)
void DM_debug_print (DerivedMesh *dm)
Define Documentation
#define SUB_ELEMS_EDGE 2
Definition at line 97 of file BKE_DerivedMesh.h.
#define SUB_ELEMS_FACE 50
Definition at line 98 of file BKE_DerivedMesh.h.
#define SUB_ELEMS_VERT 0
Definition at line 96 of file BKE_DerivedMesh.h.
Typedef Documentation
typedef struct DerivedMesh DerivedMesh
Definition at line 155 of file BKE_DerivedMesh.h.
typedef enum DerivedMeshType DerivedMeshType
typedef int(* DMCompareDrawOptions)(void *userData, int cur_index, int next_index)
Definition at line 140 of file BKE_DerivedMesh.h.
typedef enum DMDirtyFlag DMDirtyFlag
typedef enum DMDrawFlag DMDrawFlag
typedef enum DMDrawOption DMDrawOption
typedef struct DMFlagMat DMFlagMat
typedef struct DMGridAdjacency DMGridAdjacency
typedef struct DMGridData DMGridData
typedef void(* DMSetDrawInterpOptions)(void *userData, int index, float t)
Definition at line 141 of file BKE_DerivedMesh.h.
typedef DMDrawOption(* DMSetDrawOptions)(void *userData, int index)
Definition at line 142 of file BKE_DerivedMesh.h.
typedef DMDrawOption(* DMSetDrawOptionsTex)(struct MTFace *tface, int has_vcol, int matnr)
Definition at line 143 of file BKE_DerivedMesh.h.
typedef int(* DMSetMaterial)(int mat_nr, void *attribs)
Definition at line 139 of file BKE_DerivedMesh.h.
typedef struct DMVertexAttribs DMVertexAttribs
typedef float EdgeVertWeight[SUB_ELEMS_EDGE][SUB_ELEMS_EDGE]
Definition at line 565 of file BKE_DerivedMesh.h.
typedef float FaceVertWeight[SUB_ELEMS_FACE][SUB_ELEMS_FACE]
Definition at line 578 of file BKE_DerivedMesh.h.
Enumeration Type Documentation
enum DerivedMeshType
Enumerator:
DM_TYPE_CDDM
DM_TYPE_EDITBMESH
DM_TYPE_CCGDM
Definition at line 121 of file BKE_DerivedMesh.h.
enum DMDirtyFlag
Enumerator:
DM_DIRTY_TESS_CDLAYERS
Definition at line 150 of file BKE_DerivedMesh.h.
enum DMDrawFlag
Enumerator:
DM_DRAW_USE_COLORS
DM_DRAW_ALWAYS_SMOOTH
Definition at line 145 of file BKE_DerivedMesh.h.
enum DMDrawOption
Enumerator:
DM_DRAW_OPTION_SKIP
DM_DRAW_OPTION_NORMAL
DM_DRAW_OPTION_NO_MCOL
DM_DRAW_OPTION_STIPPLE
Definition at line 127 of file BKE_DerivedMesh.h.
Function Documentation
void DM_add_edge_layer (struct DerivedMesh * dm, int type, int alloctype, void * layer)
Definition at line 587 of file DerivedMesh.c.
References CustomData_add_layer(), DerivedMesh::edgeData, and DerivedMesh::numEdgeData.
Referenced by ccgDM_get_edge_data_layer(), and mesh_calc_modifiers().
void DM_add_loop_layer (DerivedMesh * dm, int type, int alloctype, void * layer)
Definition at line 597 of file DerivedMesh.c.
References CustomData_add_layer(), DerivedMesh::loopData, and DerivedMesh::numLoopData.
Referenced by editbmesh_calc_modifiers(), and mesh_calc_modifiers().
void DM_add_poly_layer (struct DerivedMesh * dm, int type, int alloctype, void * layer)
Definition at line 602 of file DerivedMesh.c.
References CustomData_add_layer(), DerivedMesh::numPolyData, and DerivedMesh::polyData.
Referenced by mesh_calc_modifiers().
void DM_add_tangent_layer (DerivedMesh * dm)
Definition at line 2456 of file DerivedMesh.c.
References BLI_memarena_free(), BLI_memarena_new(), BLI_MEMARENA_STD_BUFSIZE, BLI_memarena_use_calloc(), CD_CALLOC, CD_MTFACE, CD_NORMAL, CD_ORCO, CD_TANGENT, MVert::co, CustomData_get_layer_index(), DM_add_tessface_layer(), DM_get_tessface_data_layer(), DerivedMesh::faceData, find_vertex_tangent(), genTangSpaceDefault(), GetNormal(), GetNumFaces(), DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, GetNumVertsOfFace(), GetPosition(), DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceDataArray, GetTextureCoordinate(), DerivedMesh::getVertArray, DerivedMesh::getVertDataArray, i, len(), SMikkTSpaceInterface::m_getNormal, SMikkTSpaceInterface::m_getNumFaces, SMikkTSpaceInterface::m_getNumVerticesOfFace, SMikkTSpaceInterface::m_getPosition, SMikkTSpaceInterface::m_getTexCoord, SMikkTSpaceContext::m_pInterface, SMikkTSpaceContext::m_pUserData, SMikkTSpaceInterface::m_setTSpaceBasic, map_to_sphere(), MEM_callocN(), MEM_freeN(), SGLSLMeshToTangent::mface, SGLSLMeshToTangent::mtface, SGLSLMeshToTangent::mvert, normal_quad_v3(), normal_tri_v3(), normalize_v3_v3(), NULL, SGLSLMeshToTangent::numTessFaces, SGLSLMeshToTangent::orco, SGLSLMeshToTangent::precomputedFaceNormals, SetTSpace(), sum_or_add_vertex_tangent(), SGLSLMeshToTangent::tangent, tangent_from_uv(), MTFace::uv, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by BL_ConvertMesh(), DM_vertex_attributes_from_gpu(), do_multires_bake(), and init_render_mesh().
void DM_add_tessface_layer (struct DerivedMesh * dm, int type, int alloctype, void * layer)
Definition at line 592 of file DerivedMesh.c.
References CustomData_add_layer(), DerivedMesh::faceData, and DerivedMesh::numTessFaceData.
Referenced by ccgDM_get_tessface_data_layer(), DM_add_tangent_layer(), emDM_getTessFaceDataArray(), and getCCGDerivedMesh().
void DM_add_vert_layer (struct DerivedMesh * dm, int type, int alloctype, void * layer)
Definition at line 582 of file DerivedMesh.c.
References CustomData_add_layer(), DerivedMesh::numVertData, and DerivedMesh::vertData.
Referenced by add_orco_dm(), ccgDM_get_vert_data_layer(), distribute_threads_init_data(), do_hair_dynamics(), get_dm(), getEditDerivedBMesh(), and mesh_calc_modifiers().
void DM_calc_auto_bump_scale (DerivedMesh * dm)
Definition at line 2601 of file DerivedMesh.c.
References DerivedMesh::auto_bump_scale, CD_MTFACE, MVert::co, copy_v2_v2(), cross_v3_v3v3(), dot_v2v2(), dot_v3v3(), equals_v2v2(), equals_v3v3(), fabsf, DerivedMesh::getNumTessFaces, DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVertArray, i, len_v3(), norm(), offs, sqrtf, sub_v2_v2v2(), sub_v3_v3v3(), MTFace::uv, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by DM_vertex_attributes_from_gpu().
void DM_copy_edge_data (struct DerivedMesh * source, struct DerivedMesh * dest, int source_index, int dest_index, int count)
Definition at line 678 of file DerivedMesh.c.
References CustomData_copy_data(), and DerivedMesh::edgeData.
Referenced by applyModifier(), and doMirrorOnAxis().
void DM_copy_loop_data (struct DerivedMesh * source, struct DerivedMesh * dest, int source_index, int dest_index, int count)
Definition at line 692 of file DerivedMesh.c.
References CustomData_copy_data(), and DerivedMesh::loopData.
Referenced by applyModifier(), and doMirrorOnAxis().
void DM_copy_poly_data (struct DerivedMesh * source, struct DerivedMesh * dest, int source_index, int dest_index, int count)
Definition at line 699 of file DerivedMesh.c.
References CustomData_copy_data(), and DerivedMesh::polyData.
Referenced by applyModifier(), and doMirrorOnAxis().
void DM_copy_tessface_data (struct DerivedMesh * source, struct DerivedMesh * dest, int source_index, int dest_index, int count)
Definition at line 685 of file DerivedMesh.c.
References CustomData_copy_data(), and DerivedMesh::faceData.
Referenced by explodeMesh(), and get_dface().
void DM_copy_vert_data (struct DerivedMesh * source, struct DerivedMesh * dest, int source_index, int dest_index, int count)
Definition at line 671 of file DerivedMesh.c.
References CustomData_copy_data(), and DerivedMesh::vertData.
Referenced by applyModifier(), cutEdges(), doMirrorOnAxis(), explodeMesh(), and getCCGDerivedMesh().
char* DM_debug_info (DerivedMesh * dm)
Definition at line 3122 of file DerivedMesh.c.
References BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), dm_debug_info_layers(), DM_get_loop_data_layer(), DM_get_poly_data_layer(), DM_TYPE_CCGDM, DM_TYPE_CDDM, and DM_TYPE_EDITBMESH.
Referenced by DM_debug_print().
void DM_debug_print (DerivedMesh * dm)
Definition at line 3170 of file DerivedMesh.c.
References DM_debug_info(), MEM_freeN(), and str.
Referenced by ConvertCSGDescriptorsToDerivedMesh().
void DM_DupPolys (DerivedMesh * source, DerivedMesh * target)
Definition at line 345 of file DerivedMesh.c.
References CD_ASSIGN, CD_DUPLICATE, CD_MASK_DERIVEDMESH, CD_MLOOP, CD_MPOLY, CustomData_add_layer(), CustomData_copy(), CustomData_free(), CustomData_has_layer(), DerivedMesh::dupLoopArray, DerivedMesh::dupPolyArray, DerivedMesh::loopData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, and DerivedMesh::polyData.
Referenced by cddm_copy_ex().
void DM_ensure_tessface (DerivedMesh * dm)
Definition at line 369 of file DerivedMesh.c.
References BLI_assert, CD_POLYINDEX, CustomData_has_layer(), DerivedMesh::dirty, DM_DIRTY_TESS_CDLAYERS, DM_update_tessface_data(), DerivedMesh::faceData, DerivedMesh::getNumPolys, DerivedMesh::getNumTessFaces, DerivedMesh::recalcTessellation, and DerivedMesh::type.
Referenced by applyModifier(), BL_ConvertMesh(), connect_hair(), ConvertCSGDescriptorsToDerivedMesh(), curve_calc_modifiers_post(), deformVerts(), distribute_threads_init_data(), dynamicPaint_Modifier_do(), editbmesh_calc_modifiers(), particle_intersect_dm(), particle_system_update(), and CcdShapeConstructionInfo::SetMesh().
void DM_free_edge_data (struct DerivedMesh * dm, int index, int count)
Definition at line 711 of file DerivedMesh.c.
References CustomData_free_elem(), and DerivedMesh::edgeData.
void DM_free_loop_data (struct DerivedMesh * dm, int index, int count)
Definition at line 721 of file DerivedMesh.c.
References CustomData_free_elem(), and DerivedMesh::loopData.
void DM_free_poly_data (struct DerivedMesh * dm, int index, int count)
Definition at line 726 of file DerivedMesh.c.
References CustomData_free_elem(), and DerivedMesh::polyData.
void DM_free_tessface_data (struct DerivedMesh * dm, int index, int count)
Definition at line 716 of file DerivedMesh.c.
References CustomData_free_elem(), and DerivedMesh::faceData.
void DM_free_vert_data (struct DerivedMesh * dm, int index, int count)
Definition at line 706 of file DerivedMesh.c.
References CustomData_free_elem(), and DerivedMesh::vertData.
void DM_from_template (DerivedMesh * dm, DerivedMesh * source, DerivedMeshType type, int numVerts, int numEdges, int numFaces, int numLoops, int numPolys)
Definition at line 293 of file DerivedMesh.c.
References CD_CALLOC, CD_MASK_DERIVEDMESH, CustomData_copy(), DerivedMesh::dirty, DM_init_funcs(), DerivedMesh::edgeData, DerivedMesh::faceData, DerivedMesh::loopData, DerivedMesh::needsFree, DerivedMesh::numEdgeData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, DerivedMesh::numVertData, DerivedMesh::polyData, DerivedMesh::type, and DerivedMesh::vertData.
Referenced by cddm_copy_ex(), CDDM_from_template(), and getCCGDerivedMesh().
void* DM_get_edge_data (struct DerivedMesh * dm, int index, int type)
Definition at line 612 of file DerivedMesh.c.
References CustomData_get(), and DerivedMesh::edgeData.
Referenced by ccgDM_get_edge_data(), cdDM_create(), DM_init_funcs(), and getCCGDerivedMesh().
void* DM_get_edge_data_layer (struct DerivedMesh * dm, int type)
Definition at line 630 of file DerivedMesh.c.
References CD_MEDGE, CustomData_get_layer(), DerivedMesh::edgeData, and DerivedMesh::getEdgeArray.
Referenced by ccgDM_get_edge_data_layer(), CDDM_calc_edges(), cdDM_create(), cdDM_drawMappedEdges(), cdDM_foreachMappedEdge(), DM_init_funcs(), and mesh_calc_modifiers().
void* DM_get_loop_data_layer (struct DerivedMesh * dm, int type)
Definition at line 651 of file DerivedMesh.c.
References CustomData_get_layer(), and DerivedMesh::loopData.
Referenced by DM_debug_info().
void* DM_get_poly_data_layer (struct DerivedMesh * dm, int type)
Definition at line 646 of file DerivedMesh.c.
References CustomData_get_layer(), and DerivedMesh::polyData.
Referenced by applyModifier(), DM_debug_info(), getCCGDerivedMesh(), mesh_calc_modifiers(), and ss_sync_from_derivedmesh().
void* DM_get_tessface_data (struct DerivedMesh * dm, int index, int type)
Definition at line 617 of file DerivedMesh.c.
References CustomData_get(), and DerivedMesh::faceData.
Referenced by ccgDM_get_tessface_data(), cdDM_create(), and DM_init_funcs().
void* DM_get_tessface_data_layer (struct DerivedMesh * dm, int type)
Definition at line 638 of file DerivedMesh.c.
References CD_MFACE, CustomData_get_layer(), DerivedMesh::faceData, and DerivedMesh::getTessFaceArray.
Referenced by add_tface_color_layer(), ccgDM_drawFacesTex_common(), ccgDM_drawUVEdges(), ccgDM_get_tessface_data_layer(), cdDM_create(), cdDM_drawFacesTex_common(), cdDM_drawMappedFaces(), cdDM_drawUVEdges(), DM_add_tangent_layer(), DM_init_funcs(), do_multires_bake(), draw_dm_faces_sel(), draw_mesh_fancy(), draw_mesh_textured_old(), emDM_getTessFaceDataArray(), getCCGDerivedMesh(), gpu_buffer_color_type(), GPU_buffer_copy_uv(), GPU_buffer_copy_uvedge(), and gpu_buffer_setup_type().
void* DM_get_vert_data (struct DerivedMesh * dm, int index, int type)
Definition at line 607 of file DerivedMesh.c.
References CustomData_get(), and DerivedMesh::vertData.
Referenced by ccgDM_get_vert_data(), cdDM_create(), and DM_init_funcs().
void* DM_get_vert_data_layer (struct DerivedMesh * dm, int type)
Definition at line 622 of file DerivedMesh.c.
References CD_MVERT, CustomData_get_layer(), DerivedMesh::getVertArray, and DerivedMesh::vertData.
Referenced by add_orco_dm(), calc_weightpaint_vert_array(), ccgDM_get_vert_data_layer(), cdDM_create(), cdDM_foreachMappedVert(), DM_init_funcs(), do_hair_dynamics(), getCCGDerivedMesh(), mesh_calc_modifiers(), psys_face_mat(), and psys_mat_hair_to_orco().
void DM_init (DerivedMesh * dm, DerivedMeshType type, int numVerts, int numEdges, int numFaces, int numLoops, int numPolys)
Definition at line 276 of file DerivedMesh.c.
References DerivedMesh::auto_bump_scale, DerivedMesh::dirty, DM_init_funcs(), DerivedMesh::needsFree, DerivedMesh::numEdgeData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, DerivedMesh::numVertData, and DerivedMesh::type.
Referenced by CDDM_from_mesh(), CDDM_new(), and getEditDerivedBMesh().
void DM_init_funcs (DerivedMesh * dm)
Definition at line 246 of file DerivedMesh.c.
References DerivedMesh::bvhCache, bvhcache_init(), dm_dupEdgeArray(), dm_dupFaceArray(), dm_dupLoopArray(), dm_dupPolyArray(), dm_dupVertArray(), DM_get_edge_data(), DM_get_edge_data_layer(), DM_get_tessface_data(), DM_get_tessface_data_layer(), DM_get_vert_data(), DM_get_vert_data_layer(), dm_getEdgeArray(), dm_getEdgeCData(), dm_getLoopArray(), dm_getLoopCData(), dm_getPolyArray(), dm_getPolyCData(), dm_getTessFaceArray(), dm_getTessFaceCData(), dm_getVertArray(), dm_getVertCData(), DerivedMesh::dupEdgeArray, DerivedMesh::dupLoopArray, DerivedMesh::dupPolyArray, DerivedMesh::dupTessFaceArray, DerivedMesh::dupVertArray, DerivedMesh::getEdgeArray, DerivedMesh::getEdgeData, DerivedMesh::getEdgeDataArray, DerivedMesh::getEdgeDataLayout, DerivedMesh::getLoopArray, DerivedMesh::getLoopDataLayout, DerivedMesh::getPolyArray, DerivedMesh::getPolyDataLayout, DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceData, DerivedMesh::getTessFaceDataArray, DerivedMesh::getTessFaceDataLayout, DerivedMesh::getVertArray, DerivedMesh::getVertData, DerivedMesh::getVertDataArray, and DerivedMesh::getVertDataLayout.
Referenced by DM_from_template(), and DM_init().
void DM_init_origspace (DerivedMesh * dm)
Definition at line 3070 of file DerivedMesh.c.
References CD_ORIGSPACE_MLOOP, copy_v2_v2(), CustomData_get_layer(), DerivedMesh::dirty, DM_DIRTY_TESS_CDLAYERS, DerivedMesh::getNumPolys, DerivedMesh::getPolyArray, i, DerivedMesh::loopData, MPoly::loopstart, MPoly::totloop, and OrigSpaceLoop::uv.
Referenced by editbmesh_calc_modifiers(), and mesh_calc_modifiers().
void DM_interp_edge_data (struct DerivedMesh * source, struct DerivedMesh * dest, int * src_indices, float * weights, EdgeVertWeight * vert_weights, int count, int dest_index)
Definition at line 739 of file DerivedMesh.c.
References CustomData_interp(), and DerivedMesh::edgeData.
void DM_interp_loop_data (struct DerivedMesh * source, struct DerivedMesh * dest, int * src_indices, float * weights, int count, int dest_index)
Definition at line 762 of file DerivedMesh.c.
References CustomData_interp(), DerivedMesh::loopData, and NULL.
void DM_interp_poly_data (struct DerivedMesh * source, struct DerivedMesh * dest, int * src_indices, float * weights, int count, int dest_index)
Definition at line 770 of file DerivedMesh.c.
References CustomData_interp(), NULL, and DerivedMesh::polyData.
void DM_interp_tessface_data (struct DerivedMesh * source, struct DerivedMesh * dest, int * src_indices, float * weights, FaceVertWeight * vert_weights, int count, int dest_index)
Definition at line 748 of file DerivedMesh.c.
References CustomData_interp(), and DerivedMesh::faceData.
void DM_interp_vert_data (struct DerivedMesh * source, struct DerivedMesh * dest, int * src_indices, float * weights, int count, int dest_index)
Definition at line 731 of file DerivedMesh.c.
References CustomData_interp(), NULL, and DerivedMesh::vertData.
Referenced by getCCGDerivedMesh().
int DM_release (DerivedMesh * dm)
Definition at line 321 of file DerivedMesh.c.
References DerivedMesh::bvhCache, bvhcache_free(), CustomData_free(), CustomData_free_temporary(), DerivedMesh::edgeData, DerivedMesh::faceData, GPU_drawobject_free(), DerivedMesh::loopData, DerivedMesh::needsFree, DerivedMesh::numEdgeData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, DerivedMesh::numVertData, DerivedMesh::polyData, and DerivedMesh::vertData.
Referenced by ccgDM_release(), cdDM_release(), and emDM_release().
void DM_set_edge_data (struct DerivedMesh * dm, int index, int type, void * data)
Definition at line 661 of file DerivedMesh.c.
References CustomData_set(), and DerivedMesh::edgeData.
void DM_set_object_boundbox (struct Object * ob, DerivedMesh * dm)
Definition at line 2873 of file DerivedMesh.c.
References Object::bb, boundbox_set_from_min_max(), DerivedMesh::getMinMax, INIT_MINMAX, max, MEM_callocN(), and min.
Referenced by editbmesh_build_data(), makeDispListCurveTypes(), and mesh_build_data().
void DM_set_only_copy (DerivedMesh * dm, CustomDataMask mask)
Definition at line 575 of file DerivedMesh.c.
References CustomData_set_only_copy(), DerivedMesh::edgeData, DerivedMesh::faceData, and DerivedMesh::vertData.
Referenced by editbmesh_calc_modifiers(), mesh_calc_modifiers(), multires_modifier_update_mdisps(), multires_subdivide(), and multiresModifier_base_apply().
void DM_set_tessface_data (struct DerivedMesh * dm, int index, int type, void * data)
Definition at line 666 of file DerivedMesh.c.
References CustomData_set(), and DerivedMesh::faceData.
void DM_set_vert_data (struct DerivedMesh * dm, int index, int type, void * data)
Definition at line 656 of file DerivedMesh.c.
References CustomData_set(), and DerivedMesh::vertData.
Referenced by getEditDerivedBMesh().
void DM_swap_tessface_data (struct DerivedMesh * dm, int index, const int * corner_indices)
Definition at line 757 of file DerivedMesh.c.
References CustomData_swap(), and DerivedMesh::faceData.
struct BMesh* DM_to_bmesh (struct DerivedMesh * dm) [read]
Definition at line 189 of file modifiers_bmesh.c.
References bm_mesh_allocsize_default, BM_mesh_create(), and DM_to_bmesh_ex().
void DM_to_bmesh_ex (struct DerivedMesh * dm, struct BMesh * bm)
Definition at line 44 of file modifiers_bmesh.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BM_data_layer_add(), BM_EDGE, BM_edge_create(), BM_edge_flag_from_mflag(), BM_elem_float_data_set(), BM_FACE, BM_face_create_ngon(), BM_face_flag_from_mflag(), BM_iter_new(), BM_iter_step(), BM_LOOP, BM_LOOPS_OF_FACE, BM_VERT, BM_vert_create(), BM_vert_flag_from_mflag(), MVert::bweight, MEdge::bweight, CD_BWEIGHT, CD_CALLOC, CD_CREASE, CD_MASK_DERIVEDMESH, CD_NORMAL, MVert::co, copy_v3_v3(), MEdge::crease, CustomData_bmesh_get(), CustomData_bmesh_merge(), CustomData_has_layer(), CustomData_to_bmesh_block(), BMHeader::data, DerivedMesh::dupEdgeArray, DerivedMesh::dupVertArray, MLoop::e, BMesh::edata, DerivedMesh::edgeData, FALSE, MEdge::flag, MVert::flag, MPoly::flag, DerivedMesh::getLoopArray, DerivedMesh::getNumEdges, DerivedMesh::getNumVerts, DerivedMesh::getPolyArray, BMEdge::head, BMVert::head, BMFace::head, BMLoop::head, BMHeader::hflag, i, BMesh::ldata, DerivedMesh::loopData, MPoly::loopstart, BMFace::mat_nr, MPoly::mat_nr, MEM_callocN(), MEM_freeN(), MVert::no, BMFace::no, BMVert::no, normal_short_to_float_v3(), NULL, DerivedMesh::numPolyData, BMesh::pdata, DerivedMesh::polyData, MPoly::totloop, MLoop::v, MEdge::v1, MEdge::v2, BMesh::vdata, and DerivedMesh::vertData.
Referenced by bm_merge_dm_transform(), bpy_bmesh_from_object(), DM_to_bmesh(), and DM_to_editbmesh().
struct BMEditMesh* DM_to_editbmesh (struct DerivedMesh * dm, struct BMEditMesh * existing, int do_tessellate) [read]
Definition at line 163 of file modifiers_bmesh.c.
References BMEditMesh::bm, bm_mesh_allocsize_default, BM_mesh_create(), BMEdit_Create(), BMEdit_RecalcTessellation(), and DM_to_bmesh_ex().
Referenced by applyModifier(), arrayModifier_doArray(), and doEdgeSplit().
void DM_to_mesh (DerivedMesh * dm, struct Mesh * me, struct Object * ob)
Definition at line 461 of file DerivedMesh.c.
References BKE_mesh_tessface_calc(), BLI_findlink(), Key::block, CD_ASSIGN, CD_DUPLICATE, CD_MASK_MESH, CD_MDISPS, CD_MEDGE, CD_MLOOP, CD_MPOLY, CD_MVERT, CD_SHAPEKEY, CustomData_add_layer(), CustomData_copy(), CustomData_free(), CustomData_get_layer(), CustomData_has_layer(), DerivedMesh::dupEdgeArray, DerivedMesh::dupLoopArray, DerivedMesh::dupPolyArray, DerivedMesh::dupVertArray, DerivedMesh::edgeData, Mesh::fdata, DerivedMesh::getNumEdges, DerivedMesh::getNumLoops, DerivedMesh::getNumPolys, DerivedMesh::getNumVerts, Key::id, Mesh::id, Mesh::key, Mesh::ldata, DerivedMesh::loopData, mesh_update_customdata_pointers(), Mesh::mloop, Mesh::mpoly, ID::name, NULL, DerivedMesh::polyData, shapekey_layers_to_keyblocks(), Object::shapenr, Mesh::totedge, Mesh::totface, Mesh::totloop, Mesh::totpoly, Mesh::totvert, TRUE, KeyBlock::uid, ID::us, and DerivedMesh::vertData.
Referenced by convert_exec(), modifier_apply_obdata(), NewBooleanMesh(), and nurbs_to_mesh().
void DM_to_meshkey (DerivedMesh * dm, struct Mesh * me, struct KeyBlock * kb)
Definition at line 555 of file DerivedMesh.c.
References CD_MVERT, MVert::co, copy_v3_v3(), KeyBlock::data, Key::elemsize, DerivedMesh::getNumVerts, DerivedMesh::getVertDataArray, Mesh::key, MEM_callocN(), MEM_freeN(), KeyBlock::totelem, and Mesh::totvert.
Referenced by join_mesh_shapes_exec(), and modifier_apply_shape().
void DM_update_tessface_data (DerivedMesh * dm)
Definition at line 396 of file DerivedMesh.c.
References CD_MLOOPCOL, CD_MTEXPOLY, CD_ORIGSPACE_MLOOP, CD_POLYINDEX, CD_PREVIEW_MLOOPCOL, CustomData_from_bmeshpoly(), CustomData_get_layer(), CustomData_has_layer(), CustomData_number_of_layers(), DerivedMesh::dirty, DM_DIRTY_TESS_CDLAYERS, G, G_DEBUG, DerivedMesh::getLoopArray, DerivedMesh::getLoopDataLayout, DerivedMesh::getNumTessFaces, DerivedMesh::getPolyArray, DerivedMesh::getPolyDataLayout, DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceDataLayout, i, mesh_loops_to_mface_corners(), MLoop::v, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by DM_ensure_tessface(), and mesh_calc_modifiers().
void DM_update_weight_mcol (struct Object * ob, struct DerivedMesh * dm, int const draw_flag, float * weights, int num, const int * indices)
Definition at line 1128 of file DerivedMesh.c.
References BLI_array_declare, BLI_array_growitems, calc_colors_from_weights_array(), calc_weightpaint_vert_array(), CD_ASSIGN, CD_CALLOC, CD_PREVIEW_MCOL, CD_PREVIEW_MLOOPCOL, copy_v4_v4_char(), CustomData_add_layer(), CustomData_get_layer(), DerivedMesh::dirty, DM_DIRTY_TESS_CDLAYERS, DerivedMesh::faceData, DerivedMesh::getLoopArray, DerivedMesh::getLoopDataLayout, DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, DerivedMesh::getPolyArray, DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceDataArray, i, DerivedMesh::loopData, MPoly::loopstart, MEM_callocN(), MEM_freeN(), NULL, DerivedMesh::numPolyData, stored_cb, and MPoly::totloop.
Referenced by applyModifier(), dynamicPaint_Modifier_apply(), and mesh_calc_modifiers().
void DM_vertex_attributes_from_gpu (DerivedMesh * dm, struct GPUVertexAttribs * gattribs, DMVertexAttribs * attribs)
Definition at line 2746 of file DerivedMesh.c.
References DMVertexAttribs::array, DerivedMesh::auto_bump_scale, CD_MCOL, CD_MLOOPCOL, CD_MLOOPUV, CD_MTFACE, CD_ORCO, CD_TANGENT, CustomData_get_active_layer_index(), CustomData_get_layer_index(), CustomData_get_named_layer_index(), CustomDataLayer::data, DM_add_tangent_layer(), DM_calc_auto_bump_scale(), DM_TYPE_EDITBMESH, DMVertexAttribs::emOffset, DerivedMesh::getLoopDataLayout, DerivedMesh::getTessFaceDataLayout, GPUVertexAttribs::glindex, DMVertexAttribs::glIndex, GPUVertexAttribs::gltexco, DMVertexAttribs::glTexco, GPUVertexAttribs::layer, CustomData::layers, DMVertexAttribs::mcol, GPUVertexAttribs::name, NULL, CustomDataLayer::offset, DMVertexAttribs::orco, DMVertexAttribs::tang, DMVertexAttribs::tface, GPUVertexAttribs::totlayer, DMVertexAttribs::totmcol, DMVertexAttribs::totorco, DMVertexAttribs::tottang, DMVertexAttribs::tottface, DerivedMesh::type, GPUVertexAttribs::type, and DerivedMesh::vertData.
Referenced by ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), cdDM_drawMappedFacesGLSL(), cdDM_drawMappedFacesMat(), emDM_drawMappedFacesGLSL(), and emDM_drawMappedFacesMat().
DerivedMesh* editbmesh_get_derived_base (struct Object * , struct BMEditMesh * em)
Definition at line 2301 of file DerivedMesh.c.
References getEditDerivedBMesh(), and NULL.
Referenced by draw_mesh_object(), draw_object_mesh_instance(), and snapObject().
DerivedMesh* editbmesh_get_derived_cage (struct Scene * scene, struct Object * , struct BMEditMesh * em, CustomDataMask dataMask)
Definition at line 2289 of file DerivedMesh.c.
References BMEditMesh::derivedCage, editbmesh_build_data(), and BMEditMesh::lastDataMask.
Referenced by crazyspace_get_mapped_editverts(), draw_object_backbufsel(), face_duplilist(), mesh_foreachScreenEdge(), mesh_foreachScreenFace(), mesh_foreachScreenVert(), peelObjects(), and vertex_duplilist().
DerivedMesh* editbmesh_get_derived_cage_and_final (struct Scene * scene, struct Object * , struct BMEditMesh * em, DerivedMesh ** final_r, CustomDataMask dataMask)
Definition at line 2275 of file DerivedMesh.c.
References BMEditMesh::derivedCage, BMEditMesh::derivedFinal, editbmesh_build_data(), and BMEditMesh::lastDataMask.
Referenced by BMBVH_NewBVH(), draw_mesh_object(), draw_uvs(), knifetool_init(), and meshdeformModifier_do().
int editbmesh_get_first_deform_matrices (struct Scene * , struct Object * , struct BMEditMesh * em, float(**) deformmats[3][3], float(**) deformcos[3])
Definition at line 323 of file crazyspace.c.
References ModifierTypeInfo::deformMatricesEM, editbmesh_get_vertex_cos(), editbmesh_modifier_is_enabled(), eModifierTypeType_OnlyDeform, getEditDerivedBMesh(), i, MEM_callocN(), modifier_isCorrectableDeformed(), modifiers_clearErrors(), modifiers_getCageIndex(), modifiers_getVirtualModifierList(), modifierType_getInfo(), mti, ModifierData::next, NULL, DerivedMesh::release, ModifierTypeInfo::type, and unit_m3().
Referenced by createTransEditVerts().
float(* editbmesh_get_vertex_cos (struct BMEditMesh * em, int * numVerts_r))[3]
Definition at line 1836 of file DerivedMesh.c.
References BMIter::bm, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, BMVert::co, copy_v3_v3(), cos(), i, MEM_mallocN(), and NULL.
Referenced by editbmesh_calc_modifiers(), and editbmesh_get_first_deform_matrices().
int editbmesh_modifier_is_enabled (struct Scene * scene, struct ModifierData * md, DerivedMesh * dm)
Definition at line 1853 of file DerivedMesh.c.
References eModifierMode_Editmode, eModifierMode_Realtime, eModifierTypeFlag_RequiresOriginalData, ModifierTypeInfo::flags, modifier_isEnabled(), modifier_setError(), modifierType_getInfo(), mti, TIP_, and ModifierData::type.
Referenced by editbmesh_calc_modifiers(), and editbmesh_get_first_deform_matrices().
DerivedMesh* getEditDerivedBMesh (struct BMEditMesh * em, struct Object * ob, float(*) vertexCos[3])
Referenced by editbmesh_calc_modifiers(), editbmesh_get_derived_base(), and editbmesh_get_first_deform_matrices().
void makeDerivedMesh (struct Scene * scene, struct Object * ob, struct BMEditMesh * em, CustomDataMask dataMask, int build_shapekey_layers)
Definition at line 2170 of file DerivedMesh.c.
References editbmesh_build_data(), and mesh_build_data().
Referenced by crazyspace_get_mapped_editverts(), facesel_face_pick(), object_handle_update(), and vertex_parent_set_exec().
DerivedMesh* mesh_create_derived (struct Mesh * me, struct Object * ob, float(*) vertCos[3])
Definition at line 779 of file DerivedMesh.c.
References CDDM_apply_vert_coords(), CDDM_calc_normals(), CDDM_from_mesh(), and NULL.
Referenced by mesh_create_derived_for_modifier(), and sculpt_get_first_deform_matrices().
DerivedMesh* mesh_create_derived_for_modifier (struct Scene * scene, struct Object * ob, struct ModifierData * md, int build_shapekey_layers)
Definition at line 796 of file DerivedMesh.c.
References add_shapekey_layers(), ModifierTypeInfo::applyModifier, BLI_findlink(), Key::block, Object::data, ModifierTypeInfo::deformVerts, eModifierMode_Realtime, eModifierTypeType_OnlyDeform, ModifierTypeInfo::isDisabled, Mesh::key, key_to_mesh(), MEM_freeN(), mesh_create_derived(), mesh_getVertexCos(), ModifierData::mode, modifierType_getInfo(), mti, NULL, DerivedMesh::release, ModifierData::scene, Object::shapenr, ModifierTypeInfo::type, and ModifierData::type.
Referenced by modifier_apply_obdata(), and modifier_apply_shape().
DerivedMesh* mesh_create_derived_index_render (struct Scene * scene, struct Object * ob, CustomDataMask dataMask, int index)
Definition at line 2214 of file DerivedMesh.c.
References mesh_calc_modifiers(), and NULL.
Referenced by initElbeemMesh().
DerivedMesh* mesh_create_derived_no_deform (struct Scene * scene, struct Object * ob, float(*) vertCos[3], CustomDataMask dataMask)
Definition at line 2232 of file DerivedMesh.c.
References mesh_calc_modifiers(), and NULL.
Referenced by mesh_deform_bind().
DerivedMesh* mesh_create_derived_no_deform_render (struct Scene * scene, struct Object * ob, float(*) vertCos[3], CustomDataMask dataMask)
Definition at line 2262 of file DerivedMesh.c.
References mesh_calc_modifiers(), and NULL.
DerivedMesh* mesh_create_derived_no_virtual (struct Scene * scene, struct Object * ob, float(*) vertCos[3], CustomDataMask dataMask)
Definition at line 2242 of file DerivedMesh.c.
References mesh_calc_modifiers(), and NULL.
Referenced by KX_NavMeshObject::BuildVertIndArrays(), createVertsTrisData(), and BL_ModifierDeformer::Update().
DerivedMesh* mesh_create_derived_physics (struct Scene * scene, struct Object * ob, float(*) vertCos[3], CustomDataMask dataMask)
Definition at line 2252 of file DerivedMesh.c.
References mesh_calc_modifiers(), and NULL.
Referenced by BL_ModifierDeformer::GetPhysicsMesh().
DerivedMesh* mesh_create_derived_render (struct Scene * scene, struct Object * ob, CustomDataMask dataMask)
Definition at line 2205 of file DerivedMesh.c.
References mesh_calc_modifiers(), and NULL.
Referenced by dupli_render_particle_set(), init_render_mesh(), init_render_object_data(), object_handle_update(), pointdensity_cache_object(), pointdensity_cache_psys(), and project_paint_begin().
DerivedMesh* mesh_create_derived_view (struct Scene * scene, struct Object * ob, CustomDataMask dataMask)
Definition at line 2223 of file DerivedMesh.c.
References mesh_calc_modifiers(), and NULL.
Referenced by meshdeform_bind_exec(), and NewBooleanMesh().
DerivedMesh* mesh_get_derived_deform (struct Scene * scene, struct Object * ob, CustomDataMask dataMask)
Definition at line 2194 of file DerivedMesh.c.
References Object::derivedDeform, Object::lastDataMask, and mesh_build_data().
Referenced by brush_add(), connect_hair(), dm_deform_recalc(), draw_mesh_text(), face_duplilist(), get_multires_dm(), join_mesh_shapes_exec(), multires_apply_smat(), particle_intersect_dm(), vertex_duplilist(), and vgroup_fix().
DerivedMesh* mesh_get_derived_final (struct Scene * scene, struct Object * ob, CustomDataMask dataMask)
Definition at line 2183 of file DerivedMesh.c.
References Object::derivedFinal, Object::lastDataMask, and mesh_build_data().
Referenced by add_verts_to_dgroups(), arrayModifier_doArray(), bbs_mesh_solid(), convert_exec(), draw_mesh_fancy(), draw_object_backbufsel(), draw_object_mesh_instance(), hide_show_exec(), imapaint_pick_uv(), mesh_get_mapped_verts_nors(), mesh_to_curve(), multiresModifier_reshape(), NewBooleanMesh(), GeometryExporter::operator()(), particle_intersect_dm(), peelObjects(), project_paint_begin(), sculpt_undo_restore(), sculpt_update_mesh_elements(), snapObject(), texture_paint_init(), and weight_sample_invoke().
float* mesh_get_mapped_verts_nors (struct Scene * scene, struct Object * ob)
Definition at line 2334 of file DerivedMesh.c.
References CD_MASK_BAREMESH, CD_MASK_ORIGINDEX, Object::data, DerivedMesh::foreachMappedVert, DerivedMesh::getVertCo, DerivedMesh::getVertNo, make_vertexcosnos__mapFunc(), MEM_callocN(), mesh_get_derived_final(), NULL, OB_MESH, DerivedMesh::release, Mesh::totvert, and Object::type.
Referenced by vpaint_stroke_test_start(), and wpaint_stroke_test_start().
void vDM_ColorBand_store (struct ColorBand * coba)
Definition at line 1070 of file DerivedMesh.c.
Referenced by init_userdef_do_versions().
void weight_to_rgb (float r_rgb[3], const float weight)
Definition at line 955 of file DerivedMesh.c.
References blend().
Referenced by draw_new_particle_system(), draw_uvs_stretch(), drawlattice__point(), psys_cache_edit_paths(), and weightpaint_color().