Blender: rna_lamp.c File Reference
rna_lamp.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_lamp_types.h"
#include "DNA_material_types.h"
#include "DNA_texture_types.h"
#include "BLI_math_base.h"
Functions
static void rna_def_lamp_mtex (BlenderRNA *brna)
static void rna_def_lamp_sky_settings (BlenderRNA *brna)
static void rna_def_lamp (BlenderRNA *brna)
static void rna_def_lamp_falloff (StructRNA *srna)
static void rna_def_lamp_shadow (StructRNA *srna, int spot, int area)
static void rna_def_point_lamp (BlenderRNA *brna)
static void rna_def_area_lamp (BlenderRNA *brna)
static void rna_def_spot_lamp (BlenderRNA *brna)
static void rna_def_sun_lamp (BlenderRNA *brna)
static void rna_def_hemi_lamp (BlenderRNA *brna)
void RNA_def_lamp (BlenderRNA *brna)
Variables
EnumPropertyItem lamp_type_items []
Detailed Description
Definition in file rna_lamp.c.
Function Documentation
static void rna_def_area_lamp (BlenderRNA * brna) [static]
Definition at line 539 of file rna_lamp.c.
References LA_AREA_RECT, LA_AREA_SQUARE, LA_SAMP_DITHER, LA_SAMP_JITTER, LA_SAMP_UMBRA, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_ENUM, PROP_FLOAT, PROP_NONE, rna_def_lamp_shadow(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_lamp().
static void rna_def_hemi_lamp (BlenderRNA * brna) [static]
Definition at line 776 of file rna_lamp.c.
References RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_lamp().
void RNA_def_lamp (BlenderRNA * brna)
Definition at line 786 of file rna_lamp.c.
References rna_def_area_lamp(), rna_def_hemi_lamp(), rna_def_lamp(), rna_def_lamp_mtex(), rna_def_point_lamp(), rna_def_spot_lamp(), and rna_def_sun_lamp().
static void rna_def_lamp (BlenderRNA * brna) [static]
Definition at line 328 of file rna_lamp.c.
References LA_LAYER, LA_NEG, LA_NO_DIFF, LA_NO_SPEC, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLOR, PROP_DISTANCE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, rna_def_animdata_common(), rna_def_mtex_common(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_refine_func(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_lamp().
static void rna_def_lamp_falloff (StructRNA * srna) [static]
Definition at line 401 of file rna_lamp.c.
References LA_FALLOFF_CONSTANT, LA_FALLOFF_CURVE, LA_FALLOFF_INVLINEAR, LA_FALLOFF_INVSQUARE, LA_FALLOFF_SLIDERS, LA_SPHERE, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_point_lamp(), and rna_def_spot_lamp().
static void rna_def_lamp_mtex (BlenderRNA * brna) [static]
Definition at line 169 of file rna_lamp.c.
References LAMAP_COL, LAMAP_SHAD, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, prop_texture_coordinates_items, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), TEXCO_GLOB, TEXCO_OBJECT, and TEXCO_VIEW.
Referenced by RNA_def_lamp().
static void rna_def_lamp_shadow (StructRNA * srna, int spot, int area) [static]
Definition at line 441 of file rna_lamp.c.
References LA_LAYER_SHADOW, LA_ONLYSHADOW, LA_SAMP_CONSTANT, LA_SAMP_HALTON, LA_SAMP_HAMMERSLEY, LA_SHAD_BUF, LA_SHAD_RAY, NULL, PROP_BOOLEAN, PROP_COLOR, PROP_DISTANCE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_area_lamp(), rna_def_point_lamp(), rna_def_spot_lamp(), and rna_def_sun_lamp().
static void rna_def_lamp_sky_settings (BlenderRNA * brna) [static]
Definition at line 218 of file rna_lamp.c.
References LA_SUN_EFFECT_AP, LA_SUN_EFFECT_SKY, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_NONE, ramp_blend_items, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_sun_lamp().
static void rna_def_point_lamp (BlenderRNA * brna) [static]
Definition at line 526 of file rna_lamp.c.
References rna_def_lamp_falloff(), rna_def_lamp_shadow(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_lamp().
static void rna_def_spot_lamp (BlenderRNA * brna) [static]
Definition at line 597 of file rna_lamp.c.
References LA_HALO, LA_SHADBUF_AUTO_END, LA_SHADBUF_AUTO_START, LA_SHADBUF_BOX, LA_SHADBUF_DEEP, LA_SHADBUF_GAUSS, LA_SHADBUF_HALFWAY, LA_SHADBUF_IRREGULAR, LA_SHADBUF_REGULAR, LA_SHADBUF_TENT, LA_SHOW_CONE, LA_SQUARE, M_PI, NULL, PROP_ANGLE, PROP_BOOLEAN, PROP_DISTANCE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, rna_def_lamp_falloff(), rna_def_lamp_shadow(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_lamp().
static void rna_def_sun_lamp (BlenderRNA * brna) [static]
Definition at line 754 of file rna_lamp.c.
References NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, rna_def_lamp_shadow(), rna_def_lamp_sky_settings(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_lamp().
Variable Documentation
EnumPropertyItem lamp_type_items[]
Initial value:
 {
    {LA_LOCAL, "POINT", 0, "Point", "Omnidirectional point light source"},
    {LA_SUN, "SUN", 0, "Sun", "Constant direction parallel ray light source"},
    {LA_SPOT, "SPOT", 0, "Spot", "Directional cone light source"},
    {LA_HEMI, "HEMI", 0, "Hemi", "180 degree constant light source"},
    {LA_AREA, "AREA", 0, "Area", "Directional area light source"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 161 of file rna_lamp.c.
Referenced by OBJECT_OT_lamp_add(), and RNA_def_main_lamps().