Blender: IMAGE.h File Reference
IMAGE.h File Reference
smoke
#include <stdlib.h>
#include <string>
#include <fstream>
#include <sstream>
#include <zlib.h>
#include <png.h>
Namespaces
namespace IMAGE
Functions
template<class T >
T ABS (T a)
template<class T >
void SWAP_POINTERS (T &a, T &b)
template<class T >
void CLAMP (T &a, T b=0., T c=1.)
template<class T >
T MIN (T a, T b)
template<class T >
T MAX (T a, T b)
template<class T >
T MAX3 (T a, T b, T c)
template<class T >
float MAX3V (T vec)
template<class T >
float MIN3V (T vec)
Detailed Description
Definition in file IMAGE.h.
Function Documentation
template<class T > T ABS (T a) [inline]
Definition at line 36 of file IMAGE.h.
template<class T > void CLAMP (T & a, T b = 0., T c = 1.) [inline]
Definition at line 46 of file IMAGE.h.
Referenced by actcon_get_tarmat(), apply_heights_callback(), apply_tangmat_callback(), applyModifier(), b_bone_deform(), basic_integrate(), bicubic_interpolation_color(), BKE_mesh_validate_arrays(), BKE_text_to_curve(), boxsample(), BPy_IDArray_ass_slice(), BPy_IDArray_slice(), brush_scale_size_exec(), buf_rectfill_area(), calc_text_rcts(), calc_weightpaint_vert_color(), change_character_exec(), change_spacing_exec(), clamp_nurb_order_u(), clamp_nurb_order_v(), clamp_weights(), collision_newton_rhapson(), collision_response(), Color_ass_slice(), Color_channel_hsv_set(), Color_hsv_set(), Color_slice(), colorbalance_cdl(), colorfn(), compute_scale_factor(), console_draw_string(), cp_shade_color3ub(), D(), defvert_normalize(), defvert_normalize_lock(), direct_link_object(), direct_link_pose(), displaceModifier_do(), dither_value(), do_colorband(), do_displace(), do_guides(), do_halo_tex(), do_huecorrect(), do_huecorrect_fac(), do_kink(), do_mesh_smooth_brush(), do_multires_smooth_brush(), do_particle_interpolation(), do_volume_tex(), do_weight_paint_normalize_all_active(), draw_image_grid(), draw_new_particle_system(), draw_seq_handle(), drawgrid(), dynamicPaint_doEffectStep(), dynamicPaint_doSmudge(), dynamicPaint_doWaveStep(), dynamicPaint_frameUpdate(), dynamicPaint_mixPaintColors(), dynamicPaint_outputSurfaceImage(), dynamicPaint_paintMesh(), dynamicPaint_paintSinglePoint(), dynamicPaint_prepareEffectStep(), dynamicPaint_surfacePreStep(), dynamicPaint_updatePointData(), ED_fileselect_layout_offset_rect(), EdgeSlide(), Euler_ass_slice(), Euler_slice(), explodeMesh(), find_nearest_seq(), fluidsimModifier_do(), flushTransSeq(), followpath_get_tarmat(), get_bin_float(), get_ccgdm_data(), get_strand_normal(), GPU_material_bind_uniforms(), headerTimeSlide(), hex_to_rgb(), image_sample_apply(), IMB_getmipmap(), IMB_overlayblend_thumb(), init_heights_data(), interpolate_particle_value(), isect_sweeping_sphere_tri_v3(), join_curve_exec(), layerInterp_mcol(), layerInterp_mloopcol(), line_clip_rect2f(), make_cb_table_byte(), make_sample_tables(), make_sep_waveform_view_from_ibuf_float(), make_vectorscope_view_from_ibuf_float(), make_waveform_view_from_ibuf_float(), mathutils_rna_vector_set(), Matrix_ass_slice(), Matrix_slice(), MatrixAccess_slice(), mesh_octree_add_nodes(), mesh_octree_get_base_offs(), meshdeform_dynamic_bind(), meshdeform_interp_w(), nearestPointToObstacle(), node_composit_exec_splitviewer(), node_resize_modal(), node_shader_exec_mix_rgb(), node_shader_exec_texture(), ob_parcurve(), occ_solid_angle(), ocean_texture(), paint_sample_color(), project_paint_begin(), project_paint_bucket_bounds(), project_paint_face_init(), prop_subscript_ass_array_slice(), psys_changed_type(), psys_get_particle_on_path(), psys_get_particle_state(), psys_thread_create_path(), quad_coord(), Quaternion_ass_slice(), Quaternion_slice(), radial_control_modal(), ray_ao_qmc(), RE_engine_begin_result(), RE_engine_update_progress(), RE_inithalo_particle(), region_scale_invoke(), region_scale_modal(), render_border_exec(), sample_apply(), sample_occ_tree(), screen_test_scale(), shade_input_set_uv(), shade_lamp_loop(), shade_one_light(), shade_volume_inside(), smooth(), snode_bg_viewmove_modal(), splineik_evaluate_bone(), surface_determineForceTargetPoints(), surfaceGenerateGrid(), system_step(), testsplitpoint(), text_scroll_modal(), textured_face_generate_uv(), textview_draw(), transform_evaluate(), ui_but_float_precision(), UI_ColorPtrBlendShade3ubv(), ui_draw_but_HSV_v(), ui_draw_but_HSVCIRCLE(), ui_draw_but_HSVCUBE(), UI_GetColorPtrBlendShade3ubv(), UI_GetColorPtrShade3ubv(), UI_GetThemeColorShade3fv(), ui_handler_panel_region(), ui_item_with_label(), ui_ndofedit_but_HSVCIRCLE(), ui_ndofedit_but_HSVCUBE(), ui_numedit_but_COLORBAND(), ui_numedit_but_HISTOGRAM(), ui_numedit_but_HSVCUBE(), ui_numedit_but_NUM(), ui_numedit_but_SLI(), ui_numedit_but_WAVEFORM(), UI_ThemeColorBlend(), UI_ThemeColorBlendShade(), UI_ThemeColorBlendShadeAlpha(), UI_ThemeColorShade(), UI_ThemeColorShadeAlpha(), UI_view2d_curRect_validate_resize(), UI_view2d_scrollers_calc(), uiStyleInit(), update_timestep(), uv_map_clip_correct(), v3d_editvertex_buts(), Vector_ass_slice(), Vector_slice(), vgroup_blend(), vgroup_levels(), vgroup_normalize(), view3d_center_camera_exec(), view3d_set_1_to_1_viewborder(), view_ghost_border_exec(), viewmove_apply(), viewzoom_apply(), voxeldatatex(), waveModifier_do(), weightvg_update_vg(), and wpaint_blend().
template<class T > T MAX (T a, T b) [inline]
Definition at line 55 of file IMAGE.h.
template<class T > T MAX3 (T a, T b, T c) [inline]
Definition at line 59 of file IMAGE.h.
References max, and T.
Referenced by area_poly_v3(), cache_occ_samples(), calc_sequence(), change_plugin_seq(), compatible_bump_compute(), dynamicPaint_doWaveStep(), dynamicPaint_prepareEffectStep(), find_first_points(), FLUID_3D::FLUID_3D(), getSurfaceDimension(), GPU_render_text(), imagewrap(), imagewraposa(), imagewraposa_aniso(), initlocalview(), len_v3_tri_side_max(), lensDistort(), mirror_facehash(), multiple_scattering_diffusion(), octree_fill_rayface(), p_chart_lscm_solve(), precache_resolution(), sample_occ(), sb_detect_face_collisionCached(), sb_detect_face_pointCached(), sequencer_add_effect_strip_exec(), shade_lamp_loop(), surfaceGenerateGrid(), view3d_all_exec(), and viewselected_exec().
template<class T > float MAX3V (T vec) [inline]
Definition at line 65 of file IMAGE.h.
References max.
Referenced by FLUID_3D::addSmokeTestCase(), WTURBULENCE::computeEigenvalues(), and WTURBULENCE::stepTurbulenceFull().
template<class T > T MIN (T a, T b) [inline]
Definition at line 51 of file IMAGE.h.
template<class T > float MIN3V (T vec) [inline]
Definition at line 71 of file IMAGE.h.
References min.
Referenced by WTURBULENCE::computeEigenvalues(), and WTURBULENCE::stepTurbulenceFull().
template<class T > void SWAP_POINTERS (T & a, T & b) [inline]
Definition at line 40 of file IMAGE.h.
References T.
Referenced by WTURBULENCE::advectTextureCoordinates(), FLUID_3D::diffuseHeat(), FLUID_3D::step(), and WTURBULENCE::stepTurbulenceFull().