Blender: BLO_runtime.h File Reference
BLO_runtime.h File Reference
.blend read and write functions
Functions
int BLO_is_a_runtime (const char *file)
struct BlendFileData * BLO_read_runtime (const char *file, struct ReportList *reports)
Detailed Description
Definition in file BLO_runtime.h.
Function Documentation
int BLO_is_a_runtime (const char * file)
Definition at line 69 of file runtime.c.
References BLI_open(), handle_read_msb_int(), lseek, and O_BINARY.
Referenced by load_game_data(), and main().
struct BlendFileData* BLO_read_runtime (const char * file, struct ReportList * reports) [read]
Definition at line 98 of file runtime.c.
References BKE_reportf(), BLI_file_descriptor_size(), BLI_open(), blo_read_blendafterruntime(), handle_read_msb_int(), lseek, NULL, O_BINARY, and RPT_ERROR.
Referenced by load_game_data().