Blender: metadata.c File Reference
metadata.c File Reference
IMage Buffer
#include <stdlib.h>
#include <string.h>
#include "BLI_blenlib.h"
#include "MEM_guardedalloc.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_metadata.h"
Functions
void IMB_metadata_free (struct ImBuf *img)
int IMB_metadata_get_field (struct ImBuf *img, const char *key, char *field, int len)
int IMB_metadata_add_field (struct ImBuf *img, const char *key, const char *value)
int IMB_metadata_del_field (struct ImBuf *img, const char *key)
int IMB_metadata_change_field (struct ImBuf *img, const char *key, const char *field)
Detailed Description
Definition in file metadata.c.
Function Documentation
int IMB_metadata_add_field (struct ImBuf * img, const char * key, const char * value)
set user data in the ImMetaData struct, which has to be allocated with IMB_metadata_create before calling this function.
Parameters:
img - the ImBuf that contains the image data
key - the key of the field
value - the data to be written to the field. zero terminated string
Returns:
- 1 (true) if ImageInfo present, 0 (false) otherwise
Definition at line 87 of file metadata.c.
References BLI_strdup(), ImMetaData::key, MEM_callocN(), ImBuf::metadata, ImMetaData::next, and ImMetaData::value.
Referenced by ibJpegImageFromCinfo(), imb_loadpng(), and IMB_metadata_change_field().
int IMB_metadata_change_field (struct ImBuf * img, const char * key, const char * field)
Definition at line 141 of file metadata.c.
References BLI_strdup(), IMB_metadata_add_field(), ImMetaData::key, MEM_freeN(), ImBuf::metadata, ImMetaData::next, p, and ImMetaData::value.
Referenced by BKE_stamp_info(), and IMB_thumb_create().
int IMB_metadata_del_field (struct ImBuf * img, const char * key)
delete the key/field par in the ImMetaData struct.
Parameters:
img - the ImBuf that contains the image data
key - the key of the field
Returns:
- 1 (true) if delete the key/field, 0 (false) otherwise
Definition at line 114 of file metadata.c.
References ImMetaData::key, MEM_freeN(), ImBuf::metadata, ImMetaData::next, NULL, p, and ImMetaData::value.
void IMB_metadata_free (struct ImBuf * img)
The metadata is a list of key/value pairs (both char*) that can me saved in the header of several image formats. Apart from some common keys like 'Software' and 'Description' (png standard) we'll use keys within the Blender namespace, so should be called 'Blender::StampInfo' or 'Blender::FrameNum' etc...
Definition at line 46 of file metadata.c.
References ImMetaData::key, MEM_freeN(), ImBuf::metadata, ImMetaData::next, next, and ImMetaData::value.
Referenced by IMB_freeImBuf().
int IMB_metadata_get_field (struct ImBuf * img, const char * key, char * value, int len)
read the field from the image info into the field
Parameters:
img - the ImBuf that contains the image data
key - the key of the field
value - the data in the field, first one found with key is returned, memory has to be allocated by user.
len - length of value buffer allocated by user.
Returns:
- 1 (true) if ImageInfo present and value for the key found, 0 (false) otherwise
Definition at line 65 of file metadata.c.
References BLI_strncpy(), ImMetaData::key, ImBuf::metadata, ImMetaData::next, and ImMetaData::value.
Referenced by IMB_thumb_manage().