Blender: btConvexConvexAlgorithm.cpp File Reference
btConvexConvexAlgorithm.cpp File Reference
#include "btConvexConvexAlgorithm.h"
#include "BulletCollision/NarrowPhaseCollision/btDiscreteCollisionDetectorInterface.h"
#include "BulletCollision/BroadphaseCollision/btBroadphaseInterface.h"
#include "BulletCollision/CollisionDispatch/btCollisionObject.h"
#include "BulletCollision/CollisionShapes/btConvexShape.h"
#include "BulletCollision/CollisionShapes/btCapsuleShape.h"
#include "BulletCollision/NarrowPhaseCollision/btGjkPairDetector.h"
#include "BulletCollision/BroadphaseCollision/btBroadphaseProxy.h"
#include "BulletCollision/CollisionDispatch/btCollisionDispatcher.h"
#include "BulletCollision/CollisionShapes/btBoxShape.h"
#include "BulletCollision/CollisionDispatch/btManifoldResult.h"
#include "BulletCollision/NarrowPhaseCollision/btConvexPenetrationDepthSolver.h"
#include "BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.h"
#include "BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.h"
#include "BulletCollision/NarrowPhaseCollision/btGjkConvexCast.h"
#include "BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.h"
#include "BulletCollision/CollisionShapes/btSphereShape.h"
#include "BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.h"
#include "BulletCollision/NarrowPhaseCollision/btGjkEpa2.h"
#include "BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.h"
Classes
struct btPerturbedContactResult
Functions
static SIMD_FORCE_INLINE void segmentsClosestPoints (btVector3 &ptsVector, btVector3 &offsetA, btVector3 &offsetB, btScalar &tA, btScalar &tB, const btVector3 &translation, const btVector3 &dirA, btScalar hlenA, const btVector3 &dirB, btScalar hlenB)
static SIMD_FORCE_INLINE btScalar capsuleCapsuleDistance (btVector3 &normalOnB, btVector3 &pointOnB, btScalar capsuleLengthA, btScalar capsuleRadiusA, btScalar capsuleLengthB, btScalar capsuleRadiusB, int capsuleAxisA, int capsuleAxisB, const btTransform &transformA, const btTransform &transformB, btScalar distanceThreshold)
Variables
btScalar gContactBreakingThreshold
bool disableCcd = false
Function Documentation
static SIMD_FORCE_INLINE btScalar capsuleCapsuleDistance (btVector3 & normalOnB, btVector3 & pointOnB, btScalar capsuleLengthA, btScalar capsuleRadiusA, btScalar capsuleLengthB, btScalar capsuleRadiusB, int capsuleAxisA, int capsuleAxisB, const btTransform & transformA, const btTransform & transformB, btScalar distanceThreshold) [static]
Definition at line 114 of file btConvexConvexAlgorithm.cpp.
References btPlaneSpace1(), btRecipSqrt, distance(), btTransform::getBasis(), btMatrix3x3::getColumn(), btTransform::getOrigin(), segmentsClosestPoints(), and SIMD_EPSILON.
Referenced by btConvexConvexAlgorithm::processCollision().
static SIMD_FORCE_INLINE void segmentsClosestPoints (btVector3 & ptsVector, btVector3 & offsetA, btVector3 & offsetB, btScalar & tA, btScalar & tB, const btVector3 & translation, const btVector3 & dirA, btScalar hlenA, const btVector3 & dirB, btScalar hlenB) [static]
Specialized capsule-capsule collision algorithm has been added for Bullet 2.75 release to increase ragdoll performance If you experience problems with capsule-capsule collision, try to define BT_DISABLE_CAPSULE_CAPSULE_COLLIDER and report it in the Bullet forums with reproduction case
Definition at line 58 of file btConvexConvexAlgorithm.cpp.
References btDot().
Referenced by capsuleCapsuleDistance().
Variable Documentation
bool disableCcd = false
Definition at line 485 of file btConvexConvexAlgorithm.cpp.
Referenced by btConvexConvexAlgorithm::calculateTimeOfImpact().
btScalar gContactBreakingThreshold
Definition at line 21 of file btPersistentManifold.cpp.