Blender: LightManager Class Reference
LightManager Class Reference
#include <light.h>
Public Member Functions
LightManager ()
~LightManager ()
void device_update (Device *device, DeviceScene *dscene, Scene *scene, Progress &progress)
void device_free (Device *device, DeviceScene *dscene)
void tag_update (Scene *scene)
Public Attributes
bool need_update
Protected Member Functions
void device_update_points (Device *device, DeviceScene *dscene, Scene *scene)
void device_update_distribution (Device *device, DeviceScene *dscene, Scene *scene, Progress &progress)
void device_update_background (Device *device, DeviceScene *dscene, Scene *scene, Progress &progress)
Detailed Description
Definition at line 58 of file light.h.
Constructor & Destructor Documentation
LightManager::LightManager ()
Definition at line 125 of file light.cpp.
References need_update.
LightManager::~LightManager ()
Definition at line 130 of file light.cpp.
Member Function Documentation
void LightManager::device_free (Device * device, DeviceScene * dscene)
Definition at line 480 of file light.cpp.
References device_vector< T >::clear(), DeviceScene::light_background_conditional_cdf, DeviceScene::light_background_marginal_cdf, DeviceScene::light_data, DeviceScene::light_distribution, and Device::tex_free().
Referenced by device_update(), and Scene::~Scene().
void LightManager::device_update (Device * device, DeviceScene * dscene, Scene * scene, Progress & progress)
Definition at line 461 of file light.cpp.
References device_free(), device_update_background(), device_update_distribution(), device_update_points(), Progress::get_cancel(), and need_update.
Referenced by Scene::device_update().
void LightManager::device_update_background (Device * device, DeviceScene * dscene, Scene * scene, Progress & progress) [protected]
Definition at line 304 of file light.cpp.
References assert, average(), DeviceScene::data, dump_background_pixels(), Progress::get_cancel(), i, KernelData::integrator, LIGHT_BACKGROUND, DeviceScene::light_background_conditional_cdf, DeviceScene::light_background_marginal_cdf, Scene::lights, M_PI_F, Light::map_resolution, NULL, KernelIntegrator::pdf_background_res, device_vector< T >::resize(), Progress::set_status(), sinf, Device::tex_alloc(), Light::type, KernelIntegrator::use_direct_light, float2::x, and float2::y.
Referenced by device_update().
void LightManager::device_update_distribution (Device * device, DeviceScene * dscene, Scene * scene, Progress & progress) [protected]
Definition at line 134 of file light.cpp.
References __int_as_float(), device_vector< T >::clear(), DeviceScene::data, Progress::get_cancel(), Shader::has_surface_emission, i, KernelData::integrator, DeviceScene::light_distribution, Scene::lights, KernelIntegrator::num_all_lights, KernelIntegrator::num_distribution, Scene::objects, KernelIntegrator::pdf_lights, KernelIntegrator::pdf_triangles, device_vector< T >::resize(), Shader::sample_as_light, Progress::set_status(), Mesh::shader, Scene::shaders, Device::tex_alloc(), Mesh::transform_applied, transform_point(), Mesh::tri_offset, triangle_area(), Mesh::triangles, KernelIntegrator::use_direct_light, Mesh::used_shaders, Mesh::Triangle::v, Mesh::verts, float4::w, float4::x, float4::y, and float4::z.
Referenced by device_update().
void LightManager::device_update_points (Device * device, DeviceScene * dscene, Scene * scene) [protected]
Definition at line 397 of file light.cpp.
References __int_as_float(), DeviceInfo::advanced_shading, Light::axisu, Light::axisv, Light::cast_shadow, co, Light::co, Light::dir, ShaderManager::get_shader_id(), i, Device::info, LIGHT_AREA, LIGHT_BACKGROUND, DeviceScene::light_data, LIGHT_DISTANT, LIGHT_POINT, LIGHT_SIZE, Scene::lights, make_float4(), normalize(), device_vector< T >::resize(), SHADER_AREA_LIGHT, SHADER_CAST_SHADOW, Scene::shader_manager, Light::size, Light::sizeu, Light::sizev, Device::tex_alloc(), Light::type, float3::x, float3::y, and float3::z.
Referenced by device_update().
void LightManager::tag_update (Scene * scene)
Definition at line 493 of file light.cpp.
References need_update.
Member Data Documentation
bool LightManager::need_update
Definition at line 60 of file light.h.
Referenced by SVMShaderManager::device_update(), device_update(), LightManager(), Scene::need_reset(), Shader::tag_update(), Light::tag_update(), Object::tag_update(), tag_update(), Mesh::tag_update(), and ObjectManager::tag_update().
The documentation for this class was generated from the following files:
light.h
light.cpp