Blender: BLI_dynlib.h File Reference
BLI_dynlib.h File Reference
blenlib
Typedefs
typedef struct DynamicLibrary DynamicLibrary
Functions
DynamicLibrary * BLI_dynlib_open (char *name)
void * BLI_dynlib_find_symbol (DynamicLibrary *lib, const char *symname)
char * BLI_dynlib_get_error_as_string (DynamicLibrary *lib)
void BLI_dynlib_close (DynamicLibrary *lib)
Detailed Description
Definition in file BLI_dynlib.h.
Typedef Documentation
typedef struct DynamicLibrary DynamicLibrary
Definition at line 35 of file BLI_dynlib.h.
Function Documentation
void BLI_dynlib_close (DynamicLibrary * lib)
Definition at line 129 of file dynlib.c.
References DynamicLibrary::handle, and MEM_freeN().
void* BLI_dynlib_find_symbol (DynamicLibrary * lib, const char * symname)
Definition at line 118 of file dynlib.c.
References DynamicLibrary::handle.
Referenced by do_plugin_effect(), free_plugin_seq(), open_plugin_seq(), and open_plugin_tex().
char* BLI_dynlib_get_error_as_string (DynamicLibrary * lib)
Definition at line 123 of file dynlib.c.
Referenced by open_plugin_seq(), open_plugin_tex(), and test_dlerr().
DynamicLibrary* BLI_dynlib_open (char * name)
Definition at line 104 of file dynlib.c.
References DynamicLibrary::handle, MEM_callocN(), and NULL.
Referenced by open_plugin_seq(), and open_plugin_tex().