Blender: BKE_packedFile.h File Reference
BKE_packedFile.h File Reference
blenkernel
Defines
#define RET_OK 0
#define RET_ERROR 1
Functions
struct PackedFile * newPackedFile (struct ReportList *reports, const char *filename, const char *relabase)
struct PackedFile * newPackedFileMemory (void *mem, int memlen)
void packAll (struct Main *bmain, struct ReportList *reports)
char * unpackFile (struct ReportList *reports, const char *abs_name, const char *local_name, struct PackedFile *pf, int how)
int unpackVFont (struct ReportList *reports, struct VFont *vfont, int how)
int unpackSound (struct Main *bmain, struct ReportList *reports, struct bSound *sound, int how)
int unpackImage (struct ReportList *reports, struct Image *ima, int how)
void unpackAll (struct Main *bmain, struct ReportList *reports, int how)
int writePackedFile (struct ReportList *reports, const char *filename, struct PackedFile *pf, int guimode)
void freePackedFile (struct PackedFile *pf)
int countPackedFiles (struct Main *bmain)
int checkPackedFile (const char *filename, struct PackedFile *pf)
int seekPackedFile (struct PackedFile *pf, int offset, int whence)
void rewindPackedFile (struct PackedFile *pf)
int readPackedFile (struct PackedFile *pf, void *data, int size)
Detailed Description
Since:
March 2001
Author:
nzc
Definition in file BKE_packedFile.h.
Define Documentation
#define RET_ERROR 1
Definition at line 36 of file BKE_packedFile.h.
Referenced by unpackImage(), unpackSound(), unpackVFont(), and writePackedFile().
#define RET_OK 0
Definition at line 35 of file BKE_packedFile.h.
Referenced by unpackFile(), unpackImage(), unpackSound(), unpackVFont(), and writePackedFile().
Function Documentation
int checkPackedFile (const char * filename, struct PackedFile * pf)
Definition at line 340 of file packedFile.c.
References BLI_open(), BLI_path_abs(), BLI_strncpy(), PackedFile::data, FILE_MAX, G, i, len(), O_BINARY, PF_DIFFERS, PF_EQUAL, PF_NOFILE, and PackedFile::size.
Referenced by unpack_menu().
int countPackedFiles (struct Main * bmain)
Definition at line 128 of file packedFile.c.
References ListBase::first, bSound::id, VFont::id, Image::id, Main::image, ID::next, bSound::packedfile, VFont::packedfile, Image::packedfile, Main::sound, and Main::vfont.
Referenced by unpack_all_invoke().
void freePackedFile (struct PackedFile * pf)
Definition at line 151 of file packedFile.c.
References PackedFile::data, and MEM_freeN().
Referenced by BKE_image_memorypack(), BKE_image_signal(), free_image(), free_ttfont(), free_vfont(), load_vfont(), sound_free(), unpackImage(), unpackSound(), unpackVFont(), and vfont_get_data().
struct PackedFile* newPackedFile (struct ReportList * reports, const char * filename, const char * relabase) [read]
Definition at line 170 of file packedFile.c.
References BKE_reportf(), BLI_file_descriptor_size(), BLI_open(), BLI_path_abs(), BLI_strncpy(), data, FILE_MAX, MEM_mallocN(), newPackedFileMemory(), NULL, O_BINARY, pf, and RPT_ERROR.
Referenced by BKE_image_signal(), image_load_image_file(), image_pack_exec(), load_vfont(), packAll(), sound_pack_exec(), and vfont_get_data().
struct PackedFile* newPackedFileMemory (void * mem, int memlen) [read]
Definition at line 161 of file packedFile.c.
References PackedFile::data, MEM_callocN(), pf, and PackedFile::size.
Referenced by get_builtin_packedfile(), and newPackedFile().
void packAll (struct Main * bmain, struct ReportList * reports)
Definition at line 219 of file packedFile.c.
References BKE_reportf(), ELEM, ListBase::first, FO_BUILTIN_NAME, bSound::id, VFont::id, Image::id, ID_BLEND_PATH, IMA_SRC_FILE, IMA_SRC_MOVIE, IMA_SRC_SEQUENCE, Main::image, ID::lib, bSound::name, Main::name, VFont::name, ID::name, Image::name, newPackedFile(), ID::next, NULL, bSound::packedfile, VFont::packedfile, Image::packedfile, RPT_WARNING, Main::sound, Image::source, and Main::vfont.
Referenced by pack_all_exec(), and WM_write_file().
int readPackedFile (struct PackedFile * pf, void * data, int size)
Definition at line 105 of file packedFile.c.
References PackedFile::data, NULL, PackedFile::seek, size(), and PackedFile::size.
void rewindPackedFile (struct PackedFile * pf)
Definition at line 100 of file packedFile.c.
References seekPackedFile().
int seekPackedFile (struct PackedFile * pf, int offset, int whence)
Definition at line 69 of file packedFile.c.
References PackedFile::seek, and PackedFile::size.
Referenced by rewindPackedFile().
void unpackAll (struct Main * bmain, struct ReportList * reports, int how)
Definition at line 530 of file packedFile.c.
References ListBase::first, bSound::id, VFont::id, Image::id, Main::image, ID::next, bSound::packedfile, VFont::packedfile, Image::packedfile, Main::sound, unpackImage(), unpackSound(), unpackVFont(), and Main::vfont.
Referenced by unpack_all_exec().
char* unpackFile (struct ReportList * reports, const char * abs_name, const char * local_name, struct PackedFile * pf, int how)
Definition at line 398 of file packedFile.c.
References BLI_exists(), BLI_strdup(), NULL, PF_KEEP, PF_REMOVE, PF_USE_LOCAL, PF_USE_ORIGINAL, PF_WRITE_LOCAL, PF_WRITE_ORIGINAL, RET_OK, and writePackedFile().
Referenced by unpackImage(), unpackSound(), and unpackVFont().
int unpackImage (struct ReportList * reports, struct Image * ima, int how)
Definition at line 505 of file packedFile.c.
References BKE_image_signal(), BLI_snprintf(), BLI_splitdirstring(), BLI_strncpy(), FILE_MAX, FILE_MAXDIR, freePackedFile(), IMA_SIGNAL_RELOAD, MEM_freeN(), Image::name, NULL, Image::packedfile, RET_ERROR, RET_OK, and unpackFile().
Referenced by image_unpack_exec(), and unpackAll().
int unpackSound (struct Main * bmain, struct ReportList * reports, struct bSound * sound, int how)
Definition at line 477 of file packedFile.c.
References BLI_snprintf(), BLI_splitdirstring(), BLI_strncpy(), FILE_MAX, FILE_MAXDIR, freePackedFile(), MEM_freeN(), bSound::name, NULL, bSound::packedfile, RET_ERROR, RET_OK, sound_load(), and unpackFile().
Referenced by sound_unpack_exec(), and unpackAll().
int unpackVFont (struct ReportList * reports, struct VFont * vfont, int how)
Definition at line 452 of file packedFile.c.
References BLI_snprintf(), BLI_splitdirstring(), BLI_strncpy(), FILE_MAX, FILE_MAXFILE, freePackedFile(), MEM_freeN(), VFont::name, NULL, VFont::packedfile, RET_ERROR, RET_OK, and unpackFile().
Referenced by unpackAll().
int writePackedFile (struct ReportList * reports, const char * filename, struct PackedFile * pf, int guimode)
Definition at line 272 of file packedFile.c.
References BKE_reportf(), BLI_copy(), BLI_delete(), BLI_exists(), BLI_make_existing_file(), BLI_open(), BLI_path_abs(), BLI_rename(), BLI_snprintf(), BLI_strncpy(), PackedFile::data, FALSE, FILE_MAX, G, O_BINARY, RET_ERROR, RET_OK, RPT_ERROR, PackedFile::size, and TRUE.
Referenced by unpackFile().