Blender: RAS_MeshSlot Class Reference
RAS_MeshSlot Class Reference
#include <RAS_MaterialBucket.h>
Classes
struct iterator
Public Member Functions
RAS_MeshSlot ()
RAS_MeshSlot (const RAS_MeshSlot &slot)
virtual ~RAS_MeshSlot ()
void init (RAS_MaterialBucket *bucket, int numverts)
void begin (iterator &it)
void next (iterator &it)
bool end (iterator &it)
void SetDisplayArray (int numverts)
RAS_DisplayArray * CurrentDisplayArray ()
void SetDeformer (RAS_Deformer *deformer)
void AddPolygon (int numverts)
int AddVertex (const RAS_TexVert &tv)
void AddPolygonVertex (int offset)
bool Split (bool force=false)
bool Join (RAS_MeshSlot *target, MT_Scalar distance)
bool Equals (RAS_MeshSlot *target)
bool IsCulled ()
void SetCulled (bool culled)
Public Attributes
RAS_MaterialBucket * m_bucket
RAS_MeshObject * m_mesh
void * m_clientObj
RAS_Deformer * m_pDeformer
DerivedMesh * m_pDerivedMesh
double * m_OpenGLMatrix
bool m_bVisible
bool m_bCulled
bool m_bObjectColor
MT_Vector4 m_RGBAcolor
KX_ListSlot * m_DisplayList
bool m_bDisplayList
RAS_MeshSlot * m_joinSlot
MT_Matrix4x4 m_joinInvTransform
list< RAS_MeshSlot * > m_joinedSlots
Friends
class RAS_ListRasterizer
Detailed Description
Definition at line 101 of file RAS_MaterialBucket.h.
Constructor & Destructor Documentation
RAS_MeshSlot::RAS_MeshSlot ()
Definition at line 52 of file RAS_MaterialBucket.cpp.
References m_bCulled, m_bDisplayList, m_bObjectColor, m_bucket, m_bVisible, m_clientObj, m_DisplayList, m_joinSlot, m_mesh, m_OpenGLMatrix, m_pDeformer, m_pDerivedMesh, m_RGBAcolor, and NULL.
RAS_MeshSlot::RAS_MeshSlot (const RAS_MeshSlot & slot)
Definition at line 92 of file RAS_MaterialBucket.cpp.
References m_bCulled, m_bDisplayList, m_bObjectColor, m_bucket, m_bVisible, m_clientObj, m_DisplayList, m_joinedSlots, m_joinSlot, m_mesh, m_OpenGLMatrix, m_pDeformer, m_pDerivedMesh, m_RGBAcolor, and NULL.
RAS_MeshSlot::~RAS_MeshSlot () [virtual]
Definition at line 69 of file RAS_MaterialBucket.cpp.
References m_DisplayList, m_joinedSlots, NULL, KX_ListSlot::Release(), and Split().
Member Function Documentation
void RAS_MeshSlot::AddPolygon (int numverts)
Definition at line 260 of file RAS_MaterialBucket.cpp.
References SetDisplayArray().
Referenced by RAS_MeshObject::AddPolygon().
void RAS_MeshSlot::AddPolygonVertex (int offset)
Definition at line 280 of file RAS_MaterialBucket.cpp.
References RAS_DisplayArray::m_index.
int RAS_MeshSlot::AddVertex (const RAS_TexVert & tv)
Definition at line 265 of file RAS_MaterialBucket.cpp.
References RAS_DisplayArray::m_vertex.
void RAS_MeshSlot::begin (RAS_MeshSlot::iterator & it)
Definition at line 145 of file RAS_MaterialBucket.cpp.
References RAS_MeshSlot::iterator::array, RAS_MeshSlot::iterator::arraynum, RAS_MeshSlot::iterator::endvertex, RAS_MeshSlot::iterator::index, RAS_DisplayArray::m_index, RAS_DisplayArray::m_vertex, NULL, RAS_MeshSlot::iterator::startvertex, RAS_MeshSlot::iterator::totindex, and RAS_MeshSlot::iterator::vertex.
Referenced by BL_SkinDeformer::Apply(), BL_MeshDeformer::Apply(), RAS_MeshObject::GetVertex(), RAS_VAOpenGLRasterizer::IndexPrimitives(), RAS_OpenGLRasterizer::IndexPrimitives_3DText(), RAS_OpenGLRasterizer::IndexPrimitivesInternal(), RAS_VAOpenGLRasterizer::IndexPrimitivesMulti(), Join(), RAS_MeshObject::NumVertices(), BL_MeshDeformer::RecalcNormals(), RAS_MeshObject::SetVertexColor(), RAS_MeshObject::SortPolygons(), and Split().
RAS_DisplayArray * RAS_MeshSlot::CurrentDisplayArray ()
Definition at line 210 of file RAS_MaterialBucket.cpp.
Referenced by RAS_MeshObject::AddPolygon().
bool RAS_MeshSlot::end (RAS_MeshSlot::iterator & it)
Definition at line 205 of file RAS_MaterialBucket.cpp.
References RAS_MeshSlot::iterator::array, and NULL.
Referenced by BL_SkinDeformer::Apply(), BL_MeshDeformer::Apply(), RAS_MeshObject::GetVertex(), RAS_VAOpenGLRasterizer::IndexPrimitives(), RAS_OpenGLRasterizer::IndexPrimitives_3DText(), RAS_OpenGLRasterizer::IndexPrimitivesInternal(), RAS_VAOpenGLRasterizer::IndexPrimitivesMulti(), Join(), RAS_MeshObject::NumVertices(), BL_MeshDeformer::RecalcNormals(), RAS_MeshObject::SetVertexColor(), RAS_MeshObject::SortPolygons(), and Split().
bool RAS_MeshSlot::Equals (RAS_MeshSlot * target)
Definition at line 348 of file RAS_MaterialBucket.cpp.
References m_bObjectColor, m_bVisible, m_OpenGLMatrix, m_pDeformer, and m_RGBAcolor.
Referenced by Join(), and Split().
void RAS_MeshSlot::init (RAS_MaterialBucket * bucket, int numverts)
Definition at line 131 of file RAS_MaterialBucket.cpp.
References m_bucket, and SetDisplayArray().
Referenced by RAS_MaterialBucket::AddMesh().
bool RAS_MeshSlot::IsCulled () [inline]
Definition at line 175 of file RAS_MaterialBucket.h.
bool RAS_MeshSlot::Join (RAS_MeshSlot * target, MT_Scalar distance)
Definition at line 364 of file RAS_MaterialBucket.cpp.
References begin(), co, end(), RAS_MeshSlot::iterator::endvertex, Equals(), i, MT_Matrix4x4::invert(), length(), m_DisplayList, m_joinedSlots, m_joinInvTransform, m_joinSlot, m_OpenGLMatrix, next(), NULL, KX_ListSlot::Release(), RAS_MeshSlot::iterator::startvertex, transform(), RAS_TexVert::Transform(), MT_Matrix4x4::transposed(), and RAS_MeshSlot::iterator::vertex.
void RAS_MeshSlot::next (RAS_MeshSlot::iterator & it)
Definition at line 175 of file RAS_MaterialBucket.cpp.
References RAS_MeshSlot::iterator::array, RAS_MeshSlot::iterator::arraynum, RAS_MeshSlot::iterator::endvertex, RAS_MeshSlot::iterator::index, RAS_DisplayArray::m_index, RAS_DisplayArray::m_vertex, NULL, RAS_MeshSlot::iterator::startvertex, RAS_MeshSlot::iterator::totindex, and RAS_MeshSlot::iterator::vertex.
Referenced by BL_SkinDeformer::Apply(), BL_MeshDeformer::Apply(), RAS_MeshObject::GetVertex(), RAS_VAOpenGLRasterizer::IndexPrimitives(), RAS_OpenGLRasterizer::IndexPrimitives_3DText(), RAS_OpenGLRasterizer::IndexPrimitivesInternal(), RAS_VAOpenGLRasterizer::IndexPrimitivesMulti(), Join(), RAS_MeshObject::NumVertices(), BL_MeshDeformer::RecalcNormals(), RAS_MeshObject::SetVertexColor(), RAS_MeshObject::SortPolygons(), and Split().
void RAS_MeshSlot::SetCulled (bool culled) [inline]
Definition at line 177 of file RAS_MaterialBucket.h.
void RAS_MeshSlot::SetDeformer (RAS_Deformer * deformer)
Definition at line 291 of file RAS_MaterialBucket.cpp.
References RAS_MeshObject::GetMeshMaterial(), RAS_MaterialBucket::GetPolyMaterial(), RAS_MeshMaterial::m_baseslot, m_bucket, m_mesh, m_pDeformer, RAS_DisplayArray::m_users, RAS_Deformer::ShareVertexArray(), and RAS_Deformer::UseVertexArray().
Referenced by RAS_MeshObject::AddMeshUser().
void RAS_MeshSlot::SetDisplayArray (int numverts)
Definition at line 215 of file RAS_MaterialBucket.cpp.
References RAS_DisplayArray::BUCKET_MAX_INDEX, RAS_DisplayArray::BUCKET_MAX_VERTEX, RAS_DisplayArray::LINE, RAS_DisplayArray::m_index, RAS_DisplayArray::m_type, RAS_DisplayArray::m_users, RAS_DisplayArray::m_vertex, NULL, RAS_DisplayArray::QUAD, and RAS_DisplayArray::TRIANGLE.
Referenced by AddPolygon(), and init().
bool RAS_MeshSlot::Split (bool force = false)
Definition at line 427 of file RAS_MaterialBucket.cpp.
References begin(), end(), RAS_MeshSlot::iterator::endvertex, Equals(), i, MT_Matrix4x4::inverse(), jit, m_DisplayList, m_joinedSlots, m_joinInvTransform, m_joinSlot, next(), NULL, KX_ListSlot::Release(), RAS_MeshSlot::iterator::startvertex, RAS_TexVert::Transform(), MT_Matrix4x4::transposed(), and RAS_MeshSlot::iterator::vertex.
Referenced by KX_GameObject::UpdateBuckets(), and ~RAS_MeshSlot().
Friends And Related Function Documentation
friend class RAS_ListRasterizer [friend]
Definition at line 103 of file RAS_MaterialBucket.h.
Member Data Documentation
bool RAS_MeshSlot::m_bCulled
Definition at line 127 of file RAS_MaterialBucket.h.
Referenced by RAS_MeshSlot(), and KX_GameObject::UpdateBuckets().
bool RAS_MeshSlot::m_bDisplayList
Definition at line 133 of file RAS_MaterialBucket.h.
Referenced by RAS_ListRasterizer::IndexPrimitives(), RAS_ListRasterizer::IndexPrimitivesMulti(), RAS_MeshSlot(), and RAS_MaterialBucket::RenderMeshSlot().
bool RAS_MeshSlot::m_bObjectColor
Definition at line 129 of file RAS_MaterialBucket.h.
Referenced by CheckTexDM(), Equals(), RAS_VAOpenGLRasterizer::IndexPrimitives(), RAS_OpenGLRasterizer::IndexPrimitives_3DText(), RAS_OpenGLRasterizer::IndexPrimitivesInternal(), RAS_VAOpenGLRasterizer::IndexPrimitivesMulti(), RAS_MeshSlot(), RAS_MaterialBucket::RenderMeshSlot(), LOD_QuadricEditor::Update(), and KX_GameObject::UpdateBuckets().
RAS_MaterialBucket* RAS_MeshSlot::m_bucket
Definition at line 119 of file RAS_MaterialBucket.h.
Referenced by RAS_MeshObject::AddMeshUser(), RAS_OpenGLRasterizer::IndexPrimitivesInternal(), init(), RAS_MeshSlot(), RAS_MeshObject::RemoveFromBuckets(), SetDeformer(), and KX_GameObject::UpdateBuckets().
bool RAS_MeshSlot::m_bVisible
Definition at line 126 of file RAS_MaterialBucket.h.
Referenced by Equals(), RAS_MeshSlot(), and KX_GameObject::UpdateBuckets().
void* RAS_MeshSlot::m_clientObj
Definition at line 121 of file RAS_MaterialBucket.h.
Referenced by RAS_MeshObject::AddMeshUser(), and RAS_MeshSlot().
KX_ListSlot* RAS_MeshSlot::m_DisplayList
Definition at line 132 of file RAS_MaterialBucket.h.
Referenced by RAS_ListRasterizer::IndexPrimitives(), RAS_ListRasterizer::IndexPrimitivesMulti(), Join(), RAS_MeshSlot(), RAS_MaterialBucket::RenderMeshSlot(), Split(), and ~RAS_MeshSlot().
list<RAS_MeshSlot*> RAS_MeshSlot::m_joinedSlots
Definition at line 137 of file RAS_MaterialBucket.h.
Referenced by Join(), RAS_MeshSlot(), Split(), and ~RAS_MeshSlot().
MT_Matrix4x4 RAS_MeshSlot::m_joinInvTransform
Definition at line 136 of file RAS_MaterialBucket.h.
Referenced by Join(), and Split().
RAS_MeshSlot* RAS_MeshSlot::m_joinSlot
Definition at line 135 of file RAS_MaterialBucket.h.
Referenced by Join(), RAS_MeshSlot(), and Split().
RAS_MeshObject* RAS_MeshSlot::m_mesh
Definition at line 120 of file RAS_MaterialBucket.h.
Referenced by RAS_MeshObject::AddPolygon(), RAS_OpenGLRasterizer::IndexPrimitivesInternal(), RAS_MeshSlot(), RAS_MaterialBucket::RenderMeshSlot(), and SetDeformer().
double* RAS_MeshSlot::m_OpenGLMatrix
Definition at line 124 of file RAS_MaterialBucket.h.
Referenced by Equals(), Join(), RAS_MeshSlot(), RAS_MaterialBucket::RenderMeshSlot(), and LOD_QuadricEditor::Update().
RAS_Deformer* RAS_MeshSlot::m_pDeformer
Definition at line 122 of file RAS_MaterialBucket.h.
Referenced by Equals(), RAS_MeshSlot(), RAS_MaterialBucket::RenderMeshSlot(), and SetDeformer().
DerivedMesh* RAS_MeshSlot::m_pDerivedMesh
Definition at line 123 of file RAS_MaterialBucket.h.
Referenced by RAS_VAOpenGLRasterizer::IndexPrimitives(), RAS_ListRasterizer::IndexPrimitives(), RAS_OpenGLRasterizer::IndexPrimitivesInternal(), RAS_ListRasterizer::IndexPrimitivesMulti(), RAS_VAOpenGLRasterizer::IndexPrimitivesMulti(), RAS_MeshSlot(), and LOD_QuadricEditor::Update().
MT_Vector4 RAS_MeshSlot::m_RGBAcolor
Definition at line 130 of file RAS_MaterialBucket.h.
Referenced by CheckTexDM(), Equals(), RAS_VAOpenGLRasterizer::IndexPrimitives(), RAS_OpenGLRasterizer::IndexPrimitives_3DText(), RAS_OpenGLRasterizer::IndexPrimitivesInternal(), RAS_VAOpenGLRasterizer::IndexPrimitivesMulti(), RAS_MeshSlot(), LOD_QuadricEditor::Update(), and KX_GameObject::UpdateBuckets().
The documentation for this class was generated from the following files:
RAS_MaterialBucket.h
RAS_MaterialBucket.cpp