Blender: svm.h File Reference
svm.h File Reference
#include "svm_types.h"
#include "svm_noise.h"
#include "svm_texture.h"
#include "svm_attribute.h"
#include "svm_gradient.h"
#include "svm_closure.h"
#include "svm_noisetex.h"
#include "svm_convert.h"
#include "svm_displace.h"
#include "svm_fresnel.h"
#include "svm_camera.h"
#include "svm_geometry.h"
#include "svm_hsv.h"
#include "svm_image.h"
#include "svm_gamma.h"
#include "svm_brightness.h"
#include "svm_invert.h"
#include "svm_light_path.h"
#include "svm_magic.h"
#include "svm_mapping.h"
#include "svm_normal.h"
#include "svm_wave.h"
#include "svm_math.h"
#include "svm_mix.h"
#include "svm_ramp.h"
#include "svm_sepcomb_rgb.h"
#include "svm_musgrave.h"
#include "svm_sky.h"
#include "svm_tex_coord.h"
#include "svm_value.h"
#include "svm_voronoi.h"
#include "svm_checker.h"
Functions
CCL_NAMESPACE_BEGIN
__device_inline float3 stack_load_float3 (float *stack, uint a)
__device_inline void stack_store_float3 (float *stack, uint a, float3 f)
__device_inline float stack_load_float (float *stack, uint a)
__device_inline float stack_load_float_default (float *stack, uint a, uint value)
__device_inline void stack_store_float (float *stack, uint a, float f)
__device_inline bool stack_valid (uint a)
__device_inline uint4 read_node (KernelGlobals *kg, int *offset)
__device_inline float4 read_node_float (KernelGlobals *kg, int *offset)
__device_inline float4 fetch_node_float (KernelGlobals *kg, int offset)
__device_inline void decode_node_uchar4 (uint i, uint *x, uint *y, uint *z, uint *w)
CCL_NAMESPACE_END
CCL_NAMESPACE_BEGIN
__device_noinline void svm_eval_nodes (KernelGlobals *kg, ShaderData *sd, ShaderType type, float randb, int path_flag)
Function Documentation
__device_inline void decode_node_uchar4 (uint i, uint * x, uint * y, uint * z, uint * w)
Definition at line 113 of file kernel/svm/svm.h.
Referenced by svm_node_brightness(), svm_node_closure_bsdf(), svm_node_closure_volume(), svm_node_layer_weight(), svm_node_mix_closure(), svm_node_tex_checker(), svm_node_tex_environment(), svm_node_tex_gradient(), svm_node_tex_image(), svm_node_tex_magic(), svm_node_tex_musgrave(), svm_node_tex_noise(), svm_node_tex_voronoi(), and svm_node_tex_wave().
__device_inline float4 fetch_node_float (KernelGlobals * kg, int offset)
Definition at line 107 of file kernel/svm/svm.h.
References __int_as_float(), kernel_tex_fetch, make_float4(), uint4::w, uint4::x, uint4::y, and uint4::z.
Referenced by rgb_ramp_lookup().
__device_inline uint4 read_node (KernelGlobals * kg, int * offset)
Definition at line 92 of file kernel/svm/svm.h.
References kernel_tex_fetch.
Referenced by svm_eval_nodes(), svm_node_hsv(), svm_node_math(), svm_node_mix(), svm_node_normal(), svm_node_tex_magic(), svm_node_tex_musgrave(), svm_node_tex_noise(), svm_node_tex_wave(), svm_node_value_v(), and svm_node_vector_math().
__device_inline float4 read_node_float (KernelGlobals * kg, int * offset)
Definition at line 99 of file kernel/svm/svm.h.
References __int_as_float(), kernel_tex_fetch, make_float4(), uint4::w, uint4::x, uint4::y, and uint4::z.
Referenced by svm_node_mapping().
__device_inline float stack_load_float (float * stack, uint a)
Definition at line 66 of file kernel/svm/svm.h.
References kernel_assert, and SVM_STACK_SIZE.
Referenced by stack_load_float_default(), svm_node_brightness(), svm_node_closure_background(), svm_node_closure_bsdf(), svm_node_closure_emission(), svm_node_closure_holdout(), svm_node_closure_volume(), svm_node_combine_rgb(), svm_node_convert(), svm_node_emission_weight(), svm_node_fresnel(), svm_node_gamma(), svm_node_hsv(), svm_node_invert(), svm_node_layer_weight(), svm_node_math(), svm_node_mix(), svm_node_mix_closure(), svm_node_rgb_curves(), svm_node_rgb_ramp(), svm_node_set_bump(), and svm_node_set_displacement().
CCL_NAMESPACE_BEGIN __device_inline float3 stack_load_float3 (float * stack, uint a)
Definition at line 50 of file kernel/svm/svm.h.
References kernel_assert, make_float3(), and SVM_STACK_SIZE.
Referenced by svm_node_brightness(), svm_node_closure_weight(), svm_node_convert(), svm_node_emission_weight(), svm_node_gamma(), svm_node_hsv(), svm_node_invert(), svm_node_mapping(), svm_node_mix(), svm_node_normal(), svm_node_rgb_curves(), svm_node_separate_rgb(), svm_node_tex_checker(), svm_node_tex_environment(), svm_node_tex_gradient(), svm_node_tex_image(), svm_node_tex_magic(), svm_node_tex_musgrave(), svm_node_tex_noise(), svm_node_tex_sky(), svm_node_tex_voronoi(), svm_node_tex_wave(), and svm_node_vector_math().
__device_inline float stack_load_float_default (float * stack, uint a, uint value)
Definition at line 73 of file kernel/svm/svm.h.
References __int_as_float(), stack_load_float(), and SVM_STACK_INVALID.
Referenced by svm_node_tex_checker(), svm_node_tex_magic(), svm_node_tex_musgrave(), svm_node_tex_noise(), svm_node_tex_voronoi(), and svm_node_tex_wave().
__device_inline void stack_store_float (float * stack, uint a, float f)
Definition at line 78 of file kernel/svm/svm.h.
References kernel_assert, and SVM_STACK_SIZE.
Referenced by svm_node_attr(), svm_node_attr_bump_dx(), svm_node_attr_bump_dy(), svm_node_camera(), svm_node_combine_rgb(), svm_node_convert(), svm_node_fresnel(), svm_node_layer_weight(), svm_node_light_path(), svm_node_math(), svm_node_mix_closure(), svm_node_normal(), svm_node_rgb_ramp(), svm_node_separate_rgb(), svm_node_tex_checker(), svm_node_tex_environment(), svm_node_tex_gradient(), svm_node_tex_image(), svm_node_tex_magic(), svm_node_tex_musgrave(), svm_node_tex_noise(), svm_node_tex_voronoi(), svm_node_tex_wave(), svm_node_value_f(), and svm_node_vector_math().
__device_inline void stack_store_float3 (float * stack, uint a, float3 f)
Definition at line 57 of file kernel/svm/svm.h.
References kernel_assert, SVM_STACK_SIZE, float3::x, float3::y, and float3::z.
Referenced by svm_node_attr(), svm_node_attr_bump_dx(), svm_node_attr_bump_dy(), svm_node_brightness(), svm_node_camera(), svm_node_convert(), svm_node_gamma(), svm_node_geometry(), svm_node_geometry_bump_dx(), svm_node_geometry_bump_dy(), svm_node_hsv(), svm_node_invert(), svm_node_mapping(), svm_node_mix(), svm_node_normal(), svm_node_rgb_curves(), svm_node_rgb_ramp(), svm_node_tex_checker(), svm_node_tex_coord(), svm_node_tex_coord_bump_dx(), svm_node_tex_coord_bump_dy(), svm_node_tex_environment(), svm_node_tex_gradient(), svm_node_tex_image(), svm_node_tex_magic(), svm_node_tex_musgrave(), svm_node_tex_noise(), svm_node_tex_sky(), svm_node_tex_voronoi(), svm_node_tex_wave(), svm_node_value_v(), and svm_node_vector_math().
__device_inline bool stack_valid (uint a)
Definition at line 85 of file kernel/svm/svm.h.
References SVM_STACK_INVALID, and uint.
Referenced by svm_node_brightness(), svm_node_camera(), svm_node_closure_background(), svm_node_closure_bsdf(), svm_node_closure_emission(), svm_node_closure_holdout(), svm_node_closure_volume(), svm_node_combine_rgb(), svm_node_fresnel(), svm_node_gamma(), svm_node_hsv(), svm_node_invert(), svm_node_layer_weight(), svm_node_mix_closure(), svm_node_normal(), svm_node_rgb_ramp(), svm_node_separate_rgb(), svm_node_tex_checker(), svm_node_tex_environment(), svm_node_tex_gradient(), svm_node_tex_image(), svm_node_tex_magic(), svm_node_tex_musgrave(), svm_node_tex_noise(), svm_node_tex_voronoi(), svm_node_tex_wave(), and svm_node_vector_math().
CCL_NAMESPACE_END CCL_NAMESPACE_BEGIN __device_noinline void svm_eval_nodes (KernelGlobals * kg, ShaderData * sd, ShaderType type, float randb, int path_flag)
Definition at line 162 of file kernel/svm/svm.h.
References ShaderData::closure, NBUILTIN_CLOSURES, NODE_ADD_CLOSURE, NODE_ATTR, NODE_ATTR_BUMP_DX, NODE_ATTR_BUMP_DY, NODE_BRIGHTCONTRAST, NODE_CAMERA, NODE_CLOSURE_BACKGROUND, NODE_CLOSURE_BSDF, NODE_CLOSURE_EMISSION, NODE_CLOSURE_HOLDOUT, NODE_CLOSURE_SET_WEIGHT, NODE_CLOSURE_VOLUME, NODE_CLOSURE_WEIGHT, NODE_COMBINE_RGB, NODE_CONVERT, NODE_EMISSION_SET_WEIGHT_TOTAL, NODE_EMISSION_WEIGHT, NODE_END, NODE_FRESNEL, NODE_GAMMA, NODE_GEOMETRY, NODE_GEOMETRY_BUMP_DX, NODE_GEOMETRY_BUMP_DY, NODE_HSV, NODE_INVERT, NODE_JUMP, NODE_LAYER_WEIGHT, NODE_LIGHT_PATH, NODE_MAPPING, NODE_MATH, NODE_MIX, NODE_MIX_CLOSURE, NODE_NORMAL, NODE_RGB_CURVES, NODE_RGB_RAMP, NODE_SEPARATE_RGB, NODE_SET_BUMP, NODE_SET_DISPLACEMENT, NODE_SHADER_JUMP, NODE_TEX_CHECKER, NODE_TEX_COORD, NODE_TEX_COORD_BUMP_DX, NODE_TEX_COORD_BUMP_DY, NODE_TEX_ENVIRONMENT, NODE_TEX_GRADIENT, NODE_TEX_IMAGE, NODE_TEX_MAGIC, NODE_TEX_MUSGRAVE, NODE_TEX_NOISE, NODE_TEX_SKY, NODE_TEX_VORONOI, NODE_TEX_WAVE, NODE_VALUE_F, NODE_VALUE_V, NODE_VECTOR_MATH, ShaderData::num_closure, ShaderData::randb_closure, read_node(), ShaderData::shader, SHADER_MASK, SHADER_TYPE_DISPLACEMENT, SHADER_TYPE_SURFACE, SHADER_TYPE_VOLUME, stack, svm_node_add_closure(), svm_node_attr(), svm_node_attr_bump_dx(), svm_node_attr_bump_dy(), svm_node_brightness(), svm_node_camera(), svm_node_closure_background(), svm_node_closure_bsdf(), svm_node_closure_emission(), svm_node_closure_holdout(), svm_node_closure_set_weight(), svm_node_closure_volume(), svm_node_closure_weight(), svm_node_combine_rgb(), svm_node_convert(), svm_node_emission_set_weight_total(), svm_node_emission_weight(), svm_node_fresnel(), svm_node_gamma(), svm_node_geometry(), svm_node_geometry_bump_dx(), svm_node_geometry_bump_dy(), svm_node_hsv(), svm_node_invert(), svm_node_layer_weight(), svm_node_light_path(), svm_node_mapping(), svm_node_math(), svm_node_mix(), svm_node_mix_closure(), svm_node_normal(), svm_node_rgb_curves(), svm_node_rgb_ramp(), svm_node_separate_rgb(), svm_node_set_bump(), svm_node_set_displacement(), svm_node_tex_checker(), svm_node_tex_coord(), svm_node_tex_coord_bump_dx(), svm_node_tex_coord_bump_dy(), svm_node_tex_environment(), svm_node_tex_gradient(), svm_node_tex_image(), svm_node_tex_magic(), svm_node_tex_musgrave(), svm_node_tex_noise(), svm_node_tex_sky(), svm_node_tex_voronoi(), svm_node_tex_wave(), svm_node_value_f(), svm_node_value_v(), svm_node_vector_math(), SVM_STACK_SIZE, ShaderClosure::type, uint4::w, ShaderClosure::weight, uint4::x, uint4::y, and uint4::z.
Referenced by shader_eval_background(), shader_eval_displacement(), shader_eval_surface(), and shader_eval_volume().