Blender: IK_QJacobianSolver Class Reference
IK_QJacobianSolver Class Reference
#include <IK_QJacobianSolver.h>
Public Member Functions
IK_QJacobianSolver ()
~IK_QJacobianSolver ()
void SetPoleVectorConstraint (IK_QSegment *tip, MT_Vector3 &goal, MT_Vector3 &polegoal, float poleangle, bool getangle)
float GetPoleAngle ()
bool Setup (IK_QSegment *root, std::list< IK_QTask * > &tasks)
bool Solve (IK_QSegment *root, std::list< IK_QTask * > tasks, const MT_Scalar tolerance, const int max_iterations)
Detailed Description
Author:
Laurence Bourn
Date:
28/6/2001
Definition at line 52 of file IK_QJacobianSolver.h.
Constructor & Destructor Documentation
IK_QJacobianSolver::IK_QJacobianSolver ()
Definition at line 39 of file IK_QJacobianSolver.cpp.
References MT_Transform::setIdentity().
IK_QJacobianSolver::~IK_QJacobianSolver () [inline]
Definition at line 56 of file IK_QJacobianSolver.h.
Member Function Documentation
float IK_QJacobianSolver::GetPoleAngle () [inline]
Definition at line 61 of file IK_QJacobianSolver.h.
Referenced by IK_SolverGetPoleAngle().
void IK_QJacobianSolver::SetPoleVectorConstraint (IK_QSegment * tip, MT_Vector3 & goal, MT_Vector3 & polegoal, float poleangle, bool getangle)
Definition at line 162 of file IK_QJacobianSolver.cpp.
Referenced by IK_SolverSetPoleVectorConstraint().
bool IK_QJacobianSolver::Setup (IK_QSegment * root, std::list< IK_QTask * > & tasks)
Definition at line 85 of file IK_QJacobianSolver.cpp.
References IK_QJacobian::ArmMatrices(), i, MT_fuzzyZero(), IK_QTask::Primary(), IK_QSegment::SetDoFId(), IK_QJacobian::SetDoFWeight(), IK_QTask::SetId(), IK_QTask::SetWeight(), IK_QTask::Size(), and IK_QTask::Weight().
Referenced by IK_Solve().
bool IK_QJacobianSolver::Solve (IK_QSegment * root, std::list< IK_QTask * > tasks, const MT_Scalar tolerance, const int max_iterations)
Definition at line 320 of file IK_QJacobianSolver.cpp.
References IK_QJacobian::AngleUpdateNorm(), MT_Transform::getBasis(), IK_QJacobian::Invert(), IK_QSegment::PrependBasis(), IK_QJacobian::SubTask(), and IK_QSegment::UpdateTransform().
Referenced by IK_Solve().
The documentation for this class was generated from the following files:
IK_QJacobianSolver.h
IK_QJacobianSolver.cpp