Blender: svm_normal.h File Reference
svm_normal.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void svm_node_normal (KernelGlobals *kg, ShaderData *sd, float *stack, uint in_normal_offset, uint out_normal_offset, uint out_dot_offset, int *offset)
Function Documentation
CCL_NAMESPACE_BEGIN __device void svm_node_normal (KernelGlobals * kg, ShaderData * sd, float * stack, uint in_normal_offset, uint out_normal_offset, uint out_dot_offset, int * offset)
Definition at line 21 of file svm_normal.h.
References __int_as_float(), dot(), normalize(), read_node(), stack_load_float3(), stack_store_float(), stack_store_float3(), stack_valid(), float3::x, uint4::x, float3::y, uint4::y, float3::z, and uint4::z.
Referenced by svm_eval_nodes().