Blender: SeqEffectHandle Struct Reference
SeqEffectHandle Struct Reference
#include <BKE_sequencer.h>
Public Attributes
void(* init)(struct Sequence *seq)
void(* init_plugin)(struct Sequence *seq, const char *fname)
int(* num_inputs)(void)
void(* load)(struct Sequence *seq)
void(* copy)(struct Sequence *dst, struct Sequence *src)
void(* free)(struct Sequence *seq)
int(* early_out)(struct Sequence *seq, float facf0, float facf1)
void(* store_icu_yrange)(struct Sequence *seq, short adrcode, float *ymin, float *ymax)
void(* get_default_fac)(struct Sequence *seq, float cfra, float *facf0, float *facf1)
struct ImBuf *(* execute)(SeqRenderData context, struct Sequence *seq, float cfra, float facf0, float facf1, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3)
Detailed Description
Definition at line 114 of file BKE_sequencer.h.
Member Data Documentation
void(* SeqEffectHandle::copy)(struct Sequence *dst, struct Sequence *src)
Definition at line 129 of file BKE_sequencer.h.
Referenced by get_sequence_effect_impl().
int(* SeqEffectHandle::early_out)(struct Sequence *seq, float facf0, float facf1)
Definition at line 138 of file BKE_sequencer.h.
Referenced by get_sequence_effect_impl(), seq_get_early_out_for_blend_mode(), seq_render_effect_strip_impl(), and seq_render_strip_stack().
struct ImBuf*(* SeqEffectHandle::execute)(SeqRenderData context, struct Sequence *seq, float cfra, float facf0, float facf1, struct ImBuf *ibuf1, struct ImBuf *ibuf2, struct ImBuf *ibuf3) [read]
Definition at line 151 of file BKE_sequencer.h.
Referenced by get_sequence_effect_impl(), get_sequence_effect_num_inputs(), seq_render_effect_strip_impl(), and seq_render_strip_stack().
void(* SeqEffectHandle::free)(struct Sequence *seq)
Definition at line 132 of file BKE_sequencer.h.
Referenced by change_plugin_seq(), get_sequence_effect_impl(), seq_free_sequence(), and sequencer_change_effect_type_exec().
void(* SeqEffectHandle::get_default_fac)(struct Sequence *seq, float cfra, float *facf0, float *facf1)
Definition at line 144 of file BKE_sequencer.h.
Referenced by get_sequence_effect_impl(), and seq_render_effect_strip_impl().
void(* SeqEffectHandle::init)(struct Sequence *seq)
Definition at line 117 of file BKE_sequencer.h.
Referenced by get_sequence_effect_impl(), sequencer_add_effect_strip_exec(), and sequencer_change_effect_type_exec().
void(* SeqEffectHandle::init_plugin)(struct Sequence *seq, const char *fname)
Definition at line 118 of file BKE_sequencer.h.
Referenced by change_plugin_seq(), get_sequence_effect_impl(), and sequencer_add_effect_strip_exec().
void(* SeqEffectHandle::load)(struct Sequence *seq)
Definition at line 126 of file BKE_sequencer.h.
Referenced by get_sequence_blend(), get_sequence_effect(), and get_sequence_effect_impl().
int(* SeqEffectHandle::num_inputs)(void)
Definition at line 122 of file BKE_sequencer.h.
Referenced by get_sequence_effect_impl(), and get_sequence_effect_num_inputs().
void(* SeqEffectHandle::store_icu_yrange)(struct Sequence *seq, short adrcode, float *ymin, float *ymax)
Definition at line 141 of file BKE_sequencer.h.
Referenced by get_sequence_effect_impl().
The documentation for this struct was generated from the following file:
BKE_sequencer.h