Blender: BLI_boxpack2d.h File Reference
BLI_boxpack2d.h File Reference
blenlib
Classes
struct boxPack
Typedefs
typedef struct boxPack boxPack
Functions
void boxPack2D (boxPack *boxarray, const int len, float *tot_width, float *tot_height)
Detailed Description
Definition in file BLI_boxpack2d.h.
Typedef Documentation
typedef struct boxPack boxPack
Function Documentation
void boxPack2D (boxPack * boxarray, const int len, float * tot_width, float * tot_height)
Definition at line 155 of file boxpack2d.c.
References BL, boxVert::blb, BLF, box_areasort(), box_height, box_width, BOXBOTTOM, BOXINTERSECT, BOXLEFT, BOXRIGHT, BOXTOP, BR, boxVert::brb, BRF, CORNERFLAGS, boxVert::free, boxPack::h, i, boxVert::index, boxVert::isect_cache, len(), MAX2, MEM_freeN(), MEM_mallocN(), NULL, SET_BOXBOTTOM, SET_BOXLEFT, SET_BOXRIGHT, SET_BOXTOP, TL, boxVert::tlb, TLF, TR, boxVert::trb, TRF, boxPack::v, vertex_sort(), boxPack::w, boxPack::x, boxVert::x, boxPack::y, and boxVert::y.
Referenced by M_Geometry_box_pack_2d(), and param_pack().