Blender: editmesh_select.c File Reference
editmesh_select.c File Reference
mesh
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_array.h"
#include "BLI_smallhash.h"
#include "BLI_heap.h"
#include "BKE_context.h"
#include "BKE_displist.h"
#include "BKE_depsgraph.h"
#include "BKE_report.h"
#include "BKE_paint.h"
#include "BKE_tessmesh.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "ED_mesh.h"
#include "ED_screen.h"
#include "ED_uvedit.h"
#include "ED_view3d.h"
#include "BIF_gl.h"
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "DNA_mesh_types.h"
#include "mesh_intern.h"
Functions
void EDBM_select_mirrored (Object *UNUSED(obedit), BMEditMesh *em, int extend)
void EDBM_automerge (Scene *scene, Object *obedit, int update)
static void draw_triangulated (int mcords[][2], short tot)
int EDBM_backbuf_border_init (ViewContext *vc, short xmin, short ymin, short xmax, short ymax)
int EDBM_backbuf_check (unsigned int index)
void EDBM_backbuf_free (void)
int EDBM_backbuf_border_mask_init (ViewContext *vc, int mcords[][2], short tot, short xmin, short ymin, short xmax, short ymax)
int EDBM_backbuf_circle_init (ViewContext *vc, short xs, short ys, short rads)
static void findnearestvert__doClosest (void *userData, BMVert *eve, int x, int y, int index)
static unsigned int findnearestvert__backbufIndextest (void *handle, unsigned int index)
BMVert * EDBM_vert_find_nearest (ViewContext *vc, int *dist, short sel, short strict)
float labda_PdistVL2Dfl (const float v1[3], const float v2[3], const float v3[3])
static void findnearestedge__doClosest (void *userData, BMEdge *eed, int x0, int y0, int x1, int y1, int UNUSED(index))
BMEdge * EDBM_edge_find_nearest (ViewContext *vc, int *dist)
static void findnearestface__getDistance (void *userData, BMFace *efa, int x, int y, int UNUSED(index))
static void findnearestface__doClosest (void *userData, BMFace *efa, int x, int y, int index)
BMFace * EDBM_face_find_nearest (ViewContext *vc, int *dist)
static int unified_findnearest (ViewContext *vc, BMVert **r_eve, BMEdge **r_eed, BMFace **r_efa)
static int similar_face_select_exec (bContext *C, wmOperator *op)
static int similar_edge_select_exec (bContext *C, wmOperator *op)
static int similar_vert_select_exec (bContext *C, wmOperator *op)
static int edbm_select_similar_exec (bContext *C, wmOperator *op)
static EnumPropertyItem * select_similar_type_itemf (bContext *C, PointerRNA *UNUSED(ptr), PropertyRNA *UNUSED(prop), int *free)
void MESH_OT_select_similar (wmOperatorType *ot)
static void walker_select (BMEditMesh *em, int walkercode, void *start, int select)
static int edbm_loop_multiselect_exec (bContext *C, wmOperator *op)
void MESH_OT_loop_multi_select (wmOperatorType *ot)
static void mouse_mesh_loop (bContext *C, int mval[2], short extend, short ring)
static int edbm_select_loop_invoke (bContext *C, wmOperator *op, wmEvent *event)
void MESH_OT_loop_select (wmOperatorType *ot)
void MESH_OT_edgering_select (wmOperatorType *ot)
static float edgetag_cut_cost (BMEditMesh *UNUSED(em), BMEdge *e1, BMEdge *e2, BMVert *v)
static void edgetag_add_adjacent (BMEditMesh *em, SmallHash *visithash, Heap *heap, int mednum, int vertnum, int *nedges, int *edges, int *prevedge, float *cost)
static void edgetag_context_set (BMEditMesh *em, Scene *scene, BMEdge *e, int val)
static int edgetag_context_check (Scene *scene, BMEditMesh *em, BMEdge *e)
static int edgetag_shortest_path (Scene *scene, BMEditMesh *em, BMEdge *source, BMEdge *target)
static int mouse_mesh_shortest_path (bContext *C, int mval[2])
static int edbm_shortest_path_select_invoke (bContext *C, wmOperator *UNUSED(op), wmEvent *event)
static int edbm_shortest_path_select_poll (bContext *C)
void MESH_OT_select_shortest_path (wmOperatorType *ot)
int mouse_mesh (bContext *C, const int mval[2], short extend)
static void edbm_strip_selections (BMEditMesh *em)
void EDBM_selectmode_set (BMEditMesh *em)
void EDBM_selectmode_convert (BMEditMesh *em, short oldmode, short selectmode)
void EDBM_deselect_by_material (BMEditMesh *em, const short index, const short select)
void EDBM_select_toggle_all (BMEditMesh *em)
void EDBM_select_swap (BMEditMesh *em)
int EDBM_select_interior_faces (BMEditMesh *em)
static void linked_limit_default (bContext *C, wmOperator *op)
static int edbm_select_linked_pick_invoke (bContext *C, wmOperator *op, wmEvent *event)
void MESH_OT_select_linked_pick (wmOperatorType *ot)
static int edbm_select_linked_exec (bContext *C, wmOperator *op)
void MESH_OT_select_linked (wmOperatorType *ot)
static int edbm_select_more_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_select_more (wmOperatorType *ot)
static int edbm_select_less_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_select_less (wmOperatorType *ot)
static void walker_deselect_nth (BMEditMesh *em, int nth, int offset, BMHeader *h_act)
static void deselect_nth_active (BMEditMesh *em, BMVert **r_eve, BMEdge **r_eed, BMFace **r_efa)
static int edbm_deselect_nth (BMEditMesh *em, int nth, int offset)
static int edbm_select_nth_exec (bContext *C, wmOperator *op)
void MESH_OT_select_nth (wmOperatorType *ot)
void em_setup_viewcontext (bContext *C, ViewContext *vc)
int EM_view3d_poll (bContext *C)
static int edbm_select_sharp_edges_exec (bContext *C, wmOperator *op)
void MESH_OT_edges_select_sharp (wmOperatorType *ot)
static int edbm_select_linked_flat_faces_exec (bContext *C, wmOperator *op)
void MESH_OT_faces_select_linked_flat (wmOperatorType *ot)
static int edbm_select_non_manifold_exec (bContext *C, wmOperator *op)
void MESH_OT_select_non_manifold (wmOperatorType *ot)
static int edbm_select_random_exec (bContext *C, wmOperator *op)
void MESH_OT_select_random (wmOperatorType *ot)
static int edbm_select_next_loop_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_select_next_loop (wmOperatorType *ot)
static int edbm_region_to_loop_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_region_to_loop (wmOperatorType *ot)
static int loop_find_region (BMLoop *l, int flag, SmallHash *fhash, BMFace ***region_out)
static int verg_radial (const void *va, const void *vb)
static int loop_find_regions (BMEditMesh *em, int selbigger)
static int edbm_loop_to_region_exec (bContext *C, wmOperator *op)
void MESH_OT_loop_to_region (wmOperatorType *ot)
Variables
unsigned int bm_solidoffs = 0
unsigned int bm_wireoffs = 0
unsigned int bm_vertoffs = 0
static char * selbuf = NULL
static EnumPropertyItem prop_similar_types []
Detailed Description
Definition in file editmesh_select.c.
Function Documentation
static void deselect_nth_active (BMEditMesh * em, BMVert ** r_eve, BMEdge ** r_eed, BMFace ** r_efa) [static]
Definition at line 2093 of file editmesh_select.c.
References BMEditMesh::bm, BM_active_face_get(), BM_EDGE, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SELECT, BM_FACE, BM_ITER_MESH, BM_VERT, BM_VERTS_OF_MESH, EDBM_selectmode_flush(), BMEditSelection::ele, BMEditSelection::htype, if(), ListBase::last, NULL, SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMesh::selected, BMEditMesh::selectmode, and TRUE.
Referenced by edbm_deselect_nth().
static void draw_triangulated (int mcords[][2], short tot) [static]
Definition at line 132 of file editmesh_select.c.
References BLI_addtail(), DL_INDEX3, DL_POLY, filldisplist(), ListBase::first, freedisplist(), DispList::index, MEM_callocN(), DispList::nr, NULL, DispList::parts, DispList::type, and DispList::verts.
Referenced by EDBM_backbuf_border_mask_init().
void EDBM_automerge (Scene * scene, Object * obedit, int update)
Definition at line 105 of file editmesh_select.c.
References ToolSettings::automerge, BMEditMesh::bm, BM_ELEM_SELECT, BMEdit_FromObject(), BMEdit_RecalcTessellation(), BMO_op_callf(), DAG_id_tag_update(), Object::data, ToolSettings::doublimit, OB_MESH, OB_RECALC_DATA, Scene::toolsettings, and Object::type.
Referenced by special_aftertrans_update().
int EDBM_backbuf_border_init (ViewContext * vc, short xmin, short ymin, short xmax, short ymax)
Definition at line 179 of file editmesh_select.c.
References bm_vertoffs, View3D::drawtype, View3D::flag, IMB_freeImBuf(), MEM_callocN(), NULL, OB_SOLID, ViewContext::obedit, ImBuf::rect, ViewContext::v3d, V3D_ZBUF_SELECT, and view3d_read_backbuf().
Referenced by do_mesh_box_select().
int EDBM_backbuf_border_mask_init (ViewContext * vc, int mcords[][2], short tot, short xmin, short ymin, short xmax, short ymax)
Definition at line 228 of file editmesh_select.c.
References ViewContext::ar, bm_vertoffs, draw_triangulated(), View3D::drawtype, ED_region_pixelspace(), View3D::flag, IMB_freeImBuf(), MEM_callocN(), NULL, OB_SOLID, ViewContext::obact, ViewContext::obedit, paint_facesel_test(), paint_vertsel_test(), ImBuf::rect, ViewContext::v3d, V3D_ZBUF_SELECT, and view3d_read_backbuf().
Referenced by do_lasso_select_mesh(), do_lasso_select_paintface(), and do_lasso_select_paintvert().
int EDBM_backbuf_check (unsigned int index)
Definition at line 208 of file editmesh_select.c.
References bm_vertoffs, ImBuf::index, and NULL.
Referenced by do_lasso_select_mesh__doSelectEdge(), do_mesh_box_select__doSelectEdge(), edbm_backbuf_check_and_select_edges(), edbm_backbuf_check_and_select_faces(), edbm_backbuf_check_and_select_tfaces(), edbm_backbuf_check_and_select_verts(), and edbm_backbuf_check_and_select_verts_obmode().
int EDBM_backbuf_circle_init (ViewContext * vc, short xs, short ys, short rads)
Definition at line 289 of file editmesh_select.c.
References bm_vertoffs, View3D::drawtype, View3D::flag, IMB_freeImBuf(), MEM_callocN(), NULL, OB_SOLID, ViewContext::obact, ViewContext::obedit, paint_facesel_test(), paint_vertsel_test(), ImBuf::rect, ViewContext::v3d, V3D_ZBUF_SELECT, and view3d_read_backbuf().
Referenced by mesh_circle_select(), paint_facesel_circle_select(), and paint_vertsel_circle_select().
void EDBM_backbuf_free (void)
Definition at line 216 of file editmesh_select.c.
References MEM_freeN(), and NULL.
Referenced by do_lasso_select_mesh(), do_lasso_select_paintface(), do_lasso_select_paintvert(), do_mesh_box_select(), mesh_circle_select(), paint_facesel_circle_select(), and paint_vertsel_circle_select().
void EDBM_deselect_by_material (BMEditMesh * em, const short index, const short select)
Definition at line 1659 of file editmesh_select.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_face_select_set(), BM_FACES_OF_MESH, BM_ITER_MESH, and BMFace::mat_nr.
Referenced by material_slot_de_select().
static int edbm_deselect_nth (BMEditMesh * em, int nth, int offset) [static]
Definition at line 2147 of file editmesh_select.c.
References deselect_nth_active(), BMEdge::head, BMVert::head, BMFace::head, and walker_deselect_nth().
Referenced by edbm_select_nth_exec().
BMEdge* EDBM_edge_find_nearest (ViewContext * vc, int * dist) [read]
Definition at line 498 of file editmesh_select.c.
References BMEditMesh::bm, BM_edge_at_index(), bm_wireoffs, data, distance(), View3D::drawtype, ED_view3d_init_mats_rv3d(), ViewContext::em, findnearestedge__doClosest(), View3D::flag, mesh_foreachScreenEdge(), ViewContext::mval, NULL, OB_WIRE, ViewContext::obedit, ViewContext::rv3d, ViewContext::v3d, V3D_ZBUF_SELECT, view3d_sample_backbuf_rect(), and view3d_validate_backbuf().
Referenced by loopcut_modal(), mouse_mesh_loop(), mouse_mesh_shortest_path(), ringcut_invoke(), and unified_findnearest().
BMFace* EDBM_face_find_nearest (ViewContext * vc, int * dist) [read]
Definition at line 571 of file editmesh_select.c.
References BMEditMesh::bm, BM_face_at_index(), data, View3D::drawtype, ED_view3d_init_mats_rv3d(), ViewContext::em, findnearestface__doClosest(), findnearestface__getDistance(), View3D::flag, mesh_foreachScreenFace(), ViewContext::mval, NULL, OB_WIRE, ViewContext::obedit, ViewContext::rv3d, SCE_SELECT_FACE, BMEditMesh::selectmode, ViewContext::v3d, V3D_ZBUF_SELECT, view3d_sample_backbuf(), and view3d_validate_backbuf().
Referenced by knife_find_closest_face(), and unified_findnearest().
static int edbm_loop_multiselect_exec (bContext * C, wmOperator * op) [static]
Definition at line 916 of file editmesh_select.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SELECT, BM_iter_new(), BM_iter_step(), BMEdit_FromObject(), BMW_EDGERING, BMW_LOOP, CTX_data_edit_object(), EDBM_selectmode_flush(), MEM_freeN(), MEM_mallocN(), NC_GEOM, ND_SELECT, NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), TRUE, walker_select(), and WM_event_add_notifier().
Referenced by MESH_OT_loop_multi_select().
static int edbm_loop_to_region_exec (bContext * C, wmOperator * op) [static]
Definition at line 2733 of file editmesh_select.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ELEM_TAG, BM_face_select_set(), BM_FACES_OF_MESH, BM_ITER_MESH, BMEdit_FromObject(), CTX_data_edit_object(), Object::data, EDBM_flag_disable_all(), loop_find_regions(), NC_GEOM, ND_SELECT, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), TRUE, and WM_event_add_notifier().
Referenced by MESH_OT_loop_to_region().
static int edbm_region_to_loop_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2532 of file editmesh_select.c.
References BMEditMesh::bm, BM_EDGE, BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_SELECT, BM_ELEM_TAG, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_EDGE, BM_LOOPS_OF_FACE, BM_mesh_elem_hflag_disable_all(), BMEdit_FromObject(), CTX_data_edit_object(), Object::data, BMLoop::e, EDBM_flag_disable_all(), EDBM_selectmode_set(), EDBM_selectmode_to_scene(), BMLoop::f, FALSE, NC_GEOM, ND_SELECT, OPERATOR_FINISHED, SCE_SELECT_EDGE, SCE_SELECT_FACE, BMEditMesh::selectmode, TRUE, and WM_event_add_notifier().
Referenced by MESH_OT_region_to_loop().
int EDBM_select_interior_faces (BMEditMesh * em)
Definition at line 1713 of file editmesh_select.c.
References BMEditMesh::bm, BM_edge_face_count(), BM_EDGES_OF_FACE, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_face_select_set(), BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, FALSE, and TRUE.
Referenced by edbm_faces_select_interior_exec().
static int edbm_select_less_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1996 of file editmesh_select.c.
References BMEdit_FromObject(), CTX_data_edit_object(), EDBM_select_less(), NC_GEOM, ND_SELECT, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by MESH_OT_select_less().
static int edbm_select_linked_exec (bContext * C, wmOperator * op) [static]
Definition at line 1872 of file editmesh_select.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_set, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SEAM, BM_ELEM_SELECT, BM_ELEM_TAG, BM_face_select_set(), BM_FACES_OF_MESH, BM_ITER_MESH, BM_vert_select_set(), BM_VERTS_OF_MESH, BMEdit_FromObject(), BMO_elem_flag_set, BMW_begin(), BMW_end(), BMW_FLAG_TEST_HIDDEN, BMW_init(), BMW_ISLAND, BMW_MASK_NOP, BMW_NIL_LAY, BMW_SHELL, BMW_step(), CTX_data_edit_object(), EDBM_selectmode_flush_ex(), linked_limit_default(), NC_GEOM, ND_SELECT, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, TRUE, BMEdge::v1, BMEdge::v2, and WM_event_add_notifier().
Referenced by MESH_OT_select_linked().
static int edbm_select_linked_flat_faces_exec (bContext * C, wmOperator * op) [static]
Definition at line 2286 of file editmesh_select.c.
References angle(), angle_normalized_v3v3(), BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growone, BMEditMesh::bm, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ELEM_TAG, BM_face_select_set(), BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_LOOPS_OF_LOOP, BMEdit_FromObject(), CTX_data_edit_object(), Object::data, BMLoop::f, i, M_PI, NC_GEOM, ND_SELECT, BMFace::no, NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get(), stack, TRUE, and WM_event_add_notifier().
Referenced by MESH_OT_faces_select_linked_flat().
static int edbm_select_linked_pick_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1757 of file editmesh_select.c.
References BMEditMesh::bm, BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SEAM, BM_ELEM_SELECT, BM_FACE_FIRST_LOOP, BM_face_select_set(), BM_ITER_MESH, BM_mesh_select_mode_flush(), BMO_elem_flag_set, BMW_begin(), BMW_end(), BMW_FLAG_TEST_HIDDEN, BMW_init(), BMW_ISLAND, BMW_MASK_NOP, BMW_NIL_LAY, BMW_SHELL, BMW_step(), CTX_data_edit_object(), BMVert::e, ViewContext::em, em_setup_viewcontext(), linked_limit_default(), ViewContext::mval, NC_GEOM, ND_SELECT, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), SCE_SELECT_FACE, BMEditMesh::selectmode, BMesh::totedge, unified_findnearest(), BMEdge::v1, view3d_operator_needs_opengl(), and WM_event_add_notifier().
Referenced by MESH_OT_select_linked_pick().
static int edbm_select_loop_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1066 of file editmesh_select.c.
References mouse_mesh_loop(), wmEvent::mval, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), and view3d_operator_needs_opengl().
Referenced by MESH_OT_edgering_select(), and MESH_OT_loop_select().
void EDBM_select_mirrored (Object * UNUSEDobedit, BMEditMesh * em, int extend)
Definition at line 73 of file editmesh_select.c.
References BMEditMesh::bm, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ELEM_TAG, BM_ITER_MESH, BM_vert_select_set(), BM_VERTS_OF_MESH, EDBM_flag_disable_all(), EDBM_verts_mirror_cache_begin(), EDBM_verts_mirror_cache_end(), EDBM_verts_mirror_get(), and TRUE.
static int edbm_select_more_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1970 of file editmesh_select.c.
References BMEdit_FromObject(), CTX_data_edit_object(), EDBM_select_more(), NC_GEOM, ND_SELECT, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by MESH_OT_select_more().
static int edbm_select_next_loop_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2482 of file editmesh_select.c.
References BMEditMesh::bm, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_SELECT, BM_ELEM_TAG, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_vert_select_set(), BM_VERTS_OF_MESH, BMEdit_FromObject(), CTX_data_edit_object(), FALSE, NC_GEOM, ND_SELECT, BMLoop::next, OPERATOR_FINISHED, TRUE, BMLoop::v, and WM_event_add_notifier().
Referenced by MESH_OT_select_next_loop().
static int edbm_select_non_manifold_exec (bContext * C, wmOperator * op) [static]
Definition at line 2367 of file editmesh_select.c.
References BKE_report(), BMEditMesh::bm, BM_edge_is_manifold(), BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ITER_MESH, BM_vert_is_manifold(), BM_vert_select_set(), BM_VERTS_OF_MESH, BMEdit_FromObject(), CTX_data_edit_object(), Object::data, NC_GEOM, ND_SELECT, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, SCE_SELECT_FACE, BMEditMesh::selectmode, TRUE, and WM_event_add_notifier().
Referenced by MESH_OT_select_non_manifold().
static int edbm_select_nth_exec (bContext * C, wmOperator * op) [static]
Definition at line 2171 of file editmesh_select.c.
References BKE_report(), BMEdit_FromObject(), CTX_data_edit_object(), edbm_deselect_nth(), EDBM_update_generic(), FALSE, MIN2, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_int_get(), and RPT_ERROR.
Referenced by MESH_OT_select_nth().
static int edbm_select_random_exec (bContext * C, wmOperator * op) [static]
Definition at line 2416 of file editmesh_select.c.
References BLI_frand(), BLI_rand(), BLI_srand(), BMEditMesh::bm, BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_face_select_set(), BM_FACES_OF_MESH, BM_ITER_MESH, BM_vert_select_set(), BM_VERTS_OF_MESH, BMEdit_FromObject(), CTX_data_edit_object(), Object::data, EDBM_flag_disable_all(), EDBM_selectmode_flush(), NC_GEOM, ND_SELECT, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_float_get(), SCE_SELECT_EDGE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, TRUE, and WM_event_add_notifier().
Referenced by MESH_OT_select_random().
static int edbm_select_sharp_edges_exec (bContext * C, wmOperator * op) [static]
Definition at line 2229 of file editmesh_select.c.
References angle(), angle_normalized_v3v3(), BMEditMesh::bm, BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ITER_MESH, BMEdit_FromObject(), CTX_data_edit_object(), Object::data, DEG2RADF, BMLoop::f, fabsf, BMEdge::l, NC_GEOM, ND_SELECT, BMFace::no, OPERATOR_FINISHED, wmOperator::ptr, BMLoop::radial_next, RNA_float_get(), TRUE, and WM_event_add_notifier().
Referenced by MESH_OT_edges_select_sharp().
static int edbm_select_similar_exec (bContext * C, wmOperator * op) [static]
Definition at line 814 of file editmesh_select.c.
References CTX_data_tool_settings(), wmOperator::ptr, RNA_enum_get(), RNA_property_float_get(), RNA_property_float_set(), RNA_property_is_set(), RNA_struct_find_property(), ToolSettings::select_thresh, similar_edge_select_exec(), similar_face_select_exec(), and similar_vert_select_exec().
Referenced by MESH_OT_select_similar().
void EDBM_select_swap (BMEditMesh * em)
Definition at line 1681 of file editmesh_select.c.
References BMEditMesh::bm, BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_face_select_set(), BM_FACES_OF_MESH, BM_ITER_MESH, BM_vert_select_set(), BM_VERTS_OF_MESH, SCE_SELECT_EDGE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, and BMesh::selectmode.
Referenced by edbm_select_all_exec(), and select_all_perform().
void EDBM_select_toggle_all (BMEditMesh * em)
Definition at line 1673 of file editmesh_select.c.
References BMEditMesh::bm, BM_ELEM_SELECT, EDBM_flag_disable_all(), EDBM_flag_enable_all(), BMesh::totedgesel, BMesh::totfacesel, and BMesh::totvertsel.
Referenced by edbm_select_all_exec(), and select_all_perform().
void EDBM_selectmode_convert (BMEditMesh * em, short oldmode, short selectmode)
Definition at line 1601 of file editmesh_select.c.
References BMEditMesh::bm, BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SELECT, BM_face_select_set(), BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, NULL, SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, TRUE, BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by do_view3d_header_buttons().
void EDBM_selectmode_set (BMEditMesh * em)
Definition at line 1558 of file editmesh_select.c.
References BMEditMesh::bm, BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SELECT, BM_face_select_set(), BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_vert_select_set(), BM_VERTS_OF_MESH, EDBM_select_flush(), EDBM_selectmode_flush(), edbm_strip_selections(), FALSE, NULL, SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, BMesh::selectmode, and TRUE.
Referenced by do_view3d_header_buttons(), edbm_region_to_loop_exec(), and ringsel_finish().
static int edbm_shortest_path_select_invoke (bContext * C, wmOperator * UNUSEDop, wmEvent * event) [static]
Definition at line 1414 of file editmesh_select.c.
References mouse_mesh_shortest_path(), wmEvent::mval, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, and view3d_operator_needs_opengl().
Referenced by MESH_OT_select_shortest_path().
static int edbm_shortest_path_select_poll (bContext * C) [static]
Definition at line 1427 of file editmesh_select.c.
References BMEdit_FromObject(), CTX_data_edit_object(), ED_operator_editmesh_region_view3d(), SCE_SELECT_EDGE, and BMEditMesh::selectmode.
Referenced by MESH_OT_select_shortest_path().
static void edbm_strip_selections (BMEditMesh * em) [static]
Definition at line 1526 of file editmesh_select.c.
References BLI_freelinkN(), BMEditMesh::bm, BM_EDGE, BM_FACE, BM_VERT, ListBase::first, BMEditSelection::htype, BMEditSelection::next, SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMesh::selected, and BMEditMesh::selectmode.
Referenced by EDBM_selectmode_set().
BMVert* EDBM_vert_find_nearest (ViewContext * vc, int * dist, short sel, short strict) [read]
findnearestvert
dist (in/out): minimal distance to the nearest and at the end, actual distance sel: selection bias if SELECT, selected vertice are given a 5 pixel bias to make them further than unselect verts if 0, unselected vertice are given the bias strict: if 1, the vertice corresponding to the sel parameter are ignored and not just biased
Definition at line 380 of file editmesh_select.c.
References BMEditMesh::bm, BM_vert_at_index(), bm_wireoffs, data, distance(), View3D::drawtype, ED_view3d_init_mats_rv3d(), ViewContext::em, findnearestvert__backbufIndextest(), findnearestvert__doClosest(), View3D::flag, mesh_foreachScreenVert(), ViewContext::mval, NULL, OB_WIRE, ViewContext::obedit, ViewContext::rv3d, ViewContext::v3d, V3D_CLIP_TEST_RV3D_CLIPPING, V3D_ZBUF_SELECT, and view3d_sample_backbuf_rect().
Referenced by unified_findnearest().
static void edgetag_add_adjacent (BMEditMesh * em, SmallHash * visithash, Heap * heap, int mednum, int vertnum, int * nedges, int * edges, int * prevedge, float * cost) [static]
Definition at line 1137 of file editmesh_select.c.
References BLI_heap_insert(), BLI_smallhash_haskey(), EDBM_edge_at_index(), EDBM_vert_at_index(), edgetag_cut_cost(), and SET_INT_IN_POINTER.
Referenced by edgetag_shortest_path().
static int edgetag_context_check (Scene * scene, BMEditMesh * em, BMEdge * e) [static]
Definition at line 1192 of file editmesh_select.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_elem_float_data_get(), BM_ELEM_SEAM, BM_ELEM_SELECT, BM_ELEM_SMOOTH, CD_BWEIGHT, CD_CREASE, BMesh::edata, ToolSettings::edge_mode, EDGE_MODE_SELECT, EDGE_MODE_TAG_BEVEL, EDGE_MODE_TAG_CREASE, EDGE_MODE_TAG_SEAM, EDGE_MODE_TAG_SHARP, and Scene::toolsettings.
Referenced by edgetag_shortest_path(), and mouse_mesh_shortest_path().
static void edgetag_context_set (BMEditMesh * em, Scene * scene, BMEdge * e, int val) [static]
Definition at line 1164 of file editmesh_select.c.
References BMEditMesh::bm, BM_edge_select_set(), BM_elem_flag_set, BM_ELEM_SEAM, BM_ELEM_SMOOTH, CD_BWEIGHT, CD_CREASE, CustomData_bmesh_get(), BMHeader::data, BMesh::edata, ToolSettings::edge_mode, EDGE_MODE_SELECT, EDGE_MODE_TAG_BEVEL, EDGE_MODE_TAG_CREASE, EDGE_MODE_TAG_SEAM, EDGE_MODE_TAG_SHARP, BMEdge::head, and Scene::toolsettings.
Referenced by edgetag_shortest_path(), and mouse_mesh_shortest_path().
static float edgetag_cut_cost (BMEditMesh * UNUSEDem, BMEdge * e1, BMEdge * e2, BMVert * v) [static]
Definition at line 1117 of file editmesh_select.c.
References BMVert::co, dot_v3v3(), fabs(), len_v3(), sqrt(), sub_v3_v3v3(), BMEdge::v1, and BMEdge::v2.
Referenced by edgetag_add_adjacent().
static int edgetag_shortest_path (Scene * scene, BMEditMesh * em, BMEdge * source, BMEdge * target) [static]
Definition at line 1209 of file editmesh_select.c.
References BLI_heap_empty(), BLI_heap_free(), BLI_heap_insert(), BLI_heap_new(), BLI_heap_popmin(), BLI_smallhash_haskey(), BLI_smallhash_init(), BLI_smallhash_insert(), BLI_smallhash_release(), BMEditMesh::bm, BM_EDGE, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_index_get, BM_elem_index_set, BM_ITER_MESH, BM_mesh_elem_index_ensure(), BM_VERT, EDBM_edge_at_index(), EDBM_index_arrays_free(), EDBM_index_arrays_init(), edgetag_add_adjacent(), edgetag_context_check(), edgetag_context_set(), BMesh::elem_index_dirty, GET_INT_FROM_POINTER, i, MEM_callocN(), MEM_freeN(), MEM_mallocN(), NULL, SET_INT_IN_POINTER, BMesh::totvert, BMEdge::v1, and BMEdge::v2.
Referenced by mouse_mesh_shortest_path().
void em_setup_viewcontext (bContext * C, ViewContext * vc)
Definition at line 2209 of file editmesh_select.c.
References Object::data, Mesh::edit_btmesh, ViewContext::em, ViewContext::obedit, and view3d_set_viewcontext().
Referenced by edbm_dupli_extrude_cursor_invoke(), edbm_select_linked_pick_invoke(), knifetool_init(), mouse_mesh(), mouse_mesh_loop(), mouse_mesh_shortest_path(), ringsel_init(), vtx_slide_init(), and xsortvert_flag().
int EM_view3d_poll (bContext * C)
Definition at line 2220 of file editmesh_select.c.
References ED_operator_editmesh(), and ED_operator_view3d_active().
Referenced by MESH_OT_knife_cut(), MESH_OT_rip(), MESH_OT_screw(), MESH_OT_spin(), and MESH_OT_vertices_sort().
static void findnearestedge__doClosest (void * userData, BMEdge * eed, int x0, int y0, int x1, int y1, int UNUSEDindex) [static]
Definition at line 460 of file editmesh_select.c.
References BM_elem_flag_test, BM_ELEM_SELECT, BMVert::co, data, dist_to_line_segment_v2(), distance(), ED_view3d_clipping_test(), labda_PdistVL2Dfl(), mul_m4_v3(), RV3D_CLIPPING, TRUE, BMEdge::v1, and BMEdge::v2.
Referenced by EDBM_edge_find_nearest().
static void findnearestface__doClosest (void * userData, BMFace * efa, int x, int y, int index) [static]
Definition at line 547 of file editmesh_select.c.
References abs(), and data.
Referenced by EDBM_face_find_nearest().
static void findnearestface__getDistance (void * userData, BMFace * efa, int x, int y, int UNUSEDindex) [static]
Definition at line 536 of file editmesh_select.c.
References abs(), and data.
Referenced by EDBM_face_find_nearest().
static unsigned int findnearestvert__backbufIndextest (void * handle, unsigned int index) [static]
Definition at line 363 of file editmesh_select.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, and BM_vert_at_index().
Referenced by EDBM_vert_find_nearest().
static void findnearestvert__doClosest (void * userData, BMVert * eve, int x, int y, int index) [static]
Definition at line 328 of file editmesh_select.c.
References abs(), BM_elem_flag_test, BM_ELEM_SELECT, and data.
Referenced by EDBM_vert_find_nearest().
float labda_PdistVL2Dfl (const float v1[3], const float v2[3], const float v3[3])
Definition at line 446 of file editmesh_select.c.
References len().
Referenced by findnearestedge__doClosest(), and knife_find_closest_edge().
static void linked_limit_default (bContext * C, wmOperator * op) [static]
Definition at line 1745 of file editmesh_select.c.
References BMEdit_FromObject(), CTX_data_edit_object(), FALSE, wmOperator::ptr, RNA_boolean_set(), RNA_struct_property_is_set(), SCE_SELECT_FACE, BMEditMesh::selectmode, and TRUE.
Referenced by edbm_select_linked_exec(), and edbm_select_linked_pick_invoke().
static int loop_find_region (BMLoop * l, int flag, SmallHash * fhash, BMFace *** region_out) [static]
Definition at line 2595 of file editmesh_select.c.
References BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_free, BLI_array_pop, BLI_smallhash_haskey(), BLI_smallhash_insert(), BM_elem_flag_test, BM_ITER_ELEM, BM_LOOPS_OF_EDGE, BM_LOOPS_OF_FACE, BMLoop::e, BMLoop::f, NULL, and stack.
Referenced by loop_find_regions().
static int loop_find_regions (BMEditMesh * em, int selbigger) [static]
Definition at line 2650 of file editmesh_select.c.
References BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_free, BLI_smallhash_haskey(), BLI_smallhash_init(), BLI_smallhash_release(), BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_SELECT, BM_ELEM_TAG, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_EDGE, BM_LOOPS_OF_FACE, BMLoop::e, BMLoop::f, i, loop_find_region(), MEM_freeN(), NULL, and verg_radial().
Referenced by edbm_loop_to_region_exec().
void MESH_OT_edgering_select (wmOperatorType * ot)
Definition at line 1097 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh_region_view3d(), edbm_select_loop_invoke(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_edges_select_sharp (wmOperatorType * ot)
Definition at line 2268 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_sharp_edges_exec(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_faces_select_linked_flat (wmOperatorType * ot)
Definition at line 2349 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_linked_flat_faces_exec(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_loop_multi_select (wmOperatorType * ot)
Definition at line 973 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_loop_multiselect_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_loop_select (wmOperatorType * ot)
Definition at line 1078 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh_region_view3d(), edbm_select_loop_invoke(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_loop_to_region (wmOperatorType * ot)
Definition at line 2762 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_loop_to_region_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_region_to_loop (wmOperatorType * ot)
Definition at line 2580 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_region_to_loop_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_less (wmOperatorType * ot)
Definition at line 2007 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_less_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_linked (wmOperatorType * ot)
Definition at line 1951 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_linked_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_linked_pick (wmOperatorType * ot)
Definition at line 1853 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_linked_pick_invoke(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_more (wmOperatorType * ot)
Definition at line 1981 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_more_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_next_loop (wmOperatorType * ot)
Definition at line 2516 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_next_loop_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_non_manifold (wmOperatorType * ot)
Definition at line 2401 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_non_manifold_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_nth (wmOperatorType * ot)
Definition at line 2191 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_nth_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_random (wmOperatorType * ot)
Definition at line 2461 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_random_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_percentage(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_shortest_path (wmOperatorType * ot)
Definition at line 1437 of file editmesh_select.c.
References wmOperatorType::description, edbm_shortest_path_select_invoke(), edbm_shortest_path_select_poll(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_similar (wmOperatorType * ot)
Definition at line 868 of file editmesh_select.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_similar_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_float(), select_similar_type_itemf(), SIMVERT_NORMAL, wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_mesh().
int mouse_mesh (bContext * C, const int mval[2], short extend)
Definition at line 1458 of file editmesh_select.c.
References Object::actcol, BMEditMesh::bm, BM_active_face_set(), BM_edge_select_set(), BM_elem_flag_test, BM_ELEM_SELECT, BM_face_select_set(), BM_select_history_remove, BM_select_history_store, BM_vert_select_set(), EDBM_flag_disable_all(), EDBM_selectmode_flush(), ViewContext::em, em_setup_viewcontext(), FALSE, BMFace::mat_nr, BMEditMesh::mat_nr, ViewContext::mval, NC_GEOM, NC_MATERIAL, ND_SELECT, ND_SHADING, NULL, ViewContext::obedit, TRUE, unified_findnearest(), and WM_event_add_notifier().
Referenced by view3d_select_invoke().
static void mouse_mesh_loop (bContext * C, int mval[2], short extend, short ring) [static]
Definition at line 997 of file editmesh_select.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_select_history_store, BMW_EDGERING, BMW_FACELOOP, BMW_LOOP, EDBM_edge_find_nearest(), EDBM_flag_disable_all(), EDBM_selectmode_flush(), ViewContext::em, em_setup_viewcontext(), FALSE, ViewContext::mval, NC_GEOM, ND_SELECT, ViewContext::obedit, SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, TRUE, BMEdge::v1, view3d_validate_backbuf(), walker_select(), and WM_event_add_notifier().
Referenced by edbm_select_loop_invoke().
static int mouse_mesh_shortest_path (bContext * C, int mval[2]) [static]
Definition at line 1342 of file editmesh_select.c.
References BMEditMesh::bm, BM_EDGE, BM_select_history_remove, BM_select_history_store, CTX_data_tool_settings(), Object::data, Mesh::drawflag, ED_uvedit_live_unwrap(), EDBM_edge_find_nearest(), EDBM_selectmode_flush(), EDBM_update_generic(), EDGE_MODE_TAG_BEVEL, EDGE_MODE_TAG_CREASE, EDGE_MODE_TAG_SEAM, EDGE_MODE_TAG_SHARP, edgetag_context_check(), edgetag_context_set(), edgetag_shortest_path(), BMEditSelection::ele, ViewContext::em, em_setup_viewcontext(), FALSE, BMEditSelection::htype, if(), ListBase::last, ME_DRAWBWEIGHTS, ME_DRAWCREASES, ME_DRAWSEAMS, ME_DRAWSHARP, ViewContext::mval, ViewContext::obedit, ViewContext::scene, BMesh::selected, and TRUE.
Referenced by edbm_shortest_path_select_invoke().
static EnumPropertyItem* select_similar_type_itemf (bContext * C, PointerRNA * UNUSEDptr, PropertyRNA * UNUSEDprop, int * free) [static]
Definition at line 833 of file editmesh_select.c.
References BMEdit_FromObject(), CTX_data_edit_object(), NULL, OB_MESH, RNA_enum_item_end(), RNA_enum_items_add_value(), SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, SIMEDGE_LENGTH, SIMFACE_COPLANAR, SIMFACE_MATERIAL, SIMVERT_NORMAL, and Object::type.
Referenced by MESH_OT_select_similar().
static int similar_edge_select_exec (bContext * C, wmOperator * op) [static]
Definition at line 738 of file editmesh_select.c.
References BMEditMesh::bm, BM_ALL, BM_ELEM_SELECT, BMEdit_FromObject(), BMO_op_exec(), BMO_slot_buffer_hflag_enable(), CTX_data_edit_object(), EDBM_flag_disable_all(), EDBM_op_finish(), EDBM_op_init(), EDBM_selectmode_flush(), EDBM_update_generic(), FALSE, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), RNA_float_get(), thresh, and TRUE.
Referenced by edbm_select_similar_exec().
static int similar_face_select_exec (bContext * C, wmOperator * op) [static]
Definition at line 700 of file editmesh_select.c.
References BMEditMesh::bm, BM_ALL, BM_ELEM_SELECT, BMEdit_FromObject(), BMO_op_exec(), BMO_slot_buffer_hflag_enable(), CTX_data_edit_object(), EDBM_flag_disable_all(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), FALSE, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), RNA_float_get(), thresh, and TRUE.
Referenced by edbm_select_similar_exec().
static int similar_vert_select_exec (bContext * C, wmOperator * op) [static]
Definition at line 780 of file editmesh_select.c.
References BMEditMesh::bm, BM_ALL, BM_ELEM_SELECT, BMEdit_FromObject(), BMO_op_exec(), BMO_slot_buffer_hflag_enable(), CTX_data_edit_object(), EDBM_flag_disable_all(), EDBM_op_finish(), EDBM_op_init(), EDBM_selectmode_flush(), EDBM_update_generic(), FALSE, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), RNA_float_get(), thresh, and TRUE.
Referenced by edbm_select_similar_exec().
static int unified_findnearest (ViewContext * vc, BMVert ** r_eve, BMEdge ** r_eed, BMFace ** r_efa) [static]
Definition at line 641 of file editmesh_select.c.
References BM_ELEM_SELECT, EDBM_edge_find_nearest(), EDBM_face_find_nearest(), EDBM_vert_find_nearest(), ViewContext::em, NULL, SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, and view3d_validate_backbuf().
Referenced by edbm_select_linked_pick_invoke(), and mouse_mesh().
static int verg_radial (const void * va, const void * vb) [static]
Definition at line 2634 of file editmesh_select.c.
References BM_edge_face_count().
Referenced by loop_find_regions().
static void walker_deselect_nth (BMEditMesh * em, int nth, int offset, BMHeader * h_act) [static]
Definition at line 2025 of file editmesh_select.c.
References BLI_assert, BMEditMesh::bm, BM_EDGE, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SELECT, BM_elem_select_set(), BM_FACE, BM_FACES_OF_MESH, BM_ITER_MESH, BM_VERT, BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_pop(), BMO_push(), BMW_begin(), BMW_BREADTH_FIRST, BMW_CONNECTED_VERTEX, BMW_current_depth(), BMW_end(), BMW_FLAG_NOP, BMW_init(), BMW_ISLAND, BMW_NIL_LAY, BMW_SHELL, BMW_step(), EDBM_selectmode_flush_ex(), FALSE, BMHeader::htype, NULL, BMWalker::order, SCE_SELECT_EDGE, SCE_SELECT_FACE, and SCE_SELECT_VERTEX.
Referenced by edbm_deselect_nth().
static void walker_select (BMEditMesh * em, int walkercode, void * start, int select) [static]
Definition at line 896 of file editmesh_select.c.
References BMEditMesh::bm, BM_elem_select_set(), BM_select_history_remove, BMW_begin(), BMW_end(), BMW_FLAG_TEST_HIDDEN, BMW_init(), BMW_MASK_NOP, BMW_NIL_LAY, and BMW_step().
Referenced by edbm_loop_multiselect_exec(), and mouse_mesh_loop().
Variable Documentation
unsigned int bm_solidoffs = 0
Definition at line 126 of file editmesh_select.c.
Referenced by do_lasso_select_mesh__doSelectEdge(), do_mesh_box_select__doSelectEdge(), draw_object_backbufsel(), and edbm_backbuf_check_and_select_edges().
unsigned int bm_vertoffs = 0
Definition at line 126 of file editmesh_select.c.
Referenced by do_lasso_select_paintface(), do_lasso_select_paintvert(), draw_object_backbufsel(), EDBM_backbuf_border_init(), EDBM_backbuf_border_mask_init(), EDBM_backbuf_check(), EDBM_backbuf_circle_init(), paint_facesel_circle_select(), and paint_vertsel_circle_select().
unsigned int bm_wireoffs = 0
Definition at line 126 of file editmesh_select.c.
Referenced by draw_object_backbufsel(), edbm_backbuf_check_and_select_verts(), EDBM_edge_find_nearest(), and EDBM_vert_find_nearest().
EnumPropertyItem prop_similar_types[] [static]
Initial value:
 {
    {SIMVERT_NORMAL, "NORMAL", 0, "Normal", ""},
    {SIMVERT_FACE, "FACE", 0, "Amount of Adjacent Faces", ""},
    {SIMVERT_VGROUP, "VGROUP", 0, "Vertex Groups", ""},
    {SIMEDGE_LENGTH, "LENGTH", 0, "Length", ""},
    {SIMEDGE_DIR, "DIR", 0, "Direction", ""},
    {SIMEDGE_FACE, "FACE", 0, "Amount of Faces Around an Edge", ""},
    {SIMEDGE_FACE_ANGLE, "FACE_ANGLE", 0, "Face Angles", ""},
    {SIMEDGE_CREASE, "CREASE", 0, "Crease", ""},
    {SIMEDGE_SEAM, "SEAM", 0, "Seam", ""},
    {SIMEDGE_SHARP, "SHARP", 0, "Sharpness", ""},
    {SIMFACE_MATERIAL, "MATERIAL", 0, "Material", ""},
    {SIMFACE_IMAGE, "IMAGE", 0, "Image", ""},
    {SIMFACE_AREA, "AREA", 0, "Area", ""},
    {SIMFACE_PERIMETER, "PERIMETER", 0, "Perimeter", ""},
    {SIMFACE_NORMAL, "NORMAL", 0, "Normal", ""},
    {SIMFACE_COPLANAR, "COPLANAR", 0, "Co-planar", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 675 of file editmesh_select.c.
char* selbuf = NULL [static]
Definition at line 129 of file editmesh_select.c.