Blender: cdderivedmesh.c File Reference
cdderivedmesh.c File Reference
blenkernel
#include "GL/glew.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_edgehash.h"
#include "BLI_pbvh.h"
#include "BLI_array.h"
#include "BLI_smallhash.h"
#include "BLI_utildefines.h"
#include "BLI_scanfill.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_global.h"
#include "BKE_mesh.h"
#include "BKE_paint.h"
#include "BKE_utildefines.h"
#include "BKE_tessmesh.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_curve_types.h"
#include "MEM_guardedalloc.h"
#include "GPU_buffers.h"
#include "GPU_draw.h"
#include "GPU_extensions.h"
#include "GPU_material.h"
#include <string.h>
#include <limits.h>
#include <math.h>
Classes
struct CDDerivedMesh
Defines
#define PASSVERT(index)
Functions
static int cdDM_getNumVerts (DerivedMesh *dm)
static int cdDM_getNumEdges (DerivedMesh *dm)
static int cdDM_getNumTessFaces (DerivedMesh *dm)
static int cdDM_getNumLoops (DerivedMesh *dm)
static int cdDM_getNumPolys (DerivedMesh *dm)
static void cdDM_getVert (DerivedMesh *dm, int index, MVert *vert_r)
static void cdDM_getEdge (DerivedMesh *dm, int index, MEdge *edge_r)
static void cdDM_getTessFace (DerivedMesh *dm, int index, MFace *face_r)
static void cdDM_copyVertArray (DerivedMesh *dm, MVert *vert_r)
static void cdDM_copyEdgeArray (DerivedMesh *dm, MEdge *edge_r)
static void cdDM_copyTessFaceArray (DerivedMesh *dm, MFace *face_r)
static void cdDM_copyLoopArray (DerivedMesh *dm, MLoop *loop_r)
static void cdDM_copyPolyArray (DerivedMesh *dm, MPoly *poly_r)
static void cdDM_getMinMax (DerivedMesh *dm, float min_r[3], float max_r[3])
static void cdDM_getVertCo (DerivedMesh *dm, int index, float co_r[3])
static void cdDM_getVertCos (DerivedMesh *dm, float(*cos_r)[3])
static void cdDM_getVertNo (DerivedMesh *dm, int index, float no_r[3])
static const MeshElemMap * cdDM_getPolyMap (Object *ob, DerivedMesh *dm)
static int can_pbvh_draw (Object *ob, DerivedMesh *dm)
static struct PBVH * cdDM_getPBVH (Object *ob, DerivedMesh *dm)
static void cdDM_update_normals_from_pbvh (DerivedMesh *dm)
static void cdDM_drawVerts (DerivedMesh *dm)
static void cdDM_drawUVEdges (DerivedMesh *dm)
static void cdDM_drawEdges (DerivedMesh *dm, int drawLooseEdges, int drawAllEdges)
static void cdDM_drawLooseEdges (DerivedMesh *dm)
static void cdDM_drawFacesSolid (DerivedMesh *dm, float(*partial_redraw_planes)[4], int UNUSED(fast), DMSetMaterial setMaterial)
static void cdDM_drawFacesTex_common (DerivedMesh *dm, DMSetDrawOptionsTex drawParams, DMSetDrawOptions drawParamsMapped, DMCompareDrawOptions compareDrawOptions, void *userData)
static void cdDM_drawFacesTex (DerivedMesh *dm, DMSetDrawOptionsTex setDrawOptions, DMCompareDrawOptions compareDrawOptions, void *userData)
static void cdDM_drawMappedFaces (DerivedMesh *dm, DMSetDrawOptions setDrawOptions, DMSetMaterial setMaterial, DMCompareDrawOptions compareDrawOptions, void *userData, DMDrawFlag flag)
static void cdDM_drawMappedFacesTex (DerivedMesh *dm, DMSetDrawOptions setDrawOptions, DMCompareDrawOptions compareDrawOptions, void *userData)
static void cddm_draw_attrib_vertex (DMVertexAttribs *attribs, MVert *mvert, int a, int index, int vert, int smoothnormal)
static void cdDM_drawMappedFacesGLSL (DerivedMesh *dm, DMSetMaterial setMaterial, DMSetDrawOptions setDrawOptions, void *userData)
static void cdDM_drawFacesGLSL (DerivedMesh *dm, DMSetMaterial setMaterial)
static void cdDM_drawMappedFacesMat (DerivedMesh *dm, void(*setMaterial)(void *userData, int, void *attribs), int(*setFace)(void *userData, int index), void *userData)
static void cdDM_drawMappedEdges (DerivedMesh *dm, DMSetDrawOptions setDrawOptions, void *userData)
static void cdDM_foreachMappedVert (DerivedMesh *dm, void(*func)(void *userData, int index, const float co[3], const float no_f[3], const short no_s[3]), void *userData)
static void cdDM_foreachMappedEdge (DerivedMesh *dm, void(*func)(void *userData, int index, const float v0co[3], const float v1co[3]), void *userData)
static void cdDM_foreachMappedFaceCenter (DerivedMesh *dm, void(*func)(void *userData, int index, const float cent[3], const float no[3]), void *userData)
void CDDM_recalc_tessellation_ex (DerivedMesh *dm, const int do_face_nor_cpy)
void CDDM_recalc_tessellation (DerivedMesh *dm)
static void cdDM_free_internal (CDDerivedMesh *cddm)
static void cdDM_release (DerivedMesh *dm)
int CDDM_Check (DerivedMesh *dm)
static CDDerivedMesh * cdDM_create (const char *desc)
DerivedMesh * CDDM_new (int numVerts, int numEdges, int numTessFaces, int numLoops, int numPolys)
DerivedMesh * CDDM_from_mesh (Mesh *mesh, Object *UNUSED(ob))
DerivedMesh * CDDM_from_curve (Object *ob)
DerivedMesh * CDDM_from_curve_customDB (Object *ob, ListBase *dispbase)
static void loops_to_customdata_corners (BMesh *bm, CustomData *facedata, int cdindex, BMLoop *l3[3], int numCol, int numTex)
DerivedMesh * CDDM_from_BMEditMesh (BMEditMesh *em, Mesh *UNUSED(me), int use_mdisps, int use_tessface)
static DerivedMesh * cddm_copy_ex (DerivedMesh *source, int faces_from_tessfaces)
DerivedMesh * CDDM_copy (DerivedMesh *source)
DerivedMesh * CDDM_copy_from_tessface (DerivedMesh *source)
DerivedMesh * CDDM_from_template (DerivedMesh *source, int numVerts, int numEdges, int numTessFaces, int numLoops, int numPolys)
void CDDM_apply_vert_coords (DerivedMesh *dm, float(*vertCoords)[3])
void CDDM_apply_vert_normals (DerivedMesh *dm, short(*vertNormals)[3])
void CDDM_calc_normals_mapping_ex (DerivedMesh *dm, const short only_face_normals)
void CDDM_calc_normals_mapping (DerivedMesh *dm)
void CDDM_calc_normals (DerivedMesh *dm)
void CDDM_calc_normals_tessface (DerivedMesh *dm)
DerivedMesh * CDDM_merge_verts (DerivedMesh *dm, const int *vtargetmap)
void CDDM_calc_edges_tessface (DerivedMesh *dm)
void CDDM_calc_edges (DerivedMesh *dm)
void CDDM_lower_num_verts (DerivedMesh *dm, int numVerts)
void CDDM_lower_num_edges (DerivedMesh *dm, int numEdges)
void CDDM_lower_num_tessfaces (DerivedMesh *dm, int numTessFaces)
void CDDM_lower_num_polys (DerivedMesh *dm, int numPolys)
MVert * CDDM_get_vert (DerivedMesh *dm, int index)
MEdge * CDDM_get_edge (DerivedMesh *dm, int index)
MFace * CDDM_get_tessface (DerivedMesh *dm, int index)
MLoop * CDDM_get_loop (DerivedMesh *dm, int index)
MPoly * CDDM_get_poly (DerivedMesh *dm, int index)
MVert * CDDM_get_verts (DerivedMesh *dm)
MEdge * CDDM_get_edges (DerivedMesh *dm)
MFace * CDDM_get_tessfaces (DerivedMesh *dm)
MLoop * CDDM_get_loops (DerivedMesh *dm)
MPoly * CDDM_get_polys (DerivedMesh *dm)
void CDDM_tessfaces_to_faces (DerivedMesh *dm)
void CDDM_set_mvert (DerivedMesh *dm, MVert *mvert)
void CDDM_set_medge (DerivedMesh *dm, MEdge *medge)
void CDDM_set_mface (DerivedMesh *dm, MFace *mface)
void CDDM_set_mloop (DerivedMesh *dm, MLoop *mloop)
void CDDM_set_mpoly (DerivedMesh *dm, MPoly *mpoly)
Detailed Description
Definition in file cdderivedmesh.c.
Define Documentation
#define PASSVERT (index)
Value:
{                       \
    if (shademodel == GL_SMOOTH) {              \
        short *no = mvert[index].no;            \
        glNormal3sv(no);                        \
    }                                           \
    glVertex3fv(mvert[index].co);   \
}
Referenced by cdDM_drawFacesSolid().
Function Documentation
static int can_pbvh_draw (Object * ob, DerivedMesh * dm) [static]
Definition at line 226 of file cdderivedmesh.c.
References Object::data, PBVH::deformed, SculptSession::kb, SculptSession::modifiers_active, CDDerivedMesh::mvert, Mesh::mvert, OB_SHAPE_LOCK, Object::sculpt, and Object::shapeflag.
Referenced by cdDM_getPBVH().
void CDDM_apply_vert_coords (DerivedMesh * dm, float(*) vertCoords[3])
Definition at line 2051 of file cdderivedmesh.c.
References CD_MVERT, MVert::co, copy_v3_v3(), CustomData_duplicate_referenced_layer(), i, CDDerivedMesh::mvert, DerivedMesh::numVertData, and DerivedMesh::vertData.
Referenced by create_orco_dm(), curve_calc_modifiers_post(), deformVerts(), do_hair_dynamics(), editbmesh_calc_modifiers(), get_cddm(), get_dm(), mesh_calc_modifiers(), mesh_create_derived(), multires_apply_smat(), and multiresModifier_reshapeFromDeformMod().
void CDDM_apply_vert_normals (DerivedMesh * dm, short(*) vertNormals[3])
Definition at line 2065 of file cdderivedmesh.c.
References CD_MVERT, copy_v3_v3_short(), CustomData_duplicate_referenced_layer(), i, CDDerivedMesh::mvert, MVert::no, DerivedMesh::numVertData, and DerivedMesh::vertData.
void CDDM_calc_edges (DerivedMesh * dm)
Definition at line 2417 of file cdderivedmesh.c.
References BLI_edgehash_free(), BLI_edgehash_haskey(), BLI_edgehash_insert(), BLI_edgehash_lookup(), BLI_edgehash_new(), BLI_edgehash_size(), BLI_edgehashIterator_free(), BLI_edgehashIterator_getKey(), BLI_edgehashIterator_getValue(), BLI_edgehashIterator_isDone(), BLI_edgehashIterator_new(), BLI_edgehashIterator_setValue(), BLI_edgehashIterator_step(), CD_CALLOC, CD_MEDGE, CD_ORIGINDEX, CustomData_add_layer(), CustomData_free(), CustomData_get_layer(), CDDerivedMesh::dm, DM_get_edge_data_layer(), MLoop::e, DerivedMesh::edgeData, GET_INT_FROM_POINTER, i, MPoly::loopstart, ME_EDGEDRAW, ME_EDGERENDER, ME_POLY_LOOP_NEXT, CDDerivedMesh::medge, CDDerivedMesh::mloop, CDDerivedMesh::mpoly, NULL, DerivedMesh::numEdgeData, DerivedMesh::numPolyData, ORIGINDEX_NONE, SET_INT_IN_POINTER, MPoly::totloop, MLoop::v, MEdge::v1, and MEdge::v2.
Referenced by CDDM_from_curve_customDB().
void CDDM_calc_edges_tessface (DerivedMesh * dm)
Definition at line 2359 of file cdderivedmesh.c.
References BLI_edgehash_free(), BLI_edgehash_haskey(), BLI_edgehash_insert(), BLI_edgehash_new(), BLI_edgehash_size(), BLI_edgehashIterator_free(), BLI_edgehashIterator_getKey(), BLI_edgehashIterator_isDone(), BLI_edgehashIterator_new(), BLI_edgehashIterator_step(), CD_CALLOC, CD_MEDGE, CD_ORIGINDEX, CustomData_add_layer(), CustomData_free(), CustomData_get_layer(), DerivedMesh::edgeData, i, ME_EDGEDRAW, ME_EDGERENDER, CDDerivedMesh::medge, CDDerivedMesh::mface, NULL, DerivedMesh::numEdgeData, DerivedMesh::numTessFaceData, ORIGINDEX_NONE, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by applyModifier(), CDDM_tessfaces_to_faces(), ConvertCSGDescriptorsToDerivedMesh(), cutEdges(), and explodeMesh().
void CDDM_calc_normals (DerivedMesh * dm)
Definition at line 2133 of file cdderivedmesh.c.
References CD_CALLOC, CD_MVERT, CD_NORMAL, CDDM_get_loops(), CDDM_get_polys(), CustomData_add_layer(), CustomData_duplicate_referenced_layer(), CustomData_get_layer(), mesh_calc_normals(), CDDerivedMesh::mvert, NULL, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numVertData, DerivedMesh::polyData, and DerivedMesh::vertData.
Referenced by applyModifier(), arrayModifier_doArray(), ConvertCSGDescriptorsToDerivedMesh(), create_orco_dm(), deformVerts(), dynamicPaint_Modifier_apply(), editbmesh_calc_modifiers(), explodeMesh(), get_cddm(), mesh_calc_modifiers(), and mesh_create_derived().
void CDDM_calc_normals_mapping (DerivedMesh * dm)
Definition at line 2124 of file cdderivedmesh.c.
References CD_MVERT, CDDM_calc_normals_mapping_ex(), CustomData_is_referenced_layer(), and DerivedMesh::vertData.
Referenced by cdDM_create(), and curve_calc_modifiers_post().
void CDDM_calc_normals_mapping_ex (DerivedMesh * dm, const short only_face_normals)
Definition at line 2079 of file cdderivedmesh.c.
References BLI_assert, CD_ASSIGN, CD_MVERT, CD_NORMAL, CD_POLYINDEX, CDDM_get_loops(), CDDM_get_polys(), CDDM_recalc_tessellation_ex(), CustomData_add_layer(), CustomData_duplicate_referenced_layer(), CustomData_free_layers(), CustomData_get_layer(), CustomData_has_layer(), DerivedMesh::faceData, FALSE, MEM_mallocN(), mesh_calc_normals_mapping_ex(), CDDerivedMesh::mface, CDDerivedMesh::mvert, NULL, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, DerivedMesh::numVertData, and DerivedMesh::vertData.
Referenced by CDDM_calc_normals_mapping(), and mesh_calc_modifiers().
void CDDM_calc_normals_tessface (DerivedMesh * dm)
Definition at line 2153 of file cdderivedmesh.c.
References CD_CALLOC, CD_MVERT, CD_NORMAL, CustomData_add_layer(), CustomData_duplicate_referenced_layer(), CustomData_get_layer(), DerivedMesh::faceData, mesh_calc_normals_tessface(), CDDerivedMesh::mface, CDDerivedMesh::mvert, NULL, DerivedMesh::numTessFaceData, DerivedMesh::numVertData, and DerivedMesh::vertData.
int CDDM_Check (DerivedMesh * dm)
Definition at line 1557 of file cdderivedmesh.c.
References cdDM_getMinMax(), and DerivedMesh::getMinMax.
DerivedMesh* CDDM_copy (DerivedMesh * source) [read]
Definition at line 1999 of file cdderivedmesh.c.
References cddm_copy_ex().
Referenced by applyModifier(), canvas_copyDerivedMesh(), connect_hair(), curve_calc_modifiers_post(), deformVerts(), do_hair_dynamics(), dynamicPaint_brushMeshCalculateVelocity(), dynamicPaint_Modifier_apply(), dynamicPaint_paintMesh(), editbmesh_calc_modifiers(), get_cddm(), get_multires_dm(), mesh_calc_modifiers(), multires_modifier_update_mdisps(), multiresbake_create_loresdm(), multiresModifier_reshapeFromDeformMod(), and psys_render_set().
static DerivedMesh* cddm_copy_ex (DerivedMesh * source, int faces_from_tessfaces) [static]
Definition at line 1954 of file cdderivedmesh.c.
References CD_ASSIGN, CD_MEDGE, CD_MFACE, CD_MLOOP, CD_MPOLY, CD_MVERT, CD_ORIGINDEX, cdDM_create(), CDDM_tessfaces_to_faces(), CustomData_add_layer(), CustomData_copy_data(), CustomData_get_layer(), DerivedMesh::deformedOnly, DerivedMesh::dirty, CDDerivedMesh::dm, DM_DupPolys(), DM_from_template(), DM_TYPE_CDDM, DerivedMesh::dupEdgeArray, DerivedMesh::dupTessFaceArray, DerivedMesh::dupVertArray, DerivedMesh::edgeData, DerivedMesh::faceData, DerivedMesh::getEdgeDataArray, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVertDataArray, DerivedMesh::loopData, CDDerivedMesh::medge, CDDerivedMesh::mface, CDDerivedMesh::mloop, CDDerivedMesh::mpoly, CDDerivedMesh::mvert, DerivedMesh::numEdgeData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, DerivedMesh::numVertData, DerivedMesh::polyData, and DerivedMesh::vertData.
Referenced by CDDM_copy(), and CDDM_copy_from_tessface().
DerivedMesh* CDDM_copy_from_tessface (DerivedMesh * source) [read]
Definition at line 2004 of file cdderivedmesh.c.
References cddm_copy_ex().
static void cdDM_copyEdgeArray (DerivedMesh * dm, MEdge * edge_r) [static]
Definition at line 149 of file cdderivedmesh.c.
References CDDerivedMesh::medge, and DerivedMesh::numEdgeData.
Referenced by cdDM_create().
static void cdDM_copyLoopArray (DerivedMesh * dm, MLoop * loop_r) [static]
Definition at line 161 of file cdderivedmesh.c.
References CDDerivedMesh::mloop, and DerivedMesh::numLoopData.
Referenced by cdDM_create().
static void cdDM_copyPolyArray (DerivedMesh * dm, MPoly * poly_r) [static]
Definition at line 167 of file cdderivedmesh.c.
References CDDerivedMesh::mpoly, and DerivedMesh::numPolyData.
Referenced by cdDM_create().
static void cdDM_copyTessFaceArray (DerivedMesh * dm, MFace * face_r) [static]
Definition at line 155 of file cdderivedmesh.c.
References CDDerivedMesh::mface, and DerivedMesh::numTessFaceData.
Referenced by cdDM_create().
static void cdDM_copyVertArray (DerivedMesh * dm, MVert * vert_r) [static]
Definition at line 143 of file cdderivedmesh.c.
References CDDerivedMesh::mvert, and DerivedMesh::numVertData.
Referenced by cdDM_create().
static CDDerivedMesh* cdDM_create (const char * desc) [static]
Definition at line 1563 of file cdderivedmesh.c.
References DerivedMesh::calcNormals, CDDM_calc_normals_mapping(), cdDM_copyEdgeArray(), cdDM_copyLoopArray(), cdDM_copyPolyArray(), cdDM_copyTessFaceArray(), cdDM_copyVertArray(), cdDM_drawEdges(), cdDM_drawFacesGLSL(), cdDM_drawFacesSolid(), cdDM_drawFacesTex(), cdDM_drawLooseEdges(), cdDM_drawMappedEdges(), cdDM_drawMappedFaces(), cdDM_drawMappedFacesGLSL(), cdDM_drawMappedFacesMat(), cdDM_drawMappedFacesTex(), cdDM_drawUVEdges(), cdDM_drawVerts(), cdDM_foreachMappedEdge(), cdDM_foreachMappedFaceCenter(), cdDM_foreachMappedVert(), cdDM_getEdge(), cdDM_getMinMax(), cdDM_getNumEdges(), cdDM_getNumLoops(), cdDM_getNumPolys(), cdDM_getNumTessFaces(), cdDM_getNumVerts(), cdDM_getPBVH(), cdDM_getPolyMap(), cdDM_getTessFace(), cdDM_getVert(), cdDM_getVertCo(), cdDM_getVertCos(), cdDM_getVertNo(), CDDM_recalc_tessellation(), cdDM_release(), DerivedMesh::copyEdgeArray, DerivedMesh::copyLoopArray, DerivedMesh::copyPolyArray, DerivedMesh::copyTessFaceArray, DerivedMesh::copyVertArray, CDDerivedMesh::dm, DM_get_edge_data(), DM_get_edge_data_layer(), DM_get_tessface_data(), DM_get_tessface_data_layer(), DM_get_vert_data(), DM_get_vert_data_layer(), DerivedMesh::drawEdges, DerivedMesh::drawFacesGLSL, DerivedMesh::drawFacesSolid, DerivedMesh::drawFacesTex, DerivedMesh::drawLooseEdges, DerivedMesh::drawMappedEdges, DerivedMesh::drawMappedFaces, DerivedMesh::drawMappedFacesGLSL, DerivedMesh::drawMappedFacesMat, DerivedMesh::drawMappedFacesTex, DerivedMesh::drawUVEdges, DerivedMesh::drawVerts, DerivedMesh::foreachMappedEdge, DerivedMesh::foreachMappedFaceCenter, DerivedMesh::foreachMappedVert, DerivedMesh::getEdge, DerivedMesh::getEdgeData, DerivedMesh::getEdgeDataArray, DerivedMesh::getMinMax, DerivedMesh::getNumEdges, DerivedMesh::getNumLoops, DerivedMesh::getNumPolys, DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, DerivedMesh::getPBVH, DerivedMesh::getPolyMap, DerivedMesh::getTessFace, DerivedMesh::getTessFaceData, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVert, DerivedMesh::getVertCo, DerivedMesh::getVertCos, DerivedMesh::getVertData, DerivedMesh::getVertDataArray, DerivedMesh::getVertNo, MEM_callocN(), DerivedMesh::recalcTessellation, and DerivedMesh::release.
Referenced by cddm_copy_ex(), CDDM_from_mesh(), CDDM_from_template(), and CDDM_new().
static void cddm_draw_attrib_vertex (DMVertexAttribs * attribs, MVert * mvert, int a, int index, int vert, int smoothnormal) [static]
Definition at line 981 of file cdderivedmesh.c.
References MCol::a, DMVertexAttribs::array, MCol::b, co, MCol::g, DMVertexAttribs::glIndex, DMVertexAttribs::glTexco, DMVertexAttribs::mcol, DMVertexAttribs::orco, MCol::r, DMVertexAttribs::tang, DMVertexAttribs::tface, DMVertexAttribs::totmcol, DMVertexAttribs::totorco, DMVertexAttribs::tottang, DMVertexAttribs::tottface, and MTFace::uv.
Referenced by cdDM_drawMappedFacesGLSL(), and cdDM_drawMappedFacesMat().
static void cdDM_drawEdges (DerivedMesh * dm, int drawLooseEdges, int drawAllEdges) [static]
Definition at line 404 of file cdderivedmesh.c.
References MVert::co, DEBUG_VBO, DerivedMesh::drawObject, GPUDrawObject::edges, FALSE, MEdge::flag, GPU_buffer_draw_elements(), GPU_buffer_legacy(), GPU_buffer_unbind(), GPU_edge_setup(), i, ME_EDGEDRAW, ME_LOOSEEDGE, CDDerivedMesh::medge, CDDerivedMesh::mvert, DerivedMesh::numEdgeData, TRUE, MEdge::v1, and MEdge::v2.
Referenced by cdDM_create().
static void cdDM_drawFacesGLSL (DerivedMesh * dm, DMSetMaterial setMaterial) [static]
Definition at line 1316 of file cdderivedmesh.c.
References DerivedMesh::drawMappedFacesGLSL, and NULL.
Referenced by cdDM_create().
static void cdDM_drawFacesSolid (DerivedMesh * dm, float(*) partial_redraw_planes[4], int UNUSEDfast, DMSetMaterial setMaterial) [static]
Definition at line 504 of file cdderivedmesh.c.
References BLI_pbvh_draw(), CD_NORMAL, MVert::co, CustomData_get_layer(), DEBUG_VBO, DerivedMesh::drawObject, DerivedMesh::faceData, MFace::flag, DerivedMesh::getTessFaceDataArray, GPU_buffer_legacy(), GPU_buffer_unbind(), GPU_normal_setup(), GPU_vertex_setup(), MFace::mat_nr, GPUBufferMaterial::mat_nr, GPUDrawObject::materials, ME_SMOOTH, CDDerivedMesh::mface, CDDerivedMesh::mvert, normal_quad_v3(), normal_tri_v3(), NULL, DerivedMesh::numTessFaceData, PASSVERT, CDDerivedMesh::pbvh, CDDerivedMesh::pbvh_draw, GPUBufferMaterial::start, GPUDrawObject::totmaterial, GPUBufferMaterial::totpoint, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by cdDM_create().
static void cdDM_drawFacesTex (DerivedMesh * dm, DMSetDrawOptionsTex setDrawOptions, DMCompareDrawOptions compareDrawOptions, void * userData) [static]
Definition at line 796 of file cdderivedmesh.c.
References cdDM_drawFacesTex_common(), and NULL.
Referenced by cdDM_create().
static void cdDM_drawFacesTex_common (DerivedMesh * dm, DMSetDrawOptionsTex drawParams, DMSetDrawOptions drawParamsMapped, DMCompareDrawOptions compareDrawOptions, void * userData) [static]
Definition at line 601 of file cdderivedmesh.c.
References MCol::b, CD_MCOL, CD_MFACE, CD_MTFACE, CD_NORMAL, CD_ORIGINDEX, CD_PREVIEW_MCOL, CD_TEXTURE_MCOL, cdDM_update_normals_from_pbvh(), MVert::co, GPUDrawObject::colType, compareDrawOptions(), DEBUG_VBO, DM_DRAW_OPTION_NO_MCOL, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, DM_get_tessface_data_layer(), DerivedMesh::drawObject, MFace::flag, MCol::g, DerivedMesh::getNumTessFaces, DerivedMesh::getTessFaceDataArray, GPU_buffer_legacy(), GPU_buffer_unbind(), GPU_color3_upload(), GPU_color_setup(), GPU_color_switch(), GPU_normal_setup(), GPU_uv_setup(), GPU_vertex_setup(), i, MFace::mat_nr, ME_SMOOTH, MEM_freeN(), MEM_mallocN(), CDDerivedMesh::mvert, MVert::no, normal_quad_v3(), normal_tri_v3(), NULL, DerivedMesh::numTessFaceData, ORIGINDEX_NONE, MCol::r, GPUDrawObject::tot_triangle_point, GPUDrawObject::triangle_to_mface, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by cdDM_drawFacesTex(), and cdDM_drawMappedFacesTex().
static void cdDM_drawLooseEdges (DerivedMesh * dm) [static]
Definition at line 456 of file cdderivedmesh.c.
References MVert::co, DEBUG_VBO, DerivedMesh::drawObject, GPUDrawObject::edges, MEdge::flag, GPU_buffer_draw_elements(), GPU_buffer_legacy(), GPU_buffer_unbind(), GPU_edge_setup(), i, ME_LOOSEEDGE, CDDerivedMesh::medge, CDDerivedMesh::mvert, DerivedMesh::numEdgeData, MEdge::v1, and MEdge::v2.
Referenced by cdDM_create().
static void cdDM_drawMappedEdges (DerivedMesh * dm, DMSetDrawOptions setDrawOptions, void * userData) [static]
Definition at line 1400 of file cdderivedmesh.c.
References CD_ORIGINDEX, MVert::co, DM_DRAW_OPTION_SKIP, DM_get_edge_data_layer(), i, CDDerivedMesh::medge, CDDerivedMesh::mvert, DerivedMesh::numEdgeData, ORIGINDEX_NONE, MEdge::v1, and MEdge::v2.
Referenced by cdDM_create().
static void cdDM_drawMappedFaces (DerivedMesh * dm, DMSetDrawOptions setDrawOptions, DMSetMaterial setMaterial, DMCompareDrawOptions compareDrawOptions, void * userData, DMDrawFlag flag) [static]
Definition at line 804 of file cdderivedmesh.c.
References CD_ID_MCOL, CD_MCOL, CD_NORMAL, CD_ORIGINDEX, CD_PREVIEW_MCOL, cdDM_update_normals_from_pbvh(), MVert::co, compareDrawOptions(), DEBUG_VBO, DM_DRAW_ALWAYS_SMOOTH, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, DM_DRAW_USE_COLORS, DM_get_tessface_data_layer(), DerivedMesh::drawObject, MFace::flag, G, G_BACKBUFSEL, GPU_buffer_legacy(), GPU_buffer_unbind(), GPU_color_setup(), GPU_normal_setup(), GPU_vertex_setup(), i, MFace::mat_nr, ME_SMOOTH, CDDerivedMesh::mface, CDDerivedMesh::mvert, MVert::no, normal_quad_v3(), normal_tri_v3(), NULL, DerivedMesh::numTessFaceData, ORIGINDEX_NONE, GPUDrawObject::tot_triangle_point, GPUDrawObject::triangle_to_mface, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by cdDM_create().
static void cdDM_drawMappedFacesGLSL (DerivedMesh * dm, DMSetMaterial setMaterial, DMSetDrawOptions setDrawOptions, void * userData) [static]
Definition at line 1025 of file cdderivedmesh.c.
References MCol::a, DMVertexAttribs::array, MCol::b, CD_NORMAL, CD_ORIGINDEX, cddm_draw_attrib_vertex(), cdDM_update_normals_from_pbvh(), MVert::co, copy_v2_v2(), copy_v3_v3(), copy_v4_v4(), copy_v4_v4_char(), DEBUG_VBO, DM_DRAW_OPTION_SKIP, DM_vertex_attributes_from_gpu(), DerivedMesh::drawObject, elementsize(), MFace::flag, MCol::g, DerivedMesh::getTessFaceDataArray, DMVertexAttribs::glIndex, GPU_attrib_element_size(), GPU_buffer_alloc(), GPU_buffer_free(), GPU_buffer_legacy(), GPU_buffer_lock_stream(), GPU_buffer_unbind(), GPU_buffer_unlock(), GPU_interleaved_attrib_setup(), GPU_MAX_ATTRIB, GPU_normal_setup(), GPU_vertex_setup(), i, GPUAttrib::index, GPUDrawObject::legacy, MFace::mat_nr, DMVertexAttribs::mcol, ME_SMOOTH, CDDerivedMesh::mface, CDDerivedMesh::mvert, normal_quad_v3(), normal_tri_v3(), NULL, DerivedMesh::numTessFaceData, DMVertexAttribs::orco, ORIGINDEX_NONE, MCol::r, GPUAttrib::size, DMVertexAttribs::tang, DMVertexAttribs::tface, GPUDrawObject::tot_triangle_point, DMVertexAttribs::totmcol, DMVertexAttribs::totorco, DMVertexAttribs::tottang, DMVertexAttribs::tottface, GPUDrawObject::triangle_to_mface, GPUAttrib::type, MTFace::uv, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by cdDM_create().
static void cdDM_drawMappedFacesMat (DerivedMesh * dm, void(*)(void *userData, int, void *attribs) setMaterial, int(*)(void *userData, int index) setFace, void * userData) [static]
Definition at line 1321 of file cdderivedmesh.c.
References CD_NORMAL, CD_ORIGINDEX, cddm_draw_attrib_vertex(), cdDM_update_normals_from_pbvh(), MVert::co, DM_vertex_attributes_from_gpu(), MFace::flag, DerivedMesh::getTessFaceDataArray, MFace::mat_nr, ME_SMOOTH, CDDerivedMesh::mface, CDDerivedMesh::mvert, normal_quad_v3(), normal_tri_v3(), DerivedMesh::numTessFaceData, ORIGINDEX_NONE, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by cdDM_create().
static void cdDM_drawMappedFacesTex (DerivedMesh * dm, DMSetDrawOptions setDrawOptions, DMCompareDrawOptions compareDrawOptions, void * userData) [static]
Definition at line 973 of file cdderivedmesh.c.
References cdDM_drawFacesTex_common(), and NULL.
Referenced by cdDM_create().
static void cdDM_drawUVEdges (DerivedMesh * dm) [static]
Definition at line 333 of file cdderivedmesh.c.
References CD_MTFACE, DM_get_tessface_data_layer(), MFace::flag, GPU_buffer_legacy(), GPU_buffer_unbind(), GPU_uvedge_setup(), i, ME_HIDE, CDDerivedMesh::mface, DerivedMesh::numTessFaceData, MTFace::uv, and MFace::v4.
Referenced by cdDM_create().
static void cdDM_drawVerts (DerivedMesh * dm) [static]
Definition at line 309 of file cdderivedmesh.c.
References MVert::co, DerivedMesh::drawObject, GPU_buffer_legacy(), GPU_buffer_unbind(), GPU_vertex_setup(), i, CDDerivedMesh::mvert, DerivedMesh::numVertData, GPUDrawObject::tot_loose_point, and GPUDrawObject::tot_triangle_point.
Referenced by cdDM_create().
static void cdDM_foreachMappedEdge (DerivedMesh * dm, void(*)(void *userData, int index, const float v0co[3], const float v1co[3]) func, void * userData) [static]
Definition at line 1443 of file cdderivedmesh.c.
References CD_ORIGINDEX, MVert::co, DM_get_edge_data_layer(), i, CDDerivedMesh::medge, CDDerivedMesh::mvert, DerivedMesh::numEdgeData, ORIGINDEX_NONE, MEdge::v1, and MEdge::v2.
Referenced by cdDM_create().
static void cdDM_foreachMappedFaceCenter (DerivedMesh * dm, void(*)(void *userData, int index, const float cent[3], const float no[3]) func, void * userData) [static]
Definition at line 1464 of file cdderivedmesh.c.
References add_v3_v3v3(), CD_ORIGINDEX, MVert::co, co, CustomData_get_layer(), i, MPoly::loopstart, CDDerivedMesh::mloop, CDDerivedMesh::mpoly, mul_v3_fl(), CDDerivedMesh::mvert, normal_quad_v3(), normal_tri_v3(), DerivedMesh::numPolyData, ORIGINDEX_NONE, DerivedMesh::polyData, MPoly::totloop, and MLoop::v.
Referenced by cdDM_create().
static void cdDM_foreachMappedVert (DerivedMesh * dm, void(*)(void *userData, int index, const float co[3], const float no_f[3], const short no_s[3]) func, void * userData) [static]
Definition at line 1424 of file cdderivedmesh.c.
References CD_ORIGINDEX, CDDM_get_verts(), MVert::co, DM_get_vert_data_layer(), i, MVert::no, NULL, DerivedMesh::numVertData, and ORIGINDEX_NONE.
Referenced by cdDM_create().
static void cdDM_free_internal (CDDerivedMesh * cddm) [static]
Definition at line 1541 of file cdderivedmesh.c.
References MEM_freeN(), CDDerivedMesh::pmap, and CDDerivedMesh::pmap_mem.
Referenced by cdDM_release().
DerivedMesh* CDDM_from_BMEditMesh (BMEditMesh * em, Mesh * UNUSEDme, int use_mdisps, int use_tessface)
Definition at line 1794 of file cdderivedmesh.c.
References BMEditMesh::bm, BM_EDGE, BM_edge_flag_to_mflag(), BM_EDGES_OF_MESH, BM_elem_float_data_get(), BM_elem_index_get, BM_elem_index_set, BM_FACE, BM_face_flag_to_mflag(), BM_FACES_OF_MESH, BM_ITER_ELEM, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BM_mesh_elem_index_ensure(), BM_VERT, BM_vert_flag_to_mflag(), BM_VERTS_OF_MESH, MEdge::bweight, MVert::bweight, CD_BWEIGHT, CD_CALLOC, CD_CREASE, CD_MASK_DERIVEDMESH, CD_MASK_MDISPS, CD_MASK_SHAPEKEY, CD_MLOOPCOL, CD_MTEXPOLY, CD_ORIGINDEX, CD_POLYINDEX, CDDM_new(), BMVert::co, MVert::co, copy_v3_v3(), MEdge::crease, CustomData_bmesh_get(), CustomData_from_bmesh_block(), CustomData_from_bmeshpoly(), CustomData_get_layer(), CustomData_has_layer(), CustomData_merge(), CustomData_number_of_layers(), BMHeader::data, DerivedMesh::deformedOnly, BMLoop::e, MLoop::e, BMesh::edata, DerivedMesh::edgeData, BMesh::elem_index_dirty, BMLoop::f, DerivedMesh::faceData, MPoly::flag, MFace::flag, MEdge::flag, MVert::flag, DerivedMesh::getEdgeDataArray, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVertDataArray, BMLoop::head, BMFace::head, BMEdge::head, BMVert::head, i, BMesh::ldata, DerivedMesh::loopData, loops_to_customdata_corners(), MPoly::loopstart, BMEditMesh::looptris, MPoly::mat_nr, BMFace::mat_nr, MFace::mat_nr, CDDerivedMesh::medge, CDDerivedMesh::mface, CDDerivedMesh::mloop, CDDerivedMesh::mpoly, CDDerivedMesh::mvert, BMVert::no, MVert::no, normal_float_to_short_v3(), NULL, DerivedMesh::numEdgeData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, DerivedMesh::numVertData, BMesh::pdata, DerivedMesh::polyData, test_index_face(), BMesh::totedge, BMesh::totface, MPoly::totloop, BMesh::totloop, BMEditMesh::tottri, BMesh::totvert, BMLoop::v, MLoop::v, MFace::v1, BMEdge::v1, MEdge::v1, MFace::v2, BMEdge::v2, MEdge::v2, MFace::v3, MFace::v4, BMesh::vdata, and DerivedMesh::vertData.
DerivedMesh* CDDM_from_curve (Object * ob) [read]
Definition at line 1706 of file cdderivedmesh.c.
References CDDM_from_curve_customDB(), and Object::disp.
Referenced by applyModifier(), and get_dm().
DerivedMesh* CDDM_from_curve_customDB (Object * ob, ListBase * dispbase)
Definition at line 1711 of file cdderivedmesh.c.
References CDDM_calc_edges(), CDDM_new(), DerivedMesh::deformedOnly, CDDerivedMesh::medge, MEM_freeN(), CDDerivedMesh::mloop, CDDerivedMesh::mpoly, CDDerivedMesh::mvert, nurbs_to_mdata_customdb(), and PBVH::totvert.
Referenced by CDDM_from_curve(), create_orco_dm(), and curve_calc_modifiers_post().
DerivedMesh* CDDM_from_mesh (Mesh * mesh, Object * UNUSEDob)
Definition at line 1658 of file cdderivedmesh.c.
References BLI_assert, CD_MASK_MDISPS, CD_MASK_MESH, CD_MASK_POLYINDEX, CD_MEDGE, CD_MFACE, CD_MLOOP, CD_MPOLY, CD_MVERT, CD_ORIGINDEX, CD_POLYINDEX, CD_REFERENCE, cdDM_create(), CustomData_add_layer(), CustomData_get_layer(), CustomData_has_layer(), CustomData_merge(), DerivedMesh::deformedOnly, CDDerivedMesh::dm, DM_init(), DM_TYPE_CDDM, DerivedMesh::edgeData, DerivedMesh::faceData, Mesh::fdata, Mesh::ldata, DerivedMesh::loopData, CDDerivedMesh::medge, CDDerivedMesh::mface, CDDerivedMesh::mloop, CDDerivedMesh::mpoly, CDDerivedMesh::mvert, NULL, DerivedMesh::polyData, Mesh::totedge, Mesh::totface, Mesh::totloop, Mesh::totpoly, Mesh::totvert, and DerivedMesh::vertData.
DerivedMesh* CDDM_from_template (DerivedMesh * source, int numVerts, int numEdges, int numTessFaces, int numLoops, int numPolys) [read]
Definition at line 2011 of file cdderivedmesh.c.
References CD_CALLOC, CD_MEDGE, CD_MFACE, CD_MLOOP, CD_MPOLY, CD_MVERT, CD_ORIGINDEX, CD_POLYINDEX, cdDM_create(), CustomData_add_layer(), CustomData_get_layer(), CDDerivedMesh::dm, DM_from_template(), DM_TYPE_CDDM, DerivedMesh::edgeData, DerivedMesh::faceData, DerivedMesh::getEdgeDataArray, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVertDataArray, DerivedMesh::loopData, CDDerivedMesh::medge, CDDerivedMesh::mface, CDDerivedMesh::mloop, CDDerivedMesh::mpoly, CDDerivedMesh::mvert, NULL, DerivedMesh::polyData, and DerivedMesh::vertData.
Referenced by applyModifier(), CDDM_merge_verts(), cutEdges(), doMirrorOnAxis(), and explodeMesh().
MEdge* CDDM_get_edge (DerivedMesh * dm, int index) [read]
Definition at line 2531 of file cdderivedmesh.c.
Referenced by applyModifier().
MEdge* CDDM_get_edges (DerivedMesh * dm) [read]
Definition at line 2558 of file cdderivedmesh.c.
Referenced by applyModifier(), do_hair_dynamics(), and doMirrorOnAxis().
MLoop* CDDM_get_loop (DerivedMesh * dm, int index) [read]
Definition at line 2541 of file cdderivedmesh.c.
MLoop* CDDM_get_loops (DerivedMesh * dm) [read]
Definition at line 2568 of file cdderivedmesh.c.
Referenced by applyModifier(), CDDM_calc_normals(), CDDM_calc_normals_mapping_ex(), doMirrorOnAxis(), and dynamicPaint_Modifier_apply().
MPoly* CDDM_get_poly (DerivedMesh * dm, int index) [read]
Definition at line 2546 of file cdderivedmesh.c.
MPoly* CDDM_get_polys (DerivedMesh * dm) [read]
Definition at line 2573 of file cdderivedmesh.c.
Referenced by applyModifier(), CDDM_calc_normals(), CDDM_calc_normals_mapping_ex(), doMirrorOnAxis(), and dynamicPaint_Modifier_apply().
MFace* CDDM_get_tessface (DerivedMesh * dm, int index) [read]
Definition at line 2536 of file cdderivedmesh.c.
Referenced by closest_point_on_surface(), connect_hair(), ConvertCSGDescriptorsToDerivedMesh(), cutEdges(), explodeMesh(), get_dface(), and InterpCSGFace().
MFace* CDDM_get_tessfaces (DerivedMesh * dm) [read]
Definition at line 2563 of file cdderivedmesh.c.
MVert* CDDM_get_vert (DerivedMesh * dm, int index) [read]
Definition at line 2526 of file cdderivedmesh.c.
Referenced by applyModifier(), connect_hair(), ConvertCSGDescriptorsToDerivedMesh(), cutEdges(), deformVerts(), explodeMesh(), init_particle_interpolation(), and InterpCSGFace().
MVert* CDDM_get_verts (DerivedMesh * dm) [read]
Definition at line 2553 of file cdderivedmesh.c.
Referenced by applyModifier(), cdDM_foreachMappedVert(), cdDM_getVertCos(), displaceModifier_do(), do_hair_dynamics(), and doMirrorOnAxis().
static void cdDM_getEdge (DerivedMesh * dm, int index, MEdge * edge_r) [static]
Definition at line 131 of file cdderivedmesh.c.
References CDDerivedMesh::medge.
Referenced by cdDM_create().
static void cdDM_getMinMax (DerivedMesh * dm, float min_r[3], float max_r[3]) [static]
Definition at line 173 of file cdderivedmesh.c.
References MVert::co, DO_MINMAX, i, CDDerivedMesh::mvert, DerivedMesh::numVertData, and zero_v3().
Referenced by CDDM_Check(), and cdDM_create().
static int cdDM_getNumEdges (DerivedMesh * dm) [static]
Definition at line 98 of file cdderivedmesh.c.
References DerivedMesh::numEdgeData.
Referenced by cdDM_create().
static int cdDM_getNumLoops (DerivedMesh * dm) [static]
Definition at line 115 of file cdderivedmesh.c.
References DerivedMesh::numLoopData.
Referenced by cdDM_create().
static int cdDM_getNumPolys (DerivedMesh * dm) [static]
Definition at line 120 of file cdderivedmesh.c.
References DerivedMesh::numPolyData.
Referenced by cdDM_create().
static int cdDM_getNumTessFaces (DerivedMesh * dm) [static]
Definition at line 103 of file cdderivedmesh.c.
References DerivedMesh::numPolyData, and DerivedMesh::numTessFaceData.
Referenced by cdDM_create().
static int cdDM_getNumVerts (DerivedMesh * dm) [static]
Definition at line 93 of file cdderivedmesh.c.
References DerivedMesh::numVertData.
Referenced by cdDM_create().
static struct PBVH* cdDM_getPBVH (Object * ob, DerivedMesh * dm) [static, read]
Definition at line 248 of file cdderivedmesh.c.
References BKE_mesh_tessface_ensure(), BLI_pbvh_apply_vertCos(), BLI_pbvh_build_mesh(), BLI_pbvh_new(), can_pbvh_draw(), Object::data, Object::derivedDeform, DerivedMesh::getNumVerts, DerivedMesh::getVertCos, MEM_callocN(), MEM_freeN(), Mesh::mface, SculptSession::modifiers_active, Mesh::mvert, NULL, OB_MESH, CDDerivedMesh::pbvh, SculptSession::pbvh, CDDerivedMesh::pbvh_draw, Object::sculpt, Mesh::totface, Mesh::totvert, PBVH::totvert, and Object::type.
Referenced by cdDM_create().
static const MeshElemMap* cdDM_getPolyMap (Object * ob, DerivedMesh * dm) [static]
Definition at line 211 of file cdderivedmesh.c.
References create_vert_poly_map(), Object::data, Mesh::mloop, Mesh::mpoly, OB_MESH, CDDerivedMesh::pmap, CDDerivedMesh::pmap_mem, Mesh::totloop, Mesh::totpoly, Mesh::totvert, and Object::type.
Referenced by cdDM_create().
static void cdDM_getTessFace (DerivedMesh * dm, int index, MFace * face_r) [static]
Definition at line 137 of file cdderivedmesh.c.
References CDDerivedMesh::mface.
Referenced by cdDM_create().
static void cdDM_getVert (DerivedMesh * dm, int index, MVert * vert_r) [static]
Definition at line 125 of file cdderivedmesh.c.
References CDDerivedMesh::mvert.
Referenced by cdDM_create().
static void cdDM_getVertCo (DerivedMesh * dm, int index, float co_r[3]) [static]
Definition at line 189 of file cdderivedmesh.c.
References MVert::co, copy_v3_v3(), and CDDerivedMesh::mvert.
Referenced by cdDM_create().
static void cdDM_getVertCos (DerivedMesh * dm, float(*) cos_r[3]) [static]
Definition at line 196 of file cdderivedmesh.c.
References CDDM_get_verts(), MVert::co, copy_v3_v3(), i, and DerivedMesh::numVertData.
Referenced by cdDM_create().
static void cdDM_getVertNo (DerivedMesh * dm, int index, float no_r[3]) [static]
Definition at line 205 of file cdderivedmesh.c.
References CDDerivedMesh::mvert, MVert::no, and normal_short_to_float_v3().
Referenced by cdDM_create().
void CDDM_lower_num_edges (DerivedMesh * dm, int numEdges)
Definition at line 2500 of file cdderivedmesh.c.
References CustomData_free_elem(), DerivedMesh::edgeData, and DerivedMesh::numEdgeData.
void CDDM_lower_num_polys (DerivedMesh * dm, int numPolys)
Definition at line 2516 of file cdderivedmesh.c.
References CustomData_free_elem(), DerivedMesh::numPolyData, and DerivedMesh::polyData.
void CDDM_lower_num_tessfaces (DerivedMesh * dm, int numTessFaces)
Definition at line 2508 of file cdderivedmesh.c.
References CustomData_free_elem(), DerivedMesh::faceData, and DerivedMesh::numTessFaceData.
void CDDM_lower_num_verts (DerivedMesh * dm, int numVerts)
Definition at line 2492 of file cdderivedmesh.c.
References CustomData_free_elem(), DerivedMesh::numVertData, and DerivedMesh::vertData.
DerivedMesh* CDDM_merge_verts (DerivedMesh * dm, const int * vtargetmap)
Definition at line 2185 of file cdderivedmesh.c.
References BLI_array_append, BLI_array_append_r, BLI_array_count, BLI_array_declare, BLI_array_free, BLI_edgehash_free(), BLI_edgehash_insert(), BLI_edgehash_lookup_p(), BLI_edgehash_new(), CDDM_from_template(), CustomData_copy_data(), CDDerivedMesh::dm, MLoop::e, DerivedMesh::edgeData, GET_INT_FROM_POINTER, i, LIKELY, DerivedMesh::loopData, MPoly::loopstart, CDDerivedMesh::medge, MEM_callocN(), MEM_freeN(), CDDerivedMesh::mloop, CDDerivedMesh::mpoly, CDDerivedMesh::mvert, DerivedMesh::needsFree, NULL, DerivedMesh::numEdgeData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numVertData, DerivedMesh::polyData, DerivedMesh::release, SET_INT_IN_POINTER, MPoly::totloop, UNLIKELY, MLoop::v, MEdge::v1, MEdge::v2, and DerivedMesh::vertData.
Referenced by doMirrorOnAxis().
DerivedMesh* CDDM_new (int numVerts, int numEdges, int numTessFaces, int numLoops, int numPolys) [read]
Definition at line 1630 of file cdderivedmesh.c.
References CD_CALLOC, CD_MEDGE, CD_MFACE, CD_MLOOP, CD_MPOLY, CD_MVERT, CD_ORIGINDEX, CD_POLYINDEX, cdDM_create(), CustomData_add_layer(), CustomData_get_layer(), CDDerivedMesh::dm, DM_init(), DM_TYPE_CDDM, DerivedMesh::edgeData, DerivedMesh::faceData, DerivedMesh::loopData, CDDerivedMesh::medge, CDDerivedMesh::mface, CDDerivedMesh::mloop, CDDerivedMesh::mpoly, CDDerivedMesh::mvert, NULL, DerivedMesh::polyData, and DerivedMesh::vertData.
Referenced by CDDM_from_BMEditMesh(), CDDM_from_curve_customDB(), ConvertCSGDescriptorsToDerivedMesh(), and do_hair_dynamics().
void CDDM_recalc_tessellation (DerivedMesh * dm)
Definition at line 1536 of file cdderivedmesh.c.
References CDDM_recalc_tessellation_ex(), and TRUE.
Referenced by cdDM_create().
void CDDM_recalc_tessellation_ex (DerivedMesh * dm, const int do_face_nor_cpy)
Definition at line 1515 of file cdderivedmesh.c.
References CD_MFACE, CD_ORIGINDEX, CD_POLYINDEX, CD_REFERENCE, CustomData_add_layer(), CustomData_bmesh_update_active_layers(), CustomData_get_layer(), DerivedMesh::faceData, DerivedMesh::loopData, mesh_recalcTessellation(), CDDerivedMesh::mface, CDDerivedMesh::mvert, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, and DerivedMesh::polyData.
Referenced by CDDM_calc_normals_mapping_ex(), and CDDM_recalc_tessellation().
static void cdDM_release (DerivedMesh * dm) [static]
Definition at line 1547 of file cdderivedmesh.c.
References cdDM_free_internal(), DM_release(), and MEM_freeN().
Referenced by cdDM_create().
void CDDM_set_medge (DerivedMesh * dm, MEdge * medge)
Definition at line 2680 of file cdderivedmesh.c.
References CD_ASSIGN, CD_MEDGE, CustomData_add_layer(), CustomData_has_layer(), DerivedMesh::edgeData, CDDerivedMesh::medge, and DerivedMesh::numEdgeData.
void CDDM_set_mface (DerivedMesh * dm, MFace * mface)
Definition at line 2690 of file cdderivedmesh.c.
References CD_ASSIGN, CD_MFACE, CustomData_add_layer(), CustomData_has_layer(), DerivedMesh::faceData, CDDerivedMesh::mface, and DerivedMesh::numTessFaceData.
void CDDM_set_mloop (DerivedMesh * dm, MLoop * mloop)
Definition at line 2700 of file cdderivedmesh.c.
References CD_ASSIGN, CD_MLOOP, CustomData_add_layer(), CustomData_has_layer(), DerivedMesh::loopData, CDDerivedMesh::mloop, and DerivedMesh::numLoopData.
void CDDM_set_mpoly (DerivedMesh * dm, MPoly * mpoly)
Definition at line 2710 of file cdderivedmesh.c.
References CD_ASSIGN, CD_MPOLY, CustomData_add_layer(), CustomData_has_layer(), CDDerivedMesh::mpoly, DerivedMesh::numPolyData, and DerivedMesh::polyData.
void CDDM_set_mvert (DerivedMesh * dm, MVert * mvert)
Definition at line 2670 of file cdderivedmesh.c.
References CD_ASSIGN, CD_MVERT, CustomData_add_layer(), CustomData_has_layer(), CDDerivedMesh::mvert, DerivedMesh::numVertData, and DerivedMesh::vertData.
void CDDM_tessfaces_to_faces (DerivedMesh * dm)
Definition at line 2578 of file cdderivedmesh.c.
References BLI_assert, BLI_edgehash_free(), BLI_edgehash_insert(), BLI_edgehash_lookup(), BLI_edgehash_new(), CD_ASSIGN, CD_DUPLICATE, CD_MASK_ORIGINDEX, CD_MLOOP, CD_MPOLY, CD_POLYINDEX, CDDM_calc_edges_tessface(), CustomData_add_layer(), CustomData_free(), CustomData_get_layer(), CustomData_merge(), CDDerivedMesh::dm, MLoop::e, DerivedMesh::faceData, GET_INT_FROM_POINTER, i, DerivedMesh::loopData, CDDerivedMesh::medge, MEM_callocN(), CDDerivedMesh::mface, CDDerivedMesh::mloop, CDDerivedMesh::mpoly, NULL, DerivedMesh::numEdgeData, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::numTessFaceData, DerivedMesh::polyData, SET_INT_IN_POINTER, MLoop::v, MEdge::v1, MEdge::v2, and MFace::v4.
Referenced by applyModifier(), cddm_copy_ex(), ConvertCSGDescriptorsToDerivedMesh(), cutEdges(), and explodeMesh().
static void cdDM_update_normals_from_pbvh (DerivedMesh * dm) [static]
Definition at line 296 of file cdderivedmesh.c.
References BLI_pbvh_update(), CD_NORMAL, CustomData_get_layer(), DerivedMesh::faceData, DerivedMesh::numTessFaceData, CDDerivedMesh::pbvh, CDDerivedMesh::pbvh_draw, and PBVH_UpdateNormals.
Referenced by cdDM_drawFacesTex_common(), cdDM_drawMappedFaces(), cdDM_drawMappedFacesGLSL(), and cdDM_drawMappedFacesMat().
static void loops_to_customdata_corners (BMesh * bm, CustomData * facedata, int cdindex, BMLoop * l3[3], int numCol, int numTex) [static]
Definition at line 1747 of file cdderivedmesh.c.
References CD_MCOL, CD_MLOOPCOL, CD_MLOOPUV, CD_MTEXPOLY, CD_MTFACE, CD_PREVIEW_MCOL, CD_PREVIEW_MLOOPCOL, copy_v2_v2(), CustomData_bmesh_get(), CustomData_bmesh_get_n(), CustomData_get(), CustomData_get_n(), CustomData_has_layer(), BMHeader::data, BMLoop::f, BMFace::head, BMLoop::head, i, BMesh::ldata, ME_MTEXFACE_CPY, MESH_MLOOPCOL_TO_MCOL, BMesh::pdata, MTFace::uv, and MLoopUV::uv.
Referenced by CDDM_from_BMEditMesh().