Blender: mallocn.cpp File Reference
mallocn.cpp File Reference
Guarded memory (de)allocation
#include <new>
#include "../MEM_guardedalloc.h"
Functions
void * operator new (size_t size)
void * operator new (size_t size, const char *str)
void operator delete (void *p)
Detailed Description
Definition in file mallocn.cpp.
Function Documentation
void operator delete (void * p)
Definition at line 42 of file mallocn.cpp.
References MEM_freeN().
void* operator new (size_t size)
Definition at line 31 of file mallocn.cpp.
References MEM_mallocN().
void* operator new (size_t size, const char * str)
Definition at line 37 of file mallocn.cpp.
References MEM_mallocN().