Blender: depsgraph_private.h File Reference
depsgraph_private.h File Reference
blenkernel
#include "BKE_depsgraph.h"
#include "DNA_constraint_types.h"
#include "BKE_constraint.h"
Classes
struct DagAdjList
struct DagNode
struct DagNodeQueueElem
struct DagNodeQueue
struct DagForest
Defines
#define DEPSX 5.0f
#define DEPSY 1.8f
#define DAGQUEUEALLOC 50
Typedefs
typedef struct DagAdjList DagAdjList
typedef struct DagNode DagNode
typedef struct DagNodeQueueElem DagNodeQueueElem
typedef struct DagNodeQueue DagNodeQueue
typedef struct DagForest DagForest
Enumerations
enum { DAG_WHITE = 0, DAG_GRAY = 1, DAG_BLACK = 2 }
Functions
DagNodeQueue * queue_create (int slots)
void queue_raz (DagNodeQueue *queue)
void push_queue (DagNodeQueue *queue, DagNode *node)
void push_stack (DagNodeQueue *queue, DagNode *node)
DagNode * pop_queue (DagNodeQueue *queue)
DagNode * get_top_node_queue (DagNodeQueue *queue)
DagForest * getMainDag (void)
void setMainDag (DagForest *dag)
DagForest * dag_init (void)
DagNode * dag_find_node (DagForest *forest, void *fob)
DagNode * dag_add_node (DagForest *forest, void *fob)
DagNode * dag_get_node (DagForest *forest, void *fob)
DagNode * dag_get_sub_node (DagForest *forest, void *fob)
void dag_add_relation (DagForest *forest, DagNode *fob1, DagNode *fob2, short rel, const char *name)
void graph_bfs (void)
DagNodeQueue * graph_dfs (void)
void set_node_xy (DagNode *node, float x, float y)
void graph_print_queue (DagNodeQueue *nqueue)
void graph_print_queue_dist (DagNodeQueue *nqueue)
void graph_print_adj_list (void)
Detailed Description
Definition in file depsgraph_private.h.
Define Documentation
#define DAGQUEUEALLOC 50
Definition at line 41 of file depsgraph_private.h.
Referenced by DAG_pose_sort(), DAG_scene_sort(), get_all_childs(), graph_bfs(), graph_dfs(), pre_and_post_source_BFS(), pre_and_post_source_DFS(), push_queue(), and push_stack().
#define DEPSX 5.0f
Definition at line 38 of file depsgraph_private.h.
Referenced by graph_bfs(), and graph_dfs().
#define DEPSY 1.8f
Definition at line 39 of file depsgraph_private.h.
Referenced by graph_bfs(), and graph_dfs().
Typedef Documentation
typedef struct DagAdjList DagAdjList
typedef struct DagForest DagForest
typedef struct DagNode DagNode
typedef struct DagNodeQueue DagNodeQueue
typedef struct DagNodeQueueElem DagNodeQueueElem
Enumeration Type Documentation
anonymous enum
Enumerator:
DAG_WHITE
DAG_GRAY
DAG_BLACK
Definition at line 43 of file depsgraph_private.h.
Function Documentation
DagNode* dag_add_node (DagForest * forest, void * fob)
Definition at line 846 of file depsgraph.c.
References BLI_ghash_insert(), BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), DagNode::color, DAG_WHITE, DagForest::DagNode, ListBase::first, GS, ListBase::last, MEM_callocN(), DagForest::nodeHash, DagForest::numNodes, DagNode::ob, DagNode::type, and ugly_hack_sorry.
Referenced by build_dag(), dag_get_node(), dag_get_sub_node(), and DAG_pose_sort().
void dag_add_relation (DagForest * forest, DagNode * fob1, DagNode * fob2, short rel, const char * name)
Definition at line 938 of file depsgraph.c.
References DagNode::child, DagAdjList::count, dag_add_parent_relation(), MEM_mallocN(), DagAdjList::name, DagAdjList::next, DagAdjList::node, and DagAdjList::type.
Referenced by build_dag_object(), dag_add_collision_field_relation(), dag_add_driver_relation(), DAG_pose_sort(), and updateDepgraph().
DagNode* dag_find_node (DagForest * forest, void * fob)
Definition at line 834 of file depsgraph.c.
References BLI_ghash_lookup(), DagForest::nodeHash, and NULL.
Referenced by dag_get_node(), dag_get_sub_node(), get_all_childs(), get_first_ancestors(), and get_obparents().
DagNode* dag_get_node (DagForest * forest, void * fob)
Definition at line 875 of file depsgraph.c.
References dag_add_node(), and dag_find_node().
Referenced by build_dag_object(), dag_add_collision_field_relation(), dag_add_driver_relation(), DAG_on_visible_update(), DAG_pose_sort(), dag_scene_flush_layers(), and updateDepgraph().
DagNode* dag_get_sub_node (DagForest * forest, void * fob)
Definition at line 887 of file depsgraph.c.
References dag_add_node(), dag_find_node(), DagForest::DagNode, ListBase::first, MEM_freeN(), DagAdjList::next, DagAdjList::node, and NULL.
DagForest* dag_init (void)
Definition at line 294 of file depsgraph.c.
References MEM_callocN().
Referenced by build_dag(), and DAG_pose_sort().
DagNode* get_top_node_queue (DagNodeQueue * queue)
Definition at line 283 of file depsgraph.c.
References DagNodeQueue::first, and DagNodeQueueElem::node.
Referenced by DAG_pose_sort(), DAG_scene_sort(), get_all_childs(), graph_dfs(), and pre_and_post_source_DFS().
DagForest* getMainDag (void)
Definition at line 1086 of file depsgraph.c.
References MainDag.
Referenced by graph_print_adj_list().
void graph_bfs (void)
Definition at line 1112 of file depsgraph.c.
References DagNode::BFS_dist, DagNode::child, DagNode::color, DagNodeQueue::count, DAG_BLACK, DAG_GRAY, DAG_WHITE, DagForest::DagNode, DAGQUEUEALLOC, DEPSX, DEPSY, ListBase::first, i, DagNode::k, DagNode::next, DagAdjList::next, DagAdjList::node, NULL, pop_queue(), push_queue(), queue_create(), queue_delete(), and set_node_xy().
DagNodeQueue* graph_dfs (void)
Definition at line 1240 of file depsgraph.c.
References DagNode::child, DagNode::color, DagNodeQueue::count, DAG_BLACK, DAG_GRAY, DAG_WHITE, DagForest::DagNode, DAGQUEUEALLOC, DEPSX, DEPSY, DagNode::DFS_dist, DagNode::DFS_dvtm, DagNode::DFS_fntm, ListBase::first, get_top_node_queue(), i, DagNode::k, DagNode::next, DagAdjList::next, DagAdjList::node, NULL, DagForest::numNodes, DagNode::ob, pop_queue(), push_stack(), queue_create(), queue_delete(), set_node_xy(), and DagForest::time.
void graph_print_adj_list (void)
Definition at line 1647 of file depsgraph.c.
References DagNode::child, DagNode::color, getMainDag(), DagNode::next, DagAdjList::next, DagAdjList::node, and DagNode::ob.
void graph_print_queue (DagNodeQueue * nqueue)
Definition at line 1615 of file depsgraph.c.
References DagNode::color, DagNode::DFS_dvtm, DagNode::DFS_fntm, DagNodeQueue::first, DagNodeQueueElem::next, DagNodeQueueElem::node, and DagNode::ob.
void graph_print_queue_dist (DagNodeQueue * nqueue)
Definition at line 1627 of file depsgraph.c.
References DagNodeQueue::count, DagNode::DFS_dvtm, DagNode::DFS_fntm, DagNodeQueue::first, DagNodeQueueElem::next, DagNodeQueueElem::node, and DagNode::ob.
DagNode* pop_queue (DagNodeQueue * queue)
Definition at line 248 of file depsgraph.c.
References DagNodeQueue::count, DagNodeQueue::first, DagNodeQueue::freenodes, DagNodeQueue::last, DagNodeQueueElem::next, DagNodeQueueElem::node, and NULL.
Referenced by DAG_pose_sort(), DAG_scene_sort(), get_all_childs(), graph_bfs(), graph_dfs(), pop_ob_queue(), pre_and_post_source_BFS(), and pre_and_post_source_DFS().
void push_queue (DagNodeQueue * queue, DagNode * node)
Definition at line 156 of file depsgraph.c.
References DagNodeQueue::count, DAGQUEUEALLOC, DagNodeQueue::first, DagNodeQueue::freenodes, i, DagNodeQueue::last, MEM_mallocN(), DagNodeQueueElem::next, DagNodeQueueElem::node, and NULL.
Referenced by get_first_ancestors(), get_obparents(), graph_bfs(), and pre_and_post_source_BFS().
void push_stack (DagNodeQueue * queue, DagNode * node)
Definition at line 207 of file depsgraph.c.
References DagNodeQueue::count, DAGQUEUEALLOC, DagNodeQueue::first, DagNodeQueue::freenodes, i, DagNodeQueue::last, MEM_mallocN(), DagNodeQueueElem::next, DagNodeQueueElem::node, and NULL.
Referenced by DAG_pose_sort(), DAG_scene_sort(), get_all_childs(), graph_dfs(), and pre_and_post_source_DFS().
DagNodeQueue* queue_create (int slots)
Definition at line 84 of file depsgraph.c.
References DagNodeQueue::count, DagNodeQueue::first, DagNodeQueue::freenodes, i, DagNodeQueue::last, DagNodeQueue::maxlevel, MEM_mallocN(), DagNodeQueueElem::next, DagNodeQueueElem::node, and NULL.
Referenced by DAG_pose_sort(), DAG_scene_sort(), get_all_childs(), get_first_ancestors(), get_obparents(), graph_bfs(), graph_dfs(), pre_and_post_source_BFS(), and pre_and_post_source_DFS().
void queue_raz (DagNodeQueue * queue)
Definition at line 111 of file depsgraph.c.
References DagNodeQueue::count, DagNodeQueue::first, DagNodeQueue::freenodes, DagNodeQueue::last, DagNodeQueueElem::next, DagNodeQueueElem::node, and NULL.
void set_node_xy (DagNode * node, float x, float y)
Definition at line 1606 of file depsgraph.c.
References DagNode::x, and DagNode::y.
Referenced by graph_bfs(), and graph_dfs().
void setMainDag (DagForest * dag)
Definition at line 1092 of file depsgraph.c.