Blender: BSP_TMesh.h File Reference
BSP_TMesh.h File Reference
#include "MT_Point3.h"
#include "MT_Vector3.h"
#include "MT_Transform.h"
#include "MEM_SmartPtr.h"
#include <vector>
#include "CSG_BooleanOps.h"
Classes
struct BSP_TVertex
struct BSP_TFace
class BSP_TMesh
struct VertexIt
struct FaceIt
Functions
static void VertexIt_Destruct (CSG_VertexIteratorDescriptor *iterator)
static int VertexIt_Done (CSG_IteratorPtr it)
static void VertexIt_Fill (CSG_IteratorPtr it, CSG_IVertex *vert)
static void VertexIt_Step (CSG_IteratorPtr it)
static void VertexIt_Reset (CSG_IteratorPtr it)
static
CSG_VertexIteratorDescriptor * VertexIt_Construct (BSP_TMesh *mesh, MT_Transform trans)
static void FaceIt_Destruct (CSG_FaceIteratorDescriptor *iterator)
static int FaceIt_Done (CSG_IteratorPtr it)
static void FaceIt_Fill (CSG_IteratorPtr it, CSG_IFace *face)
static void FaceIt_Step (CSG_IteratorPtr it)
static void FaceIt_Reset (CSG_IteratorPtr it)
static CSG_FaceIteratorDescriptor * FaceIt_Construct (BSP_TMesh *mesh)
static MEM_SmartPtr< BSP_TMesh > BuildMesh (CSG_MeshPropertyDescriptor &props, CSG_FaceIteratorDescriptor &face_it, CSG_VertexIteratorDescriptor &vertex_it)
Function Documentation
static MEM_SmartPtr<BSP_TMesh> BuildMesh (CSG_MeshPropertyDescriptor & props, CSG_FaceIteratorDescriptor & face_it, CSG_VertexIteratorDescriptor & vertex_it) [static]
Some Build functions.
Definition at line 319 of file BSP_TMesh.h.
References CSG_FaceIteratorDescriptor::Done, CSG_VertexIteratorDescriptor::Done, CSG_VertexIteratorDescriptor::Fill, CSG_FaceIteratorDescriptor::Fill, CSG_FaceIteratorDescriptor::it, CSG_VertexIteratorDescriptor::it, BSP_TVertex::m_pos, BSP_TFace::m_verts, CSG_IVertex::position, CSG_FaceIteratorDescriptor::Step, CSG_VertexIteratorDescriptor::Step, and CSG_IFace::vertex_index.
static CSG_FaceIteratorDescriptor* FaceIt_Construct (BSP_TMesh * mesh) [static]
Definition at line 291 of file BSP_TMesh.h.
References CSG_FaceIteratorDescriptor::Done, FaceIt_Done(), FaceIt_Fill(), FaceIt_Reset(), FaceIt_Step(), BSP_TMesh::FaceSet(), CSG_FaceIteratorDescriptor::Fill, CSG_FaceIteratorDescriptor::it, FaceIt::mesh, NULL, CSG_FaceIteratorDescriptor::num_elements, FaceIt::pos, CSG_FaceIteratorDescriptor::Reset, and CSG_FaceIteratorDescriptor::Step.
static void FaceIt_Destruct (CSG_FaceIteratorDescriptor * iterator) [static]
Definition at line 227 of file BSP_TMesh.h.
References CSG_FaceIteratorDescriptor::it, and NULL.
static int FaceIt_Done (CSG_IteratorPtr it) [static]
Definition at line 238 of file BSP_TMesh.h.
References BSP_TMesh::FaceSet(), FaceIt::mesh, and FaceIt::pos.
Referenced by FaceIt_Construct().
static void FaceIt_Fill (CSG_IteratorPtr it, CSG_IFace * face) [static]
Definition at line 252 of file BSP_TMesh.h.
References FaceIt::pos, CSG_IFace::vertex_index, and CSG_IFace::vertex_number.
Referenced by FaceIt_Construct().
static void FaceIt_Reset (CSG_IteratorPtr it) [static]
Definition at line 280 of file BSP_TMesh.h.
References BSP_TMesh::FaceSet(), FaceIt::mesh, and FaceIt::pos.
Referenced by FaceIt_Construct().
static void FaceIt_Step (CSG_IteratorPtr it) [static]
Definition at line 269 of file BSP_TMesh.h.
References FaceIt::pos.
Referenced by FaceIt_Construct().
static CSG_VertexIteratorDescriptor* VertexIt_Construct (BSP_TMesh * mesh, MT_Transform trans) [static]
Definition at line 192 of file BSP_TMesh.h.
References CSG_VertexIteratorDescriptor::Done, CSG_VertexIteratorDescriptor::Fill, CSG_VertexIteratorDescriptor::it, VertexIt::mesh, NULL, CSG_VertexIteratorDescriptor::num_elements, VertexIt::pos, CSG_VertexIteratorDescriptor::Reset, CSG_VertexIteratorDescriptor::Step, VertexIt::trans, VertexIt_Done(), VertexIt_Fill(), VertexIt_Reset(), VertexIt_Step(), and BSP_TMesh::VertexSet().
static void VertexIt_Destruct (CSG_VertexIteratorDescriptor * iterator) [static]
Definition at line 132 of file BSP_TMesh.h.
References CSG_VertexIteratorDescriptor::it, and NULL.
static int VertexIt_Done (CSG_IteratorPtr it) [static]
Definition at line 143 of file BSP_TMesh.h.
References VertexIt::mesh, VertexIt::pos, and BSP_TMesh::VertexSet().
Referenced by VertexIt_Construct().
static void VertexIt_Fill (CSG_IteratorPtr it, CSG_IVertex * vert) [static]
Definition at line 155 of file BSP_TMesh.h.
References MT_Tuple3::getValue(), p, VertexIt::pos, CSG_IVertex::position, and VertexIt::trans.
Referenced by VertexIt_Construct().
static void VertexIt_Reset (CSG_IteratorPtr it) [static]
Definition at line 181 of file BSP_TMesh.h.
References VertexIt::mesh, VertexIt::pos, and BSP_TMesh::VertexSet().
Referenced by VertexIt_Construct().
static void VertexIt_Step (CSG_IteratorPtr it) [static]
Definition at line 170 of file BSP_TMesh.h.
References VertexIt::pos.
Referenced by VertexIt_Construct().