Blender: collada_utils.h File Reference
collada_utils.h File Reference
COLLADA
#include "COLLADAFWMeshPrimitive.h"
#include "COLLADAFWGeometry.h"
#include "COLLADAFWFloatOrDoubleArray.h"
#include "COLLADAFWTypes.h"
#include <vector>
#include <map>
#include "DNA_object_types.h"
#include "DNA_customdata_types.h"
#include "DNA_texture_types.h"
#include "BKE_context.h"
Typedefs
typedef std::map
< COLLADAFW::TextureMapId,
std::vector< MTex * > > TexIndexTextureArrayMap
Functions
float bc_get_float_value (const COLLADAFW::FloatOrDoubleArray &array, unsigned int index)
int bc_test_parent_loop (Object *par, Object *ob)
int bc_set_parent (Object *ob, Object *par, bContext *C, bool is_parent_space=true)
char * bc_CustomData_get_layer_name (const CustomData *data, int type, int n)
char * bc_CustomData_get_active_layer_name (const CustomData *data, int type)
Detailed Description
Definition in file collada_utils.h.
Typedef Documentation
typedef std::map<COLLADAFW::TextureMapId, std::vector<MTex*> > TexIndexTextureArrayMap
Definition at line 43 of file collada_utils.h.
Function Documentation
char* bc_CustomData_get_active_layer_name (const CustomData * data, int type)
Definition at line 138 of file DocumentExporter.cpp.
References CustomData_get_active_layer_index(), CustomData::layers, CustomDataLayer::name, and NULL.
Referenced by getActiveUVLayerName().
char* bc_CustomData_get_layer_name (const CustomData * data, int type, int n)
Referenced by InstanceWriter::add_material_bindings().
float bc_get_float_value (const COLLADAFW::FloatOrDoubleArray & array, unsigned int index)
Definition at line 48 of file collada_utils.cpp.
Referenced by SkinInfo::borrow_skin_controller_data().
int bc_set_parent (Object * ob, Object * par, bContext * C, bool is_parent_space = true)
Definition at line 72 of file collada_utils.cpp.
References bc_test_parent_loop(), copy_m4_m4(), CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), DAG_scene_sort(), invert_m4_m4(), mult_m4_m4m4(), NC_OBJECT, ND_TRANSFORM, NULL, OB_RECALC_DATA, OB_RECALC_OB, object_apply_mat4(), Object::obmat, Object::parent, Object::parentinv, PAROBJECT, Object::parsubstr, Object::partype, Object::recalc, what_does_parent(), where_is_object(), and WM_event_add_notifier().
Referenced by DocumentImporter::create_instance_node(), SkinInfo::link_armature(), ArmatureImporter::make_armatures(), and DocumentImporter::write_node().
int bc_test_parent_loop (Object * par, Object * ob)
Definition at line 60 of file collada_utils.cpp.
References bc_test_parent_loop(), NULL, and Object::parent.
Referenced by bc_set_parent(), and bc_test_parent_loop().