Blender: math_rotation.c File Reference
math_rotation.c File Reference
blenlib
#include <assert.h>
#include "BLI_math.h"
Classes
struct RotOrderInfo
Defines
#define QUAT_EPSILON 0.0001
#define GET_ROTATIONORDER_INFO(order) (assert(order >= 0 && order <= 6), (order < 1) ? &rotOrders[0] : &rotOrders[(order) - 1])
Typedefs
typedef struct RotOrderInfo RotOrderInfo
Functions
void unit_axis_angle (float axis[3], float *angle)
void unit_qt (float q[4])
void copy_qt_qt (float q1[4], const float q2[4])
int is_zero_qt (float *q)
void mul_qt_qtqt (float q[4], const float q1[4], const float q2[4])
void mul_qt_v3 (const float q[4], float v[3])
void conjugate_qt (float q[4])
float dot_qtqt (const float q1[4], const float q2[4])
void invert_qt (float q[4])
void invert_qt_qt (float q1[4], const float q2[4])
void mul_qt_fl (float q[4], const float f)
void sub_qt_qtqt (float q[4], const float q1[4], const float q2[4])
void mul_fac_qt_fl (float q[4], const float fac)
static void quat_to_mat3_no_error (float m[][3], const float q[4])
void quat_to_mat3 (float m[][3], const float q[4])
void quat_to_mat4 (float m[][4], const float q[4])
void mat3_to_quat (float q[4], float wmat[][3])
void mat4_to_quat (float q[4], float m[][4])
void mat3_to_quat_is_ok (float q[4], float wmat[3][3])
float normalize_qt (float q[4])
float normalize_qt_qt (float r[4], const float q[4])
void rotation_between_vecs_to_quat (float q[4], const float v1[3], const float v2[3])
void rotation_between_quats_to_quat (float q[4], const float q1[4], const float q2[4])
void vec_to_quat (float q[4], const float vec[3], short axis, const short upflag)
void interp_qt_qtqt (float result[4], const float quat1[4], const float quat2[4], const float t)
void add_qt_qtqt (float result[4], const float quat1[4], const float quat2[4], const float t)
void tri_to_quat (float quat[4], const float v1[3], const float v2[3], const float v3[3])
void print_qt (const char *str, const float q[4])
void axis_angle_to_quat (float q[4], const float axis[3], float angle)
void quat_to_axis_angle (float axis[3], float *angle, const float q[4])
void axis_angle_to_eulO (float eul[3], const short order, const float axis[3], const float angle)
void eulO_to_axis_angle (float axis[3], float *angle, const float eul[3], const short order)
void axis_angle_to_mat3 (float mat[3][3], const float axis[3], const float angle)
void axis_angle_to_mat4 (float mat[4][4], const float axis[3], const float angle)
void mat3_to_axis_angle (float axis[3], float *angle, float mat[3][3])
void mat4_to_axis_angle (float axis[3], float *angle, float mat[4][4])
void single_axis_angle_to_mat3 (float mat[3][3], const char axis, const float angle)
void vec_rot_to_mat3 (float mat[][3], const float vec[3], const float phi)
void vec_rot_to_mat4 (float mat[][4], const float vec[3], const float phi)
void vec_rot_to_quat (float *quat, const float vec[3], const float phi)
void eul_to_mat3 (float mat[][3], const float eul[3])
void eul_to_mat4 (float mat[][4], const float eul[3])
static void mat3_to_eul2 (float tmat[][3], float eul1[3], float eul2[3])
void mat3_to_eul (float *eul, float tmat[][3])
void mat4_to_eul (float *eul, float tmat[][4])
void quat_to_eul (float *eul, const float quat[4])
void eul_to_quat (float *quat, const float eul[3])
void rotate_eul (float *beul, const char axis, const float ang)
void compatible_eul (float eul[3], const float oldrot[3])
void mat3_to_compatible_eul (float eul[3], const float oldrot[3], float mat[][3])
void eulO_to_quat (float q[4], const float e[3], const short order)
void quat_to_eulO (float e[3], short const order, const float q[4])
void eulO_to_mat3 (float M[3][3], const float e[3], const short order)
static void mat3_to_eulo2 (float M[3][3], float *e1, float *e2, short order)
void eulO_to_mat4 (float M[4][4], const float e[3], const short order)
void mat3_to_eulO (float eul[3], const short order, float M[3][3])
void mat4_to_eulO (float e[3], const short order, float M[4][4])
void mat3_to_compatible_eulO (float eul[3], float oldrot[3], short order, float mat[3][3])
void mat4_to_compatible_eulO (float eul[3], float oldrot[3], short order, float M[4][4])
void rotate_eulO (float beul[3], short order, char axis, float ang)
void eulO_to_gimbal_axis (float gmat[][3], const float eul[3], const short order)
void mat4_to_dquat (DualQuat *dq, float basemat[][4], float mat[][4])
void dquat_to_mat4 (float mat[][4], DualQuat *dq)
void add_weighted_dq_dq (DualQuat *dqsum, DualQuat *dq, float weight)
void normalize_dq (DualQuat *dq, float totweight)
void mul_v3m3_dq (float *co, float mat[][3], DualQuat *dq)
void copy_dq_dq (DualQuat *dq1, DualQuat *dq2)
void quat_apply_track (float quat[4], short axis, short upflag)
void vec_apply_track (float vec[3], short axis)
float focallength_to_fov (float focal_length, float sensor)
float fov_to_focallength (float hfov, float sensor)
static float mod_inline (float a, float b)
float angle_wrap_rad (float angle)
float angle_wrap_deg (float angle)
Variables
static RotOrderInfo rotOrders []
Detailed Description
Definition in file math_rotation.c.
Define Documentation
#define GET_ROTATIONORDER_INFO (order) (assert(order >= 0 && order <= 6), (order < 1) ? &rotOrders[0] : &rotOrders[(order) - 1])
Definition at line 1198 of file math_rotation.c.
Referenced by eulO_to_gimbal_axis(), eulO_to_mat3(), eulO_to_quat(), and mat3_to_eulo2().
#define QUAT_EPSILON 0.0001
Definition at line 38 of file math_rotation.c.
Referenced by quat_to_axis_angle(), quat_to_mat3(), and quat_to_mat4().
Typedef Documentation
typedef struct RotOrderInfo RotOrderInfo
Function Documentation
void add_qt_qtqt (float result[4], const float quat1[4], const float quat2[4], const float t)
Definition at line 586 of file math_rotation.c.
Referenced by pose_slide_apply_quat(), and Quaternion_add().
void add_weighted_dq_dq (DualQuat * dqsum, DualQuat * dq, float weight)
Definition at line 1561 of file math_rotation.c.
References add_m4_m4m4(), copy_m4_m4(), dot_qtqt(), mul_m4_fl(), DualQuat::quat, DualQuat::scale, DualQuat::scale_weight, and DualQuat::trans.
Referenced by dist_bone_deform(), and pchan_bone_deform().
float angle_wrap_deg (float angle)
Definition at line 1767 of file math_rotation.c.
References mod_inline().
float angle_wrap_rad (float angle)
Definition at line 1762 of file math_rotation.c.
References M_PI, and mod_inline().
Referenced by C_Matrix_Rotation(), Quaternion_angle_set(), Quaternion_new(), and Rotation().
void axis_angle_to_eulO (float eul[3], const short order, const float axis[3], const float angle)
Definition at line 692 of file math_rotation.c.
References axis_angle_to_quat(), and quat_to_eulO().
Referenced by BKE_rotMode_change_values(), object_clear_rot(), pchan_clear_rot(), pose_bone_do_paste(), and protectedAxisAngleBits().
void axis_angle_to_mat3 (float mat[3][3], const float axis[3], const float angle)
Definition at line 715 of file math_rotation.c.
References co, cos(), normalize_v3_v3(), si, sin(), and unit_m3().
Referenced by apply_targetless_ik(), applyModifier(), axis_angle_to_mat4(), bmo_spin_exec(), C_Matrix_Rotation(), damptrack_evaluate(), edbm_dupli_extrude_cursor_invoke(), joint_callback(), object_rot_to_mat3(), pchan_to_mat4(), and splineik_evaluate_bone().
void axis_angle_to_mat4 (float mat[4][4], const float axis[3], const float angle)
Definition at line 746 of file math_rotation.c.
References axis_angle_to_mat3(), copy_m4_m3(), and unit_m4().
Referenced by constraintob_from_transdata(), TransformReader::dae_rotate_to_mat4(), do_rotate_brush(), and AnimationImporter::evaluate_animation().
void axis_angle_to_quat (float q[4], const float axis[3], float angle)
Definition at line 646 of file math_rotation.c.
References cos(), normalize_v3_v3(), si, sin(), and unit_qt().
Referenced by applyModifier(), applyTranslation(), axis_angle_to_eulO(), axis_angle_to_gimbal_axis(), basic_rotate(), bevel_list_apply_tilt(), bevel_list_smooth(), BKE_rotMode_change_values(), boid_body(), cache_key_incremental_rotation(), do_guides(), do_kink(), draw_rotation_guide(), ElementRotation(), flyApply(), flyApply_ndof(), loc_axisangle_size_to_mat4(), make_bevel_list_3D_minimum_twist(), make_bevel_list_segment_3D(), ndof_orbit_invoke(), ndof_to_quat(), poly_rotate_plane(), pose_bone_do_paste(), psys_get_birth_coordinates(), psys_get_dupli_path_transform(), Quaternion_angle_set(), Quaternion_axis_vector_set(), Quaternion_new(), rollBoneByQuatJoint(), rotation_between_vecs_to_quat(), view3d_align_axis_to_vector(), and viewrotate_apply().
void compatible_eul (float eul[3], const float oldrot[3])
Definition at line 1061 of file math_rotation.c.
References fabs(), and M_PI.
Referenced by dvar_eval_transChan(), Euler_make_compatible(), mat3_to_compatible_eul(), mat3_to_compatible_eulO(), and rotlike_evaluate().
void conjugate_qt (float q[4])
Definition at line 100 of file math_rotation.c.
Referenced by invert_qt(), Quaternion_conjugate(), rotation_between_quats_to_quat(), and viewrotate_apply().
void copy_dq_dq (DualQuat * dq1, DualQuat * dq2)
Definition at line 1668 of file math_rotation.c.
Referenced by b_bone_deform().
void copy_qt_qt (float q1[4], const float q2[4])
Definition at line 55 of file math_rotation.c.
Referenced by add_pose_transdata(), bevel_list_cyclic_fix_3D(), bevel_list_smooth(), boid_body(), calc_curve_deform(), copy_attr(), copy_pose_channel_data(), copy_pose_result(), createTransMBallVerts(), do_path_effectors(), dquat_to_mat4(), ED_object_rotation_from_view(), equalize_bezier(), fcurves_to_pchan_links_get(), flyEnd(), game_blend_poses(), initFlyInfo(), interpolate_pathcache(), invert_qt_qt(), make_bevel_list_3D_minimum_twist(), make_bevel_list_segment_3D(), normalize_qt_qt(), object_clear_rot(), object_tfm_backup(), object_tfm_restore(), ObjectToTransData(), offset_child(), pose_bone_do_paste(), pose_slide_apply_quat(), poseAnim_mapping_reset(), psys_cache_edit_paths(), psys_get_birth_coordinates(), psys_get_from_key(), psys_get_particle_on_path(), psys_thread_create_path(), quat_mul_float(), Quaternion_CreatePyObject(), region_quadview_exec(), repositionControl(), restore_localviewdata(), restoreElement(), rotation_between_quats_to_quat(), smooth_view(), view3d_camera_to_view_exec(), view3d_smoothview_invoke(), view3d_split_250(), viewnumpad_exec(), viewops_data_create(), viewrotate_apply(), where_on_path(), and where_on_path_deform().
float dot_qtqt (const float q1[4], const float q2[4])
Definition at line 107 of file math_rotation.c.
Referenced by add_weighted_dq_dq(), dquat_to_mat4(), invert_qt(), mul_v3m3_dq(), normalize_qt(), quat_to_axis_angle(), quat_to_mat3(), quat_to_mat4(), Quaternion_dot(), Quaternion_magnitude_get(), and rotation_between_quats_to_quat().
void dquat_to_mat4 (float mat[][4], DualQuat * dq)
Definition at line 1537 of file math_rotation.c.
References copy_qt_qt(), dot_qtqt(), len(), mul_qt_fl(), DualQuat::quat, quat_to_mat4(), sqrt(), and DualQuat::trans.
void eul_to_mat3 (float mat[][3], const float eul[3])
Definition at line 885 of file math_rotation.c.
References cos(), si, and sin().
void eul_to_mat4 (float mat[][4], const float eul[3])
Definition at line 913 of file math_rotation.c.
References cos(), si, and sin().
void eul_to_quat (float * quat, const float eul[3])
Definition at line 1013 of file math_rotation.c.
References cosf, si, and sinf.
void eulO_to_axis_angle (float axis[3], float * angle, const float eul[3], const short order)
Definition at line 702 of file math_rotation.c.
References eulO_to_quat(), and quat_to_axis_angle().
Referenced by BKE_rotMode_change_values(), object_clear_rot(), pchan_clear_rot(), pose_bone_do_paste(), and protectedAxisAngleBits().
void eulO_to_gimbal_axis (float gmat[][3], const float eul[3], const short order)
Definition at line 1422 of file math_rotation.c.
References RotOrderInfo::axis, copy_v3_v3(), eulO_to_mat3(), GET_ROTATIONORDER_INFO, and R.
void eulO_to_mat3 (float M[3][3], const float e[3], const short order)
Definition at line 1246 of file math_rotation.c.
References RotOrderInfo::axis, cos(), GET_ROTATIONORDER_INFO, i, RotOrderInfo::parity, R, si, and sin().
Referenced by apply_targetless_ik(), ElementRotation(), Euler_rotate(), Euler_to_matrix(), eulO_to_gimbal_axis(), eulO_to_mat4(), joint_callback(), loc_eulO_size_to_mat4(), mathutils_any_to_rotmat(), object_rot_to_mat3(), pchan_to_mat4(), and rotate_eulO().
void eulO_to_mat4 (float M[4][4], const float e[3], const short order)
Definition at line 1329 of file math_rotation.c.
References copy_m4_m3(), eulO_to_mat3(), and normalize_m3().
Referenced by constraintob_from_transdata().
void eulO_to_quat (float q[4], const float e[3], const short order)
Definition at line 1201 of file math_rotation.c.
References RotOrderInfo::axis, cos(), GET_ROTATIONORDER_INFO, i, RotOrderInfo::parity, R, si, and sin().
Referenced by BKE_rotMode_change_values(), Euler_to_quaternion(), eulO_to_axis_angle(), object_mat3_to_rot(), and pose_bone_do_paste().
float focallength_to_fov (float focal_length, float sensor)
Definition at line 1746 of file math_rotation.c.
References atanf.
Referenced by CamerasExporter::operator()(), and project_camera_info().
float fov_to_focallength (float hfov, float sensor)
Definition at line 1751 of file math_rotation.c.
References tanf.
Referenced by DocumentImporter::writeCamera().
void interp_qt_qtqt (float result[4], const float quat1[4], const float quat2[4], const float t)
Definition at line 548 of file math_rotation.c.
References acos(), and sin().
Referenced by bevel_list_smooth(), blend_m3_m3m3(), blend_m4_m4m4(), calc_curvepath(), collision_response(), do_particle_interpolation(), execute_posetree(), game_blend_poses(), interpolate_pathcache(), pose_slide_apply_quat(), psys_get_birth_coordinates(), psys_get_particle_state(), ptcache_particle_interpolate(), Quaternion_slerp(), view3d_smoothview_invoke(), and where_on_path().
void invert_qt (float q[4])
Definition at line 112 of file math_rotation.c.
References conjugate_qt(), dot_qtqt(), and mul_qt_fl().
Referenced by axis_set_view(), dvar_eval_rotDiff(), invert_qt_qt(), object_mat3_to_rot(), and Quaternion_invert().
void invert_qt_qt (float q1[4], const float q2[4])
Definition at line 123 of file math_rotation.c.
References copy_qt_qt(), and invert_qt().
Referenced by flyApply_ndof(), ndof_orbit_invoke(), ndof_pan_invoke(), smooth_view(), and viewrotate_apply().
int is_zero_qt (float * q)
Definition at line 63 of file math_rotation.c.
void mat3_to_axis_angle (float axis[3], float * angle, float mat[3][3])
Definition at line 756 of file math_rotation.c.
References mat3_to_quat(), and quat_to_axis_angle().
Referenced by apply_targetless_ik(), object_mat3_to_rot(), pchan_mat3_to_rot(), and pivotcon_evaluate().
void mat3_to_compatible_eul (float eul[3], const float oldrot[3], float mat[][3])
Definition at line 1141 of file math_rotation.c.
References compatible_eul(), copy_v3_v3(), fabs(), and mat3_to_eul2().
void mat3_to_compatible_eulO (float eul[3], float oldrot[3], short order, float mat[3][3])
Definition at line 1367 of file math_rotation.c.
References compatible_eul(), copy_v3_v3(), fabsf, and mat3_to_eulo2().
Referenced by ElementRotation(), Euler_rotate(), mat4_to_compatible_eulO(), Matrix_to_euler(), object_mat3_to_rot(), pchan_mat3_to_rot(), and Quaternion_to_euler().
void mat3_to_eul (float * eul, float tmat[][3])
Definition at line 978 of file math_rotation.c.
References copy_v3_v3(), fabs(), and mat3_to_eul2().
static void mat3_to_eul2 (float tmat[][3], float eul1[3], float eul2[3]) [static]
Definition at line 946 of file math_rotation.c.
References KDL::atan2(), copy_m3_m3(), copy_v3_v3(), mat3_to_quat(), normalize_m3(), quat_to_mat3(), and sqrt().
Referenced by mat3_to_compatible_eul(), and mat3_to_eul().
void mat3_to_eulO (float eul[3], const short order, float M[3][3])
Definition at line 1340 of file math_rotation.c.
References copy_v3_v3(), fabs(), and mat3_to_eulo2().
Referenced by apply_targetless_ik(), mat4_to_eulO(), Matrix_to_euler(), object_mat3_to_rot(), pchan_mat3_to_rot(), quat_to_eulO(), and rotate_eulO().
static void mat3_to_eulo2 (float M[3][3], float * e1, float * e2, short order) [static]
Definition at line 1287 of file math_rotation.c.
References KDL::atan2(), RotOrderInfo::axis, copy_m3_m3(), copy_v3_v3(), GET_ROTATIONORDER_INFO, i, normalize_m3(), RotOrderInfo::parity, R, and sqrt().
Referenced by mat3_to_compatible_eulO(), and mat3_to_eulO().
void mat3_to_quat (float q[4], float wmat[][3])
Definition at line 251 of file math_rotation.c.
References copy_m3_m3(), normalize_m3(), normalize_qt(), sqrt(), and sqrtf.
void mat3_to_quat_is_ok (float q[4], float wmat[3][3])
Definition at line 311 of file math_rotation.c.
References angle(), KDL::atan2(), co, copy_m3_m3(), cos(), invert_m3_m3(), mul_m3_v3(), mul_qt_qtqt(), normalize_m3(), normalize_v3(), quat_to_mat3_no_error(), saacos(), si, and sin().
Referenced by boid_body(), psys_cache_edit_paths(), psys_get_birth_coordinates(), and visualkey_get_value().
void mat4_to_axis_angle (float axis[3], float * angle, float mat[4][4])
Definition at line 767 of file math_rotation.c.
References mat4_to_quat(), and quat_to_axis_angle().
Referenced by constraintRotLim(), and visualkey_get_value().
void mat4_to_compatible_eulO (float eul[3], float oldrot[3], short order, float M[4][4])
Definition at line 1387 of file math_rotation.c.
References copy_m3_m4(), mat3_to_compatible_eulO(), and normalize_m3().
Referenced by rotlike_evaluate().
void mat4_to_dquat (DualQuat * dq, float basemat[][4], float mat[][4])
Conversion routines between (regular quaternion, translation) and dual quaternion.
Version 1.0.0, February 7th, 2007
Copyright (C) 2006-2007 University of Dublin, Trinity College, All Rights Reserved
This software is provided 'as-is', without any express or implied warranty. In no event will the author(s) be held liable for any damages arising from the use of this software.
Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:
1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required. 2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software. 3. This notice may not be removed or altered from any source distribution.
Author:
Ladislav Kavan, kavanl@cs.tcd.ie
Changes for Blender:
renaming, style changes and optimization's
added support for scaling
Definition at line 1481 of file math_rotation.c.
References copy_m4_m4(), copy_v3_v3(), determinant_m4(), invert_m4_m4(), len_v3(), mat4_to_quat(), mat4_to_size(), mul_serie_m4(), mult_m4_m4m4(), NULL, orthogonalize_m4(), DualQuat::quat, quat_to_mat4(), R, DualQuat::scale, DualQuat::scale_weight, and DualQuat::trans.
void mat4_to_eul (float * eul, float tmat[][4])
Definition at line 994 of file math_rotation.c.
References copy_m3_m4(), mat3_to_eul(), and normalize_m3().
void mat4_to_eulO (float e[3], const short order, float M[4][4])
Definition at line 1356 of file math_rotation.c.
References copy_m3_m4(), mat3_to_eulO(), and normalize_m3().
Referenced by childof_evaluate(), constraintRotLim(), dvar_eval_transChan(), pivotcon_evaluate(), rotlike_evaluate(), rotlimit_evaluate(), transform_evaluate(), and visualkey_get_value().
void mat4_to_quat (float q[4], float m[][4])
Definition at line 303 of file math_rotation.c.
References copy_m3_m4(), and mat3_to_quat().
static float mod_inline (float a, float b) [static]
Definition at line 1757 of file math_rotation.c.
References floorf.
Referenced by angle_wrap_deg(), and angle_wrap_rad().
void mul_fac_qt_fl (float q[4], const float fac)
Definition at line 151 of file math_rotation.c.
References angle(), co, cos(), mul_v3_fl(), normalize_v3(), saacos(), si, and sin().
Referenced by game_blend_poses().
void mul_qt_fl (float q[4], const float f)
Definition at line 130 of file math_rotation.c.
Referenced by dquat_to_mat4(), invert_qt(), normalize_dq(), normalize_qt(), object_clear_rot(), pchan_clear_rot(), protectedQuaternionBits(), quat_mul_float(), Quaternion_angle_set(), Quaternion_axis_vector_set(), Quaternion_negate(), and Quaternion_rotate().
void mul_qt_qtqt (float q[4], const float q1[4], const float q2[4])
Definition at line 68 of file math_rotation.c.
Referenced by axis_set_view(), basic_rotate(), bevel_list_apply_tilt(), bevel_list_smooth(), cache_key_incremental_rotation(), calc_curve_deform(), dvar_eval_rotDiff(), ElementRotation(), finalizeControl(), flyApply(), flyApply_ndof(), followpath_get_tarmat(), game_blend_poses(), interpolate_pathcache(), make_bevel_list_3D_minimum_twist(), make_bevel_list_segment_3D(), mat3_to_quat_is_ok(), ndof_orbit_invoke(), ob_parcurve(), object_mat3_to_rot(), psys_get_birth_coordinates(), psys_thread_create_path(), quat_apply_track(), Quaternion_cross(), Quaternion_mul(), repositionBone(), rotation_between_quats_to_quat(), sub_qt_qtqt(), tri_to_quat(), vec_to_quat(), vieworbit_exec(), and viewrotate_apply().
void mul_qt_v3 (const float q[4], float v[3])
Definition at line 82 of file math_rotation.c.
Referenced by applyModifier(), axis_angle_to_gimbal_axis(), barycentric_transform(), bevel_list_smooth(), boid_body(), calc_curve_deform(), do_guides(), do_kink(), do_physical_effector(), draw_particle(), draw_rotation_guide(), draw_view_axis(), drawnurb(), explodeMesh(), flyApply_ndof(), get_effector_data(), make_bevel_list_3D_minimum_twist(), ndof_orbit_invoke(), ndof_pan_invoke(), offset_child(), psys_get_dupli_path_transform(), psys_thread_create_path(), Quaternion_mul(), recalcData_view3d(), repositionControl(), rollBoneByQuat(), rollBoneByQuatAligned(), rollBoneByQuatJoint(), rotateBevelPiece(), rule_average_speed(), smooth_view(), Vector_imul(), Vector_mul(), and viewrotate_apply().
void mul_v3m3_dq (float * co, float mat[][3], DualQuat * dq)
Definition at line 1618 of file math_rotation.c.
References copy_m3_m3(), copy_m3_m4(), dot_qtqt(), M, mul_m3_fl(), mul_m3_m3m3(), mul_m3_v3(), mul_m4_v3(), DualQuat::quat, DualQuat::scale, DualQuat::scale_weight, and DualQuat::trans.
void normalize_dq (DualQuat * dq, float totweight)
Definition at line 1596 of file math_rotation.c.
References mul_m4_fl(), mul_qt_fl(), DualQuat::quat, DualQuat::scale, DualQuat::scale_weight, and DualQuat::trans.
Referenced by armature_deform_verts().
float normalize_qt (float q[4])
Definition at line 354 of file math_rotation.c.
References dot_qtqt(), len(), mul_qt_fl(), and sqrt().
Referenced by axis_set_view(), barycentric_transform(), basic_rotate(), bevel_list_apply_tilt(), bevel_list_smooth(), BKE_rotMode_change_values(), calc_curve_deform(), calc_curvepath(), game_blend_poses(), joint_callback(), make_bevel_list_segment_3D(), mat3_to_quat(), normalize_qt_qt(), ob_parcurve(), pose_bone_do_paste(), psys_get_birth_coordinates(), Quaternion_normalize(), and viewrotate_apply().
float normalize_qt_qt (float r[4], const float q[4])
Definition at line 370 of file math_rotation.c.
References copy_qt_qt(), and normalize_qt().
Referenced by constraintob_from_transdata(), mathutils_any_to_rotmat(), new_particle_duplilist(), object_mat3_to_rot(), object_rot_to_mat3(), pchan_clear_rot(), pchan_to_mat4(), protectedQuaternionBits(), Quaternion_angle_get(), Quaternion_angle_set(), Quaternion_axis_vector_get(), Quaternion_axis_vector_set(), Quaternion_rotate(), Quaternion_to_axis_angle(), and Quaternion_to_euler().
void print_qt (const char * str, const float q[4])
Definition at line 638 of file math_rotation.c.
void quat_apply_track (float quat[4], short axis, short upflag)
Definition at line 1674 of file math_rotation.c.
References assert, and mul_qt_qtqt().
Referenced by calc_curve_deform(), followpath_get_tarmat(), and ob_parcurve().
void quat_to_axis_angle (float axis[3], float * angle, const float q[4])
Definition at line 665 of file math_rotation.c.
References acos(), dot_qtqt(), fabs(), fabsf, QUAT_EPSILON, si, and sin().
Referenced by BKE_rotMode_change_values(), ElementRotation(), eulO_to_axis_angle(), mat3_to_axis_angle(), mat4_to_axis_angle(), pose_bone_do_paste(), Quaternion_angle_set(), Quaternion_axis_vector_get(), Quaternion_axis_vector_set(), and Quaternion_to_axis_angle().
void quat_to_eul (float * eul, const float quat[4])
Definition at line 1004 of file math_rotation.c.
References mat3_to_eul(), and quat_to_mat3().
void quat_to_eulO (float e[3], short const order, const float q[4])
Definition at line 1237 of file math_rotation.c.
References M, mat3_to_eulO(), and quat_to_mat3().
Referenced by axis_angle_to_eulO(), BKE_rotMode_change_values(), pose_bone_do_paste(), and Quaternion_to_euler().
void quat_to_mat3 (float m[][3], const float q[4])
Definition at line 195 of file math_rotation.c.
References dot_qtqt(), fabsf, QUAT_EPSILON, and quat_to_mat3_no_error().
static void quat_to_mat3_no_error (float m[][3], const float q[4]) [static]
Definition at line 163 of file math_rotation.c.
References M_SQRT2.
Referenced by mat3_to_quat_is_ok(), and quat_to_mat3().
void quat_to_mat4 (float m[][4], const float q[4])
Definition at line 207 of file math_rotation.c.
References dot_qtqt(), fabsf, M_SQRT2, and QUAT_EPSILON.
void rotate_eul (float * beul, const char axis, const float ang)
Definition at line 1038 of file math_rotation.c.
References assert, eul_to_mat3(), mat3_to_eul(), and mul_m3_m3m3().
void rotate_eulO (float beul[3], short order, char axis, float ang)
Definition at line 1399 of file math_rotation.c.
References assert, eulO_to_mat3(), mat3_to_eulO(), and mul_m3_m3m3().
Referenced by Euler_rotate_axis(), and rotlike_evaluate().
void rotation_between_quats_to_quat (float q[4], const float q1[4], const float q2[4])
Definition at line 389 of file math_rotation.c.
References conjugate_qt(), copy_qt_qt(), dot(), dot_qtqt(), and mul_qt_qtqt().
Referenced by Quaternion_rotation_difference().
void rotation_between_vecs_to_quat (float q[4], const float v1[3], const float v2[3])
Definition at line 377 of file math_rotation.c.
References angle(), angle_normalized_v3v3(), axis_angle_to_quat(), and cross_v3_v3v3().
Referenced by barycentric_transform(), calc_curve_deform(), finalizeControl(), recalcData_view3d(), repositionBone(), rollBoneByQuatAligned(), rollBoneByQuatJoint(), Vector_rotation_difference(), and viewrotate_apply().
void single_axis_angle_to_mat3 (float mat[3][3], const char axis, const float angle)
Definition at line 777 of file math_rotation.c.
References assert, cosf, and sinf.
Referenced by C_Matrix_Rotation().
void sub_qt_qtqt (float q[4], const float q1[4], const float q2[4])
Definition at line 138 of file math_rotation.c.
References mul_qt_qtqt().
Referenced by explodeMesh(), pose_slide_apply_quat(), and set_crazy_vertex_quat().
void tri_to_quat (float quat[4], const float v1[3], const float v2[3], const float v3[3])
Definition at line 594 of file math_rotation.c.
References angle(), KDL::atan2(), co, cos(), invert_m3_m3(), mul_m3_v3(), mul_qt_qtqt(), normal_tri_v3(), normalize_v3(), quat_to_mat3(), saacos(), si, sin(), and sub_v3_v3v3().
Referenced by face_duplilist(), make_bevel_list_3D_tangent(), ob_parvert3(), and set_crazy_vertex_quat().
void unit_axis_angle (float axis[3], float * angle)
Definition at line 41 of file math_rotation.c.
Referenced by add_only_object(), apply_armature_pose2bones_exec(), apply_objects_internal(), do_versions(), object_clear_rot(), pchan_clear_rot(), rest_pose(), and verify_pose_channel().
void unit_qt (float q[4])
Definition at line 49 of file math_rotation.c.
Referenced by add_metaball_element(), add_only_object(), apply_armature_pose2bones_exec(), apply_objects_internal(), axis_angle_to_quat(), cache_key_incremental_rotation(), do_versions(), object_clear_rot(), offset_child(), pchan_clear_rot(), psys_get_birth_coordinates(), psys_thread_create_path(), Quaternion_CreatePyObject(), Quaternion_identity(), repositionBone(), rest_pose(), vec_rot_to_quat(), and verify_pose_channel().
void vec_apply_track (float vec[3], short axis)
Definition at line 1703 of file math_rotation.c.
References assert, and copy_v3_v3().
Referenced by calc_curve_deform().
void vec_rot_to_mat3 (float mat[][3], const float vec[3], const float phi)
Definition at line 825 of file math_rotation.c.
References co, cos(), si, and sin().
void vec_rot_to_mat4 (float mat[][4], const float vec[3], const float phi)
Definition at line 851 of file math_rotation.c.
References copy_m4_m3(), unit_m4(), and vec_rot_to_mat3().
void vec_rot_to_quat (float * quat, const float vec[3], const float phi)
Definition at line 861 of file math_rotation.c.
References cos(), normalize_v3(), si, sin(), and unit_qt().
void vec_to_quat (float q[4], const float vec[3], short axis, const short upflag)
Definition at line 405 of file math_rotation.c.
References angle(), assert, KDL::atan2(), co, cos(), cosf, fabs(), mul_qt_qtqt(), normalize_v3(), quat_to_mat3(), saacos(), si, sin(), sinf, and sqrt().
Referenced by BKE_ptcache_make_particle_key(), followpath_get_tarmat(), make_bevel_list_3D_minimum_twist(), make_bevel_list_3D_zup(), make_bevel_list_segment_3D(), makeBevelList(), new_particle_duplilist(), ob_parcurve(), psys_get_birth_coordinates(), ptcache_particle_interpolate(), Vector_to_track_quat(), and vertex_dupli__mapFunc().
Variable Documentation
RotOrderInfo rotOrders[] [static]
Initial value:
 {
    {{0, 1, 2}, 0},
    {{0, 2, 1}, 1},
    {{1, 0, 2}, 1},
    {{1, 2, 0}, 0},
    {{2, 0, 1}, 0},
    {{2, 1, 0}, 1}
}
Definition at line 1184 of file math_rotation.c.