Blender: rna_userdef.c File Reference
rna_userdef.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_curve_types.h"
#include "DNA_space_types.h"
#include "DNA_userdef_types.h"
#include "DNA_brush_types.h"
#include "DNA_view3d_types.h"
#include "DNA_scene_types.h"
#include "WM_api.h"
#include "WM_types.h"
#include "BLI_utildefines.h"
#include "BLF_translation.h"
#include "BKE_sound.h"
Functions
static void rna_def_userdef_theme_ui_font_style (BlenderRNA *brna)
static void rna_def_userdef_theme_ui_style (BlenderRNA *brna)
static void rna_def_userdef_theme_ui_wcol (BlenderRNA *brna)
static void rna_def_userdef_theme_ui_wcol_state (BlenderRNA *brna)
static void rna_def_userdef_theme_ui_panel (BlenderRNA *brna)
static void rna_def_userdef_theme_ui (BlenderRNA *brna)
static void rna_def_userdef_theme_space_generic (BlenderRNA *brna)
static void rna_def_userdef_theme_space_list_generic (BlenderRNA *brna)
static void rna_def_userdef_theme_spaces_main (StructRNA *srna)
static void rna_def_userdef_theme_spaces_list_main (StructRNA *srna)
static void rna_def_userdef_theme_spaces_vertex (StructRNA *srna)
static void rna_def_userdef_theme_spaces_edge (StructRNA *srna)
static void rna_def_userdef_theme_spaces_face (StructRNA *srna)
static void rna_def_userdef_theme_spaces_curves (StructRNA *srna, short incl_nurbs)
static void rna_def_userdef_theme_space_view3d (BlenderRNA *brna)
static void rna_def_userdef_theme_space_graph (BlenderRNA *brna)
static void rna_def_userdef_theme_space_file (BlenderRNA *brna)
static void rna_def_userdef_theme_space_outliner (BlenderRNA *brna)
static void rna_def_userdef_theme_space_userpref (BlenderRNA *brna)
static void rna_def_userdef_theme_space_console (BlenderRNA *brna)
static void rna_def_userdef_theme_space_info (BlenderRNA *brna)
static void rna_def_userdef_theme_space_text (BlenderRNA *brna)
static void rna_def_userdef_theme_space_node (BlenderRNA *brna)
static void rna_def_userdef_theme_space_logic (BlenderRNA *brna)
static void rna_def_userdef_theme_space_buts (BlenderRNA *brna)
static void rna_def_userdef_theme_space_time (BlenderRNA *brna)
static void rna_def_userdef_theme_space_image (BlenderRNA *brna)
static void rna_def_userdef_theme_space_seq (BlenderRNA *brna)
static void rna_def_userdef_theme_space_action (BlenderRNA *brna)
static void rna_def_userdef_theme_space_nla (BlenderRNA *brna)
static void rna_def_userdef_theme_colorset (BlenderRNA *brna)
static void rna_def_userdef_theme_space_clip (BlenderRNA *brna)
static void rna_def_userdef_themes (BlenderRNA *brna)
static void rna_def_userdef_addon (BlenderRNA *brna)
static void rna_def_userdef_dothemes (BlenderRNA *brna)
static void rna_def_userdef_solidlight (BlenderRNA *brna)
static void rna_def_userdef_view (BlenderRNA *brna)
static void rna_def_userdef_edit (BlenderRNA *brna)
static void rna_def_userdef_system (BlenderRNA *brna)
static void rna_def_userdef_input (BlenderRNA *brna)
static void rna_def_userdef_filepaths (BlenderRNA *brna)
void rna_def_userdef_addon_collection (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_userdef (BlenderRNA *brna)
Detailed Description
Definition in file rna_userdef.c.
Function Documentation
void RNA_def_userdef (BlenderRNA * brna)
Definition at line 3476 of file rna_userdef.c.
References NULL, PROP_COLLECTION, PROP_ENUM, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_collection_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_addon(), rna_def_userdef_addon_collection(), rna_def_userdef_dothemes(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_solidlight(), rna_def_userdef_system(), rna_def_userdef_view(), STRUCT_UNDO, USER_SECTION_ADDONS, USER_SECTION_EDIT, USER_SECTION_FILE, USER_SECTION_INPUT, USER_SECTION_INTERFACE, USER_SECTION_SYSTEM, and USER_SECTION_THEME.
static void rna_def_userdef_addon (BlenderRNA * brna) [static]
Definition at line 2241 of file rna_userdef.c.
References NULL, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_name_property(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and STRUCT_UNDO.
Referenced by RNA_def_userdef().
void rna_def_userdef_addon_collection (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 3451 of file rna_userdef.c.
References FUNC_NO_SELF, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_ui_text(), and STRUCT_UNDO.
Referenced by RNA_def_userdef().
static void rna_def_userdef_dothemes (BlenderRNA * brna) [static]
Definition at line 2257 of file rna_userdef.c.
References rna_def_userdef_theme_colorset(), rna_def_userdef_theme_space_action(), rna_def_userdef_theme_space_buts(), rna_def_userdef_theme_space_clip(), rna_def_userdef_theme_space_console(), rna_def_userdef_theme_space_file(), rna_def_userdef_theme_space_generic(), rna_def_userdef_theme_space_graph(), rna_def_userdef_theme_space_image(), rna_def_userdef_theme_space_info(), rna_def_userdef_theme_space_list_generic(), rna_def_userdef_theme_space_logic(), rna_def_userdef_theme_space_nla(), rna_def_userdef_theme_space_node(), rna_def_userdef_theme_space_outliner(), rna_def_userdef_theme_space_seq(), rna_def_userdef_theme_space_text(), rna_def_userdef_theme_space_time(), rna_def_userdef_theme_space_userpref(), rna_def_userdef_theme_space_view3d(), rna_def_userdef_theme_ui(), rna_def_userdef_theme_ui_style(), and rna_def_userdef_themes().
Referenced by RNA_def_userdef().
static void rna_def_userdef_edit (BlenderRNA * brna) [static]
Definition at line 2548 of file rna_userdef.c.
References AUTOKEY_FLAG_AUTOMATKEY, AUTOKEY_FLAG_INSERTAVAIL, AUTOKEY_FLAG_INSERTNEEDED, AUTOKEY_FLAG_XYZ2RGB, AUTOKEY_MODE_EDITKEYS, AUTOKEY_MODE_NORMAL, AUTOKEY_ON, beztriple_interpolation_mode_items, GP_PAINT_DOSIMPLIFY, GP_PAINT_DOSMOOTH, keyframe_handle_type_items, NC_SPACE, ND_SPACE_GRAPH, NULL, PROP_BOOLEAN, PROP_COLOR_GAMMA, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_nested(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), STRUCT_UNDO, USER_ADD_EDITMODE, USER_ADD_VIEWALIGNED, USER_DUP_ACT, USER_DUP_ARM, USER_DUP_CURVE, USER_DUP_FONT, USER_DUP_IPO, USER_DUP_LAMP, USER_DUP_MAT, USER_DUP_MBALL, USER_DUP_MESH, USER_DUP_PSYS, USER_DUP_SURF, USER_DUP_TEX, USER_GLOBALUNDO, USER_MAT_ON_OB, USER_NONEGFRAMES, and USER_RELEASECONFIRM.
Referenced by RNA_def_userdef().
static void rna_def_userdef_filepaths (BlenderRNA * brna) [static]
Definition at line 3318 of file rna_userdef.c.
References NULL, PROP_BOOLEAN, PROP_DIRPATH, PROP_ENUM, PROP_FILEPATH, PROP_INT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_default(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_nested(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), STRUCT_UNDO, USER_AUTOSAVE, USER_FILECOMPRESS, USER_FILENOUI, USER_FILTERFILEEXTS, USER_HIDE_DOT, USER_HIDE_RECENT, USER_RELPATHS, USER_SAVE_PREVIEWS, and USER_SHOW_THUMBNAILS.
Referenced by RNA_def_userdef().
static void rna_def_userdef_input (BlenderRNA * brna) [static]
Definition at line 3146 of file rna_userdef.c.
References NDOF_FLY_HELICOPTER, NDOF_LOCK_HORIZON, NDOF_PANX_INVERT_AXIS, NDOF_PANY_INVERT_AXIS, NDOF_PANZ_INVERT_AXIS, NDOF_ROLL_INVERT_AXIS, NDOF_ROTATE_INVERT_AXIS, NDOF_SHOW_GUIDE, NDOF_TILT_INVERT_AXIS, NDOF_ZOOM_INVERT, NDOF_ZOOM_UPDOWN, NULL, PROP_BOOLEAN, PROP_DIRPATH, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_nested(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), STRUCT_UNDO, USER_CONTINUOUS_MOUSE, USER_LMOUSESELECT, USER_MMB_PASTE, USER_NONUMPAD, USER_TRACKBALL, USER_TWOBUTTONMOUSE, USER_WHEELZOOMDIR, USER_ZOOM_CONT, USER_ZOOM_DOLLY, USER_ZOOM_HORIZ, USER_ZOOM_INVERT, and USER_ZOOM_SCALE.
Referenced by RNA_def_userdef().
static void rna_def_userdef_solidlight (BlenderRNA * brna) [static]
Definition at line 2287 of file rna_userdef.c.
References NULL, PROP_BOOLEAN, PROP_COLOR, PROP_DIRECTION, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_float_array_default(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and STRUCT_UNDO.
Referenced by RNA_def_userdef().
static void rna_def_userdef_system (BlenderRNA * brna) [static]
Definition at line 2761 of file rna_userdef.c.
References N_, NC_WINDOW, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_ENUM_NO_CONTEXT, PROP_FLOAT, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_sdna(), RNA_def_property_enum_default(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_maxlength(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_nested(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), STRUCT_UNDO, USER_ALLWINCODECS, USER_CP_CIRCLE, USER_CP_SQUARE_HS, USER_CP_SQUARE_HV, USER_CP_SQUARE_SV, USER_CUSTOM_RANGE, USER_DISABLE_AA, USER_DISABLE_MIPMAP, USER_DISABLE_VBO, USER_DOTRANSLATE, USER_DRAW_AUTOMATIC, USER_DRAW_FULL, USER_DRAW_OVERLAP, USER_DRAW_OVERLAP_FLIP, USER_DRAW_TRIPLE, USER_SCRIPT_AUTOEXEC_DISABLE, USER_TEXT_DISABLE_AA, USER_TR_IFACE, USER_TR_TOOLTIPS, USER_TXT_TABSTOSPACES_DISABLE, and USER_USETEXTUREFONT.
Referenced by RNA_def_userdef().
static void rna_def_userdef_theme_colorset (BlenderRNA * brna) [static]
Definition at line 1959 of file rna_userdef.c.
References NULL, PROP_BOOLEAN, PROP_COLOR_GAMMA, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), STRUCT_UNDO, and TH_WIRECOLOR_CONSTCOLS.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_action (BlenderRNA * brna) [static]
Definition at line 1815 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_list_main(), rna_def_userdef_theme_spaces_main(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_buts (BlenderRNA * brna) [static]
Definition at line 1601 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_main(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_clip (BlenderRNA * brna) [static]
Definition at line 1993 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_main(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_console (BlenderRNA * brna) [static]
Definition at line 1377 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_main(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_file (BlenderRNA * brna) [static]
Definition at line 1286 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_list_main(), rna_def_userdef_theme_spaces_main(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_generic (BlenderRNA * brna) [static]
Definition at line 748 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_graph (BlenderRNA * brna) [static]
Definition at line 1200 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_curves(), rna_def_userdef_theme_spaces_list_main(), rna_def_userdef_theme_spaces_main(), rna_def_userdef_theme_spaces_vertex(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_image (BlenderRNA * brna) [static]
Definition at line 1647 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_face(), rna_def_userdef_theme_spaces_main(), rna_def_userdef_theme_spaces_vertex(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_info (BlenderRNA * brna) [static]
Definition at line 1422 of file rna_userdef.c.
References NULL, RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_main(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_list_generic (BlenderRNA * brna) [static]
Definition at line 819 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_logic (BlenderRNA * brna) [static]
Definition at line 1580 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_main(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_nla (BlenderRNA * brna) [static]
Definition at line 1902 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_list_main(), rna_def_userdef_theme_spaces_main(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_node (BlenderRNA * brna) [static]
Definition at line 1509 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_int_default(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_list_main(), rna_def_userdef_theme_spaces_main(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_outliner (BlenderRNA * brna) [static]
Definition at line 1338 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_main(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_seq (BlenderRNA * brna) [static]
Definition at line 1711 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_main(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_text (BlenderRNA * brna) [static]
Definition at line 1437 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_main(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_time (BlenderRNA * brna) [static]
Definition at line 1621 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_main(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_userpref (BlenderRNA * brna) [static]
Definition at line 1363 of file rna_userdef.c.
References NULL, RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_main(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_space_view3d (BlenderRNA * brna) [static]
Definition at line 1052 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_spaces_curves(), rna_def_userdef_theme_spaces_edge(), rna_def_userdef_theme_spaces_face(), rna_def_userdef_theme_spaces_main(), rna_def_userdef_theme_spaces_vertex(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_spaces_curves (StructRNA * srna, short incl_nurbs) [static]
Definition at line 946 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_userdef_theme_space_graph(), and rna_def_userdef_theme_space_view3d().
static void rna_def_userdef_theme_spaces_edge (StructRNA * srna) [static]
Definition at line 891 of file rna_userdef.c.
References PROP_COLOR_GAMMA, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_userdef_theme_space_view3d().
static void rna_def_userdef_theme_spaces_face (StructRNA * srna) [static]
Definition at line 921 of file rna_userdef.c.
References PROP_COLOR_GAMMA, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_range(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_userdef_theme_space_image(), and rna_def_userdef_theme_space_view3d().
static void rna_def_userdef_theme_spaces_list_main (StructRNA * srna) [static]
Definition at line 860 of file rna_userdef.c.
References NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), and RNA_def_property_ui_text().
Referenced by rna_def_userdef_theme_space_action(), rna_def_userdef_theme_space_file(), rna_def_userdef_theme_space_graph(), rna_def_userdef_theme_space_nla(), and rna_def_userdef_theme_space_node().
static void rna_def_userdef_theme_spaces_main (StructRNA * srna) [static]
Definition at line 849 of file rna_userdef.c.
References NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), and RNA_def_property_ui_text().
Referenced by rna_def_userdef_theme_space_action(), rna_def_userdef_theme_space_buts(), rna_def_userdef_theme_space_clip(), rna_def_userdef_theme_space_console(), rna_def_userdef_theme_space_file(), rna_def_userdef_theme_space_graph(), rna_def_userdef_theme_space_image(), rna_def_userdef_theme_space_info(), rna_def_userdef_theme_space_logic(), rna_def_userdef_theme_space_nla(), rna_def_userdef_theme_space_node(), rna_def_userdef_theme_space_outliner(), rna_def_userdef_theme_space_seq(), rna_def_userdef_theme_space_text(), rna_def_userdef_theme_space_time(), rna_def_userdef_theme_space_userpref(), and rna_def_userdef_theme_space_view3d().
static void rna_def_userdef_theme_spaces_vertex (StructRNA * srna) [static]
Definition at line 871 of file rna_userdef.c.
References PROP_COLOR_GAMMA, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_range(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_userdef_theme_space_graph(), rna_def_userdef_theme_space_image(), and rna_def_userdef_theme_space_view3d().
static void rna_def_userdef_theme_ui (BlenderRNA * brna) [static]
Definition at line 630 of file rna_userdef.c.
References NULL, PROP_FACTOR, PROP_FILEPATH, PROP_FLOAT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_ui_panel(), rna_def_userdef_theme_ui_wcol(), rna_def_userdef_theme_ui_wcol_state(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_ui_font_style (BlenderRNA * brna) [static]
Definition at line 408 of file rna_userdef.c.
References NULL, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and STRUCT_UNDO.
Referenced by rna_def_userdef_theme_ui_style().
static void rna_def_userdef_theme_ui_panel (BlenderRNA * brna) [static]
Definition at line 611 of file rna_userdef.c.
References NULL, PROP_BOOLEAN, PROP_COLOR_GAMMA, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and STRUCT_UNDO.
Referenced by rna_def_userdef_theme_ui().
static void rna_def_userdef_theme_ui_style (BlenderRNA * brna) [static]
Definition at line 462 of file rna_userdef.c.
References NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_theme_ui_font_style(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_theme_ui_wcol (BlenderRNA * brna) [static]
Definition at line 510 of file rna_userdef.c.
References NULL, PROP_BOOLEAN, PROP_COLOR_GAMMA, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and STRUCT_UNDO.
Referenced by rna_def_userdef_theme_ui().
static void rna_def_userdef_theme_ui_wcol_state (BlenderRNA * brna) [static]
Definition at line 566 of file rna_userdef.c.
References NULL, PROP_COLOR_GAMMA, PROP_FACTOR, PROP_FLOAT, RNA_def_property(), RNA_def_property_array(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and STRUCT_UNDO.
Referenced by rna_def_userdef_theme_ui().
static void rna_def_userdef_themes (BlenderRNA * brna) [static]
Definition at line 2082 of file rna_userdef.c.
References NULL, PROP_COLLECTION, PROP_ENUM, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_SKIP_SAVE, PROP_STRING, RNA_def_property(), RNA_def_property_collection_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_name_property(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and STRUCT_UNDO.
Referenced by rna_def_userdef_dothemes().
static void rna_def_userdef_view (BlenderRNA * brna) [static]
Definition at line 2323 of file rna_userdef.c.
References NULL, PROP_BOOLEAN, PROP_ENUM, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_default(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_nested(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), STRUCT_UNDO, USER_AUTOPERSP, USER_CAM_LOCK_NO_PARENT, USER_DRAWVIEWINFO, USER_LOCKAROUND, USER_MENUFIXEDORDER, USER_MENUOPENAUTO, USER_ORBIT_SELECTION, USER_ORBIT_ZBUF, USER_PLAINMENUS, USER_QUIT_PROMPT, USER_SCENEGLOBAL, USER_SHOW_FPS, USER_SHOW_ROTVIEWICON, USER_SHOW_VIEWPORTNAME, USER_SPLASH_DISABLE, USER_TIMECODE_MILLISECONDS, USER_TIMECODE_MINIMAL, USER_TIMECODE_SECONDS_ONLY, USER_TIMECODE_SMPTE_FULL, USER_TIMECODE_SMPTE_MSF, USER_TOOLTIPS, USER_TOOLTIPS_PYTHON, USER_ZOOM_TO_MOUSEPOS, and V3D_USE_MANIPULATOR.
Referenced by RNA_def_userdef().