Blender: anim_channels_defines.c File Reference
anim_channels_defines.c File Reference
animation
#include <stdio.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "DNA_anim_types.h"
#include "DNA_armature_types.h"
#include "DNA_camera_types.h"
#include "DNA_object_types.h"
#include "DNA_particle_types.h"
#include "DNA_screen_types.h"
#include "DNA_scene_types.h"
#include "DNA_space_types.h"
#include "DNA_key_types.h"
#include "DNA_lamp_types.h"
#include "DNA_lattice_types.h"
#include "DNA_mesh_types.h"
#include "DNA_material_types.h"
#include "DNA_meta_types.h"
#include "DNA_node_types.h"
#include "DNA_world_types.h"
#include "DNA_gpencil_types.h"
#include "DNA_speaker_types.h"
#include "RNA_access.h"
#include "BKE_curve.h"
#include "BKE_key.h"
#include "BKE_context.h"
#include "BKE_utildefines.h"
#include "UI_interface.h"
#include "UI_interface_icons.h"
#include "UI_resources.h"
#include "ED_anim_api.h"
#include "ED_keyframing.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "WM_api.h"
#include "WM_types.h"
Defines
#define EXTRA_SCROLL_PAD 100.0f
#define INDENT_STEP_SIZE 7
#define ANIM_CHAN_NAME_SIZE 256
#define GET_ACF_FLAG_PTR(ptr, type) ((*(type) = sizeof((ptr))), &(ptr))
#define ACF_SETTING_SET(sval, sflag, smode)
#define ICON_WIDTH 17
#define SLIDER_WIDTH 80
#define RENAME_TEXT_WIDTH 100
Functions
static void acf_generic_root_color (bAnimContext *UNUSED(ac), bAnimListElem *UNUSED(ale), float *color)
static void acf_generic_root_backdrop (bAnimContext *ac, bAnimListElem *ale, float yminc, float ymaxc)
static void acf_generic_dataexpand_color (bAnimContext *UNUSED(ac), bAnimListElem *UNUSED(ale), float *color)
static void acf_generic_dataexpand_backdrop (bAnimContext *ac, bAnimListElem *ale, float yminc, float ymaxc)
static void acf_generic_channel_color (bAnimContext *ac, bAnimListElem *ale, float *color)
static void acf_generic_channel_backdrop (bAnimContext *ac, bAnimListElem *ale, float yminc, float ymaxc)
static short acf_generic_indention_0 (bAnimContext *UNUSED(ac), bAnimListElem *UNUSED(ale))
static short acf_generic_indention_1 (bAnimContext *UNUSED(ac), bAnimListElem *UNUSED(ale))
static short acf_generic_indention_flexible (bAnimContext *UNUSED(ac), bAnimListElem *ale)
static short acf_generic_basic_offset (bAnimContext *ac, bAnimListElem *ale)
static short acf_nodetree_rootType_offset (bNodeTree *ntree)
static short acf_generic_group_offset (bAnimContext *ac, bAnimListElem *ale)
static void acf_generic_idblock_name (bAnimListElem *ale, char *name)
static short acf_generic_idblock_nameprop (bAnimListElem *ale, PointerRNA *ptr, PropertyRNA **prop)
static short acf_generic_idfill_nameprop (bAnimListElem *ale, PointerRNA *ptr, PropertyRNA **prop)
static short acf_generic_dataexpand_setting_valid (bAnimContext *ac, bAnimListElem *UNUSED(ale), int setting)
static void acf_summary_color (bAnimContext *UNUSED(ac), bAnimListElem *UNUSED(ale), float *color)
static void acf_summary_backdrop (bAnimContext *ac, bAnimListElem *ale, float yminc, float ymaxc)
static void acf_summary_name (bAnimListElem *UNUSED(ale), char *name)
static int acf_summary_icon (bAnimListElem *UNUSED(ale))
static short acf_summary_setting_valid (bAnimContext *UNUSED(ac), bAnimListElem *UNUSED(ale), int setting)
static int acf_summary_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_summary_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_scene_icon (bAnimListElem *UNUSED(ale))
static short acf_scene_setting_valid (bAnimContext *ac, bAnimListElem *UNUSED(ale), int setting)
static int acf_scene_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_scene_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_object_icon (bAnimListElem *ale)
static void acf_object_name (bAnimListElem *ale, char *name)
static short acf_object_setting_valid (bAnimContext *ac, bAnimListElem *ale, int setting)
static int acf_object_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_object_setting_ptr (bAnimListElem *ale, int setting, short *type)
static void acf_group_color (bAnimContext *UNUSED(ac), bAnimListElem *ale, float *color)
static void acf_group_backdrop (bAnimContext *ac, bAnimListElem *ale, float yminc, float ymaxc)
static void acf_group_name (bAnimListElem *ale, char *name)
static short acf_group_name_prop (bAnimListElem *ale, PointerRNA *ptr, PropertyRNA **prop)
static short acf_group_setting_valid (bAnimContext *ac, bAnimListElem *UNUSED(ale), int setting)
static int acf_group_setting_flag (bAnimContext *ac, int setting, short *neg)
static void * acf_group_setting_ptr (bAnimListElem *ale, int UNUSED(setting), short *type)
static void acf_fcurve_name (bAnimListElem *ale, char *name)
static short acf_fcurve_setting_valid (bAnimContext *ac, bAnimListElem *ale, int setting)
static int acf_fcurve_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_fcurve_setting_ptr (bAnimListElem *ale, int UNUSED(setting), short *type)
static int acf_fillactd_icon (bAnimListElem *UNUSED(ale))
static short acf_fillactd_setting_valid (bAnimContext *UNUSED(ac), bAnimListElem *UNUSED(ale), int setting)
static int acf_fillactd_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_fillactd_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_filldrivers_icon (bAnimListElem *UNUSED(ale))
static void acf_filldrivers_name (bAnimListElem *UNUSED(ale), char *name)
static short acf_filldrivers_setting_valid (bAnimContext *UNUSED(ac), bAnimListElem *UNUSED(ale), int setting)
static int acf_filldrivers_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_filldrivers_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_dsmat_icon (bAnimListElem *UNUSED(ale))
static int acf_dsmat_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_dsmat_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_dslam_icon (bAnimListElem *UNUSED(ale))
static int acf_dslam_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_dslam_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_dstex_icon (bAnimListElem *UNUSED(ale))
static short acf_dstex_offset (bAnimContext *UNUSED(ac), bAnimListElem *UNUSED(ale))
static int acf_dstex_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_dstex_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_dscam_icon (bAnimListElem *UNUSED(ale))
static int acf_dscam_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_dscam_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_dscur_icon (bAnimListElem *ale)
static int acf_dscur_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_dscur_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_dsskey_icon (bAnimListElem *UNUSED(ale))
static int acf_dsskey_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_dsskey_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_dswor_icon (bAnimListElem *UNUSED(ale))
static int acf_dswor_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_dswor_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_dspart_icon (bAnimListElem *UNUSED(ale))
static int acf_dspart_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_dspart_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_dsmball_icon (bAnimListElem *UNUSED(ale))
static int acf_dsmball_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_dsmball_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_dsarm_icon (bAnimListElem *UNUSED(ale))
static int acf_dsarm_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_dsarm_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_dsntree_icon (bAnimListElem *UNUSED(ale))
static short acf_dsntree_offset (bAnimContext *ac, bAnimListElem *ale)
static int acf_dsntree_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_dsntree_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_dsmesh_icon (bAnimListElem *UNUSED(ale))
static int acf_dsmesh_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_dsmesh_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_dslat_icon (bAnimListElem *UNUSED(ale))
static int acf_dslat_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_dslat_setting_ptr (bAnimListElem *ale, int setting, short *type)
static int acf_dsspk_icon (bAnimListElem *UNUSED(ale))
static int acf_dsspk_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_dsspk_setting_ptr (bAnimListElem *ale, int setting, short *type)
static void acf_shapekey_name (bAnimListElem *ale, char *name)
static short acf_shapekey_nameprop (bAnimListElem *ale, PointerRNA *ptr, PropertyRNA **prop)
static short acf_shapekey_setting_valid (bAnimContext *UNUSED(ac), bAnimListElem *UNUSED(ale), int setting)
static int acf_shapekey_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_shapekey_setting_ptr (bAnimListElem *ale, int setting, short *type)
static void acf_gpd_color (bAnimContext *UNUSED(ac), bAnimListElem *UNUSED(ale), float *color)
static int acf_gpd_icon (bAnimListElem *UNUSED(ale))
static short acf_gpd_setting_valid (bAnimContext *UNUSED(ac), bAnimListElem *UNUSED(ale), int setting)
static int acf_gpd_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_gpd_setting_ptr (bAnimListElem *ale, int UNUSED(setting), short *type)
static void acf_gpl_name (bAnimListElem *ale, char *name)
static short acf_gpl_name_prop (bAnimListElem *ale, PointerRNA *ptr, PropertyRNA **prop)
static short acf_gpl_setting_valid (bAnimContext *UNUSED(ac), bAnimListElem *UNUSED(ale), int setting)
static int acf_gpl_setting_flag (bAnimContext *UNUSED(ac), int setting, short *neg)
static void * acf_gpl_setting_ptr (bAnimListElem *ale, int UNUSED(setting), short *type)
static void ANIM_init_channel_typeinfo_data (void)
bAnimChannelType * ANIM_channel_get_typeinfo (bAnimListElem *ale)
void ANIM_channel_debug_print_info (bAnimListElem *ale, short indent_level)
short ANIM_channel_setting_get (bAnimContext *ac, bAnimListElem *ale, int setting)
void ANIM_channel_setting_set (bAnimContext *ac, bAnimListElem *ale, int setting, short mode)
void ANIM_channel_draw (bAnimContext *ac, bAnimListElem *ale, float yminc, float ymaxc)
static void achannel_setting_widget_cb (bContext *C, void *UNUSED(arg1), void *UNUSED(arg2))
static void achannel_setting_flush_widget_cb (bContext *C, void *ale_npoin, void *setting_wrap)
static void achannel_setting_rename_done_cb (bContext *C, void *ads_poin, void *UNUSED(arg2))
static void achannel_setting_slider_cb (bContext *C, void *id_poin, void *fcu_poin)
static void achannel_setting_slider_shapekey_cb (bContext *C, void *key_poin, void *kb_poin)
static void draw_setting_widget (bAnimContext *ac, bAnimListElem *ale, bAnimChannelType *acf, uiBlock *block, int xpos, int ypos, int setting)
void ANIM_channel_draw_widgets (bContext *C, bAnimContext *ac, bAnimListElem *ale, uiBlock *block, float yminc, float ymaxc, size_t channel_index)
Variables
static bAnimChannelType ACF_SUMMARY
static bAnimChannelType ACF_SCENE
static bAnimChannelType ACF_OBJECT
static bAnimChannelType ACF_GROUP
static bAnimChannelType ACF_FCURVE
static bAnimChannelType ACF_FILLACTD
static bAnimChannelType ACF_FILLDRIVERS
static bAnimChannelType ACF_DSMAT
static bAnimChannelType ACF_DSLAM
static bAnimChannelType ACF_DSTEX
static bAnimChannelType ACF_DSCAM
static bAnimChannelType ACF_DSCUR
static bAnimChannelType ACF_DSSKEY
static bAnimChannelType ACF_DSWOR
static bAnimChannelType ACF_DSPART
static bAnimChannelType ACF_DSMBALL
static bAnimChannelType ACF_DSARM
static bAnimChannelType ACF_DSNTREE
static bAnimChannelType ACF_DSMESH
static bAnimChannelType ACF_DSLAT
static bAnimChannelType ACF_DSSPK
static bAnimChannelType ACF_SHAPEKEY
static bAnimChannelType ACF_GPD
static bAnimChannelType ACF_GPL
static bAnimChannelType * animchannelTypeInfo [ANIMTYPE_NUM_TYPES]
static short ACF_INIT = 1
Detailed Description
Definition in file anim_channels_defines.c.
Define Documentation
#define ACF_SETTING_SET (sval, sflag, smode)
Value:
{\
        if (negflag) {\
            if (smode == ACHANNEL_SETFLAG_INVERT)   (sval) ^= (sflag); \
            else if (smode == ACHANNEL_SETFLAG_ADD) (sval) &= ~(sflag); \
            else                                    (sval) |= (sflag); \
        } \
        else {\
            if (smode == ACHANNEL_SETFLAG_INVERT)   (sval) ^= (sflag); \
            else if (smode == ACHANNEL_SETFLAG_ADD) (sval) |= (sflag); \
            else                                    (sval) &= ~(sflag); \
        }\
    }
Definition at line 2654 of file anim_channels_defines.c.
Referenced by ANIM_channel_setting_set().
#define ANIM_CHAN_NAME_SIZE 256
Definition at line 87 of file anim_channels_defines.c.
Referenced by acf_filldrivers_name(), acf_generic_idblock_name(), acf_gpl_name(), acf_group_name(), acf_object_name(), acf_shapekey_name(), acf_summary_name(), ANIM_channel_debug_print_info(), and ANIM_channel_draw().
#define EXTRA_SCROLL_PAD 100.0f
Definition at line 82 of file anim_channels_defines.c.
Referenced by acf_generic_channel_backdrop(), acf_generic_dataexpand_backdrop(), acf_generic_root_backdrop(), acf_group_backdrop(), acf_summary_backdrop(), and ANIM_channel_draw().
#define GET_ACF_FLAG_PTR (ptr, type) ((*(type) = sizeof((ptr))), &(ptr))
Definition at line 92 of file anim_channels_defines.c.
Referenced by acf_dsarm_setting_ptr(), acf_dscam_setting_ptr(), acf_dscur_setting_ptr(), acf_dslam_setting_ptr(), acf_dslat_setting_ptr(), acf_dsmat_setting_ptr(), acf_dsmball_setting_ptr(), acf_dsmesh_setting_ptr(), acf_dsntree_setting_ptr(), acf_dspart_setting_ptr(), acf_dsskey_setting_ptr(), acf_dsspk_setting_ptr(), acf_dstex_setting_ptr(), acf_dswor_setting_ptr(), acf_fcurve_setting_ptr(), acf_fillactd_setting_ptr(), acf_filldrivers_setting_ptr(), acf_gpd_setting_ptr(), acf_gpl_setting_ptr(), acf_group_setting_ptr(), acf_object_setting_ptr(), acf_scene_setting_ptr(), acf_shapekey_setting_ptr(), and acf_summary_setting_ptr().
#define ICON_WIDTH 17
Definition at line 2717 of file anim_channels_defines.c.
Referenced by ANIM_channel_draw(), ANIM_channel_draw_widgets(), and draw_setting_widget().
#define INDENT_STEP_SIZE 7
Definition at line 85 of file anim_channels_defines.c.
Referenced by acf_generic_basic_offset(), and acf_nodetree_rootType_offset().
#define RENAME_TEXT_WIDTH 100
Definition at line 2721 of file anim_channels_defines.c.
Referenced by ANIM_channel_draw_widgets().
#define SLIDER_WIDTH 80
Definition at line 2719 of file anim_channels_defines.c.
Referenced by ANIM_channel_draw(), and ANIM_channel_draw_widgets().
Function Documentation
static int acf_dsarm_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 1822 of file anim_channels_defines.c.
static int acf_dsarm_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 1828 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, ADT_UI_SELECTED, and ARM_DS_EXPAND.
static void* acf_dsarm_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 1853 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, bArmature::adt, bAnimListElem::data, AnimData::flag, bArmature::flag, GET_ACF_FLAG_PTR, and NULL.
static int acf_dscam_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 1350 of file anim_channels_defines.c.
static int acf_dscam_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 1356 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, ADT_UI_SELECTED, and CAM_DS_EXPAND.
static void* acf_dscam_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 1381 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, Camera::adt, bAnimListElem::data, AnimData::flag, Camera::flag, GET_ACF_FLAG_PTR, and NULL.
static int acf_dscur_icon (bAnimListElem * ale) [static]
Definition at line 1427 of file anim_channels_defines.c.
References curve_type(), bAnimListElem::data, OB_FONT, and OB_SURF.
static int acf_dscur_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 1443 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, ADT_UI_SELECTED, and CU_DS_EXPAND.
static void* acf_dscur_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 1468 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, Curve::adt, bAnimListElem::data, Curve::flag, AnimData::flag, GET_ACF_FLAG_PTR, and NULL.
static int acf_dslam_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 1189 of file anim_channels_defines.c.
static int acf_dslam_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 1195 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, ADT_UI_SELECTED, and LA_DS_EXPAND.
static void* acf_dslam_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 1220 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, Lamp::adt, bAnimListElem::data, AnimData::flag, Lamp::flag, GET_ACF_FLAG_PTR, and NULL.
static int acf_dslat_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 2064 of file anim_channels_defines.c.
static int acf_dslat_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 2070 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, ADT_UI_SELECTED, and LT_DS_EXPAND.
static void* acf_dslat_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 2095 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, Lattice::adt, bAnimListElem::data, AnimData::flag, Lattice::flag, GET_ACF_FLAG_PTR, and NULL.
static int acf_dsmat_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 1112 of file anim_channels_defines.c.
static int acf_dsmat_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 1118 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, ADT_UI_SELECTED, and MA_DS_EXPAND.
static void* acf_dsmat_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 1143 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, Material::adt, bAnimListElem::data, AnimData::flag, Material::flag, GET_ACF_FLAG_PTR, and NULL.
static int acf_dsmball_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 1745 of file anim_channels_defines.c.
static int acf_dsmball_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 1751 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, ADT_UI_SELECTED, and MB_DS_EXPAND.
static void* acf_dsmball_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 1776 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, MetaBall::adt, bAnimListElem::data, MetaBall::flag, AnimData::flag, GET_ACF_FLAG_PTR, and NULL.
static int acf_dsmesh_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 1987 of file anim_channels_defines.c.
static int acf_dsmesh_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 1993 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, ADT_UI_SELECTED, and ME_DS_EXPAND.
static void* acf_dsmesh_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 2018 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, Mesh::adt, bAnimListElem::data, AnimData::flag, Mesh::flag, GET_ACF_FLAG_PTR, and NULL.
static int acf_dsntree_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 1899 of file anim_channels_defines.c.
static short acf_dsntree_offset (bAnimContext * ac, bAnimListElem * ale) [static]
Definition at line 1905 of file anim_channels_defines.c.
References acf_generic_basic_offset(), acf_nodetree_rootType_offset(), and bAnimListElem::data.
static int acf_dsntree_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 1916 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, ADT_UI_SELECTED, and NTREE_DS_EXPAND.
static void* acf_dsntree_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 1941 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, bNodeTree::adt, bAnimListElem::data, AnimData::flag, bNodeTree::flag, GET_ACF_FLAG_PTR, and NULL.
static int acf_dspart_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 1668 of file anim_channels_defines.c.
static int acf_dspart_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 1674 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, ADT_UI_SELECTED, and PART_DS_EXPAND.
static void* acf_dspart_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 1699 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ParticleSettings::adt, bAnimListElem::data, ParticleSettings::flag, AnimData::flag, GET_ACF_FLAG_PTR, and NULL.
static int acf_dsskey_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 1514 of file anim_channels_defines.c.
static int acf_dsskey_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 1520 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, ADT_UI_SELECTED, and KEY_DS_EXPAND.
static void* acf_dsskey_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 1545 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, Key::adt, bAnimListElem::data, AnimData::flag, Key::flag, GET_ACF_FLAG_PTR, and NULL.
static int acf_dsspk_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 2141 of file anim_channels_defines.c.
static int acf_dsspk_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 2147 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, ADT_UI_SELECTED, and SPK_DS_EXPAND.
static void* acf_dsspk_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 2172 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, Speaker::adt, bAnimListElem::data, AnimData::flag, Speaker::flag, GET_ACF_FLAG_PTR, and NULL.
static int acf_dstex_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 1266 of file anim_channels_defines.c.
static short acf_dstex_offset (bAnimContext * UNUSEDac, bAnimListElem * UNUSEDale) [static]
Definition at line 1273 of file anim_channels_defines.c.
static int acf_dstex_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 1279 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, ADT_UI_SELECTED, and TEX_DS_EXPAND.
static void* acf_dstex_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 1304 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, Tex::adt, bAnimListElem::data, AnimData::flag, Tex::flag, GET_ACF_FLAG_PTR, and NULL.
static int acf_dswor_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 1591 of file anim_channels_defines.c.
static int acf_dswor_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 1597 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, ADT_UI_SELECTED, and WO_DS_EXPAND.
static void* acf_dswor_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 1622 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, World::adt, bAnimListElem::data, World::flag, AnimData::flag, GET_ACF_FLAG_PTR, and NULL.
static void acf_fcurve_name (bAnimListElem * ale, char * name) [static]
Definition at line 860 of file anim_channels_defines.c.
References bAnimListElem::data, getname_anim_fcurve(), and bAnimListElem::id.
static int acf_fcurve_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 892 of file anim_channels_defines.c.
References ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_PROTECT, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, FCURVE_MUTED, FCURVE_PROTECTED, FCURVE_SELECTED, and FCURVE_VISIBLE.
static void* acf_fcurve_setting_ptr (bAnimListElem * ale, int UNUSEDsetting, short * type) [static]
Definition at line 917 of file anim_channels_defines.c.
References bAnimListElem::data, FCurve::flag, and GET_ACF_FLAG_PTR.
static short acf_fcurve_setting_valid (bAnimContext * ac, bAnimListElem * ale, int setting) [static]
Definition at line 866 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_PROTECT, ACHANNEL_SETTING_VISIBLE, FCurve::bezt, bAnimListElem::data, SPACE_IPO, and bAnimContext::spacetype.
static int acf_fillactd_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 947 of file anim_channels_defines.c.
static int acf_fillactd_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 967 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_SELECT, ACT_COLLAPSED, and ADT_UI_SELECTED.
static void* acf_fillactd_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 986 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_SELECT, bAnimListElem::adt, bAnimListElem::data, bAction::flag, GET_ACF_FLAG_PTR, and NULL.
static short acf_fillactd_setting_valid (bAnimContext * UNUSEDac, bAnimListElem * UNUSEDale, int setting) [static]
Definition at line 953 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, and ACHANNEL_SETTING_SELECT.
static int acf_filldrivers_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 1032 of file anim_channels_defines.c.
static void acf_filldrivers_name (bAnimListElem * UNUSEDale, char * name) [static]
Definition at line 1037 of file anim_channels_defines.c.
References ANIM_CHAN_NAME_SIZE, and BLI_strncpy().
static int acf_filldrivers_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 1057 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, and ADT_DRIVERS_COLLAPSED.
static void* acf_filldrivers_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 1073 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, bAnimListElem::data, AnimData::flag, GET_ACF_FLAG_PTR, and NULL.
static short acf_filldrivers_setting_valid (bAnimContext * UNUSEDac, bAnimListElem * UNUSEDale, int setting) [static]
Definition at line 1044 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND.
static short acf_generic_basic_offset (bAnimContext * ac, bAnimListElem * ale) [static]
Definition at line 248 of file anim_channels_defines.c.
References ANIM_channel_get_typeinfo(), bAnimChannelType::get_indent_level, and INDENT_STEP_SIZE.
Referenced by acf_dsntree_offset(), and acf_generic_group_offset().
static void acf_generic_channel_backdrop (bAnimContext * ac, bAnimListElem * ale, float yminc, float ymaxc) [static]
Definition at line 196 of file anim_channels_defines.c.
References ANIM_channel_get_typeinfo(), bAnimContext::ar, View2D::cur, EXTRA_SCROLL_PAD, bAnimChannelType::get_backdrop_color, bAnimChannelType::get_offset, ARegion::v2d, and rctf::xmax.
static void acf_generic_channel_color (bAnimContext * ac, bAnimListElem * ale, float * color) [static]
Definition at line 150 of file anim_channels_defines.c.
References ThemeWireColor::active, ANIM_channel_get_typeinfo(), ANIMTYPE_FCURVE, copy_v3_v3_char(), bActionGroup::cs, bActionGroup::customCol, bAnimListElem::data, SpaceAction::flag, bAnimChannelType::get_indent_level, FCurve::grp, if(), NULL, rgb_uchar_to_float(), SACTION_NODRAWGCOLORS, ThemeWireColor::select, bAnimContext::sl, ThemeWireColor::solid, SPACE_ACTION, bAnimContext::spacetype, TH_HEADER, bAnimListElem::type, and UI_GetThemeColorShade3fv().
static void acf_generic_dataexpand_backdrop (bAnimContext * ac, bAnimListElem * ale, float yminc, float ymaxc) [static]
Definition at line 134 of file anim_channels_defines.c.
References ANIM_channel_get_typeinfo(), bAnimContext::ar, View2D::cur, EXTRA_SCROLL_PAD, bAnimChannelType::get_backdrop_color, bAnimChannelType::get_offset, ARegion::v2d, and rctf::xmax.
static void acf_generic_dataexpand_color (bAnimContext * UNUSEDac, bAnimListElem * UNUSEDale, float * color) [static]
Definition at line 127 of file anim_channels_defines.c.
References TH_DOPESHEET_CHANNELSUBOB, and UI_GetThemeColor3fv().
static short acf_generic_dataexpand_setting_valid (bAnimContext * ac, bAnimListElem * UNUSEDale, int setting) [static]
Definition at line 354 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, SPACE_NLA, and bAnimContext::spacetype.
static short acf_generic_group_offset (bAnimContext * ac, bAnimListElem * ale) [static]
Definition at line 284 of file anim_channels_defines.c.
References acf_generic_basic_offset(), acf_nodetree_rootType_offset(), ANIMCONT_ACTION, bAnimContext::datatype, ELEM, GS, bAnimListElem::id, ID_MA, ID_NT, ID_PA, ID_TE, and ID::name.
static void acf_generic_idblock_name (bAnimListElem * ale, char * name) [static]
Definition at line 314 of file anim_channels_defines.c.
References ANIM_CHAN_NAME_SIZE, BLI_strncpy(), bAnimListElem::data, if(), and ID::name.
static short acf_generic_idblock_nameprop (bAnimListElem * ale, PointerRNA * ptr, PropertyRNA ** prop) [static]
Definition at line 324 of file anim_channels_defines.c.
References bAnimListElem::id, NULL, RNA_id_pointer_create(), RNA_struct_name_property(), and PointerRNA::type.
static short acf_generic_idfill_nameprop (bAnimListElem * ale, PointerRNA * ptr, PropertyRNA ** prop) [static]
Definition at line 334 of file anim_channels_defines.c.
References bAnimListElem::data, NULL, RNA_id_pointer_create(), RNA_struct_name_property(), and PointerRNA::type.
static short acf_generic_indention_0 (bAnimContext * UNUSEDac, bAnimListElem * UNUSEDale) [static]
Definition at line 214 of file anim_channels_defines.c.
static short acf_generic_indention_1 (bAnimContext * UNUSEDac, bAnimListElem * UNUSEDale) [static]
Definition at line 218 of file anim_channels_defines.c.
static short acf_generic_indention_flexible (bAnimContext * UNUSEDac, bAnimListElem * ale) [static]
Definition at line 230 of file anim_channels_defines.c.
References ANIMTYPE_FCURVE, bAnimListElem::data, FCurve::grp, if(), and bAnimListElem::type.
static void acf_generic_root_backdrop (bAnimContext * ac, bAnimListElem * ale, float yminc, float ymaxc) [static]
Definition at line 108 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ANIM_channel_get_typeinfo(), ANIM_channel_setting_get(), bAnimContext::ar, View2D::cur, EXTRA_SCROLL_PAD, bAnimChannelType::get_backdrop_color, bAnimChannelType::get_offset, UI_CNR_BOTTOM_LEFT, UI_CNR_TOP_LEFT, uiDrawBox(), uiSetRoundBox(), ARegion::v2d, and rctf::xmax.
static void acf_generic_root_color (bAnimContext * UNUSEDac, bAnimListElem * UNUSEDale, float * color) [static]
Definition at line 101 of file anim_channels_defines.c.
References TH_DOPESHEET_CHANNELOB, and UI_GetThemeColor3fv().
static void acf_gpd_color (bAnimContext * UNUSEDac, bAnimListElem * UNUSEDale, float * color) [static]
Definition at line 2325 of file anim_channels_defines.c.
References TH_DOPESHEET_CHANNELSUBOB, and UI_GetThemeColorShade3fv().
static int acf_gpd_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 2332 of file anim_channels_defines.c.
static int acf_gpd_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 2352 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_SELECT, AGRP_SELECTED, and GP_DATA_EXPAND.
static void* acf_gpd_setting_ptr (bAnimListElem * ale, int UNUSEDsetting, short * type) [static]
Definition at line 2370 of file anim_channels_defines.c.
References bAnimListElem::data, bGPdata::flag, and GET_ACF_FLAG_PTR.
static short acf_gpd_setting_valid (bAnimContext * UNUSEDac, bAnimListElem * UNUSEDale, int setting) [static]
Definition at line 2338 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, and ACHANNEL_SETTING_SELECT.
static void acf_gpl_name (bAnimListElem * ale, char * name) [static]
Definition at line 2400 of file anim_channels_defines.c.
References ANIM_CHAN_NAME_SIZE, BLI_strncpy(), bAnimListElem::data, if(), and bGPDlayer::info.
static short acf_gpl_name_prop (bAnimListElem * ale, PointerRNA * ptr, PropertyRNA ** prop) [static]
Definition at line 2409 of file anim_channels_defines.c.
References bAnimListElem::data, bAnimListElem::id, NULL, RNA_GPencilLayer, RNA_pointer_create(), RNA_struct_name_property(), and PointerRNA::type.
static int acf_gpl_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 2437 of file anim_channels_defines.c.
References ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_PROTECT, ACHANNEL_SETTING_SELECT, GP_LAYER_HIDE, GP_LAYER_LOCKED, and GP_LAYER_SELECT.
static void* acf_gpl_setting_ptr (bAnimListElem * ale, int UNUSEDsetting, short * type) [static]
Definition at line 2459 of file anim_channels_defines.c.
References bAnimListElem::data, bGPDlayer::flag, and GET_ACF_FLAG_PTR.
static short acf_gpl_setting_valid (bAnimContext * UNUSEDac, bAnimListElem * UNUSEDale, int setting) [static]
Definition at line 2422 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, and ACHANNEL_SETTING_VISIBLE.
static void acf_group_backdrop (bAnimContext * ac, bAnimListElem * ale, float yminc, float ymaxc) [static]
Definition at line 743 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ANIM_channel_get_typeinfo(), ANIM_channel_setting_get(), bAnimContext::ar, View2D::cur, EXTRA_SCROLL_PAD, bAnimChannelType::get_backdrop_color, bAnimChannelType::get_offset, UI_CNR_BOTTOM_LEFT, UI_CNR_TOP_LEFT, uiDrawBox(), uiSetRoundBox(), ARegion::v2d, and rctf::xmax.
static void acf_group_color (bAnimContext * UNUSEDac, bAnimListElem * ale, float * color) [static]
Definition at line 733 of file anim_channels_defines.c.
References AGRP_ACTIVE, bAnimListElem::flag, TH_GROUP, TH_GROUP_ACTIVE, and UI_GetThemeColorShade3fv().
static void acf_group_name (bAnimListElem * ale, char * name) [static]
Definition at line 761 of file anim_channels_defines.c.
References ANIM_CHAN_NAME_SIZE, BLI_strncpy(), bAnimListElem::data, if(), and bActionGroup::name.
static short acf_group_name_prop (bAnimListElem * ale, PointerRNA * ptr, PropertyRNA ** prop) [static]
Definition at line 771 of file anim_channels_defines.c.
References bAnimListElem::data, bAnimListElem::id, NULL, RNA_ActionGroup, RNA_pointer_create(), RNA_struct_name_property(), and PointerRNA::type.
static int acf_group_setting_flag (bAnimContext * ac, int setting, short * neg) [static]
Definition at line 793 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_PROTECT, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, AGRP_EXPANDED, AGRP_EXPANDED_G, AGRP_MUTED, AGRP_NOTVISIBLE, AGRP_PROTECTED, AGRP_SELECTED, SPACE_IPO, and bAnimContext::spacetype.
static void* acf_group_setting_ptr (bAnimListElem * ale, int UNUSEDsetting, short * type) [static]
Definition at line 830 of file anim_channels_defines.c.
References bAnimListElem::data, bActionGroup::flag, and GET_ACF_FLAG_PTR.
static short acf_group_setting_valid (bAnimContext * ac, bAnimListElem * UNUSEDale, int setting) [static]
Definition at line 780 of file anim_channels_defines.c.
References ACHANNEL_SETTING_VISIBLE, SPACE_IPO, and bAnimContext::spacetype.
static short acf_nodetree_rootType_offset (bNodeTree * ntree) [static]
Definition at line 259 of file anim_channels_defines.c.
References INDENT_STEP_SIZE, NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, and bNodeTree::type.
Referenced by acf_dsntree_offset(), and acf_generic_group_offset().
static int acf_object_icon (bAnimListElem * ale) [static]
Definition at line 585 of file anim_channels_defines.c.
References bAnimListElem::data, OB_ARMATURE, OB_CAMERA, OB_CURVE, OB_EMPTY, OB_FONT, OB_LAMP, OB_LATTICE, OB_MBALL, OB_MESH, OB_SPEAKER, OB_SURF, and Base::object.
static void acf_object_name (bAnimListElem * ale, char * name) [static]
Definition at line 622 of file anim_channels_defines.c.
References ANIM_CHAN_NAME_SIZE, BLI_strncpy(), bAnimListElem::data, if(), and Base::object.
static int acf_object_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 658 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, OB_ADS_COLLAPSED, and SELECT.
static void* acf_object_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 684 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, bAnimListElem::data, GET_ACF_FLAG_PTR, NULL, and Base::object.
static short acf_object_setting_valid (bAnimContext * ac, bAnimListElem * ale, int setting) [static]
Definition at line 633 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, bAnimListElem::data, Base::object, SPACE_IPO, SPACE_NLA, and bAnimContext::spacetype.
static int acf_scene_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 484 of file anim_channels_defines.c.
static int acf_scene_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 512 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, ADT_CURVES_NOT_VISIBLE, ADT_NLA_EVAL_OFF, SCE_DS_COLLAPSED, and SCE_DS_SELECTED.
static void* acf_scene_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 538 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, Scene::adt, bAnimListElem::data, AnimData::flag, Scene::flag, GET_ACF_FLAG_PTR, and NULL.
static short acf_scene_setting_valid (bAnimContext * ac, bAnimListElem * UNUSEDale, int setting) [static]
Definition at line 490 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_VISIBLE, SPACE_IPO, SPACE_NLA, and bAnimContext::spacetype.
static void acf_shapekey_name (bAnimListElem * ale, char * name) [static]
Definition at line 2218 of file anim_channels_defines.c.
References ANIM_CHAN_NAME_SIZE, BLI_snprintf(), BLI_strncpy(), bAnimListElem::data, if(), bAnimListElem::index, and KeyBlock::name.
static short acf_shapekey_nameprop (bAnimListElem * ale, PointerRNA * ptr, PropertyRNA ** prop) [static]
Definition at line 2233 of file anim_channels_defines.c.
References bAnimListElem::data, bAnimListElem::id, if(), KeyBlock::name, NULL, RNA_pointer_create(), RNA_ShapeKey, RNA_struct_name_property(), and PointerRNA::type.
static int acf_shapekey_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 2264 of file anim_channels_defines.c.
References ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_PROTECT, ACHANNEL_SETTING_SELECT, KEYBLOCK_LOCKED, KEYBLOCK_MUTE, and KEYBLOCK_SEL.
static void* acf_shapekey_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 2285 of file anim_channels_defines.c.
References ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_PROTECT, ACHANNEL_SETTING_SELECT, bAnimListElem::data, KeyBlock::flag, GET_ACF_FLAG_PTR, and NULL.
static short acf_shapekey_setting_valid (bAnimContext * UNUSEDac, bAnimListElem * UNUSEDale, int setting) [static]
Definition at line 2249 of file anim_channels_defines.c.
References ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_PROTECT, and ACHANNEL_SETTING_SELECT.
static void acf_summary_backdrop (bAnimContext * ac, bAnimListElem * ale, float yminc, float ymaxc) [static]
Definition at line 387 of file anim_channels_defines.c.
References ANIM_channel_get_typeinfo(), bAnimContext::ar, View2D::cur, EXTRA_SCROLL_PAD, bAnimChannelType::get_backdrop_color, UI_CNR_BOTTOM_LEFT, UI_CNR_TOP_LEFT, uiDrawBox(), uiSetRoundBox(), ARegion::v2d, and rctf::xmax.
static void acf_summary_color (bAnimContext * UNUSEDac, bAnimListElem * UNUSEDale, float * color) [static]
Definition at line 377 of file anim_channels_defines.c.
static int acf_summary_icon (bAnimListElem * UNUSEDale) [static]
Definition at line 413 of file anim_channels_defines.c.
static void acf_summary_name (bAnimListElem * UNUSEDale, char * name) [static]
Definition at line 406 of file anim_channels_defines.c.
References ANIM_CHAN_NAME_SIZE, and BLI_strncpy().
static int acf_summary_setting_flag (bAnimContext * UNUSEDac, int setting, short * neg) [static]
Definition at line 426 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, and ADS_FLAG_SUMMARY_COLLAPSED.
static void* acf_summary_setting_ptr (bAnimListElem * ale, int setting, short * type) [static]
Definition at line 441 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, SpaceAction::ads, bAnimListElem::data, GET_ACF_FLAG_PTR, if(), NULL, bAnimContext::sl, SPACE_ACTION, and bAnimContext::spacetype.
static short acf_summary_setting_valid (bAnimContext * UNUSEDac, bAnimListElem * UNUSEDale, int setting) [static]
Definition at line 419 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND.
static void achannel_setting_flush_widget_cb (bContext * C, void * ale_npoin, void * setting_wrap) [static]
Definition at line 2909 of file anim_channels_defines.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIM_channel_setting_get(), ANIM_flush_setting_anim_channels(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, BLI_freelistN(), bAnimContext::data, bAnimContext::datatype, filter(), GET_INT_FROM_POINTER, NA_EDITED, NC_ANIMATION, ND_ANIMCHAN, NULL, and WM_event_add_notifier().
Referenced by draw_setting_widget().
static void achannel_setting_rename_done_cb (bContext * C, void * ads_poin, void * UNUSEDarg2) [static]
Definition at line 2949 of file anim_channels_defines.c.
References NA_RENAME, NC_ANIMATION, ND_ANIMCHAN, NULL, bDopeSheet::renameIndex, and WM_event_add_notifier().
Referenced by ANIM_channel_draw_widgets().
static void achannel_setting_slider_cb (bContext * C, void * id_poin, void * fcu_poin) [static]
Definition at line 2962 of file anim_channels_defines.c.
References ANIM_get_keyframing_flags(), CFRA, CTX_data_scene(), CTX_wm_reports(), fcurve_frame_has_keyframe(), insert_keyframe_direct(), INSERTKEY_REPLACE, NA_EDITED, NC_ANIMATION, ND_ANIMCHAN, NULL, RNA_id_pointer_create(), FCurve::rna_path, RNA_path_resolve(), and WM_event_add_notifier().
Referenced by ANIM_channel_draw_widgets().
static void achannel_setting_slider_shapekey_cb (bContext * C, void * key_poin, void * kb_poin) [static]
Definition at line 2999 of file anim_channels_defines.c.
References ANIM_get_keyframing_flags(), CFRA, CTX_data_scene(), CTX_wm_reports(), fcurve_frame_has_keyframe(), insert_keyframe_direct(), INSERTKEY_REPLACE, key_get_curValue_rnaPath(), MEM_freeN(), NA_EDITED, NC_ANIMATION, ND_ANIMCHAN, NULL, RNA_id_pointer_create(), RNA_path_resolve(), verify_adt_action(), verify_fcurve(), and WM_event_add_notifier().
Referenced by ANIM_channel_draw_widgets().
static void achannel_setting_widget_cb (bContext * C, void * UNUSEDarg1, void * UNUSEDarg2) [static]
Definition at line 2903 of file anim_channels_defines.c.
References NA_EDITED, NC_ANIMATION, ND_ANIMCHAN, NULL, and WM_event_add_notifier().
Referenced by draw_setting_widget().
void ANIM_channel_debug_print_info (bAnimListElem * ale, short indent_level)
Definition at line 2563 of file anim_channels_defines.c.
References ANIM_CHAN_NAME_SIZE, ANIM_channel_get_typeinfo(), BLI_strncpy(), bAnimChannelType::channel_type_name, bAnimChannelType::name, and bAnimListElem::type.
void ANIM_channel_draw (bAnimContext * ac, bAnimListElem * ale, float yminc, float ymaxc)
Definition at line 2725 of file anim_channels_defines.c.
References ACHANNEL_BUTTON_WIDTH, ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_PROTECT, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_SOLO, ACHANNEL_SETTING_VISIBLE, ANIM_CHAN_NAME_SIZE, ANIM_channel_get_typeinfo(), ANIM_channel_setting_get(), ANIMTYPE_FCURVE, ANIMTYPE_SHAPEKEY, bAnimContext::ar, FCurve::color, View2D::cur, bAnimListElem::data, bAnimChannelType::draw_backdrop, ELEM, EXTRA_SCROLL_PAD, FCURVE_DISABLED, fdrawline(), SpaceIpo::flag, SpaceAction::flag, bAnimListElem::flag, bAnimChannelType::get_backdrop_color, bAnimChannelType::get_offset, bAnimChannelType::has_setting, bAnimChannelType::icon, ICON_WIDTH, View2D::mask, bAnimChannelType::name, NULL, SACTION_SLIDERS, SIPO_SLIDERS, bAnimContext::sl, SLIDER_WIDTH, SPACE_ACTION, SPACE_IPO, SPACE_NLA, bAnimContext::spacetype, TH_TEXT, TH_TEXT_HI, bAnimListElem::type, UI_DrawString(), UI_icon_draw(), UI_ThemeColor(), ARegion::v2d, rcti::xmax, rctf::xmax, and rcti::xmin.
Referenced by draw_channel_names(), draw_nla_channel_list_gl(), and graph_draw_channel_names().
void ANIM_channel_draw_widgets (bContext * C, bAnimContext * ac, bAnimListElem * ale, uiBlock * block, float yminc, float ymaxc, size_t channel_index)
Definition at line 3153 of file anim_channels_defines.c.
References ACHANNEL_BUTTON_WIDTH, ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_PROTECT, achannel_setting_rename_done_cb(), achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), ACHANNEL_SETTING_SOLO, ACHANNEL_SETTING_VISIBLE, bAnimContext::ads, ANIM_channel_get_typeinfo(), ANIMTYPE_FCURVE, ANIMTYPE_SHAPEKEY, bAnimContext::ar, FCurve::array_index, View2D::cur, bAnimListElem::data, draw_setting_widget(), ELEM, ELEM3, SpaceIpo::flag, SpaceAction::flag, free_path(), bAnimChannelType::get_offset, bAnimChannelType::has_setting, bAnimChannelType::icon, ICON_WIDTH, bAnimListElem::id, key_get_curValue_rnaPath(), View2D::mask, MEM_freeN(), bAnimChannelType::name_prop, NULL, RENAME_TEXT_WIDTH, bDopeSheet::renameIndex, RNA_id_pointer_create(), FCurve::rna_path, RNA_path_resolve(), RNA_property_identifier(), SACTION_SLIDERS, SIPO_SLIDERS, bAnimContext::sl, SLIDER_WIDTH, SPACE_ACTION, SPACE_IPO, SPACE_NLA, bAnimContext::spacetype, TEX, bAnimListElem::type, UI_EMBOSS, UI_EMBOSSN, uiBlockSetEmboss(), uiButActiveOnly(), uiButSetFunc(), uiDefAutoButR(), uiDefButR(), ARegion::v2d, rctf::xmax, rcti::xmax, and rcti::xmin.
Referenced by draw_channel_names(), draw_nla_channel_list(), and graph_draw_channel_names().
bAnimChannelType* ANIM_channel_get_typeinfo (bAnimListElem * ale)
Definition at line 2544 of file anim_channels_defines.c.
References ANIM_init_channel_typeinfo_data(), ANIMTYPE_NUM_TYPES, NULL, and bAnimListElem::type.
Referenced by acf_generic_basic_offset(), acf_generic_channel_backdrop(), acf_generic_channel_color(), acf_generic_dataexpand_backdrop(), acf_generic_root_backdrop(), acf_group_backdrop(), acf_summary_backdrop(), ANIM_channel_debug_print_info(), ANIM_channel_draw(), ANIM_channel_draw_widgets(), ANIM_channel_setting_get(), ANIM_channel_setting_set(), ANIM_flush_setting_anim_channels(), draw_channel_strips(), rename_anim_channels(), and skip_fcurve_with_name().
short ANIM_channel_setting_get (bAnimContext * ac, bAnimListElem * ale, int setting)
Definition at line 2595 of file anim_channels_defines.c.
References ANIM_channel_get_typeinfo(), bAnimChannelType::has_setting, bAnimChannelType::setting_flag, and bAnimChannelType::setting_ptr.
Referenced by acf_generic_root_backdrop(), acf_group_backdrop(), achannel_setting_flush_widget_cb(), ANIM_channel_draw(), animchannels_visibility_toggle_exec(), draw_channel_strips(), and setflag_anim_channels().
void ANIM_channel_setting_set (bAnimContext * ac, bAnimListElem * ale, int setting, short mode)
Definition at line 2672 of file anim_channels_defines.c.
References ACF_SETTING_SET, ANIM_channel_get_typeinfo(), bAnimChannelType::has_setting, bAnimChannelType::setting_flag, and bAnimChannelType::setting_ptr.
Referenced by ANIM_flush_setting_anim_channels(), animchannels_visibility_set_exec(), animchannels_visibility_toggle_exec(), borderselect_anim_channels(), and setflag_anim_channels().
static void ANIM_init_channel_typeinfo_data (void) [static]
Definition at line 2494 of file anim_channels_defines.c.
References ACF_DSARM, ACF_DSCAM, ACF_DSCUR, ACF_DSLAM, ACF_DSLAT, ACF_DSMAT, ACF_DSMBALL, ACF_DSMESH, ACF_DSNTREE, ACF_DSPART, ACF_DSSKEY, ACF_DSSPK, ACF_DSTEX, ACF_DSWOR, ACF_FCURVE, ACF_FILLACTD, ACF_FILLDRIVERS, ACF_GPD, ACF_GPL, ACF_GROUP, ACF_OBJECT, ACF_SCENE, ACF_SHAPEKEY, ACF_SUMMARY, and NULL.
Referenced by ANIM_channel_get_typeinfo().
static void draw_setting_widget (bAnimContext * ac, bAnimListElem * ale, bAnimChannelType * acf, uiBlock * block, int xpos, int ypos, int setting) [static]
Definition at line 3046 of file anim_channels_defines.c.
References ACHANNEL_SETTING_EXPAND, achannel_setting_flush_widget_cb(), ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_PROTECT, ACHANNEL_SETTING_SOLO, ACHANNEL_SETTING_VISIBLE, achannel_setting_widget_cb(), ALE_FCURVE, ANIMTYPE_FCURVE, ICON_WIDTH, ICONTOG, ICONTOGN, MEM_dupallocN(), NULL, SET_INT_IN_POINTER, bAnimChannelType::setting_flag, bAnimChannelType::setting_ptr, bAnimListElem::type, uiButSetFunc(), uiButSetNFunc(), uiDefIconButBitC(), uiDefIconButBitI(), and uiDefIconButBitS().
Referenced by ANIM_channel_draw_widgets().
Variable Documentation
bAnimChannelType ACF_DSARM [static]
Initial value:
{
    "Armature Expander",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_generic_basic_offset,
    acf_generic_idblock_name,
    acf_generic_idblock_nameprop,
    acf_dsarm_icon,
    acf_generic_dataexpand_setting_valid,
    acf_dsarm_setting_flag,
    acf_dsarm_setting_ptr
}
Definition at line 1878 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_DSCAM [static]
Initial value:
{
    "Camera Expander",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_generic_basic_offset,
    acf_generic_idblock_name,
    acf_generic_idfill_nameprop,
    acf_dscam_icon,
    acf_generic_dataexpand_setting_valid,
    acf_dscam_setting_flag,
    acf_dscam_setting_ptr
}
Definition at line 1406 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_DSCUR [static]
Initial value:
{
    "Curve Expander",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_generic_basic_offset,
    acf_generic_idblock_name,
    acf_generic_idblock_nameprop,
    acf_dscur_icon,
    acf_generic_dataexpand_setting_valid,
    acf_dscur_setting_flag,
    acf_dscur_setting_ptr
}
Definition at line 1493 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_DSLAM [static]
Initial value:
{
    "Lamp Expander",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_generic_basic_offset,
    acf_generic_idblock_name,
    acf_generic_idblock_nameprop,
    acf_dslam_icon,
    acf_generic_dataexpand_setting_valid,
    acf_dslam_setting_flag,
    acf_dslam_setting_ptr
}
Definition at line 1245 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_DSLAT [static]
Initial value:
{
    "Lattice Expander",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_generic_basic_offset,
    acf_generic_idblock_name,
    acf_generic_idblock_nameprop,
    acf_dslat_icon,
    acf_generic_dataexpand_setting_valid,
    acf_dslat_setting_flag,
    acf_dslat_setting_ptr
}
Definition at line 2120 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_DSMAT [static]
Initial value:
{
    "Material Data Expander",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_generic_basic_offset,
    acf_generic_idblock_name,
    acf_generic_idblock_nameprop,
    acf_dsmat_icon,
    acf_generic_dataexpand_setting_valid,
    acf_dsmat_setting_flag,
    acf_dsmat_setting_ptr
}
Definition at line 1168 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_DSMBALL [static]
Initial value:
{
    "Metaball Expander",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_generic_basic_offset,
    acf_generic_idblock_name,
    acf_generic_idblock_nameprop,
    acf_dsmball_icon,
    acf_generic_dataexpand_setting_valid,
    acf_dsmball_setting_flag,
    acf_dsmball_setting_ptr
}
Definition at line 1801 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_DSMESH [static]
Initial value:
{
    "Mesh Expander",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_generic_basic_offset,
    acf_generic_idblock_name,
    acf_generic_idblock_nameprop,
    acf_dsmesh_icon,
    acf_generic_dataexpand_setting_valid,
    acf_dsmesh_setting_flag,
    acf_dsmesh_setting_ptr
}
Definition at line 2043 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_DSNTREE [static]
Initial value:
{
    "Node Tree Expander",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_dsntree_offset,
    acf_generic_idblock_name,
    acf_generic_idblock_nameprop,
    acf_dsntree_icon,
    acf_generic_dataexpand_setting_valid,
    acf_dsntree_setting_flag,
    acf_dsntree_setting_ptr
}
Definition at line 1966 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_DSPART [static]
Initial value:
{
    "Particle Data Expander",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_generic_basic_offset,
    acf_generic_idblock_name,
    acf_generic_idblock_nameprop,
    acf_dspart_icon,
    acf_generic_dataexpand_setting_valid,
    acf_dspart_setting_flag,
    acf_dspart_setting_ptr
}
Definition at line 1724 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_DSSKEY [static]
Initial value:
{
    "Shape Key Expander",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_generic_basic_offset,
    acf_generic_idblock_name,
    acf_generic_idblock_nameprop,
    acf_dsskey_icon,
    acf_generic_dataexpand_setting_valid,
    acf_dsskey_setting_flag,
    acf_dsskey_setting_ptr
}
Definition at line 1570 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_DSSPK [static]
Initial value:
{
    "Speaker Expander",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_generic_basic_offset,
    acf_generic_idblock_name,
    acf_generic_idblock_nameprop,
    acf_dsspk_icon,
    acf_generic_dataexpand_setting_valid,
    acf_dsspk_setting_flag,
    acf_dsspk_setting_ptr
}
Definition at line 2197 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_DSTEX [static]
Initial value:
{
    "Texture Data Expander",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_dstex_offset,
    acf_generic_idblock_name,
    acf_generic_idfill_nameprop,
    acf_dstex_icon,
    acf_generic_dataexpand_setting_valid,
    acf_dstex_setting_flag,
    acf_dstex_setting_ptr
}
Definition at line 1329 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_DSWOR [static]
Initial value:
{
    "World Expander",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_generic_basic_offset,
    acf_generic_idblock_name,
    acf_generic_idfill_nameprop,
    acf_dswor_icon,
    acf_generic_dataexpand_setting_valid,
    acf_dswor_setting_flag,
    acf_dswor_setting_ptr
}
Definition at line 1647 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_FCURVE [static]
Initial value:
{
    "F-Curve",
    acf_generic_channel_color,
    acf_generic_channel_backdrop,
    acf_generic_indention_flexible,
    acf_generic_group_offset,
    acf_fcurve_name,
    NULL,
    NULL,
    acf_fcurve_setting_valid,
    acf_fcurve_setting_flag,
    acf_fcurve_setting_ptr
}
Definition at line 926 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_FILLACTD [static]
Initial value:
{
    "Ob-Action Filler",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_generic_basic_offset,
    acf_generic_idblock_name,
    acf_generic_idfill_nameprop,
    acf_fillactd_icon,
    acf_fillactd_setting_valid,
    acf_fillactd_setting_flag,
    acf_fillactd_setting_ptr
}
Definition at line 1011 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_FILLDRIVERS [static]
Initial value:
{
    "Drivers Filler",
    acf_generic_dataexpand_color,
    acf_generic_dataexpand_backdrop,
    acf_generic_indention_1,
    acf_generic_basic_offset,
    acf_filldrivers_name,
    NULL,
    acf_filldrivers_icon,
    acf_filldrivers_setting_valid,
    acf_filldrivers_setting_flag,
    acf_filldrivers_setting_ptr
}
Definition at line 1090 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_GPD [static]
Initial value:
{
    "GPencil Datablock",
    acf_gpd_color,
    acf_group_backdrop,
    acf_generic_indention_0,
    acf_generic_group_offset,
    acf_generic_idblock_name,
    acf_generic_idfill_nameprop,
    acf_gpd_icon,
    acf_gpd_setting_valid,
    acf_gpd_setting_flag,
    acf_gpd_setting_ptr
}
Definition at line 2379 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_GPL [static]
Initial value:
{
    "GPencil Layer",
    acf_generic_channel_color,
    acf_generic_channel_backdrop,
    acf_generic_indention_flexible,
    acf_generic_group_offset,
    acf_gpl_name,
    acf_gpl_name_prop,
    NULL,
    acf_gpl_setting_valid,
    acf_gpl_setting_flag,
    acf_gpl_setting_ptr
}
Definition at line 2468 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_GROUP [static]
Initial value:
{
    "Group",
    acf_group_color,
    acf_group_backdrop,
    acf_generic_indention_0,
    acf_generic_group_offset,
    acf_group_name,
    acf_group_name_prop,
    NULL,
    acf_group_setting_valid,
    acf_group_setting_flag,
    acf_group_setting_ptr
}
Definition at line 839 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
short ACF_INIT = 1 [static]
Definition at line 2491 of file anim_channels_defines.c.
bAnimChannelType ACF_OBJECT [static]
Initial value:
{
    "Object",
    acf_generic_root_color,
    acf_generic_root_backdrop,
    acf_generic_indention_0,
    NULL,
    acf_object_name,
    acf_generic_idblock_nameprop,
    acf_object_icon,
    acf_object_setting_valid,
    acf_object_setting_flag,
    acf_object_setting_ptr
}
Definition at line 712 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_SCENE [static]
Initial value:
{
    "Scene",
    acf_generic_root_color,
    acf_generic_root_backdrop,
    acf_generic_indention_0,
    NULL,
    acf_generic_idblock_name,
    acf_generic_idblock_nameprop,
    acf_scene_icon,
    acf_scene_setting_valid,
    acf_scene_setting_flag,
    acf_scene_setting_ptr
}
Definition at line 565 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_SHAPEKEY [static]
Initial value:
{
    "Shape Key",
    acf_generic_channel_color,
    acf_generic_channel_backdrop,
    acf_generic_indention_0,
    acf_generic_basic_offset,
    acf_shapekey_name,
    acf_shapekey_nameprop,
    NULL,
    acf_shapekey_setting_valid,
    acf_shapekey_setting_flag,
    acf_shapekey_setting_ptr
}
Definition at line 2304 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType ACF_SUMMARY [static]
Initial value:
{
    "Summary",
    acf_summary_color,
    acf_summary_backdrop,
    acf_generic_indention_0,
    NULL,
    acf_summary_name,
    NULL,
    acf_summary_icon,
    acf_summary_setting_valid,
    acf_summary_setting_flag,
    acf_summary_setting_ptr
}
Definition at line 463 of file anim_channels_defines.c.
Referenced by ANIM_init_channel_typeinfo_data().
bAnimChannelType* animchannelTypeInfo[ANIMTYPE_NUM_TYPES] [static]
Definition at line 2490 of file anim_channels_defines.c.