Blender: device_intern.h File Reference
device_intern.h File Reference
Functions
Device * device_cpu_create (DeviceInfo &info, int threads)
Device * device_opencl_create (DeviceInfo &info, bool background)
Device * device_cuda_create (DeviceInfo &info, bool background)
Device * device_network_create (DeviceInfo &info, const char *address)
Device * device_multi_create (DeviceInfo &info, bool background)
void device_cpu_info (vector< DeviceInfo > &devices)
void device_opencl_info (vector< DeviceInfo > &devices)
void device_cuda_info (vector< DeviceInfo > &devices)
void device_network_info (vector< DeviceInfo > &devices)
void device_multi_info (vector< DeviceInfo > &devices)
Function Documentation
Device* device_cpu_create (DeviceInfo & info, int threads)
Definition at line 256 of file device_cpu.cpp.
Referenced by Device::create().
void device_cpu_info (vector< DeviceInfo > & devices)
Definition at line 261 of file device_cpu.cpp.
References DeviceInfo::advanced_shading, DeviceInfo::description, DEVICE_CPU, DeviceInfo::id, DeviceInfo::num, system_cpu_brand_string(), and DeviceInfo::type.
Referenced by Device::available_devices().
Device* device_cuda_create (DeviceInfo & info, bool background)
Definition at line 829 of file device_cuda.cpp.
References CUDADevice::CUDADevice().
Referenced by Device::create().
void device_cuda_info (vector< DeviceInfo > & devices)
Definition at line 834 of file device_cuda.cpp.
References DeviceInfo::advanced_shading, CU_DEVICE_ATTRIBUTE_KERNEL_EXEC_TIMEOUT, CUDA_SUCCESS, cuDeviceComputeCapability, cuDeviceGetAttribute, cuDeviceGetCount, cuDeviceGetName, cuInit, DeviceInfo::description, DEVICE_CUDA, DeviceInfo::display_device, DeviceInfo::id, Device::info, DeviceInfo::num, string_printf(), and DeviceInfo::type.
Referenced by Device::available_devices().
Device* device_multi_create (DeviceInfo & info, bool background)
Definition at line 291 of file device_multi.cpp.
Referenced by Device::create().
void device_multi_info (vector< DeviceInfo > & devices)
Definition at line 391 of file device_multi.cpp.
References DEVICE_CUDA, device_multi_add(), and DEVICE_OPENCL.
Referenced by Device::available_devices().
Device* device_network_create (DeviceInfo & info, const char * address)
Referenced by Device::create(), and MultiDevice::MultiDevice().
void device_network_info (vector< DeviceInfo > & devices)
Referenced by Device::available_devices().
Device* device_opencl_create (DeviceInfo & info, bool background)
Referenced by Device::create().
void device_opencl_info (vector< DeviceInfo > & devices)
Referenced by Device::available_devices().