Blender: node_texture_output.c File Reference
node_texture_output.c File Reference
texnodes
#include "node_texture_util.h"
#include "NOD_texture.h"
Functions
static void exec (void *data, bNode *node, bNodeStack **in, bNodeStack **UNUSED(out))
static void unique_name (bNode *node)
static void assign_index (struct bNode *node)
static void init (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static void copy (bNode *orig, bNode *new)
void register_node_type_tex_output (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate inputs []
Detailed Description
Definition in file node_texture_output.c.
Function Documentation
static void assign_index (struct bNode * node) [static]
Definition at line 124 of file node_texture_output.c.
References bNode::custom1, bNode::next, bNode::prev, TEX_NODE_OUTPUT, and bNode::type.
Referenced by copy(), and init().
static void copy (bNode * orig, bNode * new) [static]
Definition at line 154 of file node_texture_output.c.
References assign_index(), node_copy_standard_storage(), and unique_name().
Referenced by BSP_CSGMesh::AddPolygon(), MD5Hash::append(), TransformReader::get_node_mat(), IDP_ReplaceGroupInGroup(), IDP_SyncGroupValues(), makebody_tga(), p_split_vert(), register_node_type_tex_output(), WM_dropbox_add(), and wm_save_as_mainfile_exec().
static void exec (void * data, bNode * node, bNodeStack ** in, bNodeStack ** UNUSEDout) [static]
Definition at line 44 of file node_texture_output.c.
References TexParams::co, bNode::custom1, TexCallData::do_preview, TexResult::nor, NULL, params_from_cdata(), TexResult::talpha, TexCallData::target, TexResult::tb, tex_do_preview(), tex_input_rgba(), tex_input_vec(), TexResult::tg, TexCallData::thread, TexResult::tin, TexResult::tr, and TexCallData::which_output.
Referenced by register_node_type_tex_output().
static void init (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 144 of file node_texture_output.c.
References assign_index(), MEM_callocN(), TexNodeOutput::name, bNode::storage, and unique_name().
void register_node_type_tex_output (bNodeTreeType * ttype)
Definition at line 161 of file node_texture_output.c.
References copy(), exec(), init(), NODE_CLASS_OUTPUT, node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and TEX_NODE_OUTPUT.
Referenced by registerTextureNodes().
static void unique_name (bNode * node) [static]
Definition at line 80 of file node_texture_output.c.
References i, len(), MEM_freeN(), MEM_mallocN(), TexNodeOutput::name, NULL, bNode::storage, strlen(), and TEX_NODE_OUTPUT.
Referenced by copy(), and init().
Variable Documentation
bNodeSocketTemplate inputs[] [static]
Initial value:
 {
    { SOCK_RGBA,   1, "Color",  0.0f, 0.0f, 0.0f, 1.0f},
    { SOCK_VECTOR, 1, "Normal", 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, PROP_DIRECTION},
    { -1, 0, "" }
}
Definition at line 37 of file node_texture_output.c.