Blender: ocean.c File Reference
ocean.c File Reference
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_scene_types.h"
#include "BKE_image.h"
#include "BKE_ocean.h"
#include "BKE_utildefines.h"
#include "BKE_global.h"
#include "BLI_math_base.h"
#include "BLI_math_inline.h"
#include "BLI_rand.h"
#include "BLI_string.h"
#include "BLI_threads.h"
#include "BLI_path_util.h"
#include "BLI_utildefines.h"
#include "IMB_imbuf.h"
#include "IMB_imbuf_types.h"
#include "RE_render_ext.h"
Classes
struct Ocean
Typedefs
typedef struct Ocean Ocean
Functions
float BKE_ocean_jminus_to_foam (float UNUSED(jminus), float UNUSED(coverage))
void BKE_ocean_eval_uv (struct Ocean *UNUSED(oc), struct OceanResult *UNUSED(ocr), float UNUSED(u), float UNUSED(v))
void BKE_ocean_eval_uv_catrom (struct Ocean *UNUSED(oc), struct OceanResult *UNUSED(ocr), float UNUSED(u), float UNUSED(v))
void BKE_ocean_eval_xz (struct Ocean *UNUSED(oc), struct OceanResult *UNUSED(ocr), float UNUSED(x), float UNUSED(z))
void BKE_ocean_eval_xz_catrom (struct Ocean *UNUSED(oc), struct OceanResult *UNUSED(ocr), float UNUSED(x), float UNUSED(z))
void BKE_ocean_eval_ij (struct Ocean *UNUSED(oc), struct OceanResult *UNUSED(ocr), int UNUSED(i), int UNUSED(j))
void BKE_simulate_ocean (struct Ocean *UNUSED(o), float UNUSED(t), float UNUSED(scale), float UNUSED(chop_amount))
struct Ocean * BKE_add_ocean (void)
void BKE_init_ocean (struct Ocean *UNUSED(o), int UNUSED(M), int UNUSED(N), float UNUSED(Lx), float UNUSED(Lz), float UNUSED(V), float UNUSED(l), float UNUSED(A), float UNUSED(w), float UNUSED(damp), float UNUSED(alignment), float UNUSED(depth), float UNUSED(time), short UNUSED(do_height_field), short UNUSED(do_chop), short UNUSED(do_normals), short UNUSED(do_jacobian), int UNUSED(seed))
void BKE_free_ocean_data (struct Ocean *UNUSED(oc))
void BKE_free_ocean (struct Ocean *oc)
void BKE_free_ocean_cache (struct OceanCache *och)
void BKE_ocean_cache_eval_uv (struct OceanCache *UNUSED(och), struct OceanResult *UNUSED(ocr), int UNUSED(f), float UNUSED(u), float UNUSED(v))
void BKE_ocean_cache_eval_ij (struct OceanCache *UNUSED(och), struct OceanResult *UNUSED(ocr), int UNUSED(f), int UNUSED(i), int UNUSED(j))
struct OceanCache * BKE_init_ocean_cache (const char *UNUSED(bakepath), const char *UNUSED(relbase), int UNUSED(start), int UNUSED(end), float UNUSED(wave_scale), float UNUSED(chop_amount), float UNUSED(foam_coverage), float UNUSED(foam_fade), int UNUSED(resolution))
void BKE_simulate_ocean_cache (struct OceanCache *UNUSED(och), int UNUSED(frame))
void BKE_bake_ocean (struct Ocean *UNUSED(o), struct OceanCache *UNUSED(och), void(*update_cb)(void *, float progress, int *cancel), void *UNUSED(update_cb_data))
Typedef Documentation
typedef struct Ocean Ocean
Function Documentation
struct Ocean* BKE_add_ocean (void) [read]
Definition at line 1375 of file ocean.c.
References MEM_callocN().
Referenced by copyData(), initData(), and ocean_bake_exec().
void BKE_bake_ocean (struct Ocean * UNUSEDo, struct OceanCache * UNUSEDoch, void(*)(void *, float progress, int *cancel) update_cb, void * UNUSEDupdate_cb_data)
Definition at line 1429 of file ocean.c.
References update_cb().
void BKE_free_ocean (struct Ocean * oc)
Definition at line 1391 of file ocean.c.
References MEM_freeN().
Referenced by freeData(), and oceanbake_endjob().
void BKE_free_ocean_cache (struct OceanCache * och)
Definition at line 1401 of file ocean.c.
References MEM_freeN().
Referenced by freeData().
void BKE_free_ocean_data (struct Ocean * UNUSEDoc)
Definition at line 1387 of file ocean.c.
void BKE_init_ocean (struct Ocean * UNUSEDo, int UNUSEDM, int UNUSEDN, float UNUSEDLx, float UNUSEDLz, float UNUSEDV, float UNUSEDl, float UNUSEDA, float UNUSEDw, float UNUSEDdamp, float UNUSEDalignment, float UNUSEDdepth, float UNUSEDtime, short UNUSEDdo_height_field, short UNUSEDdo_chop, short UNUSEDdo_normals, short UNUSEDdo_jacobian, int UNUSEDseed)
Definition at line 1382 of file ocean.c.
struct OceanCache* BKE_init_ocean_cache (const char * UNUSEDbakepath, const char * UNUSEDrelbase, int UNUSEDstart, int UNUSEDend, float UNUSEDwave_scale, float UNUSEDchop_amount, float UNUSEDfoam_coverage, float UNUSEDfoam_fade, int UNUSEDresolution) [read]
Definition at line 1416 of file ocean.c.
References MEM_callocN().
void BKE_ocean_cache_eval_ij (struct OceanCache * UNUSEDoch, struct OceanResult * UNUSEDocr, int UNUSEDf, int UNUSEDi, int UNUSEDj)
Definition at line 1412 of file ocean.c.
void BKE_ocean_cache_eval_uv (struct OceanCache * UNUSEDoch, struct OceanResult * UNUSEDocr, int UNUSEDf, float UNUSEDu, float UNUSEDv)
Definition at line 1408 of file ocean.c.
void BKE_ocean_eval_ij (struct Ocean * UNUSEDoc, struct OceanResult * UNUSEDocr, int UNUSEDi, int UNUSEDj)
Definition at line 1367 of file ocean.c.
void BKE_ocean_eval_uv (struct Ocean * UNUSEDoc, struct OceanResult * UNUSEDocr, float UNUSEDu, float UNUSEDv)
Definition at line 1350 of file ocean.c.
void BKE_ocean_eval_uv_catrom (struct Ocean * UNUSEDoc, struct OceanResult * UNUSEDocr, float UNUSEDu, float UNUSEDv)
Definition at line 1355 of file ocean.c.
void BKE_ocean_eval_xz (struct Ocean * UNUSEDoc, struct OceanResult * UNUSEDocr, float UNUSEDx, float UNUSEDz)
Definition at line 1359 of file ocean.c.
void BKE_ocean_eval_xz_catrom (struct Ocean * UNUSEDoc, struct OceanResult * UNUSEDocr, float UNUSEDx, float UNUSEDz)
Definition at line 1363 of file ocean.c.
float BKE_ocean_jminus_to_foam (float UNUSEDjminus, float UNUSEDcoverage)
Definition at line 1345 of file ocean.c.
void BKE_simulate_ocean (struct Ocean * UNUSEDo, float UNUSEDt, float UNUSEDscale, float UNUSEDchop_amount)
Definition at line 1371 of file ocean.c.
void BKE_simulate_ocean_cache (struct OceanCache * UNUSEDoch, int UNUSEDframe)
Definition at line 1425 of file ocean.c.