Blender: BIK_api.h File Reference
BIK_api.h File Reference
ikplugin
Classes
struct BIK_ParamValue
Defines
#define BIK_PARAM_CONSTRAINT_ERROR 0
#define BIK_PARAM_CHANNEL_JOINT 0
#define BIK_PARAM_SOLVER_RANK 0
#define BIK_PARAM_SOLVER_ITERATION 1
Typedefs
typedef struct BIK_ParamValue BIK_ParamValue
Enumerations
enum BIK_ParamType { BIK_PARAM_TYPE_FLOAT = 0, BIK_PARAM_TYPE_INT, BIK_PARAM_TYPE_STRING }
Functions
void BIK_initialize_tree (struct Scene *scene, struct Object *ob, float ctime)
void BIK_execute_tree (struct Scene *scene, struct Object *ob, struct bPoseChannel *pchan, float ctime)
void BIK_release_tree (struct Scene *scene, struct Object *ob, float ctime)
void BIK_clear_data (struct bPose *pose)
void BIK_clear_cache (struct bPose *pose)
void BIK_update_param (struct bPose *pose)
void BIK_test_constraint (struct Object *ob, struct bConstraint *cons)
int BIK_get_constraint_param (struct bPose *pose, struct bConstraint *cons, int id, BIK_ParamValue *value)
int BIK_get_channel_param (struct bPose *pose, struct bPoseChannel *pchan, int id, BIK_ParamValue *value)
int BIK_get_solver_param (struct bPose *pose, struct bPoseChannel *pchan, int id, BIK_ParamValue *value)
Detailed Description
Definition in file BIK_api.h.
Define Documentation
#define BIK_PARAM_CHANNEL_JOINT 0
Definition at line 85 of file BIK_api.h.
#define BIK_PARAM_CONSTRAINT_ERROR 0
Definition at line 82 of file BIK_api.h.
#define BIK_PARAM_SOLVER_ITERATION 1
Definition at line 89 of file BIK_api.h.
#define BIK_PARAM_SOLVER_RANK 0
Definition at line 88 of file BIK_api.h.
Typedef Documentation
typedef struct BIK_ParamValue BIK_ParamValue
Definition at line 63 of file BIK_api.h.
Enumeration Type Documentation
enum BIK_ParamType
Enumerator:
BIK_PARAM_TYPE_FLOAT
BIK_PARAM_TYPE_INT
BIK_PARAM_TYPE_STRING
Definition at line 48 of file BIK_api.h.
Function Documentation
void BIK_clear_cache (struct bPose * pose)
Definition at line 122 of file ikplugin_api.c.
References IKPlugin::clear_cache, and get_plugin().
Referenced by BKE_ptcache_object_reset().
void BIK_clear_data (struct bPose * pose)
Definition at line 114 of file ikplugin_api.c.
References get_plugin(), and IKPlugin::remove_armature_func.
Referenced by constraint_delete_exec(), free_pose(), and game_free_pose().
void BIK_execute_tree (struct Scene * scene, struct Object * ob, struct bPoseChannel * pchan, float ctime)
Definition at line 98 of file ikplugin_api.c.
References IKPlugin::execute_tree_func, get_plugin(), and Object::pose.
Referenced by where_is_pose().
int BIK_get_channel_param (struct bPose * pose, struct bPoseChannel * pchan, int id, BIK_ParamValue * value)
int BIK_get_constraint_param (struct bPose * pose, struct bConstraint * cons, int id, BIK_ParamValue * value)
int BIK_get_solver_param (struct bPose * pose, struct bPoseChannel * pchan, int id, BIK_ParamValue * value)
void BIK_initialize_tree (struct Scene * scene, struct Object * ob, float ctime)
Definition at line 90 of file ikplugin_api.c.
References get_plugin(), IKPlugin::initialize_tree_func, and Object::pose.
Referenced by where_is_pose().
void BIK_release_tree (struct Scene * scene, struct Object * ob, float ctime)
Definition at line 106 of file ikplugin_api.c.
References get_plugin(), Object::pose, and IKPlugin::release_tree_func.
Referenced by where_is_pose().
void BIK_test_constraint (struct Object * ob, struct bConstraint * cons)
Definition at line 138 of file ikplugin_api.c.
References get_plugin(), Object::pose, and IKPlugin::test_constraint.
Referenced by test_constraints().
void BIK_update_param (struct bPose * pose)
Definition at line 130 of file ikplugin_api.c.
References get_plugin(), and IKPlugin::update_param.