Blender: SubdVert Class Reference
SubdVert Class Reference
#include <subd_vert.h>
Classes
class EdgeIterator
class ReverseEdgeIterator
Public Member Functions
SubdVert (int id_)
int valence ()
bool is_boundary ()
EdgeIterator edges ()
EdgeIterator edges (SubdEdge *edge)
Public Attributes
int id
float3 co
SubdEdge * edge
SubdVert * next
SubdVert * prev
Detailed Description
Definition at line 39 of file subd_vert.h.
Constructor & Destructor Documentation
SubdVert::SubdVert (int id_) [inline]
Definition at line 49 of file subd_vert.h.
References co, edge, make_float3(), next, NULL, and prev.
Member Function Documentation
EdgeIterator SubdVert::edges () [inline]
Definition at line 114 of file subd_vert.h.
References edge.
Referenced by SubdAccBuilder::computeBoundaryTangentStencils(), SubdAccBuilder::computeEdgeStencil(), SubdMesh::link_boundary(), and valence().
EdgeIterator SubdVert::edges (SubdEdge * edge) [inline]
Definition at line 115 of file subd_vert.h.
bool SubdVert::is_boundary () [inline]
Definition at line 71 of file subd_vert.h.
References edge, and SubdEdge::face.
Referenced by SubdAccBuilder::computeBoundaryTangentStencils(), SubdAccBuilder::computeCornerStencil(), SubdAccBuilder::computeEdgeStencil(), SubdFaceRing::is_boundary(), and pseudoValence().
int SubdVert::valence () [inline]
Definition at line 60 of file subd_vert.h.
References edges(), and SubdVert::EdgeIterator::isDone().
Referenced by SubdAccBuilder::computeBoundaryTangentStencils(), SubdAccBuilder::computeCornerStencil(), SubdAccBuilder::computeEdgeStencil(), SubdFaceRing::initVerts(), SubdFaceRing::is_regular(), and pseudoValence().
Member Data Documentation
float3 SubdVert::co
Definition at line 43 of file subd_vert.h.
Referenced by SubdMesh::add_vert(), SubdAccBuilder::computeCornerStencil(), SubdAccBuilder::computeEdgeStencil(), SubdFaceRing::has_vert(), SubdFaceRing::initVerts(), and SubdVert().
SubdEdge* SubdVert::edge
Definition at line 45 of file subd_vert.h.
Referenced by SubdMesh::add_edge(), SubdAccBuilder::computeBoundaryTangentStencils(), SubdAccBuilder::computeCornerStencil(), SubdAccBuilder::computeEdgeStencil(), edges(), is_boundary(), SubdMesh::link_boundary_edge(), and SubdVert().
int SubdVert::id
Definition at line 42 of file subd_vert.h.
Referenced by SubdMesh::link_boundary().
SubdVert* SubdVert::next
Definition at line 46 of file subd_vert.h.
Referenced by SubdVert().
SubdVert* SubdVert::prev
Definition at line 47 of file subd_vert.h.
Referenced by SubdVert().
The documentation for this class was generated from the following file:
subd_vert.h