Blender: space_clip.c File Reference
space_clip.c File Reference
#include <string.h>
#include <stdio.h>
#include "DNA_scene_types.h"
#include "DNA_movieclip_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "BKE_main.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "BKE_movieclip.h"
#include "BKE_tracking.h"
#include "IMB_imbuf_types.h"
#include "ED_screen.h"
#include "ED_clip.h"
#include "ED_transform.h"
#include "IMB_imbuf.h"
#include "BIF_gl.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "RNA_access.h"
#include "clip_intern.h"
Functions
static void init_preview_region (const bContext *C, ARegion *ar)
static ARegion * clip_has_preview_region (const bContext *C, ScrArea *sa)
static void clip_scopes_tag_refresh (ScrArea *sa)
static void clip_stabilization_tag_refresh (ScrArea *sa)
static SpaceLink * clip_new (const bContext *C)
static void clip_free (SpaceLink *sl)
static void clip_init (struct wmWindowManager *UNUSED(wm), ScrArea *UNUSED(sa))
static SpaceLink * clip_duplicate (SpaceLink *sl)
static void clip_listener (ScrArea *sa, wmNotifier *wmn)
static void clip_operatortypes (void)
static void clip_keymap (struct wmKeyConfig *keyconf)
static int clip_context (const bContext *C, const char *member, bContextDataResult *result)
static void clip_refresh (const bContext *C, ScrArea *sa)
static void movieclip_main_area_set_view2d (SpaceClip *sc, ARegion *ar)
static void clip_main_area_init (wmWindowManager *wm, ARegion *ar)
static void clip_main_area_draw (const bContext *C, ARegion *ar)
static void clip_main_area_listener (ARegion *ar, wmNotifier *wmn)
static void clip_preview_area_init (wmWindowManager *wm, ARegion *ar)
static void clip_preview_area_draw (const bContext *C, ARegion *ar)
static void clip_preview_area_listener (ARegion *UNUSED(ar), wmNotifier *UNUSED(wmn))
static void clip_header_area_init (wmWindowManager *UNUSED(wm), ARegion *ar)
static void clip_header_area_draw (const bContext *C, ARegion *ar)
static void clip_tools_area_init (wmWindowManager *wm, ARegion *ar)
static void clip_tools_area_draw (const bContext *C, ARegion *ar)
static void clip_props_area_listener (ARegion *ar, wmNotifier *wmn)
static void clip_properties_area_init (wmWindowManager *wm, ARegion *ar)
static void clip_properties_area_draw (const bContext *C, ARegion *ar)
static void clip_properties_area_listener (ARegion *ar, wmNotifier *wmn)
void ED_spacetype_clip (void)
Variables
const char * clip_context_dir [] = {"edit_movieclip", NULL}
Detailed Description
Definition in file space_clip.c.
Function Documentation
static int clip_context (const bContext * C, const char * member, bContextDataResult * result) [static]
Definition at line 616 of file space_clip.c.
References SpaceClip::clip, CTX_data_dir(), CTX_data_dir_set(), CTX_data_equals(), CTX_data_id_pointer_set(), CTX_wm_space_clip(), FALSE, MovieClip::id, and TRUE.
Referenced by ED_spacetype_clip().
static SpaceLink* clip_duplicate (SpaceLink * sl) [static]
Definition at line 225 of file space_clip.c.
References FALSE, MEM_dupallocN(), NULL, MovieClipScopes::ok, SpaceClip::scopes, and MovieClipScopes::track_preview.
Referenced by ED_spacetype_clip().
static void clip_free (SpaceLink * sl) [static]
Definition at line 209 of file space_clip.c.
References SpaceClip::clip, IMB_freeImBuf(), NULL, SpaceClip::scopes, and MovieClipScopes::track_preview.
Referenced by ED_spacetype_clip().
static ARegion* clip_has_preview_region (const bContext * C, ScrArea * sa) [static]
Definition at line 99 of file space_clip.c.
References BKE_area_find_region_type(), BLI_insertlinkbefore(), init_preview_region(), MEM_callocN(), NULL, ScrArea::regionbase, RGN_TYPE_PREVIEW, and RGN_TYPE_WINDOW.
Referenced by clip_refresh().
static void clip_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 876 of file space_clip.c.
References ED_region_header().
Referenced by ED_spacetype_clip().
static void clip_header_area_init (wmWindowManager * UNUSEDwm, ARegion * ar) [static]
Definition at line 871 of file space_clip.c.
References ED_region_header_init().
Referenced by ED_spacetype_clip().
static void clip_init (struct wmWindowManager * UNUSEDwm, ScrArea * UNUSEDsa) [static]
Definition at line 220 of file space_clip.c.
Referenced by ED_spacetype_clip().
static void clip_keymap (struct wmKeyConfig * keyconf) [static]
Definition at line 396 of file space_clip.c.
References ACTIONMOUSE, AKEY, BKEY, CKEY, DELKEY, DKEY, FALSE, FKEY, GKEY, HKEY, HOMEKEY, IKEY, JKEY, KM_ALT, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTARROWKEY, LEFTMOUSE, LKEY, MIDDLEMOUSE, MKEY, MOUSEPAN, MOUSEZOOM, NKEY, OKEY, PAD1, PAD2, PAD4, PAD8, PADMINUS, PADPERIOD, PADPLUSKEY, wmKeyMapItem::ptr, RIGHTARROWKEY, RNA_boolean_set(), RNA_enum_set(), RNA_float_set(), RNA_string_set(), SC_MODE_DISTORTION, SC_MODE_RECONSTRUCTION, SEL_INVERT, SEL_TOGGLE, SELECTMOUSE, SKEY, SPACE_CLIP, TABKEY, TKEY, TRACK_CLEAR_ALL, TRACK_CLEAR_REMAINED, TRACK_CLEAR_UPTO, transform_keymap_for_space(), TRUE, WHEELINMOUSE, WHEELOUTMOUSE, WKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), XKEY, and ZKEY.
Referenced by ED_spacetype_clip().
static void clip_listener (ScrArea * sa, wmNotifier * wmn) [static]
Definition at line 236 of file space_clip.c.
References wmNotifier::action, wmNotifier::category, clip_scopes_tag_refresh(), clip_stabilization_tag_refresh(), wmNotifier::data, ED_area_tag_redraw(), NA_EDITED, NA_EVALUATED, NA_REMOVED, NA_SELECTED, NC_GEOM, NC_MOVIECLIP, NC_SCENE, NC_SCREEN, NC_SPACE, ND_ANIMPLAY, ND_DISPLAY, ND_FRAME, ND_FRAME_RANGE, ND_SELECT, and ND_SPACE_CLIP.
Referenced by ED_spacetype_clip().
static void clip_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 761 of file space_clip.c.
References BKE_tracking_sync_user(), clip_draw_grease_pencil(), clip_draw_main(), CTX_data_scene(), CTX_wm_space_clip(), ED_clip_view_selection(), ED_space_clip(), ED_space_clip_get_stable_buffer(), MovieTrackingStabilization::flag, SpaceClip::flag, IMB_freeImBuf(), movieclip_main_area_set_view2d(), NULL, SC_LOCK_SELECTION, MovieTracking::stabilization, TH_BACK, MovieClip::tracking, TRACKING_2D_STABILIZATION, MovieClip::tracking_context, UI_ThemeClearColor(), UI_view2d_view_restore(), SpaceClip::user, SpaceClip::xlockof, SpaceClip::xof, SpaceClip::ylockof, and SpaceClip::yof.
Referenced by ED_spacetype_clip().
static void clip_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 747 of file space_clip.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, SPACE_CLIP, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_STANDARD, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_clip().
static void clip_main_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 808 of file space_clip.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NC_SCREEN, and ND_GPENCIL.
Referenced by ED_spacetype_clip().
static SpaceLink* clip_new (const bContext * C) [static]
Definition at line 153 of file space_clip.c.
References ARegion::alignment, BLI_addtail(), SpaceClip::flag, init_preview_region(), MEM_callocN(), SpaceClip::path_length, SpaceClip::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_ALIGN_LEFT, RGN_ALIGN_RIGHT, RGN_SPLIT_PREV, RGN_TYPE_HEADER, RGN_TYPE_TOOL_PROPS, RGN_TYPE_TOOLS, RGN_TYPE_UI, RGN_TYPE_WINDOW, SC_MANUAL_CALIBRATION, SC_SHOW_GRAPH_FRAMES, SC_SHOW_GRAPH_TRACKS, SC_SHOW_MARKER_PATTERN, SC_SHOW_TRACK_PATH, SpaceClip::scopes, SPACE_CLIP, SpaceClip::spacetype, MovieClipScopes::track_preview_height, and SpaceClip::zoom.
Referenced by ED_spacetype_clip().
static void clip_operatortypes (void) [static]
Definition at line 295 of file space_clip.c.
References CLIP_OT_add_marker(), CLIP_OT_change_frame(), CLIP_OT_clean_tracks(), CLIP_OT_clear_solution(), CLIP_OT_clear_track_path(), CLIP_OT_copy_tracks(), CLIP_OT_delete_marker(), CLIP_OT_delete_track(), CLIP_OT_detect_features(), CLIP_OT_disable_markers(), CLIP_OT_frame_jump(), CLIP_OT_graph_center_current_frame(), CLIP_OT_graph_delete_curve(), CLIP_OT_graph_delete_knot(), CLIP_OT_graph_disable_markers(), CLIP_OT_graph_select(), CLIP_OT_graph_select_all_markers(), CLIP_OT_graph_select_border(), CLIP_OT_graph_view_all(), CLIP_OT_hide_tracks(), CLIP_OT_hide_tracks_clear(), CLIP_OT_join_tracks(), CLIP_OT_lock_tracks(), CLIP_OT_mode_set(), CLIP_OT_open(), CLIP_OT_paste_tracks(), CLIP_OT_properties(), CLIP_OT_rebuild_proxy(), CLIP_OT_reload(), CLIP_OT_select(), CLIP_OT_select_all(), CLIP_OT_select_border(), CLIP_OT_select_circle(), CLIP_OT_select_grouped(), CLIP_OT_set_axis(), CLIP_OT_set_center_principal(), CLIP_OT_set_origin(), CLIP_OT_set_plane(), CLIP_OT_set_scale(), CLIP_OT_set_solution_scale(), CLIP_OT_slide_marker(), CLIP_OT_solve_camera(), CLIP_OT_stabilize_2d_add(), CLIP_OT_stabilize_2d_remove(), CLIP_OT_stabilize_2d_select(), CLIP_OT_stabilize_2d_set_rotation(), CLIP_OT_tools(), CLIP_OT_track_copy_color(), CLIP_OT_track_markers(), CLIP_OT_tracking_object_new(), CLIP_OT_tracking_object_remove(), CLIP_OT_view_all(), CLIP_OT_view_pan(), CLIP_OT_view_selected(), CLIP_OT_view_zoom(), CLIP_OT_view_zoom_in(), CLIP_OT_view_zoom_out(), CLIP_OT_view_zoom_ratio(), and WM_operatortype_append().
Referenced by ED_spacetype_clip().
static void clip_preview_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 835 of file space_clip.c.
References clip_draw_graph(), CTX_data_scene(), CTX_wm_space_clip(), ED_clip_graph_center_current_frame(), SpaceClip::flag, SC_LOCK_TIMECURSOR, TH_BACK, UI_ThemeClearColor(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_view_ortho(), UI_view2d_view_restore(), ARegion::v2d, V2D_GRID_NOCLAMP, V2D_UNIT_FRAMESCALE, and V2D_UNIT_VALUES.
Referenced by ED_spacetype_clip().
static void clip_preview_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 821 of file space_clip.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, SPACE_CLIP, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_CUSTOM, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_clip().
static void clip_preview_area_listener (ARegion * UNUSEDar, wmNotifier * UNUSEDwmn) [static]
Definition at line 864 of file space_clip.c.
Referenced by ED_spacetype_clip().
static void clip_properties_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 932 of file space_clip.c.
References BKE_movieclip_update_scopes(), SpaceClip::clip, CTX_wm_space_clip(), ED_region_panels(), NULL, SpaceClip::scopes, and SpaceClip::user.
Referenced by ED_spacetype_clip().
static void clip_properties_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 922 of file space_clip.c.
References wmWindowManager::defaultconf, ED_region_panels_init(), ARegion::handlers, SPACE_CLIP, WM_event_add_keymap_handler(), and WM_keymap_find().
Referenced by ED_spacetype_clip().
static void clip_properties_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 941 of file space_clip.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NA_EDITED, NC_BRUSH, NC_SCREEN, and ND_GPENCIL.
Referenced by ED_spacetype_clip().
static void clip_props_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 896 of file space_clip.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NC_SCENE, NC_SCREEN, NC_SPACE, NC_WM, ND_GPENCIL, ND_HISTORY, ND_MODE, and ND_SPACE_CLIP.
Referenced by ED_spacetype_clip().
static void clip_refresh (const bContext * C, ScrArea * sa) [static]
Definition at line 632 of file space_clip.c.
References ARegion::alignment, BKE_area_find_region_type(), BKE_movieclip_user_set_frame(), RenderData::cfra, clip_has_preview_region(), CTX_data_scene(), CTX_wm_manager(), CTX_wm_window(), View2D::cur, ED_area_initialize(), ED_area_tag_redraw(), ELEM, FALSE, ListBase::first, View2D::flag, ARegion::flag, ARegion::handlers, Scene::r, RGN_ALIGN_BOTTOM, RGN_ALIGN_NONE, RGN_ALIGN_TOP, RGN_FLAG_HIDDEN, RGN_TYPE_WINDOW, SpaceClip::runtime_flag, SC_GRAPH_BOTTOM, SC_VIEW_CLIP, SC_VIEW_GRAPH, ScrArea::spacedata, View2D::tot, TRUE, SpaceClip::user, ARegion::v2d, V2D_IS_INITIALISED, SpaceClip::view, and WM_event_remove_handlers().
Referenced by ED_spacetype_clip().
static void clip_scopes_tag_refresh (ScrArea * sa) [static]
Definition at line 122 of file space_clip.c.
References FALSE, ListBase::first, if(), SpaceClip::mode, MovieClipScopes::ok, ScrArea::regionbase, RGN_FLAG_HIDDEN, RGN_TYPE_UI, SC_MODE_TRACKING, SpaceClip::scopes, and ScrArea::spacedata.
Referenced by clip_listener().
static void clip_stabilization_tag_refresh (ScrArea * sa) [static]
Definition at line 139 of file space_clip.c.
References ED_space_clip(), FALSE, ListBase::first, MovieTrackingStabilization::ok, and ScrArea::spacedata.
Referenced by clip_listener().
static void clip_tools_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 889 of file space_clip.c.
References ED_region_panels(), and NULL.
Referenced by ED_spacetype_clip().
static void clip_tools_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 884 of file space_clip.c.
References ED_region_panels_init().
Referenced by ED_spacetype_clip().
void ED_spacetype_clip (void)
Definition at line 959 of file space_clip.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), clip_context(), clip_duplicate(), clip_free(), clip_header_area_draw(), clip_header_area_init(), clip_init(), clip_keymap(), clip_listener(), clip_main_area_draw(), clip_main_area_init(), clip_main_area_listener(), clip_new(), clip_operatortypes(), clip_preview_area_draw(), clip_preview_area_init(), clip_preview_area_listener(), clip_properties_area_draw(), clip_properties_area_init(), clip_properties_area_listener(), clip_props_area_listener(), clip_refresh(), clip_tools_area_draw(), clip_tools_area_init(), SpaceType::context, ARegionType::draw, SpaceType::duplicate, ED_clip_buttons_register(), ED_clip_tool_props_register(), ED_KEYMAP_FRAMES, ED_KEYMAP_GPENCIL, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_PREVIEW, RGN_TYPE_TOOL_PROPS, RGN_TYPE_TOOLS, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_CLIP, SpaceType::spaceid, and UI_COMPACT_PANEL_WIDTH.
Referenced by ED_spacetypes_init().
static void init_preview_region (const bContext * C, ARegion * ar) [static]
Definition at line 72 of file space_clip.c.
References ARegion::alignment, CTX_data_scene(), View2D::cur, RenderData::efra, ARegion::flag, FLT_MAX, View2D::keeptot, View2D::max, MAXFRAMEF, View2D::min, Scene::r, ARegion::regiontype, RGN_ALIGN_TOP, RGN_FLAG_HIDDEN, RGN_TYPE_PREVIEW, View2D::scroll, View2D::tot, ARegion::v2d, V2D_SCROLL_BOTTOM, V2D_SCROLL_LEFT, V2D_SCROLL_SCALE_HORIZONTAL, V2D_SCROLL_SCALE_VERTICAL, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by clip_has_preview_region(), and clip_new().
static void movieclip_main_area_set_view2d (SpaceClip * sc, ARegion * ar) [static]
Definition at line 698 of file space_clip.c.
References MovieClip::aspx, MovieClip::aspy, MovieTracking::camera, View2D::cur, ED_space_clip(), ED_space_clip_size(), View2D::mask, MovieTrackingCamera::pixel_aspect, View2D::tot, MovieClip::tracking, ARegion::v2d, ARegion::winrct, rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, SpaceClip::xof, rctf::ymax, rcti::ymax, rctf::ymin, rcti::ymin, SpaceClip::yof, and SpaceClip::zoom.
Referenced by clip_main_area_draw().
Variable Documentation
const char* clip_context_dir[] = {"edit_movieclip", NULL}
Definition at line 614 of file space_clip.c.