Blender: ED_render.h File Reference
ED_render.h File Reference
Editors
#include "DNA_vec_types.h"
Classes
struct RenderInfo
Defines
#define PR_DBASE 1
#define PR_DISPRECT 2
#define PR_PROJECTED 4
#define PR_ROTATED 8
#define PR_BUTS_RENDER 0
#define PR_ICON_RENDER 1
#define PR_NODE_RENDER 2
Typedefs
typedef struct RenderInfo RenderInfo
Functions
void ED_operatortypes_render (void)
void ED_render_id_flush_update (struct Main *bmain, struct ID *id)
void ED_render_engine_changed (struct Main *bmain)
void ED_render_engine_area_exit (struct ScrArea *sa)
void ED_render_scene_update (struct Main *bmain, struct Scene *scene, int updated)
void ED_preview_init_dbase (void)
void ED_preview_free_dbase (void)
void ED_preview_shader_job (const struct bContext *C, void *owner, struct ID *id, struct ID *parent, struct MTex *slot, int sizex, int sizey, int method)
void ED_preview_icon_job (const struct bContext *C, void *owner, struct ID *id, unsigned int *rect, int sizex, int sizey)
void ED_preview_kill_jobs (const struct bContext *C)
void ED_preview_draw (const struct bContext *C, void *idp, void *parentp, void *slot, rcti *rect)
void ED_render_clear_mtex_copybuf (void)
Detailed Description
Definition in file ED_render.h.
Define Documentation
#define PR_BUTS_RENDER 0
Definition at line 79 of file ED_render.h.
Referenced by ED_preview_draw(), and shader_preview_render().
#define PR_DBASE 1
Definition at line 66 of file ED_render.h.
#define PR_DISPRECT 2
Definition at line 67 of file ED_render.h.
Referenced by panel_activate_state().
#define PR_ICON_RENDER 1
Definition at line 80 of file ED_render.h.
Referenced by common_preview_startjob(), icon_preview_startjob_all_sizes(), preview_prepare_scene(), and shader_preview_render().
#define PR_NODE_RENDER 2
Definition at line 81 of file ED_render.h.
Referenced by node_area_refresh(), preview_prepare_scene(), shader_preview_render(), and shader_preview_updatejob().
#define PR_PROJECTED 4
Definition at line 68 of file ED_render.h.
#define PR_ROTATED 8
Definition at line 69 of file ED_render.h.
Typedef Documentation
typedef struct RenderInfo RenderInfo
Function Documentation
void ED_operatortypes_render (void)
Definition at line 46 of file render_ops.c.
References MATERIAL_OT_copy(), MATERIAL_OT_new(), MATERIAL_OT_paste(), OBJECT_OT_material_slot_add(), OBJECT_OT_material_slot_assign(), OBJECT_OT_material_slot_copy(), OBJECT_OT_material_slot_deselect(), OBJECT_OT_material_slot_remove(), OBJECT_OT_material_slot_select(), RENDER_OT_opengl(), RENDER_OT_render(), RENDER_OT_view_cancel(), RENDER_OT_view_show(), SCENE_OT_render_layer_add(), SCENE_OT_render_layer_remove(), TEXTURE_OT_envmap_clear(), TEXTURE_OT_envmap_clear_all(), TEXTURE_OT_envmap_save(), TEXTURE_OT_new(), TEXTURE_OT_slot_copy(), TEXTURE_OT_slot_move(), TEXTURE_OT_slot_paste(), WM_operatortype_append(), and WORLD_OT_new().
Referenced by ED_spacetypes_init().
void ED_preview_draw (const struct bContext * C, void * idp, void * parentp, void * slot, rcti * rect)
Referenced by uiTemplatePreview().
void ED_preview_free_dbase (void)
Definition at line 203 of file render_preview.c.
References free_main().
Referenced by WM_exit_ext().
void ED_preview_icon_job (const struct bContext * C, void * owner, struct ID * id, unsigned int * rect, int sizex, int sizey)
Referenced by icon_set_image().
void ED_preview_init_dbase (void)
Definition at line 184 of file render_preview.c.
References BLO_read_from_memory(), datatoc_preview_blend, datatoc_preview_blend_size, G, G_FILE_NO_UI, BlendFileData::main, MEM_freeN(), and NULL.
Referenced by WM_init().
void ED_preview_kill_jobs (const struct bContext * C)
Definition at line 1083 of file render_preview.c.
References common_preview_startjob(), CTX_wm_manager(), NULL, and WM_jobs_kill().
Referenced by cut_links_exec(), detach_links_exec(), image_open_exec(), image_reload_exec(), image_replace_exec(), image_unpack_exec(), node_active_link_viewer(), node_add_file_exec(), node_delete_exec(), node_delete_reconnect_exec(), node_duplicate_exec(), node_group_edit_exec(), node_group_make_exec(), node_group_socket_add_exec(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_socket_remove_exec(), node_group_ungroup_exec(), node_link_invoke(), node_make_link_exec(), node_mute_exec(), node_preview_toggle_exec(), node_read_renderlayers_exec(), and node_socket_toggle_exec().
void ED_preview_shader_job (const struct bContext * C, void * owner, struct ID * id, struct ID * parent, struct MTex * slot, int sizex, int sizey, int method)
Referenced by ED_preview_draw(), and node_area_refresh().
void ED_render_clear_mtex_copybuf (void)
Definition at line 885 of file render_shading.c.
Referenced by copy_mtex_exec(), and WM_init().
void ED_render_engine_area_exit (struct ScrArea * sa)
Definition at line 119 of file render_update.c.
References ListBase::first, ARegion::next, NULL, RE_engine_free(), ScrArea::regionbase, ARegion::regiondata, ARegion::regiontype, RegionView3D::render_engine, RGN_TYPE_WINDOW, SPACE_VIEW3D, and ScrArea::spacetype.
Referenced by ED_area_exit(), and ED_render_engine_changed().
void ED_render_engine_changed (struct Main * bmain)
Definition at line 142 of file render_update.c.
References bScreen::areabase, ED_render_engine_area_exit(), ListBase::first, bScreen::id, ScrArea::next, ID::next, and Main::screen.
Referenced by ED_screen_set_scene().
void ED_render_id_flush_update (struct Main * bmain, struct ID * id)
Definition at line 348 of file render_update.c.
References GS, ID_IM, ID_LA, ID_MA, ID_SCE, ID_TE, ID_WO, image_changed(), lamp_changed(), material_changed(), ID::name, scene_changed(), texture_changed(), and world_changed().
Referenced by ED_object_add_duplicate(), ED_object_add_type(), and WM_init().
void ED_render_scene_update (struct Main * bmain, struct Scene * scene, int updated)
Definition at line 69 of file render_update.c.
References bScreen::areabase, BLI_thread_is_main(), C, CTX_create(), CTX_data_main_set(), CTX_data_scene_set(), CTX_free(), CTX_wm_area_set(), CTX_wm_manager_set(), CTX_wm_region_set(), CTX_wm_screen_set(), ListBase::first, RenderEngine::flag, bScreen::id, ARegion::next, ScrArea::next, ID::next, RE_ENGINE_DO_UPDATE, ScrArea::regionbase, ARegion::regiondata, ARegion::regiontype, RegionView3D::render_engine, RGN_TYPE_WINDOW, Main::screen, SPACE_VIEW3D, ScrArea::spacetype, RenderEngine::type, RenderEngineType::view_update, and Main::wm.
Referenced by WM_init().