Blender: MenuType Struct Reference
MenuType Struct Reference
#include <BKE_screen.h>
Public Attributes
struct MenuType * next
struct MenuType * prev
char idname [BKE_ST_MAXNAME]
char label [BKE_ST_MAXNAME]
char * description
int(* poll)(const struct bContext *, struct MenuType *)
void(* draw)(const struct bContext *, struct Menu *)
ExtensionRNA ext
Detailed Description
Definition at line 205 of file BKE_screen.h.
Member Data Documentation
char* MenuType::description
Definition at line 210 of file BKE_screen.h.
Referenced by uiItemM().
void(* MenuType::draw)(const struct bContext *, struct Menu *)
Definition at line 215 of file BKE_screen.h.
Referenced by node_menus_register(), recent_files_menu_register(), ui_item_menutype_func(), uiPupMenuInvoke(), and wm_block_create_splash().
ExtensionRNA MenuType::ext
Definition at line 218 of file BKE_screen.h.
Referenced by WM_menutype_free().
char MenuType::idname[BKE_ST_MAXNAME]
Definition at line 208 of file BKE_screen.h.
Referenced by node_menus_register(), recent_files_menu_register(), ui_menu_block_set_keymaps(), ui_tooltip_create(), WM_menutype_add(), and WM_menutype_freelink().
char MenuType::label[BKE_ST_MAXNAME]
Definition at line 209 of file BKE_screen.h.
Referenced by node_menus_register(), recent_files_menu_register(), uiItemM(), and uiPupMenuInvoke().
struct MenuType* MenuType::next
Definition at line 206 of file BKE_screen.h.
int(* MenuType::poll)(const struct bContext *, struct MenuType *)
Definition at line 213 of file BKE_screen.h.
Referenced by uiPupMenuInvoke().
struct MenuType * MenuType::prev
Definition at line 206 of file BKE_screen.h.
The documentation for this struct was generated from the following file:
BKE_screen.h