Blender: node_texture_viewer.c File Reference
node_texture_viewer.c File Reference
texnodes
#include "node_texture_util.h"
#include "NOD_texture.h"
#include <math.h>
Functions
static void exec (void *data, bNode *node, bNodeStack **in, bNodeStack **UNUSED(out))
void register_node_type_tex_viewer (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate inputs []
static bNodeSocketTemplate outputs []
Detailed Description
Definition in file node_texture_viewer.c.
Function Documentation
static void exec (void * data, bNode * node, bNodeStack ** in, bNodeStack ** UNUSEDout) [static]
Definition at line 45 of file node_texture_viewer.c.
References TexCallData::do_preview, params_from_cdata(), TexParams::previewco, tex_do_preview(), tex_input_rgba(), and TexCallData::thread.
Referenced by register_node_type_tex_viewer().
void register_node_type_tex_viewer (bNodeTreeType * ttype)
Definition at line 59 of file node_texture_viewer.c.
References exec(), NODE_CLASS_OUTPUT, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), NULL, and TEX_NODE_VIEWER.
Referenced by registerTextureNodes().
Variable Documentation
bNodeSocketTemplate inputs[] [static]
Initial value:
 {
    { SOCK_RGBA, 1, "Color", 1.0f, 0.0f, 0.0f, 1.0f },
    { -1, 0, "" }
}
Definition at line 37 of file node_texture_viewer.c.
bNodeSocketTemplate outputs[] [static]
Initial value:
 {
    { -1, 0, "" }
}
Definition at line 41 of file node_texture_viewer.c.