Blender: node_composite_directionalblur.c File Reference
node_composite_directionalblur.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static CompBuf * dblur (bNode *node, CompBuf *img, int iterations, int wrap, float center_x, float center_y, float dist, float angle, float spin, float zoom)
static void node_composit_exec_dblur (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_composit_init_dblur (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_dblur (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_dblur_in []
static bNodeSocketTemplate cmp_node_dblur_out []
Detailed Description
Definition in file node_composite_directionalblur.c.
Function Documentation
static CompBuf* dblur (bNode * node, CompBuf * img, int iterations, int wrap, float center_x, float center_y, float dist, float angle, float spin, float zoom) [static]
Definition at line 45 of file node_composite_directionalblur.c.
References angle(), cosf, D(), dupalloc_compbuf(), bNode::exec, free_compbuf(), i, NODE_BREAK, p, powf, qd_getPixelLerp(), qd_getPixelLerpWrap(), CompBuf::rect, rot, sinf, sqrtf, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_dblur().
static void node_composit_exec_dblur (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 110 of file node_composite_directionalblur.c.
References NodeDBlurData::angle, CB_RGBA, NodeDBlurData::center_x, NodeDBlurData::center_y, bNodeStack::data, dblur(), NodeDBlurData::distance, dupalloc_compbuf(), NodeDBlurData::iter, NULL, NodeDBlurData::spin, bNode::storage, CompBuf::type, typecheck_compbuf(), NodeDBlurData::wrap, and NodeDBlurData::zoom.
Referenced by register_node_type_cmp_dblur().
static void node_composit_init_dblur (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 125 of file node_composite_directionalblur.c.
References NodeDBlurData::center_x, NodeDBlurData::center_y, MEM_callocN(), and bNode::storage.
Referenced by register_node_type_cmp_dblur().
void register_node_type_cmp_dblur (bNodeTreeType * ttype)
Definition at line 133 of file node_composite_directionalblur.c.
References CMP_NODE_DBLUR, NODE_CLASS_OP_FILTER, node_composit_exec_dblur(), node_composit_init_dblur(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_dblur_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image", 1.0f, 1.0f, 1.0f, 1.f},
    {   -1, 0, ""       }
}
Definition at line 35 of file node_composite_directionalblur.c.
bNodeSocketTemplate cmp_node_dblur_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""       }
}
Definition at line 40 of file node_composite_directionalblur.c.