Blender: btHashMap< Key, Value > Class Template Reference
btHashMap< Key, Value > Class Template Reference
#include <btHashMap.h>
Public Member Functions
void insert (const Key &key, const Value &value)
void remove (const Key &key)
int size () const
const Value * getAtIndex (int index) const
Value * getAtIndex (int index)
Value * operator[] (const Key &key)
const Value * find (const Key &key) const
Value * find (const Key &key)
int findIndex (const Key &key) const
void clear ()
Protected Member Functions
void growTables (const Key &)
Protected Attributes
btAlignedObjectArray< int > m_hashTable
btAlignedObjectArray< int > m_next
btAlignedObjectArray< Value > m_valueArray
btAlignedObjectArray< Key > m_keyArray
Detailed Description
template<class Key, class Value>
class btHashMap< Key, Value >
The btHashMap template class implements a generic and lightweight hashmap. A basic sample of how to use btHashMap is located in Demos\BasicDemo\main.cpp
Definition at line 204 of file btHashMap.h.
Member Function Documentation
template<class Key, class Value> void btHashMap< Key, Value >::clear () [inline]
Definition at line 424 of file btHashMap.h.
Referenced by btSoftBodyTriangleCallback::clearCache(), and btDefaultSerializer::finishSerialization().
template<class Key, class Value> const Value* btHashMap< Key, Value >::find (const Key & key) const [inline]
Definition at line 386 of file btHashMap.h.
Referenced by btAdjustInternalEdgeContacts(), btDefaultSerializer::findNameForPointer(), btDefaultSerializer::findPointer(), btDefaultSerializer::getReverseType(), btDefaultSerializer::getUniquePointer(), btHashMap< btHashPtr, btPointerUid >::operator[](), btConnectivityProcessor::processTriangle(), btSoftBody::serialize(), and btCollisionWorld::serializeCollisionObjects().
template<class Key, class Value> Value* btHashMap< Key, Value >::find (const Key & key) [inline]
Definition at line 396 of file btHashMap.h.
template<class Key, class Value> int btHashMap< Key, Value >::findIndex (const Key & key) const [inline]
Definition at line 407 of file btHashMap.h.
Referenced by btHashMap< btHashPtr, btPointerUid >::find(), btHashMap< btHashPtr, btPointerUid >::insert(), and btHashMap< btHashPtr, btPointerUid >::remove().
template<class Key, class Value> const Value* btHashMap< Key, Value >::getAtIndex (int index) const [inline]
Definition at line 368 of file btHashMap.h.
Referenced by btSoftBodyTriangleCallback::clearCache().
template<class Key, class Value> Value* btHashMap< Key, Value >::getAtIndex (int index) [inline]
Definition at line 375 of file btHashMap.h.
template<class Key, class Value> void btHashMap< Key, Value >::growTables (const Key &) [inline, protected]
Definition at line 214 of file btHashMap.h.
Referenced by btHashMap< btHashPtr, btPointerUid >::insert().
template<class Key, class Value> void btHashMap< Key, Value >::insert (const Key & key, const Value & value) [inline]
Definition at line 253 of file btHashMap.h.
Referenced by btDefaultSerializer::finalizeChunk(), btDefaultSerializer::getUniquePointer(), btDefaultSerializer::initDNA(), btSoftBodyTriangleCallback::processTriangle(), btConnectivityProcessor::processTriangle(), btDefaultSerializer::registerNameForPointer(), btSoftBody::serialize(), and btCollisionWorld::serializeCollisionObjects().
template<class Key, class Value> Value* btHashMap< Key, Value >::operator[] (const Key & key) [inline]
Definition at line 382 of file btHashMap.h.
template<class Key, class Value> void btHashMap< Key, Value >::remove (const Key & key) [inline]
Definition at line 280 of file btHashMap.h.
template<class Key, class Value> int btHashMap< Key, Value >::size () const [inline]
Definition at line 363 of file btHashMap.h.
Referenced by btSoftBodyTriangleCallback::clearCache().
Member Data Documentation
template<class Key, class Value> btAlignedObjectArray<int> btHashMap< Key, Value >::m_hashTable [protected]
Definition at line 208 of file btHashMap.h.
Referenced by btHashMap< btHashPtr, btPointerUid >::clear(), btTriangleInfoMap::deSerialize(), btHashMap< btHashPtr, btPointerUid >::findIndex(), btHashMap< btHashPtr, btPointerUid >::growTables(), btHashMap< btHashPtr, btPointerUid >::insert(), btHashMap< btHashPtr, btPointerUid >::remove(), and btTriangleInfoMap::serialize().
template<class Key, class Value> btAlignedObjectArray<Key> btHashMap< Key, Value >::m_keyArray [protected]
Definition at line 212 of file btHashMap.h.
Referenced by btHashMap< btHashPtr, btPointerUid >::clear(), btTriangleInfoMap::deSerialize(), btHashMap< btHashPtr, btPointerUid >::findIndex(), btHashMap< btHashPtr, btPointerUid >::growTables(), btHashMap< btHashPtr, btPointerUid >::insert(), btHashMap< btHashPtr, btPointerUid >::remove(), and btTriangleInfoMap::serialize().
template<class Key, class Value> btAlignedObjectArray<int> btHashMap< Key, Value >::m_next [protected]
Definition at line 209 of file btHashMap.h.
Referenced by btHashMap< btHashPtr, btPointerUid >::clear(), btTriangleInfoMap::deSerialize(), btHashMap< btHashPtr, btPointerUid >::findIndex(), btHashMap< btHashPtr, btPointerUid >::growTables(), btHashMap< btHashPtr, btPointerUid >::insert(), btHashMap< btHashPtr, btPointerUid >::remove(), and btTriangleInfoMap::serialize().
template<class Key, class Value> btAlignedObjectArray<Value> btHashMap< Key, Value >::m_valueArray [protected]
Definition at line 211 of file btHashMap.h.
Referenced by btHashMap< btHashPtr, btPointerUid >::clear(), btTriangleInfoMap::deSerialize(), btHashMap< btHashPtr, btPointerUid >::find(), btHashMap< btHashPtr, btPointerUid >::findIndex(), btHashMap< btHashPtr, btPointerUid >::getAtIndex(), btHashMap< btHashPtr, btPointerUid >::growTables(), btHashMap< btHashPtr, btPointerUid >::insert(), btHashMap< btHashPtr, btPointerUid >::remove(), btTriangleInfoMap::serialize(), and btHashMap< btHashPtr, btPointerUid >::size().
The documentation for this class was generated from the following file:
btHashMap.h