Blender: device_vector< T > Class Template Reference
device_vector< T > Class Template Reference
#include <device_memory.h>
Public Member Functions
device_vector ()
virtual ~device_vector ()
T * resize (size_t width, size_t height=0)
T * copy (T *ptr, size_t width, size_t height=0)
void reference (T *ptr, size_t width, size_t height=0)
void clear ()
size_t size ()
Detailed Description
template<typename T>
class device_vector< T >
Definition at line 181 of file device_memory.h.
Constructor & Destructor Documentation
template<typename T> device_vector< T >::device_vector () [inline]
Definition at line 184 of file device_memory.h.
template<typename T> virtual device_vector< T >::~device_vector () [inline, virtual]
Definition at line 198 of file device_memory.h.
Member Function Documentation
template<typename T> void device_vector< T >::clear () [inline]
Definition at line 228 of file device_memory.h.
Referenced by SVMShaderManager::device_free(), ObjectManager::device_free(), MeshManager::device_free(), LightManager::device_free(), Integrator::device_free(), Filter::device_free(), DisplayBuffer::device_free(), RenderBuffers::device_free(), ShaderManager::device_free_common(), and LightManager::device_update_distribution().
template<typename T> T* device_vector< T >::copy (T * ptr, size_t width, size_t height = 0) [inline]
Definition at line 212 of file device_memory.h.
Referenced by SVMShaderManager::device_update(), Filter::device_update(), and MeshManager::device_update_attributes().
template<typename T> void device_vector< T >::reference (T * ptr, size_t width, size_t height = 0) [inline]
Definition at line 219 of file device_memory.h.
Referenced by MeshManager::device_update_bvh().
template<typename T> T* device_vector< T >::resize (size_t width, size_t height = 0) [inline]
Definition at line 201 of file device_memory.h.
Referenced by device_vector< uint4 >::copy(), Integrator::device_update(), LightManager::device_update_background(), ShaderManager::device_update_common(), LightManager::device_update_distribution(), MeshManager::device_update_mesh(), LightManager::device_update_points(), ObjectManager::device_update_transforms(), MeshManager::displace(), dump_background_pixels(), DisplayBuffer::reset(), RenderBuffers::reset(), and MeshManager::update_svm_attributes().
template<typename T> size_t device_vector< T >::size () [inline]
Definition at line 237 of file device_memory.h.
Referenced by MeshManager::displace(), dump_background_pixels(), and MeshManager::update_svm_attributes().
The documentation for this class was generated from the following file:
device_memory.h