Blender: transform_manipulator.c File Reference
transform_manipulator.c File Reference
transform
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include <unistd.h>
#include "MEM_guardedalloc.h"
#include "DNA_armature_types.h"
#include "DNA_curve_types.h"
#include "DNA_lattice_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meta_types.h"
#include "DNA_screen_types.h"
#include "DNA_scene_types.h"
#include "DNA_view3d_types.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "RNA_access.h"
#include "BKE_action.h"
#include "BKE_context.h"
#include "BKE_curve.h"
#include "BKE_global.h"
#include "BKE_mesh.h"
#include "BKE_particle.h"
#include "BKE_pointcache.h"
#include "BKE_tessmesh.h"
#include "BIF_gl.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_armature.h"
#include "ED_curve.h"
#include "ED_mesh.h"
#include "ED_particle.h"
#include "ED_view3d.h"
#include "UI_resources.h"
#include "transform.h"
Defines
#define MAN_TRANS_X 1
#define MAN_TRANS_Y 2
#define MAN_TRANS_Z 4
#define MAN_TRANS_C 7
#define MAN_ROT_X 8
#define MAN_ROT_Y 16
#define MAN_ROT_Z 32
#define MAN_ROT_V 64
#define MAN_ROT_T 128
#define MAN_ROT_C 248
#define MAN_SCALE_X 256
#define MAN_SCALE_Y 512
#define MAN_SCALE_Z 1024
#define MAN_SCALE_C 1792
#define MAN_RGB 0
#define MAN_GHOST 1
#define MAN_MOVECOL 2
Functions
static void calc_tw_center (Scene *scene, float *co)
static void protectflag_to_drawflags (short protectflag, short *drawflags)
static void stats_pose (Scene *scene, RegionView3D *rv3d, bPoseChannel *pchan)
static void stats_editbone (RegionView3D *rv3d, EditBone *ebo)
static void axis_angle_to_gimbal_axis (float gmat[3][3], float axis[3], float angle)
static int test_rotmode_euler (short rotmode)
int gimbal_axis (Object *ob, float gmat[][3])
int calc_manipulator_stats (const bContext *C)
static void test_manipulator_axis (const bContext *C)
static float screen_aligned (RegionView3D *rv3d, float mat[][4])
static void partial_doughnut (float radring, float radhole, int start, int end, int nsides, int nrings)
static char axisBlendAngle (float angle)
static void manipulator_setcolor (View3D *v3d, char axis, int colcode, unsigned char alpha)
static void draw_manipulator_axes (View3D *v3d, RegionView3D *rv3d, int colcode, int flagx, int flagy, int flagz)
static void preOrthoFront (int ortho, float twmat[][4], int axis)
static void postOrtho (int ortho)
static void draw_manipulator_rotate (View3D *v3d, RegionView3D *rv3d, int moving, int drawflags, int combo)
static void drawsolidcube (float size)
static void draw_manipulator_scale (View3D *v3d, RegionView3D *rv3d, int moving, int drawflags, int combo, int colcode)
static void draw_cone (GLUquadricObj *qobj, float len, float width)
static void draw_cylinder (GLUquadricObj *qobj, float len, float width)
static void draw_manipulator_translate (View3D *v3d, RegionView3D *rv3d, int UNUSED(moving), int drawflags, int combo, int colcode)
static void draw_manipulator_rotate_cyl (View3D *v3d, RegionView3D *rv3d, int moving, int drawflags, int combo, int colcode)
void BIF_draw_manipulator (const bContext *C)
static int manipulator_selectbuf (ScrArea *sa, ARegion *ar, const int mval[2], float hotspot)
int BIF_do_manipulator (bContext *C, struct wmEvent *event, wmOperator *op)
Variables
static int drawflags = 0xFFFF
Detailed Description
Definition in file transform_manipulator.c.
Define Documentation
#define MAN_GHOST 1
Definition at line 107 of file transform_manipulator.c.
Referenced by draw_manipulator_translate(), and manipulator_setcolor().
#define MAN_MOVECOL 2
Definition at line 108 of file transform_manipulator.c.
Referenced by BIF_draw_manipulator(), draw_manipulator_rotate(), and manipulator_setcolor().
#define MAN_RGB 0
Definition at line 106 of file transform_manipulator.c.
Referenced by BIF_draw_manipulator(), draw_manipulator_rotate(), and manipulator_selectbuf().
#define MAN_ROT_C 248
Definition at line 97 of file transform_manipulator.c.
Referenced by BIF_do_manipulator(), draw_manipulator_rotate(), draw_manipulator_rotate_cyl(), and manipulator_selectbuf().
#define MAN_ROT_T 128
Definition at line 96 of file transform_manipulator.c.
Referenced by BIF_do_manipulator(), and draw_manipulator_rotate().
#define MAN_ROT_V 64
Definition at line 95 of file transform_manipulator.c.
Referenced by draw_manipulator_rotate(), and draw_manipulator_rotate_cyl().
#define MAN_ROT_X 8
Definition at line 92 of file transform_manipulator.c.
Referenced by BIF_do_manipulator(), draw_manipulator_rotate(), draw_manipulator_rotate_cyl(), and protectflag_to_drawflags().
#define MAN_ROT_Y 16
Definition at line 93 of file transform_manipulator.c.
Referenced by BIF_do_manipulator(), draw_manipulator_rotate(), draw_manipulator_rotate_cyl(), and protectflag_to_drawflags().
#define MAN_ROT_Z 32
Definition at line 94 of file transform_manipulator.c.
Referenced by BIF_do_manipulator(), draw_manipulator_rotate(), draw_manipulator_rotate_cyl(), and protectflag_to_drawflags().
#define MAN_SCALE_C 1792
Definition at line 102 of file transform_manipulator.c.
Referenced by BIF_do_manipulator(), draw_manipulator_scale(), and manipulator_selectbuf().
#define MAN_SCALE_X 256
Definition at line 99 of file transform_manipulator.c.
Referenced by BIF_do_manipulator(), draw_manipulator_axes(), draw_manipulator_scale(), protectflag_to_drawflags(), and test_manipulator_axis().
#define MAN_SCALE_Y 512
Definition at line 100 of file transform_manipulator.c.
Referenced by BIF_do_manipulator(), draw_manipulator_axes(), draw_manipulator_scale(), protectflag_to_drawflags(), and test_manipulator_axis().
#define MAN_SCALE_Z 1024
Definition at line 101 of file transform_manipulator.c.
Referenced by BIF_do_manipulator(), draw_manipulator_axes(), draw_manipulator_scale(), protectflag_to_drawflags(), and test_manipulator_axis().
#define MAN_TRANS_C 7
Definition at line 90 of file transform_manipulator.c.
Referenced by BIF_do_manipulator(), draw_manipulator_translate(), and manipulator_selectbuf().
#define MAN_TRANS_X 1
Definition at line 87 of file transform_manipulator.c.
Referenced by BIF_do_manipulator(), draw_manipulator_axes(), draw_manipulator_translate(), protectflag_to_drawflags(), and test_manipulator_axis().
#define MAN_TRANS_Y 2
Definition at line 88 of file transform_manipulator.c.
Referenced by BIF_do_manipulator(), draw_manipulator_axes(), draw_manipulator_translate(), protectflag_to_drawflags(), and test_manipulator_axis().
#define MAN_TRANS_Z 4
Definition at line 89 of file transform_manipulator.c.
Referenced by BIF_do_manipulator(), draw_manipulator_axes(), draw_manipulator_translate(), protectflag_to_drawflags(), and test_manipulator_axis().
Function Documentation
static void axis_angle_to_gimbal_axis (float gmat[3][3], float axis[3], float angle) [static]
Definition at line 166 of file transform_manipulator.c.
References axis_angle_to_quat(), copy_v3_v3(), cross_v3_v3v3(), M_PI, mul_qt_v3(), normalize_m3(), and normalize_v3().
Referenced by gimbal_axis().
static char axisBlendAngle (float angle) [static]
Definition at line 736 of file transform_manipulator.c.
Referenced by draw_manipulator_axes(), draw_manipulator_scale(), and draw_manipulator_translate().
int BIF_do_manipulator (bContext * C, struct wmEvent * event, wmOperator * op)
Definition at line 1618 of file transform_manipulator.c.
References CTX_wm_area(), CTX_wm_region(), ListBase::first, MAN_ROT_C, MAN_ROT_T, MAN_ROT_X, MAN_ROT_Y, MAN_ROT_Z, MAN_SCALE_C, MAN_SCALE_X, MAN_SCALE_Y, MAN_SCALE_Z, MAN_TRANS_C, MAN_TRANS_X, MAN_TRANS_Y, MAN_TRANS_Z, manipulator_selectbuf(), wmEvent::mval, wmOperator::ptr, RNA_boolean_set_array(), RNA_enum_set(), ScrArea::spacedata, View3D::twflag, View3D::twmode, V3D_DRAW_MANIPULATOR, V3D_USE_MANIPULATOR, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by manipulator_invoke().
void BIF_draw_manipulator (const bContext * C)
Definition at line 1464 of file transform_manipulator.c.
References View3D::around, calc_manipulator_stats(), copy_v3_v3(), CTX_data_scene(), CTX_wm_area(), CTX_wm_region(), draw_manipulator_rotate(), draw_manipulator_rotate_cyl(), draw_manipulator_scale(), draw_manipulator_translate(), ED_view3d_pixel_size(), ListBase::first, G, give_cursor(), MAN_MOVECOL, MAN_RGB, Object::mode, mul_mat3_m4_fl(), NULL, OB_MODE_POSE, OBACT, Scene::obedit, Object::obmat, ARegion::regiondata, ScrArea::spacedata, test_manipulator_axis(), Scene::twcent, RegionView3D::twdrawflag, View3D::twflag, RegionView3D::twmat, Scene::twmax, Scene::twmin, View3D::twtype, V3D_ACTIVE, V3D_CENTER, V3D_CENTROID, V3D_CURSOR, V3D_DRAW_MANIPULATOR, V3D_LOCAL, V3D_MANIP_ROTATE, V3D_MANIP_SCALE, V3D_MANIP_TRANSLATE, and V3D_USE_MANIPULATOR.
int calc_manipulator_stats (const bContext * C)
Definition at line 271 of file transform_manipulator.c.
References applyTransformOrientation(), View3D::around, Scene::base, Nurb::bezt, BMEditMesh::bm, BM_EDGES_OF_VERT, BM_editselection_center(), BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_FACES_OF_VERT, BM_ITER_ELEM, BM_ITER_MESH, BM_select_history_active_get(), BM_VERTS_OF_MESH, BMEdit_FromObject(), BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, Nurb::bp, calc_tw_center(), bPose::chanbase, PTCacheEditKey::co, BMVert::co, copy_m3_m4(), copy_m4_m3(), copy_m4_m4(), count_set_pose_transflags(), CTX_data_edit_object(), CTX_data_scene(), CTX_data_tool_settings(), CTX_wm_area(), CTX_wm_region(), CU_BEZIER, CU_HIDE_HANDLES, curve_editnurbs(), Object::data, Lattice::def, Curve::drawflag, EBONE_VISIBLE, ED_curve_actSelection(), ED_getTransformOrientationMatrix(), bArmature::edbo, MetaBall::editelems, Lattice::editlatt, ELEM, BPoint::f1, BezTriple::f1, BezTriple::f2, BezTriple::f3, ListBase::first, Object::flag, PTCacheEditKey::flag, PTCacheEditPoint::flag, EditBone::flag, gimbal_axis(), EditBone::head, INIT_MINMAX, PTCacheEditPoint::keys, EditLatt::latt, View3D::lay, Object::lay, Object::mode, mul_m4_v3(), mul_v3_fl(), Base::next, bPoseChannel::next, Nurb::next, EditBone::next, normalize_m3(), normalize_m4(), NULL, OB_ARMATURE, OB_CURVE, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_ALL_PAINT, OB_MODE_PARTICLE_EDIT, OB_MODE_POSE, OB_SURF, OBACT, Base::object, Object::obmat, PE_get_current(), PEK_SELECT, PEK_USE_WCO, PEP_HIDE, Lattice::pntsu, Nurb::pntsu, Lattice::pntsv, Nurb::pntsv, Lattice::pntsw, PTCacheEdit::points, Object::pose, Object::protectflag, protectflag_to_drawflags(), ARegion::regiondata, SCE_SELECT_EDGE, SCE_SELECT_VERTEX, SELECT, ToolSettings::selectmode, ScrArea::spacedata, stats_editbone(), stats_pose(), EditBone::tail, TESTBASELIB, TFM_ROTATION, PTCacheEdit::totpoint, Scene::twcent, RegionView3D::twdrawflag, RegionView3D::twmat, Scene::twmax, Scene::twmin, View3D::twmode, Nurb::type, Object::type, unit_m4(), V3D_ACTIVE, V3D_MANIP_GIMBAL, V3D_MANIP_GLOBAL, V3D_MANIP_LOCAL, V3D_MANIP_NORMAL, V3D_MANIP_VIEW, BPoint::vec, BezTriple::vec, RegionView3D::viewinv, PTCacheEditKey::world_co, and zero_v3().
static void calc_tw_center (Scene * scene, float * co) [static]
Definition at line 111 of file transform_manipulator.c.
References add_v3_v3(), DO_MINMAX, max, min, Scene::twcent, Scene::twmax, and Scene::twmin.
Referenced by calc_manipulator_stats(), and stats_pose().
static void draw_cone (GLUquadricObj * qobj, float len, float width) [static]
Definition at line 1255 of file transform_manipulator.c.
Referenced by draw_manipulator_translate().
static void draw_cylinder (GLUquadricObj * qobj, float len, float width) [static]
Definition at line 1265 of file transform_manipulator.c.
Referenced by draw_manipulator_rotate_cyl().
static void draw_manipulator_axes (View3D * v3d, RegionView3D * rv3d, int colcode, int flagx, int flagy, int flagz) [static]
Definition at line 798 of file transform_manipulator.c.
References axisBlendAngle(), MAN_SCALE_X, MAN_SCALE_Y, MAN_SCALE_Z, MAN_TRANS_X, MAN_TRANS_Y, MAN_TRANS_Z, manipulator_setcolor(), and RegionView3D::twangle.
Referenced by draw_manipulator_rotate_cyl(), draw_manipulator_scale(), and draw_manipulator_translate().
static void draw_manipulator_rotate (View3D * v3d, RegionView3D * rv3d, int moving, int drawflags, int combo) [static]
Definition at line 850 of file transform_manipulator.c.
References copy_m4_m4(), copy_v3db_v3fl(), drawcircball(), G, G_PICKSEL, glLoadMatrixf, glMultMatrixf, is_negative_m4(), is_orthogonal_m4(), len_v3(), M_PI, MAN_MOVECOL, MAN_RGB, MAN_ROT_C, MAN_ROT_T, MAN_ROT_V, MAN_ROT_X, MAN_ROT_Y, MAN_ROT_Z, manipulator_setcolor(), mul_v3_fl(), normalize_v3(), partial_doughnut(), postOrtho(), preOrthoFront(), saacos(), size(), TH_BACK, TH_TRANSFORM, RegionView3D::twmat, UI_ThemeColor(), UI_ThemeColorShade(), unit_m4(), V3D_MANIP_SCALE, RegionView3D::viewinv, RegionView3D::viewmat, RegionView3D::viewquat, and View3D::zbuf.
Referenced by BIF_draw_manipulator(), and manipulator_selectbuf().
static void draw_manipulator_rotate_cyl (View3D * v3d, RegionView3D * rv3d, int moving, int drawflags, int combo, int colcode) [static]
Definition at line 1356 of file transform_manipulator.c.
References copy_m4_m4(), draw_cylinder(), draw_manipulator_axes(), drawcircball(), G, G_PICKSEL, glLoadMatrixf, glMultMatrixf, if(), is_negative_m4(), MAN_ROT_C, MAN_ROT_V, MAN_ROT_X, MAN_ROT_Y, MAN_ROT_Z, manipulator_setcolor(), MAT4_UNITY, mul_v3_fl(), normalize_v3(), screen_aligned(), size(), TH_TRANSFORM, RegionView3D::twmat, UI_ThemeColor(), V3D_MANIP_SCALE, RegionView3D::viewmat, and View3D::zbuf.
Referenced by BIF_draw_manipulator(), and manipulator_selectbuf().
static void draw_manipulator_scale (View3D * v3d, RegionView3D * rv3d, int moving, int drawflags, int combo, int colcode) [static]
Definition at line 1165 of file transform_manipulator.c.
References axisBlendAngle(), copy_m4_m4(), draw_manipulator_axes(), drawcircball(), drawsolidcube(), G, G_PICKSEL, glLoadMatrixf, glMultMatrixf, if(), is_negative_m4(), MAN_SCALE_C, MAN_SCALE_X, MAN_SCALE_Y, MAN_SCALE_Z, manipulator_setcolor(), screen_aligned(), size(), RegionView3D::twangle, RegionView3D::twmat, unit_m4(), V3D_MANIP_ROTATE, V3D_MANIP_TRANSLATE, RegionView3D::viewmat, and View3D::zbuf.
Referenced by BIF_draw_manipulator(), and manipulator_selectbuf().
static void draw_manipulator_translate (View3D * v3d, RegionView3D * rv3d, int UNUSEDmoving, int drawflags, int combo, int colcode) [static]
Definition at line 1281 of file transform_manipulator.c.
References axisBlendAngle(), draw_cone(), draw_manipulator_axes(), drawcircball(), G, G_PICKSEL, glLoadMatrixf, glMultMatrixf, if(), MAN_GHOST, MAN_TRANS_C, MAN_TRANS_X, MAN_TRANS_Y, MAN_TRANS_Z, manipulator_setcolor(), screen_aligned(), size(), RegionView3D::twangle, RegionView3D::twmat, unit_m4(), V3D_MANIP_ROTATE, V3D_MANIP_SCALE, RegionView3D::viewmat, and View3D::zbuf.
Referenced by BIF_draw_manipulator(), and manipulator_selectbuf().
static void drawsolidcube (float size) [static]
Definition at line 1104 of file transform_manipulator.c.
Referenced by draw_manipulator_scale().
int gimbal_axis (Object * ob, float gmat[][3])
Definition at line 202 of file transform_manipulator.c.
References axis_angle_to_gimbal_axis(), bPoseChannel::bone, Bone::bone_mat, copy_m3_m4(), bPoseChannel::eul, eulO_to_gimbal_axis(), get_active_posechannel(), Object::mode, mul_m3_m3m3(), normalize_m3(), OB_MODE_POSE, Object::obmat, bPoseChannel::parent, Object::parent, bPoseChannel::pose_mat, Object::rot, ROT_MODE_AXISANGLE, bPoseChannel::rotAngle, Object::rotAngle, Object::rotAxis, bPoseChannel::rotAxis, Object::rotmode, bPoseChannel::rotmode, and test_rotmode_euler().
Referenced by calc_manipulator_stats(), and initTransformOrientation().
static int manipulator_selectbuf (ScrArea * sa, ARegion * ar, const int mval[2], float hotspot) [static]
Definition at line 1537 of file transform_manipulator.c.
References draw_manipulator_rotate(), draw_manipulator_rotate_cyl(), draw_manipulator_scale(), draw_manipulator_translate(), ListBase::first, G, G_PICKSEL, MAN_RGB, MAN_ROT_C, MAN_SCALE_C, MAN_TRANS_C, mult_m4_m4m4(), NULL, RegionView3D::persmat, ARegion::regiondata, setwinmatrixview3d(), ScrArea::spacedata, RegionView3D::twdrawflag, View3D::twtype, V3D_MANIP_ROTATE, V3D_MANIP_SCALE, V3D_MANIP_TRANSLATE, RegionView3D::viewmat, RegionView3D::winmat, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by BIF_do_manipulator().
static void manipulator_setcolor (View3D * v3d, char axis, int colcode, unsigned char alpha) [static]
Definition at line 752 of file transform_manipulator.c.
References BLI_assert, MAN_GHOST, MAN_MOVECOL, TH_TRANSFORM, View3D::twmode, UI_GetThemeColor3ubv(), V3D_MANIP_LOCAL, and V3D_MANIP_NORMAL.
Referenced by draw_manipulator_axes(), draw_manipulator_rotate(), draw_manipulator_rotate_cyl(), draw_manipulator_scale(), and draw_manipulator_translate().
static void partial_doughnut (float radring, float radhole, int start, int end, int nsides, int nrings) [static]
Definition at line 659 of file transform_manipulator.c.
References cos(), i, M_PI, and sin().
Referenced by draw_manipulator_rotate().
static void postOrtho (int ortho) [static]
Definition at line 843 of file transform_manipulator.c.
Referenced by draw_manipulator_rotate().
static void preOrthoFront (int ortho, float twmat[][4], int axis) [static]
Definition at line 831 of file transform_manipulator.c.
References copy_m4_m4(), glMultMatrixf, is_negative_m4(), and orthogonalize_m4().
Referenced by draw_manipulator_rotate().
static void protectflag_to_drawflags (short protectflag, short * drawflags) [static]
Definition at line 121 of file transform_manipulator.c.
References MAN_ROT_X, MAN_ROT_Y, MAN_ROT_Z, MAN_SCALE_X, MAN_SCALE_Y, MAN_SCALE_Z, MAN_TRANS_X, MAN_TRANS_Y, MAN_TRANS_Z, OB_LOCK_LOCX, OB_LOCK_LOCY, OB_LOCK_LOCZ, OB_LOCK_ROTX, OB_LOCK_ROTY, OB_LOCK_ROTZ, OB_LOCK_SCALEX, OB_LOCK_SCALEY, and OB_LOCK_SCALEZ.
Referenced by calc_manipulator_stats(), stats_editbone(), and stats_pose().
static float screen_aligned (RegionView3D * rv3d, float mat[][4]) [static]
Definition at line 641 of file transform_manipulator.c.
References len_v3(), M_PI, saacos(), and RegionView3D::viewquat.
Referenced by draw_manipulator_rotate_cyl(), draw_manipulator_scale(), and draw_manipulator_translate().
static void stats_editbone (RegionView3D * rv3d, EditBone * ebo) [static]
Definition at line 159 of file transform_manipulator.c.
References BONE_EDITMODE_LOCKED, EditBone::flag, OB_LOCK_LOC, OB_LOCK_ROT, OB_LOCK_SCALE, protectflag_to_drawflags(), and RegionView3D::twdrawflag.
Referenced by calc_manipulator_stats().
static void stats_pose (Scene * scene, RegionView3D * rv3d, bPoseChannel * pchan) [static]
Definition at line 146 of file transform_manipulator.c.
References bPoseChannel::bone, BONE_TRANSFORM, calc_tw_center(), Bone::flag, bPoseChannel::pose_head, bPoseChannel::protectflag, protectflag_to_drawflags(), and RegionView3D::twdrawflag.
Referenced by calc_manipulator_stats().
static void test_manipulator_axis (const bContext * C) [static]
Definition at line 602 of file transform_manipulator.c.
References angle(), angle_v3v3(), CTX_wm_region_view3d(), ED_view3d_global_to_vector(), fabs(), M_PI, MAN_SCALE_X, MAN_SCALE_Y, MAN_SCALE_Z, MAN_TRANS_X, MAN_TRANS_Y, MAN_TRANS_Z, RAD2DEGF, RegionView3D::twangle, RegionView3D::twdrawflag, and RegionView3D::twmat.
Referenced by BIF_draw_manipulator().
static int test_rotmode_euler (short rotmode) [static]
Definition at line 197 of file transform_manipulator.c.
References ELEM, ROT_MODE_AXISANGLE, and ROT_MODE_QUAT.
Referenced by gimbal_axis().
Variable Documentation
int drawflags = 0xFFFF [static]
Definition at line 1462 of file transform_manipulator.c.