Blender: mball_ops.c File Reference
mball_ops.c File Reference
metaball
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "ED_mball.h"
#include "ED_screen.h"
#include "ED_object.h"
#include "BLI_utildefines.h"
#include "mball_intern.h"
Functions
void ED_operatortypes_metaball (void)
void ED_keymap_metaball (wmKeyConfig *keyconf)
Detailed Description
Definition in file mball_ops.c.
Function Documentation
void ED_keymap_metaball (wmKeyConfig * keyconf)
Definition at line 57 of file mball_ops.c.
References AKEY, DELKEY, DKEY, ED_object_generic_keymap(), ED_operator_editmball(), FALSE, HKEY, IKEY, KM_ALT, KM_CTRL, KM_PRESS, KM_SHIFT, wmKeyMap::poll, wmKeyMapItem::ptr, RNA_boolean_set(), RNA_enum_set(), SEL_INVERT, SEL_TOGGLE, TRUE, WM_keymap_add_item(), WM_keymap_find(), and XKEY.
Referenced by ED_spacetypes_keymap().
void ED_operatortypes_metaball (void)
Definition at line 45 of file mball_ops.c.
References MBALL_OT_delete_metaelems(), MBALL_OT_duplicate_metaelems(), MBALL_OT_hide_metaelems(), MBALL_OT_reveal_metaelems(), MBALL_OT_select_all(), MBALL_OT_select_random_metaelems(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().