Blender: editmesh_bvh.c File Reference
editmesh_bvh.c File Reference
mesh
#include "MEM_guardedalloc.h"
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "DNA_screen_types.h"
#include "DNA_view3d_types.h"
#include "BLI_math.h"
#include "BLI_smallhash.h"
#include "BKE_DerivedMesh.h"
#include "BKE_tessmesh.h"
#include "ED_mesh.h"
#include "ED_view3d.h"
Classes
struct BMBVHTree
Defines
#define IN_EDITMESHBVH
Typedefs
typedef struct BMBVHTree BMBVHTree
Functions
static void cage_mapped_verts_callback (void *userData, int index, const float co[3], const float UNUSED(no_f[3]), const short UNUSED(no_s[3]))
BMBVHTree * BMBVH_NewBVH (BMEditMesh *em, int flag, Scene *scene, Object *obedit)
void BMBVH_FreeBVH (BMBVHTree *tree)
static float ray_tri_intersection (const BVHTreeRay *ray, const float UNUSED(m_dist), float *v0, float *v1, float *v2, float *uv, float UNUSED(e))
static void raycallback (void *userdata, int index, const BVHTreeRay *ray, BVHTreeRayHit *hit)
BMFace * BMBVH_RayCast (BMBVHTree *tree, float *co, float *dir, float *hitout, float *cagehit)
BVHTree * BMBVH_BVHTree (BMBVHTree *tree)
static void vertsearchcallback (void *userdata, int index, const float *UNUSED(co), BVHTreeNearest *hit)
BMVert * BMBVH_FindClosestVert (BMBVHTree *tree, float *co, float maxdist)
static BMFace * edge_ray_cast (BMBVHTree *tree, float *co, float *dir, float *hitout, BMEdge *e)
static void scale_point (float *c1, float *p, float s)
int BMBVH_EdgeVisible (BMBVHTree *tree, BMEdge *e, ARegion *ar, View3D *v3d, Object *obedit)
Detailed Description
Definition in file editmesh_bvh.c.
Define Documentation
#define IN_EDITMESHBVH
Definition at line 32 of file editmesh_bvh.c.
Typedef Documentation
typedef struct BMBVHTree BMBVHTree
Function Documentation
BVHTree* BMBVH_BVHTree (BMBVHTree * tree) [read]
Definition at line 283 of file editmesh_bvh.c.
References BMBVHTree::tree.
Referenced by knife_edge_tri_isect().
int BMBVH_EdgeVisible (BMBVHTree * tree, BMEdge * e, ARegion * ar, View3D * v3d, Object * obedit)
Definition at line 390 of file editmesh_bvh.c.
References add_v3_v3v3(), BMVert::co, copy_v3_v3(), ED_view3d_win_to_segment_clip(), edge_ray_cast(), KDL::epsilon, invert_m4_m4(), mul_m4_v3(), mul_v3_fl(), normalize_v3(), NULL, Object::obmat, scale_point(), sub_v3_v3v3(), BMEdge::v1, BMEdge::v2, ARegion::winx, and ARegion::winy.
Referenced by createSlideVerts().
BMVert* BMBVH_FindClosestVert (BMBVHTree * tree, float * co, float maxdist) [read]
Definition at line 310 of file editmesh_bvh.c.
References BLI_bvhtree_find_nearest(), BMVert::co, BVHTreeNearest::co, copy_v3_v3(), BVHTreeNearest::dist, BMBVHTree::em, FLT_MAX, i, BVHTreeNearest::index, len_v3(), BMEditMesh::looptris, BMBVHTree::maxdist, NULL, sub_v3_v3v3(), BMBVHTree::tree, BMLoop::v, and vertsearchcallback().
Referenced by EDBM_verts_mirror_cache_begin().
void BMBVH_FreeBVH (BMBVHTree * tree)
Definition at line 191 of file editmesh_bvh.c.
References BLI_bvhtree_free(), BMBVHTree::cagecos, BMBVHTree::cos, MEM_freeN(), and BMBVHTree::tree.
Referenced by createSlideVerts(), EDBM_verts_mirror_cache_begin(), and knifetool_exit().
BMBVHTree* BMBVH_NewBVH (BMEditMesh * em, int flag, Scene * scene, Object * obedit) [read]
Definition at line 86 of file editmesh_bvh.c.
References BLI_bvhtree_balance(), BLI_bvhtree_insert(), BLI_bvhtree_new(), BLI_smallhash_init(), BLI_smallhash_release(), BMBVHTree::bm, BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_index_get, BM_elem_index_set, BM_ELEM_SELECT, BM_ITER_MESH_INDEX, BM_VERT, BM_VERTS_OF_MESH, BMBVH_RESPECT_HIDDEN, BMBVH_RESPECT_SELECT, BMBVH_USE_CAGE, BMEdit_RecalcTessellation(), cage_mapped_verts_callback(), BMBVHTree::cagecos, CD_MASK_DERIVEDMESH, BMVert::co, copy_v3_v3(), BMBVHTree::cos, cos(), data, editbmesh_get_derived_cage_and_final(), BMesh::elem_index_dirty, BMBVHTree::em, BMBVHTree::epsilon, BMLoop::f, BMBVHTree::flag, DerivedMesh::foreachMappedVert, i, BMEditMesh::looptris, MEM_callocN(), NULL, BMBVHTree::ob, BMBVHTree::scene, BMEditMesh::tottri, BMesh::totvert, BMBVHTree::tree, and BMLoop::v.
Referenced by createSlideVerts(), EDBM_verts_mirror_cache_begin(), and knifetool_init().
BMFace* BMBVH_RayCast (BMBVHTree * tree, float * co, float * dir, float * hitout, float * cagehit) [read]
Definition at line 242 of file editmesh_bvh.c.
References BLI_bvhtree_ray_cast(), BMBVH_RETURN_ORIG, BVHTreeRayHit::co, BMVert::co, copy_v3_v3(), BVHTreeRayHit::dist, BMBVHTree::em, BMLoop::f, BMBVHTree::flag, FLT_MAX, i, BVHTreeRayHit::index, BMEditMesh::looptris, NULL, raycallback(), BMBVHTree::tree, BMBVHTree::uv, and BMLoop::v.
Referenced by edge_ray_cast(), knife_edge_tri_isect(), and knife_find_closest_face().
static void cage_mapped_verts_callback (void * userData, int index, const float co[3], const float UNUSEDno_f[3], const short UNUSEDno_s[3]) [static]
Definition at line 72 of file editmesh_bvh.c.
References BLI_smallhash_haskey(), BLI_smallhash_insert(), copy_v3_v3(), data, hash, and NULL.
Referenced by BMBVH_NewBVH().
static BMFace* edge_ray_cast (BMBVHTree * tree, float * co, float * dir, float * hitout, BMEdge * e) [static]
Definition at line 372 of file editmesh_bvh.c.
References BM_edge_in_face(), BMBVH_RayCast(), and NULL.
Referenced by BMBVH_EdgeVisible().
static float ray_tri_intersection (const BVHTreeRay * ray, const float UNUSEDm_dist, float * v0, float * v1, float * v2, float * uv, float UNUSEDe) [static]
Definition at line 204 of file editmesh_bvh.c.
References BVHTreeRay::direction, FLT_MAX, isect_ray_tri_v3(), and BVHTreeRay::origin.
Referenced by raycallback().
static void raycallback (void * userdata, int index, const BVHTreeRay * ray, BVHTreeRayHit * hit) [static]
Definition at line 216 of file editmesh_bvh.c.
References add_v3_v3(), BVHTreeRayHit::co, BMVert::co, copy_v2_v2(), copy_v3_v3(), BVHTreeRay::direction, BVHTreeRayHit::dist, BMBVHTree::em, BMBVHTree::epsilon, BVHTreeRayHit::index, BMEditMesh::looptris, mul_v3_fl(), BVHTreeRayHit::no, BMVert::no, normalize_v3(), BVHTreeRay::origin, ray_tri_intersection(), BMBVHTree::uv, and BMLoop::v.
Referenced by BMBVH_RayCast().
static void scale_point (float * c1, float * p, float s) [static]
Definition at line 382 of file editmesh_bvh.c.
References add_v3_v3(), mul_v3_fl(), and sub_v3_v3().
Referenced by BMBVH_EdgeVisible().
static void vertsearchcallback (void * userdata, int index, const float * UNUSEDco, BVHTreeNearest * hit) [static]
Definition at line 288 of file editmesh_bvh.c.
References BMVert::co, BVHTreeNearest::co, copy_v3_v3(), BVHTreeNearest::dist, BMBVHTree::em, i, BVHTreeNearest::index, len_v3(), BMEditMesh::looptris, BMBVHTree::maxdist, BVHTreeNearest::no, BMVert::no, sub_v3_v3v3(), and BMLoop::v.
Referenced by BMBVH_FindClosestVert().