Blender: dualcon_c_api.cpp File Reference
dualcon_c_api.cpp File Reference
#include <cassert>
#include "dualcon.h"
#include "ModelReader.h"
#include "octree.h"
#include <cstdio>
#include <float.h>
Classes
class DualConInputReader
Defines
#define GET_FACE(_mesh, _n) (*(DualConFaces)(((char*)(_mesh)->faces) + ((_n) * (_mesh)->face_stride)))
#define GET_CO(_mesh, _n) (*(DualConCo)(((char*)(_mesh)->co) + ((_n) * (_mesh)->co_stride)))
Functions
void veccopy (float dst[3], const float src[3])
void * dualcon (const DualConInput *input_mesh, DualConAllocOutput alloc_output, DualConAddVert add_vert, DualConAddQuad add_quad, DualConFlags flags, DualConMode mode, float threshold, float hermite_num, float scale, int depth)
Define Documentation
#define GET_CO (_mesh, _n) (*(DualConCo)(((char*)(_mesh)->co) + ((_n) * (_mesh)->co_stride)))
Definition at line 45 of file dualcon_c_api.cpp.
Referenced by DualConInputReader::getNextTriangle().
#define GET_FACE (_mesh, _n) (*(DualConFaces)(((char*)(_mesh)->faces) + ((_n) * (_mesh)->face_stride)))
Definition at line 42 of file dualcon_c_api.cpp.
Referenced by DualConInputReader::getNextTriangle(), and DualConInputReader::reset().
Function Documentation
void* dualcon (const DualConInput * input_mesh, DualConAllocOutput alloc_output, DualConAddVert add_vert, DualConAddQuad add_quad, DualConFlags flags, DualConMode mode, float threshold, float hermite_num, float scale, int depth)
Definition at line 187 of file dualcon_c_api.cpp.
References Octree::getOutputMesh(), and Octree::scanConvert().
void veccopy (float dst[3], const float src[3])
Definition at line 35 of file dualcon_c_api.cpp.
Referenced by DualConInputReader::getBoundingBox(), DualConInputReader::getNextTriangle(), and DualConInputReader::reset().