Blender: curve_ops.c File Reference
curve_ops.c File Reference
curve
#include <stdlib.h>
#include <math.h>
#include "DNA_curve_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_curve.h"
#include "ED_object.h"
#include "ED_screen.h"
#include "ED_transform.h"
#include "curve_intern.h"
Functions
void ED_operatortypes_curve (void)
void ED_operatormacros_curve (void)
void ED_keymap_curve (wmKeyConfig *keyconf)
Detailed Description
Definition in file curve_ops.c.
Function Documentation
void ED_keymap_curve (wmKeyConfig * keyconf)
Definition at line 158 of file curve_ops.c.
References AKEY, BACKSPACEKEY, BKEY, CKEY, CU_CHINFO_BOLD, CU_CHINFO_ITALIC, CU_CHINFO_SMALLCAPS, CU_CHINFO_UNDERLINE, DEL_ALL, DEL_NEXT_SEL, DEL_PREV_SEL, DELKEY, DKEY, DOWNARROWKEY, ED_object_generic_keymap(), ED_operator_editfont(), ED_operator_editsurfcurve(), EKEY, ENDKEY, FALSE, FKEY, HKEY, HOMEKEY, IKEY, KM_ALT, KM_ANY, KM_CLICK, KM_CTRL, KM_OSKEY, KM_PRESS, KM_SHIFT, KM_TEXTINPUT, LEFTARROWKEY, LEFTMOUSE, LINE_BEGIN, LINE_END, LKEY, NEXT_CHAR, NEXT_LINE, NEXT_PAGE, NEXT_WORD, PADMINUS, PADPLUSKEY, PAGEDOWNKEY, PAGEUPKEY, PKEY, wmKeyMap::poll, PREV_CHAR, PREV_LINE, PREV_PAGE, PREV_WORD, wmKeyMapItem::ptr, RETKEY, RIGHTARROWKEY, RKEY, RNA_boolean_set(), RNA_enum_set(), RNA_int_set(), SEL_INVERT, SEL_TOGGLE, SKEY, TFM_CURVE_SHRINKFATTEN, TKEY, TRUE, UKEY, UPARROWKEY, VKEY, WKEY, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), and XKEY.
Referenced by ED_spacetypes_keymap().
void ED_operatormacros_curve (void)
Definition at line 138 of file curve_ops.c.
References wmOperatorType::description, FALSE, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorTypeMacro::ptr, RNA_boolean_set(), RNA_enum_set(), WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().
void ED_operatortypes_curve (void)
Definition at line 56 of file curve_ops.c.
References CURVE_OT_cyclic_toggle(), CURVE_OT_de_select_first(), CURVE_OT_de_select_last(), CURVE_OT_delete(), CURVE_OT_duplicate(), CURVE_OT_extrude(), CURVE_OT_handle_type_set(), CURVE_OT_hide(), CURVE_OT_make_segment(), CURVE_OT_primitive_bezier_circle_add(), CURVE_OT_primitive_bezier_curve_add(), CURVE_OT_primitive_nurbs_circle_add(), CURVE_OT_primitive_nurbs_curve_add(), CURVE_OT_primitive_nurbs_path_add(), CURVE_OT_radius_set(), CURVE_OT_reveal(), CURVE_OT_select_all(), CURVE_OT_select_less(), CURVE_OT_select_linked(), CURVE_OT_select_linked_pick(), CURVE_OT_select_more(), CURVE_OT_select_next(), CURVE_OT_select_nth(), CURVE_OT_select_previous(), CURVE_OT_select_random(), CURVE_OT_select_row(), CURVE_OT_separate(), CURVE_OT_shade_flat(), CURVE_OT_shade_smooth(), CURVE_OT_smooth(), CURVE_OT_smooth_radius(), CURVE_OT_spin(), CURVE_OT_spline_type_set(), CURVE_OT_spline_weight_set(), CURVE_OT_subdivide(), CURVE_OT_switch_direction(), CURVE_OT_tilt_clear(), CURVE_OT_vertex_add(), FONT_OT_case_set(), FONT_OT_case_toggle(), FONT_OT_change_character(), FONT_OT_change_spacing(), FONT_OT_delete(), FONT_OT_file_paste(), FONT_OT_insert_lorem(), FONT_OT_line_break(), FONT_OT_move(), FONT_OT_move_select(), FONT_OT_open(), FONT_OT_style_set(), FONT_OT_style_toggle(), FONT_OT_text_copy(), FONT_OT_text_cut(), FONT_OT_text_insert(), FONT_OT_text_paste(), FONT_OT_textbox_add(), FONT_OT_textbox_remove(), FONT_OT_unlink(), SURFACE_OT_primitive_nurbs_surface_circle_add(), SURFACE_OT_primitive_nurbs_surface_curve_add(), SURFACE_OT_primitive_nurbs_surface_cylinder_add(), SURFACE_OT_primitive_nurbs_surface_sphere_add(), SURFACE_OT_primitive_nurbs_surface_surface_add(), SURFACE_OT_primitive_nurbs_surface_torus_add(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().