Blender: rayobject.h File Reference
rayobject.h File Reference
Rendering
#include "../raytrace/rayobject_internal.h"
Classes
struct RayFace
struct VlakPrimitive
Defines
#define RE_rayface_isQuad(a) ((a)->quad)
Typedefs
typedef struct RayObject RayObject
typedef struct RayFace RayFace
typedef struct VlakPrimitive VlakPrimitive
Functions
int RE_rayobject_raycast (RayObject *r, struct Isect *i)
RayObject * RE_rayobject_octree_create (int ocres, int size)
RayObject * RE_rayobject_instance_create (RayObject *target, float transform[][4], void *ob, void *target_ob)
RayObject * RE_rayobject_empty_create (void)
RayObject * RE_rayobject_blibvh_create (int size)
RayObject * RE_rayobject_vbvh_create (int size)
RayObject * RE_rayobject_svbvh_create (int size)
RayObject * RE_rayobject_qbvh_create (int size)
void RE_rayobject_add (RayObject *r, RayObject *)
void RE_rayobject_done (RayObject *r)
void RE_rayobject_free (RayObject *r)
void RE_rayobject_set_control (RayObject *r, void *data, int(*test_break)(void *data))
RayObject * RE_rayface_from_vlak (RayFace *face, struct ObjectInstanceRen *obi, struct VlakRen *vlr)
RayObject * RE_vlakprimitive_from_vlak (VlakPrimitive *face, struct ObjectInstanceRen *obi, struct VlakRen *vlr)
void RE_rayobject_merge_bb (RayObject *ob, float *min, float *max)
void RE_rayobject_hint_bb (RayObject *r, struct RayHint *hint, float *min, float *max)
Detailed Description
Definition in file rayobject.h.
Define Documentation
#define RE_rayface_isQuad (a) ((a)->quad)
Definition at line 86 of file rayobject.h.
Referenced by isec_tri_quad(), isec_tri_quad_neighbour(), makeraytree_single(), octree_fill_rayface(), rayface_from_vlak(), and RE_rayobject_merge_bb().
Typedef Documentation
typedef struct RayFace RayFace
typedef struct RayObject RayObject
Definition at line 50 of file rayobject.h.
typedef struct VlakPrimitive VlakPrimitive
Function Documentation
RayObject* RE_rayface_from_vlak (RayFace * face, struct ObjectInstanceRen * obi, struct VlakRen * vlr)
Definition at line 91 of file rayobject.cpp.
References VertRen::co, rayface_from_coords(), VlakRen::v1, VlakRen::v2, VlakRen::v3, and VlakRen::v4.
Referenced by makeraytree_object(), and makeraytree_single().
void RE_rayobject_add (RayObject * r, RayObject *)
Definition at line 449 of file rayobject.cpp.
References RayObjectAPI::add, RayObject::api, and RE_rayobject_align.
Referenced by makeraytree_object(), and makeraytree_single().
RayObject* RE_rayobject_blibvh_create (int size)
Definition at line 80 of file rayobject_blibvh.cpp.
References RayObject::api, assert, BVHObject::bb, BLI_bvhtree_new(), BVHObject::bvh, bvh_api, INIT_MINMAX, BVHObject::leafs, MEM_callocN(), BVHObject::next_leaf, BVHObject::rayobj, RE_rayobject_isAligned, and RE_rayobject_unalignRayAPI.
Referenced by RE_rayobject_create().
void RE_rayobject_done (RayObject * r)
Definition at line 455 of file rayobject.cpp.
References RayObject::api, RayObjectAPI::done, and RE_rayobject_align.
Referenced by makeraytree_object(), and makeraytree_single().
RayObject* RE_rayobject_empty_create (void)
Definition at line 77 of file rayobject_empty.cpp.
References RE_rayobject_unalignRayAPI.
Referenced by makeraytree_single().
void RE_rayobject_free (RayObject * r)
Definition at line 461 of file rayobject.cpp.
References RayObject::api, RayObjectAPI::free, and RE_rayobject_align.
Referenced by free_renderdata_tables(), freeraytree(), and makeraytree_object().
void RE_rayobject_hint_bb (RayObject * r, struct RayHint * hint, float * min, float * max)
Definition at line 519 of file rayobject.cpp.
References RayObject::api, assert, RayObjectAPI::hint_bb, RE_rayobject_align, RE_rayobject_isRayAPI, RE_rayobject_isRayFace, and RE_rayobject_isVlakPrimitive.
Referenced by ray_ao_qmc(), ray_ao_spheresamp(), ray_shadow_jitter(), and ray_shadow_qmc().
RayObject* RE_rayobject_instance_create (RayObject * target, float transform[][4], void * ob, void * target_ob)
Definition at line 79 of file rayobject_instance.cpp.
References RayObject::api, assert, copy_m4_m4(), InstanceRayObject::global2target, instance_api, invert_m4_m4(), MEM_callocN(), InstanceRayObject::ob, InstanceRayObject::rayobj, RE_rayobject_isAligned, RE_rayobject_unalignRayAPI, InstanceRayObject::target, InstanceRayObject::target2global, and InstanceRayObject::target_ob.
Referenced by makeraytree_object().
void RE_rayobject_merge_bb (RayObject * ob, float * min, float * max)
Definition at line 486 of file rayobject.cpp.
References RayObject::api, assert, RayObjectAPI::bb, DO_MINMAX, VlakPrimitive::face, VlakPrimitive::ob, rayface_from_vlak(), RE_rayface_isQuad, RE_rayobject_align, RE_rayobject_isRayAPI, RE_rayobject_isRayFace, RE_rayobject_isVlakPrimitive, RayFace::v1, RayFace::v2, RayFace::v3, and RayFace::v4.
Referenced by bvh_node_merge_bb(), makeraytree(), RE_rayobject_blibvh_add(), RE_rayobject_instance_bb(), RE_rayobject_octree_done(), rtbuild_add(), and rtbuild_calc_bb().
RayObject* RE_rayobject_octree_create (int ocres, int size)
Definition at line 478 of file rayobject_octree.cpp.
References RayObject::api, assert, MEM_callocN(), Octree::ocres, octree_api, Octree::rayobj, RE_rayobject_isAligned, RE_rayobject_unalignRayAPI, Octree::ro_nodes, Octree::ro_nodes_size, Octree::ro_nodes_used, and size().
Referenced by RE_rayobject_create().
RayObject* RE_rayobject_qbvh_create (int size)
Definition at line 156 of file rayobject_qbvh.cpp.
References NULL.
Referenced by RE_rayobject_create().
int RE_rayobject_raycast (RayObject * r, struct Isect * i)
Definition at line 371 of file rayobject.cpp.
References Isect::bv_index, Isect::dir, Isect::hint, Isect::hit, i, Isect::idot_axis, Isect::last_hit, Isect::mode, RE_RAY_SHADOW, RE_rayobject_intersect(), and RE_RC_COUNT.
Referenced by bake_intersect_tree(), intersect_outside_volume(), ray_ao_qmc(), ray_ao_spheresamp(), ray_shadow(), ray_shadow_jitter(), ray_shadow_qmc(), ray_trace_shadow_rad(), ray_trace_shadow_tra(), traceray(), vol_get_bounds(), vol_get_shadow(), and vol_trace_behind().
void RE_rayobject_set_control (RayObject * r, void * data, int(*)(void *data) test_break)
Definition at line 544 of file rayobject.cpp.
References RayObject::control, data, RayObjectControl::data, RE_rayobject_align, RE_rayobject_isRayAPI, RayObjectControl::test_break, and test_break().
RayObject* RE_rayobject_svbvh_create (int size)
Definition at line 192 of file rayobject_svbvh.cpp.
References NULL.
Referenced by RE_rayobject_create().
RayObject* RE_rayobject_vbvh_create (int size)
Definition at line 207 of file rayobject_vbvh.cpp.
References size().
Referenced by RE_rayobject_create().
RayObject* RE_vlakprimitive_from_vlak (VlakPrimitive * face, struct ObjectInstanceRen * obi, struct VlakRen * vlr)
Definition at line 98 of file rayobject.cpp.
References VlakPrimitive::face, VlakPrimitive::ob, and RE_rayobject_unalignVlakPrimitive.
Referenced by makeraytree_object(), and makeraytree_single().