Blender: BKE_fluidsim.h File Reference
BKE_fluidsim.h File Reference
blenkernel
Functions
void initElbeemMesh (struct Scene *scene, struct Object *ob, int *numVertices, float **vertices, int *numTriangles, int **triangles, int useGlobalCoords, int modifierIndex)
void fluid_get_bb (struct MVert *mvert, int totvert, float obmat[][4], float start[3], float size[3])
void fluid_estimate_memory (struct Object *ob, struct FluidsimSettings *fss, char *value)
Detailed Description
Definition in file BKE_fluidsim.h.
Function Documentation
void fluid_estimate_memory (struct Object * ob, struct FluidsimSettings * fss, char * value)
void fluid_get_bb (struct MVert * mvert, int totvert, float obmat[][4], float start[3], float size[3])
void initElbeemMesh (struct Scene * scene, struct Object * ob, int * numVertices, float ** vertices, int * numTriangles, int ** triangles, int useGlobalCoords, int modifierIndex)
Definition at line 68 of file fluidsim.c.
References CD_MASK_BAREMESH, co, copy_v3_v3(), DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, DerivedMesh::getTessFaceArray, DerivedMesh::getVertArray, i, MEM_callocN(), mesh_create_derived_index_render(), mul_m4_v3(), NULL, Object::obmat, DerivedMesh::release, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.