Blender: node_composite_texture.c File Reference
node_composite_texture.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void texture_procedural (CompBuf *cbuf, float *out, float xco, float yco)
static void node_composit_exec_texture (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_texture (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_texture_in []
static bNodeSocketTemplate cmp_node_texture_out []
Detailed Description
Definition in file node_composite_texture.c.
Function Documentation
static void node_composit_exec_texture (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 91 of file node_composite_texture.c.
References alloc_compbuf(), CB_RGBA, CB_VAL, composit1_pixel_processor(), copy_v3_v3(), bNodeStack::data, data, do_copy_rgba(), do_copy_value(), free_compbuf(), generate_preview(), bNode::id, CompBuf::node, NULL, CompBuf::procedural_offset, CompBuf::procedural_size, CompBuf::procedural_type, CompBuf::rect_procedural, RenderData::size, texture_procedural(), bNodeStack::vec, RenderData::xsch, and RenderData::ysch.
Referenced by register_node_type_cmp_texture().
void register_node_type_cmp_texture (bNodeTreeType * ttype)
Definition at line 145 of file node_composite_texture.c.
References CMP_NODE_TEXTURE, NODE_CLASS_INPUT, node_composit_exec_texture(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
static void texture_procedural (CompBuf * cbuf, float * out, float xco, float yco) [static]
Definition at line 48 of file node_composite_texture.c.
References CB_RGBA, CB_VAL, copy_v3_v3(), bNode::id, multitex_ext(), CompBuf::node, NULL, CompBuf::procedural_offset, CompBuf::procedural_size, CompBuf::procedural_type, size(), TexResult::ta, TexResult::talpha, TexResult::tb, TEX_RGB, TexResult::tg, TexResult::tin, TexResult::tr, CompBuf::type, and typecheck_compbuf_color().
Referenced by node_composit_exec_texture().
Variable Documentation
bNodeSocketTemplate cmp_node_texture_in[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 1, "Offset",       0.0f, 0.0f, 0.0f, 0.0f, -2.0f, 2.0f, PROP_TRANSLATION},
    {   SOCK_VECTOR, 1, "Scale",        1.0f, 1.0f, 1.0f, 1.0f, -10.0f, 10.0f, PROP_XYZ},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_composite_texture.c.
bNodeSocketTemplate cmp_node_texture_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "Value"},
    {   SOCK_RGBA , 0, "Color"},
    {   -1, 0, ""   }
}
Definition at line 41 of file node_composite_texture.c.