Blender: AUD_Reference.h File Reference
AUD_Reference.h File Reference
#include <map>
#include <cstddef>
Classes
class AUD_ReferenceHandler
class AUD_Reference< T >
Functions
template<class T , class U >
bool operator== (const AUD_Reference< T > &a, const AUD_Reference< U > &b)
template<class T , class U >
bool operator!= (const AUD_Reference< T > &a, const AUD_Reference< U > &b)
Detailed Description
Definition in file AUD_Reference.h.
Function Documentation
template<class T , class U > bool operator!= (const AUD_Reference< T > & a, const AUD_Reference< U > & b) [inline]
Definition at line 242 of file AUD_Reference.h.
References AUD_Reference< T >::getOriginal().
Referenced by ATTRIBUTE_ALIGNED16().
template<class T , class U > bool operator== (const AUD_Reference< T > & a, const AUD_Reference< U > & b) [inline]
Definition at line 236 of file AUD_Reference.h.
References AUD_Reference< T >::getOriginal().