Blender: StrandSurface Struct Reference
StrandSurface Struct Reference
#include <render_types.h>
Public Attributes
struct StrandSurface * next
struct StrandSurface * prev
ObjectRen obr
int(* face)[4]
float(* co)[3]
float(* ao)[3]
float(* env)[3]
float(* indirect)[3]
float(* prevco)[3]
float((* nextco)[3]
int totvert
int totface
Detailed Description
Definition at line 410 of file render_types.h.
Member Data Documentation
float(* StrandSurface::ao)[3]
Definition at line 416 of file render_types.h.
Referenced by cache_strand_surface(), free_strand_surface(), make_occ_tree(), and sample_occ_surface().
float(* StrandSurface::co)[3]
Definition at line 414 of file render_types.h.
Referenced by cache_strand_surface(), calculate_speedvectors(), calculate_strandsurface_speedvectors(), exec_strandsurface_sample(), free_strand_surface(), make_occ_tree(), and sample_occ_surface().
float(* StrandSurface::env)[3]
Definition at line 417 of file render_types.h.
Referenced by cache_strand_surface(), free_strand_surface(), make_occ_tree(), and sample_occ_surface().
int(* StrandSurface::face)[4]
Definition at line 413 of file render_types.h.
Referenced by cache_strand_surface(), calculate_speedvectors(), exec_strandsurface_sample(), free_strand_surface(), make_occ_tree(), and sample_occ_surface().
float(* StrandSurface::indirect)[3]
Definition at line 418 of file render_types.h.
Referenced by cache_strand_surface(), free_strand_surface(), make_occ_tree(), and sample_occ_surface().
struct StrandSurface* StrandSurface::next
Definition at line 411 of file render_types.h.
Referenced by cache_strand_surface(), free_strand_surface(), make_occ_tree(), and RE_Database_FromScene_Vectors().
float((* StrandSurface::nextco)[3]
Definition at line 420 of file render_types.h.
Referenced by cache_strand_surface(), calculate_strandsurface_speedvectors(), free_strand_surface(), and RE_Database_FromScene_Vectors().
ObjectRen StrandSurface::obr
Definition at line 412 of file render_types.h.
Referenced by cache_strand_surface().
struct StrandSurface * StrandSurface::prev
Definition at line 411 of file render_types.h.
float(* StrandSurface::prevco)[3]
Definition at line 420 of file render_types.h.
Referenced by cache_strand_surface(), calculate_strandsurface_speedvectors(), free_strand_surface(), and RE_Database_FromScene_Vectors().
int StrandSurface::totface
Definition at line 421 of file render_types.h.
Referenced by cache_strand_surface(), and make_occ_tree().
int StrandSurface::totvert
Definition at line 421 of file render_types.h.
Referenced by cache_strand_surface(), calculate_strandsurface_speedvectors(), and make_occ_tree().
The documentation for this struct was generated from the following file:
render_types.h