Blender: BLO_undofile.h File Reference
BLO_undofile.h File Reference
.blend read and write functions
Classes
struct MemFileChunk
struct MemFile
Typedefs
typedef struct MemFile MemFile
Functions
void add_memfilechunk (MemFile *compare, MemFile *current, const char *buf, unsigned int size)
void BLO_free_memfile (MemFile *memfile)
void BLO_merge_memfile (MemFile *first, MemFile *second)
Detailed Description
Definition in file BLO_undofile.h.
Typedef Documentation
typedef struct MemFile MemFile
Function Documentation
void add_memfilechunk (MemFile * compare, MemFile * current, const char * buf, unsigned int size)
Definition at line 102 of file undofile.c.
References BLI_addtail(), MemFileChunk::buf, MemFile::chunks, ListBase::first, MemFileChunk::ident, MEM_mallocN(), my_memcmp(), MemFileChunk::next, NULL, MemFile::size, size(), and MemFileChunk::size.
Referenced by bgnwrite(), and writedata_do_write().
void BLO_free_memfile (MemFile * memfile)
Definition at line 54 of file undofile.c.
References BLI_remlink(), MemFileChunk::buf, MemFile::chunks, ListBase::first, MemFileChunk::ident, MEM_freeN(), and MemFile::size.
Referenced by BKE_reset_undo(), BKE_write_undo(), and BLO_merge_memfile().
void BLO_merge_memfile (MemFile * first, MemFile * second)
Definition at line 68 of file undofile.c.
References BLO_free_memfile(), MemFile::chunks, ListBase::first, MemFileChunk::ident, and MemFileChunk::next.
Referenced by BKE_write_undo().