Blender: scolumn_bmod.c File Reference
scolumn_bmod.c File Reference
opennl
#include <stdio.h>
#include <stdlib.h>
#include "ssp_defs.h"
Functions
void susolve (int, int, float *, float *)
void slsolve (int, int, float *, float *)
void smatvec (int, int, int, float *, float *, float *)
int scolumn_bmod (const int jcol, const int nseg, float *dense, float *tempv, int *segrep, int *repfnz, int fpanelc, GlobalLU_t *Glu, SuperLUStat_t *stat)
Detailed Description
Definition in file scolumn_bmod.c.
Function Documentation
int scolumn_bmod (const int jcol, const int nseg, float * dense, float * tempv, int * segrep, int * repfnz, int fpanelc, GlobalLU_t * Glu, SuperLUStat_t * stat)
Definition at line 42 of file scolumn_bmod.c.
References GEMV, i, GlobalLU_t::lsub, GlobalLU_t::lusup, LUSUP, GlobalLU_t::nzlumax, SuperLUStat_t::ops, slsolve(), sLUMemXpand(), smatvec(), strlen(), strsv_(), SUPERLU_MAX, GlobalLU_t::supno, TRSV, GlobalLU_t::xlsub, GlobalLU_t::xlusup, and GlobalLU_t::xsup.
Referenced by sgstrf().
void slsolve (int ldm, int ncol, float * M, float * rhs)
Definition at line 33 of file smyblas2.c.
Referenced by scolumn_bmod(), sgstrs(), sp_strsv(), spanel_bmod(), and ssnode_bmod().
void smatvec (int ldm, int nrow, int ncol, float * M, float * vec, float * Mxvec)
Definition at line 160 of file smyblas2.c.
Referenced by scolumn_bmod(), sgstrs(), sp_strsv(), spanel_bmod(), and ssnode_bmod().
void susolve (int ldm, int ncol, float * M, float * rhs)
Definition at line 131 of file smyblas2.c.
Referenced by sgstrs(), and sp_strsv().