Blender: node_shader_bsdf_glossy.c File Reference
node_shader_bsdf_glossy.c File Reference
#include "../node_shader_util.h"
Functions
static int node_shader_gpu_bsdf_glossy (GPUMaterial *mat, bNode *UNUSED(node), GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_bsdf_glossy (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_bsdf_glossy_in []
static bNodeSocketTemplate sh_node_bsdf_glossy_out []
Function Documentation
static int node_shader_gpu_bsdf_glossy (GPUMaterial * mat, bNode * UNUSEDnode, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 43 of file node_shader_bsdf_glossy.c.
References GPU_builtin(), GPU_stack_link(), GPU_VIEW_NORMAL, and GPU_VIEW_POSITION.
Referenced by register_node_type_sh_bsdf_glossy().
void register_node_type_sh_bsdf_glossy (bNodeTreeType * ttype)
Definition at line 50 of file node_shader_bsdf_glossy.c.
References NODE_CLASS_SHADER, NODE_NEW_SHADING, NODE_OPTIONS, node_shader_gpu_bsdf_glossy(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_BSDF_GLOSSY.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_bsdf_glossy_in[] [static]
Initial value:
 {
    {   SOCK_RGBA,  1, "Color",     0.8f, 0.8f, 0.8f, 1.0f, 0.0f, 1.0f},
    {   SOCK_FLOAT, 1, "Roughness", 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 32 of file node_shader_bsdf_glossy.c.
bNodeSocketTemplate sh_node_bsdf_glossy_out[] [static]
Initial value:
 {
    {   SOCK_SHADER, 0, "BSDF"},
    {   -1, 0, ""   }
}
Definition at line 38 of file node_shader_bsdf_glossy.c.