Blender: ImageSource Class Reference
ImageSource Class Reference
class for source of image
#include <ImageBase.h>
Public Member Functions
ImageSource (const char *id)
constructor
virtual ~ImageSource (void)
destructor
const char * getId (void)
get id
bool is (const char *id)
compare id to argument
PyImage * getSource (void)
get source object
void setSource (PyImage *source)
set source object
unsigned int * getImage (double ts=-1.0)
get image from source
unsigned int * getImageBuf (void)
get buffered image
void refresh (void)
refresh source
short * getSize (void)
get image size
Protected Attributes
char m_id [SourceIdSize]
id of source
PyImage * m_source
pointer to source structure
unsigned int * m_image
buffered image from source
Detailed Description
class for source of image
Definition at line 263 of file ImageBase.h.
Constructor & Destructor Documentation
ImageSource::ImageSource (const char * id)
constructor
Definition at line 290 of file ImageBase.cpp.
References ImageSource(), m_id, and SourceIdSize.
Referenced by ImageSource().
ImageSource::~ImageSource (void) [virtual]
destructor
Definition at line 300 of file ImageBase.cpp.
References NULL, and setSource().
Member Function Documentation
const char* ImageSource::getId (void) [inline]
get id
Definition at line 272 of file ImageBase.h.
References m_id.
unsigned int * ImageSource::getImage (double ts = -1.0)
get image from source
Definition at line 329 of file ImageBase.cpp.
References ImageBase::getImage(), m_image, PyImage::m_image, m_source, and NULL.
unsigned int* ImageSource::getImageBuf (void) [inline]
get buffered image
Definition at line 284 of file ImageBase.h.
References m_image.
short* ImageSource::getSize (void) [inline]
get image size
Definition at line 289 of file ImageBase.h.
References ImageBase::getSize(), PyImage::m_image, m_source, and NULL.
PyImage* ImageSource::getSource (void) [inline]
get source object
Definition at line 277 of file ImageBase.h.
References m_source.
bool ImageSource::is (const char * id)
compare id to argument
Definition at line 308 of file ImageBase.cpp.
References m_id.
void ImageSource::refresh (void)
refresh source
Definition at line 344 of file ImageBase.cpp.
References PyImage::m_image, m_source, NULL, and ImageBase::refresh().
void ImageSource::setSource (PyImage * source)
set source object
Definition at line 317 of file ImageBase.cpp.
References m_source, and NULL.
Referenced by ImageBase::setSource(), and ~ImageSource().
Member Data Documentation
char ImageSource::m_id[SourceIdSize] [protected]
id of source
Definition at line 297 of file ImageBase.h.
Referenced by getId(), ImageSource(), and is().
unsigned int* ImageSource::m_image [protected]
buffered image from source
Definition at line 301 of file ImageBase.h.
Referenced by getImage(), getImageBuf(), and ImageSourceMix::setOffset().
PyImage* ImageSource::m_source [protected]
pointer to source structure
Definition at line 299 of file ImageBase.h.
Referenced by getImage(), getSize(), getSource(), refresh(), and setSource().
The documentation for this class was generated from the following files:
ImageBase.h
ImageBase.cpp