Blender: node_texture_bricks.c File Reference
node_texture_bricks.c File Reference
texnodes
#include "node_texture_util.h"
#include "NOD_texture.h"
#include <math.h>
Functions
static void init (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static float noise (int n)
static void colorfn (float *out, TexParams *p, bNode *node, bNodeStack **in, short thread)
static void exec (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_tex_bricks (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate inputs []
static bNodeSocketTemplate outputs []
Detailed Description
Definition in file node_texture_bricks.c.
Function Documentation
static void colorfn (float * out, TexParams * p, bNode * node, bNodeStack ** in, short thread) [static]
Definition at line 67 of file node_texture_bricks.c.
References CLAMP(), TexParams::co, co, copy_v4_v4(), bNode::custom1, bNode::custom2, bNode::custom3, bNode::custom4, MA_RAMP_BLEND, noise(), ramp_blend(), tex_input_rgba(), and tex_input_value().
Referenced by exec().
static void exec (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 118 of file node_texture_bricks.c.
References colorfn(), and tex_output().
Referenced by register_node_type_tex_bricks().
static void init (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 53 of file node_texture_bricks.c.
References bNode::custom3, and bNode::custom4.
static float noise (int n) [static]
Definition at line 59 of file node_texture_bricks.c.
Referenced by colorfn().
void register_node_type_tex_bricks (bNodeTreeType * ttype)
Definition at line 123 of file node_texture_bricks.c.
References exec(), init(), NODE_CLASS_PATTERN, NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and TEX_NODE_BRICKS.
Referenced by registerTextureNodes().
Variable Documentation
bNodeSocketTemplate inputs[] [static]
Initial value:
 {
    { SOCK_RGBA,  1, "Bricks 1",    0.596f, 0.282f, 0.0f,  1.0f },
    { SOCK_RGBA,  1, "Bricks 2",    0.632f, 0.504f, 0.05f, 1.0f },
    { SOCK_RGBA,  1, "Mortar",      0.0f,   0.0f,   0.0f,  1.0f },
    { SOCK_FLOAT, 1, "Thickness",   0.02f,  0.0f,   0.0f,  0.0f,  0.0f,    1.0f, PROP_UNSIGNED },
    { SOCK_FLOAT, 1, "Bias",        0.0f,   0.0f,   0.0f,  0.0f, -1.0f,    1.0f, PROP_NONE },
    { SOCK_FLOAT, 1, "Brick Width", 0.5f,   0.0f,   0.0f,  0.0f,  0.001f, 99.0f, PROP_UNSIGNED },
    { SOCK_FLOAT, 1, "Row Height",  0.25f,  0.0f,   0.0f,  0.0f,  0.001f, 99.0f, PROP_UNSIGNED },
    { -1, 0, "" }
}
Definition at line 38 of file node_texture_bricks.c.
bNodeSocketTemplate outputs[] [static]
Initial value:
 {
    { SOCK_RGBA, 0, "Color"},
    { -1, 0, "" }
}
Definition at line 48 of file node_texture_bricks.c.