Blender: btUniversalConstraint Class Reference
btUniversalConstraint Class Reference
#include <btUniversalConstraint.h>
Public Member Functions
btUniversalConstraint (btRigidBody &rbA, btRigidBody &rbB, btVector3 &anchor, btVector3 &axis1, btVector3 &axis2)
const btVector3 & getAnchor ()
const btVector3 & getAnchor2 ()
const btVector3 & getAxis1 ()
const btVector3 & getAxis2 ()
btScalar getAngle1 ()
btScalar getAngle2 ()
void setUpperLimit (btScalar ang1max, btScalar ang2max)
void setLowerLimit (btScalar ang1min, btScalar ang2min)
void setAxis (const btVector3 &axis1, const btVector3 &axis2)
Protected Attributes
btVector3 m_anchor
btVector3 m_axis1
btVector3 m_axis2
Detailed Description
Constraint similar to ODE Universal Joint has 2 rotatioonal degrees of freedom, similar to Euler rotations around Z (axis 1) and Y (axis 2) Description from ODE manual : "Given axis 1 on body 1, and axis 2 on body 2 that is perpendicular to axis 1, it keeps them perpendicular. In other words, rotation of the two bodies about the direction perpendicular to the two axes will be equal."
Definition at line 34 of file btUniversalConstraint.h.
Constructor & Destructor Documentation
btUniversalConstraint::btUniversalConstraint (btRigidBody & rbA, btRigidBody & rbB, btVector3 & anchor, btVector3 & axis1, btVector3 & axis2)
Definition at line 30 of file btUniversalConstraint.cpp.
References btTransform::getBasis(), btRigidBody::getCenterOfMassTransform(), btTransform::inverse(), btGeneric6DofConstraint::m_frameInA, btGeneric6DofConstraint::m_frameInB, btGeneric6DofConstraint::setAngularLowerLimit(), btGeneric6DofConstraint::setAngularUpperLimit(), btTransform::setIdentity(), btGeneric6DofConstraint::setLinearLowerLimit(), btGeneric6DofConstraint::setLinearUpperLimit(), btTransform::setOrigin(), btMatrix3x3::setValue(), SIMD_HALF_PI, SIMD_PI, and UNIV_EPS.
Member Function Documentation
const btVector3& btUniversalConstraint::getAnchor () [inline]
Definition at line 46 of file btUniversalConstraint.h.
References btTransform::getOrigin(), and btGeneric6DofConstraint::m_calculatedTransformA.
const btVector3& btUniversalConstraint::getAnchor2 () [inline]
Definition at line 47 of file btUniversalConstraint.h.
References btTransform::getOrigin(), and btGeneric6DofConstraint::m_calculatedTransformB.
btScalar btUniversalConstraint::getAngle1 () [inline]
Definition at line 50 of file btUniversalConstraint.h.
References btGeneric6DofConstraint::getAngle().
btScalar btUniversalConstraint::getAngle2 () [inline]
Definition at line 51 of file btUniversalConstraint.h.
References btGeneric6DofConstraint::getAngle().
const btVector3& btUniversalConstraint::getAxis1 () [inline]
Definition at line 48 of file btUniversalConstraint.h.
References m_axis1.
const btVector3& btUniversalConstraint::getAxis2 () [inline]
Definition at line 49 of file btUniversalConstraint.h.
References m_axis2.
void btUniversalConstraint::setAxis (const btVector3 & axis1, const btVector3 & axis2)
Reimplemented from btGeneric6DofConstraint.
Definition at line 64 of file btUniversalConstraint.cpp.
References btGeneric6DofConstraint::calculateTransforms(), btTransform::getBasis(), btRigidBody::getCenterOfMassTransform(), btTransform::inverse(), m_anchor, m_axis1, m_axis2, btGeneric6DofConstraint::m_frameInA, btGeneric6DofConstraint::m_frameInB, btTypedConstraint::m_rbA, btTypedConstraint::m_rbB, btTransform::setIdentity(), btTransform::setOrigin(), and btMatrix3x3::setValue().
void btUniversalConstraint::setLowerLimit (btScalar ang1min, btScalar ang2min) [inline]
Definition at line 54 of file btUniversalConstraint.h.
References btGeneric6DofConstraint::setAngularLowerLimit().
void btUniversalConstraint::setUpperLimit (btScalar ang1max, btScalar ang2max) [inline]
Definition at line 53 of file btUniversalConstraint.h.
References btGeneric6DofConstraint::setAngularUpperLimit().
Member Data Documentation
btVector3 btUniversalConstraint::m_anchor [protected]
Definition at line 37 of file btUniversalConstraint.h.
Referenced by setAxis().
btVector3 btUniversalConstraint::m_axis1 [protected]
Definition at line 38 of file btUniversalConstraint.h.
Referenced by getAxis1(), and setAxis().
btVector3 btUniversalConstraint::m_axis2 [protected]
Definition at line 39 of file btUniversalConstraint.h.
Referenced by getAxis2(), and setAxis().
The documentation for this class was generated from the following files:
btUniversalConstraint.h
btUniversalConstraint.cpp