Blender: node_composite_image.c File Reference
node_composite_image.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static bNodeSocket * cmp_node_image_add_render_pass_output (bNodeTree *ntree, bNode *node, int UNUSED(pass), int rres_index)
static void cmp_node_image_add_render_pass_outputs (bNodeTree *ntree, bNode *node, int passflag)
static void cmp_node_image_add_multilayer_outputs (bNodeTree *ntree, bNode *node, RenderLayer *rl)
static void cmp_node_image_create_outputs (bNodeTree *ntree, bNode *node)
static bNodeSocket * cmp_node_image_output_find_match (bNode *UNUSED(node), bNodeSocket *newsock, ListBase *oldsocklist)
static bNodeSocket * cmp_node_image_output_relink (bNode *node, bNodeSocket *oldsock, int oldindex)
static void cmp_node_image_sync_output (bNode *UNUSED(node), bNodeSocket *UNUSED(newsock), bNodeSocket *UNUSED(oldsock))
static void cmp_node_image_verify_outputs (bNodeTree *ntree, bNode *node)
static void cmp_node_image_update (bNodeTree *ntree, bNode *node)
float * node_composit_get_float_buffer (RenderData *rd, ImBuf *ibuf, int *alloc)
static CompBuf * node_composit_get_image (RenderData *rd, Image *ima, ImageUser *iuser)
static CompBuf * node_composit_get_zimage (bNode *node, RenderData *rd)
static CompBuf * compbuf_multilayer_get (RenderData *rd, RenderLayer *rl, Image *ima, ImageUser *iuser, int passindex)
static void node_composit_exec_image (void *data, bNode *node, bNodeStack **UNUSED(in), bNodeStack **out)
static void node_composit_init_image (bNodeTree *ntree, bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_image (bNodeTreeType *ttype)
static CompBuf * compbuf_from_pass (RenderData *rd, RenderLayer *rl, int rectx, int recty, int passcode)
static void node_composit_rlayers_out (RenderData *rd, RenderLayer *rl, bNodeStack **out, int rectx, int recty)
static void node_composit_exec_rlayers (void *data, bNode *node, bNodeStack **UNUSED(in), bNodeStack **out)
void register_node_type_cmp_rlayers (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_rlayers_out []
Detailed Description
Definition in file node_composite_image.c.
Function Documentation
static void cmp_node_image_add_multilayer_outputs (bNodeTree * ntree, bNode * node, RenderLayer * rl) [static]
Definition at line 144 of file node_composite_image.c.
References RenderPass::channels, ListBase::first, RenderPass::name, RenderPass::next, nodeAddSocket(), RenderLayer::passes, SET_INT_IN_POINTER, SOCK_FLOAT, SOCK_OUT, SOCK_RGBA, and bNodeSocket::storage.
Referenced by cmp_node_image_create_outputs().
static bNodeSocket* cmp_node_image_add_render_pass_output (bNodeTree * ntree, bNode * node, int UNUSEDpass, int rres_index) [static]
Definition at line 69 of file node_composite_image.c.
References node_add_output_from_template(), SET_INT_IN_POINTER, and bNodeSocket::storage.
Referenced by cmp_node_image_add_render_pass_outputs().
static void cmp_node_image_add_render_pass_outputs (bNodeTree * ntree, bNode * node, int passflag) [static]
Definition at line 80 of file node_composite_image.c.
References cmp_node_image_add_render_pass_output(), RRES_OUT_ALPHA, RRES_OUT_AO, RRES_OUT_DIFF, RRES_OUT_DIFF_COLOR, RRES_OUT_DIFF_DIRECT, RRES_OUT_DIFF_INDIRECT, RRES_OUT_EMIT, RRES_OUT_ENV, RRES_OUT_GLOSSY_COLOR, RRES_OUT_GLOSSY_DIRECT, RRES_OUT_GLOSSY_INDIRECT, RRES_OUT_IMAGE, RRES_OUT_INDEXMA, RRES_OUT_INDEXOB, RRES_OUT_INDIRECT, RRES_OUT_MIST, RRES_OUT_NORMAL, RRES_OUT_REFLECT, RRES_OUT_REFRACT, RRES_OUT_RGBA, RRES_OUT_SHADOW, RRES_OUT_SPEC, RRES_OUT_TRANSM_COLOR, RRES_OUT_TRANSM_DIRECT, RRES_OUT_TRANSM_INDIRECT, RRES_OUT_UV, RRES_OUT_VEC, RRES_OUT_Z, SCE_PASS_AO, SCE_PASS_COMBINED, SCE_PASS_DIFFUSE, SCE_PASS_DIFFUSE_COLOR, SCE_PASS_DIFFUSE_DIRECT, SCE_PASS_DIFFUSE_INDIRECT, SCE_PASS_EMIT, SCE_PASS_ENVIRONMENT, SCE_PASS_GLOSSY_COLOR, SCE_PASS_GLOSSY_DIRECT, SCE_PASS_GLOSSY_INDIRECT, SCE_PASS_INDEXMA, SCE_PASS_INDEXOB, SCE_PASS_INDIRECT, SCE_PASS_MIST, SCE_PASS_NORMAL, SCE_PASS_REFLECT, SCE_PASS_REFRACT, SCE_PASS_RGBA, SCE_PASS_SHADOW, SCE_PASS_SPEC, SCE_PASS_TRANSM_COLOR, SCE_PASS_TRANSM_DIRECT, SCE_PASS_TRANSM_INDIRECT, SCE_PASS_UV, SCE_PASS_VECTOR, and SCE_PASS_Z.
Referenced by cmp_node_image_create_outputs().
static void cmp_node_image_create_outputs (bNodeTree * ntree, bNode * node) [static]
Definition at line 162 of file node_composite_image.c.
References BKE_image_get_ibuf(), BLI_findlink(), cmp_node_image_add_multilayer_outputs(), cmp_node_image_add_render_pass_outputs(), bNode::id, if(), IMA_TYPE_MULTILAYER, ImageUser::layer, RenderResult::layers, RenderLayer::passflag, Image::rr, RRES_OUT_ALPHA, RRES_OUT_IMAGE, RRES_OUT_Z, bNode::storage, and Image::type.
Referenced by cmp_node_image_verify_outputs().
static bNodeSocket* cmp_node_image_output_find_match (bNode * UNUSEDnode, bNodeSocket * newsock, ListBase * oldsocklist) [static]
Definition at line 190 of file node_composite_image.c.
References ListBase::first, bNodeSocket::name, bNodeSocket::next, and NULL.
Referenced by cmp_node_image_verify_outputs().
static bNodeSocket* cmp_node_image_output_relink (bNode * node, bNodeSocket * oldsock, int oldindex) [static]
Definition at line 200 of file node_composite_image.c.
References BLI_findlink(), ListBase::first, bNodeSocket::name, bNodeSocket::next, and bNode::outputs.
Referenced by cmp_node_image_verify_outputs().
static void cmp_node_image_sync_output (bNode * UNUSEDnode, bNodeSocket * UNUSEDnewsock, bNodeSocket * UNUSEDoldsock) [static]
Definition at line 213 of file node_composite_image.c.
Referenced by cmp_node_image_verify_outputs().
static void cmp_node_image_update (bNodeTree * ntree, bNode * node) [static]
Definition at line 268 of file node_composite_image.c.
References cmp_node_image_verify_outputs(), NODE_UPDATE_ID, and bNode::update.
Referenced by register_node_type_cmp_image().
static void cmp_node_image_verify_outputs (bNodeTree * ntree, bNode * node) [static]
Definition at line 219 of file node_composite_image.c.
References cmp_node_image_create_outputs(), cmp_node_image_output_find_match(), cmp_node_image_output_relink(), cmp_node_image_sync_output(), ListBase::first, bNodeSocket::flag, bNodeLink::fromsock, ListBase::last, link(), bNodeTree::links, bNodeSocket::next, bNodeLink::next, nodeRemoveSocket(), NULL, bNode::outputs, and SOCK_DYNAMIC.
Referenced by cmp_node_image_update(), and node_composit_init_image().
static CompBuf* compbuf_from_pass (RenderData * rd, RenderLayer * rl, int rectx, int recty, int passcode) [static]
Definition at line 537 of file node_composite_image.c.
References alloc_compbuf(), CB_RGBA, CB_VAL, CB_VEC3, CB_VEC4, RenderData::disprect, ELEM, ELEM4, get_cropped_compbuf(), NULL, R_COMP_CROP, RE_RenderLayerGetPass(), CompBuf::rect, SCE_PASS_COMBINED, SCE_PASS_INDEXMA, SCE_PASS_INDEXOB, SCE_PASS_MIST, SCE_PASS_RGBA, SCE_PASS_VECTOR, SCE_PASS_Z, and RenderData::scemode.
Referenced by node_composit_rlayers_out().
static CompBuf* compbuf_multilayer_get (RenderData * rd, RenderLayer * rl, Image * ima, ImageUser * iuser, int passindex) [static]
Definition at line 397 of file node_composite_image.c.
References BKE_image_multilayer_index(), BLI_findlink(), node_composit_get_image(), NULL, ImageUser::pass, RenderLayer::passes, and Image::rr.
Referenced by node_composit_exec_image().
static void node_composit_exec_image (void * data, bNode * node, bNodeStack ** UNUSEDin, bNodeStack ** out) [static]
Definition at line 412 of file node_composite_image.c.
References BKE_image_get_ibuf(), BKE_image_user_calc_frame(), BLI_countlist(), BLI_findlink(), CB_RGBA, RenderData::cfra, CHAN_A, compbuf_multilayer_get(), bNodeStack::data, data, ListBase::first, Image::flag, generate_preview(), GET_INT_FROM_POINTER, i, bNode::id, IMA_DO_PREMUL, IMA_TYPE_MULTILAYER, RenderResult::layers, CompBuf::malloc, MEM_dupallocN(), bNodeSocket::name, bNodeSocket::next, node_composit_get_image(), node_composit_get_zimage(), NULL, bNode::outputs, CompBuf::rect, Image::rr, bNodeSocket::storage, bNode::storage, CompBuf::type, Image::type, valbuf_from_rgbabuf(), CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_image().
static void node_composit_exec_rlayers (void * data, bNode * node, bNodeStack ** UNUSEDin, bNodeStack ** out) [static]
Definition at line 621 of file node_composite_image.c.
References alloc_compbuf(), BLI_findlink(), CB_RGBA, CHAN_A, bNode::custom1, bNodeStack::data, data, RenderData::disprect, generate_preview(), get_cropped_compbuf(), Scene::id, bNode::id, RenderData::layers, SceneRenderLayer::name, ID::name, node_composit_rlayers_out(), NULL, Scene::r, R_COMP_CROP, RE_AcquireResultRead(), RE_GetRender(), RE_GetRenderLayer(), RE_ReleaseResult(), CompBuf::rect, RenderLayer::rectf, RenderResult::rectx, RenderResult::recty, RRES_OUT_ALPHA, RRES_OUT_IMAGE, RenderData::scemode, valbuf_from_rgbabuf(), RenderResult::xof, CompBuf::xof, RenderResult::yof, and CompBuf::yof.
Referenced by register_node_type_cmp_rlayers().
float* node_composit_get_float_buffer (RenderData * rd, ImBuf * ibuf, int * alloc)
Definition at line 276 of file node_composite_image.c.
References RenderData::color_mgt_flag, FALSE, ImBuf::flags, IB_cm_predivide, IB_PROFILE_LINEAR_RGB, IB_PROFILE_NONE, IB_PROFILE_SRGB, IMB_buffer_float_from_float(), MEM_mapallocN(), ImBuf::profile, R_COLOR_MANAGEMENT, ImBuf::rect_float, TRUE, ImBuf::x, and ImBuf::y.
Referenced by node_composit_get_image(), and node_composit_get_movieclip().
static CompBuf* node_composit_get_image (RenderData * rd, Image * ima, ImageUser * iuser) [static]
Definition at line 317 of file node_composite_image.c.
References alloc_compbuf(), BKE_image_get_ibuf(), ImBuf::channels, RenderData::disprect, FALSE, get_cropped_compbuf(), IMB_float_from_rect(), CompBuf::malloc, MEM_freeN(), node_composit_get_float_buffer(), NULL, R_COMP_CROP, ImBuf::rect, CompBuf::rect, ImBuf::rect_float, Image::rr, RenderData::scemode, ImBuf::x, and ImBuf::y.
Referenced by compbuf_multilayer_get(), and node_composit_exec_image().
static CompBuf* node_composit_get_zimage (bNode * node, RenderData * rd) [static]
Definition at line 379 of file node_composite_image.c.
References alloc_compbuf(), BKE_image_get_ibuf(), CB_VAL, RenderData::disprect, get_cropped_compbuf(), bNode::id, NULL, R_COMP_CROP, CompBuf::rect, RenderData::scemode, bNode::storage, ImBuf::x, ImBuf::y, and ImBuf::zbuf_float.
Referenced by node_composit_exec_image().
static void node_composit_init_image (bNodeTree * ntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 507 of file node_composite_image.c.
References cmp_node_image_verify_outputs(), ImageUser::fie_ima, ImageUser::frames, MEM_callocN(), ImageUser::ok, ImageUser::sfra, and bNode::storage.
Referenced by register_node_type_cmp_image().
static void node_composit_rlayers_out (RenderData * rd, RenderLayer * rl, bNodeStack ** out, int rectx, int recty) [static]
Definition at line 562 of file node_composite_image.c.
References compbuf_from_pass(), bNodeStack::data, RRES_OUT_AO, RRES_OUT_DIFF, RRES_OUT_DIFF_COLOR, RRES_OUT_DIFF_DIRECT, RRES_OUT_DIFF_INDIRECT, RRES_OUT_EMIT, RRES_OUT_ENV, RRES_OUT_GLOSSY_COLOR, RRES_OUT_GLOSSY_DIRECT, RRES_OUT_GLOSSY_INDIRECT, RRES_OUT_INDEXMA, RRES_OUT_INDEXOB, RRES_OUT_INDIRECT, RRES_OUT_MIST, RRES_OUT_NORMAL, RRES_OUT_REFLECT, RRES_OUT_REFRACT, RRES_OUT_RGBA, RRES_OUT_SHADOW, RRES_OUT_SPEC, RRES_OUT_TRANSM_COLOR, RRES_OUT_TRANSM_DIRECT, RRES_OUT_TRANSM_INDIRECT, RRES_OUT_UV, RRES_OUT_VEC, RRES_OUT_Z, SCE_PASS_AO, SCE_PASS_DIFFUSE, SCE_PASS_DIFFUSE_COLOR, SCE_PASS_DIFFUSE_DIRECT, SCE_PASS_DIFFUSE_INDIRECT, SCE_PASS_EMIT, SCE_PASS_ENVIRONMENT, SCE_PASS_GLOSSY_COLOR, SCE_PASS_GLOSSY_DIRECT, SCE_PASS_GLOSSY_INDIRECT, SCE_PASS_INDEXMA, SCE_PASS_INDEXOB, SCE_PASS_INDIRECT, SCE_PASS_MIST, SCE_PASS_NORMAL, SCE_PASS_REFLECT, SCE_PASS_REFRACT, SCE_PASS_RGBA, SCE_PASS_SHADOW, SCE_PASS_SPEC, SCE_PASS_TRANSM_COLOR, SCE_PASS_TRANSM_DIRECT, SCE_PASS_TRANSM_INDIRECT, SCE_PASS_UV, SCE_PASS_VECTOR, and SCE_PASS_Z.
Referenced by node_composit_exec_rlayers().
void register_node_type_cmp_image (bNodeTreeType * ttype)
Definition at line 520 of file node_composite_image.c.
References CMP_NODE_IMAGE, cmp_node_image_update(), NODE_CLASS_INPUT, node_composit_exec_image(), node_composit_init_image(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_storage(), node_type_update(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
void register_node_type_cmp_rlayers (bNodeTreeType * ttype)
Definition at line 671 of file node_composite_image.c.
References CMP_NODE_R_LAYERS, NODE_CLASS_INPUT, node_composit_exec_rlayers(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_rlayers_out[] [static]
Definition at line 37 of file node_composite_image.c.