Blender: filter.cpp File Reference
filter.cpp File Reference
#include "camera.h"
#include "device.h"
#include "filter.h"
#include "scene.h"
#include "kernel_types.h"
#include "util_algorithm.h"
#include "util_debug.h"
#include "util_math.h"
Functions
static float filter_func_box (float v, float width)
static float filter_func_gaussian (float v, float width)
static vector< float > filter_table (FilterType type, float width)
Function Documentation
static float filter_func_box (float v, float width) [static]
Definition at line 43 of file filter.cpp.
Referenced by filter_table().
static float filter_func_gaussian (float v, float width) [static]
Definition at line 48 of file filter.cpp.
References expf.
Referenced by filter_table().
static vector<float> filter_table (FilterType type, float width) [static]
Definition at line 54 of file filter.cpp.
References assert, fabsf, FILTER_BOX, filter_func_box(), filter_func_gaussian(), FILTER_GAUSSIAN, FILTER_TABLE_SIZE, i, and NULL.
Referenced by Filter::device_update().