Blender: node_composite_flip.c File Reference
node_composite_flip.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void node_composit_exec_flip (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_flip (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_flip_in []
static bNodeSocketTemplate cmp_node_flip_out []
Detailed Description
Definition in file node_composite_flip.c.
Function Documentation
static void node_composit_exec_flip (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 46 of file node_composite_flip.c.
References alloc_compbuf(), bNode::custom1, bNodeStack::data, data, i, CompBuf::rect, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_flip().
void register_node_type_cmp_flip (bNodeTreeType * ttype)
Definition at line 91 of file node_composite_flip.c.
References CMP_NODE_FLIP, NODE_CLASS_DISTORT, node_composit_exec_flip(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_flip_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_composite_flip.c.
bNodeSocketTemplate cmp_node_flip_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 41 of file node_composite_flip.c.