Blender: PHY_IGraphicController Class Reference
PHY_IGraphicController Class Reference
#include <PHY_IGraphicController.h>
Public Member Functions
virtual ~PHY_IGraphicController ()
virtual bool SetGraphicTransform ()=0
virtual void Activate (bool active=true)=0
virtual void setLocalAabb (const PHY__Vector3 &aabbMin, const PHY__Vector3 &aabbMax)=0
virtual void setLocalAabb (const float *aabbMin, const float *aabbMax)=0
virtual PHY_IGraphicController * GetReplica (class PHY_IMotionState *motionstate)
Detailed Description
PHY_IPhysicsController is the abstract simplified Interface to a physical object. It contains the IMotionState and IDeformableMesh Interfaces.
Definition at line 42 of file PHY_IGraphicController.h.
Constructor & Destructor Documentation
PHY_IGraphicController::~PHY_IGraphicController () [virtual]
Definition at line 34 of file PHY_IGraphicController.cpp.
Member Function Documentation
virtual void PHY_IGraphicController::Activate (bool active = true) [pure virtual]
Implemented in CcdGraphicController.
Referenced by KX_GameObject::ActivateGraphicController(), and KX_GameObject::SetVisible().
virtual PHY_IGraphicController* PHY_IGraphicController::GetReplica (class PHY_IMotionState * motionstate) [inline, virtual]
Reimplemented in CcdGraphicController.
Definition at line 54 of file PHY_IGraphicController.h.
Referenced by KX_Scene::AddNodeReplicaObject().
virtual bool PHY_IGraphicController::SetGraphicTransform () [pure virtual]
SynchronizeMotionStates ynchronizes dynas, kinematic and deformable entities (and do 'late binding')
Implemented in CcdGraphicController.
Referenced by KX_GameObject::SynchronizeTransform(), and KX_GameObject::UpdateTransform().
virtual void PHY_IGraphicController::setLocalAabb (const PHY__Vector3 & aabbMin, const PHY__Vector3 & aabbMax) [pure virtual]
Implemented in CcdGraphicController.
Referenced by BL_ModifierDeformer::Update().
virtual void PHY_IGraphicController::setLocalAabb (const float * aabbMin, const float * aabbMax) [pure virtual]
The documentation for this class was generated from the following files:
PHY_IGraphicController.h
PHY_IGraphicController.cpp