Blender: btSoftColliders::CollideSDF_RS Struct Reference
btSoftColliders::CollideSDF_RS Struct Reference
#include <btSoftBodyInternals.h>
Public Member Functions
void Process (const btDbvtNode *leaf)
void DoNode (btSoftBody::Node &n) const
Public Attributes
btSoftBody * psb
btCollisionObject * m_colObj1
btRigidBody * m_rigidBody
btScalar dynmargin
btScalar stamargin
Detailed Description
Definition at line 832 of file btSoftBodyInternals.h.
Member Function Documentation
void btSoftColliders::CollideSDF_RS::DoNode (btSoftBody::Node & n) const [inline]
Definition at line 839 of file btSoftBodyInternals.h.
References btDot(), btFabs(), btTransform::getOrigin(), ImpulseMatrix(), btSoftBody::Node::m_battach, btSoftBody::RContact::m_c0, btSoftBody::RContact::m_c1, btSoftBody::RContact::m_c2, btSoftBody::RContact::m_c3, btSoftBody::RContact::m_c4, btSoftBody::RContact::m_cti, btSoftBody::Node::m_im, btSoftBody::RContact::m_node, btSoftBody::Node::m_q, and btSoftBody::Node::m_x.
void btSoftColliders::CollideSDF_RS::Process (const btDbvtNode * leaf) [inline]
Reimplemented from btDbvt::ICollide.
Definition at line 834 of file btSoftBodyInternals.h.
References btDbvtNode::data.
Member Data Documentation
btScalar btSoftColliders::CollideSDF_RS::dynmargin
Definition at line 876 of file btSoftBodyInternals.h.
Referenced by btSoftBody::defaultCollisionHandler().
btCollisionObject* btSoftColliders::CollideSDF_RS::m_colObj1
Definition at line 874 of file btSoftBodyInternals.h.
Referenced by btSoftBody::defaultCollisionHandler().
btRigidBody* btSoftColliders::CollideSDF_RS::m_rigidBody
Definition at line 875 of file btSoftBodyInternals.h.
Referenced by btSoftBody::defaultCollisionHandler().
btSoftBody* btSoftColliders::CollideSDF_RS::psb
Definition at line 873 of file btSoftBodyInternals.h.
Referenced by btSoftBody::defaultCollisionHandler().
btScalar btSoftColliders::CollideSDF_RS::stamargin
Definition at line 877 of file btSoftBodyInternals.h.
Referenced by btSoftBody::defaultCollisionHandler().
The documentation for this struct was generated from the following file:
btSoftBodyInternals.h