Blender: BLI_linklist.c File Reference
BLI_linklist.c File Reference
blenlib
#include "MEM_guardedalloc.h"
#include "BLI_linklist.h"
#include "BLI_memarena.h"
Functions
int BLI_linklist_length (LinkNode *list)
int BLI_linklist_index (LinkNode *list, void *ptr)
LinkNode * BLI_linklist_find (LinkNode *list, int index)
void BLI_linklist_reverse (LinkNode **listp)
void BLI_linklist_prepend (LinkNode **listp, void *ptr)
void BLI_linklist_append (LinkNode **listp, void *ptr)
void BLI_linklist_prepend_arena (LinkNode **listp, void *ptr, MemArena *ma)
void BLI_linklist_insert_after (LinkNode **listp, void *ptr)
void BLI_linklist_free (LinkNode *list, LinkNodeFreeFP freefunc)
void BLI_linklist_apply (LinkNode *list, LinkNodeApplyFP applyfunc, void *userdata)
Detailed Description
Definition in file BLI_linklist.c.
Function Documentation
void BLI_linklist_append (LinkNode ** listp, void * ptr)
Definition at line 100 of file BLI_linklist.c.
References LinkNode::link, MEM_mallocN(), LinkNode::next, and NULL.
Referenced by cloth_build_springs(), createVertsTrisData(), navmesh_create_exec(), and project_paint_begin().
void BLI_linklist_apply (LinkNode * list, LinkNodeApplyFP applyfunc, void * userdata)
Definition at line 158 of file BLI_linklist.c.
References LinkNode::link, and LinkNode::next.
Referenced by bvhcache_find().
LinkNode* BLI_linklist_find (LinkNode * list, int index) [read]
Definition at line 64 of file BLI_linklist.c.
References i, LinkNode::next, and NULL.
void BLI_linklist_free (LinkNode * list, LinkNodeFreeFP freefunc)
Definition at line 145 of file BLI_linklist.c.
References LinkNode::link, MEM_freeN(), LinkNode::next, and next.
Referenced by _bpy_names(), BLI_file_free_lines(), BLI_memarena_free(), bvhcache_free(), cloth_build_springs(), cloth_free_errorsprings(), cloth_free_modifier(), cloth_free_modifier_extern(), createVertsTrisData(), editbmesh_calc_modifiers(), filelist_from_library(), layerInterp_mdeformvert(), KX_BlenderSceneConverter::LinkBlendFile(), mesh_calc_modifiers(), navmesh_create_exec(), object_mouse_select_menu(), and project_paint_begin().
int BLI_linklist_index (LinkNode * list, void * ptr)
Definition at line 53 of file BLI_linklist.c.
References LinkNode::link, and LinkNode::next.
Referenced by project_paint_begin().
void BLI_linklist_insert_after (LinkNode ** listp, void * ptr)
Definition at line 128 of file BLI_linklist.c.
References LinkNode::link, MEM_mallocN(), LinkNode::next, and NULL.
int BLI_linklist_length (LinkNode * list)
Definition at line 38 of file BLI_linklist.c.
References BLI_linklist_length(), len(), and LinkNode::next.
Referenced by BLI_linklist_length(), and filelist_from_library().
void BLI_linklist_prepend (LinkNode ** listp, void * ptr)
Definition at line 91 of file BLI_linklist.c.
References LinkNode::link, MEM_mallocN(), and LinkNode::next.
Referenced by BLI_file_read_as_lines(), BLI_memarena_alloc(), BLO_blendhandle_get_datablock_names(), BLO_blendhandle_get_linkable_groups(), BLO_blendhandle_get_previews(), bvhcache_insert(), cloth_add_spring(), cloth_build_springs(), layerInterp_mdeformvert(), and object_mouse_select_menu().
void BLI_linklist_prepend_arena (LinkNode ** listp, void * ptr, MemArena * ma)
Definition at line 119 of file BLI_linklist.c.
References BLI_memarena_alloc(), LinkNode::link, and LinkNode::next.
Referenced by do_projectpaint_smear(), do_projectpaint_smear_f(), project_paint_begin(), project_paint_delayed_face_init(), and project_paint_face_init().
void BLI_linklist_reverse (LinkNode ** listp)
Definition at line 75 of file BLI_linklist.c.
References next, and NULL.
Referenced by BLI_file_read_as_lines(), and modifiers_calcDataMasks().