Blender: IMB_allocimbuf.h File Reference
IMB_allocimbuf.h File Reference
IMage Buffer
Header file for allocimbuf.c.
Functions
short imb_addencodedbufferImBuf (struct ImBuf *ibuf)
short imb_enlargeencodedbufferImBuf (struct ImBuf *ibuf)
Detailed Description
Header file for allocimbuf.c.
Definition in file IMB_allocimbuf.h.
Function Documentation
short imb_addencodedbufferImBuf (struct ImBuf * ibuf)
Definition at line 225 of file allocimbuf.c.
References ImBuf::encodedbuffer, ImBuf::encodedbuffersize, ImBuf::encodedsize, FALSE, ImBuf::flags, freeencodedbufferImBuf(), IB_mem, ImBuf::mall, MEM_mallocN(), NULL, and TRUE.
Referenced by IMB_dupImBuf(), imb_save_openexr(), and imb_savepng().
short imb_enlargeencodedbufferImBuf (struct ImBuf * ibuf)
Definition at line 246 of file allocimbuf.c.
References ImBuf::encodedbuffer, ImBuf::encodedbuffersize, ImBuf::encodedsize, FALSE, ImBuf::flags, freeencodedbufferImBuf(), IB_mem, ImBuf::mall, MEM_mallocN(), NULL, and TRUE.
Referenced by WriteData().