Blender: btClosestNotMeConvexResultCallback Class Reference
btClosestNotMeConvexResultCallback Class Reference
Public Member Functions
btClosestNotMeConvexResultCallback (btCollisionObject *me, const btVector3 &fromA, const btVector3 &toA, btOverlappingPairCache *pairCache, btDispatcher *dispatcher)
virtual btScalar addSingleResult (btCollisionWorld::LocalConvexResult &convexResult, bool normalInWorldSpace)
virtual bool needsCollision (btBroadphaseProxy *proxy0) const
Detailed Description
Definition at line 746 of file btDiscreteDynamicsWorld.cpp.
Constructor & Destructor Documentation
btClosestNotMeConvexResultCallback::btClosestNotMeConvexResultCallback (btCollisionObject * me, const btVector3 & fromA, const btVector3 & toA, btOverlappingPairCache * pairCache, btDispatcher * dispatcher) [inline]
Definition at line 755 of file btDiscreteDynamicsWorld.cpp.
Member Function Documentation
virtual btScalar btClosestNotMeConvexResultCallback::addSingleResult (btCollisionWorld::LocalConvexResult & convexResult, bool normalInWorldSpace) [inline, virtual]
Reimplemented from btCollisionWorld::ClosestConvexResultCallback.
Definition at line 764 of file btDiscreteDynamicsWorld.cpp.
References btCollisionWorld::ClosestConvexResultCallback::m_convexFromWorld, btCollisionWorld::ClosestConvexResultCallback::m_convexToWorld, btCollisionWorld::LocalConvexResult::m_hitCollisionObject, and btCollisionWorld::LocalConvexResult::m_hitNormalLocal.
virtual bool btClosestNotMeConvexResultCallback::needsCollision (btBroadphaseProxy * proxy0) const [inline, virtual]
don't do CCD when the collision filters are not matching
don't do CCD when there are already contact points (touching contact/penetration)
Reimplemented from btCollisionWorld::ConvexResultCallback.
Definition at line 785 of file btDiscreteDynamicsWorld.cpp.
References btOverlappingPairCache::findPair(), if(), btDispatcher::needsResponse(), btAlignedObjectArray< T >::resize(), and btAlignedObjectArray< T >::size().
The documentation for this class was generated from the following file:
btDiscreteDynamicsWorld.cpp