Blender: MOD_fluidsim_util.h File Reference
MOD_fluidsim_util.h File Reference
modifiers
Functions
void fluidsim_init (struct FluidsimModifierData *fluidmd)
void fluidsim_free (struct FluidsimModifierData *fluidmd)
struct DerivedMesh * fluidsimModifier_do (struct FluidsimModifierData *fluidmd, struct Scene *scene, struct Object *ob, struct DerivedMesh *dm, int useRenderParams, int isFinalCalc)
Detailed Description
Definition in file MOD_fluidsim_util.h.
Function Documentation
void fluidsim_free (struct FluidsimModifierData * fluidmd)
Definition at line 152 of file MOD_fluidsim_util.c.
References FluidsimModifierData::fss, MEM_freeN(), FluidsimSettings::meshVelocities, and NULL.
Referenced by freeData().
void fluidsim_init (struct FluidsimModifierData * fluidmd)
Definition at line 66 of file MOD_fluidsim_util.c.
References FluidsimSettings::animEnd, FluidsimSettings::animRate, FluidsimSettings::animStart, FluidsimSettings::attractforceRadius, FluidsimSettings::attractforceStrength, FluidsimSettings::cpsQuality, FluidsimSettings::cpsTimeEnd, FluidsimSettings::cpsTimeStart, FluidsimSettings::domainNovecgen, FluidsimSettings::flag, FluidsimSettings::fmd, FluidsimModifierData::fss, FluidsimSettings::generateParticles, FluidsimSettings::generateTracers, FluidsimSettings::grav, FluidsimSettings::gstar, FluidsimSettings::guiDisplayMode, FluidsimSettings::lastgoodframe, FluidsimSettings::maxRefine, MEM_callocN(), FluidsimSettings::meshVelocities, modifier_path_init(), NULL, OB_FLUIDSIM_ACTIVE, OB_FLUIDSIM_ENABLE, OB_FSBND_PARTSLIP, OB_FSSG_NOOBS, FluidsimSettings::particleInfAlpha, FluidsimSettings::particleInfSize, FluidsimSettings::partSlipValue, FluidsimSettings::previewresxyz, FluidsimSettings::realsize, FluidsimSettings::renderDisplayMode, FluidsimSettings::resolutionxyz, FluidsimSettings::show_advancedoptions, FluidsimSettings::surfaceSmoothing, FluidsimSettings::surfaceSubdivs, FluidsimSettings::surfdataPath, FluidsimSettings::type, FluidsimSettings::typeFlags, FluidsimSettings::velocityforceRadius, FluidsimSettings::velocityforceStrength, FluidsimSettings::viscosityExponent, FluidsimSettings::viscosityValue, and FluidsimSettings::volumeInitType.
Referenced by initData().
struct DerivedMesh* fluidsimModifier_do (struct FluidsimModifierData * fluidmd, struct Scene * scene, struct Object * ob, struct DerivedMesh * dm, int useRenderParams, int isFinalCalc) [read]