Blender: GEN_Link Class Reference
GEN_Link Class Reference
#include <GEN_List.h>
Public Member Functions
GEN_Link ()
GEN_Link (GEN_Link *next, GEN_Link *prev)
GEN_Link * getNext () const
GEN_Link * getPrev () const
bool isHead () const
bool isTail () const
void insertBefore (GEN_Link *link)
void insertAfter (GEN_Link *link)
void remove ()
Detailed Description
Definition at line 36 of file GEN_List.h.
Constructor & Destructor Documentation
GEN_Link::GEN_Link () [inline]
Definition at line 38 of file GEN_List.h.
GEN_Link::GEN_Link (GEN_Link * next, GEN_Link * prev) [inline]
Definition at line 39 of file GEN_List.h.
Member Function Documentation
GEN_Link* GEN_Link::getNext () const [inline]
Definition at line 41 of file GEN_List.h.
Referenced by GEN_List::getHead().
GEN_Link* GEN_Link::getPrev () const [inline]
Definition at line 42 of file GEN_List.h.
Referenced by GEN_List::getTail().
void GEN_Link::insertAfter (GEN_Link * link) [inline]
Definition at line 54 of file GEN_List.h.
References link().
Referenced by GEN_List::addHead().
void GEN_Link::insertBefore (GEN_Link * link) [inline]
Definition at line 47 of file GEN_List.h.
References link().
Referenced by GEN_List::addTail().
bool GEN_Link::isHead () const [inline]
Definition at line 44 of file GEN_List.h.
bool GEN_Link::isTail () const [inline]
Definition at line 45 of file GEN_List.h.
void GEN_Link::remove () [inline]
Definition at line 61 of file GEN_List.h.
The documentation for this class was generated from the following file:
GEN_List.h