Blender: KDL Namespace Reference
KDL Namespace Reference
Classes
class Chain
This class encapsulates a serial kinematic interconnection structure. It is build out of segments.
class ChainFkSolverPos
This abstract class encapsulates a solver for the forward position kinematics for a KDL::Chain.
class ChainFkSolverVel
This abstract class encapsulates a solver for the forward velocity kinematics for a KDL::Chain.
class ChainFkSolverAcc
This abstract class encapsulates a solver for the forward acceleration kinematics for a KDL::Chain.
class ChainFkSolverPos_recursive
class ChainJntToJacSolver
Class to calculate the jacobian of a general KDL::Chain, it is used by other solvers. It should not be used outside of KDL.
class VectorAcc
class RotationAcc
class FrameAcc
class TwistAcc
class Vector
A concrete implementation of a 3 dimensional vector class.
class Rotation
represents rotations in 3 dimensional space.
class Frame
represents a frame transformation in 3D space (rotation + translation)
class Twist
represents both translational and rotational velocities.
class Wrench
represents both translational and rotational acceleration.
class Vector2
2D version of Vector
class Rotation2
class Frame2
class VectorVel
class RotationVel
class FrameVel
class TwistVel
class Inertia
class Jacobian
class JntArray
This class represents an fixed size array containing joint values of a KDL::Chain.
class JntArrayAcc
class JntArrayVel
class Joint
This class encapsulates a simple joint, that is with one parameterized degree of freedom and with scalar dynamic properties.
class Segment
This class encapsulates a simple segment, that is a "rigid body" (i.e., a frame and an inertia) with a joint and with "handles", root and tip to connect to other segments.
class TreeElement
class Tree
This class encapsulates a tree kinematic interconnection structure. It is build out of segments.
class TreeFkSolverPos
This abstract class encapsulates a solver for the forward position kinematics for a KDL::Tree.
class TreeFkSolverPos_recursive
class TreeJntToJacSolver
class Error
class Error_IO
class Error_BasicIO
class Error_BasicIO_File
class Error_BasicIO_Exp_Delim
class Error_BasicIO_Not_A_Space
class Error_BasicIO_Unexpected
class Error_BasicIO_ToBig
class Error_BasicIO_Not_Opened
class Error_FrameIO
class Error_Frame_Vector_Unexpected_id
class Error_Frame_Frame_Unexpected_id
class Error_Frame_Rotation_Unexpected_id
class Error_ChainIO
class Error_Chain_Unexpected_id
class Error_RedundancyIO
Error_Redundancy indicates an error that occured during solving for redundancy.
class Error_Redundancy_Illegal_Resolutiontype
class Error_Redundancy
class Error_Redundancy_Unavoidable
class Error_Redundancy_Low_Manip
class Error_MotionIO
class Error_MotionIO_Unexpected_MotProf
class Error_MotionIO_Unexpected_Traj
class Error_MotionPlanning
class Error_MotionPlanning_Circle_ToSmall
class Error_MotionPlanning_Circle_No_Plane
class Error_MotionPlanning_Incompatible
class Error_MotionPlanning_Not_Feasible
class Error_MotionPlanning_Not_Applicable
class Error_Integrator
Abstract subclass of all errors that can be thrown by Adaptive_Integrator.
class Error_Stepsize_Underflow
Error_Stepsize_Underflow is thrown if the stepsize becomes to small.
class Error_To_Many_Steps
class Error_Stepsize_To_Small
Error_Stepsize_To_Small is thrown if the stepsize becomes to small.
class Error_Criterium
class Error_Criterium_Unexpected_id
class Error_Limits
class Error_Limits_Unexpected_id
class Error_Not_Implemented
class Rall1d
class Rall2d
class TI
class TI< double >
class TI< int >
Typedefs
typedef Rall2d< double, double,
double > doubleAcc
typedef Rall1d< double > doubleVel
typedef std::map< std::string,
TreeElement, std::less
< std::string >
, Eigen::aligned_allocator
< std::pair< std::string,
TreeElement > > > SegmentMap
typedef std::stack< std::string > ErrorStack
Functions
VectorAcc operator+ (const VectorAcc &r1, const VectorAcc &r2)
VectorAcc operator- (const VectorAcc &r1, const VectorAcc &r2)
VectorAcc operator+ (const Vector &r1, const VectorAcc &r2)
VectorAcc operator- (const Vector &r1, const VectorAcc &r2)
VectorAcc operator+ (const VectorAcc &r1, const Vector &r2)
VectorAcc operator- (const VectorAcc &r1, const Vector &r2)
VectorAcc operator- (const VectorAcc &r)
VectorAcc operator* (const VectorAcc &r1, const VectorAcc &r2)
VectorAcc operator* (const VectorAcc &r1, const Vector &r2)
VectorAcc operator* (const Vector &r1, const VectorAcc &r2)
VectorAcc operator* (double r1, const VectorAcc &r2)
VectorAcc operator* (const VectorAcc &r1, double r2)
VectorAcc operator* (const doubleAcc &r1, const VectorAcc &r2)
VectorAcc operator* (const VectorAcc &r2, const doubleAcc &r1)
doubleAcc dot (const VectorAcc &lhs, const VectorAcc &rhs)
doubleAcc dot (const VectorAcc &lhs, const Vector &rhs)
doubleAcc dot (const Vector &lhs, const VectorAcc &rhs)
bool Equal (const VectorAcc &r1, const VectorAcc &r2, double eps)
bool Equal (const Vector &r1, const VectorAcc &r2, double eps)
bool Equal (const VectorAcc &r1, const Vector &r2, double eps)
VectorAcc operator/ (const VectorAcc &r1, double r2)
VectorAcc operator/ (const VectorAcc &r2, const doubleAcc &r1)
RotationAcc operator* (const RotationAcc &r1, const RotationAcc &r2)
RotationAcc operator* (const Rotation &r1, const RotationAcc &r2)
RotationAcc operator* (const RotationAcc &r1, const Rotation &r2)
VectorAcc operator* (const Rotation &R, const VectorAcc &x)
bool Equal (const RotationAcc &r1, const RotationAcc &r2, double eps)
bool Equal (const Rotation &r1, const RotationAcc &r2, double eps)
bool Equal (const RotationAcc &r1, const Rotation &r2, double eps)
FrameAcc operator* (const FrameAcc &lhs, const FrameAcc &rhs)
FrameAcc operator* (const FrameAcc &lhs, const Frame &rhs)
FrameAcc operator* (const Frame &lhs, const FrameAcc &rhs)
bool Equal (const FrameAcc &r1, const FrameAcc &r2, double eps)
bool Equal (const Frame &r1, const FrameAcc &r2, double eps)
bool Equal (const FrameAcc &r1, const Frame &r2, double eps)
TwistAcc operator* (const TwistAcc &lhs, double rhs)
TwistAcc operator* (double lhs, const TwistAcc &rhs)
TwistAcc operator/ (const TwistAcc &lhs, double rhs)
TwistAcc operator* (const TwistAcc &lhs, const doubleAcc &rhs)
TwistAcc operator* (const doubleAcc &lhs, const TwistAcc &rhs)
TwistAcc operator/ (const TwistAcc &lhs, const doubleAcc &rhs)
TwistAcc operator+ (const TwistAcc &lhs, const TwistAcc &rhs)
TwistAcc operator- (const TwistAcc &lhs, const TwistAcc &rhs)
TwistAcc operator- (const TwistAcc &arg)
bool Equal (const TwistAcc &a, const TwistAcc &b, double eps)
bool Equal (const Twist &a, const TwistAcc &b, double eps)
bool Equal (const TwistAcc &a, const Twist &b, double eps)
bool Equal (const Rotation &a, const Rotation &b, double eps)
Rotation operator* (const Rotation &lhs, const Rotation &rhs)
bool operator== (const Rotation &a, const Rotation &b)
IMETHOD Vector diff (const Vector &a, const Vector &b, double dt=1)
IMETHOD Vector diff (const Rotation &R_a_b1, const Rotation &R_a_b2, double dt=1)
IMETHOD Twist diff (const Frame &F_a_b1, const Frame &F_a_b2, double dt=1)
IMETHOD Twist diff (const Twist &a, const Twist &b, double dt=1)
IMETHOD Wrench diff (const Wrench &W_a_p1, const Wrench &W_a_p2, double dt=1)
IMETHOD Vector addDelta (const Vector &a, const Vector &da, double dt=1)
IMETHOD Rotation addDelta (const Rotation &a, const Vector &da, double dt=1)
IMETHOD Frame addDelta (const Frame &a, const Twist &da, double dt=1)
IMETHOD Twist addDelta (const Twist &a, const Twist &da, double dt=1)
IMETHOD Wrench addDelta (const Wrench &a, const Wrench &da, double dt=1)
std::ostream & operator<< (std::ostream &os, const Vector &v)
std::ostream & operator<< (std::ostream &os, const Twist &v)
std::ostream & operator<< (std::ostream &os, const Wrench &v)
std::ostream & operator<< (std::ostream &os, const Rotation &R)
std::ostream & operator<< (std::ostream &os, const Frame &T)
std::ostream & operator<< (std::ostream &os, const Vector2 &v)
std::ostream & operator<< (std::ostream &os, const Rotation2 &R)
std::ostream & operator<< (std::ostream &os, const Frame2 &T)
std::istream & operator>> (std::istream &is, Vector &v)
std::istream & operator>> (std::istream &is, Twist &v)
std::istream & operator>> (std::istream &is, Wrench &v)
std::istream & operator>> (std::istream &is, Rotation &r)
std::istream & operator>> (std::istream &is, Frame &T)
std::istream & operator>> (std::istream &is, Vector2 &v)
std::istream & operator>> (std::istream &is, Rotation2 &r)
std::istream & operator>> (std::istream &is, Frame2 &T)
IMETHOD doubleVel diff (const doubleVel &a, const doubleVel &b, double dt=1.0)
IMETHOD doubleVel addDelta (const doubleVel &a, const doubleVel &da, double dt=1.0)
IMETHOD void random (doubleVel &F)
IMETHOD void posrandom (doubleVel &F)
IMETHOD VectorVel diff (const VectorVel &a, const VectorVel &b, double dt=1.0)
IMETHOD VectorVel addDelta (const VectorVel &a, const VectorVel &da, double dt=1.0)
IMETHOD VectorVel diff (const RotationVel &a, const RotationVel &b, double dt=1.0)
IMETHOD RotationVel addDelta (const RotationVel &a, const VectorVel &da, double dt=1.0)
IMETHOD TwistVel diff (const FrameVel &a, const FrameVel &b, double dt=1.0)
IMETHOD FrameVel addDelta (const FrameVel &a, const TwistVel &da, double dt=1.0)
IMETHOD void random (VectorVel &a)
IMETHOD void random (TwistVel &a)
IMETHOD void random (RotationVel &R)
IMETHOD void random (FrameVel &F)
IMETHOD void posrandom (VectorVel &a)
IMETHOD void posrandom (TwistVel &a)
IMETHOD void posrandom (RotationVel &R)
IMETHOD void posrandom (FrameVel &F)
FrameVel operator* (const FrameVel &lhs, const FrameVel &rhs)
FrameVel operator* (const FrameVel &lhs, const Frame &rhs)
FrameVel operator* (const Frame &lhs, const FrameVel &rhs)
bool Equal (const FrameVel &r1, const FrameVel &r2, double eps)
bool Equal (const Frame &r1, const FrameVel &r2, double eps)
bool Equal (const FrameVel &r1, const Frame &r2, double eps)
RotationVel operator* (const RotationVel &r1, const RotationVel &r2)
RotationVel operator* (const Rotation &r1, const RotationVel &r2)
RotationVel operator* (const RotationVel &r1, const Rotation &r2)
VectorVel operator+ (const VectorVel &r1, const VectorVel &r2)
VectorVel operator- (const VectorVel &r1, const VectorVel &r2)
VectorVel operator+ (const VectorVel &r1, const Vector &r2)
VectorVel operator- (const VectorVel &r1, const Vector &r2)
VectorVel operator+ (const Vector &r1, const VectorVel &r2)
VectorVel operator- (const Vector &r1, const VectorVel &r2)
VectorVel operator- (const VectorVel &r)
void SetToZero (VectorVel &v)
VectorVel operator* (const VectorVel &r1, const VectorVel &r2)
VectorVel operator* (const VectorVel &r1, const Vector &r2)
VectorVel operator* (const Vector &r1, const VectorVel &r2)
VectorVel operator* (double r1, const VectorVel &r2)
VectorVel operator* (const VectorVel &r1, double r2)
VectorVel operator* (const doubleVel &r1, const VectorVel &r2)
VectorVel operator* (const VectorVel &r2, const doubleVel &r1)
VectorVel operator/ (const VectorVel &r1, double r2)
VectorVel operator/ (const VectorVel &r2, const doubleVel &r1)
VectorVel operator* (const Rotation &R, const VectorVel &x)
bool Equal (const VectorVel &r1, const VectorVel &r2, double eps)
bool Equal (const Vector &r1, const VectorVel &r2, double eps)
bool Equal (const VectorVel &r1, const Vector &r2, double eps)
bool Equal (const RotationVel &r1, const RotationVel &r2, double eps)
bool Equal (const Rotation &r1, const RotationVel &r2, double eps)
bool Equal (const RotationVel &r1, const Rotation &r2, double eps)
bool Equal (const TwistVel &a, const TwistVel &b, double eps)
bool Equal (const Twist &a, const TwistVel &b, double eps)
bool Equal (const TwistVel &a, const Twist &b, double eps)
IMETHOD doubleVel dot (const VectorVel &lhs, const VectorVel &rhs)
IMETHOD doubleVel dot (const VectorVel &lhs, const Vector &rhs)
IMETHOD doubleVel dot (const Vector &lhs, const VectorVel &rhs)
TwistVel operator* (const TwistVel &lhs, double rhs)
TwistVel operator* (double lhs, const TwistVel &rhs)
TwistVel operator/ (const TwistVel &lhs, double rhs)
TwistVel operator* (const TwistVel &lhs, const doubleVel &rhs)
TwistVel operator* (const doubleVel &lhs, const TwistVel &rhs)
TwistVel operator/ (const TwistVel &lhs, const doubleVel &rhs)
TwistVel operator+ (const TwistVel &lhs, const TwistVel &rhs)
TwistVel operator- (const TwistVel &lhs, const TwistVel &rhs)
TwistVel operator- (const TwistVel &arg)
void SetToZero (TwistVel &v)
void SetToZero (Jacobian &jac)
void changeRefPoint (const Jacobian &src1, const Vector &base_AB, Jacobian &dest)
void changeBase (const Jacobian &src1, const Rotation &rot, Jacobian &dest)
void changeRefFrame (const Jacobian &src1, const Frame &frame, Jacobian &dest)
bool Equal (const Jacobian &a, const Jacobian &b, double eps)
void Add (const JntArray &src1, const JntArray &src2, JntArray &dest)
void Subtract (const JntArray &src1, const JntArray &src2, JntArray &dest)
void Multiply (const JntArray &src, const double &factor, JntArray &dest)
void Divide (const JntArray &src, const double &factor, JntArray &dest)
void MultiplyJacobian (const Jacobian &jac, const JntArray &src, Twist &dest)
void SetToZero (JntArray &array)
bool Equal (const JntArray &src1, const JntArray &src2, double eps)
bool operator== (const JntArray &src1, const JntArray &src2)
void Add (const JntArrayAcc &src1, const JntArrayAcc &src2, JntArrayAcc &dest)
void Add (const JntArrayAcc &src1, const JntArrayVel &src2, JntArrayAcc &dest)
void Add (const JntArrayAcc &src1, const JntArray &src2, JntArrayAcc &dest)
void Subtract (const JntArrayAcc &src1, const JntArrayAcc &src2, JntArrayAcc &dest)
void Subtract (const JntArrayAcc &src1, const JntArrayVel &src2, JntArrayAcc &dest)
void Subtract (const JntArrayAcc &src1, const JntArray &src2, JntArrayAcc &dest)
void Multiply (const JntArrayAcc &src, const double &factor, JntArrayAcc &dest)
void Multiply (const JntArrayAcc &src, const doubleVel &factor, JntArrayAcc &dest)
void Multiply (const JntArrayAcc &src, const doubleAcc &factor, JntArrayAcc &dest)
void Divide (const JntArrayAcc &src, const double &factor, JntArrayAcc &dest)
void Divide (const JntArrayAcc &src, const doubleVel &factor, JntArrayAcc &dest)
void Divide (const JntArrayAcc &src, const doubleAcc &factor, JntArrayAcc &dest)
void SetToZero (JntArrayAcc &array)
bool Equal (const JntArrayAcc &src1, const JntArrayAcc &src2, double eps)
void Add (const JntArrayVel &src1, const JntArrayVel &src2, JntArrayVel &dest)
void Add (const JntArrayVel &src1, const JntArray &src2, JntArrayVel &dest)
void Subtract (const JntArrayVel &src1, const JntArrayVel &src2, JntArrayVel &dest)
void Subtract (const JntArrayVel &src1, const JntArray &src2, JntArrayVel &dest)
void Multiply (const JntArrayVel &src, const double &factor, JntArrayVel &dest)
void Multiply (const JntArrayVel &src, const doubleVel &factor, JntArrayVel &dest)
void Divide (const JntArrayVel &src, const double &factor, JntArrayVel &dest)
void Divide (const JntArrayVel &src, const doubleVel &factor, JntArrayVel &dest)
void SetToZero (JntArrayVel &array)
bool Equal (const JntArrayVel &src1, const JntArrayVel &src2, double eps)
std::ostream & operator<< (std::ostream &os, const Joint &joint)
std::istream & operator>> (std::istream &is, Joint &joint)
std::ostream & operator<< (std::ostream &os, const Segment &segment)
std::istream & operator>> (std::istream &is, Segment &segment)
std::ostream & operator<< (std::ostream &os, const Chain &chain)
std::istream & operator>> (std::istream &is, Chain &chain)
std::ostream & operator<< (std::ostream &os, const Tree &tree)
std::ostream & operator<< (std::ostream &os, SegmentMap::const_iterator root)
std::istream & operator>> (std::istream &is, Tree &tree)
std::ostream & operator<< (std::ostream &os, const JntArray &array)
std::istream & operator>> (std::istream &is, JntArray &array)
std::ostream & operator<< (std::ostream &os, const Jacobian &jac)
std::istream & operator>> (std::istream &is, Jacobian &jac)
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::vector< T > &vec)
template<typename T >
std::istream & operator>> (std::istream &is, std::vector< T > &vec)
void IOTrace (const std::string &description)
void IOTracePop ()
pops a description of the IO-stack
void IOTraceOutput (std::ostream &os)
outputs the IO-stack to a stream to provide a better errormessage.
void IOTracePopStr (char *buffer, int size)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > operator/ (const Rall1d< T, V, S > &lhs, const Rall1d< T, V, S > &rhs)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > operator* (const Rall1d< T, V, S > &lhs, const Rall1d< T, V, S > &rhs)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > operator+ (const Rall1d< T, V, S > &lhs, const Rall1d< T, V, S > &rhs)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > operator- (const Rall1d< T, V, S > &lhs, const Rall1d< T, V, S > &rhs)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > operator- (const Rall1d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > operator* (S s, const Rall1d< T, V, S > &v)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > operator* (const Rall1d< T, V, S > &v, S s)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > operator+ (S s, const Rall1d< T, V, S > &v)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > operator+ (const Rall1d< T, V, S > &v, S s)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > operator- (S s, const Rall1d< T, V, S > &v)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > operator- (const Rall1d< T, V, S > &v, S s)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > operator/ (S s, const Rall1d< T, V, S > &v)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > operator/ (const Rall1d< T, V, S > &v, S s)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > exp (const Rall1d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > log (const Rall1d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > sin (const Rall1d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > cos (const Rall1d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > tan (const Rall1d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > sinh (const Rall1d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > cosh (const Rall1d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > sqr (const Rall1d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > pow (const Rall1d< T, V, S > &arg, double m)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > sqrt (const Rall1d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > atan (const Rall1d< T, V, S > &x)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > hypot (const Rall1d< T, V, S > &y, const Rall1d< T, V, S > &x)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > asin (const Rall1d< T, V, S > &x)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > acos (const Rall1d< T, V, S > &x)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > abs (const Rall1d< T, V, S > &x)
template<class T , class V , class S >
INLINE S Norm (const Rall1d< T, V, S > &value)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > tanh (const Rall1d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > atan2 (const Rall1d< T, V, S > &y, const Rall1d< T, V, S > &x)
template<class T , class V , class S >
INLINE Rall1d< T, V, S > LinComb (S alfa, const Rall1d< T, V, S > &a, const T &beta, const Rall1d< T, V, S > &b)
template<class T , class V , class S >
INLINE void LinCombR (S alfa, const Rall1d< T, V, S > &a, const T &beta, const Rall1d< T, V, S > &b, Rall1d< T, V, S > &result)
template<class T , class V , class S >
INLINE void SetToZero (Rall1d< T, V, S > &value)
template<class T , class V , class S >
INLINE void SetToIdentity (Rall1d< T, V, S > &value)
template<class T , class V , class S >
INLINE bool Equal (const Rall1d< T, V, S > &y, const Rall1d< T, V, S > &x, double eps=epsilon)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > operator/ (const Rall2d< T, V, S > &lhs, const Rall2d< T, V, S > &rhs)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > operator* (const Rall2d< T, V, S > &lhs, const Rall2d< T, V, S > &rhs)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > operator+ (const Rall2d< T, V, S > &lhs, const Rall2d< T, V, S > &rhs)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > operator- (const Rall2d< T, V, S > &lhs, const Rall2d< T, V, S > &rhs)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > operator- (const Rall2d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > operator* (S s, const Rall2d< T, V, S > &v)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > operator* (const Rall2d< T, V, S > &v, S s)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > operator+ (S s, const Rall2d< T, V, S > &v)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > operator+ (const Rall2d< T, V, S > &v, S s)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > operator- (S s, const Rall2d< T, V, S > &v)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > operator- (const Rall2d< T, V, S > &v, S s)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > operator/ (S s, const Rall2d< T, V, S > &rhs)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > operator/ (const Rall2d< T, V, S > &v, S s)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > exp (const Rall2d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > log (const Rall2d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > sin (const Rall2d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > cos (const Rall2d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > tan (const Rall2d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > sinh (const Rall2d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > cosh (const Rall2d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > tanh (const Rall2d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > sqr (const Rall2d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > pow (const Rall2d< T, V, S > &arg, double m)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > sqrt (const Rall2d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > asin (const Rall2d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > acos (const Rall2d< T, V, S > &arg)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > atan (const Rall2d< T, V, S > &x)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > atan2 (const Rall2d< T, V, S > &y, const Rall2d< T, V, S > &x)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > abs (const Rall2d< T, V, S > &x)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > hypot (const Rall2d< T, V, S > &y, const Rall2d< T, V, S > &x)
template<class T , class V , class S >
INLINE S Norm (const Rall2d< T, V, S > &value)
template<class T , class V , class S >
INLINE Rall2d< T, V, S > LinComb (S alfa, const Rall2d< T, V, S > &a, const T &beta, const Rall2d< T, V, S > &b)
template<class T , class V , class S >
INLINE void LinCombR (S alfa, const Rall2d< T, V, S > &a, const T &beta, const Rall2d< T, V, S > &b, Rall2d< T, V, S > &result)
template<class T , class V , class S >
INLINE void SetToZero (Rall2d< T, V, S > &value)
template<class T , class V , class S >
INLINE void SetToIdentity (Rall2d< T, V, S > &value)
template<class T , class V , class S >
INLINE bool Equal (const Rall2d< T, V, S > &y, const Rall2d< T, V, S > &x, double eps=epsilon)
template<typename Scalar >
Scalar PYTHAG (Scalar a, Scalar b)
template<typename Scalar >
Scalar SIGN (Scalar a, Scalar b)
template<typename MatrixA , typename MatrixUV , typename VectorS >
int svd_eigen_HH (const Eigen::MatrixBase< MatrixA > &A, Eigen::MatrixBase< MatrixUV > &U, Eigen::MatrixBase< VectorS > &S, Eigen::MatrixBase< MatrixUV > &V, Eigen::MatrixBase< VectorS > &tmp, int maxiter=150)
double sin (double a)
double cos (double a)
double exp (double a)
double log (double a)
double tan (double a)
double cosh (double a)
double sinh (double a)
double sqrt (double a)
double atan (double a)
double acos (double a)
double asin (double a)
double tanh (double a)
double pow (double a, double b)
double atan2 (double a, double b)
double max (double a, double b)
double min (double a, double b)
double LinComb (double alfa, double a, double beta, double b)
void LinCombR (double alfa, double a, double beta, double b, double &result)
void SetToZero (double &arg)
to uniformly set double, RNDouble,Vector,... objects to zero in template-classes
void SetToIdentity (double &arg)
to uniformly set double, RNDouble,Vector,... objects to the identity element in template-classes
double sign (double arg)
double sqr (double arg)
double Norm (double arg)
bool Equal (double a, double b, double eps=epsilon)
void random (double &a)
void posrandom (double &a)
double diff (double a, double b, double dt)
double addDelta (double a, double da, double dt)
void _check_istream (std::istream &is)
int _EatUntilEndOfLine (std::istream &is, int *countp=NULL)
int _EatUntilEndOfComment (std::istream &is, int *countp=NULL)
int _EatSpace (std::istream &is, int *countp=NULL)
void Eat (std::istream &is, int delim)
void EatEnd (std::istream &is, int delim)
char Upper (char ch)
void Eat (std::istream &is, const char *descript)
void EatWord (std::istream &is, const char *delim, char *storage, int maxsize)
Variables
ErrorStack errorstack
int STREAMBUFFERSIZE = 10000
int MAXLENFILENAME = 255
maximal length of a file name
const double PI = 3.1415926535897932384626433832795
the value of pi
const double deg2rad = 0.01745329251994329576923690768488
the value pi/180
const double rad2deg = 57.2957795130823208767981548141052
the value 180/pi
double epsilon = 0.000001
default precision while comparing with Equal(..,..) functions. Initialized at 0.0000001.
double epsilon2 = 0.000001*0.000001
power or 2 of epsilon
int VSIZE
the number of derivatives used in the RN-... objects.
Typedef Documentation
typedef Rall2d<double,double,double> KDL::doubleAcc
Definition at line 39 of file frameacc.hpp.
typedef Rall1d<double> KDL::doubleVel
Definition at line 35 of file framevel.hpp.
typedef std::stack<std::string> KDL::ErrorStack
Definition at line 29 of file error_stack.cpp.
typedef std::map<std::string,TreeElement, std::less<std::string>, Eigen::aligned_allocator<std::pair<std::string, TreeElement> > > KDL::SegmentMap
Definition at line 37 of file tree.hpp.
Function Documentation
void KDL::_check_istream (std::istream & is)
checks validity of basic io of is
Definition at line 34 of file utility_io.cpp.
Referenced by _EatSpace(), _EatUntilEndOfComment(), _EatUntilEndOfLine(), and EatWord().
int KDL::_EatSpace (std::istream & is, int * countp = NULL)
Definition at line 78 of file utility_io.cpp.
References _check_istream(), _EatUntilEndOfComment(), _EatUntilEndOfLine(), and NULL.
Referenced by Eat(), EatEnd(), and EatWord().
int KDL::_EatUntilEndOfComment (std::istream & is, int * countp = NULL)
Definition at line 56 of file utility_io.cpp.
References _check_istream(), and NULL.
Referenced by _EatSpace().
int KDL::_EatUntilEndOfLine (std::istream & is, int * countp = NULL)
Definition at line 42 of file utility_io.cpp.
References _check_istream(), and NULL.
Referenced by _EatSpace().
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::abs (const Rall1d< T, V, S > & x)
Definition at line 408 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, Sign(), and T.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::abs (const Rall2d< T, V, S > & x)
Definition at line 464 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, Sign(), and T.
double KDL::acos (double a) [inline]
Definition at line 112 of file utility.h.
References acos().
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::acos (const Rall2d< T, V, S > & arg)
Definition at line 428 of file rall2d.h.
References acos(), KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, sin(), sqr(), T, and KDL::Rall2d< T, V, S >::t.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::acos (const Rall1d< T, V, S > & x)
Definition at line 400 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, sqr(), sqrt(), T, and KDL::Rall1d< T, V, S >::t.
Referenced by acos(), KDL::Rotation::GetRotAngle(), and KDL::Rotation::GetXZRot().
void KDL::Add (const JntArrayAcc & src1, const JntArrayVel & src2, JntArrayAcc & dest)
Definition at line 68 of file jntarrayacc.cpp.
References Add(), KDL::JntArrayAcc::q, KDL::JntArrayVel::q, KDL::JntArrayAcc::qdot, KDL::JntArrayVel::qdot, and KDL::JntArrayAcc::qdotdot.
void KDL::Add (const JntArrayAcc & src1, const JntArrayAcc & src2, JntArrayAcc & dest)
Definition at line 62 of file jntarrayacc.cpp.
References Add(), KDL::JntArrayAcc::q, KDL::JntArrayAcc::qdot, and KDL::JntArrayAcc::qdotdot.
void KDL::Add (const JntArrayAcc & src1, const JntArray & src2, JntArrayAcc & dest)
Definition at line 74 of file jntarrayacc.cpp.
References Add(), KDL::JntArrayAcc::q, KDL::JntArrayAcc::qdot, and KDL::JntArrayAcc::qdotdot.
void KDL::Add (const JntArrayVel & src1, const JntArrayVel & src2, JntArrayVel & dest)
Definition at line 54 of file jntarrayvel.cpp.
References Add(), KDL::JntArrayVel::q, and KDL::JntArrayVel::qdot.
void KDL::Add (const JntArrayVel & src1, const JntArray & src2, JntArrayVel & dest)
Definition at line 59 of file jntarrayvel.cpp.
References Add(), KDL::JntArrayVel::q, and KDL::JntArrayVel::qdot.
void KDL::Add (const JntArray & src1, const JntArray & src2, JntArray & dest)
Function to add two joint arrays, all the arguments must have the same size: A + B = C. This function is aliasing-safe, A or B can be the same array as C.
Parameters:
src1 A
src2 B
dest C
Definition at line 98 of file jntarray.cpp.
References assert, and i.
Referenced by Add(), Divide(), and Multiply().
double KDL::addDelta (double a, double da, double dt) [inline]
Definition at line 285 of file utility.h.
IMETHOD Vector KDL::addDelta (const Vector & a, const Vector & da, double dt = 1)
Referenced by addDelta(), and addDelta().
IMETHOD doubleVel KDL::addDelta (const doubleVel & a, const doubleVel & da, double dt = 1.0)
Definition at line 41 of file framevel.hpp.
IMETHOD VectorVel KDL::addDelta (const VectorVel & a, const VectorVel & da, double dt = 1.0)
Definition at line 312 of file framevel.hpp.
References addDelta(), KDL::VectorVel::p, and KDL::VectorVel::v.
IMETHOD FrameVel KDL::addDelta (const FrameVel & a, const TwistVel & da, double dt = 1.0)
Definition at line 327 of file framevel.hpp.
IMETHOD RotationVel KDL::addDelta (const RotationVel & a, const VectorVel & da, double dt = 1.0)
Definition at line 319 of file framevel.hpp.
References addDelta(), KDL::VectorVel::p, KDL::RotationVel::R, KDL::VectorVel::v, and KDL::RotationVel::w.
IMETHOD Rotation KDL::addDelta (const Rotation & a, const Vector & da, double dt = 1)
IMETHOD Frame KDL::addDelta (const Frame & a, const Twist & da, double dt = 1)
IMETHOD Twist KDL::addDelta (const Twist & a, const Twist & da, double dt = 1)
IMETHOD Wrench KDL::addDelta (const Wrench & a, const Wrench & da, double dt = 1)
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::asin (const Rall2d< T, V, S > & arg)
Definition at line 416 of file rall2d.h.
References asin(), cos(), KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, sqr(), T, and KDL::Rall2d< T, V, S >::t.
double KDL::asin (double a) [inline]
Definition at line 115 of file utility.h.
References asin().
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::asin (const Rall1d< T, V, S > & x)
Definition at line 392 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, sqr(), sqrt(), T, and KDL::Rall1d< T, V, S >::t.
Referenced by asin(), check_zone(), MeanValueMeshCoords::computeWeights(), ntlMatrix4x4< Scalar >::decompose(), do_math(), KX_Dome::FlattenPanorama(), MT_Matrix3x3::getEuler(), node_shader_exec_math(), saasin(), and valuefn().
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::atan (const Rall2d< T, V, S > & x)
Definition at line 441 of file rall2d.h.
References atan(), KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, sqr(), T, and KDL::Rall2d< T, V, S >::t.
double KDL::atan (double a) [inline]
Definition at line 109 of file utility.h.
References atan().
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::atan (const Rall1d< T, V, S > & x)
Definition at line 376 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, sqr(), T, and KDL::Rall1d< T, V, S >::t.
Referenced by atan(), blender_camera_sync(), do_math(), node_shader_exec_math(), panorama_pixel_rot(), speedvector_project(), and valuefn().
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::atan2 (const Rall2d< T, V, S > & y, const Rall2d< T, V, S > & x)
Definition at line 453 of file rall2d.h.
References atan2(), KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, sqr(), T, and KDL::Rall2d< T, V, S >::t.
double KDL::atan2 (double a, double b) [inline]
Definition at line 124 of file utility.h.
References atan2().
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::atan2 (const Rall1d< T, V, S > & y, const Rall1d< T, V, S > & x)
Definition at line 430 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, KDL::Rall1d< T, V, S >::t, and T.
Referenced by atan2(), b_bone_spline_setup(), BKE_text_to_curve(), blend(), calculate_stabdata(), ComputeTwist(), ntlMatrix4x4< Scalar >::decompose(), DirectionToThetaPhi(), do_chroma_key(), EulerAngleFromMatrix(), fix_bonelist_roll(), KX_Dome::FlattenDome(), KX_Dome::FlattenPanorama(), MT_Matrix3x3::getEuler(), KDL::Rotation::GetEulerZYZ(), KDL::Rotation2::GetRot(), KDL::Rotation::GetRot(), KDL::Rotation::GetRPY(), join_armature_exec(), map_to_tube(), mat3_to_eul2(), mat3_to_eulo2(), mat3_to_quat_is_ok(), mat3_to_vec_roll(), Mat3ToEulOld(), paint_draw_cursor(), radial_control_modal(), RE_inithalo(), RE_inithalo_particle(), RotationBetween(), KX_ObstacleSimulationTOI_rays::sampleRVO(), sculpt_update_cache_variants(), MT_ExpMap::setRotation(), shadeHaloFloat(), svm_gradient(), tri_to_quat(), and vec_to_quat().
void KDL::changeBase (const Jacobian & src1, const Rotation & rot, Jacobian & dest)
Definition at line 95 of file jacobian.cpp.
References assert, i, and KDL::Jacobian::twists.
Referenced by KDL::ChainJntToJacSolver::JntToJac(), and KDL::TreeJntToJacSolver::JntToJac().
void KDL::changeRefFrame (const Jacobian & src1, const Frame & frame, Jacobian & dest)
Definition at line 103 of file jacobian.cpp.
References assert, i, and KDL::Jacobian::twists.
void KDL::changeRefPoint (const Jacobian & src1, const Vector & base_AB, Jacobian & dest)
Definition at line 87 of file jacobian.cpp.
References assert, i, KDL::Twist::RefPoint(), and KDL::Jacobian::twists.
Referenced by iTaSC::Armature::updateJacobian(), and iTaSC::Distance::updateJacobian().
double KDL::cos (double a) [inline]
Definition at line 88 of file utility.h.
References cos().
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::cos (const Rall1d< T, V, S > & arg)
Definition at line 320 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, sin(), KDL::Rall1d< T, V, S >::t, and T.
Referenced by asin(), base_callback(), cos(), KDL::Frame::DH(), KDL::Frame::DH_Craig1989(), KDL::RotationVel::DoRotX(), KDL::RotationVel::DoRotY(), KDL::RotationVel::DoRotZ(), KDL::Rotation::EulerZYZ(), Rot(), KDL::RotationVel::Rot(), KDL::Rotation::Rot(), KDL::Rotation::Rot2(), KDL::RotationVel::RotX(), KDL::RotationVel::RotY(), KDL::RotationVel::RotZ(), KDL::Rotation::RPY(), KDL::Rotation2::SetRot(), sin(), and tan().
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::cos (const Rall2d< T, V, S > & arg)
Definition at line 345 of file rall2d.h.
References cos(), KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, sin(), KDL::Rall2d< T, V, S >::t, and T.
double KDL::cosh (double a) [inline]
Definition at line 100 of file utility.h.
References cosh().
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::cosh (const Rall1d< T, V, S > & arg)
Definition at line 344 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, sinh(), T, and KDL::Rall1d< T, V, S >::t.
Referenced by cosh(), sinh(), and tanh().
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::cosh (const Rall2d< T, V, S > & arg)
Definition at line 369 of file rall2d.h.
References cosh(), KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, sinh(), T, and KDL::Rall2d< T, V, S >::t.
IMETHOD doubleVel KDL::diff (const doubleVel & a, const doubleVel & b, double dt = 1.0)
Definition at line 37 of file framevel.hpp.
double KDL::diff (double a, double b, double dt) [inline]
Definition at line 279 of file utility.h.
IMETHOD VectorVel KDL::diff (const RotationVel & a, const RotationVel & b, double dt = 1.0)
Definition at line 315 of file framevel.hpp.
References diff(), KDL::RotationVel::R, and KDL::RotationVel::w.
IMETHOD TwistVel KDL::diff (const FrameVel & a, const FrameVel & b, double dt = 1.0)
Definition at line 323 of file framevel.hpp.
IMETHOD VectorVel KDL::diff (const VectorVel & a, const VectorVel & b, double dt = 1.0)
Definition at line 308 of file framevel.hpp.
References diff(), KDL::VectorVel::p, and KDL::VectorVel::v.
IMETHOD Twist KDL::diff (const Twist & a, const Twist & b, double dt = 1)
IMETHOD Wrench KDL::diff (const Wrench & W_a_p1, const Wrench & W_a_p2, double dt = 1)
IMETHOD Twist KDL::diff (const Frame & F_a_b1, const Frame & F_a_b2, double dt = 1)
IMETHOD Vector KDL::diff (const Vector & a, const Vector & b, double dt = 1)
Referenced by iTaSC::ConstraintSet::closeLoop(), closestPtPtSeg(), GIM_AABB::collide_triangle_exact(), cullPoints2(), diff(), diff(), Equal(), EXPP_FloatsAreEqual(), btQuaternion::farthest(), fcm_envelope_evaluate(), fix_connected_bone(), iTaSC::CopyPose::getControlParameters(), iTaSC::Armature::getMaxEndEffectorChange(), GPU_enable_material(), GPU_update_image_time(), HC_relaxation_iteration_uv(), laplacian_relaxation_iteration_uv(), measure_facepair(), mirror_bezier_cframe(), mirror_bezier_marker(), mirror_bezier_value(), mirror_bezier_xaxis(), mirror_bezier_yaxis(), multiple_scattering_diffusion(), btQuaternion::nearest(), nearest_point_in_tri_surface(), p_smooth(), btSphereSphereCollisionAlgorithm::processCollision(), ray_trace(), SegmentSqrDistance(), ui_draw_but_NORMAL(), UI_view2d_curRect_validate_resize(), GHOST_NDOFManager::updateButtons(), btVoronoiSimplexSolver::updateClosestVectorAndPoints(), iTaSC::CopyPose::updateControlOutput(), iTaSC::MovingFrame::updateCoordinates(), uv_sculpt_stroke_apply(), uv_sculpt_stroke_init(), and viewAxisCorrectCenter().
IMETHOD Vector KDL::diff (const Rotation & R_a_b1, const Rotation & R_a_b2, double dt = 1)
void KDL::Divide (const JntArray & src, const double & factor, JntArray & dest)
Function to divide all the array values with a scalar factor: A/b=C. This function is aliasing-safe, A can be the same array as C.
Parameters:
src A
factor b
dest C
Definition at line 119 of file jntarray.cpp.
References assert, i, and KDL::JntArray::rows().
Referenced by Divide().
void KDL::Divide (const JntArrayAcc & src, const double & factor, JntArrayAcc & dest)
Definition at line 129 of file jntarrayacc.cpp.
References Divide(), KDL::JntArrayAcc::q, KDL::JntArrayAcc::qdot, and KDL::JntArrayAcc::qdotdot.
void KDL::Divide (const JntArrayAcc & src, const doubleVel & factor, JntArrayAcc & dest)
Definition at line 135 of file jntarrayacc.cpp.
References Add(), Divide(), KDL::Rall1d< T, V, S >::grad, Multiply(), KDL::JntArrayAcc::q, KDL::JntArrayAcc::qdot, KDL::JntArrayAcc::qdotdot, Subtract(), and KDL::Rall1d< T, V, S >::t.
void KDL::Divide (const JntArrayAcc & src, const doubleAcc & factor, JntArrayAcc & dest)
Definition at line 147 of file jntarrayacc.cpp.
References Add(), KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, Divide(), Multiply(), KDL::JntArrayAcc::q, KDL::JntArrayAcc::qdot, KDL::JntArrayAcc::qdotdot, Subtract(), and KDL::Rall2d< T, V, S >::t.
void KDL::Divide (const JntArrayVel & src, const double & factor, JntArrayVel & dest)
Definition at line 89 of file jntarrayvel.cpp.
References Divide(), KDL::JntArrayVel::q, and KDL::JntArrayVel::qdot.
void KDL::Divide (const JntArrayVel & src, const doubleVel & factor, JntArrayVel & dest)
Definition at line 94 of file jntarrayvel.cpp.
References Divide(), KDL::Rall1d< T, V, S >::grad, Multiply(), KDL::JntArrayVel::q, KDL::JntArrayVel::qdot, Subtract(), and KDL::Rall1d< T, V, S >::t.
IMETHOD doubleVel KDL::dot (const VectorVel & lhs, const VectorVel & rhs)
Definition at line 357 of file framevel.hpp.
IMETHOD doubleVel KDL::dot (const VectorVel & lhs, const Vector & rhs)
Definition at line 360 of file framevel.hpp.
IMETHOD doubleVel KDL::dot (const Vector & lhs, const VectorVel & rhs)
Definition at line 363 of file framevel.hpp.
doubleAcc KDL::dot (const VectorAcc & lhs, const Vector & rhs)
Definition at line 144 of file frameacc.hpp.
doubleAcc KDL::dot (const Vector & lhs, const VectorAcc & rhs)
Definition at line 151 of file frameacc.hpp.
doubleAcc KDL::dot (const VectorAcc & lhs, const VectorAcc & rhs)
Definition at line 137 of file frameacc.hpp.
Referenced by dot().
void KDL::Eat (std::istream & is, int delim)
Eats characters of the stream until the character delim is encountered
Parameters:
is a stream
delim eat until this character is encountered
Definition at line 110 of file utility_io.cpp.
References _EatSpace().
Referenced by operator>>().
void KDL::Eat (std::istream & is, const char * descript)
Eats characters of the stream as long as they satisfy the description in descript
Parameters:
is a stream
descript description string. A sequence of spaces, tabs, new-lines and comments is regarded as 1 space in the description string.
Definition at line 153 of file utility_io.cpp.
References _EatSpace(), p, and Upper().
void KDL::EatEnd (std::istream & is, int delim)
Eats characters of the stream until the character delim is encountered similar to Eat(is,delim) but spaces at the end are not read.
Parameters:
is a stream
delim eat until this character is encountered
Definition at line 124 of file utility_io.cpp.
References _EatSpace().
Referenced by operator>>().
void KDL::EatWord (std::istream & is, const char * delim, char * storage, int maxsize)
Eats a word of the stream delimited by the letters in delim or space(tabs...)
Parameters:
is a stream
delim a string containing the delimmiting characters
storage for returning the word
maxsize a word can be maximally maxsize-1 long.
Definition at line 184 of file utility_io.cpp.
References _check_istream(), _EatSpace(), NULL, p, and size().
Referenced by operator>>().
bool KDL::Equal (const TwistVel & a, const TwistVel & b, double eps = epsilon)
Definition at line 342 of file framevel.hpp.
bool KDL::Equal (const Twist & a, const TwistVel & b, double eps = epsilon)
Definition at line 346 of file framevel.hpp.
bool KDL::Equal (const TwistVel & a, const Twist & b, double eps = epsilon)
Definition at line 350 of file framevel.hpp.
bool KDL::Equal (const FrameAcc & r1, const FrameAcc & r2, double eps = epsilon)
Definition at line 393 of file frameacc.hpp.
template<class T , class V , class S > INLINE bool KDL::Equal (const Rall2d< T, V, S > & y, const Rall2d< T, V, S > & x, double eps = epsilon)
Definition at line 525 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, Equal(), and KDL::Rall2d< T, V, S >::t.
bool KDL::Equal (const Frame & r1, const FrameAcc & r2, double eps = epsilon)
Definition at line 396 of file frameacc.hpp.
bool KDL::Equal (const FrameAcc & r1, const Frame & r2, double eps = epsilon)
Definition at line 399 of file frameacc.hpp.
bool KDL::Equal (const Jacobian & a, const Jacobian & b, double eps = epsilon)
Definition at line 121 of file jacobian.cpp.
References KDL::Jacobian::columns(), Equal(), i, KDL::Jacobian::rows(), and KDL::Jacobian::twists.
bool KDL::Equal (double a, double b, double eps = epsilon) [inline]
Definition at line 265 of file utility.h.
bool KDL::Equal (const Vector & r1, const VectorAcc & r2, double eps = epsilon)
Definition at line 166 of file frameacc.hpp.
bool KDL::Equal (const JntArray & src1, const JntArray & src2, double eps = epsilon)
Function to check if two arrays are the same with a precision of eps
Parameters:
src1
src2
eps default: epsilon
Returns:
true if each element of src1 is within eps of the same element in src2, or if both src1 and src2 have no data (ie 0==rows())
Definition at line 141 of file jntarray.cpp.
References assert, Equal(), and i.
bool KDL::Equal (const VectorAcc & r1, const VectorAcc & r2, double eps = epsilon)
Definition at line 159 of file frameacc.hpp.
Referenced by iTaSC::ConstraintSet::closeLoop(), iTaSC::Distance::closeLoop(), Equal(), Equal(), operator==(), and operator==().
bool KDL::Equal (const RotationVel & r1, const Rotation & r2, double eps = epsilon)
Definition at line 339 of file framevel.hpp.
bool KDL::Equal (const VectorAcc & r1, const Vector & r2, double eps = epsilon)
Definition at line 173 of file frameacc.hpp.
bool KDL::Equal (const JntArrayAcc & src1, const JntArrayAcc & src2, double eps = epsilon)
Definition at line 167 of file jntarrayacc.cpp.
References Equal(), KDL::JntArrayAcc::q, KDL::JntArrayAcc::qdot, and KDL::JntArrayAcc::qdotdot.
bool KDL::Equal (const TwistAcc & a, const TwistAcc & b, double eps = epsilon)
Definition at line 586 of file frameacc.hpp.
bool KDL::Equal (const JntArrayVel & src1, const JntArrayVel & src2, double eps = epsilon)
Definition at line 108 of file jntarrayvel.cpp.
References Equal(), KDL::JntArrayVel::q, and KDL::JntArrayVel::qdot.
bool KDL::Equal (const Twist & a, const TwistAcc & b, double eps = epsilon)
Definition at line 590 of file frameacc.hpp.
bool KDL::Equal (const TwistAcc & a, const Twist & b, double eps = epsilon)
Definition at line 594 of file frameacc.hpp.
bool KDL::Equal (const Rotation & a, const Rotation & b, double eps = epsilon)
do not use operator == because the definition of Equal(.,.) is slightly different. It compares whether the 2 arguments are equal in an eps-interval
Definition at line 157 of file frames.cpp.
References KDL::Rotation::data, and Equal().
bool KDL::Equal (const FrameVel & r1, const FrameVel & r2, double eps = epsilon)
Definition at line 75 of file framevel.hpp.
bool KDL::Equal (const Frame & r1, const FrameVel & r2, double eps = epsilon)
Definition at line 78 of file framevel.hpp.
bool KDL::Equal (const FrameVel & r1, const Frame & r2, double eps = epsilon)
Definition at line 81 of file framevel.hpp.
bool KDL::Equal (const RotationAcc & r1, const RotationAcc & r2, double eps = epsilon)
Definition at line 323 of file frameacc.hpp.
bool KDL::Equal (const Rotation & r1, const RotationAcc & r2, double eps = epsilon)
Definition at line 326 of file frameacc.hpp.
bool KDL::Equal (const RotationAcc & r1, const Rotation & r2, double eps = epsilon)
Definition at line 330 of file frameacc.hpp.
template<class T , class V , class S > INLINE bool KDL::Equal (const Rall1d< T, V, S > & y, const Rall1d< T, V, S > & x, double eps = epsilon)
Definition at line 468 of file rall1d.h.
References Equal(), KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
bool KDL::Equal (const VectorVel & r1, const VectorVel & r2, double eps = epsilon)
Definition at line 323 of file framevel.hpp.
References diff(), KDL::FrameVel::M, and KDL::FrameVel::p.
bool KDL::Equal (const Vector & r1, const VectorVel & r2, double eps = epsilon)
Definition at line 326 of file framevel.hpp.
bool KDL::Equal (const RotationVel & r1, const RotationVel & r2, double eps = epsilon)
Definition at line 333 of file framevel.hpp.
bool KDL::Equal (const Rotation & r1, const RotationVel & r2, double eps = epsilon)
Definition at line 336 of file framevel.hpp.
bool KDL::Equal (const VectorVel & r1, const Vector & r2, double eps = epsilon)
Definition at line 329 of file framevel.hpp.
double KDL::exp (double a) [inline]
Definition at line 91 of file utility.h.
References exp().
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::exp (const Rall1d< T, V, S > & arg)
Definition at line 296 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, KDL::Rall1d< T, V, S >::t, and T.
Referenced by AtmospherePixleShader(), avgLogLum(), BL_ConvertActuators(), BLI_newname(), Blinn_Spec(), ComputeAttenuatedSunlight(), defocus_blur(), exp(), GetSkyXYZRadiance(), Image_getbuffer(), Image_getImage(), ImageMirror_init(), ImageRender_init(), ImageViewport_setCaptureSize(), ImageViewport_setWhole(), load(), RVBlurBitmap2_byte(), RVBlurBitmap2_float(), sb_detect_face_pointCached(), sb_detect_vertex_collisionCached(), ntlRay::shade(), IsoSurface::smoothSurface(), sqrt3d(), sqrt3f(), Texture_init(), tonemap(), SCA_RandomActuator::Update(), and waveModifier_do().
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::exp (const Rall2d< T, V, S > & arg)
Definition at line 317 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, exp(), and KDL::Rall2d< T, V, S >::t.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::hypot (const Rall2d< T, V, S > & y, const Rall2d< T, V, S > & x)
Definition at line 471 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, hypot(), sqr(), and KDL::Rall2d< T, V, S >::t.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::hypot (const Rall1d< T, V, S > & y, const Rall1d< T, V, S > & x)
Definition at line 384 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, T, and KDL::Rall1d< T, V, S >::t.
Referenced by hypot().
void KDL::IOTrace (const std::string & description)
Definition at line 35 of file error_stack.cpp.
References errorstack.
Referenced by operator>>().
void KDL::IOTraceOutput (std::ostream & os)
outputs the IO-stack to a stream to provide a better errormessage.
Definition at line 44 of file error_stack.cpp.
References errorstack.
void KDL::IOTracePop ()
pops a description of the IO-stack
Definition at line 40 of file error_stack.cpp.
References errorstack.
Referenced by operator>>().
void KDL::IOTracePopStr (char * buffer, int size)
outputs one element of the IO-stack to the buffer (maximally size chars) returns empty string if no elements on the stack.
Definition at line 52 of file error_stack.cpp.
References errorstack, and size().
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::LinComb (S alfa, const Rall2d< T, V, S > & a, const T & beta, const Rall2d< T, V, S > & b)
Definition at line 491 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, LinComb(), and KDL::Rall2d< T, V, S >::t.
double KDL::LinComb (double alfa, double a, double beta, double b) [inline]
Definition at line 227 of file utility.h.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::LinComb (S alfa, const Rall1d< T, V, S > & a, const T & beta, const Rall1d< T, V, S > & b)
Definition at line 438 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
Referenced by LinComb(), and KDL::Rall1d< T, V, S >::operator/=().
template<class T , class V , class S > INLINE void KDL::LinCombR (S alfa, const Rall2d< T, V, S > & a, const T & beta, const Rall2d< T, V, S > & b, Rall2d< T, V, S > & result)
Definition at line 501 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, LinCombR(), and KDL::Rall2d< T, V, S >::t.
void KDL::LinCombR (double alfa, double a, double beta, double b, double & result) [inline]
Definition at line 232 of file utility.h.
template<class T , class V , class S > INLINE void KDL::LinCombR (S alfa, const Rall1d< T, V, S > & a, const T & beta, const Rall1d< T, V, S > & b, Rall1d< T, V, S > & result)
Definition at line 447 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
Referenced by LinCombR(), and KDL::Rall1d< T, V, S >::operator*=().
double KDL::log (double a) [inline]
Definition at line 94 of file utility.h.
References log().
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::log (const Rall1d< T, V, S > & arg)
Definition at line 304 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, T, and KDL::Rall1d< T, V, S >::t.
Referenced by log().
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::log (const Rall2d< T, V, S > & arg)
Definition at line 327 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, log(), and KDL::Rall2d< T, V, S >::t.
double KDL::max (double a, double b) [inline]
Definition at line 200 of file utility.h.
double KDL::min (double a, double b) [inline]
Definition at line 208 of file utility.h.
void KDL::Multiply (const JntArray & src, const double & factor, JntArray & dest)
Function to multiply all the array values with a scalar factor: A*b=C. This function is aliasing-safe, A can be the same array as C.
Parameters:
src A
factor b
dest C
Definition at line 112 of file jntarray.cpp.
References assert, and i.
Referenced by Divide(), and Multiply().
void KDL::Multiply (const JntArrayAcc & src, const double & factor, JntArrayAcc & dest)
Definition at line 100 of file jntarrayacc.cpp.
References Multiply(), KDL::JntArrayAcc::q, KDL::JntArrayAcc::qdot, and KDL::JntArrayAcc::qdotdot.
void KDL::Multiply (const JntArrayAcc & src, const doubleVel & factor, JntArrayAcc & dest)
Definition at line 106 of file jntarrayacc.cpp.
References Add(), KDL::Rall1d< T, V, S >::grad, Multiply(), KDL::JntArrayAcc::q, KDL::JntArrayAcc::qdot, KDL::JntArrayAcc::qdotdot, and KDL::Rall1d< T, V, S >::t.
void KDL::Multiply (const JntArrayAcc & src, const doubleAcc & factor, JntArrayAcc & dest)
Definition at line 116 of file jntarrayacc.cpp.
References Add(), KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, Multiply(), KDL::JntArrayAcc::q, KDL::JntArrayAcc::qdot, KDL::JntArrayAcc::qdotdot, and KDL::Rall2d< T, V, S >::t.
void KDL::Multiply (const JntArrayVel & src, const double & factor, JntArrayVel & dest)
Definition at line 76 of file jntarrayvel.cpp.
References Multiply(), KDL::JntArrayVel::q, and KDL::JntArrayVel::qdot.
void KDL::Multiply (const JntArrayVel & src, const doubleVel & factor, JntArrayVel & dest)
Definition at line 81 of file jntarrayvel.cpp.
References Add(), KDL::Rall1d< T, V, S >::grad, Multiply(), KDL::JntArrayVel::q, KDL::JntArrayVel::qdot, and KDL::Rall1d< T, V, S >::t.
void KDL::MultiplyJacobian (const Jacobian & jac, const JntArray & src, Twist & dest)
Function to multiply a KDL::Jacobian with a KDL::JntArray to get a KDL::Twist, it should not be used to calculate the forward velocity kinematics, the solver classes are built for this purpose. J*q = t
Parameters:
jac J
src q
dest t
Postcondition:
dest==Twist::Zero() if 0==src.rows() (ie src is empty)
Definition at line 126 of file jntarray.cpp.
References assert, KDL::Jacobian::columns(), i, and SetToZero().
double KDL::Norm (double arg) [inline]
Definition at line 252 of file utility.h.
References fabs().
template<class T , class V , class S > INLINE S KDL::Norm (const Rall2d< T, V, S > & value)
Definition at line 482 of file rall2d.h.
References Norm(), and KDL::Rall2d< T, V, S >::t.
template<class T , class V , class S > INLINE S KDL::Norm (const Rall1d< T, V, S > & value)
Definition at line 417 of file rall1d.h.
References KDL::Rall1d< T, V, S >::t.
Referenced by Norm(), and iTaSC::Distance::updateControlOutput().
VectorAcc KDL::operator* (const VectorAcc & r1, const Vector & r2)
Definition at line 59 of file frameacc.hpp.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::operator* (const Rall2d< T, V, S > & v, S s)
Definition at line 269 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, and KDL::Rall2d< T, V, S >::t.
TwistVel KDL::operator* (const TwistVel & lhs, double rhs)
Definition at line 415 of file framevel.hpp.
TwistVel KDL::operator* (const TwistVel & lhs, const doubleVel & rhs)
Definition at line 431 of file framevel.hpp.
TwistVel KDL::operator* (const doubleVel & lhs, const TwistVel & rhs)
Definition at line 436 of file framevel.hpp.
TwistAcc KDL::operator* (const TwistAcc & lhs, double rhs)
Definition at line 471 of file frameacc.hpp.
VectorVel KDL::operator* (const doubleVel & r1, const VectorVel & r2)
Definition at line 270 of file framevel.hpp.
FrameAcc KDL::operator* (const FrameAcc & lhs, const Frame & rhs)
Definition at line 353 of file frameacc.hpp.
TwistAcc KDL::operator* (const TwistAcc & lhs, const doubleAcc & rhs)
Definition at line 487 of file frameacc.hpp.
TwistAcc KDL::operator* (const doubleAcc & lhs, const TwistAcc & rhs)
Definition at line 492 of file frameacc.hpp.
FrameAcc KDL::operator* (const Frame & lhs, const FrameAcc & rhs)
Definition at line 357 of file frameacc.hpp.
VectorVel KDL::operator* (const VectorVel & r1, const Vector & r2)
Definition at line 249 of file framevel.hpp.
VectorAcc KDL::operator* (const Vector & r1, const VectorAcc & r2)
Definition at line 63 of file frameacc.hpp.
VectorVel KDL::operator* (const VectorVel & r1, double r2)
Definition at line 264 of file framevel.hpp.
VectorAcc KDL::operator* (double r1, const VectorAcc & r2)
Definition at line 70 of file frameacc.hpp.
VectorVel KDL::operator* (const Vector & r1, const VectorVel & r2)
Definition at line 253 of file framevel.hpp.
References KDL::TwistVel::rot, KDL::VectorVel::value(), and KDL::TwistVel::vel.
RotationAcc KDL::operator* (const RotationAcc & r1, const RotationAcc & r2)
Definition at line 192 of file frameacc.hpp.
FrameVel KDL::operator* (const FrameVel & lhs, const FrameVel & rhs)
Definition at line 33 of file framevel.hpp.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::operator* (S s, const Rall1d< T, V, S > & v)
Definition at line 247 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::operator* (const Rall1d< T, V, S > & v, S s)
Definition at line 253 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
FrameVel KDL::operator* (const FrameVel & lhs, const Frame & rhs)
Definition at line 37 of file framevel.hpp.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
FrameVel KDL::operator* (const Frame & lhs, const FrameVel & rhs)
Definition at line 41 of file framevel.hpp.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
Rotation KDL::operator* (const Rotation & lhs, const Rotation & rhs)
Definition at line 177 of file frames.cpp.
References KDL::Rotation::data, and Rotation().
RotationAcc KDL::operator* (const Rotation & r1, const RotationAcc & r2)
Definition at line 199 of file frameacc.hpp.
VectorAcc KDL::operator* (const VectorAcc & r1, const VectorAcc & r2)
Definition at line 52 of file frameacc.hpp.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::operator* (const Rall1d< T, V, S > & lhs, const Rall1d< T, V, S > & rhs)
Definition at line 222 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
RotationVel KDL::operator* (const RotationVel & r1, const RotationVel & r2)
Definition at line 94 of file framevel.hpp.
RotationAcc KDL::operator* (const RotationAcc & r1, const Rotation & r2)
Definition at line 203 of file frameacc.hpp.
RotationVel KDL::operator* (const Rotation & r1, const RotationVel & r2)
Definition at line 98 of file framevel.hpp.
RotationVel KDL::operator* (const RotationVel & r1, const Rotation & r2)
Definition at line 102 of file framevel.hpp.
VectorAcc KDL::operator* (const doubleAcc & r1, const VectorAcc & r2)
Definition at line 78 of file frameacc.hpp.
VectorAcc KDL::operator* (const Rotation & R, const VectorAcc & x)
Definition at line 254 of file frameacc.hpp.
VectorVel KDL::operator* (const VectorVel & r1, const VectorVel & r2)
Definition at line 245 of file framevel.hpp.
TwistAcc KDL::operator* (double lhs, const TwistAcc & rhs)
Definition at line 476 of file frameacc.hpp.
VectorVel KDL::operator* (double r1, const VectorVel & r2)
Definition at line 260 of file framevel.hpp.
VectorAcc KDL::operator* (const VectorAcc & r1, double r2)
Definition at line 74 of file frameacc.hpp.
TwistVel KDL::operator* (double lhs, const TwistVel & rhs)
Definition at line 420 of file framevel.hpp.
VectorVel KDL::operator* (const VectorVel & r2, const doubleVel & r1)
Definition at line 274 of file framevel.hpp.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::operator* (const Rall2d< T, V, S > & lhs, const Rall2d< T, V, S > & rhs)
Definition at line 235 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, and KDL::Rall2d< T, V, S >::t.
FrameAcc KDL::operator* (const FrameAcc & lhs, const FrameAcc & rhs)
Definition at line 349 of file frameacc.hpp.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::operator* (S s, const Rall2d< T, V, S > & v)
Definition at line 263 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, and KDL::Rall2d< T, V, S >::t.
VectorVel KDL::operator* (const Rotation & R, const VectorVel & x)
Definition at line 286 of file framevel.hpp.
VectorAcc KDL::operator* (const VectorAcc & r2, const doubleAcc & r1)
Definition at line 85 of file frameacc.hpp.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::operator+ (S s, const Rall2d< T, V, S > & v)
Definition at line 275 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, and KDL::Rall2d< T, V, S >::t.
VectorAcc KDL::operator+ (const VectorAcc & r1, const VectorAcc & r2)
Definition at line 24 of file frameacc.hpp.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::operator+ (const Rall1d< T, V, S > & lhs, const Rall1d< T, V, S > & rhs)
Definition at line 228 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
TwistVel KDL::operator+ (const TwistVel & lhs, const TwistVel & rhs)
Definition at line 449 of file framevel.hpp.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::operator+ (const Rall1d< T, V, S > & v, S s)
Definition at line 265 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
TwistAcc KDL::operator+ (const TwistAcc & lhs, const TwistAcc & rhs)
Definition at line 505 of file frameacc.hpp.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::operator+ (S s, const Rall1d< T, V, S > & v)
Definition at line 259 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
VectorAcc KDL::operator+ (const Vector & r1, const VectorAcc & r2)
Definition at line 31 of file frameacc.hpp.
VectorVel KDL::operator+ (const VectorVel & r1, const VectorVel & r2)
Definition at line 210 of file framevel.hpp.
VectorVel KDL::operator+ (const VectorVel & r1, const Vector & r2)
Definition at line 218 of file framevel.hpp.
VectorVel KDL::operator+ (const Vector & r1, const VectorVel & r2)
Definition at line 226 of file framevel.hpp.
VectorAcc KDL::operator+ (const VectorAcc & r1, const Vector & r2)
Definition at line 38 of file frameacc.hpp.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::operator+ (const Rall2d< T, V, S > & lhs, const Rall2d< T, V, S > & rhs)
Definition at line 245 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, and KDL::Rall2d< T, V, S >::t.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::operator+ (const Rall2d< T, V, S > & v, S s)
Definition at line 281 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, and KDL::Rall2d< T, V, S >::t.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::operator- (S s, const Rall2d< T, V, S > & v)
Definition at line 287 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, and KDL::Rall2d< T, V, S >::t.
VectorAcc KDL::operator- (const Vector & r1, const VectorAcc & r2)
Definition at line 35 of file frameacc.hpp.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::operator- (const Rall2d< T, V, S > & lhs, const Rall2d< T, V, S > & rhs)
Definition at line 251 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, and KDL::Rall2d< T, V, S >::t.
TwistVel KDL::operator- (const TwistVel & lhs, const TwistVel & rhs)
Definition at line 454 of file framevel.hpp.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::operator- (const Rall2d< T, V, S > & arg)
Definition at line 257 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, and KDL::Rall2d< T, V, S >::t.
VectorAcc KDL::operator- (const VectorAcc & r1, const VectorAcc & r2)
Definition at line 28 of file frameacc.hpp.
TwistAcc KDL::operator- (const TwistAcc & lhs, const TwistAcc & rhs)
Definition at line 510 of file frameacc.hpp.
TwistAcc KDL::operator- (const TwistAcc & arg)
Definition at line 516 of file frameacc.hpp.
VectorAcc KDL::operator- (const VectorAcc & r1, const Vector & r2)
Definition at line 42 of file frameacc.hpp.
VectorAcc KDL::operator- (const VectorAcc & r)
Definition at line 47 of file frameacc.hpp.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::operator- (const Rall1d< T, V, S > & arg)
Definition at line 241 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
VectorVel KDL::operator- (const VectorVel & r1, const VectorVel & r2)
Definition at line 214 of file framevel.hpp.
VectorVel KDL::operator- (const VectorVel & r1, const Vector & r2)
Definition at line 222 of file framevel.hpp.
VectorVel KDL::operator- (const Vector & r1, const VectorVel & r2)
Definition at line 230 of file framevel.hpp.
VectorVel KDL::operator- (const VectorVel & r)
Definition at line 235 of file framevel.hpp.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::operator- (const Rall1d< T, V, S > & lhs, const Rall1d< T, V, S > & rhs)
Definition at line 235 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::operator- (const Rall1d< T, V, S > & v, S s)
Definition at line 277 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::operator- (S s, const Rall1d< T, V, S > & v)
Definition at line 271 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
TwistVel KDL::operator- (const TwistVel & arg)
Definition at line 460 of file framevel.hpp.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::operator- (const Rall2d< T, V, S > & v, S s)
Definition at line 293 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, and KDL::Rall2d< T, V, S >::t.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::operator/ (S s, const Rall1d< T, V, S > & v)
Definition at line 283 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
TwistVel KDL::operator/ (const TwistVel & lhs, double rhs)
Definition at line 425 of file framevel.hpp.
VectorVel KDL::operator/ (const VectorVel & r2, const doubleVel & r1)
Definition at line 282 of file framevel.hpp.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::operator/ (const Rall1d< T, V, S > & lhs, const Rall1d< T, V, S > & rhs)
Definition at line 216 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
VectorVel KDL::operator/ (const VectorVel & r1, double r2)
Definition at line 278 of file framevel.hpp.
TwistVel KDL::operator/ (const TwistVel & lhs, const doubleVel & rhs)
Definition at line 441 of file framevel.hpp.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::operator/ (S s, const Rall2d< T, V, S > & rhs)
Definition at line 299 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, and KDL::Rall2d< T, V, S >::t.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::operator/ (const Rall2d< T, V, S > & lhs, const Rall2d< T, V, S > & rhs)
Definition at line 225 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, and KDL::Rall2d< T, V, S >::t.
TwistAcc KDL::operator/ (const TwistAcc & lhs, const doubleAcc & rhs)
Definition at line 497 of file frameacc.hpp.
VectorAcc KDL::operator/ (const VectorAcc & r1, double r2)
Definition at line 180 of file frameacc.hpp.
VectorAcc KDL::operator/ (const VectorAcc & r2, const doubleAcc & r1)
Definition at line 184 of file frameacc.hpp.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::operator/ (const Rall1d< T, V, S > & v, S s)
Definition at line 289 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, and KDL::Rall1d< T, V, S >::t.
TwistAcc KDL::operator/ (const TwistAcc & lhs, double rhs)
Definition at line 481 of file frameacc.hpp.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::operator/ (const Rall2d< T, V, S > & v, S s)
Definition at line 310 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, and KDL::Rall2d< T, V, S >::t.
std::ostream & KDL::operator<< (std::ostream & os, const Vector & v)
width to be used when printing variables out with frames_io.h global variable, can be changed.
Definition at line 45 of file frames_io.cpp.
References KDL_FRAME_WIDTH.
std::ostream & KDL::operator<< (std::ostream & os, const Rotation & R)
Definition at line 74 of file frames_io.cpp.
References KDL::Rotation::GetEulerZYX(), KDL::Rotation::GetRPY(), i, KDL_FRAME_WIDTH, p, and R.
std::ostream & KDL::operator<< (std::ostream & os, const Frame & T)
Definition at line 108 of file frames_io.cpp.
References KDL::Frame::M, and KDL::Frame::p.
std::ostream & KDL::operator<< (std::ostream & os, const Vector2 & v)
Definition at line 114 of file frames_io.cpp.
References KDL_FRAME_WIDTH.
std::ostream & KDL::operator<< (std::ostream & os, const Jacobian & jac)
Definition at line 88 of file kinfam_io.cpp.
References KDL::Jacobian::columns(), i, KDL_FRAME_WIDTH, and KDL::Jacobian::rows().
std::ostream & KDL::operator<< (std::ostream & os, const Frame2 & T)
Definition at line 126 of file frames_io.cpp.
References KDL::Frame2::M, and KDL::Frame2::p.
std::ostream & KDL::operator<< (std::ostream & os, const JntArray & array)
Definition at line 76 of file kinfam_io.cpp.
References i, KDL_FRAME_WIDTH, and KDL::JntArray::rows().
std::ostream & KDL::operator<< (std::ostream & os, const Rotation2 & R)
Definition at line 121 of file frames_io.cpp.
References KDL::Rotation2::GetRot(), and rad2deg.
std::ostream & KDL::operator<< (std::ostream & os, const Joint & joint)
Definition at line 29 of file kinfam_io.cpp.
References KDL::Joint::getTypeName().
std::ostream & KDL::operator<< (std::ostream & os, const Segment & segment)
Definition at line 37 of file kinfam_io.cpp.
References KDL::Segment::getFrameToTip(), and KDL::Segment::getJoint().
std::ostream & KDL::operator<< (std::ostream & os, const Chain & chain)
Definition at line 46 of file kinfam_io.cpp.
References KDL::Chain::getNrOfSegments(), KDL::Chain::getSegment(), and i.
std::ostream & KDL::operator<< (std::ostream & os, const Tree & tree)
Definition at line 58 of file kinfam_io.cpp.
References KDL::Tree::getSegment().
std::ostream & KDL::operator<< (std::ostream & os, SegmentMap::const_iterator root)
Definition at line 63 of file kinfam_io.cpp.
References i.
template<typename T > std::ostream& KDL::operator<< (std::ostream & os, const std::vector< T > & vec)
Definition at line 54 of file kinfam_io.hpp.
References i.
std::ostream & KDL::operator<< (std::ostream & os, const Twist & v)
Definition at line 51 of file frames_io.cpp.
References KDL_FRAME_WIDTH, KDL::Twist::rot, and KDL::Twist::vel.
std::ostream & KDL::operator<< (std::ostream & os, const Wrench & v)
Definition at line 62 of file frames_io.cpp.
References KDL::Wrench::force, KDL_FRAME_WIDTH, and KDL::Wrench::torque.
bool KDL::operator== (const JntArray & src1, const JntArray & src2)
Definition at line 150 of file jntarray.cpp.
References Equal().
bool KDL::operator== (const Rotation & a, const Rotation & b)
Definition at line 377 of file frames.cpp.
References KDL::Rotation::data, and Equal().
Referenced by operator!=().
std::istream & KDL::operator>> (std::istream & is, Joint & joint)
Definition at line 33 of file kinfam_io.cpp.
std::istream & KDL::operator>> (std::istream & is, Wrench & v)
Definition at line 174 of file frames_io.cpp.
References Eat(), EatEnd(), KDL::Wrench::force, IOTrace(), IOTracePop(), and KDL::Wrench::torque.
std::istream & KDL::operator>> (std::istream & is, Jacobian & jac)
Definition at line 99 of file kinfam_io.cpp.
std::istream & KDL::operator>> (std::istream & is, Twist & v)
Definition at line 155 of file frames_io.cpp.
References Eat(), EatEnd(), IOTrace(), IOTracePop(), KDL::Twist::rot, and KDL::Twist::vel.
std::istream & KDL::operator>> (std::istream & is, Rotation2 & r)
Definition at line 295 of file frames_io.cpp.
References deg2rad, Eat(), EatEnd(), IOTrace(), IOTracePop(), and KDL::Rotation2::Rot().
std::istream & KDL::operator>> (std::istream & is, Rotation & r)
Definition at line 193 of file frames_io.cpp.
References angle(), deg2rad, Eat(), EatEnd(), EatWord(), KDL::Rotation::EulerZYX(), KDL::Rotation::EulerZYZ(), i, KDL::Rotation::Identity(), IOTrace(), IOTracePop(), KDL::Rotation::Rot(), and KDL::Rotation::RPY().
std::istream & KDL::operator>> (std::istream & is, Tree & tree)
Definition at line 72 of file kinfam_io.cpp.
std::istream & KDL::operator>> (std::istream & is, Vector2 & v)
Definition at line 285 of file frames_io.cpp.
References Eat(), EatEnd(), IOTrace(), and IOTracePop().
std::istream & KDL::operator>> (std::istream & is, JntArray & array)
Definition at line 84 of file kinfam_io.cpp.
std::istream & KDL::operator>> (std::istream & is, Frame2 & T)
Definition at line 305 of file frames_io.cpp.
References IOTrace(), IOTracePop(), KDL::Frame2::M, and KDL::Frame2::p.
std::istream & KDL::operator>> (std::istream & is, Chain & chain)
Definition at line 54 of file kinfam_io.cpp.
std::istream & KDL::operator>> (std::istream & is, Frame & T)
Definition at line 254 of file frames_io.cpp.
References deg2rad, KDL::Frame::DH(), Eat(), EatEnd(), EatWord(), IOTrace(), IOTracePop(), KDL::Frame::M, and KDL::Frame::p.
std::istream & KDL::operator>> (std::istream & is, Segment & segment)
Definition at line 42 of file kinfam_io.cpp.
template<typename T > std::istream& KDL::operator>> (std::istream & is, std::vector< T > & vec)
Definition at line 64 of file kinfam_io.hpp.
std::istream & KDL::operator>> (std::istream & is, Vector & v)
Definition at line 132 of file frames_io.cpp.
References Eat(), EatEnd(), EatWord(), IOTrace(), IOTracePop(), and KDL::Vector::Zero().
IMETHOD void KDL::posrandom (TwistVel & a)
Definition at line 356 of file framevel.hpp.
IMETHOD void KDL::posrandom (doubleVel & F)
Definition at line 49 of file framevel.hpp.
Referenced by posrandom(), and posrandom().
void KDL::posrandom (double & a) [inline]
Definition at line 275 of file utility.h.
IMETHOD void KDL::posrandom (FrameVel & F)
Definition at line 366 of file framevel.hpp.
References KDL::FrameVel::M, KDL::FrameVel::p, and posrandom().
IMETHOD void KDL::posrandom (VectorVel & a)
Definition at line 352 of file framevel.hpp.
References KDL::VectorVel::p, posrandom(), and KDL::VectorVel::v.
IMETHOD void KDL::posrandom (RotationVel & R)
Definition at line 361 of file framevel.hpp.
References posrandom(), and KDL::RotationVel::R.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::pow (const Rall2d< T, V, S > & arg, double m)
Definition at line 394 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, pow(), T, and KDL::Rall2d< T, V, S >::t.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::pow (const Rall1d< T, V, S > & arg, double m)
Definition at line 360 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, T, and KDL::Rall1d< T, V, S >::t.
Referenced by pow().
double KDL::pow (double a, double b) [inline]
Definition at line 121 of file utility.h.
References pow().
template<typename Scalar > Scalar KDL::PYTHAG (Scalar a, Scalar b) [inline]
Definition at line 33 of file svd_eigen_HH.hpp.
References fabs(), and sqrt().
Referenced by svd_eigen_HH().
IMETHOD void KDL::random (RotationVel & R)
Definition at line 343 of file framevel.hpp.
References KDL::RotationVel::R, random(), and KDL::RotationVel::w.
IMETHOD void KDL::random (FrameVel & F)
Definition at line 348 of file framevel.hpp.
References KDL::FrameVel::M, and random().
void KDL::random (double & a) [inline]
Definition at line 271 of file utility.h.
IMETHOD void KDL::random (VectorVel & a)
Definition at line 334 of file framevel.hpp.
References KDL::VectorVel::p, and random().
IMETHOD void KDL::random (TwistVel & a)
Definition at line 338 of file framevel.hpp.
IMETHOD void KDL::random (doubleVel & F)
Definition at line 45 of file framevel.hpp.
Referenced by posrandom(), random(), and random().
template<class T , class V , class S > INLINE void KDL::SetToIdentity (Rall2d< T, V, S > & value)
Definition at line 517 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, SetToIdentity(), SetToZero(), and KDL::Rall2d< T, V, S >::t.
template<class T , class V , class S > INLINE void KDL::SetToIdentity (Rall1d< T, V, S > & value)
Definition at line 461 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, SetToZero(), and KDL::Rall1d< T, V, S >::t.
Referenced by KDL::Rall1d< T, V, S >::Identity(), KDL::Rall2d< T, V, S >::Identity(), and SetToIdentity().
void KDL::SetToIdentity (double & arg) [inline]
to uniformly set double, RNDouble,Vector,... objects to the identity element in template-classes
Definition at line 243 of file utility.h.
void KDL::SetToZero (Jacobian & jac)
Definition at line 81 of file jacobian.cpp.
References i, SetToZero(), and KDL::Jacobian::twists.
template<class T , class V , class S > INLINE void KDL::SetToZero (Rall2d< T, V, S > & value)
Definition at line 509 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, SetToZero(), and KDL::Rall2d< T, V, S >::t.
void KDL::SetToZero (VectorVel & v)
Definition at line 239 of file framevel.hpp.
Referenced by KDL::ChainJntToJacSolver::JntToJac(), KDL::TreeJntToJacSolver::JntToJac(), MultiplyJacobian(), KDL::Rall1d< T, V, S >::operator=(), KDL::Rall2d< T, V, S >::operator=(), KDL::Rall1d< T, V, S >::Rall1d(), KDL::Rall2d< T, V, S >::Rall2d(), SetToIdentity(), SetToZero(), SetToZero(), KDL::Rall2d< T, V, S >::Zero(), and KDL::Rall1d< T, V, S >::Zero().
template<class T , class V , class S > INLINE void KDL::SetToZero (Rall1d< T, V, S > & value)
Definition at line 455 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, SetToZero(), and KDL::Rall1d< T, V, S >::t.
void KDL::SetToZero (JntArrayVel & array)
Definition at line 102 of file jntarrayvel.cpp.
References KDL::JntArrayVel::q, KDL::JntArrayVel::qdot, and SetToZero().
void KDL::SetToZero (double & arg) [inline]
to uniformly set double, RNDouble,Vector,... objects to zero in template-classes
Definition at line 238 of file utility.h.
void KDL::SetToZero (JntArray & array)
Function to set all the values of the array to 0
Parameters:
array
Definition at line 135 of file jntarray.cpp.
References i.
void KDL::SetToZero (TwistVel & v)
Definition at line 465 of file framevel.hpp.
void KDL::SetToZero (JntArrayAcc & array)
Definition at line 160 of file jntarrayacc.cpp.
References KDL::JntArrayAcc::q, KDL::JntArrayAcc::qdot, KDL::JntArrayAcc::qdotdot, and SetToZero().
double KDL::sign (double arg) [inline]
Definition at line 247 of file utility.h.
Referenced by KDL::Rotation::GetRPY().
template<typename Scalar > Scalar KDL::SIGN (Scalar a, Scalar b) [inline]
Definition at line 51 of file svd_eigen_HH.hpp.
References fabs().
Referenced by svd_eigen_HH().
double KDL::sin (double a) [inline]
Definition at line 84 of file utility.h.
References sin().
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::sin (const Rall2d< T, V, S > & arg)
Definition at line 337 of file rall2d.h.
References cos(), KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, sin(), T, and KDL::Rall2d< T, V, S >::t.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::sin (const Rall1d< T, V, S > & arg)
Definition at line 312 of file rall1d.h.
References cos(), KDL::Rall1d< T, V, S >::grad, T, and KDL::Rall1d< T, V, S >::t.
Referenced by acos(), base_callback(), cos(), KDL::Frame::DH(), KDL::Frame::DH_Craig1989(), KDL::RotationVel::DoRotX(), KDL::RotationVel::DoRotY(), KDL::RotationVel::DoRotZ(), KDL::Rotation::EulerZYZ(), KDL::Rotation::GetRotAngle(), KDL::RotationVel::Rot(), KDL::Rotation::Rot(), Rot(), KDL::Rotation::Rot2(), KDL::RotationVel::RotX(), KDL::RotationVel::RotY(), KDL::RotationVel::RotZ(), KDL::Rotation::RPY(), KDL::Rotation2::SetRot(), and sin().
double KDL::sinh (double a) [inline]
Definition at line 103 of file utility.h.
References sinh().
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::sinh (const Rall1d< T, V, S > & arg)
Definition at line 336 of file rall1d.h.
References cosh(), KDL::Rall1d< T, V, S >::grad, T, and KDL::Rall1d< T, V, S >::t.
Referenced by MeanValueMeshCoords::computeWeights(), cosh(), and sinh().
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::sinh (const Rall2d< T, V, S > & arg)
Definition at line 361 of file rall2d.h.
References cosh(), KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, sinh(), T, and KDL::Rall2d< T, V, S >::t.
double KDL::sqr (double arg) [inline]
Definition at line 251 of file utility.h.
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::sqr (const Rall2d< T, V, S > & arg)
Definition at line 385 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, sqr(), and KDL::Rall2d< T, V, S >::t.
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::sqr (const Rall1d< T, V, S > & arg)
Definition at line 352 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, T, and KDL::Rall1d< T, V, S >::t.
Referenced by acos(), asin(), atan(), atan2(), copypose_error(), fresnel(), KDL::Rotation::GetEulerZYZ(), KDL::Rotation::GetRPY(), hypot(), KDL::Vector2::Norm(), KDL::Vector::Norm(), KDL::Rotation::Ortho(), processSamples(), TNT::pythag(), QMC_sampleDisc(), QMC_sampleHemi(), QMC_samplePhong(), KX_ObstacleSimulationTOI_cells::sampleRVO(), iTaSC::WDLSSolver::solve(), sqr(), sqrt(), tan(), tanh(), and iTaSC::Armature::updateJoint().
double KDL::sqrt (double a) [inline]
Definition at line 106 of file utility.h.
References sqrt().
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::sqrt (const Rall1d< T, V, S > & arg)
Definition at line 368 of file rall1d.h.
References KDL::Rall1d< T, V, S >::grad, T, and KDL::Rall1d< T, V, S >::t.
Referenced by acos(), asin(), copypose_error(), EulerAngleFromMatrix(), KDL::Rotation::GetEulerZYZ(), KDL::Rotation::GetRotAngle(), KDL::Rotation::GetRPY(), KDL::Vector2::Norm(), KDL::Vector::Norm(), KDL::Rotation::Ortho(), PYTHAG(), sqrt(), and svd_eigen_HH().
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::sqrt (const Rall2d< T, V, S > & arg)
Definition at line 405 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, sqr(), sqrt(), and KDL::Rall2d< T, V, S >::t.
void KDL::Subtract (const JntArray & src1, const JntArray & src2, JntArray & dest)
Function to subtract two joint arrays, all the arguments must have the same size: A - B = C. This function is aliasing-safe, A or B can be the same array as C.
Parameters:
src1 A
src2 B
dest C
Definition at line 105 of file jntarray.cpp.
References assert, and i.
Referenced by Divide(), and Subtract().
void KDL::Subtract (const JntArrayVel & src1, const JntArrayVel & src2, JntArrayVel & dest)
Definition at line 65 of file jntarrayvel.cpp.
References KDL::JntArrayVel::q, KDL::JntArrayVel::qdot, and Subtract().
void KDL::Subtract (const JntArrayVel & src1, const JntArray & src2, JntArrayVel & dest)
Definition at line 70 of file jntarrayvel.cpp.
References KDL::JntArrayVel::q, KDL::JntArrayVel::qdot, and Subtract().
void KDL::Subtract (const JntArrayAcc & src1, const JntArrayAcc & src2, JntArrayAcc & dest)
Definition at line 81 of file jntarrayacc.cpp.
References KDL::JntArrayAcc::q, KDL::JntArrayAcc::qdot, KDL::JntArrayAcc::qdotdot, and Subtract().
void KDL::Subtract (const JntArrayAcc & src1, const JntArrayVel & src2, JntArrayAcc & dest)
Definition at line 87 of file jntarrayacc.cpp.
References KDL::JntArrayAcc::q, KDL::JntArrayVel::q, KDL::JntArrayAcc::qdot, KDL::JntArrayVel::qdot, KDL::JntArrayAcc::qdotdot, and Subtract().
void KDL::Subtract (const JntArrayAcc & src1, const JntArray & src2, JntArrayAcc & dest)
Definition at line 93 of file jntarrayacc.cpp.
References KDL::JntArrayAcc::q, KDL::JntArrayAcc::qdot, KDL::JntArrayAcc::qdotdot, and Subtract().
template<typename MatrixA , typename MatrixUV , typename VectorS > int KDL::svd_eigen_HH (const Eigen::MatrixBase< MatrixA > & A, Eigen::MatrixBase< MatrixUV > & U, Eigen::MatrixBase< VectorS > & S, Eigen::MatrixBase< MatrixUV > & V, Eigen::MatrixBase< VectorS > & tmp, int maxiter = 150)
svd calculation of boost ublas matrices
Parameters:
A matrix<double>(mxn)
U matrix<double>(mxn)
S vector<double> n
V matrix<double>(nxn)
tmp vector<double> n
maxiter defaults to 150
Returns:
-2 if maxiter exceeded, 0 otherwise
Definition at line 68 of file svd_eigen_HH.hpp.
References e_scalar, fabs(), g, i, PYTHAG(), SIGN(), sqrt(), and V.
Referenced by iTaSC::ConstraintSet::closeLoop(), iTaSC::WDLSSolver::solve(), iTaSC::WSDLSSolver::solve(), and iTaSC::Scene::update().
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::tan (const Rall1d< T, V, S > & arg)
Definition at line 328 of file rall1d.h.
References cos(), KDL::Rall1d< T, V, S >::grad, sqr(), KDL::Rall1d< T, V, S >::t, and T.
Referenced by BL_ConvertSensors(), KX_Dome::CalculateFrustum(), copy_text(), KX_Dome::CreateMeshDome250(), do_math(), fcm_fn_generator_evaluate(), node_shader_exec_math(), AUD_ButterworthFactory::recalculateCoefficients(), ntlWorld::renderScene(), sky_texture_precompute(), tan(), valuefn(), and WardIso_Spec().
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::tan (const Rall2d< T, V, S > & arg)
Definition at line 353 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, sqr(), T, KDL::Rall2d< T, V, S >::t, and tan().
double KDL::tan (double a) [inline]
Definition at line 97 of file utility.h.
References tan().
double KDL::tanh (double a) [inline]
Definition at line 118 of file utility.h.
References tanh().
template<class T , class V , class S > INLINE Rall1d<T,V,S> KDL::tanh (const Rall1d< T, V, S > & arg)
Definition at line 423 of file rall1d.h.
References cosh(), KDL::Rall1d< T, V, S >::grad, sqr(), T, and KDL::Rall1d< T, V, S >::t.
Referenced by tanh().
template<class T , class V , class S > INLINE Rall2d<T,V,S> KDL::tanh (const Rall2d< T, V, S > & arg)
Definition at line 377 of file rall2d.h.
References KDL::Rall2d< T, V, S >::d, KDL::Rall2d< T, V, S >::dd, sqr(), T, KDL::Rall2d< T, V, S >::t, and tanh().
char KDL::Upper (char ch) [inline]
Definition at line 143 of file utility_io.cpp.
Referenced by Eat().
Variable Documentation
const double KDL::deg2rad = 0.01745329251994329576923690768488
the value pi/180
Definition at line 20 of file utility.cpp.
Referenced by operator>>().
double KDL::epsilon = 0.000001
default precision while comparing with Equal(..,..) functions. Initialized at 0.0000001.
Definition at line 22 of file utility.cpp.
Referenced by BLI_bvhtree_new(), BMBVH_EdgeVisible(), bvhtree_from_mesh_edges(), bvhtree_from_mesh_faces(), bvhtree_from_mesh_verts(), btSubsimplexConvexCast::calcTimeOfImpact(), compress_deepsamples(), IK_QJacobian::ComputeNullProjection(), convert_tree(), iTaSC::Distance::Distance(), EulerAngleFromMatrix(), ff_visible_quad(), iTaSC::Armature::finalize(), KDL::Rotation::GetEulerZYZ(), KDL::Rotation::GetRot(), KDL::Rotation::GetRPY(), KDL::Rotation::GetXZRot(), KDL::Frame2::Integrate(), meshdeform_ray_tree_intersect(), occ_visible_quad(), pseudoInverse(), iTaSC::Distance::setControlParameters(), iTaSC::WSDLSSolver::solve(), iTaSC::WDLSSolver::solve(), iTaSC::Scene::update(), iTaSC::Armature::updateJoint(), iTaSC::Distance::updateKinematics(), and Vector_richcmpr().
double KDL::epsilon2 = 0.000001*0.000001
power or 2 of epsilon
Definition at line 23 of file utility.cpp.
Referenced by cloth_collision_response_static(), and iTaSC::Armature::updateJoint().
ErrorStack KDL::errorstack
Definition at line 31 of file error_stack.cpp.
Referenced by IOTrace(), IOTraceOutput(), IOTracePop(), and IOTracePopStr().
int KDL::MAXLENFILENAME = 255
maximal length of a file name
Definition at line 18 of file utility.cpp.
const double KDL::PI = 3.1415926535897932384626433832795
the value of pi
Definition at line 19 of file utility.cpp.
Referenced by KDL::Rotation::GetEulerZYZ(), KDL::Rotation::GetRot(), KDL::Rotation::GetRotAngle(), KDL::Rotation::GetRPY(), and KDL::Rotation::GetXZRot().
const double KDL::rad2deg = 57.2957795130823208767981548141052
the value 180/pi
Definition at line 21 of file utility.cpp.
Referenced by operator<<().
int KDL::STREAMBUFFERSIZE = 10000
/note linkage Something fishy about the difference between C++ and C in C++ const values default to INTERNAL linkage, in C they default to EXTERNAL linkage. Here the constants should have EXTERNAL linkage because they, for at least some of them, can be changed by the user. If you want to explicitly declare internal linkage, use "static".
Definition at line 17 of file utility.cpp.
int KDL::VSIZE
the number of derivatives used in the RN-... objects.