Blender: CPropValue Class Reference
CPropValue Class Reference
#include <Value.h>
Public Member Functions
CPropValue ()
virtual ~CPropValue ()
virtual void SetName (const char *name)
virtual STR_String & GetName ()
Protected Attributes
STR_String m_strNewName
Detailed Description
Definition at line 411 of file Value.h.
Constructor & Destructor Documentation
CPropValue::CPropValue () [inline]
Definition at line 414 of file Value.h.
virtual CPropValue::~CPropValue () [inline, virtual]
Definition at line 421 of file Value.h.
Member Function Documentation
virtual STR_String& CPropValue::GetName () [inline, virtual]
Implements CValue.
Definition at line 429 of file Value.h.
Referenced by CVectorValue::CalcFinal().
virtual void CPropValue::SetName (const char * name) [inline, virtual]
Implements CValue.
Definition at line 425 of file Value.h.
Referenced by CBoolValue::CBoolValue(), CFloatValue::CFloatValue(), CIntValue::CIntValue(), CStringValue::CStringValue(), and CVectorValue::CVectorValue().
Member Data Documentation
STR_String CPropValue::m_strNewName [protected]
Definition at line 437 of file Value.h.
The documentation for this class was generated from the following file:
Value.h