Blender: SCA_ANDController Class Reference
SCA_ANDController Class Reference
#include <SCA_ANDController.h>
Public Member Functions
SCA_ANDController (SCA_IObject *gameobj)
virtual ~SCA_ANDController ()
virtual CValue * GetReplica ()
virtual void Trigger (SCA_LogicManager *logicmgr)
Detailed Description
Definition at line 40 of file SCA_ANDController.h.
Constructor & Destructor Documentation
SCA_ANDController::SCA_ANDController (SCA_IObject * gameobj)
Definition at line 45 of file SCA_ANDController.cpp.
Referenced by GetReplica().
SCA_ANDController::~SCA_ANDController () [virtual]
Definition at line 53 of file SCA_ANDController.cpp.
Member Function Documentation
CValue * SCA_ANDController::GetReplica (void) [virtual]
Implements CValue.
Definition at line 85 of file SCA_ANDController.cpp.
References CValue::ProcessReplica(), and SCA_ANDController().
void SCA_ANDController::Trigger (SCA_LogicManager * logicmgr) [virtual]
Implements SCA_IController.
Definition at line 59 of file SCA_ANDController.cpp.
References SCA_LogicManager::AddActiveActuator(), SCA_ISensor::GetState(), i, SCA_IController::m_linkedactuators, and SCA_IController::m_linkedsensors.
The documentation for this class was generated from the following files:
SCA_ANDController.h
SCA_ANDController.cpp