Blender: MT_Vector4 Class Reference
MT_Vector4 Class Reference
#include <MT_Vector4.h>
Public Member Functions
virtual ~MT_Vector4 ()
MT_Vector4 ()
MT_Vector4 (const float *v)
MT_Vector4 (const double *v)
MT_Vector4 (MT_Scalar xx, MT_Scalar yy, MT_Scalar zz, MT_Scalar ww)
MT_Vector4 & operator+= (const MT_Vector4 &v)
MT_Vector4 & operator-= (const MT_Vector4 &v)
MT_Vector4 & operator*= (MT_Scalar s)
MT_Vector4 & operator/= (MT_Scalar s)
MT_Scalar dot (const MT_Vector4 &v) const
MT_Scalar length2 () const
MT_Scalar length () const
MT_Vector4 absolute () const
void normalize ()
MT_Vector4 normalized () const
void scale (MT_Scalar x, MT_Scalar y, MT_Scalar z, MT_Scalar w)
MT_Vector4 scaled (MT_Scalar x, MT_Scalar y, MT_Scalar z, MT_Scalar w) const
bool fuzzyZero () const
Detailed Description
Definition at line 54 of file MT_Vector4.h.
Constructor & Destructor Documentation
virtual MT_Vector4::~MT_Vector4 () [inline, virtual]
Definition at line 56 of file MT_Vector4.h.
MT_Vector4::MT_Vector4 () [inline]
Definition at line 57 of file MT_Vector4.h.
Referenced by absolute(), and scaled().
MT_Vector4::MT_Vector4 (const float * v) [inline]
Definition at line 58 of file MT_Vector4.h.
MT_Vector4::MT_Vector4 (const double * v) [inline]
Definition at line 59 of file MT_Vector4.h.
MT_Vector4::MT_Vector4 (MT_Scalar xx, MT_Scalar yy, MT_Scalar zz, MT_Scalar ww) [inline]
Definition at line 60 of file MT_Vector4.h.
Member Function Documentation
GEN_INLINE MT_Vector4 MT_Vector4::absolute () const
Definition at line 53 of file MT_Vector4.inl.
References MT_Tuple4::m_co, MT_abs(), and MT_Vector4().
GEN_INLINE MT_Scalar MT_Vector4::dot (const MT_Vector4 & v) const
Definition at line 46 of file MT_Vector4.inl.
References MT_Tuple4::m_co.
Referenced by MT_Quaternion::angle(), MT_dot(), and MT_Quaternion::slerp().
GEN_INLINE bool MT_Vector4::fuzzyZero () const
Definition at line 65 of file MT_Vector4.inl.
References length2(), and MT_fuzzyZero2().
Referenced by MT_fuzzyZero().
GEN_INLINE MT_Scalar MT_Vector4::length () const
Definition at line 51 of file MT_Vector4.inl.
References length2(), and sqrt().
Referenced by MT_length(), normalize(), and normalized().
GEN_INLINE MT_Scalar MT_Vector4::length2 () const
Definition at line 50 of file MT_Vector4.inl.
References MT_dot().
Referenced by MT_Quaternion::angle(), fuzzyZero(), MT_Quaternion::inverse(), MT_Quaternion::invert(), length(), MT_length2(), and MT_Matrix3x3::setRotation().
GEN_INLINE void MT_Vector4::normalize ()
Definition at line 67 of file MT_Vector4.inl.
References length().
GEN_INLINE MT_Vector4 MT_Vector4::normalized () const
Definition at line 68 of file MT_Vector4.inl.
References length().
Referenced by MT_ExpMap::setRotation().
GEN_INLINE MT_Vector4 & MT_Vector4::operator*= (MT_Scalar s)
Definition at line 13 of file MT_Vector4.inl.
References MT_Tuple4::m_co.
GEN_INLINE MT_Vector4 & MT_Vector4::operator+= (const MT_Vector4 & v)
Definition at line 3 of file MT_Vector4.inl.
References MT_Tuple4::m_co.
GEN_INLINE MT_Vector4 & MT_Vector4::operator-= (const MT_Vector4 & v)
Definition at line 8 of file MT_Vector4.inl.
References MT_Tuple4::m_co.
GEN_INLINE MT_Vector4 & MT_Vector4::operator/= (MT_Scalar s)
Definition at line 18 of file MT_Vector4.inl.
References MT_assert, and MT_fuzzyZero().
GEN_INLINE void MT_Vector4::scale (MT_Scalar x, MT_Scalar y, MT_Scalar z, MT_Scalar w)
Definition at line 57 of file MT_Vector4.inl.
References MT_Tuple4::m_co.
GEN_INLINE MT_Vector4 MT_Vector4::scaled (MT_Scalar x, MT_Scalar y, MT_Scalar z, MT_Scalar w) const
Definition at line 61 of file MT_Vector4.inl.
References MT_Tuple4::m_co, and MT_Vector4().
The documentation for this class was generated from the following files:
MT_Vector4.h
MT_Vector4.inl