Blender: GHOST_DisplayManagerSDL Class Reference
GHOST_DisplayManagerSDL Class Reference
#include <GHOST_DisplayManagerSDL.h>
Public Member Functions
GHOST_DisplayManagerSDL (GHOST_SystemSDL *system)
GHOST_TSuccess getNumDisplays (GHOST_TUns8 &numDisplays) const
GHOST_TSuccess getNumDisplaySettings (GHOST_TUns8 display, GHOST_TInt32 &numSettings) const
GHOST_TSuccess getDisplaySetting (GHOST_TUns8 display, GHOST_TInt32 index, GHOST_DisplaySetting &setting) const
GHOST_TSuccess getCurrentDisplaySetting (GHOST_TUns8 display, GHOST_DisplaySetting &setting) const
GHOST_TSuccess getCurrentDisplayModeSDL (SDL_DisplayMode &mode) const
GHOST_TSuccess setCurrentDisplaySetting (GHOST_TUns8 display, const GHOST_DisplaySetting &setting)
Detailed Description
Definition at line 43 of file GHOST_DisplayManagerSDL.h.
Constructor & Destructor Documentation
GHOST_DisplayManagerSDL::GHOST_DisplayManagerSDL (GHOST_SystemSDL * system)
Definition at line 37 of file GHOST_DisplayManagerSDL.cpp.
Member Function Documentation
GHOST_TSuccess GHOST_DisplayManagerSDL::getCurrentDisplayModeSDL (SDL_DisplayMode & mode) const
Definition at line 108 of file GHOST_DisplayManagerSDL.cpp.
References GHOST_kSuccess.
GHOST_TSuccess GHOST_DisplayManagerSDL::getCurrentDisplaySetting (GHOST_TUns8 display, GHOST_DisplaySetting & setting) const [virtual]
Returns the current setting for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
setting The current setting of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 96 of file GHOST_DisplayManagerSDL.cpp.
References GHOST_kSuccess, and ghost_mode_from_sdl().
GHOST_TSuccess GHOST_DisplayManagerSDL::getDisplaySetting (GHOST_TUns8 display, GHOST_TInt32 index, GHOST_DisplaySetting & setting) const [virtual]
Returns the current setting for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
index The setting index to be returned.
setting The setting of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 81 of file GHOST_DisplayManagerSDL.cpp.
References GHOST_ASSERT, GHOST_kSuccess, and ghost_mode_from_sdl().
GHOST_TSuccess GHOST_DisplayManagerSDL::getNumDisplays (GHOST_TUns8 & numDisplays) const [virtual]
Returns the number of display devices on this system.
Parameters:
numDisplays The number of displays on this system.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 46 of file GHOST_DisplayManagerSDL.cpp.
References GHOST_kSuccess.
GHOST_TSuccess GHOST_DisplayManagerSDL::getNumDisplaySettings (GHOST_TUns8 display, GHOST_TInt32 & numSettings) const [virtual]
Returns the number of display settings for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
numSettings The number of settings of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 53 of file GHOST_DisplayManagerSDL.cpp.
References GHOST_ASSERT, and GHOST_kSuccess.
GHOST_TSuccess GHOST_DisplayManagerSDL::setCurrentDisplaySetting (GHOST_TUns8 display, const GHOST_DisplaySetting & setting) [virtual]
Changes the current setting for this display device. The setting given to this method is matched againts the available diplay settings. The best match is activated (
See also:
findMatch()).
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
setting The setting of the display device to be matched and activated.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 115 of file GHOST_DisplayManagerSDL.cpp.
References GHOST_WindowManager::getActiveWindow(), GHOST_WindowSDL::getSDLWindow(), GHOST_System::getWindowManager(), GHOST_kFailure, GHOST_kSuccess, ghost_mode_to_sdl(), i, GHOST_DisplaySetting::xPixels, and GHOST_DisplaySetting::yPixels.
The documentation for this class was generated from the following files:
GHOST_DisplayManagerSDL.h
GHOST_DisplayManagerSDL.cpp