Blender: rna_boid.c File Reference
rna_boid.c File Reference
RNA
#include <float.h>
#include <limits.h>
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_scene_types.h"
#include "DNA_boid_types.h"
#include "DNA_object_types.h"
#include "DNA_particle_types.h"
#include "WM_api.h"
#include "WM_types.h"
Functions
static void rna_def_boidrule_goal (BlenderRNA *brna)
static void rna_def_boidrule_avoid (BlenderRNA *brna)
static void rna_def_boidrule_avoid_collision (BlenderRNA *brna)
static void rna_def_boidrule_follow_leader (BlenderRNA *brna)
static void rna_def_boidrule_average_speed (BlenderRNA *brna)
static void rna_def_boidrule_fight (BlenderRNA *brna)
static void rna_def_boidrule (BlenderRNA *brna)
static void rna_def_boidstate (BlenderRNA *brna)
static void rna_def_boid_settings (BlenderRNA *brna)
void RNA_def_boid (BlenderRNA *brna)
Variables
EnumPropertyItem boidrule_type_items []
EnumPropertyItem boidruleset_type_items []
Detailed Description
Definition in file rna_boid.c.
Function Documentation
void RNA_def_boid (BlenderRNA * brna)
Definition at line 655 of file rna_boid.c.
References rna_def_boid_settings(), rna_def_boidrule(), and rna_def_boidstate().
static void rna_def_boid_settings (BlenderRNA * brna) [static]
Definition at line 497 of file rna_boid.c.
References BOID_ALLOW_CLIMB, BOID_ALLOW_FLIGHT, BOID_ALLOW_LAND, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_pointer_funcs(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), and RNA_def_struct_ui_text().
Referenced by RNA_def_boid().
static void rna_def_boidrule (BlenderRNA * brna) [static]
Definition at line 403 of file rna_boid.c.
References BOIDRULE_IN_AIR, BOIDRULE_ON_LAND, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_STRING, rna_def_boidrule_average_speed(), rna_def_boidrule_avoid(), rna_def_boidrule_avoid_collision(), rna_def_boidrule_fight(), rna_def_boidrule_follow_leader(), rna_def_boidrule_goal(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_refine_func(), and RNA_def_struct_ui_text().
Referenced by RNA_def_boid().
static void rna_def_boidrule_average_speed (BlenderRNA * brna) [static]
Definition at line 360 of file rna_boid.c.
References PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by rna_def_boidrule().
static void rna_def_boidrule_avoid (BlenderRNA * brna) [static]
Definition at line 279 of file rna_boid.c.
References BRULE_GOAL_AVOID_PREDICT, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_boidrule().
static void rna_def_boidrule_avoid_collision (BlenderRNA * brna) [static]
Definition at line 305 of file rna_boid.c.
References BRULE_ACOLL_WITH_BOIDS, BRULE_ACOLL_WITH_DEFLECTORS, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by rna_def_boidrule().
static void rna_def_boidrule_fight (BlenderRNA * brna) [static]
Definition at line 384 of file rna_boid.c.
References PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by rna_def_boidrule().
static void rna_def_boidrule_follow_leader (BlenderRNA * brna) [static]
Definition at line 329 of file rna_boid.c.
References BRULE_LEADER_IN_LINE, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by rna_def_boidrule().
static void rna_def_boidrule_goal (BlenderRNA * brna) [static]
Definition at line 258 of file rna_boid.c.
References BRULE_GOAL_AVOID_PREDICT, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_boidrule().
static void rna_def_boidstate (BlenderRNA * brna) [static]
Definition at line 450 of file rna_boid.c.
References NULL, PROP_COLLECTION, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_pointer_funcs(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), and RNA_def_struct_ui_text().
Referenced by RNA_def_boid().
Variable Documentation
EnumPropertyItem boidrule_type_items[]
Initial value:
 {
    {eBoidRuleType_Goal, "GOAL", 0, "Goal", "Go to assigned object or loudest assigned signal source"},
    {eBoidRuleType_Avoid, "AVOID", 0, "Avoid", "Get away from assigned object or loudest assigned signal source"},
    {eBoidRuleType_AvoidCollision, "AVOID_COLLISION", 0, "Avoid Collision",
                                   "Manoeuvre to avoid collisions with other boids and deflector objects in "
                                   "near future"},
    {eBoidRuleType_Separate, "SEPARATE", 0, "Separate", "Keep from going through other boids"},
    {eBoidRuleType_Flock, "FLOCK", 0, "Flock", "Move to center of neighbors and match their velocity"},
    {eBoidRuleType_FollowLeader, "FOLLOW_LEADER", 0, "Follow Leader", "Follow a boid or assigned object"},
    {eBoidRuleType_AverageSpeed, "AVERAGE_SPEED", 0, "Average Speed", "Maintain speed, flight level or wander"},
    {eBoidRuleType_Fight, "FIGHT", 0, "Fight", "Go to closest enemy and attack when in range"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 49 of file rna_boid.c.
Referenced by boid_new_rule(), and BOID_OT_rule_add().
EnumPropertyItem boidruleset_type_items[]
Initial value:
 {
    {eBoidRulesetType_Fuzzy, "FUZZY", 0, "Fuzzy",
                             "Rules are gone through top to bottom (only the first rule which effect is above "
                             "fuzziness threshold is evaluated)"},
    {eBoidRulesetType_Random, "RANDOM", 0, "Random", "A random rule is selected for each boid"},
    {eBoidRulesetType_Average, "AVERAGE", 0, "Average", "All rules are averaged"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 70 of file rna_boid.c.