Blender: MOD_particlesystem.c File Reference
MOD_particlesystem.c File Reference
modifiers
#include <stddef.h>
#include "DNA_material_types.h"
#include "BLI_utildefines.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_material.h"
#include "BKE_modifier.h"
#include "BKE_particle.h"
#include "MOD_util.h"
Functions
static void initData (ModifierData *md)
static void freeData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static CustomDataMask requiredDataMask (Object *UNUSED(ob), ModifierData *md)
static void deformVerts (ModifierData *md, Object *ob, DerivedMesh *derivedData, float(*vertexCos)[3], int UNUSED(numVerts), int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
Variables
ModifierTypeInfo modifierType_ParticleSystem
Detailed Description
Definition in file MOD_particlesystem.c.
Function Documentation
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 73 of file MOD_particlesystem.c.
References ParticleSystemModifierData::dm, ParticleSystemModifierData::flag, NULL, ParticleSystemModifierData::psys, ParticleSystemModifierData::totdmedge, ParticleSystemModifierData::totdmface, and ParticleSystemModifierData::totdmvert.
static void deformVerts (ModifierData * md, Object * ob, DerivedMesh * derivedData, float(*) vertexCos[3], int UNUSEDnumVerts, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 123 of file MOD_particlesystem.c.
References CDDM_apply_vert_coords(), CDDM_calc_normals(), CDDM_copy(), ParticleSystemModifierData::dm, eParticleSystemFlag_file_loaded, eParticleSystemFlag_psys_updated, ListBase::first, ParticleSystemModifierData::flag, get_dm(), DerivedMesh::getNumEdges, DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, DerivedMesh::needsFree, NULL, particle_system_update(), Object::particlesystem, ParticleSystemModifierData::psys, psys_check_enabled(), PSYS_RECALC_RESET, ParticleSystem::recalc, DerivedMesh::release, ModifierData::scene, ParticleSystemModifierData::totdmedge, ParticleSystemModifierData::totdmface, and ParticleSystemModifierData::totdmvert.
static void freeData (ModifierData * md) [static]
Definition at line 58 of file MOD_particlesystem.c.
References ParticleSystemModifierData::dm, ParticleSystem::flag, DerivedMesh::needsFree, NULL, ParticleSystemModifierData::psys, PSYS_DELETE, and DerivedMesh::release.
static void initData (ModifierData * md) [static]
Definition at line 51 of file MOD_particlesystem.c.
References ParticleSystemModifierData::dm, NULL, ParticleSystemModifierData::psys, ParticleSystemModifierData::totdmedge, ParticleSystemModifierData::totdmface, and ParticleSystemModifierData::totdmvert.
static CustomDataMask requiredDataMask (Object * UNUSEDob, ModifierData * md) [static]
Definition at line 86 of file MOD_particlesystem.c.
References CD_MASK_MDEFORMVERT, CD_MASK_MTFACE, CD_MASK_ORCO, CD_MASK_ORIGINDEX, CD_MASK_ORIGSPACE_MLOOP, i, MTex::mapto, MAX_MTEX, ParticleSettings::mtex, ParticleSystem::part, ParticleSystemModifierData::psys, PSYS_TOT_VG, ParticleSettings::tanfac, MTex::texco, TEXCO_UV, and ParticleSystem::vgroup.
Variable Documentation
ModifierTypeInfo modifierType_ParticleSystem
Initial value:
 {
                  "ParticleSystem",
            "ParticleSystemModifierData",
            sizeof(ParticleSystemModifierData),
                  eModifierTypeType_OnlyDeform,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_SupportsMapping
                            | eModifierTypeFlag_UsesPointCache ,
              copyData,
           deformVerts,
         NULL  ,
        NULL,
      NULL,
         NULL,
       NULL,
              initData,
      requiredDataMask,
              freeData,
            NULL,
        NULL,
         NULL,
        NULL,
     NULL,
         NULL,
        NULL,
}
Definition at line 216 of file MOD_particlesystem.c.