Blender: idprop_py_api.h File Reference
idprop_py_api.h File Reference
Python Generic
Classes
struct BPy_IDProperty
struct BPy_IDArray
struct BPy_IDGroup_Iter
Defines
#define IDPROP_ITER_KEYS 0
#define IDPROP_ITER_ITEMS 1
Typedefs
typedef struct BPy_IDProperty BPy_IDProperty
typedef struct BPy_IDArray BPy_IDArray
typedef struct BPy_IDGroup_Iter BPy_IDGroup_Iter
Functions
PyObject * BPy_Wrap_GetKeys (struct IDProperty *prop)
PyObject * BPy_Wrap_GetValues (struct ID *id, struct IDProperty *prop)
PyObject * BPy_Wrap_GetItems (struct ID *id, struct IDProperty *prop)
int BPy_Wrap_SetMapItem (struct IDProperty *prop, PyObject *key, PyObject *val)
PyObject * BPy_IDGroup_WrapData (struct ID *id, struct IDProperty *prop, struct IDProperty *parent)
const char * BPy_IDProperty_Map_ValidateAndCreate (PyObject *key, struct IDProperty *group, PyObject *ob)
void IDProp_Init_Types (void)
PyObject * BPyInit_idprop (void)
Detailed Description
Definition in file idprop_py_api.h.
Define Documentation
#define IDPROP_ITER_ITEMS 1
Definition at line 70 of file idprop_py_api.h.
Referenced by BPy_Group_Iter_Next(), and BPy_IDGroup_IterItems().
#define IDPROP_ITER_KEYS 0
Definition at line 69 of file idprop_py_api.h.
Referenced by BPy_IDGroup_iter().
Typedef Documentation
typedef struct BPy_IDArray BPy_IDArray
typedef struct BPy_IDGroup_Iter BPy_IDGroup_Iter
typedef struct BPy_IDProperty BPy_IDProperty
Function Documentation
PyObject* BPy_IDGroup_WrapData (struct ID * id, struct IDProperty * prop, struct IDProperty * parent)
Definition at line 141 of file idprop_py_api.c.
References IDP_ARRAY, IDP_DOUBLE, IDP_FLOAT, IDP_GROUP, IDP_IDPARRAY, IDP_INT, IDP_STRING, idprop_py_from_idp_array(), idprop_py_from_idp_double(), idprop_py_from_idp_float(), idprop_py_from_idp_group(), idprop_py_from_idp_idparray(), idprop_py_from_idp_int(), idprop_py_from_idp_string(), and IDProperty::type.
Referenced by BPy_Group_Iter_Next(), BPy_IDGroup_Get(), BPy_IDGroup_Map_GetItem(), BPy_Wrap_GetItems(), BPy_Wrap_GetValues(), idprop_py_from_idp_idparray(), pyrna_struct_get(), and pyrna_struct_subscript().
const char* BPy_IDProperty_Map_ValidateAndCreate (PyObject * key, struct IDProperty * group, PyObject * ob)
Definition at line 344 of file idprop_py_api.c.
References IDPropertyTemplate::array, BPy_IDProperty_Map_ValidateAndCreate(), IDPropertyTemplate::d, error(), IDPropertyTemplate::i, i, IDP_AppendArray(), IDP_ARRAY, IDP_Array, IDP_DOUBLE, IDP_FreeProperty(), IDP_GROUP, IDP_IDPARRAY, IDP_INT, IDP_New(), IDP_NewIDPArray(), IDP_ReplaceInGroup(), idp_sequence_type(), IDP_STRING, IDP_STRING_SUB_BYTE, IDP_STRING_SUB_UTF8, len(), IDPropertyTemplate::len, MAX_IDPROP_NAME, MEM_freeN(), NULL, PyC_UnicodeAsByte(), IDPropertyTemplate::str, IDPropertyTemplate::string, IDPropertyTemplate::subtype, IDProperty::type, and IDPropertyTemplate::type.
Referenced by BPy_IDProperty_Map_ValidateAndCreate(), and BPy_Wrap_SetMapItem().
PyObject* BPy_Wrap_GetItems (struct ID * id, struct IDProperty * prop)
Definition at line 747 of file idprop_py_api.c.
References BPy_IDGroup_CorrectListLen(), BPy_IDGroup_WrapData(), BPy_Wrap_GetItems(), IDProperty::data, ListBase::first, IDPropertyData::group, i, IDProperty::len, IDProperty::name, and IDProperty::next.
Referenced by BPy_IDGroup_GetItems(), BPy_Wrap_GetItems(), and pyrna_struct_items().
PyObject* BPy_Wrap_GetKeys (struct IDProperty * prop)
Definition at line 703 of file idprop_py_api.c.
References BPy_IDGroup_CorrectListLen(), BPy_Wrap_GetKeys(), IDProperty::data, ListBase::first, IDPropertyData::group, i, len(), IDProperty::len, IDProperty::name, and IDProperty::next.
Referenced by BPy_IDGroup_GetKeys(), BPy_Wrap_GetKeys(), and pyrna_struct_keys().
PyObject* BPy_Wrap_GetValues (struct ID * id, struct IDProperty * prop)
Definition at line 727 of file idprop_py_api.c.
References BPy_IDGroup_CorrectListLen(), BPy_IDGroup_WrapData(), BPy_Wrap_GetValues(), IDProperty::data, ListBase::first, IDPropertyData::group, i, IDProperty::len, and IDProperty::next.
Referenced by BPy_IDGroup_GetValues(), BPy_Wrap_GetValues(), and pyrna_struct_values().
int BPy_Wrap_SetMapItem (struct IDProperty * prop, PyObject * key, PyObject * val)
Definition at line 484 of file idprop_py_api.c.
References BPy_IDProperty_Map_ValidateAndCreate(), err, IDP_FreeProperty(), IDP_GetPropertyFromGroup(), IDP_GROUP, IDP_RemFromGroup(), MEM_freeN(), NULL, and IDProperty::type.
Referenced by BPy_IDGroup_Map_SetItem(), and pyrna_struct_ass_subscript().
PyObject* BPyInit_idprop (void)
Definition at line 1471 of file idprop_py_api.c.
References BPyInit_idprop_types(), and mod().
void IDProp_Init_Types (void)
Definition at line 1407 of file idprop_py_api.c.
Referenced by BPy_init_modules().