Blender: util.c File Reference
util.c File Reference
IMage Buffer
#include "BLI_blenlib.h"
#include "DNA_userdef_types.h"
#include "BKE_global.h"
#include "imbuf.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_filetype.h"
#include "IMB_anim.h"
Defines
#define UTIL_DEBUG 0
Functions
static int IMB_ispic_name (const char *name)
int IMB_ispic (const char *filename)
static int isavi (const char *name)
int imb_get_anim_type (const char *name)
int IMB_isanim (const char *filename)
Variables
const char * imb_ext_image []
const char * imb_ext_image_qt []
const char * imb_ext_movie []
const char * imb_ext_audio []
Detailed Description
Definition in file source/blender/imbuf/intern/util.c.
Define Documentation
#define UTIL_DEBUG 0
Definition at line 68 of file source/blender/imbuf/intern/util.c.
Referenced by imb_get_anim_type(), and IMB_ispic_name().
Function Documentation
int imb_get_anim_type (const char * name)
Attention:
Defined in util.c
Definition at line 327 of file source/blender/imbuf/intern/util.c.
References ANIM_AVI, ANIM_FFMPEG, ANIM_MOVIE, ANIM_NONE, ANIM_QTIME, ANIM_REDCODE, ANIM_SEQUENCE, IMB_ispic(), isavi(), ismovie(), and UTIL_DEBUG.
Referenced by anim_getnew(), and IMB_isanim().
int IMB_isanim (const char * name)
Attention:
Defined in util.c
Definition at line 372 of file source/blender/imbuf/intern/util.c.
References ANIM_SEQUENCE, BLI_testextensie(), FALSE, G, imb_get_anim_type(), and USER_FILTERFILEEXTS.
int IMB_ispic (const char * name)
Attention:
Defined in util.c
Definition at line 183 of file source/blender/imbuf/intern/util.c.
References BLI_testextensie_array(), FALSE, G, imb_ext_image, imb_ext_image_qt, IMB_ispic_name(), and USER_FILTERFILEEXTS.
Referenced by imb_get_anim_type(), and ispic().
static int IMB_ispic_name (const char * name) [static]
Definition at line 149 of file source/blender/imbuf/intern/util.c.
References BIG_LONG, BLI_open(), FALSE, ImFileType::filetype, IMB_FILE_TYPES, ImFileType::is_a, JPG, O_BINARY, and UTIL_DEBUG.
Referenced by IMB_ispic().
static int isavi (const char * name) [static]
Definition at line 202 of file source/blender/imbuf/intern/util.c.
References AVI_is_avi().
Referenced by imb_get_anim_type().
Variable Documentation
const char* imb_ext_audio[]
Initial value:
 {
    ".wav",
    ".ogg",
    ".oga",
    ".mp3",
    ".mp2",
    ".ac3",
    ".aac",
    ".flac",
    ".wma",
    ".eac3",
    ".aif",
    ".aiff",
    ".m4a",
    NULL}
Definition at line 133 of file source/blender/imbuf/intern/util.c.
Referenced by file_extension_type().
const char* imb_ext_image[]
Initial value:
 {
    ".png",
    ".tga",
    ".bmp",
    ".jpg", ".jpeg",
    ".sgi", ".rgb", ".rgba",
    NULL}
Definition at line 70 of file source/blender/imbuf/intern/util.c.
Referenced by BKE_add_image_extension(), file_extension_type(), and IMB_ispic().
const char* imb_ext_image_qt[]
Initial value:
 {
    ".gif",
    ".psd",
    ".pct", ".pict",
    ".pntg",
    ".qtif",
    NULL}
Definition at line 97 of file source/blender/imbuf/intern/util.c.
Referenced by BKE_add_image_extension(), file_extension_type(), and IMB_ispic().
const char* imb_ext_movie[]
Initial value:
 {
    ".avi",
    ".flc",
    ".mov",
    ".movie",
    ".mp4",
    ".m4v",
    ".m2v",
    ".m2t",
    ".m2ts",
    ".mts",
    ".mv",
    ".avs",
    ".wmv",
    ".ogv",
    ".dv",
    ".mpeg",
    ".mpg",
    ".mpg2",
    ".vob",
    ".mkv",
    ".flv",
    ".divx",
    ".xvid",
    ".mxf",
    NULL}
Definition at line 105 of file source/blender/imbuf/intern/util.c.
Referenced by BKE_add_image_file(), BKE_add_movieclip_file(), BKE_movieclip_reload(), file_extension_type(), and image_replace_exec().