Blender: filter.c File Reference
filter.c File Reference
IMage Buffer
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_filter.h"
#include "imbuf.h"
Functions
static void filtrow (unsigned char *point, int x)
static void filtrowf (float *point, int x)
static void filtcolum (unsigned char *point, int y, int skip)
static void filtcolumf (float *point, int y, int skip)
void IMB_filtery (struct ImBuf *ibuf)
void imb_filterx (struct ImBuf *ibuf)
void IMB_filterN (ImBuf *out, ImBuf *in)
void IMB_filter (struct ImBuf *ibuf)
void IMB_mask_filter_extend (char *mask, int width, int height)
void IMB_mask_clear (ImBuf *ibuf, char *mask, int val)
static int filter_make_index (const int x, const int y, const int w, const int h)
static int check_pixel_assigned (const void *buffer, const char *mask, const int index, const int depth, const int is_float)
void IMB_filter_extend (struct ImBuf *ibuf, char *mask, int filter)
void IMB_remakemipmap (ImBuf *ibuf, int use_filter)
void IMB_makemipmap (ImBuf *ibuf, int use_filter)
ImBuf * IMB_getmipmap (ImBuf *ibuf, int level)
void IMB_premultiply_rect (unsigned int *rect, char planes, int w, int h)
void IMB_premultiply_rect_float (float *rect_float, char planes, int w, int h)
void IMB_premultiply_alpha (ImBuf *ibuf)
Detailed Description
Definition in file filter.c.
Function Documentation
static int check_pixel_assigned (const void * buffer, const char * mask, const int index, const int depth, const int is_float) [static]
Definition at line 337 of file filter.c.
References NULL.
Referenced by IMB_filter_extend().
static void filtcolum (unsigned char * point, int y, int skip) [static]
Definition at line 93 of file filter.c.
References error().
Referenced by IMB_filtery().
static void filtcolumf (float * point, int y, int skip) [static]
Definition at line 116 of file filter.c.
Referenced by IMB_filtery().
static int filter_make_index (const int x, const int y, const int w, const int h) [static]
Definition at line 331 of file filter.c.
Referenced by IMB_filter_extend().
static void filtrow (unsigned char * point, int x) [static]
Definition at line 53 of file filter.c.
References error().
Referenced by imb_filterx().
static void filtrowf (float * point, int x) [static]
Definition at line 73 of file filter.c.
Referenced by imb_filterx().
void IMB_filter (struct ImBuf * ibuf)
Definition at line 259 of file filter.c.
References imb_filterx(), and IMB_filtery().
void IMB_filter_extend (struct ImBuf * ibuf, char * mask, int filter)
Definition at line 360 of file filter.c.
References check_pixel_assigned(), filter(), filter_make_index(), FILTER_MASK_MARGIN, i, MEM_dupallocN(), MEM_freeN(), NULL, ImBuf::rect, ImBuf::rect_float, sqrt(), ImBuf::x, and ImBuf::y.
Referenced by RE_bake_ibuf_filter().
void IMB_filterN (ImBuf * out, ImBuf * in)
Definition at line 211 of file filter.c.
References ImBuf::rect, ImBuf::x, and ImBuf::y.
Referenced by IMB_makemipmap(), and IMB_remakemipmap().
void imb_filterx (struct ImBuf * ibuf)
Definition at line 174 of file filter.c.
References filtrow(), filtrowf(), ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by IMB_double_x(), and IMB_filter().
void IMB_filtery (struct ImBuf * ibuf)
Attention:
Defined in filter.c
Definition at line 136 of file filter.c.
References filtcolum(), filtcolumf(), ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by avi_fetchibuf(), IMB_anim_absolute(), IMB_double_y(), IMB_filter(), and input_preprocess().
ImBuf* IMB_getmipmap (ImBuf * ibuf, int level) [read]
Definition at line 531 of file filter.c.
References CLAMP(), ImBuf::mipmap, and ImBuf::miptot.
Referenced by IMB_tiles_to_rect().
void IMB_makemipmap (ImBuf * ibuf, int use_filter)
Definition at line 501 of file filter.c.
References IB_MIPMAP_LEVELS, IB_rect, IMB_allocImBuf(), IMB_filterN(), IMB_freeImBuf(), imb_freemipmapImBuf(), IMB_onehalf(), ImBuf::miplevel, ImBuf::mipmap, ImBuf::miptot, ImBuf::x, and ImBuf::y.
Referenced by draw_bgpic(), and image_mipmap_test().
void IMB_mask_clear (ImBuf * ibuf, char * mask, int val)
Definition at line 305 of file filter.c.
References ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
void IMB_mask_filter_extend (char * mask, int width, int height)
Definition at line 265 of file filter.c.
References FILTER_MASK_MARGIN, MEM_dupallocN(), and MEM_freeN().
void IMB_premultiply_alpha (ImBuf * ibuf)
Definition at line 589 of file filter.c.
References IMB_premultiply_rect(), IMB_premultiply_rect_float(), NULL, ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by IMB_ibImageFromMemory(), imb_read_tiff_pixels(), and input_preprocess().
void IMB_premultiply_rect (unsigned int * rect, char planes, int w, int h)
Definition at line 537 of file filter.c.
Referenced by imb_loadtiletiff(), and IMB_premultiply_alpha().
void IMB_premultiply_rect_float (float * rect_float, char planes, int w, int h)
Definition at line 563 of file filter.c.
Referenced by IMB_premultiply_alpha().
void IMB_remakemipmap (ImBuf * ibuf, int use_filter)
Definition at line 467 of file filter.c.
References IB_MIPMAP_LEVELS, IB_rect, IMB_allocImBuf(), IMB_filterN(), IMB_freeImBuf(), imb_onehalf_no_alloc(), ImBuf::miplevel, ImBuf::mipmap, ImBuf::miptot, ImBuf::x, and ImBuf::y.
Referenced by draw_bgpic(), and image_mipmap_test().