Blender: BIF_generate.h File Reference
BIF_generate.h File Reference
armature
Typedefs
typedef int(NextSubdivisionFunc)(struct ToolSettings *, struct BArcIterator *, int, int, float[3], float[3])
Functions
float calcArcCorrelation (struct BArcIterator *iter, int start, int end, float v0[3], float n[3])
int nextFixedSubdivision (struct ToolSettings *toolsettings, struct BArcIterator *iter, int start, int end, float head[3], float p[3])
int nextLengthSubdivision (struct ToolSettings *toolsettings, struct BArcIterator *iter, int start, int end, float head[3], float p[3])
int nextAdaptativeSubdivision (struct ToolSettings *toolsettings, struct BArcIterator *iter, int start, int end, float head[3], float p[3])
struct EditBone * subdivideArcBy (struct ToolSettings *toolsettings, struct bArmature *arm, ListBase *editbones, struct BArcIterator *iter, float invmat[][4], float tmat[][3], NextSubdivisionFunc next_subdividion)
void setBoneRollFromNormal (struct EditBone *bone, float *no, float invmat[][4], float tmat[][3])
Detailed Description
Definition in file BIF_generate.h.
Typedef Documentation
typedef int(NextSubdivisionFunc)(struct ToolSettings *, struct BArcIterator *, int, int, float[3], float[3])
Definition at line 35 of file BIF_generate.h.
Function Documentation
float calcArcCorrelation (struct BArcIterator * iter, int start, int end, float v0[3], float n[3])
Definition at line 66 of file editarmature_generate.c.
References abs(), dot_v3v3(), i, IT_peek(), len(), len_v3(), BArcIterator::p, project_v3_v3v3(), sub_v3_v3(), and sub_v3_v3v3().
Referenced by nextAdaptativeSubdivision(), and sk_getSegments().
int nextAdaptativeSubdivision (struct ToolSettings * toolsettings, struct BArcIterator * iter, int start, int end, float head[3], float p[3])
Definition at line 176 of file editarmature_generate.c.
References calcArcCorrelation(), copy_v3_v3(), i, IT_peek(), BArcIterator::p, ToolSettings::skgen_correlation_limit, and sub_v3_v3v3().
Referenced by sk_convertStroke(), and sk_drawStrokeSubdivision().
int nextFixedSubdivision (struct ToolSettings * toolsettings, struct BArcIterator * iter, int start, int end, float head[3], float p[3])
Referenced by sk_convertStroke(), and sk_drawStrokeSubdivision().
int nextLengthSubdivision (struct ToolSettings * toolsettings, struct BArcIterator * iter, int start, int end, float head[3], float p[3])
Definition at line 202 of file editarmature_generate.c.
References add_v3_v3(), copy_v3_v3(), dot_v3v3(), i, isnan(), IT_peek(), len_v3v3(), mul_v3_fl(), normalize_v3(), BArcIterator::p, ToolSettings::skgen_length_limit, sqrt(), and sub_v3_v3v3().
Referenced by sk_convertStroke(), and sk_drawStrokeSubdivision().
void setBoneRollFromNormal (struct EditBone * bone, float * no, float invmat[][4], float tmat[][3])
Referenced by sk_convertStroke(), and subdivideArcBy().
struct EditBone* subdivideArcBy (struct ToolSettings * toolsettings, struct bArmature * arm, ListBase * editbones, struct BArcIterator * iter, float invmat[][4], float tmat[][3], NextSubdivisionFunc next_subdividion) [read]
Referenced by sk_convertStroke().