Blender: CTR_UHeapable Class Reference
CTR_UHeapable Class Reference
#include <CTR_UHeap.h>
Public Member Functions
int & HeapPos ()
float & HeapKey ()
const float & HeapKey () const
const int & HeapPos () const
Protected Member Functions
CTR_UHeapable ()
~CTR_UHeapable ()
Detailed Description
Definition at line 54 of file CTR_UHeap.h.
Constructor & Destructor Documentation
CTR_UHeapable::CTR_UHeapable () [inline, protected]
Definition at line 89 of file CTR_UHeap.h.
CTR_UHeapable::~CTR_UHeapable () [inline, protected]
Definition at line 95 of file CTR_UHeap.h.
Member Function Documentation
float& CTR_UHeapable::HeapKey () [inline]
Definition at line 63 of file CTR_UHeap.h.
Referenced by LOD_QuadricEditor::BuildQuadrics(), LOD_QuadricEditor::ComputeEdgeCosts(), LOD_NdQuadricEditor::InitializeHeapKeys(), and CTR_UHeap< LOD_Edge >::SC_Heap().
const float& CTR_UHeapable::HeapKey () const [inline]
Definition at line 70 of file CTR_UHeap.h.
const int& CTR_UHeapable::HeapPos () const [inline]
Definition at line 77 of file CTR_UHeap.h.
int& CTR_UHeapable::HeapPos () [inline]
Definition at line 58 of file CTR_UHeap.h.
Referenced by CTR_UHeap< LOD_Edge >::SC_Heap().
The documentation for this class was generated from the following file:
CTR_UHeap.h