Blender: AUD_Reference< T > Class Template Reference
AUD_Reference< T > Class Template Reference
#include <AUD_Reference.h>
Public Member Functions
template<class U >
AUD_Reference (U *reference)
AUD_Reference ()
AUD_Reference (const AUD_Reference &ref)
template<class U >
AUD_Reference (const AUD_Reference< U > &ref)
~AUD_Reference ()
AUD_Reference & operator= (const AUD_Reference &ref)
bool isNull () const
T * get () const
void * getOriginal () const
T & operator* () const
T * operator-> () const
Detailed Description
template<class T>
class AUD_Reference< T >
This class provides reference counting functionality.
Definition at line 97 of file AUD_Reference.h.
Constructor & Destructor Documentation
template<class T> template<class U > AUD_Reference< T >::AUD_Reference (U * reference) [inline]
Creates a new reference counter.
Parameters:
reference The reference.
Definition at line 109 of file AUD_Reference.h.
template<class T> AUD_Reference< T >::AUD_Reference () [inline]
Definition at line 120 of file AUD_Reference.h.
template<class T> AUD_Reference< T >::AUD_Reference (const AUD_Reference< T > & ref) [inline]
Copies an AUD_Reference object.
Parameters:
ref The AUD_Reference object to copy.
Definition at line 130 of file AUD_Reference.h.
template<class T> template<class U > AUD_Reference< T >::AUD_Reference (const AUD_Reference< U > & ref) [inline, explicit]
Definition at line 142 of file AUD_Reference.h.
template<class T> AUD_Reference< T >::~AUD_Reference () [inline]
Destroys a AUD_Reference object, if there's no furthere reference on the reference, it is destroyed as well.
Definition at line 157 of file AUD_Reference.h.
Member Function Documentation
template<class T> T* AUD_Reference< T >::get () const [inline]
Returns the reference.
Definition at line 205 of file AUD_Reference.h.
Referenced by AUD_addSequence(), AUD_doesPlayback(), AUD_getSequencerPosition(), AUD_init(), AUD_mixdown(), AUD_openMixdownDevice(), AUD_Reference< AUD_PitchReader >::AUD_Reference(), AUD_removeSequence(), AUD_seekSequencer(), AUD_setSequencerAnimData(), AUD_setSequencerDeviceSpecs(), AUD_setSequencerFPS(), AUD_setSequencerMuted(), AUD_setSequencerSpecs(), AUD_startPlayback(), AUD_stopPlayback(), AUD_updateSequencerData(), AUD_SequencerEntry::setSound(), and AUD_SequencerHandle::update().
template<class T> void* AUD_Reference< T >::getOriginal () const [inline]
Returns the original pointer.
Definition at line 213 of file AUD_Reference.h.
Referenced by operator!=(), and operator==().
template<class T> bool AUD_Reference< T >::isNull () const [inline]
Returns whether the reference is NULL.
Definition at line 197 of file AUD_Reference.h.
Referenced by AUD_getInfo(), AUD_init(), AUD_openMixdownDevice(), AUD_pauseAfter(), AUD_play(), AUD_playDevice(), AUD_readSoundBuffer(), AUD_SequencerHandle::AUD_SequencerHandle(), AUD_setAttenuation(), AUD_setConeAngleInner(), AUD_setConeAngleOuter(), AUD_setConeVolumeOuter(), AUD_setDistanceMaximum(), AUD_setDistanceReference(), AUD_setRelative(), AUD_setSourceLocation(), AUD_setSourceOrientation(), AUD_setSourceVelocity(), AUD_setVolumeMaximum(), AUD_setVolumeMinimum(), AUD_FFMPEGFactory::createReader(), AUD_SndFileFactory::createReader(), AUD_FileFactory::createReader(), AUD_SoftwareDevice::play(), AUD_SequencerHandle::seek(), AUD_SequencerHandle::stop(), KX_SoundActuator::Update(), AUD_SequencerHandle::update(), and KX_SoundActuator::~KX_SoundActuator().
template<class T> T& AUD_Reference< T >::operator* () const [inline]
Returns the reference.
Definition at line 221 of file AUD_Reference.h.
template<class T> T* AUD_Reference< T >::operator-> () const [inline]
Returns the reference.
Definition at line 229 of file AUD_Reference.h.
template<class T> AUD_Reference& AUD_Reference< T >::operator= (const AUD_Reference< T > & ref) [inline]
Assigns an AUD_Reference to this object.
Parameters:
ref The AUD_Reference object to assign.
Definition at line 171 of file AUD_Reference.h.
The documentation for this class was generated from the following file:
AUD_Reference.h