Blender: IK_QSwingSegment Class Reference
IK_QSwingSegment Class Reference
#include <IK_QSegment.h>
Public Member Functions
IK_QSwingSegment ()
MT_Vector3 Axis (int dof) const
bool UpdateAngle (const IK_QJacobian &jacobian, MT_Vector3 &delta, bool *clamp)
void Lock (int dof, IK_QJacobian &jacobian, MT_Vector3 &delta)
void UpdateAngleApply ()
void SetLimit (int axis, MT_Scalar lmin, MT_Scalar lmax)
void SetWeight (int axis, MT_Scalar weight)
void SetBasis (const MT_Matrix3x3 &basis)
Detailed Description
Definition at line 274 of file IK_QSegment.h.
Constructor & Destructor Documentation
IK_QSwingSegment::IK_QSwingSegment ()
Definition at line 636 of file IK_QSegment.cpp.
Member Function Documentation
MT_Vector3 IK_QSwingSegment::Axis (int dof) const [virtual]
Implements IK_QSegment.
Definition at line 647 of file IK_QSegment.cpp.
References MT_Transform::getBasis(), MT_Matrix3x3::getColumn(), and IK_QSegment::m_global_transform.
void IK_QSwingSegment::Lock (int dof, IK_QJacobian & jacobian, MT_Vector3 & delta) [virtual]
Reimplemented from IK_QSegment.
Definition at line 740 of file IK_QSegment.cpp.
References IK_QJacobian::Lock(), IK_QSegment::m_DoF_id, and IK_QSegment::m_locked.
void IK_QSwingSegment::SetBasis (const MT_Matrix3x3 & basis) [virtual]
Reimplemented from IK_QSegment.
Definition at line 641 of file IK_QSegment.cpp.
References IK_QSegment::m_basis, and RemoveTwist().
void IK_QSwingSegment::SetLimit (int axis, MT_Scalar lmin, MT_Scalar lmax) [virtual]
Reimplemented from IK_QSegment.
Definition at line 752 of file IK_QSegment.cpp.
References MT_clamp(), MT_PI(), and sin().
void IK_QSwingSegment::SetWeight (int axis, MT_Scalar weight) [virtual]
Reimplemented from IK_QSegment.
Definition at line 786 of file IK_QSegment.cpp.
References IK_QSegment::m_weight.
bool IK_QSwingSegment::UpdateAngle (const IK_QJacobian & jacobian, MT_Vector3 & delta, bool * clamp) [virtual]
Implements IK_QSegment.
Definition at line 652 of file IK_QSegment.cpp.
References IK_QJacobian::AngleUpdate(), ComputeSwingMatrix(), cos(), EllipseClamp(), MT_Vector3::length(), M, IK_QSegment::m_basis, IK_QSegment::m_DoF_id, IK_QSegment::m_locked, MatrixToAxisAngle(), MT_fuzzyZero(), RemoveTwist(), sin(), SphericalRangeParameters(), MT_Matrix3x3::transposed(), MT_Tuple3::x(), MT_Tuple3::y(), and MT_Tuple3::z().
void IK_QSwingSegment::UpdateAngleApply () [virtual]
Implements IK_QSegment.
Definition at line 747 of file IK_QSegment.cpp.
References IK_QSegment::m_basis.
The documentation for this class was generated from the following files:
IK_QSegment.h
IK_QSegment.cpp