Blender: btSoftColliders::CollideVF_SS Struct Reference
btSoftColliders::CollideVF_SS Struct Reference
#include <btSoftBodyInternals.h>
Public Member Functions
void Process (const btDbvtNode *lnode, const btDbvtNode *lface)
Public Attributes
btSoftBody * psb [2]
btScalar mrg
Detailed Description
Definition at line 882 of file btSoftBodyInternals.h.
Member Function Documentation
void btSoftColliders::CollideVF_SS::Process (const btDbvtNode * lnode, const btDbvtNode * lface) [inline]
Reimplemented from btDbvt::ICollide.
Definition at line 884 of file btSoftBodyInternals.h.
References BaryCoord(), BaryEval(), btMax(), btSqrt(), btDbvtNode::data, length(), btSoftBody::SContact::m_cfm, btSoftBody::SContact::m_face, btSoftBody::SContact::m_friction, btSoftBody::Node::m_im, btSoftBody::SContact::m_margin, btSoftBody::Node::m_n, btSoftBody::SContact::m_node, btSoftBody::SContact::m_normal, btSoftBody::Node::m_q, btSoftBody::SContact::m_weights, btSoftBody::Node::m_x, p, ProjectOrigin(), and SIMD_INFINITY.
Member Data Documentation
btScalar btSoftColliders::CollideVF_SS::mrg
Definition at line 926 of file btSoftBodyInternals.h.
Referenced by btSoftBody::defaultCollisionHandler().
btSoftBody* btSoftColliders::CollideVF_SS::psb[2]
Definition at line 925 of file btSoftBodyInternals.h.
Referenced by btSoftBody::defaultCollisionHandler().
The documentation for this struct was generated from the following file:
btSoftBodyInternals.h