Blender: UI_view2d.h File Reference
UI_view2d.h File Reference
Interface and Widgets
Defines
#define V2D_IS_CLIPPED 12000
#define V2D_ARG_DUMMY -1
#define V2D_SCROLL_HEIGHT 17
#define V2D_SCROLL_WIDTH 17
#define V2D_SCROLLER_HANDLE_SIZE 12
#define V2D_LOCK_SET 0
#define V2D_LOCK_COPY 1
#define IN_2D_VERT_SCROLL(v2d, co) (BLI_in_rcti(&v2d->vert, co[0], co[1]))
#define IN_2D_HORIZ_SCROLL(v2d, co) (BLI_in_rcti(&v2d->hor, co[0], co[1]))
Typedefs
typedef struct View2DGrid View2DGrid
typedef struct View2DScrollers View2DScrollers
Enumerations
enum {
V2D_COMMONVIEW_CUSTOM = -1, V2D_COMMONVIEW_STANDARD, V2D_COMMONVIEW_LIST, V2D_COMMONVIEW_STACK,
V2D_COMMONVIEW_HEADER, V2D_COMMONVIEW_PANELS_UI
}
enum {
V2D_UNIT_SECONDS = 0, V2D_UNIT_FRAMES, V2D_UNIT_FRAMESCALE, V2D_UNIT_VALUES,
V2D_UNIT_DEGREES, V2D_UNIT_TIME, V2D_UNIT_SECONDSSEQ
}
enum { V2D_GRID_NOCLAMP = 0, V2D_GRID_CLAMP }
enum {
V2D_HORIZONTAL_LINES = (1<<0), V2D_VERTICAL_LINES = (1<<1), V2D_HORIZONTAL_AXIS = (1<<2), V2D_VERTICAL_AXIS = (1<<3),
V2D_HORIZONTAL_FINELINES = (1<<4), V2D_GRIDLINES_MAJOR = (V2D_VERTICAL_LINES|V2D_VERTICAL_AXIS|V2D_HORIZONTAL_LINES|V2D_HORIZONTAL_AXIS), V2D_GRIDLINES_ALL = (V2D_GRIDLINES_MAJOR|V2D_HORIZONTAL_FINELINES)
}
Functions
void UI_view2d_region_reinit (struct View2D *v2d, short type, int winx, int winy)
void UI_view2d_curRect_validate (struct View2D *v2d)
void UI_view2d_curRect_validate_resize (struct View2D *v2d, int resize)
void UI_view2d_curRect_reset (struct View2D *v2d)
void UI_view2d_sync (struct bScreen *screen, struct ScrArea *sa, struct View2D *v2dcur, int flag)
void UI_view2d_totRect_set (struct View2D *v2d, int width, int height)
void UI_view2d_totRect_set_resize (struct View2D *v2d, int width, int height, int resize)
int UI_view2d_tab_set (struct View2D *v2d, int tab)
void UI_view2d_view_ortho (struct View2D *v2d)
void UI_view2d_view_orthoSpecial (struct ARegion *ar, struct View2D *v2d, short xaxis)
void UI_view2d_view_restore (const struct bContext *C)
View2DGrid * UI_view2d_grid_calc (struct Scene *scene, struct View2D *v2d, short xunits, short xclamp, short yunits, short yclamp, int winx, int winy)
void UI_view2d_grid_draw (struct View2D *v2d, View2DGrid *grid, int flag)
void UI_view2d_constant_grid_draw (struct View2D *v2d)
void UI_view2d_grid_size (View2DGrid *grid, float *r_dx, float *r_dy)
void UI_view2d_grid_free (View2DGrid *grid)
View2DScrollers * UI_view2d_scrollers_calc (const struct bContext *C, struct View2D *v2d, short xunits, short xclamp, short yunits, short yclamp)
void UI_view2d_scrollers_draw (const struct bContext *C, struct View2D *v2d, View2DScrollers *scrollers)
void UI_view2d_scrollers_free (View2DScrollers *scrollers)
void UI_view2d_listview_cell_to_view (struct View2D *v2d, short columnwidth, short rowheight, float startx, float starty, int column, int row, struct rctf *rect)
void UI_view2d_listview_view_to_cell (struct View2D *v2d, short columnwidth, short rowheight, float startx, float starty, float viewx, float viewy, int *column, int *row)
void UI_view2d_listview_visible_cells (struct View2D *v2d, short columnwidth, short rowheight, float startx, float starty, int *column_min, int *column_max, int *row_min, int *row_max)
void UI_view2d_region_to_view (struct View2D *v2d, int x, int y, float *viewx, float *viewy)
void UI_view2d_view_to_region (struct View2D *v2d, float x, float y, int *regionx, int *regiony)
void UI_view2d_to_region_no_clip (struct View2D *v2d, float x, float y, int *regionx, int *region_y)
struct View2D * UI_view2d_fromcontext (const struct bContext *C)
struct View2D * UI_view2d_fromcontext_rwin (const struct bContext *C)
void UI_view2d_getscale (struct View2D *v2d, float *x, float *y)
short UI_view2d_mouse_in_scrollers (const struct bContext *C, struct View2D *v2d, int x, int y)
void UI_view2d_text_cache_add (struct View2D *v2d, float x, float y, const char *str, const char col[4])
void UI_view2d_text_cache_rectf (struct View2D *v2d, struct rctf *rect, const char *str, const char col[4])
void UI_view2d_text_cache_draw (struct ARegion *ar)
void UI_view2d_operatortypes (void)
void UI_view2d_keymap (struct wmKeyConfig *keyconf)
Variables
enum { ... } eView2D_CommonViewTypes
enum { ... } eView2D_Units
enum { ... } eView2D_Clamp
enum { ... } eView2D_Gridlines
Detailed Description
Definition in file UI_view2d.h.
Define Documentation
#define IN_2D_HORIZ_SCROLL (v2d, co) (BLI_in_rcti(&v2d->hor, co[0], co[1]))
Definition at line 124 of file UI_view2d.h.
Referenced by UI_view2d_mouse_in_scrollers().
#define IN_2D_VERT_SCROLL (v2d, co) (BLI_in_rcti(&v2d->vert, co[0], co[1]))
Definition at line 123 of file UI_view2d.h.
Referenced by UI_view2d_mouse_in_scrollers().
#define V2D_ARG_DUMMY -1
Definition at line 68 of file UI_view2d.h.
Referenced by action_channel_area_draw(), action_main_area_draw(), console_main_area_draw(), drawnodespace(), ED_region_panels(), file_main_area_draw(), graph_channel_area_draw(), image_main_area_draw(), info_main_area_draw(), logic_main_area_draw(), nla_channel_area_draw(), nla_main_area_draw(), outliner_main_area_draw(), scroller_activate_init(), time_main_area_draw(), and UI_view2d_grid_calc().
#define V2D_IS_CLIPPED 12000
Definition at line 43 of file UI_view2d.h.
Referenced by UI_view2d_text_cache_add(), and UI_view2d_view_to_region().
#define V2D_LOCK_COPY 1
Definition at line 116 of file UI_view2d.h.
Referenced by actkeys_viewall(), draw_channel_names(), draw_nla_channel_list(), graphkeys_viewall(), nlaedit_viewall(), reset_exec(), scroller_activate_apply(), sequencer_view_all_exec(), sequencer_view_all_preview_exec(), sequencer_view_selected_exec(), UI_view2d_sync(), view_borderzoom_exec(), view_pan_apply(), view_zoomdrag_apply(), and view_zoomstep_apply().
#define V2D_LOCK_SET 0
Definition at line 114 of file UI_view2d.h.
#define V2D_SCROLL_HEIGHT 17
Definition at line 105 of file UI_view2d.h.
Referenced by draw_outliner(), ED_region_panels(), file_calc_previews(), outliner_draw_restrictcols(), outliner_draw_rnacols(), time_draw_cache(), UI_view2d_totRect_set_resize(), and view2d_masks().
#define V2D_SCROLL_WIDTH 17
Definition at line 106 of file UI_view2d.h.
Referenced by ED_region_panels(), ED_spacetype_ipo(), outliner_back(), outliner_draw_restrictcols(), outliner_draw_struct_marks(), UI_view2d_region_reinit(), UI_view2d_totRect_set_resize(), and view2d_masks().
#define V2D_SCROLLER_HANDLE_SIZE 12
Definition at line 109 of file UI_view2d.h.
Referenced by mouse_in_scroller_handle(), UI_view2d_scrollers_calc(), and UI_view2d_scrollers_draw().
Typedef Documentation
typedef struct View2DGrid View2DGrid
Definition at line 140 of file UI_view2d.h.
typedef struct View2DScrollers View2DScrollers
Definition at line 141 of file UI_view2d.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
V2D_COMMONVIEW_CUSTOM
V2D_COMMONVIEW_STANDARD
V2D_COMMONVIEW_LIST
V2D_COMMONVIEW_STACK
V2D_COMMONVIEW_HEADER
V2D_COMMONVIEW_PANELS_UI
Definition at line 50 of file UI_view2d.h.
anonymous enum
Enumerator:
V2D_UNIT_SECONDS
V2D_UNIT_FRAMES
V2D_UNIT_FRAMESCALE
V2D_UNIT_VALUES
V2D_UNIT_DEGREES
V2D_UNIT_TIME
V2D_UNIT_SECONDSSEQ
Definition at line 71 of file UI_view2d.h.
anonymous enum
Enumerator:
V2D_GRID_NOCLAMP
V2D_GRID_CLAMP
Definition at line 85 of file UI_view2d.h.
anonymous enum
Enumerator:
V2D_HORIZONTAL_LINES
V2D_VERTICAL_LINES
V2D_HORIZONTAL_AXIS
V2D_VERTICAL_AXIS
V2D_HORIZONTAL_FINELINES
V2D_GRIDLINES_MAJOR
V2D_GRIDLINES_ALL
Definition at line 91 of file UI_view2d.h.
Function Documentation
void UI_view2d_constant_grid_draw (struct View2D * v2d)
Definition at line 1301 of file view2d.c.
References View2D::cur, step(), TH_BACK, UI_ThemeColorShade(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by draw_timeline_seq(), and drawnodespace().
void UI_view2d_curRect_reset (struct View2D * v2d)
Definition at line 789 of file view2d.c.
References View2D::align, View2D::cur, View2D::mask, V2D_ALIGN_NO_NEG_X, V2D_ALIGN_NO_NEG_Y, V2D_ALIGN_NO_POS_X, V2D_ALIGN_NO_POS_Y, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
void UI_view2d_curRect_validate (struct View2D * v2d)
Definition at line 715 of file view2d.c.
References UI_view2d_curRect_validate_resize().
Referenced by draw_image_seq(), reset_exec(), scroller_activate_apply(), sequencer_view_all_exec(), sequencer_view_all_preview_exec(), sequencer_view_selected_exec(), snode_home(), view_borderzoom_exec(), view_pan_apply(), view_zoomdrag_apply(), and view_zoomstep_apply().
void UI_view2d_curRect_validate_resize (struct View2D * v2d, int resize)
Definition at line 324 of file view2d.c.
References ABS, View2D::align, CLAMP(), View2D::cur, KDL::diff(), View2D::keepofs, View2D::keeptot, View2D::keepzoom, View2D::mask, View2D::max, View2D::maxzoom, View2D::min, View2D::minzoom, View2D::oldwinx, View2D::oldwiny, View2D::tot, V2D_ALIGN_NO_NEG_X, V2D_ALIGN_NO_NEG_Y, V2D_ALIGN_NO_POS_X, V2D_ALIGN_NO_POS_Y, V2D_KEEPASPECT, V2D_KEEPOFS_X, V2D_KEEPOFS_Y, V2D_KEEPTOT_STRICT, V2D_KEEPZOOM, V2D_LIMITZOOM, V2D_LOCKOFS_X, V2D_LOCKOFS_Y, V2D_LOCKZOOM_X, V2D_LOCKZOOM_Y, view2d_masks(), rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by UI_view2d_curRect_validate(), UI_view2d_region_reinit(), and UI_view2d_totRect_set_resize().
struct View2D* UI_view2d_fromcontext (const struct bContext * C) [read]
Referenced by createTransSeqData(), draw_markers_time(), ed_marker_border_select_exec(), ed_marker_move_modal(), ed_marker_select(), sequencer_borderselect_exec(), sequencer_cut_invoke(), sequencer_generic_invoke_xy__internal(), sequencer_select_invoke(), sequencer_select_linked_pick_invoke(), sequencer_view_all_exec(), sequencer_view_all_preview_exec(), sequencer_view_selected_exec(), sequencer_view_zoom_ratio_exec(), and view_ghost_border_exec().
struct View2D* UI_view2d_fromcontext_rwin (const struct bContext * C) [read]
void UI_view2d_getscale (struct View2D * v2d, float * x, float * y)
Definition at line 1986 of file view2d.c.
References View2D::cur, View2D::mask, rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, rctf::ymax, rcti::ymax, rctf::ymin, and rcti::ymin.
Referenced by draw_cfra_number(), draw_fcurve_samples(), draw_fcurve_vertices_handles(), draw_graph_cfra(), draw_keylist(), draw_marker(), draw_tracks_curves(), and nla_action_draw_keyframes().
View2DGrid* UI_view2d_grid_calc (struct Scene * scene, struct View2D * v2d, short xunits, short xclamp, short yunits, short yclamp, int winx, int winy)
Referenced by action_main_area_draw(), clip_draw_graph(), graph_main_area_draw(), nla_main_area_draw(), time_main_area_draw(), and UI_view2d_scrollers_calc().
void UI_view2d_grid_draw (struct View2D * v2d, View2DGrid * grid, int flag)
Definition at line 1192 of file view2d.c.
References View2D::cur, View2DGrid::dx, View2DGrid::dy, View2D::mask, NULL, View2DGrid::startx, View2DGrid::starty, step(), TH_GRID, UI_ThemeColor(), UI_ThemeColorShade(), V2D_HORIZONTAL_AXIS, V2D_HORIZONTAL_FINELINES, V2D_HORIZONTAL_LINES, V2D_VERTICAL_AXIS, V2D_VERTICAL_LINES, rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, rcti::ymax, rctf::ymax, rctf::ymin, and rcti::ymin.
Referenced by action_main_area_draw(), clip_draw_graph(), graph_main_area_draw(), nla_main_area_draw(), and time_main_area_draw().
void UI_view2d_grid_free (View2DGrid * grid)
Definition at line 1339 of file view2d.c.
References MEM_freeN().
Referenced by action_main_area_draw(), clip_draw_graph(), graph_main_area_draw(), nla_main_area_draw(), and time_main_area_draw().
void UI_view2d_grid_size (View2DGrid * grid, float * r_dx, float * r_dy)
Definition at line 1332 of file view2d.c.
References View2DGrid::dx, and View2DGrid::dy.
Referenced by draw_fcurve_curve().
void UI_view2d_keymap (struct wmKeyConfig * keyconf)
Definition at line 1691 of file view2d_ops.c.
References BKEY, HOMEKEY, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTMOUSE, MIDDLEMOUSE, MOUSEPAN, MOUSEZOOM, PADMINUS, PADPLUSKEY, PAGEDOWNKEY, PAGEUPKEY, wmKeyMapItem::ptr, RNA_boolean_set(), TRUE, WHEELDOWNMOUSE, WHEELINMOUSE, WHEELOUTMOUSE, WHEELUPMOUSE, WM_keymap_add_item(), and WM_keymap_find().
Referenced by ED_spacetypes_keymap().
void UI_view2d_listview_cell_to_view (struct View2D * v2d, short columnwidth, short rowheight, float startx, float starty, int column, int row, struct rctf * rect)
Definition at line 1776 of file view2d.c.
References View2D::align, ELEM, NULL, V2D_ALIGN_NO_NEG_X, V2D_ALIGN_NO_NEG_Y, V2D_ALIGN_NO_POS_X, V2D_ALIGN_NO_POS_Y, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
void UI_view2d_listview_view_to_cell (struct View2D * v2d, short columnwidth, short rowheight, float startx, float starty, float viewx, float viewy, int * column, int * row)
Definition at line 1819 of file view2d.c.
References fabsf, floorf, and NULL.
Referenced by animchannels_mouseclick_invoke(), animchannels_rename_invoke(), mouse_action_keys(), mouse_nla_strips(), nlachannels_mouseclick_invoke(), outliner_item_activate(), and UI_view2d_listview_visible_cells().
void UI_view2d_listview_visible_cells (struct View2D * v2d, short columnwidth, short rowheight, float startx, float starty, int * column_min, int * column_max, int * row_min, int * row_max)
Definition at line 1852 of file view2d.c.
References View2D::cur, UI_view2d_listview_view_to_cell(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
short UI_view2d_mouse_in_scrollers (const struct bContext * C, struct View2D * v2d, int x, int y)
Referenced by scroller_activate_invoke().
void UI_view2d_operatortypes (void)
Definition at line 1671 of file view2d_ops.c.
References VIEW2D_OT_pan(), VIEW2D_OT_reset(), VIEW2D_OT_scroll_down(), VIEW2D_OT_scroll_left(), VIEW2D_OT_scroll_right(), VIEW2D_OT_scroll_up(), VIEW2D_OT_scroller_activate(), VIEW2D_OT_zoom(), VIEW2D_OT_zoom_border(), VIEW2D_OT_zoom_in(), VIEW2D_OT_zoom_out(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
void UI_view2d_region_reinit (struct View2D * v2d, short type, int winx, int winy)
Definition at line 166 of file view2d.c.
References View2D::align, View2D::cur, View2D::flag, init(), View2D::keepofs, View2D::keeptot, View2D::keepzoom, View2D::max, View2D::maxzoom, View2D::min, View2D::minzoom, uiStyle::panelzoom, View2D::scroll, View2D::tot, UI_GetStyle(), UI_view2d_curRect_validate_resize(), UI_view2d_totRect_set_resize(), V2D_ALIGN_NO_NEG_X, V2D_ALIGN_NO_NEG_Y, V2D_ALIGN_NO_POS_Y, V2D_COMMONVIEW_HEADER, V2D_COMMONVIEW_LIST, V2D_COMMONVIEW_PANELS_UI, V2D_COMMONVIEW_STACK, V2D_COMMONVIEW_STANDARD, V2D_IS_INITIALISED, V2D_KEEPASPECT, V2D_KEEPTOT_BOUNDS, V2D_KEEPTOT_STRICT, V2D_KEEPZOOM, V2D_LIMITZOOM, V2D_LOCKOFS_Y, V2D_LOCKZOOM_X, V2D_LOCKZOOM_Y, V2D_SCROLL_BOTTOM, V2D_SCROLL_HORIZONTAL_HIDE, V2D_SCROLL_RIGHT, V2D_SCROLL_VERTICAL_HIDE, V2D_SCROLL_WIDTH, view2d_masks(), View2D::winx, View2D::winy, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by action_channel_area_init(), action_main_area_init(), buttons_header_area_init(), clip_main_area_init(), clip_preview_area_init(), console_main_area_init(), ED_region_header_init(), ED_region_panels_init(), file_main_area_draw(), file_main_area_init(), file_ui_area_init(), graph_channel_area_init(), graph_main_area_init(), info_main_area_init(), logic_main_area_init(), nla_channel_area_init(), nla_main_area_init(), node_main_area_init(), outliner_main_area_init(), script_main_area_init(), sequencer_main_area_init(), sequencer_preview_area_init(), text_main_area_init(), time_main_area_init(), and userpref_main_area_draw().
void UI_view2d_region_to_view (struct View2D * v2d, int x, int y, float * viewx, float * viewy)
Definition at line 1875 of file view2d.c.
References View2D::cur, div, View2D::mask, rctf::xmax, rcti::xmax, rctf::xmin, rcti::xmin, rctf::ymax, rcti::ymax, rctf::ymin, and rcti::ymin.
Referenced by actkeys_select_leftright_invoke(), animchannels_mouseclick_invoke(), animchannels_rename_invoke(), border_select_exec(), border_select_graph_exec(), borderselect_action(), borderselect_anim_channels(), borderselect_exec(), borderselect_graphkeys(), borderselect_nla_strips(), CalcSnapGeometry(), circle_select_exec(), createTransActionData(), createTransNlaData(), createTransSeqData(), cut_links_exec(), do_node_add(), ed_marker_border_select_exec(), ed_marker_select(), file_hilight_set(), find_file_mouse_rect(), find_nearest_seq(), frame_from_event(), gp_stroke_convertcoords(), grab_clone_modal(), graphkeys_click_insert_invoke(), graphkeys_select_leftright_invoke(), graphview_cursor_setprops(), image_sample_apply(), image_sample_line_exec(), image_view_zoom_in_invoke(), image_view_zoom_init(), image_view_zoom_invoke(), image_view_zoom_out_invoke(), imapaint_paint_stroke(), mouse_action_keys(), mouse_frame_side(), mouse_nla_strips(), nlachannels_mouseclick_invoke(), nlaedit_select_leftright_invoke(), node_add_file_invoke(), node_border_select_invoke(), node_borderselect_exec(), node_link_invoke(), node_link_modal(), node_mouse_select(), node_resize_invoke(), node_resize_modal(), outliner_border_select_exec(), outliner_item_activate(), outliner_item_openclose(), outliner_item_rename(), outliner_operation(), outliner_parent_clear_poll(), outliner_parent_drop_poll(), parent_drop_invoke(), previewrange_define_exec(), select_invoke(), select_linked_internal(), select_loop_invoke(), sequencer_borderselect_exec(), sequencer_generic_invoke_xy__internal(), sequencer_select_invoke(), set_2d_cursor_invoke(), set_tile_invoke(), stitch_select(), TimeSlide(), TimeTranslate(), uv_sculpt_stroke_apply(), uv_sculpt_stroke_init(), view_borderzoom_exec(), view_ghost_border_exec(), view_zoomdrag_invoke(), view_zoomin_invoke(), and view_zoomout_invoke().
View2DScrollers* UI_view2d_scrollers_calc (const struct bContext * C, struct View2D * v2d, short xunits, short xclamp, short yunits, short yclamp)
Referenced by action_channel_area_draw(), action_main_area_draw(), clip_preview_area_draw(), console_main_area_draw(), draw_timeline_seq(), drawnodespace(), ED_region_panels(), file_main_area_draw(), graph_channel_area_draw(), graph_main_area_draw(), image_main_area_draw(), info_main_area_draw(), logic_main_area_draw(), nla_channel_area_draw(), nla_main_area_draw(), outliner_main_area_draw(), scroller_activate_init(), and time_main_area_draw().
void UI_view2d_scrollers_draw (const struct bContext * C, struct View2D * v2d, View2DScrollers * scrollers)
Referenced by action_channel_area_draw(), action_main_area_draw(), clip_preview_area_draw(), console_main_area_draw(), draw_timeline_seq(), drawnodespace(), ED_region_panels(), file_main_area_draw(), graph_channel_area_draw(), graph_main_area_draw(), image_main_area_draw(), info_main_area_draw(), logic_main_area_draw(), nla_channel_area_draw(), nla_main_area_draw(), outliner_main_area_draw(), and time_main_area_draw().
void UI_view2d_scrollers_free (View2DScrollers * scrollers)
Definition at line 1755 of file view2d.c.
References View2DScrollers::grid, and MEM_freeN().
Referenced by action_channel_area_draw(), action_main_area_draw(), clip_preview_area_draw(), console_main_area_draw(), draw_timeline_seq(), drawnodespace(), ED_region_panels(), file_main_area_draw(), graph_channel_area_draw(), graph_main_area_draw(), image_main_area_draw(), info_main_area_draw(), logic_main_area_draw(), nla_channel_area_draw(), nla_main_area_draw(), outliner_main_area_draw(), scroller_activate_init(), and time_main_area_draw().
void UI_view2d_sync (struct bScreen * screen, struct ScrArea * sa, struct View2D * v2dcur, int flag)
Definition at line 723 of file view2d.c.
References bScreen::areabase, View2D::cur, ED_region_tag_redraw(), ListBase::first, View2D::flag, ScrArea::next, ARegion::next, ScrArea::regionbase, ARegion::v2d, V2D_LOCK_COPY, V2D_VIEWSYNC_AREA_VERTICAL, V2D_VIEWSYNC_SCREEN_TIME, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by actkeys_viewall(), draw_channel_names(), draw_nla_channel_list(), graphkeys_viewall(), nlaedit_viewall(), reset_exec(), scroller_activate_apply(), sequencer_view_all_exec(), sequencer_view_all_preview_exec(), sequencer_view_selected_exec(), view_borderzoom_exec(), view_pan_apply(), view_zoomdrag_apply(), and view_zoomstep_apply().
int UI_view2d_tab_set (struct View2D * v2d, int tab)
Definition at line 907 of file view2d.c.
References View2D::cur, MEM_callocN(), MEM_freeN(), View2D::tab_cur, View2D::tab_num, View2D::tab_offset, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by ED_region_panels().
void UI_view2d_text_cache_add (struct View2D * v2d, float x, float y, const char * str, const char col[4])
Definition at line 2038 of file view2d.c.
References BLI_addtail(), View2DString::col, len(), MEM_callocN(), View2DString::mval, View2DString::pack, strlen(), UI_view2d_view_to_region(), and V2D_IS_CLIPPED.
Referenced by draw_seq_handle(), and nla_draw_strip_frames_text().
void UI_view2d_text_cache_draw (struct ARegion * ar)
Definition at line 2077 of file view2d.c.
References BLF_CLIPPING, BLF_clipping_default(), BLF_disable_default(), BLF_draw_default(), BLF_DRAW_STR_DUMMY_MAX, BLF_enable_default(), BLF_height_default(), BLI_freelistN(), View2DString::col, ED_region_pixelspace(), ListBase::first, View2DString::mval, View2DString::next, View2DString::pack, View2DString::rect, str, View2DString::ub, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by draw_timeline_seq(), and nla_main_area_draw().
void UI_view2d_text_cache_rectf (struct View2D * v2d, struct rctf * rect, const char * str, const char col[4])
Definition at line 2059 of file view2d.c.
References BLI_addtail(), View2DString::col, len(), MEM_callocN(), View2DString::mval, View2DString::pack, View2DString::rect, strlen(), UI_view2d_to_region_no_clip(), rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by draw_seq_text(), and nla_draw_strip_text().
void UI_view2d_to_region_no_clip (struct View2D * v2d, float x, float y, int * regionx, int * region_y)
Definition at line 1927 of file view2d.c.
References View2D::cur, View2D::mask, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by draw_image_buffer(), draw_image_buffer_tiled(), draw_image_grid(), draw_image_paint_helpers(), draw_movieclip_buffer(), ED_clip_point_stable_pos(), projectIntView(), ui_searchbox_create(), ui_tooltip_create(), and UI_view2d_text_cache_rectf().
void UI_view2d_totRect_set (struct View2D * v2d, int width, int height)
Definition at line 902 of file view2d.c.
References UI_view2d_totRect_set_resize().
Referenced by buttons_header_buttons(), console_textview_update_rect(), draw_image_seq(), draw_outliner(), ED_region_header(), ED_region_panels(), file_calc_previews(), graph_draw_channel_names(), and info_textview_update_rect().
void UI_view2d_totRect_set_resize (struct View2D * v2d, int width, int height, int resize)
Definition at line 839 of file view2d.c.
References abs(), View2D::align, ELEM3, G, G_DEBUG, View2D::scroll, View2D::tot, UI_view2d_curRect_validate_resize(), V2D_ALIGN_NO_NEG_X, V2D_ALIGN_NO_NEG_Y, V2D_ALIGN_NO_POS_X, V2D_ALIGN_NO_POS_Y, V2D_SCROLL_HEIGHT, V2D_SCROLL_HORIZONTAL, V2D_SCROLL_VERTICAL, V2D_SCROLL_WIDTH, view2d_scroll_mapped(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by UI_view2d_region_reinit(), and UI_view2d_totRect_set().
void UI_view2d_view_ortho (struct View2D * v2d)
Definition at line 978 of file view2d.c.
References View2D::cur, View2D::flag, floorf, View2D::mask, V2D_PIXELOFS_X, V2D_PIXELOFS_Y, view2d_map_cur_using_mask(), wmOrtho2(), rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by action_channel_area_draw(), action_main_area_draw(), buttons_header_area_draw(), clip_preview_area_draw(), console_main_area_draw(), draw_graph_sfra_efra(), draw_image_seq(), draw_outliner(), draw_timeline_seq(), drawnodespace(), ED_region_header(), ED_region_panels(), file_main_area_draw(), file_ui_area_draw(), graph_channel_area_draw(), graph_main_area_draw(), image_main_area_draw(), info_main_area_draw(), logic_main_area_draw(), nla_channel_area_draw(), nla_main_area_draw(), script_main_area_draw(), and time_main_area_draw().
void UI_view2d_view_orthoSpecial (struct ARegion * ar, struct View2D * v2d, short xaxis)
Definition at line 1017 of file view2d.c.
References view2d_map_cur_using_mask(), ARegion::winx, ARegion::winy, wmOrtho2(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by action_main_area_draw(), ANIM_draw_cfra(), draw_graph_cfra(), draw_timeline_seq(), graph_main_area_draw(), nla_main_area_draw(), and time_main_area_draw().
void UI_view2d_view_restore (const struct bContext * C)
Referenced by action_channel_area_draw(), action_main_area_draw(), buttons_header_area_draw(), clip_main_area_draw(), clip_preview_area_draw(), console_main_area_draw(), draw_image_seq(), draw_timeline_seq(), drawnodespace(), ED_region_header(), ED_region_panels(), file_main_area_draw(), file_ui_area_draw(), graph_channel_area_draw(), graph_main_area_draw(), image_main_area_draw(), info_main_area_draw(), logic_main_area_draw(), nla_channel_area_draw(), nla_main_area_draw(), outliner_main_area_draw(), script_main_area_draw(), and time_main_area_draw().
void UI_view2d_view_to_region (struct View2D * v2d, float x, float y, int * regionx, int * regiony)
Definition at line 1900 of file view2d.c.
References View2D::cur, View2D::mask, V2D_IS_CLIPPED, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by gp_stroke_eraser_dostroke(), gp_strokepoint_convertcoords(), mouse_select_knot(), nearest_fcurve_vert_store(), and UI_view2d_text_cache_add().
Variable Documentation
enum { ... } eView2D_Clamp
enum { ... } eView2D_CommonViewTypes
enum { ... } eView2D_Gridlines
enum { ... } eView2D_Units