Blender: graph_ops.c File Reference
graph_ops.c File Reference
graph editor
#include <stdlib.h>
#include <math.h>
#include "DNA_scene_types.h"
#include "DNA_anim_types.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_main.h"
#include "BKE_sound.h"
#include "UI_view2d.h"
#include "ED_anim_api.h"
#include "ED_markers.h"
#include "ED_screen.h"
#include "ED_transform.h"
#include "graph_intern.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
Functions
static void graphview_cursor_apply (bContext *C, wmOperator *op)
static int graphview_cursor_exec (bContext *C, wmOperator *op)
static void graphview_cursor_setprops (bContext *C, wmOperator *op, wmEvent *event)
static int graphview_cursor_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int graphview_cursor_modal (bContext *C, wmOperator *op, wmEvent *event)
static void GRAPH_OT_cursor_set (wmOperatorType *ot)
void graphedit_operatortypes (void)
void ED_operatormacros_graph (void)
static void graphedit_keymap_keyframes (wmKeyConfig *keyconf, wmKeyMap *keymap)
void graphedit_keymap (wmKeyConfig *keyconf)
Detailed Description
Definition in file graph_ops.c.
Function Documentation
void ED_operatormacros_graph (void)
Definition at line 239 of file graph_ops.c.
References wmOperatorType::description, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorTypeMacro::ptr, RNA_enum_set(), TFM_TIME_DUPLICATE, WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().
static void GRAPH_OT_cursor_set (wmOperatorType * ot) [static]
Definition at line 164 of file graph_ops.c.
References wmOperatorType::description, ED_operator_graphedit_active(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, graphview_cursor_exec(), graphview_cursor_invoke(), graphview_cursor_modal(), wmOperatorType::idname, wmOperatorType::invoke, MAXFRAME, MINAFRAME, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), RNA_def_int(), and wmOperatorType::srna.
Referenced by graphedit_operatortypes().
void graphedit_keymap (wmKeyConfig * keyconf)
Definition at line 404 of file graph_ops.c.
References EKEY, graphedit_keymap_keyframes(), KM_PRESS, KM_SHIFT, NKEY, SPACE_IPO, WM_keymap_add_item(), and WM_keymap_find().
Referenced by ED_spacetype_ipo().
static void graphedit_keymap_keyframes (wmKeyConfig * keyconf, wmKeyMap * keymap) [static]
Definition at line 256 of file graph_ops.c.
References ACTIONMOUSE, AKEY, BKEY, CKEY, DELKEY, DKEY, ED_marker_keymap_animedit_conflictfree(), FALSE, GRAPHKEYS_COLUMNSEL_CFRA, GRAPHKEYS_COLUMNSEL_KEYS, GRAPHKEYS_COLUMNSEL_MARKERS_BETWEEN, GRAPHKEYS_COLUMNSEL_MARKERS_COLUMN, GRAPHKEYS_LRSEL_LEFT, GRAPHKEYS_LRSEL_RIGHT, GRAPHKEYS_LRSEL_TEST, HKEY, HOMEKEY, IKEY, KKEY, KM_ALT, KM_CLICK, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTBRACKETKEY, LEFTMOUSE, LKEY, MKEY, OKEY, PADMINUS, PADPERIOD, PADPLUSKEY, PKEY, wmKeyMapItem::ptr, RIGHTBRACKETKEY, RNA_boolean_set(), RNA_enum_set(), RNA_string_set(), SELECTMOUSE, SKEY, SPACE_IPO, TABKEY, TKEY, transform_keymap_for_space(), TRUE, VKEY, WM_keymap_add_item(), and XKEY.
Referenced by graphedit_keymap().
void graphedit_operatortypes (void)
Definition at line 187 of file graph_ops.c.
References GRAPH_OT_bake(), GRAPH_OT_clean(), GRAPH_OT_click_insert(), GRAPH_OT_clickselect(), GRAPH_OT_copy(), GRAPH_OT_cursor_set(), GRAPH_OT_delete(), GRAPH_OT_duplicate(), GRAPH_OT_euler_filter(), GRAPH_OT_extrapolation_type(), GRAPH_OT_fmodifier_add(), GRAPH_OT_fmodifier_copy(), GRAPH_OT_fmodifier_paste(), GRAPH_OT_frame_jump(), GRAPH_OT_ghost_curves_clear(), GRAPH_OT_ghost_curves_create(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_paste(), GRAPH_OT_previewrange_set(), GRAPH_OT_properties(), GRAPH_OT_sample(), GRAPH_OT_select_all_toggle(), GRAPH_OT_select_border(), GRAPH_OT_select_column(), GRAPH_OT_select_leftright(), GRAPH_OT_select_less(), GRAPH_OT_select_linked(), GRAPH_OT_select_more(), GRAPH_OT_smooth(), GRAPH_OT_snap(), GRAPH_OT_sound_bake(), GRAPH_OT_view_all(), GRAPH_OT_view_selected(), and WM_operatortype_append().
Referenced by ED_spacetype_ipo().
static void graphview_cursor_apply (bContext * C, wmOperator * op) [static]
Definition at line 70 of file graph_ops.c.
References CFRA, CTX_data_main(), CTX_data_scene(), CTX_wm_space_graph(), SpaceIpo::cursorVal, NC_SCENE, ND_FRAME, wmOperator::ptr, RNA_float_get(), RNA_int_get(), sound_seek_scene(), SUBFRA, and WM_event_add_notifier().
Referenced by graphview_cursor_exec(), graphview_cursor_invoke(), and graphview_cursor_modal().
static int graphview_cursor_exec (bContext * C, wmOperator * op) [static]
Definition at line 93 of file graph_ops.c.
References graphview_cursor_apply(), and OPERATOR_FINISHED.
Referenced by GRAPH_OT_cursor_set().
static int graphview_cursor_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 121 of file graph_ops.c.
References graphview_cursor_apply(), graphview_cursor_setprops(), OPERATOR_RUNNING_MODAL, and WM_event_add_modal_handler().
Referenced by GRAPH_OT_cursor_set().
static int graphview_cursor_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 138 of file graph_ops.c.
References ESCKEY, graphview_cursor_apply(), graphview_cursor_setprops(), KM_RELEASE, LEFTMOUSE, MOUSEMOVE, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, RIGHTMOUSE, wmEvent::type, and wmEvent::val.
Referenced by GRAPH_OT_cursor_set().
static void graphview_cursor_setprops (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 102 of file graph_ops.c.
References CTX_wm_region(), wmEvent::mval, NULL, wmOperator::ptr, RNA_float_set(), RNA_int_set(), UI_view2d_region_to_view(), and ARegion::v2d.
Referenced by graphview_cursor_invoke(), and graphview_cursor_modal().