Blender: KDL::Vector2 Class Reference
KDL::Vector2 Class Reference
2D version of Vector
#include <frames.hpp>
Public Member Functions
Vector2 ()
Does not initialise to Zero().
Vector2 (double x, double y)
Vector2 (const Vector2 &arg)
Vector2 (double *xyz)
Vector2 (float *xyz)
Vector2 & operator= (const Vector2 &arg)
double operator() (int index) const
Access to elements, range checked when NDEBUG is not set, from 0..1.
double & operator() (int index)
Access to elements, range checked when NDEBUG is not set, from 0..1.
void GetValue (double *xy) const
store vector components in array
void ReverseSign ()
Vector2 & operator-= (const Vector2 &arg)
Vector2 & operator+= (const Vector2 &arg)
double Normalize (double eps=epsilon)
double Norm () const
void Set3DXY (const Vector &v)
projects v in its XY plane, and sets *this to these values
void Set3DYZ (const Vector &v)
projects v in its YZ plane, and sets *this to these values
void Set3DZX (const Vector &v)
projects v in its ZX plane, and sets *this to these values
void Set3DPlane (const Frame &F_someframe_XY, const Vector &v_someframe)
Static Public Member Functions
static Vector2 Zero ()
Friends
class Rotation2
Vector2 operator* (const Vector2 &lhs, double rhs)
Vector2 operator* (double lhs, const Vector2 &rhs)
Vector2 operator/ (const Vector2 &lhs, double rhs)
Vector2 operator+ (const Vector2 &lhs, const Vector2 &rhs)
Vector2 operator- (const Vector2 &lhs, const Vector2 &rhs)
Vector2 operator* (const Vector2 &lhs, const Vector2 &rhs)
Vector2 operator- (const Vector2 &arg)
void SetToZero (Vector2 &v)
bool Equal (const Vector2 &a, const Vector2 &b, double eps=epsilon)
Detailed Description
2D version of Vector
Definition at line 913 of file frames.hpp.
Constructor & Destructor Documentation
KDL::Vector2::Vector2 () [inline]
Does not initialise to Zero().
Definition at line 918 of file frames.hpp.
Referenced by Normalize().
IMETHOD Vector2::Vector2 (double x, double y) [inline]
Definition at line 756 of file frames.inl.
IMETHOD Vector2::Vector2 (const Vector2 & arg) [inline]
Definition at line 750 of file frames.inl.
KDL::Vector2::Vector2 (double * xyz) [inline]
KDL::Vector2::Vector2 (float * xyz) [inline]
Member Function Documentation
IMETHOD void Vector2::GetValue (double * xy) const [inline]
store vector components in array
Definition at line 51 of file frames.inl.
References data.
double KDL::Vector2::Norm () const [inline]
Returns:
the norm of the vector
Definition at line 87 of file frames.cpp.
References fabs(), KDL::sqr(), and KDL::sqrt().
Referenced by Normalize().
double KDL::Vector2::Normalize (double eps = epsilon)
Normalizes this vector and returns it norm makes v a unitvector and returns the norm of v. if v is smaller than eps, Vector(1,0,0) is returned with norm 0. if this is not good, check the return value of this method.
Definition at line 102 of file frames.cpp.
References Norm(), and Vector2().
Referenced by KDL::Rotation::GetXZRot().
double KDL::Vector2::operator() (int index) const [inline]
Access to elements, range checked when NDEBUG is not set, from 0..1.
IMETHOD double & Vector2::operator() (int index) [inline]
Access to elements, range checked when NDEBUG is not set, from 0..1.
Definition at line 831 of file frames.inl.
References FRAMES_CHECKI.
Vector2& KDL::Vector2::operator+= (const Vector2 & arg) [inline]
Vector2& KDL::Vector2::operator-= (const Vector2 & arg) [inline]
Vector2& KDL::Vector2::operator= (const Vector2 & arg) [inline]
void KDL::Vector2::ReverseSign () [inline]
IMETHOD void Vector2::Set3DPlane (const Frame & F_someframe_XY, const Vector & v_someframe) [inline]
projects v_someframe in the XY plane of F_someframe_XY, and sets *this to these values expressed wrt someframe.
Definition at line 868 of file frames.inl.
References KDL::Frame::Inverse().
IMETHOD void Vector2::Set3DXY (const Vector & v) [inline]
projects v in its XY plane, and sets *this to these values
Definition at line 849 of file frames.inl.
IMETHOD void Vector2::Set3DYZ (const Vector & v) [inline]
projects v in its YZ plane, and sets *this to these values
Definition at line 855 of file frames.inl.
IMETHOD void Vector2::Set3DZX (const Vector & v) [inline]
projects v in its ZX plane, and sets *this to these values
Definition at line 861 of file frames.inl.
static Vector2 KDL::Vector2::Zero () [inline, static]
Returns:
a zero 2D vector.
Referenced by KDL::Frame2::Frame2(), and SetToZero().
Friends And Related Function Documentation
bool Equal (const Vector2 & a, const Vector2 & b, double eps = epsilon) [friend]
do not use operator == because the definition of Equal(.,.) is slightly different. It compares whether the 2 arguments are equal in an eps-interval
Vector2 operator* (const Vector2 & lhs, double rhs) [friend]
Vector2 operator* (double lhs, const Vector2 & rhs) [friend]
Vector2 operator* (const Vector2 & lhs, const Vector2 & rhs) [friend]
Vector2 operator+ (const Vector2 & lhs, const Vector2 & rhs) [friend]
Vector2 operator- (const Vector2 & arg) [friend]
Vector2 operator- (const Vector2 & lhs, const Vector2 & rhs) [friend]
Vector2 operator/ (const Vector2 & lhs, double rhs) [friend]
friend class Rotation2 [friend]
Definition at line 981 of file frames.hpp.
void SetToZero (Vector2 & v) [friend]
The documentation for this class was generated from the following files:
frames.hpp
frames.cpp
frames.inl