Blender: BLI_mempool.c File Reference
BLI_mempool.c File Reference
blenlib
#include "BLI_utildefines.h"
#include "BLI_listbase.h"
#include "BLI_mempool.h"
#include "DNA_listBase.h"
#include "MEM_guardedalloc.h"
#include <string.h>
#include <stdlib.h>
Classes
struct BLI_freenode
struct BLI_mempool_chunk
struct BLI_mempool
Defines
#define MAKE_ID(a, b, c, d) ((int)(d)<<24 | (int)(c)<<16 | (b)<<8 | (a))
#define FREEWORD MAKE_ID('f', 'r', 'e', 'e')
#define MEMPOOL_ELEM_SIZE_MIN (sizeof(void *) * 2)
Typedefs
typedef struct BLI_freenode BLI_freenode
typedef struct BLI_mempool_chunk BLI_mempool_chunk
Functions
BLI_mempool * BLI_mempool_create (int esize, int totelem, int pchunk, int flag)
void * BLI_mempool_alloc (BLI_mempool *pool)
void * BLI_mempool_calloc (BLI_mempool *pool)
void BLI_mempool_free (BLI_mempool *pool, void *addr)
int BLI_mempool_count (BLI_mempool *pool)
void * BLI_mempool_findelem (BLI_mempool *pool, int index)
void BLI_mempool_iternew (BLI_mempool *pool, BLI_mempool_iter *iter)
void * BLI_mempool_iterstep (BLI_mempool_iter *iter)
void BLI_mempool_destroy (BLI_mempool *pool)
Detailed Description
Definition in file BLI_mempool.c.
Define Documentation
#define FREEWORD MAKE_ID('f', 'r', 'e', 'e')
Definition at line 57 of file BLI_mempool.c.
Referenced by BLI_mempool_alloc(), BLI_mempool_create(), BLI_mempool_free(), and BLI_mempool_iterstep().
#define MAKE_ID (a, b, c, d) ((int)(d)<<24 | (int)(c)<<16 | (b)<<8 | (a))
Definition at line 54 of file BLI_mempool.c.
#define MEMPOOL_ELEM_SIZE_MIN (sizeof(void *) * 2)
Definition at line 82 of file BLI_mempool.c.
Referenced by BLI_mempool_create().
Typedef Documentation
typedef struct BLI_freenode BLI_freenode
typedef struct BLI_mempool_chunk BLI_mempool_chunk
Function Documentation
void* BLI_mempool_alloc (BLI_mempool * pool)
Definition at line 174 of file BLI_mempool.c.
References BLI_addtail(), BLI_MEMPOOL_ALLOW_ITER, BLI_MEMPOOL_SYSMALLOC, BLI_mempool::chunks, BLI_mempool::csize, BLI_mempool_chunk::data, BLI_mempool::esize, BLI_mempool::flag, BLI_mempool::free, BLI_freenode::freeword, FREEWORD, MEM_mallocN(), BLI_freenode::next, BLI_mempool_chunk::next, NULL, BLI_mempool::pchunk, BLI_mempool_chunk::prev, BLI_mempool::totalloc, and BLI_mempool::totused.
Referenced by BLI_edgehash_insert(), BLI_ghash_insert(), BLI_mempool_calloc(), BMW_state_add(), CustomData_bmesh_alloc_block(), edge_copy_add_path(), edge_path_new(), and IMB_moviecache_put().
void* BLI_mempool_calloc (BLI_mempool * pool)
Definition at line 233 of file BLI_mempool.c.
References BLI_mempool_alloc(), and BLI_mempool::esize.
Referenced by BM_edge_create(), bm_face_boundary_add(), bm_face_create__internal(), bm_face_create__sfme(), bm_loop_create(), BM_vert_create(), bmo_flag_layer_alloc(), bmo_flag_layer_free(), knife_append_list(), new_knife_edge(), and new_knife_vert().
int BLI_mempool_count (BLI_mempool * pool)
Definition at line 291 of file BLI_mempool.c.
References BLI_mempool::totused.
BLI_mempool* BLI_mempool_create (int esize, int totelem, int pchunk, int flag)
Definition at line 84 of file BLI_mempool.c.
References BLI_addtail(), BLI_MEMPOOL_ALLOW_ITER, BLI_MEMPOOL_SYSMALLOC, BLI_mempool::chunks, BLI_mempool::csize, BLI_mempool_chunk::data, BLI_mempool::esize, ListBase::first, BLI_mempool::flag, BLI_mempool::free, BLI_freenode::freeword, FREEWORD, i, ListBase::last, MAX2, MEM_mallocN(), MEMPOOL_ELEM_SIZE_MIN, BLI_freenode::next, BLI_mempool_chunk::next, NULL, BLI_mempool::pchunk, BLI_mempool_chunk::prev, BLI_mempool::totalloc, and BLI_mempool::totused.
Referenced by BLI_edgehash_new(), BLI_ghash_new(), bm_mempool_init(), bmo_flag_layer_alloc(), bmo_flag_layer_free(), BMW_init(), CustomData_bmesh_init_pool(), edge_pathbase_new(), IMB_moviecache_create(), and knifetool_init().
void BLI_mempool_destroy (BLI_mempool * pool)
Definition at line 394 of file BLI_mempool.c.
References BLI_freelist(), BLI_freelistN(), BLI_MEMPOOL_SYSMALLOC, BLI_mempool::chunks, BLI_mempool_chunk::data, ListBase::first, BLI_mempool::flag, MEM_freeN(), BLI_mempool_chunk::next, and NULL.
Referenced by BLI_edgehash_free(), BLI_ghash_free(), BM_mesh_data_free(), bmo_flag_layer_alloc(), bmo_flag_layer_free(), BMW_end(), CustomData_bmesh_merge(), edge_pathbase_free(), IMB_moviecache_free(), knifetool_exit(), and update_data_blocks().
void* BLI_mempool_findelem (BLI_mempool * pool, int index)
Definition at line 296 of file BLI_mempool.c.
References BLI_MEMPOOL_ALLOW_ITER, BLI_mempool_iternew(), BLI_mempool_iterstep(), BLI_mempool::flag, and NULL.
Referenced by BM_edge_at_index(), BM_face_at_index(), and BM_vert_at_index().
void BLI_mempool_free (BLI_mempool * pool, void * addr)
Definition at line 241 of file BLI_mempool.c.
References BLI_addtail(), BLI_freelist(), BLI_freelistN(), BLI_MEMPOOL_ALLOW_ITER, BLI_MEMPOOL_SYSMALLOC, BLI_remlink(), BLI_mempool::chunks, BLI_mempool_chunk::data, BLI_mempool::esize, ListBase::first, BLI_mempool::flag, BLI_mempool::free, BLI_freenode::freeword, FREEWORD, i, MEM_freeN(), BLI_freenode::next, BLI_mempool_chunk::next, NULL, BLI_mempool::pchunk, BLI_mempool::totalloc, and BLI_mempool::totused.
Referenced by BLI_edgehash_clear(), BLI_ghash_remove(), BM_face_kill(), bm_kill_only_edge(), bm_kill_only_face(), bm_kill_only_loop(), bm_kill_only_vert(), bmesh_jekv(), bmesh_jfke(), bmesh_sfme(), BMW_state_remove(), CustomData_bmesh_free_block(), edge_free_path(), moviecache_keyfree(), and moviecache_valfree().
void BLI_mempool_iternew (BLI_mempool * pool, BLI_mempool_iter * iter)
Definition at line 316 of file BLI_mempool.c.
References BLI_MEMPOOL_ALLOW_ITER, BLI_mempool::chunks, BLI_mempool_iter::curchunk, BLI_mempool_iter::curindex, ListBase::first, BLI_mempool::flag, NULL, and BLI_mempool_iter::pool.
Referenced by BLI_mempool_findelem(), bmiter__edge_of_mesh_begin(), bmiter__face_of_mesh_begin(), bmiter__vert_of_mesh_begin(), knife_make_cuts(), and knifetool_draw().
void* BLI_mempool_iterstep (BLI_mempool_iter * iter)
Definition at line 367 of file BLI_mempool.c.
References BLI_mempool_iter::curchunk, BLI_mempool_iter::curindex, BLI_mempool_chunk::data, BLI_mempool::esize, BLI_freenode::freeword, FREEWORD, LIKELY, BLI_mempool_chunk::next, NULL, BLI_mempool::pchunk, BLI_mempool_iter::pool, BLI_mempool::totused, and UNLIKELY.
Referenced by BLI_mempool_findelem(), bmiter__edge_of_mesh_step(), bmiter__face_of_mesh_step(), bmiter__vert_of_mesh_step(), knife_make_cuts(), and knifetool_draw().