Blender: rna_ui_api.c File Reference
rna_ui_api.c File Reference
RNA
#include <stdlib.h>
#include <stdio.h>
#include "RNA_define.h"
#include "UI_resources.h"
#include "UI_icons.h"
Defines
#define DEF_ICON_BLANK_SKIP
#define DEF_ICON(name) {ICON_##name, (#name), 0, (#name), ""},
#define DEF_VICO(name) {VICO_##name, (#name), 0, (#name), ""},
Functions
static void api_ui_item_common (FunctionRNA *func)
static void api_ui_item_op (FunctionRNA *func)
static void api_ui_item_op_common (FunctionRNA *func)
static void api_ui_item_rna_common (FunctionRNA *func)
void RNA_api_ui_layout (StructRNA *srna)
Variables
static EnumPropertyItem icon_items []
Detailed Description
Definition in file rna_ui_api.c.
Define Documentation
#define DEF_ICON (name) {ICON_##name, (#name), 0, (#name), ""},
Definition at line 74 of file rna_ui_api.c.
#define DEF_ICON_BLANK_SKIP
Definition at line 73 of file rna_ui_api.c.
#define DEF_VICO (name) {VICO_##name, (#name), 0, (#name), ""},
Definition at line 75 of file rna_ui_api.c.
Function Documentation
static void api_ui_item_common (FunctionRNA * func) [static]
Definition at line 83 of file rna_ui_api.c.
References PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_ui_text(), and RNA_def_string_translate().
Referenced by api_ui_item_op_common(), and RNA_api_ui_layout().
static void api_ui_item_op (FunctionRNA * func) [static]
Definition at line 95 of file rna_ui_api.c.
References PROP_REQUIRED, RNA_def_property_flag(), and RNA_def_string().
Referenced by api_ui_item_op_common(), and RNA_api_ui_layout().
static void api_ui_item_op_common (FunctionRNA * func) [static]
Definition at line 102 of file rna_ui_api.c.
References api_ui_item_common(), and api_ui_item_op().
Referenced by RNA_api_ui_layout().
static void api_ui_item_rna_common (FunctionRNA * func) [static]
Definition at line 108 of file rna_ui_api.c.
References PROP_NEVER_NULL, PROP_REQUIRED, PROP_RNAPTR, RNA_def_pointer(), RNA_def_property_flag(), and RNA_def_string().
Referenced by RNA_api_ui_layout().
void RNA_api_ui_layout (StructRNA * srna)
Definition at line 118 of file rna_ui_api.c.
References api_ui_item_common(), api_ui_item_op(), api_ui_item_op_common(), api_ui_item_rna_common(), curve_type_items, FUNC_USE_CONTEXT, NULL, PROP_NEVER_NULL, PROP_REQUIRED, PROP_RNAPTR, RNA_def_boolean(), RNA_def_enum(), RNA_def_float(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_string(), and RNA_def_string_translate().
Referenced by rna_def_ui_layout().
Variable Documentation
EnumPropertyItem icon_items[] [static]
Initial value:
 {
        {0, NULL, 0, NULL, NULL}}
Definition at line 76 of file rna_ui_api.c.