Blender: CCGSubSurf.c File Reference
CCGSubSurf.c File Reference
blenkernel
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "CCGSubSurf.h"
#include "BKE_subsurf.h"
#include "MEM_guardedalloc.h"
#include "BLO_sys_types.h"
#include "BLI_utildefines.h"
Classes
struct _EHEntry
struct _EHash
struct _EHashIterator
struct CCGVert
struct CCGEdge
struct CCGFace
struct CCGSubSurf
Defines
#define CCG_INLINE inline
#define EPSILON (1.0e-35f)
#define EHASH_alloc(eh, nb) ((eh)->allocatorIFC.alloc((eh)->allocator, nb))
#define EHASH_free(eh, ptr) ((eh)->allocatorIFC.free((eh)->allocator, ptr))
#define EHASH_hash(eh, item) (((uintptr_t) (item)) % ((unsigned int) (eh)->curSize))
#define VertDataZero(av) { float *_a = (float *)av; _a[0] = _a[1] = _a[2] = 0.0f; }
#define VertDataCopy(av, bv) { float *_a = (float *)av, *_b = (float *) bv; _a[0] = _b[0]; _a[1] = _b[1]; _a[2] = _b[2]; }
#define VertDataAdd(av, bv) { float *_a = (float *)av, *_b = (float *) bv; _a[0] += _b[0]; _a[1] += _b[1]; _a[2] += _b[2]; }
#define VertDataSub(av, bv) { float *_a = (float *)av, *_b = (float *) bv; _a[0] -= _b[0]; _a[1] -= _b[1]; _a[2] -= _b[2]; }
#define VertDataMulN(av, n) { float *_a = (float *)av; float _n = n; _a[0] *= _n; _a[1] *= _n; _a[2] *= _n; }
#define VertDataAvg4(tv, av, bv, cv, dv)
#define NormZero(av) { float *_a = (float *) av; _a[0] = _a[1] = _a[2] = 0.0f; }
#define NormCopy(av, bv) { float *_a = (float *) av, *_b = (float *) bv; _a[0] = _b[0]; _a[1] = _b[1]; _a[2] = _b[2]; }
#define NormAdd(av, bv) { float *_a = (float *) av, *_b = (float *) bv; _a[0] += _b[0]; _a[1] += _b[1]; _a[2] += _b[2]; }
#define CCGSUBSURF_alloc(ss, nb) ((ss)->allocatorIFC.alloc((ss)->allocator, nb))
#define CCGSUBSURF_realloc(ss, ptr, nb, ob) ((ss)->allocatorIFC.realloc((ss)->allocator, ptr, nb, ob))
#define CCGSUBSURF_free(ss, ptr) ((ss)->allocatorIFC.free((ss)->allocator, ptr))
#define VERT_getNo(e, lvl) _vert_getNo(e, lvl, vertDataSize, normalDataOffset)
#define EDGE_getNo(e, lvl, x) _edge_getNo(e, lvl, x, vertDataSize, normalDataOffset)
#define FACE_getIFNo(f, lvl, S, x, y) _face_getIFNo(f, lvl, S, x, y, subdivLevels, vertDataSize, normalDataOffset)
#define FACE_calcIFNo(f, lvl, S, x, y, no) _face_calcIFNo(f, lvl, S, x, y, no, subdivLevels, vertDataSize)
#define FACE_getIENo(f, lvl, S, x) _face_getIENo(f, lvl, S, x, subdivLevels, vertDataSize, normalDataOffset)
#define VERT_getCo(v, lvl) _vert_getCo(v, lvl, vertDataSize)
#define EDGE_getCo(e, lvl, x) _edge_getCo(e, lvl, x, vertDataSize)
#define FACE_getIECo(f, lvl, S, x) _face_getIECo(f, lvl, S, x, subdivLevels, vertDataSize)
#define FACE_getIFCo(f, lvl, S, x, y) _face_getIFCo(f, lvl, S, x, y, subdivLevels, vertDataSize)
Typedefs
typedef unsigned char byte
typedef struct _EHEntry EHEntry
typedef struct _EHash EHash
typedef void(* EHEntryFreeFP)(EHEntry *, void *)
typedef struct _EHashIterator EHashIterator
Enumerations
enum { Vert_eEffected = (1 << 0), Vert_eChanged = (1 << 1), Vert_eSeam = (1 << 2) }
enum { Edge_eEffected = (1 << 0) }
enum { Face_eEffected = (1 << 0) }
enum SyncState {
eSyncState_None = 0, eSyncState_Vert, eSyncState_Edge, eSyncState_Face,
eSyncState_Partial
}
Functions
static void ccgSubSurf__sync (CCGSubSurf *ss)
static int _edge_isBoundary (const CCGEdge *e)
static EHash * _ehash_new (int estimatedNumEntries, CCGAllocatorIFC *allocatorIFC, CCGAllocatorHDL allocator)
static void _ehash_free (EHash *eh, EHEntryFreeFP freeEntry, void *userData)
static void _ehash_insert (EHash *eh, EHEntry *entry)
static void * _ehash_lookupWithPrev (EHash *eh, void *key, void ***prevp_r)
static void * _ehash_lookup (EHash *eh, void *key)
static EHashIterator * _ehashIterator_new (EHash *eh)
static void _ehashIterator_free (EHashIterator *ehi)
static void * _ehashIterator_getCurrent (EHashIterator *ehi)
static void _ehashIterator_next (EHashIterator *ehi)
static int _ehashIterator_isStopped (EHashIterator *ehi)
static void * _stdAllocator_alloc (CCGAllocatorHDL UNUSED(a), int numBytes)
static void * _stdAllocator_realloc (CCGAllocatorHDL UNUSED(a), void *ptr, int newSize, int UNUSED(oldSize))
static void _stdAllocator_free (CCGAllocatorHDL UNUSED(a), void *ptr)
static CCGAllocatorIFC * _getStandardAllocatorIFC (void)
int ccg_gridsize (int level)
int ccg_factor (int low_level, int high_level)
static int ccg_edgesize (int level)
static int ccg_spacing (int high_level, int low_level)
static int ccg_edgebase (int level)
static int VertDataEqual (const float *a, const float *b)
static CCG_INLINE byte * VERT_getLevelData (CCGVert *v)
static CCG_INLINE byte * EDGE_getLevelData (CCGEdge *e)
static CCG_INLINE CCGVert ** FACE_getVerts (CCGFace *f)
static CCG_INLINE CCGEdge ** FACE_getEdges (CCGFace *f)
static CCG_INLINE byte * FACE_getCenterData (CCGFace *f)
static CCGVert * _vert_new (CCGVertHDL vHDL, CCGSubSurf *ss)
static void _vert_remEdge (CCGVert *v, CCGEdge *e)
static void _vert_remFace (CCGVert *v, CCGFace *f)
static void _vert_addEdge (CCGVert *v, CCGEdge *e, CCGSubSurf *ss)
static void _vert_addFace (CCGVert *v, CCGFace *f, CCGSubSurf *ss)
static CCGEdge * _vert_findEdgeTo (const CCGVert *v, const CCGVert *vQ)
static int _vert_isBoundary (const CCGVert *v)
static void * _vert_getCo (CCGVert *v, int lvl, int dataSize)
static float * _vert_getNo (CCGVert *v, int lvl, int dataSize, int normalDataOffset)
static void _vert_free (CCGVert *v, CCGSubSurf *ss)
static int VERT_seam (const CCGVert *v)
static CCGEdge * _edge_new (CCGEdgeHDL eHDL, CCGVert *v0, CCGVert *v1, float crease, CCGSubSurf *ss)
static void _edge_remFace (CCGEdge *e, CCGFace *f)
static void _edge_addFace (CCGEdge *e, CCGFace *f, CCGSubSurf *ss)
static CCGVert * _edge_getOtherVert (CCGEdge *e, CCGVert *vQ)
static void * _edge_getCo (CCGEdge *e, int lvl, int x, int dataSize)
static float * _edge_getNo (CCGEdge *e, int lvl, int x, int dataSize, int normalDataOffset)
static void * _edge_getCoVert (CCGEdge *e, CCGVert *v, int lvl, int x, int dataSize)
static void _edge_free (CCGEdge *e, CCGSubSurf *ss)
static void _edge_unlinkMarkAndFree (CCGEdge *e, CCGSubSurf *ss)
static float EDGE_getSharpness (CCGEdge *e, int lvl)
static CCGFace * _face_new (CCGFaceHDL fHDL, CCGVert **verts, CCGEdge **edges, int numVerts, CCGSubSurf *ss)
static CCG_INLINE void * _face_getIECo (CCGFace *f, int lvl, int S, int x, int levels, int dataSize)
static CCG_INLINE void * _face_getIENo (CCGFace *f, int lvl, int S, int x, int levels, int dataSize, int normalDataOffset)
static CCG_INLINE void * _face_getIFCo (CCGFace *f, int lvl, int S, int x, int y, int levels, int dataSize)
static CCG_INLINE float * _face_getIFNo (CCGFace *f, int lvl, int S, int x, int y, int levels, int dataSize, int normalDataOffset)
static int _face_getVertIndex (CCGFace *f, CCGVert *v)
static int _face_getEdgeIndex (CCGFace *f, CCGEdge *e)
static CCG_INLINE void * _face_getIFCoEdge (CCGFace *f, CCGEdge *e, int f_ed_idx, int lvl, int eX, int eY, int levels, int dataSize)
static float * _face_getIFNoEdge (CCGFace *f, CCGEdge *e, int f_ed_idx, int lvl, int eX, int eY, int levels, int dataSize, int normalDataOffset)
static void _face_calcIFNo (CCGFace *f, int lvl, int S, int x, int y, float *no, int levels, int dataSize)
static void _face_free (CCGFace *f, CCGSubSurf *ss)
static void _face_unlinkMarkAndFree (CCGFace *f, CCGSubSurf *ss)
CCGSubSurf * ccgSubSurf_new (CCGMeshIFC *ifc, int subdivLevels, CCGAllocatorIFC *allocatorIFC, CCGAllocatorHDL allocator)
void ccgSubSurf_free (CCGSubSurf *ss)
CCGError ccgSubSurf_setAllowEdgeCreation (CCGSubSurf *ss, int allowEdgeCreation, float defaultCreaseValue, void *defaultUserData)
void ccgSubSurf_getAllowEdgeCreation (CCGSubSurf *ss, int *allowEdgeCreation_r, float *defaultCreaseValue_r, void *defaultUserData_r)
CCGError ccgSubSurf_setSubdivisionLevels (CCGSubSurf *ss, int subdivisionLevels)
void ccgSubSurf_getUseAgeCounts (CCGSubSurf *ss, int *useAgeCounts_r, int *vertUserOffset_r, int *edgeUserOffset_r, int *faceUserOffset_r)
CCGError ccgSubSurf_setUseAgeCounts (CCGSubSurf *ss, int useAgeCounts, int vertUserOffset, int edgeUserOffset, int faceUserOffset)
CCGError ccgSubSurf_setCalcVertexNormals (CCGSubSurf *ss, int useVertNormals, int normalDataOffset)
CCGError ccgSubSurf_initFullSync (CCGSubSurf *ss)
CCGError ccgSubSurf_initPartialSync (CCGSubSurf *ss)
CCGError ccgSubSurf_syncVertDel (CCGSubSurf *ss, CCGVertHDL vHDL)
CCGError ccgSubSurf_syncEdgeDel (CCGSubSurf *ss, CCGEdgeHDL eHDL)
CCGError ccgSubSurf_syncFaceDel (CCGSubSurf *ss, CCGFaceHDL fHDL)
CCGError ccgSubSurf_syncVert (CCGSubSurf *ss, CCGVertHDL vHDL, const void *vertData, int seam, CCGVert **v_r)
CCGError ccgSubSurf_syncEdge (CCGSubSurf *ss, CCGEdgeHDL eHDL, CCGVertHDL e_vHDL0, CCGVertHDL e_vHDL1, float crease, CCGEdge **e_r)
CCGError ccgSubSurf_syncFace (CCGSubSurf *ss, CCGFaceHDL fHDL, int numVerts, CCGVertHDL *vHDLs, CCGFace **f_r)
CCGError ccgSubSurf_processSync (CCGSubSurf *ss)
static void ccgSubSurf__calcVertNormals (CCGSubSurf *ss, CCGVert **effectedV, CCGEdge **effectedE, CCGFace **effectedF, int numEffectedV, int numEffectedE, int numEffectedF)
static void ccgSubSurf__calcSubdivLevel (CCGSubSurf *ss, CCGVert **effectedV, CCGEdge **effectedE, CCGFace **effectedF, int numEffectedV, int numEffectedE, int numEffectedF, int curLvl)
static void ccgSubSurf__allFaces (CCGSubSurf *ss, CCGFace ***faces, int *numFaces, int *freeFaces)
static void ccgSubSurf__effectedFaceNeighbours (CCGSubSurf *ss, CCGFace **faces, int numFaces, CCGVert ***verts, int *numVerts, CCGEdge ***edges, int *numEdges)
CCGError ccgSubSurf_updateFromFaces (CCGSubSurf *ss, int lvl, CCGFace **effectedF, int numEffectedF)
CCGError ccgSubSurf_updateToFaces (CCGSubSurf *ss, int lvl, CCGFace **effectedF, int numEffectedF)
CCGError ccgSubSurf_stitchFaces (CCGSubSurf *ss, int lvl, CCGFace **effectedF, int numEffectedF)
CCGError ccgSubSurf_updateNormals (CCGSubSurf *ss, CCGFace **effectedF, int numEffectedF)
CCGError ccgSubSurf_updateLevels (CCGSubSurf *ss, int lvl, CCGFace **effectedF, int numEffectedF)
int ccgSubSurf_getNumVerts (const CCGSubSurf *ss)
int ccgSubSurf_getNumEdges (const CCGSubSurf *ss)
int ccgSubSurf_getNumFaces (const CCGSubSurf *ss)
CCGVert * ccgSubSurf_getVert (CCGSubSurf *ss, CCGVertHDL v)
CCGEdge * ccgSubSurf_getEdge (CCGSubSurf *ss, CCGEdgeHDL e)
CCGFace * ccgSubSurf_getFace (CCGSubSurf *ss, CCGFaceHDL f)
int ccgSubSurf_getSubdivisionLevels (const CCGSubSurf *ss)
int ccgSubSurf_getEdgeSize (const CCGSubSurf *ss)
int ccgSubSurf_getEdgeLevelSize (const CCGSubSurf *ss, int level)
int ccgSubSurf_getGridSize (const CCGSubSurf *ss)
int ccgSubSurf_getGridLevelSize (const CCGSubSurf *ss, int level)
CCGVertHDL ccgSubSurf_getVertVertHandle (CCGVert *v)
int ccgSubSurf_getVertAge (CCGSubSurf *ss, CCGVert *v)
void * ccgSubSurf_getVertUserData (CCGSubSurf *ss, CCGVert *v)
int ccgSubSurf_getVertNumFaces (CCGVert *v)
CCGFace * ccgSubSurf_getVertFace (CCGVert *v, int index)
int ccgSubSurf_getVertNumEdges (CCGVert *v)
CCGEdge * ccgSubSurf_getVertEdge (CCGVert *v, int index)
void * ccgSubSurf_getVertData (CCGSubSurf *ss, CCGVert *v)
void * ccgSubSurf_getVertLevelData (CCGSubSurf *ss, CCGVert *v, int level)
CCGEdgeHDL ccgSubSurf_getEdgeEdgeHandle (CCGEdge *e)
int ccgSubSurf_getEdgeAge (CCGSubSurf *ss, CCGEdge *e)
void * ccgSubSurf_getEdgeUserData (CCGSubSurf *ss, CCGEdge *e)
int ccgSubSurf_getEdgeNumFaces (CCGEdge *e)
CCGFace * ccgSubSurf_getEdgeFace (CCGEdge *e, int index)
CCGVert * ccgSubSurf_getEdgeVert0 (CCGEdge *e)
CCGVert * ccgSubSurf_getEdgeVert1 (CCGEdge *e)
void * ccgSubSurf_getEdgeDataArray (CCGSubSurf *ss, CCGEdge *e)
void * ccgSubSurf_getEdgeData (CCGSubSurf *ss, CCGEdge *e, int x)
void * ccgSubSurf_getEdgeLevelData (CCGSubSurf *ss, CCGEdge *e, int x, int level)
float ccgSubSurf_getEdgeCrease (CCGEdge *e)
CCGFaceHDL ccgSubSurf_getFaceFaceHandle (CCGFace *f)
int ccgSubSurf_getFaceAge (CCGSubSurf *ss, CCGFace *f)
void * ccgSubSurf_getFaceUserData (CCGSubSurf *ss, CCGFace *f)
int ccgSubSurf_getFaceNumVerts (CCGFace *f)
CCGVert * ccgSubSurf_getFaceVert (CCGFace *f, int index)
CCGEdge * ccgSubSurf_getFaceEdge (CCGFace *f, int index)
int ccgSubSurf_getFaceEdgeIndex (CCGFace *f, CCGEdge *e)
void * ccgSubSurf_getFaceCenterData (CCGFace *f)
void * ccgSubSurf_getFaceGridEdgeDataArray (CCGSubSurf *ss, CCGFace *f, int gridIndex)
void * ccgSubSurf_getFaceGridEdgeData (CCGSubSurf *ss, CCGFace *f, int gridIndex, int x)
void * ccgSubSurf_getFaceGridDataArray (CCGSubSurf *ss, CCGFace *f, int gridIndex)
void * ccgSubSurf_getFaceGridData (CCGSubSurf *ss, CCGFace *f, int gridIndex, int x, int y)
CCGVertIterator * ccgSubSurf_getVertIterator (CCGSubSurf *ss)
CCGEdgeIterator * ccgSubSurf_getEdgeIterator (CCGSubSurf *ss)
CCGFaceIterator * ccgSubSurf_getFaceIterator (CCGSubSurf *ss)
CCGVert * ccgVertIterator_getCurrent (CCGVertIterator *vi)
int ccgVertIterator_isStopped (CCGVertIterator *vi)
void ccgVertIterator_next (CCGVertIterator *vi)
void ccgVertIterator_free (CCGVertIterator *vi)
CCGEdge * ccgEdgeIterator_getCurrent (CCGEdgeIterator *vi)
int ccgEdgeIterator_isStopped (CCGEdgeIterator *vi)
void ccgEdgeIterator_next (CCGEdgeIterator *vi)
void ccgEdgeIterator_free (CCGEdgeIterator *vi)
CCGFace * ccgFaceIterator_getCurrent (CCGFaceIterator *vi)
int ccgFaceIterator_isStopped (CCGFaceIterator *vi)
void ccgFaceIterator_next (CCGFaceIterator *vi)
void ccgFaceIterator_free (CCGFaceIterator *vi)
int ccgSubSurf_getNumFinalVerts (const CCGSubSurf *ss)
int ccgSubSurf_getNumFinalEdges (const CCGSubSurf *ss)
int ccgSubSurf_getNumFinalFaces (const CCGSubSurf *ss)
Variables
static int kHashSizes []
Detailed Description
Definition in file CCGSubSurf.c.
Define Documentation
#define CCG_INLINE inline
Definition at line 21 of file CCGSubSurf.c.
#define CCGSUBSURF_alloc (ss, nb) ((ss)->allocatorIFC.alloc((ss)->allocator, nb))
Definition at line 421 of file CCGSubSurf.c.
Referenced by _edge_new(), _face_new(), _vert_new(), ccgSubSurf_new(), and ccgSubSurf_setAllowEdgeCreation().
#define CCGSUBSURF_free (ss, ptr) ((ss)->allocatorIFC.free((ss)->allocator, ptr))
Definition at line 423 of file CCGSubSurf.c.
Referenced by _edge_free(), _face_free(), _vert_free(), ccgSubSurf_free(), and ccgSubSurf_setAllowEdgeCreation().
#define CCGSUBSURF_realloc (ss, ptr, nb, ob) ((ss)->allocatorIFC.realloc((ss)->allocator, ptr, nb, ob))
Definition at line 422 of file CCGSubSurf.c.
Referenced by _edge_addFace(), _vert_addEdge(), and _vert_addFace().
#define EDGE_getCo (e, lvl, x) _edge_getCo(e, lvl, x, vertDataSize)
Definition at line 1553 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcSubdivLevel(), ccgSubSurf__sync(), and ccgSubSurf_stitchFaces().
#define EDGE_getNo (e, lvl, x) _edge_getNo(e, lvl, x, vertDataSize, normalDataOffset)
Definition at line 1338 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcVertNormals().
#define EHASH_alloc (eh, nb) ((eh)->allocatorIFC.alloc((eh)->allocator, nb))
Definition at line 53 of file CCGSubSurf.c.
Referenced by _ehash_insert(), _ehash_new(), and _ehashIterator_new().
#define EHASH_free (eh, ptr) ((eh)->allocatorIFC.free((eh)->allocator, ptr))
Definition at line 54 of file CCGSubSurf.c.
Referenced by _ehash_free(), _ehash_insert(), and _ehashIterator_free().
#define EHASH_hash (eh, item) (((uintptr_t) (item)) % ((unsigned int) (eh)->curSize))
Definition at line 56 of file CCGSubSurf.c.
Referenced by _ehash_insert(), _ehash_lookup(), and _ehash_lookupWithPrev().
#define EPSILON (1.0e-35f)
Definition at line 26 of file CCGSubSurf.c.
Referenced by _face_calcIFNo(), Carve_checkMeshSetInterseciton_do(), and ccgSubSurf__calcVertNormals().
#define FACE_calcIFNo (f, lvl, S, x, y, no) _face_calcIFNo(f, lvl, S, x, y, no, subdivLevels, vertDataSize)
Definition at line 1340 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcVertNormals().
#define FACE_getIECo (f, lvl, S, x) _face_getIECo(f, lvl, S, x, subdivLevels, vertDataSize)
Definition at line 1554 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcSubdivLevel(), ccgSubSurf__sync(), ccgSubSurf_stitchFaces(), ccgSubSurf_updateFromFaces(), and ccgSubSurf_updateToFaces().
#define FACE_getIENo (f, lvl, S, x) _face_getIENo(f, lvl, S, x, subdivLevels, vertDataSize, normalDataOffset)
Definition at line 1341 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcVertNormals().
#define FACE_getIFCo (f, lvl, S, x, y) _face_getIFCo(f, lvl, S, x, y, subdivLevels, vertDataSize)
Definition at line 1555 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcSubdivLevel(), ccgSubSurf__sync(), ccgSubSurf_stitchFaces(), ccgSubSurf_updateFromFaces(), and ccgSubSurf_updateToFaces().
#define FACE_getIFNo (f, lvl, S, x, y) _face_getIFNo(f, lvl, S, x, y, subdivLevels, vertDataSize, normalDataOffset)
Definition at line 1339 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcVertNormals().
#define NormAdd (av, bv) { float *_a = (float *) av, *_b = (float *) bv; _a[0] += _b[0]; _a[1] += _b[1]; _a[2] += _b[2]; }
Definition at line 295 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcVertNormals().
#define NormCopy (av, bv) { float *_a = (float *) av, *_b = (float *) bv; _a[0] = _b[0]; _a[1] = _b[1]; _a[2] = _b[2]; }
Definition at line 294 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcVertNormals().
#define NormZero (av) { float *_a = (float *) av; _a[0] = _a[1] = _a[2] = 0.0f; }
Definition at line 293 of file CCGSubSurf.c.
Referenced by _face_calcIFNo(), and ccgSubSurf__calcVertNormals().
#define VERT_getCo (v, lvl) _vert_getCo(v, lvl, vertDataSize)
Definition at line 1552 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcSubdivLevel(), ccgSubSurf__sync(), ccgSubSurf_stitchFaces(), ccgSubSurf_updateFromFaces(), and ccgSubSurf_updateToFaces().
#define VERT_getNo (e, lvl) _vert_getNo(e, lvl, vertDataSize, normalDataOffset)
Definition at line 1337 of file CCGSubSurf.c.
#define VertDataAdd (av, bv) { float *_a = (float *)av, *_b = (float *) bv; _a[0] += _b[0]; _a[1] += _b[1]; _a[2] += _b[2]; }
Definition at line 283 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcSubdivLevel(), ccgSubSurf__sync(), and ccgSubSurf_stitchFaces().
#define VertDataAvg4 (tv, av, bv, cv, dv)
Value:
{ \
        float *_t = (float *) tv, *_a = (float *) av, *_b = (float *) bv, *_c = (float *) cv, *_d = (float *) dv; \
        _t[0] = (_a[0] + _b[0] + _c[0] + _d[0]) * 0.25f; \
        _t[1] = (_a[1] + _b[1] + _c[1] + _d[1]) * 0.25f; \
        _t[2] = (_a[2] + _b[2] + _c[2] + _d[2]) * 0.25f; \
    }
Definition at line 286 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcSubdivLevel().
#define VertDataCopy (av, bv) { float *_a = (float *)av, *_b = (float *) bv; _a[0] = _b[0]; _a[1] = _b[1]; _a[2] = _b[2]; }
Definition at line 282 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcSubdivLevel(), ccgSubSurf__calcVertNormals(), ccgSubSurf__sync(), ccgSubSurf_stitchFaces(), ccgSubSurf_syncVert(), ccgSubSurf_updateFromFaces(), and ccgSubSurf_updateToFaces().
#define VertDataMulN (av, n) { float *_a = (float *)av; float _n = n; _a[0] *= _n; _a[1] *= _n; _a[2] *= _n; }
Definition at line 285 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcSubdivLevel(), ccgSubSurf__sync(), and ccgSubSurf_stitchFaces().
#define VertDataSub (av, bv) { float *_a = (float *)av, *_b = (float *) bv; _a[0] -= _b[0]; _a[1] -= _b[1]; _a[2] -= _b[2]; }
Definition at line 284 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcSubdivLevel(), and ccgSubSurf__sync().
#define VertDataZero (av) { float *_a = (float *)av; _a[0] = _a[1] = _a[2] = 0.0f; }
Definition at line 281 of file CCGSubSurf.c.
Referenced by ccgSubSurf__calcSubdivLevel(), ccgSubSurf__sync(), and ccgSubSurf_stitchFaces().
Typedef Documentation
typedef unsigned char byte
Definition at line 30 of file CCGSubSurf.c.
typedef struct _EHash EHash
typedef struct _EHashIterator EHashIterator
typedef struct _EHEntry EHEntry
Definition at line 40 of file CCGSubSurf.c.
typedef void(* EHEntryFreeFP)(EHEntry *, void *)
Definition at line 76 of file CCGSubSurf.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
Vert_eEffected
Vert_eChanged
Vert_eSeam
Definition at line 299 of file CCGSubSurf.c.
anonymous enum
Enumerator:
Edge_eEffected
Definition at line 304 of file CCGSubSurf.c.
anonymous enum
Enumerator:
Face_eEffected
Definition at line 307 of file CCGSubSurf.c.
enum SyncState
Enumerator:
eSyncState_None
eSyncState_Vert
eSyncState_Edge
eSyncState_Face
eSyncState_Partial
Definition at line 375 of file CCGSubSurf.c.
Function Documentation
static void _edge_addFace (CCGEdge * e, CCGFace * f, CCGSubSurf * ss) [static]
Definition at line 558 of file CCGSubSurf.c.
References CCGSUBSURF_realloc, CCGEdge::faces, and CCGEdge::numFaces.
Referenced by _face_new().
static void _edge_free (CCGEdge * e, CCGSubSurf * ss) [static]
Definition at line 599 of file CCGSubSurf.c.
References CCGSUBSURF_free, and CCGEdge::faces.
Referenced by _edge_unlinkMarkAndFree(), ccgSubSurf_free(), and ccgSubSurf_setSubdivisionLevels().
static void* _edge_getCo (CCGEdge * e, int lvl, int x, int dataSize) [static]
Definition at line 578 of file CCGSubSurf.c.
References ccg_edgebase(), and EDGE_getLevelData().
Referenced by ccgSubSurf_getEdgeLevelData().
static void* _edge_getCoVert (CCGEdge * e, CCGVert * v, int lvl, int x, int dataSize) [static]
Definition at line 588 of file CCGSubSurf.c.
References ccg_edgebase(), EDGE_getLevelData(), and CCGEdge::v0.
Referenced by ccgSubSurf__calcSubdivLevel(), ccgSubSurf__sync(), ccgSubSurf_stitchFaces(), ccgSubSurf_updateFromFaces(), and ccgSubSurf_updateToFaces().
static float* _edge_getNo (CCGEdge * e, int lvl, int x, int dataSize, int normalDataOffset) [static]
Definition at line 583 of file CCGSubSurf.c.
References ccg_edgebase(), and EDGE_getLevelData().
static CCGVert* _edge_getOtherVert (CCGEdge * e, CCGVert * vQ) [static]
Definition at line 568 of file CCGSubSurf.c.
References CCGEdge::v0, and CCGEdge::v1.
Referenced by ccgSubSurf__sync().
static int _edge_isBoundary (const CCGEdge * e) [static]
Definition at line 563 of file CCGSubSurf.c.
References CCGEdge::numFaces.
Referenced by _vert_isBoundary(), ccgSubSurf__calcSubdivLevel(), and ccgSubSurf__sync().
static CCGEdge* _edge_new (CCGEdgeHDL eHDL, CCGVert * v0, CCGVert * v1, float crease, CCGSubSurf * ss) [static]
Definition at line 523 of file CCGSubSurf.c.
References _vert_addEdge(), ccg_edgebase(), CCGSUBSURF_alloc, ccgSubSurf_getEdgeUserData(), CCGEdge::crease, CCGSubSurf::currentAge, CCGSubSurf::edgeUserAgeOffset, CCGMeshIFC::edgeUserSize, CCGEdge::eHDL, CCGEdge::faces, CCGEdge::flags, CCGSubSurf::meshIFC, NULL, CCGEdge::numFaces, CCGSubSurf::subdivLevels, CCGSubSurf::useAgeCounts, CCGEdge::v0, CCGEdge::v1, and CCGMeshIFC::vertDataSize.
Referenced by ccgSubSurf_syncEdge(), and ccgSubSurf_syncFace().
static void _edge_remFace (CCGEdge * e, CCGFace * f) [static]
Definition at line 548 of file CCGSubSurf.c.
References CCGEdge::faces, i, and CCGEdge::numFaces.
Referenced by _face_unlinkMarkAndFree().
static void _edge_unlinkMarkAndFree (CCGEdge * e, CCGSubSurf * ss) [static]
Definition at line 604 of file CCGSubSurf.c.
References _edge_free(), _vert_remEdge(), CCGVert::flags, CCGEdge::v0, CCGEdge::v1, and Vert_eEffected.
Referenced by ccgSubSurf_processSync(), ccgSubSurf_syncEdge(), and ccgSubSurf_syncEdgeDel().
static void _ehash_free (EHash * eh, EHEntryFreeFP freeEntry, void * userData) [static]
Definition at line 77 of file CCGSubSurf.c.
References _EHash::buckets, _EHash::curSize, EHASH_free, _EHEntry::next, and next.
Referenced by ccgSubSurf_free(), ccgSubSurf_processSync(), and ccgSubSurf_setSubdivisionLevels().
static void _ehash_insert (EHash * eh, EHEntry * entry) [static]
Definition at line 97 of file CCGSubSurf.c.
References _EHash::buckets, _EHash::curSize, _EHash::curSizeIdx, EHASH_alloc, EHASH_free, EHASH_hash, hash, _EHEntry::key, kHashSizes, _EHEntry::next, next, and _EHash::numEntries.
Referenced by ccgSubSurf_syncEdge(), ccgSubSurf_syncFace(), and ccgSubSurf_syncVert().
static void* _ehash_lookup (EHash * eh, void * key) [static]
Definition at line 144 of file CCGSubSurf.c.
References _EHash::buckets, EHASH_hash, hash, _EHEntry::key, and _EHEntry::next.
Referenced by ccgSubSurf_getEdge(), ccgSubSurf_getFace(), ccgSubSurf_getVert(), ccgSubSurf_syncEdge(), and ccgSubSurf_syncFace().
static void* _ehash_lookupWithPrev (EHash * eh, void * key, void *** prevp_r) [static]
Definition at line 128 of file CCGSubSurf.c.
References _EHash::buckets, EHASH_hash, hash, and NULL.
Referenced by ccgSubSurf_syncEdge(), ccgSubSurf_syncEdgeDel(), ccgSubSurf_syncFace(), ccgSubSurf_syncFaceDel(), ccgSubSurf_syncVert(), and ccgSubSurf_syncVertDel().
static EHash* _ehash_new (int estimatedNumEntries, CCGAllocatorIFC * allocatorIFC, CCGAllocatorHDL allocator) [static]
Definition at line 61 of file CCGSubSurf.c.
References CCGAllocatorIFC::alloc, _EHash::allocator, _EHash::allocatorIFC, _EHash::buckets, _EHash::curSize, _EHash::curSizeIdx, EHASH_alloc, kHashSizes, and _EHash::numEntries.
Referenced by ccgSubSurf_initFullSync(), ccgSubSurf_new(), and ccgSubSurf_setSubdivisionLevels().
static void _ehashIterator_free (EHashIterator * ehi) [static]
Definition at line 178 of file CCGSubSurf.c.
References _EHashIterator::eh, and EHASH_free.
Referenced by ccgEdgeIterator_free(), ccgFaceIterator_free(), and ccgVertIterator_free().
static void* _ehashIterator_getCurrent (EHashIterator * ehi) [static]
Definition at line 183 of file CCGSubSurf.c.
References _EHashIterator::curEntry.
Referenced by ccgEdgeIterator_getCurrent(), ccgFaceIterator_getCurrent(), and ccgVertIterator_getCurrent().
static int _ehashIterator_isStopped (EHashIterator * ehi) [static]
Definition at line 200 of file CCGSubSurf.c.
References _EHashIterator::curEntry.
Referenced by ccgEdgeIterator_isStopped(), ccgFaceIterator_isStopped(), and ccgVertIterator_isStopped().
static EHashIterator* _ehashIterator_new (EHash * eh) [static]
Definition at line 164 of file CCGSubSurf.c.
References _EHash::buckets, _EHashIterator::curBucket, _EHashIterator::curEntry, _EHash::curSize, _EHashIterator::eh, EHASH_alloc, and NULL.
Referenced by ccgSubSurf_getEdgeIterator(), ccgSubSurf_getFaceIterator(), and ccgSubSurf_getVertIterator().
static void _ehashIterator_next (EHashIterator * ehi) [static]
Definition at line 188 of file CCGSubSurf.c.
References _EHash::buckets, _EHashIterator::curBucket, _EHashIterator::curEntry, _EHash::curSize, _EHashIterator::eh, and _EHEntry::next.
Referenced by ccgEdgeIterator_next(), ccgFaceIterator_next(), and ccgVertIterator_next().
static void _face_calcIFNo (CCGFace * f, int lvl, int S, int x, int y, float * no, int levels, int dataSize) [static]
Definition at line 736 of file CCGSubSurf.c.
References _face_getIFCo(), EPSILON, length(), NormZero, and sqrtf.
static void _face_free (CCGFace * f, CCGSubSurf * ss) [static]
Definition at line 764 of file CCGSubSurf.c.
References CCGSUBSURF_free.
Referenced by _face_unlinkMarkAndFree(), ccgSubSurf_free(), and ccgSubSurf_setSubdivisionLevels().
static int _face_getEdgeIndex (CCGFace * f, CCGEdge * e) [static]
Definition at line 693 of file CCGSubSurf.c.
References FACE_getEdges(), i, and CCGFace::numVerts.
Referenced by _face_getIFCoEdge(), ccgSubSurf__calcSubdivLevel(), and ccgSubSurf__calcVertNormals().
static CCG_INLINE void* _face_getIECo (CCGFace * f, int lvl, int S, int x, int levels, int dataSize) [static]
Definition at line 657 of file CCGSubSurf.c.
References ccg_gridsize(), ccg_spacing(), and FACE_getCenterData().
Referenced by ccgSubSurf_getFaceGridEdgeData().
static CCG_INLINE void* _face_getIENo (CCGFace * f, int lvl, int S, int x, int levels, int dataSize, int normalDataOffset) [static]
Definition at line 664 of file CCGSubSurf.c.
References ccg_gridsize(), ccg_spacing(), and FACE_getCenterData().
static CCG_INLINE void* _face_getIFCo (CCGFace * f, int lvl, int S, int x, int y, int levels, int dataSize) [static]
Definition at line 671 of file CCGSubSurf.c.
References ccg_gridsize(), ccg_spacing(), and FACE_getCenterData().
Referenced by _face_calcIFNo(), _face_getIFCoEdge(), and ccgSubSurf_getFaceGridData().
static CCG_INLINE void* _face_getIFCoEdge (CCGFace * f, CCGEdge * e, int f_ed_idx, int lvl, int eX, int eY, int levels, int dataSize) [static]
Definition at line 701 of file CCGSubSurf.c.
References _face_getEdgeIndex(), _face_getIFCo(), BLI_assert, ccg_gridsize(), ccg_spacing(), FACE_getVerts(), CCGFace::numVerts, and CCGEdge::v0.
Referenced by _face_getIFNoEdge(), and ccgSubSurf__calcSubdivLevel().
static CCG_INLINE float* _face_getIFNo (CCGFace * f, int lvl, int S, int x, int y, int levels, int dataSize, int normalDataOffset) [static]
Definition at line 678 of file CCGSubSurf.c.
References ccg_gridsize(), ccg_spacing(), and FACE_getCenterData().
static float* _face_getIFNoEdge (CCGFace * f, CCGEdge * e, int f_ed_idx, int lvl, int eX, int eY, int levels, int dataSize, int normalDataOffset) [static]
Definition at line 732 of file CCGSubSurf.c.
References _face_getIFCoEdge().
Referenced by ccgSubSurf__calcVertNormals().
static int _face_getVertIndex (CCGFace * f, CCGVert * v) [static]
Definition at line 685 of file CCGSubSurf.c.
References FACE_getVerts(), i, and CCGFace::numVerts.
Referenced by ccgSubSurf__calcSubdivLevel(), and ccgSubSurf__calcVertNormals().
static CCGFace* _face_new (CCGFaceHDL fHDL, CCGVert ** verts, CCGEdge ** edges, int numVerts, CCGSubSurf * ss) [static]
Definition at line 625 of file CCGSubSurf.c.
References _edge_addFace(), _vert_addFace(), ccg_gridsize(), CCGSUBSURF_alloc, ccgSubSurf_getFaceUserData(), CCGSubSurf::currentAge, FACE_getEdges(), FACE_getVerts(), CCGSubSurf::faceUserAgeOffset, CCGMeshIFC::faceUserSize, CCGFace::fHDL, CCGFace::flags, i, CCGSubSurf::meshIFC, CCGFace::numVerts, CCGSubSurf::subdivLevels, CCGSubSurf::useAgeCounts, and CCGMeshIFC::vertDataSize.
Referenced by ccgSubSurf_syncFace().
static void _face_unlinkMarkAndFree (CCGFace * f, CCGSubSurf * ss) [static]
Definition at line 768 of file CCGSubSurf.c.
References _edge_remFace(), _face_free(), _vert_remFace(), FACE_getEdges(), FACE_getVerts(), CCGVert::flags, CCGFace::numVerts, and Vert_eEffected.
Referenced by ccgSubSurf_processSync(), ccgSubSurf_syncFace(), and ccgSubSurf_syncFaceDel().
static CCGAllocatorIFC* _getStandardAllocatorIFC (void) [static]
Definition at line 220 of file CCGSubSurf.c.
References _stdAllocator_alloc(), _stdAllocator_free(), _stdAllocator_realloc(), CCGAllocatorIFC::alloc, CCGAllocatorIFC::free, NULL, CCGAllocatorIFC::realloc, and CCGAllocatorIFC::release.
Referenced by ccgSubSurf_new().
static void* _stdAllocator_alloc (CCGAllocatorHDL UNUSEDa, int numBytes) [static]
Definition at line 207 of file CCGSubSurf.c.
Referenced by _getStandardAllocatorIFC().
static void _stdAllocator_free (CCGAllocatorHDL UNUSEDa, void * ptr) [static]
Definition at line 215 of file CCGSubSurf.c.
Referenced by _getStandardAllocatorIFC().
static void* _stdAllocator_realloc (CCGAllocatorHDL UNUSEDa, void * ptr, int newSize, int UNUSEDoldSize) [static]
Definition at line 211 of file CCGSubSurf.c.
Referenced by _getStandardAllocatorIFC().
static void _vert_addEdge (CCGVert * v, CCGEdge * e, CCGSubSurf * ss) [static]
Definition at line 468 of file CCGSubSurf.c.
References CCGSUBSURF_realloc, CCGVert::edges, and CCGVert::numEdges.
Referenced by _edge_new().
static void _vert_addFace (CCGVert * v, CCGFace * f, CCGSubSurf * ss) [static]
Definition at line 473 of file CCGSubSurf.c.
References CCGSUBSURF_realloc, CCGVert::faces, and CCGVert::numFaces.
Referenced by _face_new().
static CCGEdge* _vert_findEdgeTo (const CCGVert * v, const CCGVert * vQ) [static]
Definition at line 478 of file CCGSubSurf.c.
References CCGVert::edges, i, NULL, CCGVert::numEdges, CCGEdge::v0, and CCGEdge::v1.
Referenced by ccgSubSurf_syncFace().
static void _vert_free (CCGVert * v, CCGSubSurf * ss) [static]
Definition at line 509 of file CCGSubSurf.c.
References CCGSUBSURF_free, CCGVert::edges, and CCGVert::faces.
Referenced by ccgSubSurf_free(), ccgSubSurf_processSync(), ccgSubSurf_setSubdivisionLevels(), and ccgSubSurf_syncVertDel().
static void* _vert_getCo (CCGVert * v, int lvl, int dataSize) [static]
Definition at line 500 of file CCGSubSurf.c.
References VERT_getLevelData().
Referenced by ccgSubSurf_getVertLevelData(), and ccgSubSurf_syncVert().
static float* _vert_getNo (CCGVert * v, int lvl, int dataSize, int normalDataOffset) [static]
Definition at line 504 of file CCGSubSurf.c.
References VERT_getLevelData().
Referenced by ccgSubSurf__calcVertNormals().
static int _vert_isBoundary (const CCGVert * v) [static]
Definition at line 491 of file CCGSubSurf.c.
References _edge_isBoundary(), CCGVert::edges, i, and CCGVert::numEdges.
Referenced by ccgSubSurf__calcSubdivLevel(), and ccgSubSurf__sync().
static CCGVert* _vert_new (CCGVertHDL vHDL, CCGSubSurf * ss) [static]
Definition at line 427 of file CCGSubSurf.c.
References CCGSUBSURF_alloc, ccgSubSurf_getVertUserData(), CCGSubSurf::currentAge, CCGVert::edges, CCGVert::faces, CCGVert::flags, CCGSubSurf::meshIFC, NULL, CCGVert::numEdges, CCGVert::numFaces, CCGSubSurf::subdivLevels, CCGSubSurf::useAgeCounts, CCGMeshIFC::vertDataSize, CCGSubSurf::vertUserAgeOffset, CCGMeshIFC::vertUserSize, and CCGVert::vHDL.
Referenced by ccgSubSurf_syncVert().
static void _vert_remEdge (CCGVert * v, CCGEdge * e) [static]
Definition at line 448 of file CCGSubSurf.c.
References CCGVert::edges, i, and CCGVert::numEdges.
Referenced by _edge_unlinkMarkAndFree().
static void _vert_remFace (CCGVert * v, CCGFace * f) [static]
Definition at line 458 of file CCGSubSurf.c.
References CCGVert::faces, i, and CCGVert::numFaces.
Referenced by _face_unlinkMarkAndFree().
static int ccg_edgebase (int level) [static]
Definition at line 267 of file CCGSubSurf.c.
References BLI_assert.
Referenced by _edge_getCo(), _edge_getCoVert(), _edge_getNo(), _edge_new(), and ccgSubSurf_getEdgeUserData().
static int ccg_edgesize (int level) [static]
Definition at line 250 of file CCGSubSurf.c.
References BLI_assert.
Referenced by ccgSubSurf__calcSubdivLevel(), ccgSubSurf__calcVertNormals(), ccgSubSurf_getEdgeLevelSize(), ccgSubSurf_getNumFinalEdges(), ccgSubSurf_getNumFinalVerts(), and ccgSubSurf_stitchFaces().
int ccg_factor (int low_level, int high_level)
Definition at line 242 of file CCGSubSurf.c.
References BLI_assert.
Referenced by multires_mdisps_downsample_hidden(), multires_mdisps_upsample_hidden(), and subsurf_copy_grid_hidden().
int ccg_gridsize (int level)
Definition at line 234 of file CCGSubSurf.c.
References BLI_assert.
Referenced by _face_getIECo(), _face_getIENo(), _face_getIFCo(), _face_getIFCoEdge(), _face_getIFNo(), _face_new(), ccgSubSurf__calcSubdivLevel(), ccgSubSurf__calcVertNormals(), ccgSubSurf_getFaceUserData(), ccgSubSurf_getGridLevelSize(), ccgSubSurf_getNumFinalEdges(), ccgSubSurf_getNumFinalFaces(), ccgSubSurf_getNumFinalVerts(), ccgSubSurf_stitchFaces(), ccgSubSurf_updateFromFaces(), ccgSubSurf_updateToFaces(), multires_mdisps_downsample_hidden(), multires_mdisps_initialize_hidden(), multires_mdisps_upsample_hidden(), and subsurf_copy_grid_hidden().
static int ccg_spacing (int high_level, int low_level) [static]
Definition at line 258 of file CCGSubSurf.c.
References BLI_assert.
Referenced by _face_getIECo(), _face_getIENo(), _face_getIFCo(), _face_getIFCoEdge(), and _face_getIFNo().
void ccgEdgeIterator_free (CCGEdgeIterator * vi)
Definition at line 3002 of file CCGSubSurf.c.
References _ehashIterator_free().
Referenced by ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_drawVerts(), ccgDM_foreachMappedEdge(), and ccgDM_getMinMax().
CCGEdge* ccgEdgeIterator_getCurrent (CCGEdgeIterator * vi)
Definition at line 2990 of file CCGSubSurf.c.
References _ehashIterator_getCurrent().
Referenced by ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_drawVerts(), ccgDM_foreachMappedEdge(), ccgDM_getMinMax(), ccgdm_getVertCos(), and getCCGDerivedMesh().
int ccgEdgeIterator_isStopped (CCGEdgeIterator * vi)
Definition at line 2994 of file CCGSubSurf.c.
References _ehashIterator_isStopped().
Referenced by ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_drawVerts(), ccgDM_foreachMappedEdge(), ccgDM_getMinMax(), ccgdm_getVertCos(), and getCCGDerivedMesh().
void ccgEdgeIterator_next (CCGEdgeIterator * vi)
Definition at line 2998 of file CCGSubSurf.c.
References _ehashIterator_next().
Referenced by ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_drawVerts(), ccgDM_foreachMappedEdge(), ccgDM_getMinMax(), ccgdm_getVertCos(), and getCCGDerivedMesh().
void ccgFaceIterator_free (CCGFaceIterator * vi)
Definition at line 3019 of file CCGSubSurf.c.
References _ehashIterator_free().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedFaceCenter(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and set_subsurf_uv().
CCGFace* ccgFaceIterator_getCurrent (CCGFaceIterator * vi)
Definition at line 3007 of file CCGSubSurf.c.
References _ehashIterator_getCurrent().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedFaceCenter(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and set_subsurf_uv().
int ccgFaceIterator_isStopped (CCGFaceIterator * vi)
Definition at line 3011 of file CCGSubSurf.c.
References _ehashIterator_isStopped().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedFaceCenter(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and set_subsurf_uv().
void ccgFaceIterator_next (CCGFaceIterator * vi)
Definition at line 3015 of file CCGSubSurf.c.
References _ehashIterator_next().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedFaceCenter(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and set_subsurf_uv().
static void ccgSubSurf__allFaces (CCGSubSurf * ss, CCGFace *** faces, int * numFaces, int * freeFaces) [static]
Definition at line 2339 of file CCGSubSurf.c.
References _EHash::buckets, _EHash::curSize, CCGSubSurf::fMap, i, MEM_mallocN(), CCGFace::next, and _EHash::numEntries.
Referenced by ccgSubSurf_stitchFaces(), ccgSubSurf_updateFromFaces(), ccgSubSurf_updateLevels(), ccgSubSurf_updateNormals(), and ccgSubSurf_updateToFaces().
static void ccgSubSurf__calcSubdivLevel (CCGSubSurf * ss, CCGVert ** effectedV, CCGEdge ** effectedE, CCGFace ** effectedF, int numEffectedV, int numEffectedE, int numEffectedF, int curLvl) [static]
Definition at line 1557 of file CCGSubSurf.c.
References _edge_getCoVert(), _edge_isBoundary(), _face_getEdgeIndex(), _face_getIFCoEdge(), _face_getVertIndex(), _vert_isBoundary(), ccg_edgesize(), ccg_gridsize(), co, EDGE_getCo, EDGE_getSharpness(), CCGVert::edges, FACE_getCenterData(), FACE_getEdges(), FACE_getIECo, FACE_getIFCo, FACE_getVerts(), CCGEdge::faces, CCGVert::faces, i, MEM_freeN(), MEM_mallocN(), CCGSubSurf::meshIFC, CCGVert::numEdges, CCGVert::numFaces, CCGEdge::numFaces, CCGFace::numVerts, CCGSubSurf::q, CCGSubSurf::r, CCGSubSurf::subdivLevels, CCGEdge::v0, CCGEdge::v1, VERT_getCo, VERT_seam(), VertDataAdd, VertDataAvg4, VertDataCopy, VertDataMulN, CCGMeshIFC::vertDataSize, VertDataSub, and VertDataZero.
Referenced by ccgSubSurf__sync(), and ccgSubSurf_updateLevels().
static void ccgSubSurf__calcVertNormals (CCGSubSurf * ss, CCGVert ** effectedV, CCGEdge ** effectedE, CCGFace ** effectedF, int numEffectedV, int numEffectedE, int numEffectedF) [static]
Definition at line 1343 of file CCGSubSurf.c.
References _face_getEdgeIndex(), _face_getIFNoEdge(), _face_getVertIndex(), _vert_getNo(), ccg_edgesize(), ccg_gridsize(), Edge_eEffected, EDGE_getNo, EPSILON, FACE_calcIFNo, FACE_getCenterData(), FACE_getEdges(), FACE_getIENo, FACE_getIFNo, FACE_getVerts(), CCGEdge::faces, CCGVert::faces, CCGEdge::flags, CCGVert::flags, i, K, length(), CCGSubSurf::meshIFC, NormAdd, CCGSubSurf::normalDataOffset, NormCopy, NormZero, CCGVert::numFaces, CCGEdge::numFaces, CCGFace::numVerts, sqrtf, CCGSubSurf::subdivLevels, Vert_eEffected, VertDataCopy, and CCGMeshIFC::vertDataSize.
Referenced by ccgSubSurf__sync(), and ccgSubSurf_updateNormals().
static void ccgSubSurf__effectedFaceNeighbours (CCGSubSurf * ss, CCGFace ** faces, int numFaces, CCGVert *** verts, int * numVerts, CCGEdge *** edges, int * numEdges) [static]
Definition at line 2363 of file CCGSubSurf.c.
References _EHash::buckets, _EHash::curSize, Edge_eEffected, CCGSubSurf::eMap, Face_eEffected, CCGEdge::faces, CCGVert::faces, CCGEdge::flags, CCGFace::flags, CCGVert::flags, i, MEM_mallocN(), CCGVert::next, CCGEdge::next, _EHash::numEntries, CCGVert::numFaces, CCGEdge::numFaces, Vert_eEffected, and CCGSubSurf::vMap.
Referenced by ccgSubSurf_stitchFaces(), ccgSubSurf_updateLevels(), and ccgSubSurf_updateNormals().
static void ccgSubSurf__sync (CCGSubSurf * ss) [static]
Definition at line 2057 of file CCGSubSurf.c.
References _edge_getCoVert(), _edge_getOtherVert(), _edge_isBoundary(), _vert_isBoundary(), _EHash::buckets, CCGSubSurf::calcVertNormals, ccgSubSurf__calcSubdivLevel(), ccgSubSurf__calcVertNormals(), ccgSubSurf_getEdgeUserData(), ccgSubSurf_getFaceUserData(), ccgSubSurf_getVertUserData(), co, CCGSubSurf::currentAge, _EHash::curSize, Edge_eEffected, EDGE_getCo, EDGE_getSharpness(), CCGVert::edges, CCGSubSurf::edgeUserAgeOffset, CCGSubSurf::eMap, Face_eEffected, FACE_getCenterData(), FACE_getEdges(), FACE_getIECo, FACE_getIFCo, FACE_getVerts(), CCGEdge::faces, CCGVert::faces, CCGSubSurf::faceUserAgeOffset, CCGEdge::flags, CCGFace::flags, CCGVert::flags, CCGSubSurf::fMap, i, MEM_freeN(), MEM_mallocN(), CCGSubSurf::meshIFC, CCGVert::next, CCGVert::numEdges, _EHash::numEntries, CCGVert::numFaces, CCGEdge::numFaces, CCGFace::numVerts, CCGSubSurf::q, CCGSubSurf::r, CCGSubSurf::subdivLevels, CCGSubSurf::useAgeCounts, CCGEdge::v0, CCGEdge::v1, Vert_eEffected, VERT_getCo, VERT_seam(), VertDataAdd, VertDataCopy, VertDataMulN, CCGMeshIFC::vertDataSize, VertDataSub, VertDataZero, CCGSubSurf::vertUserAgeOffset, and CCGSubSurf::vMap.
Referenced by ccgSubSurf_processSync().
void ccgSubSurf_free (CCGSubSurf * ss)
Definition at line 831 of file CCGSubSurf.c.
References _edge_free(), _ehash_free(), _face_free(), _vert_free(), CCGSubSurf::allocator, CCGSubSurf::allocatorIFC, CCGSUBSURF_free, CCGSubSurf::defaultEdgeUserData, CCGSubSurf::eMap, CCGSubSurf::fMap, MEM_freeN(), CCGSubSurf::oldEMap, CCGSubSurf::oldFMap, CCGSubSurf::oldVMap, CCGSubSurf::q, CCGSubSurf::r, CCGAllocatorIFC::release, CCGSubSurf::syncState, CCGSubSurf::tempEdges, CCGSubSurf::tempVerts, and CCGSubSurf::vMap.
Referenced by _getSubSurf(), ccgDM_release(), freeData(), set_subsurf_uv(), subsurf_calculate_limit_positions(), and subsurf_make_derived_from_derived().
void ccgSubSurf_getAllowEdgeCreation (CCGSubSurf * ss, int * allowEdgeCreation_r, float * defaultCreaseValue_r, void * defaultUserData_r)
Definition at line 879 of file CCGSubSurf.c.
References CCGSubSurf::allowEdgeCreation, CCGSubSurf::defaultCreaseValue, CCGSubSurf::defaultEdgeUserData, CCGMeshIFC::edgeUserSize, and CCGSubSurf::meshIFC.
CCGEdge* ccgSubSurf_getEdge (CCGSubSurf * ss, CCGEdgeHDL e)
Definition at line 2719 of file CCGSubSurf.c.
References _ehash_lookup(), and CCGSubSurf::eMap.
int ccgSubSurf_getEdgeAge (CCGSubSurf * ss, CCGEdge * e)
Definition at line 2825 of file CCGSubSurf.c.
References ccgSubSurf_getEdgeUserData(), CCGSubSurf::currentAge, CCGSubSurf::edgeUserAgeOffset, and CCGSubSurf::useAgeCounts.
Referenced by ccgDM_drawEdges(), ccgDM_drawMappedEdges(), and ccgDM_drawMappedEdgesInterp().
float ccgSubSurf_getEdgeCrease (CCGEdge * e)
Definition at line 2878 of file CCGSubSurf.c.
References CCGEdge::crease.
Referenced by ss_sync_from_uv().
void* ccgSubSurf_getEdgeData (CCGSubSurf * ss, CCGEdge * e, int x)
Definition at line 2865 of file CCGSubSurf.c.
References ccgSubSurf_getEdgeLevelData(), and CCGSubSurf::subdivLevels.
Referenced by ccgDM_copyFinalVertArray(), ccgDM_drawVerts(), ccgDM_getFinalVert(), ccgdm_getVertCos(), ccgSubSurf_getEdgeDataArray(), multires_mvert_to_ss(), and subsurf_calculate_limit_positions().
void* ccgSubSurf_getEdgeDataArray (CCGSubSurf * ss, CCGEdge * e)
Definition at line 2861 of file CCGSubSurf.c.
References ccgSubSurf_getEdgeData().
Referenced by ccgDM_drawEdges(), ccgDM_drawLooseEdges(), ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_foreachMappedEdge(), and ccgDM_getMinMax().
CCGEdgeHDL ccgSubSurf_getEdgeEdgeHandle (CCGEdge * e)
Definition at line 2821 of file CCGSubSurf.c.
References CCGEdge::eHDL.
Referenced by ccgDM_copyFinalEdgeArray(), ccgdm_getVertCos(), and getCCGDerivedMesh().
CCGFace* ccgSubSurf_getEdgeFace (CCGEdge * e, int index)
Definition at line 2844 of file CCGSubSurf.c.
References CCGEdge::faces, NULL, and CCGEdge::numFaces.
Referenced by ccgdm_adjacent_grid().
CCGEdgeIterator* ccgSubSurf_getEdgeIterator (CCGSubSurf * ss)
Definition at line 2964 of file CCGSubSurf.c.
References _ehashIterator_new(), and CCGSubSurf::eMap.
Referenced by ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_drawVerts(), ccgDM_foreachMappedEdge(), ccgDM_getMinMax(), ccgdm_getVertCos(), and getCCGDerivedMesh().
void* ccgSubSurf_getEdgeLevelData (CCGSubSurf * ss, CCGEdge * e, int x, int level)
Definition at line 2869 of file CCGSubSurf.c.
References _edge_getCo(), CCGSubSurf::meshIFC, NULL, CCGSubSurf::subdivLevels, and CCGMeshIFC::vertDataSize.
Referenced by ccgSubSurf_getEdgeData().
int ccgSubSurf_getEdgeLevelSize (const CCGSubSurf * ss, int level)
Definition at line 2736 of file CCGSubSurf.c.
References ccg_edgesize(), and CCGSubSurf::subdivLevels.
Referenced by ccgSubSurf_getEdgeSize().
int ccgSubSurf_getEdgeNumFaces (CCGEdge * e)
Definition at line 2840 of file CCGSubSurf.c.
References CCGEdge::numFaces.
Referenced by ccgdm_adjacent_grid(), ccgDM_copyFinalEdgeArray(), ccgDM_drawEdges(), ccgDM_drawLooseEdges(), and ccgDM_getFinalEdge().
int ccgSubSurf_getEdgeSize (const CCGSubSurf * ss)
Definition at line 2732 of file CCGSubSurf.c.
References ccgSubSurf_getEdgeLevelSize(), and CCGSubSurf::subdivLevels.
Referenced by ccgDM_copyFinalEdgeArray(), ccgDM_copyFinalFaceArray(), ccgDM_copyFinalLoopArray(), ccgDM_copyFinalVertArray(), ccgDM_drawEdges(), ccgDM_drawLooseEdges(), ccgDM_drawMappedEdges(), ccgDM_drawMappedEdgesInterp(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgDM_drawVerts(), ccgDM_foreachMappedEdge(), ccgDM_get_edge_data_layer(), ccgDM_getFinalEdge(), ccgDM_getFinalFace(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), multires_mvert_to_ss(), and subsurf_copy_grid_hidden().
void* ccgSubSurf_getEdgeUserData (CCGSubSurf * ss, CCGEdge * e)
Definition at line 2835 of file CCGSubSurf.c.
References ccg_edgebase(), EDGE_getLevelData(), CCGSubSurf::meshIFC, CCGSubSurf::subdivLevels, and CCGMeshIFC::vertDataSize.
Referenced by _edge_new(), ccgDM_getEdgeMapIndex(), ccgSubSurf__sync(), ccgSubSurf_getEdgeAge(), ccgSubSurf_syncFace(), getCCGDerivedMesh(), getEdgeIndex(), getFaceIndex(), and ss_sync_from_derivedmesh().
CCGVert* ccgSubSurf_getEdgeVert0 (CCGEdge * e)
Definition at line 2853 of file CCGSubSurf.c.
References CCGEdge::v0.
Referenced by getCCGDerivedMesh(), getEdgeIndex(), and getFaceIndex().
CCGVert* ccgSubSurf_getEdgeVert1 (CCGEdge * e)
Definition at line 2857 of file CCGSubSurf.c.
References CCGEdge::v1.
Referenced by getCCGDerivedMesh(), and getEdgeIndex().
CCGFace* ccgSubSurf_getFace (CCGSubSurf * ss, CCGFaceHDL f)
Definition at line 2723 of file CCGSubSurf.c.
References _ehash_lookup(), and CCGSubSurf::fMap.
Referenced by ss_sync_from_uv().
int ccgSubSurf_getFaceAge (CCGSubSurf * ss, CCGFace * f)
Definition at line 2889 of file CCGSubSurf.c.
References ccgSubSurf_getFaceUserData(), CCGSubSurf::currentAge, CCGSubSurf::faceUserAgeOffset, and CCGSubSurf::useAgeCounts.
void* ccgSubSurf_getFaceCenterData (CCGFace * f)
Definition at line 2937 of file CCGSubSurf.c.
References FACE_getCenterData().
Referenced by ccgDM_copyFinalVertArray(), ccgDM_drawVerts(), ccgDM_getFinalVert(), ccgdm_getVertCos(), multires_mvert_to_ss(), and subsurf_calculate_limit_positions().
CCGEdge* ccgSubSurf_getFaceEdge (CCGFace * f, int index)
Definition at line 2917 of file CCGSubSurf.c.
References FACE_getEdges(), NULL, and CCGFace::numVerts.
Referenced by ccgdm_adjacent_grid(), getFaceIndex(), and ss_sync_from_uv().
int ccgSubSurf_getFaceEdgeIndex (CCGFace * f, CCGEdge * e)
Definition at line 2926 of file CCGSubSurf.c.
References FACE_getEdges(), i, and CCGFace::numVerts.
CCGFaceHDL ccgSubSurf_getFaceFaceHandle (CCGFace * f)
Definition at line 2885 of file CCGSubSurf.c.
References CCGFace::fHDL.
Referenced by ccgdm_adjacent_grid(), ccgDM_drawFacesSolid(), ccgDM_drawFacesTex_common(), ccgDM_drawMappedFaces(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgdm_getVertCos(), getCCGDerivedMesh(), and set_subsurf_uv().
void* ccgSubSurf_getFaceGridData (CCGSubSurf * ss, CCGFace * f, int gridIndex, int x, int y)
Definition at line 2953 of file CCGSubSurf.c.
References _face_getIFCo(), CCGSubSurf::meshIFC, CCGSubSurf::subdivLevels, and CCGMeshIFC::vertDataSize.
Referenced by ccgDM_copyFinalVertArray(), ccgDM_drawVerts(), ccgDM_foreachMappedFaceCenter(), ccgDM_getFinalVert(), ccgdm_getVertCos(), ccgSubSurf_getFaceGridDataArray(), and multires_mvert_to_ss().
void* ccgSubSurf_getFaceGridDataArray (CCGSubSurf * ss, CCGFace * f, int gridIndex)
Definition at line 2949 of file CCGSubSurf.c.
References ccgSubSurf_getFaceGridData().
Referenced by ccgdm_create_grids(), ccgDM_drawEdges(), ccgDM_drawFacesSolid(), ccgDM_drawFacesTex_common(), ccgDM_drawMappedFaces(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgDM_getMinMax(), and set_subsurf_uv().
void* ccgSubSurf_getFaceGridEdgeData (CCGSubSurf * ss, CCGFace * f, int gridIndex, int x)
Definition at line 2945 of file CCGSubSurf.c.
References _face_getIECo(), CCGSubSurf::meshIFC, CCGSubSurf::subdivLevels, and CCGMeshIFC::vertDataSize.
Referenced by ccgDM_copyFinalVertArray(), ccgDM_drawVerts(), ccgDM_getFinalVert(), ccgdm_getVertCos(), ccgSubSurf_getFaceGridEdgeDataArray(), and multires_mvert_to_ss().
void* ccgSubSurf_getFaceGridEdgeDataArray (CCGSubSurf * ss, CCGFace * f, int gridIndex)
Definition at line 2941 of file CCGSubSurf.c.
References ccgSubSurf_getFaceGridEdgeData().
CCGFaceIterator* ccgSubSurf_getFaceIterator (CCGSubSurf * ss)
Definition at line 2968 of file CCGSubSurf.c.
References _ehashIterator_new(), and CCGSubSurf::fMap.
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedFaceCenter(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and set_subsurf_uv().
int ccgSubSurf_getFaceNumVerts (CCGFace * f)
Definition at line 2904 of file CCGSubSurf.c.
References CCGFace::numVerts.
Referenced by ccgdm_adjacent_grid(), ccgDM_copyFinalEdgeArray(), ccgDM_copyFinalFaceArray(), ccgDM_copyFinalLoopArray(), ccgDM_copyFinalPolyArray(), ccgDM_copyFinalVertArray(), ccgdm_create_grids(), ccgDM_drawEdges(), ccgDM_drawFacesSolid(), ccgDM_drawFacesTex_common(), ccgDM_drawMappedFaces(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgDM_drawVerts(), ccgDM_get_tessface_data_layer(), ccgDM_getFinalVert(), ccgDM_getMinMax(), ccgDM_getNumGrids(), ccgdm_getVertCos(), getCCGDerivedMesh(), getFaceIndex(), multires_mvert_to_ss(), and set_subsurf_uv().
void* ccgSubSurf_getFaceUserData (CCGSubSurf * ss, CCGFace * f)
Definition at line 2899 of file CCGSubSurf.c.
References ccg_gridsize(), FACE_getCenterData(), CCGSubSurf::meshIFC, CCGFace::numVerts, CCGSubSurf::subdivLevels, and CCGMeshIFC::vertDataSize.
Referenced by _face_new(), ccgDM_getFaceMapIndex(), ccgSubSurf__sync(), ccgSubSurf_getFaceAge(), getCCGDerivedMesh(), getFaceIndex(), and ss_sync_from_derivedmesh().
CCGVert* ccgSubSurf_getFaceVert (CCGFace * f, int index)
Definition at line 2908 of file CCGSubSurf.c.
References FACE_getVerts(), NULL, and CCGFace::numVerts.
Referenced by getCCGDerivedMesh(), and getFaceIndex().
int ccgSubSurf_getGridLevelSize (const CCGSubSurf * ss, int level)
Definition at line 2749 of file CCGSubSurf.c.
References ccg_gridsize(), and CCGSubSurf::subdivLevels.
Referenced by ccgSubSurf_getGridSize().
int ccgSubSurf_getGridSize (const CCGSubSurf * ss)
Definition at line 2745 of file CCGSubSurf.c.
References ccgSubSurf_getGridLevelSize(), and CCGSubSurf::subdivLevels.
Referenced by ccgDM_copyFinalEdgeArray(), ccgDM_copyFinalFaceArray(), ccgDM_copyFinalLoopArray(), ccgDM_copyFinalPolyArray(), ccgDM_copyFinalVertArray(), ccgDM_drawEdges(), ccgDM_drawFacesSolid(), ccgDM_drawFacesTex_common(), ccgDM_drawMappedFaces(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgDM_drawVerts(), ccgDM_get_tessface_data_layer(), ccgDM_getFinalEdge(), ccgDM_getFinalFace(), ccgDM_getFinalVert(), ccgDM_getGridSize(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), multires_mvert_to_ss(), set_subsurf_uv(), and subsurf_copy_grid_hidden().
int ccgSubSurf_getNumEdges (const CCGSubSurf * ss)
Definition at line 2706 of file CCGSubSurf.c.
References CCGSubSurf::eMap, and _EHash::numEntries.
Referenced by ccgDM_copyFinalEdgeArray(), ccgDM_copyFinalVertArray(), ccgDM_drawEdges(), ccgDM_drawLooseEdges(), ccgDM_get_edge_data_layer(), ccgDM_getFinalVert(), ccgdm_getVertCos(), getCCGDerivedMesh(), and multires_mvert_to_ss().
int ccgSubSurf_getNumFaces (const CCGSubSurf * ss)
Definition at line 2710 of file CCGSubSurf.c.
References CCGSubSurf::fMap, and _EHash::numEntries.
Referenced by ccgDM_copyFinalEdgeArray(), ccgDM_copyFinalFaceArray(), ccgDM_copyFinalLoopArray(), ccgDM_copyFinalPolyArray(), ccgDM_copyFinalVertArray(), ccgdm_create_grids(), ccgDM_drawEdges(), ccgDM_drawFacesSolid(), ccgDM_drawFacesTex_common(), ccgDM_drawMappedFaces(), ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), ccgDM_get_tessface_data_layer(), ccgDM_getFinalEdge(), ccgDM_getFinalVert(), ccgDM_getNumGrids(), ccgdm_getVertCos(), getCCGDerivedMesh(), multires_mvert_to_ss(), set_subsurf_uv(), and subsurf_copy_grid_hidden().
int ccgSubSurf_getNumFinalEdges (const CCGSubSurf * ss)
Definition at line 3037 of file CCGSubSurf.c.
References ccg_edgesize(), ccg_gridsize(), CCGSubSurf::eMap, _EHash::numEntries, CCGSubSurf::numGrids, and CCGSubSurf::subdivLevels.
Referenced by ccgDM_getNumEdges(), and getCCGDerivedMesh().
int ccgSubSurf_getNumFinalFaces (const CCGSubSurf * ss)
Definition at line 3046 of file CCGSubSurf.c.
References ccg_gridsize(), CCGSubSurf::numGrids, and CCGSubSurf::subdivLevels.
Referenced by ccgDM_getNumLoops(), ccgDM_getNumTessFaces(), and getCCGDerivedMesh().
int ccgSubSurf_getNumFinalVerts (const CCGSubSurf * ss)
Definition at line 3026 of file CCGSubSurf.c.
References ccg_edgesize(), ccg_gridsize(), CCGSubSurf::eMap, CCGSubSurf::fMap, _EHash::numEntries, CCGSubSurf::numGrids, CCGSubSurf::subdivLevels, and CCGSubSurf::vMap.
Referenced by ccgDM_getNumVerts(), and getCCGDerivedMesh().
int ccgSubSurf_getNumVerts (const CCGSubSurf * ss)
Definition at line 2702 of file CCGSubSurf.c.
References _EHash::numEntries, and CCGSubSurf::vMap.
Referenced by ccgDM_copyFinalVertArray(), ccgDM_get_vert_data_layer(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and multires_mvert_to_ss().
int ccgSubSurf_getSubdivisionLevels (const CCGSubSurf * ss)
Definition at line 2728 of file CCGSubSurf.c.
References CCGSubSurf::subdivLevels.
Referenced by set_subsurf_uv(), ss_sync_from_derivedmesh(), ss_sync_from_uv(), and subsurf_copy_grid_hidden().
void ccgSubSurf_getUseAgeCounts (CCGSubSurf * ss, int * useAgeCounts_r, int * vertUserOffset_r, int * edgeUserOffset_r, int * faceUserOffset_r)
Definition at line 907 of file CCGSubSurf.c.
References CCGSubSurf::edgeUserAgeOffset, CCGSubSurf::faceUserAgeOffset, CCGSubSurf::useAgeCounts, and CCGSubSurf::vertUserAgeOffset.
Referenced by _getSubSurf(), ccgDM_drawEdges(), ccgDM_drawMappedEdges(), and ccgDM_drawMappedEdgesInterp().
CCGVert* ccgSubSurf_getVert (CCGSubSurf * ss, CCGVertHDL v)
Definition at line 2715 of file CCGSubSurf.c.
References _ehash_lookup(), and CCGSubSurf::vMap.
int ccgSubSurf_getVertAge (CCGSubSurf * ss, CCGVert * v)
Definition at line 2765 of file CCGSubSurf.c.
References ccgSubSurf_getVertUserData(), CCGSubSurf::currentAge, CCGSubSurf::useAgeCounts, and CCGSubSurf::vertUserAgeOffset.
void* ccgSubSurf_getVertData (CCGSubSurf * ss, CCGVert * v)
Definition at line 2805 of file CCGSubSurf.c.
References ccgSubSurf_getVertLevelData(), and CCGSubSurf::subdivLevels.
Referenced by ccgDM_copyFinalVertArray(), ccgDM_drawVerts(), ccgDM_foreachMappedVert(), ccgDM_getFinalVert(), ccgDM_getMinMax(), ccgdm_getVertCos(), multires_mvert_to_ss(), and subsurf_calculate_limit_positions().
CCGEdge* ccgSubSurf_getVertEdge (CCGVert * v, int index)
Definition at line 2796 of file CCGSubSurf.c.
References CCGVert::edges, NULL, and CCGVert::numEdges.
Referenced by subsurf_calculate_limit_positions().
CCGFace* ccgSubSurf_getVertFace (CCGVert * v, int index)
Definition at line 2783 of file CCGSubSurf.c.
References CCGVert::faces, NULL, and CCGVert::numFaces.
Referenced by subsurf_calculate_limit_positions().
CCGVertIterator* ccgSubSurf_getVertIterator (CCGSubSurf * ss)
Definition at line 2960 of file CCGSubSurf.c.
References _ehashIterator_new(), and CCGSubSurf::vMap.
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedVert(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and subsurf_calculate_limit_positions().
void* ccgSubSurf_getVertLevelData (CCGSubSurf * ss, CCGVert * v, int level)
Definition at line 2809 of file CCGSubSurf.c.
References _vert_getCo(), CCGSubSurf::meshIFC, NULL, CCGSubSurf::subdivLevels, and CCGMeshIFC::vertDataSize.
Referenced by ccgSubSurf_getVertData().
int ccgSubSurf_getVertNumEdges (CCGVert * v)
Definition at line 2792 of file CCGSubSurf.c.
References CCGVert::numEdges.
Referenced by subsurf_calculate_limit_positions().
int ccgSubSurf_getVertNumFaces (CCGVert * v)
Definition at line 2779 of file CCGSubSurf.c.
References CCGVert::numFaces.
Referenced by subsurf_calculate_limit_positions().
void* ccgSubSurf_getVertUserData (CCGSubSurf * ss, CCGVert * v)
Definition at line 2775 of file CCGSubSurf.c.
References CCGSubSurf::meshIFC, CCGSubSurf::subdivLevels, VERT_getLevelData(), and CCGMeshIFC::vertDataSize.
Referenced by _vert_new(), ccgDM_getVertMapIndex(), ccgSubSurf__sync(), ccgSubSurf_getVertAge(), getCCGDerivedMesh(), getEdgeIndex(), getFaceIndex(), and ss_sync_from_derivedmesh().
CCGVertHDL ccgSubSurf_getVertVertHandle (CCGVert * v)
Definition at line 2761 of file CCGSubSurf.c.
References CCGVert::vHDL.
Referenced by ccgdm_getVertCos(), getCCGDerivedMesh(), and subsurf_calculate_limit_positions().
CCGError ccgSubSurf_initFullSync (CCGSubSurf * ss)
Definition at line 961 of file CCGSubSurf.c.
References _ehash_new(), CCGSubSurf::allocator, CCGSubSurf::allocatorIFC, CCGSubSurf::currentAge, eCCGError_InvalidSyncState, eCCGError_None, CCGSubSurf::eMap, eSyncState_None, eSyncState_Vert, CCGSubSurf::fMap, CCGSubSurf::lenTempArrays, MEM_mallocN(), CCGSubSurf::numGrids, CCGSubSurf::oldEMap, CCGSubSurf::oldFMap, CCGSubSurf::oldVMap, CCGSubSurf::syncState, CCGSubSurf::tempEdges, CCGSubSurf::tempVerts, and CCGSubSurf::vMap.
Referenced by ss_sync_from_derivedmesh(), and ss_sync_from_uv().
CCGError ccgSubSurf_initPartialSync (CCGSubSurf * ss)
Definition at line 988 of file CCGSubSurf.c.
References CCGSubSurf::currentAge, eCCGError_InvalidSyncState, eCCGError_None, eSyncState_None, eSyncState_Partial, and CCGSubSurf::syncState.
CCGSubSurf* ccgSubSurf_new (CCGMeshIFC * ifc, int subdivLevels, CCGAllocatorIFC * allocatorIFC, CCGAllocatorHDL allocator)
Definition at line 781 of file CCGSubSurf.c.
References _ehash_new(), _getStandardAllocatorIFC(), CCGAllocatorIFC::alloc, CCGSubSurf::allocator, CCGSubSurf::allocatorIFC, CCGSubSurf::allowEdgeCreation, CCGSubSurf::calcVertNormals, CCGSUBSURF_alloc, CCGSubSurf::currentAge, CCGSubSurf::defaultCreaseValue, CCGSubSurf::defaultEdgeUserData, CCGSubSurf::edgeUserAgeOffset, CCGSubSurf::eMap, eSyncState_None, CCGSubSurf::faceUserAgeOffset, CCGSubSurf::fMap, CCGSubSurf::lenTempArrays, CCGSubSurf::meshIFC, CCGSubSurf::normalDataOffset, NULL, CCGSubSurf::numGrids, CCGSubSurf::oldEMap, CCGSubSurf::oldFMap, CCGSubSurf::oldVMap, CCGSubSurf::q, CCGSubSurf::r, CCGSubSurf::subdivLevels, CCGSubSurf::syncState, CCGSubSurf::tempEdges, CCGSubSurf::tempVerts, CCGSubSurf::useAgeCounts, CCGMeshIFC::vertDataSize, CCGSubSurf::vertUserAgeOffset, and CCGSubSurf::vMap.
Referenced by _getSubSurf().
CCGError ccgSubSurf_processSync (CCGSubSurf * ss)
Definition at line 1306 of file CCGSubSurf.c.
References _edge_unlinkMarkAndFree(), _ehash_free(), _face_unlinkMarkAndFree(), _vert_free(), ccgSubSurf__sync(), eCCGError_InvalidSyncState, eCCGError_None, eSyncState_None, eSyncState_Partial, CCGSubSurf::lenTempArrays, MEM_freeN(), NULL, CCGSubSurf::oldEMap, CCGSubSurf::oldFMap, CCGSubSurf::oldVMap, CCGSubSurf::syncState, CCGSubSurf::tempEdges, and CCGSubSurf::tempVerts.
Referenced by ss_sync_from_derivedmesh(), and ss_sync_from_uv().
CCGError ccgSubSurf_setAllowEdgeCreation (CCGSubSurf * ss, int allowEdgeCreation, float defaultCreaseValue, void * defaultUserData)
Definition at line 860 of file CCGSubSurf.c.
References CCGSubSurf::allowEdgeCreation, CCGSUBSURF_alloc, CCGSUBSURF_free, CCGSubSurf::defaultCreaseValue, CCGSubSurf::defaultEdgeUserData, eCCGError_None, CCGMeshIFC::edgeUserSize, and CCGSubSurf::meshIFC.
CCGError ccgSubSurf_setCalcVertexNormals (CCGSubSurf * ss, int useVertNormals, int normalDataOffset)
Definition at line 940 of file CCGSubSurf.c.
References CCGSubSurf::calcVertNormals, eCCGError_InvalidValue, eCCGError_None, CCGSubSurf::meshIFC, CCGSubSurf::normalDataOffset, and CCGMeshIFC::vertDataSize.
Referenced by _getSubSurf().
CCGError ccgSubSurf_setSubdivisionLevels (CCGSubSurf * ss, int subdivisionLevels)
Definition at line 888 of file CCGSubSurf.c.
References _edge_free(), _ehash_free(), _ehash_new(), _face_free(), _vert_free(), CCGSubSurf::allocator, CCGSubSurf::allocatorIFC, eCCGError_InvalidValue, eCCGError_None, CCGSubSurf::eMap, CCGSubSurf::fMap, CCGSubSurf::numGrids, CCGSubSurf::subdivLevels, and CCGSubSurf::vMap.
Referenced by _getSubSurf().
CCGError ccgSubSurf_setUseAgeCounts (CCGSubSurf * ss, int useAgeCounts, int vertUserOffset, int edgeUserOffset, int faceUserOffset)
Definition at line 916 of file CCGSubSurf.c.
References eCCGError_InvalidValue, eCCGError_None, CCGSubSurf::edgeUserAgeOffset, CCGMeshIFC::edgeUserSize, CCGSubSurf::faceUserAgeOffset, CCGMeshIFC::faceUserSize, CCGSubSurf::meshIFC, CCGSubSurf::useAgeCounts, CCGSubSurf::vertUserAgeOffset, and CCGMeshIFC::vertUserSize.
Referenced by _getSubSurf().
CCGError ccgSubSurf_stitchFaces (CCGSubSurf * ss, int lvl, CCGFace ** effectedF, int numEffectedF)
Definition at line 2497 of file CCGSubSurf.c.
References _edge_getCoVert(), ccg_edgesize(), ccg_gridsize(), ccgSubSurf__allFaces(), ccgSubSurf__effectedFaceNeighbours(), eCCGError_None, Edge_eEffected, EDGE_getCo, FACE_getCenterData(), FACE_getEdges(), FACE_getIECo, FACE_getIFCo, FACE_getVerts(), i, MEM_freeN(), CCGSubSurf::meshIFC, CCGVert::numFaces, CCGEdge::numFaces, CCGFace::numVerts, CCGSubSurf::subdivLevels, CCGEdge::v0, CCGEdge::v1, Vert_eEffected, VERT_getCo, VertDataAdd, VertDataCopy, VertDataMulN, CCGMeshIFC::vertDataSize, and VertDataZero.
Referenced by multires_stitch_grids(), and multiresModifier_disp_run().
CCGError ccgSubSurf_syncEdge (CCGSubSurf * ss, CCGEdgeHDL eHDL, CCGVertHDL e_vHDL0, CCGVertHDL e_vHDL1, float crease, CCGEdge ** e_r)
Definition at line 1126 of file CCGSubSurf.c.
References _edge_new(), _edge_unlinkMarkAndFree(), _ehash_insert(), _ehash_lookup(), _ehash_lookupWithPrev(), CCGEdge::crease, eCCGError_InvalidSyncState, eCCGError_None, CCGSubSurf::eMap, eSyncState_Edge, eSyncState_Partial, eSyncState_Vert, CCGEdge::next, NULL, CCGSubSurf::oldEMap, CCGSubSurf::syncState, CCGEdge::v0, CCGEdge::v1, Vert_eChanged, Vert_eEffected, CCGVert::vHDL, and CCGSubSurf::vMap.
Referenced by ss_sync_from_derivedmesh(), and ss_sync_from_uv().
CCGError ccgSubSurf_syncEdgeDel (CCGSubSurf * ss, CCGEdgeHDL eHDL)
Definition at line 1022 of file CCGSubSurf.c.
References _edge_unlinkMarkAndFree(), _ehash_lookupWithPrev(), eCCGError_InvalidSyncState, eCCGError_InvalidValue, eCCGError_None, CCGSubSurf::eMap, eSyncState_Partial, CCGEdge::next, CCGEdge::numFaces, and CCGSubSurf::syncState.
CCGError ccgSubSurf_syncFace (CCGSubSurf * ss, CCGFaceHDL fHDL, int numVerts, CCGVertHDL * vHDLs, CCGFace ** f_r)
Definition at line 1185 of file CCGSubSurf.c.
References _edge_new(), _ehash_insert(), _ehash_lookup(), _ehash_lookupWithPrev(), _face_new(), _face_unlinkMarkAndFree(), _vert_findEdgeTo(), CCGSubSurf::allowEdgeCreation, ccgSubSurf_getEdgeUserData(), CCGSubSurf::defaultCreaseValue, CCGSubSurf::defaultEdgeUserData, eCCGError_InvalidSyncState, eCCGError_InvalidValue, eCCGError_None, CCGMeshIFC::edgeUserSize, CCGSubSurf::eMap, eSyncState_Edge, eSyncState_Face, eSyncState_Partial, eSyncState_Vert, FACE_getEdges(), FACE_getVerts(), CCGVert::flags, CCGSubSurf::fMap, CCGSubSurf::lenTempArrays, MEM_reallocN(), CCGSubSurf::meshIFC, CCGFace::next, NULL, CCGSubSurf::numGrids, CCGFace::numVerts, CCGSubSurf::oldFMap, CCGSubSurf::syncState, CCGSubSurf::tempEdges, CCGSubSurf::tempVerts, Vert_eChanged, Vert_eEffected, and CCGSubSurf::vMap.
Referenced by ss_sync_from_derivedmesh(), and ss_sync_from_uv().
CCGError ccgSubSurf_syncFaceDel (CCGSubSurf * ss, CCGFaceHDL fHDL)
Definition at line 1043 of file CCGSubSurf.c.
References _ehash_lookupWithPrev(), _face_unlinkMarkAndFree(), eCCGError_InvalidSyncState, eCCGError_InvalidValue, eCCGError_None, eSyncState_Partial, CCGSubSurf::fMap, CCGFace::next, and CCGSubSurf::syncState.
CCGError ccgSubSurf_syncVert (CCGSubSurf * ss, CCGVertHDL vHDL, const void * vertData, int seam, CCGVert ** v_r)
Definition at line 1064 of file CCGSubSurf.c.
References _ehash_insert(), _ehash_lookupWithPrev(), _vert_getCo(), _vert_new(), eCCGError_InvalidSyncState, eCCGError_None, CCGVert::edges, eSyncState_Partial, eSyncState_Vert, FACE_getVerts(), CCGVert::faces, CCGVert::flags, i, CCGSubSurf::meshIFC, CCGVert::next, NULL, CCGVert::numEdges, CCGVert::numFaces, CCGFace::numVerts, CCGSubSurf::oldVMap, CCGSubSurf::syncState, CCGEdge::v0, CCGEdge::v1, Vert_eChanged, Vert_eEffected, Vert_eSeam, VertDataCopy, VertDataEqual(), CCGMeshIFC::vertDataSize, and CCGSubSurf::vMap.
Referenced by ss_sync_from_derivedmesh(), and ss_sync_from_uv().
CCGError ccgSubSurf_syncVertDel (CCGSubSurf * ss, CCGVertHDL vHDL)
Definition at line 1001 of file CCGSubSurf.c.
References _ehash_lookupWithPrev(), _vert_free(), eCCGError_InvalidSyncState, eCCGError_InvalidValue, eCCGError_None, eSyncState_Partial, CCGVert::next, CCGVert::numEdges, CCGVert::numFaces, CCGSubSurf::syncState, and CCGSubSurf::vMap.
CCGError ccgSubSurf_updateFromFaces (CCGSubSurf * ss, int lvl, CCGFace ** effectedF, int numEffectedF)
Definition at line 2415 of file CCGSubSurf.c.
References _edge_getCoVert(), ccg_gridsize(), ccgSubSurf__allFaces(), eCCGError_None, FACE_getCenterData(), FACE_getEdges(), FACE_getIECo, FACE_getIFCo, FACE_getVerts(), i, MEM_freeN(), CCGSubSurf::meshIFC, CCGFace::numVerts, CCGSubSurf::subdivLevels, VERT_getCo, VertDataCopy, and CCGMeshIFC::vertDataSize.
Referenced by ccgdm_pbvh_update(), multires_modifier_update_mdisps(), and multires_subdivide().
CCGError ccgSubSurf_updateLevels (CCGSubSurf * ss, int lvl, CCGFace ** effectedF, int numEffectedF)
Definition at line 2664 of file CCGSubSurf.c.
References ccgSubSurf__allFaces(), ccgSubSurf__calcSubdivLevel(), ccgSubSurf__effectedFaceNeighbours(), eCCGError_None, i, MEM_freeN(), and CCGSubSurf::subdivLevels.
Referenced by multires_modifier_update_mdisps(), and multires_subdivide().
CCGError ccgSubSurf_updateNormals (CCGSubSurf * ss, CCGFace ** effectedF, int numEffectedF)
Definition at line 2632 of file CCGSubSurf.c.
References CCGSubSurf::calcVertNormals, ccgSubSurf__allFaces(), ccgSubSurf__calcVertNormals(), ccgSubSurf__effectedFaceNeighbours(), eCCGError_None, i, and MEM_freeN().
Referenced by ccgdm_pbvh_update(), and multiresModifier_disp_run().
CCGError ccgSubSurf_updateToFaces (CCGSubSurf * ss, int lvl, CCGFace ** effectedF, int numEffectedF)
Definition at line 2454 of file CCGSubSurf.c.
References _edge_getCoVert(), ccg_gridsize(), ccgSubSurf__allFaces(), eCCGError_None, FACE_getCenterData(), FACE_getEdges(), FACE_getIECo, FACE_getIFCo, FACE_getVerts(), i, MEM_freeN(), CCGSubSurf::meshIFC, CCGFace::numVerts, CCGSubSurf::subdivLevels, VERT_getCo, VertDataCopy, and CCGMeshIFC::vertDataSize.
Referenced by multires_mvert_to_ss().
void ccgVertIterator_free (CCGVertIterator * vi)
Definition at line 2985 of file CCGSubSurf.c.
References _ehashIterator_free().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedVert(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and subsurf_calculate_limit_positions().
CCGVert* ccgVertIterator_getCurrent (CCGVertIterator * vi)
Definition at line 2973 of file CCGSubSurf.c.
References _ehashIterator_getCurrent().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedVert(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and subsurf_calculate_limit_positions().
int ccgVertIterator_isStopped (CCGVertIterator * vi)
Definition at line 2977 of file CCGSubSurf.c.
References _ehashIterator_isStopped().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedVert(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and subsurf_calculate_limit_positions().
void ccgVertIterator_next (CCGVertIterator * vi)
Definition at line 2981 of file CCGSubSurf.c.
References _ehashIterator_next().
Referenced by ccgDM_drawVerts(), ccgDM_foreachMappedVert(), ccgDM_getMinMax(), ccgdm_getVertCos(), getCCGDerivedMesh(), and subsurf_calculate_limit_positions().
static CCG_INLINE byte* EDGE_getLevelData (CCGEdge * e) [static]
Definition at line 342 of file CCGSubSurf.c.
Referenced by _edge_getCo(), _edge_getCoVert(), _edge_getNo(), and ccgSubSurf_getEdgeUserData().
static float EDGE_getSharpness (CCGEdge * e, int lvl) [static]
Definition at line 613 of file CCGSubSurf.c.
References CCGEdge::crease.
Referenced by ccgSubSurf__calcSubdivLevel(), and ccgSubSurf__sync().
static CCG_INLINE byte* FACE_getCenterData (CCGFace * f) [static]
Definition at line 370 of file CCGSubSurf.c.
References FACE_getEdges().
Referenced by _face_getIECo(), _face_getIENo(), _face_getIFCo(), _face_getIFNo(), ccgSubSurf__calcSubdivLevel(), ccgSubSurf__calcVertNormals(), ccgSubSurf__sync(), ccgSubSurf_getFaceCenterData(), ccgSubSurf_getFaceUserData(), ccgSubSurf_stitchFaces(), ccgSubSurf_updateFromFaces(), and ccgSubSurf_updateToFaces().
static CCG_INLINE CCGEdge** FACE_getEdges (CCGFace * f) [static]
Definition at line 365 of file CCGSubSurf.c.
References FACE_getVerts(), and CCGFace::numVerts.
Referenced by _face_getEdgeIndex(), _face_new(), _face_unlinkMarkAndFree(), ccgSubSurf__calcSubdivLevel(), ccgSubSurf__calcVertNormals(), ccgSubSurf__sync(), ccgSubSurf_getFaceEdge(), ccgSubSurf_getFaceEdgeIndex(), ccgSubSurf_stitchFaces(), ccgSubSurf_syncFace(), ccgSubSurf_updateFromFaces(), ccgSubSurf_updateToFaces(), and FACE_getCenterData().
static CCG_INLINE CCGVert** FACE_getVerts (CCGFace * f) [static]
Definition at line 360 of file CCGSubSurf.c.
Referenced by _face_getIFCoEdge(), _face_getVertIndex(), _face_new(), _face_unlinkMarkAndFree(), ccgSubSurf__calcSubdivLevel(), ccgSubSurf__calcVertNormals(), ccgSubSurf__sync(), ccgSubSurf_getFaceVert(), ccgSubSurf_stitchFaces(), ccgSubSurf_syncFace(), ccgSubSurf_syncVert(), ccgSubSurf_updateFromFaces(), ccgSubSurf_updateToFaces(), and FACE_getEdges().
static CCG_INLINE byte* VERT_getLevelData (CCGVert * v) [static]
Definition at line 323 of file CCGSubSurf.c.
Referenced by _vert_getCo(), _vert_getNo(), and ccgSubSurf_getVertUserData().
static int VERT_seam (const CCGVert * v) [static]
Definition at line 516 of file CCGSubSurf.c.
References CCGVert::flags, and Vert_eSeam.
Referenced by ccgSubSurf__calcSubdivLevel(), and ccgSubSurf__sync().
static int VertDataEqual (const float * a, const float * b) [static]
Definition at line 277 of file CCGSubSurf.c.
Referenced by ccgSubSurf_syncVert().
Variable Documentation
int kHashSizes[] [static]
Initial value:
 {
    1, 3, 5, 11, 17, 37, 67, 131, 257, 521, 1031, 2053, 4099, 8209,
    16411, 32771, 65537, 131101, 262147, 524309, 1048583, 2097169,
    4194319, 8388617, 16777259, 33554467, 67108879, 134217757, 268435459
}
Definition at line 34 of file CCGSubSurf.c.
Referenced by _ehash_insert(), and _ehash_new().