Blender: KX_VisibilityActuator Class Reference
KX_VisibilityActuator Class Reference
#include <KX_VisibilityActuator.h>
Public Member Functions
KX_VisibilityActuator (SCA_IObject *gameobj, bool visible, bool occlusion, bool recursive)
virtual ~KX_VisibilityActuator (void)
virtual CValue * GetReplica (void)
virtual bool Update ()
Detailed Description
Definition at line 38 of file KX_VisibilityActuator.h.
Constructor & Destructor Documentation
KX_VisibilityActuator::KX_VisibilityActuator (SCA_IObject * gameobj, bool visible, bool occlusion, bool recursive)
Definition at line 37 of file KX_VisibilityActuator.cpp.
Referenced by GetReplica().
KX_VisibilityActuator::~KX_VisibilityActuator (void) [virtual]
Definition at line 51 of file KX_VisibilityActuator.cpp.
Member Function Documentation
CValue * KX_VisibilityActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 59 of file KX_VisibilityActuator.cpp.
References KX_VisibilityActuator(), and SCA_IActuator::ProcessReplica().
bool KX_VisibilityActuator::Update (void) [virtual]
Reimplemented from SCA_IActuator.
Definition at line 69 of file KX_VisibilityActuator.cpp.
References SCA_ILogicBrick::GetParent(), SCA_IActuator::IsNegativeEvent(), SCA_IActuator::RemoveAllEvents(), KX_GameObject::SetOccluder(), KX_GameObject::SetVisible(), and KX_GameObject::UpdateBuckets().
The documentation for this class was generated from the following files:
KX_VisibilityActuator.h
KX_VisibilityActuator.cpp