Blender: image_ops.c File Reference
image_ops.c File Reference
image and UV editor
#include <stddef.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "DNA_object_types.h"
#include "DNA_node_types.h"
#include "DNA_packedFile_types.h"
#include "DNA_scene_types.h"
#include "BKE_colortools.h"
#include "BKE_context.h"
#include "BKE_image.h"
#include "BKE_global.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_node.h"
#include "BKE_packedFile.h"
#include "BKE_report.h"
#include "BKE_screen.h"
#include "IMB_imbuf.h"
#include "IMB_imbuf_types.h"
#include "RE_pipeline.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "ED_image.h"
#include "ED_render.h"
#include "ED_screen.h"
#include "ED_space_api.h"
#include "ED_uvedit.h"
#include "ED_util.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "WM_api.h"
#include "WM_types.h"
#include "image_intern.h"
Classes
struct ViewPanData
struct ViewZoomData
struct SaveImageOptions
struct ImageSampleInfo
struct RecordCompositeData
Typedefs
typedef struct ViewPanData ViewPanData
typedef struct ViewZoomData ViewZoomData
typedef struct ImageSampleInfo ImageSampleInfo
typedef struct RecordCompositeData RecordCompositeData
Functions
static void sima_zoom_set (SpaceImage *sima, ARegion *ar, float zoom, float location[2])
static void sima_zoom_set_factor (SpaceImage *sima, ARegion *ar, float zoomfac, float location[2])
static int space_image_buffer_exists_poll (bContext *C)
static int space_image_file_exists_poll (bContext *C)
static int space_image_poll (bContext *C)
int space_image_main_area_poll (bContext *C)
int space_image_main_area_not_uv_brush_poll (bContext *C)
static int space_image_image_sample_poll (bContext *C)
static void image_view_pan_init (bContext *C, wmOperator *op, wmEvent *event)
static void image_view_pan_exit (bContext *C, wmOperator *op, int cancel)
static int image_view_pan_exec (bContext *C, wmOperator *op)
static int image_view_pan_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int image_view_pan_modal (bContext *C, wmOperator *op, wmEvent *event)
static int image_view_pan_cancel (bContext *C, wmOperator *op)
void IMAGE_OT_view_pan (wmOperatorType *ot)
static void image_view_zoom_init (bContext *C, wmOperator *op, wmEvent *event)
static void image_view_zoom_exit (bContext *C, wmOperator *op, int cancel)
static int image_view_zoom_exec (bContext *C, wmOperator *op)
static int image_view_zoom_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int image_view_zoom_modal (bContext *C, wmOperator *op, wmEvent *event)
static int image_view_zoom_cancel (bContext *C, wmOperator *op)
void IMAGE_OT_view_zoom (wmOperatorType *ot)
static int image_view_ndof_invoke (bContext *C, wmOperator *UNUSED(op), wmEvent *event)
void IMAGE_OT_view_ndof (wmOperatorType *ot)
static int image_view_all_exec (bContext *C, wmOperator *UNUSED(op))
void IMAGE_OT_view_all (wmOperatorType *ot)
static int image_view_selected_exec (bContext *C, wmOperator *UNUSED(op))
static int image_view_selected_poll (bContext *C)
void IMAGE_OT_view_selected (wmOperatorType *ot)
static int image_view_zoom_in_exec (bContext *C, wmOperator *op)
static int image_view_zoom_in_invoke (bContext *C, wmOperator *op, wmEvent *event)
void IMAGE_OT_view_zoom_in (wmOperatorType *ot)
static int image_view_zoom_out_exec (bContext *C, wmOperator *op)
static int image_view_zoom_out_invoke (bContext *C, wmOperator *op, wmEvent *event)
void IMAGE_OT_view_zoom_out (wmOperatorType *ot)
static int image_view_zoom_ratio_exec (bContext *C, wmOperator *op)
void IMAGE_OT_view_zoom_ratio (wmOperatorType *ot)
static void image_filesel (bContext *C, wmOperator *op, const char *path)
static void image_open_init (bContext *C, wmOperator *op)
static int image_open_cancel (bContext *UNUSED(C), wmOperator *op)
static int image_open_exec (bContext *C, wmOperator *op)
static int image_open_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void IMAGE_OT_open (wmOperatorType *ot)
static int image_replace_exec (bContext *C, wmOperator *op)
static int image_replace_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void IMAGE_OT_replace (wmOperatorType *ot)
static void save_image_options_defaults (SaveImageOptions *simopts)
static char imtype_best_depth (ImBuf *ibuf, const char imtype)
static int save_image_options_init (SaveImageOptions *simopts, SpaceImage *sima, Scene *scene, const short guess_path)
static void save_image_options_from_op (SaveImageOptions *simopts, wmOperator *op)
static void save_image_options_to_op (SaveImageOptions *simopts, wmOperator *op)
static void save_image_doit (bContext *C, SpaceImage *sima, wmOperator *op, SaveImageOptions *simopts, int do_newpath)
static void image_save_as_free (wmOperator *op)
static int image_save_as_exec (bContext *C, wmOperator *op)
static int image_save_as_check (bContext *UNUSED(C), wmOperator *op)
static int image_save_as_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int image_save_as_cancel (bContext *UNUSED(C), wmOperator *op)
static int image_save_as_draw_check_prop (PointerRNA *ptr, PropertyRNA *prop)
static void image_save_as_draw (bContext *UNUSED(C), wmOperator *op)
void IMAGE_OT_save_as (wmOperatorType *ot)
static int image_save_exec (bContext *C, wmOperator *op)
void IMAGE_OT_save (wmOperatorType *ot)
static int image_save_sequence_exec (bContext *C, wmOperator *op)
void IMAGE_OT_save_sequence (wmOperatorType *ot)
static int image_reload_exec (bContext *C, wmOperator *UNUSED(op))
void IMAGE_OT_reload (wmOperatorType *ot)
static int image_new_exec (bContext *C, wmOperator *op)
static int image_new_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void IMAGE_OT_new (wmOperatorType *ot)
static int image_invert_poll (bContext *C)
static int image_invert_exec (bContext *C, wmOperator *op)
void IMAGE_OT_invert (wmOperatorType *ot)
static int image_pack_test (bContext *C, wmOperator *op)
static int image_pack_exec (bContext *C, wmOperator *op)
static int image_pack_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void IMAGE_OT_pack (wmOperatorType *ot)
static int image_unpack_exec (bContext *C, wmOperator *op)
static int image_unpack_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void IMAGE_OT_unpack (wmOperatorType *ot)
static void image_sample_draw (const bContext *UNUSED(C), ARegion *ar, void *arg_info)
static void image_sample_apply (bContext *C, wmOperator *op, wmEvent *event)
static void image_sample_exit (bContext *C, wmOperator *op)
static int image_sample_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int image_sample_modal (bContext *C, wmOperator *op, wmEvent *event)
static int image_sample_cancel (bContext *C, wmOperator *op)
void IMAGE_OT_sample (wmOperatorType *ot)
static int image_sample_line_exec (bContext *C, wmOperator *op)
static int image_sample_line_invoke (bContext *C, wmOperator *op, wmEvent *event)
void IMAGE_OT_sample_line (wmOperatorType *ot)
void IMAGE_OT_curves_point_set (wmOperatorType *ot)
static int image_record_composite_apply (bContext *C, wmOperator *op)
static int image_record_composite_init (bContext *C, wmOperator *op)
static void image_record_composite_exit (bContext *C, wmOperator *op)
static int image_record_composite_exec (bContext *C, wmOperator *op)
static int image_record_composite_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int image_record_composite_modal (bContext *C, wmOperator *op, wmEvent *event)
static int image_record_composite_cancel (bContext *C, wmOperator *op)
void IMAGE_OT_record_composite (wmOperatorType *ot)
static int image_cycle_render_slot_poll (bContext *C)
static int image_cycle_render_slot_exec (bContext *C, wmOperator *op)
void IMAGE_OT_cycle_render_slot (wmOperatorType *ot)
void ED_image_update_frame (const Main *mainp, int cfra)
Detailed Description
Definition in file image_ops.c.
Typedef Documentation
typedef struct ImageSampleInfo ImageSampleInfo
typedef struct RecordCompositeData RecordCompositeData
typedef struct ViewPanData ViewPanData
typedef struct ViewZoomData ViewZoomData
Function Documentation
void ED_image_update_frame (const Main * mainp, int cfra)
Definition at line 2381 of file image_ops.c.
References bScreen::areabase, View3D::bgpicbase, BKE_image_user_calc_frame(), CMP_NODE_IMAGE, ELEM, ListBase::first, ImageUser::flag, bNode::id, wmWindowManager::id, Tex::id, if(), Tex::ima, IMA_ANIM_ALWAYS, IMA_SRC_MOVIE, IMA_SRC_SEQUENCE, SpaceImage::iuser, BGpic::iuser, Tex::iuser, bNode::next, BGpic::next, ScrArea::next, wmWindow::next, ID::next, bNodeTree::nodes, SpaceNode::nodetree, NTREE_COMPOSIT, wmWindow::screen, Image::source, SPACE_IMAGE, SPACE_NODE, SPACE_VIEW3D, ScrArea::spacedata, ScrArea::spacetype, bNode::storage, Main::tex, TEX_IMAGE, SpaceNode::treetype, bNode::type, Tex::type, wmWindowManager::windows, and Main::wm.
static int image_cycle_render_slot_exec (bContext * C, wmOperator * op) [static]
Definition at line 2331 of file image_ops.c.
References CTX_data_edit_image(), IMA_MAX_RENDER_SLOT, Image::last_render_slot, NC_IMAGE, ND_DRAW, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, Image::render_slot, Image::renders, RNA_boolean_get(), and WM_event_add_notifier().
Referenced by IMAGE_OT_cycle_render_slot().
static int image_cycle_render_slot_poll (bContext * C) [static]
Definition at line 2324 of file image_ops.c.
References CTX_data_edit_image(), IMA_TYPE_R_RESULT, and Image::type.
Referenced by IMAGE_OT_cycle_render_slot().
static void image_filesel (bContext * C, wmOperator * op, const char * path) [static]
Definition at line 788 of file image_ops.c.
References wmOperator::ptr, RNA_string_set(), and WM_event_add_fileselect().
Referenced by image_open_invoke(), image_replace_invoke(), and image_save_as_invoke().
static int image_invert_exec (bContext * C, wmOperator * op) [static]
Definition at line 1590 of file image_ops.c.
References BKE_image_get_ibuf(), CTX_data_edit_image(), g, i, IB_BITMAPDIRTY, IB_MIPMAP_INVALID, IMB_rect_from_float(), ImBuf::mipmap, NA_EDITED, NC_IMAGE, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, ImBuf::rect, ImBuf::rect_float, RNA_boolean_get(), ImBuf::userflags, WM_event_add_notifier(), ImBuf::x, and ImBuf::y.
Referenced by IMAGE_OT_invert().
static int image_invert_poll (bContext * C) [static]
Definition at line 1580 of file image_ops.c.
References BKE_image_get_ibuf(), CTX_data_edit_image(), and NULL.
Referenced by IMAGE_OT_invert().
static int image_new_exec (bContext * C, wmOperator * op) [static]
Definition at line 1486 of file image_ops.c.
References BKE_add_image_size(), BKE_image_signal(), RenderData::color_mgt_flag, CTX_data_edit_object(), CTX_data_scene(), CTX_wm_space_image(), ED_space_image_set(), Image::id, IMA_SIGNAL_USER_NEW_IMAGE, SpaceImage::iuser, linearrgb_to_srgb_v3_v3(), MAX_ID_NAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, Scene::r, R_COLOR_MANAGEMENT, RNA_boolean_get(), RNA_float_get_array(), RNA_id_pointer_create(), RNA_int_get(), RNA_property_pointer_set(), RNA_property_update(), RNA_string_get(), uiIDContextProperty(), and ID::us.
Referenced by IMAGE_OT_new().
static int image_new_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1544 of file image_ops.c.
References WM_operator_props_dialog_popup().
Referenced by IMAGE_OT_new().
static int image_open_cancel (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 804 of file image_ops.c.
References wmOperator::customdata, MEM_freeN(), NULL, and OPERATOR_CANCELLED.
Referenced by IMAGE_OT_open().
static int image_open_exec (bContext * C, wmOperator * op) [static]
Definition at line 811 of file image_ops.c.
References BKE_add_image_file(), BKE_image_signal(), BKE_reportf(), CTX_data_edit_object(), CTX_data_pointer_get_type(), CTX_data_scene(), CTX_wm_space_image(), wmOperator::customdata, PointerRNA::data, ED_preview_kill_jobs(), ED_space_image_set(), ImageUser::fie_ima, FILE_MAX, Image::id, IMA_SIGNAL_RELOAD, image_open_init(), SpaceImage::iuser, Tex::iuser, MEM_freeN(), NA_EDITED, NC_IMAGE, NULL, ImageUser::offset, OPERATOR_CANCELLED, OPERATOR_FINISHED, PropertyPointerRNA::prop, wmOperator::ptr, PropertyPointerRNA::ptr, wmOperator::reports, RNA_id_pointer_create(), RNA_property_pointer_set(), RNA_property_update(), RNA_string_get(), RNA_Texture, RPT_ERROR, ImageUser::sfra, str, TEX_IMAGE, Tex::type, ID::us, and WM_event_add_notifier().
Referenced by image_open_invoke(), and IMAGE_OT_open().
static void image_open_init (bContext * C, wmOperator * op) [static]
Definition at line 796 of file image_ops.c.
References wmOperator::customdata, MEM_callocN(), PropertyPointerRNA::prop, PropertyPointerRNA::ptr, and uiIDContextProperty().
Referenced by image_open_exec(), and image_open_invoke().
static int image_open_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 879 of file image_ops.c.
References CTX_data_pointer_get_type(), CTX_wm_space_image(), PointerRNA::data, Tex::ima, SpaceImage::image, image_filesel(), image_open_exec(), image_open_init(), Image::name, NULL, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_struct_property_is_set(), RNA_Texture, TEX_IMAGE, and Tex::type.
Referenced by IMAGE_OT_open().
void IMAGE_OT_curves_point_set (wmOperatorType * ot)
Definition at line 2148 of file image_ops.c.
References wmOperatorType::cancel, wmOperatorType::flag, wmOperatorType::idname, image_sample_cancel(), image_sample_invoke(), image_sample_modal(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), space_image_main_area_not_uv_brush_poll(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_cycle_render_slot (wmOperatorType * ot)
Definition at line 2359 of file image_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_cycle_render_slot_exec(), image_cycle_render_slot_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_invert (wmOperatorType * ot)
Definition at line 1643 of file image_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_invert_exec(), image_invert_poll(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_new (wmOperatorType * ot)
Definition at line 1550 of file image_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, image_new_exec(), image_new_invoke(), wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::name, NULL, OPTYPE_UNDO, RNA_def_boolean(), RNA_def_float_color(), RNA_def_int(), RNA_def_property_float_array_default(), RNA_def_string(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_open (wmOperatorType * ot)
Definition at line 909 of file image_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, image_open_cancel(), image_open_exec(), image_open_invoke(), IMAGEFILE, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, WM_FILESEL_FILEPATH, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by image_operatortypes().
void IMAGE_OT_pack (wmOperatorType * ot)
Definition at line 1731 of file image_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_pack_exec(), image_pack_invoke(), wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_record_composite (wmOperatorType * ot)
Definition at line 2308 of file image_ops.c.
References wmOperatorType::cancel, wmOperatorType::exec, wmOperatorType::idname, image_record_composite_cancel(), image_record_composite_exec(), image_record_composite_invoke(), image_record_composite_modal(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, wmOperatorType::poll, and space_image_buffer_exists_poll().
Referenced by image_operatortypes().
void IMAGE_OT_reload (wmOperatorType * ot)
Definition at line 1471 of file image_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_reload_exec(), wmOperatorType::name, and OPTYPE_REGISTER.
Referenced by image_operatortypes().
void IMAGE_OT_replace (wmOperatorType * ot)
Definition at line 975 of file image_ops.c.
References wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, image_replace_exec(), image_replace_invoke(), IMAGEFILE, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, space_image_poll(), WM_FILESEL_FILEPATH, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by image_operatortypes().
void IMAGE_OT_sample (wmOperatorType * ot)
Definition at line 2018 of file image_ops.c.
References wmOperatorType::cancel, wmOperatorType::flag, wmOperatorType::idname, image_sample_cancel(), image_sample_invoke(), image_sample_modal(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, and space_image_image_sample_poll().
Referenced by image_operatortypes().
void IMAGE_OT_sample_line (wmOperatorType * ot)
Definition at line 2127 of file image_ops.c.
References wmOperatorType::cancel, CURSOR_EDIT, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_sample_line_exec(), image_sample_line_invoke(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, wmOperatorType::poll, space_image_main_area_poll(), WM_gesture_straightline_cancel(), WM_gesture_straightline_modal(), and WM_operator_properties_gesture_straightline().
Referenced by image_operatortypes().
void IMAGE_OT_save (wmOperatorType * ot)
Definition at line 1359 of file image_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_save_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and space_image_file_exists_poll().
Referenced by image_operatortypes().
void IMAGE_OT_save_as (wmOperatorType * ot)
Definition at line 1311 of file image_ops.c.
References wmOperatorType::cancel, wmOperatorType::check, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_SAVE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, image_save_as_cancel(), image_save_as_check(), image_save_as_draw(), image_save_as_exec(), image_save_as_invoke(), IMAGEFILE, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), space_image_buffer_exists_poll(), wmOperatorType::srna, wmOperatorType::ui, WM_FILESEL_FILEPATH, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by image_operatortypes().
void IMAGE_OT_save_sequence (wmOperatorType * ot)
Definition at line 1436 of file image_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_save_sequence_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and space_image_buffer_exists_poll().
Referenced by image_operatortypes().
void IMAGE_OT_unpack (wmOperatorType * ot)
Definition at line 1808 of file image_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, image_unpack_exec(), image_unpack_invoke(), wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PF_USE_LOCAL, RNA_def_enum(), RNA_def_string(), wmOperatorType::srna, and unpack_method_items.
Referenced by image_operatortypes().
void IMAGE_OT_view_all (wmOperatorType * ot)
Definition at line 589 of file image_ops.c.
References wmOperatorType::exec, wmOperatorType::idname, image_view_all_exec(), wmOperatorType::name, wmOperatorType::poll, and space_image_main_area_poll().
Referenced by image_operatortypes().
void IMAGE_OT_view_ndof (wmOperatorType * ot)
Definition at line 536 of file image_ops.c.
References wmOperatorType::idname, image_view_ndof_invoke(), wmOperatorType::invoke, and wmOperatorType::name.
Referenced by image_operatortypes().
void IMAGE_OT_view_pan (wmOperatorType * ot)
Definition at line 331 of file image_ops.c.
References wmOperatorType::cancel, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, image_view_pan_cancel(), image_view_pan_exec(), image_view_pan_invoke(), image_view_pan_modal(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, wmOperatorType::poll, RNA_def_float_vector(), space_image_main_area_poll(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_view_selected (wmOperatorType * ot)
Definition at line 650 of file image_ops.c.
References wmOperatorType::exec, wmOperatorType::idname, image_view_selected_exec(), image_view_selected_poll(), wmOperatorType::name, and wmOperatorType::poll.
Referenced by image_operatortypes().
void IMAGE_OT_view_zoom (wmOperatorType * ot)
Definition at line 468 of file image_ops.c.
References wmOperatorType::cancel, wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, image_view_zoom_cancel(), image_view_zoom_exec(), image_view_zoom_invoke(), image_view_zoom_modal(), wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, RNA_def_float(), space_image_main_area_poll(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_view_zoom_in (wmOperatorType * ot)
Definition at line 689 of file image_ops.c.
References wmOperatorType::exec, FLT_MAX, wmOperatorType::idname, image_view_zoom_in_exec(), image_view_zoom_in_invoke(), wmOperatorType::invoke, wmOperatorType::name, NULL, wmOperatorType::poll, RNA_def_float_vector(), space_image_main_area_poll(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_view_zoom_out (wmOperatorType * ot)
Definition at line 730 of file image_ops.c.
References wmOperatorType::exec, FLT_MAX, wmOperatorType::idname, image_view_zoom_out_exec(), image_view_zoom_out_invoke(), wmOperatorType::invoke, wmOperatorType::name, NULL, wmOperatorType::poll, RNA_def_float_vector(), space_image_main_area_poll(), and wmOperatorType::srna.
Referenced by image_operatortypes().
void IMAGE_OT_view_zoom_ratio (wmOperatorType * ot)
Definition at line 772 of file image_ops.c.
References wmOperatorType::exec, FLT_MAX, wmOperatorType::idname, image_view_zoom_ratio_exec(), wmOperatorType::name, wmOperatorType::poll, RNA_def_float(), space_image_main_area_poll(), and wmOperatorType::srna.
Referenced by image_operatortypes().
static int image_pack_exec (bContext * C, wmOperator * op) [static]
Definition at line 1683 of file image_ops.c.
References BKE_image_get_ibuf(), BKE_image_memorypack(), BKE_report(), CTX_data_edit_image(), CTX_data_main(), IB_BITMAPDIRTY, Image::id, ID_BLEND_PATH, image_pack_test(), NA_EDITED, Image::name, NC_IMAGE, newPackedFile(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Image::packedfile, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RPT_ERROR, ImBuf::userflags, and WM_event_add_notifier().
Referenced by IMAGE_OT_pack(), and image_pack_invoke().
static int image_pack_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1708 of file image_ops.c.
References BKE_image_get_ibuf(), CTX_data_edit_image(), IB_BITMAPDIRTY, wmOperator::idname, image_pack_exec(), image_pack_test(), NULL, OPERATOR_CANCELLED, wmOperator::ptr, RNA_boolean_get(), uiItemBooleanO(), uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), and ImBuf::userflags.
Referenced by IMAGE_OT_pack().
static int image_pack_test (bContext * C, wmOperator * op) [static]
Definition at line 1665 of file image_ops.c.
References BKE_report(), CTX_data_edit_image(), IMA_SRC_MOVIE, IMA_SRC_SEQUENCE, Image::packedfile, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RPT_ERROR, and Image::source.
Referenced by image_pack_exec(), and image_pack_invoke().
static int image_record_composite_apply (bContext * C, wmOperator * op) [static]
Definition at line 2181 of file image_ops.c.
References BKE_image_all_free_anim_ibufs(), BKE_image_get_ibuf(), RenderData::cfra, CTX_data_scene(), CTX_wm_area(), CTX_wm_space_image(), CTX_wm_window(), wmOperator::customdata, ED_area_tag_redraw(), RecordCompositeData::efra, SpaceImage::image, imb_freerectfloatImBuf(), SpaceImage::iuser, Scene::nodetree, ntreeCompositExecTree(), ntreeCompositTagAnimated(), RecordCompositeData::old_cfra, Scene::r, and WM_timecursor().
Referenced by image_record_composite_exec(), image_record_composite_invoke(), and image_record_composite_modal().
static int image_record_composite_cancel (bContext * C, wmOperator * op) [static]
Definition at line 2302 of file image_ops.c.
References image_record_composite_exit(), and OPERATOR_CANCELLED.
Referenced by IMAGE_OT_record_composite().
static int image_record_composite_exec (bContext * C, wmOperator * op) [static]
Definition at line 2251 of file image_ops.c.
References image_record_composite_apply(), image_record_composite_exit(), image_record_composite_init(), OPERATOR_CANCELLED, and OPERATOR_FINISHED.
Referenced by IMAGE_OT_record_composite().
static void image_record_composite_exit (bContext * C, wmOperator * op) [static]
Definition at line 2230 of file image_ops.c.
References RenderData::cfra, CTX_data_scene(), CTX_wm_manager(), CTX_wm_space_image(), CTX_wm_window(), wmOperator::customdata, SpaceImage::image, MEM_freeN(), NA_EDITED, NC_IMAGE, RecordCompositeData::old_cfra, Scene::r, RecordCompositeData::timer, WM_cursor_restore(), WM_event_add_notifier(), and WM_event_remove_timer().
Referenced by image_record_composite_cancel(), image_record_composite_exec(), and image_record_composite_modal().
static int image_record_composite_init (bContext * C, wmOperator * op) [static]
Definition at line 2209 of file image_ops.c.
References RenderData::cfra, CTX_data_scene(), CTX_wm_space_image(), wmOperator::customdata, RecordCompositeData::efra, ImageUser::frames, SpaceImage::iuser, MEM_callocN(), Scene::nodetree, NULL, RecordCompositeData::old_cfra, Scene::r, ImageUser::sfra, and RecordCompositeData::sfra.
Referenced by image_record_composite_exec(), and image_record_composite_invoke().
static int image_record_composite_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 2264 of file image_ops.c.
References CTX_wm_manager(), CTX_wm_window(), wmOperator::customdata, image_record_composite_apply(), image_record_composite_init(), OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, TIMER, RecordCompositeData::timer, WM_event_add_modal_handler(), and WM_event_add_timer().
Referenced by IMAGE_OT_record_composite().
static int image_record_composite_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2281 of file image_ops.c.
References wmOperator::customdata, wmEvent::customdata, ESCKEY, image_record_composite_apply(), image_record_composite_exit(), OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, TIMER, RecordCompositeData::timer, and wmEvent::type.
Referenced by IMAGE_OT_record_composite().
static int image_reload_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1452 of file image_ops.c.
References BKE_image_signal(), CTX_data_edit_image(), CTX_wm_space_image(), ED_preview_kill_jobs(), IMA_SIGNAL_RELOAD, SpaceImage::iuser, NA_EDITED, NC_IMAGE, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by IMAGE_OT_reload().
static int image_replace_exec (bContext * C, wmOperator * op) [static]
Definition at line 930 of file image_ops.c.
References BKE_image_signal(), BLI_strncpy(), BLI_testextensie_array(), CTX_wm_space_image(), ED_preview_kill_jobs(), FILE_MAX, IMA_SIGNAL_RELOAD, IMA_SRC_FILE, IMA_SRC_MOVIE, SpaceImage::image, imb_ext_movie, SpaceImage::iuser, NA_EDITED, Image::name, NC_IMAGE, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_string_get(), Image::source, str, and WM_event_add_notifier().
Referenced by IMAGE_OT_replace(), and image_replace_invoke().
static int image_replace_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 957 of file image_ops.c.
References CTX_wm_space_image(), SpaceImage::image, image_filesel(), image_replace_exec(), Image::name, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_boolean_set(), and RNA_struct_property_is_set().
Referenced by IMAGE_OT_replace().
static void image_sample_apply (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1857 of file image_ops.c.
References ImBuf::channels, ImageSampleInfo::channels, CLAMP(), ImageSampleInfo::col, ImageSampleInfo::colf, ImageSampleInfo::colfp, ImageSampleInfo::colp, CTX_wm_area(), CTX_wm_region(), CTX_wm_space_image(), SpaceImage::cumap, curvemapping_do_ibuf(), curvemapping_set_black_white(), wmOperator::customdata, ImageSampleInfo::draw, ED_area_tag_redraw(), ED_space_image_acquire_buffer(), ED_space_image_release_buffer(), G, wmEvent::mval, ScrArea::next, NULL, wmOperator::ptr, ImBuf::rect, ImBuf::rect_float, RNA_enum_get(), RNA_struct_find_property(), SPACE_NODE, ScrArea::spacetype, UI_view2d_region_to_view(), ARegion::v2d, ImageSampleInfo::x, ImBuf::x, ImageSampleInfo::y, ImBuf::y, ImageSampleInfo::z, ImBuf::zbuf, ImBuf::zbuf_float, ImageSampleInfo::zf, ImageSampleInfo::zfp, and ImageSampleInfo::zp.
Referenced by image_sample_invoke(), and image_sample_modal().
static int image_sample_cancel (bContext * C, wmOperator * op) [static]
Definition at line 2012 of file image_ops.c.
References image_sample_exit(), and OPERATOR_CANCELLED.
Referenced by IMAGE_OT_curves_point_set(), and IMAGE_OT_sample().
static void image_sample_draw (const bContext * UNUSEDC, ARegion * ar, void * arg_info) [static]
Definition at line 1848 of file image_ops.c.
References ImageSampleInfo::channels, ImageSampleInfo::colfp, ImageSampleInfo::colp, ImageSampleInfo::draw, ED_image_draw_info(), ImageSampleInfo::x, ImageSampleInfo::y, ImageSampleInfo::zfp, and ImageSampleInfo::zp.
Referenced by image_sample_invoke().
static void image_sample_exit (bContext * C, wmOperator * op) [static]
Definition at line 1967 of file image_ops.c.
References ImageSampleInfo::art, CTX_wm_area(), wmOperator::customdata, ImageSampleInfo::draw_handle, ED_area_tag_redraw(), ED_region_draw_cb_exit(), and MEM_freeN().
Referenced by image_sample_cancel(), and image_sample_modal().
static int image_sample_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1976 of file image_ops.c.
References ImageSampleInfo::art, CTX_wm_region(), CTX_wm_space_image(), wmOperator::customdata, ImageSampleInfo::draw_handle, ED_region_draw_cb_activate(), ED_space_image_has_buffer(), image_sample_apply(), image_sample_draw(), MEM_callocN(), OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, REGION_DRAW_POST_PIXEL, ARegion::type, and WM_event_add_modal_handler().
Referenced by IMAGE_OT_curves_point_set(), and IMAGE_OT_sample().
static int image_sample_line_exec (bContext * C, wmOperator * op) [static]
Definition at line 2035 of file image_ops.c.
References ImBuf::channels, Histogram::channels, RenderData::color_mgt_flag, copy_v3_v3(), CTX_data_scene(), CTX_wm_area(), CTX_wm_region(), CTX_wm_space_image(), Histogram::data_b, Histogram::data_g, Histogram::data_luma, Histogram::data_r, ED_area_tag_redraw(), ED_space_image_acquire_buffer(), ED_space_image_release_buffer(), i, linearrgb_to_srgb_v3_v3(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, Scene::r, R_COLOR_MANAGEMENT, ImBuf::rect, ImBuf::rect_float, rgb_to_luma(), rgb_to_luma_byte(), RNA_int_get(), SpaceImage::sample_line_hist, UI_view2d_region_to_view(), ARegion::v2d, ImBuf::x, Histogram::x_resolution, Histogram::xmax, ImBuf::y, and Histogram::ymax.
Referenced by IMAGE_OT_sample_line().
static int image_sample_line_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2117 of file image_ops.c.
References CTX_wm_space_image(), ED_space_image_has_buffer(), OPERATOR_CANCELLED, and WM_gesture_straightline_invoke().
Referenced by IMAGE_OT_sample_line().
static int image_sample_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1997 of file image_ops.c.
References image_sample_apply(), image_sample_exit(), LEFTMOUSE, MOUSEMOVE, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, RIGHTMOUSE, and wmEvent::type.
Referenced by IMAGE_OT_curves_point_set(), and IMAGE_OT_sample().
static int image_save_as_cancel (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 1277 of file image_ops.c.
References image_save_as_free(), and OPERATOR_CANCELLED.
Referenced by IMAGE_OT_save_as().
static int image_save_as_check (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 1242 of file image_ops.c.
References wmOperator::customdata, ImageFormatData::imtype, and WM_operator_filesel_ensure_ext_imtype().
Referenced by IMAGE_OT_save_as().
static void image_save_as_draw (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 1296 of file image_ops.c.
References wmOperator::customdata, image_save_as_draw_check_prop(), wmOperator::layout, NULL, wmOperator::properties, RNA_ImageFormatSettings, RNA_pointer_create(), wmOperatorType::srna, wmOperator::type, uiDefAutoButsRNA(), and uiTemplateImageSettings().
Referenced by IMAGE_OT_save_as().
static int image_save_as_draw_check_prop (PointerRNA * ptr, PropertyRNA * prop) [static]
Definition at line 1284 of file image_ops.c.
References RNA_boolean_get(), and RNA_property_identifier().
Referenced by image_save_as_draw().
static int image_save_as_exec (bContext * C, wmOperator * op) [static]
Definition at line 1222 of file image_ops.c.
References CTX_data_scene(), CTX_wm_space_image(), image_save_as_free(), OPERATOR_FINISHED, save_image_doit(), save_image_options_defaults(), save_image_options_from_op(), save_image_options_init(), and TRUE.
Referenced by IMAGE_OT_save_as(), and image_save_as_invoke().
static void image_save_as_free (wmOperator * op) [static]
Definition at line 1214 of file image_ops.c.
References wmOperator::customdata, MEM_freeN(), and NULL.
Referenced by image_save_as_cancel(), and image_save_as_exec().
static int image_save_as_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1248 of file image_ops.c.
References CTX_data_scene(), CTX_wm_space_image(), wmOperator::customdata, ED_space_image(), ELEM, SaveImageOptions::filepath, SaveImageOptions::im_format, IMA_TYPE_COMPOSITE, IMA_TYPE_R_RESULT, image_filesel(), image_save_as_exec(), MEM_mallocN(), OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_boolean_set(), RNA_struct_property_is_set(), save_image_options_defaults(), save_image_options_init(), save_image_options_to_op(), TRUE, and Image::type.
Referenced by IMAGE_OT_save_as().
static int image_save_exec (bContext * C, wmOperator * op) [static]
Definition at line 1338 of file image_ops.c.
References BKE_reportf(), BLI_exists(), BLI_file_is_writable(), CTX_data_scene(), CTX_wm_space_image(), FALSE, SaveImageOptions::filepath, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, save_image_doit(), save_image_options_from_op(), and save_image_options_init().
Referenced by IMAGE_OT_save().
static int image_save_sequence_exec (bContext * C, wmOperator * op) [static]
Definition at line 1375 of file image_ops.c.
References BKE_report(), BKE_reportf(), BLI_path_abs(), BLI_splitdirstring(), BLI_strncpy(), CTX_data_main(), CTX_wm_space_image(), FILE_MAX, ListBase::first, IB_BITMAPDIRTY, IB_rect, IB_zbuf, IB_zbuffloat, Image::ibufs, IMA_SRC_SEQUENCE, IMA_TYPE_MULTILAYER, SpaceImage::image, IMB_saveiff(), ImBuf::name, Main::name, ImBuf::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, RPT_INFO, RPT_WARNING, Image::source, Image::type, and ImBuf::userflags.
Referenced by IMAGE_OT_save_sequence().
static int image_unpack_exec (bContext * C, wmOperator * op) [static]
Definition at line 1751 of file image_ops.c.
References BKE_report(), BLI_findstring(), CTX_data_edit_image(), CTX_data_main(), ED_preview_kill_jobs(), G, G_AUTOPACK, IMA_SRC_MOVIE, IMA_SRC_SEQUENCE, Main::image, MAX_ID_NAME, NA_EDITED, Main::name, NC_IMAGE, OPERATOR_CANCELLED, OPERATOR_FINISHED, Image::packedfile, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), RNA_string_get(), RNA_struct_property_is_set(), RPT_ERROR, RPT_WARNING, Image::source, unpackImage(), and WM_event_add_notifier().
Referenced by IMAGE_OT_unpack(), and image_unpack_invoke().
static int image_unpack_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1785 of file image_ops.c.
References BKE_report(), CTX_data_edit_image(), G, G_AUTOPACK, Image::id, IMA_SRC_MOVIE, IMA_SRC_SEQUENCE, image_unpack_exec(), ID::name, Image::name, OPERATOR_CANCELLED, OPERATOR_FINISHED, Image::packedfile, wmOperator::ptr, wmOperator::reports, RNA_struct_property_is_set(), RPT_ERROR, RPT_WARNING, Image::source, and unpack_menu().
Referenced by IMAGE_OT_unpack().
static int image_view_all_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 552 of file image_ops.c.
References CTX_wm_region(), CTX_wm_space_image(), ED_region_tag_redraw(), ED_space_image_aspect(), ED_space_image_size(), MIN2, NULL, OPERATOR_FINISHED, power_of_2(), sima_zoom_set(), ARegion::winrct, rcti::xmax, rcti::xmin, SpaceImage::xof, rcti::ymax, rcti::ymin, and SpaceImage::yof.
Referenced by IMAGE_OT_view_all().
static int image_view_ndof_invoke (bContext * C, wmOperator * UNUSEDop, wmEvent * event) [static]
Definition at line 497 of file image_ops.c.
References CTX_wm_region(), CTX_wm_space_image(), wmEvent::customdata, wmNDOFMotionData::dt, ED_region_tag_redraw(), if(), NDOF_MOTION, NDOF_ZOOM_INVERT, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, sima_zoom_set_factor(), wmNDOFMotionData::tvec, wmEvent::type, SpaceImage::xof, SpaceImage::yof, and SpaceImage::zoom.
Referenced by IMAGE_OT_view_ndof().
static int image_view_pan_cancel (bContext * C, wmOperator * op) [static]
Definition at line 325 of file image_ops.c.
References image_view_pan_exit(), and OPERATOR_CANCELLED.
Referenced by IMAGE_OT_view_pan().
static int image_view_pan_exec (bContext * C, wmOperator * op) [static]
Definition at line 257 of file image_ops.c.
References CTX_wm_region(), CTX_wm_space_image(), ED_region_tag_redraw(), NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get_array(), SpaceImage::xof, and SpaceImage::yof.
Referenced by IMAGE_OT_view_pan(), image_view_pan_invoke(), and image_view_pan_modal().
static void image_view_pan_exit (bContext * C, wmOperator * op, int cancel) [static]
Definition at line 242 of file image_ops.c.
References CTX_wm_region(), CTX_wm_space_image(), CTX_wm_window(), wmOperator::customdata, ED_region_tag_redraw(), MEM_freeN(), WM_cursor_restore(), SpaceImage::xof, ViewPanData::xof, SpaceImage::yof, and ViewPanData::yof.
Referenced by image_view_pan_cancel(), and image_view_pan_modal().
static void image_view_pan_init (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 225 of file image_ops.c.
References BC_NSEW_SCROLLCURSOR, CTX_wm_space_image(), CTX_wm_window(), wmOperator::customdata, ViewPanData::event_type, MEM_callocN(), WM_cursor_modal(), WM_event_add_modal_handler(), ViewPanData::x, SpaceImage::xof, ViewPanData::xof, ViewPanData::y, SpaceImage::yof, and ViewPanData::yof.
Referenced by image_view_pan_invoke().
static int image_view_pan_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 280 of file image_ops.c.
References CTX_wm_space_image(), image_view_pan_exec(), image_view_pan_init(), MOUSEPAN, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmEvent::prevy, wmOperator::ptr, RNA_float_set_array(), wmEvent::type, wmEvent::y, and SpaceImage::zoom.
Referenced by IMAGE_OT_view_pan().
static int image_view_pan_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 299 of file image_ops.c.
References CTX_wm_space_image(), wmOperator::customdata, ViewPanData::event_type, image_view_pan_exec(), image_view_pan_exit(), KM_RELEASE, MOUSEMOVE, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_float_set_array(), wmEvent::type, wmEvent::val, ViewPanData::x, SpaceImage::xof, ViewPanData::xof, ViewPanData::y, wmEvent::y, SpaceImage::yof, ViewPanData::yof, and SpaceImage::zoom.
Referenced by IMAGE_OT_view_pan().
static int image_view_selected_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 602 of file image_ops.c.
References CTX_data_edit_object(), CTX_data_scene(), CTX_wm_region(), CTX_wm_space_image(), ED_image_aspect(), ED_region_tag_redraw(), ED_space_image(), ED_space_image_size(), ED_uvedit_minmax(), max, MAX2, min, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, sima_zoom_set(), size(), SpaceImage::xof, and SpaceImage::yof.
Referenced by IMAGE_OT_view_selected().
static int image_view_selected_poll (bContext * C) [static]
Definition at line 645 of file image_ops.c.
References ED_operator_uvedit(), and space_image_main_area_poll().
Referenced by IMAGE_OT_view_selected().
static int image_view_zoom_cancel (bContext * C, wmOperator * op) [static]
Definition at line 462 of file image_ops.c.
References image_view_zoom_exit(), and OPERATOR_CANCELLED.
Referenced by IMAGE_OT_view_zoom().
static int image_view_zoom_exec (bContext * C, wmOperator * op) [static]
Definition at line 394 of file image_ops.c.
References CTX_wm_region(), CTX_wm_space_image(), ED_region_tag_redraw(), NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get(), and sima_zoom_set_factor().
Referenced by IMAGE_OT_view_zoom().
static void image_view_zoom_exit (bContext * C, wmOperator * op, int cancel) [static]
Definition at line 380 of file image_ops.c.
References CTX_wm_region(), CTX_wm_space_image(), CTX_wm_window(), wmOperator::customdata, ED_region_tag_redraw(), MEM_freeN(), WM_cursor_restore(), ViewZoomData::zoom, and SpaceImage::zoom.
Referenced by image_view_zoom_cancel(), and image_view_zoom_modal().
static int image_view_zoom_in_exec (bContext * C, wmOperator * op) [static]
Definition at line 663 of file image_ops.c.
References CTX_wm_region(), CTX_wm_space_image(), ED_region_tag_redraw(), OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get_array(), and sima_zoom_set_factor().
Referenced by IMAGE_OT_view_zoom_in(), and image_view_zoom_in_invoke().
static int image_view_zoom_in_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 678 of file image_ops.c.
References CTX_wm_region(), image_view_zoom_in_exec(), wmEvent::mval, wmOperator::ptr, RNA_float_set_array(), UI_view2d_region_to_view(), and ARegion::v2d.
Referenced by IMAGE_OT_view_zoom_in().
static void image_view_zoom_init (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 361 of file image_ops.c.
References BC_NSEW_SCROLLCURSOR, CTX_wm_region(), CTX_wm_space_image(), CTX_wm_window(), wmOperator::customdata, ViewZoomData::event_type, ViewZoomData::location, MEM_callocN(), wmEvent::mval, UI_view2d_region_to_view(), ARegion::v2d, WM_cursor_modal(), WM_event_add_modal_handler(), ViewZoomData::x, ViewZoomData::y, ViewZoomData::zoom, and SpaceImage::zoom.
Referenced by image_view_zoom_invoke().
static int image_view_zoom_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 415 of file image_ops.c.
References CTX_wm_region(), CTX_wm_space_image(), ED_region_tag_redraw(), image_view_zoom_init(), MOUSEZOOM, wmEvent::mval, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_float_set(), sima_zoom_set(), wmEvent::type, UI_view2d_region_to_view(), ARegion::v2d, and SpaceImage::zoom.
Referenced by IMAGE_OT_view_zoom().
static int image_view_zoom_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 437 of file image_ops.c.
References CTX_wm_region(), CTX_wm_space_image(), wmOperator::customdata, ED_region_tag_redraw(), ViewZoomData::event_type, image_view_zoom_exit(), KM_RELEASE, ViewZoomData::location, MOUSEMOVE, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_float_set(), sima_zoom_set(), wmEvent::type, wmEvent::val, ViewZoomData::x, ViewZoomData::y, and ViewZoomData::zoom.
Referenced by IMAGE_OT_view_zoom().
static int image_view_zoom_out_exec (bContext * C, wmOperator * op) [static]
Definition at line 704 of file image_ops.c.
References CTX_wm_region(), CTX_wm_space_image(), ED_region_tag_redraw(), OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get_array(), and sima_zoom_set_factor().
Referenced by IMAGE_OT_view_zoom_out(), and image_view_zoom_out_invoke().
static int image_view_zoom_out_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 719 of file image_ops.c.
References CTX_wm_region(), image_view_zoom_out_exec(), wmEvent::mval, wmOperator::ptr, RNA_float_set_array(), UI_view2d_region_to_view(), and ARegion::v2d.
Referenced by IMAGE_OT_view_zoom_out().
static int image_view_zoom_ratio_exec (bContext * C, wmOperator * op) [static]
Definition at line 747 of file image_ops.c.
References CTX_wm_region(), CTX_wm_space_image(), ED_region_tag_redraw(), NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get(), sima_zoom_set(), SpaceImage::xof, and SpaceImage::yof.
Referenced by IMAGE_OT_view_zoom_ratio().
static char imtype_best_depth (ImBuf * ibuf, const char imtype) [static]
Definition at line 1008 of file image_ops.c.
References BKE_imtype_valid_depths(), R_IMF_CHAN_DEPTH_12, R_IMF_CHAN_DEPTH_16, R_IMF_CHAN_DEPTH_24, R_IMF_CHAN_DEPTH_32, R_IMF_CHAN_DEPTH_8, and ImBuf::rect_float.
Referenced by save_image_options_init().
static void save_image_doit (bContext * C, SpaceImage * sima, wmOperator * op, SaveImageOptions * simopts, int do_newpath) [static]
Definition at line 1113 of file image_ops.c.
References BKE_alphatest_ibuf(), BKE_image_acquire_renderresult(), BKE_image_release_renderresult(), BKE_report(), BKE_reportf(), BKE_write_ibuf_as(), BLI_path_rel(), BLI_strncpy(), CTX_data_main(), CTX_data_scene(), ED_space_image(), ED_space_image_acquire_buffer(), ED_space_image_release_buffer(), ELEM, FALSE, SaveImageOptions::filepath, G, IB_BITMAPDIRTY, IB_rect, IB_rectfloat, IB_zbuf, IB_zbuffloat, Image::id, ID_BLEND_PATH, SaveImageOptions::im_format, IMA_SRC_FILE, IMA_SRC_GENERATED, IMA_SRC_VIEWER, IMA_TYPE_IMAGE, IMA_TYPE_R_RESULT, SpaceImage::image, imb_freerectfloatImBuf(), imb_freerectImBuf(), IMB_freezbuffloatImBuf(), IMB_freezbufImBuf(), ImageFormatData::imtype, ImBuf::mall, NA_EDITED, ImBuf::name, Image::name, NC_IMAGE, ImageFormatData::planes, ImBuf::planes, wmOperator::ptr, ImageFormatData::quality, R_IMF_IMTYPE_MULTILAYER, R_IMF_PLANES_RGB, R_IMF_PLANES_RGBA, RE_WriteRenderResult(), ImBuf::rect, ImBuf::rect_float, wmOperator::reports, RNA_boolean_get(), RNA_struct_find_property(), RPT_ERROR, Image::source, TRUE, Image::type, ImBuf::userflags, WM_cursor_wait(), WM_event_add_notifier(), ImBuf::zbuf, and ImBuf::zbuf_float.
Referenced by image_save_as_exec(), and image_save_exec().
static void save_image_options_defaults (SaveImageOptions * simopts) [static]
Definition at line 1002 of file image_ops.c.
References BKE_imformat_defaults(), SaveImageOptions::filepath, and SaveImageOptions::im_format.
Referenced by image_save_as_exec(), and image_save_as_invoke().
static void save_image_options_from_op (SaveImageOptions * simopts, wmOperator * op) [static]
Definition at line 1090 of file image_ops.c.
References BLI_path_abs(), wmOperator::customdata, SaveImageOptions::filepath, G, SaveImageOptions::im_format, wmOperator::ptr, RNA_string_get(), and RNA_struct_property_is_set().
Referenced by image_save_as_exec(), and image_save_exec().
static int save_image_options_init (SaveImageOptions * simopts, SpaceImage * sima, Scene * scene, const short guess_path) [static]
Definition at line 1029 of file image_ops.c.
References BKE_ftype_to_imtype(), BLI_path_abs(), BLI_strncpy(), ImageFormatData::depth, ED_space_image_acquire_buffer(), ED_space_image_release_buffer(), ELEM, ELEM3, FALSE, FILE_MAX, SaveImageOptions::filepath, ImBuf::ftype, G, SaveImageOptions::im_format, RenderData::im_format, IMA_SRC_GENERATED, IMA_TYPE_COMPOSITE, IMA_TYPE_R_RESULT, SpaceImage::image, ImageFormatData::imtype, imtype_best_depth(), ImBuf::name, NULL, ImageFormatData::planes, ImBuf::planes, ImageFormatData::quality, Scene::r, R_IMF_IMTYPE_PNG, R_IMF_PLANES_BW, R_IMF_PLANES_RGB, R_IMF_PLANES_RGBA, Image::source, TRUE, and Image::type.
Referenced by image_save_as_exec(), image_save_as_invoke(), and image_save_exec().
static void save_image_options_to_op (SaveImageOptions * simopts, wmOperator * op) [static]
Definition at line 1102 of file image_ops.c.
References wmOperator::customdata, SaveImageOptions::filepath, SaveImageOptions::im_format, wmOperator::ptr, and RNA_string_set().
Referenced by image_save_as_invoke().
static void sima_zoom_set (SpaceImage * sima, ARegion * ar, float zoom, float location[2]) [static]
Definition at line 85 of file image_ops.c.
References ED_space_image_aspect(), ED_space_image_size(), USER_ZOOM_TO_MOUSEPOS, ARegion::winrct, rcti::xmax, rcti::xmin, SpaceImage::xof, rcti::ymax, rcti::ymin, SpaceImage::yof, and SpaceImage::zoom.
Referenced by image_view_all_exec(), image_view_selected_exec(), image_view_zoom_invoke(), image_view_zoom_modal(), image_view_zoom_ratio_exec(), and sima_zoom_set_factor().
static void sima_zoom_set_factor (SpaceImage * sima, ARegion * ar, float zoomfac, float location[2]) [static]
Definition at line 121 of file image_ops.c.
References sima_zoom_set(), and SpaceImage::zoom.
Referenced by image_view_ndof_invoke(), image_view_zoom_exec(), image_view_zoom_in_exec(), and image_view_zoom_out_exec().
static int space_image_buffer_exists_poll (bContext * C) [static]
Definition at line 133 of file image_ops.c.
References CTX_wm_space_image(), ED_space_image_has_buffer(), SPACE_IMAGE, and SpaceImage::spacetype.
Referenced by IMAGE_OT_record_composite(), IMAGE_OT_save_as(), IMAGE_OT_save_sequence(), and space_image_file_exists_poll().
static int space_image_file_exists_poll (bContext * C) [static]
Definition at line 142 of file image_ops.c.
References BLI_exists(), BLI_file_is_writable(), BLI_path_abs(), BLI_strncpy(), CTX_data_main(), CTX_wm_operator_poll_msg_set(), CTX_wm_space_image(), ED_space_image_acquire_buffer(), ED_space_image_release_buffer(), FALSE, FILE_MAX, ImBuf::name, Main::name, space_image_buffer_exists_poll(), and TRUE.
Referenced by IMAGE_OT_save().
static int space_image_image_sample_poll (bContext * C) [static]
Definition at line 205 of file image_ops.c.
References CTX_data_edit_object(), CTX_data_scene(), CTX_wm_space_image(), ED_space_image_show_uvedit(), space_image_main_area_poll(), Scene::toolsettings, and ToolSettings::use_uv_sculpt.
Referenced by IMAGE_OT_sample().
int space_image_main_area_not_uv_brush_poll (bContext * C)
Definition at line 194 of file image_ops.c.
References CTX_data_scene(), CTX_wm_space_image(), Scene::toolsettings, and ToolSettings::uvsculpt.
Referenced by IMAGE_OT_curves_point_set().
int space_image_main_area_poll (bContext * C)
Definition at line 182 of file image_ops.c.
References CTX_wm_space_image().
Referenced by IMAGE_OT_sample_line(), IMAGE_OT_view_all(), IMAGE_OT_view_pan(), IMAGE_OT_view_zoom(), IMAGE_OT_view_zoom_in(), IMAGE_OT_view_zoom_out(), IMAGE_OT_view_zoom_ratio(), image_view_selected_poll(), and space_image_image_sample_poll().
static int space_image_poll (bContext * C) [static]
Definition at line 174 of file image_ops.c.
References CTX_wm_space_image(), SpaceImage::image, SPACE_IMAGE, and SpaceImage::spacetype.
Referenced by IMAGE_OT_replace().