Blender: logImageCore.h File Reference
logImageCore.h File Reference
Cineon
#include <stdio.h>
#include "logImageLib.h"
#include "BLO_sys_types.h"
Classes
struct _Log_Image_File_t_
Typedefs
typedef int(GetRowFn)(LogImageFile *logImage, unsigned short *row, int lineNum)
typedef int(SetRowFn)(LogImageFile *logImage, const unsigned short *row, int lineNum)
typedef void(CloseFn)(LogImageFile *logImage)
typedef unsigned int U32
typedef unsigned short U16
typedef unsigned char U8
typedef signed int S32
typedef float R32
typedef char ASCII
Functions
void setupLut (LogImageFile *)
void setupLut16 (LogImageFile *)
int pixelsToLongs (int numPixels)
R32 htonf (R32 f)
R32 ntohf (R32 f)
R32 undefined (void)
U16 reverseU16 (U16 value)
U32 reverseU32 (U32 value)
R32 reverseR32 (R32 value)
Detailed Description
Definition in file logImageCore.h.
Typedef Documentation
typedef char ASCII
Definition at line 109 of file logImageCore.h.
typedef void(CloseFn)(LogImageFile *logImage)
Definition at line 49 of file logImageCore.h.
typedef int(GetRowFn)(LogImageFile *logImage, unsigned short *row, int lineNum)
Definition at line 47 of file logImageCore.h.
typedef float R32
Definition at line 108 of file logImageCore.h.
typedef signed int S32
Definition at line 107 of file logImageCore.h.
typedef int(SetRowFn)(LogImageFile *logImage, const unsigned short *row, int lineNum)
Definition at line 48 of file logImageCore.h.
typedef unsigned short U16
Definition at line 105 of file logImageCore.h.
typedef unsigned int U32
Definition at line 104 of file logImageCore.h.
typedef unsigned char U8
Definition at line 106 of file logImageCore.h.
Function Documentation
R32 htonf (R32 f)
Definition at line 142 of file logImageCore.c.
References Hack::f, and Hack::i.
Referenced by fillCineonChannelInfo(), fillCineonImageInfo(), fillCineonOriginationInfo(), and fillDpxChannelInfo().
R32 ntohf (R32 f)
Definition at line 150 of file logImageCore.c.
References Hack::f, and Hack::i.
Referenced by dumpCineonChannelInfo(), dumpCineonImageInfo(), dumpCineonOriginationInfo(), dumpDpxChannelInfo(), and dumpDpxOriginationInfo().
int pixelsToLongs (int numPixels)
Definition at line 130 of file logImageCore.c.
Referenced by cineonCreate(), cineonOpen(), cineonOpenFromMem(), dpxCreate(), dpxGetRowBytes(), dpxSetRowBytes(), fillDpxFileInfo(), intern_dpxOpen(), and verboseMe().
R32 reverseR32 (R32 value)
Definition at line 203 of file logImageCore.c.
U16 reverseU16 (U16 value)
Definition at line 168 of file logImageCore.c.
U32 reverseU32 (U32 value)
Definition at line 184 of file logImageCore.c.
void setupLut (LogImageFile *)
Definition at line 72 of file logImageCore.c.
References LogImageByteConversionParameters::blackPoint, convertFrom(), convertTo(), LogImageByteConversionParameters::gamma, i, _Log_Image_File_t_::lut10, _Log_Image_File_t_::lut8, _Log_Image_File_t_::params, rint, and LogImageByteConversionParameters::whitePoint.
Referenced by cineonCreate(), cineonOpen(), cineonOpenFromMem(), dpxCreate(), and intern_dpxOpen().
void setupLut16 (LogImageFile *)
Definition at line 101 of file logImageCore.c.
References LogImageByteConversionParameters::blackPoint, convertFrom(), convertTo(), LogImageByteConversionParameters::gamma, i, _Log_Image_File_t_::lut10_16, _Log_Image_File_t_::lut16_16, _Log_Image_File_t_::params, rint, and LogImageByteConversionParameters::whitePoint.
Referenced by logImageSetByteConversion().
R32 undefined (void)
Definition at line 160 of file logImageCore.c.
References Hack::f, Hack::i, and UNDEF_FLOAT.
Referenced by fillCineonImageInfo(), and fillCineonOriginationInfo().