Blender: BKE_paint.h File Reference
BKE_paint.h File Reference
blenkernel
Classes
struct SculptSession
Typedefs
typedef struct SculptSession SculptSession
Functions
void paint_init (struct Paint *p, const char col[3])
void free_paint (struct Paint *p)
void copy_paint (struct Paint *src, struct Paint *tar)
struct Paint * paint_get_active (struct Scene *sce)
struct Brush * paint_brush (struct Paint *paint)
void paint_brush_set (struct Paint *paint, struct Brush *br)
int paint_facesel_test (struct Object *ob)
int paint_vertsel_test (struct Object *ob)
int paint_is_face_hidden (const struct MFace *f, const struct MVert *mvert)
int paint_is_grid_face_hidden (const unsigned int *grid_hidden, int gridsize, int x, int y)
void free_sculptsession (struct Object *ob)
void free_sculptsession_deformMats (struct SculptSession *ss)
Variables
const char PAINT_CURSOR_SCULPT [3]
const char PAINT_CURSOR_VERTEX_PAINT [3]
const char PAINT_CURSOR_WEIGHT_PAINT [3]
const char PAINT_CURSOR_TEXTURE_PAINT [3]
Detailed Description
Definition in file BKE_paint.h.
Typedef Documentation
typedef struct SculptSession SculptSession
Function Documentation
void copy_paint (struct Paint * src, struct Paint * tar)
Definition at line 147 of file paint.c.
References Paint::brush, and id_us_plus().
Referenced by copy_scene().
void free_paint (struct Paint * p)
Definition at line 138 of file paint.c.
References Paint::brush, and id_us_min().
Referenced by free_scene().
void free_sculptsession (struct Object * ob)
Definition at line 278 of file object.c.
References BLI_pbvh_free(), SculptSession::deform_cos, SculptSession::deform_imats, Object::derivedFinal, DerivedMesh::getPBVH, SculptSession::layer_co, MEM_freeN(), NULL, SculptSession::orig_cos, SculptSession::pbvh, Object::sculpt, and SculptSession::texcache.
Referenced by free_object(), and sculpt_toggle_mode().
void free_sculptsession_deformMats (struct SculptSession * ss)
Definition at line 267 of file object.c.
Referenced by object_sculpt_modifiers_changed(), sculpt_undo_restore(), and sculpt_update_mesh_elements().
struct Brush* paint_brush (struct Paint * paint) [read]
Definition at line 86 of file paint.c.
References Paint::brush, and NULL.
Referenced by brush_add_exec(), brush_curve_preset_exec(), brush_curve_preset_poll(), brush_drawcursor(), brush_generic_tool_set(), brush_reset_exec(), brush_scale_size_exec(), brush_strength(), buttons_context_path_brush(), buttons_texture_users_from_context(), calc_sculpt_normal(), calc_sculpt_plane(), calc_vp_strength_dl(), do_clay_brush(), do_clay_strips_brush(), do_crease_brush(), do_draw_brush(), do_fill_brush(), do_flatten_brush(), do_grab_brush(), do_inflate_brush(), do_layer_brush(), do_mesh_smooth_brush(), do_multires_smooth_brush(), do_nudge_brush(), do_pinch_brush(), do_rotate_brush(), do_scrape_brush(), do_snake_hook_brush(), do_symmetrical_brush_actions(), do_thumb_brush(), draw_image_paint_helpers(), get_alpha_clone_image(), get_offset(), HC_relaxation_iteration_uv(), image_paint_brush(), laplacian_relaxation_iteration_uv(), make_local_brush(), paint_brush_stroke_add_step(), paint_draw_cursor(), paint_draw_smooth_stroke(), paint_init(), paint_poll(), paint_sample_color(), paint_stroke_new(), project_state_init(), sculpt_brush_exit_tex(), sculpt_brush_init_tex(), sculpt_brush_stroke_init(), sculpt_combine_proxies(), sculpt_fix_noise_tear(), sculpt_flush_stroke_deform(), sculpt_get_brush_geometry(), sculpt_restore_mesh(), sculpt_stroke_done(), sculpt_stroke_modifiers_check(), sculpt_tool_name(), sculpt_update_cache_invariants(), sculpt_update_cache_variants(), sculpt_update_tex(), snode_set_context(), texture_paint_init(), uv_sculpt_brush(), uv_sculpt_stroke_apply(), uv_sculpt_stroke_init(), vertex_paint_poll(), vpaint_blend(), vpaint_get_current_col(), vpaint_paint_poly(), vpaint_stroke_update_step(), weight_paint_poll(), wpaint_blend(), and wpaint_stroke_update_step().
void paint_brush_set (struct Paint * paint, struct Brush * br)
Definition at line 91 of file paint.c.
References Paint::brush, id_us_min(), and id_us_plus().
Referenced by brush_add_exec(), brush_generic_tool_set(), make_local_brush(), paint_init(), sculpt_stroke_done(), and sculpt_update_cache_invariants().
int paint_facesel_test (struct Object * ob)
Definition at line 101 of file paint.c.
References Object::data, ME_EDIT_PAINT_MASK, Object::mode, NULL, OB_MESH, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, and Object::type.
Referenced by backdrawview3d(), draw_mesh_fancy(), draw_mesh_text(), ED_view3d_object_datamask(), EDBM_backbuf_border_mask_init(), EDBM_backbuf_circle_init(), facemask_paint_poll(), mask_paint_poll(), mesh_build_data(), view3d_borderselect_exec(), view3d_circle_select_exec(), view3d_lasso_select(), view3d_select_invoke(), view3d_selectable_data(), and viewselected_exec().
struct Paint* paint_get_active (struct Scene * sce) [read]
Definition at line 56 of file paint.c.
References Scene::basact, ToolSettings::imapaint, Object::mode, NULL, OB_MODE_EDIT, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, Base::object, UvSculpt::paint, ImagePaintSettings::paint, VPaint::paint, Sculpt::paint, ToolSettings::sculpt, Scene::toolsettings, ToolSettings::use_uv_sculpt, ToolSettings::uvsculpt, ToolSettings::vpaint, and ToolSettings::wpaint.
Referenced by brush_add_exec(), brush_curve_preset_exec(), brush_curve_preset_poll(), brush_drawcursor(), brush_reset_exec(), brush_scale_size_exec(), buttons_context_path_brush(), buttons_texture_users_from_context(), draw_mesh_fancy(), paint_brush_stroke_add_step(), paint_cursor_start(), paint_draw_cursor(), paint_draw_smooth_stroke(), paint_poll(), paint_sample_color(), paint_stroke_new(), sculpt_get_brush_geometry(), and viewops_data_free().
void paint_init (struct Paint * p, const char col[3])
Definition at line 122 of file paint.c.
References add_brush(), Paint::flags, NULL, paint_brush(), paint_brush_set(), Paint::paint_cursor_col, and PAINT_SHOW_BRUSH.
Referenced by ED_space_image_uv_sculpt_update(), sculpt_toggle_mode(), set_vpaint(), set_wpaint(), and texture_paint_toggle_exec().
int paint_is_face_hidden (const struct MFace * f, const struct MVert * mvert)
Referenced by BLI_pbvh_node_raycast(), GPU_build_mesh_buffers(), and gpu_draw_buffers_legacy_mesh().
int paint_is_grid_face_hidden (const unsigned int * grid_hidden, int gridsize, int x, int y)
Definition at line 166 of file paint.c.
References BLI_BITMAP_GET.
Referenced by BLI_pbvh_node_raycast(), gpu_count_grid_quads(), and gpu_draw_buffers_legacy_grids().
int paint_vertsel_test (struct Object * ob)
Definition at line 112 of file paint.c.
References Object::data, ME_EDIT_VERT_SEL, Object::mode, NULL, OB_MESH, OB_MODE_WEIGHT_PAINT, and Object::type.
Referenced by draw_mesh_fancy(), draw_mesh_text(), EDBM_backbuf_border_mask_init(), EDBM_backbuf_circle_init(), mask_paint_poll(), vert_paint_poll(), view3d_borderselect_exec(), view3d_circle_select_exec(), view3d_lasso_select(), view3d_select_invoke(), and view3d_selectable_data().
Variable Documentation
const char PAINT_CURSOR_SCULPT[3]
Definition at line 51 of file paint.c.
Referenced by ED_space_image_uv_sculpt_update(), and sculpt_toggle_mode().
const char PAINT_CURSOR_TEXTURE_PAINT[3]
Definition at line 54 of file paint.c.
Referenced by texture_paint_toggle_exec().
const char PAINT_CURSOR_VERTEX_PAINT[3]
Definition at line 52 of file paint.c.
Referenced by set_vpaint().
const char PAINT_CURSOR_WEIGHT_PAINT[3]
Definition at line 53 of file paint.c.
Referenced by set_wpaint().