Blender: iTaSC::CopyPose Class Reference
iTaSC::CopyPose Class Reference
#include <CopyPose.hpp>
Classes
struct ControlState
Public Types
enum ID {
ID_POSITION = 0, ID_POSITIONX = 1, ID_POSITIONY = 2, ID_POSITIONZ = 3,
ID_ROTATION = 4, ID_ROTATIONX = 5, ID_ROTATIONY = 6, ID_ROTATIONZ = 7
}
enum CTL {
CTL_NONE = 0x00, CTL_POSITIONX = 0x01, CTL_POSITIONY = 0x02, CTL_POSITIONZ = 0x04,
CTL_POSITION = 0x07, CTL_ROTATIONX = 0x08, CTL_ROTATIONY = 0x10, CTL_ROTATIONZ = 0x20,
CTL_ROTATION = 0x38, CTL_ALL = 0x3F
}
Public Member Functions
CopyPose (unsigned int control_output=CTL_ALL, unsigned int dynamic_output=CTL_NONE, double armlength=1.0, double accuracy=1e-6, unsigned int maximum_iterations=100)
virtual ~CopyPose ()
virtual bool setControlParameters (struct ConstraintValues *_values, unsigned int _nvalues, double timestep)
virtual const ConstraintValues * getControlParameters (unsigned int *_nvalues)
Protected Member Functions
virtual void updateKinematics (const Timestamp &timestamp)
virtual void pushCache (const Timestamp &timestamp)
virtual void updateJacobian ()
virtual bool initialise (Frame &init_pose)
virtual void initCache (Cache *_cache)
virtual void updateControlOutput (const Timestamp &timestamp)
virtual void modelUpdate (Frame &_external_pose, const Timestamp &timestamp)
virtual double getMaxTimestep (double &timestep)
Detailed Description
Definition at line 16 of file CopyPose.hpp.
Member Enumeration Documentation
enum iTaSC::CopyPose::CTL
Enumerator:
CTL_NONE
CTL_POSITIONX
CTL_POSITIONY
CTL_POSITIONZ
CTL_POSITION
CTL_ROTATIONX
CTL_ROTATIONY
CTL_ROTATIONZ
CTL_ROTATION
CTL_ALL
Definition at line 39 of file CopyPose.hpp.
enum iTaSC::CopyPose::ID
Enumerator:
ID_POSITION
ID_POSITIONX
ID_POSITIONY
ID_POSITIONZ
ID_ROTATION
ID_ROTATIONX
ID_ROTATIONY
ID_ROTATIONZ
Definition at line 29 of file CopyPose.hpp.
Constructor & Destructor Documentation
iTaSC::CopyPose::CopyPose (unsigned int control_output = CTL_ALL, unsigned int dynamic_output = CTL_NONE, double armlength = 1.0, double accuracy = 1e-6, unsigned int maximum_iterations = 100)
Definition at line 20 of file CopyPose.cpp.
References iTaSC::ConstraintValues::alpha, assert, CTL_ALL, CTL_POSITION, CTL_POSITIONX, CTL_POSITIONY, CTL_POSITIONZ, CTL_ROTATION, CTL_ROTATIONX, CTL_ROTATIONY, CTL_ROTATIONZ, e_identity_matrix, iTaSC::ConstraintValues::feedback, iTaSC::ConstraintValues::id, iTaSC::ConstraintSingleValue::id, ID_POSITION, ID_POSITIONX, ID_POSITIONY, ID_POSITIONZ, ID_ROTATION, ID_ROTATIONX, ID_ROTATIONY, ID_ROTATIONZ, iTaSC::ConstraintSet::m_Cf, iTaSC::ConstraintSet::m_Jf, iTaSC::ConstraintSet::m_nc, iTaSC::ConstraintSet::m_Wy, iTaSC::ConstraintValues::number, iTaSC::ConstraintSet::reset(), iTaSC::ConstraintValues::tolerance, and iTaSC::ConstraintValues::values.
iTaSC::CopyPose::~CopyPose () [virtual]
Definition at line 115 of file CopyPose.cpp.
Member Function Documentation
const ConstraintValues * iTaSC::CopyPose::getControlParameters (unsigned int * _nvalues) [virtual]
Implements iTaSC::ConstraintSet.
Definition at line 456 of file CopyPose.cpp.
References CTL_POSITIONX, CTL_ROTATION, CTL_ROTATIONX, KDL::diff(), iTaSC::F_identity, iTaSC::ConstraintSet::m_internalPose, KDL::Twist::rot, and KDL::Twist::vel.
double iTaSC::CopyPose::getMaxTimestep (double & timestep) [protected, virtual]
Reimplemented from iTaSC::ConstraintSet.
Definition at line 471 of file CopyPose.cpp.
References e_scalar, iTaSC::ConstraintSet::m_chidot, and iTaSC::ConstraintSet::m_maxDeltaChi.
void iTaSC::CopyPose::initCache (Cache * _cache) [protected, virtual]
Implements iTaSC::ConstraintSet.
Definition at line 132 of file CopyPose.cpp.
References iTaSC::Cache::addChannel().
bool iTaSC::CopyPose::initialise (Frame & init_pose) [protected, virtual]
Reimplemented from iTaSC::ConstraintSet.
Definition at line 119 of file CopyPose.cpp.
References iTaSC::ConstraintSet::m_externalPose, iTaSC::ConstraintSet::m_internalPose, and updateJacobian().
void iTaSC::CopyPose::modelUpdate (Frame & _external_pose, const Timestamp & timestamp) [protected, virtual]
Reimplemented from iTaSC::ConstraintSet.
Definition at line 126 of file CopyPose.cpp.
References iTaSC::ConstraintSet::m_externalPose, iTaSC::ConstraintSet::m_internalPose, and updateJacobian().
void iTaSC::CopyPose::pushCache (const Timestamp & timestamp) [protected, virtual]
Implements iTaSC::ConstraintSet.
Definition at line 258 of file CopyPose.cpp.
References iTaSC::Timestamp::cache, iTaSC::Timestamp::cacheTimestamp, and iTaSC::Timestamp::substep.
Referenced by updateKinematics().
bool iTaSC::CopyPose::setControlParameters (struct ConstraintValues * _values, unsigned int _nvalues, double timestep) [virtual]
Implements iTaSC::ConstraintSet.
Definition at line 361 of file CopyPose.cpp.
References CTL_POSITIONX, CTL_ROTATION, CTL_ROTATIONX, iTaSC::ConstraintValues::id, ID_POSITION, ID_POSITIONZ, ID_ROTATION, and ID_ROTATIONZ.
Referenced by updateControlOutput().
void iTaSC::CopyPose::updateControlOutput (const Timestamp & timestamp) [protected, virtual]
Implements iTaSC::ConstraintSet.
Definition at line 425 of file CopyPose.cpp.
References iTaSC::Timestamp::cacheTimestamp, CTL_POSITIONX, CTL_ROTATION, CTL_ROTATIONX, KDL::diff(), iTaSC::F_identity, iTaSC::Timestamp::interpolate, iTaSC::ConstraintSet::m_constraintCallback, iTaSC::ConstraintSet::m_constraintParam, iTaSC::ConstraintSet::m_internalPose, iTaSC::ConstraintSet::m_substep, iTaSC::Timestamp::realTimestep, iTaSC::Timestamp::reiterate, KDL::Twist::rot, setControlParameters(), iTaSC::Timestamp::substep, and KDL::Twist::vel.
void iTaSC::CopyPose::updateJacobian () [protected, virtual]
Implements iTaSC::ConstraintSet.
Definition at line 276 of file CopyPose.cpp.
Referenced by initialise(), and modelUpdate().
void iTaSC::CopyPose::updateKinematics (const Timestamp & timestamp) [protected, virtual]
Implements iTaSC::ConstraintSet.
Definition at line 265 of file CopyPose.cpp.
References CTL_POSITIONX, CTL_ROTATION, CTL_ROTATIONX, iTaSC::Timestamp::interpolate, and pushCache().
The documentation for this class was generated from the following files:
CopyPose.hpp
CopyPose.cpp