Blender: bsdf_reflection.h File Reference
bsdf_reflection.h File Reference
Classes
struct BsdfReflectionClosure
Typedefs
typedef CCL_NAMESPACE_BEGIN
struct BsdfReflectionClosure BsdfReflectionClosure
Functions
__device void bsdf_reflection_setup (ShaderData *sd, ShaderClosure *sc)
__device void bsdf_reflection_blur (ShaderClosure *sc, float roughness)
__device float3 bsdf_reflection_eval_reflect (const ShaderData *sd, const ShaderClosure *sc, const float3 I, const float3 omega_in, float *pdf)
__device float3 bsdf_reflection_eval_transmit (const ShaderData *sd, const ShaderClosure *sc, const float3 I, const float3 omega_in, float *pdf)
__device float bsdf_reflection_albedo (const ShaderData *sd, const ShaderClosure *sc, const float3 I)
__device int bsdf_reflection_sample (const ShaderData *sd, const ShaderClosure *sc, float randu, float randv, float3 *eval, float3 *omega_in, float3 *domega_in_dx, float3 *domega_in_dy, float *pdf)
Typedef Documentation
typedef CCL_NAMESPACE_BEGIN struct BsdfReflectionClosure BsdfReflectionClosure
Function Documentation
__device float bsdf_reflection_albedo (const ShaderData * sd, const ShaderClosure * sc, const float3 I)
Definition at line 64 of file bsdf_reflection.h.
__device void bsdf_reflection_blur (ShaderClosure * sc, float roughness)
Definition at line 50 of file bsdf_reflection.h.
Referenced by svm_bsdf_blur().
__device float3 bsdf_reflection_eval_reflect (const ShaderData * sd, const ShaderClosure * sc, const float3 I, const float3 omega_in, float * pdf)
Definition at line 54 of file bsdf_reflection.h.
References make_float3().
Referenced by svm_bsdf_eval().
__device float3 bsdf_reflection_eval_transmit (const ShaderData * sd, const ShaderClosure * sc, const float3 I, const float3 omega_in, float * pdf)
Definition at line 59 of file bsdf_reflection.h.
References make_float3().
Referenced by svm_bsdf_eval().
__device int bsdf_reflection_sample (const ShaderData * sd, const ShaderClosure * sc, float randu, float randv, float3 * eval, float3 * omega_in, float3 * domega_in_dx, float3 * domega_in_dy, float * pdf)
Definition at line 69 of file bsdf_reflection.h.
References ShaderData::dI, dot(), differential3::dx, differential3::dy, ShaderData::I, LABEL_REFLECT, LABEL_SINGULAR, make_float3(), ShaderData::N, and ShaderData::Ng.
Referenced by svm_bsdf_sample().
__device void bsdf_reflection_setup (ShaderData * sd, ShaderClosure * sc)
Definition at line 44 of file bsdf_reflection.h.
References CLOSURE_BSDF_REFLECTION_ID, ShaderData::flag, SD_BSDF, and ShaderClosure::type.
Referenced by svm_node_closure_bsdf(), and svm_node_glossy_setup().