Blender: editmesh_knife.c File Reference
editmesh_knife.c File Reference
mesh
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_array.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_smallhash.h"
#include "BLI_scanfill.h"
#include "BLI_memarena.h"
#include "BKE_DerivedMesh.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "ED_screen.h"
#include "ED_space_api.h"
#include "ED_view3d.h"
#include "ED_mesh.h"
#include "WM_api.h"
#include "WM_types.h"
#include "DNA_scene_types.h"
#include "DNA_mesh_types.h"
#include "DNA_object_types.h"
#include "BKE_tessmesh.h"
#include "UI_resources.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "mesh_intern.h"
Classes
struct KnifeColors
struct KnifeVert
struct Ref
struct KnifeEdge
struct BMEdgeHit
struct KnifePosData
struct KnifeTool_OpData
Defines
#define _USE_MATH_DEFINES
#define KMAXDIST 10
#define HEADER_LENGTH 190
#define MARK 4
#define DEL 8
#define VERT_ON_EDGE 16
#define VERT_ORIG 32
#define FACE_FLIP 64
#define BOUNDARY 128
#define FACE_NEW 256
#define SCANFILL_CUTS 0
Typedefs
typedef struct KnifeColors KnifeColors
typedef struct KnifeVert KnifeVert
typedef struct Ref Ref
typedef struct KnifeEdge KnifeEdge
typedef struct BMEdgeHit BMEdgeHit
typedef struct KnifePosData KnifePosData
typedef struct KnifeTool_OpData KnifeTool_OpData
Enumerations
enum {
KNF_MODAL_CANCEL = 1, KNF_MODAL_CONFIRM, KNF_MODAL_MIDPOINT_ON, KNF_MODAL_MIDPOINT_OFF,
KNF_MODAL_NEW_CUT, KNF_MODEL_IGNORE_SNAP_ON, KNF_MODEL_IGNORE_SNAP_OFF, KNF_MODAL_ADD_CUT,
KNF_MODAL_ANGLE_SNAP_TOGGLE, KNF_MODAL_CUT_THROUGH_TOGGLE
}
Functions
static ListBase * knife_get_face_kedges (KnifeTool_OpData *kcd, BMFace *f)
static void knife_input_ray_cast (KnifeTool_OpData *kcd, const int mval_i[2], float r_origin[3], float r_ray[3])
static void knife_update_header (bContext *C, KnifeTool_OpData *kcd)
static void knife_project_v3 (KnifeTool_OpData *kcd, const float co[3], float sco[3])
static void knife_pos_data_clear (KnifePosData *kpd)
static ListBase * knife_empty_list (KnifeTool_OpData *kcd)
static void knife_append_list (KnifeTool_OpData *kcd, ListBase *lst, void *elem)
static Ref * find_ref (ListBase *lb, void *ref)
static KnifeEdge * new_knife_edge (KnifeTool_OpData *kcd)
static void knife_add_to_vert_edges (KnifeTool_OpData *kcd, KnifeEdge *kfe)
static KnifeVert * new_knife_vert (KnifeTool_OpData *kcd, float *co, float *cageco)
static KnifeVert * get_bm_knife_vert (KnifeTool_OpData *kcd, BMVert *v)
static KnifeEdge * get_bm_knife_edge (KnifeTool_OpData *kcd, BMEdge *e)
static void knife_start_cut (KnifeTool_OpData *kcd)
static void knife_find_basef (KnifeTool_OpData *kcd, KnifeEdge *kfe)
static void knife_edge_append_face (KnifeTool_OpData *kcd, KnifeEdge *kfe, BMFace *f)
static KnifeVert * knife_split_edge (KnifeTool_OpData *kcd, KnifeEdge *kfe, float co[3], KnifeEdge **newkfe_out)
static void knife_add_single_cut (KnifeTool_OpData *kcd)
static int verge_linehit (const void *vlh1, const void *vlh2)
static void knife_add_single_cut_through (KnifeTool_OpData *kcd, KnifeVert *v1, KnifeVert *v2, BMFace *f)
static void knife_get_vert_faces (KnifeTool_OpData *kcd, KnifeVert *kfv, BMFace *facef, ListBase *lst)
static void knife_get_edge_faces (KnifeTool_OpData *kcd, KnifeEdge *kfe, ListBase *lst)
static void knife_cut_through (KnifeTool_OpData *kcd)
static void knife_add_cut (KnifeTool_OpData *kcd)
static void knife_finish_cut (KnifeTool_OpData *UNUSED(kcd))
static void knifetool_draw_angle_snapping (KnifeTool_OpData *kcd)
static void knife_init_colors (KnifeColors *colors)
static void knifetool_draw (const bContext *C, ARegion *UNUSED(ar), void *arg)
static float len_v3_tri_side_max (const float v1[3], const float v2[3], const float v3[3])
static BMEdgeHit * knife_edge_tri_isect (KnifeTool_OpData *kcd, BMBVHTree *bmtree, const float v1[3], const float v2[3], const float v3[3], SmallHash *ehash, bglMats *mats, int *count)
static void knife_bgl_get_mats (KnifeTool_OpData *UNUSED(kcd), bglMats *mats)
static void knife_find_line_hits (KnifeTool_OpData *kcd)
static BMFace * knife_find_closest_face (KnifeTool_OpData *kcd, float co[3], float cageco[3], int *is_space)
static int knife_sample_screen_density (KnifeTool_OpData *kcd, float radius)
static float knife_snap_size (KnifeTool_OpData *kcd, float maxsize)
static KnifeEdge * knife_find_closest_edge (KnifeTool_OpData *kcd, float p[3], float cagep[3], BMFace **fptr, int *is_space)
static KnifeVert * knife_find_closest_vert (KnifeTool_OpData *kcd, float p[3], float cagep[3], BMFace **fptr, int *is_space)
static void knife_snap_angle (KnifeTool_OpData *kcd)
static int knife_update_active (KnifeTool_OpData *kcd)
static float frac_along (const float a[3], const float b[3], const float v[3])
static void sort_by_frac_along (ListBase *lst, BMEdge *e)
static int find_chain_search (KnifeTool_OpData *kcd, KnifeVert *kfv, ListBase *fedges, SmallHash *visited, ListBase *chain)
static ListBase * find_chain_from_vertex (KnifeTool_OpData *kcd, KnifeEdge *kfe, BMVert *v, ListBase *fedges)
static ListBase * find_chain (KnifeTool_OpData *kcd, ListBase *fedges)
static int find_hole_search (KnifeTool_OpData *kcd, KnifeVert *kfvfirst, KnifeVert *kfv, ListBase *fedges, SmallHash *visited, ListBase *hole)
static ListBase * find_hole (KnifeTool_OpData *kcd, ListBase *fedges)
static int find_hole_chains (KnifeTool_OpData *kcd, ListBase *hole, BMFace *f, ListBase **mainchain, ListBase **sidechain)
static int knife_edge_in_face (KnifeTool_OpData *UNUSED(kcd), KnifeEdge *kfe, BMFace *f)
static void knife_make_chain_cut (KnifeTool_OpData *kcd, BMFace *f, ListBase *chain, BMFace **newface)
static void knife_make_face_cuts (KnifeTool_OpData *kcd, BMFace *f, ListBase *kfedges)
static void knife_make_cuts (KnifeTool_OpData *kcd)
static void knifetool_finish (bContext *C, wmOperator *op)
static int project_knife_view_clip (View3D *v3d, RegionView3D *rv3d, float *clipsta, float *clipend)
static void knife_recalc_projmat (KnifeTool_OpData *kcd)
static void knifetool_exit (bContext *C, wmOperator *op)
static void cage_mapped_verts_callback (void *userData, int index, const float co[3], const float UNUSED(no_f[3]), const short UNUSED(no_s[3]))
static void knifetool_update_mval (KnifeTool_OpData *kcd, int mval[2])
static int knifetool_init (bContext *C, wmOperator *op, int UNUSED(do_cut))
static int knifetool_cancel (bContext *C, wmOperator *op)
static int knifetool_invoke (bContext *C, wmOperator *op, wmEvent *evt)
wmKeyMap * knifetool_modal_keymap (wmKeyConfig *keyconf)
static int knifetool_modal (bContext *C, wmOperator *op, wmEvent *event)
void MESH_OT_knife_tool (wmOperatorType *ot)
Detailed Description
Definition in file editmesh_knife.c.
Define Documentation
#define _USE_MATH_DEFINES
Definition at line 32 of file editmesh_knife.c.
#define BOUNDARY 128
Definition at line 1649 of file editmesh_knife.c.
#define DEL 8
Definition at line 1645 of file editmesh_knife.c.
#define FACE_FLIP 64
Definition at line 1648 of file editmesh_knife.c.
#define FACE_NEW 256
Definition at line 1650 of file editmesh_knife.c.
#define HEADER_LENGTH 190
Referenced by knife_update_header().
#define KMAXDIST 10
Definition at line 72 of file editmesh_knife.c.
Referenced by knife_find_closest_face(), and knifetool_init().
#define MARK 4
Definition at line 1644 of file editmesh_knife.c.
#define SCANFILL_CUTS 0
Definition at line 1652 of file editmesh_knife.c.
#define VERT_ON_EDGE 16
Definition at line 1646 of file editmesh_knife.c.
#define VERT_ORIG 32
Definition at line 1647 of file editmesh_knife.c.
Typedef Documentation
typedef struct BMEdgeHit BMEdgeHit
typedef struct KnifeColors KnifeColors
typedef struct KnifeEdge KnifeEdge
typedef struct KnifePosData KnifePosData
typedef struct KnifeTool_OpData KnifeTool_OpData
typedef struct KnifeVert KnifeVert
typedef struct Ref Ref
Enumeration Type Documentation
anonymous enum
Enumerator:
KNF_MODAL_CANCEL
KNF_MODAL_CONFIRM
KNF_MODAL_MIDPOINT_ON
KNF_MODAL_MIDPOINT_OFF
KNF_MODAL_NEW_CUT
KNF_MODEL_IGNORE_SNAP_ON
KNF_MODEL_IGNORE_SNAP_OFF
KNF_MODAL_ADD_CUT
KNF_MODAL_ANGLE_SNAP_TOGGLE
KNF_MODAL_CUT_THROUGH_TOGGLE
Definition at line 2878 of file editmesh_knife.c.
Function Documentation
static void cage_mapped_verts_callback (void * userData, int index, const float co[3], const float UNUSEDno_f[3], const short UNUSEDno_s[3]) [static]
Definition at line 2753 of file editmesh_knife.c.
References BLI_smallhash_haskey(), BLI_smallhash_insert(), copy_v3_v3(), data, NULL, and BMesh::totvert.
Referenced by knifetool_init().
static ListBase* find_chain (KnifeTool_OpData * kcd, ListBase * fedges) [static]
Definition at line 2120 of file editmesh_knife.c.
References BLI_assert, BLI_countlist(), BLI_remlink(), find_chain_from_vertex(), find_ref(), ListBase::first, knife_append_list(), knife_empty_list(), Ref::next, NULL, Ref::ref, KnifeVert::v, KnifeEdge::v1, and KnifeEdge::v2.
Referenced by knife_make_face_cuts().
static ListBase* find_chain_from_vertex (KnifeTool_OpData * kcd, KnifeEdge * kfe, BMVert * v, ListBase * fedges) [static]
Definition at line 2090 of file editmesh_knife.c.
References BLI_assert, BLI_smallhash_init(), BLI_smallhash_insert(), BLI_smallhash_release(), find_chain_search(), knife_append_list(), knife_empty_list(), NULL, KnifeVert::v, KnifeEdge::v1, and KnifeEdge::v2.
Referenced by find_chain().
static int find_chain_search (KnifeTool_OpData * kcd, KnifeVert * kfv, ListBase * fedges, SmallHash * visited, ListBase * chain) [static]
Definition at line 2058 of file editmesh_knife.c.
References BLI_remlink(), BLI_smallhash_haskey(), BLI_smallhash_insert(), FALSE, ListBase::first, knife_append_list(), ListBase::last, Ref::next, NULL, Ref::ref, TRUE, KnifeVert::v, KnifeEdge::v1, and KnifeEdge::v2.
Referenced by find_chain_from_vertex().
static ListBase* find_hole (KnifeTool_OpData * kcd, ListBase * fedges) [static]
Definition at line 2194 of file editmesh_knife.c.
References BLI_remlink(), BLI_smallhash_init(), BLI_smallhash_release(), FALSE, find_hole_search(), find_ref(), ListBase::first, knife_append_list(), knife_empty_list(), Ref::next, NULL, Ref::ref, KnifeVert::v, KnifeEdge::v1, and KnifeEdge::v2.
Referenced by knife_make_face_cuts().
static int find_hole_chains (KnifeTool_OpData * kcd, ListBase * hole, BMFace * f, ListBase ** mainchain, ListBase ** sidechain) [static]
Definition at line 2237 of file editmesh_knife.c.
References KnifeTool_OpData::arena, axis_dominant_v3(), BLI_assert, BLI_countlist(), BLI_memarena_alloc(), BM_ITER_ELEM, BM_VERTS_OF_FACE, KnifeVert::co, BMVert::co, FALSE, ListBase::first, FLT_MAX, get_bm_knife_vert(), i, isect_line_line_v2(), knife_append_list(), knife_empty_list(), BMFace::len, len_squared_v2v2(), MIN2, new_knife_edge(), Ref::next, BMFace::no, NULL, Ref::ref, TRUE, KnifeEdge::v1, and KnifeEdge::v2.
Referenced by knife_make_face_cuts().
static int find_hole_search (KnifeTool_OpData * kcd, KnifeVert * kfvfirst, KnifeVert * kfv, ListBase * fedges, SmallHash * visited, ListBase * hole) [static]
Definition at line 2159 of file editmesh_knife.c.
References BLI_remlink(), BLI_smallhash_haskey(), BLI_smallhash_insert(), FALSE, ListBase::first, knife_append_list(), ListBase::last, Ref::next, NULL, Ref::ref, TRUE, KnifeVert::v, KnifeEdge::v1, and KnifeEdge::v2.
Referenced by find_hole().
static Ref* find_ref (ListBase * lb, void * ref) [static]
Definition at line 256 of file editmesh_knife.c.
References ListBase::first, Ref::next, NULL, and Ref::ref.
Referenced by find_chain(), find_hole(), knife_add_single_cut(), knife_add_single_cut_through(), knife_make_cuts(), and knife_split_edge().
static float frac_along (const float a[3], const float b[3], const float v[3]) [static]
Definition at line 2011 of file editmesh_knife.c.
References len_v3v3().
Referenced by knife_make_cuts(), and sort_by_frac_along().
static KnifeEdge* get_bm_knife_edge (KnifeTool_OpData * kcd, BMEdge * e) [static]
get a KnifeEdge wrapper for an existing BMEdge
Note:
knife_get_face_kedges / get_bm_knife_edge are called recusively - KEEP STACK MEM USAGE LOW
Definition at line 312 of file editmesh_knife.c.
References BLI_ghash_insert(), BLI_ghash_lookup(), KnifeEdge::e, BMLoop::f, KnifeEdge::faces, get_bm_knife_vert(), knife_add_to_vert_edges(), knife_append_list(), knife_get_face_kedges(), BMEdge::l, new_knife_edge(), KnifeTool_OpData::origedgemap, BMLoop::radial_next, BMEdge::v1, KnifeEdge::v1, BMEdge::v2, and KnifeEdge::v2.
Referenced by knife_get_face_kedges().
static KnifeVert* get_bm_knife_vert (KnifeTool_OpData * kcd, BMVert * v) [static]
Definition at line 296 of file editmesh_knife.c.
References BLI_ghash_insert(), BLI_ghash_lookup(), BM_elem_index_get, KnifeTool_OpData::cagecos, BMVert::co, new_knife_vert(), KnifeTool_OpData::origvertmap, and KnifeVert::v.
Referenced by find_hole_chains(), and get_bm_knife_edge().
static void knife_add_cut (KnifeTool_OpData * kcd) [static]
Definition at line 708 of file editmesh_knife.c.
References KnifePosData::bmface, KnifePosData::cage, BMEdgeHit::cagehit, KnifePosData::co, copy_v3_v3(), KnifeTool_OpData::cur, KnifeTool_OpData::cut_through, KnifePosData::edge, BMEdgeHit::f, BMEdgeHit::hit, i, KnifePosData::is_space, BMEdgeHit::kfe, knife_add_single_cut(), knife_cut_through(), len_v3v3(), KnifeTool_OpData::linehits, MEM_freeN(), NULL, KnifeTool_OpData::prev, BMEdgeHit::realhit, KnifeTool_OpData::totlinehit, KnifeVert::v, BMEdgeHit::v, verge_linehit(), and KnifePosData::vert.
Referenced by knifetool_modal().
static void knife_add_single_cut (KnifeTool_OpData * kcd) [static]
Definition at line 470 of file editmesh_knife.c.
References KnifeEdge::basef, KnifePosData::bmface, KnifePosData::co, KnifeTool_OpData::cur, KnifeEdge::draw, KnifeVert::draw, KnifePosData::edge, KnifeEdge::faces, find_ref(), KnifeVert::inspace, KnifePosData::is_space, KnifeVert::isface, knife_add_to_vert_edges(), knife_edge_append_face(), knife_find_basef(), knife_split_edge(), new_knife_edge(), new_knife_vert(), NULL, KnifeTool_OpData::prev, KnifeEdge::v1, KnifeEdge::v2, and KnifePosData::vert.
Referenced by knife_add_cut(), and knife_cut_through().
static void knife_add_single_cut_through (KnifeTool_OpData * kcd, KnifeVert * v1, KnifeVert * v2, BMFace * f) [static]
Definition at line 547 of file editmesh_knife.c.
References KnifeEdge::basef, KnifeEdge::draw, KnifeEdge::faces, find_ref(), knife_add_to_vert_edges(), knife_edge_append_face(), new_knife_edge(), KnifeEdge::v1, and KnifeEdge::v2.
Referenced by knife_cut_through().
static void knife_add_to_vert_edges (KnifeTool_OpData * kcd, KnifeEdge * kfe) [static]
Definition at line 274 of file editmesh_knife.c.
References KnifeVert::edges, knife_append_list(), KnifeEdge::v1, and KnifeEdge::v2.
Referenced by get_bm_knife_edge(), knife_add_single_cut(), knife_add_single_cut_through(), and knife_split_edge().
static void knife_append_list (KnifeTool_OpData * kcd, ListBase * lst, void * elem) [static]
Definition at line 247 of file editmesh_knife.c.
References BLI_addtail(), BLI_mempool_calloc(), Ref::ref, and KnifeTool_OpData::refs.
Referenced by find_chain(), find_chain_from_vertex(), find_chain_search(), find_hole(), find_hole_chains(), find_hole_search(), get_bm_knife_edge(), knife_add_to_vert_edges(), knife_edge_append_face(), knife_get_edge_faces(), knife_get_face_kedges(), knife_get_vert_faces(), knife_make_cuts(), and knife_make_face_cuts().
static void knife_bgl_get_mats (KnifeTool_OpData * UNUSEDkcd, bglMats * mats) [static]
Definition at line 1204 of file editmesh_knife.c.
References bgl_get_mats().
Referenced by knife_find_line_hits(), and knife_input_ray_cast().
static void knife_cut_through (KnifeTool_OpData * kcd) [static]
Definition at line 594 of file editmesh_knife.c.
References KnifePosData::bmface, KnifePosData::co, KnifeTool_OpData::cur, KnifePosData::edge, KnifeEdge::faces, ListBase::first, BMEdgeHit::hit, i, BMEdgeHit::kfe, knife_add_single_cut(), knife_add_single_cut_through(), knife_get_edge_faces(), knife_get_vert_faces(), knife_split_edge(), KnifeTool_OpData::linehits, MEM_callocN(), MEM_freeN(), Ref::next, NULL, KnifeTool_OpData::prev, Ref::ref, KnifeTool_OpData::totlinehit, KnifeEdge::v1, verge_linehit(), and KnifePosData::vert.
Referenced by knife_add_cut().
static void knife_edge_append_face (KnifeTool_OpData * kcd, KnifeEdge * kfe, BMFace * f) [static]
Definition at line 423 of file editmesh_knife.c.
References KnifeEdge::faces, knife_append_list(), and knife_get_face_kedges().
Referenced by knife_add_single_cut(), knife_add_single_cut_through(), and knife_split_edge().
static int knife_edge_in_face (KnifeTool_OpData * UNUSEDkcd, KnifeEdge * kfe, BMFace * f) [static]
Definition at line 2379 of file editmesh_knife.c.
References BM_face_point_inside_test(), BM_ITER_ELEM, BM_LOOPS_OF_FACE, KnifeVert::co, FALSE, mid_v3_v3v3(), NULL, TRUE, KnifeVert::v, BMLoop::v, KnifeEdge::v1, and KnifeEdge::v2.
Referenced by knife_make_face_cuts().
static BMEdgeHit* knife_edge_tri_isect (KnifeTool_OpData * kcd, BMBVHTree * bmtree, const float v1[3], const float v2[3], const float v3[3], SmallHash * ehash, bglMats * mats, int * count) [static]
Definition at line 1062 of file editmesh_knife.c.
References add_v3_v3(), BLI_array_append, BLI_array_count, BLI_array_declare, BLI_bvhtree_balance(), BLI_bvhtree_free(), BLI_bvhtree_insert(), BLI_bvhtree_new(), BLI_bvhtree_overlap(), BLI_smallhash_haskey(), BLI_smallhash_insert(), BMBVH_BVHTree(), BMBVH_RayCast(), KnifePosData::cage, KnifeVert::cageco, BMEdgeHit::cagehit, KnifePosData::co, copy_v3_v3(), cos(), KnifeTool_OpData::cur, KnifeTool_OpData::cut_through, KnifeTool_OpData::em, BMLoop::f, BMEdgeHit::f, FALSE, ListBase::first, BMEdgeHit::hit, i, Object::imat, BVHTreeOverlap::indexA, interp_v3_v3v3(), isect_line_tri_v3(), BMEdgeHit::kfe, knife_find_basef(), knife_get_face_kedges(), knife_project_v3(), len_squared_v3v3(), len_v3_tri_side_max(), len_v3v3(), BMEditMesh::looptris, MEM_freeN(), mul_m4_v3(), mul_v3_fl(), Ref::next, normalize_v3(), NULL, KnifeTool_OpData::ob, p, BMEdgeHit::perc, KnifeTool_OpData::prev, BMEdgeHit::realhit, Ref::ref, BMEdgeHit::schit, KnifeTool_OpData::snap_midpoints, sub_v3_v3(), BMEdgeHit::v, KnifeEdge::v1, KnifeEdge::v2, KnifePosData::vert, and view3d_unproject().
Referenced by knife_find_line_hits().
static ListBase* knife_empty_list (KnifeTool_OpData * kcd) [static]
Definition at line 238 of file editmesh_knife.c.
References KnifeTool_OpData::arena, BLI_memarena_alloc(), ListBase::first, ListBase::last, and NULL.
Referenced by find_chain(), find_chain_from_vertex(), find_hole(), find_hole_chains(), knife_get_face_kedges(), knife_make_cuts(), and knife_make_face_cuts().
static void knife_find_basef (KnifeTool_OpData * kcd, KnifeEdge * kfe) [static]
Definition at line 392 of file editmesh_knife.c.
References KnifeEdge::basef, KnifePosData::bmface, KnifeTool_OpData::cur, KnifeVert::edges, KnifeEdge::faces, ListBase::first, KnifeVert::isface, Ref::next, KnifeTool_OpData::prev, Ref::ref, KnifeEdge::v1, and KnifeEdge::v2.
Referenced by knife_add_single_cut(), and knife_edge_tri_isect().
static KnifeEdge* knife_find_closest_edge (KnifeTool_OpData * kcd, float p[3], float cagep[3], BMFace ** fptr, int * is_space) [static]
Definition at line 1409 of file editmesh_knife.c.
References KnifePosData::bmface, KnifeVert::cageco, closest_to_line_segment_v3(), KnifeVert::co, co, copy_v3_v3(), KnifeTool_OpData::cur, dist_to_line_segment_v2(), KnifeEdge::e, ED_view3d_clipping_test(), KnifeTool_OpData::ethresh, ListBase::first, FLT_MAX, KnifeTool_OpData::ignore_edge_snapping, KnifeTool_OpData::ignore_vert_snapping, interp_v3_v3v3(), knife_find_closest_face(), knife_get_face_kedges(), knife_project_v3(), knife_snap_size(), labda_PdistVL2Dfl(), len_v3v3(), mid_v3_v3v3(), mul_m4_v3(), Ref::next, NULL, ViewContext::obedit, Object::obmat, Ref::ref, RegionView3D::rflag, ViewContext::rv3d, RV3D_CLIPPING, KnifeVert::sco, KnifeTool_OpData::snap_midpoints, TRUE, KnifeEdge::v1, KnifeEdge::v2, and KnifeTool_OpData::vc.
Referenced by knife_update_active().
static BMFace* knife_find_closest_face (KnifeTool_OpData * kcd, float co[3], float cageco[3], int * is_space) [static]
Definition at line 1315 of file editmesh_knife.c.
References add_v3_v3v3(), KnifeTool_OpData::bmbvh, BMBVH_RayCast(), EDBM_face_find_nearest(), KMAXDIST, knife_input_ray_cast(), ViewContext::mval, and KnifeTool_OpData::vc.
Referenced by knife_find_closest_edge(), knife_find_closest_vert(), and knife_sample_screen_density().
static KnifeVert* knife_find_closest_vert (KnifeTool_OpData * kcd, float p[3], float cagep[3], BMFace ** fptr, int * is_space) [static]
Definition at line 1498 of file editmesh_knife.c.
References KnifePosData::bmface, KnifeVert::cageco, KnifeVert::co, co, copy_v3_v3(), KnifeTool_OpData::cur, ED_view3d_clipping_test(), ListBase::first, FLT_MAX, i, KnifeTool_OpData::ignore_vert_snapping, knife_find_closest_face(), knife_get_face_kedges(), knife_project_v3(), knife_snap_size(), len_v2v2(), mul_m4_v3(), Ref::next, NULL, ViewContext::obedit, Object::obmat, Ref::ref, RegionView3D::rflag, ViewContext::rv3d, RV3D_CLIPPING, KnifeVert::sco, TRUE, KnifeVert::v, KnifeEdge::v1, KnifeEdge::v2, KnifeTool_OpData::vc, and KnifeTool_OpData::vthresh.
Referenced by knife_update_active().
static void knife_find_line_hits (KnifeTool_OpData * kcd) [static]
Definition at line 1212 of file editmesh_knife.c.
References KnifeTool_OpData::ar, BLI_smallhash_init(), BLI_smallhash_release(), KnifeTool_OpData::bmbvh, KnifePosData::cage, copy_v3_v3(), KnifeTool_OpData::cur, ED_view3d_win_to_segment_clip(), hash, i, Object::imat, KnifeTool_OpData::is_ortho, knife_bgl_get_mats(), knife_edge_tri_isect(), knife_project_v3(), BMEdgeHit::l, len_v2v2(), limit_dist_v3(), KnifeTool_OpData::linehits, MEM_freeN(), MEM_reallocN(), mul_m4_v3(), NULL, KnifeTool_OpData::ob, KnifeTool_OpData::prev, BMEdgeHit::schit, KnifeTool_OpData::totlinehit, ViewContext::v3d, and KnifeTool_OpData::vc.
Referenced by knife_update_active().
static void knife_finish_cut (KnifeTool_OpData * UNUSEDkcd) [static]
Definition at line 787 of file editmesh_knife.c.
Referenced by knifetool_modal().
static void knife_get_edge_faces (KnifeTool_OpData * kcd, KnifeEdge * kfe, ListBase * lst) [static]
Definition at line 579 of file editmesh_knife.c.
References BM_FACES_OF_EDGE, BM_ITER_ELEM, KnifeEdge::e, and knife_append_list().
Referenced by knife_cut_through().
static ListBase * knife_get_face_kedges (KnifeTool_OpData * kcd, BMFace * f) [static]
Note:
knife_get_face_kedges / get_bm_knife_edge are called recusively - KEEP STACK MEM USAGE LOW
Definition at line 369 of file editmesh_knife.c.
References BLI_ghash_insert(), BLI_ghash_lookup(), BM_FACE_FIRST_LOOP, BMLoop::e, get_bm_knife_edge(), KnifeTool_OpData::kedgefacemap, knife_append_list(), knife_empty_list(), and BMLoop::next.
Referenced by get_bm_knife_edge(), knife_edge_append_face(), knife_edge_tri_isect(), knife_find_closest_edge(), knife_find_closest_vert(), and knife_sample_screen_density().
static void knife_get_vert_faces (KnifeTool_OpData * kcd, KnifeVert * kfv, BMFace * facef, ListBase * lst) [static]
Definition at line 564 of file editmesh_knife.c.
References BM_FACES_OF_VERT, BM_ITER_ELEM, KnifeVert::isface, knife_append_list(), and KnifeVert::v.
Referenced by knife_cut_through().
static void knife_init_colors (KnifeColors * colors) [static]
Definition at line 889 of file editmesh_knife.c.
References KnifeColors::curpoint, KnifeColors::curpoint_a, KnifeColors::edge, KnifeColors::line, KnifeColors::point, KnifeColors::point_a, TH_ACTIVE_SPLINE, TH_HANDLE_SEL_VECT, TH_NURB_ULINE, TH_NURB_VLINE, and UI_GetThemeColor3ubv().
Referenced by knifetool_init().
static void knife_input_ray_cast (KnifeTool_OpData * kcd, const int mval_i[2], float r_origin[3], float r_ray[3]) [static]
Definition at line 1284 of file editmesh_knife.c.
References copy_m3_m4(), Object::imat, invert_m3(), invert_m4_m4(), KnifeTool_OpData::is_ortho, knife_bgl_get_mats(), mul_m3_v3(), mul_m4_v3(), negate_v3_v3(), normalize_v3(), KnifeTool_OpData::ob, Object::obmat, ViewContext::rv3d, sub_v3_v3v3(), KnifeTool_OpData::vc, view3d_unproject(), and RegionView3D::viewinv.
Referenced by knife_find_closest_face(), knife_start_cut(), and knife_update_active().
static void knife_make_chain_cut (KnifeTool_OpData * kcd, BMFace * f, ListBase * chain, BMFace ** newface) [static]
Definition at line 2422 of file editmesh_knife.c.
References BLI_array_fixedstack_declare, BLI_array_fixedstack_free, BLI_assert, BLI_countlist(), BMEditMesh::bm, BM_edge_exists(), BM_edge_select_set(), BM_face_split(), BM_face_split_n(), BM_NGON_STACK_SIZE, KnifeVert::co, BMVert::co, copy_v3_v3(), cos(), BMLoop::e, KnifeTool_OpData::em, equals_v3v3(), ListBase::first, i, ListBase::last, Ref::next, BMLoop::next, next, NULL, Ref::ref, KnifeTool_OpData::select_result, TRUE, KnifeVert::v, BMLoop::v, KnifeEdge::v1, and KnifeEdge::v2.
Referenced by knife_make_face_cuts().
static void knife_make_cuts (KnifeTool_OpData * kcd) [static]
Definition at line 2595 of file editmesh_knife.c.
References KnifeEdge::basef, BLI_mempool_iternew(), BLI_mempool_iterstep(), BLI_smallhash_init(), BLI_smallhash_insert(), BLI_smallhash_iternew(), BLI_smallhash_iternext(), BLI_smallhash_lookup(), BLI_smallhash_release(), BMEditMesh::bm, BM_edge_split(), BM_ELEM_SELECT, KnifeVert::co, KnifeEdge::e, EDBM_flag_disable_all(), KnifeVert::edges, KnifeTool_OpData::em, find_ref(), ListBase::first, frac_along(), KnifeTool_OpData::kedges, knife_append_list(), knife_empty_list(), knife_make_face_cuts(), KnifeTool_OpData::kverts, Ref::next, KnifeTool_OpData::only_select, Ref::ref, sort_by_frac_along(), and KnifeVert::v.
Referenced by knifetool_finish().
static void knife_make_face_cuts (KnifeTool_OpData * kcd, BMFace * f, ListBase * kfedges) [static]
Definition at line 2490 of file editmesh_knife.c.
References KnifeEdge::basef, BLI_assert, BLI_countlist(), BLI_remlink(), BMEditMesh::bm, BM_face_kill(), KnifeTool_OpData::em, find_chain(), find_hole(), find_hole_chains(), ListBase::first, knife_append_list(), knife_edge_in_face(), knife_empty_list(), knife_make_chain_cut(), Ref::next, NULL, and Ref::ref.
Referenced by knife_make_cuts().
static void knife_pos_data_clear (KnifePosData * kpd) [static]
Definition at line 227 of file editmesh_knife.c.
References KnifePosData::bmface, KnifePosData::cage, KnifePosData::co, KnifePosData::edge, KnifePosData::mval, NULL, KnifePosData::vert, and zero_v3().
Referenced by knife_update_active(), and knifetool_init().
static void knife_project_v3 (KnifeTool_OpData * kcd, const float co[3], float sco[3]) [static]
Definition at line 222 of file editmesh_knife.c.
References KnifeTool_OpData::ar, ED_view3d_project_float_v3(), and KnifeTool_OpData::projmat.
Referenced by knife_edge_tri_isect(), knife_find_closest_edge(), knife_find_closest_vert(), knife_find_line_hits(), knife_sample_screen_density(), knifetool_draw(), and new_knife_vert().
static void knife_recalc_projmat (KnifeTool_OpData * kcd) [static]
Definition at line 2704 of file editmesh_knife.c.
References KnifeTool_OpData::ar, KnifeTool_OpData::clipend, KnifeTool_OpData::clipsta, ED_view3d_ob_project_mat_get(), Object::imat, invert_m4_m4(), KnifeTool_OpData::is_ortho, KnifeTool_OpData::ob, Object::obmat, project_knife_view_clip(), KnifeTool_OpData::projmat, ARegion::regiondata, ViewContext::rv3d, ViewContext::v3d, and KnifeTool_OpData::vc.
Referenced by knifetool_init(), knifetool_modal(), and knifetool_update_mval().
static int knife_sample_screen_density (KnifeTool_OpData * kcd, float radius) [static]
Definition at line 1346 of file editmesh_knife.c.
References KnifeVert::cageco, co, copy_v3_v3(), ED_view3d_clipping_test(), ListBase::first, i, knife_find_closest_face(), knife_get_face_kedges(), knife_project_v3(), len_v2v2(), mul_m4_v3(), Ref::next, ViewContext::obedit, Object::obmat, Ref::ref, RegionView3D::rflag, ViewContext::rv3d, RV3D_CLIPPING, KnifeVert::sco, TRUE, KnifeEdge::v1, KnifeEdge::v2, and KnifeTool_OpData::vc.
Referenced by knife_snap_size().
static void knife_snap_angle (KnifeTool_OpData * kcd) [static]
Definition at line 1578 of file editmesh_knife.c.
References KnifeTool_OpData::angle_snapping, fabsf, ViewContext::mval, KnifePosData::mval, KnifeTool_OpData::prev, and KnifeTool_OpData::vc.
Referenced by knife_update_active().
static float knife_snap_size (KnifeTool_OpData * kcd, float maxsize) [static]
Definition at line 1399 of file editmesh_knife.c.
References knife_sample_screen_density(), MAX2, and MIN2.
Referenced by knife_find_closest_edge(), and knife_find_closest_vert().
static KnifeVert* knife_split_edge (KnifeTool_OpData * kcd, KnifeEdge * kfe, float co[3], KnifeEdge ** newkfe_out) [static]
Definition at line 429 of file editmesh_knife.c.
References KnifeEdge::basef, BLI_addtail(), BLI_remlink(), KnifeVert::cageco, KnifeVert::co, copy_v3_v3(), KnifeEdge::draw, KnifeVert::draw, KnifeEdge::e, KnifeVert::edges, KnifeEdge::faces, find_ref(), ListBase::first, interp_v3_v3v3(), knife_add_to_vert_edges(), knife_edge_append_face(), len_v3v3(), new_knife_edge(), new_knife_vert(), Ref::next, Ref::ref, KnifeEdge::v1, and KnifeEdge::v2.
Referenced by knife_add_single_cut(), and knife_cut_through().
static void knife_start_cut (KnifeTool_OpData * kcd) [static]
Definition at line 345 of file editmesh_knife.c.
References add_v3_v3v3(), BMEditMesh::bm, BM_vert_at_index(), KnifePosData::cage, closest_to_line_v3(), co, BMVert::co, KnifePosData::co, copy_v3_v3(), KnifeTool_OpData::cur, KnifePosData::edge, KnifeTool_OpData::em, KnifePosData::is_space, is_zero_v3(), knife_input_ray_cast(), KnifePosData::mval, NULL, KnifeTool_OpData::prev, and KnifePosData::vert.
Referenced by knifetool_modal().
static int knife_update_active (KnifeTool_OpData * kcd) [static]
Definition at line 1611 of file editmesh_knife.c.
References add_v3_v3v3(), KnifeTool_OpData::angle_snapping, KnifePosData::bmface, KnifePosData::cage, closest_to_line_v3(), co, KnifePosData::co, KnifeTool_OpData::cur, KnifePosData::edge, KnifePosData::is_space, knife_find_closest_edge(), knife_find_closest_vert(), knife_find_line_hits(), knife_input_ray_cast(), knife_pos_data_clear(), knife_snap_angle(), KnifeTool_OpData::mode, ViewContext::mval, KnifePosData::mval, NULL, KnifeTool_OpData::prev, KnifeTool_OpData::vc, and KnifePosData::vert.
Referenced by knifetool_modal(), and knifetool_update_mval().
static void knife_update_header (bContext * C, KnifeTool_OpData * kcd) [static]
Definition at line 206 of file editmesh_knife.c.
References KnifeTool_OpData::angle_snapping, BLI_snprintf(), CTX_wm_area(), KnifeTool_OpData::cut_through, ED_area_headerprint(), HEADER_LENGTH, KnifeTool_OpData::ignore_edge_snapping, and KnifeTool_OpData::snap_midpoints.
Referenced by knifetool_invoke(), and knifetool_modal().
static int knifetool_cancel (bContext * C, wmOperator * op) [static]
Definition at line 2850 of file editmesh_knife.c.
References knifetool_exit(), and OPERATOR_CANCELLED.
Referenced by MESH_OT_knife_tool().
static void knifetool_draw (const bContext * C, ARegion * UNUSEDar, void * arg) [static]
Definition at line 905 of file editmesh_knife.c.
References KnifeTool_OpData::angle_snapping, BLI_mempool_iternew(), BLI_mempool_iterstep(), KnifePosData::bmface, KnifePosData::cage, KnifeVert::cageco, BMEdgeHit::cagehit, KnifeTool_OpData::colors, copy_v3_v3(), CTX_wm_view3d(), KnifeTool_OpData::cur, KnifeColors::curpoint, KnifeColors::curpoint_a, KnifeEdge::draw, KnifeVert::draw, KnifeColors::edge, KnifePosData::edge, glMultMatrixf, i, KnifeTool_OpData::kedges, BMEdgeHit::kfe, knife_project_v3(), knifetool_draw_angle_snapping(), KnifeTool_OpData::kverts, len_v2v2(), KnifeColors::line, KnifeTool_OpData::linehits, KnifeTool_OpData::mode, KnifeTool_OpData::ob, Object::obmat, KnifeColors::point, KnifeColors::point_a, KnifeTool_OpData::prev, BMEdgeHit::schit, KnifeTool_OpData::totkedge, KnifeTool_OpData::totkvert, KnifeTool_OpData::totlinehit, BMEdgeHit::v, KnifeEdge::v1, KnifeEdge::v2, KnifePosData::vert, KnifeTool_OpData::vthresh, and View3D::zbuf.
Referenced by knifetool_init().
static void knifetool_draw_angle_snapping (KnifeTool_OpData * kcd) [static]
Definition at line 792 of file editmesh_knife.c.
References KnifeTool_OpData::angle_snapping, KnifeTool_OpData::ar, KnifePosData::cage, bglMats::modelview, KnifeTool_OpData::ob, KnifeTool_OpData::prev, bglMats::projection, ViewContext::rv3d, TH_TRANSFORM, UI_ThemeColor(), KnifeTool_OpData::vc, view3d_get_transformation(), bglMats::viewport, ARegion::winrct, ARegion::winx, ARegion::winy, rcti::xmin, and rcti::ymin.
Referenced by knifetool_draw().
static void knifetool_exit (bContext * C, wmOperator * op) [static]
Definition at line 2715 of file editmesh_knife.c.
References KnifeTool_OpData::ar, KnifeTool_OpData::arena, BLI_ghash_free(), BLI_memarena_free(), BLI_mempool_destroy(), KnifeTool_OpData::bmbvh, BMBVH_FreeBVH(), KnifeTool_OpData::cagecos, CTX_wm_window(), wmOperator::customdata, KnifeTool_OpData::draw_handle, ED_region_draw_cb_exit(), ED_region_tag_redraw(), KnifeTool_OpData::kedgefacemap, KnifeTool_OpData::kedges, KnifeTool_OpData::kverts, KnifeTool_OpData::linehits, MEM_freeN(), NULL, KnifeTool_OpData::origedgemap, KnifeTool_OpData::origvertmap, KnifeTool_OpData::refs, ARegion::type, and WM_cursor_restore().
Referenced by knifetool_cancel(), and knifetool_modal().
static void knifetool_finish (bContext * C, wmOperator * op) [static]
Definition at line 2677 of file editmesh_knife.c.
References wmOperator::customdata, EDBM_update_generic(), KnifeTool_OpData::em, knife_make_cuts(), and TRUE.
Referenced by knifetool_modal().
static int knifetool_init (bContext * C, wmOperator * op, int UNUSEDdo_cut) [static]
Definition at line 2779 of file editmesh_knife.c.
References KnifeTool_OpData::ar, KnifeTool_OpData::arena, BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BLI_memarena_new(), BLI_MEMPOOL_ALLOW_ITER, BLI_mempool_create(), BLI_smallhash_init(), BLI_smallhash_release(), BMEditMesh::bm, BM_mesh_elem_index_ensure(), BM_VERT, KnifeTool_OpData::bmbvh, BMBVH_NewBVH(), BMBVH_RESPECT_HIDDEN, BMBVH_RESPECT_SELECT, BMBVH_RETURN_ORIG, BMBVH_USE_CAGE, BMEdit_FromObject(), cage_mapped_verts_callback(), KnifeTool_OpData::cagecos, CD_MASK_DERIVEDMESH, KnifeTool_OpData::colors, CTX_data_edit_object(), CTX_data_scene(), CTX_wm_region(), KnifeTool_OpData::cur, wmOperator::customdata, KnifeTool_OpData::cut_through, data, KnifeTool_OpData::draw_handle, ED_region_draw_cb_activate(), ED_region_tag_redraw(), editbmesh_get_derived_cage_and_final(), KnifeTool_OpData::em, em_setup_viewcontext(), KnifeTool_OpData::ethresh, KnifeTool_OpData::extend, DerivedMesh::foreachMappedVert, KnifeTool_OpData::kedgefacemap, KnifeTool_OpData::kedges, KMAXDIST, knife_init_colors(), knife_pos_data_clear(), knife_recalc_projmat(), knifetool_draw(), KnifeTool_OpData::kverts, MEM_callocN(), KnifeTool_OpData::ob, KnifeTool_OpData::only_select, KnifeTool_OpData::origedgemap, KnifeTool_OpData::origvertmap, KnifeTool_OpData::prev, wmOperator::ptr, KnifeTool_OpData::refs, REGION_DRAW_POST_VIEW, RNA_boolean_get(), SCE_SELECT_FACE, KnifeTool_OpData::select_result, BMEditMesh::selectmode, BMesh::totvert, ARegion::type, KnifeTool_OpData::vc, and KnifeTool_OpData::vthresh.
Referenced by knifetool_invoke().
static int knifetool_invoke (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 2857 of file editmesh_knife.c.
References BC_KNIFECURSOR, CTX_wm_window(), wmOperator::customdata, knife_update_header(), knifetool_init(), knifetool_update_mval(), wmEvent::mval, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, view3d_operator_needs_opengl(), WM_cursor_modal(), and WM_event_add_modal_handler().
Referenced by MESH_OT_knife_tool().
static int knifetool_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2941 of file editmesh_knife.c.
References KnifeTool_OpData::angle_snapping, KnifeTool_OpData::ar, BMEdit_FromObject(), CTX_data_edit_object(), CTX_wm_area(), wmOperator::customdata, KnifeTool_OpData::cut_through, ED_area_headerprint(), ED_region_tag_redraw(), KnifeTool_OpData::em, EVT_MODAL_MAP, KnifeTool_OpData::extend, KnifeTool_OpData::ignore_edge_snapping, KnifeTool_OpData::ignore_vert_snapping, KM_RELEASE, KNF_MODAL_ADD_CUT, KNF_MODAL_ANGLE_SNAP_TOGGLE, KNF_MODAL_CANCEL, KNF_MODAL_CONFIRM, KNF_MODAL_CUT_THROUGH_TOGGLE, KNF_MODAL_MIDPOINT_OFF, KNF_MODAL_MIDPOINT_ON, KNF_MODAL_NEW_CUT, KNF_MODEL_IGNORE_SNAP_OFF, KNF_MODEL_IGNORE_SNAP_ON, knife_add_cut(), knife_finish_cut(), knife_recalc_projmat(), knife_start_cut(), knife_update_active(), knife_update_header(), knifetool_exit(), knifetool_finish(), knifetool_update_mval(), MIDDLEMOUSE, KnifeTool_OpData::mode, MOUSEMOVE, wmEvent::mval, NULL, OB_MESH, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, KnifeTool_OpData::prevmode, KnifeTool_OpData::snap_midpoints, wmEvent::type, Object::type, wmEvent::val, view3d_operator_needs_opengl(), WHEELDOWNMOUSE, and WHEELUPMOUSE.
Referenced by MESH_OT_knife_tool().
wmKeyMap* knifetool_modal_keymap (wmKeyConfig * keyconf) [read]
Definition at line 2891 of file editmesh_knife.c.
References CKEY, EKEY, ESCKEY, KM_ANY, KM_PRESS, KM_RELEASE, KNF_MODAL_ADD_CUT, KNF_MODAL_ANGLE_SNAP_TOGGLE, KNF_MODAL_CANCEL, KNF_MODAL_CONFIRM, KNF_MODAL_CUT_THROUGH_TOGGLE, KNF_MODAL_MIDPOINT_OFF, KNF_MODAL_MIDPOINT_ON, KNF_MODAL_NEW_CUT, KNF_MODEL_IGNORE_SNAP_OFF, KNF_MODEL_IGNORE_SNAP_ON, LEFTCTRLKEY, LEFTMOUSE, LEFTSHIFTKEY, wmKeyMap::modal_items, NULL, PADENTER, RETKEY, RIGHTCTRLKEY, RIGHTMOUSE, RIGHTSHIFTKEY, SPACEKEY, WM_modalkeymap_add(), WM_modalkeymap_add_item(), WM_modalkeymap_assign(), WM_modalkeymap_get(), and ZKEY.
Referenced by ED_keymap_mesh().
static void knifetool_update_mval (KnifeTool_OpData * kcd, int mval[2]) [static]
Definition at line 2767 of file editmesh_knife.c.
References KnifeTool_OpData::ar, ED_region_tag_redraw(), knife_recalc_projmat(), knife_update_active(), ViewContext::mval, and KnifeTool_OpData::vc.
Referenced by knifetool_invoke(), and knifetool_modal().
static float len_v3_tri_side_max (const float v1[3], const float v2[3], const float v3[3]) [static]
Definition at line 1053 of file editmesh_knife.c.
References len_v3v3(), and MAX3().
Referenced by knife_edge_tri_isect().
void MESH_OT_knife_tool (wmOperatorType * ot)
Definition at line 3071 of file editmesh_knife.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_editmesh_view3d(), FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, knifetool_cancel(), knifetool_invoke(), knifetool_modal(), wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
static KnifeEdge* new_knife_edge (KnifeTool_OpData * kcd) [static]
Definition at line 268 of file editmesh_knife.c.
References BLI_mempool_calloc(), KnifeTool_OpData::kedges, and KnifeTool_OpData::totkedge.
Referenced by find_hole_chains(), get_bm_knife_edge(), knife_add_single_cut(), knife_add_single_cut_through(), and knife_split_edge().
static KnifeVert* new_knife_vert (KnifeTool_OpData * kcd, float * co, float * cageco) [static]
Definition at line 280 of file editmesh_knife.c.
References BLI_mempool_calloc(), KnifeVert::cageco, KnifeVert::co, copy_v3_v3(), knife_project_v3(), KnifeTool_OpData::kverts, KnifeVert::sco, and KnifeTool_OpData::totkvert.
Referenced by get_bm_knife_vert(), knife_add_single_cut(), and knife_split_edge().
static int project_knife_view_clip (View3D * v3d, RegionView3D * rv3d, float * clipsta, float * clipend) [static]
Definition at line 2691 of file editmesh_knife.c.
References ED_view3d_clip_range_get(), and orth().
Referenced by knife_recalc_projmat().
static void sort_by_frac_along (ListBase * lst, BMEdge * e) [static]
Definition at line 2025 of file editmesh_knife.c.
References BLI_insertlinkafter(), BLI_remlink(), KnifeVert::co, BMVert::co, ListBase::first, frac_along(), ListBase::last, Ref::next, next, NULL, Ref::prev, Ref::ref, BMEdge::v1, and BMEdge::v2.
Referenced by knife_make_cuts().
static int verge_linehit (const void * vlh1, const void * vlh2) [static]
Definition at line 538 of file editmesh_knife.c.
References BMEdgeHit::l.
Referenced by knife_add_cut(), and knife_cut_through().