Blender: rna_curve.c File Reference
rna_curve.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_curve_types.h"
#include "DNA_key_types.h"
#include "DNA_material_types.h"
#include "DNA_scene_types.h"
#include "BKE_font.h"
#include "WM_types.h"
#include "BKE_curve.h"
#include "ED_curve.h"
Functions
static void rna_def_bpoint (BlenderRNA *brna)
static void rna_def_beztriple (BlenderRNA *brna)
static void rna_def_path (BlenderRNA *brna, StructRNA *srna)
static void rna_def_nurbs (BlenderRNA *brna, StructRNA *srna)
static void rna_def_font (BlenderRNA *brna, StructRNA *srna)
static void rna_def_textbox (BlenderRNA *brna)
static void rna_def_charinfo (BlenderRNA *brna)
static void rna_def_surface (BlenderRNA *brna)
static void rna_def_text (BlenderRNA *brna)
static void rna_def_curve_spline_points (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_curve_spline_bezpoints (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_curve_splines (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_curve (BlenderRNA *brna)
static void rna_def_curve_nurb (BlenderRNA *brna)
void RNA_def_curve (BlenderRNA *brna)
Variables
EnumPropertyItem beztriple_handle_type_items []
EnumPropertyItem keyframe_handle_type_items []
EnumPropertyItem beztriple_interpolation_mode_items []
EnumPropertyItem curve_type_items []
static const EnumPropertyItem curve3d_fill_mode_items []
static const EnumPropertyItem curve2d_fill_mode_items []
Detailed Description
Definition in file rna_curve.c.
Function Documentation
static void rna_def_beztriple (BlenderRNA * brna) [static]
Definition at line 756 of file rna_curve.c.
References FLT_MAX, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_TRANSLATION, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and RNA_TRANSLATION_PREC_DEFAULT.
Referenced by RNA_def_curve().
static void rna_def_bpoint (BlenderRNA * brna) [static]
Definition at line 701 of file rna_curve.c.
References FLT_MAX, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, PROP_TRANSLATION, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and RNA_TRANSLATION_PREC_DEFAULT.
Referenced by RNA_def_curve().
static void rna_def_charinfo (BlenderRNA * brna) [static]
Definition at line 1094 of file rna_curve.c.
References CU_CHINFO_BOLD, CU_CHINFO_ITALIC, CU_CHINFO_SMALLCAPS, CU_CHINFO_UNDERLINE, NULL, PROP_BOOLEAN, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_curve().
static void rna_def_curve (BlenderRNA * brna) [static]
Definition at line 1253 of file rna_curve.c.
References CU_3D, CU_AUTOSPACE, CU_DEFORM_FILL, CU_FILL_CAPS, CU_HIDE_HANDLES, CU_HIDE_NORMALS, CU_TWIST_MINIMUM, CU_TWIST_TANGENT, CU_TWIST_Z_UP, CU_UV_ORCO, FLT_MAX, NC_GEOM, NC_OBJECT, ND_DATA, ND_DRAW, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_EULER, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_TRANSLATION, PROP_UNIT_LENGTH, PROP_XYZ, rna_def_animdata_common(), rna_def_curve_splines(), rna_def_path(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_editable_func(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_refine_func(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and RNA_TRANSLATION_PREC_DEFAULT.
Referenced by RNA_def_curve().
void RNA_def_curve (BlenderRNA * brna)
Definition at line 1637 of file rna_curve.c.
References rna_def_beztriple(), rna_def_bpoint(), rna_def_charinfo(), rna_def_curve(), rna_def_curve_nurb(), rna_def_surface(), rna_def_text(), and rna_def_textbox().
static void rna_def_curve_nurb (BlenderRNA * brna) [static]
Definition at line 1475 of file rna_curve.c.
References CU_NURB_BEZIER, CU_NURB_CYCLIC, CU_NURB_ENDPOINT, CU_SMOOTH, KEY_BSPLINE, KEY_CARDINAL, KEY_CU_EASE, KEY_LINEAR, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_INT, PROP_NONE, PROP_UNSIGNED, rna_def_curve_spline_bezpoints(), rna_def_curve_spline_points(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_curve().
static void rna_def_curve_spline_bezpoints (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1185 of file rna_curve.c.
References FUNC_USE_REPORTS, FUNC_USE_SELF_ID, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_curve_nurb().
static void rna_def_curve_spline_points (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1158 of file rna_curve.c.
References FUNC_USE_REPORTS, FUNC_USE_SELF_ID, NULL, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_curve_nurb().
static void rna_def_curve_splines (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1213 of file rna_curve.c.
References CU_POLY, FUNC_USE_REPORTS, NC_SCENE, ND_OB_ACTIVE, NULL, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REQUIRED, RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_curve().
static void rna_def_font (BlenderRNA * brna, StructRNA * srna) [static]
Definition at line 902 of file rna_curve.c.
References CU_FAST, CU_FLUSH, CU_JUSTIFY, CU_LEFT, CU_MIDDLE, CU_RIGHT, MAX_ID_NAME, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_text().
static void rna_def_nurbs (BlenderRNA * brna, StructRNA * srna) [static]
Definition at line 891 of file rna_curve.c.
References CU_UV_ORCO, NULL, PROP_BOOLEAN, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_surface(), and rna_def_text().
static void rna_def_path (BlenderRNA * brna, StructRNA * srna) [static]
Definition at line 842 of file rna_curve.c.
References CU_DEFORM_BOUNDS_OFF, CU_FOLLOW, CU_OFFS_PATHDIST, CU_PATH, CU_PATH_RADIUS, CU_STRETCH, MAXFRAME, NULL, PROP_BOOLEAN, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_curve().
static void rna_def_surface (BlenderRNA * brna) [static]
Definition at line 1131 of file rna_curve.c.
References rna_def_nurbs(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_curve().
static void rna_def_text (BlenderRNA * brna) [static]
Definition at line 1143 of file rna_curve.c.
References rna_def_font(), rna_def_nurbs(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_curve().
static void rna_def_textbox (BlenderRNA * brna) [static]
Definition at line 1058 of file rna_curve.c.
References NULL, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), and RNA_def_struct_ui_text().
Referenced by RNA_def_curve().
Variable Documentation
EnumPropertyItem beztriple_handle_type_items[]
Initial value:
 {
        {HD_FREE, "FREE", 0, "Free", ""},
        {HD_VECT, "VECTOR", 0, "Vector", ""},
        {HD_ALIGN, "ALIGNED", 0, "Aligned", ""},
        {HD_AUTO, "AUTO", 0, "Auto", ""},
        {0, NULL, 0, NULL, NULL}}
Definition at line 46 of file rna_curve.c.
EnumPropertyItem beztriple_interpolation_mode_items[]
Initial value:
 {
        {BEZT_IPO_CONST, "CONSTANT", 0, "Constant", ""},
        {BEZT_IPO_LIN, "LINEAR", 0, "Linear", ""},
        {BEZT_IPO_BEZ, "BEZIER", 0, "Bezier", ""},
        {0, NULL, 0, NULL, NULL}}
Definition at line 61 of file rna_curve.c.
Referenced by ACTION_OT_interpolation_type(), GRAPH_OT_interpolation_type(), rna_def_fkeyframe(), and rna_def_userdef_edit().
const EnumPropertyItem curve2d_fill_mode_items[] [static]
Initial value:
 {
    {0, "NONE", 0, "None", ""},
    {CU_BACK, "BACK", 0, "Back", ""},
    {CU_FRONT, "FRONT", 0, "Front", ""},
    {CU_FRONT|CU_BACK, "BOTH", 0, "Both", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 82 of file rna_curve.c.
const EnumPropertyItem curve3d_fill_mode_items[] [static]
Initial value:
 {
    {0, "FULL", 0, "Full", ""},
    {CU_BACK, "BACK", 0, "Back", ""},
    {CU_FRONT, "FRONT", 0, "Front", ""},
    {CU_FRONT|CU_BACK, "HALF", 0, "Half", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 75 of file rna_curve.c.
EnumPropertyItem curve_type_items[]
Initial value:
 {
    {CU_POLY, "POLY", 0, "Poly", ""},
    {CU_BEZIER, "BEZIER", 0, "Bezier", ""},
    {CU_BSPLINE, "BSPLINE", 0, "BSpline", ""},
    {CU_CARDINAL, "CARDINAL", 0, "Cardinal", ""},
    {CU_NURBS, "NURBS", 0, "Ease", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 67 of file rna_curve.c.
Referenced by RNA_api_ui_layout(), and rna_def_gpencil_layers().
EnumPropertyItem keyframe_handle_type_items[]
Initial value:
 {
        {HD_FREE, "FREE", 0, "Free", ""},
        {HD_VECT, "VECTOR", 0, "Vector", ""},
        {HD_ALIGN, "ALIGNED", 0, "Aligned", ""},
        {HD_AUTO, "AUTO", 0, "Automatic", ""},
        {HD_AUTO_ANIM, "AUTO_CLAMPED", 0, "Auto Clamped", "Auto handles clamped to not overshoot"},
        {0, NULL, 0, NULL, NULL}}
Definition at line 53 of file rna_curve.c.
Referenced by ACTION_OT_handle_type(), GRAPH_OT_handle_type(), rna_def_fkeyframe(), and rna_def_userdef_edit().