Blender: gim_pair_set Class Reference
gim_pair_set Class Reference
A pairset array.
#include <gim_box_set.h>
Public Member Functions
gim_pair_set ()
void push_pair (GUINT index1, GUINT index2)
void push_pair_inv (GUINT index1, GUINT index2)
Detailed Description
A pairset array.
Definition at line 66 of file gim_box_set.h.
Constructor & Destructor Documentation
gim_pair_set::gim_pair_set () [inline]
Definition at line 69 of file gim_box_set.h.
Member Function Documentation
void gim_pair_set::push_pair (GUINT index1, GUINT index2) [inline]
Definition at line 72 of file gim_box_set.h.
References gim_array< GIM_PAIR >::push_back().
Referenced by GIM_TREE_TREE_COLLIDER< BOX_SET_CLASS0, BOX_SET_CLASS1 >::find_collision_pairs().
void gim_pair_set::push_pair_inv (GUINT index1, GUINT index2) [inline]
Definition at line 77 of file gim_box_set.h.
References gim_array< GIM_PAIR >::push_back().
The documentation for this class was generated from the following file:
gim_box_set.h