Blender: transform_ops.c File Reference
transform_ops.c File Reference
transform
#include "MEM_guardedalloc.h"
#include "DNA_scene_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_armature.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "ED_screen.h"
#include "transform.h"
Classes
struct TransformModeItem
Typedefs
typedef struct TransformModeItem TransformModeItem
Functions
void TRANSFORM_OT_translate (struct wmOperatorType *ot)
void TRANSFORM_OT_rotate (struct wmOperatorType *ot)
void TRANSFORM_OT_tosphere (struct wmOperatorType *ot)
void TRANSFORM_OT_resize (struct wmOperatorType *ot)
void TRANSFORM_OT_shear (struct wmOperatorType *ot)
void TRANSFORM_OT_warp (struct wmOperatorType *ot)
void TRANSFORM_OT_shrink_fatten (struct wmOperatorType *ot)
void TRANSFORM_OT_push_pull (struct wmOperatorType *ot)
void TRANSFORM_OT_tilt (struct wmOperatorType *ot)
void TRANSFORM_OT_trackball (struct wmOperatorType *ot)
void TRANSFORM_OT_mirror (struct wmOperatorType *ot)
void TRANSFORM_OT_edge_slide (struct wmOperatorType *ot)
void TRANSFORM_OT_edge_crease (struct wmOperatorType *ot)
void TRANSFORM_OT_seq_slide (struct wmOperatorType *ot)
static int snap_type_exec (bContext *C, wmOperator *op)
static void TRANSFORM_OT_snap_type (wmOperatorType *ot)
static int select_orientation_exec (bContext *C, wmOperator *op)
static int select_orientation_invoke (bContext *C, wmOperator *UNUSED(op), wmEvent *UNUSED(event))
static void TRANSFORM_OT_select_orientation (struct wmOperatorType *ot)
static int delete_orientation_exec (bContext *C, wmOperator *UNUSED(op))
static int delete_orientation_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int delete_orientation_poll (bContext *C)
static void TRANSFORM_OT_delete_orientation (struct wmOperatorType *ot)
static int create_orientation_exec (bContext *C, wmOperator *op)
static int create_orientation_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static void TRANSFORM_OT_create_orientation (struct wmOperatorType *ot)
static void transformops_exit (bContext *C, wmOperator *op)
static int transformops_data (bContext *C, wmOperator *op, wmEvent *event)
static int transform_modal (bContext *C, wmOperator *op, wmEvent *event)
static int transform_cancel (bContext *C, wmOperator *op)
static int transform_exec (bContext *C, wmOperator *op)
static int transform_invoke (bContext *C, wmOperator *op, wmEvent *event)
void Transform_Properties (struct wmOperatorType *ot, int flags)
void TRANSFORM_OT_transform (struct wmOperatorType *ot)
void transform_operatortypes (void)
void transform_keymap_for_space (wmKeyConfig *keyconf, wmKeyMap *keymap, int spaceid)
Variables
static float VecOne [3] = {1, 1, 1}
static char OP_TRANSLATION [] = "TRANSFORM_OT_translate"
static char OP_ROTATION [] = "TRANSFORM_OT_rotate"
static char OP_TOSPHERE [] = "TRANSFORM_OT_tosphere"
static char OP_RESIZE [] = "TRANSFORM_OT_resize"
static char OP_SHEAR [] = "TRANSFORM_OT_shear"
static char OP_WARP [] = "TRANSFORM_OT_warp"
static char OP_SHRINK_FATTEN [] = "TRANSFORM_OT_shrink_fatten"
static char OP_PUSH_PULL [] = "TRANSFORM_OT_push_pull"
static char OP_TILT [] = "TRANSFORM_OT_tilt"
static char OP_TRACKBALL [] = "TRANSFORM_OT_trackball"
static char OP_MIRROR [] = "TRANSFORM_OT_mirror"
static char OP_EDGE_SLIDE [] = "TRANSFORM_OT_edge_slide"
static char OP_EDGE_CREASE [] = "TRANSFORM_OT_edge_crease"
static char OP_SEQ_SLIDE [] = "TRANSFORM_OT_seq_slide"
static TransformModeItem transform_modes []
EnumPropertyItem transform_mode_types []
Detailed Description
Definition in file transform_ops.c.
Typedef Documentation
typedef struct TransformModeItem TransformModeItem
Function Documentation
static int create_orientation_exec (bContext * C, wmOperator * op) [static]
Definition at line 269 of file transform_ops.c.
References BIF_createTransformOrientation(), CTX_data_scene(), CTX_wm_view3d(), MAX_NAME, NA_EDITED, NC_SCENE, NC_SPACE, ND_SPACE_VIEW3D, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_string_get(), and WM_event_add_notifier().
Referenced by create_orientation_invoke(), and TRANSFORM_OT_create_orientation().
static int create_orientation_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 285 of file transform_ops.c.
References create_orientation_exec().
Referenced by TRANSFORM_OT_create_orientation().
static int delete_orientation_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 221 of file transform_ops.c.
References BIF_removeTransformOrientationIndex(), CTX_data_scene(), CTX_wm_view3d(), NA_EDITED, NC_SCENE, NC_SPACE, ND_SPACE_VIEW3D, OPERATOR_FINISHED, View3D::twmode, V3D_MANIP_CUSTOM, and WM_event_add_notifier().
Referenced by delete_orientation_invoke(), and TRANSFORM_OT_delete_orientation().
static int delete_orientation_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 234 of file transform_ops.c.
References delete_orientation_exec().
Referenced by TRANSFORM_OT_delete_orientation().
static int delete_orientation_poll (bContext * C) [static]
Definition at line 239 of file transform_ops.c.
References CTX_wm_view3d(), ED_operator_areaactive(), View3D::twmode, and V3D_MANIP_CUSTOM.
Referenced by TRANSFORM_OT_delete_orientation().
static int select_orientation_exec (bContext * C, wmOperator * op) [static]
Definition at line 176 of file transform_ops.c.
References BIF_selectTransformOrientationValue(), CTX_wm_view3d(), NC_SPACE, ND_SPACE_VIEW3D, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), and WM_event_add_notifier().
Referenced by TRANSFORM_OT_select_orientation().
static int select_orientation_invoke (bContext * C, wmOperator * UNUSEDop, wmEvent * UNUSEDevent) [static]
Definition at line 187 of file transform_ops.c.
References OPERATOR_CANCELLED, uiItemsEnumO(), uiPupMenuBegin(), uiPupMenuEnd(), and uiPupMenuLayout().
Referenced by TRANSFORM_OT_select_orientation().
static int snap_type_exec (bContext * C, wmOperator * op) [static]
Definition at line 144 of file transform_ops.c.
References CTX_data_tool_settings(), NC_SCENE, ND_TOOLSETTINGS, NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), ToolSettings::snap_mode, and WM_event_add_notifier().
Referenced by TRANSFORM_OT_snap_type().
static int transform_cancel (bContext * C, wmOperator * op) [static]
Definition at line 388 of file transform_ops.c.
References wmOperator::customdata, OPERATOR_CANCELLED, TransInfo::state, TRANS_CANCEL, transformEnd(), and transformops_exit().
Referenced by TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), and TRANSFORM_OT_warp().
static int transform_exec (bContext * C, wmOperator * op) [static]
Definition at line 399 of file transform_ops.c.
References CTX_AUTOCONFIRM, wmOperator::customdata, G, NC_OBJECT, ND_TRANSFORM, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, TransInfo::options, transformApply(), transformEnd(), transformops_data(), transformops_exit(), and WM_event_add_notifier().
Referenced by transform_invoke(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), and TRANSFORM_OT_warp().
static int transform_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 424 of file transform_ops.c.
References wmOperator::flag, G, OP_GRAB_POINTER, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_struct_property_is_set(), transform_exec(), transformops_data(), and WM_event_add_modal_handler().
Referenced by TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), and TRANSFORM_OT_warp().
void transform_keymap_for_space (wmKeyConfig * keyconf, wmKeyMap * keymap, int spaceid)
Definition at line 844 of file transform_ops.c.
References DKEY, EKEY, EVT_TWEAK_A, EVT_TWEAK_S, GKEY, TransformModeItem::idname, KM_ALT, KM_ANY, KM_CTRL, KM_PRESS, KM_SHIFT, MKEY, OP_MIRROR, OP_RESIZE, OP_ROTATION, OP_SEQ_SLIDE, OP_SHEAR, OP_TOSPHERE, OP_TRANSLATION, OP_WARP, wmKeyMapItem::ptr, RKEY, RNA_boolean_set(), RNA_enum_set(), RNA_string_set(), SKEY, SPACE_ACTION, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_SEQ, SPACE_VIEW3D, SPACEKEY, TABKEY, TFM_TIME_EXTEND, TFM_TIME_SCALE, TFM_TIME_SLIDE, TFM_TIME_TRANSLATE, TFM_TRANSLATION, TKEY, transform_modal_keymap(), TRUE, WKEY, WM_keymap_add_item(), and WM_modalkeymap_assign().
Referenced by action_keymap_keyframes(), clip_keymap(), ED_keymap_uvedit(), graphedit_keymap_keyframes(), nla_keymap_main(), node_keymap(), sequencer_keymap(), and view3d_keymap().
static int transform_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 355 of file transform_ops.c.
References C, TransInfo::context, wmOperator::customdata, NDOF_MOTION, NULL, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, transformApply(), transformEnd(), transformEvent(), transformops_exit(), and wmEvent::type.
Referenced by TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), and TRANSFORM_OT_warp().
void transform_operatortypes (void)
Definition at line 826 of file transform_ops.c.
References TransformModeItem::idname, TransformModeItem::opfunc, TRANSFORM_OT_create_orientation(), TRANSFORM_OT_delete_orientation(), TRANSFORM_OT_select_orientation(), TRANSFORM_OT_snap_type(), TRANSFORM_OT_transform(), and WM_operatortype_append().
Referenced by view3d_operatortypes().
static void TRANSFORM_OT_create_orientation (struct wmOperatorType * ot) [static]
Definition at line 290 of file transform_ops.c.
References create_orientation_exec(), create_orientation_invoke(), wmOperatorType::description, ED_operator_areaactive(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MAX_NAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_string(), and wmOperatorType::srna.
Referenced by transform_operatortypes().
static void TRANSFORM_OT_delete_orientation (struct wmOperatorType * ot) [static]
Definition at line 255 of file transform_ops.c.
References delete_orientation_exec(), delete_orientation_invoke(), delete_orientation_poll(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by transform_operatortypes().
void TRANSFORM_OT_edge_crease (struct wmOperatorType * ot)
Definition at line 761 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_editmesh(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OP_EDGE_CREASE, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_SNAP, wmOperatorType::poll, RNA_def_float_factor(), wmOperatorType::srna, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), and Transform_Properties().
void TRANSFORM_OT_edge_slide (struct wmOperatorType * ot)
Definition at line 741 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_editmesh(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OP_EDGE_SLIDE, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_CORRECT_UV, P_MIRROR, P_SNAP, wmOperatorType::poll, RNA_def_float_factor(), wmOperatorType::srna, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), and Transform_Properties().
void TRANSFORM_OT_mirror (struct wmOperatorType * ot)
Definition at line 723 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OP_MIRROR, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_CONSTRAINT, P_PROPORTIONAL, wmOperatorType::poll, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), and Transform_Properties().
void TRANSFORM_OT_push_pull (struct wmOperatorType * ot)
Definition at line 662 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OP_PUSH_PULL, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_MIRROR, P_PROPORTIONAL, P_SNAP, wmOperatorType::poll, RNA_def_float(), wmOperatorType::srna, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), and Transform_Properties().
void TRANSFORM_OT_resize (struct wmOperatorType * ot)
Definition at line 536 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OP_RESIZE, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_CONSTRAINT, P_GEO_SNAP, P_MIRROR, P_OPTIONS, P_PROPORTIONAL, wmOperatorType::poll, RNA_def_float_vector(), wmOperatorType::srna, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), Transform_Properties(), and VecOne.
void TRANSFORM_OT_rotate (struct wmOperatorType * ot)
Definition at line 577 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, M_PI, wmOperatorType::modal, wmOperatorType::name, NULL, OP_ROTATION, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_AXIS, P_CONSTRAINT, P_GEO_SNAP, P_MIRROR, P_PROPORTIONAL, wmOperatorType::poll, RNA_def_float_rotation(), wmOperatorType::srna, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), and Transform_Properties().
static void TRANSFORM_OT_select_orientation (struct wmOperatorType * ot) [static]
Definition at line 200 of file transform_ops.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, PROP_ENUM, PROP_NONE, RNA_def_enum_funcs(), RNA_def_property(), RNA_def_property_ui_text(), rna_TransformOrientation_itemf(), select_orientation_exec(), select_orientation_invoke(), and wmOperatorType::srna.
Referenced by transform_operatortypes().
void TRANSFORM_OT_seq_slide (struct wmOperatorType * ot)
Definition at line 781 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_sequencer_active(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OP_SEQ_SLIDE, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_SNAP, wmOperatorType::poll, RNA_def_float_vector(), wmOperatorType::srna, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), Transform_Properties(), and VecOne.
void TRANSFORM_OT_shear (struct wmOperatorType * ot)
Definition at line 641 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OP_SHEAR, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_MIRROR, P_PROPORTIONAL, P_SNAP, wmOperatorType::poll, RNA_def_float(), wmOperatorType::srna, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), and Transform_Properties().
void TRANSFORM_OT_shrink_fatten (struct wmOperatorType * ot)
Definition at line 682 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_editmesh(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OP_SHRINK_FATTEN, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_MIRROR, P_PROPORTIONAL, P_SNAP, wmOperatorType::poll, RNA_def_float(), wmOperatorType::srna, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), and Transform_Properties().
static void TRANSFORM_OT_snap_type (wmOperatorType * ot) [static]
Definition at line 155 of file transform_ops.c.
References wmOperatorType::description, ED_operator_areaactive(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), snap_element_items, snap_type_exec(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by transform_operatortypes().
void TRANSFORM_OT_tilt (struct wmOperatorType * ot)
Definition at line 597 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_editcurve_3d(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, M_PI, wmOperatorType::modal, wmOperatorType::name, NULL, OP_TILT, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_CONSTRAINT, P_MIRROR, P_PROPORTIONAL, P_SNAP, wmOperatorType::poll, RNA_def_float_rotation(), wmOperatorType::srna, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), and Transform_Properties().
void TRANSFORM_OT_tosphere (struct wmOperatorType * ot)
Definition at line 702 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OP_TOSPHERE, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_MIRROR, P_PROPORTIONAL, P_SNAP, wmOperatorType::poll, RNA_def_float_factor(), wmOperatorType::srna, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), and Transform_Properties().
void TRANSFORM_OT_trackball (struct wmOperatorType * ot)
Definition at line 557 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OP_TRACKBALL, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_MIRROR, P_PROPORTIONAL, P_SNAP, wmOperatorType::poll, RNA_def_float_vector(), wmOperatorType::srna, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), Transform_Properties(), and VecOne.
void TRANSFORM_OT_transform (struct wmOperatorType * ot)
Definition at line 801 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_ALIGN_SNAP, P_AXIS, P_CONSTRAINT, P_MIRROR, P_PROPORTIONAL, wmOperatorType::poll, PROP_HIDDEN, RNA_def_enum(), RNA_def_float_vector(), RNA_def_property_flag(), wmOperatorType::srna, TFM_TRANSLATION, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), and Transform_Properties().
Referenced by transform_operatortypes().
void TRANSFORM_OT_translate (struct wmOperatorType * ot)
Definition at line 516 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OP_TRANSLATION, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_ALIGN_SNAP, P_CONSTRAINT, P_MIRROR, P_OPTIONS, P_PROPORTIONAL, wmOperatorType::poll, RNA_def_float_vector_xyz(), wmOperatorType::srna, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), and Transform_Properties().
void TRANSFORM_OT_warp (struct wmOperatorType * ot)
Definition at line 620 of file transform_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, M_PI, wmOperatorType::modal, wmOperatorType::name, NULL, OP_WARP, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, P_MIRROR, P_PROPORTIONAL, P_SNAP, wmOperatorType::poll, RNA_def_float_rotation(), wmOperatorType::srna, transform_cancel(), transform_exec(), transform_invoke(), transform_modal(), and Transform_Properties().
void Transform_Properties (struct wmOperatorType * ot, int flags)
Definition at line 444 of file transform_ops.c.
References FLT_MAX, NULL, P_ALIGN_SNAP, P_AXIS, P_CONSTRAINT, P_CORRECT_UV, P_GEO_SNAP, P_MIRROR, P_OPTIONS, P_PROPORTIONAL, P_SNAP, PROP_DIRECTION, PROP_ENUM, PROP_FLOAT, PROP_HIDDEN, PROP_NONE, proportional_editing_items, proportional_falloff_items, RNA_def_boolean(), RNA_def_boolean_vector(), RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_float(), RNA_def_float_vector(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_flag(), RNA_def_property_ui_text(), rna_TransformOrientation_itemf(), snap_target_items, and wmOperatorType::srna.
Referenced by MESH_OT_rip(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_seq_slide(), TRANSFORM_OT_shear(), TRANSFORM_OT_shrink_fatten(), TRANSFORM_OT_tilt(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), TRANSFORM_OT_warp(), and VIEW3D_OT_manipulator().
static int transformops_data (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 317 of file transform_ops.c.
References wmOperator::customdata, G, TransformModeItem::idname, wmOperatorType::idname, initTransform(), MEM_callocN(), MEM_freeN(), TransformModeItem::mode, NULL, wmOperator::ptr, RNA_enum_get(), and wmOperator::type.
Referenced by transform_exec(), and transform_invoke().
static void transformops_exit (bContext * C, wmOperator * op) [static]
Definition at line 309 of file transform_ops.c.
References wmOperator::customdata, G, MEM_freeN(), NULL, and saveTransform().
Referenced by transform_cancel(), transform_exec(), and transform_modal().
Variable Documentation
char OP_EDGE_CREASE[] = "TRANSFORM_OT_edge_crease" [static]
Definition at line 74 of file transform_ops.c.
Referenced by TRANSFORM_OT_edge_crease().
char OP_EDGE_SLIDE[] = "TRANSFORM_OT_edge_slide" [static]
Definition at line 73 of file transform_ops.c.
Referenced by TRANSFORM_OT_edge_slide().
char OP_MIRROR[] = "TRANSFORM_OT_mirror" [static]
Definition at line 72 of file transform_ops.c.
Referenced by transform_keymap_for_space(), and TRANSFORM_OT_mirror().
char OP_PUSH_PULL[] = "TRANSFORM_OT_push_pull" [static]
Definition at line 69 of file transform_ops.c.
Referenced by TRANSFORM_OT_push_pull().
char OP_RESIZE[] = "TRANSFORM_OT_resize" [static]
Definition at line 65 of file transform_ops.c.
Referenced by transform_keymap_for_space(), and TRANSFORM_OT_resize().
char OP_ROTATION[] = "TRANSFORM_OT_rotate" [static]
Definition at line 63 of file transform_ops.c.
Referenced by transform_keymap_for_space(), and TRANSFORM_OT_rotate().
char OP_SEQ_SLIDE[] = "TRANSFORM_OT_seq_slide" [static]
Definition at line 75 of file transform_ops.c.
Referenced by transform_keymap_for_space(), and TRANSFORM_OT_seq_slide().
char OP_SHEAR[] = "TRANSFORM_OT_shear" [static]
Definition at line 66 of file transform_ops.c.
Referenced by transform_keymap_for_space(), and TRANSFORM_OT_shear().
char OP_SHRINK_FATTEN[] = "TRANSFORM_OT_shrink_fatten" [static]
Definition at line 68 of file transform_ops.c.
Referenced by TRANSFORM_OT_shrink_fatten().
char OP_TILT[] = "TRANSFORM_OT_tilt" [static]
Definition at line 70 of file transform_ops.c.
Referenced by TRANSFORM_OT_tilt().
char OP_TOSPHERE[] = "TRANSFORM_OT_tosphere" [static]
Definition at line 64 of file transform_ops.c.
Referenced by transform_keymap_for_space(), and TRANSFORM_OT_tosphere().
char OP_TRACKBALL[] = "TRANSFORM_OT_trackball" [static]
Definition at line 71 of file transform_ops.c.
Referenced by TRANSFORM_OT_trackball().
char OP_TRANSLATION[] = "TRANSFORM_OT_translate" [static]
Definition at line 62 of file transform_ops.c.
Referenced by transform_keymap_for_space(), and TRANSFORM_OT_translate().
char OP_WARP[] = "TRANSFORM_OT_warp" [static]
Definition at line 67 of file transform_ops.c.
Referenced by transform_keymap_for_space(), and TRANSFORM_OT_warp().
EnumPropertyItem transform_mode_types[]
Definition at line 111 of file transform_ops.c.
Referenced by CURVE_OT_extrude(), GRAPH_OT_duplicate(), MBALL_OT_duplicate_metaelems(), NLA_OT_duplicate(), OBJECT_OT_duplicate(), and SEQUENCER_OT_duplicate().
TransformModeItem transform_modes[] [static]
Initial value:
{
    {OP_TRANSLATION, TFM_TRANSLATION, TRANSFORM_OT_translate},
    {OP_ROTATION, TFM_ROTATION, TRANSFORM_OT_rotate},
    {OP_TOSPHERE, TFM_TOSPHERE, TRANSFORM_OT_tosphere},
    {OP_RESIZE, TFM_RESIZE, TRANSFORM_OT_resize},
    {OP_SHEAR, TFM_SHEAR, TRANSFORM_OT_shear},
    {OP_WARP, TFM_WARP, TRANSFORM_OT_warp},
    {OP_SHRINK_FATTEN, TFM_SHRINKFATTEN, TRANSFORM_OT_shrink_fatten},
    {OP_PUSH_PULL, TFM_PUSHPULL, TRANSFORM_OT_push_pull},
    {OP_TILT, TFM_TILT, TRANSFORM_OT_tilt},
    {OP_TRACKBALL, TFM_TRACKBALL, TRANSFORM_OT_trackball},
    {OP_MIRROR, TFM_MIRROR, TRANSFORM_OT_mirror},
    {OP_EDGE_SLIDE, TFM_EDGE_SLIDE, TRANSFORM_OT_edge_slide},
    {OP_EDGE_CREASE, TFM_CREASE, TRANSFORM_OT_edge_crease},
    {OP_SEQ_SLIDE, TFM_SEQ_SLIDE, TRANSFORM_OT_seq_slide},
    {NULL, 0}
}
Definition at line 92 of file transform_ops.c.
float VecOne[3] = {1, 1, 1} [static]
Definition at line 60 of file transform_ops.c.
Referenced by TRANSFORM_OT_resize(), TRANSFORM_OT_seq_slide(), and TRANSFORM_OT_trackball().