Blender: space_file.c File Reference
space_file.c File Reference
fileselector
#include <string.h>
#include <stdio.h>
#include "RNA_access.h"
#include "MEM_guardedalloc.h"
#include "BIF_gl.h"
#include "BLO_readfile.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "ED_space_api.h"
#include "ED_screen.h"
#include "ED_fileselect.h"
#include "IMB_imbuf_types.h"
#include "IMB_thumbs.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "file_intern.h"
#include "fsmenu.h"
#include "filelist.h"
Functions
static SpaceLink * file_new (const bContext *UNUSED(C))
static void file_free (SpaceLink *sl)
static void file_init (struct wmWindowManager *UNUSED(wm), ScrArea *sa)
static SpaceLink * file_duplicate (SpaceLink *sl)
static void file_refresh (const bContext *C, ScrArea *UNUSED(sa))
static void file_listener (ScrArea *sa, wmNotifier *wmn)
static void file_main_area_init (wmWindowManager *wm, ARegion *ar)
static void file_main_area_listener (ARegion *ar, wmNotifier *wmn)
static void file_main_area_draw (const bContext *C, ARegion *ar)
static void file_operatortypes (void)
static void file_keymap (struct wmKeyConfig *keyconf)
static void file_channel_area_init (wmWindowManager *wm, ARegion *ar)
static void file_channel_area_draw (const bContext *C, ARegion *ar)
static void file_channel_area_listener (ARegion *UNUSED(ar), wmNotifier *wmn)
static void file_header_area_init (wmWindowManager *wm, ARegion *ar)
static void file_header_area_draw (const bContext *C, ARegion *ar)
static void file_ui_area_init (wmWindowManager *wm, ARegion *ar)
static void file_ui_area_draw (const bContext *C, ARegion *ar)
static void file_ui_area_listener (ARegion *ar, wmNotifier *wmn)
void ED_spacetype_file (void)
void ED_file_init (void)
void ED_file_exit (void)
Detailed Description
Definition in file space_file.c.
Function Documentation
void ED_file_exit (void)
Definition at line 628 of file space_file.c.
References filelist_free_icons(), fsmenu_free(), and fsmenu_get().
Referenced by WM_exit_ext().
void ED_file_init (void)
Definition at line 612 of file space_file.c.
References BLENDER_BOOKMARK_FILE, BLENDER_USER_CONFIG, BLI_get_folder(), BLI_make_file_string(), FILE_MAX, filelist_init_icons(), fsmenu_get(), fsmenu_read_bookmarks(), fsmenu_read_system(), IMB_thumb_makedirs(), and NULL.
Referenced by WM_init().
void ED_spacetype_file (void)
Definition at line 551 of file space_file.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, file_channel_area_draw(), file_channel_area_init(), file_channel_area_listener(), file_duplicate(), file_free(), file_header_area_draw(), file_header_area_init(), file_init(), file_keymap(), file_listener(), file_main_area_draw(), file_main_area_init(), file_main_area_listener(), file_new(), file_operatortypes(), file_panels_register(), file_refresh(), file_ui_area_draw(), file_ui_area_init(), file_ui_area_listener(), SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_CHANNELS, RGN_TYPE_HEADER, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_FILE, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
static void file_channel_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 471 of file space_file.c.
References ED_region_panels(), and NULL.
Referenced by ED_spacetype_file().
static void file_channel_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 460 of file space_file.c.
References wmWindowManager::defaultconf, ED_region_panels_init(), ARegion::handlers, View2D::mask, SPACE_FILE, ARegion::v2d, ARegion::winrct, WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_file().
static void file_channel_area_listener (ARegion * UNUSEDar, wmNotifier * wmn) [static]
Definition at line 476 of file space_file.c.
References wmNotifier::category.
Referenced by ED_spacetype_file().
static SpaceLink* file_duplicate (SpaceLink * sl) [static]
Definition at line 158 of file space_file.c.
References FileSelectParams::dir, filelist_new(), filelist_setdir(), SpaceFile::files, folderlist_duplicate(), SpaceFile::folders_next, SpaceFile::folders_prev, SpaceFile::layout, MEM_dupallocN(), NULL, SpaceFile::op, SpaceFile::params, and FileSelectParams::type.
Referenced by ED_spacetype_file().
static void file_free (SpaceLink * sl) [static]
Definition at line 112 of file space_file.c.
References filelist_free(), filelist_freelib(), SpaceFile::files, folderlist_free(), SpaceFile::folders_next, SpaceFile::folders_prev, SpaceFile::layout, MEM_freeN(), NULL, and SpaceFile::params.
Referenced by ED_spacetype_file().
static void file_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 495 of file space_file.c.
References ED_region_header().
Referenced by ED_spacetype_file().
static void file_header_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 485 of file space_file.c.
References wmWindowManager::defaultconf, ED_region_header_init(), ARegion::handlers, View2D::mask, SPACE_FILE, ARegion::v2d, ARegion::winrct, WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_file().
static void file_init (struct wmWindowManager * UNUSEDwm, ScrArea * sa) [static]
Definition at line 149 of file space_file.c.
References FileLayout::dirty, ListBase::first, if(), SpaceFile::layout, ScrArea::spacedata, and TRUE.
Referenced by ED_spacetype_file().
static void file_keymap (struct wmKeyConfig * keyconf) [static]
Definition at line 397 of file space_file.c.
References AKEY, BACKSPACEKEY, BKEY, DELKEY, EVT_TWEAK_L, HKEY, IKEY, KM_ALT, KM_ANY, KM_CLICK, KM_CTRL, KM_DBL_CLICK, KM_PRESS, KM_SHIFT, LEFTMOUSE, MOUSEMOVE, NKEY, PADMINUS, PADPERIOD, PADPLUSKEY, PKEY, wmKeyMapItem::ptr, RNA_boolean_set(), RNA_int_set(), SPACE_FILE, TIMER1, TRUE, WM_keymap_add_item(), WM_keymap_find(), WM_keymap_verify_item(), and XKEY.
Referenced by ED_spacetype_file().
static void file_listener (ScrArea * sa, wmNotifier * wmn) [static]
Definition at line 249 of file space_file.c.
References wmNotifier::category, wmNotifier::data, ED_area_tag_redraw(), ED_area_tag_refresh(), NC_SPACE, ND_SPACE_FILE_LIST, and ND_SPACE_FILE_PARAMS.
Referenced by ED_spacetype_file().
static void file_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 304 of file space_file.c.
References FileSelectParams::active_file, CTX_wm_space_file(), CTX_wm_window(), View2D::cur, ED_fileselect_get_layout(), ED_fileselect_get_params(), wmWindow::eventstate, file_calc_previews(), file_draw_list(), file_hilight_set(), FILE_LAYOUT_VER, file_refresh(), filelist_empty(), SpaceFile::files, FileLayout::flag, View2D::keepofs, NULL, View2D::scroll, TH_BACK, UI_GetThemeColor3fv(), UI_view2d_region_reinit(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_view_ortho(), UI_view2d_view_restore(), ARegion::v2d, V2D_ARG_DUMMY, V2D_COMMONVIEW_LIST, V2D_LOCKOFS_X, V2D_LOCKOFS_Y, V2D_SCROLL_BOTTOM, V2D_SCROLL_RIGHT, ARegion::winx, ARegion::winy, rctf::ymax, and rctf::ymin.
Referenced by ED_spacetype_file().
static void file_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 271 of file space_file.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, SPACE_FILE, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_LIST, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_file().
static void file_main_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 287 of file space_file.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NC_SPACE, ND_SPACE_FILE_LIST, and ND_SPACE_FILE_PARAMS.
Referenced by ED_spacetype_file().
static SpaceLink* file_new (const bContext * UNUSEDC) [static]
Definition at line 72 of file space_file.c.
References View2D::align, ARegion::alignment, BLI_addtail(), View2D::keeptot, View2D::keepzoom, View2D::maxzoom, MEM_callocN(), View2D::minzoom, SpaceFile::regionbase, ARegion::regiontype, RGN_ALIGN_LEFT, RGN_ALIGN_TOP, RGN_TYPE_CHANNELS, RGN_TYPE_HEADER, RGN_TYPE_UI, RGN_TYPE_WINDOW, View2D::scroll, SPACE_FILE, SpaceFile::spacetype, ARegion::v2d, V2D_ALIGN_NO_NEG_X, V2D_ALIGN_NO_POS_Y, V2D_KEEPASPECT, V2D_KEEPTOT_STRICT, V2D_LIMITZOOM, V2D_LOCKZOOM_X, V2D_LOCKZOOM_Y, V2D_SCROLL_BOTTOM, and V2D_SCROLL_RIGHT.
Referenced by ED_spacetype_file().
static void file_operatortypes (void) [static]
Definition at line 371 of file space_file.c.
References FILE_OT_bookmark_add(), FILE_OT_bookmark_toggle(), FILE_OT_cancel(), FILE_OT_delete(), FILE_OT_delete_bookmark(), FILE_OT_directory(), FILE_OT_directory_new(), FILE_OT_execute(), FILE_OT_filenum(), FILE_OT_hidedot(), FILE_OT_highlight(), FILE_OT_next(), FILE_OT_parent(), FILE_OT_previous(), FILE_OT_refresh(), FILE_OT_rename(), FILE_OT_select(), FILE_OT_select_all_toggle(), FILE_OT_select_bookmark(), FILE_OT_select_border(), FILE_OT_smoothscroll(), and WM_operatortype_append().
Referenced by ED_spacetype_file().
static void file_refresh (const bContext * C, ScrArea * UNUSEDsa) [static]
Definition at line 184 of file space_file.c.
References FileSelectParams::active_file, BLI_strncpy(), CTX_wm_space_file(), FileSelectParams::dir, FileLayout::dirty, FileSelectParams::display, ED_fileselect_get_params(), EDITING_FILE, FILE_FILTER, FILE_HIDE_DOT, FILE_IMGDISPLAY, FILE_MAX, FILE_SORT_NONE, filelist_dir(), filelist_empty(), filelist_file(), filelist_filter(), filelist_find(), filelist_hidedot(), filelist_new(), filelist_readdir(), filelist_setdir(), filelist_setfilter(), filelist_setfilter_types(), filelist_sort(), SpaceFile::files, FileSelectParams::filter, FileSelectParams::filter_glob, FileSelectParams::flag, folderlist_new(), SpaceFile::folders_prev, SpaceFile::layout, SpaceFile::params, FileSelectParams::renameedit, FileSelectParams::renamefile, direntry::selflag, FileSelectParams::sort, thumbnails_running(), thumbnails_start(), thumbnails_stop(), TRUE, and FileSelectParams::type.
Referenced by ED_spacetype_file(), and file_main_area_draw().
static void file_ui_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 515 of file space_file.c.
References View2D::cur, file_draw_buttons(), TH_PANEL, UI_GetThemeColor3fv(), UI_view2d_view_ortho(), UI_view2d_view_restore(), ARegion::v2d, rctf::ymax, and rctf::ymin.
Referenced by ED_spacetype_file().
static void file_ui_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 501 of file space_file.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, SPACE_FILE, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_HEADER, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_file().
static void file_ui_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 536 of file space_file.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NC_SPACE, and ND_SPACE_FILE_LIST.
Referenced by ED_spacetype_file().