Blender: MT_Matrix3x3.inl File Reference
MT_Matrix3x3.inl File Reference
#include "MT_Optimize.h"
Functions
GEN_INLINE MT_Vector3 operator* (const MT_Matrix3x3 &m, const MT_Vector3 &v)
GEN_INLINE MT_Vector3 operator* (const MT_Vector3 &v, const MT_Matrix3x3 &m)
GEN_INLINE MT_Matrix3x3 operator* (const MT_Matrix3x3 &m1, const MT_Matrix3x3 &m2)
GEN_INLINE MT_Matrix3x3 MT_multTransposeLeft (const MT_Matrix3x3 &m1, const MT_Matrix3x3 &m2)
GEN_INLINE MT_Matrix3x3 MT_multTransposeRight (const MT_Matrix3x3 &m1, const MT_Matrix3x3 &m2)
Function Documentation
GEN_INLINE MT_Matrix3x3 MT_multTransposeLeft (const MT_Matrix3x3 & m1, const MT_Matrix3x3 & m2)
Definition at line 109 of file MT_Matrix3x3.inl.
Referenced by MT_Transform::multInverseLeft().
GEN_INLINE MT_Matrix3x3 MT_multTransposeRight (const MT_Matrix3x3 & m1, const MT_Matrix3x3 & m2)
Definition at line 122 of file MT_Matrix3x3.inl.
References dot().
GEN_INLINE MT_Vector3 operator* (const MT_Vector3 & v, const MT_Matrix3x3 & m)
Definition at line 98 of file MT_Matrix3x3.inl.
References MT_Matrix3x3::tdot().
GEN_INLINE MT_Matrix3x3 operator* (const MT_Matrix3x3 & m1, const MT_Matrix3x3 & m2)
Definition at line 102 of file MT_Matrix3x3.inl.
References MT_Matrix3x3::tdot().
GEN_INLINE MT_Vector3 operator* (const MT_Matrix3x3 & m, const MT_Vector3 & v)
Definition at line 94 of file MT_Matrix3x3.inl.
References MT_dot().