Blender: view3d_intern.h File Reference
view3d_intern.h File Reference
3D view
#include "ED_view3d.h"
Defines
#define BL_NEAR_CLIP 0.001
#define DRAW_PICKING 1
#define DRAW_CONSTCOLOR 2
#define DRAW_SCENESET 4
#define DRAW_MODIFIERS_PREVIEW 1
#define DRAW_FACE_SELECT 2
#define V3D_CACHE_TEXT_ZBUF (1<<0)
#define V3D_CACHE_TEXT_WORLDSPACE (1<<1)
#define V3D_CACHE_TEXT_ASCII (1<<2)
#define V3D_CACHE_TEXT_GLOBALSPACE (1<<3)
#define V3D_CACHE_TEXT_LOCALCLIP (1<<4)
#define VIEW3D_CAMERA_BORDER_HACK
Functions
void VIEW3D_OT_layers (struct wmOperatorType *ot)
void view3d_operatortypes (void)
void VIEW3D_OT_zoom (struct wmOperatorType *ot)
void VIEW3D_OT_dolly (struct wmOperatorType *ot)
void VIEW3D_OT_zoom_camera_1_to_1 (struct wmOperatorType *ot)
void VIEW3D_OT_move (struct wmOperatorType *ot)
void VIEW3D_OT_rotate (struct wmOperatorType *ot)
void VIEW3D_OT_ndof_orbit (struct wmOperatorType *ot)
void VIEW3D_OT_ndof_pan (struct wmOperatorType *ot)
void VIEW3D_OT_view_all (struct wmOperatorType *ot)
void VIEW3D_OT_viewnumpad (struct wmOperatorType *ot)
void VIEW3D_OT_view_selected (struct wmOperatorType *ot)
void VIEW3D_OT_view_center_cursor (struct wmOperatorType *ot)
void VIEW3D_OT_view_center_camera (struct wmOperatorType *ot)
void VIEW3D_OT_view_pan (struct wmOperatorType *ot)
void VIEW3D_OT_view_persportho (struct wmOperatorType *ot)
void VIEW3D_OT_background_image_add (struct wmOperatorType *ot)
void VIEW3D_OT_background_image_remove (struct wmOperatorType *ot)
void VIEW3D_OT_view_orbit (struct wmOperatorType *ot)
void VIEW3D_OT_clip_border (struct wmOperatorType *ot)
void VIEW3D_OT_cursor3d (struct wmOperatorType *ot)
void VIEW3D_OT_manipulator (struct wmOperatorType *ot)
void VIEW3D_OT_enable_manipulator (struct wmOperatorType *ot)
void VIEW3D_OT_render_border (struct wmOperatorType *ot)
void VIEW3D_OT_zoom_border (struct wmOperatorType *ot)
void view3d_boxview_copy (ScrArea *sa, ARegion *ar)
void ndof_to_quat (struct wmNDOFMotionData *ndof, float q[4])
float ndof_to_axis_angle (struct wmNDOFMotionData *ndof, float axis[3])
void view3d_keymap (struct wmKeyConfig *keyconf)
void VIEW3D_OT_fly (struct wmOperatorType *ot)
void draw_motion_paths_init (View3D *v3d, struct ARegion *ar)
void draw_motion_path_instance (Scene *scene, struct Object *ob, struct bPoseChannel *pchan, struct bAnimVizSettings *avs, struct bMotionPath *mpath)
void draw_motion_paths_cleanup (View3D *v3d)
void draw_object (Scene *scene, struct ARegion *ar, View3D *v3d, Base *base, int flag)
int draw_glsl_material (Scene *scene, struct Object *ob, View3D *v3d, int dt)
void draw_object_instance (Scene *scene, View3D *v3d, RegionView3D *rv3d, struct Object *ob, int dt, int outline)
void draw_object_backbufsel (Scene *scene, View3D *v3d, RegionView3D *rv3d, struct Object *ob)
void drawaxes (float size, char drawtype)
void view3d_cached_text_draw_begin (void)
void view3d_cached_text_draw_add (const float co[3], const char *str, short xoffs, short flag, const unsigned char col[4])
void view3d_cached_text_draw_end (View3D *v3d, ARegion *ar, int depth_write, float mat[][4])
int draw_armature (Scene *scene, View3D *v3d, ARegion *ar, Base *base, int dt, int flag, const short is_outline)
void draw_mesh_textured (Scene *scene, View3D *v3d, RegionView3D *rv3d, struct Object *ob, struct DerivedMesh *dm, int faceselect)
void view3d_main_area_draw (const struct bContext *C, struct ARegion *ar)
void draw_depth (Scene *scene, struct ARegion *ar, View3D *v3d, int(*func)(void *))
void draw_depth_gpencil (Scene *scene, ARegion *ar, View3D *v3d)
void add_view3d_after (ListBase *lb, Base *base, int flag)
void circf (float x, float y, float rad)
void circ (float x, float y, float rad)
void view3d_update_depths_rect (struct ARegion *ar, struct ViewDepths *d, struct rcti *rect)
float view3d_depth_near (struct ViewDepths *d)
void VIEW3D_OT_select (struct wmOperatorType *ot)
void VIEW3D_OT_select_circle (struct wmOperatorType *ot)
void VIEW3D_OT_select_border (struct wmOperatorType *ot)
void VIEW3D_OT_select_lasso (struct wmOperatorType *ot)
void VIEW3D_OT_select_menu (struct wmOperatorType *ot)
void VIEW3D_OT_smoothview (struct wmOperatorType *ot)
void VIEW3D_OT_camera_to_view (struct wmOperatorType *ot)
void VIEW3D_OT_camera_to_view_selected (struct wmOperatorType *ot)
void VIEW3D_OT_object_as_camera (struct wmOperatorType *ot)
void VIEW3D_OT_localview (struct wmOperatorType *ot)
void VIEW3D_OT_game_start (struct wmOperatorType *ot)
int ED_view3d_boundbox_clip (RegionView3D *rv3d, float obmat[][4], struct BoundBox *bb)
void smooth_view (struct bContext *C, struct View3D *v3d, struct ARegion *ar, struct Object *, struct Object *, float *ofs, float *quat, float *dist, float *lens)
void setwinmatrixview3d (ARegion *ar, View3D *v3d, rctf *rect)
void setviewmatrixview3d (Scene *scene, View3D *v3d, RegionView3D *rv3d)
void fly_modal_keymap (struct wmKeyConfig *keyconf)
void viewrotate_modal_keymap (struct wmKeyConfig *keyconf)
void viewmove_modal_keymap (struct wmKeyConfig *keyconf)
void viewzoom_modal_keymap (struct wmKeyConfig *keyconf)
void viewdolly_modal_keymap (struct wmKeyConfig *keyconf)
void VIEW3D_OT_properties (struct wmOperatorType *ot)
void view3d_buttons_register (struct ARegionType *art)
void VIEW3D_OT_toolshelf (struct wmOperatorType *ot)
void view3d_toolshelf_register (struct ARegionType *art)
void view3d_tool_props_register (struct ARegionType *art)
int minmax_verts (struct Object *obedit, float *min, float *max)
void VIEW3D_OT_snap_selected_to_grid (struct wmOperatorType *ot)
void VIEW3D_OT_snap_selected_to_cursor (struct wmOperatorType *ot)
void VIEW3D_OT_snap_cursor_to_grid (struct wmOperatorType *ot)
void VIEW3D_OT_snap_cursor_to_center (struct wmOperatorType *ot)
void VIEW3D_OT_snap_cursor_to_selected (struct wmOperatorType *ot)
void VIEW3D_OT_snap_cursor_to_active (struct wmOperatorType *ot)
ARegion * view3d_has_buttons_region (ScrArea *sa)
ARegion * view3d_has_tools_region (ScrArea *sa)
void draw_volume (struct ARegion *ar, struct GPUTexture *tex, float *min, float *max, int res[3], float dx, struct GPUTexture *tex_shadow)
Variables
const char * view3d_context_dir []
float view3d_camera_border_hack_col [4]
short view3d_camera_border_hack_test
Detailed Description
Definition in file view3d_intern.h.
Define Documentation
#define BL_NEAR_CLIP 0.001
Definition at line 53 of file view3d_intern.h.
Referenced by apply_project_float(), project_float_noclip(), project_int(), project_int_noclip(), project_short(), project_short_noclip(), view3d_project_short_clip(), view3d_project_short_clip_persmat(), and view3d_project_short_noclip().
#define DRAW_CONSTCOLOR 2
Definition at line 57 of file view3d_intern.h.
Referenced by draw_dupli_objects_color(), draw_mesh_fancy(), draw_object(), ED_view3d_draw_offscreen(), view3d_main_area_draw_objects(), and view3d_opengl_select().
#define DRAW_FACE_SELECT 2
Definition at line 62 of file view3d_intern.h.
Referenced by draw_mesh_fancy(), draw_mesh_textured(), and draw_mesh_textured_old().
#define DRAW_MODIFIERS_PREVIEW 1
Definition at line 61 of file view3d_intern.h.
Referenced by draw_mesh_fancy(), draw_mesh_textured(), and draw_mesh_textured_old().
#define DRAW_PICKING 1
Definition at line 56 of file view3d_intern.h.
Referenced by draw_mesh_fancy(), draw_object(), draw_viewport_object_reconstruction(), draw_viewport_reconstruction(), and view3d_opengl_select().
#define DRAW_SCENESET 4
Definition at line 58 of file view3d_intern.h.
Referenced by draw_armature(), draw_object(), ED_view3d_draw_offscreen(), and view3d_main_area_draw_objects().
#define V3D_CACHE_TEXT_ASCII (1<<2)
Definition at line 124 of file view3d_intern.h.
Referenced by draw_em_indices(), draw_em_measure_stats(), draw_motion_path_instance(), draw_new_particle_system(), drawRBpivot(), and view3d_cached_text_draw_end().
#define V3D_CACHE_TEXT_GLOBALSPACE (1<<3)
Definition at line 125 of file view3d_intern.h.
Referenced by draw_viewport_object_reconstruction(), and view3d_cached_text_draw_end().
#define V3D_CACHE_TEXT_LOCALCLIP (1<<4)
Definition at line 126 of file view3d_intern.h.
Referenced by draw_em_indices(), draw_em_measure_stats(), and view3d_cached_text_draw_end().
#define V3D_CACHE_TEXT_WORLDSPACE (1<<1)
Definition at line 123 of file view3d_intern.h.
Referenced by draw_motion_path_instance(), draw_new_particle_system(), and view3d_cached_text_draw_end().
#define V3D_CACHE_TEXT_ZBUF (1<<0)
Definition at line 122 of file view3d_intern.h.
Referenced by view3d_cached_text_draw_end().
#define VIEW3D_CAMERA_BORDER_HACK
Definition at line 207 of file view3d_intern.h.
Function Documentation
void add_view3d_after (ListBase * lb, Base * base, int flag)
Definition at line 1715 of file view3d_draw.c.
References View3DAfter::base, BLI_addtail(), Base::flag, View3DAfter::flag, and MEM_callocN().
Referenced by draw_mesh_object(), draw_object(), and drawlamp().
void circ (float x, float y, float rad)
Definition at line 131 of file view3d_draw.c.
Referenced by drawcursor(), and drawlamp().
void circf (float x, float y, float rad)
Definition at line 114 of file view3d_draw.c.
int draw_armature (Scene * scene, View3D * v3d, ARegion * ar, Base * base, int dt, int flag, const short is_outline)
Definition at line 2541 of file drawarmature.c.
References ARM_EDITMODE, ARM_GHOST_CUR, ARM_GHOST_KEYS, ARM_GHOST_RANGE, ARM_LINE, ARM_POSEMODE, ARM_WIRE, bPose::chanbase, Object::data, draw_ebones(), draw_ghost_poses(), draw_ghost_poses_keys(), draw_ghost_poses_range(), draw_pose_bones(), draw_pose_paths(), DRAW_SCENESET, bArmature::drawtype, bArmature::edbo, ELEM, FALSE, ListBase::first, Base::flag, bArmature::flag, View3D::flag2, G, G_PICKSEL, bArmature::ghostep, bArmature::ghosttype, Object::mode, modifiers_isDeformedByArmature(), OB_FROMDUPLI, OB_MODE_POSE, OB_MODE_WEIGHT_PAINT, OB_NEG_SCALE, OB_WIRE, OBACT, Base::object, Object::pose, TH_WIRE, Object::transflag, UI_ThemeColor(), and V3D_RENDER_OVERRIDE.
Referenced by draw_object(), and drawObjectSelect().
void draw_depth (Scene * scene, struct ARegion * ar, View3D * v3d, int(*)(void *) func)
Definition at line 2065 of file view3d_draw.c.
References View3D::afterdraw_transp, View3D::afterdraw_xray, View3D::afterdraw_xraytransp, View3DAfter::base, Scene::base, BLI_remlink(), draw_dupli_objects(), draw_dupli_objects_color(), draw_object(), ED_view3d_clipping_disable(), ED_view3d_clipping_set(), FALSE, ListBase::first, View3D::flag, Base::flag, glLoadMatrixf, invert_m4_m4(), Base::lay, View3D::lay, MEM_freeN(), mult_m4_m4m4(), View3DAfter::next, next, Base::next, NULL, OB_DUPLI, Base::object, RegionView3D::persinv, RegionView3D::persmat, ARegion::regiondata, RegionView3D::rflag, RV3D_CLIPPING, Scene::set, SETLOOPER, setviewmatrixview3d(), setwinmatrixview3d(), TH_WIRE, Object::transflag, View3D::transp, TRUE, V3D_SELECT_OUTLINE, RegionView3D::viewinv, RegionView3D::viewmat, RegionView3D::winmat, View3D::xray, and View3D::zbuf.
Referenced by ED_view3d_autodist(), ED_view3d_autodist_init(), and view3d_zoom_border_exec().
void draw_depth_gpencil (Scene * scene, ARegion * ar, View3D * v3d)
Definition at line 2040 of file view3d_draw.c.
References draw_gpencil_view3d(), glLoadMatrixf, invert_m4_m4(), mult_m4_m4m4(), NULL, RegionView3D::persinv, RegionView3D::persmat, ARegion::regiondata, setviewmatrixview3d(), setwinmatrixview3d(), TRUE, RegionView3D::viewinv, RegionView3D::viewmat, RegionView3D::winmat, and View3D::zbuf.
Referenced by ED_view3d_autodist_init().
int draw_glsl_material (Scene * scene, struct Object * ob, View3D * v3d, int dt)
Definition at line 321 of file drawobject.c.
References check_object_draw_texture(), G, G_PICKSEL, GAME_MAT_GLSL, Scene::gm, GPU_glsl_support(), GameData::matmode, Object::mode, OB_MODE_WEIGHT_PAINT, OB_SOLID, OBACT, and scene_use_new_shading_nodes().
Referenced by draw_em_fancy(), draw_mesh_fancy(), draw_mesh_object(), draw_object_mesh_instance(), drawCurveDerivedMesh(), drawDispList(), ED_view3d_draw_offscreen(), and view3d_main_area_draw_objects().
void draw_mesh_textured (Scene * scene, View3D * v3d, RegionView3D * rv3d, struct Object * ob, struct DerivedMesh * dm, int faceselect)
Definition at line 943 of file drawmesh.c.
References Object::data, data, DM_DRAW_ALWAYS_SMOOTH, DM_DRAW_USE_COLORS, DRAW_FACE_SELECT, draw_mesh_face_select(), draw_mesh_textured_old(), DRAW_MODIFIERS_PREVIEW, DerivedMesh::drawMappedFaces, DerivedMesh::drawMappedFacesMat, View3D::drawtype, GPU_begin_object_materials(), GPU_enable_material(), GPU_end_object_materials(), GPU_glsl_support(), Object::mode, NULL, OB_MATERIAL, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, OB_NEG_SCALE, Scene::obedit, scene_use_new_shading_nodes(), tex_mat_set_face_editmesh_cb(), tex_mat_set_face_mesh_cb(), tex_mat_set_material_cb(), tex_mat_set_texture_cb(), Object::transflag, and wpaint__setSolidDrawOptions_material().
Referenced by draw_em_fancy(), and draw_mesh_fancy().
void draw_motion_path_instance (Scene * scene, struct Object * ob, struct bPoseChannel * pchan, struct bAnimVizSettings * avs, struct bMotionPath * mpath)
Definition at line 85 of file drawanimviz.c.
References AnimData::action, action_groups_find_named(), action_to_keylist(), agroup_to_keylist(), BKE_animdata_from_id(), BLI_dlrbTree_free(), BLI_dlrbTree_init(), BLI_dlrbTree_linkedlist_sync(), BLI_dlrbTree_search_exact(), bPoseChannel::bone, BONE_SELECTED, CFRA, co, bMotionPathVert::co, compare_ak_cfraPtr(), bMotionPath::end_frame, equals_v3v3(), Object::flag, Bone::flag, i, Object::id, Object::imat, invert_m4_m4(), len(), bMotionPath::length, MOTIONPATH_TYPE_ACFRA, MOTIONPATH_VIEW_FNUMS, MOTIONPATH_VIEW_KFACT, MOTIONPATH_VIEW_KFNOS, MOTIONPATH_VIEW_KFRAS, mul_v3_m4v3(), bPoseChannel::name, NULL, Object::obmat, bAnimVizSettings::path_ac, bAnimVizSettings::path_bc, bAnimVizSettings::path_step, bAnimVizSettings::path_type, bAnimVizSettings::path_viewflag, bMotionPath::points, SELECT, SET_INTENSITY, bMotionPath::start_frame, TH_BACK, TH_BONE_POSE, TH_CFRAME, TH_TEXT_HI, TH_VERTEX_SELECT, TH_WIRE, UI_GetThemeColor3ubv(), UI_ThemeColor(), UI_ThemeColorBlend(), UI_ThemeColorBlendShade(), V3D_CACHE_TEXT_ASCII, V3D_CACHE_TEXT_WORLDSPACE, and view3d_cached_text_draw_add().
Referenced by draw_object(), and draw_pose_paths().
void draw_motion_paths_cleanup (View3D * v3d)
Definition at line 312 of file drawanimviz.c.
References View3D::zbuf.
Referenced by draw_object(), and draw_pose_paths().
void draw_motion_paths_init (View3D * v3d, struct ARegion * ar)
Definition at line 71 of file drawanimviz.c.
References glLoadMatrixf, ARegion::regiondata, RegionView3D::viewmat, and View3D::zbuf.
Referenced by draw_object(), and draw_pose_paths().
void draw_object (Scene * scene, struct ARegion * ar, View3D * v3d, Base * base, int flag)
Definition at line 6371 of file drawobject.c.
References Curve::actbox, ACTIVE, add_view3d_after(), View3D::afterdraw_xray, Object::avs, BA_WAS_SEL, Scene::basact, Object::bb, Curve::bb, bglBegin(), bglEnd(), bglVertex3fv(), BKE_curframe(), BKE_font_getselection(), Object::boundtype, bObjectSolverConstraint::camera, bFollowTrackConstraint::camera, View3D::camera, Scene::camera, SmokeModifierData::coll, Object::collision_boundtype, colortab, CONSTRAINT_DRAW_PIVOT, CONSTRAINT_EXPAND, constraint_get_typeinfo(), CONSTRAINT_OBTYPE_OBJECT, CONSTRAINT_TYPE_FOLLOWTRACK, CONSTRAINT_TYPE_OBJECTSOLVER, CONSTRAINT_TYPE_RIGIDBODYJOINT, Object::constraints, constraints_clear_evalob(), constraints_make_evalob(), copy_m3_m3(), copy_v3_v3(), cpack, CU_FAST, curve_editnurbs(), Object::data, data, bConstraint::data, DESELECT, Object::disp, SmokeModifierData::domain, draw_armature(), draw_bounding_volume(), DRAW_CONSTCOLOR, draw_empty_image(), draw_forcefield(), draw_hooks(), draw_mesh_object(), draw_motion_path_instance(), draw_motion_paths_cleanup(), draw_motion_paths_init(), draw_new_particle_system(), DRAW_PICKING, draw_ptcache_edit(), DRAW_SCENESET, draw_textcurs(), draw_update_ptcache_edit(), draw_volume(), drawaxes(), drawcamera(), drawcentercircle(), drawcircball(), drawDispList(), drawlamp(), drawlattice(), drawmball(), drawnurb(), drawObjectSelect(), drawRBpivot(), drawspeaker(), drawtexspace(), View3D::drawtype, drawWireExtra(), Object::dt, Object::dtx, SmokeDomainSettings::dx, SmokeDomainSettings::dx_wt, ED_view3d_boundbox_clip(), ED_view3d_init_mats_rv3d_gl(), MetaBall::editelems, Curve::editfont, Curve::editnurb, ELEM, ELEM3, eModifierType_Smoke, Object::empty_drawsize, Object::empty_drawtype, FALSE, ListBase::first, bConstraint::flag, Curve::flag, bRigidBodyJointConstraint::flag, Base::flag, View3D::flag, Object::flag, View3D::flag2, SmokeDomainSettings::fluid, bConstraintTypeInfo::flush_constraint_targets, PartDeflect::forcefield, free_old_images(), Curve::fsize, G, G_RENDER_OGL, G_TRANSFORM_OBJ, Object::gameflag, bConstraintTypeInfo::get_constraint_targets, bConstraintTypeInfo::get_target_matrix, glLoadMatrixf, glMultMatrixf, GPU_create_smoke(), GPU_disable_material(), GPU_enable_material(), GPU_free_smoke(), TextBox::h, SelBox::h, i, Object::id, if(), Object::imat, Object::inertia, invert_m4_m4(), Object::lay, View3D::lay, SoftBody::lcom, ID::lib, Curve::linedist, Curve::lines, Curve::linewidth, SoftBody::lrot, SoftBody::lscale, makeDispListCurveTypes(), bConstraintTarget::matrix, MIN2, MOD_SMOKE_TYPE_COLL, MOD_SMOKE_VIEW_SHOWBIG, Object::mode, modifiers_findByType(), Object::mpath, mul_m3_m3m3(), ID::name, bConstraint::next, ParticleSystem::next, bConstraintTarget::next, NULL, SmokeCollSettings::numpoints, OB_ARMATURE, OB_ARROWS, OB_AXIS, OB_BOUND_SPHERE, OB_BOUNDBOX, OB_BOUNDS, OB_CAMERA, OB_CURVE, ob_draw_RE_motion(), OB_DRAWNAME, OB_DRAWTRANSP, OB_DRAWWIRE, OB_DRAWXRAY, OB_DYNAMIC, OB_EMPTY, OB_EMPTY_IMAGE, OB_FONT, OB_FROMDUPLI, OB_FROMGROUP, OB_LAMP, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_EDIT, OB_MODE_PARTICLE_EDIT, OB_MODE_POSE, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, OB_PAINT, OB_RENDER, OB_RESTRICT_RENDER, OB_RESTRICT_VIEW, OB_SOLID, OB_SPEAKER, OB_SURF, OB_TEXSPACE, OB_WIRE, OBACT, Scene::obedit, Base::object, Object::obmat, Object::orig, SmokeDomainSettings::p0, SmokeDomainSettings::p1, Object::parent, Object::particlesystem, Object::pd, PE_create_current(), RegionView3D::persp, SmokeCollSettings::points, project_short(), PTCacheEdit::psys, ARegion::regiondata, SmokeDomainSettings::res, SmokeDomainSettings::res_wt, Object::restrictflag, rgb_float_to_uchar(), RV3D_CAMOB, SBSO_ESTIMATEIPO, Curve::selboxes, SELECT, set_inverted_drawing(), setlinestyle(), smoke_get_density(), smoke_get_index(), Object::soft, SoftBody::solverflags, Base::sx, Curve::tb, SmokeDomainSettings::tex, SmokeDomainSettings::tex_shadow, EditFont::textcurs, TH_ACTIVE, TH_CAMERA, TH_EMPTY, TH_GRID, TH_GROUP, TH_GROUP_ACTIVE, TH_LAMP, TH_SELECT, TH_SPEAKER, TH_TRANSFORM, TH_WIRE, Curve::totbox, View3D::transp, bConstraint::type, Object::type, SmokeModifierData::type, bConstraintTypeInfo::type, UI_GetThemeColor3ubv(), UI_make_axis_color(), UI_ThemeColor(), UI_ThemeColorShade(), unit_m4(), ID::us, V3D_DRAW_CENTERS, V3D_HIDE_HELPLINES, V3D_RENDER_OVERRIDE, V3D_SELECT_OUTLINE, view3d_cached_text_draw_add(), view3d_cached_text_draw_begin(), view3d_cached_text_draw_end(), RegionView3D::viewmat, RegionView3D::viewmatob, SmokeDomainSettings::viewsettings, SelBox::w, TextBox::w, SmokeDomainSettings::wt, TextBox::x, SelBox::x, Curve::xof, View3D::xray, TextBox::y, SelBox::y, Curve::yof, and View3D::zbuf.
Referenced by draw_depth(), draw_dupli_objects_color(), ED_view3d_draw_offscreen(), view3d_draw_transp(), view3d_draw_xray(), view3d_draw_xraytransp(), view3d_main_area_draw_objects(), and view3d_opengl_select().
void draw_object_backbufsel (Scene * scene, View3D * v3d, RegionView3D * rv3d, struct Object * ob)
Definition at line 7318 of file drawobject.c.
References bbs_mesh_solid(), bbs_mesh_solid_EM(), bbs_mesh_solid_hide2__setDrawOpts(), bbs_mesh_verts(), bbs_mesh_wire(), bbs_obmode_mesh_verts(), bglPolygonOffset(), BMEditMesh::bm, bm_solidoffs, bm_vertoffs, bm_wireoffs, CD_MASK_BAREMESH, Scene::customdata_mask, Object::data, RegionView3D::dist, DerivedMesh::drawMappedFaces, EDBM_index_arrays_free(), EDBM_index_arrays_init(), Mesh::edit_btmesh, editbmesh_get_derived_cage(), Mesh::editflag, G, G_TRANSFORM_EDIT, glLoadMatrixf, glMultMatrixf, GPU_enable_material(), ME_EDIT_VERT_SEL, mesh_get_derived_final(), Object::mode, NULL, OB_CURVE, OB_MESH, OB_MODE_EDIT, OB_MODE_WEIGHT_PAINT, OB_SURF, Object::obmat, DerivedMesh::release, SCE_SELECT_FACE, SCE_SELECT_VERTEX, ToolSettings::selectmode, Scene::toolsettings, BMesh::totedge, BMesh::totface, BMesh::totvert, Mesh::totvert, Object::type, and RegionView3D::viewmat.
Referenced by backdrawview3d().
void draw_object_instance (Scene * scene, View3D * v3d, RegionView3D * rv3d, struct Object * ob, int dt, int outline)
Definition at line 7447 of file drawobject.c.
References draw_empty_image(), draw_object_mesh_instance(), drawaxes(), Object::empty_drawsize, Object::empty_drawtype, NULL, OB_EMPTY, OB_EMPTY_IMAGE, OB_MESH, and Object::type.
Referenced by draw_custom_bone().
void draw_volume (struct ARegion * ar, struct GPUTexture * tex, float * min, float * max, int res[3], float dx, struct GPUTexture * tex_shadow)
Definition at line 160 of file drawvolume.c.
References ABS, add_v3_v3v3(), convex(), copy_v3_v3(), dot_v3v3(), glLoadMatrixf, GPU_non_power_of_two_support(), GPU_texture_bind(), GPU_texture_unbind(), i, intersect_edges(), MEM_callocN(), MEM_freeN(), mul_v3_fl(), normalize_v3(), NULL, power_of_2_max_i(), ARegion::regiondata, size(), strlen(), sub_v3_v3v3(), tend(), tstart(), RegionView3D::viewinv, and RegionView3D::viewmat.
Referenced by draw_object().
void drawaxes (float size, char drawtype)
Definition at line 529 of file drawobject.c.
References draw_empty_cone(), draw_empty_sphere(), draw_xyz_wire(), drawcircle_size(), drawcube_size(), OB_ARROWS, OB_CIRCLE, OB_CUBE, OB_EMPTY_CONE, OB_EMPTY_SPHERE, OB_PLAINAXES, OB_SINGLE_ARROW, and size().
Referenced by draw_ebones(), draw_object(), draw_object_instance(), draw_pose_bones(), and draw_viewport_object_reconstruction().
int ED_view3d_boundbox_clip (RegionView3D * rv3d, float obmat[][4], struct BoundBox * bb)
Definition at line 814 of file view3d_view.c.
References copy_v3_v3(), BoundBox::flag, max, min, mul_m4_v4(), mult_m4_m4m4(), NULL, OB_BB_DISABLED, RegionView3D::persmat, and BoundBox::vec.
Referenced by draw_dupli_objects_color(), draw_mesh_object(), draw_object(), drawObjectSelect(), and drawWireExtra().
void fly_modal_keymap (struct wmKeyConfig * keyconf)
Definition at line 84 of file view3d_fly.c.
References AKEY, DKEY, ESCKEY, FKEY, FLY_MODAL_ACCELERATE, FLY_MODAL_AXIS_LOCK_X, FLY_MODAL_AXIS_LOCK_Z, FLY_MODAL_CANCEL, FLY_MODAL_CONFIRM, FLY_MODAL_DECELERATE, FLY_MODAL_DIR_BACKWARD, FLY_MODAL_DIR_DOWN, FLY_MODAL_DIR_FORWARD, FLY_MODAL_DIR_LEFT, FLY_MODAL_DIR_RIGHT, FLY_MODAL_DIR_UP, FLY_MODAL_FREELOOK_DISABLE, FLY_MODAL_FREELOOK_ENABLE, FLY_MODAL_PAN_DISABLE, FLY_MODAL_PAN_ENABLE, FLY_MODAL_PRECISION_DISABLE, FLY_MODAL_PRECISION_ENABLE, KM_ANY, KM_PRESS, KM_RELEASE, LEFTCTRLKEY, LEFTMOUSE, LEFTSHIFTKEY, MIDDLEMOUSE, wmKeyMap::modal_items, NULL, PADENTER, PADMINUS, PADPLUSKEY, RETKEY, RIGHTMOUSE, RKEY, SKEY, SPACEKEY, WHEELDOWNMOUSE, WHEELUPMOUSE, WKEY, WM_modalkeymap_add(), WM_modalkeymap_add_item(), WM_modalkeymap_assign(), WM_modalkeymap_get(), XKEY, and ZKEY.
Referenced by view3d_keymap().
int minmax_verts (struct Object * obedit, float * min, float * max)
Definition at line 1062 of file view3d_snap.c.
References add_v3_v3(), copy_m3_m4(), copy_v3_v3(), DO_MINMAX, ELEM5, TransVert::flag, TransVert::loc, make_trans_verts(), TransVert::maploc, MEM_freeN(), mul_m3_v3(), NULL, OB_ARMATURE, OB_CURVE, OB_LATTICE, OB_MESH, OB_SURF, Object::obmat, TM_ALL_JOINTS, tottrans, transvmain, TX_VERT_USE_MAPLOC, and Object::type.
Referenced by viewselected_exec().
float ndof_to_axis_angle (struct wmNDOFMotionData * ndof, float axis[3])
Definition at line 984 of file view3d_edit.c.
References wmNDOFMotionData::dt, normalize_v3_v3(), and wmNDOFMotionData::rvec.
Referenced by flyApply_ndof(), ndof_orbit_invoke(), and ndof_to_quat().
void ndof_to_quat (struct wmNDOFMotionData * ndof, float q[4])
Definition at line 989 of file view3d_edit.c.
References angle(), axis_angle_to_quat(), and ndof_to_axis_angle().
void setviewmatrixview3d (Scene * scene, View3D * v3d, RegionView3D * rv3d)
Definition at line 1154 of file view3d_view.c.
References View3D::camera, copy_v3_v3(), RegionView3D::dist, ED_view3d_lock(), get_pose_channel(), give_cursor(), mul_m4_v3(), OB_ARMATURE, View3D::ob_centre, View3D::ob_centre_bone, View3D::ob_centre_cursor, Object::obmat, obmat_to_viewmat(), RegionView3D::ofs, RegionView3D::persp, Object::pose, bPoseChannel::pose_mat, quat_to_mat4(), RV3D_CAMOB, RV3D_PERSP, translate_m4(), Object::type, RegionView3D::viewlock, RegionView3D::viewmat, RegionView3D::viewquat, and where_is_object().
Referenced by draw_depth(), draw_depth_gpencil(), and ED_view3d_update_viewmat().
void setwinmatrixview3d (ARegion * ar, View3D * v3d, rctf * rect)
Definition at line 1029 of file view3d_view.c.
References ED_view3d_viewplane_get(), RegionView3D::is_persp, orth(), ARegion::regiondata, RegionView3D::winmat, ARegion::winx, ARegion::winy, wmFrustum(), wmOrtho(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by draw_depth(), draw_depth_gpencil(), ED_view3d_update_viewmat(), manipulator_selectbuf(), and view3d_opengl_select().
void smooth_view (struct bContext * C, struct View3D * v3d, struct ARegion * ar, struct Object * , struct Object * , float * ofs, float * quat, float * dist, float * lens)
Definition at line 126 of file view3d_view.c.
References angle_v3v3(), copy_qt_qt(), copy_v3_v3(), CTX_wm_area(), CTX_wm_manager(), CTX_wm_window(), RegionView3D::dist, ED_region_tag_redraw(), ED_view3d_camera_lock_init(), ED_view3d_from_object(), equals_v3v3(), equals_v4v4(), FALSE, if(), invert_qt_qt(), View3D::lens, M_PI, MEM_mallocN(), mul_qt_v3(), SmoothViewStore::new_dist, SmoothViewStore::new_lens, SmoothViewStore::new_ofs, SmoothViewStore::new_quat, NULL, RegionView3D::ofs, SmoothViewStore::orig_dist, SmoothViewStore::orig_lens, SmoothViewStore::orig_ofs, SmoothViewStore::orig_quat, SmoothViewStore::orig_view, RegionView3D::persp, ARegion::regiondata, RegionView3D::rflag, RV3D_BOXVIEW, RV3D_LOCKED, RV3D_NAVIGATING, RV3D_PERSP, RV3D_VIEW_USER, RegionView3D::smooth_timer, RegionView3D::sms, SmoothViewStore::time_allowed, TIMER1, SmoothViewStore::to_camera, TRUE, RegionView3D::view, view3d_boxview_copy(), RegionView3D::viewlock, RegionView3D::viewquat, WM_event_add_timer(), and WM_event_remove_timer().
Referenced by axis_set_view(), obmat_to_viewmat(), view3d_align_axis_to_vector(), view3d_all_exec(), view3d_setobjectascamera_exec(), view3d_zoom_border_exec(), viewcenter_cursor_exec(), viewnumpad_exec(), vieworbit_exec(), and viewselected_exec().
void view3d_boxview_copy (ScrArea * sa, ARegion * ar)
Definition at line 277 of file view3d_edit.c.
References copy_v3_v3(), RegionView3D::dist, ED_region_tag_redraw(), ListBase::first, ARegion::next, RegionView3D::ofs, ScrArea::regionbase, ARegion::regiondata, ARegion::regiontype, RGN_TYPE_WINDOW, RV3D_BOXCLIP, view3d_boxview_clip(), and RegionView3D::viewlock.
Referenced by ED_view3d_quadview_update(), smooth_view(), and view3d_smoothview_invoke().
void view3d_buttons_register (struct ARegionType * art)
Definition at line 1104 of file view3d_buttons.c.
References BLI_addtail(), PanelType::draw, gpencil_panel_standard(), PanelType::idname, PanelType::label, MEM_callocN(), ARegionType::paneltypes, PanelType::poll, view3d_panel_object(), view3d_panel_vgroup(), and view3d_panel_vgroup_poll().
Referenced by ED_spacetype_view3d().
void view3d_cached_text_draw_add (const float co[3], const char * str, short xoffs, short flag, const unsigned char col[4])
Definition at line 825 of file drawobject.c.
References BLI_addtail(), CachedTextLevel, ViewCachedString::col, copy_v3_v3(), ViewCachedString::flag, MEM_callocN(), ViewCachedString::pack, ViewCachedString::str_len, strings, strlen(), ViewCachedString::vec, and ViewCachedString::xoffs.
Referenced by draw_ebones(), draw_em_indices(), draw_em_measure_stats(), draw_motion_path_instance(), draw_new_particle_system(), draw_object(), draw_pose_bones(), draw_viewport_object_reconstruction(), and drawRBpivot().
void view3d_cached_text_draw_begin (void)
Definition at line 818 of file drawobject.c.
References CachedTextLevel, ListBase::first, ListBase::last, NULL, and strings.
Referenced by draw_object().
void view3d_cached_text_draw_end (View3D * v3d, ARegion * ar, int depth_write, float mat[][4])
Definition at line 846 of file drawobject.c.
References bgl_get_mats(), BLF_draw_default(), BLF_draw_default_ascii(), BLI_freelistN(), CachedTextLevel, ViewCachedString::col, ED_region_pixelspace(), ED_view3d_clipping_disable(), ED_view3d_clipping_enable(), ListBase::first, ViewCachedString::flag, IS_CLIPPED, bglMats::modelview, mul_m4_v3(), ViewCachedString::next, ViewCachedString::pack, bglMats::projection, ARegion::regiondata, RegionView3D::rflag, RV3D_CLIPPING, ViewCachedString::sco, str, ViewCachedString::str_len, strings, ViewCachedString::ub, V3D_CACHE_TEXT_ASCII, V3D_CACHE_TEXT_GLOBALSPACE, V3D_CACHE_TEXT_LOCALCLIP, V3D_CACHE_TEXT_WORLDSPACE, V3D_CACHE_TEXT_ZBUF, ViewCachedString::vec, view3d_project_short_clip(), view3d_project_short_clip_persmat(), bglMats::viewport, ARegion::winrct, rcti::xmin, ViewCachedString::xoffs, rcti::ymin, and View3D::zbuf.
Referenced by draw_object().
float view3d_depth_near (struct ViewDepths * d)
Definition at line 2017 of file view3d_draw.c.
References ViewDepths::depth_range, ViewDepths::depths, far, FLT_MAX, ViewDepths::h, i, near, and ViewDepths::w.
Referenced by view3d_zoom_border_exec(), and view_autodist_depth_margin().
ARegion* view3d_has_buttons_region (ScrArea * sa)
Definition at line 69 of file space_view3d.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_RIGHT, RGN_FLAG_HIDDEN, RGN_TYPE_HEADER, and RGN_TYPE_UI.
Referenced by view3d_properties().
ARegion* view3d_has_tools_region (ScrArea * sa)
Definition at line 93 of file space_view3d.c.
References ARegion::alignment, BLI_insertlinkafter(), ListBase::first, ARegion::flag, MEM_callocN(), ARegion::next, NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_ALIGN_LEFT, RGN_FLAG_HIDDEN, RGN_SPLIT_PREV, RGN_TYPE_HEADER, RGN_TYPE_TOOL_PROPS, and RGN_TYPE_TOOLS.
Referenced by view3d_toolshelf().
void view3d_keymap (struct wmKeyConfig * keyconf)
Definition at line 110 of file view3d_ops.c.
References ACCENTGRAVEKEY, ACTIONMOUSE, BKEY, CKEY, COMMAKEY, EIGHTKEY, EQUALKEY, EVT_TWEAK_A, FALSE, FIVEKEY, FKEY, fly_modal_keymap(), FOURKEY, HOMEKEY, KM_ALT, KM_ANY, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTMOUSE, MIDDLEMOUSE, MINUSKEY, MOUSEPAN, MOUSEROTATE, MOUSEZOOM, NDOF_BUTTON_BACK, NDOF_BUTTON_BOTTOM, NDOF_BUTTON_FIT, NDOF_BUTTON_FRONT, NDOF_BUTTON_LEFT, NDOF_BUTTON_RIGHT, NDOF_BUTTON_TOP, NDOF_MOTION, NINEKEY, NKEY, ONEKEY, PAD0, PAD1, PAD2, PAD3, PAD4, PAD5, PAD6, PAD7, PAD8, PADENTER, PADMINUS, PADPERIOD, PADPLUSKEY, PADSLASHKEY, PERIODKEY, wmKeyMapItem::ptr, RNA_boolean_set(), RNA_enum_set(), RNA_int_set(), RNA_string_set(), RV3D_VIEW_BACK, RV3D_VIEW_BOTTOM, RV3D_VIEW_CAMERA, RV3D_VIEW_FRONT, RV3D_VIEW_LEFT, RV3D_VIEW_RIGHT, RV3D_VIEW_TOP, SELECTMOUSE, SEVENKEY, SIXKEY, SKEY, SPACE_VIEW3D, SPACEKEY, THREEKEY, TIMER1, TKEY, transform_keymap_for_space(), TRUE, TWOKEY, V3D_VIEW_PANDOWN, V3D_VIEW_PANLEFT, V3D_VIEW_PANRIGHT, V3D_VIEW_PANUP, V3D_VIEW_STEPDOWN, V3D_VIEW_STEPLEFT, V3D_VIEW_STEPRIGHT, V3D_VIEW_STEPUP, viewdolly_modal_keymap(), viewmove_modal_keymap(), viewrotate_modal_keymap(), viewzoom_modal_keymap(), WHEELDOWNMOUSE, WHEELINMOUSE, WHEELOUTMOUSE, WHEELUPMOUSE, WM_keymap_add_item(), WM_keymap_add_menu(), WM_keymap_find(), WM_keymap_verify_item(), ZEROKEY, and ZKEY.
Referenced by ED_spacetype_view3d().
void view3d_main_area_draw (const struct bContext * C, struct ARegion * ar)
void view3d_operatortypes (void)
Definition at line 58 of file view3d_ops.c.
References transform_operatortypes(), VIEW3D_OT_background_image_add(), VIEW3D_OT_background_image_remove(), VIEW3D_OT_camera_to_view(), VIEW3D_OT_camera_to_view_selected(), VIEW3D_OT_clip_border(), VIEW3D_OT_cursor3d(), VIEW3D_OT_dolly(), VIEW3D_OT_enable_manipulator(), VIEW3D_OT_fly(), VIEW3D_OT_game_start(), VIEW3D_OT_layers(), VIEW3D_OT_localview(), VIEW3D_OT_manipulator(), VIEW3D_OT_move(), VIEW3D_OT_ndof_orbit(), VIEW3D_OT_ndof_pan(), VIEW3D_OT_object_as_camera(), VIEW3D_OT_properties(), VIEW3D_OT_render_border(), VIEW3D_OT_rotate(), VIEW3D_OT_select(), VIEW3D_OT_select_border(), VIEW3D_OT_select_circle(), VIEW3D_OT_select_lasso(), VIEW3D_OT_select_menu(), VIEW3D_OT_smoothview(), VIEW3D_OT_snap_cursor_to_active(), VIEW3D_OT_snap_cursor_to_center(), VIEW3D_OT_snap_cursor_to_grid(), VIEW3D_OT_snap_cursor_to_selected(), VIEW3D_OT_snap_selected_to_cursor(), VIEW3D_OT_snap_selected_to_grid(), VIEW3D_OT_toolshelf(), VIEW3D_OT_view_all(), VIEW3D_OT_view_center_camera(), VIEW3D_OT_view_center_cursor(), VIEW3D_OT_view_orbit(), VIEW3D_OT_view_pan(), VIEW3D_OT_view_persportho(), VIEW3D_OT_view_selected(), VIEW3D_OT_viewnumpad(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), VIEW3D_OT_zoom_camera_1_to_1(), and WM_operatortype_append().
Referenced by ED_spacetype_view3d().
void VIEW3D_OT_background_image_add (struct wmOperatorType * ot)
Definition at line 3107 of file view3d_edit.c.
References background_image_add_exec(), background_image_add_invoke(), wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, FILE_MAX, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::name, wmOperatorType::poll, RNA_def_string(), and wmOperatorType::srna.
Referenced by view3d_operatortypes().
void VIEW3D_OT_background_image_remove (struct wmOperatorType * ot)
Definition at line 3146 of file view3d_edit.c.
References background_image_remove_exec(), wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by view3d_operatortypes().
void VIEW3D_OT_camera_to_view (struct wmOperatorType * ot)
Definition at line 389 of file view3d_view.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, view3d_camera_to_view_exec(), and view3d_camera_to_view_poll().
Referenced by view3d_operatortypes().
void VIEW3D_OT_camera_to_view_selected (struct wmOperatorType * ot)
Definition at line 456 of file view3d_view.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, view3d_camera_to_view_selected_exec(), and view3d_camera_to_view_selected_poll().
Referenced by view3d_operatortypes().
void VIEW3D_OT_clip_border (struct wmOperatorType * ot)
Definition at line 3244 of file view3d_edit.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_region_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, view3d_clipping_exec(), view3d_clipping_invoke(), WM_border_select_cancel(), and WM_border_select_modal().
Referenced by view3d_operatortypes().
void VIEW3D_OT_cursor3d (struct wmOperatorType * ot)
Definition at line 3338 of file view3d_edit.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and set_3dcursor_invoke().
Referenced by view3d_operatortypes().
void VIEW3D_OT_dolly (struct wmOperatorType * ot)
Definition at line 2009 of file view3d_edit.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, viewdolly_cancel(), viewdolly_exec(), viewdolly_invoke(), viewdolly_modal(), and viewdolly_poll().
Referenced by view3d_operatortypes().
void VIEW3D_OT_enable_manipulator (struct wmOperatorType * ot)
Definition at line 3415 of file view3d_edit.c.
References wmOperatorType::description, ED_operator_view3d_active(), enable_manipulator_invoke(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_boolean(), RNA_def_property_flag(), and wmOperatorType::srna.
Referenced by view3d_operatortypes().
void VIEW3D_OT_fly (struct wmOperatorType * ot)
Definition at line 1233 of file view3d_fly.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::flag, fly_cancel(), fly_invoke(), fly_modal(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, and wmOperatorType::poll.
Referenced by view3d_operatortypes().
void VIEW3D_OT_game_start (struct wmOperatorType * ot)
Definition at line 1813 of file view3d_view.c.
References wmOperatorType::description, wmOperatorType::exec, game_engine_exec(), game_engine_poll(), wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by view3d_operatortypes().
void VIEW3D_OT_layers (struct wmOperatorType * ot)
Definition at line 254 of file view3d_header.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_int(), wmOperatorType::srna, view3d_layers_exec(), view3d_layers_invoke(), and view3d_layers_poll().
Referenced by view3d_operatortypes().
void VIEW3D_OT_localview (struct wmOperatorType * ot)
Definition at line 1579 of file view3d_view.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, localview_exec(), wmOperatorType::name, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by view3d_operatortypes().
void VIEW3D_OT_manipulator (struct wmOperatorType * ot)
Definition at line 3380 of file view3d_edit.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::idname, wmOperatorType::invoke, manipulator_invoke(), wmOperatorType::name, P_CONSTRAINT, wmOperatorType::poll, and Transform_Properties().
Referenced by view3d_operatortypes().
void VIEW3D_OT_move (struct wmOperatorType * ot)
Definition at line 1391 of file view3d_edit.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, wmOperatorType::poll, viewmove_cancel(), viewmove_invoke(), and viewmove_modal().
Referenced by view3d_operatortypes().
void VIEW3D_OT_ndof_orbit (struct wmOperatorType * ot)
Definition at line 1136 of file view3d_edit.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, ndof_orbit_invoke(), and wmOperatorType::poll.
Referenced by view3d_operatortypes().
void VIEW3D_OT_ndof_pan (struct wmOperatorType * ot)
Definition at line 1230 of file view3d_edit.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, ndof_pan_invoke(), and wmOperatorType::poll.
Referenced by view3d_operatortypes().
void VIEW3D_OT_object_as_camera (struct wmOperatorType * ot)
Definition at line 509 of file view3d_view.c.
References wmOperatorType::description, ED_operator_rv3d_user_region_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and view3d_setobjectascamera_exec().
Referenced by view3d_operatortypes().
void VIEW3D_OT_properties (struct wmOperatorType * ot)
Definition at line 1139 of file view3d_buttons.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and view3d_properties().
Referenced by view3d_operatortypes().
void VIEW3D_OT_render_border (struct wmOperatorType * ot)
Definition at line 2411 of file view3d_edit.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, render_border_exec(), RNA_def_int(), wmOperatorType::srna, view3d_camera_active_poll(), WM_border_select_cancel(), WM_border_select_invoke(), and WM_border_select_modal().
Referenced by view3d_operatortypes().
void VIEW3D_OT_rotate (struct wmOperatorType * ot)
Definition at line 963 of file view3d_edit.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_region_view3d_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, wmOperatorType::poll, viewrotate_cancel(), viewrotate_invoke(), and viewrotate_modal().
Referenced by view3d_operatortypes().
void VIEW3D_OT_select (struct wmOperatorType * ot)
Definition at line 2269 of file view3d_select.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, and view3d_select_invoke().
Referenced by view3d_operatortypes().
void VIEW3D_OT_select_border (struct wmOperatorType * ot)
Definition at line 2136 of file view3d_select.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, TRUE, view3d_borderselect_exec(), view3d_selectable_data(), WM_border_select_cancel(), WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by view3d_operatortypes().
void VIEW3D_OT_select_circle (struct wmOperatorType * ot)
Definition at line 2727 of file view3d_select.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, view3d_circle_select_exec(), view3d_selectable_data(), WM_gesture_circle_cancel(), WM_gesture_circle_invoke(), and WM_gesture_circle_modal().
Referenced by view3d_operatortypes().
void VIEW3D_OT_select_lasso (struct wmOperatorType * ot)
Definition at line 998 of file view3d_select.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_collection_runtime(), RNA_OperatorMousePath, wmOperatorType::srna, view3d_lasso_select_exec(), view3d_selectable_data(), WM_gesture_lasso_cancel(), WM_gesture_lasso_invoke(), and WM_gesture_lasso_modal().
Referenced by view3d_operatortypes().
void VIEW3D_OT_select_menu (struct wmOperatorType * ot)
Definition at line 1148 of file view3d_select.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_select_menu_enum_itemf(), object_select_menu_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::prop, PROP_HIDDEN, RNA_def_boolean(), RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_property_flag(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by view3d_operatortypes().
void VIEW3D_OT_smoothview (struct wmOperatorType * ot)
Definition at line 333 of file view3d_view.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and view3d_smoothview_invoke().
Referenced by view3d_operatortypes().
void VIEW3D_OT_snap_cursor_to_active (struct wmOperatorType * ot)
Definition at line 1013 of file view3d_snap.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and snap_curs_to_active().
Referenced by view3d_operatortypes().
void VIEW3D_OT_snap_cursor_to_center (struct wmOperatorType * ot)
Definition at line 1044 of file view3d_snap.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and snap_curs_to_center().
Referenced by view3d_operatortypes().
void VIEW3D_OT_snap_cursor_to_grid (struct wmOperatorType * ot)
Definition at line 800 of file view3d_snap.c.
References wmOperatorType::description, ED_operator_region_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and snap_curs_to_grid().
Referenced by view3d_operatortypes().
void VIEW3D_OT_snap_cursor_to_selected (struct wmOperatorType * ot)
Definition at line 963 of file view3d_snap.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and snap_curs_to_sel().
Referenced by view3d_operatortypes().
void VIEW3D_OT_snap_selected_to_cursor (struct wmOperatorType * ot)
Definition at line 764 of file view3d_snap.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and snap_sel_to_curs().
Referenced by view3d_operatortypes().
void VIEW3D_OT_snap_selected_to_grid (struct wmOperatorType * ot)
Definition at line 640 of file view3d_snap.c.
References wmOperatorType::description, ED_operator_region_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and snap_sel_to_grid().
Referenced by view3d_operatortypes().
void VIEW3D_OT_toolshelf (struct wmOperatorType * ot)
Definition at line 258 of file view3d_toolbar.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and view3d_toolshelf().
Referenced by view3d_operatortypes().
void VIEW3D_OT_view_all (struct wmOperatorType * ot)
Definition at line 2118 of file view3d_edit.c.
References wmOperatorType::description, ED_operator_region_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, and view3d_all_exec().
Referenced by view3d_operatortypes().
void VIEW3D_OT_view_center_camera (struct wmOperatorType * ot)
Definition at line 2345 of file view3d_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, view3d_camera_user_poll(), and view3d_center_camera_exec().
Referenced by view3d_operatortypes().
void VIEW3D_OT_view_center_cursor (struct wmOperatorType * ot)
Definition at line 2300 of file view3d_edit.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and viewcenter_cursor_exec().
Referenced by view3d_operatortypes().
void VIEW3D_OT_view_orbit (struct wmOperatorType * ot)
Definition at line 2953 of file view3d_edit.c.
References wmOperatorType::description, ED_operator_rv3d_user_region_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, and vieworbit_exec().
Referenced by view3d_operatortypes().
void VIEW3D_OT_view_pan (struct wmOperatorType * ot)
Definition at line 3002 of file view3d_edit.c.
References wmOperatorType::description, ED_operator_region_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, and viewpan_exec().
Referenced by view3d_operatortypes().
void VIEW3D_OT_view_persportho (struct wmOperatorType * ot)
Definition at line 3039 of file view3d_edit.c.
References wmOperatorType::description, ED_operator_rv3d_user_region_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and viewpersportho_exec().
Referenced by view3d_operatortypes().
void VIEW3D_OT_view_selected (struct wmOperatorType * ot)
Definition at line 2264 of file view3d_edit.c.
References wmOperatorType::description, ED_operator_region_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and viewselected_exec().
Referenced by view3d_operatortypes().
void VIEW3D_OT_viewnumpad (struct wmOperatorType * ot)
Definition at line 2875 of file view3d_edit.c.
References wmOperatorType::description, ED_operator_rv3d_user_region_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_boolean(), RNA_def_enum(), RNA_def_property_flag(), wmOperatorType::srna, and viewnumpad_exec().
Referenced by view3d_operatortypes().
void VIEW3D_OT_zoom (struct wmOperatorType * ot)
Definition at line 1776 of file view3d_edit.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_region_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, viewzoom_cancel(), viewzoom_exec(), viewzoom_invoke(), and viewzoom_modal().
Referenced by view3d_operatortypes().
void VIEW3D_OT_zoom_border (struct wmOperatorType * ot)
Definition at line 2577 of file view3d_edit.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_region_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, view3d_zoom_border_exec(), view3d_zoom_border_invoke(), WM_border_select_cancel(), and WM_border_select_modal().
Referenced by view3d_operatortypes().
void VIEW3D_OT_zoom_camera_1_to_1 (struct wmOperatorType * ot)
Definition at line 2633 of file view3d_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, view3d_camera_user_poll(), and view3d_zoom_1_to_1_camera_exec().
Referenced by view3d_operatortypes().
void view3d_tool_props_register (struct ARegionType * art)
Definition at line 233 of file view3d_toolbar.c.
References BLI_addtail(), PanelType::draw, PanelType::draw_header, PanelType::idname, PanelType::label, MEM_callocN(), ARegionType::paneltypes, view3d_panel_operator_redo(), and view3d_panel_operator_redo_header().
Referenced by ED_spacetype_view3d().
void view3d_toolshelf_register (struct ARegionType * art)
Definition at line 222 of file view3d_toolbar.c.
References BLI_addtail(), PanelType::draw, PanelType::idname, PanelType::label, MEM_callocN(), ARegionType::paneltypes, and view3d_panel_tool_shelf().
Referenced by ED_spacetype_view3d().
void view3d_update_depths_rect (struct ARegion * ar, struct ViewDepths * d, struct rcti * rect)
Definition at line 1929 of file view3d_draw.c.
References BLI_isect_rcti(), ViewDepths::damaged, ViewDepths::depth_range, ViewDepths::depths, FALSE, ViewDepths::h, MEM_freeN(), MEM_mallocN(), NULL, TRUE, ViewDepths::w, ARegion::winrct, ARegion::winx, ARegion::winy, ViewDepths::x, rcti::xmax, rcti::xmin, ViewDepths::y, rcti::ymax, and rcti::ymin.
Referenced by view3d_zoom_border_exec(), and view_autodist_depth_margin().
void viewdolly_modal_keymap (struct wmKeyConfig * keyconf)
Definition at line 1684 of file view3d_edit.c.
References ESCKEY, KM_ANY, KM_PRESS, KM_RELEASE, LEFTCTRLKEY, LEFTMOUSE, LEFTSHIFTKEY, MIDDLEMOUSE, wmKeyMap::modal_items, NULL, VIEW_MODAL_CONFIRM, VIEWROT_MODAL_SWITCH_MOVE, VIEWROT_MODAL_SWITCH_ROTATE, WM_modalkeymap_add(), WM_modalkeymap_add_item(), WM_modalkeymap_assign(), and WM_modalkeymap_get().
Referenced by view3d_keymap().
void viewmove_modal_keymap (struct wmKeyConfig * keyconf)
Definition at line 1251 of file view3d_edit.c.
References ESCKEY, KM_ANY, KM_PRESS, KM_RELEASE, LEFTCTRLKEY, LEFTMOUSE, LEFTSHIFTKEY, MIDDLEMOUSE, wmKeyMap::modal_items, NULL, VIEW_MODAL_CONFIRM, VIEWROT_MODAL_SWITCH_ROTATE, VIEWROT_MODAL_SWITCH_ZOOM, WM_modalkeymap_add(), WM_modalkeymap_add_item(), WM_modalkeymap_assign(), and WM_modalkeymap_get().
Referenced by view3d_keymap().
void viewrotate_modal_keymap (struct wmKeyConfig * keyconf)
Definition at line 585 of file view3d_edit.c.
References ESCKEY, KM_ANY, KM_PRESS, KM_RELEASE, LEFTALTKEY, LEFTCTRLKEY, LEFTMOUSE, LEFTSHIFTKEY, MIDDLEMOUSE, wmKeyMap::modal_items, NULL, VIEW_MODAL_CONFIRM, VIEWROT_MODAL_AXIS_SNAP_DISABLE, VIEWROT_MODAL_AXIS_SNAP_ENABLE, VIEWROT_MODAL_SWITCH_MOVE, VIEWROT_MODAL_SWITCH_ZOOM, WM_modalkeymap_add(), WM_modalkeymap_add_item(), WM_modalkeymap_assign(), and WM_modalkeymap_get().
Referenced by view3d_keymap().
void viewzoom_modal_keymap (struct wmKeyConfig * keyconf)
Definition at line 1413 of file view3d_edit.c.
References ESCKEY, KM_ANY, KM_PRESS, KM_RELEASE, LEFTCTRLKEY, LEFTMOUSE, LEFTSHIFTKEY, MIDDLEMOUSE, wmKeyMap::modal_items, NULL, VIEW_MODAL_CONFIRM, VIEWROT_MODAL_SWITCH_MOVE, VIEWROT_MODAL_SWITCH_ROTATE, WM_modalkeymap_add(), WM_modalkeymap_add_item(), WM_modalkeymap_assign(), and WM_modalkeymap_get().
Referenced by view3d_keymap().
Variable Documentation
float view3d_camera_border_hack_col[4]
Definition at line 1504 of file drawobject.c.
Referenced by drawcamera(), and drawviewborder().
short view3d_camera_border_hack_test
Definition at line 1505 of file drawobject.c.
Referenced by drawcamera(), and drawviewborder().
const char* view3d_context_dir[]
Definition at line 1035 of file space_view3d.c.