Blender: btQuickprof.cpp File Reference
btQuickprof.cpp File Reference
#include "btQuickprof.h"
#include <sys/time.h>
#include <stdio.h>
Classes
struct btClockData
Defines
#define mymin(a, b) (a > b ? a : b)
Functions
void Profile_Get_Ticks (unsigned long int *ticks)
float Profile_Get_Tick_Rate (void)
Variables
static btClock gProfileClock
Define Documentation
#define mymin (a, b) (a > b ? a : b)
Definition at line 55 of file btQuickprof.cpp.
Referenced by btClock::getTimeMicroseconds(), and btClock::getTimeMilliseconds().
Function Documentation
float Profile_Get_Tick_Rate (void) [inline]
Definition at line 247 of file btQuickprof.cpp.
Referenced by CProfileManager::Get_Time_Since_Reset(), and CProfileNode::Return().
void Profile_Get_Ticks (unsigned long int * ticks) [inline]
Definition at line 242 of file btQuickprof.cpp.
References btClock::getTimeMicroseconds().
Referenced by CProfileNode::Call(), CProfileManager::Get_Time_Since_Reset(), CProfileManager::Reset(), and CProfileNode::Return().
Variable Documentation
btClock gProfileClock [static]
Definition at line 21 of file btQuickprof.cpp.