Blender: scaling.c File Reference
scaling.c File Reference
IMage Buffer
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "MEM_guardedalloc.h"
#include "imbuf.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_allocimbuf.h"
#include "IMB_filter.h"
#include "BLO_sys_types.h"
Classes
struct scale_outpix_byte
struct scale_outpix_float
struct imbufRGBA
Functions
struct ImBuf * IMB_half_x (struct ImBuf *ibuf1)
struct ImBuf * IMB_double_fast_x (struct ImBuf *ibuf1)
struct ImBuf * IMB_double_x (struct ImBuf *ibuf1)
struct ImBuf * IMB_half_y (struct ImBuf *ibuf1)
struct ImBuf * IMB_double_fast_y (struct ImBuf *ibuf1)
struct ImBuf * IMB_double_y (struct ImBuf *ibuf1)
void imb_onehalf_no_alloc (struct ImBuf *ibuf2, struct ImBuf *ibuf1)
struct ImBuf * IMB_onehalf (struct ImBuf *ibuf1)
static void enlarge_picture_byte (unsigned char *src, unsigned char *dst, int src_width, int src_height, int dst_width, int dst_height)
static void shrink_picture_byte (unsigned char *src, unsigned char *dst, int src_width, int src_height, int dst_width, int dst_height)
static void q_scale_byte (unsigned char *in, unsigned char *out, int in_width, int in_height, int dst_width, int dst_height)
static void enlarge_picture_float (float *src, float *dst, int src_width, int src_height, int dst_width, int dst_height)
static void shrink_picture_float (float *src, float *dst, int src_width, int src_height, int dst_width, int dst_height)
static void q_scale_float (float *in, float *out, int in_width, int in_height, int dst_width, int dst_height)
static int q_scale_linear_interpolation (struct ImBuf *ibuf, int newx, int newy)
static struct ImBuf * scaledownx (struct ImBuf *ibuf, int newx)
static struct ImBuf * scaledowny (struct ImBuf *ibuf, int newy)
static struct ImBuf * scaleupx (struct ImBuf *ibuf, int newx)
static struct ImBuf * scaleupy (struct ImBuf *ibuf, int newy)
static void scalefast_Z_ImBuf (ImBuf *ibuf, int newx, int newy)
struct ImBuf * IMB_scaleImBuf (struct ImBuf *ibuf, unsigned int newx, unsigned int newy)
struct ImBuf * IMB_scalefastImBuf (struct ImBuf *ibuf, unsigned int newx, unsigned int newy)
Detailed Description
Definition in file scaling.c.
Function Documentation
static void enlarge_picture_byte (unsigned char * src, unsigned char * dst, int src_width, int src_height, int dst_width, int dst_height) [static]
Definition at line 366 of file scaling.c.
References ImBuf::x.
Referenced by q_scale_byte().
static void enlarge_picture_float (float * src, float * dst, int src_width, int src_height, int dst_width, int dst_height) [static]
Definition at line 577 of file scaling.c.
Referenced by q_scale_float().
struct ImBuf* IMB_double_fast_x (struct ImBuf * ibuf1) [read]
Attention:
defined in scaling.c
Definition at line 119 of file scaling.c.
References ImBuf::flags, i, IMB_allocImBuf(), NULL, ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by double_fast_x(), and IMB_double_x().
struct ImBuf* IMB_double_fast_y (struct ImBuf * ibuf1) [read]
Attention:
defined in scaling.c
Definition at line 244 of file scaling.c.
References ImBuf::flags, IMB_allocImBuf(), NULL, ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by double_fast_y(), and IMB_double_y().
struct ImBuf* IMB_double_x (struct ImBuf * ibuf1) [read]
Attention:
defined in scaling.c
Definition at line 158 of file scaling.c.
References IMB_double_fast_x(), imb_filterx(), NULL, ImBuf::rect, and ImBuf::rect_float.
Referenced by double_x().
struct ImBuf* IMB_double_y (struct ImBuf * ibuf1) [read]
Attention:
defined in scaling.c
Definition at line 282 of file scaling.c.
References IMB_double_fast_y(), IMB_filtery(), NULL, and ImBuf::rect.
Referenced by double_y().
struct ImBuf* IMB_half_x (struct ImBuf * ibuf1) [read]
Attention:
defined in scaling.c
Definition at line 53 of file scaling.c.
References ImBuf::flags, g, IMB_allocImBuf(), IMB_dupImBuf(), NULL, ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by half_x(), and IMB_onehalf().
struct ImBuf* IMB_half_y (struct ImBuf * ibuf1) [read]
Attention:
defined in scaling.c
Definition at line 172 of file scaling.c.
References ImBuf::flags, g, IMB_allocImBuf(), IMB_dupImBuf(), NULL, ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by half_y(), and IMB_onehalf().
struct ImBuf* IMB_onehalf (struct ImBuf * ibuf1) [read]
Attention:
Defined in scaling.c
Definition at line 346 of file scaling.c.
References ImBuf::flags, IMB_allocImBuf(), IMB_half_x(), IMB_half_y(), imb_onehalf_no_alloc(), NULL, ImBuf::planes, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by IMB_makemipmap(), and onehalf().
void imb_onehalf_no_alloc (struct ImBuf * ibuf2, struct ImBuf * ibuf1)
Definition at line 296 of file scaling.c.
References imb_addrectImBuf(), NULL, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by IMB_onehalf(), and IMB_remakemipmap().
struct ImBuf* IMB_scalefastImBuf (struct ImBuf * ibuf, unsigned int newx, unsigned int newy) [read]
Attention:
Defined in scaling.c
Definition at line 1499 of file scaling.c.
References IB_rect, IB_rectfloat, imb_freerectfloatImBuf(), imb_freerectImBuf(), ImBuf::mall, MEM_freeN(), MEM_mallocN(), NULL, ImBuf::rect, ImBuf::rect_float, scalefast_Z_ImBuf(), ImBuf::x, and ImBuf::y.
Referenced by BKE_tracking_stabilize(), icon_copy_rect(), index_rebuild_fallback(), input_preprocess(), scalefastImBuf(), and seq_proxy_build_frame().
struct ImBuf* IMB_scaleImBuf (struct ImBuf * ibuf, unsigned int newx, unsigned int newy) [read]
Attention:
Defined in scaling.c
Definition at line 1470 of file scaling.c.
References NULL, q_scale_linear_interpolation(), ImBuf::rect, ImBuf::rect_float, scaledownx(), scaledowny(), scalefast_Z_ImBuf(), scaleupx(), scaleupy(), ImBuf::x, and ImBuf::y.
Referenced by blend_file_thumb(), get_undistorted_ibuf(), icon_draw_rect(), IMB_thumb_create(), input_preprocess(), movieclip_build_proxy_ibuf(), node_composit_exec_scale(), and scaleImBuf().
static void q_scale_byte (unsigned char * in, unsigned char * out, int in_width, int in_height, int dst_width, int dst_height) [static]
Definition at line 564 of file scaling.c.
References enlarge_picture_byte(), and shrink_picture_byte().
Referenced by q_scale_linear_interpolation().
static void q_scale_float (float * in, float * out, int in_width, int in_height, int dst_width, int dst_height) [static]
Definition at line 765 of file scaling.c.
References enlarge_picture_float(), and shrink_picture_float().
Referenced by q_scale_linear_interpolation().
static int q_scale_linear_interpolation (struct ImBuf * ibuf, int newx, int newy) [static]
q_scale_linear_interpolation (derived from ppmqscale, http://libdv.sf.net)
q stands for quick _and_ quality :)
only handles common cases when we either
scale both, x and y or shrink both, x and y
but that is pretty fast:
does only blit once instead of two passes like the old code (fewer cache misses)
uses fixed point integer arithmetic for byte buffers
doesn't branch in tight loops
Should be comparable in speed to the ImBuf ..._fast functions at least for byte-buffers.
NOTE: disabled, due to inacceptable inaccuracy and quality loss, see bug #18609 (ton)
Definition at line 799 of file scaling.c.
References FALSE, IB_rect, IB_rectfloat, imb_freerectfloatImBuf(), imb_freerectImBuf(), ImBuf::mall, MEM_mallocN(), q_scale_byte(), q_scale_float(), ImBuf::rect, ImBuf::rect_float, TRUE, ImBuf::x, and ImBuf::y.
Referenced by IMB_scaleImBuf().
static struct ImBuf* scaledownx (struct ImBuf * ibuf, int newx) [static, read]
Definition at line 833 of file scaling.c.
References add(), BLI_assert, IB_rect, IB_rectfloat, imb_freerectfloatImBuf(), imb_freerectImBuf(), ImBuf::mall, MEM_freeN(), MEM_mallocN(), NULL, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by IMB_scaleImBuf().
static struct ImBuf* scaledowny (struct ImBuf * ibuf, int newy) [static, read]
Definition at line 963 of file scaling.c.
References add(), BLI_assert, IB_rect, IB_rectfloat, imb_freerectfloatImBuf(), imb_freerectImBuf(), ImBuf::mall, MEM_freeN(), MEM_mallocN(), NULL, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by IMB_scaleImBuf().
static void scalefast_Z_ImBuf (ImBuf * ibuf, int newx, int newy) [static]
Definition at line 1437 of file scaling.c.
References IB_zbuf, IMB_freezbufImBuf(), ImBuf::mall, MEM_mallocN(), NULL, ImBuf::rect, ImBuf::x, ImBuf::y, and ImBuf::zbuf.
Referenced by IMB_scalefastImBuf(), and IMB_scaleImBuf().
static struct ImBuf* scaleupx (struct ImBuf * ibuf, int newx) [static, read]
Definition at line 1094 of file scaling.c.
References add(), IB_rect, IB_rectfloat, imb_freerectfloatImBuf(), imb_freerectImBuf(), ImBuf::mall, MEM_freeN(), MEM_mallocN(), NULL, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by IMB_scaleImBuf().
static struct ImBuf* scaleupy (struct ImBuf * ibuf, int newy) [static, read]
Definition at line 1261 of file scaling.c.
References add(), IB_rect, IB_rectfloat, imb_freerectfloatImBuf(), imb_freerectImBuf(), ImBuf::mall, MEM_freeN(), MEM_mallocN(), NULL, ImBuf::rect, ImBuf::rect_float, ImBuf::x, and ImBuf::y.
Referenced by IMB_scaleImBuf().
static void shrink_picture_byte (unsigned char * src, unsigned char * dst, int src_width, int src_height, int dst_width, int dst_height) [static]
Definition at line 449 of file scaling.c.
References scale_outpix_byte::a, scale_outpix_byte::b, scale_outpix_byte::g, MEM_callocN(), MEM_freeN(), NULL, scale_outpix_byte::r, and scale_outpix_byte::weight.
Referenced by q_scale_byte().
static void shrink_picture_float (float * src, float * dst, int src_width, int src_height, int dst_width, int dst_height) [static]
Definition at line 651 of file scaling.c.
References scale_outpix_float::a, scale_outpix_float::b, scale_outpix_float::g, MEM_callocN(), MEM_freeN(), scale_outpix_float::r, and scale_outpix_float::weight.
Referenced by q_scale_float().