Blender: rna_scene.c File Reference
rna_scene.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_brush_types.h"
#include "DNA_group_types.h"
#include "DNA_modifier_types.h"
#include "DNA_particle_types.h"
#include "DNA_scene_types.h"
#include "DNA_userdef_types.h"
#include "BLI_math.h"
#include "BLF_translation.h"
#include "BKE_tessmesh.h"
#include "RE_engine.h"
#include "RE_pipeline.h"
#include "ED_render.h"
#include "WM_api.h"
#include "WM_types.h"
#include "BLI_threads.h"
Defines
#define R_IMF_ENUM_BMP {R_IMF_IMTYPE_BMP, "BMP", ICON_FILE_IMAGE, "BMP", "Output image in bitmap format"},
#define R_IMF_ENUM_IRIS
#define R_IMF_ENUM_PNG {R_IMF_IMTYPE_PNG, "PNG", ICON_FILE_IMAGE, "PNG", "Output image in PNG format"},
#define R_IMF_ENUM_JPEG {R_IMF_IMTYPE_JPEG90, "JPEG", ICON_FILE_IMAGE, "JPEG", "Output image in JPEG format"},
#define R_IMF_ENUM_TAGA {R_IMF_IMTYPE_TARGA, "TARGA", ICON_FILE_IMAGE, "Targa", "Output image in Targa format"},
#define R_IMF_ENUM_TAGA_RAW
#define R_IMF_ENUM_DDS
#define R_IMF_ENUM_JPEG2K
#define R_IMF_ENUM_CINEON
#define R_IMF_ENUM_DPX
#define R_IMF_ENUM_EXR_MULTI
#define R_IMF_ENUM_EXR
#define R_IMF_ENUM_HDR
#define R_IMF_ENUM_TIFF
#define IMAGE_TYPE_ITEMS_IMAGE_ONLY
#define IMAGE_COLOR_MODE_BW image_color_mode_items[0]
#define IMAGE_COLOR_MODE_RGB image_color_mode_items[1]
#define IMAGE_COLOR_MODE_RGBA image_color_mode_items[2]
Functions
static void rna_def_transform_orientation (BlenderRNA *brna)
static void rna_def_tool_settings (BlenderRNA *brna)
static void rna_def_unified_paint_settings (BlenderRNA *brna)
static void rna_def_unit_settings (BlenderRNA *brna)
void rna_def_render_layer_common (StructRNA *srna, int scene)
static void rna_def_scene_game_recast_data (BlenderRNA *brna)
static void rna_def_scene_game_data (BlenderRNA *brna)
static void rna_def_scene_render_layer (BlenderRNA *brna)
static void rna_def_render_layers (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_scene_image_format_data (BlenderRNA *brna)
static void rna_def_scene_ffmpeg_settings (BlenderRNA *brna)
static void rna_def_scene_render_data (BlenderRNA *brna)
static void rna_def_scene_objects (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_scene_bases (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_timeline_markers (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_scene_keying_sets (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_scene_keying_sets_all (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_selected_uv_element (BlenderRNA *brna)
void RNA_def_scene (BlenderRNA *brna)
Variables
EnumPropertyItem uv_sculpt_relaxation_items []
EnumPropertyItem uv_sculpt_tool_items []
EnumPropertyItem snap_target_items []
EnumPropertyItem proportional_falloff_items []
EnumPropertyItem proportional_editing_items []
EnumPropertyItem mesh_select_mode_items []
EnumPropertyItem snap_element_items []
EnumPropertyItem image_only_type_items []
EnumPropertyItem image_type_items []
EnumPropertyItem image_color_mode_items []
EnumPropertyItem image_color_depth_items []
Detailed Description
Definition in file rna_scene.c.
Define Documentation
#define IMAGE_COLOR_MODE_BW image_color_mode_items[0]
Definition at line 247 of file rna_scene.c.
#define IMAGE_COLOR_MODE_RGB image_color_mode_items[1]
Definition at line 248 of file rna_scene.c.
#define IMAGE_COLOR_MODE_RGBA image_color_mode_items[2]
Definition at line 249 of file rna_scene.c.
#define IMAGE_TYPE_ITEMS_IMAGE_ONLY
Value:
R_IMF_ENUM_BMP                                                            \
    R_IMF_ENUM_DDS                                                            \
    R_IMF_ENUM_IRIS                                                           \
    R_IMF_ENUM_PNG                                                            \
    R_IMF_ENUM_JPEG                                                           \
    R_IMF_ENUM_JPEG2K                                                         \
    R_IMF_ENUM_TAGA                                                           \
    R_IMF_ENUM_TAGA_RAW                                                       \
    {0, "", 0, " ", NULL},                                                    \
    R_IMF_ENUM_CINEON                                                         \
    R_IMF_ENUM_DPX                                                            \
    R_IMF_ENUM_EXR_MULTI                                                      \
    R_IMF_ENUM_EXR                                                            \
    R_IMF_ENUM_HDR                                                            \
    R_IMF_ENUM_TIFF                                                           \
Definition at line 185 of file rna_scene.c.
#define R_IMF_ENUM_BMP {R_IMF_IMTYPE_BMP, "BMP", ICON_FILE_IMAGE, "BMP", "Output image in bitmap format"},
Definition at line 128 of file rna_scene.c.
#define R_IMF_ENUM_CINEON
Definition at line 156 of file rna_scene.c.
#define R_IMF_ENUM_DDS
Definition at line 141 of file rna_scene.c.
#define R_IMF_ENUM_DPX
Definition at line 157 of file rna_scene.c.
#define R_IMF_ENUM_EXR
Definition at line 168 of file rna_scene.c.
#define R_IMF_ENUM_EXR_MULTI
Definition at line 167 of file rna_scene.c.
#define R_IMF_ENUM_HDR
Definition at line 175 of file rna_scene.c.
#define R_IMF_ENUM_IRIS
Value:
{R_IMF_IMTYPE_IRIS, "IRIS", ICON_FILE_IMAGE, "Iris", \
                                                "Output image in (old!) SGI IRIS format"},
Definition at line 129 of file rna_scene.c.
#define R_IMF_ENUM_JPEG {R_IMF_IMTYPE_JPEG90, "JPEG", ICON_FILE_IMAGE, "JPEG", "Output image in JPEG format"},
Definition at line 132 of file rna_scene.c.
#define R_IMF_ENUM_JPEG2K
Definition at line 148 of file rna_scene.c.
#define R_IMF_ENUM_PNG {R_IMF_IMTYPE_PNG, "PNG", ICON_FILE_IMAGE, "PNG", "Output image in PNG format"},
Definition at line 131 of file rna_scene.c.
#define R_IMF_ENUM_TAGA {R_IMF_IMTYPE_TARGA, "TARGA", ICON_FILE_IMAGE, "Targa", "Output image in Targa format"},
Definition at line 133 of file rna_scene.c.
#define R_IMF_ENUM_TAGA_RAW
Value:
{R_IMF_IMTYPE_RAWTGA, "TARGA_RAW", ICON_FILE_IMAGE, "Targa Raw", \
                                                  "Output image in uncompressed Targa format"},
Definition at line 134 of file rna_scene.c.
#define R_IMF_ENUM_TIFF
Definition at line 181 of file rna_scene.c.
Function Documentation
void rna_def_render_layer_common (StructRNA * srna, int scene)
Definition at line 1862 of file rna_scene.c.
References NC_SCENE, ND_RENDER_OPTIONS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_LAYER, PROP_LAYER_MEMBER, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct_name_property(), SCE_LAY_ALL_Z, SCE_LAY_DISABLE, SCE_LAY_EDGE, SCE_LAY_HALO, SCE_LAY_NEG_ZMASK, SCE_LAY_SKY, SCE_LAY_SOLID, SCE_LAY_STRAND, SCE_LAY_ZMASK, SCE_LAY_ZTRA, SCE_PASS_AO, SCE_PASS_COMBINED, SCE_PASS_DIFFUSE, SCE_PASS_DIFFUSE_COLOR, SCE_PASS_DIFFUSE_DIRECT, SCE_PASS_DIFFUSE_INDIRECT, SCE_PASS_EMIT, SCE_PASS_ENVIRONMENT, SCE_PASS_GLOSSY_COLOR, SCE_PASS_GLOSSY_DIRECT, SCE_PASS_GLOSSY_INDIRECT, SCE_PASS_INDEXMA, SCE_PASS_INDEXOB, SCE_PASS_INDIRECT, SCE_PASS_MIST, SCE_PASS_NORMAL, SCE_PASS_REFLECT, SCE_PASS_REFRACT, SCE_PASS_RGBA, SCE_PASS_SHADOW, SCE_PASS_SPEC, SCE_PASS_TRANSM_COLOR, SCE_PASS_TRANSM_DIRECT, SCE_PASS_TRANSM_INDIRECT, SCE_PASS_UV, SCE_PASS_VECTOR, and SCE_PASS_Z.
Referenced by rna_def_render_layer(), and rna_def_scene_render_layer().
static void rna_def_render_layers (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 2680 of file rna_scene.c.
References FUNC_USE_MAIN, FUNC_USE_REPORTS, FUNC_USE_SELF_ID, NC_SCENE, ND_RENDER_OPTIONS, NULL, PROP_EDITABLE, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REQUIRED, PROP_UNSIGNED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_scene_render_data().
void RNA_def_scene (BlenderRNA * brna)
Definition at line 4086 of file rna_scene.c.
References AUDIO_SCRUB, AUDIO_SYNC, FLT_MAX, MAXFRAME, MINAFRAME, MINFRAME, NA_EDITED, NC_SCENE, NC_SPACE, NC_WINDOW, ND_FRAME, ND_FRAME_RANGE, ND_KEYINGSET, ND_LAYER, ND_RENDER_OPTIONS, ND_SPACE_GRAPH, ND_SPACE_VIEW3D, ND_WORLD, NULL, PHYS_GLOBAL_GRAVITY, PROP_ACCELERATION, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_INT, PROP_LAYER_MEMBER, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_TIME, PROP_XYZ_LENGTH, RNA_api_scene(), rna_def_animdata_common(), RNA_def_function(), RNA_def_function_return(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), rna_def_scene_bases(), rna_def_scene_game_data(), rna_def_scene_image_format_data(), rna_def_scene_keying_sets(), rna_def_scene_keying_sets_all(), rna_def_scene_objects(), rna_def_scene_render_data(), rna_def_scene_render_layer(), rna_def_selected_uv_element(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), rna_def_timeline_markers(), rna_def_tool_settings(), rna_def_transform_orientation(), rna_def_unified_paint_settings(), rna_def_unit_settings(), SCE_FRAME_DROP, SCE_NLA_EDIT_ON, SCER_PRV_RANGE, and STRUCT_ID_REFCOUNT.
static void rna_def_scene_bases (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 3939 of file rna_scene.c.
References NC_SCENE, ND_OB_ACTIVE, NULL, PROP_EDITABLE, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_scene().
static void rna_def_scene_ffmpeg_settings (BlenderRNA * brna) [static]
Definition at line 2857 of file rna_scene.c.
References FFMPEG_AUTOSPLIT_OUTPUT, FFMPEG_LOSSLESS_OUTPUT, NC_SCENE, ND_RENDER_OPTIONS, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_scene_render_data().
static void rna_def_scene_game_data (BlenderRNA * brna) [static]
Definition at line 2280 of file rna_scene.c.
References DOME_ENVMAP, DOME_FISHEYE, DOME_PANORAM_SPH, DOME_TRUNCATED_FRONT, DOME_TRUNCATED_REAR, event_type_items, GAME_DISPLAY_LISTS, GAME_ENABLE_ALL_FRAMES, GAME_ENABLE_ANIMATION_RECORD, GAME_GLSL_NO_COLOR_MANAGEMENT, GAME_GLSL_NO_EXTRA_TEX, GAME_GLSL_NO_LIGHTS, GAME_GLSL_NO_NODES, GAME_GLSL_NO_RAMPS, GAME_GLSL_NO_SHADERS, GAME_GLSL_NO_SHADOWS, GAME_IGNORE_DEPRECATION_WARNINGS, GAME_MAT_GLSL, GAME_MAT_MULTITEX, GAME_MAT_TEXFACE, GAME_PLAYER_DESKTOP_RESOLUTION, GAME_PLAYER_FULLSCREEN, GAME_RESTRICT_ANIM_UPDATES, GAME_SHOW_DEBUG_PROPS, GAME_SHOW_FRAMERATE, GAME_SHOW_MOUSE, GAME_SHOW_OBSTACLE_SIMULATION, GAME_SHOW_PHYSICS, NA_EDITED, NC_SCENE, NULL, OBSTSIMULATION_NONE, OBSTSIMULATION_TOI_cells, OBSTSIMULATION_TOI_rays, PROP_ACCELERATION, PROP_BOOLEAN, PROP_COLOR, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), rna_def_scene_game_recast_data(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), SCE_GAMEFRAMING_BARS, SCE_GAMEFRAMING_EXTEND, SCE_GAMEFRAMING_SCALE, STEREO_ABOVEBELOW, STEREO_ANAGLYPH, STEREO_DOME, STEREO_ENABLED, STEREO_INTERLACED, STEREO_NOSTEREO, STEREO_QUADBUFFERED, STEREO_SIDEBYSIDE, STEREO_VINTERLACE, WOPHY_BULLET, and WOPHY_NONE.
Referenced by RNA_def_scene().
static void rna_def_scene_game_recast_data (BlenderRNA * brna) [static]
Definition at line 2190 of file rna_scene.c.
References M_PI, NC_SCENE, NULL, PROP_ANGLE, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_scene_game_data().
static void rna_def_scene_image_format_data (BlenderRNA * brna) [static]
Definition at line 2729 of file rna_scene.c.
References NC_SCENE, ND_RENDER_OPTIONS, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_PERCENTAGE, R_CINEON_LOG, R_IMF_EXR_CODEC_NONE, R_IMF_EXR_CODEC_PIZ, R_IMF_EXR_CODEC_PXR24, R_IMF_EXR_CODEC_RLE, R_IMF_EXR_CODEC_ZIP, R_IMF_FLAG_PREVIEW_JPG, R_IMF_FLAG_ZBUF, R_IMF_JP2_FLAG_CINE_48, R_IMF_JP2_FLAG_CINE_PRESET, R_IMF_JP2_FLAG_YCC, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_scene().
static void rna_def_scene_keying_sets (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 3993 of file rna_scene.c.
References FUNC_USE_REPORTS, NC_SCENE, ND_KEYINGSET, NULL, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_scene().
static void rna_def_scene_keying_sets_all (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 4035 of file rna_scene.c.
References NC_SCENE, ND_KEYINGSET, NULL, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_scene().
static void rna_def_scene_objects (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 3900 of file rna_scene.c.
References FUNC_USE_CONTEXT, FUNC_USE_REPORTS, NC_SCENE, ND_OB_ACTIVE, NULL, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NEVER_UNLINK, PROP_NONE, PROP_POINTER, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_scene().
static void rna_def_scene_render_data (BlenderRNA * brna) [static]
Definition at line 3133 of file rna_scene.c.
References BLENDER_MAX_THREADS, NC_SCENE, NC_WINDOW, ND_FRAME, ND_RENDER_OPTIONS, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_COLOR, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FILEPATH, PROP_FLOAT, PROP_INT, PROP_NEVER_NULL, PROP_NEVER_UNLINK, PROP_NONE, PROP_PERCENTAGE, PROP_POINTER, PROP_STRING, PROP_UNSIGNED, R_ADDSKY, R_ALPHAKEY, R_ALPHAPREMUL, R_BAKE_CLEAR, R_BAKE_LORES_MESH, R_BAKE_MULTIRES, R_BAKE_NORMALIZE, R_BAKE_OSA, R_BAKE_SPACE_CAMERA, R_BAKE_SPACE_OBJECT, R_BAKE_SPACE_TANGENT, R_BAKE_SPACE_WORLD, R_BAKE_TO_ACTIVE, R_BORDER, R_COLOR_MANAGEMENT, R_COLOR_MANAGEMENT_PREDIVIDE, R_COMP_FREE, R_CROP, R_DOCOMP, R_DOSEQ, R_EDGE, R_ENVMAP, R_EXR_TILE_FILE, R_EXTENSION, R_FIELDS, R_FIELDSTILL, R_FILTER_BOX, R_FILTER_CATROM, R_FILTER_CUBIC, R_FILTER_GAUSS, R_FILTER_MITCH, R_FILTER_QUAD, R_FILTER_TENT, R_FIXED_THREADS, R_FREE_IMAGE, R_FULL_SAMPLE, R_MBLUR, R_NO_OVERWRITE, R_NO_TEX, R_ODDFIELD, R_OSA, R_OUTPUT_AREA, R_OUTPUT_NONE, R_OUTPUT_SCREEN, R_OUTPUT_WINDOW, R_RADIO, R_RAYSTRUCTURE_AUTO, R_RAYSTRUCTURE_BLIBVH, R_RAYSTRUCTURE_OCTREE, R_RAYSTRUCTURE_SIMD_QBVH, R_RAYSTRUCTURE_SIMD_SVBVH, R_RAYSTRUCTURE_VBVH, R_RAYTRACE, R_RAYTRACE_USE_INSTANCES, R_RAYTRACE_USE_LOCAL_COORDS, R_SEQ_GL_PREV, R_SEQ_GL_REND, R_SHADOW, R_SIMPLE_NO_TRIANGULATE, R_SIMPLIFY, R_SINGLE_LAYER, R_SSS, R_STAMP_CAMERA, R_STAMP_CAMERALENS, R_STAMP_DATE, R_STAMP_DRAW, R_STAMP_FILENAME, R_STAMP_FRAME, R_STAMP_MARKER, R_STAMP_NOTE, R_STAMP_RENDERTIME, R_STAMP_SCENE, R_STAMP_SEQSTRIP, R_STAMP_TIME, R_TOUCH, RE_BAKE_ALL, RE_BAKE_ALPHA, RE_BAKE_AO, RE_BAKE_DISPLACEMENT, RE_BAKE_EMIT, RE_BAKE_MIRROR_COLOR, RE_BAKE_MIRROR_INTENSITY, RE_BAKE_NORMALS, RE_BAKE_SHADOW, RE_BAKE_SPEC_COLOR, RE_BAKE_SPEC_INTENSITY, RE_BAKE_TEXTURE, RNA_api_scene_render(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), rna_def_render_layers(), rna_def_scene_ffmpeg_settings(), RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and viewport_shade_items.
Referenced by RNA_def_scene().
static void rna_def_scene_render_layer (BlenderRNA * brna) [static]
Definition at line 2668 of file rna_scene.c.
References NULL, rna_def_render_layer_common(), RNA_def_struct(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_scene().
static void rna_def_selected_uv_element (BlenderRNA * brna) [static]
Definition at line 4066 of file rna_scene.c.
References PROP_IDPROPERTY, PROP_INT, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_ui_text(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_scene().
static void rna_def_timeline_markers (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 3961 of file rna_scene.c.
References FUNC_USE_REPORTS, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_scene().
static void rna_def_tool_settings (BlenderRNA * brna) [static]
Definition at line 1429 of file rna_scene.c.
References ANIMRECORD_FLAG_WITHNLA, AUTOKEY_FLAG_ONLYKEYINGSET, AUTOKEY_MODE_EDITKEYS, AUTOKEY_MODE_NORMAL, AUTOKEY_ON, BONE_SKETCHING, BONE_SKETCHING_ADJUST, BONE_SKETCHING_QUICK, EDGE_MODE_SELECT, EDGE_MODE_TAG_BEVEL, EDGE_MODE_TAG_CREASE, EDGE_MODE_TAG_SEAM, EDGE_MODE_TAG_SHARP, GP_TOOL_FLAG_PAINTSESSIONS_ON, NC_GEOM, NC_SCENE, NC_SPACE, ND_DATA, ND_SPACE_IMAGE, ND_SPACE_VIEW3D, ND_TOOLSETTINGS, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_text(), SCE_SNAP, SCE_SNAP_NO_SELF, SCE_SNAP_PEEL_OBJECT, SCE_SNAP_PROJECT, SCE_SNAP_ROTATE, SK_CONVERT_CUT_ADAPTATIVE, SK_CONVERT_CUT_FIXED, SK_CONVERT_CUT_LENGTH, SK_CONVERT_RETARGET, SK_RETARGET_AUTONAME, SK_RETARGET_ROLL_JOINT, SK_RETARGET_ROLL_NONE, SK_RETARGET_ROLL_VIEW, UV_SCULPT_ALL_ISLANDS, UV_SCULPT_LOCK_BORDERS, UV_SELECT_EDGE, UV_SELECT_FACE, UV_SELECT_ISLAND, UV_SELECT_VERTEX, UV_SHOW_SAME_IMAGE, and UV_SYNC_SELECTION.
Referenced by RNA_def_scene().
static void rna_def_transform_orientation (BlenderRNA * brna) [static]
Definition at line 1409 of file rna_scene.c.
References NC_SPACE, ND_SPACE_VIEW3D, NULL, PROP_FLOAT, PROP_MATRIX, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_float_sdna(), RNA_def_property_multi_array(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), and RNA_def_struct_name_property().
Referenced by RNA_def_scene().
static void rna_def_unified_paint_settings (BlenderRNA * brna) [static]
Definition at line 1763 of file rna_scene.c.
References FLT_MAX, MAX_BRUSH_PIXEL_RADIUS, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_default(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_range(), RNA_def_property_ui_icon(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_ui_text(), UNIFIED_PAINT_ALPHA, UNIFIED_PAINT_BRUSH_ALPHA_PRESSURE, UNIFIED_PAINT_BRUSH_LOCK_SIZE, UNIFIED_PAINT_BRUSH_SIZE_PRESSURE, and UNIFIED_PAINT_SIZE.
Referenced by RNA_def_scene().
static void rna_def_unit_settings (BlenderRNA * brna) [static]
Definition at line 1820 of file rna_scene.c.
References NC_WINDOW, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_text(), USER_UNIT_IMPERIAL, USER_UNIT_METRIC, USER_UNIT_NONE, USER_UNIT_OPT_SPLIT, and USER_UNIT_ROT_RADIANS.
Referenced by RNA_def_scene().
Variable Documentation
EnumPropertyItem image_color_depth_items[]
Initial value:
 {
    {R_IMF_CHAN_DEPTH_8,   "8", 0, "8",  "8 bit color channels"},
    {R_IMF_CHAN_DEPTH_12, "12", 0, "12", "12 bit color channels"},
    {R_IMF_CHAN_DEPTH_16, "16", 0, "16", "16 bit color channels"},
    {R_IMF_CHAN_DEPTH_32, "32", 0, "32", "32 bit color channels"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 251 of file rna_scene.c.
EnumPropertyItem image_color_mode_items[]
Initial value:
 {
    {R_IMF_PLANES_BW, "BW", 0, "BW", "Images get saved in 8 bits grayscale (only PNG, JPEG, TGA, TIF)"},
    {R_IMF_PLANES_RGB, "RGB", 0, "RGB", "Images are saved with RGB (color) data"},
    {R_IMF_PLANES_RGBA, "RGBA", 0, "RGBA", "Images are saved with RGB and Alpha data (if supported)"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 241 of file rna_scene.c.
EnumPropertyItem image_only_type_items[]
Initial value:
 {
    IMAGE_TYPE_ITEMS_IMAGE_ONLY
    {0, NULL, 0, NULL, NULL}}
Definition at line 203 of file rna_scene.c.
EnumPropertyItem image_type_items[]
Definition at line 209 of file rna_scene.c.
Referenced by rna_def_image().
EnumPropertyItem mesh_select_mode_items[]
Initial value:
 {
    {SCE_SELECT_VERTEX, "VERTEX", ICON_VERTEXSEL, "Vertex", "Vertex selection mode"},
    {SCE_SELECT_EDGE, "EDGE", ICON_EDGESEL, "Edge", "Edge selection mode"},
    {SCE_SELECT_FACE, "FACE", ICON_FACESEL, "Face", "Face selection mode"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 109 of file rna_scene.c.
EnumPropertyItem proportional_editing_items[]
Initial value:
 {
    {PROP_EDIT_OFF, "DISABLED", ICON_PROP_OFF, "Disable", "Proportional Editing disabled"},
    {PROP_EDIT_ON, "ENABLED", ICON_PROP_ON, "Enable", "Proportional Editing enabled"},
    {PROP_EDIT_CONNECTED, "CONNECTED", ICON_PROP_CON, "Connected",
                          "Proportional Editing using connected geometry only"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 101 of file rna_scene.c.
Referenced by Transform_Properties().
EnumPropertyItem proportional_falloff_items[]
Initial value:
 {
    {PROP_SMOOTH, "SMOOTH", ICON_SMOOTHCURVE, "Smooth", "Smooth falloff"},
    {PROP_SPHERE, "SPHERE", ICON_SPHERECURVE, "Sphere", "Spherical falloff"},
    {PROP_ROOT, "ROOT", ICON_ROOTCURVE, "Root", "Root falloff"},
    {PROP_SHARP, "SHARP", ICON_SHARPCURVE, "Sharp", "Sharp falloff"},
    {PROP_LIN, "LINEAR", ICON_LINCURVE, "Linear", "Linear falloff"},
    {PROP_CONST, "CONSTANT", ICON_NOCURVE, "Constant", "Constant falloff"},
    {PROP_RANDOM, "RANDOM", ICON_RNDCURVE, "Random", "Random falloff"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 90 of file rna_scene.c.
Referenced by Transform_Properties().
EnumPropertyItem snap_element_items[]
Initial value:
 {
    {SCE_SNAP_MODE_INCREMENT, "INCREMENT", ICON_SNAP_INCREMENT, "Increment", "Snap to increments of grid"},
    {SCE_SNAP_MODE_VERTEX, "VERTEX", ICON_SNAP_VERTEX, "Vertex", "Snap to vertices"},
    {SCE_SNAP_MODE_EDGE, "EDGE", ICON_SNAP_EDGE, "Edge", "Snap to edges"},
    {SCE_SNAP_MODE_FACE, "FACE", ICON_SNAP_FACE, "Face", "Snap to faces"},
    {SCE_SNAP_MODE_VOLUME, "VOLUME", ICON_SNAP_VOLUME, "Volume", "Snap to volume"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 115 of file rna_scene.c.
Referenced by TRANSFORM_OT_snap_type().
EnumPropertyItem snap_target_items[]
Initial value:
 {
    {SCE_SNAP_TARGET_CLOSEST, "CLOSEST", 0, "Closest", "Snap closest point onto target"},
    {SCE_SNAP_TARGET_CENTER, "CENTER", 0, "Center", "Snap center onto target"},
    {SCE_SNAP_TARGET_MEDIAN, "MEDIAN", 0, "Median", "Snap median onto target"},
    {SCE_SNAP_TARGET_ACTIVE, "ACTIVE", 0, "Active", "Snap active onto target"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 83 of file rna_scene.c.
Referenced by Transform_Properties().
EnumPropertyItem uv_sculpt_relaxation_items[]
Initial value:
 {
    {UV_SCULPT_TOOL_RELAX_LAPLACIAN, "LAPLACIAN", 0, "Laplacian", "Use Laplacian method for relaxation"},
    {UV_SCULPT_TOOL_RELAX_HC, "HC", 0, "HC", "Use HC method for relaxation"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 71 of file rna_scene.c.
EnumPropertyItem uv_sculpt_tool_items[]
Initial value:
 {
    {UV_SCULPT_TOOL_PINCH, "PINCH", 0, "Pinch", "Pinch UVs"},
    {UV_SCULPT_TOOL_RELAX, "RELAX", 0, "Relax", "Relax UVs"},
    {UV_SCULPT_TOOL_GRAB, "GRAB", 0, "Grab", "Grab UVs"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 76 of file rna_scene.c.
Referenced by BRUSH_OT_uv_sculpt_tool_set().