Blender: NM_Scalar.h File Reference
NM_Scalar.h File Reference
moto
#include <math.h>
#include <iostream>
Classes
class NM_Scalar< T >
Functions
template<class T >
NM_Scalar< T > operator+ (const NM_Scalar< T > &x, const NM_Scalar< T > &y)
template<class T >
NM_Scalar< T > operator- (const NM_Scalar< T > &x, const NM_Scalar< T > &y)
template<class T >
NM_Scalar< T > operator* (const NM_Scalar< T > &x, const NM_Scalar< T > &y)
template<class T >
NM_Scalar< T > operator/ (const NM_Scalar< T > &x, const NM_Scalar< T > &y)
template<class T >
std::ostream & operator<< (std::ostream &os, const NM_Scalar< T > &x)
template<class T >
NM_Scalar< T > sqrt (const NM_Scalar< T > &x)
template<class T >
NM_Scalar< T > acos (const NM_Scalar< T > &x)
template<class T >
NM_Scalar< T > cos (const NM_Scalar< T > &x)
template<class T >
NM_Scalar< T > sin (const NM_Scalar< T > &x)
template<class T >
NM_Scalar< T > fabs (const NM_Scalar< T > &x)
template<class T >
NM_Scalar< T > pow (const NM_Scalar< T > &x, const NM_Scalar< T > &y)
Detailed Description
Definition in file NM_Scalar.h.
Function Documentation
template<class T > NM_Scalar<T> acos (const NM_Scalar< T > & x) [inline]
Definition at line 135 of file NM_Scalar.h.
References NM_Scalar< T >::getError(), and NM_Scalar< T >::getValue().
Referenced by MT_Vector3::angle(), MT_Vector2::angle(), MT_Quaternion::angle(), AngleBetween(), camera_params_from_object(), damptrack_evaluate(), DirectionToThetaPhi(), do_math(), EvalTspace(), findzero(), interp_qt_qtqt(), node_shader_exec_math(), p_vec_angle(), quat_to_axis_angle(), RotationBetween(), saacos(), saacos_d(), safe_acos(), MT_Quaternion::slerp(), splineik_evaluate_bone(), stitch_island_calculate_edge_rotation(), stitch_island_calculate_vert_rotation(), AUD_SoftwareDevice::AUD_SoftwareHandle::update(), valuefn(), and view3d_align_axis_to_vector().
template<class T > NM_Scalar<T> cos (const NM_Scalar< T > & x) [inline]
Definition at line 140 of file NM_Scalar.h.
References NM_Scalar< T >::getError(), and NM_Scalar< T >::getValue().
Referenced by add_render_lamp(), AngleBetween(), axis_angle_to_mat3(), axis_angle_to_quat(), BKE_text_to_curve(), BM_face_interp_from_face(), BM_loop_interp_from_face(), BM_vert_interp_from_face(), BMBVH_NewBVH(), bmo_vertexsmooth_exec(), buildchar(), KX_Dome::CalculateCameraOrientation(), ccgdm_getVertCos(), cloth_calc_helper_forces(), curve_getKeyVertexCos(), curve_getVertexCos(), ntlMatrix4x4< Scalar >::decompose(), btMatrix3x3::diagonalize(), do_kink(), do_material_tex(), do_math(), doEdgeSplit(), doMirrorOnAxis(), draw_pose_dofs(), ED_mesh_uv_loop_reset_ex(), ED_view3d_lock(), editbmesh_get_vertex_cos(), equirectangular_to_direction(), eul_to_mat3(), eul_to_mat4(), eulO_to_mat3(), eulO_to_quat(), EulToMat3(), KX_OrientationInterpolator::Execute(), extrawindow_spin_cursor(), fcm_fn_generator_evaluate(), fglow(), FHT(), find_next_pano_slice(), findzero(), KX_Dome::FlattenDome(), RAS_OpenGLRasterizer::FlushDebugShapes(), followpath_get_tarmat(), fresnel_dielectric(), gearGL(), genTangSpace(), MT_Matrix3x3::getEuler(), ParticleTracer::getTriangles(), ntlMatrix4x4< Scalar >::initRotationX(), ntlMatrix4x4< Scalar >::initRotationY(), ntlMatrix4x4< Scalar >::initRotationZ(), ControlParticles::initTimeArray(), knife_edge_tri_isect(), knife_make_chain_cut(), KX_ConstraintActuator::KX_ConstraintActuator(), magic(), makeBokeh(), makeshadowbuf(), mat3_to_quat_is_ok(), mesh_getVertexCos(), mul_fac_qt_fl(), ndof_orbit_invoke(), node_composit_exec_rotate(), node_shader_exec_math(), node_update_hidden(), ob_parcurve(), p_abf_compute_sines(), p_chart_rotate_minimum_area(), partial_doughnut(), GHOST_WindowWin32::processWin32TabletEvent(), project_renderdata(), psys_make_billboard(), radial_control_set_initial_mouse(), MTRand::randNorm(), MT_Vector3::random(), MT_Quaternion::random(), RE_inithalo(), RE_inithalo_particle(), AUD_LowpassFactory::recalculateCoefficients(), AUD_HighpassFactory::recalculateCoefficients(), rotate(), rotate_m4(), rotate_normalized_v3_v3v3fl(), RotationMatrix(), MT_Quaternion::setEuler(), MT_Matrix3x3::setEuler(), MT_Quaternion::setRotation(), shapekey_layers_to_keyblocks(), simpleDeform_bend(), simpleDeform_twist(), sphere_sampler(), spin_nurb(), stabilization_auto_scale_factor(), stitch_uv_rotate(), streaks(), transform_image(), tri_to_quat(), ui_draw_but_HSVCIRCLE(), IK_QSwingSegment::UpdateAngle(), IK_QSphericalSegment::UpdateAngle(), IK_QElbowSegment::UpdateAngleApply(), uv_map_rotation_matrix(), valuefn(), vec_rot_to_mat3(), vec_rot_to_quat(), vec_to_quat(), viewnumpad_exec(), vieworbit_exec(), viewrotate_apply(), and Warp().
template<class T > NM_Scalar<T> fabs (const NM_Scalar< T > & x) [inline]
Definition at line 150 of file NM_Scalar.h.
References fabs(), NM_Scalar< T >::getError(), and NM_Scalar< T >::getValue().
template<class T > NM_Scalar<T> operator* (const NM_Scalar< T > & x, const NM_Scalar< T > & y) [inline]
Definition at line 112 of file NM_Scalar.h.
References NM_Scalar< T >::getError(), and NM_Scalar< T >::getValue().
template<class T > NM_Scalar<T> operator+ (const NM_Scalar< T > & x, const NM_Scalar< T > & y) [inline]
Definition at line 92 of file NM_Scalar.h.
References fabs(), NM_Scalar< T >::getError(), and NM_Scalar< T >::getValue().
template<class T > NM_Scalar<T> operator- (const NM_Scalar< T > & x, const NM_Scalar< T > & y) [inline]
Definition at line 102 of file NM_Scalar.h.
References fabs(), NM_Scalar< T >::getError(), and NM_Scalar< T >::getValue().
template<class T > NM_Scalar<T> operator/ (const NM_Scalar< T > & x, const NM_Scalar< T > & y) [inline]
Definition at line 118 of file NM_Scalar.h.
References NM_Scalar< T >::getError(), and NM_Scalar< T >::getValue().
template<class T > std::ostream& operator<< (std::ostream & os, const NM_Scalar< T > & x) [inline]
Definition at line 124 of file NM_Scalar.h.
template<class T > NM_Scalar<T> pow (const NM_Scalar< T > & x, const NM_Scalar< T > & y) [inline]
Definition at line 155 of file NM_Scalar.h.
References fabs(), NM_Scalar< T >::getError(), and NM_Scalar< T >::getValue().
Referenced by _final_goal(), accum_density(), area_lamp_energy_multisample(), brush_add(), brush_comb(), brush_cut(), brush_gen_radial_control_imbuf(), brush_puff(), calc_cb(), cloth_apply_vgroup(), color_scene_linear_to_srgb(), color_srgb_to_scene_linear(), convertTo(), AUD_EnvelopeFactory::createReader(), distribute_threads_exec(), do_clump(), do_kink(), do_math(), do_physical_effector(), do_rough_end(), double_round(), drawlamp(), dynamicPaint_doWaveStep(), Eigenhqr2(), Eigentql2(), falloff_func(), fb(), fbderiv(), gammaCorrect(), gamtabs(), ntlLightObject::getShadedColor(), invGammaCorrect(), make_sep_waveform_view_from_ibuf_byte(), make_sep_waveform_view_from_ibuf_float(), make_vectorscope_view_from_ibuf_byte(), make_vectorscope_view_from_ibuf_float(), make_waveform_view_from_ibuf_byte(), make_waveform_view_from_ibuf_float(), makeGammaTables(), Minnaert_Diff(), multires_load_old_dm(), node_shader_exec_math(), node_shader_exec_squeeze(), noise_musgrave_fBm(), noise_musgrave_hetero_terrain(), noise_musgrave_hybrid_multi_fractal(), noise_musgrave_multi_fractal(), noise_musgrave_ridged_multi_fractal(), power_of_2(), psys_cache_edit_paths(), psys_render_simplify_distribution(), psys_render_viewport_falloff(), psys_threads_init_path(), QMC_samplePhong(), RE_zbuf_accumulate_vecblur(), LbmFsgrSolver::recalculateObjectSpeeds(), rect_bevel_side(), render_new_particle_system(), sample_occ_cache(), sculpt_brush_test_cube(), ControlParticles::setInfluenceVelocity(), shade_lamp_loop(), soft_range_round_down(), soft_range_round_up(), static_particle_strand(), step_to_grid(), strand_eval_width(), strand_shade_segment(), streaks(), surfaceGenerateGrid(), TNT::SVD(), tonemap(), IsoSurface::triangulate(), ui_get_but_scale_unit(), AUD_SoftwareDevice::AUD_SoftwareHandle::update(), valuefn(), view3d_smoothview_invoke(), and voronoi_distance().
template<class T > NM_Scalar<T> sin (const NM_Scalar< T > & x) [inline]
Definition at line 145 of file NM_Scalar.h.
References NM_Scalar< T >::getError(), and NM_Scalar< T >::getValue().
Referenced by add_render_lamp(), AngleBetween(), axis_angle_to_mat3(), axis_angle_to_quat(), BKE_text_to_curve(), buildchar(), calc_bevel_sin_cos(), KX_Dome::CalculateCameraOrientation(), MeanValueMeshCoords::computeWeights(), defocus_blur(), btMatrix3x3::diagonalize(), do_kink(), do_material_tex(), do_math(), draw_pose_dofs(), ED_mesh_uv_loop_reset_ex(), ED_view3d_lock(), equirectangular_to_direction(), eul_to_mat3(), eul_to_mat4(), eulO_to_mat3(), eulO_to_quat(), EulToMat3(), KX_OrientationInterpolator::Execute(), extrawindow_spin_cursor(), fcm_fn_generator_evaluate(), find_next_pano_slice(), KX_Dome::FlattenDome(), RAS_OpenGLRasterizer::FlushDebugShapes(), followpath_get_tarmat(), gearGL(), ParticleTracer::getTriangles(), ntlMatrix4x4< Scalar >::initRotationX(), ntlMatrix4x4< Scalar >::initRotationY(), ntlMatrix4x4< Scalar >::initRotationZ(), ControlParticles::initTimeArray(), interp_qt_qtqt(), KX_ConstraintActuator::KX_ConstraintActuator(), magic(), makeBokeh(), makeshadowbuf(), mat3_to_quat_is_ok(), mul_fac_qt_fl(), ndof_orbit_invoke(), NewTestMesh(), node_composit_exec_rotate(), node_shader_exec_math(), node_update_hidden(), noise_wave(), ob_parcurve(), p_abf_compute_sines(), p_chart_lscm_solve(), p_chart_rotate_minimum_area(), partial_doughnut(), GHOST_WindowWin32::processWin32TabletEvent(), project_renderdata(), psys_make_billboard(), quat_to_axis_angle(), radial_control_set_initial_mouse(), MT_Vector3::random(), MT_Quaternion::random(), RE_inithalo(), RE_inithalo_particle(), AUD_SinusReader::read(), AUD_LowpassFactory::recalculateCoefficients(), AUD_HighpassFactory::recalculateCoefficients(), rotate(), rotate_m4(), rotate_normalized_v3_v3v3fl(), RotationMatrix(), MT_Quaternion::setEuler(), MT_Matrix3x3::setEuler(), IK_QSwingSegment::SetLimit(), IK_QSphericalSegment::SetLimit(), MT_Quaternion::setRotation(), simpleDeform_bend(), simpleDeform_twist(), sinc(), MT_Quaternion::slerp(), sphere_sampler(), spin_nurb(), stabilization_auto_scale_factor(), stitch_uv_rotate(), streaks(), tex_sin(), transform_image(), tri_to_quat(), ui_draw_but_HSVCIRCLE(), IK_QSwingSegment::UpdateAngle(), IK_QSphericalSegment::UpdateAngle(), IK_QElbowSegment::UpdateAngleApply(), uv_map_rotation_matrix(), valuefn(), vec_rot_to_mat3(), vec_rot_to_quat(), vec_to_quat(), viewnumpad_exec(), vieworbit_exec(), viewrotate_apply(), and Warp().
template<class T > NM_Scalar<T> sqrt (const NM_Scalar< T > & x) [inline]
Definition at line 129 of file NM_Scalar.h.
References NM_Scalar< T >::getError(), and NM_Scalar< T >::getValue().
Referenced by accum_density(), LbmFsgrSolver::adaptTimestep(), add_in_range(), MT_Vector3::angle(), MT_Vector2::angle(), MT_Quaternion::angle(), approximate_Rd_rgb(), armature_circle_doSelectJoint(), arrayModifier_doArray(), AUD_readSound(), bgl_sphere_project(), blend(), BLI_jitterate1(), BLI_kdtree_find_n_nearest(), BLI_kdtree_find_nearest(), Blinn_Spec(), bm_corners_to_loops(), BM_face_multires_bounds_smooth(), bm_loop_interp_mdisps(), bm_loop_reverse_loop(), bokeh_single_image(), brightness_standard_deviation(), brush_cut(), brush_edit_apply(), brush_gen_radial_control_imbuf(), bspface_init_strand(), build_Rd_table(), buildNormal(), C_Matrix_OrthoProjection(), C_Matrix_Scale(), calc_bevel_sin_cos(), calc_weight(), calcSpringFactor(), calctrackballvec(), calculate_speedvectors(), calculate_strandsurface_speedvectors(), Parametrizer::calculateAllMissingValues(), calculatePropRatio(), cg_filtered(), check_zone(), TNT::Cholesky_upper_factorization(), cloth_calc_spring_force(), compress_shadowbuf(), btConeTwistConstraint::computeConeLimitInfo(), computeEigenvalues3x3(), ComputeSwingMatrix(), MeanValueMeshCoords::computeWeights(), curvemap_make_table(), defocus_blur(), IsoSurface::diffuseVertexField(), direction_to_mirrorball(), dist_to_line_segment_v2(), dist_to_line_v2(), do_clay_brush(), do_distance_matte(), do_fill_brush(), do_filter_edge(), do_flatten_brush(), do_kink(), do_physical_effector(), do_scrape_brush(), dquat_to_mat4(), draw_ghost_poses(), draw_ghost_poses_keys(), draw_ghost_poses_range(), edgetag_cut_cost(), Eigenhqr2(), Eigenorthes(), Eigentred2(), EllipseClamp(), EulerAngleFromMatrix(), f_Rd(), fcm_fn_generator_evaluate(), FHT(), find_next_part(), findzero(), LbmFsgrSolver::fineAdvance(), KX_Dome::FlattenDome(), fresnel(), fresnel_dielectric(), gamma_correct_compbuf(), gamtabs(), gearGL(), get_avg_speed(), get_matrix_editbone(), LbmFsgrSolver::getLesNoneqTensorCoeff(), LbmFsgrSolver::getLesOmega(), getLowestRoot(), BasicVector::getNormalized(), getNormalized(), btConeTwistConstraint::GetPointForAngle(), MT_Matrix3x3::getRotation(), HC_relaxation_iteration_uv(), TNT::hypot(), hypot(), IMB_filter_extend(), init_frame_smoke(), init_mv_jit(), LbmFsgrSolver::initializeSolverMemory(), InputAngle(), InputCustomRatio(), InputSpring(), isect_line_sphere_v2(), isect_line_sphere_v3(), key_inside_circle(), Kx_Normalize(), lamp_get_visibility(), laplacian_relaxation_iteration_uv(), lasso_inside(), latticecurve_circle_doSelect(), LbmFsgrSolver::LbmFsgrSolver(), MT_Vector4::length(), MT_Vector3::length(), MT_Vector2::length(), AUD_Vector3::length(), load_fluidsimspeedvectors(), lookat_m4(), make_jitter_weight_tab(), makeraytree(), marble_int(), mat3_to_eul2(), mat3_to_eulo2(), mat3_to_quat(), Mat3ToEulOld(), mesh_calc_ngon_normal(), mesh_calc_ngon_normal_coords(), mesh_circle_doSelectFace(), mesh_circle_doSelectVert(), mirrorball_to_direction(), mistfactor(), my_boundbox_mesh(), nearest_fcurve_vert_store(), nextLengthSubdivision(), BasicVector::norm(), norm(), BasicVector::normalize(), Projections::normalize(), normalize(), Normalize_d(), normalize_qt(), normalize_v3_d(), normalize_vn_vn(), KX_Camera::NormalizeClipPlanes(), nurbscurve_circle_doSelect(), old_mdisps_convert(), ortho_basis_v3v3_v3(), p_edge_length(), p_edge_uv_length(), p_face_stretch(), p_smooth(), param_average(), param_pack(), pchan_circle_doSelectJoint(), point_behind_strand(), psys_render_projected_area(), psys_render_simplify_distribution(), TNT::pythag(), QMC_sampleDisc(), QMC_sampleHemi(), QMC_samplePhong(), TNT::QR_factor(), quad_coord(), Quaternion_magnitude_get(), radial_control_modal(), MTRand::randNorm(), MT_Vector3::random(), MT_Quaternion::random(), RandomSpherical(), ray_shadow_jitter(), Rd_rsquare(), RE_make_stars(), RE_rayobject_octree_done(), RE_zbuf_accumulate_vecblur(), refract(), BasicVector::refractVector(), refractVector(), render_lighting_halo(), resolve_quad_uv(), sasqrt(), sculpt_brush_test(), sculpt_update_cache_variants(), IK_QJacobian::SetDoFWeight(), IK_QTask::SetWeight(), shade_by_transmission(), shadeHaloFloat(), smoke_step(), iTaSC::WSDLSSolver::solve(), SphericalRangeParameters(), spothalo(), static_particle_strand(), WTURBULENCE::stepTurbulenceFull(), strand_eval_point(), stretchto_evaluate(), TNT::SVD(), FilterNormal::tFilter(), ui_do_animate(), ui_fontscale(), ui_hsvcircle_vals_from_pos(), ui_item_rna_size(), ui_numedit_but_NORMAL(), SCA_RandomActuator::Update(), AUD_SoftwareDevice::AUD_SoftwareHandle::update(), iTaSC::Armature::updateJoint(), uv_sculpt_stroke_apply(), uv_sculpt_stroke_init(), vec_to_quat(), Vector_angle(), Vector_length_get(), Vector_length_set(), view3d_sample_backbuf_rect(), viewzoom_apply(), voronoi_distance(), warpModifier_do(), weightvg_do_map(), and DocumentImporter::writeLight().