Blender: BL_MeshDeformer Class Reference
BL_MeshDeformer Class Reference
#include <BL_MeshDeformer.h>
Public Member Functions
void VerifyStorage ()
void RecalcNormals ()
virtual void Relink (CTR_Map< class CTR_HashedPtr, void * > *map)
BL_MeshDeformer (BL_DeformableGameObject *gameobj, struct Object *obj, class RAS_MeshObject *meshobj)
virtual ~BL_MeshDeformer ()
virtual void SetSimulatedTime (double time)
virtual bool Apply (class RAS_IPolyMaterial *mat)
virtual bool Update (void)
virtual bool UpdateBuckets (void)
virtual RAS_Deformer * GetReplica ()
virtual void ProcessReplica ()
struct Mesh * GetMesh ()
virtual class RAS_MeshObject * GetRasMesh ()
virtual float(* GetTransVerts (int *tot))[3]
Protected Attributes
class RAS_MeshObject * m_pMeshObject
struct Mesh * m_bmesh
float(* m_transverts)[3]
float(* m_transnors)[3]
struct Object * m_objMesh
int m_tvtot
BL_DeformableGameObject * m_gameobj
double m_lastDeformUpdate
Detailed Description
Definition at line 47 of file BL_MeshDeformer.h.
Constructor & Destructor Documentation
BL_MeshDeformer::BL_MeshDeformer (BL_DeformableGameObject * gameobj, struct Object * obj, class RAS_MeshObject * meshobj) [inline]
Definition at line 53 of file BL_MeshDeformer.h.
BL_MeshDeformer::~BL_MeshDeformer () [virtual]
Definition at line 85 of file BL_MeshDeformer.cpp.
References m_transnors, and m_transverts.
Member Function Documentation
bool BL_MeshDeformer::Apply (class RAS_IPolyMaterial * mat) [virtual]
Implements RAS_Deformer.
Reimplemented in BL_ModifierDeformer, and BL_SkinDeformer.
Definition at line 51 of file BL_MeshDeformer.cpp.
References RAS_MeshSlot::begin(), MVert::co, RAS_MeshSlot::end(), RAS_MeshSlot::iterator::endvertex, RAS_MeshObject::GetFirstMaterial(), BL_DeformableGameObject::GetLastFrame(), RAS_MeshObject::GetLastMaterial(), RAS_TexVert::getOrigIndex(), i, m_bmesh, m_gameobj, m_lastDeformUpdate, m_pMeshObject, RAS_MeshObject::MeshModified(), Mesh::mvert, RAS_MeshSlot::next(), RAS_TexVert::SetXYZ(), RAS_MeshSlot::iterator::startvertex, and RAS_MeshSlot::iterator::vertex.
struct Mesh* BL_MeshDeformer::GetMesh () [inline, read]
Definition at line 72 of file BL_MeshDeformer.h.
References m_bmesh.
virtual class RAS_MeshObject* BL_MeshDeformer::GetRasMesh () [inline, virtual]
Reimplemented from RAS_Deformer.
Definition at line 73 of file BL_MeshDeformer.h.
References m_pMeshObject.
virtual RAS_Deformer* BL_MeshDeformer::GetReplica (void) [inline, virtual]
Implements RAS_Deformer.
Reimplemented in BL_ModifierDeformer, BL_ShapeDeformer, and BL_SkinDeformer.
Definition at line 70 of file BL_MeshDeformer.h.
References NULL.
virtual float(* BL_MeshDeformer::GetTransVerts (int * tot))[3] [inline, virtual]
Reimplemented from RAS_Deformer.
Definition at line 74 of file BL_MeshDeformer.h.
References m_transverts, and m_tvtot.
void BL_MeshDeformer::ProcessReplica () [virtual]
Implements RAS_Deformer.
Reimplemented in BL_ModifierDeformer, BL_ShapeDeformer, and BL_SkinDeformer.
Definition at line 93 of file BL_MeshDeformer.cpp.
References RAS_Deformer::m_bDynamic, m_lastDeformUpdate, m_transnors, m_transverts, m_tvtot, and NULL.
void BL_MeshDeformer::RecalcNormals ()
Warning:
This function is expensive!
Definition at line 115 of file BL_MeshDeformer.cpp.
References RAS_MeshSlot::iterator::array, RAS_MeshSlot::begin(), RAS_MeshSlot::end(), RAS_MeshSlot::iterator::endvertex, RAS_TexVert::FLAT, RAS_MeshObject::GetFirstMaterial(), RAS_TexVert::getFlag(), RAS_MeshObject::GetLastMaterial(), RAS_TexVert::getOrigIndex(), i, RAS_MeshSlot::iterator::index, m_bmesh, m_gameobj, m_pMeshObject, m_transnors, m_transverts, RAS_DisplayArray::m_type, RAS_MeshSlot::next(), normalize_v3(), NULL, RAS_TexVert::SetNormal(), RAS_MeshSlot::iterator::startvertex, RAS_MeshSlot::iterator::totindex, Mesh::totvert, and RAS_MeshSlot::iterator::vertex.
Referenced by BL_SkinDeformer::BlenderDeformVerts(), and BL_ShapeDeformer::Update().
void BL_MeshDeformer::Relink (CTR_Map< class CTR_HashedPtr, void * > * map) [virtual]
Implements RAS_Deformer.
Reimplemented in BL_SkinDeformer.
Definition at line 102 of file BL_MeshDeformer.cpp.
References m_gameobj, and NULL.
virtual void BL_MeshDeformer::SetSimulatedTime (double time) [inline, virtual]
Definition at line 66 of file BL_MeshDeformer.h.
virtual bool BL_MeshDeformer::Update (void) [inline, virtual]
Implements RAS_Deformer.
Reimplemented in BL_ModifierDeformer, BL_ShapeDeformer, and BL_SkinDeformer.
Definition at line 68 of file BL_MeshDeformer.h.
virtual bool BL_MeshDeformer::UpdateBuckets (void) [inline, virtual]
Implements RAS_Deformer.
Reimplemented in BL_SkinDeformer.
Definition at line 69 of file BL_MeshDeformer.h.
void BL_MeshDeformer::VerifyStorage ()
Definition at line 225 of file BL_MeshDeformer.cpp.
References m_bmesh, m_transnors, m_transverts, m_tvtot, and Mesh::totvert.
Referenced by BL_ShapeDeformer::Update(), and BL_SkinDeformer::UpdateInternal().
Member Data Documentation
struct Mesh* BL_MeshDeformer::m_bmesh [protected]
Definition at line 79 of file BL_MeshDeformer.h.
Referenced by Apply(), BL_SkinDeformer::BGEDeformVerts(), BL_ShapeDeformer::BL_ShapeDeformer(), BL_SkinDeformer::BlenderDeformVerts(), BL_ShapeDeformer::GetKey(), GetMesh(), BL_ModifierDeformer::GetPhysicsMesh(), RecalcNormals(), BL_ShapeDeformer::SetKey(), BL_ModifierDeformer::Update(), BL_ShapeDeformer::Update(), BL_SkinDeformer::UpdateInternal(), VerifyStorage(), and BL_ShapeDeformer::~BL_ShapeDeformer().
BL_DeformableGameObject* BL_MeshDeformer::m_gameobj [protected]
Definition at line 88 of file BL_MeshDeformer.h.
Referenced by BL_SkinDeformer::Apply(), Apply(), BL_ModifierDeformer::Apply(), BL_ModifierDeformer::GetPhysicsMesh(), RecalcNormals(), Relink(), BL_ModifierDeformer::Update(), and BL_ShapeDeformer::Update().
double BL_MeshDeformer::m_lastDeformUpdate [protected]
Definition at line 89 of file BL_MeshDeformer.h.
Referenced by Apply(), and ProcessReplica().
struct Object* BL_MeshDeformer::m_objMesh [protected]
Definition at line 85 of file BL_MeshDeformer.h.
Referenced by BL_SkinDeformer::BGEDeformVerts(), and BL_SkinDeformer::BlenderDeformVerts().
class RAS_MeshObject* BL_MeshDeformer::m_pMeshObject [protected]
Definition at line 78 of file BL_MeshDeformer.h.
Referenced by BL_SkinDeformer::Apply(), BL_ModifierDeformer::Apply(), Apply(), GetRasMesh(), RecalcNormals(), and BL_ShapeDeformer::Update().
float(* BL_MeshDeformer::m_transnors)[3] [protected]
Definition at line 84 of file BL_MeshDeformer.h.
Referenced by BL_SkinDeformer::Apply(), BL_SkinDeformer::BGEDeformVerts(), ProcessReplica(), RecalcNormals(), BL_SkinDeformer::UpdateInternal(), VerifyStorage(), and ~BL_MeshDeformer().
float(* BL_MeshDeformer::m_transverts)[3] [protected]
Definition at line 83 of file BL_MeshDeformer.h.
Referenced by BL_SkinDeformer::Apply(), BL_SkinDeformer::BGEDeformVerts(), BL_SkinDeformer::BlenderDeformVerts(), BL_ModifierDeformer::GetPhysicsMesh(), GetTransVerts(), ProcessReplica(), RecalcNormals(), BL_ModifierDeformer::Update(), BL_ShapeDeformer::Update(), BL_SkinDeformer::UpdateInternal(), VerifyStorage(), and ~BL_MeshDeformer().
int BL_MeshDeformer::m_tvtot [protected]
Definition at line 87 of file BL_MeshDeformer.h.
Referenced by GetTransVerts(), ProcessReplica(), and VerifyStorage().
The documentation for this class was generated from the following files:
BL_MeshDeformer.h
BL_MeshDeformer.cpp